### ISSUE TITLE
add `vcpkg remove --force-depends <package>`

### ISSUE THREAD

**Issue by rkitover** [microsoft/vcpkg#10000]
It should be possible to remove a package without anything that depends on it if you intend to immediately reinstall it or rebuild it in any other way.

`vcpkg remove --force-depends <some-package>` would remove just the package and not any of its dependencies.

**Comment by linquize** [comment]
What is the difference between `vcpkg remove --recurse <package>` and your idea ?

**Comment by rkitover** [comment]
`--recurse` will also remove packages that depend on the listed package, while `--force-depends` would remove only the listed package and break any packages that depend on it, until it is reinstalled or provided in some other way.

**Comment by linquize** [comment]
Do you want to save time: Avoid recompile all other packages?

**Comment by rkitover** [comment]
Sure, for example, wxwidgets depends on libtiff, if I'm just reinstalling libtiff I don't want to recompile wxwidgets, which is very big.

There are various reasons why someone may want to do this. They may just be upgrading a package, or recompiling it with different options flags, etc..

**Comment by rkitover** [comment]
In my own experiments I found an issue that will complicate implementing this.

If a dependency of a package is removed, the core considers the database corrupted.

For example, I get this message:

```
Error: database corrupted. Package sfml:x64-windows-static is installed but dependency freetype:x64-windows-static is not.
```

This would need to be fixed to allow at the very least reinstalling the missing dependency.

**Comment by rkitover** [comment]
Even better if vcpkg could operate normally with missing dependencies and just print a loud warning or something.

**Comment by Sweepi** [comment]
On the same note, would it be possible to add
vcpkg rebuild <package>
vcpkg reinstall <package>
?

**Comment by JackBoosY** [comment]
I think we should not do this because it will break the dependencies stored in vcpkg and cause the lack of these dependencies when building other ports in the future.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
