### ISSUE TITLE
libssh 0.9.3 not work due to missing threading in mbedtls

### ISSUE THREAD

**Issue by linquize** [microsoft/vcpkg#10012]
**Describe the bug**
with libssh 0.9.3 in vcpkg
`./vcpkg install libssh`

Then write a program to call libssh. When it runs, libssh shows error to stderr.

Windows: `DllMain: ssh_init failed!`
Linux: `Error in auto_init()`

**Environment**
- OS: Windows and Linux
- Compiler: Windows: MSVC2019, Linux: gcc 9

**To Reproduce**
1. ./vcpkg install libssh
2. Then write a program to call libssh. 
3. When it runs, libssh shows error to stderr.

```c
int main(int argc, char **argv)
{
    ssh_init();
    ssh_session my_ssh_session = ssh_new();
    if (my_ssh_session == NULL)
        return -1;

    const char* host = "localhost";
    ssh_options_set(my_ssh_session, SSH_OPTIONS_HOST, host);
    ssh_options_set(my_ssh_session, SSH_OPTIONS_USER, "user");
    int rc = ssh_connect(my_ssh_session);
    return 0;
}
```

**Expected behavior**
No error

**Additional context**
The problem seems to be in `mbedtls`. Need to enable threading library in mbedtls.

Patch `include/mbedtls/config.h`

In all platforms,
`#define MBEDTLS_THREADING_C`
In Windows,
`#define MBEDTLS_THREADING_ALT`
In other platforms,
`#define MBEDTLS_THREADING_PTHREAD`

Create `include/mbedtls/threading_alt.h`
define the type `mbedtls_threading_mutex_t`

Then recompile `mbedtls`, then recompile `libssh`.
The error goes away.

**Comment by timautry** [comment]
Instructions on how to configure mbedtls for use with libssh are detailed here:
**https://tls.mbed.org/kb/compiling-and-building/how-do-i-configure-mbedtls**
