### ISSUE TITLE
[fcl] update to 0.6.0

### ISSUE THREAD

**Issue by traversaro** [microsoft/vcpkg#10013]
Library name: 
* fcl ( flexible-collision-library)

New version number: 
* 0.6.0

Other information that may be useful (release notes, etc...):
* https://github.com/flexible-collision-library/fcl/issues/331
* https://github.com/flexible-collision-library/fcl/releases/tag/v0.6.0

As this release has several breaking changes, probably it is important to check if ports that depend on fcl (as `ompl`) works fine with the new version before upgrading.

**Comment by PhoebeHui** [comment]
@traversaro, thanks for the information! the PR has been merged, please get vcpkg latest source and try again.
