### ISSUE TITLE
[New Port Request]  Dynamic Animation and Robotics Toolkit (DART)

### ISSUE THREAD

**Issue by traversaro** [microsoft/vcpkg#10015]
Library name: Dynamic Animation and Robotics Toolkit (DART)

Library description: DART (Dynamic Animation and Robotics Toolkit) is a collaborative, cross-platform, open source library that provides data structures and algorithms for kinematic and dynamic applications in robotics and computer animation. 

Source repository URL: https://github.com/dartsim/dart

Project homepage (if different from the source repository): http://dartsim.github.io/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
* Repology: https://repology.org/project/dart/versions and https://repology.org/project/dartsim/versions
* Debian package: https://packages.debian.org/source/sid/dart
* Homebrew Formula: https://formulae.brew.sh/formula/dartsim
* Third-party port repository, ready to be imported: https://github.com/jslee02/vcpkg-dart

**Comment by Spirit532** [comment]
Was about to create a request for this. Definitely a good candidate to be added into vcpkg!

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
