### ISSUE TITLE
[libmariadb] build failure

### ISSUE THREAD

**Issue by OlafvdSpek** [microsoft/vcpkg#10024]
**Host Environment**
- OS: Windows 10
- Compiler: MSVC 16.5.0 preview 2

**To Reproduce**
`./vcpkg install libmariadb`

**Failure logs** 
```
PS C:\vc\vcpkg> ./vcpkg install libmariadb                                                                              Computing installation plan...
The following packages will be built and installed:
    libmariadb[core]:x86-windows
Starting package 1/1: libmariadb:x86-windows
Building package libmariadb[core]:x86-windows...
-- Using cached C:/vc/vcpkg/downloads/MariaDB-mariadb-connector-c-8e9c3116105d9a998a60991b7f4ba910d454d4b1.tar.gz
-- Extracting source C:/vc/vcpkg/downloads/MariaDB-mariadb-connector-c-8e9c3116105d9a998a60991b7f4ba910d454d4b1.tar.gz
-- Applying patch md.patch
CMake Error at scripts/cmake/vcpkg_apply_patches.cmake:52 (message):
  Applying patch failed.  Patch needs to be updated to work with source being
  used by vcpkg!
Call Stack (most recent call first):
  scripts/cmake/vcpkg_extract_source_archive_ex.cmake:134 (vcpkg_apply_patches)
  scripts/cmake/vcpkg_from_github.cmake:139 (vcpkg_extract_source_archive_ex)
  ports/libmariadb/portfile.cmake:8 (vcpkg_from_github)
  scripts/ports.cmake:90 (include)


Error: Building package libmariadb:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libmariadb:x86-windows
  Vcpkg version: 2020.02.04-nohash

Additionally, attach any relevant sections from the log files above.
```

**Comment by JackBoosY** [comment]
Confirmed.

**Comment by taadams1** [comment]
I am experiencing the same issue with the x64 package
`$ .\\vcpkg install libmariadb:x64-windows
Computing installation plan...
The following packages will be built and installed:
    libmariadb[core]:x64-windows
Starting package 1/1: libmariadb:x64-windows
Building package libmariadb[core]:x64-windows...
-- Using cached C:/Users/admin/otclient_test/vcpkg/downloads/MariaDB-mariadb-connector-c-8e9c3116105d9a998a60991b7f4ba910d454d4b1.tar.gz
-- Extracting source C:/Users/admin/otclient_test/vcpkg/downloads/MariaDB-mariadb-connector-c-8e9c3116105d9a998a60991b7f4ba910d454d4b1.tar.gz
-- Applying patch md.patch
CMake Error at scripts/cmake/vcpkg_apply_patches.cmake:50 (message):
  Applying patch failed.  Patch needs to be updated to work with source being
  used by vcpkg!
Call Stack (most recent call first):
  scripts/cmake/vcpkg_extract_source_archive_ex.cmake:134 (vcpkg_apply_patches)
  scripts/cmake/vcpkg_from_github.cmake:139 (vcpkg_extract_source_archive_ex)
  ports/libmariadb/portfile.cmake:8 (vcpkg_from_github)
  scripts/ports.cmake:90 (include)


Error: Building package libmariadb:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libmariadb:x64-windows
  Vcpkg version: 2020.02.04-nohash

Additionally, attach any relevant sections from the log files above.
`

**Comment by JackBoosY** [comment]
@taadams1 Could you try my PR #10043 changes?

**Comment by mikhael4ever** [comment]
same here Error: Building package libmariadb:x64-windows failed with: BUILD_FAILED

**Comment by JackBoosY** [comment]
Hi @mikhael4ever, could you use #10043 changes?

**Comment by mikhael4ever** [comment]
Hello, @JackBoosY, what i need to change ?

I have changed red by green one #10043  in files chanded:

`CONTROL and md.patch from C:\vcpkg\ports\libmariadb`

But nothing changed, same error:

```
Starting package 1/1: libmariadb:x64-windows
Building package libmariadb[core]:x64-windows...
CMake Error at ports/libmariadb/portfile.cmake:3 (message):
  FATAL ERROR: libmysql and libmariadb are incompatible.
Call Stack (most recent call first):
  scripts/ports.cmake:90 (include)


Error: Building package libmariadb:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libmariadb:x64-windows
  Vcpkg version: 2020.02.04-nohash

Additionally, attach any relevant sections from the log files above.

C:\vcpkg>
```

**Comment by mikhael4ever** [comment]
I downloaded all again and now i get this error, when i try to install it again:

```
The following packages are already installed:
    boost-asio[core]:x64-windows
    boost-filesystem[core]:x64-windows
    boost-iostreams[core]:x64-windows
    boost-lockfree[core]:x64-windows
    boost-system[core]:x64-windows
    boost-variant[core]:x64-windows
    cryptopp[core]:x64-windows
    libmariadb[core]:x64-windows
    luajit[core]:x64-windows
    mpir[core]:x64-windows
    pugixml[core]:x64-windows
Package boost-iostreams:x64-windows is already installed
Package boost-asio:x64-windows is already installed
Package boost-filesystem:x64-windows is already installed
Package boost-lockfree:x64-windows is already installed
Package boost-system:x64-windows is already installed
Package boost-variant:x64-windows is already installed
Package cryptopp:x64-windows is already installed
Package libmariadb:x64-windows is already installed
Package luajit:x64-windows is already installed
Package mpir:x64-windows is already installed
Package pugixml:x64-windows is already installed

Total elapsed time: 4.116 ms

The package cryptopp:x64-windows provides CMake targets:

    find_package(cryptopp CONFIG REQUIRED)
    target_link_libraries(main PRIVATE cryptopp-static)

The package pugixml:x64-windows provides CMake targets:

    find_package(pugixml CONFIG REQUIRED)
    target_link_libraries(main PRIVATE pugixml)


C:\vcpkg>

```

**Comment by OlafvdSpek** [comment]
@mikhael4ever What's the error / problem?

**Comment by mikhael4ever** [comment]
> @mikhael4ever What's the error / problem?

Hello,

Whats that mean ?

`The package cryptopp:x64-windows provides CMake targets:

    find_package(cryptopp CONFIG REQUIRED)
    target_link_libraries(main PRIVATE cryptopp-static)

The package pugixml:x64-windows provides CMake targets:

    find_package(pugixml CONFIG REQUIRED)
    target_link_libraries(main PRIVATE pugixml)`

**Comment by OlafvdSpek** [comment]
It explains how you can use those packages if you're using cmake.

**Comment by mikhael4ever** [comment]
> It explains how you can use those packages if you're using cmake.

Oh, ok ty!

I get this one:

```
C:\vcpkg>.\vcpkg integrate install
Applied user-wide integration for this vcpkg root.

All MSBuild C++ projects can now #include any installed libraries.
Linking will be handled automatically.
Installing new libraries will make them instantly available.

CMake projects should use: "-DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake"

C:\vcpkg>
```

Do you know how can i do that:

`CMake projects should use: "-DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake"`

**Comment by JackBoosY** [comment]
@mikebmcl That's not a error, it's a usage message.
For integration, please see [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/users/integration.md).

**Comment by JackBoosY** [comment]
Close this issue via #10177 merged.

**Comment by mikhael4ever** [comment]
> @mikebmcl That's not a error, it's a usage message.
> For integration, please see [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/users/integration.md).

ok, ty, ill check it right now! :D
