### ISSUE TITLE
[<vtk>] build failure with QTOpenGLWidget

### ISSUE THREAD

**Issue by jafrado** [microsoft/vcpkg#10027]
**Host Environment**
- OS: Windows 10
- Compiler: VS 2019 (MSVC 19.24.28314.0)

**To Reproduce**
`./vcpkg install vtk[opengl]`

**Failure logs** 
-Unable to build/link any application which uses QVTKOpenGLWidget
-Sample application which exhibits the problem here: https://github.com/jafrado/QVTKOpenGLWidget

**Additional context**
I already have a fix for this issue, at a minimum it requires adding -DvtkGUISupportQtOpenGL=ON to the VTK_WITH_QT stanza in ports/vtk/portfile.cmake. Optimally, this should be a separate build feature. I have both, and can push the changes.

**Comment by jafrado** [comment]
Add pull request https://github.com/microsoft/vcpkg/pull/10060 with fixes.

**Comment by NancyLi1013** [comment]
Hi @jafrado 
Have you tried the latest version? `opengl `has been added for `vtk`. 
Can this current version work for you?
Thanks.

**Comment by jafrado** [comment]
yes, that part works. But PCL is not working with this version of VTK,
unfortunately it needs some more work. However, the issue is resolved.

**Comment by NancyLi1013** [comment]
Thanks for your reply. 
Since this issue is solved, I'm closing it for now.
You can open a new issue if there is another problem.
