### ISSUE TITLE
[vxl] build failure

### ISSUE THREAD

**Issue by timautry** [microsoft/vcpkg#10029]
**Host Environment**
- OS: [Windows 10 Pro Version 1909 (OS Build 18363.657) ]
- Compiler: VS 2017 v15.9.19 and VS2019 v16.4.4

**To Reproduce**
.\vcpkg.exe install vxl[core,core_imaging]:x64-windows

Building package vxl[core,core_imaging]:x64-windows...
CMake Warning at ports/vxl/portfile.cmake:8 (message):
  Can't build VXL CORE_IMAGING features with non built-in OpenJpeg.  Please
  remove OpenJpeg, and try install VXL again if you need them.
Call Stack (most recent call first):
  scripts/ports.cmake:90 (include)

-- Using cached E:/Git/vcpkg.downloads/vxl-vxl-dac1c7ed8e183e9c6de8b928c8b0294a7bd1d8ee.tar.gz
-- Extracting source E:/Git/vcpkg.downloads/vxl-vxl-dac1c7ed8e183e9c6de8b928c8b0294a7bd1d8ee.tar.gz
-- Applying patch fix_dependency.patch
-- Using source at D:/Git/vs2019.prod/buildtrees/vxl/src/4a7bd1d8ee-c80aa455d1
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v
    Working Directory: D:/Git/vs2019.prod/buildtrees/vxl/x64-windows-dbg
    See logs for more information:
      D:\Git\vs2019.prod\buildtrees\vxl\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/vxl/portfile.cmake:50 (vcpkg_install_cmake)
  scripts/ports.cmake:90 (include)

Error: Building package vxl:x64-windows failed with: BUILD_FAILED
Elapsed time for package vxl:x64-windows: 43.74 s

**Failure logs** 
Attached "install-x64-windows-dbg-out.log"
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/4189288/install-x64-windows-dbg-out.log)

**Additional context**
I first got the message about "fix_dependcy.patch" needing to be updated:
-- Applying patch fix_dependency.patch
CMake Error at scripts/cmake/vcpkg_apply_patches.cmake:52 (message):
  **Applying patch failed.  Patch needs to be updated to work with source being
  used by vcpkg!**
Call Stack (most recent call first):
  scripts/cmake/vcpkg_extract_source_archive_ex.cmake:134 (vcpkg_apply_patches)
  scripts/cmake/vcpkg_from_github.cmake:139 (vcpkg_extract_source_archive_ex)
  ports/libmariadb/portfile.cmake:8 (vcpkg_from_github)
  scripts/ports.cmake:90 (include)

So I created a **new patch** to work with the **new source** - attached as fix_dependency.patch.txt.

[fix_dependency.patch.txt](https://github.com/microsoft/vcpkg/files/4189284/fix_dependency.patch.txt)

**Comment by LilyWangL** [comment]
Related issue #3911
