### ISSUE TITLE
Not able to compile vcpkg on Azure DevOps Microsoft hosted agent

### ISSUE THREAD

**Issue by kenr** [microsoft/vcpkg#10023]
**Describe the bug**
vcpkg does not compile on Azure DevOps Microsoft hosted agent.

**Environment**
- OS: Windows / Azure DevOps Microsoft hosted agent [windows-latest](https://github.com/actions/virtual-environments/blob/master/images/win/Windows2019-Readme.md)
- Compiler: VisualStudio/16.4.4+29728.190

**To Reproduce**
1. Checkout master branch of vcpkg
2. Invoke bootstrap.bat
3. Compilation fails (see attachment)

**Expected behavior**
A built version of vcpkg

**Failure logs** 
[20200211-vcpkg-build-failure.txt](https://github.com/microsoft/vcpkg/files/4185694/20200211-vcpkg-build-failure.txt)

**Comment by kenr** [comment]
@PhoebeHui are you not able to reproduce it?

**Comment by PhoebeHui** [comment]
@kenr, thanks for reporting this issue.

However, I can't repro this issue with latest vcpkg and visual studio 16.4.5 and 16.5 preview 2.

**Comment by kenr** [comment]
@PhoebeHui Sorry, my mistake! I was using an old fork of vcpkg, using master from Microsoft it compiles. I guess this is the same as issue #9982
