### ISSUE TITLE
[libpq & libpqxx] Requires debug/release postfix string on x64-windows

### ISSUE THREAD

**Issue by Lewis123d** [microsoft/vcpkg#10034]
vcpkg version:  2020.02.04-nohash
execute cmd: install libpqxx:x64-windows and succeed
output files includes
debug:
libpq.pdb/dll/lib
libpqxxd.pdb/dll/lib 
other dependency files, ex: libcrypto,libssl .etc

release:
libpq.pdb/dll/lib
libpqxx.pdb/dll/lib 
other dependency files, ex: libcrypto,libssl .etc

How to modify portfile.cmake, CMakeList.txt or other config files and vcpkg will output following files(not rename the file directly)?

debug:
libpq-x64-d.pdb/dll/lib
libpqxx-x64-d.pdb/dll/lib 
other dependency files, ex: libcrypto,libssl .etc

release:
libpq-x64.pdb/dll/lib
libpqxx-x64.pdb/dll/lib 
other dependency files, ex: libcrypto,libssl .etc

**Comment by Neumann-A** [comment]
From https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md

>**Do not rename binaries outside the names given by upstream**
This means that if the upstream library has different names in release and debug (libx versus libxd), then the debug library should not be renamed to libx. Vice versa, if the upstream library has the same name in release and debug, we should not introduce a new name.

**Comment by Lewis123d** [comment]
For my case, I want to separate two different libraries into debug and release(even x64 and x86 .etc).
Now libpqxx meet my requirement.
Please see this file: ports/libpqxx/CMakeLists.txt
line 4: set(CMAKE_DEBUG_POSTFIX "d")

BUT libpq does NOT.
No matter debug or release mode, the library name is always the same: libpq.pdb/dll/lib.
So, is there any solutions to figure out it?

**Comment by Neumann-A** [comment]
>I want to separate two different libraries into debug and release(even x64 and x86 .etc).

use folders instead of names...e.g.
`x86/rel/` vs `x86/dbg/` or
`x64/rel/` vs `x64/dbg/`

vcpkg also uses different folders to separate debug/release libraries. e.g. `/lib` vs `/debug/lib `

**Comment by Lewis123d** [comment]
Hi @NancyLi1013 
Is any solution to meet my requirement?

**Comment by NancyLi1013** [comment]
Hi @Lewis123d 
Thanks for posting this issue.
Sorry for the late reply.
Since `libpq `is not built with `cmake`.
We cannot use `set(CMAKE_DEBUG_POSTFIX "d")` to implement this.
I also checked `libpq` source code. But I have no idea about this.

**Comment by Neumann-A** [comment]
Even if libpq would use CMake we should not add the debug suffix unless the original author does it in his CMakeList.txt. (there are some exception to that but thats a different issue)

**Comment by NancyLi1013** [comment]
@Lewis123d 
As @Neumann-A  said above, we should not introduce a new name if the upstream library has the same name in release and debug.
https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#useful-implementation-notes
So in this case, we should keep the original name.

**Comment by NancyLi1013** [comment]
Please post this issue to upstream if you still need to add the debug suffix.
We will update this port once upstream accept it. Before this, we will keep it as now.
