### ISSUE TITLE
[openssl-windows] Static build fail

### ISSUE THREAD

**Issue by manugc** [microsoft/vcpkg#10033]
**Host Environment**
- OS: Windows 10
- Compiler: MSVC 2019

**To Reproduce**
`./vcpkg install openssl-windows:x86-windows-static`

**Failure logs** 
All logs are correct.

**Additional context**
When finished building in the installed folder, only debug with the html folder appears. Do not copy the necessary files

**Comment by huargovfx** [comment]
I am having a similar issue with windows 7 and MSVC 2015, it builds for a while and later stops, it shows as half installed only. I can't get openimageio built because of this.

**Comment by LilyWangL** [comment]
@manugc Thanks for posting this issue. Does this issue occur? I installed `openssl-windows:x86-windows-static` successfully on Visual Studio 2019 and the latest VCPKG source. If you still build failed, please provide the install log.

**Comment by manugc** [comment]
@LilyWangL Hi, the problem I have detected is that it does not copy the package files to installed. It just generates the debug / html folder. Build without errors but do not move files.

[build-x86-windows-static-rel-1-out.log](https://github.com/microsoft/vcpkg/files/4392951/build-x86-windows-static-rel-1-out.log)

**Comment by LilyWangL** [comment]
@manugc Sorry I am late. Could you provide more detail about the package files? Which files you need in your project?

**Comment by manugc** [comment]
Hi @LilyWangL. Yesterday I saw the commit https://github.com/microsoft/vcpkg/commit/8be5365d739a31f07c2125b07ce1bf47a01cd555 
and try to build. Now everything is correct.
For my part you can close the bug

**Comment by LilyWangL** [comment]
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.
