### ISSUE TITLE
[folly] update to latest

### ISSUE THREAD

**Issue by z6833** [microsoft/vcpkg#10045]
Library name: folly:x64-windows

New version number: latest

Other information that may be useful (release notes, etc...):
Hello, thanks for your help of updating `fizz` #9724 .  I want to install project `mvfst` on windows7, and it relies on `fizz` and `folly` . I have installed updated version of `fizz` by vcpkg , and it works . But it still has problems of `folly` . I installed it by commands `./vcpkg install folly:x64-windows` . The information of errors show that maybe `folly` need to be update . Could you please update `folly` to latest version ?

**Comment by LilyWangL** [comment]
The new version build failed due to a compiler bug in MSVC 19.22.27905, this will be fixed in newer releases. The related source issue: https://github.com/facebook/folly/issues/1324

**Comment by z6833** [comment]
Do you mean that I should update my visiual studio ? Or updating the `vcpkg`?

**Comment by LilyWangL** [comment]
> Do you mean that I should update my visiual studio ? Or updating the `vcpkg`?

This issue need wait the Visual Studio newer releases.

**Comment by z6833** [comment]
Hello, I tried to compile `mvfst` with the latest version of `visual studio` . And It seems that did not work well . Errors are the same as before . I tried to analysize the errors , most of them  were resulted by 'folly' , so I consider that weather the version of `folly` resulted in these problems .
Information about the compilers followed
[Info_compiler.txt](https://github.com/microsoft/vcpkg/files/4402431/Info_compiler.txt). And information about `Errors`
![error_list_1](https://user-images.githubusercontent.com/33688513/77909039-2dbe7d00-72bf-11ea-9825-0237dec4d8f1.PNG)
![error_list_2](https://user-images.githubusercontent.com/33688513/77909071-3b740280-72bf-11ea-928e-28e49b46750a.PNG)

**Comment by z6833** [comment]
I contrasts the codes of folly::asyncUDPSocket in version v2019-10-21 with version of the latest . And I found that the function writemGSO was not defined in v2019.10.21, which was found in the latest version. So I  doubt that the version of folly port results my problems . Could you please update the version of folly , or tell me how I could do that myself ？
![捕获](https://user-images.githubusercontent.com/33688513/77979399-2a66d800-7337-11ea-85c0-2d6ef46d6bfd.PNG)
![捕获2](https://user-images.githubusercontent.com/33688513/77979407-2fc42280-7337-11ea-8869-4f5d03a52bd3.PNG)
![捕获3](https://user-images.githubusercontent.com/33688513/77979418-33f04000-7337-11ea-86e0-8f2288d60c36.PNG)

**Comment by LilyWangL** [comment]
I try to install folly 2020.03.30.00 on Visual Studio 2019 16.5.0, and I install failed with the error:
```
D:\PROJECTS\vcpkg\buildtrees\folly\src\head\master-98bc7b42e7\folly/SharedMutex.h(1644): error C2783: 'folly::atomic_ref<T> folly::make_atomic_ref_t::operator ()(T &) const': could not deduce template argument for '__formal'
D:\PROJECTS\vcpkg\buildtrees\folly\src\head\master-98bc7b42e7\folly/synchronization/AtomicRef.h(104): note: see declaration of 'folly::make_atomic_ref_t::operator ()'
D:\PROJECTS\vcpkg\buildtrees\folly\src\head\master-98bc7b42e7\folly/SharedMutex.h(1669): error C2672: 'operator __surrogate_func': no matching overloaded function found
D:\PROJECTS\vcpkg\buildtrees\folly\src\head\master-98bc7b42e7\folly/SharedMutex.h(1669): error C2783: 'folly::atomic_ref<T> folly::make_atomic_ref_t::operator ()(T &) const': could not deduce template argument for '__formal'
D:\PROJECTS\vcpkg\buildtrees\folly\src\head\master-98bc7b42e7\folly/synchronization/AtomicRef.h(104): note: see declaration of 'folly::make_atomic_ref_t::operator ()'
D:\PROJECTS\vcpkg\buildtrees\folly\src\head\master-98bc7b42e7\folly/SharedMutex.h(1721): error C2672: 'operator __surrogate_func': no matching overloaded function found
D:\PROJECTS\vcpkg\buildtrees\folly\src\head\master-98bc7b42e7\folly/SharedMutex.h(1721): error C2783: 'folly::atomic_ref<T> folly::make_atomic_ref_t::operator ()(T &) const': could not deduce template argument for '__formal'
```
You can modify the version in CONTROL and portfile.cmake like this:
```
Source: folly
Version: 2020.03.30.00
Homepage: https://github.com/facebook/folly
```
```
vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO facebook/folly
    REF 278c88d5a323e94927e58d3d371067896dcbc796 #v2020.03.30.00
    SHA512 8571fe1d396a9553885d9645d84b03288dbe3686552ca556a3fda2a180370911e96bc36d2e0e411fa193034e03dce31e71075d14eab2e9339fe820fb9dd9fc61
    HEAD_REF master
    PATCHES
        missing-include-atomic.patch
        reorder-glog-gflags.patch
        disable-non-underscore-posix-names.patch
        boost-1.70.patch
)
```

**Comment by z6833** [comment]
I modified `vcpkg/ports/folly/CONTROL` and `portfile.cmake` accoding to your advice . I got the `dismatch error`. details:
[folly-install-log.txt](https://github.com/microsoft/vcpkg/files/4420424/folly-install-log.txt)

![01](https://user-images.githubusercontent.com/33688513/78240027-0363fe00-7511-11ea-8b24-966004aaa2d7.PNG)
![2](https://user-images.githubusercontent.com/33688513/78240034-05c65800-7511-11ea-96aa-edc03027a715.PNG)
![3](https://user-images.githubusercontent.com/33688513/78240040-08c14880-7511-11ea-8f89-5c56de6fbe18.PNG)

**Comment by LilyWangL** [comment]
Due to apply the patch failed, folly build failed. Updating folly to new version need fix the old patches, you could add the patch changes to the source files and comment the patch code in portfile.cmake.

**Comment by chllcy** [comment]
VS2019 and windows 10
vcpkg install folly:x64-windows --head
how can fix this problem?
the folly version:"url": "https://api.github.com/repos/facebook/folly/git/commits/0938cf4150a97143125ac892303a90cef7ad2254"
--------------------------------------------------------------------------------------------------
D:\github\vcpkg\buildtrees\folly\src\head\master-0820c1f591\folly/lang/Pretty.h(89): warning C4686: 'folly::detail::pretty_carray_from': possible change in behavior, change in UDT return calling convention
D:\github\vcpkg\buildtrees\folly\src\head\master-0820c1f591\folly/SharedMutex.h(1644): error C2672: 'operator __surrogate_func': no matching overloaded function found

D:\github\vcpkg\buildtrees\folly\src\head\master-0820c1f591\folly/SharedMutex.h(404): note: while compiling class template member function 'void folly::SharedMutexImpl<false,void,std::atomic,false,false>::lock_shared(folly::SharedMutexImpl<false,void,std::atomic,false,false>::Token &)'
D:\github\vcpkg\buildtrees\folly\src\head\master-0820c1f591\folly/SharedMutex.h(1340): note: see reference to function template instantiation 'void folly::SharedMutexImpl<false,void,std::atomic,false,false>::lock_shared(folly::SharedMutexImpl<false,void,std::atomic,false,false>::Token &)' being compiled
D:\github\vcpkg\buildtrees\folly\src\head\master-0820c1f591\folly/SharedMutex.h(1549): note: see reference to class template instantiation 'folly::SharedMutexImpl<false,void,std::atomic,false,false>' being compiled
D:\github\vcpkg\buildtrees\folly\src\head\master-0820c1f591\folly/SharedMutex.h(1644): error C2783: 'folly::atomic_ref<T> folly::make_atomic_ref_t::operator ()(T &) const': could not deduce template argument for '__formal'
D:\github\vcpkg\buildtrees\folly\src\head\master-0820c1f591\folly/synchronization/AtomicRef.h(104): note: see declaration of 'folly::make_atomic_ref_t::operator ()'
D:\github\vcpkg\buildtrees\folly\src\head\master-0820c1f591\folly/SharedMutex.h(1669): error C2672: 'operator __surrogate_func': no matching overloaded function found
D:\github\vcpkg\buildtrees\folly\src\head\master-0820c1f591\folly/SharedMutex.h(1669): error C2783: 'folly::atomic_ref<T> folly::make_atomic_ref_t::operator ()(T &) const': could not deduce template argument for '__formal'
D:\github\vcpkg\buildtrees\folly\src\head\master-0820c1f591\folly/synchronization/AtomicRef.h(104): note: see declaration of 'folly::make_atomic_ref_t::operator ()'
D:\github\vcpkg\buildtrees\folly\src\head\master-0820c1f591\folly/SharedMutex.h(1721): error C2672: 'operator __surrogate_func': no matching overloaded function found
D:\github\vcpkg\buildtrees\folly\src\head\master-0820c1f591\folly/SharedMutex.h(1721): error C2783: 'folly::atomic_ref<T> folly::make_atomic_ref_t::operator ()(T &) const': could not deduce template argument for '__formal'

**Comment by z6833** [comment]
> Due to apply the patch failed, folly build failed. Updating folly to new version need fix the old patches, you could add the patch changes to the source files and comment the patch code in portfile.cmake.
@LilyWangL   sorry to bother you again.  I am not sure I understand your words well, I have tried to search those packages relied on `folly` , and seems to get into a big mess . I can not find which packaes to modify . I wonder if it would be convenient for you to update version of folly ?

**Comment by PhoebeHui** [comment]
Folly has been upgrade to latest revision by PR https://github.com/microsoft/vcpkg/pull/13701, please get latest source and try again.
