### ISSUE TITLE
[librtmp] build failure

### ISSUE THREAD

**Issue by kiokju** [microsoft/vcpkg#10047]
**Host Environment**
- OS: [ Windows]
- Compiler: revision 2020.02.04

**To Reproduce**
`./vcpkg install librtmp:x64-windows`

**Failure logs** 
-CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: C:/msys64/usr/bin/git.exe fetch https://git.ffmpeg.org/rtmpdump c5f04a58fc2aeea6296ca7c44ee4734c18401aa3 --depth 1 -n
    Working Directory: D:/programs/vcpkg/downloads/git-tmp
    Error code: 3328
    See logs for more information:
      D:\programs\vcpkg\buildtrees\librtmp\git-fetch-x64-windows-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_git.cmake:82 (vcpkg_execute_required_process)
  ports/librtmp/portfile.cmake:3 (vcpkg_from_git)
  scripts/ports.cmake:90 (include)

Error: Building package librtmp:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: librtmp:x64-windows
  Vcpkg version: 2020.02.04-nohash

Additionally, attach any relevant sections from the log files above.

-C:/msys64/usr/lib/git-core/git-remote-https.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory

**Comment by NancyLi1013** [comment]
Hi @kiokju thanks for posting this issue.
Could you please provide the log here` D:\programs\vcpkg\buildtrees\librtmp\git-fetch-x64-windows-err.log` ?
It seems that there is something wrong with git on your local. 
Could you check and try it again?

**Comment by kiokju** [comment]
[git-fetch-x64-windows-err.log](https://github.com/microsoft/vcpkg/files/4202074/git-fetch-x64-windows-err.log)

**Comment by NancyLi1013** [comment]
Could you please check if you have added `C:/msys64/usr/bin` and `git `to Path ?
Please also confirm if git can work normally on your local.
I can build this port successfully on my local.

**Comment by NancyLi1013** [comment]
Does this issue exist now?

**Comment by kiokju** [comment]
No. It is same. 

(And I checked  added git execute path "C:/msys64/usr/bin").

**Comment by NancyLi1013** [comment]
I'm not sure what happened on your local git. 
Could you try to use the git that vcpkg provides? 

If vcpkg cannot detect a suitable git version, it will download it that vcpkg provides.

```
PS F:\vcpkg> .\vcpkg.exe install librtmp
Computing installation plan...
The following packages will be built and installed:
    librtmp[core]:x86-windows
Starting package 1/1: librtmp:x86-windows
Building package librtmp[core]:x86-windows...
A suitable version of git was not found (required v2.21.0). Downloading portable git v2.21.0...
Extracting git...
-- Fetching https://git.ffmpeg.org/rtmpdump...
-- Extracting source F:/vcpkg/downloads/librtmp-c5f04a58fc2aeea6296ca7c44ee4734c18401aa3.tar.gz
-- Applying patch dh.patch
-- Applying patch handshake.patch
-- Applying patch hashswf.patch
-- Applying patch fix_strncasecmp.patch
-- Applying patch hide_netstackdump.patch
-- Using source at F:/vcpkg/buildtrees/librtmp/src/4c18401aa3-8fdbdf4b55
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Installing: F:/vcpkg/packages/librtmp_x86-windows/share/librtmp/copyright
-- Installing: F:/vcpkg/packages/librtmp_x86-windows/share/librtmp/librtmp.3.html
-- Performing post-build validation done
Building package librtmp[core]:x86-windows... done
Installing package librtmp[core]:x86-windows...
Installing package librtmp[core]:x86-windows... done
Elapsed time for package librtmp:x86-windows: 42.05 s

Total elapsed time: 42.05 s
```

**Comment by kiokju** [comment]
I re-install MSYS2. and work fine!!

Thanks.

**Comment by NancyLi1013** [comment]
Thanks for your update.
