### ISSUE TITLE
[Freetype] Removal of Harfbuzz causes Ubuntu build failure on linking of project using Freetype.

### ISSUE THREAD

**Issue by RubyNova** [microsoft/vcpkg#10041]
**Describe the bug**
While Freetype itself builds fine, linkage into an actual project causes a build failure. Specifically, it is looking for harfbuzz-related objects, which naturally cannot be found as of #9888 .

**Environment**
- OS: Linux (Ubuntu 18.04)
- Compiler: vcpkg dependencies - g++8, linking project - Clang 8.0.1

**To Reproduce**
1. Set up a Ubuntu instance that does not have, or depend on, Harfbuzz as a core OS library (so no GNOME, for example).
1. Install Freetype (./vcpkg install freetype).
2. Link to Freetype in an application.
3. Observe the issue when performing a build of said application.

**Expected behavior**
The build should be succeeding without Harfbuzz, assumedly, based on the aforementioned PR.

**Failure logs** 
Relevant AzDO logs: https://dev.azure.com/NovelRT/NovelRT/_build/results?buildId=352&view=logs&j=7657cd23-e7c8-5f16-3eca-368b7743e6ae&t=cee3d295-27f3-503f-0cb1-8f6ca694b184

**Additional context**
Please note that Windows is completely unaffected.

Since this happened on an AzDO machine and based on further testing, it came to light that installing freetype via vcpkg like this may cause it to rely on the local copy of harfbuzz that comes with Ubuntu as of 16.04 LTS, which is probably not the intended behaviour. This also suggests that Freetype still has a dependency on harfbuzz somewhere.

Please also note that I am certain it is the Harfbuzz changes due to the fact NovelRT is built daily on the master branch, and the last succeeding build for it was before #9888 was merged. It was fine before this.

Linked is the PR in which this failure first occured, should you require it: 
https://github.com/novelrt/NovelRT/pull/126

**Comment by tannergooding** [comment]
Looking at https://github.com/microsoft/vcpkg/pull/9706 vs https://github.com/microsoft/vcpkg/pull/9888, there are various lines that were explicitly excluding harfbuzz before which weren't added back in 9888.

**Comment by PhoebeHui** [comment]
@tannergooding, thanks for reporting this issue.

PR#9888 remove harfbuzz feature from freetype, due to we already have port harfbuzz which depend on freetype. If not remove that feature, then freetype depend on harfbuzz, harfbuzz depend on freetype, it become circle, and will fail with issue https://github.com/microsoft/vcpkg/issues/9850.

The solution here might need to add 'harfbuzz' to the project when it used.
     find_package(harfbuzz CONFIG REQUIRED)
    target_link_libraries(main PRIVATE harfbuzz::harfbuzz)

**Comment by tannergooding** [comment]
Sure, but I was pointing out that prior to #9706 (which added the optional support for harfbuzz) FreeType was built with the following two options (always): https://github.com/microsoft/vcpkg/pull/9706/files#diff-8921d681f7afa53cf4fb11cc2d46aab8L35-L36

After 9706, you could optionally enable it; but that caused the issue reported in https://github.com/microsoft/vcpkg/issues/9850 (and no issue if disabled).

In https://github.com/microsoft/vcpkg/pull/9888, you removed the support for enabling harfbuzz, but didn't add back in the lines that prevented it from building as part of freetype (which looks to be causing the issue @RubyNova logged).

**Comment by PhoebeHui** [comment]
@tannergooding, thanks for clarifying this.

However, I checked the freetype which already disabled harfbuzz by default.  I'm not  sure why it still build here.
 
option(FT_WITH_HARFBUZZ "Improve auto-hinting of OpenType fonts." OFF)

**Comment by capnkenny** [comment]
@PhoebeHui I was able to test your suggestion on our CI build and found that it succeeded when we included `-DCMAKE_DISABLE_FIND_PACKAGE_HarfBuzz=TRUE` as well as the line you suggested as listed here:
https://github.com/capnkenny/vcpkg/blob/master/ports/freetype/portfile.cmake#L41

Please note that based on the implementation from above, this was only needed for Ubuntu x64 and x86 as the current implementation works as-is for Windows.

**Comment by PhoebeHui** [comment]
@capnkenny, thanks for trying out this!

Would you like to summit a PR? I think only adding '-DCMAKE_DISABLE_FIND_PACKAGE_HarfBuzz=TRUE' that should work.

**Comment by capnkenny** [comment]
Sure thing!

I'll test only including the one line first, then I'll submit a PR with the change.

**Comment by PhoebeHui** [comment]
@RubyNova, the PR has been merged, please get the latest source and try again.

@capnkenny, thanks for your contribution!
