### ISSUE TITLE
bazel build system

### ISSUE THREAD

**Issue by kreuzerkrieg** [microsoft/vcpkg#10058]
Is Bazel supported by vcpkg ports?

**Comment by vicroms** [comment]
If I recall correctly the `tensorflow-cc` port uses Bazel.

**Comment by PhoebeHui** [comment]
It used as a program see https://github.com/microsoft/vcpkg/blob/5deea3b975fe62990973d73a102de818d83ba20c/scripts/cmake/vcpkg_find_acquire_program.cmake#L272

and https://github.com/microsoft/vcpkg/blob/73e55002f1e3e8093431bc1b506d907396bfbf2f/ports/tensorflow-cc/portfile.cmake#L21

**Comment by PhoebeHui** [comment]
@kreuzerkrieg, does this still be a problem for you?

**Comment by kreuzerkrieg** [comment]
Nope. I think I can handle it. Thanks for the assistance
