### ISSUE TITLE
vcpkg.exe is not being created

### ISSUE THREAD

**Issue by saurayi** [microsoft/vcpkg#10059]
**Describe the bug**
vcpkg.exe is not being create when I execute bootstrap-vcpkg.bat

**Environment**
- OS: Windows

**Expected behavior**
Create vcpkg.exe

**Failure logs** 
Nothing...

**Comment by vicroms** [comment]
Hi @saurayi 

Please attach the output of `bootstrap-vcpkg.bat` and elaborate more on your environment.

We've had similar reports in the past and the usual cause is the antivirus software quarantining `vcpkg.exe`.  Do you know if that is the case for you?

**Comment by linquize** [comment]
Which vcpkg commit were used?
Visual Studio version?

**Comment by PhoebeHui** [comment]
@saurayi, does this still be a problem for you? could yu please provide more information?

**Comment by PhoebeHui** [comment]
@saurayi, you can reference https://github.com/microsoft/vcpkg/issues/9704#issuecomment-576414004, please reopen this issue and provide failure logs if it still be a problem for you.
