### ISSUE TITLE
libmariadb build failure - Applying patch failed!!

### ISSUE THREAD

**Issue by YURSHAT** [microsoft/vcpkg#10053]
**Environment**
- OS: Windows 7 Ultimate SP1 (OS Build 7601) x64
- Compiler: VC 2017 v15.9.18 Toolset v141

**To Reproduce**
1. .`/vcpkg install libmariadb`
2. See error
`Error: Building package libmariadb:x86-windows failed with: BUILD_FAILED`

**Failure logs** 
[failure.log](https://github.com/microsoft/vcpkg/files/4198543/failure.log)

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/10024.

**Comment by Derimax3** [comment]
-- Extracting source C:/Users/Adorius Black/vcpkg/downloads/MariaDB-mariadb-connector-c-8e9c3116105d9a998a60991b7f4ba910d454d4b1.tar.gz
-- Applying patch md.patch
CMake Error at scripts/cmake/vcpkg_apply_patches.cmake:50 (message):
  Applying patch failed.  Patch needs to be updated to work with source being
  used by vcpkg!
Call Stack (most recent call first):
  scripts/cmake/vcpkg_extract_source_archive_ex.cmake:134 (vcpkg_apply_patches)
  scripts/cmake/vcpkg_from_github.cmake:139 (vcpkg_extract_source_archive_ex)
  ports/libmariadb/portfile.cmake:8 (vcpkg_from_github)
  scripts/ports.cmake:90 (include)


Error: Building package libmariadb:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libmariadb:x64-windows
  Vcpkg version: 2020.02.04-nohash
