### ISSUE TITLE
You broke libssh win32

### ISSUE THREAD

**Issue by FixVCPkgYouBrokeItAfterJan2020** [microsoft/vcpkg#10054]
After release 2020 January, someone, broke win32 libssh. vcpkg-master and git clone of current code both have a broken libssh on win32. Old code chose openssl as dependency which also has libcrypt - this works. New vcpkg libssh win 32 port chooses mblts(don't think I'm spelling this thrash library correctly or do I care) threads - this is broken.

The problem is inside of crypto_thread_init is broken. It returns SSH_ERROR because it can't understand win32thread string in the compare operation.

Please revert it and ban the programmer from checking in trash again. Thanks. I will not be checking this dead account for responses. My awaited response will be someone will fix current code base today.

**Comment by timautry** [comment]
- If one has an issue with the new port version of libssh, one needs to direct a message to the maintainers at https://www.libssh.org. They would be responsible for the new changes to libssh.
- The maintainers/volunteers working with vcpkg just create the necessary scripts to integrate the ports (like libssh) into vcpkg for the various platforms supported.
- Each portfile.cmake has the location of where each package is retrieved from. Proceeding to the mentioned download location one can find who is responsible for maintaining it and how to contact them.

**Comment by linquize** [comment]
See #10012

**Comment by LilyWangL** [comment]
Thanks for posting this issue. This issue has been fixed in PR #10154, so I am closing this issue for now.
