### ISSUE TITLE
[libpq/libpqxx] Is possible to built-in openssl and zlib?

### ISSUE THREAD

**Issue by BlueeABC** [microsoft/vcpkg#10067]
Is possible to built-in openssl and zlib that I can just only link these two libraries, libpq and libpqxx? 

my environment is Windows and VS2017

**Comment by JackBoosY** [comment]
Hi @BlueeABC, thanks for reporting this issue.
`libpq` and `libpqxx` already have feature `openssl, zlib`, and we want the dependent libraries of each port to use the ones in vcpkg to ensure that the versions match.

**Comment by timautry** [comment]
Yes, just use the following:
->vcpkg install libpq[openssl,zlib] openssl openssl-windows zlib libpqxx 
Computing installation plan...
The following packages will be built and installed:
    libpq[core,openssl,zlib]:x64-windows
    libpqxx[core]:x64-windows
    openssl[core]:x64-windows
    openssl-windows[core]:x64-windows
    zlib[core]:x64-windows

Note: My default triplet is x64-windows, you may need to specify "--triplet x64-windows" if you want 64-bit as I believe the default for vs2017 is x86-windows.

**Comment by JackBoosY** [comment]
Hi @BlueeABC, does this issue resolved?

**Comment by JackBoosY** [comment]
Please reopen this issue if it still bothers you.
