### ISSUE TITLE
[libmariadb] build failure

### ISSUE THREAD

**Issue by guigallo** [microsoft/vcpkg#10079]
**Host Environment**
- OS: Windows 10
- Compiler: Vcpkg version: 2020.02.04-nohash

**To Reproduce**
`vcpkg install libmariadb:x64-windows`

**Failure logs** 

> Computing installation plan...
The following packages will be built and installed:
    libmariadb[core]:x64-windows
Starting package 1/1: libmariadb:x64-windows
Building package libmariadb[core]:x64-windows...
-- Using cached C:/git/vcpkg/downloads/MariaDB-mariadb-connector-c-8e9c3116105d9a998a60991b7f4ba910d454d4b1.tar.gz
-- Extracting source C:/git/vcpkg/downloads/MariaDB-mariadb-connector-c-8e9c3116105d9a998a60991b7f4ba910d454d4b1.tar.gz
-- Applying patch md.patch
CMake Error at scripts/cmake/vcpkg_apply_patches.cmake:50 (message):
  Applying patch failed.  Patch needs to be updated to work with source being
  used by vcpkg!
Call Stack (most recent call first):
  scripts/cmake/vcpkg_extract_source_archive_ex.cmake:134 (vcpkg_apply_patches)
  scripts/cmake/vcpkg_from_github.cmake:139 (vcpkg_extract_source_archive_ex)
  ports/libmariadb/portfile.cmake:8 (vcpkg_from_github)
  scripts/ports.cmake:90 (include)
Error: Building package libmariadb:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libmariadb:x64-windows
  Vcpkg version: 2020.02.04-nohash
Additionally, attach any relevant sections from the log files above.

**Failure logs** 
Already updated with `vcpkg update` and `git pull`

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/10024
