### ISSUE TITLE
boost-compatibility:x86-windows buid failures

### ISSUE THREAD

**Issue by boyd1982** [microsoft/vcpkg#10074]
Package: boost-compatibility:x86-windows
Vcpkg version: 2020.02.04-nohash

**Comment by linquize** [comment]
What problem?

**Comment by boyd1982** [comment]
already settled！ seems to be network problem.


Thank you for the quick response!!


Bo
| |
许博
|
|


|
签名由网易邮箱大师定制
On 2/15/2020 07:39，linquize<notifications@github.com> wrote：

What problem?

**Comment by PhoebeHui** [comment]
@boyd1982, it looks the issue solved? can I close this issue?

**Comment by boyd1982** [comment]
sure,thank you!




| |
许博
邮箱：xubosuper@163.com
|

签名由 网易邮箱大师 定制

On 02/15/2020 19:45, Phoebe wrote:

@boyd1982, it looks the issue solved? can I close this issue?
