### ISSUE TITLE
[mongo-c-driver:x64-linux-dynamic] build failure

### ISSUE THREAD

**Issue by blemidon** [microsoft/vcpkg#10078]
**Host Environment**
- OS: CentOS Linux release 8.1.1911 (Core)
- Compiler: g++ (GCC) 8.3.1 20190507 (Red Hat 8.3.1-4)

**To Reproduce**
`./vcpkg install mongo-c-driver:x64-linux-dynamic --overlay-triplets=custom-triplets`

**Failure logs** 
Building package mongo-c-driver[core]:x64-linux-dynamic... done
Installing package mongo-c-driver[core]:x64-linux-dynamic...
The following files are already installed in /home/imrei/Projects/vcpkg/installed/x64-linux-dynamic and are in conflict with mongo-c-driver:x64-linux-dynamic

Installed by libbson:x64-linux-dynamic
    debug/lib/libbson-1.0.so
    debug/lib/libbson-1.0.so.0
    debug/lib/libbson-1.0.so.0.0.0
    lib/libbson-1.0.so
    lib/libbson-1.0.so.0
    lib/libbson-1.0.so.0.0.0

**Additional context**
custom-triplets/x64-linux-dynamic.cmake 

set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_CMAKE_SYSTEM_NAME Linux)

**Comment by NancyLi1013** [comment]
The triplet ` x64-linux-dynamic` is currently not supported in vcpkg.

**Comment by Darkcacok** [comment]
cmake -DCMAKE_TOOLCHAIN_FILE=/home/test/vcpkg/scripts/buildsystems/vcpkg.cmake ..
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found Freetype: /home/test/vcpkg/installed/x64-linux/lib/libfreetype.a (found version "2.10.1") 
-- Found ZLIB: /home/test/vcpkg/installed/x64-linux/debug/lib/libz.a (found version "1.2.11") 
-- Found BZip2: /home/test/vcpkg/installed/x64-linux/lib/libbz2.a (found version "1.0.6") 
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- Found PNG: /home/test/vcpkg/installed/x64-linux/debug/lib/libpng.a (found version "1.6.37") 
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- Found JPEG: /home/test/vcpkg/installed/x64-linux/debug/lib/libjpeg.a  
CMake Error at /home/test/vcpkg/installed/x64-linux/share/unofficial-nana/unofficial-nana-config.cmake:45 (target_link_libraries):
  Cannot specify link libraries for target "unofficial::nana::nana" which is
  not built by this project.
Call Stack (most recent call first):
  /home/test/vcpkg/scripts/buildsystems/vcpkg.cmake:288 (_find_package)
  CMakeLists.txt:18 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/test/Desktop/724942d43cd11c6ee5b3461ac067c846-e6e86199bd2e7151cd9608dd0719a69daa303243/build/CMakeFiles/CMakeOutput.log".
See also "/home/test/Desktop/724942d43cd11c6ee5b3461ac067c846-e6e86199bd2e7151cd9608dd0719a69daa303243/build/CMakeFiles/CMakeError.log".

**Comment by Darkcacok** [comment]
https://mega.nz/#!G88iiQxS!f5DgGc44RV4yrlHZnrGwZlkuQ7Z3_RJjAEOAx1kjdKU
https://mega.nz/#!vps0jIBZ!d_6jaKA_KtfTbtycMfZwoDLmF0jLexF-6KCVkx7f_IM

**Comment by LilyWangLL** [comment]
This issue hasn’t been updated more than 3 months, if it is still an issue, please reopen this issue.
