### ISSUE TITLE
[glew] incorrect library name in installed cmake helpers with triplet x86-mingw

### ISSUE THREAD

**Issue by 375gnu** [microsoft/vcpkg#10084]
**Describe the bug**
CMake helpers installed by the package (`$vcpkg/installed/$triplet/share/glew/glew-targets-{release,debug}.cmake`) have incorrect library name in *some* cases, at least when it's built for x86-mingw: glew32.a/glew32d.a instead of libglew32.a/libglew32d.a

**Environment**
- OS: GNU/Linux, I suppose the same on Windows
- Compiler: i686-w64-mingw32-gcc (GCC) 8.3-win32 20191201

**To Reproduce**
1. ./vcpkg install glew:x86-mingw
2. use `find_package(GLEW)`

**Expected behavior**
CMake is able to find GLEW libraries.

**Comment by LilyWangLL** [comment]
This issue hasn’t been updated more than 3 months, if it is still an issue, please reopen this issue.
