### ISSUE TITLE
have bug, can't install cpprestsdk

### ISSUE THREAD

**Issue by WangHHY19931001** [microsoft/vcpkg#10081]
system：windows 10
opt：use cmd run "vcpkg install cpprestsdk"
return:
Starting package 1/47: boost-build:x86-windows
Building package boost-build[core]:x86-windows...
-- Using cached C:/vcpkg/downloads/boostorg-build-boost-1.72.0.tar.gz
-- Using source at C:/vcpkg/buildtrees/boost-build/src/ost-1.72.0-fa8b817276
-- Using cached C:/vcpkg/downloads/boost_LICENSE_1_0.txt
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.72.0/boostcpp.jam...
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.72.0/boostcpp.jam... Failed. Status: 35;"SSL connect error"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:175 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  ports/boost-build/portfile.cmake:27 (vcpkg_download_distfile)
  scripts/ports.cmake:90 (include)

Error: Building package boost-build:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-build:x86-windows
  Vcpkg version: 2020.02.04-nohash

Additionally, attach any relevant sections from the log files above.

beacause:
https://raw.githubusercontent.com/boostorg/boost/boost-1.72.0/boostcpp.jam not exists

**Comment by timautry** [comment]
@WangHHY19931001  
- The URL could be blocked somehow by:
   - the site the URL is on was down temporarily
   - a corporate firewall
   - by your ISP 
   - a firewall and/or proxy configuration on your laptop/pc
- You should be able to access the URL **https://raw.githubusercontent.com/boostorg/boost/boost-1.72.0/boostcpp.jam** from an internet browser.

**Comment by LilyWangL** [comment]
Ping @WangHHY19931001

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Please open a new issue if this is still a problem for you.
