### ISSUE TITLE
Suitable version of powershell-core was not found even though vcpkg is launched from pwsh

### ISSUE THREAD

**Issue by patrikhuber** [microsoft/vcpkg#10086]
**Describe the bug**
I launched vcpkg from my powershell 6.2.4. When I launch vcpkg, it complains of missing powershell...:

```
Building package boost-vcpkg-helpers[core]:x64-windows...
A suitable version of powershell-core was not found (required v6.2.1). Downloading portable powershell-core v6.2.1...
Downloading powershell-core...
  https://github.com/PowerShell/PowerShell/releases/download/v6.2.1/PowerShell-6.2.1-win-x86.zip -> D:\vcpkg\downloads\PowerShell-6.2.1-win-x86.zip
```

Even though I am literally **running** vcpkg from pwsh 6.2.4.

**Environment**
- OS: Windows 10, pwsh 6.2.4 64bit, installed from .MSI
- vcpkg updated today (`git pull`) and ran `.\bootstrap_vcpkg.bat`

**Comment by timautry** [comment]
@patrikhuber  See #8975 and #9606 - vcpkg uses its own version of powershell installed in the _vcpkg-root_/downloads/powershell - not the one(s) in the PATH environment variable.

**Comment by patrikhuber** [comment]
@timautry Thanks for linking to those! I've left a comment there.
