### ISSUE TITLE
[liblemon] build failure

### ISSUE THREAD

**Issue by spykermj** [microsoft/vcpkg#10096]
**Host Environment**
- OS: MacOS Catalina
- Compiler: revision (as provided by XCode 11.3.1)

**To Reproduce**
`brew install doxygen`
`./vcpkg install liblemon`

**Failure logs** 

There should be no empty directories in /REDACTED/vcpkg/packages/liblemon_x64-osx
The following empty directories were found:

    /REDACTED/vcpkg/packages/liblemon_x64-osx/share/doc/lemon/html

If a directory should be populated but is not, this might indicate an error in the portfile.
If the directories are not needed and their creation cannot be disabled, use something like this in the portfile to remove them:

    file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/a/dir" "${CURRENT_PACKAGES_DIR}/some/other/dir")

Found 1 error(s). Please correct the portfile:

**Additional context**

Can work around the problem by uninstalling doxygen:
`brew uninstall doxygen`

Or by applying this diff:

~~~~
diff --git a/ports/liblemon/portfile.cmake b/ports/liblemon/portfile.cmake
index 960b09987..76000d9e9 100644
--- a/ports/liblemon/portfile.cmake
+++ b/ports/liblemon/portfile.cmake
@@ -40,6 +40,7 @@ vcpkg_copy_tool_dependencies(${CURRENT_PACKAGES_DIR}/tools/liblemon)
 file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/include)
 file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/share)
 file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/bin ${CURRENT_PACKAGES_DIR}/debug/bin)
+file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/share/doc)
 
 # Handle copyright
 file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/liblemon RENAME copyright)
~~~~
The current master branch commit reference I'm using at the moment is 1be75a28bfce2084bb0b59ec92a6853f13d7be66.

**Comment by NancyLi1013** [comment]
Hi @spykermj 
Thanks for posting this issue.
This issue should be fixed now. Please try to update vcpkg and build it again.
