### ISSUE TITLE
[arrow] update to 0.16.* containing the csv implementations e.g. TableReader

### ISSUE THREAD

**Issue by gisfromscratch** [microsoft/vcpkg#10097]
Library name: arrow

New version number: 0.16.*

I was not able to find the csv implementations for the TableReader like mentioned [here](https://arrow.apache.org/docs/cpp/csv.html), but I can see this on the master branch of version 0.16.*. See [reader.cc](https://github.com/apache/arrow/blob/master/cpp/src/arrow/csv/reader.cc)

Please update this arrow port.

**Comment by LilyWangL** [comment]
Hi @gisfromscratch, thanks for posting this issue, the port arrow has been updated to version 0.16.0. I can find the code which you want in new source. You can update the vcpkg and rebuild arrow.
The related PR: #9922.

**Comment by gisfromscratch** [comment]
@LilyWangL The arrow/csv folder is not included into the build. Just the src folder contains the header files and CMakeLists. When I take a look after rebuild I only see the following folders:

```
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       20.02.2020     00:14                array
d-----       20.02.2020     00:14                compute
d-----       20.02.2020     00:14                io
d-----       20.02.2020     00:14                ipc
d-----       20.02.2020     00:14                testing
d-----       20.02.2020     00:14                util
d-----       20.02.2020     00:14                vendored
```

Would you be so kind and include the csv folder to the current build file?

**Comment by esride-jts** [comment]
@LilyWangL 
I updated arrow from a pre 0.16 version on my business developer laptop and now the folder is missing, too. As far as I can judge it, there must be a modifcation of the make files so that csv Folder is not integrated into the build. Would you be so kind  and tell us how to go back to an old Version of arrow like vcpkg downgrade --version=0.14.0.

**Comment by NancyLi1013** [comment]
Hi @esride-jts 

Sorry for the long delay.
I noticed that `arrow `has bee updated to 3.0.0. Could you please help check if this is still a problem for you?

Thanks.

**Comment by esride-jts** [comment]
@NancyLi1013  works like a charm. Let me try this again using my other workstation.

**Comment by gisfromscratch** [comment]
Works fine, thanks to all
