### ISSUE TITLE
Does openssl installing during 1 hour?

### ISSUE THREAD

**Issue by vyushin** [microsoft/vcpkg#10090]
Maybe I did something wrong?
I cloned the repository. Then ran:
```bash
.\vcpkg.exe install openssl:x64-windows openssl:x86-windows
```
output:
```bash
Computing installation plan...
The following packages will be built and installed:
    openssl[core]:x64-windows
    openssl[core]:x86-windows
  * openssl-windows[core]:x64-windows
  * openssl-windows[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/4: openssl-windows:x64-windows
Building package openssl-windows[core]:x64-windows...
-- Using cached C:/vcpkg/downloads/openssl-1.1.1d.tar.gz
-- Using source at C:/vcpkg/buildtrees/openssl-windows/src/openssl-1-b1f8ae3e6c
-- Copying openssl release source files...
-- Copying openssl release source files... done
-- Configure x64-windows-rel
-- Configure x64-windows-rel done
-- Build x64-windows-rel
-- Build x64-windows-rel done
-- Copying openssl debug source files...
-- Copying openssl debug source files... done
-- Configure x64-windows-dbg
-- Configure x64-windows-dbg done
-- Build x64-windows-dbg
-- Build x64-windows-dbg done
-- Installing: C:/vcpkg/packages/openssl-windows_x64-windows/share/openssl-windows/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package openssl-windows[core]:x64-windows... done
Installing package openssl-windows[core]:x64-windows...
Installing package openssl-windows[core]:x64-windows... done
Elapsed time for package openssl-windows:x64-windows: 28.38 min
Starting package 2/4: openssl:x64-windows
Building package openssl[core]:x64-windows...
-- Installing: C:/vcpkg/packages/openssl_x64-windows/share/openssl//usage
-- Performing post-build validation
-- Performing post-build validation done
Building package openssl[core]:x64-windows... done
Installing package openssl[core]:x64-windows...
Installing package openssl[core]:x64-windows... done
Elapsed time for package openssl:x64-windows: 348.5 ms
Starting package 3/4: openssl-windows:x86-windows
Building package openssl-windows[core]:x86-windows...
-- Using cached C:/vcpkg/downloads/openssl-1.1.1d.tar.gz
-- Using source at C:/vcpkg/buildtrees/openssl-windows/src/openssl-1-b1f8ae3e6c
-- Copying openssl release source files...
-- Copying openssl release source files... done
-- Configure x86-windows-rel
-- Configure x86-windows-rel done
-- Build x86-windows-rel
-- Build x86-windows-rel done
-- Copying openssl debug source files...
-- Copying openssl debug source files... done
-- Configure x86-windows-dbg
-- Configure x86-windows-dbg done
-- Build x86-windows-dbg
-- Build x86-windows-dbg done
-- Installing: C:/vcpkg/packages/openssl-windows_x86-windows/share/openssl-windows/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package openssl-windows[core]:x86-windows... done
Installing package openssl-windows[core]:x86-windows...
Installing package openssl-windows[core]:x86-windows... done
Elapsed time for package openssl-windows:x86-windows: 33.69 min
Starting package 4/4: openssl:x86-windows
Building package openssl[core]:x86-windows...
-- Installing: C:/vcpkg/packages/openssl_x86-windows/share/openssl//usage
-- Performing post-build validation
-- Performing post-build validation done
Building package openssl[core]:x86-windows... done
Installing package openssl[core]:x86-windows...
Installing package openssl[core]:x86-windows... done
Elapsed time for package openssl:x86-windows: 428.5 ms

Total elapsed time: 1.035 h

The package openssl is compatible with built-in CMake targets:

    find_package(OpenSSL REQUIRED)
    target_link_libraries(main PRIVATE OpenSSL::SSL OpenSSL::Crypto)

The package openssl is compatible with built-in CMake targets:

    find_package(OpenSSL REQUIRED)
    target_link_libraries(main PRIVATE OpenSSL::SSL OpenSSL::Crypto)
```

**Comment by timautry** [comment]
It depends on what hardware (cpu, memory, motherboard, disk drives, etc.) is used, what anti-virus/other software installed/running and the version of visual studio  installed - as I have noticed 2019 is a little faster than 2017... ...

I only installed the x64-windows versions and it took a total of 3.553/3.552 minutes for vs2017/vs2019 respectively:

**SYSTEM@ANDROMEDA 02/15/2020 18:10:20 D:\Git\vs2017.test**
->vcpkg install openssl openssl-windows
Computing installation plan...
The following packages will be built and installed:
    openssl[core]:x64-windows
    openssl-windows[core]:x64-windows
Starting package 1/2: openssl-windows:x64-windows
Building package openssl-windows[core]:x64-windows...
-- Using cached E:/Git/vcpkg.downloads/openssl-1.1.1d.tar.gz
-- Extracting source E:/Git/vcpkg.downloads/openssl-1.1.1d.tar.gz
-- Using source at D:/Git/vs2017.test/buildtrees/openssl-windows/src/openssl-1-b1f8ae3e6c
-- Copying openssl release source files...
-- Copying openssl release source files... done
-- Configure x64-windows-rel
-- Configure x64-windows-rel done
-- Build x64-windows-rel
-- Build x64-windows-rel done
-- Copying openssl debug source files...
-- Copying openssl debug source files... done
-- Configure x64-windows-dbg
-- Configure x64-windows-dbg done
-- Build x64-windows-dbg
-- Build x64-windows-dbg done
-- Installing: D:/Git/vs2017.test/packages/openssl-windows_x64-windows/share/openssl-windows/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package openssl-windows[core]:x64-windows... done
Installing package openssl-windows[core]:x64-windows...
Installing package openssl-windows[core]:x64-windows... done
Elapsed time for package openssl-windows:x64-windows: 3.551 min
Starting package 2/2: openssl:x64-windows
Building package openssl[core]:x64-windows...
-- Installing: D:/Git/vs2017.test/packages/openssl_x64-windows/share/openssl//usage
-- Performing post-build validation
-- Performing post-build validation done
Building package openssl[core]:x64-windows... done
Installing package openssl[core]:x64-windows...
Installing package openssl[core]:x64-windows... done
Elapsed time for package openssl:x64-windows: 70.9 ms

Total elapsed time: 3.553 min

The package openssl is compatible with built-in CMake targets:

    find_package(OpenSSL REQUIRED)
    target_link_libraries(main PRIVATE OpenSSL::SSL OpenSSL::Crypto)

The package openssl is compatible with built-in CMake targets:

    find_package(OpenSSL REQUIRED)
    target_link_libraries(main PRIVATE OpenSSL::SSL OpenSSL::Crypto)

_________________________________________________________________________________________

**SYSTEM@ANDROMEDA 02/15/2020 18:02:48 D:\Git\vs2019.test**
->vcpkg install openssl openssl-windows
Computing installation plan...
The following packages will be built and installed:
    openssl[core]:x64-windows
    openssl-windows[core]:x64-windows
Starting package 1/2: openssl-windows:x64-windows
Building package openssl-windows[core]:x64-windows...
-- Using cached E:/Git/vcpkg.downloads/openssl-1.1.1d.tar.gz
-- Extracting source E:/Git/vcpkg.downloads/openssl-1.1.1d.tar.gz
-- Using source at D:/Git/vs2019.test/buildtrees/openssl-windows/src/openssl-1-b1f8ae3e6c
-- Copying openssl release source files...
-- Copying openssl release source files... done
-- Configure x64-windows-rel
-- Configure x64-windows-rel done
-- Build x64-windows-rel
-- Build x64-windows-rel done
-- Copying openssl debug source files...
-- Copying openssl debug source files... done
-- Configure x64-windows-dbg
-- Configure x64-windows-dbg done
-- Build x64-windows-dbg
-- Build x64-windows-dbg done
-- Installing: D:/Git/vs2019.test/packages/openssl-windows_x64-windows/share/openssl-windows/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package openssl-windows[core]:x64-windows... done
Installing package openssl-windows[core]:x64-windows...
Installing package openssl-windows[core]:x64-windows... done
Elapsed time for package openssl-windows:x64-windows: 3.551 min
Starting package 2/2: openssl:x64-windows
Building package openssl[core]:x64-windows...
-- Installing: D:/Git/vs2019.test/packages/openssl_x64-windows/share/openssl//usage
-- Performing post-build validation
-- Performing post-build validation done
Building package openssl[core]:x64-windows... done
Installing package openssl[core]:x64-windows...
Installing package openssl[core]:x64-windows... done
Elapsed time for package openssl:x64-windows: 66.97 ms

Total elapsed time: 3.552 min

The package openssl is compatible with built-in CMake targets:

    find_package(OpenSSL REQUIRED)
    target_link_libraries(main PRIVATE OpenSSL::SSL OpenSSL::Crypto)

The package openssl is compatible with built-in CMake targets:

    find_package(OpenSSL REQUIRED)
    target_link_libraries(main PRIVATE OpenSSL::SSL OpenSSL::Crypto)

**Comment by timautry** [comment]
**Update:**
I installed openssl openssl-unix x64-linux triplet on a OpenSUSE Leap 15.1 linux running in a microsoft virtual machine (on top of Windows 10 Pro) with 4 virtual processors and 8 GB of memory and it took 1.83 minutes for the test environment and 1.81 for the production environment, but the test environment had to download the source first, where the source was already available to production environment, as they share the downloads folder between them.

**Comment by vyushin** [comment]
My system: 
* Windows 10 Pro
* 4 CPU 2.00 GHz, 12 Gb memory, SSD
* Visual Studio Build Tools 2017 (maybe there aren't necessary tools but I don't know which one)

**Comment by timautry** [comment]
My system is also Windows 10 Pro, x64, full installs of VS2017 and VS2019 community, but has a moderate upgrade in the hardware category, Intel I9, 8 core, additional memory and NVMe SSD drives.
I would guess hardware makes a big difference.

**Comment by PhoebeHui** [comment]
@timautry, thanks for taking a look at this questions!

@vyushin, does this still be a problem for you?

**Comment by vyushin** [comment]
@PhoebeHui, maybe installation time depending hardware but this seems strange for me when we speak about 4CPU, 12 Gb RAM and SSD. I don't undersund wy installation time was longer as expect.

**Comment by PhoebeHui** [comment]
@vyushin, it seems that affectd by the hardware, I get 2 VMs and try to install openssl, and given the time cost:

 .\vcpkg.exe install openssl:x64-windows openssl:x86-windows
2 CPU and 8G RAM -- cost 1.5hr
8 CPU and 32G RAM-- cost 30min

**Comment by PhoebeHui** [comment]
@vyushin, I checked it already build openssl in parallel in vcpkg, let me know if you expect vcpkg should do something here.
