### ISSUE TITLE
Error: Building package boost-test:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by moregion** [microsoft/vcpkg#10093]
Error: Building package boost-test:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-test:x64-windows
  Vcpkg version: 2020.02.04-nohash

**Comment by moregion** [comment]
C:\dev\vcpkg>.\vcpkg update
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.

C:\dev\vcpkg>git pull
Already up to date.

**Comment by JackBoosY** [comment]
Hi @moregion, thanks for reporting this issue!
Could you provide failure logs?

Thanks.

**Comment by moregion** [comment]
Hi.
The problem have been solved.

Thanks for your reply！


------------------------------------------------------------------
发件人：Jack·Boos·Yu <notifications@github.com>
发送时间：2020年2月17日(星期一) 21:55
收件人：microsoft/vcpkg <vcpkg@noreply.github.com>
抄　送：moregion <sham_bhala@aliyun.com>; Mention <mention@noreply.github.com>
主　题：Re: [microsoft/vcpkg] Error: Building package boost-test:x64-windows failed with: BUILD_FAILED (#10093)

Hi @moregion, thanks for reporting this issue!
 Could you provide failure logs?
Thanks.

**Comment by 9and3** [comment]
Hello @moregion ,

I actually have the same boost-test issue. May I ask how did you solve this issue? Thanks.
