### ISSUE TITLE
boost-exception:x64-android build failure

### ISSUE THREAD

**Issue by geiseri** [microsoft/vcpkg#10091]
**Host Environment**
- Arch Linux
- Compiler: Android NDK 21.0.6113669 (clang)

**To Reproduce**
- Create a triplet file with the below contents:

```
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_CMAKE_SYSTEM_NAME Android)
```
- Then run: `./vcpkg --triplet x64-android install boost-exception`

**Failure logs** 

```
-- Building x64-android-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: /home/HOUSE.GEEKCENTRAL.IO/geiseri/vcpkg/downloads/tools/cmake-3.14.0-linux/cmake-3.14.0-Linux-x86_64/bin/cmake --build . --config Debug --target install -- -v
    Working Directory: /home/HOUSE.GEEKCENTRAL.IO/geiseri/vcpkg/buildtrees/boost-exception/x64-android-dbg
    See logs for more information:
      /home/HOUSE.GEEKCENTRAL.IO/geiseri/vcpkg/buildtrees/boost-exception/install-x64-android-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  installed/x64-android/share/boost-build/boost-modular-build.cmake:90 (vcpkg_install_cmake)
  ports/boost-exception/portfile.cmake:14 (boost_modular_build)
  scripts/ports.cmake:90 (include)
```
The associated error log below:
[error.log](https://github.com/microsoft/vcpkg/files/4208988/error.log)

I think it might be confused as to the compiler I am using.  As if it wants clang, but its using gcc.

**Comment by Voskrese** [comment]
clang++: **error**: no such file or directory: 'x86_64-none-linux-android21'

API - android21 - 21 ?

**Comment by geiseri** [comment]
Yes, I am using 21.0.6113669 from Android Studio.

**Comment by mschofie** [comment]
I repro the same error on a Windows 10 host environment. It looks like the wrong clang `--target` command-line is being built into the `user-config.jam`. Clang wants `--target=<value>` but `--target= <value>` is being passed (i.e. extra space after the `=`). It looks like [`ports/boost-modular-build-helper/CMakeLists.txt`](https://github.com/microsoft/vcpkg/blob/c3ac3b24ffbc1c6e4fb759c8cd8e7a5aff9a3b94/ports/boost-modular-build-helper/CMakeLists.txt#L86) is responsible for specifying the target:

```
    set(CXXFLAGS "${CXXFLAGS} <compileflags>${CMAKE_CXX_COMPILE_OPTIONS_TARGET} <compileflags>${CMAKE_CXX_COMPILER_TARGET}")
```

Which appears to be how gcc expects the target to be passed. So adding a check for Clang, and passing the target in a Clang-like way fixes things for me, i.e.

```
if(CMAKE_CXX_COMPILER_TARGET)
    if(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
        set(CXXFLAGS "${CXXFLAGS} <compileflags>${CMAKE_CXX_COMPILE_OPTIONS_TARGET}${CMAKE_CXX_COMPILER_TARGET}")
    else()
        set(CXXFLAGS "${CXXFLAGS} <compileflags>${CMAKE_CXX_COMPILE_OPTIONS_TARGET} <compileflags>${CMAKE_CXX_COMPILER_TARGET}")
    endif()
endif()
```

But I'm a bit out of my depth here - so it's not clear if this is the Right Thing to do.

**Comment by JackBoosY** [comment]
Close this issue via #10285 merged.
