### ISSUE TITLE
Add proxy support [was: glew download is unreliable]

### ISSUE THREAD

**Issue by ebraminio** [microsoft/vcpkg#101]
Hey guys, I am trying use "glew" from vcpkg on a CI system on appveyor but sometimes am getting this error which suggests I should file a bug here:

```
-- CURRENT_BUILDTREES_DIR=C:/projects/glyphy/vcpkg/buildtrees/glew
-- CURRENT_PORT_DIR=C:/projects/glyphy/vcpkg/ports/glew/.
-- Downloading http://downloads.sourceforge.net/project/glew/glew/1.13.0/glew-1.13.0.tgz...
-- Downloading http://downloads.sourceforge.net/project/glew/glew/1.13.0/glew-1.13.0.tgz... Failed. Status: 56;"Failure when receiving data from the peer"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:43 (message):

      Failed to download file.
      Add mirrors or submit an issue at https://github.com/Microsoft/vcpkg/issues
```

**Comment by ras0219-msft** [comment]
Are you able to install other packages successfully?

Could you try adding a step before calling `vcpkg install glew` that downloads the needed archive to `downloads\` using one of the recommended download mechanisms[1] for Appveyor?

[1] https://www.appveyor.com/docs/how-to/download-file/

**Comment by ebraminio** [comment]
> Are you able to install other packages successfully?

glew is first package I am trying to download. Thanks a lot for sharing these solutions, I would try them next time I face with the error but till then, here is log of some of failed run I hope would be useful:

* https://ci.appveyor.com/project/ebraminio/glyphy/build/1.0.37#L278
* https://ci.appveyor.com/project/ebraminio/glyphy/build/1.0.36#L277
* https://ci.appveyor.com/project/ebraminio/glyphy/build/1.0.21#L273
* https://ci.appveyor.com/project/ebraminio/glyphy/build/1.0.16#L271
* https://ci.appveyor.com/project/ebraminio/glyphy/build/1.0.11#L274

**Comment by ras0219-msft** [comment]
It looks like they most likely have a caching proxy in place. The immediate fix is probably to use one of their officially supported mechanisms for downloading the source archive ahead of time.

In the future, we should look at either submitting a fix to CMake to make it more proxy-aware or switching to a different download mechanism (such as `Invoke-WebRequest`).

**Comment by ras0219-msft** [comment]
According to https://cmake.org/pipermail/cmake/2010-March/035775.html, it looks like setting the environment variable `HTTP_PROXY` to `http://host:port` may work.

**Comment by adam4813** [comment]
[glew] The whole repository is also hosted on github https://github.com/nigels-com/glew which is linked to on the main project page.

**Comment by LilyWangL** [comment]
This issue hasn’t been updated in two year, if it is still an issue, please reopen.
