### ISSUE TITLE
[opencv4] build failure

### ISSUE THREAD

**Issue by RollingIsland** [microsoft/vcpkg#10103]
**Host Environment**
- OS: Windows

**To Reproduce**
`.\vcpkg install opencv4[contrib,nonfree,cuda]:x64-windows`

**Failure logs** 
-- Downloading https://github.com/tiny-dnn/tiny-dnn/archive/v1.0.0a3.tar.gz... Failed. Status: 18;"Transferred a partial file"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:175 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  ports/opencv4/portfile.cmake:74 (vcpkg_download_distfile)
  scripts/ports.cmake:94 (include)

Error: Building package opencv4:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: opencv4:x64-windows
  Vcpkg version: 2019.09.12-nohash

**Additional context**
1. I checked my network again and again and I'm so sure **my network is good**. 
2. I successed to download the package in chorme with the url shown in the console without any problem. 
3. I'd like to know how to fix it.
4. Or is there any way to make the program use the package I downloaded with other tools. (Actually I have done it several times, I just rename my package the same way as it in \vcpkg\downloads\temp\ then re-run vcpkg and it usually works. However when downloading this package, vcpkg makes a sub-dir "opencv-cache", no matter where I put my package and how I rename it, vcpkg just rewrite the cache dir and begin to download and fail again). 

Anyway, thanks a lot for making such a fantastic tool to make it much easier managing package in VS!

**Comment by theoractice** [comment]
`.\vcpkg install opencv4[contrib]` fails in my case.

**Comment by PhoebeHui** [comment]
@RollingIsland, you can download tiny-dnn archive manullay and put it to downloads\opencv-cache\tiny_dnn\ and rename it to db1c512e09ca2c7a6faef36f9c53e59-v1.0.0a3.tar.gz

For me, it located to
"E:\VCPKG\src\downloads\opencv-cache\tiny_dnn\adb1c512e09ca2c7a6faef36f9c53e59-v1.0.0a3.tar.gz"

.\vcpkg install opencv4[contrib,nonfree,cuda]:x64-windows installed successfully for me. @theoractice, if opencv4[contrib] failed for you, could you report a new issue if it's a different issue with this? and also attach failure logs.

Building package opencv4[contrib,core,dnn,jpeg,nonfree,opengl,png,tiff,webp]:x64-windows... done
Installing package opencv4[contrib,core,dnn,jpeg,nonfree,opengl,png,tiff,webp]:x64-windows...
Installing package opencv4[contrib,core,dnn,jpeg,nonfree,opengl,png,tiff,webp]:x64-windows... done
Elapsed time for package opencv4:x64-windows: 20.59 min

Total elapsed time: 25.75 min

The package opencv4:x64-windows provides CMake targets:

    find_package(OpenCV CONFIG REQUIRED)
    # Note: 42 target(s) were omitted.
    target_link_libraries(main PRIVATE opencv_ml opencv_dnn opencv_dpm opencv_hdf)

**Comment by RollingIsland** [comment]
@PhoebeHui  Thanks for your quick reply! Your solution worked!
