### ISSUE TITLE
[boost-function] build failure

### ISSUE THREAD

**Issue by fawdlstty** [microsoft/vcpkg#10100]
**Host Environment**
- OS: Win7 x64
- Compiler: vs2017

**To Reproduce**
`vcpkg install boost-function:x86-windows-static`

**Failure logs** 
```
Computing installation plan...
Error: database corrupted. Package boost-algorithm:x86-windows-static is installed but dependency boost-function:x86-windows-static is not.
```

**Additional context**
none

**Comment by fawdlstty** [comment]
Due to unstable access to github on the Chinese network, it is easy to fail, and often fails when running 'vcpkg install boost:x86-windows-static' to install a package.This error message will be prompted after rerun

**Comment by fawdlstty** [comment]
After recursively removing the dependencies a dozen times, I can reinstall boost.
Recurrence process:
Update VCPKG, then 'VCPKG upgrade --no-dry-run', which will report "param is null" or something similar (no screenshots, this error message can not be found), the installation will stop, at this point run 'VCPKG install boost:x86-windows-static' this error.
I will make another issue when I get the detailed error again

**Comment by CMakey** [comment]
> After recursively removing the dependencies a dozen times, I can reinstall boost. Recurrence process: Update VCPKG, then 'VCPKG upgrade --no-dry-run', which will report "param is null" or something similar (no screenshots, this error message can not be found), the installation will stop, at this point run 'VCPKG install boost:x86-windows-static' this error. I will make another issue when I get the detailed error again

thanks, this really help me a lot. After  removing the dependency things step by step with the error coming up. I can fully remove the boost without reinstall all packages.
