### ISSUE TITLE
Automatically fill vcpkg version with git hash

### ISSUE THREAD

**Issue by linquize** [microsoft/vcpkg#10109]
`vcpkg version` will show

`Vcpkg package management program version 2020.02.04-nohash`

or

`Vcpkg package management program version 2020.02.04-unknownhash`

I suggest to fill `nohash` with git hash (7-10 chars) if `git` is installed and the directory is under a git repository.

Currently `bootstrap.ps1` defines `VCPKG_VERSION` `-nohash`

**Comment by JackBoosY** [comment]
Fixed.
