### ISSUE TITLE
[libpq] lack of pdb files in package for static library linkage

### ISSUE THREAD

**Issue by elviiix** [microsoft/vcpkg#10113]
When building libpq with static library linkage pdb files aren't copied into output lib directory that results in warning on linking. (if you don't have that pdb avaiable in build path on the same computer).

Changing in
ports\libpq\patches\windows\minimize_install.patch
+ "$conf\\", "libpgcommon\\libpgcommon.lib",
to
+		"$conf\\", "libpgcommon\\libpgcommon.lib", "libpgcommon\\libpgcommon.pdb", "libpq\\libpq.pdb", "libpgport\\libpgport.pdb",

solves the problem (but I doubt that it's the correct way).

**Environment**
- OS: Windows 10
- Compiler: VS 2019 

**To Reproduce**
1. ./vcpkg install libpq:x86-windows-static
2. ./vcpkg vcpkg export libpq:x86-windows-static --nuget --output=vcpkg --nuget-version=1.1.0.0
Import resulting package to VS project and build the resulting project.

**Comment by JackBoosY** [comment]
We don't need pdb for static libraries.

**Comment by elviiix** [comment]
If you don't have pdb file in package (or in directory where package was built on the same computer where you are building your project) you get warnings during build like
6>libpq.lib(encnames.obj) : warning LNK4099: PDB 'libpq.pdb' was not found with 'libpq.lib(encnames.obj)' or at '...\libpq.pdb'; linking object as if no debug info

Try renaming your vcpkg directory and building the project as described in problem.

**Comment by JackBoosY** [comment]
@elviiix 
For most ports that use cmake or msbuild, vcpkg adds the compilation option `/z7` to embed debugging symbols in the generated static library.
However, for some ports that use make or other difficult to set compile options, using `/Zi` by default will make them generate independent pdb files, causing this issue.

**Comment by JackBoosY** [comment]
For makefile, we should set `/z7` in `vcpkg_configure_make`.

**Comment by JackBoosY** [comment]
Since libpq use msvc to build itself, this should be a port bug.
