### ISSUE TITLE
#10063 is not very robust

### ISSUE THREAD

**Issue by cenit** [microsoft/vcpkg#10114]
**Describe the bug**
When installing ports that still have no abi keys (due to dependencies that have not been updated in a long time, which it might be better to forcefully trigger to rebuild now due to this issue), the build fails immediately with this message (example):
```
Building package opencv4[contrib,core,dnn,ffmpeg,jpeg,opengl,png,tiff,webp]:x64-linux...
Warning: abi keys are missing values:
    opengl

Failed to open '/mnt/e/Codice/vcpkg/buildtrees/opencv4/stdout-x64-linux.log' for writing
```

Also, in case a build has to be restarted: again a problem related to this "untested" tee mechanism

```
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- mt.exe has failed. This may be the result of anti-virus. Disabling anti-virus on the buildtree folder may improve build speed
-- Restarting Build x64-windows-rel because of mt.exe file locking issue. Iteration: 1
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:114 (file):
  file failed to open for reading (No such file or directory):

    C:/src/vcpkg/-out-1.log
Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/opencv4/portfile.cmake:332 (vcpkg_install_cmake)
  scripts/ports.cmake:90 (include)


Error: Building package opencv4:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: opencv4:x64-windows
  Vcpkg version: 2020.02.04-nohash-external
```

**Environment**
- n/a

**To Reproduce**
1. ./vcpkg install opencv4

**Expected behavior**
The package installs

**Comment by linquize** [comment]
Are you using WSL?

**Comment by cenit** [comment]
yes it happened on WSL, but does not seem related to that. Is it?

**Comment by PhoebeHui** [comment]
I tried to install opencv4[contrib,core,dnn,ffmpeg,jpeg,opengl,png,tiff,webp]:x64-linux with WSL, however, I didn't repro this issue. It built successfully for me.

**Comment by cenit** [comment]
```
Building package opencv4[core,dnn,ffmpeg,jpeg,opengl,png,tiff,webp]:x64-osx...
Warning: abi keys are missing values:
    opengl

Failed to open '/Users/stefano/code/vcpkg/buildtrees/opencv4/stdout-x64-osx.log' for writing
```

happening also on my Mac. This is clearly something unrelated to wsl, windows, ...
Judging from recent rise in filesystem issues, I think some damage might have been done inside Vcpkg

**Comment by cenit** [comment]
also on Mac, I can confirm that creating the buildtrees/opencv4 folder manually before the installation is enough to bypass the problem

**Comment by cenit** [comment]
in fact, I can't see any place in  #10063 where it's make sure that the folder exists before opening the file in it

**Comment by cenit** [comment]
I can reproduce the problem also on Windows. And with other ports too (example: libwebp)

**Comment by cenit** [comment]
Maybe I found a connection between ports that require folder created manually that otherwise fail. Maybe.

It seems they are all those that are still outputting a warning message about missing ABI infos that fail. May it help you, @ras0219-msft ?

**Comment by cenit** [comment]
#10287 might fix also this one. Closing after a check

**Comment by cenit** [comment]
#10287 closed one issue, another is still persistent

This is what happens in case a build has to be restarted: again a problem related to this untested tee mechanism that has been inserted in vcpkg too quickly

```
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- mt.exe has failed. This may be the result of anti-virus. Disabling anti-virus on the buildtree folder may improve build speed
-- Restarting Build x64-windows-rel because of mt.exe file locking issue. Iteration: 1
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:114 (file):
  file failed to open for reading (No such file or directory):

    C:/src/vcpkg/-out-1.log
```
