### ISSUE TITLE
[brotli] build failure on arm64-uwp

### ISSUE THREAD

**Issue by JackBoosY** [microsoft/vcpkg#10115]
**Host Environment**
- OS: Windows
- Compiler: revision

**To Reproduce**
`./vcpkg install brotli:arm64-uwp`

**Failure logs** 
Macro `_CRT_SECURE_NO_WARNINGS` is missing, deprecated functions reported by logs.

**Comment by strega-nil** [comment]
Fixed by #10116 :) Thanks Jack!
