### ISSUE TITLE
OpenCV build failed

### ISSUE THREAD

**Issue by sn2234** [Microsoft/vcpkg#1011]
Package: opencv:x64-windows
  Vcpkg version: 0.0.80-a0d5b944953f14cb58121e76f7fe6140e8134ca3

[package-x64-windows-rel-out.txt](https://github.com/Microsoft/vcpkg/files/968585/package-x64-windows-rel-out.txt)

**Comment by ras0219-msft** [comment]
It looks like opencv is picking up our copy of openblas which may have some issues.

As an immediate workaround, you can do
```
vcpkg remove --no-purge openblas:x64-windows
vcpkg install opencv:x64-windows
vcpkg install openblas:x64-windows
```

Bugs to fix:
- The opencv port should exercise more control -- either always use blas or never use blas
- This likely indicates a bug in our `openblas` port.
