### ISSUE TITLE
[CLI11] update to 1.9.0

### ISSUE THREAD

**Issue by BullyWiiPlaza** [microsoft/vcpkg#10121]
Library name: CLI11
New version number: 1.9.0
Release notes: https://github.com/CLIUtils/CLI11/releases/tag/v1.9.0

I tried to implement the update but failed so I'd appreciate if it gets done by someone else.

**Comment by LilyWangL** [comment]
Thanks for posting this issue. This issue has been fixed, so I am closing this issue for now.
