### ISSUE TITLE
Visual Studio will not use the static Boost libraries (build system: CMake)

### ISSUE THREAD

**Issue by BullyWiiPlaza** [microsoft/vcpkg#10122]
**Describe the bug**
If I install the static `Boost` libraries via `vcpkg install Boost:x64-windows-static` and set the `CMake` variable `Boost_USE_STATIC_LIBS` to `ON`, `Visual Studio` still does not link against the static libraries in the `C:/vcpkg/installed/x64-windows-static` directory. Instead, it looks for `Boost` inside the `C:/vcpkg/installed//x64-windows` directory.

**Environment**
- OS: Windows 10 Pro 64-bit
- Compiler: MSVC 14.24.28314 (Visual Studio 2019)

**To Reproduce**
1. `vcpkg Boost:x64-windows-static`
2. Compile
3. Error 'C:/vcpkg/installed/x64-windows/lib/boost_filesystem-vc140-mt.lib', needed by 'MyProject.exe', missing and no known rule to make it

Related StackOverflow question: https://stackoverflow.com/questions/60132392

**Expected behavior**
When compiling, `Visual Studio` looks in the `C:/vcpkg/installed/x64-windows-static` directory, discovers the `Boost` installation and statically links the code.

**Failure logs**
None.

**Additional context**
I want to compile my code into an `EXE` without any dependent `Boost` `DLL`s.

**Comment by NancyLi1013** [comment]
Hi @BullyWiiPlaza 

Thanks for posting this issue.
Could you please try to set `VCPKG_TARGET_TRIPLET` as `x64-windows-static` and then build it again?

**Comment by BullyWiiPlaza** [comment]
Thank you. That seems to get me one step closer to solving the problem. When I modify my `CMakeSettings.json` file to include the following entry:

```
"variables": [
	{
	  "name": "VCPKG_TARGET_TRIPLET",
	  "value": "x64-windows-static",
	  "type": "STRING"
	}
]
```

It compiles successfully but fails during linking:
`Error	LNK2005	"private: static class std::locale::_Locimp * __cdecl std::locale::_Getgloballocale(void)" (?_Getgloballocale@locale@std@@CAPEAV_Locimp@12@XZ) already defined in msvcprt.lib(MSVCP140.dll)	D:\Cpp\MyProject\out\build\x64-Release\MyProject	D:\Cpp\MyProject\out\build\x64-Release\libcpmt.lib(locale0.obj)
`
...
`
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in main.cpp.obj	D:\Cpp\MyProject\out\build\x64-Release\MyProjectD:\Cpp\MyProject\out\build\x64-Release\boost_filesystem-vc140-mt.lib(path_traits.obj)
`
...

In total there are quite a few of those linker errors. How can I fix them?

**Comment by NancyLi1013** [comment]
@BullyWiiPlaza 
Sorry for the late reply.

It seems that the CRT linkage type doesn't match.
Could you please check if you have set it correctly？
In this case, `/MT` might be suitable. since you need to static linkage.

**Comment by NancyLi1013** [comment]
I'm going to close this issue for now. since there seems to be inactive.
Please feel free to reopen this if it is still a problem for you.
