### ISSUE TITLE
[zstd] build failure

### ISSUE THREAD

**Issue by cenit** [microsoft/vcpkg#10124]
**Host Environment**
- OS: Windows
- Compiler: VS 2017 latest

**To Reproduce**
`./vcpkg install zstd:x64-windows`

**Failure logs** 
```
Starting package 13/92: zstd:x64-windows
Building package zstd[core]:x64-windows...
-- Using cached C:/src/vcpkg/downloads/facebook-zstd-10f0e6993f9d2f682da6d04aa2385b7d53cbb4ee.tar.gz
-- Extracting source C:/src/vcpkg/downloads/facebook-zstd-10f0e6993f9d2f682da6d04aa2385b7d53cbb4ee.tar.gz
-- Using source at C:/src/vcpkg/buildtrees/zstd/src/7d53cbb4ee-6ac5c97a10
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Performing post-build validation
The following files are placed in
C:\src\vcpkg\packages\zstd_x64-windows\debug:

    C:/src/vcpkg/packages/zstd_x64-windows/debug/include

Files cannot be present in those directories.

Found 1 error(s). Please correct the portfile:
    C:\src\vcpkg\ports\zstd\portfile.cmake
-- Performing post-build validation done
Error: Building package zstd:x64-windows failed with: POST_BUILD_CHECKS_FAILED
```

Edit: retrying the procedure, the error became the following:

```
Starting package 1/80: zstd:x64-windows
Building package zstd[core]:x64-windows...
CMake Error at scripts/ports.cmake:73 (message):
  Unable to empty directory: C:/src/vcpkg/packages/zstd_x64-windows

    Files are likely in use.


Coud not create directory C:\src\vcpkg\packages\zstd_x64-windows\share\zstd
```

antivirus is disabled on vcpkg folder

**Comment by PhoebeHui** [comment]
@cenit, could you double check if  folder C:/src/vcpkg/packages/zstd_x64-windows open? if so, please close it and try to build it again and see if the issue occur.

I can't repro this issue, zstd:x64-windows build successfully for me.

**Comment by cenit** [comment]
Nothing was open apart from powershell to install libraries. 
It's obvious it's a filesystem issue unrelated to zstd, the problem for me is that vcpkg is becoming damaged in its own internals, not just portfiles. Broken logs via tee, unreleased filesystem locks, etc, these at least were not there. Now they joined us, adding some more stress to this product which is already borderline to becoming abandoned by me. Note that in the computer nothing changed recently, apart from vs and vcpkg...

**Comment by PhoebeHui** [comment]
I have no idea about this issue. We usually see this error when the folder opened or used by other program, and can't empty it . 

@ras0219-msft, could you help take a look?
