### ISSUE TITLE
Inconsistent parsing of triplet names between qualified port names and `--triplet` option

### ISSUE THREAD

**Issue by mjl5007** [microsoft/vcpkg#10120]
**Describe the bug**
I created a custom triplet `x64-osx-10.14` which sets the deployment target explicitly to macOS 10.14. When I attempt to build/install a port using this triplet in the qualified name of the port, I get an error:

```
$ vcpkg/vcpkg install upb:x64-osx-10.14 --overlay-triplets=custom-triplets/
Error: <unknown>:1:15: expected eof
   on expression: "upb:x64-osx-10.14"
                                 ^
```

However, using the `--triplet` option instead works fine:
```
$ vcpkg/vcpkg install upb --triplet x64-osx-10.14 --overlay-triplets=custom-triplets/
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
Computing installation plan...
The following packages will be built and installed:
    upb[core]:x64-osx-10.14
Starting package 1/1: upb:x64-osx-10.14
Building package upb[core]:x64-osx-10.14...
-- [OVERLAY] Loading triplet configuration from: /Users/****/repos/custom-triplets/x64-osx-10.14.cmake
...
```

**Environment**
- OS: macOS 10.14.6 (18G3020)
- Compiler: `vcpkg` itself built with `gcc-8 (Homebrew GCC 8.3.0_2) 8.3.0`; building ports with Xcode 10.1 and/or 11.3.

**To Reproduce**
1. Create a custom triplet file with a `.` or `_` (perhaps other characters?) in the triplet name. (e.g. `x64-osx-10.14.cmake` or `x64-osx-10_14.cmake`)
2. Install a port, specifying the triplet as port of a qualified port name, e.g. `vcpkg install upb:x64-osx-10.14` -- FAILS with error described above.
3. Install the same port, specifying the default triplet with the `--triplet` option, e.v. `vcpkg install upb --triplet x64-osx-10.14` -- build proceeds just fine.

**Expected behavior**
Consistent behavior when parsing triplet names in qualified port names vs. `--triplet` option. If `.`, `_`, or other characters are invalid in triplet names, both ways if specifying the triplet should give the same error, and ideally the naming requirements for triplets should be mentioned in the docs for triplets. If those characters *are* valid in triplet names, then specifying the triplet in a qualified port name should not give an error.

**Comment by PhoebeHui** [comment]
Confirmed, this issue repoed. It's not related to platform. @mjl5007, thanks for reporting this issue.
