### ISSUE TITLE
[openal-soft:x64-windows] build failure

### ISSUE THREAD

**Issue by tibdev12** [microsoft/vcpkg#10135]
**Host Environment**
- OS: Windows 7

**To Reproduce**
`./vcpkg install openal-soft:x64-windows`

**Failure logs** 
Computing installation plan...
The following packages will be built and installed:
    openal-soft[core]:x64-windows
Starting package 1/1: openal-soft:x64-windows
Building package openal-soft[core]:x64-windows...
-- Using cached D:/Vcpkg/vcpkg/downloads/kcat-openal-soft-f5e0eef34db3a3ab94b61a2f99f84f078ba947e7.tar.gz
-- Using source at D:/Vcpkg/vcpkg/buildtrees/openal-soft/src/078ba947e7-94fd0db62c
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: D:/Vcpkg/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe --build . --config De
bug --target install -- /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /m
    Working Directory: D:/Vcpkg/vcpkg/buildtrees/openal-soft/x64-windows-dbg
    See logs for more information:
      D:\Vcpkg\vcpkg\buildtrees\openal-soft\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/openal-soft/portfile.cmake:58 (vcpkg_install_cmake)
  scripts/ports.cmake:90 (include)

**And log from install-x64-windows-dbg-out.log:**
C:\Program Files (x86)\Windows Kits\10\Include\10.0.16299.0\um\urlmon.h(7887): error C2504: 'IZoneIdentifier': base class undefined (compiling source file D:\Vcpkg\vcpkg\buildtrees\openal-soft\src\078ba947e7-94fd0db62c\alc\alconfig.cpp) [D:\Vcpkg\vcpkg\buildtrees\openal-soft\x64-windows-dbg\OpenAL.vcxproj]

**Additional context**
The above error is occured while trying install OpenAL-Soft on Windows 7. I have not found solution to this issue. Please, provide me a solution. Let me know if you need more information.

**Comment by PhoebeHui** [comment]
@tibdev12, thanks for reporting this issue.

However, I can't repro this issue with vs2017 15.9.20 and windows sdk 17763.0 on windows 7
What's compiler version do you use?

PS D:\vcpkg> ./vcpkg install openal-soft:x64-windows
Computing installation plan...
The following packages will be built and installed:
    openal-soft[core]:x64-windows
Starting package 1/1: openal-soft:x64-windows
Building package openal-soft[core]:x64-windows...
-- Downloading https://github.com/kcat/openal-soft/archive/f5e0eef34db3a3ab94b61a2f99f84f078ba947e7.tar.gz...
-- Extracting source D:/vcpkg/downloads/kcat-openal-soft-f5e0eef34db3a3ab94b61a2f99f84f078ba947e7.tar.gz
-- Applying patch dont-export-symbols-in-static-build.patch
-- Applying patch fix-arm-builds.patch
-- Using source at D:/vcpkg/buildtrees/openal-soft/src/078ba947e7-94fd0db62c
-- Downloading https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip...
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: D:/vcpkg/packages/openal-soft_x64-windows/share/openal-soft/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package openal-soft[core]:x64-windows... done
Installing package openal-soft[core]:x64-windows...
Installing package openal-soft[core]:x64-windows... done
Elapsed time for package openal-soft:x64-windows: 8.143 min

Total elapsed time: 8.143 min
The package openal-soft:x64-windows provides CMake targets:
    find_package(openal-soft CONFIG REQUIRED)
    target_link_libraries(main PRIVATE OpenAL::OpenAL)

**Comment by tibdev12** [comment]
@PhoebeHui 
Thanks for you reply. What do you mean version compiler?

Visual Studio 2017, version 15.8.4
Vcpkg version 2020.02.04-nohash
Windows 10 SDK 10.0.17134.0

**Comment by PhoebeHui** [comment]
@tibdev12, from the failures, it seems that you used windows sdk 10.0.16299.0, it seems compiler issue  or windows sdk issue, could you upgrade visual studio and install windows sdk by vs installer, then try to build again?

**Comment by tibdev12** [comment]
@PhoebeHui 
What i have done:
- upgrade VS to the newest version
- remove all SDK from C:\Program Files\Windows Kits\
- install SDK, just newest version by VS installer
- reinstall vcpkg

And it works! Thank you for your suggestion. I think we can close this thread.

**Comment by PhoebeHui** [comment]
Great to hear that!
