### ISSUE TITLE
vcpkg install error

### ISSUE THREAD

**Issue by MrJiangSheng** [Microsoft/vcpkg#1013]
I have install vcpkg，but can't install any lib。

```
C:\Users\Administrator\Desktop\vcpkg-master>vcpkg integrate install
Applied user-wide integration for this vcpkg root.

All MSBuild C++ projects can now #include any installed libraries.
Linking will be handled automatically.
Installing new libraries will make them instantly available.

CMake projects should use -DCMAKE_TOOLCHAIN_FILE=C:/Users/Administrator/Desktop/
vcpkg-master/scripts/buildsystems/vcpkg.cmake

C:\Users\Administrator\Desktop\vcpkg-master>vcpkg install libpng:x64-windows
The following packages will be built and installed:
    libpng:x64-windows
  * zlib:x64-windows
Additional packages (*) need to be installed to complete this operation.
Building package zlib:x64-windows...
-- CURRENT_INSTALLED_DIR=C:/Users/Administrator/Desktop/vcpkg-master/installed/x
64-windows
-- DOWNLOADS=C:/Users/Administrator/Desktop/vcpkg-master/downloads
-- CURRENT_PACKAGES_DIR=C:/Users/Administrator/Desktop/vcpkg-master/packages/zli
b_x64-windows
-- CURRENT_BUILDTREES_DIR=C:/Users/Administrator/Desktop/vcpkg-master/buildtrees
/zlib
-- CURRENT_PORT_DIR=C:/Users/Administrator/Desktop/vcpkg-master/ports/zlib/.
-- Using cached C:/Users/Administrator/Desktop/vcpkg-master/downloads/zlib1211.t
ar.gz
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting source C:/Users/Administrator/Desktop/vcpkg-master/downloads/zlib1
211.tar.gz
-- Extracting done
-- Configuring x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:14 (message):
    Command failed: C:/Users/Administrator/Desktop/vcpkg-master/downloads/cmake-
3.8.0-rc1-win32-x86/bin/cmake.exe;C:/Users/Administrator/Desktop/vcpkg-master/bu
ildtrees/zlib/src/zlib-1.2.11;-DSKIP_INSTALL_FILES=ON;-DBUILD_SHARED_LIBS=ON;-DV
CPKG_TARGET_TRIPLET=x64-windows;-DCMAKE_CXX_FLAGS= /DWIN32 /D_WINDOWS /W3 /utf-8
 /GR /EHsc /MP;-DCMAKE_C_FLAGS= /DWIN32 /D_WINDOWS /W3 /utf-8 /MP;-DCMAKE_EXPORT
_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND
_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON;-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=
TRUE;-DCMAKE_VERBOSE_MAKEFILE=ON;-DVCPKG_APPLOCAL_DEPS=OFF;-DCMAKE_TOOLCHAIN_FIL
E=C:/Users/Administrator/Desktop/vcpkg-master/scripts/buildsystems/vcpkg.cmake;-
DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON;-DCMAKE_CXX_FLAGS_RELEASE=/MD /O
2 /Oi /Gy /DNDEBUG /Zi;-DCMAKE_C_FLAGS_RELEASE=/MD /O2 /Oi /Gy /DNDEBUG /Zi;-DCM
AKE_SHARED_LINKER_FLAGS_RELEASE=/DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF;-DCMAKE
_EXE_LINKER_FLAGS_RELEASE=/DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF;-G;Visual Stu
dio 15 2017 Win64;-DCMAKE_BUILD_TYPE=Release;-DCMAKE_INSTALL_PREFIX=C:/Users/Adm
inistrator/Desktop/vcpkg-master/packages/zlib_x64-windows
    Working Directory: C:/Users/Administrator/Desktop/vcpkg-master/buildtrees/zl
ib/x64-windows-rel
    See logs for more information:
      C:\Users\Administrator\Desktop\vcpkg-master\buildtrees\zlib\config-x64-win
dows-rel-out.log
      C:\Users\Administrator\Desktop\vcpkg-master\buildtrees\zlib\config-x64-win
dows-rel-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:100 (vcpkg_execute_required_process)

  ports/zlib/portfile.cmake:10 (vcpkg_configure_cmake)
  scripts/ports.cmake:73 (include)


Error: Building package zlib:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zlib:x64-windows
  Vcpkg version: 0.0.79-unknownhash

Additionally, attach any relevant sections from the log files above.
```

**Comment by ras0219-msft** [comment]
Hi @MrJiangSheng,

> 0.0.79-unknownhash

First and foremost, please update to the latest Vcpkg. If the problem still persists, please attach the logs:
> C:\Users\Administrator\Desktop\vcpkg-master\buildtrees\zlib\config-x64-windows-rel-out.log
> C:\Users\Administrator\Desktop\vcpkg-master\buildtrees\zlib\config-x64-windows-rel-err.log

**Comment by MrJiangSheng** [comment]
@ras0219-msft I'm sorry for bother you again,I updated the latest vcpkg but there is still the same error.the error in `'C:\Users\Administrator\Desktop\vcpkg-master\buildtrees\zlib\config-x64-windows-rel-err.log'is` CMake Error at CMakeLists.txt:4 (project):

>   No CMAKE_C_COMPILER could be found.

and  in ‘C:\Users\Administrator\Desktop\vcpkg-master\buildtrees\zlib\config-x64-windows-rel-err.log’
```
-- The C compiler identification is unknown
-- Configuring incomplete, errors occurred!
See also "C:/Users/Administrator/Desktop/vcpkg-master/buildtrees/zlib/x64-windows-rel/CMakeFiles/CMakeOutput.log".
See also "C:/Users/Administrator/Desktop/vcpkg-master/buildtrees/zlib/x64-windows-rel/CMakeFiles/CMakeError.log".
```
what can i do to configure the complier ?
I have install vs2012,2015and2017,cmake3.8 and git in win7.thanks for you help again,

**Comment by ras0219-msft** [comment]
I suspect you may be on a 32-bit system. We use the x64-native toolchain when building for x64-windows, however that will fail if you're on a 32-bit system.

Could you run `vcpkg env --debug` and post the results (run `exit` afterwords)? You'll probably see a message saying something to the effect that "this toolchain is not available".

**Comment by MrJiangSheng** [comment]
Thanks a lot for you help and I think I may found what wrong,the vs 2017 may lost something and I will install it again.And my system is 64-bit system.

**Comment by ras0219-msft** [comment]
Let me know if you still have problems -- I'd be happy to reopen this issue.

**Comment by MrJiangSheng** [comment]
Thanks!

**Comment by MrJiangSheng** [comment]
@ras0219-msft  dear Sir，I‘m so sorry to tell you that my installation still not work. I get the new error:

```

- C:\Users\Administrator\Desktop\vcpkg-master>bootstrap-vcpkg.bat
- Could not find MSBuild version with C++ support. VS2015 or VS2017 (with C++) needs to be installed.
- 所在位置 C:\Users\Administrator\Desktop\vcpkg-master\scripts\findAnyMSBuildWithCppPlatformToolset.p
- s1:164 字符: 6
- + throw <<<<  "Could not find MSBuild version with C++ support. VS2015 or VS2017 (with C++) needs t
- o be installed."
-     + CategoryInfo          : OperationStopped: (Could not find ...o be installed.:String) [], Run
-    timeException
-     + FullyQualifiedErrorId : Could not find MSBuild version with C++ support. VS2015 or VS2017 (w
-    ith C++) needs to be installed.
- 

```

**Comment by ras0219-msft** [comment]
Ok, could you run
```
C:\Users\Administrator\Desktop\vcpkg-master\scripts\findAnyMSBuildWithCppPlatformToolset.ps1 -verbose
```
from powershell and post the results?

**Comment by MrJiangSheng** [comment]
Im sorry，and what I can do to configure the 2015 compiler as the default compiler when I install vcpkg and other lib.I have install vs2017 again,but it's also have some problems when  I install any lib.

**Comment by MrJiangSheng** [comment]
I have run it but nothing works.

**Comment by MrJiangSheng** [comment]
I  run it and open the'' findAnyMSBuildWithCppPlatformToolset.txt''.it comtent is:
[CmdletBinding()]
param(
    [Parameter(Mandatory=$False)]
    [switch]$DisableVS2015 = $False,

    [Parameter(Mandatory=$False)]
    [switch]$DisableVS2017 = $False
)

if ($DisableVS2015 -and $DisableVS2017)
{
    throw "Both VS2015 and VS2017 were disabled."
}

function New-MSBuildInstance()
{
    param ($msbuildExePath, $toolsetVersion)

    $instance = new-object PSObject
    $instance | add-member -type NoteProperty -Name msbuildExePath -Value $msbuildExePath
    $instance | add-member -type NoteProperty -Name toolsetVersion -Value $toolsetVersion

    return $instance
}

Write-Verbose "Executing $($MyInvocation.MyCommand.Name) with DisableVS2017=$DisableVS2017, DisableVS2015=$DisableVS2015"
$scriptsDir = split-path -parent $MyInvocation.MyCommand.Definition

$validInstances = New-Object System.Collections.ArrayList

# VS2017
Write-Verbose "`n`n"
Write-Verbose "Checking for MSBuild from VS2017 instances..."
$VisualStudio2017InstallationInstances = & $scriptsDir\findVisualStudioInstallationInstances.ps1
Write-Verbose "VS2017 Candidates: $([system.String]::Join(',', $VisualStudio2015InstallationInstances))"
foreach ($instanceCandidate in $VisualStudio2015InstallationInstances)
{
    $VCFolder= "$instanceCandidate\VC\Tools\MSVC\"

    if (Test-Path $VCFolder)
    {
        $instance = New-MSBuildInstance "$instanceCandidate\MSBuild\15.0\Bin\MSBuild.exe" "v141"
        Write-Verbose "Found $instance"
        $validInstances.Add($instance) > $null
    }
}

# VS2015 - in Program Files
Write-Verbose "`n`n"
Write-Verbose "Checking for MSBuild from VS2015 in Program Files..."
$CandidateProgramFiles = $(& $scriptsDir\getProgramFiles32bit.ps1), $(& $scriptsDir\getProgramFilesPlatformBitness.ps1)
Write-Verbose "Program Files Candidate locations: $([system.String]::Join(',', $CandidateProgramFiles))"
foreach ($ProgramFiles in $CandidateProgramFiles)
{
    $clExe= "$ProgramFiles\Microsoft Visual Studio 14.0\VC\bin\cl.exe"

    if (!(Test-Path $clExe))
    {
        Write-Verbose "$clExe - Not Found"
        continue
    }

    Write-Verbose "$clExe - Found"
    $instance = New-MSBuildInstance "$ProgramFiles\MSBuild\14.0\Bin\MSBuild.exe" "v140"
    Write-Verbose "Found $instance"
    $validInstances.Add($instance) > $null
}

# VS2015 - through the registry
function NewCppRegistryPair()
{
    param ($visualStudioEntry, $msBuildEntry)

    $instance = new-object PSObject
    $instance | add-member -type NoteProperty -Name visualStudioEntry -Value $visualStudioEntry
    $instance | add-member -type NoteProperty -Name msBuildEntry -Value $msBuildEntry

    return $instance
}

Write-Verbose "`n`n"
Write-Verbose "Checking for MSBuild from VS2015 through the registry..."

$registryPairs =
$(NewCppRegistryPair "Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\visualstudio\14.0" "Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\msbuild\toolsversions\14.0"),
$(NewCppRegistryPair "Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\visualstudio\14.0" "Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\msbuild\toolsversions\14.0")

foreach ($pair in $registryPairs)
{
    $vsEntry = $pair.visualStudioEntry
    try
    {
        $VS14InstallDir = $(gp $vsEntry InstallDir -erroraction Stop | % { $_.InstallDir })
        Write-Verbose "$vsEntry\InstallDir - Found"
    }
    catch
    {
        Write-Verbose "$vsEntry\InstallDir - Not Found"
        continue
    }

    Write-Verbose "$VS14InstallDir - Obtained from registry"
    # We want "${VS14InstallDir}..\..\VC\bin\cl.exe"
    # Doing Split-path to avoid the ..\.. from appearing in the output
    $clExePath = Split-path $VS14InstallDir -Parent
    $clExePath = Split-path $clExePath -Parent
    $clExePath = "$clExePath\VC\bin\cl.exe"

    if (!(Test-Path $clExePath))
    {
        Write-Verbose "$clExePath - Not Found"
        continue
    }

    Write-Verbose "$clExePath - Found"

    $msbuildEntry = $pair.msBuildEntry
    try
    {
        $MSBuild14 = $(gp $msbuildEntry MSBuildToolsPath -erroraction Stop | % { $_.MSBuildToolsPath })
        Write-Verbose "$msbuildEntry\MSBuildToolsPath - Found"
    }
    catch
    {
        Write-Verbose "$msbuildEntry\MSBuildToolsPath - Not Found"
        continue
    }

    Write-Verbose "${MSBuild14} - Obtained from registry"
    $msbuildPath = "${MSBuild14}MSBuild.exe"
    if (!(Test-Path $msbuildPath))
    {
        Write-Verbose "$msbuildPath - Not Found"
        continue
    }

    $instance = New-MSBuildInstance $msbuildPath "v140"
    Write-Verbose "Found $instance"
    $validInstances.Add($instance) > $null
}

Write-Verbose "`n`n`n"
Write-Verbose "The following MSBuild instances were found:"
foreach ($instance in $validInstances)
{
    Write-Verbose $instance
}

# Selecting
foreach ($instance in $validInstances)
{
    if (!$DisableVS2017 -and $instance.toolsetVersion -eq "v141")
    {
        return $instance.msbuildExePath, $instance.toolsetVersion
    }

    if (!$DisableVS2015 -and $instance.toolsetVersion -eq "v140")
    {
        return $instance.msbuildExePath, $instance.toolsetVersion
    }
}


throw "Could not find MSBuild version with C++ support. VS2015 or VS2017 (with C++) needs to be installed."

**Comment by MrJiangSheng** [comment]
。。。。。

**Comment by ras0219-msft** [comment]
It is a powershell script, so if you are in cmd.exe you will need to do
```batchfile
powershell.exe -exec bypass scripts\findAnyMSBuildWithCppPlatformToolset.ps1 -verbose
```

**Comment by MrJiangSheng** [comment]
I have try it but no work and I think it must need to reinstall the vs2015 or vs2017 or the system.thinks again for you help..

**Comment by MrJiangSheng** [comment]
And know I have unstall the vs2015and vs2017,,,,,,
