### ISSUE TITLE
Panda Qemu Lib for analyzing Binaries.Adding to port

### ISSUE THREAD

**Issue by eix128** [microsoft/vcpkg#10138]
Panda also used very much for analysing malware or reverse engineering.
I just compiled the library with WSL on Windows.
I dont know how to compile for Windows native.

https://github.com/panda-re/panda

Checkout example work done on panda qemu
https://adalogics.com/blog/Building-a-custom-malware-sandbox-with-PANDA-Part-1

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
