### ISSUE TITLE
[pcl] build failure

### ISSUE THREAD

**Issue by vinimarco** [microsoft/vcpkg#10130]
I Keep having the following problem try to install pcl library although i have the latest version of vcpkg 

**Host Environment**
- OS: Windows 10

**Failure logs** 
Error: Building package pcl:x64-windows-static failed with: BUILD_FAILED Please ensure you're using the latest portfiles with `.\vcpkg update`, then submit an issue at https://github.com/Microsoft/vcpkg/issues including:   Package: pcl:x64-windows-static   Vcpkg version: 2020.02.04-nohash

**Comment by JackBoosY** [comment]
Duplicate with #10095.
