### ISSUE TITLE
[MIPP] Cross platform SIMD Lib for C++

### ISSUE THREAD

**Issue by eix128** [microsoft/vcpkg#10136]
It would be good to add MIPP Library to vcpkg as a port.
You can checkout the lib.
 
https://github.com/aff3ct/MIPP

Its so insane simd lib.Even used on 5G

https://ppopp18.sigplan.org/details/WPMVP2018/7/MIPP-a-Portable-C-SIMD-Wrapper-and-its-use-for-Error-Correction-Coding-in-5G-Stand

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
