### ISSUE TITLE
ESP32 Microcontroller package manager support ?

### ISSUE THREAD

**Issue by eix128** [microsoft/vcpkg#10133]
Hi , is there any plan to make vcpkg for microcontroller package manager ?
Like ESP32-IDF or Arduino ?

**Comment by JackBoosY** [comment]
vcpkg is a c/c++ third-party package manager, so if you need to use some libraries, please reopen an issue to request the addition of non-existent libraries.
If you want to support the ESP32 Microcontroller platform, please reopen an issue to request the addition of new ones triplet.
