### ISSUE TITLE
vcpkg install error: "Cannot get dependencies because "...

### ISSUE THREAD

**Issue by ras0219-msft** [Microsoft/vcpkg#1014]
From @MrJiangSheng:

> C:\Users\Administrator\Desktop\vcpkg-master> vcpkg install libpng x64-uwp
Cannot get dependencies because there was none of: source/binary/status paragrap
hs

>C:\Users\Administrator\Desktop\vcpkg-master> vcpkg install libpng x64-uwp
Cannot get dependencies because there was none of: source/binary/status paragrap
hs
C:\Users\Administrator\Desktop\vcpkg-master>

I removed the comments from another thread because they were not relevant to that discussion. Additionally, please do not ping random individuals -- many are users like you who won't appreciate the extra emails in their inbox!

**Comment by ras0219-msft** [comment]
@MrJiangSheng, could you ensure you are using the latest vcpkg? I'm unable to reproduce the error you are seeing in the latest version.

To fix the problem immediately: with the syntax `install libpng x64-uwp` we're interpreting `x64-uwp` as a package to be installed:
```
PS D:\src\vcpkg> vcpkg install x64-uwp
Could not find package x64-uwp:x86-windows
```

I believe you intended to run `vcpkg install libpng:x64-uwp`.

**Comment by MrJiangSheng** [comment]
@ras0219-msft I‘m very glad for you harmness help and sorry for bother all of you.it's my first time to call help in github.

**Comment by MrJiangSheng** [comment]
@ras0219-msft thanks a lot.and when I run as you suggested,there is another problem as follow：

Error: Building package zlib:x64-uwp failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zlib:x64-uwp
  Vcpkg version: 0.0.79-unknownhash
 

 And the full test is:


C:\Users\Administrator\Desktop\vcpkg-master>vcpkg install libpng:x64-uwp
The following packages will be built and installed:
    libpng:x64-uwp
  * zlib:x64-uwp
Additional packages (*) need to be installed to complete this operation.
Building package zlib:x64-uwp...
-- CURRENT_INSTALLED_DIR=C:/Users/Administrator/Desktop/vcpkg-master/installed/x64-uwp
-- DOWNLOADS=C:/Users/Administrator/Desktop/vcpkg-master/downloads
-- CURRENT_PACKAGES_DIR=C:/Users/Administrator/Desktop/vcpkg-master/packages/zlib_x64-uwp
-- CURRENT_BUILDTREES_DIR=C:/Users/Administrator/Desktop/vcpkg-master/buildtrees/zlib
-- CURRENT_PORT_DIR=C:/Users/Administrator/Desktop/vcpkg-master/ports/zlib/.
-- Using cached C:/Users/Administrator/Desktop/vcpkg-master/downloads/zlib1211.tar.gz
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Configuring x64-uwp-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:14 (message):
    Command failed: C:/Users/Administrator/Desktop/vcpkg-master/downloads/cmake-3.8.0-rc1-win32-x86/
bin/cmake.exe;C:/Users/Administrator/Desktop/vcpkg-master/buildtrees/zlib/src/zlib-1.2.11;-DSKIP_INS
TALL_FILES=ON;-DCMAKE_SYSTEM_NAME=WindowsStore;-DCMAKE_SYSTEM_VERSION=10.0;-DBUILD_SHARED_LIBS=ON;-D
VCPKG_TARGET_TRIPLET=x64-uwp;-DCMAKE_CXX_FLAGS= /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP;-DCMAKE_
C_FLAGS= /DWIN32 /D_WINDOWS /W3 /utf-8 /MP;-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAG
E_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON;-DCMAKE_INSTALL_SYSTEM_R
UNTIME_LIBS_SKIP=TRUE;-DCMAKE_VERBOSE_MAKEFILE=ON;-DVCPKG_APPLOCAL_DEPS=OFF;-DCMAKE_TOOLCHAIN_FILE=C
:/Users/Administrator/Desktop/vcpkg-master/scripts/buildsystems/vcpkg.cmake;-DCMAKE_ERROR_ON_ABSOLUT
E_INSTALL_DESTINATION=ON;-DCMAKE_CXX_FLAGS_RELEASE=/MD /O2 /Oi /Gy /DNDEBUG /Zi;-DCMAKE_C_FLAGS_RELE
ASE=/MD /O2 /Oi /Gy /DNDEBUG /Zi;-DCMAKE_SHARED_LINKER_FLAGS_RELEASE=/DEBUG /INCREMENTAL:NO /OPT:REF
 /OPT:ICF;-DCMAKE_EXE_LINKER_FLAGS_RELEASE=/DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF;-G;Visual Studio
 15 2017 Win64;-DCMAKE_BUILD_TYPE=Release;-DCMAKE_INSTALL_PREFIX=C:/Users/Administrator/Desktop/vcpk
g-master/packages/zlib_x64-uwp
    Working Directory: C:/Users/Administrator/Desktop/vcpkg-master/buildtrees/zlib/x64-uwp-rel
    See logs for more information:
      C:\Users\Administrator\Desktop\vcpkg-master\buildtrees\zlib\config-x64-uwp-rel-out.log
      C:\Users\Administrator\Desktop\vcpkg-master\buildtrees\zlib\config-x64-uwp-rel-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:100 (vcpkg_execute_required_process)
  ports/zlib/portfile.cmake:10 (vcpkg_configure_cmake)
  scripts/ports.cmake:73 (include)


Error: Building package zlib:x64-uwp failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zlib:x64-uwp
  Vcpkg version: 0.0.79-unknownhash

Additionally, attach any relevant sections from the log files above.

C:\Users\Administrator\Desktop\vcpkg-master>

**Comment by ras0219-msft** [comment]
This looks the same as #1013, so let's continue there.
