### ISSUE TITLE
[cairo:x64-windows] build failure

### ISSUE THREAD

**Issue by DA40** [microsoft/vcpkg#10149]
**Host Environment**
- OS: Windows 10
- Compiler: MSVC/14.24.28314
- Vcpkg version: 2020.02.04-nohash

**To Reproduce**
`./vcpkg install gtk:x64-windows`

**Failure logs** 
Starting package 15/22: cairo:x64-windows
Building package cairo[core]:x64-windows...
-- Downloading https://www.cairographics.org/releases/cairo-1.16.0.tar.xz...
-- Extracting source C:/Dev/vcpkg/downloads/cairo-1.16.0.tar.xz
-- Applying patch export-only-in-shared-build.patch
-- Applying patch 0001_fix_osx_defined.patch
-- Using source at C:/Dev/vcpkg/buildtrees/cairo/src/1.16.0-1ead74a565
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: ninja -v
    Working Directory: C:/Dev/vcpkg/buildtrees/cairo/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\Dev\vcpkg\buildtrees\cairo\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:295 (vcpkg_execute_required_process)
  ports/cairo/portfile.cmake:32 (vcpkg_configure_cmake)
  scripts/ports.cmake:90 (include)
Error: Building package cairo:x64-windows failed with: BUILD_FAILED

[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/4232710/config-x64-windows-out.log)

**Comment by LilyWangL** [comment]
@DA40 thanks for posting this issue. Could you provide the error log `config-x64-windows-out.log`?

**Comment by DA40** [comment]
Hi Lily,

That log file is attached at the end of my bug report.

Regards,

Keith MacDonald

**Comment by LilyWangL** [comment]
@DA40 I can't repro this issue, from your log, it failed with following failure, there is a similar issue #9554, could you double check if you have similar permission issue?
```
CMake Error at C:/Program Files/CMake/share/cmake-3.16/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/Dev/vcpkg/buildtrees/cairo/x64-windows-dbg/CMakeFiles/CMakeTmp
    
    Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe cmTC_4b3e0 && [1/2] Building C object CMakeFiles\cmTC_4b3e0.dir\testCCompiler.c.obj
    [2/2] Linking C executable cmTC_4b3e0.exe
    FAILED: cmTC_4b3e0.exe 
    cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\cmTC_4b3e0.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100177~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100177~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MIB055~1\2019\PROFES~1\VC\Tools\MSVC\1424~1.283\bin\Hostx64\x64\link.exe /nologo CMakeFiles\cmTC_4b3e0.dir\testCCompiler.c.obj  /out:cmTC_4b3e0.exe /implib:cmTC_4b3e0.lib /pdb:cmTC_4b3e0.pdb /version:0.0  /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    FINAL LINK: command "C:\PROGRA~2\MIB055~1\2019\PROFES~1\VC\Tools\MSVC\1424~1.283\bin\Hostx64\x64\link.exe /nologo CMakeFiles\cmTC_4b3e0.dir\testCCompiler.c.obj /out:cmTC_4b3e0.exe /implib:cmTC_4b3e0.lib /pdb:cmTC_4b3e0.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\cmTC_4b3e0.dir/intermediate.manifest CMakeFiles\cmTC_4b3e0.dir/manifest.res" failed (exit code 1168) with the following output:
    LINK : fatal error LNK1168: cannot open cmTC_4b3e0.exe for writing
    ninja: build stopped: subcommand failed.
```

**Comment by DA40** [comment]
The root of my C drive is write protected, so if that's where vcpkg is creating files, it explains my build failure.  Why doesn't it use the folder assigned to the TEMP environment variable?

**Comment by LilyWangL** [comment]
@DA40 Sorrt I am late. Could you please try to clone VCPKG to other drives and install port again?

**Comment by DA40** [comment]
I've been able to install cairo by making the root of the C drive writeable. It would be better if VCPKG didn't try to create files there.

**Comment by LilyWangL** [comment]
When VCPKG installing port, it will create install files on directory _vcpkg/_. It need directory _vcpkg/_ is writeable. This issue has been fixed, so I am closing this issue for now.
