### ISSUE TITLE
[sqlite-orm] cannot find package

### ISSUE THREAD

**Issue by algobot76** [microsoft/vcpkg#10141]
**Host Environment**
- OS: mac 10.15
- Compiler: clang 11

**To Reproduce**

- Run `./vcpkg install sqlite-orm`
- Add `find_package(sqlite_orm CONFIG REQUIRED)` to `CMakeLists.txt`
- Run cmake

**Failure logs** 
```
 Could not find a package configuration file provided by "sqlite_orm" with
  any of the following names:

    sqlite_ormConfig.cmake
    sqlite_orm-config.cmake

  Add the installation prefix of "sqlite_orm" to CMAKE_PREFIX_PATH or set
  "sqlite_orm_DIR" to a directory containing one of the above files.  If
  "sqlite_orm" provides a separate development package or SDK, be sure it has
  been installed.
```

**Comment by NancyLi1013** [comment]
Hi @algobot76 

Thanks for posting this issue.

Since `sqlite-orm` does not provide an exported cmake file now.
So we cannot use `find_package(sqlite_orm CONFIG REQUIRED)` to find this library.
Maybe you can use `find_path()` and `find_library()` to find it.

**Comment by DenisLopatin** [comment]
I don't know if this will be useful to someone someday, but I encountered the same problem when building a project. The thing is that sometimes some guides advise to write `find_package(sqlite_orm REQUIRED)` in `CMakeLists.txt`, but after I changed it to `find_package(SqliteOrm REQUIRED)` everything worked. I'll leave it here, you never know if someone else will encounter a similar problem.
