### ISSUE TITLE
Angle port Cannot open include file: 'glext_explicit_context_autogen.inc' not found 

### ISSUE THREAD

**Issue by mediabuff** [microsoft/vcpkg#10142]
Windows 10

**Comment by LilyWangL** [comment]
Hi @mediabuff, thanks for posting this issue. Could you please provide the reproduce steps and error log?

**Comment by LilyWangL** [comment]
Ping @mediabuff

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Please reopen this issue if it still be a problem for you.
