### ISSUE TITLE
[libssh] ssh_init failure

### ISSUE THREAD

**Issue by DDoSolitary** [microsoft/vcpkg#10144]
****

**Is your feature request related to a problem? Please describe.**
Currently, libssh links with mbedtls by default. However, when compiling with mbedtls, libssh requires that either MBEDTLS_THREADING_ALT is enabled or threading is not supported, otherwise the `crypto_thread_init` function, which is indirectly called by `ssh_init`, returns an error.

src/threads/mbedtls.c:
```c
int crypto_thread_init(struct ssh_threads_callbacks_struct *user_callbacks)
{
    int cmp;

    if (user_callbacks == NULL) {
        return SSH_OK;
    }

    cmp = strcmp(user_callbacks->type, "threads_noop");
    if (cmp == 0) {
        return SSH_OK;
    }
#ifdef MBEDTLS_THREADING_ALT
    else {
        if (user_callbacks != NULL) {
            crypto_thread_finalize();
        }

        mbedtls_threading_set_alt(user_callbacks->mutex_init,
                                  user_callbacks->mutex_destroy,
                                  user_callbacks->mutex_lock,
                                  user_callbacks->mutex_unlock);
    }
#elif defined MBEDTLS_THREADING_PTHREAD
    return SSH_OK;
#else
    return SSH_ERROR;
#endif
}
```

However:

- libssh does support multi-threading on Windows and it doesn't provide any trivial way (like cmake options) to turn it off. (And of course it is not desireable to turn it off in most cases)
- MBEDTLS_THREADING_ALT is not enabled by the mbedtls port, and it is actually impossible to enable it because mbedtls requires the user to define a custom `mbedtls_threading_mutex_t` type **when compiling mbedtls itself**, which is expected to be defined by dependencies such as libssh.

As a result, the libssh port built with default features is completely unusable, because `ssh_init` is required to be called before using any libssh functions, and it is even automatically called by `DllMain` on `DLL_PROCESS_ATTACH`, making the built DLL impossible to load.

**Proposed solution**
An quick fix would be remove the mbedtls feature for libssh and use openssl by default, which doesn't have special requirements as that of mbedtls.

**Describe alternatives you've considered**
Or probably we can create a patch that disables threading support when mbedtls is used, and display some sort of warnings about multi-threading being unavailable.

**Additional context**
N/A

**Comment by DDoSolitary** [comment]
I just noticed this portion of code in `crypto_thread_init`:

```c
#elif defined MBEDTLS_THREADING_PTHREAD
    return SSH_OK;
#else
```

It seems that we can enable `MBEDTLS_THREADING_PTHREAD` for the mbedtls port, which will make libssh happy and keep threading support enabled. This approach seems to be more ideal.

**Comment by linquize** [comment]
See #10012

**Comment by DDoSolitary** [comment]
Sorry, didn't notice that there's an existing issue about this.
