### ISSUE TITLE
[qt5:x64-windows / atlmfc:x64-windows] build failed

### ISSUE THREAD

**Issue by Sangguk-Cha** [microsoft/vcpkg#10152]
**Describe the bug**
When I installed qt5, the package atlfmc:x64-windows has error.

**Environment**
- OS: Windows
- Compiler: MSVC++ 14.16 _MSC_VER == 1916

**To Reproduce**
1. ./vcpkg install qt5:x64-windows / atlemc:x64-windows
2. See error
Error : Building package atlfmc:x64-windows failed with : BUILD_FAILED
Please ensure you're using the latest portfiles with '.\vcpkg update', then submit an issut at https://github.com/microsoft/vcpkg/issues including:
   Package: atlmfc:x64-windows
   Vcpkg version: 2020.02.04-nohash

**Expected behavior**
I want to install qt5

**Failure logs** 
CMake Error at ports/atlmfc/portfile.cmake:7 (message):
  Unable to locate 'afxres.h'.  Ensure you have installed the ATL/MFC
  component of Visual Studio.
Call Stack (most recent call first):
  scripts/ports.cmake:90 (include)

**Additional context**

**Comment by PhoebeHui** [comment]
@Sangguk-Cha, do you install ATL/MFC component? if not, could you installed it by visual studio installer? I can't repro this issue, it built successfully for me.

![image](https://user-images.githubusercontent.com/20694052/75026801-83da1c80-54d8-11ea-86ce-82c91a3cb8e0.png)

**Comment by PhoebeHui** [comment]
@Sangguk-Cha, does this still be a problem for you?

**Comment by PhoebeHui** [comment]
Please reopen this issue if it still be a problem for you.
