### ISSUE TITLE
FFmpeg build on macos expose library vdpau which does not exist for macos

### ISSUE THREAD

**Issue by sarbjit-longia** [microsoft/vcpkg#10153]
**Describe the bug**
Installed FFmpeg using vcpkg and while using it the build failed as library vdpau is not found. On investigation found following problematic line in FindFFMpeg.cmake

if(UNIX)
     list(APPEND FFMPEG_PLATFORM_DEPENDENT_LIBS -pthread -lvdpau -lX11)
endif()

**Environment**
- OS: osx
- Compiler: clang

**To Reproduce**
1. ./vcpkg install ffmpeg
2. Link against installed ffmpeg libs and build fails for any applicaiton.

**Expected behavior**
Build shall pass for any application linking against installed FFmpeg

**Failure logs** 
None

**Additional context**
None

**Comment by JackBoosY** [comment]
Confirmed, we need to disable `vdpau` using param `--disable-vdpau`.

**Comment by JackBoosY** [comment]
Hi @sarbjit-longia, thanks for reporting this issue!
I've fixed it, please update vcpkg and rebuild ffmpeg.

Thanks.
