### ISSUE TITLE
geotrans - CONTROL file updated to version 3.8 but portfile.cmake still downloads 3.7

### ISSUE THREAD

**Issue by timautry** [microsoft/vcpkg#10150]
**Describe the bug**
geotrans - The CONTROL file makes reference to version 3.8 but the _vcpkg-root_\ports\geotrans\portfile.cmake still contains logic to download version 3.7.

**Environment**
- OS: ALL
- Compiler: ALL

**To Reproduce**
- N/A

**Expected behavior**
Either the CONTROL file needs to be updated to version 3.7-2 (as other issues were addressed in the portfile.cmake update) or make changes to actually download and install version 3.8.

**Failure logs** 
- N/A

**Additional context**
- N/A

**Comment by timautry** [comment]
[geotrans-3.8-upgrade-files.zip](https://github.com/microsoft/vcpkg/files/4233694/geotrans-3.8-upgrade-files.zip)
- See attached file named geotrans-3.8-upgrade-files.zip:
  - includes updated files: 
     - CONTROL
     - CMakeFiles.txt
     - portfile.cmake
  - has necessary changes to download/install port GEOTRANS 3.8
 - I only tested it against VS2017 and VS2019 dynamic builds only
- Hopes this helps.
Thank you,

**Comment by LilyWangL** [comment]
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.
