### ISSUE TITLE
[New Port Request] tsduck

### ISSUE THREAD

**Issue by RonWuYi** [microsoft/vcpkg#10160]
Library name:
tsduck

Library description:
TSDuck is an extensible toolkit for MPEG/DVB transport streams.

Source repository URL:
https://github.com/tsduck/tsduck

Project homepage (if different from the source repository):
https://tsduck.io/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
N/A

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
