### ISSUE TITLE
What is the proper syntax for VCPKG_ENV_PASSTHROUGH?

### ISSUE THREAD

**Issue by ghost** [microsoft/vcpkg#10166]
What is the proper syntax for **VCPKG_ENV_PASSTHROUGH** in vcpkg triplets on Windows x64?
- I found information here "https://devblogs.microsoft.com/cppblog/vcpkg-2019-07-update/" but it does not give the syntax.
- I also found a discussions here "https://github.com/Microsoft/vcpkg/issues/3712", "https://github.com/microsoft/vcpkg/issues/7127" and "https://github.com/microsoft/vcpkg/issues/7328"
- I tried:
  - **set(VCPKG_ENV_PASSTHROUGH INCLUDE;LIB;LIBPATH)** in a custom triplet
  - **set VCPKG_ENV_PASSTHROUGH=INCLUDE;LIB;LIBPATH** in an environment variable
- Neither method allowed the variables to pass into a clean **.\vcpkg.exe env** command.
- I did find a discussion on **VCPKG_KEEP_ENV_VARS** here  "https://github.com/microsoft/vcpkg/blob/master/docs/users/config-environment.md", "https://vcpkg.readthedocs.io/en/latest/users/config-environment/#vcpkg_keep_env_vars" and "https://github.com/microsoft/vcpkg/issues/8950"
  - **set(VCPKG_KEEP_ENV_VARS INCLUDE;LIB;LIBPATH)** in a custom triplet
  - **set VCPKG_KEEP_ENV_VARS=INCLUDE;LIB;LIBPATH** in an environment variable 
- both worked and passed the variables into a clean **.\vcpkg.exe env** 

Since it seems both serve the same purpose, which should one use and if **VCPKG_ENV_PASSTHROUGH** is the correct method, what is the correct syntax?

**Comment by timautry** [comment]
I close, I no longer use product.

**Comment by cbezault** [comment]
See https://github.com/microsoft/vcpkg/blob/master/triplets/community/arm-mingw-dynamic.cmake
