### ISSUE TITLE
[Folly] linking folly and gflag

### ISSUE THREAD

**Issue by ayermolo** [microsoft/vcpkg#10169]
I am building folly using vcpkg and trying to link against it in VS 2017 project.
The Visual Solution can't find gflags_shared.lib.
Poking around looks like in folly-targets.cmake it lists: gflag_shared.
The gflags project itself builds, also using vcpkg, gflag.lib and gflag_debug.lib

Probably ports/folly/portfile.cmake can be modified to fix it up? This should do the trick:
string(REPLACE "gflags_shared" "\${_IMPORT_PREFIX}/\$<\$<CONFIG:DEBUG>:debug/>lib/gflags\$<\$<CONFIG:DEBUG>:_debug>.lib" _contents "${_contents}")

**Comment by PhoebeHui** [comment]
@ayermolo, thanks for reporting this issue!

Could you provide us repro code and repro steps?

**Comment by ayermolo** [comment]
@PhoebeHui Sorry for late reply. Tried it, and it also seems to work.

**Comment by PhoebeHui** [comment]
@ayermolo, thanks for the updates!

I will draft a PR for this.

**Comment by PhoebeHui** [comment]
@ayermolo, the PR has been merged, could you get latest source and try to build again?

**Comment by ayermolo** [comment]
@PhoebeHui yep works with latest. Thanks!
