### ISSUE TITLE
May I ask for the support for apr-util and apache2

### ISSUE THREAD

**Issue by Amarillys** [microsoft/vcpkg#1016]
I find that vcpkg only has the apr 1.5.2, but not apr-util and apache2.
Thanks a lot.

**Comment by OlafvdSpek** [comment]
Is apache2 a library?

**Comment by jumpinjackie** [comment]
I'm guessing @Amarillys is referring to the apache httpd server (that's also referred as apache2)

https://httpd.apache.org/

**Comment by atkawa7** [comment]
@Amarillys see #1363

**Comment by JackBoosY** [comment]
We can’t reopen this issue until a PR is opened, unfortunately, consider making a pull request!
