### ISSUE TITLE
[tesseract] Add port for creating dynamic library instead of command line

### ISSUE THREAD

**Issue by bleze** [microsoft/vcpkg#10174]
Installing tesseract will produce the command line version static linked with library. It would be nice to be able to build the dynamic link library of tesseract to be used from another application.
I know it's possible with CMake but that defeats the purpose of vcpkg.

**Comment by linquize** [comment]
modify `triplets/x64-linux.cmake`
change `VCPKG_LIBRARY_LINKAGE` to `dynamic`

**Comment by linquize** [comment]
To customize for own use,
modify `triplets/x64-linux.cmake`
change `VCPKG_LIBRARY_LINKAGE` to `dynamic`

**Comment by bleze** [comment]
@linquize, thanks! However it does not make a difference when I try it.
I'm building x64 on Win10, where the triplet is already set to dynamic. I changed it for the linux file anyways, but still I do not get the tesseract dll

**Comment by linquize** [comment]
Windows vcpkg default triplets (x86-windows, x64-windows)  are dynamic
x86-windows-static,  x64-windows-static are static

**Comment by bleze** [comment]
But, then it should work without changing any files? But it does not. Tesseract lib is linked static into command line exe. The dependencies like Leptonica is dynamic.

**Comment by kurinoku** [comment]
I have the exact same problem, it builds the executable (with its dependencies as dll) and the static library, but a tesseract.dll is nowhere to be found.
