### ISSUE TITLE
binary packages support

### ISSUE THREAD

**Issue by rkitover** [microsoft/vcpkg#10178]
I wrote a prototype for supporting binary packages in vcpkg in PowerShell:

https://github.com/rkitover/vcpkg-binpkg-prototype/

What do you guys think? Would it be worthwhile to work on this in the core?

**Comment by BillyONeal** [comment]
Packaging binaries is somewhat incompatible with our design goal of ensuring that the tree remains functional when any given port is updated because we can rebuild everything within that port's "cone of destruction". These kinds of issues are the primary reason why "NuGet for C++" became defunct and why we built vcpkg in the first place.

**Comment by BillyONeal** [comment]
Does the official binary caching feature @ras0219 and @ras0219-msft submitted described in https://github.com/microsoft/vcpkg/pull/11204 implement what you wanted here?

**Comment by rkitover** [comment]
My module actually makes perfectly functional binary packages, I need to make a few more tweaks to add the `Abi:` key etc., I'm actually thinking of making a binary package server.

**Comment by JackBoosY** [comment]
I think we will never provide pre-compiled binary packages.

**Comment by rkitover** [comment]
I'm actually considering switching to Conan for a project because it does provide binary packages and things like recompiling ffmpeg can get very tedious, plus it causes a lot of issues with the CI.

**Comment by JackBoosY** [comment]
@rkitover  Yep, I know that. but providing binary packages represents a lack of code security.

**Comment by BillyONeal** [comment]
I think we might provide binaries someday, but if we do it would be through the existing binary caching feature.
