### ISSUE TITLE
[openal-soft] Update to 1.20.1

### ISSUE THREAD

**Issue by past-due** [microsoft/vcpkg#10172]
Library name: OpenAL-soft

New version number: 1.20.1

Numerous important changes / fixes:

> openal-soft-1.20.1:
> 
>     Implemented the AL_SOFT_direct_channels_remix extension. This extends
>     AL_DIRECT_CHANNELS_SOFT to optionally remix input channels that don't have
>     a matching output channel.
> 
>     Implemented the AL_SOFT_bformat_ex extension. This extends B-Format buffer
>     support for N3D or SN3D scaling, or ACN channel ordering.
> 
>     Fixed a potential voice leak when a source is started and stopped or
>     restarted in quick succession.
> 
>     Fixed a potential device reset failure with JACK.
> 
>     Improved handling of unsupported channel configurations with WASAPI. Such
>     setups will now try to output at least a stereo mix.
> 
>     Improved clarity a bit for the HRTF second-order ambisonic decoder.
> 
>     Improved detection of compatible layouts for SOFA files in makemhr and
>     sofa-info.
> 
>     Added the ability to resample HRTFs on load. MHR files no longer need to
>     match the device sample rate to be usable.
> 
>     Added an option to limit the HRTF's filter length.

Source: https://github.com/kcat/openal-soft/blob/711c05613eceeda0e02a6c16080f725ff60cb33f/ChangeLog

**Comment by crackedmind** [comment]
But it's alreay 1.20.1 since February 10
https://github.com/microsoft/vcpkg/blob/master/ports/openal-soft/CONTROL#L2

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Port openal-soft has been updated to version 1.20.1 in PR #9986, you can update vcpkg and build it.
