### ISSUE TITLE
[qt5:x64-osx] build failure

### ISSUE THREAD

**Issue by zhangfuwen** [microsoft/vcpkg#10173]
**Host Environment**
- OS: [MacOS Catalina 10.15.3]
- Compiler: Apple clang version 11.0.0 (clang-1100.0.33.17)

**To Reproduce**
`./vcpkg install qt5:x64-osx`

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
```
Building package qt5-imageformats[core]:x64-osx...
-- Using cached /Users/dean/Projects/CLionProjects/vcpkg/downloads/qtimageformats-everywhere-src-5.12.5.tar.xz
-- Using source at /Users/dean/Projects/CLionProjects/vcpkg/buildtrees/qt5-imageformats/src/5.12.5-7ddf5dd29e
-- Configuring x64-osx-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: /Users/dean/Projects/CLionProjects/vcpkg/installed/x64-osx/tools/qt5/bin/qmake CONFIG-=debug CONFIG+=release CONFIG-=shared CONFIG*=static /Users/dean/Projects/CLionProjects/vcpkg/buildtrees/qt5-imageformats/src/5.12.5-7ddf5dd29e -qtconf /Users/dean/Projects/CLionProjects/vcpkg/buildtrees/qt5-imageformats/x64-osx-rel/qt.conf -- -system-tiff -system-webp -jasper -no-mng -verbose "TIFF_LIBS=/Users/dean/Projects/CLionProjects/vcpkg/installed/x64-osx/lib/libtiff.a /Users/dean/Projects/CLionProjects/vcpkg/installed/x64-osx/lib/liblzma.a" "WEBP_LIBS=/Users/dean/Projects/CLionProjects/vcpkg/installed/x64-osx/lib/libwebp.a /Users/dean/Projects/CLionProjects/vcpkg/installed/x64-osx/lib/libwebpdemux.a" "JASPER_LIBS=/Users/dean/Projects/CLionProjects/vcpkg/installed/x64-osx/lib/libjasper.a FREEGLUT_RELEASE-NOTFOUND"
    Working Directory: /Users/dean/Projects/CLionProjects/vcpkg/buildtrees/qt5-imageformats/x64-osx-rel
    Error code: 3
    See logs for more information:
      /Users/dean/Projects/CLionProjects/vcpkg/buildtrees/qt5-imageformats/config-x64-osx-rel-out.log
      /Users/dean/Projects/CLionProjects/vcpkg/buildtrees/qt5-imageformats/config-x64-osx-rel-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_qmake.cmake:61 (vcpkg_execute_required_process)
  installed/x64-osx/share/qt5/qt_build_submodule.cmake:10 (vcpkg_configure_qmake)
  installed/x64-osx/share/qt5/qt_submodule_installation.cmake:8 (qt_build_submodule)
  ports/qt5-imageformats/portfile.cmake:37 (qt_submodule_installation)
  scripts/ports.cmake:90 (include)


Error: Building package qt5-imageformats:x64-osx failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: qt5-imageformats:x64-osx
  Vcpkg version: 2020.02.04-unknownhash

Additionally, attach any relevant sections from the log files above.
```
-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by JackBoosY** [comment]
Hi @zhangfuwen, thanks for reporting this issue.
Please provide failure log _/Users/dean/Projects/CLionProjects/vcpkg/buildtrees/qt5-imageformats/config-x64-osx-rel-out.log_.

Thanks.

**Comment by zhangfuwen** [comment]
[config-x64-osx-rel-out.log](https://github.com/microsoft/vcpkg/files/4275759/config-x64-osx-rel-out.log)

@JackBoosY Hi, sorry for late reply. Attached above is the log.

**Comment by JackBoosY** [comment]
Could you also provide _/Users/dean/Projects/CLionProjects/vcpkg/buildtrees/qt5-imageformats/config-x64-osx-rel-err.log_ ?

Thanks.

**Comment by ashriram** [comment]
It seems to be related to this
" /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -stdlib=libc++ -headerpad_max_install_names  -arch x86_64 -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.15 -Wl,-rpath,@executable_path/../Frameworks -o jasper main.o   -L/Users/ashriram/.vcpkg/installed/x64-osx/lib -L/Users/ashriram/.vcpkg/installed/x64-osx/lib/manual-link /Users/ashriram/.vcpkg/installed/x64-osx/lib/libjasper.a FREEGLUT_RELEASE-NOTFOUND
> clang: error: no such file or directory: 'FREEGLUT_RELEASE-NOTFOUND"

**Comment by ashriram** [comment]
Done running configuration tests.

Configure summary:

Further Image Formats:
  JasPer ................................. no
  MNG .................................... no
  TIFF ................................... yes
    Using system libtiff ................. yes
  WEBP ................................... yes
    Using system libwebp ................. yes

ERROR: Feature 'jasper' was enabled, but the pre-condition 'features.imageformatplugin && libs.jasper' failed.

**Comment by JackBoosY** [comment]
confirmed.

**Comment by Neumann-A** [comment]
> 'FREEGLUT_RELEASE-NOTFOUND

see #9705
