### ISSUE TITLE
icu build failure

### ISSUE THREAD

**Issue by dargonforce** [microsoft/vcpkg#10179]
**Host Environment**
- OS: Windows 10
- Compiler: 

**To Reproduce**
`./vcpkg install icu:x64-windows`

**Failure logs** 
[log.txt](https://github.com/microsoft/vcpkg/files/4240587/log.txt)

**Additional context**
None

**Comment by PhoebeHui** [comment]
@dargonforce, could you try following steps:
1. Download http://repo.msys2.org/distrib/x86_64/msys2-base-x86_64-20181211.tar.xz manually
2. Put it to .\VCPKG\downloads\msys2-base-x86_64-20181211.tar.xz
3. Try to build again.

**Comment by dargonforce** [comment]
the build is working normally now, must have been a short outage from repo.msys2.org, thanks
