### ISSUE TITLE
[glib] BUILD_FAILED trying to install FluidSynth

### ISSUE THREAD

**Issue by cecilios** [microsoft/vcpkg#10176]
**Host Environment**
- OS: Windows 10 Home, version 1903, OS Build 18362.657
- Compiler: I don't know what vcpkg is using. I only installed MS Visual Studio.

**To Reproduce**
`./vcpkg install fluidsynth:x64-windows-static`

**Failure logs** 
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.4.4
** Copyright (c) 2019 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community>cd C:\Users\cecilio\source\repos\vcpkg

C:\Users\cecilio\source\repos\vcpkg>vcpkg install fluidsynth:x64-windows-static
Computing installation plan...
The following packages will be built and installed:
    fluidsynth[core]:x64-windows-static
  * gettext[core]:x64-windows-static
  * glib[core]:x64-windows-static
  * libffi[core]:x64-windows-static
  * libiconv[core]:x64-windows-static
  * pcre[core]:x64-windows-static
  * zlib[core]:x64-windows-static
Additional packages (*) will be modified to complete this operation.
Starting package 1/7: libiconv:x64-windows-static
Building package libiconv[core]:x64-windows-static...
-- Using cached C:/Users/cecilio/source/repos/vcpkg/downloads/libiconv-1.16.tar.gz
-- Using source at C:/Users/cecilio/source/repos/vcpkg/buildtrees/libiconv/src/1.16-de9101a181
-- Configuring x64-windows-static
-- Building x64-windows-static-dbg
-- Building x64-windows-static-rel
-- Installing: C:/Users/cecilio/source/repos/vcpkg/packages/libiconv_x64-windows-static/share/libiconv/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package libiconv[core]:x64-windows-static... done
Installing package libiconv[core]:x64-windows-static...
Installing package libiconv[core]:x64-windows-static... done
Elapsed time for package libiconv:x64-windows-static: 8.017 s
Starting package 2/7: gettext:x64-windows-static
Building package gettext[core]:x64-windows-static...
-- Using cached C:/Users/cecilio/source/repos/vcpkg/downloads/gettext-0.19.tar.gz
-- Using source at C:/Users/cecilio/source/repos/vcpkg/buildtrees/gettext/src/0.19-4325388200
-- Configuring x64-windows-static
-- Building x64-windows-static-dbg
-- Building x64-windows-static-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package gettext[core]:x64-windows-static... done
Installing package gettext[core]:x64-windows-static...
Installing package gettext[core]:x64-windows-static... done
Elapsed time for package gettext:x64-windows-static: 4.493 s
Starting package 3/7: libffi:x64-windows-static
Building package libffi[core]:x64-windows-static...
-- Using cached C:/Users/cecilio/source/repos/vcpkg/downloads/libffi-libffi-v3.3.tar.gz
-- Using source at C:/Users/cecilio/source/repos/vcpkg/buildtrees/libffi/src/v3.3-2d8a36299e
-- Configuring x64-windows-static
-- Building x64-windows-static-dbg
-- Building x64-windows-static-rel
-- Installing: C:/Users/cecilio/source/repos/vcpkg/packages/libffi_x64-windows-static/share/libffi/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package libffi[core]:x64-windows-static... done
Installing package libffi[core]:x64-windows-static...
Installing package libffi[core]:x64-windows-static... done
Elapsed time for package libffi:x64-windows-static: 4.74 s
Starting package 4/7: pcre:x64-windows-static
Building package pcre[core]:x64-windows-static...
-- Using cached C:/Users/cecilio/source/repos/vcpkg/downloads/pcre-8.41.zip
-- Using source at C:/Users/cecilio/source/repos/vcpkg/buildtrees/pcre/src/pcre-8-cf30a7ff9b
-- Configuring x64-windows-static
-- Building x64-windows-static-dbg
-- Building x64-windows-static-rel
-- Installing: C:/Users/cecilio/source/repos/vcpkg/packages/pcre_x64-windows-static/share/pcre/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package pcre[core]:x64-windows-static... done
Installing package pcre[core]:x64-windows-static...
Installing package pcre[core]:x64-windows-static... done
Elapsed time for package pcre:x64-windows-static: 30.66 s
Starting package 5/7: zlib:x64-windows-static
Building package zlib[core]:x64-windows-static...
-- Using cached C:/Users/cecilio/source/repos/vcpkg/downloads/zlib1211.tar.gz
-- Using source at C:/Users/cecilio/source/repos/vcpkg/buildtrees/zlib/src/1.2.11-deec42f53b
-- Configuring x64-windows-static
-- Building x64-windows-static-dbg
-- Building x64-windows-static-rel
-- Installing: C:/Users/cecilio/source/repos/vcpkg/packages/zlib_x64-windows-static/share/zlib/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package zlib[core]:x64-windows-static... done
Installing package zlib[core]:x64-windows-static...
Installing package zlib[core]:x64-windows-static... done
Elapsed time for package zlib:x64-windows-static: 6.101 s
Starting package 6/7: glib:x64-windows-static
Building package glib[core]:x64-windows-static...
-- Note: glib only supports dynamic library linkage. Building dynamic library.
CMake Error at scripts/cmake/vcpkg_check_linkage.cmake:42 (message):
  Refusing to build unexpected dynamic library against the static CRT.  If
  this is desired, please configure your triplet to directly request this
  configuration.
Call Stack (most recent call first):
  ports/glib/portfile.cmake:6 (vcpkg_check_linkage)
  scripts/ports.cmake:90 (include)

Error: Building package glib:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: glib:x64-windows-static
  Vcpkg version: 2020.02.04-nohash

Additionally, attach any relevant sections from the log files above.

C:\Users\cecilio\source\repos\vcpkg>

**Additional context**
New to vcpkg. Just trying to install FluidSynth and link it statically in my project.

**Comment by NancyLi1013** [comment]
Hi @cecilios 

Thanks for posting this issue.
Since `glib ` doesn't support static build for Windows.
The issue you encountered is intended.
Please refer to the detail info here #3409.

**Comment by cecilios** [comment]
Ok, thank you for the quick answer!
