### ISSUE TITLE
[libmysql:x64-osx] Building package libmysql:x64-osx failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by pourounas** [microsoft/vcpkg#10189]
**Host Environment**
- OS: x64-osx
- Compiler: revision

**To Reproduce**
`./vcpkg install libmysql
[config-x64-osx-dbg-err.log](https://github.com/microsoft/vcpkg/files/4242991/config-x64-osx-dbg-err.log)
[config-x64-osx-dbg-out.log](https://github.com/microsoft/vcpkg/files/4242994/config-x64-osx-dbg-out.log)

**Failure logs** 
-- Configuring x64-osx-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: /usr/local/Cellar/cmake/3.16.4/bin/cmake /Users/pourounas/dev/cpp/vcpkg/buildtrees/libmysql/src/ysql-8.0.4-a02d75c4bb -DWITHOUT_SERVER=ON -DWITH_UNIT_TESTS=OFF -DENABLED_PROFILING=OFF -DWIX_DIR=OFF -DHAVE_LLVM_LIBCPP_EXITCODE=1 -DSTACK_DIRECTION=-1 -DWINDOWS_RUNTIME_MD=ON -DIGNORE_BOOST_VERSION=ON -DWITH_SSL=system -DWITH_ICU=system -DWITH_LIBEVENT=system -DWITH_LZMA=system -DWITH_LZ4=system -DWITH_ZLIB=system -DCMAKE_MAKE_PROGRAM=/Users/pourounas/dev/cpp/vcpkg/downloads/tools/ninja-1.8.2-osx/ninja -DCMAKE_SYSTEM_NAME=Darwin -DBUILD_SHARED_LIBS=OFF -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/Users/pourounas/dev/cpp/vcpkg/scripts/toolchains/osx.cmake -DVCPKG_TARGET_TRIPLET=x64-osx -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=external -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=/Users/pourounas/dev/cpp/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_TARGET_ARCHITECTURE=x64 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/Users/pourounas/dev/cpp/vcpkg/packages/libmysql_x64-osx/debug
    Working Directory: /Users/pourounas/dev/cpp/vcpkg/buildtrees/libmysql/x64-osx-dbg
    Error code: 1
    See logs for more information:
      /Users/pourounas/dev/cpp/vcpkg/buildtrees/libmysql/config-x64-osx-dbg-out.log
      /Users/pourounas/dev/cpp/vcpkg/buildtrees/libmysql/config-x64-osx-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:304 (vcpkg_execute_required_process)
  ports/libmysql/portfile.cmake:38 (vcpkg_configure_cmake)
  scripts/ports.cmake:90 (include)

Error: Building package libmysql:x64-osx failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libmysql:x64-osx
  Vcpkg version: 2020.02.04-unknownhash

Additionally, attach any relevant sections from the log files above.

**Additional context**
Tried the below:
- ./vcpkg update

- git pull

**Comment by NancyLi1013** [comment]
Hi @pourounas 

Thanks for posting this issue.
It's duplicated to #5204.
