### ISSUE TITLE
Error: Building package opencv4:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by nicolas-gervais** [microsoft/vcpkg#10188]
**Host Environment**
- OS: Windows
- Compiler: revision

**To Reproduce**
`.\vcpkg install pthreads opencv[cuda,ffmpeg]`

**Failure logs** 
```
-- Downloading https://raw.githubusercontent.com/opencv/opencv_3rdparty/8afa57abc8229d611c4937165d20e2a2d9fc5a12/face_landmark_model.dat...
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: ninja -v
    Working Directory: C:/Users/Nicolas/Documents/vcpkg/buildtrees/opencv4/x86-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\Users\Nicolas\Documents\vcpkg\buildtrees\opencv4\config-x86-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:295 (vcpkg_execute_required_process)
  ports/opencv4/portfile.cmake:257 (vcpkg_configure_cmake)
  scripts/ports.cmake:90 (include)
```

**Comment by cenit** [comment]
Could you please post the content of the file `C:\Users\Nicolas\Documents\vcpkg\buildtrees\opencv4\config-x86-windows-out.log`?

**Comment by sampper** [comment]
I have a problem with openvc4[cuda] too, although mine is with x64-windows but I think the problem is the same.

-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: ninja -v
    Working Directory: C:/src/alt_vcpkg/vcpkg/buildtrees/opencv4/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\src\alt_vcpkg\vcpkg\buildtrees\opencv4\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:295 (vcpkg_execute_required_process)
  ports/opencv4/portfile.cmake:257 (vcpkg_configure_cmake)
  scripts/ports.cmake:90 (include)

[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/4285830/config-x64-windows-out.log)

CMake Error at C:/src/alt_vcpkg/vcpkg/scripts/buildsystems/vcpkg.cmake:217 (_add_library):
  Target "opencv_cudev" links to target "Threads::Threads" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

**Comment by sampper** [comment]
I downgraded cmake to release version  --     CMake: 3.16.4 from rc1  CMake: 3.17.0-rc1.

Now the Extra dependency Threads::Threads is gone and building is started correctly.

[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/4286144/config-x64-windows-out.log)

**Comment by cenit** [comment]
> I downgraded cmake to release version -- CMake: 3.16.4 from rc1 CMake: 3.17.0-rc1.
> 
> Now the Extra dependency Threads::Threads is gone and building is started correctly.
> 
> [config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/4286144/config-x64-windows-out.log)

Can you please open an issue upstream also to CMake?

**Comment by alexdewar** [comment]
I'm getting the same issue, even though I'm using CMake v3.16.4 :disappointed:

[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/4338273/config-x64-windows-out.log)

**Comment by cenit** [comment]
Your error is different: 

```
CMake Error at cmake/OpenCVFindProtobuf.cmake:67 (message):
  PROTOBUF_GENERATE_CPP command is not available
```

Looks like protobuf is not properly installed on your system. It should come down as a dependency of opencv... can you try to reinstall it?

**Comment by alexdewar** [comment]
Protobuf was installed (it showed up when I ran ``vcpkg list``), but I tried cleaning out my vcpkg install and rebuilding everything from scratch. I still got the same error, even when I explicitly installed protobuf before opencv..

**Comment by cenit** [comment]
mmm interesting. In order to try to reproduce the problem or find any anomaly, please write all your system and configuration details

**Comment by alexdewar** [comment]
@cenit I'm building on Windows 10 with the ``windows-x64`` triplet. What other configuration info would you like?

**Comment by alexdewar** [comment]
@cenit Ping?

**Comment by vsvrp-1995** [comment]
**Environment :** 
Windows 10 x64
cmake 3.16.6 (downgraded to it after build failed with 3.17 - same error)

**To Reproduce**
.\vcpkg install pthreads opencv[cuda,ffmpeg]

[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/4491324/config-x64-windows-out.log)
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/4491325/install-x64-windows-dbg-out.log)

**Ends up something like this**

Starting package 1/2: opencv4:x64-windows
Building package opencv4[contrib,core,cuda,dnn,ffmpeg,jpeg,opengl,png,tiff,webp]:x64-windows...
-- Using cached C:/vcpkg-master/downloads/opencv-opencv-4.1.1.tar.gz
-- Using source at C:/vcpkg-master/buildtrees/opencv4/src/4.1.1-fb9e10326a
-- Using cached C:/vcpkg-master/downloads/opencv-cache/tiny_dnn/adb1c512e09ca2c7a6faef36f9c53e59-v1.0.0a3.tar.gz
-- Using cached C:/vcpkg-master/downloads/opencv-cache/nvidia_optical_flow/ca5acedee6cb45d0ec610a6732de5c15-79c6cee80a2df9a196f20afd6b598a9810964c32.zip
-- Using cached C:/vcpkg-master/downloads/opencv-opencv_contrib-4.1.1.tar.gz
-- Using source at C:/vcpkg-master/buildtrees/opencv4/src/4.1.1-521dd00bd2
-- Using cached C:/vcpkg-master/downloads/opencv-cache/xfeatures2d/boostdesc/0ea90e7a8f3f7876d450e4149c97c74f-boostdesc_bgm.i
-- Using cached C:/vcpkg-master/downloads/opencv-cache/xfeatures2d/boostdesc/232c966b13651bd0e46a1497b0852191-boostdesc_bgm_bi.i
-- Using cached C:/vcpkg-master/downloads/opencv-cache/xfeatures2d/boostdesc/324426a24fa56ad9c5b8e3e0b3e5303e-boostdesc_bgm_hd.i
-- Using cached C:/vcpkg-master/downloads/opencv-cache/xfeatures2d/boostdesc/202e1b3e9fec871b04da31f7f016679f-boostdesc_binboost_064.i
-- Using cached C:/vcpkg-master/downloads/opencv-cache/xfeatures2d/boostdesc/98ea99d399965c03d555cef3ea502a0b-boostdesc_binboost_128.i
-- Using cached C:/vcpkg-master/downloads/opencv-cache/xfeatures2d/boostdesc/e6dcfa9f647779eb1ce446a8d759b6ea-boostdesc_binboost_256.i
-- Using cached C:/vcpkg-master/downloads/opencv-cache/xfeatures2d/boostdesc/0ae0675534aa318d9668f2a179c2a052-boostdesc_lbgm.i
-- Using cached C:/vcpkg-master/downloads/opencv-cache/xfeatures2d/vgg/e8d0dcd54d1bcfdc29203d011a797179-vgg_generated_48.i
-- Using cached C:/vcpkg-master/downloads/opencv-cache/xfeatures2d/vgg/7126a5d9a8884ebca5aea5d63d677225-vgg_generated_64.i
-- Using cached C:/vcpkg-master/downloads/opencv-cache/xfeatures2d/vgg/7cd47228edec52b6d82f46511af325c5-vgg_generated_80.i
-- Using cached C:/vcpkg-master/downloads/opencv-cache/xfeatures2d/vgg/151805e03568c9f490a5e3a872777b75-vgg_generated_120.i
-- Using cached C:/vcpkg-master/downloads/opencv-cache/data/7505c44ca4eb54b4ab1e4777cb96ac05-face_landmark_model.dat
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v
    Working Directory: C:/vcpkg-master/buildtrees/opencv4/x64-windows-dbg
    See logs for more information:
      C:\vcpkg-master\buildtrees\opencv4\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/opencv4/portfile.cmake:332 (vcpkg_install_cmake)
  scripts/ports.cmake:90 (include)


Error: Building package opencv4:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: opencv4:x64-windows
  Vcpkg version: 2020.02.04-nohash


Any quick help will be greatly appreciated.. thank you

**Comment by vsvrp-1995** [comment]
> **Host Environment**
> 
> * OS: Windows
> * Compiler: revision
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> `.\vcpkg install pthreads opencv[cuda,ffmpeg]`
> 
> **Failure logs**
> 
> ```
> -- Downloading https://raw.githubusercontent.com/opencv/opencv_3rdparty/8afa57abc8229d611c4937165d20e2a2d9fc5a12/face_landmark_model.dat...
> -- Configuring x86-windows
> CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
>     Command failed: ninja -v
>     Working Directory: C:/Users/Nicolas/Documents/vcpkg/buildtrees/opencv4/x86-windows-rel/vcpkg-parallel-configure
>     Error code: 1
>     See logs for more information:
>       C:\Users\Nicolas\Documents\vcpkg\buildtrees\opencv4\config-x86-windows-out.log
> 
> Call Stack (most recent call first):
>   scripts/cmake/vcpkg_configure_cmake.cmake:295 (vcpkg_execute_required_process)
>   ports/opencv4/portfile.cmake:257 (vcpkg_configure_cmake)
>   scripts/ports.cmake:90 (include)
> ```

Sorry if this sounds stupid.. initially I got that error ninja -v command failed... so I did this.. 
1. define new system variable, VCPKG_ROOT and make it point the location of the vcpkg folder.
2. define another system variable named VCPKG_DEFAULT_TRIPLET and set its value to x64-windows.

It seems this error is related to some lack of cuda support for x86 and so I need to make it x64 default in vcpkg.. something like that.. 

After doing all that .. i ended up with error I mentioned in above comment.

I was following this tutorial [https://medium.com/analytics-vidhya/installing-darknet-on-windows-462d84840e5a](url) to get darknet working on my windows.. Hope it helps

**Comment by NancyLi1013** [comment]
Hi all,
`opencv4 `has been update to 4.3.  Please update vcpkg to the latest version and try to rebuild this.
