### ISSUE TITLE
[<port name>] build failure

### ISSUE THREAD

**Issue by stephenanthonylewis** [microsoft/vcpkg#10184]
**Host Environment**
- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**
`./vcpkg install xxxx`

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by PhoebeHui** [comment]
It seems that you create a invalid bug. If not, please reopen this issue and fill the related information.
