### ISSUE TITLE
[New Port Request] <brpc>

### ISSUE THREAD

**Issue by how0723** [microsoft/vcpkg#10190]
Library name: brpc

Library description: Industrial-grade RPC framework used throughout Baidu, with 1,000,000+ instances and thousands kinds of services, called "baidu-rpc" inside Baidu.

Source repository URL: https://github.com/apache/incubator-brpc

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
