### ISSUE TITLE
[opencv3]build failure

### ISSUE THREAD

**Issue by RollingIsland** [microsoft/vcpkg#10195]
**Host Environment**
- OS: Windows 10

**To Reproduce**
`.\vcpkg install opencv3[nonfree,contrib,cuda]:x64-windows`

**Failure logs** 
The following packages will be built and installed:
    opencv3[contrib,core,cuda,dnn,flann,jpeg,nonfree,opengl,png,tiff,webp]:x64-windows
Starting package 1/1: opencv3:x64-windows
Building package opencv3[contrib,core,cuda,dnn,flann,jpeg,nonfree,opengl,png,tiff,webp]:x64-windows...
-- Using cached E:/vcpkg/downloads/opencv-opencv-3.4.7.tar.gz
-- Using source at E:/vcpkg/buildtrees/opencv3/src/3.4.7-76c703aeb9
-- Using cached E:/vcpkg/downloads/opencv-cache/tiny_dnn/adb1c512e09ca2c7a6faef36f9c53e59-v1.0.0a3.tar.gz
-- Using cached E:/vcpkg/downloads/opencv-opencv_contrib-3.4.7.tar.gz
-- Using source at E:/vcpkg/buildtrees/opencv3/src/3.4.7-8b40424ca7
-- Using cached E:/vcpkg/downloads/opencv-cache/data/7505c44ca4eb54b4ab1e4777cb96ac05-face_landmark_model.dat
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- mt.exe has failed. This may be the result of anti-virus. Disabling anti-virus on the buildtree folder may improve build speed
-- Restarting Build x64-windows-rel because of mt.exe file locking issue. Iteration: 1
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:114 (file):
  file failed to open for reading (No such file or directory):

    E:/vcpkg/-out-1.log
Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/opencv3/portfile.cmake:301 (vcpkg_install_cmake)
  scripts/ports.cmake:94 (include)

Error: Building package opencv3:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: opencv3:x64-windows
  Vcpkg version: 2019.09.12-nohash

**Additional context**
I closed my anti-virus program but no help.

**Comment by RollingIsland** [comment]
Solved. The solution is to run Windows PowerShell as Administrator.

**Comment by LilyWangL** [comment]
@RollingIsland, it seems you solved the issue, feel free reopen this issue if it still be a problem for you.
