### ISSUE TITLE
How do I undefine a MACRO

### ISSUE THREAD

**Issue by hotbroker** [microsoft/vcpkg#10193]
here is piece of code in libcurl:
```
#include "curl_setup.h"
#ifndef HAVE_SOCKETPAIR
int Curl_socketpair(int domain, int type, int protocol,
                    curl_socket_t socks[2]);
#else
#define Curl_socketpair(a,b,c,d) socketpair(a,b,c,d)
#endif

/* Defined here to allow specific build configs to disable it completely */
#define USE_SOCKETPAIR 1

#endif /* HEADER_CURL_SOCKETPAIR_H */
```
i would like to un define USE_SOCKETPAIR ,how do i do that .i know there r some config inside port directory from vcpkg,but i just dont know how to do that .I would appreciate that if someone can help me out

**Comment by JackBoosY** [comment]
I checked the source code and did not define `HAVE_SOCKETPAIR` anywhere. This macro should not be enabled.

**Comment by hotbroker** [comment]
> I checked the source code and did not define `HAVE_SOCKETPAIR` anywhere. This macro should not be enabled.

u r right,but this is NOT what I care( FYI,source code will implement Curl_socketpair by it own,  instead calling API)

I just want to know if it is ok to remove the "socketpair system",controled by the "**USE_SOCKETPAIR** "

**Comment by JackBoosY** [comment]
@hotbroker That's okay, but that's personal customization.
You need to modify source code in _VCPKG_PATH/buildtrees/curl/src/url_*_.
Just change `#ifndef HAVE_SOCKETPAIR` to `#if 0` will solve your issue. I guess.

**Comment by hotbroker** [comment]
> @hotbroker That's okay, but that's personal customization.
> You need to modify source code in _VCPKG_PATH/buildtrees/curl/src/url_*_.
> Just change `#ifndef HAVE_SOCKETPAIR` to `#if 0` will solve your issue. I guess.

well,if i do it in this way,I know how it works。but I remove & install this lib  after changing source code , didnt the vcpkge will release a new package of source code again?

so eventually it may not work,I tested this on zlib

**Comment by JackBoosY** [comment]
@hotbroker You may need to patch to complete these tasks, and use the patch in `portfile.cmake`.
Since I'm not sure if this feature is officially supported, I recommend against using it as a feature.

**Comment by hotbroker** [comment]
> @hotbroker You may need to patch to complete these tasks, and use the patch in `portfile.cmake`.
> Since I'm not sure if this feature is officially supported, I recommend against using it as a feature.

老铁，你是中国人啊？哈。按你那么说的，我要去修改cmake了

**Comment by JackBoosY** [comment]
@hotbroker 个人的修改我建议打patch，基准目录是VCPKG_PATH/buildtrees/curl/url-*，以此为基准用`git init .`来打补丁，然后把补丁放到VCPKG_PATH/ports/curl里面。
以后如果更新版本也没关系，直接revert `portfile.cmake`然后`git pull`，最后把补丁加到`portfile.cmake`里面就行了。
不过有可能更新导致你打补丁的文件修改了，从而使补丁失效。这时候你得重新打一次。

**Comment by hotbroker** [comment]
> @hotbroker 个人的修改我建议打patch，基准目录是VCPKG_PATH/buildtrees/curl/url-*，以此为基准用`git init .`来打补丁，然后把补丁放到VCPKG_PATH/ports/curl里面。
> 以后如果更新版本也没关系，直接revert `portfile.cmake`然后`git pull`，最后把补丁加到`portfile.cmake`里面就行了。
> 不过有可能更新导致你打补丁的文件修改了，从而使补丁失效。这时候你得重新打一次。

目前看应该是只能改这里了。暂时先这样吧，谢谢了。cmake还不是很会看，里面有些变量都不知道哪 来。

**Comment by JackBoosY** [comment]
cmake自带一些变量，如果不是`VCPKG_`开头的或者在source中搜不到，可以去cmake官网搜一下。
