### ISSUE TITLE
Installation of gRPC results in incomplete installation

### ISSUE THREAD

**Issue by pvvl** [Microsoft/vcpkg#1019]
Tried this on a Windows7:
$ ./vcpkg install grpc
The following packages will be built and installed:
    grpc:x86-windows
Building package grpc:x86-windows...
-- CURRENT_INSTALLED_DIR=C:/j/18a/Middleware/vcpkg/installed/x86-windows
-- DOWNLOADS=C:/j/18a/Middleware/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/j/18a/Middleware/vcpkg/packages/grpc_x86-windows
-- CURRENT_BUILDTREES_DIR=C:/j/18a/Middleware/vcpkg/buildtrees/grpc
-- CURRENT_PORT_DIR=C:/j/18a/Middleware/vcpkg/ports/grpc/.
-- Warning: Dynamic building not supported yet. Building static.
-- Using cached C:/j/18a/Middleware/vcpkg/downloads/grpc-v1.2.3.tar.gz
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Configuring x86-windows-rel
-- Configuring x86-windows-rel done
-- Configuring x86-windows-dbg
-- Configuring x86-windows-dbg done
-- Package x86-windows-rel
-- Package x86-windows-rel done
-- Package x86-windows-dbg
-- Package x86-windows-dbg done
-- Installing: C:/j/18a/Middleware/vcpkg/packages/grpc_x86-windows/share/grpc/copyright
-- Performing post-build validation
There should be no empty directories in C:/j/18a/Middleware/vcpkg/packages/grpc_x86-windows
The following empty directories were found:

    C:/j/18a/Middleware/vcpkg/packages/grpc_x86-windows/tools

If a directory should be populated but is not, this might indicate an error in the portfile.
If the directories are not needed and their creation cannot be disabled, use something like this in the portfile to remove them:

    file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/a/dir ${CURRENT_PACKAGES_DIR}/some/other/dir)

Found 1 error(s). Please correct the portfile:
    C:\j\18a\Middleware\vcpkg\ports\grpc\portfile.cmake
-- Performing post-build validation done
Error: Building package grpc:x86-windows failed with: POST_BUILD_CHECKS_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: grpc:x86-windows
  Vcpkg version: 0.0.80-89ad7d6b22e71ed058c2386c147154603da4bee9

Additionally, attach any relevant sections from the log files above.

**Comment by ras0219-msft** [comment]
Thanks for reporting this issue!

I've moved the `MAKE_DIRECTORY` call into a conditional statement, which should fix your issue, in 8df90aa. Could you please pull and confirm this fixes your issue?

**Comment by pvvl** [comment]
Hi Robert,

Your change worked like a charm on 64 bit, thanks for that!

32 bit builds now fail where previously they did not, so I cannot confirm that your change worked on 32 bit.
For some reason, openssl does not build on 32 bit anymore now.
This is the output from the attempt to install openssl on 32 bit from vcpkg:

The following packages will be built and installed:
    openssl:x86-windows
Building package openssl:x86-windows...
-- CURRENT_INSTALLED_DIR=C:/j/18a/Middleware/vcpkg/installed/x86-windows
-- DOWNLOADS=C:/j/18a/Middleware/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/j/18a/Middleware/vcpkg/packages/openssl_x86-windows
-- CURRENT_BUILDTREES_DIR=C:/j/18a/Middleware/vcpkg/buildtrees/openssl
-- CURRENT_PORT_DIR=c:/j/18a/Middleware/vcpkg/ports/openssl/.
-- Using cached C:/j/18a/Middleware/vcpkg/downloads/openssl-1.0.2k.tar.gz
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting source C:/j/18a/Middleware/vcpkg/downloads/openssl-1.0.2k.tar.gz
-- Extracting done
-- Applying patch C:/j/18a/Middleware/vcpkg/ports/openssl/PerlScriptSpaceInPathFixes.patch
-- Applying patch C:/j/18a/Middleware/vcpkg/ports/openssl/PerlScriptSpaceInPathFixes.patch done
-- Applying patch C:/j/18a/Middleware/vcpkg/ports/openssl/ConfigureIncludeQuotesFix.patch
-- Applying patch C:/j/18a/Middleware/vcpkg/ports/openssl/ConfigureIncludeQuotesFix.patch done
-- Applying patch C:/j/18a/Middleware/vcpkg/ports/openssl/STRINGIFYPatch.patch
-- Applying patch C:/j/18a/Middleware/vcpkg/ports/openssl/STRINGIFYPatch.patch done
-- Build x86-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:14 (message):
    Command failed: NMAKE-NOTFOUND;-f;ms\ntdll.mak;install
    Working Directory: C:/j/18a/Middleware/vcpkg/buildtrees/openssl/x86-windows-rel/openssl-1.0.2k
    See logs for more information:
      C:\j\18a\Middleware\vcpkg\buildtrees\openssl\build-x86-windows-rel-out.log
      C:\j\18a\Middleware\vcpkg\buildtrees\openssl\build-x86-windows-rel-err.log

Call Stack (most recent call first):
  ports/openssl/portfile.cmake:65 (vcpkg_execute_required_process)
  scripts/ports.cmake:73 (include)


Error: Building package openssl:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openssl:x86-windows
  Vcpkg version: 0.0.81-e1a111ad09d74a5b683635000e34bcc38c717d45

Additionally, attach any relevant sections from the log files above.

**Comment by NancyLi1013** [comment]
Please open a new issue if this is still a problem for you.
