### ISSUE TITLE
[New Port Request] <Caffe>

### ISSUE THREAD

**Issue by akamrecs** [microsoft/vcpkg#10198]
Library name: Caffe

Library description: Caffe, a fast open framework for deep learning.

Source repository URL: https://github.com/BVLC/caffe

Project homepage: http://caffe.berkeleyvision.org/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by traversaro** [comment]
Related issue: https://github.com/microsoft/vcpkg/issues/8093 .

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
