### ISSUE TITLE
vcpkg integrate install error

### ISSUE THREAD

**Issue by merlinio2000** [Microsoft/vcpkg#102]
Im using Windows 10 Anniversary Update with the de-ch locale.
I can download any package just fine but when I try to use vcpkg integrate install I get:
Error: failed to copy targets file to C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\ImportBefore\Default\vcpkg.system.props

Any help is appreciated. Thanks.

**Comment by phsucharee** [comment]
That error should have been fixed by https://github.com/Microsoft/vcpkg/commit/1402262962f9f29faa1c611b78b793a389a13843 as far as I know. It fixed that for me.

**Comment by merlinio2000** [comment]
thanks alot turns out I cloned the repository just before the fix.
