### ISSUE TITLE
[New Port Request] KWSys

### ISSUE THREAD

**Issue by Pospelove** [microsoft/vcpkg#10203]
**Library name:**

KWSys

**Library description:**

KWSys is the Kitware System Library.  It provides platform-independent
APIs to many common system features that are implemented differently on
every platform.  This library is intended to be shared among many
projects at the source level, so it has a configurable namespace.

**Source repository URL:**

https://gitlab.kitware.com/utils/kwsys

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by Pospelove** [comment]
I can't

**Comment by Pospelove** [comment]
![image](https://user-images.githubusercontent.com/37947786/130444563-fe13bcc0-1b0f-47a3-a73b-f93519192eea.png)
