### ISSUE TITLE
Invalid option value: '-Source'

### ISSUE THREAD

**Issue by SSouper** [microsoft/vcpkg#10206]
**Describe the bug**
Upon running vcpkg install whatever after bootstrapping, it goes ahead and downloads whatever it needs but it fails extracting 7zip with this error message:

`Failed to extract 'C:\Users\redacted\vcpkg\downloads\7-zip.commandline.18.1.0.nupkg' with message:
Invalid option value: '-Source C:\Users\redacted\vcpkg\downloads'
NuGet.CommandLine.CommandLineException: Invalid option value: '-Source C:\Users\redacted\vcpkg\downloads'
   at NuGet.CommandLine.CommandLineParser.AssignValue(Object command, PropertyInfo property, String option, Object value)
   at NuGet.CommandLine.CommandLineParser.ExtractOptions(ICommand command, IEnumerator`1 argsEnumerator)
   at NuGet.CommandLine.CommandLineParser.ParseCommandLine(IEnumerable`1 commandLineArgs)
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String args)
`

**Environment**
- OS: Up to date Windows 10 Pro
- Compiler: No idea but it compiles :P

**To Reproduce**
1. ./vcpkg install whateverpackage
2. See error
**Expected behavior**
It installs cmake/7zip/whatever it needs and carries on building desired package.

**Failure logs** 
-see desc

**Additional context**
-

**Comment by PhoebeHui** [comment]
@supertransformer, I can't repro this issue with latest vcpkg source, could you get vcpkg clean source and see if this issue still occur?


PS E:\vcpkg\clean\vcpkg> ./vcpkg install nlohmann-json
Computing installation plan...
The following packages will be built and installed:
    nlohmann-json[core]:x86-windows
Starting package 1/1: nlohmann-json:x86-windows
Building package nlohmann-json[core]:x86-windows...
A suitable version of powershell-core was not found (required v6.2.1). Downloading portable powershell-core v6.2.1...
Downloading powershell-core...
  https://github.com/PowerShell/PowerShell/releases/download/v6.2.1/PowerShell-6.2.1-win-x86.zip -> E:\vcpkg\clean\vcpkg\downloads\PowerShell-6.2.1-win-x86.zip
Extracting powershell-core...
A suitable version of 7zip was not found (required v18.1.0). Downloading portable 7zip v18.1.0...
Downloading 7zip...
  https://www.nuget.org/api/v2/package/7-Zip.CommandLine/18.1.0 -> E:\vcpkg\clean\vcpkg\downloads\7-zip.commandline.18.1.0.nupkg
Extracting 7zip...
A suitable version of nuget was not found (required v4.6.2). Downloading portable nuget v4.6.2...
Downloading nuget...
  https://dist.nuget.org/win-x86-commandline/v4.6.2/nuget.exe -> E:\vcpkg\clean\vcpkg\downloads\nuget.exe
A suitable version of git was not found (required v2.21.0). Downloading portable git v2.21.0...
Downloading git...
  https://github.com/git-for-windows/git/releases/download/v2.21.0.windows.1/PortableGit-2.21.0-32-bit.7z.exe -> E:\vcpkg\clean\vcpkg\downloads\PortableGit-2.21.0-32-bit.7z.exe
Extracting git...

**Comment by supertransformer** [comment]
@PhoebeHui I got a clean source and [this](https://www.youtube.com/watch?v=Duz_CqFbNyU) is what happened.

**Comment by PhoebeHui** [comment]
@supertransformer, thanks for your updates, could you add the failure message? the vedio is not clear.

**Comment by PhoebeHui** [comment]
We haven't been able to repro this, if more information comes up, or this issue appears again, please reopen.
