### ISSUE TITLE
add cmd to the instructions

### ISSUE THREAD

**Issue by akilisosa** [microsoft/vcpkg#10219]
****

**Is your feature request related to a problem? Please describe.**

I believe the documentation for vcpkg needs to be updated. I worked through the instructions in gitbash and powershell on a windows 10 computer, everything went well until the end when i was trying to run vcpkg as a command, and it wasn't recognized. I asked for help, and then somebody told me i should try using the regular cmd and it worked. 

**Proposed solution**

I think there should be a suggestion to use the cmd in the documentation

**Describe alternatives you've considered**

alter the instructions entirely to include the cmd where bash and PS commands are

**Additional context**

I realize here im not in the right folder, but if i navigate to the vcpkg i get the same error. 

![Capture9](https://user-images.githubusercontent.com/18223349/75308738-2c5fe780-581d-11ea-9111-d4b7198c2029.PNG)

This works with the regular command prompt:
![Capture10](https://user-images.githubusercontent.com/18223349/75308741-2f5ad800-581d-11ea-9607-7a31ff9b695b.PNG)

gitbash doesn't work: 
![Capture](https://user-images.githubusercontent.com/18223349/75308802-56b1a500-581d-11ea-898e-6c5bdbc015cd.PNG)

**Comment by timautry** [comment]
@akilisosa 

vcpkg does NOT modify system environment variables, such as PATH.
That said:
  - it requires one to know where the vcpkg instance was installed
  - the current directory must be the **_vcpkg-root_** location (as vcpkg would not be able to find it's files and directory structure). In other words, vcpkg was not designed to execute from just any directory/folder on the installed machine
  - and Basic Windows/Linux/Unix command line 101:
     - For gitbash ask linux/unix (bash, ksh, csh, etc) - go to the **vcpkg-root** directory (appears it is akili@LAPTOP-1GL3CKR1 MINGW64 ~/Documents/vcpkg (master)) and type: ./vcpkg _command options_
     - For windows (either cmd or powershell) - go to the **vcpkg-root** directory and type: vcpkg, or .\vcpkg or vcpkg.exe or .\vcpkg.exe _command options_

**Comment by akilisosa** [comment]
@timautry 
Thank you so much! I realize if I had a better understanding of the command line I wouldn't have run into this problem. All those commands worked. I saw three or four other posts similar to this one. Maybe it would be helpful to include information about this in the readme file.

**Comment by akilisosa** [comment]
I see that the actual problem is that I didn't read the documentation thoroughly enough because you do have an examples page that goes over this.  My mistake.

**Comment by timautry** [comment]
@akilisosa - thank you for the feedback. I am just someone who volunteers to help when I see issues I have experienced in the past few month. I am in no way able to make decide how vcpkg is documented, enhanced and/or maintained. I will cc this to those I have seen who do most of the trouble shooting, maintenance and enhancing :)
cc: @JackBoosY @NancyLi1013 @PhoebeHui

**Comment by strega-nil** [comment]
I believe the documentation has been updated to fix this?
