### ISSUE TITLE
[thread] build failure on x64-windows

### ISSUE THREAD

**Issue by AjitDingankar** [microsoft/vcpkg#10218]
**Host Environment**
- OS: Windows
- Compiler: Microsoft (R) C/C++ Optimizing Compiler Version 19.24.28316 for x86

**To Reproduce**
`./vcpkg install boost:x64-windows`

**Failure logs** 
Starting package 67/148: boost-thread:x64-windows
Building package boost-thread[core]:x64-windows...
-- Using cached C:/Users/adingank/git/vcpkg/downloads/boostorg-thread-boost-1.72.0.tar.gz
-- Extracting source C:/Users/adingank/git/vcpkg/downloads/boostorg-thread-boost-1.72.0.tar.gz
CMake Error at scripts/cmake/vcpkg_extract_source_archive_ex.cmake:140 (file):
  file RENAME failed to rename

    C:/Users/adingank/git/vcpkg/buildtrees/boost-thread/src/TEMP/thread-boost-1.72.0

  to

    C:/Users/adingank/git/vcpkg/buildtrees/boost-thread/src/ost-1.72.0-af57bfeb4d

  because: No such file or directory

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:139 (vcpkg_extract_source_archive_ex)
  ports/boost-thread/portfile.cmake:5 (vcpkg_from_github)
  scripts/ports.cmake:90 (include)

Error: Building package boost-thread:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-thread:x64-windows
  Vcpkg version: 2020.02.04-nohash

**Additional context**
Previously I had tried just the `vcpkg install boost` which defaulted to the x86 architecture, 
and ran into similar issues.

**Comment by NancyLi1013** [comment]
Hi @AjitDingankar 

Thanks for posting this issue.
Could you please try to remove _C:/Users/adingank/git/vcpkg/buildtrees/boost-thread_ and build it again?

**Comment by AjitDingankar** [comment]
Thanks, Nancy! Tried your suggestion, and it went past boost-thread but got similar problems with 
boost-phoenix now; so will retry similar approach. 

```
Starting package 6/82: boost-phoenix:x64-windows
Building package boost-phoenix[core]:x64-windows...
-- Downloading https://github.com/boostorg/phoenix/archive/boost-1.72.0.tar.gz...
-- Extracting source C:/Users/adingank/git/vcpkg/downloads/boostorg-phoenix-boost-1.72.0.tar.gz
CMake Error at scripts/cmake/vcpkg_extract_source_archive_ex.cmake:140 (file):
  file RENAME failed to rename

    C:/Users/adingank/git/vcpkg/buildtrees/boost-phoenix/src/TEMP/phoenix-boost-1.72.0

  to

    C:/Users/adingank/git/vcpkg/buildtrees/boost-phoenix/src/ost-1.72.0-d6c0ef9714

  because: No such file or directory

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:139 (vcpkg_extract_source_archive_ex)
  ports/boost-phoenix/portfile.cmake:5 (vcpkg_from_github)
  scripts/ports.cmake:90 (include)


Error: Building package boost-phoenix:x64-windows failed with: BUILD_FAILED
```

**Comment by AjitDingankar** [comment]
Went through similar exercise for boost-spirit, but it doesn't work for that case! :-( 
The errors are shown below: 
```
Starting package 1/74: boost-spirit:x64-windows
Building package boost-spirit[core]:x64-windows...
-- Using cached C:/Users/adingank/git/vcpkg/downloads/boostorg-spirit-boost-1.72.0.tar.gz
-- Extracting source C:/Users/adingank/git/vcpkg/downloads/boostorg-spirit-boost-1.72.0.tar.gz
CMake Error at scripts/cmake/vcpkg_extract_source_archive_ex.cmake:140 (file):
  file RENAME failed to rename

    C:/Users/adingank/git/vcpkg/buildtrees/boost-spirit/src/TEMP/spirit-boost-1.72.0

  to

    C:/Users/adingank/git/vcpkg/buildtrees/boost-spirit/src/ost-1.72.0-ae9686f115

  because: No such file or directory

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:139 (vcpkg_extract_source_archive_ex)
  ports/boost-spirit/portfile.cmake:5 (vcpkg_from_github)
  scripts/ports.cmake:90 (include)


Error: Building package boost-spirit:x64-windows failed with: BUILD_FAILED
```

**Comment by NancyLi1013** [comment]
Hi @AjitDingankar 

Could you please try to use `powershell `to build this?

**Comment by AjitDingankar** [comment]
Same error in powershell: 

```
Starting package 1/74: boost-spirit:x64-windows
Building package boost-spirit[core]:x64-windows...
-- Using cached C:/Users/adingank/git/vcpkg/downloads/boostorg-spirit-boost-1.72.0.tar.gz
-- Extracting source C:/Users/adingank/git/vcpkg/downloads/boostorg-spirit-boost-1.72.0.tar.gz
CMake Error at scripts/cmake/vcpkg_extract_source_archive_ex.cmake:140 (file):
  file RENAME failed to rename

    C:/Users/adingank/git/vcpkg/buildtrees/boost-spirit/src/TEMP/spirit-boost-1.72.0

  to

    C:/Users/adingank/git/vcpkg/buildtrees/boost-spirit/src/ost-1.72.0-ae9686f115

  because: No such file or directory

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:139 (vcpkg_extract_source_archive_ex)
  ports/boost-spirit/portfile.cmake:5 (vcpkg_from_github)
  scripts/ports.cmake:90 (include)


Error: Building package boost-spirit:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-spirit:x64-windows
  Vcpkg version: 2020.02.04-nohash

Additionally, attach any relevant sections from the log files above.
PS C:\Users\adingank>
```

**Comment by NancyLi1013** [comment]
@AjitDingankar 
Could you please help confirm if you have permission to rename these files?
Since I noticed vcpkg was cloned in _C:/Users/adingank/git/_.
Please also try to remove this file and build again.
`C:/Users/adingank/git/vcpkg/downloads/boostorg-spirit-boost-1.72.0.tar.gz`

**Comment by AjitDingankar** [comment]
Just confirmed that I can rename the above file manually. 
```
C:\Users\adingank\git\vcpkg\buildtrees\boost-spirit\src>rename TEMP\spirit-boost-1.72.0 ost-1.72.0-ae9686f115

C:\Users\adingank\git\vcpkg\buildtrees\boost-spirit\src>dir TEMP
 Volume in drive C is OSDisk
 Volume Serial Number is 8A8B-1D3C

 Directory of C:\Users\adingank\git\vcpkg\buildtrees\boost-spirit\src\TEMP

02/28/2020  08:49 AM    <DIR>          .
02/28/2020  08:49 AM    <DIR>          ..
02/27/2020  09:01 AM                 0 boostorg-spirit-boost-1.72.0.tar.gz.extracted
12/05/2019  02:23 PM    <DIR>          ost-1.72.0-ae9686f115
               1 File(s)              0 bytes
               3 Dir(s)  351,268,253,696 bytes free
```
However, I'm confused by the fact that the original script tried to use the rename command to move the file from TEMP to the parent directory src.

**Comment by AjitDingankar** [comment]
Built after removing 
```
C:/Users/adingank/git/vcpkg/downloads/boostorg-spirit-boost-1.72.0.tar.gz
```
and got the same error as before.

**Comment by NancyLi1013** [comment]
@AjitDingankar 
Sorry for the late reply.
I am also not sure what happended to your environment.
Could you please try to clone vcpkg to another directory that is not in `C:/` and try to build this again?

**Comment by AjitDingankar** [comment]
I don't understand; ALL my files are under C: on the Windows laptop which only has one disk!

**Comment by NancyLi1013** [comment]
Sorry, I don't know you only have one disk. 
Since I cannot reproduce this issue and also have no idea about this.
I suggest that you clone vcpkg to a clean environment and try it again.

**Comment by AjitDingankar** [comment]
Re: "Sorry, I don't know you only have one disk." 
Even if I had a second disk, what difference would it have made? 
It'd probably be named "D:" instead of "C:"! 

Re: "I cannot reproduce this issue and also have no idea about this."
Is there any developer who can take a look at this? 

Re: "I suggest that you clone vcpkg to a clean environment and try it again."
I will do so, but wanted to make sure what you mean by "a clean environment" since I had 
a fresh clone to start with!

**Comment by AjitDingankar** [comment]
Removed the buildtrees folder
Ran vcpkg update
Ran git pull 

Still got the same errors! I'm about to give up on vcpkg...

**Comment by JackBoosY** [comment]
There are actually two reasons for this:
1. Cmake bug.
I've faced the same issue before. Related: #4245.

2. Permission.
Because the C drive is a system drive, you need to clone vcpkg in a folder that does not require administrator permissions to read and write, such as _C:\Users\\$USR\Documents_.

**Comment by AjitDingankar** [comment]
Thanks for the pointers! 

1. I don't really understand what the *resolution* was that I could follow. I think it refers to Docker 
env, whereas I'm working on a physical Windows machine. 

2. I had indeed cloned vcpkg in my home directory so permissions should not be an issue. Also, it 
fails at various places after installing some packages. If it were a permissions issue it should always 
have failed on the first package, I think.

**Comment by AjitDingankar** [comment]
I just cloned vcpkg again in %USERPROFILE%/git folder and tried it again: 
```
vcpkg install boost:x64-windows
```
After installing 5 packages it fails with the same error: 
```
Starting package 5/148: boost-core:x64-windows
Building package boost-core[core]:x64-windows...
-- Downloading https://github.com/boostorg/core/archive/boost-1.72.0.tar.gz...
-- Extracting source C:/Users/adingank/git/vcpkg/downloads/boostorg-core-boost-1.72.0.tar.gz
-- Using source at C:/Users/adingank/git/vcpkg/buildtrees/boost-core/src/ost-1.72.0-be0b21b1c0
-- Packaging headers
-- Packaging headers done
-- Using cached C:/Users/adingank/git/vcpkg/downloads/boost_LICENSE_1_0.txt
-- Installing: C:/Users/adingank/git/vcpkg/packages/boost-core_x64-windows/share/boost-core/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package boost-core[core]:x64-windows... done
Installing package boost-core[core]:x64-windows...
Installing package boost-core[core]:x64-windows... done
Elapsed time for package boost-core:x64-windows: 3.311 s
Starting package 6/148: boost-preprocessor:x64-windows
Building package boost-preprocessor[core]:x64-windows...
-- Downloading https://github.com/boostorg/preprocessor/archive/boost-1.72.0.tar.gz...
-- Extracting source C:/Users/adingank/git/vcpkg/downloads/boostorg-preprocessor-boost-1.72.0.tar.gz
CMake Error at scripts/cmake/vcpkg_extract_source_archive_ex.cmake:140 (file):
  file RENAME failed to rename

    C:/Users/adingank/git/vcpkg/buildtrees/boost-preprocessor/src/TEMP/preprocessor-boost-1.72.0

  to

    C:/Users/adingank/git/vcpkg/buildtrees/boost-preprocessor/src/ost-1.72.0-a796360b87

  because: No such file or directory

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:139 (vcpkg_extract_source_archive_ex)
  ports/boost-preprocessor/portfile.cmake:5 (vcpkg_from_github)
  scripts/ports.cmake:90 (include)

Error: Building package boost-preprocessor:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-preprocessor:x64-windows
  Vcpkg version: 2020.02.04-nohash
```
However, the source directory exists and the parent of the target is writeable: 
```
adingank@adingank-MOBL1 MINGW64 ~/git/vcpkg (master)
$ ls -l buildtrees/boost-preprocessor/src/TEMP/preprocessor-boost-1.72.0/
total 34
-rw-r--r-- 1 adingank 1049089 1439 Nov 12 12:01 appveyor.yml
-rw-r--r-- 1 adingank 1049089  421 Nov 12 12:01 CMakeLists.txt
drwxr-xr-x 1 adingank 1049089    0 Nov 12 12:01 doc/
drwxr-xr-x 1 adingank 1049089    0 Nov 12 12:01 include/
-rw-r--r-- 1 adingank 1049089  415 Nov 12 12:01 index.html
drwxr-xr-x 1 adingank 1049089    0 Nov 12 12:01 meta/
drwxr-xr-x 1 adingank 1049089    0 Nov 12 12:01 test/

adingank@adingank-MOBL1 MINGW64 ~/git/vcpkg (master)
$ ls -al buildtrees/boost-preprocessor/src/
total 4
drwxr-xr-x 1 adingank 1049089 0 Mar 19 13:03 ./
drwxr-xr-x 1 adingank 1049089 0 Mar 19 13:03 ../
drwxr-xr-x 1 adingank 1049089 0 Mar 19 13:03 TEMP/
```

**Comment by JackBoosY** [comment]
@dan-shaw Could you please have a look?

We cannot roll back the cmake version because we need some new cmake functionality (a Robert's PR). And I can occasionally reproduce this issue on a Windows machine.

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/8199
