### ISSUE TITLE
How do I apply 'vcpkg integrate' to e.g. v140 toolchain with v142 installed?

### ISSUE THREAD

**Issue by ocornut** [microsoft/vcpkg#10212]
Hello,

I have installed VS 2019 (v142) along with the 2015 and 2017 toolchains (v140 and v141) which are available in the VS 2019 installer.
(The reason is I am developing a free software which aims for high compatibility with many toolchains, I am testing dozen of compilers down to VS 2010 etc., so even though I am using the VS 2019 IDE I need to use older compilers on an daily basis.)

When I use `vcpkg integrate install` the include/lib integrate works if my project toolchain is set to v142 but not when set to v140, although supposedly vcpkg supports VS 2015 v140 toolchain.
How I can setup VS integration to work with the v140 toolchain? All the FAQ/documents I've checked were surprisingly evasive on how vcpkg support multiple toolchains installed on the computer.

Without support for v140 I need to always retarget my projects to v142. Dealing with many repo and many branches this is becoming very inconvenient.
Note: I do NOT have the full VS 2015 installed, only the VS 2015 toolchain available as part of VS 2019. Perhaps installing the full VS 2015 would work better?

Thank you!

**EDIT** may be similar to #707

**Comment by timautry** [comment]
@ocornut  
 - ".\vcpkg.exe integrate install" is system wide and user wide for the PC/Laptop
 - ".\vcpkg.exe integrate project" is the route I took, having a vcpkg instance setup for each version of visual studio and forcing each version to use the native toolset, compiler, link, etc for that version.
 - The initial setup required much thought, attention to detail, to make it versatile yet easy to work with.
 - The end result has a series of scripts with shortcut setting various environment variables for both Visual Studio and vcpkg in each instance. 

It would be a nice enhancement if there was a way to integrate vcpkg into each version of VS separately targeting the toolset of your choice.

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Please open a new issue if this is still a problem for you.

**Comment by ocornut** [comment]
Hello @LilyWangL,

I don't understand why the issue was closed. @timautry answer is pretty much not answering the issue, albeit ignoring it. `integrate install` is NOT system wide as it does NOT work with alternate toolsets available in the installer, unless the toolset gets the IDE installed., I don't understand why it couldn't be fixed at it is clearly an assymetry.

**e.g. Scenario 1**
VS 2019 IDE w/ Toolchain 2019 installed
VS 2017 IDE w/ Toolchain 2017 installed

`integrate install` works for both toolchains.

**e.g. Scenario 2**
VS 2019 IDE w/ Toolchain 2019 + Toolchain 2017 installed

`integrate install` only works for toolchain 2019.

**Comment by timautry** [comment]
See this documentation - it may help to create an overlay custom triplet file to do what is needed:
https://github.com/microsoft/vcpkg/blob/master/docs/users/triplets.md

In depth details:
https://vcpkg.readthedocs.io/en/latest/
