### ISSUE TITLE
vcpkg install boost-compute doesnt work on linux

### ISSUE THREAD

**Issue by eix128** [microsoft/vcpkg#10229]
Hi , i have tried to used boost-compute on linux.
cmake cant find the library even i install on linux with command : 

vcpkg install boost-compute 

but same library works on windows nice.
There is some configuration problem on linux i think.

I had to manually install boost-compute with github to solve the issue on linux.

**Comment by PhoebeHui** [comment]
@eix128, I checked that boost-compute only extract the source and install the headers to share folder in vcpkg, so there is no library on windows and Linux.

**Comment by eix128** [comment]
so how to use it on linux ? 
it works fine on windows

**Comment by PhoebeHui** [comment]
@eix128, would you like to give an example that how you used on windows, since there is only headers for this librariy, I'm curious about that. I think you might manually install boost-compute with github to solve this issue temporarily.

**Comment by PhoebeHui** [comment]
@eix128, please provide us above information if it still be a problem for you.
