### ISSUE TITLE
zlib build failure

### ISSUE THREAD

**Issue by FullyArticulate** [microsoft/vcpkg#10220]
**Host Environment**
- OS: Windows 10.0.18363
- Compiler: VS Community 2017 15.9.20

**To Reproduce**
.\vcpkg.exe install zlib

**Failure logs** 
`PS C:\dev\vcpkg> .\vcpkg.exe install zlib
Computing installation plan...
The following packages will be built and installed:
    zlib[core]:x86-windows
Starting package 1/1: zlib:x86-windows
Building package zlib[core]:x86-windows...
-- Using cached C:/dev/vcpkg/downloads/zlib1211.tar.gz
-- Using source at C:/dev/vcpkg/buildtrees/zlib/src/1.2.11-deec42f53b
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: ninja -v
    Working Directory: C:/dev/vcpkg/buildtrees/zlib/x86-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\dev\vcpkg\buildtrees\zlib\config-x86-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:295 (vcpkg_execute_required_process)
  ports/zlib/portfile.cmake:22 (vcpkg_configure_cmake)
  scripts/ports.cmake:90 (include)

Error: Building package zlib:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zlib:x86-windows
  Vcpkg version: 2020.02.04-nohash`

**The config-x86-windows-out.log:**

[1/2] cmd /c "cd .. && "C:/dev/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe" "C:/dev/
vcpkg/buildtrees/zlib/src/1.2.11-deec42f53b" "-DSKIP_INSTALL_FILES=ON" "-DSKIP_BUILD_EXAMPLES=ON" "-DCMAKE_MAKE_PROGRAM=
C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.e
xe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/dev/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_T
ARGET_TRIPLET=x86-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v141" "-DCMAKE_EXPORT_NO_PACKAGE_REGI
STRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INS
TALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:
/dev/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-D
VCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBU
G=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_TARGET_ARCHITECTURE=x86" "-DCMAKE_INSTALL_LIBDIR:STRI
NG=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=C:/dev/vcp
kg/packages/zlib_x86-windows""
FAILED: ../CMakeCache.txt
cmd /c "cd .. && "C:/dev/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe" "C:/dev/vcpkg/
buildtrees/zlib/src/1.2.11-deec42f53b" "-DSKIP_INSTALL_FILES=ON" "-DSKIP_BUILD_EXAMPLES=ON" "-DCMAKE_MAKE_PROGRAM=C:/Pro
gram Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" "-
DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/dev/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_
TRIPLET=x86-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v141" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=O
N" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_S
YSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/dev/v
cpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_
CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-
DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_TARGET_ARCHITECTURE=x86" "-DCMAKE_INSTALL_LIBDIR:STRING=lib
" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=C:/dev/vcpkg/pac
kages/zlib_x86-windows""
-- The C compiler identification is unknown
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023
/bin/Hostx64/x86/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023
/bin/Hostx64/x86/cl.exe -- broken
CMake Error at C:/dev/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/share/cmake-3.14/Modules/CMakeTe
stCCompiler.cmake:60 (message):
  The C compiler

    "C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x86/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/dev/vcpkg/buildtrees/zlib/x86-windows-rel/CMakeFiles/CMakeTmp

    Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Micr
osoft/CMake/Ninja/ninja.exe cmTC_8bb7a
    [1/2] Building C object CMakeFiles\cmTC_8bb7a.dir\testCCompiler.c.obj
    FAILED: CMakeFiles/cmTC_8bb7a.dir/testCCompiler.c.obj
    C:\PROGRA~2\MICROS~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x86\cl.exe   /DWIN32 /D_WINDOWS /W3 /utf-8 /
MP -o CMakeFiles\cmTC_8bb7a.dir\testCCompiler.c.obj   -c testCCompiler.c
    Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27035 for x86
    Copyright (C) Microsoft Corporation.  All rights reserved.

    cl : Command line warning D9035 : option 'o' has been deprecated and will be removed in a future release
    testCCompiler.c
    c1: fatal error C1083: Cannot open source file: 'testCCompiler.c': No such file or directory
    ninja: build stopped: subcommand failed.

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:4 (project)

-- Configuring incomplete, errors occurred!

**Other info from other reported issues with zlib:**
The Desktop Development with C++ workload is installed
The English Language pack is installed
Windows 10 SDK 10.0.17134.0 is installed
Building zlib:x64-windows has the same issues

**Comment by NancyLi1013** [comment]
Hi @FullyArticulate 

Thanks for posting this issue.
I cannot reproduce this issue on my local.
The problem maybe here.

` The C compiler identification is unknown`
Could you please try to run cmake as Admin and then try to build it again?

**Comment by FullyArticulate** [comment]
I tried it as root with the same results.

I had a co-installed older version of cmake which I removed, then re-cloned vcpkg and built. vcpkg installed a portable cmake, and I got the same result. 

I then installed the latest cmake (3.17), re-cloned vcpkg and built. No more portable cmake installed, but the same result.

I did notice a warning towards the top of the config-x64-windows-out.log:

cmd /c "cd .. && "C:/Program Files/CMake/bin/cmake.exe" "C:/dev/vcpkg/buildtrees/zlib/src/1.2.11-deec42f53b" "-DSKIP_INSTALL_FILES=ON" "-DSKIP_BUILD_EXAMPLES=ON" "-DCMAKE_MAKE_PROGRAM=C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/dev/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v141" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_TARGET_ARCHITECTURE=x64" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=C:/dev/vcpkg/packages/zlib_x64-windows""
CMake Warning at C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:126 (message):
  **There are no libraries installed for the Vcpkg triplet x64-windows.**
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.17/Modules/CMakeDetermineSystem.cmake:93 (include)
  CMakeLists.txt:4 (project)


-- The C compiler identification is unknown
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe - broken
CMake Error at C:/Program Files/CMake/share/cmake-3.17/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe"

  is not able to compile a simple test program.

I'm not sure what would cause the C compile identification unknown issue. The compiler is completely up to date (as of yesterday), the cmake is completely up to date (as of today).

**Comment by timautry** [comment]
@FullyArticulate 
I was researching this issue on the internet by searching google for the phrase **cl.exe is not able to compile a simple test program** using Visual Studio and CLion.

I found several, but one that could be the issue "https://intellij-support.jetbrains.com/hc/en-us/community/posts/360006862480-Error-The-C-compiler-is-not-able-to-compile-a-simple-test-program" asking the developer if "rc.exe" was in there path.
- rc.exe is part of the Windows SDK
- Do you know if you have the Windows SDK installed with Visual Studio?
- To find out open the cmd or powershell prompt you use with vcpkg
   - at the command line enter **vcpkg env**
   - when the command prompt returns enter **where rc.exe**
   - It should tell you it exists in the following locations:
     - C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64\rc.exe
     - C:\Program Files (x86)\Windows Kits\10\bin\x64\rc.exe
   - If you get the message "INFO: Could not find the files for the given pattern(s) then:
     - The Windows SDK is not installed, use the Visual Studio Installer to install it _**or**_
     - The Windows SDK is corrupt, go to control panel and repair it:
        - open an administrator command prompt
        - **set windowssdkversion** and note the version number
        - enter **control**
        - select **Programs and Features**
        - **find the windows sdk version** noted from above
        - **right click on the version** and select **change**
        - select the **Repair** radio button and click **next** button
        - when it is complete close all windows, and command prompts (I would also reboot).
        - Try repeating the above steps to ensure rc.exe can be found from the **where rc.exe** at the cmd or powershell prompt you use with vcpkg.

**Comment by FullyArticulate** [comment]
Windows 10 SD is installed, v10.1.17763.132, installed 2/25/20.

I ran the test you suggested, and then repaired the SDK, and ran it again. Both before and after:

`C:\dev\vcpkg>.\vcpkg.exe env
Microsoft Windows [Version 10.0.18363.657]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\dev\vcpkg>where rc.exe
C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x64\rc.exe

C:\dev\vcpkg>where cl
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x86\cl.exe
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64\cl.exe
`
vcpkg install zlib:x64-windows reports the same error after repair.

**Comment by FullyArticulate** [comment]
I uninstalled Visual Studio Community 2017, and installed VSC 2019. Now it works just fine. I'm not sure if it was a unique-to-me, or specific to VSC2017 issue, but VSC 2019 fixed it.

**Comment by FullyArticulate** [comment]
I've reopened this because I want to make sure it's seen by vcpkg maintainers--it's possibly a root cause for many "it doesn't work at all" issues under Windows.

The issue was *NOT* VSC 2017 vs 2019. It was in fact a case sensitive filesystem on Windows.

I had used WSL to create my base development directory long ago. By default, WSL turns on case sensitivity for any directories it creates. When I checked out vcpkg in DOS with git, it automatically inherited the case sensitivity of the development directory. 

You can check the status under DOS of a directory by:

`fsutil file queryCaseSensitiveInfo C:\directory\name`

If it's enabled (which is *NOT* the default for Windows, but only for directories created by WSL, you'll have to disable each directory individually with:

`fsutil file setCaseSensitiveInfo C:\directory\name disable`

Note, *MANY* packages would not compile under Windows because of this issue. For example, OpenSSL would not find NASM, even though it downloaded and put it in the path, because it was searching for NASM not nasm.

**Comment by PhoebeHui** [comment]
@FullyArticulate, for the issue that you encountered before, it's not specific to VSC2017 issue, it should be relate to VS setting up. 

For the case sensitivity issue, thanks for bring up this! 
Do you share the folder that created by WSL? if so, this might be expected for me, since the folder should be controlled by WSL, you might need to clone vcpkg by windows. I don't have rich experience of using WSL. I have WSL installed on my machine, it works, and I clone another vcpkg instance by windows, it also works.

**Comment by FullyArticulate** [comment]
Hi Phoebe,

You can reproduce it be creating a directory within WSL in the DOS filesystem. For example, in WSL: "mkdir /mnt/c/test" will create C:\test.

At that point, whether you git clone in windows or WSL doesn't matter--that C:\test directory is now marked as case sensitive, and all of its children will inherit that setting.

I was explicitly cloning vcpkg, bootstrapping, and installing all with DOS, but because the parent directory had case sensitivity set, I had many unexpected problems.

**Comment by PhoebeHui** [comment]
Thanks @FullyArticulate for the details!

We recommand to create sperate vcpkg instance for window and linux. The IO operations from WSL in Windows shares is incredibly slow compared to the Linux filesystem. You are looking at much slower builds.
