### ISSUE TITLE
[sqlite , sqlcipher and OpenCL-HPP ] adding to port

### ISSUE THREAD

**Issue by eix128** [microsoft/vcpkg#10228]
it can be good if you can add
OpenCLTM API C++ bindings (cl.hpp and cl2.hpp)
https://github.com/KhronosGroup/OpenCL-CLHPP

sqlcipher 
https://github.com/sqlcipher/sqlcipher

sqlite 
https://github.com/sqlite/sqlite

FOR sqlcipher how to windows:
https://tribal1012.tistory.com/267

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
