### ISSUE TITLE
libcurl build failure

### ISSUE THREAD

**Issue by aronyu79** [microsoft/vcpkg#10225]
**Host Environment**
- OS: Windows 10
- Compiler: MSVC

**To Reproduce**
`./vcpkg install curl:x64-uwp`

**Failure logs** 
Computing installation plan...
Warning: qualifier has changed meaning recently:
   windows
Warning: qualifier has changed meaning recently:
   windows
The following packages will be built and installed:
    curl[core,non-http,ssl,winssl]:x64-uwp
Starting package 1/1: curl:x64-uwp
Building package curl[core,non-http,ssl,winssl]:x64-uwp...
-- Using cached E:/repo/vcpkg/downloads/curl-curl-curl-7_68_0.tar.gz
-- Using source at E:/repo/vcpkg/buildtrees/curl/src/url-7_68_0-14339e1325
CMake Error at ports/curl/portfile.cmake:23 (message):
  winssl,sspi,tool are not supported on non-Windows and uwp platforms
Call Stack (most recent call first):
  scripts/ports.cmake:90 (include)

Error: Building package curl:x64-uwp failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: curl:x64-uwp
  Vcpkg version: 2020.02.04-nohash

Additionally, attach any relevant sections from the log files above.

**Additional context**
So this fails due to the build having a dependency on winssl, but it should be possible to use openssl with cul, which there is an uwp port. If someone could point me to where I could change this I can try it out.

**Comment by aronyu79** [comment]
also tried .\vcpkg install curl[core,openssl]:x64-uwp which builds openssl-windows

**Comment by JackBoosY** [comment]
```
winssl,sspi,tool are not supported on non-Windows and uwp platforms
```

**Comment by JackBoosY** [comment]
Hi @aronyu79, thanks for reporting this issue.
Since curl some features doesn't support uwp, please use command `./vcpkg install curl[core]:x64-uwp` to build curl.

Thanks.

**Comment by aronyu79** [comment]
Hi Jack! Thanks for clarifying. I am not totally sure what I am doing but if I want curl with openssl I did manage to point out the openssl-uwp package in the CONTROL file. This seems to default to the openssl package if I don't change it. Any comments? will core use openssl-uwp?

**Comment by aronyu79** [comment]
We put up a PR here, what do you think?
https://github.com/microsoft/vcpkg/pull/10235

**Comment by JackBoosY** [comment]
Well, I was wrong.

Thanks for that PR.

**Comment by JackBoosY** [comment]
Please keep this issue open before #10235 merged.

**Comment by JackBoosY** [comment]
Hi @aronyu79, this issue has been fixed.
Please update vcpkg and rebuild curl:x64-uwp.

Thanks.
