### ISSUE TITLE
Boost RuntimeLibrary missmatch

### ISSUE THREAD

**Issue by nareshn2003** [microsoft/vcpkg#10221]
Hi

I am trying to build 64bit dll in my project and using boost static lib to my project using CMake , it builds project fine but compilers gives me this error.

1>boost_thread-vc140-mt-gd.lib(tss_pe.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in 1obj
1>boost_thread-vc140-mt-gd.lib(thread.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in 2.obj

My Dll project is created with Runtime Library is Mutli-threaded DLL (/MDd) and using boost static lib.

I had install vcpkg using this commands
1) vcpkg install boost:x64-windows-static
2) CMake -G "Visual Studio 14 2015 Win64" -H./Software/ -B./Software/Build64 -DVCPKG_TARGET_TRIPLET=x64-windows-static -DCMAKE_TOOLCHAIN_FILE=D:/Work/vcpkg/scripts/buildsystems/vcpkg.cmake

**Environment**
- OS: Windows 10 64bit
- Compiler: Visual Studio 2015 Update 3

Is this bug or am i doing anything wrong ? vcpkg generate using wrong type of Runtime library ?
If i link the pre-compiled boost library with static version it works fine. 

Naresh

**Comment by jbar98** [comment]
Try the x64-windows-static-md triplet when installing the boost libs

**Comment by nareshn2003** [comment]
> Try the x64-windows-static-md triplet when installing the boost libs

Thanks .,. it working now.

**Comment by qqblack** [comment]
But when I use `vcpkg install boost:x64-windows-static-md` (or `vcpkg install boost  --triplet=x64-windows-static-md`), it only changes the output directory. The `.lib` file still is `*-mt.lib`

<img width="561" alt="question1" src="https://user-images.githubusercontent.com/25791058/120581437-662a8f80-c45d-11eb-8d10-dabfaf9ce8ea.png">
