### ISSUE TITLE
[New Port Request] PythonQt

### ISSUE THREAD

**Issue by EvgenyVRN** [microsoft/vcpkg#10237]
Library name: PythonQt

Library description: PythonQt is a dynamic Python binding for the Qt framework. It offers an easy way to embed the Python scripting language into your C++ Qt applications.
The focus of PythonQt is on embedding Python into an existing C++ application, not on writing the whole application completely in Python.
If you are looking for a simple way to embed Python objects into your C++/Qt Application and to script parts of your application via Python, PythonQt is the way to go!
PythonQt is a stable library that was developed to make the Image Processing and Visualization platform MeVisLab scriptable from Python.

Source repository URL: https://github.com/MeVisLab/pythonqt

Project homepage (if different from the source repository): https://mevislab.github.io/pythonqt/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by Voskrese** [comment]
CMake-ified version of PythonQt
https://github.com/commontk/PythonQt/tree/patched-10

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
