### ISSUE TITLE
How do I import PhysX into a cmake project?

### ISSUE THREAD

**Issue by Mikea15** [microsoft/vcpkg#10233]
I'm trying to find out what is missing from the config files, but I can't seem to build successfully with PhysX, with a cmake project.

Using a VS Solution works fine tho.

Anyone managed to include/use find_package and link_targets?

Cheers.

**Comment by JackBoosY** [comment]
PhysX does not support exporting cmake files.
Therefore, you need to use `find_path` and` find_library` to use this port.

**Comment by galvesribeiro** [comment]
@Mikea15 were you able to make it work with the find_path? Tried to make it work here but VSCode is all about a red sea with errors everywhere… Can you update the issue with your findings please? Thanks!

**Comment by JackBoosY** [comment]
@galvesribeiro Here is a template:
```cmake
include(FindPackageHandleStandardArgs)
include(SelectLibraryConfigurations)
find_path(CPPKAFKA_INCLUDES NAMES cppkafka.h HINTS ${CURRENT_INSTALLED_DIR} PATH_SUFFIXES cppkafka)
find_library(CPPKAFKA_LIBRARY_RELEASE NAMES cppkafka PATH_SUFFIXES lib PATHS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}" NO_DEFAULT_PATH REQUIRED)
find_library(CPPKAFKA_LIBRARY_DEBUG NAMES cppkafka PATH_SUFFIXES lib PATHS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/debug" NO_DEFAULT_PATH REQUIRED)
select_library_configurations(CPPKAFKA)
```
