### ISSUE TITLE
[New Port Request] whereami

### ISSUE THREAD

**Issue by eix128** [microsoft/vcpkg#10239]
Library name:

Library description: Getting binary or exe's path that works on many platforms

Windows
Linux
Mac
iOS
Android
QNX Neutrino
FreeBSD
NetBSD
DragonFly BSD
SunOS

Source repository URL:

https://github.com/gpakosz/whereami

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
