### ISSUE TITLE
[portaudio] build failure

### ISSUE THREAD

**Issue by eix128** [microsoft/vcpkg#10231]
**Host Environment**
- OS: Windows 10 x64
- Compiler: MSVC

**To Reproduce**
vcpkg install portaudio:x64-windows-static
vcpkg install portaudio:x64-windows
vcpkg install portaudio:x86-windows
tried with cmake params:
-DCMAKE_TOOLCHAIN_FILE="D:/repo/vcpkg/scripts/buildsystems/vcpkg.cmake" -DCMAKE_BUILD_TYPE=Release -DCMAKE_CL_64=1 -DVCPKG_TARGET_TRIPLET=x64-windows-static  -DOPENSSL_USE_STATIC_LIBS=TRUE

I have added the project
    find_package(portaudio CONFIG REQUIRED)
    target_link_libraries(main PRIVATE portaudio portaudio_static)

**Failure logs** 
CMake Error at D:/repo/vcpkg/installed/x64-windows-static/share/portaudio/portaudioTargets.cmake:80 (message):
  The imported target "portaudio" references the file

     "D:/repo/vcpkg/installed/x64-windows-static/debug/bin/portaudio.dll"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "D:/repo/vcpkg/installed/x64-windows-static/share/portaudio/portaudioTargets.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  D:/repo/vcpkg/installed/x64-windows-static/share/portaudio/portaudioConfig.cmake:1 (include)
  D:/repo/vcpkg/scripts/buildsystems/vcpkg.cmake:285 (_find_package)
  CMakeLists.txt:68 (find_package)

-- Configuring incomplete, errors occurred!
See also "D:/CLionProjects/SQLCipherParallelGPUAttack/cmake-build-release-visual-studio/CMakeFiles/CMakeOutput.log".
See also "D:/CLionProjects/SQLCipherParallelGPUAttack/cmake-build-release-visual-studio/CMakeFiles/CMakeError.log".

Seems like
portaudio.dll is missing by default...
Need to add it

I have fixed the problem by
downloading binary
https://github.com/spatialaudio/portaudio-binaries
renamed libportaudio64bit.dll to portaudio.dll
then copied it to locations:
D:\repo\vcpkg\installed\x64-windows-static\debug\bin
D:\repo\vcpkg\installed\x64-windows-static\bin

But it only works on x64.
For x86 i need to do same delete old dll replace

**Comment by timautry** [comment]
@eix128 

Several ways to go here,

1. There should be a copy of the files created in the _vcpkg-root_/packages directory/folder as follows:
- D:\repo\vcpkg\packages\portaudio_x64-windows
- D:\repo\vcpkg\packages\portaudio_x64-windows-static
- D:\repo\vcpkg\packages\portaudio_x86-windows

You can copy them back to their original locations based on the hierarchy found within each package directory/folder.
Example:
- D:\repo\vcpkg\packages\portaudio_x64-windows\bin\*.* would be copied to D:\repo\vcpkg\installed\x64-windows\bin
- D:\repo\vcpkg\packages\portaudio_x64-windows\debug\bin\*.* would be copied to D:\repo\vcpkg\installed\x64-windows\debug\bin
- repeat for each folder/directory and triplet 
- x64-windows-static, x86-windows, etc, etc, etc as needed

2. Try removing the port and then try to reinstall the port:
 - cd to the _vcpkg-root_ folder
 - .\vcpkg remove portaudio:x64-windows
 - .\vcpkg install portaudio:x64-windows
 - repeat for each triplet as needed, x64-windows-static, x86-windows, etc, etc

3. If all else fails you can always delete the current vcpkg instance and create it anew or create a total new vcpkg instance.

**Comment by LilyWangL** [comment]
Ping @eix128

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Please reopen this issue if it still be a problem for you.

**Comment by TyrasNistru** [comment]
Still can't build the x64-windows-static triplet.
```
Computing installation plan...
The following packages will be built and installed:
    portaudio[core]:x64-windows-static
A suitable version of powershell-core was not found (required v6.2.1). Downloading portable powershell-core v6.2.1...
Downloading powershell-core...
  https://github.com/PowerShell/PowerShell/releases/download/v6.2.1/PowerShell-6.2.1-win-x86.zip -> C:\vcpkg\downloads\PowerShell-6.2.1-win-x86.zip
Extracting powershell-core...
A suitable version of 7zip was not found (required v18.1.0). Downloading portable 7zip v18.1.0...
Downloading 7zip...
  https://www.nuget.org/api/v2/package/7-Zip.CommandLine/18.1.0 -> C:\vcpkg\downloads\7-zip.commandline.18.1.0.nupkg
Extracting 7zip...
A suitable version of nuget was not found (required v4.8.1). Downloading portable nuget v4.8.1...
Downloading nuget...
  https://dist.nuget.org/win-x86-commandline/v4.8.1/nuget.exe -> C:\vcpkg\downloads\nuget.exe
Starting package 1/1: portaudio:x64-windows-static
Building package portaudio[core]:x64-windows-static...
-- Fetching https://git.assembla.com/portaudio.git...
-- Extracting source C:/vcpkg/downloads/portaudio-c5d2c51bd6fe354d0ee1119ba932bfebd3ebfacc.tar.gz
-- Applying patch fix-library-can-not-be-found.patch
-- Applying patch fix-include.patch
-- Using source at C:/vcpkg/buildtrees/portaudio/src/ebd3ebfacc-5ed52dac86
-- Configuring x64-windows-static
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: ninja -v
    Working Directory: C:/vcpkg/buildtrees/portaudio/x64-windows-static-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\vcpkg\buildtrees\portaudio\config-x64-windows-static-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:295 (vcpkg_execute_required_process)
  ports/portaudio/portfile.cmake:12 (vcpkg_configure_cmake)
  scripts/ports.cmake:90 (include)


Error: Building package portaudio:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: portaudio:x64-windows-static
  Vcpkg version: 2020.02.04-nohash
```

**Comment by penumbra23** [comment]
Any progress on this? I'm getting the following error:

```
Starting package 16/3: portaudio:x64-windows
Building package portaudio[core]:x64-windows...
Could not locate cached archive: C:\Users\vcpkg\AppData\Local\vcpkg/archives\06\0646dc06cff9bf4492c5289f96ba7f6568ec22d4.zip
-- Fetching https://git.assembla.com/portaudio.git...
-- Extracting source C:/Users/vcpkg/src/vcpkg/downloads/portaudio-c5d2c51bd6fe354d0ee1119ba932bfebd3ebfacc.tar.gz
-- Applying patch fix-library-can-not-be-found.patch
-- Applying patch fix-include.patch
-- Using source at C:/Users/vcpkg/src/vcpkg/buildtrees/portaudio/src/ebd3ebfacc-5ed52dac86.clean
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:83 (message):
    Command failed: ninja -v
    Working Directory: C:/Users/vcpkg/src/vcpkg/buildtrees/portaudio/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:/Users/vcpkg/src/vcpkg/buildtrees\portaudio\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:300 (vcpkg_execute_required_process)
  ports/portaudio/portfile.cmake:12 (vcpkg_configure_cmake)
  scripts/ports.cmake:79 (include)


Error: Building package portaudio:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: portaudio:x64-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.
```

After inspecting the logs:
```
CMake Error:
  Running

   'C:/Users/vcpkg/src/vcpkg/downloads/tools/ninja/1.10.0-windows/ninja.exe' '-C' 'C:/Users/vcpkg/src/vcpkg/buildtrees/portaudio/x64-windows-rel' '-t' 'cleandead'

  failed with:

   ninja: error: build.ninja:525: multiple rules generate portaudio.lib [-w dupbuild=err]
```

**Comment by sfhacker** [comment]
Any updates on this long standing issue?

![image](https://user-images.githubusercontent.com/25817529/93027359-8e642b00-f64f-11ea-9cc5-1ba079d13a51.png)
