### ISSUE TITLE
[osg] windows-static builds of dependent ports fail (e.g. osg-qt)

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#10249]
Reason: CMake dependent ports will always assume shared build on windows.
From `include/osg/Export`
```
#if defined(_MSC_VER) || defined(__CYGWIN__) || defined(__MINGW32__) || defined( __BCPLUSPLUS__)  || defined( __MWERKS__)
    #  if defined( OSG_LIBRARY_STATIC )
    #    define OSG_EXPORT
    #  elif defined( OSG_LIBRARY )
    #    define OSG_EXPORT   __declspec(dllexport)
    #  else
    #    define OSG_EXPORT   __declspec(dllimport)
    #  endif
#else
    #  define OSG_EXPORT
#endif
```

Since CMake findModule for OSG will not automatically pass `OSG_LIBRARY_STATIC` linkage against OSG will fail in static builds on windows. As such `if defined( OSG_LIBRARY_STATIC )` should be changed to `if TRUE` for static windows builds

**Comment by JackBoosY** [comment]
I will fix them after #10082 merged.

**Comment by JackBoosY** [comment]
@Neumann-A I see that many header files contain similar content. Should we define `OSG_LIBRARY_STATIC` in one file to solve this issue? And which header file do we usually include osg first?

**Comment by LilyWangLL** [comment]
Ping @Neumann-A for response.

**Comment by LilyWangLL** [comment]
> @Neumann-A I see that many header files contain similar content. Should we define `OSG_LIBRARY_STATIC` in one file to solve this issue? And which header file do we usually include osg first?

Ping @Neumann-A for response.
