### ISSUE TITLE
qt 5.8 build failed

### ISSUE THREAD

**Issue by cxq2003** [Microsoft/vcpkg#1024]
I built qt 5.8 failed as follows under windows 7 sp1 64 chinese edition with cmake 3.8.0 and visual studio 2017. The vcpkg version is 0.0.81-e6a47f5c6a2f6efef3d10fd1e2cbb9e123d5dbe7.

jom 1.1.2 - empower your cores

C:\vcpkg\buildtrees\qt5\src\qt-5.8.0\qtbase\src\corelib\kernel\qobjectdefs.h(0): Note: No relevant classes found. No output generated.
C:\vcpkg\buildtrees\qt5\src\qt-5.8.0\qtbase\src\network\access\qnetworkaccessdebugpipebackend_p.h(0): Note: No relevant classes found. No output generated.
jom: C:\vcpkg\buildtrees\qt5\x86-windows-rel\qtbase\src\plugins\generic\tuiotouch\Makefile.Release [.obj\release\qtuiohandler.obj] Error 2
jom: C:\vcpkg\buildtrees\qt5\x86-windows-rel\qtbase\src\plugins\generic\tuiotouch\Makefile [release] Error 2
jom: C:\vcpkg\buildtrees\qt5\x86-windows-rel\qtbase\src\plugins\generic\Makefile [sub-tuiotouch-make_first] Error 2
jom: C:\vcpkg\buildtrees\qt5\x86-windows-rel\qtbase\src\plugins\Makefile [sub-generic-make_first] Error 2
jom: C:\vcpkg\buildtrees\qt5\x86-windows-rel\qtbase\src\Makefile [sub-plugins-make_first] Error 2
jom: C:\vcpkg\buildtrees\qt5\x86-windows-rel\qtbase\Makefile [sub-src-make_first] Error 2
jom: C:\vcpkg\buildtrees\qt5\x86-windows-rel\Makefile [module-qtbase-make_first] Error 2

**Comment by tobiaskohlbau** [comment]
Have you tried invoking the installation again? Sometimes it fails and I'm still not confident what's causing this issue. Would be glad if you could add the other generated log files maybe they show more information.

**Comment by cxq2003** [comment]
C:\vcpkg>vcpkg install qt5
The following packages will be built and installed:
    qt5:x86-windows
Building package qt5:x86-windows...
-- CURRENT_INSTALLED_DIR=C:/vcpkg/installed/x86-windows
-- DOWNLOADS=C:/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/vcpkg/packages/qt5_x86-windows
-- CURRENT_BUILDTREES_DIR=C:/vcpkg/buildtrees/qt5
-- CURRENT_PORT_DIR=C:/vcpkg/ports/qt5/.
-- Using cached C:/vcpkg/downloads/qt-5.8.0.7z
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Applying patch C:/vcpkg/ports/qt5/fix-qalgorithms-vs2017.patch
-- Applying patch failed. This is expected if this patch was previously applied.

-- Applying patch C:/vcpkg/ports/qt5/fix-qalgorithms-vs2017.patch done
-- Applying patch C:/vcpkg/ports/qt5/fix-commandline-overrides.patch
-- Applying patch failed. This is expected if this patch was previously applied.

-- Applying patch C:/vcpkg/ports/qt5/fix-commandline-overrides.patch done
-- Configuring x86-windows-rel
-- Configuring x86-windows-rel done
-- Configuring x86-windows-dbg
-- Configuring x86-windows-dbg done
-- Package x86-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:14 (message):
    Command failed: C:/vcpkg/downloads/tools/jom/jom-1.1.2/jom.exe;/J;8
    Working Directory: C:/vcpkg/buildtrees/qt5/x86-windows-rel
    See logs for more information:
      C:\vcpkg\buildtrees\qt5\build-x86-windows-rel-out.log
      C:\vcpkg\buildtrees\qt5\build-x86-windows-rel-err.log

Call Stack (most recent call first):
  ports/qt5/install_qt.cmake:19 (vcpkg_execute_required_process)
  ports/qt5/portfile.cmake:54 (install_qt)
  scripts/ports.cmake:73 (include)


Error: Building package qt5:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: qt5:x86-windows
  Vcpkg version: 0.0.81-ef149c7c4b8852916cf863598ce17ead9602641b

Additionally, attach any relevant sections from the log files above.

C:\vcpkg>vcpkg install qt5
The following packages will be built and installed:
    qt5:x86-windows
Building package qt5:x86-windows...
-- CURRENT_INSTALLED_DIR=C:/vcpkg/installed/x86-windows
-- DOWNLOADS=C:/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/vcpkg/packages/qt5_x86-windows
-- CURRENT_BUILDTREES_DIR=C:/vcpkg/buildtrees/qt5
-- CURRENT_PORT_DIR=C:/vcpkg/ports/qt5/.
-- Using cached C:/vcpkg/downloads/qt-5.8.0.7z
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting source C:/vcpkg/downloads/qt-5.8.0.7z
-- Extracting done
-- Applying patch C:/vcpkg/ports/qt5/fix-qalgorithms-vs2017.patch
-- Applying patch C:/vcpkg/ports/qt5/fix-qalgorithms-vs2017.patch done
-- Applying patch C:/vcpkg/ports/qt5/fix-commandline-overrides.patch
-- Applying patch C:/vcpkg/ports/qt5/fix-commandline-overrides.patch done
-- Configuring x86-windows-rel
-- Configuring x86-windows-rel done
-- Configuring x86-windows-dbg
-- Configuring x86-windows-dbg done
-- Package x86-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:14 (message):
    Command failed: C:/vcpkg/downloads/tools/jom/jom-1.1.2/jom.exe;/J;8
    Working Directory: C:/vcpkg/buildtrees/qt5/x86-windows-rel
    See logs for more information:
      C:\vcpkg\buildtrees\qt5\build-x86-windows-rel-out.log
      C:\vcpkg\buildtrees\qt5\build-x86-windows-rel-err.log

Call Stack (most recent call first):
  ports/qt5/install_qt.cmake:19 (vcpkg_execute_required_process)
  ports/qt5/portfile.cmake:54 (install_qt)
  scripts/ports.cmake:73 (include)


Error: Building package qt5:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: qt5:x86-windows
  Vcpkg version: 0.0.81-ef149c7c4b8852916cf863598ce17ead9602641b

**Comment by tobiaskohlbau** [comment]
Could you try adding ```DISABLE_PARALLEL``` after this line https://github.com/Microsoft/vcpkg/blob/master/ports/qt5/portfile.cmake#L43 ?

After this change run ```vcpkg install qt``` again jom should be run with /J;1 so one process only maybe this brings some trouble. (Note that this could result in very long compilation time.)

**Comment by ZeppLu** [comment]
I suggest you check `C:\vcpkg\buildtrees\qt5\build-x86-windows-rel-out.log` to see if it contains `error C2001`. If so, you may suffer the same issue as mine (#1092).
