### ISSUE TITLE
How to build .so objects specfically for Linux

### ISSUE THREAD

**Issue by define-private-public** [microsoft/vcpkg#10247]
I made a C#/Nuget project that uses some native C libraries (`libsndfile`, `portaudio`, `libflac`, etc) that are all cross platform.  I want to use vcpkg to possibly make managing these native libraries a little easier.

I tried out vcpkg.  when it installed/build `portaudio`, I was able to find a `.so` object for it, but for `libsndfile`, `libflac`, `libogg`, `libvorbis`, none of their shared objects are found in the project tree; only the static archives.

Is there a way I can force it to always build the shared libraries?

**Comment by linquize** [comment]
See also #10174

**Comment by PhoebeHui** [comment]
@linquize, thanks for your comments!

@define-private-public, have you try the solution that linquize provided? does the issue solved?

**Comment by define-private-public** [comment]
Sorry, been a bit slow with trying that out.  It's on my TODO list.  I'll be sure to report back once I've tried it.

**Comment by define-private-public** [comment]
That seemed to do the trick for me.  Thanks!

Though I would prefer if I could specify something like `--build-dynamic` as an option on the `install` command, or if there was some other environment variable I could set.

**Comment by PhoebeHui** [comment]
@define-private-public,  we have a docs about this, you can reference https://github.com/microsoft/vcpkg/blob/4d551ff4b3cea2f387b02ed69486a23b1be2fd73/docs/examples/overlay-triplets-linux-dynamic.md, let me know if you have any questions about this.

**Comment by define-private-public** [comment]
@PhoebeHui thanks!  that works wonders.  I have it now working how I want it for Linux and Windows (I think I can manage OS X myself).  I don't have any more questions on how to use this, so I'll go and close this ticket.

Thanks again!
