### ISSUE TITLE
Split into separate repository for portfiles?

### ISSUE THREAD

**Issue by SeekingMeaning** [microsoft/vcpkg#10248]
## For example, this is how Homebrew does it:

`brew`

`brew install llvm`

`/usr/local/Homebrew`

`/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/llvm.rb`

`/usr/local/Cellar/llvm/9.0.1/bin`

`/usr/local/bin`

- https://github.com/Homebrew/brew
- https://github.com/Homebrew/homebrew-core

## How vcpkg currently works:

`vcpkg`

`vcpkg install llvm`

`VCPKG_ROOT`

`VCPKG_ROOT\ports\llvm\portfile.cmake`

`VCPKG_ROOT\packages\llvm_x64-windows\bin`

`VCPKG_ROOT\installed\x64-windows\bin`

- https://github.com/microsoft/vcpkg

## Possible future alternative for vcpkg:

- https://gitlab.com/SeekingMeaning/vcpkg-no-ports
- https://github.com/microsoft/vcpkg-ports

**Comment by timautry** [comment]
@SeekingMeaning  how does this fork version work?

- Cloned, compiled/linked on Windows 10 x64, VS 2019, the version of vcpkg mentioned from https://github.com/SeekingMeaning/vcpkg-no-ports. 
- There are no instructions other than the original vcpkg instructions in this fork on how one is suppose to use it?

**Comment by SeekingMeaning** [comment]
This is being done in PR https://github.com/microsoft/vcpkg/pull/15474

- https://github.com/microsoft/vcpkg-tool is equivalent to https://github.com/Homebrew/brew
- https://github.com/microsoft/vcpkg is equivalent to https://github.com/Homebrew/homebrew-core
