### ISSUE TITLE
[qt5:MSYS2] build failure

### ISSUE THREAD

**Issue by Frank-Dz** [microsoft/vcpkg#10240]
When I tried to install QT5 via VCPKG. I always met such a problem.

`
-- Using source at C:/local/vcpkg/buildtrees/icu/src/c-65_1-src-702c9cff96
-- Acquiring MSYS2...
-- Using cached C:/local/vcpkg/downloads/msys2-base-x86_64-20181211.tar.xz
gpg: /etc/pacman.d/gnupg/trustdb.gpg: trustdb created
gpg: no ultimately trusted keys found
gpg: starting migration from earlier GnuPG versions
gpg: porting secret keys from '/etc/pacman.d/gnupg/secring.gpg' to gpg-agent
gpg: migration succeeded
gpg: Generating pacman keyring master key...
gpg: key D275FF753336897E marked as ultimately trusted
gpg: directory '/etc/pacman.d/gnupg/openpgp-revocs.d' created
gpg: revocation certificate stored as '/etc/pacman.d/gnupg/openpgp-revocs.d/23B2FA5E0368BDA2AC1B653BD275FF753336897E.rev'
gpg: Done
==> Updating trust database...
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
==> Appending keys from msys2.gpg...
==> Locally signing trusted keys in keyring...
  -> Locally signing key D55E7A6D7CE9BA1587C0ACACF40D263ECA25678A...
  -> Locally signing key 123D4D51A1793859C2BE916BBBE514E53E0D0813...
  -> Locally signing key B91BCF3303284BF90CC043CA9F418C233E652008...
  -> Locally signing key 9DD0D4217D75A33B896159E6DA7EF2ABAEEA755C...
==> Importing owner trust values...
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: inserting ownertrust of 4
==> Updating trust database...
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   4  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: depth: 1  valid:   4  signed:   3  trust: 0-, 0q, 0n, 4m, 0f, 0u
gpg: depth: 2  valid:   3  signed:   0  trust: 3-, 0q, 0n, 0m, 0f, 0u
:: Synchronizing package databases...
downloading mingw32.db...
error: failed retrieving file 'mingw32.db' from repo.msys2.org : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
downloading mingw32.db...
error: failed retrieving file 'mingw32.db' from sourceforge.net : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
downloading mingw32.db...
error: failed retrieving file 'mingw32.db' from www2.futureware.at : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
error: failed retrieving file 'mingw32.db' from mirror.yandex.ru : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
error: failed to update mingw32 (download library error)
downloading mingw64.db...
error: failed retrieving file 'mingw64.db' from repo.msys2.org : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
error: failed retrieving file 'mingw64.db' from sourceforge.net : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
downloading mingw64.db...
error: failed retrieving file 'mingw64.db' from www2.futureware.at : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
error: failed retrieving file 'mingw64.db' from mirror.yandex.ru : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
error: failed to update mingw64 (download library error)
downloading msys.db...
error: failed retrieving file 'msys.db' from repo.msys2.org : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
downloading msys.db...
error: failed retrieving file 'msys.db' from sourceforge.net : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
downloading msys.db...
error: failed retrieving file 'msys.db' from www2.futureware.at : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
error: failed retrieving file 'msys.db' from mirror.yandex.ru : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
error: failed to update msys (download library error)
error: failed to synchronize all databases
`

The cause is that CGAL with QT5 needs **msys2-base-x86_64-20181211.tar.xz**.
But when install this pkg, there is something wrong with the command which has been reported in [here](https://github.com/msys2/MSYS2-packages/issues/1658)
Seems like we need to add some commands to cancel time-out setting.

ENV: windows-64, vs17.

How can we fix such a problem?

Best,
Frank

**Comment by Voskrese** [comment]
as a temporary option. start the terminal
`...\vcpkg\downloads\tools\msys2\msys64\msys2.exe`

enter in the terminal
`pacman -Syyuu --noconfirm --needed --overwrite '*'
`

try again 
`vcpkg install icu:x64-windows
`

**Comment by Frank-Dz** [comment]
> as a temporary option. start the terminal
> `...\vcpkg\downloads\tools\msys2\msys64\msys2.exe`
> 
> enter in the terminal
> `pacman -Syyuu --noconfirm --needed --overwrite '*' `
> 
> > Adding `--disable-download-timeout` appears to work in the meantime, as in `pacman -Syu --disable-download-timeout`
> 
> `pacman -Syyuu --disable-download-timeout --noconfirm --needed --overwrite '*' `
> 
> try again
> `vcpkg install icu:x64-windows `

Thanks! Tried but still have this problem:
`
low. Less than 1 bytes/sec transferred the last 10 seconds
error: failed retrieving file 'mingw32.db' from sourceforge.net : Connection timed out after 10001 milliseconds
error: failed retrieving file 'mingw32.db' from www2.futureware.at : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
error: failed retrieving file 'mingw32.db' from mirror.yandex.ru : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
error: failed to update mingw32 (download library error)
error: failed retrieving file 'mingw64.db' from repo.msys2.org : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
error: failed retrieving file 'mingw64.db' from sourceforge.net : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
 mingw64                    6.7 KiB  3.92K/s 01:54 [---------------------]   1%
`
Seems like it could successfully download some pkgs but not all.

Best,
Frank

**Comment by Frank-Dz** [comment]
`
# pacman -Syyuu --noconfirm --needed --overwrite '*'
`
Full logs: 
`
# pacman -Syyuu --noconfirm --needed --overwrite '*'
:: Synchronizing package databases...
error: failed retrieving file 'mingw32.db' from repo.msys2.org : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
error: failed retrieving file 'mingw32.db' from sourceforge.net : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
error: failed retrieving file 'mingw32.db' from www2.futureware.at : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
error: failed retrieving file 'mingw32.db' from mirror.yandex.ru : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
error: failed to update mingw32 (download library error)
error: failed retrieving file 'mingw64.db' from repo.msys2.org : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
error: failed retrieving file 'mingw64.db' from sourceforge.net : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
error: failed retrieving file 'mingw64.db' from www2.futureware.at : Connection timed out after 10000 milliseconds
error: failed retrieving file 'mingw64.db' from mirror.yandex.ru : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
error: failed to update mingw64 (download library error)
error: failed retrieving file 'msys.db' from repo.msys2.org : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
error: failed retrieving file 'msys.db' from sourceforge.net : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
error: failed retrieving file 'msys.db' from www2.futureware.at : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
error: failed retrieving file 'msys.db' from mirror.yandex.ru : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
error: failed to update msys (download library error)
error: failed to synchronize all databases
`

**Comment by Frank-Dz** [comment]
> as a temporary option. start the terminal
> `...\vcpkg\downloads\tools\msys2\msys64\msys2.exe`
> 
> enter in the terminal
> `pacman -Syyuu --noconfirm --needed --overwrite '*' `
> 
> > Adding `--disable-download-timeout` appears to work in the meantime, as in `pacman -Syu --disable-download-timeout`
> 
> `pacman -Syyuu --disable-download-timeout --noconfirm --needed --overwrite '*' `
> 
> try again
> `vcpkg install icu:x64-windows `

It does solve the problem. Yet, the downloading time is quite slow though I have set up the VPN.
`
# pacman -Syyuu --disable-download-timeout --noconfirm --needed --overwrite '*'
:: Synchronizing package databases...
 mingw32                    0.0   B  0.00B/s 00:00 [---------------------]   0%
`
Is there a solution to this problem? 
Many thanks for you kind help and guidance!

Best,
Frank

**Comment by Frank-Dz** [comment]
Well solved by setting
`
export http_proxy=http://www-myproxy.example.com:8080
export https_proxy=$http_proxy
export ftp_proxy=$http_proxy
`
before the command:

pacman -Syyuu --disable-download-timeout --noconfirm --needed --overwrite '*'

Thanks again for your great work and kind help!

Best,
Frank

**Comment by Frank-Dz** [comment]
> as a temporary option. start the terminal
> `...\vcpkg\downloads\tools\msys2\msys64\msys2.exe`
> 
> enter in the terminal
> `pacman -Syyuu --noconfirm --needed --overwrite '*' `
> 
> > Adding `--disable-download-timeout` appears to work in the meantime, as in `pacman -Syu --disable-download-timeout`
> 
> `pacman -Syyuu --disable-download-timeout --noconfirm --needed --overwrite '*' `
> 
> try again
> `vcpkg install icu:x64-windows `

Sorry. I made a mistake, it did not work:
When I set msys2 up according to your guidance. When I go back to run vcpkg install icu:x64-windows. If always need to reinstall the msys2:


![image](https://user-images.githubusercontent.com/55009565/75522449-fbfa9200-5a44-11ea-9e8e-64e1f4ea2e62.png)


Best,
Frank

**Comment by Frank-Dz** [comment]
Plus, I successfully get key and run the command in msys2.exe as an administrator.




On 02/28/2020 01:39, Voskrese wrote:

as a temporary option. start the terminal
...\vcpkg\downloads\tools\msys2\msys64\msys2.exe

enter in the terminal
pacman -Syyuu --noconfirm --needed --overwrite '*'

try again
vcpkg install icu:x64-windows

**Comment by Frank-Dz** [comment]
> as a temporary option. start the terminal
> `...\vcpkg\downloads\tools\msys2\msys64\msys2.exe`
> 
> enter in the terminal
> `pacman -Syyuu --noconfirm --needed --overwrite '*' `
> 
> > Adding `--disable-download-timeout` appears to work in the meantime, as in `pacman -Syu --disable-download-timeout`
> 
> `pacman -Syyuu --disable-download-timeout --noconfirm --needed --overwrite '*' `
> 
> try again
> `vcpkg install icu:x64-windows `

This is the details:
I wonder why it doesn't directly check the folder downloads\tools but to check the zipped uninstalled pkg first?

![image](https://user-images.githubusercontent.com/55009565/75557431-f324b300-5a7a-11ea-8c7a-6b90bf062c06.png)


Log:
./vcpkg install icu:x64-windows
Computing installation plan...
The following packages will be built and installed:
    icu[core]:x64-windows
Starting package 1/1: icu:x64-windows
Building package icu[core]:x64-windows...
-- Using cached C:/local/vcpkg/downloads/icu4c-65_1-src.tgz
-- Using source at C:/local/vcpkg/buildtrees/icu/src/c-65_1-src-702c9cff96
-- Acquiring MSYS2...
-- Using cached C:/local/vcpkg/downloads/msys2-base-x86_64-20181211.tar.xz
CMake Error: Problem with archive_write_header(): Can't unlink already-existing object
CMake Error: Current file: msys64/usr/bin/dirmngr.exe
CMake Error: Problem extracting tar: C:/local/vcpkg/downloads/msys2-base-x86_64-20181211.tar.xz
gpg: /etc/pacman.d/gnupg/trustdb.gpg: trustdb created
gpg: no ultimately trusted keys found
C:/local/vcpkg/downloads/tools/msys2/msys64/usr/bin/awk.exe: error while loading shared libraries: msys-readline7.dll: cannot open shared object file: No such file or directory
gpg: starting migration from earlier GnuPG versions
gpg: porting secret keys from '/etc/pacman.d/gnupg/secring.gpg' to gpg-agent
gpg: migration succeeded
gpg: Generating pacman keyring master key...
gpg: key 33A44C00167212D5 marked as ultimately trusted
gpg: directory '/etc/pacman.d/gnupg/openpgp-revocs.d' created
gpg: revocation certificate stored as '/etc/pacman.d/gnupg/openpgp-revocs.d/EEFEDB144146E4D28890DBA733A44C00167212D5.rev'
gpg: Done
==> Updating trust database...
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
==> Appending keys from msys2.gpg...
==> Locally signing trusted keys in keyring...
  -> Locally signing key D55E7A6D7CE9BA1587C0ACACF40D263ECA25678A...
  -> Locally signing key 123D4D51A1793859C2BE916BBBE514E53E0D0813...
  -> Locally signing key B91BCF3303284BF90CC043CA9F418C233E652008...
  -> Locally signing key 9DD0D4217D75A33B896159E6DA7EF2ABAEEA755C...
==> Importing owner trust values...
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: inserting ownertrust of 4
==> Updating trust database...
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   4  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: depth: 1  valid:   4  signed:   3  trust: 0-, 0q, 0n, 4m, 0f, 0u
gpg: depth: 2  valid:   3  signed:   0  trust: 3-, 0q, 0n, 0m, 0f, 0u

**Comment by Voskrese** [comment]
you an individual problem, update all the build tools and check your folder permissions

> CMake Error: Problem with archive_write_header(): Can't unlink already-existing object
> CMake Error: Current file: msys64/usr/bin/dirmngr.exe
> CMake Error: Problem extracting tar: C:/local/vcpkg/downloads/msys2-base-x86_64-20181211.tar.xz

CMake Error - Can't unlink already

as an option try

delete folder 
C:/local/vcpkg/buildtrees/**icu**
C:/local/vcpkg/downloads/tools/**msys2**

try again
`vcpkg install icu:x64-windows `

**Comment by Frank-Dz** [comment]
Thanks! I tried but did not make it. Maybe I have something wrong at some steps.
I finally solve the problem by manually set a sha512 following:
[https://github.com/microsoft/vcpkg/issues/10255](https://github.com/microsoft/vcpkg/issues/10255)
Now msys2 successfully works for me.

Thank you again for your kind help and guidance~

Best,
Frank

**Comment by Voskrese** [comment]
that is, you did not download the distribution because of the weak Internet, you decided to change the hash of the file in the settings. and that solved your problem?

hmm... )))

**Comment by Frank-Dz** [comment]
Yep. All pkgs well installed!
And I am using them.




Best,
Frank


On 02/29/2020 15:10, Voskrese wrote:

that is, you did not download the distribution because of the weak Internet, you decided to change the hash of the file in the settings. and that solved your problem?

hmm... )))

**Comment by Frank-Dz** [comment]
I downloaded the .tar.xz file, extract it and set the setting of msys2. And make it as a .tar.xz.
Then we let vcpkg use this modified msys2 pck.


That's it.


On 02/29/2020 15:10, Voskrese wrote:

that is, you did not download the distribution because of the weak Internet, you decided to change the hash of the file in the settings. and that solved your problem?

hmm... )))
