### ISSUE TITLE
Error when trying to install cpprestsdk

### ISSUE THREAD

**Issue by cbomfim** [microsoft/vcpkg#10259]
I'm trying to install cpprestsdk. I follow all steps from https://docs.microsoft.com/en-us/cpp/build/vcpkg?view=vs-2019. When I run "vcpkg install cpprestsdk" got an error as follow:

Error: Building package boost-atomic:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-atomic:x86-windows
  Vcpkg version: 2020.02.04-nohash

Additionally, attach any relevant sections from the log files above.

I performed verification as stated above and got:

vcpkg>.\vcpkg update
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.

Log file shows:

   Criando biblioteca <my vcpkg home dir>\vcpkg\buildtrees\boost-atomic\x86-windows-rel\boost\build\64c60debac8240633333a6301148bbec\boost_atomic-vc140-mt-x32-1_72.lib e objeto <my vcpkg home dir>\vcpkg\buildtrees\boost-atomic\x86-windows-rel\boost\build\64c60debac8240633333a6301148bbec\boost_atomic-vc140-mt-x32-1_72.exp
msvc.manifest.dll <my vcpkg home dir>\vcpkg\buildtrees\boost-atomic\x86-windows-rel\boost\build\64c60debac8240633333a6301148bbec\boost_atomic-vc140-mt-x32-1_72.dll
'mt' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.

        if exist "<my vcpkg home dir>\vcpkg\buildtrees\boost-atomic\x86-windows-rel\boost\build\64c60debac8240633333a6301148bbec\boost_atomic-vc140-mt-x32-1_72.dll.manifest" (
            call "<my vcpkg home dir>\vcpkg\buildtrees\boost-atomic\x86-windows-rel\boost\standalone\msvc\6303f0eb78aa64dc89c3f04044858d46\msvc-setup.bat" x86 >nul
 mt -manifest "<my vcpkg home dir>\vcpkg\buildtrees\boost-atomic\x86-windows-rel\boost\build\64c60debac8240633333a6301148bbec\boost_atomic-vc140-mt-x32-1_72.dll.manifest" "-outputresource:<my vcpkg home dir>\vcpkg\buildtrees\boost-atomic\x86-windows-rel\boost\build\64c60debac8240633333a6301148bbec\boost_atomic-vc140-mt-x32-1_72.dll;2"
        )
    
...failed msvc.manifest.dll <my vcpkg home dir>\vcpkg\buildtrees\boost-atomic\x86-windows-rel\boost\build\64c60debac8240633333a6301148bbec\boost_atomic-vc140-mt-x32-1_72.dll <my vcpkg home dir>\vcpkg\buildtrees\boost-atomic\x86-windows-rel\boost\build\64c60debac8240633333a6301148bbec\boost_atomic-vc140-mt-x32-1_72.lib <my vcpkg home dir>\vcpkg\buildtrees\boost-atomic\x86-windows-rel\boost\build\64c60debac8240633333a6301148bbec\boost_atomic-vc140-mt-x32-1_72.pdb <my vcpkg home dir>\vcpkg\buildtrees\boost-atomic\x86-windows-rel\boost\build\64c60debac8240633333a6301148bbec\boost_atomic-vc140-mt-x32-1_72.pdb...
...removing <my vcpkg home dir>\vcpkg\buildtrees\boost-atomic\x86-windows-rel\boost\build\64c60debac8240633333a6301148bbec\boost_atomic-vc140-mt-x32-1_72.dll
...removing <my vcpkg home dir>\vcpkg\buildtrees\boost-atomic\x86-windows-rel\boost\build\64c60debac8240633333a6301148bbec\boost_atomic-vc140-mt-x32-1_72.lib
...removing <my vcpkg home dir>\vcpkg\buildtrees\boost-atomic\x86-windows-rel\boost\build\64c60debac8240633333a6301148bbec\boost_atomic-vc140-mt-x32-1_72.pdb
...failed updating 1 target...
...updated 11 targets...

I am using Visual Studio Community 2019.  Tried to run using Command window and PowerShell and got same result. 

I am new on this field and don't know how to solve that. Appreciate any help.

Regards,

Carlos Bomfim

PS> sorry my poor english.

**Comment by timautry** [comment]
Hi @cbomfim 

It seems you may not have a Windows SDK installed, at the log is showing vcpkg cannot find "mt.exe", included with the Windows SDK.

vcpkg needs the following installed to work properly on windows:
- Run the Visual Studio Installer:
   - Under the Workloads tab make sure the **"Desktop development with C++"** is checked. 
   - Under Individual Components tab scroll almost to the end and make sure at least **one of the "Windows SDK versions"** are checked (personally I install them all) 
   - Under the Language packs tab make sure **"English"** is checked.
 - If you needed to check either one, two or all three, then click the **Modify button** and wait for the installer to complete.

Try to install the port cpprestsdk again.

**Comment by cbomfim** [comment]
Hi Tim,

thank you for your help. I could pass through the point where I got the error. Not finished yet because some actions are taking too long to finish. Right now I am waiting mora then 2 hours performing "Build x86-windows-rel".

Thanks a lot,

Carlos Bomfim

**Comment by NancyLi1013** [comment]
Hi @cbomfim 
Thanks for posting this issue.
Could you help confirm if this issue still exist on your local now?

@timautry 
Thanks for your help and above info.

**Comment by cbomfim** [comment]
Hi Nancy,

yes, the issue was solved. I got both lib, x86 and x64. Thanks for helping again

Carlos Henrique de Morais Bomfim
