### ISSUE TITLE
building gRPC for UWP, communication problem with the vcpkg team.

### ISSUE THREAD

**Issue by Noemata** [microsoft/vcpkg#10254]
**Describe the bug**
Unable to communicate with the vcpkg team the urgency of getting gRPC build for UWP.

I have had many days of back and forth dialog related to building gRPC for UWP.  I'm noticing that this is getting only cursory attention at this stage.  Not sure why.

In the vcpkg build setup for gRPC there is an exclusion for uwp related to the abseil library.  I had identified that it should be possible to get abseil building for UWP since this is a library consisting mostly of algorithms and not system level code.

I've had to go as far as sorting out the build for this myself shown in the screenshot below:

![image](https://user-images.githubusercontent.com/6632315/75553427-5de7d700-5a06-11ea-8712-5c4d95baf1d4.png)

Could we please get this resolved.  gRPC is an essential library.  gRPC was formerly building using vcpkg with a UWP target.  The latest 1.27.1 release of gRPC needs to be supported by vcpkg with a UWP target.  Please give this some attention.  Spotting the !uwp build exclusion for abseil in the vcpkg build setup is easy and was never the real problem.  Adding this exclusion was a mistake.

**Comment by timautry** [comment]
@Noemata 

- Realize most of the work on vcpkg is/has been done by volunteers who donate their time to this and other projects, not to mention this is in addition to their day-to-day professional occupations.
- By chance one has built a solution to the issue one is experiencing, then may I suggest one make a pull request on the port(s) affected, make the required changes, have it pass current regression testing and merged into the project master.

**Comment by Noemata** [comment]
Noted.  I didn't realize this was a volunteer effort.  I thought Microsoft had some investment in this.  Not sure why Microsoft would be promoting tooling that is susceptible to major regressions?  The lib in question was previously available for UWP using vcpkg.  You can imagine how problematic it is to use tooling that can break unexpectedly while you're progressing a project along.   Not a good thing.

**Comment by Noemata** [comment]
Microsoft, please remove the following link from your docs website and place it somewhere more obviously associated with volunteer efforts with no association to the company:

https://docs.microsoft.com/en-us/cpp/build/vcpkg?view=vs-2019

It's misleading to have vcpkg in what outwardly looks like official documentation given this is not really an official tool that is supported in a professional manner where we can expect proper regression testing to be employed.

**Comment by PhoebeHui** [comment]
@Noemata, sorry for my late reply.

Related issue https://github.com/microsoft/vcpkg/issues/10072.
It seems that grpc adding dependency from revision 1.27.1(PR https://github.com/microsoft/vcpkg/pull/9963), however, adseil doesn't suport target UWP. so this is failed. I will help confirm.

@timautry, thanks for you comments!

**Comment by Noemata** [comment]
Just to be clear, it's not adseil, presumable that was a typo for abseil, and it is possible to build abseil for UWP as shown by the screenshot above.  The abseil exclusion should never have been added.  I'm guessing someone rushed this through not realizing it was straightforward to build abseil for UWP.

Hopefully, vcpkg build targets will be maintained across library releases.  I would rather see a given library not move forward, than to drop previously supported targets just for the sake of supporting the most current release.  I'm sure a lot more Linux libs could be supported by dropping Windows, which highlights the point of maintaining build target support across releases.

**Comment by PhoebeHui** [comment]
@Noemata, the PR has been merged, please get vcpkg latest source and try again. Let me know if you have any issue about this.
