### ISSUE TITLE
[double-conversion] build failure

### ISSUE THREAD

**Issue by xianglli** [microsoft/vcpkg#10264]
**Host Environment**
- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**
`./vcpkg install xxxx`

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.
Starting package 4/16: double-conversion:x64-windows
Building package double-conversion[core]:x64-windows...
-- Note: double-conversion only supports static library linkage. Building static library.
-- Downloading https://github.com/google/double-conversion/archive/v3.1.5.tar.gz...
-- Downloading https://github.com/google/double-conversion/archive/v3.1.5.tar.gz... Failed. Status: 18;"Transferred a partial file"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:175 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:132 (vcpkg_download_distfile)
  ports/double-conversion/portfile.cmake:5 (vcpkg_from_github)
  scripts/ports.cmake:90 (include)

Error: Building package double-conversion:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: double-conversion:x64-windows
  Vcpkg version: 2020.02.04-nohash

**Comment by NancyLi1013** [comment]
Hi @xianglli 

Thanks for posting this issue.
Could you please help confirm if you have access to  `https://github.com/google/double-conversion/archive/v3.1.5.tar.gz`?

If yes, please download `https://github.com/google/double-conversion/archive/v3.1.5.tar.gz` manually and put it into `VCPKG_PATH/downloads`, then rebuild `double-conversion`.

**Comment by NancyLi1013** [comment]
@xianglli 
Does this issue still exist on your local now?

**Comment by NancyLi1013** [comment]
Please feel free to reopen it if this is still a problem for you.
