### ISSUE TITLE
[openal-soft] macOS builds have no backends defined (thus, no audio output)

### ISSUE THREAD

**Issue by past-due** [microsoft/vcpkg#10266]
**Describe the bug**
The vcpkg port currently defines no suitable backends for macOS builds. Thus, while macOS builds compile without errors, they do not function properly. (No devices detected, no audio output.)

**Environment**
- OS: macOS

**To Reproduce**
1. ./vcpkg install openal-soft
2. Link to an application, attempt to open a device / output audio

PR forthcoming.

**Comment by PhoebeHui** [comment]
@past-due, thanks for your contribution!

The PR has been merged, so close this issue.
