### ISSUE TITLE
[doctest] update to 2.3.7

### ISSUE THREAD

**Issue by AMS21** [microsoft/vcpkg#10263]
Library name: doctest

New version number: 2.3.7

Other information that may be useful (release notes, etc...)
https://github.com/onqtam/doctest/blob/master/CHANGELOG.md#237-2020-02-24

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Port doctest has been updated to version 2.3.7, you can update vcpkg and rebuild it.
