### ISSUE TITLE
[bzip2] build failure

### ISSUE THREAD

**Issue by Lsz-20** [microsoft/vcpkg#10269]
**Host Environment**
- Windows10
- VS2017
something wrong when I using OpenMVS···
**To Reproduce**
`./vcpkg install vcpkg install zlib boost-iostreams boost-program-options boost-system boost-serialization eigen3 ceres opencv cgal[core] glew glfw3

**Failure logs** 
```
Package zlib:x64-windows is already installed
Elapsed time for package zlib:x64-windows: 7.817 ms
Starting package 2/54: opencv:x64-windows
Package opencv:x64-windows is already installed
Elapsed time for package opencv:x64-windows: 3.801 ms
Starting package 3/54: bzip2:x64-windows
Building package bzip2[core]:x64-windows...
-- Downloading https://github.com/past-due/bzip2-mirror/releases/download/v1.0.6/bzip2-1.0.6.tar.gz...
-- Downloading https://github.com/past-due/bzip2-mirror/releases/download/v1.0.6/bzip2-1.0.6.tar.gz... Failed. Status: 6;"Couldn't resolve host name"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:175 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  ports/bzip2/portfile.cmake:3 (vcpkg_download_distfile)
  scripts/ports.cmake:94 (include)


Error: Building package bzip2:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: bzip2:x64-windows
  Vcpkg version: 2019.09.12-nohash

Additionally, attach any relevant sections from the log files above.
```
**Additional context**
I download from https://github.com/past-due/bzip2-mirror/releases/download/v1.0.6/bzip2-1.0.6.tar.gz and put it into .\vcpkg\download\temp but it also didn't work and show the same problem····

**Comment by JackBoosY** [comment]
Please download `https://github.com/past-due/bzip2-mirror/releases/download/v1.0.6/bzip2-1.0.6.tar.gz` manually use proxy and put it into _VCPKG_PATH/downloads_, then rebuild bzip2.

Thanks.

**Comment by Lsz-20** [comment]
> 请`https://github.com/past-due/bzip2-mirror/releases/download/v1.0.6/bzip2-1.0.6.tar.gz`使用代理手动下载并放入_VCPKG_PATH / downloads_，然后重新_构建_ bzip2。
> 
> 谢谢。

**Comment by Lsz-20** [comment]
I have download this package,and I have try it put it into VCPKG_PATH / downloads/temp or VCPKG_PATH / downloads,but it still show me errors,here are the followings（when i Put into VCPKG_PATH / downloads）：

Starting package 3/54: bzip2:x64-windows
Building package bzip2[core]:x64-windows...
-- Using cached F:/Opencv/vcpkg/downloads/bzip2-1.0.6.tar.gz
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:99 (message):

  File does not have expected hash:

          File path: [ F:/Opencv/vcpkg/downloads/bzip2-1.0.6.tar.gz ]
      Expected hash: [ 00ace5438cfa0c577e5f578d8a808613187eff5217c35164ffe044fbafdfec9e98f4192c02a7d67e01e5a5ccced630583ad1003c37697219b0f147343a3fdd12 ]
        Actual hash: [ 80b646be32a7f7cdeb56de1c9205d4d46e55f6c985766038db238e23f293586ee06f54308b38087e0f54f0e8664ea7b076b651cc04e5068e50e8695b14827fda ]

  Please delete the file and retry if this file should be downloaded again.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:110 (test_hash)
  ports/bzip2/portfile.cmake:3 (vcpkg_download_distfile)
  scripts/ports.cmake:94 (include)

Error: Building package bzip2:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: bzip2:x64-windows
  Vcpkg version: 2019.09.12-nohash

Thanks

> 请`https://github.com/past-due/bzip2-mirror/releases/download/v1.0.6/bzip2-1.0.6.tar.gz`使用代理手动下载并放入_VCPKG_PATH / downloads_，然后重新_构建_ bzip2。
> 
> 谢谢。

**Comment by JackBoosY** [comment]
It seems that the source you downloaded is not the same as the one provided by the official website. Please use another URL to download it and replace it into _downloads_.

Well, use [this url](https://github.com/microsoft/vcpkg/files/4273303/bzip2-1.0.6.tar.gz).

**Comment by Lsz-20** [comment]
> 您下载的来源似乎与官方网站提供的来源不同。请使用另一个URL进行下载并将其替换为_下载_。
> 
> 好吧，使用[此url](https://github.com/microsoft/vcpkg/files/4273303/bzip2-1.0.6.tar.gz)。

It also didn't work and show the same error (′⌒`)
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:99 (message):

  File does not have expected hash:

          File path: [ F:/Opencv/vcpkg/downloads/bzip2-1.0.6.tar.gz ]
      Expected hash: [ 00ace5438cfa0c577e5f578d8a808613187eff5217c35164ffe044fbafdfec9e98f4192c02a7d67e01e5a5ccced630583ad1003c37697219b0f147343a3fdd12 ]
        Actual hash: [ cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e ]

  Please delete the file and retry if this file should be downloaded again.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:110 (test_hash)
  ports/bzip2/portfile.cmake:3 (vcpkg_download_distfile)
  scripts/ports.cmake:94 (include)

Error: Building package bzip2:x64-windows failed with: BUILD_FAILED

thanks

**Comment by JackBoosY** [comment]
Use [this](https://github.com/microsoft/vcpkg/files/4273414/bzip2-1.0.6.tar.gz)?

Seems like your network has problem, the downloaded file is corrupted.

**Comment by Lsz-20** [comment]
> Use [this](https://github.com/microsoft/vcpkg/files/4273414/bzip2-1.0.6.tar.gz)?
> 
> Seems like your network has problem, the downloaded file is corrupted.

Neither of those will succeed, I will try to download it using someone else's network

**Comment by JackBoosY** [comment]
Please modify _VCPKG_PATH/ports/bzip2/portfile.cmake_ and change hash `00ace5438cfa0c577e5f578d8a808613187eff5217c35164ffe044fbafdfec9e98f4192c02a7d67e01e5a5ccced630583ad1003c37697219b0f147343a3fdd12 ` to `cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e ` and try to build bzip2 again.

Thanks.

**Comment by Lsz-20** [comment]
> 请修改_VCPKG_PATH / ports / bzip2 / portfile.cmake_，并将hash更改`00ace5438cfa0c577e5f578d8a808613187eff5217c35164ffe044fbafdfec9e98f4192c02a7d67e01e5a5ccced630583ad1003c37697219b0f147343a3fdd12 `为，`cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e `然后尝试再次构建bzip2。
> 
> 谢谢。

Thanks for your help.there must be something wrong with my network,I can use others' network to download right bzip2.I'll try your new suggestion.
Thanks!!(*^__^*)
