### ISSUE TITLE
grpc patch to solve infinite loop in debug trace

### ISSUE THREAD

**Issue by quantotto** [microsoft/vcpkg#10270]
I am using Ubuntu 18.04 along with grpc 1.27.1 from vcpkg.

On Ubuntu, grpc might exhibit infinite loop. This issue is documented for 1.24.3 here: https://github.com/grpc/grpc/issues/20757 and it is still relevant for 1.27.1

The above thread also includes a patch for src/core/debug/trace.cc file.

I've updated my private ports/grpc with this patch and interested in submitting Pull request. Any objections?

Two files (.patch and updates portfile.cmake) attached in the below ZIP.
Thanks!
[grpc_patch.zip](https://github.com/microsoft/vcpkg/files/4271570/grpc_patch.zip)

**Comment by LilyWangL** [comment]
@quantotto Thanks for posting this issue. Do you have interesting to submit a pull request to fix this issue?

**Comment by quantotto** [comment]
Yep, @LilyWangL  I'll do that. Just wanted to verify. Thanks!

**Comment by quantotto** [comment]
submitted https://github.com/microsoft/vcpkg/pull/10278

**Comment by LilyWangLL** [comment]
@quantotto `grpc` has been updated to version v1.41.0, does this issue still exists?

**Comment by quantotto** [comment]
@LilyWangLL grpc kept the same behavior, so the issue is still there.

**Comment by LilyWangLL** [comment]
> @LilyWangLL grpc kept the same behavior, so the issue is still there.

Thanks for your reply. According the commeny https://github.com/microsoft/vcpkg/pull/10278#issuecomment-601544392, this issue is a upstream issue. This need upstream fix, if upstream fix this issue, we will sync fix to VCPKG.

**Comment by quantotto** [comment]
Yes, I understand. I will keep using a patch on my own private copy.

Thanks!

**Comment by JackBoosY** [comment]
Please reopen this issue when it is fixed upstream.
