### ISSUE TITLE
Can not install new ports.

### ISSUE THREAD

**Issue by lazyhamster** [microsoft/vcpkg#10279]
**Describe the bug**
New feature for recording stdout output during build prevents installation of any new port.

Build routine tries to create output file stdout-[triplet-name].log in buildtrees/[port-name] folder. But if this folder does not exists (e.g. port was never installed before) then process fails. And library installation process fails too.

If I manually create empty folder [port-name] in buildtrees/ then everything works fine. If I reinstall existing port or install version for another triplet then everything is fine too because port folder already exists.

**Environment**
- OS: Windows 10
- Compiler: MSVC 2017

**To Reproduce**
1. Choose any port that was never installed.
2. Try ./vcpkg install xxxx 
2. See error

**Expected behavior**
Port installed.

**Failure logs** 
Sample output.
```
E:\Work\Libraries\vcpkg>vcpkg install freetype
Computing installation plan...
The following packages will be built and installed:
    freetype[bzip2,core,png]:x86-windows
Starting package 1/1: freetype:x86-windows
Building package freetype[bzip2,core,png]:x86-windows...
Warning: abi keys are missing values:
    libpng
    zlib

Failed to open 'E:\Work\Libraries\vcpkg\buildtrees\freetype\stdout-x86-windows.log' for writing 

```

**Comment by timautry** [comment]
@lazyhamster I had this issue also, you may wish to try the following (fixed for me):
- cd _vcpkg-root_ (E:\Work\Libraries\vcpkg)
- git pull (this will update vcpkg scripts, code and ports)
- run the .\bootstrap.bat or ./bootstrap.sh as applicable (recompiles and links vcpkg to use new scripts and implement new code)
- vcpkg install freetype

As a general rule, when I do a "git pull" and I see the _vcpkg-root_\scripts and/or _vcpkg-root_\toolsrc files have changes, I run the bootstrap process afterwards to ensure the vcpkg executable and scripts are synchronized properly.

**Comment by JackBoosY** [comment]
Relate to [this changes](https://github.com/microsoft/vcpkg/commit/0ebb462870b7ec2bf41949a1a4eb777b90674406#diff-7c78ff08e66ca1729315028943b36e19).

**Comment by JackBoosY** [comment]
Duplicate with #10089.
