### ISSUE TITLE
Using vcpkg gives compilation errors in Visual Studio 2015

### ISSUE THREAD

**Issue by Nemoon** [microsoft/vcpkg#10282]
I am trying to compile (by porting) some code in Windows 10 that was originally developed for Linux.

The code depends on 2 external libraries: `cppkafka `and `librdkafka`. 

I saw that `vcpkg` is able to get the libraries, compile them, and then make them automatically available in Visual Studio 2015 (through the `vcpkg integrate install` command).

I see that the `vcpkg` compiles the dependencies for windows 64 (`cppkafka` and `librdkafka`) properly, as the .dll, .lib... are all made available on the install folder of `vcpkg`. 

When I try compiling my code in Visual Studio 2015, I see errors concerning the dependencies headers, which for me is unexpected. If `vcpkg` compiled them, why Visual Studio doesn't? From the `vcpkg` documentation, I assume they use the same compiler. Next I show some example errors I am getting:

```
1>------ Build started: Project: AndreKafkaDriver, Configuration: Release x64 ------
1>C:\...\vcpkg\installed\x64-windows\include\librdkafka/rdkafka.h(64): error C2371: 'ssize_t': redefinition; different basic types
1>  C:\Siemens\Automation\WinCC_OA\3.16\api\include\winnt\win32.h(47): note: see declaration of 'ssize_t'
1>c:\...\vcpkg\installed\x64-windows\include\cppkafka\header_list.h(265): warning C4267: 'argument': conversion from 'size_t' to 'ssize_t', possible loss of data
1>C:\...\vcpkg\installed\x64-windows\include\cppkafka/utils/buffered_producer.h(1035): error C2065: 'queue1': undeclared identifier
1>C:\...\vcpkg\installed\x64-windows\include\cppkafka/utils/buffered_producer.h(1035): error C2065: 'queue2': undeclared identifier
1>C:\...\vcpkg\installed\x64-windows\include\cppkafka/utils/buffered_producer.h(1035): error C2065: 'mutex': undeclared identifier
1>C:\...\vcpkg\installed\x64-windows\include\cppkafka/utils/buffered_producer.h(1035): error C2275: 'std::mutex': illegal use of this type as an expression
1>C:\...\vcpkg\installed\x64-windows\include\cppkafka/utils/buffered_producer.h(1035): note: see declaration of 'std::mutex'
1>C:\...\vcpkg\installed\x64-windows\include\cppkafka/utils/buffered_producer.h(1035): error C2182: 'swap_queues': illegal use of type 'void'
1>C:\...\vcpkg\installed\x64-windows\include\cppkafka/utils/buffered_producer.h(1035): error C2470: 'cppkafka::BufferedProducer<BufferType,Allocator>::swap_queues': looks like a function definition, but there is no parameter list; skipping apparent body
1>C:\...\vcpkg\installed\x64-windows\include\cppkafka/utils/buffered_producer.h(1035): error C2072: 'cppkafka::BufferedProducer<BufferType,Allocator>::swap_queues': initialization of a function
1>kafkaHWService.cxx(29): fatal error C1083: Cannot open include file: 'execinfo.h': No such file or directory
...
```

Thanks in advance,

Nerea

**Comment by PhoebeHui** [comment]
@Nemoon, thanks for reporting this issue!

Could you please provide us the repro steps and repro code?

**Comment by Nemoon** [comment]
Hello,
Fortunately, I was able to fix those errors regarding cppkafka library by changing the Visual Studio version from 2015 to 2017.  
Thanks anyways! :)

**Comment by PhoebeHui** [comment]
Great, thanks for your updates!

**Comment by AraHaan** [comment]
It would be nice to know how one can use vcpkg to install dependencies (and have it compile them) using the vs2015 toolset (for example if I need to install ``boost``, ``log4cxx``, ``apr``, and ``apr-util``, ``cryptopp``, etc (to name a few dependencies I might need).
