### ISSUE TITLE
gRPC appears to only link against static CRT

### ISSUE THREAD

**Issue by IIFE** [microsoft/vcpkg#10289]
****

**Is your feature request related to a problem? Please describe.**
the gRPC port appears to build gRPC against static CRT using the following option:
`-DgRPC_MSVC_STATIC_RUNTIME=${gRPC_MSVC_STATIC_RUNTIME}`

This is problematic when consuming the gRPC libraries in a solution that only relies on the dynamic CRT.

In my triplet override I am specifying `set(VCPKG_CRT_LINKAGE dynamic)`, however I believe that is getting ignored by the `-DgRPC_MSVC_STATIC_RUNTIME=${gRPC_MSVC_STATIC_RUNTIME}` option.

**Proposed solution**
Allow gRPC to be built against dynamic CRT.

**Describe alternatives you've considered**
I am thinking of changing the port to link against dynamic CRT, however I'm not sure how to best do that as I'm not familiar with the side effects of the gRPC options.

**Additional context**
Visual Studio 2015, Windows.

**Comment by IIFE** [comment]
Strangely, which I run `dumpbin /DIRECTIVES grpc.lib` it shows `/DEFAULTLIB:MSVCRT`. What does the `-DgRPC_MSVC_STATIC_RUNTIME=${gRPC_MSVC_STATIC_RUNTIME}` option actually do, as I think I'm getting confused by it.

**Comment by IIFE** [comment]
Furthermore, any reason gRPC is only built as static lib. Following option in port file appears to indicate so:
`vcpkg_check_linkage(ONLY_STATIC_LIBRARY)`

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Due to grpc has problems with exporting symbols, it only support static build. You can get more information from: #539 #535

**Comment by IIFE** [comment]
@LilyWangL Thanks for your reply.

OK that's no problem if it builds as a static lib. However, I just want to confirm my understanding. gRPC is built as a static lib, however it's linked against the dynamic CRT, correct?

Thanks.

**Comment by LilyWangL** [comment]
If you build grpc:x86-windows, you will get a static lib and it's linked the dynamic CRT.

**Comment by IIFE** [comment]
Thanks for the confirmation.
