### ISSUE TITLE
[tinyxml2] Generate suffixed debug libraries

### ISSUE THREAD

**Issue by brad-anderson** [Microsoft/vcpkg#1028]
This is the same issue as #710 but for tinyxml2. Using `find_package(tinyxml2)` with a Release configuration finds the debug version of `tinyxml2.lib` resulting in the usual `_ITERATOR_DEBUG_LEVEL` and RuntimeLibrary mismatches at link time.

I'm using a `FindTinyXML2.cmake` floating around the web but `find_library` would have the same problem as that's all the module is using.

**Comment by eco** [comment]
I submitted an [upstream patch](https://github.com/leethomason/tinyxml2/pull/551) to hopefully help address this (just adding the usual "d" suffix).

**Comment by NancyLi1013** [comment]
The PR has been merged. It should be fixed.
