### ISSUE TITLE
[tesseract] Running tesseract.exe failed

### ISSUE THREAD

**Issue by huang-lijin** [microsoft/vcpkg#10299]
**Host Environment**
- OS: windows7 x64
- Compiler: vs2015

**To Reproduce**
`./vcpkg install tesseract`

**Failure logs** 
The installation shows that the installation is successful, and the installation of lib and exe files is successful. But when I use testeract.exe to identify the text, I make an error. When I enter vs debugging, I find that it is "__m128i packed1 = _mm_loadl_epi64(reinterpret_cast<const __m128i*>(u));" in getutf8text. Function execution error

**Comment by LilyWangL** [comment]
@huang-lijin Thanks for posting this issue. Do you install tesseract failed? If install failed, please attach the log file `install-triplet-dbg-out.log`.

**Comment by huang-lijin** [comment]
@LilyWangL I succeeded in installing Tesseract, but an error occurred when I ran tesseract.exe。When I enter vs debugging, I find that it is "__m128i packed1 = _mm_loadl_epi64" function error

**Comment by LilyWangL** [comment]
@huang-lijin If you have any question about using tesseract.exe, you can submit an issue on tesseract's source page: https://github.com/tesseract-ocr/tesseract/issues. There are more tesseract's contributors, they are more familiar with tesseract. 

Thanks.

**Comment by huang-lijin** [comment]
I know how to use testeract, I have used the official download of EXE file. However, I failed when I tried to use the EXE file created through ". / vcpkg install testeract: x64-windows-static".

**Comment by LilyWangL** [comment]
Could you please provide the command and repro steps which can use the EXE file to reproduce the function error? Thanks.

**Comment by huang-lijin** [comment]
[tesseract.zip](https://github.com/microsoft/vcpkg/files/4291502/tesseract.zip)
error for "tesseract.exe 111.tif out"

**Comment by linquize** [comment]
What kind of error at `_mm_loadl_epi64`?
Memory address misalignment issue?
What CPU did you use?

**Comment by huang-lijin** [comment]
My CPU is Intel Pentium G3220.

**Comment by huang-lijin** [comment]
My CPU is Intel Pentium G3220.
Yes, the error is memory address misalignment issue.
I find some data, some people say it is the Instruction set error.
buy my CPU is support SSE4. So I don't know why.

**Comment by JackBoosY** [comment]
Hi @huang-lijin, does this issue still exist?
```
PS F:\vcpkg\packages\tesseract_x86-windows\tools\tesseract> .\tesseract.exe 111.tif out
Error opening data file F:\vcpkg\packages\tesseract_x86-windows\tools\tesseract/tessdata/eng.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.
Failed loading language 'eng'
Tesseract couldn't load any languages!
Could not initialize tesseract.
PS F:\vcpkg\packages\tesseract_x86-windows\tools\tesseract>
```
Can you please provide the traning file?

Thanks.

**Comment by JackBoosY** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
