### ISSUE TITLE
[New Port Request] <S2 Geometry Library>

### ISSUE THREAD

**Issue by sotex** [microsoft/vcpkg#10296]
Library name:
S2 Geometry Library

Library description:
![s2hierarchy](https://s2geometry.io/devguide/img/s2hierarchy.gif)
A unique feature of the S2 library is that unlike traditional geographic information systems, which represent data as flat two-dimensional projections (similar to an atlas), the S2 library represents all data on a three-dimensional sphere (similar to a globe). This makes it possible to build a worldwide geographic database with no seams or singularities, using a single coordinate system, and with low distortion everywhere compared to the true shape of the Earth. While the Earth is not quite spherical, it is much closer to being a sphere than it is to being flat!

Source repository URL:
[https://github.com/google/s2geometry](https://github.com/google/s2geometry)

Project homepage (if different from the source repository):
[https://s2geometry.io/](https://s2geometry.io/)

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

[Fix a windows compile error #30](https://github.com/google/s2geometry/pull/30)
[Request: Option to not require external dependencies for static linking scenarios #8](https://github.com/google/s2geometry/issues/8)

**Comment by Voskrese** [comment]
release https://github.com/google/s2geometry/archive/v0.9.0.tar.gz

build ok, win x64

`Build-Depends: gtest, glog, gflags, openssl
`
dynamic
```
    OPTIONS 
      -DWITH_GFLAGS=OFF
      -DWITH_GLOG=OFF
      -DBUILD_EXAMPLES=OFF
```

static
```
    OPTIONS 
      -DWITH_GFLAGS=ON
      -DWITH_GLOG=ON
      -DBUILD_EXAMPLES=OFF
```

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by nside** [comment]
why not package this library?

**Comment by varpande** [comment]
Hi. is there any update on this @LilyWangL ? There is a duplicate issue on this here #21706.

**Comment by PhoebeHui** [comment]
We're happy to answer any questions we can to support this effort, but for now we'd prefer to support your role as a maintainer than to take ownership ourselves. None of our core team is very familiar with s2geometry, so we feel you'll do a much better job than we could! consider making a pull request.

**Comment by ankitgit** [comment]
@PhoebeHui we need also this change can you please give add me as a maintainer and I will open a PR for this.
