### ISSUE TITLE
vcpkg should work in Visual Studio Code the same way it works in Visual Studio

### ISSUE THREAD

**Issue by BillyONeal** [microsoft/vcpkg#10297]
**Is your feature request related to a problem? Please describe.**
Intellisense in Visual Studio understands which libraries are provided by vcpkg, and displays accurate intellisense information and similar resulting from this information. Unfortunately, VS Code (and/or the C++ extension for VS Code) don't look for the same signals. This was reported by @SuperWig over here: https://github.com/microsoft/STL/pull/572#issuecomment-594084726

**Proposed solution**
Either `vcpkg integrate install` should set appropriate system metadata that VS Code looks for (ideally on all platforms), or VS Code or the C++ extension thereof should check the same place VS checks when doing CMake configure steps.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by SuperWig** [comment]
>or the C++ extension thereof should check the same place VS checks when doing CMake configure steps.

Wouldn't that be the CMakeTools extension  - https://github.com/microsoft/vscode-cmake-tools - and not the C++ one?

**Comment by BillyONeal** [comment]
I don't know. There's some overlap here. The CMake extension is the thing that would do cmake processing but it's the C++ extension that actually consumes the resulting header / define / configuration information.

**Comment by BillyONeal** [comment]
It looks like this works now ?
