### ISSUE TITLE
[geographiclib] update to 1.50.1

### ISSUE THREAD

**Issue by brunotl** [microsoft/vcpkg#10293]
Library name: GeographicLib

New version number: 1.50.1

Other information that may be useful (release notes, etc...)

https://geographiclib.sourceforge.io/

version 1.50.1 is version update to support the WMM2020 magnetic model expected to be available 2019-12-10.

**Comment by jjpepper** [comment]
I'm getting an error when trying to install the current version:

```-- Downloading https://jaist.dl.sourceforge.net/project/geographiclib/distrib/GeographicLib-1.47-patch1.zip...
-- Downloading https://jaist.dl.sourceforge.net/project/geographiclib/distrib/GeographicLib-1.47-patch1.zip... Failed. Status: 22;"HTTP response code said error"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:172 (message):
      
      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:***@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues
```
Is this expected?  Should I raise a separate issue for this?  I'm not behind a proxy.

**Comment by NancyLi1013** [comment]
Hi @jjpepper 

Could you please help confirm if you have access to `https://jaist.dl.sourceforge.net/project/geographiclib/distrib/GeographicLib-1.47-patch1.zip`?

**Comment by jjpepper** [comment]
It seems like a HTML page is returned for that URL now. Maybe the file has
moved and a website gets returned when that happens.

**Comment by jjpepper** [comment]
I suspect it’s because it was pointing at a patch release which has been
removed in favour of a newer stable version. So likely the package just
needs to be updated.

**Comment by NancyLi1013** [comment]
Thanks for your info.
I also test this on my local and the current package still can be downloaded successfully. The package is not removed from the website now.

But I will try to update this port to latest version these days.

**Comment by jjpepper** [comment]
It appears to be flaky.  It's failed about 60% of the times I've tried to
run vcpkg install geographiclib today.

**Comment by NancyLi1013** [comment]
Hi all,
`geographiclib ` has been updated, please update vcpkg to the latest version and try to rebuild this port.
