### ISSUE TITLE
How do I minimize the amount of shared libraries?

### ISSUE THREAD

**Issue by jabra98** [microsoft/vcpkg#10298]
Hello, is there a way to reduce the amount of shared libraries generated/needed when installing a package like Qt5? I usually had to provide three .dlls to get everything running (QtCore, QtGui, QtWidgets) when I downloaded the binaries directly. Now after building it and trying to link it dynamically (using the x64-windows triplet), my binary folder gets filled with loads of other .dlls which seem to be dependencies of the three core module I need. This tremendously increases my linking times.. Is there a way to get rid of those?

**Comment by JackBoosY** [comment]
Usually, we use `feature` to separate the port's dependencies, and only use the command `.\vcpkg install ${PORT}[core]` to build will use only the minimum dependencies (required).
In qt5, this situation becomes complicated.

@Neumann-A

**Comment by Neumann-A** [comment]
in qt5 there are no dependency features yet and vcpkg is build qt with everything enabled. We could provide features in the future but for the time being lets focus on getting qt updated first. 
If you want to minimize the dependencies yourself you need to modify the portfile of qt5-base with the configure option you would like qt5-base being build with.

**Comment by jbar98** [comment]
Can you tell me what would be needed to change in that portfile?
