### ISSUE TITLE
[New Port Request] <SoapySDR>

### ISSUE THREAD

**Issue by eix128** [microsoft/vcpkg#10294]
Library name: 
SoapySDR  

Library description:

SoapySDR is general software defined radio.
That works universally accross all RF platforms.
Hacker RF , LimeSDR , Ettus etc....

Source repository URL:

https://github.com/pothosware/SoapySDR

Project homepage (if different from the source repository):

https://github.com/pothosware/SoapySDR/wiki

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by howard0su** [comment]
#39729
