### ISSUE TITLE
usockets activate ssl again

### ISSUE THREAD

**Issue by daef** [microsoft/vcpkg#10292]
Library name: usockets

according to [this](https://github.com/microsoft/vcpkg/blob/master/ports/usockets/CMakeLists.txt#L6) ssl is [deactivated](https://github.com/microsoft/vcpkg/blob/master/ports/usockets/portfile.cmake#L15) because of an [closed issue](https://github.com/microsoft/vcpkg/issues/4267) .

**Comment by JackBoosY** [comment]
Hi @daef, thanks for reporting this issue!
I've added these features in #10303, please update vcpkg and rebuild usockets[ssl].

Thanks.
