### ISSUE TITLE
[cgal]Failed to download

### ISSUE THREAD

**Issue by Lsz-20** [microsoft/vcpkg#10300]
Starting package 6/11: cgal:x64-windows
Building package cgal[core]:x64-windows...
-- Downloading https://github.com/CGAL/cgal/archive/releases/CGAL-4.14.tar.gz...
-- Downloading https://github.com/CGAL/cgal/archive/releases/CGAL-4.14.tar.gz... Failed. Status: 18;"Transferred a partial file"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:175 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:108 (vcpkg_download_distfile)
  ports/cgal/portfile.cmake:5 (vcpkg_from_github)
  scripts/ports.cmake:94 (include)

Error: Building package cgal:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: cgal:x64-windows
  Vcpkg version: 2019.09.12-nohash

Additionally, attach any relevant sections from the log files above.
And I try to download from https://github.com/CGAL/cgal/archive/releases/CGAL-4.14.tar.gz and put it into 。./vcpkg/download or ./vcpkg/download/temp ,but it's still not working,and show me the same failed or the wrong hash
Is there a problem with the downloaded website?
Thanks

**Comment by NancyLi1013** [comment]
Hi @Lsz-20 

Thanks for posting this issue.

Please download https://github.com/CGAL/cgal/archive/releases/CGAL-4.14.tar.gz manually use proxy and put it into VCPKG_PATH/downloads, then rebuild `cgal`.

BTW, `cgal` has been updated to 5.0.2. You can try to update vcpkg and rebuild this port.

**Comment by Lsz-20** [comment]
> 嗨@ Lsz-20
> 
> 感谢您发布此问题。
> 
> 请使用代理手动下载https://github.com/CGAL/cgal/archive/releases/CGAL-4.14.tar.gz并将其放入VCPKG_PATH / downloads中，然后重新构建`cgal`。
> 
> BTW，`cgal`已更新至5.0.2。您可以尝试更新vcpkg并重建此端口。

Thanks for your advice,I download https://github.com/CGAL/cgal/archive/releases/CGAL-4.14.tar.gz manually use proxy but it still show me the same fault···

**Comment by NancyLi1013** [comment]
Could you try to update vcpkg and build the new version 5.0.2?
Please help confirm if this version is the same issue.

**Comment by Lsz-20** [comment]
> 您可以成功下载 https://github.com/CGAL/cgal/archive/releases/CGAL-4.14.tar.gz，这表明网站没有问题。
> 
> 您可以尝试更新vcpkg并构建新版本5.0.2吗？
> 请帮助确认此版本是否相同。

Thanks for your help，I have deal it well now.O(∩_∩)O
