### ISSUE TITLE
[sdl2-mixer] build failure on pre-Catalina macOS

### ISSUE THREAD

**Issue by kevinlul** [microsoft/vcpkg#10318]
**Host Environment**
- OS: macOS 10.14.6
- Compiler: Apple clang version 11.0.0 (clang-1100.0.33.17)

**To Reproduce**
`./vcpkg install sdl2-mixer[libflac,libogg,mpg123]`

**Failure logs** 
The key issue seems to be that `os/availability.h` either does not exist or is marked with `API_UNAVAILABLE` in older Xcode SDKs.

**Additional context**
Regression appears to be introduced by #10201

**Comment by Toxe** [comment]
Can you use another compiler or do you _have_ to use AppleClang?

**Comment by kevinlul** [comment]
I don't see the relevance, but in general you can change the compiler by setting the `CC` and `CXX` environment variables. However, Apple Clang is the platform compiler for macOS.

**Comment by Toxe** [comment]
True, I was just asking to give you a workaround just in case.

**Comment by LilyWangL** [comment]
I try to install other ports's feature, and get the same error: `zsh: no matches found: port[feature]`. Could you please confirm this? @strega-nil

**Comment by Toxe** [comment]
@LilyWangL That is because your shell is interpreting the `[]` as a wildcard. I am using zsh as well, try putting it into quotes, like: `vcpkg install "sdl2-mixer[libflac,libogg,mpg123]"`

**Comment by strega-nil** [comment]
hmm... on the one hand, I'm not sure if we should support pre-Catalina macOS. I don't think Apple supports previous versions of macOS. On the other hand, I can see that someone might want this to be a feature; it may make sense to make this a default feature, as opposed to _always_ working.

@kevinlul If you'd like to change this, I'd be happy to merge a PR that makes native MIDI support a default feature. That should fix it.

**Comment by kevinlul** [comment]
Apple generally supports the last three released major versions. As of writing, 10.13 High Sierra has extended support until September. Thus, Homebrew tests the most recent three versions and ships bottles for those. I can look more in-depth into how this can be patched but in the meantime I've locally reverted the PR that introduced the regression for my uses.

**Comment by strega-nil** [comment]
Hmm, good to know. Thanks @kevinlul, it's really hard to figure out exactly what macOS versions are supported.
