### ISSUE TITLE
[New Port Request] TFT-eSPI

### ISSUE THREAD

**Issue by estradjm** [microsoft/vcpkg#10310]
Library name: TFT-eSPI

Library description:
Arduino and PlatformIO IDE compatible TFT library optimised for the STM32, ESP8266 and ESP32 that supports different driver chips

Source repository URL:
git@github.com:Bodmer/TFT_eSPI.git

Project homepage (if different from the source repository):
https://github.com/Bodmer/TFT_eSPI

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
