### ISSUE TITLE
atk build failure

### ISSUE THREAD

**Issue by shalinsirwani** [microsoft/vcpkg#10312]
**Host Environment**
- OS: [Windows]
- Compiler: vs142

**To Reproduce**
`./vcpkg install atk`

**Failure logs** 

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/atk/portfile.cmake:27 (vcpkg_install_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package atk:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: atk:x86-windows
  Vcpkg version: 2018.11.23

**Comment by NancyLi1013** [comment]
Hi @shalinsirwani 
Thanks for posting this issue.
Could you please post the fail log?
BTW, I noticed that you used old version vcpkg. Could you please try to update vcpkg(2020.02.04) and build it again?

**Comment by shalinsirwani** [comment]
i downloaded vcpkg today

**Comment by NancyLi1013** [comment]
> Error: Building package atk:x86-windows failed with: BUILD_FAILED
> Please ensure you're using the latest portfiles with `.\vcpkg update`, then
> submit an issue at https://github.com/Microsoft/vcpkg/issues including:
> Package: atk:x86-windows
> Vcpkg version: 2018.11.23

Please see above info. 
You can use `git pull `to update vcpkg and use `vcpkg version` to check if the version is latest.

If there is still the same error, please provide the failure logs.

Thanks.

**Comment by shalinsirwani** [comment]
in this version of vcpkg "2020.02.04" problems solves. 
thank you.
closing thread..:)
