### ISSUE TITLE
[New Port Request] eXosip2

### ISSUE THREAD

**Issue by wuzangsama** [microsoft/vcpkg#10313]
Library name: eXosip2

Library description: 
eXosip is a library that hides the complexity of using the SIP protocol for mutlimedia session establishement. This protocol is mainly to be used by VoIP telephony applications (endpoints or conference server) but might be also usefull for any application that wish to establish sessions like multiplayer games.

Source repository URL:
http://git.savannah.nongnu.org/cgit/exosip.git
http://download.savannah.nongnu.org/releases/exosip/libexosip2-5.1.1.tar.gz

Project homepage (if different from the source repository):
https://savannah.nongnu.org/projects/exosip

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
