### ISSUE TITLE
vc[ffmpeg] build failure

### ISSUE THREAD

**Issue by ZhengzhongSun** [microsoft/vcpkg#10321]
**Host Environment**
- OS: [Windows 10 Pro]
  Package: ffmpeg:x64-windows
  Vcpkg version: 2020.02.04-nohash

**To Reproduce**
`./vcpkg install ffmpeg:x64-windows`

**Failure logs** 
Computing installation plan...
The following packages will be built and installed:
    ffmpeg[avresample,core]:x64-windows
Starting package 1/1: ffmpeg:x64-windows
Building package ffmpeg[avresample,core]:x64-windows...
-- Downloading https://github.com/ffmpeg/ffmpeg/archive/n4.2.tar.gz...
-- Extracting source E:/Projects/github/vcpkg/downloads/ffmpeg-ffmpeg-n4.2.tar.gz
-- Applying patch 0001-create-lib-libraries.patch
-- Applying patch 0002-detect-openssl.patch
-- Applying patch 0003-fix-windowsinclude.patch
-- Applying patch 0004-fix-debug-build.patch
-- Applying patch 0005-fix-libvpx-linking.patch
-- Using source at E:/Projects/github/vcpkg/buildtrees/ffmpeg/src/n4.2-b7812eeecc
-- Acquiring MSYS Packages...
-- Acquiring MSYS Packages... OK
-- Building Options: --enable-asm --enable-yasm --disable-doc --enable-debug --enable-runtime-cpudetect --disable-openssl --disable-ffmpeg --disable-ffplay --disable-ffprobe --disable-libvpx --disable-libx264 --disable-opencl --disable-lzma --disable-bzlib --enable-avresample  --disable-static --enable-shared --extra-cflags=-DHAVE_UNISTD_H=0
-- Building Release Options:  --extra-cflags=-MD --extra-cxxflags=-MD
-- Building ffmpeg for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: E:/Projects/github/vcpkg/downloads/tools/msys2/msys64/usr/bin/bash.exe --noprofile --norc E:/Projects/github/vcpkg/ports/ffmpeg\build.sh E:/Projects/github/vcpkg/buildtrees/ffmpeg/x64-windows-rel E:/Projects/github/vcpkg/buildtrees/ffmpeg/src/n4.2-b7812eeecc E:/Projects/github/vcpkg/packages/ffmpeg_x64-windows "--enable-asm --enable-yasm --disable-doc --enable-debug --enable-runtime-cpudetect --disable-openssl --disable-ffmpeg --disable-ffplay --disable-ffprobe --disable-libvpx --disable-libx264 --disable-opencl --disable-lzma --disable-bzlib --enable-avresample  --disable-static --enable-shared --extra-cflags=-DHAVE_UNISTD_H=0  --extra-cflags=-MD --extra-cxxflags=-MD"
    Working Directory: E:/Projects/github/vcpkg/buildtrees/ffmpeg/x64-windows-rel
    Error code: 127
    See logs for more information:
      E:\Projects\github\vcpkg\buildtrees\ffmpeg\build-x64-windows-rel-out.log

Call Stack (most recent call first):
  ports/ffmpeg/portfile.cmake:193 (vcpkg_execute_required_process)
  scripts/ports.cmake:90 (include)

Error: Building package ffmpeg:x64-windows failed with: BUILD_FAILED

**Additional context**
[build-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/4296248/build-x64-windows-rel-out.log)

**Comment by cenit** [comment]
#9818 
We were able to fix the issue removing the downloads\tools\msys2 folder and then restarting the build. Might be problematic now since the msys2 website for redownloading is down and the PR to fix the issue is still pending

**Comment by ZhengzhongSun** [comment]
> #9818
> We were able to fix the issue removing the downloads\tools\msys2 folder and then restarting the build. Might be problematic now since the msys2 website for redownloading is down and the PR to fix the issue is still pending

Thanks! This solution works for me.
