### ISSUE TITLE
[New Port Request] jrtplib

### ISSUE THREAD

**Issue by wuzangsama** [microsoft/vcpkg#10324]
Library name: jrtplib

Library description: a C++ implementation of the RTP(Real-time Transport Protocol)

Source repository URL:
https://github.com/j0r1/JRTPLIB

Project homepage (if different from the source repository):
https://github.com/j0r1/JRTPLIB

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
maybe should rely on openssl

**Comment by japj** [comment]
Unfortunately, it seems the developer of JRTLIB has just decided to end development:
https://github.com/j0r1/JRTPLIB/blob/master/README.md

**Comment by wuzangsama** [comment]
OK, thansk for reply, I have write the portfile in my own project, I can still use it personally.

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
