### ISSUE TITLE
MSYS2 acquisition failed

### ISSUE THREAD

**Issue by bogdanlytvynovskyi** [microsoft/vcpkg#10322]
**Describe the bug**
When doing fresh build from vcpkg anything that requires msys2, build will fail due to repo.msys2.org being down

**Environment**
- OS: Windows
- Compiler: NA

**To Reproduce**
1. ./vcpkg install ffmpeg
2. See error

**Expected behavior**
I would expect for msys retrieval code target mirrors in case repo.msys2.org is down

msys2 issue reported here: https://github.com/msys2/MSYS2-packages/issues/1884

**Comment by JackBoosY** [comment]
Related: [#1098](https://github.com/msys2/MSYS2-packages/issues/1098)

**Comment by Voskrese** [comment]
copy
https://github.com/msys2/MSYS2-packages/tree/master/pacman-mirrors

to
...\vcpkg\downloads\tools\msys2\msys64\etc\pacman.d

**Comment by bogdanlytvynovskyi** [comment]
@JackBoosY  - it seems that vcpkg_acquire_msys.cmake has support for mirrors. Following patch did a trick for me. Would you kindly take care of creating proper PR for this?
[msys2_mirror.txt](https://github.com/microsoft/vcpkg/files/4300204/msys2_mirror.txt)

**Comment by MaverickTse** [comment]
> @JackBoosY - it seems that vcpkg_acquire_msys.cmake has support for mirrors. Following patch did a trick for me. Would you kindly take care of creating proper PR for this?
> [msys2_mirror.txt](https://github.com/microsoft/vcpkg/files/4300204/msys2_mirror.txt)

The one reason that I'm reluctant to make a PR is that any "mirror" hardcoded in the cmake script is going to receive increased traffic, and I cannot tell if any mirror is more reliable than others (Personal server is out, China server... may not be comfortable for everyone).

Also the pacman -Syu command will also access the default repo.msys2.org.

In addition, running pacman -Syu from a 2018 archive can take quite a while and MAY break msys2 itself.

**Comment by bogdanlytvynovskyi** [comment]
> The one reason that I'm reluctant to make a PR is that any "mirror" hardcoded in the cmake script is going to receive increased traffic, and I cannot tell if any mirror is more reliable than others

This is the reason mirrors exist, unless I am missing something. Working is better than non working IMO.

>Also the pacman -Syu command will also access the default repo.msys2.org.

Yes it does, and then resorts to other mirrors.

> In addition, running pacman -Syu from a 2018 archive can take quite a while and MAY break msys2 itself

Not sure specifically about this concern. I took exactly same version as currently used and it worked pretty well for me

**Comment by ylluminate** [comment]
After a fresh install from downloading and installing from a nightly installer build, where do you put the mirror list so that `pacman -Syu` works again? 

Out of the box this simply fails and doesn't try to pull from mirrors for me...

**Comment by MaverickTse** [comment]
At lease the 20190524 xz version works for me. Tested with building icu:x64-windows. The older 2018 version has problem with mirror however.
I'd refrain from using nightly... can be too buggy for an important infrastructure

**Comment by MaverickTse** [comment]
There is a PKGBUILD package in the github msys2 repo that handles mirror:

https://github.com/msys2/MSYS2-packages/tree/master/pacman-mirrors
