### ISSUE TITLE
Any command for downloading all the repo

### ISSUE THREAD

**Issue by eix128** [microsoft/vcpkg#10328]
Is there any way to download all the ports to offline disk ?
So that i can use it without internet.

We have big disks , size doesnt matter.
Sometimes we need to work offline machines.

I just need to filter by :
linux-x86 , linux-x64 , windows-x64 , windows-x86 , ARM Win/Linux , RiscV Win/Linux also

**Comment by linquize** [comment]
Not yet.

When you build a package, some tools (binaries) are downloaded, and the source code of the libraries are downloaded, but not the binaries of the libraries.

**Comment by NancyLi1013** [comment]
Hi @eix128 
Thanks for posting this issue.
Currently, there is no command to meet your demand, except for downloading these ports manually.

Maybe you can clone this [commit](https://github.com/JackBoos/vcpkg/commit/f18021e479500f5782234cd538e218b7cad642c1
) to use `./vcpkg install *` to download all the ports. 

Note: This way is only adapted to Windows platform. Also this is not an official commit, which is maintained by personal person.

**Comment by NancyLi1013** [comment]
@eix128 
Please let me know if you have any concerns about this issue.

**Comment by NancyLi1013** [comment]
Please feel free to reopen this issue if this is still a problem for you.
Close it due to no response.
