### ISSUE TITLE
[expat] build failure

### ISSUE THREAD

**Issue by bbblanccc** [microsoft/vcpkg#10336]
**Host Environment**
- OS: Windows 10
- Compiler: Cmake

**To Reproduce**
`./vcpkg.exe install expat`

**Failure logs** 
```
CMake Error: Problem with archive_write_header(): Can't create ''
CMake Error: Current file: libexpat-R_2_2_7/README.md
CMake Error: Problem extracting tar: D:/CDH/vcpkg/downloads/libexpat-libexpat-R_2_2_7.tar.gz
```

**Additional context**
I tried `cmake.exe -E tar zxvf libexpat-libexpat-R_2_2_7.tar.gz` and failed again. Seems like the tar.gz archive contains error or packed just for linux.

**Comment by linquize** [comment]
Can you `git pull` latest vcpkg and try again?
Visual Studio version?
CMake is not a compiler.

**Comment by bbblanccc** [comment]
The vcpkg is already latest 2020.02.04-nohash, VS is Community 2019 ver 16.4.5. 

The PowerShell said:

```
Building package expat[core]:x86-windows...
-- Downloading https://github.com/libexpat/libexpat/archive/R_2_2_7.tar.gz...
-- Extracting source D:/CDH/vcpkg/downloads/libexpat-libexpat-R_2_2_7.tar.gz
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: D:/CDH/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe -E tar xjf D:/CDH/vcpkg/downloads/libexpat-libexpat-R_2_2_7.tar.gz
    Working Directory: D:/CDH/vcpkg/buildtrees/expat/src/TEMP
    Error code: 1
    See logs for more information:
      D:\CDH\vcpkg\buildtrees\expat\extract-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_extract_source_archive.cmake:43 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_extract_source_archive_ex.cmake:108 (vcpkg_extract_source_archive)
  scripts/cmake/vcpkg_from_github.cmake:139 (vcpkg_extract_source_archive_ex)
  ports/expat/portfile.cmake:6 (vcpkg_from_github)
  scripts/ports.cmake:90 (include)
```
Thanks for correcting, I suggest the compiler is gcc (mingw).

**Comment by linquize** [comment]
What is the content of `D:\CDH\vcpkg\buildtrees\expat\extract-err.log`

**Comment by linquize** [comment]
What is the content of `D:\CDH\vcpkg\buildtrees\expat\extract-err.log`?

**Comment by bbblanccc** [comment]
It's just :
```
CMake Error: Problem with archive_write_header(): Can't create ''
CMake Error: Current file: libexpat-R_2_2_7/README.md
CMake Error: Problem extracting tar: D:/CDH/vcpkg/downloads/libexpat-libexpat-R_2_2_7.tar.gz
```

**Comment by linquize** [comment]
Did you enable Windows 10 **Developer Mode**?
This tar file has symbolic links inside (`README.md` is a symbolic link).

**Comment by linquize** [comment]
What is your Windows 10 version?

**Comment by linquize** [comment]
Can you delete `downloads` directory and try again?

**Comment by NancyLi1013** [comment]
Hi @bbblanccc 
Thanks for posting this issue.
I cannot reproduce this issue on my local.
Could you please refer to #6059 to try it again?

@linquize 
Thanks for your above guides for this issue.

**Comment by bbblanccc** [comment]
Really sorry for not responding, and thanks for your help 🤝  @linquize. The problem is caused by locale settings (UTF-8) and is solved!
@NancyLi1013 I've changed the encoding of win and the problem was solved, thanks a lot! 👍

**Comment by NancyLi1013** [comment]
@bbblanccc 
Thanks for your instant feedback.
Since this issue is solved now. I close it.
