### ISSUE TITLE
[avro-c] build failure

### ISSUE THREAD

**Issue by kreuzerkrieg** [microsoft/vcpkg#10339]
- OS:  Linux
- Compiler: GCC9.2.1
`./vcpkg install avro-c`
-Cut and past the appropriate build messages from the console output.
-- The C compiler identification is GNU 9.2.1
-- The CXX compiler identification is GNU 9.2.1
-- Check for working C compiler: /usr/lib/ccache/cc
-- Check for working C compiler: /usr/lib/ccache/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/lib/ccache/c++
-- Check for working CXX compiler: /usr/lib/ccache/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found ZLIB: /home/user/Development/vcpkg/installed/x64-linux/debug/lib/libz.a (found version "1.2.11") 
-- Found Snappy: /home/user/Development/vcpkg/installed/x64-linux/lib/libsnappy.a  
-- Could NOT find LIBLZMA (missing: LIBLZMA_DIR)
-- Configuring incomplete, errors occurred!
See also "/home/user/Development/vcpkg/buildtrees/avro-c/x64-linux-dbg/CMakeFiles/CMakeOutput.log".

`liblzma` is already installed
Package liblzma:x64-linux is already installed

EDIT001: Ok, it started with wrong package names used and ended with avro not compiling on linux with `snappy`

**Comment by kreuzerkrieg** [comment]
any news?

**Comment by LilyWangL** [comment]
> any news?

This issue will be fixed in PR #9898.

**Comment by LilyWangL** [comment]
@kreuzerkrieg Thanks for posting this issue. The port avro-c has been updated to version 1.9.2 in PR #10380, and it doesn't support triplet `uwp` `Linux` `OSX`.

**Comment by kreuzerkrieg** [comment]
any reason it would not support Linux?

**Comment by LilyWangL** [comment]
@spektom Could you help confirm avro-c doesn't support triplet `Linux`? Thanks in advance.

**Comment by kreuzerkrieg** [comment]
when you say "avro-c" do you mean the port or the apache foundation project? according to [this ](https://github.com/apache/avro/blob/master/lang/c/INSTALL)the obly OS not mentioned there is Windows. I guess `build.sh` is a good hint it should work on Linux.

**Comment by spektom** [comment]
There's no reason for it to not work in Linux. However, building it in Linux doesn't go smooth., I've fixed the originally reported error (inability to find debug libraries: LZMAD and SNAPPYD), but then another issue pops up when linking with Snappy:

```
/home/michael/Dev/projects/vcpkg/installed/x64-linux/debug/lib/libsnappyd.a(snappy.cc.o): In function `snappy::internal::WorkingMemory::WorkingMemory(unsigned long)':
/home/michael/Dev/projects/vcpkg/buildtrees/snappy/src/9717df7902-acae3bca74/snappy.cc:464: undefined reference to `std::allocator<char>::allocator()'
/home/michael/Dev/projects/vcpkg/buildtrees/snappy/src/9717df7902-acae3bca74/snappy.cc:464: undefined reference to `std::allocator<char>::~allocator()'
...
```

Looks like it tries to link against C++ lib.
I try to dig it further.

**Comment by kreuzerkrieg** [comment]
BTW, it happens without any reference to `vcpkg`, if you just checkout avro and snappy, build them and link avro with your build results it will fail with the same error. It doesnt happen with `apt` provided snappy. I've already asked on avro jira about such a behavior, maybe they can provide some useful info

**Comment by spektom** [comment]
@kreuzerkrieg can you test PR #10514 please?

**Comment by kreuzerkrieg** [comment]
Looks like it worked!
Building package avro-c[core]:x64-linux...
-- Downloading https://github.com/apache/avro/archive/release-1.9.2.tar.gz...
-- Extracting source /home/ernest/Development/spektom/vcpkg/downloads/apache-avro-release-1.9.2.tar.gz
-- Applying patch avro.patch
-- Applying patch snappy-pr-793.patch
-- Using source at /home/ernest/Development/spektom/vcpkg/buildtrees/avro-c/src/ease-1.9.2-eb8e8ac105
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Installing: /home/ernest/Development/spektom/vcpkg/packages/avro-c_x64-linux/share/avro-c/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package avro-c[core]:x64-linux... done
Installing package avro-c[core]:x64-linux...
Installing package avro-c[core]:x64-linux... done
Elapsed time for package avro-c:x64-linux: 10.02 s

**Comment by LilyWangL** [comment]
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.
