### ISSUE TITLE
Is it possible to disable the post build script

### ISSUE THREAD

**Issue by jabra98** [microsoft/vcpkg#10334]
Hello, is there a way to disable the post build script on windows?
That is the execution of the vcpkg/scripts/buildsystems/msbuild/applocal.ps1

**Comment by LilyWangL** [comment]
@jabra98 Thanks for posting this issue. Do you mean you want to disable the script applocal.ps1?

**Comment by jabra98** [comment]
Yes. For now I've just commented everything out and it works for the time being

**Comment by LilyWangL** [comment]
You can use `set(VCPKG_POLICY_EMPTY_PACKAGE enabled)` to disable the post-build check. See more information from: https://github.com/microsoft/vcpkg/issues/7109#issuecomment-508233035

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
