### ISSUE TITLE
How do I specify the include files location in portfile.cmake?

### ISSUE THREAD

**Issue by aholzinger** [microsoft/vcpkg#10332]
I'm trying to write a portfile for a library, let's call it _the_library_ which is built with cmake. The include hierarchy for using this  library is:
>a
>b
>the_library
>c
>d

With the standard _portfile.cmake_ approach the _${VCPKG_ROOT_DIR}/installed/${TARGET_TRIPLET}/include_ directory after installation looks like this (listing only the new directories, not those of already previously installed libraries):
>a
>b
>the_library
>c
>d

This is not nice, especially because there can be name conflicts with other installed libraries (actually one of the subdirectories is named _boost_ which conflicts with the boost library). All the headers should go to _${VCPKG_ROOT_DIR}/installed/${TARGET_TRIPLET}/include/the_library_ which itself should then look like this:
>a
>b
>the_library
>c
>d

A user would then have to `#include <the_library/the_library/header.h>` (or if needed also `#include <the_library/a/header.h>`.

Does anybody know how can I acheive this in a way that using the library with cmake will find the library and report the right include directory?

**Comment by JackBoosY** [comment]
In general, all header files need to be archived in _include_. In order to resolve the conflict with the header files of other ports, we want to install the directory as _include/$<port>_, and create sub-folders according to the directory structure in source.

**Comment by aholzinger** [comment]
That's exactly the reason I'm asking. If a library project (not yet supported by vcpkg) with its CMakeLists.txt doesn't respect this, how can I fix it in portfile.cmake?

**Comment by garethsb-sony** [comment]
> A user would then have to `#include <the_library/the_library/header.h>` (or if needed also `#include <the_library/a/header.h>`.
Or the user could add `include/the_library` to their include path as well as `include` and then write `#include <the_library/header.h>` and `#include <a/header.h>`?

**Comment by aholzinger** [comment]
Yes, that's how I do it now, i.e. in a non CMake Visual Studio project I just set the vcpkg/include directory plus the vcpkg/include/nmos-cpp directory as additional include paths and the same for the lib directories. Then one can use nmos-cpp as if the project would be part of the nmos-cpp project.

With nmos-cpp and the vcpkg files from "my" nmos-cpp fork the outer CmakeLists.txt "adds" the nmos-cpp include directory and below then there is nmos, bst, detail, etc.

I looked for a way to do this without the need to change the nmos-cpp project. With the generic changes in the .cmake files it's working.

Still it would be interesting if vcpkg could do something similar.

**Comment by garethsb-sony** [comment]
**nmos-cpp** project is effectively a package of several smaller co-developed libraries or modules like `nmos`, `mdns` and so on (plus some extensions to existing libs like **boost** and **cpprestsdk**). Adding an extra project directory might solve very basic filename conflicts with other 'ports', but any such conflict is likely to indicate greater conflicts in C++ symbol names, which simple file-system reorganisation cannot hope to solve.

**Comment by aholzinger** [comment]
I see two issues here:

- nmos-cpp doesn't export only one include directory, but more than one
- some of the sub-include directories use names of other common libraries like boost or cpprestsdk

I don't see conflicts in C++ symbol names, because if they would be existing, these errors would already pop-up when building nmos-cpp in the classical way, because boost, cpprestsdk and so on are all already there, regardless where the include files reside.

IMHO the only real issue (for adding it to a system like vcpkg) is that nmos-cpp is "exporting" more than one include directory. One vcpkg library should either export one include file ore one include directory.

I think for the time being the chosen approach with the outer CMakeLists.txt is right for working with nmos-cpp (as a vcpkg library) and make some experience. We will soon find out if there will problems like C++ symbol name clashes will pop up.

If not, we can again rethink the directory setup and afterwards try to get nmos-cpp upstream to be an official/supported vcpkg library, can't we?

**Comment by JackBoosY** [comment]
You need to confirm if the port uses dependent ports in vcpkg. I think that if the port's built-in dependencies are used, their header files will be exported.
You can also delete duplicate header files in `portfile.cmake`, such as:
```
file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/include/boost)
```

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
