### ISSUE TITLE
bash: .vcpkg: command not found Trying to install Vcpkg for Vs code 

### ISSUE THREAD

**Issue by Garvit13** [microsoft/vcpkg#10341]
So, when I tried to install the Vcpkg for VS code I downloaded the repo and opened the bootstrap-vcpkg.bat a cmd window gets opened and it's just like a new window and gets closed in a sec. Then when I type the command vcpkg in Bash, I get the error... 

bash: .vcpkg: command not found...in bash

 and...

.\vcpkg: The term '.\vcpkg' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ .\vcpkg integrate install
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\vcpkg:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException....in po.\vcpkg : The term '.\vcpkg' is not recognized as the name of a cmdlet, function, script file, or operable program.

in PowerShell. OS win--10-->1803

**Comment by timautry** [comment]
@Garvit13 
- I assume you are using a Linux distro as you mention **bash**
- cd to the _vcpkg-root_ folder/directory where git put the vcpkg source and components
- at the command line run **./bootstrap-vcpkg.sh** to compile and link _vcpkg_ 
- then **./vcpkg integrate install** to integrate vcpkg into the linux development environment
- and then **./vcpkg integrate bash** to add vcpkg shell commands

_.\bootstrap-vcpkg.bat_ is for a windows installation.

**Comment by NancyLi1013** [comment]
Hi @Garvit13 

Thanks for posting this issue.
Please help confirm if you do as the following steps on Windows platform:
```
> git clone https://github.com/Microsoft/vcpkg.git
> cd vcpkg
> .\bootstrap-vcpkg.bat
> .\vcpkg integrate install
```
Only when running `.\bootstrap-vcpkg.bat` successfully, then execuate ` ./vcpkg xxx `.

@timautry Thanks for your above info for this issue.

**Comment by NancyLi1013** [comment]
Since VS code has been mentioned in #10217, let's track this there.

**Comment by marfrede** [comment]
`./vcpkg.exe _command_` worked for me.
e.g. `./vcpkg.exe integrate install`
