### ISSUE TITLE
[New Port Request] <11Zip>

### ISSUE THREAD

**Issue by Flame12220** [microsoft/vcpkg#10347]
Library name: 11Zip

Library description: It is a zip library for C++

Source repository URL: https://github.com/Sygmei/11Zip

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
