### ISSUE TITLE
[embree3 ] ISPC, AVX512SKX

### ISSUE THREAD

**Issue by Voskrese** [microsoft/vcpkg#10353]
add feature

```
    OPTIONS
        -DEMBREE_ISPC_SUPPORT=ON
        -DEMBREE_ISA_AVX512SKX=ON or -DEMBREE_MAX_ISA=AVX512SKX
```

**[tools]** ispc - src [ [https://github.com/ispc/ispc](https://github.com/ispc/ispc) ] prebuilt [ [https://sourceforge.net/projects/ispcmirror/files/v1.12.0/](https://sourceforge.net/projects/ispcmirror/files/v1.12.0/) ]

:((

```
    IF (EMBREE_ISA_AVX512KNL OR EMBREE_ISA_AVX512SKX)
      MESSAGE(FATAL_ERROR "Microsoft Visual C++ Compiler does not support AVX512. Please use Intel Compiler or Clang.")
    ENDIF()
```

**Comment by Voskrese** [comment]
`-DEMBREE_ISA_AVX512SKX=ON
`
**default this option is turned OFF.**

> EMBREE_MAX_ISA: Select highest supported ISA (SSE2, SSE4.2, AVX, AVX2, AVX512KNL, AVX512SKX, or NONE). When set to NONE the EMBREE_ISA_* variables can be used to enable ISAs individually. By default the option is set to AVX2.
> 
> EMBREE_ISA_SSE2: Enables SSE2 when EMBREE_MAX_ISA is set to NONE. By default this option is turned OFF.
> 
> EMBREE_ISA_SSE42: Enables SSE4.2 when EMBREE_MAX_ISA is set to NONE. By default this option is turned OFF.
> 
> EMBREE_ISA_AVX: Enables AVX when EMBREE_MAX_ISA is set to NONE. By default this option is turned OFF.
> 
> EMBREE_ISA_AVX2: Enables AVX2 when EMBREE_MAX_ISA is set to NONE. By default this option is turned OFF.
> 
> EMBREE_ISA_AVX512KNL: Enables AVX-512 for Xeon Phi when EMBREE_MAX_ISA is set to NONE. By default this option is turned OFF.
> 
> EMBREE_ISA_AVX512SKX: Enables AVX-512 for Skylake when EMBREE_MAX_ISA is set to NONE. By default this option is turned OFF.

**Comment by dbabokin** [comment]
ISPC downloads moved to Github Releases: https://github.com/ispc/ispc/releases
