### ISSUE TITLE
[tensorflow] build failure

### ISSUE THREAD

**Issue by RageLog** [microsoft/vcpkg#10356]
- OS:windows
- Compiler: x64-x86
Error: Building package tensorflow-cc:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: tensorflow-cc:x64-windows-static 
  Vcpkg version: 2019.09.12-nohash

all tensorflow pkg gave to me same error.

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/7995, also has Upstream issue https://github.com/tensorflow/tensorflow/issues/32228 to track.
