### ISSUE TITLE
intelrealsense2 build failure

### ISSUE THREAD

**Issue by blakat360** [microsoft/vcpkg#10359]
**Host Environment**
- OS: windows
- Compiler: visual studio 16 2019
-vcpkg version: 2020.02.04-nohash

**To Reproduce**
`./vcpkg install realsense2`
also tried
`./vcpkg install realsense2:x64-windows`
and
`./vcpkg install realsense2:x64-windows-static`

**Failure logs** 
all the logs look very similar to this

Error: Building package realsense2:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: realsense2:x64-windows-static
  Vcpkg version: 2020.02.04-nohash

**Additional context**
I have ran both ./vcpkg update and .\vcpkg update. It says I'm up to date. I also ran git pull and that is also up to date. Any help would be much appreciated.

**Comment by LilyWangL** [comment]
@blakat360 Thanks for posting this issue. Please attach the install log file: _[VCPKG_path]/buildtrees/realsense2/install-x86-windows-dbg-out.log_

**Comment by LilyWangL** [comment]
Ping @blakat360

**Comment by blakat360** [comment]
by the time you asked for the log file, I had already switched to linux and installed it using apt. I no longer have access to the old file system
