### ISSUE TITLE
 itk:x86-windows build failure

### ISSUE THREAD

**Issue by brunok2017** [microsoft/vcpkg#10360]
**Host Environment**
- OS: [Windows 10]
- Compiler: vs2017

**To Reproduce**
`./vcpkg install itk:x86-windows'

**Failure logs** 
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: D:/vcpkg/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v
    Working Directory: D:/vcpkg/vcpkg/buildtrees/itk/x86-windows-dbg
    See logs for more information:
      D:\vcpkg\vcpkg\buildtrees\itk\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/itk/portfile.cmake:67 (vcpkg_install_cmake)
  scripts/ports.cmake:90 (include)

**Comment by NancyLi1013** [comment]
Duplicated to #9891. Let's track this issue here.
