### ISSUE TITLE
[New Port Request] ospray

### ISSUE THREAD

**Issue by Voskrese** [microsoft/vcpkg#10363]
Library name: ospray

Library description: An Open, Scalable, Portable, Ray Tracing Based Rendering Engine for High-Fidelity Visualization

Source repository URL: https://github.com/ospray/ospray

Project homepage (if different from the source repository): http://ospray.org/

**deps**
[embree (ispc)](https://github.com/microsoft/vcpkg/issues/10353), tbb, glfw3, [openvkl](https://github.com/microsoft/vcpkg/issues/10352), [ospcommon](https://github.com/ospray/ospcommon), [ispc[tools]](https://sourceforge.net/projects/ispcmirror/files)

-DOSPRAY_APPS_EXAMPLES=OFF
-DOSPRAY_APPS_TESTING=OFF
-DOSPRAY_BUILD_ISA=AVX2

embree3 MSVC not support AVX512 
>     IF (EMBREE_ISA_AVX512KNL OR EMBREE_ISA_AVX512SKX)
>       MESSAGE(FATAL_ERROR "Microsoft Visual C++ Compiler does not support AVX512. Please use Intel Compiler or Clang.")
>     ENDIF()

> OSPRAY_BUILD_ISA to the highest level your CPU supports (AVX2 for Haswell or later). If you are compiling for KNL, either use ALL or AVX512

```
-DOSPRAY_BUILD_MIC_SUPPORT to OFF if you are on a Xeon CPU
-DOSPRAY_USE_EXTERNAL_EMBREE to OFF
```

```
-DOSPRAY_ENABLE_APPS=OFF
-DOSPRAY_MODULE_BILINEAR_PATCH=OFF
```

`-DOSPRAY_BUILD_MPI_DEVICE to ON` - [MPI_DEVICE](https://github.com/ospray/module_mpi)

`-DOSPRAY_MODULE_DENOISER to ON` - [oidn](https://github.com/OpenImageDenoise/oidn)

**[tools]** ispc - src [ [https://github.com/ispc/ispc](url) ] prebuilt [ [https://sourceforge.net/projects/ispcmirror/files/v1.12.0/](https://sourceforge.net/projects/ispcmirror/files) ]

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by Voskrese** [comment]
@LilyWangL 
![2020-05-25_141110](https://user-images.githubusercontent.com/10104740/82783807-cfaeb000-9e91-11ea-8a74-6f88d7f44b12.png)

**2 months have passed, what is the request period?**

**Comment by LilyWangL** [comment]
If the latest update is a month ago, we will close this issue.
