### ISSUE TITLE
realsense2[openni2] build failure

### ISSUE THREAD

**Issue by FSund** [microsoft/vcpkg#10361]
**Host Environment**
- OS: Windows 10.0.18363
- Compiler: MSVC v142

**To Reproduce**
`./vcpkg install realsense2[openni2]`

I have `VCPKG_DEFAULT_TRIPLET = x64-windows`

**Failure logs** 
```
PS C:\vcpkg> vcpkg install realsense2[openni2]
Computing installation plan...
The following packages will be built and installed:
    realsense2[core,openni2]:x64-windows
Starting package 1/1: realsense2:x64-windows
Building package realsense2[core,openni2]:x64-windows...
-- Using cached C:/vcpkg/downloads/IntelRealSense-librealsense-9f99fa9a509555f85bffc15ce27531aaa6db6f7e.tar.gz
-- Using source at C:/vcpkg/buildtrees/realsense2/src/aaa6db6f7e-746a483df4
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
CMake Error at ports/realsense2/portfile.cmake:79 (file):
  file COPY cannot find
  "C:/vcpkg/buildtrees/realsense2/x64-windows-rel/_out/rs2driver*".
Call Stack (most recent call first):
  scripts/ports.cmake:90 (include)


Error: Building package realsense2:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: realsense2:x64-windows
  Vcpkg version: 2020.02.04-nohash
```

[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/4306960/install-x64-windows-dbg-out.log)
[install-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/4306961/install-x64-windows-rel-out.log)
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/4306966/config-x64-windows-out.log)

(most other logs are empty)

**Additional context**
I already had `openni` installed, so I was doing `vcpkg install realsense2[openni2] --recurse` the first time I got this error.

**Comment by PhoebeHui** [comment]
@FSund, thanks for reporting this issue!

I will summit a PR for fixing this issue.

**Comment by PhoebeHui** [comment]
@FSund, the PR has been merged, please get latest source and try again.

**Comment by FSund** [comment]
Nice, thanks!
