### ISSUE TITLE
vcpkg library files and Visual Studio 2017 compiler version

### ISSUE THREAD

**Issue by Nemoon** [microsoft/vcpkg#10362]
Hello! 

I have used `vcpkg` to compile `cppkafka` static library in Windows 10, and everything worked perfectly, I have the headers and the library files available.

On the other hand, I am using Visual Studio 2017 (version 15.9.20) to compile my project together with the `cppkafka` static library. I read in https://docs.microsoft.com/en-us/cpp/porting/binary-compat-2015-2017?view=vs-2019 that the toolset version for VS2017 is `v141` (in fact it doesn't let you compile if you are using `v140` toolset).

I am pretty sure I properly configured the project settings so that the compiler and linker were able to find all the dependencies:
- "Additional Include Directories" (`C:\...\vcpkg\installed\x64-windows-static\include`) 
- "Additional Library Directories" (`C:\...\vcpkg\installed\x64-windows-static\lib`)
- "Additional Dependencies" (pointing to each of the `.lib` files inside the `\lib` folder)

VS2017 was able to compile, but not to link, where I got many errors. After a while, I noticed the following: I saw in the `C:\...\vcpkg\installed\x64-windows-static\lib` path that the library filenames contained the string `-vc140-` in between. See picture attached:
![vc140](https://user-images.githubusercontent.com/25422200/76094348-c6185900-5fc2-11ea-8b5f-8742f591ff42.png)

Anyways, I found out that in the path `C:\...\vcpkg\buildtrees\boost-atomic\x64-windows-static-rel\stage\lib` (just an example file), you could find, let's say, the equivalent library file for `vc141`:
![vc141](https://user-images.githubusercontent.com/25422200/76097285-bcddbb00-5fc7-11ea-82c1-aad2b2505c31.png)

I am a bit confused with VS2017 compiler version and VS toolset version. Does it mean that if I am using VC++ 14.16, I cannot use the libraries shown in the first picture (vc140)? Why you can find two different versions of these library files in `vcpkg `folder?

Sorry for the long explanation but I thought like this it would be easier for you to understand my question. 

Thank you very much :)

**Comment by JackBoosY** [comment]
Yep, I can confirm that's a bug.

**Comment by PhoebeHui** [comment]
@Nemoon, thanks for reporting this issue, I will take a look.

**Comment by PhoebeHui** [comment]
@Nemoon, the lib renames to vc140, see the [background](https://github.com/microsoft/vcpkg/issues/601#issuecomment-276220946) why it renamed.

**Comment by PhoebeHui** [comment]
@Nemoon, does this still be a problem for you?

**Comment by Nemoon** [comment]
Hello! And sorry for the late response, I've been very busy these days...

I saw what you suggested me to read, and I did, but honestly, I needed to move to another part of my project so I left this issue apart for a while, didn't dedicate much time to fix it after your reply.
So don't worry for the moment, I will probably come back when really needed, and if this issue should be closed, you can do it (or it's me the only one that can close?), I can create it again if needed in the future...

Thanks a lot! :)

**Comment by JackBoosY** [comment]
@Nemoon Okay, please reopen this issue if it's stll bothering you.
