### ISSUE TITLE
7zip-cpp

### ISSUE THREAD

**Issue by jonndoe47pp** [microsoft/vcpkg#10371]
Library name:
7zip-cpp
Library description:
Wrapper for 7Zip library
Source repository URL:
https://github.com/keithjjones/7zip-cpp
Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
