### ISSUE TITLE
[libmysql] build failure

### ISSUE THREAD

**Issue by kreuzerkrieg** [microsoft/vcpkg#10370]
- OS: Ubuntu 18.04
- Compiler: GCC 9.2.1

`./vcpkg install libmysql`

> CMake Error at ports/libmysql/portfile.cmake:4 (message):
>   FATAL ERROR: libmysql and libmariadb are incompatible.

**Comment by JackBoosY** [comment]
It can be seen from the error message: there is a conflict between libmysql and libmariadb.
If you wish to install libmysql, please remove libmariadb and try again.

Thanks.

**Comment by kreuzerkrieg** [comment]
Oh... I got the message as there is a dependency between the two, so they both have to have some specific version.
So, there is no way to install both?

**Comment by Toxe** [comment]
No, not that I know of.
