### ISSUE TITLE
qt5:x64-windows failed

### ISSUE THREAD

**Issue by yaoyu** [Microsoft/vcpkg#1037]
PS D:\Develop\GitOthers\vcpkg> ./vcpkg install qt5
The following packages will be built and installed:
    qt5:x64-windows
Building package qt5:x64-windows...
-- CURRENT_INSTALLED_DIR=D:/Develop/GitOthers/vcpkg/installed/x64-windows
-- DOWNLOADS=D:/Develop/GitOthers/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=D:/Develop/GitOthers/vcpkg/packages/qt5_x64-windows
-- CURRENT_BUILDTREES_DIR=D:/Develop/GitOthers/vcpkg/buildtrees/qt5
-- CURRENT_PORT_DIR=D:/Develop/GitOthers/vcpkg/ports/qt5/.
-- Using cached D:/Develop/GitOthers/vcpkg/downloads/qt-5.8.0.7z
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting source D:/Develop/GitOthers/vcpkg/downloads/qt-5.8.0.7z
-- Extracting done
-- Applying patch D:/Develop/GitOthers/vcpkg/ports/qt5/fix-qalgorithms-vs2017.patch
-- Applying patch D:/Develop/GitOthers/vcpkg/ports/qt5/fix-qalgorithms-vs2017.patch done
-- Applying patch D:/Develop/GitOthers/vcpkg/ports/qt5/fix-commandline-overrides.patch
-- Applying patch D:/Develop/GitOthers/vcpkg/ports/qt5/fix-commandline-overrides.patch done
-- Configuring x64-windows-rel
-- Configuring x64-windows-rel done
-- Configuring x64-windows-dbg
-- Configuring x64-windows-dbg done
-- Package x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:14 (message):
    Command failed: D:/Develop/GitOthers/vcpkg/downloads/tools/jom/jom-1.1.2/jom.exe;/J;8
    Working Directory: D:/Develop/GitOthers/vcpkg/buildtrees/qt5/x64-windows-rel
    See logs for more information:
      D:\Develop\GitOthers\vcpkg\buildtrees\qt5\build-x64-windows-rel-out.log
      D:\Develop\GitOthers\vcpkg\buildtrees\qt5\build-x64-windows-rel-err.log

Call Stack (most recent call first):
  ports/qt5/install_qt.cmake:19 (vcpkg_execute_required_process)
  ports/qt5/portfile.cmake:54 (install_qt)
  scripts/ports.cmake:73 (include)

Error: Building package qt5:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: qt5:x64-windows
  Vcpkg version: 0.0.81-22848e4b7e29a3a74c28afafe4d177e541ec8638

Additionally, attach any relevant sections from the log files above.

**Comment by yaoyu** [comment]
build-x64-windows-rel-err.log

jom 1.1.2 - empower your cores

D:\Develop\GitOthers\vcpkg\buildtrees\qt5\src\qt-5.8.0\qtbase\src\corelib\kernel\qobjectdefs.h(0): Note: No relevant classes found. No output generated.
D:\Develop\GitOthers\vcpkg\buildtrees\qt5\src\qt-5.8.0\qtbase\src\network\access\qnetworkaccessdebugpipebackend_p.h(0): Note: No relevant classes found. No output generated.
jom: D:\Develop\GitOthers\vcpkg\buildtrees\qt5\x64-windows-rel\qtbase\src\plugins\generic\tuiotouch\Makefile.Release [.obj\release\qtuiohandler.obj] Error 2
jom: D:\Develop\GitOthers\vcpkg\buildtrees\qt5\x64-windows-rel\qtbase\src\plugins\generic\tuiotouch\Makefile [release] Error 2
jom: D:\Develop\GitOthers\vcpkg\buildtrees\qt5\x64-windows-rel\qtbase\src\plugins\generic\Makefile [sub-tuiotouch-make_first] Error 2
jom: D:\Develop\GitOthers\vcpkg\buildtrees\qt5\x64-windows-rel\qtbase\src\plugins\Makefile [sub-generic-make_first] Error 2
jom: D:\Develop\GitOthers\vcpkg\buildtrees\qt5\x64-windows-rel\qtbase\src\Makefile [sub-plugins-make_first] Error 2
jom: D:\Develop\GitOthers\vcpkg\buildtrees\qt5\x64-windows-rel\qtbase\Makefile [sub-src-make_first] Error 2
jom: D:\Develop\GitOthers\vcpkg\buildtrees\qt5\x64-windows-rel\Makefile [module-qtbase-make_first] Error 2

**Comment by ZeppLu** [comment]
I suggest you check `D:\Develop\GitOthers\vcpkg\buildtrees\qt5\build-x64-windows-rel-out.log` to see if it contains `error C2001`. If so, you may suffer the same issue as mine (#1092).

**Comment by yaoyu** [comment]
Thanks!

At 2017-05-15 00:33:13, "Zepp" <notifications@github.com> wrote:


I suggest you check D:\Develop\GitOthers\vcpkg\buildtrees\qt5\build-x64-windows-rel-out.log to see if it contains error C2001. If so, you may suffer the same issue as mine (#1092).
