### ISSUE TITLE
x86-linux-static vcpkg package for wxwidgets

### ISSUE THREAD

**Issue by smadurange** [microsoft/vcpkg#10376]
Library name: wxwidgets

Library description: Cross-platform GUI tool kit

Source repository URL: https://github.com/wxWidgets/wxWidgets

**Comment by NancyLi1013** [comment]
Hi @smadurange 
Thanks for posting this request.
`wxwidgests `has been added to vcpkg.
Could you please help confirm if[ this port](https://github.com/microsoft/vcpkg/tree/master/ports/wxwidgets) is the one you wanted?

**Comment by smadurange** [comment]
Thanks for the quick reply. I was looking for a 32-bit linux static lib port of wxwidgets. Currently available ports are:

```
vailable architecture triplets
VCPKG built-in triplets:
  arm-uwp
  x64-linux
  x86-windows
  x64-windows-static
  x64-osx
  x64-windows
  x64-uwp
  arm64-windows

VCPKG community triplets:
  x86-mingw
  arm64-uwp
  x86-windows-static-md
  x64-windows-static-md
  x86-windows-static
  arm-windows
  x86-uwp
  x64-mingw
  arm-mingw
  arm64-mingw
```

**Comment by NancyLi1013** [comment]
Since vcpkg currently only supports` x64-linux`(In fact, this triplet is built as static).
As for `x86-linux`, it is not available in vcpkg for all ports.
So this issue may be not a new port request. It might be a port feature or vcpkg feature.

**Comment by strega-nil** [comment]
We will accept PRs to add this triplet as a community triplet to vcpkg. Thanks for the issue!

https://github.com/microsoft/vcpkg/blob/master/docs/users/triplets.md

**Comment by smadurange** [comment]
Eventually, ended up using Qt instead of wxwidgets. But, I opened the PR below as I needed 32-bit cpprestsdk.

PR: https://github.com/microsoft/vcpkg/pull/10727

**Comment by Adela0814** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
