### ISSUE TITLE
[libcpuid and stormlib] build failure x64-windows /include is empty or not present

### ISSUE THREAD

**Issue by timautry** [microsoft/vcpkg#10383]
**Host Environment**
- OS: [Microsoft Windows Version 1909 (OS Build 18363.719)]
- Compiler: Visual Studio
   - VS 2017 v15.9.21 VS Tools Version 14.16.27023
   - VS 2019 v16.4.6   VS Tools Version 14.24.28314

**To Reproduce**
- Steps to reproduce the behavior:
`.\vcpkg install libcpuid[core] stormlib[core]`
Computing installation plan...
The following packages will be built and installed:
    libcpuid[core]:x64-windows
    stormlib[core]:x64-windows

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
Starting package 1/2: stormlib:x64-windows
Building package stormlib[core]:x64-windows...
-- Using cached E:/Git/vcpkg.downloads/ladislav-zezula-StormLib-2f0e0e69e6b3739d7c450ac3d38816aee45ac3c2.tar.gz
-- Using source at D:/Git/vs2017.prod/buildtrees/stormlib/src/aee45ac3c2-cf775d9e5a
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: D:/Git/vs2017.prod/packages/stormlib_x64-windows/share/stormlib/copyright
-- Performing post-build validation
**The folder /include is empty or not present. This indicates the library was not correctly installed.**
**Found 1 error(s). Please correct the portfile:**
    **D:\Git\vs2017.prod\ports\stormlib\portfile.cmake**
-- Performing post-build validation done
**Error: Building package stormlib:x64-windows failed with: POST_BUILD_CHECKS_FAILED**
Elapsed time for package stormlib:x64-windows: 3.491 min
Starting package 2/2: libcpuid:x64-windows
Building package libcpuid[core]:x64-windows...
-- Note: libcpuid only supports static library linkage. Building static library.
-- Using cached E:/Git/vcpkg.downloads/anrieff-libcpuid-f2ab8b7ef2c286f619d96c3ce8902cb76b801bf0.tar.gz
-- Using source at D:/Git/vs2017.prod/buildtrees/libcpuid/src/b76b801bf0-c750aa7385
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: D:/Git/vs2017.prod/packages/libcpuid_x64-windows/share/libcpuid/copyright
-- Performing post-build validation
**The folder /include is empty or not present. This indicates the library was not correctly installed.**
**Found 1 error(s). Please correct the portfile:**
    **D:\Git\vs2017.prod\ports\libcpuid\portfile.cmake**
-- Performing post-build validation done
**Error: Building package libcpuid:x64-windows failed with: POST_BUILD_CHECKS_FAILED**
Elapsed time for package libcpuid:x64-windows: 1.603 min

Total elapsed time: 5.094 min

RESULTS
    stormlib:x64-windows: POST_BUILD_CHECKS_FAILED: 3.491 min
    libcpuid:x64-windows: POST_BUILD_CHECKS_FAILED: 1.603 min

SUMMARY
    SUCCEEDED: 0
    BUILD_FAILED: 0
    POST_BUILD_CHECKS_FAILED: 2
    FILE_CONFLICTS: 0
    CASCADED_DUE_TO_MISSING_DEPENDENCIES: 0
    EXCLUDED: 0

- Please attach any additional failure logs mentioned in the console output.
  All other output is correct.

**Additional context**
  - It appears that post-build validation fails when there is not an /include folder to copy to packages folder.
  - Is there a way to disable the /include folder check in the post-build validation script?

**Comment by linquize** [comment]
@timautry Can you build with VS2019 again?

**Comment by timautry** [comment]
@linquize  - works fine on both x64-linux instances but fails on all x64-windows instances
cc: @NancyLi1013 

- vcpkg was up-to-date as of the time of this posting
- none of the commits to vcpkg today has not:
  - updated either port 
  - updated any of the vcpkg source files or scripts.

The _builds for both work fine_ until **Performing post-build validation** sequence on both ports
 - failure occurs when vcpkg is attempting to copy the contents of the /include folder to either:
   - the /packages/_port-name_-x64-windows 
   -  /installed/x64-windows/include folders.

Expanded both downloads from source:
-  anrieff-libcpuid-f2ab8b7ef2c286f619d96c3ce8902cb76b801bf0.tar.gz last commit 29 days ago
- ladislav-zezula-StormLib-2f0e0e69e6b3739d7c450ac3d38816aee45ac3c2.tar.gz last commit Nov 2, 2019

These 2 ports have no /include folder any where within the source folder tree - just the h/hpp and cpp files co-mingled in the same folders of each sub folder.

_vcpkg-root_\toolsrc\src\vcpkg\postbuildlint.cpp lines 80 - 99 check for that folder /include - if does not exists or is empty it throws an error exception, if the **EMPTY_INCLUDE_FOLDER** policy is enabled. 

Maybe there is a way to disable this policy in the portfile.cmake, not sure though...


    static LintStatus check_for_files_in_include_directory(const Files::Filesystem& fs,
                                                           const Build::BuildPolicies& policies,
                                                           const fs::path& package_dir)
    {
        if (policies.is_enabled(BuildPolicy::EMPTY_INCLUDE_FOLDER))
        {
            return LintStatus::SUCCESS;
        }

        const fs::path include_dir = package_dir / "include";
        if (!fs.exists(include_dir) || fs.is_empty(include_dir))
        {
            System::print2(System::Color::warning,
                           "The folder /include is empty or not present. This indicates the library was not correctly "
                           "installed.\n");
            return LintStatus::ERROR_DETECTED;
        }

        return LintStatus::SUCCESS;
    }

**Comment by timautry** [comment]
@linquize 
cc: @NancyLi1013 

Added to the end of each libcpuid and stormlib portfile.cmake:

**# Allow empty include directory**
**set(VCPKG_POLICY_EMPTY_INCLUDE_FOLDER enabled)**

They now build/install and **pass post-build validation**.

I guess changes need to be made to the portfile.cmake on each port (libcpuid and stormlib), to add this code, so it only affects windows, as linux builds fine without the code.

**Comment by PhoebeHui** [comment]
@timautry, I can't repro this issue with latest vcpkg source, could you get lastest source, also remove the stormlib and libcpuid soource under buildtrees, and try to build them again?

PS E:\vcpkg\clean\vcpkg> ./vcpkg install stormlib[core]:x64-windows
Computing installation plan...
The following packages will be built and installed:
    stormlib[core]:x64-windows
Starting package 1/1: stormlib:x64-windows
Building package stormlib[core]:x64-windows...
-- Using cached E:/VCPKG/clean/vcpkg/downloads/ladislav-zezula-StormLib-2f0e0e69e6b3739d7c450ac3d38816aee45ac3c2.tar.gz
-- Using source at E:/VCPKG/clean/vcpkg/buildtrees/stormlib/src/aee45ac3c2-cf775d9e5a
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: E:/VCPKG/clean/vcpkg/packages/stormlib_x64-windows/share/stormlib/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package stormlib[core]:x64-windows... done
Installing package stormlib[core]:x64-windows...
Installing package stormlib[core]:x64-windows... done
Elapsed time for package stormlib:x64-windows: 42.79 s

Total elapsed time: 42.79 s
The package stormlib:x64-windows provides CMake targets:
    find_package(stormlib CONFIG REQUIRED)
    target_link_libraries(main PRIVATE stormlib::stormlib)

PS E:\vcpkg\clean\vcpkg> ./vcpkg install libcpuid[core]:x64-windows
Computing installation plan...
The following packages will be built and installed:
    libcpuid[core]:x64-windows
Starting package 1/1: libcpuid:x64-windows
Building package libcpuid[core]:x64-windows...
-- Note: libcpuid only supports static library linkage. Building static library.
-- Downloading https://github.com/anrieff/libcpuid/archive/f2ab8b7ef2c286f619d96c3ce8902cb76b801bf0.tar.gz...
-- Extracting source E:/VCPKG/clean/vcpkg/downloads/anrieff-libcpuid-f2ab8b7ef2c286f619d96c3ce8902cb76b801bf0.tar.gz
-- Using source at E:/VCPKG/clean/vcpkg/buildtrees/libcpuid/src/b76b801bf0-c750aa7385
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: E:/VCPKG/clean/vcpkg/packages/libcpuid_x64-windows/share/libcpuid/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package libcpuid[core]:x64-windows... done
Installing package libcpuid[core]:x64-windows...
Installing package libcpuid[core]:x64-windows... done
Elapsed time for package libcpuid:x64-windows: 20.51 s

Total elapsed time: 20.51 s
The package libcpuid:x64-windows provides CMake targets:
    find_package(cpuid CONFIG REQUIRED)
    target_link_libraries(main PRIVATE cpuid::cpuid)
