### ISSUE TITLE
 [angle:x64-linux] build failure

### ISSUE THREAD

**Issue by hailIulius** [microsoft/vcpkg#10381]
**Host Environment**
- OS: [e.g. Windows/Linux etc...]
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic
- Compiler: revision
gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)

**To Reproduce**
vcpkg install --triplet x64-linux xerces-c xalan-c cli11 catch2 qt5-base

  The following packages will be built and installed:

    * angle[core]:x64-linux
    * bzip2[core]:x64-linux
      catch2[core]:x64-linux
      cli11[core]:x64-linux
    * dirent[core]:x64-linux
    * double-conversion[core]:x64-linux
    * egl-registry[core]:x64-linux
    * expat[core]:x64-linux
    * fontconfig[core]:x64-linux
    * freetype[bzip2,core,png]:x64-linux
    * harfbuzz[core,ucdn]:x64-linux
    * icu[core]:x64-linux
    * libiconv[core]:x64-linux
    * libjpeg-turbo[core]:x64-linux
    * libpng[core]:x64-linux
    * libpq[core,openssl,zlib]:x64-linux
    * openssl[core]:x64-linux
    * openssl-unix[core]:x64-linux
    * pcre2[core]:x64-linux
      qt5-base[core]:x64-linux
    * ragel[core]:x64-linux
    * sqlite3[core]:x64-linux
      xalan-c[core]:x64-linux
      xerces-c[core]:x64-linux
    * zlib[core]:x64-linux

**Failure logs** 

      Command failed: /home/iulian/.local/share/pmm/1.4.1/vcpkg-2020.01/downloads/tools/cmake-3.14.0-linux/cmake-3.14.0-Linux-x86_64/bin/cmake --build . --config Debug --target install -- -v
      Working Directory: /home/iulian/.local/share/pmm/1.4.1/vcpkg-2020.01/buildtrees/angle/x64-linux-dbg
      See logs for more information:
        /home/iulian/.local/share/pmm/1.4.1/vcpkg-2020.01/buildtrees/angle/install-x64-linux-dbg-out.log

  Call Stack (most recent call first):

    scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
    scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
    ports/angle/portfile.cmake:40 (vcpkg_install_cmake)
    scripts/ports.cmake:94 (include)

  Error: Building package angle:x64-linux failed with: BUILD_FAILED

  Please ensure you're using the latest portfiles with `.\vcpkg update`, then

  submit an issue at https://github.com/Microsoft/vcpkg/issues including:

    Package: angle:x64-linux
    Vcpkg version: 2020.01.17-unknownhash

  Additionally, attach any relevant sections from the log files above.

Call Stack (most recent call first):
  build/_pmm/1.4.1/main.cmake:36 (_pmm_vcpkg)
  build/_pmm/1.4.1/main.cmake:50 (_pmm_project_fn)
  CMakeLists.txt:107 (pmm)

**Additional context**
The error occur on compiling angle package 
```
In file included from /home/iulian/.local/share/pmm/1.4.1/vcpkg-2020.01/buildtrees/angle/src/3d929a7f0e-ac85ee4a0e/include/EGL/egl.h:39:0,
                 from /home/iulian/.local/share/pmm/1.4.1/vcpkg-2020.01/buildtrees/angle/src/3d929a7f0e-ac85ee4a0e/src/common/PackedEGLEnums_autogen.h:15,
                 from /home/iulian/.local/share/pmm/1.4.1/vcpkg-2020.01/buildtrees/angle/src/3d929a7f0e-ac85ee4a0e/src/common/PackedEnums.h:12,
                 from /home/iulian/.local/share/pmm/1.4.1/vcpkg-2020.01/buildtrees/angle/src/3d929a7f0e-ac85ee4a0e/src/libANGLE/Context.h:18,
                 from /home/iulian/.local/share/pmm/1.4.1/vcpkg-2020.01/buildtrees/angle/src/3d929a7f0e-ac85ee4a0e/src/libGLESv2/entry_points_gles_3_1_autogen.cpp:13:
/home/iulian/.local/share/pmm/1.4.1/vcpkg-2020.01/buildtrees/angle/src/3d929a7f0e-ac85ee4a0e/include/EGL/eglplatform.h:128:10: fatal error: X11/Xlib.h: No such file or directory
```

**Comment by linquize** [comment]
Did you `apt-get install libx11-dev` before building angle?

**Comment by JackBoosY** [comment]
It looks like we should add a warning message to angle's portfile.cmake.

**Comment by linquize** [comment]
For angle, please `apt-get install -y libx11-dev mesa-common-dev libxi-dev libxext-dev`

**Comment by linquize** [comment]
For angle: `apt-get install -y libx11-dev mesa-common-dev libxi-dev libxext-dev`
For icu: `apt-get install -y make`
For libpq: `apt-get install -y bison flex`
For qt5-base: `apt-get install -y libgl1-mesa-dev libglu1-mesa-dev`

**Comment by NancyLi1013** [comment]
@hailIulius 

Could you please help confirm if this can be solved by installing `libx11-dev`?

**Comment by linquize** [comment]
not just `libx11-dev` but also `mesa-common-dev`, `libxi-dev`, `libxext-dev`

**Comment by NancyLi1013** [comment]
@hailIulius 
I have added the related warning message. Please try to update vcpkg and build it again.
@linquize 
Thanks for your above suggestions about this issue.
