### ISSUE TITLE
[glib] Build using Meson

### ISSUE THREAD

**Issue by smcv** [microsoft/vcpkg#10389]
**Is your feature request related to a problem? Please describe.**
* The vcpkg GLib port is stuck at a version that is no longer supported, and in particular does not receive security fixes.
* The GLib maintainers are frustrated when downstream distributions use a rewrite of GLib's own build system, which is likely to have bugs that GLib's own build system does not, or incompatibilities with GLib's own build system.

**Proposed solution**
Build GLib with Meson, similar to the fribidi port.

This was not possible in the past, because GLib's native build system used to be GNU Autotools, which only works on Unixish platforms; but since version 2.58, GLib's native build system is Meson, which is portable to Windows.

**Comment by Voskrese** [comment]
@Neumann-A 
maybe you can redo the ports GNOME?

`+ `need to redo the port `gettext`

https://github.com/wingtk/gvsbuild/blob/dbb0997461d59de0c4a3af3f178e4d401c800990/gvsbuild/projects.py#L429

```
            archive_url = 'http://ftp.gnu.org/pub/gnu/gettext/gettext-0.19.7.tar.gz',
            hash = '5386d2a40500295783c6a52121adcf42a25519e2d23675950619c9e69558c23f',
            dependencies = ['win-iconv'],
            patches = ['0001-gettext-runtime-Add-pre-configured-headers-for-MSVC-.patch',
                       '0001-gettext-tools-Add-pre-configured-headers-and-sources.patch',
                       '0001-gettext-tools-gnulib-lib-libxml-Check-for-_WIN32-as-.patch',
                       '0001-gettext-tools-Make-private-headers-C-friendly.patch',
                       '0001-gettext-tools-src-x-lua.c-Fix-C99ism.patch',
                       '0002-gettext-tools-gnulib-lib-Declare-items-at-top-of-blo.patch',
                       '0004-gettext-runtime-intl-plural-exp.h-Match-up-declarati.patch',
                       '0005-gettext-runtime-intl-printf-parse.c-Fix-build-on-Vis.patch',
                       '0006-gettext-intrinsics.patch'],
            )
```

**Comment by vlj** [comment]
Here :
https://github.com/microsoft/vcpkg/pull/11477

But it's stuck because of cross compilation.
