### ISSUE TITLE
[python3:x86-windows-static] build failure

### ISSUE THREAD

**Issue by yavin87** [microsoft/vcpkg#10387]
**Host Environment**
- OS: Windows 10
- Compiler: revision

**To Reproduce**
`.\vcpkg.exe install boost:x86-windows-static`

**Failure logs** 
Powershell output:
> Starting package 46/57: python3:x86-windows-static
> Building package python3[core]:x86-windows-static...
> -- Using community triplet x86-windows-static. This triplet configuration is not guaranteed to succeed.
> -- [COMMUNITY] Loading triplet configuration from: ***\Documents\GIT\vcpkg\triplets\community\x86-windows-static.cmake
> -- Downloading https://github.com/python/cpython/archive/v3.7.3.tar.gz...
> -- Extracting source ***/Documents/GIT/vcpkg/downloads/python-cpython-v3.7.3.tar.gz
> -- Using source at ***/Documents/GIT/vcpkg/buildtrees/python3/src/v3.7.3-1161ad7a91
> -- Building ***/Documents/GIT/vcpkg/buildtrees/python3/src/v3.7.3-1161ad7a91-Lib-Win/PCBuild/pythoncore.vcxproj for Release
> CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
>     Command failed: msbuild ***/Documents/GIT/vcpkg/buildtrees/python3/src/v3.7.3-1161ad7a91-Lib-Win/PCBuild/pythoncore.vcxproj /p:Configuration=Release /t:Rebuild /p:Platform=Win32 /p:PlatformToolset=v142 /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /p:WindowsTargetPlatformVersion=10.0.18362.0 /m /p:WholeProgramOptimization=false
>     Working Directory: ***/Documents/GIT/vcpkg/buildtrees/python3/x86-windows-static-rel
>     Error code: 1
>     See logs for more information:
>       ***\Documents\GIT\vcpkg\buildtrees\python3\build-x86-windows-static-rel-out.log
> 
> Call Stack (most recent call first):
>   scripts/cmake/vcpkg_build_msbuild.cmake:119 (vcpkg_execute_required_process)
>   ports/python3/portfile.cmake:46 (vcpkg_build_msbuild)
>   scripts/ports.cmake:90 (include)
> 
> 
> Error: Building package python3:x86-windows-static failed with: BUILD_FAILED
> Please ensure you're using the latest portfiles with `.\vcpkg update`, then
> submit an issue at https://github.com/Microsoft/vcpkg/issues including:
>   Package: python3:x86-windows-static
>   Vcpkg version: 2020.02.04-nohash-external
> 
> Additionally, attach any relevant sections from the log files above.

[build-x86-windows-static-rel-out.log](https://github.com/microsoft/vcpkg/files/4318622/build-x86-windows-static-rel-out.log)

**Additional context**
Tried updating
> PS> ***\Documents\GIT\vcpkg> .\vcpkg.exe update
> Using local portfile versions. To update the local portfiles, use `git pull`.
> No packages need updating.

**Comment by linquize** [comment]
Why doesn't python3 depends on pthreads on Windows?

**Comment by JackBoosY** [comment]
`pthreads` also support Windows, and it will generate `pthreadVC3.lib` / `pthreadVCE3.lib` / `pthreadVSE3.lib`. You can have a try using command `.\vcpkg install pthreads`.

And I can successfully install `python3:x86-windows-static` on my machine.
So I suggest you remove pthreads first, then try to rebuild `python3:x86-windows-static`.

Thanks.

**Comment by JackBoosY** [comment]
Hi @linquize, does this issue have any progress?

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
