### ISSUE TITLE
 Error: Building package libepoxy:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by hub-wll** [microsoft/vcpkg#10382]
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libepoxy:x64-windows
  Vcpkg version: 2020.02.04-nohash

how to deal with this problem?

**Comment by linquize** [comment]
After `git pull` the latest vcpkg repository, run `bootstrap-vcpkg.bat` again to build vcpkg.
Then `vcpkg install libepoxy:x64-windows`

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Please provide the error log.

**Comment by hub-wll** [comment]
Thanks for your answer, I have soled this problem by conducting the installation process again.

**Comment by LilyWangL** [comment]
Thanks for posting this issue. This issue has been fixed, so I am closing this issue for now.

**Comment by gvanem** [comment]
Not so fast. During my `vcpkg install gtk:x86-windows`, I too get an error for ` libepoxy:x86-windows`.

These are the errors:
```
Building package libepoxy[core]:x86-windows...
-- Using cached F:/gv/VC_project/VCPKG/downloads/anholt-libepoxy-1.5.3.tar.gz
-- Using source at F:/gv/VC_project/VCPKG/buildtrees/libepoxy/src/1.5.3-d7b9d32fcb
-- Configuring x86-windows-rel
-- Configuring x86-windows-rel done
-- Configuring x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: F:/gv/VC_project/VCPKG/downloads/tools/python/python-3.7.3-x86/python.exe F:/gv/VC_project/VCPKG/dow
nloads/tools/meson/meson-0.53.2/meson.py -Denable-glx=no -Denable-egl=no -Dcmake_prefix_path=F:/gv/VC_project/VCPKG/inst
alled/x86-windows --buildtype plain --backend ninja --wrap-mode nodownload --default-library shared --prefix F:/gv/VC_pr
oject/VCPKG/packages/libepoxy_x86-windows/debug --includedir ../include F:/gv/VC_project/VCPKG/buildtrees/libepoxy/src/1
.5.3-d7b9d32fcb
    Working Directory: F:/gv/VC_project/VCPKG/buildtrees/libepoxy/x86-windows-dbg
    Error code: 1
    See logs for more information:
      F:\gv\VC_project\VCPKG\buildtrees\libepoxy\config-x86-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_meson.cmake:112 (vcpkg_execute_required_process)
  ports/libepoxy/portfile.cmake:14 (vcpkg_configure_meson)
  scripts/ports.cmake:90 (include)

Error: Building package libepoxy:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libepoxy:x86-windows
  Vcpkg version: 2020.02.04-unknownhash-debug
```

The `buildtrees\libepoxy\config-x86-windows-dbg-out.log` contains this:
```
meson.build:1:0: ERROR: Executables created by c compiler cl are not runnable.
```
Oh, really!?

My `vcpkg` was pulled and built from todays `master`.

**Comment by LilyWangL** [comment]
@gvanem Could you provide the all log: `buildtrees\libepoxy\config-x86-windows-dbg-out.log`? You can attach the log file to here.

**Comment by gvanem** [comment]
@LilyWangL It contain this:
```
The Meson build system
Version: 0.53.2
Source dir: F:\gv\VC_project\VCPKG\buildtrees\libepoxy\src\1.5.3-d7b9d32fcb
Build dir: F:\gv\VC_project\VCPKG\buildtrees\libepoxy\x86-windows-dbg
Build type: native build
WARNING: Unknown options: "enable-egl, enable-glx"
Project name: libepoxy
Project version: 1.5.3
Appending CFLAGS from environment: ' /DWIN32 /D_WINDOWS /W3 /utf-8  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1'
Appending LDFLAGS from environment: ['/DEBUG']
Appending CPPFLAGS from environment: ' '

meson.build:1:0: ERROR: Executables created by c compiler cl are not runnable.

A full log can be found at F:\gv\VC_project\VCPKG\buildtrees\libepoxy\x86-windows-dbg\meson-logs\meson-log.txt
```
And the [meson-log.txt](https://github.com/microsoft/vcpkg/files/4353372/meson-log.txt).

**Comment by codemonkeyq** [comment]
I find a error from package-x64-windows-rel-out.log
--------------------------------- errors ----------------------------------------
../src/1.5.3-d7b9d32fcb/src/dispatch_common.c: error C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
--------------------------------- errors -----------------------------------------

I'm delete dispatch_common.c All Comments  // and /* */
it working , you try
