### ISSUE TITLE
[cppgraphqlgen] build failure x64-windows with VS 2017

### ISSUE THREAD

**Issue by timautry** [microsoft/vcpkg#10393]
**Host Environment**
- OS: [Microsoft Windows Version 1909 (OS Build 18363.719)]
- Compiler: VS 2017 v15.9.21 VS Tools Version 14.16.27023

**To Reproduce**
`.\vcpkg install cppgraphqlgen`

**Failure logs** 
- Cut and past the appropriate build messages from the console output.
Computing installation plan...
The following packages will be built and installed:
    cppgraphqlgen[core]:x64-windows
Starting package 1/1: cppgraphqlgen:x64-windows
Building package cppgraphqlgen[core]:x64-windows...
-- Using cached E:/Git/vcpkg.downloads/microsoft-cppgraphqlgen-v3.1.1.tar.gz
-- Extracting source E:/Git/vcpkg.downloads/microsoft-cppgraphqlgen-v3.1.1.tar.gz
-- Using source at D:/Git/vs2017.prod/buildtrees/cppgraphqlgen/src/v3.1.1-f2eca4fdc5
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v
    Working Directory: D:/Git/vs2017.prod/buildtrees/cppgraphqlgen/x64-windows-dbg
    See logs for more information:
      D:\Git\vs2017.prod\buildtrees\cppgraphqlgen\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/cppgraphqlgen/portfile.cmake:17 (vcpkg_install_cmake)
  scripts/ports.cmake:90 (include)

Error: Building package cppgraphqlgen:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: cppgraphqlgen:x64-windows
  Vcpkg version: 2020.02.04-nohash-external

Additionally, attach any relevant sections from the log files above.
- Please attach any additional failure logs mentioned in the console output.
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/4321099/install-x64-windows-dbg-out.log)

**Additional context**
It builds, compiles and installs fine on VS 2019 v16.4.6 VS Tools Version 14.24.28314.

**Comment by NancyLi1013** [comment]
Hi @timautry 
Thanks for posting this issue.
I can build this port succesffully with VS 2017. 
```
D:\Git\vs2017.prod\buildtrees\cppgraphqlgen\src\v3.1.1-f2eca4fdc5\include\graphqlservice/GraphQLService.h(563): error C3539: a template-argument cannot be a type that contains 'auto'
IntrospectionSchema.cpp(137): note: see reference to function template instantiation 'std::future<graphql::response::Value> graphql::service::ModifiedResult<graphql::introspection::object::Type>::convert<graphql::service::TypeModifier::List,>(graphql::service::FieldResult<std::vector<std::shared_ptr<graphql::introspection::object::Type>,std::allocator<_Ty>>> &&,graphql::service::ResolverParams &&)' being compiled
        with
        [
            _Ty=std::shared_ptr<graphql::introspection::object::Type>
        ]
IntrospectionSchema.cpp(137): note: see reference to function template instantiation 'std::future<graphql::response::Value> graphql::service::ModifiedResult<graphql::introspection::object::Type>::convert<graphql::service::TypeModifier::List,>(graphql::service::FieldResult<std::vector<std::shared_ptr<graphql::introspection::object::Type>,std::allocator<_Ty>>> &&,graphql::service::ResolverParams &&)' being compiled
        with
        [
            _Ty=std::shared_ptr<graphql::introspection::object::Type>
        ]
```
Could you please try to remove `auto `and build it again?
