### ISSUE TITLE
[libgeotiff:x64-windows] update to <1.5.1>

### ISSUE THREAD

**Issue by HWiman** [microsoft/vcpkg#10394]
Library name: libgeotiff

New version number: 1.5.1

Other information that may be useful (release notes, etc...)
https://github.com/OSGeo/libgeotiff

vcpkg rocks! Keep up the good work!

**Comment by Gigas002** [comment]
1.6.0 released, hope port is going to be updated soon.

**Comment by LilyWangL** [comment]
I will confirm and update this port soon.
