### ISSUE TITLE
[New Port Request] <ncnn>

### ISSUE THREAD

**Issue by how0723** [microsoft/vcpkg#10400]
Library name: ncnn

Library description: ncnn is a high-performance neural network inference framework optimized for the mobile platform

Source repository URL: https://github.com/Tencent/ncnn

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by linquize** [comment]
core: no dependencies
feature opencv: depends on opencv

**Comment by linquize** [comment]
core: no dependencies
feature tools: depends on protobuf, opencv

**Comment by linquize** [comment]
core: no dependencies
feature tools: depends on protobuf, opencv

List of tools:

    caffe model convert tool: depends on protobuf
    onnx model convert tool: depends on protobuf
    quantize tools: depends on opencv

**Comment by MaverickTse** [comment]
I support this proposal if it can be reliably built. Note that recent ncnn's CI check often failed for Linux build. I personally can only get it built on windows.

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by zchrissirhcz** [comment]
@LilyWangL Hi, I would like to add this port now. The previously mentioned "ncnn's CI often check failed for Linux build" is fixed, and it is also possible to choose its git tags which are stable(build success on all platforms) and format is united (e.g. 20200420).

 https://github.com/Tencent/ncnn/tags

**Comment by zchrissirhcz** [comment]
Actually, I just git cloned the latest vcpkg on my macOSX(Intel chip), running a `./vcpkg search ncnn` shows this port is outdated:
<img width="867" alt="image" src="https://user-images.githubusercontent.com/3831847/168283848-c1feb1f6-3439-46dd-902e-f6cd5e2ed5e7.png">

@JackBoosY  Hi, would you please help consider adding this port?

**Comment by JackBoosY** [comment]
@zchrissirhcz You can make a simple PR then I will help you to add this port.
