### ISSUE TITLE
Error with .\bootstrap-vcpkg.bat

### ISSUE THREAD

**Issue by nisha1729** [microsoft/vcpkg#10406]
I'm trying to install this package and when I run .\bootstrap-vcpkg.bat, I get the following error:
```
Program 'bootstrap-vcpkg.bat' failed to run: The specified executable is not a valid application for this OS
platform.At line:1 char:1
+ .\bootstrap-vcpkg.bat
+ ~~~~~~~~~~~~~~~~~~~~~.
At line:1 char:1
+ .\bootstrap-vcpkg.bat
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed
```
Windows 10, Power Shell (5.1.18362.628)

Could someone tell me what I'm missing? Thanks!

**Comment by NancyLi1013** [comment]
Hi @nisha1729 

Thanks for posting this issue.
Could you please help provide the steps to reproduce? Is vcpkg the latest version(2020.02.04) ?

**Comment by nisha1729** [comment]
Hi @NancyLi1013 , 

I followed the instructions given:
```
> git clone https://github.com/Microsoft/vcpkg.git
> cd vcpkg
> .\bootstrap-vcpkg.bat

```

**Comment by NancyLi1013** [comment]
This is not related to the directory that you installed.
Is this your first time to clone vcpkg or not?

You can try `git pull`  to update vcpkg to the latest version and then run `.\bootstrap-vcpkg.bat`. If there is no any update, it is already the latest.
If still error, please post the full error log.

**Comment by nisha1729** [comment]
There is no update, so it must be the latest. Yes, it is my first time. Error is still the same:
`\

`

**Comment by NancyLi1013** [comment]
Could you please help provide the following information?
-  Windows 10 version (The specific version)
-  Visual Studio version (The specofic version)
-  Windows SDK version (Which version you have installed)

**Comment by traversaro** [comment]
> There is no update, so it must be the latest. Yes, it is my first time. Error is still the same:
> 
> ```
> Program 'bootstrap-vcpkg.bat' failed to run: The specified executable is not a valid application for this OS
> platform.At line:1 char:1
> + .\bootstrap-vcpkg.bat
> + ~~~~~~~~~~~~~~~~~~~~~.
> At line:1 char:1
> + .\bootstrap-vcpkg.bat
> + ~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
>     + FullyQualifiedErrorId : NativeCommandFailed
> ```
> 
> ![image](https://user-images.githubusercontent.com/7227383/76623894-4e19d800-655a-11ea-916b-ea7344cd10da.png)

Based on the screenshot, you are running `git clone` in a directory called `vcpkg`, but the git clone will create another `vcpkg` directory inside it, and so to actually run the `bootstrap-vcpkg.bat` you need to first run `cd vcpkg` to actually move in the `vcpkg` created by `git clone`.

**Comment by NancyLi1013** [comment]
@nisha1729 

Is this still a problem for you now?

**Comment by nisha1729** [comment]
No, thank you.

**Comment by Remi-Coulom** [comment]
I have the same problem. How did you solve it?

**Comment by narasimhan11102** [comment]
@NancyLi1013
Hello,
When I try to run the bootstrap command in cmd I get an error stating that VS has not been installed, but I have already installed VS CODE earlier 
![image](https://user-images.githubusercontent.com/76741184/103304501-cd679200-4a2e-11eb-8c7c-e41a63e59a54.png)

**Comment by NancyLi1013** [comment]
@narasimhan11102 

Please see the comments here https://github.com/microsoft/vcpkg/issues/11222#issuecomment-752298079.

Thanks.

**Comment by sabrabano0** [comment]
i got this error too, this is my first time
C:\openMVG_MVS\vcpkg\scripts\bootstrap.ps1 : Downloading vcpkg.exe failed. Please check your internet connection, or
consider downloading a recent vcpkg.exe from https://github.com/microsoft/vcpkg-tool with a browser.
At line:1 char:4
+ & {& 'c:\openMVG_MVS\vcpkg\scripts\bootstrap.ps1' }
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,bootstrap.ps1

ScriptHalted
At C:\openMVG_MVS\vcpkg\scripts\bootstrap.ps1:60 char:5
+     throw
+     ~~~~~
    + CategoryInfo          : OperationStopped: (:) [], RuntimeException
    + FullyQualifiedErrorId : ScriptHalted

**Comment by numericlee** [comment]
same issue
WSL2

**Comment by shreyashnadage** [comment]
> i got this error too, this is my first time
> C:\openMVG_MVS\vcpkg\scripts\bootstrap.ps1 : Downloading vcpkg.exe failed. Please check your internet connection, or
> consider downloading a recent vcpkg.exe from https://github.com/microsoft/vcpkg-tool with a browser.
> At line:1 char:4
> + & {& 'c:\openMVG_MVS\vcpkg\scripts\bootstrap.ps1' }
> +    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
>     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,bootstrap.ps1
> 
> ScriptHalted
> At C:\openMVG_MVS\vcpkg\scripts\bootstrap.ps1:60 char:5
> +     throw
> +     ~~~~~
>     + CategoryInfo          : OperationStopped: (:) [], RuntimeException
>     + FullyQualifiedErrorId : ScriptHalted

How did you solve this?
