### ISSUE TITLE
Mention MSVC requirements in FAQ doc

### ISSUE THREAD

**Issue by linquize** [microsoft/vcpkg#10401]
Let's mention some MSVC requirements in FAQ doc
- Currently on Windows, MSVC must be installed in order to build `vcpkg.exe`
- The necessary Visual Studio C++ features to select
- Visual Studio English language pack, recently there are issues reported regarding this

**Comment by PhoebeHui** [comment]
This should not be a problem now, currently we download the vcpkg.exe instead.
For English language pack, it has been mentioned in https://github.com/microsoft/vcpkg#quick-start-windows.
