### ISSUE TITLE
[New Port Request] <xed>

### ISSUE THREAD

**Issue by eix128** [microsoft/vcpkg#10412]
Library name:
XED

Library description:
The X86 Encoder Decoder (XED), is a software library (and associated headers) for encoding and decoding X86 (IA32 and Intel64) instructions. The decoder takes sequences of 1-15 bytes along with machine mode information and produces a data structure describing the opcode, operands, and flags. The encoder takes a similar data structure and produces a sequence of 1 to 15 bytes. Disassembly is essentially a printing pass on the data structure.

XED is the encoder/decoder used by Pin and the Intel® Software Development Emulator (SDE). XED is used by the ASIM performance model, ZSIM, Intel® VTune Amplifier, IACA, as well as in projects at McAfee, Wind River, and many other projects inside and outside Intel.

Source repository URL:
https://intelxed.github.io

Project homepage (if different from the source repository):
https://software.intel.com/en-us/articles/xed-x86-encoder-decoder-software-library

Remill library i have given to you is using this library as dependency

There is also some cmake script that may help you:
https://github.com/trailofbits/cxx-common/blob/master/cmake_modules/FindXED.cmake

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by DiskGetor** [comment]
vcpkg.exe  install xed ? nothing output?
