### ISSUE TITLE
CMake Error at C:/Program Files/CMake/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message)

### ISSUE THREAD

**Issue by Asif1405** [microsoft/vcpkg#10418]
I am trying to use cmake to compile darknet for YOLO V3. But getting following error:
CMake Error at C:/Program Files/CMake/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message): Could NOT find PThreads_windows (missing: PThreads_windows_LIBRARY PThreads_windows_INCLUDE_DIR) Call Stack (most recent call first): C:/Program Files/CMake/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE) cmake/Modules/FindPThreads_windows.cmake:39 (find_package_handle_standard_args) C:/Users/MSI/vcpkg/scripts/buildsystems/vcpkg.cmake:288 (_find_package) CMakeLists.txt:93 (find_package)

How can I fix this?

**Comment by linquize** [comment]
How did you install darknet?
`vcpkg install darknet:x64-windows`?
What compiler did you use?

**Comment by PhoebeHui** [comment]
@Asif1405, could you provide us the environment and repro steps, also attach the failure logs? 

I tried to build darknet:x64-windows with latest vcpkg and VS2017 15.9.19, it built successfully for me.
Starting package 3/3: darknet:x64-windows
Building package darknet[core]:x64-windows...
-- Downloading https://github.com/AlexeyAB/darknet/archive/81290b07376c5abb4988a492dda70913bb90133d.tar.gz...
-- Extracting source F:/VCPKG/src/downloads/AlexeyAB-darknet-81290b07376c5abb4988a492dda70913bb90133d.tar.gz
-- Using source at F:/VCPKG/src/buildtrees/darknet/src/13bb90133d-a4584e7461
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: F:/VCPKG/src/packages/darknet_x64-windows/share/darknet/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package darknet[core]:x64-windows... done
Installing package darknet[core]:x64-windows...
Installing package darknet[core]:x64-windows... done
Elapsed time for package darknet:x64-windows: 52.26 s

Total elapsed time: 1.488 min

The package darknet:x64-windows provides CMake targets:

    find_package(Darknet CONFIG REQUIRED)

**Comment by PhoebeHui** [comment]
@Asif1405, feel free to reopen this issue if it still a problem for you, please also provide us the repro steps at the same time.
