### ISSUE TITLE
Release-only pre-built binary package?

### ISSUE THREAD

**Issue by soroush-rabiei** [microsoft/vcpkg#10410]
I have a proprietary SDK which is basically a set of DLL, LIB and header files. I would like to pack it as a vcpkg package. So far I've made a `CMakeList.txt` that simply copies those binaries and header files in corresponding locations. 

The problem is that the vendor of this SDK does not provide any debug builds, so I tried to disable debug build in `profile.cmake`:

```
set(VCPKG_BUILD_TYPE release)
```

Though vcpkg still complains:

```
Mismatching number of debug and release binaries. Found 0 for debug but 6 for release.
```

Well, my SDK does not have any debug binaries, and I don't want vcpkg to look for them. How do I disable debug build completely?

**Comment by linquize** [comment]
Did you read https://vcpkg.readthedocs.io/en/latest/about/faq/ ?

**Comment by PhoebeHui** [comment]
@soroush-rabiei, 'set(VCPKG_BUILD_TYPE release)' should be added to triplets file, like in .\triplets\x64-windows.cmake.

**Comment by PhoebeHui** [comment]
@soroush-rabiei, does this still be a problem for you?

**Comment by PhoebeHui** [comment]
@soroush-rabiei, please reopen this issue if the issue persist.

**Comment by kevin--** [comment]
This does not answer the question. I am writing a port file for a release-only library similar to the OP. setting the `VCPKG_BUILD_TYPE` in the port file does not affect anything.

```
Mismatching number of debug and release binaries. Found 0 for debug but 2 for release.
Debug binaries


Release binaries

    /Users/xxx/projects/vcpkg/packages/mylib_arm64-osx/lib/libone.a
    /Users/xxx/projects/vcpkg/packages/mylib_arm64-osx/lib/libtwo.a

Debug binaries were not found

Found 1 post-build check problem(s). To submit these ports to curated catalogs, please first correct the portfile:
```
I see there is a policy in the vcpkg tool itself to check or not check this, so how do we manipulate this setting from a portfile? Thanks!
