### ISSUE TITLE
[New Port Request] <intel pin>

### ISSUE THREAD

**Issue by eix128** [microsoft/vcpkg#10415]
Library name:
intel pin , pin tools
Library description:
Pin is a dynamic binary instrumentation framework for the IA-32, x86-64 and MIC instruction-set architectures that enables the creation of dynamic program analysis tools. Some tools built with Pin are Intel® VTune™ Amplifier, Intel® Inspector, Intel® Advisor and Intel® Software Development Emulator (Intel® SDE). The tools created using Pin, called Pintools, can be used to perform program analysis on user space applications on Linux*, Windows* and macOS*. As a dynamic binary instrumentation tool, instrumentation is performed at run time on the compiled binary files. Thus, it requires no recompiling of source code and can support instrumenting programs that dynamically generate code.

Source repository URL:
https://software.intel.com/en-us/articles/pin-a-binary-instrumentation-tool-downloads

Project homepage (if different from the source repository):
https://software.intel.com/en-us/articles/pin-a-dynamic-binary-instrumentation-tool

Tracing executable with Pin:
https://www.youtube.com/watch?v=kurzaoWuSHA

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
