### ISSUE TITLE
[New Port Request] <remill>

### ISSUE THREAD

**Issue by eix128** [microsoft/vcpkg#10411]
Library name:
Remill

Library description:
Remill is a static binary translator that translates machine code instructions into LLVM bitcode. It translates x86 and amd64 machine code (including AVX and AVX512) into LLVM bitcode. AArch64 support is underway.

Remill focuses on accurately lifting instructions. It is meant to be used as a library for other tools, e.g. McSema.

Source repository URL:
https://github.com/lifting-bits/remill

This project has sub dependencies:

Git | Latest
CMake | 3.2+
Google Flags | Latest
Google Log | Latest
Google Test | Latest
LLVM | 3.5+
Clang | 3.5+
Intel XED | Latest
Python | 2.7
Unzip | Latest
ccache | Latest

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
