### ISSUE TITLE
[curlpp] build failure

### ISSUE THREAD

**Issue by DropJor4** [microsoft/vcpkg#10423]
I install curlpp in my terminal in the folder vcpkg and then it indicates this,

Computing installation plan...
The following packages will be built and installed:
    curlpp[core]:x86-windows
Starting package 1/1: curlpp:x86-windows
Building package curlpp[core]:x86-windows...
-- Using cached D:/accountmap/Desktop/vcpkg-master/vcpkg-master/downloads/jpbarrette-curlpp-8810334c830faa3b38bcd94f5b1ab695a4f05eb9.tar.gz
-- Using source at D:/accountmap/Desktop/vcpkg-master/vcpkg-master/buildtrees/curlpp/src/95a4f05eb9-6c154942c9
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: ninja -v
    Working Directory: D:/accountmap/Desktop/vcpkg-master/vcpkg-master/buildtrees/curlpp/x86-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\accountmap\Desktop\vcpkg-master\vcpkg-master\buildtrees\curlpp\config-x86-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:295 (vcpkg_execute_required_process)
  ports/curlpp/portfile.cmake:11 (vcpkg_configure_cmake)
  scripts/ports.cmake:90 (include)

Error: Building package curlpp:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: curlpp:x86-windows
  Vcpkg version: 2020.02.04-nohash

Additionally, attach any relevant sections from the log files above.

Does anyone know how I could fix this?

**Comment by linquize** [comment]
Can you post the content of `D:\accountmap\Desktop\vcpkg-master\vcpkg-master\buildtrees\curlpp\config-x86-windows-out.log`?

**Comment by linquize** [comment]
Could you change the title of the issue, for example: "[curlpp] build failure"?

**Comment by DropJor4** [comment]
No I can not in the folder config-x86-windows-out.log

**Comment by DropJor4** [comment]
But can i fix this?

**Comment by DropJor4** [comment]
This is my config-x86-windows-out.log!

[1/2] cmd /c "cd .. && "D:/accountmap/Desktop/vcpkg-master/vcpkg-master/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe" "D:/accountmap/Desktop/vcpkg-master/vcpkg-master/buildtrees/curlpp/src/95a4f05eb9-6c154942c9" "-DCMAKE_MAKE_PROGRAM=D:/accountmap/Desktop/vcpkg-master/vcpkg-master/downloads/tools/ninja/ninja-1.8.2/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=D:/accountmap/Desktop/vcpkg-master/vcpkg-master/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x86-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v141" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=D:/accountmap/Desktop/vcpkg-master/vcpkg-master/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_TARGET_ARCHITECTURE=x86" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=D:/accountmap/Desktop/vcpkg-master/vcpkg-master/packages/curlpp_x86-windows""
FAILED: ../CMakeCache.txt 
cmd /c "cd .. && "D:/accountmap/Desktop/vcpkg-master/vcpkg-master/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe" "D:/accountmap/Desktop/vcpkg-master/vcpkg-master/buildtrees/curlpp/src/95a4f05eb9-6c154942c9" "-DCMAKE_MAKE_PROGRAM=D:/accountmap/Desktop/vcpkg-master/vcpkg-master/downloads/tools/ninja/ninja-1.8.2/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=D:/accountmap/Desktop/vcpkg-master/vcpkg-master/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x86-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v141" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=D:/accountmap/Desktop/vcpkg-master/vcpkg-master/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_TARGET_ARCHITECTURE=x86" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=D:/accountmap/Desktop/vcpkg-master/vcpkg-master/packages/curlpp_x86-windows""
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:1 (project):
  No CMAKE_C_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:1 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "D:/accountmap/Desktop/vcpkg-master/vcpkg-master/buildtrees/curlpp/x86-windows-rel/CMakeFiles/CMakeOutput.log".
See also "D:/accountmap/Desktop/vcpkg-master/vcpkg-master/buildtrees/curlpp/x86-windows-rel/CMakeFiles/CMakeError.log".
[2/2] cmd /c "cd ../../x86-windows-dbg && "D:/accountmap/Desktop/vcpkg-master/vcpkg-master/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe" "D:/accountmap/Desktop/vcpkg-master/vcpkg-master/buildtrees/curlpp/src/95a4f05eb9-6c154942c9" "-DCMAKE_MAKE_PROGRAM=D:/accountmap/Desktop/vcpkg-master/vcpkg-master/downloads/tools/ninja/ninja-1.8.2/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=D:/accountmap/Desktop/vcpkg-master/vcpkg-master/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x86-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v141" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=D:/accountmap/Desktop/vcpkg-master/vcpkg-master/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_TARGET_ARCHITECTURE=x86" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_INSTALL_PREFIX=D:/accountmap/Desktop/vcpkg-master/vcpkg-master/packages/curlpp_x86-windows/debug""
FAILED: ../../x86-windows-dbg/CMakeCache.txt 
cmd /c "cd ../../x86-windows-dbg && "D:/accountmap/Desktop/vcpkg-master/vcpkg-master/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe" "D:/accountmap/Desktop/vcpkg-master/vcpkg-master/buildtrees/curlpp/src/95a4f05eb9-6c154942c9" "-DCMAKE_MAKE_PROGRAM=D:/accountmap/Desktop/vcpkg-master/vcpkg-master/downloads/tools/ninja/ninja-1.8.2/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=D:/accountmap/Desktop/vcpkg-master/vcpkg-master/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x86-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v141" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=D:/accountmap/Desktop/vcpkg-master/vcpkg-master/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_TARGET_ARCHITECTURE=x86" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_INSTALL_PREFIX=D:/accountmap/Desktop/vcpkg-master/vcpkg-master/packages/curlpp_x86-windows/debug""
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:1 (project):
  No CMAKE_C_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:1 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "D:/accountmap/Desktop/vcpkg-master/vcpkg-master/buildtrees/curlpp/x86-windows-dbg/CMakeFiles/CMakeOutput.log".
See also "D:/accountmap/Desktop/vcpkg-master/vcpkg-master/buildtrees/curlpp/x86-windows-dbg/CMakeFiles/CMakeError.log".
ninja: build stopped: subcommand failed.

**Comment by linquize** [comment]
Why did you have `ninja` in `downloads/tools`?
Is your VS2017 properly installed with MSVC features?

**Comment by DropJor4** [comment]
What is MSVC?

**Comment by DropJor4** [comment]
How do I install that exactly?

**Comment by DropJor4** [comment]
Yes I installed VS2017 correct

**Comment by linquize** [comment]
Strange,  C++ compiler was not detected by cmake.

**Comment by linquize** [comment]
Do you also has gcc?

**Comment by linquize** [comment]
Do you also have gcc or clang installed?

**Comment by NancyLi1013** [comment]
Hi @DropJor4 
Thanks for posting this issue.
Could you please help confirm if you have installed Visual Studio?

**Comment by kokerf** [comment]
My cmake version is 3.17.0-rc3, and I met the same case.

```
PS E:\library\vcpkg> .\vcpkg.exe install eigen3
Computing installation plan...
The following packages will be built and installed:
    eigen3[core]:x86-windows
Starting package 1/1: eigen3:x86-windows
Building package eigen3[core]:x86-windows...
Warning: The following VS instances are excluded because the English language pack is unavailable.
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community
    C:\Program Files (x86)\Microsoft Visual Studio 12.0\
Please install the English language pack.
-- Using cached E:/library/vcpkg/downloads/libeigen-eigen-3.3.7.tar.gz
-- Using source at E:/library/vcpkg/buildtrees/eigen3/src/3.3.7-c7b55a8243
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: ninja -v
    Working Directory: E:/library/vcpkg/buildtrees/eigen3/x86-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      E:\library\vcpkg\buildtrees\eigen3\config-x86-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:295 (vcpkg_execute_required_process)
  ports/eigen3/portfile.cmake:14 (vcpkg_configure_cmake)
  scripts/ports.cmake:90 (include)


Error: Building package eigen3:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: eigen3:x86-windows
  Vcpkg version: 2020.02.04-nohash
```

**Comment by DropJor4** [comment]
linquize, No I did not download that

**Comment by NancyLi1013** [comment]
@kokerf 
```
Warning: The following VS instances are excluded because the English language pack is unavailable.
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community
    C:\Program Files (x86)\Microsoft Visual Studio 12.0\
Please install the English language pack.
```
Please check if you have installed English language pack in Visual Studio.

**Comment by kokerf** [comment]
> @kokerf
> 
> ```
> Warning: The following VS instances are excluded because the English language pack is unavailable.
>     C:\Program Files (x86)\Microsoft Visual Studio\2017\Community
>     C:\Program Files (x86)\Microsoft Visual Studio 12.0\
> Please install the English language pack.
> ```
> 
> Please check if you have installed English language pack in Visual Studio.
> 
> @DropJor4
> Please install Visual Studio (2015 Update 3 or newer (on Windows) first and then build this.

Thank you for you reply. I fixed it by switching the cmake version to 3.14.0. But another error occurred. McAfee deleted `CMakeFiles\3.14.0\CompilerIdCXX\CMakeCXXCompilerId.exe` as virus when I was installing a package. I wonder if I should open a new issue :unamused: .

**Comment by DropJor4** [comment]
Nancy, I have already downloaded visual studio 2017

**Comment by DropJor4** [comment]
Do I also have to install the English version?

**Comment by NancyLi1013** [comment]
@DropJor4 You can check it in `Language packs` item of `Visual Studio Installer` and confirm if it has been installed.

**Comment by DropJor4** [comment]
@NancyLi1013 Yes it was installed but did not help me further

**Comment by DropJor4** [comment]
@NancyLi1013 could this work on my other pc at once?

**Comment by NancyLi1013** [comment]
Please install Visual Studio with Englist pack and Windows SDK first.
Then you can try the steps:
```
> git clone https://github.com/Microsoft/vcpkg.git
> cd vcpkg

PS> .\bootstrap-vcpkg.bat
```
If there is no problem on your local environment, it should work well.

**Comment by DropJor4** [comment]
@NancyLi1013 You mean on my PC itself?

**Comment by NancyLi1013** [comment]
Yes, you need to install them manually first.

**Comment by NancyLi1013** [comment]
@DropJor4 
Could you please help confirm if you still have this issue?

**Comment by NancyLi1013** [comment]
Please feel free to reopen this issue if it is still a problem for you.
