### ISSUE TITLE
[New Port Request] cbc

### ISSUE THREAD

**Issue by linquize** [microsoft/vcpkg#10425]
Library name: cbc

Library description: COIN-OR Branch-and-Cut solver

Source repository URL: https://github.com/coin-or/Cbc

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included): ortools depends on this.

**Comment by Voskrese** [comment]
the port is not mine
did not test the port

[cbc.zip](https://github.com/microsoft/vcpkg/files/4334795/cbc.zip)

**Comment by AirCoder89** [comment]
### Create by Adobe Flash & ActionScript 3.0

**Description:**
Drag the black balls to activate the whites.. Sounds easy? Try it!
white ball is activated if the lines pass through it! To complete the level you have to activate all grey balls.

**Features:**
◆ unlimited levels
◆ amazing design
◆ original soundtrack
◆ increasing difficulty

**Screenshots**

![Screenshot_2016-10-06-12-03-52](https://user-images.githubusercontent.com/62396712/77127184-e1b44280-6a4b-11ea-8c59-f16820f37cb1.jpg)
![01](https://user-images.githubusercontent.com/62396712/77127168-d2cd9000-6a4b-11ea-8d26-743f7f74c1a2.png)
![Screenshot_2016-10-06-11-58-39](https://user-images.githubusercontent.com/62396712/77127174-d6f9ad80-6a4b-11ea-9a7d-5d77f10ead9e.jpg)
![Screenshot_2016-09-29-11-13-36](https://user-images.githubusercontent.com/62396712/77127177-d95c0780-6a4b-11ea-8846-03cca8116626.jpg)
![Screenshot_2016-09-29-11-16-36](https://user-images.githubusercontent.com/62396712/77127178-da8d3480-6a4b-11ea-8303-942ecc3e596c.jpg)
![Screenshot_2016-10-06-12-04-04](https://user-images.githubusercontent.com/62396712/77127214-fd1f4d80-6a4b-11ea-845f-769077d2f2bd.jpg)

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue and continue related PR, but we're closing it for now.
