### ISSUE TITLE
building aruco get error "The following EXEs were found in /bin or /debug/bin. EXEs are not valid distribution targets."

### ISSUE THREAD

**Issue by haimingZZ** [microsoft/vcpkg#10428]
I am building aruco from source code, the link is as follow   https://www.uco.es/investiga/grupos/ava/node/26;
and i got the following errors:

λ vcpkg install aruco:x64-windows
Computing installation plan...
The following packages will be built and installed:
    aruco[core]:x64-windows
Starting package 1/1: aruco:x64-windows
Building package aruco[core]:x64-windows...
-- Using cached F:/git_vcpkg/vcpkg/downloads/aruco-3.1.11.zip
-- Using source at F:/git_vcpkg/vcpkg/buildtrees/aruco/src/aruco-3-a1294cedcd
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: F:/git_vcpkg/vcpkg/packages/aruco_x64-windows/share/aruco/copyright
-- Performing post-build validation
The following EXEs were found in /bin or /debug/bin. EXEs are not valid distribution targets.

    F:/git_vcpkg/vcpkg/packages/aruco_x64-windows/bin/aruco_batch_processing.exe
    F:/git_vcpkg/vcpkg/packages/aruco_x64-windows/bin/aruco_calibration.exe
    F:/git_vcpkg/vcpkg/packages/aruco_x64-windows/bin/aruco_calibration_fromimages.exe
    F:/git_vcpkg/vcpkg/packages/aruco_x64-windows/bin/aruco_create_markermap.exe
    F:/git_vcpkg/vcpkg/packages/aruco_x64-windows/bin/aruco_markermap_pix2meters.exe
    F:/git_vcpkg/vcpkg/packages/aruco_x64-windows/bin/aruco_print_dictionary.exe
    F:/git_vcpkg/vcpkg/packages/aruco_x64-windows/bin/aruco_print_marker.exe
    F:/git_vcpkg/vcpkg/packages/aruco_x64-windows/bin/aruco_simple.exe
    F:/git_vcpkg/vcpkg/packages/aruco_x64-windows/bin/aruco_simple_markermap.exe
    F:/git_vcpkg/vcpkg/packages/aruco_x64-windows/bin/aruco_test.exe
    F:/git_vcpkg/vcpkg/packages/aruco_x64-windows/bin/aruco_test_markermap.exe
    F:/git_vcpkg/vcpkg/packages/aruco_x64-windows/bin/aruco_tracker.exe
    F:/git_vcpkg/vcpkg/packages/aruco_x64-windows/bin/fractal_tracker.exe

The following EXEs were found in /bin or /debug/bin. EXEs are not valid distribution targets.

    F:/git_vcpkg/vcpkg/packages/aruco_x64-windows/debug/bin/aruco_batch_processing.exe
    F:/git_vcpkg/vcpkg/packages/aruco_x64-windows/debug/bin/aruco_calibration.exe
    F:/git_vcpkg/vcpkg/packages/aruco_x64-windows/debug/bin/aruco_calibration_fromimages.exe
    F:/git_vcpkg/vcpkg/packages/aruco_x64-windows/debug/bin/aruco_create_markermap.exe
    F:/git_vcpkg/vcpkg/packages/aruco_x64-windows/debug/bin/aruco_markermap_pix2meters.exe
    F:/git_vcpkg/vcpkg/packages/aruco_x64-windows/debug/bin/aruco_print_dictionary.exe
    F:/git_vcpkg/vcpkg/packages/aruco_x64-windows/debug/bin/aruco_print_marker.exe
    F:/git_vcpkg/vcpkg/packages/aruco_x64-windows/debug/bin/aruco_simple.exe
    F:/git_vcpkg/vcpkg/packages/aruco_x64-windows/debug/bin/aruco_simple_markermap.exe
    F:/git_vcpkg/vcpkg/packages/aruco_x64-windows/debug/bin/aruco_test.exe
    F:/git_vcpkg/vcpkg/packages/aruco_x64-windows/debug/bin/aruco_test_markermap.exe
    F:/git_vcpkg/vcpkg/packages/aruco_x64-windows/debug/bin/aruco_tracker.exe
    F:/git_vcpkg/vcpkg/packages/aruco_x64-windows/debug/bin/fractal_tracker.exe

Found 2 error(s). Please correct the portfile:
    F:\git_vcpkg\vcpkg\ports\aruco\portfile.cmake
-- Performing post-build validation done
Error: Building package aruco:x64-windows failed with: POST_BUILD_CHECKS_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: aruco:x64-windows
  Vcpkg version: 2020.02.04-nohash

Additionally, attach any relevant sections from the log files above.

So how to delete the used exe files? 
Thanks a lot.

**Comment by haimingZZ** [comment]
I  changed the file options.cmake as follow

#------------------------------------------------------
# Build type
#------------------------------------------------------

if(NOT CMAKE_BUILD_TYPE )
   set( CMAKE_BUILD_TYPE "Debug" )
endif()

#------------------------------------------------------
# Lib Names and Dirs
#------------------------------------------------------

if(WIN32)
    # Postfix of DLLs:
    # Postfix of DLLs:
    set(PROJECT_DLLVERSION "${PROJECT_VERSION_MAJOR}${PROJECT_VERSION_MINOR}${PROJECT_VERSION_PATCH}")
    #set(RUNTIME_OUTPUT_PATH ${PROJECT_BINARY_DIR}/del_exe CACHE PATH "Directory for dlls and binaries")
    #set(EXECUTABLE_OUTPUT_PATH ${PROJECT_BINARY_DIR}/del_exe CACHE PATH "Directory for binaries")
    set(LIBRARY_OUTPUT_PATH ${PROJECT_BINARY_DIR}/bin CACHE PATH "Directory for dlls")

else()
    # Postfix of so's:
    set(PROJECT_DLLVERSION)
#    set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} ${CMAKE_INSTALL_PREFIX}/lib/cmake/ /usr/lib/cmake)
endif()

option(USE_OWN_EIGEN3	"Set to OFF to use a standard eigen3 version" ON)
option(BUILD_UTILS	"Set to OFF to not compile utils " OFF)
option(BUILD_SHARED_LIBS 	"Set to OFF to build static libraries" ON)
option(BUILD_GLSAMPLES 	"Set to OFF to build static libraries" OFF)
option(USE_TIMERS 	"Set to OFF to build static libraries" OFF)
option(BUILD_DEBPACKAGE 	"Set to ON to use cpack" OFF)
option(ARUCO_DEVINSTALL 	"Set to OFF to disable source installation" ON)
  iF(USE_TIMERS)
add_definitions(-DUSE_TIMERS)
ENDIF()
# ----------------------------------------------------------------------------
#   PROJECT CONFIGURATION
#   force some variables that could be defined in the command line to be written to cache
# ----------------------------------------------------------------------------
option(INSTALL_DOC 	"Set to ON to build/install Documentation" OFF)
if (INSTALL_DOC)
    find_package(Doxygen REQUIRED)
    message( STATUS "INSTALL_DOC:         ${INSTALL_DOC} ")
    include("${PROJECT_SOURCE_DIR}/cmake/generateDoc.cmake")
    generate_documentation(${PROJECT_SOURCE_DIR}/cmake/dox.in)
endif()

# ----------------------------------------------------------------------------
#   Uninstall target, for "make uninstall"
# ----------------------------------------------------------------------------
configure_file("${PROJECT_SOURCE_DIR}/cmake/cmake_uninstall.cmake.in" "${PROJECT_BINARY_DIR}/cmake_uninstall.cmake" IMMEDIATE @ONLY)
add_custom_target(uninstall "${CMAKE_COMMAND}" -P "${PROJECT_BINARY_DIR}/cmake_uninstall.cmake")

the building process is fine. No error occur.
Is there other way to work this around?
1 add instructions to delete *.exe in portfile.cmake?
2 if i want to build vcpkg package from sources in folder instead of zip file, what should i do？
3 if i want to commit this aruco package to vcpkg git, how should i do that?

thanks a lot

**Comment by PhoebeHui** [comment]
Hi @haimingZZ ,

1. Usually, the .exe need to delete or move to 'tools' folder, does the .exe file used to build the project, if so, that might need to move tools folder , if it's no use, then it should be removed.
2. Where does the source place? Github? if so, you can reference [doc](https://github.com/microsoft/vcpkg/blob/master/docs/examples/packaging-github-repos.md).
3. We are happy to accept the PR! the [doc](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md) provide the guidelines with maintainers, feel free to summit a PR, the team member and contributor will help review.

**Comment by PhoebeHui** [comment]
@haimingZZ, feel free to reopen this issue if it still be a problem for you.

**Comment by ooeygui** [comment]
@haimingZZ Hi there, 
Sorry for reaching out on a closed bug - there really isn't a good chat channel for this.
I'm the development lead for ROS on Windows. I was going to start adding Arocu to VCPKG as well, when I accidentally came across your post. I was wondering if you've made progress on it? Or if you need help?

**Comment by haimingZZ** [comment]
@ooeygui I have added aruco to vcpkg, simply change some settings.
\cmake\options.cmake
&& CMakeLists.txt
The build zip files are attatched.

I think there is better ways to build aruco. I didn't find a solution in vcpkg document.
If you have a better solution, please let me know.

Thanks.

[aruco-3.1.11_vcpkg.zip](https://github.com/microsoft/vcpkg/files/4526283/aruco-3.1.11_vcpkg.zip)
