### ISSUE TITLE
[freerdp] Included FreeRDP headers can't find other FreeRDP headers

### ISSUE THREAD

**Issue by VelocityRa** [microsoft/vcpkg#10421]
FreeRDP built fine, then I imported it to my project with
```
set(WITH_MANPAGES OFF)
set(WITH_CLIENT OFF)
set(WITH_SERVER ON)
set(WITH_DEBUG_ALL ON)
find_package(FreeRDP CONFIG REQUIRED)
find_package(WinPR CONFIG REQUIRED)
target_link_libraries(myproj PUBLIC freerdp winpr winpr-tools)
```
and when including any file, ie.
```c
#include <freerdp2/freerdp/api.h>
```
I get compile errors when _that_ file tries to include `<winpr/platform.h>`.
Similar case for any other file in the project.

Those files **do** exist in my installation's `include/` but they are of course in `freerdp2/freerdp/*`.
Probably some include paths are not set correctly by vpckg?

I'm on x64-windows & MSVC.

**Comment by linquize** [comment]
`find_package(FreeRDP CONFIG REQUIRED)` will cause

```
CMake Error at C:/vcpkg/installed/x64-windows/share/freerdp/FreeRDPConfig.cmake:12 (message):
File or directory C:/vcpkg/installed/x64-windows/include/freerdp2/ referenced by variable FreeRDP_INCLUDE_DIR does not exist !
```

**Comment by VelocityRa** [comment]
Huh? Works fine for me. Maybe you forgot to set `VCPKG_DEFAULT_TRIPLET`?

**Comment by VelocityRa** [comment]
Btw, with the following I can get this to work with:
```cmake
target_include_directories(myproj PUBLIC "C:/vcpkg/installed/x64-windows/include/freerdp2/freerdp")
target_include_directories(myproj PUBLIC "C:/vcpkg/installed/x64-windows/include/winpr2")
```
(obviously not a long term solution)

**Comment by VelocityRa** [comment]
Never mind, was fixed by https://github.com/microsoft/vcpkg/pull/9944.

**Comment by linquize** [comment]
Is it really fixed? the commit is one month ago.
And I tested yesterday master.

**Comment by VelocityRa** [comment]
I tested yesterday's master too and it works.
