### ISSUE TITLE
[New Port Request]  ortools

### ISSUE THREAD

**Issue by xarthurx** [microsoft/vcpkg#10424]
Library name: ortools

Library description:
OR-Tools is an open source software suite for optimization, tuned for tackling the world's toughest problems in vehicle routing, flows, integer and linear programming, and constraint programming.

After modeling your problem in the programming language of your choice, you can use any of a half dozen solvers to solve it: commercial solvers such as Gurobi or CPLEX, or open-source solvers such as SCIP, GLPK, or Google's GLOP and award-winning CP-SAT.

Source repository URL:
https://github.com/google/or-tools

Project homepage (if different from the source repository):
https://developers.google.com/optimization

**Comment by linquize** [comment]
Blocker: create new port **cbc** first.
https://github.com/coin-or/Cbc

**Comment by linquize** [comment]
Blocker: ortools has dependency **cbc**. So create new port **cbc** first. See #10425

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by FishHe** [comment]
OR-Tools is useful, why not import?

**Comment by PhoebeHui** [comment]
@FishHe, if you're interest in adding this port to vcpkg, please create a PR firstly, we would help reopen this issue, currently this is not usual scenario we're working on now, but we accept PRs for supporting new port.

**Comment by flomnes** [comment]
https://vcpkg.io/en/package/coin-or-cbc cbc now has a port !
