### ISSUE TITLE
[bfgroup-lyra] update to <1.3>

### ISSUE THREAD

**Issue by skyshaver** [microsoft/vcpkg#10435]
Library name: bfgroup-lyra

New version number: 1.4

Other information that may be useful (release notes, etc...)

**Comment by PhoebeHui** [comment]
@skyshaver, thanks for bringing this up.

I noticed the latest release revision is [1.3](https://github.com/bfgroup/Lyra/releases) , so I update it to 1.3.

**Comment by PhoebeHui** [comment]
The PR has been merged, please get latest source and try again.
