### ISSUE TITLE
bootstrap-vcpkg.bat can't find bootstrap.ps1

### ISSUE THREAD

**Issue by jprochazk** [microsoft/vcpkg#10432]
**Describe the bug**
The bootstrap .bat file cannot find the powershell script under the "scripts" directory. I had to run the bootstrap.ps1 script with powershell manually, by opening powershell, cd into vcpkg and running scripts/bootstrap.ps1. After I did this, the build succeeded without errors. I am a first time user, so I'm not sure if I did something wrong.

**Environment**
- OS: Windows 10

**To Reproduce**
1. clone the repo
2. run bootstrap-vcpkg.bat

**Expected behavior**
The build should have happened normally

**Failure logs** 
```
& : The module '%~dp0scripts' could not be loaded. For more information, run 'Import-Module %~dp0scripts'.
At line:1 char:6
+ & {& '%~dp0scripts\bootstrap.ps1' %*}
+      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (%~dp0scripts\bootstrap.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoLoadModule
```

**Comment by NancyLi1013** [comment]
Hi @jprochazk 
Thanks for posting this issue.
Could you please help confirm if you have `cd `into vcpkg before you run ` bootstrap-vcpkg.bat`?
The correct steps are as like this:
```
> git clone https://github.com/Microsoft/vcpkg.git
> cd vcpkg

PS> .\bootstrap-vcpkg.bat
```

**Comment by jprochazk** [comment]
Hello @NancyLi1013, thank you for the response. I can no longer reproduce the issue. I think it's just as you've said, I was in ```cd```'d into the wrong directory.
