### ISSUE TITLE
[New Port Request] libfortrt

### ISSUE THREAD

**Issue by Voskrese** [microsoft/vcpkg#10440]
Library name: libfortrt

Library description: Runtime library for Fort compiler. Libfortrt is a new implementation of the Fortran runtime library.

Libfortrt is the runtime library for fort (the Fortran frontend for LLVM,
https://github.com/llvm-fortran/fort). It can be used by any other Fortran
compiler.

Source repository URL: https://github.com/llvm-fortran/libfortrt

deps: Fort
https://github.com/microsoft/vcpkg/issues/10439

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
