### ISSUE TITLE
[<boost-build:x64-osx] build failure

### ISSUE THREAD

**Issue by x11562** [microsoft/vcpkg#10454]
**Host Environment**
- OS: mac
- Compiler: revision

**To Reproduce**
`./vcpkg install boost`

**Failure logs** 
Starting package 11/148: boost-build:x64-osx
Building package boost-build[core]:x64-osx...
-- Using cached /Users/xiena/code/github/vcpkg/downloads/boostorg-build-boost-1.72.0.tar.gz
-- Using source at /Users/xiena/code/github/vcpkg/buildtrees/boost-build/src/ost-1.72.0-fa8b817276
-- Using cached /Users/xiena/code/github/vcpkg/downloads/boost_LICENSE_1_0.txt
-- Using cached /Users/xiena/code/github/vcpkg/downloads/boost-1.72.0-boostcpp.jam
-- Installing: /Users/xiena/code/github/vcpkg/packages/boost-build_x64-osx/share/boost-build/copyright
-- Installing: /Users/xiena/code/github/vcpkg/packages/boost-build_x64-osx/tools/boost-build/boostcpp.jam
-- Bootstrapping...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: /Users/xiena/code/github/vcpkg/packages/boost-build_x64-osx/tools/boost-build/bootstrap.sh
    Working Directory: /Users/xiena/code/github/vcpkg/packages/boost-build_x64-osx/tools/boost-build
    Error code: 1
    See logs for more information:
      /Users/xiena/code/github/vcpkg/buildtrees/boost-build/bootstrap-x64-osx-out.log

Call Stack (most recent call first):
  ports/boost-build/portfile.cmake:61 (vcpkg_execute_required_process)
  scripts/ports.cmake:90 (include)

Error: Building package boost-build:x64-osx failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-build:x64-osx
  Vcpkg version: 2020.02.04-unknownhash

Additionally, attach any relevant sections from the log files above.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by LilyWangL** [comment]
@x11562 Thanks for posting this issue. Please provide the error log: 
`/Users/xiena/code/github/vcpkg/buildtrees/boost-build/bootstrap-x64-osx-out.log`.

**Comment by x11562** [comment]
> @x11562 Thanks for posting this issue. Please provide the error log:
> `/Users/xiena/code/github/vcpkg/buildtrees/boost-build/bootstrap-x64-osx-out.log`.

I'm sorry，
 I updated the mac operating system, it's OK

**Comment by LilyWangL** [comment]
This issue has been solved, so I am closing this issue for now.
