### ISSUE TITLE
Error in macOS 10.15 Catalina: ninja: build stopped: subcommand failed

### ISSUE THREAD

**Issue by jsmjsm** [microsoft/vcpkg#10458]
**Describe the bug**

**Environment**
- OS: [macOS 10.15 Catalina]

**To Reproduce**
1.  ./bootstrap-vcpkg.sh
2.  See error

📚 **Failure logs** 
```
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/unistd.h:525,
                 from ../include/pch.h:19,
                 from ../src/vcpkg/base/files.cpp:1:
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_ctermid.h:26:10: note: previous declaration with 'C++' linkage
   26 | char    *ctermid(char *);
      |          ^~~~~~~
ninja: build stopped: subcommand failed.
```

🔨 **Feasible solution**
Using this cmd to build
`@ CXXFLAGS="-D_CTERMID_H_" ./bootstrap-vcpkg.sh`

Same Problem in macOS 10.14 Mojave, see: https://github.com/microsoft/vcpkg/issues/9029

Hope can fix this bug or giving guidance.

**Comment by NancyLi1013** [comment]
Thanks for posting this issue.
It's duplicated to #8670.
