### ISSUE TITLE
[New Port Request] libtomcrypt, libtommath

### ISSUE THREAD

**Issue by mupchurch-verys** [microsoft/vcpkg#10466]
Library name: libtomcrypt, libtommath

Library description:

LibTomCrypt is a fairly comprehensive, modular and portable cryptographic toolkit that provides developers with a vast array of well known published block ciphers, one-way hash functions, chaining …

Source repository URL:
https://github.com/libtom/libtomcrypt
https://github.com/libtom/libtommath

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
libtomcrypt depends on libtommath (which is why i included it)

**Comment by Sil3ntStorm** [comment]
See #8787

**Comment by LilyWangL** [comment]
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.
