### ISSUE TITLE
[restbed] SSL not enabled

### ISSUE THREAD

**Issue by danieljpb** [microsoft/vcpkg#10464]
**Describe the bug**
When run with ssl enabled, exit with std::runtime_error

**Environment**
- OS:  Windows
- Compiler: MSVC++ 14.16

**To Reproduce**
1. ./vcpkg install restbed
2. See error
Compile this example and run:
https://github.com/Corvusoft/restbed/blob/master/documentation/example/HTTPS_SERVICE.md

**Comment by PhoebeHui** [comment]
@danieljpb, sorry for my late reply.

Could you try to install restbed with openssl feature? the command is './vcpkg install restbed[openssl]'.

**Comment by PhoebeHui** [comment]
Please reopen this issue if it still be a problem for you.
