### ISSUE TITLE
Add FANN

### ISSUE THREAD

**Issue by lindevs** [Microsoft/vcpkg#1046]
Fast Artificial Neural Network Library is a free open source neural network library, which implements multilayer artificial neural networks in C with support for both fully connected and sparsely connected networks.
[https://github.com/libfann/fann](https://github.com/libfann/fann)

**Comment by JackBoosY** [comment]
same with #1046
pr: #5290

**Comment by JackBoosY** [comment]
Hi @lindevs Fann has been added to the port now. Enjoy it!

**Comment by lindevs** [comment]
@JackBoosY thanks.
