### ISSUE TITLE
[New Port Request] Skyr URL

### ISSUE THREAD

**Issue by glynos** [microsoft/vcpkg#10462]
Library name: Skyr URL

Library description: A C++ library that implements the WhatWG URL specification

Source repository URL: https://github.com/cpp-netlib/url

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by glynos** [comment]
I created a PR for this issue: https://github.com/microsoft/vcpkg/pull/10463

**Comment by LilyWangL** [comment]
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.
