### ISSUE TITLE
[pcl] build failure on Ubuntu 18.04

### ISSUE THREAD

**Issue by christianlandgraf** [microsoft/vcpkg#10461]
**Host Environment**
- OS:Ubuntu 18.04
- Compiler: tried with gcc-7.5 und gcc-9

**Steps to reproduce the behavior:**
`./vcpkg install pcl:x64-linux`

**Failure logs** 
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: /home/chl/Software/vcpkg/downloads/tools/cmake-3.14.0-linux/cmake-3.14.0-Linux-x86_64/bin/cmake --build . --config Debug --target install -- -v
    Working Directory: /home/chl/Software/vcpkg/buildtrees/pcl/x64-linux-dbg
    See logs for more information:
      /home/chl/Software/vcpkg/buildtrees/pcl/install-x64-linux-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/pcl/portfile.cmake:53 (vcpkg_install_cmake)
  scripts/ports.cmake:90 (include)

Error: Building package pcl:x64-linux failed with: BUILD_FAILED

Log File:
[install-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/4350448/install-x64-linux-dbg-out.log)

**Additional context**
I also tried to install the patch provided in pull request #9231 but it did not help. I use the latest vcpkg version.

**Comment by NancyLi1013** [comment]
Hi @christianlandgraf 
Thanks for posting this issue.
It seems that there is no enough space left in your local machine.
```
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
```
Could you please check it first?

**Comment by christianlandgraf** [comment]
Thanks for the quick rsponse @NancyLi1013 . There are about 98gb left on my machine, according to gparted and other tools.

**Comment by christianlandgraf** [comment]
It worked today, I suspect it was because of missing CPU capacity.
