### ISSUE TITLE
why does the static method .takeVacationDays(5); return Nan

### ISSUE THREAD

**Issue by Jose7136** [microsoft/vcpkg#10475]
why does it return NaN when using static on this._remainingVacationDays, but i remove the static and rather use an instance of a class it does work please help!!).
```
class HospitalEmployee {
  constructor(name) {
    this._name = name;
    this._remainingVacationDays = 20;
  }
  
  get name() {
    return this._name;
  }
  
  get remainingVacationDays() {
    return this._remainingVacationDays;
  }
  
  static takeVacationDays(Dayoff) {
    return this._remainingVacationDays -= Dayoff;
  }
  static generatePassword() {
    return Math.floor(Math.random() * 10000)
  }
}

class Nurse extends HospitalEmployee {
  constructor(name, certifications) {
    super(name);
    this._certifications = certifications;
  } 
  
  get certifications() {
    return this._certifications;
  }
  
  addCertification(newCertification) {
    this.certifications.push(newCertification);
  }
}


console.log(HospitalEmployee.takeVacationDays(5));
```

**Comment by PhoebeHui** [comment]
@Jose7136, which port do you use? could you alos provide us the compiler revision?

**Comment by Jose7136** [comment]
Im learning how to code and this is just an exercise on codecademy, the thing is that im trying to convey the takeVacationDays method to static and call it within the HospitalEmployee class since it is static, however it returns NAN when it should return a number, if you remove the static word from takeVacationDays and use an instance of a class it does work. This is the link to that exercise thanks: https://www.codecademy.com/courses/introduction-to-javascript/lessons/classes/exercises/static-methods

If you remove static from takeVacationDays and use an instance of a class like below it does work.
For example:
const nurseOlynyk = new Nurse(8);
console.log(nurseOlynyk.takeVacationDays(5));

**Comment by Neumann-A** [comment]
This has nothing to do with vcpkg...... close this issue
..... please move your question to stackoverflow. (C#?)

static methods don't act on the instance itself but on the class. As such the `this` pointer is not accessible although I don't know why the compiler lets you do such nonsense in whatever language you are using here
