### ISSUE TITLE
Error when compiling with the Arduino Uno  - IBM_lmic framework

### ISSUE THREAD

**Issue by Fratasch** [microsoft/vcpkg#10481]
There is a problem withe the IBM_lmic ?
can anyone help me with this? 

![Bildschirmfoto 2020-03-20 um 08 39 04](https://user-images.githubusercontent.com/62419217/77144705-e2b69580-6a86-11ea-8153-bd385d69e3bc.jpeg)

Thank You!!

**Comment by NancyLi1013** [comment]
Hi @Fratasch 
Thanks for posting this issue.
Could you please help provide the steps to reproduce?
