### ISSUE TITLE
Don't find package unofficial-nana

### ISSUE THREAD

**Issue by Darkcacok** [microsoft/vcpkg#10480]
Severity	Code	Description	Project	File	Line	Suppression State
Error		CMake Error at src/CMakeLists.txt:9 (find_package):
  Could not find a package configuration file provided by "unofficial-nana"
  with any of the following names:

    unofficial-nanaConfig.cmake
    unofficial-nana-config.cmake

  Add the installation prefix of "unofficial-nana" to CMAKE_PREFIX_PATH or
  set "unofficial-nana_DIR" to a directory containing one of the above files.
  If "unofficial-nana" provides a separate development package or SDK, be
  sure it has been installed.

**Comment by linquize** [comment]
Try this

```cmake
cmake_minimum_required(VERSION 3.10)
project(main)
add_executable(main main.cpp)
find_package(unofficial-nana CONFIG REQUIRED)
target_link_libraries(main PRIVATE unofficial::nana::nana)
```

**Comment by Darkcacok** [comment]
This work only on windows, but on ubuntu 18.04 don't.

**Comment by linquize** [comment]
What is your error on Linux?

**Comment by linquize** [comment]
On Linux, you have to build nana as dynamic library (see #10078), then when you use it in your `CMakeLists.txt`, add
```cmake
set(VCPKG_TARGET_TRIPLET "x64-linux-dynamic")
```

**Comment by linquize** [comment]
On Linux, you have to build nana as dynamic library (see #10078), then when you use it in your cmake project, run
`cmake -DVCPKG_TARGET_TRIPLET=x64-linux-dynamic`

**Comment by linquize** [comment]
I use Ubuntu 18.04 + gcc 7

**Comment by Darkcacok** [comment]
CMake Warning at /home/test/vcpkg/scripts/buildsystems/vcpkg.cmake:126 (message):
  There are no libraries installed for the Vcpkg triplet x64-linux-dynamic.
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/CMakeDetermineSystem.cmake:94 (include)
  CMakeLists.txt:11 (project)


-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /home/test/vcpkg/scripts/buildsystems/vcpkg.cmake:288 (_find_package):
  Could not find a package configuration file provided by "unofficial-nana"
  with any of the following names:

    unofficial-nanaConfig.cmake
    unofficial-nana-config.cmake

  Add the installation prefix of "unofficial-nana" to CMAKE_PREFIX_PATH or
  set "unofficial-nana_DIR" to a directory containing one of the above files.
  If "unofficial-nana" provides a separate development package or SDK, be
  sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:18 (find_package)

**Comment by Darkcacok** [comment]
test@lubuntu:~/vcpkg$ ./vcpkg list
bzip2:x64-linux                                    1.0.6-5          High-quality data compressor.
dirent:x64-linux                                   1.23.2           Dirent is a C/C++ programming interface that all...
expat:x64-linux                                    2.2.7            XML parser library written in C
fontconfig:x64-linux                               2.12.4-10        Library for configuring and customizing font acc...
freetype:x64-linux                                 2.10.1-5         A library to render fonts.
freetype[bzip2]:x64-linux                                           Support bzip2 compressed fonts.
freetype[png]:x64-linux                                             Support PNG compressed OpenType embedded bitmaps.
libiconv:x64-linux                                 1.16-1           GNU Unicode text conversion
libjpeg-turbo:x64-linux                            2.0.4            libjpeg-turbo is a JPEG image codec that uses SI...
libpng:x64-linux                                   1.6.37-6         libpng is a library implementing an interface fo...
zlib:x64-linux                                     1.2.11-6         A compression library

**Comment by Darkcacok** [comment]
> I use Ubuntu 18.04 + gcc 7

Lubuntu 18.04

**Comment by Darkcacok** [comment]
cmake -DCMAKE_TOOLCHAIN_FILE=/home/test/vcpkg/scripts/buildsystems/vcpkg.cmake ..
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found Freetype: /home/test/vcpkg/installed/x64-linux/lib/libfreetype.a (found version "2.10.1") 
-- Found ZLIB: /home/test/vcpkg/installed/x64-linux/debug/lib/libz.a (found version "1.2.11") 
-- Found BZip2: /home/test/vcpkg/installed/x64-linux/lib/libbz2.a (found version "1.0.6") 
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- Found PNG: /home/test/vcpkg/installed/x64-linux/debug/lib/libpng.a (found version "1.6.37") 
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- Found JPEG: /home/test/vcpkg/installed/x64-linux/debug/lib/libjpeg.a  
CMake Error at /home/test/vcpkg/installed/x64-linux/share/unofficial-nana/unofficial-nana-config.cmake:45 (target_link_libraries):
  Cannot specify link libraries for target "unofficial::nana::nana" which is
  not built by this project.
Call Stack (most recent call first):
  /home/test/vcpkg/scripts/buildsystems/vcpkg.cmake:288 (_find_package)
  CMakeLists.txt:18 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/test/Desktop/724942d43cd11c6ee5b3461ac067c846-e6e86199bd2e7151cd9608dd0719a69daa303243/build/CMakeFiles/CMakeOutput.log".
See also "/home/test/Desktop/724942d43cd11c6ee5b3461ac067c846-e6e86199bd2e7151cd9608dd0719a69daa303243/build/CMakeFiles/CMakeError.log".

**Comment by Darkcacok** [comment]
https://mega.nz/#!G88iiQxS!f5DgGc44RV4yrlHZnrGwZlkuQ7Z3_RJjAEOAx1kjdKU
https://mega.nz/#!vps0jIBZ!d_6jaKA_KtfTbtycMfZwoDLmF0jLexF-6KCVkx7f_IM

**Comment by LilyWangL** [comment]
@Darkcacok Did you install nana successfully on your Linux machine?

**Comment by Darkcacok** [comment]
> @Darkcacok Did you install nana successfully on your Linux machine?

Yes. I tried this on my machine and in clear virtual machine.

**Comment by LilyWangL** [comment]
@Darkcacok Thanks for posting this issue. The version of cmake which is installed by Linux is low, you can use cmake which is installed by VCPKG. The command is:
**_VCPKG_PATH_**/downloads/tools/cmake-3.14.0-linux/cmake-3.14.0-Linux-x86_64/bin/cmake -DCMAKE_TOOLCHAIN_FILE=**_VCPKG_PATH_**/scripts/buildsystems/vcpkg.cmake CMakeLists.txt

**Comment by Darkcacok** [comment]
> @Darkcacok Thanks for posting this issue. The version of cmake which is installed by Linux is low, you can use cmake which is installed by VCPKG. The command is:
> **_VCPKG_PATH_**/downloads/tools/cmake-3.14.0-linux/cmake-3.14.0-Linux-x86_64/bin/cmake -DCMAKE_TOOLCHAIN_FILE=**_VCPKG_PATH_**/scripts/buildsystems/vcpkg.cmake CMakeLists.txt
Thank you for your time. This is resolved using the new version of cmake. 

But now I have another issue. 
/home/maxim/Projects/vcpkg/scripts/buildsystems/vcpkg.cmake:186: error: Target "gui" links to target "PNG::PNG" but the target was not found. Perhaps a find_package() call is missing for an IMPORTED target, or an ALIAS target is missing? src/application/CMakeLists.txt:13 (add_executable)

**Comment by LilyWangL** [comment]
Could you please provide the repro code?

**Comment by Darkcacok** [comment]
https://gist.github.com/caiorss/724942d43cd11c6ee5b3461ac067c846
I replaced the cmake version with my own and the path to the toolchane.

This error occurs when this cmake file depends from another cmake file. For some reason cmake does not use libpng, which is downloaded using vcpkg.

When I compile this project separately, another error occurs. I think it is connected with the same.

```
/usr/bin/ld: /home/maxim/Projects/vcpkg/installed/x64-linux/lib/libfontconfig.a(fcfreetype.c.o): undefined reference to symbol 'FT_Get_Postscript_Name'
//usr/lib/x86_64-linux-gnu/libfreetype.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/gui1.dir/build.make:103: recipe for target 'gui1' failed
make[2]: *** [gui1] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/gui1.dir/all' failed
make[1]: *** [CMakeFiles/gui1.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by Darkcacok** [comment]
Please help me https://github.com/Darkcacok/vcpkg/pull/1

**Comment by NancyLi1013** [comment]
Sorry for the long delay.

It seems that the original issue has been solved.
Please open a new issue if you have other concerns @Darkcacok.
