### ISSUE TITLE
[New Port Request] ITensor

### ISSUE THREAD

**Issue by shencebebetterme** [microsoft/vcpkg#10487]
Library name: ITensor

Library description:  C++ library for implementing tensor network calculations

Source repository URL: https://github.com/ITensor/ITensor

Project homepage (if different from the source repository): http://itensor.org/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
