### ISSUE TITLE
[New Port Request] <Tengine>

### ISSUE THREAD

**Issue by yuenar** [microsoft/vcpkg#10482]
Library name: Tengine

Library description:

> Tengine, developed by OPEN AI LAB, is an AI application development platform for AIoT scenarios launched by OPEN AI LAB, which is dedicated to solving the fragmentation problem of aiot industrial chain and accelerating the landing of AI industrialization. Tengine is specially designed for AIoT scenarios, and it has several features, such as cross platform, heterogeneous scheduling, chip bottom acceleration, ultra light weight and independent, and complete development and deployment tool chain. Tengine is compatible with a variety of operating systems and deep learning algorithm framework, which simplifies and accelerates the rapid migration of scene oriented AI algorithm on embedded edge devices, as well as the actual application deployment;

Source repository URL:https://github.com/OAID/Tengine

Project homepage (if different from the source repository):http://www.tengine.org.cn/

Anything else that is useful to know when adding (such as optional features the library may have that should be included): **tengine is useful library when crosscompile**

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
