### ISSUE TITLE
plibsys

### ISSUE THREAD

**Issue by BEMfreshman** [microsoft/vcpkg#10498]
**Describe the bug**
After installing plibsys and integrated into all VS project, compilation of any C file will be terminated because compiler fail to located pmacros.h which is included in plibsysconfig.h. 
**Environment**
- OS:Windows
- Compiler:MSVC141 (VS 2017)

**To Reproduce**
1. ./vcpkg install plibsys
2. build project in VS and include "plibsys/plibsys.h". Any code will fail.
Repro code when

**Expected behavior**
I hope you could find out why and fix it if you could.

**Comment by LilyWangL** [comment]
@BEMfreshman Thanks for posting this issue. You could use `find_library` to use plibsys in your project. I created an empty CMakeProject and added these codes in CMakeLists.txt, the project built successfully. 
My CMakeLists.txt:
```
cmake_minimum_required (VERSION 3.8)
add_executable (CMakeProject "CMakeProject.cpp" "CMakeProject.h")

find_path(PLIBSYS_INCLUDE_DIR plibsys.h)
find_library(PLIBSYS_LIBRARY plibsys.lib)
include_directories(${PLIBSYS_INCLUDE_DIR})
target_link_libraries(CMakeProject16 PUBLIC ${PLIBSYS_LIBRARY})
```
My CMakeProject.cpp
```
#include "CMakeProject16.h"
#include "plibsys.h"
using namespace std;
int main()
{
	cout << "Hello CMake." << endl;
	return 0;
}
```

**Comment by linquize** [comment]
Try
`find_path(PLIBSYS_INCLUDE_DIR plibsys.h PATH_SUFFIXES plibsys)`

**Comment by BEMfreshman** [comment]
Thank you for your response.

I will try your solution later.
