### ISSUE TITLE
[hunspell] build failure within VS 2019 prompt

### ISSUE THREAD

**Issue by wangqr** [microsoft/vcpkg#10492]
**Host Environment**
- OS: Windows 10.0.18363.720
- Compiler: VS 2019

**To Reproduce**
`./vcpkg install hunspell --triplet x64-windows`

**Failure logs** 
```
Computing installation plan...
The following packages will be built and installed:
    hunspell[core]:x64-windows
Starting package 1/1: hunspell:x64-windows
Building package hunspell[core]:x64-windows...
-- Using cached C:/Users/wangqr/Files/src/vcpkg/downloads/hunspell-hunspell-v1.7.0.tar.gz
-- Extracting source C:/Users/wangqr/Files/src/vcpkg/downloads/hunspell-hunspell-v1.7.0.tar.gz
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/bin/cmake.exe" -E tar xjf C:/Users/wangqr/Files/src/vcpkg/downloads/hunspell-hunspell-v1.7.0.tar.gz
    Working Directory: C:/Users/wangqr/Files/src/vcpkg/buildtrees/hunspell/src/TEMP
    Error code: 1
    See logs for more information:
      C:\Users\wangqr\Files\src\vcpkg\buildtrees\hunspell\extract-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_extract_source_archive.cmake:43 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_extract_source_archive_ex.cmake:108 (vcpkg_extract_source_archive)
  scripts/cmake/vcpkg_from_github.cmake:139 (vcpkg_extract_source_archive_ex)
  ports/hunspell/portfile.cmake:3 (vcpkg_from_github)
  scripts/ports.cmake:90 (include)


Error: Building package hunspell:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: hunspell:x64-windows
  Vcpkg version: 2020.02.04-nohash-external

Additionally, attach any relevant sections from the log files above.
```
* `C:\Users\wangqr\Files\src\vcpkg\buildtrees\hunspell\extract-err.log`
```
CMake Error: Problem with archive_write_header(): Can't create ''
CMake Error: Current file: hunspell-1.7.0/README
CMake Error: Problem extracting tar: C:/Users/wangqr/Files/src/vcpkg/downloads/hunspell-hunspell-v1.7.0.tar.gz
```

**Additional context**
7-zip can open and extract `hunspell-hunspell-v1.7.0.tar.gz` without issue.

**Comment by linquize** [comment]
Clean everything and try again

**Comment by wangqr** [comment]
I have fresh cloned vcpkg from a5a244f5bdc390fc1c3d42e126e0bfd80541f060 and the issue is the same.

Full stdout at https://paste.ubuntu.com/p/xHnKgYZxCX/

**Comment by linquize** [comment]
Did you use **VS2019 command prompt ** or just ordinary **Windows Command Prompt** to run `vcpkg install hunspell`?

**Comment by wangqr** [comment]
I was using **VS2019 command prompt (x64 native)**. Just tried **ordinary Windows Command Prompt** and it does work fine. Is this expected?

**Comment by linquize** [comment]
When you use **VS2019 command prompt**, **CMake** that comes with **Visual Studio** will be used because `cmake` is in `%PATH%`.
When ordinary **Windows Command Prompt** is used, **CMake** that downloaded by **vcpkg** will be used. This is always the version that works correctly.

**Comment by linquize** [comment]
MSVC 16.5.0 ships CMake 3.16.
vcpkg downloads CMake 3.14.
CMake 3.16 is known to breaks some packages, so in the mean time, use CMake 3.14.

**Comment by wangqr** [comment]
When running in cmd, it actually uses the CMake that I installed. I've logged out `${CMAKE_COMMAND}`, and it is `C:/Program Files/CMake/bin/cmake.exe`. The version of that CMake is 3.17.0.

**Comment by linquize** [comment]
Also problematic with cmake 3.17. Could you try to temporarily, either
1. move your `C:/Program Files/CMake/bin/cmake.exe` to somewhere else; or
2. modify %PATH% to remove `C:\Program Files\CMake\bin``%PATH%`

so that it does not find `cmake` in `%PATH%`

**Comment by wangqr** [comment]
No, I mean it is working normally with CMake 3.17

**Comment by Cheney-W** [comment]
@wangqr Dose this issue still occur when using a PowerShell window to install hunspell:x64-windows?

**Comment by linquize** [comment]
But your log says cmake is in program files

**Comment by wangqr** [comment]
Output of `vcpkg.exe install hunspell:x64-windows --debug`: https://paste.ubuntu.com/p/FW8yzHSw5b/
If I run it from plain PowerShell, it success: https://paste.ubuntu.com/p/yYj4bvyFch/
If I start PowerShell from VS 2019 prompt, it fails: https://paste.ubuntu.com/p/jxQzM4ytNp/

> But your log says cmake is in program files

The log says failed command is `C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/bin/cmake.exe` so I think it is the one provided by VS. And VS is installed in program files.

**Comment by Cheney-W** [comment]
@wangqr What's the version of the C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/bin/cmake.exe?

**Comment by wangqr** [comment]
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community>"C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/bin/cmake.exe" --version
cmake version 3.16.19112601-MSVC_2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

**Comment by Cheney-W** [comment]
This is a cmake bug, and I think it has been fixed in 3.17.0, because your issue disappeared with your `C:\Program Files\CMake\bin\cmake.exe` (cmake version 3.17.0)

**Comment by wangqr** [comment]
In that case, can VS upgrade the bundled CMake?

**Comment by Cheney-W** [comment]
I think you could send a feedback to Visual Studio. Please refer to this: https://developercommunity.visualstudio.com/content/problem/post.html?space=8

**Comment by wangqr** [comment]
https://developercommunity.visualstudio.com/content/problem/964144/cmake-bundled-in-vs1029-breaks-vcpkg-problem-with.html

**Comment by Cheney-W** [comment]
Thank you!
