### ISSUE TITLE
[cppcms] build failure

### ISSUE THREAD

**Issue by how0723** [microsoft/vcpkg#10493]
**Host Environment**
- OS: linux/debian x64
- Compiler: gcc 8.3

**To Reproduce**
`root@unique-gig-2:/home/vcpkg-2020.01# vcpkg install cppcms
-bash: vcpkg: command not found
root@unique-gig-2:/home/vcpkg-2020.01# ./vcpkg install cppcms
The following packages will be built and installed:
    cppcms[core]:x64-linux
Starting package 1/1: cppcms:x64-linux
Building package cppcms[core]:x64-linux...
-- Note: cppcms only supports dynamic library linkage. Building dynamic library.
-- Using cached /home/vcpkg-2020.01/downloads/artyom-beilis-cppcms-b72b19915794d1af63c9a9e9bea58e20a4ad93d4.tar.gz
-- Extracting source /home/vcpkg-2020.01/downloads/artyom-beilis-cppcms-b72b19915794d1af63c9a9e9bea58e20a4ad93d4.tar.gz
-- Using source at /home/vcpkg-2020.01/buildtrees/cppcms/src/20a4ad93d4-26c9d29282
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
CMake Error at ports/cppcms/portfile.cmake:25 (file):
  file must be called with at least two arguments.
Call Stack (most recent call first):
  scripts/ports.cmake:94 (include)

Error: Building package cppcms:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: cppcms:x64-linux
  Vcpkg version: 2020.01.17-unknownhash
`

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by PhoebeHui** [comment]
@how0723, thanks for reporting this issue.
 
It seems that cppcms doesn't support on linux in vcpkg, It looks it's a source issue in upstream. 
I will add a failure message to cppcms in vcpkg.
