### ISSUE TITLE
[expat] Not automatically copy expat.dll in debug mode

### ISSUE THREAD

**Issue by lambdald** [microsoft/vcpkg#10497]
OS: Windows 10 verion 1909
IDE: Microsoft Visual Studio Professional 2019 version 16.4.6

In debug mode, expat can be linked correctly. When running the .exe file of my project, an error will be prompted. The error was that "expat.dll is missing", even though it was in debug mode. As far as I know, the debug version of the dll file should end with ’d’ and can be copied to work directory automatically.

**Comment by NancyLi1013** [comment]
Hi @lambdald 
Thanks for posting this issue.
I try to build this on my local with Visual Studio 2019 16.5.0.
I can build it successfully and execute .exe project without any error.
Could you please provide your project case and post the error log?

**Comment by NancyLi1013** [comment]
Please feel free to reopen it if this is still a problem for you.
