### ISSUE TITLE
How do I get macOS dSYM files generated for a port?

### ISSUE THREAD

**Issue by christophe-calmejane** [microsoft/vcpkg#10491]
I'm trying to add a port for an internal library but it fails during install phase. The library has cmake install rules that want to install dSYM files.

When building the library with default cmake tools on macOS, the dSYM are generated thanks to this command:
`			set_target_properties(${TARGET_NAME} PROPERTIES
				XCODE_ATTRIBUTE_DEBUG_INFORMATION_FORMAT[variant=Debug] "dwarf-with-dsym"
				XCODE_ATTRIBUTE_DEBUG_INFORMATION_FORMAT[variant=Release] "dwarf-with-dsym"
				XCODE_ATTRIBUTE_DEPLOYMENT_POSTPROCESSING[variant=Debug] "YES"
				XCODE_ATTRIBUTE_DEPLOYMENT_POSTPROCESSING[variant=Release] "YES"
			)
`

If I understand correctly how vcpkg works, it's not using cmake's `Xcode generator` but `Ninja generator`.

**1. Would that be the reason why I don't have dSYM generated in the build folder?**

**2. Are the debug symbols kept in the dylib/dll?**

**3. How then can I generate the dSYM files on macOS (using ninja)?**

Thanks for your help.

**Comment by christophe-calmejane** [comment]
Ok looks like I found the answers myself (I hope!)

1. The XCODE_ATTRIBUTE I have in my CMakeLists.txt is ignored by Ninja. Xcode is generating the dSYM files using a program named `dsymutil`

2. Looks like all debug symbols are present in the generated binary

3. A simple test like this appears to be doing what I need:
- build binaries with `-g` flag
- call `dsymutil` on the binary as post build step
- call `strip -x` on binary as post build step

So I guess I have to update my projects to support Ninja natively.

**Comment by LilyWangL** [comment]
Thanks for your issue. It's very useful for other users who need use dSYM files. This issue has been solved, so I am closing this issue for now.

**Comment by Sunbreak** [comment]
An example if anyone interested: https://github.com/Sunbreak/cli-breakpad.trial#use-breakpad-for-cli-breakpad

# Use breakpad for cli-breakpad

## Build & Run cli-breakpad

### macOS

```sh
$ cmake -S . -Bbuild -DCMAKE_BUILD_TYPE=RelWithDebInfo
$ cmake --build build
$ ./build/cli-breakpad
dump_dir: .
minidump_id: 64C31053-BBE4-400C-9588-B29F63E08E71
```

## Dump info for cli-breakpad

### macOS

```sh
$ dsymutil ./build/cli-breakpad -o cli-breakpad.dSYM
$ ./breakpad/mac/dump_syms cli-breakpad.dSYM > cli-breakpad.sym
$ uuid=`awk 'FNR==1{print \$4}' cli-breakpad.sym`
$ mkdir -p symbols/cli-breakpad/$uuid/
$ mv ./cli-breakpad.sym symbols/cli-breakpad/$uuid/
$ ./breakpad/mac/$(arch)/minidump_stackwalk 64C31053-BBE4-400C-9588-B29F63E08E71.dmp symbols > cli-breakpad.log
```
