### ISSUE TITLE
Why do not the port make the same way to be linked?

### ISSUE THREAD

**Issue by zh1an** [microsoft/vcpkg#10509]
When asking a question please also include where you looked for an answer (so we can update the documentation if needed).
When I use many ports in my project, there aways are different way to link these ports. Some library do not provide the way that use `target_link_library()` to link themself, so I must use ${VcpkgRoot} directory to link them or add include directory, but then some header-only library will be link many times and this is invalid.
So, is the way that I link library wrong and how do I do? If this is that right, Why do not the port make the same way to be linked?

**Comment by JackBoosY** [comment]
Because some ports do **NOT** support exporting cmake files(config.cmake/targets.cmake etc.), we can **NOT** directly use `find_package` and `target_link_libraries` to use this port.
In this case, we need to use `find_library` and `find_path` based on the header files and libraries generated by the port. and then use `target_link_libraries`.

**Comment by zh1an** [comment]
> Because some ports do **NOT** support exporting cmake files(config.cmake/targets.cmake etc.), we can **NOT** directly use `find_package` and `target_link_libraries` to use this port.
> In this case, we need to use `find_library` and `find_path` based on the header files and libraries generated by the port. and then use `target_link_libraries`.

Thanks, I will learn `find_library` and `find_path` .

**Comment by JackBoosY** [comment]
@zh1an For example:
Port `ALIB` generated header file `a.h` in _include/ALIB_ and `A.lib` in _lib_.
You can use the following codes:
```
find_path(A_INCLUDE_DIR a.h PATH_SUFFIXES ALIB)
find_library(ALIB A required)

target_include_directories(main PRIVATE ${A_INCLUDE_DIR})
target_link_libraries(main PRIVATE ALIB)
```
