### ISSUE TITLE
[New Port Request] Copperspice

### ISSUE THREAD

**Issue by AMS21** [microsoft/vcpkg#10501]
Library name: Copperspice

Library description: CopperSpice is a set of individual libraries which can be used to develop cross platform software applications in C++.

Source repository URL: https://github.com/copperspice/copperspice

Project homepage (if different from the source repository): https://www.copperspice.com/

Anything else that is useful to know when adding (such as optional features the library may have that should be included): Since its derived from QT. Like QT it comes with many different submodules which are not all necessarily required to use copperspice. There are some libraries which can be used completely independently from copperspice like csString for example.

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
