### ISSUE TITLE
[libjpeg-turbo:x86-windows] build failure

### ISSUE THREAD

**Issue by UnknownObject000** [microsoft/vcpkg#10507]
**Host Environment**
- OS: [Windows 10 Professional Workstation x64 2004(19041.153)]
- Compiler: MSVC16 (Visual Studio Professional 2019),CMake 3.16.0

**To Reproduce**
`./vcpkg install opencv`

**Failure logs** 
-- Downloading https://github.com/libjpeg-turbo/libjpeg-turbo/archive/2.0.3.tar.gz... Failed. Status: 56;"Failure when receiving data from the peer"                                                                       CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:175 (message):                                                                               Failed to download file.                                           onment                                                                         variables to "https://user:password@your-proxy-ip-address:port/".        Otherwise, please submit an issue at https://github.com/Microsoft/v                                                                         Call Stack (most recent call first):                                       scripts/cmake/vcpkg_from_github.cmake:132 (vcpkg_download_distfile)      ports/libjpeg-turbo/portfile.cmake:3 (vcpkg_from_github)                 scripts/ports.cmake:94 (include)                                                                                                                                                                                         Error: Building package libjpeg-turbo:x86-windows failed with: BUILD_FAILED                                                                       Please ensure you're using the latest portfiles with `.\vcpkg update`, then                                                                       submit an issue at https://github.com/Microsoft/vcpkg/issues including:    Package: libjpeg-turbo:x86-windows                                       Vcpkg version: 2019.09.12-nohash                                                                                                                Additionally, attach any relevant sections from the log files above.

**Comment by NancyLi1013** [comment]
Hi @UnknownObject000 

Thanks for posting this issue.

It seems that there is something wrong when  downloading  this archive https://github.com/libjpeg-turbo/libjpeg-turbo/archive/2.0.3.tar.gz.

Could you please help confirm if you have access to https://github.com/libjpeg-turbo/libjpeg-turbo/archive/2.0.3.tar.gz?

If yes, please download it manually and put it into _VCPKG_PATH/downloads_, then rebuild this port.

Kindly remind: 
`libjpeg-turbo` has been updated to 2.0.4. If you need the new version, you can try to update vcpkg and use it.

**Comment by UnknownObject000** [comment]
Thank you for give me telling me that.I installed it successlly and I'll close this issue.
