### ISSUE TITLE
[New Port Request] ZXing

### ISSUE THREAD

**Issue by soroshsabz** [microsoft/vcpkg#10503]
Library name: ZXing-C++

Library description: This project is a C++ port of ZXing Library.

Source repository URL: https://github.com/nu-book/zxing-cpp

I think we have another port of zxing-cpp from https://github.com/glassechidna/zxing-cpp in vcpkg port file, but the new port project is recently updated and better maintain and linked in https://github.com/zxing/zxing official repo. and does not memory leakage issue

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
