### ISSUE TITLE
Cannot compile openssl package

### ISSUE THREAD

**Issue by Xiao-Chong** [Microsoft/vcpkg#1051]
OS : windows 7 sp1 64bit
VS 2015 up3

> vcpkg install openssl

Error msg as below:
-- Build x86-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:14 (message):
    Command failed: NMAKE-NOTFOUND;-f;ms\ntdll.mak;install
    Working Directory: D:/vcpkg/buildtrees/openssl/x86-windows-rel/openssl-1.0.2
k
    See logs for more information:
      D:\vcpkg\buildtrees\openssl\build-x86-windows-rel-out.log
      D:\vcpkg\buildtrees\openssl\build-x86-windows-rel-err.log

Call Stack (most recent call first):
  ports/openssl/portfile.cmake:66 (vcpkg_execute_required_process)
  scripts/ports.cmake:73 (include)

==================================================
if I manually modify the portfile.cmake file as below:
find_program(NMAKE nmake HINTS "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin")
it passed.
However, the other issue occured : 
cl is not found when nmake ntdll.mak.
'cl' is not an internal or external commad 
NMAKE : fatal error U1077: 'cl' : return code '0x1'
Stop.

I am sure running under developer command prompt console, and nmake and cl can execute from there manually.

Thanks for help.

**Comment by alexkaratarakis** [comment]
Please try: 
`vcpkg install openssl --debug`

It will provide some extra information.

Also, you don't need to be running in a developer command prompt; vcpkg can run from any prompt and will use the correct environment depending on the target architecture (note: it won't modify your environment of your console in any way, just use the correct environment). Having said that, if vcpkg is not doing the environment isolation correctly, this is something we should fix. Please try running vcpkg in clean console to see if it has a different result.

**Comment by Xiao-Chong** [comment]
Hi, thanks for reply.  After executing vcpkg install openssl --debug in clean console,  got messages below:

D:\vcpkg>vcpkg install openssl --debug
The following packages will be built and installed:
    openssl:x86-windows
Building package openssl:x86-windows...
[DEBUG] _wspawnlpe(cmd.exe /c ""C:\Program Files (x86)\Microsoft Visual Studio 1
4.0\VC\vcvarsall.bat" x64_x86   2>&1 && "C:\Program Files\CMake\bin\cmake.exe" "
-DCMD=BUILD" "-DPORT=openssl" "-DCURRENT_PORT_DIR=D:/vcpkg/ports/openssl/." "-DT
ARGET_TRIPLET=x86-windows" "-DVCPKG_PLATFORM_TOOLSET=v140" "-DVCPKG_USE_HEAD_VER
SION=0" "-D_VCPKG_NO_DOWNLOADS=0" "-DGIT=C:/Program Files/Git/cmd/git.exe" -P "D
:/vcpkg/scripts/ports.cmake"")
Error in script usage. The correct usage is:
    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" [opti
on]
  or
    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" [opti
on] store
  or
    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" [opti
on] [version number]
  or
    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" [opti
on] store [version number]
where [option] is: x86 | amd64 | arm | x86_amd64 | x86_arm | amd64_x86 | amd64_a
rm
where [version number] is either the full Windows 10 SDK version number or "8.1"
 to use the windows 8.1 SDK
:
The store parameter sets environment variables to support
  store (rather than desktop) development.
:
For example:
    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_a
md64
    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_a
rm store
    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_a
md64 10.0.10240.0
    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_a
rm store 10.0.10240.0
    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64 8
.1
    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64 s
tore 8.1
:
Please make sure either Visual Studio or C++ Build SKU is installed.
-- CURRENT_INSTALLED_DIR=D:/vcpkg/installed/x86-windows
-- DOWNLOADS=D:/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=D:/vcpkg/packages/openssl_x86-windows
-- CURRENT_BUILDTREES_DIR=D:/vcpkg/buildtrees/openssl
-- CURRENT_PORT_DIR=D:/vcpkg/ports/openssl/.
-- Using cached D:/vcpkg/downloads/openssl-1.0.2k.tar.gz
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Applying patch D:/vcpkg/ports/openssl/PerlScriptSpaceInPathFixes.patch
-- Applying patch failed. This is expected if this patch was previously applied.

-- Applying patch D:/vcpkg/ports/openssl/PerlScriptSpaceInPathFixes.patch done
-- Applying patch D:/vcpkg/ports/openssl/ConfigureIncludeQuotesFix.patch
-- Applying patch failed. This is expected if this patch was previously applied.

-- Applying patch D:/vcpkg/ports/openssl/ConfigureIncludeQuotesFix.patch done
-- Applying patch D:/vcpkg/ports/openssl/STRINGIFYPatch.patch
-- Applying patch failed. This is expected if this patch was previously applied.

-- Applying patch D:/vcpkg/ports/openssl/STRINGIFYPatch.patch done
-- Build x86-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:14 (message):
    Command failed: NMAKE-NOTFOUND;-f;ms\ntdll.mak;install
    Working Directory: D:/vcpkg/buildtrees/openssl/x86-windows-rel/openssl-1.0.2
k
    See logs for more information:
      D:\vcpkg\buildtrees\openssl\build-x86-windows-rel-out.log
      D:\vcpkg\buildtrees\openssl\build-x86-windows-rel-err.log

Call Stack (most recent call first):
  ports/openssl/portfile.cmake:66 (vcpkg_execute_required_process)
  scripts/ports.cmake:73 (include)


[DEBUG] _wspawnlpe() returned 1
Error: Building package openssl:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openssl:x86-windows
  Vcpkg version: 0.0.81-e1a111ad09d74a5b683635000e34bcc38c717d45

Additionally, attach any relevant sections from the log files above.
[DEBUG] ..\src\commands_install.cpp(362)

D:\vcpkg>vcpkg install openssl --debug > log.txt
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:14 (message):
    Command failed: NMAKE-NOTFOUND;-f;ms\ntdll.mak;install
    Working Directory: D:/vcpkg/buildtrees/openssl/x86-windows-rel/openssl-1.0.2
k
    See logs for more information:
      D:\vcpkg\buildtrees\openssl\build-x86-windows-rel-out.log
      D:\vcpkg\buildtrees\openssl\build-x86-windows-rel-err.log

Call Stack (most recent call first):
  ports/openssl/portfile.cmake:66 (vcpkg_execute_required_process)
  scripts/ports.cmake:73 (include)

**Comment by ras0219-msft** [comment]
Thanks for posting the log!

I've changed our usage of "x64" to "amd64" when initializing vcvarsall.bat, which should fix this issue.

Could you pull, re-run bootstrap, and try again?

**Comment by Xiao-Chong** [comment]
Hi there,

Problem solved.  Thank you very much.
