### ISSUE TITLE
Vcpkg PR tests failing for all PRs  dating back 20200320

### ISSUE THREAD

**Issue by ArashPartow** [microsoft/vcpkg#10519]
PRs dating back to the 20th are failing. 

Is there anything PR authors can do to resolve this issue or is this a MSFT CI _backend issue_?

----------

Examples
https://github.com/microsoft/vcpkg/pull/10518
https://github.com/microsoft/vcpkg/pull/10514
https://github.com/microsoft/vcpkg/pull/10511
https://github.com/microsoft/vcpkg/pull/10508
https://github.com/microsoft/vcpkg/pull/10506
https://github.com/microsoft/vcpkg/pull/10505
https://github.com/microsoft/vcpkg/pull/10500
https://github.com/microsoft/vcpkg/pull/10496
https://github.com/microsoft/vcpkg/pull/10486
https://github.com/microsoft/vcpkg/pull/10485

**Comment by dan-shaw** [comment]
#10508 will fix this
