### ISSUE TITLE
[New Port Request] cglm

### ISSUE THREAD

**Issue by davll** [microsoft/vcpkg#10516]
Library name: cglm

Library description: Highly Optimized Graphics Math (glm) for C

Source repository URL: https://github.com/recp/cglm

Though vcpkg has glm already, but I think it is good to have one more option for C developers: :)
[The intro on Reddit](https://www.reddit.com/r/gamedev/comments/94kz0u/optimized_3d_math_library_for_c/)

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
