### ISSUE TITLE
cpprestsdk Failed massage

### ISSUE THREAD

**Issue by RageLog** [microsoft/vcpkg#10510]
i didn't found solution for this. Always gave to me  this error.
PS C:\vcpkg-master> .\vcpkg.exe install cpprestsdk cpprestsdk:x64-windows
Computing installation plan...
The following packages will be built and installed:
  * brotli[core]:x86-windows
  * brotli[core]:x64-windows
    cpprestsdk[brotli,compression,core,default-features,websockets]:x64-windows
    cpprestsdk[brotli,compression,core,default-features,websockets]:x86-windows
  * websocketpp[core]:x64-windows
  * websocketpp[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/6: brotli:x86-windows
Building package brotli[core]:x86-windows...
-- Using cached C:/vcpkg-master/downloads/google-brotli-v1.0.7.tar.gz
-- Using source at C:/vcpkg-master/buildtrees/brotli/src/v1.0.7-bf01b84227
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Installing: C:/vcpkg-master/packages/brotli_x86-windows/share/brotli/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package brotli[core]:x86-windows... done
Installing package brotli[core]:x86-windows...
Failed at [C:\vcpkg-master\toolsrc\src\vcpkg\vcpkglib.cpp(216)] with message:
no such file or directory

**Comment by LilyWangL** [comment]
@RageLog Thanks for posting this issue. Do you can install other ports successfully?

**Comment by RageLog** [comment]
No, i couldnt install but i found a solution that, remove all instalition of vcpkg(and of course api) and install again.

**Comment by LilyWangL** [comment]
Thanks for your issue. This issue has been solved, so I am closing this issue for now.
