### ISSUE TITLE
boost build failure with latest vcpkg + general directory rename failures

### ISSUE THREAD

**Issue by etheory** [microsoft/vcpkg#10529]
**Host Environment**
- OS: Microsoft Windows 10 Home, Version 10.0.18362 Build 18362
- Compiler: Visual Studio Community 2019 x64-windows
- vcpkg-2020.02.04-nohash-external

**To Reproduce**
.\vcpkg install boost:x64-windows

**Failure logs** 
Building package boost-config[core]:x64-windows...
-- Using cached Z:/Programming/Graphics/vcpkg/downloads/boostorg-config-boost-1.72.0.tar.gz
-- Extracting source Z:/Programming/Graphics/vcpkg/downloads/boostorg-config-boost-1.72.0.tar.gz
CMake Error at scripts/cmake/vcpkg_extract_source_archive_ex.cmake:140 (file):
  file RENAME failed to rename

    Z:/Programming/Graphics/vcpkg/buildtrees/boost-config/src/TEMP/config-boost-1.72.0

  to

    Z:/Programming/Graphics/vcpkg/buildtrees/boost-config/src/ost-1.72.0-e18c20b3a7

  because: No such file or directory

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:139 (vcpkg_extract_source_archive_ex)
  ports/boost-config/portfile.cmake:5 (vcpkg_from_github)
  scripts/ports.cmake:90 (include)

Error: Building package boost-config:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-config:x64-windows
  Vcpkg version: 2020.02.04-nohash-external

Additionally, attach any relevant sections from the log files above.

**Additional context**
This was not occurring until I recently updated to the latest vcpkg version.

This now occurs for ALL package installs, not just boost. Effectively, after the last update vcpkg is useless and doesn't work at all.

**Comment by linquize** [comment]
Similar issue #10524 related to `boost-math` module

**Comment by HerveAncher** [comment]
For my side, I was not able to install Boost 1.72.0 with the CMake version downloaded by vcpkg (3.14.0).

I have updated VS2019 to 16.5.0, which include 3.16.x and with this version, no problem by launching the vcpkg command from x64 native tools for VS2019.

Do you try to use a newer version of CMake with vcpkg?

**Comment by etheory** [comment]
I tried exactly what you suggested above, using VS2019 latest version from "x64 Native Tools Command Prompt for VS 2019".
This does, at least so far, seem to fix the issues.
Thank you.
It's quite a lengthy workaround though, installing VS2019 isn't exactly a small install ;-)

**Comment by etheory** [comment]
I get a different issue though now.

**Comment by etheory** [comment]
Duplicate of https://github.com/microsoft/vcpkg/issues/9132

**Comment by PhoebeHui** [comment]
Related to https://github.com/microsoft/vcpkg/issues/8199
