### ISSUE TITLE
Including library with no native cmake support

### ISSUE THREAD

**Issue by r4ph0u** [microsoft/vcpkg#10528]
Hello !
I've been strugguling on that for 2 days :
I installed xxhash with vcpkg in order to use them in a project.

As they do not provide cmake support (unable to use find package configuration files), I am trying what is indicated in the vcpkg doc :

```
find_path(XXHASH_INCLUDE_DIR xxhash/xxhash.h)
find_library(XXHASH_LIBRARY xxhash)
include_directories(${XXHASH_INCLUDE_DIR})
link_libraries(${XXHASH_LIBRARY})
```

However, cmake is unable to find the include path and the library

I also have the same problem with json-c library

This is my cmake output :
```
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.


-- Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
XXHASH_INCLUDE_DIR
   used as include directory in directory D:/raphael/Programmation/Projet Reseau/groupe-12/src
   used as include directory in directory D:/raphael/Programmation/Projet Reseau/groupe-12/src
   used as include directory in directory D:/raphael/Programmation/Projet Reseau/groupe-12/src

CMake Error in CMakeLists.txt:
  Found relative path while evaluating include directories of "exec":

    "XXHASH_INCLUDE_DIR-NOTFOUND"



CMake Error in CMakeLists.txt:
  Found relative path while evaluating include directories of "exec":

    "XXHASH_INCLUDE_DIR-NOTFOUND"



-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

**Comment by JackBoosY** [comment]
Hi @r4ph0u, thanks for reporting this issue!
Before using the port already installed by vcpkg, you need to use the command `./vcpkg Integrate install 'to integrate vcpkg into the cmake project, and then add the vcpkg toolchain to the cmake project.
See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/users/integration.md).

**Comment by linquize** [comment]
I do not want to use `vcpkg Integrate install` because it want per-project basis.

**Comment by linquize** [comment]
@r4ph0u should be `find_path(XXHASH_INCLUDE_DIR xxhash.h)`

**Comment by r4ph0u** [comment]
> 
> 
> Hi @r4ph0u, thanks for reporting this issue!
> Before using the port already installed by vcpkg, you need to use the command `./vcpkg Integrate install 'to integrate vcpkg into the cmake project, and then add the vcpkg toolchain to the cmake project.
> See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/users/integration.md).

Thanks for answering, however, I already used  `vcpkg integrate install` and I am including the vcpkg toolchain path.

Here is my full CMakeLists.txt :


```
cmake_minimum_required(VERSION 3.0)

if(DEFINED ENV{VCPKG_ROOT} AND NOT DEFINED CMAKE_TOOLCHAIN_FILE)
  set(CMAKE_TOOLCHAIN_FILE "$ENV{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake"
      CACHE STRING "")
endif()
if(DEFINED ENV{VCPKG_DEFAULT_TRIPLET} AND NOT DEFINED VCPKG_TARGET_TRIPLET)
  set(VCPKG_TARGET_TRIPLET "$ENV{VCPKG_DEFAULT_TRIPLET}" CACHE STRING "")
endif()



project(executable)
set(EXECUTABLE_OUTPUT_PATH bin)

set(SRCS
    main.cpp
    convManager.cpp
    )

set(HEADERS
    conversation.hpp
    convManager.hpp
    )


add_executable(exec ${SRCS} ${HEADERS})

find_path(XXHASH_INCLUDE_DIR xxhash/xxhash.h)

find_library(XXHASH_LIBRARY xxhash)
include_directories(${XXHASH_INCLUDE_DIR})
link_libraries(${XXHASH_LIBRARY})
```

**Comment by linquize** [comment]
@r4ph0u should be `find_path(XXHASH_INCLUDE_DIR xxhash.h)`

**Comment by r4ph0u** [comment]
> 
> 
> @r4ph0u should be `find_path(XXHASH_INCLUDE_DIR xxhash.h)`

same result
```

-- The C compiler identification is GNU 8.2.0
-- The CXX compiler identification is GNU 8.2.0
-- Check for working C compiler: C:/MinGW/bin/gcc.exe
-- Check for working C compiler: C:/MinGW/bin/gcc.exe - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/MinGW/bin/g++.exe
-- Check for working CXX compiler: C:/MinGW/bin/g++.exe - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
XXHASH_INCLUDE_DIR
   used as include directory in directory D:/raphael/Programmation/Projet Reseau/groupe-12/src
   used as include directory in directory D:/raphael/Programmation/Projet Reseau/groupe-12/src
   used as include directory in directory D:/raphael/Programmation/Projet Reseau/groupe-12/src

CMake Error in CMakeLists.txt:
  Found relative path while evaluating include directories of "exec":

    "XXHASH_INCLUDE_DIR-NOTFOUND"



CMake Error in CMakeLists.txt:
  Found relative path while evaluating include directories of "exec":

    "XXHASH_INCLUDE_DIR-NOTFOUND"



-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

**Comment by r4ph0u** [comment]
Is the `CMAKE_TOOLCHAIN_FILE `even doing anything as I am not using `find_package()` ?

**Comment by linquize** [comment]
Oh! You use mingw, you have to set `VCPKG_TARGET_TRIPLET` to `x86-mingw`

`cmake.exe -DVCPKG_TARGET_TRIPLET=x86-mingw`

**Comment by linquize** [comment]
The toolchain file is loaded even if `find_package` is not used.

**Comment by r4ph0u** [comment]
As mentioned, I have the same problem when i run cmake with vs 2019 generator.
I tried the x86-mingw triplet but it changed nothing

**Comment by linquize** [comment]
If you wish to use VS2019, remove `C:\mingw\bin` from `%PATH%`. Then clean everything and try again with vs 2019 generator

**Comment by r4ph0u** [comment]
I would like not to use VS2019, but I always try to build both with VS and MinGW (in separated folders). None of them works with all your advices

**Comment by r4ph0u** [comment]
I have both verison installed of course, I tried building with VS2019 with x86-windows triplet and with MinGW with x86-windows triplet, none works

```with
C:\vcpkg>vcpkg list
xxhash:x86-mingw                                   0.7.0            Extremely fast hash algorithm
xxhash:x86-windows                                 0.7.0            Extremely fast hash algorithm
```

Maybe I shuld just stop searching and including the lib directly in my projet folder ? What file do I have to use copy then ?   .h files and .lib ?

**Comment by linquize** [comment]
`echo %VCPKG_ROOT%`

**Comment by r4ph0u** [comment]
```
>echo %VCPKG_ROOT%
C:\vcpkg
```

**Comment by linquize** [comment]
What command line did you use to build your project with mingw?

**Comment by r4ph0u** [comment]
I used :
`cmake -G "MinGW Makefiles"`

note that the `CMAKE_TOOLCHAIN_FILE `and `VCPKG_TARGET_TRIPLET` variable are set inside CMakeLists.txt

**Comment by Neumann-A** [comment]
`cmake_minimum_required(VERSION 3.0)`
Simply no...... bump that to a reasonable value and maybe 
`find_path(XXHASH_INCLUDE_DIR xxhash.h PATH_SUFFIXES include)`
works then. 
But we could talk if vcpkg.cmake should append itself to `CMAKE_INCLUDE_PATH`

**Comment by NancyLi1013** [comment]
@r4ph0u 
Could you please try to set `CMAKE_TOOLCHAIN_FILE ` with `cmake `command instead of in `CMakeLists.txt`?
like this `cmake -DCMAKE_TOOLCHAIN_FILE="VCPKG_ROOT_PATH/scripts/buildsystems/vcpkg.cmake"`
Please also make sure that there are no other build caches in build folder and then build it again.
I can build `x86-windows` and `x64-windows` triplets with Visual Studio 2019 and cmake successfully.
```
PS E:\vcpkg\test> E:\vcpkg\downloads\tools\cmake-3.14.0-windows\cmake-3.14.0-win32-x86\bin\cmake.exe -DCMAKE_TOOLCHAIN_FILE="E:/vcpkg/scripts/buildsystems/vcpkg.cmake" -DCMAKE_BUILD_TYPE="Debug"
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.


-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
-- The C compiler identification is MSVC 19.25.28611.0
-- The CXX compiler identification is MSVC 19.25.28611.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx86/x86/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx86/x86/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx86/x86/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx86/x86/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
XXHASH_INCLUDE_DIR:E:/vcpkg/installed/x64-windows/include
XXHASH_LIBRARY:E:/vcpkg/installed/x64-windows/debug/lib/xxhash.lib
-- Configuring done
-- Generating done
-- Build files have been written to: E:/vcpkg/test
```

**Comment by r4ph0u** [comment]
not sure why, but it finally worked. Thanks all for your help.
@Neumann-A : what reasonnable value would you recommand for minimal required version, and why ?

**Comment by Neumann-A** [comment]
> what reasonnable value would you recommand for minimal required version, and why ?

depends on your target. If you only intend to build for windows go with the latest (3.17) since it is easy enough to install a new cmake version. If you also target Ubuntu then go with 3.10 since that is in LTS (see https://discourse.vtk.org/t/minimum-cmake-version/2867). Personally I would always at least go with the minimum vcpkg uses which is 3.14 but I always prefer latest (3.17). 
The reason you should go with a higher cmake_minimum_required is because you will lock yourself out of newer cmake features which might not work as you think or policies have changed over the years. And there is no reason to support anything less than 3.10 unless you have to support an ancient linux distro.....
