### ISSUE TITLE
boost-math build failure

### ISSUE THREAD

**Issue by vptrbv** [microsoft/vcpkg#10524]
**Host Environment**
- OS: Windows
- Compiler: Clang 9.0.1 with MSVC-like command-line

**To Reproduce**
PS C:\Users\vptrb\build\vcpkg> `.\vcpkg.exe install boost-math`

**Failure logs** 
Computing installation plan...
The following packages will be built and installed:
    boost-math[core]:x86-windows
Starting package 1/1: boost-math:x86-windows
Building package boost-math[core]:x86-windows...
-- Using cached C:/Users/vptrb/build/vcpkg/downloads/boostorg-math-boost-1.72.0.tar.gz
-- Extracting source C:/Users/vptrb/build/vcpkg/downloads/boostorg-math-boost-1.72.0.tar.gz
CMake Error at scripts/cmake/vcpkg_extract_source_archive_ex.cmake:140 (file):
  file RENAME failed to rename

    C:/Users/vptrb/build/vcpkg/buildtrees/boost-math/src/TEMP/math-boost-1.72.0

  to

    C:/Users/vptrb/build/vcpkg/buildtrees/boost-math/src/ost-1.72.0-2786b6df16

  because: No such file or directory

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:139 (vcpkg_extract_source_archive_ex)
  ports/boost-math/portfile.cmake:5 (vcpkg_from_github)
  scripts/ports.cmake:90 (include)

Error: Building package boost-math:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-math:x86-windows
  Vcpkg version: 2020.02.04-nohash

**Comment by linquize** [comment]
Similar issue #10529 related to `boost-config` module

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/8199.
