### ISSUE TITLE
vcpkg.vcxproj should auto-detect PlatformToolset from VisualStudioVersion

### ISSUE THREAD

**Issue by linquize** [microsoft/vcpkg#10532]
`vcpkg.vcxproj`, `vcpkglib.vcxproj`, `vcpkgmetricsuploader.vcxproj`, `vcpkgtest.vcxproj` should auto-detect `PlatformToolset` property from `VisualStudioVersion`.

This allows to compile the same project files in VS2015, VS2017 and VS2019 without requiring the user to edit the project files manually.

**Comment by JackBoosY** [comment]
Well, I don't think this will bring any help to users, because when we use vcpkg, we always use script `bootstrap-vcpkg.bat` to build vcpkg instead of using `vcpkg.sln`.

**Comment by linquize** [comment]
This is not for users, but for developers who wish to edit vcpkg source code in VS2019

**Comment by linquize** [comment]
Because I no longer install VS2015  v140 and Win8.1 SDK.
I only install VS2019 v142 toolset with latest Win10 SDK.
If I open in VS2019, it still requires VS2015 v140 toolset to build

**Comment by JackBoosY** [comment]
@dan-shaw What do you think?

**Comment by Neumann-A** [comment]
My opinion: I don't understand why there is even a *.sln solution within the Github repo. Just use CMake to generate the *.sln file if needed....

**Comment by JackBoosY** [comment]
@Neumann-A We have, see [here](https://github.com/microsoft/vcpkg/blob/master/toolsrc/vcpkg.sln) .
The reason for using sln directly in Windows is that cmake may not be installed on the user's machine, and cmake in vcpkg is downloaded by vcpkg.exe.

**Comment by linquize** [comment]
Suggest something like
```xml
<PlatformToolset Condition="'$(VisualStudioVersion)' == '16.0'">v142</PlatformToolset>
```

**Comment by linquize** [comment]
This will use the corresponding toolset when open the project in different versions of Visual Studio

> 
> 
> Suggest something like
> 
> ```
> <PlatformToolset Condition="'$(VisualStudioVersion)' == '16.0'">v142</PlatformToolset>
> ```
> 
> in all `.vcxproj` files

**Comment by BillyONeal** [comment]
vcpkg.vcxproj no longer exists and we now only use the CMakeLists.txt system, so I'm closing this.
