### ISSUE TITLE
Drive case not ignored downloading CMake

### ISSUE THREAD

**Issue by sgraham** [Microsoft/vcpkg#1053]
c:\src\test\third_party>c:\src\vcpkg\vcpkg.exe install openssl:x64-windows zlib:x64-windows libuv:x64-windows
The following packages will be built and installed:
    libuv:x64-windows
    openssl:x64-windows
    zlib:x64-windows
Building package openssl:x64-windows...

Download cmake
No suitable version of cmake was found (requires 3.8.0 or higher). Download portable version?
[Y] Yes  [N] No  [A] Always Allow Downloads  [?] Help (default is "Y"):
Expected dependency downloaded path to be c:/src/vcpkg/downloads/cmake-3.8.0-win32-x86/bin/cmake.exe, but was C:/src/vcpkg/downloads/cmake-3.8.0-win32-x86/bin/cmake.exe

c:\src\test\third_party>cd C:/

C:\>cd src\test\third_party

C:\src\test\third_party>c:\src\vcpkg\vcpkg.exe install openssl:x64-windows zlib:x64-windows libuv:x64-windows
The following packages will be built and installed:
    libuv:x64-windows
    openssl:x64-windows
    zlib:x64-windows
Building package openssl:x64-windows...
...

**Comment by ras0219-msft** [comment]
Thanks for reporting this!

I've switched to using fs::equivalent in `master`, which should handle case insensitivity. Let us know if the issue appears again for you!
