### ISSUE TITLE
vcpkg doc website: Maintainers menu too long

### ISSUE THREAD

**Issue by linquize** [microsoft/vcpkg#10530]
https://vcpkg.readthedocs.io/ website: Maintainers menu too long for 1366x768 resolution.
To show all available menu items, I have to zoom out to 80%.

![vcpkg_maintainers](https://user-images.githubusercontent.com/791115/77409364-17627e00-6df4-11ea-8624-41b0fa6e1952.png)

Any ideas to improve the website UI?

**Comment by Neumann-A** [comment]
Could be order into:

make related
meson related
cmake related
qmake related
msbuild related
buildsystems

and another on for general utility functions.

**Comment by linquize** [comment]
As of today, Maintainers menu has **49** items long! I have to zoom out to **40%**!

**Comment by PhoebeHui** [comment]
The https://vcpkg.readthedocs.io/ has been deprecated, the new website is https://vcpkg.io/en/index.html, and you can submit feedbacks about the new website in https://github.com/vcpkg/vcpkg.github.io/issues.
