### ISSUE TITLE
Update Blitz repo to use last commit

### ISSUE THREAD

**Issue by HerveAncher** [microsoft/vcpkg#10531]
Dear all,

A push last week a PR https://github.com/blitzpp/blitz/pull/161 where I integrate static libreary support for Blitz under Windows and MinGW.
The last time I try to install Blitz accross vcpkg (vcpkg install blitz:x64-windows) was a failed, because files were missing after compilation (like DLL and library.

I think the trouble is that the current config using Ninja defined badly the destination of targets (extract from .ninja_log):

```
9769	10080	606749551	/src/blitz.dll	2ca2bbf865eb0a4e
9769	10080	606749551	/src/blitz.lib	2ca2bbf865eb0a4e
```

There are same slash at the beginning of the target paths.
May somebody correct the script and update the hash to use the last version of Blitz?

Regards.

**Comment by HerveAncher** [comment]
Maybe @NancyLi1013?

**Comment by HerveAncher** [comment]
Additional information: I try to install Blitz with vcpkg under standard Command Prompt, and from x64 Native Tools Command Prompt for VS 2019, with the same result.

So defined some MSVC env variables do not change the result.

**Comment by NancyLi1013** [comment]
Hi @HerveAncher 

Thanks for posting this issue.
I checked it just now and it seemed that there was something wrong with this port.
I can install it successfully, but there are no lib or dll files generated.

I will go further investagition about this port.

**Comment by HerveAncher** [comment]
> I can install it successfully, but there are no lib or dll files generated.

That is exactly what I got. thanks for this quick answer .°D

**Comment by NancyLi1013** [comment]
@HerveAncher 
The current `blitz `version in vcpkg seems to be some problems on Windows.
So I updated this port to the latest commit in this PR #10546 
Could you please help confirm if this can work for you?

**Comment by NancyLi1013** [comment]
This issue should be fixed now.
Please update vcpkg and try to rebuild it.
