### ISSUE TITLE
[portaudio] install pa_asio.h when portaudio is used together with [asiosdk]

### ISSUE THREAD

**Issue by s13n** [microsoft/vcpkg#10538]
When portaudio includes ASIO SDK support, the header file `pa_asio.h` is frequently needed, but it isn't provided in the installed include directory. This makes client projects fail to build when they rely on specific ASIO functionality.

The `pa_asio.h` header file is included in the portaudio source tree, it needs to be installed along with the other public header files. It could simply be installed unconditionally, or it could be installed when the presence of the ASIOSDK is detected.

**Comment by NancyLi1013** [comment]
Hi @s13n 
Thanks for posting this issue.
It seems that `pa_asio.h` will be installed automatically if ASIO SDK is detected to be installed on your machine.

**Comment by NancyLi1013** [comment]
```
FIND_PACKAGE(ASIOSDK)
  IF(ASIOSDK_FOUND)
    OPTION(PA_USE_ASIO "Enable support for ASIO" ON)
  ELSE()
    OPTION(PA_USE_ASIO "Enable support for ASIO" OFF)
  ENDIF()
```
When `PA_USE_ASIO` is on, `pa_asio.h` will be added by this:
`SET(PA_PUBLIC_INCLUDES ${PA_PUBLIC_INCLUDES} include/pa_asio.h)`

**Comment by NancyLi1013** [comment]
Hi @s13n 
Could you please help confirm if this can work for you?

**Comment by NancyLi1013** [comment]
In my option, the current status is correct. 
So I'm closing this issue for now since there is no response in a long time.
Please feel free to reopen this if it is still a problem for you.

**Comment by aparks5** [comment]
Just a heads up, ASIOSDK cannot be found because it can't be installed. Therefore portaudio never adds pa_asio.h to the install despite best efforts.
https://github.com/microsoft/vcpkg/issues/12521
