### ISSUE TITLE
realsense2:x64-windows - rs2::pipeline::start() blocks forever while running with Realsense T265.

### ISSUE THREAD

**Issue by piotr-tanski** [microsoft/vcpkg#10545]
While using Realsense2 (for x64-windows) library in the application communicating with the Intel Realsense T265 device, a call to method rs2::pipeline::start() never returns. The problem is 100% reproducible.
Unfortunately, there's no output at all from the realsense2 lib. If there's a switch to enable debug logs, please let me know and I will paste the logs from runtime.

To solve the problem, I downloaded realsense2 source from https://github.com/IntelRealSense/librealsense/archive/v2.32.1.zip and built it with -DBUILD_WITH_TM2=ON flag. Now, it works just fine.
This is the reason why it seems that the vcpkg package is somehow broken for T265.

Please, can someone advise? Would it be possible to update the vcpkg package?

**Comment by LilyWangL** [comment]
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.
