### ISSUE TITLE
realsense2:x86-windows Build Failed, wrong path to .inf

### ISSUE THREAD

**Issue by mediadog** [microsoft/vcpkg#10541]
Attempting to build RealSense2 on Win7 x64 Enterprise, when executing "vcpkg install realsense2", the build fails and the buildtrees\realsense2\install-x86-windows-dbg-err.log file contains:
```
ninja: error: 'D:/vcpkg-master/buildtrees/realsense2/src/aaa6db6f7e-746a483df4/IntelRealSense_D400_series_win7.inf', needed by 'CMakeFiles/realsense-driver', missing and no known rule to make it
```
That .inf file actually resides in:
_D:\vcpkg-master\buildtrees\realsense2\src\aaa6db6f7e-746a483df4\src\win7\drivers_

Note the missing src\win7\drivers in the path in the ninja error.

Main output:
```
-- Extracting source D:/vcpkg-master/downloads/IntelRealSense-librealsense-9f99fa9a509555f85bffc15ce27531aaa6db6f7e.tar
gz
-- Applying patch fix_openni2.patch
-- Applying patch fix-dependency-glfw3.patch
-- Using source at D:/vcpkg-master/buildtrees/realsense2/src/aaa6db6f7e-746a483df4
-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: D:/vcpkg-master/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe --build .
--config Debug --target install -- -v
    Working Directory: D:/vcpkg-master/buildtrees/realsense2/x86-windows-dbg
    See logs for more information:
      D:\vcpkg-master\buildtrees\realsense2\install-x86-windows-dbg-err.log

Error: Building package realsense2:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: realsense2:x86-windows
  Vcpkg version: 2020.02.04-nohash
```
And yes everything is up to date.  Thanks!

**Comment by LilyWangL** [comment]
This is a source bug, it has been fixed in new version realsense2. The related source issue: https://github.com/IntelRealSense/librealsense/issues/5809

**Comment by mediadog** [comment]
I just did a clean vcpkg bootstrap and install realsense and got the same error, ditto for x64.  Is there some change needed for vcpkg to get the latest version?  The version in the config-x86-windows-out.log file shows:

-- Info: REALSENSE_VERSION_STRING=2.30.0

So how can I make it get 2.33.1?  Thanks!

**Comment by LilyWangL** [comment]
> I just did a clean vcpkg bootstrap and install realsense and got the same error, ditto for x64. Is there some change needed for vcpkg to get the latest version? The version in the config-x86-windows-out.log file shows:
> 
> -- Info: REALSENSE_VERSION_STRING=2.30.0
> 
> So how can I make it get 2.33.1? Thanks!

You can sync PR #10550 changes to your local VCPKG, and rebuild this port.

**Comment by mediadog** [comment]
Not being a git-meister, I was unable to figure out what you mean by "sync PR #10550", so I just cloned the one there, and yes it did build!  Or at least the main lib did, none of the wrappers built (looking for OpenNI2).  How do I get those to build?  (Perhaps I should open another issue on that?)  Thanks!

**Comment by LilyWangL** [comment]
Thanks for posting this issue. This issue has been fixed. You can update VCPKG and rebuild realsense2.
