### ISSUE TITLE
[New Port Request] rapidyaml

### ISSUE THREAD

**Issue by YukinoHayakawa** [microsoft/vcpkg#10549]
Library name:
rapidyaml

Library description:
"Or ryml, for short. ryml is a library to parse and emit YAML, and do it fast."

Source repository URL:
https://github.com/biojppm/rapidyaml

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by YukinoHayakawa** [comment]
> The port is already added, named "ryml" (#10793), that is also correct name.
> From home: "Or ryml, for short. ryml is a library to parse and emit YAML, and do it fast."

Ah. I see. Feel so stupid missing that one :) Thank you.

**Comment by PavelKisliak** [comment]
No, no, the port was added after about month after your request.

**Comment by YukinoHayakawa** [comment]
> No, no, the port was added after about month after your request.

Feeling better now :)
