### ISSUE TITLE
vtk[core] build failure

### ISSUE THREAD

**Issue by MatteoNasci** [microsoft/vcpkg#10558]
**Host Environment**
- OS: Windows
- Compiler: MSVC

**To Reproduce**
`./vcpkg install vtk:x64-windows-static`

**Failure logs** 
```
Computing installation plan...
The following packages will be built and installed:
    vtk[core]:x64-windows-static
Starting package 1/1: vtk:x64-windows-static
Building package vtk[core]:x64-windows-static...
-- Using cached D:/vcpkg/downloads/Kitware-VTK-v8.2.0.tar.gz
-- Using source at D:/vcpkg/buildtrees/vtk/src/v8.2.0-d1dd9405dd
-- Configuring x64-windows-static
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: ninja -v
    Working Directory: D:/vcpkg/buildtrees/vtk/x64-windows-static-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\vcpkg\buildtrees\vtk\config-x64-windows-static-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:295 (vcpkg_execute_required_process)
  ports/vtk/portfile.cmake:94 (vcpkg_configure_cmake)
  scripts/ports.cmake:90 (include)


Error: Building package vtk:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: vtk:x64-windows-static
  Vcpkg version: 2020.02.04-nohash
```
[vcpkg/buildtrees/vtk/config-x64-windows-static-out.log](https://github.com/microsoft/vcpkg/files/4383597/config-x64-windows-static-out.log)

[vcpkg/buildtrees/vtk/x64-windows-static-rel/CMakeFiles/CMakeError.log](https://github.com/microsoft/vcpkg/files/4383615/CMakeError.log)
[vcpkg/buildtrees/vtk/x64-windows-static-rel/CMakeFiles/CMakeOutput.log](https://github.com/microsoft/vcpkg/files/4383616/CMakeOutput.log)

[vcpkg/buildtrees/vtk/x64-windows-static-dbg/CMakeFiles/CMakeError.log](https://github.com/microsoft/vcpkg/files/4383638/CMakeError.log)
[vcpkg/buildtrees/vtk/x64-windows-static-dbg/CMakeFiles/CMakeOutput.log](https://github.com/microsoft/vcpkg/files/4383639/CMakeOutput.log)

**Comment by JackBoosY** [comment]
`export(TARGETS ${_vtk_compiletools_targets}` failed. But I can't repro this issue now.

**Comment by MatteoNasci** [comment]
I have modified the vcpkg\buildtrees\vtk\src\v8.2.0-d1dd9405dd\CMakeLists.txt using the fix of the issue you mentioned and now vtk seems to install correctly.  

At the end I get a note saying that some targets were omitted. I don't know if this may cause problems when I go and use it (I'll test later).

    find_package(VTK CONFIG REQUIRED)
    # Note: 102 target(s) were omitted.
    target_link_libraries(main PRIVATE foo vtksys somelib verdict)

**Comment by MatteoNasci** [comment]
I have modified the vcpkg\buildtrees\vtk\src\v8.2.0-d1dd9405dd\CMakeLists.txt using the fix of the issue you mentioned and now vtk seems to install correctly.  

Thanks, I'm closing the issue :)
