### ISSUE TITLE
install error 

### ISSUE THREAD

**Issue by MrJiangSheng** [Microsoft/vcpkg#1055]
C:\Users\Administrator\Desktop\vcpkg-master>bootstrap-vcpkg
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Microsoft (R) 生成引擎版本 15.1.1012.6693
版权所有(C) Microsoft Corporation。保留所有权利。

生成启动时间为 2017/5/9/周二 16:11:58。
     1>节点 1 上的项目“C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\dirs.proj”(默认目标)。
     1>项目“C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\dirs.proj”(1)正在节点 1 上生成“C:\Users\Administrator\Desktop\vc
       pkg-master\toolsrc\vcpkg\vcpkg.vcxproj”(2) (Clean 个目标)。
     2>CoreClean:
         正在创建目录“Release\”。
     2>项目“C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\vcpkg\vcpkg.vcxproj”(2)正在节点 1 上生成“C:\Users\Administrator\
       Desktop\vcpkg-master\toolsrc\vcpkglib\vcpkglib.vcxproj”(3) (Clean 个目标)。
     3>CoreClean:
         正在创建目录“Release\”。
     3>已完成生成项目“C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\vcpkglib\vcpkglib.vcxproj”(Clean 个目标)的操作。
     2>已完成生成项目“C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\vcpkg\vcpkg.vcxproj”(Clean 个目标)的操作。
     1>项目“C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\dirs.proj”(1)正在节点 1 上生成“C:\Users\Administrator\Desktop\vc
       pkg-master\toolsrc\vcpkgmetricsuploader\vcpkgmetricsuploader.vcxproj”(4) (Clean 个目标)。
     4>CoreClean:
         正在创建目录“Release\”。
     4>已完成生成项目“C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\vcpkgmetricsuploader\vcpkgmetricsuploader.vcxproj”(C
       lean 个目标)的操作。
     1>项目“C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\dirs.proj”(1)正在节点 1 上生成“C:\Users\Administrator\Desktop\vc
       pkg-master\toolsrc\vcpkg\vcpkg.vcxproj”(2:2) (Build 个目标)。
   2:2>项目“C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\vcpkg\vcpkg.vcxproj”(2:2)正在节点 1 上生成“C:\Users\Administrato
       r\Desktop\vcpkg-master\toolsrc\vcpkglib\vcpkglib.vcxproj”(3:4) (默认目标)。
     3>PrepareForBuild:
         正在创建目录“C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\Release\”。
         正在创建目录“Release\vcpkglib.tlog\”。
       InitializeBuildStatus:
         正在创建“Release\vcpkglib.tlog\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
       ClCompile:
         D:\Program Files\VS2017\VC\Tools\MSVC\14.10.25017\bin\HostX86\x86\CL.exe /c /I..\include /Zi /nologo /W3 /WX-
         /diagnostics:classic /sdl /MP /O2 /Oi /Oy- /GL /D DISABLE_METRICS=0 /D "VCPKG_VERSION=-HEAD" /D _MBCS /D NDEBU
         G /D _MBCS /Gm- /EHsc /MD /GS /Gy /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Yc"pch.h" /Fp"Release\vcpkg
         lib.pch" /Fo"Release\\" /Fd"Release\vcpkglib.pdb" /Gd /TP /analyze- /errorReport:queue /std:c++latest ..\src\p
         ch.cpp
         pch.cpp
     3>C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\include\pch.h(28): fatal error C1083: 无法打开包括文件: “shlobj.h”:
       No such file or directory [C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\vcpkglib\vcpkglib.vcxproj]
     3>已完成生成项目“C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\vcpkglib\vcpkglib.vcxproj”(默认目标)的操作 - 失败。
     2>已完成生成项目“C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\vcpkg\vcpkg.vcxproj”(Build 个目标)的操作 -  失败。
     1>已完成生成项目“C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\dirs.proj”(默认目标)的操作 - 失败。

生成失败。

       “C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\dirs.proj”(默认目标) (1) ->
       “C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\vcpkg\vcpkg.vcxproj”(Build 目标) (2:2) ->
       “C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\vcpkglib\vcpkglib.vcxproj”(默认目标) (3:4) ->
       (ClCompile 目标) ->
         C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\include\pch.h(28): fatal error C1083: 无法打开包括文件: “shlobj.h”
       : No such file or directory [C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\vcpkglib\vcpkglib.vcxproj]

    0 个警告
    1 个错误

已用时间 00:00:08.25
Copy-Item : 找不到路径“C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\Release\vcpkg.exe”，因为该路径不存在。
所在位置 C:\Users\Administrator\Desktop\vcpkg-master\scripts\bootstrap.ps1:34 字符: 5
+     Copy-Item $vcpkgSourcesPath\Release\vcpkg.exe $vcpkgRootDir\vcpkg ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Admini...lease\vcpkg.exe:String) [Copy-Item], ItemNotFoundExce
   ption
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand

Copy-Item : 找不到路径“C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\Release\vcpkgmetricsuploader.exe”，因为该
路径不存在。
所在位置 C:\Users\Administrator\Desktop\vcpkg-master\scripts\bootstrap.ps1:35 字符: 5
+     Copy-Item $vcpkgSourcesPath\Release\vcpkgmetricsuploader.exe $vcp ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Admini...icsuploader.exe:String) [Copy-Item], ItemNotFoundExce
   ption
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand

C:\Users\Administrator\Desktop\vcpkg-master>cd C:\Users\Administrator\Desktop\vcpkg-master

**Comment by MrJiangSheng** [comment]
I have install my system win10X64,and vs2012,2015,2017,cmake3.81,git,but what is wrong?

**Comment by MrJiangSheng** [comment]
I unstall the git,and the problem become this:
Microsoft Windows [版本 10.0.14393]
(c) 2016 Microsoft Corporation。保留所有权利。

C:\Windows\system32>cd C:\Users\Administrator\Desktop\vcpkg-master

C:\Users\Administrator\Desktop\vcpkg-master>bootstrap-vcpkg
Microsoft (R) 生成引擎版本 15.1.1012.6693
版权所有(C) Microsoft Corporation。保留所有权利。

生成启动时间为 2017/5/9/周二 16:57:59。
     1>节点 1 上的项目“C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\dirs.proj”(默认目标)。
     1>项目“C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\dirs.proj”(1)正在节点 1 上生成“C:\Users\Administrator\Desktop\vc
       pkg-master\toolsrc\vcpkg\vcpkg.vcxproj”(2) (Clean 个目标)。
     2>CoreClean:
         正在创建目录“Release\”。
     2>项目“C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\vcpkg\vcpkg.vcxproj”(2)正在节点 1 上生成“C:\Users\Administrator\
       Desktop\vcpkg-master\toolsrc\vcpkglib\vcpkglib.vcxproj”(3) (Clean 个目标)。
     3>CoreClean:
         正在创建目录“Release\”。
     3>已完成生成项目“C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\vcpkglib\vcpkglib.vcxproj”(Clean 个目标)的操作。
     2>已完成生成项目“C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\vcpkg\vcpkg.vcxproj”(Clean 个目标)的操作。
     1>项目“C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\dirs.proj”(1)正在节点 1 上生成“C:\Users\Administrator\Desktop\vc
       pkg-master\toolsrc\vcpkgmetricsuploader\vcpkgmetricsuploader.vcxproj”(4) (Clean 个目标)。
     4>CoreClean:
         正在创建目录“Release\”。
     4>已完成生成项目“C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\vcpkgmetricsuploader\vcpkgmetricsuploader.vcxproj”(C
       lean 个目标)的操作。
     1>项目“C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\dirs.proj”(1)正在节点 1 上生成“C:\Users\Administrator\Desktop\vc
       pkg-master\toolsrc\vcpkg\vcpkg.vcxproj”(2:2) (Build 个目标)。
   2:2>项目“C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\vcpkg\vcpkg.vcxproj”(2:2)正在节点 1 上生成“C:\Users\Administrato
       r\Desktop\vcpkg-master\toolsrc\vcpkglib\vcpkglib.vcxproj”(3:4) (默认目标)。
     3>PrepareForBuild:
         正在创建目录“C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\Release\”。
         正在创建目录“Release\vcpkglib.tlog\”。
       InitializeBuildStatus:
         正在创建“Release\vcpkglib.tlog\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
       ClCompile:
         D:\Program Files\VS2017\VC\Tools\MSVC\14.10.25017\bin\HostX86\x86\CL.exe /c /I..\include /Zi /nologo /W3 /WX-
         /diagnostics:classic /sdl /MP /O2 /Oi /Oy- /GL /D DISABLE_METRICS=0 /D "VCPKG_VERSION=-unknownhash" /D _MBCS /
         D NDEBUG /D _MBCS /Gm- /EHsc /MD /GS /Gy /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Yc"pch.h" /Fp"Releas
         e\vcpkglib.pch" /Fo"Release\\" /Fd"Release\vcpkglib.pdb" /Gd /TP /analyze- /errorReport:queue /std:c++latest .
         .\src\pch.cpp
         pch.cpp
     3>C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\include\pch.h(28): fatal error C1083: 无法打开包括文件: “shlobj.h”:
       No such file or directory [C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\vcpkglib\vcpkglib.vcxproj]
     3>已完成生成项目“C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\vcpkglib\vcpkglib.vcxproj”(默认目标)的操作 - 失败。
     2>已完成生成项目“C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\vcpkg\vcpkg.vcxproj”(Build 个目标)的操作 - 失败。
     1>已完成生成项目“C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\dirs.proj”(默认目标)的操作 - 失败。

生成失败。

       “C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\dirs.proj”(默认目标) (1) ->
       “C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\vcpkg\vcpkg.vcxproj”(Build 目标) (2:2) ->
       “C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\vcpkglib\vcpkglib.vcxproj”(默认目标) (3:4) ->
       (ClCompile 目标) ->
         C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\include\pch.h(28): fatal error C1083: 无法打开包括文件: “shlobj.h”
       : No such file or directory [C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\vcpkglib\vcpkglib.vcxproj]

    0 个警告
    1 个错误

已用时间 00:00:02.42
Copy-Item : 找不到路径“C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\Release\vcpkg.exe”，因为该路径不存在。
所在位置 C:\Users\Administrator\Desktop\vcpkg-master\scripts\bootstrap.ps1:34 字符: 5
+     Copy-Item $vcpkgSourcesPath\Release\vcpkg.exe $vcpkgRootDir\vcpkg ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Admini...lease\vcpkg.exe:String) [Copy-Item], ItemNotFoundExce
   ption
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand

Copy-Item : 找不到路径“C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\Release\vcpkgmetricsuploader.exe”，因为该
路径不存在。
所在位置 C:\Users\Administrator\Desktop\vcpkg-master\scripts\bootstrap.ps1:35 字符: 5
+     Copy-Item $vcpkgSourcesPath\Release\vcpkgmetricsuploader.exe $vcp ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Admini...icsuploader.exe:String) [Copy-Item], ItemNotFoundExce
   ption
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand

**Comment by MrJiangSheng** [comment]
I unstall the git,and the problem become this:
Microsoft Windows [版本 10.0.14393]
(c) 2016 Microsoft Corporation。保留所有权利。

C:\Windows\system32>cd C:\Users\Administrator\Desktop\vcpkg-master

C:\Users\Administrator\Desktop\vcpkg-master>bootstrap-vcpkg
Microsoft (R) 生成引擎版本 15.1.1012.6693
版权所有(C) Microsoft Corporation。保留所有权利。

生成启动时间为 2017/5/9/周二 16:57:59。
     1>节点 1 上的项目“C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\dirs.proj”(默认目标)。
     1>项目“C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\dirs.proj”(1)正在节点 1 上生成“C:\Users\Administrator\Desktop\vc
       pkg-master\toolsrc\vcpkg\vcpkg.vcxproj”(2) (Clean 个目标)。
     2>CoreClean:
         正在创建目录“Release\”。
     2>项目“C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\vcpkg\vcpkg.vcxproj”(2)正在节点 1 上生成“C:\Users\Administrator\
       Desktop\vcpkg-master\toolsrc\vcpkglib\vcpkglib.vcxproj”(3) (Clean 个目标)。
     3>CoreClean:
         正在创建目录“Release\”。
     3>已完成生成项目“C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\vcpkglib\vcpkglib.vcxproj”(Clean 个目标)的操作。
     2>已完成生成项目“C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\vcpkg\vcpkg.vcxproj”(Clean 个目标)的操作。
     1>项目“C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\dirs.proj”(1)正在节点 1 上生成“C:\Users\Administrator\Desktop\vc
       pkg-master\toolsrc\vcpkgmetricsuploader\vcpkgmetricsuploader.vcxproj”(4) (Clean 个目标)。
     4>CoreClean:
         正在创建目录“Release\”。
     4>已完成生成项目“C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\vcpkgmetricsuploader\vcpkgmetricsuploader.vcxproj”(C
       lean 个目标)的操作。
     1>项目“C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\dirs.proj”(1)正在节点 1 上生成“C:\Users\Administrator\Desktop\vc
       pkg-master\toolsrc\vcpkg\vcpkg.vcxproj”(2:2) (Build 个目标)。
   2:2>项目“C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\vcpkg\vcpkg.vcxproj”(2:2)正在节点 1 上生成“C:\Users\Administrato
       r\Desktop\vcpkg-master\toolsrc\vcpkglib\vcpkglib.vcxproj”(3:4) (默认目标)。
     3>PrepareForBuild:
         正在创建目录“C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\Release\”。
         正在创建目录“Release\vcpkglib.tlog\”。
       InitializeBuildStatus:
         正在创建“Release\vcpkglib.tlog\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
       ClCompile:
         D:\Program Files\VS2017\VC\Tools\MSVC\14.10.25017\bin\HostX86\x86\CL.exe /c /I..\include /Zi /nologo /W3 /WX-
         /diagnostics:classic /sdl /MP /O2 /Oi /Oy- /GL /D DISABLE_METRICS=0 /D "VCPKG_VERSION=-unknownhash" /D _MBCS /
         D NDEBUG /D _MBCS /Gm- /EHsc /MD /GS /Gy /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Yc"pch.h" /Fp"Releas
         e\vcpkglib.pch" /Fo"Release\\" /Fd"Release\vcpkglib.pdb" /Gd /TP /analyze- /errorReport:queue /std:c++latest .
         .\src\pch.cpp
         pch.cpp
     3>C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\include\pch.h(28): fatal error C1083: 无法打开包括文件: “shlobj.h”:
       No such file or directory [C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\vcpkglib\vcpkglib.vcxproj]
     3>已完成生成项目“C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\vcpkglib\vcpkglib.vcxproj”(默认目标)的操作 - 失败。
     2>已完成生成项目“C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\vcpkg\vcpkg.vcxproj”(Build 个目标)的操作 - 失败。
     1>已完成生成项目“C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\dirs.proj”(默认目标)的操作 - 失败。

生成失败。

       “C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\dirs.proj”(默认目标) (1) ->
       “C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\vcpkg\vcpkg.vcxproj”(Build 目标) (2:2) ->
       “C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\vcpkglib\vcpkglib.vcxproj”(默认目标) (3:4) ->
       (ClCompile 目标) ->
         C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\include\pch.h(28): fatal error C1083: 无法打开包括文件: “shlobj.h”
       : No such file or directory [C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\vcpkglib\vcpkglib.vcxproj]

    0 个警告
    1 个错误

已用时间 00:00:02.42
Copy-Item : 找不到路径“C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\Release\vcpkg.exe”，因为该路径不存在。
所在位置 C:\Users\Administrator\Desktop\vcpkg-master\scripts\bootstrap.ps1:34 字符: 5
+     Copy-Item $vcpkgSourcesPath\Release\vcpkg.exe $vcpkgRootDir\vcpkg ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Admini...lease\vcpkg.exe:String) [Copy-Item], ItemNotFoundExce
   ption
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand

Copy-Item : 找不到路径“C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\Release\vcpkgmetricsuploader.exe”，因为该
路径不存在。
所在位置 C:\Users\Administrator\Desktop\vcpkg-master\scripts\bootstrap.ps1:35 字符: 5
+     Copy-Item $vcpkgSourcesPath\Release\vcpkgmetricsuploader.exe $vcp ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Admini...icsuploader.exe:String) [Copy-Item], ItemNotFoundExce
   ption
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand

**Comment by ras0219-msft** [comment]
Hi @MrJiangSheng,

>C:\Users\Administrator\Desktop\vcpkg-master\toolsrc\include\pch.h(28): fatal error C1083: 无法打开包括文件: “shlobj.h”

This indicates that you don't have the Windows Desktop SDK installed. Unfortunately, in one version of VS2017, this was not checked by default under certain workloads.

Please ensure the optional box "Windows 10 SDK (10.0......) for Desktop C++" under the "Desktop Development with C++" workload is checked in the VS 2017 installer.

**Comment by MrJiangSheng** [comment]
dear sir,thanks for you help,know I get a new error:

```
Download cmake
No suitable version of cmake was found (requires 3.8.0 or higher). Download portable version?
[Y] Yes  [N] No  [A] Always Allow Downloads  [?] 帮助 (默认值为“Y”): ?
Y - Downloads cmake v3.8.0 app-locally.
N - Does not download cmake.
A - Downloads cmake v3.8.0 app-locally.(Future download prompts will not be displayed)
[Y] Yes  [N] No  [A] Always Allow Downloads  [?] 帮助 (默认值为“Y”): Y
Launching powershell failed or was denied

C:\Users\Administrator\Desktop\vcpkg-master>vcpkg install sdl2 curl
The following packages will be built and installed:
    curl:x86-windows
  * libssh2:x86-windows
  * openssl:x86-windows
    sdl2:x86-windows
  * zlib:x86-windows
Additional packages (*) will be installed to complete this operation.
Building package sdl2:x86-windows...
Launching powershell failed or was denied``
```

**Comment by ras0219-msft** [comment]
It seems we have an issue in our download scripts on your system. The easiest workaround is to go to https://cmake.org/download/ and [install CMake 3.8.1](https://cmake.org/files/v3.8/cmake-3.8.1-win32-x86.msi).

For additional debugging information, you can add `--debug` on any vcpkg command line.

**Comment by MrJiangSheng** [comment]
Dir sir.thanks  very much,and I have get it now.
