### ISSUE TITLE
[expat:x86-windows] build failure

### ISSUE THREAD

**Issue by pingpongo** [microsoft/vcpkg#10552]
**Host Environment**
- OS: [Windows 10.]
- Compiler: 2020.02.04-nohash

**To Reproduce**
`./vcpkg install gtk:x86-windows`

**Failure logs** 
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: "C:/Program Files (x86)/CMake/bin/cmake.exe" -E tar xjf C:/Users/Civico/source/repos/vcpkg/downloads/libexpat-libexpat-R_2_2_7.tar.gz
    Working Directory: C:/Users/Civico/source/repos/vcpkg/buildtrees/expat/src/TEMP
    Error code: 1

Call Stack (most recent call first):
  scripts/cmake/vcpkg_extract_source_archive.cmake:43 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_extract_source_archive_ex.cmake:108 (vcpkg_extract_source_archive)
  scripts/cmake/vcpkg_from_github.cmake:139 (vcpkg_extract_source_archive_ex)
  ports/expat/portfile.cmake:6 (vcpkg_from_github)
  scripts/ports.cmake:90 (include)

Error: Building package expat:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: expat:x86-windows
  Vcpkg version: 2020.02.04-nohash

**Additional context**
I tried installing the x64 version but had the same problem, just with the package "Package: expat:x64-windows"

**Comment by linquize** [comment]
What version of cmake (`C:/Program Files (x86)/CMake/bin/cmake.exe`) did you use?

**Comment by JackBoosY** [comment]
Well, that's a cmake bug, we need to wait for cmake to fix it officially.

Related: #10336 #6059 #10492 #5951 #9078 #8603 ...

**Comment by JackBoosY** [comment]
Hi @pingpongo Could you install cmake 3.17.0 manually and try again?
If it works, we will consider to update cmake to 3.17.0 later.

**Comment by pingpongo** [comment]
Issue is fixed, due to a windows setting I was not able to extract a file.

Solution is courtesy of this guy -> https://github.com/Microsoft/vcpkg/issues/6059#issuecomment-483141555

"The UTF-8 beta in intl.cpl > Administrative > Change system locale... needs to be unticked for cmake (3.16) to function properly."

**Comment by pingpongo** [comment]
> What version of cmake (`C:/Program Files (x86)/CMake/bin/cmake.exe`) did you use?

3.16 :)
