### ISSUE TITLE
[mdnsresponder:x64-windows-static-md] build failure

### ISSUE THREAD

**Issue by Krzmbrzl** [microsoft/vcpkg#10553]
**Host Environment**
- OS: Windows 7
- Compiler: revision

**To Reproduce**
`./vcpkg install mdnsresponder:x64-windows-static-md`

**Failure logs**
```
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: msbuild D:/vcpkg/buildtrees/mdnsresponder/src/ponder-765-35f
1c06423/mDNSResponder.sln /p:Configuration=Release /t:dns-sd /p:Platform=x64 /p:
PlatformToolset=v142 /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /p:Wind
owsTargetPlatformVersion=10.0.18362.0 /m /p:WholeProgramOptimization=false
    Working Directory: D:/vcpkg/buildtrees/mdnsresponder/x64-windows-static-md-r
el
    Error code: 1
    See logs for more information:
      D:\vcpkg\buildtrees\mdnsresponder\build-x64-windows-static-md-rel-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_msbuild.cmake:119 (vcpkg_execute_required_process)
  ports/mdnsresponder/portfile.cmake:60 (vcpkg_build_msbuild)
  scripts/ports.cmake:90 (include)


Error: Building package mdnsresponder:x64-windows-static-md failed with: BUILD_F
AILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: mdnsresponder:x64-windows-static-md
  Vcpkg version: 2020.02.04-nohash-external
```

**Additional context**
The relevant line from the error from the log seems to be
```
     3>dll.rc(10): fatal error RC1015: cannot open include file 'afxres.h'. [D:\vcpkg\buildtrees\mdnsresponder\src\ponder-765-35f1c06423\mDNSWindows\DLL\dnssd.vcxproj]
```
`afxres.h` seems to be part of the MFC framework, so I went ahead and installed `C++ v14.24 MFC for v142 build tools (x86 & x64)` via the Visual Studio 2019 installer. The error stays the same though (I also tried rebooting in-between).

[build-x64-windows-static-md-rel-out.log](https://github.com/microsoft/vcpkg/files/4382094/build-x64-windows-static-md-rel-out.log)

**Comment by Krzmbrzl** [comment]
Okay I installed all MFC versions that were listed for VS 2019 build tools and that resolved the problem. Guess the single one I had before was the wrong one... Don't know which of all these version was the one that fixed the problem in the end.

**Comment by PhoebeHui** [comment]
@Krzmbrzl, glad to see this issue has been resolved.
