### ISSUE TITLE
Support vcpkg integrate bash on Windows

### ISSUE THREAD

**Issue by linquize** [microsoft/vcpkg#10554]
To support `vcpkg integrate bash` on Windows as well.

based on existing code, modify something
1. For `home_path`, Get User's directory instead of `%HOME%`
2. Write `.bashrc` with '/' style path

**Comment by Voskrese** [comment]
bash/sh msys or wsl?

**Comment by linquize** [comment]
It doesn't matter you use what bash. When you write .bashrc in User's directory

**Comment by heydojo** [comment]
Git bash? https://initgeek.com/how-to-use-git-git-bash-and-github/
WSL cross compilation?

@linquize would you mind please clarifying what it is you mean please?
vcpkg already supports invocation via Windows built in command processor (cmd.exe) and also powershell.
bash isn't a native shell on Windows, so I don't know why or how it would be possible to support that officially, unless you can may be more specific about a port of bash for Windows which exists that you have tried and is actively maintained.
The only one which springs to mind for me is git bash but I don't use it myself.

**Comment by linquize** [comment]
Simply append one line to the end of `~/.bashrc`, which is `C:\Users\user\.bashrc`

No need to find where win32 bash is located. 

Unrelated to WSL.
