### ISSUE TITLE
[New Port Request] elements

### ISSUE THREAD

**Issue by tGstep** [microsoft/vcpkg#10551]
Library name: elements

Library description: Elements is a lightweight, fine-grained, resolution independent, modular GUI library.

Source repository URL: https://github.com/cycfi/elements

Project homepage (if different from the source repository): https://cycfi.github.io/elements/

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by daljit97** [comment]
I think Elements would really be a great addition to vcpkg and I would also like to see a port.
