### ISSUE TITLE
Gnu make on windows 10

### ISSUE THREAD

**Issue by manang** [microsoft/vcpkg#10561]
I'm trying to use vcpkg on windows 10 with gnu make.
My problem is that when I launch cmake to generate the gnu makefiles, cmake ignore the vcpkg toolchain.
do you have a solution?
Thanks

**Comment by linquize** [comment]
How do you write your `CMakeLists.txt`?  Could you post it?

**Comment by manang** [comment]
HI,
this is the cmakefile
https://github.com/FDio/cicn/blob/cframework/master/libparc/CMakeLists.txt

**Comment by PhoebeHui** [comment]
@manang, have you figured out this issue finally?

**Comment by PhoebeHui** [comment]
@manang, do you mind to provide us the steps you have tried? I will have a try and see if we can figure out this.

**Comment by dg0yt** [comment]
>  I launch cmake to generate the gnu makefiles

In terms of cmake generators, are you refering to MSYS makefiles, MinGW makefiles or UNIX Makefiles?

**Comment by manang** [comment]
ok, my problem is about 1 year and more ago.
I'm able to generate the nmakefile, so, I can compile the source code with nmake.
I launched
cmake <src_folder> -DCMAKE_TOOLCHAIN_FILE=<path_vcpkg_toolchain>
without the parameter -G.
the cmake file ignores CMAKE_TOOLCHAIN_FILE parameter
thanks

**Comment by dg0yt** [comment]
Note that CMAKE_TOOLCHAIN_FILE is only useful the first time you run cmake for a build directory. After this, most toolchain-related cmake cache variables are already set and will not be updaded unless you explicitly set or unset them. This is cmake behaviour.
