### ISSUE TITLE
static ports: missing pdb symbols in vcpkg/buildtrees

### ISSUE THREAD

**Issue by robertobernabe** [microsoft/vcpkg#10564]
**Describe the bug**
When installing static version of a port no debug symbols are generated in the `vcpkg\buildtrees` directory for debug builds. For that reason the cmake macro `vcpkg_copy_pdbs()` does not copy any pdbs into the corresponding directories.

**Environment**
- OS: Windows
- Compiler: MSVS 2019

**To Reproduce**
1. ./vcpkg install gtest:x64-windows-static
2. See missing *.pbd(s)
```
vcpkg\installed\x64-windows-static\debug>tree /f /a
Folder PATH listing
Volume serial number is 7A3F-D1FD
C:.
\---lib
    |   gmockd.lib
    |   gtestd.lib
    |
    +---manual-link
    |   |   gmock_maind.lib
    |   |   gtest_maind.lib
    |   |
    |   \---pkgconfig
    |           gmock_main.pc
    |           gtest_main.pc
    |
    \---pkgconfig
            gmock.pc
            gtest.pc
```

**Expected behavior**

**Failure logs** 
[install-x64-windows-static-dbg-out.log](https://github.com/microsoft/vcpkg/files/4386587/install-x64-windows-static-dbg-out.log)
[install-x64-windows-static-rel-out.log](https://github.com/microsoft/vcpkg/files/4386588/install-x64-windows-static-rel-out.log)
[config-x64-windows-static-out.log](https://github.com/microsoft/vcpkg/files/4386589/config-x64-windows-static-out.log)
[stdout-x64-windows-static.log](https://github.com/microsoft/vcpkg/files/4386590/stdout-x64-windows-static.log)
[x64-windows-static.vcpkg_abi_info.txt](https://github.com/microsoft/vcpkg/files/4386591/x64-windows-static.vcpkg_abi_info.txt)
[patch-x64-windows-static-1-err.log](https://github.com/microsoft/vcpkg/files/4386592/patch-x64-windows-static-1-err.log)
[patch-x64-windows-static-0-err.log](https://github.com/microsoft/vcpkg/files/4386593/patch-x64-windows-static-0-err.log)

**Additional context**
For the triplet `x64-windows` it's like expected
```
vcpkg\installed\x64-windows\debug>tree /f /a
Folder PATH listing
Volume serial number is 7A3F-D1FD
C:.
+---bin
|       gmockd.dll
|       gmockd.pdb
|       gmock_maind.dll
|       gmock_maind.pdb
|       gtestd.dll
|       gtestd.pdb
|       gtest_maind.dll
|       gtest_maind.pdb
|
\---lib
    |   gmockd.lib
    |   gtestd.lib
    |
    +---manual-link
    |   |   gmock_maind.lib
    |   |   gtest_maind.lib
    |   |
    |   \---pkgconfig
    |           gmock_main.pc
    |           gtest_main.pc
    |
    \---pkgconfig
            gmock.pc
            gtest.pc
```

**Comment by PhoebeHui** [comment]
Related to https://github.com/microsoft/vcpkg/issues/10461

**Comment by alek-d** [comment]
For me it looks like PDBs are not generated for static libraries.

**Comment by Mike4Online** [comment]
The static libraries I have built with vcpkg embed the debug symbols directly into the .lib file, rather than placing debug symbols into a separate .pdb file.  This is directed by the /Z7 command-line parameter on each cl.exe (compiler) call.  I would also like an easy way to override this default behavior and have the option to generate distinct .pdb files for each .lib built with vcpkg.

**Comment by FrankHeimes** [comment]
When building the `vcpkg` packages, the compiler/linker embed the full paths to all of the source files in the PDB file. And with `/Z7`, the PDB file is embedded into the LIB file. So the LIB file should hold the full paths of all source files.

We keep the correct versions of the `installed` folder in TFS with our product source code. So after storing the LIB file in TFS, in order for source code debugging to work, the LIB file needs to be indexed for TFS and all relevant sources need to be accessible through TFS.

I haven't found any documentation on how to do this properly after building the `vcpkg` packages. Any hints?

**Comment by JackBoosY** [comment]
As @FrankHeimes said, in static build we don't need pdbs.
