### ISSUE TITLE
[vcpkg]report error while runing command 'vcpkg install osg'

### ISSUE THREAD

**Issue by LSL-ding** [microsoft/vcpkg#10577]
when I implement command ''vcpkg install osg' ,It reported error in last step.
enviroment:
 Package: osg:x64-windows
  Vcpkg version: 2020.02.04-nohash

error:
![image](https://user-images.githubusercontent.com/52522394/77736785-cba81280-7047-11ea-95b6-4e458ab1e9b1.png)

**Comment by LSL-ding** [comment]
It should be the last step to install osg,It takes long time,help please

**Comment by LSL-ding** [comment]
I have installed cmake-3.17.0

**Comment by Voskrese** [comment]
error log files attach

**Comment by LSL-ding** [comment]
> error log files attach
![image](https://user-images.githubusercontent.com/52522394/77754007-7bd84400-7065-11ea-91d4-00e6d5187e55.png)
sorry I don't upload the file,this is its last several line in the log

**Comment by linquize** [comment]
Did you Install Visual Studio **English Language Pack**?

**Comment by linquize** [comment]
The example application `osgmovie` build failed because of `SDL/SDL.h` not found.

There is already `fix-sdl.patch` in `ports/osg`, but not correct.
Should use `SDL2/SDL.h` when `USE_SDL2`, use `SDL/SDL.h` when `USE_SDL`

**Comment by LSL-ding** [comment]
thank you all, @linquize and @Voskrese ,I've solved this error by installing sdl1
