### ISSUE TITLE
 How do I install

### ISSUE THREAD

**Issue by rafaelwitter** [microsoft/vcpkg#10571]
./bootstrap-vcpkg.sh: 219: [: Illegal number: 
-- The C compiler identification is GNU 7.5.0
CMake Error at /home/.../Desktop/C/vcpkg/downloads/tools/cmake-3.14.0-linux/cmake-3.14.0-Linux-x86_64/share/cmake-3.14/Modules/CMakeDetermineCXXCompiler.cmake:48 (message):
  Could not find compiler set in environment variable CXX:

  g++.

Call Stack (most recent call first):
  CMakeLists.txt:3 (project)

CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!

how to resolve?

**Comment by JackBoosY** [comment]
Hi @rafaelwitter, thanks for reporting this issue.
Please install English Language Package using Visual Studio Installer first.

Thanks.

**Comment by linquize** [comment]
Did you install `g++`?

Test with
`g++ --version`

**Comment by JackBoosY** [comment]
Hi @rafaelwitter, thanks for reporting this issue.
Please install gcc first.

Thanks.

**Comment by rafaelwitter** [comment]
> Did you install `g++`?
> 
> Test with
> `g++ --version`

yes, g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
i dont know what to do

**Comment by linquize** [comment]
What shell did you use? line 219 has error.

`ls -l /bin/sh`

**Comment by rafaelwitter** [comment]
> What shell did you use? line 219 has error.
> 
> `ls -l /bin/sh`

this commands output this: 
lrwxrwxrwx 1 root root 4 Jan 24 13:36 /bin/sh -> dash

**Comment by linquize** [comment]
`echo "$CXX"`

**Comment by JackBoosY** [comment]
@dan-shaw Could you please have a look?

Thanks.

**Comment by rafaelwitter** [comment]
I’ve already done. It was missing a reboot system only. Thanks for the supporting.
