### ISSUE TITLE
Add rocksdb 

### ISSUE THREAD

**Issue by dibyendumajumdar** [Microsoft/vcpkg#1057]
The rocksdb project supports CMake based build on Windows so it should be possible to add it to vcpkg. If no one else works on this then I will look at it in the later part of June as until then I have some other commitments.

**Comment by atkawa7** [comment]
@dibyendumajumdar See #1368

**Comment by dibyendumajumdar** [comment]
@atkawa7 Cool. I tried working on this too but got stuck as the Rocksdb 5.4.6 using VS2017. 

https://github.com/facebook/rocksdb/issues/2262

Apparently it is fixed in the master branch but no release yet. How did you resolve this issue?

**Comment by atkawa7** [comment]
@dibyendumajumdar I ended up using the master branch

**Comment by atkawa7** [comment]
@ras0219-msft could you close this?
