### ISSUE TITLE
couldn't find the Visual Studio

### ISSUE THREAD

**Issue by namanjain0505** [microsoft/vcpkg#10576]
couldn't run the file the error shown is
Could not find Visual Studio. VS2015 or VS2017 (with C++) needs to be installed.
At D:\soft\vcpkg-master\vcpkg-master\scripts\bootstrap.ps1:143 char:9
+         throw "Could not find Visual Studio. VS2015 or VS2017 (with C ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find ...o be installed.:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find Visual Studio. VS2015 or VS2017 (with C++) needs to be installed.

**The details of Visual Studio are**
Version: 1.43.2 (system setup)
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:38:38.248Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by linquize** [comment]
You reported the version information of VSCode, which is not Visual Studio.

You must install Visual Studio 2015.3, 2017 or 2019 with C++ features.

**Comment by JackBoosY** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
