### ISSUE TITLE
[sdl2-gfx] build failure

### ISSUE THREAD

**Issue by prafulla-kr** [microsoft/vcpkg#10570]
**Host Environment**
- OS: [Ubuntu]
- Compiler: 7.5.0
[install-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/4389456/install-x64-linux-dbg-out.log)

**To Reproduce**
`./vcpkg install sdl2-gfx`

**Failure logs** 
buildtrees/sdl2-gfx/src/1.0.4-86ce4cf464/SDL2_rotozoom.c
/home/prafulla/vcpkg/buildtrees/sdl2-gfx/src/1.0.4-86ce4cf464/SDL2_rotozoom.c:31:10: fatal error: windows.h: No such file or directory
 #include <windows.h>
          ^~~~~~~~~~~
compilation terminated.
**Additional context**
I just commented the lines in SDL2_rootzoom.c and the issue was resolved.

**Comment by NancyLi1013** [comment]
Hi @prafulla-kr 
Thanks for posting this issue.
I have submitted the PR #10575 to fix it.

**Comment by NancyLi1013** [comment]
This issue should be fixed now. Please try to update vcpkg and rebuild it.
