### ISSUE TITLE
[build path]Error: Building package libjpeg-turbo:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by LSL-ding** [microsoft/vcpkg#10573]
when I implement  the command  './vcpkg install osg',there is an error
enviroment:
  Package: libjpeg-turbo:x64-windows
  Vcpkg version: 2020.02.04-nohash
error report:

-- Downloading https://github.com/libjpeg-turbo/libjpeg-turbo/archive/166e34213e4f4e2363ce058a7bcc69fd03e38b76.tar.gz... Failed. Status: 7;"Couldn't connect to server"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:175 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:132 (vcpkg_download_distfile)
  ports/libjpeg-turbo/portfile.cmake:3 (vcpkg_from_github)
  scripts/ports.cmake:90 (include)

Error: Building package libjpeg-turbo:x64-windows failed with: BUILD_FAILED

**Comment by JackBoosY** [comment]
It seems that you cannot successfully connect to the server.
Please use this url:
[libjpeg-turbo-libjpeg-turbo-2.0.3.tar.gz](https://github.com/microsoft/vcpkg/files/4391111/libjpeg-turbo-libjpeg-turbo-2.0.3.tar.gz)
Download it and put it into _VCPKG_PATH/downloads_ then rebuild osg.

Thanks.

**Comment by LSL-ding** [comment]
> It seems that you cannot successfully connect to the server.
> Please use this url:
> [libjpeg-turbo-libjpeg-turbo-2.0.3.tar.gz](https://github.com/microsoft/vcpkg/files/4391111/libjpeg-turbo-libjpeg-turbo-2.0.3.tar.gz)
> Download it and put it into _VCPKG_PATH/downloads_ then rebuild osg.
> 
> Thanks.

thank you very much,but it alway report this error when downloading package,I'm going to download all package this but afraid of geting wrong version

**Comment by JackBoosY** [comment]
This is an unofficial mirror branch, but it is not synchronized to the master branch:
https://github.com/JackBoos/vcpkg/tree/mirror_zhCN

**Comment by johnnyontheweb** [comment]
> It seems that you cannot successfully connect to the server.
> Please use this url:
> [libjpeg-turbo-libjpeg-turbo-2.0.3.tar.gz](https://github.com/microsoft/vcpkg/files/4391111/libjpeg-turbo-libjpeg-turbo-2.0.3.tar.gz)
> Download it and put it into _VCPKG_PATH/downloads_ then rebuild osg.

This is not working, install will download it again. Where this can be changed and forced to "libjpeg-turbo-libjpeg-turbo-2.0.3"?

**Comment by JackBoosY** [comment]
> This is not working, install will download it again. Where this can be changed and forced to "libjpeg-turbo-libjpeg-turbo-2.0.3"?

Yeah, this port was updated to 2.1.4 now. Please use [this file](https://github.com/microsoft/vcpkg/files/10524322/libjpeg-turbo-2.1.4.tar.gz) instead.

**Comment by johnnyontheweb** [comment]
Thanks for your reply, but unfortunately the install command re-download the wrong package again, see below.

`vcpkg install libvpx:x64-windows-static libyuv:x64-windows-static opus:x64-windows-static
Computing installation plan...
The following packages will be built and installed:
  * libjpeg-turbo[core]:x64-windows-static -> 2.0.6#2
    libvpx[core]:x64-windows-static -> 1.10.0#2
    libyuv[core]:x64-windows-static -> 2021-04-15
    opus[core]:x64-windows-static -> 1.3.1#6
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows-static...
Restored 0 packages from C:\Users\Giovanni\AppData\Local\vcpkg\archives in 187.4 us. Use --debug to see more details.
Starting package 1/4: libjpeg-turbo:x64-windows-static
Building package libjpeg-turbo[core]:x64-windows-static...
-- Downloading https://github.com/libjpeg-turbo/libjpeg-turbo/archive/10ba6ed3365615ed5c2995fe2d240cb2d5000173.tar.gz -> libjpeg-turbo-libjpeg-turbo-10ba6ed3365615ed5c2995fe2d240cb2d5000173.tar.gz...
-- Cleaning sources at C:/Users/Giovanni/.cargo/vcpkg/buildtrees/libjpeg-turbo/src/b2d5000173-96baffe5bc.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/Giovanni/.cargo/vcpkg/downloads/libjpeg-turbo-libjpeg-turbo-10ba6ed3365615ed5c2995fe2d240cb2d5000173.tar.gz
-- Applying patch add-options-for-exes-docs-headers.patch
-- Applying patch workaround_cmake_system_processor.patch
-- Applying patch fix-incompatibility-for-c11-c17.patch
-- Using source at C:/Users/Giovanni/.cargo/vcpkg/buildtrees/libjpeg-turbo/src/b2d5000173-96baffe5bc.clean
-- Configuring x64-windows-static
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: ninja -v
    Working Directory: C:/Users/Giovanni/.cargo/vcpkg/buildtrees/libjpeg-turbo/x64-windows-static-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\Users\Giovanni\.cargo\vcpkg\buildtrees\libjpeg-turbo\config-x64-windows-static-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:345 (vcpkg_execute_required_process)
  ports/libjpeg-turbo/portfile.cmake:41 (vcpkg_configure_cmake)
  scripts/ports.cmake:142 (include)


Error: Building package libjpeg-turbo:x64-windows-static failed with: BUILD_FAILED`

Where this can be changed?

**Comment by JackBoosY** [comment]
can you please git pull vcpkg then try again?

**Comment by johnnyontheweb** [comment]
thanks, it worked!

**Comment by QYH2MMT4EVER** [comment]
> 

Can you teach me how to git pull vcpkg?i have the same problem ! plz tell me the git bash command to git pull vcpkg!thx!

**Comment by JackBoosY** [comment]
> > 
> 
> Can you teach me how to git pull vcpkg?i have the same problem ! plz tell me the git bash command to git pull vcpkg!thx!

Just run command `git pull` in your vcpkg root path.
