### ISSUE TITLE
[installing osg by vcpkg]after running command "vcpkg install osg" successfully

### ISSUE THREAD

**Issue by LSL-ding** [microsoft/vcpkg#10587]
After runing command "vcpkg install osg" successfully,I wanna test if it works,so I opened osglogo.exe.But it reported  errors :"can't find zlib1.dll" ,"can;t find fontconfig.dll"
![image](https://user-images.githubusercontent.com/52522394/77813855-fd23eb00-70e6-11ea-9f83-bdd11759ebf7.png)
![image](https://user-images.githubusercontent.com/52522394/77813868-13ca4200-70e7-11ea-917a-ff757d007aec.png)
And then I tested in visual studio 2019,there are errors too.#include "stdafx.h"
code in VS:
#include <osgViewer/Viewer>
#include <osgDB/ReadFile>
#include"pch.h"
int main()
{
	osgViewer::Viewer viewer;
	viewer.setSceneData(osgDB::readNodeFile("cow.osg"));
	return viewer.run();
}
error:
can't open source file stdafx.h
can't open source file osgViewer/Viewer
can't open source file osgDB/ReadFile
........
I have added path "E:\imgcourse\vcpkg\buildtrees\osg\x64-windows-rel\bin" to system path,

**Comment by NancyLi1013** [comment]
Hi @LSL-ding 
Thanks for posting this issue.
Could you please help confirm how do you get `osglogo.exe`?
I checked this on my local and didn't find this file. Is this generated by feature `collada`?

**Comment by NancyLi1013** [comment]
Please let me know if you have any concerns about this issue.

**Comment by NancyLi1013** [comment]
I'm going to close this issue since there is no any response in a long time.
Please feel reopen this if it is still a problem for you.
