### ISSUE TITLE
Attempting to build zlib

### ISSUE THREAD

**Issue by drazenzadravec** [microsoft/vcpkg#10584]
```
-- Downloading http://www.zlib.net/zlib-1.2.11.tar.gz...
CMake Error at X:/Build/vcpkg/scripts/cmake/vcpkg_download_distfile.cmake:185 (file):
  file RENAME failed to rename

    /cygdrive/x/Build/vcpkg/X:/Build/vcpkg/downloads/temp/zlib1211.tar.gz

  to

    /cygdrive/x/Build/vcpkg/X:/Build/vcpkg/downloads/zlib1211.tar.gz

  because: No such file or directory

Call Stack (most recent call first):
  X:/Build/vcpkg/ports/zlib/portfile.cmake:5 (vcpkg_download_distfile)
  X:/Build/vcpkg/scripts/ports.cmake:90 (include)


Error: Building package zlib:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zlib:x86-windows
  Vcpkg version: 2020.02.04-nohash

Additionally, attach any relevant sections from the log files above.
```
[stdout-x86-windows.log](https://github.com/microsoft/vcpkg/files/4396176/stdout-x86-windows.log)
[x86-windows.vcpkg_abi_info.txt](https://github.com/microsoft/vcpkg/files/4396177/x86-windows.vcpkg_abi_info.txt)

**Comment by Voskrese** [comment]
`/cygdrive/x/Build/vcpkg/X:/Build/vcpkg/downloads/temp/zlib1211.tar.gz` path ?

/cygdrive/x/Build/vcpkg/  <<-->> X:/Build/vcpkg/downloads/temp/zlib1211.tar.gz

**Comment by linquize** [comment]
What command line did you enter in **cygwin**?

**Comment by drazenzadravec** [comment]
PowerShell command:

PS>vcpkg install zlib

Note: this was a complete new install of vcpkg, the first build attempt was zlib. After cloning with git, and calling .\bootstrap.bat all within powershell on a Windows 10 machine.

I have been using vcpkg for years now with previous version, I have built a considerable number of packages using vcpkg.

I decided to start a new fresh vcpkg for a new customer.

________________________________

**Comment by linquize** [comment]
Powershell? There is `/cygdrive`

**Comment by drazenzadravec** [comment]
I was able to get it working, installed vcpkg this morning and is working.

I removed same Environmental Variables and place the cygwin EV at the end.

I noticed that vcpkg was updated 18 hours before I started a new install.

I am not sure if changing the Environmental Variables and vcpkg changes corrected the issue, or if one or the other corrected the issue.

The vcpkg install was done using PowerShell.
________________________________

**Comment by Voskrese** [comment]
full log files attach

**Comment by JackBoosY** [comment]
Maybe this issue fixed in some PRs.
