### ISSUE TITLE
itk:x64-windows build failure

### ISSUE THREAD

**Issue by nicogerber** [microsoft/vcpkg#10581]
**Host Environment**
- OS: Windows 10
- Compiler: Visual Studio 2019

**To Reproduce**
`./vcpkg.exe install itk:x64-windows`

**Failure logs** 
The following packages will be built and installed:
    itk[core]:x64-windows
Starting package 1/1: itk:x64-windows
Building package itk[core]:x64-windows...
-- Using cached E:/vcpkg_dynamic/downloads/InsightSoftwareConsortium-ITK-v5.0.1.tar.gz
-- Using source at E:/vcpkg_dynamic/buildtrees/itk/src/v5.0.1-d4f3d9a818
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v
    Working Directory: E:/vcpkg_dynamic/buildtrees/itk/x64-windows-dbg
    See logs for more information:
      [E:\vcpkg_dynamic\buildtrees\itk\install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/4394585/install-x64-windows-dbg-out.log)

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/itk/portfile.cmake:67 (vcpkg_install_cmake)
  scripts/ports.cmake:90 (include)

Error: Building package itk:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: itk:x64-windows
  Vcpkg version: 2020.02.04-nohash-external

**Additional context**
- Might be related to #9891 but not sure
- It can't find the H5open symbol, however, the HDF5 library is correctly installed and I can find it manually:
`dumpbin /exports E:\vcpkg_dynamic\installed\x64-windows\lib\hdf5.lib | findstr H5open`

Thanks for your help!

**Comment by PhoebeHui** [comment]
@nicogerber, it's same issue with https://github.com/microsoft/vcpkg/issues/9891, duplicated to that issue. I will priotiry to investgate this issue next week, sorry for my late reply.
