### ISSUE TITLE
[pixel] List Linux dependencies

### ISSUE THREAD

**Issue by linquize** [microsoft/vcpkg#10593]
port: pixel
Please add warning message to list Linux dependencies
`apt-get install libglu1-mesa-dev`

**Comment by NancyLi1013** [comment]
@linquize 
Thanks for your above info.
It seems that only `libglu1-mesa-dev` is enough.
Could you help explain why we need to add `libxext-dev`?

**Comment by linquize** [comment]
Rebuild in clean environment, `libxext-dev` is NOT needed

**Comment by NancyLi1013** [comment]
Thanks for your update.
I will add this later.

**Comment by NancyLi1013** [comment]
The warning message has been added now.
