### ISSUE TITLE
Unable to find a libray 'painlessMesh' 

### ISSUE THREAD

**Issue by SJ-Suhas** [microsoft/vcpkg#10598]
I want to install a library painlessMesh, which can't be found by command `vcpkg search painlessMesh`

**Comment by linquize** [comment]
This library is not in vcpkg yet.

You should open an issue **Request a new port**

https://gitlab.com/painlessMesh/painlessMesh

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
