### ISSUE TITLE
[pixel] build failure in MSVC

### ISSUE THREAD

**Issue by linquize** [microsoft/vcpkg#10590]
**Host Environment**
- OS: Windows
- Compiler: VS2019

**To Reproduce**
`./vcpkg install pixel:x64-windows`

**Failure logs** 
```
C:\vcpkg\buildtrees\pixel\src\v0.3-7b31616cf1\pixel\src\Window.cpp(271) : error C4716: 'Pixel::Window::isPressed': must return a value
```

**Additional context**
This is due to missing return value in
https://github.com/dascandy/pixel/blob/1a3631429da9eeac5208584713f358ef0ab09e51/pixel/src/Window.cpp#L270

**Comment by NancyLi1013** [comment]
Hi @linquize 
Thanks for posting this issue.
Since `pixel ` source currently doesn't support this. I open an issue to upstream and hope to be fixed by them.

**Comment by sfhacker** [comment]
This open issue is OVER a year old. Will try to repro it locally.

**Comment by Cheney-W** [comment]
This issue has been fixed by https://github.com/dascandy/pixel/commit/c4411f67746fdd811aa5f8c102ac340e9eaf4ec5 in the upstream. Need update port version now.
