### ISSUE TITLE
Redirect bootstrap-vcpkg.sh in Msys2 bash to bootstrap.bat

### ISSUE THREAD

**Issue by linquize** [microsoft/vcpkg#10595]
Redirect `bootstrap-vcpkg.sh` in Msys2 bash to `bootstrap.bat`

In Msys2 bash, `uname -s` returns `MSYS_NT-6.1-7601` in Win7.

**Comment by Neumann-A** [comment]
@JackBoosY close? I think it already does this. At least in git bash I can execute either

**Comment by JackBoosY** [comment]
> @JackBoosY close? I think it already does this. At least in git bash I can execute either

git bash can, but msys2 bash can't.

**Comment by numericlee** [comment]
\vcpkg\bootstrap-vcpkg.bat
.vcpkgbootstrap-vcpkg.bat: command not found

do I need to chmod this?

**Comment by dg0yt** [comment]
> do I need to chmod this?

No. In a sh shell, you need forward slashes:
~~~sh
./vcpkg/bootstrap-vcpkg.bat
~~~
