### ISSUE TITLE
[libpq] build failure

### ISSUE THREAD

**Issue by EpoUnlimited** [microsoft/vcpkg#10592]
_**Version**_
Package: libpq:x86-windows
Vcpkg version: 2020.02.04-nohash

_**To Reproduce**_
`./vcpkg install poco

_**Failure logs**_ 
```
Building libpq x86-windows-RELEASE...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: ".../Documents/Visual Studio 2019/vcpkg/downloads/tools/perl/perl/bin/perl.exe" build.pl RELEASE libpq
    Working Directory: .../Documents/Visual Studio 2019/vcpkg/buildtrees/libpq/x86-windows-rel/src/tools/msvc
    Error code: 1
    See logs for more information:
      ...\Documents\Visual Studio 2019\vcpkg\buildtrees\libpq\build-libpq-x86-windows-RELEASE-out.log

Call Stack (most recent call first):
  ports/libpq/portfile.cmake:194 (vcpkg_execute_required_process)
  scripts/ports.cmake:90 (include)


Error: Building package libpq:x86-windows failed with: BUILD_FAILED
```
build-libpq-x86-windows-RELEASE-out.log:
```
cl output Microsoft (R) C/C++ Optimizing Compiler Version 19.25.28611 for x86
.....
Generating probes.h...
Generating errcodes.h...
Generating plerrcodes.h...
Generating qsort_tuple.c...
Generating libpq.rc...
Generating sql_help.h...
Generating kwlist_d.h...
Generating pl_reserved_kwlist_d.h and pl_unreserved_kwlist_d.h...
Generating c_kwlist_d.h and ecpg_kwlist_d.h...
Generating preproc.y...
Generating ecpg_config.h...
Generating pg_config_paths.h...
Microsoft (R) Build Engine version 16.5.0+d4cbfca49 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1008: Only one project can be specified.
Switch: Studio

For switch syntax, type "MSBuild -help"
```
**Additional context**

**Comment by linquize** [comment]
No error for me.

**Comment by rodrigosilvafe** [comment]
I have the same issue but with plplot package and I tried with another one (sqlite3) which appears in the documentation and got the same problem.
I think there must be another reason for this, the problem is not the poco package or any.
Can anyone help?
Thanks in advance

**Comment by LilyWangL** [comment]
@EpoUnlimited Thanks for posting this issue. Could you clone VCPKG on other directory which the directory name have no space? I think due to `Documents\Visual Studio 2019\vcpkg\buildtrees\libpq` have space, libpq build failed.

**Comment by LilyWangL** [comment]
> I have the same issue but with plplot package and I tried with another one (sqlite3) which appears in the documentation and got the same problem.
> I think there must be another reason for this, the problem is not the poco package or any.
> Can anyone help?
> Thanks in advance

Did you install port plplot failed? Could you please provide your error log?

**Comment by EpoUnlimited** [comment]
@LilyWangL Thanks for the reply. You are right! The installation of the poco:x86-windows and poco:x64-windows is done without any problems now after removing space in the directory path of vcpkg.
Thanks also for the tips.
