### ISSUE TITLE
[asio] cannot link library in CMake

### ISSUE THREAD

**Issue by prokotg** [microsoft/vcpkg#10604]
**Host Environment**
- OS:x64_linux (Ubuntu 18.04)
- Cmake: 3.10
- Compiler: gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04) 

**To Reproduce**
`./vcpkg install asio`
create new project with `CMakeLists.txt`
simply add `find_package(asio)`

**Failure logs** 
```
CMake Error at /home/tom/fun/vcpkg/installed/x64-linux/share/asio/asio-config.cmake:3 (target_link_libraries):
[cmake]   Cannot specify link libraries for target "asio::asio" which is not built by
[cmake]   this project.
[cmake] Call Stack (most recent call first):
[cmake]   /home/tom/fun/vcpkg/scripts/buildsystems/vcpkg.cmake:286 (_find_package)
[cmake]   CMakeLists.txt:1 (find_package)
```

I had no problem linking asio on Windows and linking other libs on linux (such us GTest). Apologies if this is my fault only, I'm a CMake noobie.

**Comment by linquize** [comment]
Can you post your `CMakeLists.txt`?

**Comment by prokotg** [comment]
@linquize literally

```
cmake_minimum_required(VERSION 3.10)
project(pa)
find_package(asio CONFIG REQUIRED)
```

**Comment by linquize** [comment]
Did you write `add_executable()` and `target_link_libraries()`? and how?

**Comment by prokotg** [comment]
@linquize I have tried to work it out with and without `add_executable` . So one `CMakeLists.txt` was exactly like one above to figure out if it will break; another one was:
```
cmake_minimum_required(VERSION 3.10)
project(pa)
add_executable(helloworld main.cpp)
find_package(asio CONFIG REQUIRED)
target_link_libraries(helloworld PRIVATE asio asio::asio)
```

both produce the same error. Cheers!

**Comment by linquize** [comment]
Change to `target_link_libraries(helloworld PRIVATE asio::asio)`

**Comment by prokotg** [comment]
@linquize still same error, it does not even go pass through 4th line `find_package(asio CONFIG REQUIRED)`. Isn't the error coming out of asio cmake? Is it possible that my cmake triggers something?

**Comment by linquize** [comment]
Run cmake configure, remember to set `CMAKE_TOOLCHAIN_FILE`
`cmake -DCMAKE_TOOLCHAIN_FILE=/home/tom/fun/vcpkg/scripts/buildsystems/vcpkg.cmake`

**Comment by LilyWangL** [comment]
@prokotg Thanks for posting this issue. The version of cmake which is installed by Linux is low, you can use cmake which is installed by VCPKG. The command is:
**_VCPKG_PATH_**/downloads/tools/cmake-3.14.0-linux/cmake-3.14.0-Linux-x86_64/bin/cmake -DCMAKE_TOOLCHAIN_FILE=**_VCPKG_PATH_**/scripts/buildsystems/vcpkg.cmake CMakeLists.txt

**Comment by prokotg** [comment]
@LilyWangL Oh my... I built and installed CMake 3.17 from sources and everything went perfect. Would it be possible to inform user about required cmake version? Is there some info in docs?
