### ISSUE TITLE
[New Port Request] srdfdom

### ISSUE THREAD

**Issue by ISWBenjaminKaiser** [microsoft/vcpkg#10607]
Library name: srdfdom

Library description: Parser for the Semantic Robot Description Format (SRDF)
 
Source repository URL: https://github.com/ros-planning/srdfdom

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by linquize** [comment]
Note: This library has a part that uses python in `CMakeLists.txt`, should be skipped.
Also `catkin` is not available in vcpkg.

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
