### ISSUE TITLE
Building package ffmpeg:x86-windows failed with: BUILD_FAILED 

### ISSUE THREAD

**Issue by cummins-orgs** [microsoft/vcpkg#10606]
[msys-pacman-x86-windows-out.log](https://github.com/microsoft/vcpkg/files/4402926/msys-pacman-x86-windows-out.log)
[msys-pacman-x86-windows-err.log](https://github.com/microsoft/vcpkg/files/4402927/msys-pacman-x86-windows-err.log)

**Host Environment**
- OS: Windows 10
- Compiler: revision

**To Reproduce**
`./vcpkg install ffmpeg:x86-windows`

**Failure logs** 
No packages need updating.
PS D:\Box_Drive\Box\STRATSYNC\kinect_to_unity\kinect-to-hololens\vcpkg> .\vcpkg.exe install ffmpeg:x86-windows
The following packages will be built and installed:
    ffmpeg[avresample,core]:x86-windows
Starting package 1/1: ffmpeg:x86-windows
Building package ffmpeg[avresample,core]:x86-windows...
-- Using cached D:/Box_Drive/Box/STRATSYNC/kinect_to_unity/kinect-to-hololens/vcpkg/downloads/ffmpeg-ffmpeg-n4.2.tar.gz
-- Using source at D:/Box_Drive/Box/STRATSYNC/kinect_to_unity/kinect-to-hololens/vcpkg/buildtrees/ffmpeg/src/n4.2-02d8c63f80
-- Acquiring MSYS Packages...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: D:/Box_Drive/Box/STRATSYNC/kinect_to_unity/kinect-to-hololens/vcpkg/downloads/tools/msys2/msys64/usr/bin/bash.exe --noprofile --norc -c "pacman -Sy --noconfirm --needed diffutils make"
    Working Directory: D:/Box_Drive/Box/STRATSYNC/kinect_to_unity/kinect-to-hololens/vcpkg/downloads/tools/msys2
    Error code: 1
    See logs for more information:
      D:\Box_Drive\Box\STRATSYNC\kinect_to_unity\kinect-to-hololens\vcpkg\buildtrees\ffmpeg\msys-pacman-x86-windows-out.log
      D:\Box_Drive\Box\STRATSYNC\kinect_to_unity\kinect-to-hololens\vcpkg\buildtrees\ffmpeg\msys-pacman-x86-windows-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_acquire_msys.cmake:106 (vcpkg_execute_required_process)
  ports/ffmpeg/portfile.cmake:43 (vcpkg_acquire_msys)
  scripts/ports.cmake:94 (include)

**Comment by linquize** [comment]
Please post `D:\Box_Drive\Box\STRATSYNC\kinect_to_unity\kinect-to-hololens\vcpkg\buildtrees\ffmpeg\msys-pacman-x86-windows-out.log`

**Comment by LilyWangL** [comment]
@cummins-orgs Thanks for posting this issue. Could you try to run the command from this comment: https://github.com/msys2/MINGW-packages/issues/240#issuecomment-57850041?

**Comment by cummins-orgs** [comment]
Hi, thanks for the quick response! I do not seem to have pacman or pacman-key installed. Maybe that is the source of the problem. Currently working on installing that so I can run those commands:

pacman-key --init
pacman-key --populate msys2
pacman-key --refresh-keys

Will update once I have pacman-key installed

**Comment by cummins-orgs** [comment]
It looks like pacman is for Linux - I am running on Windows. Can't find a way to install it and run those commands.  This may be a noob comment, of course! New to Windows development and vcpkg.

**Comment by LilyWangL** [comment]
Because I can't reproduce this issue locally, so I can't verify it. Could you please try this steps on Windows? https://github.com/Alexpux/MSYS2-pacman/issues/50#issuecomment-353764211

**Comment by cummins-orgs** [comment]
Trying now - thanks! If you have any tips on this part please let me know, figuring out how to do it now "Was able to get it to work by downloading the binary pacman package & manually installing all its contents to Git/MSYS environment. "

**Comment by cummins-orgs** [comment]
Using WSL, I installed pacman. I can't get any aspect of it to work using Powershell. I can install and interact with it in bash. 

So not sure how these will interact/how pacman-key relates to vcpkg. 

I can run the below fine inside the pacman /scripts directory, where pacman-key seems to be stored. Trying to run them anywhere else just gives an error. No output  when I run them in the so I'm pretty sure it's not actually doing anything:

matt@MattSI:/mnt/d/Documents/kinect-to-hololens/pacman/pacman-5.2.1/scripts$ pacman-key --init
matt@MattSI:/mnt/d/Documents/kinect-to-hololens/pacman/pacman-5.2.1/scripts$ pacman-key --populate msys2
matt@MattSI:/mnt/d/Documents/kinect-to-hololens/pacman/pacman-5.2.1/scripts$ pacman-key --refresh-keys

**Comment by Voskrese** [comment]
@cummins-orgs 
Why are you running PACMAN in UBUNTU and what do you want to achieve with this?

**Comment by cummins-orgs** [comment]
@Voskrese Only to try to follow above suggestions! All I originally am trying to do is follow this:

https://github.com/cummins-orgs/kinect-to-hololens/blob/master/README.md

Which requires vcpkg to install dependencies:

".\vcpkg.exe install asio:x86-windows asio:x64-windows ffmpeg:x86-windows ffmpeg:x64-windows libvpx:x86-windows libvpx:x64-windows ms-gsl:x86-windows ms-gsl:x64-windows opencv:x86-windows opencv:x64-windows readerwriterqueue:x86-windows readerwriterqueue:x64-windows opus:x86-windows opus:x64-windows"

Then vcpkg wouldn't do it, so far lol

**Comment by Voskrese** [comment]
open BASH

..\ `vcpkg\downloads\tools\msys2\msys64\msys2.exe`

```
pacman-key --init
pacman-key --populate msys2
pacman-key --refresh-keys
```

`pacman -Syuu --noconfirm --needed --overwrite '*'`

cmd or powershell
` ./vcpkg install ffmpeg:x86-windows`

**Comment by cummins-orgs** [comment]
Thanks a lot! Trying now, will update :)

**Comment by cummins-orgs** [comment]
Ok, the vcpkg part of this is now behaving itself, followed those instructions, thanks for all your help!
