### ISSUE TITLE
How do I use the pre-installed msys2?

### ISSUE THREAD

**Issue by neko-para** [microsoft/vcpkg#10616]
I decide to install qt on windows, which relies on icu. And then 'Acquiring MSYS2' appears. But I've already installed msys2 before. Is there any way to help vcpkg know the pre-installed msys2 and use it instead of downloading another?

**Comment by neko-para** [comment]
Actually, I hope if all tools used by vcpkg could be switched to the installed version. I've installed perl from msys2 and set it in PATH, but vcpkg still tries to download another perl.

**Comment by linquize** [comment]
Currently, setting `VCPKG_FORCE_SYSTEM_BINARIES=1` environment variable will allow you to use your own cmake, ninja, cmake, but not other tools like perl

**Comment by NancyLi1013** [comment]
Hi all,

It's similar to this issue #11837. Let's track this issue there.
