### ISSUE TITLE
boost-build[core] build failure

### ISSUE THREAD

**Issue by christophe-calmejane** [microsoft/vcpkg#10612]
**Host Environment**
- OS: macOS 10.15.3
- Compiler: Xcode 11.3.1

**To Reproduce**
`export CC=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc`
`export CXX=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++`
`./vcpkg install boost-build[core]`

**Failure logs** 
```
$ ./vcpkg install boost-build[core]
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
Computing installation plan...
The following packages will be built and installed:
    boost-build[core]:x64-osx
Starting package 1/1: boost-build:x64-osx
Building package boost-build[core]:x64-osx...
-- Using cached /Users/christophe.calmejane/dev/vcpkg/downloads/boostorg-build-boost-1.72.0.tar.gz
-- Using source at /Users/christophe.calmejane/dev/vcpkg/buildtrees/boost-build/src/ost-1.72.0-fa8b817276
-- Using cached /Users/christophe.calmejane/dev/vcpkg/downloads/boost_LICENSE_1_0.txt
-- Using cached /Users/christophe.calmejane/dev/vcpkg/downloads/boost-1.72.0-boostcpp.jam
-- Installing: /Users/christophe.calmejane/dev/vcpkg/packages/boost-build_x64-osx/share/boost-build/copyright
-- Installing: /Users/christophe.calmejane/dev/vcpkg/packages/boost-build_x64-osx/tools/boost-build/boostcpp.jam
-- Bootstrapping...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: /Users/christophe.calmejane/dev/vcpkg/packages/boost-build_x64-osx/tools/boost-build/bootstrap.sh
    Working Directory: /Users/christophe.calmejane/dev/vcpkg/packages/boost-build_x64-osx/tools/boost-build
    Error code: 1
    See logs for more information:
      /Users/christophe.calmejane/dev/vcpkg/buildtrees/boost-build/bootstrap-x64-osx-out.log
```
```
$ cat /Users/christophe.calmejane/dev/vcpkg/buildtrees/boost-build/bootstrap-x64-osx-out.log
Bootstrapping the build engine with toolset clang...

Failed to bootstrap the build engine
Consult 'bootstrap.log' for more details
```
```
$ cat ./packages/boost-build_x64-osx/tools/boost-build/bootstrap.log
###
###
### Using 'clang' toolset.
###
###
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ --version
Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin19.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
###
###
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -x c++ -O3 -std=c++11 -O3 -s -DNDEBUG builtins.cpp class.cpp command.cpp compile.cpp constants.cpp cwd.cpp debug.cpp debugger.cpp execcmd.cpp filesys.cpp frames.cpp function.cpp glob.cpp hash.cpp hcache.cpp hdrmacro.cpp headers.cpp jam.cpp jambase.cpp jamgram.cpp lists.cpp make.cpp make1.cpp md5.cpp mem.cpp modules.cpp native.cpp object.cpp option.cpp output.cpp parse.cpp pathsys.cpp regexp.cpp rules.cpp scan.cpp search.cpp strings.cpp subst.cpp sysinfo.cpp timestamp.cpp variable.cpp w32_getreg.cpp modules/order.cpp modules/path.cpp modules/property-set.cpp modules/regex.cpp modules/sequence.cpp modules/set.cpp execunix.cpp fileunix.cpp pathunix.cpp -o b2
In file included from builtins.cpp:7:
./jam.h:336:10: fatal error: 'sys/types.h' file not found
#include <sys/types.h>
         ^~~~~~~~~~~~~
1 error generated.

```
**Additional context**
For some reason, I need to have CC/CXX set (here I manually set them before invoking vcpkg just for showcasing the issue).
I tracked down the issue in `packages/boost-build/tools/boost-build/src/engine/build.sh` where the script is setting CXX like this: `CXX=${CXX:=clang++}`
If CXX is not set before invoking vcpkg then clang++ is chosen and everything compiles correctly.

Is there a clean way for vcpkg to unset critical environment variables for ports that might behave differently if set (for any reason)? I don't think outside environment should impact how boost (or any other package) is compiled, except for any options passed to vcpkg command line.

Just FYI, my actual use case is because a project is calling `vcpkg install` from a CMake script that is executed at configure time. Depending on the chosen compiler (by CMake), boost either succeed or fails to compile. For instance if I use `Xcode` generator then everything is fine (because CXX is set to clang++ by CMake), but if I use `Ninja` or `Makefiles` then it fails.

**Comment by PhoebeHui** [comment]
@christophe-calmejane, boost currently upgrade to 1.73.0, could you get latest source and see if this issue still occur?
I can't repro this issue locally.

 ./vcpkg install boost-build
Computing installation plan...
The following packages will be built and installed:
    boost-build[core]:x64-osx
Detecting compiler hash for triplet x64-osx...
Starting package 1/1: boost-build:x64-osx
Building package boost-build[core]:x64-osx...
Could not locate cached archive: /Users/vcpkg/.cache/vcpkg/archives/62/62bc95a660c9a6fa4ecc0fb0cba0536921dff742.zip
-- Downloading https://github.com/boostorg/build/archive/boost-1.73.0.tar.gz...
-- Extracting source /Users/vcpkg/phoebe/vcpkg/downloads/boostorg-build-boost-1.73.0.tar.gz
-- Using source at /Users/vcpkg/phoebe/vcpkg/buildtrees/boost-build/src/ost-1.73.0-018fb008dd.clean
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.73.0/LICENSE_1_0.txt...
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.73.0/boostcpp.jam...
-- Installing: /Users/vcpkg/phoebe/vcpkg/packages/boost-build_x64-osx/share/boost-build/copyright
-- Installing: /Users/vcpkg/phoebe/vcpkg/packages/boost-build_x64-osx/tools/boost-build/boostcpp.jam
-- Bootstrapping...
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: /Users/vcpkg/.cache/vcpkg/archives/62/62bc95a660c9a6fa4ecc0fb0cba0536921dff742.zip
Building package boost-build[core]:x64-osx... done
Installing package boost-build[core]:x64-osx...
Installing package boost-build[core]:x64-osx... done
Elapsed time for package boost-build:x64-osx: 7.719 s

Total elapsed time: 9.298 s

**Comment by christophe-calmejane** [comment]
Have you manually defined CC and CXX env variables before running `vcpkg install`?

**Comment by PhoebeHui** [comment]
I didn't define any CC and CXX env variable.

**Comment by PhoebeHui** [comment]
BTW, you can reference https://github.com/microsoft/vcpkg/blob/master/scripts/azure-pipelines/osx/azure-pipelines.yml#L19 for VM setup on OSX.

**Comment by christophe-calmejane** [comment]
Well, defining the env vars was the whole point of the ticket. Boost was (and is still) compiling fine, as long as it's not disturbed by an external element.
My ticket's point was that vcpkg should not (in general, not just Boost which merely served as an example) be affected in any way be the environement. It's a complete build toolchain, if something has to impact the compilation it should be defined in ports file and/or passed as parameters (via CMAKE TOOLCHAIN file for example).
Here with boost, we have a compilation failure if CC and CXX are defined (to valid values, as I used the exact same values that Ninja generator sets CC/CXX to).
So it's not a specific port bug, but more something that vcpkg should take care of internally like undefining (backuping) some env vars before calling cmake).

**Comment by PhoebeHui** [comment]
@christophe-calmejane, Sorry for my late response.

This is mostly like a Upstream issue, vcpkg only execute bootstrap.sh, see https://github.com/microsoft/vcpkg/blob/master/ports/boost-build/portfile.cmake#L63, without setting any additional flags on osx, could you report an issue to boost build instead?

**Comment by LilyWangLL** [comment]
@christophe-calmejane Thanks for your issue. This issue should be a upstream issue, did you report this issue on upstaream?

**Comment by christophe-calmejane** [comment]
I might have missed Phoebe's answer (along with forgetting this ticket), so I didn't report to boost project. Not sure I will have the time to do so for now, neither have I checked with a more recent boost version.

**Comment by LilyWangLL** [comment]
Waiting upstream fix this issue, we will sync upstream's change to VCPKG.

**Comment by JackBoosY** [comment]
Please reopen this issue when it is fixed upstream.
