### ISSUE TITLE
fix mpl emergency

### ISSUE THREAD

**Issue by Milerius** [microsoft/vcpkg#10614]
Hello

is this possible to fix https://github.com/boostorg/mpl/issues/46 with a diff patch ? removing the second condition as suggested, unable to use boost::filesystem on windows because of that 

@ras0219-msft

**Comment by JackBoosY** [comment]
Hi @Milerius, that's a source bug.
According to the policy, we need to wait for the upstream to fix this issue, and then update to vcpkg.

**Comment by yurybura** [comment]
@JackBoosY Seems like this issue was fixed after update to 1.74.0 in #14089
