### ISSUE TITLE
mosquitto build failure (windows static x86/x64)

### ISSUE THREAD

**Issue by gizmocuz** [microsoft/vcpkg#10611]
**Host Environment**
- OS: Windows
- Compiler: Visual Studio 2019 16.5.1

**To Reproduce**
vcpkg install mosquitto:x86-windows-static
vcpkg install mosquitto:x64-windows-static

(Dynamic are working)

**Failure logs** 
 Package: mosquitto:x64-windows-static
  Vcpkg version: 2020.02.04-nohash-external

The following packages will be built and installed:
    mosquitto[core]:x64-windows-static
Starting package 1/1: mosquitto:x64-windows-static
Building package mosquitto[core]:x64-windows-static...
-- Note: mosquitto only supports dynamic library linkage. Building dynamic library.
CMake Error at scripts/cmake/vcpkg_check_linkage.cmake:42 (message):
  Refusing to build unexpected dynamic library against the static CRT.  If
  this is desired, please configure your triplet to directly request this
  configuration.
Call Stack (most recent call first):
  ports/mosquitto/portfile.cmake:1 (vcpkg_check_linkage)
  scripts/ports.cmake:90 (include)

**Comment by NancyLi1013** [comment]
Hi @gizmocuz 
Thanks for posting this issue.
Since static build on Windows is currently not supported in vcpkg.
The result you encountered is intended now.
I will try to fix this later.

**Comment by NancyLi1013** [comment]
@gizmocuz 
I submitted a PR to fix this. 
Could you please help confirm if this can work for you?

**Comment by NancyLi1013** [comment]
The PR has been merged. Please try to update vcpkg and rebuild this.

**Comment by gizmocuz** [comment]
@NancyLi1013 , Thank you for the PR
Unfortunately it does not work 100%, when using the static triplet no DLL's are copied into the build folder.
But the final executable still depends on mosquitto.dll

![image](https://user-images.githubusercontent.com/2265299/79566339-ae002300-80b2-11ea-857c-7dd74fe9d1c4.png)

It seems something does not go 100% correct here...

**Comment by NancyLi1013** [comment]
@gizmocuz 
Thanks for your feedback. I will look into this on my local.

**Comment by gizmocuz** [comment]
Compiled/Tested under Windows, this works great ! Thanks

**Comment by NancyLi1013** [comment]
Okay. Since you can work normally, I am going to close this issue now.
Please open a new issue if you have other problems.

**Comment by gizmocuz** [comment]
@NancyLi1013 , I am very sorry about this, This post/remark was for another project (MQTT Explorer), this issue is not solved... Sorry!

**Comment by NancyLi1013** [comment]
Could you please provide your project case?

**Comment by NancyLi1013** [comment]
@gizmocuz 
Please let me know if you still have any concern about this issue.

**Comment by NancyLi1013** [comment]
Closing this issue for inactive thread. Please reopen this or open a new issue if this is still a problem for you.
