### ISSUE TITLE
How do I include libgraphqlparser? 

### ISSUE THREAD

**Issue by ckaminski** [microsoft/vcpkg#10622]
I have the following library installed: 

> C:\repos\cpp\vcpkg>vcpkg list | findstr graphql
> graphqlparser:x86-windows                          0.7.0-1          A GraphQL query parser in C++ with C and C++ APIs

running find_package(graphqlparser CONFIG REQUIRED) from my CMakeLists.txt returns the following: 

CMake Error at C:/repos/cpp/vcpkg/scripts/buildsystems/vcpkg.cmake:288 (_find_package):
  Could not find a package configuration file provided by "graphqlparser"
  with any of the following names:

    graphqlparserConfig.cmake
    graphqlparser-config.cmake

  Add the installation prefix of "graphqlparser" to CMAKE_PREFIX_PATH or set
  "graphqlparser_DIR" to a directory containing one of the above files.  If
  "graphqlparser" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:15 (find_package)

I'm not an expert on cmake by any means, but other packages I have installed have config files installed.  

I'm rebuilding graphqlparser, and get the following output 
C:\repos\cpp\graphqlserver\build>vcpkg install graphqlparser
Computing installation plan...
The following packages will be built and installed:
    graphqlparser[core]:x86-windows
Starting package 1/1: graphqlparser:x86-windows
Building package graphqlparser[core]:x86-windows...
-- Using cached C:/repos/cpp/vcpkg/downloads/graphql-libgraphqlparser-v0.7.0.tar.gz
-- Using source at C:/repos/cpp/vcpkg/buildtrees/graphqlparser/src/v0.7.0-759c5901bd
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package graphqlparser[core]:x86-windows... done
Installing package graphqlparser[core]:x86-windows...
Installing package graphqlparser[core]:x86-windows... done
Elapsed time for package graphqlparser:x86-windows: 1.774 min

Total elapsed time: 1.774 min

**Comment by linquize** [comment]
```cmake
add_executable(example example.cpp)
find_path(GRAPHQLPARSER_INCLUDE_DIR graphqlparser/GraphQLParser.h)
find_library(GRAPHQLPARSER_LIBRARY graphqlparser)
target_include_directories(example PRIVATE ${GRAPHQLPARSER_INCLUDE_DIR})
target_link_libraries(example PRIVATE ${GRAPHQLPARSER_LIBRARY})
```

**Comment by NancyLi1013** [comment]
Hi @ckaminski 
Thanks for posting this issue.
As @linquize said above,` find_package()` is not available for `graphqlparser `now.
If possible, you can try to use this port in the above way.

**Comment by ckaminski** [comment]
That was very helpful.  Thank you to @linquize.
