### ISSUE TITLE
vcpkgTools.xml, vcpkg_find_acquire_program.cmake version/filename inconsistent

### ISSUE THREAD

**Issue by linquize** [microsoft/vcpkg#10625]
`vcpkgTools.xml` vs `vcpkg_find_acquire_program.cmake`
nuget v4.6.2 vs v4.8.1
aria2 v1.33.1 vs v1.34.0
ninja simply filename inconsistent `ninja-win-1.8.2.zip` vs `ninja-1.8.2-win.zip`

**Comment by LilyWangL** [comment]
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.
