### ISSUE TITLE
[jwt-cpp] Install required dependencies automatically

### ISSUE THREAD

**Issue by pistecid** [microsoft/vcpkg#10626]
****

**Is your feature request related to a problem? Please describe.**
When installed the jwt-cpp package is not working properly (once header is included, the compilation fails due to missing dependency on picojson which is also available in vcpkg)

**Proposed solution**
Add picojson package as a prerequisite to the jwt-cpp package

**Describe alternatives you've considered**
Installation picojson manually is a possible workaround

**Comment by linquize** [comment]
What platform, compiler do you use?

**Comment by linquize** [comment]
It does not depend on picojson. It can compile successfully without picojson.

**Comment by pistecid** [comment]
I'm using windows 10 platform + visual studio 2019 compiler. The jwt.h within the jwt-cpp starts with follwoing lines:

#pragma once
#define PICOJSON_USE_INT64
#include "picojson/picojson.h"

So I'm not sure if it can work properly without picojson.

**Comment by linquize** [comment]
Although it can compile successfully without `picojson`, it is needed in the header file. 
So we should treat `picojson` as a dependency.

**Comment by linquize** [comment]
jwt-cpp is a header-only library that does not need to "compile". The CMake build process simply does copy files.
`picojson` is needed in the header file.
So we should treat `picojson` as a dependency.

**Comment by PhoebeHui** [comment]
@pistecid, thanks for bringing up this!

@linquize, thanks for your comments, I will help confrim this.
