### ISSUE TITLE
[tensorflow-cc{1.14}:x64-windows] build failure

### ISSUE THREAD

**Issue by muha0143** [microsoft/vcpkg#10632]
**Host Environment**
- OS: [windows 10]

I used this command line 
`vcpkg install tensorflow-cc:x64-windows`

**Failure logs** 
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: C:/vcpkg/downloads/tools/msys2/msys64/usr/bin/bash.exe --noprofile --norc -c "C:/vcpkg/downloads/tools/bazel/0.25.2/bazel.exe build --verbose_failures -c opt --python_path=C:/vcpkg/downloads/tools/python/python-3.7.3-x64/python.exe --incompatible_disable_deprecated_attr_params=false --define=no_tensorflow_py_deps=true ///tensorflow:libtensorflow_cc.so ///tensorflow:install_headers"
    Working Directory: C:/vcpkg/buildtrees/tensorflow-cc/x64-windows-rel
    See logs for more information:
      C:\vcpkg\buildtrees\tensorflow-cc\build-x64-windows-rel-err.log

Call Stack (most recent call first):
  ports/tensorflow-cc/portfile.cmake:90 (vcpkg_execute_build_process)
  scripts/ports.cmake:90 (include)

Error: Building package tensorflow-cc:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: tensorflow-cc:x64-windows
  Vcpkg version: 2020.02.04-nohash

**Comment by Voskrese** [comment]
**See logs for more information:**

**See logs for more information:**

> C:\vcpkg\buildtrees\tensorflow-cc\build-x64-windows-rel-err.log

**Comment by Cheney-W** [comment]
@muha0143 Could you please provide the failure log and the version of your VS to us?

**Comment by muha0143** [comment]
@Cheney-W 

Visual Studio 2019 community


build-x64-windows-rel-err.log : 

$TEST_TMPDIR defined: output root default is 'c:\vcpkg\buildtrees\.bzl' and max_idle_secs default is '15'.
Starting local Bazel server and connecting to it...
Loading: 
Loading: 0 packages loaded
Loading: 0 packages loaded
    currently loading: tensorflow
Analyzing: 2 targets (1 packages loaded, 0 targets configured)
Analyzing: 2 targets (16 packages loaded, 48 targets configured)
Analyzing: 2 targets (46 packages loaded, 388 targets configured)
Analyzing: 2 targets (59 packages loaded, 1283 targets configured)
Analyzing: 2 targets (59 packages loaded, 2430 targets configured)
Analyzing: 2 targets (62 packages loaded, 2505 targets configured)
Analyzing: 2 targets (79 packages loaded, 2925 targets configured)
Analyzing: 2 targets (79 packages loaded, 2925 targets configured)
Analyzing: 2 targets (79 packages loaded, 2925 targets configured)
Analyzing: 2 targets (79 packages loaded, 2925 targets configured)
Analyzing: 2 targets (79 packages loaded, 2925 targets configured)
Analyzing: 2 targets (79 packages loaded, 2925 targets configured)
Analyzing: 2 targets (79 packages loaded, 2925 targets configured)
Analyzing: 2 targets (79 packages loaded, 2925 targets configured)
Analyzing: 2 targets (79 packages loaded, 2925 targets configured)
Analyzing: 2 targets (79 packages loaded, 2925 targets configured)
Analyzing: 2 targets (79 packages loaded, 2925 targets configured)
Analyzing: 2 targets (79 packages loaded, 2925 targets configured)
INFO: An error occurred during the fetch of repository 'gif_archive'
INFO: Call stack for the definition of repository 'gif_archive':
 - C:/vcpkg/buildtrees/tensorflow-cc/x64-windows-rel/tensorflow/workspace.bzl:265:5
 - C:/vcpkg/buildtrees/tensorflow-cc/x64-windows-rel/WORKSPACE:94:1
INFO: An error occurred during the fetch of repository 'mkl_dnn'
INFO: Call stack for the definition of repository 'mkl_dnn':
 - C:/vcpkg/buildtrees/tensorflow-cc/x64-windows-rel/tensorflow/workspace.bzl:126:5
 - C:/vcpkg/buildtrees/tensorflow-cc/x64-windows-rel/WORKSPACE:94:1
INFO: An error occurred during the fetch of repository 'jpeg'
INFO: Call stack for the definition of repository 'jpeg':
 - C:/vcpkg/buildtrees/tensorflow-cc/x64-windows-rel/third_party/jpeg/workspace.bzl:6:5
 - C:/vcpkg/buildtrees/tensorflow-cc/x64-windows-rel/tensorflow/workspace.bzl:45:5
 - C:/vcpkg/buildtrees/tensorflow-cc/x64-windows-rel/tensorflow/workspace.bzl:73:5
 - C:/vcpkg/buildtrees/tensorflow-cc/x64-windows-rel/WORKSPACE:94:1
INFO: An error occurred during the fetch of repository 'com_google_absl'
INFO: Call stack for the definition of repository 'com_google_absl':
 - C:/vcpkg/buildtrees/tensorflow-cc/x64-windows-rel/tensorflow/workspace.bzl:137:5
 - C:/vcpkg/buildtrees/tensorflow-cc/x64-windows-rel/WORKSPACE:94:1
Analyzing: 2 targets (81 packages loaded, 3185 targets configured)
INFO: An error occurred during the fetch of repository 'eigen_archive'
INFO: Call stack for the definition of repository 'eigen_archive':
 - C:/vcpkg/buildtrees/tensorflow-cc/x64-windows-rel/tensorflow/workspace.bzl:148:5
 - C:/vcpkg/buildtrees/tensorflow-cc/x64-windows-rel/WORKSPACE:94:1
INFO: An error occurred during the fetch of repository 'org_sqlite'
INFO: Call stack for the definition of repository 'org_sqlite':
 - C:/vcpkg/buildtrees/tensorflow-cc/x64-windows-rel/tensorflow/workspace.bzl:253:5
 - C:/vcpkg/buildtrees/tensorflow-cc/x64-windows-rel/WORKSPACE:94:1
INFO: An error occurred during the fetch of repository 'icu'
INFO: Call stack for the definition of repository 'icu':
 - C:/vcpkg/buildtrees/tensorflow-cc/x64-windows-rel/third_party/icu/workspace.bzl:11:5
 - C:/vcpkg/buildtrees/tensorflow-cc/x64-windows-rel/tensorflow/workspace.bzl:42:5
 - C:/vcpkg/buildtrees/tensorflow-cc/x64-windows-rel/tensorflow/workspace.bzl:73:5
 - C:/vcpkg/buildtrees/tensorflow-cc/x64-windows-rel/WORKSPACE:94:1
Analyzing: 2 targets (81 packages loaded, 3185 targets configured)
INFO: An error occurred during the fetch of repository 'double_conversion'
INFO: Call stack for the definition of repository 'double_conversion':
 - C:/vcpkg/buildtrees/tensorflow-cc/x64-windows-rel/tensorflow/workspace.bzl:751:5
 - C:/vcpkg/buildtrees/tensorflow-cc/x64-windows-rel/WORKSPACE:94:1
ERROR: C:/vcpkg/buildtrees/tensorflow-cc/x64-windows-rel/tensorflow/core/platform/default/build_config/BUILD:212:1: no such package '@gif_archive//': java.io.IOException: Error downloading [http://mirror.tensorflow.org/ufpr.dl.sourceforge.net/project/giflib/giflib-5.1.4.tar.gz, http://pilotfiber.dl.sourceforge.net/project/giflib/giflib-5.1.4.tar.gz] to C:/vcpkg/buildtrees/.bzl/_bazel_muhammed/m2gwzxod/external/gif_archive/giflib-5.1.4.tar.gz: All mirrors are down: [GET returned 404 Not Found] and referenced by '//tensorflow/core/platform/default/build_config:gif'
ERROR: Analysis of target '//tensorflow:libtensorflow_cc.so' failed; build aborted: Analysis failed
INFO: Elapsed time: 66.029s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (81 packages loaded, 3185 targets configured)
FAILED: Build did NOT complete successfully (81 packages loaded, 3185 targets configured)

**Comment by Cheney-W** [comment]
Duplicated to #7995, also has Upstream issue tensorflow/tensorflow#32228 to track.
