### ISSUE TITLE
Ninja invocation should respect  VCPKG_MAX_CONCURRENCY 

### ISSUE THREAD

**Issue by yuanchen-zhu** [microsoft/vcpkg#10631]
**Problem**

Currently, ninja invocation by vcpkg does not seem to respect VCPKG_MAX_CONCURRENCY. As a result, ninja will use it's default parallelism, which can result in out of memory error if the RAM/core ratio is low, e.g., on my 6 core system with 32GB RAM, ninja defaults to 14 parallel jobs and run out of memory when compiling PCL from the master branch. When that happens , vcpkg prints "Restarting Build without parallelism because memory exceeded" and restarts the build with **NO** parallelism, which is very SLOW. 

**Proposed solution**

It would be much better, if vcpkg invokes ninja with `-j ` followed by value specified by VCPKG_MAX_CONCURRENCY. 

**Alternatives**
Ninja doesn't allow the number of max parallel jobs to be controlled by an environment variable.

**Comment by Neumann-A** [comment]
From my observation running out of memory only happens in the link stage and linking larger libraries can be rather slow and consume a lot of memory. 

>and restarts the build

it does not restart the whole build. Ninja restarts at the missing build steps

But i agree that it should respect `VCPKG_MAX_CONCURRENCY`
