### ISSUE TITLE
Copying dlls fails with square brackets in output directory

### ISSUE THREAD

**Issue by johannesstricker** [microsoft/vcpkg#10639]
**Describe the bug**
When building with cmake and the path to the build directory contains square brackets (e.g. `c:/project/build/visual studio 2019 [x86]/`), then the post-build action of copying dependencies to the output directory fails with the following error:

```
[build]   Split-Path : Cannot bind argument to parameter 'Path' because it is null.
[build]   At C:\Users\Johannes\vcpkg\scripts\buildsystems\msbuild\applocal.ps1:40 char:39
[build]   +     $baseTargetBinaryDir = Split-Path $baseBinaryPath -parent
[build]   +                                       ~~~~~~~~~~~~~~~
[build]       + CategoryInfo          : InvalidData: (:) [Split-Path], ParameterBindingValidationException
[build]       + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.SplitPathCo 
[build]      mmand
[build]    
[build]   Split-Path : Cannot bind argument to parameter 'Path' because it is null.
[build]   At C:\Users\Johannes\vcpkg\scripts\buildsystems\msbuild\applocal.ps1:58 char:35
[build]   +     $targetBinaryDir = Split-Path $targetBinaryPath -parent
[build]   +                                   ~~~~~~~~~~~~~~~~~
[build]       + CategoryInfo          : InvalidData: (:) [Split-Path], ParameterBindingValidationException
[build]       + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.SplitPathCo 
[build]      mmand
```
The build doesn't fail, but the output directory does not contain the required dlls.

**Environment**
- OS: Windows
- Compiler: msvc14.2

**To Reproduce**
1. vcpkq install qt5
2. create a qt5 project in a directory with square brackets
3. build

**Expected behavior**
The output directory should contain all dependencies.

**Comment by JackBoosY** [comment]
Hi @johannesstricker, sorry for late.
Does this issue still exist?

**Comment by JackBoosY** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.
