### ISSUE TITLE
realsense2:x64-windows - build configured with BUILD_WITH_TM2:BOOL=OFF doesn't work with T265 device.

### ISSUE THREAD

**Issue by piotr-tanski** [microsoft/vcpkg#10640]
It's related to the issue I've previously reported here: https://github.com/microsoft/vcpkg/issues/10545#issue-587497763.

The library doesn't work with Realsense T265 devices because the build is configured with BUILD_WITH_TM2:BOOL=OFF. The flag needs to be set to ON, acc. to librealsense documentation [source: https://github.com/IntelRealSense/librealsense/wiki/Build-Configuration]:

![obraz](https://user-images.githubusercontent.com/7444196/78108580-fbfd0180-73f7-11ea-9d90-1b695cffe3a8.png)

**Comment by NancyLi1013** [comment]
Hi @piotr-tanski 
Thanks for posting this issue.
It ssems like `BUILD_WITH_TM2` is default set as `ON`.
So we just need to remove `-DBUILD_WITH_TM2=OFF` or update this as` -DBUILD_WITH_TM2=ON`.

**Comment by piotr-tanski** [comment]
Hi @NancyLi1013 ,
Thanks for the reply.
Yes, it seems that `BUILD_WITH_TM2` flag is ON by default, in the librealsense source. It's set to OFF only when:

```
# Checking Internet connection, as TM2 needs to download the FW from amazon cloud
if(BUILD_WITH_TM2 AND NOT INTERNET_CONNECTION)
    message(WARNING "No internet connection, disabling BUILD_WITH_TM2")
    set(BUILD_WITH_TM2 OFF)
```
... but I can't see any warning like that in the cmake output.

I wonder if it's a good idea to always build the librealsense with the `BUILD_WITH_TM2=ON`, as it's not needed in many cases. Wouldn't it be a good idea to have separate packages on the vcpkg - the one available now, and the second one targeted at TM2 devices?

Kind regards,
Piotr

**Comment by NancyLi1013** [comment]
@piotr-tanski 
Thanks for your above info.
I also noticed this information. If `BUILD_WITH_TM2` is only needed by Realsense T265 devices, we may set `TM2 `as a feature for `realsense2`.
What do you think about this?

**Comment by piotr-tanski** [comment]
@NancyLi1013 
Sounds great for me.

**Comment by NancyLi1013** [comment]
You can add these codes to test on your machine and help confirm if this can work for you.
CONTROL:
```
Feature: tm2
Description: Build Intel® RealSense™ T265 device
```
portfile.cmake
```
set(BUILD_WITH_TM2 OFF)
if("tools" IN_LIST FEATURES)
    set(BUILD_WITH_TM2 ON)
endif()
```
update  `-DBUILD_WITH_TM2=OFF
` as  `-DBUILD_WITH_TM2=${BUILD_WITH_TM2}`

**Comment by piotr-tanski** [comment]
It works fine now.
However, to the portfile.cmake, I added following code:
```
set(BUILD_WITH_TM2 OFF)
if("tm2" IN_LIST FEATURES)
    set(BUILD_WITH_TM2 ON)
endif()
```
`tm2` instead of `tools`.

Thank you very much for help.

**Comment by NancyLi1013** [comment]
Thanks for your test and fedback.
Sorry for my mistake. I will submit a PR to fix this issue.

**Comment by NancyLi1013** [comment]
Hi @piotr-tanski 
Since the PR has been merged. I'm going to close this issue. Please try to update vcpkg and rebuild this.
