### ISSUE TITLE
How do I disable automatic copying of dependencies to the output folder

### ISSUE THREAD

**Issue by wdx04** [microsoft/vcpkg#10648]
Hi,
I'm building an Qt desktop application. Like Qt itself, my application consists of a main executable and several types of plugins in their designated subfolders.  When I build a plugin, the build system copies all DLL dependencies of that plugin to the plugin subfolder. These DLLs are useless because the operating system will locate plugins' dependent DLLs in the main executable folder. Also, the plugin loader complains about these DLLs because it assume all DLLs in the plugin subfolders are actual plugins. There are other problems about automatic copying of dependencies, for example, I'm building OpenCV with vcpkg, but I want to use the official OpenCV DLL with my application as the official DLL is significantly faster, now every time I rebuild my application, the official OpenCV DLL is overwritten by the vcpkg one, I have to delete it and copy the official one back.
So is there a way to completely disable automatic copying of dependencies to the output folder? I would rather copy them manually as required.
Thanks.

**Comment by Neumann-A** [comment]
If you are using cmake:
`option(VCPKG_APPLOCAL_DEPS "Automatically copy dependencies into the output directory for executables." ON)`
if you are using VS:
`<Target Name="AppLocalFromInstalled" AfterTargets="CopyFilesToOutputDirectory" BeforeTargets="CopyLocalFilesOutputGroup;RegisterOutput" Condition="'$(VcpkgEnabled)' == 'true' and '$(VcpkgApplocalDeps)' == 'true'">`

**Comment by wdx04** [comment]
> If you are using cmake:
> option(VCPKG_APPLOCAL_DEPS "Automatically copy dependencies into the output directory for executables." ON)
> if you are using VS:
> <Target Name="AppLocalFromInstalled" AfterTargets="CopyFilesToOutputDirectory" BeforeTargets="CopyLocalFilesOutputGroup;RegisterOutput" Condition="'$(VcpkgEnabled)' == 'true' and '$(VcpkgApplocalDeps)' == 'true'">

I turned off VCPKG_APPLOCAL_DEPS, then dependencies are not automatically copied. Thank you.
