### ISSUE TITLE
vcpkg upgrade interrupted, vcpkg upgrade again but say up-to-date

### ISSUE THREAD

**Issue by linquize** [microsoft/vcpkg#10654]
Find a library to upgrade.

```
git reset --hard <older-commit>
./vcpkg install <some-library>:x64-windows
git pull
./vcpkg upgrade --no-dry-run
The following packages will be rebuilt:
  * xxx[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/2: xxx:x64-windows
Removing package xxx:x64-windows...
Removing package xxx:x64-windows... done
Purging package xxx:x64-windows...
Purging package xxx:x64-windows... done
Elapsed time for package xxx:x64-windows: 8.097 ms
Starting package 2/2: xxx:x64-windows
Building package xxx[core]:x64-windows...
```
Before `vcpkg upgrade` finishes, press **Ctrl+C** to interrupt the build process.

Run `vcpkg upgrade` again.
```
./vcpkg upgrade --no-dry-run
All installed packages are up-to-date with the local portfiles.
```

**Comment by linquize** [comment]
Current problem is:
`vcpkg upgrade` performs remove, then build, then install.

remove:
Update status want = `purge`, status = `half-installed`
Delete files from `installed/`
Update status want = `purge`, status = `not-installed`

build:
If interrupted here, the package status want = `purge`, status = `not-installed`.

install:
Update status want = `install`, status = `half-installed`
Copy files to `installed/`
Update status want = `purge`, status = `not-installed`


For such removal, I suggest to mark another want value, so that `vcpkg upgrade` can determine the state between remove and install.
Currently, want `deinstall`, `hold`, `unknown` are not used.

**Comment by JackBoosY** [comment]
@dan-shaw Could you please have a look?

Thanks.

**Comment by dan-shaw** [comment]
@linquize @JackBoosY This is a known problem. The current upgrade command removes all packages before installing the new packages, so if it fails, not all packages will be installed.

**Comment by olafurw** [comment]
How about then giving a status screen at the end.

`Update complete, pages X and Y updated. Z failed to update and so it is removed. To try again, please fix the issue and reinstall package Z`

Currently, like in the duplicate #11805 there's nothing. System just stops and tells you nothing.

**Comment by linquize** [comment]
If vcpkg is killed, how do you tell package Z is missing?

**Comment by olafurw** [comment]
In my case it wasn't killed. Just failed to install due to a version mismatch. Same behavior as yours.

**Comment by dannypike** [comment]
This has just happened to me, and I am now slogging my way through all of the different projects, trying to restore all of their dependencies.

To avoid the problem in future (at least until the VCPKG team manage to create a fix for it), I am using this to create a "restore" batch script that will allow me to reinstall everything:
```
dir /b /ad packages | sed "s/\(.*\)_/vcpkg install \1:/w restore.cmd"
```
Running that after installing any new packages will create a restore.cmd script that looks like this:
```
vcpkg install args:x64-windows
vcpkg install args:x86-windows
vcpkg install boost-vcpkg-helpers:x64-windows
vcpkg install bzip2:x64-windows
vcpkg install glfw3:x64-windows
.
.
.
```
As ```install``` is idempotent, it will recover all of the "forgotten" packages when an ```upgrade``` fails.

Hope it helps. :)

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/4360
