### ISSUE TITLE
Error: Building package openssl-windows:x86-windows failed with: BUILD_FAILED[<port name>] build failure

### ISSUE THREAD

**Issue by MohammadGhasemi** [microsoft/vcpkg#10652]
**Host Environment**
- OS: Windows 10
- Compiler: msvc 14.25

**To Reproduce**
`./vcpkg install libtorrent`

**Failure logs** 
Error: Building package openssl-windows:x86-windows failed with: BUILD_FAILED
Package: openssl-windows:x86-windows
Vcpkg version: 2020.02.04-nohash

**Additional context**
I tried .\vcpkg update

**Comment by NancyLi1013** [comment]
Hi @MohammadGhasemi 
Thanks for posting this issue.
Could you please provide the failure log?

**Comment by MohammadGhasemi** [comment]
> Hi @MohammadGhasemi
> Thanks for posting this issue.
> Could you please provide the failure log?

Sure, where is it?

**Comment by NancyLi1013** [comment]
I'm not sure in which step you encountered this issue.
You can post the build process on the console and also provide the failure log in _VCPKG_ROOT_PATH\buildtrees\openssl-windows\configure-x86windows-dbg-out.log_
or 
_VCPKG_ROOT_PATH\buildtrees\openssl-windows\install-x86windows-dbg-out.log_.

**Comment by MohammadGhasemi** [comment]
build process on the console:
https://pastebin.pl/view/ce273d81

those log files were not there, but there were two other files:
stdout-x86-windows.log
https://pastebin.pl/view/dafcd1a7
and
x86-windows.vcpkg_abi_info.txt
https://pastebin.pl/view/d1e4ed33

**Comment by NancyLi1013** [comment]
```
Starting package 58/81: openssl-windows:x86-windows
Building package openssl-windows[core]:x86-windows...
-- Downloading http://strawberryperl.com/download/5.30.0.1/strawberry-perl-5.30.0.1-32bit.zip...
-- Downloading http://strawberryperl.com/download/5.30.0.1/strawberry-perl-5.30.0.1-32bit.zip... Failed. Status: 22;"HTTP response code said error"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:175 (message):
 
      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues
 
Call Stack (most recent call first):
  scripts/cmake/vcpkg_find_acquire_program.cmake:343 (vcpkg_download_distfile)
  ports/openssl-windows/portfile.cmake:9 (vcpkg_find_acquire_program)
  scripts/ports.cmake:90 (include)
```
Could you please help confirm if you have access to http://strawberryperl.com/download/5.30.0.1/strawberry-perl-5.30.0.1-32bit.zip?
You can download this archive manually, then put it into _C:/Users/mohammad/Downloads/vcpkg-master/downloads/_ and rebuild it again.

**Comment by MohammadGhasemi** [comment]
Yes, that solved the problem.  Thank you very much! For some reason I had to use a VPN to download the file. I think that has something to do with the sanction laws. Now I should be able to #include the library. But I still get LNK2019 error. :-(

**Comment by NancyLi1013** [comment]
Please post the error info.
If possible, you can also provide your project case.

**Comment by MohammadGhasemi** [comment]
error:
https://pastebin.pl/view/5d0727cc
project: (it only needs libtorrent library installed)
https://pastebin.pl/view/59935020

**Comment by NancyLi1013** [comment]
Have you tried to use these?
 ```
 find_package(LibtorrentRasterbar CONFIG REQUIRED)
 target_link_libraries(main PRIVATE LibtorrentRasterbar::torrent-rasterbar)
```

**Comment by MohammadGhasemi** [comment]
Yes. Error:
https://pastebin.pl/view/2ad25f2b

**Comment by NancyLi1013** [comment]
Have you run the command  `./vcpkg integrate install ` and set `CMAKE_TOOLCHAIN_FILE` before configuring?

**Comment by MohammadGhasemi** [comment]
I haven't done the second one . Thank you it compiles now. :-)

**Comment by NancyLi1013** [comment]
Thanks for your update.
Since this issue has been fixed, I am closing it for now.
