### ISSUE TITLE
[boost] find package failure with MSVC 2013 / v120 

### ISSUE THREAD

**Issue by ManuelKugelmann** [microsoft/vcpkg#10669]
Folow up to #10643

**Describe the bug**
FindBoost does not work, because `vcpkg.cmake:248 `does this    `set(Boost_COMPILER "-vc140")`.
It needs to be `"-vc140" `for this use case.

**Environment**
- OS: Windows 10
- Compiler: MSVC 2013 / v120

**To Reproduce**
1. Fix #10643 and then build boost with v120
2. find_package(Boost)

**Comment by JackBoosY** [comment]
Hi @ManuelKugelmann, thanks for reporting this issue!
vcpkg requires Visual Studio 2015 or later, so we won't fix this issue.
See [documentation](https://github.com/microsoft/vcpkg#quick-start-windows).

**Comment by ManuelKugelmann** [comment]
Hi @JackBoosY, afaik vcpkg supports the "v120" toolset now. 
Please see https://github.com/microsoft/vcpkg/pull/10670 for a fix to this issue.
