### ISSUE TITLE
Security issue: openssl package is detected as a Gen:Variant.Ursu.761595 by 9 different antivirus

### ISSUE THREAD

**Issue by Milerius** [microsoft/vcpkg#10668]
In our team 4 different people get the same analysis:

- https://www.virustotal.com/gui/file/22b1d2d99ee9366e686444656f46e35e39d7e76c455a9269a0ae6e3cb3272210/detection

package: `openssl-windows:x64-Windows` only in Release, not in debug

file infected: `buildtrees\openssl-windows\x64-windows-rel\test\version.exe`

Even worst, when we build in Release, the Ursu trojan which is a virus that allow installation of stuff without asking the user seem's to install a crypto mining trojan named:

`Gen:Variant.Razy.577635`

This happens to the final binary when we build with vcpkg.

When we build without vcpkg we don't have any warnings by any other antivirus.

I think that's a serious problem, we cannot release our binary with such a virustotal report.

**Comment by timautry** [comment]
- It is highly possible a false positive
- I just ran the same file with mixed results:
   - compiled vcpkg with vs 2017 toolset v141:
      - only one engine detected
      - https://www.virustotal.com/gui/file/2759ea16b506b024a469d8ac71e6d8f58e7e0d8313ed608d7bc6440f1665aae9/detection  
   - compiled vcpkg with vs 2019 toolset v142: 
      - no engines identified 
      -  https://www.virustotal.com/gui/file/0c8595384ae66ba5a7aac49f772da3c0d973bb18a8a36275970596ed2c6ee107/detection

**Comment by Milerius** [comment]
It's cannot be a false positive with 9 different antivirus from 4 different computer with fresh machine.

First time when you install it, nothing happens, it's come later when you use vcpkg, for building etc

**Comment by timautry** [comment]
Other alternatives could be the machines and/or the image they were built from are compromised.
This is highly probable as you state "_First time when you install it, nothing happens, it's come later when you use vcpkg, for building etc_" the system may be clean then become infected or a certain action activates the malware ... maybe a site or a network...
- vs 2017 toolset v141 no detection : https://www.virustotal.com/gui/file/92d1d9b2a98c29f323d28394c8d1722d7170c360e0dbc3f27b6101e00eb1baab/detection
- vs 2019 toolset v142 no detection: 
https://www.virustotal.com/gui/file/3bec8a85863063a7b1b564e46b8d4c1a1af5fa6aba64e6100906f7ce8bb39d6b/detection

**Comment by Milerius** [comment]
@timautry I made a fresh test with a fresh machine with windows official installer + parallel desktop. building vcpkg, instantly flagged by all antivirus...

**Comment by timautry** [comment]
@Milerius  I do not know what else to say???
You can view the submitted file(s) information from my current machine with only 1 positive on versions.exe compiled with VS 2017, none on the versions.exe compiled with VS 2019 and no positive hits on vcpkg.exe compiled with VS 2017 and VS 2019 as scanned by the hundred or more vendors Virus Total uses to scan files submissions.

**Comment by Neumann-A** [comment]
just saying:
version.c
```
/* A simple helper for the perl function OpenSSL::Test::openssl_versions */
int main(void)
{
    printf("Build version: 0x%08lX\n", OPENSSL_VERSION_NUMBER);
    printf("Library version: 0x%08lX\n", OpenSSL_version_num());
    return 0;
}
```
cversion.c
```
unsigned long OpenSSL_version_num(void)
{
    return OPENSSL_VERSION_NUMBER;
}
```
x64-windows-static latest VS
https://www.virustotal.com/gui/file/b83274cc103740a4a948cc5cb2158b578bff95ce9a824aeee498bad877377b02/detection
x64-windows
https://www.virustotal.com/gui/file/896c8b5867d1bb8828cfce021ebe37638bc509272cfcc42d172206ff3e187caf/detection
nothing

Go clean your infected/vulnerable network/pcs?

**Comment by Milerius** [comment]
According to https://www.gamedev.net/forums/topic/700800-malware-is-compiled-into-my-exe-but-only-for-one-project/?page=1

It's can be due to my optimization compilation flag that generate a code that look like the virus signature

**Comment by Milerius** [comment]
Yeah it's was that all my CXX flags was with 03 by default result in every binary with infected signature like. I'm closing it
