### ISSUE TITLE
macOS applocal.py appending path infinitely

### ISSUE THREAD

**Issue by christophe-calmejane** [microsoft/vcpkg#10665]
**Describe the bug**
The applocal.py script running on a macOS bundle appends `../Frameworks` each time a compilation is ran.

**Environment**
- OS: macOS
- Compiler: Xcode 11

**To Reproduce**
Create a simple project that is using a shared library on macOS so the applocal.py script is ran, like this one (change paths obviously):
```
cmake_minimum_required(VERSION 3.12)

set(CMAKE_TOOLCHAIN_FILE "/Users/christophe.calmejane/dev/vcpkg/scripts/buildsystems/vcpkg.cmake" CACHE STRING "")
set(VCPKG_TARGET_TRIPLET "x64-osx-dynamic" CACHE STRING "")

project(Test LANGUAGES CXX VERSION 1.0.0.1)
set(CMAKE_CXX_STANDARD 17)

find_package(curl CONFIG REQUIRED)

add_executable(Test MACOSX_BUNDLE test.cpp)
target_link_libraries(Test PRIVATE CURL::libcurl)

set_target_properties(Test PROPERTIES XCODE_ATTRIBUTE_OTHER_CODE_SIGN_FLAGS "--deep --strict --force --options=runtime")
set_target_properties(Test PROPERTIES XCODE_ATTRIBUTE_ENABLE_HARDENED_RUNTIME YES)
```
With a simple test.cpp file:
```
#include <stdio.h>
#include <curl/curl.h>

int main()
{
	printf("V: %s\n",curl_version());
	return 0;
}
```
* Generate a cmake solution using Xcode generator:
`cmake -H. -B_buil -G Xcode`
* Go to build folder
* Compile:
`cmake --build .`
* Look at generated binary dynamic loader dependencies:
`otool -L Debug/Test.app/Contents/MacOS/Test`
* You should have this:
`@executable_path/../Frameworks/libcurl-d.dylib`
* Compile again (without cleaning):
`cmake --build .`
* Now look again at dependencies and you get this:
`@executable_path/../Frameworks/../Frameworks/libcurl-d.dylib`
* Run again, and it goes forever... which might cause undefined behaviour after a few compilations

**Bonus issue**
The script is replacing existing `@rpath` with `@executable_path` which might not be desirable

**Comment by christophe-calmejane** [comment]
Well, it's actually more dramatic than I thought.
Using the latest Xcode and macOS version, as soon as there is more than 1 recursion it's causing an app crash when launching it:
`error: Bad executable (or shared library)`

**Comment by christophe-calmejane** [comment]
I started to update the script for my own needs but I do not master python at all.
The basic idea would be:
- if a dependency is using `@rpath`, use `otool -l` to retrieve the RPATH value and use it instead of hardcoding `../Frameworks`
- if a dependency is using `@executable_path`, extract the relative path from executable to library (eg. `@executable_path`/../Frameworks/libcurl.dylib` -> `../Frameworks/`)
- if a dependency is using something else but still matching the script's current regex (`^@.*path/`) then keep what the script is currently doing (ie. replacing to `@executable_path/../Frameworks`)

I think it should solve both issues and be more robust.

**Comment by christophe-calmejane** [comment]
This is what I wrote to retrieve RPATH
```python
def get_lcrpath(filename):
    process_output = namedtuple('ProcessOutput', ['stdout', 'stderr', 'retcode'])
    try:
        p1 = Popen(["otool", "-l", filename], stdout=PIPE)
        p2 = Popen(["grep", "LC_RPATH", "-A2"], stdin=p1.stdout, stdout=PIPE)
        p3 = Popen(["grep", "path"], stdin=p2.stdout, stdout=PIPE)
        p4 = Popen(["sed", "-e", "s/\(.*path @[^/]*\)\(.*\)\( (.*)\)/\\2/g"], stdin=p3.stdout, stdout=PIPE)
        stdout, stderr = p4.communicate(b'')
        stdout = stdout.replace('\n', '')
        proc_out = process_output(stdout, stderr, p4.returncode)
        return proc_out
    except Exception as exc:
        GlobalConfig.logger.error('\texception: {0}'.format(exc))
        return process_output('', exc.message, -1)

```

**Comment by JackBoosY** [comment]
@ras0219-msft Could you please have a look?

Thanks.

**Comment by JackBoosY** [comment]
cc @strega-nil

**Comment by BillyONeal** [comment]
@vicroms You contributed this feature, can you take a look?

**Comment by JackBoosY** [comment]
Ping @strega-nil-ms

**Comment by jimwang118** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
