### ISSUE TITLE
[flatbuffers] update to 1.12.0

### ISSUE THREAD

**Issue by codehz** [microsoft/vcpkg#10663]
Library name: flatbuffers

New version number: 1.12.0

Other information that may be useful (release notes, etc...)

> 
>     An official Swift port! (including gRPC support).
>     A Kotlin port!
>     Object API and native JSON support for C#.
>     Object API and gRPC support for Python.
>     Object API for Go.
>     FlexBuffers for Java.
>     Many other fixes and smaller improvements, 247 commits since 1.11.0
>

**Comment by NancyLi1013** [comment]
Hi @codehz 
Thanks for posting this issue.
The PR has been merged and please try to update vcpkg and use it.
