### ISSUE TITLE
[New Port Request] Ghostscript

### ISSUE THREAD

**Issue by dhrdlicka** [microsoft/vcpkg#10687]
Library name: Ghostscript

Library description: An interpreter for the PostScript language and for PDF.

Source repository URL: http://git.ghostscript.com/?p=ghostpdl.git;a=summary

Project homepage (if different from the source repository): https://www.ghostscript.com/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
