### ISSUE TITLE
[New Port Request] open-vcdiff

### ISSUE THREAD

**Issue by BullyWiiPlaza** [microsoft/vcpkg#10684]
Library name: open-vcdiff

Library description: An encoder/decoder for the VCDIFF (RFC3284) format

Source repository URL: https://github.com/google/open-vcdiff

Project homepage (if different from the source repository): -

Anything else that is useful to know when adding (such as optional features the library may have that should be included): -

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
