### ISSUE TITLE
[abseil] please merge PR #637

### ISSUE THREAD

**Issue by phiysng** [microsoft/vcpkg#10690]
Library name:

abseil fail to complie on Windows's MSVC complier.

see [ISSUE #357](https://github.com/abseil/abseil-cpp/issues/357).

for example:

```c++

typedef absl::InlinedVector<int, 10> IntVec;
  
absl::InlinedVector<int,10> vec;
```

the complier refused to compile:
```
error C3546: '...': there are no parameter packs available to expand
```

New version number:

this bug seemed to be fixed on [PR#637](https://github.com/abseil/abseil-cpp/commit/b92f35f65fa5298d430eab49c1831b5f3e9594c8).

Can vcpkg update its version to a new version that fix this issue or make a patch to get around this(like [this](https://github.com/microsoft/vcpkg/blob/master/ports/abseil/fix-lnk2019-error.patch)?

environment info:

- up-to-date VS2019

- abseil:x64-windows                                 2020-03-03-1     an open-source collection designed to augment th...

**Comment by LilyWangL** [comment]
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.
