### ISSUE TITLE
no ffplay.exe

### ISSUE THREAD

**Issue by dbyoung720** [microsoft/vcpkg#10697]
vcpkg install ffmpeg[ffplay]:x64-windows-static
compile ok, but not ffplay.exe

OS:WIN10X64
LG:VS2019

**Comment by Brainiarc7** [comment]
The ffplay binary requires FFmpeg to be compiled with SDL support,
otherwise it's skipped.

**Comment by dbyoung720** [comment]
sdl2 I have compiled

**Comment by myd7349** [comment]
Please give this a try:
> vcpkg install ffmpeg[ffplay]

`ffplay` is an optional feature defined in `ffmpeg`'s CONTROL file.
