### ISSUE TITLE
building boost-uwp error

### ISSUE THREAD

**Issue by bigdimboom** [Microsoft/vcpkg#1069]
Building x64-uwp-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process_repeat.cmake:21 (message):
    Command failed: C:/dev/vcpkg/buildtrees/boost/src/boost_1_64_0/b2.exe;--stagedir=C:/dev/vcpkg/buildtrees/boost/x64-uwp-rel/stage;--build-dir=C:/dev/vcpkg/buildtrees/boost/x64-uwp-rel;-sZLIB_INCLUDE="C:/dev/vcpkg/installed/x64-uwp\include";-sBZIP2_INCLUDE="C:/dev/vcpkg/installed/x64-uwp\include";-j8;--debug-configuration;--hash;-q;--without-python;threading=multi;runtime-link=shared;link=shared;address-model=64;windows-api=store;--without-type_erasure;--without-log;--without-mpi;--without-wave;--without-coroutine;--without-metaparse;--without-locale;--without-timer;--without-program_options;--without-test;--without-filesystem;--without-thread;--without-iostreams;--without-container;toolset=msvc-14.1;-sZLIB_BINARY=zlib;-sZLIB_LIBPATH="C:/dev/vcpkg/installed/x64-uwp\lib";-sBZIP2_BINARY=bz2;-sBZIP2_LIBPATH="C:/dev/vcpkg/installed/x64-uwp\lib";variant=release;debug-symbols=on
    Working Directory: C:/dev/vcpkg/buildtrees/boost/src/boost_1_64_0
    See logs for more information:
      C:\dev\vcpkg\buildtrees\boost\build-x64-uwp-rel-out.log
      C:\dev\vcpkg\buildtrees\boost\build-x64-uwp-rel-err.log

Call Stack (most recent call first):
  ports/boost/portfile.cmake:188 (vcpkg_execute_required_process_repeat)
  scripts/ports.cmake:73 (include)

Error: Building package boost:x64-uwp failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost:x64-uwp
  Vcpkg version: 0.0.81-c25faaa7e91bd5dd75b5d326aaf0fd5ca745d50c

Additionally, attach any relevant sections from the log files above.

**Comment by ras0219-msft** [comment]
Thanks for reporting this! It should be fixed in 74c2c23.
