### ISSUE TITLE
吐槽 VCPKG

### ISSUE THREAD

**Issue by dbyoung720** [microsoft/vcpkg#10698]
吐槽 VCPKG

1、下载没有进度显示、不能断点续传；不知道什么时候会出错；
2、编译没有进度，像个傻瓜一样干等着,不知道什么时候会出错；
3、随便编译了一个 libvpx 就报错了；
4、再编译一个 ffplay 看看，编程是成功了，就是没有 bin,ffplay.exe 不知道哪里去了；

**Comment by linquize** [comment]
English
1. Download without showing progress. No resume download.
2. Build without showing progress. Waiting madly. Don't know where error occurs.
3. Build libvpx error
4. Build ffplay seems to be successful, however, `ffplay.exe` not found in `bin`

**Comment by JackBoosY** [comment]
> 1. 一般情况下下载的都是工具或源代码包，工具只用下载一次，源代码包很小的，所以没加进度。不过以后应该会加。
> 2. 编译进度需要与编译系统深度配合，而vcpkg目前只是封装了一次编译过程，所以比较难。vcpkg并不是像apt，yum类型包管理器。这些包管理器只需要下载二进制，而vcpkg需要进行编译步骤。
> 3. 请提供编译失败日志。谢谢。
> 4. ffplay是ffmpeg的feature，请使用ffmpeg[ffplay]来编译。

1. In general, tools or source code packages are downloaded. Tools are only downloaded once. The source code package is very small, so no progress is made. But it should be added in the future.
2. The build progress needs to be deeply coordinated with the compilation system, and vcpkg currently only encapsulates a compilation process, so it is more difficult. vcpkg is not like apt, yum type package manager. These package managers only need to download binaries, while vcpkg needs to be compiled.
3. Please provide the failure logs. Thanks.
4. ffplay is a feature of ffmpeg, please use `ffmpeg[ffplay]` to build.
