### ISSUE TITLE
libvpx build failure

### ISSUE THREAD

**Issue by dbyoung720** [microsoft/vcpkg#10696]
**Host Environment**
- OS:WIN10X64
- Compiler: VS2019

**To Reproduce**
`./vcpkg install libvpx`

**Failure logs** 
-- Building E:/Source/Microsoft/vcpkg/buildtrees/libvpx/x64-windows-static/vpx.vcxproj for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: msbuild E:/Source/Microsoft/vcpkg/buildtrees/libvpx/x64-windows-static/vpx.vcxproj /p:Configuration=Release /t:Rebuild /p:Platform=x64 /p:PlatformToolset=v142 /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /p:WindowsTargetPlatformVersion=10.0.18362.0 /m /p:WholeProgramOptimization=false
    Working Directory: E:/Source/Microsoft/vcpkg/buildtrees/libvpx/x64-windows-static-rel
    Error code: 1
    See logs for more information:
      E:\Source\Microsoft\vcpkg\buildtrees\libvpx\build-x64-windows-static-rel-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_msbuild.cmake:119 (vcpkg_execute_required_process)
  ports/libvpx/portfile.cmake:73 (vcpkg_build_msbuild)
  scripts/ports.cmake:90 (include)

Error: Building package libvpx:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libvpx:x64-windows-static
  Vcpkg version: 2020.02.04-nohash

[libvpx.zip](https://github.com/microsoft/vcpkg/files/4431848/libvpx.zip)

**Comment by timautry** [comment]
@dbyound720 - see issue vcpkg unable to find yasm.exe #10523 for a possible resolution.
