### ISSUE TITLE
bootstrap-vcpkg.sh does not build on clang-10

### ISSUE THREAD

**Issue by acgetchell** [microsoft/vcpkg#10699]
**Describe the bug**
`vcpkg` does not build on Clang-10

**Environment**
- OS: Ubuntu 18.04
- Compiler: clang 10.0.0

**To Reproduce**
1. ./bootstrap-vcpkg.sh
2. See error

```
CMake Error at CMakeLists.txt:63 (message):
535  Can't find which C++ runtime is in use
```

**Expected behavior**
`vcpkg` to build

**Failure logs** 
https://travis-ci.com/github/acgetchell/CDT-test/jobs/314214540#L508

**Additional context**
https://github.com/acgetchell/CDT-test/blob/master/.travis.yml

**Comment by linquize** [comment]
https://github.com/acgetchell/CDT-test/blob/65757c280d0a4e7f857f347111ad6713f0a6b6e0/.travis.yml#L44

Should be `- if [[ "$CXX" == "clang++" ]]; then export CXX="clang++-10" CC="clang-10"; fi`

**Comment by acgetchell** [comment]
Indeed.

https://travis-ci.com/github/acgetchell/CDT-test/jobs/314409425

Thanks for pointing out my mistake!
