### ISSUE TITLE
glib build failure

### ISSUE THREAD

**Issue by dbyoung720** [microsoft/vcpkg#10701]
**Host Environment**
- OS:WIN10X64
- Compiler: VS2019

**To Reproduce**
`vcpkg install glib:x64-windows-static`

**Comment by Voskrese** [comment]
log files?

**Comment by dbyoung720** [comment]
need log ?
Have you tested it?
vcpkg install glib: x64-windows-static
Can it be compiled successfully?

**Comment by Voskrese** [comment]
Do you suggest everyone test? and it should be written that only a dynamic assembly

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Glib static build will be fixed in PR #9593.
