### ISSUE TITLE
[New Port Request] <mmg>

### ISSUE THREAD

**Issue by Foadsf** [microsoft/vcpkg#10706]
Library name: **mmg**

Library description: mmg is open-source software for bidimensional and tridimensional surface and volume remeshing.

Source repository URL:  https://github.com/MmgTools/mmg

Project homepage (if different from the source repository): https://www.mmgtools.org/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
