### ISSUE TITLE
[New Port Request] <elastic>

### ISSUE THREAD

**Issue by Foadsf** [microsoft/vcpkg#10707]
Library name: elastic (formerly ELAS)

Library description: Elastic is a simple yet efficient finite element solver for linear elasticity problems in two and three dimensions.

Source repository URL: https://github.com/ISCDtoolbox/LinearElasticity

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by Foadsf** [comment]
@PhoebeHui what is the point of having the `[New Port Request]` tags if you close the requests without implementing them?!
