### ISSUE TITLE
[live555] build failure

### ISSUE THREAD

**Issue by how0723** [microsoft/vcpkg#10711]
**Host Environment**
- OS: Win10 64bit
- Compiler: msvc142

**To Reproduce**
`./vcpkg install live555`

**Failure logs** 
Starting package 3/3: live555:x64-windows-static
Building package live555[core]:x64-windows-static...
CMake Error at ports/live555/portfile.cmake:5 (message):
  Live555 does not have persistent releases.  Please re-run the installation
  with --head.
Call Stack (most recent call first):
  scripts/ports.cmake:90 (include)

Error: Building package live555:x64-windows-static failed with: BUILD_FAILED

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by cenit** [comment]
as the log says, please use this command:

`./vcpkg install live555 --head`

**Comment by roalz** [comment]
> as the log says, please use this command:
> 
> `./vcpkg install live555 --head`

Sorry to bother in a closed issue, but I'm using vcpkg manifests and I can't find how to use the --head option with manifests.
I've also tried `vcpkg install --head` in the root manifest folder, but it seems the --head option is not used at all.

  Package: live555:x64-windows
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e
