### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by therock247uk** [microsoft/vcpkg#10716]
hi i get this when trying to install vcpkg

Program 'bootstrap-vcpkg.bat' failed to run: The specified executable is not a valid application for this OS

**Comment by drescherjm** [comment]
I think you tried to execute the script in the wrong folder.

**Comment by JackBoosY** [comment]
Hi @therock247uk, thanks for reporting this isssue!
Without more details, I cannot help you solve this issue.
So please provide OS version, compiler version.

Thanks.

**Comment by strega-nil** [comment]
Since there has been no information about this, I'm going to assume that the issue is solved. If you need anything else, please don't hesitate to reopen @therock247uk :)
