### ISSUE TITLE
[New Port Request] CTP (Comprehensive Transaction Platform) API client library

### ISSUE THREAD

**Issue by xgao1023** [microsoft/vcpkg#10719]
Library name: ctp

Library description: The Comprehensive Transaction Platform (CTP) is a future brokerage management system developed specially for futures companies. CTP API client library allows users to connect to CTP gateway for algorithmic trading.

Source repository URL: N/A

Project homepage (if different from the source repository): http://www.sfit.com.cn

This is a binary package that support Windows and Linux only.

**Comment by xgao1023** [comment]
I already have a pull request
https://github.com/microsoft/vcpkg/pull/10717

**Comment by PhoebeHui** [comment]
The PR has been merged, thanks for your contribution!
