### ISSUE TITLE
How do I install curl on ARM64

### ISSUE THREAD

**Issue by xiejiulong** [microsoft/vcpkg#10725]
I try 
./vcpkg install curl on Linux_ARM64, (NOT x64)
but when install curl's dependency openssl, vcpkg failed.
and install grpc / poco libs has the same problem with openssl.
I use the tag 2020_01 vcpkg version, should use the newest version?
how can i resolve this problem?
thanks very much!

**Comment by NancyLi1013** [comment]
Hi @xiejiulong 
Thanks for posting this issue.
arm64-linux is currently not supported by vcpkg.
All the supported triplets are listed [here](https://github.com/microsoft/vcpkg/tree/master/triplets).

**Comment by xiejiulong** [comment]
**Hi @NancyLi1013 
thanks for your response
for example, I install grpc which dependency openssl,the error out:**
root@Ubuntu:/ssd/vcpkg/vcpkg# ./vcpkg install grpc
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
The following packages will be built and installed:
    grpc[core]:x64-linux
  * openssl[core]:x64-linux
  * openssl-unix[core]:x64-linux
Additional packages (*) will be modified to complete this operation.
Starting package 1/3: openssl-unix:x64-linux
Building package openssl-unix[core]:x64-linux...
-- Using cached /ssd/vcpkg/vcpkg/downloads/openssl-1.1.1d.tar.gz
-- Using source at /ssd/vcpkg/vcpkg/buildtrees/openssl-unix/src/1.1.1d-b1f8ae3e6c
-- Configuring x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: /usr/local/bin/cmake /ssd/vcpkg/vcpkg/ports/openssl-unix -DSOURCE_PATH=/ssd/vcpkg/vcpkg/buildtrees/openssl-unix/src/1.1.1d-b1f8ae3e6c -DPERL=/usr/bin/perl -DMAKE=/usr/bin/make -DCMAKE_MAKE_PROGRAM=/usr/bin/ninja -DCMAKE_SYSTEM_NAME=Linux -DBUILD_SHARED_LIBS=ON -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/ssd/vcpkg/vcpkg/scripts/toolchains/linux.cmake -DVCPKG_TARGET_TRIPLET=x64-linux -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=external -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=/ssd/vcpkg/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_TARGET_ARCHITECTURE=arm64 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/ssd/vcpkg/vcpkg/packages/openssl-unix_x64-linux/debug
    Working Directory: /ssd/vcpkg/vcpkg/buildtrees/openssl-unix/x64-linux-dbg
    Error code: 1
    See logs for more information:
      /ssd/vcpkg/vcpkg/buildtrees/openssl-unix/config-x64-linux-dbg-out.log
      /ssd/vcpkg/vcpkg/buildtrees/openssl-unix/config-x64-linux-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:304 (vcpkg_execute_required_process)
  ports/openssl-unix/portfile.cmake:41 (vcpkg_configure_cmake)
  scripts/ports.cmake:94 (include)


Error: Building package openssl-unix:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openssl-unix:x64-linux
  Vcpkg version: 2020.01.17-unknownhash

Additionally, attach any relevant sections from the log files above.
root@Ubuntu:/ssd/vcpkg/vcpkg#
--------------------------------------------------------------------------------------------------------------
**Can this problem solved?
I install jsoncpp which not dependency openssl, there is no problem, every thing is ok.
It't looks like all libs which dependency openssl has the compile problem.
thanks very much.**

**Comment by xiejiulong** [comment]
Hi @NancyLi1013 
Thanks for response.
some libs on ARM-64 can compile, such as jsoncpp,zlib and so on.
my arm64-linux.cmake like below:
set(VCPKG_TARGET_ARCHITECTURE arm64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)

set(VCPKG_CMAKE_SYSTEM_NAME Linux)

and I use the command below:
**./vcpkg install grpc --triplet arm64-linux**
**c-ares install ok.
zlib install ok.
protobuf looks like install ok.
but when install openssl-unix occurs error below**:


root@Ubuntu:/ssd/vcpkg/vcpkg# ./vcpkg install grpc --triplet arm64-linux
The following packages will be built and installed:
  * c-ares[core]:arm64-linux
    grpc[core]:arm64-linux
  * openssl[core]:arm64-linux
  * openssl-unix[core]:arm64-linux
  * protobuf[core]:arm64-linux
  * zlib[core]:arm64-linux
Additional packages (*) will be modified to complete this operation.
Starting package 1/6: c-ares:arm64-linux
Building package c-ares[core]:arm64-linux...
-- Using cached /ssd/vcpkg/vcpkg/downloads/c-ares-c-ares-9f1fdbf5dd633f81352fac0d6bc0d0c4d45be459.tar.gz
-- Using source at /ssd/vcpkg/vcpkg/buildtrees/c-ares/src/c4d45be459-24e25a63ee
-- Configuring arm64-linux-dbg
-- Configuring arm64-linux-rel
-- Building arm64-linux-dbg
-- Building arm64-linux-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package c-ares[core]:arm64-linux... done
Installing package c-ares[core]:arm64-linux...
Installing package c-ares[core]:arm64-linux... done
Elapsed time for package c-ares:arm64-linux: 1.314 min
Starting package 2/6: zlib:arm64-linux
Building package zlib[core]:arm64-linux...
-- Using cached /ssd/vcpkg/vcpkg/downloads/zlib1211.tar.gz
-- Extracting source /ssd/vcpkg/vcpkg/downloads/zlib1211.tar.gz
-- Applying patch cmake_dont_build_more_than_needed.patch
-- Using source at /ssd/vcpkg/vcpkg/buildtrees/zlib/src/1.2.11-f690224aeb
-- Configuring arm64-linux-dbg
-- Configuring arm64-linux-rel
-- Building arm64-linux-dbg
-- Building arm64-linux-rel
arm64-linux-- Installing: /ssd/vcpkg/vcpkg/packages/zlib_arm64-linux/share/zlib/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package zlib[core]:arm64-linux... done
Installing package zlib[core]:arm64-linux...
Installing package zlib[core]:arm64-linux... done
Elapsed time for package zlib:arm64-linux: 15 s
Starting package 3/6: protobuf:arm64-linux
Building package protobuf[core]:arm64-linux...
-- Using cached /ssd/vcpkg/vcpkg/downloads/protocolbuffers-protobuf-v3.11.2.tar.gz
-- Using source at /ssd/vcpkg/vcpkg/buildtrees/protobuf/src/v3.11.2-b4b83ed380
-- Configuring arm64-linux-dbg
-- Configuring arm64-linux-rel
-- Building arm64-linux-dbg
-- Building arm64-linux-rel
-- Installing: /ssd/vcpkg/vcpkg/packages/protobuf_arm64-linux/tools/protobuf/protoc
-- Installing: /ssd/vcpkg/vcpkg/packages/protobuf_arm64-linux/tools/protobuf/protoc-3.11.2.0
-- Installing: /ssd/vcpkg/vcpkg/packages/protobuf_arm64-linux/share/protobuf/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package protobuf[core]:arm64-linux... done
Installing package protobuf[core]:arm64-linux...
Installing package protobuf[core]:arm64-linux... done
Elapsed time for package protobuf:arm64-linux: 8.966 min
Starting package 4/6: openssl-unix:arm64-linux
Building package openssl-unix[core]:arm64-linux...
-- Using cached /ssd/vcpkg/vcpkg/downloads/openssl-1.1.1d.tar.gz
-- Using source at /ssd/vcpkg/vcpkg/buildtrees/openssl-unix/src/1.1.1d-b1f8ae3e6c
-- Configuring arm64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: /usr/local/bin/cmake /ssd/vcpkg/vcpkg/ports/openssl-unix -DSOURCE_PATH=/ssd/vcpkg/vcpkg/buildtrees/openssl-unix/src/1.1.1d-b1f8ae3e6c -DPERL=/usr/bin/perl -DMAKE=/usr/bin/make -DCMAKE_MAKE_PROGRAM=/usr/bin/ninja -DCMAKE_SYSTEM_NAME=Linux -DBUILD_SHARED_LIBS=ON -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/ssd/vcpkg/vcpkg/scripts/toolchains/linux.cmake -DVCPKG_TARGET_TRIPLET=arm64-linux -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=external -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=/ssd/vcpkg/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_TARGET_ARCHITECTURE=arm64 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/ssd/vcpkg/vcpkg/packages/openssl-unix_arm64-linux/debug
    Working Directory: /ssd/vcpkg/vcpkg/buildtrees/openssl-unix/arm64-linux-dbg
    Error code: 1
    See logs for more information:
      /ssd/vcpkg/vcpkg/buildtrees/openssl-unix/config-arm64-linux-dbg-out.log
      /ssd/vcpkg/vcpkg/buildtrees/openssl-unix/config-arm64-linux-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:304 (vcpkg_execute_required_process)
  ports/openssl-unix/portfile.cmake:41 (vcpkg_configure_cmake)
  scripts/ports.cmake:94 (include)


Error: Building package openssl-unix:arm64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openssl-unix:arm64-linux
  Vcpkg version: 2020.01.17-unknownhash

Additionally, attach any relevant sections from the log files above.
root@Ubuntu:/ssd/vcpkg/vcpkg# arm64-linux


**How can I solve this problem?**
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: /usr/local/bin/cmake /ssd/vcpkg/vcpkg/ports/openssl-unix -DSOURCE_PATH=/ssd/vcpkg/vcpkg/buildtrees/openssl-unix/src/1.1.1d-b1f8ae3e6c -DPERL=/usr/bin/perl -DMAKE=/usr/bin/make -DCMAKE_MAKE_PROGRAM=/usr/bin/ninja -DCMAKE_SYSTEM_NAME=Linux -DBUILD_SHARED_LIBS=ON -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/ssd/vcpkg/vcpkg/scripts/toolchains/linux.cmake -DVCPKG_TARGET_TRIPLET=arm64-linux -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=external -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=/ssd/vcpkg/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_TARGET_ARCHITECTURE=arm64 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/ssd/vcpkg/vcpkg/packages/openssl-unix_arm64-linux/debug
    Working Directory: /ssd/vcpkg/vcpkg/buildtrees/openssl-unix/arm64-linux-dbg
    Error code: 1
    See logs for more information:
      /ssd/vcpkg/vcpkg/buildtrees/openssl-unix/config-arm64-linux-dbg-out.log
      /ssd/vcpkg/vcpkg/buildtrees/openssl-unix/config-arm64-linux-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:304 (vcpkg_execute_required_process)
  ports/openssl-unix/portfile.cmake:41 (vcpkg_configure_cmake)
  scripts/ports.cmake:94 (include)

----------------------------------------------------------------------------------------------
**and the config-arm64-linux-dbg-out.log:**
-- The C compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Configuring incomplete, errors occurred!
See also "/ssd/vcpkg/vcpkg/buildtrees/openssl-unix/arm64-linux-dbg/CMakeFiles/CMakeOutput.log".

----------------------------------------------------------------------------------------------
the config-arm64-linux-dbg-err.log out:
CMAKE_C_COMPILER=/usr/bin/cc
COMPILER_ROOT=/usr/bin
CMAKE_SYSROOT=
CMAKE_OSX_SYSROOT=
CMAKE_C_FLAGS=-fPIC
CMAKE_C_FLAGS_RELEASE=-O3 -DNDEBUG
CMAKE_C_FLAGS_DEBUG=-g
CMAKE_INCLUDE_SYSTEM_FLAG_C=-isystem
ENV{ANDROID_DEV}=/usr
CMake Error at CMakeLists.txt:79 (file):
  file STRINGS file
  "/ssd/vcpkg/vcpkg/buildtrees/openssl-unix/arm64-linux-dbg/1.1.1d-b1f8ae3e6c/crypto/opensslv.h"
  cannot be read.


-----------------------------------------------------------------------------------------------
thanks very much!!!

**Comment by NancyLi1013** [comment]
Thanks for your detail.
Since this is about custom triplet, not all ports can compile successfully.
We might consider to support this triplet in the future but I'm not sure the specific time.

**Comment by xiejiulong** [comment]
@NancyLi1013 
thanks very much.
I have another problem:
When vcpkg install grpc lib, it must compiles the dependency lib named openssl-unix, I manual compile openssl by download the source code and make install at /usr/local/bin, How can I let vcpkg skip compile the openssl lib and compile grpc directly?
some lib I used can work ok only grpc/poco which dependency openssl-x
Is there anything you can do to help me? thank you very much!!

**Comment by NancyLi1013** [comment]
You can remove `openssl` from `Build-Depends` field in  [CONTROL](https://github.com/microsoft/vcpkg/blob/master/ports/grpc/CONTROL).
But I'm not sure if you can build it successfully without `openssl`.
Before doing this, you need to make sure that if `grpc `can find `openssl ` correctly on your local.

**Comment by xiejiulong** [comment]
@NancyLi1013 
ok, thanks very much. Let me have a try.

**Comment by NancyLi1013** [comment]
Please let me know if you have any other questions about this.

**Comment by NancyLi1013** [comment]
Personally, the origin issue has been solved now.
Please open a new issue if you have other problems.

Thanks.

**Comment by linquize** [comment]
`poco` can work without `openssl` (no patching needed), 
however, you have to edit poco's vcpkg `CONTROL` file to make `openssl` a separate feature.
