### ISSUE TITLE
[DirectXMesh] Port should support build for DirectX12

### ISSUE THREAD

**Issue by mgubisch** [microsoft/vcpkg#10723]
****

**Is your feature request related to a problem? Please describe.**
If i try to use DirectXMesh from vcpkg within a directx12 project i got link errors.
Inspection of Library symbols shows that the library is compiled for D3D11 (some functions have different headers for D3D12)

**Proposed solution**
Provide a Port for DirectXMesh building for DirectX12

**Describe alternatives you've considered**
I used NuGet so far, but i wan't to get rid of it in my project and migrate to vcpkg managee

**Comment by timautry** [comment]
According to the DirectXMesh documentation, to use Direct3D 12 with Visual Studio 2017/2019 on Windows 10, providing you have one of the Windows 10 SDK's installed (_Windows 8 SDK does not have the d3d12 files_) is to do the following:

**#include <d3d12.h>** // To use Direct3D 12 this header must be included before DirectXMesh.h
#include  "DirectXMesh.h"

- By default, the library supports Direct3D 11. If you want to support Direct3D 12, then you need to #include <d3d12.h> before you do #include "DirectXMesh.h".

Reference: https://github.com/microsoft/DirectXMesh/wiki/DirectXMesh paragraph on Headers.

**Comment by mgubisch** [comment]
Well i included <d3d12.h> beforce DirectXMesh.h
But the header isn't the problem
The lib which came out from the build executet by vcpkg install directxmesh:x64-windows just seem to use Windows 8 SDK (even I have the latest windows 10 SDK installed)

It looks to me that the port invokes the wrong solution 
It seems to build DirectXTex_Desktop_2019.sln where the corresponding vcxproj files define _WIN32_WINNT=0x0601 causing only to build against directx11

There is another file called DirectXTex_Desktop_2019_Win10.sln
The .vcxproj files in there define _WIN32_WINNT=0x0A00
With that Version the DirectX12 functions are available in the library and a can link against it.
But therefore i had to build manually, what i wanted to avoid using vcpkg...

**Comment by timautry** [comment]
Ah, that explains why it worked when I tested it, I do not have the Windows 8 SDK installed???
**Yes, I agree, it should be a feature added** to select whether you want to create the port with just  support for Direct3D 11 or if you have all the pre-requisites installed, support for both Direct3D 11 and Direct3D12 or maybe as I put it, **automagically** happen... 👍

**Comment by mgubisch** [comment]
I just tested the new port file and it works
Thanks a lot for your quick and great support

**Comment by timautry** [comment]
You are most welcome!
I just contribute like many others to this and other open source projects.
Have a wonderful week.

**Comment by LilyWangL** [comment]
@timautry Thanks for your help.

**Comment by timautry** [comment]
@LilyWangL you are welcome! 👍

**Comment by LilyWangL** [comment]
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.
