### ISSUE TITLE
Compiling against winpcap on a recent Visual Studio fails

### ISSUE THREAD

**Issue by traversaro** [microsoft/vcpkg#10730]
**Describe the bug**
Compiling a project that uses winpcap on a modern Visual Studio fails with the following error: 
~~~
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.24.28314\include\xkeycheck.h(266,1): warning C4005: 'inline': macro redefinition [C:\src\idjl-software\build\src\tools\idjl-egm2mat\idjl-egm2mat.vcxproj]
C:\idjl\vcpkg\installed\x64-windows\include\pcap-stdinc.h(69): message : see previous definition of 'inline' [C:\src\idjl-software\build\src\tools\idjl-egm2mat\idjl-egm2mat.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.24.28314\include\xkeycheck.h(268,1): fatal error C1189: #error:  The C++ Standard Library forbids macroizing the keyword "inline". Enable warning C4005 to find the forbidden define. [C:\src\idjl-software\build\src\tools\idjl-egm2mat\idjl-egm2mat.vcxproj]
~~~

A simple workaround is just to comment the line 69 (that contains the line `#define inline _inline`) from `vcpkg\installed\x64-windows\include\pcap-stdinc.h` .

**Environment**
- OS: Windows
- Compiler: Visual Studio v16.4.5

**To Reproduce**
1. ./vcpkg install winpcap
2. Compile a simple project that include `#include <pcap/pcap.h>` . 
3. See the compilation error aforementioned. 

**Expected behavior**
The compilation should work. 

**Failure logs** 
~~~
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.24.28314\include\xkeycheck.h(266,1): warning C4005: 'inline': macro redefinition [C:\src\idjl-software\build\src\tools\idjl-egm2mat\idjl-egm2mat.vcxproj]
C:\idjl\vcpkg\installed\x64-windows\include\pcap-stdinc.h(69): message : see previous definition of 'inline' [C:\src\idjl-software\build\src\tools\idjl-egm2mat\idjl-egm2mat.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.24.28314\include\xkeycheck.h(268,1): fatal error C1189: #error:  The C++ Standard Library forbids macroizing the keyword "inline". Enable warning C4005 to find the forbidden define. [C:\src\idjl-software\build\src\tools\idjl-egm2mat\idjl-egm2mat.vcxproj]
~~~

**Additional context**
I opened this issue for visibility for the problem, but apparently winpcap is completely unmaintained (see https://www.winpcap.org/), so I don't think continue to patch at the packaging level a non-maintained project is feasible. Instead, I discovered that now libpcap supports being compiled diretly on Windows, so I will submit a PR to enable the compilation of libpcap on Windows.

**Comment by traversaro** [comment]
A workaround for this issue is to install the `libpcap` port instead, once this PR https://github.com/microsoft/vcpkg/pull/10731 has been merged.

**Comment by PhoebeHui** [comment]
I think we should use libpcap instead in future, currently libpcap haven't support static build on windows.
