### ISSUE TITLE
Halide install puts some source code in tools directory

### ISSUE THREAD

**Issue by timautry** [microsoft/vcpkg#10732]
**Describe the bug**
vcpkg halide install puts additional source files in the directories/folders:
 - _vcpkg-root_/installed/x64-windows/tools 
 - _vcpkg-root_/installed/x64-windows/debug/tools 
 - files are as follows:
   - GenGen.cpp
   - halide_benchmark.h
   - halide_image.h
   - halide_image_info.h
   - halide_image_io.h
   - halide_malloc_trace.h
   - halide_trace_config.h
   - RunGen.h
   - RunGenMain.cpp

**Environment**
- OS: [Microsoft Windows [Version 10.0.18363.753]]
- Compiler: 
  - Visual Studio 2017 Version: 15.9.21  VS Tools Version: 14.16.27023
  - Visual Studio 2019 Version: 16.5.2  VS Tools Version: 14.25.28610
  - WinSDK 10.0.18362.0 
  - cmake version 3.17.0
  - git version 2.26.0.windows.1
  - Vcpkg package management program version 2020.02.04-nohash-external

**To Reproduce**
1. ./vcpkg install halide[core,opencl,opengl,utils]:x64-windows
2. No errors created

**Expected behavior**
I do not think these files should not be here:
 - either not at all left in buildtrees
 - or in another source directory/folder

**Failure logs** 
None

**Additional context**
None

**Comment by NancyLi1013** [comment]
Hi @timautry 
Thanks for posting this issue.
These files are installed by upstream source.
https://github.com/halide/Halide/blob/master/CMakeLists.txt#L461-L472.
why do you think these files should not be installed to tools folder?

**Comment by timautry** [comment]
- Creates confusion as to what port they belong
- vcpkg does not build nor use the "RunGen" tool which these headers/sources/scripts belong
- They should at least be grouped into a tools/halide sub-folder with the halide "RunGen" tool binary 
- No other tools built by other vcpkg ports have their headers/sources/scripts stored in the tools directory/folder except **boost-build** which has its own tools/boost-build sub-folder, and the boost-build tool **b2.exe** is built and used by vcpkg as vcpkg needs b2.exe to build the boost libraries
- Headers and source should not be stored in the same directory/folder designed for binaries
- Final thought: If vcpkg is not going to build the "RunGen" tool the files serve no purpose and should have the portfile run a patch against the CMakelists.txt as has been done in countless other ports to either:
  - eliminate copying these files into the root tools folder -or-
  - as a minimum put them in a tools/halide sub-folder -or-
  - build the RunGen tool and copy only the binary to the tools folder -or-
  - a combination of the above

- See the reference on the RunGen tool and its use: https://github.com/halide/Halide/blob/master/README_rungen.md

**Comment by NancyLi1013** [comment]
Thanks for your details and suggestions about this issue.
Since these files are not used in vcpkg, it might be better to remove these.
I will submitted a PR to handle this.

**Comment by timautry** [comment]
I close, no longer use product.
