### ISSUE TITLE
[fmt] update to 6.2

### ISSUE THREAD

**Issue by DailyShana** [microsoft/vcpkg#10741]
Library name: fmt

New version number: 6.2

Other information that may be useful (release notes, etc...)

**Comment by DailyShana** [comment]
hmm, I clicked "port update" when opening this issue but the label is "port feature" but not "port update".
seems there is an issue in issue template

**Comment by LilyWangL** [comment]
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.
