### ISSUE TITLE
freerdp port reports incorrect version

### ISSUE THREAD

**Issue by rossbrower** [Microsoft/vcpkg#1074]
Environment: windows 10
Port: freerdp:x86-windows         
Version: 2.0.0-beta1+android11

Expected:
If I check out the source from the release tag (tags/2.0.0-beta1+android11) I see the tag reflected in 
"C:\git\FreeRDP\include\freerdp\version.h" as `#define GIT_REVISION "2.0.0-beta1+android11"`

Actual
The value in "\vcpkg\installed\x86-windows\include\freerdp2\freerdp\version.h" is not the same. In my case it is `#define GIT_REVISION "90bb4a2"` which doesn't seem to correspond to anything.

**Comment by rossbrower** [comment]
@Mixaill Sorry to bug you... could you take a quick peek?

**Comment by Mixaill** [comment]
Please check #1076

**Comment by rossbrower** [comment]
@Mixaill Thanks!
