### ISSUE TITLE
protobuf-c code generation using protoc-gen-c is not working

### ISSUE THREAD

**Issue by victech-yeoinbo** [microsoft/vcpkg#10745]
I installed protobuf-c[tools] package in x64-linux env and build protoc-gen-c successfully.
But, when I try generate c code using protoc and plugin built failed.
FYI) If I built protobuf-c not using vcpkg, code generation works well.

**Environment**
- OS: ubuntu 18.04
- Compiler: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

**To Reproduce**
I made test.proto file like below 

```
syntax = "proto3";

message AfTestSmall
{
    int32 v0 = 1;
    int32 v1 = 2;
    int32 v2 = 3;
    int32 v3 = 4;
}
```

and install package and run protoc
```
./vcpkg install protobuf-c[tools]
./installed/x64-linux/tools/protobuf/protoc --c_out=. --plugin=/home/dev/vcpkg/installed/x64-linux/tools/protoc-gen-c test.proto
```

then fail with message below
```
terminate called after throwing an instance of 'std::system_error'
  what():  Unknown error -1
--c_out: protoc-gen-c: Plugin killed by signal 6.
```

**Comment by JackBoosY** [comment]
Confirmed.

**Comment by JackBoosY** [comment]
It looks like crashed at _protobuf/compiler/command_line_interface.cc_ line 2078:
```
  if (!subprocess.Communicate(request, &response, &communicate_error)) {
    *error = strings::Substitute("$0: $1", plugin_name, communicate_error);
    return false;
  }
```

**Comment by JackBoosY** [comment]
@ras0219-msft Could you please take a look?

Thanks.

**Comment by lipnitsk** [comment]
https://github.com/protobuf-c/protobuf-c/pull/425/commits/ce75229b6a2af6dcf701f94d981ad95a1952d8b6 should fix this. See https://github.com/protocolbuffers/protobuf/issues/5107, https://github.com/protocolbuffers/protobuf/issues/5140 for more info.
