### ISSUE TITLE
Virusscanner hits vcpkg while installing OpenSSL; Virustotal shows Malware infection

### ISSUE THREAD

**Issue by Maju-Ketchup** [microsoft/vcpkg#10742]
During the installation of OpenSSL on my machine, Kaspersky antivirus deletes the vcpkg.exe as Trojan and delets it. 
In addition Virus Total detects the compiled vcpkg.exe as Trojan with 4 diffrent scanners.
Ironically Microsofts own is among them.

**Environment**
Windows 10
- Compiler: 19.25.28612 for x64

**To Reproduce**

1. Install Kaspersky
2. ./vcpkg install OpenSSL

**Expected behavior**
Open SSL should be installed without being detected as Virus

**Additional context**
Company policy doesn't allow to disable and or add vcpkg to  the exception list.

**Comment by Neumann-A** [comment]
probably duplicate of #10668 and a false positive (or really an infected system this time?)

**Comment by Maju-Ketchup** [comment]
Oh overseen this Ticket, thanks.
