### ISSUE TITLE
[New Port Request] lexbor

### ISSUE THREAD

**Issue by smadurange** [microsoft/vcpkg#10740]
Library name: lexbor

Library description: Web browser engine

Source repository URL: https://github.com/lexbor/lexbor

Project homepage (if different from the source repository): https://lexbor.com/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
NA.

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
