### ISSUE TITLE
New port request: libmbus

### ISSUE THREAD

**Issue by xaelsouth** [microsoft/vcpkg#10747]
Library name: libmbus

Library description: libmbus is an open source library for the M-bus (Meter-Bus) protocol.

Source repository URL: https://github.com/rscada/libmbus

Here is the windows port of the libaray including MSVC-Project - https://github.com/xaelsouth/libmbus-winport

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
