### ISSUE TITLE
Can't load imgui and tinyobjloader with find_package in CMake on OSX

### ISSUE THREAD

**Issue by j20232** [microsoft/vcpkg#10748]
I have a question about package installation.

My environment is here:

```
OS: macOS Catalina 10.15.3
cmake: 3.13.2
clang: 11.0.3v
```

First, I installed imgui and tinyobjloader with following commands:

```bash
$ vcpkg install imgui
...
The package imgui:x64-osx provides CMake targets:

    find_package(imgui CONFIG REQUIRED)
    target_link_libraries(main PRIVATE imgui::imgui)


$ vcpkg install tinyobjloader
...
The package tinyobjloader:x64-osx provides CMake targets:

    find_package(tinyobjloader CONFIG REQUIRED)
    target_link_libraries(main PRIVATE tinyobjloader::tinyobjloader)
```

After that, the installation can be seen as follows:

```bash
$ vcpkg list | grep imgui
imgui:x64-osx                                      1.74             Bloat-free Immediate Mode Graphical User interfa...

$ vcpkg list | grep tinyobjloader
tinyobjloader:x64-osx                              2.0.0-rc2        Tiny but powerful single file wavefront obj loader
```

So, I tried to import imgui and tinyobjloader via `find_package` like follows:

```
cmake_minimum_required(VERSION 3.10)
project(sample)
if(DEFINED ENV{VCPKG_ROOT})
    set(CMAKE_TOOLCHAIN_FILE $ENV{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake CACHE STRING "")
endif()

find_package(imgui CONFIG REQUIRED)
find_package(tinyobjloader CONFIG REQUIRED)
```

These statements return the following errors:

imgui
```
Could not find a package configuration file provided by "imgui" with any of
  the following names:

    imguiConfig.cmake
    imgui-config.cmake

  Add the installation prefix of "imgui" to CMAKE_PREFIX_PATH or set
  "imgui_DIR" to a directory containing one of the above files.  If "imgui"
  provides a separate development package or SDK, be sure it has been
  installed.
```

tinyobjloader
```
Could not find a package configuration file provided by "tinyobjloader"
  with any of the following names:

    tinyobjloaderConfig.cmake
    tinyobjloader-config.cmake

  Add the installation prefix of "tinyobjloader" to CMAKE_PREFIX_PATH or set
  "tinyobjloader_DIR" to a directory containing one of the above files.  If
  "tinyobjloader" provides a separate development package or SDK, be sure it
  has been installed.
```

These errors look like same, but I cannot solve them.
In other packages, such as eigen3, glfw and so on, there are no problems.

Could you give me the solutions?

Best regards,

**Comment by tlemo** [comment]
Have you checked that the `VCPKG_ROOT` is set and points to the right location?

**Comment by PhoebeHui** [comment]
@j20232, have you tried the above solution? do this still be a problem for you?

**Comment by j20232** [comment]
@PhoebeHui 
No....
Finally, I give up to use vcpkg on OSX.

**Comment by PhoebeHui** [comment]
@j20232, thanks for your response. Since this is not be an issue for you, I would close this issue.

BTW, the doc https://github.com/microsoft/vcpkg/blob/master/docs/examples/installing-and-using-packages.md shows how to using a package that installed by vcpkg.

**Comment by disini** [comment]
Hey bro, I have the same problem on ubuntu 22.04, have you find some ways to fix that ? 

```
CMake Error at CMakeLists.txt:57 (find_package):
  Could not find a package configuration file provided by "imgui" with any of
  the following names:

    imguiConfig.cmake
    imgui-config.cmake

  Add the installation prefix of "imgui" to CMAKE_PREFIX_PATH or set
  "imgui_DIR" to a directory containing one of the above files.  If "imgui"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
```

I searched everywhere on imgui source folder but there's no any .cmake files at all~~

**Comment by cyborgdennett** [comment]
> Hey bro, I have the same problem on ubuntu 22.04, have you find some ways to fix that ?
> 
> ```
> CMake Error at CMakeLists.txt:57 (find_package):
>   Could not find a package configuration file provided by "imgui" with any of
>   the following names:
> 
>     imguiConfig.cmake
>     imgui-config.cmake
> 
>   Add the installation prefix of "imgui" to CMAKE_PREFIX_PATH or set
>   "imgui_DIR" to a directory containing one of the above files.  If "imgui"
>   provides a separate development package or SDK, be sure it has been
>   installed.
> 
> 
> -- Configuring incomplete, errors occurred!
> ```
> 
> I searched everywhere on imgui source folder but there's no any .cmake files at all~~

I have the same error as you. Did you manage to figure it out? all the other dependencies work good.

**Comment by CharlosNels** [comment]
I have the same problem too.

**Comment by sfhacker** [comment]
This issue is from .... 2020! God save us all!
