### ISSUE TITLE
Capstone build failure

### ISSUE THREAD

**Issue by illera88** [microsoft/vcpkg#10752]
**Host Environment**
- OS: Windows

**To Reproduce**
- vcpkg.exe install capstone --triplet x64-windows
- Using capstone in my CMakeLists.txt with:
```
find_package(Capstone REQUIRED)
```
```
find_package(PkgConfig REQUIRED)
pkg_check_modules (CAPSTONE REQUIRED capstone)
```
None of the two seems to find capstone. I can other vcpkg ports with no problem.

**Comment by illera88** [comment]
@Rastaban I think you were the one doing the port. Do you have any problem using it?

Thanks in advance

**Comment by JackBoosY** [comment]
@illera88 You can use the following codes:
```
find_library(Capstone capstone_dll REQUIRED)
find_path(Capstone_INCLUDE_DIR capstone.h PATH_SUFFIXES capstone)
set(${Capstone_INCLUDE_DIR} ${Capstone_INCLUDE_DIR}../)

target_link_libraries(main PRIVATE Capstone)
target_include_directories(main PRIVATE ${Capstone_INCLUDE_DIR})

```

**Comment by illera88** [comment]
What is the reason that capstone for Windows needs to be imported:
`#include <capstone.h>`
but for Linux and OSX:
`#include <capstone/capstone.h>`

That's why 
`set(Capstone_INCLUDE_DIR ${Capstone_INCLUDE_DIR}/../)`

needs to be added right?

**Comment by JackBoosY** [comment]
@illera88 In order to deal with the issue of header file conflicts with other ports, the capstone header file is installed in _include/capstone_.
