### ISSUE TITLE
How to let my library(here I call it `mylib`) find anther binary library when do `./vcpkg install mylib`

### ISSUE THREAD

**Issue by daydream123** [microsoft/vcpkg#10765]
I'm developing a library with cmake, it depends a third library, the third library only has header files and so files, I created a port for it and also wrote a FindXXX.cmake to let my library find_package(thirdlib) with it. I'm lucky it works well, my library can build out so files and run(an example inside). so I also created a port for my library, but when I do "./vcpkg install mylib" it failed, the error message was "cannot find FindXXX.cmake(I created for that third library)".

--------------------------------------------------------------------------------------------------------
My question is how to let mylib find thirdlib's FindXXX.cmake automatically?
in fact, my lib also depends anther lib developed by me in vcpkg, and it can find_package() with CONFIG mode.

**Comment by Neumann-A** [comment]
you need to install your `FindXXX.cmake` and modify the `CMAKE_MODULE_PATH` in your `mylibconfig.cmake` to find that `FindXXX.cmake` module. Don't forget to restore the `CMAKE_MODULE_PATH` at the end of your `mylibconfig.cmake`

**Comment by daydream123** [comment]
> you need to install your `FindXXX.cmake` and modify the `CMAKE_MODULE_PATH` in your `mylibconfig.cmake` to find that `FindXXX.cmake` module. Don't forget to restore the `CMAKE_MODULE_PATH` at the end of your `mylibconfig.cmake`

ok, I will try it, thanks for your reply.

**Comment by daydream123** [comment]
haha, I fixed this problem, I don't known how to change mylibconfig.cmake, but if I copy FindXXX.cmake inside my library project and append that dir into CMAKE_MODULE_PATH, it works!
