### ISSUE TITLE
[Freetype] system harfbuzz linked in

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#10762]
**Describe the bug**
If Freetype is build on a system which has harfbuzz installed it will automatically pick up that dependency

**Solution**
add `-DCMAKE_DISABLE_FIND_PACKAGE_HarfBuzz=TRUE` to `vcpkg_configure_cmake `in the freetype portfile.

**Comment by timautry** [comment]
FYI Not sure if adding this will cause the issue mention in **_freetype and harfbuzz - cycle detected with graph at freetype:x64-windows #9850_** but it would be something to keep in mind?

**Comment by Neumann-A** [comment]
As long has you don't add harfbuzz as a build dependency for freetype everything is find. The Idea is to completely disable the harfbuzz detection in freetype since it is only a development option for freetype itself. From the changelogs it seems like harfbuzz should be separated into two libraries so building harfbuzz with freetype is the correct choice (and not the other way around).

**Comment by Neumann-A** [comment]
already closed by #10073 seems like the branch i am currently working on is not up to date
