### ISSUE TITLE
[berkeleydb:x64-windows-static] build failure

### ISSUE THREAD

**Issue by coopci** [microsoft/vcpkg#10775]
**Host Environment**
- OS: Windows 7
- Compiler:  cl Microsoft (R) C/C++ Optimizing Compiler Version 19.10.25019 for x64

**To Reproduce**
`vcpkg install --triplet x64-windows-static berkeleydb`

**Failure logs** 
Error: Building package berkeleydb:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: berkeleydb:x64-windows-static
  Vcpkg version: 2020.02.04-nohash

Additionally, attach any relevant sections from the log files above.

**Additional context**
In config-x64-windows-static-out.log:
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_C_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.

CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.

I have run vcpkg intgrate install
```
E:\src\vcpkg>vcpkg integrate install
Applied user-wide integration for this vcpkg root.

All MSBuild C++ projects can now #include any installed libraries.
Linking will be handled automatically.
Installing new libraries will make them instantly available.

CMake projects should use: "-DCMAKE_TOOLCHAIN_FILE=E:/src/vcpkg/scripts/buildsys
tems/vcpkg.cmake"
```
I have set CC and CXX to cl, and cl is in PATH:
```
E:\src\vcpkg>printenv CC
cl

E:\src\vcpkg>printenv CXX
cl

E:\src\vcpkg>cl
Microsoft (R) C/C++ Optimizing Compiler Version 19.10.25019 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

usage: cl [ option... ] filename... [ /link linkoption... ]
```

**Comment by linquize** [comment]
No problem for me. No need to set `%CC%` or `%CXX%`

**Comment by coopci** [comment]
It doesn't work neither setting nor not setting %CC% or %CXX%. Is this thing really usable ?

**Comment by linquize** [comment]
Did you select MSVC features in Visual Studio Installer?

**Comment by coopci** [comment]
> 
> 
> Did you select MSVC features in Visual Studio Installer?

I dont' remember, how to check and reset?

**Comment by coopci** [comment]
I can new ATL, MFC, WIN32 project in visual studio IDE, does that mean I selected MSVC features?

**Comment by coopci** [comment]
If I use the cmake installed by vcpkg to build a hello word, however, it seems to work:
```
E:\src\hello>cmake .
-- Building for: Visual Studio 15 2017
-- The C compiler identification is MSVC 19.10.25019.0   <=== Seems It could identify the C compiler
-- The CXX compiler identification is MSVC 19.10.25019.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/
2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX86/x86/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/
2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX86/x86/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studi
o/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX86/x86/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studi
o/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX86/x86/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: E:/src/hello

E:\src\hello>ls
ALL_BUILD.vcxproj          CMakeLists.txt            ZERO_CHECK.vcxproj
ALL_BUILD.vcxproj.filters  Tutorial.sln              ZERO_CHECK.vcxproj.filters
CMakeCache.txt             Tutorial.vcxproj          cmake_install.cmake
CMakeFiles                 Tutorial.vcxproj.filters  hello.c
```

**Comment by coopci** [comment]
If I goto the berkeleydb source folder and run `cmake .` it also could find C compiler.
```
E:\src\vcpkg\buildtrees\berkeleydb\src\db-4-c2cacfc4e9>cmake .
-- Building for: Visual Studio 15 2017
-- The C compiler identification is MSVC 19.10.25019.0
-- The CXX compiler identification is MSVC 19.10.25019.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/
2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX86/x86/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/
2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX86/x86/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studi
o/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX86/x86/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studi
o/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX86/x86/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: E:/src/vcpkg/buildtrees/berkeleydb/src/db-4
-c2cacfc4e9
```

**Comment by Voskrese** [comment]
E:\src\vcpkg\buildtrees\berkeleydb\src\db-4-c2cacfc4e9>`cmake . -G"Visual Studio 15 2017" -Ax64`
?

**Comment by Cheney-W** [comment]
I can install berkeleydb:x64-windows-static successfully with VS2017 15.9.21 and latest VCPKG. What's the version of your VS?

**Comment by Cheney-W** [comment]
@coopci  Could you please run `.\vcpkg.exe install berkeleydb:x64-windows-static --debug` and provide the log to us?

**Comment by Cheney-W** [comment]
@coopci Has this issue resolved?

**Comment by Cheney-W** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen
