### ISSUE TITLE
[New Port Request] flecs

### ISSUE THREAD

**Issue by paulherman** [microsoft/vcpkg#10774]
Library name: flecs

Library description: A Multithreaded Entity Component System for C89/99 and C++11

Source repository URL: https://github.com/SanderMertens/flecs

Project homepage (if different from the source repository): same

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
