### ISSUE TITLE
[GRPC] fails to create cmake config

### ISSUE THREAD

**Issue by HiceS** [microsoft/vcpkg#10773]
**Describe the bug**

After running the following commands the cmake [package]-config.cmake files are all created but the grpc-config.cmake and gRPCConfig.cmake fail to be created.

After finished all of the dependencies generate correct and complete config file however the grpc port does not contain this which does not align with the information provided in the instructions for linking the port.
 
**Environment**
- OS: Windows 10

**To Reproduce**
1. `  git clone https://github.com/Microsoft/vcpkg.git `
2. ` cd vcpkg `
3. `  .\bootstrap-vcpkg.bat `
4. `  .\vcpkg integrate install ` while in a admin terminal
5. ` .\vcpkg install grpc ` or ` .\vcpkg install:grpc:x64-windows `

**Expected behavior**
I expect to see a ` grpc-config.cmake ` file in order to use the ` findpackage ` functionality while vcpkg is included in the ` CMAKE_TOOLCHAIN_FILE`.

    find_package(gRPC CONFIG REQUIRED)
    message(STATUS "Using gRPC ${gRPC_VERSION}")

**Failure logs** 
No direct failure but to verify I did do a full system search and no such file was built on my machine no matter where I try to download vcpkg.

No failures happen during build and it's evident the full build gets completed and the following message is prompted.

```
PS C:\vcpkg> .\vcpkg.exe install grpc:x64-windows
Computing installation plan...
The following packages are already installed:
    grpc[core]:x64-windows
Package grpc:x64-windows is already installed

Total elapsed time: 129.4 us

The package grpc:x64-windows provides CMake targets:

    find_package(gRPC CONFIG REQUIRED)
    # Note: 8 target(s) were omitted.
    target_link_libraries(main PRIVATE gRPC::gpr gRPC::grpc gRPC::grpc++ gRPC::grpc++_alts)

    find_package(modules CONFIG REQUIRED)
    target_link_libraries(main PRIVATE c-ares::cares)
```

**Additional context**
This file at some point existed on my previous build machine but is no longer built on this machine. I however am very new to this so it's entirely possibly I'm doing this incorrectly.

**Comment by HiceS** [comment]
Seems like this was an issue in the following issue in the GRPC repo:

https://github.com/grpc/grpc/issues/11378

**Comment by HiceS** [comment]
https://github.com/grpc/grpc/pull/12469

This should have been fixed in the following PR, however it doesn't seem that it is correct.

**Comment by LilyWangL** [comment]
Thanks for posting this issue. After installing grpc successfully, the VCPKG will create files as below, it include the file gRPCConfig.cmake.
![image](https://user-images.githubusercontent.com/47812810/80577438-7477d200-8a39-11ea-90c2-4e7943fece36.png)

**Comment by HiceS** [comment]
Yeah that's interesting on my machine that's not showing up in that local folder relative to vcpkg or anywhere using the search anything utility.

I've moved on to cloning it locally and automating a build with cmake.

I can try to provide more info soon.

**Comment by LilyWangL** [comment]
Hi @HiceS, does this issue still occur?

**Comment by HiceS** [comment]
@LilyWangL I just re-cloned and installed the latest GRPC and it seems to now create the required files. Maybe it was my local machine but now they get built correctly thank you. I can close this or you can if you feel it's satisfied.

**Comment by LilyWangL** [comment]
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.
