### ISSUE TITLE
[FFMPEG] build failure (x86/x64 windows-static with OpenSSL)

### ISSUE THREAD

**Issue by gizmocuz** [microsoft/vcpkg#10772]
**Host Environment**
- OS: Windows
- Compiler: VS2019 (16.5.3)

**To Reproduce**
`vcpkg install --triplet x64-windows-static --recursive ffmpeg[ffmpeg,ffplay,ffprobe,openssl,lzma,bzip2,x264,nonfree,gpl,version3,avresample,nvcodec]`

rel-out.log contains:

> === CONFIGURING ===
> ERROR: openssl not found
> 
> If you think configure made a mistake, make sure you are using the latest
> version from Git.  If the latest version fails, report the problem to the
> ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
> Include the log file "ffbuild/config.log" produced by configure as this will help
> solve the problem. 

Both x86 and x64 have this issue, non-static seems fine

**Comment by NancyLi1013** [comment]
Hi @gizmocuz 
Thanks for posting this issue.
It's duplicated to  #8631. 
We have already submitted the PR #8797 to fix this issue.
