### ISSUE TITLE
How do I use vcpkg as en external in an existing repo

### ISSUE THREAD

**Issue by clumbo** [microsoft/vcpkg#10783]
I have heard it is best practice to use vcpkg as an external in your project folder, I use pitchfork structure but not sure if this is possible and how do you integrate it?

**Comment by linquize** [comment]
You can use vcpkg as a git submodule

**Comment by codingcolumbo** [comment]
Thanks, could you point me to some documentation of how to do this, while using cmake?

**Comment by JackBoosY** [comment]
For using a self-built CI system, you only need to add `clone vcpkg`, `build vcpkg`, and `vcpkg integrate` steps in the CI build step.
For integration into a custom project, it is generally not necessary to add the vcpkg source code to the project, but set the vcpkg path to an environment variable or other configuration field, and then use this field in the project to find the required port.

Can you describe it in more detail?

**Comment by JackBoosY** [comment]
Hi @codingcolumbo, does this issue still bother you?

**Comment by clumbo** [comment]
no thats great thankyou
