### ISSUE TITLE
[mpg123::x64-windows-static] build failure

### ISSUE THREAD

**Issue by SkuliAdams** [microsoft/vcpkg#10788]
**Host Environment**
- OS: Windows 10
- Compiler: MSVC v142 - VS 2019 C++ x64/x89 build tools (v14.25)
(Visual studio 2019)

**To Reproduce**
The failure occurs with this command:
`./vcpkg --triplet x64-windows-static install sdl2 sdl2-image sdl2-mixer[dynamic-load,libflac,mpg123,libmodplug,libvorbis] sdl2-ttf gettext`

**Failure logs** 

Starting package 1/2: mpg123:x64-windows-static
Building package mpg123[core]:x64-windows-static...
-- Using cached C:/Program Files/Git/vcpkg/downloads/mpg123-1.25.8.tar.bz2
-- Using source at C:/Program Files/Git/vcpkg/buildtrees/mpg123/src/mpg123-1-9840211cc0
-- Building C:/Program Files/Git/vcpkg/buildtrees/mpg123/src/mpg123-1-9840211cc0/ports/MSVC++/2015/win32/libmpg123/libmpg123.vcxproj for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: msbuild "C:/Program Files/Git/vcpkg/buildtrees/mpg123/src/mpg123-1-9840211cc0/ports/MSVC++/2015/win32/libmpg123/libmpg123.vcxproj" /p:Configuration=Release_x86 /t:Rebuild /p:Platform=x64 /p:PlatformToolset=v142 /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /p:WindowsTargetPlatformVersion=10.0.18362.0 /m /p:WholeProgramOptimization=false
    Working Directory: C:/Program Files/Git/vcpkg/buildtrees/mpg123/x64-windows-static-rel
    Error code: 1
    See logs for more information:
      C:\Program Files\Git\vcpkg\buildtrees\mpg123\build-x64-windows-static-rel-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_msbuild.cmake:119 (vcpkg_execute_required_process)
  ports/mpg123/portfile.cmake:48 (vcpkg_build_msbuild)
  scripts/ports.cmake:90 (include)

Error: Building package mpg123:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: mpg123:x64-windows-static
  Vcpkg version: 2020.02.04-nohash-external

Here is the referenced log:
[build-x64-windows-static-rel-out.log](https://github.com/microsoft/vcpkg/files/4465473/build-x64-windows-static-rel-out.log)
**Additional context**
As the log recommended, I performed another git pull and `./vcpkg update`, and it is up to date.

**Comment by timautry** [comment]
See issue **_vcpkg unable to find yasm.exe #10523_**

**Comment by NancyLi1013** [comment]
Hi @SkuliAdams 
Thanks for posting this issue.
Duplicated to #10523. Let's track this issue there.
@timautry 
Thanks for your info.
