### ISSUE TITLE
vcpkg broke Visual Studio

### ISSUE THREAD

**Issue by Niadb** [microsoft/vcpkg#10785]
I only installed vcpkg to download some library that dependent on it, and don't have any use for vcpkg in my own work..

But somehow it integrated itself into Visual Studio 2019(C++), and started breaking my builds that didn't even use it. Spitting out shit loads of error msgs about needing to use "Release" or "Debug"(I have a custom name for my Solution Config), and causing projects to build endlessly(ever time I run it would think it needs to build all over again--not the case without vcpkg).

Anyway I removed vcpkg, and the problem went away, and don't plan to use it again, but just thought you should be aware of this issue.

**Comment by linquize** [comment]
Delete `C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\ImportBefore\Default\vcpkg.system.props` to remove integration.
You don't need to remove vcpkg.

**Comment by timautry** [comment]
@Niadb try this:
- **.\vcpkg.exe integrate remove** (to removes system wide integration with visual studio)
- **.\vcpkg.exe integrate project** (to create a nupkg to be included in projects where you need to use vcpkg port libraries) - there will be a message from this command telling you how to include vcpkg libraries into individual projects - screen print or save this info to a file and use when needed.

**Comment by linquize** [comment]
`vcpkg integrate remove` does not perform **clean** remove because `C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\ImportBefore\Default\vcpkg.system.props` is not deleted.

**Comment by timautry** [comment]
@linquize but it does remove the %LOCALAPPDATA%\vcpkg\vcpkg.path.txt and %LOCALAPPDATA%\vcpkg\vcpkg.user.targets files, which does make the **if** condition in the file C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\v140\ImportBefore\Default\vcpkg.system.props **false** for the user removing the integrated install. 
Your method makes it an absolute, either all users have it integrated or all users do not, and when you have developers sharing the same machine on different shifts, one may desire it integrated where the other does not.

**Comment by PhoebeHui** [comment]
I think '.\vcpkg.exe integrate remove' is fine, and personally, should be careful to modify/remove files under MSBuild folder.

**Comment by PhoebeHui** [comment]
@Niadb, thanks for reporting this issue!

BTW, we recently published a [product roadmap](https://github.com/microsoft/vcpkg/wiki/Roadmap) in our wiki. You can read the original announcement in our [blog post](https://devblogs.microsoft.com/cppblog/vcpkg-2020-04-update-and-product-roadmap/). we plan to shipped with visual studio and VS code in future, If you like to share the repro steps or example about this issue, that would be great.
