### ISSUE TITLE
[libyaml] build failure

### ISSUE THREAD

**Issue by AlexAltea** [microsoft/vcpkg#10789]
**Host Environment**
- OS: Linux
- Compiler: GCC 9.2.0

**To Reproduce**
Steps to reproduce the behavior: `./vcpkg install libyaml` and try build any example from the official repository, e.g. https://github.com/yaml/libyaml/blob/master/tests/run-parser.c.

**Failure logs** 
```
/usr/bin/ld: /vcpkg/installed/x64-linux/debug/lib/libOFF.a(api.c.o): in function `yaml_strdup':
/vcpkg/buildtrees/libyaml/src/0.2.2-2fff7d3dcb/src/api.c:66: undefined reference to `_strdup'
```

**Additional context**

The issue seems to be caused by the patch [fix-POSIX_name.patch](https://github.com/microsoft/vcpkg/blob/master/ports/libyaml/fix-POSIX_name.patch) that replaces POSIX's `strdup` with MSVC's `_strdup`.

This patch is applied unconditionally in the [portfile.cmake](https://github.com/microsoft/vcpkg/blob/master/ports/libyaml/portfile.cmake), but it should **only** be applied under Windows+MSVC and not under Linux/OSX+GCC/Clang. I'm not sure how to update the port file to reflect these necessary changes.

**Comment by LilyWangL** [comment]
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.
