### ISSUE TITLE
Ports should indicate (in their CONTROL file?) if they support static linkage

### ISSUE THREAD

**Issue by jumpinjackie** [microsoft/vcpkg#1079]
It would make `vcpkg search` results more informative.

Also, it has potential CI value as a way to programmatically determine what linkage modes to test a given port under.

**Comment by ras0219-msft** [comment]
Related to #229.

**Comment by LilyWangL** [comment]
Thanks for posting this issue. This issue has been fixed. The [Supports](https://github.com/microsoft/vcpkg/blob/e62d1361288e83eba786395b60361ab35ba83800/docs/maintainers/control-files.md#supports) has been added to CONTROL. So I am closing this issue for now.
