### ISSUE TITLE
grpc in windows 10 with x64-windows-static build program has some error

### ISSUE THREAD

**Issue by codinggg** [microsoft/vcpkg#10798]
Hi. I am tring use grpc in windows10.  I use vcpkg to build x64-windows-static version, it is build ok with no problem.
But when I use grpc in my code with runtime library with MT pattern has some build error

> runtimelibrary' value 'md_dynamicrelease' doesn't match value 'mt_staticrelease'

![1](https://user-images.githubusercontent.com/7337719/79063998-cbf70d80-7cd7-11ea-9a3d-df4daf47d52a.jpg)

so I convert runtime library to MD pattern, it show other library error

> runtimelibrary' value 'mt_staticrelease' doesn't match value 'md_dynamicrelease'

![2](https://user-images.githubusercontent.com/7337719/79064062-30b26800-7cd8-11ea-909c-99b0754a5968.jpg)

It's look like x64-windows-static version has some library like absl*.lib is build with MD pattern. Additionally I am try build x64-windows version and it is ok.
It's a bug? How to fix that problem ?

**Comment by NancyLi1013** [comment]
Hi @codinggg 
Thanks for posting this issue.
It seems that both `grpc `and `abseil` only support static library on Windows.
https://github.com/microsoft/vcpkg/blob/master/ports/grpc/portfile.cmake#L1-L3
https://github.com/microsoft/vcpkg/blob/master/ports/abseil/portfile.cmake#L1
So we might use `/MT `to build this.

BTW, could you please help provide your project case?

**Comment by codinggg** [comment]
I am very happy to do that ;)
I upload my vs project to github [https://github.com/codinggg/grpc-server](url)

**Comment by codinggg** [comment]
Today I notice that grpc project has update, and after I upgrade static grpc library, my project compile succcessfully! This problem probably solved.
