### ISSUE TITLE
[nlohmann-json] Support multiple header install

### ISSUE THREAD

**Issue by kevinlul** [microsoft/vcpkg#10795]
****

**Is your feature request related to a problem? Please describe.**
When using JSON for Modern C++ (nlohmann-json), there are cases when a developer would rather forward-declare (say, in a header) rather than include the entire `json.hpp`. The vcpkg port currently just downloads the single-include header and does not provide other options.

**Proposed solution**
According to [upstream documentation](https://github.com/nlohmann/json#integration)
```
You can further use file include/nlohmann/json_fwd.hpp for forward-declarations. The installation of json_fwd.hpp (as part of cmake's install step), can be achieved by setting -DJSON_MultipleHeaders=ON.
```
so by cloning and building via CMake, vcpkg can provide both the core and multiheader features.

I'd like to try and do this. I assume it involves replacing the nlohmann-json portfile with a more standard CMake library portfile?

**Comment by JackBoosY** [comment]
We can export other cmake files with different names and keep the existing cmake files.

**Comment by kevinlul** [comment]
We don't have a custom CMake configuration for nlohmann-json. It's just a portfile that downloads the single include, pretty much.

https://github.com/microsoft/vcpkg/tree/master/ports/nlohmann-json

**Comment by JackBoosY** [comment]
@kevinlul I mean [alias](https://cmake.org/cmake/help/v3.10/command/add_library.html#alias-libraries).
