### ISSUE TITLE
[libgit2] update to 1.0.0

### ISSUE THREAD

**Issue by kevinlul** [microsoft/vcpkg#10794]
Library name: libgit2

New version number: 1.0.0

Other information that may be useful (release notes, etc...) https://github.com/libgit2/libgit2/releases/tag/v1.0.0

This strictly supersedes 0.99.0. I might do this if I get the time.

**Comment by LilyWangL** [comment]
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.
