### ISSUE TITLE
[sdl2-mixer:x64-uwp] build failure

### ISSUE THREAD

**Issue by jonasjuni** [microsoft/vcpkg#10805]
**Host Environment**
- OS: Microsoft Windows 10 Pro 1909

- Compiler:  MSVC 19.26.28720.3

**To Reproduce**
`PS C:\vcpkg> .\vcpkg install sdl2-mixer:x64-uwp`

**Failure logs** 
PS C:\vcpkg> .\vcpkg install `sdl2-mixer:x64-uwp`
Computing installation plan...
The following packages will be built and installed:
    sdl2-mixer[core]:x64-uwp
Starting package 1/1: sdl2-mixer:x64-uwp
Building package sdl2-mixer[core]:x64-uwp...
-- Using cached C:/vcpkg/downloads/SDL2_mixer-2.0.4.zip
-- Using source at C:/vcpkg/buildtrees/sdl2-mixer/src/2.0.4-a895b09396
-- Configuring x64-uwp
-- Building x64-uwp-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: C:/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe --build
 . --config Debug --target install -- /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /m
    Working Directory: C:/vcpkg/buildtrees/sdl2-mixer/x64-uwp-dbg
    See logs for more information:
      C:\vcpkg\buildtrees\sdl2-mixer\install-x64-uwp-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/sdl2-mixer/portfile.cmake:49 (vcpkg_install_cmake)
  scripts/ports.cmake:90 (include)

Error: Building package sdl2-mixer:x64-uwp failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: sdl2-mixer:x64-uwp
  Vcpkg version: 2020.02.04-nohash

Additionally, attach any relevant sections from the log files above.

4>music.obj : error LNK2019: unresolved external symbol native_midi_detect referenced in function open_music_type [C:\vcpkg\buildtrees\sdl2-mixer\x64-uwp-dbg\SDL2_mixer.vcxproj]

**Additional context**
I'm really noob, I may missing a lib in my environment, but I didn't have any problem building sdl2-mixer:x64-windows port...
 sorry for disturbing you guys!

**Comment by jonasjuni** [comment]
[install-x64-uwp-dbg-out.log](https://github.com/microsoft/vcpkg/files/4470266/install-x64-uwp-dbg-out.log)

**Comment by leo60228** [comment]
The same issue happens on x64-windows with libvorbis.

**Comment by jonasjuni** [comment]
Good news, 
Last update

**Comment by Zopolis4** [comment]
Any updates on this? I'm having the same issue as well.
