### ISSUE TITLE
Could not find a package configuration file provided by "nlohmann-fifo-map"

### ISSUE THREAD

**Issue by ujos** [microsoft/vcpkg#10809]
**Describe the bug**
I cannot generate a solution that depends on "nlohmann-fifo-map" package. `find_package(nlohmann-fifo-map REQUIRED)` returns following error

```
CMake Error at C:/Users/dmytro_ovdiienko/source/vcpkg/scripts/buildsystems/vcpkg.cmake:286 (_find_package):
  Could not find a package configuration file provided by "nlohmann-fifo-map"
  with any of the following names:

    nlohmann-fifo-mapConfig.cmake
    nlohmann-fifo-map-config.cmake

  Add the installation prefix of "nlohmann-fifo-map" to CMAKE_PREFIX_PATH or
  set "nlohmann-fifo-map_DIR" to a directory containing one of the above
  files.  If "nlohmann-fifo-map" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:8 (find_package)
```

**Environment**
- OS: Windows 10
- Compiler: VS 2017
- CMake: 3.12.4

**To Reproduce**
1. Install package
```./vcpkg install nlohmann-fifo-map```
2. Extract attached archive
   [VcpkgTest.zip](https://github.com/microsoft/vcpkg/files/4468574/VcpkgTest.zip)
3. Switch to the `VcpkgTest` folder
4. Create `build` folder
5. Run following command to generate solution file
```
cmake -DCMAKE_TOOLCHAIN_FILE=%VCPKG_ROOT%/scripts/buildsystems/vcpkg.cmake ..
```

**Expected behavior**
Solution is generated

**Failure logs** 
```
CMake Error at C:/Users/dmytro_ovdiienko/source/vcpkg/scripts/buildsystems/vcpkg.cmake:286 (_find_package):
  Could not find a package configuration file provided by "nlohmann-fifo-map"
  with any of the following names:

    nlohmann-fifo-mapConfig.cmake
    nlohmann-fifo-map-config.cmake

  Add the installation prefix of "nlohmann-fifo-map" to CMAKE_PREFIX_PATH or
  set "nlohmann-fifo-map_DIR" to a directory containing one of the above
  files.  If "nlohmann-fifo-map" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:8 (find_package)
```

**Comment by Neumann-A** [comment]
`find_package(nlohmann-fifo-map REQUIRED)`

requires that nlohmann/fifo_map actually exports a CMake target which it does not. The official target (following nlohman/json) would probably be `nlohmann_fifo_map` if it would exists.

So your best bet to find it is using `find_file` for `fifo_map.hpp`

Also this is an upstream usage issue not a vcpkg issue. People need to lern that the proper CMake way for all dependencies is to export their targets. Even when its only an interface target for a header only library.

**Comment by ujos** [comment]
> requires that nlohmann/fifo_map actually exports a CMake target which it does not

@Neumann-A Following is a tail of the `vcpkg install nlohmann-fifo-map` output.

```
The package nlohmann-fifo-map:x86-windows provides CMake targets:

    find_package(nlohmann-fifo-map CONFIG REQUIRED)
    target_link_libraries(main PRIVATE nlohmann_fifo_map::nlohmann_fifo_map)
```

I assume `nlohmann/fifo_map` exports CMake target, no?

**Comment by Neumann-A** [comment]
Ah I see somebody decided to completly replace the original CMakeLists.txt within vcpkg and make the generated target unuseable. 
Rename `<vcpkgroot>/installed/<triplet>/share/nlohmann-fifo-map` to `<vcpkgroot>/installed/<triplet>/share/nlohmann_fifo_map` 
and use `find_package(nlohmann_fifo_map CONFIG REQUIRED)`

**Comment by Neumann-A** [comment]
You also need to rename `nlohmann_fifo_map_config.cmake` to `nlohmann_fifo_map-config.cmake` if you do the above. Alternativly you can rename `nlohmann_fifo_map_config.cmake` to `nlohmann-fifo-map-config.cmake` withouth renaming the folder above. Feel free to open up a PR with these changes.

**Comment by LilyWangL** [comment]
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.
