### ISSUE TITLE
[nlohmann-json] vcpkg package name and CMake package name consistency

### ISSUE THREAD

**Issue by ujos** [microsoft/vcpkg#10818]
There is vcpkg package `nlohmann-json`. The corresponding CMake package name is `nlohmann_json`. Please pay attention on the difference between those two names (underscore vs minus) 

The problem is when `nlohmann-json` package is not installed, then during project generation CMake reports 

```
  Could not find a package configuration file provided by "nlohmann_json"
  with any of the following names:
```

User may not know the package name so to solve this issue he/she will copy package name and call

```
vcpkg install nlohmann_json
```

This command will fail because there is no package `nlohmann_json`.

**Proposed solution**
To solve this issue and improve developer's experience I believe CMake package name should be equal to vcpkg package name. i.e. in this case both CMake and vcpkg packages should have same name `nlohmann-json`

**Alternatives**
As an alternative CMake can report both vcpkg name and CMake package name and make error message more user friendly

```
  Could not find a package configuration file provided by "nlohmann_json"
  with any of the following names:
...
  To install package run:
    vcpkg install nlohmann-json:<triplet>
```

Another and even better option is to download and install prerequisites automatically. Probably there is some parameter I'm not aware of, so it could happen that it is already implemented.

**Comment by LilyWangL** [comment]
@ujos Thanks for posting this issue. `find_package(nlohmann_json 3.2.0 REQUIRED)` is official code, and it shouldn't be break. And many ports depend on nlohmann-json, if I modify `find_package(nlohmann_json 3.2.0 REQUIRED)`, they will build failed.

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Please open a new issue if this is still a problem for you.
