### ISSUE TITLE
vcpkg install manual mode

### ISSUE THREAD

**Issue by linquize** [microsoft/vcpkg#10810]
Feature suggestion: vcpkg install manual mode
`vcpkg install --manual <package>`

In `vcpkg_extract_source_archive_ex.cmake`,
between `vcpkg_extract_source_archive()` and `vcpkg_apply_patches()`,
If in manual mode,
(1st wait) wait for maintainer to continue, by polling to check existence of a file. e.g. `cmake -E sleep 5`
During this period, maintainer can inspect and edit some files in `buildtrees/<port>` directory.
Optionally, manual / auto perform `git init`, `git add`, `git commit` in `${TEMP_SOURCE_PATH}`
When maintainer finishes editing, he should create a wait file, so that the cmake script continues.

After `vcpkg_apply_patches()`,
If in manual mode,
(2nd wait) wait for user to continue, by polling to check existence of a file.
During this period, maintainer can edit some files in `buildtrees/<port>` directory.
Optionally, manual / auto perform `git commit`, `git diff` in `${TEMP_SOURCE_PATH}` to generate patch file.
When maintainer finishes editing, he should create a wait file, so that the cmake script continues.

This workflow may help maintainers to prepare and test port patches.

**Comment by JackBoosY** [comment]
Now, we can use `--editable` to build the modified code.  And we want to make sure that the code has been modified before installation, so I think this feature is not needed.

**Comment by JackBoosY** [comment]
And we have overlay port now, please see [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/specifications/ports-overlay.md).
