### ISSUE TITLE
[tbb] File does not have expected hash

### ISSUE THREAD

**Issue by shauser67** [microsoft/vcpkg#10822]
The vcpkg package tbb fails to build on x64-linux and x86-windows (osx not tested).

```
File does not have expected hash:

File path: [ /home/sh/dev/vcpkg-2020.01/downloads/temp/intel-tbb-4bdba61bafc6ba2d636f31564f1de5702d365cf7.tar.gz ]
Expected hash: [ 0b00c9deefdac5dc1f4fbae314e91eb3513b54b47ff6dec08ed2460486fc7d211ab36d6130e5787bfd50523cb613c65f03f9217d967292ca9056e2d3f5010bf8 ]
Actual hash: [ f2a8d7e0476f846039390f4a79af3fe13770e23b01bf4741e738136f7ddb401357a0e50f35212e8d0fa5fc4cf1563418337309227d7243fc3676edd406ae652d ]
```

Package: tbb:x64-linux
Vcpkg version: 2020.01.17-unknownhash

**Comment by PhoebeHui** [comment]
@shauser67, coud you get latest source(git pull) and try to build tbb again? from your log, it seems you are using the older revision. 

PS F:\vcpkg\src> ./vcpkg install tbb
Computing installation plan...
The following packages will be built and installed:
    tbb[core]:x86-windows
Starting package 1/1: tbb:x86-windows
Building package tbb[core]:x86-windows...
-- Downloading https://github.com/oneapi-src/oneTBB/archive/427c252e0bb9e191767a62d8a744b21950c343f6.tar.gz...
-- Extracting source F:/VCPKG/src/downloads/oneapi-src-oneTBB-427c252e0bb9e191767a62d8a744b21950c343f6.tar.gz
-- Applying patch fix-static-build.patch
-- Applying patch terminate-when-buildtool-notfound.patch
-- Using source at F:/VCPKG/src/buildtrees/tbb/src/1950c343f6-81f8b97441
-- Building build/vs2013/makefile.sln for Release
-- Building build/vs2013/makefile.sln for Debug
-- Installing: F:/VCPKG/src/packages/tbb_x86-windows/share/tbb/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package tbb[core]:x86-windows... done
Installing package tbb[core]:x86-windows...
Installing package tbb[core]:x86-windows... done
Elapsed time for package tbb:x86-windows: 1.639 min

Total elapsed time: 1.643 min

The package tbb provides CMake targets:

    find_package(TBB CONFIG REQUIRED)
    target_link_libraries(main PRIVATE TBB::tbb)

**Comment by shauser67** [comment]
Thank you, this solved the issue!
