### ISSUE TITLE
[vcpkg buildsystem] The cmake build system does not detect standard libraries that are too old to work

### ISSUE THREAD

**Issue by emrsmsrli** [microsoft/vcpkg#10829]
**Describe the bug**
Vcpkg does not bootstrap on Travis with Clang-9 compiler, using command
`./bootstrap-vcpkg.sh -disableMetrics`. 

Having this error:  `Illegal number: clang version 9`

After this, it gives compile errors. More on attached logs below.

**Environment**
- OS: Ubuntu 16.04 (Travis Xenial image)
- Compiler: Clang 9

**To Reproduce**
1. Install clang-9 on a Travis Xenial image with source configuration like this:
```yaml
sourceline: 'deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main'
key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
```
2. Set env variables `CC=/usr/bin/clang-9` && `CXX=/usr/bin/clang++-9`
3. Clone vcpkg and try to bootstrap it
3. See compile errors

**Expected behavior**
Vcpkg should bootstrap with clang-9 without any issues.

**Failure logs** 
- https://pastecode.xyz/view/abf87f00#L35

**Comment by NancyLi1013** [comment]
Hi @emrsmsrli 
Thanks for posting this issue.
Could you please try to refer to this issue #3980 and check if you set ariables CC=/usr/bin/clang-9 && CXX=/usr/bin/clang++-9 correctly?

**Comment by emrsmsrli** [comment]
Hi there. 
Yes the env variables are set correctly. I was building fine with Clang before I switched to vcpkg.

**Comment by linquize** [comment]
Could you try the latest master? Fixed issues #10834, #10846, #10867

**Comment by emrsmsrli** [comment]
It's still failing. 

```
Downloading cmake... 
Downloading cmake... done.
Extracting cmake...
Extracting cmake... done.

Downloading ninja...
Downloading ninja... done.
Extracting ninja...
Extracting ninja... done.

-- The CXX compiler identification is Clang 9.0.1
-- Check for working CXX compiler: /usr/bin/clang++-9
-- Check for working CXX compiler: /usr/bin/clang++-9 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting the C++ standard library

CMake Error at cmake/utilities.cmake:79 (message):
  Can't find which C++ runtime is in use
Call Stack (most recent call first):
  CMakeLists.txt:31 (vcpkg_detect_standard_library)
```

You can see the full log here: https://travis-ci.com/github/emrsmsrli/gameboi/jobs/320946027

I'm using libc++ in my clang builds. I checked out #10834, it seems `vcpkg_detect_standard_library` is implemented but I need to pass libc++ explicitly in this case. Is there any way I can do that?

Thanks.

**Comment by emrsmsrli** [comment]
I guess it doesn't really matter for packages, my own cmake script handles that. But still vcpkg is not building properly because of misdetection.

**Comment by strega-nil** [comment]
@emrsmsrli so is this an issue on macOS, I assume? If you explicitly set `CXX`, we shouldn't do that check.

**Comment by strega-nil** [comment]
Hmm, that looks like an older version of vcpkg; can you try updating to latest master?

**Comment by strega-nil** [comment]
For what it's worth, you don't have to worry about setting `CC` anymore.

**Comment by strega-nil** [comment]
Also, I can't figure out how to install packages on Ubuntu in a way that causes this failure. What standard library are you linking with?

**Comment by strega-nil** [comment]
Oh, that's frustrating; apparently in libstdc++ 2016, they don't define `__GLIBCXX__` in `<ciso646>`. I'll fix this...

**Comment by NancyLi1013** [comment]
Hi @emrsmsrli 
Since vcpkg doesn't support libstdc++ 5, please try to update it to the new version.

**Comment by PhoebeHui** [comment]
@emrsmsrli, does this issue still repro with latest VCPKG?

**Comment by emrsmsrli** [comment]
@PhoebeHui I can confirm vcpkg successfully builds with the same config I had at the time this issue is created. You can find the logs here: https://app.travis-ci.com/github/emrsmsrli/gameboi/jobs/529087800
Don't mind the build job failing, that's on my end. Thanks for the efforts!

**Comment by PhoebeHui** [comment]
@emrsmsrli, thanks for your reply!
