### ISSUE TITLE
Error: Building package boost:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by vinniefalco** [Microsoft/vcpkg#1082]
Fresh clone and build of vcpkg, followed the directions in the README.md
Ran from a command prompt, this commant:
```
.\vcpkg install beast
```

Failed with this error:
```
Error: Building package boost:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost:x86-windows
  Vcpkg version: 0.0.81-05e682a19d40036c9a34c2c7a94e6325fb7e9f1c
```

This was the output:
```
C:\Users\vinnie\src\vcpkg>.\vcpkg install beast
The following packages will be built and installed:
    beast:x86-windows
  * boost:x86-windows
Additional packages (*) will be installed to complete this operation.
Building package boost:x86-windows...
-- CURRENT_INSTALLED_DIR=C:/Users/vinnie/src/vcpkg/installed/x86-windows
-- DOWNLOADS=C:/Users/vinnie/src/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/Users/vinnie/src/vcpkg/packages/boost_x86-windows
-- CURRENT_BUILDTREES_DIR=C:/Users/vinnie/src/vcpkg/buildtrees/boost
-- CURRENT_PORT_DIR=C:/Users/vinnie/src/vcpkg/ports/boost/.
-- Using cached C:/Users/vinnie/src/vcpkg/downloads/boost_1_64_0.tar.bz2
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Using cached C:/Users/vinnie/src/vcpkg/downloads/boost-range-has_range_iterator-hotfix_e7ebe14707130cda7b72e0ae5e93b17157fdb6a2.diff
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Applying patch C:/Users/vinnie/src/vcpkg/buildtrees/boost/src/boost-range-has_range_iterator-hotfix_e7ebe14707130cda7b72e0ae5e93b17157fdb6a2.diff.fixed
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch C:/Users/vinnie/src/vcpkg/buildtrees/boost/src/boost-range-has_range_iterator-hotfix_e7ebe14707130cda7b72e0ae5e93b17157fdb6a2.diff.fixed done
-- Bootstrapping done
-- Building x86-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process_repeat.cmake:21 (message):
    Command failed: C:/Users/vinnie/src/vcpkg/buildtrees/boost/src/boost_1_64_0/b2.exe;--stagedir=C:/Users/vinnie/src/vcpkg/buildtrees/boost/x86-windows-rel/stage;--build-dir=C:/Users/vinnie/src/vcpkg/buildtrees/boost/x86-windows-rel;-sZLIB_INCLUDE="C:/Users/vinnie/src/vcpkg/installed/x86-windows\include";-sBZIP2_INCLUDE="C:/Users/vinnie/src/vcpkg/installed/x86-windows\include";-j20;--debug-configuration;--hash;-q;--without-python;threading=multi;runtime-link=shared;link=shared;toolset=msvc-14.1;-sZLIB_BINARY=zlib;-sZLIB_LIBPATH="C:/Users/vinnie/src/vcpkg/installed/x86-windows\lib";-sBZIP2_BINARY=bz2;-sBZIP2_LIBPATH="C:/Users/vinnie/src/vcpkg/installed/x86-windows\lib";variant=release;debug-symbols=on
    Working Directory: C:/Users/vinnie/src/vcpkg/buildtrees/boost/src/boost_1_64_0
    See logs for more information:
      C:\Users\vinnie\src\vcpkg\buildtrees\boost\build-x86-windows-rel-out.log
      C:\Users\vinnie\src\vcpkg\buildtrees\boost\build-x86-windows-rel-err.log

Call Stack (most recent call first):
  ports/boost/portfile.cmake:188 (vcpkg_execute_required_process_repeat)
  scripts/ports.cmake:73 (include)
```

**Comment by ras0219-msft** [comment]
Hey vinnie, thanks for trying out vcpkg 😊.

Sorry about the failure! I suspect based on previous experience that it is due to a site-config or user config file somewhere on your disk that bjam is picking up.

Could you post or send us the two log files listed in the message?
- C:\Users\vinnie\src\vcpkg\buildtrees\boost\build-x86-windows-rel-out.log
- C:\Users\vinnie\src\vcpkg\buildtrees\boost\build-x86-windows-rel-err.log

**Comment by vinniefalco** [comment]
I renamed the site-config.jam in my user directory and it got farther along. This is the contents of my site-config.jam:

```
import os ;

using msvc ;

using boostbook
    : "C:/Users/vinnie/lib/docbook-xsl"
    : "C:/Users/vinnie/lib/docbook-dtd"
    ;

using xsltproc ;

using doxygen ;

using fop
    : "C:/Users/vinnie/boost_1_64_0/tools/boostbook/fop-0.94\fop
    :
    : "C:/ProgramData/Oracle/Java/javapath/java
    ;

local OPENSSL_ROOT = [ os.environ OPENSSL_ROOT ] ;
local OPENSSL_LIBRARIES = [ os.environ OPENSSL_LIBRARIES ] ;
local OPENSSL_INCLUDE_DIR = [ os.environ OPENSSL_INCLUDE_DIR ] ;

project
  : requirements
    <include>$(OPENSSL_ROOT)/include
    <library-path>$(OPENSSL_ROOT)/lib
  ;
```

It is still building, probably it will work, thanks.

**Comment by vinniefalco** [comment]
Here are the log files. Not sure what the numbers at the end of the filenames mean.




[build-x86-windows-rel-err-2.txt](https://github.com/Microsoft/vcpkg/files/994575/build-x86-windows-rel-err-2.txt)
[build-x86-windows-rel-out-0.txt](https://github.com/Microsoft/vcpkg/files/994573/build-x86-windows-rel-out-0.txt)
[build-x86-windows-rel-out-1.txt](https://github.com/Microsoft/vcpkg/files/994572/build-x86-windows-rel-out-1.txt)
[build-x86-windows-rel-out-2.txt](https://github.com/Microsoft/vcpkg/files/994577/build-x86-windows-rel-out-2.txt)
[build-x86-windows-rel-err-0.txt](https://github.com/Microsoft/vcpkg/files/994574/build-x86-windows-rel-err-0.txt)
[build-x86-windows-rel-err-1.txt](https://github.com/Microsoft/vcpkg/files/994576/build-x86-windows-rel-err-1.txt)

**Comment by vinniefalco** [comment]
The beast install was successful but I need that site-config.jam where it is for my other projects to work. What do I do?

**Comment by vinniefalco** [comment]
Just wondering if anyone knows the answer to this:
> I would love advice on how to stop Visual Studio 2017 from echoing the command lines it is using during a build, but that's not a vcpkg specific problem.

Described in more detail in #1084 (which I have since closed)

**Comment by ras0219-msft** [comment]
Unfortunately, the best current answer is that you will need to temporarily rename your site-config if you want to build boost through vcpkg -- you can rename it back once you are done since we cache the build.

I would love to have a better answer here, but I haven't been able to find any way to suppress bjam from picking it up (site-config). In the worst case, we may need to patch boost during our build to fix this.

**Comment by vinniefalco** [comment]
Oh, you're saying that my site-config.jam only gets in the way when building Boost through vcpkg. That's not completely terrible. I could rename it to user-config.jam, maybe that would help.

**Comment by ras0219-msft** [comment]
That would work for us, because we supply our own user-config in order to customize the exact compiler used.

I don't know your full environment so I'm not sure how it would impact the rest of your boost usages.

**Comment by vinniefalco** [comment]
I did a fresh install using `vcpkg install beast` with my config file renamed to **user-config.jam**, and it all worked! I was able to build my previous projects which use the bjam toolchain (mostly documentation) which relied on my user-wide jam file and it worked as well, so I think this is resolved.

**Comment by SergeyJames** [comment]
Hi everybody! 
1. remove "\protobuf" from "C:\src\vcpkg\buildtrees\"
2. .\vcpkg.exe install protobuf
It helped me!
