### ISSUE TITLE
cant run PS> .\bootstrap-vcpkg.bat in powershell

### ISSUE THREAD

**Issue by youmania83** [microsoft/vcpkg#10824]
Dear All,

I wont be able to run PS> .\bootstrap-vcpkg.bat in powershell.

I am getting following errors.

bootstrap-vcpkg.bat : The term 'bootstrap-vcpkg.bat' is not recognized as the name of a cmdlet, function, script file,
or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and
try again.
At line:1 char:1
+ bootstrap-vcpkg.bat
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (bootstrap-vcpkg.bat:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

please help me by step by step guide .

My OS  is win 10

**Comment by vadi2** [comment]
Did you `cd` to a directory where that file is? That might be the problem.

**Comment by PhoebeHui** [comment]
@youmania83, can you try the following steps:

1. git clone https://github.com/microsoft/vcpkg
2. cd vcpkg
3. .\bootstrap-vcpkg.bat

**Comment by youmania83** [comment]
Already tried these steps

**Comment by youmania83** [comment]
> @youmania83, can you try the following steps:
> 
> 1. git clone https://github.com/microsoft/vcpkg
> 2. cd vcpkg
> 3. .\bootstrap-vcpkg.bat
> 

Already done this  bro.

3rd command won't work in powershell.
Powershell produce error command not found

**Comment by vadi2** [comment]
Show us the full output of all 3 steps.

**Comment by PhoebeHui** [comment]
@youmania83, does this still be a problem for you?

**Comment by PhoebeHui** [comment]
@youmania83, please reopen if it still be a problem for you.

**Comment by niitsuma** [comment]
execute \bootstrap-vcpkg.bat on current vcpkg
then
cd \vcpkg-some-old-version
execute \bootstrap-vcpkg.bat 

This error happen
and
rec-open com can avoid this

**Comment by nitish166** [comment]
> Show us the full output of all 3 steps.

PS C:\Users\TEMP\Downloads\vcpkg-master\vcpkg-master\toolsrc\windows-bootstrap\vcpkg> bootstrap-vcpkg.bat
bootstrap-vcpkg.bat : The term 'bootstrap-vcpkg.bat' is not recognized as the name of a cmdlet, function, script file, or operable program.       
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ bootstrap-vcpkg.bat
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (bootstrap-vcpkg.bat:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by nitish166** [comment]
Please check the above error and get back to me. Thank you!

**Comment by Felipe21** [comment]
im having the exact same issue i ha e installed git on disk D  msvc on disk D and vcpkg on disk D
i made thse 3 steps but after all i got this error
Prueba la nueva tecnología PowerShell multiplataforma https://aka.ms/pscore6
i opened git and powershell as admin ( yes i tried both )
```
PS C:\Windows\system32> cd ..
PS C:\Windows> cd..
PS C:\> cd D:
PS D:\> cd vcpkg
PS D:\vcpkg> .\bootstrap-vcpkg.bat
"powershell.exe" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
PS D:\vcpkg>

```

**Comment by PhoebeHui** [comment]
@Felipe21, could you please report a new issue instead?

**Comment by ErfanRoshan** [comment]
Hey guys this issue has a straightforward answer.
You must add Powershell in the environment variable.
The address is C:\Windows\System32\WindowsPowerShell\v1.0
