### ISSUE TITLE
[wangle] linking wangle

### ISSUE THREAD

**Issue by tarakan012** [microsoft/vcpkg#10827]
I am building wangle using vcpkg and trying to link against it in VS 2017 project.
>------ Build started: Project: CMakeLists, Configuration: Debug ------
  [1/2] "C:\PROGRA~2\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.exe"  /nologo /TP -DBOOST_CONFIG_SUPPRESS_OUTDATED_MESSAGE -DGFLAGS_IS_A_DLL=1 -DWIN32_LEAN_AND_MEAN -D_CRT_NONSTDC_NO_WARNINGS -D_CRT_SECURE_NO_WARNINGS -D_ENABLE_EXTENDED_ALIGNED_STORAGE -D_SCL_SECURE_NO_WARNINGS -D_STL_EXTRA_DISABLED_WARNINGS="4774 4987" -ID:\vcpkg\installed\x64-windows\include /DWIN32 /D_WINDOWS /W3 /GR /EHsc /MDd /Zi /Ob0 /Od /RTC1   /EHs /GF /Zc:referenceBinding /Zc:rvalueCast /Zc:implicitNoexcept /Zc:strictStrings /Zc:threadSafeInit /Zc:throwingNew /permissive- /std:c++latest /wd4191 /wd4291 /wd4309 /wd4310 /wd4366 /wd4587 /wd4592 /wd4628 /wd4723 /wd4724 /wd4868 /wd4996 /wd4068 /wd4091 /wd4146 /wd4800 /wd4018 /wd4365 /wd4388 /wd4389 /wd4100 /wd4459 /wd4505 /wd4701 /wd4702 /wd4061 /wd4127 /wd4200 /wd4201 /wd4296 /wd4316 /wd4324 /wd4355 /wd4371 /wd4435 /wd4514 /wd4548 /wd4571 /wd4574 /wd4582 /wd4583 /wd4619 /wd4623 /wd4625 /wd4626 /wd4643 /wd4647 /wd4668 /wd4706 /wd4710 /wd4711 /wd4714 /wd4820 /wd5026 /wd5027 /wd5031 /wd5045 /we4099 /we4129 /we4566 /bigobj /showIncludes /FoCMakeFiles\Lion.dir\main.cpp.obj /FdCMakeFiles\Lion.dir\ /FS -c ..\..\main.cpp
D:\vcpkg\installed\x64-windows\include\folly\portability\Windows.h(31): warning C4005: '_CRT_INTERNAL_NONSTDC_NAMES': macro redefinition
  C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt\corecrt.h(322): note: see previous definition of '_CRT_INTERNAL_NONSTDC_NAMES'
D:\vcpkg\installed\x64-windows\include\folly\executors\IOThreadPoolExecutor.h(94): warning C4250: 'folly::IOThreadPoolExecutor': inherits 'folly::DefaultKeepAliveExecutor::folly::DefaultKeepAliveExecutor::keepAliveAcquire' via dominance
  D:\vcpkg\installed\x64-windows\include\folly/DefaultKeepAliveExecutor.h(135): note: see declaration of 'folly::DefaultKeepAliveExecutor::keepAliveAcquire'
D:\vcpkg\installed\x64-windows\include\folly\executors\IOThreadPoolExecutor.h(94): warning C4250: 'folly::IOThreadPoolExecutor': inherits 'folly::DefaultKeepAliveExecutor::folly::DefaultKeepAliveExecutor::keepAliveRelease' via dominance
  D:\vcpkg\installed\x64-windows\include\folly/DefaultKeepAliveExecutor.h(143): note: see declaration of 'folly::DefaultKeepAliveExecutor::keepAliveRelease'
D:\vcpkg\installed\x64-windows\include\wangle\bootstrap\ClientBootstrap.h(134): warning C4244: 'argument': conversion from '_Rep' to 'int', possible loss of data
          with
          [
              _Rep=__int64
          ]
  D:\vcpkg\installed\x64-windows\include\wangle/bootstrap/ClientBootstrap.h(103): note: while compiling class template member function 'folly::Future<P *> wangle::ClientBootstrap<MyPipeline>::connect(const folly::SocketAddress &,std::chrono::milliseconds)'
          with
          [
              P=MyPipeline
          ]
  ..\..\main.cpp(58): note: see reference to function template instantiation 'folly::Future<P *> wangle::ClientBootstrap<MyPipeline>::connect(const folly::SocketAddress &,std::chrono::milliseconds)' being compiled
          with
          [
              P=MyPipeline
          ]
  ..\..\main.cpp(50): note: see reference to class template instantiation 'wangle::ClientBootstrap<MyPipeline>' being compiled
  D:\vcpkg\installed\x64-windows\include\folly/Range.h(1356): note: see reference to class template instantiation 'folly::Range<const char *>' being compiled
  [2/2] cmd.exe /C "cd . && "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\Lion.dir --manifests  -- "C:\PROGRA~2\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64\link.exe" /nologo CMakeFiles\Lion.dir\main.cpp.obj  /out:Lion.exe /implib:Lion.lib /pdb:Lion.pdb /version:0.0  /machine:x64 /debug /INCREMENTAL /subsystem:console  D:\vcpkg\installed\x64-windows\debug\lib\wangle.lib D:\vcpkg\installed\x64-windows\debug\lib\fizz.lib D:\vcpkg\installed\x64-windows\debug\lib\folly.lib Iphlpapi.lib Ws2_32.lib D:\vcpkg\installed\x64-windows\debug\lib\zlibd.lib D:\vcpkg\installed\x64-windows\lib\libssl.lib D:\vcpkg\installed\x64-windows\lib\libcrypto.lib D:\vcpkg\installed\x64-windows\lib\libsodium.lib D:\vcpkg\installed\x64-windows\lib\glog.lib D:\vcpkg\installed\x64-windows\lib\double-conversion.lib D:\vcpkg\installed\x64-windows\debug\lib\boost_system-vc140-mt-gd.lib D:\vcpkg\installed\x64-windows\debug\lib\boost_thread-vc140-mt-gd.lib D:\vcpkg\installed\x64-windows\debug\lib\boost_filesystem-vc140-mt-gd.lib D:\vcpkg\installed\x64-windows\debug\lib\boost_regex-vc140-mt-gd.lib D:\vcpkg\installed\x64-windows\debug\lib\boost_context-vc140-mt-gd.lib D:\vcpkg\installed\x64-windows\debug\lib\boost_program_options-vc140-mt-gd.lib D:\vcpkg\installed\x64-windows\debug\lib\boost_chrono-vc140-mt-gd.lib D:\vcpkg\installed\x64-windows\debug\lib\boost_date_time-vc140-mt-gd.lib D:\vcpkg\installed\x64-windows\debug\lib\boost_atomic-vc140-mt-gd.lib D:\vcpkg\installed\x64-windows\debug\lib\libssl.lib D:\vcpkg\installed\x64-windows\debug\lib\libcrypto.lib D:\vcpkg\installed\x64-windows\debug\lib\glog.lib D:\vcpkg\installed\x64-windows\debug\lib\gflags_debug.lib shlwapi.lib D:\vcpkg\installed\x64-windows\debug\lib\event.lib D:\vcpkg\installed\x64-windows\debug\lib\double-conversion.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
  FAILED: Lion.exe 
  cmd.exe /C "cd . && "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\Lion.dir --manifests  -- "C:\PROGRA~2\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64\link.exe" /nologo CMakeFiles\Lion.dir\main.cpp.obj  /out:Lion.exe /implib:Lion.lib /pdb:Lion.pdb /version:0.0  /machine:x64 /debug /INCREMENTAL /subsystem:console  D:\vcpkg\installed\x64-windows\debug\lib\wangle.lib D:\vcpkg\installed\x64-windows\debug\lib\fizz.lib D:\vcpkg\installed\x64-windows\debug\lib\folly.lib Iphlpapi.lib Ws2_32.lib D:\vcpkg\installed\x64-windows\debug\lib\zlibd.lib D:\vcpkg\installed\x64-windows\lib\libssl.lib D:\vcpkg\installed\x64-windows\lib\libcrypto.lib D:\vcpkg\installed\x64-windows\lib\libsodium.lib D:\vcpkg\installed\x64-windows\lib\glog.lib D:\vcpkg\installed\x64-windows\lib\double-conversion.lib D:\vcpkg\installed\x64-windows\debug\lib\boost_system-vc140-mt-gd.lib D:\vcpkg\installed\x64-windows\debug\lib\boost_thread-vc140-mt-gd.lib D:\vcpkg\installed\x64-windows\debug\lib\boost_filesystem-vc140-mt-gd.lib D:\vcpkg\installed\x64-windows\debug\lib\boost_regex-vc140-mt-gd.lib D:\vcpkg\installed\x64-windows\debug\lib\boost_context-vc140-mt-gd.lib D:\vcpkg\installed\x64-windows\debug\lib\boost_program_options-vc140-mt-gd.lib D:\vcpkg\installed\x64-windows\debug\lib\boost_chrono-vc140-mt-gd.lib D:\vcpkg\installed\x64-windows\debug\lib\boost_date_time-vc140-mt-gd.lib D:\vcpkg\installed\x64-windows\debug\lib\boost_atomic-vc140-mt-gd.lib D:\vcpkg\installed\x64-windows\debug\lib\libssl.lib D:\vcpkg\installed\x64-windows\debug\lib\libcrypto.lib D:\vcpkg\installed\x64-windows\debug\lib\glog.lib D:\vcpkg\installed\x64-windows\debug\lib\gflags_debug.lib shlwapi.lib D:\vcpkg\installed\x64-windows\debug\lib\event.lib D:\vcpkg\installed\x64-windows\debug\lib\double-conversion.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
  LINK Pass 1: command "C:\PROGRA~2\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64\link.exe /nologo CMakeFiles\Lion.dir\main.cpp.obj /out:Lion.exe /implib:Lion.lib /pdb:Lion.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console D:\vcpkg\installed\x64-windows\debug\lib\wangle.lib D:\vcpkg\installed\x64-windows\debug\lib\fizz.lib D:\vcpkg\installed\x64-windows\debug\lib\folly.lib Iphlpapi.lib Ws2_32.lib D:\vcpkg\installed\x64-windows\debug\lib\zlibd.lib D:\vcpkg\installed\x64-windows\lib\libssl.lib D:\vcpkg\installed\x64-windows\lib\libcrypto.lib D:\vcpkg\installed\x64-windows\lib\libsodium.lib D:\vcpkg\installed\x64-windows\lib\glog.lib D:\vcpkg\installed\x64-windows\lib\double-conversion.lib D:\vcpkg\installed\x64-windows\debug\lib\boost_system-vc140-mt-gd.lib D:\vcpkg\installed\x64-windows\debug\lib\boost_thread-vc140-mt-gd.lib D:\vcpkg\installed\x64-windows\debug\lib\boost_filesystem-vc140-mt-gd.lib D:\vcpkg\installed\x64-windows\debug\lib\boost_regex-vc140-mt-gd.lib D:\vcpkg\installed\x64-windows\debug\lib\boost_context-vc140-mt-gd.lib D:\vcpkg\installed\x64-windows\debug\lib\boost_program_options-vc140-mt-gd.lib D:\vcpkg\installed\x64-windows\debug\lib\boost_chrono-vc140-mt-gd.lib D:\vcpkg\installed\x64-windows\debug\lib\boost_date_time-vc140-mt-gd.lib D:\vcpkg\installed\x64-windows\debug\lib\boost_atomic-vc140-mt-gd.lib D:\vcpkg\installed\x64-windows\debug\lib\libssl.lib D:\vcpkg\installed\x64-windows\debug\lib\libcrypto.lib D:\vcpkg\installed\x64-windows\debug\lib\glog.lib D:\vcpkg\installed\x64-windows\debug\lib\gflags_debug.lib shlwapi.lib D:\vcpkg\installed\x64-windows\debug\lib\event.lib D:\vcpkg\installed\x64-windows\debug\lib\double-conversion.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\Lion.dir/intermediate.manifest CMakeFiles\Lion.dir/manifest.res" failed (exit code 1319) with the following output:
C:\WINDOWS\system32\double-conversion.lib(double-conversion.cc.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.cpp.obj
C:\WINDOWS\system32\double-conversion.lib(double-conversion.cc.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in main.cpp.obj
C:\WINDOWS\system32\double-conversion.lib(bignum-dtoa.cc.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.cpp.obj
C:\WINDOWS\system32\double-conversion.lib(bignum-dtoa.cc.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in main.cpp.obj
C:\WINDOWS\system32\double-conversion.lib(fast-dtoa.cc.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.cpp.obj
C:\WINDOWS\system32\double-conversion.lib(fast-dtoa.cc.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in main.cpp.obj
C:\WINDOWS\system32\double-conversion.lib(fixed-dtoa.cc.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.cpp.obj
C:\WINDOWS\system32\double-conversion.lib(fixed-dtoa.cc.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in main.cpp.obj
C:\WINDOWS\system32\double-conversion.lib(strtod.cc.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.cpp.obj
C:\WINDOWS\system32\double-conversion.lib(strtod.cc.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in main.cpp.obj
C:\WINDOWS\system32\double-conversion.lib(bignum.cc.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.cpp.obj
C:\WINDOWS\system32\double-conversion.lib(bignum.cc.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in main.cpp.obj
C:\WINDOWS\system32\double-conversion.lib(diy-fp.cc.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.cpp.obj
C:\WINDOWS\system32\double-conversion.lib(diy-fp.cc.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in main.cpp.obj
C:\WINDOWS\system32\double-conversion.lib(cached-powers.cc.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.cpp.obj
C:\WINDOWS\system32\double-conversion.lib(cached-powers.cc.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in main.cpp.obj
     Creating library Lion.lib and object Lion.exp
C:\WINDOWS\system32\LINK : warning LNK4098: defaultlib 'MSVCRT' conflicts with use of other libs; use /NODEFAULTLIB:library
C:\WINDOWS\system32\Lion.exe : fatal error LNK1319: 16 mismatches detected
  ninja: build stopped: subcommand failed.

**Comment by LilyWangL** [comment]
@tarakan012 Thanks for posting this issue. Could you please provide the repro code?

**Comment by tarakan012** [comment]
@LilyWangL https://github.com/tarakan012/wangle_test

**Comment by LilyWangL** [comment]
Sorry I am late, I reproduced this issue locally. 
Iterator debug level defaults to 2 in debug and is disabled in release. One of the dlls this project are using probably has iterator debugging turned off in debug either because it was built in an older version of visual studio. I could build this project sucessfully in release.
