### ISSUE TITLE
Cannot link vcpkg installed library

### ISSUE THREAD

**Issue by guidebee** [microsoft/vcpkg#10823]
**Describe the bug**
lvcpkg install opencv correctly, was working before, not sure it's because recent upgrade. cannot link opencv library on windows anymore, though on Mac works fine.

**Environment**
- OS: windows 10 
- Compiler: revision

**To Reproduce**
1. ./vcpkg install catch2 sdl2 ffmpeg opencv opecv[contrib] nlohmann-json
2. See error
  λ ninja
[1/3] Linking CXX executable apps\tutorial02\tutorial02.exe
FAILED: apps/tutorial02/tutorial02.exe
cmd.exe /C "cd . && C:\SysGCC\mingw64\bin\c++.exe -D__STDC_CONSTANT_MACROS   @CMakeFiles\tutorial02.rsp  -o apps\tutorial02\tutorial02.exe -Wl,--out-implib,apps\tutorial02\libtutorial02.dll.a -Wl,--major-image-version,0,--minor-image-version,0  && cmd.exe /C "cd /D C:\Workspace\ffmpeg-tutorial\build\apps\tutorial02 && powershell -noprofile -executionpolicy Bypass -file C:/Workspace/vcpkg/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary C:/Workspace/ffmpeg-tutorial/build/apps/tutorial02/tutorial02.exe -installedDir C:/Workspace/vcpkg/installed/x64-windows/bin -OutVariable out""
Warning: corrupt .drectve at end of def file
C:/Workspace/vcpkg/installed/x64-windows/debug/lib/manual-link/SDL2maind.lib(CMakeFiles/SDL2main.dir/src/main/windows/SDL_windows_main.c.obj):(.text$mn+0x2fb): undefined reference to `SDL_ShowSimpleMessageBox'
C:/Workspace/vcpkg/installed/x64-windows/debug/lib/manual-link/SDL2maind.lib(CMakeFiles/SDL2main.dir/src/main/windows/SDL_windows_main.c.obj):(.text$mn+0x49d): undefined reference to `SDL_ReportAssertion'
C:/Workspace/vcpkg/installed/x64-windows/debug/lib/manual-link/SDL2maind.lib(CMakeFiles/SDL2main.dir/src/main/windows/SDL_windows_main.c.obj):(.text$mn+0x502): undefined reference to `SDL_ReportAssertion'
C:/Workspace/vcpkg/installed/x64-windows/debug/lib/manual-link/SDL2maind.lib(CMakeFiles/SDL2main.dir/src/main/windows/SDL_windows_main.c.obj):(.text$mn+0x53b): undefined reference to `SDL_SetMainReady'
collect2.exe: error: ld returned 1 exit status

collect2.exe: error: ld returned 1 exit status
[2/3] Linking CXX executable apps\tutorial03\tutorial03.exe
FAILED: apps/tutorial03/tutorial03.exe
cmd.exe /C "cd . && C:\SysGCC\mingw64\bin\c++.exe -D__STDC_CONSTANT_MACROS   @CMakeFiles\tutorial03.rsp  -o apps\tutorial03\tutorial03.exe -Wl,--out-implib,apps\tutorial03\libtutorial03.dll.a -Wl,--major-image-version,0,--minor-image-version,0  && cmd.exe /C "cd /D C:\Workspace\ffmpeg-tutorial\build\apps\tutorial03 && powershell -noprofile -executionpolicy Bypass -file C:/Workspace/vcpkg/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary C:/Workspace/ffmpeg-tutorial/build/apps/tutorial03/tutorial03.exe -installedDir C:/Workspace/vcpkg/installed/x64-windows/bin -OutVariable out""
apps/tutorial03/CMakeFiles/tutorial03.dir/__/__/src/tutorial03.cpp.obj:tutorial03.cpp:(.text+0xa9): undefined reference to `cv::cvtColor(cv::_InputArray const&, cv::_OutputArray const&, int, int)'
apps/tutorial03/CMakeFiles/tutorial03.dir/__/__/src/tutorial03.cpp.obj:tutorial03.cpp:(.text+0x12f): undefined reference to `cv::Canny(cv::_InputArray const&, cv::_OutputArray const&, double, double, int, bool)'
apps/tutorial03/CMakeFiles/tutorial03.dir/__/__/src/tutorial03.cpp.obj:tutorial03.cpp:(.text+0x1cf): undefined reference to `cv::findContours(cv::_InputArray const&, cv::_OutputArray const&, cv::_OutputArray const&, int, int, cv::Point_<int>)'
apps/tutorial03/CMakeFiles/tutorial03.dir/__/__/src/tutorial03.cpp.obj:tutorial03.cpp:(.text+0x2c3): undefined reference to `cv::contourArea(cv::_InputArray const&, bool)'
apps/tutorial03/CMakeFiles/tutorial03.dir/__/__/src/tutorial03.cpp.obj:tutorial03.cpp:(.text+0x36d): undefined reference to `cv::approxPolyDP(cv::_InputArray const&, cv::_OutputArray const&, double, bool)'
apps/tutorial03/CMakeFiles/tutorial03.dir/__/__/src/tutorial03.cpp.obj:tutorial03.cpp:(.text+0x740): undefined reference to `cv::resize(cv::_InputArray const&, cv::_OutputArray const&, cv::Size_<int>, double, double, int)'
apps/tutorial03/CMakeFiles/tutorial03.dir/__/__/src/tutorial03.cpp.obj:tutorial03.cpp:(.text+0x7bb): undefined reference to `cv::cvtColor(cv::_InputArray const&, cv::_OutputArray const&, int, int)'
apps/tutorial03/CMakeFiles/tutorial03.dir/__/__/src/tutorial03.cpp.obj:tutorial03.cpp:(.text+0x911): undefined reference to `cv::Mat::zeros(cv::Size_<int>, int)'
apps/tutorial03/CMakeFiles/tutorial03.dir/__/__/src/tutorial03.cpp.obj:tutorial03.cpp:(.text+0x9a7): undefined reference to `cv::contourArea(cv::_InputArray const&, bool)'
apps/tutorial03/CMakeFiles/tutorial03.dir/__/__/src/tutorial03.cpp.obj:tutorial03.cpp:(.text+0xa80): undefined reference to `cv::drawContours(cv::_InputOutputArray const&, cv::_InputArray const&, int, cv::Scalar_<double> const&, int, int, cv::_InputArray const&, int, cv::Point_<int>)'
apps/tutorial03/CMakeFiles/tutorial03.dir/__/__/src/tutorial03.cpp.obj:tutorial03.cpp:(.text+0xb11): undefined reference to `cv::resizeWindow(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int)'
apps/tutorial03/CMakeFiles/tutorial03.dir/__/__/src/tutorial03.cpp.obj:tutorial03.cpp:(.text+0xb87): undefined reference to `cv::imshow(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, cv::_InputArray const&)'
apps/tutorial03/CMakeFiles/tutorial03.dir/__/__/src/tutorial03.cpp.obj:tutorial03.cpp:(.text+0xbbe): undefined reference to `cv::waitKey(int)'
apps/tutorial03/CMakeFiles/tutorial03.dir/__/__/src/tutorial03.cpp.obj:tutorial03.cpp:(.text+0xc7b): undefined reference to `cv::imwrite(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, cv::_InputArray const&, std::vector<int, std::allocator<int> > const&)'
apps/tutorial03/CMakeFiles/tutorial03.dir/__/__/src/tutorial03.cpp.obj:tutorial03.cpp:(.text+0x12b9): undefined reference to `cv::namedWindow(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
apps/tutorial03/CMakeFiles/tutorial03.dir/__/__/src/tutorial03.cpp.obj:tutorial03.cpp:(.text$_ZN2cv3MatC1ERKS0_[_ZN2cv3MatC1ERKS0_]+0x17b): undefined reference to `cv::Mat::copySize(cv::Mat const&)'
apps/tutorial03/CMakeFiles/tutorial03.dir/__/__/src/tutorial03.cpp.obj:tutorial03.cpp:(.text$_ZN2cv3MatC1EiiiPvy[_ZN2cv3MatC1EiiiPvy]+0x138): undefined reference to `cv::error(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*, char const*, int)'
apps/tutorial03/CMakeFiles/tutorial03.dir/__/__/src/tutorial03.cpp.obj:tutorial03.cpp:(.text$_ZN2cv3MatC1EiiiPvy[_ZN2cv3MatC1EiiiPvy]+0x20e): undefined reference to `cv::error(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*, char const*, int)'
apps/tutorial03/CMakeFiles/tutorial03.dir/__/__/src/tutorial03.cpp.obj:tutorial03.cpp:(.text$_ZN2cv3MatC1EiiiPvy[_ZN2cv3MatC1EiiiPvy]+0x28b): undefined reference to `cv::Mat::updateContinuityFlag()'
apps/tutorial03/CMakeFiles/tutorial03.dir/__/__/src/tutorial03.cpp.obj:tutorial03.cpp:(.text$_ZN2cv3MatD1Ev[_ZN2cv3MatD1Ev]+0x36): undefined reference to `cv::fastFree(void*)'
apps/tutorial03/CMakeFiles/tutorial03.dir/__/__/src/tutorial03.cpp.obj:tutorial03.cpp:(.text$_ZN2cv3MataSERKS0_[_ZN2cv3MataSERKS0_]+0x10e): undefined reference to `cv::Mat::copySize(cv::Mat const&)'
apps/tutorial03/CMakeFiles/tutorial03.dir/__/__/src/tutorial03.cpp.obj:tutorial03.cpp:(.text$_ZN2cv3Mat7releaseEv[_ZN2cv3Mat7releaseEv]+0x48): undefined reference to `cv::Mat::deallocate()'
collect2.exe: error: ld returned 1 exit status
[3/3] Linking CXX executable tests\all_tests.exe
FAILED: tests/all_tests.exe
cmd.exe /C "cd . && C:\SysGCC\mingw64\bin\c++.exe -D__STDC_CONSTANT_MACROS   tests/CMakeFiles/all_tests.dir/all_tests.cpp.obj tests/CMakeFiles/all_tests.dir/test_opencv.cpp.obj tests/CMakeFiles/all_tests.dir/__/src/fact.cpp.obj  -o tests\all_tests.exe -Wl,--out-implib,tests\liball_tests.dll.a -Wl,--major-image-version,0,--minor-image-version,0  C:/Workspace/vcpkg/installed/x64-windows/debug/lib/avcodec.lib  C:/Workspace/vcpkg/installed/x64-windows/debug/lib/avformat.lib  C:/Workspace/vcpkg/installed/x64-windows/debug/lib/avutil.lib  C:/Workspace/vcpkg/installed/x64-windows/debug/lib/avdevice.lib
C:/Workspace/vcpkg/installed/x64-windows/debug/lib/swscale.lib  C:/Workspace/vcpkg/installed/x64-windows/debug/lib/avfilter.lib  C:/Workspace/vcpkg/installed/x64-windows/debug/lib/avresample.lib  C:/Workspace/vcpkg/installed/x64-windows/debug/lib/swresample.lib  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cmd.exe /C "cd /D C:\Workspace\ffmpeg-tutorial\build\tests && powershell -noprofile -executionpolicy Bypass -file C:/Workspace/vcpkg/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary C:/Workspace/ffmpeg-tutorial/build/tests/all_tests.exe -installedDir C:/Workspace/vcpkg/installed/x64-windows/bin -OutVariable out""
tests/CMakeFiles/all_tests.dir/test_opencv.cpp.obj:test_opencv.cpp:(.text$_ZN2cv3MatD1Ev[_ZN2cv3MatD1Ev]+0x36): undefined reference to `cv::fastFree(void*)'
tests/CMakeFiles/all_tests.dir/test_opencv.cpp.obj:test_opencv.cpp:(.text$_ZN2cv3Mat6createEiii[_ZN2cv3Mat6createEiii]+0x90): undefined reference to `cv::Mat::create(int, int const*, int)'
tests/CMakeFiles/all_tests.dir/test_opencv.cpp.obj:test_opencv.cpp:(.text$_ZN2cv3Mat7releaseEv[_ZN2cv3Mat7releaseEv]+0x48): undefined reference to `cv::Mat::deallocate()'
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

3. sample project is at https://github.com/guidebee/ffmpeg-tutorial
**Expected behavior**
 Link installed library correctly

**Failure logs** 
-(please attached failure logs)

**Additional context**

**Comment by guidebee** [comment]
![libs](https://user-images.githubusercontent.com/1016338/79222443-1b7d3b00-7e8a-11ea-951c-0e7e89699c84.PNG)

**Comment by guidebee** [comment]
`C:\Workspace\vcpkg\installed\x64-windows\debug\lib (master -> origin)
λ vcpkg list
catch2:x64-mingw                                   2.11.3           A modern, header-only test framework for unit te...
catch2:x64-windows                                 2.11.1           A modern, header-only test framework for unit te...
ffmpeg:x64-windows                                 4.2-6            a library to decode, encode, transcode, mux, dem...
ffmpeg[avresample]:x64-windows                                      Libav audio resampling library support in ffmpeg
hdf5:x64-windows                                   1.10.5-12        HDF5 is a data model, library, and file format f...
hdf5[szip]:x64-windows                                              Build with szip
hdf5[zlib]:x64-windows                                              Build with zlib
libjpeg-turbo:x64-windows                          2.0.4            libjpeg-turbo is a JPEG image codec that uses SI...
liblzma:x64-windows                                5.2.4-4          Compression library with an API similar to that ...
libpng:x64-windows                                 1.6.37-6         libpng is a library implementing an interface fo...
libwebp:x64-windows                                1.1.0            WebP codec: library to encode and decode images ...
libwebp[nearlossless]:x64-windows                                   Enable near-lossless encoding
libwebp[simd]:x64-windows                                           Enable any SIMD optimization.
libwebp[unicode]:x64-windows                                        Build Unicode executables. (Adds definition UNIC...
nlohmann-json:x64-windows                          3.7.3            JSON for Modern C++
opencv4:x64-windows                                4.1.1-3          computer vision library
opencv4[contrib]:x64-windows                                        opencv_contrib module
opencv4[dnn]:x64-windows                                            Enable dnn module
opencv4[jpeg]:x64-windows                                           JPEG support for opencv
opencv4[opengl]:x64-windows                                         opengl support for opencv
opencv4[png]:x64-windows                                            PNG support for opencv
opencv4[tiff]:x64-windows                                           TIFF support for opencv
opencv4[webp]:x64-windows                                           WebP support for opencv
opencv:x64-windows                                 4.1.1-1          Computer vision library
opencv[contrib]:x64-windows                                         opencv_contrib module
opencv[dnn]:x64-windows                                             Enable dnn module
opencv[jpeg]:x64-windows                                            JPEG support for opencv
opencv[opengl]:x64-windows                                          opengl support for opencv
opencv[png]:x64-windows                                             PNG support for opencv
opencv[tiff]:x64-windows                                            TIFF support for opencv
opencv[webp]:x64-windows                                            WebP support for opencv
opengl:x64-windows                                 0.0-5            Open Graphics Library (OpenGL)[3][4][5] is a cro...
protobuf:x64-windows                               3.11.3           Protocol Buffers - Google's data interchange format
sdl2:x64-mingw                                     2.0.10-3         Simple DirectMedia Layer is a cross-platform dev...
sdl2:x64-windows                                   2.0.10-3         Simple DirectMedia Layer is a cross-platform dev...
szip:x64-mingw                                     2.1.1-6          Szip compression software, providing lossless co...
szip:x64-windows                                   2.1.1-6          Szip compression software, providing lossless co...
tiff:x64-windows                                   4.0.10-8         A library that supports the manipulation of TIFF...
zlib:x64-mingw                                     1.2.11-6         A compression library
zlib:x64-windows                                   1.2.11-6         A compression library
`

**Comment by NancyLi1013** [comment]
Hi @guidebee 
Thanks for posting this issue.
Could you please help confirm if you install them with `powershell` and also have run `.\vcpkg integrate install` before building?

**Comment by NancyLi1013** [comment]
@guidebee 
Please let me know if you still have any concern about this.

**Comment by NancyLi1013** [comment]
Closing this issue due to no response.
Please feel free to reopen this if it is still a problem for you.
