### ISSUE TITLE
Visual Studio cannot find headers for static x64 cpprestsdk built with vcpkg

### ISSUE THREAD

**Issue by NoAndWhere** [microsoft/vcpkg#10836]
**Issue**
If I build a static x64 version of cpprestsdk with vcpkg, the headers are not found in a Visual Studio project (i.e. typing “#include <>” will not show “cpprest” in the popup list; applicaitons built with "#include <cpprest/http_client.h>" will not find the header.). The shared (DLL) version does not have this problem.

**Expected behavior**
When using a static version of cpprestsdk with vcpkg, I should be able to type “#include <>” and find “cpprest” in the popup list; applications built with "#include <cpprest/http_client.h>" should find the header.

**Environment**
Windows 10 v1903 Build 18362.657, x64
Visual Studio Enterprise 2019, Version 16.5.3
Platform Toolset v142
Windows SDK v10.0.10941.0

**Visual Studio Project Properties**
Configuration: Release
Platform: x64
Runtime Library: Multi-threaded (/MT)

**Steps to Reproduce**
- Install vcpkg v2020.01.31 plus all commits since – “bootstrap-vcpkg.bat”- successful.

- Integrate vcpkg with Visual Studio – “vcpkg integrate install” – successful:
    Applied user-wide integration for this vcpkg root.
    All MSBuild C++ projects can now #include any installed libraries.
    Linking will be handled automatically.
    Installing new libraries will make them instantly available.
    CMake projects should use: "-DCMAKE_TOOLCHAIN_FILE=C:/Program Files (x86)/vcpkg-
    master/scripts/buildsystems/vcpkg.cmake"

- Install x64 static CPPRESTSDK v2.10.15 – “vcpkg install cpprestsdk --triplet x64-windows-static" – successful:
    The package cpprestsdk:x64-windows-static provides CMake targets:
    find_package(cpprestsdk CONFIG REQUIRED)
    target_link_libraries(main PRIVATE cpprestsdk::cpprest
    cpprestsdk::cpprestsdk_zlib_internal cpprestsdk::cpprestsdk_brotli_internal)

- Create a new console application in Visual Studio with the same **Visual Studio Project Properties**.

- Put "#include <cpprest/http_client.h>" in the application header file.

- Attempt to build the project; <cpprest/http_client.h> will not be found.

**Workaround**
- Install x64 dynamic CPPRESTSDK v2.10.15 – “vcpkg install cpprestsdk --triplet x64-windows" – successful:
    The package cpprestsdk:x64-windows provides CMake targets:
    find_package(cpprestsdk CONFIG REQUIRED)
    target_link_libraries(main PRIVATE cpprestsdk::cpprest
    cpprestsdk::cpprestsdk_zlib_internal cpprestsdk::cpprestsdk_brotli_internal)

- Add the following to the application header file:
    #define _NO_ASYNCRTIMP
    #pragma comment(lib,"bcrypt.lib")
    #pragma comment(lib,"crypt32.lib")
    #pragma comment(lib,"winhttp.lib")

- Add the following to the "Globals" section of the application's .vcxproj file:
    \<VcpkgTriplet Condition="'$(Platform)'=='x64'"\>x64-windows-static\</VcpkgTriplet\>

- Changed contents of CPPRESTSDK lib folders in VCPKG:
    - Renamed "packages\cpprestsdk_x64-windows\debug\lib\cpprest_2_10d.lib" to "packages\cpprestsdk_x64-windows\debug\lib\cpprest_2_10d.lib-dll version"
    - Renamed "packages\cpprestsdk_x64-windows\lib\cpprest_2_10.lib" to "packages\cpprestsdk_x64-windows\lib\cpprest_2_10.lib-dll version"
    - Copied "packages\cpprestsdk_x64-windows-static\debug\lib\cpprest_2_10d.lib" to "packages\cpprestsdk_x64-windows\debug\lib\cpprest_2_10d.lib"
    - Copied "packages\cpprestsdk_x64-windows-static\lib\cpprest_2_10.lib" to "packages\cpprestsdk_x64-windows\lib\cpprest_2_10.lib"

I have dug around a bit in both vcpkg and cpprestsdk files to try and understand how the integration with Visual Studio works and find an explanation. Alas, I have come up empty-handed. Can someone please provide me the clue I must be missing?

**Comment by Neumann-A** [comment]
Need to set `VcpkgTriplet` to `x64-windows-static` in your VS Solution via a `*.props` file or similar. Else it always defaults to `x64-windows`.
From (scripts/buildsystems/msbuild/vcpkg.targets):
```
  <PropertyGroup Condition="'$(Platform)|$(ApplicationType)|$(ApplicationTypeRevision)' == 'x64||'">
    <VcpkgEnabled Condition="'$(VcpkgEnabled)' == ''">true</VcpkgEnabled>
    <VcpkgTriplet Condition="'$(VcpkgTriplet)' == ''">x64-windows</VcpkgTriplet>
  </PropertyGroup>
```

**Comment by JackBoosY** [comment]
Please see [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/users/integration.md#with-msbuild).

**Comment by NoAndWhere** [comment]
From what I wrote above (\ added so it appears correctly):

Add the following to the "Globals" section of the application's .vcxproj file:
\<VcpkgTriplet Condition="'$(Platform)'=='x64'"\>x64-windows-static\</VcpkgTriplet\>

**Comment by NoAndWhere** [comment]
I think something in my vcpkg installation was borked. I just wiped and rebuilt, and the headers show up correctly now. The .vcxproj requirement is still present (as stated in the documentation) as are the changes to the header file.
