### ISSUE TITLE
openssl-windows:x86-windows build failure

### ISSUE THREAD

**Issue by baocean** [microsoft/vcpkg#10839]
**Host Environment**
- OS: Windows 10
- Compiler: Visual Studio 2019
windows sdk 10.0.18362.0

**To Reproduce**
> vcpkg  install --triplet x86-windows openssl 

or 

> vcpkg  install --triplet x64-windows openssl 

**Failure logs** 
```
	"D:\vcpkg-2020.01\downloads\tools\perl\perl\bin\perl.exe" "-I." -Mconfigdata "util\dofile.pl"  "-omakefile" "crypto\include\internal\bn_conf.h.in" > crypto\include\internal\bn_conf.h
	"D:\vcpkg-2020.01\downloads\tools\perl\perl\bin\perl.exe" "-I." -Mconfigdata "util\dofile.pl"  "-omakefile" "crypto\include\internal\dso_conf.h.in" > crypto\include\internal\dso_conf.h
	"D:\vcpkg-2020.01\downloads\tools\perl\perl\bin\perl.exe" "-I." -Mconfigdata "util\dofile.pl"  "-omakefile" "include\openssl\opensslconf.h.in" > include\openssl\opensslconf.h
	D:\vcpkg-2020.01\downloads\tools\jom\jom-1.1.3\jom.exe /kj8 depend && D:\vcpkg-2020.01\downloads\tools\jom\jom-1.1.3\jom.exe /kj8 _all
	cl  /Zi /Fdossl_static.pdb /Gs0 /GF /Gy /MD /W3 /wd4090 /nologo /O2 /WX -utf-8 -FS /I "." /I "include" -D"L_ENDIAN" -D"OPENSSL_PIC" -D"OPENSSL_CPUID_OBJ" -D"OPENSSL_BN_ASM_PART_WORDS" -D"OPENSSL_IA32_SSE2" -D"OPENSSL_BN_ASM_MONT" -D"OPENSSL_BN_ASM_GF2m" -D"SHA1_ASM" -D"SHA256_ASM" -D"SHA512_ASM" -D"RC4_ASM" -D"MD5_ASM" -D"RMD160_ASM" -D"VPAES_ASM" -D"WHIRLPOOL_ASM" -D"GHASH_ASM" -D"ECP_NISTZ256_ASM" -D"POLY1305_ASM" -D"OPENSSLDIR=\"D:\\vcpkg-2020.01\\packages\\openssl-windows_x86-windows\"" -D"ENGINESDIR=\"D:\\vcpkg-2020.01\\packages\\openssl-windows_x86-windows\\lib\\engines-1_1\"" -D"OPENSSL_SYS_WIN32" -D"WIN32_LEAN_AND_MEAN" -D"UNICODE" -D"_UNICODE" -D"_CRT_SECURE_NO_DEPRECATE" -D"_WINSOCK_DEPRECATED_NO_WARNINGS" -D"OPENSSL_USE_APPLINK" -D"NDEBUG"  -c /Foapps\app_rand.obj "apps\app_rand.c"
app_rand.c
	cl  /Zi /Fdossl_static.pdb /Gs0 /GF /Gy /MD /W3 /wd4090 /nologo /O2 /WX -utf-8 -FS /I "." /I "include" -D"L_ENDIAN" -D"OPENSSL_PIC" -D"OPENSSL_CPUID_OBJ" -D"OPENSSL_BN_ASM_PART_WORDS" -D"OPENSSL_IA32_SSE2" -D"OPENSSL_BN_ASM_MONT" -D"OPENSSL_BN_ASM_GF2m" -D"SHA1_ASM" -D"SHA256_ASM" -D"SHA512_ASM" -D"RC4_ASM" -D"MD5_ASM" -D"RMD160_ASM" -D"VPAES_ASM" -D"WHIRLPOOL_ASM" -D"GHASH_ASM" -D"ECP_NISTZ256_ASM" -D"POLY1305_ASM" -D"OPENSSLDIR=\"D:\\vcpkg-2020.01\\packages\\openssl-windows_x86-windows\"" -D"ENGINESDIR=\"D:\\vcpkg-2020.01\\packages\\openssl-windows_x86-windows\\lib\\engines-1_1\"" -D"OPENSSL_SYS_WIN32" -D"WIN32_LEAN_AND_MEAN" -D"UNICODE" -D"_UNICODE" -D"_CRT_SECURE_NO_DEPRECATE" -D"_WINSOCK_DEPRECATED_NO_WARNINGS" -D"OPENSSL_USE_APPLINK" -D"NDEBUG"  -c /Foapps\s_socket.obj "apps\s_socket.c"
s_socket.c
apps\s_socket.c(11): fatal error C1083: Cannot open include file: 'stdio.h': No such file or directory
D:\vcpkg-2020.01\buildtrees\openssl-windows\x86-windows-rel\include\openssl/crypto.h(14): fatal error C1083: Cannot open include file: 'stdlib.h': No such file or directory
```
**Additional context**
I would like to mention that of course all headers exist.
_C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt_

And I couldn't find how to help vcpkg to specify them.

**Comment by Cheney-W** [comment]
@baocean Thanks for reporting this issue!
Please do as below:
1. Open a normal CMD window.
2. "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\VsDevCmd.bat"
3. Run set include.
4. Please check if the following paths exist in the value of INCLUDE:
`C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt`
`C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared`
`C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um`
`C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt`
`C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt`

**Comment by baocean** [comment]
Hello Cheney

Thank you for the reply!
After I run 
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat"

INCLUDE environment variable contains following
INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.25.28610\ATLMFC\include;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.25.28610\include;

No windows sdk pathes. However windows SDK was installed in normal way using visutal studio installer and all include files are there.
C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0

**Comment by Cheney-W** [comment]
@baocean 
Could you find `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Microsoft SDKs\Windows\v10.0` in your Registry Editor?
The detail of this item as below:
![image](https://user-images.githubusercontent.com/38240633/79526061-06292c00-8097-11ea-9c60-91eb8e347711.png)
If you don‘t have this item, you can manually add it to the registry. 
VsDevCmd.bat will call winsdk.bat to set the environment of Windows SDK, and winsdk.bat uses the value in the registry to determine the path and version of the current Windows SDK.

**Comment by baocean** [comment]
Hello

I identified that from windows policy an access to registry is disabled. 
After I solved that issue everything was fine.
Thank you very much!
