### ISSUE TITLE
[New Port Request] OpenSubdiv

### ISSUE THREAD

**Issue by shauser67** [microsoft/vcpkg#10837]
Library name: OpenSubdiv

Library description: Library for high performance subdivision surface (subdiv) evaluation

Source repository URL: https://github.com/PixarAnimationStudios/OpenSubdiv

Project homepage (if different from the source repository): http://graphics.pixar.com/opensubdiv/docs/intro.html

Anything else that is useful to know when adding (such as optional features the library may have that should be included): n/a

**Comment by NancyLi1013** [comment]
Hi @shauser67 
Thanks for posting this request.
`OpenSubdiv` has been mentioned to this issue #5310. 
So I'm going to close this issue due to duplication.
