### ISSUE TITLE
Annoying and scary behavior from Visual Studio

### ISSUE THREAD

**Issue by vinniefalco** [Microsoft/vcpkg#1084]
It was bad enough that when I upgraded to Visual Studio 2017, these unwanted lines began appearing in my IDE Output Window interspersed with the "normal" output such as the name of the translation unit being compiled (lines have been truncated for clarity)
```
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\bin\HostX86\x86\CL.exe /c ...
...
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\bin\HostX86\x86\CL.exe /c /IC:\Use...
...
4>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\bin\HostX86\x86\CL.exe /c /IC...
```

These lines are annoying because in Visual Studio 2015 I could just press F4 to go to the source file containing the first error in the compilation. But in Visual Studio 2017 when I press F4 it highlights these useless lines which just repeat the command line used to build, which I did not ask for and which I cannot figure out how to suppress.

But now that I have "installed" vcpkg, the behavior of Visual Studio has changed in a mysterious way. I am now seeing these unwanted lines in my output in addition to the previously described unwanted lines:
```
5>powershell.exe -ExecutionPolicy Bypass -noprofile -File...
...
6>powershell.exe -ExecutionPolicy Bypass -noprofile ..."C:\Users\vinnie\src\vcpkg\installed\x86-windows\debug\bin" ...
...
6>powershell.exe -ExecutionPolicy Bypass -noprofile -File "C:\Users\vinnie\src\vcpkg\scripts\buildsystems\msbuild\applocal.ps1" 
```

What concerns me about these new unwanted lines is that unlike the old unwanted lines, which appeared to be merely informational and obstructive, these new unwanted Output Window lines imply that something has happened to my build environment which could possibly change the way that my programs are being compiled, in a way that I cannot audit or troubleshoot. I just reported an issue where my previously-working .vcxproj projects can now no longer build that I have used vcpkg to install libraries that these previously-working .vcxproj were using (which were in a different, manually built and installed location).

How can I get my build environment back to the way it was before I ever touched vcpkg, and can I introduce vcpkg back on to my system in a way that will not compromise the setting of my build environment? I have published a port in the vcpkg repository (Beast) and it seems I need the vcpkg tool in order to generate this SHA512 digest, over what - I do not know, I cannot find any documentation on what data the digest is calculated on. And I need this SHA512 digest in order to update Beast from **1.0.0-b30** which is currently the latest in the port, to the current version of Beast which is **v40**.

**Comment by vinniefalco** [comment]
It looks like  `vcpkg integrate remove` solved this problem. I would love advice on how to stop Visual Studio 2017 from echoing the command lines it is using during a build, but that's not a vcpkg specific problem.

**Comment by ras0219-msft** [comment]
To perhaps remove some of the mystery: Those PowerShell commands are added as a post-build action for executables (as part of `integrate install`) to automatically copy library dependencies out of vcpkg into your output folder.

Rest assured that integrate remove will completely remove it 😊.

**Comment by vinniefalco** [comment]
Are the APIs which *vcpkg* uses to covertly alter the behavior of Visual Studio public? In other words could another package manager take advantage of these APIs to make include directories and libraries available? Also, are there any ways of observing these behavioral changes in the IDE GUI? For example, a dialog that produces a list of "integrations" or external applications which have access (like vcpkg)?

**Comment by ras0219-msft** [comment]
For vs2015, we add a file into the msbuild installation directly (this is what requires administrator access). This mechanism is also used by intel's MKL SDK, I believe. In 2017, we added support in the box to avoid the need for administrator access on first install, however the 2015 mechanism still exists.

However, this extension point sees overall very little use (and for good reason -- it has the potential to interfere with every build, and so needs a level of quality control and issue responsiveness that isn't reasonable for many projects).

You can see exactly what we do inside our sources (the `toolsrc\` folder).
