### ISSUE TITLE
[glib] Configuration specific flags are not passed to configure script

### ISSUE THREAD

**Issue by emptyVoid** [microsoft/vcpkg#10853]
**Describe the bug**
Arguments passed in the wrong order:
https://github.com/microsoft/vcpkg/blob/c5f01e1dee0d41b8014ac6f1eeafda974917ba17/ports/glib/CMakeLists.txt#L76

**Environment**
- OS: non-Windows

**Expected behavior**
Should be:
```cmake
    string(TOUPPER "${CMAKE_BUILD_TYPE}" UPPER_CONFIG)
```

**Additional context**
[See docs](https://cmake.org/cmake/help/v3.17/command/string.html#toupper)

**Comment by NancyLi1013** [comment]
Hi @emptyVoid 
Thanks for posting this issue.
I will make a PR to fix this.

**Comment by NancyLi1013** [comment]
This issue has been fixed now. Please try to update vcpkg and rebuild it.
