### ISSUE TITLE
How do I build all required Windows Libraries with ITERATOR_DEBUG_LEVEL=0 (in debug)

### ISSUE THREAD

**Issue by invy** [microsoft/vcpkg#10857]
How to do it? Is there the way to control it via triplet? What runtime should I link against in this case?
Or I shouldn't do it at all, because I'm looking for trouble?

**Comment by Voskrese** [comment]
LEVEL=0 ?

**Comment by Neumann-A** [comment]
You could try 
`set(ENV{_CL_} "/D_ITERATOR_DEBUG_LEBEL=0")`
or 
`set(VCPKG_C_FLAGS_DEBUG "/D_ITERATOR_DEBUG_LEBEL=0")`
`set(VCPKG_CXX_FLAGS_DEBUG "/D_ITERATOR_DEBUG_LEBEL=0")`
in the triplet. 

But it is probably not consistent across all ports.

**Comment by invy** [comment]
> But it is probably not consistent across all ports.
@Neumann-A yes, this is what bothers me either.
The following question would be: how to I verify, that ports have been build consistently. Ootherwise it could end up in a disaster, because inconsistency could be notices only in some cases and only after some surprise segfaults.

**Comment by Neumann-A** [comment]
@invy: You can check the debug build logs if the flag is in the cl call. Isn't it considered a feature in MS STL that libraries build with different _ITERATOR_DEBUG_LEVEL won't link due to the famous linker error. Here is just one example: https://github.com/conan-io/conan/issues/1341

**Comment by invy** [comment]
@Neumann-A they won't if you link statically, but dynamically everything would link fine.

**Comment by JackBoosY** [comment]
I think you should set it into [here](https://github.com/microsoft/vcpkg/tree/master/scripts/toolchains).

**Comment by Voskrese** [comment]
https://github.com/microsoft/vcpkg/blob/b12256a4af4e77e1ae87bbf76c1c3a654cdcd1a2/scripts/buildsystems/vcpkg.cmake#L18

example
...\vcpkg\buildtrees\berkeleydb\src

`touch vcpkg.config.cmake`

add 
https://github.com/microsoft/vcpkg/issues/10857#issuecomment-614602769

or add

```
        if(VCPKG_TARGET_ARCHITECTURE STREQUAL "x86")
          add_definitions(-D_X86_=1)
#          set(ARCH_32BITS 1)
#          add_definitions(-Di386=1)
#          add_definitions(-D_M_X86)
        elseif(VCPKG_TARGET_ARCHITECTURE STREQUAL "x64")
          add_definitions("-D_WIN64")
#          set(ARCH_64BITS 1)
#          add_definitions(-D_AMD64_)
#          add_definitions(-DAMD64)    
#          add_definitions(-D_M_X64)
    
#          add_compile_definitions(" -DINTEGER8 -D_FILE_OFFSET_BITS=64")
          add_definitions("-DINTEGER8 -D_FILE_OFFSET_BITS=64")
          list(APPEND CMAKE_Fortran_FLAGS "-fdefault-integer-8")
          string(REPLACE "\\;" "" CMAKE_Fortran_FLAGS ${CMAKE_Fortran_FLAGS})
        else()
          message(FATAL_ERROR "Unsupported architecture")
        endif()
```

more ... only CURRENT project

**Comment by invy** [comment]
@JackBoosY this looks good.
Will toolchain settings also affect libraries built with msbuild and automake?

**Comment by Neumann-A** [comment]
>I think you should set it into here.

The correct way to do it use a custom triplet and specific a toolchain via `VCPKG_CHAINLOAD_TOOLCHAIN_FILE`

https://vcpkg.readthedocs.io/en/latest/users/triplets/

**Comment by invy** [comment]
@Neumann-A great!
It would be cool if I also could somehow add a custom linter :)

**Comment by JackBoosY** [comment]
@invy Does this issue solved?

**Comment by JackBoosY** [comment]
Please reopen this issue if it still bother you.
