### ISSUE TITLE
[New Port Request]  apr2

### ISSUE THREAD

**Issue by pengliaoye** [microsoft/vcpkg#10852]
Library name:

apr

Library description:

Apache  Portable Runtime

Source repository URL:

APR 2.0 (development version, incorporating both APR and APR-UTIL from earlier versions):
svn co https://svn.apache.org/repos/asf/apr/apr/trunk/ apr

Project homepage (if different from the source repository):

http://apr.apache.org/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

optional DBM and DBD libraries supported

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by pengliaoye** [comment]
hi, can you build this
