### ISSUE TITLE
[New Port Request] ruby

### ISSUE THREAD

**Issue by traversaro** [microsoft/vcpkg#10855]
Library name: ruby

Library description: ruby interpreter

Source repository URL: https://github.com/ruby/ruby

Project homepage (if different from the source repository): https://www.ruby-lang.org

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

As done for Python in https://github.com/microsoft/vcpkg/blob/2020.01/ports/python3/portfile.cmake, it would be great to have a port that builds the ruby interpreter so that it can be used as a library. 

Note that to build ruby for Visual Studio on Windows (that is different from the mingw compiler used to distribute the official binary of Ruby on Windows, and used for most binary extension available in RubyGems) it is necessary to follow the instructions in https://github.com/ruby/ruby/blob/master/win32/README.win32 .

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
