### ISSUE TITLE
[cgal] build failure missing dependency to boost-interval

### ISSUE THREAD

**Issue by gjaegy** [microsoft/vcpkg#10861]
**Host Environment**
- OS: Windows
- Compiler: VS2019

**To Reproduce**
`./vcpkg install cgal`

**Failure logs** 
missing dependency boost-interval (see #include <boost/numeric/interval.hpp> line in installed\x64-windows\include\CGAL\Algebraic_kernel_d\Interval_evaluate_1.h).

**Additional context**

**Comment by LilyWangL** [comment]
Thanks for posting this issue. I installed `cagal:x64-windows` successfully locally. Could you please provide the all error log? You can attach the log file on this page.

**Comment by gjaegy** [comment]
Hi, thanks for your answer.

It's not "Cagal", it's "CGAL" `(cgal:x64-windows`)

Although, as I said, one can install CGAL since it's a header only library, however, when including in your project, you'll get a missing include (mentioned in my first post), which is included in `boost-interval` (so boost-interval should be added as dependency of CGAL).

**Comment by LilyWangL** [comment]
It's my fault, this should be `cgal:x64-windows`. I will fix this issue soon.

**Comment by LilyWangL** [comment]
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.
