### ISSUE TITLE
reprint the cmake usage when `vcpkg install` an existing lib

### ISSUE THREAD

**Issue by rockonedege** [microsoft/vcpkg#10860]
****
I always find it valuble at the end of installing a library something like this shows up

```sh
The package mongo-c-driver is compatible with built-in CMake targets:

        find_package(mongo-c-driver CONFIG REQUIRED)
        target_include_directories(${project} PRIVATE ${MONGOC_INCLUDE_DIRS})

For use dynamic library:
        target_link_libraries(${project} PRIVATE ${MONGOC_LIBRARIES})
For use static library:
        target_link_libraries(${project} PRIVATE ${MONGOC_STATIC_LIBRARY})
  
        
```

However, there's no way to bring it up again afterwards that I know of.

**Is your feature request related to a problem? Please describe.**
No.

**Proposed solution**

I am hoping there is a way, either by a new command or at every `vcpkg install <lib>` even when `<lib>` was installed already

**Describe alternatives you've considered**

text search in the /vcpkg folder

**Additional context**

**Comment by timautry** [comment]
I have always used "_**vcpkg install < port >**_"  to get the information again.

**Comment by NancyLi1013** [comment]
Hi @rockonedege 
Thanks for posting this issue.
It seems that we need to add the usages to vcpkg folder, which can make them easy to be found.
Currently, some ports has implemented to add the usages to ports/libName/usage.

For example:
https://github.com/microsoft/vcpkg/tree/master/ports/ignition-cmake2/usage
https://github.com/microsoft/vcpkg/blob/master/ports/xeus/usage
https://github.com/microsoft/vcpkg/blob/master/ports/libhdfs3/usage

**Comment by Farwaykorse** [comment]
> I always find it valuble at the end of installing a library something like this shows up
> [...]
> I am hoping there is a way, either by a new command or at every `vcpkg install <lib>` even when `<lib>` was installed already
> 
Actually, like @timautry said, just running `vcpkg install <port>` does show this message again.

````PowerShell
$ vcpkg install ms-gsl:x64-windows
Computing installation plan...
The following packages are already installed:
    ms-gsl[core]:x64-windows
Package ms-gsl:x64-windows is already installed

Total elapsed time: 7.939 ms

The package ms-gsl:x64-windows provides CMake targets:

    find_package(Microsoft.GSL CONFIG REQUIRED)
    target_link_libraries(main PRIVATE Microsoft.GSL::GSL)
````

**Comment by rockonedege** [comment]
Thanks. It looks I was confused, as some packages do  others don't.

**Comment by NancyLi1013** [comment]
Hi all,

Thanks for joining the discussion about this issue.

Currently, there are two ways to get the usage info:

One way is the usage file in the packge, another way is by reading the cmake config files.
Since when we want to improve or change the message, it isn't possible to update them into the files immediately.

But based on the above situation you encountered, we will consider to add the usages to the ports that users ask for requirement.

**Comment by NancyLi1013** [comment]
@rockonedege and @Farwaykorse 
Could you please help list the ports that you want to add the usage info?

**Comment by rockonedege** [comment]
I'd like it to be a standard feature for all packages. in the mean time, the most notable missing for me 
are 
- boost
- mongo-cxx-driver
- mongo-c-driver(this one works after I submitted issue ticket, but it generates warnings saying vcpkg is use a deprecated way of importing)

**Comment by NancyLi1013** [comment]
@rockonedege 
Thanks for your above info.
Currently, there is no plan for all packages. we can only add the usage info for these ports that you require.

**Comment by wildmichael** [comment]
When in manifest mode, `vcpkg` never reveals the usage information. A simple `vcpkg usage <port>` command would be great for this use-case.

**Comment by PhoebeHui** [comment]
boost and mongo-c-driver has usage file, for mongo-cxx-driver, since it doesn't provide any cmake config and targets file, so it doesn't print any usage information. For manifest mode issue, we would use https://github.com/microsoft/vcpkg/issues/12290 to track the status.
