### ISSUE TITLE
[SDL2] build failure

### ISSUE THREAD

**Issue by aspioupiou** [microsoft/vcpkg#10862]
**Host Environment**
- OS: Linux
- Compiler: gcc 9.2

**To Reproduce**
./vcpkg install SDL2 --head

```
vcpkg/buildtrees/sdl2/src/ase-2.0.10-c1be3add38/src/audio/sndio/SDL_sndioaudio.c:95: undefined reference to `sio_open'
vcpkg/buildtrees/sdl2/src/ase-2.0.10-c1be3add38/src/audio/sndio/SDL_sndioaudio.c:96: undefined reference to `sio_close'
vcpkg/buildtrees/sdl2/src/ase-2.0.10-c1be3add38/src/audio/sndio/SDL_sndioaudio.c:97: undefined reference to `sio_setpar'
vcpkg/buildtrees/sdl2/src/ase-2.0.10-c1be3add38/src/audio/sndio/SDL_sndioaudio.c:98: undefined reference to `sio_getpar'
vcpkg/buildtrees/sdl2/src/ase-2.0.10-c1be3add38/src/audio/sndio/SDL_sndioaudio.c:99: undefined reference to `sio_start'
vcpkg/buildtrees/sdl2/src/ase-2.0.10-c1be3add38/src/audio/sndio/SDL_sndioaudio.c:100: undefined reference to `sio_stop'
vcpkg/buildtrees/sdl2/src/ase-2.0.10-c1be3add38/src/audio/sndio/SDL_sndioaudio.c:101: undefined reference to `sio_read'
vcpkg/buildtrees/sdl2/src/ase-2.0.10-c1be3add38/src/audio/sndio/SDL_sndioaudio.c:102: undefined reference to `sio_write'
vcpkg/buildtrees/sdl2/src/ase-2.0.10-c1be3add38/src/audio/sndio/SDL_sndioaudio.c:103: undefined reference to `sio_nfds'
vcpkg/buildtrees/sdl2/src/ase-2.0.10-c1be3add38/src/audio/sndio/SDL_sndioaudio.c:104: undefined reference to `sio_pollfd'
vcpkg/buildtrees/sdl2/src/ase-2.0.10-c1be3add38/src/audio/sndio/SDL_sndioaudio.c:105: undefined reference to `sio_revents'
vcpkg/buildtrees/sdl2/src/ase-2.0.10-c1be3add38/src/audio/sndio/SDL_sndioaudio.c:106: undefined reference to `sio_eof'
vcpkg/buildtrees/sdl2/src/ase-2.0.10-c1be3add38/src/audio/sndio/SDL_sndioaudio.c:107: undefined reference to `sio_initpar'
````

**Comment by NancyLi1013** [comment]
Hi @aspioupiou 
Thanks for posting this issue.
It seems that you used `SDL2`old version.
`SDL2 `has been updated to 2.0.12.
I can install it successfully on my local.
Could you please try to update vcpkg and rebuild `SDL2`?

**Comment by aspioupiou** [comment]
hi @NancyLi1013 
Thanks for your feedback

I've tested both and we had the same problem. I forgot to mention I don't explicitly install sdl2, it is automatically done by installing `magnum` package.

In either case, it does not happen when building the package, but when linking to it.
**statically*

I've found out that manually linking to `sndio` after linking to SDL2 solves the issue (`target_link_libraries(myApp, .... sndio)`)

I hope this helps

Cheers

**Comment by NancyLi1013** [comment]
Could you please provide the steps to reproduce and the failure log?
Before building this, please make sure you have updated vcpkg to the latest version.

Thanks.

**Comment by aspioupiou** [comment]
Hi Nancy, 

I'm sorry for the late reply.

Here are the steps to reproduce. Using Ubuntu 18.04.1 with latest vcpkg : 
- Install the packages `corrade, magnum[glxcontext], magnum[windowlessglxapplication], magnum-gles[opengltester], magnum-plugins-gles[assimpimporter,jpegimporter, pngimporter], magnum-integration-gles[imgui]`
- then `find_packages(Magnum REQUIRED Sdl2Application)  `
- Finally `target_link_libraries( my_app Magnum::Sdl2Application)

Doing so will build successfully the packages. Project won't build however. The linker won't find sndio which must be manually linked by adding `target_link_libraries(my_app sndio)`

Hopefully you can reproduce, Don't hesitate to ping me if you can't so I can help you

All the best

**Comment by NancyLi1013** [comment]
Thanks for your update.
I will try to reproduce this on my machine.

**Comment by NancyLi1013** [comment]
These ports seems not exist in vcpng now.
`magnum-gles, magnum-plugins-gles, magnum-integration-gles`.

**Comment by aspioupiou** [comment]
I'm sorry @NancyLi1013, these are the wrong port name. You should use  `magnum, magnum-plugins, magnum-integration`

**Comment by NancyLi1013** [comment]
Could you please provide your project case? 
I installed these ports `magnum, magnum-plugins, magnum-integration`.
Then create a simple cmake project to build this on gcc version 9.2.1 20191102 (Ubuntu 9.2.1-17ubuntu1~18.04.1)
and there is no any error.
This is my CMakeLists.txt:
```
cmake_minimum_required(VERSION 3.14)
project(test)
find_package(Magnum CONFIG REQUIRED Sdl2Application)
add_executable(main main.cpp)
target_link_libraries(main PRIVATE Magnum::Sdl2Application)

```

**Comment by aspioupiou** [comment]
Hum, did you use `--head` ? On standard release it works IIRC

**Comment by NancyLi1013** [comment]
Sorry, I forgot to add` --head`.

But since you used `--head`, it meant that you used the latest source code instead of the version  that vcpkg maintained.

So we cannot make sure if the latest version in upstream can work.

If you want to use the latest code, it might be better to bring up an issue in upstream.

**Comment by aspioupiou** [comment]
Ok ! Thank you for your feedback @NancyLi1013 !

**Comment by NancyLi1013** [comment]
Please open a new issue if you encounter the problem after updating to the new version in vcpkg.
