### ISSUE TITLE
README.md build badge is the Road To Nowhere

### ISSUE THREAD

**Issue by vinniefalco** [Microsoft/vcpkg#1087]
Clicking on the build badge on the README.md doesn't bring you to the continuous integration site, it just takes you to the image by itself on a page.

**Comment by ras0219-msft** [comment]
We currently use VSTS for our CI, which is unfortunately not publicly accessible. We do hope to improve this situation in the future!

**Comment by KindDragon** [comment]
Remove link for README.md than

**Comment by vinniefalco** [comment]
Consider, rather than switching CI services, simply **adding** services! They are free, and **vcpkg** is open source. For example http://appveyor.com Badges are like Pokemon, gotta catch them all! Projects with more badges are obviously of higher quality :)

See: 
![image](https://cloud.githubusercontent.com/assets/1503976/26013465/686c7db2-370d-11e7-9c5f-98fd3f0afe67.png)

**Comment by vinniefalco** [comment]
Should we close this?

**Comment by ras0219-msft** [comment]
Yeah, I think the primary issue is resolved.

We are interested in improving the CI system when we can, though there are some constraints that make it difficult 😊. Thanks for posting them though!

**Comment by jasjuang** [comment]
+1 for AppVeyor
