### ISSUE TITLE
[New Port Request] npcap

### ISSUE THREAD

**Issue by traversaro** [microsoft/vcpkg#10873]
Library name: npcap

Library description: Packet capture library for Windows

Source repository URL: https://github.com/nmap/npcap

Project homepage (if different from the source repository): https://nmap.org/npcap/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

Related comment:  https://github.com/microsoft/vcpkg/pull/10731#issuecomment-614938011

**Comment by guyharris** [comment]
Unlike WinPcap, Npcap is 1) currently being developed and maintained and 2) is based on a reasonably up-to-date version of libpcap.

**Comment by desowin** [comment]
Note that to get kernel driver that works on Windows without TESTSIGNING enabled, Kernel-Mode Code Signing certificate is required. For Windows 10, also Attestation Signing is required which requires EV Kernel-Mode Code Signing and uploading the package to Microsoft Hardware Dev Center - which is pretty much impossible to do in vcpkg port IMHO.

As such, as far as the kernel driver goes, the only viable option for majority of users would be to use official releases.

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by traversaro** [comment]
> If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

As suggested also in other issues, probably to avoid confusion in the users if the policy of "leaving the new port request open for some time and then close it" would be written in a clear way somewhere. Furthermore, it would probably make sense to edit or clarify existing documentation (see https://docs.microsoft.com/en-us/cpp/build/vcpkg?view=vs-2019#contribute-new-libraries) that suggests that issues that request new ports are welcome. As a final suggestions, it is  now impossible to navigate new port requests that have not been solved, as both solved and unsolved new port requests are listed as Closed Issues with the `category:new-port` , so it would be great to have a specific label applied to new port request that are still unsolved.

**Comment by PhoebeHui** [comment]
Good point! @traversaro, thanks for bringing up this!
