### ISSUE TITLE
[glad] build failure

### ISSUE THREAD

**Issue by PriyanshJalan** [microsoft/vcpkg#10876]
**Host Environment**
- OS: [Windows 10]
- Compiler: VS 2019 16.5.4 ( C/C++ Optimizing Compiler Version 19.25.28614)

**To Reproduce**
Steps to reproduce the behaviour:
`./vcpkg install glad:x64-windows`

**Failure logs** 
- console log
PS C:\vcpkg> vcpkg install glad:x64-windows
Computing installation plan...
The following packages will be built and installed:
    glad[core]:x64-windows
Starting package 1/1: glad:x64-windows
Building package glad[core]:x64-windows...
-- Note: glad only supports static library linkage. Building static library.
-- Using cached C:/vcpkg/downloads/Dav1dde-glad-de6c39e3040c987323b8ed078c36442f4fb681b3.tar.gz
-- Using source at C:/vcpkg/buildtrees/glad/src/2f4fb681b3-78068df8f5
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v
    Working Directory: C:/vcpkg/buildtrees/glad/x64-windows-dbg
    See logs for more information:
      C:\vcpkg\buildtrees\glad\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/glad/portfile.cmake:39 (vcpkg_install_cmake)
  scripts/ports.cmake:90 (include)

Error: Building package glad:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: glad:x64-windows
  Vcpkg version: 2020.02.04-nohash

- log file
[1/4] cmd.exe /C "cd /D C:\vcpkg\buildtrees\glad\src\2f4fb681b3-78068df8f5 && C:\Windows\System32\python -m glad --profile=compatibility --out-path=C:/vcpkg/buildtrees/glad/x64-windows-dbg --api= --generator=c-debug --extensions= --spec=gl --reproducible"
FAILED: src/glad.c include/glad/glad.h 
cmd.exe /C "cd /D C:\vcpkg\buildtrees\glad\src\2f4fb681b3-78068df8f5 && C:\Windows\System32\python -m glad --profile=compatibility --out-path=C:/vcpkg/buildtrees/glad/x64-windows-dbg --api= --generator=c-debug --extensions= --spec=gl --reproducible"
'C:\Windows\System32\python' is not recognized as an internal or external command,
operable program or batch file.
ninja: build stopped: subcommand failed..

**Comment by LilyWangL** [comment]
@PriyanshJalan Thanks for posting this issue. Did you run `git pull` before building glad? I installed `glad:x64-windows` successfully with the latest VCPKG source.

**Comment by PriyanshJalan** [comment]
Yes! I did. I tried agin just to double check. 
- Console log - 
PS C:\vcpkg> git pull
Already up to date.
PS C:\vcpkg> vcpkg install glad:x64-windows
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
Computing installation plan...
The following packages will be built and installed:
    glad[core]:x64-windows
Starting package 1/1: glad:x64-windows
Building package glad[core]:x64-windows...
-- Note: glad only supports static library linkage. Building static library.
-- Using cached C:/vcpkg/downloads/Dav1dde-glad-de6c39e3040c987323b8ed078c36442f4fb681b3.tar.gz
-- Using source at C:/vcpkg/buildtrees/glad/src/2f4fb681b3-78068df8f5
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v
    Working Directory: C:/vcpkg/buildtrees/glad/x64-windows-dbg
    See logs for more information:
      C:\vcpkg\buildtrees\glad\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/glad/portfile.cmake:39 (vcpkg_install_cmake)
  scripts/ports.cmake:90 (include)


Error: Building package glad:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: glad:x64-windows
  Vcpkg version: 2020.02.04-nohash


- log file
[1/4] cmd.exe /C "cd /D C:\vcpkg\buildtrees\glad\src\2f4fb681b3-78068df8f5 && C:\Windows\System32\python -m glad --profile=compatibility --out-path=C:/vcpkg/buildtrees/glad/x64-windows-dbg --api= --generator=c-debug --extensions= --spec=gl --reproducible"
FAILED: src/glad.c include/glad/glad.h 
cmd.exe /C "cd /D C:\vcpkg\buildtrees\glad\src\2f4fb681b3-78068df8f5 && C:\Windows\System32\python -m glad --profile=compatibility --out-path=C:/vcpkg/buildtrees/glad/x64-windows-dbg --api= --generator=c-debug --extensions= --spec=gl --reproducible"
'C:\Windows\System32\python' is not recognized as an internal or external command,
operable program or batch file.
ninja: build stopped: subcommand failed.

**Comment by timautry** [comment]
I see the build is trying to execute python in the C:\Windows\System32 directory?
- normally vcpkg would execute python from `_<vcpkg-root>_\downloads\tools\python\python-_<version>_\python.exe`
- Is there an environment variable or a command line option being used to override the default location vcpkg is looking for python?

**Comment by PriyanshJalan** [comment]
Yes, indeed that was the problem.  I had an environment variable activated. 

My "where python" command gave the following paths  - 
C:\Users\XXXXX\Anaconda3\python.exe
C:\Windows\System32\python
C:\Users\XXXXX\AppData\Local\Microsoft\WindowsApps\python.exe

I had python installed through Anaconda and Microsoft Store. I  had recently uninstalled the Microsoft Store version but it had left an empty file "C:\Windows\System32\python". This led vcpkg to this installation of python and it could not use python to build glad:x64-windows.

Thanks for the help!

- Success Console Log
```
vcpkg install glad:x64-windows
Computing installation plan...
The following packages will be built and installed:
    glad[core]:x64-windows
Starting package 1/1: glad:x64-windows
Building package glad[core]:x64-windows...
-- Note: glad only supports static library linkage. Building static library.
-- Using cached C:/vcpkg/downloads/Dav1dde-glad-de6c39e3040c987323b8ed078c36442f4fb681b3.tar.gz
-- Using source at C:/vcpkg/buildtrees/glad/src/2f4fb681b3-78068df8f5
-- Downloading https://www.python.org/ftp/python/3.7.3/python-3.7.3-embed-amd64.zip...
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: C:/vcpkg/packages/glad_x64-windows/share/glad/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package glad[core]:x64-windows... done
Installing package glad[core]:x64-windows...
Installing package glad[core]:x64-windows... done
Elapsed time for package glad:x64-windows: 3.534 min

    Total elapsed time: 3.535 min

The package glad:x64-windows provides CMake targets:

    find_package(glad CONFIG REQUIRED)
    target_link_libraries(main PRIVATE glad::glad)
```

**Comment by timautry** [comment]
No problem. Glad it works now.
