### ISSUE TITLE
How do I upgrade some selected packages?

### ISSUE THREAD

**Issue by haquocviet** [microsoft/vcpkg#10877]
Hi all, 
When I have my custom port, if I do upgrade then packages in my custom port will get overwritten.
Is there any way to upgrade only packages in the main port or only packages in a custom port?
Or possible to upgrade some selected packages in one of ports?

**Comment by JackBoosY** [comment]
See #10674.

**Comment by haquocviet** [comment]
I think vcpkg should add more options to the "upgrade" command to support fine-grained demands.

Suppose I have installed lib1, lib2 and lib3. Note that lib3 is installed via a custom-port.	
In case I do not want to upgrade lib3 so I would to run a command like this:
	**vcpkg upgrade lib1:triplet, lib2:triplet --no-dry-run**	
or like this:
	**vcpkg upgrade --exclude=lib3:triplet --no-dry-run**
	
If I really want to upgrade lib3 I should run like this:
	**vcpkg upgrade --overlay-port=lib3:triplet --no-dry-run**

**Comment by traversaro** [comment]
This seems to also be (partially) related to  https://github.com/microsoft/vcpkg/issues/10119 and the new requirement of passing `--overlay-ports` with the used overlay ports for all commands (including also `upgrade` I guess).

**Comment by JackBoosY** [comment]
So, does this issue resolved?

**Comment by haquocviet** [comment]
Because there is no option to exclude specified packages from 'upgrade', I walked around the issue by clumsy way like this:
- run 'upgrade' all packages including ones in my ports get upgraded.
- run 'remove' unwanted upgraded packages corresponding to the ones in my ports.
- run 'install' packages in my ports again with --overlay-ports.

**Comment by JackBoosY** [comment]
For this feature, please track #10674.
