### ISSUE TITLE
vcpkg add legend next to each port feature as to what platform (OS and hardware) a feature is valid

### ISSUE THREAD

**Issue by timautry** [microsoft/vcpkg#10882]
****

**Is your feature request related to a problem? Please describe.**
Yes, not knowing a ports valid OS, hardware aka platform is valid for.
When the project first started out, all ports/features were for windows platform, but now we are including many flavors of linux, macosx, android, ios, etc.

**Proposed solution**
Some type of legend noting what platform a port and its features belongs too.

**Describe alternatives you've considered**
The only method now is trial and error or manually looking through the CI file.
Note: I believe all the information needed would be in the CI file, as I believe it stores the port, feature and hardware the port/feature **fails** on, so using reverse logic we can arrive at what is supported to create the Legend values next to each port and feature.
See example below.

**Additional context**
Example: libpq, opencv and llvm have many features. The latter opencv, opencv3, opencv4 and llvm will build for hours before they error out with a feature not supported for your platform. Very frustrating especially when the port does not come right out and tell you the port and/or feature is invalid and you must dig through logs to decipher what the problem may be, and the time wasted when you could be developing, doing meaningful work.

**Example** - note this is an example not factual:
1. When you do a vcpkg search libpq this is what you get:
libpq                12.0-1           The official database access API of postgresql
libpq[openssl]                        support for encrypted client connections and random number generation on platf...
libpq[zlib]                           Use zlib (else --without-zlib)
libpq[readline]                       Use readline (else --without-readline)
libpq[libedit]                        prefer libedit (--with-libedit-preferred)
libpq[perl]                           build the server programming language PL/Perl (dynamic only?) (--with-perl)
libpq[python]                         build the PL/Python server programming language (dynamic only?) (--with-python)
libpq[tcl]                            build the PL/Tcl procedural language(dynamic only?) (--with-tcl)
libpq[nls]                            Native Language Support (--enable-nls[=LANGUAGES])
libpq[kerberos]                       Kerberos Support (--with-gssapi)
libpq[systemd]                        Build with support for systemd service notifications. (--with-systemd)
libpq[ldap]                           LDAP Support (--with-ldap)
libpq[bsd]                            OpenBSD Support (--with-bsd-auth)
libpq[pam]                            Build with PAM (Pluggable Authentication Modules) support. (--with-pam)
libpq[llvm]                           Build with support for LLVM based JIT compilation (--with-llvm)
libpq[icu]                            Build with support for the ICU library (--with-icu)
libpq[bonjour]                        Build with Bonjour support (--with-bonjour)
libpq[uuid]                           Build the uuid-ossp module (which provides functions to generate UUIDs) (--wit...
libpq[xml]                            Build with libxml (--with-libxml)
libpq[xslt]                           Build with libxslt (--with-libxslt)
libpq[client]                         Build all client tools and libraries.

2. Proposed:
`  + libpq`                12.0-1           The official database access API of postgresql
`  + libpq[openssl]`                        support for encrypted client connections and random number generation on platf...
`  + libpq[zlib]`                           Use zlib (else --without-zlib)
`   n libpq[readline]`                       Use readline (else --without-readline)
`   n libpq[libedit]`                        prefer libedit (--with-libedit-preferred)
`   + libpq[perl]`                           build the server programming language PL/Perl (dynamic only?) (--with-perl)
`   n libpq[python]`                         build the PL/Python server programming language (dynamic only?) (--with-python)
`   n libpq[tcl]`                            build the PL/Tcl procedural language(dynamic only?) (--with-tcl)
`   a libpq[nls]`                            Native Language Support (--enable-nls[=LANGUAGES])
`  w libpq[kerberos]`                       Kerberos Support (--with-gssapi)
` lm libpq[systemd]`                        Build with support for systemd service notifications. (--with-systemd)
`  ai libpq[ldap]`                           LDAP Support (--with-ldap)
`   lm libpq[bsd]`                            OpenBSD Support (--with-bsd-auth)
`   al libpq[pam]`                            Build with PAM (Pluggable Authentication Modules) support. (--with-pam)
`   n libpq[llvm]`                           Build with support for LLVM based JIT compilation (--with-llvm)
`   + libpq[icu]`                            Build with support for the ICU library (--with-icu)
`   n libpq[bonjour]`                        Build with Bonjour support (--with-bonjour)
`   n libpq[uuid]`                           Build the uuid-ossp module (which provides functions to generate UUIDs) (--wit...
`   + libpq[xml]`                            Build with libxml (--with-libxml)
`   + libpq[xslt]`                           Build with libxslt (--with-libxslt)
`    l libpq[client]`                         Build all client tools and libraries.

Legend for ports and features:
`+ - all platforms`
`a - android only`
`i - ios`
`l - linux`
`m - mac only`
`n - not implemented`
`w - windows only`

3. We may also want to add hardware legends also, such as ARM, ARM64, PowerPC, x86, x64, etc.

**Comment by Neumann-A** [comment]
IMHO way to cryptic but I would support a supports field for features.

**Comment by timautry** [comment]
> IMHO way to cryptic but I would support a supports field for features.

That would be acceptable also.

**Comment by timautry** [comment]
I close, I no longer use product.
