### ISSUE TITLE
vcpkg bootstrap fails on macOS 10.12 (cause: ninja update 1.10)

### ISSUE THREAD

**Issue by past-due** [microsoft/vcpkg#10890]
**Describe the bug**
Likely since 2070c3c0d8999556f873847cf4c080e1fd210086, which updates ninja to v1.10, vcpkg fails to build on macOS 10.12.

```
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
Referenced from: /<path>/vcpkg/downloads/tools/ninja-1.10.0-osx/ninja
Expected in: /usr/lib/libSystem.B.dylib
```

It seems that ninja was built for macOS without explicitly specifying a deployment target. It's likely it will fail to run on macOS 10.13 as well. (Although I haven't tested yet.)

See: https://github.com/ninja-build/ninja/issues/1764

I've opened a PR for ninja to specify the deployment target for macOS builds: https://github.com/ninja-build/ninja/pull/1765

In the interim, rebuilding the ninja v1.10 macOS binary used by vcpkg (and specifying a `MACOSX_DEPLOYMENT_TARGET`) may be a good idea.

**Environment**
- OS: macOS 10.12

**To Reproduce**
(On macOS 10.12 - possibly 10.13)
1. ./bootstrap-vcpkg.sh
2. See error

**Comment by Voskrese** [comment]
Reproduce in the old version ninja

**Comment by cenit** [comment]
Thank you @past-due for the help and the upstream fix!!

**Comment by bakercp** [comment]
For what it's worth, on macOS 10.13 I found this same issue after a failed initial boostrap, I just deleted the `ninja` from the `vcpkg/downloads/tools/ninja-1.10.0-osx/` folder and symlinked it to an up-to-date version I installed with brew.  I ran boostrap again and it all seemed to work.
