### ISSUE TITLE
How do I install packages from a file?

### ISSUE THREAD

**Issue by brupelo** [microsoft/vcpkg#10896]
Latest vcpkg version here... vcpkg install didn't reveal any way to achieve this so... after saving all my packages in a vcpkg_packages.txt (1 package per line) I've tried:

- `cat vcpkg_packages.txt | vcpkg install`
- `cat vcpkg_packages.txt > vcpkg install`
- `cat vcpkg_packages.txt | xargs vcpkg install`
- `cat vcpkg_packages.txt | xargs -l vcpkg install`

And unfortunately none of them did the trick so... how would you install packages stored in a file? For instance, with python's pip you can `pip install -r requirements.txt` ... with npm, cargo, etc etc...

Thanks in advance.

**Comment by NancyLi1013** [comment]
Hi @brupelo 
Thanks for posting this issue.
Since vcpkg currently doesn't support this.
You can install packages that are listed in vcpkg via the command vcpkg install port1 port2 port3 ... .

**Comment by brupelo** [comment]
@NancyLi1013 Yeah, that's the way I did it the other day... it'd be quite handy though having the ability to install from file or stdin though... that way you could nicely store/share your list of packages across computers. One thing I didn't understand though was my attempt when using xargs didn't do the trick... :/

**Comment by NancyLi1013** [comment]
@brupelo 
Thanks for your details about this.
I also tried this on my local.
I run `cat vcpkg_packages.txt | xargs -t
`  but I only saw the command I write in `vcpkg_packages.txt` was printed on the command window. 
```
vruil@linux003:~/vcpkg$ cat vcpkg_packages.txt | xargs -t
./vcpkg install sqlite3
```

Do you want to implement that those ports you listed in the file can be installed automatically?

I also tried the commands you mentioned above, unfortunately none of them can run normally.

**Comment by NancyLi1013** [comment]
I'm going to close this issue for now due to no response for a long time.
Please feel free to reopen this issue if this is still a problem for you.

**Comment by nilsnolde** [comment]
On windows: I have no idea where I have this from, but this works for me:

`path\to\vcpkg.exe --triplet x64-windows install "@.vcpkg_deps.txt"`

with `.vcpkg_deps.txt` simply listing the deps, e.g.:
```
boost-algorithm
boost-config
boost-core
boost-heap
boost-lexical-cast
boost-property-tree
boost-variant
boost-geometry
boost-program-options
curl
protobuf
```

What I couldn't make work yet is to reference a dep file in another directory..

**Comment by elibroftw** [comment]
The most useful things we find are always at the depths of the internet

**Comment by dg0yt** [comment]
@elibroftw From `vcpkg help`:
~~~
  @response_file                  Specify a response file to provide additional parameters
~~~
