### ISSUE TITLE
[New Port Request] oRTP

### ISSUE THREAD

**Issue by japj** [microsoft/vcpkg#10898]
Library name: 
oRTP

Library description:
oRTP is a C library implementing the RTP protocol (rfc3550). It is available for most unix clones (primilarly Linux and HP-UX), and Microsoft Windows.

Source repository URL:
git://git.linphone.org/ortp.git
(mirror at https://github.com/BelledonneCommunications/ortp)

Project homepage (if different from the source repository):
http://www.linphone.org/technical-corner/ortp

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
There is an additional dependency: bctoolbox[1]: portability layer

[1] git://git.linphone.org/bctoolbox.git or http://www.linphone.org/releases/sources/bctoolbox

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
