### ISSUE TITLE
[New Port Request] obfusion

### ISSUE THREAD

**Issue by BullyWiiPlaza** [microsoft/vcpkg#10897]
Library name: obfusion

Library description: C++ X86 Code Obfuscation Library

Source repository URL: https://github.com/kgretzky/obfusion

Project homepage (if different from the source repository): -

Anything else that is useful to know when adding (such as optional features the library may have that should be included): -

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
