### ISSUE TITLE
Can't locate wxwidgets when trying to install

### ISSUE THREAD

**Issue by amciffer** [microsoft/vcpkg#10892]
I'm unable to install - see below.  Was the package removed?

C:\Users\Andrew\vcpkg>.\vcpkg install wxwidgets
Computing installation plan...
Error: Cannot find definition for package `wxwidgets`

**Comment by timautry** [comment]
Try this:
1. `.\vcpkg search wxwidgets` - it should like this:
` SYSTEM@ANDROMEDA 04/18/2020  9:43:01 D:\Git\vs2017.prod`
`->vcpkg search wxwidgets`
`plplot[wxwidgets]                     plplot wxwidgets module`
`wxchartdir           1.0.0            wxChartDir provides components for the integration and use of the commercial C...`
`wxwidgets            3.1.3            wxWidgets is a widget toolkit and tools library for creating graphical user in...`
`If your library is not listed, please open an issue at and/or consider making a pull request:`
`    https://github.com/Microsoft/vcpkg/issues`

2. If it does not list it, then try `.\vcpkg search` - it should show many ports to install

3. If both 1 and 2 fail, it appears the vcpkg instance may be corrupt - you will need to delete and recreate it.

**Comment by amciffer** [comment]
Thanks – not sure why I’m having issues.  When I search for wxwidgets, it doesn’t see it:

C:\Users\Andrew\vcpkg>.\vcpkg search wxwidgets
plplot[wxwidgets]                     plplot wxwidgets module
wxchartdir           1.0.0            wxChartDir provides components for the integration and use of the commercial C...


And a general search (vcpkg search) doesn’t show it either.  I was able to install sqlite3 today.

I had wxwidgets on my machine previously, and wanted to reinstall it.  I did a “remove”, so I think my machine is clean – not sure if that should matter anyway.

**Comment by amciffer** [comment]
I re-installed vcpkg and it now works – thank you.

**Comment by timautry** [comment]
Glad it fixed it for you. Have a wonderful day!

**Comment by LilyWangL** [comment]
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.
