### ISSUE TITLE
[New Port Request] DotNetSdk

### ISSUE THREAD

**Issue by Pospelove** [microsoft/vcpkg#10894]
Library name: .NET SDK

Source repository URL: https://github.com/dotnet/runtime

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
Many ports (i.e. chakracore) are relying on .NET SDK so it will be reasonable to add it as a port.

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
