### ISSUE TITLE
Why cmake command file(WRITE...) and file(MAKE_DIRECTORY...) failed?

### ISSUE THREAD

**Issue by goproxies** [microsoft/vcpkg#10907]
I tried to use vcpkg install openssl. I found that cmake command `file(WRITE...)` and `file(MAKE_DIRECTORY...)` failed.There were nothing of file and directory created.The cmake system in my computer work correctly with the same commands.The errors info as follow:

PS F:\msys64\home\whitesky\vcpkg\vcpkg> vcpkg install openssl:x64-windows
Computing installation plan...
The following packages will be built and installed:
    openssl[core]:x64-windows
  * openssl-windows[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/2: openssl-windows:x64-windows
Building package openssl-windows[core]:x64-windows...
-- Using cached F:/msys64/home/whitesky/vcpkg/vcpkg/downloads/openssl-1.1.1d.tar.gz
-- Extracting source F:/msys64/home/whitesky/vcpkg/vcpkg/downloads/openssl-1.1.1d.tar.gz
CMake Error at F:/msys64/home/whitesky/vcpkg/vcpkg/scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: /usr/bin/cmake.exe -E tar xjf F:/msys64/home/whitesky/vcpkg/vcpkg/downloads/openssl-1.1.1d.tar.gz
    Working Directory: F:/msys64/home/whitesky/vcpkg/vcpkg/buildtrees/openssl-windows/src/TEMP
    Error code: No such file or directory
    See logs for more information:

Call Stack (most recent call first):
  F:/msys64/home/whitesky/vcpkg/vcpkg/scripts/cmake/vcpkg_extract_source_archive.cmake:50 (vcpkg_execute_required_proces
s)
  F:/msys64/home/whitesky/vcpkg/vcpkg/scripts/cmake/vcpkg_extract_source_archive_ex.cmake:108 (vcpkg_extract_source_arch
ive)
  F:/msys64/home/whitesky/vcpkg/vcpkg/ports/openssl-windows/portfile.cmake:22 (vcpkg_extract_source_archive_ex)
  F:/msys64/home/whitesky/vcpkg/vcpkg/scripts/ports.cmake:90 (include)

Could not copy into file: F:\msys64\home\whitesky\vcpkg\vcpkg\packages\openssl-windows_x64-windows\share\openssl-windows
\vcpkg_abi_info.txt

**Comment by LilyWangL** [comment]
@goproxies Thanks for posting this issue. You could remove the directory `F:/msys64/home/whitesky/vcpkg/vcpkg/buildtrees/openssl-windows/src/TEMP` and install `openssl-windows:x64-windows` again.

**Comment by goproxies** [comment]
I found this problem may result from some unkown current-dicretory-difference auto-config between powershell and msys2-shell.Actually it can work corretly in msys2-shell,but file and directory were created in the project root path `.../vcpkg/vcpkg/` in powershell.And this problem can not be reproduced now after I downloaded some packages to `.../vcpkg/vcpkg/downloads` manually.
