### ISSUE TITLE
[ffmpeg] Add avisynthplus feature

### ISSUE THREAD

**Issue by longnguyen2004** [microsoft/vcpkg#10906]
Since avisynthplus is also included in vcpkg, it seems logical to add this feature to the ffmpeg port. Besides I use avisynthplus quite frequently, It'd be nice if I can build ffmpeg with avisynthplus support

**Comment by NancyLi1013** [comment]
Hi @longnguyen2004 

Thanks for posting this issue.
I'm sorry that this feature cannot be supported now.

https://github.com/FFmpeg/FFmpeg/blob/master/doc/general.texi#L52-L64.

As for Windows, `avisynthplus `required is not available in vcpkg.

```
For Windows, supported AviSynth variants are
@url{http://avisynth.nl, AviSynth 2.6 RC1 or higher} for 32-bit builds and
@url{http://avisynth.nl/index.php/AviSynth+, AviSynth+ r1718 or higher} for 32-bit and 64-bit builds.
```
As for Linux and macOS, `avisynthplus `provided by vcpkg has broken on these two platforms now.

Based on these cases, this feature might not be added for now.

**Comment by wangqr** [comment]
Actually, avisynthplus 3.5.0 provided in vcpkg does satisfy "AviSynth+ r1718 or higher" requirement. AviSynth+ 3.4.0 is after r2772, and r2772 is after r1718.

**Comment by NancyLi1013** [comment]
@wangqr 
Thanks for your above info. I will try to verify if this can work now.

**Comment by NancyLi1013** [comment]
Hi @wangqr and @longnguyen2004 
I submitted a PR to add `avisynthplus`. Could you please help confirm if this can work for you?

Note:
Since `avisynthplus` currently only supports dynamic build and it doesn't support Linux.
Feature `avisynthplus` can only be built on x86-windows and x64-windows triplets.
