### ISSUE TITLE
some libs in boost 1.6.4 still use deprecated std functional class

### ISSUE THREAD

**Issue by feverzsj** [Microsoft/vcpkg#1090]
I've found [numeric_conversion](https://github.com/boostorg/numeric_conversion), [algorithm](https://github.com/boostorg/algorithm) still using deprecated std::unary_function in boost 1.6.4. Thus, can't be compiled with /std:c++latest. Although the authors have already fixed them in repository for a long time, 1.6.4 still uses the old version.
Since next boost release will be at least 2 months later, I think a patch may be helpful.

**Comment by codicodi** [comment]
I'm not sure if patching is a good idea here.
For one, you can easily workaround such issues by defining `_HAS_AUTO_PTR_ETC` project wide (libc++ offers similar macros, so you can add them too, if you want to keep your project portable).
Additionally, in some cases we can't really do anything as patching would break interfaces (like factory functions returning `std::auto_ptr<...>` in Boost.Locale).

**Comment by ras0219-msft** [comment]
I agree, this unfortunately looks like it would be too big a change for Vcpkg to make.

I would highly encourage you to post on the boost mailing list instead and ensure that the updated version are included in the next 1.65 release!
