### ISSUE TITLE
[New Port Request] <BehaviorTree.CPP>

### ISSUE THREAD

**Issue by UxiBeo** [microsoft/vcpkg#10909]
Library name: BehaviorTree.CPP

Library description: This C++ 14 library provides a framework to create BehaviorTrees. It was designed to be flexible, easy to use, reactive and fast.

Source repository URL: https://github.com/BehaviorTree/BehaviorTree.CPP

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
