### ISSUE TITLE
capstone linux build failure

### ISSUE THREAD

**Issue by illera88** [microsoft/vcpkg#10905]
**Host Environment**
- OS: Ubuntu (ubuntu-latest)

**To Reproduce**
`./vcpkg install capstone`

Trying to install it in a Github workflow.

```
Run vcpkg version
  vcpkg version
  vcpkg install capstone
  shell: /bin/bash -e {0}
Vcpkg package management program version 2020.02.04-unknownhash

See LICENSE.txt for license information.
Computing installation plan...
CMake Error at buildtrees/0.vcpkg_tags.cmake:10:
  Parse error.  Expected a command name, got left paren with text "(".


CMake Error: Error processing file: /usr/local/share/vcpkg/buildtrees/0.vcpkg_tags.cmake
```

**Comment by NancyLi1013** [comment]
Hi @illera88 
Thanks for posting this issue.
I can build this port successfully on both Ubuntu 16.04 and 18.04.
Could you please help confirm how do you get  this file `0.vcpkg_tags.cmake`?
If possible, could you post the full build process log and provide this file `0.vcpkg_tags.cmake`?
