### ISSUE TITLE
Building package io2d:x64-linux failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by othmanalbahri1** [microsoft/vcpkg#10900]
Hello,

I'm running the latest VCPKG on an Ubuntu 18 machine. I'm trying to install IO2D using VCPKG. However, I get a build error that seems to be related to X11_LIB. Below is the terminal output:

> $./vcpkg install io2d
> Computing installation plan...
> The following packages will be built and installed:
>     io2d[core]:x64-linux
> Starting package 1/1: io2d:x64-linux
> Building package io2d[core]:x64-linux...
> -- Using cached /home/oab/Documents/Route-Planning/vcpkg/downloads/cpp-io2d-P0267_RefImpl-add3c9792dcd3f08c497ae3adafb2a3b5b5fc338.tar.gz
> -- Using source at /home/oab/Documents/Route-Planning/vcpkg/buildtrees/io2d/src/3b5b5fc338-1775a03870
> -- Configuring x64-linux-dbg
> CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
>     Command failed: /home/oab/Documents/Route-Planning/vcpkg/downloads/tools/cmake-3.14.0-linux/cmake-3.14.0-Linux-x86_64/bin/cmake /home/oab/Documents/Route-Planning/vcpkg/buildtrees/io2d/src/3b5b5fc338-1775a03870 -DIO2D_WITHOUT_SAMPLES=1 -DIO2D_WITHOUT_TESTS=1 -DCMAKE_INSTALL_INCLUDEDIR:STRING=include -DCMAKE_MAKE_PROGRAM=/home/oab/Documents/Route-Planning/vcpkg/downloads/tools/ninja-1.10.0-linux/ninja -DCMAKE_SYSTEM_NAME=Linux -DBUILD_SHARED_LIBS=OFF -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/home/oab/Documents/Route-Planning/vcpkg/scripts/toolchains/linux.cmake -DVCPKG_TARGET_TRIPLET=x64-linux -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=external -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=/home/oab/Documents/Route-Planning/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_TARGET_ARCHITECTURE=x64 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/home/oab/Documents/Route-Planning/vcpkg/packages/io2d_x64-linux/debug
>     Working Directory: /home/oab/Documents/Route-Planning/vcpkg/buildtrees/io2d/x64-linux-dbg
>     Error code: 1
>     See logs for more information:
>       /home/oab/Documents/Route-Planning/vcpkg/buildtrees/io2d/config-x64-linux-dbg-out.log
>       /home/oab/Documents/Route-Planning/vcpkg/buildtrees/io2d/config-x64-linux-dbg-err.log
> 
> Call Stack (most recent call first):
>   scripts/cmake/vcpkg_configure_cmake.cmake:306 (vcpkg_execute_required_process)
>   ports/io2d/portfile.cmake:18 (vcpkg_configure_cmake)
>   scripts/ports.cmake:90 (include)
> 
> 
> Error: Building package io2d:x64-linux failed with: BUILD_FAILED
> Please ensure you're using the latest portfiles with `.\vcpkg update`, then
> submit an issue at https://github.com/Microsoft/vcpkg/issues including:
>   Package: io2d:x64-linux
>   Vcpkg version: 2020.02.04-unknownhash
> 
> Additionally, attach any relevant sections from the log files above.

The log files include:

> Default IO2D backend was not specified, choosing automatically...
> Found Linux, using CAIRO_XLIB.
> CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
> Please set them or make sure they are set and tested correctly in the CMake files:
> X11_LIB
>     linked by target "io2d_cairo_xlib" in directory /home/oab/Documents/Route-Planning/vcpkg/buildtrees/io2d/src/3b5b5fc338-1775a03870/P0267_RefImpl/P0267_RefImpl/cairo/xlib
> 

And

> -- The CXX compiler identification is GNU 7.5.0
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
> -- Found Cairo: /home/oab/Documents/Route-Planning/vcpkg/installed/x64-linux/include/cairo (found version "1.16.0") 
> -- Found ZLIB: /home/oab/Documents/Route-Planning/vcpkg/installed/x64-linux/debug/lib/libz.a (found version "1.2.11") 
> -- Found BZip2: optimized;/home/oab/Documents/Route-Planning/vcpkg/installed/x64-linux/lib/libbz2.a;debug;/home/oab/Documents/Route-Planning/vcpkg/installed/x64-linux/debug/lib/libbz2d.a (found version "1.0.6") 
> -- Looking for BZ2_bzCompressInit
> -- Looking for BZ2_bzCompressInit - found
> -- Found JPEG: /home/oab/Documents/Route-Planning/vcpkg/installed/x64-linux/debug/lib/libjpeg.a (found version "62") 
> -- Found PNG: optimized;/home/oab/Documents/Route-Planning/vcpkg/installed/x64-linux/debug/lib/libpng.a;debug;/home/oab/Documents/Route-Planning/vcpkg/installed/x64-linux/debug/lib/libpng16d.a (found version "1.6.37") 
> -- Found TIFF: optimized;/home/oab/Documents/Route-Planning/vcpkg/installed/x64-linux/lib/libtiff.a;debug;/home/oab/Documents/Route-Planning/vcpkg/installed/x64-linux/debug/lib/libtiffd.a (found version "4.0.10") 
> -- Found Freetype: optimized;/home/oab/Documents/Route-Planning/vcpkg/installed/x64-linux/lib/libfreetype.a;debug;/home/oab/Documents/Route-Planning/vcpkg/installed/x64-linux/debug/lib/libfreetyped.a (found version "2.10.1") 
> -- Looking for C++ include pthread.h
> -- Looking for C++ include pthread.h - found
> -- Looking for pthread_create
> -- Looking for pthread_create - not found
> -- Looking for pthread_create in pthreads
> -- Looking for pthread_create in pthreads - not found
> -- Looking for pthread_create in pthread
> -- Looking for pthread_create in pthread - found
> -- Found Threads: TRUE  
> -- Found EXPAT: /home/oab/Documents/Route-Planning/vcpkg/installed/x64-linux/debug/lib/libexpat.a (found version "2.2.7") 
> -- Configuring incomplete, errors occurred!
> See also "/home/oab/Documents/Route-Planning/vcpkg/buildtrees/io2d/x64-linux-dbg/CMakeFiles/CMakeOutput.log".
> See also "/home/oab/Documents/Route-Planning/vcpkg/buildtrees/io2d/x64-linux-dbg/CMakeFiles/CMakeError.log".

Also, here's the output from /vcpkg/buildtrees/io2d/x64-linux-dbg/CMakeFiles/CMakeError.log:

> Determining if the pthread_create exist failed with the following output:
> Change Dir: /home/oab/Documents/Route-Planning/vcpkg/buildtrees/io2d/x64-linux-dbg/CMakeFiles/CMakeTmp
> 
> Run Build Command(s):/home/oab/Documents/Route-Planning/vcpkg/downloads/tools/ninja-1.10.0-linux/ninja cmTC_03950 
> [1/2] Building CXX object CMakeFiles/cmTC_03950.dir/CheckSymbolExists.cxx.o
> [2/2] Linking CXX executable cmTC_03950
> FAILED: cmTC_03950 
> : && /usr/bin/c++  -fPIC   CMakeFiles/cmTC_03950.dir/CheckSymbolExists.cxx.o  -o cmTC_03950   && :
> CMakeFiles/cmTC_03950.dir/CheckSymbolExists.cxx.o: In function `main':
> CheckSymbolExists.cxx:(.text+0x1b): undefined reference to `pthread_create'
> collect2: error: ld returned 1 exit status
> ninja: build stopped: subcommand failed.
> 
> File /home/oab/Documents/Route-Planning/vcpkg/buildtrees/io2d/x64-linux-dbg/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx:
> /* */
> 
> #include <pthread.h>
> 

> 
> int main(int argc, char** argv)
> {
>   (void)argv;
> #ifndef pthread_create
>   return ((int*)(&pthread_create))[argc];
> #else
>   (void)argc;
>   return 0;
> #endif
> }
> 
> Determining if the function pthread_create exists in the pthreads failed with the following output:
> Change Dir: /home/oab/Documents/Route-Planning/vcpkg/buildtrees/io2d/x64-linux-dbg/CMakeFiles/CMakeTmp
> 
> Run Build Command(s):/home/oab/Documents/Route-Planning/vcpkg/downloads/tools/ninja-1.10.0-linux/ninja cmTC_c555e 
> [1/2] Building CXX object CMakeFiles/cmTC_c555e.dir/CheckFunctionExists.cxx.o
> [2/2] Linking CXX executable cmTC_c555e
> FAILED: cmTC_c555e 
> : && /usr/bin/c++  -fPIC -DCHECK_FUNCTION_EXISTS=pthread_create   CMakeFiles/cmTC_c555e.dir/CheckFunctionExists.cxx.o  -o cmTC_c555e  -lpthreads && :
> /usr/bin/ld: cannot find -lpthreads
> collect2: error: ld returned 1 exit status
> ninja: build stopped: subcommand failed.
> 

I'd appreciate your help.

Thanks,

Othman

**Comment by LilyWangL** [comment]
Sorry I am late. Thanks for posting this issue. I can't reproduce this issue locally, I installed io2d:x64-linux successfully with the latest source. Does the issue persist? Can you try vcpkg latest revision?
```
Building package io2d[core]:x64-linux... done
Installing package io2d[core]:x64-linux...
Installing package io2d[core]:x64-linux... done
Elapsed time for package io2d:x64-linux: 10.69 s

Total elapsed time: 2.13 min
```

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
