### ISSUE TITLE
gsl and ms-gsl share the same include/gsl directory/folder

### ISSUE THREAD

**Issue by timautry** [microsoft/vcpkg#10917]
**Describe the bug**
gsl and ms-gsl share the same include/gsl directory/folder

**Environment**
- OS: [Microsoft Windows x64 Pro [Version 10.0.18363.778]]
- Compiler:
   - Visual Studio 2017 Version: 15.9.22 VS Tools Version: 14.16.27023
   - Visual Studio 2019 Version: 16.5.4 VS Tools Version: 14.25.28610
- WinSDK 10.0.18362.0
- cmake version 3.17.1
- ninja version 1.10.0
- Vcpkg package management program version 2020.02.04-nohash-external

**To Reproduce**
1. `.vcpkg install gsl[*] ms-gsl[*]`
2. No error is created stating they exist in the same location
3. The gsl have the .h extension where the ms-gsl * files do not.

**Expected behavior**
Possibility to store the ms-gsl include files in a include/ms-gsl directory/folder with the .h extension?

**Failure logs** 
No failures.

**Additional context**
None

**Comment by JackBoosY** [comment]
Although they are all installed in the same folder, there are no conflicting files. I think this issue can be ignored.

**Comment by timautry** [comment]
Ok - I just wanted to mention the inconsistency on how vcpkg ms-gsl port files were:
- stored in the include/gsl without the .h extension
- stored in the include/gsl with the gsl port files

- The reason I mentioned it, as if I needed to use the ms-gsl port header files I would put
`#include "gsl/gsl.h"` 
only for it not to be found, so I would need to go searching for it.

- I know it is how microsoft deployed the port on github source and sometimes microsoft does at times strays away from being consistent making their own normal :)

- However the group wants to store them is fine, I just found this odd when troubleshooting the seal issue #10918 ... :)

Have a wonderful day.
