### ISSUE TITLE
[mpg123] build failure

### ISSUE THREAD

**Issue by TerensTare** [microsoft/vcpkg#10914]
**Host Environment**
- OS: [e.g. Windows/Linux etc...] Azure hosted runners (on Windows, Linux and Mac-OS)
- Compiler: cl.exe (Windows), /usr/bin/c++ (Linux), XCode C++ (Mac)

**To Reproduce**
`./vcpkg install sdl2 sdl2-image sdl2-image[libjpeg-turbo] sdl2-image[tiff] sdl2-image[libwebp] sdl2-mixer sdl2-mixer[dynamic-load] sdl2-mixer[libflac] sdl2-mixer[mpg123] sdl2-mixer[libmodplug] sdl2-mixer[libvorbis] sdl2-mixer[opusfile] sdl2-ttf nlohmann-json sol2 fmt`

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
On Linux runner:
![image](https://user-images.githubusercontent.com/37905314/79699394-a6e23c00-828f-11ea-9983-9ed8aecb93d0.png)
-Please attach any additional failure logs mentioned in the console output.
On Windows runner:
![image](https://user-images.githubusercontent.com/37905314/79699422-dc872500-828f-11ea-92f3-d26247989170.png)

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by timautry** [comment]
See issue #10523 
- The `yasm` executable binary needs to be in one of the paths used by vcpkg.
- On windows I created a symlink to `yasm` as shown in the issue, but I am not sure how to solve the issue on Linux (I am not as versed on Linux as windows)
- Maybe this info will help figure out where to put a symlink at and if so, please post to help others solve the issue on Linux.
Have a wonderful day :)

**Comment by Voskrese** [comment]
@TerensTare 
test the patch, whether it works or not, and unsubscribe
https://github.com/microsoft/vcpkg/pull/10929/files
https://github.com/microsoft/vcpkg/pull/10929.patch

**Comment by TerensTare** [comment]
I found a workaround for it @timautry  and @Voskrese . I just added a variable on a matrix named get_yasm. On linux it is equivalent to `sudo apt-get install yasm`. On Mac it is `brew install yasm`, meanwhile on Windows it is just `echo`, as apparently, vcpkg automatically installs yasm on Windows if needed.
