### ISSUE TITLE
vcpkg hint message should use forward slash on Mac/Linux

### ISSUE THREAD

**Issue by linquize** [microsoft/vcpkg#10910]
Currently there are 4 hints, but always show `.\vcpkg` regardless platform.

```
.\vcpkg update
.\vcpkg upgrade
.\vcpkg remove
.\vcpkg edit
```

It is better to use `./vcpkg` on Mac/Linux

**Comment by PhoebeHui** [comment]
This issue has been fixed, please get latest source and try again.
