### ISSUE TITLE
seal fails to install if ms-gsl 3.0.0 is installed

### ISSUE THREAD

**Issue by ghost** [microsoft/vcpkg#10918]
**Host Environment**
- OS: [Microsoft Windows x64 Pro [Version 10.0.18363.778]]
- Compiler:
   - Visual Studio 2017 Version: 15.9.22 VS Tools Version: 14.16.27023
   - Visual Studio 2019 Version: 16.5.4 VS Tools Version: 14.25.28610
- WinSDK 10.0.18362.0
- cmake version 3.17.1
- ninja version 1.10.0
- Vcpkg package management program version 2020.02.04-nohash-external

**To Reproduce**
`./vcpkg install ms-gsl[*] seal[*]`

**Failure logs** 
-Console output from vs2019 prod failed install with debug option:
[vs2019.prod.seal.log](https://github.com/microsoft/vcpkg/files/4500464/vs2019.prod.seal.log)

-Console output from vs2019 test successful install with debut option:
[vs2019.test.seal.log](https://github.com/microsoft/vcpkg/files/4500465/vs2019.test.seal.log)

-Failure log from vs2019 prod failed install:
[vs2019.test.seal.install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/4500467/vs2019.test.seal.install-x64-windows-dbg-out.log)

-Same log from vs2019 test successful install:
[vs2019.prod.seal.install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/4500468/vs2019.prod.seal.install-x64-windows-dbg-out.log)

**Additional context**
- ms-gsl will install properly.
- seal will not install if ms-gsl is installed
- removing ms-gsl and seal will install
- I am not 100% sure, but I believe seal installed properly with ms-gsl before ms-gsl was upgraded from version 2.1.0 to 3.0.0???

**Comment by JackBoosY** [comment]
Hi @timautry, thanks for reporting this issue.
Can you comment out `PREFER_NINJA` in _VCPKG_PATH/ports/seal/portfile.cmake_ and try again?

Thanks.

**Comment by JackBoosY** [comment]
Do we need to rename `ms-gsl` to `gsl-windows`, rename `gsl` to `gsl-unix` and add an empty port `gsl` like `openssl` to solve this issue?

**Comment by timautry** [comment]
@JackBoosY 
See attached results with PREFER_NINJA commented out in the seal/portfile.cmake file:
1. failed build where ms-gsl port is installed:
[vcpkg.prod.seal.install.zip](https://github.com/microsoft/vcpkg/files/4505183/vcpkg.prod.seal.install.zip)
2. successful build where ms-gsl is NOT installed:
[vcpkg.test.seal.install.zip](https://github.com/microsoft/vcpkg/files/4505187/vcpkg.test.seal.install.zip)
- Note: the zipped files contain the vcpkg console with --debug option and the complete buildtrees/seal, logs, etc.

**Comment by JackBoosY** [comment]
```
## Version 3.4.3

...
- Removed support for Microsoft GSL `gsl::multi_span`, as it was recently deprecated in GSL.
```

**Comment by timautry** [comment]
@JackBoosY 
- updated with latest vcpkg from github `git pull`
- ms-gsl was updated to version 3.0.1
- seal was updated to version 3.4.5

Still the same issue, if ms-gsl is installed first, seal will NOT install. If install seal first, it installs fine, then install ms-gsl, it is fine.

**Comment by JackBoosY** [comment]
@timautry I am digging deeper into the cause of the error.

**Comment by JackBoosY** [comment]
In _SOURCE/native/src/CMakeLists.txt_ line 280:
```
    find_package(MSGSL MODULE)
    if(NOT MSGSL_FOUND)
        set(SEAL_USE_MSGSL OFF CACHE BOOL ${SEAL_USE_MSGSL_OPTION_STR} FORCE)
        clear_msgsl_cache()
    endif()
```

Related: [#159](https://github.com/microsoft/SEAL/issues/159).

**Comment by WeiDaiWD** [comment]
@timautry Microsoft SEAL 3.4.5 and older does not support Microsoft GSL 3.0.0 and newer, due to API changes in Microsoft GSL 3.0.0. Please use a newer version of Microsoft SEAL and follow the [installation guide](https://github.com/microsoft/SEAL/blob/master/README.md).

**Comment by timautry** [comment]
@WeiDaiWD cc: @JackBoosY It will be up to the maintainers of microsoft/vcpkg if and when it is decided whether to upgrade and/or continue to maintain the microsoft/seal in microsoft/vcpkg or not.

**Comment by JackBoosY** [comment]
I consider to keep this issue open until it's resolved.

**Comment by timautry** [comment]
I close, I no longer use product.
