### ISSUE TITLE
Latest vcpkg won't compile on Windows 10

### ISSUE THREAD

**Issue by acgetchell** [microsoft/vcpkg#10916]
**Describe the bug**
`vcpkg` won't compile on Windows 10

**Environment**
- OS: Windows 10 1909 OS build 18363.778
- Compiler: Visual Studio 16.5.4

**To Reproduce**
1. cd vcpkg
2. ./bootstrap-vcpkg.bat
3. See error:

Copy-Item : Access to the path 'C:\Users\adam\vcpkg\toolsrc\msbuild.x86.release\vcpkg.exe' is denied.
At C:\Users\adam\vcpkg\scripts\bootstrap.ps1:428 char:1
+ Copy-Item "$vcpkgReleaseDir\vcpkg.exe" "$vcpkgRootDir\vcpkg.exe"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (C:\Users\adam\v...lease\vcpkg.exe:FileInfo) [Copy-Item], Unauthorized
   AccessException
    + FullyQualifiedErrorId : CopyFileInfoItemUnauthorizedAccessError,Microsoft.PowerShell.Commands.CopyItemCommand

This happens even when `bootstrap-vcpkg.bat` is run with Administrative Privileges:

**Expected behavior**
A new version of vcpkg builds.

**Failure logs** 
PS C:\Users\adam\vcpkg> .\bootstrap-vcpkg.bat

Building vcpkg.exe ...

  pch.cpp
  archives.cpp
  checks.cpp
  chrono.cpp
  cofffilereader.cpp
  downloads.cpp
  enums.cpp
  files.cpp
  hash.cpp
  json.cpp
  machinetype.cpp
  parse.cpp
  strings.cpp
  stringview.cpp
  system.cpp
  system.print.cpp
  system.process.cpp
  unicode.cpp
  binarycaching.cpp
  binaryparagraph.cpp
  build.cpp
  cmakevars.cpp
  commands.autocomplete.cpp
  commands.buildexternal.cpp
  commands.cache.cpp
  commands.ci.cpp
  commands.contact.cpp
  commands.cpp
  commands.create.cpp
  commands.dependinfo.cpp
  commands.edit.cpp
  commands.env.cpp
  commands.exportifw.cpp
  commands.import.cpp
  commands.integrate.cpp
  commands.list.cpp
  commands.owns.cpp
  commands.porthistory.cpp
  commands.portsdiff.cpp
  commands.search.cpp
  commands.setinstalled.cpp
  commands.upgrade.cpp
  commands.version.cpp
  commands.xvsinstances.cpp
  dependencies.cpp
  export.cpp
  export.chocolatey.cpp
  export.prefab.cpp
  globalstate.cpp
  help.cpp
  input.cpp
  install.cpp
  logicexpression.cpp
  metrics.cpp
  packagespec.cpp
  paragraphparseresult.cpp
  paragraphs.cpp
  portfileprovider.cpp
  postbuildlint.buildtype.cpp
  postbuildlint.cpp
  remove.cpp
  sourceparagraph.cpp
  statusparagraph.cpp
  statusparagraphs.cpp
  tools.cpp
  triplet.cpp
  update.cpp
  userconfig.cpp
  vcpkgcmdarguments.cpp
  vcpkglib.cpp
  vcpkgpaths.cpp
  versiont.cpp
  visualstudio.cpp
  vcpkglib.vcxproj -> C:\Users\adam\vcpkg\toolsrc\msbuild.x86.release\vcpkglib.lib
  vcpkg.cpp
  Generating code
  Previous IPDB not found, fall back to full compilation.
  All 17466 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Finished generating code
  vcpkg.vcxproj -> C:\Users\adam\vcpkg\toolsrc\msbuild.x86.release\vcpkg.exe
  vcpkgmetricsuploader.cpp
  Generating code
  Previous IPDB not found, fall back to full compilation.
  All 6747 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Finished generating code
  vcpkgmetricsuploader.vcxproj -> C:\Users\adam\vcpkg\toolsrc\msbuild.x86.release\vcpkgmetricsuploader.exe

Building vcpkg.exe... done.

Telemetry
---------
vcpkg collects usage data in order to help us improve your experience. The data collected by Microsoft is anonymous. You can opt-out of telemetry by re-running bootstrap-vcpkg.bat with -disableMetrics.
Read more about vcpkg telemetry at docs/about/privacy.md

Copy-Item : Access to the path 'C:\Users\adam\vcpkg\toolsrc\msbuild.x86.release\vcpkg.exe' is denied.
At C:\Users\adam\vcpkg\scripts\bootstrap.ps1:428 char:1
+ Copy-Item "$vcpkgReleaseDir\vcpkg.exe" "$vcpkgRootDir\vcpkg.exe"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (C:\Users\adam\v...lease\vcpkg.exe:FileInfo) [Copy-Item], Unauthorized
   AccessException
    + FullyQualifiedErrorId : CopyFileInfoItemUnauthorizedAccessError,Microsoft.PowerShell.Commands.CopyItemCommand

**Additional context**
Updating vcpkg and package versions.

**Comment by acgetchell** [comment]
If I delete the entire `vcpkg` directory and clone it, I get:

```
PS C:\Users\adam> git clone https://github.com/microsoft/vcpkg.git
Cloning into 'vcpkg'...
remote: Enumerating objects: 77099, done.
remote: Total 77099 (delta 0), reused 0 (delta 0), pack-reused 77099 eceiving objects: 100% (77099/77099), 20.82 MiB | 4Receiving objects: 100% (77099/77099), 21.33 MiB | 4.91 MiB/s, done.

Resolving deltas: 100% (47528/47528), done.
Updating files: 100% (4607/4607), done.
PS C:\Users\adam> cd .\vcpkg\
PS C:\Users\adam\vcpkg> ls


    Directory: C:\Users\adam\vcpkg


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        4/19/2020   3:58 PM                .github
d-----        4/19/2020   3:58 PM                docs
d-----        4/19/2020   3:58 PM                ports
d-----        4/19/2020   3:58 PM                scripts
d-----        4/19/2020   3:58 PM                toolsrc
d-----        4/19/2020   3:58 PM                triplets
-a----        4/19/2020   3:58 PM              8 .gitattributes
-a----        4/19/2020   3:58 PM           6258 .gitignore
-a----        4/19/2020   3:58 PM              0 .vcpkg-root
-a----        4/19/2020   3:58 PM            100 bootstrap-vcpkg.bat
-a----        4/19/2020   3:58 PM            109 bootstrap-vcpkg.sh
-a----        4/19/2020   3:58 PM         442952 CHANGELOG.md
-a----        4/19/2020   3:58 PM           2432 CONTRIBUTING.md
-a----        4/19/2020   3:58 PM           1096 LICENSE.txt
-a----        4/19/2020   3:58 PM           2334 NOTICE.txt
-a----        4/19/2020   3:58 PM           4345 README.md
-a----        4/19/2020   3:58 PM           3282 README_zh_CN.md


PS C:\Users\adam\vcpkg> .\bootstrap-vcpkg.bat
The property 'instance' cannot be found on this object. Verify that the property exists.
At C:\Users\adam\vcpkg\scripts\bootstrap.ps1:78 char:31
+         foreach ($instance in $asXml.instances.instance)
+                               ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict

Could not find Visual Studio. VS2015 or VS2017 (with C++) needs to be installed.
At C:\Users\adam\vcpkg\scripts\bootstrap.ps1:143 char:9
+         throw "Could not find Visual Studio. VS2015 or VS2017 (with C ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find ...o be installed.:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find Visual Studio. VS2015 or VS2017 (with C++) needs to be installed.
```

**Comment by acgetchell** [comment]
Hmmm, I think it's being blocked by BitDefender.

**Comment by acgetchell** [comment]
BitDefender flags `vcpkg` as malware.

**Comment by amirahathifah** [comment]
same with me , being blocked by avg
