### ISSUE TITLE
[WinReg] Update to v2.2.0

### ISSUE THREAD

**Issue by GiovanniDicanio** [microsoft/vcpkg#10919]
Library name: WinReg

New version number: v2.2.0

Other information that may be useful (release notes, etc...)

I attached the updated vcpkg `CONTROL` and `portfile.cmake` files compressed in a single .zip archive. Thanks.
[winreg_vcpkg_files.zip](https://github.com/microsoft/vcpkg/files/4500529/winreg_vcpkg_files.zip)

**Comment by NancyLi1013** [comment]
Hi @GiovanniDicanio 
Thanks for posting this issue.
WinReg has been updated to 2.2.0, please try to update vcpkg and use it.
