### ISSUE TITLE
Ability to copy file with different destination name

### ISSUE THREAD

**Issue by pravic** [microsoft/vcpkg#1091]
Currently it looks a bit awkward:

```cmake
# Handle copyright
file(COPY ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/@PORT@)
file(RENAME ${CURRENT_PACKAGES_DIR}/share/@PORT@/LICENSE ${CURRENT_PACKAGES_DIR}/share/@PORT@/copyright)
```

Wouldn't it be better to make something like `vcpkg_copy_file(SRC DST)` instead?

**Comment by LilyWangL** [comment]
Thanks for posting this issue. This issue has been fixed. You can use `file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)` to handle copyright. So I am closing this issue for now.

**Comment by pravic** [comment]
@LilyWangL I don't see any ` INSTALL... RENAME` mention in the documentation. Could you tell more?

https://cmake.org/cmake/help/latest/command/file.html#install

**Comment by LilyWangL** [comment]
`file (INSTALL...DESTINATION...RENAME)` is a combined command, `RENAME` is a parameter.
