### ISSUE TITLE
[New Port Request] ADVobfuscator

### ISSUE THREAD

**Issue by BullyWiiPlaza** [microsoft/vcpkg#10911]
Library name: ADVobfuscator

Library description: Obfuscation library based on C++11/14 and metaprogramming

Source repository URL: https://github.com/andrivet/ADVobfuscator

Project homepage (if different from the source repository): -

Anything else that is useful to know when adding (such as optional features the library may have that should be included): -

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by BullyWiiPlaza** [comment]
Here's the respective pull request: https://github.com/microsoft/vcpkg/pull/18989

**Comment by JackBoosY** [comment]
Close this issue via #18989 merged.
