### ISSUE TITLE
mpg123 fails install Linux x64-linux triplet - portfile.cmake trying to copy from /lib instead of /lib64

### ISSUE THREAD

**Issue by timautry** [microsoft/vcpkg#10920]
**Describe the bug**
mpg123 fails install Linux x64-linux triplet - portfile.cmake trying to copy from /lib instead of /lib64

**Environment**
- OS: [Linux OpenSuse Leap 15.1 - latest updates]
- Compiler: GNU 8.2.1 - latest updates

**To Reproduce**
1. ./vcpkg install mpg123
2.  `CMake error at ports/mpg123/portfile.cmake:147 _file):`
`file INSTALL cannot find`
`"/home/tim.autry/git/vcpkg/buildtrees/mpg123/src/mpg123-1-9840211cc0/build/debug/lib/libmpg123.a".`
3. In the above message the file actually exists in:
"/home/tim.autry/git/vcpkg/buildtrees/mpg123/src/mpg123-1-9840211cc0/build/debug/**lib64**/libmpg123.a".
4. mpg123 x64-linux triplet builds but the portfile.cmake at line 147 and 155 have a hardcoded path containing **/lib**. Maybe needs to use a variable containing either **lib (for x86-builds)** or **lib64 (for x64-builds)** or a variable the appends **64** onto /lib.

**Expected behavior**
Should build and install properly depending on x86 or x64 architecture.

**Failure logs** 
No failure logs, on screen output

**Additional context**
None

**Comment by LilyWangL** [comment]
Thanks for posting this issue. I can't reproduce this issue. I can install mpg123:x64-Linux successfully on Linux 18.04 GCC8.4.0. And I can't find this directory: `[VCPKG_PAYH]/buildtrees/mpg123/src/mpg123-1-9840211cc0/build/debug/lib64/libmpg123.a`. This is my directory on Linux.
![image](https://user-images.githubusercontent.com/47812810/79739744-2ecc5280-8331-11ea-83e0-6968e62386af.png)

**Comment by timautry** [comment]
- As @strega-nil , @Farwaykorse and I found out last week when troubleshooting and correcting the ./bootstrap-vcpkg.sh (#10847), OpenSUSE Leap does not necessarily work the same as Ubuntu.
- I myself have worked on AIX, HP-UX and Sun Solaris Unix systems and IBM, HP and Sun all put their own spin on their flavor of Unix... I am sure the same applies with Red Hat, OpenSUSE, Ubuntu, ... etc - each having their own spin on how their Linux system works.
- **Do note** the OpenSUSE Leap 15.1 is **NOT WSL** - it resides within a Hyper-V machine installed from the OpenSUSE Leap x86_64 bit distribution DVD.
- A screen shot of the same location:
![image](https://user-images.githubusercontent.com/16106113/79778684-26f7b880-8307-11ea-87f5-39998a3eb4c5.png)
- Unfortunately each distro with their own spin on their version of Linux cause more issues trying to support them all, and I feared this would start happening when vcpkg started supporting Linux distros :(
- My question is then - _is vcpkg going to support OpenSUSE 64-bit_?

**Comment by LilyWangL** [comment]
@ras0219-msft Could you help take a look? We don't have OpenSUSE machine. Thanks.

**Comment by timautry** [comment]
Unfortunately this issue also exists in OpenSUSE 15.2 installed on WSL2.
![image](https://user-images.githubusercontent.com/16106113/86494725-5b92e200-bd44-11ea-83e1-72debfbcf788.png)

No lib just lib64 on OpenSUSE 15.2 x64 on WSL2.
![image](https://user-images.githubusercontent.com/16106113/86494819-bcbab580-bd44-11ea-8b6e-0f89677cffaa.png)

**Comment by timautry** [comment]
PR #12255 should fix this issue for mpg123 port only.
