### ISSUE TITLE
VC++ compiler failed to compile UTF-8 files without BOM

### ISSUE THREAD

**Issue by ZeppLu** [Microsoft/vcpkg#1092]
I tried to compile qt5.8 and failed, in `build-x64-windows-rel-out.log`, I found this error:

> D:\Dev\vcpkg\buildtrees\qt5\src\qt-5.8.0\qtbase\src\plugins\generic\tuiotouch\qtuiohandler.cpp(491): error C2001: 常量中有换行符 (translation: newline in constant)

You can manually check this file, and there's a Unicode character in the 491th line. I googled a lot, and it's said that `cl.exe` would interpret source files using the same encoding as system, unless the file has BOM. Windows simplified-Chinese version use GBK encoding, so `cl.exe` misinterpreted that Unicode character as something containing newline.

According to [MSDN](https://msdn.microsoft.com/en-us/library/mt708819.aspx), you can specify command line option `-source-charset:utf-8` to force `cl.exe` to understand UTF-8.

Firstly, I tried to modified `portfile.cmake` to add option `QMAKE_CXXFLAGS+="-source-charset:utf-8"` when configuring qt. But that brought another problem: if I do so, the generated Makefile would miss `-I D:\Dev\vcpkg\installed\x64-windows\include`, so source files that include other packages's staff like `zlib.h` would fail to compile. It's weird, I can't figure out the reason.

Then, I turned to modify `vcpkg\buildtrees\qt5\src\qt-5.8.0\qtbase\mkspecs\common\msvc-desktop.conf` to add option `QMAKE_CFLAGS+="-source-charset:utf-8"`. It did solve this problem, though it's kind of a dirty trick. Can anyone find a neater solution?

PS: I believe that #1037 and #1024 are actually the same as this issue, since the openners are both Chinese (you can check their profiles).

**Comment by ZeppLu** [comment]
Sorry I forgot it...
System: Windows 10 Education 15063, locale zh-cn
vcpkg version: 0.0.81-8379a80abe5288c7c06d5b9ab16efe355d1c6f62

**Comment by ras0219-msft** [comment]
Thanks for reporting this! We build all CMake projects with `/utf-8` for exactly this reason, so we should use that flag here as well for consistency.

While a similar "dirty trick", I've added `/utf-8` to `%_CL_%` in the branch qt5-gbk, which should work. Could you try that branch out and confirm it works on your machine?

**Comment by ZeppLu** [comment]
Works like a charm! But actually my solution is much more dirty than yours, since it can cause mkspec in the installed path to be modified either.

**Comment by ras0219-msft** [comment]
Thanks for verifying!
