### ISSUE TITLE
[cpprestsdk] port missing package version file (can't use cmake package versioning)

### ISSUE THREAD

**Issue by diablodale** [microsoft/vcpkg#10938]
The `cpprestsdk` port is missing the package version file. Therefore it is not possible in cmake to use package version checking as in `find_package(cpprestsdk 2.8.0 CONFIG REQUIRED)`

This is duplicate of the incorrectly dup-closed https://github.com/microsoft/vcpkg/issues/5231. The user @LilyWangL mistakenly collapsed two distinct issues as one. It is *not* a duplicate of https://github.com/microsoft/vcpkg/issues/5040

### Repro

1. Setup a working vspkg with VS2019
2. `vcpkg install cpprestsdk`
3. Create your app's `CMakeLists.txt` with the needed toolchain file
4. Add to that `CMakeLists.txt` the following: `find_package(cpprestsdk 2.8.0 CONFIG REQUIRED)`

### Result

```
[cmake] CMake Error at C:/njs/vcpkg/scripts/buildsystems/vcpkg.cmake:329 (_find_package):
[cmake]   Could not find a configuration file for package "cpprestsdk" that is
[cmake]   compatible with requested version "2.8.0".
[cmake] 
[cmake]   The following configuration files were considered but not accepted:
[cmake] 
[cmake]     C:/njs/vcpkg/installed/x86-windows-static-md-v142-sdk81/share/cpprestsdk/cpprestsdk-config.cmake, version: unknown
[cmake] 
[cmake] Call Stack (most recent call first):
[cmake]   CMakeLists.txt:127 (find_package)
```

### Expected

No errors and a later successful compile using the `cpprestsdk` library.

### Solution

Add package versioning information to the port as described in official cmake docs https://cmake.org/cmake/help/v3.0/manual/cmake-packages.7.html#package-version-file

### Notes

A repeat reminder...this is not an issue with vcpkg installing/compiling a specific version. Those are other open issues.

Instead, this is an issue with the port `cpprestsdk` does not contain the package version file. Therefore an app's CMakeLists.txt can not express or require a specific version of the port using `find_package(cpprestsdk 2.8.0 CONFIG REQUIRED)`

### Describe alternatives you've considered
No reasonable alternative other than to remove package version in `find_package()`. Otherwise, the alternative is to implement what is already built into cmake.

**Comment by BillyONeal** [comment]
Isn't this a change that needs to happen in Microsoft/cpprestsdk instead of here?

**Comment by diablodale** [comment]
❔😵 Maaybe. Happy to move the convo over there if so.

I see a correct version in structured fields in both this repo's `portfile.cmake` and `CONTROL` for cpprestsdk. At my current level of understanding, I don't know if vcpkg.exe uses/exposes/mutates those versions so they are exposed to vcpkg's CMAKE_TOOLCHAIN_FILE, etc. Or perhaps "helps" ports by autogen such cmake version if if that port doesn't do it themselves.

**Comment by horenmar** [comment]
@BillyONeal It should happen upstream, and cpprestsdk should be responsive enough (:wink:) that it is better place to solve this issue.

**Comment by BillyONeal** [comment]
@horenmar Yes, but I don't know how any of this cmake versioning works to make such a change. I'm just saying that in general, patching it in vcpkg should only be done if it can't be patched upstream.

**Comment by horenmar** [comment]
I was gonna say that it is easy, but then I actually looked at cpprestsdk's CMakeLists, and welp 🤷 

Usually you just [set the version as project's property](https://github.com/catchorg/Catch2/blob/89f5f8435176aad44624442b7f1e874a513bee67/CMakeLists.txt#L17), and then you use [CMake's helpers to create a simple Config + Version file, like so](https://github.com/catchorg/Catch2/blob/89f5f8435176aad44624442b7f1e874a513bee67/CMakeLists.txt#L110-L172).

**Comment by diablodale** [comment]
I consider this specific issue closed. The cpprestsdk port fixed the version issue on 25 April 2020. 

For those that find this issue, I've written a cmake helper function to require a specific semver or newer of any vcpkg installed package https://gist.github.com/diablodale/471341d2e139b0b42f4270c78f031378
