### ISSUE TITLE
[icu] build failure

### ISSUE THREAD

**Issue by chikanakawork** [microsoft/vcpkg#10937]
I received an error message during installing c++ libraries CGAL and Qt5.  
I would appreciate if you let me know how to solve the issue. 
Thanks. 

**Host Environment**
- OS: Windows10

**To Reproduce**
`./vcpkg.exe install cgal:x64-windows`
`./vcpkg.exe install qt5:x64-windows`

**Failure logs** 
C:\Users\natmi\Chikara_Work\dev\vcpkg>vcpkg.exe install qt5:x64-windows
Computing installation plan...
The following packages will be built and installed:
  * atlmfc[core]:x64-windows
  * freeglut[core]:x64-windows
  * icu[core]:x64-windows
  * jasper[core]:x64-windows
  * libpq[core,openssl,zlib]:x64-windows
  * libwebp[core,nearlossless,simd,unicode]:x64-windows
  * opengl[core]:x64-windows
  * openssl[core]:x64-windows
  * openssl-windows[core]:x64-windows
  * pcre2[core]:x64-windows
    qt5[core]:x64-windows
  * qt5-3d[core]:x64-windows
  * qt5-activeqt[core]:x64-windows
  * qt5-base[core]:x64-windows
  * qt5-charts[core]:x64-windows
  * qt5-datavis3d[core]:x64-windows
  * qt5-declarative[core]:x64-windows
  * qt5-gamepad[core]:x64-windows
  * qt5-graphicaleffects[core]:x64-windows
  * qt5-imageformats[core]:x64-windows
  * qt5-location[core]:x64-windows
  * qt5-mqtt[core]:x64-windows
  * qt5-multimedia[core]:x64-windows
  * qt5-networkauth[core]:x64-windows
  * qt5-purchasing[core]:x64-windows
  * qt5-quickcontrols[core]:x64-windows
  * qt5-quickcontrols2[core]:x64-windows
  * qt5-script[core]:x64-windows
  * qt5-scxml[core]:x64-windows
  * qt5-sensors[core]:x64-windows
  * qt5-serialport[core]:x64-windows
  * qt5-speech[core]:x64-windows
  * qt5-svg[core]:x64-windows
  * qt5-tools[core]:x64-windows
  * qt5-virtualkeyboard[core]:x64-windows
  * qt5-webchannel[core]:x64-windows
  * qt5-websockets[core]:x64-windows
  * qt5-winextras[core]:x64-windows
  * qt5-xmlpatterns[core]:x64-windows
  * sqlite3[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/40: icu:x64-windows
Building package icu[core]:x64-windows...
-- Using cached C:/Users/natmi/Chikara_Work/dev/vcpkg/downloads/icu4c-65_1-src.tgz
-- Using source at C:/Users/natmi/Chikara_Work/dev/vcpkg/buildtrees/icu/src/c-65_1-src-702c9cff96
-- Acquiring MSYS Packages...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: C:/Users/natmi/Chikara_Work/dev/vcpkg/downloads/tools/msys2/msys64/usr/bin/bash.exe --noprofile --norc -c "pacman -Sy --noconfirm --needed make automake1.15"
    Working Directory: C:/Users/natmi/Chikara_Work/dev/vcpkg/downloads/tools/msys2
    Error code: 1
    See logs for more information:
      C:\Users\natmi\Chikara_Work\dev\vcpkg\buildtrees\icu\msys-pacman-x64-windows-out.log
      C:\Users\natmi\Chikara_Work\dev\vcpkg\buildtrees\icu\msys-pacman-x64-windows-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_acquire_msys.cmake:108 (vcpkg_execute_required_process)
  ports/icu/portfile.cmake:77 (vcpkg_acquire_msys)
  scripts/ports.cmake:90 (include)

Error: Building package icu:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: icu:x64-windows
  Vcpkg version: 2020.02.04-nohash

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Could you please provide the error log: `C:\Users\natmi\Chikara_Work\dev\vcpkg\buildtrees\icu\msys-pacman-x64-windows-out.log`? You can attach the log file on this page.

**Comment by chikanakawork** [comment]
Thanks for your message. 

Attached is the log file: 
  C:\Users\natmi\Chikara_Work\dev\vcpkg\buildtrees\icu\msys-pacman-x64-windows-out.log
[msys-pacman-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/4507616/msys-pacman-x64-windows-out.log)

Thanks

**Comment by LilyWangL** [comment]
Thanks for your reply. This issue is same with #10606, you can get more information from issue #10606.

**Comment by LilyWangL** [comment]
Pinging @chikanakawork, does this issue occur?

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
