### ISSUE TITLE
[spdlog] update to v1.5.0

### ISSUE THREAD

**Issue by L-Sun** [microsoft/vcpkg#10931]
Library name: spdlog

New version number:  v1.5.0

Other information that may be useful (release notes, etc...)
https://github.com/gabime/spdlog/releases/tag/v1.5.0

**Comment by NancyLi1013** [comment]
Also need to update to 1.6.0.

**Comment by NancyLi1013** [comment]
Hi @L-Sun 
Thanks for posting this issue.
`spdlog `has been updated to 1.6.1. Please try to update vcpkg and use it.
