### ISSUE TITLE
Update to CMake 3.15 or later

### ISSUE THREAD

**Issue by christophe-calmejane** [microsoft/vcpkg#10933]
****

**Is your feature request related to a problem? Please describe.**
vcpkg is currently using cmake version 3.14.
Unfortunately this version does not support the `FOLLOW_SYMLINK_CHAIN` option of `file(COPY|INSTALL)` which was added in cmake 3.15.

**Proposed solution**
Update cmake to at least 3.15

**Describe alternatives you've considered**
Installing cmake 3.15 or later on the system, and set `VCPKG_FORCE_SYSTEM_BINARIES` env var, but this is not a proper solution as all computers have to install a new cmake version and correctly set this variable

**Comment by Voskrese** [comment]
https://github.com/microsoft/vcpkg/pull/10767

**Comment by timautry** [comment]
@christophe-calmejane  Pull request to upgrade to cmake 3.17.1 already in progress: https://github.com/microsoft/vcpkg/pull/10767

**Comment by christophe-calmejane** [comment]
Oh this is great. I checked issues but not PRs :)
