### ISSUE TITLE
[freerdp] linux build failure on Ubuntu 20.04

### ISSUE THREAD

**Issue by therealkenc** [microsoft/vcpkg#10944]
**Host Environment**
- OS: Ubuntu 20.04
- Compiler: gcc 9.2.1

**To Reproduce**
`./vcpkg install freerdp`

**Failure logs** 
Relevant fail is:
```
/usr/bin/ld: /home/ken/vcpkg/installed/x64-linux/debug/lib/libgobject-2.0.a(gboxed.c.o): undefined reference to symbol 'g_markup_parse_context_ref'
/usr/bin/ld: /lib/x86_64-linux-gnu/libglib-2.0.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```
[install-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/4507692/install-x64-linux-dbg-out.log)

**Additional context**
The glib dependency seems to have built.

![image](https://user-images.githubusercontent.com/7049700/79827161-78796500-8352-11ea-8fc8-57363eb2492e.png)

**Comment by LilyWangL** [comment]
Thanks for posting this issue. I installed freerdp successfully with the VCPKG latest source on Linux. Did you run `git pull` before installing freerdp?

**Comment by therealkenc** [comment]
Yes I had just installed it.

![image](https://user-images.githubusercontent.com/7049700/80188930-baaadc80-85c6-11ea-8517-9e88f0208f93.png)

**Comment by therealkenc** [comment]
I happened to have a Ubuntu 18.04 around and it did build sucessfully. The run above is on Ubuntu 20.04.

**Comment by LilyWangL** [comment]
Sorry I am late. Due to I don't have Ubuntu 20.04 machine, could you please try to install new version freerdp on Ubuntu 20.04? The attached file is the new version freerdp file.
[freerdp.zip](https://github.com/microsoft/vcpkg/files/4790655/freerdp.zip)

**Comment by therealkenc** [comment]
Hi Lili, my bad too, apologies I missed the notification on this. Yes confirmed we're good with freerdp2 off of `git` current (ie as of this writing) on an up to date Ubuntu 20.04. Thank you!

![image](https://user-images.githubusercontent.com/7049700/85112815-19f22b00-b1cb-11ea-93d7-c92b215fc4e2.png)

**Comment by LilyWangL** [comment]
I will submit a PR to update freerdp to new version, waiting for PR merged and closing this issue again.
