### ISSUE TITLE
[<port name>] build failure

### ISSUE THREAD

**Issue by MillhioreBT** [microsoft/vcpkg#10946]
**Host Environment**
- OS: Windows
- Compiler: revision

**To Reproduce**
`./vcpkg install wxwidgets:x64-windows boost:x64-windows libarchive:x64-windows`

**Failure logs** 
Warning: The following VS instances are excluded because the English language pack is unavailable.
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
Please install the English language pack.
-- Using cached C:/vcpkg/downloads/libjpeg-turbo-libjpeg-turbo-166e34213e4f4e2363ce058a7bcc69fd03e38b76.tar.gz
-- Using source at C:/vcpkg/buildtrees/libjpeg-turbo/src/fd03e38b76-a5b0f5fafe
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: ninja -v
    Working Directory: C:/vcpkg/buildtrees/libjpeg-turbo/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\vcpkg\buildtrees\libjpeg-turbo\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:297 (vcpkg_execute_required_process)
  ports/libjpeg-turbo/portfile.cmake:33 (vcpkg_configure_cmake)
  scripts/ports.cmake:90 (include)

Error: Building package libjpeg-turbo:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libjpeg-turbo:x64-windows
  Vcpkg version: 2020.02.04-nohash

Additionally, attach any relevant sections from the log files above.

**Additional context**
![image](https://user-images.githubusercontent.com/28090948/79886384-c7f97880-83c6-11ea-893f-19eae2b2760c.png)

**Comment by timautry** [comment]
@MillhioreBT 
_Warning: The following VS instances are excluded because the **English language pack is unavailable**._
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
**Please install the English language pack.**

**Comment by MillhioreBT** [comment]
> @MillhioreBT
> _Warning: The following VS instances are excluded because the **English language pack is unavailable**._
> C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
> **Please install the English language pack.**

Working! thank, sorry for the my stupid question.
