### ISSUE TITLE
[New Port Request] libtomcrypt

### ISSUE THREAD

**Issue by crmoore** [microsoft/vcpkg#10948]
Library name: libtomcrypt

Library description: LibTomCrypt is a fairly comprehensive, modular and portable cryptographic toolkit that provides developers with a vast array of well known published block ciphers, one-way hash functions, chaining modes, pseudo-random number generators, public key cryptography and a plethora of other routines. 

Source repository URL: https://github.com/libtom/libtomcrypt

Project homepage (if different from the source repository): https://www.libtom.net

Anything else that is useful to know when adding (such as optional features the library may have that should be included): requires libtommath

**Comment by Voskrese** [comment]
https://github.com/microsoft/vcpkg/issues/10466
https://github.com/microsoft/vcpkg/issues/10947
