### ISSUE TITLE
[New Port Request] triton

### ISSUE THREAD

**Issue by illera88** [microsoft/vcpkg#10942]
Library name: triton

Library description: Triton is a Dynamic Binary Analysis (DBA) framework. It provides internal components like a Dynamic Symbolic Execution (DSE) engine, a dynamic taint engine, AST representations of the x86, x86-64, ARM32 and AArch64 Instructions Set Architecture (ISA), SMT simplification passes, an SMT solver interface and, the last but not least, Python bindings.

Source repository URL: https://github.com/JonathanSalwan/Triton

Project homepage (if different from the source repository): http://triton.quarkslab.com

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
Triton dependencies are `boost`, `capstone` and `z3` all of them already supported by vcpkg.
Triton has python bindings that should be optional when building.

Cheers

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
