### ISSUE TITLE
Dynamic build of packages with static dependencies possible?

### ISSUE THREAD

**Issue by jabra98** [microsoft/vcpkg#10940]
How can I build dynamic versions of packages but with their respective dependencies linked statically. For example if I have one package A which has a dependency to B. I would rather want A to link B statically so I don't have A's shared libraries depend on B shared libraries when including it in my project. Is this possible?

**Comment by JackBoosY** [comment]
You can add `vcpkg_check_linkage(ONLY_STATIC_LIBRARY)` to the top of `portfile.cmake` that needs to be built as a static port.

**Comment by jabra98** [comment]
And this will then generate dynamic libraries for the package I am installing but with it’s dependencies statically linked to it?

**Comment by Neumann-A** [comment]
See https://github.com/microsoft/vcpkg/blob/master/docs/users/triplets.md in the section `per-port customization` 
You simply want your dependent ports be build with `VCPKG_LIBRARY_LINKAGE` set to `static`

**Comment by jabra98** [comment]
I see, thanks
