### ISSUE TITLE
install boost fail in win10

### ISSUE THREAD

**Issue by xiaohui96** [microsoft/vcpkg#10953]
when I use .\vcpkg install boost in win10, it always can't install successfully. Error: Building package boost-compatibility:x86-windows failed with：BUILD_FAILED.

**Comment by linquize** [comment]
Error log please

**Comment by LilyWangL** [comment]
Pinging @xiaohui96

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Please open a new issue if this is still a problem for you.
