### ISSUE TITLE
Install and Build vcpkg on Jetson Nano Arch64 Ubuntu Nano

### ISSUE THREAD

**Issue by Stricklyspeaking** [microsoft/vcpkg#10955]
**Host Environment**
- Linux Ubuntu Nano on aarch64 4.9.140-tegra
Nvedia Jetson Nano

**To Reproduce**
Downloaded vcpkg   https://github.com/microsoft/vcpkg.git   (2020.01.31)

**Failure logs** 
./bootstrap-vcpkg.sh  required a newer version than make version 3.10 included with my referenced distribution.

**Additional context**
When vcpkg is not available from your distribution you must build this from source.
Building vcpkg requires a more recient version of cmake – 3.13 or so.
The reality is that most linux distributions are not that current on cmake so you
Have to build cmake from source.  When I pulled down cmake source 3.16 to build it was  looking for some special openssl configuration files that did not exist on my linux. I saw a lot of posings on the web about this issue. So I pulled down version 3.17 of cmake and this version builds fine. It did take a lot of time. 

I had previously pulled down the vcpkg source and discovered the build files were in ~/vcpkg/toolsrc. So went there and …
Mkdir build
Cd build
Make

There is no install included in the Makefile generated by CMaketext.txt.
A reboot was required.

If I run ./bootstrap-vcpkg.sh at this point this is what I see....

sudo ./bootstrap-vcpkg.sh
./bootstrap-vcpkg.sh: 243: /home/bob/vcpkg/scripts/bootstrap.sh: /home/bob/vcpkg/downloads/tools/cmake-3.14.0-linux/cmake-3.14.0-Linux-x86_64/bin/cmake: Exec format error 

Bob

**Comment by linquize** [comment]
In the mean time, you can lower the required cmake version to 3.13, by editing `toolsrc/CMakeLists.txt`
```cmake
cmake_minimum_required(VERSION 3.13)
```

Same for raspbian buster that ships arm cmake 3.13

**Comment by Voskrese** [comment]
**Linux-x86_64** /bin/cmake: **Exec format error**

Ubuntu Nano on **aarch64**

**Comment by linquize** [comment]
```bash
sudo apt-get install cmake
./bootstrap-vcpkg.sh --useSystemBinaries
VCPKG_FORCE_SYSTEM_BINARIES=1 ./vcpkg instal xxx
```

**Comment by NancyLi1013** [comment]
Hi @Stricklyspeaking 

Thanks for posting this issue.
Please update cmake version on your local to rebuild. 

In vcpkg latest version, vcpkg requires cmake min version 3.14. So we need higher or equal cmake 3.14 to build.
But if you want to use cmake you installed, you can try to change the minimum version as @linquize suggested above.

**Comment by NancyLi1013** [comment]
I'm going to close this issue for now due to no response in a  long time,
Please feel free to reopen this issue if this is still a problem for you.
