### ISSUE TITLE
[SQLiteCpp] update to 3.0.0

### ISSUE THREAD

**Issue by iwongdotcn** [microsoft/vcpkg#10968]
Library name: SQLiteCpp

New version number: 3.0.0

Version 3.0.0 - January 31 2020

C++11 is now required
CMake 3.1 minimum
Visual Studio 2015 minimum
Update Googletest to latest release 1.10
Add Github Actions continuous integration solution
Add Valgrind memcheck tool to Travis CI
Remove Statement::isOk() deprecated in 2.2.0 when renamed to Statement::hasRow()
Replace Database::backup() "C" implementation by calling the Backup class
#252 Run Valgrind memcheck on Travis CI
#253 Keep inline functions for GCov code coverage
#254 Re-enable Coverity static analysis
#256 Fix linking with system library (libsqlite3)
#242 Added a getIndex method and used it (KOLANICH)
#257 Improve Statement unit tests coverage (bind by name with a std::string)
#234 support for external sqlite3 (BioDataAnalysis/emmenlau)
#243 adding a pure attribute to getIndex() (KOLANICH)

**Comment by iwongdotcn** [comment]
https://github.com/SRombauts/SQLiteCpp/releases/tag/3.0.0

**Comment by LilyWangL** [comment]
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.
