### ISSUE TITLE
C-Ares build error

### ISSUE THREAD

**Issue by jmin911** [Microsoft/vcpkg#1096]
When installing grpc static, it pulled c-ares as well.  But c-ares failed with the following messages:
There should be no bin\ directory in a static build, but C:\src\vcpkg\packages\c-ares_x86-windows-static\bin is present.
There should be no debug\bin\ directory in a static build, but C:\src\vcpkg\packages\c-ares_x86-windows-static\debug\bin is present.
If the creation of bin\ and/or debug\bin\ cannot be disabled, use this in the portfile to remove them

    if(VCPKG_LIBRARY_LINKAGE STREQUAL static)
        file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/bin ${CURRENT_PACKAGES_DIR}/debug/bin)
    endif()

There should be no empty directories in C:/src/vcpkg/packages/c-ares_x86-windows-static
The following empty directories were found:

    C:/src/vcpkg/packages/c-ares_x86-windows-static/bin
    C:/src/vcpkg/packages/c-ares_x86-windows-static/debug/bin

If a directory should be populated but is not, this might indicate an error in the portfile.
If the directories are not needed and their creation cannot be disabled, use something like this in the portfile to remove them:

    file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/a/dir ${CURRENT_PACKAGES_DIR}/some/other/dir)

Found 2 error(s). Please correct the portfile:
    C:\src\vcpkg\ports\c-ares\portfile.cmake
-- Performing post-build validation done
Error: Building package c-ares:x86-windows-static failed with: POST_BUILD_CHECKS_FAILED

**Comment by KindDragon** [comment]
Sorry about that. My PR should fix this.
