### ISSUE TITLE
[New Port Request] tlx

### ISSUE THREAD

**Issue by iwongdotcn** [microsoft/vcpkg#10970]
Library name: tlx

Library description: Collection of Sophisticated C++ Data Structures, Algorithms, and Miscellaneous Helpers

Source repository URL: https://github.com/tlx/tlx

Project homepage (if different from the source repository): http://tlx.github.io/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by NancyLi1013** [comment]
Hi @iwongdotcn 
Thanks for posting this request.

tlx has been added to vcpkg now. Please try to update vcpkg to the latest version and use it.
