### ISSUE TITLE
[glfw3] build failure

### ISSUE THREAD

**Issue by Vaitrix** [microsoft/vcpkg#10985]
I am trying to install the package glfw3 on my computer but an error pops up. 
Appreciate any help on the matter. 
Thank you!

**Host Environment**
- OS: Windows

**To Reproduce**
.\vcpkg install glfw3

**Failure logs** 
Computing installation plan...
The following packages will be built and installed:
    glfw3[core]:x86-windows
A suitable version of powershell-core was not found (required v6.2.1). Downloading portable powershell-core v6.2.1...
Downloading powershell-core...
  https://github.com/PowerShell/PowerShell/releases/download/v6.2.1/PowerShell-6.2.1-win-x86.zip -> C:\Users\lenovo\Documents\GitHub\vcpkg\vcpkg\downloads\PowerShell-6.2.1-win-x86.zip
Extracting powershell-core...
A suitable version of 7zip was not found (required v18.1.0). Downloading portable 7zip v18.1.0...
Downloading 7zip...
  https://www.nuget.org/api/v2/package/7-Zip.CommandLine/18.1.0 -> C:\Users\lenovo\Documents\GitHub\vcpkg\vcpkg\downloads\7-zip.commandline.18.1.0.nupkg
Extracting 7zip...
A suitable version of nuget was not found (required v4.8.1). Downloading portable nuget v4.8.1...
Downloading nuget...
  https://dist.nuget.org/win-x86-commandline/v4.8.1/nuget.exe -> C:\Users\lenovo\Documents\GitHub\vcpkg\vcpkg\downloads\nuget.exe
Starting package 1/1: glfw3:x86-windows
Building package glfw3[core]:x86-windows...
A suitable version of git was not found (required v2.25.1). Downloading portable git v2.25.1...
Downloading git...
  https://github.com/git-for-windows/git/releases/download/v2.25.1.windows.1/PortableGit-2.25.1-32-bit.7z.exe -> C:\Users\lenovo\Documents\GitHub\vcpkg\vcpkg\downloads\PortableGit-2.25.1-32-bit.7z.exe
Extracting git...
-- Downloading https://github.com/glfw/glfw/archive/3.3.2.tar.gz...
-- Downloading https://github.com/glfw/glfw/archive/3.3.2.tar.gz... Failed. Status: 22;"HTTP response code said error"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:175 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:132 (vcpkg_download_distfile)
  ports/glfw3/portfile.cmake:1 (vcpkg_from_github)
  scripts/ports.cmake:90 (include)

Error: Building package glfw3:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: glfw3:x86-windows
  Vcpkg version: 2020.02.04-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by kreuzerkrieg** [comment]
it was outage at github service
https://www.githubstatus.com/

try now

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Please open a new issue if this is still a problem for you.
