### ISSUE TITLE
Install failure due to full disk not detected

### ISSUE THREAD

**Issue by s-bear** [microsoft/vcpkg#10997]
**Description**
I was attempting to install halide[core,opencl,opengl]:x64-windows, which requires llvm[core,tools,utils]:x64-windows. I did not have sufficient disk space available to install llvm. vcpkg reported errors while installing llvm (see logs below), but continued with the halide build regardless, then failed the halide build because llvm was missing. After freeing disk space vcpkg continues to fail, assuming llvm is installed when it is not. It appears that vcpkg did not detect the errors while installing llvm's files and assumed that it installed correctly.

**Environment**
- OS: Windows 10 Enterprise (10.0.18363 Build 18363)
- Compiler: Microsoft Visual Studio 2017, `cl.exe` reports version 19.16.27031.1 for x64
- `vcpkg version` reports: `Vcpkg package management program version 2020.02.04-nohash`

**To Reproduce**
1. Without llvm or halide installed and with less than 77.6 GB of disk space:
2. `./vcpkg install llvm[core,tools,utils]:x64-windows halide[core,tools,utils]:x64-windows`
3. llvm build fails due to lack of disk space, halide build attempted but fails due to missing llvm
4. free disk space, sufficient for llvm build
5. `./vcpkg install llvm[core,tools,utils]:x64-windows halide[core,tools,utils]:x64-windows`
6. llvm does not reinstall, halide build fails due to missing llvm

**Expected behavior**
llvm and halide are installed succesfully

**Failure logs** 
- Command line session: [vcpkg disk-space error logs.txt](https://github.com/microsoft/vcpkg/files/4526608/vcpkg.disk-space.error.logs.txt)
- [buildtrees/llvm/install-x64-windows-rel-err.log](https://github.com/microsoft/vcpkg/files/4526552/install-x64-windows-rel-err.log)
- [buildtrees/llvm/install-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/4526553/install-x64-windows-rel-out.log)
- [buildtrees/llvm/stdout-x64-windows.log](https://github.com/microsoft/vcpkg/files/4526559/stdout-x64-windows.log)
- [buildtrees/halide/config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/4526611/config-x64-windows-out.log)

**Additional context**
None.

**Comment by timautry** [comment]
- Try `.\vcpkg.exe remove llvm:x64-windows`
- then: `.\vcpkg.exe install llvm[<features>]:x64-windows`
- If llvmt installs properly, then proceed with `.\vcpkg.exe install halide[<features>]:x64-windows`
Notes: 
1. llvm take around 85 gb of disk space for a full build with all features installed.
2. If llvm will not install properly, the vcpkg instance may be corrupted, requiring the deletion and recloning, compiling, linking of vcpkg along with reinstalling all the ports[<features>] wishing to be installed.

**Comment by s-bear** [comment]
@timautry removing and reinstalling llvm was a successful workaround, and thanks for the heads-up about how much space is required!
I also edited my triplets file to do release-only builds (`set(VCPKG_BUILD_TYPE release)`) which should help with my lack of disk space.
Cheers,
Sam

**Comment by LilyWangL** [comment]
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.
