### ISSUE TITLE
The version in description of qt5[latest] is wrong

### ISSUE THREAD

**Issue by spindensity** [microsoft/vcpkg#10998]
**Describe the bug**

Execute:

```
vcpkg search qt5
```

Output:

```
qt5[latest]                           Build latest qt version (5.14.1) instead of LTS
```

But the actual version is `5.14.2` (not `5.14.1`) according to #10644 and the `CONTROL` file of  `qt5-base`:

```
Feature: latest
Description: Build latest qt version (5.14.2) instead of LTS
```

**Comment by Neumann-A** [comment]
Yeah seems like I forgot to update the information in the qt5 metaport and nobody noticed it. Fixed in #10749
