### ISSUE TITLE
[boost-regex] build failure

### ISSUE THREAD

**Issue by LucaFuma74** [microsoft/vcpkg#10990]
**Host Environment**
- OS: Windows 10
- Compiler: MSVC <toolset-msvc:version>14.0

**To Reproduce**
.\vcpkg install boost:x64-windows

**Failure logs** 
Error: Building package boost-regex:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-regex:x64-windows
  Vcpkg version: 2020.02.04-nohash

-Please attach any additional failure logs mentioned in the console output.

compile-c-c++ D:\WRK\ExtLibraries\vcpkg\buildtrees\boost-regex\x64-windows-rel\boost\build\205baa6b740ec306ccf03465a04a5936\usinstances.obj
usinstances.cpp
msvc.link.dll D:\WRK\ExtLibraries\vcpkg\buildtrees\boost-regex\x64-windows-rel\boost\build\205baa6b740ec306ccf03465a04a5936\boost_regex-vc140-mt-x64-1_72.dll
   Creazione della libreria D:\WRK\ExtLibraries\vcpkg\buildtrees\boost-regex\x64-windows-rel\boost\build\205baa6b740ec306ccf03465a04a5936\boost_regex-vc140-mt-x64-1_72.lib e dell'oggetto D:\WRK\ExtLibraries\vcpkg\buildtrees\boost-regex\x64-windows-rel\boost\build\205baa6b740ec306ccf03465a04a5936\boost_regex-vc140-mt-x64-1_72.exp
msvc.manifest.dll D:\WRK\ExtLibraries\vcpkg\buildtrees\boost-regex\x64-windows-rel\boost\build\205baa6b740ec306ccf03465a04a5936\boost_regex-vc140-mt-x64-1_72.dll
"mt" non è riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch.

        if exist "D:\WRK\ExtLibraries\vcpkg\buildtrees\boost-regex\x64-windows-rel\boost\build\205baa6b740ec306ccf03465a04a5936\boost_regex-vc140-mt-x64-1_72.dll.manifest" (
            call "D:\WRK\ExtLibraries\vcpkg\buildtrees\boost-regex\x64-windows-rel\boost\standalone\msvc\a1c47416b677e1e61abd4f30699dc29c\msvc-setup.bat" amd64 >nul
 mt -manifest "D:\WRK\ExtLibraries\vcpkg\buildtrees\boost-regex\x64-windows-rel\boost\build\205baa6b740ec306ccf03465a04a5936\boost_regex-vc140-mt-x64-1_72.dll.manifest" "-outputresource:D:\WRK\ExtLibraries\vcpkg\buildtrees\boost-regex\x64-windows-rel\boost\build\205baa6b740ec306ccf03465a04a5936\boost_regex-vc140-mt-x64-1_72.dll;2"
        )
    
...failed msvc.manifest.dll D:\WRK\ExtLibraries\vcpkg\buildtrees\boost-regex\x64-windows-rel\boost\build\205baa6b740ec306ccf03465a04a5936\boost_regex-vc140-mt-x64-1_72.dll D:\WRK\ExtLibraries\vcpkg\buildtrees\boost-regex\x64-windows-rel\boost\build\205baa6b740ec306ccf03465a04a5936\boost_regex-vc140-mt-x64-1_72.lib D:\WRK\ExtLibraries\vcpkg\buildtrees\boost-regex\x64-windows-rel\boost\build\205baa6b740ec306ccf03465a04a5936\boost_regex-vc140-mt-x64-1_72.pdb D:\WRK\ExtLibraries\vcpkg\buildtrees\boost-regex\x64-windows-rel\boost\build\205baa6b740ec306ccf03465a04a5936\boost_regex-vc140-mt-x64-1_72.pdb...
...removing D:\WRK\ExtLibraries\vcpkg\buildtrees\boost-regex\x64-windows-rel\boost\build\205baa6b740ec306ccf03465a04a5936\boost_regex-vc140-mt-x64-1_72.dll
...removing D:\WRK\ExtLibraries\vcpkg\buildtrees\boost-regex\x64-windows-rel\boost\build\205baa6b740ec306ccf03465a04a5936\boost_regex-vc140-mt-x64-1_72.lib
...removing D:\WRK\ExtLibraries\vcpkg\buildtrees\boost-regex\x64-windows-rel\boost\build\205baa6b740ec306ccf03465a04a5936\boost_regex-vc140-mt-x64-1_72.pdb
...failed updating 1 target...
...updated 20 targets...

**Comment by timautry** [comment]
**"mt" is not recognized as internal or external command,**
**an executable program or a batch file.**

**mt** is part of the Windows SDK. 
vcpkg requires Windows SDK version 8.1 or higher.

See requirements **Quick Start** Prerequisites section: https://github.com/microsoft/vcpkg

**Comment by LucaFuma74** [comment]
Thanks Timautry! My mistake... All the best.

**Comment by timautry** [comment]
You are most welcome! Glad it worked.
