### ISSUE TITLE
[ websocketpp:x86-windows-static] build failure[boost-regex] build failure

### ISSUE THREAD

**Issue by tjhappy** [microsoft/vcpkg#10995]
Host Environment

OS: Windows 10
Compiler: MSVC toolset-msvc:version14.1
To Reproduce
.\vcpkg install websocketpp:x86-windows-static]

Failure logs
```
Building package zlib[core]:x86-windows-static...
-- Using community triplet x86-windows-static. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: C:\Dev\vcpkg\triplets\community\x86-windows-static.cmake
-- Using cached C:/Dev/vcpkg/downloads/zlib1211.tar.gz
-- Using source at C:/Dev/vcpkg/buildtrees/zlib/src/1.2.11-deec42f53b
-- Configuring x86-windows-static
-- Building x86-windows-static-dbg
-- Building x86-windows-static-rel
-- Installing: C:/Dev/vcpkg/packages/zlib_x86-windows-static/share/zlib/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package zlib[core]:x86-windows-static... done
Installing package zlib[core]:x86-windows-static...
Installing package zlib[core]:x86-windows-static... done
Elapsed time for package zlib:x86-windows-static: 7.233 s
Starting package 62/62: websocketpp:x86-windows-static
Building package websocketpp[core]:x86-windows-static...
-- Using community triplet x86-windows-static. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: C:\Dev\vcpkg\triplets\community\x86-windows-static.cmake
-- Using cached C:/Dev/vcpkg/downloads/zaphoyd-websocketpp-1c699ce46843a787482a703fdeff9271fbb7bb5d.tar.gz
-- Using source at C:/Dev/vcpkg/buildtrees/websocketpp/src/71fbb7bb5d-a523570fc1
-- Performing post-build validation
There should be no empty directories in C:\Dev\vcpkg\packages\websocketpp_x86-windows-static
The following empty directories were found:

    C:/Dev/vcpkg/packages/websocketpp_x86-windows-static/include/websocketpp/.vs/websocketpp/v15

If a directory should be populated but is not, this might indicate an error in the portfile.
If the directories are not needed and their creation cannot be disabled, use something like this in the portfile to remove them:

    file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/a/dir" "${CURRENT_PACKAGES_DIR}/some/other/dir")


Found 1 error(s). Please correct the portfile:
    C:\Dev\vcpkg\ports\websocketpp\portfile.cmake
-- Performing post-build validation done
Error: Building package websocketpp:x86-windows-static failed with: POST_BUILD_CHECKS_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: websocketpp:x86-windows-static
  Vcpkg version: 2020.02.04-nohash
```

**Comment by JackBoosY** [comment]
websocketpp is a header only library, and the path _C:/Dev/vcpkg/packages/websocketpp_x86-windows-static_ should not be used.
Did you use that path manually?

**Comment by tjhappy** [comment]
I used .\vcpkg install websocketpp:x86-windows. It's ok. Last,i uesd .\vcpkg install websocketpp:x86-windows-static,failed

**Comment by JackBoosY** [comment]
@tjhappy Please remove _C:/Dev/vcpkg/packages/websocketpp_x86-windows-static_, remove `websocketpp:x86-windows-static` and rebuild it.

Thanks.

**Comment by tjhappy** [comment]
I removed C:/Dev/vcpkg/packages/websocketpp_x86-windows-static, remove websocketpp:x86-windows-static and rebuild it.
error info:
PS C:\Dev\vcpkg> .\vcpkg remove websocketpp:x86-windows-static
The following packages are not installed, so not removed:
    websocketpp:x86-windows-static
Package websocketpp:x86-windows-static is not installed
Purging package websocketpp:x86-windows-static...
Purging package websocketpp:x86-windows-static... done
PS C:\Dev\vcpkg> .\vcpkg install websocketpp:x86-windows-static
Computing installation plan...
The following packages will be built and installed:
    websocketpp[core]:x86-windows-static
Starting package 1/1: websocketpp:x86-windows-static
Building package websocketpp[core]:x86-windows-static...
-- Using community triplet x86-windows-static. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: C:\Dev\vcpkg\triplets\community\x86-windows-static.cmake
-- Using cached C:/Dev/vcpkg/downloads/zaphoyd-websocketpp-1c699ce46843a787482a703fdeff9271fbb7bb5d.tar.gz
-- Using source at C:/Dev/vcpkg/buildtrees/websocketpp/src/71fbb7bb5d-a523570fc1
-- Performing post-build validation
There should be no empty directories in C:\Dev\vcpkg\packages\websocketpp_x86-windows-static
The following empty directories were found:

    C:/Dev/vcpkg/packages/websocketpp_x86-windows-static/include/websocketpp/.vs/websocketpp/v15

If a directory should be populated but is not, this might indicate an error in the portfile.
If the directories are not needed and their creation cannot be disabled, use something like this in the portfile to remove them:

    file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/a/dir" "${CURRENT_PACKAGES_DIR}/some/other/dir")


Found 1 error(s). Please correct the portfile:
    C:\Dev\vcpkg\ports\websocketpp\portfile.cmake
-- Performing post-build validation done
Error: Building package websocketpp:x86-windows-static failed with: POST_BUILD_CHECKS_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: websocketpp:x86-windows-static
  Vcpkg version: 2020.02.04-nohash

**Comment by tjhappy** [comment]
I found the erro. "-- Using source at C:/Dev/vcpkg/buildtrees/websocketpp/src/71fbb7bb5d-a523570fc1"  is error. I remove the "C:/Dev/vcpkg/buildtrees/websocketpp" and build .It's ok.
Thanks.
