### ISSUE TITLE
Glew:x64-windows install failure

### ISSUE THREAD

**Issue by operativeF** [Microsoft/vcpkg#11]
Glew:x64-windows fails to install, citing that that the Windows 8.1 SDK wasn't found.

[build-x64-windows-rel-out.txt](https://github.com/Microsoft/vcpkg/files/481533/build-x64-windows-rel-out.txt)

I tried retargeting the files and solution, and it still didn't work.

**Comment by sdcb** [comment]
Looks like file /ports/glew/portfile.cmake is hard code to "Win32", you can switch the "Win32" to "x64" by hand, and build again to resolve this issue temperately.
