### ISSUE TITLE
[<port name>] build failure

### ISSUE THREAD

**Issue by Amine74** [microsoft/vcpkg#11008]
**Host Environment**
Windows 8.1
cmake-3.17.1-win64-x64
Microsoft Visual Studio Community 2019
Version 16.5.4 , Desktop Development in C++ installed with all optionals (include Windows SDK) 

**To Reproduce**
.\bootstrap-vcpkg.bat

**Failure logs**
- c:\Program Files <x86>\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets<39.4.5>: error MSB 6006 "CL.exe" stopped with the code -1073741701. [c:\Users\triki\vcpkg\toolsrc\vcpkglib\vcpkg.vcxproj]
- c:\Users\triki\vcpkg\scripts\bootstrap.ps1: Building vcpkg.exe failed. Please ensure you have installed Visual Studio with Desktop c++ workload and the Windows SDK for Desktop c++
 

**Additional context**
I have already installed the Windows SDK, but it does not seem to work. Do you have an idea what the problem is?

**Comment by timautry** [comment]
- Run the **visual studio installer** as administrator
- select **modify**
- under workloads, select **Desktop development with  C++**
- under language packs select **English**
- insure the Windows SDK install is version 8.1 or higher
- select modify
- after complete insure git is installed
- all this can be found in the Quick Start/Prerequisites section of the vcpkg read me page: https://github.com/microsoft/vcpkg

**Comment by Amine74** [comment]
Although I have followed the steps, it still doesn't work.

**Comment by timautry** [comment]
Things left to try:
- Delete the vcpkg instance and clone it again.
- Repair Visual Studio and the Windows SDK installation.
- Lastly, Remove and Reinstall Visual Studio and Windows SDK.

The only errors posted suggests vcpkg can not find Visual Studio or the Windows SDK.

**Comment by Amine74** [comment]
Repair Visual Studio solved the problem. Thanks a lot :)

**Comment by timautry** [comment]
Glad it is working now!!!
