### ISSUE TITLE
boost build failue

### ISSUE THREAD

**Issue by gaoyunjun** [microsoft/vcpkg#11005]
**Host Environment**
- OS: [e.g. Windows]
- Compiler: revision
win7 vs2017
Package: boost-preprocessor:x64-windows
  Vcpkg version: 2020.02.04-nohash

**To Reproduce**
`./vcpkg install boost:x64-windows

**Failure logs** 
Additional packages (*) will be modified to complete this operation.
Starting package 1/139: boost-preprocessor:x64-windows
Building package boost-preprocessor[core]:x64-windows...
-- Downloading https://github.com/boostorg/preprocessor/archive/boost-1.72.0.tar.gz...
-- Extracting source E:/git/vcpkg/downloads/boostorg-preprocessor-boost-1.72.0.tar.gz
-- Using source at E:/git/vcpkg/buildtrees/boost-preprocessor/src/ost-1.72.0-a796360b87
-- Packaging headers
-- Packaging headers done
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.72.0/LICENSE_1_0.txt...
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.72.0/LICENSE_1_0.txt... Failed. Status: 6;"Could
n't resolve host name"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:175 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  installed/x64-windows/share/boost-vcpkg-helpers/boost-modular-headers.cmake:17 (vcpkg_download_distfile)
  ports/boost-preprocessor/portfile.cmake:14 (boost_modular_headers)
  scripts/ports.cmake:90 (include)

Error: Building package boost-preprocessor:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:

**Comment by timautry** [comment]
Please try again - github.com has been having sporatic issues the past few days, I myself have experienced this issue and waited a while and tried again for the download to work properly.

**Comment by LilyWangL** [comment]
Pinging @gaoyunjun

**Comment by gaoyunjun** [comment]
I tried again, and it was the same question;When I was in the browser input: https://raw.githubusercontent.com/boostorg/boost/boost-1.72.0/LICENSE_1_0.txt this address, parse failed, so this should be the reason for my network, rather than VCPKG bug

**Comment by LilyWangL** [comment]
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.
