### ISSUE TITLE
qt5:x64-windows-static configuration failed.

### ISSUE THREAD

**Issue by xandox** [microsoft/vcpkg#1101]
I am try to compile qt5 with static libs but it fail on configuration step.
[qt5-x64-windows-static-configure-logs.zip](https://github.com/Microsoft/vcpkg/files/1003457/qt5-x64-windows-static-configure-logs.zip)
with x64-windows configuration works fine

**Comment by Retik** [comment]
I'm having the exact same issue.

[config.txt](https://github.com/Microsoft/vcpkg/files/1089920/config.txt)
[config-x64-windows-static-rel-err.txt](https://github.com/Microsoft/vcpkg/files/1089921/config-x64-windows-static-rel-err.txt)
[config-x64-windows-static-rel-out.txt](https://github.com/Microsoft/vcpkg/files/1089922/config-x64-windows-static-rel-out.txt)

**Comment by JackBoosY** [comment]
Hi @xandox, thanks for reporting this issue!
Since qt5 has been upgraded to 5.12.5, this issue was fixed.
Please update vcpkg and rebuild qt5:x64-windows-static.

Thnaks.
