### ISSUE TITLE
Error: Building package sdl1:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by Amine74** [microsoft/vcpkg#11014]
**Host Environment**
- Windows 8.1
- Visual Studio Commity 2019

**To Reproduce**
`./vcpkg install sdl1:x64-windows

**Failure logs** 
Error: Building package sdl1:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: sdl1:x64-windows
  Vcpkg version: 2020.02.04-nohash
Additionally, attach any relevant sections from the log files above.

**Additional context**
Any Ideas?
Note that I have already updated vcpkg and git pull

**Comment by Amine74** [comment]
In the log build-x64-windows-rel-out.log is written:
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified.

**Comment by LilyWangL** [comment]
Do you install Visual C++ https://docs.microsoft.com/en-us/cpp/overview/visual-cpp-in-visual-studio?view=vs-2019?

**Comment by LilyWangL** [comment]
Pinging @Amine74

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Please open a new issue if this is still a problem for you.
