### ISSUE TITLE
How do I use PDCurses after having installed it?

### ISSUE THREAD

**Issue by miss-programgamer** [microsoft/vcpkg#11027]
My question is fairly straightforward: After having installed pdcurses via vcpkg, how do I actually use it in one of my project's `CmakeLists.txt?` I can't seem to `find_package` it under the names `PDCurses`, `Curses`, `PDC`, or similar. The portfile doesn't make it clear what the package is named either:

https://github.com/microsoft/vcpkg/blob/master/ports/pdcurses/portfile.cmake

Plus, when I install other packages, a short snippet for how they should be included into projects is printed. For instance, SDL2 tells you to do `find_package(SDL2 CONFIG REQUIRED)` and then `target_link_libraries(main PRIVATE SDL2::SDL2 SDL2::SDL2main)`. This instruction is conspicuously missing when I install PDCurses.

I've confirmed that this is not a CMake configuration issue by doing a clean reconfigure and finding SDL2, which DOES work.

So, again, how do I include PDCurses?

**Comment by JackBoosY** [comment]
Because PDCurses did not export any cmake files.
Therefore, you need to add some custom code, for example:
```
find_path(pdcurses_INCLUDES curses.h)
find_library(pdcurses pdcurses REQUIRED)

target_include_directories(${PROJECT} PRIVATE ${pdcurses_INCLUDES})
target_link_libraries(${PROJECT} PRIVATE pdcurses)
```

**Comment by programgamer-real** [comment]
Well, that's disappointing. At least you solved my problem, so thanks.

For future readers though, it should actually be the following:

```
find_path(PDC_INCLUDES curses.h)
find_library(PDC_LIBS pdcurses REQUIRED)

target_include_directories(${PROJECT} PRIVATE ${PDC_INCLUDES})
target_link_libraries(${PROJECT} PRIVATE ${PDC_LIBS})
```

**Comment by JackBoosY** [comment]
@programgamer-real This is because the official does not support this feature, can you make this request to the official?

**Comment by programgamer-real** [comment]
Sure, should I make a new issue for this?

**Comment by JackBoosY** [comment]
@programgamer-real Yes, could you report it to the official?

**Comment by DeepspaceFreelancer** [comment]
For me these were the lines:

```
find_path(pdcurses_INCLUDES curses.h)
find_library(pdcurses pdcurses REQUIRED)
include_directories(${pdcurses_INCLUDES})
```

and for linking:
```
target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE pdcurses)
```

Used this for include in the main.cpp:

```
#include <pdcurses.h>
```
