### ISSUE TITLE
Install a package with specific version?

### ISSUE THREAD

**Issue by wanlizhu** [microsoft/vcpkg#11023]
****

**Is your feature request related to a problem? Please describe.**
* This request isn't related to any existing problem.

**Proposed solution**
* For example, extend the current triplet to contain version information:  `boost@1.72.0:x64-windows`. 

**Describe alternatives you've considered**
ditto

**Additional context**
* This feature is very essential when I'm considering using `vcpkg` as the default package management system of my company's future projects.  If we can't control which version's package to install, we can't control the stability of our projects. 

* The latest version of a third-party package is NOT always a suitable version for every project.  I believe the functionality to control the installed package's version is very important and necessary.

**Comment by Neumann-A** [comment]
The trick ist to combine the command:
`vcpkg x-history <portname>`
with:
https://github.com/microsoft/vcpkg/blob/master/docs/specifications/ports-overlay.md
to fix a port to a certain version or simply wanting to have a customized build. 
Maybe also relevant:
`https://github.com/microsoft/vcpkg/blob/master/docs/examples/overlay-triplets-linux-dynamic.md`

**Comment by AugP** [comment]
Hello and thank you for the suggestion. We will be doing a more detailed announcement by the end of the week on our roadmap, but one of the top things on it is versioning support. We have received a lot of feedback about this in the past and we definitely want to address it.

**Comment by vicroms** [comment]
We recently published a [product roadmap](https://github.com/microsoft/vcpkg/wiki/Roadmap) in our wiki. You can read the original announcement in our [blog post](https://devblogs.microsoft.com/cppblog/vcpkg-2020-04-update-and-product-roadmap/).

**Comment by PhoebeHui** [comment]
Installing an old or specific version in vcpkg is supported now, see [versioning](https://devblogs.microsoft.com/cppblog/take-control-of-your-vcpkg-dependencies-with-versioning-support/) for details, please file a new issue if you encounter a problem.
