### ISSUE TITLE
[Qt] Maybe switch to github downloads

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#11038]
we should probably switch the Qt installation to github downloads instead of binary downloads. This would also make `vcpkg install <someqtport> --head` possible. 

The only problem could be that people would start mixing `vcpkg install <someqtport>` with `vcpkg install <someotherqtport> --head` which will work since `--head` deactivates the hash check

related #2203 (but not about github)

**Comment by JackBoosY** [comment]
Yeah, I noticed that. Maybe we need to switch qt repo to github.

**Comment by heydojo** [comment]
I tried this and was doing something like:

```cmake
set(FULL_VERSION 5.12.5)
vcpkg_find_acquire_program(PERL)
get_filename_component((PERL_DIR "${(PERL}" DIRECTORY )
vcpkg_add_to_path(PREPEND "${(PERL_DIR}")

vcpkg_from_github(
        ## (https://github.com/qt/qtwebengine)
        OUT_SOURCE_PATH TARGET_SOURCE_PATH
        REPO qt/qtwebengine
        REF dbc0d09be2bbc3dce01ace956f534c4012402fba
        HEAD_REF 5.12.5
        SHA512 38146b74bc13c2abf21591c671925786f1602530af691776c0693288c1b71805b841604a6a0abc96404cdc4ce6c5dd94bb694170eee56955c39a44673e959a13
 )

vcpkg_execute_required_process(
		COMMAND perl ${VCPKG_ROOT_DIR}/packages/qt5-base_x64-windows/tools/qt5/bin/syncqt.pl -version ${FULL_VERSION}
		WORKING_DIRECTORY ${TARGET_SOURCE_PATH}
)
```
**syncqt.pl** needs to be called after pulling each repo. I don't think the process takes very long iirc.
Hope this helps.

**Comment by Neumann-A** [comment]
qt6 is using the official git of qt. (and i don't care about qt5)
