### ISSUE TITLE
[New Port Request] boost-nowide

### ISSUE THREAD

**Issue by tats-u** [microsoft/vcpkg#11035]
Library name: boost-nowide

Library description: Boost nowide nowide module (it makes it easier to handle Unicode (UTF-8) I/O in Windows without `wchar_t`)

Source repository URL: https://github.com/boostorg/nowide

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
Windows API prefers `wchar_t` as characters type for I/O rather than `char`, but this is a Galapagosized behavier and lacks compatibility with and code portability to other OSes (macOS, Linux, and other POSIX OSes).
Other major OSes treat `char` as UTF-8 but Windows usually do not.  But you can force Windows to do so with the help of this library.

**Comment by tats-u** [comment]
There is a package `boost-vcpkg-helpers`.  Does it requires a special way to add boost packages?

**Comment by BaileyLove** [comment]
Wanted to share, that according to [this reddit post](https://www.reddit.com/r/cpp/comments/frnw7y/boostnowide_released/) nowide is to be officially included into the upcoming 1.73 boost release.

**Comment by tats-u** [comment]
Oh, did it used to be an unofficial module?  It is no wonder that it is unavailable in Vcpkg.

**Comment by BaileyLove** [comment]
Yes, it was an unofficial 3rd party module. Before boost 1.73, you had to do stuff yourself to use it. You could either use some of its functionality using only its headers, or for access to things like nowide iostream (iirc) you had to copy-paste it into boost directory and compile it together with boost. Today it looks like there is a standalone version of nowide available.

IDK is you can or can not do anything about it. Probably, boost vcpkg port has a maintainer here. As soon as they update it, we should have access to the new built-in boost::nowide.

**Comment by tats-u** [comment]
I got it.  I will wait for actions of port maintainers.
