### ISSUE TITLE
consuming SFML

### ISSUE THREAD

**Issue by MathiasMagnus** [Microsoft/vcpkg#1103]
Hi!

How does one consume SFML properly with CMake? I was trying to point CMake to the vcpkg toolchains file and hoped that in turn `find_package(SFML)` would work, but it does not. Is SFML not CMake-aware enough to omit manual file detection? I am aware that SFML ships with a FindModule.cmake script instead of a PackageConfig.cmake file (honestly, the last time I used SFML 5 years ago it was OK, but 5 years later, it's kinda lame they still don't have proper PackageConfig scripts).

How do I instruct CMake to find the static libraries and matching headers built by vcpkg without having to alter the CMake scripts? (Meaning the scripts should be cross-plat and only the invocation should reflect vcpkg usage.) Using the toolchain file is not enough?

**Comment by codicodi** [comment]
According to [SFML wiki](https://github.com/SFML/SFML/wiki/Tutorial%3A-Build-your-SFML-project-with-CMake) you are supposed to take the FindSFML.cmake module and ship it with your application. You can find it in `<vcpkg-root>/buildtrees/sfml/src/SFML-2.4.2/cmake/Modules/`
