### ISSUE TITLE
How do I ...

### ISSUE THREAD

**Issue by aphage** [microsoft/vcpkg#11032]
/Qspectre
Where can i close this, my first installation failed

**Comment by linquize** [comment]
What package did you install?

**Comment by NancyLi1013** [comment]
@aphage 
Could you please describe your question more clearly? 
 Please provide the steps or post the error info.

**Comment by aphage** [comment]
PS E:\install\vcpkg> ./bootstrap-vcpkg.bat

Building vcpkg.exe ...

C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(4
36,5): error MSB8040: 此项目需要缓解了 Spectre 漏洞的库。从 Visual Studio 安装程序(单个组件选项卡)为正在使用的任何工具集和体系结构安装它们。了解详细信息: https://aka.ms/Of
hn4c [E:\install\vcpkg\toolsrc\vcpkglib\vcpkglib.vcxproj]
E:\install\vcpkg\scripts\bootstrap.ps1 : Building vcpkg.exe failed. Please ensure you have installed Visual Studio with
 the Desktop C++ workload and the Windows SDK for Desktop C++.
所在位置 行:1 字符: 4
+ & {& 'E:\install\vcpkg\scripts\bootstrap.ps1' }
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,bootstrap.ps1

**Comment by aphage** [comment]
error MSB8040: Spectre-mitigated libraries are required for this project

**Comment by aphage** [comment]
Okay, I manually modified the "toolsrc / vcpkg.sln" project properties and solved

**Comment by aphage** [comment]
Thanks guys
