### ISSUE TITLE
[vcpkg/CI] Report resulting CASCADE if port is added as a skip/fail in the ci baseline

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#11046]
Reason: Reduced CI coverage due to adding ports to the skip/fail list without realising it. Recent example: `qt5-activeqt` deactivating `qt5-tools` deactivating even more dependent ports.

**Comment by cbezault** [comment]
Related to my comment here: https://github.com/microsoft/vcpkg/pull/10828#discussion_r408449555

**Comment by strega-nil** [comment]
I think y'all have a good point here; we should look into it as soon as we have our CI checked in

**Comment by BillyONeal** [comment]
@strega-nil The CI is checked in :).

**Comment by strega-nil** [comment]
@BillyONeal oh, right! we just run the scripts from this repo now, don't we?

**Comment by BillyONeal** [comment]
For Windows yes. I think that's sufficient to make that change since the pending *nix changes reuse the same scripts from here.

**Comment by Neumann-A** [comment]
ci.baseline now has =pass and CI shows reasons/missing ports for cascades.
