### ISSUE TITLE
[sdl2:x64-windows] build failure

### ISSUE THREAD

**Issue by ToastyMod** [microsoft/vcpkg#11042]
**Host Environment**
- OS: Windows 10
- Compiler: MSVC i think??

**To Reproduce**
`./vcpkg.exe install sdl2:x64-windows`

**Failure logs** 
`PS E:\devel\vcpkg> .\vcpkg.exe install sdl2-ttf:x64-windows sdl2:x64-windows
Computing installation plan...
The following packages will be built and installed:
  * bzip2[core]:x64-windows
  * freetype[bzip2,core,png]:x64-windows
  * libpng[core]:x64-windows
    sdl2[core]:x64-windows
    sdl2-ttf[core]:x64-windows
  * zlib[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/6: sdl2:x64-windows
Building package sdl2[core]:x64-windows...
-- Using cached E:/devel/vcpkg/downloads/SDL2-2.0.12.tar.gz
-- Using source at E:/devel/vcpkg/buildtrees/sdl2/src/SDL2-2-1f74301957
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: E:/devel/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v
    Working Directory: E:/devel/vcpkg/buildtrees/sdl2/x64-windows-dbg
    See logs for more information:
      E:\devel\vcpkg\buildtrees\sdl2\install-x64-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/sdl2/portfile.cmake:37 (vcpkg_install_cmake)
  scripts/ports.cmake:90 (include)

Error: Building package sdl2:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: sdl2:x64-windows
  Vcpkg version: 2020.02.04-nohash

Additionally, attach any relevant sections from the log files above.`

**Additional context**
i was following the steps from [this sdl2 for rust setup](https://github.com/Rust-SDL2/rust-sdl2#windows-msvc-with-vcpkg)
i am running vcpkg directly from where i cloned it.

**Comment by timautry** [comment]
Please upload the `E:\devel\vcpkg\buildtrees\sdl2\install-x64-windows-dbg-err.log`, to review for possible errors.

**Comment by NancyLi1013** [comment]
Hi @ToastyMod 
Thanks for posting this issue.
I cannot reproduce this on my local.
Could you please provide the failure log as @timautry said above?

**Comment by ToastyMod** [comment]
`ninja: error: 'E:/devel/vcpkg-2020.04/buildtrees/sdl2/src/SDL2-2-1f74301957/src/main/windows/SDL_windows_main.c', needed by 'CMakeFiles/SDL2main.dir/src/main/windows/SDL_windows_main.c.obj', missing and no known rule to make it
`

**Comment by NancyLi1013** [comment]
Could you please try to comment ` PREFER_NINJA` and then build this again?
It seems that there is something wrong with your Ninja.

**Comment by ToastyMod** [comment]
where is that? ive never used consciously used ninja before lol

**Comment by NancyLi1013** [comment]
Comment out `PREFER_NINJA ` here https://github.com/microsoft/vcpkg/blob/master/ports/sdl2/portfile.cmake#L29, then rebuild `sdl2`.

**Comment by NancyLi1013** [comment]
@ToastyMod 
Does this work for you?

**Comment by NancyLi1013** [comment]
I'm closing this issue for now since inactive in a long time. Please feel free to reopen this if it is still a problem for you.
