### ISSUE TITLE
[Vcpkg] The property AdditionalIncludeDirectories in file vcxproj doesn't work after PR #10952

### ISSUE THREAD

**Issue by LilyWangL** [microsoft/vcpkg#11050]
**Describe the bug**
Due to add option `/p:UseEnv=True` in **vcpkg_build_msbuild.cmake** and **vcpkg_install_msbuild.cmake**. The property `AdditionalIncludeDirectories` in file vcxproj doesn't work. 
The related PR: #10952. @Voskrese Could you take a look?

**Environment**
- OS: Windows10
- Compiler: revision Visual Studio 2019

**To Reproduce**
1. ./vcpkg install pmdk:x64-windows ./vcpkg install pbc:x64-windows
2. See error
pbc: vcpkg\buildtrees\pbc\x64-windows-rel\src\e816cf9d08-73bced3986\arith\dlog.c : fatal error C1083: Cannot open include file: 'pbc_vc_compat.win32.h': No such file or directory
pmdk: vcpkg\buildtrees\pmdk\src\2149e37eaa-96cbbce504\src\common\alloc.c : fatal error C1083: Cannot open include file: 'platform.h': No such file or directory

**Expected behavior**

**Failure logs** 
-(please attached failure logs)

**Additional context**

**Comment by Neumann-A** [comment]
related https://github.com/conan-io/conan/issues/2829

**Comment by Neumann-A** [comment]
I would say: Add an option `DISABLE_ENVIRONMENT` to **vcpkg_build_msbuild.cmake / vcpkg_install_msbuild.cmake.** which disables `/p:UseEnv=True`. Personally I think keeping `/p:UseEnv=True` as the default is desirable.
