### ISSUE TITLE
[hdf5] build failure

### ISSUE THREAD

**Issue by kerwinxu** [microsoft/vcpkg#11053]
**Host Environment**
- OS: [e.g. Windows/Linux etc...] win10 
- Compiler: revision 

**To Reproduce**
 vcpkg install hdf5:x64-windows
Computing installation plan...
The following packages will be built and installed:
    hdf5[core,szip,zlib]:x64-windows
Starting package 1/1: hdf5:x64-windows
Building package hdf5[core,szip,zlib]:x64-windows...
-- Using cached E:/Program/vc/vcpkg/downloads/CMake-hdf5-1.10.5.tar.gz
-- Using source at E:/Program/vc/vcpkg/buildtrees/hdf5/src/hdf5-69d2d96f64
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: "D:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v
    Working Directory: E:/Program/vc/vcpkg/buildtrees/hdf5/x64-windows-dbg
    See logs for more information:
      E:\Program\vc\vcpkg\buildtrees\hdf5\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/hdf5/portfile.cmake:62 (vcpkg_install_cmake)
  scripts/ports.cmake:90 (include)

Error: Building package hdf5:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: hdf5:x64-windows
  Vcpkg version: 2020.02.04-nohash

Additionally, attach any relevant sections from the log files above.

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

 E:\Program\vc\vcpkg\buildtrees\hdf5\install-x64-windows-dbg-out.log
src\CMakeFiles\hdf5-shared.dir\H5Topaque.c.obj 

src\CMakeFiles\hdf5-shared.dir\H5Torder.c.obj 

src\CMakeFiles\hdf5-shared.dir\H5Tpad.c.obj 

src\CMakeFiles\hdf5-shared.dir\H5Tprecis.c.obj 

src\CMakeFiles\hdf5-shared.dir\H5Tstrpad.c.obj 

src\CMakeFiles\hdf5-shared.dir\H5Tvisit.c.obj 

src\CMakeFiles\hdf5-shared.dir\H5Tvlen.c.obj 

src\CMakeFiles\hdf5-shared.dir\H5TS.c.obj 

src\CMakeFiles\hdf5-shared.dir\H5VM.c.obj 

src\CMakeFiles\hdf5-shared.dir\H5WB.c.obj 

src\CMakeFiles\hdf5-shared.dir\H5Z.c.obj 

src\CMakeFiles\hdf5-shared.dir\H5Zdeflate.c.obj 

src\CMakeFiles\hdf5-shared.dir\H5Zfletcher32.c.obj 

src\CMakeFiles\hdf5-shared.dir\H5Znbit.c.obj 

src\CMakeFiles\hdf5-shared.dir\H5Zscaleoffset.c.obj 

src\CMakeFiles\hdf5-shared.dir\H5Zshuffle.c.obj 

src\CMakeFiles\hdf5-shared.dir\H5Zszip.c.obj 

src\CMakeFiles\hdf5-shared.dir\H5Ztrans.c.obj 

src\CMakeFiles\hdf5-shared.dir\__\shared\H5Tinit.c.obj 

src\CMakeFiles\hdf5-shared.dir\__\shared\H5lib_settings.c.obj E:\Program\vc\vcpkg\installed\x64-windows\debug\lib\zlibd.lib E:\Program\vc\vcpkg\installed\x64-windows\debug\lib\szip_D.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib 

LINK : fatal error LNK1168: cannot open bin\hdf5_D.dll for writing

ninja: build stopped: subcommand failed.

but i found hdf5_D.dll in  E:\Program\vc\vcpkg\buildtrees\hdf5\x64-windows-dbg\bin .

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by Neumann-A** [comment]
Cannot reproduce. Did you ran out of disk space or lack permissions in this folder? This the most common issue for this kind of error.
