### ISSUE TITLE
qt5[latest] QtQuick2 plugin Qt5QmlWorkerScript dependency not copied to output directory on build

### ISSUE THREAD

**Issue by andy-fillebrown** [microsoft/vcpkg#11056]
When building Qt projects dependent on the QtQuick2 plugin, the shared Qt5QmlWorkerScript library is not copied to the project output directory. This causes loading the QtQuick2 plugin to fail at runtime.

**Environment**
- OS: Windows
- Compiler: Visual Studio / MSVC

**To Reproduce**
1. ./vcpkg install qt5[latest]
2. Build any project that uses QtQuick2.
3. Run the project.
4. Runtime error: plugin cannot be loaded for module "QtQuick": Cannot load library [...]\bin\qml\QtQuick.2\qtquick2plugind.dll: The specified module could not be found.

Copying Qt5QmlWorkerScriptd.dll to [...]\bin fixes the problem.

**Comment by JackBoosY** [comment]
@Neumann-A  Could you please have a look?

Thanks.

**Comment by Neumann-A** [comment]
Seems like there are a few new Qml dlls with 5.14 which need to be included into the check of qtdeploy.ps

**Comment by Reveares** [comment]
This is still an issue with qt 5.15

**Comment by seanlis** [comment]
As for my simple app, 5 dlls were not copied
- Qt5QuickControls2
- Qt5QuickTemplates2
- Qt5Quick
- Qt5QmlModels
- Qt5QmlWorkerScript
