### ISSUE TITLE
Eliminate bad error reporting "Value was null"

### ISSUE THREAD

**Issue by atsushieno** [microsoft/vcpkg#11052]
****

**Is your feature request related to a problem? Please describe.**

vcpkg became valuable to me now that it started to support Android prefab (https://github.com/microsoft/vcpkg/pull/10271), so I started evaluating current ports. So far I cannot "export" AAR for **unknown** reason. And this seems to happen to **everywhere** in vcpkg tool itself has some bogus code that only avoids runtime crash.

It is not appropriate. We need at least information on why and/or where it crashed.

**Proposed solution**

- Give error details on each caller to `check_exit()`.
- Give error codes (either in MSBuild style or not).

**Additional context**

Here is an **example** reproducible steps I had (Ubuntu 19.10, Android SDK at standard location `~/Android/Sdk` with NDK):

- `./bootstrap-vcpkg.sh -disableMetrics`
- `export ANDROID_NDK_HOME=~/Android/Sdk/ndk/21.0.6113669`
- create `triplets/arm64-android.cmake` (below)
- `./vcpkg install jsoncpp:arm64-android`
- `./vcpkg export --triplet arm64-android jsoncpp  --prefab --prefab-maven` (as [docs/specifications/prefab.md](https://github.com/microsoft/vcpkg/blob/master/docs/specifications/prefab.md) describes.)

File content for `triplets/arm64-android.cmake`:

```
set(VCPKG_TARGET_ARCHITECTURE arm64-v8a)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_CMAKE_SYSTEM_NAME Android)
```

The output from the last command:

```
The following packages are already built and will be exported:
    jsoncpp:arm64-android
Value was null
```

revision: 28ab0b1

**Comment by horenmar** [comment]
This is caused by _some_ call to vcpkg's `Optional::value_or_exit`, and also surfaces when unit tests are run on Linux.

**Comment by atkawa7** [comment]
@atsushieno Do you have four triplets defined ?. #11055
https://github.com/microsoft/vcpkg/blob/master/docs/specifications/prefab.md
>>> The following architectures arm64-v8a, armeabi-v7a, x86_64 x86 must be present
>>> Please note the four architectures are required. If any is missing the export will fail 
>>> To export the following environment ANDROID_NDK_HOME variable is required for exporting
>>>The following table outlines the mapping from vcpkg architectures to android architectures

>>> |vcpkg architecture | android architecture |
|-------------------|----------------------|
|arm64              | arm64-v8a            |
|arm                | armeabi-v7a          |
|x64                | x86_64               |
|x86                | x86                  |



```zsh
triplets
├── arm-uwp.cmake
├── arm64-windows.cmake
├── community
│   ├── arm-android.cmake
│   ├── arm-mingw.cmake
│   ├── arm-windows.cmake
│   ├── arm64-android.cmake
│   ├── arm64-mingw.cmake
│   ├── arm64-uwp.cmake
│   ├── x64-android.cmake
│   ├── x64-mingw.cmake
│   ├── x64-osx-dynamic.cmake
│   ├── x64-windows-static-md.cmake
│   ├── x86-android.cmake
│   ├── x86-mingw.cmake
│   ├── x86-uwp.cmake
│   ├── x86-windows-static-md.cmake
│   └── x86-windows-static.cmake
├── x64-linux.cmake
├── x64-osx.cmake
├── x64-uwp.cmake
├── x64-windows-static.cmake
├── x64-windows.cmake
└── x86-windows.cmake
```


```zsh
cat triplets/community/arm-android.cmake
set(VCPKG_TARGET_ARCHITECTURE arm)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_CMAKE_SYSTEM_NAME Android)

cat triplets/community/arm64-android.cmake
set(VCPKG_TARGET_ARCHITECTURE arm64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_CMAKE_SYSTEM_NAME Android)
 
cat triplets/community/x86-android.cmake
set(VCPKG_TARGET_ARCHITECTURE x86)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_CMAKE_SYSTEM_NAME Android)

cat triplets/community/x64-android.cmake
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_CMAKE_SYSTEM_NAME Android)
```

**Comment by atkawa7** [comment]
@atsushieno @NancyLi1013 @strega-nil The issue could be related to a wrong vpkg
`VCPKG_TARGET_ARCHITECTURE arm64-v8a` when calling ```  Optional<CPUArchitecture> to_cpu_architecture(StringView arch);``` from prefab. So it could be this line 
https://github.com/microsoft/vcpkg/blob/master/toolsrc/src/vcpkg/export.prefab.cpp#L285
```cpp
auto cpu_architecture = System::to_cpu_architecture(triplet_build_info.target_architecture).value_or_exit(VCPKG_LINE_INFO);```

**Comment by atsushieno** [comment]
When I first encountered the issue I had four configuration files saved there. When I described my repro steps I thought I need only one (arm54) so I only mentioned it.

I just made sure the issue still persists. As https://github.com/microsoft/vcpkg/issues/11052#issuecomment-621057129 states maybe current implementation has the issue on Linux.

**Comment by atkawa7** [comment]
@atsushieno It seems `set(VCPKG_TARGET_ARCHITECTURE arm64-v8a)` is incorrect. See above. Please change this and try to run again

**Comment by atsushieno** [comment]
Thanks, but it does not seem to be the fix for "export" target. 

```
/sources/vcpkg$ ./vcpkg export --triplet arm64-android jsoncpp --prefab --prefab-maven
The following packages are already built and will be exported:
    jsoncpp:arm64-android

Exporting package jsoncpp...
Error: Packages not installed jsoncpp:x64-android /sources/vcpkg/installed/vcpkg/info/jsoncpp_1.9.2_x64-android.list
```

I have some hard time on reproducing the *exact* same output as the original report as `git clean -xdf` and removing `~/.vcpkg` does not seem to be enough.  This is not "Value was null" anymore and I don't know how to reliably reproduce the problem that **this issue** should fix.

On the other hand `vcpkg export` not being able to build package is a present issue.

**Comment by atkawa7** [comment]
It means you do not have  jsoncpp:x64-android installed. You need to install all triplets like this then export
```
./vcpkg install jsoncpp:arm-android  jsoncpp:arm64-android  jsoncpp:x64-android  jsoncpp:x86-android 
```

**Comment by atkawa7** [comment]
@atsushieno See above 

then 

```
./vcpkg export --triplet arm64-android jsoncpp --prefab --prefab-maven
```

**Comment by atkawa7** [comment]
```
./vcpkg install jsoncpp:arm-android  jsoncpp:arm64-android  jsoncpp:x64-android  jsoncpp:x86-android
Computing installation plan...
The following packages are already installed:
    jsoncpp[core]:x86-android
    jsoncpp[core]:arm-android
    jsoncpp[core]:arm64-android
    jsoncpp[core]:x64-android
Package jsoncpp:x86-android is already installed
Package jsoncpp:arm-android is already installed
Package jsoncpp:arm64-android is already installed
Package jsoncpp:x64-android is already installed

Total elapsed time: 22 us

The package jsoncpp:x86-android provides CMake targets:

    find_package(jsoncpp CONFIG REQUIRED)
    target_link_libraries(main PRIVATE jsoncpp_lib)

The package jsoncpp:arm-android provides CMake targets:

    find_package(jsoncpp CONFIG REQUIRED)
    target_link_libraries(main PRIVATE jsoncpp_lib)

The package jsoncpp:arm64-android provides CMake targets:

    find_package(jsoncpp CONFIG REQUIRED)
    target_link_libraries(main PRIVATE jsoncpp_lib)

The package jsoncpp:x64-android provides CMake targets:

    find_package(jsoncpp CONFIG REQUIRED)
    target_link_libraries(main PRIVATE jsoncpp_lib)
```

**Comment by atkawa7** [comment]
```
./vcpkg export --triplet arm64-android jsoncpp --prefab --prefab-maven
The following packages are already built and will be exported:
    jsoncpp:arm64-android
Exporting package jsoncpp...
Successfuly exported jsoncpp. Checkout /Users/allen/Source/vcpkg/prefab
```

**Comment by atsushieno** [comment]
Ah, I missed that `x64-` part. Now they all build. Perfect, thanks. Now the prefab packaging part is resolved.

**Comment by atsushieno** [comment]
(Out of curious, why aren't those Android triplets part of the sources? I don't see any reason to not include them.)

**Comment by atkawa7** [comment]
There were removed to allow user to define their custom android triplet. Maybe @ras0219-msft or @NancyLi1013 @strega-nil  can enable them back

**Comment by pthom** [comment]
@atkawa7  : the presence of pre-configured triplets and a link to the prefab.md in the user would have helped me a lot. 

I proposed a [PR that tries to address this](https://github.com/microsoft/vcpkg/pull/11264)
  
Could you comment on it?
