### ISSUE TITLE
vcpkg_check_features seems not to work

### ISSUE THREAD

**Issue by illera88** [microsoft/vcpkg#11061]
Hi,

I'm trying to use `vcpkg_check_features` to get optional features and it's not working. I created a very simple port with CONTROL:
```
Source: mytest
Version: 0.1.0

Feature: test
Description: Build with test
```

and port.cmake:
```
vcpkg_check_features(OUT_FEATURE_OPTIONS FEATURE_OPTIONS
    test BUILD_TESTS
)

message(STATUS "BUILD_TEST is set to " ${BUILD_TESTS})
```

I'm installing it with `vcpkg.exe install mytest` and I get nothing when the message is printed:

`-- BUILD_TEST is set to`

Why? Is `vcpkg_check_features` not supposed to populate `BUILD_TESTS` in this case with `OFF` and when used `vcpkg.exe install mytest[test]` with `ON`?

What am I doing wrong?

**Comment by Neumann-A** [comment]
```
vcpkg_check_features(OUT_FEATURE_OPTIONS FEATURE_OPTIONS
    test BUILD_TESTS
)
```
does not set `BUILD_TESTS` in the portfile. It will only add `-DBUILD_TESTS=ON`(or OFF) too `FEATURE_OPTIONS` for the cmake configure call

**Comment by illera88** [comment]
I see, how can I get the features a user selected in the portfile so I can react depending on that?

Thanks

**Comment by illera88** [comment]
I found how to do it. In the case that someone is interested:

```function(check_feature name var)
    set(${var} OFF PARENT_SCOPE)
    if (${name} IN_LIST FEATURES)
        set(${var} ON PARENT_SCOPE)
    endif ()
endfunction ()

check_feature("test"         BUILD_TESTS)
```
