### ISSUE TITLE
[python3] Build failure on Ubuntu 16.04.6 LTS (WSL)

### ISSUE THREAD

**Issue by yurybura** [microsoft/vcpkg#11069]
**Host Environment**
- OS: Ubuntu 16.04.6 LTS (WSL)
- Compiler: g++ (Ubuntu 7.5.0-3ubuntu1~16.04) 7.5.0

**To Reproduce**
`./vcpkg install python3`

**Failure logs** 
```
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
Computing installation plan...
The following packages will be built and installed:
    python3[core]:x64-linux
Starting package 1/1: python3:x64-linux
Building package python3[core]:x64-linux...
-- Using cached /mnt/d/libs/yurybura/vcpkg-boost/downloads/python-cpython-v3.7.3.tar.gz
-- Extracting source /mnt/d/libs/yurybura/vcpkg-boost/downloads/python-cpython-v3.7.3.tar.gz
-- Using source at /mnt/d/libs/yurybura/vcpkg-boost/buildtrees/python3/src/v3.7.3-1161ad7a91
-- Configuring x64-linux-rel
-- Building x64-linux-rel
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: make install -j 9
    Working Directory: /mnt/d/libs/yurybura/vcpkg-boost/buildtrees/python3/src/v3.7.3-1161ad7a91-x64-linux-release
    See logs for more information:
      /mnt/d/libs/yurybura/vcpkg-boost/buildtrees/python3/make-build-x64-linux-release-out.log
      /mnt/d/libs/yurybura/vcpkg-boost/buildtrees/python3/make-build-x64-linux-release-err.log

Call Stack (most recent call first):
  ports/python3/portfile.cmake:141 (vcpkg_execute_build_process)
  scripts/ports.cmake:90 (include)


Error: Building package python3:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: python3:x64-linux
  Vcpkg version: 2020.02.04-unknownhash
```
[make-build-x64-linux-release-err.log](https://github.com/microsoft/vcpkg/files/4544596/make-build-x64-linux-release-err.log)
[make-build-x64-linux-release-out.log](https://github.com/microsoft/vcpkg/files/4544598/make-build-x64-linux-release-out.log)

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Could you remove `libffi:x64-linux` and rebuild `python3:x64-linux`? I can't reproduce this issue locally. I installed `python3:x64-linux` successfully with the latest VCPKG source.

**Comment by yurybura** [comment]
***@***:/mnt/d/libs/yurybura/vcpkg-boost$ ./vcpkg install python3:x64-linux
Computing installation plan...
The following packages will be built and installed:
  * libffi[core]:x64-linux
    python3[core]:x64-linux
Additional packages (*) will be modified to complete this operation.
Starting package 1/2: libffi:x64-linux
Building package libffi[core]:x64-linux...
-- Using cached /mnt/d/libs/yurybura/vcpkg-boost/downloads/libffi-libffi-v3.3.tar.gz
-- Using source at /mnt/d/libs/yurybura/vcpkg-boost/buildtrees/libffi/src/v3.3-2d8a36299e
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Installing: /mnt/d/libs/yurybura/vcpkg-boost/packages/libffi_x64-linux/share/libffi/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package libffi[core]:x64-linux... done
Installing package libffi[core]:x64-linux...
Installing package libffi[core]:x64-linux... done
Elapsed time for package libffi:x64-linux: 3.603 s
Starting package 2/2: python3:x64-linux
Building package python3[core]:x64-linux...
-- Using cached /mnt/d/libs/yurybura/vcpkg-boost/downloads/python-cpython-v3.7.3.tar.gz
-- Extracting source /mnt/d/libs/yurybura/vcpkg-boost/downloads/python-cpython-v3.7.3.tar.gz
-- Using source at /mnt/d/libs/yurybura/vcpkg-boost/buildtrees/python3/src/v3.7.3-1161ad7a91
-- Configuring x64-linux-rel
-- Building x64-linux-rel
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: make install -j 9
    Working Directory: /mnt/d/libs/yurybura/vcpkg-boost/buildtrees/python3/src/v3.7.3-1161ad7a91-x64-linux-release
    See logs for more information:
      /mnt/d/libs/yurybura/vcpkg-boost/buildtrees/python3/make-build-x64-linux-release-out.log
      /mnt/d/libs/yurybura/vcpkg-boost/buildtrees/python3/make-build-x64-linux-release-err.log

Call Stack (most recent call first):
  ports/python3/portfile.cmake:141 (vcpkg_execute_build_process)
  scripts/ports.cmake:90 (include)


Error: Building package python3:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: python3:x64-linux
  Vcpkg version: 2020.02.04-unknownhash

Additionally, attach any relevant sections from the log files above.

**Comment by OmenWild** [comment]
I have an Ubuntu 16.04.6 LTS system with this exact same problem. I am behind 80 or so packages, but it is otherwise up to date. This is a research system, so upgrading and rebooting needs to be scheduled, thus I cannot simply upgrade now and retry. It fails with the same error with the following sequence:

```
git clone https://github.com/Microsoft/vcpkg.git
cd vcpkg
./bootstrap-vcpkg.sh -disableMetrics |& tee bootstrap-vcpkg.out
./vcpkg install python3 |& tee python3.out
```

I have included the output of the vcpkg log files, as well as the output from the two tee commands above.

[make-build-x64-linux-release-err.log](https://github.com/microsoft/vcpkg/files/4567040/make-build-x64-linux-release-err.log)
[make-build-x64-linux-release-out.log](https://github.com/microsoft/vcpkg/files/4567041/make-build-x64-linux-release-out.log)
[python3.log](https://github.com/microsoft/vcpkg/files/4567042/python3.log)
[bootstrap-vcpkg.log](https://github.com/microsoft/vcpkg/files/4567043/bootstrap-vcpkg.log)

**Comment by Barath-Kannan** [comment]
Ran into the same problem using;
- Ubuntu 18.04
- gcc 10.1.0 built from source

logs showed an error because libffi was not build with PIC

I removed libffi, added the following to libffis CMakeLists.txt;
`set_property(TARGET lib1 PROPERTY POSITION_INDEPENDENT_CODE ON)`
and then installed it again and everything worked correctly after that

Does someone want to put up a PR with that simple fix? I don't have time

**Comment by yurybura** [comment]
@Barath-Kannan 
ldd (Ubuntu GLIBC 2.23-0ubuntu11) 2.23

**Comment by LilyWangL** [comment]
@yurybura Sorry I am late. `python3` has been updated to 3.8, I can installed it successfully on Linux Ubuntu 16.04. Could you please update VCPKG and rebuild `python3`?

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
