### ISSUE TITLE
[itk:x64-windows] build failure

### ISSUE THREAD

**Issue by bcolombet** [microsoft/vcpkg#11067]
**Host Environment**
- OS: Window 10 Pro
- Compiler: MSVC 2017

**To Reproduce**
`./vcpkg install itk --triplet x64-windows`

**Failure logs** 
  Command failed: D:/Dev/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v
    Working Directory: D:/Dev/vcpkg/buildtrees/itk/x64-windows-dbg

**Additional context**
I've updated and rebuilt vcpkg using git pull and bootstrap script. Same results.
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/4544187/install-x64-windows-dbg-out.log)

**Comment by JackBoosY** [comment]
Duplicated with #9891.
