### ISSUE TITLE
Cmake can't locate Python properly when using vcpkg toolchain file

### ISSUE THREAD

**Issue by TBamberger** [microsoft/vcpkg#11060]
This is reproducible with the following minimal `CMakeLists.txt` file:
```
cmake_minimum_required(VERSION 3.17)
project(foo)
find_package(Python REQUIRED  COMPONENTS Development)
```

When I pass my vcpkg toolchain file to cmake it finds the python `_Python_INCLUDE_DIR` in my systems python installation but the `_Python_RUNTIME_LIBRARY_RELEASE` in `[...]/vcpkg/installed/x64-windows/lib/python37.lib` and the `_Python_RUNTIME_LIBRARY_RELEASE` isn't found at all since none is present in the vcpkg python installation.

Setting the `Python_ROOT_DIR` variable to my systems python installation or using a python virtual environment (in this case adding the Interpreter component as recommended in the [cmake manual](https://cmake.org/cmake/help/v3.17/module/FindPython.html)) instead both don't work. In both cases the lib files in the vcpkg installation are used.

However, if I don't use the vcpkg toolchain file cmake is able to detect the include dir as well as the release and debug libraries in my systems python installation as expected.

I am testing this on Windows 10 with python 3.7, cmake 3.17.1 (although previous versions didn't work either).

**Comment by LilyWangL** [comment]
Thanks for posting this issue. I use `find_package(Python REQUIRED  COMPONENTS Development)` in cmake project and find `python37.lib` successfully.
`[CMake] -- Found Python: E:/0423/vcpkg/installed/x86-windows/lib/python37.lib (found version "3.7") found components: Development`

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.

**Comment by wrosecrans** [comment]
Did this issue ever get looked into?  I am confused why the ticket was closed.  It's listed as "requires repro," but the repro attempt says that it only found a python inside the vcpkg path E:/0423/vcpkg/installed/... which is exactly the issue that was reported.  I think it was actually reproduced, just misunderstood what was being reproduced.  Using the vcpkg toolchain file breaks finding any Python install outside of vcpkg.

Deleting python stuff from my vcpkg install dir and setting 
set (Python3_ROOT_DIR "C:/Users/wrose/AppData/Local/Programs/Python/Python310" )
set (Python3_FIND_STRATEGY LOCATION)
set (Python3_FIND_REGISTRY NEVER)
set (Python3_FIND_ABI "ANY" "ANY" "ANY")
find_package (Python3 COMPONENTS Interpreter Development REQUIRED)

to try and force it to look in exactly that dir, and accept any ABI variation, fails with 

Could NOT find Python3 (missing: Development Development.Module
  Development.Embed) (found version "3.10.1")

in C:/Users/wrose/Documents/development/vcpkg/scripts/buildsystems/vcpkg.cmake:788 (_find_package)


I am confused why it says it found 3.10.1, but didn't find the development stuff.  It's there in the path I told it to search.

**Comment by josenetodgg** [comment]
I'm having the same issue when trying to build [OpenImageIO](https://github.com/AcademySoftwareFoundation/OpenImageIO) with dependencies installed via vcpkg. It prevents cmake to find python even specifying libraries, root and executable paths.

**Comment by dg0yt** [comment]
Given all the changes to vcpkg, cmake, python, it might be better to open a new issue.
