### ISSUE TITLE
Could not find a configuration file for package, even through the package installed successfully

### ISSUE THREAD

**Issue by wanlizhu** [microsoft/vcpkg#11076]
**Describe the bug**
Could not find a configuration file for package, even through the package installed successfully

**Environment**
- OS: [Windows10]
- Compiler: Visual Studio 16 2019 -A x64

**To Reproduce**
1. run `vcpkg integrate install` 
2. install `glfw3` by running: `vcpkg install glfw3:x64-windows`
3. Calling CMake command with vcpkg toolchain file `vcpkg/scripts/buildsystems/vcpkg.cmake`
4. find glfw3 using `find_package(glfw3 REQUIRED)`, then it'll fail

**Expected behavior**
Found installed `glfw3` without error

**Failure logs** 
```
CMake Error at C:/Users/zhuwa.ADS/vcpkg/scripts/buildsystems/vcpkg.cmake:329 (_find_package):
[cmake]   Could not find a configuration file for package "glfw3" that is compatible
[cmake]   with requested version "".
[cmake] 
[cmake]   The following configuration files were considered but not accepted:
[cmake] 
[cmake]     C:/Users/zhuwa.ADS/vcpkg/installed/x64-windows/share/glfw3/glfw3Config.cmake, version: 3.3.2 (64bit)
[cmake] -- Configuring incomplete, errors occurred!
```

**Additional context**
This bug is not always appeared. Sometimes, it'll be failed, sometimes not.

**Comment by Neumann-A** [comment]
In general this happens if the architecture does not match i.e. x86 vs x64. 
Maybe you are sometimes switching architecture without noticing it?

**Comment by wanlizhu** [comment]
Yes, it is the reason indeed. Thanks for your answer.
