### ISSUE TITLE
[vcpkg] Ignore missing ports in VCPKGs installed database

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#11078]
```
Computing installation plan...
Error: while loading cmake:x64-windows-static: Port definition not found.
Please run "vcpkg remove cmake:x64-windows-static" and re-attempt.
```

Is just anoying getting these kind of messages when I reuse vcpkg for different PRs/branches with additional ports.
Or give me an option like `--ignore-missing`

**Comment by traversaro** [comment]
Related issue: https://github.com/microsoft/vcpkg/issues/10119 .

**Comment by Neumann-A** [comment]
I think this behavior was fixed.

**Comment by traversaro** [comment]
Unfortunately I am afraid the problem was reintroduced recently, see https://github.com/microsoft/vcpkg/issues/15836 . However it is tracked there, so probably there is no need to re-open this issue.
