### ISSUE TITLE
[libiconv] Also build on non windows platforms

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#11071]
Or is there a specific reason why libiconv is only building on windows and not the other platforms?

**Comment by NancyLi1013** [comment]
Hi @Neumann-A 
I checked the history changes for `libicnv` and found this seemed to be changed by this [commit ](https://github.com/microsoft/vcpkg/commit/9f9778ccff48981a691bf34f30ecc4bf2efd5ac1#diff-75f5e80b0de8152d23315062163fd547).
But I also don't know why we only build this on Windows.

**Comment by Neumann-A** [comment]
closing since iconv can be buildtin to the c library.
