### ISSUE TITLE
[vcpkg] hash-check on download sometimes runs on `*.tar.gz.part`

### ISSUE THREAD

**Issue by Farwaykorse** [microsoft/vcpkg#11081]
**Describe the bug**
Incidentally a port install fails because of the hash-check on the downloaded archive for (at least) the portable CMake.
It tries to verify the hash on a `*.tar.gs.part` file instead of the `*.tar.gs` file.

**Environment**
- Seen on the TravisCI bionic image (Ubuntu 18.06)

**To Reproduce**
Only happens incidentally. I've only seen this happen a few times on TravisCI.

**Failure logs** 
A TravisCI run executing `vcpkg install` for two packages: [gist with outputs](https://gist.github.com/Farwaykorse/51e805f387cfd78a4f8aa150846caef6)
The first install (ms-gsl) fails, the second succeeds.

**Comment by NancyLi1013** [comment]
Hi @Farwaykorse 
Thanks for posting this issue.
There is only `cmake-3.14.0-Linux-x86_64.tar.gz` instead of `cmake-3.14.0-Linux-x86_64.tar.gz.part
` file.
So the file should be correct.

As for the issue you encountered, I'm not sure why this failed on your machine. We never met this situation on Windows, Linux and OSX platforms.

Did you need to update the hash value to the new one to install the port?

**Comment by Farwaykorse** [comment]
Hi @NancyLi1013 
There was no need to change the hash.
In the same CI job a second port install was started, directly after the first in a single bash-script, which downloaded CMake again and succeeded.
`````Bash
./vcpkg install ms-gsl
./vcpkg install gtest
`````
The error message:
```Shell
File does not have the expected hash:
             url : [ https://github.com/Kitware/CMake/releases/download/v3.14.0/cmake-3.14.0-Linux-x86_64.tar.gz ]
       File path : [ /home/travis/tools/vcpkg/downloads/cmake-3.14.0-Linux-x86_64.tar.gz.part ]
   Expected hash : [ e687c0f3acfb15c880ddac67e2821907f833cb900c6ecedb4ab5df5102604d82753c948e3c7dca6e5bcce6278a09b7d577b1afade2e133aec5b2057ac48d3c74 ]
     Actual hash : [ 307be647cae6546248a5bd9e52b7951a3c9c150d48f0e9e542acb1329142276c2ec0b51d01e43867ba919b9ca06ee239f3c5fc2a2cc7b43ee391ea1dcde416c1 ]
````
I believe the `*.part` file is an artefact or temporary file from the tool (curl?) performing the download.

I'm not sure why the file is present for the first `vcpkg install` at the time when the hash was calculated.
But it seems to me the check should not match the wrong file.

**Comment by Farwaykorse** [comment]
Just now the issue appeared for both calls to `vcpkg install`:
https://travis-ci.com/github/Farwaykorse/fwkSudoku/jobs/325739028#L559

Notably, downloading Ninja (from GitHub) also failed in the same job. It is quite possible it shows due to a communication issue between GitHub and some of the TravisCI systems.

**Comment by NancyLi1013** [comment]
Hi @Farwaykorse 
Sorry for the late response.
I noticed the info you provided above and found that you installed cmake via your custom script instead of vcpkg. So I also don't know what happen in your case.

Could you please try to do these steps to use vcpkg?
```
 git clone https://github.com/Microsoft/vcpkg.git
 cd vcpkg
./bootstrap-vcpkg.sh
```

**Comment by NancyLi1013** [comment]
@Farwaykorse 
Please let me know if you still have this problem.

**Comment by NancyLi1013** [comment]
I'm closing this issue for now since inactive in a long time.
Please feel free to reopen this if it is still a problem for you.

**Comment by Sulfuric-Acid1024** [comment]
It's been more than three years, but I'm still having the exact same problem here:

![image](https://github.com/microsoft/vcpkg/assets/88928074/ce5f59e7-f5f3-47b6-8f1a-b2f29bd53743)

Error Message:

```
Computing installation plan...
The following packages will be built and installed:
    gazebo[bullet,core,dart,ffmpeg,gdal,graphviz,gts,libusb,openal,simbody]:x64-windows -> 2022-01-20#4
Detecting compiler hash for triplet x64-windows...
-- Using HTTP(S)_PROXY in environment variables.
Restored 0 package(s) from C:\Users\liuzx\AppData\Local\vcpkg\archives in 742 us. Use --debug to see more details.
Installing 1/1 gazebo:x64-windows...
Building gazebo[bullet,core,dart,ffmpeg,gdal,graphviz,gts,libusb,openal,simbody]:x64-windows...
-- Using cached gazebo3211.diff.
-- Downloading https://github.com/osrf/gazebo/archive/382dcc3f36095a8d79b5bc9c8b8ad346e867c51d.tar.gz -> osrf-gazebo-382dcc3f36095a8d79b5bc9c8b8ad346e867c51d.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Trying to load bundleconfig from D:\Program_Files\vcpkg\vcpkg-bundle.json
[DEBUG] Failed to open: D:\Program_Files\vcpkg\vcpkg-bundle.json
[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
[DEBUG] Metrics enabled.
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Feature flag 'dependencygraph' unset
Downloading https://github.com/osrf/gazebo/archive/382dcc3f36095a8d79b5bc9c8b8ad346e867c51d.tar.gz
[DEBUG] Trying to hash D:\Program_Files\vcpkg\downloads\osrf-gazebo-382dcc3f36095a8d79b5bc9c8b8ad346e867c51d.tar.gz.6488.part
[DEBUG] D:\Program_Files\vcpkg\downloads\osrf-gazebo-382dcc3f36095a8d79b5bc9c8b8ad346e867c51d.tar.gz.6488.part has hash 1ddae39a5e46708d11729786853b199dbf5a8dadf9dfa6a32d82defe820d8721fb51ae22b6f041703bcdc4680fce15adf21c6fa8c3a11413d8b072ac8a8557ee
error: Failed to download from mirror set
error: File does not have the expected hash:
url: https://github.com/osrf/gazebo/archive/382dcc3f36095a8d79b5bc9c8b8ad346e867c51d.tar.gz
File: D:\Program_Files\vcpkg\downloads\osrf-gazebo-382dcc3f36095a8d79b5bc9c8b8ad346e867c51d.tar.gz.6488.part
Expected hash: 57638cd0b23b5f2bfd32fdc159d6cd77ca34e3bd695c225591979aef4b7271eac93d3706fa1ffa2340f90013267a4171bebe1e4c142f19ad2bf67963dfed627e
Actual hash: 1ddae39a5e46708d11729786853b199dbf5a8dadf9dfa6a32d82defe820d8721fb51ae22b6f041703bcdc4680fce15adf21c6fa8c3a11413d8b072ac8a8557ee
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(1045):
[DEBUG] Time in subprocesses: 0us
[DEBUG] Time in parsing JSON: 6us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 5783us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 9.7 s (9654685us)
```
