### ISSUE TITLE
[vcpkg/cmake] Add pkg-config to path for CMake?

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#11088]
Cannot really tell if this is something desirable or not. I just see a know that a few ports use `find_package(PkgConfig OPTIONAL)`. So I think this should be discussed.

**Comment by Voskrese** [comment]
will add how you can use it

https://github.com/Kitware/CMake/blob/master/Modules/UsePkgConfig.cmake

```
## Config
exec_program(pkg-config
              ARGS --cflags glib-2.0
              OUTPUT_VARIABLE GLIB_CFLAGS)
exec_program(pkg-config
              ARGS --libs glib-2.0
              OUTPUT_VARIABLE GLIB_LDFLAGS)
```

**Comment by BillyONeal** [comment]
It seems like ports should use `vcpkg_add_to_path` if they want to do this.
