### ISSUE TITLE
[vcpkg] how to disable default features

### ISSUE THREAD

**Issue by fran6co** [microsoft/vcpkg#11097]
Is there a way to disable the default features? Couldn't find it in the documentation.

For example I would like to install magnum without sdl support but with glfw, I tried doing this but it doesn't work:

`vcpkg install magnum[glfwapplication,-sdl2application]`

**Comment by Neumann-A** [comment]
`vcpkg install magnum[core, glfwapplication]` If you want the other default features you have to explicitly list them.

**Comment by fran6co** [comment]
Thanks, that's not very clear from the documentation or I missed something

**Comment by linquize** [comment]
Note: it should be `vcpkg install magnum[core,glfwapplication]`
cannot have space between feature names: `vcpkg install magnum[core, glfwapplication]`
