### ISSUE TITLE
[vcpkg] vcpkg_acquire_msys wrong working dir at line 124

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#11099]
```
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:50 (_execute_process):
  _execute_process called with no value for WORKING_DIRECTORY.
Call Stack (most recent call first):
  scripts/cmake/vcpkg_acquire_msys.cmake:121 (vcpkg_execute_required_process)
  ports/lapack-reference/portfile.cmake:17 (vcpkg_acquire_msys)
  scripts/ports.cmake:90 (include)
```

Uses` ${SOURCE_PATH}` at line 124 which is not necessarily defined in the function call

**Comment by linquize** [comment]
what port did you install?

**Comment by Neumann-A** [comment]
a custom one where `vcpkg_acquire_msys` is before `vcpkg_from_github`.
Its bad practice to try to access variables in a function which might not be defined in the scope of the function unless those variables are defined before the include of the function.

**Comment by linquize** [comment]
CMake can set a variable to parent scope
```cmake
set(NAME VALUE PARENT_SCOPE)
```
and vcpkg has this kind of cmake statement.

**Comment by Neumann-A** [comment]
the function call is CHILD_SCOPE ....
https://github.com/microsoft/vcpkg/blob/2bc6cd714f931c32d3299a137d5abe0f86f803e1/scripts/cmake/vcpkg_acquire_msys.cmake#L120-L125

SOURCE_PATH is not defined within the function 
should probably be TOOLPATH as in 
https://github.com/microsoft/vcpkg/blob/2bc6cd714f931c32d3299a137d5abe0f86f803e1/scripts/cmake/vcpkg_acquire_msys.cmake#L108-L113

https://github.com/microsoft/vcpkg/blob/2bc6cd714f931c32d3299a137d5abe0f86f803e1/scripts/cmake/vcpkg_acquire_msys.cmake#L39

**Comment by linquize** [comment]
Typically, in `portfile.cmake`
```cmake
vcpkg_from_github(OUT_SOURCE_PATH SOURCE_PATH ......)
```

in `vcpkg_from_github.cmake`,
```cmake
vcpkg_extract_source_archive_ex(OUT_SOURCE_PATH SOURCE_PATH ......)
```

in `vcpkg_extract_source_archive_ex.cmake`,
It will set SOURCE_PATH to `PARENT_SCOPE`

If you do not call `vcpkg_from_github()`, `SOURCE_PATH` is not set.

**Comment by ras0219-msft** [comment]
Thanks @Neumann-A for the accurate and precise problem description!
