### ISSUE TITLE
[vcpkg] Improve bootstrap detection of VS2015 version

### ISSUE THREAD

**Issue by ras0219-msft** [microsoft/vcpkg#1109]
https://github.com/Azure/azure-batch-software-entitlement/blob/fbac30d55bf8c3cef48dad87d0ee3da55a5b3519/docs/build-guide.md#troubleshooting

We should detect the VS2015 version during bootstrap and notify the user that they need at least Update 3.

**Comment by LilyWangL** [comment]
This issue hasn’t been updated in a year, if it is still an issue, please reopen.
