### ISSUE TITLE
[poco] Remove unneeded dependencies from core feature

### ISSUE THREAD

**Issue by linquize** [microsoft/vcpkg#11094]
`poco` core feature should not depend on `libpq` and `libpng`, but add `openssl`. Then an **equivalent** set of files is produced.

After `vcpkg install poco`, disk space used: 2.2GB (original) vs 1.4GB (without `libpq`) which saves 800MB!

To verify this change makes **equivalent** files, here are the 2 scripts to print the file lists and hashes in `packages/poco_x64-linux` directory.

Dockerfile 1
```dockerfile
FROM ubuntu:focal

RUN apt-get update && apt-get install -y curl tar unzip git g++ make && rm -rf /var/lib/apt/lists/*
WORKDIR /src
RUN git clone git://github.com/Microsoft/vcpkg.git . && git checkout 2020.04
RUN ./bootstrap-vcpkg.sh
RUN apt-get update && apt-get install -y bison flex && rm -rf /var/lib/apt/lists/*
RUN ./vcpkg install poco
RUN find packages/poco_x64-linux -type f ! -name vcpkg_abi_info.txt ! -name CONTROL | sort | sha1sum `xargs` | tee sum.txt && sha1sum sum.txt
```

Dockerfile 2
```dockerfile
FROM ubuntu:focal

RUN apt-get update && apt-get install -y curl tar unzip git g++ make && rm -rf /var/lib/apt/lists/*
WORKDIR /src
RUN git clone git://github.com/Microsoft/vcpkg.git . && git checkout 2020.04
RUN ./bootstrap-vcpkg.sh
RUN sed -ie 's/, libpq,/, openssl,/g' ports/poco/CONTROL && sed -ie 's/, libpng//g' ports/poco/CONTROL
RUN ./vcpkg install poco
RUN find packages/poco_x64-linux -type f ! -name vcpkg_abi_info.txt ! -name CONTROL | sort | sha1sum `xargs` | tee sum.txt && sha1sum sum.txt
```

**Comment by NancyLi1013** [comment]
Hi @linquize 
Thanks for posting this issue.
It seems that `libpq `is required for feature `postgresql` and `libpng `is required for feature `pdf`.
So they can be removed from the dependency lists.

But as for `openssl `, it looks like optional instead of required, which can be referred [here](https://github.com/pocoproject/poco/blob/master/README.md).

`OpenSSL headers and libraries (optional, but recommended)`

**Comment by linquize** [comment]
However, poco 's CMakLists.txt uses find_package to detect SSL present.

**Comment by linquize** [comment]
However, poco 's CMakLists.txt uses find_package to detect if OpenSSL present. 
If installed directory already has openssl, find_package will return openssl is present.

**Comment by linquize** [comment]
Yes, you can create a separate feature call openssl that depends on openssl

**Comment by NancyLi1013** [comment]
Since it's related to #10108, we can track this issue there #10108.
I'm closing this issue for now.
