### ISSUE TITLE
[cpprestsdk] DLLs do not have the App Container bit set

### ISSUE THREAD

**Issue by lsalamon** [Microsoft/vcpkg#111]
I have this error when run this command:
C:\Users\MYUSER\Desktop\Sources\vcpkg>.\toolsrc\Release\vcpkg.exe install cpprestsdk:x86-uwp zlib:x64-windows
-- CURRENT_INSTALLED_DIR=C:/Users/MYUSER/Desktop/Sources/vcpkg/installed/x86-uwp
-- DOWNLOADS=C:/Users/MYUSER/Desktop/Sources/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/Users/MYUSER/Desktop/Sources/vcpkg/packages/cpprestsdk_x86-uwp
-- CURRENT_BUILDTREES_DIR=C:/Users/MYUSER/Desktop/Sources/vcpkg/buildtrees/cpprestsdk
-- CURRENT_PORT_DIR=C:/Users/MYUSER/Desktop/Sources/vcpkg/ports/cpprestsdk/.
-- Cloning
-- Cloning done
-- Adding worktree and patching
-- Patching
-- Adding worktree and patching done
-- Configuring x86-uwp-rel
-- Configuring x86-uwp-rel done
-- Configuring x86-uwp-dbg
-- Configuring x86-uwp-dbg done
-- Build x86-uwp-rel
-- Build x86-uwp-rel done
-- Build x86-uwp-dbg
-- Build x86-uwp-dbg done
-- Package x86-uwp-rel
-- Package x86-uwp-rel done
-- Package x86-uwp-dbg
-- Package x86-uwp-dbg done
-- Warning: Could not find a matching pdb file for:
    C:/Users/MYUSER/Desktop/Sources/vcpkg/packages/cpprestsdk_x86-uwp/bin/cpprest_2_8.dll

-- Performing post-build validation
The following DLLs do not have the App Container bit set:

    C:/Users/MYUSER/Desktop/Sources/vcpkg/packages/cpprestsdk_x86-uwp/bin/cpprest_2_8.dll
    C:/Users/MYUSER/Desktop/Sources/vcpkg/packages/cpprestsdk_x86-uwp/debug/bin/cpprest_2_8.dll

This bit is required for Windows Store apps.
<b>Found 1 error(s). Please correct the portfile:</b>
    C:\Users\MYUSER\Desktop\Sources\vcpkg\ports\cpprestsdk\portfile.cmake

My vcpkg version is:
Vcpkg package management program version 0.0.30-e507c14229e5dd206499eef3ffa4e887131b9678

**Comment by ras0219-msft** [comment]
Thanks, this definitely looks like a bug in the `cpprestsdk` CMake/portfile.
