### ISSUE TITLE
[python3] build failure with linux dynamic triplet

### ISSUE THREAD

**Issue by ASxa86** [microsoft/vcpkg#11101]
**Host Environment**
- OS: Ubuntu 19.10
- Compiler: GCC v9.2.1

**To Reproduce**
copy/configure a dynamic triplet for linux.
[x64-linux-shared.txt](https://github.com/microsoft/vcpkg/files/4559335/x64-linux-shared.txt)
`./vcpkg install python3[enable-shared]:x64-linux-shared`

**Failure logs** 
```
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: make install -j 9
    Working Directory: /home/aaron/dev/vcpkg-python/vcpkg/buildtrees/python3/src/v3.7.3-1161ad7a91-x64-linux-shared-release
    See logs for more information:
      /home/aaron/dev/vcpkg-python/vcpkg/buildtrees/python3/make-build-x64-linux-shared-release-out.log
      /home/aaron/dev/vcpkg-python/vcpkg/buildtrees/python3/make-build-x64-linux-shared-release-err.log

Call Stack (most recent call first):
  ports/python3/portfile.cmake:141 (vcpkg_execute_build_process)
  scripts/ports.cmake:90 (include)


Error: Building package python3:x64-linux-shared failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: python3:x64-linux-shared
  Vcpkg version: 2020.02.04-unknownhash
```
[make-build-x64-linux-shared-release-err.log](https://github.com/microsoft/vcpkg/files/4559343/make-build-x64-linux-shared-release-err.log)

**Additional context**
It appears zlib is missing when attempting to build python3 as shared. I resolved this locally by adding zlib to ports/python3/CONTROL as a dependency.

**Comment by heydojo** [comment]
Hi @ASxa86 !
Just for clarity, you added zlib to the control file for the python3 port
https://github.com/microsoft/vcpkg/blob/master/ports/python3/CONTROL
and it resolved your issue? You were able to build then?

**Comment by ASxa86** [comment]
Yes. I was originally attempting to build boost:x64-linux-shared and it would always fail when attempting to build python3. I took a look at the error 

> zipimport.ZipImportError: can't decompress data; zlib not available

and tried adding zlib as a dependency to python3's control file. This appears to have resolved that compile error.

**Comment by NancyLi1013** [comment]
Hi @ASxa86 
Thanks for posting this issue.
I try to test this issue on my Ubuntu 18.04, gcc 9.2.1 and it can build successfully.

So I don't know if this issue only exists 19.10 or new version than this.

**Comment by NancyLi1013** [comment]
@heydojo 
Sorry, I dismissed the triplet before.

Now I can also reproduce this on my local.

After adding `zlib `as a dependency to `python3`, I encountered this error:
```
ModuleNotFoundError: No module named '_ctypes'In file included from /usr/include/string.h:494,
                 from ./Include/Python.h:30,
                 from Objects/structseq.c:4:
```
It seems that `libffi-dev` is required.

Installing via `sudo apt-get install libffi-dev` and then rebuild `python3` without any errors.

I will try to fix this later.
