### ISSUE TITLE
[vcpkg] TODO: Use pkg-config in vcpkg_fixup_pkgconfig to check for libraries

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#11103]
Currently `vcpkg_fixup_pkgconfig` uses a hand written parser to get the libs used in the *.pc file but this is incomplete and does not always work as intended. As such it is probably better to directly use pkg-config calls to analyse the generated *.pc files for correctness.

**Comment by strega-nil** [comment]
Do you want to do this @Neumann-A? I can assign you, if you like.

**Comment by Neumann-A** [comment]
List available in: https://github.com/microsoft/vcpkg/pull/12151#issuecomment-651581440

**Comment by traversaro** [comment]
This has been fixed for `ffmpeg` in https://github.com/microsoft/vcpkg/pull/11273, as it was necessary to fix a CI failure of the added port.
