### ISSUE TITLE
LLVM update to 10.0.0

### ISSUE THREAD

**Issue by alexreinking** [microsoft/vcpkg#11108]
Library name: LLVM

New version number: 10.0.0

The existing LLVM package is version 8.0.0. Versions 8.0.1, 9.0.0, 9.0.1, and 10.0.0 are newer and released. Halide, also an existing port, no longer supports LLVM 8. I would appreciate it if the version could be bumped, or if multiple versions could be made available.

**Comment by timautry** [comment]
See https://github.com/microsoft/vcpkg/pull/10295 [llvm] Update to version 10.0.0 and add new features

**Comment by alexreinking** [comment]
@timautry -- Thanks and sorry for the duplicate!
