### ISSUE TITLE
[opengl] Build faIled

### ISSUE THREAD

**Issue by dongliangcao** [microsoft/vcpkg#11107]
**Host Environment**
- OS: Windows
- Compiler: revision

**To Reproduce**
vcpkg install freeimage:x64-windows

**Failure logs** 
CMake Error at ports/opengl/portfile.cmake:20 (message):
  Cannot find Windows 10.0.18362.0 SDK.  File does not exist: C:\Program
  Files (x86)\Windows Kits\10\Lib\10.0.18362.0\um\x64\OpenGL32.Lib
Call Stack (most recent call first):
  scripts/ports.cmake:90 (include)

Error: Building package opengl:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: opengl:x64-windows
  Vcpkg version: 2020.02.04-nohash

**Comment by heydojo** [comment]
`Cannot find Windows 10.0.18362.0 SDK`

Would you confirm that you have the latest Windows SDK installed please?
The Windows SDK can be installed via the "individual components" section of the Visual Studio installer.
Thanks

**Comment by PhoebeHui** [comment]
@dongliangcao, does this still be a problem for you?

**Comment by PhoebeHui** [comment]
@dongliangcao, if the SDK installed, but it doesn't locate in C:\Program
  Files (x86)\Windows Kits, this error also occurs, It shoud be duplicated issue https://github.com/microsoft/vcpkg/issues/8288, feel free to reopen if it's different issue.
