### ISSUE TITLE
How do I change my library CMake to make it easier to create port for vcpkg

### ISSUE THREAD

**Issue by kreuzerkrieg** [microsoft/vcpkg#11118]
Is there a guideline what have to be done to existing CMake based library to make the port creation easier? Like, creating `INSTALL(TARGET)` section or something?

**Comment by LilyWangL** [comment]
You can refer to port sqlite3 or gtk, their CMakeLists.txt is write by the contributor who create them on VCPKG.
https://github.com/microsoft/vcpkg/blob/7e6e30ff8e9e0b823c212d4e61471989eebcbb0f/ports/sqlite3/CMakeLists.txt
https://github.com/microsoft/vcpkg/blob/70e7124cc485b943b911b0aae8ae30b4cbce9583/ports/gtk/CMakeLists.txt
