### ISSUE TITLE
[vcpkg_buildpath_length_warning] Please add advice to enable long paths on Windows 10

### ISSUE THREAD

**Issue by heydojo** [microsoft/vcpkg#11119]
The text in: https://github.com/microsoft/vcpkg/blob/master/scripts/cmake/vcpkg_buildpath_length_warning.cmake

Could offer a link to the Microsoft document concerning the issue, which is: https://docs.microsoft.com/en-gb/windows/win32/fileio/naming-a-file#enable-long-paths-in-windows-10-version-1607-and-later

This is on the condition that Windows 10 is the host operating system.

Currently, the console just gets spammed with:

```console
CMake Warning at scripts/cmake/vcpkg_buildpath_length_warning.cmake:4 (message):
  qt5-webengine's buildsystem uses very long paths and may fail on your
  system.

  We recommend moving vcpkg to a short path such as 'C:\src\vcpkg' or using
  the subst command.
Call Stack (most recent call first):
  installed/x64-windows/share/qt5/qt_download_submodule.cmake:13 (vcpkg_buildpath_length_warning)
  ports/qt5-webengine/portfile.cmake:72 (qt_download_submodule)
  scripts/ports.cmake:90 (include)
```

Thanks!

**Comment by Voskrese** [comment]
josm

https://github.com/microsoft/vcpkg/issues/10200

**Comment by BillyONeal** [comment]
I think we should add such instructions if and only if we have observed that building these ports with that flag enabled in a location wherein the directory structure would result in paths that are too long succeeds with the flag set and fails without.

Note that this probably means build tools and similar would need to be manifested and I'm pretty sure Qt depends on some that are not, but only testing would tell. See https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#enable-long-paths-in-windows-10-version-1607-and-later for additional details. (I believe there were version(s) of Windows 10 that had bugs where either the flag or the manifest were not correct checked but that was considered a bug)
