### ISSUE TITLE
I can't install lib on wsl in visual studio cmake file directly.

### ISSUE THREAD

**Issue by jiayuehua** [microsoft/vcpkg#11110]
- vc output

Installation started on background task.
Running '"/home/rob/openSrc/vcpkg/vcpkg" install sqlite3:x64-linux 2>&1' on 'WSL'...

[vcpkg] Error: Could not detect vcpkg-root.
[vcpkg] 

Installation of 'sqlite3' failed.

- vcpkg on wsl linux command line 
from command line it work, but I can only run command and install lib in the vcpkg source repo dir from command line. sounds like some issue related to the vcpkg-root.

~/openSrc$ PATH=/home/rob/openSrc/vcpkg:$PATH
~/openSrc$ vcpkg install catch                        
Error: Could not detect vcpkg-root.
~/openSrc$ cd vcpkg 
~/openSrc/vcpkg$ vcpkg install catch
Computing installation plan...

**Comment by Voskrese** [comment]
https://github.com/microsoft/vcpkg/blob/3a1e8e01f57ab54559a588cb4cd9442a2f27b6c8/scripts/buildsystems/vcpkg.cmake#L142

file `ls -la /home/rob/openSrc/vcpkg/.vcpkg-root`

**Comment by jiayuehua** [comment]
thank voskrese. but I think the problem is not here. The error message is "Could not DETECT .vcpkg-root" rather than "not FIND .vcpkg-root". 

https://github.com/microsoft/vcpkg/blob/ef50d66690df4712495039e68054269d705c14b4/toolsrc/src/vcpkg.cpp#L99
99-115 show that one need to set VCPKG_ROOT if run vcpkg command out of vcpkg repo and its subdirs. 

I think there is some problem with this line of code:
https://github.com/microsoft/vcpkg/blob/ef50d66690df4712495039e68054269d705c14b4/toolsrc/src/vcpkg.cpp#L102
Sound like it just append VCPKG_ROOT to pwd absolute path.


~/openSrc$ export VCPKG_ROOT=/home/rob/openSrc/vcpkg 
~/openSrc$ vcpkg install catch                      
Error: Invalid vcpkg root directory /home/rob/openSrc/home/rob/openSrc/vcpkg: No such file or directory

otherwise:
~/openSrc$ export VCPKG_ROOT=vcpkg                  
~/openSrc$ vcpkg install catch    
Computing installation plan...
The following packages will be built and installed:

**Comment by Voskrese** [comment]
export vcpkg=VCPKG_ROOT
?

**Comment by jiayuehua** [comment]
export VCPKG_ROOT=vcpkg,  mean  set the VCPKG_ROOT relative path to pwd dir which is 'vcpkg'

**Comment by timautry** [comment]
export VCPKG_ROOT=/home/rob/openSrc/vcpkg
export PATH=$VCPKG_ROOT:$PATH

Should be able to install a port from any path/location...
At least on OpenSUSE Leap 15.1 it works.

**Comment by berkanuslu** [comment]
@timautry thanks but it didn't work for me.

I have the same error. I tried Ubuntu 18.04 and OpenSUSE Leap 15.1 in WSL. By the way, I can install packages from WSL's terminal. But VS2019 cannot run the command.

I tried it in VS2019 Community Version 16.6.0 Preview 5.0 and VS2019 Community Version 16.5.4. But there was no change.

**Comment by timautry** [comment]
See this article. It might help. I myself do not use WSL but a Hyper-V instance with OpenSuse Leap 15.1 installed with it own vcpkg instance and ports installed. 
https://devblogs.microsoft.com/cppblog/c-with-visual-studio-2019-and-windows-subsystem-for-linux-wsl/

**Comment by berkanuslu** [comment]
Thanks for sharing it. I read it before. Also, I watched this video. https://www.youtube.com/watch?v=ijmZKRIfoOI&list=PLReL099Y5nRdHYz4JwB0bq1kaVw2yGDag&index=3

I didn't understand, something is missing, but I didn't find it. If someone helps us, I'll be appreciated.

**Comment by timautry** [comment]
@berkanuslu  Ah, you need WSL2 which will not be generally available until the Windows 10 2004 May feature rollout later this month aka Windows 10 20H1...
 - One would need to install an Insider Preview 19041 or higher?
 - Right now Windows 10 has WSL1 which may be the problem?

**Comment by PhoebeHui** [comment]
@jiayuehua, does this still be a problem for you, I can't rero this issue with vcpkg latest source.

**Comment by jiayuehua** [comment]
Work fine now.but now I am using a new computer and update vs regularly. I don't use my old computer and old vs version any more, so I can't reproduce it.

**Comment by PhoebeHui** [comment]
@jiayuehua, glad it works for you now, thanks for your response!

**Comment by syheliel** [comment]
I meet this question in Ubuntu, and I find that it is caused by hard link. use `ln -s your_vcpkg_path /usr/bin/vcpkg` rather than the version without `-s` can solve it.
