### ISSUE TITLE
Expect and computed SHA512 are inverted

### ISSUE THREAD

**Issue by aspioupiou** [microsoft/vcpkg#11115]
**Describe the bug**
When customising the portfiles with a specific commit of a package and setting the hash to 1 as suggested here https://vcpkg.readthedocs.io/en/latest/maintainers/vcpkg_from_github/, expected and computed has are inverted :

```
      Expected hash: [ 1 ]
        Actual hash: [ caa392d99b6c60751924018b88080bfcc34803e2f3af7f0c064a05dce6c749247afbaaf13f66eed6ad9cb8b8d850f1891298151c963bb78fa36612a344837047 ]
```

**Environment**
- OS: All OS with latest vcpkg

**To Reproduce**
1. chose any packages and change the current commit id by another one.
2.  Set the SHA512 to 1
3. install the package.

This is just a GUI bug since it does not affect anything else

**Comment by Neumann-A** [comment]
No the order is correct. The expected hash is the hash in the portfile while the actual hash is the computed hash of the downloaded file

**Comment by aspioupiou** [comment]
@Neumann-A Sorry, I made a complete mismatched. Closing the issue.

Sorry for the inconvenience !
