### ISSUE TITLE
Odd CMake message

### ISSUE THREAD

**Issue by kreuzerkrieg** [microsoft/vcpkg#11117]
I'm getting the following warning when using `vcpkg`. Never encountered it. Any ideas what is the reason could possibly be and how to resolve it?

> Cannot generate a safe runtime search path for target compressed_buffer
>   because there is a cycle in the constraint graph:
> 
>     dir 0 is [/home/user/Development/vcpkg/installed/x64-linux/lib]
>       dir 1 must precede it due to runtime library [libodbc.so.2]
>     dir 1 is [/home/user/Development/vcpkg/installed/x64-linux/debug/lib]
>       dir 0 must precede it due to runtime library [libodbc.so.2]
> 
>   Some of these libraries may not be found correctly.

Looks like mixing debug and release versions?

**Comment by kreuzerkrieg** [comment]
Looks like `find_package` for `poco` was called twice. I dont know how it ends up with this message about `odbc` but maybe `vcpkg` can can produce more clear message?

**Comment by JackBoosY** [comment]
Hi @kreuzerkrieg, does this issue still exist?

**Comment by kreuzerkrieg** [comment]
No idea, I'm not "there" anymore
