### ISSUE TITLE
How do I use vcpkg without admin?

### ISSUE THREAD

**Issue by gilescope** [microsoft/vcpkg#11113]
Would love the docs on the readme to say what to do if you don't have admin as otherwise we're just stuck at the 'vcpkg integrate install' step. Even if there's a note there saying if you havn't got admin forget trying to do anything with vcpkg would be helpful - at least I'd know.

**Comment by linquize** [comment]
If you do not have admin right, you can adjust the additional linker directory per project basis. Then, you do not need `vcpkg integrate install`.

**Comment by timautry** [comment]
You can always use:
1. `.\vcpkg.exe integrate project` which creates a nupkg in `<vcpkg-root>\scripts\buildsystems\vcpkg.<Drive>.<Path>.1.0.0.nupkg`
2. Then when you create a new project you can add the nupkg using the instructs received when the nupkg was created.
3. I personally do this as I have VS2017 and VS2019 along with a test/prod version of each. The `vcpkg.exe integrate install` can only integrate one instance of vcpkg to all versions of VS2015, 2017 and 2019 installed on the system.
Example:
- With a project open, go to Tools->NuGet Package Manager->Package Manager Console and paste:
    - Install-Package vcpkg.D.Git.vs2019.test -Source "D:\Git\vs2019.test\scripts\buildsystems"
4. Just beware of the ports requiring a manual_linkage, like SDL2main, they can be found in:
   - `<vcpkg-root>\installed\<triplet>\lib\manual-link` for release
   - `<vcpkg-root>\installed\<triplet>\debug\lib\manual-link` for release
5. You will need to add them manually in the C/C++ linker lib properties along with adding the path on linker additional lib paths for each build type in your project, aka release, debug.

**Comment by Voskrese** [comment]
```
vcpkg integrate install --debug
[DEBUG] Using vcpkg-root: E:\tools\vcpkg
Applied user-wide integration for this vcpkg root.

All MSBuild C++ projects can now #include any installed libraries.
Linking will be handled automatically.
Installing new libraries will make them instantly available.

CMake projects should use: "-DCMAKE_TOOLCHAIN_FILE=E:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake"
[DEBUG] E:\tools\vcpkg\toolsrc\src\vcpkg\commands.integrate.cpp(294)
```

https://github.com/microsoft/vcpkg/blob/f7fb56decd9d03cf79a1d23f44daa3a23560b995/toolsrc/src/vcpkg/commands.integrate.cpp#L170

https://github.com/microsoft/vcpkg/blob/f7fb56decd9d03cf79a1d23f44daa3a23560b995/toolsrc/src/vcpkg/commands.integrate.cpp#L175

`dir C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\v140\ImportBefore\Default`

the folder `C:\Program Files (x86)` requires administrator rights

@

**Comment by heydojo** [comment]
On Windows (providing you have the Visual Studio C++ workload installed) I would try something like :
```console
SETLOCAL
CALL D:\Programs\MSVS2019\VC\Auxiliary\Build\vcvars64.bat"
SET SRCROOTDIR=D:\test
SET VCPKGDIR=%SRCROOTDIR%\vcpkg
SET QTDIR=%VCPKGDIR%\installed\x64-windows
CD %SRCROOTDIR%
git clone https://github.com/Microsoft/vcpkg
cd vcpkg
CALL .\bootstrap-vcpkg.bat
vcpkg install somelibrary:x64-windows someotherlibrary:x64-windows
```

followed by something like the following for a Qt application:

```console
cd .. && mkdir build && cd build
cmake .. -G "Visual Studio 16 2019" -A x64 -DQt5_DIR:PATH="%QTDIR%\share\cmake\Qt5" -DQMAKE_EXECUTABLE:FILEPATH="%QTDIR%\tools\qt5\bin\qmake.exe"
```
you then issue an msbuild command to build the .sln file which cmake generated for you in the previous step.

You don't need to `vcpkg integrate install` and I never do it myself.

**Comment by NancyLi1013** [comment]
@heydojo 
Please let me know if you still have problems about this issue.

**Comment by NancyLi1013** [comment]
I'm closing this issue for now. Please feel free to reopen this if it is still a problem for you.
