### ISSUE TITLE
"vcpkg integrate powershell" does not work with Powershell 7.0

### ISSUE THREAD

**Issue by baget** [microsoft/vcpkg#11126]
**Describe the bug**
when running `vcpkg integrate powershell`  on powershell 7.0, vcpkg does report that:

> A suitable version of powershell-core was not found (required v6.2.1)

Then try to download the older version

**Environment**
- OS: `Windows 10 - 10.0.18363.778`
- Powershell: `Powershell core 7.0.0`

**To Reproduce**
1. ./vcpkg install powershell
2. See the following prints:
```
A suitable version of powershell-core was not found (required v6.2.1). Downloading portable powershell-core v6.2.1...
Downloading powershell-core...
  https://github.com/PowerShell/PowerShell/releases/download/v6.2.1/PowerShell-6.2.1-win-x86.zip -> D:\MyProjects\GitHub\vcpkg\downloads\PowerShell-6.2.1-win-x86.zip
```

**Expected behavior**
To work with PowerShell 7.0.0 and do not try to download older version.

**Comment by timautry** [comment]
#8975 #9606 #10086 
1. The first time vcpkg is run to install a port it installs some necessary packages it needs in the tools directory, powershell core 6.2.1 is one. The message is as shown in the post above.
2. The powershell used by vcpkg is not the one used when you open a powershell prompt and use for vcpkg command completion integration. This is either the one installed with windows or another version if you downloaded and installed and is found in your PATH variable.
3. See below:

`SYSTEM@ANDROMEDA 05/02/2020  9:19:14 D:\Git\vs2019.prod`
`->pwsh --version`
`PowerShell 7.0.0`

`SYSTEM@ANDROMEDA 05/02/2020  9:19:14 D:\Git\vs2019.prod`

`->vcpkg integrate powershell`

`Adding the following line to C:\Users\Tim.Autry\Documents\PowerShell\Microsoft.PowerShell_profile.ps1:
    Import-Module 'D:\Git\vs2019.prod\scripts\posh-vcpkg'`

`Successfully added posh-vcpkg to your PowerShell profile. Please start a new Powershell window for the changes to take effect.`

Note: vcpkg has **NO** port named **powershell** so the command will fail:
`SYSTEM@ANDROMEDA 05/02/2020  9:19:31 D:\Git\vs2019.prod`
`->vcpkg install powershell`
`Computing installation plan...`
**`Error: Cannot find definition for package `powershell`.`**

**Comment by baget** [comment]
> 1. The first time vcpkg is run to install a port it installs some necessary packages it needs in the tools directory, powershell core 6.2.1 is one. The message is as shown in the post above.
> 2. The powershell used by vcpkg is not the one used when you open a powershell prompt and use for vcpkg command completion integration. This is either the one installed with windows or another version if you downloaded and installed and is found in your PATH variable.

so might need to change the wording of message, it is not clear.

**Comment by Voskrese** [comment]
make a PR PowerShell 7+
https://github.com/microsoft/vcpkg/pulls

> and the problem will disappear

**Comment by JIbald** [comment]
could someone maybe explain this to me a little further? 
I don't fully understand the explanation and can't make vcpkg work.

**Comment by BillyONeal** [comment]
This has since been updated to PowerShell 7.0.3 in current `master` but I interpret this bug report to be "powershell integration should never try to acquire powershell and fail if a system one is not present"

**Comment by SHIHUAMarryMe** [comment]
PowerShell 7.1.4 also has this problem.

**Comment by LilyWangLL** [comment]
I couldn't reproduce this issue on powershell 7.2.4, command `.\vcpkg.exe integrate powershell` can run succeed, this issue should be fix.
![image](https://user-images.githubusercontent.com/94091114/172982026-9baf542b-1e61-4bfb-b04b-fbbf15069338.png)
