### ISSUE TITLE
Eigen fails to install latest version if an existing version is present

### ISSUE THREAD

**Issue by stekyne** [Microsoft/vcpkg#1112]
I had Eigen installed already but I think it's been updated to 3.3.3? It now fails to update correctly.

C:\Users\skyne\Source\Repos\csound\msvc>..\..\vcpkg\vcpkg.exe install eigen3 --triplet x64-windows
The following packages will be built and installed:
    eigen3:x64-windows
Building package eigen3:x64-windows...
-- CURRENT_INSTALLED_DIR=C:/Users/skyne/Source/Repos/vcpkg/installed/x64-windows
-- DOWNLOADS=C:/Users/skyne/Source/Repos/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/Users/skyne/Source/Repos/vcpkg/packages/eigen3_x64-windows
-- CURRENT_BUILDTREES_DIR=C:/Users/skyne/Source/Repos/vcpkg/buildtrees/eigen3
-- CURRENT_PORT_DIR=C:/Users/skyne/Source/Repos/vcpkg/ports/eigen3/.
-- Using cached C:/Users/skyne/Source/Repos/vcpkg/downloads/eigen-3.3.3.tar.bz2
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Configuring x64-windows-rel
CMake Error at Repos/vcpkg/scripts/cmake/vcpkg_execute_required_process.cmake:14 (message):
    Command failed: C:/Program Files/CMake/bin/cmake.exe;C:/Users/skyne/Source/Repos/vcpkg/buildtrees/eigen3/src/eigen-eigen-67e894c6cd8f;-DBUILD_SHARED_LIBS=ON;-DVCPKG_TARGET_TRIPLET=x64-windows;-DCMAKE_CXX_FLAGS= /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP;-DCMAKE_C_FLAGS= /DWIN32 /D_WINDOWS /W3 /utf-8 /MP;-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON;-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE;-DCMAKE_VERBOSE_MAKEFILE=ON;-DVCPKG_APPLOCAL_DEPS=OFF;-DCMAKE_TOOLCHAIN_FILE=C:/Users/skyne/Source/Repos/vcpkg/scripts/buildsystems/vcpkg.cmake;-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON;-DCMAKE_CXX_FLAGS_RELEASE=/MD /O2 /Oi /Gy /DNDEBUG /Zi;-DCMAKE_C_FLAGS_RELEASE=/MD /O2 /Oi /Gy /DNDEBUG /Zi;-DCMAKE_SHARED_LINKER_FLAGS_RELEASE=/DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF;-DCMAKE_EXE_LINKER_FLAGS_RELEASE=/DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF;-G;Visual Studio 15 2017 Win64;-DCMAKE_BUILD_TYPE=Release;-DCMAKE_INSTALL_PREFIX=C:/Users/skyne/Source/Repos/vcpkg/packages/eigen3_x64-windows
    Working Directory: C:/Users/skyne/Source/Repos/vcpkg/buildtrees/eigen3/x64-windows-rel
    See logs for more information:
      C:\Users\skyne\Source\Repos\vcpkg\buildtrees\eigen3\config-x64-windows-rel-out.log
      C:\Users\skyne\Source\Repos\vcpkg\buildtrees\eigen3\config-x64-windows-rel-err.log

Call Stack (most recent call first):
  Repos/vcpkg/scripts/cmake/vcpkg_configure_cmake.cmake:106 (vcpkg_execute_required_process)
  Repos/vcpkg/ports/eigen3/portfile.cmake:12 (vcpkg_configure_cmake)
  Repos/vcpkg/scripts/ports.cmake:73 (include)

Error: Building package eigen3:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: eigen3:x64-windows
  Vcpkg version: 0.0.81-8b85f125a24c8dcb6af116696f70b873846b9405

Error file:
CMake Error at CMakeLists.txt:415 (add_subdirectory):
  The source directory
    C:/Users/skyne/Source/Repos/vcpkg/buildtrees/eigen3/src/eigen-eigen-67e894c6cd8f/Eigen
  does not contain a CMakeLists.txt file.

CMake Error at unsupported/CMakeLists.txt:1 (add_subdirectory):
  The source directory
    C:/Users/skyne/Source/Repos/vcpkg/buildtrees/eigen3/src/eigen-eigen-67e894c6cd8f/unsupported/Eigen
  does not contain a CMakeLists.txt file.

Within one of the cmake files:
C:\Users\skyne\Source\Repos\vcpkg\buildtrees\eigen3\x64-windows-rel\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: 'pthread.h': No 

The solution was to delete the buildtree for eigen and install again.

**Comment by ras0219-msft** [comment]
Thanks for reporting this!

There was a mistake in the previous version's portfile which resulted in the problem you see. Deleting the buildtree is exactly the right workaround, and you shouldn't have this issue in the future.

**Comment by stekyne** [comment]
Ok great, thanks for the quick response!
