### ISSUE TITLE
Found trojan in vcpkg.exe

### ISSUE THREAD

**Issue by GauthamBanasandra** [microsoft/vcpkg#11125]
**Describe the bug**
I executed the following commands to install vcpkg -
```
PS> git clone https://github.com/Microsoft/vcpkg.git
PS> cd vcpkg
PS> .\bootstrap-vcpkg.bat
```

I tried to install OpenSSL by executing the following command -
```
PS> .\vcpkg install openssl:x64-windows
```

Windows Defender pops up with an alert on vcpkg as shown in this image - 
![vcpkg](https://user-images.githubusercontent.com/10280768/80855366-44f5df00-8c5e-11ea-8f9d-d2b588ae8e3e.jpg)

**Environment**
- OS: Windows 10
- Compiler: revision

**To Reproduce**
```
PS> git clone https://github.com/Microsoft/vcpkg.git
PS> cd vcpkg
PS> .\bootstrap-vcpkg.bat
PS> .\vcpkg install openssl:x64-windows
```

**Comment by Voskrese** [comment]
the code is publicly available, and you can analyze it in any way

**Comment by heydojo** [comment]
Hi @GauthamBanasandra what you appear to have discovered is what is called a "false positive." Such occurrences can be very common when using anti-virus software applications.
Please report your findings to the people at Microsoft developing Windows Defender.
vcpkg is clearly not a Wacatac.G!ml variant and as @Voskrese pointed out, the code is fully open source, so you can verify that as true for yourself if you like.

**Comment by timautry** [comment]
I too use Windows Defender, or is it Microsoft Defender now - LOL...
Anyway make sure you have the latest definitions, as it is clearly a false positive.
I have never had Defender state vcpkg was a virus, trojan, etc, etc... but I have had AVG, Avast, Norton all report vcpkg was some type of Malware from time to time in the past.

**Comment by GauthamBanasandra** [comment]
Thank you all. I'm not an expert in this matter. I just reported what I saw. If you all feel that there's no problem, then please feel free to close this issue.

**Comment by strega-nil** [comment]
Yeah, assuming you got the vcpkg sources from the correct upstream repository, it's definitely not a trojan. Please file a bug on Windows Defender, thanks!
