### ISSUE TITLE
Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)

### ISSUE THREAD

**Issue by lukkio88** [microsoft/vcpkg#11134]
Hi,

I have a CMakeFiles.txt for a project I'm currently working on. And among the lines I have this one:

```
find_package(PkgConfig REQUIRED)
```

Which makes crash when I try to run CMake with the following error:

```
CMake Error at C:/Program Files/CMake/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:445 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.17/Modules/FindPkgConfig.cmake:45 (find_package_handle_standard_args)
  C:/Projects/vcpkg/scripts/buildsystems/vcpkg.cmake:329 (_find_package)
  CMakeLists.txt:29 (find_package)
```

So I thought I had to install FindPackage and closest thing I came across that look to me like a procedure is this one:

`https://stackoverflow.com/questions/1710922/how-to-install-pkg-config-in-windows`

But I can't figure how this would apply to `vcpkg`

Could you help please?

**Comment by LilyWangL** [comment]
Related issue: #11088
