### ISSUE TITLE
[vcpkg/ninja] VS CMake tools for Windows/Linux overwrite ninja from within VCPKG

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#11133]
**Describe the bug**
If any CMake tools from VS are installed `vcpkg_find_acquire_program` will use ninja installed with the VS CMake tools instead of VCPKGs internal version which is currently a newer version.

**Environment**
- OS: Windows
- Compiler: VS 16.5.4

**To Reproduce**
Install CMake tools for Windows or for Linux in the VS Installer
Install any port using ninja and check the configure log. 

**Expected behavior**
Use the correct ninja version (newer or at least the same version as within VCPKG) 

**Failure logs** 
Example from one of the configure logs. 
`"-DCMAKE_MAKE_PROGRAM=C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe"`

**Comment by Voskrese** [comment]
if(GENERATOR STREQUAL "Ninja" VERSION_LESS "1.10")

NO FATAL ERROR ?
