### ISSUE TITLE
mongo-c-driver 1.6.1 not usable unders windows 10

### ISSUE THREAD

**Issue by rockonedege** [microsoft/vcpkg#11141]
**Describe the bug**
when used in cmake, the follwing error occurs:

> CMake Error at F:/vcpkg/scripts/buildsystems/vcpkg.cmake:329 (_find_package):
>   Could not find a package configuration file provided by "mongo-c-driver"
>   with any of the following names:
> 
>     mongo-c-driverConfig.cmake
>     mongo-c-driver-config.cmake
> 
>   Add the installation prefix of "mongo-c-driver" to CMAKE_PREFIX_PATH or set
>   "mongo-c-driver_DIR" to a directory containing one of the above files.  If
>   "mongo-c-driver" provides a separate development package or SDK, be sure it
>   has been installed.
> Call Stack (most recent call first):
>   CMakeLists.txt:40 (find_package)

**To Reproduce**
1`vcpkg install mongo-cxx-driver:x64-windows-static` and 'vcpkg install mongo-cxx-driver:x64-windows', all builds ok.
>mongo-c-driver:x64-windows                         1.16.1           Client library written in C for MongoDB.
>mongo-c-driver:x64-windows-static                  1.16.1           Client library written in C for MongoDB.
>mongo-cxx-driver:x64-windows                       3.4.0-4          MongoDB C++ Driver.
>mongo-cxx-driver:x64-windows-static                3.4.0-4          MongoDB C++ Driver.
2.  in a cmake file
```cmake
find_package(libmongocxx REQUIRED)
find_package(libbsoncxx REQUIRED)
find_package(mongo-c-driver CONFIG REQUIRED)
```

the above error shows

**Expected behavior**

no error

**Failure logs** 

-(please attached failure logs)

> -- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19613.
> -- clang-format found: D:/Program Files/LLVM/bin/clang-format.exe
> -- cmake-format not found!
> -- clang-tidy found: D:/Program Files/LLVM/bin/clang-tidy.exe
> -- include-what-you-use not found!
> -- cppcheck found: D:/Program Files/Cppcheck/cppcheck.exe
> -- dot found: D:/Program Files (x86)/Graphviz2.38/bin/dot.exe
> -- Environment Info
>    -- Binary Dir   - CMAKE_BINARY_DIR      = F:/WD/tf-amd/code/cpp/~build-windows
>    -- System Name  - CMAKE_SYSTEM_NAME     = Windows
>    -- Build type   - CMAKE_BUILD_TYPE      = 
>    -- Compiler ID  - CMAKE_CXX_COMPILER_ID = MSVC
>    -- Install path - CMAKE_INSTALL_PREFIX  = C:/Program Files (x86)/tf-amd
>    -- Home path    - CMAKE_HOME_DIRECTORY  = F:/WD/tf-amd/code/cpp
>    -- C++ Standard - CMAKE_CXX_STANDARD  = 17
>    -- Target = 64 bits build
> -- Disable macro min(), max()
> -- Use Windows 10 SDKs for Boost.Asio
> CMake Error at F:/vcpkg/scripts/buildsystems/vcpkg.cmake:329 (_find_package):
>   Could not find a package configuration file provided by "mongo-c-driver"
>   with any of the following names:
> 
>     mongo-c-driverConfig.cmake
>     mongo-c-driver-config.cmake
> 
>   Add the installation prefix of "mongo-c-driver" to CMAKE_PREFIX_PATH or set
>   "mongo-c-driver_DIR" to a directory containing one of the above files.  If
>   "mongo-c-driver" provides a separate development package or SDK, be sure it
>   has been installed.
> Call Stack (most recent call first):
>   CMakeLists.txt:40 (find_package)
> 
> 
> -- Configuring incomplete, errors occurred!

**Additional context**

**Comment by rockonedege** [comment]
The same fails to Linux.

>cmake_toolchain_file = vcpkg/scripts/buildsystems/vcpkg.cmake
build dir = ./~build-linux
-- clang-format found: /usr/bin/clang-format
-- cmake-format not found!
-- clang-tidy found: /usr/bin/clang-tidy
-- include-what-you-use not found!
-- cppcheck found: /usr/bin/cppcheck
-- dot found: /usr/bin/dot
-- Environment Info
   -- System Name  - CMAKE_SYSTEM_NAME     = Linux
   -- Build type   - CMAKE_BUILD_TYPE      = RELEASE
   -- Compiler ID  - CMAKE_CXX_COMPILER_ID = Clang
   -- Install path - CMAKE_INSTALL_PREFIX  = /usr/local 
   -- C++ Standard - CMAKE_CXX_STANDARD  = 17 
   -- Target = 64 bits build
CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:329 (_find_package):
  Could not find a package configuration file provided by "mongo-c-driver"
  with any of the following names:

    mongo-c-driverConfig.cmake
    mongo-c-driver-config.cmake

  Add the installation prefix of "mongo-c-driver" to CMAKE_PREFIX_PATH or set
  "mongo-c-driver_DIR" to a directory containing one of the above files.  If
  "mongo-c-driver" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:40 (find_package)


-- Configuring incomplete, errors occurred!
See also "~/code/cpp/~build-linux/CMakeFiles/CMakeOutput.log".
See also "~/code/cpp/~build-linux/CMakeFiles/CMakeError.log".
ninja: error: loading 'build.ninja': No such file or directory

**Comment by LilyWangL** [comment]
Thanks for posting this issue. This issue has been fixed. You can update VCPKG and rebuild mongo-c-driver.

**Comment by rockonedege** [comment]
It's not a clean fix. Warnings generated:

>CMake Warning at F:/vcpkg/installed/x64-windows/share/libmongoc-1.0/libmongoc-1.0-config.cmake:15 (message):
  This CMake target is deprecated.  Use 'mongo::mongoc_shared' instead.
  Consult the example projects for further details.
Call Stack (most recent call first):
  F:/vcpkg/scripts/buildsystems/vcpkg.cmake:329 (_find_package)
  CMakeLists.txt:42 (find_package)


>CMake Warning at F:/vcpkg/installed/x64-windows/share/bson-1.0/bson-1.0-config.cmake:15 (message):
  This CMake target is deprecated.  Use 'mongo::bson_shared' instead.
  Consult the example projects for further details.
Call Stack (most recent call first):
  F:/vcpkg/scripts/buildsystems/vcpkg.cmake:329 (_find_package)
  F:/vcpkg/installed/x64-windows/share/libmongoc-1.0/libmongoc-1.0-config.cmake:22 (find_package)
  F:/vcpkg/scripts/buildsystems/vcpkg.cmake:329 (_find_package)
  CMakeLists.txt:42 (find_package)
