### ISSUE TITLE
[boost] update to 1.73.0

### ISSUE THREAD

**Issue by 20zinnm** [microsoft/vcpkg#11147]
Library name: Boost

New version number: 1.73.0

**Comment by 20zinnm** [comment]
I can do this later today if nobody beats me to it.

**Comment by timautry** [comment]
Will we include the two new libraries, NoWide and StaticString?

**Comment by 20zinnm** [comment]
I'll look into it @timautry.

**Comment by timautry** [comment]
Thank you very much @20zinnm !!!

**Comment by yurybura** [comment]
@20zinnm Could I help you?) I had experience to update to v1.72 (#9317).

**Comment by 20zinnm** [comment]
@yurybura Go for it. I got a bit busier than expected yesterday.
