### ISSUE TITLE
Is there an error or inconsistency in where some libraries' headers are installed ? 

### ISSUE THREAD

**Issue by breathe67** [microsoft/vcpkg#11149]
What is the convention regarding how library headers are placed within ..\vcpkg\installed\x64-windows\include ? I am new to vcpkg, so I installed both sqlite3 and 7zip as a test. While 7zip has headers installed in an ..\include\7zip subdirectory , sqlite3's headers are right in the 'root' ..\include in the vcpkg path above.  If I were to keep installing packages, would some of them just dump all the headers to ..\installed ? ...and would this cause name conflicts ?

Looked for an answer in this github issue collection on port issues.

**Comment by BillyONeal** [comment]
I believe this is up to the individual ports.

**Comment by LilyWangL** [comment]
The installation of the header file depends on the configuration file of the port, such as the CMakeLists.txt. It is not up to VCPKG.
