### ISSUE TITLE
Not able to find Win SDK libraries using vcpkg

### ISSUE THREAD

**Issue by jamal** [microsoft/vcpkg#11150]
I was trying to get an example project using Skia with CMake and ran into an issue when trying to link against Skia in my project.

I don't think the issue is specific to Skia, as I was unable to use `find_library` to find Win SDK libraries when testing either.

CMake output on build:
```
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19041.
-- The C compiler identification is MSVC 19.25.28612.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/jamal/dev/ui/build
Microsoft (R) Build Engine version 16.5.0+d4cbfca49 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  main.cc
LINK : fatal error LNK1104: cannot open file 'SKIA_FONTSUB_LIB_LIBRARY-NOTFOUND.lib' [C:\Users\jamal\dev\ui\build\main.vcxproj]
```

I'm able to manually work around this by setting the `CMAKE_LIBRARY_PATH`, but my expectation would be that the vcpkg cmake toolchain would specify this.

Example CMakeLists.txt:
```
cmake_minimum_required(VERSION 3.0)
project(ui)

# The following was added to resolve the issue, removing this will cause the link failure
set(CMAKE_LIBRARY_PATH "C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.18362.0\\um\\x64")

# OpenGL
find_path(OPENGL_INCLUDE_DIR gl)
find_library(OPENGL_LIBRARY NAMES OpenGL32)

# SDL2
find_package(SDL2 CONFIG REQUIRED)

# Skia
find_package(skia CONFIG REQUIRED)

add_executable(main src/main.cc)

target_include_directories(main PRIVATE 
    ${OPENGL_INCLUDE_DIR})
target_link_libraries(main PRIVATE 
    ${OPENGL_LIBRARY}
    SDL2::SDL2 SDL2::SDL2main
    skia::skia)
```

**Comment by heydojo** [comment]
Remove the hack from your CMakeLists
```cmake
# The following was added to resolve the issue, removing this will cause the link failure
set(CMAKE_LIBRARY_PATH "C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.18362.0\\um\\x64")
```
and try setting up your build environment before you start a build by calling the right vcvars script first before calling cmake.

For example:

```console
SETLOCAL
SET MSVSDIR="D:\Programs\MSVS2019"
CALL %MSVSDIR%"\VC\Auxiliary\Build\vcvars64.bat"
MKDIR build
CD build
cmake .. -G "Visual Studio 16 2019" -A x64
```

Hope this helps.

**Comment by NancyLi1013** [comment]
Hi @jamal 
Thanks for posting this issue.
Have you added the option `"-DCMAKE_TOOLCHAIN_FILE=VCPKG_ROOT_PATH\vcpkg\scripts\buildsystems\vcpkg.cmake"` before building?

**Comment by jamal** [comment]
@heydojo The hack was only added to work around the issue temporarily. Is configuring the VC env (using `vcvars[arch].bat`) or otherwise expected? The documentation / examples don't reference that at all. That being said, yes, this also solves my problems without introducing the library path manually.

@NancyLi1013 Yes, I'm configuring the cmake toolchain file as expected.

**Comment by JackBoosY** [comment]
@jamal You can use the environment `$ENV{WindowsSdkDir}` to get the Windows SDK path.

**Comment by NancyLi1013** [comment]
@jamal 

Can this issue be solved after trying to use the above way from @JackBoosY ?

**Comment by NancyLi1013** [comment]
Closing this issue for now since there seems inactive for a long time. Please feel free to reopen this issue if it is still a problem for you.

**Comment by esohns** [comment]
I have encountered a similar issue. Linking fails because vcpkg/cmake seems to prepends its' 'installed' directory to Windows SDK libraries specified without a full path. Linking then fails with e.g.:
LINK : fatal error LNK1181: cannot open input file 'C:\vcpkg\installed\x64-windows\lib\winmm.lib'.
It should just be finding the 'WinMM.Lib' in 'C:\Program Files (x86)\Windows Kits\10\\lib\10.0.26100.0\\um\x64' instead.

I'm setting up the developer command prompt and using the cmake toolchain file as specified above.
