### ISSUE TITLE
Error on install on Linux: 'Error getting canonicalization of /vcpkg/vcpkg/triplets: Not a directory'

### ISSUE THREAD

**Issue by teqdruid** [microsoft/vcpkg#11167]
**Describe the bug**

Getting this while trying to build Linux docker image:
```
Step 15/22 : RUN ./vcpkg install capnproto:x64-linux
 ---> Running in 1cea0bbe295e
Error getting canonicalization of /vcpkg/vcpkg/triplets: Not a directory
The command '/bin/sh -c ./vcpkg install capnproto:x64-linux' returned a non-zero code: 1
```

This has worked in the past. (Sadly, I don't know the commit upon which it last worked.) It also fails on other packages.

**Environment**
- OS: 'mcr.microsoft.com/dotnet/core/sdk:3.1.201-bionic' (Ubuntu)
- Compiler: vcpkg commit cfc05991f5a73ee4b2df7d9132fc8a5a6a42224e

**To Reproduce**
1. ./vcpkg install install capnproto:x64
2. See error
Repro code when

**Expected behavior**
Install that package

**Failure logs** 
-(please attached failure logs)

**Additional context**

Dockerfile for repro:

```
FROM mcr.microsoft.com/dotnet/core/sdk:3.1.201-bionic
LABEL maintainer="John Demme (me@teqdruid.com)"

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install apt-utils -y
RUN apt-get update && apt-get install -y \
    curl tar \
    g++ \
    git \
    cmake 

RUN apt-get install -y unzip

# Compile vcpkg to get cross-platform C/C++ library management
RUN cd / && \
    git clone https://github.com/Microsoft/vcpkg.git && \
    cd vcpkg && \
    git checkout cfc05991f5a73ee4b2df7d9132fc8a5a6a42224e
WORKDIR /vcpkg
RUN ./bootstrap-vcpkg.sh
ENV VCPKG_ROOT=/vcpkg

# Install libraries
RUN ./vcpkg install capnproto:x64-linux
```

**Comment by BillyONeal** [comment]
Does https://github.com/microsoft/vcpkg/commit/46bf8c52cb343b6557a48b5b80aad56cdeedd4d8 fix this?

**Comment by teqdruid** [comment]
Yep. Thanks!
