### ISSUE TITLE
Read the Roadmap for VCPKG

### ISSUE THREAD

**Issue by vicroms** [microsoft/vcpkg#11177]
The [roadmap for vcpkg](https://github.com/microsoft/vcpkg/wiki/Roadmap) has been published and is available in this repository's wiki.  

Read the original announcement in our [blog post](https://devblogs.microsoft.com/cppblog/vcpkg-2020-04-update-and-product-roadmap/).
---
Last updated: April 21st, 2022

**Comment by Voskrese** [comment]
Wiki was needed a long time ago, and it's time to move all the documentation there

**Comment by AugP** [comment]
> Wiki was needed a long time ago, and it's time to move all the documentation there
Yes, we definitely need to expand the wiki now that we are using it to include docs. In general we need to consolidate the docs into one place and see what areas need to be better documented.

**Comment by andyzimmerer** [comment]
i don't know  the right terminal, Mac OS, json, or any app? I don't understand, the things make Siri with translator app shortcuts,json, and tools for the worker! I must go out in few minutes, maybe Siri do it or I must tomorrow wach agin

**Comment by andyzimmerer** [comment]
thank you

**Comment by Mike4Online** [comment]
Would be good to have a place to comment on various items in the roadmap (besides here).

Regarding Manifests, I suggest adding a **license-url** value.  The URL would lead to the text of the license.  You could then generate a list of open source libraries and their licenses by parsing each of the **vcpkg.json** files in your local source folder.  in the Java world, this can be done with the [License Maven Plugin](https://www.mojohaus.org/license-maven-plugin/) (which goes far beyond what I am suggesting).

I also suggest that **vcpkg.json** files permit additional values to be entered beyond what is in the specification.  I don't know enough about JSON and schemas to know if this is possible, or if explicit fields would need to be added for custom use.

**Comment by KaungZawHtet** [comment]
Plz reconsider port update mechanism. Current way is too manual. Authors have to make PR and wait for the approve every time new version come.

**Comment by ArcticLampyrid** [comment]
> Plz reconsider port update mechanism. Current way is too manual. Authors have to make PR and wait for the approve every time new version come.

Actually I prefer to fetch config from a remote url provided by package author.
Since vcpkg are actually distributed (all package source are served by package author's repository), why not make it more distributed?

**Comment by cyraid** [comment]
> > Plz reconsider port update mechanism. Current way is too manual. Authors have to make PR and wait for the approve every time new version come.
> 
> Actually I prefer to fetch config from a remote url provided by package author.
> Since vcpkg are actually distributed (all package source are served by package author's repository), why not make it more distributed?

And what happens if the package author does not provide updates in a timely manner? Let's say we need a security fix from a library, but the author is not around to update it?

What is the current recommended way to handle updating libraries like this?

**Comment by ArcticLampyrid** [comment]
> Let's say we need a security fix from a library, but the author is not around to update it?

Just like any other package managers (Npm/Nuget/Maven), if the author does not update it, you need to fetch the package from a fork (usually in another id).
Currently we maintain package configs in vcpkg repo, but we are not maintaining the libraries' content (That's unrealistic, you know). If the author does not maintain the library and there is no 3th-party patches, we won't receive a security fix.

**Comment by cyraid** [comment]
> > Let's say we need a security fix from a library, but the author is not around to update it?
> 
> Just like any other package managers (Npm/Nuget/Maven), if the author does not update it, you need to fetch the package from a fork (usually in another id).
> Currently we maintain package configs in vcpkg repo, but we are not maintaining the libraries' content (That's unrealistic, you know). If the author does not maintain the library and there is no 3th-party patches, we won't receive a security fix.

No of course not that is definitely unrealistic. But take skis library. It is always evolving, and the last update on vcpkg says from 2020. Is it because it's tied to a specific git version? Or is that date meaning it's the last time the build script of that library was updated? Sorry for clouding up your roadmap.

**Comment by ahmedyarub** [comment]
what is the roadmap of Q3 2021+?

**Comment by ffes** [comment]
Since this item is still pinned to the issues page, you apparently still consider this roadmap important. The only item remaining on the roadmap is "Vcpkg will be shipped with Visual Studio and Visual Studio Code" which has a date of 2021 Q2. Since we are already in 2021 Q4, I thought I asked if there is any news about that.

**Comment by JackBoosY** [comment]
Ping @AugP

**Comment by davidhunter22** [comment]
The VS 2022 road map https://docs.microsoft.com/en-us/visualstudio/productinfo/vs-roadmap in the C++ does not mention VCPKG at all. Has shipping it with VS in limbo?

**Comment by Hoikas** [comment]
The roadmap seems to be severely out of date at this point.

**Comment by JackBoosY** [comment]
Yeah, we are updating this.

**Comment by AugP** [comment]
I forgot to post here but I updated it in the last couple of weeks. We'll try to get more precise with our estimates for when feature work will land as we continue our planning process.

**Comment by Luiz-Monad** [comment]
> Plz reconsider port update mechanism. Current way is too manual. Authors have to make PR and wait for the approve every time new version come.

I use port overlays with submodules, it would be nicer if ports could have their own repositories, then it would be as easy as updating your git submodules from the remote-url in the json manifest of the port.
