### ISSUE TITLE
Would like to be able to see (or at least log) the build output for a given library during the install process.     

### ISSUE THREAD

**Issue by breathe67** [microsoft/vcpkg#11185]
I'd like to be able to see (or at least log) the build output for a given library during the 'vcpkg install libX' process. 

This is to confirm that the library is being built as expected. Sometimes a compiler may issue warnings that are hidden, and are important for a project that includes it. Another example might be to  confirm that compile time flags are compatible or are as expected - perhaps useful when debugging the parent project, profiling optimizations, etc.  

I'd imagine this would be easy, maybe just capture stdout/stderr from the lib's build process to a log file ?

**Comment by vicroms** [comment]
Hi @breathe67 

You can find log files for the multiple install steps in the buildtrees directory, the path should be `<vcpkg_path>/buildtrees/<library>`, for example:

In path `<vcpkg path>/buildtrees/curl`:

```
# Archive extraction logs
extract-err.log
extract-out.log

# Patch logs
patch-x86-windows-0-err.log
patch-x86-windows-0-out.log

# CMake configure step logs
config-x86-windows-err.log
config-x86-windows-out.log

# Build output (separated by build type: debug|release).
install-x86-windows-dbg-err.log
install-x86-windows-dbg-out.log
install-x86-windows-rel-err.log
install-x86-windows-rel-out.log

# vcpkg output
stdout-x86-windows.log
```

You should be able to open these files while the build is running.

**Comment by breathe67** [comment]
Thanks a lot - was searching a bit for this :)
