### ISSUE TITLE
vcpkg install newest boost failed

### ISSUE THREAD

**Issue by svenzhang2016** [microsoft/vcpkg#11181]
-- Using cached D:/vcpkg/vcpkg/downloads/boostorg-build-boost-1.72.0.tar.gz
-- Using source at D:/vcpkg/vcpkg/buildtrees/boost-build/src/ost-1.72.0-fa8b817276
-- Using cached D:/vcpkg/vcpkg/downloads/boost_LICENSE_1_0.txt
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.72.0/boostcpp.jam...
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.72.0/boostcpp.jam... Failed. Status: 6;"Couldn't resolve host name"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:175 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  ports/boost-build/portfile.cmake:27 (vcpkg_download_distfile)
  scripts/ports.cmake:90 (include)

Error: Building package boost-build:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-build:x86-windows
  Vcpkg version: 2020.02.04-nohash

**Comment by JackBoosY** [comment]
Please use my private repo: `https://github.com/JackBoos/vcpkg/tree/mirror_zhCN`

**Comment by PhoebeHui** [comment]
@svenzhang2016, you can also try workaround in https://github.com/microsoft/vcpkg/issues/12599#issuecomment-664725171

See more information in issue #12383.

**Comment by fly2sky2018** [comment]
the same problem for me .. 
//////////////////////////////////////////////////////////////////////
Starting package 1/54: boost-build:x64-windows
Building package boost-build[core]:x64-windows...
-- Using cached D:/Documents/GitHub/vcpkg/downloads/boostorg-build-boost-1.75.0.beta1.tar.gz
-- Cleaning sources at D:/Documents/GitHub/vcpkg/buildtrees/boost-build/src/75.0.beta1-4371cdd5cf.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/Documents/GitHub/vcpkg/downloads/boostorg-build-boost-1.75.0.beta1.tar.gz
-- Applying patch fix_options.patch
-- Using source at D:/Documents/GitHub/vcpkg/buildtrees/boost-build/src/75.0.beta1-4371cdd5cf.clean
-- Using cached D:/Documents/GitHub/vcpkg/downloads/boost_LICENSE_1_0.txt
-- User Skipping hash check for D:/Documents/GitHub/vcpkg/downloads/boost_LICENSE_1_0.txt.
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.75.0.beta1/boostcpp.jam -> boost-1.75.0.beta1-boostcpp.jam...
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.75.0.beta1/boostcpp.jam... Failed. Status: 6;"Couldn't resolve host name"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:205 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".

      If error with status 4 (Issue #15434),
      try setting "http://user:password@your-proxy-ip-address:port/".

      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  ports/boost-build/portfile.cmake:25 (vcpkg_download_distfile)
  scripts/ports.cmake:139 (include)


Error: Building package boost-build:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-build:x64-windows
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

Additionally, attach any relevant sections from the log files above.

**Comment by JackBoosY** [comment]
@fly2sky2018  https://gitee.com/jackboosy/vcpkg/issues/I44496
