### ISSUE TITLE
bootstrap-vcpkg.sh fails to compile on Mac OS X

### ISSUE THREAD

**Issue by tobbi** [microsoft/vcpkg#11184]
**Describe the bug**
After checking out the latest master branch and running `./bootstrap-vcpkg.sh`, I encounter a build failure.

Output:
https://pastebin.com/qQawB2Ba

**Environment**
- OS: [e.g. Windows/Linux etc...] Mac OS X
- Compiler: GNU 6.5.0 (according to output)

**To Reproduce**
1. Run `./bootstrap-vcpkg.sh`
2. See error

**Expected behavior**
Build should work fine.

**Failure logs** 
see above code block

**Comment by NancyLi1013** [comment]
Hi @tobbi 
Thanks for posting this issue.
It seems that this is duplicated to #8670. Let's track this issue there.
