### ISSUE TITLE
[New Port Request] RtAudio

### ISSUE THREAD

**Issue by AJIOB** [microsoft/vcpkg#11183]
Library name: RtAudio

Library description: RtAudio is a set of C++ classes that provide a common API for realtime audio input/output across Linux, Macintosh OS-X and Windows operating systems. 

Source repository URL: https://github.com/thestk/rtaudio

Project homepage (if different from the source repository): http://www.music.mcgill.ca/~gary/rtaudio/index.html

Anything else that is useful to know when adding (such as optional features the library may have that should be included): -

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
