### ISSUE TITLE
Libffi crashes in Debug mode

### ISSUE THREAD

**Issue by pim01** [microsoft/vcpkg#11188]
I am trying to compile the simplest gtkmm application (a gtk window). I have installed the required vcpkg packages.  I experience no problem when compiling and executing  the .exe generated in Release mode but that generated in the Debug mode crashes. Microsoft C++ runtime Library reports a 

> Debug Error ! Run-Time Check Failure #4:  Stack area around _alloca memory reserved by this function is corrupted.  concerning the libffi.dll installed  Debug mode target directory.  

![libffi-crash](https://user-images.githubusercontent.com/47497941/81131805-af539b80-8f4c-11ea-87a6-51fbad03d12a.PNG)

I simply observe that the size of the libffi.dll in Release (27kB) and Debug Mode (103kB) are different. 
which can be expected  when debugging symbols are placed into the objects of the dll.  Overwriting the corrupted dll produced in Debug mode with that produced in the Release mode makes the .exe target in Debug mode execute normally. I also observe that the  libffi.dll used in Release mode has the same size that the one shipped with my vcpkg repo. 

I don't know by which exact mechanism or compiler configuration option does the dll size inflate in debug mode. I guess there is some coupling with debugging symbols in the associated .pdb. 

My Debug mode  compiler cmd line options are the following; 

`/JMC /GS /W1 /Zc:wchar_t /I"C:\Users\Pierre\Documents\GitHub\vcpkg\installed\x64-windows\include" /ZI /Gm- /Od /Fd"x64\Debug\vc142.pdb" /Zc:inline /fp:precise /errorReport:prompt /WX- /Zc:forScope /RTC1 /Gd /MDd /FC /Fa"x64\Debug\" /EHsc /nologo /Fo"x64\Debug\" /Fp"x64\Debug\about.pch" /diagnostics:column 
`
 My Release mode cmd line option is this one: 

`/GS /W1 /Zc:wchar_t /I"C:\Users\Pierre\Documents\GitHub\vcpkg\installed\x64-windows\include" /Zi /Gm- /O2 /Fd"x64\Release\vc142.pdb" /Zc:inline /fp:precise /errorReport:prompt /WX- /Zc:forScope /Gd /MD /FC /Fa"x64\Release\" /EHsc /nologo /Fo"x64\Release\" /Fp"x64\Release\about.pch" /diagnostics:column`

Any help would be appreciated. Thanks.

**Comment by NancyLi1013** [comment]
Hi @pim01 
Thanks for posting this issue.
It's duplicated to #10230. Let's track this issue there.
