### ISSUE TITLE
[New Port Request] djarek/certify

### ISSUE THREAD

**Issue by 20zinnm** [microsoft/vcpkg#11182]
Library name: certify

Library description: Boost.ASIO-based TLS certificate verification library

Source repository URL: https://github.com/djarek/certify

Project homepage (if different from the source repository): https://djarek.github.io/certify/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

I've already written a portfile for it, but I'm not sure what the policy is for proposed boost libraries. The repo is set up exactly like a Boost library, so it's trivial to add it to vcpkg, but It's not actually an official Boost library. Does it still get to put its header files in the Boost include directory?

**Comment by 20zinnm** [comment]
Here is the portfile that works for me:

```cmake
include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO djarek/certify
    REF bb7b58c260ad75f1287ffddee9671ff7019e7524
    SHA512 96274554da778f0f5646058c6d4999d6f6d404b3b86c96037985d900013bc51a0657bde5d988f6beb2a51e867910a7a555f2529736bb1127d4476272889be81f
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
```

As you can see, it treats certify as a boost package. However, it's not yet an official package.

**Comment by LilyWangL** [comment]
@20zinnm Thanks for posting this issue. Could you please submit a PR to add this port?

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now

**Comment by Nolanlemahn** [comment]
Hi - I'm interested in having this port added (or doing some legwork), but I'm fairly new to the vcpkg ecosystem and flows.

One thing that I'm noticing: Certify is (still) not yet part of Boost - it seems to me like if it's named as `certify` (or `djarek-certify`), it becoming `boost-certify` later could be confusing.

I also don't expect `scripts/boost/generate-ports.ps1` to work here. Any suggestions? (I've read most of the contributor/maintainer guides.)
