### ISSUE TITLE
[Python] build & export wheel

### ISSUE THREAD

**Issue by Voskrese** [microsoft/vcpkg#11192]
maybe worth making an analog https://www.lfd.uci.edu/~gohlke/pythonlibs , because all the tools for this are there

`python setup.py bdist_wheel`

```
python -m pip wheel --global-option bdist_ext --global-option -DFOO wheel
python setup.py bdist_ext -DFOO bdist_wheel -d TARGET
```

```
python setup.py bdist --format=zip

Formats
bdist_dumb 	tar, gztar, bztar, xztar, ztar, zip
bdist_rpm 	rpm, srpm
bdist_wininst 	wininst
bdist_msi 	msi
```

build a 64bit version of your extension. The Windows Installers also support this option, so the command:

> Valid values are currently ‘win32’, ‘win-amd64’ and ‘win-ia64’

`python setup.py build --plat-name=win-amd64 bdist_wininst`

**Comment by strega-nil** [comment]
Would you like to do this? We'd really appreciate having this feature 😄
