### ISSUE TITLE
gtk:x64-windows build failure

### ISSUE THREAD

**Issue by SZ-Berlin** [microsoft/vcpkg#11194]
**Host Environment**
- OS: Windows 10 64x
- Compiler: Microsoft Visual Studio Professional 2019 Version 16.5.4

**To Reproduce**
 .\vcpkg.exe install gtk:x64-windows

**Failure logs** 
stdout-x64-windows:

```
Using cached C:/Tools/vcpkg/downloads/anholt-libepoxy-1.5.3.tar.gz
 -- Extracting source C:/Tools/vcpkg/downloads/anholt-libepoxy-1.5.3.tar.gz
 -- Using source at C:/Tools/vcpkg/buildtrees/libepoxy/src/1.5.3-d7b9d32fcb
 -- Acquiring MSYS Packages... 
 CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: C:/Tools/vcpkg/downloads/tools/msys2/msys64/usr/bin/bash.exe --noprofile  --norc -c "pacman -Sy --noconfirm --needed pkg-config"
    Working Directory: C:/Tools/vcpkg/downloads/tools/msys2
    Error code: 255
    See logs for more information:
      C:\Tools\vcpkg\buildtrees\libepoxy\msys-pacman-x64-windows-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_acquire_msys.cmake:108 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_configure_meson.cmake:106 (vcpkg_acquire_msys)
  ports/libepoxy/portfile.cmake:12 (vcpkg_configure_meson)
  scripts/ports.cmake:90 (include)
```

msys-pacman-x64-windows-err: 

`error: failed to initialize alpm library
(could not find or read directory: /var/lib/pacman/)
`

**Additional context**
VS language packs English is installed.
vcpkg new build.

**Comment by Voskrese** [comment]
Error code: 255
    See logs for more information:
      C:\Tools\vcpkg\buildtrees\libepoxy\msys-pacman-x64-windows-err.log

**Comment by timautry** [comment]
It looks like the msys2/mingw tool is corrupt or was unable to download all the appropriate files.
My suggestion would be:
- to make sure `full access` rights are given to the userid used to access the `C:\Tools\vcpkg` folder/files and all sub-folders/files
- to rename the _msys2_ folder found in `C:\Tools\vcpkg\downloads\tools\msys2` to _msys2.old_ and try again
- hopefully vcpkg will download/recreate the msys2/mingw tools 
- when all works then delete/remove `C:\Tools\vcpkg\downloads\tools\msys2.old` folder.

**Comment by SZ-Berlin** [comment]
Hello, Timautry,
your suggestion was successful. 
Thank you and stay healthy.
-- SZ

```
Installing package libepoxy[core]:x64-windows... done
Installing package gtk[core]:x64-windows... done
```
