### ISSUE TITLE
Why does Vcpkg try to download and install older versions of tools than ones that I have already installed?

### ISSUE THREAD

**Issue by tats-u** [microsoft/vcpkg#11196]
****

**Is your feature request related to a problem? Please describe.**
I have already installed PowerShell 7.0.0, but Vcpkg downloaded and installed 6.2.1.  This spended my time and network bandwidth.
Looking into `scripts/vcpkgTools.xml` and `toolsrc/src/tools.cpp`, Vcpkg does not seem to check the versions of tools installed in system.

**Proposed solution**
It wold be nice if maximum and minimum required versions for each tool, and how to analyze versions of tools already in PATH are given in `vcpkgTools.xml`.

**Describe alternatives you've considered**

**Additional context**

**Comment by timautry** [comment]
Using the lastest/greatest versions of the utility software introduces an unknown element into the stability of vcpkg and degrades the user experience. 
Example a few weeks ago, ninja was upgraded from 1.8.2 to 1.10.0 and many ports began failing as a change was made in how multiple build versions defined in cmake files where handled - under 1.8.2, this was flagged as a warning and the build continued, now under 1.10.0, this is flagged as an error and the build stops. There is a solution, but it will take time to test/implement effectively considering the 100's of ports vcpkg is capable of installing.
One can always experiment and create test versions of vcpkg with customized changes to use the latest/greatest utility software. One can then share their findings and experience which will greatly enhance the experience using vcpkg.
_In the end, it would be nice if there was a gui type interface that one could put the path of already installed utility software to use..._

**Comment by Voskrese** [comment]
> **1.9**.2 to 1.10.0

**Comment by timautry** [comment]
- the vcpkg ninja was actually upgraded from 1.8.2 to 1.10.0 https://github.com/microsoft/vcpkg/commit/19ef8e31479d8f0d6a469c134080812944f2d7c1#diff-1efa33d774ab169851c15310ec385b92 
- the vcpkg ninja update from 1.8.2 to 1.10.0 identified how ninja was changed between 1.8.2 and 1.9.0 documented in #10887

**Comment by Voskrese** [comment]
the problem is another, it's when compiling at once a dynamic and static library

**Comment by timautry** [comment]
> the problem is another, it's when compiling at once a dynamic and static library

- to clarify, where ninja 1.8.2 previously treated by default the multiple definitions for release/debug (static/dynamic) as a warning, continuing the build
 - now version 1.10.0 (changed with 1.9.0) treats by default the multiple definitions for release/debug (static/dynamic) as an error, stopping the build
 - see PR https://github.com/microsoft/vcpkg/pull/10964

**Comment by Voskrese** [comment]
https://github.com/microsoft/vcpkg/pull/7055

https://github.com/microsoft/vcpkg/pull/7052

**Comment by JackBoosY** [comment]
I think this issue was resolved, right?

**Comment by tats-u** [comment]
It would be nice if Vcpkg could designate the version of dependencies as the formats like `^x.y.z`, `<x.y.z`, or something, which can be used in package managers for other languages (`npm`, `yarn`, `cargo`, and `poetry`) if possible, but I will hold it off because Vcpkg can retain just single version per package.

This seems not to be possible to fix as long as Vcpkg adopts Git, not an ecosystem like npm, PyPI, or crates, as package management.
