### ISSUE TITLE
[Zydis] Zycore includes not placed correctly

### ISSUE THREAD

**Issue by MathematicalDessert** [microsoft/vcpkg#11191]
**Describe the bug**
Zycore includes not found in the installed directory, leading to build errors when using the Zydis library. See pull request #11173 for fix.

**Environment**
- OS: Windows 10
- Compiler: Visual Studio 2019

**To Reproduce**
1. ./vcpkg install zydis
2. Include Zydis/Zydis.h in any project
3. Attempt to use any types imported from Zycore library (e.g. ZyanUSize)

**Expected behavior**
Zyccore should be installed separately, and have its own include folder.

**Failure logs** 
N/A

**Additional context**
N/A

**Comment by strega-nil** [comment]
Closed by #11173
