### ISSUE TITLE
libiconv port

### ISSUE THREAD

**Issue by ethanhs** [Microsoft/vcpkg#112]
As part of #34, a libiconv port is needed first. Sadly, the GNU folks decided to remove support for MSVC. As I see it, a patch that adds cmake or vcxproj files for the library are needed. There is an issue on the GNU issues which has a VS10 sln, but [there are cmake-ified versions of the latest libiconv](https://github.com/vovythevov/libiconv-cmake), which seem cleaner than using MSVC build files.

**Comment by ras0219-msft** [comment]
Hmm, this is unfortunate. Please take whichever path you find most productive; as a general guideline we'd prefer using the original sources and only the linked repository's CMakeLists.txt/sln to make it easier for others to trust the port.

**Comment by ethanhs** [comment]
>as a general guideline we'd prefer using the original sources and only the linked repository's CMakeLists.txt/sln to make it easier for others to trust the port.

I agree that using the original build system is preferable, but libiconv uses configure and automake, which I don't think can be used with MSVC, so I was thinking we'd ship the original + a patch that adds cmake files to build libiconv.

**Comment by Orvid** [comment]
Might be worth looking at the build setup for some of PHP's dependencies on windows: https://github.com/winlibs/ iconv is included.

**Comment by ethanhs** [comment]
@Orvid I've seen that, and considered it. But it makes more sense to me for use to use a CMake based system, so instead of maintaining 4+ solutions, there is just one cmake file, which can build for whichever VS version you need.

**Comment by ethanhs** [comment]
Since #118 is merged, I am going to close this.
