### ISSUE TITLE
[asmjit] update to the latest commit

### ISSUE THREAD

**Issue by kobalicek** [microsoft/vcpkg#11207]
Library name:
asmjit (https://github.com/asmjit/asmjit)

New version number:
80645e66a8ae85749937bda3b329388c8a76ea4c

The current asmjit in vcpkg is broken as somebody downgraded the version to some old version from 2019, which was called oldstable before it got out of support. This is really unfortunate situation as vcpkg offers asmjit that nobody should use anymore, but previously it offered a newer one, which was supported.

As an author of the library I don't know what to think in this case - I don't think vcpkg is good for projects where master branch is considered "stable" and the project is alive and gets frequent fixes. The problem is, that from somebody who maintains the project, I just don't want to make PRs for every fix that I do - imagine that I would have to fix conan packages, vcpkg packages, and some other packages, for everything that happens in the project. This simply doesn't scale. And if I don't do that, then I get contacted by people that installed asmjit from vcpkg and their version was broken like I just did.

It would be nice if this can be fixed, and also if it would be possible to create vcpkg packages that would not need a specific commit, and where you can say - give me the actual version, which is the current master, or a specific commit.

I mean I really think there should be some automatic or semi-automatic way of updating the package so it can stay actual.

**Comment by timautry** [comment]
@kobalicek - I tend to agree with you.
I have thought for a long time, vcpkg should have progression as follows:
1. production - contains only released stable versions of port/features, no alphas, no betas, no untested
2. quality assurance - contains the next group of stable versions of ports/features, again, no alphas, no betas and no untested
3. and 4 - development and test versions - contains newest latest greatest versions being tested, patches, etc.
- Except for extreme emergencies, the production and quality assurance could be update say quarterly maybe monthly. This would include new changes to vcpkg functionality/features in and of itself and stable finished versions of ports/features.
- The test and development versions could be updated as much as is needed by those adding, updating and/or patching ports/features.

- It has got so where some basic ports which many other ports depend on have been changing several times a week, requiring hours upon hours to completely rebuild the vcpkg instance just to implement, things that should have been caught in a test or development environment before being pushed into the finished version of vcpkg.
- Again my two cents worth, maybe I am too old school, or old fashioned, but as @kobalicek mentions, when you have to maintain your package for multiple package ports, and everyone is wanting the latest greatest and it becomes impossible to meet the needs of the everyone, and many of us are volunteering our spare time on the open source projects to help out.
- It then gets to a point where the volunteers no long want to spend their time supporting the packages as it takes all their waking hours to do so.

**Comment by NancyLi1013** [comment]
Hi @kobalicek 
Thanks for posting this issue.
In fact, we have plans to update these ports to the latest version at regular time.
I noticed that there was no released version for `asmjit `. 
Could you please release a stable version?

@timautry 
Thanks for your suggestions to vcpkg.
In principle, we suggest that using released stable versions for any ports is better way to make sure the quality of ports.
But sometimes, some specific ports need to be updated to the latest commit to fix the urgent issues if there are no released version.

Of course, there are still a lot of work that need us to optimize.

**Comment by kobalicek** [comment]
@NancyLi1013 

> Could you please release a stable version?

Only master branch is considered stable at the moment, you can use date if you need a version string.

**Comment by NancyLi1013** [comment]
`asmjit ` has been updated to the latest commit. Please update vcpkg and rebuild it.
