### ISSUE TITLE
[libepoxy:x64-windows] build failure

### ISSUE THREAD

**Issue by yezifeiafei** [microsoft/vcpkg#11210]
**Environment**
- OS: Windows
- Compiler: Visual Studio Community 2019
- Vcpkg version: 2020.02.04-nohash
- Package: libepoxy:x64-windows

**To Reproduce**
./vcpkg install libepoxy:x64-windows

**Failure logs** 
```
Starting package 1/6: libepoxy:x64-windows
Building package libepoxy[core]:x64-windows...
-- Using cached D:/vcpkg/downloads/anholt-libepoxy-1.5.3.tar.gz
-- Using source at D:/vcpkg/buildtrees/libepoxy/src/1.5.3-d7b9d32fcb
-- Acquiring MSYS Packages...
-- Acquiring MSYS Packages... OK
-- Configuring x64-windows-dbg
-- Configuring x64-windows-dbg done
-- Configuring x64-windows-rel
-- Configuring x64-windows-rel done
-- Package x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: "D:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" install -v
    Working Directory: D:/vcpkg/buildtrees/libepoxy/x64-windows-rel
    Error code: 1
    See logs for more information:
      D:\vcpkg\buildtrees\libepoxy\package-x64-windows-rel-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_meson.cmake:19 (vcpkg_execute_required_process)
  ports/libepoxy/portfile.cmake:16 (vcpkg_install_meson)
  scripts/ports.cmake:90 (include)


Error: Building package libepoxy:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libepoxy:x64-windows
  Vcpkg version: 2020.02.04-nohash
```

**Additional context**
 D:\vcpkg\buildtrees\libepoxy\package-x64-windows-rel-out.log
[config-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/4590429/config-x64-windows-rel-out.log)

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Please provide the error log: `D:\vcpkg\buildtrees\libepoxy\package-x64-windows-rel-out.log`.

**Comment by yezifeiafei** [comment]
> Thanks for posting this issue. Please provide the error log: `D:\vcpkg\buildtrees\libepoxy\package-x64-windows-rel-out.log`.

Sorry, I mixed up `package-x64-windows-rel-out.log` and `config-x64-windows-rel-out.log`.
[package-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/4591490/package-x64-windows-rel-out.log)

**Comment by Voskrese** [comment]
` ../src/1.5.3-d7b9d32fcb/src/dispatch_common.c(1): error C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss`

**Comment by Voskrese** [comment]
`move "D:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja\ninja.EXE" "D:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja\__ninja__.EXE"`

**Comment by Voskrese** [comment]
https://docs.microsoft.com/en-us/cpp/build/reference/utf-8-set-source-and-executable-character-sets-to-utf-8?redirectedfrom=MSDN&view=vs-2019

1. AdditionalOptions, add the `/utf-8` option to specify your preferred encoding
2. chcp 65001

**Comment by yezifeiafei** [comment]
Hi, Voskrese~ Thanks for your reply!
I try [this](https://github.com/microsoft/vcpkg/issues/11210#issuecomment-625139184) and manually remove the non-standard ASCII in `../src/1.5.3-d7b9d32fcb/src/dispatch_common.c`, and this issue is fixed consequently.

But I don't really understand [this](https://github.com/microsoft/vcpkg/issues/11210#issuecomment-625145951). Why do this?

Moreover, if non-standard ASCII characters are too many to remove manually, what should i do?

**Comment by Voskrese** [comment]
https://github.com/microsoft/vcpkg/blob/aa0b9d7ca9e1b98e7bb18538f04dd39e7a41d3ff/scripts/toolchains/windows.cmake#L16

```
    set(CMAKE_CXX_FLAGS " /DWIN32 /D_WINDOWS /W3 ${CHARSET_FLAG} /GR /EHsc /MP ${VCPKG_CXX_FLAGS}" CACHE STRING "")
    set(CMAKE_C_FLAGS " /DWIN32 /D_WINDOWS /W3 ${CHARSET_FLAG} /MP ${VCPKG_C_FLAGS}" CACHE STRING "")
```

add CMAKE_CXX_FLAGS and CMAKE_C_FLAGS "/utf-8"

**Comment by c72578** [comment]
Similar issue: #10382

**Comment by xiaoxi-li** [comment]
Similiar issue:＃11526

**Comment by xiaoxi-li** [comment]
Similiar issue:[https://github.com/microsoft/vcpkg/issues/11526](url)

**Comment by xiaoxi-li** [comment]
Similiar issue:[https://github.com/microsoft/vcpkg/issues/11525](url)

**Comment by LilyWangL** [comment]
The related issue: #11845

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/11525.
