### ISSUE TITLE
[vcpkg/CI] stdout-<triplet>-log does not contain post build failure output of vcpkg.exe

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#11219]
The log only contains the messages printed by the cmake script but is missing the post build failure reasons if it fails due to those.  (like empty directories, cmake files at the wrong location or duplicated files with other ports)

**Comment by BillyONeal** [comment]
As a workaround for now the logs are included if you look in the actual logs for the associated build; Ctrl+F and typing in the name of the port in question should find it.

**Comment by PhoebeHui** [comment]
eg: https://dev.azure.com/vcpkg/public/_build/results?buildId=40222&view=logs&j=a83b7983-e539-5449-9e09-337ff5f52283&t=d09e293f-02da-5f82-8282-c7874dd40062&l=1478
