### ISSUE TITLE
libmysql[core]:x86-windows build failure 

### ISSUE THREAD

**Issue by QwazyWabbitWOS** [microsoft/vcpkg#11214]
**Host Environment**
- OS: Windows 10 on AMD 6300 x86_64
- Compiler: clang version 4.0.0 (trunk)
Target: i686-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files (x86)\LLVM\bin

**To Reproduce**
.\vcpkg.exe install libmysql

**Failure logs** 
Computing installation plan...
The following packages will be built and installed:
    libmysql[core]:x86-windows
Starting package 1/1: libmysql:x86-windows
Building package libmysql[core]:x86-windows...
CMake Error at scripts/cmake/vcpkg_fail_port_install.cmake:93 (message):
  Architecture 'x86' not supported by libmysql!

Call Stack (most recent call first):
  ports/libmysql/portfile.cmake:1 (vcpkg_fail_port_install)
  scripts/ports.cmake:90 (include)

Error: Building package libmysql:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libmysql:x86-windows
  Vcpkg version: 2020.02.04-nohash

-Please attach any additional failure logs mentioned in the console output.

**Additional context**
After first failure, git pull was executed as well as ./vcpkg upgrade, Subsequent install attempt failed.

**Comment by LilyWangL** [comment]
Thanks for posting this issue. The port libmysql doesn't support `x86-windows` triplet.
```
CMake Error at scripts/cmake/vcpkg_fail_port_install.cmake:93 (message):
Architecture 'x86' not supported by libmysql!
```

**Comment by QwazyWabbitWOS** [comment]
Thanks for the prompt reply. I'm a little grieved that it went through the lengthy process of installing boost before deciding the triplet was unsupported. How can I determine in advance what triplets are supported for any package? How is this related to Issue #8334, still open from last year?

**Comment by LilyWangL** [comment]
The [Supports](https://github.com/microsoft/vcpkg/blob/e62d1361288e83eba786395b60361ab35ba83800/docs/maintainers/control-files.md#supports) in CONTROL file of port explain this port doesn't support witch triplet.

**Comment by strega-nil** [comment]
Unfortunately, this isn't a thing we can solve; if you'd like to build libmysql, you'll have to use the x64 version

```
> vcpkg install libmysql:x64-windows
```

**Comment by QwazyWabbitWOS** [comment]
I did that and it was successful. However, I still ended up installing the 64-bit mysql server from Oracle and their development kit for Visual Studio from htttps://dev.mysql.com. Thanks for all the help.
