### ISSUE TITLE
[New Port Request] Compact Encoding Detection

### ISSUE THREAD

**Issue by rsarov** [microsoft/vcpkg#11211]
Library name: CED

Library description: Compact Encoding Detection(CED for short) is a library written in C++ that scans given raw bytes and detect the most likely text encoding.

Source repository URL: https://github.com/google/compact_enc_det

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
