### ISSUE TITLE
Cannot install pdcurses

### ISSUE THREAD

**Issue by hjxkyw** [Microsoft/vcpkg#1121]
C:\tools\vcpkg>.\vcpkg.exe install pdcurses
The following packages will be built and installed:
    pdcurses:x86-windows
Building package pdcurses:x86-windows...
-- CURRENT_INSTALLED_DIR=C:/tools/vcpkg/installed/x86-windows
-- DOWNLOADS=C:/tools/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/tools/vcpkg/packages/pdcurses_x86-windows
-- CURRENT_BUILDTREES_DIR=C:/tools/vcpkg/buildtrees/pdcurses
-- CURRENT_PORT_DIR=C:/tools/vcpkg/ports/pdcurses/.
-- Using cached C:/tools/vcpkg/downloads/pdcurs34.zip
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Build x86-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:14 (message):
    Command failed: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.10.25017/bin/HostX64/x64/nmake.exe;/A;-f;vcpkg.mak;WIDE=Y;UTF8=Y;DLL=Y
    Working Directory: C:/tools/vcpkg/buildtrees/pdcurses/src/win32
    See logs for more information:
      C:\tools\vcpkg\buildtrees\pdcurses\build-x86-windows-rel-out.log
      C:\tools\vcpkg\buildtrees\pdcurses\build-x86-windows-rel-err.log

Call Stack (most recent call first):
  ports/pdcurses/portfile.cmake:27 (vcpkg_execute_required_process)
  scripts/ports.cmake:73 (include)

Error: Building package pdcurses:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: pdcurses:x86-windows
  Vcpkg version: 0.0.81-7b71ac70fe0ce2c23908d5228cde7f7b04b603cc

Additionally, attach any relevant sections from the log files above.

C:\tools\vcpkg>gvim C:\tools\vcpkg\buildtrees\pdcurses\build-x86-windows-rel-out.log

C:\tools\vcpkg>gvim C:\tools\vcpkg\buildtrees\pdcurses\build-x86-windows-rel-err.log

C:\tools\vcpkg>

[logs.zip](https://github.com/Microsoft/vcpkg/files/1016197/logs.zip)

**Comment by ras0219-msft** [comment]
Thanks for reporting this issue!

I believe I have fixed this via 54be2d5, please let me know if you still hit an issue.
