### ISSUE TITLE
global include path evaluate $(VcpkgRoot) to empty

### ISSUE THREAD

**Issue by slavidodo** [microsoft/vcpkg#11212]
**Describe the bug**
when adding $(VckpgRoot) 

**Environment**
- OS: Windows
- Compiler: MSVC 14.25.28610 (2019)

**To Reproduce**
1. ./vcpkg install luajit
2. prefer luajit over lua globally ``<IncludePath>$(VcpkgRoot)include\luajit;$(VC_IncludePath);$(WindowsSDK_IncludePath);</IncludePath>``
3. simple in any cpp file ``#include <lua.hpp>`

**Expected behavior**
The compiler can find lua.hpp in (vcpkg\installed\luajit)

**Notes to avoid confusion**
1. the global include path is actually wrapped with a configuration condition like this:
```xml
<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
  <IncludePath>$(VcpkgRoot)include\luajit;$(VC_IncludePath);$(WindowsSDK_IncludePath);</IncludePath>
</PropertyGroup>
```
2. ``#include <luajit/lua.hpp>`` works fine as expected

**Failure logs** 
```fatal error C1083: Cannot open include file: 'lua.hpp': No such file or directory (compiling source file xx.cpp)```

**Additional context**
Through detailed logging, triplet selection happened after IncludePath was evaluated
the behavior is not the same when using appveyor!

**Comment by Voskrese** [comment]
![2020-05-07_173250](https://user-images.githubusercontent.com/10104740/81278870-dc0ccd80-9088-11ea-9310-2d4fe5e8e0df.png)

**Comment by slavidodo** [comment]
If it's not integrated then <luajit/lua.hpp> wouldn't be working!

I double checked now tho, yeah still the same issue

**Comment by Voskrese** [comment]
full log attach

**Comment by slavidodo** [comment]
There you go [Log.txt](https://github.com/microsoft/vcpkg/files/4594744/Log.txt)

**Comment by Voskrese** [comment]
https://github.com/slavidodo/forgottenserver/blob/6c96facb41f357bfbff5ed59b2542462086d5c13/src/luascript.h#L23

`<IncludePath>$(VcpkgRoot)include\luajit`

search `lua.hpp` ?

**Comment by slavidodo** [comment]
Assuming what you gave works, it's clearly not gonna work as the main issue is that ``$(VcpkgRoot)`` is evaluated to null.

Anyways we did a temporary solution by moving this part to AdditionalIncludeDirectories

**Comment by LilyWangL** [comment]
Due to `$(VcpkgRoot)include\luajit` is added to MSVC manually, so you should use `#include "lua.h"`.

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
