### ISSUE TITLE
[Feature Request] Add command to rebuild all installed ports

### ISSUE THREAD

**Issue by sharpe5** [microsoft/vcpkg#11215]
I'd like to rebuild the existing `vcpkg` directory under a newer version of `gcc`.

I'm wondering - is this possible without manually reinstalling everything from scratch?

Not that it matters, but I'm using `WSL v1` with `Ubuntu 18.04`.

**Comment by sharpe5** [comment]
I've searched everywhere in the documentation, I cannot seem to find any mention of this use case.

The reason I am asking is that I suspect that gcc v9.3.0 has a stability regression with -O3 compared to v9.2.1, and I want to run some tests to verify this.

**Comment by timautry** [comment]
Why not just create a new instance of vcpkg?
- git clone https://github.com/Microsoft/vcpkg.git ./vcpkg-9.3.0
- cd ./vcpkg-9.3.0
- ./bootstrap-vcpkg.sh
- modify the linux triplet to use gcc 9.3.0

I personally have 4 instances, vs2017.prod vs2017.test vs2019.prod and vs2019.test each using the compiler, linker and toolset native to that visual studio version. 

To save some space I did create a common downloads directory so they share the downloaded files, tools, etc.

**Comment by NancyLi1013** [comment]
@sharpe5 
Thanks for posting this issue.

- If you want to rebuild some ports you already installed, you can remove them and then install them again.

- If you want to rebuild vcpkg instance, you can rerun `./bootstrap-vcpkg.sh`.

- Of course, you can clone a new vcpkg as @timautry said above, and then rebuild them.

Please let me know if you still have any concern about this issue.

If there are some problems on` gcc v9.3.0`, please open a new issue to track it.

Thanks.

**Comment by sharpe5** [comment]
@timautry, @NancyLi1013 Thank you for your comments.

It would be fantastic to have a command to rebuild all packages. That way, if the compiler was upgraded (or changed), it would be easy to build everything under the new compiler.

I guess the only solution, for now, is to write some sort of script to remove/install the packages one by one? Not that would be difficult, but it would be a bit hacky.

**Comment by NancyLi1013** [comment]
@strega-nil 
Could you please help comment about this issue?

**Comment by strega-nil** [comment]
I think this is a pretty good idea; if you wanted to add a command to do it @sharpe5, I could probably offer assistance :)

**Comment by sharpe5** [comment]
Thank you for the offer, that is very generous. However I don't think I have enough C++ experience yet to add a command like this.

**Comment by strega-nil** [comment]
Fair enough :)

**Comment by sharpe5** [comment]
Please ignore the title change, the original is correct.
