### ISSUE TITLE
.\bootstrap-vcpkg.bat doesn't work.

### ISSUE THREAD

**Issue by LightningRpper** [microsoft/vcpkg#11222]
I'm trying to run .\bootstrap-vcpkg.bat to stop getting some of my code thinking #include<stdio.h> is an error and it refuses to run. The window shows up for a second and then red text shows up for one millisecond and then disappears. The Ubuntu terminal is also no help because it doesn't show what's wrong. Can someone help me please?

**Comment by timautry** [comment]
On Linux run `./bootstrap-vcpkg.sh`  from the `<vcpkg-root>` directory

FYI: `.\bootstrap-vcpkg.bat` is for Windows

**Comment by LightningRpper** [comment]
@leha-bot I tried running it but it's now giving me an error that VS Code is not installed when it actually is.

**Comment by LightningRpper** [comment]
It says "Could not find Visual Studio. VS2015 or VS2017 (with C++) needs to be installed." but it's actually right there. I have it opened.

**Comment by NancyLi1013** [comment]
Hi @LightningRpper 
Thanks for posting this issue.
Does this issue only exist on Windows or on both Windows and Linux?
Please refer to the similar issue #7903 first.

**Comment by LightningRpper** [comment]
@NancyLi1013 It exists on both. When I use Powershell, cmd, and Ubuntu, it gives me the same error.

**Comment by LightningRpper** [comment]
I just want to do something to get rid of the #include errors, which should not be errors to begin with.

**Comment by NancyLi1013** [comment]
Could you please post the detail error info?

**Comment by NancyLi1013** [comment]
@LightningRpper 
Could you please provide the full build log?

**Comment by linquize** [comment]
Could you run
`"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -prerelease -legacy -products * -format xml`
and post the content here?

**Comment by PhoebeHui** [comment]
Related to https://github.com/microsoft/vcpkg/issues/7903

**Comment by narasimhan11102** [comment]
When I try to run the bootstrap command in cmd I get an error stating that VS has not been installed, but I have already installed VS CODE earlier
image
Can u please help me resolve this issue!
![image](https://user-images.githubusercontent.com/76741184/103305319-d3f70900-4a30-11eb-92b1-999698dbf401.png)

**Comment by NancyLi1013** [comment]
@narasimhan11102 

Currently, vcpkg only supports Visual Studio. So you need to install Visual Studio instead of Visual Studio Code.

Also we recommend to use powershell instead of cmd to build vcpkg.

So could you please install Visual Studio with English package to try this again?

**Comment by narasimhan11102** [comment]
> @narasimhan11102
> 
> Currently, vcpkg only supports Visual Studio. So you need to install Visual Studio instead of Visual Studio Code.
> 
> Also we recommend to use powershell instead of cmd to build vcpkg.
> 
> So could you please install Visual Studio with English package to try this again?

But then how do I get the libraries for visual studio code ?

**Comment by Sonikyara** [comment]
Ошибка при попытке  ./bootstrap-vcpkg.bat

Не удается найти свойство "instance" для этого объекта. Убедитесь, что оно существует.
C:\Users\Professional\td\vcpkg\scripts\bootstrap.ps1:78 знак:31
+         foreach ($instance in $asXml.instances.instance)
+                               ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict

**Comment by NancyLi1013** [comment]
vcpkg doesn't support visual studio code. So you cannot use the libraries installed by vcpkg with visual studio code.

**Comment by Nicolas-Constanty** [comment]
Hello @NancyLi1013,
I just got some struggle with bootstrap-vcpkg.bat on [AppVeyor](https://www.appveyor.com/), calling it caused my build pipeline to fail. 
I tried to explain in detail how to reproduce it, and how I "fixed" it.

## How to reproduce it :
* Create a repository
* Add vcpkg as a submodule to your repository
```
git submodule add https://github.com/microsoft/vcpkg.git vcpkg
```
* Create dependency.bat with this content:
```
cd vcpkg
.\bootstrap-vcpkg.bat -disableMetrics
.\vcpkg.exe update
.\vcpkg.exe install cgal:x64-windows
.\vcpkg.exe install boost-uuid:x64-windows
```
 * Create appveyor.yml with this content:
```
image:
 - Visual Studio 2019

platform:
  - x64

configuration:
  - Release

clone_script:
  - cmd: git clone -q --recursive -j8 --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
  - cmd: git checkout -qf %APPVEYOR_REPO_COMMIT%

before_build:
  - cmd: dependency.bat
```

## How I fix it
I just replaced this line from the dependency.bat
```
.\bootstrap-vcpkg.bat -disableMetrics
```
by
```
cmd /c .\bootstrap-vcpkg.bat -disableMetrics
```

I assumed that calling it from a sub cmd shell whould cause a crash only on the sub cmd shell and not the main one.
That is working well for me, but I think there is something wrong with the exit of bootstrap-vcpkg.bat.

## Here is what happen when it fail
![image](https://user-images.githubusercontent.com/9875531/107768175-5a904d00-6d36-11eb-8ec9-54f77d4aff16.png)
The red line represente where my dependency script fail, and since it exit before installing any of my dependencies the pipeline fail just after on another step.

**Comment by NancyLi1013** [comment]
Please feel free to reopen this issue if it is still a problem for you.

**Comment by Ghalif** [comment]
Hello. I am getting this Error when I used the command "./bootstrap-vcpkg.bat". How can I resolve this?

```
PS C:\Windows\system32\OpenSfM\vcpkg> ./bootstrap-vcpkg.bat
Downloading https://github.com/microsoft/vcpkg-tool/releases/download/2022-05-05/vcpkg.exe -> C:\Windows\System32\OpenSfM\vcpkg\vcpkg.exeWhile calling Windows API function CreateFileW got error 0x00000003:
The system cannot find the path specified.

C:\Windows\System32\OpenSfM\vcpkg\scripts\bootstrap.ps1 : Downloading vcpkg.exe failed. Please check your internet
connection, or consider downloading a recent vcpkg.exe from https://github.com/microsoft/vcpkg-tool with a browser.
At line:1 char:4
+ & {& 'C:\Windows\System32\OpenSfM\vcpkg\scripts\bootstrap.ps1' }
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,bootstrap.ps1

ScriptHalted
At C:\Windows\System32\OpenSfM\vcpkg\scripts\bootstrap.ps1:60 char:5
+     throw
+     ~~~~~
    + CategoryInfo          : OperationStopped: (:) [], RuntimeException
    + FullyQualifiedErrorId : ScriptHalted
```

Can someone help me resolve this problem? Thank you.
