### ISSUE TITLE
[qt5-base] build failure

### ISSUE THREAD

**Issue by panter-dsd** [microsoft/vcpkg#11227]
**Host Environment**
- OS: Linux
- Compiler: gcc (Arch Linux 9.3.0-1) 9.3.0

**To Reproduce**
`./vcpkg install qt5-base`

**Failure logs** 
`/home/panter/install/vcpkg/buildtrees/qt5-base/x64-linux-dbg/bin/rcc: error while loading shared libraries: libbz2d.so.1.0: cannot open shared object file: No such file or directory
/home/panter/install/vcpkg/buildtrees/qt5-base/x64-linux-dbg/bin/qfloat16-tables: error while loading shared libraries: libbz2d.so.1.0: cannot open shared object file: No such file or directory
`
[build-x64-linux-dbg-err.log](https://github.com/microsoft/vcpkg/files/4595189/build-x64-linux-dbg-err.log)
[build-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/4595191/build-x64-linux-dbg-out.log)

**Additional info**
x64-linux.cmake
```
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)

set(VCPKG_CMAKE_SYSTEM_NAME Linux)
```

**Comment by panter-dsd** [comment]
`set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)

set(VCPKG_CMAKE_SYSTEM_NAME Linux)
`

**Comment by Neumann-A** [comment]
please add the `configure-<xxx>.logs` I might also need the config.log from `buildtrees/qt5-base/x64-linux-dbg` to analyse the error

**Comment by panter-dsd** [comment]
Config files: 
[config-x64-linux-dbg-err.log](https://github.com/microsoft/vcpkg/files/4595388/config-x64-linux-dbg-err.log)
[config-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/4595389/config-x64-linux-dbg-out.log)
[config-x64-linux-rel-err.log](https://github.com/microsoft/vcpkg/files/4595390/config-x64-linux-rel-err.log)
[config-x64-linux-rel-out.log](https://github.com/microsoft/vcpkg/files/4595392/config-x64-linux-rel-out.log)

**Comment by panter-dsd** [comment]
[config.log](https://github.com/microsoft/vcpkg/files/4595396/config.log)

**Comment by Neumann-A** [comment]
Sry don't know enough about Linux compilers here to know why rcc appends `.1.0` to the library. From the logs I couldn't find any reference to `libbz2d.so.1.0` only `libbz2d.so`. You could symlink `libbz2d.so` to `libbz2d.so.1.0` to solve the error and do the same for the release versions.

**Comment by panter-dsd** [comment]
```
> find ~/install/vcpkg -name "libbz2d.so*"
/home/xxx/install/vcpkg/packages/bzip2_x64-linux/debug/lib/libbz2d.so
/home/xxx/install/vcpkg/packages/bzip2_x64-linux/debug/lib/libbz2d.so.1.0.6
/home/xxx/install/vcpkg/packages/bzip2_x64-linux/debug/lib/libbz2d.so.1.0
/home/xxx/install/vcpkg/installed/x64-linux/debug/lib/libbz2d.so
/home/xxx/install/vcpkg/installed/x64-linux/debug/lib/libbz2d.so.1.0.6
/home/xxx/install/vcpkg/installed/x64-linux/debug/lib/libbz2d.so.1.0
/home/xxx/install/vcpkg/buildtrees/bzip2/x64-linux-dbg/libbz2d.so
/home/xxx/install/vcpkg/buildtrees/bzip2/x64-linux-dbg/libbz2d.so.1.0.6
/home/xxx/install/vcpkg/buildtrees/bzip2/x64-linux-dbg/libbz2d.so.1.0
```

I have libbz2d.so.1.0

**Comment by Neumann-A** [comment]
hmm is LD_LIBRARY_PATH set in your environment? Or we need to check RPATH settings in those executables.

**Comment by panter-dsd** [comment]
If I right understand, vcpkg should set LD_LIBRARY_PATH by itself. It's weird but I successfully built this library approximately 8 hours before....

**Comment by JackBoosY** [comment]
@strega-nil  Could you please take a look?

Thanks.

**Comment by hellozee** [comment]
Okay, it could be reproduced with dynamic builds only, static ones don't seem to be affected

**Comment by Neumann-A** [comment]
Yeah static builds don't try to find dynamic dependencies at runtime ;) The problem is the dynamic linker does not know where to search for the required library.

**Comment by hellozee** [comment]
Okay now qt5-imageformats won't build, 
[config-x64-linux-rel-rel-err.log](https://github.com/microsoft/vcpkg/files/4769493/config-x64-linux-rel-rel-err.log)

**Comment by Neumann-A** [comment]
Interesting never encountered that problem. You can just add it into the `TIFF_LIBS` for `OPT_REL` and `OPT_DBG` in the portfile

**Comment by hellozee** [comment]
Okay new issue, qt5-base now ends up with broken cmake configs, where all the configs end up having,
```
_qt5_<submodule>_parse_prl(TARGET Qt5::<submodule> LIB_FILE "${imported_implib}" CONFIGURATION "${Configuration}" OUT_DEPS PRL_DEPS OUT_FLAGS PRL_FLAGS)
```
where `imported_implib` is an unknown variable, though switching that too `imported_location` manually fixes this.

**Comment by Neumann-A** [comment]
hmm is this 5.12.8 or 5.14?

**Comment by hellozee** [comment]
5.12.8

**Comment by Neumann-A** [comment]
Should not happend with 5.14. The PRL parser is just backported to 5.12.8 in vcpkg and probably only works correct with the tested triplets.

**Comment by JackBoosY** [comment]
Hi everyone, since qt has been updated to 5.15, does this issue exists?

**Comment by hellozee** [comment]
welp, this is still a problem, 😭

**Comment by Bardo91** [comment]
> welp, this is still a problem, sob

Hi, I encoutered same problem with fontconfig, this may help https://github.com/microsoft/vcpkg/discussions/19127#discussioncomment-1049627 to you

**Comment by JonLiu1993** [comment]
Hi everyone, since qt has been updated to 5.15.7, I can successfully install qt5-base in my local machine, does this issue exists?
````
PS F:\test\vcpkg> ./vcpkg install qt5-base --editable
Computing installation plan...
The following packages are already installed:
    qt5-base[core]:x86-windows -> 5.15.7#2
qt5-base:x86-windows is already installed
Restored 0 package(s) from C:\Users\vzhli17\AppData\Local\vcpkg\archives in 188.7 us. Use --debug to see more details.
Total elapsed time: 203.1 ms
````

**Comment by FrankXie05** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.
This issue hasn’t been updated in a year; if it is still an issue, please reopen it.
