### ISSUE TITLE
[New Port Request] bitserializer-pugixml

### ISSUE THREAD

**Issue by PavelKisliak** [microsoft/vcpkg#11243]
Library name: bitserializer-pugixml

Library description: Sub-module of BitSerializer for support serialization to XML

Source repository URL: https://bitbucket.org/Pavel_Kisliak/bitserializer

Number of PR:  #11241
Please merge after #11160 (with updates of core library).

**Comment by LilyWangL** [comment]
Thanks for posting this issue. This port has been added to VCPKG, you can update VCPKG and install it.
