### ISSUE TITLE
[fribidi] Fribidi doesn't cross-compile on x86-64 to target arm/arm64

### ISSUE THREAD

**Issue by janisozaur** [microsoft/vcpkg#11248]
****

**Is your feature request related to a problem? Please describe.**
`./vcpkg.exe install fribidi:arm64-windows` fails due to invalid assumptions in the port's build system, meson. Possible upstream issue: https://github.com/mesonbuild/meson/issues/4402

**Additional context**
meson output:
`ERROR: Could not invoke sanity test executable: [WinError 216] This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.`

I have not checked how other meson-based ports handle cross-compilation.

**Comment by traversaro** [comment]
Related issue: https://github.com/microsoft/vcpkg/issues/11230 .

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/11230
