### ISSUE TITLE
[New Port Request] Guile

### ISSUE THREAD

**Issue by kayarre** [microsoft/vcpkg#11252]
Library name: Guile 

Library description: Guile is a programming language. Guile is designed to help programmers create flexible applications that can be extended by users or other programmers with plug-ins, modules, or scripts.  With Guile you can create applications and games for the desktop, the Web, the command-line, and more.

Source repository URL: https://git.savannah.gnu.org/git/guile.git

Project homepage (if different from the source repository): https://www.gnu.org/software/guile/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
