### ISSUE TITLE
Problem with g2o

### ISSUE THREAD

**Issue by RollingIsland** [microsoft/vcpkg#11251]
**Describe the bug**
I'm trying to compile [ORB_SLAM2](https://github.com/raulmur/ORB_SLAM2), which need the **g2o** package. I successfully installed g2o by using vcpkg without any problem. However when I tried to compile ORB_SLAM2 there is something wrong in linking:
![QHLRA7%JPBQZ0OD}Z5`NE49](https://user-images.githubusercontent.com/36465854/81428261-9d613b00-918e-11ea-8a8d-d212bb72a843.png)
Well, as linking should be automatically done, this is quite strange.
Is there any thing wrong with the package? or the link function of vcpkg? It will be great help if this can be solved.

**Environment**
- OS: Windows
- Compiler: VS2017

**Comment by NancyLi1013** [comment]
Hi @RollingIsland 
Thanks for posting this issue.

I noticed that `orb-slam2` used the internal `g2o` to build.
https://github.com/raulmur/ORB_SLAM2/blob/master/CMakeLists.txt#L73-L78
The source code for `g2o `is listed here.
https://github.com/raulmur/ORB_SLAM2/tree/master/Thirdparty/g2o

So if you want to use `g2o ` provided in vcpkg, you should add the usage to CMakeLists.txt and remove the g2o in thirdparty.

```
    find_package(g2o CONFIG REQUIRED)
    target_link_libraries(main PRIVATE g2o::core g2o::stuff g2o::types_icp g2o::types_sba)
```

Could you please update it and then try it again?

**Comment by RollingIsland** [comment]
@NancyLi1013 , Thanks for your quick apply. 
Actually I create a new empty VS project to compile `orb_slam2`. I installed all the required thirdparty packages by vcpkg, and the source files & the header files were added manually. 
In case that the CMakeLists.txt cause any problem, I just delete it and try again, but seems no help.

**Comment by NancyLi1013** [comment]
Thanks for your reply. I will try to use `g2o `on my local machine and confirm if it can work well.

**Comment by NancyLi1013** [comment]
Hi @RollingIsland 
Sorry for the late reply.
I create a simple CMake project and try to use `g2o` and it can build successfully on my local. 
This is my CMakeLists.txt:
```
cmake_minimum_required (VERSION 3.8)
find_package(g2o CONFIG REQUIRED)
# Add source to this project's executable.
add_executable (CMakeG2o "CMakeG2o.cpp" "CMakeG2o.h")
target_link_libraries(CMakeG2o PRIVATE g2o::core g2o::stuff g2o::types_icp g2o::types_sba)
```

So it might be something wrong to `g2o`  in `ORB_SLAM2`.  It should be a problem in `ORB_SLAM2` instead of `g2o`.

**Comment by NancyLi1013** [comment]
I'm closing this issue for now since it seems to be solved on my side.
Please try to do some changes for `ORB_SLAM2 ` to rebuild it.
