### ISSUE TITLE
[eastl] Compiling solution fails with "EABase/eabase.h not found"

### ISSUE THREAD

**Issue by Nelarius** [microsoft/vcpkg#11262]
**Describe the bug**
Installing `eastl` also installs the `eabase` dependency. But including any `eastl` headers leads to a compilation failure, because `eastl`'s internal includes are are of the form `#include <EABase/eabase.h>`, and the `eabase` package places the headers into `include/Common/EABase/**.h`.

**Environment**
- OS: Windows 10
- Compiler: Visual Studio Community 2019 Version 16.5.4

**To Reproduce**
1. ./vcpkg install eastl
2. Create a new Console App project in Visual Studio.
3. Add `#include <EASTL/vector.h>` and compile
4. The build will fail with
```
1>eastl-repro.cpp
1>C:\Users\nelarius\vcpkg\installed\x86-windows\include\EASTL\internal\config.h(61,11): fatal error C1083: Cannot open include file: 'EABase/eabase.h': No such file or directory
```

**Expected behavior**
I would expect that the solution should work without manually specifying the inclusion path, just like the other packages I installed. EABase's CMake install seems to export the correct include path `include/Common`, but I was under the impression that you don't have to use CMake with `vcpkg` to generate your solution files 🤔 

**Additional context**
EABase's folder structure seems to be a recurring theme with the project, see for instance https://github.com/electronicarts/EASTL/issues/320.

**Comment by PhoebeHui** [comment]
@Nelarius, thanks for reporting this issue!

I think the changes should be updated in Upstream, eabase install its headers to ./include/Common, so the port(eg: eastl) which depends on eabase would find the headers under ./include/Common, if we changes the path, all these ports affect.

**Comment by PhoebeHui** [comment]
Please report to upstream instead, reopen this issue if you still expect vcpkg do something here.

**Comment by xgalaxy** [comment]
I think this ticket should be reopened. Its the ports patch file that is causing the EABase headers to be installed into the incorrect location. This doesn't seem like an upstream issue to me.
