### ISSUE TITLE
Windows static build -  post-build validation invalid crt linkage

### ISSUE THREAD

**Issue by simogasp** [microsoft/vcpkg#11271]
Hi,
I'm creating the port for popsift (#10979), a library for feature detection in computer vision.
Normally the library is cross-platform so as now there have been no issues on bulding/execution on the 3 platforms outside vcpkg.
The library only depends on CUDA.
I have a bit of a issue when building the static version under windows on vcpkg as I always receive this error at the post-build validation (building has no issue)
```
Expected Debug,Static crt linkage, but the following libs had invalid crt linkage:

    C:/alicevision/vcpkg/packages/popsift_x64-windows-static/debug/lib/popsiftd.lib: Release,Static

To inspect the lib files, use:
    dumpbin.exe /directives mylibfile.lib
```
So if I do the `dumpbin` I get something like:
```
File Type: LIBRARY

   Linker Directives
   -----------------
   /FAILIFMISMATCH:_MSC_VER=1900
   /FAILIFMISMATCH:_ITERATOR_DEBUG_LEVEL=2
   /FAILIFMISMATCH:RuntimeLibrary=MTd_StaticDebug
   /DEFAULTLIB:libcpmtd
   /FAILIFMISMATCH:_CRT_STDIO_ISO_WIDE_SPECIFIERS=0
   /FAILIFMISMATCH:_PPLTASK_ASYNC_LOGGING=1
   /FAILIFMISMATCH:ppltask_saved_frame_numbers=PPL_TASK_SAVE_FRAME_COUNT
   /include:?id@?$num_put@DV?$ostreambuf_iterator@DU?$char_traits@D@std@@@std@@@std@@2V0locale@2@A
   /include:?id@?$numpunct@D@std@@2V0locale@2@A
   /DEFAULTLIB:LIBCMTD
   /DEFAULTLIB:OLDNAMES

   Linker Directives
   -----------------
   /DEFAULTLIB:LIBCMT                                       # <-- this one makes the post-build fail
   /DEFAULTLIB:OLDNAMES                   

   Linker Directives
   -----------------
   /FAILIFMISMATCH:_MSC_VER=1900
   /FAILIFMISMATCH:_ITERATOR_DEBUG_LEVEL=2
   /FAILIFMISMATCH:RuntimeLibrary=MTd_StaticDebug
   /DEFAULTLIB:libcpmtd
   /FAILIFMISMATCH:_CRT_STDIO_ISO_WIDE_SPECIFIERS=0
   /include:?id@?$num_put@DV?$ostreambuf_iterator@DU?$char_traits@D@std@@@std@@@std@@2V0locale@2@A
   /include:?id@?$numpunct@D@std@@2V0locale@2@A
   /DEFAULTLIB:LIBCMTD
   /DEFAULTLIB:OLDNAMES

   Linker Directives
   -----------------
   /FAILIFMISMATCH:_MSC_VER=1900
   /FAILIFMISMATCH:_ITERATOR_DEBUG_LEVEL=2
   /FAILIFMISMATCH:RuntimeLibrary=MTd_StaticDebug
   /DEFAULTLIB:libcpmtd
   /FAILIFMISMATCH:_CRT_STDIO_ISO_WIDE_SPECIFIERS=0
   /include:?id@?$num_put@DV?$ostreambuf_iterator@DU?$char_traits@D@std@@@std@@@std@@2V0locale@2@A
   /include:?id@?$numpunct@D@std@@2V0locale@2@A
   /DEFAULTLIB:LIBCMTD
   /DEFAULTLIB:OLDNAMES
...
```
All the remaining ` /DEFAULTLIB` correctly point to `LIBCMTD`, only the second one (see above) points to the non debug version of the lib `LIBCMT`, which is making the test fail.

I've tried several things to fix this without success:

* I made sure that all flags /MT and /MTd were correctly set. In the ninja build file I have
```
  LANGUAGE_COMPILE_FLAGS = /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MTd /Z7 /Ob0 /Od /RTC1
  LINK_FLAGS = /machine:x64  /VERBOSE:LIB
```
Compared to other ports that pass the post-build there is basically no difference in terms of flags

* I tried to add `/NODEFAULTLIB:libcmt.lib` but I got the same result.

The weird thing is that if I create the visual studio solution through cmake and build in VS I got a lib that is correct, ie no `libcmt.lib` in the dumpbin. And again there is no difference in terms of flags.
So you can understand why this thing is driving me crazy.

I'm not an expert in windows build, so it is possible that I'm missing something.
Any help would be really appreciated!

**Comment by simogasp** [comment]
Ok I might have found the problem.
Since nvcc is involved, there is a intermediate linking step in which all the cuda objs are collected into a popsift_intermediate_link.obj.
While all the objs from the cuda files had the proper flags and the correct libcmtd, the intermediate file had the libcmt, which in the end made the post build check fail.
Now, the intermediate linking step is run through a batch file in which nvcc is called without the proper flag.
So in the end the problem is that the flags were not properly propagate in this intermediate step.

To overcome this I added in our code 
```
if(MSVC)
  if(BUILD_SHARED_LIBS)
    if(CMAKE_BUILD_TYPE STREQUAL "Debug")
      set(PopSift_MVSC_LINKER "/MDd")
    else()
      set(PopSift_MVSC_LINKER "/MD")
    endif()
  else()
    if(CMAKE_BUILD_TYPE STREQUAL "Debug")
      set(PopSift_MVSC_LINKER "/MTd")
    else()
      set(PopSift_MVSC_LINKER "/MT")
    endif()
  endif()
  list(APPEND CUDA_NVCC_FLAGS   -Xcompiler ${PopSift_MVSC_LINKER})
endif()
```
which is ugly and probably has the side effect of duplicating the flag in the same command line.
But at least it works.

I cannot understand whose fault it is, there are too many layers, CMake, vcpkg, ninja... I don't know which one does not correctly propagate the flag.
**Probably** it is ninja, because I tried to generate the ninja project from cmake (outside vcpkg) and even there is a .bat file for the intermediate step and it has not the flags.

**Comment by JackBoosY** [comment]
vcpkg will set different `C_FLAGS` / `CXX_FLAGS` according to the triplet and pass it to cmake. If the value is changed in `CMakeLists.txt` or `*.cmake` in the source, `MT` / `MTD` / `MD` / `MDD` may be overwritten. This can be seen in _buildtrees/$PORT/install*.log_. 
So I think this issue should be fixed by adding patches, not vcpkg.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

**Comment by MacNic** [comment]
Hi,

I faced this issued also on a libraries using both C++ and CUDA and I stumbled on this issue from CMake : https://gitlab.kitware.com/cmake/cmake/-/merge_requests/3485

According to this post the issue was due to the way CMake treats MSVC runtime by default (going for /MD or /MDd).

Thus as vcpkg seems to update C_FLAGS and CXX_FLAGS to /MT in case x64-windows-static is used, it seems to leaves CUDA_FLAGS to default (/MD) which results in the aforementioned issued (invalid crt linkage).

Hacking with the flags as proposed by @simogasp did not work for me, so the solution I found was to use the CMake policy [CMP0091](https://cmake.org/cmake/help/latest/policy/CMP0091.html) and to populate the variable [CMAKE_MSVC_RUNTIME_LIBRARY](https://cmake.org/cmake/help/latest/variable/CMAKE_MSVC_RUNTIME_LIBRARY.html) before creating the targets.

For reference, here is the code snippet I used

````
cmake_minimum_required(VERSION 3.15)

# Activate usage of CMAKE_MSVC_RUNTIME_LIBRARY
cmake_policy(SET CMP0091 NEW)

project(whatever)

# Make sure MSVC runtime is consistent accross
# all languages (i.e. CXX, CUDA, etc, ...)
# cfr : https://gitlab.kitware.com/cmake/cmake/-/issues/19428
if(NOT DEFINED CMAKE_MSVC_RUNTIME_LIBRARY)
  if(BUILD_SHARED_LIBS)
    set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>DLL")
  else()
    set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
  endif()
endif()

**Comment by JackBoosY** [comment]
Please note that the CRT linkage of all ports in vcpkg should be configured according to the configuration of the triplet, and should not be mandatory.
