### ISSUE TITLE
bootstrap-vcpkg.sh -disableMetrics flag not passed to bootstrap-vcpkg.bat

### ISSUE THREAD

**Issue by linquize** [microsoft/vcpkg#11274]
On Windows, calling `bootstrap-vcpkg.sh` will redirect to `bootstrap-vcpkg.bat`.
However, `-disableMetrics` flag is not passed to `bootstrap-vcpkg.bat`

**Comment by strega-nil** [comment]
Oops! Lemme fix it right now.
