### ISSUE TITLE
[New Port Request] bgfx

### ISSUE THREAD

**Issue by chronos38** [microsoft/vcpkg#11289]
Library name: bgfx

Library description: Cross-platform, graphics API agnostic, "Bring Your Own Engine/Framework" style rendering library.

Source repository URL: https://github.com/bkaradzic/bgfx

Project homepage (if different from the source repository): https://bkaradzic.github.io/bgfx/overview.html

Anything else that is useful to know when adding (such as optional features the library may have that should be included): Relies on two other repositories from the same author, https://github.com/bkaradzic/bimg and https://github.com/bkaradzic/bx

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
