### ISSUE TITLE
Building a DLL with statically linked dependency doesn't work

### ISSUE THREAD

**Issue by lpintes** [microsoft/vcpkg#11284]
I just discovered vcpkg. It is very exciting except that ... it doesn't work for me.
I want to build a DLL with CURL as a dependency. So i installed the following:
./vcpkg install curl:x86-windows-static

This was successful. I then created a new DLL project in VS 2019, included curl/curl.h in DllMain.cpp and obtained "include file cannot be found" error.

Somehow I expected that it could "just work".

**Comment by linquize** [comment]
You need either `vcpkg integrate install` for system-wide integration,
or set **Additional Include Directories** to `C:\vcpkg\installed\x86-windows-static` on per-project basis.

**Comment by NancyLi1013** [comment]
Hi @lpintes 
Thanks for posting this issue.

Could you please follow the above suggestions and then try to build it again?

Please provide your project case if there are still some problems for this.

**Comment by lpintes** [comment]
Hello,
I did integrate install. It works fine when I built the port as DLL, includes were found automatically.

But when I build curl:x86-windows-static, it didn't work. I even tried to remove curl and install only the x86-windows-static, but also that didn't help.

**Comment by NancyLi1013** [comment]
@lpintes 
Could you please post the detail errors?

**Comment by lpintes** [comment]
Hello,
I will try to describe thesituation once more.
So one day I just discovered vcpkg. Good because I needed to do something with curl.

So I cloned the repo, bootstrapped, made vcpkg integrate, installed curl.
I then created a project, tested that #include <curl/curl.h> just magically works.

Then I thought that maybe it would be better to just have one static binary and wondered if that's is possible, so:

vcpkg remove curl
vcpkg install curl:x86-windows-static

And now the #include didn't work. There were no errors, except that I was not able to use the library like in the first case "vcpkg install curl".

**Comment by NancyLi1013** [comment]
@lpintes 
Sorry for the late response.

For the static build, we need to add the triplet to the project.
```
<PropertyGroup Label="Globals">
 <!-- .... -->
 <VcpkgTriplet Condition="'$(Platform)'=='Win32'">x86-windows-static</VcpkgTriplet>
 <VcpkgTriplet Condition="'$(Platform)'=='x64'">x64-windows-static</VcpkgTriplet>
</PropertyGroup>
```
Please refer to this `doc` to learn more about this.

**Comment by NancyLi1013** [comment]
I'm closing this issue for now. Please do as the above guidelines first and rebuild this.
Please feel free to reopen this issue if it is still a problem for you.
