### ISSUE TITLE
[skia] build failure

### ISSUE THREAD

**Issue by sotex** [microsoft/vcpkg#11285]
**Host Environment**
- OS: Windows 10
- Compiler: Visual Studio 2019

**To Reproduce**
`./vcpkg install skia`

**Failure logs** 
```bash
PS D:\vcpkg> .\vcpkg.exe install skia
Computing installation plan...
The following packages will be built and installed:
    skia[core]:x64-windows
Starting package 1/1: skia:x64-windows
Building package skia[core]:x64-windows...
-- Using cached D:/vcpkg/downloads/skia-05676f7bc238f667de848dfd37b4aa3c01b69efb.tar.gz
-- Using source at D:/vcpkg/buildtrees/skia/src/3c01b69efb-0a98da8354
-- Syncing git dependencies...
-- Generating build (debug)...
-- Generating build (release)...
-- Building Skia (debug)...
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -C D:/vcpkg/buildtrees/skia/x64-windows-dbg skia
    Working Directory: D:/vcpkg/buildtrees/skia/src/3c01b69efb-0a98da8354
    See logs for more information:
      D:\vcpkg\buildtrees\skia\build-x64-windows-dbg-out.log
      D:\vcpkg\buildtrees\skia\build-x64-windows-dbg-err.log

Call Stack (most recent call first):
  ports/skia/portfile.cmake:107 (vcpkg_execute_build_process)
  scripts/ports.cmake:90 (include)


Error: Building package skia:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: skia:x64-windows
  Vcpkg version: 2020.02.04-nohash

Additionally, attach any relevant sections from the log files above.
```

**Additional context**

**build-x64-windows-dbg-err.log**
```bash
ninja: error: '../src/3c01b69efb-0a98da8354/third_party/externals/icu/common/icudtl.dat', needed by 'icudtl.dat', missing and no known rule to make it
```
I really don't have this file here
![图片](https://user-images.githubusercontent.com/16911453/81498028-0ebafe00-92f5-11ea-8e2e-1069aba38a9b.png)

**Comment by JackBoosY** [comment]
Hi @sotex, thanks for reporting this issue.
Could you provide full log _D:\vcpkg\buildtrees\skia\build-x64-windows-dbg-out.log_ and _D:\vcpkg\buildtrees\skia\build-x64-windows-dbg-err.log_?

Thanks.

**Comment by sotex** [comment]
@JackBoosY Sorry, I only reply to you today.

**build-x64-windows-dbg-out.log**
```log
ninja: Entering directory `D:/vcpkg/buildtrees/skia/x64-windows-dbg'

```

**build-x64-windows-dbg-err.log**
```log
ninja: error: '../src/3c01b69efb-0a98da8354/third_party/externals/icu/common/icudtl.dat', needed by 'icudtl.dat', missing and no known rule to make it

```

**Comment by vejmartin** [comment]
@sotex, do you have access to https://chromium.googlesource.com? To my surprise, there appear to be issues with that url from China.
This has also been reported in the following issues:
* https://bugs.chromium.org/p/chromium/issues/detail?id=411187
* https://github.com/google/shaka-packager/issues/597
* https://github.com/microsoft/onnxruntime/issues/1775

The error's indicating that the `icu` dependency is failing, which can be disabled by adding
```
skia_use_icu = false
```
to `D:\vcpkg\buildtrees\skia\x64-windows-dbg\args.gn` and `D:\vcpkg\buildtrees\skia\x64-windows-rel\args.gn`. However, I would expect there to be other failing dependencies as well.

@JackBoosY, I'll look into replacing these dependencies in the Skia port with ones from vcpkg (as was done for the `Crashpad` port), which should hopefully fix this issue.

**Comment by sotex** [comment]
@vejmartin You are right, we cannot access **googlesource.com** . I will try again as you said, thank you very much.

**Comment by fawdlstty** [comment]
I'm having the same problem and can't access skia.googlesource.com. I wonder if there is any other way to solve it?

**Comment by JackBoosY** [comment]
@fawdlstty  May be you need a proxy.

**Comment by fawdlstty** [comment]
Yes, I have try to use, but the results are very poor, I still can't install Skia 😢
