### ISSUE TITLE
[gsoap] Error: Building package gsoap:x64-windows-static failed

### ISSUE THREAD

**Issue by tom2068** [microsoft/vcpkg#11298]
Package: gsoap:x64-windows-static
Vcpkg version: 2020.02.04-nohash

CMake Error at scripts/cmake/vcpkg_fail_port_install.cmake:93 (message):
  Architecture 'x64' not supported by gsoap!

Call Stack (most recent call first):
  ports/gsoap/portfile.cmake:1 (vcpkg_fail_port_install)
  scripts/ports.cmake:90 (include)

**Comment by NancyLi1013** [comment]
Hi @tom2068 
Thanks for posting this issue.
Since `gsoap `only supports x86. The current behavior is intended.

**Comment by NancyLi1013** [comment]
`gsoap `has been updated to 2.8.102 and has added the support for x64 via PR #11355.
Please update vcpkg and try to rebuild this port.
