### ISSUE TITLE
Error: Building package libjpeg-turbo:x86-uwp failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by rdikshit** [microsoft/vcpkg#11296]
**Host Environment**
- OS: [Windows 10]

**To Reproduce**
```
C:\sv\vcpkg>.\vcpkg install opencv[contrib]:x86-uwp --recurse
Computing installation plan...
Warning: qualifier has changed meaning recently:
   windows
The following packages will be built and installed:
  * libjpeg-turbo[core]:x86-uwp
  * liblzma[core]:x86-uwp
  * libpng[core]:x86-uwp
  * libwebp[core,nearlossless,simd,unicode]:x86-uwp
    opencv[contrib,core,dnn,jpeg,opengl,png,tiff,webp]:x86-uwp
  * opencv4[contrib,core,dnn,jpeg,opengl,png,tiff,webp]:x86-uwp
  * opengl[core]:x86-uwp
  * protobuf[core]:x86-uwp
  * tiff[core]:x86-uwp
  * zlib[core]:x86-uwp
Additional packages (*) will be modified to complete this operation.
Starting package 1/10: libjpeg-turbo:x86-uwp
Building package libjpeg-turbo[core]:x86-uwp...
-- Using community triplet x86-uwp. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: C:\sv\vcpkg\triplets\community\x86-uwp.cmake
-- Using cached C:/sv/vcpkg/downloads/libjpeg-turbo-libjpeg-turbo-166e34213e4f4e2363ce058a7bcc69fd03e38b76.tar.gz
-- Using source at C:/sv/vcpkg/buildtrees/libjpeg-turbo/src/fd03e38b76-a5b0f5fafe
-- Configuring x86-uwp
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: ninja -v
    Working Directory: C:/sv/vcpkg/buildtrees/libjpeg-turbo/x86-uwp-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\sv\vcpkg\buildtrees\libjpeg-turbo\config-x86-uwp-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:297 (vcpkg_execute_required_process)
  ports/libjpeg-turbo/portfile.cmake:33 (vcpkg_configure_cmake)
  scripts/ports.cmake:90 (include)


Error: Building package libjpeg-turbo:x86-uwp failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libjpeg-turbo:x86-uwp
  Vcpkg version: 2020.02.04-nohash
```

**Failure logs** 
Package: libjpeg-turbo:x86-uwp
Vcpkg version: 2020.02.04-nohash

**Additional context**
I tried this : https://github.com/microsoft/vcpkg/issues/1158

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Please provide this error log: `C:\sv\vcpkg\buildtrees\libjpeg-turbo\config-x86-uwp-out.log`.

**Comment by rdikshit** [comment]
[1/2] cmd /c "cd .. && "C:/sv/vcpkg/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe" "C:/sv/vcpkg/vcpkg/buildtrees/liblzma/src/v5.2.4-66bfe33102" "-DCMAKE_SYSTEM_NAME=WindowsStore" "-DCMAKE_SYSTEM_VERSION=10.0" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/sv/vcpkg/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x86-uwp" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v142" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/sv/vcpkg/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_TARGET_ARCHITECTURE=x86" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-AWin32" "-G" "Visual Studio 16 2019" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=C:/sv/vcpkg/vcpkg/packages/liblzma_x86-uwp""
FAILED: ../CMakeCache.txt 
cmd /c "cd .. && "C:/sv/vcpkg/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe" "C:/sv/vcpkg/vcpkg/buildtrees/liblzma/src/v5.2.4-66bfe33102" "-DCMAKE_SYSTEM_NAME=WindowsStore" "-DCMAKE_SYSTEM_VERSION=10.0" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/sv/vcpkg/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x86-uwp" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v142" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/sv/vcpkg/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_TARGET_ARCHITECTURE=x86" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-AWin32" "-G" "Visual Studio 16 2019" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=C:/sv/vcpkg/vcpkg/packages/liblzma_x86-uwp""
CMake Warning at C:/sv/vcpkg/vcpkg/scripts/buildsystems/vcpkg.cmake:157 (message):
  There are no libraries installed for the Vcpkg triplet x86-uwp.
Call Stack (most recent call first):
  C:/sv/vcpkg/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/share/cmake-3.14/Modules/CMakeDetermineSystem.cmake:93 (include)
  CMakeLists.txt:2 (project)


CMake Error at CMakeLists.txt:2 (project):
  A Windows Store component with CMake requires both the Windows Desktop SDK
  as well as the Windows Store '10.0' SDK.  Please make sure that you have
  both installed


-- Configuring incomplete, errors occurred!
See also "C:/sv/vcpkg/vcpkg/buildtrees/liblzma/x86-uwp-rel/CMakeFiles/CMakeOutput.log".
[2/2] cmd /c "cd ../../x86-uwp-dbg && "C:/sv/vcpkg/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe" "C:/sv/vcpkg/vcpkg/buildtrees/liblzma/src/v5.2.4-66bfe33102" "-DCMAKE_SYSTEM_NAME=WindowsStore" "-DCMAKE_SYSTEM_VERSION=10.0" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/sv/vcpkg/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x86-uwp" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v142" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/sv/vcpkg/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_TARGET_ARCHITECTURE=x86" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-AWin32" "-G" "Visual Studio 16 2019" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_INSTALL_PREFIX=C:/sv/vcpkg/vcpkg/packages/liblzma_x86-uwp/debug""
FAILED: ../../x86-uwp-dbg/CMakeCache.txt 
cmd /c "cd ../../x86-uwp-dbg && "C:/sv/vcpkg/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe" "C:/sv/vcpkg/vcpkg/buildtrees/liblzma/src/v5.2.4-66bfe33102" "-DCMAKE_SYSTEM_NAME=WindowsStore" "-DCMAKE_SYSTEM_VERSION=10.0" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/sv/vcpkg/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x86-uwp" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v142" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/sv/vcpkg/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_TARGET_ARCHITECTURE=x86" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-AWin32" "-G" "Visual Studio 16 2019" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_INSTALL_PREFIX=C:/sv/vcpkg/vcpkg/packages/liblzma_x86-uwp/debug""
CMake Warning at C:/sv/vcpkg/vcpkg/scripts/buildsystems/vcpkg.cmake:157 (message):
  There are no libraries installed for the Vcpkg triplet x86-uwp.
Call Stack (most recent call first):
  C:/sv/vcpkg/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/share/cmake-3.14/Modules/CMakeDetermineSystem.cmake:93 (include)
  CMakeLists.txt:2 (project)


CMake Error at CMakeLists.txt:2 (project):
  A Windows Store component with CMake requires both the Windows Desktop SDK
  as well as the Windows Store '10.0' SDK.  Please make sure that you have
  both installed


-- Configuring incomplete, errors occurred!
See also "C:/sv/vcpkg/vcpkg/buildtrees/liblzma/x86-uwp-dbg/CMakeFiles/CMakeOutput.log".
ninja: build stopped: subcommand failed.

**Comment by LilyWangL** [comment]
There are this error in your log:
```
CMake Error at CMakeLists.txt:2 (project):
A Windows Store component with CMake requires both the Windows Desktop SDK
as well as the Windows Store '10.0' SDK. Please make sure that you have
both installed
```
This is related with your environment.

**Comment by rdikshit** [comment]
I have installed both the components, still the same error 

Run the visual studio installer
Choose to modify your current install of visual studio
Ensure you have installed both the Universal Windows Platform development and Desktop development with C++ options

**Comment by LilyWangL** [comment]
Sorry I am late. Could you please provide your Visual Studio installation details screenshot to us? Like this:
![image](https://user-images.githubusercontent.com/47812810/84460869-9a7dcc80-ac9d-11ea-9c73-e579f528a052.png)

**Comment by LilyWangL** [comment]
Pinging @rdikshit for response.

**Comment by rdikshit** [comment]
Hello Lily
I was able to resolve the issue. Thanks or your help.
