### ISSUE TITLE
Official exported packages for large projects?

### ISSUE THREAD

**Issue by tjysdsg** [microsoft/vcpkg#11297]
****

**Is your feature request related to a problem? Please describe.**
It takes forever to install llvm on my machine, because of the project is too large.

**Proposed solution**
Create a repository containing prebuilt projects, and users can download them and install them using the `import` command.

Since the CI will build and test all the packages, why not add an `export` command and publish the built packages publicly?

**Additional context**
I understand that maintaining vcpkg itself is probably a huge project, but I think adding this feature will provide huge improvement on the build/install time

**Comment by JackBoosY** [comment]
I think we will never provide pre-compiled binaries.

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/10178
