### ISSUE TITLE
Installed package successfully but include files are not detected in Visual Studio 16

### ISSUE THREAD

**Issue by BaderEddineOuaich** [microsoft/vcpkg#11295]
**Describe the bug**
i am trying to install ``glfw3:x64-windows-static``, it installs and builds just fine. but it does not detect the #include files in visual studio project. i have executed command ``vcpkg integrate install`` after i installed the package but the problem still remain.

**Environment**
- OS: Windows 10 Pro version 1903
- Compiler: Visual C++ 14.25.28610
- Platform Toolset: v142
- IDE: Visual Studio 16 2019 Community

**To Reproduce**
1. ./vcpkg install glfw3:x64-windows-static --clean-after-build
2. ./vcpkg integrate install
3. i open visual studio project and #include <GLFW.. & nothing is detected.

**Expected behavior**
expected visual studio to detect glfw3 include files and use the library statically and gracefully

**Comment by BaderEddineOuaich** [comment]
Additional info
- vcpkg env --debug
<pre>
[DEBUG] Using vcpkg-root: C:\vcpkg<br>
[DEBUG] Found path: C:\Program Files\CMake\bin\cmake.exe<br>
[DEBUG] CreateProcessW("C:\Program Files\CMake\bin\cmake.exe" --version)<br>
[DEBUG] cmd_execute_and_stream_data() returned 0 after  1449937 us<br>
[DEBUG] CreateProcessW("C:\Program Files\CMake\bin\cmake.exe"  -P "C:/vcpkg/buildtrees/0.vcpkg_tags.cmake")<br>
[DEBUG] cmd_execute_and_stream_data() returned 0 after   129242 us<br>
[DEBUG] CreateProcessW("C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -all -prerelease -legacy -
products * -format xml)<br>
[DEBUG] cmd_execute_and_stream_data() returned 0 after    98643 us<br>
[DEBUG] CreateProcessW(cmd /c ""C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsa
ll.bat" -vcvars_ver=14.2 amd64_x86   2>&1 <NUL" & echo cdARN4xjKueKScMy9C6H& set)<br>
[DEBUG] cmd_execute_and_stream_data() returned 0 after  4240670 us<br>
[DEBUG] CreateProcessW(cmd)<br>
Microsoft Windows [Version 10.0.18362.778]
(c) 2019 Microsoft Corporation. All rights reserved.
</pre>

- vcpkg env --debug --triplet x64-windows
<pre>
[DEBUG] Using vcpkg-root: C:\vcpkg<br>
[DEBUG] Found path: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft
\CMake\CMake\bin\cmake.exe<br>
[DEBUG] CreateProcessW("C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Micro
soft\CMake\CMake\bin\cmake.exe" --version)<br>
[DEBUG] cmd_execute_and_stream_data() returned 0 after   781837 us<br>
[DEBUG] CreateProcessW("C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Micro
soft\CMake\CMake\bin\cmake.exe"  -P "C:/vcpkg/buildtrees/0.vcpkg_tags.cmake")<br>
[DEBUG] cmd_execute_and_stream_data() returned 0 after    56889 us<br>
[DEBUG] CreateProcessW("C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -all -prerelease -legacy -
products * -format xml)<br>
[DEBUG] cmd_execute_and_stream_data() returned 0 after    53011 us<br>
[DEBUG] CreateProcessW(cmd /c ""C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsa
ll.bat" -vcvars_ver=14.2 amd64   2>&1 <NUL" & echo cdARN4xjKueKScMy9C6H& set)<br>
[DEBUG] cmd_execute_and_stream_data() returned 0 after  2137467 us
[DEBUG] CreateProcessW(cmd)<br>
Microsoft Windows [Version 10.0.18362.778]
(c) 2019 Microsoft Corporation. All rights reserved.
</pre>

**Comment by PhoebeHui** [comment]
@BaderEddineOuaich, you need add  ' <VcpkgTriplet Condition="'$(Platform)'=='x64'">x64-windows-static</VcpkgTriplet>' in your project file. see https://github.com/microsoft/vcpkg/blob/master/docs/users/integration.md#with-msbuild

<PropertyGroup Label="Globals">
  
  <VcpkgTriplet Condition="'$(Platform)'=='Win32'">x86-windows-static</VcpkgTriplet>
  <VcpkgTriplet Condition="'$(Platform)'=='x64'">x64-windows-static</VcpkgTriplet>
</PropertyGroup>

I tried, it works. see

![image](https://user-images.githubusercontent.com/20694052/87755609-e17d5580-c839-11ea-980f-d7081c85b0cc.png)

**Comment by BaderEddineOuaich** [comment]
@PhoebeHui it solved the issue. thanks!
