### ISSUE TITLE
[freerdp/libusb] build failure

### ISSUE THREAD

**Issue by VelocityRa** [microsoft/vcpkg#11304]
**Host Environment**
- OS: x64-linux
- latest vcpkg master

**To Reproduce**
`./vcpkg install libusb:x64-linux`

**Failure logs** 
```
Building package libusb[core]:x64-linux...
--
737 | CMake Error at ports/libusb/portfile.cmake:2 (message):
738 | Error: the port is unsupported on your platform.  Please open an issue on
739 | github.com/Microsoft/vcpkg to request a fix
740 | Call Stack (most recent call first):
741 | scripts/ports.cmake:90 (include)
742 |  
743 |  
744 | Error: Building package libusb:x64-linux failed with: BUILD_FAILED
745 | Please ensure you're using the latest portfiles with `.\vcpkg update`, then
746 | submit an issue at https://github.com/Microsoft/vcpkg/issues including:
747 | Package: libusb:x64-linux
748 | Vcpkg version: 2020.02.04-unknownhash-external
749 |  
750 | Additionally, attach any relevant sections from the log files above.
751 | The command '/bin/sh -c ./vcpkg install freerdp' returned a non-zero code: 1
752 | time="2020-05-11T07:08:47Z" level=fatal msg="exit status 1"
```

**Additional context**
I'm using the freerdp port which depends on libusb. I don't even make use of libusb, so an alternate solution for my case would be to make the libusb dependency optional.

Relevant PR: https://github.com/microsoft/vcpkg/pull/11051 (added the libusb dependency)

**Comment by AlexAltea** [comment]
Related issue: https://github.com/microsoft/vcpkg/issues/9560

As @VelocityRa mentioned, this causes `freerdp:x64-linux` to fail as well (since it depends on `libusb`).
