### ISSUE TITLE
llvm build failure

### ISSUE THREAD

**Issue by BenKey** [microsoft/vcpkg#11309]
**Host Environment**
- OS: Windows 10 Pro Version 1909 build 18363.778
- Compiler: MSVC 19.25.28614 for x64

**To Reproduce**
`./vcpkg install llvm llvm[clang-tools-extra] llvm[utils] --triplet x64-windows`

**Failure logs** 

```
[3299/3385] cmd.exe /C "cd . && D:\vcpkg\downloads\tools\cmake-3.14.0-windows\cmake-3.14.0-win32-x86\bin\cmake.exe -E vs_link_dll --intdir=tools\clang\tools\libclang\CMakeFiles\libclang.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1425~1.286\bin\Hostx64\x64\link.exe  @CMakeFiles\libclang.rsp  /out:bin\libclangd.dll /implib:lib\libclangd.lib /pdb:bin\libclangd.pdb /dll /version:10.0 /machine:x64 /debug /INCREMENTAL   && cd ."
FAILED: bin/libclangd.dll lib/libclangd.lib 
cmd.exe /C "cd . && D:\vcpkg\downloads\tools\cmake-3.14.0-windows\cmake-3.14.0-win32-x86\bin\cmake.exe -E vs_link_dll --intdir=tools\clang\tools\libclang\CMakeFiles\libclang.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1425~1.286\bin\Hostx64\x64\link.exe  @CMakeFiles\libclang.rsp  /out:bin\libclangd.dll /implib:lib\libclangd.lib /pdb:bin\libclangd.pdb /dll /version:10.0 /machine:x64 /debug /INCREMENTAL   && cd ."
LINK Pass 1: command "C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1425~1.286\bin\Hostx64\x64\link.exe @CMakeFiles\libclang.rsp /out:bin\libclangd.dll /implib:lib\libclangd.lib /pdb:bin\libclangd.pdb /dll /version:10.0 /machine:x64 /debug /INCREMENTAL /MANIFEST /MANIFESTFILE:tools\clang\tools\libclang\CMakeFiles\libclang.dir/intermediate.manifest tools\clang\tools\libclang\CMakeFiles\libclang.dir/manifest.res" failed (exit code 1104) with the following output:
Microsoft (R) Incremental Linker Version 14.25.28614.0
Copyright (C) Microsoft Corporation.  All rights reserved.

...

LINK : fatal error LNK1104: cannot open file 'dl.lib'
ninja: build stopped: subcommand failed.

```
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/4610756/install-x64-windows-dbg-out.log)

**Comment by JackBoosY** [comment]
`dl` should not be linked in windows.

**Comment by yurybura** [comment]
Dear @BenKey please test my fix in PR #11268
Thank you!

**Comment by BenKey** [comment]
@yurybura 
I was not certain how to sync the pull request to my fork.

What I ended up doing is as follows.

1. I replaced ports/llvm/CONTROL with https://raw.githubusercontent.com/microsoft/vcpkg/1b8eb0c93d9d75378e605542cd8a9ecf28ef0a9b/ports/llvm/CONTROL.
2. I replaced ports/llvm/portfile.cmake with https://raw.githubusercontent.com/microsoft/vcpkg/1b8eb0c93d9d75378e605542cd8a9ecf28ef0a9b/ports/llvm/portfile.cmake.
3. I then ran the following command.
     vcpkg install llvm llvm[clang-tools-extra] llvm[utils] --triplet x64-windows

The build still failed with the same error. See the following log file.
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/4619457/install-x64-windows-dbg-out.log)

**Comment by JackBoosY** [comment]
In _SOURCE_PATH/clang/tools/libclang/CMakeLists.txt_ line 63:
```
find_library(DL_LIBRARY_PATH dl)
if (DL_LIBRARY_PATH)
  list(APPEND LIBS dl)
endif()
```

Does this related?

**Comment by yurybura** [comment]
Dear @BenKey you haven't been used my latest version..
Please apply my last commit from PR #11268 : https://github.com/microsoft/vcpkg/pull/11268/commits/a6ddd53c8428425f6b13e12e0a1c93375f70ed2f.
Thank you.

**Comment by yurybura** [comment]
> Does this related?

@JackBoosY  I think so yes. I don't want to patch LLVM code. Instead of that I overrides `DL_LIBRARY_PATH` with empty value using CMake command line (see https://github.com/microsoft/vcpkg/commit/a6ddd53c8428425f6b13e12e0a1c93375f70ed2f).

**Comment by BenKey** [comment]
@yurybura After adding the other change I tried again. It works! Thanks.

**Comment by JackBoosY** [comment]
Please keep this issue open before #11268 merged.
