### ISSUE TITLE
[vcpkg] Could not locate a complete toolset.

### ISSUE THREAD

**Issue by zh1an** [microsoft/vcpkg#11305]
**Describe the bug**
Last week, `vcpkg` is fine, but just now I found it did not work. And I updated from git, it was also failed.

**Environment**
- OS: [windows 10]
- Compiler: msvc 2015

**To Reproduce**
```
F:\vcpkg>vcpkg.exe install asio
Computing installation plan...
The following packages will be built and installed:
    asio[core]:x86-windows
Starting package 1/1: asio:x86-windows
Building package asio[core]:x86-windows...
Could not locate a complete toolset.
The following paths were examined:

```
**Expected behavior**

**Failure logs** 
Could not locate a complete toolset.
The following paths were examined:

**Additional context**
I've checked out other issues. Then I installed **visual studio 2015 english package**, after reboot I tried again, it's failed.

The picture shows visual studio settings.
![微信图片_20200511175756](https://user-images.githubusercontent.com/30436038/81549217-f7d9e180-93b0-11ea-9a12-a7d343719221.png)

**Comment by Voskrese** [comment]
to triplets
`set(VCPKG_PLATFORM_TOOLSET v140)`

**Comment by zh1an** [comment]
> to triplets
> `set(VCPKG_PLATFORM_TOOLSET v140)`

Hi @Voskrese ,
I cannot understand what you've said. Can you tell me what file and where need to modify?

**Comment by tuanhui-li** [comment]
> > to triplets
> > `set(VCPKG_PLATFORM_TOOLSET v140)`
> 
> Hi @Voskrese ,
> I cannot understand what you've said. Can you tell me what file and where need to modify?

Hi, I also want to know how to do set(VCPKG_PLATFORM_TOOLSET v140), how do you solve this problem
