### ISSUE TITLE
install using --overlay-ports results in error (error getting status of path)

### ISSUE THREAD

**Issue by robertobernabe** [microsoft/vcpkg#11301]
**Describe the bug**
`vcpkg install` in combination with `--overlay-ports` is failing since latest release.
If `overlay-ports` is a absolute path it will fail.
Maybe this is an result of 
[vcpkg] Resolve relative overlay ports to the current working directory. (#11233)

**Environment**
- OS: Windows

**To Reproduce**
1. `vcpkg install gtest:x64-windows-static --overlay-ports=<PATH_TO_VCPKG_PORTS_DIR>`
2. See error

```
C:\Users\florian.schaeffeler\vcpkg>vcpkg install gtest:x64-windows-static --overlay-ports=%VCPKG_OVERLAY_PORTS%
Computing installation plan...
error getting status of path C:\Users\florian.schaeffeler\vcpkg\C:Users\florian.schaeffeler\git\wpp\vcpkg-ports\release: The filename, directory name, or volume label syntax is incorrect.

```
**Expected behavior**
Port should be installed without any errors.

**Failure logs** 
-(please attached failure logs)

**Additional context**
Looks like the some path is getting wrongly combined (i assume the overlay ports directory is concatenated with the vcpkg root directory - which makes only sense if overlay ports directory is relative).

**Comment by PhoebeHui** [comment]
Confirmed, this issue reproed. Thank you robertobernabe for bringing this up!

Repro steps:
1. Create .\vcpkg\custom-ports\sqlite3
2. ./vcpkg install sqlite3:x64-windows --overlay-ports=F:\VCPKG\custom-ports\sqlite3
Computing installation plan...
error getting status of path F:\vcpkg\src\F:VCPKG\custom-ports\sqlite3: The filename, directory name, or volume label syntax is incorrect.

**Comment by TobiasFunk** [comment]
Hey i have already a fix for the issue and will create a PR in the next minutes

**Comment by PhoebeHui** [comment]
@TobiasFunk, thanks for your quick fix!

I tried it, it works well for this case!

Computing installation plan...
The following packages will be built and installed:
    sqlite3[core]:x64-windows -- F:\VCPKG\custom-ports\sqlite3
Starting package 1/1: sqlite3:x64-windows
Building package sqlite3[core]:x64-windows...
-- Installing port from location: F:\VCPKG\custom-ports\sqlite3
use custom-ports sqlite
-- Using cached F:/VCPKG/src/downloads/sqlite-amalgamation-3310100.zip
-- Using source at F:/VCPKG/src/buildtrees/sqlite3/src/3310100-b37a578ce1
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package sqlite3[core]:x64-windows... done
Installing package sqlite3[core]:x64-windows...
Installing package sqlite3[core]:x64-windows... done
Elapsed time for package sqlite3:x64-windows: 30.11 s

Total elapsed time: 30.32 s

The package sqlite3:x64-windows provides CMake targets:

    find_package(sqlite3 CONFIG REQUIRED)
    target_link_libraries(main PRIVATE sqlite3)
