### ISSUE TITLE
Support for dynamic runtime with static linking?

### ISSUE THREAD

**Issue by laohyx** [Microsoft/vcpkg#1131]
Hi,

Now vcpkg has supported both dynamic and static linking, but I noticed that `*-windows-static` triplet set both `VCPKG_CRT_LINKAGE` and `VCPKG_LIBRARY_LINKAGE` to `static`.

Is there a possibility to have this triplet? Or for what reason vcpkg requires linking and runtime the same?
```
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE static)
```

Thanks.

**Comment by bagong** [comment]
You can define you're own build triplet and use it to build. Unfortunately the combination crt-dynamic (md) and library-static are not offered by default, although I am pretty sure they are quite much needed.

**Comment by laohyx** [comment]
Thanks for your quick response!

Yes, I added a new triplet as I said. But for some ports, the `portfile.cmake` doesn't consider other triplets. Can I make pull requests for these non-existed triplets? Maybe helpful for other combinations.

For example, `gtest`, under static linking, would use static runtime by default, but the `portfile` doesn't provide config for dynamic runtime under static linking. I would like to add such an option to make it work.

**Comment by bagong** [comment]
Hmmm, what I've been doing is for example create a triplet of the type x64-staticlib-dynamiccrt, call the file x64-windows-static-md, and then build: `vcpkg pname:x64-windows-static-md`. It seemed to work, no need for the portfile to know of it, except your particular build needs to reflect that in the cmake-configuration (which is usually not the case, I think)

**Comment by laohyx** [comment]
Please check `vcpkg install gtest:x64-windows-static-md`
`gtest` is the case. [It uses static CRT when static linking](https://github.com/google/googletest/blob/master/googletest/cmake/internal_utils.cmake#L35)

**Comment by bagong** [comment]
Well, yes, that's a case where it would be nice to make a cmake patch that prevents the execution of that line if setting dynamic crt via build triplet. From my limited understanding there is one case in which it is really unavoidable to combine static library with dynamic runtime: if you have a build where some libraries a linked statically and others dynamically.

**Comment by ras0219-msft** [comment]
It's definitely reasonable to add these triplets yourself. We'd be happy to accept PRs for libraries that misbehave under this configuration!

We want to be cautious about adding more "in-box" triplets because it significantly increases the burden on maintainers. Testing all the possible flavors will easily result in several dozen builds, which is currently unreasonable (in the future we hope to improve this!).

**Comment by ras0219-msft** [comment]
On the specific point of `gtest`, we do specify `gtest_force_shared_crt`[1] which should allow us to correctly support static-md.

[1] https://github.com/Microsoft/vcpkg/blob/master/ports/gtest/portfile.cmake#L20-L24

**Comment by jjYBdx4IL** [comment]
Microsoft recommends /MD. Why would anyone use /MT just because they wanna include boost or wxwidgets libs directly into their .exe output? Kinda strange to discourage static-md because the static-md is exactly what MS seems to recommend.
