### ISSUE TITLE
[realsense2] update to 2.34.1

### ISSUE THREAD

**Issue by Yanis-F** [microsoft/vcpkg#11329]
Library name:
realsense2

New version number: 
v2.34.1

Other information that may be useful (release notes, etc...) :
v2.34.1 commit : https://github.com/IntelRealSense/librealsense/tree/v2.34.1

**Comment by Yanis-F** [comment]
I just realized the 2.34.1 is on the development branch, I am a bit confused about this since the version is listed in the "release" tab of the github.
I would need at least the 2.34.0 version

**Comment by Cheney-W** [comment]
@Yanis-F Thanks for reporting this issue! 
I'll update this version to 2.34.0, it's currently being tested for FEATURE, and when the FEATURE test passes, I'll submit a PR.
