### ISSUE TITLE
Add package for StrTk

### ISSUE THREAD

**Issue by jschroedl** [Microsoft/vcpkg#1133]
Description:
The C++ String Toolkit Library (StrTk) consists of robust, optimized and portable string processing algorithms for the C++ language. StrTk is designed to be easy to use and integrate within existing code bases. Furthermore the library has a rich set of features that makes light work of any kind of string processing task. 

http://www.partow.net/programming/strtk/index.html

**Comment by Mixaill** [comment]
Please check #1142
