### ISSUE TITLE
ffmpeg:x64-windows build failure

### ISSUE THREAD

**Issue by EnzoDAndrea** [microsoft/vcpkg#11337]
**Host Environment**
- OS: Windows 10
- Compiler: Visual Studio 2019 CMAKE

**To Reproduce**
`./vcpkg install ffmpeg:x64-windows`

**Failure logs** 
-- Using cached C:/Program Files/VCPkg/downloads/ffmpeg-ffmpeg-n4.2.tar.gz
-- Extracting source C:/Program Files/VCPkg/downloads/ffmpeg-ffmpeg-n4.2.tar.gz
-- Applying patch 0001-create-lib-libraries.patch
-- Applying patch 0003-fix-windowsinclude.patch
-- Applying patch 0004-fix-debug-build.patch
-- Applying patch 0005-fix-libvpx-linking.patch
-- Applying patch 0006-fix-StaticFeatures.patch
-- Using source at C:/Program Files/VCPkg/buildtrees/ffmpeg/src/n4.2-a4d149a5c6
CMake Error at ports/ffmpeg/portfile.cmake:16 (message):
  Error: ffmpeg will not build with spaces in the path.  Please use a
  directory with no spaces
Call Stack (most recent call first):
  scripts/ports.cmake:90 (include)

*** INFO
zlib 9733f1ea63ddd8ae97810e5598daeaa5e7da26e0
CONTROL 16fe63bb95b1e9f309b54c7bea9521cb72d20be3
vcpkg-cmake-wrapper.cmake 185f3ce346a5ced573f6c7fd41ab9f5146b77bb5
0006-fix-StaticFeatures.patch 2019b72a6e7af153bdd54cb574ae6fc2d2f43836
0004-fix-debug-build.patch 24fb49856631788d651d27b1ecdc669cc99b450a
build.sh 7a3fcf869b5017c3763afe90e5894486e74029bb
0001-create-lib-libraries.patch 82fd250e880296562bee8b4c9342e5a735cb39aa
build_linux.sh 88c253cadd25d2e59dd99bc4ec57abc1b4684680
FindFFMPEG.cmake.in 9be54e6c701714f18bc8aac485db5eb8996816f3
0005-fix-libvpx-linking.patch ca631d186b134bd84fe324210eff8ff5832552c2
portfile.cmake d8c993a6f7e8619d4ff141702dd59463db7aa005
0003-fix-windowsinclude.patch ebeecc1f6d119d180ffbb7e6686d6bfdbd19c2a7
cmake 3.14.7
powershell ab1effc926b000a6adc12198a1886514ec203621a53b0cd7ec1cd9a8225dccda7e857feaabcfba4004bea73129b986abaad777c4573f44e0af70411226ce08b0
vcpkg_fixup_cmake_targets dac334f3bf50b8262be92623168023aa565aa729
post_build_checks 2
triplet 3eab5c64d9cf628fc0aec277fde66dbdc69b8516
features avresample;core

[stdout-x64-windows.log](https://github.com/microsoft/vcpkg/files/4623442/stdout-x64-windows.log)
[x64-windows.vcpkg_abi_info.txt](https://github.com/microsoft/vcpkg/files/4623443/x64-windows.vcpkg_abi_info.txt)

**Comment by timautry** [comment]
**Error: ffmpeg will not build with spaces in the path. Please use a directory with no spaces**
`C:/Program Files/VCPkg/buildtrees/ffmpeg/src/n4.2-a4d149a5c6` contains a space.
Put vcpkg in a location without any spaces.

**Comment by PhoebeHui** [comment]
@EnzoDAndrea, please try the solution provided by timautry, and reopen this issue if it still be a problem for you.
