### ISSUE TITLE
[libdisasm:x64-windows] build failure

### ISSUE THREAD

**Issue by taimoortanweer1** [microsoft/vcpkg#11333]
**Host Environment**
- O: Windows 7
- Compiler:   Vcpkg version: 2020.02.04-nohash

**To Reproduce**
`./vcpkg install libdisasm:x64-windows`

**Failure logs** 
Building vcpkg.exe... done.

Telemetry
---------
vcpkg collects usage data in order to help us improve your experience. The data collected by Microsoft is anonymous. You can opt-out of telemetry by re-running bootstrap-vcpkg.bat with -disableMetrics.
Read more about vcpkg telemetry at docs/about/privacy.md

Computing installation plan...
The following packages will be built and installed:
    breakpad[core]:x64-windows
  * bzip2[core]:x64-windows
  * libdisasm[core]:x64-windows
    libzip[bzip2,core,default-aes,wincrypto]:x64-windows
    libzippp[core]:x64-windows
    nlohmann-json[core]:x64-windows
    openssl[core]:x64-windows
  * openssl-windows[core]:x64-windows
    zlib[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/9: libdisasm:x64-windows
Building package libdisasm[core]:x64-windows...
-- Note: libdisasm only supports static library linkage. Building static library.
-- Downloading https://sourceforge.net/projects/bastard/files/libdisasm/0.23/libdisasm-0.23.tar.gz...
-- Downloading https://sourceforge.net/projects/bastard/files/libdisasm/0.23/libdisasm-0.23.tar.gz... Failed. Status: 7;"Couldn't connect to server"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:175 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  ports/libdisasm/portfile.cmake:5 (vcpkg_download_distfile)
  scripts/ports.cmake:90 (include)

Error: Building package libdisasm:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libdisasm:x64-windows
  Vcpkg version: 2020.02.04-nohash
**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by LilyWangL** [comment]
@taimoortanweer1 Thanks for posting this issue, could you work around this issue as following steps:

1. Download https://sourceforge.net/projects/bastard/files/libdisasm/0.23/libdisasm-0.23.tar.gz manually.
2. Put libdisasm-0.23.tar.gz to .\vcpkg\downloads\
3. Try to build again.

**Comment by taimoortanweer1** [comment]
I think this is not a solution this is just a way around but anyways thanks for your help :)
