### ISSUE TITLE
easyhook install failed

### ISSUE THREAD

**Issue by babyaaaaaa** [microsoft/vcpkg#11347]
Computing installation plan...
The following packages will be built and installed:
    easyhook[core]:x86-windows
Starting package 1/1: easyhook:x86-windows
Building package easyhook[core]:x86-windows...
.Net framework 4.0 is required, please install it before install easyhook.
-- Using cached D:/work/windows project/vcpkg-master/downloads/EasyHook-EasyHook-v2.7.6789.0.tar.gz
-- Using source at D:/work/windows project/vcpkg-master/buildtrees/easyhook/src/2.7.6789.0-a68d73d015
-- Building EasyHook.sln for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: msbuild "D:/work/windows project/vcpkg-master/buildtrees/easyhook/x86-windows-rel/2.7.6789.0-a68d73d015/EasyHook.sln" /p:Configuration=netfx4-Release /t:EasyHookDll /p:Platform=Win32 /p:PlatformToolset=v142 /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /p:WindowsTargetPlatformVersion=10.0.18362.0 /m
    Working Directory: D:/work/windows project/vcpkg-master/buildtrees/easyhook/x86-windows-rel/2.7.6789.0-a68d73d015
    Error code: 1
    See logs for more information:
      D:\work\windows project\vcpkg-master\buildtrees\easyhook\build-x86-windows-rel-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_msbuild.cmake:159 (vcpkg_execute_required_process)
  ports/easyhook/portfile.cmake:22 (vcpkg_install_msbuild)
  scripts/ports.cmake:90 (include)

Error: Building package easyhook:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: easyhook:x86-windows
  Vcpkg version: 2020.02.04-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by LilyWangL** [comment]
Please provide the error log: `D:\work\windows project\vcpkg-master\buildtrees\easyhook\build-x86-windows-rel-out.log`.

**Comment by babyaaaaaa** [comment]
hi，this is the log，thanks a lot


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Lily"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月18日(星期一) 下午4:32
收件人:&nbsp;"microsoft/vcpkg"<vcpkg@noreply.github.com&gt;;
抄送:&nbsp;"祝明"<397756442@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [microsoft/vcpkg] easyhook install failed (#11347)





 
Please provide the error log: D:\work\windows project\vcpkg-master\buildtrees\easyhook\build-x86-windows-rel-out.log.

**Comment by LilyWangL** [comment]
You can attach the log file on this page.

**Comment by babyaaaaaa** [comment]
用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.5.0+d4cbfca49
版权所有(C) Microsoft Corporation。保留所有权利。

生成启动时间为 2020/5/18 20:11:31。
     1>项目“D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\EasyHook.sln”在节点 1 上(EasyHookDll 个目标)。
     1>ValidateSolutionConfiguration:
         正在生成解决方案配置“netfx4-Release|Win32”。
     1>项目“D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\EasyHook.sln”(1)正在节点 1 上生成“D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\EasyHookDll\EasyHookDll.vcxproj”(2) (默认目标)。
     2>项目“D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\EasyHookDll\EasyHookDll.vcxproj”(2)正在节点 1 上生成“D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\EasyHookSvc\EasyHookSvc.csproj”(3:2) (默认目标)。
     3>PrepareForBuild:
         正在创建目录“..\Build\netfx4-Release\x86\”。
         正在创建目录“obj\x86\netfx4-Release\”。
   3:2>项目“D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\EasyHookSvc\EasyHookSvc.csproj”(3:2)正在节点 1 上生成“D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\EasyHook\EasyHook.csproj”(4:3) (默认目标)。
     4>PrepareForBuild:
         正在创建目录“..\Build\netfx4-Release\x64\”。
         正在创建目录“obj\netfx4-Release\”。
       ResolveAssemblyReferences:
         将生成 TargetFramework 配置文件排除列表。
       GenerateTargetFrameworkMonikerAttribute:
       正在跳过目标“GenerateTargetFrameworkMonikerAttribute”，因为所有输出文件相对于输入文件而言都是最新的。
       CoreCompile:
         C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Roslyn\csc.exe /noconfig /unsafe+ /nowarn:1701,1702 /nostdlib+ /platform:AnyCPU /errorreport:prompt /doc:..\Build\netfx4-Release\x64\EasyHook.XML /define:TRACE;NET4 /highentropyva- /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\Profile\Client\mscorlib.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\Profile\Client\System.Core.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\Profile\Client\System.Data.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\Profile\Client\System.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\Profile\Client\System.Runtime.Remoting.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\Profile\Client\System.Xml.dll" /debug:pdbonly /keyfile:StrongName.snk /optimize+ /out:obj\netfx4-Release\EasyHook.dll /ruleset:"C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Team Tools\Static Analysis Tools\\Rule Sets\AllRules.ruleset" /target:library /utf8output /langversion:7.3 COMClassInfo.cs GACWrap.cs Config.cs Debugging.cs DllImport.cs HelperServiceInterface.cs InjectionLoader.cs LocalHook.cs Properties\AssemblyInfo.cs RemoteHook.cs ServiceMgmt.cs WOW64Bypass.cs "C:\Users\39775\AppData\Local\Temp\.NETFramework,Version=v4.0,Profile=Client.AssemblyAttributes.cs"
         对来自后列目录的编译器使用共享编译: C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Roslyn
       CopyFilesToOutputDirectory:
         正在将文件从“D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\EasyHook\obj\netfx4-Release\EasyHook.dll”复制到“D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\Build\netfx4-Release\x64\EasyHook.dll”。
         EasyHook -> D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\Build\netfx4-Release\x64\EasyHook.dll
         正在将文件从“D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\EasyHook\obj\netfx4-Release\EasyHook.pdb”复制到“D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\Build\netfx4-Release\x64\EasyHook.pdb”。
       AfterBuild:
         正在将文件从“D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\Build\netfx4-Release\x64\EasyHook.dll”复制到“D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\Build\netfx4-Release\x86\EasyHook.dll”。
     4>已完成生成项目“D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\EasyHook\EasyHook.csproj”(默认目标)的操作。
     3>ResolveAssemblyReferences:
         将生成 TargetFramework 配置文件排除列表。
       GenerateTargetFrameworkMonikerAttribute:
       正在跳过目标“GenerateTargetFrameworkMonikerAttribute”，因为所有输出文件相对于输入文件而言都是最新的。
       CoreCompile:
         C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Roslyn\csc.exe /noconfig /nowarn:1701,1702 /nostdlib+ /platform:x86 /errorreport:prompt /define:TRACE;NET4 /highentropyva- /reference:"D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\Build\netfx4-Release\x64\EasyHook.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\Profile\Client\mscorlib.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\Profile\Client\System.Core.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\Profile\Client\System.Data.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\Profile\Client\System.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\Profile\Client\System.Runtime.Remoting.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\Profile\Client\System.ServiceProcess.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\Profile\Client\System.Xml.dll" /debug:pdbonly /keyfile:StrongName.snk /optimize+ /out:obj\x86\netfx4-Release\EasyHookSvc.exe /ruleset:"C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Team Tools\Static Analysis Tools\\Rule Sets\AllRules.ruleset" /target:exe /utf8output /langversion:7.3 InjectionService.cs InjectionService.designer.cs Program.cs Properties\AssemblyInfo.cs "C:\Users\39775\AppData\Local\Temp\.NETFramework,Version=v4.0,Profile=Client.AssemblyAttributes.cs"
         对来自后列目录的编译器使用共享编译: C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Roslyn
       _CopyFilesMarkedCopyLocal:
         正在将文件从“D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\Build\netfx4-Release\x64\EasyHook.pdb”复制到“D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\Build\netfx4-Release\x86\EasyHook.pdb”。
         正在将文件从“D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\Build\netfx4-Release\x64\EasyHook.xml”复制到“D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\Build\netfx4-Release\x86\EasyHook.xml”。
         正在创建“D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\EasyHookSvc\obj\x86\netfx4-Release\EasyHookSvc.csproj.CopyComplete”，因为已指定“AlwaysCreate”。
       CopyFilesToOutputDirectory:
         正在将文件从“D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\EasyHookSvc\obj\x86\netfx4-Release\EasyHookSvc.exe”复制到“D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\Build\netfx4-Release\x86\EasyHookSvc.exe”。
         EasyHookSvc -> D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\Build\netfx4-Release\x86\EasyHookSvc.exe
         正在将文件从“D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\EasyHookSvc\obj\x86\netfx4-Release\EasyHookSvc.pdb”复制到“D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\Build\netfx4-Release\x86\EasyHookSvc.pdb”。
       AfterBuild:
         正在将文件从“D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\Build\netfx4-Release\x86\EasyHookSvc.exe”复制到“D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\Build\netfx4-Release\x86\EasyHook32Svc.exe”。
         正在将文件从“D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\Build\netfx4-Release\x86\EasyHook32Svc.exe”复制到“D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\Build\netfx4-Release\x64\EasyHook32Svc.exe”。
     3>已完成生成项目“D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\EasyHookSvc\EasyHookSvc.csproj”(默认目标)的操作。
     2>PrepareForBuild:
         正在创建目录“D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\Build\netfx4-Release\x86\Temp\EasyHookDll\”。
         正在创建目录“D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\Build\netfx4-Release\x86\Temp\EasyHookDll\EasyHookDll.tlog\”。
       InitializeBuildStatus:
         正在创建“D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\Build\netfx4-Release\x86\Temp\EasyHookDll\EasyHookDll.tlog\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
       _MASM:
         Assembling ..\DriverShared\ASM\HookSpecific_x86.asm...
         cmd.exe /C "C:\Users\39775\AppData\Local\Temp\tmp63c978b490ec4c418ad476bda4373965.cmd"
         ml.exe /c /nologo /Fo"D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\Build\netfx4-Release\x86\Temp\EasyHookDll\HookSpecific_x86.obj" /W3 /errorReport:prompt  /Ta..\DriverShared\ASM\HookSpecific_x86.asm
       ClCompile:
         C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.25.28610\bin\HostX64\x86\CL.exe /c /I"D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\\DriverShared" /I"D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\\" /I"D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\\Public" /I"D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\EasyHookDll\\" /Zi /nologo /W4 /WX- /diagnostics:column /Ox /Oi /Ot /Oy- /GL /D WIN32 /D _WINDOWS /D _USRDLL /D EASYHOOK_EXPORTS /D _WINDLL /D _UNICODE /D UNICODE /GF /Gm- /EHa /MT /GS- /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\Build\netfx4-Release\x86\Temp\EasyHookDll\\" /Fd"D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\Build\netfx4-Release\x86\Temp\EasyHookDll\vc142.pdb" /Gz /TC /analyze- /FC /errorReport:queue ..\DriverShared\Disassembler\libudis86\decode.c ..\DriverShared\Disassembler\libudis86\itab.c "..\DriverShared\Disassembler\libudis86\syn-att.c" "..\DriverShared\Disassembler\libudis86\syn-intel.c" ..\DriverShared\Disassembler\libudis86\syn.c ..\DriverShared\Disassembler\libudis86\udis86.c
         decode.c
         itab.c
         syn-att.c
         syn-intel.c
         syn.c
         udis86.c
         C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.25.28610\bin\HostX64\x86\CL.exe /c /I"D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\\DriverShared" /I"D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\\" /I"D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\\Public" /I"D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\EasyHookDll\\" /Zi /nologo /W4 /WX- /diagnostics:column /Ox /Oi /Ot /Oy- /GL /D WIN32 /D _WINDOWS /D _USRDLL /D EASYHOOK_EXPORTS /D _WINDLL /D _UNICODE /D UNICODE /GF /Gm- /EHa /MT /GS- /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\Build\netfx4-Release\x86\Temp\EasyHookDll\\" /Fd"D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\Build\netfx4-Release\x86\Temp\EasyHookDll\vc142.pdb" /Gz /TP /analyze- /FC /errorReport:queue dllmain.c LocalHook\acl.c ..\DriverShared\LocalHook\alloc.c ..\DriverShared\LocalHook\barrier.c ..\DriverShared\LocalHook\caller.c LocalHook\debug.cpp ..\DriverShared\LocalHook\install.c ..\DriverShared\LocalHook\reloc.c ..\DriverShared\LocalHook\uninstall.c RemoteHook\driver.cpp RemoteHook\entry.cpp gacutil.cpp RemoteHook\service.c RemoteHook\stealth.c RemoteHook\thread.c ..\DriverShared\Rtl\error.c Rtl\file.c Rtl\memory.c ..\DriverShared\Rtl\string.c
         dllmain.c
         acl.c
         alloc.c
         barrier.c
         caller.c
         debug.cpp
         install.c
         reloc.c
         uninstall.c
         driver.cpp
         entry.cpp
     2>D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\EasyHookDll\RemoteHook\entry.cpp(31,10): fatal error C1083: Cannot open include file: 'mscoree.h': No such file or directory [D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\EasyHookDll\EasyHookDll.vcxproj]
         gacutil.cpp
     2>D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\EasyHookDll\gacutil.cpp(26,10): fatal error C1083: Cannot open include file: 'fusion.h': No such file or directory [D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\EasyHookDll\EasyHookDll.vcxproj]
         service.c
         stealth.c
     2>D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\EasyHookDll\RemoteHook\stealth.c(223,2): warning C4002: too many arguments for function-like macro invocation 'DEBUGMSG' [D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\EasyHookDll\EasyHookDll.vcxproj]
         thread.c
     2>D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\EasyHookDll\RemoteHook\thread.c(1808,114): warning C4477: 'sprintf_s' : format string '%x' requires an argument of type 'unsigned int', but variadic argument 3 has type 'ULONG64' [D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\EasyHookDll\EasyHookDll.vcxproj]
       D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\EasyHookDll\RemoteHook\thread.c(1808,114): message : consider using '%llx' in the format string [D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\EasyHookDll\EasyHookDll.vcxproj]
       D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\EasyHookDll\RemoteHook\thread.c(1808,114): message : consider using '%I64x' in the format string [D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\EasyHookDll\EasyHookDll.vcxproj]
     2>D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\EasyHookDll\RemoteHook\thread.c(1836,114): warning C4477: 'sprintf_s' : format string '%x' requires an argument of type 'unsigned int', but variadic argument 3 has type 'ULONG64' [D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\EasyHookDll\EasyHookDll.vcxproj]
       D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\EasyHookDll\RemoteHook\thread.c(1836,114): message : consider using '%llx' in the format string [D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\EasyHookDll\EasyHookDll.vcxproj]
       D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\EasyHookDll\RemoteHook\thread.c(1836,114): message : consider using '%I64x' in the format string [D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\EasyHookDll\EasyHookDll.vcxproj]
     2>D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\EasyHookDll\RemoteHook\thread.c(1851,114): warning C4477: 'sprintf_s' : format string '%x' requires an argument of type 'unsigned int', but variadic argument 3 has type 'ULONG64' [D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\EasyHookDll\EasyHookDll.vcxproj]
       D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\EasyHookDll\RemoteHook\thread.c(1851,114): message : consider using '%llx' in the format string [D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\EasyHookDll\EasyHookDll.vcxproj]
       D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\EasyHookDll\RemoteHook\thread.c(1851,114): message : consider using '%I64x' in the format string [D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\EasyHookDll\EasyHookDll.vcxproj]
         error.c
         file.c
         memory.c
         string.c
     2>已完成生成项目“D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\EasyHookDll\EasyHookDll.vcxproj”(默认目标)的操作 - 失败。
     1>已完成生成项目“D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\EasyHook.sln”(EasyHookDll 个目标)的操作 - 失败。

生成失败。

       “D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\EasyHook.sln”(EasyHookDll 目标) (1) ->
       “D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\EasyHookDll\EasyHookDll.vcxproj”(默认目标) (2) ->
       (ClCompile 目标) -> 
         D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\EasyHookDll\RemoteHook\stealth.c(223,2): warning C4002: too many arguments for function-like macro invocation 'DEBUGMSG' [D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\EasyHookDll\EasyHookDll.vcxproj]
         D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\EasyHookDll\RemoteHook\thread.c(1808,114): warning C4477: 'sprintf_s' : format string '%x' requires an argument of type 'unsigned int', but variadic argument 3 has type 'ULONG64' [D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\EasyHookDll\EasyHookDll.vcxproj]
         D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\EasyHookDll\RemoteHook\thread.c(1836,114): warning C4477: 'sprintf_s' : format string '%x' requires an argument of type 'unsigned int', but variadic argument 3 has type 'ULONG64' [D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\EasyHookDll\EasyHookDll.vcxproj]
         D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\EasyHookDll\RemoteHook\thread.c(1851,114): warning C4477: 'sprintf_s' : format string '%x' requires an argument of type 'unsigned int', but variadic argument 3 has type 'ULONG64' [D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\EasyHookDll\EasyHookDll.vcxproj]


       “D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\EasyHook.sln”(EasyHookDll 目标) (1) ->
       “D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\EasyHookDll\EasyHookDll.vcxproj”(默认目标) (2) ->
       (ClCompile 目标) -> 
         D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\EasyHookDll\RemoteHook\entry.cpp(31,10): fatal error C1083: Cannot open include file: 'mscoree.h': No such file or directory [D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\EasyHookDll\EasyHookDll.vcxproj]
         D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\EasyHookDll\gacutil.cpp(26,10): fatal error C1083: Cannot open include file: 'fusion.h': No such file or directory [D:\work\windows project\vcpkg-master\buildtrees\easyhook\x86-windows-rel\2.7.6789.0-a68d73d015\EasyHookDll\EasyHookDll.vcxproj]

    4 个警告
    2 个错误

已用时间 00:00:11.68

**Comment by LilyWangL** [comment]
Thanks for your reply. I can't reproduce this issue locally, I installed it successfully with Visual Studio 2019 and VCPKG latest source on Windows 10. Could you provide your machine information?

**Comment by babyaaaaaa** [comment]
> Thanks for your reply. I can't reproduce this issue locally, I installed it successfully with Visual Studio 2019 and VCPKG latest source on Windows 10. Could you provide your machine information?

I use win10 and Vcpkg version: 2020.02.04

**Comment by babyaaaaaa** [comment]
Computing installation plan...
The following packages will be built and installed:
    easyhook[core]:x86-windows
Starting package 1/1: easyhook:x86-windows
Building package easyhook[core]:x86-windows...
.Net framework 4.0 is required, please install it before install easyhook.
-- Using cached D:/work/windows_project/vcpkg-master/downloads/EasyHook-EasyHook-v2.7.6789.0.tar.gz
-- Using source at D:/work/windows_project/vcpkg-master/buildtrees/easyhook/src/2.7.6789.0-a68d73d015
-- Building EasyHook.sln for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: msbuild D:/work/windows_project/vcpkg-master/buildtrees/easyhook/x86-windows-rel/2.7.6789.0-a68d73d015/EasyHook.sln /p:Configuration=netfx4-Release /t:EasyHookDll /p:Platform=Win32 /p:PlatformToolset=v142 /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /p:WindowsTargetPlatformVersion=10.0.18362.0 /m
    Working Directory: D:/work/windows_project/vcpkg-master/buildtrees/easyhook/x86-windows-rel/2.7.6789.0-a68d73d015
    Error code: 1
    See logs for more information:
      D:\work\windows_project\vcpkg-master\buildtrees\easyhook\build-x86-windows-rel-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_msbuild.cmake:159 (vcpkg_execute_required_process)
  ports/easyhook/portfile.cmake:22 (vcpkg_install_msbuild)
  scripts/ports.cmake:90 (include)


Error: Building package easyhook:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:

**Comment by LilyWangL** [comment]
Thanks for your reply. `mscoree.h` and `fusion.h` is part of the native API to the .NET runtime. You should confirm if you install the following items on Visual Studio.
![image](https://user-images.githubusercontent.com/47812810/86901172-d1c98700-c13e-11ea-87ca-fcd2e2a8f10f.png)

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
