### ISSUE TITLE
Error running `.\vcpkg integrate install` after build

### ISSUE THREAD

**Issue by celsomilne** [microsoft/vcpkg#11342]
**Describe the bug**
`vcpkg` installs from bootstrap fine, but calling `.\vcpkg integrate install` (or any other `vcpkg` command) causes an error: 
```
Program 'vcpkg.exe' failed to run: The system cannot find the file specifiedAt line:1 char:1
+ .\vcpkg.exe integrate install
```

**Environment**
- OS: Windows 10
- Compiler: Microsoft (R) C/C++ Optimizing Compiler Version 19.25.28614 for x86

**To Reproduce**
1. `.\bootstrap-vcpkg.bat` (installation proceeds fine):
```
[... enumeration of .cpp files to compile]
  Generating code
  Previous IPDB not found, fall back to full compilation.
  All 17630 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Finished generating code
  vcpkg.vcxproj -> C:\Users\Celso\vcpkg\toolsrc\msbuild.x86.release\vcpkg.exe
  vcpkgmetricsuploader.cpp
  Generating code
  Previous IPDB not found, fall back to full compilation.
  All 6758 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Finished generating code
  vcpkgmetricsuploader.vcxproj -> C:\Users\Me\vcpkg\toolsrc\msbuild.x86.release\vcpkgmetricsuploader.exe
Building vcpkg.exe... done.
```
2. Run `.\vcpkg integrate install`
```
Program 'vcpkg.exe' failed to run: The system cannot find the file specifiedAt line:1 char:1
+ .\vcpkg integrate install
+ ~~~~~~~~~~~~~~~~~~~~~~~~~.
At line:1 char:1
+ .\vcpkg integrate install
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed
```

**Additional context**
I've tried running these commands from both `Developer Command Prompt for VS 2019` and `Windows PowerShell`. Both instances have been run with Administrator rights (as per the docs). I've tried pulling as well, but everything is up to date.

**EDIT:**
Once I run `.\vcpkg integrate install`, the `vcpkg.exe` disappears from the directory, as if deleted. I have also tried using `Developer Command Prompt for VS 2017`, to no avail.

**Comment by PhoebeHui** [comment]
@celsomilne, sorry for my late reply.

It seems that vcpkg.exe removed, it might due to false alert in virus detection, could you check that your anti-virus software isn't blocking VCPKG?

**Comment by PhoebeHui** [comment]
@celsomilne, please reopen this issue if it still be a problem for you.
