### ISSUE TITLE
[python3] Installs import library in x64-windows-static builds 

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#11349]
On Windows python3
- has only VS projects for dll's in its source tree. 
- portfiles indicates some patches which does not exist anymore?
- in static builds only an import library is installed and not a static library. (How does this pass post build checks?)
- CRT linkage is also a kind of a mystery to me.

**Comment by Hoikas** [comment]
This was fixed in #11708.

**Comment by strega-nil** [comment]
From @Hoikas, this issue has been solved. Thanks y'all!
