### ISSUE TITLE
The ABC's of a platformio setup 

### ISSUE THREAD

**Issue by gregfoulkes** [microsoft/vcpkg#11340]
https://github.com/microsoft/vcpkg/blob/24e8be5fcfddd0da98b58a63cd918849787fb06fain.cpp#L4-L4

**Comment by linquize** [comment]
Do you mean https://github.com/microsoft/vcpkg/blob/24e8be5fcfddd0da98b58a63cd918849787fb06f/toolsrc/src/vcpkg-fuzz/main.cpp ?

**Comment by LilyWangL** [comment]
@gregfoulkes Thanks for posting this issue. Could you please more information about this issue?

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
