### ISSUE TITLE
[mpir] build failure

### ISSUE THREAD

**Issue by acgetchell** [microsoft/vcpkg#11346]
**Host Environment**
- OS: macOS 10.14.6
- Compiler: gcc 9.3.0

**To Reproduce**
`./vcpkg install mpir --triplet=`

**Failure logs** 

```
Error: Building package mpir:x64-osx failed with: BUILD_FAILED

Please ensure you're using the latest portfiles with `.\vcpkg update`, then

submit an issue at https://github.com/Microsoft/vcpkg/issues including:

  Package: mpir:x64-osx

  Vcpkg version: 2020.02.04-unknownhash
```

https://travis-ci.org/github/acgetchell/CDT-plusplus/jobs/686812207#L2281

**Additional context**

https://github.com/acgetchell/CDT-plusplus/blob/develop/.travis.yml

**Comment by NancyLi1013** [comment]
Hi @acgetchell 
Thanks for posting this issue.
Could you please provide the error log from here?
_/Users/travis/build/acgetchell/CDT-plusplus/vcpkg/buildtrees/mpir/install-x64-osx-dbg-out.log
 /Users/travis/build/acgetchell/CDT-plusplus/vcpkg/buildtrees/mpir/install-x64-osx-dbg-err.log_

**Comment by acgetchell** [comment]
I’m sorry, I don’t have direct access to Travis-CI’s file system to retrieve those particular logs.

**Comment by NancyLi1013** [comment]
So we cannot get the error info now?
Since I cannot reproduce this on my local with clang 11.0.0, I don't know what happened on Travis-CI.

**Comment by NancyLi1013** [comment]
Is this similar to #8627?

**Comment by acgetchell** [comment]
I believe it can be reproduced on MacOS 10.14 with gcc 9.3.0 installed via Homebrew.

**Comment by NancyLi1013** [comment]
Thanks for your info. I only have MacOS 10.15.2 machine now. 
So there should be more investigations about this issue.

**Comment by Farwaykorse** [comment]
@acgetchell you can get Travis to print the contents of these files to the console.
Add to your .travis.yml:
````Bash
after_failure:
- |
  LOG_PATH='/Users/travis/build/acgetchell/CDT-plusplus/vcpkg/buildtrees/mpir/install-x64-osx-dbg-out.log'
  if [[ -e "${LOG_PATH}" ]]; then cat "${LOG_PATH}"; fi
- |
  LOG_PATH='/Users/travis/build/acgetchell/CDT-plusplus/vcpkg/buildtrees/mpir/install-x64-osx-dbg-err.log'
  if [[ -e "${LOG_PATH}" ]]; then cat "${LOG_PATH}"; fi
````

**Comment by NancyLi1013** [comment]
@acgetchell 
Could you help provide the error info in the way that @Farwaykorse said above?

**Comment by acgetchell** [comment]
Travis-CI has macOS 10.15 now so I don't see this issue anymore. Thanks for your attention!
