### ISSUE TITLE
curl: (35) Unknown SSL protocol error in connection to github.com:-9836 when installing ./bootstrap-vcpkg.sh on macOS Sierra (10.12.6)

### ISSUE THREAD

**Issue by CottonTheButton** [microsoft/vcpkg#11348]
**Describe the bug**

**Environment**
- OS: macOS
- Compiler: Apple LLVM version 9.0.0 (clang-900.0.39.2)

**To Reproduce**
1. git clone https://github.com/Microsoft/vcpkg.git
2. cd vcpkg
3. ./bootstrap-vcpkg.sh

**Expected behavior**
Um... I expected it to work :p

**Failure logs** 
curl: (35) Unknown SSL protocol error in connection to github.com:-9836

**Additional context**
Error Files:
[CMakeError.log](https://github.com/microsoft/vcpkg/files/4631200/CMakeError.log)
[CMakeOutput.log](https://github.com/microsoft/vcpkg/files/4631201/CMakeOutput.log)

https://pastebin.com/v0ApBamG

**Comment by CottonTheButton** [comment]
I get this when I do "sh path-to-the-.sh-file" https://pastebin.com/cyD6biC0

**Comment by CottonTheButton** [comment]
[CMakeError.log](https://github.com/microsoft/vcpkg/files/4626166/CMakeError.log)
[CMakeOutput.log](https://github.com/microsoft/vcpkg/files/4626167/CMakeOutput.log)

**Comment by strega-nil** [comment]
Unfortunately, we don't support macOS 10.12 anymore officially; you can try passing `-useSystemBinaries` after installing ninja 1.9, and you will also have to install g++ 9 from homebrew. We would also recommend upgrading to the latest macOS version if at all possible.
