### ISSUE TITLE
Add package SUNDIALS

### ISSUE THREAD

**Issue by fcooper8472** [Microsoft/vcpkg#1135]
SUNDIALS: SUite of Nonlinear and DIfferential/ALgebraic Equation Solvers

SUNDIALS is implemented with the goal of providing robust time integrators and nonlinear solvers that can easily be incorporated into existing simulation codes.

https://computation.llnl.gov/projects/sundials

**Comment by atkawa7** [comment]
@ras0219-msft Could you close this?
