### ISSUE TITLE
[google/libphonenumber] Google's common Java, C++ and JavaScript library for parsing, formatting, and validating international phone numbers.

### ISSUE THREAD

**Issue by flightgong** [microsoft/vcpkg#11350]
Library name: libphonenumber

Library description: Google's common Java, C++ and JavaScript library for parsing, formatting, and validating international phone numbers.

Source repository URL: https://github.com/google/libphonenumber/tree/master/cpp

Project homepage (if different from the source repository):

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
