### ISSUE TITLE
Automatically create patch from buildtree

### ISSUE THREAD

**Issue by zabulus** [microsoft/vcpkg#1136]
After tuning of buildtree sources to make it compile for selected triplet, I'd like to have an option to create .patch file from patched sources.
It should be some automatic call of git patch for detached source trees.

**Comment by ras0219-msft** [comment]
Thanks for the suggestion! This would definitely be useful.

Complications:
- Most ports (by design) directly download archives. This means we'd really need a tool which can diff the contents of a compressed archive against the files on disk.
- The files on disk might already contain patches, which need to be "subtracted" from the new patch.

**Comment by zabulus** [comment]
About second consideration. A contributor should manually subtract all not-needed changes. It's not so complicated, in patch changes are divided per file. If new changes are intersect with existing patches, in this case work more complicated, because you need to break a patch to separate patches.

**Comment by zabulus** [comment]
About first consideration. Implementation could use CRC32 for detecting what files have been changed and do unpack and diff only for these files

**Comment by KindDragon** [comment]
> Most ports (by design) directly download archives. This means we'd really need a tool which can diff the contents of a compressed archive against the files on disk -- ideally without doing a full extraction.

I think we can add an option to `vcpkg_from_github` to use shallow clone instead of downloading an archive, this will simplify patch creating. A user can apply already contain patches and commit them locally to subtract from further changes.

**Comment by Fleischner** [comment]
two options for the install command will help:
 --no-build                 only extracts package to the source tree
 --create-repo            creates git repo in source tree (as with the patch example)

additional command
 vcpkg patch packagename [patchname] --create                creates the patch (as with the patch example)

**Comment by MathiasMagnus** [comment]
May I add, whatever the solution is, a documentation section could greatly simplify the life of maintainers. I, for one, still have no clue how to create a patch without cloning the targeted repo, committing the changes I made in Vcpkg, and even then, I'd still have to figure out how to create the patch file.

So whatever this discussion boils down to, if there would be an official recommendation in the docs, that would be great. The current document solely describes applying patches, but not creating them.

**Comment by JackBoosY** [comment]
@MathiasMagnus  the document has updated yet. Thanks for advice.

**Comment by PhoebeHui** [comment]
See docs
https://github.com/microsoft/vcpkg/blob/master/docs/examples/patching.md#patching-the-code-to-improve-compatibility
