### ISSUE TITLE
 Add package libtiff 4.0.7 zlib 1.2.11 libjpeg 9b ...

### ISSUE THREAD

**Issue by Voskrese** [Microsoft/vcpkg#1137]
Существует проект
https://github.com/peirick/VS2015_Tesseract
отлично собирается под "Microsoft Visual Studio 14.0"

build_tesseract.bat
либо
`cmd /k ""C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"" x86` \x64
`msbuild tesseract.sln /p:Configuration=Release /p:Platform=x86`\x64
```
tree /F
    giflib.lib
    jbig2enc.exe
    jbig2enc.pdb
    libjpeg.lib
    liblept.lib
    libpng.lib
    libtesseract.lib
    libtiff.lib
    libwebp.lib
    openjpeg.lib
    tesseract.exe
    tesseract.pdb
    zlib.lib
```

total 125400
-rw-r--r-- 1 Nikolay 197609    570858 May 22 16:53 giflib.lib
-rwxr-xr-x 1 Nikolay 197609   1745408 May 22 16:56 jbig2enc.exe
-rw-r--r-- 1 Nikolay 197609  12742656 May 22 16:56 jbig2enc.pdb
-rw-r--r-- 1 Nikolay 197609   4474356 May 22 16:53 libjpeg.lib
-rw-r--r-- 1 Nikolay 197609  22065016 May 22 16:54 liblept.lib
-rw-r--r-- 1 Nikolay 197609   2824428 May 22 16:54 libpng.lib
-rw-r--r-- 1 Nikolay 197609 189153654 May 22 17:00 libtesseract.lib
-rw-r--r-- 1 Nikolay 197609   5184562 May 22 16:54 libtiff.lib
-rw-r--r-- 1 Nikolay 197609   3469104 May 22 16:52 libwebp.lib
-rw-r--r-- 1 Nikolay 197609   3116944 May 22 16:52 openjpeg.lib
-rwxr-xr-x 1 Nikolay 197609   3416064 May 22 17:03 tesseract.exe
-rw-r--r-- 1 Nikolay 197609  22401024 May 22 17:03 tesseract.pdb

-rw-r--r-- 1 Nikolay 197609    **757324** May 22 16:52 **zlib.lib**

обращаю внимание на размеры, тот же zlib.lib по размеру в десять раз больше чем у порта существющего здесь

_Суть сего поста,_  **добавьте пжлт в порт отсутствующее программы**
_Libraries
    Giflib 5.1.4
    libtiff 4.0.7
    zlib 1.2.11
    libpng 1.6.28
    libjpeg 9b
    OpenJPEG 2.1.2
    jbig2enc 0.28
    webp master_

**Comment by Mixaill** [comment]
>обращаю внимание на размеры, тот же zlib.lib по размеру в десять раз больше чем у порта существющего здесь

абсолютно ничего не значит :) 

> добавьте пжлт в порт отсутствующее программы

- [x] giflib
- [x] libtiff
- [x] zlib
- [x] libpng
- [x] webp
- [ ] libjpeg
- [ ] OpenJPEG
- [ ] jbig2enc

**Comment by Mixaill** [comment]
Translation of original post:
----------

There is a project https://github.com/peirick/VS2015_Tesseract which perfectly builds under "Microsoft Visual Studio 14.0" :

* `build_tesseract.bat`
or
* `cmd /k ""C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"" x86\x64
msbuild tesseract.sln /p:Configuration=Release /p:Platform=x86\x64`

```
E:\tools\SRC\VS2015_Tesseract\Release>tree /F
giflib.lib
jbig2enc.exe
jbig2enc.pdb
libjpeg.lib
liblept.lib
libpng.lib
libtesseract.lib
libtiff.lib
libwebp.lib
openjpeg.lib
tesseract.exe
tesseract.pdb
zlib.lib

total 125400
-rw-r--r-- 1 Nikolay 197609 570858 May 22 16:53 giflib.lib
-rwxr-xr-x 1 Nikolay 197609 1745408 May 22 16:56 jbig2enc.exe
-rw-r--r-- 1 Nikolay 197609 12742656 May 22 16:56 jbig2enc.pdb
-rw-r--r-- 1 Nikolay 197609 4474356 May 22 16:53 libjpeg.lib
-rw-r--r-- 1 Nikolay 197609 22065016 May 22 16:54 liblept.lib
-rw-r--r-- 1 Nikolay 197609 2824428 May 22 16:54 libpng.lib
-rw-r--r-- 1 Nikolay 197609 189153654 May 22 17:00 libtesseract.lib
-rw-r--r-- 1 Nikolay 197609 5184562 May 22 16:54 libtiff.lib
-rw-r--r-- 1 Nikolay 197609 3469104 May 22 16:52 libwebp.lib
-rw-r--r-- 1 Nikolay 197609 3116944 May 22 16:52 openjpeg.lib
-rwxr-xr-x 1 Nikolay 197609 3416064 May 22 17:03 tesseract.exe
-rw-r--r-- 1 Nikolay 197609 22401024 May 22 17:03 tesseract.pdb

-rw-r--r-- 1 Nikolay 197609 757324 May 22 16:52 zlib.lib
```

Pay attention to the file sizes, `zlib.lib` is ten times larger than vcpkg's one.

The essence of this post: please add ports for missing libraries:

```
Giflib 5.1.4
libtiff 4.0.7
zlib 1.2.11
libpng 1.6.28
libjpeg 9b
OpenJPEG 2.1.2
jbig2enc 0.28
webp master
```

**Comment by KindDragon** [comment]
Related to #687

**Comment by KindDragon** [comment]
> libjpeg

https://github.com/Microsoft/vcpkg/tree/master/ports/libjpeg-turbo

> OpenJPEG

https://github.com/Microsoft/vcpkg/tree/master/ports/openjpeg

**Comment by KindDragon** [comment]
I think it can be closed as duplicate of #465

**Comment by Voskrese** [comment]
вдруг кому пригодится, вот здесь как я понял полная версия со всеми исправлениями

Visual Studio 2015 Projects for Tessearct and dependencies.
https://github.com/vdevan/TesseractTrainingTools

**Comment by Voskrese** [comment]
[new] port request: `libtesseract `+ `leptonica`

**Comment by KindDragon** [comment]
@Voskrese Why you reopen this issue? We already have issue #465 about Tesseract, just vote for it

**Comment by Voskrese** [comment]
@KindDragon а ну ок) запамятовал, подумал что нет открытых

> well OK) forgot, thought no open, close

**Comment by Voskrese** [comment]
@KindDragon как на счет `leptonica` ? это обособленная библиотека

> What about leptonica? This is a separate library
