### ISSUE TITLE
[abseil] build failure

### ISSUE THREAD

**Issue by suhao** [microsoft/vcpkg#11372]
**Host Environment**

- OS: windows10 desktop
- Compiler: arm-uwp

**To Reproduce**

`./vcpkg install --recurse abseil:arm-uwp`

**Failure logs** 
|item|message|
|-|-|
|file| [absl/time/internal/cctz/src/zone_info_source.cc](https://github.com/abseil/abseil-cpp/blob/master/absl/time/internal/cctz/src/zone_info_source.cc)
|error| fatal error C1189: #error:  Unsupported MSVC platform

```
#if defined(_M_IX86)
#elif defined(_M_IA_64) || defined(_M_AMD64) || defined(_M_ARM64)
#else
#error Unsupported MSVC platform
#endif  // _M_<PLATFORM>
```

No code here to capture **_M_ARM**

**Additional context**

I had try to modify with a [patch to capture **_M_ARM**](https://github.com/suhao/pkg/commit/c1cd17dd2b9982e9686b73236e8b587f7239808f) which just to confirm that it can be compiled through.  I am not sure if this condition is handled correctly. 

Hope that friends who are good at ARM-UWP could give a good solution to solve this error.  Thank you!

```
From 5968dc74a7b3c326387db1d985e0f5eb0c3d273f Mon Sep 17 00:00:00 2001
Subject: [PATCH 12/12] ARM-UWP
Url: https://github.com/suhao/pkg/commit/c1cd17dd2b9982e9686b73236e8b587f7239808f
---
 absl/time/internal/cctz/src/zone_info_source.cc | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/absl/time/internal/cctz/src/zone_info_source.cc b/absl/time/internal/cctz/src/zone_info_source.cc
index 98ea161..a155fe8 100644
--- a/absl/time/internal/cctz/src/zone_info_source.cc
+++ b/absl/time/internal/cctz/src/zone_info_source.cc
@@ -83,7 +83,7 @@ ZoneInfoSourceFactory default_factory = DefaultFactory;
     "@@U?$default_delete@VZoneInfoSource@cctz@time_internal@" ABSL_INTERNAL_MANGLED_NS                                   \
     "@@@std@@@std@@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@2@@Z@" ABSL_INTERNAL_MANGLED_BACKREFERENCE \
     "@@ZA")
-#elif defined(_M_IA_64) || defined(_M_AMD64) || defined(_M_ARM64)
+#elif defined(_M_IA_64) || defined(_M_AMD64) || defined(_M_ARM64) || defined(_M_ARM)
 #pragma comment(                                                                                                          \
     linker,                                                                                                               \
     "/alternatename:?zone_info_source_factory@cctz_extension@time_internal@" ABSL_INTERNAL_MANGLED_NS                     \
-- 
2.26.0.windows.1
```

**Comment by JackBoosY** [comment]
Confirmed.

**Comment by JackBoosY** [comment]
@suhao Could you report this issue to the upstream so that we can merge this changes into vcpkg?

Thanks.

**Comment by suhao** [comment]
@JackBoosY I had report this issue to the upstream. Abseil had fixed this issue. Thank you!


fixed link: https://github.com/abseil/abseil-cpp/issues/694

**Comment by JackBoosY** [comment]
Since the upstream accept this changes, I will open a PR to fix it in vcpkg and remove it in next update.
