### ISSUE TITLE
[realsense2] build failure

### ISSUE THREAD

**Issue by bcrespy** [microsoft/vcpkg#11374]
**Host Environment**
- OS: Windows 10
- Compiler: MSVS2017

**To Reproduce**
`./vcpkg install realsense2`

**Failure logs** 
`Error: Building package realsense2:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: realsense2:x86-windows
  Vcpkg version: 2020.02.04-nohash`
[install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/4633872/install-x86-windows-dbg-out.log)

**Additional context**
I have installed the english version of MSVS2017, Windows 10 SDK, I am kinda stuck now and don't know what to do. I attached all the logs, I couldn't find a clue about this issue within the log.

Thanks for your time

**Comment by suhao** [comment]
Please forgive me for taking the time to disturb you.

I found the error from the log:
```
c:\vcpkg\buildtrees\realsense2\src\dbc1bebf69-5a1aac81b3\src\winusb\device-winusb.h(14): fatal error C1083: Cannot open include file: 'atlstr.h': No such file or directory
```

## Maybe you had missed ATL SDK or something.

When running the Visual Studio Installer, select the Individual components tab, and under SDKs, libraries, and frameworks make sure Visual C++ ATL Support is selected.

![image](https://user-images.githubusercontent.com/24261214/82044974-dfcfce00-96e0-11ea-8b6d-f35fb8fe14a6.png)

## Installed "Visual C++ ATL support" and MFC and ATL support. The error still occurred in our x64 project.

You could try to fix some paths with the following two commands:
```
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC>mklink /d atlmfc "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\atlmfc"
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\atlmfc\lib>mklink /d amd64 "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\atlmfc\lib\x64
```

## More
Here are some links that helped me investigate your issue:
* http://stackoverflow.com/a/16404536/796832
* https://groups.google.com/forum/#!topic/microsoft.public.vc.language/pUU-NM4RRhA

**Comment by bcrespy** [comment]
> Please forgive me for taking the time to disturb you.
I don't understand what you meant by saying this, however **thanks for helping me and pointing out the issue, which is now solved. Thanks a lot !!**
