### ISSUE TITLE
[tinyxml] Use proper CMake Targets

### ISSUE THREAD

**Issue by Electric-Turtle** [microsoft/vcpkg#11382]
****

**Is your feature request related to a problem? Please describe.**
The current version of the tinyxml port doesn't actually differentiate between the debug and release library that it builds in it's tinyxml-config.cmake file.  It _always_ put the release version into the tinyxml_LIBRARIES variable:
[configfileisbugged](https://github.com/microsoft/vcpkg/blob/5504dfa7da38a65981868fc7885744ac5d8f234e/ports/tinyxml/tinyxml-config.cmake#L11)

For now, most dependencies of TinyXML have been "getting away with it", as people typically just write their own FindTinyXML.cmake script that sidesteps the problem.  But if you genuinely use the tinyxml_LIBRARIES variable set by this port as a link library for a Debug build configuration, you will (at least on Windows) get a linker error when the linker does what you ask and tries to link a pre-built Release library into a Debug library.

**Proposed solution**
Use proper exported targets as the CMake gods intended.  Export a target (perhaps named tinyxml::tinyxml to follow the convention used in tinyxml2) that includes the appropriate libraries and include directories for the current build type.

**Describe alternatives you've considered**
One could always just ignore the tinyxml-config.cmake file and just write your own FindTinyXML script, but this is hacky.

**Additional context**
None presently identified.

**Comment by Electric-Turtle** [comment]
I have fixed the issue in my personal fork of vcpkg, will be opening a pull request soon.

**Comment by traversaro** [comment]
To complement on this, typically all the port that install CMake config files that are not already install under upstream, install them under a clearly different name, such as `unofficial-tinyxml`  to avoid confusion to downstream users, especially to make sure that downstream users do not accidentally rely on a behaviour that is available in vcpkg but not if the same dependency is installed in a system with a different package manager. 

Unfortunately, this was not done with tinyxml's vcpkg port, and indeed it created problems, see https://github.com/robotology/ycm/pull/296 .
