### ISSUE TITLE
[vcpkg] use CMake Kitware vs fork microsoft

### ISSUE THREAD

**Issue by Voskrese** [microsoft/vcpkg#11384]
Actually the question is, is it better to use forked microsoft to build **android** and tools **clang** applications under **WINDOWS** ?

statically linked binaries https://github.com/microsoft/CMake

__________

In addition

[cmake-3.17.3587832-MSVC_2-Linux-arm.sh - Linux - ARMv6+ - 32 bit version](https://github.com/microsoft/CMake/releases/download/v3.17.3587832/cmake-3.17.3587832-MSVC_2-Linux-arm.sh)

https://docs.microsoft.com/en-us/cpp/build/get-started-linux-cmake?view=vs-2019

example
`sudo ./cmake-3.11.18033000-MSVC_2-Linux-x86_64.sh --skip-license --prefix=/usr`

**Comment by strega-nil** [comment]
I don't want to use a non-standard CMake fork.

**Comment by Voskrese** [comment]
@strega-nil 
it is clear that many edits will affect the build, but the one above is installed with MSVC

I just wanted to hear the opinion of users who compile this build for  WSL/GGC and Android
