### ISSUE TITLE
[angle] build failure with VS 2017 vc141 fatal error C1001: An internal error has occurred in the compiler

### ISSUE THREAD

**Issue by timautry** [microsoft/vcpkg#11387]
**Host Environment**
- OS: [Microsoft Windows [Version 10.0.18363.836]]
- Compiler: Visual Studio 2017 Version: 15.9.23  VS Tools Version: 14.16.27023

**To Reproduce**
`SYSTEM@ANDROMEDA 05/15/2020 17:30:09 D:\Git\vs2017.prod`
`->.\vcpkg.exe install angle[core]:x64-windows`

**Failure logs** 
- Cut and past the appropriate build messages from the console output.
`Computing installation plan...`
`The following packages will be built and installed:`
`    angle[core]:x64-windows`
`Starting package 1/1: angle:x64-windows`
`Building package angle[core]:x64-windows...`
`-- Using cached D:/Git/vcpkg.downloads/google-angle-1fdf6ca5141d8e349e875eab6e51d93d929a7f0e.tar.gz`
`-- Extracting source D:/Git/vcpkg.downloads/google-angle-1fdf6ca5141d8e349e875eab6e51d93d929a7f0e.tar.gz`
`-- Applying patch 001-fix-uwp.patch`
`-- Applying patch 002-fix-builder-error.patch`
`-- Using source at D:/Git/vs2017.prod/buildtrees/angle/src/3d929a7f0e-ac85ee4a0e`
`-- Configuring x64-windows`
`-- Building x64-windows-dbg`
`CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):`
`    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v`
`    Working Directory: D:/Git/vs2017.prod/buildtrees/angle/x64-windows-dbg`
`    See logs for more information:`
`      D:\Git\vs2017.prod\buildtrees\angle\install-x64-windows-dbg-out.log`

` Call Stack (most recent call first):`
`  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)`
`  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)`
`  ports/angle/portfile.cmake:40 (vcpkg_install_cmake)`
`  scripts/ports.cmake:90 (include)`

`Error: Building package angle:x64-windows failed with: BUILD_FAILED`
`Please ensure you're using the latest portfiles with .\vcpkg update then`
`submit an issue at https://github.com/Microsoft/vcpkg/issues including:`
`  Package: angle:x64-windows`
`  Vcpkg version: 2020.02.04-nohash-external`

Additionally, attach any relevant sections from the log files above.

- Please attach any additional failure logs mentioned in the console output.
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/4637227/install-x64-windows-dbg-out.log)

**Additional context**
VS 2019 toolset v142 - port installs successfully.

Seems **an internal error has occurred in the compiler** has somehow been introduced with the change from 15.9.22 to 15.9.23 as this was working prior to 15.9.23 update :(

D:\Git\vs2017.test\buildtrees\angle\src\3d929a7f0e-ac85ee4a0e\src\compiler\translator\SymbolTable_ESSL_autogen.cpp(1761): **fatal error C1001: An internal error has occurred in the compiler.**
(compiler file 'msc1.cpp', line 1518)
 To work around this problem, try simplifying or changing the program near the locations listed above.
Please choose the Technical Support command on the Visual C++ 
 Help menu, or open the Technical Support help file for more information
Internal Compiler Error in `C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe.`  You will be prompted to send an error report to Microsoft later.
INTERNAL COMPILER ERROR in `C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe`
    Please choose the Technical Support command on the Visual C++
    Help menu, or open the Technical Support help file for more information

I thought I saw the same issue on some ports being compiled in VS2019 v142 - wonder if MS has somehow introduced this same bug into VS 2017?

**Comment by NancyLi1013** [comment]
Hi @timautry 
Thanks for posting this issue.

This is a compiler bug. Since this issue doesn't exist on Visual Studio 2019. We suggest that use Visual Studio 2019 to build `angle`.

**Comment by timautry** [comment]
@NancyLi1013 will this be reported upstream to microsoft, as I tried but only having community edition there is not support?
Cc @JackBoosY @strega-nil

**Comment by strega-nil** [comment]
You should be able to report issues here: https://developercommunity.visualstudio.com/content/problem/post.html?space=62

However, since we can't do anything about this, I'm going to close this issue. Sorry!

**Comment by timautry** [comment]
We have the same issue with vs2019 and the ace port, and it stays open and port owner figures out a way to fix because a corporate partner had the issue? 
I tried to contact support it was rejected because I use community, needed to purchase a support plan before I could log an issue.
I thought the vcpkg team would be so nice and report the issue upstream like on so many other port issues.

**Comment by timautry** [comment]
Also this needs to stay open as an fyi for others who may run across the same issue.

**Comment by timautry** [comment]
Thank you again @strega-nil...

**Comment by timautry** [comment]
I am closing this as it is not a vcpkg issue and visual studio team says it is a cmake issue.
