### ISSUE TITLE
[vcpkg] support EWDK

### ISSUE THREAD

**Issue by Voskrese** [microsoft/vcpkg#11392]
Is it possible to organize full support **Enterprise WDK** (EWDK)?

https://docs.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk

full portable ISO image !

ENV
```
EnterpriseWDK=true
DisableRegistryUse=true
```

run `LaunchBuildEnv`

> The EWDK is a standalone, self-contained command-line environment for building drivers. It includes the Visual Studio Build Tools, the SDK, and the WDK. The latest public version of the EWDK contains Visual Studio 2019 Build Tools 16.3.0 and MSVC toolset v14.23. To get started, mount the ISO and run LaunchBuildEnv.

**Comment by strega-nil** [comment]
If you would like to add this feature, we can absolutely support this, but it's not something we're interested in putting developer time into right now :)

**Comment by thxkiwi** [comment]
This support is something I'd greatly appreciate and I'm happy to do the work to make it happen. Linking this to another issue and the corresponding discussion 

https://github.com/microsoft/vcpkg/issues/27446

https://github.com/microsoft/vcpkg/discussions/27449
