### ISSUE TITLE
initialize-environment.ps1 failing windows builds

### ISSUE THREAD

**Issue by isanych** [microsoft/vcpkg#11395]
**Describe the bug**
All my latest pull requests requests failing on windows during environment initialization:

https://dev.azure.com/vcpkg/public/_build/results?buildId=36974&view=logs&j=878666d5-db33-5b27-9e7d-b0c7ee352005&t=74aefe2a-c21b-52a4-9295-f464e377cc01&l=28
```
Linking downloads => D:\downloads
##[error]C:\agent\_work\1\s\scripts\azure-pipelines\windows\initialize-environment.ps1 : Exception calling "Delete" with "1" 
##[error]argument(s): "The directory is not empty.
"
At C:\agent\_work\_temp\f631f658-541a-4f38-b5be-3d80e71b5a09.ps1:3 char:1

##[error]+ . 'C:\agent\_work\1\s\scripts\azure-pipelines\windows\initialize-envi ...

##[error]+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

##[error]    + CategoryInfo          : NotSpecified: (:) [initialize-environment.ps1], MethodInvocationException

##[error]    + FullyQualifiedErrorId : IOException,initialize-environment.ps1

##[error] 

##[error]PowerShell exited with code '1'.
```
And I see the same error in other PRs too - https://dev.azure.com/vcpkg/public/_build/results?buildId=36980&view=logs&j=3859ca13-59fe-57bd-13f9-449df7d191a6&t=cca7a5dc-b423-5664-9a84-dcceb853785f&l=39

**Comment by Voskrese** [comment]
@BillyONeal 
something broke, the build is successful or not

**Comment by PhoebeHui** [comment]
@BillyONeal, this issue tends to disappear after rerun, however, I noticed it occurred for serveral times, could you help have a look?

**Comment by Voskrese** [comment]
@PhoebeHui work delete recurs
https://github.com/microsoft/vcpkg/pull/11409

**Comment by PhoebeHui** [comment]
@Voskrese, thanks for the PR! Let's see if it fix this issue.

**Comment by BillyONeal** [comment]
We must have accepted a port or similar recently that's leaving some files locked after a run. Or I damaged the job object stuff....
