### ISSUE TITLE
[sfml] x64-wincustom-static build failure

### ISSUE THREAD

**Issue by jabra11** [microsoft/vcpkg#11391]
**Host Environment**
- OS: windows 10
- Compiler: latest msvc

**To Reproduce**
`./vcpkg install sfml
```
**Failure logs** 
Starting package 2/2: sfml:x64-wincustom-static
Building package sfml[core]:x64-wincustom-static...
-- Downloading https://github.com/SFML/SFML/archive/2.5.1.tar.gz...
-- Extracting source D:/Libs/testvcpkg/vcpkg/downloads/SFML-SFML-2.5.1.tar.gz
-- Applying patch use-system-freetype.patch
-- Using source at D:/Libs/testvcpkg/vcpkg/buildtrees/sfml/src/2.5.1-f499a1097e
-- Configuring x64-wincustom-static
-- Building x64-wincustom-static-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v
    Working Directory: D:/Libs/testvcpkg/vcpkg/buildtrees/sfml/x64-wincustom-static-dbg
    See logs for more information:
      D:\Libs\testvcpkg\vcpkg\buildtrees\sfml\install-x64-wincustom-static-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/sfml/portfile.cmake:31 (vcpkg_install_cmake)
  scripts/ports.cmake:90 (include)


Error: Building package sfml:x64-wincustom-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: sfml:x64-wincustom-static
  Vcpkg version: 2020.02.04-nohash
```
Additionally, attach any relevant sections from the log files above.
[install-x64-wincustom-static-dbg-out.log](https://github.com/microsoft/vcpkg/files/4638019/install-x64-wincustom-static-dbg-out.log)

**Additional context**
I'm using a custom triplet which looks like this: 
```
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)

if(${PORT} MATCHES "qt5-|sfml")
    set(VCPKG_LIBRARY_LINKAGE dynamic)
else()
    set(VCPKG_LIBRARY_LINKAGE static)
endif()
```
The build with this triplet works at this commit: https://github.com/microsoft/vcpkg/commit/28ab0b15cd7cdc1004cac9a28a5ecab198c161b9

**Comment by timautry** [comment]
- From the log install-x64-wincustom-static-dbg-out.log 
`   Creating library lib\sfml-audio-d.lib and object lib\sfml-audio-d.exp`
`OpenAL32.lib(winmm.obj) : error LNK2019: unresolved external symbol __imp_waveOutGetNumDevs referenced in function "void __cdecl 'anonymous namespace'::ProbePlaybackDevices(void)" (?ProbePlaybackDevices@?A0x0e5760ab@@YAXXZ)`
`OpenAL32.lib(winmm.obj) : error LNK2019: unresolved external symbol __imp_waveutGetDevCapsW referenced in function "void __cdecl 'anonymous namespace'::ProbePlaybackDevices(void)" (?ProbePlaybackDevices@?A0x0e5760ab@@YAXXZ)`
`OpenAL32.lib(winmm.obj) : error LNK2019: unresolved external symbol __imp_waveOutOpen referenced in function "public: virtual void __cdecl 'anonymous namespace'::WinMMPlayback::open(char const *)" (?open@WinMMPlayback@?A0x0e5760ab@@UEAAXPEBD@Z)`
etc etc etc ...

- Looks like the SFML build can not find OpenAL.
- Is the port openal-soft port installed?

**Comment by jabra98** [comment]
Yes, the openal-soft package is installed

**Comment by timautry** [comment]
Was the openal-soft package installed by the same custom triplet?
Possibly it could be static versus dynamic?
Custom triplets sometimes are not too reliable.

**Comment by jabra98** [comment]
It was installed by the same custom triplet, I just wonder what could have broken it since https://github.com/microsoft/vcpkg/commit/28ab0b15cd7cdc1004cac9a28a5ecab198c161b9

**Comment by timautry** [comment]
I am at a loss of what else to try?
I can see last week SFML was changed to remove a no longer needed patch, and OpenSoftAL has not changed in months.
I have not experienced any issues installing SFML compiling dynamic it was changed and unfortunately I do not use QT5.
Hopefully someone else may be able to provide you with assistance.

**Comment by sandsmark** [comment]
from a quick glance the "not needed patch" was not arm specific, how was it verified that it was safe to drop the patch?

there's some static library related stuff in it, so I guess just reverted the commit removing it should probably fix this.

**Comment by sandsmark** [comment]
https://ci.appveyor.com/project/sandsmark/freeaoe/builds/33753443?fullLog=true#L1066 here's the full build log of openal failing to build statically

**Comment by sandsmark** [comment]
in case someone else needs it, I fixed my CI by reverting the commit that broke openal by running this at the start (on appveyor):

```
cd c:\tools\vcpkg\
git reset --hard origin/master
git pull
git revert -n cc3ba82ae15fae6428c94ab013f298f56188ef94
bootstrap-vcpkg.bat
```

I don't have any windows machines so I'm not comfortable opening a PR without testing it, but imho the commit should just be reverted (if I'm reading it correctly it didn't actually update openal, it just broke the static build by removing the patch)

**Comment by JackBoosY** [comment]
`sfml-audio-d-2.dll` should link to `winmm.lib`.

**Comment by JackBoosY** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
