### ISSUE TITLE
boost:arm-uwp fails to build

### ISSUE THREAD

**Issue by stoperro** [Microsoft/vcpkg#1139]
On clean clone
`vcpkg.exe install boost:arm-uwp`
fails with:
```
-- Building arm-uwp-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process_repeat.cmake:21 (message):
    Command failed: F:/vcpkg_boost_arm_uwp/buildtrees/boost/src/boost_1_64_0/b2.exe;--stagedir=F:/vcpkg_boost_arm_uwp/buildtrees/boost/arm-uwp-rel/stage;--build-dir=F:/vcpkg_boost_arm_uwp/buildtrees/boost/arm-uwp-rel;-sZLIB_INCLUDE="F:/vcpkg_boost_arm_uwp/installed/arm-uwp\include";-sBZIP2_INCLUDE="F:/vcpkg_boost_arm_uwp/installed/arm-uwp\include";-j8;--debug-configuration;--hash;-q;--without-python;threading=multi;runtime-link=shared;link=shared;windows-api=store;--without-type_erasure;--without-log;--without-mpi;--without-wave;--without-coroutine;--without-metaparse;--without-locale;--without-timer;--without-program_options;--without-test;--without-filesystem;--without-thread;--without-iostreams;--without-container;toolset=msvc-14.1;-sZLIB_BINARY=zlib;-sZLIB_LIBPATH="F:/vcpkg_boost_arm_uwp/installed/arm-uwp\lib";-sBZIP2_BINARY=bz2;-sBZIP2_LIBPATH="F:/vcpkg_boost_arm_uwp/installed/arm-uwp\lib";variant=release;debug-symbols=on
    Working Directory: F:/vcpkg_boost_arm_uwp/buildtrees/boost/src/boost_1_64_0
    See logs for more information:
      F:\vcpkg_boost_arm_uwp\buildtrees\boost\build-arm-uwp-rel-out.log
      F:\vcpkg_boost_arm_uwp\buildtrees\boost\build-arm-uwp-rel-err.log

Call Stack (most recent call first):
  ports/boost/portfile.cmake:188 (vcpkg_execute_required_process_repeat)
  scripts/ports.cmake:73 (include)

Error: Building package boost:arm-uwp failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost:arm-uwp
  Vcpkg version: 0.0.81-fb689bd13dd6ba563a885d71fff1dd2b32a615db
```

I've noticed 3 problems:

1. Bootstrap tries to compile B2 for ARM platform (which my PC isn't)
2. Boost.Config tries to run test applications that are for ARM
3. Boost.Thread doesn't compile and while it's removed from compilation, Boost.Context and Boost.Coroutine2 has dependency to it - so it's compiled anyway

[boost-arm-uwp-rel.zip](https://github.com/Microsoft/vcpkg/files/1019637/boost-arm-uwp-rel.zip)

For 1. there is a simple WA - first build e.g. boost:x64-windows, this will create b2 binary that seems to be reused for e.g. ARM targets.
For 2. one can just click message boxes that pop up. This results in Boost thinking that some compiler features are not present, I assume what will cause issues later, but at least it allows moving forward...
For 3. when Boost.Context and Boost.Coroutine2 is removed for compilation targeting ARM, build succeeds with other targets:
[boost_arm_uwp_no_thread.zip](https://github.com/Microsoft/vcpkg/files/1019598/boost_arm_uwp_no_thread.zip)

I think Boost doesn't realize it's supposed to do cross compilation, and when cross compiling, running binaries compiled for target (not host) won't work. Those might be Boost issues, but at least workarounds above allowed me to build Boost for ARM UWP with the current state of it...

**Comment by congzhangzh** [comment]
I have the same problem too:)

**Comment by stoperro** [comment]
With newest vcpkg version, I've tried now to compile Boost from scratch on clean vcpkg directory and it works :) I think the issue can be closed.
The command is:
`vcpkg install boost-build:x86-windows && vcpkg install boost:arm-uwp`
but user is warned about missing boost-build and what to do, so it's fine.

**Comment by JackBoosY** [comment]
Hi @stoperro Thanks for reporting this issue!
I found nothing wrong with build boost:arm-uwp in latest version(v1.69.0), could you update vcpkg and repro it?
Thx.

**Comment by JackBoosY** [comment]
Please open a new issue if this is still a problem for you.
Thx.
