### ISSUE TITLE
[boost-math] build failure

### ISSUE THREAD

**Issue by shadowindcc** [microsoft/vcpkg#11400]
**Host Environment**
- OS: Windows 10
- Compiler: revision

**To Reproduce**
`./vcpkg install boost-math`

**Failure logs** 
PS D:\Project\vcpkg> .\vcpkg.exe install boost-math
Computing installation plan...
The following packages will be built and installed:
    boost-math[core]:x86-windows
Starting package 1/1: boost-math:x86-windows
Building package boost-math[core]:x86-windows...
-- Using cached D:/Project/vcpkg/downloads/boostorg-math-boost-1.73.0.tar.gz
-- Extracting source D:/Project/vcpkg/downloads/boostorg-math-boost-1.73.0.tar.gz
CMake Error at scripts/cmake/vcpkg_extract_source_archive_ex.cmake:140 (file):
  file RENAME failed to rename

    D:/Project/vcpkg/buildtrees/boost-math/src/TEMP/math-boost-1.73.0

  to

    D:/Project/vcpkg/buildtrees/boost-math/src/ost-1.73.0-0b998d205c

  because: No such file or directory

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:139 (vcpkg_extract_source_archive_ex)
  ports/boost-math/portfile.cmake:3 (vcpkg_from_github)
  scripts/ports.cmake:90 (include)

Error: Building package boost-math:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-math:x86-windows
  Vcpkg version: 2020.02.04-nohash

Additionally, attach any relevant sections from the log files above.
[x86-windows.vcpkg_abi_info.txt](https://github.com/microsoft/vcpkg/files/4639206/x86-windows.vcpkg_abi_info.txt)

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/8199
