### ISSUE TITLE
[New Port Request] isl Integer Set Library

### ISSUE THREAD

**Issue by vmiheer** [microsoft/vcpkg#11402]
Library name: isl (Integer Set Library)

Library description: Integer Set Library

Source repository URL: http://isl.gforge.inria.fr/
Binary repository URL: https://osdn.net/projects/mingw/releases/69300

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by vmiheer** [comment]
```powershell
.\vcpkg.exe create isl http://isl.gforge.inria.fr/isl-0.22.1.tar.bz2 isl-0.22.1.tar.bz2
.\vcpkg.exe edit isl
.\vcpkg.exe build isl
```
I get error:
```
Value was null
```
Can someone help?

**Comment by vmiheer** [comment]
I tried to fiddle with it and seems like:
1. The `build` command is absolute? `install` seemed to work?
2. Best and fastest way to get this thing up and running would be downloading it from https://osdn.net/projects/mingw/releases/ (from msys) as it needs to configure and gnu-ld and stuff, much faster to download binary instead?

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
