### ISSUE TITLE
[spdlog] update to 1.6.0

### ISSUE THREAD

**Issue by JeanPhilippeKernel** [microsoft/vcpkg#11401]
Library name: spdlog

New version number: 1.6.0

Other information that may be useful (release notes, etc...)
https://github.com/gabime/spdlog/releases/tag/v1.6.0

**Comment by NancyLi1013** [comment]
Hi @JeanPhilippeKernel 
Thanks for posting this issue.
The update for spdlog has been mentioned in PR #10931. So let's track this issue there.
