### ISSUE TITLE
Build issue while building atkmm

### ISSUE THREAD

**Issue by licon** [microsoft/vcpkg#11418]
I have trouble building gtkmm:

Computing installation plan...
The following packages will be built and installed:
  * atkmm[core]:x64-windows
  * bzip2[core]:x64-windows
  * cairo[core]:x64-windows
  * cairomm[core]:x64-windows
  * dirent[core]:x64-windows
  * expat[core]:x64-windows
  * fontconfig[core]:x64-windows
  * freetype[bzip2,core,png]:x64-windows
  * gdk-pixbuf[core]:x64-windows
  * gtk[core]:x64-windows
    gtkmm[core]:x64-windows
  * harfbuzz[core,glib,ucdn]:x64-windows
  * libepoxy[core]:x64-windows
  * libpng[core]:x64-windows
  * pango[core]:x64-windows
  * pangomm[core]:x64-windows
  * pixman[core]:x64-windows
  * ragel[core]:x64-windows
  * tool-meson[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/19: atkmm:x64-windows
Building package atkmm[core]:x64-windows...
-- Using cached D:/software/vcpkg/downloads/atkmm-2.24.2.tar.xz
-- Using source at D:/software/vcpkg/buildtrees/atkmm/src/atkmm-2-de808b48b0
-- Building D:/software/vcpkg/buildtrees/atkmm/src/atkmm-2-de808b48b0/MSVC_Net2013/atkmm.sln for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: msbuild D:/software/vcpkg/buildtrees/atkmm/src/atkmm-2-de808b48b0/MSVC_Net2013/atkmm.sln /p:Configuration=Release /t:atkmm /p:Platform=x64 /p:PlatformToolset=v142 /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /p:WindowsTargetPlatformVersion=10.0.18362.0 /m /p:ForceImportBeforeCppTargets=D:/software/vcpkg/scripts/buildsystems/msbuild/vcpkg.targets /p:VcpkgTriplet=x64-windows
    Working Directory: D:/software/vcpkg/buildtrees/atkmm/x64-windows-rel
    Error code: 1
    See logs for more information:
      D:\software\vcpkg\buildtrees\atkmm\build-x64-windows-rel-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_msbuild.cmake:119 (vcpkg_execute_required_process)
  ports/atkmm/portfile.cmake:25 (vcpkg_build_msbuild)
  scripts/ports.cmake:90 (include)

Error: Building package atkmm:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: atkmm:x64-windows
  Vcpkg version: 2020.02.04-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by timautry** [comment]
@licon  please attach the `D:\software\vcpkg\buildtrees\atkmm\build-x64-windows-rel-out.log` file so the issue can be looked at.

**Comment by LilyWangL** [comment]
Pinging... @licon

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
