### ISSUE TITLE
[usd] build failure on Linux

### ISSUE THREAD

**Issue by shauser67** [microsoft/vcpkg#11419]
**Host Environment**
- OS: Ubuntu 20.04
- Compiler: gcc 9.3.0

**To Reproduce**
`./vcpkg --triplet x64-linux install usd`

**Failure logs** 
/home/sh/dev/vcpkg/buildtrees/usd/src/2cd10d91c8-6bd873f966/pxr/usd/ar/packageUtils.cpp:202:41: error: ‘find_if’ is not a member of ‘std’; did you mean ‘find’?
  202 |         auto innermostCloseRevIt = std::find_if(

**Additional context**
#include \<algorithm\> seems to be missing somewhere

**Comment by NancyLi1013** [comment]
Hi @shauser67 
Thanks for posting this issue.
I will try to fix this later.
