### ISSUE TITLE
Boost download failure

### ISSUE THREAD

**Issue by Adriankhl** [microsoft/vcpkg#11417]
**Host Environment**
- OS: Windows
- Compiler: MSVC

**To Reproduce**
Random download bug, can't reproduce

**Failure logs** 
```
-- Downloading https://github.com/boostorg/geometry/archive/boost-1.73.0.tar.gz... Failed. Status: 56;"Failure when receiving data from the peer"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:175 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:132 (vcpkg_download_distfile)
  ports/boost-geometry/portfile.cmake:3 (vcpkg_from_github)
  scripts/ports.cmake:90 (include)


Error: Building package boost-geometry:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-geometry:x64-windows
  Vcpkg version: 2020.02.04-nohash
```

**Additional context**
It happens a few times that vcpkg hangs after downloaded a boost package. It looks like `cmake.exe` is running but nothing happens. This can be easily solved by `Ctrl-c` then run `vcpkg install` again but it is quite annoying. I can see the package has already been downloaded in the `downloads/temp` directory.

Is there any way to identify if this is a vcpkg bug, a github bug, a cmake bug, a Windows (defender?) bug or simply my network problem?

**Comment by 285424336** [comment]
you can reference this website

**Comment by 285424336** [comment]
You can reference this website:  https://www.cnblogs.com/sinferwu/p/12726833.html. 
This problem also happen to me, now i solve it.

**Comment by PhoebeHui** [comment]
Duplicate to https://github.com/microsoft/vcpkg/issues/11181.
