### ISSUE TITLE
port log files with build errors are out of reach

### ISSUE THREAD

**Issue by bsergean** [microsoft/vcpkg#11413]
**Describe the bug**
I am trying to diagnose why my port isn't building after attempting [to upgrade it](https://github.com/microsoft/vcpkg/pull/11030), but it isn't possible to access the raw log files. Navigating azure ci isn't easy and there are many undecipherable steps in the build process.

Now that github supports CI with github actions, why not just using it btw for a better developer experience ?

**Comment by bsergean** [comment]
This is what I see when I try to see what went wrong on a given platform, none of this makes sense for a port author.

<img width="930" alt="Screen Shot 2020-05-17 at 11 03 14 AM" src="https://user-images.githubusercontent.com/11857745/82156100-08b1a980-982e-11ea-84ce-265bea19a956.png">

**Comment by Voskrese** [comment]
https://github.com/microsoft/vcpkg/issues/11395

**Comment by bsergean** [comment]
Thanks good to know.

**Comment by PhoebeHui** [comment]
@bsergean, thanks for reporting this issue!

 I will duplicate this issue to https://github.com/microsoft/vcpkg/issues/11395 to track.
