### ISSUE TITLE
sentencepiece build failure

### ISSUE THREAD

**Issue by remideprez02** [microsoft/vcpkg#11411]
**Host Environment**
- OS: Windows 10
- Compiler: Visual Studio 2019
- Package: sentencepiece:x64-windows
- Vcpkg version: 2020.02.04-nohash

**To Reproduce**
`./vcpkg install sentencepiece sentencepiece:x64-windows`

**Failure logs** 
Building package sentencepiece[core]:x64-windows...
-- Note: sentencepiece only supports static library linkage. Building static library.
CMake Error at scripts/cmake/vcpkg_check_linkage.cmake:51 (message):
  sentencepiece only supports static crt linkage
Call Stack (most recent call first):
  ports/sentencepiece/portfile.cmake:4 (vcpkg_check_linkage)
  scripts/ports.cmake:90 (include)

Error: Building package sentencepiece:x64-windows failed with: BUILD_FAILED

**Additional context**
I followed the steps here : https://github.com/google/sentencepiece/blob/master/README.md

**Comment by LilyWangL** [comment]
Thanks for posting this issue. `sentencepiece` only support static library linkage, so you can build `sentencepiece:x64-windows-static`.
```
Building package sentencepiece[core]:x64-windows...
-- Note: sentencepiece only supports static library linkage. Building static library.
```

**Comment by remideprez02** [comment]
Thank you for your quick answer, it works perfectly !

Btw, I don't know if I should open a new issue or not but I tried to build it from source with ninja/cmake and I had this error :
![image](https://user-images.githubusercontent.com/22635669/82190703-ba65de80-98f1-11ea-8b0d-b592bc9971b8.png)
