### ISSUE TITLE
[New Port Request] sqlpp11-connector-postgresql

### ISSUE THREAD

**Issue by MarcoSpeziali** [microsoft/vcpkg#11424]
Library name: sqlpp11-connector-postgresql

Library description: PostgreSQL connector for sqlpp11 library

Source repository URL: https://github.com/matthijs/sqlpp11-connector-postgresql

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by MarcoSpeziali** [comment]
[portfile.txt](https://github.com/microsoft/vcpkg/files/4648759/portfile.txt)
[CONTROL.txt](https://github.com/microsoft/vcpkg/files/4648760/CONTROL.txt)

I've created the CONTROL and portfile.cmake files, it seams to works

**Comment by PhoebeHui** [comment]
@MarcoSpeziali, could you summit a PR for this port?

**Comment by MarcoSpeziali** [comment]
@PhoebeHui using those portfile and CONTROL files I was then unable to compile for some linking problems. So I think I made some mistakes

**Comment by PhoebeHui** [comment]
@MarcoSpeziali, If you'd like to continue working on it, please reopen and ping us!
