### ISSUE TITLE
osx builds failing on git checkout

### ISSUE THREAD

**Issue by isanych** [microsoft/vcpkg#11425]
All my latest pull requests failing on osx - https://dev.azure.com/vcpkg/public/_build/results?buildId=37110&view=logs&j=7b75bd19-17d3-53d4-00fd-23f1a49a8ba4&t=6c1a7a3b-b385-5a17-556f-78ddf167924d&l=39
```
git checkout --progress --force refs/remotes/pull/11423/merge
Previous HEAD position was 35a71e008 Merge 6248f7cc6dd2a25fe8b8f31d8f8ef1c76eec5ed9 into 8a583e80da3b72141105da9003175679af2fcb92
fatal: update_ref failed for ref 'HEAD': cannot lock ref 'HEAD': Unable to create '/Volumes/data/work/1/s/.git/HEAD.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
##[error]Git checkout failed with exit code: 128
```

**Comment by PhoebeHui** [comment]
@isanych, thanks for reporting this issue!

@strega-nil, this is a known issue for team, and I noticed this issue occurred frenquently when rerun PR on OSX recently.

**Comment by strega-nil** [comment]
Yeah, this is really frustrating; unfortunately, I have no idea how to get azure devops to not git clone initially, because it would be really nice to be able to remove the `HEAD` file (or even just the entire repo) before every clone. There's no real reason to keep it around.

**Comment by PhoebeHui** [comment]
The PR has been merged. and I haven't see this failure again.
