### ISSUE TITLE
[halide] find package broken

### ISSUE THREAD

**Issue by huangqinjin** [microsoft/vcpkg#11428]
With #8803 , `find_package(Halide)` succeeds without any package information, since `halide_config.cmake` is almost empty. 

This breaks `opencv4[halide]`. OpenCV will fall back to manually `find_path` and `find_library` to get `HALIDE_INCLUDE_DIRS` and `HALIDE_LIBRARIES` if  `find_package(Halide)` fails.

Seems `halide.cmake` plays the role of `halide-config.cmake`.

**Comment by JackBoosY** [comment]
Close this issue via #11429 merged.
