### ISSUE TITLE
FYI [angle] build failure with VS 2017 vc141 fatal error C1001: An internal error has occurred in the compiler #11387

### ISSUE THREAD

**Issue by timautry** [microsoft/vcpkg#11430]
Reference [angle] build failure with VS 2017 vc141 fatal error C1001: An internal error has occurred in the compiler #11387 
Reference [ace] vcpkg install ace:x64-windows fails on Visual Studio 2019 16.5  #10522 

Both are same issue, but different VS versions and toolset.

Reported VS 2017 issue: https://developercommunity.visualstudio.com/content/problem/1037098/vs-2017-fatal-error-c1001-an-internal-error-has-oc.html

Reported VS 2019 issue:
https://developercommunity.visualstudio.com/content/problem/954522/internal-compiler-error-1925286104.html

**Comment by jwillemsen** [comment]
Should be fixed by https://github.com/microsoft/vcpkg/pull/11369

**Comment by timautry** [comment]
@Cheney-W  @jwillemsen  I apologize, I thought it had been merged in. I am still new with git.
