### ISSUE TITLE
[boost-locale] build failure

### ISSUE THREAD

**Issue by lone-wolf-akela** [microsoft/vcpkg#11436]
**Host Environment**
- OS: Windows 10 2004
- Compiler: Visual Studio 2019 16.5.5

**To Reproduce**
`.\vcpkg.exe install boost-locale[core]:x86-windows`

**Failure logs** 
Computing installation plan...
The following packages will be built and installed:
    boost-locale[core]:x86-windows
Starting package 1/1: boost-locale:x86-windows
Building package boost-locale[core]:x86-windows...
-- Using cached D:/source/vcpkg/downloads/boostorg-locale-boost-1.73.0.tar.gz
-- Using source at D:/source/vcpkg/buildtrees/boost-locale/src/ost-1.73.0-60f2c445b1
-- Building x86-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: D:/source/vcpkg/installed/x86-windows/tools/boost-build/b2.exe --stagedir=D:/source/vcpkg/buildtrees/boost-locale/x86-windows-rel/stage --build-dir=D:/source/vcpkg/buildtrees/boost-locale/x86-windows-rel --user-config=D:/source/vcpkg/buildtrees/boost-locale/x86-windows-rel/user-config.jam -j12 --debug-configuration --debug-building --debug-generators --disable-icu --ignore-site-config --hash -q -sZLIB_INCLUDE=D:/source/vcpkg/installed/x86-windows/include -sBZIP2_INCLUDE=D:/source/vcpkg/installed/x86-windows/include -sLZMA_INCLUDE=D:/source/vcpkg/installed/x86-windows/include -sZSTD_INCLUDE=D:/source/vcpkg/installed/x86-windows/include threading=multi threadapi=win32 runtime-link=shared link=shared address-model=32 architecture=x86 toolset=msvc -sZLIB_BINARY=zlib -sZLIB_LIBPATH=D:/source/vcpkg/installed/x86-windows/lib -sBZIP2_BINARY=bz2 -sBZIP2_LIBPATH=D:/source/vcpkg/installed/x86-windows/lib -sLZMA_BINARY=lzma -sLZMA_LIBPATH=D:/source/vcpkg/installed/x86-windows/lib -sZSTD_BINARY=zstd -sZSTD_LIBPATH=D:/source/vcpkg/installed/x86-windows/lib variant=release debug-symbols=on
    Working Directory: D:/source/vcpkg/buildtrees/boost-locale/src/ost-1.73.0-60f2c445b1/build
    Error code: 1
    See logs for more information:
      D:\source\vcpkg\buildtrees\boost-locale\build-x86-windows-rel-out.log

Call Stack (most recent call first):
  installed/x86-windows/share/boost-build/boost-modular-build.cmake:286 (vcpkg_execute_required_process)
  ports/boost-locale/portfile.cmake:12 (boost_modular_build)
  scripts/ports.cmake:90 (include)

Error: Building package boost-locale:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-locale:x86-windows
  Vcpkg version: 2020.02.04-nohash

[build-x86-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/4647899/build-x86-windows-rel-out.log)

**Comment by PhoebeHui** [comment]
@lone-wolf-akela, Boost curently upgrade to 1_73, could you please get latest clean source and see if this issue still occurred? I tried it, and built successfully with vcpkg latest clean source by VS2019. 

From your log, the failures is
..\src\..\build\has_iconv.cpp(8): fatal error C1083: Cannot open include file: 'iconv.h': No such file or directory

**Comment by lone-wolf-akela** [comment]
> @lone-wolf-akela, Boost curently upgrade to 1_73, could you please get latest clean source and see if this issue still occurred? I tried it, and built successfully with vcpkg latest clean source by VS2019.
> 
> From your log, the failures is
> ..\src..\build\has_iconv.cpp(8): fatal error C1083: Cannot open include file: 'iconv.h': No such file or directory

Thanks for the advice. I remove boost-modular-build-helper (which was version 1.72.0-1 installed in my computer) and now it successfully compiles.
