### ISSUE TITLE
vcpkg search - Warning: an error occurred while parsing 'libgo'

### ISSUE THREAD

**Issue by timautry** [microsoft/vcpkg#11434]
**Describe the bug**
The word supports is misspelled in the libgo port CONTROL file - it is missing the trailing s
Line 5 of CONTROL file:
-  is `Support: !(arm|uwp)`
-  should be `Supports: !(arm|uwp)`

**Environment**
- OS: [Microsoft Windows [Version 10.0.18363.836]]
         OpenSUSE Leap 15.1
- Compiler: 
   - Visual Studio 2017 Version: 15.9.23  VS Tools Version: 14.16.27023
   - Visual Studio 2019 Version: 16.5.5  VS Tools Version: 14.25.28610
   - gcc (SUSE Linux) 8.2.1 20180831 [gcc-8-branch revision 264010]

**To Reproduce**
1. Windows: `.\vcpkg.exe search` or `.\vcpkg.exe search libgo`
2. Linux  `./vcpkg search` or `./vcpkg search libgo`
3. Error same on Windows and OpenSUSE
`Warning: an error occurred while parsing 'libgo'`
`Use '--debug' to get more information about the parse failures`

4. Results of `.\vcpkg search libgo --debug `
`[DEBUG] Using vcpkg-root: D:\Git\vs2019.test`
`Error: There are invalid fields in the control file of libgo`
`The following fields were not expected:`
` `
`    Support`
` `
`This is the list of valid fields (case-sensitive):`
` `
`    Source`
`    Version`
`    Description`
`    Maintainer`
`    Build-Depends`
`    Homepage`
`    Type`
`    Supports`

`Different source may be available for vcpkg. Use .\bootstrap-vcpkg.bat to update.`

**Expected behavior**
Should be no errors when doing a `vcpkg search` or `vcpkg search <port>`

**Failure logs** 
No logs

**Additional context**
Looks like a simple typo

**PR to follow**
https://github.com/microsoft/vcpkg/pull/11435

**Comment by timautry** [comment]
Also this error prevents from installing port:
`.\vcpkg.exe install libgo`
`Computing installation plan...`
`Error: There are invalid fields in the control file of libgo`
`The following fields were not expected:`
` `
`    Support`
` `
`This is the list of valid fields (case-sensitive):`
` `
`    Source`
`    Version`
`    Description`
`    Maintainer`
`    Build-Depends`
`    Homepage`
`    Type`
`    Supports`
` `
`Different source may be available for vcpkg. Use .\bootstrap-vcpkg.bat to update.`
` `
`Error: Failed to load port from libgo`

**Comment by NancyLi1013** [comment]
HI @timautry 
Thanks for posting this issue.
It's my mistake to miss this. Sorry about this.

**Comment by timautry** [comment]
@NancyLi1013 You are most welcomed!
