### ISSUE TITLE
[New Port Request] <quickjs>

### ISSUE THREAD

**Issue by Imzpy** [microsoft/vcpkg#11446]
Library name:
quickjs
Library description:
QuickJS is a small and embeddable Javascript engine. It supports the ES2020 specification including modules, asynchronous generators, proxies and BigInt.
It optionally supports mathematical extensions such as big decimal floating point numbers (BigDecimal), big binary floating point numbers (BigFloat) and operator overloading.
Source repository URL:
https://github.com/horhof/quickjs
Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by HarrievG** [comment]
Reopen :)

**Comment by shyakocat** [comment]
Request quickjs  `+1`

**Comment by HarrievG** [comment]
can be found here now
https://bellard.org/quickjs/
