### ISSUE TITLE
vcpkg is inconsistent in how it accepts path parameters in its command line interface

### ISSUE THREAD

**Issue by BillyONeal** [microsoft/vcpkg#11456]
**Is your feature request related to a problem? Please describe.**

Consider:

* `--vcpkg-root <path>`
* `--x-scripts-root=<path>`

where a user probably expects one of:

* `--vcpkg-root=<path>`
* `--x-scripts-root=<path>`

or

* `--vcpkg-root <path>`
* `--x-scripts-root <path>`

**Proposed solution**
We already shipped this inconsistency, so just picking one and sticking with it isn't an option. However, we can:

* change parameter parsing to accept either form for all such parameters
* choose the = or separate argument form as the canonical one, and update help text to be consistent

**Comment by BillyONeal** [comment]
Note that I have changes outstanding against much of the help text printing machinery, so until that's submitted maybe hold off working on this. After that fair game for anyone interested.

https://github.com/BillyONeal/vcpkg/tree/directories

**Comment by strega-nil** [comment]
My favorite option is the former solution, for what it's worth

**Comment by BillyONeal** [comment]
@strega-nil Did you fix this already?

**Comment by strega-nil** [comment]
Nope, I should be able to fix it by end of December though.

**Comment by BillyONeal** [comment]
Ah, not pushing you to take any action here; I just was looking at issues I filed and remember that you touched all the command line parsing things and wanted to double check. Thanks!
