### ISSUE TITLE
Option to remove package from all triplets

### ISSUE THREAD

**Issue by pravic** [microsoft/vcpkg#1146]
Currently it requires a manually specified triplet. And, for 7 current triplets, it is a bit unconvenient way to remove package from all installed builds.

**Comment by bagong** [comment]
And an automatic "upgrade" that remembers which packages for which triplets were installed/built 😄

**Comment by codicodi** [comment]
How about wildcards?
`./vcpkg remove boost:*` - does what @pravic asked
`./vcpkg install zlib:*-windows`   <- installs zlib:x86-windows and zlib:x64-windows

**Comment by pravic** [comment]
Nice, it is even much better than just `vcpkg remove --all`.
I suppose that wildcards are not implemented yet?

**Comment by codicodi** [comment]
Yeah, that was just an idea. Sorry if I wasn't clear enough

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/8486
