### ISSUE TITLE
Module "Visualization" of PCL is not built along the others when use [vcpkg -install pcl:x64-windows]

### ISSUE THREAD

**Issue by Qiuchi0918** [microsoft/vcpkg#11462]

**Comment by Qiuchi0918** [comment]
Is there anything else I should do before installing pcl in vcpkg? The pcl installation completed without an error.  Built part of the library seems to be working fine.

**Comment by Neumann-A** [comment]
You mean VTK visualization? Its deactiavted until upstream can be built with VTK 9.0

**Comment by Qiuchi0918** [comment]
Yes the VTK visualization. I thought I must have misconfigured something because the all-in-one build of the same version works just fine. And the console message of something about vtk will be removed in a future version does pop up when 3d viewer is used. Anyway thank you for your help, maybe I should just stick with the all-in-one for now.

**Comment by dlahmad** [comment]
When will it be enabled again?

**Comment by Neumann-A** [comment]
>It's deactivated until upstream can be built with VTK 9.0

https://github.com/PointCloudLibrary/pcl/pull/4138

**Comment by TaylorDale** [comment]
So is there a way to use the visualiser with an older version or something? Or is it literally not possible at all to use the visualiser with VCPKG PCL

**Comment by thomaswillecomme** [comment]
@TaylorDale if i understand the vcpkg way correctly:

- you do a git log at ports/pcl
- you identify the commit which broke the visualization. here it is the upgrade of VTK8 to VTK9 :  c7cd6184d23686ffe54893a76bcd801b7940ba4b
- you checkout one commit before: git checkout c7cd6184d23686ffe54893a76bcd801b7940ba4b^
- clean the whole thing (you loose all changes): git clean -dfx 
- run the bootstrap 
- rebuild it all : vcpkg install pcl
