### ISSUE TITLE
[harfbuzz] build failure

### ISSUE THREAD

**Issue by paul-sorensen** [microsoft/vcpkg#11469]
**Host Environment**
- OS: Windows 10
- Compiler: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\bin\Hostx64\x64\cl.exe

**To Reproduce**
.\vcpkg install harfbuzz[icu]:x64-windows
(the same happens with x86-windows)

**Failure logs** 
Console output:
```
D:\Development\cpp\vcpkg>.\vcpkg install harfbuzz[icu]:x64-windows
Computing installation plan...
The following packages will be built and installed:
    harfbuzz[core,icu,ucdn]:x64-windows
Starting package 1/1: harfbuzz:x64-windows
Building package harfbuzz[core,icu,ucdn]:x64-windows...
-- Using cached D:/Development/cpp/vcpkg/downloads/harfbuzz-harfbuzz-2.5.3.tar.gz
-- Using source at D:/Development/cpp/vcpkg/buildtrees/harfbuzz/src/2.5.3-984271955b
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: D:/Development/cpp/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v
    Working Directory: D:/Development/cpp/vcpkg/buildtrees/harfbuzz/x64-windows-dbg
    See logs for more information:
      D:\Development\cpp\vcpkg\buildtrees\harfbuzz\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/harfbuzz/portfile.cmake:72 (vcpkg_install_cmake)
  scripts/ports.cmake:90 (include)


Error: Building package harfbuzz:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: harfbuzz:x64-windows
  Vcpkg version: 2020.02.04-nohash
```

There are no failures in the logs (file `install-x64-windows-dbg-err.log` is empty), but the standard log is here:
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/4657884/install-x64-windows-dbg-out.log)

**Additional context**
The std and err logs do not have the relevant error detail but when manually running the build command from the working directory, both given in the above console output here:
```CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: D:/Development/cpp/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v
    Working Directory: D:/Development/cpp/vcpkg/buildtrees/harfbuzz/x64-windows-dbg
```

more interesting results are shown:
```
D:\Development\cpp\vcpkg\buildtrees\harfbuzz\x64-windows-dbg>D:/Development/cpp/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v
[1/58] C:\PROGRA~2\MICROS~4\2019\COMMUN~1\VC\Tools\MSVC\1426~1.288\bin\Hostx64\x64\cl.exe   /TP -DHAVE_ATEXIT -DHAVE_FREETYPE=1 -DHAVE_FT_DONE_MM_VAR -DHAVE_FT_GET_VAR_BLEND_COORDINATES -DHAVE_FT_SET_VAR_BLEND_COORDINATES -DHAVE_ICU -DHAVE_ISATTY -DHAVE_STDBOOL_H -DHB_DLL_EXPORT -D_CRT_NONSTDC_NO_WARNINGS -D_CRT_SECURE_NO_WARNINGS -Dharfbuzz_EXPORTS -ID:\Development\cpp\vcpkg\buildtrees\harfbuzz\src\2.5.3-984271955b\src -Isrc -ID:\Development\cpp\vcpkg\installed\x64-windows\include /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1    -wd4244 -wd4267 /showIncludes /FoCMakeFiles\harfbuzz.dir\src\hb-map.cc.obj /FdCMakeFiles\harfbuzz.dir\ /FS -c D:\Development\cpp\vcpkg\buildtrees\harfbuzz\src\2.5.3-984271955b\src\hb-map.cc
FAILED: CMakeFiles/harfbuzz.dir/src/hb-map.cc.obj
C:\PROGRA~2\MICROS~4\2019\COMMUN~1\VC\Tools\MSVC\1426~1.288\bin\Hostx64\x64\cl.exe   /TP -DHAVE_ATEXIT -DHAVE_FREETYPE=1 -DHAVE_FT_DONE_MM_VAR -DHAVE_FT_GET_VAR_BLEND_COORDINATES -DHAVE_FT_SET_VAR_BLEND_COORDINATES -DHAVE_ICU -DHAVE_ISATTY -DHAVE_STDBOOL_H -DHB_DLL_EXPORT -D_CRT_NONSTDC_NO_WARNINGS -D_CRT_SECURE_NO_WARNINGS -Dharfbuzz_EXPORTS -ID:\Development\cpp\vcpkg\buildtrees\harfbuzz\src\2.5.3-984271955b\src -Isrc -ID:\Development\cpp\vcpkg\installed\x64-windows\include /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1    -wd4244 -wd4267 /showIncludes /FoCMakeFiles\harfbuzz.dir\src\hb-map.cc.obj /FdCMakeFiles\harfbuzz.dir\ /FS -c D:\Development\cpp\vcpkg\buildtrees\harfbuzz\src\2.5.3-984271955b\src\hb-map.cc
Microsoft (R) C/C++ Optimizing Compiler Version 19.26.28805 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

D:\Development\cpp\vcpkg\buildtrees\harfbuzz\src\2.5.3-984271955b\src\hb-common.h(67): fatal error C1083: Cannot open include file: 'stdint.h': No such file or directory
```

(this message is [1/58] and there are a lot more, I've just included only one of them as they all have the same error)

So, the compiler cannot find stdint.h. This file is on my system as I can "#include <stdint.h>" from within Visual Studio and it is found at this location:

`C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include\stdint.h`

Did I miss a step in installing or configuring vcpkg? Do I have to tell it about my particular Visual Studio installation other than running `./vcpkg integrate install`? Or perhaps I need to install a basic system package before I install dependent packages?

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Did you run `git pull` before installing `harfbuzz[icu]`?

**Comment by paul-sorensen** [comment]
I had run `git pull` prior to installing, or at least ran it after attempting installation again.

Since I created this issue earlier today I have successfully installed `harfbuzz` without the `[icu]` option, as well as `icu` by itself, and have re-confirmed that the problem port is `harfbuzz[icu]`. A specific triplet does not make a difference - x86-windows, x86-windows-static, x64-windows, and x64-windows-static all fail with the same issue.

Something else that may be the cause or related to it - I encountered a different error at first having to do with msys or so I thought. Some googling found [this issue](https://github.com/microsoft/vcpkg/issues/11438) in which there is a link to [another issue](https://github.com/msys2/MSYS2-packages/issues/1962) where the provided workaround is to install the latest version of msys2. I did this and copied files from the newly installed version to the corresponding directory within vcpkg which resolved that particular problem. **Since then I have not tried to reproduce the `harfbuzz[icu]` install error with a clean install of vcpkg.**

**Comment by LilyWangL** [comment]
@paul-sorensen Sorry I am late. 
The version of harfbuzz on the latest VCPKG is 2.6.6, and I saw your install `harfbuzz-2.5.3` in your log. I can install `harfbuzz[icu]:x64-windows` on the latest VCPKG source.

> Building package harfbuzz[core,icu]:x64-windows...
-- Downloading https://github.com/harfbuzz/harfbuzz/archive/2.6.6.tar.gz...
-- Extracting source F:/0525/vcpkg/downloads/harfbuzz-harfbuzz-2.6.6.tar.gz
-- Applying patch 0001-fix-cmake-export.patch
-- Applying patch 0002-fix-uwp-build.patch
-- Applying patch 0003-remove-broken-test.patch
-- Applying patch find-package-freetype-2.patch
-- Applying patch glib-cmake.patch
-- Using source at F:/0525/vcpkg/buildtrees/harfbuzz/src/2.6.6-8af0fa33ca
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: F:/0525/vcpkg/packages/harfbuzz_x64-windows/share/harfbuzz/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package harfbuzz[core,icu]:x64-windows... done
Installing package harfbuzz[core,icu]:x64-windows...
Installing package harfbuzz[core,icu]:x64-windows... done
Elapsed time for package harfbuzz:x64-windows: 1.022 min
Total elapsed time: 16.63 min

**Comment by LilyWangL** [comment]
@paul-sorensen Does this issue still occur?

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
