### ISSUE TITLE
Error: Port definition not found.

### ISSUE THREAD

**Issue by Yang09701194** [microsoft/vcpkg#11463]
When asking a question please also include where you looked for an answer (so we can update the documentation if needed).

Few hours ago I can normally run `vcpkg install cpprestsdk:x86-windows`, but after I run `git pull`, I can't execute install command, it shows `Errors: Port definition not found.`

Maybe vcpkg can support `backward compatibility`? 

```
C:\vcpkg>vcpkg install cpprestsdk:x86-windows
Computing installation plan...
Error: while loading boost-disjoint-sets:x86-windows: Port definition not found.
Please run "vcpkg remove boost-disjoint-sets:x86-windows" and re-attempt.
```

Also then I run:

```
C:\vcpkg>vcpkg remove boost-disjoint-sets:x86-windows
The following packages will be removed:
  * boost:x86-windows
    boost-disjoint-sets:x86-windows
Additional packages (*) need to be removed to complete this operation.
If you are sure you want to remove them, run the command with the --recurse option
```
Reinstall boost in my experience takes lots of time, should I really remove recurse?

**Comment by PhoebeHui** [comment]
@Yang09701194, thanks for reporting this issue!

It should be a vcpkg bug, I duplicated to https://github.com/microsoft/vcpkg/issues/11463.
