### ISSUE TITLE
[vcpkg] vcpkg requires dumpbin.exe with clang on windows

### ISSUE THREAD

**Issue by Chronial** [microsoft/vcpkg#11467]
Using vcpkg with cmake, ninja and clang on windows fails because there is a dependency on the dumbin.exe tool in applocal.ps1: https://github.com/microsoft/vcpkg/blob/9b4535e7ee7673fb8515d1f4f256990423a0d952/scripts/buildsystems/msbuild/applocal.ps1#L60

**Environment**
- OS: Windows
- Toolchain: CMake with Ninja
- Compiler: clang-10.0.0

**To Reproduce**
* `source.cpp` with contents `int main(){return 0;}`
* `CMakeLists.txt` with contents:
```cmake
cmake_minimum_required(VERSION 3.16)
project(Test CXX)
add_executable(main source.cpp)
find_package(sqlite3 CONFIG REQUIRED)
target_link_libraries(main sqlite3)
```

1. Install `sqlite3:x64-windows` package in vcpkg
2. Run `cmake.exe . -G Ninja -DCMAKE_TOOLCHAIN_FILE=<vcpkg-path>/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows`
3. Run ninja.exe

**Failure logs** 
```
dumpbin : The term 'dumpbin' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\dev\tmp\vcpkg-fork\scripts\buildsystems\msbuild\applocal.ps1:60 char:12
+     $a = $(dumpbin /DEPENDENTS $targetBinary | ? { $_ -match "^    [^ ...
+            ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (dumpbin:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Additional context**
I guess clang is not officially supported on windows? We are using it successfully – this issue and #11466 are the only things that don't work out of the box.

I will gladly provide a PR to fix this issue, I'm just not sure what the best way forward is here. I see two options:
1. Try to find a dumpbin by looking for a msvc installation in the registry or using the `VS2019INSTALLDIR` env var.
2. Add support for llvm-objdump which comes with clang.

Is either of those an acceptable way forward for you?

**Comment by timautry** [comment]
I would think one would need to use the dumpbin with the associated version of Visual Studio being use, 2015, 2017 or 2019 and whether VCPKG_VISUAL_STUDIO_PATH, VCPKG_DEFAULT_TRIPLET, VCPKG_PLATFORM_TOOLSET and VCPK_TARGET_ARCHITECTURE is populated or not in order to allow cross-compiles using specific architecture, version and toolset.

**Comment by Chronial** [comment]
Dumpbin is only used to extract the list of dependent dlls. Why do you think that operation is toolset or target architecture dependent?

**Comment by timautry** [comment]
> Dumpbin is only used to extract the list of dependent dlls. Why do you think that operation is toolset or target architecture dependent?

@Chronial Thank you for the information, I am still learning C++ and its mysteries.
- Will have to accept the statement if one is obtaining `only` dependent dlls to be true.
- It would be good if vcpkg honored the `_IsNativeEnvironment` and/or `PreferredToolArchitecture` environment variables instead using the Visual Studio location and appending `hard-coded \bin\Hostx86\x86\dumpbin.exe` in the visualstudio.cpp source file.
