### ISSUE TITLE
force dlls to build with embedded version

### ISSUE THREAD

**Issue by crusader-mike** [microsoft/vcpkg#11470]
****

**Is your feature request related to a problem? Please describe.**
Some (or most?) vcpkg (dynamic) libraries get built without embedded version on Windows. This causes issues with MSI packages -- in my case (we switched from nugets to vcpkg) installation (built with WiX) can't replace old dll during upgrade because prev dll has a version and new one doesn't.

**Proposed solution**
Fail build if resulting dll doesn't contain embedded version. At least add a command line option for this.

**Describe alternatives you've considered**
For now I ended up adding version to vcpk library manually -- which is FAR from being ideal.

**Comment by BillyONeal** [comment]
This is something the individual port would have to do, which port did you upgrade specifically?

**Comment by crusader-mike** [comment]
In my case it was azure sdk -- their lib (`wastorage.dll`) isn't versioned, but related nuget had versioned dll. Once we switched -- it caused problems in our installation (by default MSI refuses to install unversioned lib on top of versioned one during upgrade; no easy workaround available).

Idea is to nag (with warnings) ports to add versions to dynamic builds and/or add option that will guarantee that given vcpkg bundle contains only versioned dlls.

**Comment by BillyONeal** [comment]
The problem is that lots of ports legitimately do not have versions so we can't really make that a requirement

**Comment by BillyONeal** [comment]
For example, there's nothing [abseil/Abseil](https://abseil.io/about/releases) could put here that would meet your requirements.

**Comment by crusader-mike** [comment]
1. They all have a "vcpkg version" -- nothing wrong with using it as "dll version" for each dll produced (by given port).

2. What about an optional cmdline option that will check every produced dll for presence of version and fail build if such dll exists? In this way when I build all ports (I have installed) -- I'll have a way to ensure all dlls have version.

**Comment by BillyONeal** [comment]
>They all have a "vcpkg version"

They do not. At least, not in a form accepted by MSI.
