### ISSUE TITLE
pkg-config is not listed. How to install it using vcpkg

### ISSUE THREAD

**Issue by jay-thakur** [microsoft/vcpkg#11487]
Hi,

I have cloned FLANN & trying to build it but getting below error - 

```
CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
Call Stack (most recent call first):
  C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.15/Modules/FindPkgConfig.cmake:41 (find_package_handle_standard_args)
  CMakeLists.txt:149 (find_package)


-- Configuring incomplete, errors occurred!
See also "C:/flann/build/CMakeFiles/CMakeOutput.log".
```
I did
```
vcpkg search pkg-config
```
But I don't see any pkg-config.

How to install it ? Please guide / Help.

Thanks,
Jay

**Comment by JackBoosY** [comment]
All you need to do is clone vcpkg, build vcpkg and build flann.
Please see [readme](https://github.com/microsoft/vcpkg#quick-start).

**Comment by JackBoosY** [comment]
@jay-thakur  Does this issue still bother you?

**Comment by jay-thakur** [comment]
@JackBoosY we can close this issue.

**Comment by luizfernandonb** [comment]
> Some libraries requires pkg-config. On Windows, it will be automatically downloaded. On Linux, you have to install pkg-config via system package manager.

Hey @jay-thakur, how did you solve this error?

**Comment by CrossVR** [comment]
For anyone else encountering this issue, the package that you need to install is called `pkgconf`, not `pkg-config`.

```
.\vcpkg install pkgconf
```

**Comment by dg0yt** [comment]
> the package that you need to install is called `pkgconf`, not `pkg-config`.

`pkgconf` is an alternative implementation of pkg-config. It was added as a port, and it can fill the gap. But it is not what vcpkg would use in the first place.

Note that you would normally need the tool for the host, not for the target.
