### ISSUE TITLE
Empty libm package for Windows

### ISSUE THREAD

**Issue by mnaoumov** [microsoft/vcpkg#11486]
Right now if cmake script requires `libm` library, we have edit it to exclude checks on Windows. Having empty package that does nothing should help with this problem

**Comment by mnaoumov** [comment]
Same question about `unistd.h`

**Comment by Neumann-A** [comment]
Answer: No. 
Reason: Library authors make often wrong assumptions if anything like this is found while configuring. So it does not help, it just moves the problem to a different position.

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
