### ISSUE TITLE
[<libarchive[core] or libarchive[bzip2,core,libxml2,lz4,lzma,lzo,openssl,zstd]>]:x64-windows build failure

### ISSUE THREAD

**Issue by timautry** [microsoft/vcpkg#11481]
**Host Environment**
- OS: [Microsoft Windows [Version 10.0.18363.836]]
- Compiler: Visual Studio 2019 Version: 16.6.0  VS Tools Version: 14.26.28801

**To Reproduce**
`.\vcpkg install libarchive`

**Failure logs** 
- Cut and past the appropriate build messages from the console output.
`Computing installation plan...`
`The following packages will be built and installed:`
`    libarchive[bzip2,core,libxml2,lz4,lzma,lzo,openssl,zstd]:x64-windows`
`Starting package 1/1: libarchive:x64-windows`
`Building package libarchive[bzip2,core,libxml2,lz4,lzma,lzo,openssl,zstd]:x64-windows...`
`-- Using cached D:/Git/vcpkg.downloads/libarchive-libarchive-cce09646b566c61c2debff58a70da780b8457883.tar.gz`
`-- Using source at D:/Git/vs2019.prod/buildtrees/libarchive/src/80b8457883-1ab8492808`
`-- Configuring x64-windows`
`-- Building x64-windows-dbg`
`CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):`
`    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v`
`    Working Directory: D:/Git/vs2019.prod/buildtrees/libarchive/x64-windows-dbg`
`    See logs for more information:`
`      D:\Git\vs2019.prod\buildtrees\libarchive\install-x64-windows-dbg-out.log`

`Call Stack (most recent call first):`
`  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)`
`  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)`
`  ports/libarchive/portfile.cmake:67 (vcpkg_install_cmake)`
`  scripts/ports.cmake:90 (include)`

`Error: Building package libarchive:x64-windows failed with: BUILD_FAILED`
`Please ensure you're using the latest portfiles with `.\vcpkg update`, then`
`submit an issue at https://github.com/Microsoft/vcpkg/issues including:`
`  Package: libarchive:x64-windows`
`  Vcpkg version: 2020.02.04-nohash-external`

`Additionally, attach any relevant sections from the log files above.`

- Please attach any additional failure logs mentioned in the console output.
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/4660244/install-x64-windows-dbg-out.log)

**Additional context**
1. Note: I only entered vcpkg install libarchive which should have only tried to install the  `core` feature
2. No matter which port features selected it always wants to install all features - reference https://github.com/microsoft/vcpkg/issues/11479 
3. libarchive with all features installs fine with VS2017

**Comment by JackBoosY** [comment]
```
D:\Git\vs2019.prod\buildtrees\libarchive\src\80b8457883-1ab8492808\libarchive\archive_read_support_format_warc.c(344): error C4061: enumerator 'WT_NONE' in switch of enum 'warc_type_t' is not explicitly handled by a case label
D:\Git\vs2019.prod\buildtrees\libarchive\src\80b8457883-1ab8492808\libarchive\archive_read_support_format_warc.c(75): note: see declaration of 'warc_type_t'
D:\Git\vs2019.prod\buildtrees\libarchive\src\80b8457883-1ab8492808\libarchive\archive_read_support_format_warc.c(344): error C4061: enumerator 'WT_INFO' in switch of enum 'warc_type_t' is not explicitly handled by a case label
D:\Git\vs2019.prod\buildtrees\libarchive\src\80b8457883-1ab8492808\libarchive\archive_read_support_format_warc.c(75): note: see declaration of 'warc_type_t'
D:\Git\vs2019.prod\buildtrees\libarchive\src\80b8457883-1ab8492808\libarchive\archive_read_support_format_warc.c(344): error C4061: enumerator 'WT_META' in switch of enum 'warc_type_t' is not explicitly handled by a case label
D:\Git\vs2019.prod\buildtrees\libarchive\src\80b8457883-1ab8492808\libarchive\archive_read_support_format_warc.c(75): note: see declaration of 'warc_type_t'
D:\Git\vs2019.prod\buildtrees\libarchive\src\80b8457883-1ab8492808\libarchive\archive_read_support_format_warc.c(344): error C4061: enumerator 'WT_REQ' in switch of enum 'warc_type_t' is not explicitly handled by a case label
D:\Git\vs2019.prod\buildtrees\libarchive\src\80b8457883-1ab8492808\libarchive\archive_read_support_format_warc.c(75): note: see declaration of 'warc_type_t'
D:\Git\vs2019.prod\buildtrees\libarchive\src\80b8457883-1ab8492808\libarchive\archive_read_support_format_warc.c(344): error C4061: enumerator 'WT_RVIS' in switch of enum 'warc_type_t' is not explicitly handled by a case label
D:\Git\vs2019.prod\buildtrees\libarchive\src\80b8457883-1ab8492808\libarchive\archive_read_support_format_warc.c(75): note: see declaration of 'warc_type_t'
D:\Git\vs2019.prod\buildtrees\libarchive\src\80b8457883-1ab8492808\libarchive\archive_read_support_format_warc.c(344): error C4061: enumerator 'WT_CONV' in switch of enum 'warc_type_t' is not explicitly handled by a case label
D:\Git\vs2019.prod\buildtrees\libarchive\src\80b8457883-1ab8492808\libarchive\archive_read_support_format_warc.c(75): note: see declaration of 'warc_type_t'
D:\Git\vs2019.prod\buildtrees\libarchive\src\80b8457883-1ab8492808\libarchive\archive_read_support_format_warc.c(344): error C4061: enumerator 'WT_CONT' in switch of enum 'warc_type_t' is not explicitly handled by a case label
D:\Git\vs2019.prod\buildtrees\libarchive\src\80b8457883-1ab8492808\libarchive\archive_read_support_format_warc.c(75): note: see declaration of 'warc_type_t'
D:\Git\vs2019.prod\buildtrees\libarchive\src\80b8457883-1ab8492808\libarchive\archive_read_support_format_warc.c(344): error C4061: enumerator 'LAST_WT' in switch of enum 'warc_type_t' is not explicitly handled by a case label
D:\Git\vs2019.prod\buildtrees\libarchive\src\80b8457883-1ab8492808\libarchive\archive_read_support_format_warc.c(75): note: see declaration of 'warc_type_t'
D:\Git\vs2019.prod\buildtrees\libarchive\src\80b8457883-1ab8492808\libarchive\archive_read_support_format_warc.c(368): error C4061: enumerator 'WT_NONE' in switch of enum 'warc_type_t' is not explicitly handled by a case label
D:\Git\vs2019.prod\buildtrees\libarchive\src\80b8457883-1ab8492808\libarchive\archive_read_support_format_warc.c(75): note: see declaration of 'warc_type_t'
D:\Git\vs2019.prod\buildtrees\libarchive\src\80b8457883-1ab8492808\libarchive\archive_read_support_format_warc.c(368): error C4061: enumerator 'WT_INFO' in switch of enum 'warc_type_t' is not explicitly handled by a case label
D:\Git\vs2019.prod\buildtrees\libarchive\src\80b8457883-1ab8492808\libarchive\archive_read_support_format_warc.c(75): note: see declaration of 'warc_type_t'
D:\Git\vs2019.prod\buildtrees\libarchive\src\80b8457883-1ab8492808\libarchive\archive_read_support_format_warc.c(368): error C4061: enumerator 'WT_META' in switch of enum 'warc_type_t' is not explicitly handled by a case label
D:\Git\vs2019.prod\buildtrees\libarchive\src\80b8457883-1ab8492808\libarchive\archive_read_support_format_warc.c(75): note: see declaration of 'warc_type_t'
D:\Git\vs2019.prod\buildtrees\libarchive\src\80b8457883-1ab8492808\libarchive\archive_read_support_format_warc.c(368): error C4061: enumerator 'WT_REQ' in switch of enum 'warc_type_t' is not explicitly handled by a case label
D:\Git\vs2019.prod\buildtrees\libarchive\src\80b8457883-1ab8492808\libarchive\archive_read_support_format_warc.c(75): note: see declaration of 'warc_type_t'
D:\Git\vs2019.prod\buildtrees\libarchive\src\80b8457883-1ab8492808\libarchive\archive_read_support_format_warc.c(368): error C4061: enumerator 'WT_RVIS' in switch of enum 'warc_type_t' is not explicitly handled by a case label
D:\Git\vs2019.prod\buildtrees\libarchive\src\80b8457883-1ab8492808\libarchive\archive_read_support_format_warc.c(75): note: see declaration of 'warc_type_t'
D:\Git\vs2019.prod\buildtrees\libarchive\src\80b8457883-1ab8492808\libarchive\archive_read_support_format_warc.c(368): error C4061: enumerator 'WT_CONV' in switch of enum 'warc_type_t' is not explicitly handled by a case label
D:\Git\vs2019.prod\buildtrees\libarchive\src\80b8457883-1ab8492808\libarchive\archive_read_support_format_warc.c(75): note: see declaration of 'warc_type_t'
D:\Git\vs2019.prod\buildtrees\libarchive\src\80b8457883-1ab8492808\libarchive\archive_read_support_format_warc.c(368): error C4061: enumerator 'WT_CONT' in switch of enum 'warc_type_t' is not explicitly handled by a case label
D:\Git\vs2019.prod\buildtrees\libarchive\src\80b8457883-1ab8492808\libarchive\archive_read_support_format_warc.c(75): note: see declaration of 'warc_type_t'
D:\Git\vs2019.prod\buildtrees\libarchive\src\80b8457883-1ab8492808\libarchive\archive_read_support_format_warc.c(368): error C4061: enumerator 'LAST_WT' in switch of enum 'warc_type_t' is not explicitly handled by a case label
D:\Git\vs2019.prod\buildtrees\libarchive\src\80b8457883-1ab8492808\libarchive\archive_read_support_format_warc.c(75): note: see declaration of 'warc_type_t'
```

**Comment by timautry** [comment]
@JackBoosY 
- I am not sure what you want me to do?
- The same source as my VS 2017 which compile fine.
- The only other difference I can think of is:
   - my previous VS 2019 install was Visual Studio 2019 Version: 16.5.5 VS Tools Version: 14.25.28610
   - the new install is upgrade to Visual Studio 2019 Version: 16.6.0 VS Tools Version: 14.26.28801
- Maybe it is something introduced with the 16.6.0 upgrade that is not compatible.
- I will delete my VS 2019 install and recreate from scratch to see if that makes a difference.

**Comment by timautry** [comment]
I created a totally new instance of vcpkg using VS2019 and I am still getting the same issue?
Is anyone else using VS 2019 16.6.0?
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/4663366/install-x64-windows-dbg-out.log)

**Comment by timautry** [comment]
I found I can comment out line 154 of the  `<vcpkg-root>\buildtrees\libarchive\src\80b8457883-1ab8492808\CMakeLists.txt` and the port will compile, link and install.
`  # This is added into CMAKE_C_FLAGS when CMAKE_BUILD_TYPE is "Debug"`
`  # Enable level 4 C4061: The enumerate has no associated handler in a switch`
`  #                       statement.`
**`  #SET(CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG} /we4061")`**

Further research I found on https://docs.microsoft.com/en-us/cpp/overview/cpp-conformance-improvements?view=vs-2019 in this paragraph:

**Switch-related warnings for C**
Starting in **Visual Studio 2019 version 16.6**, the compiler implements some preexisting C++ warnings for code compiled as C. The following warnings are **now enabled** at different levels: C4060, **C4061**, C4062, C4063, C4064, C4065, C4808, and C4809. Warnings C4065 and C4060 are disabled by default in C.

**The warnings trigger on missing case statements, undefined enum, and bad bool switches (that is, ones that contain too many cases).** 

So I have a couple of questions here, remembering that I new to C++:
1.  The logs show C4016 as an error, is there a way to make them a warning?
2.  Either way it appears some type of patch needs to be made to make this work for VS2019 16.6 or higher, but I am not sure if it is above my current abilities?
3. Or should this be identified to the upstream vendor of libarchive?

Please advise.....

**Comment by timautry** [comment]
I figured out that if I change line 154 from:
**`SET(CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG} /we4061")`**
to:
**`SET(CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG} /w14061")`**
it makes the message a warning instead of an error and the port compiles, links installs.
My revised questions are:
1. Should we make a patch to update line 154 of the CMakeLists.txt file? **-or-**
2. Should we open a issue upstream at libarchive/libarchive and wait for them to patch? **-or--*
3. Do both?

**Comment by JackBoosY** [comment]
@timautry I just picked out the error messages, so I can more easily dig the cause.

**Comment by JackBoosY** [comment]
No, I can't repro this issue by Visual Studio 2019, here is my output:
```
PS F:\vcpkg> .\vcpkg.exe install libarchive
Computing installation plan...
The following packages will be built and installed:
    libarchive[bzip2,core,libxml2,lz4,lzma,lzo,openssl,zstd]:x86-windows
Warning: abi keys are missing values:
    bzip2
    liblzma
    libxml2
    lz4
    zlib
    zstd

Starting package 1/1: libarchive:x86-windows
Building package libarchive[bzip2,core,libxml2,lz4,lzma,lzo,openssl,zstd]:x86-windows...
-- Using cached F:/vcpkg/downloads/libarchive-libarchive-cce09646b566c61c2debff58a70da780b8457883.tar.gz
-- Using source at F:/vcpkg/buildtrees/libarchive/src/80b8457883-1ab8492808
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Installing: F:/vcpkg/packages/libarchive_x86-windows/share/libarchive/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package libarchive[bzip2,core,libxml2,lz4,lzma,lzo,openssl,zstd]:x86-windows... done
Installing package libarchive[bzip2,core,libxml2,lz4,lzma,lzo,openssl,zstd]:x86-windows...
Installing package libarchive[bzip2,core,libxml2,lz4,lzma,lzo,openssl,zstd]:x86-windows... done
Elapsed time for package libarchive:x86-windows: 4.285 min

Total elapsed time: 4.285 min
```

**Comment by Neumann-A** [comment]
>.\vcpkg install libarchive

will always build the default features not core.

if you want core you explicitly need to use:
`.\vcpkg install libarchive[core]`

this also applies if you want single features e.g.

`.\vcpkg install libarchive[core bzip2]`

if there is a port depending on libarchive it also need to say w´hich features it requires else it assumes the default:

e.g. `Build-Depends: libarchive` will assume the default features are required while `Build-Depends: libarchive[core]` only requires the port to be installed.

**Comment by timautry** [comment]
@JackBoosY  The issue was created with x64-windows triplet and the latest 16.6.0 of VS 2019. I did not have the issue on 16.5.5 or prior versions. I will report this upstream at libarchive.

@Neumann-A The only problem with making all features default is when running an vcpkg upgrade it installs all features even though you may have originally install just core as mentioned by @zrax in issue https://github.com/microsoft/vcpkg/issues/11479
Note: the default behavior of vcpkg has always been just to install the bare minimum and left all other features optional and this port seems to be an exception for reasons unknown?

**Comment by timautry** [comment]
@JackBoosY - see https://github.com/libarchive/libarchive/blob/master/CMakeLists.txt#L157
The latest version of libarchive has the line removed:
**`SET(CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG} /we4061")`**
and all the rest of the **`we`** lines changed to **`w1`**.

All that is needed is upgrade libarchive to the latest version and problem solved.
For a simple/small port I would attempt, but for one as complex as this one is way above my current abilities.
