### ISSUE TITLE
Maybe package dependencies removal problem

### ISSUE THREAD

**Issue by lpintes** [microsoft/vcpkg#11493]
I am just playing with vcpkg. I installed the packages boost-test and boost-spirit.

A lot of other boost packages were installed. I then decided to remove the boost-test and boost-spirit. However their dependencies are still in buildtrees folder, and vcpkg thinks they are not installed.

I verified this by issuing the vcpkg list command.

Besides boost ones, I only installed curl and curlpp.

**Comment by timautry** [comment]
`<vcpkg-root>\buildtrees` is only a working folder while building the port.

vcpkg uses the `<vcpkg-root>\installed\<triplet>\` folder when used with your development tools.

You can either delete the folders in buildtrees manually, or use the --clean-after-build option to have them automatically removed after the port is successfully built, or leave them there if you have the disk space.

**Note:** --clean-after-build deletes the port download file in `<vcpkg-root>\downloads`, package files in `<vcpkg-root>\packages\<port><triplet>` and the `<vcpkg-root>\buildtrees` folder after successful build of each port.

**Comment by Neumann-A** [comment]
>--clean-after-build deletes the port download file in <vcpkg-root>\downloads

does this also apply if enviromnent variable `VCPKG_DOWNLOADS` is set ?

**Comment by lpintes** [comment]
Thank you for a reply. Wonder why GitHub doesn't notify me via email like in the past that someone commented something.

Just thought that my ticket were ignored completely. Now I will check everything I reported just to be sure.

**Comment by timautry** [comment]
> > --clean-after-build deletes the port download file in \downloads
> 
> does this also apply if environment variable `VCPKG_DOWNLOADS` is set ?

@Neumann-A  Yes, I found this out by accident one day. LOL looking backup.
- I have a common folder **`set VCPKG_DOWNLOADS=D:\Git\vcpkg.downloads`** for all the instances of vcpkg I have installed (vs2017 prod and test, vs2019 prod and test). 
- I was testing the different command line options for vcpkg  and used the **`--clean-after-build`** option. 
- It not only deleted the port source download but all the downloaded port sources.
- Luckily I keep a backup of this folder in my daily backup scheme.

**Comment by Neumann-A** [comment]
@timautry: vcpkg should probably not clean a globally set download folder.  Is there another options which does not affect the download folder? If not there should probably be an issue opened about that behavior.

**Comment by timautry** [comment]
@Neumann-A 
I did a quick test with these results:
1. I created and instance
2. vcpkg install bzip2:x64-windows
3. /buildtrees, /downloads and /packages all have folders with contents relating to bzip2
4. The downloads folder also has the appropriate downloaded tools needed by vcpkg
5. vcpkg install zlib:x64-windows --clean-after-build
6 /buildtrees has both bzip2 and zlib folders, bzip2 has all the original contents, zlib only has the logs created during the build, no source, debug or release folders
7. /packages still has the bzip2 folder but as expected no zlib folder
8. /downloads was completely clean except /tools and /temp folders
9. in essence as you mentioned the /downloads should have only deleted the zlib download, not the  bzip2 and the tool download, aka the 7zip, nuget and powershell downloads.
10. I will submit an issue for this... https://github.com/microsoft/vcpkg/issues/11528
Thank you very much and have a wonderful weekend.
