### ISSUE TITLE
[openssl-windows] update to 1.1.1g

### ISSUE THREAD

**Issue by michaeladm** [microsoft/vcpkg#11490]
Library name: openssl

New version number: 1.1.1g

Port already have openssl-windows:x64-windows-static-md version, also it must have openssl-windows:x64-windows-static-mt ( /MT & /MTd ).
Common public install OpenSSL have this libs:
[C:\Program Files\OpenSSL-Win64\lib\VC\static]:
libcrypto64MD.lib
libcrypto64MDd.lib
libcrypto64MT.lib
libcrypto64MTd.lib
libssl64MD.lib
libssl64MDd.lib
libssl64MT.lib
libssl64MTd.lib
I would like to have the same in our version (vcpkg install).

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/11127
