### ISSUE TITLE
sqlite3 with features geopoly and json1

### ISSUE THREAD

**Issue by sanjaychugh** [microsoft/vcpkg#11508]
We are using sqlite3 with the geopoly and json1 features.
It would be nice to add these to the sqlite3 port.
I've modded the port in my working copy which is working fine.
It would be good if the other members on my team didn't have to make the same modification.
I could just tell them to install vcpkg and install sqlite3 with the appropriate features.

Would this be acceptable for a PR?

Thanks.

**Comment by PhoebeHui** [comment]
@sanjaychugh, feel free to summit a PR for this, we're happy to accept the PR!

**Comment by sanjaychugh** [comment]
Thanks! This is my first ever crack at doing this.
From reading the instructions, it seems I will have to create a fork as I don't have write permissions to create a branch. Is that correct.?
And then I can create the PR using the fork.
Also after I create the PR there will be a comment with a link to accept the CLA as per what I read. Is that correct?
Thanks again.

**Comment by sanjaychugh** [comment]
OK, I think I got it right. Will find out I guess.
I've created the PR and and signed the CLA.
This is the URL for the request:
[https://github.com/microsoft/vcpkg/pull/11532](url)

**Comment by Adela0814** [comment]
Fixed by PR https://github.com/microsoft/vcpkg/pull/11532
