### ISSUE TITLE
install glog error

### ISSUE THREAD

**Issue by kahotv** [microsoft/vcpkg#11514]
Package: gflags:x86-windows-static
Vcpkg version: 2020.02.04-nohash

**Comment by Voskrese** [comment]
hi 🤔

**Comment by kahotv** [comment]
hi

E:\Tools\vcpkg>vcpkg install glog:x86-windows-static
Computing installation plan...
The following packages will be built and installed:
  * gflags[core]:x86-windows-static
    glog[core]:x86-windows-static
Additional packages (*) will be modified to complete this operation.
Starting package 1/2: gflags:x86-windows-static
Building package gflags[core]:x86-windows-static...
-- Using community triplet x86-windows-static. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: E:\Tools\vcpkg\triplets\community\x86-windows-static.cmake
Warning: The following VS instances are excluded because the English language pack is unavailable.
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community
Please install the English language pack.
-- Using cached E:/Tools/vcpkg/downloads/gflags-gflags-v2.2.2.tar.gz
-- Using source at E:/Tools/vcpkg/buildtrees/gflags/src/v2.2.2-d9283b9285
-- Configuring x86-windows-static
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: ninja -v
    Working Directory: E:/Tools/vcpkg/buildtrees/gflags/x86-windows-static-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      E:\Tools\vcpkg\buildtrees\gflags\config-x86-windows-static-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:297 (vcpkg_execute_required_process)
  ports/gflags/portfile.cmake:18 (vcpkg_configure_cmake)
  scripts/ports.cmake:90 (include)


Error: Building package gflags:x86-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: gflags:x86-windows-static
  Vcpkg version: 2020.02.04-nohash

Additionally, attach any relevant sections from the log files above.

E:\Tools\vcpkg>

**Comment by Voskrese** [comment]
See logs for more information:
E:\Tools\vcpkg\buildtrees\gflags\config-x86-windows-static-out.log

**Comment by kahotv** [comment]
[1/2] cmd /c "cd ../../x86-windows-static-dbg && "E:/Tools/vcpkg/downloads/tools/cmake-3.17.2-windows/cmake-3.17.2-win32-x86/bin/cmake.exe" "E:/Tools/vcpkg/buildtrees/gflags/src/v2.2.2-d9283b9285" "-DGFLAGS_REGISTER_BUILD_DIR:BOOL=OFF" "-DGFLAGS_REGISTER_INSTALL_PREFIX:BOOL=OFF" "-DBUILD_gflags_nothreads_LIB:BOOL=OFF" "-DCMAKE_DEBUG_POSTFIX=d" "-DCMAKE_MAKE_PROGRAM=E:/Tools/vcpkg/downloads/tools/ninja/ninja-1.10.0/ninja.exe" "-DBUILD_SHARED_LIBS=OFF" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=E:/Tools/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x86-windows-static" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v140" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=E:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=static" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_TARGET_ARCHITECTURE=x86" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_INSTALL_PREFIX=E:/Tools/vcpkg/packages/gflags_x86-windows-static/debug""
FAILED: ../../x86-windows-static-dbg/CMakeCache.txt 
cmd /c "cd ../../x86-windows-static-dbg && "E:/Tools/vcpkg/downloads/tools/cmake-3.17.2-windows/cmake-3.17.2-win32-x86/bin/cmake.exe" "E:/Tools/vcpkg/buildtrees/gflags/src/v2.2.2-d9283b9285" "-DGFLAGS_REGISTER_BUILD_DIR:BOOL=OFF" "-DGFLAGS_REGISTER_INSTALL_PREFIX:BOOL=OFF" "-DBUILD_gflags_nothreads_LIB:BOOL=OFF" "-DCMAKE_DEBUG_POSTFIX=d" "-DCMAKE_MAKE_PROGRAM=E:/Tools/vcpkg/downloads/tools/ninja/ninja-1.10.0/ninja.exe" "-DBUILD_SHARED_LIBS=OFF" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=E:/Tools/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x86-windows-static" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v140" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=E:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=static" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_TARGET_ARCHITECTURE=x86" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_INSTALL_PREFIX=E:/Tools/vcpkg/packages/gflags_x86-windows-static/debug""
CMake Warning at E:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake:157 (message):
  There are no libraries installed for the Vcpkg triplet x86-windows-static.
Call Stack (most recent call first):
  E:/Tools/vcpkg/downloads/tools/cmake-3.17.2-windows/cmake-3.17.2-win32-x86/share/cmake-3.17/Modules/CMakeDetermineSystem.cmake:93 (include)
  CMakeLists.txt:97 (project)


-- The CXX compiler identification is MSVC 19.0.24215.1
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_x86/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_x86/cl.exe - broken
CMake Error at E:/Tools/vcpkg/downloads/tools/cmake-3.17.2-windows/cmake-3.17.2-win32-x86/share/cmake-3.17/Modules/CMakeTestCXXCompiler.cmake:53 (message):
  The C++ compiler

    "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_x86/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: E:/Tools/vcpkg/buildtrees/gflags/x86-windows-static-dbg/CMakeFiles/CMakeTmp
    
    Run Build Command(s):E:/Tools/vcpkg/downloads/tools/ninja/ninja-1.10.0/ninja.exe cmTC_4f955 && [1/2] Building CXX object CMakeFiles\cmTC_4f955.dir\testCXXCompiler.cxx.obj
    [2/2] Linking CXX executable cmTC_4f955.exe
    FAILED: cmTC_4f955.exe 
    cmd.exe /C "cd . && E:\Tools\vcpkg\downloads\tools\cmake-3.17.2-windows\cmake-3.17.2-win32-x86\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_4f955.dir --rc=rc --mt=CMAKE_MT-NOTFOUND --manifests  -- C:\PROGRA~2\MICROS~1.0\VC\bin\AMD64_~2\link.exe /nologo CMakeFiles\cmTC_4f955.dir\testCXXCompiler.cxx.obj  /out:cmTC_4f955.exe /implib:cmTC_4f955.lib /pdb:cmTC_4f955.pdb /version:0.0  /machine:X86  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    RC Pass 1: command "rc /fo CMakeFiles\cmTC_4f955.dir/manifest.res CMakeFiles\cmTC_4f955.dir/manifest.rc" failed (exit code 0) with the following output:
    系统找不到指定的文件。
    ninja: build stopped: subcommand failed.
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:97 (project)


-- Configuring incomplete, errors occurred!
See also "E:/Tools/vcpkg/buildtrees/gflags/x86-windows-static-dbg/CMakeFiles/CMakeOutput.log".
See also "E:/Tools/vcpkg/buildtrees/gflags/x86-windows-static-dbg/CMakeFiles/CMakeError.log".
[2/2] cmd /c "cd .. && "E:/Tools/vcpkg/downloads/tools/cmake-3.17.2-windows/cmake-3.17.2-win32-x86/bin/cmake.exe" "E:/Tools/vcpkg/buildtrees/gflags/src/v2.2.2-d9283b9285" "-DGFLAGS_REGISTER_BUILD_DIR:BOOL=OFF" "-DGFLAGS_REGISTER_INSTALL_PREFIX:BOOL=OFF" "-DBUILD_gflags_nothreads_LIB:BOOL=OFF" "-DCMAKE_DEBUG_POSTFIX=d" "-DCMAKE_MAKE_PROGRAM=E:/Tools/vcpkg/downloads/tools/ninja/ninja-1.10.0/ninja.exe" "-DBUILD_SHARED_LIBS=OFF" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=E:/Tools/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x86-windows-static" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v140" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=E:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=static" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_TARGET_ARCHITECTURE=x86" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=E:/Tools/vcpkg/packages/gflags_x86-windows-static""
FAILED: ../CMakeCache.txt 
cmd /c "cd .. && "E:/Tools/vcpkg/downloads/tools/cmake-3.17.2-windows/cmake-3.17.2-win32-x86/bin/cmake.exe" "E:/Tools/vcpkg/buildtrees/gflags/src/v2.2.2-d9283b9285" "-DGFLAGS_REGISTER_BUILD_DIR:BOOL=OFF" "-DGFLAGS_REGISTER_INSTALL_PREFIX:BOOL=OFF" "-DBUILD_gflags_nothreads_LIB:BOOL=OFF" "-DCMAKE_DEBUG_POSTFIX=d" "-DCMAKE_MAKE_PROGRAM=E:/Tools/vcpkg/downloads/tools/ninja/ninja-1.10.0/ninja.exe" "-DBUILD_SHARED_LIBS=OFF" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=E:/Tools/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x86-windows-static" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v140" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=E:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=static" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_TARGET_ARCHITECTURE=x86" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=E:/Tools/vcpkg/packages/gflags_x86-windows-static""
CMake Warning at E:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake:157 (message):
  There are no libraries installed for the Vcpkg triplet x86-windows-static.
Call Stack (most recent call first):
  E:/Tools/vcpkg/downloads/tools/cmake-3.17.2-windows/cmake-3.17.2-win32-x86/share/cmake-3.17/Modules/CMakeDetermineSystem.cmake:93 (include)
  CMakeLists.txt:97 (project)


-- The CXX compiler identification is MSVC 19.0.24215.1
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_x86/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_x86/cl.exe - broken
CMake Error at E:/Tools/vcpkg/downloads/tools/cmake-3.17.2-windows/cmake-3.17.2-win32-x86/share/cmake-3.17/Modules/CMakeTestCXXCompiler.cmake:53 (message):
  The C++ compiler

    "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_x86/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: E:/Tools/vcpkg/buildtrees/gflags/x86-windows-static-rel/CMakeFiles/CMakeTmp
    
    Run Build Command(s):E:/Tools/vcpkg/downloads/tools/ninja/ninja-1.10.0/ninja.exe cmTC_fa196 && [1/2] Building CXX object CMakeFiles\cmTC_fa196.dir\testCXXCompiler.cxx.obj
    [2/2] Linking CXX executable cmTC_fa196.exe
    FAILED: cmTC_fa196.exe 
    cmd.exe /C "cd . && E:\Tools\vcpkg\downloads\tools\cmake-3.17.2-windows\cmake-3.17.2-win32-x86\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_fa196.dir --rc=rc --mt=CMAKE_MT-NOTFOUND --manifests  -- C:\PROGRA~2\MICROS~1.0\VC\bin\AMD64_~2\link.exe /nologo CMakeFiles\cmTC_fa196.dir\testCXXCompiler.cxx.obj  /out:cmTC_fa196.exe /implib:cmTC_fa196.lib /pdb:cmTC_fa196.pdb /version:0.0  /machine:X86  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    RC Pass 1: command "rc /fo CMakeFiles\cmTC_fa196.dir/manifest.res CMakeFiles\cmTC_fa196.dir/manifest.rc" failed (exit code 0) with the following output:
    系统找不到指定的文件。
    ninja: build stopped: subcommand failed.
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:97 (project)


-- Configuring incomplete, errors occurred!
See also "E:/Tools/vcpkg/buildtrees/gflags/x86-windows-static-rel/CMakeFiles/CMakeOutput.log".
See also "E:/Tools/vcpkg/buildtrees/gflags/x86-windows-static-rel/CMakeFiles/CMakeError.log".
ninja: build stopped: subcommand failed.

**Comment by Voskrese** [comment]
1.
`vcpkg env`
2.
`where rc`

**Comment by PhoebeHui** [comment]
@kahotv, sorry for my late reply.

Could you install English language pack and try to build again?

**Comment by PhoebeHui** [comment]
@kahotv, please reopen this issue if it still be a problem for you.
