### ISSUE TITLE
Fail to install activemq-cpp/apr in linux ubuntu 18.04 (WSL)

### ISSUE THREAD

**Issue by EricWebsmith** [microsoft/vcpkg#11518]
**Describe the bug**

I installed activemq-cpp successfully on windows.

But when I tried to install activemq-cpp on Linux (WSL ubuntu 18.04), I failed.

Firstly, I failed installing apr. (See log 1)

I followed the log and added the following code in the config.cmake file

```python
    if(VCPKG_LIBRARY_LINKAGE STREQUAL "static")
        file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/bin" "${CURRENT_PACKAGES_DIR}/debug/bin")
    endif()
```

After that, i was able to install apr (see log2)

But when I tried to install activemq-cpp, I got another error, saying "Error code: No such file or directory".

I checked the files, both activemq-cpp.vcxproj and vcpkg.targets were there. I have no clue which file or directory does not exist.

(See log3)

**Environment**

- OS: Linux (WSL Ubuntu 18.04)
- Compiler: default

**To Reproduce**

1. copy the following code to ....\vcpkg\ports\portfile.cmake

```python
    vcpkg_install_make()
	
    if(VCPKG_LIBRARY_LINKAGE STREQUAL "static")
        file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/bin" "${CURRENT_PACKAGES_DIR}/debug/bin")
    endif()

endif()
```

2. ./vcpkg install apr
2. ./vcpkg install activemq-cpp

**Expected behavior**
I hope activemq-cpp will be installed successfully on my Linux (WSL).

**Failure logs** 

### Log 1 - failed to install apr

eric@r2:/mnt/d/projects/vcpkg$ ./vcpkg install apr
Computing installation plan...
The following packages will be built and installed:
    apr[core]:x64-linux
Starting package 1/1: apr:x64-linux
Building package apr[core]:x64-linux...
-- Using cached /mnt/d/projects/vcpkg/downloads/apr-1.7.0.tar.bz2
-- Using source at /mnt/d/projects/vcpkg/buildtrees/apr/src/apr-1-3a6fcafcf9
-- Configuring apr
-- Using generator make
-- Configuring x64-linux
-- Building x64-linux
-- Installing x64-linux
-- Installing: /mnt/d/projects/vcpkg/packages/apr_x64-linux/share/apr/copyright
-- Performing post-build validation
There should be no bin\ directory in a static build, but /mnt/d/projects/vcpkg/packages/apr_x64-linux/bin is present.
If the creation of bin\ and/or debug\bin\ cannot be disabled, use this in the portfile to remove them

    if(VCPKG_LIBRARY_LINKAGE STREQUAL "static")
        file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/bin" "${CURRENT_PACKAGES_DIR}/debug/bin")
    endif()

Found 1 error(s). Please correct the portfile:
    /mnt/d/projects/vcpkg/ports/apr/portfile.cmake
-- Performing post-build validation done
Error: Building package apr:x64-linux failed with: POST_BUILD_CHECKS_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: apr:x64-linux
  Vcpkg version: 2020.02.04-unknownhash

Additionally, attach any relevant sections from the log files above.

### Log 2 - successfully installed apr

eric@r2:/mnt/d/projects/vcpkg$ ./vcpkg install apr
Computing installation plan...
The following packages will be built and installed:
    apr[core]:x64-linux
Starting package 1/1: apr:x64-linux
Building package apr[core]:x64-linux...
-- Using cached /mnt/d/projects/vcpkg/downloads/apr-1.7.0.tar.bz2
-- Using source at /mnt/d/projects/vcpkg/buildtrees/apr/src/apr-1-3a6fcafcf9
-- Configuring apr
-- Using generator make
-- Configuring x64-linux
-- Building x64-linux
-- Installing x64-linux
-- Installing: /mnt/d/projects/vcpkg/packages/apr_x64-linux/share/apr/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package apr[core]:x64-linux... done
Installing package apr[core]:x64-linux...
Installing package apr[core]:x64-linux... done
Elapsed time for package apr:x64-linux: 1.826 min

Total elapsed time: 1.826 min

### Log 3 - Fail to install activemq-cpp

eric@r2:/mnt/d/projects/vcpkg$ ./vcpkg install activemq-cpp
Computing installation plan...
The following packages will be built and installed:
    activemq-cpp[core]:x64-linux
Starting package 1/1: activemq-cpp:x64-linux
Building package activemq-cpp[core]:x64-linux...
-- Downloading https://www.apache.org/dist/activemq/activemq-cpp/3.9.5/activemq-cpp-library-3.9.5-src.tar.bz2...
-- Extracting source /mnt/d/projects/vcpkg/downloads/activemq-cpp-library-3.9.5-src.tar.bz2
-- Applying patch /mnt/d/projects/vcpkg/ports/activemq-cpp/FunctionLevelLinkingOn.diff
-- Using source at /mnt/d/projects/vcpkg/buildtrees/activemq-cpp/src/-library-3-dac1f8e3f5
-- Building /mnt/d/projects/vcpkg/buildtrees/activemq-cpp/src/-library-3-dac1f8e3f5/vs2010-build/activemq-cpp.vcxproj for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: msbuild /mnt/d/projects/vcpkg/buildtrees/activemq-cpp/src/-library-3-dac1f8e3f5/vs2010-build/activemq-cpp.vcxproj /p:Configuration=ReleaseDLL /t:Rebuild /p:Platform=x64 /p:PlatformToolset=external /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /p:WindowsTargetPlatformVersion= /m /p:WholeProgramOptimization=false /p:ForceImportBeforeCppTargets=/mnt/d/projects/vcpkg/scripts/buildsystems/msbuild/vcpkg.targets /p:VcpkgTriplet=x64-linux
    Working Directory: /mnt/d/projects/vcpkg/buildtrees/activemq-cpp/x64-linux-rel
    Error code: No such file or directory
    See logs for more information:

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_msbuild.cmake:119 (vcpkg_execute_required_process)
  ports/activemq-cpp/portfile.cmake:35 (vcpkg_build_msbuild)
  scripts/ports.cmake:90 (include)

Error: Building package activemq-cpp:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: activemq-cpp:x64-linux
  Vcpkg version: 2020.02.04-unknownhash

Additionally, attach any relevant sections from the log files above.

**Comment by EricWebsmith** [comment]
I just reproduced this on my home computer. the environment is the same.

**Comment by EricWebsmith** [comment]
I reinstalled my Linux and upgraded it to Ubuntu 20.04, the problem is reproduced again.

**Comment by PhoebeHui** [comment]
@EricWebsmith, apr installed successfully for me with latest vcpkg and Ubuntu 18.04.
For activemq-cpp port, it's unsupport on linux, I summited a PR 11589 for adding the Supports.

Starting package 1/2: apr:x64-linux
Building package apr[core]:x64-linux...
-- Downloading https://www.apache.org/dist/apr/apr-1.7.0.tar.bz2...
-- Extracting source /home/phoebe/vcpkg/downloads/apr-1.7.0.tar.bz2
-- Using source at /home/phoebe/vcpkg/buildtrees/apr/src/apr-1-3a6fcafcf9
-- Configuring apr
-- apr requires pkg-config from the system package manager (example: "sudo apt-get install pkg-config")
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Installing x64-linux-dbg
-- Installing x64-linux-rel
-- Installing: /home/phoebe/vcpkg/packages/apr_x64-linux/share/apr/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package apr[core]:x64-linux... done
Installing package apr[core]:x64-linux...
Installing package apr[core]:x64-linux... done
Elapsed time for package apr:x64-linux: 1.171 min

**Comment by PhoebeHui** [comment]
The PR has been merged. Feel free to reopen this issue if apr still fail on your side.
