### ISSUE TITLE
[protobuf-c] Feature test relies on wrong dependency

### ISSUE THREAD

**Issue by JackBoosY** [microsoft/vcpkg#11519]
**Describe the bug**
When a certain port has multiple features and there is a dependency relationship between feature and feature, the feature that installs the port's dependency and other features will generate an error: 

> Package *** does not have a *** feature.

Example: `protobuf-c` has feature `tools` and `test`, and feature `test` depend on `tools`.

**Environment**
- OS: [e.g. Windows/Linux etc...] All triplets
- Compiler: revision

**To Reproduce**
1. `./vcpkg install protobuf-c[test]`
2. See error
Repro code when

**Expected behavior**
Port should be built succesfully as expected.

**Failure logs** 
N/A

**Additional context**
N/A

**Comment by JackBoosY** [comment]
https://github.com/microsoft/vcpkg/blob/e792d1c171a18d32401db0f95251515cc15056f5/toolsrc/src/vcpkg/dependencies.cpp#L683

It looks like I found the wrong port and feature matching value here.

**Comment by Neumann-A** [comment]
try changing:
`protobuf[tools]`
to
`protobuf[core,tools]`

**Comment by JackBoosY** [comment]
@Neumann-A Not working.

**Comment by JackBoosY** [comment]
Well... I noticed the feature `test` dependency is wrong now...
