### ISSUE TITLE
Error: Building package libepoxy:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by xiaoxi-li** [microsoft/vcpkg#11526]
**Describe the bug**

**Environment**
- OS: [e.g. Windows.]
- Compiler: visual studio community 2019

**To Reproduce**
1. ./vcpkg install gtk:x64-windows
2. See error
Repro code when

**Expected behavior**

**Failure logs** 
C:\Users\L\Downloads\Compressed\vcpkg-master>vcpkg install gtk:x64-windows
Computing installation plan...
The following packages will be built and installed:
    gtk[core]:x64-windows
  * harfbuzz[core,glib]:x64-windows
  * libepoxy[core]:x64-windows
  * pango[core]:x64-windows
  * ragel[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/5: libepoxy:x64-windows
Building package libepoxy[core]:x64-windows...
-- Using cached C:/Users/L/Downloads/Compressed/vcpkg-master/downloads/anholt-libepoxy-1.5.3.tar.gz
-- Using source at C:/Users/L/Downloads/Compressed/vcpkg-master/buildtrees/libepoxy/src/1.5.3-d7b9d32fcb
-- Acquiring MSYS Packages...
-- Acquiring MSYS Packages... OK
-- Configuring x64-windows-dbg
-- Configuring x64-windows-dbg done
-- Configuring x64-windows-rel
-- Configuring x64-windows-rel done
-- Package x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" install -v
    Working Directory: C:/Users/L/Downloads/Compressed/vcpkg-master/buildtrees/libepoxy/x64-windows-rel
    Error code: 1
    See logs for more information:
      C:\Users\L\Downloads\Compressed\vcpkg-master\buildtrees\libepoxy\package-x64-windows-rel-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_meson.cmake:19 (vcpkg_execute_required_process)
  ports/libepoxy/portfile.cmake:16 (vcpkg_install_meson)
  scripts/ports.cmake:90 (include)

Error: Building package libepoxy:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libepoxy:x64-windows
  Vcpkg version: 2020.02.04-nohash
**Additional context**

Additionally, attach any relevant sections from the log files above

**Comment by timautry** [comment]
@xiaoxi-li Please attach or upload the log file **`C:\Users\L\Downloads\Compressed\vcpkg-master\buildtrees\libepoxy\package-x64-windows-rel-out.log`** to assist in diagnosing the issue.
Thank you.

**Comment by xiaoxi-li** [comment]
> @ xiaoxi-li请附加或上传日志文件**`C:\Users\L\Downloads\Compressed\vcpkg-master\buildtrees\libepoxy\package-x64-windows-rel-out.log`**以帮助诊断问题。
> 谢谢。
This is the log file:package-x64-windows-rel-out.log,thank you for your reply!
[1/28] "C:/Users/L/Downloads/Compressed/vcpkg-master/downloads/tools/python/python-3.7.3-x64/python.exe" "../src/1.5.3-d7b9d32fcb/src/gen_dispatch.py" "--header" "--no-source" "--outputdir=include/epoxy" "../src/1.5.3-d7b9d32fcb/registry/wgl.xml"
[2/28] "C:/Users/L/Downloads/Compressed/vcpkg-master/downloads/tools/python/python-3.7.3-x64/python.exe" "../src/1.5.3-d7b9d32fcb/src/gen_dispatch.py" "--source" "--no-header" "--outputdir=src" "../src/1.5.3-d7b9d32fcb/registry/wgl.xml"
[3/28] "C:/Users/L/Downloads/Compressed/vcpkg-master/downloads/tools/python/python-3.7.3-x64/python.exe" "../src/1.5.3-d7b9d32fcb/src/gen_dispatch.py" "--header" "--no-source" "--outputdir=include/epoxy" "../src/1.5.3-d7b9d32fcb/registry/gl.xml"
[4/28] cl @"test/9f86d08@@misc defines@exe/miscdefines.c.obj".rsp
[5/28] cl @"test/9f86d08@@header guards@exe/headerguards.c.obj".rsp
[6/28] cl @"test/9f86d08@@khronos typedefs@exe/khronos_typedefs.c.obj".rsp
[7/28] "C:/Users/L/Downloads/Compressed/vcpkg-master/downloads/tools/python/python-3.7.3-x64/python.exe" "../src/1.5.3-d7b9d32fcb/src/gen_dispatch.py" "--source" "--no-header" "--outputdir=src" "../src/1.5.3-d7b9d32fcb/registry/gl.xml"
[8/28] cl @"test/9f86d08@@khronos typedefs@exe/khronos_typedefs_nonepoxy.c.obj".rsp
../src/1.5.3-d7b9d32fcb/test/khronos_typedefs_nonepoxy.c(60): warning C4068: unknown pragma
[9/28] cl @test/9f86d08@@wgl_common@sta/wgl_common.c.obj.rsp
[10/28] cl @src/25a6634@@epoxy@sha/dispatch_common.c.obj.rsp
FAILED: src/25a6634@@epoxy@sha/dispatch_common.c.obj 
cl @src/25a6634@@epoxy@sha/dispatch_common.c.obj.rsp
../src/1.5.3-d7b9d32fcb/src/dispatch_common.c(1): error C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
../src/1.5.3-d7b9d32fcb/src/dispatch_common.c(409): warning C4996: 'sscanf': This function or variable may be unsafe. Consider using sscanf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
../src/1.5.3-d7b9d32fcb/src/dispatch_common.c(506): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
[11/28] cl @src/25a6634@@epoxy@sha/dispatch_wgl.c.obj.rsp
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared\minwindef.h(130): warning C4005: 'APIENTRY': macro redefinition
C:\Users\L\Downloads\Compressed\vcpkg-master\buildtrees\libepoxy\src\1.5.3-d7b9d32fcb\include\epoxy/gl.h(59): note: see previous definition of 'APIENTRY'
[12/28] lib "/NOLOGO" /MACHINE:x64 /OUT:test/libwgl_common.a @test/libwgl_common.a.rsp
[13/28] cl @test/9f86d08@@wgl_usefontbitmaps@exe/wgl_usefontbitmaps.c.obj.rsp
../src/1.5.3-d7b9d32fcb/test/wgl_usefontbitmaps.c(50): warning C4267: 'function': conversion from 'size_t' to 'GLsizei', possible loss of data
../src/1.5.3-d7b9d32fcb/test/wgl_usefontbitmaps.c(59): warning C4267: 'function': conversion from 'size_t' to 'GLsizei', possible loss of data
[14/28] cl @test/9f86d08@@wgl_per_context_funcptrs@exe/wgl_per_context_funcptrs.c.obj.rsp
[15/28] cl @test/9f86d08@@wgl_core_and_exts@exe/wgl_core_and_exts.c.obj.rsp
[16/28] cl @test/9f86d08@@wgl_usefontbitmaps_unicode@exe/wgl_usefontbitmaps.c.obj.rsp
../src/1.5.3-d7b9d32fcb/test/wgl_usefontbitmaps.c(50): warning C4267: 'function': conversion from 'size_t' to 'GLsizei', possible loss of data
../src/1.5.3-d7b9d32fcb/test/wgl_usefontbitmaps.c(59): warning C4267: 'function': conversion from 'size_t' to 'GLsizei', possible loss of data
[17/28] cl @src/25a6634@@epoxy@sha/meson-generated_.._wgl_generated_dispatch.c.obj.rsp
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared\minwindef.h(130): warning C4005: 'APIENTRY': macro redefinition
C:\Users\L\Downloads\Compressed\vcpkg-master\buildtrees\libepoxy\src\1.5.3-d7b9d32fcb\include\epoxy/gl.h(59): note: see previous definition of 'APIENTRY'
src/wgl_generated_dispatch.c(4555): warning C4098: 'epoxy_wglBlitContextFramebufferAMD_global_rewrite_ptr': 'void' function returning a value
src/wgl_generated_dispatch.c(4555): warning C4098: 'epoxy_wglBlitContextFramebufferAMD_dispatch_table_rewrite_ptr': 'void' function returning a value
src/wgl_generated_dispatch.c(4555): warning C4098: 'epoxy_wglBlitContextFramebufferAMD_dispatch_table_thunk': 'void' function returning a value
src/wgl_generated_dispatch.c(4581): warning C4098: 'epoxy_wglDeleteBufferRegionARB_global_rewrite_ptr': 'void' function returning a value
src/wgl_generated_dispatch.c(4581): warning C4098: 'epoxy_wglDeleteBufferRegionARB_dispatch_table_rewrite_ptr': 'void' function returning a value
src/wgl_generated_dispatch.c(4581): warning C4098: 'epoxy_wglDeleteBufferRegionARB_dispatch_table_thunk': 'void' function returning a value
src/wgl_generated_dispatch.c(4585): warning C4098: 'epoxy_wglDestroyDisplayColorTableEXT_global_rewrite_ptr': 'void' function returning a value
src/wgl_generated_dispatch.c(4585): warning C4098: 'epoxy_wglDestroyDisplayColorTableEXT_dispatch_table_rewrite_ptr': 'void' function returning a value
src/wgl_generated_dispatch.c(4585): warning C4098: 'epoxy_wglDestroyDisplayColorTableEXT_dispatch_table_thunk': 'void' function returning a value
[18/28] cl @src/25a6634@@epoxy@sha/meson-generated_.._gl_generated_dispatch.c.obj.rsp
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared\minwindef.h(130): warning C4005: 'APIENTRY': macro redefinition
C:\Users\L\Downloads\Compressed\vcpkg-master\buildtrees\libepoxy\src\1.5.3-d7b9d32fcb\include\epoxy/gl.h(59): note: see previous definition of 'APIENTRY'
ninja: build stopped: subcommand failed.

**Comment by timautry** [comment]
The error is `../src/1.5.3-d7b9d32fcb/src/dispatch_common.c(1): error C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss`

See issues https://github.com/microsoft/vcpkg/issues/10382 and https://github.com/microsoft/vcpkg/issues/11210 for possible solutions.

**Comment by NancyLi1013** [comment]
Hi @xiaoxi-li 
Thanks for posting this issue. It's duplicated to #11210. So let's focus on this issue there.

**Comment by xiaoxi-li** [comment]
> 嗨@ xiaoxi-li
> 感谢您发布此问题。复制到[＃11210](https://github.com/microsoft/vcpkg/issues/11210)。因此，让我们在那里集中讨论此问题。

ok,

**Comment by xiaoxi-li** [comment]
> @ xiaoxi-li错误是`../src/1.5.3-d7b9d32fcb/src/dispatch_common.c(1): error C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss`
> 
> 有关可能的解决方案，请参阅问题[＃10382](https://github.com/microsoft/vcpkg/issues/10382)和[＃11210](https://github.com/microsoft/vcpkg/issues/11210)。
 I have try the ways provided by the net friends in #11210 and #10382 ,but it still has this problem.
And this is the out-log
[package-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/4677524/package-x64-windows-rel-out.log)
