### ISSUE TITLE
[vcpkg] install <port> --clean-after-build bug deletes all files in vcpkg-root/downloads

### ISSUE THREAD

**Issue by timautry** [microsoft/vcpkg#11528]
**Describe the bug**
[vcpkg] install <port> --clean-after-build bug files deletes all files in vcpkg-root/downloads folder.
Reference: at end of issue discussion between @Neumann-A and @timautry about `--clean-after-build` option

**Environment**
- OS: Windows and Linux - I do not have OSX to test
- Compiler: any

**To Reproduce**
1. `/vcpkg install <port> --clean-after-build`
   `/vcpkg install <port> <port> <port> --clean-after-build`
2. No errors

**Expected behavior**
--clean-after-build should only delete current downloaded ports in /downloads folder

**Failure logs** 
- None

**Additional context**
1. vcpkg install bzip2:x64-windows **installs port**
2. /buildtrees, /downloads and /packages all have folders with contents relating to bzip2. **good**
3. The /downloads folder also has the appropriate downloaded tools needed by vcpkg. **good**
4. vcpkg install zlib:x64-windows --clean-after-build  **installs port**
5. /buildtrees has both bzip2 and zlib folders, bzip2 has all the original contents, zlib only has the logs created during the build, no source, debug or release folders. **good**
6. /packages still has the bzip2 folder but as expected no zlib folder. **good**
7. /downloads was completely clean except /tools and /temp folders? **question at hand**
8. **Question/discussion should** `--clean-after-build` option only delete the ports on the command line or all ports and tools sources from the /downloads folder?

**Comment by Neumann-A** [comment]
The important point missing here is that it also cleans everything in the download folder if environment variable `VCPKG_DOWNLOADS` ist set. This is a issue because this is most likely pointing to a common folder between different vcpkg instances. 
`--clean-after-build` should probably be split into
`--clean-buildfiles-after-build, ` and
`--clean-downloads-after-build` (should probably be a separate command instead?)

**Comment by timautry** [comment]
> The important point missing here is that it also cleans everything in the download folder if environment variable `VCPKG_DOWNLOADS` ist set. This is a issue because this is most likely pointing to a common folder between different vcpkg instances.
> `--clean-after-build` should probably be split into
> `--clean-buildfiles-after-build, ` and
> `--clean-downloads-after-build` (should probably be a separate command instead?)

- Forgot to mention that piece of the puzzle. Thank you very much @Neumann-A !!!
- I do use the environment variable `set VCPKG_DOWNLOADS=D:\Git\vcpkg.downloads` as a common location for all vcpkg instances on computer.
- Another thought add `--clean-packages-after-build`  so one can pick and choose which to delete and which to keep.

**Comment by timautry** [comment]
I close, I no long use product.
