### ISSUE TITLE
[libepoxy] x64-wndows build failure

### ISSUE THREAD

**Issue by xiaoxi-li** [microsoft/vcpkg#11525]
**Host Environment**
- OS: [e.g. Windows]
- Compiler: cmd

**To Reproduce**
`./vcpkg install gtk:x64-windows

**Failure logs** 
-C:\Users\L\Downloads\Compressed\vcpkg-master>vcpkg install gtk:x64-windows
Computing installation plan...
The following packages will be built and installed:
    gtk[core]:x64-windows
  * harfbuzz[core,glib]:x64-windows
  * libepoxy[core]:x64-windows
  * pango[core]:x64-windows
  * ragel[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/5: libepoxy:x64-windows
Building package libepoxy[core]:x64-windows...
-- Using cached C:/Users/L/Downloads/Compressed/vcpkg-master/downloads/anholt-libepoxy-1.5.3.tar.gz
-- Using source at C:/Users/L/Downloads/Compressed/vcpkg-master/buildtrees/libepoxy/src/1.5.3-d7b9d32fcb
-- Acquiring MSYS Packages...
-- Acquiring MSYS Packages... OK
-- Configuring x64-windows-dbg
-- Configuring x64-windows-dbg done
-- Configuring x64-windows-rel
-- Configuring x64-windows-rel done
-- Package x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" install -v
    Working Directory: C:/Users/L/Downloads/Compressed/vcpkg-master/buildtrees/libepoxy/x64-windows-rel
    Error code: 1
    See logs for more information:
      C:\Users\L\Downloads\Compressed\vcpkg-master\buildtrees\libepoxy\package-x64-windows-rel-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_meson.cmake:19 (vcpkg_execute_required_process)
  ports/libepoxy/portfile.cmake:16 (vcpkg_install_meson)
  scripts/ports.cmake:90 (include)

Error: Building package libepoxy:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libepoxy:x64-windows
  Vcpkg version: 2020.02.04-nohash

**Additional context**
[package-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/4680252/package-x64-windows-rel-out.log)

**Comment by NancyLi1013** [comment]
Hi @xiaoxi-li 

Thanks for posting this issue. Could you please help provide the log from`C:\Users\L\Downloads\Compressed\vcpkg-master\buildtrees\libepoxy\package-x64-windows-rel-out.log`?

And please also confirm if it is the same issue with #11526  or #11210.

**Comment by NancyLi1013** [comment]
@xiaoxi-li 
Please attach the failure log from `C:\Users\L\Downloads\Compressed\vcpkg-master\buildtrees\libepoxy\package-x64-windows-rel-out.log`.

**Comment by xiaoxi-li** [comment]
> @ xiaoxi-li
> 请附上来自的故障日志`C:\Users\L\Downloads\Compressed\vcpkg-master\buildtrees\libepoxy\package-x64-windows-rel-out.log`。

I have attached the log in my issue,thank you！Or you can read it on this comment directly.
[package-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/4680262/package-x64-windows-rel-out.log)

**Comment by NancyLi1013** [comment]
Sorry for my mistake. I didn't notice this before.

```
FAILED: src/epoxy-0.dll 
link @src/epoxy-0.dll.rsp
   Creating library src\\epoxy.lib and object src\\epoxy.exp
meson-generated_.._gl_generated_dispatch.c.obj : error LNK2019: unresolved external symbol epoxy_gles1_dlsym referenced in function gl_provider_resolver
meson-generated_.._gl_generated_dispatch.c.obj : error LNK2019: unresolved external symbol epoxy_gles2_dlsym referenced in function gl_provider_resolver
meson-generated_.._gl_generated_dispatch.c.obj : error LNK2019: unresolved external symbol epoxy_conservative_has_gl_extension referenced in function gl_provider_resolver
meson-generated_.._wgl_generated_dispatch.c.obj : error LNK2019: unresolved external symbol epoxy_gl_dlsym referenced in function wgl_provider_resolver
dispatch_common.c.obj : error LNK2001: unresolved external symbol epoxy_gl_dlsym
dispatch_common.c.obj : error LNK2019: unresolved external symbol epoxy_has_gl_extension referenced in function epoxy_glsl_version
src\epoxy-0.dll : fatal error LNK1120: 5 unresolved externals
ninja: build stopped: subcommand failed.
```
I cannot reproduce this on my local machine. with Visual Studio 2019 16.5.3.  `libepoxy `has been updated to 1.5.4. Could you please try to update vcpkg and rebuild this?

**Comment by xiaoxi-li** [comment]
> 对不起，我错了。我以前没注意到。
> 
> ```
> FAILED: src/epoxy-0.dll 
> link @src/epoxy-0.dll.rsp
>    Creating library src\\epoxy.lib and object src\\epoxy.exp
> meson-generated_.._gl_generated_dispatch.c.obj : error LNK2019: unresolved external symbol epoxy_gles1_dlsym referenced in function gl_provider_resolver
> meson-generated_.._gl_generated_dispatch.c.obj : error LNK2019: unresolved external symbol epoxy_gles2_dlsym referenced in function gl_provider_resolver
> meson-generated_.._gl_generated_dispatch.c.obj : error LNK2019: unresolved external symbol epoxy_conservative_has_gl_extension referenced in function gl_provider_resolver
> meson-generated_.._wgl_generated_dispatch.c.obj : error LNK2019: unresolved external symbol epoxy_gl_dlsym referenced in function wgl_provider_resolver
> dispatch_common.c.obj : error LNK2001: unresolved external symbol epoxy_gl_dlsym
> dispatch_common.c.obj : error LNK2019: unresolved external symbol epoxy_has_gl_extension referenced in function epoxy_glsl_version
> src\epoxy-0.dll : fatal error LNK1120: 5 unresolved externals
> ninja: build stopped: subcommand failed.
> ```
> 
> 我无法在本地计算机上重现此内容。使用Visual Studio 2019 16.5.3。 `libepoxy `已更新至1.5.4。您能否尝试更新vcpkg并重建它？

Yeah! Ok!

**Comment by xiaoxi-li** [comment]
> > 对不起，我错了。我以前没注意到。
> > ```
> > FAILED: src/epoxy-0.dll 
> > link @src/epoxy-0.dll.rsp
> >    Creating library src\\epoxy.lib and object src\\epoxy.exp
> > meson-generated_.._gl_generated_dispatch.c.obj : error LNK2019: unresolved external symbol epoxy_gles1_dlsym referenced in function gl_provider_resolver
> > meson-generated_.._gl_generated_dispatch.c.obj : error LNK2019: unresolved external symbol epoxy_gles2_dlsym referenced in function gl_provider_resolver
> > meson-generated_.._gl_generated_dispatch.c.obj : error LNK2019: unresolved external symbol epoxy_conservative_has_gl_extension referenced in function gl_provider_resolver
> > meson-generated_.._wgl_generated_dispatch.c.obj : error LNK2019: unresolved external symbol epoxy_gl_dlsym referenced in function wgl_provider_resolver
> > dispatch_common.c.obj : error LNK2001: unresolved external symbol epoxy_gl_dlsym
> > dispatch_common.c.obj : error LNK2019: unresolved external symbol epoxy_has_gl_extension referenced in function epoxy_glsl_version
> > src\epoxy-0.dll : fatal error LNK1120: 5 unresolved externals
> > ninja: build stopped: subcommand failed.
> > ```
> > 
> > 
> > 我无法在本地计算机上重现此内容。使用Visual Studio 2019 16.5.3。 `libepoxy `已更新至1.5.4。您能否尝试更新vcpkg并重建它？
> 
> Yeah! Ok!

But sorry,it also fail when I built it again
Error: Building package libepoxy:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libepoxy:x64-windows
  Vcpkg version: 2020.02.04-nohash

**Comment by NancyLi1013** [comment]
@xiaoxi-li 

```
File "D:\obj\Windows-Release\37amd64_Release\msi_python\zip_amd64\pathlib.py", line 1200, in read_text
UnicodeDecodeError: 'gbk' codec can't decode byte 0x84 in position 385754: illegal multibyte sequence
```
It seems that you used `python `that is installed by yourself.

Could you please remove python and rebuild this?

**Comment by carnoxen** [comment]
I met this issue, too. Should I change my system locale to english?

**Comment by carnoxen** [comment]
Here's my error log
```
  File "D:\obj\Windows-Release\37amd64_Release\msi_python\zip_amd64\pathlib.py", line 1200, in read_text
UnicodeDecodeError: 'cp949' codec can't decode byte 0xec in position 385988: illegal multibyte sequence
```

**Comment by NancyLi1013** [comment]
@carnoxen 

You don't need to change your system to English, just make sure you have installed English package in Visual Studio.

Please help check if you installed python on your machine manually. If so, please try to remove it and use `python `provided by vcpkg.

**Comment by Chris48193** [comment]
Hello Guys!
I had the same problem and ran my command line as administrator and the problem was fixed.

**Comment by luojia65** [comment]
Same issue, not resolved after run as admin, remove python (I don't have python installed) and installing English support for VS

**Comment by NancyLi1013** [comment]
Hi all,
Thanks for posting this issue and joining in the discussion.
Could you please refer to this https://github.com/microsoft/vcpkg/issues/12148#issuecomment-652303702 and try to rebuild this?

**Comment by NancyLi1013** [comment]
Hi all,
@xiaoxi-li @carnoxen @luojia65 

Could you please try the workaround https://github.com/microsoft/vcpkg/issues/12865#issuecomment-673216071?

**Comment by NancyLi1013** [comment]
I'm closing this issue for now since there is no response in a long time.
