### ISSUE TITLE
[ffmpeg:arm64-android] build failure

### ISSUE THREAD

**Issue by sopyer** [microsoft/vcpkg#11522]
**Host Environment**
- OS: Windows 10 Pro 1909 build 18363.836
- Compiler: Visual Studio 2019 (ver 16.5.5)

**To Reproduce**
`./vcpkg install ffmpeg:arm64-android`

**Failure logs** 
```

Computing installation plan...
The following packages will be built and installed:
    ffmpeg[avresample,core]:arm64-android
Starting package 1/1: ffmpeg:arm64-android
Building package ffmpeg[avresample,core]:arm64-android...
-- Using cached D:/dev/vcpkg/downloads/ffmpeg-ffmpeg-n4.2.tar.gz
-- Using source at D:/dev/vcpkg/buildtrees/ffmpeg/src/n4.2-a4d149a5c6
-- Building Options: --enable-asm --enable-yasm --disable-doc --enable-debug --enable-runtime-cpudetect --disable-openssl --disable-ffmpeg --disable-ffplay --disable-ffprobe --disable-libvpx --disable-libx264 --disable-opencl --disable-lzma --disable-bzlib --enable-avresample --disable-cuda --disable-nvenc --disable-cuvid --disable-libnpp  --enable-cross-compile --target-os=win32 --arch=arm64
-- Building Release Options:
-- Building ffmpeg for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: /bin/bash --noprofile --norc D:/dev/vcpkg/ports/ffmpeg/build_linux.sh D:/dev/vcpkg/buildtrees/ffmpeg/arm64-android-rel D:/dev/vcpkg/buildtrees/ffmpeg/src/n4.2-a4d149a5c6 D:/dev/vcpkg/packages/ffmpeg_arm64-android "--enable-asm --enable-yasm --disable-doc --enable-debug --enable-runtime-cpudetect --disable-openssl --disable-ffmpeg --disable-ffplay --disable-ffprobe --disable-libvpx --disable-libx264 --disable-opencl --disable-lzma --disable-bzlib --enable-avresample --disable-cuda --disable-nvenc --disable-cuvid --disable-libnpp  --enable-cross-compile --target-os=win32 --arch=arm64 "
    Working Directory: D:/dev/vcpkg/buildtrees/ffmpeg/arm64-android-rel
    Error code: The system cannot find the file specified
    See logs for more information:

Call Stack (most recent call first):
  ports/ffmpeg/portfile.cmake:202 (vcpkg_execute_required_process)
  scripts/ports.cmake:90 (include)


Error: Building package ffmpeg:arm64-android failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: ffmpeg:arm64-android
  Vcpkg version: 2020.02.04-nohash-external

Additionally, attach any relevant sections from the log files above.
```

**Additional context**
Added manually arm64-android triplet for static library compilation
```
set(VCPKG_TARGET_ARCHITECTURE arm64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_CMAKE_SYSTEM_NAME Android)
```

**Comment by rib** [comment]
Just trying this I got an _almost_ identical build failure except I see it failing to run `/bin/sh ./build.sh` instead of ` /bin/bash --noprofile --norc D:/dev/vcpkg/ports/ffmpeg/build_linux.sh`

**Comment by rib** [comment]
Btw, just to mention that I was able to successfully build ffmpeg:arm64-android from Linux instead of Windows.

(2020.06.15-unknownhash)

**Comment by rib** [comment]
Oh, actually I take that back - what I actually got was an amd64 build, not an Android build :)

**Comment by bmegli** [comment]
# Linux arm64-android build ending up as host build

Backtracking the build process:

1. The final configuration and build is executed by [build.sh.in](https://github.com/microsoft/vcpkg/blob/615547c1d5b363d3586d2012c4cd7d075a0516b8/ports/ffmpeg/build.sh.in#L94) `build_ffmpeg`
2. The `@CONFIGURE_OPTIONS@` determines build type
3. The `@CONFIGURE_OPTIONS@` are set in [port](https://github.com/microsoft/vcpkg/blob/615547c1d5b363d3586d2012c4cd7d075a0516b8/ports/ffmpeg/portfile.cmake#L646) from all gathered options.
4. The port is [missing path](https://github.com/microsoft/vcpkg/blob/615547c1d5b363d3586d2012c4cd7d075a0516b8/ports/ffmpeg/portfile.cmake#L566) for ANDROID target 

It is enough to add case for:
`if(VCPKG_TARGET_IS_ANDROID)` to fix this problem..

**Comment by jheaff1** [comment]
I too am facing the same issue. I am attempting to build ffmpeg for the `arm-android` triplet yet x64 libraries are built

**Comment by Adela0814** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.

**Comment by bmegli** [comment]
@Adela0814,

In case of building from Linux there were no changes addressing this issue.

The state is still the same - the arm64-android build ends up with x86-64 binaries build (maybe just host)
- the reason was described [here](https://github.com/microsoft/vcpkg/issues/11522#issuecomment-914992259)
- the outcome was analyzed [here](https://github.com/microsoft/vcpkg/issues/11522#issuecomment-907189502)

This happens for both static build and dynamic build (with modified triplet).

I can't say about building from Windows but I would expect the root cause to be the same.

-----------------------------------------------------

I have no way to reopen the issue.

You may keep it closed but I expect the community will simply create duplicate confusing issues.

If anything, at least for building from Linux, the issue could be made more specific like:
 - [ffmpeg:arm64-android] build on Linux ends up with x86-64 architecture (or just host arch)
