### ISSUE TITLE
vcpkg import <pkg>

### ISSUE THREAD

**Issue by Voskrese** [Microsoft/vcpkg#1153]
Не судите строго )) я только начинаю разбираться
есть такая функция как импорт

> .\vcpkg /?
> vcpkg import <pkg>              Import a pre-built library

> E:\tools\vcpkg>.\vcpkg import
> Error: `import` requires 3 arguments, but 0 were provided
> Example:
>   vcpkg import C:\path\to\CONTROLfile C:\path\to\includedir C:\path\to\projectdir

Пытаюсь собрать либы для и сам mailcore2
https://github.com/MailCore/mailcore2/blob/master/build-windows/README.md
~~при сборке **проверка на зависимость** icu
но она не подхватывается с проекта vcpkg 
естественно интеграция была произведена vcpkg integrate install~~

> ~~vcpkg list
> icu:x86-windows             59.1-1           Mature and widely used Unicode and localization l...~~

> ~~vcpkg install icu
> The following packages are already installed:
>     icu:x86-windows
> Package icu:x86-windows is already installed~~

**подхватился**
У меня два вопроса:
**как правильно прописать в проекте на include, lib от vcpkg?** ~~смаке их не видит~~ 

_____________________________________________________

> E:\tools\SRC\mailcore2>cmake . -DCMAKE_TOOLCHAIN_FILE=E:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x86-windows -DCMAKE_BUILD_TYPE=Release -DVCPKG_PLATFORM_TOOLSET=v140 -DLIBRARY_DIRS="E:\tools\SRC\mailcore2\Externals\lib;E:\tools\vcpkg\installed\x86-windows\lib" -DINCLUDE_DIR="E:\tools\vcpkg\installed\x86-windows\include;E:\tools\SRC\mailcore2\Externals\include" -G "Visual Studio 14 2015"

> -- The C compiler identification is MSVC 19.0.24210.0
> -- The CXX compiler identification is MSVC 19.0.24210.0
> -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
> -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
> -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Found icu4c
> CMake Error at CMakeLists.txt:88 (message):
>   ERROR: Could not find ctemplate
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "E:/tools/SRC/mailcore2/CMakeFiles/CMakeOutput.log".

> E:\tools\SRC\mailcore2>ls -Al E:\tools\SRC\mailcore2\Externals\lib\ | grep libctemplate.lib
> -rw-r--r-- 1 Nikolay 197609   331120 Nov 24  2014 libctemplate.lib

_____________________________________________________
и как подключить уже имеющиеся скомпилированные с проекта?
CTemplate.    libEtPan.    Cyrus SASL.    LibXML 2.    Tidy HTML5,    zlib,    icu4c, OpenSSL and pthread for win32

_____________________________________________________
п.с. и еще пару команд не документированных, где можно прочитать описание и возможности?
vcpkg/toolsrc/src/commands_help.cpp 
vcpkg/toolsrc/src/commands_available_commands.cpp
vcpkg/toolsrc/include/vcpkg_Commands.h

> E:\tools\vcpkg>vcpkg portsdiff
> The argument should be a branch/tag/hash to checkout.
> Example:
>   vcpkg portsdiff mybranchname

> E:\tools\vcpkg>vcpkg depend-info

> E:\tools\vcpkg>vcpkg build-external /?
> Error: `build-external` requires 2 arguments, but 1 were provided
> Example:
>   vcpkg build_external zlib2 C:\path\to\dir\with\controlfile\

как я понял компилирует все библиотеки?  1/230

> E:\tools\vcpkg>vcpkg ci
> Starting package 1/230: ace:x86-windows
> Building package ace:x86-windows...
> ....

**Comment by Voskrese** [comment]
vcpkg import Import a pre-built library

> Example:
>     vcpkg import C:\path\to\CONTROLfile C:\path\to\includedir C:\path\to\projectdir

допустим нам нужно подключить библиотеку ctemplate
http://d.etpan.org/mailcore2-deps/ctemplate-win32/

скачали, распаковали, получили

> E:\tools\SRC\ctemplate-win32-1>tree /F
> ├───include
> │   └───ctemplate
> │           find_ptr.h
> │           per_expand_data.h
> │           str_ref.h
> │           template.h
> │           template_annotator.h
> │           template_cache.h
> │           template_dictionary.h
> │           template_dictionary_interface.h
> │           template_emitter.h
> │           template_enums.h
> │           template_modifiers.h
> │           template_namelist.h
> │           template_pathops.h
> │           template_string.h
> │
> ├───lib
> │       libctemplate.dll
> │       libctemplate.exp
> │       libctemplate.lib
> │       libctemplate.pdb
> │
> └───lib64
>         libctemplate.dll
>         libctemplate.exp
>         libctemplate.lib
>         libctemplate.pdb

создали в коне папки файл **CONTROL** с примерным содеражвнием

> Package: ctemplate
> Version: 0
> Architecture: x86-windows
> Multi-Arch: same
> Description: ctemplate 

подключаем

> vcpkg import E:\temp\ctemplate-win32-1\CONTROL E:\temp\ctemplate-win32-1\include E:\temp\ctemplate-win32-1

ошибка
`The path E:\temp\ctemplate-win32-1\Debug is not a directory`

создаем, забегу вперед, будет подобная ошибка только с папкой Release, в которой должны лежать релизные либы
```
md E:\temp\ctemplate-win32-1\Debug
ren lib Release
```

повторяем подключение
```
vcpkg import E:\temp\ctemplate-win32-1\CONTROL E:\temp\ctemplate-win32-1\include E:\temp\ctemplate-win32-1
```
получаем, _папка include задвоилась_

> E:\tools\vcpkg\packages\ctemplate_x86-windows>tree /F
> 
> │   CONTROL
> │
> ├───bin
> │       libctemplate.dll
> │
> ├───debug
> │   ├───bin
> │   │       libctemplate.dll
> │   │
> │   └───lib
> │           libctemplate.lib
> │
> ├───include
> │   │   find_ptr.h
> │   │   per_expand_data.h
> │   │   str_ref.h
> │   │   template.h
> │   │   template_annotator.h
> │   │   template_cache.h
> │   │   template_dictionary.h
> │   │   template_dictionary_interface.h
> │   │   template_emitter.h
> │   │   template_enums.h
> │   │   template_modifiers.h
> │   │   template_namelist.h
> │   │   template_pathops.h
> │   │   template_string.h
> │   │
> │   └───ctemplate
> │           find_ptr.h
> │           per_expand_data.h
> │           str_ref.h
> │           template.h
> │           template_annotator.h
> │           template_cache.h
> │           template_dictionary.h
> │           template_dictionary_interface.h
> │           template_emitter.h
> │           template_enums.h
> │           template_modifiers.h
> │           template_namelist.h
> │           template_pathops.h
> │           template_string.h
> │
> └───lib
>         libctemplate.lib

**в итоге, как использовать импортированную библиотеку? vcpkg ее не видит, смаке так же**
vcpkg list | grep libctemplate - ее нет
cmake при сборке не видит

**Comment by Voskrese** [comment]
**собственно это баг или я где то не доглядел?** переименовав либу, cmake отработал правильно и нашел зависимость

```ls E:\tools\vcpkg\installed\x86-windows\lib\ | grep ctemplate```

> libctemplate.lib

`ren E:\tools\vcpkg\installed\x86-windows\lib\libctemplate.lib ctemplate.lib`
`ls E:\tools\vcpkg\installed\x86-windows\lib\ | grep ctemplate`

> ctemplate.lib


`cmake . -DCMAKE_TOOLCHAIN_FILE=E:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x86-windows -DCMAKE_BUILD_TYPE=Release -DVCPKG_PLATFORM_TOOLSET=v140 -G "Visual Studio 14 2015"`
-- Found icu4c
**-- Found ctemplate**

**Comment by ras0219-msft** [comment]
Hi @Voskrese! I don't speak Russian, so sorry in advance for any mistranslations 😃.

> Пытаюсь собрать либы для и сам mailcore2

The `import` command unfortunately has been used very little and is lacking in documentation. It's intended as a quick-and-dirty way to import MSBuild projects that you've built via Visual Studio using Vcpkg.

Additionally, prebuilt binaries for larger projects cause a bunch of problems when mixing multiple libraries. If you want to import a bigger library like MailCore2, I'd really recommend making a portfile for it and building from source.

> как правильно прописать в проекте на include, lib от vcpkg? смаке их не видит
...
-- Found icu4c
CMake Error at CMakeLists.txt:88 (message):
ERROR: Could not find ctemplate

I think that cmake found icu4 directly, however we certainly don't have ctemplate packaged. I think the best way to handle this would be to first package ctemplate, then move on to mailcore2.

> и как подключить уже имеющиеся скомпилированные с проекта?

Importing prebuilt binaries with dependencies causes problems when mixing with the rest of the system, so I wouldn't recommend using it for this case. If you only want to use MailCore2, you could use their prebuilt binaries, but if you want to mix it with vcpkg, you'll really need to create individual source builds for each library.

It looks like we do have libxml2, zlib, icu, and openssl already packaged.

> п.с. и еще пару команд не документированных, где можно прочитать описание и возможности?

We do have a few undocumented commands that either have lots of edge cases, aren't generally useful, or we don't think are "fully thought through". We don't want anyone to accidentally depend on them for some important process, so we haven't documented them. The best way to understand what they do if you're simply curious would be to read the code 😜.

---

If you'd like to attempt to use the prebuilt binaries in spite of my warnings above, the best way would be to write a portfile that downloads and places the binaries in the right place. Take a look at redshell[1] or openvr[2] for some examples of this.

You may also find `vcpkg owns` to be useful when debugging. Only the files in `installed\` will be found, which is also where `owns` searches.

[1] https://github.com/Microsoft/vcpkg/blob/1913f6602f785e902d8185f322a50748fffbeb67/ports/redshell/portfile.cmake
[2] https://github.com/Microsoft/vcpkg/blob/1913f6602f785e902d8185f322a50748fffbeb67/ports/openvr/portfile.cmake

---

>собственно это баг или я где то не доглядел? переименовав либу, cmake отработал правильно и нашел зависимость

This is almost certainly a bug in mailcore2's cmake file. They are looking for "ctemplate.lib"[3] in cmake, but their prebuilt library is called "libctemplate" for some reason.

[3] https://github.com/MailCore/mailcore2/blob/master/CMakeLists.txt#L82-L85

**Comment by Voskrese** [comment]
Машинный перевод спасает и стирает языковой барьер ;) Спасибо за ответ
