### ISSUE TITLE
[vcpkg metrics] Users should be able to disable metrics after build

### ISSUE THREAD

**Issue by strega-nil** [microsoft/vcpkg#11530]
Users should be able to avoid metrics by setting the environment variable `VCPKG_DISABLE_METRICS`, or by passing the `-disable-metrics` flag to vcpkg.

Additionally, as a minor update, we should rewrite the metrics library to use the JSON library which is now built in, as opposed to using string interpolation

**Comment by MikeGitb** [comment]
YEs please for the environment variable. Everytime I re-bootstrap vcpkg I forget to set the flag (or what it is spelled exactly) so I then immediately re-re-boostrap vcpkg with the right setting.

Btw.: I'd be much more willing to upload metrics if you'd share the aggregated statistics with the community.

**Comment by strega-nil** [comment]
Closed as completed in #11542 :)
