### ISSUE TITLE
mimalloc find_package does not work, missing dlsl

### ISSUE THREAD

**Issue by MeirBon** [microsoft/vcpkg#11536]
**Describe the bug**
mimalloc requires a few dlls to be included with the binary for it to run. These dlls are [available in the repository](https://github.com/microsoft/mimalloc/tree/master/bin) in the bin folder. Without these, a program linked with mimalloc will simply not run.

Also, the vcpkg instruction suggests finding mimalloc using the command `find_package(mimalloc CONFIG REQUIRED)`, however, CMake will not accept the 1.6 version for this command. Instead, this is logged:
```
Could not find a configuration file for package "mimalloc" that is
Could not find a configuration file for package "mimalloc" that is compatible with requested version "".

The following configuration files were considered but not accepted:

C:/vcpkg/installed/x64-windows/share/mimalloc/mimalloc-config.cmake, version: 1.6
```

**Environment**
- OS: Windows
- Compiler: clang 10.0, msvc included with Visual Studio 2019

**To Reproduce**
1. ./vcpkg install mimalloc
2. Create a CMake project that links to mimalloc as follows:
``` CMake
find_package(mimalloc CONFIG REQUIRED)
target_link_libraries(main PRIVATE mimalloc mimalloc-static)
```
3. Configuring the project will give the error shown above.
4. Link to mimalloc using the following:
``` CMake
find_package(mimalloc 1.6 CONFIG REQUIRED)
target_link_libraries(main PRIVATE mimalloc mimalloc-static)
```
5. Compilation and linking should now be succesful, but at runtime this error is displayed:
``` 
The code execution cannot proceed because mimalloc-redirect.dll was not found. Reinstalling the program may fix this problem.
```

**Expected behavior**
- The commands provided by vcpkg should not throw any errors about not finding a package.
- The required binaries (mimalloc-redirect.dll) should be provided by vcpkg.

**Comment by LilyWangL** [comment]
@MeirBon Thanks for posting this issue. I submit a PR to fix this issue, could you please help to verify this PR is useful for your project?

**Comment by MeirBon** [comment]
@LilyWangL I just tested it and it works 😃 I don't have to add the missing dlls manually anymore. Thank you!
