### ISSUE TITLE
[New Port Request] ROOT

### ISSUE THREAD

**Issue by Kinexity** [microsoft/vcpkg#11541]
Library name: ROOT

Library description: ROOT is a modular scientific software toolkit. It provides all the functionalities needed to deal with big data processing, statistical analysis, visualisation and storage.

Source repository URL: https://github.com/root-project/root

Project homepage: https://root.cern.ch/

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
