### ISSUE TITLE
[libflac[core]:x86-windows] build failure

### ISSUE THREAD

**Issue by Christsnatcher** [microsoft/vcpkg#11551]
**Host Environment**
Windows 8.1 x64
MSVC++ 14.26 VS 2019 v16.6

**To Reproduce**
In cmd: **vcpkg install libflac[core]:x86-windows** 

fails with the following error message:
```
D:\Code\Repos\vcpkg>vcpkg install libflac[core]:x86-windows
Computing installation plan...
The following packages will be built and installed:
    libflac[core]:x86-windows
Starting package 1/1: libflac:x86-windows
Building package libflac[core]:x86-windows...
-- Using cached D:/Code/Repos/vcpkg/downloads/xiph-flac-ce6dd6b5732e319ef60716d9cc9af6a836a4011a.tar.gz
-- Using source at D:/Code/Repos/vcpkg/buildtrees/libflac/src/a836a4011a-c7a3381410
-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v
    Working Directory: D:/Code/Repos/vcpkg/buildtrees/libflac/x86-windows-dbg
    See logs for more information:
      D:\Code\Repos\vcpkg\buildtrees\libflac
[libflac-logs.zip](https://github.com/microsoft/vcpkg/files/4674109/libflac-logs.zip)
\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/libflac/portfile.cmake:21 (vcpkg_install_cmake)
  scripts/ports.cmake:90 (include)


Error: Building package libflac:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libflac:x86-windows
  Vcpkg version: 2020.02.04-nohash
```

**Additional context**
-Building the 64-bit library works flawlessly.
-I see a connection to pull request https://github.com/microsoft/vcpkg/pull/11152, as the error messages shown there are (almost) identical with the one I encounter and it's explicitly mentioned that the x86 and x64 headers differ for this port, which explains the observation mentioned above.

Thank you very much!
[libflac-logs.zip](https://github.com/microsoft/vcpkg/files/4674115/libflac-logs.zip)

**Comment by LilyWangL** [comment]
Thanks for posting this issue. I can't reproduce this issue locally. Could you remove _[VCPKG_PATH]/buildtrees/libflac_ and install `libflac[core]:x86-windows` again?

**Comment by Christsnatcher** [comment]
Hello. I already did this prior to posting the issue, removed all traces of libflac from all vcpkg folders to no avail unfortunatley. I also tried to build against other Windows SDK versions that the latest, again without success. The x64 build does always succeed, the x86 one never.

Thank you for helping me, esp. since this is a quite important lib and required dependency of e.g. libsndfile[core,external-libs]:x86-windows and sndfile[core,external-libs]:x86-windows.

**Comment by LilyWangL** [comment]
Hi, I download `libflac-logs.zip`, but I can't find the more error message in `install-x86-windows-dbg-out.log`, could you please provide the error log `install-x86-windows-dbg-out.log` again?
Thanks.

**Comment by Christsnatcher** [comment]
Hello, yes, that's correct. The only error message found in this file is the last line

**ninja: build stopped: subcommand failed.**

The error message shown in the command window somehow don't get logged. Anyways, here's everything again:

**CMD windows message:**

```
D:\Code\Repos\vcpkg>vcpkg install libflac[core]:x86-windows
Computing installation plan...
The following packages will be built and installed:
    libflac[core]:x86-windows
Starting package 1/1: libflac:x86-windows
Building package libflac[core]:x86-windows...
-- Downloading https://github.com/xiph/flac/archive/ce6dd6b5732e319ef60716d9cc9af6a836a4011a.tar.gz...
-- Extracting source D:/Code/Repos/vcpkg/downloads/xiph-flac-ce6dd6b5732e319ef60716d9cc9af6a836a4011a.tar.gz
-- Applying patch D:/Code/Repos/vcpkg/ports/libflac/uwp-library-console.patch
-- Applying patch D:/Code/Repos/vcpkg/ports/libflac/uwp-createfile2.patch
-- Using source at D:/Code/Repos/vcpkg/buildtrees/libflac/src/a836a4011a-c7a3381410
-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v
    Working Directory: D:/Code/Repos/vcpkg/buildtrees/libflac/x86-windows-dbg
    See logs for more information:
      D:\Code\Repos\vcpkg\buildtrees\libflac\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/libflac/portfile.cmake:21 (vcpkg_install_cmake)
  scripts/ports.cmake:90 (include)


Error: Building package libflac:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libflac:x86-windows
  Vcpkg version: 2020.02.04-nohash
```
To be on the 100% "safe side" I set up a fresh vcpkg installation and tried to install only libflac[core]:x86-windows, which failed with the error message shown above. Then I zipped the entire output, except for the actual src, find the .zip as attachment.

Again, thank you very much for helping me, cheers!
[libflac[core]x86-windows.zip](https://github.com/microsoft/vcpkg/files/4699326/libflac.core.x86-windows.zip)

**Comment by Christsnatcher** [comment]
I apologize, everything was my "fault", mea culpa. I had an x64 build of NASM in "C:\Program Files\NASM", which CMake apparently found and decided to use "later" for building, and this particular NASM build caused the actual fatal error. I honestly don't know if NASM is only able to assemble files of its own bitness or if the NASM.exe itself is faulty, but after removing it building libflac[core]:x86-windows worked flawlessly again.

Thank you very much, I'll close the issue now.
