### ISSUE TITLE
Could not find Visual Studio. VS2015 or VS2017 

### ISSUE THREAD

**Issue by steverosky** [microsoft/vcpkg#11553]
got this error when trying to use vcpkg to intall c++ libraries...but vscode version 1.45.1 installed

_```
Could not find Visual Studio. VS2015 or VS2017 (with C++) needs to be installed.
At C:\Users\User\vcpkg\scripts\bootstrap.ps1:143 char:9
+         throw "Could not find Visual Studio. VS2015 or VS2017 (with C ...
+     
    + CategoryInfo          : OperationStopped: (Could not find ...o be installed.:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find Visual Studio. VS2015 or VS2017 (with C++) needs to be installed.
```
-

**Comment by NancyLi1013** [comment]
Hi @steverosky 

Thanks for posting this issue.

Since VS code has not been supported in vcpkg yet. You still need to install Vsual Studio 2017 or 2019.

**Comment by NancyLi1013** [comment]
@steverosky 
If you want to care about the support for Visual Studio Code, you can pay attention to the progress of this issue #10217.
 I'm closing this issue for now.

**Comment by steverosky** [comment]
thank you soo much
