### ISSUE TITLE
[New Port Request] openXLSX

### ISSUE THREAD

**Issue by tlogger** [microsoft/vcpkg#11555]
Library name: openXLSX

Library description: cross platform excel library

Source repository URL: https://github.com/troldal/OpenXLSX

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
