### ISSUE TITLE
[boost] remove --recurse fails and needs 4 additional removes

### ISSUE THREAD

**Issue by diablodale** [microsoft/vcpkg#11552]
`vcpkg remove boost-vcpkg-helpers --recurse` fails to remove all of boost. It requires an additional 3 `remove` to finally remove all of boost. 🤛🤛🤛

This errant behavior was exposed due to failure of `upgrade` https://github.com/microsoft/vcpkg/issues/11482 and the boost port requiring special and unique removal procedure https://github.com/microsoft/vcpkg/issues/8486#issuecomment-580928157

## Setup

* Windows 10
* vcpkg
* boost 1.72.0 installed

## Repro

1. `vcpkg remove boost-vcpkg-helpers --recurse`. Notice is spelled *plural*
2. `vcpkg list`
3. Boost is still there. Was `boost-vcpkg-helper` always there? Notice it is spelled *singular*
4. `vcpkg remove boost-vcpkg-helper --recurse`
5. `vcpkg list`
6. Still more boost. And now I can see there is `boost-build`
7. `vcpkg remove boost-build --recurse`
8. `vcpkg list`
9. Yet more boost. Now there is `boost-modular-build-helper`
10. `vcpkg remove boost-modular-build-helper --recurse`
11. `vcpkg list`

## Result

Boost is gone after four separate removals, each one a unique boost-only command in a unique boost only removal process.

## Expected

`vcpkg remove boost` should work. Full stop. No special procedure. No wack-a-mole with 4 seperate `remove` commands.

## Cute animal pic

![mole-cat](https://user-images.githubusercontent.com/679350/82761925-194dbb00-9dfe-11ea-9030-56e15cc490ea.gif)

**Comment by PhoebeHui** [comment]
@diablodale, ./vcpkg remove xxx --recurse only remove current port and all ports which depends on it.

For boost, boost-modular-build-helper and boost-build doesn't rely on boost-vcpkg-helpers, so they hasn't been removed. I tried, It should requres 3 steps to remove all compoments, I think this is expected.
 
1 ./vcpkg remove boost-vcpkg-helpers --recurse
2. ./vcpkg remove boost-modular-build-helper
3. ./vcpkg remove boost-build

**Comment by yurybura** [comment]
@diablodale @PhoebeHui I can add missed dependencies to the `boost` port.

**Comment by PhoebeHui** [comment]
@yurybura, thanks!

However I think If they don't rely on each other, we should not add them. It seems that boost-modular-build-helper and boost-build doesn't need boost-vcpkg-helpers.

**Comment by PhoebeHui** [comment]
Currently, you can simply remove all boost components via

./vcpkg remove boost-uninstall --recurse

**Comment by diablodale** [comment]
How can this be documented?
How can a user that wants to install, and then remove boost using vcpkg know this special uninstall procedure?
Can other defective uninstall procedures be disabled?

**Comment by PhoebeHui** [comment]
@diablodale, this is a temporary workaround, the future it would use 'vcpkg remove boost' to remove the all components.

See more discussions in https://github.com/microsoft/vcpkg/pull/12851.

**Comment by diablodale** [comment]
hahaha, got it. I read the code in the PR you linked. Seems that is a clear way to document it. Works for me. 😉
