### ISSUE TITLE
[New Port Request] XLSX I/O

### ISSUE THREAD

**Issue by tlogger** [microsoft/vcpkg#11556]
Library name: XLSX I/O

Library description: cross platform excel read/write library

Source repository URL: https://sourceforge.net/projects/xlsxio/

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue and continue the PR, but we're closing it for now.
