### ISSUE TITLE
[protobuf] update to 3.12.1

### ISSUE THREAD

**Issue by przole** [microsoft/vcpkg#11566]
Library name: protobuf

New version number: 3.12.1

https://github.com/protocolbuffers/protobuf/releases/tag/v3.12.1

**Comment by memetea** [comment]
please synchronize x84 and x64 version.  

currently the x86-windows protoc version is 3.12.0. but x64-windows protoc version is 3.11.4.


```
> E:\vcpkg\installed\x86-windows\tools\protobuf\protoc --version

libprotoc 3.12.0

> E:\vcpkg\installed\x64-windows\tools\protobuf\protoc --version

libprotoc 3.11.4
```

**Comment by przole** [comment]
In the meantime, a new version has appeared:

https://github.com/protocolbuffers/protobuf/releases/tag/v3.12.3
