### ISSUE TITLE
amqpcpp update to 4.1.7

### ISSUE THREAD

**Issue by przole** [microsoft/vcpkg#11563]
Library name: amqpcpp

New version number: 4.1.7

https://github.com/CopernicaMarketingSoftware/AMQP-CPP/releases/tag/v4.1.7

**Comment by sa4044** [comment]
! [icon_com partyjoy weparty_14] (https://github.com/microsoft/vcpkg/assets/166659172/250aaead-53b6-4b0b-9a1d-39ece8eebc77)Can you make an order? How to buy or ship in a banned country?
