### ISSUE TITLE
[openssl-windows:x86-windows] build failure

### ISSUE THREAD

**Issue by Ravenwater** [microsoft/vcpkg#11572]
**Host Environment**
- OS: Windows10
- Compiler: revision 
Microsoft Visual Studio Professional 2017 Version 15.9.21
VisualStudio.15.Release/15.9.21+28307.1064
Microsoft .NET Framework Version 4.8.03752

**To Reproduce**
`./vcpkg install grpc`

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.
```
tomtz@SW-LAPTOP-250 MINGW64 /C/Users/tomtz/Documents/dev/clones/vcpkg (master)
$ vcpkg search grpc
grpc                 1.28.1-1         An RPC library and framework
grpc[absl-sync]                       Use abseil synchronization module

If your library is not listed, please open an issue at and/or consider making a pull request:
    https://github.com/Microsoft/vcpkg/issues

tomtz@SW-LAPTOP-250 MINGW64 /C/Users/tomtz/Documents/dev/clones/vcpkg (master)
$ vcpkg install grpc
Computing installation plan...
The following packages will be built and installed:
  * abseil[core]:x86-windows
  * c-ares[core]:x86-windows
    grpc[core]:x86-windows
  * openssl[core]:x86-windows
  * openssl-windows[core]:x86-windows
  * upb[core]:x86-windows
  * zlib[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/7: abseil:x86-windows
Building package abseil[core]:x86-windows...
-- Note: abseil only supports static library linkage. Building static library.
-- Downloading https://github.com/abseil/abseil-cpp/archive/06f0e767d13d4d68071c4fc51e25724e0fc8bc74.tar.gz...
-- Extracting source C:/Users/tomtz/Documents/dev/clones/vcpkg/downloads/abseil-abseil-cpp-06f0e767d13d4d68071c4fc51e25724e0fc8bc74.tar.gz
-- Applying patch fix-uwp-build.patch
-- Applying patch fix-MSVCbuildfail.patch
-- Applying patch fix-lnk2019-error.patch
-- Using source at C:/Users/tomtz/Documents/dev/clones/vcpkg/buildtrees/abseil/src/4e0fc8bc74-685d00770e
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Installing: C:/Users/tomtz/Documents/dev/clones/vcpkg/packages/abseil_x86-windows/share/abseil/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package abseil[core]:x86-windows... done
Installing package abseil[core]:x86-windows...
Installing package abseil[core]:x86-windows... done
Elapsed time for package abseil:x86-windows: 4.027 min
Starting package 2/7: c-ares:x86-windows
Building package c-ares[core]:x86-windows...
-- Downloading https://github.com/c-ares/c-ares/archive/9f1fdbf5dd633f81352fac0d6bc0d0c4d45be459.tar.gz...
-- Extracting source C:/Users/tomtz/Documents/dev/clones/vcpkg/downloads/c-ares-c-ares-9f1fdbf5dd633f81352fac0d6bc0d0c4d45be459.tar.gz
-- Using source at C:/Users/tomtz/Documents/dev/clones/vcpkg/buildtrees/c-ares/src/c4d45be459-24e25a63ee
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package c-ares[core]:x86-windows... done
Installing package c-ares[core]:x86-windows...
Installing package c-ares[core]:x86-windows... done
Elapsed time for package c-ares:x86-windows: 4.473 min
Starting package 3/7: openssl-windows:x86-windows
Building package openssl-windows[core]:x86-windows...
-- Downloading http://strawberryperl.com/download/5.30.0.1/strawberry-perl-5.30.0.1-32bit.zip...
-- Downloading https://www.openssl.org/source/openssl-1.1.1d.tar.gz...
-- Extracting source C:/Users/tomtz/Documents/dev/clones/vcpkg/downloads/openssl-1.1.1d.tar.gz
-- Using source at C:/Users/tomtz/Documents/dev/clones/vcpkg/buildtrees/openssl-windows/src/openssl-1-b1f8ae3e6c
-- Downloading http://www.nasm.us/pub/nasm/releasebuilds/2.14.02/win32/nasm-2.14.02-win32.zip...
-- Downloading http://download.qt.io/official_releases/jom/jom_1_1_3.zip...
-- Copying openssl release source files...
-- Copying openssl release source files... done
-- Configure x86-windows-rel
-- Configure x86-windows-rel done
-- Build x86-windows-rel
-- Build x86-windows-rel done
-- Copying openssl debug source files...
-- Copying openssl debug source files... done
-- Configure x86-windows-dbg
-- Configure x86-windows-dbg done
-- Build x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: nmake -f makefile install_sw install_ssldirs
    Working Directory: C:/Users/tomtz/Documents/dev/clones/vcpkg/buildtrees/openssl-windows/x86-windows-dbg
    Error code: 2
    See logs for more information:
      C:\Users\tomtz\Documents\dev\clones\vcpkg\buildtrees\openssl-windows\build-x86-windows-dbg-1-out.log
      C:\Users\tomtz\Documents\dev\clones\vcpkg\buildtrees\openssl-windows\build-x86-windows-dbg-1-err.log

Call Stack (most recent call first):
  ports/openssl-windows/portfile.cmake:131 (vcpkg_execute_required_process)
  scripts/ports.cmake:90 (include)


Error: Building package openssl-windows:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openssl-windows:x86-windows
  Vcpkg version: 2020.02.04-nohash

Additionally, attach any relevant sections from the log files above.
```
[build-x86-windows-dbg-1-err.log](https://github.com/microsoft/vcpkg/files/4679000/build-x86-windows-dbg-1-err.log)
[build-x86-windows-dbg-1-out.log](https://github.com/microsoft/vcpkg/files/4679001/build-x86-windows-dbg-1-out.log)

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

Validated that I have the latest portfiles.

During the build, I got several virus scanner messages warning of trojan horses contained in executables being generated.

**Comment by Ravenwater** [comment]
Some more results: I did a raw build of grpc (branch 1.29.1) from the repo, both win32 and x64 and both complete without errors. With the raw cmake build process, I need to define a build target (Win32/x64). The default is Win32, which we don't use, so we had to specifically set the build process to build x64. How do I do that with vcpkg?

**Comment by Ravenwater** [comment]
any update on this? I was able to build and install v1.30.dev brute force, but in that build none of the abseil projects work, blaming that their libs are not correct Win32 programs.

Would love to see if we can leverage vcpkg but at this time, it still needs some handholding that is not in the documentation.

**Comment by PhoebeHui** [comment]
@Ravenwater, sorry for my late reply.

From you log, it failled due to 'fuzz\x509-test.exe : fatal error LNK1108: cannot write file at 0x0', Could you remove  .exe file, and see this issue still still exist?

**Comment by PhoebeHui** [comment]
I can't repro this, it built successfully for me.

PS E:\vcpkg\clean\vcpkg> ./vcpkg install openssl-windows:x86-windows
Computing installation plan...
The following packages will be built and installed:
    openssl-windows[core]:x86-windows
Starting package 1/1: openssl-windows:x86-windows
Building package openssl-windows[core]:x86-windows...
-- Using cached E:/VCPKG/clean/vcpkg/downloads/openssl-1.1.1d.tar.gz
-- Using source at E:/VCPKG/clean/vcpkg/buildtrees/openssl-windows/src/openssl-1-b1f8ae3e6c
-- Copying openssl release source files...
-- Copying openssl release source files... done
-- Configure x86-windows-rel
-- Configure x86-windows-rel done
-- Build x86-windows-rel
-- Build x86-windows-rel done
-- Copying openssl debug source files...
-- Copying openssl debug source files... done
-- Configure x86-windows-dbg
-- Configure x86-windows-dbg done
-- Build x86-windows-dbg
-- Build x86-windows-dbg done
-- Installing: E:/VCPKG/clean/vcpkg/packages/openssl-windows_x86-windows/share/openssl-windows/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package openssl-windows[core]:x86-windows... done
Installing package openssl-windows[core]:x86-windows...
Installing package openssl-windows[core]:x86-windows... done
Elapsed time for package openssl-windows:x86-windows: 7.605 min

Total elapsed time: 7.61 min

The package openssl is compatible with built-in CMake targets:

    find_package(OpenSSL REQUIRED)
    target_link_libraries(main PRIVATE OpenSSL::SSL OpenSSL::Crypto)

**Comment by Ravenwater** [comment]
Tried this on two different systems, one succeeds, the other fails. The one that fails threw up several virus pattern matches. Will explore if that is the cause of the vcpkg build failure.

**Comment by Ravenwater** [comment]
@PhoebeHui  looks like it is WebRoot's virus scanner that is causing the failures: when I disable it, vcpkg succeeds:

```
tomtz@SW-LAPTOP-250 MINGW64 /C/Users/tomtz/Documents/dev/clones/vcpkg (master)
$ ./vcpkg.exe install openssl-windows:x86-windows
Computing installation plan...
The following packages will be built and installed:
    openssl-windows[core]:x86-windows
Starting package 1/1: openssl-windows:x86-windows
Building package openssl-windows[core]:x86-windows...
-- Using cached C:/Users/tomtz/Documents/dev/clones/vcpkg/downloads/openssl-1.1.1d.tar.gz
-- Using source at C:/Users/tomtz/Documents/dev/clones/vcpkg/buildtrees/openssl-windows/src/openssl-1-b1f8ae3e6c
-- Copying openssl release source files...
-- Copying openssl release source files... done
-- Configure x86-windows-rel
-- Configure x86-windows-rel done
-- Build x86-windows-rel
-- Build x86-windows-rel done
-- Copying openssl debug source files...
-- Copying openssl debug source files... done
-- Configure x86-windows-dbg
-- Configure x86-windows-dbg done
-- Build x86-windows-dbg
-- Build x86-windows-dbg done
-- Installing: C:/Users/tomtz/Documents/dev/clones/vcpkg/packages/openssl-windows_x86-windows/share/openssl-windows/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package openssl-windows[core]:x86-windows... done
Installing package openssl-windows[core]:x86-windows...
Installing package openssl-windows[core]:x86-windows... done
Elapsed time for package openssl-windows:x86-windows: 6.657 min

Total elapsed time: 6.657 min

The package openssl is compatible with built-in CMake targets:

    find_package(OpenSSL REQUIRED)
    target_link_libraries(main PRIVATE OpenSSL::SSL OpenSSL::Crypto)
```

Let me build the larger grpc target and see if it succeeds before closing this and marking it up to the virus scanner.

**Comment by Ravenwater** [comment]
Confirmed: the WebRoot virus scanner was the culprit. I'll close this issue as resolved.
