### ISSUE TITLE
[libzip] build failure

### ISSUE THREAD

**Issue by 0-wiz-0** [microsoft/vcpkg#11574]
**Host Environment**
- OS: Windows (appveyor)
- Compiler: not relevant, it fails in the patch step

**To Reproduce**
`./vcpkg install libzip`

**Failure logs** 
See
https://ci.appveyor.com/project/nih-at/ckmame/builds/33110042

which starts with 'vcpkg update' and ends with:
````
Building package libzip[bzip2,core,openssl]:x64-windows...
-- Downloading https://github.com/nih-at/libzip/archive/rel-1-5-2.tar.gz...
-- Extracting source C:/Tools/vcpkg/downloads/nih-at-libzip-rel-1-5-2.tar.gz
-- Applying patch avoid_computation_on_void_pointer.patch
CMake Error at scripts/cmake/vcpkg_apply_patches.cmake:52 (message):
  Applying patch failed.  Patch needs to be updated to work with source being
  used by vcpkg!
Call Stack (most recent call first):
  scripts/cmake/vcpkg_extract_source_archive_ex.cmake:134 (vcpkg_apply_patches)
  scripts/cmake/vcpkg_from_github.cmake:114 (vcpkg_extract_source_archive_ex)
  ports/libzip/portfile.cmake:2 (vcpkg_from_github)
  scripts/ports.cmake:94 (include)
Error: Building package libzip:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libzip:x64-windows
  Vcpkg version: 2019.09.12-nohash
Additionally, attach any relevant sections from the log files above.
````

**Additional context**
libzip (git head) itself builds fine in appveyor. Also, there is a newer release out, so updating to that would be nice as well.

**Comment by NancyLi1013** [comment]
Hi @0-wiz-0 
Thanks for posting this issue.

It seems that you didn't update vcpkg to the latest version.
Since `libzip `has been updated to the latest release 1.6.1 in vcpkg.

Could you please try to use `git pull ` to update vcpkg and rebuild this port?

**Comment by 0-wiz-0** [comment]
It seems the default appveyor checkout was in a weird state. Checking out my own copy of vcpkg fixed this.  Thank you!
