### ISSUE TITLE
Different ports fulfilling same dependency requirement

### ISSUE THREAD

**Issue by albertziegenhagel** [Microsoft/vcpkg#1157]
This is a problem that vcpkg currently does not have, but that may will arise in the near future, so I wanted to start a discussion on it:

Some libraries do have dependencies to not one specific library but rather to a standardized interface that can be implemented by multiple different libraries. Examples are BLAS [1] or MPI [2]. While a library consuming BLAS in general does not care how the required functions are implemented there are many different vendor implementations where each of them has some advantages and disadvantages over the other ones (OpenBLAS, Intel MKL, reference (netlib) BLAS/LAPACK, ...).

Vcpkg should provide support where a user can choose which implementation he wants to use.

I had a quick look at homebrew and at least for MPI they have defined a special requirement `:mpi` [3] that can be satisfied by both `open-mpi` and `mpich2`. But I don't really like this kind of explicit implementation for a specific requirement. Instead I would propose the following:

- A port that depends on MPI would state `mpi` instead of the specific implementation (currently `msmpi`) as its dependency.
- In the CONTROL file of a port, we add an additional group called `Provides` (name can be changed). If that group is not specified a port by default always provides an interface that is called the same as the library. So the `msmpi` port as currently would provide `msmpi` only. If the port now additionally states that it provides `mpi`, the set of provided interfaces by the port would be `mpi` and `msmpi`. This way an other port would be able to depend either on the generic `mpi` or the specific `msmpi` if needed.
- Checking for dependencies would then be done based on the interface sets instead of library names.
- A user should not be able to install two libraries that provide the same interface. We would not need to state conflicts explicitly.

The only question that remains in my opinion is, if the user wants to install a library that depends on `mpi` but he does not yet have an mpi implementation installed. homebrew solves this by providing a default mpi implementation (which is open-mpi) that will be installed automatically in those cases. We have two ways to to the same. A port could specify that it wants to be the default implementation for an interface. E.g. in the CONTROL file

```
Provides: mpi [default]
```

An other possibility would be to have a separate list of default ports that could look like this:

```
mpi: msmpi
blas: openblas
lapack: clapack
```

The benefit of the second possibility is that we could look up the default ports quickly (we do not need to red all CONTROL files) and we guarantee no conflicts (what if two different ports state that they are `default`?) 

The reason why I am bringing this is up is not really MPI (I do not know of any other free MPI implementation on windows than MSMPI) but it is BLAS and LAPACK. Currently we do have a port for BLAS that uses OpenBLAS, but it is compiled without the assembly code enabled, what in my opinion contradicts the idea of BLAS: it should provide bleeding fast linear algebra operations, but the C reference implementation that is currently compiled by vcpkg is the opposite of that. From very quick benchmarks that I run, I saw that the reference BLAS implementation compiled with a fortran compiler is about four times faster. For LAPACK it is similar, since we currently compile an outdated version where the original Fortran code has been converted to C code by a tool. While those libraries are very good as a default implementation (since they to not need a fortran compiler) it would be nice to have the possibility to choose a different implementation, when a fortran compiler is available.

What do you think?

[1] https://en.wikipedia.org/wiki/Basic_Linear_Algebra_Subprograms
[2] https://en.wikipedia.org/wiki/Message_Passing_Interface
[3] https://github.com/Homebrew/brew/blob/bbed7246bc5c5b7acb8c1d427d10b43e090dfd39/Library/Homebrew/requirements/mpi_requirement.rb

**Comment by ras0219-msft** [comment]
I think this is the same issue as being discussed in #164. Would you mind reposting there?

**Comment by albertziegenhagel** [comment]
Sorry for overlooking the other issue. I reposted there.
