### ISSUE TITLE
Error: Building package liblzma:arm-uwp failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by vivekbarkam** [microsoft/vcpkg#1158]
HI, I am not able to build liblzma for arm-uwp, where as it is building fine for x86-windows and x64-windows. But for arm-uwp, x86-uwp, x64-uwp its not building. I am attaching supporting files.. Please help me.

![image](https://cloud.githubusercontent.com/assets/9570532/26398197/d277d898-4089-11e7-9838-e16542b2fa5e.png)

[package-arm-uwp-rel-out.txt](https://github.com/Microsoft/vcpkg/files/1025157/package-arm-uwp-rel-out.txt)

**Comment by zabulus** [comment]
Problems are:
>      4>tuklib_physmem.obj : error LNK2019: unresolved external symbol GetVersion referenced in function lzma_tuklib_physmem [E:\vcpkg\buildtrees\liblzma\arm-uwp-rel\lzma.vcxproj]
     4>tuklib_physmem.obj : error LNK2019: unresolved external symbol GetModuleHandle referenced in function lzma_tuklib_physmem [E:\vcpkg\buildtrees\liblzma\arm-uwp-rel\lzma.vcxproj]
     4>tuklib_physmem.obj : error LNK2019: unresolved external symbol GlobalMemoryStatus referenced in function lzma_tuklib_physmem [E:\vcpkg\buildtrees\liblzma\arm-uwp-rel\lzma.vcxproj]
     4>stream_encoder_mt.obj : error LNK2019: unresolved external symbol GetTickCount referenced in function wait_for_work [E:\vcpkg\buildtrees\liblzma\arm-uwp-rel\lzma.vcxproj]

UWP lacks these APIs, and additional patch(es) should be provided to fix dependencies on these APIs.

**Comment by vivekbarkam** [comment]
Hi zabulus, thanks for your reply. Where we can get the additional patches, as i have searched but couldn't find them.

**Comment by ras0219-msft** [comment]
I'd recommend submitting an issue to the liblzma mailing list that you'd like them to support UWP. Their main website is https://tukaani.org/xz/. Once they have support in their current development branch, we could look at building a patch out of that.

Otherwise, you could try following our tutorial on how to patch the library yourself: https://github.com/Microsoft/vcpkg/blob/master/docs/example-3-patch-libpng.md.

**Comment by JackBoosY** [comment]
See PR #3907

**Comment by NancyLi1013** [comment]
Hi @vivekbarkam, thanks for posting this issue. This port has already supported UWP. This feature has been merged in this PR #5607. Please try to update this port to the latest version and try to use it.

PS F:\Files\vcpkgTest\vcpkg> .\vcpkg.exe install liblzma:arm-uwp
The following packages will be built and installed:
    liblzma[core]:arm-uwp
Starting package 1/1: liblzma:arm-uwp
Building package liblzma[core]:arm-uwp...
-- Using cached F:/Files/vcpkgTest/vcpkg/downloads/xz-mirror-xz-v5.2.4.tar.gz
-- Using source at F:/Files/vcpkgTest/vcpkg/buildtrees/liblzma/src/v5.2.4-66bfe33102
-- Configuring arm-uwp
-- Building arm-uwp-dbg
-- Building arm-uwp-rel
-- Installing: F:/Files/vcpkgTest/vcpkg/packages/liblzma_arm-uwp/share/liblzma/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package liblzma[core]:arm-uwp... done
Installing package liblzma[core]:arm-uwp...
Installing package liblzma[core]:arm-uwp... done
Elapsed time for package liblzma:arm-uwp: 3.762 min

Total elapsed time: 3.762 min

The package liblzma:arm-uwp provides CMake targets:

    find_package(LibLZMA CONFIG REQUIRED)
    target_link_libraries(main PRIVATE LibLZMA::LibLZMA)
