### ISSUE TITLE
[gli] Support of gliConfig.cmake

### ISSUE THREAD

**Issue by Arthapz** [microsoft/vcpkg#11598]
gli has a support of gliConfig.cmake, it would be nice to include it.

**Comment by NancyLi1013** [comment]
Hi @Arthapz 
Thanks for posting this issue.

Since `gli `is a head-only library. We just need to include the headers. 

Personally, it's not necessary to add the config file to it.

**Comment by Arthapz** [comment]
Glm is also a headeronly library, and it has the  glmConfig.cmake,
Personally, i prefer  having cmake import file for all libs header only or not

**Comment by NancyLi1013** [comment]
Hi all,
I submitted a PR to add the support for `gli` just now. Could you please help take a look if this can meet your demands?

**Comment by Arthapz** [comment]
Hi;
this is perfect, thx.
