### ISSUE TITLE
[icu] update to 67.1

### ISSUE THREAD

**Issue by dinoele** [microsoft/vcpkg#11593]
Library name: ICU

New version number: 67.1

ICU 67 updates to CLDR 37 locale data with many additions and corrections. This release also includes the updates to Unicode 13, subsuming the special CLDR 36.1 and ICU 66 releases. ICU 67 includes many bug fixes for date and number formatting, including enhanced support for user preferences in the locale identifier. The LocaleMatcher code and data are improved, and number skeletons have a new “concise” form that can be used in MessageFormat strings.

This is the first regular release after ICU 65. ICU 66 was a low-impact release with just Unicode 13 and a few bug fixes.

https://github.com/unicode-org/icu/releases

**Comment by dinoele** [comment]
Hi. Could you please share your plans for updating this library?

**Comment by PhoebeHui** [comment]
@dinoele, sorry for my late reply.

Jon has summited a PR 11714 to upgrade icu. Thanks for reporting this issue!

**Comment by dinoele** [comment]
@PhoebeHui, thanks for the quick update!
