### ISSUE TITLE
Bond update to 9.0.0

### ISSUE THREAD

**Issue by salmanhk** [microsoft/vcpkg#11615]
Library name: Bond

New version number: 9.0.0

https://github.com/microsoft/bond/releases/tag/9.0.0

**Comment by mdslack** [comment]
Another vote for this update (note: Visual Studio 2019 16.6 breaks Bond < 9.0.0)

**Comment by chwarr** [comment]
I think that such an update is already underway in https://github.com/microsoft/vcpkg/pull/10319
