### ISSUE TITLE
opengl[core]:x86-windows build failure

### ISSUE THREAD

**Issue by mbhoshen** [microsoft/vcpkg#11618]
PS C:\Users\moshe\vcpkg> .\vcpkg install opengl
Computing installation plan...
The following packages will be built and installed:
    opengl[core]:x86-windows
Starting package 1/1: opengl:x86-windows
Building package opengl[core]:x86-windows...
CMake Error at ports/opengl/portfile.cmake:16 (message):
  Portfile not yet configured for Windows SDK with version:
Call Stack (most recent call first):
  scripts/ports.cmake:90 (include)

Error: Building package opengl:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: opengl:x86-windows
  Vcpkg version: 2020.02.04-nohash

**Comment by PhoebeHui** [comment]
@mbhoshen, do you install windows sdk? I can't repro this issue, it built successfully for me.

**Comment by PhoebeHui** [comment]
@mbhoshen, feel free to reopen it still be a problem for you.
