### ISSUE TITLE
How to best acquire bison/flex/gperf and ruby?

### ISSUE THREAD

**Issue by bagong** [Microsoft/vcpkg#1161]
I am currently trying to create a qtwebkit package (separate from the Qt5 build, not as part of it). Qt-webkit has a lot of build dependencies. All libraries are covered by vcpkg, but there seems to be no predefined function to acquire the build-time tool dependencies gnuwin32utils bison, flex and gperf, and also none for ruby. To keep things as automatic as possible it would be nice to acquire them like can be done for perl etc., or at least like can be done for python2 (btw - why can't VSs-python2 not be acquired full-automatically?), i.e. get a warning that they need to be downloaded and added to the search path.

- bison/flex/gperf are actually bundled with the qt5 source (but not webkit), they could be downloaded here:

      https://github.com/qt/qt5/tree/dev/gnuwin32

- ruby I am not sure. Qt recommends: https://dl.bintray.com/oneclick/rubyinstaller/rubyinstaller-2.3.3-x64.exe (or the 32-bit version)

Any "best-practice" reco would be appreciated!

**Comment by ras0219-msft** [comment]
Good question!

As you noticed in the other thread, for any executables that are _target_ architecture independent, it's ideal to get them through `vcpkg_find_acquire_program`. Our policy is that we prefer "portable" versions if possible, but if installation is required then we halt the build and instruct the user to download and install the software as needed (e.g. python2).

As for picking up python2 from VS -- that would be a great improvement! We just haven't done so yet :)

**Comment by bagong** [comment]
Okay, so for ruby, this seems like a good candidate, right (it's called "rubyinstaller", but it's a portable archive that only needs to be extracted):

https://github.com/oneclick/rubyinstaller2/releases/download/2.4.1-1/rubyinstaller-2.4.1-1-x64.7z

Should one prefer the  32- or 64-bit version, or offer both, either following host architecture, or by distinguishing ruby32 and ruby64? (The same question would be relevant for python, I think)

**Comment by ras0219-msft** [comment]
Generally, I'd recommend just getting the 32-bit version. This makes things simpler for all the various kinds of Windows, since they can all run x86. However, sometimes 64-bit may have a significant advantage for some reason, in which case you would need to follow the current host architecture. 

We already handle msys based on the host architecture today, as an example.
