### ISSUE TITLE
[OpenBLAS] Dynamic CPU architecture support

### ISSUE THREAD

**Issue by leezu** [microsoft/vcpkg#11623]
OpenBLAS can be built for multiple targets with runtime detection of the target cpu by specifiying DYNAMIC_ARCH=1 in Makefile.rule, on the gmake command line or as -DDYNAMIC_ARCH=TRUE in cmake.

This is important to have good performance on newer cpus without making the openblas library cause illegal instruction errors on older cpus.

Reference: https://github.com/xianyi/OpenBLAS/#support-for-multiple-targets-in-a-single-library

**Comment by NancyLi1013** [comment]
Related PR https://github.com/microsoft/vcpkg/pull/15238

**Comment by NancyLi1013** [comment]
Hi @leezu 

The feature dynamic arch for `openblas  `has been supported in vcpkg via PR #15238 now. Please update to the latest vcpkg and try to rebuild `openblas`.
