### ISSUE TITLE
docs: triplet VCPKG_C_FLAGS and VCPKG_CXX_FLAGS is unclear

### ISSUE THREAD

**Issue by diablodale** [microsoft/vcpkg#11621]
Docs for triplets and the flag families `VCPKG_C_FLAGS*`, VCPKG_CXX_FLAGS* are unclear. By trial and error I discovered that you must use `set()`, not a cache variable, and the value must be a single string (*not* a list). I recommend updating official docs to clarify correct usage. Here is the ambiguous doc...

https://github.com/microsoft/vcpkg/blob/55be137d5ba6230f62aa7fb0994fda1728ce7fef/docs/users/triplets.md#L67-L77

## Setup

* vcpkg b37f5d651d0f55a3f0ed709ed1682a4385294519
* tested with port `opencv4`

## Single Success

`set(VCPKG_CXX_FLAGS "-DWINVER=0x0A00 -D_WIN32_WINNT=0x0A00 -DNTDDI_VERSION=0x0A000005")` works.

The family of settings like VCPKG_C*_FLAGS* must...

1. be `set()`
2. its *single* value must be a string
3. if multiple compiler settings are desired, then put them all in a single string and separate them with a space

## Failures

Various combinations were tested and all failed. For example the following all failed in each their own way:

* set(VCPKG_CXX_FLAGS  
-DWINVER=0x0A00  
-D_WIN32_WINNT=0x0A00  
-DNTDDI_VERSION=0x0A000005  
)
* set(VCPKG_CXX_FLAGS -DWINVER=0x0A00 -D_WIN32_WINNT=0x0A00 -DNTDDI_VERSION=0x0A000005)
* set(VCPKG_CXX_FLAGS -DWINVER=0x0A00 -D_WIN32_WINNT=0x0A00 -DNTDDI_VERSION=0x0A000005 CACHE internal)
* etc.

## Example of clearer doc

Sets additional compiler flags to be used when not using `VCPKG_CHAINLOAD_TOOLCHAIN_FILE`. 
Use `set()` and declare the single value of that variable as a string. When multiple compiler flags are needed, separate them with a space. For example, a triplet file would include:

```cmake
set(VCPKG_C_FLAGS "-DWINVER=0x0A00 -D_WIN32_WINNT=0x0A00 -DNTDDI_VERSION=0x0A000005")
```

 This option also has forms for configuration-specific and C flags: 
 - `VCPKG_CXX_FLAGS` 
 - `VCPKG_CXX_FLAGS_DEBUG` 
 - `VCPKG_CXX_FLAGS_RELEASE` 
 - `VCPKG_C_FLAGS` 
 - `VCPKG_C_FLAGS_DEBUG` 
 - `VCPKG_C_FLAGS_RELEASE`

**Comment by redbaron** [comment]
Also worth mentioning, that despite what name suggests, values from these var end up in `CMAKE_*_FLAGS_INIT` not `CMAKE_*_FLAGS` as one might expect. As a consequence it is NOT setting final set of flags, but merely sets a default starting value for CMake to add to
