### ISSUE TITLE
Error: Building package opencv4:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by savagecabbage123** [microsoft/vcpkg#11624]
**Host Environment**
- OS: windows
- Compiler: revision

**To Reproduce**
`./vcpkg install opencv4`

**Failure logs** 
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: ninja -v
    CMake Error at cmake/OpenCVModule.cmake:816 (add_custom_command):
  add_custom_command called with OUTPUT containing a "#".  This character is
  not allowed.
Call Stack (most recent call first):
  modules/core/CMakeLists.txt:63 (ocv_glob_module_sources)

CMake Error at cmake/OpenCVModule.cmake:816 (add_custom_command):
  add_custom_command called with OUTPUT containing a "#".  This character is
  not allowed.
Call Stack (most recent call first):
  cmake/OpenCVModule.cmake:1066 (ocv_glob_module_sources)
  modules/imgproc/CMakeLists.txt:12 (ocv_define_module)

-- Excluding from source files list: modules/imgproc/src/imgwarp.avx2.cpp
-- Excluding from source files list: modules/imgproc/src/resize.avx2.cpp
-- Excluding from source files list: modules/imgproc/src/sumpixels.avx512_skx.cpp
CMake Error at modules/java/generator/CMakeLists.txt:87 (add_custom_command):
  add_custom_command called with OUTPUT containing a "#".  This character is
  not allowed.
**Additional context**
 I did .\vcpkg update and it was up to date and im using visual studio 2019, also installing other packages just before this one worked

**Comment by NancyLi1013** [comment]
```
add_custom_command called with OUTPUT containing a "#". This character is
not allowed.
```
@savagecabbage123 
Thanks for posting this issue.
Could you please check if your path contains this character  "#" ?

**Comment by savagecabbage123** [comment]
The path for vcpkg?

**Comment by NancyLi1013** [comment]
You can check this path first.
```
add_custom_command(
      OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/${OCL_NAME}.cpp"  # don't add .hpp file here to optimize build process
      COMMAND ${CMAKE_COMMAND} "-DMODULE_NAME=${name}" "-DCL_DIR=${CMAKE_CURRENT_LIST_DIR}/src/opencl" "-DOUTPUT=${CMAKE_CURRENT_BINARY_DIR}/${OCL_NAME}.cpp" -P "${OpenCV_SOURCE_DIR}/cmake/cl2cpp.cmake"
      DEPENDS ${cl_kernels} "${OpenCV_SOURCE_DIR}/cmake/cl2cpp.cmake"
      COMMENT "Processing OpenCL kernels (${name})"
    )
```
In addition, you can use `git pull
` to update vcpkg to the latest commit instead of `vcpkg update`.

**Comment by savagecabbage123** [comment]
I moved it to a different folder but when it installed it was successful but said 

    find_package(OpenCV CONFIG REQUIRED)
    # Note: 10 target(s) were omitted.
    target_link_libraries(main PRIVATE opencv_ml opencv_dnn opencv_core opencv_flann)

do you know what I can do to fix this or point me to a forum for help? Thanks in advance

**Comment by NancyLi1013** [comment]
The message is for the usage of`opencv`. You saw this info and it indicates that this port has been installed successfully.

Since this info will be printed out on the console at the end of installation.

Let me know if still have questions about this.

**Comment by savagecabbage123** [comment]
I still can't use it. Visual studio cant find it and I am wondering if it is because of the find_package(OpenCV CONFIG REQUIRED) line

**Comment by NancyLi1013** [comment]
@savagecabbage123 
Is this issue solved for you? It is not related with the info `find_package(OpenCV CONFIG REQUIRED)`.
If you still have the problem about the usage, please provide the detail error info or your project case.
