### ISSUE TITLE
[New Port Request] WinDivert

### ISSUE THREAD

**Issue by Nomade040** [microsoft/vcpkg#11620]
Library name: WinDivert

Library description: Windows Packet Divert (WinDivert) is a user-mode packet capture-and-divert package for Windows 2008, Windows 7, Windows 8, Windows 10 and Windows 2016. 

Source repository URL: https://github.com/basil00/Divert

Project homepage (if different from the source repository): https://www.reqrypt.org/windivert.html

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
