### ISSUE TITLE
Error: Cannot find definition for package `ceres`.

### ISSUE THREAD

**Issue by TigerVersusT** [microsoft/vcpkg#11631]
I can't install the ceres package, and I'm quit sure it's a valid package, because I used to install it.

**Environment**
- OS: win10 64
- Compiler: revision

**To Reproduce**
1. ./vcpkg install ceres
2. See error

**Expected behavior**
install ceres for me

**Failure logs** 
Error: Cannot find definition for package `ceres`.

**Comment by NancyLi1013** [comment]
Hi @TigerVersusT 
Thanks for posting this issue.

Could you please try to update vcpkg and rebuild this port? Or do you have any changes for `ceres` on your local?

**Comment by TigerVersusT** [comment]
@NancyLi1013 Thanks for reply, I'll update it first to see whether it works

**Comment by TigerVersusT** [comment]
and I did changed something locally, it seems that I have installed the ceres package， but when compling my project, visual studio report that I don't have it. Then I tried to uninstall it but failed ,so I delete everything related to ceres. After that I install it again and ecountered this problem.

**Comment by TigerVersusT** [comment]
Oh, I solved this by rebuild the vcpkg
