### ISSUE TITLE
install fail: vcpkg install gtk:x64-windows

### ISSUE THREAD

**Issue by huangdade** [microsoft/vcpkg#11644]
Package: libepoxy:x64-windows
  Vcpkg version: 2020.02.04-nohash

![图片](https://user-images.githubusercontent.com/4537048/83235605-b88afd80-a1c4-11ea-8fb3-8354207197d5.png)

**Comment by huangdade** [comment]
[package-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/4700461/package-x64-windows-rel-out.log)

**Comment by NancyLi1013** [comment]
Hi @huangdade 
Thanks for posting this issue. It's duplicated to #11210. Let's track this issue there.
