### ISSUE TITLE
[bond] build failure

### ISSUE THREAD

**Issue by sinozope** [microsoft/vcpkg#11642]
D:\opt\vcpkg>vcpkg install bond
Computing installation plan...
The following packages will be built and installed:
    bond[core]:x64-windows
  * boost-algorithm[core]:x64-windows
  * boost-assign[core]:x64-windows
  * boost-atomic[core]:x64-windows
  * boost-build[core]:x64-windows
  * boost-chrono[core]:x64-windows
  * boost-container[core]:x64-windows
  * boost-date-time[core]:x64-windows
  * boost-exception[core]:x64-windows
  * boost-filesystem[core]:x64-windows
  * boost-foreach[core]:x64-windows
  * boost-iostreams[core]:x64-windows
  * boost-lexical-cast[core]:x64-windows
  * boost-locale[core]:x64-windows
  * boost-math[core]:x64-windows
  * boost-phoenix[core]:x64-windows
  * boost-proto[core]:x64-windows
  * boost-ptr-container[core]:x64-windows
  * boost-range[core]:x64-windows
  * boost-regex[core]:x64-windows
  * boost-serialization[core]:x64-windows
  * boost-spirit[core]:x64-windows
  * boost-system[core]:x64-windows
  * boost-thread[core]:x64-windows
  * boost-unordered[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/25: boost-build:x64-windows
Building package boost-build[core]:x64-windows...
-- Using cached D:/opt/vcpkg/downloads/boostorg-build-boost-1.73.0.tar.gz
-- Using source at D:/opt/vcpkg/buildtrees/boost-build/src/ost-1.73.0-018fb008dd
-- Using cached D:/opt/vcpkg/downloads/boost_LICENSE_1_0.txt
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.73.0/boostcpp.jam...
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.73.0/boostcpp.jam... Failed. Status: 5;"Couldn't resolve proxy name"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:175 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  ports/boost-build/portfile.cmake:27 (vcpkg_download_distfile)
  scripts/ports.cmake:90 (include)

Error: Building package boost-build:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-build:x64-windows
  Vcpkg version: 2020.02.04-nohash

Additionally, attach any relevant sections from the log files above.

D:\opt\vcpkg>set HTTPS_PROXY=

D:\opt\vcpkg>set HTTP_PROXY=

D:\opt\vcpkg>vcpkg install bond
Computing installation plan...
The following packages will be built and installed:
    bond[core]:x64-windows
  * boost-algorithm[core]:x64-windows
  * boost-assign[core]:x64-windows
  * boost-atomic[core]:x64-windows
  * boost-build[core]:x64-windows
  * boost-chrono[core]:x64-windows
  * boost-container[core]:x64-windows
  * boost-date-time[core]:x64-windows
  * boost-exception[core]:x64-windows
  * boost-filesystem[core]:x64-windows
  * boost-foreach[core]:x64-windows
  * boost-iostreams[core]:x64-windows
  * boost-lexical-cast[core]:x64-windows
  * boost-locale[core]:x64-windows
  * boost-math[core]:x64-windows
  * boost-phoenix[core]:x64-windows
  * boost-proto[core]:x64-windows
  * boost-ptr-container[core]:x64-windows
  * boost-range[core]:x64-windows
  * boost-regex[core]:x64-windows
  * boost-serialization[core]:x64-windows
  * boost-spirit[core]:x64-windows
  * boost-system[core]:x64-windows
  * boost-thread[core]:x64-windows
  * boost-unordered[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/25: boost-build:x64-windows
Building package boost-build[core]:x64-windows...
-- Using cached D:/opt/vcpkg/downloads/boostorg-build-boost-1.73.0.tar.gz
-- Using source at D:/opt/vcpkg/buildtrees/boost-build/src/ost-1.73.0-018fb008dd
-- Using cached D:/opt/vcpkg/downloads/boost_LICENSE_1_0.txt
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.73.0/boostcpp.jam...
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.73.0/boostcpp.jam... Failed. Status: 6;"Couldn't resolve host name"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:175 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  ports/boost-build/portfile.cmake:27 (vcpkg_download_distfile)
  scripts/ports.cmake:90 (include)

Error: Building package boost-build:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-build:x64-windows
  Vcpkg version: 2020.02.04-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by LilyWangL** [comment]
Thanks for your issue. Could you work around this issue as following steps:

1. Download https://raw.githubusercontent.com/boostorg/boost/boost-1.73.0/boostcpp.jam manually.
2. Put it to .\vcpkg\downloads\
3. Try to build again.

**Comment by LilyWangL** [comment]
Pinging @sinozope

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
