### ISSUE TITLE
Failed to find OpenImageIO - Could not find OpenImageIO include directory

### ISSUE THREAD

**Issue by TigerVersusT** [microsoft/vcpkg#11649]
**Describe the bug**
I installed OpenInageIO but can't use it in the cmake project

**Environment**
- OS: win10
- Compiler: revision

**To Reproduce**
1. ./vcpkg install OpemImageIO
2. See error
Repro code when

**Failure logs** 
CMake Error at src/cmake/FindOpenImageIO.cmake:28 (message):
  Failed to find OpenImageIO - Could not find OpenImageIO include directory,
  set OPENIMAGEIO_INCLUDE_DIR to directory containing OpenImageIO/imageio.h
Call Stack (most recent call first):
  src/cmake/FindOpenImageIO.cmake:90 (openimageio_report_not_found)
  src/CMakeLists.txt:306 (find_package)

**Comment by rubywerman** [comment]
Were you able to solve this? Having the same issue.

**Comment by TigerVersusT** [comment]
> 
> 
> @TigerVersusT Were you able to solve this? Having the same issue.

Hi, rubywerman, it's been a long time since I last edited it, but considering my closing this issue so fast it must not a complicated problem. Try clean the cmake cache folder in your project first， then see if you have ever installed packages concurrently in two consoles， finally, delete all packages manually and reinstall all( should ask more people to find possible solutions before doing this  ). That's all I can remember, hope it helps to you.
