### ISSUE TITLE
cairo build failure, static library target

### ISSUE THREAD

**Issue by jpcima** [microsoft/vcpkg#11640]
**Host Environment**
- OS: Windows x86 in Appveyor
- Compiler: Microsoft Visual Studio 2017 MSVC 19.16.27035.0

**To Reproduce**
`vcpkg install cairo:x86-windows-static`

**Failure logs** 
```
Starting package 10/14: glib:x86-windows-static
Building package glib[core]:x86-windows-static...
-- Note: glib only supports dynamic library linkage. Building dynamic library.
CMake Error at scripts/cmake/vcpkg_check_linkage.cmake:42 (message):
  Refusing to build unexpected dynamic library against the static CRT.  If
  this is desired, please configure your triplet to directly request this
  configuration.
Call Stack (most recent call first):
  ports/glib/portfile.cmake:10 (vcpkg_check_linkage)
  scripts/ports.cmake:94 (include)
```

**Additional context**
Currently it's not possible to build `cairo` statically, because this pulls static `glib`, and Glib is only compatible with dll builds.

Glib however, is an **optional** dependency of cairo, which there exists a configure option to disable (`--disable-gobject`).

It would be helpful if we can somewhat have a strategy that can build target `unofficial::cairo::cairo`, and skip `unofficial::cairo::cairo-gobject`.
(such as to make it a separate package, or what else may be appropriate)

**Comment by NancyLi1013** [comment]
Hi @jpcima 
Thanks for posting this issue.
In this case, we might consider to set `gobject` as a feature for `cairo` and remove the dependency of `glib`.  
What's your opinion?

**Comment by jpcima** [comment]
>In this case, we might consider to set gobject as a feature for cairo and remove the dependency of glib.

Hi, I think it seems an adequate approach to solving this problem, and I would find it greatly helpful :+1: 
Thanks.

**Comment by NancyLi1013** [comment]
Thanks for your feedback. I will try to fix this issue in these days.

**Comment by NancyLi1013** [comment]
@jpcima 
I submitted a PR to fix this issue just now.
Could you please help confirm if it can work for you?

**Comment by jpcima** [comment]
It's a success with the PR #11829. Thanks.
The software built correctly in both architectures.
https://ci.appveyor.com/project/SFZTools/sfizz/builds/33421287/job/eqhioqfssvte0paw
