### ISSUE TITLE
GTKMM build failure

### ISSUE THREAD

**Issue by rengedv** [microsoft/vcpkg#11658]
- OS:  Windows
- Compiler: Visual Studio 2017

vcpkg install gtkmm

Package: libsigcpp:x64-windows
Vcpkg version: 2020.02.04-nohash

**Comment by PhoebeHui** [comment]
@rengedv, could you attach the failure logs?

gtkmm and libsigcpp:x64-windows built successfully for me:

PS F:\vcpkg\src> ./vcpkg install gtkmm
Computing installation plan...
The following packages will be built and installed:
    gtkmm[core]:x86-windows
Starting package 1/1: gtkmm:x86-windows
Building package gtkmm[core]:x86-windows...
-- Using cached F:/VCPKG/src/downloads/gtkmm-3.22.2.tar.xz
-- Using source at F:/VCPKG/src/buildtrees/gtkmm/src/gtkmm-3-59e077bd25
-- Building F:/VCPKG/src/buildtrees/gtkmm/src/gtkmm-3-59e077bd25/MSVC_Net2013/gtkmm.sln for Release
-- Building F:/VCPKG/src/buildtrees/gtkmm/src/gtkmm-3-59e077bd25/MSVC_Net2013/gtkmm.sln for Debug
-- Performing post-build validation
-- Performing post-build validation done
Building package gtkmm[core]:x86-windows... done
Installing package gtkmm[core]:x86-windows...
Installing package gtkmm[core]:x86-windows... done
Elapsed time for package gtkmm:x86-windows: 2.891 min

Total elapsed time: 2.895 min

PS F:\vcpkg\src> ./vcpkg install libsigcpp:x64-windows
Computing installation plan...
The following packages will be built and installed:
    libsigcpp[core]:x64-windows
Starting package 1/1: libsigcpp:x64-windows
Building package libsigcpp[core]:x64-windows...
-- Using cached F:/VCPKG/src/downloads/libsigc++-2.10.0.tar.xz
-- Using source at F:/VCPKG/src/buildtrees/libsigcpp/src/ibsigc++-2-7a3eaca3e7
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package libsigcpp[core]:x64-windows... done
Installing package libsigcpp[core]:x64-windows...
Installing package libsigcpp[core]:x64-windows... done
Elapsed time for package libsigcpp:x64-windows: 32.07 s

Total elapsed time: 32.2 s

**Comment by rengedv** [comment]
Hello Phoebe,

thank you for your answer and greetings from germany.

First of all, i have tested this stuff with VS 2013/2015/2017/2019 

some errors, but, i stay with the essential one, GTK works

but gtkmm didn´t compile , because of these messages., in german, i will translate

D:\vcpkg\buildtrees\glibmm\src\glibmm-2-23f726c484\glib\glibmm/ustring.h(244): error C2131: Ausdruck wurde nicht zu einer Konstanten ausgewertet.
D:\vcpkg\buildtrees\glibmm\src\glibmm-2-23f726c484\glib\glibmm/ustring.h(244): note: Fehler wurde durch Argumente ohne Konstante oder einen Verweis auf ein Symbol ohne Konstante verursacht
D:\vcpkg\buildtrees\glibmm\src\glibmm-2-23f726c484\glib\glibmm/ustring.h(244): note: siehe Verwendung von "npos"
ninja: build stopped: subcommand failed.

-- now the translation 

in line 244 of the file ustring.h, Visual Studio and, also 2019 16.6.0 cannot parse this line. 

I use C/C++ since 34 Years.. i have played with this line a little bit, but, just playing.. 
Because of the german messages i didn´t provide more information. My opinion, in one of your previews or 16.6.1 Release.. someday.. maybe soon :-)... it will work..  

Have a nice week, greetings from Germany

Karl-Heinz Reng

**Comment by PhoebeHui** [comment]
@rengedv, thanks for your information!

From your log, it seems that glibmm build failed, I get latest source, and reinstall gtkmm, both build successfully for me. I still can't repro this issue.

PS F:\vcpkg\src> ./vcpkg install gtkmm
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
Computing installation plan...
The following packages will be built and installed:
  * atkmm[core]:x86-windows
  * glibmm[core]:x86-windows
    gtkmm[core]:x86-windows
  * pangomm[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/4: glibmm:x86-windows
Building package glibmm[core]:x86-windows...
-- Using cached F:/VCPKG/src/downloads/glibmm-2.52.1.tar.xz
-- Using source at F:/VCPKG/src/buildtrees/glibmm/src/glibmm-2-23f726c484
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Installing: F:/VCPKG/src/packages/glibmm_x86-windows/share/glibmm/copyright
-- Installing: F:/VCPKG/src/packages/glibmm_x86-windows/share/glibmm/readme.txt
-- Performing post-build validation
-- Performing post-build validation done
Building package glibmm[core]:x86-windows... done
Installing package glibmm[core]:x86-windows...
Installing package glibmm[core]:x86-windows... done
Elapsed time for package glibmm:x86-windows: 2.39 min
Starting package 2/4: atkmm:x86-windows
Building package atkmm[core]:x86-windows...
-- Using cached F:/VCPKG/src/downloads/atkmm-2.24.2.tar.xz
-- Using source at F:/VCPKG/src/buildtrees/atkmm/src/atkmm-2-de808b48b0
-- Building F:/VCPKG/src/buildtrees/atkmm/src/atkmm-2-de808b48b0/MSVC_Net2013/atkmm.sln for Release
-- Building F:/VCPKG/src/buildtrees/atkmm/src/atkmm-2-de808b48b0/MSVC_Net2013/atkmm.sln for Debug
-- Installing: F:/VCPKG/src/packages/atkmm_x86-windows/share/atkmm/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package atkmm[core]:x86-windows... done
Installing package atkmm[core]:x86-windows...
Installing package atkmm[core]:x86-windows... done
Elapsed time for package atkmm:x86-windows: 38.58 s
Starting package 3/4: pangomm:x86-windows
Building package pangomm[core]:x86-windows...
-- Using cached F:/VCPKG/src/downloads/pangomm-2.40.1.tar.xz
-- Using source at F:/VCPKG/src/buildtrees/pangomm/src/pangomm-2-bb0817eca2
-- Building F:/VCPKG/src/buildtrees/pangomm/src/pangomm-2-bb0817eca2/MSVC_Net2013/pangomm.sln for Release
-- Building F:/VCPKG/src/buildtrees/pangomm/src/pangomm-2-bb0817eca2/MSVC_Net2013/pangomm.sln for Debug
-- Installing: F:/VCPKG/src/packages/pangomm_x86-windows/share/pangomm/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package pangomm[core]:x86-windows... done
Installing package pangomm[core]:x86-windows...
Installing package pangomm[core]:x86-windows... done
Elapsed time for package pangomm:x86-windows: 39.83 s
Starting package 4/4: gtkmm:x86-windows
Building package gtkmm[core]:x86-windows...
-- Using cached F:/VCPKG/src/downloads/gtkmm-3.22.2.tar.xz
-- Using source at F:/VCPKG/src/buildtrees/gtkmm/src/gtkmm-3-59e077bd25
-- Building F:/VCPKG/src/buildtrees/gtkmm/src/gtkmm-3-59e077bd25/MSVC_Net2013/gtkmm.sln for Release
-- Building F:/VCPKG/src/buildtrees/gtkmm/src/gtkmm-3-59e077bd25/MSVC_Net2013/gtkmm.sln for Debug
-- Installing: F:/VCPKG/src/packages/gtkmm_x86-windows/share/gtkmm/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package gtkmm[core]:x86-windows... done
Installing package gtkmm[core]:x86-windows...
Installing package gtkmm[core]:x86-windows... done
Elapsed time for package gtkmm:x86-windows: 3.136 min

Total elapsed time: 6.852 min

**Comment by rengedv** [comment]
Hello Phoebe,

yesterday i have tried the new Visual Studio 16.6.1 Release, maybe some changes in the C++ solution, so i tried.. No.

I have started also witn an complety new vcpkg., after the update. 27 Packages must be installed.. if there is nothing .. a small error with msys2, but after a once more this problem ist solved. GTK works.. GTKMM, no way.

Here for GLIBMM result, as i mentioned. more the one VS installed. And i found a solution for VS 2013, but not quite sure, because memory leak. This is a solution for use it @home at your risk ;-)

Greetings

Karl-Heinz Reng

-- the log

 Computing installation plan...
The following packages will be built and installed:
    glibmm[core]:x86-windows
Starting package 1/1: glibmm:x86-windows
Building package glibmm[core]:x86-windows...
Warning: The following VS instances are excluded because the English language pack is unavailable.
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise
    C:\Program Files (x86)\Microsoft Visual Studio 12.0\
Please install the English language pack.
-- Using cached D:/vcpkg/downloads/glibmm-2.52.1.tar.xz
-- Using source at D:/vcpkg/buildtrees/glibmm/src/glibmm-2-23f726c484
-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: D:/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v
    Working Directory: D:/vcpkg/buildtrees/glibmm/x86-windows-dbg
    See logs for more information:
      D:\vcpkg\buildtrees\glibmm\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/glibmm/portfile.cmake:30 (vcpkg_install_cmake)
  scripts/ports.cmake:90 (include)


Error: Building package glibmm:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: glibmm:x86-windows
  Vcpkg version: 2020.02.04-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by PhoebeHui** [comment]
@rengedv, from your log:

1. VCPKG start to support from Visual Studio 2015 Update 3, so VS2013 doesn't support.
2. Please install the English language pack.
3. Could you also get latest vcpkg source and try again, I noticed that you still use CMake-3.14, we upgarded to 3.17

**Comment by rengedv** [comment]
Hello Phoebe,

first of, thank you for your comment. Before i noticed you about this Issue i have tested this on 2 PC and now, also one Laptop. Short, on the Laptop i have since last year installed VS 2019 Preview, yesterday I have updated VCPKG (and of course, i have tested with cmake 3.17 last weekend, before wrote down the issue. )

now, Laptop, VS 2019 Preview 16.7.2.0 ... last vcpkg, with cmake, total broken, only opencl works.

PC 1, 208 packages installed, OpenCL, OpenGL, freeglut, zlib, glad, glfw3, sdl2, etc.  and also last weekend boost, 145 librarys, (deleted on monday, this Boost with dll, no solution for me) All  builds with this english language information. 

Thats really not the problem. I have a build of gtk, perfect, GTKMM / GLIBMM ist the error, and this is at the moment a problem with the compiler. 

A little problem for Windows User is also, that the first fresh build of GTK/GTKMM makes some noise of the missing bash.. (when msys2 is a fresh install). After vckpg install gtk oder gtkmm oder glibmm, this works.

Visual Studio 2013, well it may not be supported with VCPKG, but if you download the necessary project, and lock at the *.sln File.. this works, But this line in ustring.h, 241 or so, i have watched this line in VS 2013/2015/2017/2019.. latest not preview release. No way at the moment.

I don´t ned the english language support, to build a boost Test Project (i don´t like this dll stuff in your vcpkg solution, i stay on b2 bulds with may cores on my "engines". ) but, Opengl, or opencl ode SDL2 with SD2 Image, all project compiles with my vcpkg build.. all BUT ONE.. yesterday this new Preview.. unusable.. on my laptop, but this is only for testing and playing with code.. ;-)

i wish you a nice weekend in this different times, and thank you again.  I will test with the next releases, und maybe someday, it will work for me, but i don´t think it is the language stuff.. because a lot of the other libraries works fine.. 

Greetings from Germany

Karl-Heinz

**Comment by rengedv** [comment]
Hello Phoebe,

Problem solved
1. i deleted the directory c:\program files(x86)\Microsoft Visual Studio 14 .A C++ / SDK / XML etc.  was installed, maybe through the first start after compiling vcpkg. Maybe an issue could also have been the installation node.js and the configuration of node.js after the installation . The chocolatey packet manager has installed a lot of stuff. 

2. After deleting, 

Installing package gtkmm[core]:x86-windows... done
Elapsed time for package gtkmm:x86-windows: 4.225 min

Total elapsed time: 6.104 min

all works fine. 

CMake wasn´t the problem. The VS 2019 C++ Compiler error has gone. At the moment, i use, 16.6.2, it seems the error has gone after Update 16.6.1.

Greetings form  Germany, have a nice weekend

Karl-Heinz

**Comment by Zergoma** [comment]
hello,

sorry I've got the same issue trying to install gtkmm (x86-x64) :
VS2015 update 3 => ok,
English language pack => ok,
CMake 3.17 =>ok
(vcpkg is up-to-date, and I make a vcpkg update too)

toolset configure for visual 2015 : 
vcpkg\triplets\x64-windows.cmake && x86-windows.cmake
I had added this line in the files : 

> set(VCPKG_PLATFORM_TOOLSET v140)


D:\vcpkg\vcpkg>vcpkg install gtkmm
Computing installation plan...
The following packages will be built and installed:
  * atkmm[core]:x86-windows
  * cairomm[core]:x86-windows
  * glibmm[core]:x86-windows
    gtkmm[core]:x86-windows
  * pangomm[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/5: glibmm:x86-windows
Building package glibmm[core]:x86-windows...
-- Using cached D:/vcpkg/vcpkg/downloads/glibmm-2.52.1.tar.xz
-- Using source at D:/vcpkg/vcpkg/buildtrees/glibmm/src/glibmm-2-23f726c484
-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: D:/vcpkg/vcpkg/downloads/tools/cmake-3.17.2-windows/cmake-3.
17.2-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v
    Working Directory: D:/vcpkg/vcpkg/buildtrees/glibmm/x86-windows-dbg
    See logs for more information:
      D:\vcpkg\vcpkg\buildtrees\glibmm\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/glibmm/portfile.cmake:30 (vcpkg_install_cmake)
  scripts/ports.cmake:76 (include)


Error: Building package glibmm:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: glibmm:x86-windows
  Vcpkg version: 2020.02.04-nohash

Additionally, attach any relevant sections from the log files above.

D:\vcpkg\vcpkg>

### log file
I join the log file 
but same thing : glib\glibmm/ustring.h(244): error C2131: expression did not evaluate to a constant
[install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/4812320/install-x86-windows-dbg-out.log)

I really need your help to find a solution

**Comment by rengedv** [comment]
Use Visual Studio 2019. 16.6.2.. 
 
Von: Zergoma [mailto:notifications@github.com] 
Gesendet: Montag, 22. Juni 2020 11:18
An: microsoft/vcpkg
Cc: rengedv; Mention
Betreff: Re: [microsoft/vcpkg] GTKMM build failure (#11658)
 
hello,
sorry I've got the same issue trying to install gtkmm (x86-x64) :
VS2015 update 3 => ok,
English language pack => ok,
CMake 3.17 =>ok
(vcpkg is up-to-date, and I make a vcpkg update too)
toolset configure for visual 2015 :
vcpkg\triplets\x64-windows.cmake && x86-windows.cmake
I had added this line in the files :
set(VCPKG_PLATFORM_TOOLSET v140)
D:\vcpkg\vcpkg>vcpkg install gtkmm
Computing installation plan...
The following packages will be built and installed:
*	atkmm[core]:x86-windows
*	cairomm[core]:x86-windows
*	glibmm[core]:x86-windows
gtkmm[core]:x86-windows
*	pangomm[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/5: glibmm:x86-windows
Building package glibmm[core]:x86-windows...
-- Using cached D:/vcpkg/vcpkg/downloads/glibmm-2.52.1.tar.xz
-- Using source at D:/vcpkg/vcpkg/buildtrees/glibmm/src/glibmm-2-23f726c484
-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
Command failed: D:/vcpkg/vcpkg/downloads/tools/cmake-3.17.2-windows/cmake-3.
17.2-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v
Working Directory: D:/vcpkg/vcpkg/buildtrees/glibmm/x86-windows-dbg
See logs for more information:
D:\vcpkg\vcpkg\buildtrees\glibmm\install-x86-windows-dbg-out.log
Call Stack (most recent call first):
scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
ports/glibmm/portfile.cmake:30 (vcpkg_install_cmake)
scripts/ports.cmake:76 (include)
Error: Building package glibmm:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with .\vcpkg update, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
Package: glibmm:x86-windows
Vcpkg version: 2020.02.04-nohash
Additionally, attach any relevant sections from the log files above.
D:\vcpkg\vcpkg>

log file

I join the log file
but same thing : glib\glibmm/ustring.h(244): error C2131: expression did not evaluate to a constant
install-x86-windows-dbg-out.log <https://github.com/microsoft/vcpkg/files/4812320/install-x86-windows-dbg-out.log> 
I really need your help to find a solution

**Comment by rengedv** [comment]
Hello Zergoma,

Visual Studio 2015 didn´t work. Problem with one line of code. 

Use Visual Studio 2019, Community, if you don´t habe the Professional Edition. You need 16.6.1 or higher. If you install Visual Studio 2019 for the first time, you will get the latest release (don´t use the preview!), and all works fine. It is necessary that Visual Studio 2019 will be used for the build process!
Look at the command line prompt at VS 2019 menu.  

Have a nice day, greetings from Germany. 


Karl-Heinz

**Comment by Zergoma** [comment]
Hello,

Thank you for your returns.
Is there a fix in sight for this problem under VS2015 update 3 (v140) ?
(My team is working with this version. The upgrade to 2019 version is not planned for a while.
It will be more easily for me to convince them to use Gtk+ that way, and bury MFC ...  ^^ )

I tested too the vs2019 version: everythings fine as you told me.

Have nice day,
Mit freundlichen Grüßen

Guillaume

**Comment by rengedv** [comment]
Salut Guillaume,

your question about a fix VS 2015 Update 3. I am working in this business since 34 years, and i think, the answer is easy. No!
But maybe if some enterprises like Autodesk, which have used a long time vs 2015, and even today you can download some SDKs for the use with VS 2012/2013/2015, now switched to VS 2017 also (maybe could this be the cause why i got last week an update, a minor update of course, for vs 2017 Professional on my boxes)

Use Hyper-V, or another VM, or another notebook or PC for this problems. When you have the Library, then happy coding. Thats my way. 

I presume, you are from France, so, bonne chance et rester en bonne sante (german keyboard, without all your necessary ´ ` , sorry ;-))

Greetings from germany

Katl-Heinz Reng

**Comment by PhoebeHui** [comment]
@rengedv, nice to hear that the problem solved, and thanks for sharing the solution here!
