### ISSUE TITLE
vcpkg build failure with Visual Studio 2015 on AppVeyor

### ISSUE THREAD

**Issue by rouault** [microsoft/vcpkg#11666]
**Describe the bug**
vcpkg fails to build with the APPVEYOR_BUILD_WORKER_IMAGE=Visual Studio 2015 image on AppVeyor. It is apparently due to commit 09319cd79e3bee6a41bb76db739aef3f3644f19

**Environment**
- OS: Windows
- Compiler: MSVC 19.0.24241.7

**To Reproduce**
- Have a AppVeyor configuration with APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
- bootstrap-vcpkg.bat

It fails with
```
..\src\vcpkg\metrics.cpp(44): error C2127: 'write_byte': illegal initialization of 'constexpr' entity with a non-constant expression [C:\projects\gdal\vcpkg\toolsrc\vcpkglib\vcpkglib.vcxproj]
  ..\src\vcpkg\metrics.cpp(44): note: failure was caused by evaluating a lambda expression
```

**Expected behavior**
Successful build :-)

**Failure logs** 
Log of failure at https://ci.appveyor.com/project/OSGeo/gdal/builds/33212824/job/b6u6fdc5p8ssy7ri

**Comment by JackBoosY** [comment]
Yep. because cppkafka doesn't provide export cmake files. So we need to add `vcpkg-cmake-wrapper`.

**Comment by JackBoosY** [comment]
Hi @rouault, does this issue still exist?

**Comment by rouault** [comment]
> does this issue still exist?

no, seems to be fixed
