### ISSUE TITLE
How to link to CppKafka installed using vcpkg

### ISSUE THREAD

**Issue by smadurange** [microsoft/vcpkg#11660]
I installed CppKafka using vcpkg (I'm on a x64 Windows 10 using Visual Studio 2019):
```
Computing installation plan...
The following packages are already installed:
    cppkafka[core]:x86-windows
Package cppkafka:x86-windows is already installed
```
Then, I have my CMakeLists.txt:

```
cmake_minimum_required (VERSION 3.8)

add_executable (KafkaSdk  main.cpp)

find_package(CppKafka REQUIRED)
target_link_libraries(KafkaSdk CppKafka::cppkafka)
```

My CMakeSettings.json:

```
{
  "configurations": [
    {
      "name": "x64-Debug",
      "generator": "Ninja",
      "configurationType": "Debug",
      "inheritEnvironments": [ "msvc_x64_x64" ],
      "buildRoot": "${projectDir}\\out\\build\\${name}",
      "installRoot": "${projectDir}\\out\\install\\${name}",
      "cmakeCommandArgs": "",
      "buildCommandArgs": "-v",
      "ctestCommandArgs": "",
      "cmakeToolchain": "C:/Users/xxx/vcpkg/scripts/buildsystems/vcpkg.cmake",
      "variables": []
    },
    {
      "name": "x86-Debug",
      "generator": "Ninja",
      "configurationType": "Debug",
      "buildRoot": "${projectDir}\\out\\build\\${name}",
      "installRoot": "${projectDir}\\out\\install\\${name}",
      "cmakeCommandArgs": "",
      "buildCommandArgs": "-v",
      "ctestCommandArgs": "",
      "cmakeToolchain": "C:/Users/xxx/vcpkg/scripts/buildsystems/vcpkg.cmake",
      "inheritEnvironments": [ "msvc_x86" ],
      "variables": []
    }
  ]
}
```

I'm selecting x86-Debug build when I build the project. I get the error
```
CMake Error at C:/Users/xxx/vcpkg/scripts/buildsystems/vcpkg.cmake:329 (_find_package):
  By not providing "FindCppKafka.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "CppKafka",
  but CMake did not find one.

  Could not find a package configuration file provided by "CppKafka" with any
  of the following names:

    CppKafkaConfig.cmake
    cppkafka-config.cmake

  Add the installation prefix of "CppKafka" to CMAKE_PREFIX_PATH or set
  "CppKafka_DIR" to a directory containing one of the above files.  If
  "CppKafka" provides a separate development package or SDK, be sure it has
  been installed.		C:/Users/xxx/vcpkg/scripts/buildsystems/vcpkg.cmake
```

I installed vcpkg just today. So vcpkg commit should be 0fc90d9f158fefd0112d778bebef3441ece2e130.

**Comment by JackBoosY** [comment]
Yep. because cppkafka doesn't provide export cmake files. So we need to add `vcpkg-cmake-wrapper`.

**Comment by kuoshijia** [comment]
@JackBoosY is there a work-around? I have met the same problem too. Thanks in advance.

**Comment by JackBoosY** [comment]
@kuoshijia Use the following code:
```
include(FindPackageHandleStandardArgs)
include(SelectLibraryConfigurations)

find_path(CPPKAFKA_INCLUDES NAMES cppkafka.h HINTS ${CURRENT_INSTALLED_DIR} PATH_SUFFIXES cppkafka)

find_library(CPPKAFKA_LIBRARY_DEBUG NAMES cppkafka PATH_SUFFIXES lib PATHS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}" NO_DEFAULT_PATH REQUIRED)
find_library(CPPKAFKA_LIBRARY_RELEASE NAMES cppkafka PATH_SUFFIXES lib PATHS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/debug" NO_DEFAULT_PATH REQUIRED)

select_library_configurations(CPPKAFKA)

......

target_include_directories({TARGET} PRIVATE ${CPPKAFKA_INCLUDES})
target_link_libraries({TARGET} PRIVATE ${CPPKAFKA_LIBRARY})
```

**Comment by kuoshijia** [comment]
> @kuoshijia Use the following code:
> 
> ```
> include(FindPackageHandleStandardArgs)
> include(SelectLibraryConfigurations)
> 
> find_path(CPPKAFKA_INCLUDES NAMES cppkafka.h HINTS ${CURRENT_INSTALLED_DIR} PATH_SUFFIXES cppkafka)
> 
> find_library(CPPKAFKA_LIBRARY_DEBUG NAMES cppkafka PATH_SUFFIXES lib PATHS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}" NO_DEFAULT_PATH REQUIRED)
> find_library(CPPKAFKA_LIBRARY_RELEASE NAMES cppkafka PATH_SUFFIXES lib PATHS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/debug" NO_DEFAULT_PATH REQUIRED)
> 
> select_library_configurations(CPPKAFKA)
> 
> ......
> 
> target_include_directories({TARGET} PRIVATE ${CPPKAFKA_INCLUDES})
> target_link_libraries({TARGET} PRIVATE ${CPPKAFKA_LIBRARY})
> ```

That does the trick! Except that cppkafka uses namespace "cppkafka" so that I changed the include directory.

`find_package(RdKafka REQUIRED)
if (RdKafka_FOUND)
    message(STATUS "Found valid RdKafka version")
else()
    message(FATAL_ERROR "Failed to find valid RdKafka version")
endif()

include(FindPackageHandleStandardArgs)
include(SelectLibraryConfigurations)

find_path(CPPKAFKA_INCLUDES NAMES cppkafka.h HINTS ${CURRENT_INSTALLED_DIR} PATH_SUFFIXES cppkafka)

find_library(CPPKAFKA_LIBRARY_DEBUG NAMES cppkafka PATH_SUFFIXES lib PATHS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}" NO_DEFAULT_PATH REQUIRED)
find_library(CPPKAFKA_LIBRARY_RELEASE NAMES cppkafka PATH_SUFFIXES lib PATHS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/debug" NO_DEFAULT_PATH REQUIRED)

select_library_configurations(CPPKAFKA)

add_executable(main main.cpp)

target_include_directories(main PRIVATE ${CPPKAFKA_INCLUDES}/..)
target_link_libraries(main PRIVATE ${CPPKAFKA_LIBRARY} RdKafka::rdkafka++)
`

**Comment by MonicaLiu0311** [comment]
Fixed by https://github.com/microsoft/vcpkg/pull/31182.
