### ISSUE TITLE
Boost Installation Problem

### ISSUE THREAD

**Issue by sunsaintx** [microsoft/vcpkg#11661]
Package: boost-compatibility:x86-windows
  Vcpkg version: 2020.02.04-nohash-external
  CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:175 (message)

**Comment by PhoebeHui** [comment]
@sunsaintx, I can't repro this issue, could you confirm which file download failed? boost-1.73.0.tar.gz or LICENSE_1_0.txt? if the problem persist for you, could you please try to manually download the file and put them to vcpkg\downloads\ folder?

PS F:\vcpkg\boost_173\vcpkg> ./vcpkg install boost-compatibility:x64-windows
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
Computing installation plan...
The following packages will be built and installed:
    boost-compatibility[core]:x64-windows
Starting package 1/1: boost-compatibility:x64-windows
Building package boost-compatibility[core]:x64-windows...
-- Downloading https://github.com/boostorg/compatibility/archive/boost-1.73.0.tar.gz...
-- Extracting source F:/VCPKG/boost_173/vcpkg/downloads/boostorg-compatibility-boost-1.73.0.tar.gz
-- Using source at F:/VCPKG/boost_173/vcpkg/buildtrees/boost-compatibility/src/ost-1.73.0-44642da97c
-- Packaging headers
-- Packaging headers done
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.73.0/LICENSE_1_0.txt...
-- Installing: F:/VCPKG/boost_173/vcpkg/packages/boost-compatibility_x64-windows/share/boost-compatibility/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package boost-compatibility[core]:x64-windows... done
Installing package boost-compatibility[core]:x64-windows...
Installing package boost-compatibility[core]:x64-windows... done
Elapsed time for package boost-compatibility:x64-windows: 1.917 s

Total elapsed time: 1.919 s

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/11627.

**Comment by chatyan** [comment]
>.\vcpkg install pcl
Computing installation plan...
The following packages will be built and installed:
  * boost-algorithm[core]:x86-windows
  * boost-any[core]:x86-windows
  * boost-array[core]:x86-windows
  * boost-asio[core]:x86-windows
  * boost-assert[core]:x86-windows
  * boost-atomic[core]:x86-windows
  * boost-bimap[core]:x86-windows
  * boost-bind[core]:x86-windows
  * boost-build[core]:x86-windows
  * boost-chrono[core]:x86-windows
  * boost-circular-buffer[core]:x86-windows
  * boost-compatibility[core]:x86-windows
  * boost-concept-check[core]:x86-windows
  * boost-config[core]:x86-windows
  * boost-container[core]:x86-windows
  * boost-container-hash[core]:x86-windows
  * boost-context[core]:x86-windows
  * boost-conversion[core]:x86-windows
  * boost-core[core]:x86-windows
  * boost-coroutine[core]:x86-windows
  * boost-date-time[core]:x86-windows
  * boost-detail[core]:x86-windows
  * boost-dynamic-bitset[core]:x86-windows
  * boost-endian[core]:x86-windows
  * boost-exception[core]:x86-windows
  * boost-filesystem[core]:x86-windows
  * boost-foreach[core]:x86-windows
  * boost-format[core]:x86-windows
  * boost-function[core]:x86-windows
  * boost-function-types[core]:x86-windows
  * boost-functional[core]:x86-windows
  * boost-fusion[core]:x86-windows
  * boost-graph[core]:x86-windows
  * boost-integer[core]:x86-windows
  * boost-interprocess[core]:x86-windows
  * boost-intrusive[core]:x86-windows
  * boost-io[core]:x86-windows
  * boost-iostreams[core]:x86-windows
  * boost-iterator[core]:x86-windows
  * boost-lambda[core]:x86-windows
  * boost-lexical-cast[core]:x86-windows
  * boost-locale[core]:x86-windows
  * boost-math[core]:x86-windows
  * boost-modular-build-helper[core]:x86-windows
  * boost-move[core]:x86-windows
  * boost-mp11[core]:x86-windows
  * boost-mpl[core]:x86-windows
  * boost-multi-array[core]:x86-windows
  * boost-multi-index[core]:x86-windows
  * boost-multiprecision[core]:x86-windows
  * boost-numeric-conversion[core]:x86-windows
  * boost-optional[core]:x86-windows
  * boost-parameter[core]:x86-windows
  * boost-phoenix[core]:x86-windows
  * boost-pool[core]:x86-windows
  * boost-predef[core]:x86-windows
  * boost-preprocessor[core]:x86-windows
  * boost-property-map[core]:x86-windows
  * boost-property-tree[core]:x86-windows
  * boost-proto[core]:x86-windows
  * boost-ptr-container[core]:x86-windows
  * boost-random[core]:x86-windows
  * boost-range[core]:x86-windows
  * boost-ratio[core]:x86-windows
  * boost-rational[core]:x86-windows
  * boost-regex[core]:x86-windows
  * boost-serialization[core]:x86-windows
  * boost-signals2[core]:x86-windows
  * boost-smart-ptr[core]:x86-windows
  * boost-spirit[core]:x86-windows
  * boost-static-assert[core]:x86-windows
  * boost-system[core]:x86-windows
  * boost-test[core]:x86-windows
  * boost-thread[core]:x86-windows
  * boost-throw-exception[core]:x86-windows
  * boost-tokenizer[core]:x86-windows
  * boost-tti[core]:x86-windows
  * boost-tuple[core]:x86-windows
  * boost-type-index[core]:x86-windows
  * boost-type-traits[core]:x86-windows
  * boost-typeof[core]:x86-windows
  * boost-unordered[core]:x86-windows
  * boost-utility[core]:x86-windows
  * boost-uuid[core]:x86-windows
  * boost-variant[core]:x86-windows
  * boost-winapi[core]:x86-windows
  * boost-xpressive[core]:x86-windows
  * bzip2[core]:x86-windows
  * curl[core,non-http,ssl,sspi,winssl]:x86-windows
  * double-conversion[core]:x86-windows
  * eigen3[core]:x86-windows
  * expat[core]:x86-windows
  * flann[core]:x86-windows
  * freetype[bzip2,core,png]:x86-windows
  * glew[core]:x86-windows
  * hdf5[core,szip,zlib]:x86-windows
  * jsoncpp[core]:x86-windows
  * libharu[core,notiffsymbols]:x86-windows
  * libiconv[core]:x86-windows
  * libjpeg-turbo[core]:x86-windows
  * liblzma[core]:x86-windows
  * libogg[core]:x86-windows
  * libpng[core]:x86-windows
  * libtheora[core]:x86-windows
  * libxml2[core]:x86-windows
  * lz4[core]:x86-windows
  * netcdf-c[core]:x86-windows
  * openssl[core]:x86-windows
  * openssl-windows[core]:x86-windows
    pcl[core]:x86-windows
  * pegtl-2[core]:x86-windows
  * proj4[core,database]:x86-windows
  * pugixml[core]:x86-windows
  * qhull[core]:x86-windows
  * sqlite3[core,tool]:x86-windows
  * szip[core]:x86-windows
  * tiff[core]:x86-windows
  * utfcpp[core]:x86-windows
  * vtk[core]:x86-windows
  * xxhash[core]:x86-windows
  * zlib[core]:x86-windows
  * zstd[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/122: boost-compatibility:x86-windows
Building package boost-compatibility[core]:x86-windows...
-- Using cached D:/Work 2019/GIT Code/vcpkg/downloads/boostorg-compatibility-boost-1.73.0.tar.gz
-- Using source at D:/Work 2019/GIT Code/vcpkg/buildtrees/boost-compatibility/src/ost-1.73.0-44642da97c
-- Packaging headers
-- Packaging headers done
-- Using cached D:/Work 2019/GIT Code/vcpkg/downloads/boost_LICENSE_1_0.txt
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:99 (message):


  **File does not have expected hash:

          File path: [ D:/Work 2019/GIT Code/vcpkg/downloads/boost_LICENSE_1_0.txt ]
      Expected hash: [ d6078467835dba8932314c1c1e945569a64b065474d7aced27c9a7acc391d52e9f234138ed9f1aa9cd576f25f12f557e0b733c14891d42c16ecdc4a7bd4d60b8 ]
        Actual hash: [ b3e1ca08971b1c3e8cb11a854d094cea3a5fd2c95cf9e985b5212a4bde7975cc3ae15455e8d9e7dc3f2a47b1285b0a34798fc6e194d4ec2db4ceb76547bf07bb ]**

  Please delete the file and retry if this file should be downloaded again.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:110 (test_hash)
  installed/x86-windows/share/boost-vcpkg-helpers/boost-modular-headers.cmake:17 (vcpkg_download_distfile)
  ports/boost-compatibility/portfile.cmake:12 (boost_modular_headers)
  scripts/ports.cmake:76 (include)


Error: Building package boost-compatibility:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-compatibility:x86-windows
  Vcpkg version: 2020.02.04-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by fangice** [comment]
> @PhoebeHui Hi, I got the same problem when I install pcl.
> I download boost_LICENSE_1_0.txt. But It got "File does not have expected hash" problem.
> Here is the log. Do you have any suggestion?
> 
> > .\vcpkg install pcl
> > Computing installation plan...
> > The following packages will be built and installed:
> 
> * boost-algorithm[core]:x86-windows
> * boost-any[core]:x86-windows
> * boost-array[core]:x86-windows
> * boost-asio[core]:x86-windows
> * boost-assert[core]:x86-windows
> * boost-atomic[core]:x86-windows
> * boost-bimap[core]:x86-windows
> * boost-bind[core]:x86-windows
> * boost-build[core]:x86-windows
> * boost-chrono[core]:x86-windows
> * boost-circular-buffer[core]:x86-windows
> * boost-compatibility[core]:x86-windows
> * boost-concept-check[core]:x86-windows
> * boost-config[core]:x86-windows
> * boost-container[core]:x86-windows
> * boost-container-hash[core]:x86-windows
> * boost-context[core]:x86-windows
> * boost-conversion[core]:x86-windows
> * boost-core[core]:x86-windows
> * boost-coroutine[core]:x86-windows
> * boost-date-time[core]:x86-windows
> * boost-detail[core]:x86-windows
> * boost-dynamic-bitset[core]:x86-windows
> * boost-endian[core]:x86-windows
> * boost-exception[core]:x86-windows
> * boost-filesystem[core]:x86-windows
> * boost-foreach[core]:x86-windows
> * boost-format[core]:x86-windows
> * boost-function[core]:x86-windows
> * boost-function-types[core]:x86-windows
> * boost-functional[core]:x86-windows
> * boost-fusion[core]:x86-windows
> * boost-graph[core]:x86-windows
> * boost-integer[core]:x86-windows
> * boost-interprocess[core]:x86-windows
> * boost-intrusive[core]:x86-windows
> * boost-io[core]:x86-windows
> * boost-iostreams[core]:x86-windows
> * boost-iterator[core]:x86-windows
> * boost-lambda[core]:x86-windows
> * boost-lexical-cast[core]:x86-windows
> * boost-locale[core]:x86-windows
> * boost-math[core]:x86-windows
> * boost-modular-build-helper[core]:x86-windows
> * boost-move[core]:x86-windows
> * boost-mp11[core]:x86-windows
> * boost-mpl[core]:x86-windows
> * boost-multi-array[core]:x86-windows
> * boost-multi-index[core]:x86-windows
> * boost-multiprecision[core]:x86-windows
> * boost-numeric-conversion[core]:x86-windows
> * boost-optional[core]:x86-windows
> * boost-parameter[core]:x86-windows
> * boost-phoenix[core]:x86-windows
> * boost-pool[core]:x86-windows
> * boost-predef[core]:x86-windows
> * boost-preprocessor[core]:x86-windows
> * boost-property-map[core]:x86-windows
> * boost-property-tree[core]:x86-windows
> * boost-proto[core]:x86-windows
> * boost-ptr-container[core]:x86-windows
> * boost-random[core]:x86-windows
> * boost-range[core]:x86-windows
> * boost-ratio[core]:x86-windows
> * boost-rational[core]:x86-windows
> * boost-regex[core]:x86-windows
> * boost-serialization[core]:x86-windows
> * boost-signals2[core]:x86-windows
> * boost-smart-ptr[core]:x86-windows
> * boost-spirit[core]:x86-windows
> * boost-static-assert[core]:x86-windows
> * boost-system[core]:x86-windows
> * boost-test[core]:x86-windows
> * boost-thread[core]:x86-windows
> * boost-throw-exception[core]:x86-windows
> * boost-tokenizer[core]:x86-windows
> * boost-tti[core]:x86-windows
> * boost-tuple[core]:x86-windows
> * boost-type-index[core]:x86-windows
> * boost-type-traits[core]:x86-windows
> * boost-typeof[core]:x86-windows
> * boost-unordered[core]:x86-windows
> * boost-utility[core]:x86-windows
> * boost-uuid[core]:x86-windows
> * boost-variant[core]:x86-windows
> * boost-winapi[core]:x86-windows
> * boost-xpressive[core]:x86-windows
> * bzip2[core]:x86-windows
> * curl[core,non-http,ssl,sspi,winssl]:x86-windows
> * double-conversion[core]:x86-windows
> * eigen3[core]:x86-windows
> * expat[core]:x86-windows
> * flann[core]:x86-windows
> * freetype[bzip2,core,png]:x86-windows
> * glew[core]:x86-windows
> * hdf5[core,szip,zlib]:x86-windows
> * jsoncpp[core]:x86-windows
> * libharu[core,notiffsymbols]:x86-windows
> * libiconv[core]:x86-windows
> * libjpeg-turbo[core]:x86-windows
> * liblzma[core]:x86-windows
> * libogg[core]:x86-windows
> * libpng[core]:x86-windows
> * libtheora[core]:x86-windows
> * libxml2[core]:x86-windows
> * lz4[core]:x86-windows
> * netcdf-c[core]:x86-windows
> * openssl[core]:x86-windows
> * openssl-windows[core]:x86-windows
>   pcl[core]:x86-windows
> * pegtl-2[core]:x86-windows
> * proj4[core,database]:x86-windows
> * pugixml[core]:x86-windows
> * qhull[core]:x86-windows
> * sqlite3[core,tool]:x86-windows
> * szip[core]:x86-windows
> * tiff[core]:x86-windows
> * utfcpp[core]:x86-windows
> * vtk[core]:x86-windows
> * xxhash[core]:x86-windows
> * zlib[core]:x86-windows
> * zstd[core]:x86-windows
>   Additional packages (*) will be modified to complete this operation.
>   Starting package 1/122: boost-compatibility:x86-windows
>   Building package boost-compatibility[core]:x86-windows...
>   -- Using cached D:/Work 2019/GIT Code/vcpkg/downloads/boostorg-compatibility-boost-1.73.0.tar.gz
>   -- Using source at D:/Work 2019/GIT Code/vcpkg/buildtrees/boost-compatibility/src/ost-1.73.0-44642da97c
>   -- Packaging headers
>   -- Packaging headers done
>   -- Using cached D:/Work 2019/GIT Code/vcpkg/downloads/boost_LICENSE_1_0.txt
>   CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:99 (message):
> 
> **File does not have expected hash:
> 
> ```
>       File path: [ D:/Work 2019/GIT Code/vcpkg/downloads/boost_LICENSE_1_0.txt ]
>   Expected hash: [ d6078467835dba8932314c1c1e945569a64b065474d7aced27c9a7acc391d52e9f234138ed9f1aa9cd576f25f12f557e0b733c14891d42c16ecdc4a7bd4d60b8 ]
>     Actual hash: [ b3e1ca08971b1c3e8cb11a854d094cea3a5fd2c95cf9e985b5212a4bde7975cc3ae15455e8d9e7dc3f2a47b1285b0a34798fc6e194d4ec2db4ceb76547bf07bb ]**
> ```
> 
> Please delete the file and retry if this file should be downloaded again.
> 
> Call Stack (most recent call first):
> scripts/cmake/vcpkg_download_distfile.cmake:110 (test_hash)
> installed/x86-windows/share/boost-vcpkg-helpers/boost-modular-headers.cmake:17 (vcpkg_download_distfile)
> ports/boost-compatibility/portfile.cmake:12 (boost_modular_headers)
> scripts/ports.cmake:76 (include)
> 
> Error: Building package boost-compatibility:x86-windows failed with: BUILD_FAILED
> Please ensure you're using the latest portfiles with `.\vcpkg update`, then
> submit an issue at https://github.com/Microsoft/vcpkg/issues including:
> Package: boost-compatibility:x86-windows
> Vcpkg version: 2020.02.04-nohash
> 
> Additionally, attach any relevant sections from the log files above.

Hi, I got the same problem . How did you solve it ?

**Comment by sunsaintx** [comment]
I think I know the problem. It's due to different versions of packages.



发自我的小米手机
在 fangice <notifications@github.com>，2020年6月27日 下午5:06写道：

@PhoebeHui<https://github.com/PhoebeHui> Hi, I got the same problem when I install pcl.
I download boost_LICENSE_1_0.txt. But It got "File does not have expected hash" problem.
Here is the log. Do you have any suggestion?

.\vcpkg install pcl
Computing installation plan...
The following packages will be built and installed:

  *   boost-algorithm[core]:x86-windows
  *   boost-any[core]:x86-windows
  *   boost-array[core]:x86-windows
  *   boost-asio[core]:x86-windows
  *   boost-assert[core]:x86-windows
  *   boost-atomic[core]:x86-windows
  *   boost-bimap[core]:x86-windows
  *   boost-bind[core]:x86-windows
  *   boost-build[core]:x86-windows
  *   boost-chrono[core]:x86-windows
  *   boost-circular-buffer[core]:x86-windows
  *   boost-compatibility[core]:x86-windows
  *   boost-concept-check[core]:x86-windows
  *   boost-config[core]:x86-windows
  *   boost-container[core]:x86-windows
  *   boost-container-hash[core]:x86-windows
  *   boost-context[core]:x86-windows
  *   boost-conversion[core]:x86-windows
  *   boost-core[core]:x86-windows
  *   boost-coroutine[core]:x86-windows
  *   boost-date-time[core]:x86-windows
  *   boost-detail[core]:x86-windows
  *   boost-dynamic-bitset[core]:x86-windows
  *   boost-endian[core]:x86-windows
  *   boost-exception[core]:x86-windows
  *   boost-filesystem[core]:x86-windows
  *   boost-foreach[core]:x86-windows
  *   boost-format[core]:x86-windows
  *   boost-function[core]:x86-windows
  *   boost-function-types[core]:x86-windows
  *   boost-functional[core]:x86-windows
  *   boost-fusion[core]:x86-windows
  *   boost-graph[core]:x86-windows
  *   boost-integer[core]:x86-windows
  *   boost-interprocess[core]:x86-windows
  *   boost-intrusive[core]:x86-windows
  *   boost-io[core]:x86-windows
  *   boost-iostreams[core]:x86-windows
  *   boost-iterator[core]:x86-windows
  *   boost-lambda[core]:x86-windows
  *   boost-lexical-cast[core]:x86-windows
  *   boost-locale[core]:x86-windows
  *   boost-math[core]:x86-windows
  *   boost-modular-build-helper[core]:x86-windows
  *   boost-move[core]:x86-windows
  *   boost-mp11[core]:x86-windows
  *   boost-mpl[core]:x86-windows
  *   boost-multi-array[core]:x86-windows
  *   boost-multi-index[core]:x86-windows
  *   boost-multiprecision[core]:x86-windows
  *   boost-numeric-conversion[core]:x86-windows
  *   boost-optional[core]:x86-windows
  *   boost-parameter[core]:x86-windows
  *   boost-phoenix[core]:x86-windows
  *   boost-pool[core]:x86-windows
  *   boost-predef[core]:x86-windows
  *   boost-preprocessor[core]:x86-windows
  *   boost-property-map[core]:x86-windows
  *   boost-property-tree[core]:x86-windows
  *   boost-proto[core]:x86-windows
  *   boost-ptr-container[core]:x86-windows
  *   boost-random[core]:x86-windows
  *   boost-range[core]:x86-windows
  *   boost-ratio[core]:x86-windows
  *   boost-rational[core]:x86-windows
  *   boost-regex[core]:x86-windows
  *   boost-serialization[core]:x86-windows
  *   boost-signals2[core]:x86-windows
  *   boost-smart-ptr[core]:x86-windows
  *   boost-spirit[core]:x86-windows
  *   boost-static-assert[core]:x86-windows
  *   boost-system[core]:x86-windows
  *   boost-test[core]:x86-windows
  *   boost-thread[core]:x86-windows
  *   boost-throw-exception[core]:x86-windows
  *   boost-tokenizer[core]:x86-windows
  *   boost-tti[core]:x86-windows
  *   boost-tuple[core]:x86-windows
  *   boost-type-index[core]:x86-windows
  *   boost-type-traits[core]:x86-windows
  *   boost-typeof[core]:x86-windows
  *   boost-unordered[core]:x86-windows
  *   boost-utility[core]:x86-windows
  *   boost-uuid[core]:x86-windows
  *   boost-variant[core]:x86-windows
  *   boost-winapi[core]:x86-windows
  *   boost-xpressive[core]:x86-windows
  *   bzip2[core]:x86-windows
  *   curl[core,non-http,ssl,sspi,winssl]:x86-windows
  *   double-conversion[core]:x86-windows
  *   eigen3[core]:x86-windows
  *   expat[core]:x86-windows
  *   flann[core]:x86-windows
  *   freetype[bzip2,core,png]:x86-windows
  *   glew[core]:x86-windows
  *   hdf5[core,szip,zlib]:x86-windows
  *   jsoncpp[core]:x86-windows
  *   libharu[core,notiffsymbols]:x86-windows
  *   libiconv[core]:x86-windows
  *   libjpeg-turbo[core]:x86-windows
  *   liblzma[core]:x86-windows
  *   libogg[core]:x86-windows
  *   libpng[core]:x86-windows
  *   libtheora[core]:x86-windows
  *   libxml2[core]:x86-windows
  *   lz4[core]:x86-windows
  *   netcdf-c[core]:x86-windows
  *   openssl[core]:x86-windows
  *   openssl-windows[core]:x86-windows
pcl[core]:x86-windows
  *   pegtl-2[core]:x86-windows
  *   proj4[core,database]:x86-windows
  *   pugixml[core]:x86-windows
  *   qhull[core]:x86-windows
  *   sqlite3[core,tool]:x86-windows
  *   szip[core]:x86-windows
  *   tiff[core]:x86-windows
  *   utfcpp[core]:x86-windows
  *   vtk[core]:x86-windows
  *   xxhash[core]:x86-windows
  *   zlib[core]:x86-windows
  *   zstd[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/122: boost-compatibility:x86-windows
Building package boost-compatibility[core]:x86-windows...
-- Using cached D:/Work 2019/GIT Code/vcpkg/downloads/boostorg-compatibility-boost-1.73.0.tar.gz
-- Using source at D:/Work 2019/GIT Code/vcpkg/buildtrees/boost-compatibility/src/ost-1.73.0-44642da97c
-- Packaging headers
-- Packaging headers done
-- Using cached D:/Work 2019/GIT Code/vcpkg/downloads/boost_LICENSE_1_0.txt
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:99 (message):

**File does not have expected hash:

      File path: [ D:/Work 2019/GIT Code/vcpkg/downloads/boost_LICENSE_1_0.txt ]
  Expected hash: [ d6078467835dba8932314c1c1e945569a64b065474d7aced27c9a7acc391d52e9f234138ed9f1aa9cd576f25f12f557e0b733c14891d42c16ecdc4a7bd4d60b8 ]
    Actual hash: [ b3e1ca08971b1c3e8cb11a854d094cea3a5fd2c95cf9e985b5212a4bde7975cc3ae15455e8d9e7dc3f2a47b1285b0a34798fc6e194d4ec2db4ceb76547bf07bb ]**


Please delete the file and retry if this file should be downloaded again.

Call Stack (most recent call first):
scripts/cmake/vcpkg_download_distfile.cmake:110 (test_hash)
installed/x86-windows/share/boost-vcpkg-helpers/boost-modular-headers.cmake:17 (vcpkg_download_distfile)
ports/boost-compatibility/portfile.cmake:12 (boost_modular_headers)
scripts/ports.cmake:76 (include)

Error: Building package boost-compatibility:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with .\vcpkg update, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
Package: boost-compatibility:x86-windows
Vcpkg version: 2020.02.04-nohash

Additionally, attach any relevant sections from the log files above.

Hi, I got the same problem . How did you solve it ?
