### ISSUE TITLE
[libepoxy] build failure

### ISSUE THREAD

**Issue by weirdworkshop** [microsoft/vcpkg#11669]
**Host Environment**
- OS: Win 10
- Compiler: cmd

**To Reproduce**
`./vcpkg install libepoxy:x64-windows

The following packages will be built and installed:
    libepoxy[core]:x64-windows
Starting package 1/1: libepoxy:x64-windows
Building package libepoxy[core]:x64-windows...
-- Using cached C:/Users/catherine jones/vcpkg/downloads/anholt-libepoxy-1.5.4.tar.gz
-- Using source at C:/Users/catherine jones/vcpkg/buildtrees/libepoxy/src/1.5.4-337c486045
-- Acquiring MSYS Packages...
-- Acquiring MSYS Packages... OK
-- Configuring x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: "C:/Users/catherine jones/vcpkg/downloads/tools/python/python-3.7.3-x64/python.exe" "C:/Users/catherine jones/vcpkg/downloads/tools/meson/meson-0.54.2/meson.py" -Denable-glx=no -Denable-egl=no "-Dcmake_prefix_path=['C:/Users/catherine jones/vcpkg/installed/x64-windows','C:/Users/catherine jones/vcpkg/installed/x64-windows/share']" --buildtype plain --backend ninja --wrap-mode nodownload --default-library shared --libdir lib --prefix "C:/Users/catherine jones/vcpkg/packages/libepoxy_x64-windows/debug" --includedir ../include "C:/Users/catherine jones/vcpkg/buildtrees/libepoxy/src/1.5.4-337c486045" -Dc_args=['/DWIN32','/D_WINDOWS','/W3','/MP','/D_DEBUG','/MDd','/Z7','/Ob0','/Od','/RTC1'] -Dcpp_args=['/DWIN32','/D_WINDOWS','/W3','/GR','/EHsc','/MP','/D_DEBUG','/MDd','/Z7','/Ob0','/Od','/RTC1'] -Dc_link_args=[] -Dcpp_link_args=[]
    Working Directory: C:/Users/catherine jones/vcpkg/buildtrees/libepoxy/x64-windows-dbg
    Error code: 2
    See logs for more information:
      C:\Users\catherine jones\vcpkg\buildtrees\libepoxy\config-x64-windows-dbg-out.log
      C:\Users\catherine jones\vcpkg\buildtrees\libepoxy\config-x64-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_meson.cmake:161 (vcpkg_execute_required_process)
  ports/libepoxy/portfile.cmake:16 (vcpkg_configure_meson)
  scripts/ports.cmake:90 (include)

Error: Building package libepoxy:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libepoxy:x64-windows
  Vcpkg version: 2020.02.04-nohash

Additionally, attach any relevant sections from the log files above.
[config-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/4706657/config-x64-windows-dbg-err.log)
[config-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/4706658/config-x64-windows-dbg-out.log)

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by PhoebeHui** [comment]
@weirdworkshop, I can't repro this issue, it built successfully for me, from your log:

lt is likely that your environment is messed up. the python environments involved here is strange for me: D:\obj\Windows-Release\37amd64_Release\msi_python\zip_amd64\subprocess.py

Failure:
  File "C:\Users\catherine jones\vcpkg\downloads\tools\meson\meson-0.54.2\mesonbuild\mesonlib.py", line 1202, in Popen_safe_legacy
    stdout=stdout, stderr=stderr, **kwargs)
  File "D:\obj\Windows-Release\37amd64_Release\msi_python\zip_amd64\subprocess.py", line 775, in __init__
  File "D:\obj\Windows-Release\37amd64_Release\msi_python\zip_amd64\subprocess.py", line 1178, in _execute_child
OSError: [WinError 193] %1 is not a valid Win32 application

**Comment by weirdworkshop** [comment]
Thanks.  not sure where "D:\obj\Windows-Release\37amd64_Release\msi_python\zip_amd64\subprocess.py"  was coming from.  Ended up deleting my python install. Deleting all the python files in Appdata\Roaming,  removed my D drive which is an external drive.  neither fixed it.  But did start getting error messages because it didn't like installing into my user folder 'Catherine Jones' two separate words.  So installed onto root of C Drive and that worked.
