### ISSUE TITLE
Using vcpkg installed libraries with external projects

### ISSUE THREAD

**Issue by sedapsfognik** [Microsoft/vcpkg#1166]
Hello!

I'm using vcpkg and all is working fine.
I just want to ask: is there a way to use libraries installed by vcpkg with libraries that do not exist in vcpkg database?
Currently I'm trying to cmake and compile "mysql connector c++" which requires boost.
I can't just set path to boost(as I understand), because boost's 'hierarchy' of includes/libraries etc directories was reimplemented by vcpkg. And there is no BOOST_DIR in it's standard meaning.
I just do not want to download separate boost(and other libraries) just to cmake and compile libraries those do not present in vcpkg yet.

I think it would be very good to have such an ability.
Thanks.

**Comment by Voskrese** [comment]
я сам недавно начал разбираться )
но возможно это поможет

> # Create and move into the build directory
> mkdir build
> cd build
> # Configure the project
> cmake ../ -DCMAKE_FIND_ROOT_PATH=/opt/mips_linux_toolchain/ \
> -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY \
> -DCMAKE_CXX_COMPILER=/opt/mips_linux_toolchain/bin/mips-linux-gnu-g++ \
> -DLIBTINS_ENABLE_WPA2=0 \
> -DCROSS_COMPILING=1

**-DCMAKE_FIND_ROOT_PATH**

cmake . -DVCPKG_TARGET_TRIPLET=x86-windows -DCMAKE_BUILD_TYPE=Release -DVCPKG_PLATFORM_TOOLSET=v140 -DCMAKE_INSTALL_PREFIX=E:\tools\vcpkg\installed\Extern **-DCMAKE_FIND_ROOT_PATH=E:\tools\vcpkg\installed\x86-windows**  -G "Visual Studio 14 2015"

> CMAKE_FIND_ROOT_PATH: this indicates the root path in which the toolchain is installed.
> CMAKE_FIND_ROOT_PATH_MODE_LIBRARY: this is not required, but it's a useful flag. It tells CMake to only look for libraries in the path provided by the previous option. Without it, it could detect another installation of them, even if they're compiled for another architecture.

Меня так интересует этот вопрос. Надеюсь более опытные подскажут ответ

**Comment by ras0219-msft** [comment]
Hi @sedapsfognik!

We definitely support building other libraries on top of vcpkg :). Depending on the buildsystem of that library, it should be as simple as following our standard use example [1]. For example, if the project you want to build uses CMake (which I believe MySQL Connector does), you can simply add
```
-DCMAKE_TOOLCHAIN_FILE=/path/to/vcpkg/scripts/buildsystems/vcpkg.cmake
```
onto your cmake configure line.

[1] https://github.com/Microsoft/vcpkg/blob/b01984a739c1edbbab081848db5062e70343c2a7/docs/EXAMPLES.md#example-1-2
