### ISSUE TITLE
[New Port Request] libiptcdata

### ISSUE THREAD

**Issue by pokev25** [microsoft/vcpkg#11670]
Library name: libiptcdata

Library description:
libiptcdata is a library for manipulating the International Press
Telecommunications Council (IPTC) metadata stored within multimedia
files such as images

Source repository URL:
https://github.com/ianw/libiptcdata

Project homepage (if different from the source repository):
http://libiptcdata.sourceforge.net/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
