### ISSUE TITLE
[curl] build failure dynamic linkage

### ISSUE THREAD

**Issue by ASxa86** [microsoft/vcpkg#11679]
**Host Environment**
- OS: Ubuntu 18.04, Ubuntu 20.04
- Compiler: gcc v9.3.0

**To Reproduce**
First, I defined a triplet for dynamic linkage on linux and then ran the following command:
`./vcpkg install curl:x64-linux-shared`

**Failure logs** 
`There should be no empty directories in /home/aaron/dev/vcpkg/packages/curl_x64-linux-shared
The following empty directories were found:

    /home/aaron/dev/vcpkg/packages/curl_x64-linux-shared/bin
    /home/aaron/dev/vcpkg/packages/curl_x64-linux-shared/debug/bin

If a directory should be populated but is not, this might indicate an error in the portfile.
If the directories are not needed and their creation cannot be disabled, use something like this in the portfile to remove them:

    file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/a/dir" "${CURRENT_PACKAGES_DIR}/some/other/dir")

Found 1 error(s). Please correct the portfile:
    /home/aaron/dev/vcpkg/ports/curl/portfile.cmake
-- Performing post-build validation done
Error: Building package curl:x64-linux-shared failed with: POST_BUILD_CHECKS_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: curl:x64-linux-shared
  Vcpkg version: 2020.02.04-unknownhash

Additionally, attach any relevant sections from the log files above.`

**Additional context**
I was able to resolve this issue by making sure the bin directories were removed in the curl/portfile.cmake file. It appears the directories were only getting removed for static builds.

**Comment by U-v-U** [comment]
```
 ports/curl/portfile.cmake | 1 +
 1 file changed, 1 insertion(+)

diff --git a/ports/curl/portfile.cmake b/ports/curl/portfile.cmake
index 0ad9cd7a2..392b52dac 100644
--- a/ports/curl/portfile.cmake
+++ b/ports/curl/portfile.cmake
@@ -90,6 +90,7 @@ if(VCPKG_LIBRARY_LINKAGE STREQUAL "static")
 else()
     file(INSTALL ${CURRENT_PACKAGES_DIR}/bin/curl-config DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT})
     file(REMOVE ${CURRENT_PACKAGES_DIR}/bin/curl-config ${CURRENT_PACKAGES_DIR}/debug/bin/curl-config)
+    file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/bin ${CURRENT_PACKAGES_DIR}/debug/bin)
     #Fix install path
     file(READ ${CURRENT_PACKAGES_DIR}/share/${PORT}/curl-config CURL_CONFIG)
     string(REPLACE "${CURRENT_PACKAGES_DIR}" "${CURRENT_INSTALLED_DIR}" CURL_CONFIG "${CURL_CONFIG}")
```

Apply this patch onto the curl's `portfile.cmake` could fix the error.

**Comment by Adela0814** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
