### ISSUE TITLE
[openssl][uwp] Enable stdio for UWP port. (Verify peers and host is not working with openssl uwp port)

### ISSUE THREAD

**Issue by fengli** [microsoft/vcpkg#11674]
****

**Is your feature request related to a problem? Please describe.**
[SSL_CTX_load_verify_locations](https://www.openssl.org/docs/man1.0.2/man3/SSL_CTX_load_verify_locations.html) is required for UWP port to load ca file since OpenSSL will not use the CA of the OS.

But in UWP build, stdio is disabled by default. However, SSL_CTX_load_verify_locations relies on the default X509_STORE file lookup functionality uses stdio (via BIO_s_file). That basically means no verification of peers and hosts is possible with OpenSSL.

**Proposed solution**
Enable stdio in UWP build for openssl. (currently, the build with enabling stdio will fail)

**More context**
[curl] [x64-uwp] cannot set certification verify locations https://github.com/microsoft/vcpkg/issues/11663

**Comment by Neumann-A** [comment]
Discuss that with upstream since it is an upstream setting

https://github.com/openssl/openssl/blob/082c041b4233b17b80129d4ac6b33a28014442b0/Configurations/50-win-onecore.conf#L113

**Comment by fengli** [comment]
> Discuss that with upstream since it is an upstream setting
> 
> https://github.com/openssl/openssl/blob/082c041b4233b17b80129d4ac6b33a28014442b0/Configurations/50-win-onecore.conf#L113

Can you elaborate more? Upstream you mean openssl? But the configuration we have is in vcpkg right? The “disable stdio” in the link you provided.

**Comment by Neumann-A** [comment]
> But the configuration we have is in vcpkg right? 

If you would inspect the link a bit more careful you would see that the configuration is in openssl and not in vcpkg. vcpkg just uses that configuration to build for UWP since it is the configuration ment for UWP by openssl. Maybe there is some reason that it is deactivated in UWP and another way to use/load certificates in UWP?

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
