### ISSUE TITLE
file RENAME failed to rename (build fails by CMake)

### ISSUE THREAD

**Issue by peterTonic2000** [microsoft/vcpkg#11685]
file RENAME failed to rename (build fails by CMake)

**Environment**
- OS: Win10
- Visual Studio 2019 16.6
- Vcpkg version 2020.02.04-nohas

**To Reproduce**
1. ./vcpkg install tesseract (or any other package)

Extracting 7zip...
A suitable version of nuget was not found (required v4.8.1). Downloading portable nuget v4.8.1...
Downloading nuget...
  https://dist.nuget.org/win-x86-commandline/v4.8.1/nuget.exe -> C:\Developer\vcpkg\downloads\nuget.exe
Starting package 1/9: giflib:x86-windows
Building package giflib[core]:x86-windows...
-- Note: giflib only supports static library linkage. Building static library.
-- Downloading https://nchc.dl.sourceforge.net/project/giflib/giflib-5.1.4.tar.bz2...
CMake Error at C:/Developer/vcpkg/scripts/cmake/vcpkg_download_distfile.cmake:185 (file):
  file RENAME failed to rename

    /c/Developer/vcpkg/C:/Developer/vcpkg/downloads/temp/giflib-5.1.4.tar.bz2

  to

    /c/Developer/vcpkg/C:/Developer/vcpkg/downloads/giflib-5.1.4.tar.bz2

  because: No such file or directory

**Expected behavior**
After new installation of vcpkg, installation of first package should work.

This happens with any package I want to install. Have tried reinstall vcpkg several times, does not solve the problem.

Both folders do exist (& ".../temp/giflib-5.1.4.tar.bz2" exists). 

What is going wrong?

**Comment by JackBoosY** [comment]
Can you confirm your vcpkg is latest?

**Comment by cenit** [comment]
`/c/Developer/vcpkg/C:/Developer/vcpkg` path also looks very strange. 
Which shell are you using?

**Comment by peterTonic2000** [comment]
Hi & thanks for your reply.

Yes, latest vcpkg (I downloaded & bootstrapped vcpkg yesterday several
times). I tried both, power shell & cmd.

Do I need to install anything else besides visual studio, git & vcpkg? What
about c++ workload?

Also, maybe the problem comes from some my msys2 installation (I added the
paths to the environment), maybe confusing of cmake versions, ...?

By the way, my windows is win10, 10.0.18368 Home.

**Comment by JackBoosY** [comment]
@peterTonic2000 From your info, please remove msys2 first, then try to install port.

Thanks.

**Comment by peterTonic2000** [comment]
Hi there. I renamed the msys folder so that the msys files are not found by
the system --> compilation /installation via vcpkg seems to work.

I also tried it with sqlite: I find a folder
"C:\Developer\vcpkg\packages\sqlite3_x86-windows\include" with two header
files. So the installation seems to be successfull - right?

**Comment by Neumann-A** [comment]
>So the installation seems to be successfull - right?

Only if the headers are also in `C:\Developer\vcpkg\installed\x86-windows\include` otherwise the installation is incomplete

**Comment by peterTonic2000** [comment]
Yes, the header files are also in .. vcpkg\installed\x86-windows\include

I also tried to include the headers in visual studio, works as well.

thanks for your help!
