### ISSUE TITLE
[osg] build failure

### ISSUE THREAD

**Issue by ASxa86** [microsoft/vcpkg#11686]
**Host Environment**
- OS: Ubuntu 18.04
- Compiler: gcc v7.5.0

**To Reproduce**
`./vcpkg install osg:x64-linux`

**Failure logs** 
Building package osg[core,plugins]:x64-linux...
-- Using cached /home/aaron/dev/vcpkg/downloads/openscenegraph-OpenSceneGraph-OpenSceneGraph-3.6.4.tar.gz
-- Using source at /home/aaron/dev/vcpkg/buildtrees/osg/src/raph-3.6.4-c5448290ed
Build osg requires gcc with version higher than 4.7.
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: /home/aaron/dev/vcpkg/downloads/tools/cmake-3.17.2-linux/cmake-3.17.2-Linux-x86_64/bin/cmake --build . --config Debug --target install -- -v
    Working Directory: /home/aaron/dev/vcpkg/buildtrees/osg/x64-linux-dbg
    See logs for more information:
      /home/aaron/dev/vcpkg/buildtrees/osg/install-x64-linux-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/osg/portfile.cmake:75 (vcpkg_install_cmake)
  scripts/ports.cmake:90 (include)

Error: Building package osg:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: osg:x64-linux
  Vcpkg version: 2020.02.04-unknownhash
[install-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/4708811/install-x64-linux-dbg-out.log)

**Additional context**
Seems to be a compile error with one of the plugins that depends on asio within osg.

**Comment by NancyLi1013** [comment]
Related PR #11645.
