### ISSUE TITLE
[geos] build failure dynamic linkage

### ISSUE THREAD

**Issue by ASxa86** [microsoft/vcpkg#11681]
**Host Environment**
- OS: Ubuntu 20.04
- Compiler: gcc v9.3.0

**To Reproduce**
`./vcpkg install geos:x64-linux-shared`

**Failure logs** 
There should be no empty directories in /home/aaron/dev/vcpkg/packages/geos_x64-linux-shared
The following empty directories were found:

    /home/aaron/dev/vcpkg/packages/geos_x64-linux-shared/bin
    /home/aaron/dev/vcpkg/packages/geos_x64-linux-shared/debug/bin

If a directory should be populated but is not, this might indicate an error in the portfile.
If the directories are not needed and their creation cannot be disabled, use something like this in the portfile to remove them:

    file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/a/dir" "${CURRENT_PACKAGES_DIR}/some/other/dir")

Found 1 error(s). Please correct the portfile:
    /home/aaron/dev/vcpkg/ports/geos/portfile.cmake
-- Performing post-build validation done
Error: Building package geos:x64-linux-shared failed with: POST_BUILD_CHECKS_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: geos:x64-linux-shared
  Vcpkg version: 2020.02.04-unknownhash

Additionally, attach any relevant sections from the log files above.

**Additional context**
Fix by removing the linkage check in to portfile.cmake prior to removing the bin directories.

**Comment by JackBoosY** [comment]
Solved by #17616.
