### ISSUE TITLE
Why not conan Public federation vs private federation

### ISSUE THREAD

**Issue by IceflowRE** [microsoft/vcpkg#11684]
With [conan center index](https://github.com/conan-io/conan-center-index), the argument
> Conan relies on individuals publishing independent copies of each package. We believe this approach encourages a large number of packages that are all broken in different ways. We believe it is a waste of user's time to pick through the list of 20+ public packages for Boost 1.56 to determine the handful that will work for their particular situation. 

Becomes a bit invalid, as a centered repository everyone can contribute to, exists.

**Comment by PhoebeHui** [comment]
I think we can close this issue now, see the package federation in vcpkg https://github.com/microsoft/vcpkg/blob/master/docs/specifications/registries.md
https://github.com/microsoft/vcpkg/blob/master/docs/specifications/registries-2.md

**Comment by IceflowRE** [comment]
https://vcpkg.readthedocs.io/en/latest/about/faq/#why-not-conan

The FAQ is still wrong.

**Comment by PhoebeHui** [comment]
@IceflowRE, thanks for the information!

**Comment by vicroms** [comment]
@IceflowRE I also think that the FAQ is due for an update, both vcpkg and Conan have changed a lot since the document was originally written.
