### ISSUE TITLE
[libevent] build failure dynamic linkage

### ISSUE THREAD

**Issue by ASxa86** [microsoft/vcpkg#11680]
**Host Environment**
- OS: Ubuntu 20.04
- Compiler: gcc v9.3.0

**To Reproduce**
First, define a triplet for dynamic linkage.
`./vcpkg install libevent:x64-linux-shared`

**Failure logs** 
There should be no empty directories in /home/aaron/dev/vcpkg/packages/libevent_x64-linux-shared
The following empty directories were found:

    /home/aaron/dev/vcpkg/packages/libevent_x64-linux-shared/bin

If a directory should be populated but is not, this might indicate an error in the portfile.
If the directories are not needed and their creation cannot be disabled, use something like this in the portfile to remove them:

    file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/a/dir" "${CURRENT_PACKAGES_DIR}/some/other/dir")

Found 1 error(s). Please correct the portfile:
    /home/aaron/dev/vcpkg/ports/libevent/portfile.cmake
-- Performing post-build validation done
Error: Building package libevent:x64-linux-shared failed with: POST_BUILD_CHECKS_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libevent:x64-linux-shared
  Vcpkg version: 2020.02.04-unknownhash

Additionally, attach any relevant sections from the log files above.

**Additional context**
This can be resolved in the portfile.cmake by removing the linkage check prior to removing bin directories.

**Comment by Adela0814** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
