### ISSUE TITLE
[libgeotiff] build failure linux dynamic

### ISSUE THREAD

**Issue by ASxa86** [microsoft/vcpkg#11682]
**Host Environment**
- OS: Ubuntu 20.04
- Compiler: gcc v9.3.0

**To Reproduce**
`./vcpkg install libgeotiff:x64-linux-shared`

**Failure logs** 
There should be no empty directories in /home/aaron/dev/vcpkg/packages/libgeotiff_x64-linux-shared
The following empty directories were found:

    /home/aaron/dev/vcpkg/packages/libgeotiff_x64-linux-shared/bin

If a directory should be populated but is not, this might indicate an error in the portfile.
If the directories are not needed and their creation cannot be disabled, use something like this in the portfile to remove them:

    file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/a/dir" "${CURRENT_PACKAGES_DIR}/some/other/dir")

Found 1 error(s). Please correct the portfile:
    /home/aaron/dev/vcpkg/ports/libgeotiff/portfile.cmake
-- Performing post-build validation done
Error: Building package libgeotiff:x64-linux-shared failed with: POST_BUILD_CHECKS_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libgeotiff:x64-linux-shared
  Vcpkg version: 2020.02.04-unknownhash

Additionally, attach any relevant sections from the log files above.

**Additional context**
I resolved this by removing the static linkage check in the libgeotiff/portfile.cmake file in order to remove the bin directories.

**Comment by Osyotr** [comment]
@NancyLi1013 I think this issue can be closed now. I've been able to build it with x64-linux-dynamic
