### ISSUE TITLE
[New Port Request] gdl (GNOME docking library) 

### ISSUE THREAD

**Issue by brukted** [microsoft/vcpkg#11690]
Library name:
gdl (GNOME docking library) 

Library description:
gdl provides docking feature to gdk+ widgets.

Source repository URL:
https://github.com/GNOME/gdl

Project homepage (if different from the source repository):
https://developer.gnome.org/gdl/

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
