### ISSUE TITLE
How do I use gtkmm?

### ISSUE THREAD

**Issue by brukted** [microsoft/vcpkg#11705]
I am trying to use gtkmm with vcpkg but It neither has pkg-config nor cmake support?

**Comment by PhoebeHui** [comment]
See example https://github.com/microsoft/vcpkg/blob/master/docs/examples/installing-and-using-packages.md#handling-libraries-without-native-cmake-support

**Comment by brukted** [comment]
Thanks

**Comment by renjuashokan** [comment]
I created one CMake file for both windows and Linux.

https://gist.github.com/renjuashokan/88f6acec7d4a6f6462abed548423c349
