### ISSUE TITLE
PkgConfig and temporary folders

### ISSUE THREAD

**Issue by brukted** [microsoft/vcpkg#11700]
I was looking around to write a script that can generate pkgConfig files for any port and I found that pkgCofig files like spdlog's point directories in packages as include directories. But according to vcpkg's [docs()](https://vcpkg.readthedocs.io/en/latest/about/faq/#how-can-i-remove-temporary-files) packages is a temporary folder so it isn't guaranteed to exist. So my question is should pkgCofig files point to directories in installed or in packages ? Can you elaborate on vcpkg folder structure as a whole?

**Comment by Neumann-A** [comment]
apparently spdlog is missing a `vcpkg_fixup_pkgconfig` call.
