### ISSUE TITLE
[icu] build icu with CMake

### ISSUE THREAD

**Issue by invy** [microsoft/vcpkg#11717]
Building icu with msys seems to be very unstable, so IMHO it would be much less effort, if we'd be able to build it using CMake.

**Comment by JackBoosY** [comment]
However, the official does not support cmake, which means that we need to write `CMakeLists.txt`, which will increase the chance of unknowable errors.

**Comment by invy** [comment]
@JackBoosY yes, this is of course risk factor, but what is the viable cross platform alternative for cmake anyway? vcpkg is trying to target cross platform development and is pretty good at it, except some corner cases. There are bunch of other packages which also use msys, but what makes icu painful, is, that it's in the boost dependencies, so if icu build breaks, it breakes pretty much 'everything'.
Alternatively, ICU provides msbuild project, which we can build, when building with msvc.

**Comment by invy** [comment]
also consider this repo:
https://github.com/viaduck/icu-cmake

**Comment by JackBoosY** [comment]
@invy Like now, we can choose different ways to build icu according to different platforms. And we better follow the official build plan.

**Comment by invy** [comment]
@JackBoosY hm yes, I agree. There should be better sustainable solution regarding msys.
We could close the issue.
