### ISSUE TITLE
[New Port Request] sdl-gpu

### ISSUE THREAD

**Issue by KiritoDv** [microsoft/vcpkg#11710]
Library name: sdl-gpu

Library description: A library for high-performance, modern 2D graphics with SDL written in C.

Source repository URL: https://github.com/grimfang4/sdl-gpu

Project homepage (if different from the source repository): 

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by MrEmii** [comment]
Ooooh yeeeeeeeeeeeeeeeees

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
