### ISSUE TITLE
[vtk:x64-windows] build failure

### ISSUE THREAD

**Issue by JRoca1** [microsoft/vcpkg#11724]
**Host Environment**
- OS: Windows 10
- Compiler: cmake-3.17.2-windows

**To Reproduce**
`./vcpkg install vtk:x64-windows

**Failure logs** 
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: C:/vcpkg-master/downloads/tools/cmake-3.17.2-windows/cmake-3.17.2-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v
    Working Directory: C:/vcpkg-master/buildtrees/vtk/x64-windows-dbg
    See logs for more information:
      C:\vcpkg-master\buildtrees\vtk\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/vtk/portfile.cmake:153 (vcpkg_install_cmake)
  scripts/ports.cmake:90 (include)

Error: Building package vtk:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: vtk:x64-windows
  Vcpkg version: 2020.02.04-nohash

[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/4717360/install-x64-windows-dbg-out.log)

**Comment by Neumann-A** [comment]
ICE try updating your visual studio. Nothing I could help here either way.

**Comment by JRoca1** [comment]
Hello.

Updating Visual Studio works for me.

Best regards.
