### ISSUE TITLE
[New Port Request] OpenImageDenoise

### ISSUE THREAD

**Issue by chena1982** [microsoft/vcpkg#11749]
Library name : OpenImageDenoise

Library description: Intel Open Image Denoise is an open source library of high-performance, high-quality denoising filters for images rendered with ray tracing

Source repository URL: https://github.com/OpenImageDenoise/oidn
Project homepage: https://openimagedenoise.github.io/

Thanks.

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by flarive** [comment]
I would be very interested by a vcpkg port of OIDN (OpenImageDenoise), how could i reopen this closed issue ?
