### ISSUE TITLE
[nanogui] update to 2020-04-05

### ISSUE THREAD

**Issue by Lvdi** [microsoft/vcpkg#11743]
Library name: NanoGUI

New version number: 2020-04-05

Other information that may be useful (release notes, etc...)

NanoGUI's repository has been moved [here](https://github.com/mitsuba-renderer/nanogui), and the [old one](https://github.com/wjakob/nanogui) is not going to be updated any more.

**Comment by xarthurx** [comment]
https://github.com/microsoft/vcpkg/issues/8761

**Comment by xarthurx** [comment]
The current version of `nanogui` is still using the old github repo, which has stopped developing.

https://github.com/microsoft/vcpkg/issues/8761
This issue has not been resolve actually.

**Comment by JonLiu1993** [comment]
Duplicate #17052
