### ISSUE TITLE
[fmt] build failure

### ISSUE THREAD

**Issue by iaanus** [microsoft/vcpkg#11740]
**Host Environment**
- OS: Windows
- Compiler: Visual Studio 2019

**To Reproduce**
`./vcpkg install fmt:x64-windows`

**Failure logs** 
Starting package 1/1: fmt:x64-windows
Building package fmt[core]:x64-windows...
-- Downloading https://github.com/fmtlib/fmt/archive/9bdd1596cef1b57b9556f8bef32dc4a32322ef3e.tar.gz...
-- Extracting source D:/Alberto/Documenti/C++/vcpkg/downloads/fmtlib-fmt-9bdd1596cef1b57b9556f8bef32dc4a32322ef3e.tar.gz
-- Applying patch fix-warning4189.patch
-- Using source at D:/Alberto/Documenti/C++/vcpkg/buildtrees/fmt/src/a32322ef3e-ffe1c8c171
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: D:/Alberto/Documenti/C++/vcpkg/packages/fmt_x64-windows/share/fmt/copyright
-- Fixing pkgconfig
CMake Error at scripts/cmake/vcpkg_fixup_pkgconfig.cmake:207 (list):
  list sub-command FILTER, mode REGEX failed to compile regex
  "D:/Alberto/Documenti/C++/vcpkg/packages/fmt_x64-windows/debug/".
Call Stack (most recent call first):
  ports/fmt/portfile.cmake:44 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:90 (include)

RegularExpression::compile(): Nested *?+.
RegularExpression::compile(): Error in compile.
Error: Building package fmt:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: fmt:x64-windows
  Vcpkg version: 2020.02.04-nohash

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by iaanus** [comment]
Problem might occur because vcpkg is installed in a pathname that contains "C++".

**Comment by NancyLi1013** [comment]
Hi @iaanus 
Thanks for posting this issue.
It seems to be related with the path that contain "++". 

Could you please try to build this in another directory? I can build successfully on my local.

**Comment by NancyLi1013** [comment]
@Neumann-A 
Could you please help take a look? It is related with `vcpkg_fixup_pkgconfig.cmake`.

Is it possible to handle the path like this?

**Comment by Neumann-A** [comment]
I think it is related to any REGEX operation within VCPKG on paths and there a probly more than the one in vcpkg_fixup_pkgconfig. The solution to that would be to escape the regex characters before use in a regex expression. Maybe we should define extra escaped path variables for that and replace them everywhere within vcpkg.

**Comment by iaanus** [comment]
@NancyLi1013 yes, moving to a different directory, I am able to build successfully.

**Comment by NancyLi1013** [comment]
@Neumann-A 
Thanks for your above suggestion. We might need to fix this in the future.

@iaanus 
Thanks for your update. I'm closing this issue for now.
