### ISSUE TITLE
Build system expects executable in environment search path - best practice?

### ISSUE THREAD

**Issue by bagong** [Microsoft/vcpkg#1174]
Hi,

I have a case where a given build system for a library (qtwebkit) expects both gperf and cmake to be available via environment search path. Vcpkg replaces system and user path, and uses a path with build relevant entries only. I guess that's a well considered careful approach. But how to deal with build systems (I think there must be may) that expect entries in the path? Add what is needed? For gperf it's easy, as it would be downloaded through vcpkg_find_acquire_program, so the path is clear and gperf seems unproblematic, but how about cmake? It could reside in many places. So I think my question are two:

- is something like `SET(ENV{PATH} "$ENV{PATH};${GPERF_DIR}")` okay?
- is it problematic to add cmake to the path, and if not, how to best do it to cover all possible install locations. Does vcpkg maybe provide a variable?

**Comment by ras0219-msft** [comment]
Yep! Modifying the ENV macro is the way to do it. If I remember right, openssl does this.

Additionally, since we are using cmake as the scripting language, the cmake executable is always available as `${CMAKE}`. That's how `vcpkg_configure_cmake` works.

**Comment by bagong** [comment]
Another case, I just bumped into, if you don't mind: qtwebkit runs Qt5's rcc.exe as part of the build. Rcc is found, but it requires zlib.dll to run (and maybe more libs). Would we therefore add `installed\<triplet>\bin` to the path of the build-shell (like the gperf-case above)?

**Comment by ras0219-msft** [comment]
Exactly right again :). GRPC does this:

```cmake
# gRPC runs built executables during the build, so they need access to the installed DLLs.
set(ENV{PATH} "$ENV{PATH};${CURRENT_INSTALLED_DIR}/bin;${CURRENT_INSTALLED_DIR}/debug/bin")
```

https://github.com/Microsoft/vcpkg/blob/93d46a9a612d2c09b3861532ed427a197da887be/ports/grpc/portfile.cmake#L52

**Comment by bagong** [comment]
Thumbs also for thinking through adding the bin-path by default. I guess the earlier it is done, the more efficiently real world problems will help to tell if it's a good thing or not. It is easy to imagine many cases where adding the bin folder to the path would be useful. E.g. in tests.
