### ISSUE TITLE
compiling package “opencv4:x64”-windows  with VCPKGB

### ISSUE THREAD

**Issue by dswcmp** [microsoft/vcpkg#11741]
When I first started learning machine learning, I had problems building the environment
OS：windows10.0.18363.836
Newly downloaded VCPKG

I cloned and compiled vcpkg. then ran the command.\vcpkg.exe install Darknet [Full]: X64-Windows started everything ok with a lot of things installed.And then you run into problems.
error log:
-- Using cached E:/vcpkg_darknet/vcpkg/downloads/opencv-opencv-4.1.1.tar.gz
-- Using source at E:/vcpkg_darknet/vcpkg/buildtrees/opencv4/src/4.1.1-fb9e10326a
-- Using cached E:/vcpkg_darknet/vcpkg/downloads/opencv-cache/tiny_dnn/adb1c512e09ca2c7a6faef36f9c53e59-v1.0.0a3.tar.gz
-- Using cached E:/vcpkg_darknet/vcpkg/downloads/opencv-cache/nvidia_optical_flow/ca5acedee6cb45d0ec610a6732de5c15-79c6cee80a2df9a196f20afd6b598a9810964c32.zip
-- Using cached E:/vcpkg_darknet/vcpkg/downloads/opencv-opencv_contrib-4.1.1.tar.gz
-- Using source at E:/vcpkg_darknet/vcpkg/buildtrees/opencv4/src/4.1.1-521dd00bd2
-- Downloading https://raw.githubusercontent.com/opencv/opencv_3rdparty/34e4206aef44d50e6bbcd0ab06354b52e7466d26/boostdesc_bgm.i...
-- Downloading https://raw.githubusercontent.com/opencv/opencv_3rdparty/34e4206aef44d50e6bbcd0ab06354b52e7466d26/boostdesc_bgm.i... Failed. Status: 7;"Couldn't connect to server"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:175 (message):
      
      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  ports/opencv4/portfile.cmake:115 (vcpkg_download_distfile)
  scripts/ports.cmake:90 (include)

I read this problem on the Internet and never found a solution.How can I solve this problem?
My English is very limited.But I can read the answers through translation software.Thank you for any help.

**Comment by dswcmp** [comment]
I'm running the command.\vcpkg.exe from powerShell

**Comment by cenit** [comment]
Maybe you had an internet connection problem.
Just retry, it might work now!

**Comment by dswcmp** [comment]
Thank you for your reply!
I'm sure it's not a connection problem, I mean I'm sure the network is open, but I'm not sure I have access to that server.But the resources that Darknet needs have already downloaded a lot.Found so far is only https://raw.githubusercontent.com/opencv/opencv_3rdparty/34e4206aef44d50e6bbcd0ab06354b52 unable to download, or other problems?This problem has been bothering me for 4 days, not just before I posted it. Before this, I found a lot of similar problems on Google, but my problem still hasn't been solved, so I'm asking for help here.

**Comment by dswcmp** [comment]
I have modified the host files added 199.232.68.133 raw.githubusercontent.com to solve the problem

**Comment by dswcmp** [comment]
And then...I should close this lssues, right?

**Comment by JackBoosY** [comment]
@dswcmp Yes.
