### ISSUE TITLE
[New Port Request] h5cpp

### ISSUE THREAD

**Issue by ArielxX** [microsoft/vcpkg#11744]
Library name: h5cpp

Library description: library to interact with h5 files

Source repository URL: https://github.com/steven-varga/h5cpp

Project homepage (if different from the source repository): http://h5cpp.org/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
Please reopen this issue and continue PR https://github.com/microsoft/vcpkg/pull/11746 If you wish to add this port in the future.
