### ISSUE TITLE
[New Port Request] learngl

### ISSUE THREAD

**Issue by mathsun** [microsoft/vcpkg#11748]
Library name:learngl

Library description:a course about opengl
Source repository URL:https://github.com/JoeyDeVries/LearnOpenGL
Project homepage (if different from the source repository):https://learnopengl.com/Getting-started/OpenGL
Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by mathsun** [comment]
this is a very good course for opengl-learners.

**Comment by ArielxX** [comment]
Edit title **<library name here>** = `learngl`
 ;)

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
