### ISSUE TITLE
Error: Building package json-c:arm-uwp failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by vivekbarkam** [Microsoft/vcpkg#1175]
Hi,
I am trying to build json-c for arm-uwp. But i'm not able to build it. I have tried building with different scripts in profile.cmake, but its not helpful. I am attaching supporting files.

Please help me...

![image](https://cloud.githubusercontent.com/assets/9570532/26492310/6e6fd818-4224-11e7-8a25-ba67fd36e1c2.png)

profle.cmake file:
[portfile.cmake.txt](https://github.com/Microsoft/vcpkg/files/1031599/portfile.cmake.txt)

error files:
[config-arm-uwp-rel-err.log.txt](https://github.com/Microsoft/vcpkg/files/1031602/config-arm-uwp-rel-err.log.txt)

**Comment by zabulus** [comment]
Does it build for x86,

**Comment by vivekbarkam** [comment]
No. I tried all architectures, its not building. It's failed to build with the same error for all architectures.

**Comment by codicodi** [comment]
I can see you are trying to create a new port.
Port template assumes the library has a CMake-based buildsystem. Looking at https://github.com/json-c/json-c I can tell CMake support was added after latest release. Try using current master: https://github.com/json-c/json-c/archive/e76ea3777260ddc9d19285460ad250ca6de17769.zip

**Comment by vivekbarkam** [comment]
Yes I am creating a new port for json-c. I have tried using master: https://github.com/json-c/json-c/archive/e76ea3777260ddc9d19285460ad250ca6de17769.zip, after your suggestion. But i found the following errors.

![image2](https://cloud.githubusercontent.com/assets/9570532/26507297/d00ac54c-4260-11e7-97e6-88215c2e36f2.png)

It creates json-c.dll but failing to create json-c.lib. But I need static json-c.lib.
I am attaching following files for reference.

[config-arm-uwp-dbg-out.log.txt](https://github.com/Microsoft/vcpkg/files/1032676/config-arm-uwp-dbg-out.log.txt)
[config-arm-uwp-dbg-err.log.txt](https://github.com/Microsoft/vcpkg/files/1032677/config-arm-uwp-dbg-err.log.txt)
[package-arm-uwp-dbg-out.log.txt](https://github.com/Microsoft/vcpkg/files/1032678/package-arm-uwp-dbg-out.log.txt)

**Comment by ras0219-msft** [comment]
Glad to see a new port :)

If the library only supports static builds, you can add this at the top of the portfile:
```cmake
if (VCPKG_LIBRARY_LINKAGE STREQUAL dynamic)
    message(STATUS "Warning: Dynamic building not supported. Building static.")
    set(VCPKG_LIBRARY_LINKAGE static)
endif()
```

You'll still need to address the license issue and probably also need to do
```cmake
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/include/json-c/autoconf-archive")
```

**Comment by vivekbarkam** [comment]
Thanks ras0219-msft. 

The above set of lines is creating json-c.lib fine. But in future, in order to support both static and dynamic libraries what could be the set of lines i can add in the portfile.
