### ISSUE TITLE
Cannot use vcpkg from vscode-cmake-tools

### ISSUE THREAD

**Issue by daef** [microsoft/vcpkg#11769]
After installing a port and setting CMAKE_TOOLCHAIN_FILE to ...\vcpkg\scripts\buildsystems\vcpkg.cmake vscode-cmake-tools is still not able to resolve correctly.

This seems related: https://github.com/microsoft/vscode-cmake-tools/issues/443

**Environment**
- OS: Windows 10
- Compiler: Clang 10

**Expected behavior**
cmake finds the port and links against it

**Failure logs** 

     [cmake] CMake Error at C:/ad/vcpkg/scripts/buildsystems/vcpkg.cmake:266 (_find_package):
     [cmake]   Could not find a package configuration file provided by "pthreads" with any
     [cmake]   of the following names:
         ...

**Comment by NancyLi1013** [comment]
Hi @daef 
Thanks for posting this issue.
Since currently vscode isn't supported by vcpkg. Please follow the progress of this issue #10217.

**Comment by matt-42** [comment]
CMAKE_TOOLCHAIN_FILE still does not work, but this is working in my setup:
"CMAKE_PREFIX_PATH": "path_to_vcpkg/installed/x86-windows"
