### ISSUE TITLE
Error when using lconvert tool from qt5 package

### ISSUE THREAD

**Issue by drdanz** [Microsoft/vcpkg#1176]
When I run C:/vcpkg/installed/x64-windows/tools/qt5/lconvert.exe from the qt5 package I get this error:

~~~
C:/vcpkg/installed/x64-windows/tools/qt5/lconvert.exe: error while loading shared libraries: api-ms-win-crt-locale-l1-1-0.dll: cannot open shared object file: No such file or directory
~~~

Am I missing something? I have all C++ redistributable packages, etc installed...

**Comment by bagong** [comment]
Adding the bin folder to the environment search path allows it to run for me:

set PATH=C:\vcpkg\installed\x64-windows\bin;%PATH%

Best
.r.

**Comment by drdanz** [comment]
This worked, thanks! Closing this issue
