### ISSUE TITLE
How to install pcl older commit

### ISSUE THREAD

**Issue by yes89929** [microsoft/vcpkg#11768]
I`m trying to install pcl.

1. current commit of pcl has a issue about compatability with vtk 9.0.0. #11601 
So I changed port of vtk, boost, and pcl from latest to before current issue by using "git checkout"

vtk:
```
commit f2e9ef7f259843e116453bbabb7bcc2b13246f13
Author: Lars <larshg@gmail.com>
Date:   Tue Apr 21 22:14:22 2020 +0200

    [VTK] Check if VTKTarget files exist (#10925)
```

boost:

```
commit c50852aba0aa8df22e17133352edb432a9fc1e56
Author: yurybura <yurybura@gmail.com>
Date:   Fri Jan 17 02:10:15 2020 +0300

    [boost] Update to 1.72.0 (#9317)
```

pcl:
```
commit a9640a54224d968a583292bc3b1e81731eefc73c
Author: Jack<C2><B7>Boos<C2><B7>Yu <47264268+JackBoosY@users.noreply.github.com>
Date:   Fri May 1 00:49:07 2020 +0800

    [pcl] Fix link to libpng (#11047)
```

2. `vcpkg install pcl` still try to install boost 1.7.3

3. `vcpkg install boost` 
```
Computing installation plan...
Error: Cannot find definition for package `boost-disjoint-sets`.
```

Are there any solutions?

**Comment by timautry** [comment]
@yes89929 Thank you for posting this issue.
See https://github.com/microsoft/vcpkg/pull/11758 but it is an enhancement in the works.
In the meantime I was given this example:
1. Use command .\vcpkg x-history qt5

2. Get the commit id of the version you need.

3. Use command git reset <commit id>

4. Rebuild qt5.

**Comment by PhoebeHui** [comment]
@timautry, thanks for the comments!

@yes89929, could you please try above solution, please reopen if it still be a problem for you.

**Comment by alimai** [comment]
I do a test with the zlib(The latest version of zlib in vcpkg is 1.2.11-6),
Vcpkg still build the latest version of module when I following the suggestion of @timautry timautry.
1. git reset 18b029a5e3997fa4fdc7d3d06d56568a1d6f74ad
2. .\vcpkg x-history zlib
             version          date    vcpkg commit
            1.2.11-5    2019-06-15    18b029a5e3997fa4fdc7d3d06d56568a1d6f74ad
            1.2.11-3    2018-08-30    ab54bfa0cc98b96a6cffe75e4045ccbd366dbe46
            1.2.11-2    2017-09-23    67e876c76555c466e4faf49d6cd80a88b835f972
            1.2.11-1    2017-09-09    26516fe485b0e9048dd4809256a7e4526957c6e9
              1.2.11    2017-01-17    0d50c6704ddc563f459b901297bbb909adaa6e51
              1.2.10    2017-01-04    6a220edfb8454a4fc1652f82f537518ac620033f
               1.2.8    2016-11-08    1808d461b0e8793445b87eb8ceed71d5ac7aca6e
[note: The current version should be 1.2.11-5 now.]
3. .\vcpkg zlib
Computing installation plan...
The following packages will be built and installed:
    zlib[core]:x64-windows
Downloading powershell-core...
Extracting powershell-core...
Starting package 1/1: zlib:x64-windows
Building package zlib[core]:x64-windows...
-- Downloading http://www.zlib.net/zlib-1.2.11.tar.gz...
-- Extracting source E:/vcpkg/downloads/zlib1211.tar.gz
-- Applying patch cmake_dont_build_more_than_needed.patch
-- Using source at E:/vcpkg/buildtrees/zlib/src/1.2.11-deec42f53b.clean
-- Configuring x64-windows
-- Building x64-windows-rel
-- Installing: E:/vcpkg/packages/zlib_x64-windows/share/zlib/copyright
-- Performing post-build validation
-- Performing post-build validation done
Installing package zlib[core]:x64-windows...
Installing package zlib[core]:x64-windows... done
4.  .\vcpkg list
zlib:x64-windows                                   1.2.11-6         A compression library

The installed version is still 1.2.11-6, is there any thing wrong?
