### ISSUE TITLE
cannot bootstrap with vc2015 toolchain

### ISSUE THREAD

**Issue by yamcenutzer** [microsoft/vcpkg#11773]
**Describe the bug**
bootstrap-vcpkg.bat fails when using vc2015 toolchain

**Environment**
- OS: Windows
- Compiler: vc2015

**To Reproduce**
1. ./bootstrap-vcpkg.bat
2. See excerpt from building below

**Expected behavior**
vcpk.exe is built, per default with Metrics disabled (not the other way around)
...
...
..\src\vcpkg\metrics.cpp(44): error C2127: 'write_byte': illegal initialization of 'constexpr' entity with a non-consta
nt expression [C:\robinmi\vcpkg.new\toolsrc\vcpkglib\vcpkglib.vcxproj]
  ..\src\vcpkg\metrics.cpp(44): note: failure was caused by evaluating a lambda expression
...
... 
bootstrap.ps1 : Building vcpkg.exe failed. Please ensure you have installed Visual Studio
with the Desktop C++ workload and the Windows SDK for Desktop C++.
At line:1 char:4
+ & {& 'C:\robinmi\vcpkg.new\scripts\bootstrap.ps1' }
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,bootstrap.ps1

**Additional context**
removing the constexpr (which clearly requires a newer compiler than vc14) helps

**Comment by BillyONeal** [comment]
This suggests that we need to add bootstrap with 2015 to our PR/CI system

**Comment by yamcenutzer** [comment]
yes, actually most if not all libraries managed by vcpkg go to a great deal of trouble in trying to support olde c++ standards (at least c++11), which the whole üpoint of real world, industrial SW. You simply can't always play around only with new toys, you have to earn money and support decent lifetimes.

What I'm trying to say: if the library manager as an actually non-critical tool prevents you from using a decent library for your mature (old) compiler, then the manger is kind of missing the point.

**Comment by sphoto** [comment]
Same problem (Windows 10, VC2015)

**Comment by luisgo007** [comment]
Same problem Windows 10, VC2015. Trying to install NEO.

**Comment by trietptm** [comment]
This problem still exists.

**Comment by luisgo007** [comment]
I solved. I omitted the declaration as a constant and compiled Ok-

**Comment by Qiu-Kejian** [comment]
try removing the keyword 'constexpr'.

**Comment by freddy77** [comment]
I also can confirm that removing `constexpr` from line 44 fix the issue. So

```cpp
        static const auto write_byte = [](std::string& res, std::uint8_t bits) {
            res.push_back(hex[(bits >> 4) & 0x0F]);
            res.push_back(hex[(bits >> 0) & 0x0F]);
        };
```

works.

**Comment by trietptm** [comment]
I checked yesterday and this problem was fixed.

**Comment by freddy77** [comment]
Yes, this was fixed by #11891. The bug can be closed

**Comment by LilyWangL** [comment]
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.

**Comment by cgolchert** [comment]
If it was fixed I probably shouldn't still be seeing it.

**Comment by freddy77** [comment]
> If it was fixed I probably shouldn't still be seeing it.

Either you didn't pick up the change or a newer commit broke the build again. Check it and open another bug in the later case.
