### ISSUE TITLE
vcpkg create fails with "CMake Error at scripts/ports.cmake:14"

### ISSUE THREAD

**Issue by sweemer** [microsoft/vcpkg#11784]
**Describe the bug**
After running `git pull` to revision `6ac6267f512dcec29171f4cbe62a040a974fde04`, `vcpkg create` fails with "CMake Error at scripts/ports.cmake:14". Issue observed on both Linux and Windows.

**Environment**
- OS: Ubuntu 18.04 LTS and Windows 10
- Compiler: g++ 8.4.0 and Visual Studio Pro 2019

**To Reproduce**
1. `$ git clone https://github.com/microsoft/vcpkg.git # current revision 6ac6267f512dcec29171f4cbe62a040a974fde04`
1. `$ ./bootstrap.sh # .\bootstrap.bat on Windows`
2. `$ ./vcpkg create zlib2 http://zlib.net/zlib-1.2.11.tar.gz zlib-1.2.11.zip # taken directly from https://vcpkg.readthedocs.io/en/latest/examples/packaging-zipfiles/`

**Expected behavior**
> This is the output I was seeing last week as of revision 01926a1eb1117052964959ef0d334812021a23fe
> 
> $ ./vcpkg create zlib2 http://zlib.net/zlib-1.2.11.tar.gz zlib-1.2.11.zip
> -- Downloading http://zlib.net/zlib-1.2.11.tar.gz...
> -- Generated portfile: /home/sweemer/test/vcpkg\ports\zlib2\portfile.cmake
> -- Generated CONTROL: /home/sweemer/test/vcpkg\ports\zlib2\CONTROL
> -- To launch an editor for these new files, run
> --     .\vcpkg edit zlib2

**Failure logs** 
> $ ./vcpkg create zlib2 http://zlib.net/zlib-1.2.11.tar.gz zlib-1.2.11.zip
> CMake Error at scripts/ports.cmake:14 (message):
>           Your vcpkg executable is outdated and is not compatible with the current CMake scripts.
>           Please re-build vcpkg by running bootstrap-vcpkg.

**Additional context**
This was working fine as of revision `01926a1eb1117052964959ef0d334812021a23fe` last week.

**Comment by JackBoosY** [comment]
Confirmed.
@dan-shaw Could you please take a look?

**Comment by BillyONeal** [comment]
oops, I probably broke this :/ Will take a look tomorrow when it isn't 2AM :)

**Comment by BillyONeal** [comment]
(The fix will be to audit all the places vcpkg.exe calls cmake bits and ensure it's passing in all the right paths)
