### ISSUE TITLE
Building package openssl-windows:x64-windows failed with: BUILD_FAILED while installing boost-python:x64-windows

### ISSUE THREAD

**Issue by rowlmars** [microsoft/vcpkg#11781]
Hi!  Please see below and attached for info.  Thank you.

**Describe the bug**

**Environment**
- OS: OS Name	Microsoft Windows 10 Enterprise
Version	10.0.17763 Build 17763

- Compiler: revision

**To Reproduce**
1. .vcpkg.exe install boost-python:x64-windows
2. See error
Repro code when

**Expected behavior**
I expected the package to install.

**Failure logs** 
-- Using source at C:/...
[build-x64-windows-rel-1-err.log](https://github.com/microsoft/vcpkg/files/4732882/build-x64-windows-rel-1-err.log)
[build-x64-windows-rel-1-out.log](https://github.com/microsoft/vcpkg/files/4732883/build-x64-windows-rel-1-out.log)

/vcpkg/buildtrees/openssl-windows/src/openssl-1-b1f8ae3e6c
-- Copying openssl release source files...
-- Copying openssl release source files... done
-- Configure x64-windows-rel
-- Configure x64-windows-rel done
-- Build x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: nmake -f makefile install_sw install_ssldirs
    Working Directory: C:/.../vcpkg/buildtrees/openssl-windows/x64-windows-rel
    Error code: 2
    See logs for more information:
      C:\...\vcpkg\buildtrees\openssl-windows\build-x64-windows-rel-1-out.log
      C:\...\vcpkg\buildtrees\openssl-windows\build-x64-windows-rel-1-err.log

Call Stack (most recent call first):
  ports/openssl-windows/portfile.cmake:94 (vcpkg_execute_required_process)
  scripts/ports.cmake:76 (include)

Error: Building package openssl-windows:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openssl-windows:x64-windows
  Vcpkg version: 2020.02.04-nohash

Additionally, attach any relevant sections from the log files above.

C:\...\vcpkg>.\vcpkg update
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.

**Additional context**
I ran vcpkg update before submitting the ticket
Note I anonymized the path in one of the attached logs and above

**Comment by PhoebeHui** [comment]
@rowlmars,  I tried build it locally, everything built successfully for me. from you log, it seems due to the environment issue.

Could you try ./vcpkg env --triplet x64-windows --debug command and attach the output here?

Failures:
cl : Command line error D8003 : missing source filename
'Datasets\\arielsmagicscript2\\vcpkg\\packages\\openssl-windows_x64-windows\""' is not recognized as an internal or external command,
operable program or batch file.
'Datasets\\arielsmagicscript2\\vcpkg\\packages\\openssl-windows_x64-windows\\lib\\engines-1_1\""' is not recognized as an internal or external command,
operable program or batch file.
NMAKE : fatal error U1077: 'cl' : return code '0x1'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.

**Comment by rowlmars** [comment]
C:\...\vcpkg>vcpkg env --triplet x64-windows --debug
[DEBUG] Using vcpkg-root: C:\...\vcpkg
[DEBUG] Using buildtrees-root: C:\...\vcpkg\buildtrees
[DEBUG] Using downloads-root: C:\...\vcpkg\downloads
[DEBUG] Using packages-root: C:\...\vcpkg\packages
[DEBUG] Using installed-root: C:\...\vcpkg\installed
[DEBUG] Using scripts-root: C:\...\vcpkg\scripts
[DEBUG] CreateProcessW("C:\...\vcpkg\downloads\tools\cmake-3.17.2-windows\cmake-3.17.2-win32-x86\bin\cmake.exe" --version)
[DEBUG] cmd_execute_and_stream_data() returned 0 after   287028 us
[DEBUG] CreateProcessW("C:\...\vcpkg\downloads\tools\cmake-3.17.2-windows\cmake-3.17.2-win32-x86\bin\cmake.exe"  -P "C:/…/vcpkg/buildtrees/0.vcpkg_tags.cmake")
[DEBUG] cmd_execute_and_stream_data() returned 0 after   139555 us
[DEBUG] CreateProcessW("C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -all -prerelease -legacy -products * -format xml)
[DEBUG] cmd_execute_and_stream_data() returned 0 after   153460 us
[DEBUG] CreateProcessW(cmd /c ""C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" -vcvars_ver=14.2 amd64   2>&1 <NUL" & echo cdARN4xjKueKScMy9C6H& set)
[DEBUG] cmd_execute_and_stream_data() returned 0 after  4817950 us
[DEBUG] CreateProcessW(cmd)
Microsoft Windows [Version 10.0.17763.1217]
(c) 2018 Microsoft Corporation. All rights reserved.

**Comment by rowlmars** [comment]
Thank you @PhoebeHui

**Comment by PhoebeHui** [comment]
@rowlmars, sorry for the late response, does this still be a problem for you?

**Comment by PhoebeHui** [comment]
Double confirmed with latest source, this issue still can't be reproed, please create a new issue with full failure logs if it occurs again.
