### ISSUE TITLE
[icu] Essential tools not provided

### ISSUE THREAD

**Issue by rleigh-codelibre** [microsoft/vcpkg#11782]
****

ICU is not just libraries.  It is also a number of executables which projects may depend upon, e.g. genrb, pkgdata etc.  Currently, the vcpkg port does not install these e.g. under *tools/icu*, but they are present in the build tree.

From `vcpkg\buildtrees\icu\x64-windows-rel\bin`:

```
buildtrees/icu/x64-windows-rel/bin/derb.exe
buildtrees/icu/x64-windows-rel/bin/genbrk.exe
buildtrees/icu/x64-windows-rel/bin/genccode.exe
buildtrees/icu/x64-windows-rel/bin/gencfu.exe
buildtrees/icu/x64-windows-rel/bin/gencmn.exe
buildtrees/icu/x64-windows-rel/bin/gencnval.exe
buildtrees/icu/x64-windows-rel/bin/gendict.exe
buildtrees/icu/x64-windows-rel/bin/gennorm2.exe
buildtrees/icu/x64-windows-rel/bin/genrb.exe
buildtrees/icu/x64-windows-rel/bin/gensprep.exe
buildtrees/icu/x64-windows-rel/bin/icupkg.exe
buildtrees/icu/x64-windows-rel/bin/makeconv.exe
buildtrees/icu/x64-windows-rel/bin/pkgdata.exe
buildtrees/icu/x64-windows-rel/bin/uconv.exe
```

Other ports, e.g. xerces-c require some of these in order to build with ICU support enabled.

**Proposed solution**

Please package up the ICU tools, perhaps as an optional [tools] feature.

/cc @JonLiu1993 @xuhongxu96 @codicodi who have previously worked on ICU.

**Comment by NancyLi1013** [comment]
Hi @rleigh-codelibre 
Thanks for posting this issue.
I submitted a PR to add these executables. Could you please help confirm if this can work for you?

**Comment by rleigh-codelibre** [comment]
@NancyLi1013 Absolutely, I'll build and test the PR this evening.  Many thanks for looking into this, it's really appreciated.
