### ISSUE TITLE
Failed to download libxml2 in vcpkg to install Point Cloud Library

### ISSUE THREAD

**Issue by khaoula-elh** [microsoft/vcpkg#11799]
**Describe the bug**
I'm trying to install point cloud library with vcpkg but I have a problem in downloading libxml2 and I don't know how to use a PROXY. Can you help me to resolve these problem ? I need it too match in my project of graduating.

**Environment**
- OS: [Windows]

1. ./vcpkg install pcl
2. See error
-- Downloading https://github.com/GNOME/libxml2/archive/v2.9.9.tar.gz...
-- Downloading https://github.com/GNOME/libxml2/archive/v2.9.9.tar.gz... Failed. Status: 4;"A requested feature, protocol or option was not found built-in in this libcurl due to a build-time decision."
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:175 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:132 (vcpkg_download_distfile)
  ports/libxml2/portfile.cmake:3 (vcpkg_from_github)
  scripts/ports.cmake:76 (include)

**Comment by khaoula-elh** [comment]
@JackBoosY

**Comment by JackBoosY** [comment]
@khaoula-elh Seems your network has problem, you can get it [here](https://github.com/microsoft/vcpkg/files/4743579/libxml2-2.9.9.tar.gz) and put it into _VCPKG_ROOT/downloads_, then rebuild libxml2.

**Comment by PhoebeHui** [comment]
You can aslo reference https://github.com/microsoft/vcpkg/issues/13348#issue-692784879 to set your environment.
