### ISSUE TITLE
[<GTK>] update to <3.24.20>

### ISSUE THREAD

**Issue by weirdworkshop** [microsoft/vcpkg#11797]
Library name: GTK

New version number: 3.24.20 

Other information that may be useful (release notes, etc...) current version is 3.22.19 when building a simple hello world program  using Win 32 CSS theme this gives a error 
"Gtk-WARNING **: 15:51:28.177: Theme parsing error: gtk-win32-base.css:1043:59: Junk at end of value for background-image"

This has been fixed in 3.24.20 https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/1118

**Comment by LilyWangL** [comment]
Due to the following error, the new version gtk need glib update to new version, waiting for issue #11477 merged. 
`vcpkg\buildtrees\gtk\src\gtk+-3-f8376c6326\gtk\gtkmountoperation.c(709): error C2065: 'G_ASK_PASSWORD_TCRYPT': undeclared identifier`
