### ISSUE TITLE
[New Port Request]  vJoy

### ISSUE THREAD

**Issue by Electric-Turtle** [microsoft/vcpkg#11798]
Library name: vJoy

Library description: A Windows library for creating a "fake" joystick that the Windows kernel thinks is a real device, but is actually being fed software-generated values that users can set through a software API (called the vJoy Interface API).

Source repository URL: https://github.com/njz3/vJoy.git

Project homepage (if different from the source repository): http://vjoystick.sourceforge.net/site/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

So this is a somewhat unique situation.  Porting the vJoy interface API to vcpkg doesn't sound too difficult (the github has a ready to go Visual Studio project).  However, without the corresponding device driver to create the emulated device in Windows, it's not particularly useful.  The source repo has the source code for both the interface API and the device driver.  But, from what I understand, vcpkg is not in the business of building and installing kernel-privileged drivers.  

So, if this project were to get ported, would it make sense for that port to download the prebuilt driver installer (available through a release on the project GitHub) and display a helpful message along the lines of "you need to install the driver that was just downloaded to (some path)"?

Is this approach even "allowed" for vcpkg ports?  I don't mind working on porting the interface API to vcpkg.  But if a PR for that port has no chance of getting merged due to the requirement to install an external driver, I am not going to waste my time.

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
