### ISSUE TITLE
idevicerestore issues with libmobiledevice code

### ISSUE THREAD

**Issue by yogendra123456** [microsoft/vcpkg#11790]
hi @nikias and @taanders and all,
kindly give me some instruction about libmobiledevice for windows i found some error which is given below, what happen on window iphone is not placed in restore mode. while iTunes update the firmware at this stage and also 3uTools what happen with libmobiledevice code, it happen with usbmuxd or others class which is not connect device to properly to window system...
kindly provide me some update.......
[Release.txt](https://github.com/microsoft/vcpkg/files/4734811/Release.txt)

thanks in advanced @nikias and @taanders and all,

**Comment by JackBoosY** [comment]
Hi @yogendra123456, thanks for reporting this issue!
Could you report this issue to upstream?

Thanks.

**Comment by JackBoosY** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.
