### ISSUE TITLE
CMake toolchain vcpkg.cmake decides wrong triplet for UWP

### ISSUE THREAD

**Issue by stoperro** [Microsoft/vcpkg#1179]
I'm trying to use vcpkg to build UWP app with CMake. My invocation:
`cmake .. -G "Visual Studio 15 2017 Win64" -DCMAKE_SYSTEM_NAME=WindowsStore -DCMAKE_SYSTEM_VERSION=10.0 -DCMAKE_TOOLCHAIN_FILE=F:\vcpkg\scripts\buildsystems\vcpkg.cmake`

It doesn't work well - my code can't find headers of packages I have installed. What can be checked by verifying values of CMake variables inside any user CMakeLists.txt script:
`message("WINDOWS_STORE ${WINDOWS_STORE} VCPKG_TARGET_TRIPLET ${VCPKG_TARGET_TRIPLET}")`
Resulting in:
`WINDOWS_STORE 1 VCPKG_TARGET_TRIPLET x64-windows`
This is wrong - it should be x64-uwp, not x64-windows.

This causes improper vcpkg\installed paths being provided to VC.

The problem is likely with check in vcpkg\scripts\buildsystems\vcpkg.cmake:
```
    if(WINDOWS_STORE OR WINDOWS_PHONE)
        set(_VCPKG_TARGET_TRIPLET_PLAT uwp)
    else()
        set(_VCPKG_TARGET_TRIPLET_PLAT windows)
    endif()
```
Probably at that time WINDOWS_STORE is not yet set. Changing it to:
```
    if(CMAKE_SYSTEM_NAME STREQUAL "WindowsStore")
        set(_VCPKG_TARGET_TRIPLET_PLAT uwp)
    elseif(CMAKE_SYSTEM_NAME STREQUAL "WindowsPhone")
        set(_VCPKG_TARGET_TRIPLET_PLAT uwp)
    else()
        set(_VCPKG_TARGET_TRIPLET_PLAT windows)
    endif()
```
Fixes it for me.

**Comment by ras0219-msft** [comment]
Thank you very much for reporting this!

I've reproed it locally and confirmed the fix you suggested; plus checked it in to master at 334a35e4.

Thanks again!
