### ISSUE TITLE
Surfacing Nuget.exe failure for better self-troubleshooting

### ISSUE THREAD

**Issue by seanyen** [microsoft/vcpkg#11804]
**Describe the bug**
In `vcpkg` install step, it will bootstrap a set of tools (for example, `nuget`, `7zip`, and `cmake`) And when there is something wrong, the error message is not obvious for users to understand what to do next. (In such case, `Nuget.exe` is hitting some problems.)

**Environment**
- OS: Windows 10
- Compiler: Visual Studio 2019

**To Reproduce**
1. Install Vcpkg and do `vcpkg install zlib` under an admin command prompt.
2. Then, install the vcpkg to another location and do `vcpkg install zlib` under a standard user this time.

```no-highlight
>vcpkg install zlib
Computing installation plan...
A suitable version of cmake was not found (required v3.14.0). Downloading portable cmake v3.14.0...
Extracting cmake...
A suitable version of 7zip was not found (required v18.1.0). Downloading portable 7zip v18.1.0...
Extracting 7zip...
A suitable version of nuget was not found (required v4.8.1). Downloading portable nuget v4.8.1...
Downloading nuget...
  https://dist.nuget.org/win-x86-commandline/v4.8.1/nuget.exe -> c:\vcpkg\downloads\nuget.exe
Value was null
```

The only message I can see is `Value was null`. However, the actual problem is that `Nuget.exe` reported the following error, and which took me a while debugging to actually understand what's going wrong.

```
Unable to obtain lock file access on 'C:\Users\xxx\AppData\Local\Temp\NuGetScratch\lock\8e3d5c2091865a3f6f7c9a61048400221e964e2d' for operations on 'C:\Users\tzuhs\AppData\Roaming\NuGet\NuGet.Config'. This may mean that a different user or administator is holding this lock and that this process does not have permission to access it. If no other process is currently performing an operation on this file it may mean that an earlier NuGet process crashed and left an inaccessible lock file, in this case removing the file 'C:\Users\xxx\AppData\Local\Temp\NuGetScratch\lock\8e3d5c2091865a3f6f7c9a61048400221e964e2d' will allow NuGet to continue.
```

**Expected behavior**
The actual error should be output or logged for users easier troubleshooting.

**Comment by ras0219** [comment]
This should be fixed by #14948 which will output the stdout+stderr instead of "Value was null"

**Comment by JackBoosY** [comment]
Hi @seanyen, is this issue resolved?

**Comment by JackBoosY** [comment]
Please reopen this issue if it's still exist.
