### ISSUE TITLE
[irrlicht] build failure

### ISSUE THREAD

**Issue by bugbuka** [microsoft/vcpkg#11806]
**Host Environment**
- OS: [macos]
- Compiler: revision

**To Reproduce**
`./vcpkg install irrlicht`

**Failure logs** 
Starting package 1/6: irrlicht:x64-osx
Building package irrlicht[core]:x64-osx...
-- Using cached /Users/tom/github-cpp/vcpkg/downloads/irrlicht-1.8.4.zip
-- Using source at /Users/tom/github-cpp/vcpkg/buildtrees/irrlicht/src/1.8.4-e1f2402469
-- Configuring x64-osx-dbg
-- Configuring x64-osx-rel
-- Building x64-osx-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: /Users/tom/github-cpp/vcpkg/downloads/tools/cmake-3.17.2-osx/cmake-3.17.2-Darwin-x86_64/CMake.app/Contents/bin/cmake --build . --config Debug --target install -- -v
    Working Directory: /Users/tom/github-cpp/vcpkg/buildtrees/irrlicht/x64-osx-dbg
    See logs for more information:
      /Users/tom/github-cpp/vcpkg/buildtrees/irrlicht/install-x64-osx-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/irrlicht/portfile.cmake:40 (vcpkg_install_cmake)
  scripts/ports.cmake:76 (include)

Error: Building package irrlicht:x64-osx failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: irrlicht:x64-osx
  Vcpkg version: 2020.02.04-unknownhash

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by timautry** [comment]
@bugbuka Thank you for posting this issue.
Please attach/upload `/Users/tom/github-cpp/vcpkg/buildtrees/irrlicht/install-x64-osx-dbg-out.log` to this issue so someone will be able to assist in this matter.

**Comment by bugbuka** [comment]
Kais-MacBook-Pro:minetest tom$ vcpkg install irrlicht --triplet x64-osx
Computing installation plan...
The following packages will be built and installed:
    irrlicht[core]:x64-osx
Starting package 1/1: irrlicht:x64-osx
Building package irrlicht[core]:x64-osx...
-- Using cached /Users/tom/minetest/vcpkg/downloads/irrlicht-1.8.4.zip
-- Using source at /Users/tom/minetest/vcpkg/buildtrees/irrlicht/src/1.8.4-e1f2402469
-- Configuring x64-osx-dbg
-- Configuring x64-osx-rel
-- Building x64-osx-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: /Users/tom/minetest/vcpkg/downloads/tools/cmake-3.14.0-osx/cmake-3.14.0-Darwin-x86_64/CMake.app/Contents/bin/cmake --build . --config Debug --target install -- -v
    Working Directory: /Users/tom/minetest/vcpkg/buildtrees/irrlicht/x64-osx-dbg
    See logs for more information:
      /Users/tom/minetest/vcpkg/buildtrees/irrlicht/install-x64-osx-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/irrlicht/portfile.cmake:40 (vcpkg_install_cmake)
  scripts/ports.cmake:90 (include)


Error: Building package irrlicht:x64-osx failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: irrlicht:x64-osx
  Vcpkg version: 2020.02.04-unknownhash

Additionally, attach any relevant sections from the log files above.

[install-x64-osx-dbg-out.log](https://github.com/microsoft/vcpkg/files/4741622/install-x64-osx-dbg-out.log)

**Comment by timautry** [comment]
@bugbuka  when I click on the install-x64-osx-dbg-out.log link it is giving me a html 404 not found.

**Comment by PhoebeHui** [comment]
@bugbuka, it looks irrlicht:x64-osx doesn't support in vcpkg now, I tried build it on macos locally, it contains a lot of errors which looks source issue. Please report an issue to Upstream.

I will add 'Supports' and failures message to irrlicht.

**Comment by DailyShana** [comment]
the source code of irrlicht use an xcode project with some osx-specific code for building on osx.
