### ISSUE TITLE
How to provide library specific config options?

### ISSUE THREAD

**Issue by hkaiser** [Microsoft/vcpkg#1180]
Is it possible to pass specific (custom) configuration options while installing a particular library? What I had in mind for instance for HPX would be:

    vcpkg install hpx:x64-windows --config-hpx -DHPX_WITH_NETWORKING=OFF

or similar, where everything after the `--config-xxx` option would be passed to the cmake invocation for the library `xxx`.

**Comment by hkaiser** [comment]
Would there be any interest in me exploring this?

**Comment by ras0219-msft** [comment]
Sorry for the delay ;) We've been working on this kind of issue for a while in #249 and have a proposal I've just published as PR #1205.

Please take a look at that proposal and make sure it can properly handle this scenario -- I think it can, but I'd love to have a second opinion!

**Comment by hkaiser** [comment]
@ras0219-msft The proposal looks good to me. That should cover our use cases. Thanks!

**Comment by zbahhah** [comment]
@hkaiser Could you please help us in installing hpx under non-windows os via vcpkg, we face this issue: https://github.com/Microsoft/vcpkg/issues/3307 in macOS & ubuntu linux?

**Comment by hkaiser** [comment]
@zbahhah we will try to have a look, thanks!

**Comment by JackBoosY** [comment]
Hi @hkaiser , thanks for reporting this issue!
Please open a new issue if this is still a problem for you.
Thx.
