### ISSUE TITLE
"#include errors detected"

### ISSUE THREAD

**Issue by GrayHub-737** [microsoft/vcpkg#11816]
# <h1> My visual studio's unusual behavior

**Issue**
I recently created a C++ project which initially worked very well. Rather today I encountered an "**_#include errors detected. Please update your includePath. Squiggles are disabled for this translation unit (C:\Users\me\program.cpp)._**" error in my problems window.

**Environment**
- OS: [Windows]
- Compiler: [gcc 8.1]

**Additional context**
- But if I attempt to compile and run the program, it runs successfully. 
- Also when I set "C_Cpp.errorSquiggles": "Disabled", the problem suddenly disappears.

I need help! Any suggestions??

**Comment by NancyLi1013** [comment]
Hi @GrayHub-737 
Thanks for posting this issue.
Seems you used Visual Studio Code to build the project. If so, Visual Studio Code is currently not supported in vcpkg.

Please refer to [this ](https://github.com/microsoft/vscode-cpptools/issues/4718). Hope this can help you some.

**Comment by GrayHub-737** [comment]
I appreciate your comment @NancyLi1013 , my problem is solved

**Comment by NancyLi1013** [comment]
Hi @GrayHub-737 
In my opinion, this is not vcpkg issue. Please pay attention to the progress of issue [here](https://github.com/microsoft/vscode-cpptools/issues/4718). So I'm closing this issue for now.
