### ISSUE TITLE
Vcpkg has issues to run when %USERNAME% contains whitespace characters

### ISSUE THREAD

**Issue by DavidObando** [microsoft/vcpkg#1181]
The machine setup: I'm using Windows 10 build 14393.1198. I cloned the repo and ran the bootstrap batch script.

The steps to reproduce: I run 'vcpkg list'

The outcome you expected: The operation should succeed.

The actual outcome: I get an error message window complaining it cannot find a path. The path is incomplete. In my case, it complains it cannot find "C:\Users\David" when my user path is "C:\Users\David Obando"

Result:
```
PS C:\GitHub\Microsoft\vcpkg> .\vcpkg.exe list
No packages are installed. Did you mean `search`?
The system cannot find the file C:\Users\David
```
<img width="419" alt="message" src="https://cloud.githubusercontent.com/assets/950290/26531922/1ab8c0d2-43a9-11e7-8b72-f95d50f0fc20.png">

**Comment by bagong** [comment]
Cmake has this very problem! It's been with them for years...

**Comment by LilyWangL** [comment]
This issue hasn’t been updated in a year, if it is still an issue, please reopen.
