### ISSUE TITLE
[vcpkg-docs] Update or create example that uses `vcpkg_from_github`

### ISSUE THREAD

**Issue by ras0219-msft** [microsoft/vcpkg#1182]
From https://github.com/Microsoft/vcpkg/pull/1111#issuecomment-302231394
>Also would be nice to have basic step by step guide for creating port based on [cpprestsdk](https://github.com/Microsoft/vcpkg/blob/master/ports/cpprestsdk/portfile.cmake) library for example. ZLib example doesn't use `vcpkg_from_github` and `vcpkg_fixup_cmake_targets()`

**Comment by PhoebeHui** [comment]
Docs for vcpkg_from_github has added to vcpkg, see [vcpkg_from_github.md](https://github.com/vpaladino778/vcpkg/blob/e2df00a48f31490e321daaebccae72a5df7e3f4a/docs/maintainers/vcpkg_from_github.md)
