### ISSUE TITLE
[abseil] Enable building abseil as a shared library

### ISSUE THREAD

**Issue by FabienPean** [microsoft/vcpkg#11820]
Currently, abseil is only built as a static library with vcpkg, see abseil [portfile](https://github.com/microsoft/vcpkg/blob/cb8a9fe7157f8ad2423742f893955ed9ced05910/ports/abseil/portfile.cmake#L1)

However, the library can now be built as a shared library, see [AbseilConfigureCopts](https://github.com/abseil/abseil-cpp/blob/567bee2f7393fca6ca737ecf061bd9f97302e346/absl/copts/AbseilConfigureCopts.cmake#L8)

The portfile for abseil should be updated to reflect this new possibility.

**Comment by JackBoosY** [comment]
Since my PR #11827 incorrectly fixed this issue, I reopened this PR and waited for the upstream to fix it.

**Comment by JackBoosY** [comment]
Now this issue should be fixed, please reopen this issue if it still bother you.

Thanks.
