### ISSUE TITLE
FFMpeg built but cannot link with PyBind11

### ISSUE THREAD

**Issue by kestrelm** [microsoft/vcpkg#11828]
**Host Environment**
- OS: Ubuntu 18.04 LTS in WSL ( Windows 10 )
- Compiler: revision

**To Reproduce**
I managed to install FFMpeg  successfully with vcpkg. However, when I try to link my C++ to Python3.7 wrapper shared library using Pybind11 to it, the linker fails with the error:
" can not be used when making a shared object; recompile with -fPIC" for the libraries in FFMpeg.

This builds on Windows 10 but fails on Linux,.

Any ideas how I should resolve it? How do I install FFMpeg with vcpkg using the fPIC option?

Thanks

**Comment by kestrelm** [comment]
I googled online and am wondering if this has anything to do with "enabled-shared" or force the -fPIC flag through on Linux. Is this possible? Thanks!

**Comment by PhoebeHui** [comment]
@kestrelm, building ports on linux default is static libraries.

Try to build with dynamic libraries, see
https://github.com/microsoft/vcpkg/blob/a5a244f5bdc390fc1c3d42e126e0bfd80541f060/docs/examples/overlay-triplets-linux-dynamic.md#building-dynamic-libraries-on-linux

**Comment by PhoebeHui** [comment]
@kestrelm, reopen this issue if it still bother you.
