### ISSUE TITLE
macOS 10.15.2 boostrap fails with gcc 9.3.0 and clang

### ISSUE THREAD

**Issue by lkleen** [microsoft/vcpkg#11834]
running the ./bootstrap-vcpkg.sh script fails with 

> -- The CXX compiler identification is GNU 9.3.0
> -- Checking whether CXX compiler has -isysroot
> -- Checking whether CXX compiler has -isysroot - yes
> -- Checking whether CXX compiler supports OSX deployment target flag
> -- Checking whether CXX compiler supports OSX deployment target flag - yes
> -- Check for working CXX compiler: /usr/local/bin/g++-9
> -- Check for working CXX compiler: /usr/local/bin/g++-9 - works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Detecting the C++ standard library
> -- Detecting the C++ standard library - libstdc++
> -- Detecting how to use the C++ filesystem library
> -- Detecting how to use the C++ filesystem library - <filesystem>
> -- Looking for C++ include pthread.h
> -- Looking for C++ include pthread.h - found
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
> -- Found Threads: TRUE  
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /Volumes/external1/git/cpprestsdk/vcpkg/toolsrc/build.rel
> [0/2] Re-checking globbed directories...
> [1/76] Building CXX object CMakeFiles/vcpkg.dir/src/vcpkg.cpp.o
> FAILED: CMakeFiles/vcpkg.dir/src/vcpkg.cpp.o 
> /usr/local/bin/g++-9  -DVCPKG_DISABLE_METRICS=0 -DVCPKG_USE_STD_FILESYSTEM=1 -I../include -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk   -std=c++17 -MD -MT CMakeFiles/vcpkg.dir/src/vcpkg.cpp.o -MF CMakeFiles/vcpkg.dir/src/vcpkg.cpp.o.d -o CMakeFiles/vcpkg.dir/src/vcpkg.cpp.o -c ../src/vcpkg.cpp
> In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/wchar.h:90,
>                  from /usr/local/Cellar/gcc/9.3.0_1/include/c++/9.3.0/cwchar:44,
>                  from /usr/local/Cellar/gcc/9.3.0_1/include/c++/9.3.0/bits/postypes.h:40,
>                  from /usr/local/Cellar/gcc/9.3.0_1/include/c++/9.3.0/bits/char_traits.h:40,
>                  from /usr/local/Cellar/gcc/9.3.0_1/include/c++/9.3.0/string:40,
>                  from ../include/vcpkg/base/cstringview.h:4,
>                  from ../include/vcpkg/base/chrono.h:3,
>                  from ../src/vcpkg.cpp:5:
> /usr/local/Cellar/gcc/9.3.0_1/lib/gcc/9/gcc/x86_64-apple-darwin19/9.3.0/include-fixed/stdio.h:219:10: fatal error: _ctermid.h: No such file or directory
>   219 | #include <_ctermid.h>
>       |          ^~~~~~~~~~~~
> compilation terminated.
> [2/76] Building CXX object CMakeFiles/vcpkglib.dir/src/vcpkg/base/files.cpp.o

using ./bootstrap-vcpkg.sh --allowAppleClang also fails
         

> -- The CXX compiler identification is AppleClang 10.0.0.10001145
> -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
> -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ - works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Detecting the C++ standard library
> -- Detecting the C++ standard library - libc++
> -- Detecting how to use the C++ filesystem library
> -- Detecting how to use the C++ filesystem library - <filesystem>
> -- Looking for C++ include pthread.h
> -- Looking for C++ include pthread.h - found
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
> -- Found Threads: TRUE  
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /Volumes/external1/git/cpprestsdk/vcpkg/toolsrc/build.rel
> [0/2] Re-checking globbed directories...
> [1/76] Building CXX object CMakeFiles/vcpkg.dir/src/vcpkg.cpp.o
> FAILED: CMakeFiles/vcpkg.dir/src/vcpkg.cpp.o 
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++  -DVCPKG_DISABLE_METRICS=0 -DVCPKG_USE_STD_FILESYSTEM=1 -I../include -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk   -std=c++17 -MD -MT CMakeFiles/vcpkg.dir/src/vcpkg.cpp.o -MF CMakeFiles/vcpkg.dir/src/vcpkg.cpp.o.d -o CMakeFiles/vcpkg.dir/src/vcpkg.cpp.o -c ../src/vcpkg.cpp
> In file included from ../src/vcpkg.cpp:6:
> ../include/vcpkg/base/files.h:7:10: fatal error: 'filesystem' file not found
> #include <filesystem>
>          ^~~~~~~~~~~~
> 1 error generated.
> [2/76] Building CXX object CMakeFiles/vcpkglib.dir/src/vcpkg/base/enums.cpp.o

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Due to I have no MAC machine with gcc9, could you try to make soft link link `xcode/include` to `/usr/local/include`? This may solve the error `/usr/local/Cellar/gcc/9.3.0_1/lib/gcc/9/gcc/x86_64-apple-darwin19/9.3.0/include-fixed/stdio.h:219:10: fatal error: _ctermid.h: No such file or directory`.
@dan-shaw @BillyONeal Could you help take a look this issue?

**Comment by lkleen** [comment]
I'm not sure where to create the soft link. /Applications/Xcode9.1.app/Contents/Developer/Library/Xcode ?

**Comment by BillyONeal** [comment]
@lkleen I just got my hands on a MacOS machine to try to investigate this but I'm new to that platform and don't know how you get gcc-9 on that platform. When I do a bootstrap it wants to use AppleClang 11 :)

**Comment by BillyONeal** [comment]
Closing this due to more than 30 days with no response. Please feel free to open another issue (or reopen this one if possible) at such time you can point out how we can repro the problem. Thanks!
