### ISSUE TITLE
[vcpkg-docs] Add docs for `vcpkg_fixup_cmake_targets`

### ISSUE THREAD

**Issue by ras0219-msft** [microsoft/vcpkg#1183]
From https://github.com/Microsoft/vcpkg/pull/1111#issuecomment-302231394

**Comment by PhoebeHui** [comment]
Docs for `vcpkg_fixup_cmake_targets` has been added to VCPKG, see [vcpkg_fixup_cmake_targets](https://github.com/vpaladino778/vcpkg/blob/e2df00a48f31490e321daaebccae72a5df7e3f4a/docs/maintainers/cmake_fixup_cmake_targets.md#vcpkg_fixup_cmake_targets)
