### ISSUE TITLE
.\vcpkg install darknet[full] build failure

### ISSUE THREAD

**Issue by aldrichg9** [microsoft/vcpkg#11838]
**Host Environment**
- OS: [Windows 10-64bit]
- Compiler: not applicable

**To Reproduce**
PS G:\yolov4\vcpkg> .\vcpkg install darknet[full]
Computing installation plan...
The following packages will be built and installed:
  * cudnn[core]:x86-windows
    darknet[core,cuda,cudnn,full,opencv-cuda,weights,weights-train]:x86-windows
  * ffmpeg[avresample,core]:x86-windows
  * hdf5[core,szip,zlib]:x86-windows
  * libjpeg-turbo[core]:x86-windows
  * liblzma[core]:x86-windows
  * libpng[core]:x86-windows
  * libwebp[core,nearlossless,simd,unicode]:x86-windows
  * opencv[core,cuda,dnn,ffmpeg,jpeg,opengl,png,tiff,webp]:x86-windows
  * opencv4[contrib,core,cuda,dnn,ffmpeg,jpeg,opengl,png,tiff,webp]:x86-windows
  * protobuf[core]:x86-windows
  * pthreads[core]:x86-windows
  * stb[core]:x86-windows
  * szip[core]:x86-windows
  * tiff[core]:x86-windows
  * zlib[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/16: cudnn:x86-windows
Building package cudnn[core]:x86-windows...
CMake Error at ports/cudnn/portfile.cmake:8 (message):
  This port is only for x64 architectures
Call Stack (most recent call first):
  scripts/ports.cmake:76 (include)

Error: Building package cudnn:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: cudnn:x86-windows
  Vcpkg version: 2020.02.04-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by timautry** [comment]
CMake Error at ports/cudnn/portfile.cmake:8 (message):
**This port is only for x64 architectures**

Try: **`.\vcpkg install darknet[full]:x64-windows`** -or-

**`.\vcpkg install darknet[full] --triplet x64-windows`** -or-

populate the VCPKG_DEFAULT_TRIPLET environment variable 
**`set VCPKG_DEFAULT_TRIPLET=x64-windows`** then
**`.\vcpkg install darknet[full]`**

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.

**Comment by mickkn** [comment]
C:\vcpkg>set VCPKG_DEFAULT_TRIPLET=x64-windows

C:\vcpkg>vcpkg install darknet[full]
Computing installation plan...
The following packages will be rebuilt:
  * opencv4[contrib,core,cuda,dnn,ffmpeg,jpeg,opengl,png,tiff,webp]:x64-windows
The following packages will be built and installed:
    darknet[core,cuda,cudnn,full,opencv-cuda,weights,weights-train]:x64-windows
  * opencv[core,cuda,dnn,ffmpeg,jpeg,opengl,png,tiff,webp]:x64-windows
  * stb[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
If you are sure you want to rebuild the above packages, run the command with the --recurse option

C:\vcpkg>vcpkg install darknet[full] --recurse
Computing installation plan...
The following packages will be rebuilt:
  * opencv4[contrib,core,cuda,dnn,ffmpeg,jpeg,opengl,png,tiff,webp]:x64-windows
The following packages will be built and installed:
    darknet[core,cuda,cudnn,full,opencv-cuda,weights,weights-train]:x64-windows
  * opencv[core,cuda,dnn,ffmpeg,jpeg,opengl,png,tiff,webp]:x64-windows
  * stb[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/5: opencv4:x64-windows
Removing package opencv4:x64-windows...
Removing package opencv4:x64-windows... done
Elapsed time for package opencv4:x64-windows: 160 ms
Starting package 2/5: opencv4:x64-windows
Building package opencv4[contrib,core,cuda,dnn,ffmpeg,jpeg,opengl,png,tiff,webp]:x64-windows...
-- Using cached C:/vcpkg/downloads/opencv-opencv-4.1.1.tar.gz
-- Using source at C:/vcpkg/buildtrees/opencv4/src/4.1.1-fb9e10326a
-- Using cached C:/vcpkg/downloads/opencv-cache/tiny_dnn/adb1c512e09ca2c7a6faef36f9c53e59-v1.0.0a3.tar.gz
-- Using cached C:/vcpkg/downloads/opencv-cache/nvidia_optical_flow/ca5acedee6cb45d0ec610a6732de5c15-79c6cee80a2df9a196f20afd6b598a9810964c32.zip
-- Using cached C:/vcpkg/downloads/opencv-opencv_contrib-4.1.1.tar.gz
-- Using source at C:/vcpkg/buildtrees/opencv4/src/4.1.1-521dd00bd2
-- Using cached C:/vcpkg/downloads/opencv-cache/xfeatures2d/boostdesc/0ea90e7a8f3f7876d450e4149c97c74f-boostdesc_bgm.i
-- Using cached C:/vcpkg/downloads/opencv-cache/xfeatures2d/boostdesc/232c966b13651bd0e46a1497b0852191-boostdesc_bgm_bi.i
-- Using cached C:/vcpkg/downloads/opencv-cache/xfeatures2d/boostdesc/324426a24fa56ad9c5b8e3e0b3e5303e-boostdesc_bgm_hd.i
-- Using cached C:/vcpkg/downloads/opencv-cache/xfeatures2d/boostdesc/202e1b3e9fec871b04da31f7f016679f-boostdesc_binboost_064.i
-- Using cached C:/vcpkg/downloads/opencv-cache/xfeatures2d/boostdesc/98ea99d399965c03d555cef3ea502a0b-boostdesc_binboost_128.i
-- Using cached C:/vcpkg/downloads/opencv-cache/xfeatures2d/boostdesc/e6dcfa9f647779eb1ce446a8d759b6ea-boostdesc_binboost_256.i
-- Using cached C:/vcpkg/downloads/opencv-cache/xfeatures2d/boostdesc/0ae0675534aa318d9668f2a179c2a052-boostdesc_lbgm.i
-- Using cached C:/vcpkg/downloads/opencv-cache/xfeatures2d/vgg/e8d0dcd54d1bcfdc29203d011a797179-vgg_generated_48.i
-- Using cached C:/vcpkg/downloads/opencv-cache/xfeatures2d/vgg/7126a5d9a8884ebca5aea5d63d677225-vgg_generated_64.i
-- Using cached C:/vcpkg/downloads/opencv-cache/xfeatures2d/vgg/7cd47228edec52b6d82f46511af325c5-vgg_generated_80.i
-- Using cached C:/vcpkg/downloads/opencv-cache/xfeatures2d/vgg/151805e03568c9f490a5e3a872777b75-vgg_generated_120.i
-- Using cached C:/vcpkg/downloads/opencv-cache/data/7505c44ca4eb54b4ab1e4777cb96ac05-face_landmark_model.dat
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: ninja -v
    Working Directory: C:/vcpkg/buildtrees/opencv4/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\vcpkg\buildtrees\opencv4\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:299 (vcpkg_execute_required_process)
  ports/opencv4/portfile.cmake:262 (vcpkg_configure_cmake)
  scripts/ports.cmake:76 (include)


Error: Building package opencv4:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: opencv4:x64-windows
  Vcpkg version: 2020.02.04-nohash
