### ISSUE TITLE
expat:x64-uwp

### ISSUE THREAD

**Issue by jonverrier** [microsoft/vcpkg#11840]
Doesn't build - expat does not currently support UWP. 

The vcpkg documentation suggested to log here, so I am.

**Comment by NancyLi1013** [comment]
Hi @jonverrier 
Thanks for posting this issue.
I have submitted a PR #9146 to add the support uwp for `expat`.

**Comment by NancyLi1013** [comment]
@jonverrier 
Now `expat `has supported uwp. 
Please update vcpkg to the latest version and rebuild it.
