### ISSUE TITLE
[vcpkg-docs] Add Policy document for maintainers

### ISSUE THREAD

**Issue by ras0219-msft** [microsoft/vcpkg#1184]
From https://github.com/Microsoft/vcpkg/pull/1111#issuecomment-302555645
> - For contributors new to package managers, it would be nice to have a document on general packaging philosophy, covering issues like build reproducibility or why libraries shouldn't bring their own dependencies.

Additional contents:
- Guidelines for closed-source libraries as well; see https://github.com/Microsoft/vcpkg/issues/1108
- Naming collision avoidance and resolution; see https://github.com/Microsoft/vcpkg/pull/1009

**Comment by LilyWangL** [comment]
This issue has been fixed. So I am closing this issue for now.
