### ISSUE TITLE
[boost-fiber:x64-windows] build failure

### ISSUE THREAD

**Issue by sinozope** [microsoft/vcpkg#11847]
D:\opt\vcpkg>vcpkg install boost-fiber:x64-windows
Computing installation plan...
The following packages will be built and installed:
    boost-fiber[core]:x64-windows
Starting package 1/1: boost-fiber:x64-windows
Building package boost-fiber[core]:x64-windows...
-- Using cached D:/opt/vcpkg/downloads/boostorg-fiber-boost-1.73.0.tar.gz
-- Using source at D:/opt/vcpkg/buildtrees/boost-fiber/src/ost-1.73.0-19cdf62e42
-- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: D:/opt/vcpkg/installed/x64-windows/tools/boost-build/b2.exe --stagedir=D:/opt/vcpkg/buildtrees/boost-fiber/x64-windows-rel/stage --build-dir=D:/opt/vcpkg/buildtrees/boost-fiber/x64-windows-rel --user-config=D:/opt/vcpkg/buildtrees/boost-fiber/x64-windows-rel/user-config.jam -j8 --debug-configuration --debug-building --debug-generators --disable-icu --ignore-site-config --hash -q -sZLIB_INCLUDE=D:/opt/vcpkg/installed/x64-windows/include -sBZIP2_INCLUDE=D:/opt/vcpkg/installed/x64-windows/include -sLZMA_INCLUDE=D:/opt/vcpkg/installed/x64-windows/include -sZSTD_INCLUDE=D:/opt/vcpkg/installed/x64-windows/include threading=multi threadapi=win32 runtime-link=shared link=shared address-model=64 architecture=x86 toolset=msvc -sZLIB_BINARY=zlib -sZLIB_LIBPATH=D:/opt/vcpkg/installed/x64-windows/lib -sBZIP2_BINARY=bz2 -sBZIP2_LIBPATH=D:/opt/vcpkg/installed/x64-windows/lib -sLZMA_BINARY=lzma -sLZMA_LIBPATH=D:/opt/vcpkg/installed/x64-windows/lib -sZSTD_BINARY=zstd -sZSTD_LIBPATH=D:/opt/vcpkg/installed/x64-windows/lib variant=release debug-symbols=on
    Working Directory: D:/opt/vcpkg/buildtrees/boost-fiber/src/ost-1.73.0-19cdf62e42/build
    Error code: 1
    See logs for more information:
      D:\opt\vcpkg\buildtrees\boost-fiber\build-x64-windows-rel-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/boost-build/boost-modular-build.cmake:297 (vcpkg_execute_required_process)
  ports/boost-fiber/portfile.cmake:17 (boost_modular_build)
  scripts/ports.cmake:76 (include)

Error: Building package boost-fiber:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-fiber:x64-windows
  Vcpkg version: 2020.02.04-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by PhoebeHui** [comment]
@sinozope, could you please attach failure log: D:\opt\vcpkg\buildtrees\boost-fiber\build-x64-windows-rel-out.log?

**Comment by PhoebeHui** [comment]
@tekert, 

1. From the failure message in CMakeOutput.log, it seems the compiler couldn't be found, could you double check if the compiler setting up correctly in your machine.

Failures:
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_CXX_COMPILER could be found.
  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.

2. The below failure should be a bug in [boost-modular-build.cmake](
https://github.com/microsoft/vcpkg/blob/cb8a9fe7157f8ad2423742f893955ed9ced05910/ports/boost-modular-build-helper/boost-modular-build.cmake#L34), I will summit a PR to fix this issue,
```
 'CMake Error at installed/x64-linux/share/boost-build/boost-modular-build.cmake:34 (message):
The x86 boost-build tools must be installed to build for non-x86/x64
platforms. Please run vcpkg install boost-build:x86-windows.'
```

**Comment by tekert** [comment]
I was debuggin this problem yesterday, GXX seems to be correctly detected by cmake now, so i tried restarting from scratch deleting everyting and now i get this error: Seems ..vcpkg/installed/x64-linux/share/boost-build/boost-modular-build.cmake  is never created now.

```
./vcpkg install boost-build --triplet x64-linux
Computing installation plan...
The following packages are already installed:
    boost-build[core]:x64-linux
Package boost-build:x64-linux is already installed

Total elapsed time: 10.9 us
```

./vcpkg install boost --triplet x64-linux
builds a couple of boost modules and then:
```
-- Using cached /mnt/e/Sources/cpp/vcpkg/downloads/boostorg-exception-boost-1.73.0.tar.gz
-- Using source at /mnt/e/Sources/cpp/vcpkg/buildtrees/boost-exception/src/ost-1.73.0-f8dcf39b91
CMake Error at ports/boost-exception/portfile.cmake:11 (include):
  include could not find load file:

    /mnt/e/Sources/cpp/vcpkg/installed/x64-linux/share/boost-build/boost-modular-build.cmake
Call Stack (most recent call first):
  scripts/ports.cmake:76 (include)
```
Only logs created now contain only this post contents.

**Comment by tekert** [comment]
Seems i fixed it, dunno what happened, but if i install the windows version of boost first and then linux, i got that error. Its too time consuming to test again, or maybe got a bad pull.

**Comment by PhoebeHui** [comment]
Do you install windows and linux version of boost on same machine? do you use wsl?

**Comment by tekert** [comment]
Yep, from the top of my mind this is what happened:
built vcpkg from windows, then used wsl2 to build it in linux
issued a comand from windows in vcpkg to install boost on windows, everyting went well.
issued a second command from windows to build the linux version of boost.
here i had a problem mid way, it needed to manually install missing tools (i think it was git).
after that something went bad, so i manually deleted the linux install dir and also the linux build tree, decided to go to wsl2 console and install it from linux, more problems.. decided to just issue a deletetion via vcpkg to boost-vcpkg-helpers, boost-build etc, i felt like something got corrupted and i couldnt figure what, so i had to delete the entire dir of vcpkg to solve it.
Sorry i could not figure what happened, but the first time i tried to install boost:x64-linux from windows is where something corrupted and i couldnt clean delete to start over.

**Comment by PhoebeHui** [comment]
Do you use same vcpkg instance for windows and Linux? if so, I think you need distinguish them, clone vcpkg source for linux and another vcpkg source for windows.

**Comment by PhoebeHui** [comment]
@sinozope, please reopen this issue and attach the failure log if it still be a problem for you.
