### ISSUE TITLE
[libepoxy] build failure

### ISSUE THREAD

**Issue by fishnet37222** [microsoft/vcpkg#11853]
**Host Environment**
- OS: Windows 10
- Compiler: 19.26.28806

**To Reproduce**
`./vcpkg install libepoxy`

**Failure logs** 
-- Acquiring MSYS Packages...
      0 [main] bash (11752) shared_info::initialize: size of shared memory region changed from 51128 to 40888
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: C:/vcpkg/downloads/tools/msys2/msys64/usr/bin/bash.exe --noprofile --norc -c "pacman -Sy --noconfirm --needed pkg-config"
    Working Directory: C:/vcpkg/downloads/tools/msys2
    Error code: Access violation
    See logs for more information:
      C:\vcpkg\buildtrees\libepoxy\msys-pacman-x64-windows-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_acquire_msys.cmake:108 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_configure_meson.cmake:106 (vcpkg_acquire_msys)
  ports/libepoxy/portfile.cmake:12 (vcpkg_configure_meson)
  scripts/ports.cmake:90 (include)

[msys-pacman-x64-windows-err.log](https://github.com/microsoft/vcpkg/files/4751766/msys-pacman-x64-windows-err.log)

**Additional context**
I've tried installing this on three different Windows 10 installations and it only worked on one of them.  The one where it worked was running as a guest under VMWare Workstation 15 running on Ubuntu 20.04.

**Comment by JackBoosY** [comment]
Hi @fishnet3722,  thanks for reporting this issue. 
Could you update vcpkg and try to rebuild this port? 

Thanks.

**Comment by fishnet37222** [comment]
I just tried and it works without any errors.

**Comment by JackBoosY** [comment]
@fishnet37222 Because this issue was fixed in #11810.
