### ISSUE TITLE
Trojan found (possible false positive)

### ISSUE THREAD

**Issue by Mayhem93** [microsoft/vcpkg#11854]
**Describe the bug**

![image](https://user-images.githubusercontent.com/705289/84158521-a175c680-aa74-11ea-9059-bd2e55f5f542.png)

Windows Security detected this script having a trojan-like behaviour, I looked into it but didn't have time to really go into the code and I thought I'd let you guys know.

**Environment**
- OS: windows 10, build 2004
- Compiler: not relevant

**To Reproduce**

The weird thing is that I was having this version of vpckg for a few weeks and never had any issues. The trojan warning appeared after I tried copying my workspace folder from a drive to the OS drive.

My local repo is @ b271aeffa25c53f3750f58ad6209f3fa7c528716

**Comment by Migamix** [comment]
same issue, windows 8.1, denied by windows defender

**Comment by PhoebeHui** [comment]
@BillyONeal, could you help have a look?

**Comment by BillyONeal** [comment]
This seems like something you'd have to report to Defender (via the Windows Feedback tool), or otherwise exclude.

**Comment by PhoebeHui** [comment]
@Mayhem93, feel free reopen if you expect vcpkg do something here.
