### ISSUE TITLE
PCL installation issue

### ISSUE THREAD

**Issue by varunkasi** [microsoft/vcpkg#11857]
Package: hdf5:x86-windows
  Vcpkg version: 2020.02.04-nohash

**Comment by NancyLi1013** [comment]
Hi @varunkasi 
Thanks for posting this issue.
Could you please provide the error info you encountered?

**Comment by NancyLi1013** [comment]
@varunkasi 
Thanks for your quick response. Now I'm closing this issue.
Please open a new issue if you have any other questions when using vcpkg.

**Comment by varunkasi** [comment]
Sounds good. Thank you.
