### ISSUE TITLE
How do I install a package/library and above all executable?

### ISSUE THREAD

**Issue by marcoxa** [microsoft/vcpkg#11856]
Hi

I just tried to install xalan-c on a clean vcpkg installation (first time!!!)

I looked at the examples and on vcpkg.readthedocs.io and on the command line help, but I do not seem to have understood how and where I can install the Xalan.exe executable.

Issuing

C:\Where\vcpkg\is> .\vcpkg install xalan-c

correctly installs the *libraries* for xalan and xerces.  But the Xalan.exe file is "left" in the 'src' subfolder.

How do I tell vcpkg to copy the .exe file in an "executable" folder?  I believe this is an expected behavior.

All the best

Marco

**Comment by LilyWangL** [comment]
Thanks for posting this issue. I can't found the `Xalan.exe` file in xalan-c source, do you mean the `XalanExe.cpp` file?

**Comment by marcoxa** [comment]
If you run afresh

PS C:\vcpkg\is\here> vcpkg install xalan-c

The job seems to complete just fine and you end up with Xalan.exe (the executable) and friends in the following folders.

C:\vcpkg\is\here\vcpkg\buildtrees\xalan-c\x86-windows-dbg\src\xalanc
C:\vcpkg\is\here\vcpkg\buildtrees\xalan-c\x86-windows-rel\src\xalanc

In

C:\vcpkg\is\here\vcpkg\installed\x64-windows\bin

I find the .dll and .pdb files.  This looks like a good place to install the executables.  Alas, Xalan.exe is not here.

Whether this is vcpkg problem of a Xalan problem, I do not know.  I have not found any clues in either documentation about how to tell vcpkg "put the executable here or use a sensible default".

Now, I understand that "installing executables" (read "Apps") may not be the primary concern of vcpkg (which appears to be "let's install libraries").  But **that** behavior is what it expected when you come from apt or brew.

Note that I just tired Xalan.  I would not be surprised if other tools, i.e., tools that provide, at a minimum, CLI commands where to create this problem with the current vcpkg.

All the best

Marco

PS You quickly need a section of the manual about "upgrading vcpkg".

**Comment by LilyWangL** [comment]
Importing Xalan.exe will be fixed in PR #11869. About "upgrading vcpkg", you can use command `.\vcpkg upgrade`, the related documentation: https://github.com/microsoft/vcpkg/blob/dcd9595b3fb3c556b24b46764e155bf79adde44f/docs/about/faq.md#how-do-i-update-libraries
