### ISSUE TITLE
[getopt_win32] supports mingw only

### ISSUE THREAD

**Issue by degski** [microsoft/vcpkg#11864]
By inspection one can see that the above port, is 'ported' from posix to mingw (I wonder why you need a port, but ok).

There is a Apache-licensed implementation here as a work-around (just drop it in): https://github.com/iotivity/iotivity/tree/master/resource/c_common/windows .

**Comment by PhoebeHui** [comment]
I'm also not clear the background, the author @qmfrederik might know more about getopt-win32 port.

**Comment by degski** [comment]
> 
> 
> I'm also not clear the background, the author @qmfrederik might know more about getopt-win32 port.

It's weird coz they only things that do not need porting are the common posix elements, while that's exactly what we seem to be doing here.

**Comment by qmfrederik** [comment]
Well, the goal of this port was/is to support compiling code which uses getopt on Windows, without needing msys2 (i.e. a native Visual C++ toolchain).

The codebase I maintain originally used a CoApp package to get bring in getopt, and at one point it was migrated to vcpkg and that's where this port comes from.

If there's an easier way to do that, happy to be educated.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. This issue hasn’t been updated for a long time. Please reopen this issue if this is still a problem for you.
