### ISSUE TITLE
Need help with libffi arm build

### ISSUE THREAD

**Issue by zabulus** [microsoft/vcpkg#1187]
I currently trying to add support of libffi for arm.
I've made port that only lacks building of arm asm files (at least I suppose so).
armasm is unable to build resulting .S files. As I understand armasm have it's own dialect not compatible with libffi asm files.
So my question is: what could be used as replacement of arm assembler?

**Comment by ras0219-msft** [comment]
We do have `nasm` and `yasm` wired up in [`vcpkg_find_acquire_program()`](https://vcpkg.readthedocs.io/en/latest/maintainers/vcpkg_find_acquire_program/) -- these might be able to target arm.

**Comment by zabulus** [comment]
They're both not support arm:
http://www.tortall.net/projects/yasm/manual/html/running-arch.html
and Nasm also claims absence of ARM

**Comment by codicodi** [comment]
Maybe this will help:
https://groups.google.com/forum/#!topic/discuss-webrtc/VuM_GkoB_fo

**Comment by LilyWangL** [comment]
This issue hasn’t been updated in a year, if it is still an issue, please reopen.
