### ISSUE TITLE
[New Port Request] Mesa3D

### ISSUE THREAD

**Issue by jonshipman** [microsoft/vcpkg#11879]
Library name: Mesa 3D Graphics Library

Library description: Mesa is an open-source implementation of the OpenGL specification. It also has additional API support including OpenGL ES (versions 1, 2, 3), OpenCL, OpenMAX, VDPAU, VA API, XvMC and Vulkan.

Source repository URL: https://gitlab.freedesktop.org/mesa/mesa.git

Project homepage (if different from the source repository): https://www.mesa3d.org/

--- Seeing as how OpenGL is deprecated in Windows.... Mesa3D might be a decent library to support and add. The OpenGL libs included in vcpkg are not supported on ARM/ARM64 making packages that require OpenGL impossible to compile. Qt5, for example. See the following urls: https://doc.qt.io/qt-5/qt-attribution-llvmpipe.html, https://www.mesa3d.org/systems.html, https://www.mesa3d.org/llvmpipe.html

**Comment by Neumann-A** [comment]
Blocked by meson. 
1) Currently debug builds are impossible with llvmpipe enabled. 
2) compiling to arm/arm64 on windows is impossible due to mesons sanity check.

**Comment by Voskrese** [comment]
https://github.com/pal1000/mesa-dist-win/issues/35

https://github.com/pal1000/mesa-dist-win/commit/a2661caeba56ad0c05ae8dcb81f6a8864daeb522

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by Neumann-A** [comment]
@LilyWangL: Remove label [info:new-port-unresolved](https://github.com/microsoft/vcpkg/labels/info%3Anew-port-unresolved)
