### ISSUE TITLE
[New Port Request] libsoup

### ISSUE THREAD

**Issue by iamhatling** [microsoft/vcpkg#11878]
Library name:libsoup

Library description:
libsoup is an HTTP client/server library for GNOME. It uses GObjects
and the glib main loop, to integrate well with GNOME applications.

Source repository URL:https://github.com/GNOME/libsoup

Project homepage (if different from the source repository):

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
