### ISSUE TITLE
[New Port Request] <bitmagic>

### ISSUE THREAD

**Issue by JangBoo** [microsoft/vcpkg#11889]
Library name: bitmagic

Library description: Algorithms and tools for Algebra of Sets for information retrieval, indexing of databases, scientific algorithms, ranking, clustering, unsupervised machine learning and signal processing.

Source repository URL: https://github.com/tlk00/BitMagic

Project homepage (if different from the source repository): http://bitmagic.io/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by NancyLi1013** [comment]
Hi @JangBoo 
Thanks for posting this request and also for your PR.
I'm closing this issue for now since it has been added to vcpkg.
