### ISSUE TITLE
Failure to bootstrap vcpkg on 12d202099e9

### ISSUE THREAD

**Issue by TheCycoONE** [microsoft/vcpkg#11881]
**Describe the bug**
Fails to bootstrap with compile errors regarding undefined "std::experimental::filesystem::*" types. (See attached)

**Environment**
- OS: Microsoft Windows [Version 10.0.18363.836] (x64)
- Compiler: VisualStudio.16.Release/16.5.2+29926.136

**To Reproduce**
1. ./bootstrap-vcpkg
2. See error

**Expected behavior**
Should bootstrap vcpkg

**Failure logs** 
[error.log](https://github.com/microsoft/vcpkg/files/4762309/error.log)

**Comment by JackBoosY** [comment]
This function has been removed and fixed in the latest Visual Studio 2019.
Please update your Visual Studio.
Related: [#1269](https://github.com/microsoft/cpprestsdk/issues/1269)

Thanks.
