### ISSUE TITLE
Are automatic app-local dependencies supposed to work reliably for all packages?

### ISSUE THREAD

**Issue by PazerOP** [microsoft/vcpkg#11895]
This is my first time using CMake so sorry if this is a dumb question.

I took the minimal example of usage with CMake from https://github.com/microsoft/vcpkg/blob/master/docs/examples/installing-and-using-packages.md and replaced sqlite3 with SDL2. I end up with this:

```CMake
# CMakeLists.txt
cmake_minimum_required(VERSION 3.17)
project(test)

find_package(SDL2 CONFIG REQUIRED)

add_executable(main main.cpp)

target_link_libraries(main PRIVATE SDL2)
```
```C++
// main.cpp
#include <SDL2/SDL.h>
#include <stdio.h>

// An old SDL2 hack
#undef main

int main()
{
	SDL_Init(0);
	return 0;
}
```

First things first: Neither <SDL2/SDL.h> or <SDL.h> can be found, so I add `find_path` and `target_include_directories`:

```CMake
# CMakeLists.txt
cmake_minimum_required(VERSION 3.17)
project(test)

find_package(SDL2 CONFIG REQUIRED)
find_path(SDL2_INCLUDE_DIR SDL2/SDL.h)

add_executable(main main.cpp)
target_include_directories(main PRIVATE ${SDL2_INCLUDE_DIR})

target_link_libraries(main PRIVATE SDL2)
```

Now I can compile, but linking fails because SDL2.lib cannot be found. Okay, I add `find_library` and replace "SDL2" with an absolute path:
```CMake
# CMakeLists.txt
cmake_minimum_required(VERSION 3.17)
project(test)

find_package(SDL2 CONFIG REQUIRED)
find_path(SDL2_INCLUDE_DIR SDL2/SDL.h)
find_library(SDL2_LIBRARY_DIR SDL2)

add_executable(main main.cpp)
target_include_directories(main PRIVATE ${SDL2_INCLUDE_DIR})
target_link_libraries(main ${SDL2_LIBRARY_DIR})

target_link_libraries(main PRIVATE SDL2)
```

Now everything compiles, but the program does not run, because the dependencies (SDL2.dll) were not copied to the program's output directory. From what I've seen, vcpkg should do this automatically, and indeed it does for the sqlite3 example. What am I doing wrong here that breaks it?

Another thing I feel I must point out: The exact same behavior occurs with glbinding (a dependency I use in my actual project). I know that's not a terribly large sample size... but it seems to me as if sqlite3 is some kind of "blessed" package that happens to work perfectly out of the box. Would it not be better to provide a more "real-world" example? As a CMake novice, I spent several hours trying to figure out why the behavior between sqlite3 and SDL2 was so different, only to come to the conclusion that the scripts were just written that way.

**Comment by qis** [comment]
Here is a simple example project that works: https://github.com/qis/sdl2-test

Open it by right-clicking into the directory and selecting "Open in Visual Studio" or enter the directory in `cmd.exe` and run `make`, `make run`, or `make install`.

**Comment by Neumann-A** [comment]
```
# CMakeLists.txt
cmake_minimum_required(VERSION 3.0)
project(test)

find_package(SDL2 CONFIG REQUIRED)

add_executable(main main.cpp)

target_link_libraries(main PRIVATE  SDL2::SDL2) # also  SDL2::SDL2main?
```

Using VCPKG does not simplify using CMake. So you still need to know which CMake targets a package export and correctly link it into your code.

**Comment by PazerOP** [comment]
@Neumann-A that works perfectly! Thanks! I didn't come across any examples online that used that notation. It's not even in the documentation for `target_link_libraries` but at least I know about it now.

**Comment by qis** [comment]
`vcpkg install sdl2` printed it out…

**Comment by PazerOP** [comment]
Correct, I misread that because everywhere else I was looking online (including the examples here) don't use that form.
