### ISSUE TITLE
[skia] Add Linux and Android support

### ISSUE THREAD

**Issue by handicraftsman** [microsoft/vcpkg#11909]
Skia supports Linux and Android operating systems natively, but vcpkg's build scripts do not.

**Comment by daljit97** [comment]
I also second this. I just tried this and got:

> Computing installation plan...
> The following packages will be built and installed:
>     skia[core]:x64-linux
> Starting package 1/1: skia:x64-linux
> Building package skia[core]:x64-linux...
> CMake Error at scripts/cmake/vcpkg_fail_port_install.cmake:93 (message):
>   Target 'LINUX' not supported by skia!
> 
> Call Stack (most recent call first):
>   ports/skia/portfile.cmake:1 (vcpkg_fail_port_install)
>   scripts/ports.cmake:76 (include)
> 
> 
> Error: Building package skia:x64-linux failed with: BUILD_FAILED
> Please ensure you're using the latest portfiles with `.\vcpkg update`, then
> submit an issue at https://github.com/Microsoft/vcpkg/issues including:
>   Package: skia:x64-linux
>   Vcpkg version: 2020.02.04-unknownhash
> 
> Additionally, attach any relevant sections from the log files above.

**Comment by abhishekmishra** [comment]
I need this support on linux, can I help enable/test this?

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. `skia` support Linux now, you can use latest vcpkg to build `skia` on Linux. Since Android is community triplet, if someone is interested in adding and testing supports for `skia`, please reopen this issue.
```
Elapsed time to handle skia:x64-linux: 15.41 min

Total elapsed time: 23.91 min

skia provides CMake targets:
    # this is heuristically generated, and may not be correct
    find_package(skia CONFIG REQUIRED)
    target_link_libraries(main PRIVATE skia skia::skia)
```
