### ISSUE TITLE
GDAL update to 3.1.0

### ISSUE THREAD

**Issue by dec0dOS** [microsoft/vcpkg#11905]
Library name: GDAL

New version number: 3.1.0

**Comment by Gigas002** [comment]
3.1.2 was released recently. Hope that's going to be updated soon, current version 2.4.1 was released more then year ago.

**Comment by nzmercer** [comment]
Please update this. There are some very important feature updates.
I would implement it myself and do a pull request if I could actually build GDAL 3+ myself. I can't figure it out. (On Windows with Visual Studio)

**Comment by JackBoosY** [comment]
Will update in #9100.

**Comment by oswjk** [comment]
I see that #9100 was closed. Is someone working on this? The latest bugfix release of GDAL is 3.1.3.

**Comment by JackBoosY** [comment]
@oswjk I will update later.

**Comment by JackBoosY** [comment]
Needs to update libgeotiff first.
