### ISSUE TITLE
[atkmm] build failure on Linux

### ISSUE THREAD

**Issue by AtikMo** [microsoft/vcpkg#11906]
**Host Environment**
- OS: Linux (Ubuntu)
- Compiler: revision

**To Reproduce**
`./vcpkg install gtkmm`

**Failure logs** 
-- Building /home/Dell/Documents/vcpkg-master/buildtrees/atkmm/src/atkmm-2-de808b48b0/MSVC_Net2013/atkmm.sln for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: msbuild /home/Dell/Documents/vcpkg-master/buildtrees/atkmm/src/atkmm-2-de808b48b0/MSVC_Net2013/atkmm.sln /p:Configuration=Release /t:atkmm /p:Platform=x64 /p:PlatformToolset=external /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /p:WindowsTargetPlatformVersion= /m /p:ForceImportBeforeCppTargets=/home/Dell/Documents/vcpkg-master/scripts/buildsystems/msbuild/vcpkg.targets /p:VcpkgTriplet=x64-linux /p:VcpkgCurrentInstalledDir=/home/Dell/Documents/vcpkg-master/installed/x64-linux
    Working Directory: /home/Dell/Documents/vcpkg-master/buildtrees/atkmm/x64-linux-rel
    Error code: No such file or directory
    See logs for more information:

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_msbuild.cmake:120 (vcpkg_execute_required_process)
  ports/atkmm/portfile.cmake:25 (vcpkg_build_msbuild)
  scripts/ports.cmake:76 (include)

Error: Building package atkmm:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: atkmm:x64-linux
  Vcpkg version: 2020.02.04-unknownhash

Additionally, attach any relevant sections from the log files above.-Please attach any additional failure logs mentioned in the console output.

**Additional context**
none

**Comment by NancyLi1013** [comment]
Hi @AtikMo 
Thanks for posting this issue.
Since `atkmm `currently doesn't support linux. Let's track this issue here #9564.
