### ISSUE TITLE
[boost] build failure

### ISSUE THREAD

**Issue by Desmond121** [microsoft/vcpkg#11902]
**Host Environment**
- OS: Windows10 

**To Reproduce**
`./vcpkg install boost:x64-windows`

**Failure logs** 
Additional packages (*) will be modified to complete this operation.
Starting package 1/146: boost-compatibility:x64-windows
Building package boost-compatibility[core]:x64-windows...
-- Using cached D:/vcpkg/downloads/boostorg-compatibility-boost-1.73.0.tar.gz
-- Using source at D:/vcpkg/buildtrees/boost-compatibility/src/ost-1.73.0-44642da97c
-- Packaging headers
-- Packaging headers done
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.73.0/LICENSE_1_0.txt...
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.73.0/LICENSE_1_0.txt... Failed. Status: 56;"Failure when receiving data from the peer"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:175 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  installed/x64-windows/share/boost-vcpkg-helpers/boost-modular-headers.cmake:17 (vcpkg_download_distfile)
  ports/boost-compatibility/portfile.cmake:12 (boost_modular_headers)
  scripts/ports.cmake:76 (include)

Error: Building package boost-compatibility:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-compatibility:x64-windows
  Vcpkg version: 2020.02.04-nohash

**Comment by hellozee** [comment]
Could you try to install that again, sometimes it does fail to download, :smile:

**Comment by Desmond121** [comment]
> Could you try to install that again, sometimes it does fail to download, 😄

Actually I have already install it for so many times. I doubt that it might be my network issue at first, then I try to install opencv4 and it worked. So I guess maybe there is something wrong with the install URL(the 'raw.githubuserxxxxx')? I copy it to my browser and still cannot open it.

**Comment by hellozee** [comment]
The link does open in my browser, if that is the one from the log which you post. Also I too installed that package a few hours back.

**Comment by Desmond121** [comment]
That means it would something wrong with my setting, I'll go to check it, thanks bro.
