### ISSUE TITLE
[New Port Request] STX

### ISSUE THREAD

**Issue by lamarrr** [microsoft/vcpkg#11918]
Library name: STX

Library description: C++ 17 & C++ 20 Error-Handling and Utility Extensions

Source repository URL: https://github.com/lamarrr/STX

Project homepage (if different from the source repository): https://lamarrr.github.io/STX/

Anything else that is useful to know when adding (such as optional features the library may have that should be included): 

- it fetches dependencies using git
- optional features: enable backtrace library ( `STX_ENABLE_BACKTRACE` ), panic backtrace ( `STX_ENABLE_PANIC_BACKTRACE` ) , override the global panic handler ( `STX_OVERRIDE_PANIC_HANDLER` ), make panic hooks visible when loaded as a DLL ( `STX_VISIBLE_PANIC_HOOK` )

**Comment by jeanga** [comment]
I have been working on an initial version of this port here: https://github.com/jeanga/vcpkg/tree/master/ports/stx
It still requires some testing but so far so good it seems to work.
I will submit a PR when more testing is done (WSL, etc..)
