### ISSUE TITLE
[New Port Request] pdfium

### ISSUE THREAD

**Issue by chena1982** [microsoft/vcpkg#11917]
Library name: pdfium

Library description: Chromium used pdf library.

Source repository URL: https://pdfium.googlesource.com/pdfium/+/master/docs/getting-started.md

Project homepage (if different from the source repository):

I found some c++ pdf library, most of them didn't update now.
Google will maintain this library, so i think it's a better choice.

Thanks.

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by willie** [comment]
I'm new to vcpkg, but I use libpdfium (custom build) in my projects. I was hoping you all had it. I can understand why you don't, too.
