### ISSUE TITLE
[New Port Request] mysql-connector-cpp

### ISSUE THREAD

**Issue by yurybura** [microsoft/vcpkg#11921]
Library name:
MySQL Connector/C++
Library description:
MySQL Connector/C++ is a MySQL database connector for C++.
Source repository URL:
https://github.com/mysql/mysql-connector-cpp

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by autoantwort** [comment]
https://github.com/microsoft/vcpkg/labels/info%3Anew-port-unresolved can be removed.
