### ISSUE TITLE
[apr-util] build failure

### ISSUE THREAD

**Issue by Septarius** [microsoft/vcpkg#11923]
**Host Environment**
- It is a failure via the CI during a PR build. 
- OS: x64_osx
- Compiler: AppleClang 11.0.3.11030032

**To Reproduce**
Created PR that retriggered the apr-util build #11961

**Failure logs** 
_Console_
```
-- Using cached /Users/vagrant/Data/downloads/apr-util-1.6.1.tar.bz2
-- Extracting source /Users/vagrant/Data/downloads/apr-util-1.6.1.tar.bz2
-- Using source at /Users/vagrant/Data/buildtrees/apr-util/src/apr-util-1-a62665826e
-- Configuring apr-util
-- Configuring x64-osx-dbg
-- Configuring x64-osx-rel
-- Building x64-osx-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: /usr/bin/make V=1 -j 6 -f Makefile all
    Working Directory: /Users/vagrant/Data/buildtrees/apr-util/x64-osx-dbg
    See logs for more information:
      /Users/vagrant/Data/buildtrees/apr-util/build-x64-osx-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_make.cmake:200 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_make.cmake:24 (vcpkg_build_make)
  ports/apr-util/portfile.cmake:78 (vcpkg_install_make)
  scripts/ports.cmake:76 (include)
```

_Config Errors_
```
configure: WARNING: unrecognized options: --disable-silent-rules, --enable-static, --disable-shared
./../src/apr-util-1-a62665826e/configure: line 4089: cd: /Volumes/data/work/1/s/installed/x64-osx/build-1: No such file or directory
cp: /apr_rules.mk: No such file or directory
configure: WARNING: unrecognized options: --disable-silent-rules, --enable-static, --disable-shared
```

_Build Errors_
```
Makefile:50: /Volumes/data/buildtrees/apr-util/x64-osx-dbg/build/rules.mk: No such file or directory
make: *** No rule to make target `/Volumes/data/buildtrees/apr-util/x64-osx-dbg/build/rules.mk'.  Stop.
```

Attached are the artifacts from the builds
[PR11882-x64-osx port build failure logs.zip](https://github.com/microsoft/vcpkg/files/4775438/PR11882-x64-osx.port.build.failure.logs.zip)
[PR11290-x64-osx port build failure logs.zip](https://github.com/microsoft/vcpkg/files/4775440/PR11290-x64-osx.port.build.failure.logs.zip)

**Additional context**
See PR #11882 and PR #11290

**Comment by NancyLi1013** [comment]
@Septarius 
Thanks for posting this issue.
Could you please help confirm if you can reproduce this on your machine?
I try to test this and it can be built successfully on my local.

**Comment by Septarius** [comment]
@NancyLi1013 
I don't have anything local to test the OSX build. I created a PR to attempt to reproduce the build error of apr-util by retriggering it on the CI #11961

**Comment by BillyONeal** [comment]
I think this is an incompatibility with some ports and apr. I observe that when I build apr and/or apr-util by themselves like this:

```
git clean -xdff
./bootstrap_vcpkg.sh
./vcpkg install apr-util --binarycaching "--x-binarysource=clear;files,/Users/billyoneal/vcpkg_archives,upload"
git clean -xdff
./bootstrap_vcpkg.sh
./vcpkg install apr expat openssl --binarycaching "--x-binarysource=clear;files,/Users/billyoneal/vcpkg_archives,upload"
./vcpkg install apr-util
```

I get a successful build. But the binary cache for apr contains a bunch of things it should not contain, including *libtool*:

```
billyoneal@bion-mbp16 vcpkg % ls -R ~/vcpkg_archives/96/967f3a9db9ba6ab3d71af02eccf48f632d5172d8
BUILD_INFO	CONTROL		build-1		debug		include		lib		share		tools

/Users/billyoneal/vcpkg_archives/96/967f3a9db9ba6ab3d71af02eccf48f632d5172d8/build-1:
apr_rules.mk		libtool			make_exports.awk	make_var_export.awk	mkdir.sh

[rest of stuff omitted]

billyoneal@bion-mbp16 vcpkg % 
```

so if there's some other port that's also trying to create this "build-1" directory and that ended up getting sucked up into its cache, then the cached apr package would be missing this stuff. But it seems apr-util shouldn't be getting things like *libtool* et al. from the apr package?

**Comment by BillyONeal** [comment]
(Are there ports that obviously have a vendored apr that might trigger such problems?)

**Comment by Septarius** [comment]
PR #12067 fixed the issue for PR #11882 and should fix it for #11290 and any others that had the similar apr/apt-util block

**Comment by BillyONeal** [comment]
Ah, yep :)

**Comment by BillyONeal** [comment]
@Septarius Is this resolved to your satisfaction?

**Comment by Septarius** [comment]
LGTM. I can’t kick off the build for #11290 but I am confident it will work or have an unrelated issue. So I will go ahead and close this. Thanks!
