### ISSUE TITLE
How do I set the Android SDK platform version outside of editing android.cmake?

### ISSUE THREAD

**Issue by kevinlul** [microsoft/vcpkg#11927]
I can set ANDROID_NATIVE_API_LEVEL by editing the provided [toolchain file](https://github.com/microsoft/vcpkg/blob/master/scripts/toolchains/android.cmake#L5). I've noticed that setting this in the triplet file has no effect. Can the platform version for Android be configured as a user of vcpkg without editing files in the tree or is this the only way?

**Comment by kevinlul** [comment]
If I'm understanding vcpkg correctly, CMake variables set in the triplet file can be read by the portfile; however, either the toolchain file is run before the triplet file or its variables are isolated from the triplet file except for a select few, so we can't pass anything that way.

I understand that some variables like `VCPKG_CRT_LINKAGE` are known in the toolchain file, but it doesn't seem to work in general or for other specific `VCPKG_*` variables. I tried setting `VCPKG_CMAKE_SYSTEM_VERSION` in the triplet, since the NDK toolchain forces `CMAKE_SYSTEM_VERSION` to 1 in favour of its own `ANDROID_PLATFORM` system (aka `ANDROID_NATIVE_API_LEVEL`), but the value was not accessible from the toolchain file.

**Comment by christophe-calmejane** [comment]
@kevinlul (and others)
**VCPKG_CMAKE_SYSTEM_VERSION** can now be used in **android triplet files** to choose the **native API** to be used by the NDK (currently defaults to 21).
