### ISSUE TITLE
[New Port Request] Simple-FFT

### ISSUE THREAD

**Issue by ArielxX** [microsoft/vcpkg#11928]
Library name: Simple-FFT

Library description: Header-only C++ library implementing fast Fourier transform of 1D, 2D and 3D data. 

Source repository URL: https://github.com/d1vanov/Simple-FFT

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by Pospelove** [comment]
You can use this: https://github.com/microsoft/vcpkg/pull/11929. However I am not sure my PR can be merged, for now, there is no LICENSE.md in the repo of the library requested.
