### ISSUE TITLE
range-v3 package fails to build because hash doesn't match on download file

### ISSUE THREAD

**Issue by pratzl** [Microsoft/vcpkg#1192]
I've included the log from the output below. This is repeatable.

C:\lib\vcpkg>vcpkg install range-v3:x64-windows
The following packages will be built and installed:
    range-v3:x64-windows
Building package range-v3:x64-windows...
-- CURRENT_INSTALLED_DIR=C:/lib/vcpkg/installed/x64-windows
-- DOWNLOADS=C:/lib/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/lib/vcpkg/packages/range-v3_x64-windows
-- CURRENT_BUILDTREES_DIR=C:/lib/vcpkg/buildtrees/range-v3
-- CURRENT_PORT_DIR=C:/lib/vcpkg/ports/range-v3/.
-- Downloading https://github.com/ericniebler/range-v3/archive/6eb5c831ffe12cd5cb96390dbe917ca1b248772d.zip...
-- Downloading https://github.com/ericniebler/range-v3/archive/6eb5c831ffe12cd5cb96390dbe917ca1b248772d.zip... OK
-- Testing integrity of downloaded file...
-- Testing integrity of downloaded file... OK
-- Downloading https://github.com/Microsoft/Range-V3-VS2015/compare/fork_base...00ed689bac7a9dcd8601dbde382758675516799d.diff...
-- Downloading https://github.com/Microsoft/Range-V3-VS2015/compare/fork_base...00ed689bac7a9dcd8601dbde382758675516799d.diff... OK
-- Testing integrity of downloaded file...
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:47 (message):

  File does not have expected hash:

          File path: [ C:/lib/vcpkg/downloads/range-v3-fork_base_to_00ed689bac7a9dcd8601dbde382758675516799d.diff ]
      Expected hash: [ 615a53ebac22df03e865bdcc86580914c4505ec5fc691b6a2f864f7bf63690b99d0da0db2d5b1026e34b0a3f7557f30dfa0cad65643bae0b53c0ec066af9eb8e ]
        Actual hash: [ 6158cd9ee1f5957294a26dc780c881839e0bae8610688a618cd11d47df34d5e543fa09ac9a3b33d4a65af8eceae0a6a3055621206c291ef75f982e7915daf91a ]

  The file may be corrupted.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:87 (test_hash)
  ports/range-v3/portfile.cmake:9 (vcpkg_download_distfile)
  scripts/ports.cmake:73 (include)

Error: Building package range-v3:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: range-v3:x64-windows
  Vcpkg version: 0.0.81-39b69e5b06df309b9dcfea55296a4c2c3eea93ce

Additionally, attach any relevant sections from the log files above.

**Comment by pratzl** [comment]
I'm using the command window "x64 Native Tools Command Prompt for VS 2017"

**Comment by Voskrese** [comment]
File does not have expected hash:

edit
portfile.cmake

и меняй хеши, то что выше
заменить
~~615a53ebac22df03e865bdcc86580914c4505ec5fc691b6a2f864f7bf63690b99d0da0db2d5b1026e34b0a3f7557f30dfa0cad65643bae0b53c0ec066af9eb8e~~
на 
`6158cd9ee1f5957294a26dc780c881839e0bae8610688a618cd11d47df34d5e543fa09ac9a3b33d4a65af8eceae0a6a3055621206c291ef75f982e7915daf91a `

**Comment by ras0219-msft** [comment]
Thanks for reporting this!

@Voskrese fixed this in PR #1194 :)
