### ISSUE TITLE
[New Port Request] Libosmium

### ISSUE THREAD

**Issue by martinsah** [microsoft/vcpkg#11922]
Library name: Libosmium

Library description: A fast and flexible C++ library for working with OpenStreetMap data.

Source repository URL: https://github.com/osmcode/libosmium

Project homepage (if different from the source repository): https://osmcode.org/libosmium/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by Pospelove** [comment]
This port has been already added: https://github.com/microsoft/vcpkg/pull/11863

**Comment by PhoebeHui** [comment]
Thanks @Pospelove for the information!
