### ISSUE TITLE
vcpkg, It stays frozen and does not continue

### ISSUE THREAD

**Issue by giansalex** [Microsoft/vcpkg#1193]
One hour and not continue.
![image](https://cloud.githubusercontent.com/assets/14926587/26568455/1f7a592a-44c9-11e7-9f5a-d17fc2672b46.png)

SO: Windows 10 x64
Last version Repository.
VS 2017.

**Comment by ras0219-msft** [comment]
Hi @giansalex, thanks for reporting this issue!

Could you try using powershell in the default windows console and let us know if you hit the same issue?

**Comment by giansalex** [comment]
Thanks you, it's work using PS.
