### ISSUE TITLE
How do I avoid the lock of Windows Domain account by corporate virus scanner

### ISSUE THREAD

**Issue by TonyXiang8787** [microsoft/vcpkg#11944]
**Describe the bug**

After I clone the repository, my Windows Domain account is immediately locked by the corporate virus scanner. After contacting the IT security, they have concluded that there are disallowed script in the folder (repo) in [prevision-image.ps1](https://github.com/microsoft/vcpkg/blob/master/scripts/azure-pipelines/windows/provision-image.ps1). Specifically, the following lines are not allowed in the script.

```
Add-MPPreference -ExclusionPath C:\
Add-MPPreference -ExclusionPath D:\
Add-MPPreference -ExclusionPath E:\
Add-MPPreference -ExclusionProcess ninja.exe
Add-MPPreference -ExclusionProcess clang-cl.exe
Add-MPPreference -ExclusionProcess cl.exe
Add-MPPreference -ExclusionProcess link.exe
Add-MPPreference -ExclusionProcess python.exe
```

As far as I can tell, the scripts in the folder `scripts/azure-pipelines/windows` are not needed to run `vcpkg` locally. But merely having the scripts in the local harddisk will trigger antivirus immediately and the domain account will be locked. Ironically, our company uses Microsoft Corporate Windows Defender as antivirus.

**Environment**
- OS: Windows 10 1809 Enterprise, in Windows Domain
- Antivirus: Windows Defender
- Compiler: not relevant

**To Reproduce**
1. git clone https://github.com/microsoft/vcpkg.git
2. within minutes the Windows domain account is locked

**Expected behavior**
Use `vcpkg` normally.

**Failure logs** 
- not relevant

**Additional context**
I consider this a potential bug for `vcpkg` instead of internal corporate problem, because it is blocked by the **Microsoft Windows Defender** self. The security told us that we should delete the script files in folder `scripts/azure-pipelines/windows`. However, at the moment we do `git clone`, the scripts are already in the harddisk and the account will be locked within minutes. If these scripts are not needed locally, are there any other means to avoid account lock-down by the Windows Defender?

**Comment by PhoebeHui** [comment]
Related to https://github.com/microsoft/vcpkg/issues/11854

**Comment by PhoebeHui** [comment]
@TonyXiang8787, I think you can exclude the file in Defender Antivirus to avoid the false alert.

**Comment by PhoebeHui** [comment]
@TonyXiang8787, could you help test the change in https://github.com/microsoft/vcpkg/pull/11978, and see it works for you?

**Comment by TonyXiang8787** [comment]
@PhoebeHui Thanks! I will let our IT security to have a check.

**Comment by BillyONeal** [comment]
@timautry in #11972 indicated that it worked for him so I merged the PR and am closing this one as fixed, please comment if it's still getting detected for you.
