### ISSUE TITLE
How do I use multiple exported files from vcpkg on vs2019 cmake project?

### ISSUE THREAD

**Issue by yes89929** [microsoft/vcpkg#11948]
Hi
I'm always get help from vcpkg contributors and I appreciate it.
And I came back because of some problem in using exported packages of vcpkg.

For example,

1. Install packages
`vcpkg install boost`
`vcpkg install qt5`

2. Export packages individually
`vcpkg export boost --raw`
`vcpkg export qt5 --raw`

3. Import toolchain files on vs2019
but, Cmake prject in vs2019 can't select multiple toolchain file.
Are there any solutions? except `vcpkg export boost qt5 --raw`

![image](https://user-images.githubusercontent.com/33365390/84644531-43485800-af3a-11ea-97fa-75a9204a8354.png)

**Comment by JackBoosY** [comment]
Hi @yes89929, thanks for reporting this issue!
I don't know why you don't want to use the function of exporting multiple ports.
In order to ensure the correct dependencies between ports, we need to use the same vcpkg to export them, so it is reasonable to use multiple exports.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
