### ISSUE TITLE
[New Port Request] Open3D

### ISSUE THREAD

**Issue by Lvdi** [microsoft/vcpkg#11950]
Library name: Open3D

Library description: A Modern Library for 3D Data Processing

Source repository URL: https://github.com/intel-isl/Open3D

Project homepage (if different from the source repository): http://www.open3d.org/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
Related to https://github.com/microsoft/vcpkg/pull/17423

**Comment by PhoebeHui** [comment]
Please reopen this issue and continue PR https://github.com/microsoft/vcpkg/pull/17423 If you wish to add this port in the future.
