### ISSUE TITLE
QUESTION: vpx is not available for UWP on ARM* processors?

### ISSUE THREAD

**Issue by arsdever** [microsoft/vcpkg#11951]
https://github.com/microsoft/vcpkg/blob/ffa7fd27cfa29f206d1fd2ccfc722cad4aaeef3d/ports/libvpx/portfile.cmake#L1

Hi guys. As I understood from the first line, it is saying that it must fail on `UWP ARM*`, right?

**Comment by JackBoosY** [comment]
Hi @arsdever, thanks for reporting this issue!
The port where this line of code is added does not **currently** support specific triplets or the port **itself does not support** specific triplets.

**Comment by JackBoosY** [comment]
For this port, I can confirm it support arm and uwp.

**Comment by arsdever** [comment]
@JackBoosY Thanks a lot for your support. One question. Since I don't use `vcpkg` for some reason, but I have to build the lib for `UWP`. Do I need to apply some patches to be able to do build the lib for `UWP`? And, if speaking general, do I have to apply patches in the ports to build any lib for `UWP`? I mean, can I rely on the patches only when trying to build for `UWP`?

**Comment by JackBoosY** [comment]
@arsdever Generally, if the port does **NOT** use system functions that **only support** the **desktop app**, the port can build uwp, otherwise we need to find other functions that support uwp to replace it and make some patches.

**Comment by arsdever** [comment]
@JackBoosY Just to clarify. If there is a functionality to be changed, then these changes will be included in patches in the repository. And, when pulling the patches and patching the sources, developers should be able to compile the port. No more actions needed.

Correct?

**Comment by JackBoosY** [comment]
Yes,  but the patches should be put into path _VCPKG_PATH/Ports/PORTNAME_.

**Comment by arsdever** [comment]
@JackBoosY Thanks a lot. I have got all the answers.
