### ISSUE TITLE
GNU Scientific Library as installed by vcpkg is not found by CMake's FindGSL.cmake

### ISSUE THREAD

**Issue by traversaro** [Microsoft/vcpkg#1196]
CMake's [`FindGSL.cmake`](https://gitlab.kitware.com/cmake/cmake/blob/88c4576be412c85c112976dcec51b3fb7905b618/Modules/FindGSL.cmake#L153) searches for a `cblas` or `gslcblas` library, that is not installed if you install the `gsl` port in vcpkg. 

It is not clear to me if `cblas` support is something optional for gsl and hence should be optional even in the `FindGSL.cmake` CMake module or there is something else going on. 

It is possible that this is an issue in CMake upstream, but I preferred  to open it here to first collect opinions of vcpkg users that use gsl (perhaps @muemart knows something about this). 

cc @drdanz

**Comment by muemart** [comment]
The port currently compiles everything into one binary, including the cblas stuff. I'll modify the port to produce a gslcblas binary and satisfy CMake.

**Comment by traversaro** [comment]
From the PR: https://github.com/Microsoft/vcpkg/pull/1199#issuecomment-305169875
 
> > I don't think it's possible to hack around that here, because the find script doesn't look for debug suffixes.
>
> I agree. I think the only possible solution here is to patch the file upstream in CMake, and afterwards modify vcpkg gsl's port to produce debug libraries with the debug suffixes.

With respect to this, we were lucky. The MR adding support for searching debug libraries (https://gitlab.kitware.com/cmake/cmake/merge_requests/914) was merged, and in a few days CMake 3.9.0 containing that modification will be released. At this point, I think it is safe to add a 
~~~
set(CMAKE_DEBUG_POSTFIX "d")
~~~
to GSL's `CMakeLists.txt`.
