### ISSUE TITLE
[boost-locale] ICU backend missing

### ISSUE THREAD

**Issue by pr8x** [microsoft/vcpkg#11969]
I ran `vcpkg install boost-locale[icu] boost-regex[icu] boost --triplet x64-windows --recurse`  to install the boost-locale library with icu support. However, querying the supported backends via 
```c++
auto backend_manager = boost::locale::localization_backend_manager::global();
auto bk = backend_manager.get_all_backends();
```

only returns `std` and `winapi`. Seems like it's not properly building it with icu backend. Also it doesn't seem to require linkage to icu binaries.

**Environment**
- OS: Windows10 x64
- Compiler: revision

**Comment by pr8x** [comment]
I tried building it locally with 
`./b2 boost.locale.winapi=off boost.locale.std=off -sICU_PATH="..\icu671" boost.locale.icu=on --with-locale stage -a --address-model=64`
But even that does not seem to build it with ICU support. 

![image](https://user-images.githubusercontent.com/4670166/85268202-804ea600-b476-11ea-86db-fe6ca502a2bc.png)

**Comment by PhoebeHui** [comment]
@pr8x, thanks for reporting this issue.

It seems that the option 'boost.locale.icu' has been set 'ON' for boost-locale https://github.com/microsoft/vcpkg/blob/24e8be5fcfddd0da98b58a63cd918849787fb06f/ports/boost-locale/b2-options.cmake#L12

Also I double check the log file, it looks already set the option to on.
```
Building target '../build/boost_locale'
Building target '../build/boost_locale'
     Build request: object(property-set)@411 <address-model>64 <architecture>x86 <boost.locale.iconv>off <boost.locale.icu>on <boost.locale.posix>off <link>shared <runtime-link>shared <threadapi>win32 <threading>multi <toolset>msvc <variant>debug
     Command line free features:
     Target requirements: <conditional>@Jamfile<E:\VCPKG\boost_173\vcpkg\buildtrees\boost-locale\src\ost-1.73.0-60f2c445b1\build>%Jamfile<E:\VCPKG\boost_173\vcpkg\buildtrees\boost-locale\src\ost-1.73.0-60f2c445b1\build>.configure <define>BOOST_ALL_NO_LIB=1 <define>BOOST_THREAD_NO_LIB=1 <include>../include&&/E:/vcpkg/boost_173/vcpkg/installed/x64-windows/include <link>shared:<define>BOOST_LOCALE_DYN_LINK=1 <relevant>define:<relevant>link <relevant>threading:<relevant>runtime-link <relevant>threading:<relevant>toolset <tag>@Jamfile<E:\VCPKG\boost_173\vcpkg\buildtrees\boost-locale\src\ost-1.73.0-60f2c445b1>%Jamfile<E:\VCPKG\boost_173\vcpkg\buildtrees\boost-locale\src\ost-1.73.0-60f2c445b1>.tag <threading>multi <toolset>msvc,<runtime-link>shared:<threading>multi

     Building target '../build/has_icu'
         Build request: object(property-set)@415 <address-model>64 <architecture>x86 <target-os>windows <toolset-msvc:version>14.2 <toolset>msvc
         Command line free features:
         Target requirements: <define>BOOST_ALL_NO_LIB=1 <include>../include&&/E:/vcpkg/boost_173/vcpkg/installed/x64-windows/include <library>/boost/locale//icudt/<link>shared/<runtime-link>shared <library>/boost/locale//icuin/<link>shared/<runtime-link>shared <library>/boost/locale//icuuc/<link>shared/<runtime-link>shared <relevant>threading:<relevant>runtime-link <relevant>threading:<relevant>toolset <runtime-link>shared <tag>@Jamfile<E:\VCPKG\boost_173\vcpkg\buildtrees\boost-locale\src\ost-1.73.0-60f2c445b1>%Jamfile<E:\VCPKG\boost_173\vcpkg\buildtrees\boost-locale\src\ost-1.73.0-60f2c445b1>.tag <toolset>msvc,<runtime-link>shared:<threading>multi
...
```

**Comment by PhoebeHui** [comment]
![image](https://user-images.githubusercontent.com/20694052/85272321-9bd5a300-b4ae-11ea-978c-7571cc5eed2e.png)

**Comment by pr8x** [comment]
Yes, the my buildtree has these `has_icu_*` files as well. But linking with the obj only gives me `std` and `winapi` as mentioned above. What am I supposed to do with these rsp files?

**Comment by PhoebeHui** [comment]
It seem icu lib doesn't link correctly, I noticed that link error in config.log:

msvc.link E:\vcpkg\boost_173\vcpkg\buildtrees\boost-locale\x64-windows-static-dbg\boost\build\7b17862d6e014c912b42e5cec9e0a8e2\has_icu64.exe
LINK : fatal error LNK1181: cannot open input file 'icudt.lib'

Hoever I already pass the icu path via '-sICU_PATH'
<xdll-path>/E:/VCPKG/boost_173/vcpkg/installed/x64-windows-static/debug/lib ]
         Usage requirements from has_icu:  <relevant>address-model <relevant>architecture <relevant>asynch-exceptions <relevant>cxxstd <relevant>cxxstd-dialect <relevant>debug-store <relevant>debug-symbols <relevant>deduced-address-model <relevant>deduced-architecture <relevant>embed-manifest <relevant>exception-handling <relevant>extern-c-nothrow <relevant>inlining <relevant>instruction-set <relevant>link <relevant>lto <relevant>lto-mode <relevant>optimization <relevant>pch <relevant>rtti <relevant>runtime-debugging <relevant>runtime-link <relevant>segmented-stacks <relevant>threading <relevant>toolset <relevant>toolset-msvc:vendor <relevant>toolset-msvc:version <relevant>variant <relevant>warnings <relevant>warnings-as-errors <relevant>windows-api <xdll-path>/E:/VCPKG/boost_173/vcpkg/installed/x64-windows-static/debug/lib
Performing configuration checks

    - icu                      : no

**Comment by PhoebeHui** [comment]
@yurybura, do you know more about this issue?

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/3537.

There is a PR https://github.com/microsoft/vcpkg/pull/10943 to fix this issue, @pr8x, could you try the changes and see if it works for you?

**Comment by PhoebeHui** [comment]
I will close this issue and track everything via 3537.
