### ISSUE TITLE
[slikenet] CMake targets seems to be missing

### ISSUE THREAD

**Issue by Reveares** [microsoft/vcpkg#11960]
Slikenet defines CMake targets like **RakNetDLL** and **RakNetLibStatic**. Unlike other projects I can't find them when I do `find_package(RakNetDLL CONFIG REQUIRED)` .
Are they missing for this port and if yes could they be included? Or am I doing something wrong?

**Comment by PhoebeHui** [comment]
@Reveares, thanks for reporting this issue!

I summited a PR 11987 for adding the cmake config and targets file, could you help test if that works for you?

The target name is SLikeNetDLL and SLikeNetLibStatic in CMakeList file, you can use it like:

Dynamic:
  find_package(slikenet CONFIG REQUIRED)
    target_link_libraries(main PRIVATE SLikeNetDLL)

Static:
    find_package(slikenet CONFIG REQUIRED)
    target_link_libraries(main PRIVATE SLikeNetLibStatic)

**Comment by Reveares** [comment]
@PhoebeHui Thanks for your time. I did a few quick test with your PR and it worked well for me. Especially that it is only one target now is a nice addition.
