### ISSUE TITLE
[cuda] build failure

### ISSUE THREAD

**Issue by normandantzig1** [microsoft/vcpkg#11976]
**Host Environment**

Windows 10 
Cuda 11

**To Reproduce**
 .\vcpkg install cuda

**Failure logs** 
Error: Building package cuda:x86-windows failed with: BUILD_FAILED
  Package: cuda:x86-windows
  Vcpkg version: 2020.02.04-nohash

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by NancyLi1013** [comment]
Hi @normandantzig1 
Thanks for posting this issue.
Could you please help confirm if the `CUDA_PATH `is correct?
Please add` message("CUDA_PATH:$ENV{CUDA_PATH}") to portfile.cmake, and then rebuild this.
`

**Comment by timautry** [comment]
@NancyLi1013 
@normandantzig1 mentions using cuda 11 
- the cuda/cudnn ports specifically look for version 10.1.0
- looks like it is in RC (release candidate) status https://developer.nvidia.com/cuda-downloads
- no download for cudnn to support cude 11.0 on developer site https://developer.nvidia.com/rdp/cudnn-archive
- upgrading cuda to 11.0 may break the cudnn port 
![image](https://user-images.githubusercontent.com/16106113/84927803-5d4d7c00-b09b-11ea-9beb-19c1307cb9df.png)

**Comment by NancyLi1013** [comment]
@timautry 
Thanks for looking into this issue.
I have tried with `cuda `11.0  and both `cuda `and `cudnn `can build successfully on my machine.
![image](https://user-images.githubusercontent.com/46708020/84971888-49178680-b150-11ea-87da-6d7cfdb5a620.png)

After downloading, the file name is `cuda_11.0.1_451.22_win10.exe`.

**Comment by normandantzig1** [comment]
Thank You.  Let me see about the path.

**Comment by Neumann-A** [comment]
@JackBoosY: I have the same problem. nvcc is not getting found although I can open a cmd prompt and do nvcc without a problem. About the paths: For some reason i have `CUDA_PATH_V10_2` but no `CUDA_PATH` variable and `CUDA_PATH_V10_2` is not accesible from within VCPKG.

**Comment by Neumann-A** [comment]
https://github.com/microsoft/vcpkg/blob/3d2a7ca33e9997051ea221c30ccd4835989879ad/toolsrc/src/vcpkg/base/system.process.cpp#L305-L315

needs updating and also 

https://github.com/microsoft/vcpkg/blob/3d2a7ca33e9997051ea221c30ccd4835989879ad/ports/cuda/portfile.cmake#L9-L15
