### ISSUE TITLE
2020.06 static triplet not working

### ISSUE THREAD

**Issue by pokev25** [microsoft/vcpkg#11980]
**Describe the bug**
vcpkg update 2020.06
rebuild vcpkg
my project build 
static triplet not working

**Environment**
- OS: Windows 10
- Compiler: VS2019

**To Reproduce**

git pull vcpkg
 .\bootstrap-vcpkg.bat

my project using static triplet
```
<PropertyGroup Label="Globals">
  <!-- .... -->
  <VcpkgTriplet Condition="'$(Platform)'=='Win32'">x86-windows-static</VcpkgTriplet>
  <VcpkgTriplet Condition="'$(Platform)'=='x64'">x64-windows-static</VcpkgTriplet>
</PropertyGroup>
```
and build 

but project using default triplet and build fail

```
1>Using triplet "x86-windows" from "D:\Library\vcpkg\installed\x86-windows\"
```

so I'm checkout 2020.04

```
git checkout tags/2020.04
```
and rebuild vcpkg 
now my project build success.

**Comment by kevinlul** [comment]
It seems like you need a separate property group like this now
```xml
<PropertyGroup Label="Vcpkg">
    <VcpkgEnabled>true</VcpkgEnabled>
    <VcpkgAutoLink>true</VcpkgAutoLink>
    <VcpkgUseStatic>true</VcpkgUseStatic>
</PropertyGroup>
```
I'm seeing this corresponding interface in Visual Studio 2019
![image](https://user-images.githubusercontent.com/6320810/84855782-f5fbe180-b032-11ea-958e-8cd639579597.png)

**Comment by pokev25** [comment]
@kevinlul 

Thank you for telling me.

I have another question

How do I set 'x86-windows-static-md' triplet?

**Comment by kevinlul** [comment]
The XML tag appears to be `<VcpkgUserTriplet>`.

**Comment by pokev25** [comment]
OK. I found in .vcxproj 

```
  <PropertyGroup Label="Vcpkg" Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'">
    <VcpkgUseStatic>true</VcpkgUseStatic>
    <VcpkgUserTriplet>$(VcpkgPlatformTarget)-$(VcpkgOSTarget)</VcpkgUserTriplet>
  </PropertyGroup>
```

setting to

```
  <PropertyGroup Label="Vcpkg" Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'">
    <VcpkgUserTriplet>$(VcpkgPlatformTarget)-$(VcpkgOSTarget)-static-md</VcpkgUserTriplet>
  </PropertyGroup>
```

now my project build success.

![image](https://user-images.githubusercontent.com/4251972/84859027-3dbc5080-b0a7-11ea-8753-1cde6e45fd3f.png)


is it correct?

**Comment by pokev25** [comment]
Ok 
close issue

I will wait for the update of the official documentation.
