### ISSUE TITLE
When installing local port file for test 2/3 is copied successfully in folders.

### ISSUE THREAD

**Issue by 67-al-ahad** [microsoft/vcpkg#11988]
Hi, I would like to know why there's a strange behavior when I try to test my port after the installation went successfully.

My port is named **mona-based**

Here are the final folder structures:

# C:\vcpkg\packages\
1. C:\vcpkg\packages\mona-base_x86-windows

- C:\vcpkg\packages\mona-base_x86-windows\debug\lib\MonaBase.lib
- C:\vcpkg\packages\mona-base_x86-windows\include\mona-base\Mona\*.h
- C:\vcpkg\packages\mona-base_x86-windows\lib\MonaBase.lib ***e.1**

**e.1** Here the **MonaBase.lib** file is the same as in the **\debug\lib** folder. Why doesn't vcpkg compile the release version and install it here?

2. C:\vcpkg\packages\mona-base_x86-windows\share

# C:\vcpkg\installed\x86-windows\ (Missing files)
1. C:\vcpkg\installed\x86-windows\debug\lib\
- Missing **MonaBase.lib** file why ?

2. C:\vcpkg\installed\x86-windows\include
- Missing **mona-base\\*.h**  files why ?

3. C:\vcpkg\installed\x86-windows\lib
- Missing **MonaBase.lib** file why ?

Project link : https://github.com/67-al-ahad/MonaBase

**Comment by 67-al-ahad** [comment]
Solution:

```
if(${CMAKE_BUILD_TYPE} MATCHES "Debug")
    install(TARGETS ${PROJECT_NAME} CONFIGURATIONS Debug RUNTIME DESTINATION Debug/lib)
else()
    install(TARGETS ${PROJECT_NAME} CONFIGURATIONS Release RUNTIME DESTINATION lib)
endif()
```

**Comment by NancyLi1013** [comment]
Hi @67-al-ahad 
Thanks for posting this issue.
Could you please help provide your portfile.cmake and CONTROL files for `mona-base`?

**Comment by 67-al-ahad** [comment]
[mona-base.zip](https://github.com/microsoft/vcpkg/files/4796006/mona-base.zip)

**Comment by NancyLi1013** [comment]
I try to build `mona-base` based on the files you provided above. There are no any problems.
The files generated by release version are listed in _\lib_, debug versions are listed in _\debug\lib_.
So I don't know what your problems are.
`MonaBase.lib` is in _\lib_, `MonaBased.lib` is in _\debug\lib_.
The headers are only installed in` \include` in release build.

**Comment by 67-al-ahad** [comment]
Well I added this that's why
```
if(${CMAKE_BUILD_TYPE} MATCHES "Debug")
    install(TARGETS ${PROJECT_NAME} CONFIGURATIONS Debug RUNTIME DESTINATION Debug/lib)
else()
    install(TARGETS ${PROJECT_NAME} CONFIGURATIONS Release RUNTIME DESTINATION lib)
endif()
```
But if you remove it you will see that it doesn't work.

**Comment by NancyLi1013** [comment]
I comment this out in CMakeLists.txt and rebuild this port. I didn't see any problems about this.

**Comment by 67-al-ahad** [comment]
Well then can you explain to me which part of the Cmakelists.txt is responsible of install all the files both in the packages and the installed folder of vcpkg?

**Comment by NancyLi1013** [comment]
The following codes are responsible for installing all targets(.lib,.dll) and headers.
```
install(TARGETS ${PROJECT_NAME}
        RUNTIME DESTINATION bin
        LIBRARY DESTINATION lib
        ARCHIVE DESTINATION lib)

install(DIRECTORY include/ DESTINATION include/mona-base FILES_MATCHING PATTERN "*.h")
```

**Comment by 67-al-ahad** [comment]
Is there any automatic option like the following?

```
install(TARGETS ${PROJECT_NAME}
        RUNTIME DESTINATION bin
        LIBRARY DESTINATION lib
        ARCHIVE DESTINATION lib
        HEADERS DESTINATION include)
```

**Comment by NancyLi1013** [comment]
Factually, both of them are okay.
Please refer to the following documents:
[1] https://stackoverflow.com/questions/60736689/cmake-target-sources-and-install
[2] https://stackoverflow.com/questions/57797459/cmake-how-to-installdirectory-in-installtargets

**Comment by 67-al-ahad** [comment]
Thank you for the clarification CMake is a strange beast to handle.

**Comment by NancyLi1013** [comment]
Please let me know if you have other questions about this issue.

**Comment by 67-al-ahad** [comment]
This seems to be clear for me right now. I am happy with the end result. Thank you I do appreciate your assitance.

In Future I can directly use **HEADERS DESTINATION include**

**Comment by NancyLi1013** [comment]
Of course you can use it if  you have known about how to use it.

I'm closing this issue for now. Please open a new issue if you have any other issues when using vcpkg in the future.
