### ISSUE TITLE
[libigl] missing headers

### ISSUE THREAD

**Issue by soroush** [microsoft/vcpkg#11986]
**Host Environment**
- OS: Windows
- Compiler: MSCV 14.2 (2019) amd64

**To Reproduce**
`./vcpkg install libigl[opengl,glfw,imgui]`
The library compiles but partially installs. Headers at `igl/opengl` are missing.

**Description**
So, I am planning to use libigl's 3D [viewer](https://github.com/libigl/libigl/blob/master/include/igl/opengl/glfw/Viewer.h) which must be available if you enable OpenGL and glfw features at compile time. However, doing so, vcpkg does not install headers at `igl/opengl` and `igl/opengl/glfw` subdirectories at all.

**Comment by JackBoosY** [comment]
Will be fixed in #10252

**Comment by deGravity** [comment]
This was not fixed in [#10252](https://github.com/microsoft/vcpkg/pull/10252)

**Comment by deGravity** [comment]
[#13424](https://github.com/microsoft/vcpkg/pull/13424) fixes the issue for opengl, but not for opengl_glfw or opengl_glfw_imgui. Those headers are in further nested sub-directories that do not get installed. I think you need to also add something like:

```
if (LIBIGL_WITH_OPENGL_GLFW OR LIBIGL_WITH_OPENGL_GLFW_IMGUI)
   install_dir_files(opengl/glfw)
endif()

if (LIBIGL_WITH_OPENGL_GLFW_IMGUI)
    install_dir_files(opengl/glfw/imgui)
endif()
```

**Comment by JackBoosY** [comment]
@deGravity I did not expect `install_dir_files` to install files recursively.

**Comment by deGravity** [comment]
@JackBoosY No, it does not, but when opengl_glfw and/or opengl_glfw_imgui are selected, those sub-directories also need to be installed (they contain the only relevant headers). I've tried making a patch to fix this, but I'm not familiar with how to create patches for vcpkg so I haven't been able to test it yet.

**Comment by JackBoosY** [comment]
@deGravity Will fix later.

**Comment by deGravity** [comment]
Thanks! I've gotten the [patch](https://github.com/deGravity/vcpkg/commit/b09a5757b1c526f75afc0a4a9017cf848cf93911) working locally for myself now if it's helpful to you:

**Comment by JackBoosY** [comment]
@deGravity  fixed and merged. Please update vcpkg.
