### ISSUE TITLE
[skia] Linux porting works fine, maybe we should enable the build?

### ISSUE THREAD

**Issue by psionic12** [microsoft/vcpkg#11985]
I just enabled the build of skia on Linux(by removing the "LINUX" in vcpkg_fail_port_install in ports/skia/portfile.cmake), and it builds and works fine, I got 2D graphic on my screen.

So can we consider to enable it on Linux?

P.S. I add `fontconfig` and `bz2` manually in my cmake in order to build the an example, don't know this is a problem or not.

**Comment by NancyLi1013** [comment]
Hi @psionic12 
Thanks for posting this issue.
I have tried and `skia `can be built successfully on my machine. So it should have support Linux.
As for `fontconfig `and `bz2`, do you need these two ports to build example by yourself?

**Comment by psionic12** [comment]
I just coped an example from somewhere:
```
#include "GLFW/glfw3.h"
#include "skia/gpu/GrBackendSurface.h"
#include "skia/gpu/GrContext.h"
#include "skia/gpu/gl/GrGLInterface.h"
#include "skia/core/SkCanvas.h"
#include "skia/core/SkColorSpace.h"
#include "skia/core/SkSurface.h"
#include <stdio.h>
#include <stdlib.h>

//uncomment the two lines below to enable correct color spaces
//#define GL_FRAMEBUFFER_SRGB 0x8DB9
//#define GL_SRGB8_ALPHA8 0x8C43

GrContext *sContext = nullptr;
SkSurface *sSurface = nullptr;

void error_callback(int error, const char *description) {
  fputs(description, stderr);
}

void key_callback(GLFWwindow *window, int key, int scancode, int action, int mods) {
  if (key == GLFW_KEY_ESCAPE && action == GLFW_PRESS)
    glfwSetWindowShouldClose(window, GL_TRUE);
}

void init_skia(int w, int h) {
  GrContextOptions options;
  //options.fRequireDecodeDisableForSRGB = false; //was removed?
  sContext = GrContext::MakeGL(nullptr, options).release();

  GrGLFramebufferInfo framebufferInfo;
  framebufferInfo.fFBOID = 0; // assume default framebuffer
  // We are always using OpenGL and we use RGBA8 internal format for both RGBA and BGRA configs in OpenGL.
  //(replace line below with this one to enable correct color spaces) framebufferInfo.fFormat = GL_SRGB8_ALPHA8;
  framebufferInfo.fFormat = GL_RGBA8;

  SkColorType colorType;

  colorType = kBGRA_8888_SkColorType;

  GrBackendRenderTarget backendRenderTarget(w, h,
                                            0, // sample count
                                            0, // stencil bits
                                            framebufferInfo);

  //(replace line below with this one to enable correct color spaces) sSurface = SkSurface::MakeFromBackendRenderTarget(sContext, backendRenderTarget, kBottomLeft_GrSurfaceOrigin, colorType, SkColorSpace::MakeSRGB(), nullptr).release();
  sSurface = SkSurface::MakeFromBackendRenderTarget(sContext,
                                                    backendRenderTarget,
                                                    kBottomLeft_GrSurfaceOrigin,
                                                    colorType,
                                                    nullptr,
                                                    nullptr).release();
  if (sSurface == nullptr) abort();
}

void cleanup_skia() {
  delete sSurface;
  delete sContext;
}

const int kWidth = 960;
const int kHeight = 640;

int main(void) {
  GLFWwindow *window;
  glfwSetErrorCallback(error_callback);
  if (!glfwInit()) {
    exit(EXIT_FAILURE);
  }

  glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
  glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 2);
  glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);
  glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
  //(uncomment to enable correct color spaces) glfwWindowHint(GLFW_SRGB_CAPABLE, GL_TRUE);
  glfwWindowHint(GLFW_STENCIL_BITS, 0);
  //glfwWindowHint(GLFW_ALPHA_BITS, 0);
  glfwWindowHint(GLFW_DEPTH_BITS, 0);

  window = glfwCreateWindow(kWidth, kHeight, "Simple example", NULL, NULL);
  if (!window) {
    glfwTerminate();
    exit(EXIT_FAILURE);
  }
  glfwMakeContextCurrent(window);
  //(uncomment to enable correct color spaces) glEnable(GL_FRAMEBUFFER_SRGB);

  init_skia(kWidth, kHeight);

  glfwSwapInterval(1);
  glfwSetKeyCallback(window, key_callback);

  // Draw to the surface via its SkCanvas.
  SkCanvas *canvas = sSurface->getCanvas(); // We don't manage this pointer's lifetime.

  while (!glfwWindowShouldClose(window)) {
    glfwWaitEvents();
    SkPaint paint;
    paint.setColor(SK_ColorWHITE);
    canvas->drawPaint(paint);
    paint.setColor(SK_ColorBLUE);
    canvas->drawRect({100, 200, 300, 500}, paint);
    sContext->flush();

    glfwSwapBuffers(window);
  }

  cleanup_skia();

  glfwDestroyWindow(window);
  glfwTerminate();
  exit(EXIT_SUCCESS);
}
```

I don't think I need `fontconfig` and `bz2` in this example though.

**Comment by psionic12** [comment]
This look like similar when I use assimp on linux, in which case I have to add `libz` and `irrxml` manually.

**Comment by NancyLi1013** [comment]
If you don't add `fontconfig  `and `bz2 `, what is the error like?

**Comment by psionic12** [comment]
/home/liu/source/vcpkg/installed/x64-linux/debug/lib/libfreetyped.a(ftbzip2.c.o): In function `ft_bzip2_file_init':
/home/liu/source/vcpkg/buildtrees/freetype/src/2.10.1-ea10bbeefe/src/bzip2/ftbzip2.c:178: undefined reference to `BZ2_bzDecompressInit'
/home/liu/source/vcpkg/installed/x64-linux/debug/lib/libfreetyped.a(ftbzip2.c.o): In function `ft_bzip2_file_done':
/home/liu/source/vcpkg/buildtrees/freetype/src/2.10.1-ea10bbeefe/src/bzip2/ftbzip2.c:193: undefined reference to `BZ2_bzDecompressEnd'
/home/liu/source/vcpkg/installed/x64-linux/debug/lib/libfreetyped.a(ftbzip2.c.o): In function `ft_bzip2_file_reset':
/home/liu/source/vcpkg/buildtrees/freetype/src/2.10.1-ea10bbeefe/src/bzip2/ftbzip2.c:222: undefined reference to `BZ2_bzDecompressEnd'
/home/liu/source/vcpkg/buildtrees/freetype/src/2.10.1-ea10bbeefe/src/bzip2/ftbzip2.c:233: undefined reference to `BZ2_bzDecompressInit'
/home/liu/source/vcpkg/installed/x64-linux/debug/lib/libfreetyped.a(ftbzip2.c.o): In function `ft_bzip2_file_fill_output':
/home/liu/source/vcpkg/buildtrees/freetype/src/2.10.1-ea10bbeefe/src/bzip2/ftbzip2.c:304: undefined reference to `BZ2_bzDecompress'
/home/liu/source/vcpkg/installed/x64-linux/debug/lib/libfontconfig.a(fcfreetype.c.o): In function `FcGetPixelSize':
/home/liu/source/vcpkg/buildtrees/fontconfig/src/2.12.4-4b62bc356f/src/fcfreetype.c:1106: undefined reference to `FT_Get_BDF_Property'
/home/liu/source/vcpkg/installed/x64-linux/debug/lib/libfontconfig.a(fcfreetype.c.o): In function `FcFreeTypeQueryFace':
/home/liu/source/vcpkg/buildtrees/fontconfig/src/2.12.4-4b62bc356f/src/fcfreetype.c:1742: undefined reference to `FT_Get_BDF_Property'
/home/liu/source/vcpkg/buildtrees/fontconfig/src/2.12.4-4b62bc356f/src/fcfreetype.c:1749: undefined reference to `FT_Get_BDF_Property'
/home/liu/source/vcpkg/buildtrees/fontconfig/src/2.12.4-4b62bc356f/src/fcfreetype.c:1772: undefined reference to `FT_Get_BDF_Property'
/home/liu/source/vcpkg/buildtrees/fontconfig/src/2.12.4-4b62bc356f/src/fcfreetype.c:1867: undefined reference to `FT_Get_BDF_Property'
/home/liu/source/vcpkg/installed/x64-linux/debug/lib/libfontconfig.a(fcfreetype.c.o):/home/liu/source/vcpkg/buildtrees/fontconfig/src/2.12.4-4b62bc356f/src/fcfreetype.c:1888: more undefined references to `FT_Get_BDF_Property' follow
/home/liu/source/vcpkg/installed/x64-linux/debug/lib/libfontconfig.a(fcxml.c.o): In function `FcConfigMessage':
/home/liu/source/vcpkg/buildtrees/fontconfig/src/2.12.4-4b62bc356f/src/fcxml.c:574: undefined reference to `XML_GetCurrentLineNumber'
/home/liu/source/vcpkg/buildtrees/fontconfig/src/2.12.4-4b62bc356f/src/fcxml.c:577: undefined reference to `XML_GetCurrentLineNumber'
/home/liu/source/vcpkg/installed/x64-linux/debug/lib/libfontconfig.a(fcxml.c.o): In function `FcConfigParseAndLoad':
/home/liu/source/vcpkg/buildtrees/fontconfig/src/2.12.4-4b62bc356f/src/fcxml.c:3311: undefined reference to `XML_ParserCreate'
/home/liu/source/vcpkg/buildtrees/fontconfig/src/2.12.4-4b62bc356f/src/fcxml.c:3323: undefined reference to `XML_SetUserData'
/home/liu/source/vcpkg/buildtrees/fontconfig/src/2.12.4-4b62bc356f/src/fcxml.c:3325: undefined reference to `XML_SetDoctypeDeclHandler'
/home/liu/source/vcpkg/buildtrees/fontconfig/src/2.12.4-4b62bc356f/src/fcxml.c:3326: undefined reference to `XML_SetElementHandler'
/home/liu/source/vcpkg/buildtrees/fontconfig/src/2.12.4-4b62bc356f/src/fcxml.c:3327: undefined reference to `XML_SetCharacterDataHandler'
/home/liu/source/vcpkg/buildtrees/fontconfig/src/2.12.4-4b62bc356f/src/fcxml.c:3333: undefined reference to `XML_GetBuffer'
/home/liu/source/vcpkg/buildtrees/fontconfig/src/2.12.4-4b62bc356f/src/fcxml.c:3350: undefined reference to `XML_ParseBuffer'
/home/liu/source/vcpkg/buildtrees/fontconfig/src/2.12.4-4b62bc356f/src/fcxml.c:3353: undefined reference to `XML_GetErrorCode'
/home/liu/source/vcpkg/buildtrees/fontconfig/src/2.12.4-4b62bc356f/src/fcxml.c:3353: undefined reference to `XML_ErrorString'
/home/liu/source/vcpkg/buildtrees/fontconfig/src/2.12.4-4b62bc356f/src/fcxml.c:3362: undefined reference to `XML_ParserFree'

**Comment by psionic12** [comment]
Here's my CMakeLists.txt:

```
cmake_minimum_required(VERSION 3.16)
project(skia_test)

set(CMAKE_CXX_STANDARD 14)
find_package(skia CONFIG REQUIRED)
find_package(glfw3 CONFIG REQUIRED)




add_executable(skia_test main.cpp)
target_link_libraries(skia_test PRIVATE fontconfig bz2 skia::skia)
target_link_libraries(skia_test PRIVATE glfw)
```

**Comment by NancyLi1013** [comment]
I probably see why you will meet this. But I'm not familiar with `gn`, so I also don't know how to fix this.
@vejmartin 
Could you please help take a look?

**Comment by vejmartin** [comment]
The first error seems to be due to not accounting for cases where `freetype` might have previously been built with `bz2` enabled. `skia` has `freetype[core]` in the `CONTROL` file, and the `GN` configuration doesn't require `bz2`.

The second error (`fontconfig`) might be due to a bug in the `set_dependencies` function of `ports/skia/skiaConfig.cmake.in`. The `fontconfig` dependency is also not currently being replaced in the `GN` build (see `replace_skia_dep` in `ports/skia/portfile.cmake` and `skia/third_party/BUILD.gn`).
