### ISSUE TITLE
Towards qt5.9 vcpkg

### ISSUE THREAD

**Issue by bagong** [microsoft/vcpkg#1200]
Is it okay to open an issue for something not available yet, just to collect opinions and experiences for a plan to get qt5.9 (which was released today) into vcpkg. Qt5.9 is planned to be a long term support release, so both a landmark in Qt development, and at some point a challenge to vcpkg's single version policy ;)

Obvious weaknesses I have found in the Qt5.8 vcpkg version:

- the private header paths are not generated in the cmake configuration files for the modules (share/cmake ...)
- qt's policy to provide libraries with the `d` suffix, and vcpk's to use a distinct folder `debug` seem to conflict in subtle ways, like not finding the debug libraries, or - if setting the debug folder as prefix - not finding headers, and some more
- static build does not work (but is also not provided by Qt itself)

There must be less obvious problems as my results trying to build against vcpkg's Qt cause quite a few weird errors (while the official distro works). In another thread it was mentioned that Qt should be built insource build, otherwise problems (e.g. missing generation of private header paths) will result. So maybe this is another aspect in which Qt conflicts with overall design decisions of vcpkg.

Otoh I think a vcpkg-Qt will be very useful. From my Mac experience I can say that we never bother to look at the original Qt distribution but go straight to homebrew. Those versions are patched for macos, give options (e.g. webkit, db-support) and are integrated into an popular overall workflow to retrieve libraries. Qt5.9 is not distributed in a msvc_2017 32-bit version (win32/non-uwp), another desideratum vcpkg could fill. And of course we want a coherent Qt in the mix if we build using other vcpkg libraries.

**Comment by Fleischner** [comment]
If you upgrade the portfile: At the moment Qt5 copies its cmake files to /share/cmake instead of /share/qt5/cmake

**Comment by NancyLi1013** [comment]
Hi @bagong, thanks for posting this issue. qt5 has been upgraded to version 5.12.3 now. The current states about qt5 are as follows:
1. when building qt5, the libraries will be added with the `d` suffix in `debug` folder.
2. qt5 supports on Linux and OSX.
3. qt5 supports static build.

For the cmake configuration files, they are still copied to _share/port/cmake_.  Normally ports copy their cmake files to _share/port/cmake_.

**Comment by bagong** [comment]
Thanks, @NancyLi1013. I've been out of the loop for quite a while, I wasn't even aware this issue was still open. Happy to close. Thanks again!
