### ISSUE TITLE
[GLFW3] Failure to link to projects

### ISSUE THREAD

**Issue by rigo2798** [microsoft/vcpkg#12003]
**Host Environment**
- OS: [Windows
- Compiler: revision

**To Reproduce**
`./vcpkg install glfw3 

**Failure logs** 
Source.obj : error LNK2019: unresolved external symbol __imp__glClear@4 referenced in function _main

fatal error LNK1120: 1 unresolved externals

**Comment by JackBoosY** [comment]
Hi @rigo2798, thanks for reporting this issue!
I can't repro it on my machine, could you add `Opengl32.lib` to the Additional Depdendencies list and try again?

Thanks.

**Comment by rigo2798** [comment]
thankyou so much that seems to be the problem :) @JackBoosY
