### ISSUE TITLE
[vcpkg] Vcpkg general is invalid with visual studio 2015

### ISSUE THREAD

**Issue by zh1an** [microsoft/vcpkg#12002]
**Describe the bug**
General of Vcpkg with visual studio 2015 is error. The `Package install directory` option is `$(VcpkgRoot)\installed\$(VcpkgUserTriplet)\` which is translated to `F:\vcpkg\\installed\-windows\` and this is illegal. I have rebuild vcpkg and still not working.

**Environment**
- OS: Windows 10
- Compiler: msvc 2015

**To Reproduce**
1. ./vcpkg install xxxx
2. See error
Repro code when

**Expected behavior**
I cannot build with any libraries that installed by vcpkg.

**Failure logs** 
-(please attached failure logs)

**Additional context**
![image](https://user-images.githubusercontent.com/30436038/84987647-2185e580-b173-11ea-8463-187300294978.png)

**Comment by zh1an** [comment]
`Package install directory` should be translated to `F:\vcpkg\installed\x86-windows\` on my PC.

**Comment by NancyLi1013** [comment]
Hi @zh1an 
Thanks for posting this issue.
Could you please help confirm if you used Visual Studio 2015 Update 3 or newer?
Have you run the command `vcpkg integrate install` or `vcpkg integrate project` before you used any ports?

**Comment by zh1an** [comment]
> Hi @zh1an
> Thanks for posting this issue.
> Could you please help confirm if you used Visual Studio 2015 Update 3 or newer?
> Have you run the command `vcpkg integrate install` or `vcpkg integrate project` before you used any ports?

Hi @NancyLi1013 
Yes, I used Visual Studio 2015 Update 3 and I run `vcpkg integrate install` command before I open visual studio project.

PS: My windows version is Chinese version. When I install `zlib`, I need to install English package for Visual Studio. Then I installed package and change Visual Studio 2015 IDE env to English. After these operation, the Visual Studio with vcpkg is working with something wrong. I did lots of things such as redownloading vcpkg, reinstall integrate etc., it was still not working. Just now, I changed Visual Studio IDE env to Chinese, and reinstall integrate, it is working normally.

**Comment by NancyLi1013** [comment]
@zh1an 
Thanks for trying to do these operations many times.
From what you have done, we might know that this is related with the Visual Studio environment.
In fact, we only need to install English package for Visual Studio whatever the local Languages are. As for the Visual Studio IDE env, we just keep it as the original language.
