### ISSUE TITLE
uwebsockets/libuv broken?

### ISSUE THREAD

**Issue by daef** [Microsoft/vcpkg#1201]
I've tried compiling a project using uwebsockets from vcpkg (uwebsockets port installed without problems)

now using the library threw up

    vcpkg\installed\x64-windows\include\uws\Hub.h(52): error C2039: 'preCbData': is not a member of 'Loop'
    vcpkg\installed\x64-windows\include\uws\Libuv.h(7): note: see declaration of 'Loop'

during compilation. 

Peeking into `uWS/Hub.h` it looks like this preCbData field is needed when compiling with UWS_THREADSAFE

Further it seems like only one Loop-Struct out of the three available eventloop implementations (namely Epoll.h) contains the field preCbData - the other two (Libuv.h and Asio.h) are missing it.

A quick search threw up https://github.com/uNetworking/uWebSockets/issues/566 which seems somewhat related.

Any guides on how to use vcpkg to build a usable version of uws? Or do I use this wrong?

EDIT:

I just found a `#define UWS_THREADSAFE` in the code I'm trying to compile - I guess that's the problem.

**Comment by ad34** [comment]
does this actually means that we can't compile uWebSockets with thread safe support on windows?

**Comment by daef** [comment]
Nope. This means that UWS_THREADSAFE is not needed on windows to get thread safety.
