### ISSUE TITLE
[New Port Request] OpenMW

### ISSUE THREAD

**Issue by Pospelove** [microsoft/vcpkg#12012]
Port name: OpenMW

Port description: OpenMW is an open-source open-world RPG game engine that supports playing Morrowind. 

Source repository URL: https://github.com/OpenMW/openmw

Project homepage (if different from the source repository): http://openmw.org/en/

Anything else that is useful to know when adding (such as optional features the library may have that should be included): 
https://wiki.openmw.org/index.php?title=Development_Environment_Setup

Requires https://github.com/microsoft/vcpkg/pull/11991

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
