### ISSUE TITLE
[New Port Request] ChakraCoreCppBridge

### ISSUE THREAD

**Issue by Pospelove** [microsoft/vcpkg#12016]
Library name: ChakraCoreCppBridge

Library description: A convenient C++ wrapper for C-style API provided by Microsoft ChakraCore library.

Source repository URL: https://github.com/AlexBAV/ChakraCoreCppBridge

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
