### ISSUE TITLE
[abseil:x64-windows] DLL Linker Error

### ISSUE THREAD

**Issue by abcping123** [microsoft/vcpkg#12021]
**Environment**
- OS: [Windows 10 v1903]
- Compiler: Visual Studio 2017

It is fine to build abseil dll, but when I use it in my project, some annoying linker errors ocurr.
And I find this in `absl/base/config.h`

// ABSL_DLL
//
// When building Abseil as a DLL, this macro expands to `__declspec(dllexport)`
// so we can annotate symbols appropriately as being exported. When used in
// headers consuming a DLL, this macro expands to `__declspec(dllimport)` so
// that consumers know the symbol is defined inside the DLL. In all other cases,
// the macro expands to nothing.
#if defined(_MSC_VER)
#if defined(ABSL_BUILD_DLL)
#define ABSL_DLL __declspec(dllexport)
#elif defined(ABSL_CONSUME_DLL)
#define ABSL_DLL __declspec(dllimport)
#else
#define ABSL_DLL
#endif
#else
#define ABSL_DLL
#endif  // defined(_MSC_VER)

I put `ABSL_CONSUME_DLL` into preprocessor definitions, and it works.

I don't know whether it is bug, or work should be done by library users.

**Comment by JackBoosY** [comment]
@abcping123 That's indeed a bug, thanks for reporting this!

**Comment by abcping123** [comment]
@JackBoosY  It is really quick response, thanks!
