### ISSUE TITLE
[abseil:x64-windows] Errors In Using DLL

### ISSUE THREAD

**Issue by abcping123** [microsoft/vcpkg#12028]
**Environment**
- OS: [Windows 10 v1903]
- Compiler: Visual Studio 2017

I built abseil dll first time today, while it was static library before.

And I try out a very simple test code:

#include    <iostream>
#include    <absl/strings/str_cat.h>

int main(int argc, char* argv[])
{
    std::string s = absl::StrCat("hello,", "world!");
    std::cout << s << std::endl;
    return 0;
}

It is broken, actually it is fine within `absl::StrCat()`, and return the result `hello,world!`, but it fails to pass that to `std::string`.

Not only `absl::StrCat()`, I tested many other abseil string operations, they all failed.

And I rollback vcpkg to `2020.04` version, to rebuild the abseil static library, it works fine now.

I checkout abseil homepage, and find [Abseil Compatibility Guidelines](https://abseil.io/about/compatibility), maybe this could help.

**Comment by JackBoosY** [comment]
Hi @abcping123, thanks for reporting this issue.
Does my PR #12022 fixed this issue?

**Comment by abcping123** [comment]
@JackBoosY That is also my reported issue, lack of `ABSL_CONSUME_DLL` would prevents compilation.

By the way, I just find this issue only occurs in `Debug` mode (VS2017 default, /MDd), It is fine in `Release` mode.

**Comment by abcping123** [comment]
@JackBoosY That is also my reported issue, lack of `ABSL_CONSUME_DLL`  would prevents compilation.

By the way, I just find this issue only occurs in `Debug` mode(vs2017 default settings /MDd) , and it works well in `Release` mode.

**Comment by abcping123** [comment]
@JackBoosY My fault, I put both `bin` and `debug/bin` into environment variables, while `abseil` DLLs has the same name, then error ocurrs ...

Anyway, thanks for attention, I will close this issue.
