### ISSUE TITLE
Extremely slow building of GDAL

### ISSUE THREAD

**Issue by cyang-kth** [microsoft/vcpkg#12027]
When I run vcpkg on appveyor to install gdal, it takes about 33 minutes. Anyone know why it takes so long and how can it be accelerated?

```
Starting package 19/19: gdal:x86-windows
Building package gdal[core]:x86-windows...
-- Downloading http://download.osgeo.org/gdal/2.4.1/gdal241.zip...
-- Extracting source C:/Tools/vcpkg/downloads/gdal241.zip
-- Applying patch 0001-Fix-debug-crt-flags.patch
-- Applying patch 0003-Fix-std-fabs.patch
-- Extracting source C:/Tools/vcpkg/downloads/gdal241.zip
-- Applying patch 0001-Fix-debug-crt-flags.patch
-- Applying patch 0003-Fix-std-fabs.patch
-- Building x86-windows-rel
-- Building x86-windows-rel done
-- Building x86-windows-dbg
-- Building x86-windows-dbg done
-- Packaging x86-windows
-- Performing post-build validation
-- Performing post-build validation done
Building package gdal[core]:x86-windows... done
Installing package gdal[core]:x86-windows...
Installing package gdal[core]:x86-windows... done
Elapsed time for package gdal:x86-windows: 33.26 min
```

https://ci.appveyor.com/project/cyang-kth/fmm/builds/33620877#L4414

**Comment by cyang-kth** [comment]
Maybe the reason is that downloading the GDAL from http://download.osgeo.org/gdal/2.4.1/gdal241.zip is extremely slow. 

From the log, it takes about 25 minutes.

**Comment by cyang-kth** [comment]
It also seems that all library whose mirror is not on Github takes extremely long time to download. (Tens of minutes against seconds). Maybe this is an issue with the server of appveyor. Is there a way to manually define a mirror?

**Comment by cyang-kth** [comment]
I notice that the same way of installing the dependencies in cygwin is much faster perhaps because they have their own mirror to download the required packages. Is it possible to have a server to host the libraries similar as vcpkg?

**Comment by JackBoosY** [comment]
@cyang-kth We have plans to add mirrors, but not now.
