### ISSUE TITLE
[harfbuzz] cannot upgrade from 2.5.3.1 to 2.6.6

### ISSUE THREAD

**Issue by jepessen** [microsoft/vcpkg#12029]
**Describe the bug**
I want to upgrade my vcpkg installation where harfbuzz is installed. I've pulled the repository and I call vcpkg update, and harfbuzz appears there
```
> vcpkg.exe update
....
harfbuzz:x64-windows   2.5.3.1 -> 2.6.6
...
```
When I call the updagrade command I obtain following error
```
Package harfbuzz does not have a ucdn feature
```
so I cannot upgrade. Probably I can remove and add the package but I've a lot of packages installed and it will be troublesome to reinstall all. vcpkg should be able to handle missing features during update and simply write a message and the update the package without using the missing feature

**Environment**
- OS: Windows 10 64 bit
- Compiler: Visual studio 2019

**Comment by timautry** [comment]
You will need to do the following steps:
1. `vcpkg remove harfbuzz --recurse` 
2. `vcpkg install harfbuzz[features]` and any other ports that were removed in step 1.
The ucdn feature was eliminated from the port between the version upgrade.

**Comment by JackBoosY** [comment]
I think we should consider the scenes like this.

**Comment by PhoebeHui** [comment]
Closing in favor of https://github.com/microsoft/vcpkg/issues/11482.
