### ISSUE TITLE
breakpad:x64-linux include file error

### ISSUE THREAD

**Issue by aiyou4love** [microsoft/vcpkg#12025]
/mnt/c/setup/vcpkg/vcpkg/installed/x64-linux/include/common/memory_allocator.h:50:10: fatal error: third_party/lss/linux_syscall_support.h: No such file or directory
 #include "third_party/lss/linux_syscall_support.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

CMakeLists.txt:
cmake_minimum_required(VERSION 3.10)
project(startup)

include_directories(${VCPKG_ROOT}/include)
link_directories(${VCPKG_ROOT}/lib)
aux_source_directory(. SRC)
add_executable(startup ${SRC})

Main.cpp:

#include <client/linux/handler/exception_handler.h>

int main(int argc, char* argv[])
{
    return 0;
}

build.sh:

PRJ_CFG=Debug
VCPKG_ROOT=/mnt/c/setup/vcpkg/vcpkg/installed/x64-linux
cd build.amd64
cmake .. -DVCPKG_ROOT=$VCPKG_ROOT
cmake --build . --config $PRJ_CFG

**Comment by NancyLi1013** [comment]
Hi @aiyou4love 
Thanks for posting this issue.
Since `linux_syscall_support` is currently not available in vcpkg. 
We need to add this first.
https://github.com/linux-on-ibm-z/linux-syscall-support

**Comment by aiyou4love** [comment]
Thanks for your update.
