### ISSUE TITLE
[openni2] Could not find <cor.h>.  Ensure the NETFXSDK is installed.

### ISSUE THREAD

**Issue by WangZP10969** [microsoft/vcpkg#12039]
**Host Environment**
- OS: Windows x64
- Compiler: Visual Studio 2019

**To Reproduce**
C:\vcpkg-master\vcpkg.exe install pcl[openni2,qt,pcap,tools,opengl]:x64-windows

**Failure logs** 
Installing package netcdf-c[core]:x64-windows... done
Elapsed time for package netcdf-c:x64-windows: 2.944 min
Starting package 133/150: openni2:x64-windows
Building package openni2[core]:x64-windows...
CMake Error at ports/openni2/portfile.cmake:9 (message):
  Could not find <cor.h>.  Ensure the NETFXSDK is installed.
Call Stack (most recent call first):
  scripts/ports.cmake:76 (include)

Error: Building package openni2:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openni2:x64-windows
  Vcpkg version: 2020.02.04-nohash

Additionally, attach any relevant sections from the log files above.

**Additional context**

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Please confirm you have installed a version of .NET Framework SDK at 4.6.0 or higher on Visual Studio.

**Comment by WangZP10969** [comment]
@LilyWangL 
Thanks a lot, I noticed that I only installed C++ and did not include .net
