### ISSUE TITLE
How to link to 'SDL2main.lib' in Visual Studio 2019

### ISSUE THREAD

**Issue by panovr** [microsoft/vcpkg#12034]
Hi,
  I installed sdl2 by using vcpkg, and I created a new project in Visual Studio 2019.
  I added the statement:
  `#pragma comment(lib, "SDL2main.lib")`
  However, when building, there was still `Error	LNK1104	cannot open file 'SDL2main.lib'`

  It seems that `SDL2main.lib` was moved to `manual-link` folder, so how to link to 'SDL2main.lib' in Visual Studio 2019?

Reference: https://github.com/Microsoft/vcpkg/commit/3d8ba3e775c13816f4c298ba16b8094e2affc4dd

**Comment by linquize** [comment]
Try `manual-link\SDL2main.lib` ?
