### ISSUE TITLE
[cutelyst2, all Qt/CMake-based ports] build failure / x86-windows-static / FindFirstFileExA / Qt5 issue

### ISSUE THREAD

**Issue by kafeg** [microsoft/vcpkg#12038]
**Host Environment**
- OS: Windows
- Compiler:  dosen't matter, reproduces on all compilers: VS2015-VS2019

**To Reproduce**
`vcpkg.exe install --triplet x86-windows-static cutelyst2`

**Failure logs** 
D:\dev\uvcpkg\buildtrees\cutelyst2\install-x86-windows-static-dbg-err.log
```
ninja: error: FindFirstFileExA(d:/dev/uvcpkg/installed/x86-windows-static/debug/lib/qt5cored.lib "c:): The filename, directory name, or volume label syntax is incorrect.
```
**Additional context**
There is something wrong in Qt5-* ports on creating libraries list. When trying to build any related port which requires link Qt libs on `x86-windows-static`, always throws that error. 

It generates the wrong build.ninja file:

> ...
> LINK_LIBRARIES = D:\dev\uvcpkg\installed\x86-windows-static\lib\Qt5Core.lib  D:\dev\uvcpkg\installed\x86-windows-static\lib\Qt5Network.lib  Cutelyst\Cutelyst2Qt5.lib  wsgi\Cutelyst2Qt5Wsgi.lib  Cutelyst\Cutelyst2Qt5.lib  D:\dev\uvcpkg\installed\x86-windows-static\lib\Qt5Network.lib  D:\dev\uvcpkg\installed\x86-windows-static\lib\Qt5Core.lib  D:\dev\uvcpkg\installed\x86-windows-static\lib\zlib.lib  D:\dev\uvcpkg\installed\x86-windows-static\lib\pcre2-16.lib  D:\dev\uvcpkg\installed\x86-windows-static\lib\double-conversion.lib  D:\dev\uvcpkg\installed\x86-windows-static\lib\bz2.lib  D:\dev\uvcpkg\installed\x86-windows-static\lib\libpng16.lib  D:\dev\uvcpkg\installed\x86-windows-static\lib\libssl.lib  D:\dev\uvcpkg\installed\x86-windows-static\lib\libcrypto.lib  ws2_32.lib  secur32.lib  advapi32.lib  shell32.lib  crypt32.lib  user32.lib  gdi32.lib  D:\dev\uvcpkg\installed\x86-windows-static\lib\zlib.lib  D:\dev\uvcpkg\installed\x86-windows-static\lib\pcre2-16.lib  D:\dev\uvcpkg\installed\x86-windows-static\lib\double-conversion.lib  D:\dev\uvcpkg\installed\x86-windows-static\lib\bz2.lib  D:\dev\uvcpkg\installed\x86-windows-static\lib\libpng16.lib  D:\dev\uvcpkg\installed\x86-windows-static\lib\libssl.lib  D:\dev\uvcpkg\installed\x86-windows-static\lib\libcrypto.lib  ws2_32.lib  secur32.lib  advapi32.lib  shell32.lib  crypt32.lib  user32.lib  gdi32.lib  "D:\dev\uvcpkg\installed\x86-windows-static\lib\Qt5Core.lib \"C:\\Program"  Files.lib  (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\mpr.lib" "C:\\Program.lib  (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\netapi32.lib" "C:\\Program.lib  (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\userenv.lib" "C:\\Program.lib  (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\version.lib" "C:\\Program.lib  (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\ws2_32.lib" "C:\\Program.lib  (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\kernel32.lib" "C:\\Program.lib  (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\user32.lib" "C:\\Program.lib  (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\shell32.lib" "C:\\Program.lib  (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\uuid.lib" "C:\\Program.lib  (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\ole32.lib" "C:\\Program.lib  (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\advapi32.lib" "C:\\Program.lib  (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\winmm.lib".lib  "C:\\Program.lib  (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\dnsapi.lib" "C:\\Program.lib  (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\iphlpapi.lib" "C:\\Program.lib  Files.lib  (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\mpr.lib" "C:\\Program.lib  (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\netapi32.lib" "C:\\Program.lib  (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\userenv.lib" "C:\\Program.lib  (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\version.lib" "C:\\Program.lib  (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\ws2_32.lib" "C:\\Program.lib  (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\kernel32.lib" "C:\\Program.lib  (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\user32.lib" "C:\\Program.lib  (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\shell32.lib" "C:\\Program.lib  (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\uuid.lib" "C:\\Program.lib  (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\ole32.lib" "C:\\Program.lib  (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\advapi32.lib" "C:\\Program.lib  (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\winmm.lib".lib  "C:\\Program.lib  (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\dnsapi.lib" "C:\\Program.lib  (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\iphlpapi.lib" "C:\\Program.lib  (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\crypt32.lib".lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib
> ...

Here you can see a lot of lines like: `"C:\\Program.lib  (x86)\\` and one line `"D:\dev\uvcpkg\installed\x86-windows-static\lib\Qt5Core.lib \"C:\\Program"  Files.lib  (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\mpr.lib"` which breakes linkage step with error `FindFirstFileExA` above.

Doesn't reproduced on `x86-windows` or `x64-windows-static`.

PS: I understand, the `x86-windows-static` is a community triplet, but I think it's important to inform other developers about this problem. I spent a lot of time to find the reasons. Trying to find solution =)

**Comment by kafeg** [comment]
Probably the error is inside some regex and replacements in the `function(_qt5_Core_parse_prl)` in `Qt5CoreConfig.cmake`. It generates lines like `"C:\\Program;Files;(x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\mpr.lib"` with `;` in `C:\\Program;Files;(x86)`.

E.g. from:
> -- QMAKE_PRL_LIBS as a list 2 : -L$$[QT_INSTALL_LIBS] ;-L$$[QT_INSTALL_LIBS]/manual-link;  "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\mpr.lib" "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\netapi32.lib" "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\userenv.lib" "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\version.lib" "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\ws2_32.lib" "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\kernel32.lib" "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\user32.lib" "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\shell32.lib" "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\uuid.lib" "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\ole32.lib" "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\advapi32.lib" "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\winmm.lib" $$[QT_INSTALL_LIBS]/zlib.lib $$[QT_INSTALL_LIBS]/pcre2-16.lib $$[QT_INSTALL_LIBS]/double-conversion.lib $$[QT_INSTALL_LIBS]/bz2.lib $$[QT_INSTALL_LIBS]/libpng16.lib

to:
> -- QMAKE_PRL_LIBS as a list 3 : -L$$[QT_INSTALL_LIBS]; ;-L$$[QT_INSTALL_LIBS]/manual-link;  ; "C:\\Program; Files ; (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\mpr.lib" "C:\\Program; Files ; (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\netapi32.lib" "C:\\Program; Files ; (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\userenv.lib" "C:\\Program; Files ; (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\version.lib" "C:\\Program; Files ; (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\ws2_32.lib" "C:\\Program; Files ; (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\kernel32.lib" "C:\\Program; Files ; (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\user32.lib" "C:\\Program; Files ; (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\shell32.lib" "C:\\Program; Files ; (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\uuid.lib" "C:\\Program; Files ; (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\ole32.lib" "C:\\Program; Files ; (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\advapi32.lib" "C:\\Program; Files ; (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\winmm.lib"; $$[QT_INSTALL_LIBS]/zlib.lib ; $$[QT_INSTALL_LIBS]/pcre2-16.lib; $$[QT_INSTALL_LIBS]/double-conversion.lib ; $$[QT_INSTALL_LIBS]/bz2.lib; $$[QT_INSTALL_LIBS]/libpng16.lib;

**Comment by kafeg** [comment]
A partial solution to add there: `vcpkg\installed\x86-windows-static\share\cmake\Qt5Core\Qt5CoreConfig.cmake` strings:
> string(REPLACE "Program;Files;(x86)" "Program Files (x86)" _static_depends "${_static_depends}")
> string(REPLACE ".lib\" " ".lib\"; " _static_depends "${_static_depends}")

after 

> string(REGEX REPLACE "[\t ]*;[\t ]*" ";" _static_depends "${_static_depends}")      # remove unnecessary whitespaces 

Also possible to add it to exists patch

This will fix cycle `foreach(_flag IN LISTS _static_depends)` but it's not full solution.

Cycle output before:
> lib_flag -L$$[QT_INSTALL_LIBS]
lib_flag -LD:/dev/uvcpkg/installed/x86-windows-static/lib/manual-link
lib_flag "C:\\Program
lib_flag Files
lib_flag (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\mpr.lib" "C:\\Program
lib_flag Files
lib_flag (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\netapi32.lib" "C:\\Program
lib_flag Files
lib_flag (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\userenv.lib" "C:\\Program
lib_flag Files
lib_flag (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\version.lib" "C:\\Program
lib_flag Files
lib_flag (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\ws2_32.lib" "C:\\Program
lib_flag Files
lib_flag (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\kernel32.lib" "C:\\Program
lib_flag Files
lib_flag (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\user32.lib" "C:\\Program
lib_flag Files
lib_flag (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\shell32.lib" "C:\\Program
lib_flag Files
lib_flag (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\uuid.lib" "C:\\Program
lib_flag Files
lib_flag (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\ole32.lib" "C:\\Program
lib_flag Files
lib_flag (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\advapi32.lib" "C:\\Program
lib_flag Files
lib_flag (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\winmm.lib"
lib_flag D:/dev/uvcpkg/installed/x86-windows-static/lib/zlib.lib
lib_flag D:/dev/uvcpkg/installed/x86-windows-static/lib/pcre2-16.lib
lib_flag D:/dev/uvcpkg/installed/x86-windows-static/lib/double-conversion.lib
lib_flag D:/dev/uvcpkg/installed/x86-windows-static/lib/bz2.lib
lib_flag D:/dev/uvcpkg/installed/x86-windows-static/lib/libpng16.lib
lib_flag 

Cycle output after:
> lib_flag -L$$[QT_INSTALL_LIBS]
lib_flag -LD:/dev/uvcpkg/installed/x86-windows-static/lib/manual-link
lib_flag "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\mpr.lib"
lib_flag  "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\netapi32.lib"
lib_flag  "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\userenv.lib"
lib_flag  "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\version.lib"
lib_flag  "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\ws2_32.lib"
lib_flag  "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\kernel32.lib"
lib_flag  "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\user32.lib"
lib_flag  "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\shell32.lib"
lib_flag  "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\uuid.lib"
lib_flag  "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\ole32.lib"
lib_flag  "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\advapi32.lib"
lib_flag  "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x86\\winmm.lib"
lib_flag D:/dev/uvcpkg/installed/x86-windows-static/lib/zlib.lib
lib_flag D:/dev/uvcpkg/installed/x86-windows-static/lib/pcre2-16.lib
lib_flag D:/dev/uvcpkg/installed/x86-windows-static/lib/double-conversion.lib
lib_flag D:/dev/uvcpkg/installed/x86-windows-static/lib/bz2.lib
lib_flag D:/dev/uvcpkg/installed/x86-windows-static/lib/libpng16.lib
lib_flag

Keep digging...

**Comment by kafeg** [comment]
Ok, the function `function(_qt5_$${CMAKE_MODULE_NAME}_parse_prl)` in patch https://github.com/microsoft/vcpkg/blob/master/ports/qt5-base/patches/prl_parser.patch is a very strange. Maybe maintainers could check their scripts.

My final temporary solution is - disable that patch before build qt5-base, like:

`sed -i 's/patches\/prl_parser.patch/#patches\/prl_parser.patch/g' ports/qt5-base/portfile.cmake`

You could close the issue if you think it's not important because affects only to community triplet `x86-windows-static`

@Neumann-A and @JackBoosY please take a look.

**Comment by Neumann-A** [comment]
Normally this should take care of it:
```
+    if(WIN32)
+         string(REGEX REPLACE \"-L\\\\\\\"([^\\\\\\\"]+)\\\\\\\"\" \" ;-L\\\"\\\\1\\\"; \" _static_depends \"${_static_depends}\") # -L Tricky Case with spaces
+         string(REGEX REPLACE [[\\\"?[A-Z]:\\\\\\\\Program Files( \\(x86\\))*\\\\\\\\Windows Kits\\\\\\\\[0-9]+\\\\\\\\lib\\\\\\\\[0-9|.]+\\\\\\\\um\\\\\\\\x64(\\\\\\\\|/)([^\\\"]+)\\\"?]] \";\\\\3;\" _static_depends \"${_static_depends}\")
+         string(REGEX REPLACE [[ \\\"([^\\"]+)\\\" ]] \" ;\\\"\\\\1\\\"; \" _static_depends \"${_static_depends}\") 
+         # Every path with a space in it should be handled now!
+    else()
+         string(REGEX REPLACE \" -l([^ ]+)\" [[;-l\\1;]] _static_depends \"${_static_depends}\") # - l case on targets other than windows
+    endif(
```
The question is thus why it is nor working

**Comment by kafeg** [comment]
Oh, and i used 5.12.8 for my needs.

**Comment by Adela0814** [comment]
the latest qt5 version is 5.15 and this issue have been fixed, please get the latest vcpkg.
