### ISSUE TITLE
[New Port Request] Tileson

### ISSUE THREAD

**Issue by shironecko** [microsoft/vcpkg#12035]
Library name: Tileson

Library description: C++17 library for parsing Tiled maps (https://www.mapeditor.org)

Source repository URL: https://github.com/SSBMTonberry/tileson

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
Tileson as of recent version supports single-header mode, so that might be easiest to integrate.
Also note that I'm not an author of the said library, just an interested user. I've discussed adding Tileson to vcpkg with the author and offered my help in doing so.

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
