### ISSUE TITLE
[Feature requrst] Set Ports search path by file

### ISSUE THREAD

**Issue by Akarinnnnn** [microsoft/vcpkg#12033]
****

**Is your feature request related to a problem? Please describe.**
No

**Proposed solution**
Read a file named portpath.txt under the instance root path, each line in the file meant an **additional** search path

**Describe alternatives you've considered**
vcpkg install(search...) package -ports PATH/TO/PORTS

**Additional context**
None

**Comment by traversaro** [comment]
If anyone is interested in such a feature, I implemented a prototype of it in https://github.com/microsoft/vcpkg/issues/10119#issuecomment-613115859 .

**Comment by JackBoosY** [comment]
Already implemented.
