### ISSUE TITLE
[tinyxml] have not tinyxml-config-debug.cmake

### ISSUE THREAD

**Issue by polelf** [microsoft/vcpkg#12032]
port tinyxml have not tinyxml-config-debug.cmake and tinyxml-config-release.cmake

**Comment by PhoebeHui** [comment]
@polelf, what do you mean? do you mean tinyxmlTargets-debug and tinyxmlTargets-release file? double checked, tinyxml already provide cmake config and targets file.

vcpkg\installed\x86-windows\share\tinyxml> dir
tinyxml-config.cmake
tinyxmlTargets-debug.cmake
tinyxmlTargets-release.cmake
tinyxmlTargets.cmake
vcpkg_abi_info.txt

**Comment by polelf** [comment]
it works
