### ISSUE TITLE
How to install PCL1.11.0+VTK8.2.0 or PCL1.9.1+VTK8.1.0?

### ISSUE THREAD

**Issue by WangZP10969** [microsoft/vcpkg#12042]
I am installing some packages, among which are PCL
Some other packages work fine, but because PCL does not currently support VTK9.0, Visualize cannot be installed.
The PCL update process may seem lengthy, so is there a way to install other versions of VTK?
I have tested that PCL1.9.1+VTK8.1.0 or PCL1.11.0+VTK8.2.0 can work normally, which is the officially recommended version of PCL
Therefore, I am thinking, whether it is possible to install VTK packages of other versions and repair the Visualize of PCl by certain means, even by directly copying or modifying files. In order to avoid other packages, I need to compile it myself
Would you give me some suggestions? thank you very much！

**Comment by JackBoosY** [comment]
You can use the following steps:
1. Backup _VCPKG_PATH/ports/pcl_
2. `./vcpkg x-history vtk`
3. `git reset ${VTK8.1_COMMIT_ID}`
4. Use the backup pcl to restore the pcl
5. Build pcl/VTK

There may be some problems with patch execution failure that you need to deal with yourself.

**Comment by WangZP10969** [comment]
> You can use the following steps:
> 
> 1. Backup _VCPKG_PATH/ports/pcl_
> 2. `./vcpkg x-history vtk`
> 3. `git reset ${VTK8.1_COMMIT_ID}`
> 4. Use the backup pcl to restore the pcl
> 5. Build pcl/VTK
> 
> There may be some problems with patch execution failure that you need to deal with yourself.

@JackBoosY  After I run it, the following error message appears. Is my operation wrong?
```
PS C:\Windows\system32> C:\vcpkg-master\vcpkg.exe x-history vtk
Failed to run command: "C:\vcpkg-master\downloads\tools\git-2.26.2-1-windows\mingw32\bin\git.exe" --git-dir="C:\vcpkg-master\.git" log --format="%H %cd" --date=short --left-only -- ports/vtk/.
```

**Comment by JackBoosY** [comment]
@WangZP10969 Please cd to  _VCPKG_PATH_ first.

**Comment by WangZP10969** [comment]
@JackBoosY 

Am I understanding right?  C:\vcpkg-master\downloads\tools\git-2.26.2-1-windows\mingw32\bin\git.exe is here
```
PS C:\vcpkg-master> .\vcpkg x-history vtk
Failed to run command: "C:\vcpkg-master\downloads\tools\git-2.26.2-1-windows\mingw32\bin\git.exe" --git-dir="C:\vcpkg-master\.git" log --format="%H %cd" --date=short --left-only -- ports/vtk/.
```

**Comment by JackBoosY** [comment]
That should be a permission issue.
Please use `git reset 8641dfd9dd6d3bf190515822060872a56ee37906` directly.

**Comment by WangZP10969** [comment]
> That should be a permission issue.
> Please use `git reset 8641dfd9dd6d3bf190515822060872a56ee37906` directly.
@JackBoosY 
Thank you very much, next I will try how to make it work
