### ISSUE TITLE
How do I properly include the sdl2pp port

### ISSUE THREAD

**Issue by dgengin** [microsoft/vcpkg#12041]
I'm using Visual Studio 2019 with vcpkg integrated. I can include any file installed by vcpkg. When I try to use the sdl2pp package, I get these errors:

```cpp
#include <SDL2/SDL_pixels.h>    // works - SDL2 is installed under includes/SDL2
#include <SDL2pp/Color.hh>     // doesn't work - it tries to include the file above without "SDL2/"
```

```
 fatal error C1083: Cannot open include file: 'SDL_pixels.h': No such file or directory
```

the `SDL2pp.dll` builds correctly, so vcpkg must be doing something different.

related issues:
https://github.com/libSDL2pp/libSDL2pp/pull/112
https://github.com/libSDL2pp/libSDL2pp/issues/88

Shouldn't the sdl2pp include files be modified to use the "SDL2/" folder in the includes?

**Comment by NancyLi1013** [comment]
Hi @dgengin 
Thanks for posting this issue.
Since `SDL_pixels.h` is listed in _include/SDL2_ directory. So we need to include `#include <SDL2/SDL_pixels.h>` in SDL2pp/Color.hh file.

I will try to fix it later.

**Comment by dgengin** [comment]
Hi. Thanks for looking at this.

I mentioned `Color.hh`, but to fix this, you need to alter all SDL2 included in all headers, not just this file.

I read about this and apparently, some use SDL2/*** others juse the header at the root include directory, which means if we use another system with a different package manager, these includes can be different.

They say the official way is to use it without the `SDL2` directory. The best way might to be to include the same files both inside SDL2 and the root and leave SDL1 in its own folder.

**Comment by NancyLi1013** [comment]
Thanks for your suggestions about this.
Since this issue appears in `msvc `project. You need to add the include path manually in your project. We cannot install headers outside SDL2. There are also some other ports that depend on `SDL2`. We should keep consistent with other ports.

**Comment by NancyLi1013** [comment]
I'm closing this issue for now since it needs to set path manually in the project.
