### ISSUE TITLE
gtk:x86-windows build failure

### ISSUE THREAD

**Issue by Nomade040** [microsoft/vcpkg#12048]
**Host Environment**
- OS: Windows

**To Reproduce**
vcpkg install gtk:x86-windows

**Failure logs** 
Package: gtk:x86-windows
Vcpkg version: 2020.02.04-nohash
[build.log](https://github.com/microsoft/vcpkg/files/4809893/build.log)

**Additional context**
Prior to installing gtk I uninstalled tiff:x64-windows and wxwidgets:x86-windows because of database corruption.

**Comment by JackBoosY** [comment]
Please unzip this [file](https://github.com/microsoft/vcpkg/files/4810887/gtk%2B-3.22.19.tar.xz.zip), put it to _VCPKG_PATH/downloads_ then rebuild gtk.

Thanks.

**Comment by Nomade040** [comment]
Thank you, it worked!
