### ISSUE TITLE
[sqlpp11-connector-mysql] revise control file 

### ISSUE THREAD

**Issue by abcping123** [microsoft/vcpkg#12040]
Default-Features: mariadb  // sqlpp11-connector-mysql, control(line 6)

This line should be deleted, otherwise feature `mysql` cannot be built.

**Comment by PhoebeHui** [comment]
@abcping123, thanks for reporting this issue!

libmariadb and libmysql are incompatible, so the mariadb and mysql can't be built together. However sqlpp11-connector-mysql depends on one of them, remove the default feature would block sqlpp11-connector-mysql, so I will revert the change in related PR https://github.com/microsoft/vcpkg/pull/11771/, @yurybura, is that okay for you?

**Comment by abcping123** [comment]
@PhoebeHui Actually `sqlpp11-connector-mysql` could be built with `libmysql` OR `libmariadb`,  [sqlpp11-connector-mysql requirements](https://github.com/rbock/sqlpp11-connector-mysql#requirements)
In my case, I manually remove Default-Features line, and build it with libmysql without errors.

**Comment by yurybura** [comment]
@PhoebeHui @abcping123 Please don't remove libmysql feature. It works) I saved mariadb as default feature PR #11771 for backward compatibility. Without default feature `sqlpp11-connector-mysql` doesn't make sense.
For install with mariadb use this command:
`vcpkg install sqlpp11-connector-mysql` or `vcpkg install sqlpp11-connector-mysql[core,mariadb]`
For install with mysql use this command:
`vcpkg install sqlpp11-connector-mysql[core,mysql]`

**Comment by PhoebeHui** [comment]
@yurybura, thanks for the information!

@abcping123, could you use vcpkg install sqlpp11-connector-mysql[core,mysql] instead to install mysql feature?

**Comment by abcping123** [comment]
@yurybura @PhoebeHui `vcpkg install sqlpp11-connector-mysql[core,mysql]` should be ok, I checked there is no `libmariadb` dependence, while the build still needs long time.

Maybe it is better to add some tips for someone who also is troubled by this issue.

Anyway, thanks a lot, I will close this issue.
