### ISSUE TITLE
How do I fix the issue of permission denied on ./vcpkg integrate install

### ISSUE THREAD

**Issue by Kareem-Elmokattaf** [microsoft/vcpkg#12057]
I am using a Mac Os and I am trying to use VScode. I have been trying to get my vcpkg to link up with the project I am currently working on but it will noe happen. I can't figure out how to manually add it or how to integrate it using terminal. When i use terminal it tells me permission denied. What can I do?

**Comment by LogicFan** [comment]
try to add sudo before the command?

**Comment by Kareem-Elmokattaf** [comment]
After adding sudo it would say that ./vcpkg does not exist

**Comment by timautry** [comment]
@Kareem-Elmokattaf - one needs to be superuser, either admin or root depending on the OS, to enable run `./vcpkg integrate install` as stated in the quick start section of the readme https://github.com/microsoft/vcpkg

**Comment by Kareem-Elmokattaf** [comment]
I am the only user on my laptop and it still wouldn't work. Would I need to manually allow certain permissions on mac?

**Comment by timautry** [comment]
I do not have a MAC, but from my understanding the OS is built on top of a linux kernel. That said you would need to open a terminal and then login as root.
1. Open terminal.
`su`
Or maybe
`sudo su`
It will ask for the root password to complete the login as root.
2. Then you would need to change directory where the vcpkg binary resides.
Something like 
`cd /some-path/<vcpkg-root>`
then
3. `./vcpkg integrate install`

**Comment by Kareem-Elmokattaf** [comment]
I appreciate the help but I am not sure what the second part means

**Comment by timautry** [comment]
You may need to use google bing or search for some you tube online instructional videos that could assist you further in using the mac terminal and logging in as super user.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
