### ISSUE TITLE
Error: Building package boost-compatibility:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by YXGuan** [microsoft/vcpkg#12066]
**Host Environment**
- OS: Windows

**To Reproduce**
`./vcpkg install vcpkg install boost:x86-windows`

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\vcpkg-master>vcpkg install boost:x86-windows
Computing installation plan...
The following packages will be built and installed:
    boost[core]:x86-windows
  * boost-accumulators[core]:x86-windows
  * boost-algorithm[core]:x86-windows
  * boost-align[core]:x86-windows
  * boost-any[core]:x86-windows
  * boost-array[core]:x86-windows
  * boost-asio[core]:x86-windows
  * boost-assert[core]:x86-windows
  * boost-assign[core]:x86-windows
  * boost-atomic[core]:x86-windows
  * boost-beast[core]:x86-windows
  * boost-bimap[core]:x86-windows
  * boost-bind[core]:x86-windows
  * boost-build[core]:x86-windows
  * boost-callable-traits[core]:x86-windows
  * boost-chrono[core]:x86-windows
  * boost-circular-buffer[core]:x86-windows
  * boost-compatibility[core]:x86-windows
  * boost-compute[core]:x86-windows
  * boost-concept-check[core]:x86-windows
  * boost-config[core]:x86-windows
  * boost-container[core]:x86-windows
  * boost-container-hash[core]:x86-windows
  * boost-context[core]:x86-windows
  * boost-contract[core]:x86-windows
  * boost-conversion[core]:x86-windows
  * boost-convert[core]:x86-windows
  * boost-core[core]:x86-windows
  * boost-coroutine[core]:x86-windows
  * boost-coroutine2[core]:x86-windows
  * boost-crc[core]:x86-windows
  * boost-date-time[core]:x86-windows
  * boost-detail[core]:x86-windows
  * boost-dll[core]:x86-windows
  * boost-dynamic-bitset[core]:x86-windows
  * boost-endian[core]:x86-windows
  * boost-exception[core]:x86-windows
  * boost-fiber[core]:x86-windows
  * boost-filesystem[core]:x86-windows
  * boost-flyweight[core]:x86-windows
  * boost-foreach[core]:x86-windows
  * boost-format[core]:x86-windows
  * boost-function[core]:x86-windows
  * boost-function-types[core]:x86-windows
  * boost-functional[core]:x86-windows
  * boost-fusion[core]:x86-windows
  * boost-geometry[core]:x86-windows
  * boost-gil[core]:x86-windows
  * boost-graph[core]:x86-windows
  * boost-graph-parallel[core]:x86-windows
  * boost-hana[core]:x86-windows
  * boost-heap[core]:x86-windows
  * boost-histogram[core]:x86-windows
  * boost-hof[core]:x86-windows
  * boost-icl[core]:x86-windows
  * boost-integer[core]:x86-windows
  * boost-interprocess[core]:x86-windows
  * boost-interval[core]:x86-windows
  * boost-intrusive[core]:x86-windows
  * boost-io[core]:x86-windows
  * boost-iostreams[core]:x86-windows
  * boost-iterator[core]:x86-windows
  * boost-lambda[core]:x86-windows
  * boost-lexical-cast[core]:x86-windows
  * boost-local-function[core]:x86-windows
  * boost-locale[core]:x86-windows
  * boost-lockfree[core]:x86-windows
  * boost-log[core]:x86-windows
  * boost-logic[core]:x86-windows
  * boost-math[core]:x86-windows
  * boost-metaparse[core]:x86-windows
  * boost-modular-build-helper[core]:x86-windows
  * boost-move[core]:x86-windows
  * boost-mp11[core]:x86-windows
  * boost-mpl[core]:x86-windows
  * boost-msm[core]:x86-windows
  * boost-multi-array[core]:x86-windows
  * boost-multi-index[core]:x86-windows
  * boost-multiprecision[core]:x86-windows
  * boost-nowide[core]:x86-windows
  * boost-numeric-conversion[core]:x86-windows
  * boost-odeint[core]:x86-windows
  * boost-optional[core]:x86-windows
  * boost-outcome[core]:x86-windows
  * boost-parameter[core]:x86-windows
  * boost-parameter-python[core]:x86-windows
  * boost-phoenix[core]:x86-windows
  * boost-poly-collection[core]:x86-windows
  * boost-polygon[core]:x86-windows
  * boost-pool[core]:x86-windows
  * boost-predef[core]:x86-windows
  * boost-preprocessor[core]:x86-windows
  * boost-process[core]:x86-windows
  * boost-program-options[core]:x86-windows
  * boost-property-map[core]:x86-windows
  * boost-property-tree[core]:x86-windows
  * boost-proto[core]:x86-windows
  * boost-ptr-container[core]:x86-windows
  * boost-python[core]:x86-windows
  * boost-qvm[core]:x86-windows
  * boost-random[core]:x86-windows
  * boost-range[core]:x86-windows
  * boost-ratio[core]:x86-windows
  * boost-rational[core]:x86-windows
  * boost-regex[core]:x86-windows
  * boost-safe-numerics[core]:x86-windows
  * boost-scope-exit[core]:x86-windows
  * boost-serialization[core]:x86-windows
  * boost-signals2[core]:x86-windows
  * boost-smart-ptr[core]:x86-windows
  * boost-sort[core]:x86-windows
  * boost-spirit[core]:x86-windows
  * boost-stacktrace[core]:x86-windows
  * boost-statechart[core]:x86-windows
  * boost-static-assert[core]:x86-windows
  * boost-static-string[core]:x86-windows
  * boost-system[core]:x86-windows
  * boost-test[core]:x86-windows
  * boost-thread[core]:x86-windows
  * boost-throw-exception[core]:x86-windows
  * boost-timer[core]:x86-windows
  * boost-tokenizer[core]:x86-windows
  * boost-tti[core]:x86-windows
  * boost-tuple[core]:x86-windows
  * boost-type-erasure[core]:x86-windows
  * boost-type-index[core]:x86-windows
  * boost-type-traits[core]:x86-windows
  * boost-typeof[core]:x86-windows
  * boost-ublas[core]:x86-windows
  * boost-units[core]:x86-windows
  * boost-unordered[core]:x86-windows
  * boost-utility[core]:x86-windows
  * boost-uuid[core]:x86-windows
  * boost-variant[core]:x86-windows
  * boost-variant2[core]:x86-windows
  * boost-vmd[core]:x86-windows
  * boost-wave[core]:x86-windows
  * boost-winapi[core]:x86-windows
  * boost-xpressive[core]:x86-windows
  * boost-yap[core]:x86-windows
  * bzip2[core]:x86-windows
  * libffi[core]:x86-windows
  * liblzma[core]:x86-windows
  * openssl[core]:x86-windows
  * openssl-windows[core]:x86-windows
  * python3[core]:x86-windows
  * zlib[core]:x86-windows
  * zstd[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/148: boost-compatibility:x86-windows
Building package boost-compatibility[core]:x86-windows...
-- Using cached C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/vcpkg-master/downloads/boostorg-compatibility-boost-1.73.0.tar.gz
-- Using source at C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/vcpkg-master/buildtrees/boost-compatibility/src/ost-1.73.0-44642da97c
-- Packaging headers
-- Packaging headers done
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.73.0/LICENSE_1_0.txt...
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.73.0/LICENSE_1_0.txt... Failed. Status: 6;"Couldn't resolve host name"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:175 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  installed/x86-windows/share/boost-vcpkg-helpers/boost-modular-headers.cmake:17 (vcpkg_download_distfile)
  ports/boost-compatibility/portfile.cmake:12 (boost_modular_headers)
  scripts/ports.cmake:76 (include)

Error: Building package boost-compatibility:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-compatibility:x86-windows
  Vcpkg version: 2020.02.04-nohash

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/11627.
