### ISSUE TITLE
Community triplets not working because of toolchain detection mechanism

### ISSUE THREAD

**Issue by longnguyen2004** [microsoft/vcpkg#12065]
Trying to use `*-mingw` triplets gives me an `Unable to determine toolchain to use for triplet` error. There are no references to community triplets in the documentation either. Am I missing something here?

**Comment by NancyLi1013** [comment]
Hi @longnguyen2004 
Thanks for posting this issue.
Could you please help confirm which triplet you used to install and on which platform? Please also make sure if you have installed the related  components in Visual Studio.

**Comment by longnguyen2004** [comment]
I'm using the `x64-mingw` community triplet on Windows. I have Visual Studio installed, but I only use it for bootstrapping vcpkg, since I'm trying to use vcpkg with the [llvm-mingw](https://github.com/mstorsjo/llvm-mingw) toolchain.

**Comment by NancyLi1013** [comment]
Which port do you install? 
BTW, those triplets in community folder are currently not guaranteed to be built successfully.

**Comment by longnguyen2004** [comment]
Every port I try results in the same error
![image](https://user-images.githubusercontent.com/15729831/85412639-00b6f900-b594-11ea-8127-31c08d512f51.png)
![image](https://user-images.githubusercontent.com/15729831/85412667-0a406100-b594-11ea-9df8-122e4ad6fcea.png)
![image](https://user-images.githubusercontent.com/15729831/85412708-14faf600-b594-11ea-9d38-0205beb00b49.png)
If I had to guess, it's due to [/toolsrc/src/vcpkg/build.cpp](../blob/master/toolsrc/src/vcpkg/build.cpp) and [/script/buildsystems/vcpkg.cmake](../blob/master/script/buildsystems/vcpkg.cmake) missing the required `mingw` toolchain entry. I've tried [patching `build.cpp`](https://pastebin.com/DeTn8bCX) and so far I haven't had any problems. But I feel like this is not the correct way to do it

**Comment by NancyLi1013** [comment]
Thanks for your update. It seems that there is something missing in `mingw` support.

@cristianadam  
Could you please help take a look about this?

**Comment by cristianadam** [comment]
@NancyLi1013 I tested tag "2020.01" and vcpkg builds with my TDM MinGW GCC 9.2.0 and `vcpkg --triplet x64-mingw install zlib` does work.

Regarding master, I had to apply https://github.com/microsoft/vcpkg/pull/12084 to get it building. But when I tried `vcpkg --triplet x64-mingw install zlib` it didn't work.

@longnguyen2004 either use vcpkg "2020.01" or wait until the problem with the toolchain gets fixed.

**Comment by longnguyen2004** [comment]
I think I see where the problem is. In [2020.01](https://github.com/microsoft/vcpkg/blob/2020.01/toolsrc/src/vcpkg/build.cpp#L504), if `CMAKE_SYSTEM_NAME` isn't recognized, it does nothing. In [master](https://github.com/microsoft/vcpkg/blob/master/toolsrc/src/vcpkg/build.cpp#L542), it errors out, so the changes need to be reverted.

**Comment by cristianadam** [comment]
@longhuan2018 Try https://github.com/microsoft/vcpkg/pull/12084. `vcpkg --triplet x64-mingw install zlib` worked fine for me.

**Comment by longnguyen2004** [comment]
@cristianadam you mentioned the wrong person :) anyway I'll try it now

**Comment by cristianadam** [comment]
I've updated the previous comment. Sorry about that.

I used the fix you provided for build.cpp in order not to get the *Unable to determine toolchain* error. Then the `file(TO_CMAKE_PATH)` fixes the error that I got building zlib with MinGW, since it took the `c:\` part of the path and then CMake would bail with invalid `\P` characters.

 #12084 allows me to build vcpkg and install packages via `--triplet x64-mingw`.

**Comment by longnguyen2004** [comment]
I'm trying to find a better fix since both `ios` and `emscripten` is also broken in the same way.
Also, does removing the error message causes anything else, since it wasn't there in 2020.01?

**Comment by jimboyeah** [comment]
我遇到这个问题有点恶心，因为 vcpkg 的源代码忽略了 MinGW：

	>vcpkg install assimp:x64-mingw
	Computing installation plan...
	The following packages will be built and installed:
	    assimp[core]:x64-mingw
	  * minizip[core]:x64-mingw
	  * rapidjson[core]:x64-mingw
	  * zlib[core]:x64-mingw
	Additional packages (*) will be modified to complete this operation.
	Unable to determine toolchain to use for triplet x64-mingw with CMAKE_SYSTEM_NAME MinGW

解决方法是修改 build.cpp 重新编译 vcpkg：

	diff --git a/toolsrc/src/vcpkg/build.cpp b/toolsrc/src/vcpkg/build.cpp
	index c61c6b7..d7c78aa 100644
	--- a/toolsrc/src/vcpkg/build.cpp
	+++ b/toolsrc/src/vcpkg/build.cpp
	@@ -558,6 +558,10 @@ namespace vcpkg::Build
	         else if (cmake_system_name == "Android")
	         {
	             return m_paths.scripts / fs::u8path("toolchains/android.cmake");
	+        }
	+        else if (cmake_system_name == "MinGW")
	+        {
	+            return m_paths.scripts / fs::u8path("toolchains/mingw.cmake");
	         }
	         else if (cmake_system_name.empty() || cmake_system_name == "Windows" || cmake_system_name == "WindowsStore")
	         {
	--

**Comment by longnguyen2004** [comment]
I think the best way is to simply ignore the toolchain selection in `build.cpp` for community triplets and use `VCPKG_CHAINLOAD_TOOLCHAIN_FILE` instead, not sure how it'll work out though.

**Comment by NancyLi1013** [comment]
@longnguyen2004 @jimboyeah 
Could you please try to update vcpkg to the latest version and rebuild this?

**Comment by longnguyen2004** [comment]
![image](https://user-images.githubusercontent.com/15729831/87911682-3b7a5700-ca96-11ea-8bbf-cca4ad098571.png)
Yep it works now, the pkg-config error is unrelated to this

**Comment by NancyLi1013** [comment]
@longnguyen2004 
Thanks for your update. 
For the status of community triplets, please refer to this [doc](https://github.com/microsoft/vcpkg/blob/master/docs/users/triplets.md#community-triplets).

**Comment by longnguyen2004** [comment]
Alright got it, I actually have a couple of patches ready 😃
