### ISSUE TITLE
Flags appended in android.cmake are ignored, including -fPIC (link error: relocation against preemptible symbol cannot be used when making a shared object)

### ISSUE THREAD

**Issue by jamiebk** [microsoft/vcpkg#12064]
The original problem occurred when trying to use boost-filesystem under Android targeting x86, though it may occur in other ports. The linker reports many errors of the form:
```
C:\...\ndk\21.3.6528147\toolchains\llvm\prebuilt\windows-x86_64\i686-linux-android\bin\ld : 
error : C:/.../vcpkg/installed/x86-android/debug/lib/libboost_filesystem.a(operations.o): 
relocation R_386_GOTOFF against preemptible symbol _ZN5boost10filesystem4pathD2Ev cannot be used when making a shared object
```
The underlying problem is that the `-fPIC` flag as appended in scripts/toolchains/android.cmake is not being used when vcpkg compiles that library (or any Android library as far as I can tell). It's is also not using any of the `VCPKG_<LANG>_FLAGS` apparently appended in vcpkg's android.cmake: though it looks like they are being appended here they are actually being ignored.

This is because the android NDK's android.toolchain.cmake sets the `CMAKE_<LANG>_FLAGS` variables directly rather than setting the `CMAKE_<LANG>_FLAGS_INIT` variables. Normally, when the CMake language is set via `project()` or otherwise, [the INIT flags get used to set the non-INIT flags](https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_FLAGS_INIT.html). However, if the non-INIT flags are set CMake (as of 3.17.3) will just ignore the `INIT` flags and use the non-INIT flags.

When I modify vcpkg's android.cmake so it appends to the *non-INIT* `CMAKE_<LANG>_FLAGS` rather than `CMAKE_<LANG>_FLAGS_INIT` then the appended flags, including `-fPIC` are correctly used by the compiler, there are no linking errors, and boost-filesystem works as intended.

I realize this may be a defect in the Android NDKs toolchain file, rather than vcpkg. Is that the case?

**Environment**
Windows 10, Visual Studio 16.6.2
Android NDK 21.3.6528147

**To Reproduce**
Use a basic triplet file, e.g:
```
set(VCPKG_TARGET_ARCHITECTURE x86)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_CMAKE_SYSTEM_NAME Android)
```
Install boost filesystem for the triplet using vcpkg.

`git clone https://github.com/jamiebk/repros.git -b boost-filesystem-android-link`

There are several configurations in CMakeSettings.json:
* The `android-x86` config will try to build a trivial shared lib that depends on boost filesystem. I get lots of link errors as above.
* The `android-toolchain` config logs the condition of CMAKE_CXX_FLAGS and CMAKE_CXX_FLAGS_INIT to illustrate what happens in the vcpkg android toolchain (The _INIT flags get ignored)
* The `android-toolchain-modified` config has a suggested fix (appending to the `CMAKE_<LANG>_FLAGS` rather than the `_INIT` flags.

**Comment by JackBoosY** [comment]
Does this issue relate to #9881 ?

**Comment by jamiebk** [comment]
I don't think so, other than the fact that the particular flag that manifests a general problem happens to be `-fPIC`. 
`vcpkg_configure_cmake` is used by the boost-filesystem port via `boost_modular_build` to set things up and invoke the actual CMake configure step. However, this problem occurs in that configure step irrespective of whether it is set up by vcpkg_configure_cmake or not.

This problem technically affects everything that uses the vcpkg toolchain targeting Android, both port builds and end-user builds, although the absence of that particular `-fPIC` flag would only be noticed for particular configurations.
