### ISSUE TITLE
Port request: MPFR

### ISSUE THREAD

**Issue by graham-hardy** [Microsoft/vcpkg#1206]
I have been trying to add a port of MPFR, a natural complement to MPIR. There is a Github repository at BrianGladman/mpfr, which includes Visual C++ build files but I haven't been able to understand the documentation for cloning with git.

There are the following problems:
* First, I can't figure out how to use the vcpkg_from_github command to retrieve the latest repository from GitHub. It is problematic because it seems to want a tag (together with a hash) for a particular version of the library. But if I perform a clone in Git, it automatically retrieves the latest, essentially the behaviour I was hoping for with the vcpkg/CMAKE interface. It's impossible to specify a tag because there aren't any tagged releases in the BrianGladman/mpfr fork.
* Second, the HEAD_REF switch to vcpkg_from_github doesn't seem to allow me to specify the master branch. My understanding was that the HEAD_REF switch allowed the user to bypass the requirement to specify a tag and a hash value, but when I write a switch like REF "master", it returns the error "Package does not specify REF.  It must built using --head."
* Finally, from time to time when I have tried other parameters, I have gotten errors from the file command indicating that it can't create a package directory.

**Comment by ras0219-msft** [comment]
Thanks for starting the port and the questions!

We've just published some docs you might find useful: https://vcpkg.readthedocs.io/en/latest/maintainers/vcpkg_from_github/.

>I can't figure out how to use the vcpkg_from_github command to retrieve the latest repository from GitHub.

We guard "unstable" fetches like this behind the `--head` option to `install`, to alert the user that even though the package works today it might break tomorrow if they uninstall and reinstall. It was added very recently, so we haven't gotten it fully documented yet, but the basic usage is:
```
vcpkg install --head mpfr
```

> It's impossible to specify a tag because there aren't any tagged releases in the BrianGladman/mpfr fork.

You can also use a raw git commit sha, and it works really well! As an example, take a look at [`ms-gsl`](https://github.com/Microsoft/vcpkg/blob/3ebcdd384b58ff5d5f92996a6eb2e9fed0be1710/ports/ms-gsl/portfile.cmake)

> My understanding was that the HEAD_REF switch allowed the user to bypass the requirement to specify a tag and a hash value, but when I write a switch like REF "master", it returns the error "Package does not specify REF. It must built using --head."

The idea is that a package will specify _both_ REF and HEAD_REF. This means most users can get a nice, stable version that we know works well with everything else, but you can also easily access the latest master branch by installing with `--head`.

>Finally, from time to time when I have tried other parameters, I have gotten errors from the file command indicating that it can't create a package directory.

I'd really like to fix any bugs here; if you can capture the command and output next time it happens that would be really helpful!

**Comment by albertziegenhagel** [comment]
I had written a port for MPFR quiet a time ago. Since I had problems to get the Visual Studio projects from BrianGladman working at that time (I do not remember what exactly the problem was, but I think it was because you had to change the dependencies to MPIR manually). So I decided to roll out a minimal CMakeLists.txt for MPFR.

I pushed the port to a branch at https://github.com/albertziegenhagel/vcpkg/tree/add-mpfr so you can have a look at it. Since I am not really a user of MPFR myself (just needed it to build CGAL) I am not sure whether I missed to configure some special options, so I decided to not make a pull request yet.

It would definitely be nice if one could add assembler support, to get an optimized version of MPFR (which would actually be a good idea for MPIR as well).
