### ISSUE TITLE
Build_Failed ffmpeg:x64-windows

### ISSUE THREAD

**Issue by polkadottedwalrus** [microsoft/vcpkg#12077]
BUILD FAILED on ffmpeg:x64-windows. Error Below, any help would be appreciated. 

PS C:\Users\shapi\Downloads\vcpkg-master\vcpkg-master> .\vcpkg install darknet[full]:x64-windows
Computing installation plan...
The following packages will be built and installed:
    darknet[core,cuda,cudnn,full,opencv-cuda,weights,weights-train]:x64-windows
  * ffmpeg[avresample,core]:x64-windows
  * hdf5[core,szip,zlib]:x64-windows
  * libjpeg-turbo[core]:x64-windows
  * liblzma[core]:x64-windows
  * libpng[core]:x64-windows
  * libwebp[core,nearlossless,simd,unicode]:x64-windows
  * opencv[core,cuda,dnn,ffmpeg,jpeg,opengl,png,tiff,webp]:x64-windows
  * opencv4[contrib,core,cuda,dnn,ffmpeg,jpeg,opengl,png,tiff,webp]:x64-windows
  * opengl[core]:x64-windows
  * protobuf[core]:x64-windows
  * pthreads[core]:x64-windows
  * stb[core]:x64-windows
  * szip[core]:x64-windows
  * tiff[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/15: ffmpeg:x64-windows
Building package ffmpeg[avresample,core]:x64-windows...
-- Using cached C:/Users/shapi/Downloads/vcpkg-master/vcpkg-master/downloads/ffmpeg-ffmpeg-n4.2.tar.gz
-- Using source at C:/Users/shapi/Downloads/vcpkg-master/vcpkg-master/buildtrees/ffmpeg/src/n4.2-a4d149a5c6
-- Acquiring MSYS Packages...
-- Acquiring MSYS Packages... OK
-- Building Options: --enable-asm --enable-yasm --disable-doc --enable-debug --enable-runtime-cpudetect --disable-openssl --disable-ffmpeg --disable-ffplay --disable-ffprobe --disable-libvpx --disable-libx264 --disable-opencl --disable-lzma --disable-bzlib --enable-avresample --disable-cuda --disable-nvenc --disable-cuvid --disable-libnpp --disable-avisynth --disable-gpl  --disable-static --enable-shared --extra-cflags=-DHAVE_UNISTD_H=0
-- Building Release Options:  --extra-cflags=-MD --extra-cxxflags=-MD
-- Building ffmpeg for Release
-- Building Debug Options: --debug --extra-cflags=-MDd --extra-cxxflags=-MDd
-- Building ffmpeg for Debug
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: C:/Users/shapi/Downloads/vcpkg-master/vcpkg-master/downloads/tools/msys2/msys64/usr/bin/bash.exe --noprofile --norc C:/Users/shapi/Downloads/vcpkg-master/vcpkg-master/ports/ffmpeg\build.sh C:/Users/shapi/Downloads/vcpkg-master/vcpkg-master/buildtrees/ffmpeg/x64-windows-dbg C:/Users/shapi/Downloads/vcpkg-master/vcpkg-master/buildtrees/ffmpeg/src/n4.2-a4d149a5c6 C:/Users/shapi/Downloads/vcpkg-master/vcpkg-master/packages/ffmpeg_x64-windows/debug "--enable-asm --enable-yasm --disable-doc --enable-debug --enable-runtime-cpudetect --disable-openssl --disable-ffmpeg --disable-ffplay --disable-ffprobe --disable-libvpx --disable-libx264 --disable-opencl --disable-lzma --disable-bzlib --enable-avresample --disable-cuda --disable-nvenc --disable-cuvid --disable-libnpp --disable-avisynth --disable-gpl  --disable-static --enable-shared --extra-cflags=-DHAVE_UNISTD_H=0 --debug --extra-cflags=-MDd --extra-cxxflags=-MDd"
    Working Directory: C:/Users/shapi/Downloads/vcpkg-master/vcpkg-master/buildtrees/ffmpeg/x64-windows-dbg
    Error code: 1
    See logs for more information:
      C:\Users\shapi\Downloads\vcpkg-master\vcpkg-master\buildtrees\ffmpeg\build-x64-windows-dbg-out.log

Call Stack (most recent call first):
  ports/ffmpeg/portfile.cmake:227 (vcpkg_execute_required_process)
  scripts/ports.cmake:73 (include)

Error: Building package ffmpeg:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: ffmpeg:x64-windows
  Vcpkg version: 2020.02.04-nohash

Additionally, attach any relevant sections from the log files above.
PS C:\Users\shapi\Downloads\vcpkg-master\vcpkg-master>

**Comment by PhoebeHui** [comment]
@polkadottedwalrus, could you attach failure log C:\Users\shapi\Downloads\vcpkg-master\vcpkg-master\buildtrees\ffmpeg\build-x64-windows-dbg-out.log?

I can't repro this issue with latest source

PS F:\VCPKG\src> ./vcpkg install ffmpeg[avresample,core]:x64-windows
Computing installation plan...
The following packages will be built and installed:
    ffmpeg[avresample,core]:x64-windows
Starting package 1/1: ffmpeg:x64-windows
Building package ffmpeg[avresample,core]:x64-windows...
-- Using cached F:/VCPKG/src/downloads/ffmpeg-ffmpeg-n4.2.tar.gz
-- Extracting source F:/VCPKG/src/downloads/ffmpeg-ffmpeg-n4.2.tar.gz
-- Applying patch 0001-create-lib-libraries.patch
-- Applying patch 0003-fix-windowsinclude.patch
-- Applying patch 0004-fix-debug-build.patch
-- Applying patch 0005-fix-libvpx-linking.patch
-- Applying patch 0006-fix-StaticFeatures.patch
-- Using source at F:/VCPKG/src/buildtrees/ffmpeg/src/n4.2-a4d149a5c6
-- Acquiring MSYS2...
-- Downloading https://sourceforge.net/projects/msys2/files/Base/x86_64/msys2-base-x86_64-20190524.tar.xz/download...
gpg: /etc/pacman.d/gnupg/trustdb.gpg: trustdb created
gpg: no ultimately trusted keys found
gpg: starting migration from earlier GnuPG versions
gpg: porting secret keys from '/etc/pacman.d/gnupg/secring.gpg' to gpg-agent
gpg: migration succeeded
gpg: Generating pacman keyring master key...
gpg: key C2EFDBCBEF393C2B marked as ultimately trusted
gpg: directory '/etc/pacman.d/gnupg/openpgp-revocs.d' created
gpg: revocation certificate stored as '/etc/pacman.d/gnupg/openpgp-revocs.d/F965E162E7BD051497BE9652C2EFDBCBEF393C2B.rev'
gpg: Done
==> Updating trust database...
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
==> Appending keys from msys2.gpg...
==> Locally signing trusted keys in keyring...
  -> Locally signing key D55E7A6D7CE9BA1587C0ACACF40D263ECA25678A...
  -> Locally signing key 123D4D51A1793859C2BE916BBBE514E53E0D0813...
  -> Locally signing key B91BCF3303284BF90CC043CA9F418C233E652008...
  -> Locally signing key 9DD0D4217D75A33B896159E6DA7EF2ABAEEA755C...
==> Importing owner trust values...
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: inserting ownertrust of 4
==> Updating trust database...
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   4  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: depth: 1  valid:   4  signed:   3  trust: 0-, 0q, 0n, 4m, 0f, 0u
gpg: depth: 2  valid:   3  signed:   0  trust: 3-, 0q, 0n, 0m, 0f, 0u
:: Synchronizing package databases...
downloading mingw32.db...
downloading mingw32.db.sig...
downloading mingw64.db...
downloading mingw64.db.sig...
downloading msys.db...
downloading msys.db.sig...
:: Starting core system upgrade...
warning: resolving dependencies...
terminate other MSYS2 programs before proceeding
looking for conflicting packages...
error: :: installing filesystem (2020.02-3) breaks dependency 'msys2-base' required by dash
failed to prepare transaction (could not satisfy dependencies)
-- Acquiring MSYS2... OK
-- Acquiring MSYS Packages...
-- Acquiring MSYS Packages... OK
-- Building Options: --enable-asm --enable-yasm --disable-doc --enable-debug --enable-runtime-cpudetect --disable-openssl --disable-ffmpeg --disable-ffplay --disable-ffprobe --disable-libvpx --disable-libx264 --disable-opencl --disable-lzma --disable-bzlib --enable-avresample --disable-cuda --disable-nvenc --disable-cuvid --disable-libnpp --disable-avisynth --disable-gpl  --disable-static --enable-shared --extra-cflags=-DHAVE_UNISTD_H=0
-- Building Release Options:  --extra-cflags=-MD --extra-cxxflags=-MD
-- Building ffmpeg for Release
-- Building Debug Options: --debug --extra-cflags=-MDd --extra-cxxflags=-MDd
-- Building ffmpeg for Debug
-- Generating F:\VCPKG\src\packages\ffmpeg_x64-windows\debug\lib\avcodec.lib
-- Generating F:\VCPKG\src\packages\ffmpeg_x64-windows\debug\lib\avdevice.lib
-- Generating F:\VCPKG\src\packages\ffmpeg_x64-windows\debug\lib\avfilter.lib
-- Generating F:\VCPKG\src\packages\ffmpeg_x64-windows\debug\lib\avformat.lib
-- Generating F:\VCPKG\src\packages\ffmpeg_x64-windows\debug\lib\avresample.lib
-- Generating F:\VCPKG\src\packages\ffmpeg_x64-windows\debug\lib\avutil.lib
-- Generating F:\VCPKG\src\packages\ffmpeg_x64-windows\debug\lib\swresample.lib
-- Generating F:\VCPKG\src\packages\ffmpeg_x64-windows\debug\lib\swscale.lib
-- Generating F:\VCPKG\src\packages\ffmpeg_x64-windows\lib\avcodec.lib
-- Generating F:\VCPKG\src\packages\ffmpeg_x64-windows\lib\avdevice.lib
-- Generating F:\VCPKG\src\packages\ffmpeg_x64-windows\lib\avfilter.lib
-- Generating F:\VCPKG\src\packages\ffmpeg_x64-windows\lib\avformat.lib
-- Generating F:\VCPKG\src\packages\ffmpeg_x64-windows\lib\avresample.lib
-- Generating F:\VCPKG\src\packages\ffmpeg_x64-windows\lib\avutil.lib
-- Generating F:\VCPKG\src\packages\ffmpeg_x64-windows\lib\swresample.lib
-- Generating F:\VCPKG\src\packages\ffmpeg_x64-windows\lib\swscale.lib
-- Installing: F:/VCPKG/src/packages/ffmpeg_x64-windows/share/ffmpeg/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package ffmpeg[avresample,core]:x64-windows... done
Installing package ffmpeg[avresample,core]:x64-windows...
Installing package ffmpeg[avresample,core]:x64-windows... done
Elapsed time for package ffmpeg:x64-windows: 22.01 min

Total elapsed time: 22.02 min

**Comment by PhoebeHui** [comment]
@polkadottedwalrus, please reopen this issue and attach failures logs if it still be a problem for you.
