### ISSUE TITLE
[PCL:x64-linux] build failure 

### ISSUE THREAD

**Issue by bhwqy** [microsoft/vcpkg#12079]
**Host Environment**
- OS: Ubuntu 20.04
- Compiler: g++ 9

**To Reproduce**
`./vcpkg install pcl`

**Failure logs** 
-Cut and past the appropriate build messages from the console output.

Computing installation plan...
The following packages will be built and installed:
    pcl[core]:x64-linux
Starting package 1/1: pcl:x64-linux
Building package pcl[core]:x64-linux...
-- Using cached /home/qy101/Desktop/vcpkg/downloads/PointCloudLibrary-pcl-pcl-1.9.1.tar.gz
-- Using source at /home/qy101/Desktop/vcpkg/buildtrees/pcl/src/pcl-1.9.1-f2ec88a858
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
																										
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: /home/qy101/Desktop/vcpkg/downloads/tools/cmake-3.17.2-linux/cmake-3.17.2-Linux-x86_64/bin/cmake --build . --config Debug --target install -- -v
    Working Directory: /home/qy101/Desktop/vcpkg/buildtrees/pcl/x64-linux-dbg
    See logs for more information:
      /home/qy101/Desktop/vcpkg/buildtrees/pcl/install-x64-linux-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/pcl/portfile.cmake:54 (vcpkg_install_cmake)
  scripts/ports.cmake:73 (include)

Error: Building package pcl:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: pcl:x64-linux
  Vcpkg version: 2020.02.04-unknownhash

-Please attach any additional failure logs mentioned in the console output.

[install-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/4822703/install-x64-linux-dbg-out.log)

**Comment by timautry** [comment]
@bhwqy the log file on line 48 shows a kill signal was sent to the cc1plus compiler ending the vcpkg install process.

`c++: fatal error: Killed signal terminated program cc1plus` 
`compilation terminated.`

**Comment by bhwqy** [comment]
I retried to build the project and the same error occurs. I am sure the killed signal is not sent by myself. I think the reason why compiler stops is on line 46.

> FAILED: sample_consensus/CMakeFiles/pcl_sample_consensus.dir/src/sac_model_cylinder.cpp.o

**Comment by timautry** [comment]
> I retried to build the project and the same error occurs. I am sure the killed signal is not sent by myself. I think the reason why compiler stops is on line 46.
> 
> > FAILED: sample_consensus/CMakeFiles/pcl_sample_consensus.dir/src/sac_model_cylinder.cpp.o

Many articles refer to the OOM (Out of Memory) Killer process taking action to prevent a fatal system shutdown based on low memory.

- how much physical, virtual and swap memory does your system have?
- from command line run free -mh and you should get something similar to this:
`>$ free -mh`
`total used free shared buff/cache available`
`Mem: 127Gi 21Gi 105Gi 17Mi 223Mi 105Gi`
`Swap: 116Gi 130Mi 116Gi`

**Comment by bhwqy** [comment]
Thank you, I run vcpkg in a VMWare environment. The following is the settings of my system. It is OOM Killer process that kills the process. So what can I do to fix this bug?

total        used        free      shared  buff/cache   available
Mem:          3.8Gi       591Mi       2.9Gi       0.0Ki       299Mi       3.0Gi
Swap:         2.0Gi       979Mi       1.0Gi

**Comment by bhwqy** [comment]
The bug is solved by increasing the amount of of memory assigned to the virtual machine.

**Comment by timautry** [comment]
Glad you figured it out. Take care.
