### ISSUE TITLE
Browse.vc.db is not invalidated in vs2019 when VcpkgTriplet changes

### ISSUE THREAD

**Issue by aggieNick02** [microsoft/vcpkg#12076]
**Describe the bug**
Ignoring the recent break I reported (https://github.com/microsoft/vcpkg/issues/12062), when you set VcpkgTriplet in a vcxproj file, VS2015 and VS2017 consistently look in the correct location for the header files from the installed vcpkg ports. But in VS2019, while the compile behaves appropriately, when you try to open a header file from a port, it can look in the wrong location if you've changed the triplet. This is a bug and poor integration experience that seems to works correctly in VS2015 and VS2017.

**Environment**
- OS: Win 1903, 1909
- Compiler: Bad behavior in VS2019 16.6.2

**To Reproduce**
- Install `vcpkg` without the recent `.vcxproj` triplet bug, and install `minhook:x86-windows-static` (just to have something to use):
```
git clone https://github.com/Microsoft/vcpkg.git vcpkg_before
cd vcpkg_before
git checkout 14514508d8d30bdbd645b2bec89696aec25497f1~1
.\bootstrap-vcpkg.bat
.\vcpkg.exe integrate install
.\vcpkg.exe install minhook:x86-windows-static
```
- Now start visual studio 2019 (16.6.2), create a new c++ console application project with solution.
Add
`#include "minhook.h"`
immediately before the main() function.
- Build the solution. It will correctly fail as only the static minhook is installed.
- Right click on the text "minhook.h" in the text of the include line you added. Choose to go to document. This correctly fails.
- Close visual studio.
- Edit the `.vcxproj` project file to have the line:
`<VcpkgTriplet>x86-windows-static</VcpkgTriplet>`
at the bottom of the
`<PropertyGroup Label="Globals">`
section.
- Open the solution.
- Build the solution. It correctly succeeds since we now point to the static port.
- Right click on the text "minhook.h" in the text of the include line you added. Choose to go to document. This incorrectly fails!!
- Close the solution and visual studio.
- Go to the solution folder, show hidden items, and delete the .vs folder at the top-level, This folder contains the browse info database.
- Open the solution and then show the main cpp file
- Right click on the text "minhook.h" in the text of the include line you added. Choose to go to document. This correctly succeeds

**Expected behavior**
Choosing to go to the included header file should work correctly after changing the VcpkgTriplet and reloading the project or reopening visual studio. To fix the behavior you have to delete the vc browse database. This workaround is not needed in vs2015 and vs2017, and without realizing what is happening, it leads to some very confusing/poor integration behavior.

**Comment by BillyONeal** [comment]
I don't know if there's anything vcpkg can do about this. @yuehuang010 do you have any ideas on how to get the IDE to realize that that setting affects include paths?

**Comment by aggieNick02** [comment]
Yeah, that makes sense. When I started writing up the issue, what I was seeing led me to think `vcpkg` was likely at fault, but by the time I was done and had solid reproduction steps, it definitely seems like it could be a VS2019 bug at the core. I'll see if I can find a similar way to trigger it without `vcpkg` .

**Comment by aggieNick02** [comment]
Alright, I figured out how to trigger this with just VS2019. Verified the exact same sequence does not cause the bug in VS2017. We can go ahead and close this issue and I'll file one for VS 2019. Here's how to do it without `vcpkg`.
- Create a new cpp console project and add `#inlcude "foobar.h"` to the main cpp file
- Navigate to the property manager and open `Microsoft.Cpp.,Win32.user` under `Debug | Win32`C. Go the the `User Macros` section and add a macro named `MyCustomMacro` with the value `c:\missing_include`
- Create a new directory at `c:\good_include` and a new empty text document at `c:\good_include\foobar.h`
- Add `$(MyCustomMacro)` as to `Include Directories` by right clicking on the project in solution explorer, choosing `Properties...`, and going to `VC++ Directories` .
- Build solution. It will correctly fail.
- Close visual studio.
- Open `%localappdata%\Microsoft\MSBuild\v4.0\Microsoft.Cpp.Win32.user.props` in notepad
- Replace `c:\missing_include` with `c:\good_include` in the file
- Save file and exit notepad
- Reopen solution in VS2019.
- Build solution. It succeeds correctly.
- Right click on the text `"foobar.h"` and choose to go to `Go to document "foobar.h"`. It will fail. This is incorrect behavior.

**Comment by aggieNick02** [comment]
Link to VS2019 issue:
https://developercommunity.visualstudio.com/content/problem/1091182/vs2019-does-not-invalidate-browse-info-when-the-in.html
