### ISSUE TITLE
How do I choose the specify library version?

### ISSUE THREAD

**Issue by zh1an** [microsoft/vcpkg#12081]
When asking a question please also include where you looked for an answer (so we can update the documentation if needed).

I'm using VS2015.
Now some libraries has update the latest version, but they requir VS2017 or later. So I can't keep update with vcpkg.
The followings is my question:
1. Could vcpkg make a branch that indicating the library recommended with VS2015 or VS2017 or later?
2. Could vcpkg provide some method that choose the specify version library?

**Comment by BillyONeal** [comment]
The federation / manifest stuff @strega-nil is working on will provide some mitigation for this but I believe the official repository remains slated to contain only the latest versions of things (which we have ensured build together). @strega-nil can you confirm?

**Comment by strega-nil** [comment]
Check out #11758 :) cc @vicroms
