### ISSUE TITLE
[boost[core]:x64-linux] build failure

### ISSUE THREAD

**Issue by AlexandreGerault** [microsoft/vcpkg#12098]
**Host Environment**
- OS: Linux (endeavourOs)
- Compiler: GCC 10.1.0

**To Reproduce**
`./vcpkg install boost spdlog`

**Failure logs** 
```
CMake Error at installed/x64-linux/share/boost-build/boost-modular-build.cmake:112 (message):
  No libraries were produced.  This indicates a failure while building the
  boost library.
Call Stack (most recent call first):
  ports/boost-exception/portfile.cmake:12 (boost_modular_build)
  scripts/ports.cmake:73 (include)


Error: Building package boost-exception:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-exception:x64-linux
  Vcpkg version: 2020.02.04-unknownhash

Additionally, attach any relevant sections from the log files above.
```

I just installed vcpkg following the README.md to manage my packages more easily but I can't get it works. Same for spdlog (fmt dependency fail to build).

**Comment by AlexandreGerault** [comment]
I tried to install these libraries on my ubuntu laptop which uses `gcc version 9.2.1 20191008 (Ubuntu 9.2.1-9ubuntu2)`. It works well here. Is there something I can try to do for a PR?

**Comment by PhoebeHui** [comment]
@AlexandreGerault, it seems that boost-exception:x64-linux build failed with gcc 10.1.0, I don't have gcc 10.1.0, I test it by gcc 7.5.0, everything built successfully for me. you can reference the following the 2 steps:

1.  Check the failures logs under buildtree/boost-exception, and see if the specific source failures in gcc 10.1.0, if so, pelase repoert to upstream instead.
2. Down to use lower gcc revision, you can reference the primary test compilers from https://www.boost.org/users/history/version_1_73_0.html.

**Comment by AlexandreGerault** [comment]
It finally works well with GCC 10.1.0. The issue seem to come from the installation location. I now install vcpkg to my internal hard drive disk.

**Comment by PhoebeHui** [comment]
Glad to see the issue solved, thanks for your updates!
