### ISSUE TITLE
assimp is generating malformed CMake config files

### ISSUE THREAD

**Issue by traversaro** [Microsoft/vcpkg#1209]
In particular, in https://github.com/Microsoft/vcpkg/blob/dea170b46970171a104551d2d6512dee1469646b/ports/assimp/portfile.cmake#L31 the `lib/cmake/assimp-3.3` directory is renamed in `share/assimp` without properly modifying the configuration file to handle the change in its relative position (as done for example in https://github.com/Microsoft/vcpkg/commit/abe8d017dfb40c97451e493aa569c8178b8f10e2). 

Furthermore the debug imported targets in https://github.com/Microsoft/vcpkg/blob/dea170b46970171a104551d2d6512dee1469646b/ports/assimp/portfile.cmake#L33 are simply deleted, instead of being correctly processed using `vcpkg_fixup_cmake_targets`.

cc @claudiofantacci

**Comment by NancyLi1013** [comment]
This should be fixed.
