### ISSUE TITLE
MathGL simple test program hangs indefinitely

### ISSUE THREAD

**Issue by ijean** [microsoft/vcpkg#12096]
Hi,

I've installed MathGL using vcpkg with latest VS 2019 on Windows 10 2004, successfully build one of their C++ examples:

```
#include <mgl2/mgl.h>

int main() {
	mglGraph gr;
	gr.FPlot("sin(x)");
	gr.WriteFrame("test.png");
}
```

Launching the resulting executable seems to hang indefinitely (never ends). Expected behaviour is to create a PNG image file with a curve.

Regards,
Jean

**Comment by PhoebeHui** [comment]
@ijean, thanks for reporting this issue!

I'm not familar with mathgl, I try to debug the code, it seems hand at FillY12 in font.cpp. @cenit, do you know more about this?

![image](https://user-images.githubusercontent.com/20694052/85945071-dbe4cc00-b96d-11ea-8b69-03c44410da61.png)

**Comment by ijean** [comment]
@PhoebeHui good catch. I suppose the problem under Windows could be in config.h.in where *MGL_DEF_FONT_NAME* is an empty string:

```
#ifdef WIN32	// a man ask to use built-in font under Windows
#define MGL_DEF_FONT_NAME	""
#else
#define MGL_DEF_FONT_NAME	"${MGL_DEF_FONT}"
#endif
#define MGL_INSTALL_DIR	"${CMAKE_INSTALL_PREFIX}"
```

The *mglFont::mglFont* from *font.cpp* doesn't seem to correctly treat the case of an empty font name.  We probably need to patch this piece of code:

```
#ifdef WIN32	// a man ask to use built-in font under Windows
-  #define MGL_DEF_FONT_NAME	""
+  #define MGL_DEF_FONT_NAME	"${MGL_DEF_FONT}"
#else
#define MGL_DEF_FONT_NAME	"${MGL_DEF_FONT}"
#endif
```

and define the ${MGL_DEF_FONT} ${MGL_FONT_PATH} cmake variables. Just pick some font that is always present in Windows.

**Comment by PhoebeHui** [comment]
@ijean, thanks for your updates! Could you report this issue to mathgl as well?

**Comment by nil-is-lin** [comment]
I run the same test code

> #include <mgl2/mgl.h>
> 
> int main() {
> 	mglGraph gr;
> 	gr.FPlot("sin(x)");
> 	gr.WriteFrame("test.png");
> }
However, it throw 

> Global message - PNG support was disabled. Please, enable it and rebuild MathGL.
> MathGL message - test.png: couldn't open file

In fact, I have install the png module,

> PS E:\vcpkg> .\vcpkg.exe install mathgl:x64-windows
> Computing installation plan...
> The following packages are already installed:
>     mathgl[core,jpeg,opengl,png,zlib]:x64-windows
> Package mathgl:x64-windows is already installed
> 
> Total elapsed time: 360.1 us
> 
> The package mathgl:x64-windows provides CMake targets:
> 
>     find_package(mathgl CONFIG REQUIRED)
>     target_link_libraries(main PRIVATE mgl mgl-static)

It's strange, isn't it？

**Comment by nil-is-lin** [comment]
The problem `PNG support was disabled` disappeared after I installed mathgl servel times. Now the only problem with mathgl[without qt] I meet is I can't use it in cmake project. It seems work well till now in `sln` project. However, when I used it in cmakelists, 

> SET(CMAKE_TOOLCHAIN_FILE "E:/vcpkg/scripts/buildsystems/vcpkg.cmake")
> ...
> find_package(mathgl CONFIG REQUIRED)
>...
>target_link_libraries(${PROJECT_NAME} PRIVATE mgl mgl-static)

it throw

> 1> [CMake] CMake Error at E:/vcpkg/scripts/buildsystems/vcpkg.cmake:536 (_find_package):
> 1> [CMake]   Could not find a package configuration file provided by "mathgl" with any
> 1> [CMake]   of the following names:
> 1> [CMake] 
> 1> [CMake]     mathglConfig.cmake
> 1> [CMake]     mathgl-config.cmake
> 1> [CMake] 
> 1> [CMake]   Add the installation prefix of "mathgl" to CMAKE_PREFIX_PATH or set
> 1> [CMake]   "mathgl_DIR" to a directory containing one of the above files.  If "mathgl"
> 1> [CMake]   provides a separate development package or SDK, be sure it has been
> 1> [CMake]   installed.

I can not hit any thing when i search the `vcpkg.cmake` with `mathgl`. Is this a problem? or Just i am in the wrong way?

**Comment by PhoebeHui** [comment]
@nil-is-lin, thanks for reporting this issue! it seems a mathgl port bug, I will take a look, and this is a different issue.

**Comment by tupos** [comment]
Hello I also ran into this problem when I compiled mathgl. I debugged the loop from the screenshot above and it also hangt after the loop but after some time in debugger I had a message that two threads exited. Therefore I commented
```
#pragma omp parallel
```
and after this the load of dll happens without any problems and the test program which links with `mathgl.dll` does not hang anymore.

I'm not sure what is happening here, but I do not think that the define from @ijean comment from above influences this.

**Comment by JackBoosY** [comment]
I can't repro this issue now, is this resolved?

**Comment by nil-is-lin** [comment]
@JackBoosY. I just tried it and encountered problems (#22264), so it's hard to verify that the problem is solved.

**Comment by JackBoosY** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.
