### ISSUE TITLE
[Armadillo] mismatch detected for 'RuntimeLibrary'

### ISSUE THREAD

**Issue by gvanem** [microsoft/vcpkg#12102]
I have a real *show stopper* issue regarding **Armadillo, Version: 2019-04-16-8**.

I installed using `vcpkg install armadillo:x86-windows`. I got the sub-dependencies and built OK seemingly.

But using it in a C++ program compiled with `cl -MD` does not work since at the linking stage I get
many mismatches like this:
```
armadillo.lib(wrapper.cpp.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': 
value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in main.obj
```
And since `armadillo.lib` pulls in `libcpmt.lib`, there are other such mismatches (88 in all!).

So it looks like Armadillo was built with  `cl -MT`.
I request it could be changed to  `cl -MD` as Microsoft has encouraged us for years now.

Or is there an option that I can use to force this myself? (I'm a n00b when it comes to vcpkg).

**Comment by LilyWangL** [comment]
Thanks for posting this issue. `armadillo` pnly supports static library, there are this code `vcpkg_check_linkage(ONLY_STATIC_LIBRARY)` in `portfile.cmake` . And when you installing `armadillo:x86-windows`, you can see this information on powershell.
```
Building package armadillo[core]:x86-windows...
-- Note: armadillo only supports static library linkage. Building static library.
``` 
So you should use `cl -MT` to build `armadillo`.

**Comment by LilyWangL** [comment]
Due to there are no functions/data in source of `armadillo` use `__declspec(dllexport)` to export `*.dll` file, `armadillo` is a static library.

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
