### ISSUE TITLE
[New Port Request] Mozilla DeepSpeech

### ISSUE THREAD

**Issue by eix128** [microsoft/vcpkg#12106]
Mozilla has made offline speech recognition.
Here is C++ source:
https://github.com/mozilla/DeepSpeech/tree/master/native_client

There is also example:
https://github.com/mozilla/DeepSpeech/blob/master/native_client/client.cc

Vcpkg should add this library for all platforms 
OSX , Win , Linux , FreeBSD 

There is also already nuget for
https://nugetmusthaves.com/Package/DeepSpeech-GPU
https://nugetmusthaves.com/Package/DeepSpeech

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
