### ISSUE TITLE
shark machine learning library missing in vcpkg

### ISSUE THREAD

**Issue by semyalodennis** [microsoft/vcpkg#12100]
****

**Is your feature request related to a problem? Please describe.**
shark machine learning library missing in vcpkg

**Proposed solution**
shark machine learning library should be added to vcpkg

**Describe alternatives you've considered**
Getting shark machine learning library from its Github page (https://github.com/Shark-ML/Shark/)

**Additional context**

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
