### ISSUE TITLE
[xlnt] find_package failure

### ISSUE THREAD

**Issue by ZeeWanderer** [microsoft/vcpkg#12107]
**Describe the bug**
After vcpkg install and integration using `find_package(xlnt CONFIG REQUIRED)` in a cmake project results in
```
1> [CMake] CMake Error at E:/Tools/vcpkg/installed/x64-windows/share/xlnt/XlntConfig.cmake:13 (message):
1> [CMake]   File or directory include referenced by variable XLNT_INCLUDE_DIR does not
1> [CMake]   exist !
```

**Environment**
- OS: Windows 10
- Compiler: MSVC 19.26.28806.0

**To Reproduce**
1. ./vcpkg install xlnt:x64-windows
2. ./vcpkg integrate install
3. use `find_package(xlnt CONFIG REQUIRED)` in a cmake project

**Comment by johnco3** [comment]
I get the same behavior, I also tried vcpkg install xlnt:x64-windows --head to pull from the latest source but the problem persists.  Unfortunately I don't know vcpkg sufficiently to fix it.   Here is part of my CMake command output where I use `find_package(Xlnt CONFIG REQUIRED)`

The CMake output is as follows:

```
. . .
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Found Boost: C:/Users/johnc/main/extlibs/vcpkg/installed/x64-windows/include (found suitable version "1.73.0", minimum required is "1.73.0") found components: program_options date_time log log_setup filesystem thread regex chrono atomic
CMake Error at C:/Users/johnc/main/extlibs/vcpkg/installed/x64-windows/share/xlnt/XlntConfig.cmake:13 (message):
  File or directory include referenced by variable XLNT_INCLUDE_DIR does not
  exist !
Call Stack (most recent call first):
  C:/Users/johnc/main/extlibs/vcpkg/installed/x64-windows/share/xlnt/XlntConfig.cmake:31 (set_and_check)
  C:/Users/johnc/main/extlibs/vcpkg/scripts/buildsystems/vcpkg.cmake:415 (_find_package)
  CMakeLists.txt:29 (find_package)


-- Configuring incomplete, errors occurred!
See also "C:/Users/johnc/main/tcdu/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/johnc/main/tcdu/build/CMakeFiles/CMakeError.log".


```

**Comment by ZeeWanderer** [comment]
@johnco3 This is an upstream xlnt cmake problem as I tried using upstream repo as a submodule and the result is the same. In the end, I settled for MSBuild. Originally I wanted to open an upstream issue but never got to it yet.

**Comment by johnco3** [comment]
it is frustrating, as it is the only part of my build dependency that
fails. I was digging into the root of the problem and from what I can tell
it is to do with a generated line of cmake code
`set_and_check(XLNT_INCLUDE_DIR "include")`.  I don't know where this
originated from as i'm not very familiar with creating portiles for vcpkg.
But it more than likely is called via configure_package_config_file()
called through some `XlntConfig.cmake.in` file which I found on github.
Looks like the problem has to do with expanding the
@XLNT_INCLUDE_INSTALL_DIR@ whatever that is supposed to be.

set(XLNT_VERSION "@xlnt_VERSION@")

@PACKAGE_INIT@

get_filename_component(XLNT_CMAKE_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)

set_and_check(XLNT_INCLUDE_DIR "@XLNT_INCLUDE_INSTALL_DIR@")

check_required_components(xlnt)

if(NOT TARGET xlnt::xlnt)
  include("${XLNT_CMAKE_DIR}/XlntTargets.cmake")
endif()

This in turn generates the port file (which incidentally has a different
version compared to the code's 1.4.0 which I saw somewhere else).

set(XLNT_VERSION "1.5.0")

####### Expanded from @PACKAGE_INIT@ by configure_package_config_file()
#######
####### Any changes to this file will be overwritten by the next CMake run
####
####### The input file was XlntConfig.cmake.in
 ########

get_filename_component(PACKAGE_PREFIX_DIR
"${CMAKE_CURRENT_LIST_DIR}/../../" ABSOLUTE)

macro(set_and_check _var _file)
  set(${_var} "${_file}")
  if(NOT EXISTS "${_file}")
    message(FATAL_ERROR "File or directory ${_file} referenced by variable
${_var} does not exist !")
  endif()
endmacro()

macro(check_required_components _NAME)
  foreach(comp ${${_NAME}_FIND_COMPONENTS})
    if(NOT ${_NAME}_${comp}_FOUND)
      if(${_NAME}_FIND_REQUIRED_${comp})
        set(${_NAME}_FOUND FALSE)
      endif()
    endif()
  endforeach()
endmacro()

####################################################################################

get_filename_component(XLNT_CMAKE_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)

set_and_check(XLNT_INCLUDE_DIR "include")

check_required_components(xlnt)

if(NOT TARGET xlnt::xlnt)
  include("${XLNT_CMAKE_DIR}/XlntTargets.cmake")
endif()

**Comment by fly2sky2018** [comment]
meet the same problem. how to use xInt....

1)Cmake erro at
Configuring done.
but can’t generate xInt lib and dll… Please Help ~ thx

Erro is below:

CMake Error at third-party/libstudxml.build/CMakeLists.txt:52 (add_library):
** Cannot find source file:**

** C:/xlnt-master/third-party/libstudxml/libstudxml/parser.cxx**

** Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .h .hh .h++.hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .ispc**

CMake Error at third-party/libstudxml.build/CMakeLists.txt:52 (add_library):
** No SOURCES given to target: libstudxml

2)vcpkg erro ..
at the shell : 
PS C:\vcpkg-master> .\vcpkg.exe install xInt
Computing installation plan...
Error: while loading xint:
**The port directory (C:\vcpkg-master\ports\xint) does not exist
Error: failed to load port from C:\vcpkg-master\ports\xint
Note: Updating vcpkg by rerunning bootstrap-vcpkg may resolve this failure.**
