### ISSUE TITLE
How to install Qt5 on macOs? It failed.

### ISSUE THREAD

**Issue by justin-bj** [microsoft/vcpkg#12119]
./vcpkg install Qt5
Computing installation plan...
The following packages will be built and installed:
    qt5[activeqt,core,declarative,essentials,imageformats,multimedia,networkauth,quickcontrols2,svg,tools]:x64-osx
  * qt5-base[core]:x64-osx
  * qt5-declarative[core]:x64-osx
  * qt5-imageformats[core]:x64-osx
  * qt5-multimedia[core]:x64-osx
  * qt5-networkauth[core]:x64-osx
  * qt5-quickcontrols2[core]:x64-osx
  * qt5-svg[core]:x64-osx
  * qt5-tools[core]:x64-osx
  * tiff[core]:x64-osx
Additional packages (*) will be modified to complete this operation.
Starting package 1/10: qt5-base:x64-osx
Building package qt5-base[core]:x64-osx...
-- Figuring out qt target mkspec. Target arch x64
-- Target mkspec set to: macx-clang
-- Host mkspec not set. Qt's own buildsystem will try to figure out the host system
-- Using cached /Users/zhengyong/17zuoye/cpp/vcpkg/downloads/qtbase-everywhere-src-5.12.8.tar.xz
-- Using source at /Users/zhengyong/17zuoye/cpp/vcpkg/buildtrees/qt5-base/src/5.12.8-58a5dc6709
xcodebuild: error: SDK "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk" cannot be located.
xcrun: error: unable to lookup item 'SDKVersion' in SDK '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk'
-- Detected OSX SDK Version: 
CMake Error at ports/qt5-base/portfile.cmake:250 (string):
  string sub-command REGEX, mode MATCH needs at least 5 arguments total to
  command.
Call Stack (most recent call first):
  scripts/ports.cmake:73 (include)

Error: Building package qt5-base:x64-osx failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: qt5-base:x64-osx
  Vcpkg version: 2020.02.04-unknownhash

Additionally, attach any relevant sections from the log files above.

I have already executed update:
./vcpkg update
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.

git pull is ok:
git pull
Already up to date.

**Comment by Septarius** [comment]
I believe the offending line is `xcrun: error: unable to lookup item 'SDKVersion'` which points to xcode not being installed or xcode command line tools not being installed properly.

**Comment by justin-bj** [comment]
xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates

![image](https://user-images.githubusercontent.com/21333566/85830535-58857800-b7bf-11ea-8708-ac3426f79ec6.png)

**Comment by justin-bj** [comment]
> I believe the offending line is `xcrun: error: unable to lookup item 'SDKVersion'` which points to xcode not being installed or xcode command line tools not being installed properly.



xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates

**Comment by Septarius** [comment]
I don’t have a local Mac anymore to verify a build locally and it was a shot in the dark from me based on what search results came back for that error. Might know more when the Next OS X CI build runs.

**Comment by JackBoosY** [comment]
@Neumann-A Could you please take a look?

Thanks.

**Comment by Neumann-A** [comment]
@JackBoosY: Don't have OSX so cannot help here. In some issue here was another way to define/extract the platform SDK on osx but I couldn't find it with a quick search

**Comment by Neumann-A** [comment]
Found it https://github.com/microsoft/vcpkg/issues/10209#issuecomment-591367382

**Comment by JackBoosY** [comment]
Please track issue #10209.
