### ISSUE TITLE
[ gtest ] Update port to include fix for C++20 compliance

### ISSUE THREAD

**Issue by d-winsor** [microsoft/vcpkg#12115]
****

**Is your feature request related to a problem? Please describe.**
GTest in vcpkg uses std::result_of which was removed in C++20.

**Proposed solution**
The port should be updated/patched to include this fix from this commit https://github.com/google/googletest/commit/61f010d703b32de9bfb20ab90ece38ab2f25977f

**Comment by JonLiu1993** [comment]
After gtest releases the latest version, we will update the problem to the latest version
