### ISSUE TITLE
[angle] build failure

### ISSUE THREAD

**Issue by ankurverma85** [microsoft/vcpkg#12110]
**Host Environment**
- OS: linux
- Compiler: gcc-10

**To Reproduce**

`./vcpkg install angle`

And then use angle in a project by 
    target_link_libraries(${target} PRIVATE unofficial::angle::libANGLE unofficial::angle::libEGL unofficial::angle::libGLESv2)

This results in undefined reference to 
rx::DisplayEGL::DisplayEGL

There are no build issues in building angle itself from vcpkg but using vcpkg built binaries in another project

**Comment by ankurverma85** [comment]
Submitted pull request to fix the issue

https://github.com/microsoft/vcpkg/pull/12111

**Comment by PhoebeHui** [comment]
@ankurverma85, the PR has been merged, thanks for your contribution!
