### ISSUE TITLE
vcpkg Building package boost-atomic:x64-linux failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by MCl57** [microsoft/vcpkg#12121]
# command:  
./vcpkg install boost-atomic
# log:
Computing installation plan...
The following packages will be built and installed:
    boost-atomic[core]:x64-linux
Starting package 1/1: boost-atomic:x64-linux
Building package boost-atomic[core]:x64-linux...
-- Using cached /vcpkg/downloads/boostorg-atomic-boost-1.73.0.tar.gz
-- Using source at /vcpkg/buildtrees/boost-atomic/src/ost-1.73.0-3741af45ab
CMake Error at installed/x64-linux/share/boost-build/boost-modular-build.cmake:34 (message):
  The x86 boost-build tools must be installed to build for non-x86/x64
  platforms.  Please run `vcpkg install boost-build:x86-windows`.
Call Stack (most recent call first):
  ports/boost-atomic/portfile.cmake:12 (boost_modular_build)
  scripts/ports.cmake:73 (include)

Error: Building package boost-atomic:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-atomic:x64-linux
  Vcpkg version: 2020.02.04-unknownhash

**Environment**
- OS: Windows 10  2004,19041.330 with Docker container ubuntu
- path c:\..\vcpkg is in windows and ubuntu, mounted for ubuntu

**To Reproduce**

```
# dockerfile

# our local base image
FROM ubuntu 

LABEL description="Container for use with Visual Studio" 

# install build dependencies 
RUN apt-get update 
RUN apt-get install -y g++
RUN apt-get install -y rsync
RUN apt-get install -y zip
RUN apt-get install -y openssh-server
RUN apt-get install -y make 
RUN apt-get install -y ninja-build
RUN apt-get install -y gdbserver
RUN apt-get install -y git
RUN apt-get install -y curl unzip tar

# configure SSH for communication with Visual Studio 
RUN mkdir -p /var/run/sshd

RUN echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config && \ 
   ssh-keygen -A 

# expose port 22 
EXPOSE 22

# Start service
RUN service ssh start
# User add
RUN useradd -m -d /home/user -s /bin/bash -G sudo user
# set Password
RUN echo chpasswd user:password
#
RUN apt-get install -y mc
# end of dockerfile
```
# create-docker-container.cmd
```
docker --version
pause
rem https://devblogs.microsoft.com/cppblog/build-c-applications-in-a-linux-docker-container-with-visual-studio/
rem pulling down an image of the Ubuntu OS
docker pull ubuntu
docker images
docker build -t ubuntu-vs .
pause
docker run -p 5000:22 -i -t -v /c/work/CIRCLE/docker:/projects -v /c/work/git/vcpkg:/vcpkg ubuntu-vs /bin/bash
pause
```

# Commands to install vcpkg on ubuntu
```
./bootstrap-vcpkg.sh
./vcpkg update
```

**Comment by PhoebeHui** [comment]
@MCl57, thanks for reporting this issue!

Could you try to run './vcpkg install boost-build' first, and check if  "./installed/x64-linux/tools/boost-build" exist, if yes, could you try run './vcpkg isntall boost-atomic' again?

**Comment by PhoebeHui** [comment]
We have a PR https://github.com/microsoft/vcpkg/pull/11880, should address the failure:
```
CMake Error at installed/x64-linux/share/boost-build/boost-modular-build.cmake:34 (message):
The x86 boost-build tools must be installed to build for non-x86/x64
platforms. Please run vcpkg install boost-build:x86-windows.
```

**Comment by MCl57** [comment]
sorry, it doesn't work. I updated everything. I installed the full boost: x86-windows. No improvement ??? Do you have another suggestion please? Unfortunately the other branch #11880 does not help me.

### logs:
**root@50bb338af8f3:/vcpkg# ./vcpkg install evpp --recurse**
Computing installation plan...
The following packages will be built and installed:
  * boost-atomic[core]:x64-linux
  * boost-lockfree[core]:x64-linux
    evpp[core]:x64-linux
  * libevent[core,openssl,thread]:x64-linux
Additional packages (*) will be modified to complete this operation.
Starting package 1/4: boost-atomic:x64-linux
Building package boost-atomic[core]:x64-linux...
-- Using cached /vcpkg/downloads/boostorg-atomic-boost-1.73.0.tar.gz
-- Using source at /vcpkg/buildtrees/boost-atomic/src/ost-1.73.0-3741af45ab
CMake Error at installed/x64-linux/share/boost-build/boost-modular-build.cmake:34 (message):
  The x86 boost-build tools must be installed to build for non-x86/x64
  platforms.  Please run `vcpkg install boost-build:x86-windows`.
Call Stack (most recent call first):
  ports/boost-atomic/portfile.cmake:12 (boost_modular_build)
  scripts/ports.cmake:76 (include)


Error: Building package boost-atomic:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-atomic:x64-linux
  Vcpkg version: 2020.06.15-unknownhash

Additionally, attach any relevant sections from the log files above.
**root@50bb338af8f3:/vcpkg# git pull**
Already up to date.
**root@50bb338af8f3:/vcpkg# ./vcpkg update**
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.
root@50bb338af8f3:/vcpkg# ./vcpkg install boost-build:x86-windows
Computing installation plan...
The following packages are already installed:
    boost-build[core]:x86-windows
Package boost-build:x86-windows is already installed

Total elapsed time: 31.5 us

**root@50bb338af8f3:/vcpkg# ./vcpkg install boost-atomic --recurse**
Computing installation plan...
The following packages will be built and installed:
    boost-atomic[core]:x64-linux
Starting package 1/1: boost-atomic:x64-linux
Building package boost-atomic[core]:x64-linux...
-- Using cached /vcpkg/downloads/boostorg-atomic-boost-1.73.0.tar.gz
-- Using source at /vcpkg/buildtrees/boost-atomic/src/ost-1.73.0-3741af45ab
CMake Error at installed/x64-linux/share/boost-build/boost-modular-build.cmake:34 (message):
  The x86 boost-build tools must be installed to build for non-x86/x64
  platforms.  Please run `vcpkg install boost-build:x86-windows`.
Call Stack (most recent call first):
  ports/boost-atomic/portfile.cmake:12 (boost_modular_build)
  scripts/ports.cmake:76 (include)


Error: Building package boost-atomic:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-atomic:x64-linux
  Vcpkg version: 2020.06.15-unknownhash

Additionally, attach any relevant sections from the log files above.
**root@50bb338af8f3:/vcpkg# ./vcpkg install boost-lockfree --recurse**
Computing installation plan...
The following packages will be built and installed:
  * boost-atomic[core]:x64-linux
    boost-lockfree[core]:x64-linux
Additional packages (*) will be modified to complete this operation.
Starting package 1/2: boost-atomic:x64-linux
Building package boost-atomic[core]:x64-linux...
-- Using cached /vcpkg/downloads/boostorg-atomic-boost-1.73.0.tar.gz
-- Using source at /vcpkg/buildtrees/boost-atomic/src/ost-1.73.0-3741af45ab
CMake Error at installed/x64-linux/share/boost-build/boost-modular-build.cmake:34 (message):
  The x86 boost-build tools must be installed to build for non-x86/x64
  platforms.  Please run `vcpkg install boost-build:x86-windows`.
Call Stack (most recent call first):
  ports/boost-atomic/portfile.cmake:12 (boost_modular_build)
  scripts/ports.cmake:76 (include)


Error: Building package boost-atomic:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-atomic:x64-linux
  Vcpkg version: 2020.06.15-unknownhash

Additionally, attach any relevant sections from the log files above.
**root@50bb338af8f3:/vcpkg#**


##Logs:

**root@50bb338af8f3:/vcpkg# ./vcpkg install boost**
Computing installation plan...
The following packages will be built and installed:
    boost[core]:x64-linux
  * boost-accumulators[core]:x64-linux
  * boost-algorithm[core]:x64-linux
  * boost-asio[core]:x64-linux
  * boost-assign[core]:x64-linux
  * boost-atomic[core]:x64-linux
  * boost-beast[core]:x64-linux
  * boost-bimap[core]:x64-linux
  * boost-chrono[core]:x64-linux
  * boost-compute[core]:x64-linux
  * boost-container[core]:x64-linux
  * boost-context[core]:x64-linux
  * boost-contract[core]:x64-linux
  * boost-convert[core]:x64-linux
  * boost-coroutine[core]:x64-linux
  * boost-coroutine2[core]:x64-linux
  * boost-date-time[core]:x64-linux
  * boost-dll[core]:x64-linux
  * boost-exception[core]:x64-linux
  * boost-filesystem[core]:x64-linux
  * boost-flyweight[core]:x64-linux
  * boost-foreach[core]:x64-linux
  * boost-geometry[core]:x64-linux
  * boost-gil[core]:x64-linux
  * boost-graph[core]:x64-linux
  * boost-graph-parallel[core]:x64-linux
  * boost-hana[core]:x64-linux
  * boost-heap[core]:x64-linux
  * boost-histogram[core]:x64-linux
  * boost-hof[core]:x64-linux
  * boost-icl[core]:x64-linux
  * boost-interprocess[core]:x64-linux
  * boost-iostreams[core]:x64-linux
  * boost-lexical-cast[core]:x64-linux
  * boost-local-function[core]:x64-linux
  * boost-locale[core]:x64-linux
  * boost-lockfree[core]:x64-linux
  * boost-log[core]:x64-linux
  * boost-math[core]:x64-linux
  * boost-metaparse[core]:x64-linux
  * boost-msm[core]:x64-linux
  * boost-multi-index[core]:x64-linux
  * boost-multiprecision[core]:x64-linux
  * boost-nowide[core]:x64-linux
  * boost-odeint[core]:x64-linux
  * boost-outcome[core]:x64-linux
  * boost-parameter-python[core]:x64-linux
  * boost-phoenix[core]:x64-linux
  * boost-poly-collection[core]:x64-linux
  * boost-process[core]:x64-linux
  * boost-program-options[core]:x64-linux
  * boost-property-map[core]:x64-linux
  * boost-property-tree[core]:x64-linux
  * boost-proto[core]:x64-linux
  * boost-ptr-container[core]:x64-linux
  * boost-python[core]:x64-linux
  * boost-qvm[core]:x64-linux
  * boost-random[core]:x64-linux
  * boost-range[core]:x64-linux
  * boost-regex[core]:x64-linux
  * boost-safe-numerics[core]:x64-linux
  * boost-scope-exit[core]:x64-linux
  * boost-serialization[core]:x64-linux
  * boost-signals2[core]:x64-linux
  * boost-sort[core]:x64-linux
  * boost-spirit[core]:x64-linux
  * boost-stacktrace[core]:x64-linux
  * boost-statechart[core]:x64-linux
  * boost-static-string[core]:x64-linux
  * boost-system[core]:x64-linux
  * boost-test[core]:x64-linux
  * boost-thread[core]:x64-linux
  * boost-timer[core]:x64-linux
  * boost-type-erasure[core]:x64-linux
  * boost-ublas[core]:x64-linux
  * boost-units[core]:x64-linux
  * boost-unordered[core]:x64-linux
  * boost-uuid[core]:x64-linux
  * boost-variant2[core]:x64-linux
  * boost-vmd[core]:x64-linux
  * boost-wave[core]:x64-linux
  * boost-xpressive[core]:x64-linux
  * boost-yap[core]:x64-linux
Additional packages (*) will be modified to complete this operation.
Starting package 1/83: boost-exception:x64-linux
Building package boost-exception[core]:x64-linux...
-- Using cached /vcpkg/downloads/boostorg-exception-boost-1.73.0.tar.gz
-- Using source at /vcpkg/buildtrees/boost-exception/src/ost-1.73.0-f8dcf39b91
CMake Error at installed/x64-linux/share/boost-build/boost-modular-build.cmake:34 (message):
  The x86 boost-build tools must be installed to build for non-x86/x64
  platforms.  Please run `vcpkg install boost-build:x86-windows`.
Call Stack (most recent call first):
  ports/boost-exception/portfile.cmake:12 (boost_modular_build)
  scripts/ports.cmake:76 (include)


Error: Building package boost-exception:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-exception:x64-linux
  Vcpkg version: 2020.06.15-unknownhash

Additionally, attach any relevant sections from the log files above.
**root@50bb338af8f3:/vcpkg# ./vcpkg install boost-build:x86-windows**
Computing installation plan...
The following packages are already installed:
    boost-build[core]:x86-windows
Package boost-build:x86-windows is already installed

Total elapsed time: 27.4 us

**root@50bb338af8f3:/vcpkg# ./vcpkg update**
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.
root@50bb338af8f3:/vcpkg# git pull
Already up to date.
**root@50bb338af8f3:/vcpkg# ./vcpkg update**
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.
**root@50bb338af8f3:/vcpkg#**

**Comment by MCl57** [comment]
with last update vcpkg it works. 
thank you
