### ISSUE TITLE
Package: boost-build:x86-windows

### ISSUE THREAD

**Issue by gcardi** [microsoft/vcpkg#12125]
**Host Environment**
- OS: Windows 10 Pro x64
- Compiler: VS 2019 Community

**To Reproduce**
`./vcpkg install boost:x86-windows-static

**Failure logs** 
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
Computing installation plan...
The following packages will be built and installed:
    boost[core]:x86-windows-static
  * boost-accumulators[core]:x86-windows-static
  * boost-algorithm[core]:x86-windows-static
  * boost-align[core]:x86-windows-static
  * boost-any[core]:x86-windows-static
  * boost-asio[core]:x86-windows-static
  * boost-assign[core]:x86-windows-static
  * boost-atomic[core]:x86-windows-static
  * boost-beast[core]:x86-windows-static
  * boost-bimap[core]:x86-windows-static
  * boost-build[core]:x86-windows-static
  * boost-callable-traits[core]:x86-windows-static
  * boost-chrono[core]:x86-windows-static
  * boost-compute[core]:x86-windows-static
  * boost-container[core]:x86-windows-static
  * boost-context[core]:x86-windows-static
  * boost-contract[core]:x86-windows-static
  * boost-convert[core]:x86-windows-static
  * boost-coroutine[core]:x86-windows-static
  * boost-coroutine2[core]:x86-windows-static
  * boost-crc[core]:x86-windows-static
  * boost-date-time[core]:x86-windows-static
  * boost-disjoint-sets[core]:x86-windows-static
  * boost-dll[core]:x86-windows-static
  * boost-dynamic-bitset[core]:x86-windows-static
  * boost-endian[core]:x86-windows-static
  * boost-exception[core]:x86-windows-static
  * boost-fiber[core]:x86-windows-static
  * boost-filesystem[core]:x86-windows-static
  * boost-flyweight[core]:x86-windows-static
  * boost-foreach[core]:x86-windows-static
  * boost-format[core]:x86-windows-static
  * boost-function[core]:x86-windows-static
  * boost-functional[core]:x86-windows-static
  * boost-geometry[core]:x86-windows-static
  * boost-gil[core]:x86-windows-static
  * boost-graph[core]:x86-windows-static
  * boost-graph-parallel[core]:x86-windows-static
  * boost-hana[core]:x86-windows-static
  * boost-heap[core]:x86-windows-static
  * boost-histogram[core]:x86-windows-static
  * boost-hof[core]:x86-windows-static
  * boost-icl[core]:x86-windows-static
  * boost-interprocess[core]:x86-windows-static
  * boost-intrusive[core]:x86-windows-static
  * boost-io[core]:x86-windows-static
  * boost-iostreams[core]:x86-windows-static
  * boost-lambda[core]:x86-windows-static
  * boost-lexical-cast[core]:x86-windows-static
  * boost-local-function[core]:x86-windows-static
  * boost-locale[core]:x86-windows-static
  * boost-lockfree[core]:x86-windows-static
  * boost-log[core]:x86-windows-static
  * boost-math[core]:x86-windows-static
  * boost-metaparse[core]:x86-windows-static
  * boost-modular-build-helper[core]:x86-windows-static
  * boost-mp11[core]:x86-windows-static
  * boost-msm[core]:x86-windows-static
  * boost-multi-array[core]:x86-windows-static
  * boost-multi-index[core]:x86-windows-static
  * boost-multiprecision[core]:x86-windows-static
  * boost-odeint[core]:x86-windows-static
  * boost-outcome[core]:x86-windows-static
  * boost-parameter[core]:x86-windows-static
  * boost-parameter-python[core]:x86-windows-static
  * boost-phoenix[core]:x86-windows-static
  * boost-poly-collection[core]:x86-windows-static
  * boost-polygon[core]:x86-windows-static
  * boost-pool[core]:x86-windows-static
  * boost-process[core]:x86-windows-static
  * boost-program-options[core]:x86-windows-static
  * boost-property-map[core]:x86-windows-static
  * boost-property-tree[core]:x86-windows-static
  * boost-proto[core]:x86-windows-static
  * boost-ptr-container[core]:x86-windows-static
  * boost-python[core]:x86-windows-static
  * boost-qvm[core]:x86-windows-static
  * boost-random[core]:x86-windows-static
  * boost-range[core]:x86-windows-static
  * boost-ratio[core]:x86-windows-static
  * boost-rational[core]:x86-windows-static
  * boost-regex[core]:x86-windows-static
  * boost-safe-numerics[core]:x86-windows-static
  * boost-scope-exit[core]:x86-windows-static
  * boost-serialization[core]:x86-windows-static
  * boost-signals2[core]:x86-windows-static
  * boost-sort[core]:x86-windows-static
  * boost-spirit[core]:x86-windows-static
  * boost-stacktrace[core]:x86-windows-static
  * boost-statechart[core]:x86-windows-static
  * boost-system[core]:x86-windows-static
  * boost-test[core]:x86-windows-static
  * boost-thread[core]:x86-windows-static
  * boost-timer[core]:x86-windows-static
  * boost-tokenizer[core]:x86-windows-static
  * boost-tti[core]:x86-windows-static
  * boost-type-erasure[core]:x86-windows-static
  * boost-type-index[core]:x86-windows-static
  * boost-ublas[core]:x86-windows-static
  * boost-units[core]:x86-windows-static
  * boost-unordered[core]:x86-windows-static
  * boost-uuid[core]:x86-windows-static
  * boost-variant[core]:x86-windows-static
  * boost-variant2[core]:x86-windows-static
  * boost-vmd[core]:x86-windows-static
  * boost-wave[core]:x86-windows-static
  * boost-winapi[core]:x86-windows-static
  * boost-xpressive[core]:x86-windows-static
  * boost-yap[core]:x86-windows-static
  * bzip2[core]:x86-windows-static
  * libffi[core]:x86-windows-static
  * liblzma[core]:x86-windows-static
  * openssl[core]:x86-windows-static
  * openssl-windows[core]:x86-windows-static
  * python3[core]:x86-windows-static
  * zlib[core]:x86-windows-static
  * zstd[core]:x86-windows-static
Additional packages (*) will be modified to complete this operation.
Starting package 1/117: boost-build:x86-windows-static
Building package boost-build[core]:x86-windows-static...
-- Using community triplet x86-windows-static. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: C:\Users\Giuliano\source\repos\cpprestsdk\vcpkg\triplets\community\x86-windows-static.cmake
Warning: The following VS instances are excluded because the English language pack is unavailable.
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    C:\Program Files (x86)\Microsoft Visual Studio 12.0\
Please install the English language pack.
-- Using cached C:/Users/Giuliano/source/repos/cpprestsdk/vcpkg/downloads/boostorg-build-boost-1.72.0.tar.gz
-- Using source at C:/Users/Giuliano/source/repos/cpprestsdk/vcpkg/buildtrees/boost-build/src/ost-1.72.0-fa8b817276
-- Using cached C:/Users/Giuliano/source/repos/cpprestsdk/vcpkg/downloads/boost_LICENSE_1_0.txt
-- Using cached C:/Users/Giuliano/source/repos/cpprestsdk/vcpkg/downloads/boost-1.72.0-boostcpp.jam
-- Installing: C:/Users/Giuliano/source/repos/cpprestsdk/vcpkg/packages/boost-build_x86-windows-static/share/boost-build/copyright
-- Installing: C:/Users/Giuliano/source/repos/cpprestsdk/vcpkg/packages/boost-build_x86-windows-static/tools/boost-build/boostcpp.jam
-- Bootstrapping...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: C:/Users/Giuliano/source/repos/cpprestsdk/vcpkg/packages/boost-build_x86-windows-static/tools/boost-build/bootstrap.bat msvc
    Working Directory: C:/Users/Giuliano/source/repos/cpprestsdk/vcpkg/packages/boost-build_x86-windows-static/tools/boost-build
    Error code: 1
    See logs for more information:
      C:\Users\Giuliano\source\repos\cpprestsdk\vcpkg\buildtrees\boost-build\bootstrap-x86-windows-static-out.log
      C:\Users\Giuliano\source\repos\cpprestsdk\vcpkg\buildtrees\boost-build\bootstrap-x86-windows-static-err.log

Call Stack (most recent call first):
  ports/boost-build/portfile.cmake:55 (vcpkg_execute_required_process)
  scripts/ports.cmake:90 (include)

**Error: Building package boost-build:x86-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-build:x86-windows-static
  Vcpkg version: 2020.02.04-nohash**

**Comment by rockonedege** [comment]
As the error says: you'll probably need to install the English language  package from VS installer

**Comment by gcardi** [comment]
Thank you.

I’ve missed the line, sorry. My fault.

Now it’s all ok.

Thanks again.
