### ISSUE TITLE
[New Port Request] MOAB

### ISSUE THREAD

**Issue by liyangrock** [microsoft/vcpkg#12127]
Library name: MOAB

Library description: The Mesh-Oriented datABase MOAB is a component for representing and evaluating mesh data. MOAB can store structured and unstructured mesh, consisting of elements in the finite element “zoo” plus polygons and polyhedra. The functional interface to MOAB is simple yet powerful, allowing the representation of many types of metadata commonly found on the mesh. MOAB is optimized for efficiency in space and time, based on access to mesh in chunks rather than through individual entities, while also versatile enough to support individual entity access.

Source repository URL: https://bitbucket.org/fathomteam/moab/src/master/

It would be great if you can add MOAB.
Thank you!

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
