### ISSUE TITLE
[skia] stack around the variable 'options' was corrupted

### ISSUE THREAD

**Issue by psionic12** [microsoft/vcpkg#12123]
First, an example here:

```
//#define GR_TEST_UTILS true

#include "skia/gpu/GrContextOptions.h"

void init_skia(int w, int h) {
  GrContextOptions options;
}


int main(void) {
  init_skia(960, 640);
}
```

this code works fine on Linux but crashs on Windows, the reason is that `GR_TEST_UTILS` is not defined on Windows, if a user do not add it manually, the size of class `GrContextOptions ` in header will not match with the actual size in the Skia library. Since it works fine on Linux with out a manually added `#define GR_TEST_UTILS true`, I guess there may some missing definition on Windows build?

**Comment by JackBoosY** [comment]
Hi @psionic12, thanks for reporting this issue!
Althought I can't repro this issue, I think we still need to add definitions `GR_TEST_UTILS` and `NOMINMAX`.

Thanks.

**Comment by linquize** [comment]
Do you use --triplet `x86-windows` or `x64-windows`?

**Comment by psionic12** [comment]
@linquize, @JackBoosY , I used x64-windows

**Comment by psionic12** [comment]
@JackBoosY , have you met situations like this before? That is, public API headers have macros which may lead to size of the class change?

For Skia, the main user (Chrome, Android, Flutter) build the library with other code together, so this won't be a problem. I think this is why they write like this without a second thought.

I want to know if any other ports have the same problem before, and how vcpkg deal with problem.

**Comment by JackBoosY** [comment]
@psionic12 For this situation, we need to modify the installed header file to add this macro definition.
But now, I don't know where we should add.

**Comment by mocabe** [comment]
Looks like Skia defines `GR_TEST_UTILS=1` for standalone, non-official builds.  
Since we build it on non-official mode for debug builds, should we just add "GR_TEST_UTILS=1" for `SKIA_DEFINITIONS_DBG`?
https://github.com/microsoft/vcpkg/blob/b7c476bade673002cac838043b29c40bb46e1b85/ports/skia/skiaConfig.cmake.in#L47-L63

**Comment by MonicaLiu0311** [comment]
`skia` has been updated to `0.36.0`, does your issue still exist?

**Comment by psionic12** [comment]
After all these years, I can't test if the new skia version works or not, I think it's ok to close this if you guys have no problems on Windows.

**Comment by MonicaLiu0311** [comment]
> After all these years, I can't test if the new skia version works or not, I think it's ok to close this if you guys have no problems on Windows.

Thanks for your reply, this issue will be closed.
