### ISSUE TITLE
[New Port Request] WebRTC

### ISSUE THREAD

**Issue by avrionov** [microsoft/vcpkg#12134]
Library name: WebRTC

Library description: An open framework for the web that enables Real-Time Communications (RTC)

Source repository URL: https://webrtc.googlesource.com/src/

Project homepage (if different from the source repository): https://webrtc.org/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by JackBoosY** [comment]
Duplicate with #6205.
