### ISSUE TITLE
[<boost-log>] build failure

### ISSUE THREAD

**Issue by alimai** [microsoft/vcpkg#12143]
**Host Environment**
- OS: [Windows10 professional ]
- Compiler: Microsoft Visual Studio Professional 2019, Version 16.6.2

**To Reproduce**
`./vcpkg install boost-log:x64-windows`

**Failure logs** 
Computing installation plan...
The following packages will be built and installed:
    boost-log[core]:x64-windows
Starting package 1/1: boost-log:x64-windows
Building package boost-log[core]:x64-windows...
-- Using cached E:/vcpkg/downloads/boostorg-log-boost-1.73.0.tar.gz
-- Using source at E:/vcpkg/buildtrees/boost-log/src/ost-1.73.0-3d57ed4a83
-- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: E:/vcpkg/installed/x64-windows/tools/boost-build/b2.exe --stagedir=E:/vcpkg/buildtrees/boost-log/x64-windows-rel/stage --build-dir=E:/vcpkg/buildtrees/boost-log/x64-windows-rel --user-config=E:/vcpkg/buildtrees/boost-log/x64-windows-rel/user-config.jam -j4 --debug-configuration --debug-building --debug-generators --disable-icu --ignore-site-config --hash -q -sZLIB_INCLUDE=E:/vcpkg/installed/x64-windows/include -sBZIP2_INCLUDE=E:/vcpkg/installed/x64-windows/include -sLZMA_INCLUDE=E:/vcpkg/installed/x64-windows/include -sZSTD_INCLUDE=E:/vcpkg/installed/x64-windows/include threading=multi threadapi=win32 runtime-link=shared link=shared address-model=64 architecture=x86 toolset=msvc -sZLIB_BINARY=zlib -sZLIB_LIBPATH=E:/vcpkg/installed/x64-windows/lib -sBZIP2_BINARY=bz2 -sBZIP2_LIBPATH=E:/vcpkg/installed/x64-windows/lib -sLZMA_BINARY=lzma -sLZMA_LIBPATH=E:/vcpkg/installed/x64-windows/lib -sZSTD_BINARY=zstd -sZSTD_LIBPATH=E:/vcpkg/installed/x64-windows/lib variant=release debug-symbols=on
    Working Directory: E:/vcpkg/buildtrees/boost-log/src/ost-1.73.0-3d57ed4a83/build
    Error code: 1
    See logs for more information:
      E:\vcpkg\buildtrees\boost-log\build-x64-windows-rel-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/boost-build/boost-modular-build.cmake:296 (vcpkg_execute_required_process)
  ports/boost-log/portfile.cmake:25 (boost_modular_build)
  scripts/ports.cmake:73 (include)

Error: Building package boost-log:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-log:x64-windows
  Vcpkg version: 2020.02.04-nohash

**Additional context**
Error information in 'build-x64-windows-rel-out.log':
compile-c-c++ E:\vcpkg\buildtrees\boost-log\x64-windows-rel\boost\build\f7648d467bd0eca359a8f1c09d34fcab\threadsafe_queue.obj
threadsafe_queue.cpp
E:\vcpkg\buildtrees\boost-log\src\ost-1.73.0-3d57ed4a83\include\boost/log/detail/adaptive_mutex.hpp(29): fatal error C1083: Cannot open include file: 'boost/assert/source_location.hpp': No such file or directory

    call "E:\vcpkg\buildtrees\boost-log\x64-windows-rel\boost\standalone\msvc\999faa3b40e90a2a5abbbc32b31cdb11\msvc-setup.bat" amd64 >nul
 cl @"E:\vcpkg\buildtrees\boost-log\x64-windows-rel\boost\build\f7648d467bd0eca359a8f1c09d34fcab\threadsafe_queue.obj.rsp" 

...failed compile-c-c++ E:\vcpkg\buildtrees\boost-log\x64-windows-rel\boost\build\f7648d467bd0eca359a8f1c09d34fcab\threadsafe_queue.obj...

Is there anything other I should provide?

**Comment by alimai** [comment]
There don't have the file "source_location.hpp" in my computer, and not be downloaded by vcpkg either.
So I remove the '#include <boost/assert/source_location.hpp>' and the following corresponding code in 'E:\vcpkg\buildtrees\boost-log\src\ost-1.73.0-3d57ed4a83\include\boost\log\detail\adaptive_mutex.hpp',  the 'boost-log' can be built now.
There should be a better solution somewhere I think.

**Comment by PhoebeHui** [comment]
@alimai, could you please try the below solution and see if the issue still occur for you?

1. Remove all boost related components with following command and rebuild boost again.
```
 ./vcpkg remove boost-vcpkg-helpers --recurse
 ./vcpkg remove boost-modular-build-helper
 ./vcpkg remove boost-build
```
2. Or you can get clean vcpkg source and try to build boost again.

When upgrade the boost to new revision, we need rebuild all related components and sync up all new files in new revision.

**Comment by PhoebeHui** [comment]
BTW, I double confirmed, boost-log:x64-windows built successfully for me.

Starting package 7/7: boost-log:x64-windows
Building package boost-log[core]:x64-windows...
-- Using cached E:/vcpkg/boost_173/vcpkg/downloads/boostorg-log-boost-1.73.0.tar.gz
-- Using source at E:/vcpkg/boost_173/vcpkg/buildtrees/boost-log/src/ost-1.73.0-3d57ed4a83
-- Building x64-windows-rel
-- Building x64-windows-rel done
-- Building x64-windows-dbg
-- Building x64-windows-dbg done
-- Packaging x64-windows-rel
-- Packaging x64-windows-rel done
-- Packaging x64-windows-dbg
-- Packaging x64-windows-dbg done
-- Packaging headers
-- Packaging headers done
-- Using cached E:/vcpkg/boost_173/vcpkg/downloads/boost_LICENSE_1_0.txt
-- Installing: E:/vcpkg/boost_173/vcpkg/packages/boost-log_x64-windows/share/boost-log/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package boost-log[core]:x64-windows... done
Installing package boost-log[core]:x64-windows...
Installing package boost-log[core]:x64-windows... done
Elapsed time for package boost-log:x64-windows: 2.773 min

Total elapsed time: 5.056 min

**Comment by alimai** [comment]
@PhoebeHui Thanks, 
It works when we do follow your first suggestion,Remove all boost related components and rebuild them.
The most boost components are update from V1.72 to V1.73, and the "source_location.hpp" appear.
So the reason may be that, boost-log V1.73 need the file "source_location.hpp" which kept in another boost component, and it just exist in V1.73.
