### ISSUE TITLE
gtk:x86-windows Installation failed

### ISSUE THREAD

**Issue by H-angel** [microsoft/vcpkg#12148]
**Host Environment**
- OS: [Windows10]
- Compiler: vs2019

**To Reproduce**
vcpkg install glib:x86-windows

**Failure logs** 
F:\vcpkg>vcpkg install glib:x86-windows
Computing installation plan...
The following packages will be built and installed:
    glib[core]:x86-windows
Starting package 1/1: glib:x86-windows
Building package glib[core]:x86-windows...
-- Downloading https://ftp.gnome.org/pub/gnome/sources/glib/2.52/glib-2.52.3.tar.xz...
-- Downloading https://ftp.gnome.org/pub/gnome/sources/glib/2.52/glib-2.52.3.tar.xz... Failed. Status: 7;"Couldn't connect to server"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:175 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  ports/glib/portfile.cmake:10 (vcpkg_download_distfile)
  scripts/ports.cmake:73 (include)

Error: Building package glib:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: glib:x86-windows
  Vcpkg version: 2020.02.04-nohash

Additionally, attach any relevant sections from the log files above.

**Additional context**
安装gtk的时候一直报glib安装包出错，然后我专门安装glib也是错，求解，谢谢。

**Comment by zcream** [comment]
Try it using PowerShell in Administrator mode. Most of my problems went away when I did that.

**Comment by JackBoosY** [comment]
It seems that you can't reach the source website, please download [this](https://github.com/microsoft/vcpkg/files/4849168/glib-2.52.3.tar.xz.zip), unzip it and put it into _VCPKG_PATH/downloads_ then rebuild glib.

(Or you can use my [private chinese mirror branch](https://github.com/JackBoos/vcpkg/tree/mirror_zhCN))

Thanks.

**Comment by Wang-shuimu** [comment]
> 在管理员模式下使用PowerShell尝试一下。当我这样做时，我的大多数问题都消失了。

PS F:\vcpkg> .\vcpkg install gtk:x86-windows
Computing installation plan...
The following packages will be built and installed:
    gtk[core]:x86-windows
  * harfbuzz[core,glib]:x86-windows
  * libepoxy[core]:x86-windows
  * pango[core]:x86-windows
  * ragel[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/5: libepoxy:x86-windows
Building package libepoxy[core]:x86-windows...
-- Using cached F:/vcpkg/downloads/anholt-libepoxy-1.5.4.tar.gz
-- Using source at F:/vcpkg/buildtrees/libepoxy/src/1.5.4-337c486045
-- Acquiring MSYS Packages...
-- Acquiring MSYS Packages... OK
-- Configuring x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: F:/vcpkg/downloads/tools/python/python-3.8.3-x86/python.exe F:/vcpkg/downloads/tools/meson/meson-0.54.2/meson.py -Denable-glx=no -Denable-egl=no -Dcmake_prefix_path=['F:/vcpkg/installed/x86-windows','F:/vcpkg/installed/x86-windows/share'] --buildtype plain --backend ninja --wrap-mode nodownload --default-library shared --libdir lib --prefix F:/vcpkg/packages/libepoxy_x86-windows/debug --includedir ../include F:/vcpkg/buildtrees/libepoxy/src/1.5.4-337c486045 -Dc_args=['/nologo','/DWIN32','/D_WINDOWS','/W3','/MP','/D_DEBUG','/MDd','/Z7','/Ob0','/Od','/RTC1'] -Dcpp_args=['/nologo','/DWIN32','/D_WINDOWS','/W3','/GR','/EHsc','/MP','/D_DEBUG','/MDd','/Z7','/Ob0','/Od','/RTC1'] -Dc_link_args=[] -Dcpp_link_args=[]
    Working Directory: F:/vcpkg/buildtrees/libepoxy/x86-windows-dbg
    Error code: 2
    See logs for more information:
      F:\vcpkg\buildtrees\libepoxy\config-x86-windows-dbg-out.log
      F:\vcpkg\buildtrees\libepoxy\config-x86-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_meson.cmake:161 (vcpkg_execute_required_process)
  ports/libepoxy/portfile.cmake:16 (vcpkg_configure_meson)
  scripts/ports.cmake:73 (include)


Error: Building package libepoxy:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libepoxy:x86-windows
  Vcpkg version: 2020.02.04-nohash

Additionally, attach any relevant sections from the log files above.
然后glib包的问题解决了，出来了这个问题，你可以帮我看一下吗

**Comment by Wang-shuimu** [comment]
> 看来您无法访问源网站，请下载[此文件](https://github.com/microsoft/vcpkg/files/4849168/glib-2.52.3.tar.xz.zip)，将其解压缩并放入_VCPKG_PATH / downloads，_然后重新_构建_ glib。
> 
> （或者您可以使用我的[私人中文镜像分支](https://github.com/JackBoos/vcpkg/tree/mirror_zhCN)，但这不是最新的。）
> 
> 谢谢。

谢谢你的帮助，我问题已经解决了，但是出来了新的问题，你看可以帮我解决一下吗
PS F:\vcpkg> .\vcpkg install gtk:x86-windows
Computing installation plan...
The following packages will be built and installed:
    gtk[core]:x86-windows
  * harfbuzz[core,glib]:x86-windows
  * libepoxy[core]:x86-windows
  * pango[core]:x86-windows
  * ragel[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/5: libepoxy:x86-windows
Building package libepoxy[core]:x86-windows...
-- Using cached F:/vcpkg/downloads/anholt-libepoxy-1.5.4.tar.gz
-- Using source at F:/vcpkg/buildtrees/libepoxy/src/1.5.4-337c486045
-- Acquiring MSYS Packages...
-- Acquiring MSYS Packages... OK
-- Configuring x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: F:/vcpkg/downloads/tools/python/python-3.8.3-x86/python.exe F:/vcpkg/downloads/tools/meson/meson-0.54.2/meson.py -Denable-glx=no -Denable-egl=no -Dcmake_prefix_path=['F:/vcpkg/installed/x86-windows','F:/vcpkg/installed/x86-windows/share'] --buildtype plain --backend ninja --wrap-mode nodownload --default-library shared --libdir lib --prefix F:/vcpkg/packages/libepoxy_x86-windows/debug --includedir ../include F:/vcpkg/buildtrees/libepoxy/src/1.5.4-337c486045 -Dc_args=['/nologo','/DWIN32','/D_WINDOWS','/W3','/MP','/D_DEBUG','/MDd','/Z7','/Ob0','/Od','/RTC1'] -Dcpp_args=['/nologo','/DWIN32','/D_WINDOWS','/W3','/GR','/EHsc','/MP','/D_DEBUG','/MDd','/Z7','/Ob0','/Od','/RTC1'] -Dc_link_args=[] -Dcpp_link_args=[]
    Working Directory: F:/vcpkg/buildtrees/libepoxy/x86-windows-dbg
    Error code: 2
    See logs for more information:
      F:\vcpkg\buildtrees\libepoxy\config-x86-windows-dbg-out.log
      F:\vcpkg\buildtrees\libepoxy\config-x86-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_meson.cmake:161 (vcpkg_execute_required_process)
  ports/libepoxy/portfile.cmake:16 (vcpkg_configure_meson)
  scripts/ports.cmake:73 (include)


Error: Building package libepoxy:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libepoxy:x86-windows
  Vcpkg version: 2020.02.04-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by Wang-shuimu** [comment]
[config-x86-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/4850993/config-x86-windows-dbg-err.log)
[config-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/4850994/config-x86-windows-dbg-out.log)
这个是新问题的日志

**Comment by JackBoosY** [comment]
```
UnicodeDecodeError: 'gbk' codec can't decode byte 0x84 in position 352815: illegal multibyte sequence
```
Could you remove _VCPKG_PATH/buildtrees/libeopxy_  and try again?

Thanks.

**Comment by H-angel** [comment]
> ```
> UnicodeDecodeError: 'gbk' codec can't decode byte 0x84 in position 352815: illegal multibyte sequence
> ```
> 
> Could you remove _VCPKG_PATH/buildtrees/libeopxy_ and try again?
> 
> Thanks.

I tried your method, but I still can't
This is the result of my attempt，can you help me solve it，thanks
PS F:\vcpkg> .\vcpkg install gtk:x86-windows
Computing installation plan...
The following packages will be rebuilt:
  * harfbuzz[core,glib]:x86-windows
The following packages will be built and installed:
    gtk[core]:x86-windows
  * libepoxy[core]:x86-windows
  * pango[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
If you are sure you want to rebuild the above packages, run the command with the --recurse option

**Comment by JackBoosY** [comment]
Hmm...I..don't know why, but I can find this issue on the stackoverflow:
https://stackoverflow.com/questions/28165639/unicodedecodeerror-gbk-codec-cant-decode-byte-0x80-in-position-0-illegal-mult

other link:
https://blog.csdn.net/lqzdreamer/article/details/76549256
https://www.cnblogs.com/mengyu/p/6638975.html

This issue may be related to system settings or manually installed libraries/tools.

**Comment by H-angel** [comment]
> Hmm...I..don't know why, but I can find this issue on the stackoverflow:
> https://stackoverflow.com/questions/28165639/unicodedecodeerror-gbk-codec-cant-decode-byte-0x80-in-position-0-illegal-mult
> 
> other link:
> https://blog.csdn.net/lqzdreamer/article/details/76549256
> https://www.cnblogs.com/mengyu/p/6638975.html
> 
> This issue may be related to system settings or manually installed libraries/tools.

Thank for your help.

**Comment by JackBoosY** [comment]
Please use the following workaround:
https://github.com/microsoft/vcpkg/issues/12865#issuecomment-673216071

**Comment by JackBoosY** [comment]
Hi @H-angel, does this issue still exist?

**Comment by H-angel** [comment]
> @ H-angel，您好，这个问题仍然存在吗？

Thank you for your help. I have solved the problem。Thanks.
