### ISSUE TITLE
[qt5-webengine] build failure due to missing zlibd1.dll in tools\qt5\debug\bin

### ISSUE THREAD

**Issue by david-antiteum** [microsoft/vcpkg#12152]
**Host Environment**
- OS: Windows
- Compiler: VS 2019 16.6.2

**To Reproduce**
`./vcpkg remove protobuf`
`./vcpkg install qt5-webengine`

**Additional context**

After by-passing case #12150 uninstalling protobuf, the next error appears when rcc.exe is called for the debug build. It fails to start because `%VCPKG_ROOT%\installed\x64-windows\tools\qt5\debug\bin` doesn't have zlibd1.dll.

Hovewer, for the release version, the folder `%VCPKG_ROOT%\installed\x64-windows\tools\qt5\bin` contains zlib1.dll.

Thanks.

**Comment by Neumann-A** [comment]
Hmm interesting. I wonder why it worked for me. 
I also see:
`E:\qt\installed\x64-windows\tools\qt5\debug\bin\rcc.exe -name resources E:\qt\buildtrees\qt5-webengine\src\5.15.0-c7b80f6f6f\src\pdf\quick\resources.qrc -o .rcc\debug\qrc_resources.cpp`
and also don't have the dll's in `tools\qt5\debug\bin` (shouldn't matter that it is 5.15)

>Compiler: VS 2019 16.6.2

Be aware that compiling Qt with that VS version is broken without the patch added into 5.15 https://github.com/microsoft/vcpkg/pull/11596/commits/a3426977ff5dc8032bab5f09ce1d4aac52ef6845

**Comment by david-antiteum** [comment]
> Be aware that compiling Qt with that VS version is broken without the patch added into 5.15 [a342697](https://github.com/microsoft/vcpkg/commit/a3426977ff5dc8032bab5f09ce1d4aac52ef6845)

5.15 is not yet in master, right? any ETA?,

**Comment by Neumann-A** [comment]
you can probably simply "backport" (i.e just apply it) to current qt5-base. But that is a question you have to ask @JackBoosY and @BillyONeal because it requires a VM update for the linux ci to successfully run (Missing system libs).
