### ISSUE TITLE
qt5-webengine build failure

### ISSUE THREAD

**Issue by david-antiteum** [microsoft/vcpkg#12150]
**Host Environment**
- OS: Windows
- Compiler: VS 2019 16.6.2

**To Reproduce**
`./vcpkg install protobuf`
`./vcpkg install qt5-webengine`

**Additional context**

The current version of qt5-webengine compiles and uses a private copy of protobuf version 3.2.0. The current version of the protobuf package in vcpkg is 3.12.0. When compiling qt5-webengine, it generates the pb.h files with its internal version but, when builing, it finds the includes for protobuf 3.12.0 generating the error:

`This file was generated by an older version of protoc which is incompatible with your Protocol Buffer headers.  Please update your headers.`

Thanks,

David

**Comment by Neumann-A** [comment]
According to the cpp qt slack there is nothing which can be done here. You have to uninstall the headers provided by vcpkg. But that explains why it fails in CI but is locally successful if protobuf is not installed ;)

To cite:
```
Thiago Macieira  
10:24 PM The protoc problem happens because Google is Google.
10:25 They don't like to do libraries the proper way. It's "the Google Way or the highway" with them.
10:25 everything is pre-bundled and unbundling is a nightmare.
10:25 In your case, you must have some protoc headers that are interfering. Uninstall them.
```

**Comment by david-antiteum** [comment]
> But you probably can get away with first installing qt5-webengine and than protobuf as a workaround.

Unless you plan to use protobuf too. In this case you have two versions of the lib (and this a "highway" case).

Not sure why qt5-webengine needs a private copy of protobuf anyway. It is a vcpkg thing (something in the port) or a Qt thing?

Thanks for the support :)

**Comment by Neumann-A** [comment]
> It is a vcpkg thing (something in the port) or a Qt thing?

Qt thing. 

> Unless you plan to use protobuf too. In this case you have two versions of the lib (and this a "highway" case).

No you don't. Qt installs only Qt stuff. See here:
[qt5-webengine_5.15.0_x64-windows.txt](https://github.com/microsoft/vcpkg/files/4846363/qt5-webengine_5.15.0_x64-windows.txt)

**Comment by david-antiteum** [comment]
Just to complete information... With protobuf not installed and using the latest version in master that solves #12152 I have managed to build the debug version but not the release version. The latest error is:

```
%VCPKG_ROOT%\buildtrees\qt5-webengine\src\5.12.8-7a7f415e08\src\3rdparty\chromium\third_party\blink\renderer\core\css\parser\css_property_parser_helpers.cc(604) : fatal error C1001: Internal compiler error.
(compiler file 'd:\agent\_work\2\s\src\vctools\Compiler\Utc\src\p2\main.c', line 181)
 To work around this problem, try simplifying or changing the program near the locations listed above.
If possible please provide a repro here: https://developercommunity.visualstudio.com 
Please choose the Technical Support command on the Visual C++ 
 Help menu, or open the Technical Support help file for more information
  link!CloseTypeServerPDB()+0xe6771
  link!CloseTypeServerPDB()+0xe6771
```

This is for Qt 5.12.8-7a7f415e08

I don't need anything for this version, I can wait for Qt 5.15

Thanks,

**Comment by JackBoosY** [comment]
Hi @david-antiteum, does this issue still exist?

**Comment by david-antiteum** [comment]
No idea, I give up and now I´m using the Qt installation. It mixes quite well with vcpkg.

**Comment by JackBoosY** [comment]
Fine, please open a new issue if this issue still exist.
