### ISSUE TITLE
assimp build failure

### ISSUE THREAD

**Issue by pvarcholik** [microsoft/vcpkg#12154]
**Describe the bug**
Projects with assimp dependencies do not build (without workarounds).

**Environment**
- OS: Linux
- Compiler: g++ 9.3

**To Reproduce**
1. ./vcpkg install assimp
Post-installation instructions state:
```
The package assimp:x64-linux provides CMake targets:

    find_package(assimp CONFIG REQUIRED)
    target_link_libraries(main PRIVATE assimp::assimp)
```

2. Simple main.cpp with assimp dependency:
```
#include <assimp/Importer.hpp>

int main()
{
    Assimp::Importer importer;
    return 0;
}
```

3: CMakeLists.txt:
```
cmake_minimum_required(VERSION 3.15)

if(DEFINED ENV{VCPKG_ROOT} AND NOT DEFINED CMAKE_TOOLCHAIN_FILE)
  set(CMAKE_TOOLCHAIN_FILE "$ENV{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake" CACHE STRING "")
endif()

project (AssimpTest)
set(CMAKE_CXX_STANDARD 17)
add_compile_options(-Wall -Wextra -pedantic -Werror -Wno-ignored-qualifiers)

set(TARGET_NAME AssimpTest)
find_package(assimp CONFIG REQUIRED)
add_executable(${TARGET_NAME} "main.cpp")
target_link_libraries(${TARGET_NAME} PRIVATE assimp::assimp)
```

4. cmake .
5. make .

**Expected behavior**
A successful build that properly identifies and incorporates include paths and linker paths for assimp and assimp dependencies.

**Failure logs** 
CMakeFiles/AssimpTest.dir/build.make:82: *** target pattern contains no '%'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:75: CMakeFiles/AssimpTest.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

CMakeFiles/AssimpTest.dir/build.make line 82 contains:
AssimpTest: assimp::assimp-NOTFOUND

**Additional context**
If you were to replace assimp::assimp with simply assimp (which is the value of ${ASSIMP_LIBRARIES} -- the target used in the previous port) and rebuild you then get a compiler error:
main.cpp:1:10: fatal error: assimp/Importer.hpp: No such file or directory
    1 | #include <assimp/Importer.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.

i.e. the include directory is not set for this dependency. This can be addressed by adding the following to CMakeLists.txt (before the add_executable command):
```
set(INCLUDE_DIR "$ENV{VCPKG_ROOT}/installed/${VCPKG_TARGET_TRIPLET}/include")
include_directories(${INCLUDE_DIR})
```

This workaround allows the compilation to succeed but linking now fails with:
/usr/bin/ld: cannot find -lassimp
collect2: error: ld returned 1 exit status

i.e. the library directory is not set for this dependency. We can add:
```
set(LIBRARY_DIR "$ENV{VCPKG_ROOT}/installed/${VCPKG_TARGET_TRIPLET}/lib")
link_directories(${LIBRARY_DIR})
```

And now the linker will find libassimp.a. However, you'll now see numerous linker errors related to two libraries that assimp depends upon: libz.a and libIrrXML.a. Both of these libraries are installed with the installation of the assimp package but they are not included with a target_link_libraries(${TARGET_NAME} PRIVATE assimp::assimp). Instead, you must manually specify these dependencies by adding:
```
target_link_libraries(${TARGET_NAME} PRIVATE z)
target_link_libraries(${TARGET_NAME} PRIVATE IrrXML)
```

Thus, a final CMakeLists.txt file would be:
```
cmake_minimum_required(VERSION 3.15)

if(DEFINED ENV{VCPKG_ROOT} AND NOT DEFINED CMAKE_TOOLCHAIN_FILE)
  set(CMAKE_TOOLCHAIN_FILE "$ENV{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake" CACHE STRING "")
endif()

project (AssimpTest)

set(CMAKE_CXX_STANDARD 17)
add_compile_options(-Wall -Wextra -pedantic -Werror -Wno-ignored-qualifiers)

set(TARGET_NAME AssimpTest)

find_package(assimp CONFIG REQUIRED)

set(INCLUDE_DIR "$ENV{VCPKG_ROOT}/installed/${VCPKG_TARGET_TRIPLET}/include")
set(LIBRARY_DIR "$ENV{VCPKG_ROOT}/installed/${VCPKG_TARGET_TRIPLET}/lib")
include_directories(${INCLUDE_DIR})
link_directories(${LIBRARY_DIR})
add_executable(${TARGET_NAME} "main.cpp")

target_link_libraries(${TARGET_NAME} PRIVATE assimp)
target_link_libraries(${TARGET_NAME} PRIVATE z)
target_link_libraries(${TARGET_NAME} PRIVATE IrrXML)
```

This produces a successfully linked binary. However, none of that should be necessary -- and did not exist in a previous revision of this package. I see numerous commits to https://github.com/microsoft/vcpkg/tree/master/ports/assimp between 5 and 9 months ago. I suspect the error was introduced somewhere in that history.

Looking at existing issues and I see similar reports in a [number of open issues](https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+assimp), but I see no resolution.

**Comment by JackBoosY** [comment]
Confirmed.

**Comment by tomilov** [comment]
Sorry that I use this issue inappropriately, but this issue is the first result for

 > CMakeFiles/AssimpTest.dir/build.make:82: *** target pattern contains no '%'. Stop.

search request.

User-side fix for the problem, that arise when used system `assimp` library from `Debug` build is the next:

    find_package(assimp REQUIRED 5)
    set_target_properties(assimp::assimp PROPERTIES MAP_IMPORTED_CONFIG_DEBUG Release)

That is one have to "fix" `IMPORTED_CONFIGURATIONS` of `assimp::assimp` imported target before use of it in `Debug` configuration of your project (in `Release` configuration all should work fine without any modifications).

**Comment by JackBoosY** [comment]
@omilov I can't repro your problem on my machine. It works fine when I select Debug mode.
In _AssimpConfig-debug.cmake_ :
```
set_property(TARGET assimp::assimp APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(assimp::assimp PROPERTIES
  IMPORTED_IMPLIB_DEBUG "${_IMPORT_PREFIX}/debug/lib/assimp-vc141-mtd.lib"
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/debug/bin/assimp-vc141-mtd.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS assimp::assimp )
list(APPEND _IMPORT_CHECK_FILES_FOR_assimp::assimp "${_IMPORT_PREFIX}/debug/lib/assimp-vc141-mtd.lib" "${_IMPORT_PREFIX}/debug/bin/assimp-vc141-mtd.dll" )
```
It should be no problems.

**Comment by tomilov** [comment]
@JackBoosY There is no `AssimpConfig-debug.cmake` in release installation. Nevertheless my workaround is not for `vcpkg`, but for `pacman` (Archlinux).
![image](https://user-images.githubusercontent.com/896175/98653792-49165e00-235f-11eb-87b3-9424b0ee5c02.png)
