### ISSUE TITLE
Error: Building package harfbuzz:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by H-angel** [microsoft/vcpkg#12165]
**Host Environment**
- OS: windows10
- Compiler: vx2019

**To Reproduce**
`./vcpkg install gtk:x86-windows

**Failure logs** 
PS F:\vcpkg> .\vcpkg install  harfbuzz:x86-windows
Computing installation plan...
The following packages will be built and installed:
    harfbuzz[core]:x86-windows
Starting package 1/1: harfbuzz:x86-windows
Building package harfbuzz[core]:x86-windows...
-- Downloading https://github.com/harfbuzz/harfbuzz/archive/2.6.6.tar.gz...
-- Downloading https://github.com/harfbuzz/harfbuzz/archive/2.6.6.tar.gz... Failed. Status: 18;"Transferred a partial file"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:175 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:132 (vcpkg_download_distfile)
  ports/harfbuzz/portfile.cmake:1 (vcpkg_from_github)
  scripts/ports.cmake:73 (include)

Error: Building package harfbuzz:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: harfbuzz:x86-windows
  Vcpkg version: 2020.02.04-nohash

Additionally, attach any relevant sections from the log files above.

**Additional context**
安装这个出现了问题，我之前安装glib包错误的时候，别人建议我用管理员权限运行powershell。我试了一下，glib包安装好了，但是harfbuzz还是一样的error，求解，谢谢

**Comment by JackBoosY** [comment]
Also unzip [this](https://github.com/microsoft/vcpkg/files/4855223/harfbuzz-2.6.6.tar.gz.zip) and put it into the same directory, them rebuild harfbuzz would be okay.

**Comment by H-angel** [comment]
> Also unzip [this](https://github.com/microsoft/vcpkg/files/4855223/harfbuzz-2.6.6.tar.gz.zip) and put it into the same directory, them rebuild harfbuzz would be okay.

Thank for your help,this problem has been solved。
