### ISSUE TITLE
[netCDF] Fix dependency on embree (ParaView CI error)

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#12169]
@JackBoosY  The real culprit for the paraview CI error is the netCDF target. 
```
set_target_properties(netCDF::netcdf PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "${_IMPORT_PREFIX}/lib/libmath.a;ZLIB::ZLIB;hdf5::hdf5-static;hdf5::hdf5_hl-static;CURL::libcurl"
)
```
So the following needs fixing:
- add embree as a feature to netCDF and fix the build-depends. Deactivate the search for embree otherwise. 
- replace the direct library link with the embree maths target
- add the appropriate find_dependency call to netCDFConfig.cmake if build with the feature

**Comment by JackBoosY** [comment]
@Neumann-A Sorry, I can't find any code related to embree in port `netcdf-c` or `netcdf-cxx4` sources.
Could you double confirm that?

**Comment by Neumann-A** [comment]
It is not directly looking for embree but embree install `libmath.a` which is found here:
https://github.com/Unidata/netcdf-c/blob/3afce176ac0edf15adff1c281c3d3ab0a0814287/CMakeLists.txt#L874

**Comment by JackBoosY** [comment]
@Neumann-A I remeber you already report this issue on the upstream. Can you put the link here?

**Comment by Neumann-A** [comment]
@JackBoosY I did not report it to netcdf-c. I reported it to ParaView when I was looking for where the dependency might come from. But I closed the issue since it was not related to Paraview.
