### ISSUE TITLE
[ICU] buildtree needs to be delete before installing

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#12166]
I have a common problem running VCPKG from the same folder on Windows and Linux.

The ICU build fails on Linux with some cryptic error if ICU was previously build on Windows.

deleting the ICU buildtree solves the issue in general.

As such the portfile either needs to delete the buildtree before extraction or a dummy patch must be added to have different source trees for ICU on the two different platforms.

**Comment by LilyWangL** [comment]
@ras0219-msft My machine has no conditions to reproduce this issue, could you help to take a look this issue?
Thanks.

**Comment by LilyWangL** [comment]
I think this issue has been fixed in PR #12366, please reopen this issue if this is still a problem for you.
