### ISSUE TITLE
MSBuild integration: "Using triplet" message has high importance

### ISSUE THREAD

**Issue by gix** [microsoft/vcpkg#12164]
**Describe the bug**
vcpkg's msbuild integration (in `vcpkg.targets`) displays a message `Using triplet "x64-windows" from "<vcpkg-root>"`. Since #4361 this message has importance high (instead of the previous normal) which results in a lot of unnecessary build output. This change seems like a forgotten debugging aid missed in the review.

**To Reproduce**
1. `vcpkg install` and export any port as nuget.
2. Add the nuget package to a C++ project in Visual Studio.
3. Build with the default MSBuild verbosity (Minimal).

**Expected behavior**
No message.

**Comment by PhoebeHui** [comment]
@gix, thanks for reporting this issue!

For me, I'm okay to change the 'High' to 'Normal' in https://github.com/microsoft/vcpkg/blob/master/scripts/buildsystems/msbuild/vcpkg.targets#L90, and it will give message when the output set to 'Normal' or higher, reference from [verbosity-settings](https://docs.microsoft.com/en-us/visualstudio/msbuild/obtaining-build-logs-with-msbuild?view=vs-2019#verbosity-settings)

@Neumann-A, what do you think?
