### ISSUE TITLE
[New Port Request] apriltag

### ISSUE THREAD

**Issue by afraidofdark** [microsoft/vcpkg#12171]
Library name: apriltag

Library description: AprilTag is a visual fiducial system popular in robotics research. This repository contains the most recent version of AprilTag, AprilTag 3, which includes a faster (>2x) detector, improved detection rate on small tags, flexible tag layouts, and pose estimation. AprilTag consists of a small C library with minimal dependencies.

Source repository URL: https://github.com/AprilRobotics/apriltag

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
