### ISSUE TITLE
vcpkg manifest mode dependency with core feature

### ISSUE THREAD

**Issue by linquize** [microsoft/vcpkg#12187]
In vcpkg manifest mode, the following 

vcpkg.json
```
{
  "name": "project1",
  "version-string": "0.0.1",
  "dependencies": [
    {
      "name": "abc",
      "features": [ "core" ]
    }
  ]
}
```

```
Error: There are invalid field types in the CONTROL or manifest file of C:\project1\vcpkg.json
The following fields had the wrong types:

    features was expected to be an array of identifiers
```

This is because `core` is a reserved word. I have to use `"default-features": false` instead of `"features": [ "core" ]`

Could you document this behavior or provide an improvement?

**Comment by PhoebeHui** [comment]
Confirmed this issue fixed now, thanks for reporting this issue!

**Comment by linquize** [comment]
Why is it fixed? I suggest to document it.

**Comment by RDCH106** [comment]
I think the same as @linquize.

The normal case is to use _core_ in the same way as:

https://vcpkg.readthedocs.io/en/latest/specifications/feature-packages/

> When using `vcpkg install <package>`, some features will be enabled by default. These default features can be avoided by referring to the packages as `<package>[core] `and features can be added by supplying them on the same installation line.
