### ISSUE TITLE
Having a problem with vckpg: installing the Azure IoT SDK for C

### ISSUE THREAD

**Issue by SatishBoddu-MSFT** [microsoft/vcpkg#12180]
**Describe the bug**
I am following the MS docs quickstart on creating an IoT Plug and Play device for Windows i.e [Quickstart: Use a device capability model to create an IoT Plug and Play Preview device (Windows)](https://docs.microsoft.com/en-us/azure/iot-pnp/quickstart-create-pnp-device-windows) and I'm having issues preparing the development environment.

When I get to installing the SDK with vcpkg (step 2 in preparing the dev environment section) running this command gives me an error:

> .\vcpkg.exe install azure-iot-sdk-c[public-preview,use_prov_client]

![image](https://user-images.githubusercontent.com/62923178/86201549-b2b27000-bb14-11ea-9f80-75103d9c5dc5.png)

**Environment**
- OS: [e.g. Windows 10]
- Compiler: revision

**To Reproduce**
1. .\vcpkg.exe install azure-iot-sdk-c[public-preview,use_prov_client]
2. Error: <unknown>:1:47: invalid character in feature name (must be lowercase, digits, '-')
   on expression: azure-iot-sdk-c[public-preview,use_prov_client]
                                                                ^
Example:
  vcpkg install zlib zlib:x64-windows curl boost

Repro code when trying the Step2 on quickstart

**Expected behavior**
Install Azure IoT C device SDK Vcpkg: should be succesful.

**Failure logs** 
-Error: <unknown>:1:47: invalid character in feature name (must be lowercase, digits, '-')
   on expression: azure-iot-sdk-c[public-preview,use_prov_client]

**Additional context**
Similar issue reported on [Stackoverflow  ](https://stackoverflow.com/questions/62668096/having-a-problem-with-installing-the-azure-iot-sdk-for-c)as well.

**Comment by SatishBoddu-MSFT** [comment]
Hello @ericmitt , Could you please help us in this matter.

**Comment by NancyLi1013** [comment]
Hi @SatishBoddu-MSFT 
Thanks for posting this issue.
It seems that the feature name contains some invalid characters. You can update `use_prov_client` as `use-prov-client` in both CONTROL file and portfile.cmake. Then try to rebuild this.

**Comment by SatishBoddu-MSFT** [comment]
@NancyLi1013 Worked like a PRO!!!! Thanks a lot.
@ericmitt , How should we proceed further with the documentation?, do we have to include this workaround or will there be any changes from SDK side or VCPKG side ?

**Go to the Folder :** C:\Users\satish\vcpkg\ports\azure-iot-sdk-c
1) Edit the CONTROL file in any file editor,  **update**  _use_prov_client_ as **use-prov-client**


![image](https://user-images.githubusercontent.com/62923178/86327591-6cced800-bbf8-11ea-9a8a-dd580e4707a1.png)

2) Edit the portfile.cmake file : **update**  _use_prov_client_ as **use-prov-client**

![image](https://user-images.githubusercontent.com/62923178/86329729-70179300-bbfb-11ea-96d6-4396424b9af4.png)

3) run    
`.\bootstrap-vcpkg.bat`

4) run  
` .\vcpkg.exe install azure-iot-sdk-c[public-preview,use-prov-client]`

![image](https://user-images.githubusercontent.com/62923178/86330092-0350c880-bbfc-11ea-99bb-15f20bc23904.png)

**Comment by NancyLi1013** [comment]
@SatishBoddu-MSFT 
I have submitted a PR to fix this. 
Could you please help if it can work for you?

**Comment by SatishBoddu-MSFT** [comment]
> @SatishBoddu-MSFT
> I have submitted a PR to fix this.
> Could you please help if it can work for you?

@NancyLi1013 I did a fresh pull from github, used the updated command , it is Now Working!!!

> .\vcpkg.exe install azure-iot-sdk-c[public-preview,use-prov-client]

![image](https://user-images.githubusercontent.com/62923178/86488640-89f9c880-bd16-11ea-9ef0-2d0cae4454d3.png)

I have to update the documentation to reflect the updated command, below is the command which needs to be updated.

![image](https://user-images.githubusercontent.com/62923178/86488612-66cf1900-bd16-11ea-9093-5c3354f4405e.png)


Thanks again !

**Comment by NancyLi1013** [comment]
Yes, the feature name should be the same as that in CONTROL file. Thanks for your update.
