### ISSUE TITLE
Unable to download package wtl/9.1.0@lasote/vcpkg

### ISSUE THREAD

**Issue by definename** [Microsoft/vcpkg#1219]
Hi, all.
I am going to download wtl package wtl/9.1.0@lasote/vcpkg - but have error during downloading it.

That is error: 

> Failed. Status: 7;"Couldn't connect to server"

**Comment by ras0219-msft** [comment]
Hi @definedname!

This looks like a bug in lasote's Conan scripts or hosting. You'll need to post over on one of Conan's repos to get that issue fixed.

Alternatively, why not try out vcpkg directly? I'd recommend heading to our readme page, following our quickstart, then running `vcpkg install wtl`.

**Comment by ras0219-msft** [comment]
If you have any troubles with `vcpkg install wtl`, please open a new issue! Thanks!

**Comment by definename** [comment]
Looks like there was some trouble in my network. Sorry for wasting of time.

**Comment by ras0219-msft** [comment]
@definename I noticed you were interested in building cpprestsdk for MT/MTd[1].

Vcpkg builds libraries with static CRT linkage inside our `*-windows-static` triplets:
```
>vcpkg install cpprestsdk:x64-windows-static
```

[1] https://github.com/conan-io/conan/issues/1398

**Comment by definename** [comment]
How to configure conan file for this?
This is mine:

> [requires]
> Boost/1.64.0@inexorgame/stable
> cpprestsdk/2.8.0@lasote/vcpkg
> 
> [generators]
> cmake
> 
> [options]
> Boost:shared=False
> 
> [imports]
> bin, *.dll -> .Build/bin
> lib, *.dylib* -> .Build/bin

**Comment by ras0219-msft** [comment]
Hi @definedname, for help with Conan, I recommend posting to that project.

If you'd like to get cpprestsdk and boost using Vcpkg, you'll simply need to follow our [Quick Start](https://github.com/Microsoft/vcpkg#quick-start) and then run:
```
>vcpkg install cpprestsdk:x64-windows boost:x64-windows
```

Then you can use us in your CMake or MSBuild project by following our [first use tutorial](https://github.com/Microsoft/vcpkg/blob/df3f73d8256e549ad43efd0a84cd3691d91c9c10/docs/examples/using-sqlite.md#step-2-use).
