### ISSUE TITLE
[cmocka] build failure

### ISSUE THREAD

**Issue by danewalton** [microsoft/vcpkg#12193]
**Host Environment**
- OS: MacOS
- Compiler: revision

**To Reproduce**
- `./vcpkg install cmocka`
- Use cmocka via the instructions.
- Makefiles on OSX are no longer resolving the full path to the lib.

[Link to comment here](https://github.com/microsoft/vcpkg/commit/1d8f0acc9c3085d18152a3f639077a28109196b6#r40299706)

**Failure logs** 
``make[2]: *** No rule to make target `/lib/libcmocka-static.a', needed by``

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by strega-nil** [comment]
@danewalton I'm so sorry; can you try out the fix in #12196?
