### ISSUE TITLE
python3 fails to build

### ISSUE THREAD

**Issue by vladimirdlc** [Microsoft/vcpkg#1220]
I got this error trying to compile python3
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: python3:x86-windows
  Vcpkg version: 0.0.81-e573ed00a198ea609de095243ede3b40a8e79421

~\Documents\GitHub\vcpkg^C [master =]> .\vcpkg.exe install python3
The following packages will be built and installed:
    python3:x86-windows
Building package python3:x86-windows...
-- CURRENT_INSTALLED_DIR=C:/Users/vdelacruz/Documents/GitHub/vcpkg/installed/x86
-windows
-- DOWNLOADS=C:/Users/vdelacruz/Documents/GitHub/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/Users/vdelacruz/Documents/GitHub/vcpkg/packages/pytho
n3_x86-windows
-- CURRENT_BUILDTREES_DIR=C:/Users/vdelacruz/Documents/GitHub/vcpkg/buildtrees/p
ython3
-- CURRENT_PORT_DIR=C:/Users/vdelacruz/Documents/GitHub/vcpkg/ports/python3/.
-- Using cached C:/Users/vdelacruz/Documents/GitHub/vcpkg/downloads/python-cpyth
on-v3.6.1.tar.gz
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Building C:/Users/vdelacruz/Documents/GitHub/vcpkg/buildtrees/python3/src-x86
-windows/cpython-3.6.1/PCBuild/pythoncore.vcxproj for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:43 (message):
    Command failed: msbuild;C:/Users/vdelacruz/Documents/GitHub/vcpkg/buildtrees
/python3/src-x86-windows/cpython-3.6.1/PCBuild/pythoncore.vcxproj;/p:Configurati
on=Release;/t:Rebuild;/p:Platform=Win32;/p:PlatformToolset=v140;/p:VCPkgLocalApp
DataDisabled=true;/p:UseIntelMKL=No;/p:WindowsTargetPlatformVersion=10.0.15063.0
;/m
    Working Directory: C:/Users/vdelacruz/Documents/GitHub/vcpkg/buildtrees/pyth
on3/x86-windows-rel
    See logs for more information:
      C:\Users\vdelacruz\Documents\GitHub\vcpkg\buildtrees\python3\build-x86-win
dows-rel-out.log
      C:\Users\vdelacruz\Documents\GitHub\vcpkg\buildtrees\python3\build-x86-win
dows-rel-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_msbuild.cmake:92 (vcpkg_execute_required_process)
  ports/python3/portfile.cmake:58 (vcpkg_build_msbuild)
  scripts/ports.cmake:73 (include)

Error: Building package python3:x86-windows failed with: BUILD_FAILED

**Comment by Voskrese** [comment]
```
.\vcpkg.exe install python3 --debug
```
```
notepad  C:\Users\vdelacruz\Documents\GitHub\vcpkg\buildtrees\python3\build-x86-windows-rel-out.log
 C:\Users\vdelacruz\Documents\GitHub\vcpkg\buildtrees\python3\build-x86-windows-rel-err.log
```
windows sdk 10.0.15063.0 ???

**Comment by vladimirdlc** [comment]
Had installed 10.0.15063.400, is there any difference?

Will try with that version

Thanks

2017-06-05 15:04 GMT-04:00 Voskrese <notifications@github.com>:

**Comment by vladimirdlc** [comment]
[build-x86-windows-rel-out.txt](https://github.com/Microsoft/vcpkg/files/1052997/build-x86-windows-rel-out.txt)

The other file is empty

**Comment by Voskrese** [comment]
> TRACKER : error TRK0005: ‚chec de localisation deя: "rc.exe".
```
E:\tools\SRC\>where rc.exe
```
C:\Program Files (x86)\Windows Kits\10\bin\x86\rc.exe

**Comment by vladimirdlc** [comment]
![image](https://cloud.githubusercontent.com/assets/2165333/26801504/15e27c52-4a0b-11e7-999b-daa1d01c37b4.png)
It seems correct, unless it should show the same output in powershell

**Comment by vladimirdlc** [comment]
![image](https://cloud.githubusercontent.com/assets/2165333/26801657/8664964a-4a0b-11e7-800f-3dda0e94a3bb.png)
It seems correct

**Comment by vladimirdlc** [comment]
Just copied my rc.xe and rc.dll from C:\Program Files (x86)\Windows Kits\8.1\bin\x86 to 
C:\Program Files (x86)\Windows Kits\10\bin\x86\rc.exe and that fixed it!
Thank you very much :+1:
