### ISSUE TITLE
How do I create a CMakeList.txt file for installing BerkelyDB code on windows platform?

### ISSUE THREAD

**Issue by Anusha-S14** [microsoft/vcpkg#12207]
[CMakeLists_db.txt](https://github.com/microsoft/vcpkg/files/4862611/CMakeLists_db.txt)
When asking a question please also include where you looked for an answer (so we can update the documentation if needed).
Hi All,

Currently I'm trying to integrate the Berkley DB code with our source by migrating from sqlite. We are making use of CMake for our Build and we make use of CMakeList.txt for this. I know that for installing the Linux we make use of the below command:
cd build_unix/
../dist/configure --enable-sql-compat --disable-shared --with-pic --prefix=$INST_DIR

make install

But I'm stuck with windows . I'm attaching the CMakeList.txt file which I have created. Please provide some headsup on how to proceed with this.

**Comment by Anusha-S14** [comment]
Any heads-up?

**Comment by JackBoosY** [comment]
Maybe you should ask this question on [Slack](https://cpplang.now.sh/).

**Comment by Anusha-S14** [comment]
Ok
