### ISSUE TITLE
Boost 1.73 build failure (Ubuntu WSL)

### ISSUE THREAD

**Issue by acceleratxr** [microsoft/vcpkg#12204]
**Host Environment**
- OS: Ubuntu 20.04 WSL
- Compiler: Vcpkg version: 2020.02.04-unknownhash

**To Reproduce**
1. Install Ubuntu 20.04 WSL on Windows 10
2. Open Ubuntu terminal
3. Run these commands:
```
apt-get update && apt-get install build-essential cmake git -y
git clone https://github.com/Microsoft/vcpkg.git ~/.vcpkg
cd ~/.vcpkg
./bootstrap-vcpkg.sh
./vcpkg install boost --triplet x64-linux
```

**Failure logs** 
```
Building package boost-mpl[core]:x64-linux...
-- Using cached /home/ubuntu/.vcpkg/downloads/boostorg-mpl-boost-1.73.0.tar.gz
-- Extracting source /home/ubuntu/.vcpkg/downloads/boostorg-mpl-boost-1.73.0.tar.gz
CMake Error at scripts/cmake/vcpkg_extract_source_archive_ex.cmake:140 (file):
  file RENAME failed to rename

    /home/ubuntu/.vcpkg/buildtrees/boost-mpl/src/TEMP/mpl-boost-1.73.0

  to

    /home/ubuntu/.vcpkg/buildtrees/boost-mpl/src/ost-1.73.0-9b587c3c2d

  because: Permission denied

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:139 (vcpkg_extract_source_archive_ex)
  ports/boost-mpl/portfile.cmake:3 (vcpkg_from_github)
  scripts/ports.cmake:76 (include)


Error: Building package boost-mpl:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-mpl:x64-linux
  Vcpkg version: 2020.02.04-unknownhash
```
**Additional context**
I've tried deleting the buildtrees, downloads, and packages directories with no luck.

**Comment by PhoebeHui** [comment]
@acceleratxr, have you solve the problem? if not, could you try double confirm the cmake revison that you used, could you try to remove it, and use the cmake that vcpkg download instead. and see if this issue still exist?

**Comment by acceleratxr** [comment]
> @acceleratxr, have you solve the problem? if not, could you try double confirm the cmake revison that you used, could you try to remove it, and use the cmake that vcpkg download instead. and see if this issue still exist?

The version of cmake is 3.16.3. Is there documentation on how to set up the included cmake? When I just copy the executable to /usr/bin/ I get this error.
```
CMake Error: Could not find CMAKE_ROOT !!!
CMake has most likely not been installed correctly.
Modules directory not found in
/usr/share/cmake-3.17
cmake version 3.17.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

**Comment by PhoebeHui** [comment]
@acceleratxr, could you try below steps?

1. Open Ubuntu terminal as admin
2. Temprorarily remove the system cmake
3. ./vcpkg install boost

**Comment by acceleratxr** [comment]
> @acceleratxr, could you try below steps?
> 
> 1. Open Ubuntu terminal as admin
> 2. Temprorarily remove the system cmake
> 3. ./vcpkg install boost

Unfortunately I get the same failure when building boost-mpl.
```
CMake Error at scripts/cmake/vcpkg_extract_source_archive_ex.cmake:140 (file):
  file RENAME failed to rename

    /home/ubuntu/.vcpkg/buildtrees/boost-mpl/src/TEMP/mpl-boost-1.73.0

  to

    /home/ubuntu/.vcpkg/buildtrees/boost-mpl/src/ost-1.73.0-9b587c3c2d

  because: Permission denied

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:139 (vcpkg_extract_source_archive_ex)
  ports/boost-mpl/portfile.cmake:3 (vcpkg_from_github)
  scripts/ports.cmake:76 (include)


Error: Building package boost-mpl:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-mpl:x64-linux
  Vcpkg version: 2020.02.04-unknownhash

Additionally, attach any relevant sections from the log files above.
ubuntu@JANE:~/.vcpkg$ cmake

Command 'cmake' not found, but can be installed with:

sudo apt install cmake
```

**Comment by PhoebeHui** [comment]
Thanks for your updates!

Related to https://github.com/microsoft/vcpkg/issues/11283. see https://github.com/microsoft/vcpkg/issues/11283#issuecomment-627008806

**Comment by PhoebeHui** [comment]
@acceleratxr, does this still be a problem for you?

**Comment by PhoebeHui** [comment]
@acceleratxr, please reopen this issue if it still be a problem for you.

**Comment by as-ascii** [comment]
It seems that we encountered similar problem: https://github.com/docwire/docwire/issues/160
So it's still current in Nov 2024. If this is the antivirus problem than the Vcpkg documentation should probably include some note about it (for example to disable or reconfigure antivirus while building packages).

Please reopen the issue as I don't have enough permissions to do it.

**Comment by PolarGoose** [comment]
It is a generic CMake issue [Windows: Directory rename sometimes fails](https://gitlab.kitware.com/cmake/cmake/-/issues/23014) that occurs when using CMake from WSL2 on a Windows drive.
In my case, it is this CMake line that fails:
```
FetchContent_Populate(
  mded_tls
  URL https://github.com/Mbed-TLS/mbedtls/releases/download/mbedtls-3.6.4/mbedtls-3.6.4.tar.bz2
  URL_HASH MD5=eb965a5bb8044bc43a49adb435fa72ee)
```
Error:
```
CMake Error at mded_tls-subbuild/mded_tls-populate-prefix/src/mded_tls-populate-stamp/extract-mded_tls-populate.cmake:58 (file):
  file RENAME failed to rename

    /mnt/c/my/gitrepo/build/linux-gcc-Debug/ex-mded_tls-populate1234/mbedtls-3.6.4

  to

    /mnt/c/my/gitrepo/build/linux-gcc-Debug/mded_tls-src

  because: Permission denied
```

Workaround: move the source code to a Linux drive.
