### ISSUE TITLE
Consider update CMake to 3.8.2

### ISSUE THREAD

**Issue by zabulus** [Microsoft/vcpkg#1221]
Latest version of CMake 3.8.2 has been released.
Update would allow to link arm .obj files in static libraries. In previous version it wasn't implemented.

**Comment by zabulus** [comment]
Should I make PR for this?

**Comment by veikkoeeva** [comment]
I wonder what's the official update strategy version-wise. It looks like [VS 2017 has CMake 3.8](https://blogs.msdn.microsoft.com/vcblog/2017/06/14/cmake-support-in-visual-studio-whats-new-in-2017-15-3-preview-2/) included, CMake 3.9 release is supposedly [just around the corner](https://cmake.org/cmake/help/latest/release/3.9.html).

**Comment by Mixaill** [comment]
Superseded by #1526 @ras0219-msft
