### ISSUE TITLE
[boost-locale] after #10943 its not possible to build boost-locale and boost-regex with ICU anymore if community triple x64-windows-static-md is used

### ISSUE THREAD

**Issue by IRebo** [microsoft/vcpkg#12221]
I understand community triplet might not be fully supported but I think its worth reporting as this worked for a long time.

**Host Environment**
- OS: [Windows]
- Compiler: vs 2019 16.6.3

**To Reproduce**
`vcpkg install boost-locale[icu] boost-regex[icu]  --triplet x64-windows-static-md --recurse`

**Failure logs** 
Building package boost-locale[core,icu]:x64-windows-static-md... done
Installing package boost-locale[core,icu]:x64-windows-static-md...
The following files are already installed in E:/vcpkg_bug/installed/x64-windows-static-md and are in conflict with boost-locale:x64-windows-static-md

Installed by boost-regex:x64-windows-static-md
    debug/lib/has_icu.lib
    lib/has_icu.lib

**Additional context**
After reverting #10943 I can compile again.

**Comment by PhoebeHui** [comment]
@IRebo, thanks for reporting this issue!

I will confirm this issue.

**Comment by PhoebeHui** [comment]
Confirmed.  The PR https://github.com/microsoft/vcpkg/pull/10943 fixed issue when install boost-locale[icu], so it successfully gernerated has_icu.lib, which conflict when install boost-regex[icu] that also generated the lib 'has_icu.lib'.
