### ISSUE TITLE
[MANIFEST] Does not work with port-overlay feature. 

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#12226]
Since vcpkg always throws an error if a port from an overlay is installed and the overlay is not fed into the vcpkg call. 
Furthermore ports from an overlay can also not currently be installed since this is missing from the toolchain. 

https://github.com/microsoft/vcpkg/blob/8133cef324060667d59949549eb4cdcf60b6699b/scripts/buildsystems/vcpkg.cmake#L278-L290

I would also suggest to move all code related to manifests into a separate cmake file for better separation from what the toolchain normally should do. (Manifests are just a modular addition to it.)

**Comment by strega-nil** [comment]
Is this a bug, or is it a feature request? Does this break anybody, or is it just that manifests don't work with overlay ports just yet?

**Comment by Neumann-A** [comment]
The problem is if somebody tries to use manifests with a vcpkg which has an (unknown to master) port installed from a port-overlay vcpkg will throw and error on the execution of the command. 
Has such you might not be immediately breaking someone but locally sharing vcpkg instances becomes a bit more difficult if you have projects which could use the manifest but have other projects which requires ports from an overlay.

**Comment by strega-nil** [comment]
This shouldn't happen, since the installed directories aren't shared -- if `vcpkg/installed` contains `blah` from an overlay, then `proj/vcpkg_installed` doesn't care about `blah`, since it's outside of the installed tree.

**Comment by Neumann-A** [comment]
Closing since there is a way to define overlays via cmake now and registries will also solve this.
