### ISSUE TITLE
[pcre] build failure

### ISSUE THREAD

**Issue by joa-quim** [microsoft/vcpkg#12231]
```
  Package: pcre:x64-windows
  Vcpkg version: 2020.02.04-nohash
```

```
-- Downloading https://downloads.sourceforge.net/project/pcre/pcre/8.44/pcre-8.44.zip...
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:162 (file):
  file DOWNLOAD error: cannot create directory
  'C:/programs/compa_libs/vcpkg/downloads/temp' - Specify file by full path
  name and verify that you have directory creation and file write privileges.
```

**Comment by JackBoosY** [comment]
Hi @joa-quim, sorry for late.
Please clone vcpkg in non-system partation and try again.

Thanks.

**Comment by joa-quim** [comment]
In ``'C:/programs/compa_libs/vcpkg/downloads/temp'``, ``'C:/programs`` is no system partition, just a regular directory created by me.

**Comment by sfhacker** [comment]
@joa-quim I believe he/she meant: Windows system or protected folders, like 'Program files' and the like.
I am not sure what your issue is, but pcre can be downloaded just fine!

![image](https://user-images.githubusercontent.com/25817529/94680709-8f8e9b00-0365-11eb-94b3-8b9dfd4af260.png)

**Comment by joa-quim** [comment]
@sfhacker  Yes, I understood that and that's why I said that ``c:\programs`` is just a regular directory created by me. I just hate directories with spaces in name and thus avoid ``Program files`` as much as possible.

The issue is hopefully solved but that was what happen when I reported it, but have not tried after.

**Comment by JackBoosY** [comment]
@joa-quim  See #13126.
