### ISSUE TITLE
gRPC usage info is not right

### ISSUE THREAD

**Issue by li-wu** [microsoft/vcpkg#12235]
**Describe the bug**
After installing `gRPC` via `./vcpkg install grpc`, it prints the usage info: 
```
The package grpc:x64-osx provides CMake targets:

    find_package(gRPC CONFIG REQUIRED)
    # Note: 7 target(s) were omitted.
    target_link_libraries(main PRIVATE gRPC::gpr gRPC::grpc gRPC::grpc++ gRPC::grpc++_alts)

    find_package(modules CONFIG REQUIRED)
    target_link_libraries(main PRIVATE c-ares::cares)
```
The version of grpc is `1.29.1`. When using it in project like this:
```
target_link_libraries(main PRIVATE gRPC::gpr gRPC::grpc gRPC::grpc++ gRPC::grpc++_alts)
```
Cmake reports the target `gRPC::grpc++_alts` can not be found. But removing `gRPC::grpc++_alts` works.

**Environment**
- OS: MacOS 10.15.5
- Compiler: Clang 8.0.1

**To Reproduce**
1. ./vcpkg install grpc

Port usage information is not correct.

**Expected behavior**
Grpc port usage information after installation should be correct.

**Possible Solution**
Maybe a `usage` file can be added to the port of grpc.

**Comment by NancyLi1013** [comment]
Hi @li-wu 
Thanks for posting this issue.
The target `gRPC::grpc++_alts` is required by the projects that depends on `grpc++_alts`.
If your project doesn't need it, you can remove it. But we cannot remove it from the usage of `grpc`.

Factually, when we use the ports that has many targets can be linked, we can only choose some of those that we need to link.

So the usage provided is right.

**Comment by li-wu** [comment]
@NancyLi1013 Thank you for the detail information.
