### ISSUE TITLE
[vcpkg] upgrade --no-dry-run - Should the change in the new Port-Version field in the port's CONTROL file cause removal/rebuild of port and its features?

### ISSUE THREAD

**Issue by timautry** [microsoft/vcpkg#12234]
`.\vcpkg upgrade --no-dry-run`

- _Should the change in the new Port-Version field in the port's CONTROL file cause removal/rebuild of port and its features?_
- Referenced: https://vcpkg.readthedocs.io/en/latest/maintainers/control-files/ paragraph **Version** does not mention specifically the new Port-Version field.
- I noticed in commit https://github.com/microsoft/vcpkg/commit/ef91134964e8ddec77cd0db8943b72e0eaac2ef7 the ports' CONTROL files have a **Version** and **Port-Version** having had the Port-Version incremented up by 1.
- I have several of these ports installed, libpq, libiconv, libarchive and the **CONTROL** and **vcpkg-cmake-wrapper.cmake** files were updated on my instances, 4 on windows, 2 on OpenSUSE Linux (One VM one WSL2) with a `git pull` but when doing a `vcpkg upgrade` on all the instances none of them were flagged as needing to be upgraded
- The response I received after a `vcpkg upgrade --no-dry-run` was `All installed packages are up-to-date with local portfiles.`
- I would think splitting the Port-Version from the Version, a change in either would cause the port to be flagged for removal/reinstallation by `vcpkg upgrade` as the Port-Version would seem to be now for changes made like adding features, fixes, documentation, etc to a current version, but signaling the port needs to be rebuilt?
- I also noticed the `Port-Version` no longer shows on the port when a `vcpkg list` or `vcpkg search` is performed, just the base version found on Version in the CONTROL file (see attached vcpkg-search.txt and vcpkg-list noting only base version is shown on libpg, libiconv and libarchive).
- See attached files for `vcpkg list` `vcpkg search` and `ls -al` of `<vcpkg-root>\ports\libarchive` showing CONTROL and vcpkg-cmake-wrapper.cmake files updated.
[ls-al.txt](https://github.com/microsoft/vcpkg/files/4867070/ls-al.txt)
[vcpkg-search.txt](https://github.com/microsoft/vcpkg/files/4867071/vcpkg-search.txt)
[vcpkg-list.txt](https://github.com/microsoft/vcpkg/files/4867072/vcpkg-list.txt)
- `ac-130h@Andromeda:[~/git/vcpkg]`
`>$ vcpkg update`
`Using local portfile versions. To update the local portfiles, use `git pull`.`
`No packages need updating.`

- Please advise further?

Thank you and have a wonderful holiday weekend :)

**Comment by strega-nil** [comment]
Fixed by #12227 :)

**Comment by timautry** [comment]
Thank you @strega-nil.

**Comment by strega-nil** [comment]
This isn't actually fixed quite yet, we still need to merge #12227

**Comment by timautry** [comment]
> This isn't actually fixed quite yet, we still need to merge #12227

Ooopps - I acted too quickly, I apologize.

**Comment by timautry** [comment]
Thank you @strega-nil
