### ISSUE TITLE
Can't download tar.gz files

### ISSUE THREAD

**Issue by pdinnissen** [Microsoft/vcpkg#1224]
I've been trying to install boost and it's dependencies, but the downloads keep failing (I've resorted to manually downloading the required files and placing them in the download directory as a temporary bypass).  

      -- Downloading https://sourceforge.net/projects/boost/files/boost/1.64.0/boost_1_64_0.tar.bz2...
      -- Downloading https://sourceforge.net/projects/boost/files/boost/1.64.0/boost_1_64_0.tar.bz2... Failed. Status: 7;"Couldn't connect to server"
      CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:82 (message):

      Failed to download file.
      Add mirrors or submit an issue at https://github.com/Microsoft/vcpkg/issues

**Comment by ras0219-msft** [comment]
Thanks for reporting this issue.

Do you happen to be using a proxy? You may need to set the `http_proxy` and `https_proxy` environment variables to let cmake know where to download from.

**Comment by pdinnissen** [comment]
I hadn't thought about the fact that my work does use a proxy.  It's strange that I can still use vcpkg to install packages that use .zip files.

How can I set the proxy for cmake?

**Comment by ras0219-msft** [comment]
Cmake uses curl internally, so you can set the `http_proxy` and `https_proxy` environment variables to let cmake know what proxy to use.

**Comment by pdinnissen** [comment]
Thank you that worked.
