### ISSUE TITLE
[ffmpeg] x64-osx build failure

### ISSUE THREAD

**Issue by cenit** [microsoft/vcpkg#12245]
**Host Environment**
- OS: macOS 10.15.5
- Compiler: Apple clang version 11.0.3 (clang-1103.0.32.62)

**To Reproduce**
`./vcpkg install ffmpeg`

**Failure logs** 
```
critical: src/libavfilter/x86/vf_blend.asm:416: out of memory!
make: *** [libavfilter/x86/vf_blend.o] Error 2
```

**Additional context**
I had to rebuild ffmpeg during a vcpkg update. I cannot rebuilt it anymore, due to this error.

For completeness, Yasm is installed through brew

```
$  yasm --version
yasm 1.3.0
Compiled on Sep 29 2019.
```

edit: I tried also using nasm instead of yasm. Same identical error

**Comment by JackBoosY** [comment]
```
out of memory
```
Have you checked if there is insufficient memory?

**Comment by JackBoosY** [comment]
And I can't repro it on my machine now...

**Comment by cenit** [comment]
I am using my MacBook Pro with 16 GB of RAM. Also, I built ffmpeg so many times in the past on this laptop, I was really surprised to see it failing now

**Comment by cenit** [comment]
@JackBoosY Do you have the same compiler version as mine?

**Comment by JackBoosY** [comment]
@cenit 
```
vcpkg@vcpkg % gcc -v
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.3 (clang-1103.0.32.62)
Target: x86_64-apple-darwin19.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by cenit** [comment]
Updating to gcc 10.1 just released on homebrew magically fixed it.
I don't know what happened, glad that I can continue using my mac 🤣
