### ISSUE TITLE
how do I change the branch I have active for a package?

### ISSUE THREAD

**Issue by juandent** [microsoft/vcpkg#12251]
When asking a question please also include where you looked for an answer (so we can update the documentation if needed).
Just looked at the options in vcpckg.exe... I have no idea how to proceed, and I am in a hurry - please help

**Comment by juandent** [comment]
for instance, I have installed sqlite_orm via vcpkg. I suspect the master branch has been installed. Now I want to install the dev branch, how do I do that?

**Comment by timautry** [comment]
vcpkg normally only has a master package. Every once in a while there may be other branches where microsoft employees are testing something, but normally there are no other branches.
If you wish to experiment or test, you can do a `pull request` aka PR and make a fork of vcpkg to your github account - then you can change away, create new branches etc. 
If your testing fixes something, adds a new port or new features to a port you can request it be merged back into the vcpkg master after it meets all reviews, disclaimers, standards, etc, etc, etc...
Hope that helps.

**Comment by juandent** [comment]
ok.. but how can I recreate the binaries after I change the source files? there is no VC solution or projects...

**Comment by juandent** [comment]
how can I convert a CMakeList project to a solution in VC?

**Comment by timautry** [comment]
The scope of your question would be to long to explain here. I would suggest reading the docs to start learning the how the package operates and how you wish to use it in your development processes -  
https://vcpkg.readthedocs.io/en/latest/ --or--
https://github.com/microsoft/vcpkg/blob/master/docs/index.md
You may wish to read about the workings of git https://git-scm.com/doc -and- cmake https://cmake.org/
vcpkg port libraries and binaries are mostly consumed by your own Visual Studio (via integrate install or integrate project) or cmake (via toolchain(s) projects).

**Comment by PhoebeHui** [comment]
@juandent, does this still be a problem for you?

**Comment by PhoebeHui** [comment]
@juandent, see above suggestions from linquize.
