### ISSUE TITLE
Add arm64-osx triplet 

### ISSUE THREAD

**Issue by eklipse2k8** [microsoft/vcpkg#12258]
Didn't see this in the issue list, but now that apple's ADP are out in the wild, we should be building for arm64-osx.

**Comment by past-due** [comment]
That's a good first step. 👍

I'm wondering what the blockers are on supporting universal (multi-arch) builds for macOS in vcpkg?
Are there ports that assume only a single architecture?

**Comment by eklipse2k8** [comment]
I think that would be smart, cmake can handle both and compiles both. 

It would most likely break some ports though as some of them are not ready for ARM64.

Maybe the answer would be to support "arm64-osx", "x64-osx", "universal-osx"

Given that Xcode now creates true universal applications, both ios and mac in the same project, universal is a loaded term here.

__universal-apple:__
1. x64-osx
2. arm64-osx *new* (apple silicon)
3. x64-ios (simulator)
4. arm64-ios (device)

With these four architectures it would be possible to create a single fat .a or .dylib that can be added to an Xcode project and run on all targets.
