### ISSUE TITLE
User-wide integration needs to be removed for NuGet packages

### ISSUE THREAD

**Issue by pdinnissen** [microsoft/vcpkg#1225]
It seems like if you have user-wide integration installed, then the include directories will be those and not what is packaged inside the NuGet.

Not sure if this was intended behavior or not.

I am using Windows 7 and VS2017.  I tested this with the following steps:

1. vcpkg integrate install
2. vcpkg install zlib
3. vcpkg export zlib --nuget
4. create new project and install nuget package
5. vcpkg remove zlib
6. notice that the intellisense will no longer show the zlib header
7. vcpkg integrate remove
8. restart project
9. notice that the intellisens has the zlib header again

**Comment by alexkaratarakis** [comment]
Thanks for the detailed repro! We'll prepare a fix.

**Comment by LilyWangL** [comment]
This issue hasn’t been updated in a year, if it is still an issue, please reopen.
