### ISSUE TITLE
Imgui bindings feature design

### ISSUE THREAD

**Issue by RT222** [microsoft/vcpkg#12250]
Continue the discussion started in #11919.

These bindings are very well maintained, feature complete and the author recommend to use them by default except if a custom implementation is really needed : https://github.com/ocornut/imgui#integration

I think it's a good thing they are available as features for this port. What I dislike is the inability to pick only the required ones, it's all or nothing. Because of this, you are forced to acquire a lot of dependencies you will probably never need. It's also ugly because it isn't compiled to libs but rely instead on the manual inclusion of cpp files in your project, because some of them depends on platform specific APIs that can't be compiled everywhere.

Splitting these bindings to different features would solve these problems. The only drawback is that we would have a very long list of features : 

- Allegro5
- Dx9
- Dx10
- Dx11
- Dx12
- Glfw
- Glut
- Marmalade
- Metal
- Opengl2
- Opengl3
- Osx
- Sdl
- Vulkan
- Win32

I don't know if it's acceptable for vcpkg ports to have such a long feature list, but if it is, it would be a better solution than the current one, and I'd be happy to implement it.

**Comment by timautry** [comment]
I do not think a long list of features would be an issue - look at the aws-sdk-cpp or magnum ports.

It would just be if one wants to put the time and effort into breaking them into separate features, separating the dependencies for each feature and then maintaining it with fixes for each platform/OS combination or after there is a release of each new feature and/or feature dependencies.

If this is something you or someone else is considering a pull request (PR) could be done and submitted for approval/implementation.

**Comment by JackBoosY** [comment]
I'm waiting for the discussion result of https://github.com/ocornut/imgui/pull/1713.

**Comment by RT222** [comment]
Nice, it would be very helpful if Imgui provided a CMake build system by default, I hope they'll be able to add it soon. In the meantime, here's my proposal to improve the bindings support for this port : #12329

**Comment by JackBoosY** [comment]
Close this PR until upstream fixes this.
