### ISSUE TITLE
mlpack:x64-windows

### ISSUE THREAD

**Issue by zd1176630227** [microsoft/vcpkg#12266]
.\vcpkg.exe install mlpack:x64-windows

-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.73.0/LICENSE_1_0.txt...
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.73.0/LICENSE_1_0.txt... Failed. Status: 6;"Couldn't resolve host name"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:175 (message):

      Failed to download file.

  Package: boost-compatibility:x64-windows
  Vcpkg version: 2020.02.04-nohash

**Comment by c72578** [comment]
This looks like a temporary download/DNS issue, which occurred during building of the required `boost-compatibility` package.
Can you access the file, when clicking on:
https://raw.githubusercontent.com/boostorg/boost/boost-1.73.0/LICENSE_1_0.txt
If OK, retry
`.\vcpkg.exe install mlpack:x64-windows`

**Comment by zd1176630227** [comment]
I changed the DNS and now I can access it. Thank you very much.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Wolfgang St&amp;#xF6;ggl"<notifications@github.com&gt;; 
发送时间: 2020年7月5日(星期天) 中午1:02
收件人: "microsoft/vcpkg"<vcpkg@noreply.github.com&gt;; 
抄送: "随心灵动"<1176630227@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [microsoft/vcpkg] mlpack:x64-windows (#12266)





 
This looks like a temporary download/DNS issue, which occurred during building of the required boost-compatibility package.
 Can you access the file, when clicking on:
 https://raw.githubusercontent.com/boostorg/boost/boost-1.73.0/LICENSE_1_0.txt
 If OK, retry
 .\vcpkg.exe install mlpack:x64-windows

**Comment by JACK-HAI** [comment]
Could you tell me the DNS address ?

**Comment by JACK-HAI** [comment]
Could you tell me the DNS address ?

**Comment by zd1176630227** [comment]
114.114.114.114



---Original---

**Comment by JackBoosY** [comment]
@zd1176630227 Use proxy or VPN or SS can solve this issue.
