### ISSUE TITLE
[vtk[qt]:linux/qt5-x11extras] build failure

### ISSUE THREAD

**Issue by artzers** [microsoft/vcpkg#12269]
**Host Environment**
- OS: [ubuntu 16]
- Compiler: gcc/g++ 8.4

**To Reproduce**
`./vcpkg install vtk[qt]:x64-linux` or `./vcpkg install qt5-x11extras:x64-linux`

**Failure logs** 
Computing installation plan...
The following packages will be built and installed:
    qt5-x11extras[core]:x64-linux
Starting package 1/1: qt5-x11extras:x64-linux
Building package qt5-x11extras[core]:x64-linux...
-- Using cached /home/super/Downloads/vcpkg-master/downloads/qtx11extras-everywhere-src-5.12.8.tar.xz
-- Using source at /home/super/Downloads/vcpkg-master/buildtrees/qt5-x11extras/src/5.12.8-6f63f291eb
-- Configuring x64-linux-rel
-- Configuring x64-linux-rel done
-- Configuring x64-linux-dbg
-- Configuring x64-linux-dbg done
-- Package build-x64-linux-dbg
-- Package build-x64-linux-rel
-- Package install-x64-linux-dbg
-- Package install-x64-linux-rel
-- Installing: /home/super/Downloads/vcpkg-master/packages/qt5-x11extras_x64-linux/share/qt5-x11extras/copyright
-- Performing post-build validation
The folder /include is empty or not present. This indicates the library was not correctly installed.
Found 1 error(s). Please correct the portfile:
    /home/super/Downloads/vcpkg-master/ports/qt5-x11extras/portfile.cmake
-- Performing post-build validation done
Error: Building package qt5-x11extras:x64-linux failed with: POST_BUILD_CHECKS_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: qt5-x11extras:x64-linux
  Vcpkg version: 2020.02.04-unknownhash

Additionally, attach any relevant sections from the log files above.

**Additional context**
I have update libx11 by `sudo apt-get install libx11-xcb-dev libxt-dev `.
I have remove all qt5-* packages and reinstall qt5-*. The errors still ocurred.

**Comment by Neumann-A** [comment]
Missing system libraries. Try installing:

https://github.com/microsoft/vcpkg/blob/c21893b4dc68430ebcf028ffdb190e586fc3d639/scripts/azure-pipelines/linux/provision-image.sh#L8-L24

remove qt5-base und reinstall qt5-base. qt5-base must be installed with the correct system libraries installed so that qt5-x11extras build successfully.

**Comment by artzers** [comment]
@Neumann-A  Thank you. Now the vcpkg can install qt5 and vtk[qt] successfully on Ubuntu 16.  : )
However there is a small question. After installing provision-image.sh, Ubuntu cannot mount ntfs disk in nautilus, showing "no object for d-bus interface". The ubuntu forum suggests using gparted but warn "may lose data". Finally I mount ntfs disk by running `sudo mount` in bash.
