### ISSUE TITLE
[New Port Request] libsigc++ 3.03

### ISSUE THREAD

**Issue by babyaaaaaa** [microsoft/vcpkg#12261]
Library name: 
libsigc++ version3.03 (if current version newer than it, please use the newest verson)

Library description: 
libsigc++ implements a typesafe callback system for standard C++. It allows you to define signals and to connect those signals to any callback function, either global or a member function, regardless of whether it is static or virtual.

Source repository URL:
https://github.com/libsigcplusplus/libsigcplusplus

Project homepage (if different from the source repository):
https://developer.gnome.org/libsigc++/stable/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
