### ISSUE TITLE
[ffmpeg: x86-windows] build failure

### ISSUE THREAD

**Issue by reillydonovan** [microsoft/vcpkg#12260]
**Host Environment**
- OS: Windows 10 Pro 10.0.19041 Build 19041
- Compiler: Visual Studio 2019 16.6.3

**To Reproduce**
`./vcpkg install ffmpeg:x86-windows`

**Failure logs** 
-Error: Building package ffmpeg:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: ffmpeg:x86-windows
  Vcpkg version: 2019.09.12-nohash

Additionally, attach any relevant sections from the log files above.
-How do I do this?

**Additional context**
Not sure why this build fails consistently

**Comment by c72578** [comment]
Please checkout a current version of vcpkg and try again.
The version `2019.09.12-nohash` is not up to date.

The log files can be found here:
`vcpkg/buildtrees/ffmpeg/`

**Comment by LilyWangL** [comment]
The latest VCPKG version is 2020.02.04-nphash, please run command `git pull` and run `.\bootstrap-vcpkg.bat` to update VCPKG.
```
.\vcpkg.exe version
Vcpkg package management program version 2020.02.04-nohash

See LICENSE.txt for license information.
```

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
