### ISSUE TITLE
[<port name>] build failure

### ISSUE THREAD

**Issue by IshaanKarnik** [microsoft/vcpkg#12284]
**Host Environment**
- OS: Windows 10 64-Professional
- Compiler: Visual Studio 2019

**To Reproduce**
`./vcpkg install nanodbc`

**Failure logs** 
Computing installation plan...
The following packages will be built and installed:
    nanodbc[core]:x64-windows
  * unixodbc[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/2: unixodbc:x64-windows
Building package unixodbc[core]:x64-windows...
CMake Error at scripts/cmake/vcpkg_fail_port_install.cmake:93 (message):
  Target 'Windows' not supported by unixodbc!

Call Stack (most recent call first):
  ports/unixodbc/portfile.cmake:1 (vcpkg_fail_port_install)
  scripts/ports.cmake:76 (include)

Error: Building package unixodbc:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
Package: unixodbc:x64-windows
Vcpkg version: 2020.02.04-nohash

Earlier the  `nanodbc[core]:x64-windows`  was getting installed properly; after vcpkg update I'm getting this issue. Earlier `nanodbc[core]:x64-windows` didn't need  `unixodbc[core]:x64-windows`.

**Comment by timautry** [comment]
@IshaanKarnik update vcpkg and try again.
See #12248 PR #12274 was already in progress to fix this issue,removing the dependency of unixodbc from port nanodbc on windows platforms.

**Comment by IshaanKarnik** [comment]
Thanks Resolved.
