### ISSUE TITLE
Error: Building package realsense2:x86-windows

### ISSUE THREAD

**Issue by fmmsainco** [microsoft/vcpkg#12281]
When executing "vcpkg install realsense2" I get the following error:

Error: Building package realsense2:x86-windows failed with: BUILD_FAILED

This is the command output:

vcpkg install realsense2
Computing installation plan...
The following packages will be built and installed:
    realsense2[core]:x86-windows
Warning: The following VS instances are excluded because the English language pack is unavailable.
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
Please install the English language pack.
A suitable version of powershell-core was not found (required v6.2.1). Downloading portable powershell-core v6.2.1...
Downloading powershell-core...
  https://github.com/PowerShell/PowerShell/releases/download/v6.2.1/PowerShell-6.2.1-win-x86.zip -> C:\Trabajo\Fuentes\realsense\vcpkg\downloads\PowerShell-6.2.1-win-x86.zip
Extracting powershell-core...
A suitable version of 7zip was not found (required v18.1.0). Downloading portable 7zip v18.1.0...
Downloading 7zip...
  https://www.nuget.org/api/v2/package/7-Zip.CommandLine/18.1.0 -> C:\Trabajo\Fuentes\realsense\vcpkg\downloads\7-zip.commandline.18.1.0.nupkg
Extracting 7zip...
Starting package 1/1: realsense2:x86-windows
Building package realsense2[core]:x86-windows...
-- Downloading https://github.com/IntelRealSense/librealsense/archive/025fccf76803ee6a6e60de9f18ac6193b7ff8597.tar.gz...
-- Extracting source C:/Trabajo/Fuentes/realsense/vcpkg/downloads/IntelRealSense-librealsense-025fccf76803ee6a6e60de9f18ac6193b7ff8597.tar.gz
-- Applying patch fix_openni2.patch
-- Applying patch fix-dependency-glfw3.patch
-- Using source at C:/Trabajo/Fuentes/realsense/vcpkg/buildtrees/realsense2/src/93b7ff8597-4347a45ee5
-- Downloading https://github.com/ninja-build/ninja/releases/download/v1.10.0/ninja-win.zip...
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: ninja -v
    Working Directory: C:/Trabajo/Fuentes/realsense/vcpkg/buildtrees/realsense2/x86-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\Trabajo\Fuentes\realsense\vcpkg\buildtrees\realsense2\config-x86-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:300 (vcpkg_execute_required_process)
  ports/realsense2/portfile.cmake:29 (vcpkg_configure_cmake)
  scripts/ports.cmake:76 (include)

**Error: Building package realsense2:x86-windows failed with: BUILD_FAILED**
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: realsense2:x86-windows
  Vcpkg version: 2020.02.04-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by NancyLi1013** [comment]
Hi @fmmsainco 
Thanks for posting this issue.

```
Warning: The following VS instances are excluded because the English language pack is unavailable.
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
Please install the English language pack.
```

Could you please install English language pack via Visual Studio Installer first?

**Comment by NancyLi1013** [comment]
I'm closing this issue for now since no response.
Please feel free to reopen this if it is still a problem for you.
