### ISSUE TITLE
Unable to read %LOCALAPPDATA% on Windows service accounts

### ISSUE THREAD

**Issue by AlexAltea** [microsoft/vcpkg#12285]
After the merging of https://github.com/microsoft/vcpkg/pull/12091 (cc @ras0219), the instances of vcpkg running in our Windows CI exited reporting that `%LOCALAPPDATA%` cannot be read. This environment variable is undefined as the CI jobs are running on a Windows service account (running as SYSTEM).

As a hacky workaround, `$Env:LOCALAPPDATA = $Env:TEMP` solves the problem, but a proper fix would be much appreciated.

**Environment**
- OS: Windows Server 2019
- Compiler: MSVC 14.26
- Relevant environment variables (some have been redacted to `[...]`)
```
> Get-ChildItem Env:

Name                           Value
----                           -----
ALLUSERSPROFILE                C:\ProgramData
APPDATA                        C:\Windows\system32\config\systemprofile\AppData\Roaming
[...]
HOME                           C:\Windows\TEMP\drone-[...]\home\drone
HOMEPATH                       C:\Windows\TEMP\drone-[...]\home\drone
OS                             Windows_NT
Path                           C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;...
[...]
PSMODULEPATH                   WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;...
PUBLIC                         C:\Users\Public
SystemDrive                    C:
SystemRoot                     C:\Windows
TEMP                           C:\Windows\TEMP
TMP                            C:\Windows\TEMP
USERNAME                       [...]$
USERPROFILE                    C:\Windows\TEMP\drone-[...]\home\drone
VCPKG_ROOT                     C:\vcpkg
windir                         C:\Windows
```

**To reproduce**

1. Run `vcpkg install` on a Windows service account.
2. See error below:

    ```
    > vcpkg install

    Failed at [C:\vcpkg\toolsrc\src\vcpkg\userconfig.cpp(14)] with message:
    unable to read %LOCALAPPDATA%
    ```

**Expected behavior**

The command should succeed on service accounts. If *%LOCALAPPDATA%* is undefined, maybe it should fallback to one of the following directories:
- `C:\Windows\System32\config\systemprofile\AppData\Local`
- `C:\Windows\SysWOW64\config\systemprofile\AppData\Local`

**Comment by JackBoosY** [comment]
@BillyONeal @ras0219 @ras0219-msft Can you take a look?

Thanks.
