### ISSUE TITLE
[New Port Request] Add Tk library

### ISSUE THREAD

**Issue by shrinny** [microsoft/vcpkg#12283]
**Library name:**
Tk
**Library description:**
Tk is a cross-platform GUI toolkit implemented with the Tcl scripting language.
**Source repository URL:**
https://github.com/tcltk/tk/
**Project homepage (if different from the source repository):**
https://www.tcl.tk/

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
