### ISSUE TITLE
clang-cl compiler not found on Windows

### ISSUE THREAD

**Issue by jsmolka** [microsoft/vcpkg#12292]
**Describe the bug**
`No CMAKE_CXX_COMPILER could be found.` when trying to build with clang-cl with cmake on Windows. This just happens with the latest vcpkg version, previous ones worked.

**Environment**
- OS: Windows
- Compiler: clang-cl latest

**To Reproduce**
```
git clone https://github.com/jsmolka/NanoboyAdvance
cd NanoboyAdvance
mkdir build
cd build
set VCPKG_ROOT=path/to/vcpkg
cmake -T clangcl ..
```

Full build instructions in the [readme](https://github.com/fleroviux/NanoboyAdvance#windows).

**Expected behavior**
The previous vcpkg version managed to compile.

**Failure logs** 
```
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.18363.
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:8 (project):
  No CMAKE_CXX_COMPILER could be found.



-- Configuring incomplete, errors occurred!
See also "C:/dev/code/NanoboyAdvance/build/CMakeFiles/CMakeOutput.log".
See also "C:/dev/code/NanoboyAdvance/build/CMakeFiles/CMakeError.log".
```

Logs are attached (some areas in German, I can translate if necessary).
[CMakeError.log](https://github.com/microsoft/vcpkg/files/4880961/CMakeError.log)
[CMakeOutput.log](https://github.com/microsoft/vcpkg/files/4880962/CMakeOutput.log)

**Additional context**
I first noticed this issue in a GitHub Actions workflow and therefore created an issue in the actions repo. The [answer](https://github.com/actions/virtual-environments/issues/1152#issuecomment-654042618) is worth a read and gives a possible explanation.

**Comment by BillyONeal** [comment]
The triplet `x64-windows` is intended to mean the MSVC compiler, and the recent binary caching change triggering this is a reflection of that; perhaps this is effectively a request to add `x64-windows-clang` or similar?

**Comment by jsmolka** [comment]
This would be a great addition but I don't think it's required for this issue. clang-cl tries to be a drop-in replacement (ABI, arguments, ...) so compiling the libraries with MSVC is no problem. But for the application itself I would like to have the possibility to choose a specific compiler (due to some MSVC template limitations) and vcpkg shouldn't interfere there.

**Comment by Voskrese** [comment]
`cmake -T clangcl` .. this is not correct \
->> `cmake -G"V... S... ver" -T clangcl`
or
```
cmake -G"Ninja" -DCMAKE_C_COMPILER=clang-cl -DCMAKE_CXX_COMPILER=clang-cl
```

**Comment by Neumann-A** [comment]
in triplet file:
```
set(ENV{CC} clang-cl)
set(ENV{CXX} clang-cl)
```
don't forget to add the path for clang-cl to PATH in the vcpkg environment or use the fullpath.

**Comment by jsmolka** [comment]
@Voskrese my version should be equal to your first one (cmake selects Visual Studio 16 2019 as default generator if none is supplied) and the second version fails with the following error logs.

[CMakeOutput.log](https://github.com/microsoft/vcpkg/files/4885879/CMakeOutput.log)
[CMakeError.log](https://github.com/microsoft/vcpkg/files/4885880/CMakeError.log)

I success generating the solution with `cmake -T clangcl -DCMAKE_CXX_COMPILER="path/to/clang-cl.exe" ..` but then building itself failed with an error about disabled exceptions (which is nowhere to be seen in the cmake file).

@Neumann-A where would I change that? Also this seems rather unnecessary. The previous version just perfectly fine without manually altering triples.

**Comment by Voskrese** [comment]
> selects Visual Studio 16 2019 as default generator

`14.26.28801\lib\x64\libcmt.lib : warning LNK4272: library machine type 'x64' conflicts with target machine type 'x86'`

`Visual Studio 16 2019 -A x64` << -- x64 default generator 
?

"C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/Llvm/bin/clang-cl.exe" --help

x64 Llvm -->> "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/Llvm/x64/"

**Comment by jsmolka** [comment]
Even if I manage to generate a solution for clang-cl I still end up with the disabled exceptions error.

**Comment by ras0219-msft** [comment]
I believe I've identified the issue and proposed a fix in https://github.com/microsoft/vcpkg/pull/12319.

**Comment by jsmolka** [comment]
@ras0219-msft Yes, this fixes the issue.
