### ISSUE TITLE
[argtable3] spurious build failure

### ISSUE THREAD

**Issue by BillyONeal** [microsoft/vcpkg#12297]
**Host Environment**
- OS: Windows Server 2019
- Compiler: Visual Studio 2019 version 16.6

**To Reproduce**
`./vcpkg install argtable3:x64-uwp` (presumably)

**Failure logs** 
[argtable3.zip](https://github.com/microsoft/vcpkg/files/4882074/argtable3.zip)

**Additional context**
This failure appears to be spurious, there are likely races in the package's build system:

```
       "D:\buildtrees\argtable3\x64-uwp-dbg\install.vcxproj" (default target) (1) ->
       "D:\buildtrees\argtable3\x64-uwp-dbg\ALL_BUILD.vcxproj" (default target) (3) ->
       "D:\buildtrees\argtable3\x64-uwp-dbg\examples\ls.vcxproj" (default target) (7) ->
       (CustomBuild target) -> 
         CUSTOMBUILD : CMake error : Cannot restore timestamp D:/buildtrees/argtable3/x64-uwp-dbg/examples/CMakeFiles/generate.stamp [D:\buildtrees\argtable3\x64-uwp-dbg\examples\ls.vcxproj]
```

**Comment by BillyONeal** [comment]
Failed in https://dev.azure.com/vcpkg/public/_build/results?buildId=39820

**Comment by PhoebeHui** [comment]
I didn't repro this issue locally, it might due to building the example in parallel, I updated this port to latest release revision 3.1.5, let 's see if it still occur in CI testing.

**Comment by PhoebeHui** [comment]
The PR has been merged, and I haven't seen this failure on CI testing, close this issue now, would reopen this issue if it occur again.

**Comment by JackBoosY** [comment]
It's a cmake bug: https://gitlab.kitware.com/cmake/cmake/-/issues/21571
Will be fixed by update cmake to the next version.

**Comment by tomghuang** [comment]
I've modified the CMake scripts in the latest v3.2.1 release, so we can use `BUILD_SHARED_LIBS` to control whether we're building a static or dynamic library. It's more aligned with the CMake recommendations and the vcpkg design, so we won't see any error in vcpkg, CMake, and the build process.

I'm preparing a pull request to update the port to Argtable3 v3.2.1, which should resolve most of the issues.
