### ISSUE TITLE
[libb2] build failure on osx

### ISSUE THREAD

**Issue by BillyONeal** [microsoft/vcpkg#12299]
**Host Environment**
- OS: MacOS Catalina
- Compiler: Unknown

**To Reproduce**
`./vcpkg install libb2`

**Failure logs** 
This failed in a recent full rebuild: https://dev.azure.com/vcpkg/public/_build/results?buildId=39820
It also repros for me locally, indicating it is likely not a spurious build failure.

[libb2.zip](https://github.com/microsoft/vcpkg/files/4882129/libb2.zip)

**Comment by LilyWangL** [comment]
Now `libb2` can build success on MACOS, so I am closing this issue for now.
![image](https://user-images.githubusercontent.com/47812810/88154255-1e31be00-cc39-11ea-971f-f5cea6d80555.png)
