### ISSUE TITLE
Manifest mode does not offer CMake usage help

### ISSUE THREAD

**Issue by ras0219** [microsoft/vcpkg#12290]
When installing libraries in classic mode, CMake users receive very helpful notices:
```
>vcpkg install fmt
...
The package fmt:x86-windows provides CMake targets:

    find_package(fmt CONFIG REQUIRED)
    target_link_libraries(main PRIVATE fmt::fmt fmt::fmt-header-only)

```

There's no way to access this help from manifest mode (it is not printed upon install). The simplest solution would be to provide a command `vcpkg info` which could display this help information.

**Comment by PhoebeHui** [comment]
PR https://github.com/microsoft/vcpkg-tool/pull/82 would improve this.

**Comment by autoantwort** [comment]
Fixed by https://github.com/microsoft/vcpkg-tool/pull/133

**Comment by PhoebeHui** [comment]
Thanks @autoantwort!
