### ISSUE TITLE
[tesseract] build failure for feature cpu_independed

### ISSUE THREAD

**Issue by emocanu** [microsoft/vcpkg#12301]
**Host Environment**
- OS: Windows
- Compiler: VS 2019 stack

**To Reproduce**
`vcpkg install tesseract[cpu_independed]:x86-windows-static`

**Failure logs** 
Error: <unknown>:1:25: invalid character in feature name (must be lowercase, digits, '-')
   on expression: tesseract[cpu_independed]:x86-windows-static

**Workaround**
Change **cpu_independed** to **cpu-independed** in both
_vcpkg\ports\tesseract\CONTROL_
and
_vcpkg\ports\tesseract\portfile_

**Comment by PhoebeHui** [comment]
@emocanu, thanks for reporting this issue!
