### ISSUE TITLE
[New Port Request] FlopC++ - COIN-OR (Computational Infrastructure for Operations Research)

### ISSUE THREAD

**Issue by marcosrobertosilva** [microsoft/vcpkg#12308]
Library name: COIN-OR FlopC++

Library description:
Using FLOPC++, linear optimization models can be specified in a declarative style, similar to algebraic modelling languages such as GAMS and AMPL, within a C++ program. As a result the traditional strengths of algebraic modelling languages are preserved, while embedding linear optimization models in software applications is facilitated.

FLOPC++ can be used as a substitute for traditional modelling languages, when modelling linear optimization problems, but its principal strength lies in the fact that the modelling facilities are combined with a powerful general purpose programming language. This combination is essential for implementing efficient algorithms (using linear optimization for subproblems), integrating optimization models in user applications, etc.

Source repository URL: https://github.com/tkelman/FlopCpp and (svn) https://projects.coin-or.org/svn/FlopC++/stable/1.2

Project homepage (if different from the source repository): https://projects.coin-or.org/FlopC++

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
