### ISSUE TITLE
Is it possible to create a sandboxed package environment with vcpkg?

### ISSUE THREAD

**Issue by kakyoism** [microsoft/vcpkg#12310]
I'm trying to freeze the dependencies of a few projects of mine, which have been using a single vcpkg to manage the dependencies. This vcpkg instance also manages all the projects on the system.

## Goal

I want a solution similar to python's venv where Project A and B could use separate sets of dependencies with different versions. 

Something like Project A depends on

```sh
libA 1.0
libB 2.0
libC 3.0
```

but Project B depends on 

```sh
libA 5.0
libB 6.0
libC 7.0
```

## Questions

Given two projects, could I configure two separate working copies of the vcpkg as sandboxes, so that when I open the two projects in Visual Studio, VS knows which sandbox to use for each project?

**Comment by PhoebeHui** [comment]
I think that depends on how you consume the libs from vcpkg. If using the libs with cmake, you can use two vcpkg instance, since everything setting via CMAKE_TOOLCHAIN_FILE. Howver, it using them with [MSbuild](https://github.com/microsoft/vcpkg/blob/master/docs/users/integration.md#with-msbuild) then only one instance can be used at once, since only have one vcpkg.user.targets under %APPDATA%\..\Local\vcpkg. @kakyoism, Is the answer you want?

**Comment by kakyoism** [comment]
> I think that depends on how you consume the libs from vcpkg. If using the libs with cmake, you can use two vcpkg instance, since everything setting via CMAKE_TOOLCHAIN_FILE. Howver, it using them with [MSbuild](https://github.com/microsoft/vcpkg/blob/master/docs/users/integration.md#with-msbuild) then only one instance can be used at once, since only have one vcpkg.user.targets under %APPDATA%..\Local\vcpkg. @kakyoism, Is the answer you want?

When you say "only one instance at once (at a time?)" with MSbuild, do you imply that if I invoke MSbuild sequentially for two projects using two vcpkg instances, and update `vcpkg.user.targets` and other parameters configured under %APPDATA%..\Local\vcpkg accordingly, then I'll be fine?

I know this sounds a hack but in reality without this sandbox feature, multiple non-CMake-based projects are essentially unable to work with vcpkg safely. This is a serious drawback, IMHO. 

Are there any workarounds?

**Comment by ras0219-msft** [comment]
There are two easy ways to sandbox individual MSBuild instances:
https://github.com/microsoft/vcpkg/blob/master/docs/users/integration.md#linking-nuget-file and https://github.com/microsoft/vcpkg/blob/master/docs/users/integration.md#export-command

With the first, we will generate a NuGet package that points to the specific absolute path on your machine. However, these paths may not be correct for another user's machine.

With the second, we create a shrinkwrapped NuGet package containing all the binaries you select from that particular instance; these can then be added to an MSBuild project and passed around to easily restore exactly those dependencies on any machine.

Finally, there is a more difficult route: you could manually edit the vcxproj files and set the `VcpkgRoot` MSBuild property to point into a git submodule of vcpkg. This may be made easier by the new Vcpkg Property Page in VS.

**Comment by kakyoism** [comment]
> There are two easy ways to sandbox individual MSBuild instances:
> https://github.com/microsoft/vcpkg/blob/master/docs/users/integration.md#linking-nuget-file and https://github.com/microsoft/vcpkg/blob/master/docs/users/integration.md#export-command
> 
> With the first, we will generate a NuGet package that points to the specific absolute path on your machine. However, these paths may not be correct for another user's machine.
> 
> With the second, we create a shrinkwrapped NuGet package containing all the binaries you select from that particular instance; these can then be added to an MSBuild project and passed around to easily restore exactly those dependencies on any machine.
> 
> Finally, there is a more difficult route: you could manually edit the vcxproj files and set the `VcpkgRoot` MSBuild property to point into a git submodule of vcpkg. This may be made easier by the new Vcpkg Property Page in VS.

Wow. All these routes look promising. I'll give them a try. 

@ras0219-msft  Thanks a lot! Close now and will reopen it if I'm blocked again.
