### ISSUE TITLE
[New Port Request] xqilla

### ISSUE THREAD

**Issue by JonOverholser** [microsoft/vcpkg#12313]
Library name: xqilla

Library description: An XQuery and XPath 2.0 library, written in C++ and built on top of Xerces-C.

Source repository URL: https://sourceforge.net/projects/xqilla/files/XQilla-2.3.4.zip/download

Project homepage: https://sourceforge.net/projects/xqilla/

Dependencies: xerces-c

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
