### ISSUE TITLE
Dependency features not installed in manifest mode

### ISSUE THREAD

**Issue by AlexAltea** [microsoft/vcpkg#12315]
It seems that features in the array of dependencies of *vcpkg.json* files get ignored by `vcpkg install`.

**Environment**
- OS: Any?
- Compiler: Any?

**To reproduce**

1. Create an empty folder with the following `vcpkg.json` file:
    ```
    {
      "name": "xxx",
      "version-string": "0.1.0",
      "dependencies": [
        {
          "name": "capstone",
          "features": [ "x86" ]
        }
      ]
    }
    ```
2. Run `vcpkg install` in that folder.
3. `capstone[core]` is installed instead of `capstone[x86]`.
    See: https://github.com/microsoft/vcpkg/blob/master/ports/capstone/CONTROL

**Expected behavior**

`capstone[x86]` should have been installed.

**Comment by AlexAltea** [comment]
CC @strega-nil

**Comment by strega-nil** [comment]
I will look into this.
