### ISSUE TITLE
[ffmpeg] build failure

### ISSUE THREAD

**Issue by vagor77** [microsoft/vcpkg#12328]
Made on the clean install
Downloaded clean vcpkg

Host Enviroment
OS:Windows 10 x64
Compiler: Visual Studio/C++ 2019 16.6.3

**To Reproduce**
vcpkg install ffmpeg:x64-windows-static

**Failure logs** 
-- Using cached W:/LIB/vcpkg-master/downloads/ffmpeg-ffmpeg-n4.2.tar.gz
-- Cleaning sources at W:/LIB/vcpkg-master/buildtrees/ffmpeg/src/n4.2-a4d149a5c6.clean. Pass --editable to vcpkg to reuse sources.
-- Extracting source W:/LIB/vcpkg-master/downloads/ffmpeg-ffmpeg-n4.2.tar.gz
-- Applying patch 0001-create-lib-libraries.patch
-- Applying patch 0003-fix-windowsinclude.patch
-- Applying patch 0004-fix-debug-build.patch
-- Applying patch 0005-fix-libvpx-linking.patch
-- Applying patch 0006-fix-StaticFeatures.patch
-- Using source at W:/LIB/vcpkg-master/buildtrees/ffmpeg/src/n4.2-a4d149a5c6.clean
-- Acquiring MSYS Packages...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: W:/LIB/vcpkg-master/downloads/tools/msys2/msys64/usr/bin/bash.exe --noprofile --norc -c "pacman -S --noconfirm --needed diffutils make"
    Working Directory: W:/LIB/vcpkg-master/downloads/tools/msys2
    Error code: 1
    See logs for more information:
      W:\LIB\vcpkg-master\buildtrees\ffmpeg\msys-pacman-x64-windows-static-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_acquire_msys.cmake:127 (vcpkg_execute_required_process)
  ports/ffmpeg/portfile.cmake:41 (vcpkg_acquire_msys)
  scripts/ports.cmake:76 (include)

error: mingw32: signature from "Alexey Pavlov (Alexpux) <alexpux@gmail.com>" is unknown trust
error: mingw64: signature from "Alexey Pavlov (Alexpux) <alexpux@gmail.com>" is unknown trust
error: msys: signature from "Alexey Pavlov (Alexpux) <alexpux@gmail.com>" is unknown trust
error: database 'mingw32' is not valid (invalid or corrupted database (PGP signature))
error: database 'mingw64' is not valid (invalid or corrupted database (PGP signature))
error: database 'msys' is not valid (invalid or corrupted database (PGP signature))

**Comment by PhoebeHui** [comment]
@vagor77, thanks for reporting this issue!

From your log, It seems fail to ' Acquiring MSYS Packages' step, could you attach failure log 'W:\LIB\vcpkg-master\buildtrees\ffmpeg\msys-pacman-x64-windows-static-err.log'?

I can't repro this issue, it built successfully for me.
The following packages will be built and installed:
    ffmpeg[avresample,core]:x64-windows-static
Starting package 1/1: ffmpeg:x64-windows-static
Building package ffmpeg[avresample,core]:x64-windows-static...
-- Using cached E:/VCPKG/boost_173/vcpkg/downloads/ffmpeg-ffmpeg-n4.2.tar.gz
-- Extracting source E:/VCPKG/boost_173/vcpkg/downloads/ffmpeg-ffmpeg-n4.2.tar.gz
-- Applying patch 0001-create-lib-libraries.patch
-- Applying patch 0003-fix-windowsinclude.patch
-- Applying patch 0004-fix-debug-build.patch
-- Applying patch 0005-fix-libvpx-linking.patch
-- Applying patch 0006-fix-StaticFeatures.patch
-- Using source at E:/VCPKG/boost_173/vcpkg/buildtrees/ffmpeg/src/n4.2-a4d149a5c6.clean
-- Acquiring MSYS Packages...
-- Acquiring MSYS Packages... OK
-- Building Options: --enable-asm --enable-yasm --disable-doc --enable-debug --enable-runtime-cpudetect --disable-openssl --disable-ffmpeg --disable-ffplay --disable-ffprobe --disable-libvpx --disable-libx264 --disable-opencl --disable-lzma --disable-bzlib --enable-avresample --disable-cuda --disable-nvenc --disable-cuvid --disable-libnpp --disable-avisynth  --extra-cflags=-DHAVE_UNISTD_H=0
-- Building Release Options:  --extra-cflags=-MT --extra-cxxflags=-MT
-- Building ffmpeg for Release
-- Building Debug Options: --debug --extra-cflags=-MTd --extra-cxxflags=-MTd
-- Building ffmpeg for Debug
-- Installing: E:/VCPKG/boost_173/vcpkg/packages/ffmpeg_x64-windows-static/share/ffmpeg/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package ffmpeg[avresample,core]:x64-windows-static... done
Installing package ffmpeg[avresample,core]:x64-windows-static...
Installing package ffmpeg[avresample,core]:x64-windows-static... done
Elapsed time for package ffmpeg:x64-windows-static: 31.63 min

Total elapsed time: 31.64 min

**Comment by PhoebeHui** [comment]
@vagor77, could you delete .\downloads\tools\msys2 directory and try to build ffmpeg again and see if this issue still exist?

**Comment by vagor77** [comment]
the content of the msys-pacman-x64-windows-static-err.log was like this.
rror: mingw32: signature from "Alexey Pavlov (Alexpux) alexpux@gmail.com" is unknown trust
error: mingw64: signature from "Alexey Pavlov (Alexpux) alexpux@gmail.com" is unknown trust
error: msys: signature from "Alexey Pavlov (Alexpux) alexpux@gmail.com" is unknown trust
error: database 'mingw32' is not valid (invalid or corrupted database (PGP signature))
error: database 'mingw64' is not valid (invalid or corrupted database (PGP signature))
error: database 'msys' is not valid (invalid or corrupted database (PGP signature))


deleting msys2 and trying to build ffmpeg did not help.
But looks like I was able to build by disabling antivirus, which is strange.
Let me investigate a bit more

**Comment by vagor77** [comment]
> @vagor77, could you delete .\downloads\tools\msys2 directory and try to build ffmpeg again and see if this issue still exist?

after deleting the folder and disabling antivirus it compiled.

**Comment by PhoebeHui** [comment]
Thanks for your updates!
