### ISSUE TITLE
[hiredis[ssl]] build failure

### ISSUE THREAD

**Issue by RameshKandukuriB** [microsoft/vcpkg#12327]
**Host Environment**
- OS: Windows 64 bit
- Compiler: VS2019 Version 16.6.2

**To Reproduce**
vcpkg upgrade hiredis[ssl]:x64-windows-static
vcpkg upgrade hiredis[ssl]:x64-windows-static --no-dry-run
vcpkg install hiredis[ssl]:x64-windows-static --recurse
whereas vcpkg install hiredis[core]:x64-windows-static is building successfully

**Failure logs** 

**\vcpkg\buildtrees\hiredis\src\4889033d94-d35835c897.clean\ssl.c(37): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory**

Computing installation plan...
The following packages will be rebuilt:
    hiredis[core,ssl]:x64-windows-static
Starting package 1/2: hiredis:x64-windows-static
Removing package hiredis:x64-windows-static...
Removing package hiredis:x64-windows-static... done
Elapsed time for package hiredis:x64-windows-static: 83.49 ms
Starting package 2/2: hiredis:x64-windows-static
Building package hiredis[core,ssl]:x64-windows-static...
-- Using cached  /vcpkg/downloads/redis-hiredis-e777b0295eeeda89ee2ecef6ec5cb54889033d94.tar.gz
-- Cleaning sources at  /vcpkg/buildtrees/hiredis/src/4889033d94-d35835c897.clean. Pass --editable to vcpkg to reuse sources.
-- Extracting source  /vcpkg/downloads/redis-hiredis-e777b0295eeeda89ee2ecef6ec5cb54889033d94.tar.gz
-- Applying patch fix-feature-example.patch
-- Applying patch support-static-in-win.patch
-- Applying patch fix-timeval.patch
-- Using source at  /vcpkg/buildtrees/hiredis/src/4889033d94-d35835c897.clean
-- Configuring x64-windows-static
-- Building x64-windows-static-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed:  /vcpkg/downloads/tools/cmake-3.17.2-windows/cmake-3.17.2-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v
    Working Directory:  /vcpkg/buildtrees/hiredis/x64-windows-static-dbg
    See logs for more information:
      \vcpkg\buildtrees\hiredis\install-x64-windows-static-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/hiredis/portfile.cmake:28 (vcpkg_install_cmake)
  scripts/ports.cmake:76 (include)

Error: Building package hiredis:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: hiredis:x64-windows-static
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by NancyLi1013** [comment]
Hi @RameshKandukuriB 
Thanks for posting this issue.
I try to build this on my local and I cannot reproduce it.

```
PS F:\tools\vcpkg> .\vcpkg install hiredis[ssl]:x64-windows-static --recurse
Computing installation plan...
The following packages will be built and installed:
    hiredis[core,ssl]:x64-windows-static
Starting package 1/1: hiredis:x64-windows-static
Building package hiredis[core,ssl]:x64-windows-static...
-- Using cached F:/tools/vcpkg/downloads/redis-hiredis-e777b0295eeeda89ee2ecef6ec5cb54889033d94.tar.gz
-- Cleaning sources at F:/tools/vcpkg/buildtrees/hiredis/src/4889033d94-d35835c897.clean. Pass --editable to vcpkg to reuse sources.
-- Extracting source F:/tools/vcpkg/downloads/redis-hiredis-e777b0295eeeda89ee2ecef6ec5cb54889033d94.tar.gz
-- Applying patch fix-feature-example.patch
-- Applying patch support-static-in-win.patch
-- Applying patch fix-timeval.patch
-- Using source at F:/tools/vcpkg/buildtrees/hiredis/src/4889033d94-d35835c897.clean
-- Configuring x64-windows-static
-- Building x64-windows-static-dbg
-- Building x64-windows-static-rel
-- Installing: F:/tools/vcpkg/packages/hiredis_x64-windows-static/share/hiredis/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package hiredis[core,ssl]:x64-windows-static... done
Installing package hiredis[core,ssl]:x64-windows-static...
Installing package hiredis[core,ssl]:x64-windows-static... done
Elapsed time for package hiredis:x64-windows-static: 44.38 s

Total elapsed time: 44.63 s
```

**Comment by NancyLi1013** [comment]
Since `pthread.h` is only required on Unix platform. We can update this as the follows:
```

#ifdef _WIN32
#include <windows.h>
#else
#include <pthread.h>
#endif
```
Could you please try to rebuild this?
