### ISSUE TITLE
build a lib with specified version

### ISSUE THREAD

**Issue by alimai** [microsoft/vcpkg#12321]
I try to build a lib with specified version, and find a suggestion as following in #11768 :

1. Use command .\vcpkg x-history qt5
2. Get the commit id of the version you need.
3. Use command git reset <commit id>
4. Rebuild qt5.

_Originally posted by @timautry in https://github.com/microsoft/vcpkg/issues/11768#issuecomment-639874654_

I do a test with the zlib(The latest version of zlib in vcpkg is 1.2.11-6),
Vcpkg still build the latest version of module when I following the suggestion of @timautry timautry.

1. git reset 18b029a
2. .\vcpkg x-history zlib
version date vcpkg commit
1.2.11-5 2019-06-15 18b029a
1.2.11-3 2018-08-30 ab54bfa
1.2.11-2 2017-09-23 67e876c
1.2.11-1 2017-09-09 26516fe
1.2.11 2017-01-17 0d50c67
1.2.10 2017-01-04 6a220ed
1.2.8 2016-11-08 1808d46
[note: It seems the current version should be 1.2.11-5 now.]
3. .\vcpkg install zlib
Computing installation plan...
The following packages will be built and installed:
zlib[core]:x64-windows
Downloading powershell-core...
Extracting powershell-core...
Starting package 1/1: zlib:x64-windows
Building package zlib[core]:x64-windows...
-- Downloading http://www.zlib.net/zlib-1.2.11.tar.gz...
-- Extracting source E:/vcpkg/downloads/zlib1211.tar.gz
-- Applying patch cmake_dont_build_more_than_needed.patch
-- Using source at E:/vcpkg/buildtrees/zlib/src/1.2.11-deec42f53b.clean
-- Configuring x64-windows
-- Building x64-windows-rel
-- Installing: E:/vcpkg/packages/zlib_x64-windows/share/zlib/copyright
-- Performing post-build validation
-- Performing post-build validation done
Installing package zlib[core]:x64-windows...
Installing package zlib[core]:x64-windows... done
4. .\vcpkg list
zlib:x64-windows 1.2.11-6 A compression library

The installed version is still 1.2.11-6, is there any thing wrong?

**Comment by JackBoosY** [comment]
Confirmed, but I think this is just a display issue.

**Comment by alimai** [comment]
Just a 

> Confirmed, but I think this is just a display issue.

Hi, it seem not that. 
if you test the boost module, you will find that the vcpkg download the tar.gz file with latest  version from github.

**Comment by alimai** [comment]
Misuse(close the issue)

**Comment by Neumann-A** [comment]
`git reset 18b029a` probably requires `--hard ` to reset the working tree instead of leaving it untouched ;)

**Comment by alimai** [comment]
> `git reset 18b029a` probably requires `--hard ` to reset the working tree instead of leaving it untouched ;)

Oh, do you mean the buildtree?
I test it with a new vcpkg, no lib has been installed before, so there don't have any of the following folder: buildtrees,downloads,installed,packages

And I try reset it with --hard option, 
After that, the vcpkg told me to run 'bootstrap-vcpkg.bat',
Then I got many many errors.

**Comment by JackBoosY** [comment]
@ras0219 @ras0219-msft Could you take a look?

Thanks.

**Comment by strega-nil** [comment]
@alimai the correct command to run is probably:

```sh
$ git checkout <copied commit> -- ports/<port-name>
```

This will check out _only_ the specified port from the tree. You can also do something like:

```
$ mkdir pinned-ports
$ git checkout <copied commit> -- ports/<port-name>
$ mv ports/<port-name> pinned-ports
$ git checkout HEAD -- ports
```

and then proceed to use `vcpkg` with the additional flag `--overlay-ports=./pinned-ports` :)

**Comment by alimai** [comment]
> @alimai the correct command to run is probably:
> 
> ```shell
> $ git checkout <copied commit> -- ports/<port-name>
> ```
> 
> This will check out _only_ the specified port from the tree. You can also do something like:
> 
> ```
> $ mkdir pinned-ports
> $ git checkout <copied commit> -- ports/<port-name>
> $ mv ports/<port-name> pinned-ports
> $ git checkout HEAD -- ports
> ```
> 
> and then proceed to use `vcpkg` with the additional flag `--overlay-ports=./pinned-ports` :)

Thanks. It works now.

**Comment by hamaney** [comment]
I need this to be automated. it is here for you just in case 


```python
from pathlib import Path
import subprocess as p
import shutil

MISSING_PKG_NAME = 'boost-signals'
MISSING_PKG_VERSION = '1.68.0'


REPO_ROOT = Path(__file__).parent.parent.parent.parent # CHANGE TO FIT UR NEED
PORTS_OVERLAY_PATH = REPO_ROOT / 'pinned_ports'   # CHANGE TO FIT UR NEED

# VCPKG --assumed to be a submodule in repo root
VCPKG_PATH = REPO_ROOT / 'vcpkg'
VCPKG_EXE = VCPKG_PATH / 'vcpkg.exe'
VERSIONS_PATH = VCPKG_PATH / 'versions'
if not VCPKG_PATH.exists():
    raise FileNotFoundError(f"dir does not exist: {VCPKG_PATH}")

if not VERSIONS_PATH.exists():
    raise FileNotFoundError(f"dir does not exist: {VERSIONS_PATH}")


def get_git_hash_for_pkg_latest_version_patch():
    process = p.run([str(VCPKG_EXE), 'x-history', MISSING_PKG_NAME],
                    capture_output=True, encoding='utf-8', check=True)
    out = process.stdout
    print(out)
    out_lines = out.splitlines()
    out_lines_match_missing_pkg_version = list(
        filter(lambda line: MISSING_PKG_VERSION in line,  out_lines))
    version_and_hash_dict = {}
    versions_list = []
    for line in out_lines_match_missing_pkg_version:
        line_splitted = line.strip().split(' ')
        # no need to clean the mid spaces we only interseted in the first and last element
        version = line_splitted[0]
        version_git_hash = line_splitted[-1]

        version_and_hash_dict[version] = version_git_hash
        versions_list.append(version)

    latest_path_version = sorted(versions_list)[-1]

    git_hash = version_and_hash_dict[latest_path_version]
    print(f'selected {latest_path_version} : {git_hash}')
    return git_hash


def reset_vcpkg_ports_to_this_git_hash(git_hash):
    done = p.run(['git', 'checkout', git_hash, '--', f'ports/{MISSING_PKG_NAME}'],
                 # capture_output=False,
                 # encoding='utf-8',
                 check=True,
                 cwd=VCPKG_PATH)
    print(
        f'switched {VCPKG_PATH}/ports/{MISSING_PKG_NAME} to {git_hash} where it exists')
    # print(done.stdout)
    # print(done.stderr)


def copy_pkg_port_to_pinned_ports_dir():
    shutil.copytree(VCPKG_PATH / 'ports' / MISSING_PKG_NAME,
                    PORTS_OVERLAY_PATH / MISSING_PKG_NAME,
                    dirs_exist_ok=True)
    print(
        f'copied {VCPKG_PATH}/ports/{MISSING_PKG_NAME} to {PORTS_OVERLAY_PATH}')


def restore_vcpkg_ports_to_HEAD():
    p.run(['git', 'checkout', 'HEAD', '--', 'ports'],
          capture_output=True, encoding='utf-8', check=True, cwd=VCPKG_PATH)
    print(
        f'restored {VCPKG_PATH}/ports back to HEAD')


missing_pkg_version_git_hash = get_git_hash_for_pkg_latest_version_patch()
reset_vcpkg_ports_to_this_git_hash(missing_pkg_version_git_hash)
copy_pkg_port_to_pinned_ports_dir()
restore_vcpkg_ports_to_HEAD()
```
