### ISSUE TITLE
[libyuv] regression: lost all jpeg APIs for static lib builds

### ISSUE THREAD

**Issue by diablodale** [microsoft/vcpkg#12335]
The recent PR https://github.com/microsoft/vcpkg/pull/12213 by @PhoebeHui broke all jpeg APIs in libyuv for static libs.
This is most likely due to the following change:

https://github.com/microsoft/vcpkg/blob/3bffe1c0493c1220d3db2803a53c79add20d63d2/ports/libyuv/fix-build-type.patch#L32

This logic change skips an entire block which defines loading dependent jpeg libraries and setting some defines. Naturally, this is undesired.

### Setup

* Microsoft Windows [Version 10.0.19041.329]
* Visual Studio Community 16.6.3

### Repro

1. vcpkg version 2020.06.15-nohash
2. ports at current git commit 3bffe1c0493c1220d3db2803a53c79add20d63d2
3. Use a x64 static lib triplet
4. `vcpkg install libyuv`
5. Create a C++ project and configure its CMakeLists.txt as vcpkg told you
6. `#include <libyuv/mjpeg_decoder.h>`
7. `int foo = libyuv::MJPGSize(nullptr, 42, nullptr, nullptr);`
8. compile it

### Result

```
error LNK2019: unresolved external symbol MJPGSize referenced in function...
```

### Expected

Successful compile. Though it won't run successfully because those parameters are meaningless.

**Comment by PhoebeHui** [comment]
Sorry for that, I will take a look.

**Comment by PhoebeHui** [comment]
@diablodale, the changes doesn't from my PR https://github.com/microsoft/vcpkg/pull/12213, I only updated the targets file name and add dependency port JPEG to config file, so it's not a regression from PR#12213. It should be another issue, I will continue to investigate it.

**Comment by PhoebeHui** [comment]
It from PR https://github.com/microsoft/vcpkg/pull/8769, I will confirm with Jack.

**Comment by PhoebeHui** [comment]
@diablodale, thanks for reporting this issue!

I have summit a PR to fix this issue, can you help confirm if it works for you?
