### ISSUE TITLE
[vcpkg] list, search and update options no longer have <Port Version> shown after <Version> 

### ISSUE THREAD

**Issue by timautry** [microsoft/vcpkg#12331]
**Describe the bug**
vcpkg list, search and update options no longer have `<Port Version>` shown after `<Version>` in the output list. 

**Environment**
- OS: [Windows/Linux]
- Compiler: VS 2017/2019, gcc 9.2.1

**To Reproduce**
1. `->vcpkg update`
`Using local portfile versions. To update the local portfiles, use git pull.`
`The following packages differ from their port versions:`
`    fontconfig:x64-windows           2.12.4-10 -> 2.12.4`**-??**
`    freetype:x64-windows             2.10.1-6 -> 2.10.2`**-??**

2.  `->vcpkg list freetype` -or- `->vcpkg list fontconfig` 
      - **before CONTROL file changing <Port Version> to separate field**
`freetype:x64-windows                               2.10.1-6         A library to render fonts.`
`fontconfig:x64-windows                             2.12.4-10        Library for configuring and customizing font acc...`
      - **after CONTROL file changing <Port Version> to separate field**
`freetype:x64-windows                               2.10.2           A library to render fonts.`
`fontconfig:x64-windows                             2.12.4           Library for configuring and customizing font acc...`

3. `->vcpkg search freetype` -or- `vcpkg search fontconfig`
      - **before CONTROL file changing <Port Version> to separate field**
`freetype             2.10.2-6         A library to render fonts.`
`fontconfig         2.12.4-10        Library for configuring and customizing font access.`
      - **after CONTROL file changing <Port Version> to separate field**
`freetype             2.10.2           A library to render fonts.`
`fontconfig         2.12.4           Library for configuring and customizing font access.`

**Expected behavior**
- The vcpkg list, search or update to include the Port Version on the end of the Version in the output list. 
- I had to look in the CONTROL files for:
  - freetype had been updated from 2.10.1-6 to Version 2.10.2 Port Version 1
  - fontconfig had been updated from 2.12.5-10 to Version 2.12.4 Port Version 11

**Failure logs** 
None

**Additional context**
Note: I used freetype and fontconfig in these examples as they were the only two ports needing upgrade with the latest `git pull` and `.\bootstrap-vcpkg.bat` or `./bootstrap-vcpkg.sh`, but it is happening to all ports when the CONTROL file is updated to the new format separating the Port Version from the overall software Version.

**Comment by JackBoosY** [comment]
@ras0219 @ras0219-msft Could you please take a look?

Thanks.

**Comment by timautry** [comment]
Thank you @strega-nil - have a wonderful week 🥇
