### ISSUE TITLE
ffmpeg build failure

### ISSUE THREAD

**Issue by GAInTheHouse** [microsoft/vcpkg#12339]
**Host Environment**
- OS: Windows

**To Reproduce**
./vcpkg install opencv[FFmpeg] 

**Failure logs** 
Here's the command prompt dialogue box:

PS C:\Users\GAInTheHouse\vcpkg-master> ./vcpkg install opencv[ffmpeg]
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
Computing installation plan...
The following packages will be built and installed:
  * ffmpeg[avresample,core]:x64-windows
    opencv[core,dnn,ffmpeg,jpeg,opengl,png,tiff,webp]:x64-windows
  * opencv4[core,dnn,ffmpeg,jpeg,opengl,png,tiff,webp]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/3: ffmpeg:x64-windows
Building package ffmpeg[avresample,core]:x64-windows...
-- Using cached C:/Users/GAInTheHouse/vcpkg-master/downloads/ffmpeg-ffmpeg-n4.2.tar.gz
-- Using source at C:/Users/GAInTheHouse/vcpkg-master/buildtrees/ffmpeg/src/n4.2-a4d149a5c6
-- Acquiring MSYS Packages...
      0 [main] bash (11032) shared_info::initialize: size of shared memory region changed from 51128 to 40888
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: C:/Users/GAInTheHouse/vcpkg-master/downloads/tools/msys2/msys64/usr/bin/bash.exe --noprofile --norc -c "pacman -Sy --noconfirm --needed diffutils make"
    Working Directory: C:/Users/GAInTheHouse/vcpkg-master/downloads/tools/msys2
    Error code: Access violation
    See logs for more information:
      C:\Users\GAInTheHouse\vcpkg-master\buildtrees\ffmpeg\msys-pacman-x64-windows-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_acquire_msys.cmake:108 (vcpkg_execute_required_process)
  ports/ffmpeg/portfile.cmake:41 (vcpkg_acquire_msys)
  scripts/ports.cmake:90 (include)

Error: Building package ffmpeg:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: ffmpeg:x64-windows
  Vcpkg version: 2020.02.04-nohash

C:\Users\GAInTheHouse\vcpkg-master\buildtrees\ffmpeg\msys-pacman-x64-windows-err.log contains the following text:
      0 [main] bash (11032) shared_info::initialize: size of shared memory region changed from 51128 to 40888

**Comment by PhoebeHui** [comment]
Related to https://github.com/microsoft/vcpkg/issues/12328

**Comment by PhoebeHui** [comment]
@GAInTheHouse, could you delete .\downloads\tools\msys2 directory and try to build ffmpeg again and see if this issue still exist?

**Comment by GAInTheHouse** [comment]
The issue still exists.
This is the PowerShell description:

PS C:\Users\GAInTheHouse\vcpkg-master> ./vcpkg install opencv[ffmpeg]
Computing installation plan...
The following packages will be built and installed:
  * ffmpeg[avresample,core]:x64-windows
    opencv[core,dnn,ffmpeg,jpeg,opengl,png,tiff,webp]:x64-windows
  * opencv4[core,dnn,ffmpeg,jpeg,opengl,png,tiff,webp]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/3: ffmpeg:x64-windows
Building package ffmpeg[avresample,core]:x64-windows...
-- Using cached C:/Users/GAInTheHouse/vcpkg-master/downloads/ffmpeg-ffmpeg-n4.2.tar.gz
-- Using source at C:/Users/GAInTheHouse/vcpkg-master/buildtrees/ffmpeg/src/n4.2-a4d149a5c6
-- Acquiring MSYS2...
-- Using cached C:/Users/GAInTheHouse/vcpkg-master/downloads/msys2-base-x86_64-20190524.tar.xz
gpg: /etc/pacman.d/gnupg/trustdb.gpg: trustdb created
gpg: no ultimately trusted keys found
gpg: starting migration from earlier GnuPG versions
gpg: porting secret keys from '/etc/pacman.d/gnupg/secring.gpg' to gpg-agent
gpg: migration succeeded
gpg: Generating pacman keyring master key...
gpg: key 095B0A575FF4B847 marked as ultimately trusted
gpg: directory '/etc/pacman.d/gnupg/openpgp-revocs.d' created
gpg: revocation certificate stored as '/etc/pacman.d/gnupg/openpgp-revocs.d/9AD5B9EC3F84C63A185350DF095B0A575FF4B847.rev'
gpg: Done
==> Updating trust database...
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
==> Appending keys from msys2.gpg...
==> Locally signing trusted keys in keyring...
  -> Locally signing key D55E7A6D7CE9BA1587C0ACACF40D263ECA25678A...
  -> Locally signing key 123D4D51A1793859C2BE916BBBE514E53E0D0813...
  -> Locally signing key B91BCF3303284BF90CC043CA9F418C233E652008...
  -> Locally signing key 9DD0D4217D75A33B896159E6DA7EF2ABAEEA755C...
==> Importing owner trust values...
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: inserting ownertrust of 4
==> Updating trust database...
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   4  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: depth: 1  valid:   4  signed:   3  trust: 0-, 0q, 0n, 4m, 0f, 0u
gpg: depth: 2  valid:   3  signed:   0  trust: 3-, 0q, 0n, 0m, 0f, 0u
:: Synchronizing package databases...
downloading mingw32.db...
downloading mingw32.db.sig...
downloading mingw64.db...
downloading mingw64.db.sig...
downloading msys.db...
downloading msys.db.sig...
:: Starting core system upgrade...
warning: resolving dependencies...
terminate other MSYS2 programs before proceeding
looking for conflicting packages...

Packages (8) bash-4.4.023-2  filesystem-2020.02-4  libzstd-1.4.5-2  mintty-1~3.2.0-1  msys2-runtime-3.1.5-3  pacman-5.2.1-12  pacman-mirrors-20200329-1  zstd-1.4.5-2

Total Download Size:    16.60 MiB
Total Installed Size:   58.29 MiB
Net Upgrade Size:      -11.43 MiB

:: Proceed with installation? [Y/n]
:: Retrieving packages...
downloading msys2-runtime-3.1.5-3-x86_64.pkg.tar.xz...
downloading bash-4.4.023-2-x86_64.pkg.tar.xz...
downloading filesystem-2020.02-4-x86_64.pkg.tar.xz...
downloading mintty-1~3.2.0-1-x86_64.pkg.tar.xz...
downloading pacman-mirrors-20200329-1-any.pkg.tar.xz...
downloading libzstd-1.4.5-2-x86_64.pkg.tar.xz...
downloading zstd-1.4.5-2-x86_64.pkg.tar.xz...
downloading pacman-5.2.1-12-x86_64.pkg.tar.xz...
checking keyring...
checking package integrity...
loading package files...
checking for file conflicts...
checking available disk space...
:: Processing package changes...
upgrading msys2-runtime...
upgrading bash...
upgrading filesystem...
upgrading mintty...
upgrading pacman-mirrors...
installing libzstd...
installing zstd...
upgrading pacman...
warning: terminate MSYS2 without returning to shell and check for updates again
warning: for example close your terminal window instead of calling exit
-- Acquiring MSYS2... OK
-- Acquiring MSYS Packages...
      0 [main] bash (2064) shared_info::initialize: size of shared memory region changed from 51128 to 40888
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: C:/Users/GAInTheHouse/vcpkg-master/downloads/tools/msys2/msys64/usr/bin/bash.exe --noprofile --norc -c "pacman -Sy --noconfirm --needed diffutils make"
    Working Directory: C:/Users/GAInTheHouse/vcpkg-master/downloads/tools/msys2
    Error code: Access violation
    See logs for more information:
      C:\Users\GAInTheHouse\vcpkg-master\buildtrees\ffmpeg\msys-pacman-x64-windows-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_acquire_msys.cmake:108 (vcpkg_execute_required_process)
  ports/ffmpeg/portfile.cmake:41 (vcpkg_acquire_msys)
  scripts/ports.cmake:90 (include)

The Powershell does not accept any further commands until I interrupt it through the keyboard (Ctrl+C)

**Comment by cenit** [comment]
please change title to `ffmpeg[avresample,core]:x64-windows` build failure, unrelated to opencv

**Comment by PhoebeHui** [comment]
@GAInTheHouse, could try to  disabling antivirus and see if the issue still exist? See https://github.com/microsoft/vcpkg/issues/12328#issuecomment-656259912

**Comment by PhoebeHui** [comment]
Duplicated to issue https://github.com/microsoft/vcpkg/issues/12328

**Comment by GAInTheHouse** [comment]
I was able to install opencv[ffmpeg] successfully. I simply deleted all the folders from the tools directory as advised in a similar issue post.
I needed to compile the above for yolo darknet framework by AlexAB.
When I tried to build the darknet model, however, the issue of pthread came up.
I can confirm that I had installed it sing a similar fashion.
I also reconfirmed the download.
The entire error log is attached:

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----          7/9/2020  11:18 PM                build_win_release
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.19041.
-- The C compiler identification is MSVC 19.16.27040.0
-- The CXX compiler identification is MSVC 19.16.27040.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for a CUDA compiler
-- Looking for a CUDA compiler - NOTFOUND
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Found PThreads4W: optimized;C:/Users/GAInTheHouse/vcpkg-master/installed/x64-windows/lib/pthreadVC3.lib;debug;C:/Users/GAInTheHouse/vcpkg-master/installed/x64-windows/debug/lib/pthreadVC3d.lib
-- PThreads4W_DLL_DIR: C:/Users/GAInTheHouse/vcpkg-master/installed/x64-windows/include/../bin
-- Found OpenCV: C:/Users/GAInTheHouse/vcpkg-master/installed/x64-windows (found version "4.1.1")
-- Found Stb: C:/Users/GAInTheHouse/Downloads/darknet-master/darknet-master/3rdparty/stb/include
-- Found OpenMP_C: -openmp (found version "2.0")
-- Found OpenMP_CXX: -openmp (found version "2.0")
-- Found OpenMP: TRUE (found version "2.0")
-- ZED SDK not enabled, since it requires CUDA

PS C:\Users\GAInTheHouse\vcpkg-master> ./vcpkg install pthread
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
Computing installation plan...
The following packages are already installed:
    pthread[core]:x64-windows
Package pthread:x64-windows is already installed

The pthread issue was not there earlier.
It was generated after I deleted the files in the tools folder and installed opencv[fffmpeg].
I can also confirm that CUDA 10.0 is installed in my system, if that is a prerequisite of any kind.

**Comment by cenit** [comment]
Sorry I can’t understand which “issue of pthreads” you are referring to. From the logs it seems ok

**Comment by PhoebeHui** [comment]
@GAInTheHouse, I didn't see any failures from your log, could you provide us more informarion, like the failure log 'config-x64-windows-dbg-err.log', your log looks from config-x64-windows-dbg-out.log.

BTW, I tried to  install darknet:x64-windows, it built successfully for me with latest source.
PS E:\VCPKG\boost_173\vcpkg> ./vcpkg install darknet:x64-windows
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
Computing installation plan...
The following packages will be built and installed:
    darknet[core]:x64-windows
  * pthreads[core]:x64-windows
  * stb[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/3: pthreads:x64-windows
Building package pthreads[core]:x64-windows...
-- Trying auto-select mirror...
-- Downloading https://sourceforge.net/projects/pthreads4w//files/pthreads4w-code-v3.0.0.zip/download...
-- Extracting source E:/VCPKG/boost_173/vcpkg/downloads/pthreads4w-code-v3.0.0.zip
-- Using source at E:/VCPKG/boost_173/vcpkg/buildtrees/pthreads/src/49e541b66c-bb03a1deb3.clean
-- Building x64-windows-rel
-- Building x64-windows-rel done
-- Building x64-windows-dbg
-- Building x64-windows-dbg done
-- Installing: E:/VCPKG/boost_173/vcpkg/packages/pthreads_x64-windows/share/pthreads/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package pthreads[core]:x64-windows... done
Installing package pthreads[core]:x64-windows...
Installing package pthreads[core]:x64-windows... done
Elapsed time for package pthreads:x64-windows: 48.08 s
Starting package 2/3: stb:x64-windows
Building package stb[core]:x64-windows...
-- Downloading https://github.com/nothings/stb/archive/c72a95d766b8cbf5514e68d3ddbf6437ac9425b1.tar.gz...
-- Extracting source E:/VCPKG/boost_173/vcpkg/downloads/nothings-stb-c72a95d766b8cbf5514e68d3ddbf6437ac9425b1.tar.gz
-- Using source at E:/VCPKG/boost_173/vcpkg/buildtrees/stb/src/37ac9425b1-944b7d363a.clean
-- Installing: E:/VCPKG/boost_173/vcpkg/packages/stb_x64-windows/share/stb/copyright
-- Installing: E:/VCPKG/boost_173/vcpkg/packages/stb_x64-windows/share/stb/FindStb.cmake
-- Installing: E:/VCPKG/boost_173/vcpkg/packages/stb_x64-windows/share/stb/vcpkg-cmake-wrapper.cmake
-- Performing post-build validation
-- Performing post-build validation done
Building package stb[core]:x64-windows... done
Installing package stb[core]:x64-windows...
Installing package stb[core]:x64-windows... done
Elapsed time for package stb:x64-windows: 2.092 s
Starting package 3/3: darknet:x64-windows
Building package darknet[core]:x64-windows...
-- Downloading https://github.com/AlexeyAB/darknet/archive/81290b07376c5abb4988a492dda70913bb90133d.tar.gz...
-- Extracting source E:/VCPKG/boost_173/vcpkg/downloads/AlexeyAB-darknet-81290b07376c5abb4988a492dda70913bb90133d.tar.gz
-- Using source at E:/VCPKG/boost_173/vcpkg/buildtrees/darknet/src/13bb90133d-a4584e7461.clean
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: E:/VCPKG/boost_173/vcpkg/packages/darknet_x64-windows/share/darknet/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package darknet[core]:x64-windows... done
Installing package darknet[core]:x64-windows...
Installing package darknet[core]:x64-windows... done
Elapsed time for package darknet:x64-windows: 1.207 min

Total elapsed time: 2.046 min

The package darknet:x64-windows provides CMake targets:

    find_package(Darknet CONFIG REQUIRED)
    target_link_libraries(main PRIVATE Darknet::dark)

**Comment by GAInTheHouse** [comment]
> Sorry I can’t understand which “issue of pthreads” you are referring to. From the logs it seems ok

Looking for PThreads.h ... Not found

**Comment by GAInTheHouse** [comment]
> @GAInTheHouse, I didn't see any failures from your log, could you provide us more informarion, like the failure log 'config-x64-windows-dbg-err.log', your log looks from config-x64-windows-dbg-out.log.
> 
> BTW, I tried to  install darknet:x64-windows, it built successfully for me with latest source.
> PS E:\VCPKG\boost_173\vcpkg> ./vcpkg install darknet:x64-windows
> Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
> Computing installation plan...
> The following packages will be built and installed:
>     darknet[core]:x64-windows
>   * pthreads[core]:x64-windows
>   * stb[core]:x64-windows
> Additional packages (*) will be modified to complete this operation.
> Starting package 1/3: pthreads:x64-windows
> Building package pthreads[core]:x64-windows...
> -- Trying auto-select mirror...
> -- Downloading https://sourceforge.net/projects/pthreads4w//files/pthreads4w-code-v3.0.0.zip/download...
> -- Extracting source E:/VCPKG/boost_173/vcpkg/downloads/pthreads4w-code-v3.0.0.zip
> -- Using source at E:/VCPKG/boost_173/vcpkg/buildtrees/pthreads/src/49e541b66c-bb03a1deb3.clean
> -- Building x64-windows-rel
> -- Building x64-windows-rel done
> -- Building x64-windows-dbg
> -- Building x64-windows-dbg done
> -- Installing: E:/VCPKG/boost_173/vcpkg/packages/pthreads_x64-windows/share/pthreads/copyright
> -- Performing post-build validation
> -- Performing post-build validation done
> Building package pthreads[core]:x64-windows... done
> Installing package pthreads[core]:x64-windows...
> Installing package pthreads[core]:x64-windows... done
> Elapsed time for package pthreads:x64-windows: 48.08 s
> Starting package 2/3: stb:x64-windows
> Building package stb[core]:x64-windows...
> -- Downloading https://github.com/nothings/stb/archive/c72a95d766b8cbf5514e68d3ddbf6437ac9425b1.tar.gz...
> -- Extracting source E:/VCPKG/boost_173/vcpkg/downloads/nothings-stb-c72a95d766b8cbf5514e68d3ddbf6437ac9425b1.tar.gz
> -- Using source at E:/VCPKG/boost_173/vcpkg/buildtrees/stb/src/37ac9425b1-944b7d363a.clean
> -- Installing: E:/VCPKG/boost_173/vcpkg/packages/stb_x64-windows/share/stb/copyright
> -- Installing: E:/VCPKG/boost_173/vcpkg/packages/stb_x64-windows/share/stb/FindStb.cmake
> -- Installing: E:/VCPKG/boost_173/vcpkg/packages/stb_x64-windows/share/stb/vcpkg-cmake-wrapper.cmake
> -- Performing post-build validation
> -- Performing post-build validation done
> Building package stb[core]:x64-windows... done
> Installing package stb[core]:x64-windows...
> Installing package stb[core]:x64-windows... done
> Elapsed time for package stb:x64-windows: 2.092 s
> Starting package 3/3: darknet:x64-windows
> Building package darknet[core]:x64-windows...
> -- Downloading https://github.com/AlexeyAB/darknet/archive/81290b07376c5abb4988a492dda70913bb90133d.tar.gz...
> -- Extracting source E:/VCPKG/boost_173/vcpkg/downloads/AlexeyAB-darknet-81290b07376c5abb4988a492dda70913bb90133d.tar.gz
> -- Using source at E:/VCPKG/boost_173/vcpkg/buildtrees/darknet/src/13bb90133d-a4584e7461.clean
> -- Configuring x64-windows-dbg
> -- Configuring x64-windows-rel
> -- Building x64-windows-dbg
> -- Building x64-windows-rel
> -- Installing: E:/VCPKG/boost_173/vcpkg/packages/darknet_x64-windows/share/darknet/copyright
> -- Performing post-build validation
> -- Performing post-build validation done
> Building package darknet[core]:x64-windows... done
> Installing package darknet[core]:x64-windows...
> Installing package darknet[core]:x64-windows... done
> Elapsed time for package darknet:x64-windows: 1.207 min
> 
> Total elapsed time: 2.046 min
> 
> The package darknet:x64-windows provides CMake targets:
> 
>     find_package(Darknet CONFIG REQUIRED)
>     target_link_libraries(main PRIVATE Darknet::dark)

So far I've tried building darknet using the build commands. I shall try using vcpkg to install the same.

**Comment by GAInTheHouse** [comment]
Hi @PhoebeHui did you try running the python file darknet_video.py after installing darknet using vcpkg?
It produces an import error for me.

C:\Users\GAInTheHouse\vcpkg-master\buildtrees\darknet\src\13bb90133d-a4584e7461> python darknet_video.py
Traceback (most recent call last):
  File "C:\Users\GAInTheHouse\vcpkg-master\buildtrees\darknet\src\13bb90133d-a4584e7461\darknet.py", line 111, in <module>
    raise ValueError("NoDLL")
ValueError: NoDLL

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "darknet_video.py", line 8, in <module>
    import darknet
  File "C:\Users\GAInTheHouse\vcpkg-master\buildtrees\darknet\src\13bb90133d-a4584e7461\darknet.py", line 121, in <module>
    lib = CDLL(winGPUdll, RTLD_GLOBAL)
  File "C:\Users\GAInTheHouse\AppData\Local\Programs\Python\Python37\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

**Comment by cenit** [comment]
`Looking for PThreads.h ... Not found` is not an error!!! It's just cmake doing its things and verify platform resources. 

For what concern using darknet_video.py after installing darknet using vcpkg, you have to manually copy dlls from the installed/x64-windows/bin folder to where you have the python script

**Comment by GAInTheHouse** [comment]
@cenit I have copied all the dll's and into the python directory. However, the error persists.

C:\Users\GAInTheHouse\vcpkg-master\buildtrees\darknet\src\13bb90133d-a4584e7461>python darknet_video.py
Traceback (most recent call last):
  File "C:\Users\GAInTheHouse\vcpkg-master\buildtrees\darknet\src\13bb90133d-a4584e7461\darknet.py", line 111, in <module>
    raise ValueError("NoDLL")
ValueError: NoDLL

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "darknet_video.py", line 8, in <module>
    import darknet
  File "C:\Users\GAInTheHouse\vcpkg-master\buildtrees\darknet\src\13bb90133d-a4584e7461\darknet.py", line 121, in <module>
    lib = CDLL(winGPUdll, RTLD_GLOBAL)
  File "C:\Users\GAInTheHouse\AppData\Local\Programs\Python\Python37\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

**Comment by JonLiu1993** [comment]
@GAInTheHouse ,Sorry reply you so late,do you solve the problem finally?

**Comment by JonLiu1993** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
