### ISSUE TITLE
[docker] Intermittent build failures running bootstrap-vcpkg.sh

### ISSUE THREAD

**Issue by jamesalbert** [microsoft/vcpkg#12334]
**Describe the bug**
I'm trying to build vcpkg in a debian 10 environment in docker. Fairly simple Dockerfile:

```Dockerfile
FROM debian:10

RUN apt update
RUN apt install -y git make curl gcc g++ unzip tar autoconf automake libtool libssl-dev valgrind

# Install vcpkg
RUN git clone https://github.com/Microsoft/vcpkg.git
WORKDIR /vcpkg
RUN ./bootstrap-vcpkg.sh
```

Sometimes it will pass. Sometime it will fail with:
```
[31/77] Building CXX object CMakeFiles/vcpkglib.dir/src/vcpkg/binarycaching.cpp.o                                                                            
FAILED: CMakeFiles/vcpkglib.dir/src/vcpkg/binarycaching.cpp.o                                                                                                
/usr/bin/g++-8  -DVCPKG_DISABLE_METRICS=0 -DVCPKG_USE_STD_FILESYSTEM=1 -I../include -O3 -DNDEBUG   -pthread -std=c++17 -MD -MT CMakeFiles/vcpkglib.dir/src/vc
pkg/binarycaching.cpp.o -MF CMakeFiles/vcpkglib.dir/src/vcpkg/binarycaching.cpp.o.d -o CMakeFiles/vcpkglib.dir/src/vcpkg/binarycaching.cpp.o -c ../src/vcpkg/
binarycaching.cpp                                                                                                                                            
g++-8: fatal error: Killed signal terminated program cc1plus                                                                                                 
compilation terminated. 
```

or with:
```
[67/77] Building CXX object CMakeFiles/vcpkglib.dir/src/vcpkg/export.prefab.cpp.o                                                                            
FAILED: CMakeFiles/vcpkglib.dir/src/vcpkg/export.prefab.cpp.o                                                                                                
/usr/bin/g++-8  -DVCPKG_DISABLE_METRICS=0 -DVCPKG_USE_STD_FILESYSTEM=1 -I../include -O3 -DNDEBUG   -pthread -std=c++17 -MD -MT CMakeFiles/vcpkglib.dir/src/vc
pkg/export.prefab.cpp.o -MF CMakeFiles/vcpkglib.dir/src/vcpkg/export.prefab.cpp.o.d -o CMakeFiles/vcpkglib.dir/src/vcpkg/export.prefab.cpp.o -c ../src/vcpkg/
export.prefab.cpp                                                                                                                                            
g++-8: fatal error: Killed signal terminated program cc1plus                                                                                                 
compilation terminated.
```

or with:
```
[31/77] Building CXX object CMakeFiles/vcpkglib.dir/src/vcpkg/commands.ci.cpp.o
FAILED: CMakeFiles/vcpkglib.dir/src/vcpkg/commands.ci.cpp.o 
/usr/bin/g++-8  -DVCPKG_DISABLE_METRICS=0 -DVCPKG_USE_STD_FILESYSTEM=1 -I../include -O3 -DNDEBUG   -pthread -std=c++17 -MD -MT CMakeFiles/vcpkglib.dir/src/vcpkg/commands.ci.cpp.o -MF CMakeFiles/vcpkglib.dir/src/vcpkg/commands.ci.cpp.o.d -o CMakeFiles/vcpkglib.dir/src/vcpkg/commands.ci.cpp.o -c ../src/vcpkg/commands.ci.cppg++-8: fatal error: Killed signal terminated program cc1plus
compilation terminated.
```

Given the ambiguity of the error messages and my lack of knowledge with some of these tools, I'm having a hard time figuring out what's wrong. Or whether this is a vcpkg bug or something I'm doing. I've built this image several times consecutively; no environment changes took place in between.

**Environment**
- OS:
  - Host: MacOS Catalina 10.15.5
  - Container: Debian 10
- Compiler: g++ (Debian 8.3.0-6) 8.3.0

**To Reproduce**
1. Create Dockerfile as mentioned above
2. run `docker build --no-cache -t vcpkg/example .`
3. Whether it succeeds or fails, run step 2 again.

Would be curious to know if someone can actually reproduce this as I'm not finding anything close in the issues.

**Expected behavior**
Consistent build results.

**Failure logs** 
- failure logs were pasted above

**Comment by jamesalbert** [comment]
Same behavior on ubuntu in docker
```
FROM ubuntu:18.04

RUN apt update
RUN apt install -y build-essential tar curl zip unzip g++ git

RUN git clone https://github.com/microsoft/vcpkg
WORKDIR /vcpkg
RUN ./bootstrap-vcpkg.sh
```

note: changed the dockerfile to further match the getting started page. Same intermittent issues.

**Comment by NancyLi1013** [comment]
I cannot reproduce this on my local machine with Ubuntu 18.04. It might be something related with docker.
@ras0219-msft 

Could you please help take a look?

**Comment by undefinedfunction** [comment]
For anyone running into this error now, check your docker memory limits. I had 2GB RAM assigned in the docker settings (Settings > Resources > Advanced), updated that to 10GB and restarted docker and it worked. 

I was getting this error on any flavour of Debian/Ubuntu I could try but got success on Debian:10 

(OSX 11.2.3, 16gb 2019 MBP)

**Comment by JonLiu1993** [comment]
@jamesalbert ,Could you try @undefinedfunction's suggestion to check your docker memory limits and configure the RAM to be bigger and see if it solves your problem? I don't have a docker test environment to reproduce this problem

**Comment by JackBoosY** [comment]
Now in non-ARM Linux, vcpkg will download binary directly, can you please check whether this issue still exist?

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
