### ISSUE TITLE
How to switch the visual studio version?

### ISSUE THREAD

**Issue by mp5557** [Microsoft/vcpkg#1234]
I have both VS2015 and VS2017. The default VS version of vcpkg is VS2017. Is there any method to switch the VS version of vcpkg? Thanks.

**Comment by Voskrese** [comment]
v140 ?

**Comment by ras0219-msft** [comment]
Hi @mp5557,

Take a look at our triplet documentation: https://vcpkg.readthedocs.io/en/latest/users/triplets/. Basically, you can create a new triplet that has
```cmake
set(VCPKG_PLATFORM_TOOLSET v140)
```
and we'll use VS2015 to build the libraries inside that triplet.

Note that VS2017 and VS2015 are binary compatible, so ideally you shouldn't need to do this, but we definitely have the escape hatch for when things go wrong.

**Comment by magicfoo** [comment]
VS2017 and VS2019 are not: error LNK2001: unresolved external symbol ___CxxFrameHandler4

**Comment by walbourn** [comment]
> VS2017 and VS2019 are not: error LNK2001: unresolved external symbol ___CxxFrameHandler4

VS 2015 Update 3 - VS 2022 *ARE* binary compatible, but specifically you have to LINK with the latest version of the MSVC Runtime. You can use a mix of static C/C++ libraries built with VS 2015 Update 3, VS 2017, VS 2019, and/or VS 2022, but you *must* LINK it with the newest one in the mix (i.e. VS 2022). See [Microsoft Learn](https://learn.microsoft.com/en-us/cpp/porting/binary-compat-2015-2017).

The symbol `___CxxFrameHandler4` was added in Visual Studio 2019 and is related to the new [x64 exception handling implementation](https://devblogs.microsoft.com/cppblog/making-cpp-exception-handling-smaller-x64/). You *can* disable this with ``/d2FH4-``.
