### ISSUE TITLE
Could not find a package configuration file provided by "evpp"

### ISSUE THREAD

**Issue by MCl57** [microsoft/vcpkg#12349]
CMakeLists.txt

**find_package(evpp CONFIG REQUIRED)**

CMake Error at /vcpkg/scripts/buildsystems/vcpkg.cmake:415 (_find_package):
  Could not find a package configuration file provided by "evpp" with any of
  the following names:

    evppConfig.cmake
    evpp-config.cmake

  Add the installation prefix of "evpp" to CMAKE_PREFIX_PATH or set
  "evpp_DIR" to a directory containing one of the above files.  If "evpp"
  provides a separate development package or SDK, be sure it has been
  installed.		

**Host Environment**
- docker ubuntu
- Compiler: 
Microsoft Visual Studio 2019 Version 16.6.3
g++ (Ubuntu 9.3.0-10ubuntu2) 9.3.0

**To Reproduce**
`./vcpkg install evpp`

**file not exist:**
 evpp-config.cmake
 evppConfig.cmake

**Failure logs** 

1> Dateien werden auf den Remotecomputer kopiert.
1> Die CMake-Generierung für die Konfiguration wurde gestartet: "Linux-GCC-Debug".
1> Ausführbare cmake-Datei gefunden unter "/usr/bin/cmake".
1> /usr/bin/cmake -G "Ninja"  -DCMAKE_BUILD_TYPE="Debug"  -DCMAKE_TOOLCHAIN_FILE="/vcpkg/scripts/buildsystems/vcpkg.cmake" -DCMAKE_INSTALL_PREFIX=/projects/Iso-Interface/Linux-GCC-Debug/out/install/ "/projects/Iso-Interface/Iso_Server/CMakeLists.txt";
1> [CMake] CMake Error at /vcpkg/scripts/buildsystems/vcpkg.cmake:415 (_find_package):
1> [CMake]   Could not find a package configuration file provided by "evpp" with any of
1> [CMake]   the following names:
1> [CMake] 
1> [CMake]     evppConfig.cmake
1> [CMake]     evpp-config.cmake
1> [CMake] 
1> [CMake]   Add the installation prefix of "evpp" to CMAKE_PREFIX_PATH or set
1> [CMake]   "evpp_DIR" to a directory containing one of the above files.  If "evpp"
1> [CMake]   provides a separate development package or SDK, be sure it has been
1> [CMake]   installed.
1> [CMake] Call Stack (most recent call first):
1> [CMake]   CMakeLists.txt:21 (find_package)
1> [CMake] -- Configuring incomplete, errors occurred!
1> [CMake] See also "/projects/Iso-Interface/Linux-GCC-Debug/out/build/CMakeFiles/CMakeOutput.log".
1> "cd "/projects/Iso-Interface/Linux-GCC-Debug/out/build";/usr/bin/cmake -G "Ninja"  -DCMAKE_BUILD_TYPE="Debug"  -DCMAKE_TOOLCHAIN_FILE="/vcpkg/scripts/buildsystems/vcpkg.cmake" -DCMAKE_INSTALL_PREFIX=/projects/Iso-Interface/Linux-GCC-Debug/out/install/ "/projects/Iso-Interface/Iso_Server" 2>&1;" wurde mit Exitcode zurückgegeben: 1

**Comment by friendlyanon** [comment]
This is an upstream issue. evpp does not support clients using CMake, because it does not export a CMake package.

As it is right now, you have to manually find the includes, the library files, and guess whether they are shred or static.

Judging by the lack of activity in the upstream repo and the lack of responses to https://github.com/Qihoo360/evpp/issues/280, I doubt this will be fixed, or any other issues for that matter.
