### ISSUE TITLE
[Lua] update to 5.4.0

### ISSUE THREAD

**Issue by TobiasBohnen** [microsoft/vcpkg#12344]
Library name: Lua

New version number: 5.4.0

Website: [lua.org](https://www.lua.org/) 

Source: [5.4.0](https://www.lua.org/ftp/lua-5.4.0.tar.gz) 

Breaking changes: [manual](https://www.lua.org/manual/5.4/manual.html#8)

**Comment by JonLiu1993** [comment]
Relate to [#12403](https://github.com/microsoft/vcpkg/pull/12403)
