### ISSUE TITLE
[Feature] Default to x64-windows triplet on x64 Windows

### ISSUE THREAD

**Issue by VelocityRa** [microsoft/vcpkg#12357]
Most people don't use 32-bit builds these days, so we have to always specify the triplet which is cumbersome, or set the env-var which is not elegant.

### Implementation
Instead of this:
https://github.com/microsoft/vcpkg/blob/22c8e3a23afc6be45020cd3f8c92bcea783ce8fa/toolsrc/src/vcpkg/triplet.cpp#L100
there should be a check to see if the host is 64-bit and use the `x64-windows` triplet if so.

`IsWow64Process` or `IsWow64Process2` can be used for this (will work even if vcpkg is compiled as 32-bit).

**Comment by PhoebeHui** [comment]
Duplicated to issue https://github.com/microsoft/vcpkg/issues/1254 

Related PR https://github.com/microsoft/vcpkg/pull/11610

**Comment by cloudhan** [comment]
if I have commit permission, I will change
https://github.com/microsoft/vcpkg/blob/22c8e3a23afc6be45020cd3f8c92bcea783ce8fa/toolsrc/src/vcpkg/triplet.cpp#L99-L100
to
```cpp
#if defined(_WIN64)
                return Triplet::X64_WINDOWS;
#elif defined(_WIN32)
                return Triplet::X86_WINDOWS;
```
right now and force push it...

See how many thumb ups in #1254

**Comment by VelocityRa** [comment]
@cloudhan This is wrong, `_WIN64` will only check if vcpkg is compiled in a 64-bit environment, not if the host is a 64-bit operating system. If vcpkg itself was compiled as 32-bit on a 64-bit system it wouldn't work.

See my implementation recommendation above instead.

**Comment by cloudhan** [comment]
@VelocityRa Good point, and seems the bootstrap script indeed build 32bit version of vcpkg.exe on a 64bit platform. Another feature request, here you go.

**Comment by MarkIngramUK** [comment]
This has just caught me out on a fresh install (again). 64-bit by default on 64-bit machines seems like a sensible choice.
