### ISSUE TITLE
Network paths may contain "$" on Windows

### ISSUE THREAD

**Issue by vkapartzianis** [microsoft/vcpkg#12356]
****

**Is your feature request related to a problem? Please describe.**
I tried to use vcpkg on a network drive, `U` which expanded to `//subdomain1.domain1.com/subdomain2.domain2.com$/user/` in cmake files. This subsequently caused ninja to fail, with "literal $ must be written as $$". 

**Proposed solution**
I guess the expanded path to cmake should have all "$" characters replaced with "$$".

**Describe alternatives you've considered**
I had to use vcpkg from a local drive which is far from ideal in my situation. Many enterprise environments use local disks with very limited space and require users to store their documents in a network drive.

**Additional context**
More details are provided in issue #12353

**Comment by Neumann-A** [comment]
Since the path will be anyway to long for most build-systems (if you did not activate long paths on windows) you could try to use `subst` to substitute your network path to a drive letter directly instead.

**Comment by vkapartzianis** [comment]
@Neumann-A I'm not sure what you mean. I use the network drive, not any network path. It's vcpkg that expands the drive to the full path.

**Comment by Neumann-A** [comment]
In a cmd line I mean something like:
`subst V: //subdomain1.domain1.com/subdomain2.domain2.com$/user/`
or
`subst V: U:/`
and then run vcpkg from `V:`.
This should not expand the network drive.

**Comment by JackBoosY** [comment]
@ras0219 @ras0219-msft Could you please take a look?

Thanks.

**Comment by JackBoosY** [comment]
Hi @vkapartzianis, does this issue still exist?

**Comment by vkapartzianis** [comment]
@JackBoosY How can I check? I moved vcpkg to a local disk as it was entirely unusable on the network drive.

**Comment by JackBoosY** [comment]
@vkapartzianis If this issue exists, please reopen this issue.
