### ISSUE TITLE
[Feature] Prefer static builds (not enforce)

### ISSUE THREAD

**Issue by VelocityRa** [microsoft/vcpkg#12358]
Most libraries in my manifest can be compiled statically which I would prefer. Some don't support this, however.
Using a `static` triplet, I get errors because of the few that don't support it.

Is there a way to use static builds for only every library that supports it?
There's [not much reason](https://drewdevault.com/dynlib.html) to use dynamic libraries, as far as I know.
It should always preferred anyway (by default), which doesn't seem to be the case currently.

**Comment by JackBoosY** [comment]
For some reason we met, in non-Windows, we use static as the default triplet, because if you want to use a dynamic library, you need to add the installation path of the library to ldconfig.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
