### ISSUE TITLE
vcpkg manifest mode cannot bootstrap non-x64 Linux

### ISSUE THREAD

**Issue by linquize** [microsoft/vcpkg#12362]
In vcpkg **manifest mode**,
`vcpkg.cmake` will call `bootstrap-vcpkg.sh` to build `vcpkg` executable if not yet.
On Linux, `bootstrap.sh` will always download Linux x64 `cmake` and `ninja` binaries, so they won't run on non-x64 platforms, such as ARM.
In such case, user can install the correct architecture of `cmake` and `ninja` by himself, and then pass `-useSystemBinaries` flag to `bootstrap-vcpkg.sh`.
But in manifest mode, extra flags cannot be passed to `bootstrap-vcpkg.sh`.

I suggest to support `VCPKG_FORCE_SYSTEM_BINARIES` environment variable in `bootstrap.sh` as well, as an alternative to `-useSystemBinaries`. 
Similarly, `VCPKG_DISABLE_METRICS` vs `-disableMetrics`

**Comment by JackBoosY** [comment]
@strega-nil Could you please take a look?

Thanks.

**Comment by linquize** [comment]
Neither non-x64 Linux nor **Alpine x64** work, because Alpine C library is musl

**Comment by strega-nil** [comment]
Yeah, it's likely that we need to do a more complete rewrite. This will be solved before we stabilize manifests; until that point, you're going to have to, unfortunately, run the bootstrap script yourself.

**Comment by linquize** [comment]
It is easy to implement `VCPKG_FORCE_SYSTEM_BINARIES=1` in `bootstrap.sh`
so that user can set once for both bootstrap and `vcpkg install`

**Comment by strega-nil** [comment]
@linquize fair enough; do you want to write that?

**Comment by linquize** [comment]
You write

**Comment by linquize** [comment]
ARM64 OK

**Comment by JackBoosY** [comment]
Okay, please reopen this issue if you meet it again.
