### ISSUE TITLE
broken link to readthedocs

### ISSUE THREAD

**Issue by fellmad** [Microsoft/vcpkg#1237]
on this page https://github.com/Microsoft/vcpkg

this link fails: https://github.com/Microsoft/vcpkg/blob/master

here:
Our docs are now also available online at ReadTheDocs: https://vcpkg.readthedocs.io/!

**Comment by alexkaratarakis** [comment]
Thanks for the quick catch! Should be fixed now.

**Comment by fellmad** [comment]
"you are a good person."

😘
