### ISSUE TITLE
[freetype] compiling with brotli support for woff2 and linking

### ISSUE THREAD

**Issue by kevinlul** [microsoft/vcpkg#12380]
****

**Is your feature request related to a problem? Please describe.**
With the freetype 2.10.2 update merged in #11846, support for [WOFF 2 fonts](https://sourceforge.net/projects/freetype/files/freetype2/2.10.2/) was added but not accounted for when I updated the port. Thus, depending on whether brotli is already installed, it might be detected, support compiled, and linked in. The vcpkg brotli port does not export the library as `BrotliDec` like freetype expects, but as [`unofficial::brotli::brotli-SOMETHING`](https://github.com/microsoft/vcpkg/blob/master/ports/brotli/vcpkg-cmake-wrapper.cmake), and I'm not sure why it's configured in this way.

**Proposed solution**
Add an optional feature `brotli` to control `FT_WITH_BROTLI` and `CMAKE_DISABLE_FIND_PACKAGE_BrotliDec`. Then either freetype must be patched to use the unofficial vcpkg CMake module names for brotli, or the unofficial CMake module names for brotli should be removed in favour of the official ones. I'm not sure why the unofficial names were added in the first place two years ago 33286f90044465a11c2fc7e7a7d4b790c757bc01.

**Describe alternatives you've considered**
Disable brotli support entirely like with HarfBuzz. Doesn't seem like a good idea to throw out an entire feature.

**Additional context**
I think #9838 might be related with the brotli CMake module names.

**Comment by Neumann-A** [comment]
Hmm i actually touched this issue in #11776. The problem is that the pkgconfig file for brotli is incorrect which is why it is not found by freetype. freetype itself uses a FindBrotliDec module which internally uses FindPkgConfig for brotli.
