### ISSUE TITLE
[vcpkg_configure_make] Add mingw support

### ISSUE THREAD

**Issue by longnguyen2004** [microsoft/vcpkg#12385]
****

**Is your feature request related to a problem? Please describe.**
Currently, `vcpkg_configure_make` assumes that MSVC is the compiler used. This is however not true anymore since we now have community support for `mingw`. I tried modifying it but soon gave up due to the complexity. If someone can steps up or at least guides me through the process, I'd appreciate it.

**Comment by Neumann-A** [comment]
the trick is probably to replace all `if(VCPKG_TARGET_IS_WINDOWS) `with `if(VCPKG_TARGET_IS_WINDOWS AND NOT VCPKG_TARGET_IS_MINGW)` since in mingw `vcpkg_configure_make` can probably just take the linux path.

**Comment by longnguyen2004** [comment]
Alright I'll take a look

**Comment by matwey** [comment]
> the trick is probably to replace all `if(VCPKG_TARGET_IS_WINDOWS) `with `if(VCPKG_TARGET_IS_WINDOWS AND NOT VCPKG_TARGET_IS_MINGW)` since in mingw `vcpkg_configure_make` can probably just take the linux path.

No, It can't currently. `vcpkg_configure_make` hardcodes Visual Studio compiler into `CXX` env at Windows system.

**Comment by longnguyen2004** [comment]
I just noticed @Neumann-A's excellent PR #12936 which removed the hardcoded `cl.exe` and now x264 builds with x64-mingw-dynamic with some fixes. Thank you for the help, I'll make a PR for the fixes later.

**Comment by longnguyen2004** [comment]
Closing this since `vcpkg_configure_make` now works like intended.
