### ISSUE TITLE
[libepoxy] build failure

### ISSUE THREAD

**Issue by W-Binglong** [microsoft/vcpkg#12382]
**Host Environment**
- OS: [ Windows 10]
- Compiler: VS 2019

**To Reproduce**
`./vcpkg install libepoxy `

**Failure logs** 
-PS C:\Users\王炳龙> vcpkg install libepoxy
Computing installation plan...
The following packages will be built and installed:
    libepoxy[core]:x86-windows
Starting package 1/1: libepoxy:x86-windows
Building package libepoxy[core]:x86-windows...
-- Using cached E:/vcpkg-master/downloads/anholt-libepoxy-1.5.4.tar.gz
-- Cleaning sources at E:/vcpkg-master/buildtrees/libepoxy/src/1.5.4-337c486045.clean. Pass --editable to vcpkg to reuse sources.
-- Extracting source E:/vcpkg-master/downloads/anholt-libepoxy-1.5.4.tar.gz
-- Applying patch libepoxy-1.5.4_Add_call_convention_to_mock_function.patch
-- Using source at E:/vcpkg-master/buildtrees/libepoxy/src/1.5.4-337c486045.clean
-- Acquiring MSYS Packages...
-- Acquiring MSYS Packages... OK
-- Configuring x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: E:/vcpkg-master/downloads/tools/python/python-3.8.3-x86/python.exe E:/vcpkg-master/downloads/tools/meson/meson-0.54.2/meson.py -Denable-glx=no -Denable-egl=no -Dcmake_prefix_path=['E:/vcpkg-master/installed/x86-windows','E:/vcpkg-master/installed/x86-windows/share'] --buildtype plain --backend ninja --wrap-mode nodownload --default-library shared --libdir lib --prefix E:/vcpkg-master/packages/libepoxy_x86-windows/debug --includedir ../include E:/vcpkg-master/buildtrees/libepoxy/src/1.5.4-337c486045.clean -Dc_args=['/nologo','/DWIN32','/D_WINDOWS','/W3','/MP','/D_DEBUG','/MDd','/Z7','/Ob0','/Od','/RTC1'] -Dcpp_args=['/nologo','/DWIN32','/D_WINDOWS','/W3','/GR','/EHsc','/MP','/D_DEBUG','/MDd','/Z7','/Ob0','/Od','/RTC1'] -Dc_link_args=[] -Dcpp_link_args=[]
    Working Directory: E:/vcpkg-master/buildtrees/libepoxy/x86-windows-dbg
    Error code: 2
    See logs for more information:
      E:\vcpkg-master\buildtrees\libepoxy\config-x86-windows-dbg-out.log
      E:\vcpkg-master\buildtrees\libepoxy\config-x86-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_meson.cmake:161 (vcpkg_execute_required_process)
  ports/libepoxy/portfile.cmake:16 (vcpkg_configure_meson)
  scripts/ports.cmake:76 (include)

Error: Building package libepoxy:x86-windows failed with: BUILD_FAILED

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.
[config-x86-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/4907831/config-x86-windows-dbg-err.log)
[config-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/4912637/config-x86-windows-dbg-out.log)

**Comment by W-Binglong** [comment]
[Uploading config-x86-windows-dbg-out.log…]()

**Comment by NancyLi1013** [comment]
Hi @W-Binglong 
Thanks for posting this issue.

`UnicodeDecodeError: 'gbk' codec can't decode byte 0x84 in position 335288: illegal multibyte sequence`

It's duplicated to #11525.
