### ISSUE TITLE
bootstrap-vcpkg.sh failure with G++ 6.3.0

### ISSUE THREAD

**Issue by Pospelove** [microsoft/vcpkg#12381]
**Describe the bug**
Vcpkg bootstrap fails with compilation errors (see logs).

**Environment**
- OS: Ubuntu 18.0
- Compiler: G++ 6.3.0

**Reproducing**
Build this commit or newer e62d1361288e83eba786395b60361ab35ba83800.
Older versions of vcpkg are built successfully.

**Expected behavior**
Vcpkg builds successfully.

**Failure logs** 
[logs_full.txt](https://github.com/microsoft/vcpkg/files/4907719/logs_full.txt)

**Comment by linquize** [comment]
The build fails with `g++-6`
Why do you use `g++-6` in **Ubuntu 18.04**?
**Ubuntu 18.04** comes with `g++-7` by default.

**Comment by Pospelove** [comment]
Why shouldn't I? 
According to readme:
```
Prerequisites for Linux:

Git
g++ >= 6
```

So if it is not expected to build on g++ 6, readme should be updated.

**Comment by lebdron** [comment]
Seems to be fixed in https://github.com/microsoft/vcpkg/pull/12950 , should the issue be closed?

**Comment by Pospelove** [comment]
I think there is no real need to test this so closing this for now.
