### ISSUE TITLE
[LICENSE_1_0.txt download] Error: Building package boost-compatibility:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by wenjie89** [microsoft/vcpkg#12383]
**Host Environment**
- OS: [Windows 10]
- Compiler: revision 

**To Reproduce**
`./vcpkg install pcl`

**Failure logs** 
C:\scr\vcpkg>vcpkg install pcl
Computing installation plan...
Additional packages (*) will be modified to complete this operation.
Starting package 1/122: boost-compatibility:x86-windows
Building package boost-compatibility[core]:x86-windows...
-- Using cached C:/scr/vcpkg/downloads/boostorg-compatibility-boost-1.73.0.tar.gz
-- Cleaning sources at C:/scr/vcpkg/buildtrees/boost-compatibility/src/ost-1.73.0-44642da97c.clean. Pass --editable to vcpkg to reuse sources.
-- Extracting source C:/scr/vcpkg/downloads/boostorg-compatibility-boost-1.73.0.tar.gz
-- Using source at C:/scr/vcpkg/buildtrees/boost-compatibility/src/ost-1.73.0-44642da97c.clean
-- Packaging headers
-- Packaging headers done
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.73.0/LICENSE_1_0.txt...
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.73.0/LICENSE_1_0.txt... Failed. Status: 6;"Couldn't resolve host name"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:176 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  installed/x86-windows/share/boost-vcpkg-helpers/boost-modular-headers.cmake:17 (vcpkg_download_distfile)
  ports/boost-compatibility/portfile.cmake:12 (boost_modular_headers)
  scripts/ports.cmake:76 (include)

Error: Building package boost-compatibility:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-compatibility:x86-windows
  Vcpkg version: 2020.06.15-nohash

**Additional context**
From the log it's obvious that  the file with the address"https://raw.githubusercontent.com/boostorg/boost/boost-1.73.0/LICENSE_1_0.txt" cannot be downloaded and it should be the reason for the building failure. I tried to copy and paste the link directly in chrome, but I just got the message "This site can’t be reached". So, how can I get the file LICENSE_1_0.txt?

**Comment by c72578** [comment]
Problems when downloading the `LICENSE_1_0.txt` file have already been reported multiple times:
https://github.com/microsoft/vcpkg/issues/11627
https://github.com/microsoft/vcpkg/issues/11902
https://github.com/microsoft/vcpkg/issues/12266

Possible solutions are:
- Set the HTTPS_PROXY and HTTP_PROXY environment (see https://github.com/microsoft/vcpkg/issues/11627#issuecomment-642356801)
- Change DNS server (see https://github.com/microsoft/vcpkg/issues/12266#issuecomment-653856357)
- Get the `LICENSE_1_0.txt` file (also attached here), rename it and put it in the download folder as described here: https://github.com/microsoft/vcpkg/issues/11627#issuecomment-637183269

File:
[LICENSE_1_0.txt](https://github.com/microsoft/vcpkg/files/4908061/LICENSE_1_0.txt)

**Comment by wenjie89** [comment]
Thank you for your quick response. I downloaded the license file you attached here and put it in the "download" folder after rename it. Then I tried the command "vcpkg install boost-compatibility:x86-windows".  But the same error message pops up. It seems that it will automatically try to download the license file from the link even if the license file is alread in the folder. I tried to switch my vpn off and implement the line again, but I still got the same error message. Something different from before is that I copy and paste the link for the license file and it can display normally in chrome. I really don't know how to set the proxy. 
The VPN/VPS I use are SSR (with SSTAP) and trojan client. There are no such  settings in the panel.

**Comment by timautry** [comment]
The file should be found in the `<vcpkg-root>\download\` folder/directory and named `boost_LICENSE_1_0.txt`.

Attached is a copy from my system...
[boost_LICENSE_1_0.txt](https://github.com/microsoft/vcpkg/files/4909925/boost_LICENSE_1_0.txt)

**Comment by PhoebeHui** [comment]
@wenjie89, you can also download the file from https://raw.githubusercontent.com/boostorg/boost/boost-1.73.0/LICENSE_1_0.txt.

**Comment by wenjie89** [comment]
The problem I meantioned previously is fixed following the solution from ghost. However, a new issue happens:

-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.73.0/boostcpp.jam...
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.73.0/boostcpp.jam... Failed. Status: 6;"Couldn't resolve host name"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:176 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  ports/boost-build/portfile.cmake:27 (vcpkg_download_distfile)
  scripts/ports.cmake:76 (include)


Error: Building package boost-build:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-build:x86-windows
  Vcpkg version: 2020.06.15-nohash

**Comment by wenjie89** [comment]
I was wondering if there is a way to fix the problem of proxy so that it can download everything automatically?

**Comment by PhoebeHui** [comment]
@wenjie89, you can reference https://github.com/microsoft/vcpkg/issues/7207#issuecomment-545826376 for setting proxy.

**Comment by PhoebeHui** [comment]
@wenjie89, unzip the below file and put it to downloads folder should work, please have a try and reopen this issue if it still be a problem for you.

[boost_LICENSE_1_0.zip](https://github.com/microsoft/vcpkg/files/4985749/boost_LICENSE_1_0.zip)

**Comment by 13798209854** [comment]
> The file should be found in the `<vcpkg-root>\downloads\` folder/directory and named `boost_LICENSE_1_0.txt`.
> 
> Attached is a copy from my system...
> [boost_LICENSE_1_0.txt](https://github.com/microsoft/vcpkg/files/4909925/boost_LICENSE_1_0.txt)
