### ISSUE TITLE
Build Error: Paho-MQTT

### ISSUE THREAD

**Issue by jmin911** [Microsoft/vcpkg#1238]
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:43 (message):
    Command failed: C:/Program Files/CMake/bin/cmake.exe;C:/src/vcpkg/buildtrees/paho-mqtt/src/paho.mqtt.c-1.1.0;-DPAHO_
WITH_SSL=TRUE;-DBUILD_SHARED_LIBS=OFF;-DVCPKG_TARGET_TRIPLET=x86-windows-static;-DCMAKE_CXX_FLAGS= /DWIN32 /D_WINDOWS /W
3 /utf-8 /GR /EHsc /MP ;-DCMAKE_C_FLAGS= /DWIN32 /D_WINDOWS /W3 /utf-8 /MP ;-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON;-DCMAK
E_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON;-DCMAKE_INSTALL_SYSTEM_RUNTIME_
LIBS_SKIP=TRUE;-DCMAKE_VERBOSE_MAKEFILE=ON;-DVCPKG_APPLOCAL_DEPS=OFF;-DCMAKE_TOOLCHAIN_FILE=C:/src/vcpkg/scripts/buildsy
stems/vcpkg.cmake;-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON;-DCMAKE_CXX_FLAGS_RELEASE=/MT /O2 /Oi /Gy /DNDEBUG /Z
i ;-DCMAKE_C_FLAGS_RELEASE=/MT /O2 /Oi /Gy /DNDEBUG /Zi ;-DCMAKE_SHARED_LINKER_FLAGS_RELEASE=/DEBUG /INCREMENTAL:NO /OPT
:REF /OPT:ICF ;-DCMAKE_EXE_LINKER_FLAGS_RELEASE=/DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF ;-G;Visual Studio 14 2015;-DCMA
KE_BUILD_TYPE=Release;-DCMAKE_INSTALL_PREFIX=C:/src/vcpkg/packages/paho-mqtt_x86-windows-static
    Working Directory: C:/src/vcpkg/buildtrees/paho-mqtt/x86-windows-static-rel
    See logs for more information:
      C:\src\vcpkg\buildtrees\paho-mqtt\config-x86-windows-static-rel-out.log
      C:\src\vcpkg\buildtrees\paho-mqtt\config-x86-windows-static-rel-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:170 (vcpkg_execute_required_process)
  ports/paho-mqtt/portfile.cmake:12 (vcpkg_configure_cmake)
  scripts/ports.cmake:73 (include)

Error: Building package paho-mqtt:x86-windows-static failed with: BUILD_FAILED

err.log:
CMake Error at CMakeLists.txt:29 (STRING):
  string sub-command STRIP requires two arguments.

**Comment by ras0219-msft** [comment]
@atkawa7 Could you take a look at this?

**Comment by atkawa7** [comment]
@ras0219-msft @jmin911 Thank you. There is problem with cmake with the latest version. It was fixed in this [build-cmake-fix-windows pull request](https://github.com/eclipse/paho.mqtt.c/commit/16cfc0cc054f9dd1a6e08b2598f5bbb3d3b01e2f). However they haven't released new versions. Can you please try with --head to install from the master.

**Comment by JackBoosY** [comment]
Hi @jmin911 , thanks for reporting this issue!
Please open a new issue if this is still a problem for you.
Thx.
