### ISSUE TITLE
[tesseract4.1.1]  Build Error Type Of Library

### ISSUE THREAD

**Issue by singlebear** [microsoft/vcpkg#12391]
**Host Environment**
- OS: [e.g. Windows/Linux etc...] WIN10
- Compiler:VS2017+ vcpkg 2020.06

**To Reproduce**
     When use the order " .\vcpkg.exe install tesseract:x64-windows",it  should build dynamic libraries.But eventually it built a static library of tesseract.However, Other dependent libraries are normally compiled into dynamic libraries.
     vcpkg-2020.06\installed\x64-windows\lib\tesseract41.lib---174MB + no tesseract41.dll  。
     Use the traditional method cmake+VS2017，get tesseract41.lib---2.67mb + tesseract41.dll 3.00mb
**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by linquize** [comment]
What do you mean by your **traditional method** and your new method?

**Comment by singlebear** [comment]
> What do you mean by your **traditional method** and your new method?
I'm not very good at English, so The expression may not be very accurate.*traditional method* means not use VCPKG，use only the  cmake+VS2017.
1、Download the source code.
2、Set the config and generate .sln by Cmake.exe 
3、Compile dynamic library By VS2017

**Comment by LilyWangL** [comment]
Thanks for posting this issue. `tesseract` is a only static library, it has this command `vcpkg_check_linkage(ONLY_STATIC_LIBRARY)` in its portfile.cmake.

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
