### ISSUE TITLE
vcpkg install atkmm error

### ISSUE THREAD

**Issue by GordonGgx** [microsoft/vcpkg#12390]
Computing installation plan...
The following packages will be built and installed:
    atkmm[core]:x64-linux
Starting package 1/1: atkmm:x64-linux
Building package atkmm[core]:x64-linux...
-- Note: atkmm only supports dynamic library linkage. Building dynamic library.
-- Using cached /home/ggx/Documents/vcpkg/downloads/atkmm-2.24.2.tar.xz
-- Cleaning sources at /home/ggx/Documents/vcpkg/buildtrees/atkmm/src/atkmm-2-de808b48b0.clean. Pass --editable to vcpkg to reuse sources.
-- Extracting source /home/ggx/Documents/vcpkg/downloads/atkmm-2.24.2.tar.xz
-- Applying patch fix_properties.patch
-- Applying patch fix_charset.patch
-- Using source at /home/ggx/Documents/vcpkg/buildtrees/atkmm/src/atkmm-2-de808b48b0.clean
-- Building /home/ggx/Documents/vcpkg/buildtrees/atkmm/src/atkmm-2-de808b48b0.clean/MSVC_Net2013/atkmm.sln for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: msbuild /home/ggx/Documents/vcpkg/buildtrees/atkmm/src/atkmm-2-de808b48b0.clean/MSVC_Net2013/atkmm.sln /p:Configuration=Release /t:atkmm /p:Platform=x64 /p:PlatformToolset=external /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /p:WindowsTargetPlatformVersion= /p:VcpkgManifestInstall=false /m /p:ForceImportBeforeCppTargets=/home/ggx/Documents/vcpkg/scripts/buildsystems/msbuild/vcpkg.targets /p:VcpkgTriplet=x64-linux /p:VcpkgCurrentInstalledDir=/home/ggx/Documents/vcpkg/installed/x64-linux
    Working Directory: /home/ggx/Documents/vcpkg/buildtrees/atkmm/x64-linux-rel
    Error code: No such file or directory
    See logs for more information:

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_msbuild.cmake:121 (vcpkg_execute_required_process)
  ports/atkmm/portfile.cmake:25 (vcpkg_build_msbuild)
  scripts/ports.cmake:76 (include)

Error: Building package atkmm:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: atkmm:x64-linux
  Vcpkg version: 2020.06.15-unknownhash

Additionally, attach any relevant sections from the log files above.

**Comment by GordonGgx** [comment]
> /p:WindowsTargetPlatformVersion= ... ?

How to set this property?I use vcpak on Linux

**Comment by Voskrese** [comment]
**Command failed:** `msbuild`
`
 Command failed: msbuild /home/ggx/Documents/vcpkg/buildtrees/atkmm/src/atkmm-2-de808b48b0.clean/MSVC_Net2013/atkmm.sln /p:Configuration=Release /t:atkmm /p:Platform=x64 /p:PlatformToolset=external /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /p:WindowsTargetPlatformVersion= /p:VcpkgManifestInstall=false /m /p:ForceImportBeforeCppTargets=/home/ggx/Documents/vcpkg/scripts/buildsystems/msbuild/vcpkg.targets /p:VcpkgTriplet=x64-linux /p:VcpkgCurrentInstalledDir=/home/ggx/Documents/vcpkg/installed/x64-linux`

**Comment by GordonGgx** [comment]
> **Command failed:** `msbuild`
> 
> ` Command failed: msbuild /home/ggx/Documents/vcpkg/buildtrees/atkmm/src/atkmm-2-de808b48b0.clean/MSVC_Net2013/atkmm.sln /p:Configuration=Release /t:atkmm /p:Platform=x64 /p:PlatformToolset=external /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /p:WindowsTargetPlatformVersion= /p:VcpkgManifestInstall=false /m /p:ForceImportBeforeCppTargets=/home/ggx/Documents/vcpkg/scripts/buildsystems/msbuild/vcpkg.targets /p:VcpkgTriplet=x64-linux /p:VcpkgCurrentInstalledDir=/home/ggx/Documents/vcpkg/installed/x64-linux`
> 
> > maybe this means that there is no support for *UNIX

I’m found this error:
Working Directory: /home/ggx/Documents/vcpkg/buildtrees/atkmm/x64-linux-rel
    Error code: No such file or directory

**Comment by Voskrese** [comment]
)))

`which msbuild` ?
`locate msbuild` ?

mono ?

**Comment by GordonGgx** [comment]
> )))
> 
> `which msbuild` ?
> `locate msbuild` ?
> 
> mono ?

Ok. I'll try to install it

**Comment by Voskrese** [comment]
> Ok. I'll try to install it

do not )) there is no support in VCPKG for building the atkmm package on *UNIX

crossplatform ?

**Comment by GordonGgx** [comment]
> do not )) there is no support in VCPKG for building the atkmm package on *UNIX
> 
> crossplatform

Well, I can only use apt to install it.

**Comment by PhoebeHui** [comment]
Confirmed, it only supports windows now.
