### ISSUE TITLE
[curl:x64-windows-static] build failure

### ISSUE THREAD

**Issue by JasonYang-MSFT** [microsoft/vcpkg#12397]
**Host Environment**
  Package: curl:x64-windows-static
  Vcpkg version: 2020.06.15-nohash

**To Reproduce**
`.\vcpkg install curl[winssl]`

**Failure logs** 
The following packages will be built and installed:
    curl[core,non-http,ssl,sspi,winssl]:x64-windows-static
Starting package 1/1: curl:x64-windows-static
Building package curl[core,non-http,ssl,sspi,winssl]:x64-windows-static...
-- Downloading https://github.com/curl/curl/archive/5a1fc8d33808d7b22f57bdf9403cda7ff07b0670.tar.gz...
-- Downloading https://github.com/curl/curl/archive/5a1fc8d33808d7b22f57bdf9403cda7ff07b0670.tar.gz... Failed. Status: 22;"HTTP response code said error"

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by tan-wei** [comment]
Downloading fails? Maybe you should try it again or use a proxy instead.

**Comment by JackBoosY** [comment]
`500: Internal Server Error` Seems the source was removed.

**Comment by JackBoosY** [comment]
For workaround, please download [this](https://github.com/microsoft/vcpkg/files/4910845/curl-curl-curl-7_68_0.tar.gz) and put it into _VCPKG_PATH/downloads_, then rebuild curl.

**Comment by JackBoosY** [comment]
Looks like a issue on github.

**Comment by JackBoosY** [comment]
Should be okay now.
