### ISSUE TITLE
Document the workflow for edit / compile / test of a port within a larger project

### ISSUE THREAD

**Issue by JoshuaRowePhantom** [microsoft/vcpkg#12402]
****

I am doing development on a larger project, and I've discovered a bug in a dependency that is managed by vcpkg.  Ideally, I could easily edit the code locally, recompile by larger project, and test that the fix works in the context of the larger project, while also being able to go back and contribute the fix upstream.  IMHO, the bigger value of vcpkg is in the standardization of ports' specifications of CMakeLists, not the downloading of the sources (that are by-and-large git repositories anyway), though other people disagree I am sure.  

This has a number of ramifications and questions.  A definitive description of the above workflow would be helpful.  The vcpkg system of download snapshots of build sources that are already git-based might be better implemented as git clone operations, so that e.g. choosing to do local development doesn't necessary require a step outside of vcpkg, followed by steps in vcpkg, followed by steps in the target project.  For git projects, copying the port CMakeLists.txt file into the repository is even more natural with a separate branch.

I have considered the three-phase solution of working on the fix external to vcpkg, forking vcpkg and re-pointing it at my source, and rerunning vcpkg to update the sources, then rebuilding my project.  If we're living in a build-from-source world, I feel like I should just be able to rebuild my project from the top level to get the updated dependency's sources.

**Comment by JackBoosY** [comment]
@JoshuaRowePhantom Thanks for your suggestions!
@ras0219-msft @ras0219 Could you please take a look?

Thanks.

**Comment by LilyWangLL** [comment]
Ping @ras0219-msft, could you help take a look this issue?

**Comment by Adela0814** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen this issue.
