### ISSUE TITLE
TabLib wants CreateFile2 function

### ISSUE THREAD

**Issue by evpobr** [Microsoft/vcpkg#1240]
Win7 64-bit, Visual Studio 2017. TagLib installed with command:

```
./vcpkg install taglib:x64-windows-static
```

When using TagLib in VC2017 project errors happens:
```
The procedure entry point CreateFile2 could not be located in the dynamic link library KERNEL32.dll."
```

This is Windows 8 and higher function, not suppotred even under Win7.

The only reference to `CreateFile2` is in `tfilestream.cpp`:

```cpp
#if defined(_WIN32_WINNT) && (_WIN32_WINNT >= 0x0602)
    return CreateFile2(path.wstr().c_str(), access, FILE_SHARE_READ, OPEN_EXISTING, NULL);
#else
    return CreateFileW(path.wstr().c_str(), access, FILE_SHARE_READ, NULL, OPEN_EXISTING, 0, NULL);
#endif
```

if `_WIN32_WINNT` is not directly, WinSDK defines it to maximum value.

The solution is to set `_WIN32_WINNT` to value lower then `0x600` value when configuring.

**Comment by Voskrese** [comment]
если поможет, то наверно надо так

> If it helps, you probably need something like this

https://msdn.microsoft.com/en-us/library/6sehtctf.aspx

**Comment by zabulus** [comment]
Looks like we have a new pivot for triplets over here :)

**Comment by evpobr** [comment]
@zabulus, what do you mean? The source was this [article](https://blogs.msdn.microsoft.com/vcblog/2016/11/01/vcpkg-updates-static-linking-is-now-available/).

**Comment by evpobr** [comment]
I guess i can fix it.
