### ISSUE TITLE
[vcpkg] no longer putting downloads in <vcpkg-root>\downloads - ignoring VCPKG_DOWNLOADS environment variable, putting downloaded files in %LOCALAPPDATA%\vcpkg\archives

### ISSUE THREAD

**Issue by timautry** [microsoft/vcpkg#12411]
**Describe the bug**
[vcpkg] no longer putting downloads in `<vcpkg-root>\downloads` - ignoring no longer honoring VCPKG_DOWNLOADS environment variable, putting downloaded files in `%LOCALAPPDATA%\vcpkg\archives`, filling up USER PROFILE/SYSTEM Disk with downloads.

**Update** 
also includes OpenSUSE Linux 15.x on WSL2 and Hyper-V VM - putting downloaded files in `~/.cache/vcpkg/archives` install, exhausting space on `/home` mount point....

**Environment**
- OS: 
   - [Microsoft Windows [Version 10.0.19041.331]]
   - [OpenSUSE Linux 15.x]
 
- Compiler: 
   - Visual Studio 2017 Version: 15.9.24  VS Tools Version: 14.16.27023 
   - Visual Studio 2019 Version: 16.6.3  VS Tools Version: 14.26.28801
   - gcc 9.2.1

**To Reproduce**
1. ./vcpkg install xxxx -or- ./vcpkg upgrade --no-dry-run
2. No Errors 

**Expected behavior**
vcpkg should follow set environment variables and use previously downloaded packages at `<vcpkg-root>\downloads` and/or use directory/folder specified in VCPKG_DOWNLOADS environment variable.

**Failure logs** 
- No failures unless stating vcpkg not using downloads folder/directory and/or not using VCPKG_DOWNLOADS environment settings
- See attached log of `vcpkg upgrade --no-dry-run` showing ports deleted and to be reinstalled but is downloading to %LOCALAPPDATA%\vcpkg\archives in the user profile using unnecessary space on the system drive.
[vcpkg-upgrade-2019.prod-no-dry-run.log](https://github.com/microsoft/vcpkg/files/4915577/vcpkg-upgrade-2019.prod-no-dry-run.log)

**Additional context**
@ras0219-msft @BillyONeal @strega-nil @JackBoosY @Voskrese @Neumann-A 
- Please advise why the sudden expected behavior change in vcpkg?
- I find nothing on https://vcpkg.readthedocs.io/en/latest/ denoting this change of direction for local installation of vcpkg.
- This is very discouraging for me to continue using this product as this change is apparently undocumented and has had detrimental consequences...
- I have a Windows machine with WSL2 and Hyper-V all out of commission and will need to recover all from backup as it has corrupted then /home on Linux and /user profile /system drive on Windows.

**Comment by timautry** [comment]
No updated documentation here either:
https://docs.microsoft.com/en-us/cpp/build/vcpkg?view=vs-2019 as it reads:

The vcpkg folder hierarchy
All vcpkg functionality and data is self-contained in a single directory hierarchy, called an "instance". There are no registry settings or environment variables. You can have any number of instances of vcpkg on a machine, and they won't interfere with each other.

The contents of a vcpkg instance are:

buildtrees - contains subfolders of sources from which each library is built
docs - documentation and examples
downloads - cached copies of any downloaded tools or sources. vcpkg searches here first when you run the install command.
installed - Contains the headers and binaries for each installed library. When you integrate with Visual Studio, you're essentially telling it add this folder to its search paths.
packages - Internal folder for staging between installs.
ports - Files that describe each library in the catalog, its version, and where to download it. You can add your own ports if needed.
scripts - Scripts (CMake, PowerShell) used by vcpkg.
toolsrc - C++ source code for vcpkg and related components
triplets - Contains the settings for each supported target platform (for example, x86-windows or x64-uwp).

**Comment by timautry** [comment]
@ras0219-msft @BillyONeal @strega-nil @JackBoosY @Voskrese @Neumann-A
 - Never mind not need to fix this issue...
 - Product has become too unstable to be reliable to use for me. 
 - Quality control and regression of product control missing, as past months code changes break many things on local installs - it seem azure pipeline building has precedence :( not local small time user.
 - It now create more work just to maintain product change than time can be use to do real world work.
 - My opinion, project vcpkg should have stay as a **windows only package manager** like in beginning.
 - Linux and mac have excellent package managers already.
 - I go back to manual method for windows.
 - Best of luck with product vcpkg in future for the corporate and azure pipeline users...

**Comment by BillyONeal** [comment]
@timautry I'm sorry you are no longer happy with the product; our mechanism here where you are seeing effectively our nightly bits could do with some scheme where folks can ask for more stability than we currently offer.

I don't see the issue you report:

> PS D:\vcpkg> **$env:VCPKG_DOWNLOADS='D:\foobar'**
> PS D:\vcpkg> .\bootstrap-vcpkg.bat | Out-Null
> PS D:\vcpkg> .\vcpkg.exe install zlib
> Computing installation plan...
> A suitable version of cmake was not found (required v3.17.2). Downloading portable cmake v3.17.2...
> Downloading cmake...
>   https://github.com/Kitware/CMake/releases/download/v3.17.2/cmake-3.17.2-win32-x86.zip -> **D:\foobar**\cmake-3.17.2-win32-x86.zip
> Extracting cmake...
> A suitable version of 7zip was not found (required v18.1.0). Downloading portable 7zip v18.1.0...
> Downloading 7zip...
>   https://www.nuget.org/api/v2/package/7-Zip.CommandLine/18.1.0 -> D:\foobar\7-zip.commandline.18.1.0.nupkg
> Extracting 7zip...
> A suitable version of nuget was not found (required v5.5.1). Downloading portable nuget v5.5.1...
> Downloading nuget...
>   https://dist.nuget.org/win-x86-commandline/v5.5.1/nuget.exe -> D:\foobar\22ea847d-nuget.exe
> The following packages will be built and installed:
>     zlib[core]:x86-windows
> Detecting compiler hash for triplet x86-windows...
> A suitable version of powershell-core was not found (required v6.2.1). Downloading portable powershell-core v6.2.1...
> Downloading powershell-core...
>   https://github.com/PowerShell/PowerShell/releases/download/v6.2.1/PowerShell-6.2.1-win-x86.zip -> D:\foobar\PowerShell-6.2.1-win-x86.zip
> Extracting powershell-core...
> Starting package 1/1: zlib:x86-windows
> Building package zlib[core]:x86-windows...
> Could not locate cached archive: C:\Users\billy\AppData\Local\vcpkg\archives\b5\b59aaa790c27dfa19c0c39b5a972dc12781e2df9.zip
> -- Downloading http://www.zlib.net/zlib-1.2.11.tar.gz...
> -- Extracting source D:/foobar/zlib1211.tar.gz
> -- Applying patch cmake_dont_build_more_than_needed.patch
> -- Using source at D:/vcpkg/buildtrees/zlib/src/1.2.11-deec42f53b.clean
> -- Configuring x86-windows
> -- Building x86-windows-dbg
> -- Building x86-windows-rel
> -- Installing: D:/vcpkg/packages/zlib_x86-windows/share/zlib/copyright
> -- Performing post-build validation
> -- Performing post-build validation done
> Stored binary cache: C:\Users\billy\AppData\Local\vcpkg\archives\b5\b59aaa790c27dfa19c0c39b5a972dc12781e2df9.zip
> Building package zlib[core]:x86-windows... done
> Installing package zlib[core]:x86-windows...
> Installing package zlib[core]:x86-windows... done
> Elapsed time for package zlib:x86-windows: 4.076 s
> 
> Total elapsed time: 15.3 s
> 
> The package zlib is compatible with built-in CMake targets:
> 
>     find_package(ZLIB REQUIRED)
>     target_link_libraries(main PRIVATE ZLIB::ZLIB)
> 
> PS D:\vcpkg> git rev-parse HEAD
> f1fbee87db75a96fbb4a3e64359ba1004209cb40
> PS D:\vcpkg>

**Comment by strega-nil** [comment]
I'm also not seeing this behavior:

```
C:\..\nimazzuc\src\vcpkg> ./vcpkg install zlib
Computing installation plan...
warning: vcpkg appears to be in a Visual Studio prompt targeting x64 but is installing packages for x86-windows. Consider using --triplet x64-windows or --triplet x64-uwp.
The following packages will be built and installed:
    zlib[core]:x86-windows
Detecting compiler hash for triplet x86-windows...
A suitable version of powershell-core was not found (required v6.2.1). Downloading portable powershell-core v6.2.1...
Downloading powershell-core...
  https://github.com/PowerShell/PowerShell/releases/download/v6.2.1/PowerShell-6.2.1-win-x86.zip -> C:\Users\nimazzuc\src\vcpkg\downloads\PowerShell-6.2.1-win-x86.zip
A suitable version of 7zip was not found (required v18.1.0). Downloading portable 7zip v18.1.0...
Downloading 7zip...
  https://www.nuget.org/api/v2/package/7-Zip.CommandLine/18.1.0 -> C:\Users\nimazzuc\src\vcpkg\downloads\7-zip.commandline.18.1.0.nupkg
Extracting 7zip...
A suitable version of nuget was not found (required v5.5.1). Downloading portable nuget v5.5.1...
Downloading nuget...
  https://dist.nuget.org/win-x86-commandline/v5.5.1/nuget.exe -> C:\Users\nimazzuc\src\vcpkg\downloads\22ea847d-nuget.exe
Starting package 1/1: zlib:x86-windows
Building package zlib[core]:x86-windows...
Could not locate cached archive: C:\Users\nimazzuc\AppData\Local\vcpkg\archives\80\80217c0f2c1157f54c9aca0e0dfb94407b17ba3f.zip
-- Downloading http://www.zlib.net/zlib-1.2.11.tar.gz...
-- Cleaning sources at C:/Users/nimazzuc/src/vcpkg/buildtrees/zlib/src/1.2.11-deec42f53b.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/nimazzuc/src/vcpkg/downloads/zlib1211.tar.gz
-- Applying patch cmake_dont_build_more_than_needed.patch
-- Using source at C:/Users/nimazzuc/src/vcpkg/buildtrees/zlib/src/1.2.11-deec42f53b.clean
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Installing: C:/Users/nimazzuc/src/vcpkg/packages/zlib_x86-windows/share/zlib/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\nimazzuc\AppData\Local\vcpkg\archives\80\80217c0f2c1157f54c9aca0e0dfb94407b17ba3f.zip
Building package zlib[core]:x86-windows... done
Installing package zlib[core]:x86-windows...
Installing package zlib[core]:x86-windows... done
Elapsed time for package zlib:x86-windows: 6.223 s

Total elapsed time: 1.055 min

The package zlib is compatible with built-in CMake targets:

    find_package(ZLIB REQUIRED)
    target_link_libraries(main PRIVATE ZLIB::ZLIB)
```

**Comment by BillyONeal** [comment]
From your logs:

>Starting package 17/32: openal-soft:x64-windows
>Building package openal-soft[core]:x64-windows...
>Could not locate cached archive: >C:\Users\Tim.Autry\AppData\Local\vcpkg\archives\8f\8fa7ff1a28fd3bb56ec046ff06cd4e0a46a1bc8c.zip
>-- Downloading https://github.com/kcat/openal-soft/archive/f5e0eef34db3a3ab94b61a2f99f84f078ba947e7.tar.gz...
>-- Extracting source **D:/Git/vcpkg.downloads**/kcat-openal-soft-f5e0eef34db3a3ab94b61a2f99f84f078ba947e7.tar.gz

The reference to `vcpkg\archives` is not your `VCPKG_DOWNLOADS` folder, where sources are placed, it is the binary caching feature just turned on by default recently which will store built packages in case you go to reinstall them later.

**Comment by strega-nil** [comment]
And, for what it's worth, it looks like you're having an issue with running out of space in `~` because of the new binary caching feature; you can fix this by turning off the binary caching feature with an environment variable (`VCPKG_FEATURE_FLAGS=-binarycaching`), or with a flag (`--no-binarycaching`).

**Comment by Neumann-A** [comment]
Main issue I see:
- missing documentation of the feature and how to opt out. (I find the description for `VCPKG_FEATURE_FLAGS` e.g. Non-exhaustive list of off-by-default features: binarycaching manifest but It needs docs for the binarycaching feature itself)
- is there a environment variable to reroute the binary cache? If no there needs to be one
