### ISSUE TITLE
When I install the ./bootstrap.bat, the error occured 

### ISSUE THREAD

**Issue by yHsi** [microsoft/vcpkg#12416]
It is my first time to use vcpkg. When I clone the git code and install the bootstrap.bat, some message " Building vcpkg.exe failed. Please ensure you have installed Visual Studio with the Desktop C++ workload and the Windows SDK for Desktop C++." occured. I'm sure I have installed the vs2015. Then what other components should I add?

**Comment by NancyLi1013** [comment]
Hi @yHsi 
Thanks for posting this issue.
Please make sure if you have installed these workloads and components via Visual Studio Installer:

Workloads:
- Desktop development with C++
- Universal Windows Platform development (For uwp build)

Components:
- Visual C++ ATL/MFC for ARM/ARM64
- Visual C++ ATL(x86/x64) with Spectre Mitigations
- Visual C++ MFC(x86/x64) with Spectre Mitigations
- VC++ 2015.3 v14.00(v140) toolset for desktop
- Windows 10 SDK

Note: Please also installed English package and make sure you used Visual Studio 2015 Update3 or greater version.

You can refer this [file ](https://github.com/microsoft/vcpkg/blob/master/scripts/azure-pipelines/windows/provision-image.txt)to get more info about this.

**Comment by yHsi** [comment]
Hi @NancyLi1013 
Thanks for your reply.

**Comment by JackBoosY** [comment]
I think that's a vcpkg bug.

**Comment by JackBoosY** [comment]
After install Windows 10 SDK, this issue is gone.
