### ISSUE TITLE
[pthread] Handling of pthread linkage

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#12425]
Simply put this question does not exists for naitve windows builds but for mingw, linux, osx builds.

Which pthread library should we link?
 a) the one we internally build (would require renaming symlinking one of the built versions)
 b) the one the system provides

Should we decalre `Build-Depends: pthread` if we use the one provided by the system?
Should the pthread port not build pthread at all if it is provided by the system? (like libiconv?)

**Comment by JackBoosY** [comment]
@ras0219-msft What do you think?

**Comment by BillyONeal** [comment]
There should be a port that says "give me pthreads" which defines how this works, for example:

* nothing on POSIX and use pthreads-win32 or similar there (NOT PROPOSED AS THE FINAL SOLUTION HERE)

which allows a user to replace the behavior with overlay-ports or overrides.
