### ISSUE TITLE
GTK (glib) dll names are incompatible

### ISSUE THREAD

**Issue by BrentFarris** [microsoft/vcpkg#12428]
****

**Is your feature request related to a problem? Please describe.**
I am unable to use any 3rd party libraries that are not in vcpkg (such as gstreamer) because the way that vcpgk builds the GTK libs has the wrong names for a lot of the dll files. For example `gobject-2.dll` is what vcpkg has but `gobject-2.0-0.dll` is the correct name. This goes for many .dll files produced by vcpkg for gtk. Now when I try to include gstreamer, it is saying that `gobject-2.0-0.dll` is missing. 

**Proposed solution**
(a) Seeing how `gobject-2.0-0.dll` is the official build name for the dll, I am requesting that vcpkg builds **all** the dll files with the official naming so that there is compatibility with the many other libraries that vcpkg does not currently have.
(b) Adding gstreamer library to vcpkg (but this just solves only my personal issue)

**Describe alternatives you've considered**
I considered having 2 copies of every dll with the wrong name, but that is (1) silly and (2) the other dll is built separately with different flags possibly which means that I have conflicts between the internals and behaviors.

**Additional context**
1)  Install gtk from vcpkg
2)  Install [gstreamer libs](https://gstreamer.freedesktop.org/download/)
3)  Try to build their [hello world](https://gstreamer.freedesktop.org/documentation/tutorials/basic/hello-world.html?gi-language=c) example
4) Notice that it is asking for files such as `gobject-2.0-0.dll` and `glib-2.0-0.dll` (the official dll names) but vcpgk built them as `gobject-2.dll` and `glib-2.dll`

**Comment by Neumann-A** [comment]
That is not GTK but glib. glib needs to be updated and changed to its native build system. This can only be done when meson within vcpkg is updated to at least 0.55.

**Comment by BrentFarris** [comment]
Thanks for the reply! I've updated the title to help search engines.

Today I also built everything using msys2 and realized that there are some other bugs with the GTK vcpkg installation. Namely when I maximize a window a large amount of memory is allocated and never freed. If I continue opening the window, maximizing it, and closing it I can very easily get my memory well over 1GB of ram with only a single window open (this is not what happens with msys2 build of GTK). Anyway, I think that is a separate issue I can write up later I suppose.

**Comment by Voskrese** [comment]
@BrentFarris 
these are not VCPKG errors, look at the package versions, they are outdated here, so the library names are different

**Comment by PhoebeHui** [comment]
For GTK, since I noticed that the lib name '-lgtk-3' used in gtk and other XXXpc.in file.  so I removed the '0' for ARCHIVE_OUTPUT_NAME, before the libs name is  gdk-3.0.lib, now is gdk-3.lib. related to https://github.com/microsoft/vcpkg/pull/12326.
