### ISSUE TITLE
[boost-build] Use boost-build version number instead of boost version number

### ISSUE THREAD

**Issue by longnguyen2004** [microsoft/vcpkg#12422]
****

**Is your feature request related to a problem? Please describe.**
Since `boost-build` isn't a library, it's versioned separately from other `boost` components. As such we should use `boost-build` version number instead of `boost` version number. The second reason is that `v4.3.0` for `boost-build` contains some fixes for `mingw` toolchain, which I'd like to have.

**Proposed solution**
Use `boost-build` version number instead of `boost` version number

**Comment by PhoebeHui** [comment]
@longnguyen2004, thanks for reporting this issue!

From https://github.com/boostorg/build/releases, boost-build has release revision boost-1.73.0 which used in vcpkg, I think we need to keep the revision consistent with boost personally. @ras0219-msft , what do you think?

**Comment by longnguyen2004** [comment]
> boost-build has release revision boost-1.73.0
And also 4.3.0. I'm not sure but I feel like boost-build is more like its own thing rather than being related to other boost components (well, aside from the name)

**Comment by longnguyen2004** [comment]
So, should we stay at boost-1.73.0 (and having to wait until the next version of boost for updates) or switch to 4.3.0?

**Comment by longnguyen2004** [comment]
Boost 1.74.0 has been released, so this should be unnecessary. Let's do the update instead xD
