### ISSUE TITLE
[New Port Request] libnfc

### ISSUE THREAD

**Issue by haraldegger** [microsoft/vcpkg#12438]
Library name: libnfc

Library description:libnfc is a library which allows userspace application access to NFC devices.

Source repository URL: https://github.com/nfc-tools/libnfc

Project homepage (if different from the source repository): http://www.nfc-tools.org/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
