### ISSUE TITLE
[vcpkg] Could not locate a complete toolset.

### ISSUE THREAD

**Issue by yHsi** [microsoft/vcpkg#12433]
- OS windows

- visual studio version: visual surdio 2015

When I want to install a package, the error occured "Could not locate a complete toolset".
Some people suggested to install the English language package for vs, but this is useless for me.

**Comment by Voskrese** [comment]
nothing is clear, but very interesting

can you describe in more detail?

**Comment by JackBoosY** [comment]
@yHsi Thanks for reporting this issue!
Could you please provide the failure logs?

Thanks.

**Comment by bio-punk** [comment]
I also have this problem when I use VS2015update3 with English-language-pack on Windows10(1909).

So, How can I find failure log of vcpkg?

**Comment by JackBoosY** [comment]
@bio-punk please provide the message printed on console.

**Comment by bio-punk** [comment]
> @bio-punk please provide the message printed on console.
ok, here is my Console when I try to install opencv3

![vcpkg](https://user-images.githubusercontent.com/9584268/91827424-6a791080-ec71-11ea-97a9-3ba8fb616674.JPG)


```
PS C:\dev> chcp 65001                                                                                                                                                                                                                                                          Active code page: 65001
PS C:\dev> .\vcpkg\vcpkg install opencv3                                                                                                                                                                                                                                       Computing installation plan...
The following packages will be built and installed:
  * libjpeg-turbo[core]:x86-windows
  * liblzma[core]:x86-windows
  * libpng[core]:x86-windows
  * libwebp[core,nearlossless,simd,unicode]:x86-windows
    opencv3[core,dnn,flann,jpeg,opengl,png,tiff,webp]:x86-windows
  * opengl[core]:x86-windows
  * protobuf[core]:x86-windows
  * tiff[core]:x86-windows
  * zlib[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Could not locate a complete toolset.
The following paths were examined:
PS C:\dev> .\vcpkg\vcpkg install opencv3 --debug                                                                                                                                                                                                                               [DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Using vcpkg-root: C:\dev\vcpkg
[DEBUG] Using installed-root: C:\dev\vcpkg\installed
[DEBUG] Using buildtrees-root: C:\dev\vcpkg\buildtrees
[DEBUG] Using downloads-root: C:\dev\vcpkg\downloads
[DEBUG] Using packages-root: C:\dev\vcpkg\packages
[DEBUG] Using scripts-root: C:\dev\vcpkg\scripts
[DEBUG] Default binary cache path is: C:\Users\wzk\AppData\Local\vcpkg\archives
Computing installation plan...
[DEBUG] Found path: D:\ProgramData\Miniconda3\Scripts\cmake.exe
[DEBUG] Found path: D:\Program Files\Python36\Scripts\\cmake.exe
[DEBUG] Found path: D:\Program Files\CMake\bin\cmake.exe
[DEBUG] CreateProcessW("D:\ProgramData\Miniconda3\Scripts\cmake.exe" --version)
[DEBUG] cmd_execute_and_stream_data() returned 0 after    88017 us
[DEBUG] CreateProcessW("D:\ProgramData\Miniconda3\Scripts\cmake.exe" -DVCPKG_ROOT_DIR=C:/dev/vcpkg -DPACKAGES_DIR=C:/dev/vcpkg/packages -DBUILDTREES_DIR=C:/dev/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=C:/dev/vcpkg/installed -DDOWNLOADS=C:/dev/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "C:\dev\vcpkg\buildtrees\0.vcpkg_dep_info.cmake")
[DEBUG] cmd_execute_and_stream_data() returned 0 after    81698 us
[DEBUG] CreateProcessW("D:\ProgramData\Miniconda3\Scripts\cmake.exe" -DVCPKG_ROOT_DIR=C:/dev/vcpkg -DPACKAGES_DIR=C:/dev/vcpkg/packages -DBUILDTREES_DIR=C:/dev/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=C:/dev/vcpkg/installed -DDOWNLOADS=C:/dev/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "C:\dev\vcpkg\buildtrees\0.vcpkg_tags.cmake")
[DEBUG] cmd_execute_and_stream_data() returned 0 after    84719 us
The following packages will be built and installed:
  * libjpeg-turbo[core]:x86-windows
  * liblzma[core]:x86-windows
  * libpng[core]:x86-windows
  * libwebp[core,nearlossless,simd,unicode]:x86-windows
    opencv3[core,dnn,flann,jpeg,opengl,png,tiff,webp]:x86-windows
  * opengl[core]:x86-windows
  * protobuf[core]:x86-windows
  * tiff[core]:x86-windows
  * zlib[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Could not locate a complete toolset.
The following paths were examined:
[DEBUG] ..\..\src\vcpkg\visualstudio.cpp(367)
[DEBUG] Exiting after 270262 us (264373 us)
PS C:\dev>                                         
```

**Comment by JackBoosY** [comment]
@bio-punk Does your Visual Studio installed in the default path? And please make sure you installed the English Language Package.

**Comment by bio-punk** [comment]
> @bio-punk Does your Visual Studio installed in the default path? And please make sure you installed the English Language Package.
No，VS install in D:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE

**Comment by bio-punk** [comment]
> > @bio-punk Does your Visual Studio installed in the default path? And please make sure you installed the English Language Package.
> > No，VS install in D:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE
Does VS must install in C:\？

**Comment by JackBoosY** [comment]
@bio-punk 
https://github.com/microsoft/vcpkg/blob/ea82e4650890001b6a3177781e0c6096c9e1ca54/toolsrc/src/vcpkg/visualstudio.cpp#L84

**Comment by gvanem** [comment]
I have the same error:
```
Could not locate a complete toolset.
The following paths were examined:
    f:\gv\VC_2019\Common7\VC\Auxiliary\Build\vcvarsall.bat
[DEBUG] vcpkg/visualstudio.cpp(367)
[DEBUG] Exiting after 276643 us (276478 us)
```

And I have the latest MSVC-2019. My `vcvarsall.bat` is in fact here:
`f:\gv\vc_2019\VC\Auxiliary\Build\vcvarsall.bat`

Why/how does `vcpkg` look into a path that doesn't exist?

**Comment by BillyONeal** [comment]
@gvanem That looks like a completely different error since you're talking about a completely different VS. We got the root path f:\gv\VC_2019\Common7 as the output of vswhere.

**Comment by jonahbeckford** [comment]
To help those of us who have problems detecting VS, can you add `--debug` statements to (I think) https://github.com/microsoft/vcpkg/blob/2020.11/toolsrc/src/vcpkg/visualstudio.cpp#L191-L345 ? Or at least tell us how to do that?

I think it would cut down on the tickets if we had a --debug statement everytime the visualstudio.cpp code rejected a VS instance (or didn't find vswhere.exe, etc).

**Comment by JonLiu1993** [comment]
@yHsi, sorry for reply you so late, does this issue persist in the latest vcpkg?

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
