### ISSUE TITLE
[fmt] post-build failure using VCPKG_PLATFORM_TOOLSET=v141

### ISSUE THREAD

**Issue by chris-t-w** [microsoft/vcpkg#12446]
**Describe the bug**

I want to build the `fmt` port on Windows for Visual Studio 2017, however by default `vcpkg` is using the Visual Studio 2019 installation that I also have on my machine. As per the advice on [issue 1234](https://github.com/Microsoft/vcpkg/issues/1234), I created a custom triplet file, however, I receive an error at the end of the build.

**Environment**
- OS: Windows
- Compiler: Visual Studio 2017 (v141)

**To Reproduce**
1. Create a custom triplet file (`triplets/x86-windows-v141.cmake`):

```set(VCPKG_TARGET_ARCHITECTURE x86)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_PLATFORM_TOOLSET v141)
```

2. `vcpkg install fmt:x86-windows-v141 --debug`

**Expected behavior**

The library should successfully build and install using the Visual Studio 2017 tools.

**Failure logs** 

```
[DEBUG] CreateProcessW("C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86\dumpbin.exe" /exports "C:\dev\vcpkg\packages\fmt_x86-windows-v141\debug\bin\fmtd.dll")
[DEBUG] cmd_execute_and_stream_data() returned 1 after   110908 us
Running command:
   "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86\dumpbin.exe" /exports "C:\dev\vcpkg\packages\fmt_x86-windows-v141\debug\bin\fmtd.dll"
 failed
[DEBUG] C:\dev\vcpkg\toolsrc\src\vcpkg\postbuildlint.cpp(397)
```

**Additional context**

I have a slightly different but possibly related problem for a statically linked x64 version (`vcpkg install fmt:x64-windows-static-v141`):

```
Running command:
   "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86\dumpbin.exe" /directives "C:\dev\vcpkg\packages\fmt_x64-windows-static-v141\debug\lib\fmtd.lib"
 failed with message:
LINK: extra operand ‘C:\\dev\\vcpkg\\packages\\fmt_x64-windows-static-v141\\debug\\lib\\fmtd.lib’
Try 'LINK --help' for more information.

[DEBUG] C:\dev\vcpkg\toolsrc\src\vcpkg\postbuildlint.cpp(723)
```

**Comment by PhoebeHui** [comment]
@chris-t-w, I can't repro this issue, I tried following triplets with latest vcpkg source. it built successfully for me.

.\triplets\community\x86-windows-v141.cmake:
```
set(VCPKG_TARGET_ARCHITECTURE x86)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_PLATFORM_TOOLSET v141)
```

PS F:\vcpkg\src> ./vcpkg install fmt:x86-windows-v141
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
Computing installation plan...
A suitable version of cmake was not found (required v3.17.2). Downloading portable cmake v3.17.2...
Downloading cmake...
  https://github.com/Kitware/CMake/releases/download/v3.17.2/cmake-3.17.2-win32-x86.zip -> F:\vcpkg\src\downloads\cmake-3.17.2-win32-x86.zip
Extracting cmake...
The following packages will be built and installed:
    fmt[core]:x86-windows-v141
Detecting compiler hash for triplet x86-windows-v141...
A suitable version of git was not found (required v2.26.2). Downloading portable git v2.26.2...
Downloading git...
  https://github.com/git-for-windows/git/releases/download/v2.26.2.windows.1/PortableGit-2.26.2-32-bit.7z.exe -> F:\vcpkg\src\downloads\PortableGit-2.26.2-32-bit.7z.exe
Extracting git...
Starting package 1/1: fmt:x86-windows-v141
Building package fmt[core]:x86-windows-v141...
-- Using community triplet x86-windows-v141. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: F:\vcpkg\src\triplets\community\x86-windows-v141.cmake
-- Downloading https://github.com/fmtlib/fmt/archive/19bd751020a1f3c3363b2eb67a039852f139a8d3.tar.gz...
-- Extracting source F:/vcpkg/src/downloads/fmtlib-fmt-19bd751020a1f3c3363b2eb67a039852f139a8d3.tar.gz
-- Applying patch fix-warning4189.patch
-- Using source at F:/vcpkg/src/buildtrees/fmt/src/52f139a8d3-70a26f0c4b.clean
-- Configuring x86-windows-v141
-- Building x86-windows-v141-dbg
-- Building x86-windows-v141-rel
-- Installing: F:/vcpkg/src/packages/fmt_x86-windows-v141/share/fmt/copyright
-- Fixing pkgconfig
-- Fixing pkgconfig - release
-- Checking file: F:/vcpkg/src/packages/fmt_x86-windows-v141/lib/pkgconfig/fmt.pc
-- Fixing pkgconfig - debug
-- Checking file: F:/vcpkg/src/packages/fmt_x86-windows-v141/debug/lib/pkgconfig/fmt.pc
-- Fixing pkgconfig --- finished
-- Performing post-build validation
-- Performing post-build validation done
...
Building package fmt[core]:x86-windows-v141... done
Installing package fmt[core]:x86-windows-v141...
Installing package fmt[core]:x86-windows-v141... done
Elapsed time for package fmt:x86-windows-v141: 40.68 s

Total elapsed time: 1.635 min

The package fmt:x86-windows-v141 provides CMake targets:

    find_package(fmt CONFIG REQUIRED)
    target_link_libraries(main PRIVATE fmt::fmt fmt::fmt-header-only)

**Comment by chris-t-w** [comment]
I think I got to the bottom of the problem.

I have the `git` bin directory on my `PATH` environment variable and this directory contains a `link.exe` program:

```
> where link
C:\Program Files\Git\usr\bin\link.exe

> echo %PATH%
...;C:\Program Files\Git\usr\bin
```

It appears that the `dumpbin.exe` program in Visual Studio 2017 is picking up this `link.exe` binary from the `PATH` instead of the one in the Visual Studio installation.

In Visual Studio 2019 it works correctly by picking up the correct `link.exe`.

Either removing the git bin directory from the `PATH` or running the `vcpkg` install step inside a Visual Studio developer console (which ensures that the correct `link.exe` is on the `PATH` first) worked.
