### ISSUE TITLE
[x264] build failure

### ISSUE THREAD

**Issue by aspioupiou** [microsoft/vcpkg#12447]
**Host Environment**
- OS: Windows 10
- Compiler: VS2017
- Latest VCPKG

**To Reproduce**
`./vcpkg install x264`

**Failure logs** 
```
Unknown option --build=i686-pc-mingw32, ignored
Unknown option --target=i686-pc-mingw32, ignored
Unknown option --disable-silent-rules, ignored
Unknown option --verbose, ignored
Unknown option --disable-static, ignored
Unknown option --sbindir=${prefix}/../tools/x264/debug/sbin, ignored
Unknown option --datarootdir=${prefix}/share/x264, ignored
No working C compiler found.
```

**Additional context**
Seems to build x86 instead of x64.. Maybe a clue **EDIT 1 : Forcing x64 build with `vcpkg install x264:x64-windows` does not change anything**

**Comment by Voskrese** [comment]
full log attach

**Comment by NancyLi1013** [comment]
Hi @aspioupiou 
Thanks for posting this issue.
Currently, `x264 `can only build on Linux.
Since there is something wrong with `vcpkg_configure_make()`. We need to improve it.

Let's move attention to #11765.

**Comment by aspioupiou** [comment]
Hi @NancyLi1013 

I'd rather keep talking here instead of recreating a new issue, as my issue is directly linked to this one but not to #11765 

As we're using vcpkg in a company environment, we do need to ensure we can build the dependencies. 
Since updating to `2020.06` seems to be impossible in the meantime (`x264` can't be built because of #11765), we tried to make a step back and update from a 2019.10 release to a 2020.01/04 instead of 06.

However, we've noticed x264 is not built there either, having a msys building issue : 

```
-- Acquiring MSYS Packages...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: D:/usr/Documents/Code/vcpkg/downloads/tools/msys2/msys64/usr/bin/bash.exe --noprofile --norc -c "pacman -Sy --noconfirm --needed diffutils"
    Working Directory: D:/brard/Documents/Code/vcpkg/downloads/tools/msys2
    Error code: Exit code 0xc0000142



    See logs for more information:

Call Stack (most recent call first):
  scripts/cmake/vcpkg_acquire_msys.cmake:106 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_configure_make.cmake:130 (vcpkg_acquire_msys)
  ports/x264/portfile.cmake:19 (vcpkg_configure_make)
  scripts/ports.cmake:94 (include)

```

This is very problematic, as we're not capable to build our project again since we absolutely need `x264`.
How such a regression happened? And how can we solve it to at least keep build the project without any errors? (BTW, we didn't noticed this issue before because of dependencies cache not beeing updated)

Thank you

**Comment by sfhacker** [comment]
@aspioupiou There seems to be plenty of issues with this port (x264). Have you been able to sort this issue out?
Just downloaded master branch and no issues at all building it from source.

![image](https://user-images.githubusercontent.com/25817529/92627906-6010e380-f30f-11ea-8724-4bf1aa40ef50.png)

Let us know if we can be of further assistance.
