### ISSUE TITLE
[nrf-ble-driver:*-windows ci] Miscellaneous failures?

### ISSUE THREAD

**Issue by strega-nil** [microsoft/vcpkg#12450]
We should figure out what's going on with nrf-ble-driver, it's failing a bunch of PR tests: #12444, #12434, #12421, and a bunch of others.

**Comment by ras0219-msft** [comment]
Looks like `libmicrohttpd` is installing `include/platform.h` -- very bad practice, sad faces

**Comment by PhoebeHui** [comment]
Related to https://github.com/microsoft/vcpkg/pull/12445

**Comment by Karlson2k** [comment]
> Looks like `libmicrohttpd` is installing `include/platform.h` -- very bad practice, sad faces

Note to keep in history.
`libmicrohttpd` does not install any header except `libmicrohttpd.h`.
vcpkg's portfile was designed incorrectly.

Current vcpkg version finally installs correct `libmicrohttpd` headers (after merging my PR #31740).
