### ISSUE TITLE
Visual Studio 2019 not recognizing headers installed by vcpkg

### ISSUE THREAD

**Issue by v-tcassi** [microsoft/vcpkg#12452]
**Describe the bug**
I'm following this tutorial in the IoT Edge documentiontation: https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-c-module-windows

At the beginning, it uses vcpkg to install the Azure IoT Edge C SDK to develop the C module with. This include doing a fresh pull of vcpkg from the repo, bootstrapping vcpkg, installing the Azure IoT Edge C SDK package, and then running the integrate install. 

**Environment**
- OS: Windows 10
- Compiler: revision

**To Reproduce**
Following the tutorial's steps, but, more specifically:
1. .\vcpkg install azure-iot-sdk-c:x64-windows
2. .\vcpkg --triplet x64-windows integrate install
3. Creating a new project using Azure IoT Edge (Windows amd65) template (search for IoT Edge)
4. Selecting C Module (you don't need to do the IoT Container Registry stuff to reproduce the error)
5. Go to main.c, and the includes for the nine headers provided by the vcpkg install will throw errors.

**Expected behavior**
Visual Studio code can resolve the referenced headers from an integrated vcpkg install.

**Failure logs** 
Errors:
![image](https://user-images.githubusercontent.com/67973755/87712191-2e3f2e80-c75d-11ea-9c3f-fb81e2e5a37b.png)

vcpkg install:
![image](https://user-images.githubusercontent.com/67973755/87712405-72323380-c75d-11ea-86af-3dfee28f821c.png)
![image](https://user-images.githubusercontent.com/67973755/87712265-49aa3980-c75d-11ea-9a1b-f71af311b054.png)
![image](https://user-images.githubusercontent.com/67973755/87712341-6181bd80-c75d-11ea-8324-dafafd099760.png)

**Additional context**

Thanks for your time!

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Please run command `.\vcpkg.exe integrate project` and reopen Visual Studio, and rebuild your project.

**Comment by LilyWangL** [comment]
Please reopen this issue if this is still a problem for you.
