### ISSUE TITLE
[magnum-plugins] build failure using incorrect stb header files - an FYI

### ISSUE THREAD

**Issue by StarGate-One** [microsoft/vcpkg#12466]
**Host Environment**
- OS: [Microsoft Windows Version 10.0.19041.388]
- Compiler: Visual Studio 2017 15.9.25  VS Tools 14.16.27023

**To Reproduce**
1. `set VCPKG_DEFAULT_TRIPLET=x64-windows`
2. `.\vcpkg.exe Install stb[core]`
3. `.\vcpkg.exe install allegro5[core] bullet3[core,multithreading] corrade[core,interconnect,pluginmanager,testsuite,utility] devil[core,jasper,lcms,libjpeg,libpng,openexr,tiff] egl-registry[core] freeglut[core] freetype[bzip2,core,png] gettext[core] gl3w[core] glad[core] glbinding[core] glew[core] glfw3[core] glib[core] glm[core] graphite2[core] harfbuzz[core,glib,graphite2,icu] icu[core] imgui[allegro5-binding,core,dx10-binding,dx11-binding,dx12-binding,dx9-binding,freetype,glfw-binding,glut-binding,marmalade-binding,opengl2-binding,opengl3-gl3w-binding,opengl3-glad-binding,opengl3-glbinding-binding,opengl3-glew-binding,sdl2-binding,vulkan-binding,win32-binding] jasper[core] lcms[core] libffi[core] libflac[core] libiconv[core] libjpeg-turbo[core] liblzma[core] libogg[core] libpng[apng,core] libtheora[core] libvorbis[core] magnum[al-info,anyaudioimporter,anyimageconverter,anyimageimporter,anysceneconverter,anysceneimporter,audio,cglcontext,core,debugtools,distancefieldconverter,fontconverter,gl,gl-info,glfwapplication,imageconverter,magnumfont,magnumfontconverter,meshtools,objimporter,opengltester,primitives,scenegraph,sdl2application,shaders,text,texturetools,tgaimageconverter,tgaimporter,trade,wavaudioimporter,wglcontext,windowlesswglapplication] magnum-extras[core,ui] magnum-integration[bullet,core,glm,imgui] magnum-plugins[core,ddsimporter,devilimageimporter,drflacaudioimporter,freetypefont,harfbuzzfont,icoimporter,jpegimageconverter,jpegimporter,miniexrimageconverter,openddl,opengeximporter,pngimageconverter,pngimporter,stanfordimporter,stanfordsceneconverter,stbimageconverter,stbimageimporter,stlimporter] openal-soft[core] openexr[core] opengl[core] opengl-registry[core] opus[avx,core] opusfile[core] pcre[core] pcre2[core] physfs[core] ragel[core] sdl2[core,vulkan] tiff[core,tool] vulkan[core] zlib[core] --recurse --keep-going`
3. Port magnum-plugins will fail, see **Additional context** below.

**Failure logs** 
- Cut and past the appropriate build messages from the console output.
  I failed to save the console output but see **Additional context** below.
- Please attach any additional failure logs mentioned in the console output.
  I failed to save the log output but see **Additional context** below.

**Additional context**
1. This is a FYI really as I have implemented a work-around to install magnum ports first then stb port after successfully installing the magnum ports.

2. If vcpkg port stb is install before installing magnum-plugins, port magnum-plugins fails because the build finds/uses the `stb_image.h, stb_image_write.h and stb_truetype.h` files found in `<vcpkg-root>\installed\<triplet>\include` _(as the __stb_image.h__ is missing the __stbi_convert_iphone_png_to_rgb__ and __stbi_set_flip_vertically_on_load__ definitions)_  instead of the correct ones found in `<vcpkg-root>\buildtrees\magnum-plugins\src\v2020.06-f0c46dc4fa.clean\src\external\stb`.

3. If port stb is **NOT** installed before install of above mentioned packages, magnum-plugins port will install correctly.

4. One can then install port stb, but...  there is a potential could effect using the magnum-plugins header files in a downstream project depending on the search order of include files in the project and/or the magnum-plugins header files.

**Comment by StarGate-One** [comment]
I see PR #12458 is already in the works to fix this - thank you @JackBoosY .

**Comment by JackBoosY** [comment]
Fixed.
