### ISSUE TITLE
[vcpkg] Use Supports field to print a warning if port does not support the target triplet

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#12461]
Since the introduction of the `Supports` field `vcpkg_fail_port_install` isn't really necessary anymore.
VCPKG should detect if a port is supported on a given platform and otherwise print a **Warning** (not error) that the current port is not supported on the platform and the build is most likely to fail.

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/11231
