### ISSUE TITLE
Fix automatic tests in the master or remove them.

### ISSUE THREAD

**Issue by talregev** [microsoft/vcpkg#12479]
> **Describe the bug**
> A clear and concise description of what the bug is.

Some of the automatic tests in the master are always fail.

>**Environment**
- OS: Windows/Linux
- Compiler: compiler from master.

> **To Reproduce**
> Steps to reproduce the behavior:
1. Make a PR into microsoft/vcpkg
2. See with your sad eyes that the tests are fails.

> **Expected behavior**
> A clear and concise description of what you expected to happen.

All the tests in the master should be past, or remove them.

> **Failure logs** 
> -(please attached failure logs)

> **Additional context**
> Add any other context about the problem here.

**Comment by JackBoosY** [comment]
Now, vcpkg will report errors if it encounters a keyword that is not expected when parsing the CONTROL file.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
