### ISSUE TITLE
How do I use sdl, it isnt working by default in x86 nor x64?

### ISSUE THREAD

**Issue by Orion160x** [microsoft/vcpkg#12474]
I have just installed visual studio 2019, vcpkg and sdl2 both versions x86 and x64, i already integrated vcpkg with sdl2 and when i include the SDL/sdl2 library it gives me an error at the moment of build it.

**Comment by drescherjm** [comment]
You probably need to show your errors.

**Comment by Orion160x** [comment]
Severity    Code    Description Project File    Line    Suppression State
Warning C26812  The enum type 'SDL_bool' is unscoped. Prefer 'enum class' over 'enum' (Enum.3). vcpkgSDL2test   C:\Users\idbl6\Documents\repos\vcpkg\installed\x86-windows\include\SDL2\SDL_rect.h  102 

Severity    Code    Description Project File    Line    Suppression State
Error   LNK1561 entry point must be defined vcpkgSDL2test   C:\dev\C++Projects\vcpkgSDL2test\vcpkgSDL2test\LINK 1   

Severity    Code    Description Project File    Line    Suppression State
Error   LNK1120 1 unresolved externals  vcpkgSDL2test   C:\dev\C++Projects\vcpkgSDL2test\x64\Debug\vcpkgSDL2test.exe    1

**Comment by StarGate-One** [comment]
- See https://github.com/microsoft/vcpkg/blob/master/docs/users/integration.md - under the `vcpkg integrate install` paragraph, it mentions SDL2 has an SDL2main library that must be manually linked.
- you can get a full list by entering `vcpkg owns manual-link` for what you may have installed.
- Example for my system:
`->vcpkg owns manual-link`
`gtest:x64-windows: x64-windows/debug/lib/manual-link/gmock_maind.lib`
`gtest:x64-windows: x64-windows/debug/lib/manual-link/gtest_maind.lib`
`gtest:x64-windows: x64-windows/debug/lib/manual-link/pkgconfig/gmock_main.pc`
`gtest:x64-windows: x64-windows/debug/lib/manual-link/pkgconfig/gtest_main.pc`
`gtest:x64-windows: x64-windows/lib/manual-link/gmock_main.lib`
`gtest:x64-windows: x64-windows/lib/manual-link/gtest_main.lib`
`gtest:x64-windows: x64-windows/lib/manual-link/pkgconfig/gmock_main.pc`
`gtest:x64-windows: x64-windows/lib/manual-link/pkgconfig/gtest_main.pc`
`gettimeofday:x64-windows: x64-windows/debug/lib/manual-link/gettimeofday.lib`
`gettimeofday:x64-windows: x64-windows/lib/manual-link/gettimeofday.lib`
`ogre-next:x64-windows: x64-windows/debug/lib/manual-link/OgreMain_d.lib`
`ogre-next:x64-windows: x64-windows/lib/manual-link/OgreMain.lib`
`sdl1:x64-windows: x64-windows/debug/lib/manual-link/SDLmaind.lib`
`sdl1:x64-windows: x64-windows/lib/manual-link/SDLmain.lib`
`sfml:x64-windows: x64-windows/debug/lib/manual-link/sfml-main-d.lib`
`sfml:x64-windows: x64-windows/lib/manual-link/sfml-main.lib`
`sdl2:x64-windows: x64-windows/debug/lib/manual-link/SDL2maind.lib`
`sdl2:x64-windows: x64-windows/lib/manual-link/SDL2main.lib`
`boost-test:x64-windows: x64-windows/debug/lib/manual-link/boost_prg_exec_monitor-vc140-mt-gd.lib`
`boost-test:x64-windows: x64-windows/debug/lib/manual-link/boost_test_exec_monitor-vc140-mt-gd.lib`
`boost-test:x64-windows: x64-windows/lib/manual-link/boost_prg_exec_monitor-vc140-mt.lib`
`boost-test:x64-windows: x64-windows/lib/manual-link/boost_test_exec_monitor-vc140-mt.lib`

**Comment by Orion160x** [comment]
Okay, thank you.
I didnt know that i had to manually link some libs.
