### ISSUE TITLE
Total elapsed time: -7.265e+11 ns

### ISSUE THREAD

**Issue by OlafvdSpek** [microsoft/vcpkg#12470]
```
Total elapsed time: -7.265e+11 ns
```

Is a non-steady clock being used? ;)

Windows 10

**Comment by NancyLi1013** [comment]
Hi @OlafvdSpek 
Thanks for posting this issue.
Could you please provide full log about this?

**Comment by OlafvdSpek** [comment]
I think the logs are gone..

**Comment by NancyLi1013** [comment]
Could you please provide more info about this issue? Such as the steps to reproduce

**Comment by OlafvdSpek** [comment]
Are you familiar with the code and the type of clocks being used?

My guess would be it's related to a jump in time of the system clock, due to a VM being suspended. Repro without knowledge of the internals is probably not trivial.

**Comment by JackBoosY** [comment]
**VM being suspended**

**Comment by NancyLi1013** [comment]
Sorry, I'm not familiar with this.

@strega-nil 
Could you please help take a look?

**Comment by strega-nil** [comment]
This isn't really a bug... we use `std::chrono::high_resolution_clock`, and this seems like just debug output, so I'm not that concerned about it.

**Comment by OlafvdSpek** [comment]
How is this not a bug?
I agree it might not be important but I don't get how it's not a bug.

**Comment by strega-nil** [comment]
It might be a "bug", but at worst it's chrono not supporting suspending VMs in the middle of execution. Given that it's just a helpful message...
