### ISSUE TITLE
[libpq] build failure with file conflict with decimal.h from port decimal-for-cpp

### ISSUE THREAD

**Issue by StarGate-One** [microsoft/vcpkg#12473]
**Host Environment**
- OS: [Microsoft Windows Version 10.0.19041.388]
- Compiler: Visual Studio 2019 16.6.4  VS Tools 14.26.28801 

**To Reproduce**

2 Scenarios discovered, both have default triplet `set VCPKG_DEFAULT_TRIPLET=x64-windows`

- **Scenario One: - port libpq build failure if port decimal-for-cpp already installed**
1. `.\vcpkg.exe install decimal-for-cpp` **installs successfully**
2. `.\vcpkg.exe install gettext[core] icu[core] libiconv[core] liblzma[core] libpq[core,icu,nls,openssl,xml,zlib] libxml2[core] openssl[core] openssl-windows[core] zlib[core]` **all dependencies install successfully, but port libpq fails**
3. See **Failure logs** and **Additional context** sections below for console output and failure logs along with context explanation.

- **Scenario Two:**
1. `.\vcpkg.exe install gettext[core] icu[core] libiconv[core] liblzma[core] libpq[core,icu,nls,openssl,xml,zlib] libxml2[core] openssl[core] openssl-windows[core] zlib[core]` **all dependencies and port libpq install successfully**
2. `.\vcpkg.exe install decimal-for-cpp` **installs successfully**
3. Increment Port-Version up (I chose to use 1000) within CONTROL file of port libpq in directory/folder `<vcpkg-root>\ports\libpq` making vcpkg think there has been an update to port libpq forcing it to remove/reinstall port libpq in upgrade action.
4. `.\vcpkg.exe update` **Shows port libpq needs to be upgrade**
`->vcpkg update`
`Using local portfile versions. To update the local portfiles, use `git pull`.`
`The following packages differ from their port versions:`
`    libpq:x64-windows                12.2#5 -> 12.2#1000`
`To update these packages and all dependencies, run`
`    .\vcpkg upgrade`
5. `.\vcpkg.exe upgrade --no-dry-run` **upgrade fails on port libpq**
6. If you **remove port decimal-for-cpp** before the **vcpkg upgrade --no-dry-run** then the **upgrade completes successfully**.
7. See **Failure logs** and **Additional context** sections below for console output and failure logs along with context explanation.

**Failure logs** 
- Cut and past the appropriate build messages from the console output.
   1. [Scenario-One-Console.log](https://github.com/microsoft/vcpkg/files/4940564/Scenario-One-Console.log)
   2. [Scenario-Two-Console-vcpkg-install.log](https://github.com/microsoft/vcpkg/files/4940606/Scenario-Two-Console-vcpkg-install.log)
   3. [Scenario-Two-Console-vcpkg-upgrade.log](https://github.com/microsoft/vcpkg/files/4940609/Scenario-Two-Console-vcpkg-upgrade.log)

- Please attach any additional failure logs mentioned in the console output.
   1. [Scenario-One-build-libecpg_compat-x64-windows-RELEASE-out.log](https://github.com/microsoft/vcpkg/files/4940565/Scenario-One-build-libecpg_compat-x64-windows-RELEASE-out.log)
   2. [Scenario-Two-build-libecpg_compat-x64-windows-RELEASE-out.log](https://github.com/microsoft/vcpkg/files/4940610/Scenario-Two-build-libecpg_compat-x64-windows-RELEASE-out.log)

**Additional context**
- The `Building libecpg_compat x64-windows-RELEASE...` step of port libpq appears to be finding/using the `<vcpkg-root>\installed\<triplet>\include\decimal.h` instead of the `<vcpkg-root>\buildtrees\libpq\src\tgresql-12-3dcd887135.clean\src\interfaces\ecpg\include\decimal.h`.
- `.\vcpkg.exe owns decimal.h` shows both ports libpq and decimal-for-cpp owning the `decimal.h` file(s)
`->vcpkg owns decimal.h`
`decimal-for-cpp:x64-windows: x64-windows/include/decimal.h`
`libpq:x64-windows: x64-windows/include/informix/esql/decimal.h`

**Comment by ras0219-msft** [comment]
Thanks for the info!

Based on the relative popularity of the libraries and how common the header name "decimal.h" is[1], I believe the right way to fix this is is actually to install `decimal-for-cpp`'s header into a subdirectory. This is a breaking change for consumers of `decimal-for-cpp`.

[1] https://packages.debian.org/search?searchon=contents&keywords=decimal.h&mode=path&suite=stable&arch=any
