### ISSUE TITLE
[openssl-windows:x86-windows] build failure

### ISSUE THREAD

**Issue by 4drik** [microsoft/vcpkg#12489]
**Host Environment**
- OS: Windows

**To Reproduce**
`./vcpkg install wxwidgets boost libarchive`

**Failure logs** 
Starting package 92/160: openssl-windows:x86-windows
Building package openssl-windows[core]:x86-windows...
Could not locate cached archive: C:\Users\Lenovo_Pc\AppData\Local\vcpkg\archives\59\59d3d47ee57542cb7baafe68967dac3a6218b545.zip
-- Downloading https://strawberry.perl.bot/download/5.30.0.1/strawberry-perl-5.30.0.1-32bit.zip...
-- Downloading https://www.openssl.org/source/openssl-1.1.1g.tar.gz...
-- Extracting source C:/vcpkg/downloads/openssl-1.1.1g.tar.gz
-- Using source at C:/vcpkg/buildtrees/openssl-windows/src/openssl-1-bb2a9a5801.clean
-- Downloading http://www.nasm.us/pub/nasm/releasebuilds/2.14.02/win32/nasm-2.14.02-win32.zip...
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:99 (message):

  File does not have expected hash:

          File path: [ C:/vcpkg/downloads/temp/nasm-2.14.02-win32.zip ]
      Expected hash: [ a0f16a9f3b668b086e3c4e23a33ff725998e120f2e3ccac8c28293fd4faeae6fc59398919e1b89eed7461685d2730de02f2eb83e321f73609f35bf6b17a23d1e ]
        Actual hash: [ c0c328968491229bc0c67eb2e92a902e373c89085dc6e0b6e0486037a44888b0631d607e15c25136848d5e902435114404bf18d82feee2dee323b6a9254aa276 ]

  The file may have been corrupted in transit.  This can be caused by
  proxies.  If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY
  environment variables to
  "https://user:password@your-proxy-ip-address:port/".

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:183 (test_hash)
  scripts/cmake/vcpkg_find_acquire_program.cmake:382 (vcpkg_download_distfile)
  ports/openssl-windows/portfile.cmake:27 (vcpkg_find_acquire_program)
  scripts/ports.cmake:79 (include)

Error: Building package openssl-windows:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openssl-windows:x86-windows
  Vcpkg version: 2020.06.15-nohash

**Comment by StarGate-One** [comment]
@4drik 
The SHA512 has is correct, as I just downloaded it from the web address and had the correct hash.
- Try again, it may have been a network glitch, interruption, missed packet, etc.
- If that does not work
  - Click on the link : http://www.nasm.us/pub/nasm/releasebuilds/2.14.02/win32/nasm-2.14.02-win32.zip
  - Once the file is downloaded, put it in your `C:\vcpkg\downloads` directory/folder 
  - cd C:\vcpkg
  - run `vcpkg hash .\downloads\nasm-2.14.02-win32.zip` 
  - the hash should match the `actual hash` mentioned in your original post
  - if the hash matches trying to install the ports/features again
  - if the hash does not match it may require troubleshooting the computer connection to the host www.nasm.us

**Comment by 4drik** [comment]
I understand, thank you. The problem was issued by the antivirus. (Malwarebytes). I disabled it for download time.
Thank you.
