### ISSUE TITLE
libmodbus static version failed to link by console projects

### ISSUE THREAD

**Issue by whidbey** [microsoft/vcpkg#12496]
**Describe the bug**
vcpkg install libmodbus:x86-windows-static and success get the "lib" file.

a simple project with visual studio console. choose static link with office example

would show several "extern symbol unresolve... __imp__modbus_connect " like this
	
A dll version by vcpkg install libmodbus:x86-windows and works fine!.

example file:
```
#include <string.h>
#include <stdlib.h>
#include <errno.h>

#include <modbus.h>
#pragma comment(lib,"uuid.lib")
#pragma comment(lib,"ws2_32.lib")
#pragma comment(lib,"modbus.lib") //same result with absolute dir 
     modbus_t* mb;
    uint16_t tab_reg[32];

    mb = modbus_new_tcp("127.0.0.1", 1502);
    modbus_connect(mb);

    /* Read 5 registers from the address 0 */
    modbus_read_registers(mb, 0, 5, tab_reg);

    modbus_close(mb);
    modbus_free(mb);
 
```

**Environment**
- OS:windows
- Compiler: visual studio 2019

**To Reproduce**
1. ./vcpkg install libmodbus:x86-windows-static
2. create a visual studio simple project.(win32/console)
parse the code above,and compile would show the errors;

Repro code when
[] 
**Expected behavior**

**Failure logs** 
-(please attached failure logs)

**Additional context**

**Comment by Neumann-A** [comment]
> "extern symbol unresolve... __imp__modbus_connect "

`__imp` indicates that the names are mangled for shared linkage and not static linkage. You might need an additional preprocessor definition for static linkage to change some `<somemodbusname>_EXPORT` to nothing instead of `__declspec(dllimport)`.

**Comment by whidbey** [comment]
> 
> 
> > "extern symbol unresolve... __imp__modbus_connect "
> 
> `__imp` indicates that the names are mangled for shared linkage and not static linkage. You might need an additional preprocessor definition for static linkage to change some `<somemodbusname>_EXPORT` to nothing instead of `__declspec(dllimport)`.

yeah ,in fact I can temply drag cppfile to my project to resove it..
but is good if vcpkg package auto doing this...

**Comment by NancyLi1013** [comment]
Hi @whidbey 
Thanks for posting this issue.
I submitted a PR to fix this issue. Could you please try to rebuild if this can work for you?

**Comment by whidbey** [comment]
thanks but I can't see any change in the ports/libmodbus ?
and I git pull all the vcpkg git, complie vcpkg.exe and install again. still the same error

> 
> 
> Hi @whidbey
> Thanks for posting this issue.
> I submitted a PR to fix this issue. Could you please try to rebuild if this can work for you?

**Comment by whidbey** [comment]
here is my manual patch result:

Building package libmodbus[core]:x86-windows-static...
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\ar
ives\93\93d906da97b63acd53a07624968ac15b17de2beb.zip
-- Using community triplet x86-windows-static. This triplet configuration is n
 guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: C:\vcpkg2\triplets\communit
x86-windows-static.cmake
-- Using cached C:/vcpkg2/downloads/stephane-libmodbus-v3.1.6.tar.gz
-- Extracting source C:/vcpkg2/downloads/stephane-libmodbus-v3.1.6.tar.gz
-- Applying patch fix-static-linkage.patch
CMake Error at scripts/cmake/vcpkg_apply_patches.cmake:51 (message):
  Applying patch failed.  error: corrupt patch at line 12

Call Stack (most recent call first):
  scripts/cmake/vcpkg_extract_source_archive_ex.cmake:141 (vcpkg_apply_patches
  scripts/cmake/vcpkg_from_github.cmake:139 (vcpkg_extract_source_archive_ex)
  ports/libmodbus/portfile.cmake:3 (vcpkg_from_github)
  scripts/ports.cmake:79 (include)


Error: Building package libmodbus:x86-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libmodbus:x86-windows-static
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by NancyLi1013** [comment]
@whidbey 
Please rebuild based on this PR #12530. This PR is not merged in master yet.
You can use the following commands:
```
git clone https://github.com/NancyLi1013/vcpkg.git
cd vcpkg
git checkout -b dev/NancyLi/fix-libmodbus origin/dev/NancyLi/fix-libmodbus
```

**Comment by whidbey** [comment]
I follow your instrucment and product errors:

C:\Users\Administrator\vcpkg>.\vcpkg.exe install libmodbus:x86-windows-static
Computing installation plan...
A suitable version of cmake was not found (required v3.17.2). Downloading portab
le cmake v3.17.2...
Downloading cmake...
  https://github.com/Kitware/CMake/releases/download/v3.17.2/cmake-3.17.2-win32-
x86.zip -> C:\Users\Administrator\vcpkg\downloads\cmake-3.17.2-win32-x86.zip
Extracting cmake...
A suitable version of 7zip was not found (required v18.1.0). Downloading portabl
e 7zip v18.1.0...
Downloading 7zip...
  https://www.nuget.org/api/v2/package/7-Zip.CommandLine/18.1.0 -> C:\Users\Admi
nistrator\vcpkg\downloads\7-zip.commandline.18.1.0.nupkg
Extracting 7zip...
A suitable version of nuget was not found (required v5.5.1). Downloading portabl
e nuget v5.5.1...
Downloading nuget...
  https://dist.nuget.org/win-x86-commandline/v5.5.1/nuget.exe -> C:\Users\Admini
strator\vcpkg\downloads\22ea847d-nuget.exe
The following packages will be built and installed:
    libmodbus[core]:x86-windows-static
Warning: The following VS instances are excluded because the English language pa
ck is unavailable.
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community
Please install the English language pack.
Detecting compiler hash for triplet x86-windows-static...
A suitable version of git was not found (required v2.26.2). Downloading portable
 git v2.26.2...
Downloading git...
  https://github.com/git-for-windows/git/releases/download/v2.26.2.windows.1/Por
tableGit-2.26.2-32-bit.7z.exe -> C:\Users\Administrator\vcpkg\downloads\Portable
Git-2.26.2-32-bit.7z.exe
Extracting git...
A suitable version of powershell-core was not found (required v6.2.1). Downloadi
ng portable powershell-core v6.2.1...
Downloading powershell-core...
  https://github.com/PowerShell/PowerShell/releases/download/v6.2.1/PowerShell-6
.2.1-win-x86.zip -> C:\Users\Administrator\vcpkg\downloads\PowerShell-6.2.1-win-
x86.zip
File does not have the expected hash:
             url : [ https://github.com/PowerShell/PowerShell/releases/download/
v6.2.1/PowerShell-6.2.1-win-x86.zip ]
       File path : [ C:\Users\Administrator\vcpkg\downloads\PowerShell-6.2.1-win
-x86.zip.part ]
   Expected hash : [ ab1effc926b000a6adc12198a1886514ec203621a53b0cd7ec1cd9a8225
dccda7e857feaabcfba4004bea73129b986abaad777c4573f44e0af70411226ce08b0 ]
     Actual hash : [ cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36
ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e ]

**Comment by whidbey** [comment]
> 
> 
> @whidbey
> Please rebuild based on this PR #12530. This PR is not merged in master yet.
> You can use the following commands:
> 
> ```
> git clone https://github.com/NancyLi1013/vcpkg.git
> cd vcpkg
> git checkout -b dev/NancyLi/fix-libmodbus origin/dev/NancyLi/fix-libmodbus
> ```
 it works when I copy git from old version and compile your fixed version again.
seems ok now. could please merge into master

**Comment by NancyLi1013** [comment]
Thanks for your so quick update. @whidbey

**Comment by whidbey** [comment]
> 
> 
> Thanks for your so quick update. @whidbey
> We will merge it if all CI checks have passed.

I should thank you as you fixed it :-)
