### ISSUE TITLE
[SQlite3] Missing unofficial:: namespace in generated target. 

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#12505]
Since vcpkg owns the CMake build of sqlite3 and exports the targets via a CMakeLists.txt file in the port folder the target should be namespaced with `unoffical::` like all other targets vcpkg tends to export on its own.

**Comment by PhoebeHui** [comment]
@Neumann-A, thanks for posting this issue!

I have summited a PR https://github.com/microsoft/vcpkg/pull/12516 for fixing this issue.
