### ISSUE TITLE
[vcpkg|manifest] Improve error messages 

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#12501]
The following error did not tell me anything:
```
1> [CMake] Error: There are invalid field types in the CONTROL or manifest file of E:\Repos\StoPhys\vcpkg_manifest\vcpkg.json
1> [CMake] The following fields had the wrong types:
1> [CMake] 
1> [CMake]     dependencies was expected to be an array of dependencies
1> [CMake]     name was expected to be an identifier
1> [CMake] 
```

Solution:
every `"name": "<value>"` field must have a <value> with only lowercase characters. The error message did not really help here.

**Comment by JackBoosY** [comment]
See #12460.

**Comment by linquize** [comment]
What is your `vcpkg.json`?

**Comment by JackBoosY** [comment]
Since #12460 meged, I think I can close this issue.

**Comment by JackBoosY** [comment]
We still have some problems when printing this information in the pipeline, please wait for me to fix it.
