### ISSUE TITLE
Post-build validation fails: "cannot execute LINK.EXE"

### ISSUE THREAD

**Issue by chris-t-w** [microsoft/vcpkg#12507]
**Describe the bug**

The post-build validation step fails with an error.

**Environment**
- OS: Windows 10
- Compiler: Visual Studio 2019 version 14.26.28801

**To Reproduce**
1. `vcpkg.exe install fmt:x64-windows --debug`
2. See error

**Expected behavior**
The build should succeed.

**Failure logs** 

```
Running command:
   "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.26.28801\bin\HostX86\x86\dumpbin.exe" /exports "C:\dev\vcpkg\packages\fmt_x64-windows\debug\bin\fmtd.dll"
 failed
[DEBUG] C:\dev\vcpkg\toolsrc\src\vcpkg\postbuildlint.cpp(397)
```

**Additional context**

If I try to run the command above manually, I receive the error:

```
> "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.26.28801\bin\HostX86\x86\dumpbin.exe" /exports "C:\dev\vcpkg\packages\fmt_x64-windows\debug\bin\fmtd.dll"
DUMPBIN : error : cannot execute LINK.EXE; errno = 0 (2)

> where link.exe
INFO: Could not find files for the given pattern(s).
```

As there is no `LINK.EXE` program on the `PATH`. The command succeeds if I run it within a Visual Studio developer console:

```
> "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Auxiliary\Build\vcvars64.bat"

> where link.exe
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.26.28801\bin\Hostx64\x64\link.exe

> vcpkg.exe install fmt:x64-windows --debug
...
-- Performing post-build validation
-- Performing post-build validation done
...
```

Similarly, running `vcpkg env` also gives me a valid environment.

I've tried it on 3 separate development machines with the same result, so I'm not sure how it works for anybody else.

After a brief look in the source, I see some code that's calling the Visual Studio `vcvarsall.bat` script to set up an environment (e.g. in `make_build_env_cmd`) so I'm guessing that the `dumpbin` program should also be called within the context of that environment?

**Comment by PhoebeHui** [comment]
@chris-t-w, I can't repro this issue locally.

Beofore you manually execute the command, you need set the VS relate environment by executing ""C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"

```
E:\VCPKG\boost_173\vcpkg>"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.6.0
** Copyright (c) 2020 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'

E:\VCPKG\boost_173\vcpkg>where link.exe
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\bin\Hostx64\x64\link.exe

E:\VCPKG\boost_173\vcpkg>"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\bin\HostX86\x86\dumpbin.exe" /exports E:\vcpkg\boost_173\vcpkg\packages\fmt_x64-windows\debug\bin\fmtd.dll
Microsoft (R) COFF/PE Dumper Version 14.26.28805.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file E:\vcpkg\boost_173\vcpkg\packages\fmt_x64-windows\debug\bin\fmtd.dll

File Type: DLL

  Section contains the following exports for fmtd.dll

    00000000 characteristics
    FFFFFFFF time date stamp
        0.00 version
           1 ordinal base
          81 number of functions
          81 number of names

    ordinal hint RVA      name
```

**Comment by chris-t-w** [comment]
> Beofore you manually execute the command, you need set the VS relate environment

@PhoebeHui that was my point: the `dumpbin` command will fail due to `LINK.EXE` not being on the `PATH` unless it is run within a VS environment.

As far as I understand, `vcpkg` does *not* have to be run inside such an environment. Indeed, if I run with `--debug` then I can see that it runs this script itself to get a list of the environment variables (which are presumably used to create a build environment):

```
[DEBUG] CreateProcessW(cmd /c ""C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Auxiliary\Build\vcvarsall.bat" -vcvars_ver=14.2 amd64   2>&1 <NUL" & echo cdARN4xjKueKScMy9C6H& set)
```

This then raises the question, if `dumpbin` has to be run inside a VS environment, how is it supposed to work in the `vcpkg` post-build validation step, which, as far as I can tell, isn't executing with such an environment set up?

Do you have a `LINK.EXE` anywhere on your `PATH` _before_ running `vcvars64.bat`?

As mentioned, I've tried this on three independent environments so I'm confused as to what I'm doing wrong. Here's the powershell script I used on all of them:

```
$vcpkg_dir = "C:\dev\vcpkg"

New-Item -ItemType directory -Path $vcpkg_dir
git clone https://github.com/microsoft/vcpkg $vcpkg_dir
cmd.exe /c "$vcpkg_dir\bootstrap-vcpkg.bat" "-disableMetrics"

[Environment]::SetEnvironmentVariable("VCPKG_ROOT", $vcpkg_dir, "Machine")

& "$vcpkg_dir\vcpkg.exe" install fmt:x64-windows
```

Every time, the same thing:

```
Running command:
   "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.26.28801\bin\HostX86\x86\dumpbin.exe" /exports "C:\dev\vcpkg\packages\fmt_x64-windows\debug\bin\fmtd.dll"
 failed
```

**Comment by PhoebeHui** [comment]
@chris-t-w, vcpkg call vcvarsall.bat to set the VS environments inside, but out of the box, the environments doesn't perserve, so when you execute the command manually, it can not find the LINK.exe.

I don't have LINK.EX before running vcvars64.bat. I tried your powershell script, it works well for me.

So you tried to build it with powershell, Command, and Visual Studio developer console, and only Visual Studio developer console install it successfully, right?

**Comment by chris-t-w** [comment]
After re-installing Visual Studio, the issue seems to have gone away. I'm not really sure what happened, but something seems to have been weird with the linker in the installation.
