### ISSUE TITLE
[librdkafka] build failure

### ISSUE THREAD

**Issue by PversusNP** [microsoft/vcpkg#12519]
**Host Environment**
- OS: Windows 8.1
- Compiler: VS2015

**To Reproduce**
`./vcpkg install librdkafka`

**Failure logs** 
Computing installation plan...
The following packages will be built and installed:
    librdkafka[core]:x86-windows
Warning: The following VS instances are excluded because the English language pack is unavailable.
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
Please install the English language pack.
Detecting compiler hash for triplet x86-windows...
Starting package 1/1: librdkafka:x86-windows
Building package librdkafka[core]:x86-windows...
Could not locate cached archive: C:\Users\Giorgio_Brs\AppData\Local\vcpkg\archives\e5\e5e2a9d2428308245af3df9bd6934b1db
8748d0.zip
-- Downloading https://github.com/edenhill/librdkafka/archive/v1.2.0.tar.gz...
-- Extracting source D:/vcpkg/vcpkg/downloads/edenhill-librdkafka-v1.2.0.tar.gz
-- Applying patch fix-arm64.patch
-- Using source at D:/vcpkg/vcpkg/buildtrees/librdkafka/src/v1.2.0-ded80d4110.clean
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: ninja -v
    Working Directory: D:/vcpkg/vcpkg/buildtrees/librdkafka/x86-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\vcpkg\vcpkg\buildtrees\librdkafka\config-x86-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:300 (vcpkg_execute_required_process)
  ports/librdkafka/portfile.cmake:23 (vcpkg_configure_cmake)
  scripts/ports.cmake:79 (include)

Error: Building package librdkafka:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: librdkafka:x86-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.

**Additional context**
I reinstalled VS2015 SDK.
[config-x86-windows-out.log](https://github.com/microsoft/vcpkg/files/4952791/config-x86-windows-out.log)
[CMakeError.log](https://github.com/microsoft/vcpkg/files/4952794/CMakeError.log)

**Comment by PhoebeHui** [comment]
@PversusNP, do you build the port with VS2019 + VS2015 toolset?

I noticed that below warning from your log. could you install the English language pack, and try again?

Warning: The following VS instances are excluded because the English language pack is unavailable.
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
Please install the English language pack.

**Comment by PversusNP** [comment]
I need to build for VS2015 only, but I also have VS2019 installed.
I installed VS2015 ENU language pack and then reinstalled VS2015 sdk too.

Can you help me?

**Comment by PhoebeHui** [comment]
@PversusNP, you can create community triplet and setting VCPKG_PLATFORM_TOOLSET to v140

.\triplets\community\x86-windows-v140.cmake:
```
set(VCPKG_TARGET_ARCHITECTURE x86)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_PLATFORM_TOOLSET v140)
```
Then execute ./vcpkg install librdkafka:x86-windows-v140.

After install vs2019, open the installer, install the English packs and vs2015 toolset. See
![image](https://user-images.githubusercontent.com/20694052/88263196-36b6dc80-ccfc-11ea-9795-f1e979fbed4e.png)

![image](https://user-images.githubusercontent.com/20694052/88263253-4e8e6080-ccfc-11ea-9633-53aab68635b9.png)

**Comment by PversusNP** [comment]
Thank you Phoebe, it builds!

**Comment by PhoebeHui** [comment]
Great!
