### ISSUE TITLE
[New Port Request] LIEF

### ISSUE THREAD

**Issue by CRC32EX** [microsoft/vcpkg#12511]
Library name:
LIEF

Library description:
LIEF - Library to Instrument Executable Formats

Source repository URL:
https://github.com/lief-project/LIEF

Project homepage (if different from the source repository):
https://lief.quarkslab.com/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by illera88** [comment]
This would be a good addition!
@romainthomas

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by ekilmer** [comment]
FYI looks like there is a PR https://github.com/microsoft/vcpkg/pull/21213 🤞
