### ISSUE TITLE
Cannot install vcpkg

### ISSUE THREAD

**Issue by jagrme00** [microsoft/vcpkg#12520]
Hello,

I am not able to install vcpkg under under Ubuntu 16.04 with the following architecture:
![arch](https://user-images.githubusercontent.com/26929596/88048181-29122300-cb53-11ea-98c2-268fab5f56e1.png)

The steps I took are:
![vcpkg](https://user-images.githubusercontent.com/26929596/88048260-4cd56900-cb53-11ea-897b-106e69bb7bf5.png)

Under an Ubuntu 18.04 virtual machine with an intel processor I was able to install vcpkg. 

Thanks for help!

**Comment by Voskrese** [comment]
aarch = arm64 ?

download cmake arm64

**Comment by jagrme00** [comment]
Yes, aarch64 = arm64.

But how can I force vcpkg to use this new CMake version?
Because CMake was already installed and as you can see in the second screenshot vcpg automatically downloads and installs (a wrong) CMake version.

Is vcpkg looking for some environment variables of CMake to detect if it is already installed or not? Maybe they download was caused because they were not set correctly?

**Comment by StarGate-One** [comment]
1. You could try adding the new cmake directory/bin to the $PATH variable and restart your terminal windows and remove the cmake vcpkg installed -or-
2. untar/unzip the contents of the arm version of cmake and copy it to where vcpkg downloaded the wrong version to

Note: I have not tested this on Linux, but both options do work on windows.

**Comment by jagrme00** [comment]
Thanks for your reply @StarGate-One. 

Unfortunately this happens when I run the bootstrap-vcpkg.sh thus I can not remove the CMake installation automatically downloaded by vcpkg via "vcpkg remove cmake". I think your second point could be a good one. I will test it tomorrow.

**Comment by jagrme00** [comment]
Both solution approaches from @StarGate-One do not work for me. The error is still the same.

**Comment by Voskrese** [comment]
why don't look for a solution to the problem yourself? waiting for someone to help 

https://github.com/microsoft/vcpkg/search?q=aarch64&type=Issues

https://github.com/microsoft/vcpkg/issues/10955

**Comment by jagrme00** [comment]
@Voskrese: You are absolutely right. I overlooked that option... 
The steps mentioned in #3647 does not work for me. But there is definitely a better place to ask for help.
Thanks for your help guys. 

Issue closed.
