### ISSUE TITLE
[New Port Request] arrow-flight

### ISSUE THREAD

**Issue by sltoscano** [microsoft/vcpkg#12526]
Library name: Apache Arrow Flight

Library description: The transport layer for Apache Arrow data format.

Source repository URL: https://github.com/apache/arrow/tree/master/cpp/src/arrow/flight

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
