### ISSUE TITLE
vcpkg manifest mode dependencies not filtered by platform

### ISSUE THREAD

**Issue by linquize** [microsoft/vcpkg#12538]
Currently, vcpkg manifest mode dependencies are not filtered by platform.

Line 761 of `toolsrc/src/vcpkg/install.cpp`

```cpp
                for (auto& dep : (*val)->core_paragraph->dependencies)
                {
                    specs.push_back(FullPackageSpec{
                        {std::move(dep.name), default_triplet},
                        std::move(dep.features),
                    });
                }
```

It should filter by platform in this code block.

This is my `vcpkg.json` in my project.
```json
{
  "name": "sshtest",
  "version-string": "dev",
  "dependencies": [
    {
      "name": "libssh",
      "features": ["mbedtls"],
      "platform": "windows"
    }
  ]
}
```
Run cmake on Linux. Expected libssh is not installed. But actual libssh is still installed.
Run cmake on Windows. Expected libssh is installed. Actual libssh is installed.

**Comment by strega-nil** [comment]
Fixing this now
