### ISSUE TITLE
[tesseract] libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: collate_byname<char>::collate_byname failed to construct for 

### ISSUE THREAD

**Issue by AlejandroCamba** [microsoft/vcpkg#12540]
**Describe the bug**

**Environment**
- OS: [MacOS]
- Compiler: 
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - works

**To Reproduce**
1. ./vcpkg install tesseract
2.  CMakeLists.txt: 
find_package(Tesseract CONFIG REQUIRED)
target_link_libraries(startProject PRIVATE libtesseract)

3. import in main.cpp:
#include <tesseract/baseapi.h>

4. Declare:
tesseract::TessBaseAPI test;

**Expected behavior**
Be able to use tesseract classes

**Failure logs** 
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: collate_byname<char>::collate_byname failed to construct for 

**Additional context**
I'm using opencv and libzippp with vcpkg as well, both compile and work with normality

Complete CMakeLists.txt: 

```
cmake_minimum_required(VERSION 3.0)
project(startProject)

find_package(libzip REQUIRED)
find_package(libzippp CONFIG REQUIRED)
find_package(OpenCV REQUIRED)
find_package(Tesseract CONFIG REQUIRED)

set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED True)

add_executable(startProject main.cpp)
target_link_libraries(startProject PRIVATE libtesseract)
target_link_libraries(startProject PRIVATE zip)
target_link_libraries(startProject PRIVATE libzippp::libzippp)

include_directories( ${OpenCV_INCLUDE_DIRS} )
link_directories( ${OpenCV_LIB_DIR} )

target_link_libraries(startProject PRIVATE ${OpenCV_LIBS})

```

**Comment by PhoebeHui** [comment]
@AlejandroCamba, it looks a locale issue, see https://github.com/microsoft/homebrew-mssql-release/issues/18.

**Comment by PhoebeHui** [comment]
@AlejandroCamba, does this still be a problem for you?

**Comment by PhoebeHui** [comment]
I have confirmed, this is built successfully for me.


```
 cmake_minimum_required(VERSION 3.0)
 project(main)
 set(CMAKE_CXX_STANDARD 11)
 add_executable(main main.cpp)

 find_package(Tesseract CONFIG REQUIRED)
 target_link_libraries(main PRIVATE libtesseract)

```

```
#include <tesseract/baseapi.h>

int main()
{
  tesseract::TessBaseAPI test;
return 0;

```
