### ISSUE TITLE
openblas build failure

### ISSUE THREAD

**Issue by CiaranWelsh** [microsoft/vcpkg#12545]
**Host Environment**
- OS: x86-windows and x64-windows
- Compiler: msvc 2019

**To Reproduce**
`./vcpkg install openblas`

**Failure logs** 
No failure log - the process just hangs:
```
(base) PS D:\vcpkg\ports> vcpkg install openblas
Computing installation plan...
The following packages will be built and installed:
    openblas[core]:x86-windows
Detecting compiler hash for triplet x86-windows...
Starting package 1/1: openblas:x86-windows
Building package openblas[core]:x86-windows...
Could not locate cached archive: C:\Users\Ciaran\AppData\Local\vcpkg\archives\58\5841fb188ad502e5ec0b524dbbda240ae45e2b35.zip
-- Downloading https://github.com/xianyi/OpenBLAS/archive/v0.3.9.tar.gz...
-- Extracting source D:/vcpkg/downloads/xianyi-OpenBLAS-v0.3.9.tar.gz
-- Applying patch uwp.patch
-- Applying patch fix-space-path.patch
-- Applying patch fix-redefinition-function.patch
-- Applying patch github_2481.patch
-- Using source at D:/vcpkg/buildtrees/openblas/src/v0.3.9-c2b94c7c62.clean
-- Configuring x86-windows
```
Nothing more will happen. After killing the console and trying again I get:
```
(base) PS D:\vcpkg\ports> vcpkg install openblas
Computing installation plan...
The following packages will be built and installed:
    openblas[core]:x86-windows
Detecting compiler hash for triplet x86-windows...
Starting package 1/1: openblas:x86-windows
Building package openblas[core]:x86-windows...
Could not locate cached archive: C:\Users\Ciaran\AppData\Local\vcpkg\archives\58\5841fb188ad502e5ec0b524dbbda240ae45e2b35.zip
-- Using cached D:/vcpkg/downloads/xianyi-OpenBLAS-v0.3.9.tar.gz
-- Cleaning sources at D:/vcpkg/buildtrees/openblas/src/v0.3.9-c2b94c7c62.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/vcpkg/downloads/xianyi-OpenBLAS-v0.3.9.tar.gz
-- Applying patch uwp.patch
-- Applying patch fix-space-path.patch
-- Applying patch fix-redefinition-function.patch
-- Applying patch github_2481.patch
-- Using source at D:/vcpkg/buildtrees/openblas/src/v0.3.9-c2b94c7c62.clean
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: ninja -v
    Working Directory: D:/vcpkg/buildtrees/openblas/x86-windows-rel/vcpkg-parallel-configure
    Error code: The process cannot access the file because it is being used by another process
    See logs for more information:
      D:\vcpkg\buildtrees\openblas\config-x86-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:300 (vcpkg_execute_required_process)
  ports/openblas/portfile.cmake:67 (vcpkg_configure_cmake)
  scripts/ports.cmake:79 (include)


Error: Building package openblas:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openblas:x86-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.
```

**Additional context**
I've been able to reproduce the above twice. 

I have successfully been able to build openblas on x64-linux using WSL and it takes only a few moments. 

Using ProcessExplorer, I have been able to trace the process that is hanging to be getarch.exe:

![image](https://user-images.githubusercontent.com/19502680/88305464-759b6100-cd01-11ea-8244-c29b81f1d3d3.png)

**Comment by Voskrese** [comment]
`vcpkg env`

`where getarch`

**Comment by CiaranWelsh** [comment]
```
D:\vcpkg>vcpkg env
Microsoft Windows [Version 10.0.19041.388]
(c) 2020 Microsoft Corporation. All rights reserved.

D:\vcpkg>where getarch
INFO: Could not find files for the given pattern(s).

D:\vcpkg>where getarch.exe
INFO: Could not find files for the given pattern(s).
```
[config-x86-windows-out.log](https://github.com/microsoft/vcpkg/files/4967838/config-x86-windows-out.log)

**Comment by Voskrese** [comment]
> -- Configuring done
> -- Generating done
> -- Build files have been written to: D:/vcpkg/buildtrees/openblas/x86-windows-rel

build error ?

off build parallel

**Comment by CiaranWelsh** [comment]
Like I say, the build "hangs", i.e. does nothing. It doesn't matter how long I leave it to build, it just hangs. On x64-linux it works and builds quickly. 

`off build parallel?` What does this mean?

**Comment by Voskrese** [comment]
https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_install_cmake.md

edit `https://github.com/microsoft/vcpkg/blob/master/ports/openblas/portfile.cmake`

vcpkg_install_cmake(DISABLE_PARALLEL)

> only test

**Comment by CiaranWelsh** [comment]
I changed `vcpkg_install_cmake()` to  `vcpkg_install_cmake(DISABLE_PARALLEL)`. Thanks for the suggestion but it doesn't work. I had to reboot my machine before windows would let me delete the buildtree for openblas (logout did not work, oddly).  Now I get the same hanging behaviour as I did before.

**Comment by Voskrese** [comment]
what application didn't give you to remove the folder?

**Comment by CiaranWelsh** [comment]
File explorer didn't let me remove the folder due to permissions. Looking at ProcessExplorer shows that it was `getarch.exe` that was accessing the folder, preventing me from removing it.

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Do you install antivirus sw on your device? It looks like antivirus sw blocks `getarch.exe`. Could you close antivirus sw and rebuild `openblas`?

**Comment by LilyWangL** [comment]
Pinging @CiaranWelsh for response.

**Comment by CiaranWelsh** [comment]
Sorry @LilyWangL, the last email must have flown under the radar. I uninstalled AVG and the problem was resolved. Thank for the info!
