### ISSUE TITLE
Improve "The package <name> provides CMake targets" hint

### ISSUE THREAD

**Issue by yay** [microsoft/vcpkg#12561]
Currently when one installs a package, say `vcpkg install fmt`, one sees the following message at the end:

```
The package fmt:x64-osx provides CMake targets:

    find_package(fmt CONFIG REQUIRED)
    target_link_libraries(main PRIVATE fmt::fmt fmt::fmt-header-only)
```
Wouldn't it be more helpful if instead of `main` `${PROJECT_NAME}` was used?

```
The package fmt:x64-osx provides CMake targets:

    find_package(fmt CONFIG REQUIRED)
    target_link_libraries(${PROJECT_NAME} PRIVATE fmt::fmt fmt::fmt-header-only)
```

That would prevent substituting `name` for whatever your project is called when copy-pasting the provided targets into the `CMakeLists.txt`.

**Comment by JackBoosY** [comment]
Related code:
https://github.com/microsoft/vcpkg/blob/6bf5adff937abd9bf09fb1c3fda40b5f566f8acd/toolsrc/src/vcpkg/install.cpp#L681
https://github.com/microsoft/vcpkg/blob/6bf5adff937abd9bf09fb1c3fda40b5f566f8acd/toolsrc/src/vcpkg/install.cpp#L690

**Comment by PhoebeHui** [comment]
The PROJECT_NAME is not always to be same with target name, I think that's why it's not used here.
