### ISSUE TITLE
bzip2 build failure

### ISSUE THREAD

**Issue by sandunder** [microsoft/vcpkg#12567]
- OS:windows
- Compiler: msvc

error:
-- Using cached D:/vcpkg-master/downloads/bzip2-1.0.6.tar.gz
-- Cleaning sources at D:/vcpkg-master/buildtrees/bzip2/src/1.0.6-8838f21f8e.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/vcpkg-master/downloads/bzip2-1.0.6.tar.gz
-- Applying patch fix-import-export-macros.patch
-- Applying patch fix-windows-include.patch
-- Using source at D:/vcpkg-master/buildtrees/bzip2/src/1.0.6-8838f21f8e.clean
-- Configuring x64-windows-static
-- Building x64-windows-static-dbg
-- Building x64-windows-static-rel
-- Fixing pkgconfig
-- Acquiring MSYS Packages...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: D:/vcpkg-master/downloads/tools/msys2/msys64/usr/bin/bash.exe --noprofile --norc -c "pacman -S --noconfirm --needed pkg-config"
    Working Directory: D:/vcpkg-master/downloads/tools/msys2
    Error code: 1
    See logs for more information:
      D:\vcpkg-master\buildtrees\bzip2\msys-pacman-x64-windows-static-err.log
Call Stack (most recent call first):
  scripts/cmake/vcpkg_acquire_msys.cmake:127 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:281 (vcpkg_acquire_msys)
  ports/bzip2/portfile.cmake:51 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:79 (include)

buildtrees/bzip2/msys-pacman-x64-windows-static-err.log:
error: msys: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" is unknown
error: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" could not be looked up remotely
error: database 'msys' is not valid (invalid or corrupted database (PGP signature))

**Comment by rogerd007** [comment]
Related to #12288 I believe.

**Comment by sandunder** [comment]
I run this command:
`D:/vcpkg-master/downloads/tools/msys2/msys64/usr/bin/bash.exe --noprofile --norc -c "pacman -S --noconfirm --needed pkg-config"`
and here is the error:
`bash: pacman: command not found`

**Comment by sandunder** [comment]
I edit `/etc/pacman.conf`,and let `SigLevel` be `Never`,then it been corrected!

**Comment by c72578** [comment]
Related PR, which fixes these key issues: #12467

**Comment by anticrisis** [comment]
> I edit `/etc/pacman.conf`,and let `SigLevel` be `Never`,then it been corrected!

This worked for me, though I gather it means signatures will not be verified. The file is in `vcpkg/downloads/tools/msys2/msys64/etc/pacman.conf`

**Comment by zhangjiayin** [comment]
> > I edit `/etc/pacman.conf`,and let `SigLevel` be `Never`,then it been corrected!
> 
> This worked for me, though I gather it means signatures will not be verified. The file is in `vcpkg/downloads/tools/msys2/msys64/etc/pacman.conf`
works for me
