### ISSUE TITLE
Application program fails to link python library

### ISSUE THREAD

**Issue by timluther** [microsoft/vcpkg#12570]
**Describe the bug**
When compiling my application project, I'm greeted with the following message:

Error	LNK1104	cannot open file 'python37_d.lib'	AnthracitePlayer	

which is odd because I couldn't find where it was being linked, which led me to surmise that it was being linked by vcpkg magic.

**Environment**
- OS Name:                   Microsoft Windows 10 Home                                             
  OS Version:                10.0.18362 N/A Build 18362                                            
  System Type:               x64-based PC                                                          
  Processor(s):               Intel64 Family 6 Model 45 Stepping 7 GenuineIntel ~3201 Mhz     
  Total Physical Memory:     16,325 MB
- Compiler: Visual C++ 2019   00435-60000-00000-AA259

**To Reproduce**
Compile program that includes "python.h"

**Expected behavior**
Compiles cleanly

**Failure logs** 
Error	LNK1104	cannot open file 'python37_d.lib'	AnthracitePlayer	

**Additional context**

Performing this command on my system:

copy  e:\%VCPKG_ROOT%\installed\x64-windows\debug\lib\python38_d.lib  e:\prog\%VCPKG_ROOT%\installed\x64-windows\debug\lib\python37_d.lib

functions as a work around to the issue, correctly linking python38_d.dll only with an aliased library file. This leads me to suspect that the error is simply an additional explicit reference to the python library file that hasn't been updated with the version change.

**Comment by JackBoosY** [comment]
Hi @timluther, thanks for reporting this issue.
Sadly, I can' repro this issue. Please rerun integrate command and try again.

Thanks.

**Comment by JackBoosY** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.
