### ISSUE TITLE
Port request: PCL (point cloud library)

### ISSUE THREAD

**Issue by jasjuang** [Microsoft/vcpkg#1257]
PCL is a very useful computer vision library https://github.com/PointCloudLibrary/pcl, and building PCL from source on windows is very difficult most of the times. It would be very helpful to have this in vcpkg. 

@UnaNancyOwen would you be able to modify your Windows pre-built work to support this?

**Comment by UnaNancyOwen** [comment]
In general configuration, the PCL requires these dependent libraries.
But, The some libraries (FLANN, QHull, OpenNI2) are not included in vcpkg yet.
First, the vcpkg should be support these libraries for build PCL.

- [x] Boost
- [x] Eigen
- [ ] FLANN
- [ ] QHull
- [x] VTK
- [ ] OpenNI2

@jasjuang Is there anything I can do to help?

**Comment by jasjuang** [comment]
@UnaNancyOwen I saw two pull requests for FLANN and QHull which should be merged anytime soon. That means only OpenNI2 is left. Would you be able to add OpenNI2 to vcpkg and then add PCL?  I am still investigating on how to use the vcpkg api to create a package so I can contribute to the other open source libraries that I can successfully build on Windows.

**Comment by UnaNancyOwen** [comment]
@jasjuang Yes, I'll work on it, after those libraries have been added to vcpkg.

**Comment by UnaNancyOwen** [comment]
FLANN and QHull able to be installed using #1263 without problems.
```
# success
vcpkg install flann:x64-windows-static

# success
vcpkg install qhull:x64-windows-static
```

But, VTK installation will fail, because building Qt5 has failed.
Qt5 is dependency library that specified in VTK package.
Do you know something about it?
```
# failed
# This command is called in install VTK package. (vcpkg install vtk:x64-windows-static)
# But, the following error will be displayed and package install process has failed.
# Error: Building package qt5:x64-windows-static failed with: BUILD_FAILED
vcpkg install qt5:x64-windows-static
```

**Comment by jasjuang** [comment]
@UnaNancyOwen I ran into problems when installing vtk but #739 solves it for me, but I believe I am building the shared version because I ran `vcpkg install qt5:x64-windows` instead of `vcpkg install qt5:x64-windows-static`. Is there a reason why you prefer the static version?

**Comment by UnaNancyOwen** [comment]
@jasjuang Thanks, I will try with dynamic version.

**Comment by mmazat** [comment]
I was trying to add PCL port, but vtk fails in vs 2017 :(

**Comment by jasjuang** [comment]
@mmazat Are you be able to build VTK from source? I checked the issues at [VTK](https://gitlab.kitware.com/vtk/vtk/issues) and it seems that no one reported any compilation problems in VS 2017

**Comment by mmazat** [comment]
@jasjuang vtk7.1 with vs 2015 had no problem for me, I'm trying vtk7.1 +vs 2017 now, but it should be fine

**Comment by mmazat** [comment]
yeap I just checked and vtk7.1 builds with no problem by vs 2017

**Comment by UnaNancyOwen** [comment]
I sent a pull-request (#1283) that including temporary changes.
```
vcpkg install pcl:x64-windows
```

But, It have still some problems.

* Some modules require C++ version (flann_cpp) of FLANN.
  But, the current FLANN port does not install it.

* PCL need add OpenNI2 port to vcpkg for support OpenNI2 grabber.

* VTK port fails to install when choose static-link version.
  ```
  # failed
  vcpkg install vtk:x64-windows-static
  ```

**Comment by seanlis** [comment]
the FLANN port I am using:
https://github.com/seanlis/vcpkg/commit/e8b87926911d99b41620d88f9f61ed540cc488ef

It added building of flann_cpp and dll.

**Comment by UnaNancyOwen** [comment]
@seanlis Thanks, It is amazing! :)
I confirmed that flann_cpp will be generated and installed.
Please apply the following fix in order to remove unnecessary files.
And, Please send a pull request.

[portfile.cmake#L32-L34](https://github.com/seanlis/vcpkg/blob/master/ports/flann/portfile.cmake#L32-L34)
```cmake
if(VCPKG_LIBRARY_LINKAGE STREQUAL static)
    file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/bin ${CURRENT_PACKAGES_DIR}/debug/bin)
    file(REMOVE ${CURRENT_PACKAGES_DIR}/lib/flann.lib ${CURRENT_PACKAGES_DIR}/debug/lib/flann.lib)
    file(REMOVE ${CURRENT_PACKAGES_DIR}/lib/flann_cpp.lib ${CURRENT_PACKAGES_DIR}/debug/lib/flann_cpp.lib)
elseif(VCPKG_LIBRARY_LINKAGE STREQUAL dynamic)
    file(REMOVE ${CURRENT_PACKAGES_DIR}/lib/flann_s.lib ${CURRENT_PACKAGES_DIR}/debug/lib/flann_s.lib)
    file(REMOVE ${CURRENT_PACKAGES_DIR}/lib/flann_cpp_s.lib ${CURRENT_PACKAGES_DIR}/debug/lib/flann_cpp_s.lib)
endif()
```

**Comment by UnaNancyOwen** [comment]
Fixed PR #1283 to build modules that require flann_cpp.
Please review it.

**Comment by UnaNancyOwen** [comment]
* pcl_surface module always require "qhullstatic.lib" on Windows.
But, the current QHull port does not install it.

**Comment by seanlis** [comment]
Right now, as a workaround, you have to add `-DCMAKE_BUILD_TYPE=Release` to cmake in order to detect the release version.

**Comment by UnaNancyOwen** [comment]
I sent a pull-request (#1309) that add OpenNI2 port.
It is first version for add OpenNI2.
Please review it. (Most probably, It is included the some bugs.)

**Comment by UnaNancyOwen** [comment]
PCL port (#1283) supported OpenNI2.
The almost all of the main problems has been fixed.
I think the PCL port will be ready to merge after your review.
Please review it.

The remaining problems is about other ports.
That problems is following.

* pcl_surface module require "qhullstatic.lib" on Windows.
But, the current QHull port does not install it.

* VTK port fails to install when choose static-link version, because building Qt5 has failed.

Thanks,

**Comment by UnaNancyOwen** [comment]
Probably, the PCL 1.8.1 release is coming soon.
In that case, The patch that the PCL port should apply is minimized.
And, It's not necessary to remove pcl_2d_release.dll and pcl_2d_debug.dll, because It's not generated in this version.
These make the port to very simple. Also, The port maintenance will be easy in future.
Do you think we should wait for a while?

**Comment by jasjuang** [comment]
@UnaNancyOwen  When is 1.8.1 coming out? I think a lot of people will like to have 1.8.0. We can always update it to 1.8.1 when it comes out. I will review #1283 as soon as possible.

**Comment by UnaNancyOwen** [comment]
@jasjuang Please look at the [PCL 1.8.1 milestone](https://github.com/PointCloudLibrary/pcl/milestone/5).
All major issues are closed.
The release date is not specified, but I think PCL 1.8.1 will be released soon.

**Comment by UnaNancyOwen** [comment]
It seems difficult to support static triplet of the Qt port.
We should be consider that removing Qt option from the VTK port.
If it is not possible, the PCL port can't support static triplet.

**Comment by KindDragon** [comment]
@albertziegenhagel Hi. Do you need Qt option in VTK?

**Comment by albertziegenhagel** [comment]
Yes, I actually do need Qt support in VTK. I usually build everything as shared libraries, so there was no problem on my system.

I don't know whether deactivating dependencies is the right thing to do here. I think Qt should actually be fixed to work as static library. Of course feature packages #1205 would come in handy here.

**Comment by UnaNancyOwen** [comment]
PCL 1.8.1 RC1 has been released.
I updated the PCL port to PCL 1.8.1 RC1 from PCL 1.8.0.
Please review it.

I will update this port to PCL 1.8.1 from PCL 1.8.1 RC when PCL 1.8.1 is officially released.
I think that this port ready to merge at that time.
Thanks,

**Comment by Voskrese** [comment]
@UnaNancyOwen примените исправление и проверьте у себя https://github.com/Microsoft/vcpkg/issues/1430
у меня на shared x86 у меня VTK скомпилировался с поддержкой QT
если все ок, пожно оформлять патчем, к сожалению я сам еще не разобрался с git

> apply the hotfix and check host https://github.com/Microsoft/vcpkg/issues/1430
> I have a shared 86 I VTK skompilirovalsja with support for QT
> If everything is OK, dine arrange patch, unfortunately I myself haven't figured out with git

**Comment by UnaNancyOwen** [comment]
PCL port has been merged. Please close this issue.
If you found problems, Please open new issues.
Thanks,

**Comment by jasjuang** [comment]
Thanks a lot for the great work. I will report back if there issue with the port.
