### ISSUE TITLE
[tbb] Switch to better CMake build system

### ISSUE THREAD

**Issue by longnguyen2004** [microsoft/vcpkg#12575]
****

**Is your feature request related to a problem? Please describe.**
TBB CMake build system assumes that MSVC is the only compiler used on Windows, which is obviously not true. I've reported this to the team but haven't gotten any answers. MinGW support in TBB seems unfinished imo (linking directly with DLLs is just so wrong), but it's there, and the MSYS2 team had got it working [with some patches](https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-intel-tbb). Can someone here try to add MinGW support to this port?

**Comment by longnguyen2004** [comment]
Since the current TBB build system is a nightmare to deal with, can we switch to https://github.com/wjakob/tbb for a better CMake build system? That way we can just do `vcpkg_configure_cmake` for all targets and not having to worry about other stuff.

**Comment by autoantwort** [comment]
Can be closed
