### ISSUE TITLE
cairo

### ISSUE THREAD

**Issue by vinayvinnujash** [microsoft/vcpkg#12574]
**Host Environment**
- OS: Windows
- Compiler: revision

**To Reproduce**
Steps to reproduce the behavior:`.  /vcpkg install cairo 

**Failure logs** 

PS C:\src\vcpkg\vcpkg> .\vcpkg.exe install cairo                                                                        Computing installation plan...
The following packages will be built and installed:
  * bzip2[core]:x86-windows
    cairo[core]:x86-windows
  * dirent[core]:x86-windows
  * expat[core]:x86-windows
  * fontconfig[core]:x86-windows
  * freetype[bzip2,core,png]:x86-windows
  * libiconv[core]:x86-windows
  * libpng[core]:x86-windows
  * pixman[core]:x86-windows
  * zlib[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x86-windows...
Starting package 1/10: bzip2:x86-windows
Building package bzip2[core]:x86-windows...
Could not locate cached archive: C:\Users\ash\AppData\Local\vcpkg\archives\37\37e5ae6003e363d13acddbe5ed6277c0775bad67.zip
-- Using cached C:/src/vcpkg/vcpkg/downloads/bzip2-1.0.6.tar.gz
-- Cleaning sources at C:/src/vcpkg/vcpkg/buildtrees/bzip2/src/1.0.6-8838f21f8e.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/src/vcpkg/vcpkg/downloads/bzip2-1.0.6.tar.gz
-- Applying patch fix-import-export-macros.patch
-- Applying patch fix-windows-include.patch
-- Using source at C:/src/vcpkg/vcpkg/buildtrees/bzip2/src/1.0.6-8838f21f8e.clean
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Fixing pkgconfig
CMake Error at scripts/cmake/vcpkg_fixup_pkgconfig.cmake:279 (find_program):
  Could not find PKGCONFIG using the following names: pkg-config
Call Stack (most recent call first):
  ports/bzip2/portfile.cmake:51 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:79 (include)

Error: Building package bzip2:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: bzip2:x86-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.

**Additional context**

I have tried to comment out  "vcpkg_fixup_pkgconfig()", which seemed to work fine at that instance. But later I was facing issues with "find_package(io2d REQUIRED)"

It said that, it cant find io2d or io2dConfig.cmake files.   Literally, I was up all night, for around 8 hours trying to solve this issue. Having no knowledge about vcpkg or cmake, I came here for help.

Thanks in advance.

**Comment by StarGate-One** [comment]
Duplicate - See #12565
**Could not find PKGCONFIG using the following names: pkg-config**

**Comment by NancyLi1013** [comment]
Hi @vinayvinnujash 
Thanks for posting this issue.

 For the issue caused by` vcpkg_fixup_pkgconfig()`, there is a PR #12568 to fix it.

 For the issue caused by `io2d`, it seems that there is no any ports that need to depend on `io2d`. Is your project that is required for `io2d`?

You might need to run ./vcpkg integrate install and then add -DCMAKE_TOOLCHAIN_FILE=_VCPKG_ROOT/vcpkg/scripts/buildsystems/vcpkg.cmake_.
