### ISSUE TITLE
[tinygltf] update to v2.4.0

### ISSUE THREAD

**Issue by daemyung** [microsoft/vcpkg#12578]
Library name: tinygltf

New version number: v2.4.0

Other information that may be useful (release notes, etc...)
The current viersion is v.2.2.0 so some critical codes are missing.

v2.4.0 Experimental RapidJSON support. Experimental C++14 support(C++14 may give better performance)
v2.3.0 Modified Material representation according to glTF 2.0 schema(and introduced TextureInfo class)

You can check more detail information at https://github.com/syoyo/tinygltf

**Comment by JonLiu1993** [comment]
@daemyung Version 2.4.0 has not been released yet, we will update it as soon as possible after release

**Comment by daemyung** [comment]
@JonLiu1993 Then could you update to v2.3.0?

**Comment by JonLiu1993** [comment]
@daemyung Sorry, version 2.3.0 has not been released, the latest version is 2.2.0

**Comment by daemyung** [comment]
@JonLiu1993 It's strange... because v2.4.2 is released and I can see on the code. I think vcpkg tracks the version from git tags. I have raised up the issue on tinygltf(https://github.com/syoyo/tinygltf/issues/282). Please update after this issue is done. Thanks for your help.

**Comment by daemyung** [comment]
@JonLiu1993 I have talked with syoyo who is maintainer of tinygltf. tinygltf doesn't support vcpkg officially so you can update tinygltf in vcpkg by yourself. Please update it to v2.4.2.
