### ISSUE TITLE
[New Port Request] olcPixelGameEngine

### ISSUE THREAD

**Issue by Spejik** [microsoft/vcpkg#12580]
Library name: olcPixelGameEngine

Library description: An cross-platform pixel drawing and user interface framework

Source repository URL: https://github.com/OneLoneCoder/olcPixelGameEngine

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
There are some [extensions](https://github.com/OneLoneCoder/olcPixelGameEngine/tree/master/Extensions) available

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
