### ISSUE TITLE
zlib:x64-windows build failure

### ISSUE THREAD

**Issue by Hydr4bytes** [microsoft/vcpkg#12582]
**Host Environment**
- OS: Windows
- Compiler: revision

**To Reproduce**
`./vcpkg install zlib:x64-windows`

**Failure logs** 
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: C:/dev/vcpkg/downloads/tools/msys2/msys64/usr/bin/bash.exe --noprofile --norc -c "pacman -S --noconfirm --needed pkg-config"
    Working Directory: C:/dev/vcpkg/downloads/tools/msys2
    Error code: 1
    See logs for more information:
      C:\dev\vcpkg\buildtrees\zlib\msys-pacman-x64-windows-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_acquire_msys.cmake:127 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:281 (vcpkg_acquire_msys)
  ports/zlib/portfile.cmake:46 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:79 (include)

Error: Building package zlib:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zlib:x64-windows
  Vcpkg version: 2020.06.15-nohash

**Comment by StarGate-One** [comment]
Please attache/upload the file `C:\dev\vcpkg\buildtrees\zlib\msys-pacman-x64-windows-err.log` to this issue for review and possible corrective actions.

**Comment by amrosado** [comment]
I'm having a similar issue and I've been trying to figure it out.  I believe the output might look like this.

```
error: mingw32: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" is unknown
error: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" could not be looked up remotely
error: mingw64: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" is unknown
error: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" could not be looked up remotely
error: msys: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" is unknown
error: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" could not be looked up remotely
error: database 'mingw32' is not valid (invalid or corrupted database (PGP signature))
error: database 'mingw64' is not valid (invalid or corrupted database (PGP signature))
error: database 'msys' is not valid (invalid or corrupted database (PGP signature))

```

**Comment by Goddard** [comment]
Also effects me.

**Comment by BenKey** [comment]
I am getting the same issue when building ICU.

**Comment by StarGate-One** [comment]
See #12565 Down where @ImmaturityRules mentions they had to modify `<vcpkg-root>\scripts\cmake\vcpkg_acquire_msys.cmake` adding the crypto keyrings allowing MSYS to download the appropriate packages, by attaching it to the post https://raw.githubusercontent.com/yasamoka/vcpkg/abc0b68bb24ea0a552a36826950b246288b61c75/scripts/cmake/vcpkg_acquire_msys.cmake.
I downloaded it and replaced it on my system and I was allowed to download the required components.

**Comment by StarGate-One** [comment]
See #12565 - There are 2 issues:
1. `vcpkg_fixup_pkconfig.cmake` needs to be reworked - PR #12569 is in the works but in the mean time you can make the changes shown by myself @StarGate-One to the script found in `<vcpkg-root>\scripts\cmake` to temporarily fix this issue. 
[vcpkg_fixup_pkgconfig.cmake.txt](https://github.com/microsoft/vcpkg/files/4978792/vcpkg_fixup_pkgconfig.cmake.txt)

2. `vcpkg_acquire_msys.cmake` needs to have the MSYS/mingw crypto keyrings added, @ImmaturityRules has attached a copy to this same issue which fix this issue, but a PR needs to be done with those changes. You can download dthe file and put it in the same location `<vcpkg-root>\scripts\cmake` to temporarily fix this issue. 
[vcpkg_acquire_msys.cmake.txt](https://github.com/microsoft/vcpkg/files/4978796/vcpkg_acquire_msys.cmake.txt)

I have attached a copy of both, download, remove the .txt extension and copy to `<vcpkg-root>\scripts\cmake` folder and it should work.

**Comment by PhoebeHui** [comment]
We have a exist PR #12467 to fix this issue,  appreciate your effort very much.

**Comment by prokotg** [comment]
Same MSYS2 thing withm Glibmm, just leting know

**Comment by kcgen** [comment]
@strega-nil , can you reopen this? This issue is still affecting CI workflows today (4 days after it was closed): https://github.com/dosbox-staging/dosbox-staging/issues/524

The manual work-around posted by @StarGate-One above are a start to getting this fixed, but until they're tested, integrated into the production code-base, and are proven to be passing by end-users, then the issue should stay open.  

Because this affects zlib, the ripple effect has been quite massive - with GitHub CI workflows tanking almost everywhere that uses vcpkg.  Can't wait for the fix! thank you all.
