### ISSUE TITLE
[vcpkg_acquire_msys] build failure with "error: failed to update mingw32/mingw64  (invalid or corrupted database (PGP signature))"

### ISSUE THREAD

**Issue by StarGate-One** [microsoft/vcpkg#12584]
**Host Environment**
- OS: Windows 10
- Compiler: N/A

**To Reproduce**
`./vcpkg install <any port needing MSYS ming32/ming64 to build port>`

**Failure logs** 
- Cut and past the appropriate build messages from the console output.
See #12565 #12582 #12583 

- Please attach any additional failure logs mentioned in the console output.
See #12565 #12582 #12583

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.
These occurred after latest update to vcpkg #11550 Commit 458c20e

@ImmaturityRules created version containing allowable PGP keys - attached: 
[vcpkg_acquire_msys.cmake.txt](https://github.com/microsoft/vcpkg/files/4978829/vcpkg_acquire_msys.cmake.txt)

**Comment by ImmaturityRules** [comment]
For the record, I didn't create the script I linked, that was @yasamoka.

**Comment by StarGate-One** [comment]
Thanks to you and @yasamoka

**Comment by yasamoka** [comment]
I believe that the script I modified to work on Friday is the same as the one currently in the already open keyring issue. It's been fixed and hopefully the PR should be accepted come Monday.
