### ISSUE TITLE
Building Opencv4 is successful but doesn't download opencv_ffmpeg.dll and gives no error until you try to use video capture

### ISSUE THREAD

**Issue by ferjif** [microsoft/vcpkg#12587]
**The Bug is**
I recently installed opencv and it built and installed fine. but the problem is the opencv_ffmpeg.dll didn't download. I used both x86 and x64 windows triplets but still the file wasn't downloaded.
**Environment**
- OS: windows 10
- Compiler: MSVC 19
**To Reproduce**
1. ./vcpkg install opencv opencv[ffmpeg]
2. No errors builds just fine

**Expected behavior**
Opencv builds successfully and you can use it just fine until you want to use cv::VideoCapture(idx, cv::CAP_FFMPEG) which fails to open a capture object

**Comment by JackBoosY** [comment]
Hi @ferjif, thanks for reporting this issue.
Could you try #11130 changes?

Thanks.

**Comment by ferjif** [comment]
ok. i'll try it and get back to you. 
Thanks

**Comment by ferjif** [comment]
@JackBoosY sorry i didn't have time to use the pull request but the prebuilt version from opencv even with opencv_ffmpeg.dll failed to use it. so i used cv::CAP_ANY and it worked on both the vcpkg version and the prebuilt version from sourceforge.

**Comment by JackBoosY** [comment]
@cenit What do you think?

**Comment by cenit** [comment]
opencv_ffmpeg.dll is a custom ffmpeg build. You cannot find it inside vcpkg, because we use the normal ffmpeg build which is a superset of it (we have aligned windows with Linux and osx, where libopencv_ffmpeg never existed)
