### ISSUE TITLE
[qt5-declarative] build failure

### ISSUE THREAD

**Issue by thisptr-hub** [microsoft/vcpkg#12591]
**Host Environment**
- OS: WSL2 Ubuntu 20.04 on Windows 10
- Compiler: g++ (Ubuntu 9.3.0-10ubuntu2) 9.3.0, GNU ld (GNU Binutils for Ubuntu) 2.34
- Vcpkg package management program version 2020.06.15-unknownhash

**To Reproduce**
`./vcpkg install qt5-declarative:x64-linux`

**Failure logs** 

> Computing installation plan...
> The following packages will be built and installed:
>     qt5-declarative[core]:x64-linux
> Detecting compiler hash for triplet x64-linux...
> Starting package 1/1: qt5-declarative:x64-linux
> Building package qt5-declarative[core]:x64-linux...
> Could not locate cached archive: /home/vgromov/.cache/vcpkg/archives/56/56a3582070ada91546e682e5be82067426639868.zip
> -- Using cached /home/vgromov/devenv/vcpkg/downloads/qtdeclarative-everywhere-src-5.15.0.tar.xz
> -- Cleaning sources at /home/vgromov/devenv/vcpkg/buildtrees/qt5-declarative/src/5.15.0-ba8b6ef309.clean. Use --editable to skip cleaning for the packages you specify.
> -- Extracting source /home/vgromov/devenv/vcpkg/downloads/qtdeclarative-everywhere-src-5.15.0.tar.xz
> -- Using source at /home/vgromov/devenv/vcpkg/buildtrees/qt5-declarative/src/5.15.0-ba8b6ef309.clean
> -- Configuring x64-linux-rel
> -- Configuring x64-linux-rel done
> -- Configuring x64-linux-dbg
> -- Configuring x64-linux-dbg done
> -- Package build-x64-linux-dbg
> CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
>     Command failed: /usr/bin/make -j 17
>     Working Directory: /home/vgromov/devenv/vcpkg/buildtrees/qt5-declarative/x64-linux-dbg
>     Error code: 2
>     See logs for more information:
>       [/home/vgromov/devenv/vcpkg/buildtrees/qt5-declarative/package-build-x64-linux-dbg-out.log]
>       /home/vgromov/devenv/vcpkg/buildtrees/qt5-declarative/package-build-x64-linux-dbg-err.log
> Call Stack (most recent call first):
>   scripts/cmake/vcpkg_build_qmake.cmake:31 (vcpkg_execute_required_process)
>   scripts/cmake/vcpkg_build_qmake.cmake:66 (run_jom)
>   installed/x64-linux/share/qt5/qt_build_submodule.cmake:12 (vcpkg_build_qmake)
>   installed/x64-linux/share/qt5/qt_submodule_installation.cmake:8 (qt_build_submodule)
>   ports/qt5-declarative/portfile.cmake:2 (qt_submodule_installation)
>   scripts/ports.cmake:79 (include)
> 
> 
> Error: Building package qt5-declarative:x64-linux failed with: BUILD_FAILED
> Please ensure you're using the latest portfiles with `.\vcpkg update`, then
> submit an issue at https://github.com/Microsoft/vcpkg/issues including:
>   Package: qt5-declarative:x64-linux
>   Vcpkg version: 2020.06.15-unknownhash
> 
> Additionally, attach any relevant sections from the log files above.

[package-build-x64-linux-dbg-err.log](https://github.com/microsoft/vcpkg/files/4980589/package-build-x64-linux-dbg-err.log)
[package-build-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/4980590/package-build-x64-linux-dbg-out.log)

**Comment by JackBoosY** [comment]
@Neumann-A Could you please take a look?

Thanks.

**Comment by Neumann-A** [comment]
@JackBoosY `exhaustedmemory` does not look like something I am able to fix

**Comment by PhoebeHui** [comment]
Similar issue with qt5 bug https://bugreports.qt.io/browse/QTBUG-87117, I tried the patch, however it doesn't work.

**Comment by JackBoosY** [comment]
```
Cannot open foreign types file /home/vgromov/devenv/vcpkg/installed/x64-linux/debug/lib/metatypes/qt5network_metatypes.json
/usr//binusr//ldbin:/ ld/:home //vgromovhome//devenvvgromov//vcpkgdevenv//installedvcpkg//x64installed-/linuxx64/-debuglinux//libdebug//libQt5Core.alib:/ libQt5Core.aerror:  addingerror  symbolsadding:  symbolsmemory:  exhaustedmemory
 exhausted
```
Please make sure you have enough memeory and disk.
