### ISSUE TITLE
[wangle>] build failure

### ISSUE THREAD

**Issue by yangjiechina** [microsoft/vcpkg#12599]
**Host Environment**
- OS: windows10
- Compiler: Visual Studio 2017

**To Reproduce**
` .\vcpkg.exe install wangle:x64-windows`

**Failure logs** 
Computing installation plan...
The following packages will be built and installed:
  * boost-algorithm[core]:x64-windows
  * boost-any[core]:x64-windows
  * boost-atomic[core]:x64-windows
  * boost-build[core]:x64-windows
  * boost-chrono[core]:x64-windows
  * boost-container[core]:x64-windows
  * boost-container-hash[core]:x64-windows
  * boost-context[core]:x64-windows
  * boost-conversion[core]:x64-windows
  * boost-crc[core]:x64-windows
  * boost-date-time[core]:x64-windows
  * boost-endian[core]:x64-windows
  * boost-exception[core]:x64-windows
  * boost-filesystem[core]:x64-windows
  * boost-foreach[core]:x64-windows
  * boost-function[core]:x64-windows
  * boost-function-types[core]:x64-windows
  * boost-functional[core]:x64-windows
  * boost-fusion[core]:x64-windows
  * boost-integer[core]:x64-windows
  * boost-intrusive[core]:x64-windows
  * boost-io[core]:x64-windows
  * boost-iostreams[core]:x64-windows
  * boost-iterator[core]:x64-windows
  * boost-lambda[core]:x64-windows
  * boost-lexical-cast[core]:x64-windows
  * boost-locale[core]:x64-windows
  * boost-math[core]:x64-windows
  * boost-modular-build-helper[core]:x64-windows
  * boost-move[core]:x64-windows
  * boost-mp11[core]:x64-windows
  * boost-mpl[core]:x64-windows
  * boost-multi-index[core]:x64-windows
  * boost-numeric-conversion[core]:x64-windows
  * boost-optional[core]:x64-windows
  * boost-phoenix[core]:x64-windows
  * boost-pool[core]:x64-windows
  * boost-predef[core]:x64-windows
  * boost-program-options[core]:x64-windows
  * boost-proto[core]:x64-windows
  * boost-range[core]:x64-windows
  * boost-ratio[core]:x64-windows
  * boost-rational[core]:x64-windows
  * boost-regex[core]:x64-windows
  * boost-serialization[core]:x64-windows
  * boost-smart-ptr[core]:x64-windows
  * boost-spirit[core]:x64-windows
  * boost-system[core]:x64-windows
  * boost-thread[core]:x64-windows
  * boost-tokenizer[core]:x64-windows
  * boost-tuple[core]:x64-windows
  * boost-type-index[core]:x64-windows
  * boost-typeof[core]:x64-windows
  * boost-unordered[core]:x64-windows
  * boost-utility[core]:x64-windows
  * boost-variant[core]:x64-windows
  * boost-winapi[core]:x64-windows
  * bzip2[core]:x64-windows
  * double-conversion[core]:x64-windows
  * fizz[core]:x64-windows
  * fmt[core]:x64-windows
  * folly[core,zlib]:x64-windows
  * liblzma[core]:x64-windows
  * libsodium[core]:x64-windows
  * openssl[core]:x64-windows
  * openssl-windows[core]:x64-windows
    wangle[core]:x64-windows
  * zlib[core]:x64-windows
  * zstd[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Starting package 1/69: boost-build:x64-windows
Building package boost-build[core]:x64-windows...
Could not locate cached archive: C:\Users\yangjie\AppData\Local\vcpkg\archives\33\337b5c572ceefa71334c0432c78e863ac8172598.zip
-- Using cached E:/code/vcpkg-master/downloads/boostorg-build-boost-1.73.0.tar.gz
-- Cleaning sources at E:/code/vcpkg-master/buildtrees/boost-build/src/ost-1.73.0-018fb008dd.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/code/vcpkg-master/downloads/boostorg-build-boost-1.73.0.tar.gz
-- Using source at E:/code/vcpkg-master/buildtrees/boost-build/src/ost-1.73.0-018fb008dd.clean
-- Using cached E:/code/vcpkg-master/downloads/boost_LICENSE_1_0.txt
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.73.0/boostcpp.jam...
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.73.0/boostcpp.jam... Failed. Status: 6;"Couldn't resolve host name"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:176 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  ports/boost-build/portfile.cmake:27 (vcpkg_download_distfile)
  scripts/ports.cmake:79 (include)

Error: Building package boost-build:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-build:x64-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.

**Additional context**
There is no problem compiling other libraries, such as `Jsoncpp`  `evpp`

I hope you can help me

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/12383

**Comment by PhoebeHui** [comment]
@yangjiechina, boostcpp.jam file download failed from your log, could you please try following workaround:

Download https://raw.githubusercontent.com/boostorg/boost/boost-1.73.0/boostcpp.jam file manually
Rename it to 'boost-1.73.0-boostcpp.jam'
Put it to vcpkg\download folder
./vcpkg install boost-build[core]:x64-windows

**Comment by yangjiechina** [comment]
> @yangjiechina, boostcpp.jam file download failed from your log, could you please try following workaround:
> 
> Download https://raw.githubusercontent.com/boostorg/boost/boost-1.73.0/boostcpp.jam file manually
> Rename it to 'boost-1.73.0-boostcpp.jam'
> Put it to vcpkg\download folder
> ./vcpkg install boost-build[core]:x64-windows

thaks for your reply，After I recompiled following this step, an error occurred
- Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Starting package 1/69: boost-build:x64-windows
Building package boost-build[core]:x64-windows...
Could not locate cached archive: C:\Users\yangjie\AppData\Local\vcpkg\archives\33\337b5c572ceefa71334c0432c78e863ac8172598.zip
-- Using cached E:/code/vcpkg-master/downloads/boostorg-build-boost-1.73.0.tar.gz
-- Cleaning sources at E:/code/vcpkg-master/buildtrees/boost-build/src/ost-1.73.0-018fb008dd.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/code/vcpkg-master/downloads/boostorg-build-boost-1.73.0.tar.gz
-- Using source at E:/code/vcpkg-master/buildtrees/boost-build/src/ost-1.73.0-018fb008dd.clean
-- Using cached E:/code/vcpkg-master/downloads/boost_LICENSE_1_0.txt
-- Using cached E:/code/vcpkg-master/downloads/boost-1.73.0-boostcpp.jam
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:99 (message):


  File does not have expected hash:

          File path: [ E:/code/vcpkg-master/downloads/boost-1.73.0-boostcpp.jam ]
      Expected hash: [ 8cf929fa4a602342c859a6bbd5f9dda783ac29431d951bcf6cae4cb14377c1b3aed90bacd902b0f7d1807591cf5e1a244cf8fc3c6cc6e0a4056db145b58f51df ]
        Actual hash: [ f0f651be3bfaa316b197e7573ab090b53b8400fd319c5305d8c667ea1de6a2b13f8e94aa89c387146087185d137e856ba584bb2f518113da6f50a75dbadd8158 ]

  Please delete the file and retry if this file should be downloaded again.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:110 (test_hash)
  ports/boost-build/portfile.cmake:27 (vcpkg_download_distfile)
  scripts/ports.cmake:79 (include)


Error: Building package boost-build:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-build:x64-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by PhoebeHui** [comment]
Could you unzip below file and use it instead?
[boost-1.73.0-boostcpp.zip](https://github.com/microsoft/vcpkg/files/4985472/boost-1.73.0-boostcpp.zip)

**Comment by yangjiechina** [comment]
thanks for your reply, I just solved this problem.At first, I created a new file, and then copied the boost-1.73.0/boostcpp.jam code into it. The compilation failed. From https://dl.bintray.com/boostorg/release/1.73.0/source/ Download boost_ 1_ 73_ Use the inside boostcpp.jam The file was recompiled successfully

**Comment by yangjiechina** [comment]
> Could you unzip below file and use it instead?
> [boost-1.73.0-boostcpp.zip](https://github.com/microsoft/vcpkg/files/4985472/boost-1.73.0-boostcpp.zip)

Thanks again
