### ISSUE TITLE
[protobuf:x64-windows] build failure

### ISSUE THREAD

**Issue by xorange** [microsoft/vcpkg#12594]
**Host Environment**
- OS: Windows 10 pro, x64
- Compiler: (not sure)

**To Reproduce**
`.\vcpkg\vcpkg.exe install protobuf protobuf:x64-windows`

1. I'm following [protobuf installation guide](https://github.com/protocolbuffers/protobuf/tree/master/src#c-installation---windows)
2. I open windows Command Line Prompt and use `.\vcpkg\vcpkg.exe install protobuf protobuf:x64-windows`

**Failure logs** 
console error log:
```
F:\env>.\vcpkg\vcpkg.exe install protobuf protobuf:x64-windows
Computing installation plan...
The following packages will be built and installed:
    protobuf[core]:x64-windows
    protobuf[core]:x86-windows
Detecting compiler hash for triplet x64-windows...
Detecting compiler hash for triplet x86-windows...
Starting package 1/2: protobuf:x64-windows
Building package protobuf[core]:x64-windows...
Could not locate cached archive: C:\Users\YY\AppData\Local\vcpkg\archives\c6\c673c20670e5d5fdb4b2006d8509d0673ceee645.zip
-- Using cached F:/env/vcpkg/downloads/protocolbuffers-protobuf-31ebe2ac71400344a5db91ffc13c4ddfb7589f92.tar.gz
-- Cleaning sources at F:/env/vcpkg/buildtrees/protobuf/src/dfb7589f92-61fbc4fa5f.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source F:/env/vcpkg/downloads/protocolbuffers-protobuf-31ebe2ac71400344a5db91ffc13c4ddfb7589f92.tar.gz
-- Applying patch fix-uwp.patch
-- Applying patch fix-android-log.patch
-- Applying patch fix-static-build.patch
-- Using source at F:/env/vcpkg/buildtrees/protobuf/src/dfb7589f92-61fbc4fa5f.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: F:/env/vcpkg/packages/protobuf_x64-windows/tools/protobuf/protoc.exe
-- Installing: F:/env/vcpkg/packages/protobuf_x64-windows/share/protobuf/copyright
-- Fixing pkgconfig
-- Acquiring MSYS Packages...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: F:/env/vcpkg/downloads/tools/msys2/msys64/usr/bin/bash.exe --noprofile --norc -c "pacman -S --noconfirm --needed pkg-config"
    Working Directory: F:/env/vcpkg/downloads/tools/msys2
    Error code: 1
    See logs for more information:
      F:\env\vcpkg\buildtrees\protobuf\msys-pacman-x64-windows-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_acquire_msys.cmake:127 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:281 (vcpkg_acquire_msys)
  ports/protobuf/portfile.cmake:136 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:79 (include)
```

msys-pacman-x64-windows-err.log (full content):
```
error: mingw32: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" is unknown
error: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" could not be looked up remotely
error: mingw64: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" is unknown
error: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" could not be looked up remotely
error: msys: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" is unknown
error: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" could not be looked up remotely
error: database 'mingw32' is not valid (invalid or corrupted database (PGP signature))
error: database 'mingw64' is not valid (invalid or corrupted database (PGP signature))
error: database 'msys' is not valid (invalid or corrupted database (PGP signature))
```

**Questions**
I'm quite noob on this so here comes some basic questions:
1. Do I need to install extra environments or Windows Command Prompt should do the work?
2. I noticed some use of `pacman`, but my environment doesn't have any. So same as Question 1, is any prerequisites required? Such as mingw or mingw32, this is the part I really don't have any clue.
```
F:\env>pacman
'pacman' is not recognized as an internal or external command,
operable program or batch file.
```

**How I install vcpkg**
I followed this [quick start guide](https://github.com/microsoft/vcpkg#quick-start-windows)
1. `f:` (to switch to f:, which is a non-system drive)
1. `cd f:\env` (which remains to be the working directory)
1. `git clone https://github.com/microsoft/vcpkg`
2. `.\vcpkg\bootstrap-vcpkg.bat`

Regards and Thanks for your time.

**Comment by JackBoosY** [comment]
#12467 will fix this issue.

**Comment by xorange** [comment]
Thanks for incredibly fast response.

Any workaround suggestions?

**Comment by JackBoosY** [comment]
@xorange Could you try #12467 changes?

**Comment by xorange** [comment]
I suppose you mean workaround provided by yasamoka as follows:
```
# pacman -U --config <(echo) msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz
```
and from [this post](https://www.msys2.org/news/#2020-06-29-new-packagers)

I do not have command `pacman` or `pacman-key` in my environment. And currently I'm lack of knowledge to acquire or use one.

If someone happened to see this issue and decided to try out, please share your result. Do note that quote yasamoka: `As usual with these sorts of workarounds, I take no responsibility for any consequences arising out of using this. This is strictly temporary.`

As for protobuf, I built it from source following [this guide](https://github.com/protocolbuffers/protobuf/blob/master/cmake/README.md)

**Comment by JackBoosY** [comment]
@xorange Just merge his branch to your master, then rerun the install command.

**Comment by xorange** [comment]
Yes problem fixed.

Step:
1. merge [patch](https://github.com/microsoft/vcpkg/pull/12467/files#diff-c85f9ff7711f9ba06b7b2cb5647cf433)
2. `rm downloads/tools/msys2/initialized-msys2_64.stamp` (to trigger msys2 tools download and install)
3. run `cmd` with admin priviledge
4. rerun install

Thanks.

**Comment by chenpei2** [comment]
> @xorange Just merge his branch to your master, then rerun the install command.

I have the same problem and #12467 works for me. I still want to know how this happened and how to avoid such problems? because I'm not updating my environment .I just removed ffmpeg which I installed a few days ago and tried to reinstall it.

**Comment by JackBoosY** [comment]
@chenpei2 We will merge that PR as soon as possible. So after do that, you can just `git pull` and rebuild protobuf.

**Comment by xorange** [comment]
@chenpei2 
> I still want to know how this happened and how to avoid such problems? 

I guess it's just an issue of upstream keystring updating. Nothing's related to user's environment.

**Comment by OlafvdSpek** [comment]
> @chenpei2 We will merge that PR as soon as possible. So after do that, you can just `git pull` and rebuild protobuf.

Why can't it be merged already?

**Comment by JackBoosY** [comment]
@OlafvdSpek We need to merge #12603 first.
