### ISSUE TITLE
[New Port Request] Scapix

### ISSUE THREAD

**Issue by luciy-marciy** [microsoft/vcpkg#12596]
Library name: Scapix

Library description: Automatic, on the fly bindings from C++ to Java, Objective-C, Swift, Python, JavaScript (WebAssembly), and C#.

Source repository URL: https://github.com/scapix-com/scapix

Project homepage (if different from the source repository): https://www.scapix.com/

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
