### ISSUE TITLE
[x86-windows] zlib build failure

### ISSUE THREAD

**Issue by sepcon** [microsoft/vcpkg#12590]
**Host Environment**
- OS: Windows 10
- Compiler: msvc 14

**To Reproduce**
`./vcpkg install cpprestsdk`

**Failure logs** 
`CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: D:/SourceCode/GitHub/toolchains/vcpkg/downloads/tools/msys2/msys64/usr/bin/bash.exe --noprofile --norc -c "pacman -S --noconfirm --needed pkg-config"
    Working Directory: D:/SourceCode/GitHub/toolchains/vcpkg/downloads/tools/msys2
    Error code: 1
    See logs for more information:
      D:\SourceCode\GitHub\toolchains\vcpkg\buildtrees\zlib\msys-pacman-x86-windows-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_acquire_msys.cmake:127 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:281 (vcpkg_acquire_msys)
  ports/zlib/portfile.cmake:46 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:79 (include)

Error: Building package zlib:x86-windows failed with: BUILD_FAILED
`

**Additional context**
I already successfully installed **cpprestsdk**, after I tried to write a script to automatically install all of my needed packages to share with my team, then it failed at step of installing **cpprestsdk** and I'm never able to install it once more time.

[msys-pacman-x86-windows-err.log](https://github.com/microsoft/vcpkg/files/4979982/msys-pacman-x86-windows-err.log)

**Comment by ankurverma85** [comment]
https://www.msys2.org/news/#2020-06-29-new-packagers
This seems to work for me

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/12582.
