### ISSUE TITLE
[boost] update/new install build failure

### ISSUE THREAD

**Issue by aPSopt** [microsoft/vcpkg#12593]
**Host Environment**
- OS: Windows 10
- Compiler: msvs 2019 (last update)

**To Reproduce**
`./vcpkg upgrade boost --no-dry-run`

**Failure logs** 

> The following packages will be built and installed:
>     boost[core]:x64-windows
>   * boost-accumulators[core]:x64-windows
>   * boost-asio[core]:x64-windows
>   * boost-assign[core]:x64-windows
>   * boost-beast[core]:x64-windows
>   * boost-bimap[core]:x64-windows
>   * boost-compute[core]:x64-windows
>   * boost-context[core]:x64-windows
>   * boost-contract[core]:x64-windows
>   * boost-convert[core]:x64-windows
>   * boost-coroutine[core]:x64-windows
>   * boost-coroutine2[core]:x64-windows
>   * boost-date-time[core]:x64-windows
>   * boost-dll[core]:x64-windows
>   * boost-fiber[core]:x64-windows
>   * boost-flyweight[core]:x64-windows
>   * boost-geometry[core]:x64-windows
>   * boost-gil[core]:x64-windows
>   * boost-graph[core]:x64-windows
>   * boost-graph-parallel[core]:x64-windows
>   * boost-histogram[core]:x64-windows
>   * boost-icl[core]:x64-windows
>   * boost-interprocess[core]:x64-windows
>   * boost-iostreams[core]:x64-windows
>   * boost-locale[core]:x64-windows
>   * boost-lockfree[core]:x64-windows
>   * boost-log[core]:x64-windows
>   * boost-msm[core]:x64-windows
>   * boost-multi-index[core]:x64-windows
>   * boost-multiprecision[core]:x64-windows
>   * boost-nowide[core]:x64-windows
>   * boost-odeint[core]:x64-windows
>   * boost-parameter-python[core]:x64-windows
>   * boost-phoenix[core]:x64-windows
>   * boost-poly-collection[core]:x64-windows
>   * boost-process[core]:x64-windows
>   * boost-program-options[core]:x64-windows
>   * boost-property-map[core]:x64-windows
>   * boost-property-tree[core]:x64-windows
>   * boost-proto[core]:x64-windows
>   * boost-ptr-container[core]:x64-windows
>   * boost-python[core]:x64-windows
>   * boost-qvm[core]:x64-windows
>   * boost-random[core]:x64-windows
>   * boost-serialization[core]:x64-windows
>   * boost-sort[core]:x64-windows
>   * boost-spirit[core]:x64-windows
>   * boost-stacktrace[core]:x64-windows
>   * boost-statechart[core]:x64-windows
>   * boost-test[core]:x64-windows
>   * boost-thread[core]:x64-windows
>   * boost-timer[core]:x64-windows
>   * boost-type-erasure[core]:x64-windows
>   * boost-ublas[core]:x64-windows
>   * boost-units[core]:x64-windows
>   * boost-uuid[core]:x64-windows
>   * boost-wave[core]:x64-windows
>   * boost-xpressive[core]:x64-windows
>   * bzip2[core]:x64-windows
>   * liblzma[core]:x64-windows
>   * python3[core]:x64-windows
>   * zlib[core]:x64-windows
>   * zstd[core]:x64-windows
> Additional packages (*) will be modified to complete this operation.
> Detecting compiler hash for triplet x64-windows...
> Starting package 1/63: bzip2:x64-windows
> Building package bzip2[core]:x64-windows...
> Could not locate cached archive: C:\Users\AeroSun\AppData\Local\vcpkg\archives\39\3983f4cd2c53117078834d6df736f9fe928bf86a.zip
> -- Using cached D:/vcpkg/downloads/bzip2-1.0.6.tar.gz
> -- Cleaning sources at D:/vcpkg/buildtrees/bzip2/src/1.0.6-8838f21f8e.clean. Use --editable to skip cleaning for the packages you specify.
> -- Extracting source D:/vcpkg/downloads/bzip2-1.0.6.tar.gz
> -- Applying patch fix-import-export-macros.patch
> -- Applying patch fix-windows-include.patch
> -- Using source at D:/vcpkg/buildtrees/bzip2/src/1.0.6-8838f21f8e.clean
> -- Configuring x64-windows
> -- Building x64-windows-dbg
> -- Building x64-windows-rel
> -- Fixing pkgconfig
> -- Acquiring MSYS Packages...
> CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
>     Command failed: D:/vcpkg/downloads/tools/msys2/msys64/usr/bin/bash.exe --noprofile --norc -c "pacman -S --noconfirm --needed pkg-config"
>     Working Directory: D:/vcpkg/downloads/tools/msys2
>     Error code: 1
>     See logs for more information:
>       D:\vcpkg\buildtrees\bzip2\msys-pacman-x64-windows-err.log
> 
> Call Stack (most recent call first):
>   scripts/cmake/vcpkg_acquire_msys.cmake:127 (vcpkg_execute_required_process)
>   scripts/cmake/vcpkg_fixup_pkgconfig.cmake:281 (vcpkg_acquire_msys)
>   ports/bzip2/portfile.cmake:51 (vcpkg_fixup_pkgconfig)
>   scripts/ports.cmake:79 (include)

**Comment by aPSopt** [comment]
With new (clear) install I receive following error:

> Installing package boost-endian[core]:x64-windows... done
> Elapsed time for package boost-endian:x64-windows: 1.488 s
> Starting package 60/149: bzip2:x64-windows
> Building package bzip2[core]:x64-windows...
> Could not locate cached archive: C:\Users\AeroSun\AppData\Local\vcpkg\archives\39\3983f4cd2c53117078834d6df736f9fe928bf86a.zip
> -- Downloading https://github.com/past-due/bzip2-mirror/releases/download/v1.0.6/bzip2-1.0.6.tar.gz...
> -- Extracting source D:/Tmp/vcpkg/downloads/bzip2-1.0.6.tar.gz
> -- Applying patch fix-import-export-macros.patch
> -- Applying patch fix-windows-include.patch
> -- Using source at D:/Tmp/vcpkg/buildtrees/bzip2/src/1.0.6-8838f21f8e.clean
> -- Configuring x64-windows
> -- Building x64-windows-dbg
> -- Building x64-windows-rel
> -- Fixing pkgconfig
> -- Acquiring MSYS2...
> -- Downloading https://sourceforge.net/projects/msys2/files/Base/x86_64/msys2-base-x86_64-20190524.tar.xz/download...
> gpg: /etc/pacman.d/gnupg/trustdb.gpg: trustdb created
> gpg: no ultimately trusted keys found
> gpg: starting migration from earlier GnuPG versions
> gpg: porting secret keys from '/etc/pacman.d/gnupg/secring.gpg' to gpg-agent
> gpg: migration succeeded
> gpg: Generating pacman keyring master key...
> gpg: key 9711B463FE6BE14E marked as ultimately trusted
> gpg: directory '/etc/pacman.d/gnupg/openpgp-revocs.d' created
> gpg: revocation certificate stored as '/etc/pacman.d/gnupg/openpgp-revocs.d/5EDDAA98EAF3BB2D16B317BA9711B463FE6BE14E.rev'
> gpg: Done
> ==> Updating trust database...
> gpg: marginals needed: 3  completes needed: 1  trust model: pgp
> gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
> ==> Appending keys from msys2.gpg...
> ==> Locally signing trusted keys in keyring...
>   -> Locally signing key D55E7A6D7CE9BA1587C0ACACF40D263ECA25678A...
>   -> Locally signing key 123D4D51A1793859C2BE916BBBE514E53E0D0813...
>   -> Locally signing key B91BCF3303284BF90CC043CA9F418C233E652008...
>   -> Locally signing key 9DD0D4217D75A33B896159E6DA7EF2ABAEEA755C...
> ==> Importing owner trust values...
> gpg: setting ownertrust to 4
> gpg: setting ownertrust to 4
> gpg: setting ownertrust to 4
> gpg: inserting ownertrust of 4
> ==> Updating trust database...
> gpg: marginals needed: 3  completes needed: 1  trust model: pgp
> gpg: depth: 0  valid:   1  signed:   4  trust: 0-, 0q, 0n, 0m, 0f, 1u
> gpg: depth: 1  valid:   4  signed:   3  trust: 0-, 0q, 0n, 4m, 0f, 0u
> gpg: depth: 2  valid:   3  signed:   0  trust: 3-, 0q, 0n, 0m, 0f, 0u
> :: Synchronizing package databases...
> downloading mingw32.db...
> downloading mingw32.db.sig...
> error: mingw32: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" is unknown
> error: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" could not be looked up remotely
> error: failed to update mingw32 (invalid or corrupted database (PGP signature))
> downloading mingw64.db...
> downloading mingw64.db.sig...
> error: mingw64: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" is unknown
> error: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" could not be looked up remotely
> error: failed to update mingw64 (invalid or corrupted database (PGP signature))
> downloading msys.db...
> downloading msys.db.sig...
> error: msys: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" is unknown
> error: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" could not be looked up remotely
> error: failed to update msys (invalid or corrupted database (PGP signature))
> error: failed to synchronize all databases
> error: mingw32: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" is unknown
> error: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" could not be looked up remotely
> error: mingw64: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" is unknown
> error: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" could not be looked up remotely
> error: msys: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" is unknown
> error: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" could not be looked up remotely
> checking dependencies...
> 
> Packages (2) rebase-4.4.4-1  dash-0.5.10.2-1
> 
> Total Removed Size:  1.12 MiB
> 
> :: Do you want to remove these packages? [Y/n]
> :: Processing package changes...
> removing rebase...
> removing dash...
> error: mingw32: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" is unknown
> error: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" could not be looked up remotely
> error: mingw64: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" is unknown
> error: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" could not be looked up remotely
> error: msys: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" is unknown
> error: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" could not be looked up remotely
> :: Synchronizing package databases...
> downloading mingw32.db...
> downloading mingw32.db.sig...
> error: mingw32: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" is unknown
> error: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" could not be looked up remotely
> error: failed to update mingw32 (invalid or corrupted database (PGP signature))
> downloading mingw64.db...
> downloading mingw64.db.sig...
> error: mingw64: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" is unknown
> error: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" could not be looked up remotely
> error: failed to update mingw64 (invalid or corrupted database (PGP signature))
> downloading msys.db...
> downloading msys.db.sig...
> error: msys: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" is unknown
> error: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" could not be looked up remotely
> error: failed to update msys (invalid or corrupted database (PGP signature))
> error: failed to synchronize all databases
> -- Acquiring MSYS2... OK
> -- Acquiring MSYS Packages...
> CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
>     Command failed: D:/Tmp/vcpkg/downloads/tools/msys2/msys64/usr/bin/bash.exe --noprofile --norc -c "pacman -S --noconfirm --needed pkg-config"
>     Working Directory: D:/Tmp/vcpkg/downloads/tools/msys2
>     Error code: 1
>     See logs for more information:
>       D:\Tmp\vcpkg\buildtrees\bzip2\msys-pacman-x64-windows-err.log
> 
> Call Stack (most recent call first):
>   scripts/cmake/vcpkg_acquire_msys.cmake:127 (vcpkg_execute_required_process)
>   scripts/cmake/vcpkg_fixup_pkgconfig.cmake:281 (vcpkg_acquire_msys)
>   ports/bzip2/portfile.cmake:51 (vcpkg_fixup_pkgconfig)
>   scripts/ports.cmake:79 (include)

**Comment by aPSopt** [comment]
I propose before apply any commit - to make the small smoke test. 
Because it is not the first and not the seconв time the boost build trouble happens. 

I note that the boost - is base library for most part of others. And whent it broken - all others inaccessible too.
So now I have broken all libraries stack :((((

I propose to make more serious approach for applaying changes to boost build.

**Comment by JackBoosY** [comment]
#12467 will fix this issue.
