### ISSUE TITLE
.\vcpkg upgrade error vcpkglib.cpp(69) expected fieldname

### ISSUE THREAD

**Issue by MCl57** [microsoft/vcpkg#12602]
**Describe the bug**
```
_PS C:\work\git\vcpkg>_ **git pull**
Already up to date.
PS C:\work\git\vcpkg> .\vcpkg upgrade
Failed at [C:\work\git\vcpkg\toolsrc\src\vcpkg\vcpkglib.cpp(69)] with message:
Error: C:\work\git\vcpkg\installed\vcpkg\updates\0000000000:1:1: expected fieldname
   on expression:
_PS C:\work\git\vcpkg>_
```

**Environment**
- Vcpkg package management program version 2020.06.15-nohash
- OS: Windows 10, Ubuntu, Same error in both systems
- Compiler: Microsoft Visual Studio Community 2019 Version 16.6.5

**To Reproduce**
```
_PS C:\work\git\vcpkg>_ **.\vcpkg install glog**
Computing installation plan...
Failed at [C:\work\git\vcpkg\toolsrc\src\vcpkg\vcpkglib.cpp(69)] with message:
Error: C:\work\git\vcpkg\installed\vcpkg\updates\0000000000:1:1: expected fieldname
   on expression:
PS C:\work\git\vcpkg>
```

**also updated:**
```
PS C:\work\git\vcpkg> **.\bootstrap-vcpkg.bat**

Building vcpkg.exe ...

  Using triplet "x86-windows" from "C:\work\git\vcpkg\installed\x86-windows\"
  pch.cpp
  archives.cpp
  checks.cpp
  chrono.cpp
  cofffilereader.cpp
  downloads.cpp
  enums.cpp
  files.cpp
  hash.cpp
  json.cpp
  machinetype.cpp
  parse.cpp
  strings.cpp
  stringview.cpp
  system.cpp
  system.print.cpp
  system.process.cpp
  unicode.cpp
  binarycaching.cpp
  binaryparagraph.cpp
  build.cpp
  buildenvironment.cpp
  cmakevars.cpp
  commands.autocomplete.cpp
  commands.buildexternal.cpp
  commands.cache.cpp
  commands.ci.cpp
  commands.ciclean.cpp
  commands.contact.cpp
  commands.cpp
  commands.create.cpp
  commands.dependinfo.cpp
  commands.edit.cpp
  commands.env.cpp
  commands.exportifw.cpp
  commands.format-manifest.cpp
  commands.integrate.cpp
  commands.list.cpp
  commands.owns.cpp
  commands.porthistory.cpp
  commands.portsdiff.cpp
  commands.search.cpp
  commands.setinstalled.cpp
  commands.upgrade.cpp
  commands.version.cpp
  commands.xvsinstances.cpp
  dependencies.cpp
  export.cpp
  export.chocolatey.cpp
  export.prefab.cpp
  globalstate.cpp
  help.cpp
  input.cpp
  install.cpp
  platform-expression.cpp
  metrics.cpp
  packagespec.cpp
  paragraphparseresult.cpp
  paragraphs.cpp
  portfileprovider.cpp
  postbuildlint.buildtype.cpp
  postbuildlint.cpp
  remove.cpp
  sourceparagraph.cpp
  statusparagraph.cpp
  statusparagraphs.cpp
  tools.cpp
  triplet.cpp
  update.cpp
  userconfig.cpp
  vcpkgcmdarguments.cpp
  vcpkglib.cpp
  vcpkgpaths.cpp
  versiont.cpp
  visualstudio.cpp
  vcpkglib.vcxproj -> C:\work\git\vcpkg\toolsrc\msbuild.x86.release\vcpkglib.lib
  Using triplet "x86-windows" from "C:\work\git\vcpkg\installed\x86-windows\"
  vcpkg.cpp
  Code wird generiert.
  Previous IPDB not found, fall back to full compilation.
  All 19105 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Codegenerierung ist abgeschlossen.
  vcpkg.vcxproj -> C:\work\git\vcpkg\toolsrc\msbuild.x86.release\vcpkg.exe
  Using triplet "x86-windows" from "C:\work\git\vcpkg\installed\x86-windows\"
  vcpkgmetricsuploader.cpp
  Code wird generiert.
  Previous IPDB not found, fall back to full compilation.
  All 8999 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Codegenerierung ist abgeschlossen.
  vcpkgmetricsuploader.vcxproj -> C:\work\git\vcpkg\toolsrc\msbuild.x86.release\vcpkgmetricsuploader.exe

Building vcpkg.exe... done.

Telemetry
---------
vcpkg collects usage data in order to help us improve your experience.
The data collected by Microsoft is anonymous.
You can opt-out of telemetry by re-running the bootstrap-vcpkg script with -disableMetrics,
passing --disable-metrics to vcpkg on the command line,
or by setting the VCPKG_DISABLE_METRICS environment variable.

Read more about vcpkg telemetry at docs/about/privacy.md
_PS C:\work\git\vcpkg>_
```

**Comment by JackBoosY** [comment]
Hi @MCl57, thanks for reporting this issue!
Have you deleted the files or directories in _installed_ before? Can you clone a copy of vcpkg to reproduce this issue?

Thanks.

**Comment by MCl57** [comment]
// git download
[vcpkg.zip](https://github.com/microsoft/vcpkg/files/4988453/vcpkg.zip)

C:\work\git\vcpkg\installed\
[installed-vcpkg.zip](https://github.com/microsoft/vcpkg/files/4988476/installed-vcpkg.zip)

**Comment by MCl57** [comment]
Hello Jack Boos Yu,

Have you deleted the files or directories in installed before? No, never. 
I uploaded files on https://github.com/microsoft/vcpkg/issues/12602.

Mit freundlichen Grüßen

Michael Clausohm
Technical Development Manager

Clausohm-Software GmbH
Neubrandenburger Str. 46 
D-17039 Neverin

P +49 39608 269020
M +49 172 3849147

michael.clausohm@clausohm.de

Geschäftsführer: Katharina Clausohm, Michael Clausohm, Carina Clausohm, 
Heiner Clausohm
Amtsgericht Neubrandenburg HRB 2766


      







Von:    Jack·Boos·Yu <notifications@github.com>
An:     microsoft/vcpkg <vcpkg@noreply.github.com>
Kopie:  MCl57 <michael.clausohm@clausohm.de>, Mention 
<mention@noreply.github.com>
Datum:  28.07.2020 11:03
Betreff:        Re: [microsoft/vcpkg] .\vcpkg upgrade error 
vcpkglib.cpp(69) expected fieldname (#12602)



Hi @MCl57, thanks for reporting this issue!
Have you deleted the files or directories in installed before? Can you 
clone a copy of vcpkg to reproduce this issue?
Thanks.

**Comment by MCl57** [comment]
Hello Jack-Boos-Yu,
Could you delete last comment, please. I don't wont private data on web 
site (e-mail, names ...).
I clone it, an all is okay. 
Thank you very much.



Von:    Jack·Boos·Yu <notifications@github.com>
An:     microsoft/vcpkg <vcpkg@noreply.github.com>
Kopie:  MCl57 <michael.clausohm@clausohm.de>, Mention 
<mention@noreply.github.com>
Datum:  28.07.2020 11:03
Betreff:        Re: [microsoft/vcpkg] .\vcpkg upgrade error 
vcpkglib.cpp(69) expected fieldname (#12602)



Hi @MCl57, thanks for reporting this issue!
Have you deleted the files or directories in installed before? Can you 
clone a copy of vcpkg to reproduce this issue?
Thanks.

**Comment by MCl57** [comment]
here are the files:
https://github.com/microsoft/vcpkg/issues/12602#issuecomment-665031812
Is this enough?

**Comment by JackBoosY** [comment]
It seems that state file is broken.
@strega-nil Could you please take a look?

**Comment by strega-nil** [comment]
@MCl57, could you try downgrading vcpkg back to commit `ac4e90220adb99d7cea190c41d798ac113f20627`, and then rebootstrap and re-upgrade? otherwise, it looks like your installed directory might be broken; I don't know why that might be (unless there was a <ctrl-c> at some point there shouldn't've been), but deleting the installed directory and reinstalling the ports should work.

**Comment by MCl57** [comment]
Thank you, I installed complete vcpkg new now.
Now my work stops on https://github.com/microsoft/vcpkg/issues/12618
