### ISSUE TITLE
[libsrt:x64-windows] build failure

### ISSUE THREAD

**Issue by sumitkang** [microsoft/vcpkg#12609]
**Host Environment**
- OS: [Windows 7]
- Compiler: Visual studio 2017

**To Reproduce**
.\vcpkg install libsrt:x64-windows

**Failure logs** 
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: ninja -v
    Working Directory: D:/VCPKG/vcpkg/buildtrees/libsrt/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\VCPKG\vcpkg\buildtrees\libsrt\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:296 (vcpkg_execute_required_process)
  ports/libsrt/portfile.cmake:24 (vcpkg_configure_cmake)
  scripts/ports.cmake:94 (include)

Error: Building package libsrt:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libsrt:x64-windows
  Vcpkg version: 2019.09.12-nohash

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by NancyLi1013** [comment]
Hi @sumitkang 
Thanks for posting this issue.
Could you please provide the failure log from _D:\VCPKG\vcpkg\buildtrees\libsrt\config-x64-windows-out.log_?

**Comment by sumitkang** [comment]
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/4986311/config-x64-windows-out.log)
@NancyLi1013 thanks , i have uploaded the log file.

**Comment by NancyLi1013** [comment]
```
CMake Error at CMakeLists.txt:15 (project):
  Failed to run MSBuild command:

    C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/MSBuild/15.0/Bin/MSBuild.exe

  to get the value of VCTargetsPath:
```
Could you please check if `MSBuild.exe` exists on your machine?
Please also refer to this [link ](https://gitlab.kitware.com/cmake/cmake/-/issues/17349) to get the related information.

**Comment by JackBoosY** [comment]
Please close the antivirus and try again.

**Comment by sumitkang** [comment]
@NancyLi1013  MsBuild.exe exists and it is at the afollowing location.
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin

**Comment by sumitkang** [comment]
@JackBoosY  I disabled the antivirus and tried to build the package again with vcpkg but still the build fails.

**Comment by NancyLi1013** [comment]
Have you installed Windows SDK and build tools in Visual Studio?

Could you please also update vcpkg to the latest version and try to rebuild this port?

**Comment by sumitkang** [comment]
@NancyLi1013  thank you very much , though i had build tools installed but by reinstalling it again the problem is solved.
i am able to compile the library.

**Comment by NancyLi1013** [comment]
Thanks for your feedback. 
I'm closing this issue since you can build it now.
