### ISSUE TITLE
[jsoncpp] build failure

### ISSUE THREAD

**Issue by Kayd-J** [microsoft/vcpkg#12607]
**Host Environment**
- OS: [Microsoft Windows 10 Pro.  Version	10.0.19041 Build 19041]
- Compiler: revision
 ninja version 1.10.0
  Package: jsoncpp:x86-windows
  Vcpkg version: 2020.06.15-nohash

**To Reproduce**
`./vcpkg install jsoncpp`

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
Building package jsoncpp[core]:x86-windows...
Could not locate cached archive: C:\Users\Jarod\AppData\Local\vcpkg\archives\0a\0aec82e1c97f298a54c1c296362d347339904b2c.zip
-- Using cached C:/Users/Jarod/vcpkg/downloads/open-source-parsers-jsoncpp-1.9.2.tar.gz
-- Cleaning sources at C:/Users/Jarod/vcpkg/buildtrees/jsoncpp/src/1.9.2-d01d7f5c9b.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/Jarod/vcpkg/downloads/open-source-parsers-jsoncpp-1.9.2.tar.gz
-- Applying patch allow-disable-examples.patch
-- Using source at C:/Users/Jarod/vcpkg/buildtrees/jsoncpp/src/1.9.2-d01d7f5c9b.clean
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: ninja -v
    Working Directory: C:/Users/Jarod/vcpkg/buildtrees/jsoncpp/x86-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\Users\Jarod\vcpkg\buildtrees\jsoncpp\config-x86-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:300 (vcpkg_execute_required_process)
  ports/jsoncpp/portfile.cmake:17 (vcpkg_configure_cmake)
  scripts/ports.cmake:79 (include)

Error: Building package jsoncpp:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: jsoncpp:x86-windows
  Vcpkg version: 2020.06.15-nohash

-Please attach any additional failure logs mentioned in the console output.

**Additional context**
I followed the steps on the documentation

**Comment by PhoebeHui** [comment]
@Kayd-J, could you attach log file C:\Users\Jarod\vcpkg\buildtrees\jsoncpp\config-x86-windows-out.log?

**Comment by Kayd-J** [comment]
[1/2] cmd /c "cd .. && "D:/cmake-3.18.0-rc4-win64-x64/bin/cmake.exe" "C:/Users/Jarod/vcpkg/buildtrees/jsoncpp/src/1.9.2-d01d7f5c9b.clean" "-DJSONCPP_WITH_CMAKE_PACKAGE=ON" "-DBUILD_STATIC_LIBS=OFF" "-DJSONCPP_WITH_PKGCONFIG_SUPPORT=OFF" "-DJSONCPP_WITH_POST_BUILD_UNITTEST=OFF" "-DJSONCPP_WITH_TESTS=OFF" "-DJSONCPP_WITH_EXAMPLE=OFF" "-DCMAKE_MAKE_PROGRAM=C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/Users/Jarod/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x86-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v142" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/Users/Jarod/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_TARGET_ARCHITECTURE=x86" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=C:/Users/Jarod/vcpkg" "-D_VCPKG_INSTALLED_DIR=C:/Users/Jarod/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=C:/Users/Jarod/vcpkg/packages/jsoncpp_x86-windows""
FAILED: ../CMakeCache.txt 
cmd /c "cd .. && "D:/cmake-3.18.0-rc4-win64-x64/bin/cmake.exe" "C:/Users/Jarod/vcpkg/buildtrees/jsoncpp/src/1.9.2-d01d7f5c9b.clean" "-DJSONCPP_WITH_CMAKE_PACKAGE=ON" "-DBUILD_STATIC_LIBS=OFF" "-DJSONCPP_WITH_PKGCONFIG_SUPPORT=OFF" "-DJSONCPP_WITH_POST_BUILD_UNITTEST=OFF" "-DJSONCPP_WITH_TESTS=OFF" "-DJSONCPP_WITH_EXAMPLE=OFF" "-DCMAKE_MAKE_PROGRAM=C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/Users/Jarod/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x86-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v142" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/Users/Jarod/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_TARGET_ARCHITECTURE=x86" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=C:/Users/Jarod/vcpkg" "-D_VCPKG_INSTALLED_DIR=C:/Users/Jarod/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=C:/Users/Jarod/vcpkg/packages/jsoncpp_x86-windows""
-- The CXX compiler identification is MSVC 19.26.28806.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x86/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x86/cl.exe - broken
CMake Error at D:/cmake-3.18.0-rc4-win64-x64/share/cmake-3.18/Modules/CMakeTestCXXCompiler.cmake:59 (message):
  The C++ compiler

    "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x86/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/Users/Jarod/vcpkg/buildtrees/jsoncpp/x86-windows-rel/CMakeFiles/CMakeTmp
    
    Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe cmTC_d5117 && [1/2] Building CXX object CMakeFiles\cmTC_d5117.dir\testCXXCompiler.cxx.obj
    [2/2] Linking CXX executable cmTC_d5117.exe
    FAILED: cmTC_d5117.exe 
    cmd.exe /C "cd . && D:\cmake-3.18.0-rc4-win64-x64\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_d5117.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1426~1.288\bin\Hostx64\x86\link.exe /nologo CMakeFiles\cmTC_d5117.dir\testCXXCompiler.cxx.obj  /out:cmTC_d5117.exe /implib:cmTC_d5117.lib /pdb:cmTC_d5117.pdb /version:0.0 /machine:X86  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    LINK Pass 1: command "C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1426~1.288\bin\Hostx64\x86\link.exe /nologo CMakeFiles\cmTC_d5117.dir\testCXXCompiler.cxx.obj /out:cmTC_d5117.exe /implib:cmTC_d5117.lib /pdb:cmTC_d5117.pdb /version:0.0 /machine:X86 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\cmTC_d5117.dir/intermediate.manifest CMakeFiles\cmTC_d5117.dir/manifest.res" failed (exit code 1104) with the following output:
    LINK : fatal error LNK1104: cannot open file 'ucrtd.lib'
    ninja: build stopped: subcommand failed.
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:65 (project)


-- Configuring incomplete, errors occurred!
See also "C:/Users/Jarod/vcpkg/buildtrees/jsoncpp/x86-windows-rel/CMakeFiles/CMakeOutput.log".
See also "C:/Users/Jarod/vcpkg/buildtrees/jsoncpp/x86-windows-rel/CMakeFiles/CMakeError.log".
[2/2] cmd /c "cd ../../x86-windows-dbg && "D:/cmake-3.18.0-rc4-win64-x64/bin/cmake.exe" "C:/Users/Jarod/vcpkg/buildtrees/jsoncpp/src/1.9.2-d01d7f5c9b.clean" "-DJSONCPP_WITH_CMAKE_PACKAGE=ON" "-DBUILD_STATIC_LIBS=OFF" "-DJSONCPP_WITH_PKGCONFIG_SUPPORT=OFF" "-DJSONCPP_WITH_POST_BUILD_UNITTEST=OFF" "-DJSONCPP_WITH_TESTS=OFF" "-DJSONCPP_WITH_EXAMPLE=OFF" "-DCMAKE_MAKE_PROGRAM=C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/Users/Jarod/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x86-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v142" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/Users/Jarod/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_TARGET_ARCHITECTURE=x86" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=C:/Users/Jarod/vcpkg" "-D_VCPKG_INSTALLED_DIR=C:/Users/Jarod/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_INSTALL_PREFIX=C:/Users/Jarod/vcpkg/packages/jsoncpp_x86-windows/debug""
FAILED: ../../x86-windows-dbg/CMakeCache.txt 
cmd /c "cd ../../x86-windows-dbg && "D:/cmake-3.18.0-rc4-win64-x64/bin/cmake.exe" "C:/Users/Jarod/vcpkg/buildtrees/jsoncpp/src/1.9.2-d01d7f5c9b.clean" "-DJSONCPP_WITH_CMAKE_PACKAGE=ON" "-DBUILD_STATIC_LIBS=OFF" "-DJSONCPP_WITH_PKGCONFIG_SUPPORT=OFF" "-DJSONCPP_WITH_POST_BUILD_UNITTEST=OFF" "-DJSONCPP_WITH_TESTS=OFF" "-DJSONCPP_WITH_EXAMPLE=OFF" "-DCMAKE_MAKE_PROGRAM=C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/Users/Jarod/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x86-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v142" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/Users/Jarod/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_TARGET_ARCHITECTURE=x86" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=C:/Users/Jarod/vcpkg" "-D_VCPKG_INSTALLED_DIR=C:/Users/Jarod/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_INSTALL_PREFIX=C:/Users/Jarod/vcpkg/packages/jsoncpp_x86-windows/debug""
-- The CXX compiler identification is MSVC 19.26.28806.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x86/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x86/cl.exe - broken
CMake Error at D:/cmake-3.18.0-rc4-win64-x64/share/cmake-3.18/Modules/CMakeTestCXXCompiler.cmake:59 (message):
  The C++ compiler

    "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x86/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/Users/Jarod/vcpkg/buildtrees/jsoncpp/x86-windows-dbg/CMakeFiles/CMakeTmp
    
    Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe cmTC_abf8f && [1/2] Building CXX object CMakeFiles\cmTC_abf8f.dir\testCXXCompiler.cxx.obj
    [2/2] Linking CXX executable cmTC_abf8f.exe
    FAILED: cmTC_abf8f.exe 
    cmd.exe /C "cd . && D:\cmake-3.18.0-rc4-win64-x64\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_abf8f.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1426~1.288\bin\Hostx64\x86\link.exe /nologo CMakeFiles\cmTC_abf8f.dir\testCXXCompiler.cxx.obj  /out:cmTC_abf8f.exe /implib:cmTC_abf8f.lib /pdb:cmTC_abf8f.pdb /version:0.0 /machine:X86  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    LINK Pass 1: command "C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1426~1.288\bin\Hostx64\x86\link.exe /nologo CMakeFiles\cmTC_abf8f.dir\testCXXCompiler.cxx.obj /out:cmTC_abf8f.exe /implib:cmTC_abf8f.lib /pdb:cmTC_abf8f.pdb /version:0.0 /machine:X86 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\cmTC_abf8f.dir/intermediate.manifest CMakeFiles\cmTC_abf8f.dir/manifest.res" failed (exit code 1104) with the following output:
    LINK : fatal error LNK1104: cannot open file 'ucrtd.lib'
    ninja: build stopped: subcommand failed.
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:65 (project)


-- Configuring incomplete, errors occurred!
See also "C:/Users/Jarod/vcpkg/buildtrees/jsoncpp/x86-windows-dbg/CMakeFiles/CMakeOutput.log".
See also "C:/Users/Jarod/vcpkg/buildtrees/jsoncpp/x86-windows-dbg/CMakeFiles/CMakeError.log".
ninja: build stopped: subcommand failed.

**Comment by PhoebeHui** [comment]
Do you install windows sdk? could you reinstall it by vs installer?

**Comment by Kayd-J** [comment]
It worked, I did installed (a new version) both by the vs installer and by the windows sdk installer!
Thank you very much
