### ISSUE TITLE
[pcre] Add a FindPCRE.cmake

### ISSUE THREAD

**Issue by JPTIZ** [microsoft/vcpkg#12617]
****

**Is your feature request related to a problem? Please describe.**
I have been dealing with a Windows port of a project originally made for Linux, whose buildsystem is Meson (that uses pkg-config and CMake to search for dependencies). The problem is that Windows (and its official development environment - mostly Visual Studio) doesn't have pkg-config neither has PCRE, so we rely on CMake to find dependencies that are installed with VCPKG.

On top of that problem there's another one: there's no FindPCRE.cmake, so even if the `pcre` package is installed, there's no way Meson will find it using CMake.

**Proposed solution**
Provide a FindPCRE.cmake that CMake is able to find with `cmake --find-package` command from command line.

**Describe alternatives you've considered**
I can't think of alternatives right now :(

**Additional context**
Does not apply.

**Comment by NancyLi1013** [comment]
Hi @JPTIZ 
Thanks for posting this issue.

Currently, pcre has provided `unofficial-pcre-config.cmake` file in vcpkg. `FIndPACRE.cmake` is no longer needed.

Please try to refer to the usage as follows:

   ```
 find_package(unofficial-pcre CONFIG REQUIRED)
    # Note: 1 target(s) were omitted.
    target_link_libraries(main PRIVATE unofficial::pcre::pcre unofficial::pcre::pcre16 unofficial::pcre::pcre32 unofficial::pcre::pcrecpp)
```
