### ISSUE TITLE
[qt5-imageformats:x64-windows] build failure

### ISSUE THREAD

**Issue by BenKey** [microsoft/vcpkg#12628]
**Host Environment**

- OS: Windows 10 Pro version 2004 build 19041.388 64-bit
- Compiler: Visual Studio 2019 Community v16.6.5

**To Reproduce**

Run the following command.

`./vcpkg install qt5 qwt --triplet x64-windows`

**Failure logs** 

This fails with the following error.

    CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
      Command failed: D:/vcpkg/downloads/tools/jom/jom-1.1.3/jom.exe -j 9
      Working Directory: D:/vcpkg/buildtrees/qt5-imageformats/x64-windows-dbg
      Error code: 2
      See logs for more information:
        D:\vcpkg\buildtrees\qt5-imageformats\package-build-x64-windows-dbg-out.log
        D:\vcpkg\buildtrees\qt5-imageformats\package-build-x64-windows-dbg-err.log
    
    Call Stack (most recent call first):
      scripts/cmake/vcpkg_build_qmake.cmake:31 (vcpkg_execute_required_process)
      scripts/cmake/vcpkg_build_qmake.cmake:66 (run_jom)
      installed/x64-windows/share/qt5/qt_build_submodule.cmake:12 (vcpkg_build_qmake)
      installed/x64-windows/share/qt5/qt_submodule_installation.cmake:8 (qt_build_submodule)
      ports/qt5-imageformats/portfile.cmake:54 (qt_submodule_installation)
      scripts/ports.cmake:79 (include)
    
    Error: Building package qt5-imageformats:x64-windows failed with: BUILD_FAILED

The log files are as follows.

[package-build-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/4992915/package-build-x64-windows-dbg-out.log)
[package-build-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/4992916/package-build-x64-windows-dbg-err.log)

**Comment by JackBoosY** [comment]
`Cannot create parent directory`
Will fix in #12529.

**Comment by Neumann-A** [comment]
@BenKey just retry. That is a spurious error we see in qt for some yet to discover reason.
