### ISSUE TITLE
[ffmpeg with libsrt and x264 support] 

### ISSUE THREAD

**Issue by sumitkang** [microsoft/vcpkg#12623]
Library name:
ffmpeg
Library description:
ffmpeg supporting x264 and SRT.
Source repository URL:
https://github.com/FFmpeg/FFmpeg.git
Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
ffmpeg libraray wihich supports the h264 codec[x264] and the SRT protocoll[libsrt]

While building ffmpeg the flags --enable-libx264 and --enable-protocol='file,udp,rtp,srt'  should be enabled.

**Comment by PhoebeHui** [comment]
PR https://github.com/microsoft/vcpkg/pull/11277 would support this feature.

**Comment by PhoebeHui** [comment]
x264 has been added, however, it's broken on windows, the libsrt is still unavailable.

**Comment by hpablo** [comment]
I'd like to add support for libsrt (and other dependencies) myself. How should I go about doing it? The problem is: I have only a very (very) rough idea of how vcpkg works internally and how FFmpeg build work. Documentation is scattered and/or massive (should I learn all of CMake?).

I tried some naïve blind copypasting to add libsrt, but build failed. :-)

Where/how should I start looking? (Docs, guides, examples, etc.)  Many thanks!

**Comment by PhoebeHui** [comment]
@hpablo, you can reference the following docs to get started:

[installing-and-using-packages.md](https://github.com/microsoft/vcpkg/blob/master/docs/examples/installing-and-using-packages.md)
[packaging-github-repos.md](https://github.com/microsoft/vcpkg/blob/master/docs/examples/packaging-github-repos.md)
[patching.md](https://github.com/microsoft/vcpkg/blob/master/docs/examples/patching.md)
[control-files.md](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/control-files.md)
[maintainer-guide.md](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)

**Comment by dg0yt** [comment]
FTR there is also a libsrt port now. But it is not used by ffmpeg.

**Comment by gizmocuz** [comment]
Has anyone gotten this to work by any chance?

**Comment by Sibras** [comment]
ffmpeg uses libsrt now when using ffmpeg[srt] (or ffmpeg[all] or ffmpeg[all-gpl] to also get x264)

**Comment by gizmocuz** [comment]
@Sibras , thanks! Has this recently been added, or should it always have worked?

**Comment by Sibras** [comment]
It was added last September in [26679](https://github.com/microsoft/vcpkg/pull/26679)

**Comment by gizmocuz** [comment]
Thank you!

**Comment by dg0yt** [comment]
This should be closed, #26679.

**Comment by dg0yt** [comment]
> This should be closed, #26679.

@PhoebeHui @Cheney-W
