### ISSUE TITLE
OpenCV 4.3.0 No HighGUI/GTK support on Linux

### ISSUE THREAD

**Issue by LeonineKing1199** [microsoft/vcpkg#12621]
**Host Environment**
- OS: Linux
- Compiler: g++-10/clang++-10

**To Reproduce**
`./vcpkg install opencv4`

OpenCV 4.3 will build perfectly on Linux and link as well _but_ when I try and use the `cv::imshow` function, I get a message that the library was not compiled with GUI support. Because I'm on Linux, it mentions installing libgtk-2.0 which I have installed alongside pkg-config.

I worked around this issue by manually updating the portfile to set: `WITH_GTK=ON` and now it seems like it Just Works.

**Comment by JackBoosY** [comment]
@cenit Could you please take a look?

Thanks.

**Comment by cenit** [comment]
This is in fact a known issue. vcpkg distributes a GTK library which does not work on Linux. But because it exists on vcpkg, we cannot ask the users to install it from external package managers (apt). What the user did is right, at least until we make gtk to build on Linux (abandoning our custom CMakeLists and going with the official meson build)

**Comment by stephanecharette** [comment]
> I worked around this issue by manually updating the portfile to set: `WITH_GTK=ON` and now it seems like it Just Works.

Can you please provide details on exactly where I need to add `WITH_GTK=ON`?

**Comment by stephanecharette** [comment]
I think I figured it out:

- edit .../vcpkg/ports/opencv4/portfile.cmake
- look for `-DWITH_GTK=OFF`
- change that to say `-DWITH_GTK=ON`
- save and exit from your editor
- run this command:  `sudo apt-get install libgtk2.0-dev pkg-config`
- run this command:  `./vcpkg remove opencv opencv4 --recurse`
- run this command:  `./vcpkg install opencv4`   ...or whatever command you used to install OpenCV.

**Comment by rafiyandi** [comment]
how to solve on windows 10

**Comment by cenit** [comment]
> how to solve on windows 10

GTK is unsupported on "non-linux" systems by OpenCV, so the feature is not available when not running on linux
