### ISSUE TITLE
zlib:x86-windows build failure

### ISSUE THREAD

**Issue by turngrobi** [microsoft/vcpkg#12638]
**Host Environment**
- OS: Windows 10 x64
- Compiler: revision

**To Reproduce**
`.\vcpkg install zlib:x86-windows`

**Failure logs** 
Computing installation plan...
The following packages will be built and installed:
    zlib[core]:x86-windows
Detecting compiler hash for triplet x86-windows...
Starting package 1/1: zlib:x86-windows
Building package zlib[core]:x86-windows...
Could not locate cached archive: C:\Users\VeitW\AppData\Local\vcpkg\archives\11\11c81e9f496fe01c4520033c571c33a473a2bf61.zip
-- Using cached C:/ADOS/ecoSystem/vcpkg/downloads/zlib1211.tar.gz
-- Cleaning sources at C:/ADOS/ecoSystem/vcpkg/buildtrees/zlib/src/1.2.11-deec42f53b.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/ADOS/ecoSystem/vcpkg/downloads/zlib1211.tar.gz
-- Applying patch cmake_dont_build_more_than_needed.patch
-- Using source at C:/ADOS/ecoSystem/vcpkg/buildtrees/zlib/src/1.2.11-deec42f53b.clean
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Fixing pkgconfig
-- Acquiring MSYS Packages...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: C:/ADOS/ecoSystem/vcpkg/downloads/tools/msys2/msys64/usr/bin/bash.exe --noprofile --norc -c "pacman -S --noconfirm --needed pkg-config"
    Working Directory: C:/ADOS/ecoSystem/vcpkg/downloads/tools/msys2
    Error code: 1
    See logs for more information:
      C:\ADOS\ecoSystem\vcpkg\buildtrees\zlib\msys-pacman-x86-windows-err.log
> error: mingw32: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" is unknown
> error: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" could not be looked up remotely
> error: mingw64: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" is unknown
> error: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" could not be looked up remotely
> error: msys: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" is unknown
> error: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" could not be looked up remotely
> error: database 'mingw32' is not valid (invalid or corrupted database (PGP signature))
> error: database 'mingw64' is not valid (invalid or corrupted database (PGP signature))
> error: database 'msys' is not valid (invalid or corrupted database (PGP signature))

Call Stack (most recent call first):
  scripts/cmake/vcpkg_acquire_msys.cmake:153 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:281 (vcpkg_acquire_msys)
  ports/zlib/portfile.cmake:46 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:79 (include)

Error: Building package zlib:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zlib:x86-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.

**Additional context**
.\vcpkg update
To update the local portfiles, use `git pull`.
No packages need updating.

git pull
Already up to date.

**Comment by linquize** [comment]
Could you git pull and try 25412e1f462beeb8c24e2cfed9b224d559ec0edf?

**Comment by linquize** [comment]
Could you clear all the packages, `git pull` and try 25412e1f462beeb8c24e2cfed9b224d559ec0edf?

**Comment by awhittle3** [comment]
Same issue happens with zlib:x64-windows and protobuf:x64-windows with a new install of vcpkg from master (commit 0babd2f), and with a fresh install of suggested commit 25412e1.

OS: Windows 10 x64
Compiler: VS 2019 Community v16.6.5

This issue seemed to start occurring on Monday for us, with issues similar to what's described [here](https://github.com/microsoft/vcpkg/issues/12598)

Also note that older versions of vcpkg (e.g. 2020.04) seem to work now, which wasn't the case yesterday.

**Comment by TheReclif** [comment]
Try applying fixes from https://github.com/microsoft/vcpkg/issues/12565#issuecomment-664047785 to a clean, new install of vcpkg.

**Comment by linquize** [comment]
Do you think that's network issue?

**Comment by turngrobi** [comment]
Okay, the workaround mentioned by awhittle3 fixes my problem for now. 
Thx.

**Comment by PhoebeHui** [comment]
@turngrobi, the msys issue has been fixed, please remove the old msys in downloads/tools folder, get latest source and try again.

For pkg-config issue, it would be fixed by PR https://github.com/microsoft/vcpkg/pull/12569.

Duplicated this PR to https://github.com/microsoft/vcpkg/issues/12565.
