### ISSUE TITLE
[ffmpeg] CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):

### ISSUE THREAD

**Issue by samofoz** [microsoft/vcpkg#12648]
**Describe the bug**
vcpkg install ffmpeg[ffmpeg,openssl,vpx,x264]:x64-windows               fails!

**Environment**
- OS: Windows 10

**To Reproduce**
1. vcpkg install ffmpeg[ffmpeg,openssl,vpx,x264]:x64-windows
2. See error

**Expected behavior**
The package should have installed without errors.

**Failure logs** 
C:\vcpackage\vcpkg>vcpkg install ffmpeg[ffmpeg,openssl,vpx,x264]:x64-windows
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
Computing installation plan...
The following packages will be built and installed:
    ffmpeg[avresample,core,ffmpeg,gpl,nonfree,openssl,vpx,x264]:x64-windows
Detecting compiler hash for triplet x64-windows...
Starting package 1/1: ffmpeg:x64-windows
Building package ffmpeg[avresample,core,ffmpeg,gpl,nonfree,openssl,vpx,x264]:x64-windows...
Could not locate cached archive: C:\Users\samof\AppData\Local\vcpkg\archives\25\25219a52bced82afb6e122af7b4b1413ec865728.zip
-- Using cached C:/vcpackage/vcpkg/downloads/ffmpeg-ffmpeg-n4.2.tar.gz
-- Cleaning sources at C:/vcpackage/vcpkg/buildtrees/ffmpeg/src/n4.2-a4d149a5c6.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpackage/vcpkg/downloads/ffmpeg-ffmpeg-n4.2.tar.gz
-- Applying patch 0001-create-lib-libraries.patch
-- Applying patch 0003-fix-windowsinclude.patch
-- Applying patch 0004-fix-debug-build.patch
-- Applying patch 0005-fix-libvpx-linking.patch
-- Applying patch 0006-fix-StaticFeatures.patch
-- Using source at C:/vcpackage/vcpkg/buildtrees/ffmpeg/src/n4.2-a4d149a5c6.clean
-- Acquiring MSYS Packages...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: C:/vcpackage/vcpkg/downloads/tools/msys2/msys64/usr/bin/bash.exe --noprofile --norc -c "pacman -S --noconfirm --needed diffutils make"
    Working Directory: C:/vcpackage/vcpkg/downloads/tools/msys2
    Error code: 1
    See logs for more information:
      C:\vcpackage\vcpkg\buildtrees\ffmpeg\msys-pacman-x64-windows-out.log
      C:\vcpackage\vcpkg\buildtrees\ffmpeg\msys-pacman-x64-windows-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_acquire_msys.cmake:153 (vcpkg_execute_required_process)
  ports/ffmpeg/portfile.cmake:41 (vcpkg_acquire_msys)
  scripts/ports.cmake:79 (include)

Error: Building package ffmpeg:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: ffmpeg:x64-windows
  Vcpkg version: 2020.06.15-nohash

**Comment by samofoz** [comment]
C:\vcpackage\vcpkg>C:/vcpackage/vcpkg/downloads/tools/msys2/msys64/usr/bin/bash.exe --noprofile --norc -c "pacman -S --noconfirm --needed pkg-config"
/usr/bin/bash: pacman: command not found

**Comment by PhoebeHui** [comment]
@samofoz, could you remove 'C:/vcpackage/vcpkg/downloads/tools/msys2' folder, get vcpkg source with 'git pull' and try to build again? please attach the failure log if the issue still persist.

**Comment by samofoz** [comment]
On a clean install:

C:\vcpackage\vcpkg>vcpkg install ffmpeg[ffmpeg,x264]:x64-windows
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
Computing installation plan...
The following packages will be built and installed:
    ffmpeg[avresample,core,ffmpeg,gpl,x264]:x64-windows
  * x264[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Starting package 1/2: x264:x64-windows
Building package x264[core]:x64-windows...
Could not locate cached archive: C:\Users\samof\AppData\Local\vcpkg\archives\76\762922eb6b9b4c305e07b968d7670bb6e2830ddc.zip
-- Using cached C:/vcpackage/vcpkg/downloads/mirror-x264-303c484ec828ed0d8bfe743500e70314d026c3bd.tar.gz
-- Cleaning sources at C:/vcpackage/vcpkg/buildtrees/x264/src/14d026c3bd-bca2ebf740.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpackage/vcpkg/downloads/mirror-x264-303c484ec828ed0d8bfe743500e70314d026c3bd.tar.gz
-- Applying patch uwp-cflags.patch
-- Using source at C:/vcpackage/vcpkg/buildtrees/x264/src/14d026c3bd-bca2ebf740.clean
-- Acquiring MSYS Packages...
-- Acquiring MSYS Packages... OK
-- Configuring x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: C:/vcpackage/vcpkg/downloads/tools/msys2/msys64/usr/bin/bash.exe --noprofile --norc --debug -c " CC='C:/vcpackage/vcpkg/downloads/tools/msys2/msys64/usr/share/automake-1.16/compile cl.exe -nologo' CXX='C:/vcpackage/vcpkg/downloads/tools/msys2/msys64/usr/share/automake-1.16/compile cl.exe -nologo' LD='link.exe -verbose' AR='C:/vcpackage/vcpkg/downloads/tools/msys2/msys64/usr/share/automake-1.16/ar-lib lib.exe -verbose' RANLIB=':' CCAS=':' NM='dumpbin.exe -symbols -headers -all' DLLTOOL='link.exe -verbose -dll' ./../src/14d026c3bd-bca2ebf740.clean/configure --build=i686-pc-mingw32 --target=x86_64-pc-mingw32 --host=x86_64-pc-mingw32 --enable-strip --disable-lavf --disable-swscale --disable-avs --disable-ffms --disable-gpac --disable-lsmash --disable-asm --enable-debug --disable-silent-rules --verbose --enable-shared --disable-static --prefix=/C/vcpackage/vcpkg/installed/x64-windows/debug --bindir='${prefix}'/../tools/x264/debug/bin --sbindir='${prefix}'/../tools/x264/debug/sbin --includedir='${prefix}'/../include --datarootdir='${prefix}'/share/x264"
    Working Directory: C:/vcpackage/vcpkg/buildtrees/x264/x64-windows-dbg
    Error code: 1
    See logs for more information:
      C:\vcpackage\vcpkg\buildtrees\x264\config-x64-windows-dbg-out.log
[Unknown option --build=i686-pc-mingw32, ignored
Unknown option --target=x86_64-pc-mingw32, ignored
Unknown option --disable-silent-rules, ignored
Unknown option --verbose, ignored
Unknown option --disable-static, ignored
Unknown option --sbindir=${prefix}/../tools/x264/debug/sbin, ignored
Unknown option --datarootdir=${prefix}/share/x264, ignored
No working C compiler found.]

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:461 (vcpkg_execute_required_process)
  ports/x264/portfile.cmake:15 (vcpkg_configure_make)
  scripts/ports.cmake:79 (include)


Error: Building package x264:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: x264:x64-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by PhoebeHui** [comment]
@samofoz, for x264 issue, it's a duplicated issue with https://github.com/microsoft/vcpkg/issues/11765

**Comment by PhoebeHui** [comment]
Also related to issue https://github.com/microsoft/vcpkg/issues/12632
