### ISSUE TITLE
[log4cpp] generates additional annoying subdirectory oros

### ISSUE THREAD

**Issue by MCl57** [microsoft/vcpkg#12646]
**Host Environment**
- OS: [Windows 10/ Ubuntu]
- Compiler: revision

**To Reproduce**
`./vcpkg install log4cpp`

**Failure logs** 
installation okay, but
unfortunately the installation cannot be used properly due to an additional subdirectory `orocos`. In visual studio and in sources, the path `log4cpp\` is used instead of `orocos\log4cpp\`.

Result is eg:
`C:\work\git\vcpkg\installed\x64-windows\include\orocos\log4cpp\....`

**Additional context**
A temporary solution is an additional include directory in the project:
`%(AdditionalIncludeDirectories);$(VcpkgCurrentInstalledDir)include\orocos`

**Comment by LilyWangL** [comment]
Thanks for posting this issue. If you run command `./vcpkg integrate install` and `./vcpkg integrate project` before creating c++ project on Visual Studio, you can use include directory of VCPKG on Visual Studio. Does the include directory `orocos\log4cpp` will block your project?

**Comment by MCl57** [comment]
The integration into the project works. I can write the following:
```#include "orocos/log4cpp/Appender.hh"```
The further resolution of the header files fails, because the following code is used in Appender.hh.
```#include <log4cpp/Portability.hh>``` instead of ```#include <orocos/log4cpp / Portability.hh>```

```
/*
 * Appender.hh
 *
 * Copyright 2000, LifeLine Networks BV (www.lifeline.nl). All rights reserved.
 * Copyright 2000, Bastiaan Bakker. All rights reserved.
 *
 * See the COPYING file for the terms of usage and distribution.
 */

#ifndef _LOG4CPP_APPENDER_HH
#define _LOG4CPP_APPENDER_HH

#include <log4cpp/Portability.hh>
#include <string>
#include <map>
#include <set>
#include <stdarg.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <log4cpp/Priority.hh>
#include <log4cpp/Layout.hh>
#include <log4cpp/LoggingEvent.hh>
#include <log4cpp/threading/Threading.hh>
```

Fehler (aktiv)	E1696	Die Datei "Quelle" kann nicht geöffnet werden: "log4cpp/Portability.hh".	TelegramCache	C:\work\git\vcpkg\installed\x64-windows\include\orocos\log4cpp\Appender.hh	13	

C:\work\git\vcpkg\installed\x64-windows\include\orocos\log4cpp\Appender.hh(13,10): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "log4cpp/Portability.hh": No such file or directory

This error creates additional effort and a lot of trying. It doesn't work by default. Which diminishes the good impression of vcpkg.

**Comment by LilyWangL** [comment]
@MCl57 Thanks for your reply. I change the include path, could you try the attached file and rebuild log4cpp? And rebuild your project. If the attached file is useful, I will submit a Pull Request to fix it.

[log4cpp.zip](https://github.com/microsoft/vcpkg/files/5027380/log4cpp.zip)

**Comment by MCl57** [comment]
Hello @LilyWangL,
Could you please give me some advice? Where must the file be imported? Should I build log4cpp with vcpkg? I have no idea?
Thank you.

**Comment by LilyWangL** [comment]
> Hello @LilyWangL,
> Could you please give me some advice? Where must the file be imported? Should I build log4cpp with vcpkg? I have no idea?
> Thank you.

You need download the zip file and unzip this file, then use it replace _[VCPKG_PATH]/ports/log4cpp_. Then rebuild log4cpp and your project.

**Comment by MCl57** [comment]
Okay, success !!! Good job, thanks!
_Allow me a little comment:
It took me some time to understand that by rebuild mean the `vcpkg install log4cpp: x64-windows` command._
