### ISSUE TITLE
 vcpkg.exe build failure with Visual Studio 2015 update 3 (again)

### ISSUE THREAD

**Issue by cgolchert** [microsoft/vcpkg#12644]
**Describe the bug**
vcpkg bootstrap build failure.

**Environment**
OS: windows 10 64bit
Compiler: Visual Studio 2015 update 3

**To Reproduce**
bootstrap-vcpkg.bat

**Expected behavior**
Bootstrap build of vcpkg.exe

**Failure logs** 

Building vcpkg.exe ...

  pch.cpp
  archives.cpp
  checks.cpp
  chrono.cpp
  cofffilereader.cpp
  downloads.cpp
  enums.cpp
  files.cpp
  hash.cpp
..\src\vcpkg\base\files.cpp(144): error C2065: 'SYMBOLIC_LINK_FLAG_ALLOW_UNPRIVILEGED_CREATE': undeclared identifier [C
:\dev\vcpkg\toolsrc\vcpkglib\vcpkglib.vcxproj]
  json.cpp
  machinetype.cpp
  parse.cpp
  strings.cpp
  stringview.cpp
  system.cpp
  system.print.cpp
  system.process.cpp
  unicode.cpp
  binarycaching.cpp
  binaryparagraph.cpp
  build.cpp
  buildenvironment.cpp
  cmakevars.cpp
  commands.autocomplete.cpp
  commands.buildexternal.cpp
  commands.cache.cpp
  commands.ci.cpp
  commands.ciclean.cpp
  commands.contact.cpp
  commands.cpp
  commands.create.cpp
  commands.dependinfo.cpp
  commands.edit.cpp
  commands.env.cpp
  commands.exportifw.cpp
  commands.format-manifest.cpp
  commands.integrate.cpp
  commands.list.cpp
  commands.owns.cpp
  commands.porthistory.cpp
  commands.portsdiff.cpp
  commands.search.cpp
  commands.setinstalled.cpp
  commands.upgrade.cpp
  commands.version.cpp
  commands.xvsinstances.cpp
  dependencies.cpp
  export.cpp
  export.chocolatey.cpp
  export.prefab.cpp
  globalstate.cpp
  help.cpp
  input.cpp
  install.cpp
  platform-expression.cpp
  metrics.cpp
  packagespec.cpp
  paragraphparseresult.cpp
  paragraphs.cpp
  portfileprovider.cpp
  postbuildlint.buildtype.cpp
  postbuildlint.cpp
  remove.cpp
  sourceparagraph.cpp
  statusparagraph.cpp
  statusparagraphs.cpp
  tools.cpp
  triplet.cpp
  update.cpp
  userconfig.cpp
  vcpkgcmdarguments.cpp
  vcpkglib.cpp
  vcpkgpaths.cpp
  versiont.cpp
  visualstudio.cpp
C:\dev\vcpkg\scripts\bootstrap.ps1 : Building vcpkg.exe failed. Please ensure you have installed Visual Studio with
the Desktop C++ workload and the Windows SDK for Desktop C++.
At line:1 char:4
+ & {& 'c:\dev\vcpkg\scripts\bootstrap.ps1' }
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,bootstrap.ps1

ScriptHalted
At C:\dev\vcpkg\scripts\bootstrap.ps1:411 char:5
+     throw
+     ~~~~~
    + CategoryInfo          : OperationStopped: (:) [], RuntimeException
    + FullyQualifiedErrorId : ScriptHalted

**Additional context**
Worked on 7/12/2020.
Will not work with a new git pull and clean folder.

Will bootstrap on a win 7 x64 machine with same VS2015 build

**Comment by cgolchert** [comment]
Thjs was after a "vcpkg update" told me....

Warning: Different source is available for vcpkg (2020.2.4 -> 2020.6.15). Use .\bootstrap-vcpkg.bat to update.
Using local portfile versions. To update the local portfiles, use `git pull`.
Error: There are invalid fields in the control file of boost-modular-build-helper
The following fields were not expected:

    Port-Version

This is the list of valid fields (case-sensitive):

    Source
    Version
    Description
    Maintainer
    Build-Depends
    Homepage
    Type
    Supports

Different source may be available for vcpkg. Use .\bootstrap-vcpkg.bat to update.

Error: Failed to load port from boost-modular-build-helper

**Comment by cgolchert** [comment]
Was just able to reproduce it on win 7 x64

**Comment by PhoebeHui** [comment]
@cgolchert, for the first issue, I can't repro it with vs2015 update3, could you clone a clean source and see if it still exist?

The second issue is expect for me, you need to update the source file by 'git pull', and rebuild vcpkg.

**Comment by cgolchert** [comment]
After git pull.... I got the same results as the first log posted.

I had to run everything on another computer and copy the files over.  For some reason it let me bootstrap it after that.  I can't install anything without the control file error from the newly built vcpkg.exe now.

**Comment by cgolchert** [comment]
From a clean install........

C:\dev>git clone https://github.com/microsoft/vcpkg
Cloning into 'vcpkg'...
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 84339 (delta 0), reused 0 (delta 0), pack-reused 84335
Receiving objects: 100% (84339/84339), 24.74 MiB | 7.76 MiB/s, done.
Resolving deltas: 100% (52281/52281), done.
Checking out files: 100% (5082/5082), done.

C:\dev>.\vcpkg\bootstrap-vcpkg.bat

Building vcpkg.exe ...

  pch.cpp
  archives.cpp
  checks.cpp
  chrono.cpp
  cofffilereader.cpp
  downloads.cpp
  enums.cpp
  files.cpp
  hash.cpp
..\src\vcpkg\base\files.cpp(144): error C2065: 'SYMBOLIC_LINK_FLAG_ALLOW_UNPRIVILEGED_CREATE': undeclared identifier [C
:\dev\vcpkg\toolsrc\vcpkglib\vcpkglib.vcxproj]
  json.cpp
  machinetype.cpp
  parse.cpp
  strings.cpp
  stringview.cpp
  system.cpp
  system.print.cpp
  system.process.cpp
  unicode.cpp
  binarycaching.cpp
  binaryparagraph.cpp
  build.cpp
  buildenvironment.cpp
  cmakevars.cpp
  commands.autocomplete.cpp
  commands.buildexternal.cpp
  commands.cache.cpp
  commands.ci.cpp
  commands.ciclean.cpp
  commands.contact.cpp
  commands.cpp
  commands.create.cpp
  commands.dependinfo.cpp
  commands.edit.cpp
  commands.env.cpp
  commands.exportifw.cpp
  commands.format-manifest.cpp
  commands.integrate.cpp
  commands.list.cpp
  commands.owns.cpp
  commands.porthistory.cpp
  commands.portsdiff.cpp
  commands.search.cpp
  commands.setinstalled.cpp
  commands.upgrade.cpp
  commands.version.cpp
  commands.xvsinstances.cpp
  dependencies.cpp
  export.cpp
  export.chocolatey.cpp
  export.prefab.cpp
  globalstate.cpp
  help.cpp
  input.cpp
  install.cpp
  platform-expression.cpp
  metrics.cpp
  packagespec.cpp
  paragraphparseresult.cpp
  paragraphs.cpp
  portfileprovider.cpp
  postbuildlint.buildtype.cpp
  postbuildlint.cpp
  remove.cpp
  sourceparagraph.cpp
  statusparagraph.cpp
  statusparagraphs.cpp
  tools.cpp
  triplet.cpp
  update.cpp
  userconfig.cpp
  vcpkgcmdarguments.cpp
  vcpkglib.cpp
  vcpkgpaths.cpp
  versiont.cpp
  visualstudio.cpp
C:\dev\vcpkg\scripts\bootstrap.ps1 : Building vcpkg.exe failed. Please ensure you have installed Visual Studio with
the Desktop C++ workload and the Windows SDK for Desktop C++.
At line:1 char:4
+ & {& 'C:\dev\vcpkg\scripts\bootstrap.ps1' }
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,bootstrap.ps1

ScriptHalted
At C:\dev\vcpkg\scripts\bootstrap.ps1:411 char:5
+     throw
+     ~~~~~
    + CategoryInfo          : OperationStopped: (:) [], RuntimeException
    + FullyQualifiedErrorId : ScriptHalted

**Comment by PhoebeHui** [comment]
@cgolchert, do you install win10 sdk? the definition of SYMBOLIC_LINK_FLAG_ALLOW_UNPRIVILEGED_CREATE  in "C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\WinBase.h" for my local machine.

This flag appears to be introduced in the new Windows 10 build 14972, See https://stackoverflow.com/questions/41041629/symbolic-link-flag-allow-unprivileged-create-create-symboliclink

**Comment by cgolchert** [comment]
I'm not seeing a "10.0.17763.0"   Checking into it....

**Comment by cgolchert** [comment]
Installed the current win10 sdk....... 


Microsoft Windows [Version 10.0.18363.959]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\dev\vcpkg>bootstrap-vcpkg.bat

Building vcpkg.exe ...

  pch.cpp
  archives.cpp
  checks.cpp
  chrono.cpp
  cofffilereader.cpp
  downloads.cpp
  enums.cpp
  files.cpp
  hash.cpp
  json.cpp
  machinetype.cpp
  parse.cpp
  strings.cpp
  stringview.cpp
  system.cpp
  system.print.cpp
  system.process.cpp
  unicode.cpp
  binarycaching.cpp
  binaryparagraph.cpp
  build.cpp
  cmakevars.cpp
  commands.autocomplete.cpp
  commands.buildexternal.cpp
  commands.cache.cpp
  commands.ci.cpp
  commands.ciclean.cpp
  commands.contact.cpp
  commands.cpp
  commands.create.cpp
  commands.dependinfo.cpp
  commands.edit.cpp
  commands.env.cpp
  commands.exportifw.cpp
  commands.import.cpp
  commands.integrate.cpp
  commands.list.cpp
  commands.owns.cpp
  commands.porthistory.cpp
  commands.portsdiff.cpp
  commands.search.cpp
  commands.setinstalled.cpp
  commands.upgrade.cpp
  commands.version.cpp
  commands.xvsinstances.cpp
  dependencies.cpp
  export.cpp
  export.chocolatey.cpp
  export.prefab.cpp
  globalstate.cpp
  help.cpp
  input.cpp
  install.cpp
  logicexpression.cpp
  metrics.cpp
  packagespec.cpp
  paragraphparseresult.cpp
  paragraphs.cpp
  portfileprovider.cpp
  postbuildlint.buildtype.cpp
  postbuildlint.cpp
  remove.cpp
  sourceparagraph.cpp
  statusparagraph.cpp
  statusparagraphs.cpp
  tools.cpp
  triplet.cpp
  update.cpp
  userconfig.cpp
  vcpkgcmdarguments.cpp
  vcpkglib.cpp
  vcpkgpaths.cpp
  versiont.cpp
  visualstudio.cpp
  vcpkglib.vcxproj -> C:\dev\vcpkg\toolsrc\msbuild.x86.release\vcpkglib.lib
  vcpkg.cpp
  Generating code
  All 24082 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Finished generating code
LINK : fatal error LNK1158: cannot run 'rc.exe' [C:\dev\vcpkg\toolsrc\vcpkg\vcpkg.vcxproj]
  vcpkgmetricsuploader.cpp
  Generating code
  All 4228 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Finished generating code
LINK : fatal error LNK1158: cannot run 'rc.exe' [C:\dev\vcpkg\toolsrc\vcpkgmetricsuploader\vcpkgmetricsuploader.vcxproj
]
C:\dev\vcpkg\scripts\bootstrap.ps1 : Building vcpkg.exe failed. Please ensure you have installed Visual Studio with the Desktop C++ workload and the Windows SDK for Desktop C++.
At line:1 char:4
+ & {& 'C:\dev\vcpkg\scripts\bootstrap.ps1' }
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,bootstrap.ps1


C:\dev\vcpkg>

**Comment by cgolchert** [comment]
I can understand some of this isn't the fault of the vcpkg project... but then it IS "**microsoft**
/vcpkg" and none of this stuff broke without being 100% from MS.

**Comment by PhoebeHui** [comment]
From you log 'LINK : fatal error LNK1158: cannot run 'rc.exe'. It seems it still has some issue in windows set up.

Open VS2015 x64 Native tools command: 
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC>where rc
C:\Program Files (x86)\Windows Kits\10\bin\x64\rc.exe

**Comment by cgolchert** [comment]
This was the Visual Studio team screwing things up.  I ended up nuking vs2015 and bumping to 2017..

on to other crap not working because of MS.
