### ISSUE TITLE
vcpkg should recover from failed port upgrades

### ISSUE THREAD

**Issue by rkitover** [microsoft/vcpkg#12658]
****

**Is your feature request related to a problem? Please describe.**

When a build fails for a port upgrade, the previous version has been removed, and your project will no longer build.

**Proposed solution**

Before removing the previous version of a port for an upgrade, back it up. If the upgrade fails, restore the backup.

**Comment by rkitover** [comment]
An alternative and much simpler solution would be to defer the removal of the installed package until after the successful build of the new version.

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/4360
