### ISSUE TITLE
librsb

### ISSUE THREAD

**Issue by ChrisNabold** [microsoft/vcpkg#12651]
Is it possible to add the package librsb for sparse matrices?
Currently several packages are outdated eg. armadillo, gsl,  sundials mathgl. How can these package be updated to the actual releases?
Thank you for your help

**Comment by sfhacker** [comment]
Any update on this open issue?

![image](https://user-images.githubusercontent.com/25817529/92844305-0e5c7c00-f429-11ea-8308-4ac7856e9e50.png)

**Comment by ChrisNabold** [comment]
Dear John,

 

I am a rather new user and don’t have much experience using cmake.

Thank you for your efforts. Is it possible do download/install the sundials library? Is it possible to install the libraries with vcpkg?

Alternatively is it possible to send me some info how you created the libraries?

 

Thank you, best regards

Chris Nabold

**Comment by sfhacker** [comment]
You don't need vcpkg to build and install any library/program.
Just download the source code and type the following commands:

a) cmake <whatever option you need/like> ..
b) make all
c) make install

There are plenty of online tutorials about cmake! So .... there is no excuse.

**Comment by sfhacker** [comment]
This issue is almost two months old! Any update on it?

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
