### ISSUE TITLE
[New Port Request] libE57Format

### ISSUE THREAD

**Issue by tblut** [microsoft/vcpkg#12650]
Library name: libE57Format

Library description: A library to provide read & write support for the E57 file format.

Source repository URL: [https://github.com/asmaloney/libE57Format](https://github.com/asmaloney/libE57Format)

Project homepage (if different from the source repository): [https://github.com/asmaloney/libE57Format](https://github.com/asmaloney/libE57Format)

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
