### ISSUE TITLE
find_program to find pkg-config use REQUIRED 

### ISSUE THREAD

**Issue by mllw** [microsoft/vcpkg#12662]
**Describe the bug**

**Environment**
- OS: Windows
- Compiler:  Visual studio 2019

**To Reproduce**
1. ./vcpkg install boost
2. See error
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x86-windows...
Starting package 1/90: bzip2:x86-windows
Building package bzip2[core]:x86-windows...
Could not locate cached archive: C:\Users\sp\AppData\Local\vcpkg\archives\ca\ca870ac55962fdf2d70d629065a53de5e6be0169.zip
-- Using cached E:/github/cxx/vcpkg/downloads/bzip2-1.0.6.tar.gz
-- Cleaning sources at E:/github/cxx/vcpkg/buildtrees/bzip2/src/1.0.6-8838f21f8e.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/github/cxx/vcpkg/downloads/bzip2-1.0.6.tar.gz
-- Applying patch fix-import-export-macros.patch
-- Applying patch fix-windows-include.patch
-- Using source at E:/github/cxx/vcpkg/buildtrees/bzip2/src/1.0.6-8838f21f8e.clean
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Fixing pkgconfig
**CMake Error at scripts/cmake/vcpkg_fixup_pkgconfig.cmake:279 (find_program):**
  Could not find PKGCONFIG using the following names: pkg-config
Call Stack (most recent call first):
  ports/bzip2/portfile.cmake:51 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:79 (include)

Error: Building package bzip2:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: bzip2:x86-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.

at scripts/cmake/vcpkg_fixup_pkgconfig.cmake:279 
find_program(PKGCONFIG pkg-config PATHS "bin" "/usr/bin" "/usr/local/Cellar/pkg-config/0.29.2_3" REQUIRED)
### use REQUIRED will not goto vcpkg_acquire_msys to get msys

if(NOT PKGCONFIG)
        find_program(PKGCONFIG pkg-config PATHS "bin" "/usr/bin" "/usr/local/Cellar/pkg-config/0.29.2_3" REQUIRED)
        if(NOT PKGCONFIG AND CMAKE_HOST_WIN32)
            vcpkg_acquire_msys(MSYS_ROOT PACKAGES pkg-config)
            find_program(PKGCONFIG pkg-config PATHS "${MSYS_ROOT}/usr/bin" REQUIRED)
        endif()
        debug_message("Using pkg-config from: ${PKGCONFIG}")
        if(NOT PKGCONFIG AND NOT _vfpkg_SKIP_CHECK)
            message(WARNING "Unable to find pkg-config to validate *.pc files. Skipping checkes!")
            set(_vfpkg_SKIP_CHECK TRUE)
        endif()
    endif()

**Comment by GuacoIV** [comment]
I just got the same error trying to install cairo...following!

**Comment by PhoebeHui** [comment]
This issue would be fixed by PR #12569.

Close this issue as duplicate to #12565.
