### ISSUE TITLE
[protobuf] Update Protobuf package to 3.12.4

### ISSUE THREAD

**Issue by xkisu** [microsoft/vcpkg#12663]
****

**Is your feature request related to a problem? Please describe.**
Protobuf 3.12.4 fixes a mistake where 3.12.3 was mistagged, the vcpkg protobuf library needs to be updated to the new version.

**Proposed solution**
The library needs to updated to 3.12.4

**Additional context**
Link to the Protobuf issue about 3.12.3: https://github.com/protocolbuffers/protobuf/issues/7632

**Comment by JonLiu1993** [comment]
Relate to #12918

**Comment by jozefizso** [comment]
Is this issue still relevant as protobuf port was updated to higher version then 3.12.4?
