### ISSUE TITLE
libpng:x64-windows build failure

### ISSUE THREAD

**Issue by grandmaster789** [microsoft/vcpkg#12668]
- OS: windows
- Compiler: MSVC v19.26.28806 for x64 (Visual Studio 2019)

`./vcpkg install libpng:x64-windows`

**Failure logs** 
CMake Error at scripts/cmake/vcpkg_fixup_pkgconfig.cmake:279 (find_program):
  Could not find PKGCONFIG using the following names: pkg-config
Call Stack (most recent call first):
  ports/libpng/portfile.cmake:117 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:79 (include)

Error: Building package libpng:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libpng:x64-windows
  Vcpkg version: 2020.06.15-nohash

**Additional context**
afaik PKGCONFIG stuff is incompatible with windows

**Comment by StarGate-One** [comment]
@grandmaster789 see https://github.com/microsoft/vcpkg/issues/12565#issuecomment-664047785 - download the **vcpkg_fixup_pkgconfig.cmake.txt** and rename it to **vcpkg_fixup_pkgconfig.cmake** and drop it into **[vcpkg-root]\scripts\cmake** (over writing the existing one or rename the existing one if you like) and you should be good to go while waiting for the official patch to make it to master.

**Comment by linquize** [comment]
No problem for me using c0f23c6c31ea7af5a751ea48a043dc64a872f4a0.

**Comment by PhoebeHui** [comment]
This issue has been fixed, please get vcpkg latest source and try again.
