### ISSUE TITLE
Support waf and pkg-config?

### ISSUE THREAD

**Issue by bagong** [Microsoft/vcpkg#1266]
Hi,

I am trying to create a aubio port. The buildsystem is python/waf based, which to some degree can be handled with acquiring python and vcpkg_execute_required_process (if I've puzzled this out correctly). But some advanced build options (integrating fftw3, libsndfile, ffmpeg) *depend* on the availability of pkg-config. Do I see correctly that this is currently not possible and in a way against the vcpkg "philosophy"? Otoh, c/c++-packages with a unix-background usually have good pkg-config support, and it actually does work on Windows if one installs it properly.

**Comment by Voskrese** [comment]
@bagong я сам сейчас разбираюсь и очень многие моменты не ясны, но то что pkg-config работает в среде windows это я подтверждаю. а вот поиск пакетов cmake не могу настроить вне окружения vkpkg
к тому же не яно с интеграцией Qt

> I myself now and understand very many points are unclear, but what is that pkg-config works in windows, this Wednesday I confirm. and here's a search package cmake can't configure out vkpkg environment
> Besides not Yano with integration of Qt

https://man.openbsd.org/pkg-config.1
`set PKG_CONFIG_EXECUTABLE=E:\tools\Bin\pkg-config.exe`
`set PKG_CONFIG_PATH=E:\tools\vcpkg\installed\x86-windows\lib\pkgconfig;E:\tools\gstreamer\1.0\x86\lib\pkgconfig;E:\tools\Qt\vlc-2.2.6-win32\lib\pkgconfig;E:\tools\vala-0.12.0\lib\pkgconfig`
```
pkg-config --cflags glib-2.0
-IE:/tools/vcpkg/installed/x86-windows/include/glib-2.0 -IE:/tools/vcpkg/installed/x86-windows/lib/glib-2.0/include
```
```
pkg-config --cflags gio-2.0
-IE:/tools/vcpkg/installed/x86-windows/include/glib-2.0 -IE:/tools/vcpkg/installed/x86-windows/lib/glib-2.0/include

```

```
pkg-config --libs --cflags --static gio-2.0
-IE:/tools/vcpkg/installed/x86-windows/include/glib-2.0 -IE:/tools/vcpkg/installed/x86-windows/lib/glib-2.0/include -LE:/tools/vcpkg/installed/x86-windows/lib -lgio-2.0 -lzlib1 -lws2_32 -lgmodule-2.0 -lgobject-2.0 -lglib-2.0 -lintl -liconv
```

```
cmake --find-package -DNAME=Qt5Charts -DLANGUAGE=C -DCOMPILER_ID=GNU -DMODE=COMPILE
-IE:/tools/vcpkg/installed/x86-windows/include/ -IE:/tools/vcpkg/installed/x86-windows/include/QtCharts -IE:/tools/vcpkg/installed/x86-windows/include/QtWidgets -IE:/tools/vcpkg/installed/x86-windows/include/QtGui -IE:/tools/vcpkg/installed/x86-windows/include/QtCore -IE:/tools/vcpkg/installed/x86-windows/share/qt5//mkspecs/win32-msvc2017
```
??
mkspecs/win32-msvc2017

**Comment by JackBoosY** [comment]
Please open a new issue if this is still a problem for you.
Thx.
