### ISSUE TITLE
[mathgl] build failure x64-windows with feature fltk

### ISSUE THREAD

**Issue by StarGate-One** [microsoft/vcpkg#12670]
**Host Environment**
- OS: [Microsoft Windows [Version 10.0.19041.388]]
- Compiler:
   - Visual Studio 2017 Version: 15.9.25  VS Tools Version: 14.16.27023 
   - Visual Studio 2019 Version: 16.6.5  VS Tools Version: 14.26.28801

**To Reproduce**
- **`git pull`** to update vcpkg which included PR #12273 Commit https://github.com/microsoft/vcpkg/commit/7938ab75c157f221bf1ee6b3df2ed1b27728744c made changes to port `[fltk] Force static library due to global variables. Fix CMake Targets`
- **`set VCPKG_DEFAULT_TRIPLET=x64-windows`**
- **`vcpkg install mathgl[core,fltk,gif,glut,gsl,hdf5,jpeg,opengl,png,zlib]:x64-windows --editable`**

**Failure logs** 
- Cut and past the appropriate build messages from the console output.
`Computing installation plan...`
`The following packages will be built and installed:`
`    mathgl[core,fltk,gif,glut,gsl,hdf5,jpeg,opengl,png,zlib]:x64-windows`
`Detecting compiler hash for triplet x64-windows...`
`Starting package 1/1: mathgl:x64-windows`
`Building package mathgl[core,fltk,gif,glut,gsl,hdf5,jpeg,opengl,png,zlib]:x64-windows...`
`-- Trying auto-select mirror...`
`-- Using cached D:/Git/vcpkg.downloads/mathgl-2.4.3.tar.gz`
`-- Extracting source D:/Git/vcpkg.downloads/mathgl-2.4.3.tar.gz`
`-- Applying patch type_fix.patch`
`-- Applying patch fix_cmakelists_and_cpp.patch`
`-- Using source at D:/Git/vs2017.prod/buildtrees/mathgl/src/e47fc8171c-45e0c002a6`
`-- Configuring x64-windows`
`-- Building x64-windows-dbg`
`CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):`
`    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v`
`    Working Directory: D:/Git/vs2017.prod/buildtrees/mathgl/x64-windows-dbg`
`    See logs for more information:`
`      D:\Git\vs2017.prod\buildtrees\mathgl\install-x64-windows-dbg-out.log`
` `
`Call Stack (most recent call first):`
`  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)`
`  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)`
`  ports/mathgl/portfile.cmake:34 (vcpkg_install_cmake)`
`  scripts/ports.cmake:79 (include)`
` `
`Error: Building package mathgl:x64-windows failed with: BUILD_FAILED`
`Please ensure you're using the latest portfiles with `.\vcpkg update`, then`
`submit an issue at https://github.com/Microsoft/vcpkg/issues including:`
`  Package: mathgl:x64-windows`
`  Vcpkg version: 2020.06.15-nohash`
` `
`Additionally, attach any relevant sections from the log files above.`

- Please attach any additional failure logs mentioned in the console output.
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/5007567/install-x64-windows-dbg-out.log)
inside log:
`FAILED: widgets/mgl-fltkd.dll widgets/mgl-fltkd.lib `
`ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:widgets\CMakeFiles\mgl-fltk.dir/intermediate.manifest widgets\CMakeFiles\mgl-fltk.dir/manifest.res" failed (exit code 1319) with the following output:`
`fltkd.lib(Fl_Image.cxx.obj) : error LNK2038: mismatch detected for '_CRT_STDIO_ISO_WIDE_SPECIFIERS': value '0' doesn't match value '1' in fltk.cpp.obj`
`fltkd.lib(Fl_Widget.cxx.obj) : error LNK2038: mismatch detected for '_CRT_STDIO_ISO_WIDE_SPECIFIERS': value '0' doesn't match value '1' in fltk.cpp.obj`
`fltkd.lib(Fl_Tooltip.cxx.obj) : error LNK2038: mismatch detected for '_CRT_STDIO_ISO_WIDE_SPECIFIERS': value '0' doesn't match value '1' in fltk.cpp.obj`
`... ... ...`

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by PhoebeHui** [comment]
@StarGate-One, thanks for reporting this issue! I will take a look at this issue.

**Comment by hyq5436** [comment]
i have the same similar, and i solved it by add precompiled macro _CRT_STDIO_ISO_WIDE_SPECIFIERS

**Comment by StarGate-One** [comment]
> i have the same similar, and i solved it by add precompiled macro _CRT_STDIO_ISO_WIDE_SPECIFIERS

@hyq5436 where did you add this macro at?

**Comment by StarGate-One** [comment]
1. Ok I figured it out 
    - I copied the CMakeLists.txt file and added the logic to add _CRT_STDIO_ISO_WIDE_SPECIFIERS for MSVC with version greater 1899 (same as in port mathgl)
    - then modiefied the  portfile.cmake to copy this new version of the CMakeLists.txt into the src directory after the extract/patches but before cmake starts the build process.
2. My only reservation is I do not know how it will affect downstream ports depending on port fltk with this new C/C++ compiler flags, as the only port I have using fltk is mathgl. This reservation also stops me from making a patch/fix pull requests to make permanent changes to master as I honestly do not want to mess the port build up for others.
3. Anyway I included the files if someone else has this issue and wants to try this, but beware you mileage may vary?? 👍🏻 Put these 2 files in the `[vcpkg-root]\ports\fltk` directory, renaming the `portfile.cmake.txt` to `portfile.cmake`:
[portfile.cmake.txt](https://github.com/microsoft/vcpkg/files/5138096/portfile.cmake.txt)
[CMakeLists.txt](https://github.com/microsoft/vcpkg/files/5138097/CMakeLists.txt)

**Comment by StarGate-One** [comment]
Closing, no longer an issue for me as we have chosen to no longer use vcpkg.

**Comment by PhoebeHui** [comment]
Reopen this issue for tracking the port bug.

**Comment by JackBoosY** [comment]
Please reopen this issue when it is fixed upstream.
