### ISSUE TITLE
[New Port Request] OpenCTM

### ISSUE THREAD

**Issue by Fedr** [microsoft/vcpkg#12675]
Library name: OpenCTM

Library description: triangular mesh compression library

Source repository URL: http://openctm.sourceforge.net/

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
