### ISSUE TITLE
Add readline or editline

### ISSUE THREAD

**Issue by nurse** [Microsoft/vcpkg#1268]
Many command line tools depend its interactive editing on readline or libedit.
But such library is not ported to Visual C++ environment yet.
If either of readline or libedit is ported, it is helpful so much.

* GNU Readline: https://cnswww.cns.cwru.edu/php/chet/readline/rltop.html
* Editline Library (libedit): http://thrysoee.dk/editline/

**Comment by bagong** [comment]
Anything that can more or less do as a drop-in replacement for readline would be lovely. Cutting down significantly on the more obscure readline features wouldn't matter ;) I'd be will to contribute modestly to a bounty on this.

**Comment by codicodi** [comment]
This one looks promising: http://mingweditline.sourceforge.net/

**Comment by nurse** [comment]
> This one looks promising: http://mingweditline.sourceforge.net/

As far as I remember it doesn't work well on non ASCII environment because it uses ReadConsoleInput.

**Comment by bagong** [comment]
Here are two interesting projects, the later a header only lib:

https://github.com/arangodb/linenoise-ng

https://github.com/yhirose/cpp-linenoise

**Comment by nurse** [comment]
> https://github.com/yhirose/cpp-linenoise

It has some Unicode related code but as far as I understand ReadConsoleInput doesn't work well for some codepoints.

> https://github.com/arangodb/linenoise-ng

I didn't know linenoise's development is so advaned. It uses ReadConsoleInputW and maybe works well. I'll check it further later.

**Comment by nurse** [comment]
I checked linenoise.
It looks good project if you want to make a tool which has readline functionality.
But it is not what I want, the drop-in replacement for readline.

**Comment by claudiofantacci** [comment]
@nurse did you try `readline` from #3504?

Also:
> I checked linenoise.

Do you mean `linenoise-ng`?

Thanks 😄

**Comment by nurse** [comment]
@qmfrederik @claudiofantacci I tried #3504 and it works fine, thanks!
