### ISSUE TITLE
How shloud i suppress CMake Warning when i could not find CMakeLists.txt

### ISSUE THREAD

**Issue by BoIrelia** [microsoft/vcpkg#12685]
I was trying to install pcl using vcpkg, then i have this following problem during the part of freeglu. I tried to hide the warning but couldn't find the CMakeLists.txt. Really hope someone can help, thanks a lot!

CMake Warning:
  Manually-specified variables were not used by the project:

    VCPKG_PLATFORM_TOOLSET
    VCPKG_SET_CHARSET_FLAG

**Comment by JonLiu1993** [comment]
@BoIrelia ,
These two functions are configured by default by vcpkg, so you don’t need to care about this warning

**Comment by JonLiu1993** [comment]
Please reopen this issue if it still be a problem for you.
