### ISSUE TITLE
Could not find dark.  Please install it via your package manager

### ISSUE THREAD

**Issue by BoIrelia** [microsoft/vcpkg#12686]
i'm Building package kinectsdk1:x64-linux, but have this error "Could not find dark.  Please install it via your package manager". And i could not find this dark or even install wixtoolset, could anybody help thanks a lot.

**Comment by linquize** [comment]
kinectsdk1 currently supports Windows only.

**Comment by BoIrelia** [comment]
> kinectsdk1 currently supports Windows only.
got it, and really thanks!
