### ISSUE TITLE
[openexr] build failure

### ISSUE THREAD

**Issue by zth1001** [microsoft/vcpkg#12696]
**Host Environment**
- OS: [e.g. Windows/Linux etc...]
- Compiler: revision
Windows 
vcpkg version 2020.6.15
**To Reproduce**
./vcpkg install ogre

**Failure logs** 
power shell exception
see attached logs
[stdout-x86-windows.log](https://github.com/microsoft/vcpkg/files/5012274/stdout-x86-windows.log)

[install-x86-windows-rel-out-1.log](https://github.com/microsoft/vcpkg/files/5012275/install-x86-windows-rel-out-1.log)

**Comment by NancyLi1013** [comment]
Hi @zth1001 
Thanks for posting this issue.
```
-- Restarting Build without parallelism because memory exceeded
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:139 (message):
```
It seems that there is no enough space on your local. Could you please check this?

I also found this info from `install-x86-windows-rel-out-1.log`:
```
LINK : fatal error LNK1104: cannot open file 'bin\IlmImfUtilTest.exe'
ninja: build stopped: subcommand failed.
```
Could you please also check if `IlmImfUtilTest.exe` exists on your local?

**Comment by NancyLi1013** [comment]
@zth1001 

Does this issue still exist on your local?

**Comment by NancyLi1013** [comment]
Closing this issue for now since there is no response in a long time.
