### ISSUE TITLE
How do I see/trigger debug_message()?

### ISSUE THREAD

**Issue by ray42** [microsoft/vcpkg#12694]
I am trying to debug a problem with one of the packages we use which suddenly stopped installing properly. This only happens on our Jenkins job, I don't see this build failure locally, so it might be hard to reproduce. `protobuf` keeps on failing after the commit  with hash `458c20e94b9f558b523f` (where the protobuf port and vcpkg_fixup_pkgconfig.cmake is modified), this is the error:
```
-- Fixing pkgconfig - debug
-- Checking file: C:/Jenkins/workspace/VcPkg/packages/protobuf_x86-windows/debug/lib/pkgconfig/protobuf-lite.pc
-- Checking file: C:/Jenkins/workspace/VcPkg/packages/protobuf_x86-windows/debug/lib/pkgconfig/protobuf.pc
-- CHECK_LIB_protobuf-lited_DEBUG:CHECK_LIB_protobuf-lited_DEBUG-NOTFOUND

CMake Error at scripts/cmake/vcpkg_fixup_pkgconfig.cmake:239 (message):
  Library "protobuf-lited" was not found! If it is a system library use the
  SYSTEM_LIBRARIES parameter for the vcpkg_fixup_pkgconfig call! Otherwise,
  correct the *.pc file
Call Stack (most recent call first):
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:348 (vcpkg_fixup_pkgconfig_check_files)
  ports/protobuf/portfile.cmake:136 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:79 (include)


Error: Building package protobuf:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: protobuf:x86-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.
The following packages need to be built:
    protobuf:x86-windows
There are packages that have not been built.
To build them, run:
    vcpkg install protobuf:x86-windows
```
I want to make sure that `vcpkg_fixup_pkgconfig_check_files` is looking in the correct location since protobuf-lited is indeed built. I see lots of `debug_message(...)` is called, but I don't know where are they logged or how to trigger the debug/verbose output. How do I do this?

Additionally, any help with getting `protobuf` building is greatly appreciated.

**Comment by Neumann-A** [comment]
`set(PORT_DEBUG ON)` in the triplet or the portfile `debug_message` is defined in `scripts/port.cmake`

**Comment by JackBoosY** [comment]
BTW, this issue is solved.

**Comment by Andrej730** [comment]
Just wanted to mention here an alternative - `vcpkg install --cmake-args=-DPORT_DEBUG=ON` (`--cmake-args` is not currently documented, see https://github.com/MicrosoftDocs/vcpkg-docs/issues/561)
