### ISSUE TITLE
Generate pdbs for CMake libraries in Release mode [was: how to use `RelWithDebInfo`]

### ISSUE THREAD

**Issue by KindDragon** [Microsoft/vcpkg#127]
I want pdb for Release build

**Comment by ras0219-msft** [comment]
The issue with `RelWithDebInfo` is that CMake defaults to lower optimization levels :(. Instead, we should just always emit pdbs in `Release` mode by changing the settings.

I've pushed a branch `release-pdbs` with a change that enables `/Zi` and `/DEBUG` -- this works for `libpng`, but I haven't tested it more thoroughly yet. Please pull it and try it out.

**Comment by ras0219-msft** [comment]
Should be fixed by 711c4ec. Thanks for reporting this!

**Comment by ncook-hxgn** [comment]
> I want pdb for Release build

and so does binskim :)
