### ISSUE TITLE
Raylib's audio module not working 

### ISSUE THREAD

**Issue by valenotary** [microsoft/vcpkg#12707]
**Describe the bug**
Using vcpkg on the visual studio IDE, the project using raylib's audio module fails to build due to unresolved external symbols.

**Environment**
- OS: Windows
- Compiler: MVSC (cl.exe)

**To Reproduce**
1. ./vcpkg install raylib
2. Attempt to build a MSVC project that uses raylib's audio module (see attached link for picture of code)

**Expected behavior**
I expect it to just work out of the box. In previous versions of the vcpkg port I had no issues with it, but it seems that this newest one has some issues with the audio module (and possibly other modules as well!)

**Failure logs** 
[https://gyazo.com/92513df5f8693fe4037130f7194a6c10](url)

**Comment by PhoebeHui** [comment]
@valenotary, thanks for reporting this issue!

I have summited PR #12783 to fix this issue
