### ISSUE TITLE
zlib:x64-windows build failure

### ISSUE THREAD

**Issue by evalen43** [microsoft/vcpkg#12702]
**Host Environment**
- OS: Windows
- Compiler: revision

**To Reproduce**
`./vcpkg install zlib:x64-windows

**Failure logs** 
-CMake Error at scripts/cmake/vcpkg_fixup_pkgconfig.cmake:279 (find_program)
-Call Stack (most recent call first)
ports/zlib/portfile.cmake:46 (vcpkg_fixup_pkgconfig)
scripts/ports.cmake:79 (include)

**Additional context**
Package: zlib:x64-windows
Vcpkg version:2020.06.15-nohash

**Comment by Neumann-A** [comment]
should have been fixed by e29945735164d0a2595be24cd897a84b64160553. Please update you vcpkg checkout

**Comment by PhoebeHui** [comment]
This issue has been fixed, please get vcpkg latest source and try again.
