### ISSUE TITLE
tinyxmls2:x64-windows building package failure

### ISSUE THREAD

**Issue by evalen43** [microsoft/vcpkg#12700]
**Host Environment**
- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**
`./vcpkg install tinyxml2:64-windows`

**Failure logs** 
-Package: tinyxml2:64:windows.
-Vcpkg version: 2020.06.15-nohash
**Additional context**
CMake Error at scripts/cmake/vcpkg_fixup_pkgconfig.cmake:279
Could not find PKGCONFIG using the following names: pkg-config
Call Stack (most recent call first):
ports/tinyxml2/portfile.cmake;20 (vcpkg_fixup_pkgconfig
scripts/ports.cmake:79 (include)
Error: Building package tinyxml2:64-windows failed with: BUILD_FILED

**Comment by Neumann-A** [comment]
should have been fixed by e299457. Please update you vcpkg checkout

**Comment by PhoebeHui** [comment]
This issue has been fixed, please get vcpkg latest source and try again.
