### ISSUE TITLE
MSBuild integration: "Using triplet" message has high importance (again)

### ISSUE THREAD

**Issue by gix** [microsoft/vcpkg#12712]
I'm submitting bug #12164 again. It was fixed in f24543e83134c0199df370d683f69641fc66c44a but overwritten and reverted again in the next commit c21893b4dc68430ebcf028ffdb190e586fc3d639.

**Describe the bug**
vcpkg's msbuild integration (in `vcpkg.targets`) displays a message `Using triplet "x64-windows" from "<vcpkg-root>"`. Since #4361 this message has importance high (instead of the previous normal) which results in a lot of unnecessary build output. This change seems like a forgotten debugging aid missed in the review.

**To Reproduce**
1. `vcpkg install` and export any port as nuget.
2. Add the nuget package to a C++ project in Visual Studio.
3. Build with the default MSBuild verbosity (Minimal).

**Expected behavior**
No message.

**Comment by Neumann-A** [comment]
Personally I think this falls into the category: Some people like the verbose output and some people don't. As far as I remember with Normal importance the message sometimes got not displayed if the triplet was changed which can lead to confusion.

**Comment by gix** [comment]
If you like the verbose output, then increase your build verbosity. Otherwise this message is IMO not significant enough to bloat an otherwise minimal build output.

**Comment by PhoebeHui** [comment]
@gix, thanks for reporting this issue!

I have summited PR #12727 to revert the changes.
