### ISSUE TITLE
windows 10/ cmake 3.18.0-rc2 fails building devil

### ISSUE THREAD

**Issue by ridetpro1994** [microsoft/vcpkg#12721]
vcpkg install devil:x86-windows-static
Computing installation plan...
The following packages will be built and installed:
devil[core,jasper,lcms,libjpeg,libpng,openexr,tiff]:x86-windows-static

libffi[core]:x86-windows-static
liblzma[core]:x86-windows-static
libpng[core]:x86-windows-static
openexr[core]:x86-windows-static
openssl[core]:x86-windows-static
openssl-windows[core]:x86-windows-static
python3[core]:x86-windows-static
tiff[core]:x86-windows-static
zlib[core]:x86-windows-static
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x86-windows-static...
Starting package 1/10: zlib:x86-windows-static
Building package zlib[core]:x86-windows-static...
Could not locate cached archive: C:\Users\Ira\AppData\Local\vcpkg\archives\d3\d3bcac927dea0086928c96d44671fdb8b635db43.zip
-- Using community triplet x86-windows-static. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: C:\Program Files (x86)\vcpkg\triplets\community\x86-windows-static.cmake
-- Using cached C:/Program Files (x86)/vcpkg/downloads/zlib1211.tar.gz
-- Cleaning sources at C:/Program Files (x86)/vcpkg/buildtrees/zlib/src/1.2.11-deec42f53b.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Program Files (x86)/vcpkg/downloads/zlib1211.tar.gz
-- Applying patch cmake_dont_build_more_than_needed.patch
-- Using source at C:/Program Files (x86)/vcpkg/buildtrees/zlib/src/1.2.11-deec42f53b.clean
-- Configuring x86-windows-static
-- Building x86-windows-static-dbg
-- Building x86-windows-static-rel
-- Fixing pkgconfig
-- Acquiring MSYS2...
-- Using cached C:/Program Files (x86)/vcpkg/downloads/msys2-base-x86_64-20190524.tar.xz
-- Using cached C:/Program Files (x86)/vcpkg/downloads/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz
-- Using cached C:/Program Files (x86)/vcpkg/downloads/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig
gpg: /etc/pacman.d/gnupg/trustdb.gpg: trustdb created
gpg: no ultimately trusted keys found
gpg: starting migration from earlier GnuPG versions
gpg: porting secret keys from '/etc/pacman.d/gnupg/secring.gpg' to gpg-agent
gpg: migration succeeded
gpg: Generating pacman keyring master key...
gpg: key A6D47F70EE8A91DE marked as ultimately trusted
gpg: directory '/etc/pacman.d/gnupg/openpgp-revocs.d' created
gpg: revocation certificate stored as '/etc/pacman.d/gnupg/openpgp-revocs.d/39E602025AD01355238440F1A6D47F70EE8A91DE.rev'
gpg: Done
==> Updating trust database...
gpg: marginals needed: 3 completes needed: 1 trust model: pgp
gpg: depth: 0 valid: 1 signed: 0 trust: 0-, 0q, 0n, 0m, 0f, 1u
==> Appending keys from msys2.gpg...
==> Locally signing trusted keys in keyring...
-> Locally signing key D55E7A6D7CE9BA1587C0ACACF40D263ECA25678A...
-> Locally signing key 123D4D51A1793859C2BE916BBBE514E53E0D0813...
-> Locally signing key B91BCF3303284BF90CC043CA9F418C233E652008...
-> Locally signing key 9DD0D4217D75A33B896159E6DA7EF2ABAEEA755C...
==> Importing owner trust values...
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: inserting ownertrust of 4
==> Updating trust database...
gpg: marginals needed: 3 completes needed: 1 trust model: pgp
gpg: depth: 0 valid: 1 signed: 4 trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: depth: 1 valid: 4 signed: 3 trust: 0-, 0q, 0n, 4m, 0f, 0u
gpg: depth: 2 valid: 3 signed: 0 trust: 3-, 0q, 0n, 0m, 0f, 0u
/usr/bin/bash: -c: line 0: syntax error near unexpected token (' /usr/bin/bash: -c: line 0: PATH=/usr/bin;pacman-key --verify C:/Program Files (x86)/vcpkg/downloads/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig'
CMake Error at scripts/cmake/vcpkg_acquire_msys.cmake:114 (message):
Cannot verify MSYS2 keyring.
Call Stack (most recent call first):
scripts/cmake/vcpkg_fixup_pkgconfig.cmake:281 (vcpkg_acquire_msys)
ports/zlib/portfile.cmake:46 (vcpkg_fixup_pkgconfig)
scripts/ports.cmake:79 (include)

**Comment by StarGate-One** [comment]
You could just create vcpkg again from scratch, but I definitely would not use 3.18.0-rc2 and 3.18.1 has been released
**- OR -**
1. I would suggest to download/install a release version of CMake, 3.18.1 is out now (https://github.com/Kitware/CMake/releases/download/v3.18.1/cmake-3.18.1-win64-x64.msi -or-
https://github.com/Kitware/CMake/releases/download/v3.18.1/cmake-3.18.1-win32-x86.msi) depending on your machine architechture.
2. open command or powershell prompt
3. cd [vcpkg-root]
4. git pull
5. .\bootstrap-vcpkg.bat
6. move .\downloads\tools\msys2 .\downloads\tools\msys2.old
7. .\vcpkg install devil:x86-windows-static

- There has been many changes to vcpkg the past 2 weeks relating to msys2 changes (vcpkg_acquire_msys.cmake) and cmake honoring the `required` option on find_program macro in 3.18.0 and above, best to get new sources and bootstrap again

**Comment by JackBoosY** [comment]
You can also remove _VCPKG/downloads/tools/msys2_ and rebuild.

**Comment by JackBoosY** [comment]
Fixed.
