### ISSUE TITLE
[tclap:x86-windows] build failure

### ISSUE THREAD

**Issue by exhdev** [microsoft/vcpkg#12720]
**Host Environment**
- OS: Windows 10
- Compiler: Visual Studio 2019
- Package: tclap:x86-windows
- Vcpkg version: 2020.06.15-nohash

**To Reproduce**
- git clone https://github.com/microsoft/vcpkg
- .\vcpkg\bootstrap-vcpkg.bat
- .\vcpkg\vcpkg install glfw3 glew tclap jsoncpp eigen3
- .\vcpkg\vcpkg install tclap

All packages installed fine except tclap. Also tried tclap install by itself, same error. 

**Failure logs** 
C:\dev>.\vcpkg\vcpkg install tclap
Computing installation plan...
The following packages will be built and installed:
    tclap[core]:x86-windows
Detecting compiler hash for triplet x86-windows...
Starting package 1/1: tclap:x86-windows
Building package tclap[core]:x86-windows...
Could not locate cached archive: C:\Users\X\AppData\Local\vcpkg\archives\c3\c3af7207584f12726abe4dc29f9db60250a67497.zip
-- Trying auto-select mirror...
-- Downloading https://sourceforge.net/projects/tclap//files/tclap-1.2.2.tar.gz/download...
-- Downloading https://sourceforge.net/projects/tclap//files/tclap-1.2.2.tar.gz/download... Failed. Status: 35;"SSL connect error"
CMake Warning at scripts/cmake/vcpkg_download_distfile.cmake:190 (message):

      Failed to download file.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_sourceforge.cmake:152 (vcpkg_download_distfile)
  ports/tclap/portfile.cmake:1 (vcpkg_from_sourceforge)
  scripts/ports.cmake:79 (include)

-- Trying mirror cfhcable...
-- Downloading https://sourceforge.net/projects/tclap//files/tclap-1.2.2.tar.gz/download?use_mirror=cfhcable...
-- Downloading https://sourceforge.net/projects/tclap//files/tclap-1.2.2.tar.gz/download?use_mirror=cfhcable... Failed. Status: 35;"SSL connect error"
CMake Warning at scripts/cmake/vcpkg_download_distfile.cmake:190 (message):

      Failed to download file.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_sourceforge.cmake:167 (vcpkg_download_distfile)
  ports/tclap/portfile.cmake:1 (vcpkg_from_sourceforge)
  scripts/ports.cmake:79 (include)

-- Trying mirror pilotfiber...
-- Downloading https://sourceforge.net/projects/tclap//files/tclap-1.2.2.tar.gz/download?use_mirror=pilotfiber...
-- Downloading https://sourceforge.net/projects/tclap//files/tclap-1.2.2.tar.gz/download?use_mirror=pilotfiber... Failed. Status: 35;"SSL connect error"
CMake Warning at scripts/cmake/vcpkg_download_distfile.cmake:190 (message):

      Failed to download file.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_sourceforge.cmake:167 (vcpkg_download_distfile)
  ports/tclap/portfile.cmake:1 (vcpkg_from_sourceforge)
  scripts/ports.cmake:79 (include)

-- Trying mirror gigenet...
-- Downloading https://sourceforge.net/projects/tclap//files/tclap-1.2.2.tar.gz/download?use_mirror=gigenet...
-- Downloading https://sourceforge.net/projects/tclap//files/tclap-1.2.2.tar.gz/download?use_mirror=gigenet... Failed. Status: 35;"SSL connect error"
CMake Warning at scripts/cmake/vcpkg_download_distfile.cmake:190 (message):

      Failed to download file.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_sourceforge.cmake:167 (vcpkg_download_distfile)
  ports/tclap/portfile.cmake:1 (vcpkg_from_sourceforge)
  scripts/ports.cmake:79 (include)

-- Trying mirror versaweb...
-- Downloading https://sourceforge.net/projects/tclap//files/tclap-1.2.2.tar.gz/download?use_mirror=versaweb...
-- Downloading https://sourceforge.net/projects/tclap//files/tclap-1.2.2.tar.gz/download?use_mirror=versaweb... Failed. Status: 35;"SSL connect error"
CMake Warning at scripts/cmake/vcpkg_download_distfile.cmake:190 (message):

      Failed to download file.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_sourceforge.cmake:167 (vcpkg_download_distfile)
  ports/tclap/portfile.cmake:1 (vcpkg_from_sourceforge)
  scripts/ports.cmake:79 (include)

-- Trying mirror ayera...
-- Downloading https://sourceforge.net/projects/tclap//files/tclap-1.2.2.tar.gz/download?use_mirror=ayera...
-- Downloading https://sourceforge.net/projects/tclap//files/tclap-1.2.2.tar.gz/download?use_mirror=ayera... Failed. Status: 35;"SSL connect error"
CMake Warning at scripts/cmake/vcpkg_download_distfile.cmake:190 (message):

      Failed to download file.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_sourceforge.cmake:167 (vcpkg_download_distfile)
  ports/tclap/portfile.cmake:1 (vcpkg_from_sourceforge)
  scripts/ports.cmake:79 (include)

-- Trying mirror netactuate...
-- Downloading https://sourceforge.net/projects/tclap//files/tclap-1.2.2.tar.gz/download?use_mirror=netactuate...
-- Downloading https://sourceforge.net/projects/tclap//files/tclap-1.2.2.tar.gz/download?use_mirror=netactuate... Failed. Status: 35;"SSL connect error"
CMake Warning at scripts/cmake/vcpkg_download_distfile.cmake:190 (message):

      Failed to download file.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_sourceforge.cmake:167 (vcpkg_download_distfile)
  ports/tclap/portfile.cmake:1 (vcpkg_from_sourceforge)
  scripts/ports.cmake:79 (include)

-- Trying mirror phoenixnap...
-- Downloading https://sourceforge.net/projects/tclap//files/tclap-1.2.2.tar.gz/download?use_mirror=phoenixnap...
-- Downloading https://sourceforge.net/projects/tclap//files/tclap-1.2.2.tar.gz/download?use_mirror=phoenixnap... Failed. Status: 35;"SSL connect error"
CMake Warning at scripts/cmake/vcpkg_download_distfile.cmake:190 (message):

      Failed to download file.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_sourceforge.cmake:167 (vcpkg_download_distfile)
  ports/tclap/portfile.cmake:1 (vcpkg_from_sourceforge)
  scripts/ports.cmake:79 (include)

-- Trying mirror astuteinternet...
-- Downloading https://sourceforge.net/projects/tclap//files/tclap-1.2.2.tar.gz/download?use_mirror=astuteinternet...
-- Downloading https://sourceforge.net/projects/tclap//files/tclap-1.2.2.tar.gz/download?use_mirror=astuteinternet... Failed. Status: 35;"SSL connect error"
CMake Warning at scripts/cmake/vcpkg_download_distfile.cmake:190 (message):

      Failed to download file.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_sourceforge.cmake:167 (vcpkg_download_distfile)
  ports/tclap/portfile.cmake:1 (vcpkg_from_sourceforge)
  scripts/ports.cmake:79 (include)

-- Trying mirror freefr...
-- Downloading https://sourceforge.net/projects/tclap//files/tclap-1.2.2.tar.gz/download?use_mirror=freefr...
-- Downloading https://sourceforge.net/projects/tclap//files/tclap-1.2.2.tar.gz/download?use_mirror=freefr... Failed. Status: 35;"SSL connect error"
CMake Warning at scripts/cmake/vcpkg_download_distfile.cmake:190 (message):

      Failed to download file.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_sourceforge.cmake:167 (vcpkg_download_distfile)
  ports/tclap/portfile.cmake:1 (vcpkg_from_sourceforge)
  scripts/ports.cmake:79 (include)

-- Trying mirror netcologne...
-- Downloading https://sourceforge.net/projects/tclap//files/tclap-1.2.2.tar.gz/download?use_mirror=netcologne...
-- Downloading https://sourceforge.net/projects/tclap//files/tclap-1.2.2.tar.gz/download?use_mirror=netcologne... Failed. Status: 35;"SSL connect error"
CMake Warning at scripts/cmake/vcpkg_download_distfile.cmake:190 (message):

      Failed to download file.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_sourceforge.cmake:167 (vcpkg_download_distfile)
  ports/tclap/portfile.cmake:1 (vcpkg_from_sourceforge)
  scripts/ports.cmake:79 (include)

-- Trying mirror deac-riga...
-- Downloading https://sourceforge.net/projects/tclap//files/tclap-1.2.2.tar.gz/download?use_mirror=deac-riga...
-- Downloading https://sourceforge.net/projects/tclap//files/tclap-1.2.2.tar.gz/download?use_mirror=deac-riga... Failed. Status: 35;"SSL connect error"
CMake Warning at scripts/cmake/vcpkg_download_distfile.cmake:190 (message):

      Failed to download file.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_sourceforge.cmake:167 (vcpkg_download_distfile)
  ports/tclap/portfile.cmake:1 (vcpkg_from_sourceforge)
  scripts/ports.cmake:79 (include)

-- Trying mirror excellmedia...
-- Downloading https://sourceforge.net/projects/tclap//files/tclap-1.2.2.tar.gz/download?use_mirror=excellmedia...
-- Downloading https://sourceforge.net/projects/tclap//files/tclap-1.2.2.tar.gz/download?use_mirror=excellmedia... Failed. Status: 35;"SSL connect error"
CMake Warning at scripts/cmake/vcpkg_download_distfile.cmake:190 (message):

      Failed to download file.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_sourceforge.cmake:167 (vcpkg_download_distfile)
  ports/tclap/portfile.cmake:1 (vcpkg_from_sourceforge)
  scripts/ports.cmake:79 (include)

-- Trying mirror iweb...
-- Downloading https://sourceforge.net/projects/tclap//files/tclap-1.2.2.tar.gz/download?use_mirror=iweb...
-- Downloading https://sourceforge.net/projects/tclap//files/tclap-1.2.2.tar.gz/download?use_mirror=iweb... Failed. Status: 35;"SSL connect error"
CMake Warning at scripts/cmake/vcpkg_download_distfile.cmake:190 (message):

      Failed to download file.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_sourceforge.cmake:167 (vcpkg_download_distfile)
  ports/tclap/portfile.cmake:1 (vcpkg_from_sourceforge)
  scripts/ports.cmake:79 (include)

-- Trying mirror jaist...
-- Downloading https://sourceforge.net/projects/tclap//files/tclap-1.2.2.tar.gz/download?use_mirror=jaist...
-- Downloading https://sourceforge.net/projects/tclap//files/tclap-1.2.2.tar.gz/download?use_mirror=jaist... Failed. Status: 35;"SSL connect error"
CMake Warning at scripts/cmake/vcpkg_download_distfile.cmake:190 (message):

      Failed to download file.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_sourceforge.cmake:167 (vcpkg_download_distfile)
  ports/tclap/portfile.cmake:1 (vcpkg_from_sourceforge)
  scripts/ports.cmake:79 (include)

-- Trying mirror jztkft...
-- Downloading https://sourceforge.net/projects/tclap//files/tclap-1.2.2.tar.gz/download?use_mirror=jztkft...
-- Downloading https://sourceforge.net/projects/tclap//files/tclap-1.2.2.tar.gz/download?use_mirror=jztkft... Failed. Status: 35;"SSL connect error"
CMake Warning at scripts/cmake/vcpkg_download_distfile.cmake:190 (message):

      Failed to download file.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_sourceforge.cmake:167 (vcpkg_download_distfile)
  ports/tclap/portfile.cmake:1 (vcpkg_from_sourceforge)
  scripts/ports.cmake:79 (include)

-- Trying mirror managedway...
-- Downloading https://sourceforge.net/projects/tclap//files/tclap-1.2.2.tar.gz/download?use_mirror=managedway...
-- Downloading https://sourceforge.net/projects/tclap//files/tclap-1.2.2.tar.gz/download?use_mirror=managedway... Failed. Status: 35;"SSL connect error"
CMake Warning at scripts/cmake/vcpkg_download_distfile.cmake:190 (message):

      Failed to download file.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_sourceforge.cmake:167 (vcpkg_download_distfile)
  ports/tclap/portfile.cmake:1 (vcpkg_from_sourceforge)
  scripts/ports.cmake:79 (include)

-- Trying mirror nchc...
-- Downloading https://sourceforge.net/projects/tclap//files/tclap-1.2.2.tar.gz/download?use_mirror=nchc...
-- Downloading https://sourceforge.net/projects/tclap//files/tclap-1.2.2.tar.gz/download?use_mirror=nchc... Failed. Status: 35;"SSL connect error"
CMake Warning at scripts/cmake/vcpkg_download_distfile.cmake:190 (message):

      Failed to download file.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_sourceforge.cmake:167 (vcpkg_download_distfile)
  ports/tclap/portfile.cmake:1 (vcpkg_from_sourceforge)
  scripts/ports.cmake:79 (include)

-- Trying mirror netix...
-- Downloading https://sourceforge.net/projects/tclap//files/tclap-1.2.2.tar.gz/download?use_mirror=netix...
-- Downloading https://sourceforge.net/projects/tclap//files/tclap-1.2.2.tar.gz/download?use_mirror=netix... Failed. Status: 35;"SSL connect error"
CMake Warning at scripts/cmake/vcpkg_download_distfile.cmake:190 (message):

      Failed to download file.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_sourceforge.cmake:167 (vcpkg_download_distfile)
  ports/tclap/portfile.cmake:1 (vcpkg_from_sourceforge)
  scripts/ports.cmake:79 (include)

-- Trying mirror ufpr...
-- Downloading https://sourceforge.net/projects/tclap//files/tclap-1.2.2.tar.gz/download?use_mirror=ufpr...
-- Downloading https://sourceforge.net/projects/tclap//files/tclap-1.2.2.tar.gz/download?use_mirror=ufpr... Failed. Status: 35;"SSL connect error"
CMake Warning at scripts/cmake/vcpkg_download_distfile.cmake:190 (message):

      Failed to download file.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_sourceforge.cmake:167 (vcpkg_download_distfile)
  ports/tclap/portfile.cmake:1 (vcpkg_from_sourceforge)
  scripts/ports.cmake:79 (include)

-- Trying mirror tenet...
-- Downloading https://sourceforge.net/projects/tclap//files/tclap-1.2.2.tar.gz/download?use_mirror=tenet...
-- Downloading https://sourceforge.net/projects/tclap//files/tclap-1.2.2.tar.gz/download?use_mirror=tenet... Failed. Status: 35;"SSL connect error"
CMake Warning at scripts/cmake/vcpkg_download_distfile.cmake:190 (message):

      Failed to download file.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_sourceforge.cmake:167 (vcpkg_download_distfile)
  ports/tclap/portfile.cmake:1 (vcpkg_from_sourceforge)
  scripts/ports.cmake:79 (include)

CMake Error at scripts/cmake/vcpkg_from_sourceforge.cmake:182 (message):
              Couldn't download source from any of the sourceforge mirrors, please check your network.
              If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
              variables to "http[s]://user:password@your-proxy-ip-address:port/".
              Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  ports/tclap/portfile.cmake:1 (vcpkg_from_sourceforge)
  scripts/ports.cmake:79 (include)

Error: Building package tclap:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: tclap:x86-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.

**Additional context**
- I am not on a proxy server
- I am using the latest portfiles and have recently git pulled
- I've tried adding [DISABLE_SSL] to the tclap portfile per vcpkg_from_sourceforge, same SSL connect error persists

**Comment by StarGate-One** [comment]
Downloads fine for me on first try. 
File is attached - put in [vcpkg-root]\downloads folder.
[tclap-1.2.2.tar.gz](https://github.com/microsoft/vcpkg/files/5017967/tclap-1.2.2.tar.gz)

`->vcpkg install tclap --editable --only-downloads`
`Computing installation plan...`
`The following packages will be built and installed:`
 `   tclap[core]:x64-windows`
`Detecting compiler hash for triplet x64-windows...`
`Starting package 1/1: tclap:x64-windows`
`Building package tclap[core]:x64-windows...`
`-- Trying auto-select mirror...`
`-- Downloading https://sourceforge.net/projects/tclap//files/tclap-1.2.2.tar.gz/download...`
`-- Using source at D:/Git/vs2019.test/buildtrees/tclap/src/516ec17f82-3307ebc7d8`
`-- Installing: D:/Git/vs2019.test/packages/tclap_x64-windows/share/tclap/copyright`
`Downloaded sources for package tclap[core]:x64-windows`
`Elapsed time for package tclap:x64-windows: 1.443 s`

`Total elapsed time: 3.016 s`

`RESULTS`
`    tclap:x64-windows: DOWNLOADED: 1.443 s`

`SUMMARY`
`    SUCCEEDED: 0`
`    BUILD_FAILED: 0`
`    POST_BUILD_CHECKS_FAILED: 0`
`    FILE_CONFLICTS: 0`
`    CASCADED_DUE_TO_MISSING_DEPENDENCIES: 0`
`    EXCLUDED: 0`
`    DOWNLOADED: 1`
