### ISSUE TITLE
[ffmpeg] build failure

### ISSUE THREAD

**Issue by Outurnate** [microsoft/vcpkg#12722]
**Host Environment**
- OS: linux 5.7.11
- Compiler: gcc 10.1.0

**To Reproduce**
`./vcpkg install ffmpeg[x264]`

**Failure logs** 
=== CONFIGURING ===
ERROR: libx264 not found

**Additional context**
Adding --disable-opencl to x264's portfile fixes this issue

**Comment by PhoebeHui** [comment]
Confirmed that PR #11277 would fix this issue.

**Comment by PhoebeHui** [comment]
The PR has been merged, please get latest source and try again.
