### ISSUE TITLE
json5-parser build failure

### ISSUE THREAD

**Issue by jlfilion** [microsoft/vcpkg#12744]
I am running Windows 10.0.18363 with Visual Studio 2019 installed. I have updated vcpkg and I'm running git version 2.26.0.windows.1 and cmake version 3.17.0-rc3.

I installed json5-parser with the following commands:

vcpkg.exe install json5-parser:x64-windows
vcpkg.exe install json5-parser:x64-windows-static

I added to my cmake file:

find_package(json5-parser CONFIG REQUIRED)

I have been unable to get find_package(json5-parser CONFIG REQUIRED) to work. I get the following errors:

$ cmake ..
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
CMake Error at fips/CMakeLists.txt:26 (find_package):
  Could not find a package configuration file provided by "json5-parser" with
  any of the following names:

    json5-parserConfig.cmake
    json5-parser-config.cmake

  Add the installation prefix of "json5-parser" to CMAKE_PREFIX_PATH or set
  "json5-parser_DIR" to a directory containing one of the above files.  If
  "json5-parser" provides a separate development package or SDK, be sure it
  has been installed.

-- Configuring incomplete, errors occurred!

I'm quite new to this stuff, so I don't know how to "Add the installation prefix of "json5-parser" to CMAKE_PREFIX_PATH."

Everything seemed to work OK in Ubuntu.

I've included some other libraries in my build without this issue. I'm not sure why this library is different. Is there something more required by me besides installing json5-parser::x64-windows and trying to use find_package(json5-parser CONFIG REQUIRED)?

Thanks,
Joe

**Comment by NancyLi1013** [comment]
Hi @jlfilion 
Thanks for posting this issue.

Have you run `.\vcpkg integrate install `and set `CMAKE_TOOLCHAIN_FILE `to your project?

**Comment by jlfilion** [comment]
Hi @NancyLi1013 ,

Yes, I have done both of those.

I ran the integration step from git bash and obtained the following:

----
$ ./vcpkg.exe integrate install
Applied user-wide integration for this vcpkg root.

All MSBuild C++ projects can now #include any installed libraries.
Linking will be handled automatically.
Installing new libraries will make them instantly available.

CMake projects should use: "-DCMAKE_TOOLCHAIN_FILE=C:/Users/jfilion/vcpkg/scripts/buildsystems/vcpkg.cmake"
----

I then call cmake in my build directory like this:

cmake .. -DCMAKE_TOOLCHAIN_FILE=C:/Users/jfilion/vcpkg/scripts/buildsystems/vcpkg.cmake

The result is the same. The find of the json5-parser fails.

Joe

**Comment by NancyLi1013** [comment]
> -- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
> CMake Error at fips/CMakeLists.txt:26 (find_package):
> Could not find a package configuration file provided by "json5-parser" with
> any of the following names:
> 
> ```
> json5-parserConfig.cmake
> json5-parser-config.cmake
> ```

what is this ` fips/CMakeLists.txt:26`?

If I don't set `CMAKE_TOOLCHAIN_FILE`, the error will like this:

```
1> [CMake] CMake Error at F:/10821/vcpkg/scripts/buildsystems/vcpkg.cmake:286 (_find_package):
1> [CMake]   Could not find a package configuration file provided by "json5-parser" with
1> [CMake]   any of the following names:
1> [CMake] 
1> [CMake]     json5-parserConfig.cmake
1> [CMake]     json5-parser-config.cmake
1> [CMake] 
1> [CMake]   Add the installation prefix of "json5-parser" to CMAKE_PREFIX_PATH or set
1> [CMake]   "json5-parser_DIR" to a directory containing one of the above files.  If
1> [CMake]   "json5-parser" provides a separate development package or SDK, be sure it
1> [CMake]   has been installed.
1> [CMake] Call Stack (most recent call first):
1> [CMake]   CMakeProject14/CMakeLists.txt:5 (find_package)
```

**Comment by jlfilion** [comment]
Here is a snippet of my fips/CMakeLists.txt file including line 26. It's just the line that tries to find the library. Note: the find_package on line 23 seems to be working fine.

.
.
.
23: find_package(nlohmann_json CONFIG REQUIRED)
24: target_link_libraries(fips PUBLIC nlohmann_json::nlohmann_json)
25:
26: find_package(json5-parser CONFIG REQUIRED)
27: target_link_libraries(fips PRIVATE json5_parser)
28:
29: find_package(Boost REQUIRED COMPONENTS filesystem thread)
30: target_link_libraries(fips PRIVATE Boost::filesystem Boost::thread)
.
.
.

And this is the command line I used to run cmake:

 cmake .. -DCMAKE_TOOLCHAIN_FILE=C:/Users/jfilion/vcpkg/scripts/buildsystems/vcpkg.cmake

So I don't see any issue with how I am setting up the CMAKE_TOOLCHAIN_FILE variable.

Thanks,
Joe

**Comment by NancyLi1013** [comment]
Oh, I see. You used CMake command to build the cmake project. I thought you build the project via Visual Studio.

You can use `cmake  -DCMAKE_TOOLCHAIN_FILE=C:/Users/jfilion/vcpkg/scripts/buildsystems/vcpkg.cmake` to try it again.

If `nlohmann_json` can work fine, the configure should be right. Please help confirm if `nlohmann_json`  and 
`json5-parser` were installed to the same directory.

If there is still problem, please help provide the full log.

Thanks.

**Comment by jlfilion** [comment]
I'm confused. The only difference I see between what I said I ran:

cmake .. -DCMAKE_TOOLCHAIN_FILE=C:/Users/jfilion/vcpkg/scripts/buildsystems/vcpkg.cmake

and what you suggest I run:

cmake -DCMAKE_TOOLCHAIN_FILE=C:/Users/jfilion/vcpkg/scripts/buildsystems/vcpkg.cmake

are the two dots I've included to tell cmake to run one directory level up. If I run as you suggest in my build directory it won't see my CMakeLists.txt files, and if I run it one level up it will place the cmake cache where I do  not want it.

As far as the second part of your note, you ask if I've installed nlohmann_json and the json5-parser in the same directory. I have installed both simply by using the vcpkg.exe install command. I'm not sure where the libraries end up.

As far as sending you the log, what log would you like to see? A vcpkg log from when I installed the library or a log from cmake when I try to build?

Thanks for the help with this.
Joe

**Comment by NancyLi1013** [comment]
Sorry, this might be related with the path that CMakeLists.txt lists in.

If there is only one vcpkg instance on your machine, the path that `nlohmann_json` and` json5-parser `were installed should be the same. You can ignore this.

Could you please help confirm if `json5-parser-config.cmake` was in _C:/Users/jfilion/vcpkg/installed/x64-windows/share/json5-parser_?

Also please provide the log when you build the cmake project.

**Comment by jlfilion** [comment]
Hi Nancy,
Sorry about the delayed response. Technically, I'm on vacation this week (stripping wallpaper upstairs :( ). I checked for the json5-parser-config.cmake file in that directory and it does exist. I'm also including the CMake log. The odd thing about that (at least to me) is that that log doesn't have anything about the json5 parser failing.

[CMakeOutput.log](https://github.com/microsoft/vcpkg/files/5058170/CMakeOutput.log)

**Comment by NancyLi1013** [comment]
Thanks for your update. It seems there is no any error in your build log.

Could you please provide the log generated by executing `cmake .. -DCMAKE_TOOLCHAIN_FILE=C:/Users/jfilion/vcpkg/scripts/buildsystems/vcpkg.cmake`?

The following logs are from my project:
```
PS F:\tools\vcpkg\downloads\tools\cmake-3.17.2-windows\cmake-3.17.2-win32-x86\bin> .\cmake.exe -DCMAKE_TOOLCHAIN_FILE=F:\tools\vcpkg\scripts\buildsystems\vcpkg.cmake
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.


-- Building for: Visual Studio 16 2019
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
-- The C compiler identification is MSVC 19.27.29111.0
-- The CXX compiler identification is MSVC 19.27.29111.0
-- Check for working C compiler: E:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: E:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: E:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: E:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: F:/tools/vcpkg/downloads/tools/cmake-3.17.2-windows/cmake-3.17.2-win32-x86/bin
```

**Comment by jlfilion** [comment]
Sure. But it's not real interesting:

$ cmake .. -DCMAKE_TOOLCHAIN_FILE=C:/Users/jfilion/vcpkg/scripts/buildsystems/vcpkg.cmake
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
CMake Error at fips/CMakeLists.txt:26 (find_package):
  Could not find a package configuration file provided by "json5-parser" with
  any of the following names:

    json5-parserConfig.cmake
    json5-parser-config.cmake

  Add the installation prefix of "json5-parser" to CMAKE_PREFIX_PATH or set
  "json5-parser_DIR" to a directory containing one of the above files.  If
  "json5-parser" provides a separate development package or SDK, be sure it
  has been installed.


-- Configuring incomplete, errors occurred!
See also "C:/Users/jfilion/projects/crossPlatform/fips/buildx64/CMakeFiles/CMakeOutput.log".

**Comment by NancyLi1013** [comment]
It seems that it didn't detect Visual Studio, since there is no any information about this from the log.

Even if it cannot find `json5-parser`, the error log will like this:

```
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
-- The C compiler identification is MSVC 19.27.29111.0
-- The CXX compiler identification is MSVC 19.27.29111.0
-- Check for working C compiler: E:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: E:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: E:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: E:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at F:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake:455 (_find_package):
  Could not find a package configuration file provided by "json5-parser" with
  any of the following names:

    json5-parserConfig.cmake
    json5-parser-config.cmake

  Add the installation prefix of "json5-parser" to CMAKE_PREFIX_PATH or set
  "json5-parser_DIR" to a directory containing one of the above files.  If
  "json5-parser" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:2 (find_package)


-- Configuring incomplete, errors occurred!
```

In my opinion, this should be related with your local environment instead of `json5-parser`.

Could you please try to build your project after disable the following codes?
```
find_package(json5-parser CONFIG REQUIRED)
target_link_libraries(fips PRIVATE json5_parser)
```

**Comment by jlfilion** [comment]
Hi Nancy,

I'm done with my vacation now and I looked into your latest response. I think my problem has been resolved.

I noticed in the log that I sent you that cmake was looking for the compiler from the E: drive. That is very strange since my system does not have an E: drive. Just as an experiment, I opened a command prompt and typed "subst e: c:\" so that I would have an E: drive that was identical to my C: drive. I then flushed the cmake cache and reran cmake with no errors. It had no trouble finding the json5-parser library and it appeared to find the compiler on the C: drive, not the E: drive (which is kind of curious). I then removed the E: drive (with "subst e: /d") and flushed the cmake cache again and reran cmake. Everything worked fine.

So somehow my system seems to have gotten into a state where it was looking for the compiler on the wrong drive. Since I do not have an E: drive on this system, I can't explain how that could have happened but if nobody else is having similar issues, I'll assume I did something wrong at some point that got me into that state and just be happy that I'm now out of it; and thankful to you for your help and support on this issue. I think you can close this out.

Thanks again,
Joe

**Comment by NancyLi1013** [comment]
@jlfilion 
Thanks for your above details. Factually, it doesn't matter if the compiler is in C: or E: driver, which was just the path that Visual Studio installed. Since it needs CL to compile the project. I'm glad to hear from the good news that you solved this problem. 

So I'm closing this issue for now.
