### ISSUE TITLE
How do I get path to the downloaded cmake binary which is used by the vcpkg to build packages?

### ISSUE THREAD

**Issue by quickiwiki** [microsoft/vcpkg#12743]
I haven't found that out in documentation

**Comment by martin-s** [comment]
For the most ports, there is no cmake file being downloaded. The required source and tools are downloaded to the <downloads> folder.
You can make logging more verbose by using _--debug_ argument.

**Comment by quickiwiki** [comment]
I meant the cmake executable which vcpkg uses to build the packages? for example, on ubuntu the location is

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Do you mean binary directory of ports? The binary directory is _[VCPKG_path]/installed/[Triplet]/bin_.

**Comment by quickiwiki** [comment]
@LilyWangL  I meant the cmake binary. For example, on:

    windows: D:\SRC\vcpkg\downloads\tools\cmake-3.17.2-windows\cmake-3.17.2-win32-x86\bin
    ubuntu: $HOME/vcpkg/downloads/tools/cmake-3.17.2-linux/cmake-3.17.2-Linux-x86_64/bin/

I would like to know the path to the binary which is used by vcpkg to build packages

What I'm trying to do is to find out the cmake binary that is used by the vcpkg to build the ports. the difference between the cmake installed on the host and the one downloaded and used by the vcpkg leads to errors in some cases

**Comment by JackBoosY** [comment]
@quickiwiki 
All tools installed in vcpkg are under _VCPKG_ROOT/downloads/tools_. and the cmake versions used on the different system are in [vcpkgTools.xml](https://github.com/microsoft/vcpkg/blob/master/scripts/vcpkgTools.xml).

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
