### ISSUE TITLE
[boost-math] build failure

### ISSUE THREAD

**Issue by Rickmc3280** [microsoft/vcpkg#12749]
Building package boost-math[core]:x86-windows...
Could not locate cached archive: C:\Users\User\AppData\Local\vcpkg\archives\bb\bbf2019cba914b29c9fb3edff004f4c0a6270f2e.zip
-- Using cached P:/0_CPP Projects/vcpkg-master/downloads/boostorg-math-boost-1.73.0.tar.gz
-- Extracting source P:/0_CPP Projects/vcpkg-master/downloads/boostorg-math-boost-1.73.0.tar.gz
CMake Error at scripts/cmake/vcpkg_extract_source_archive_ex.cmake:147 (file):
  file RENAME failed to rename

    P:/0_CPP Projects/vcpkg-master/buildtrees/boost-math/src/ost-1.73.0-0b998d205c.tmp/math-boost-1.73.0

  to

    P:/0_CPP Projects/vcpkg-master/buildtrees/boost-math/src/ost-1.73.0-0b998d205c.clean

  because: No such file or directory

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:139 (vcpkg_extract_source_archive_ex)
  ports/boost-math/portfile.cmake:3 (vcpkg_from_github)
  scripts/ports.cmake:79 (include)

Error: Building package boost-math:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-math:x86-windows
  Vcpkg version: 2020.06.15-nohash

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/8199.
