### ISSUE TITLE
[curl] static build for Windows should not define _USRDLL

### ISSUE THREAD

**Issue by Mike4Online** [microsoft/vcpkg#12763]
**Description**
Preprocessor macro _USRDLL is defined for libCURL on Windows when using a static triplet; however, _USRDLL should only be defined for a dynamic library build.

**Environment**
- OS: Windows
- Compiler: Visual Studio 2019

**To Reproduce**
1. ./vcpkg install curl:x64-windows-static   (or curl:x86-windows-static)
2. Review %VCPKG_ROOT%\buildtrees\curl\install-x64-windows-static-dbg-out.log, and note the -D_USRDLL definition on each cl.exe command line.

**Expected behavior**
_USRDLL should not be defined when building libCURL using any of the static triplets.

**Additional context**
In the CMakeLists.txt file for libCURL, _USRDLL is defined at line 113; see the following excerpt:

```
if(CMAKE_SYSTEM_NAME STREQUAL "WindowsStore")
  add_definitions(-D_WINSOCK_DEPRECATED_NO_WARNINGS)
elseif(WIN32)
  add_definitions(-D_USRDLL)
endif()
```
The above definition of _USRDLL should occur only when BUILD_SHARED_LIBS is defined.

**Log File**

[install-x64-windows-static-dbg-out.log](https://github.com/microsoft/vcpkg/files/5029906/install-x64-windows-static-dbg-out.log)

**Comment by Mike4Online** [comment]
I see that **curl_config.h** is generated for all Debug and Release configurations for x86 and x64.  **CURL_STATICLIB** is defined within this header when specifying one of the static triplets, which is acceptable.  However, **HAVE_CONFIG_H** is not consistently defined for all static build configurations, so curl_config.h (and therefore CURL_STATICLIB) isn't always included; see related issue [https://github.com/microsoft/vcpkg/issues/12764](https://github.com/microsoft/vcpkg/issues/12764).

**Comment by NancyLi1013** [comment]
Hi @Mike4Online 

Thanks for posting this issue.

Personally, these should be updated as the follows:

```
if(CMAKE_SYSTEM_NAME STREQUAL "WindowsStore")
  add_definitions(-D_WINSOCK_DEPRECATED_NO_WARNINGS)
endif()

if(WIN32)
  if(BUILD_SHARED_LIBS)
    add_definitions(-D_USRDLL)
  else() 
    add_definitions(-D_CURL_STATICLIB)
 endif()
endif()
```
For `HAVE_CONFIG_H ` issue, I have checked the log, please see the comments here https://github.com/microsoft/vcpkg/issues/12764#issuecomment-669753902.

**Comment by Mike4Online** [comment]
Your proposed changes look good; however, it will not be necessary to define CURL_STATICLIB at this point in the CMakeLists.txt file, because CURL_STATICLIB is defined within the generated curl_config.h file, which ghets included by HAVE_CONFIG_H being defined.

My original issue post called for CURL_STATICLIB to be defined as you propose, but now I see this is not necessary.  Changing the condition for defining _USRDLL is a sufficient fix.

**Comment by NancyLi1013** [comment]
Thanks for your deep investigation and explanation to this issue. I also noticed that `CURL_STATICLIB ` is defined in  curl_config.h file.

So we just need to update it as this:

```
if(CMAKE_SYSTEM_NAME STREQUAL "WindowsStore")
  add_definitions(-D_WINSOCK_DEPRECATED_NO_WARNINGS)
endif()

if(WIN32 AND BUILD_SHARED_LIBS )
    add_definitions(-D_USRDLL)
 endif()

```
I will fix it later.
