### ISSUE TITLE
[marble] build failure on CMake 3.18

### ISSUE THREAD

**Issue by ig-or** [microsoft/vcpkg#12765]
**Host Environment**
- OS: Windows x64
- Compiler: msvc 2019

**To Reproduce**
`vcpkg remove marble`
`vcpkg install --triplet x64-windows marble`

**Failure logs** 
```
`c:\Users\space\vcpkg>vcpkg install marble
Computing installation plan...
The following packages will be built and installed:
    marble[core]:x64-windows
Detecting compiler hash for triplet x64-windows...
Starting package 1/1: marble:x64-windows
Building package marble[core]:x64-windows...
Could not locate cached archive: C:\Users\AppData\Local\vcpkg\archives\76\76aa1d763db4f9ef4946cec5f1ece5930da429c8.zip
-- Using cached C:/Users/space/vcpkg/downloads/KDE-marble-552cb9ae1f34482d1ec56532a703e0d820856286.tar.gz
-- Cleaning sources at C:/Users/space/vcpkg/buildtrees/marble/src/d820856286-99e796b78b.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/space/vcpkg/downloads/KDE-marble-552cb9ae1f34482d1ec56532a703e0d820856286.tar.gz
-- Applying patch qtfix.patch
-- Using source at C:/Users/space/vcpkg/buildtrees/marble/src/d820856286-99e796b78b.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:139 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v
    Working Directory: C:/Users/space/vcpkg/buildtrees/marble/x64-windows-dbg
    See logs for more information:
      C:\Users\space\vcpkg\buildtrees\marble\**install-x64-windows-dbg-out.log**

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/marble/portfile.cmake:17 (vcpkg_install_cmake)
  scripts/ports.cmake:79 (include)


Error: Building package marble:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: marble:x64-windows
  Vcpkg version: 2020.06.15-nohash
```
`

**in the install-x64-windows-dbg-out.log**, 
at ther very end there is a line 

`cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_dll --intdir=src\lib\marble\CMakeFiles\marblewidget.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MIB055~1\2019\PROFES~1\VC\Tools\MSVC\1426~1.288\bin\Hostx64\x64\link.exe  @src\lib\marble\CMakeFiles\marblewidget.rsp  /out:src\lib\marble\marblewidget-qt5d.dll /implib:src\lib\marble\marblewidget-qt5d.lib /pdb:src\lib\marble\marblewidget-qt5d.pdb /dll /version:0.28 /machine:x64 /nologo  /debug /INCREMENTAL  && cd ."
`

```
LINK Pass 1: command "C:\PROGRA~2\MIB055~1\2019\PROFES~1\VC\Tools\MSVC\1426~1.288\bin\Hostx64\x64\link.exe src\lib\marble\CMakeFiles\marble .< a lot of symbols - 54927 symbols here > \installed\x64-windows\debug\lib\Qt5Cored.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /out:src\lib\marble\marblewidget-qt5d.dll /implib:src\lib\marble\marblewidget-qt5d.lib /pdb:src\lib\marble\marblewidget-qt5d.pdb /dll /version:0.28 /machine:x64 /nologo /debug /INCREMENTAL /MANIFEST /MANIFESTFILE:src\lib\marble\CMakeFiles\marblewidget.dir/intermediate.manifest src\lib\marble\CMakeFiles\marblewidget.dir/manifest.res" failed (exit code 0) with the following output:
No command
ninja: build stopped: subcommand failed.
```

**Additional context**
_tried different environment variable settings, tried fresh new_ 
`git clone https://github.com/microsoft/vcpkg.git`
`bootstrap-vcpkg.bat`
`vcpkg install --triplet x64-windows marble`

Do you think this is because linker command line is too long (about 60k symbols)? If yes, we can try to put it in a file.  The strange thing is that about a week ago everything was working, and after the recent `git pull` it not working.

**Comment by ig-or** [comment]
**full log file here**
[full log file](https://gist.github.com/ig-or/12e2c279cb107385eec6952e142b04ef)

**Comment by ig-or** [comment]
maybe, related to this? [https://cmake.org/Bug/view.php?id=13461](https://cmake.org/Bug/view.php?id=13461)

**Comment by PhoebeHui** [comment]
@ig-or, I can't repro this issue, I noticed that used C:\Program Files\CMake\bin\cmake.exe in your log, what's cmake revision? could you remove it and use cmake that downloaded by vcpkg and see if this issue still repro?

I use the version 3.17.2 which downloaded by vcpkg.

Starting package 31/31: marble:x64-windows
Building package marble[core]:x64-windows...
-- Downloading https://github.com/KDE/marble/archive/552cb9ae1f34482d1ec56532a703e0d820856286.tar.gz...
-- Extracting source F:/vcpkg/src/downloads/KDE-marble-552cb9ae1f34482d1ec56532a703e0d820856286.tar.gz
-- Applying patch qtfix.patch
-- Using source at F:/vcpkg/src/buildtrees/marble/src/d820856286-99e796b78b.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: F:/vcpkg/src/packages/marble_x64-windows/share/marble/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package marble[core]:x64-windows... done
Installing package marble[core]:x64-windows...
Installing package marble[core]:x64-windows... done
Elapsed time for package marble:x64-windows: 12.37 min

Total elapsed time: 2.419 h

The package marble:x64-windows provides CMake targets:

    find_package(Astro CONFIG REQUIRED)
    target_link_libraries(main PRIVATE Astro)

    find_package(Marble CONFIG REQUIRED)
    target_link_libraries(main PRIVATE Marble)

**Comment by ig-or** [comment]
**EXACTLY!!!!** 
with latest CMAKE 3.18.1 not working
cmake --version
cmake version 3.18.1

**With v3.17.2 everything is working.** 

What can we do in this case? close this issue?

**Comment by ig-or** [comment]
@JackBoosY, @strega-nil , this port is working with "current" cmake 3.17.2, but not working with "latest" 3.18.1 
probably some other ports may be broken if/when cmake will be upgraded.

**Comment by strega-nil** [comment]
That's unfortunate. We're probably going to hold off on updating CMake until @BillyONeal is back on our team from being on loan to the STL team, and we'll make sure to look at these issues then.

**Comment by ig-or** [comment]
OK, we can close this issue as it is, or we can remove "PREFER_NINJA" from [marble] portfile.cmake. 
Without "PREFER_NINJA",  it works even with latest cmake 3.18.1.
What is better solution?

**Comment by strega-nil** [comment]
If you'd like, I would accept a change to remove `PREFER_NINJA` for now, or if you can figure out the actual underlying issue, that'd be great. Please keep the issue open for now tho.

**Comment by cristianadam** [comment]
The problem has been fixed in 3.18.2 see https://gitlab.kitware.com/cmake/cmake/-/merge_requests/5094

**Comment by strega-nil** [comment]
Oh, oof, fun.

**Comment by ig-or** [comment]
Will do this after they will officially release it. Lets wait a little bit.   Current release is 3.18.1

**Comment by JackBoosY** [comment]
I can't repro this issue after I installed cmake 3.18.1 on my machine.

**Comment by PhoebeHui** [comment]
@ig-or, we have upgraded CMake to 3.18.4, and marble built successfully now, please get latest source and try again.

**Comment by ig-or** [comment]
Great, thanks!  All is looks like working on my side also.
