### ISSUE TITLE
[fmt] update to 7.0.1

### ISSUE THREAD

**Issue by jdlugosz** [microsoft/vcpkg#12767]
Library name: fmt

New version number: 7.0.1

Other information that may be useful (release notes, etc...)
https://fmt.dev/7.0.1/usage.html#vcpkg states:
"The fmt port in vcpkg is kept up to date by Microsoft team members and community contributors. If the version is out of date, please create an issue or pull request on the vcpkg repository."

**Comment by kevinlul** [comment]
Latest version is [7.0.2](https://github.com/fmtlib/fmt/releases/tag/7.0.2), pull request #12312

**Comment by JonLiu1993** [comment]
Hi @jdlugosz, This issues has been resolved in [#12312 ](https://github.com/microsoft/vcpkg/pull/12312)
Please update vcpkg library and use
