### ISSUE TITLE
[zlib] Could not find PKGCONFIG using the following names: pkg-config

### ISSUE THREAD

**Issue by MauriceHubain** [microsoft/vcpkg#12775]
**Host Environment**
- OS: Azure DevOps Hosted Agent vs2017-win2016 / windows-2019

**To Reproduce**
vcpkg install glew:x86-windows sdl2:x86-windows sdl2-image[libjpeg-turbo]:x86-windows sqlite3:x86-windows zlib:x86-windows

**Failure logs** 
Starting package 3/7: zlib:x86-windows
Building package zlib[core]:x86-windows...
Could not locate cached archive: C:\Users\VssAdministrator\AppData\Local\vcpkg\archives\e3\e389a2204830c36ab408512d61d8a03c8467fdf5.zip
-- Downloading http://www.zlib.net/zlib-1.2.11.tar.gz...
-- Extracting source C:/vcpkg/downloads/zlib1211.tar.gz
-- Applying patch cmake_dont_build_more_than_needed.patch
-- Using source at C:/vcpkg/buildtrees/zlib/src/1.2.11-deec42f53b.clean
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Fixing pkgconfig
CMake Error at scripts/cmake/vcpkg_fixup_pkgconfig.cmake:279 (find_program):
  Could not find PKGCONFIG using the following names: pkg-config
Call Stack (most recent call first):
  ports/zlib/portfile.cmake:46 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:79 (include)

Error: Building package zlib:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zlib:x86-windows
  Vcpkg version: 2020.06.15-nohash

**Comment by PhoebeHui** [comment]
@MauriceHubain, this issue has been fixed now, could you get lastest source and try again?

**Comment by MauriceHubain** [comment]
Works fine again. Thanks!
