### ISSUE TITLE
[New Port Request] clangd

### ISSUE THREAD

**Issue by faserg1** [microsoft/vcpkg#12797]
Library name:
clangd
Library description:
language server
Source repository URL:
https://github.com/llvm/llvm-project/tree/master/clang-tools-extra/clangd
Project homepage (if different from the source repository):
https://clangd.llvm.org/

**Comment by Neumann-A** [comment]
isn't that part of the LLVM build wit feature `clang-tools-extra`?

**Comment by PhoebeHui** [comment]
@faserg1, does the feature meet your demands?

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
