### ISSUE TITLE
[alembic:x64-osx] build failure

### ISSUE THREAD

**Issue by DMotorygin** [microsoft/vcpkg#12798]
**Host Environment**
- OS: [osx]
- Compiler: AppleClang 11.0.3.11030032

**To Reproduce**
`./vcpkg install alembic`

**Failure logs** 
Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/alembic/portfile.cmake:36 (vcpkg_install_cmake)
  scripts/ports.cmake:79 (include)

Error: Building package alembic:x64-osx failed with: BUILD_FAILED

-- Note: alembic only supports dynamic library linkage. Building dynamic library.
-- Downloading https://github.com/alembic/alembic/archive/cfe114639ef7ad084d61e71ab86a17e708d838ae.tar.gz...
-- Extracting source /Users/DMotor/Documents/dev/vcpkg/vcpkg/downloads/alembic-alembic-cfe114639ef7ad084d61e71ab86a17e708d838ae.tar.gz
-- Applying patch fix-find-openexr-ilmbase.patch
-- Using source at /Users/DMotor/Documents/dev/vcpkg/vcpkg/buildtrees/alembic/src/e708d838ae-dc6119ffed.clean
-- Configuring x64-osx-dbg
-- Configuring x64-osx-rel
-- Building x64-osx-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:139 (message):
    Command failed: /Users/DMotor/Documents/dev/vcpkg/vcpkg/downloads/tools/cmake-3.17.2-osx/cmake-3.17.2-Darwin-x86_64/CMake.app/Contents/bin/cmake --build . --config Debug --target install -- -v

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/12830, which has build logs.
