### ISSUE TITLE
Building freetype:arm-uwp fails [fixed by cmake 3.9+]

### ISSUE THREAD

**Issue by pdehne** [Microsoft/vcpkg#1280]
I'm trying to build freetype:arm-uwp v2.8 on Windows 10, de-de locale, using VS 2017. The build fails just before linking with the following error in package-arm-uwp-rel-out.log:

`unrecognized file format in 'C:/Users/patrick.SPRINGFIELD/Documents/development/vcpkg/buildtrees/freetype/arm-uwp-rel/freetype.dir/Release/autofit.obj'
`

x86-uwp and x64-uwp are building without problems. package-arm-uwp-rel-err.log is empty.

Here is the complete build log:
[package-arm-uwp-rel-out.log.txt](https://github.com/Microsoft/vcpkg/files/1074593/package-arm-uwp-rel-out.log.txt)

**Comment by zabulus** [comment]
You should use CMake with version >3.8.2. Easiest way to workaround it is download it from cmake.org and make in-place replace in folder ```<vcpkg_root>\downloads\cmake...```

**Comment by pdehne** [comment]
Many thanks! In-place replace of cmake 3.8.0 with 3.9.0-rc3 fixed building freetype for arm-uwp.

**Comment by ras0219-msft** [comment]
We'll definitely update to 3.9.0 as soon as the main release comes out. Thanks for providing the current workaround, @zabulus!

**Comment by JackBoosY** [comment]
Hi @pdehne , thanks for reporting this issue!
Please open a new issue if this is still a problem for you.
Thx.
