### ISSUE TITLE
Running XROTOR on Windows - NMAKE error U1077

### ISSUE THREAD

**Issue by joshuaxdmb** [microsoft/vcpkg#12803]
Hi, I am trying to setup Xrotor in Windows 10, but I keep getting the following error:

NMAKE : fatal error U1077: 'ifl' : return code '0x1' Stop.

I already tried installing all the required VS 2019 packages. I am running the makefile from the Developer Powershell for VS 2019.
Thanks for any help.

**Comment by StarGate-One** [comment]
I do not see port a xrotor in vcpkg?
Please post the vcpkg command(s) and details involved.

**Comment by joshuaxdmb** [comment]
@StarGate-One perhaps this is the wrong place to post this, I wasn't sure. All Xrotor files and some information can be downloaded from here: http://web.mit.edu/drela/Public/web/xrotor/

**Comment by StarGate-One** [comment]
This github is for vcpkg, a c/c++ source code package manager and the sources that have been ported to be managed and installed with it. 
If you are using msvc I suggesr seeking advice in one of the visual studio c/c++ developer forums.

**Comment by PhoebeHui** [comment]
@joshuaxdmb, please report an issue with repro steps to xrotor or https://developercommunity.visualstudio.com/ instead.
