### ISSUE TITLE
[opencv4:x64-windows] build failure

### ISSUE THREAD

**Issue by JustifiedAnciantOfMUMU** [microsoft/vcpkg#12808]
**Host Environment**
- OS: Windows 10
- Compiler: revision

computing installation plan...
The following packages will be built and installed:
    darknet[core,cuda,cudnn,full,opencv-cuda,weights,weights-train]:x64-windows
  * opencv[core,cuda,dnn,ffmpeg,jpeg,opengl,png,tiff,webp]:x64-windows
  * opencv4[contrib,core,cuda,dnn,ffmpeg,jpeg,opengl,png,tiff,webp]:x64-windows
  * pthreads[core]:x64-windows
  * stb[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Starting package 1/5: opencv4:x64-windows
Building package opencv4[contrib,core,cuda,dnn,ffmpeg,jpeg,opengl,png,tiff,webp]:x64-windows...
Could not locate cached archive: C:\Users\Jon\AppData\Local\vcpkg\archives\fb\fb50a9b437182bb4cac6dc94d894a419eaaec956.zip
-- Using cached C:/Users/Jon/Documents/GitHub/vcpkg/downloads/opencv-opencv-4.3.0.tar.gz
-- Cleaning sources at C:/Users/Jon/Documents/GitHub/vcpkg/buildtrees/opencv4/src/4.3.0-0c6047baf6.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/Jon/Documents/GitHub/vcpkg/downloads/opencv-opencv-4.3.0.tar.gz
-- Applying patch 0001-disable-downloading.patch
-- Applying patch 0002-install-options.patch
-- Applying patch 0003-force-package-requirements.patch
-- Applying patch 0004-fix-policy-CMP0057.patch
-- Applying patch 0009-fix-uwp.patch
-- Using source at C:/Users/Jon/Documents/GitHub/vcpkg/buildtrees/opencv4/src/4.3.0-0c6047baf6.clean
-- Using cached C:/Users/Jon/Documents/GitHub/vcpkg/downloads/opencv-cache/tiny_dnn/adb1c512e09ca2c7a6faef36f9c53e59-v1.0.0a3.tar.gz
-- Using cached C:/Users/Jon/Documents/GitHub/vcpkg/downloads/opencv-cache/nvidia_optical_flow/ca5acedee6cb45d0ec610a6732de5c15-79c6cee80a2df9a196f20afd6b598a9810964c32.zip
-- Using cached C:/Users/Jon/Documents/GitHub/vcpkg/downloads/opencv-opencv_contrib-4.3.0.tar.gz
-- Cleaning sources at C:/Users/Jon/Documents/GitHub/vcpkg/buildtrees/opencv4/src/4.3.0-795a2a992f.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/Jon/Documents/GitHub/vcpkg/downloads/opencv-opencv_contrib-4.3.0.tar.gz
-- Applying patch 0005-add-missing-stdexcept-include.patch
-- Using source at C:/Users/Jon/Documents/GitHub/vcpkg/buildtrees/opencv4/src/4.3.0-795a2a992f.clean
-- Using cached C:/Users/Jon/Documents/GitHub/vcpkg/downloads/opencv-cache/xfeatures2d/boostdesc/0ea90e7a8f3f7876d450e4149c97c74f-boostdesc_bgm.i
-- Using cached C:/Users/Jon/Documents/GitHub/vcpkg/downloads/opencv-cache/xfeatures2d/boostdesc/232c966b13651bd0e46a1497b0852191-boostdesc_bgm_bi.i
-- Using cached C:/Users/Jon/Documents/GitHub/vcpkg/downloads/opencv-cache/xfeatures2d/boostdesc/324426a24fa56ad9c5b8e3e0b3e5303e-boostdesc_bgm_hd.i
-- Using cached C:/Users/Jon/Documents/GitHub/vcpkg/downloads/opencv-cache/xfeatures2d/boostdesc/202e1b3e9fec871b04da31f7f016679f-boostdesc_binboost_064.i
-- Using cached C:/Users/Jon/Documents/GitHub/vcpkg/downloads/opencv-cache/xfeatures2d/boostdesc/98ea99d399965c03d555cef3ea502a0b-boostdesc_binboost_128.i
-- Using cached C:/Users/Jon/Documents/GitHub/vcpkg/downloads/opencv-cache/xfeatures2d/boostdesc/e6dcfa9f647779eb1ce446a8d759b6ea-boostdesc_binboost_256.i
-- Using cached C:/Users/Jon/Documents/GitHub/vcpkg/downloads/opencv-cache/xfeatures2d/boostdesc/0ae0675534aa318d9668f2a179c2a052-boostdesc_lbgm.i
-- Using cached C:/Users/Jon/Documents/GitHub/vcpkg/downloads/opencv-cache/xfeatures2d/vgg/e8d0dcd54d1bcfdc29203d011a797179-vgg_generated_48.i
-- Using cached C:/Users/Jon/Documents/GitHub/vcpkg/downloads/opencv-cache/xfeatures2d/vgg/7126a5d9a8884ebca5aea5d63d677225-vgg_generated_64.i
-- Using cached C:/Users/Jon/Documents/GitHub/vcpkg/downloads/opencv-cache/xfeatures2d/vgg/7cd47228edec52b6d82f46511af325c5-vgg_generated_80.i
-- Using cached C:/Users/Jon/Documents/GitHub/vcpkg/downloads/opencv-cache/xfeatures2d/vgg/151805e03568c9f490a5e3a872777b75-vgg_generated_120.i
-- Using cached C:/Users/Jon/Documents/GitHub/vcpkg/downloads/opencv-cache/data/7505c44ca4eb54b4ab1e4777cb96ac05-face_landmark_model.dat
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:139 (message):
    Command failed: C:/Users/Jon/Documents/GitHub/vcpkg/downloads/tools/cmake-3.17.2-windows/cmake-3.17.2-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v
    Working Directory: C:/Users/Jon/Documents/GitHub/vcpkg/buildtrees/opencv4/x64-windows-dbg
    See logs for more information:
      C:\Users\Jon\Documents\GitHub\vcpkg\buildtrees\opencv4\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/opencv4/portfile.cmake:371 (vcpkg_install_cmake)
  scripts/ports.cmake:79 (include)

Error: Building package opencv4:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: opencv4:x64-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by JackBoosY** [comment]
Please provide failure log _C:\Users\Jon\Documents\GitHub\vcpkg\buildtrees\opencv4\install-x64-windows-dbg-out.log_.

Thanks.

**Comment by JackBoosY** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
