### ISSUE TITLE
[libffi:x64-windows] build failure

### ISSUE THREAD

**Issue by homedry** [microsoft/vcpkg#12815]
**Host Environment**
- OS: Windows 10
- Compiler: revision

**To Reproduce**
Run 'vcpkg install libffi:x64-windows'

**Failure logs** 
Computing installation plan...
The following packages will be built and installed:
    libffi[core]:x64-windows
Detecting compiler hash for triplet x64-windows...
Starting package 1/1: libffi:x64-windows
Building package libffi[core]:x64-windows...
Could not locate cached archive: C:\Users\homedry\AppData\Local\vcpkg\archives\f1\f198d59d4c6889d9c1f38d8202911295ee0e140f.zip
-- Using cached C:/vcpkg/downloads/libffi-libffi-v3.3.tar.gz
-- Cleaning sources at C:/vcpkg/buildtrees/libffi/src/v3.3-8557367958.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg/downloads/libffi-libffi-v3.3.tar.gz
-- Applying patch win64-disable-stackframe-check.patch
-- Applying patch win32-disable-stackframe-check.patch
-- Using source at C:/vcpkg/buildtrees/libffi/src/v3.3-8557367958.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Fixing pkgconfig
-- Acquiring MSYS Packages...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: C:/vcpkg/downloads/tools/msys2/msys64/usr/bin/bash.exe --noprofile --norc -c "pacman -S --noconfirm --needed pkg-config"
    Working Directory: C:/vcpkg/downloads/tools/msys2
    Error code: 1
    See logs for more information:
      C:\vcpkg\buildtrees\libffi\msys-pacman-x64-windows-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_acquire_msys.cmake:153 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:281 (vcpkg_acquire_msys)
  ports/libffi/portfile.cmake:50 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:79 (include)

Error: Building package libffi:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libffi:x64-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.
**Additional context**
I got to know this issue when I tried to install wt first.

**Comment by StarGate-One** [comment]
Looks like `pkg-config.exe` is missing in your msys2 installation.
Try deleting or renaming the **`[vcpkg-root]\downloads\tools\msys2`** directory/folder and try again

**Comment by PhoebeHui** [comment]
@homedry, could you try the step that StarGate-One provided?

**Comment by PhoebeHui** [comment]
This issue has been fixed, if you try above steps, it should pass.
