### ISSUE TITLE
[vtk-dicom] find_package() can not find vtk-dicom

### ISSUE THREAD

**Issue by QiuKejian** [microsoft/vcpkg#12813]
When asking a question please also include where you looked for an answer (so we can update the documentation if needed).

I have keep running into the following error:
  [cmake]   Could not find a package configuration file provided by "vtkDICOM" with any
  [cmake]   of the following names:
  [cmake] 
  [cmake]     vtkDICOMConfig.cmake
  [cmake]     vtkdicom-config.cmake

![image](https://user-images.githubusercontent.com/12969818/89707583-18aad680-d9a2-11ea-8301-026090a15eb3.png)

Sorry, but is this a bug or something?

**Comment by JackBoosY** [comment]
Confirmed.

**Comment by dg0yt** [comment]
Current installation state:
~~~
vtk-dicom:x64-windows:/share/dicom-0.8/Copyright.txt
vtk-dicom:x64-windows:/share/vtk-dicom/copyright
vtk-dicom:x64-windows:/share/vtk-dicom/vcpkg.spdx.json
vtk-dicom:x64-windows:/share/vtk-dicom/vcpkg_abi_info.txt
vtk-dicom:x64-windows:/share/vtk-dicom/vtk/DICOM-targets-debug.cmake
vtk-dicom:x64-windows:/share/vtk-dicom/vtk/DICOM-targets-release.cmake
vtk-dicom:x64-windows:/share/vtk-dicom/vtk/DICOM-targets.cmake
vtk-dicom:x64-windows:/share/vtk-dicom/vtk/DICOM-vtk-module-properties.cmake
~~~

Issues:
- No config file indeed.
- Not installed in right directory.
- (I assume that) vcpkg tool prints invalid usage information, #20190.

**Comment by MikeKen-Ken** [comment]
I asked the package author, using the [method](https://github.com/dgobbi/vtk-dicom/issues/218#issuecomment-1373888890) he provided, and it still failed.

**Comment by Harold2017** [comment]
Same bug here for `vcpkg package management program version 2023-04-07-bedcba5172f5e4b91caac660ab7afe92c27a9895`.
To solve this problem, I have to manually copy `*.cmake` files from `vcpkg\installed\x64-windows\share\vtk-dicom\dicom-0.8` to `vcpkg\installed\x64-windows\share\vtk-dicom` ...
