### ISSUE TITLE
Error: Building package llvm:x64-osx failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by MonySOEURN** [microsoft/vcpkg#12812]
**Host Environment**
- OS: OSX 10.15.6
- Compiler: revision

**To Reproduce**
`./vcpkg install llvm`

**Failure logs** 
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:176 (message):
      
      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:132 (vcpkg_download_distfile)
  ports/llvm/portfile.cmake:5 (vcpkg_from_github)
  scripts/ports.cmake:79 (include)

Error: Building package llvm:x64-osx failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: llvm:x64-osx
  Vcpkg version: 2020.06.15-unknownhash

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by NancyLi1013** [comment]
Hi @MonySOEURN 
Thanks for posting this issue.

Could you please help confirm if you have access to https://github.com/llvm/llvm-project/archive/llvmorg-10.0.0.tar.gz? 

If yes, please download https://github.com/llvm/llvm-project/archive/llvmorg-10.0.0.tar.gz manually and place this archive to
_VCPKG_ROOT/downloads/_. Then try to rebuild this port.

**Comment by MonySOEURN** [comment]
Noted with Thanks,
I have successfully download it after I tried 3 times.
