### ISSUE TITLE
capnproto build fails with INTERNAL COMPILER ERROR

### ISSUE THREAD

**Issue by Todd-Fulton** [microsoft/vcpkg#12819]
Package: capnproto:x64-windows
  Vcpkg version: 2020.06.15-nohash

```
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:139 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v
    Working Directory: C:/Users/ToddF/Documents/Code/pixie/vcpkg/buildtrees/capnproto/x64-windows-dbg
    See logs for more information:
      C:\Users\ToddF\Documents\Code\pixie\vcpkg\buildtrees\capnproto\install-x64-windows-dbg-out.log
```

I believe this is the relevant section from the log file.

```
C:\Users\ToddF\Documents\Code\pixie\vcpkg\buildtrees\capnproto\src\v0.7.0-b4a52715c4.clean\c++\src\kj\compat\http.c++(2419): fatal error C1001: Internal compiler error.
(compiler file 'msc1.cpp', line 1591)
 To work around this problem, try simplifying or changing the program near the locations listed above.
If possible please provide a repro here: https://developercommunity.visualstudio.com 
Please choose the Technical Support command on the Visual C++ 
 Help menu, or open the Technical Support help file for more information
INTERNAL COMPILER ERROR in 'C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\14.27.29110\bin\Hostx64\x64\cl.exe'
    Please choose the Technical Support command on the Visual C++
    Help menu, or open the Technical Support help file for more information
```

Before trying vcpkg I tried to compile version 0.8.0 as per the instructions on the site but I got the same problem with the same file (`compat/http.c++`), and probably the same line iirc in vs2019 community.

**Comment by StarGate-One** [comment]
From experience in the past, you will need to open a support ticket with microsoft developer visual studio, per the instructions listed.

**Comment by NancyLi1013** [comment]
Hi @StarGate-One 

Thanks for posting this issue.

This is a compiler bug on Visual Studio 2019. We have opened a bug to track this.

**Comment by Todd-Fulton** [comment]
Thanks, since it's a bug with the compiler I'll close this here, unless someone wants it opened for tracking or whatnot.

**Comment by NancyLi1013** [comment]
Please keep this issue open until the compiler bug is solved.

**Comment by sfhacker** [comment]
@Todd-Fulton Any update on this open issue?
We have had no issues so far!

![image](https://user-images.githubusercontent.com/25817529/92332676-f1d7e100-f0c2-11ea-83be-349660bba733.png)

**Comment by Todd-Fulton** [comment]
I've been away for awhile, sorry for not responding.
Today I updated Visual Studio, recloned and rebuilt vcpkg, and I get the same error.
I'm going to reinstall everything from scratch and try again.

@sfhacker 
One thing I noticed is that the current of capnproto in vcpk is 0.7.0 instead of 0.8.0, not sure if that matters for this particular issue. Also, I am using the msvc toolset, as far as I understand the problem is a bug in the compiler not handling some construct in  
`\c++\src\kj\compat\http-test.c++` on line `1806`. I suppose I could set up msys and use mingw in the mean time if I can get that toolchain working with vcpkg.

The logged error from todays attempt to compile:
```
C:\Users\ToddF\Documents\Code\pixie\vcpkg\buildtrees\capnproto\src\v0.7.0-b4a52715c4.clean\c++\src\kj\compat\http-test.c++(1806): fatal error C1001: Internal compiler error.
(compiler file 'msc1.cpp', line 1591)
 To work around this problem, try simplifying or changing the program near the locations listed above.
If possible please provide a repro here: https://developercommunity.visualstudio.com 
Please choose the Technical Support command on the Visual C++ 
 Help menu, or open the Technical Support help file for more information
INTERNAL COMPILER ERROR in 'C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\14.27.29110\bin\Hostx64\x64\cl.exe'
    Please choose the Technical Support command on the Visual C++
    Help menu, or open the Technical Support help file for more information
```

Steps I did today:
1) Updated Visual Studio Community 2019
2) Deleted vcpkg repo
3) cloned and built vcpkg
4) `./vcpkg install capnproto:x64-windows`

Not sure if it's relevant, but I am using a Windows Insider build, beta iirc, for wsl2. The version number listed in settings is `2004` and the os build number is `19041.508`.

I hope that helps. I'll try again after I finish reinstalling everything, I'll try visual studio 2019 preview next, maybe that'll have some fixes not in stable.

**Comment by Todd-Fulton** [comment]
It works!
- I uninstalled VS Community 2019
- Updated windows
- Installed VS Community 2019 Preview 3
- reboot
- rebuilt vcpkg
- `./vcpkg install capnproto:x64-windows`

```
~\Documents\Code\pixie\vcpkg\installed\x64-windows\tools\capnproto master
❯ .\capnp.exe help
Usage: C:\Users\ToddF\Documents\Code\pixie\vcpkg\installed\x64-windows\tools\capnproto\capnp.exe [<option>...] <command> [<arg>...]

Command-line tool for Cap'n Proto development and debugging.

Commands:
  compile  Generate source code from schema files.
  convert  Convert messages between binary, text, JSON, etc.
  ...
  ...
```

Idk if my previous installation was broken or if the issue was fixed in the compiler in preview, but, it works now.
Thank you!

**Comment by KubaO** [comment]
This is not fixed with the release compiler. It is indeed fixed in the compiler preview, but I'd consider it a bug since not everyone can build products using a preview compiler. It's worse: many people are stuck at earlier versions of MSVC 2019 (if they are lucky to even be on 2019), so this is a real problem.

**Comment by sfhacker** [comment]
@KubaO This issue is a couple of months old.
We have had no issues building this port from source on Windows.
Perhaps you could try/find an MSVC alternative?

**Comment by KubaO** [comment]
> This issue is a couple of months old.

Huh? So? It's still a problem, with shipping MSVC, today, and apparently all this underscores is that it has now been a problem for months without a workaround.

> Perhaps you could try/find an MSVC alternative?

You suggest to look for an alternative to a compiler that is one of the two major commercial Intel-targeting compilers (as in: those you can buy as a product, expect support for, etc.). I do understand that MSVC bugs aren't exactly your responsibility, and that CloudFlare may not use it, but if that's the attitude then this product should have remained closed-source - it's not as if CloudFlare needs any external userbase to further test this thing... For what it's worth, gcc's link performance on Windows is beyond abysmal and non-trivial projects are a royal pain to build with gcc on Windows because compared to MSVC it's like watching grass grow. Maybe you're missing out on fast builds by discounting MSVC :)

> We have had no issues building this port from source on Windows.

On other compilers, sure. But that's not what this issue is about, and using the preview compiler is not a viable solution to most who want to use this in production.

**Comment by NancyLi1013** [comment]
Hi @Todd-Fulton 

It seems that this issue has been fixed.

Could you please update VS2019 to the latest version and also update vcpkg to the latest version to rebuild this port?

I can build `capnproto` successfully with Visual Studio Enterprise 2019 16.8.3.

**Comment by NancyLi1013** [comment]
Closing this issue for now since it has been fixed now.
