### ISSUE TITLE
[qt5] uic.exe complains about missing symbols

### ISSUE THREAD

**Issue by infohoschie** [Microsoft/vcpkg#1281]
I run VCPKG under Windows 10 Creators Update.
As Build environment I use the Visual Studio Build Tools 2017 and CMake 3.8.2

I've installed QT5 via VCPKG in version 5.8.

In my build environment I use uic.exe to "compile" .ui files to C++ classes.
When starting the cmake build process uic fails with error code 0xc0000139 -
Calling uic.exe directly complains about missing symbols.

The PATH variable is manually set to <vcpkg_root>\installed\x64-windows\bin

When i copy the contents of <vcpkg_root>\installed\x64-windows\bin to the <vcpkg_root>\installed\x64-windows\tools\qt5 directory, uic.exe and other QT-executables can be run without any error.
IMHO some QT parts does not respect the PATH environment variable.

Does anyone has same issues?

**Comment by Voskrese** [comment]
set QT_DIR=E:\tools\vcpkg\packages\qt5_x86-windows
set QT5_DIR=E:\tools\vcpkg\packages\qt5_x86-windows
set QTDIR=E:\tools\vcpkg\packages\qt5_x86-windows
SET PATH=%QTDIR%\bin;%PATH%

set QMAKESPEC=win32-msvc2015
?

**Comment by infohoschie** [comment]
Hi Voskrese,

thank you for your hint. I've found the failure in my environment.
In my path the CMake bin-directory is placed before the vcpkg binary path. (I'm adding additional paths at the end by default)
Within the CMake installation are also QT-libraries placed, which are incompatible.
When removing CMake from path or adding the VCPKG path in front of the cmake path, the build completes.

Thanks a lot!
