### ISSUE TITLE
[boost-compatibility] boost_LICENSE_1_0.txt download

### ISSUE THREAD

**Issue by DGQXP** [microsoft/vcpkg#12825]
When asking a question please also include where you looked for an answer (so we can update the documentation if needed).
-- Using cached C:/dev/vcpkg/vcpkg-master/downloads/boostorg-compatibility-boost-1.73.0.tar.gz
-- Cleaning sources at C:/dev/vcpkg/vcpkg-master/buildtrees/boost-compatibility/src/ost-1.73.0-44642da97c.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/dev/vcpkg/vcpkg-master/downloads/boostorg-compatibility-boost-1.73.0.tar.gz
-- Using source at C:/dev/vcpkg/vcpkg-master/buildtrees/boost-compatibility/src/ost-1.73.0-44642da97c.clean
-- Packaging headers
-- Packaging headers done
-- Using cached C:/dev/vcpkg/vcpkg-master/downloads/boost_LICENSE_1_0.txt
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:99 (message):
  

  File does not have expected hash:

          File path: [ C:/dev/vcpkg/vcpkg-master/downloads/boost_LICENSE_1_0.txt ]
      Expected hash: [ d6078467835dba8932314c1c1e945569a64b065474d7aced27c9a7acc391d52e9f234138ed9f1aa9cd576f25f12f557e0b733c14891d42c16ecdc4a7bd4d60b8 ]
        Actual hash: [ b3e1ca08971b1c3e8cb11a854d094cea3a5fd2c95cf9e985b5212a4bde7975cc3ae15455e8d9e7dc3f2a47b1285b0a34798fc6e194d4ec2db4ceb76547bf07bb ]

  Please delete the file and retry if this file should be downloaded again.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:110 (test_hash)
  installed/x86-windows/share/boost-vcpkg-helpers/boost-modular-headers.cmake:17 (vcpkg_download_distfile)
  ports/boost-compatibility/portfile.cmake:12 (boost_modular_headers)
  scripts/ports.cmake:79 (include)

please help me to solve it

**Comment by DGQXP** [comment]
solved this problem

**Comment by Voskrese** [comment]
C:\Users\Nikolay\Desktop> `wget https://raw.githubusercontent.com/boostorg/boost/boost-1.73.0/LICENSE_1_0.txt`

C:\Users\Nikolay\Desktop> `vcpkg hash LICENSE_1_0.txt`

`d6078467835dba8932314c1c1e945569a64b065474d7aced27c9a7acc391d52e9f234138ed9f1aa9cd576f25f12f557e0b733c14891d42c16ecdc4a7bd4d60b8`

**Comment by andyzimmerer** [comment]
thank you

**Comment by andyzimmerer** [comment]
delete C:/dev/vcpkg/vcpkg-master/downloads/boost_LICENSE_1_0.txt and try again

**Comment by PhoebeHui** [comment]
Double checked, the hash value is correct.

**Comment by DGQXP** [comment]
thanks for your reply. It's my mistake, i already solved it. thanks again.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/vcpkg"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月10日(星期一) 下午4:45
收件人:&nbsp;"microsoft/vcpkg"<vcpkg@noreply.github.com&gt;;
抄送:&nbsp;"1968493389"<1968493389@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [microsoft/vcpkg] [boost-compatibility] boost_LICENSE_1_0.txt download (#12825)





 
Double checked, the hash value is correct.
