### ISSUE TITLE
error with msys

### ISSUE THREAD

**Issue by iiAndre** [microsoft/vcpkg#12820]
**Describe the bug**
when i try to install for example cpr i get this error :/
**Environment**
- OS: windows 10

**Failure logs** 
error: mingw32: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" is unknown
error: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" could not be looked up remotely
error: msys: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" is unknown
error: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" could not be looked up remotely
error: database 'mingw32' is not valid (invalid or corrupted database (PGP signature))
error: database 'msys' is not valid (invalid or corrupted database (PGP signature))

**Comment by Voskrese** [comment]
describe all your actions, from the beginning of use vcpkg to the error

**all in detail !**

**Comment by Neumann-A** [comment]
I think this is still an issue from the keyring update, so removing the cached msys version should solve it

**Comment by PhoebeHui** [comment]
@iiAndre, could you remove ./downloads/tools/msys folder and try to build the port again?

**Comment by PhoebeHui** [comment]
This issue has been fixed, if you try above steps, it should pass.

**Comment by iiAndre** [comment]
i will try thanks

**Comment by iiAndre** [comment]
downloading mingw64.db...
downloading mingw64.db.sig...
error: mingw64: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" is unknown
error: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" could not be looked up remotely
error: failed to update mingw64 (invalid or corrupted database (PGP signature))
downloading msys.db...
downloading msys.db.sig...
error: msys: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" is unknown
error: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" could not be looked up remotely
error: failed to update msys (invalid or corrupted database (PGP signature))
error: failed to synchronize all databases
-- Acquiring MSYS2... OK
-- Acquiring MSYS Packages...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: C:/src/vcpkg/downloads/tools/msys2/msys64/usr/bin/bash.exe --noprofile --norc -c "pacman -S --noconfirm --needed pkg-config"
    Working Directory: C:/src/vcpkg/downloads/tools/msys2
    Error code: 1
    See logs for more information:
      C:\src\vcpkg\buildtrees\zlib\msys-pacman-x86-windows-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_acquire_msys.cmake:127 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:281 (vcpkg_acquire_msys)
  ports/zlib/portfile.cmake:46 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:79 (include)

**Comment by iiAndre** [comment]
still got this
