### ISSUE TITLE
[New Port Request] pdfium

### ISSUE THREAD

**Issue by vmiheer** [microsoft/vcpkg#12824]
Library name: pdfium

Library description: Chromium pdf library

Source repository URL: https://pdfium.googlesource.com/pdfium/

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by ajmuela** [comment]
Hi @PhoebeHui, could this port be added?

**Comment by PhoebeHui** [comment]
@ajmuela, we're happy to answer any questions we can to support this effort, but for now we'd prefer to support you or other contributors than to take ownership ourselves. None of our core team is very familiar with pdfium, so we feel you'll do a much better job than we could! we can help reopen this issue if you or other contributors have a PR for it. Sorry for that.

**Comment by ajmuela** [comment]
@PhoebeHui thanks for the prompt reply! Message understood.

Unfortunately, I don't have any PR ready for it, nor am I too familiar with the requirements to create a new port. Would you be so kind to point me to a particular entry-point in the doc and/or any good existing example I could use as a reference to create one?

**Comment by PhoebeHui** [comment]
@ajmuela, you can reference the following docs, let me know if you have any questions about it.

[packaging-github-repos.md](https://github.com/microsoft/vcpkg/blob/master/docs/examples/packaging-github-repos.md) or https://vcpkg.io/en/docs/examples/packaging-github-repos.html
[packaging-zipfiles.md](https://github.com/microsoft/vcpkg/blob/master/docs/examples/packaging-zipfiles.md) or https://vcpkg.io/en/docs/examples/packaging-zipfiles.html

**Comment by donno** [comment]
This issue duplicates #11917 which in turn was also predated by #843.

This comment is mostly to link together the three issues should someone stumble across one of them like I did.
