### ISSUE TITLE
[ffmpeg] build failure

### ISSUE THREAD

**Issue by AlainMindana** [microsoft/vcpkg#12826]
**Host Environment:**
- OS: Windows 10
- Compiler: revision

**To Reproduce:**
cd vcpkg
.\bootstrap-vcpkg.bat
.\vcpkg integrate install
.\vcpkg install ffmpeg:x64-windows

**Failure logs** 

CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: C:/Users/Vins/Desktop/vcpkg/downloads/tools/msys2/msys64/usr/bin/bash.exe --noprofile --norc C:/Users/Vins/Desktop/vcpkg/ports/ffmpeg\build.sh C:/Users/Vins/Desktop/vcpkg/buildtrees/ffmpeg/x64-windows-dbg C:/Users/Vins/Desktop/vcpkg/buildtrees/ffmpeg/src/n4.2-a4d149a5c6.clean C:/Users/Vins/Desktop/vcpkg/packages/ffmpeg_x64-windows/debug "--enable-asm --enable-yasm --disable-doc --enable-debug --enable-runtime-cpudetect --disable-openssl --disable-ffmpeg --disable-ffplay --disable-ffprobe --disable-libvpx --disable-libx264 --disable-opencl --disable-lzma --disable-bzlib --enable-avresample --disable-cuda --disable-nvenc --disable-cuvid --disable-libnpp --disable-avisynth  --disable-static --enable-shared --extra-cflags=-DHAVE_UNISTD_H=0 --debug --extra-cflags=-MDd --extra-cxxflags=-MDd"
    Working Directory: C:/Users/Vins/Desktop/vcpkg/buildtrees/ffmpeg/x64-windows-dbg
    Error code: 1
    See logs for more information:
      C:\Users\Vins\Desktop\vcpkg\buildtrees\ffmpeg\build-x64-windows-dbg-out.log

Call Stack (most recent call first):
  ports/ffmpeg/portfile.cmake:229 (vcpkg_execute_required_process)
  scripts/ports.cmake:79 (include)

**Error: Building package ffmpeg:x64-windows failed with: BUILD_FAILED**
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: ffmpeg:x64-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by Voskrese** [comment]
![2020-08-09_185324](https://user-images.githubusercontent.com/10104740/89730504-c933db80-da71-11ea-9109-24fe760e5448.png)

**Comment by Voskrese** [comment]
![2020-08-09_185522](https://user-images.githubusercontent.com/10104740/89730534-0bf5b380-da72-11ea-8a71-54d100d51bf8.png)

**Comment by AlainMindana** [comment]
[build-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/5048980/build-x64-windows-dbg-out.log)

**Comment by LilyWangL** [comment]
@AlainMindana Thanks for posting this issue. I found this message in your log:
```
=== CONFIGURING ===
cl.exe is unable to create an executable file.
If cl.exe is a cross-compiler, use the --enable-cross-compile option.
Only do this if you know what cross compiling means.
C compiler test failed.

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.
```
Could you please do as follow this log?

**Comment by AlainMindana** [comment]
Yes will do. Thank you.

**Comment by LilyWangL** [comment]
Pinging @AlainMindana, does this issue resolve?

**Comment by Brouilles** [comment]
Same problem.

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
