### ISSUE TITLE
[vcpkg] upgrade action has no --x-use-aria2 option

### ISSUE THREAD

**Issue by StarGate-One** [microsoft/vcpkg#12834]
****

**Is your feature request related to a problem? Please describe.**
`vcpkg install port port port` allows you to use aria2c to download packages with `--x-use-aria2`
this option is not present in vcpkg upgrade action

**Proposed solution**
add `--x-use-aria2` to be used with vcpkg upgrade action

**Describe alternatives you've considered**
manually build scripts to vcpkg remove all upgraded ports/features and then manually build another script to vcpkg install all upgrade ports/features using the `--x-use-aria2` option do download new sources

**Additional context**
It seems as more and more options are being added to the vcpkg install action, the vcpkg upgrade action is being overlooked as some of the valuable options (not port features) such as `--editable, --x-use-aria2, etc, etc` are not being added to the upgrade actions not to mention vcpkg does not have a mechanism to remember how the port was installed originally so it can upgrade the port with the same options (not port features).

**Comment by strega-nil** [comment]
@StarGate-One would you like to do this work? I can mentor you through it if you like.

**Comment by StarGate-One** [comment]
@strega-nil I am not sure I could take on a task of this scale with my limited knowledge of C/C++. I will think about it and let you know in a few days.

**Comment by StarGate-One** [comment]
@strega-nil I looked through the build/install and upgrade code - at my stage of knowledge of C/C++ I do not believe I would be able to make these changes without considerable delay and the code to make these changes becoming stale at the rapid pace the vcpkg source has been changing the past few weeks.
So I would need to pass as by the time I was able to get something working, it would need reworking to function with what ever the present code base would be.
Anyway, I have built me a work around script (cmd shell), which takes the output from the `vcpkg upgrade`, parses it out and sets a variable to the ports/features requiring an upgrade. It then uses this information to pass to a remove function doing a `vcpkg remove --recurse [ports]` then an identical function doing a `vcpkg install --x-use-aria2 --recurse --keep-going --editable [ports]` - all output directed to a log file in case of failure I can recover the ports/features once the error is corrected.
Thank you for offering and I will still be actively involved here and there :)

**Comment by StarGate-One** [comment]
Closing, no longer an issue for me as we have chosen to no long use vcpkg.
