### ISSUE TITLE
[tensorflow-cc] x64-mingw-static build failure

### ISSUE THREAD

**Issue by gvcallen** [microsoft/vcpkg#12833]
**Host Environment**
- OS: Windows 10
- Compiler: MinGW-8.1.0-X64

**To Reproduce**
vcpkg install tensorflow-cc:x64-mingw-static

**Failure logs** 
-- Warning: Building TensorFlow can take an hour or more.
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:139 (message):
    Command failed: F:/Resources/Programming/DevTools/vcpkg/downloads/tools/msys2/msys64/usr/bin/bash.exe --noprofile --norc -c "F:/Resources/Programming/DevTools/vcpkg/downloads/tools/bazel/0.25.2/bazel.exe build --verbose_failures -c opt --python_path=F:/Resources/Programming/DevTools/Python/Python-3.8.3-64-bit/python.exe --incompatible_disable_deprecated_attr_params=false --define=no_tensorflow_py_deps=true ///tensorflow:libtensorflow_cc.so ///tensorflow:install_headers"
    Working Directory: F:/Resources/Programming/DevTools/vcpkg/buildtrees/tensorflow-cc/x64-mingw-static-rel
    See logs for more information:
      F:\Resources\Programming\DevTools\vcpkg\buildtrees\tensorflow-cc\build-x64-mingw-static-rel-err.log

Call Stack (most recent call first):
  ports/tensorflow-cc/portfile.cmake:90 (vcpkg_execute_build_process)
  scripts/ports.cmake:79 (include)

Error: Building package tensorflow-cc:x64-mingw-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: tensorflow-cc:x64-mingw-static
  Vcpkg version: 2020.06.15-nohash

**Additional context**
The process had a lot of setting up to do. I've therefore only included a portion of the console output.
[build-x64-mingw-static-rel-err.log](https://github.com/microsoft/vcpkg/files/5048246/build-x64-mingw-static-rel-err.log)

**Comment by NancyLi1013** [comment]
Hi @gvcallen 
Thanks for posting this issue.

It seems that it is related with `bazel`.

```
Analyzing: 2 targets (1 packages loaded, 0 targets configured)
INFO: An error occurred during the fetch of repository 'local_config_def_file_filter'
INFO: Call stack for the definition of repository 'local_config_def_file_filter':
 - F:/resources/programming/devtools/vcpkg/buildtrees/tensorflow-cc/x64-mingw-static-rel/tensorflow/workspace.bzl:77:5
 - F:/resources/programming/devtools/vcpkg/buildtrees/tensorflow-cc/x64-mingw-static-rel/WORKSPACE:94:1
INFO: An error occurred during the fetch of repository 'com_google_absl'
INFO: Call stack for the definition of repository 'com_google_absl':
 - F:/resources/programming/devtools/vcpkg/buildtrees/tensorflow-cc/x64-mingw-static-rel/tensorflow/workspace.bzl:137:5
 - F:/resources/programming/devtools/vcpkg/buildtrees/tensorflow-cc/x64-mingw-static-rel/WORKSPACE:94:1
INFO: An error occurred during the fetch of repository 'double_conversion'
INFO: Call stack for the definition of repository 'double_conversion':
 - F:/resources/programming/devtools/vcpkg/buildtrees/tensorflow-cc/x64-mingw-static-rel/tensorflow/workspace.bzl:751:5
 - F:/resources/programming/devtools/vcpkg/buildtrees/tensorflow-cc/x64-mingw-static-rel/WORKSPACE:94:1
```

Could you please refer to https://github.com/tensorflow/tensorflow/issues/30701?

**Comment by Adela0814** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
