### ISSUE TITLE
[zlib:x64-mingw-static] build failure

### ISSUE THREAD

**Issue by gvcallen** [microsoft/vcpkg#12832]
**Host Environment**
- OS: Windows
- Compiler: MinGW-8.1.0-x64

**To Reproduce**
vcpkg install zlib:x64-mingw-static

**Failure logs** 
vcpkg install zlib:x64-mingw-static
Computing installation plan...
The following packages will be built and installed:
    zlib[core]:x64-mingw-static
Detecting compiler hash for triplet x64-mingw-static...
Starting package 1/1: zlib:x64-mingw-static
Building package zlib[core]:x64-mingw-static...
Could not locate cached archive: C:\Users\gvcal\AppData\Local\vcpkg\archives\d9\d95ee68913853ab931fd8aa465d01026679dac5e.zip        
-- Using community triplet x64-mingw-static. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: F:\Resources\Programming\DevTools\vcpkg\triplets\community\x64-mingw-static.cmake
-- Using cached F:/Resources/Programming/DevTools/vcpkg/downloads/zlib1211.tar.gz
-- Cleaning sources at F:/Resources/Programming/DevTools/vcpkg/buildtrees/zlib/src/1.2.11-deec42f53b.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source F:/Resources/Programming/DevTools/vcpkg/downloads/zlib1211.tar.gz
-- Applying patch cmake_dont_build_more_than_needed.patch
-- Using source at F:/Resources/Programming/DevTools/vcpkg/buildtrees/zlib/src/1.2.11-deec42f53b.clean
-- Configuring x64-mingw-static
-- Building x64-mingw-static-dbg
-- Building x64-mingw-static-rel
-- Fixing pkgconfig
-- Fixing pkgconfig - release
-- Checking file: F:/Resources/Programming/DevTools/vcpkg/packages/zlib_x64-mingw-static/lib/pkgconfig/zlib.pc
-- pkg_cfg_cmd call with:F:/Resources/Programming/DevTools/Perl/strawberry-perl-5.30.2.1-64bit/perl/bin/pkg-config --exists zlib failed
-- ENV{PKG_CONFIG_PATH}:/F/Resources/Programming/DevTools/vcpkg/installed/x64-mingw-static/lib/pkgconfig:/F/Resources/Programming/DevTools/vcpkg/installed/x64-mingw-static/share/pkgconfig:/F/Resources/Programming/DevTools/vcpkg/packages/zlib_x64-mingw-static/lib/pkgconfig:/F/Resources/Programming/DevTools/vcpkg/packages/zlib_x64-mingw-static/share/pkgconfig
-- pkg-config call failed with error code:%1 is not a valid Win32 application
-- pkg-config output:
CMake Error at scripts/cmake/vcpkg_fixup_pkgconfig.cmake:84 (message):
  pkg-config error output:
Call Stack (most recent call first):
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:316 (vcpkg_fixup_pkgconfig_check_files)
  ports/zlib/portfile.cmake:46 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:79 (include)

Error: Building package zlib:x64-mingw-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zlib:x64-mingw-static
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.

**Additional context**
I was actually trying to install wxWidgets, but this failed when it reached zlib. I therefore tried to build zlib by itself, but this still failed as above.

**Comment by Neumann-A** [comment]
You need to adjust your `PATH` variable so that` find_program(PKGCONFIG pkg-config PATHS "bin" "/usr/bin" "/usr/local/bin")` does pickup the correct pkg-config. 
Maybe VCPKG really requires a way to pass CMake variables via the cmd line.

**Comment by JackBoosY** [comment]
@Neumann-A Should we download pkgconfig automaticlly in `vcpkg_find_acquire_program`?

**Comment by rmillsTalon** [comment]
Hi, I receiving this error too. The release check passed but not the debug. ...\vcpkg\packages\zlib_x86-windows\debug\lib\zlibd.lib does exist so maybe it is a problem in zlib.pc for debug?

Is there a workaround? I installed vcpkg less than an hour ago.

...
-- Fixing pkgconfig - release
-- Checking file: C:/dev/tools/vcpkg/packages/zlib_x86-windows/lib/pkgconfig/zlib.pc
-- Fixing pkgconfig - debug
-- Checking file: C:/dev/tools/vcpkg/packages/zlib_x86-windows/debug/lib/pkgconfig/zlib.pc
-- CHECK_LIB_zlibd_DEBUG:CHECK_LIB_zlibd_DEBUG-NOTFOUND
CMake Error at scripts/cmake/vcpkg_fixup_pkgconfig.cmake:239 (message):
  Library "zlibd" was not found! If it is a system library use the
  SYSTEM_LIBRARIES parameter for the vcpkg_fixup_pkgconfig call! Otherwise,
  correct the *.pc file
Call Stack (most recent call first):
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:348 (vcpkg_fixup_pkgconfig_check_files)
  ports/zlib/portfile.cmake:46 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:79 (include)


Error: Building package zlib:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zlib:x86-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by GPSnoopy** [comment]
@rmillsTalon I have the same issue with bzip2 on x64-windows-static.

**Comment by qimenlang** [comment]
delete vcpkg_fixup_pkgconfig

**Comment by cgolchert** [comment]
zlib error from trying to install openvdb[tools]



  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:4 (project)


-- Configuring incomplete, errors occurred!
See also "C:/dev/vcpkg/buildtrees/zlib/x64-windows-rel/CMakeFiles/CMakeOutput.log".
See also "C:/dev/vcpkg/buildtrees/zlib/x64-windows-rel/CMakeFiles/CMakeError.log".
[2/2] cmd /c "cd ../../x64-windows-dbg && "C:/dev/vcpkg/downloads/tools/cmake-3.17.2-windows/cmake-3.17.2-win32-x86/bin/cmake.exe" "C:/dev/vcpkg/buildtrees/zlib/src/1.2.11-1d48fa5a18.clean" "-DSKIP_INSTALL_FILES=ON" "-DSKIP_BUILD_EXAMPLES=ON" "-DCMAKE_MAKE_PROGRAM=C:/dev/vcpkg/downloads/tools/ninja/ninja-1.10.0/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/dev/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v140" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_TARGET_ARCHITECTURE=x64" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=C:/dev/vcpkg" "-D_VCPKG_INSTALLED_DIR=C:/dev/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF" "-DSKIP_INSTALL_HEADERS=ON" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_INSTALL_PREFIX=C:/dev/vcpkg/packages/zlib_x64-windows/debug""
FAILED: ../../x64-windows-dbg/CMakeCache.txt 
cmd /c "cd ../../x64-windows-dbg && "C:/dev/vcpkg/downloads/tools/cmake-3.17.2-windows/cmake-3.17.2-win32-x86/bin/cmake.exe" "C:/dev/vcpkg/buildtrees/zlib/src/1.2.11-1d48fa5a18.clean" "-DSKIP_INSTALL_FILES=ON" "-DSKIP_BUILD_EXAMPLES=ON" "-DCMAKE_MAKE_PROGRAM=C:/dev/vcpkg/downloads/tools/ninja/ninja-1.10.0/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/dev/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v140" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_TARGET_ARCHITECTURE=x64" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=C:/dev/vcpkg" "-D_VCPKG_INSTALLED_DIR=C:/dev/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF" "-DSKIP_INSTALL_HEADERS=ON" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_INSTALL_PREFIX=C:/dev/vcpkg/packages/zlib_x64-windows/debug""
-- The C compiler identification is MSVC 19.0.24215.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe - broken
CMake Error at C:/dev/vcpkg/downloads/tools/cmake-3.17.2-windows/cmake-3.17.2-win32-x86/share/cmake-3.17/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/dev/vcpkg/buildtrees/zlib/x64-windows-dbg/CMakeFiles/CMakeTmp
    
    Run Build Command(s):C:/dev/vcpkg/downloads/tools/ninja/ninja-1.10.0/ninja.exe cmTC_3bed8 && [1/2] Building C object CMakeFiles\cmTC_3bed8.dir\testCCompiler.c.obj
    [2/2] Linking C executable cmTC_3bed8.exe
    FAILED: cmTC_3bed8.exe 
    cmd.exe /C "cd . && C:\dev\vcpkg\downloads\tools\cmake-3.17.2-windows\cmake-3.17.2-win32-x86\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_3bed8.dir --rc=C:\Windows\RC.Exe --mt=CMAKE_MT-NOTFOUND --manifests  -- C:\PROGRA~2\MICROS~1.0\VC\bin\amd64\link.exe /nologo CMakeFiles\cmTC_3bed8.dir\testCCompiler.c.obj  /out:cmTC_3bed8.exe /implib:cmTC_3bed8.lib /pdb:cmTC_3bed8.pdb /version:0.0  /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    LINK Pass 1: command "C:\PROGRA~2\MICROS~1.0\VC\bin\amd64\link.exe /nologo CMakeFiles\cmTC_3bed8.dir\testCCompiler.c.obj /out:cmTC_3bed8.exe /implib:cmTC_3bed8.lib /pdb:cmTC_3bed8.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\cmTC_3bed8.dir/intermediate.manifest CMakeFiles\cmTC_3bed8.dir/manifest.res" failed (exit code 1104) with the following output:
    LINK : fatal error LNK1104: cannot open file 'gdi32.lib'
    ninja: build stopped: subcommand failed.
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:4 (project)


-- Configuring incomplete, errors occurred!
See also "C:/dev/vcpkg/buildtrees/zlib/x64-windows-dbg/CMakeFiles/CMakeOutput.log".
See also "C:/dev/vcpkg/buildtrees/zlib/x64-windows-dbg/CMakeFiles/CMakeError.log".
ninja: build stopped: subcommand failed.

**Comment by longnguyen2004** [comment]
This was fixed in PR https://github.com/microsoft/vcpkg/pull/12753, please update vcpkg by using `git pull` and try again

**Comment by cgolchert** [comment]
pretty sure it wasn't.

[zlib.txt](https://github.com/microsoft/vcpkg/files/5066262/zlib.txt)

**Comment by longnguyen2004** [comment]
@cgolchert Seems like you're missing `gdi32.lib` somehow, which is not what this issue is about. I recommend you to open another issue
@rmillsTalon Can you please test with latest vcpkg?

**Comment by cgolchert** [comment]
Is there a reason why a new install of VC2017 wouldn't install it?

I got sent to this thread because of another issue.

**Comment by longnguyen2004** [comment]
I can't repro this issue now, maybe it has been fixed at some point.

**Comment by JackBoosY** [comment]
Hi guys, is this issue resolved?

**Comment by longnguyen2004** [comment]
@JackBoosY I think this is resolved, I can't repro this

**Comment by sfhacker** [comment]
zlib is such a small and simple project that it shouldn't take several months to be built from source.
Most probably the user environment is broken or polluted somehow!
In any case, no user can afford such amount of time.

**Comment by JackBoosY** [comment]
@sfhacker Yeah I know that, see #13402.
