### ISSUE TITLE
[New Port Request] Urho3D

### ISSUE THREAD

**Issue by wagnrd** [microsoft/vcpkg#12842]
Library name: Urho3D

Library description: Cross-platform 2D and 3D game engine.

Source repository URL: https://github.com/urho3d/Urho3D

Project homepage (if different from the source repository): https://urho3d.github.io

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
The versioning is a little bit weird. So the most recent stable release is 1.7.1, whereas the top most tag number in git is 1.32 (which would be between 1.3 and 1.4).

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
