### ISSUE TITLE
.\bootstrap-vcpkg.bat Error

### ISSUE THREAD

**Issue by johnny-mueller** [microsoft/vcpkg#12844]
I proceed according to the following procedure:
```python
git clone https://github.com/microsoft/vcpkg
cd vcpkg
$env:VCPKG_ROOT=$PWD
.\bootstrap-vcpkg.bat
```

I get the following error message after running the .bat file:
```python
MSBUILD : error MSB1009: Die Projektdatei ist nicht vorhanden.
Schalter: C:\Windows\System32\vcpkg\toolsrc\windows-bootstrap\dirs.proj
C:\Windows\System32\vcpkg\scripts\bootstrap.ps1 : Building vcpkg.exe failed. Please ensure you have installed
Visual Studio with the Desktop C++ workload and the Windows SDK for Desktop C++.
In Zeile:1 Zeichen:4
+ & {& 'C:\Windows\System32\vcpkg\scripts\bootstrap.ps1' }
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,bootstrap.ps1

ScriptHalted
In C:\Windows\System32\vcpkg\scripts\bootstrap.ps1:411 Zeichen:5
+     throw
+     ~~~~~
    + CategoryInfo          : OperationStopped: (:) [], RuntimeException
    + FullyQualifiedErrorId : ScriptHalted
```

My installed packages from Visual studio installer:
Visual Studio Build Tools 2019 (16.7.0) incl. English lanuage packet
![grafik](https://user-images.githubusercontent.com/64581980/89788487-87616e80-db1f-11ea-8dbb-5c3f46af91a3.png)

Visual Studio Community 2019 (16.7.0) incl. English lanuage packet
![grafik](https://user-images.githubusercontent.com/64581980/89792306-a6163400-db24-11ea-940d-77dfa3818184.png)

Did I miss a needed of the package or how is it possible to overcome the error?

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Could you install the following item and rerun `.\bootstrap-vcpkg.bat`?
![image](https://user-images.githubusercontent.com/47812810/89851949-52592880-dbc0-11ea-9efb-165bfb71222a.png)

**Comment by johnny-mueller** [comment]
My current installed packages from Visual studio installer:
Visual Studio Community 2019 (16.7.0) incl. English lanuage packet:
![grafik](https://user-images.githubusercontent.com/64581980/89859566-912bb600-dba1-11ea-91cf-402904fc2177.png)
@LilyWangL 

Visual Studio Build Tools 2019 (16.7.0) incl. English lanuage packet
![grafik](https://user-images.githubusercontent.com/64581980/89859598-a6084980-dba1-11ea-813f-9e121c25c5f5.png)

Output of ".\bootstrap-vcpkg.bat":
```python
Schalter: C:\Windows\System32\vcpkg\toolsrc\windows-bootstrap\dirs.proj
C:\Windows\System32\vcpkg\scripts\bootstrap.ps1 : Building vcpkg.exe failed. Please ensure you have installed Visual Studio with the
Desktop C++ workload and the Windows SDK for Desktop C++.
In Zeile:1 Zeichen:4
+ & {& 'C:\Windows\System32\vcpkg\scripts\bootstrap.ps1' }
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,bootstrap.ps1

ScriptHalted
In C:\Windows\System32\vcpkg\scripts\bootstrap.ps1:411 Zeichen:5
+     throw
+     ~~~~~
    + CategoryInfo          : OperationStopped: (:) [], RuntimeException
    + FullyQualifiedErrorId : ScriptHalted
```

**Comment by LilyWangL** [comment]
Duplicate with #9392.

**Comment by johnny-mueller** [comment]
@LilyWangL Is there at the moment a workaround or a solution for that issue?

**Comment by LilyWangL** [comment]
> @LilyWangL Is there at the moment a workaround or a solution for that issue?

We will confirm this issue soon.

**Comment by LilyWangL** [comment]
@johnny-mueller Could you please provide all output of ".\bootstrap-vcpkg.bat" with VCPKG? Thanks.

**Comment by johnny-mueller** [comment]
@LilyWangL 
```python
PS C:\WINDOWS\system32> cd vcpkg
PS C:\WINDOWS\system32\vcpkg> $env:VCPKG_ROOT=$PWD
PS C:\WINDOWS\system32\vcpkg> .\bootstrap-vcpkg.bat

Building vcpkg.exe ...

MSBUILD : error MSB1009: Die Projektdatei ist nicht vorhanden.
Schalter: C:\Windows\System32\vcpkg\toolsrc\windows-bootstrap\dirs.proj
C:\Windows\System32\vcpkg\scripts\bootstrap.ps1 : Building vcpkg.exe failed. Please ensure you have installed
Visual Studio with the Desktop C++ workload and the Windows SDK for Desktop C++.
In Zeile:1 Zeichen:4
+ & {& 'C:\Windows\System32\vcpkg\scripts\bootstrap.ps1' }
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,bootstrap.ps1

ScriptHalted
In C:\Windows\System32\vcpkg\scripts\bootstrap.ps1:411 Zeichen:5
+     throw
+     ~~~~~
    + CategoryInfo          : OperationStopped: (:) [], RuntimeException
    + FullyQualifiedErrorId : ScriptHalted
```

**Comment by LilyWangL** [comment]
Thanks for your reply. You should not install vcpkg in _C:\Windows\System32\_. You will never ever have enough privileges to use a build-system. Install vcpkg to the root of any drive, but preferably not on _C:_. Also, don't put it in a path with spaces in it.

**Comment by johnny-mueller** [comment]
@LilyWangL Thanks for the advice. It works like a charm.
