### ISSUE TITLE
[New Port Request] PJSIP (include PJSUA)

### ISSUE THREAD

**Issue by zzfnohell** [microsoft/vcpkg#12840]
Library name: PJSIP 

Library description:

PJSIP is a free and open source multimedia communication library written in C language implementing standard based protocols such as SIP, SDP, RTP, STUN, TURN, and ICE. It combines signaling protocol (SIP) with rich multimedia framework and NAT traversal functionality into high level API that is portable and suitable for almost any type of systems ranging from desktops, embedded systems, to mobile handsets.

Source repository URL: https://www.pjsip.org/
Project homepage (if different from the source repository):
https://github.com/pjsip/pjproject.git

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
