### ISSUE TITLE
[vxl:x64-osx] build failure

### ISSUE THREAD

**Issue by kapikantzari** [microsoft/vcpkg#12850]
**Host Environment**
- OS: MacOS

**To Reproduce**
`./vcpkg install vxl`

**Failure logs** 
`Starting package 12/12: vxl:x64-osx`
`Building package vxl[core]:x64-osx...`
`Could not locate cached archive:` `/Users/catherine/.cache/vcpkg/archives/c7/c78021fec5637ccdf298539ec08aca263050810c.zip`
`-- Downloading https://github.com/vxl/vxl/archive/dac1c7ed8e183e9c6de8b928c8b0294a7bd1d8ee.tar.gz...`
`-- Extracting source /Users/catherine/vcpkg/downloads/vxl-vxl-dac1c7ed8e183e9c6de8b928c8b0294a7bd1d8ee.tar.gz`
`-- Applying patch fix_dependency.patch`
`CMake Error at scripts/cmake/vcpkg_apply_patches.cmake:51 (message):`
`  Applying patch failed.  Checking patch core/CMakeLists.txt...`

`  error: while searching for:`

  

  

`  # coordinate systems`

`  if(BUILD_CORE_GEOMETRY AND BUILD_CORE_NUMERICS)`

`    add_subdirectory(vcsl)`
`    add_subdirectory(vpgl)`

`  endif()`

  

`  error: patch failed: core/CMakeLists.txt:100`

`  error: core/CMakeLists.txt: patch does not apply`

`Call Stack (most recent call first):`
`  scripts/cmake/vcpkg_extract_source_archive_ex.cmake:141 (vcpkg_apply_patches)`
`  scripts/cmake/vcpkg_from_github.cmake:139 (vcpkg_extract_source_archive_ex)`
`  ports/vxl/portfile.cmake:10 (vcpkg_from_github)`
`  scripts/ports.cmake:79 (include)`

`Error: Building package vxl:x64-osx failed with: BUILD_FAILED`

`  Package: vxl:x64-osx`
`  Vcpkg version: 2020.06.15-unknownhash`

**Additional context**
I'm pretty sure my vcpkg is up-to-date.

**Comment by NancyLi1013** [comment]
Hi @kapikantzari 
Thanks for posting this issue.

I submitted a PR to update the patch.
Could you please help confirm if the new patch can woke fine?

**Comment by kapikantzari** [comment]
Hi @NancyLi1013 
Thanks for your reply.
vcpkg still gives me the same error message. Has the new patch been applied yet?

**Comment by NancyLi1013** [comment]
@NancyLi1013 
Since this PR has not been merged yet to master. 
You need to manually update the patch or rebuild this port based on PR #12854.

**Comment by kapikantzari** [comment]
Hi @NancyLi1013 
Yes it has cleared the previous error. Many thanks for the help!
