### ISSUE TITLE
[libpq:x86-windows-static] build failure

### ISSUE THREAD

**Issue by micmatsch** [microsoft/vcpkg#12855]
**Host Environment**
- OS: Windows 10
- Compiler: MS Visual Studio 2017

**To Reproduce**
`./vcpkg install poco:x86-windows-static` fails at dependency `libpq:x86-windows-static`

**Failure logs** 
```
-- Using cached D:/code/vcpp/vcpkg/downloads/postgresql-12.2.tar.bz2
-- Cleaning sources at D:/code/vcpp/vcpkg/buildtrees/libpq/src/tgresql-12-c19559b5c2.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/code/vcpp/vcpkg/downloads/postgresql-12.2.tar.bz2
-- Applying patch patches/windows/install.patch
-- Applying patch patches/windows/win_bison_flex.patch
-- Applying patch patches/windows/openssl_exe_path.patch
-- Applying patch patches/windows/Solution.patch
-- Applying patch patches/windows/MSBuildProject_fix_gendef_perl.patch
-- Applying patch patches/windows/msgfmt.patch
-- Applying patch patches/windows/python_lib.patch
-- Applying patch patches/linux/configure.patch
-- Applying patch patches/windows/MSBuildProject-static-lib.patch
-- Applying patch patches/windows/Mkvcbuild-static-lib.patch
-- Applying patch patches/windows/MSBuildProject-static-crt.patch
-- Applying patch patches/windows/minimize_install.patch
-- Using source at D:/code/vcpp/vcpkg/buildtrees/libpq/src/tgresql-12-c19559b5c2.clean
-- Copying libpq source files to D:/code/vcpp/vcpkg/buildtrees/libpq/x86-windows-static-rel...
-- Copying libpq source files... done
-- Applying patch patches/windows/Solution_RELEASE.patch
-- Applying patch patches/windows/python3_build_RELEASE.patch
-- Patches applied!
-- Building libpq x86-windows-static-RELEASE...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: D:/code/vcpp/vcpkg/downloads/tools/perl/perl/bin/perl.exe build.pl RELEASE libpq
    Working Directory: D:/code/vcpp/vcpkg/buildtrees/libpq/x86-windows-static-rel/src/tools/msvc
    Error code: 1
    See logs for more information:
      D:\code\vcpp\vcpkg\buildtrees\libpq\build-libpq-x86-windows-static-RELEASE-out.log
```

Attached log: [build-libpq-x86-windows-static-RELEASE-out.log](https://github.com/microsoft/vcpkg/files/5055612/build-libpq-x86-windows-static-RELEASE-out.log)

Relevant error in log:
```
Lib:
 C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x86\Lib.exe /OUT:".\Release\libpq\libpq.lib" /NOLOGO .\Release\libpq\libpq.res
 .\Release\libpq\encnames.obj
 .\Release\libpq\wchar.obj
 ".\Release\libpq\fe-auth-scram.obj"
 ".\Release\libpq\fe-auth.obj"
 ".\Release\libpq\fe-connect.obj"
 ".\Release\libpq\fe-exec.obj"
 ".\Release\libpq\fe-lobj.obj"
 ".\Release\libpq\fe-misc.obj"
 ".\Release\libpq\fe-print.obj"
 ".\Release\libpq\fe-protocol2.obj"
 ".\Release\libpq\fe-protocol3.obj"
 ".\Release\libpq\fe-secure-common.obj"
 ".\Release\libpq\fe-secure-openssl.obj"
 ".\Release\libpq\fe-secure.obj"
 ".\Release\libpq\legacy-pqsignal.obj"
 ".\Release\libpq\libpq-events.obj"
 .\Release\libpq\pqexpbuffer.obj
 ".\Release\libpq\pthread-win32.obj"
 .\Release\libpq\win32.obj
1>LINK : warning LNK4068: /MACHINE not specified; defaulting to X64 [D:\code\vcpp\vcpkg\buildtrees\libpq\x86-windows-static-rel\libpq.vcxproj]
1>.\Release\libpq\encnames.obj : fatal error LNK1112: module machine type 'x86' conflicts with target machine type 'x64' [D:\code\vcpp\vcpkg\buildtrees\libpq\x86-windows-static-rel\libpq.vcxproj]
```

MSVC Linker is unable to automatically determine the target machine type x86 and unfortunately defaults to x64.

**Additional context**
Made sure I had latest portfiles with `git pull` / `vcpkg update`

**Comment by andyzimmerer** [comment]
[]()

**Comment by sfhacker** [comment]
Any news/update on this open issue?

We use MinGW to build many applications.

![image](https://user-images.githubusercontent.com/25817529/90018183-e1b12980-dcef-11ea-9d5b-5d851ce073fc.png)

**Comment by micmatsch** [comment]
The problem is still there. I am not exactly an expert with cpp build tools and installed vcpkg just a few days ago, so I am not sure if I am the right person to come up with a fix. I am currently using the dynamic x86-windows triplet and that works fine, so this is no an urgent issue for me.

The problem seems rather straightforward to me: The vidual studio linker fails because it is unable to determine the target machine type x86, I assume because the first linked file is a .res without that information, and defaults to x64, I assume because that is the host machine type. Fixing it would require to add the parameter `/MACHINE:X86` to the linker command line, but I am not sure what the best way to do that would be.

**Comment by ifrisbie** [comment]
I've encountered this problem on package libpq as well.  The problem looks to be (perhaps) a bug in v141 linker (where it gives up trying to identify the architecture if the first file doesn't have that info) as it isn't an issue with v142 (VS2019).  My guess is that no one recently verified that they would still build under v141.  It is annoying for sure because I need to be able to build using VS2017 - but it appears to be a problem with the source library rather than vcpkg.  Would be nice to be able to force it though.   I think you should be able to use a custom triplet and set CMAKE_EXE_LINKER_FLAGS to append /MACHINE:X86.

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/13726
