### ISSUE TITLE
[python3] build failure

### ISSUE THREAD

**Issue by arkaprabha-majumdar** [microsoft/vcpkg#12868]
Please help me with this. I'm unsure what to do.
![Screenshot from 2020-08-12 12-51-42](https://user-images.githubusercontent.com/57062313/89987041-029b5f80-dc9b-11ea-9c0d-2aedd90423f1.png)

**Comment by PhoebeHui** [comment]
@arkaprabha-majumdar, could you try below steps:

1. Download https://github.com/python/cpython/archive/v3.8.3.tar.gz manually
2. Put it to ./vcpkg/downloads folder
3. Rename it to 'python-cpython-v3.8.3.tar.gz'
4. Try to install the port again

**Comment by PhoebeHui** [comment]
@arkaprabha-majumdar, does the problem solve?

**Comment by arkaprabha-majumdar** [comment]
It may solve the problem. I stopped the process. I'll try it out.

**Comment by PhoebeHui** [comment]
Feel free to reopen this issue if it still be a problem for you.
