### ISSUE TITLE
[libepoxy:x64-windows] build failure

### ISSUE THREAD

**Issue by Taeyeong201** [microsoft/vcpkg#12865]
**Host Environment**
- OS: Windows 10
- Compiler: MSVC 2019

**To Reproduce**
`./vcpkg install libepoxy:x64-windows`

**Failure logs** 
```
D:\vcpkg>vcpkg.exe install libepoxy:x64-windows
Computing installation plan...
The following packages will be built and installed:
    libepoxy[core]:x64-windows
Detecting compiler hash for triplet x64-windows...
Starting package 1/1: libepoxy:x64-windows
Building package libepoxy[core]:x64-windows...
Could not locate cached archive: C:\Users\mslm01\AppData\Local\vcpkg\archives\94\9480f052357668918d7616b96287a0c9395b66cb.zip
-- Using cached D:/vcpkg/downloads/anholt-libepoxy-1.5.4.tar.gz
-- Cleaning sources at D:/vcpkg/buildtrees/libepoxy/src/1.5.4-337c486045.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/vcpkg/downloads/anholt-libepoxy-1.5.4.tar.gz
-- Applying patch libepoxy-1.5.4_Add_call_convention_to_mock_function.patch
-- Using source at D:/vcpkg/buildtrees/libepoxy/src/1.5.4-337c486045.clean
-- Acquiring MSYS Packages...
-- Acquiring MSYS Packages... OK
-- Configuring x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: D:/vcpkg/downloads/tools/python/python-3.8.3-x64/python.exe D:/vcpkg/downloads/tools/meson/meson-0.54.2/meson.py -Denable-glx=no -Denable-egl=no -Dcmake_prefix_path=['D:/vcpkg/installed/x64-windows','D:/vcpkg/installed/x64-windows/share'] --buildtype plain --backend ninja --wrap-mode nodownload --default-library shared --libdir lib --prefix D:/vcpkg/packages/libepoxy_x64-windows/debug --includedir ../include D:/vcpkg/buildtrees/libepoxy/src/1.5.4-337c486045.clean -Dc_args=['/nologo','/DWIN32','/D_WINDOWS','/W3','/MP','/D_DEBUG','/MDd','/Z7','/Ob0','/Od','/RTC1'] -Dcpp_args=['/nologo','/DWIN32','/D_WINDOWS','/W3','/GR','/EHsc','/MP','/D_DEBUG','/MDd','/Z7','/Ob0','/Od','/RTC1'] -Dc_link_args=[] -Dcpp_link_args=[]
    Working Directory: D:/vcpkg/buildtrees/libepoxy/x64-windows-dbg
    Error code: 2
    See logs for more information:
      D:\vcpkg\buildtrees\libepoxy\config-x64-windows-dbg-out.log
      D:\vcpkg\buildtrees\libepoxy\config-x64-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_meson.cmake:161 (vcpkg_execute_required_process)
  ports/libepoxy/portfile.cmake:15 (vcpkg_configure_meson)
  scripts/ports.cmake:79 (include)


Error: Building package libepoxy:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libepoxy:x64-windows
  Vcpkg version: 2020.06.15-nohash
```

[config-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/5060657/config-x64-windows-dbg-err.log)   
[config-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/5060658/config-x64-windows-dbg-out.log)

   
**Additional context**
I saw and followed issues related to 'libepoxy'. But it bothers me with the same error.

**Comment by Voskrese** [comment]
open `cmd.exe`
run `chcp`

?

**Comment by Taeyeong201** [comment]
"chcp" output 949
But I type "chcp 65001".
I reinstalled vcpkg from scratch and installed libepoxy, but
I have the same error

[vcpkg_install_libepoxy_error.txt](https://github.com/microsoft/vcpkg/files/5061494/vcpkg_install_libepoxy_error.txt)

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Do you install English language package on Visual Studio Installer? I found Korean warning in you install log.

**Comment by Taeyeong201** [comment]
I checked that the English language pack was installed,
I erased the Korean language pack and rebooted it.

And I tried installing vcpkg and libepoxy from the beginning, but it is the same error.
[vcpkg_install_libepoxy_error_2.txt](https://github.com/microsoft/vcpkg/files/5062020/vcpkg_install_libepoxy_error_2.txt)   

I got a Unicode format warning on file "\vcpkg\toolsrc\src\vcpkg\export.prefab.cpp".
So I changed the character encoding from UTF-8 to ANSI in Notepad 
and tried again from the beginning, but it was the same error.
[warningFix_vcpkg_install_libepoxy_error.txt](https://github.com/microsoft/vcpkg/files/5062110/warningFix_vcpkg_install_libepoxy_error.txt)

**Comment by LilyWangL** [comment]
Thanks for your reply. Could you try to tick a "Use Unicode UTF-8 for worldwide language support", box in "Region & Language" - "Administrative" - "Change system locale" - "Region Settings".
![image](https://user-images.githubusercontent.com/47812810/90088626-f7efd180-dd51-11ea-9350-6e4bab0383ae.png)
Then clone VCPKG and install libepoxy again. Thanks.

**Comment by Taeyeong201** [comment]
Amazing!!! 
from installing vcpkg to installing libepoxy, there was no warning, no error.
So I solved the problem.

Thanks a million.
Thanks a bunch.
I really appreciate it.
I can’t thank you enough.
I don’t have the words to thank you for this.
