### ISSUE TITLE
[New Port Request] <QuickJS>

### ISSUE THREAD

**Issue by kingdevnl** [microsoft/vcpkg#12879]
Library name:
QuickJS
Library description:
QuickJS is a small and embeddable Javascript engine. It supports the ES2020 specification including modules, asynchronous generators, proxies and BigInt.

Source repository URL:
https://github.com/horhof/quickjs
Project homepage (if different from the source repository):
https://bellard.org/quickjs/
Anything else that is useful to know when adding (such as optional features the library may have that should be included):

It seems to be a MinGW project?

**Comment by blackknifes** [comment]
It's source code use gcc expanded feature.So it cannot be build by msvc, but could be build by clang-cl.
Need edit some code before build it on Windows (The code include some linux header and call some posix function, example unistd header file and gettimeofday function).

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
