### ISSUE TITLE
[lapack] build failure

### ISSUE THREAD

**Issue by FishHe** [microsoft/vcpkg#12888]
After #12805 ， the lapack can not be built.

[1/2] cmd /c "cd ../../x64-windows-static-md-dbg && "C:/Program Files/CMake/bin/cmake.exe" "D:/vcpkg/buildtrees/lapack-reference/src/v3.8.0-954f10683f.clean" "-DUSE_OPTIMIZED_BLAS=OFF" "-DCBLAS=OFF" "-DCMAKE_GNUtoMS=ON" "-DCMAKE_Fortran_COMPILER=D:/vcpkg/downloads/tools/msys2/msys64/mingw64/bin/gfortran.exe" "-DCMAKE_C_COMPILER=D:/vcpkg/downloads/tools/msys2/msys64/mingw64/bin/gcc.exe" "-DCMAKE_Fortran_FLAGS_INIT:STRING= -mabi=ms -m64 " "-DCMAKE_MAKE_PROGRAM=C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=D:/vcpkg/scripts/toolchains/mingw.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows-static-md" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v142" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=D:/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_TARGET_ARCHITECTURE=x64" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=D:/vcpkg" "-D_VCPKG_INSTALLED_DIR=D:/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_INSTALL_PREFIX=D:/vcpkg/packages/lapack-reference_x64-windows-static-md/debug""
FAILED: ../../x64-windows-static-md-dbg/CMakeCache.txt 
cmd /c "cd ../../x64-windows-static-md-dbg && "C:/Program Files/CMake/bin/cmake.exe" "D:/vcpkg/buildtrees/lapack-reference/src/v3.8.0-954f10683f.clean" "-DUSE_OPTIMIZED_BLAS=OFF" "-DCBLAS=OFF" "-DCMAKE_GNUtoMS=ON" "-DCMAKE_Fortran_COMPILER=D:/vcpkg/downloads/tools/msys2/msys64/mingw64/bin/gfortran.exe" "-DCMAKE_C_COMPILER=D:/vcpkg/downloads/tools/msys2/msys64/mingw64/bin/gcc.exe" "-DCMAKE_Fortran_FLAGS_INIT:STRING= -mabi=ms -m64 " "-DCMAKE_MAKE_PROGRAM=C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=D:/vcpkg/scripts/toolchains/mingw.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows-static-md" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v142" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=D:/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_TARGET_ARCHITECTURE=x64" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=D:/vcpkg" "-D_VCPKG_INSTALLED_DIR=D:/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_INSTALL_PREFIX=D:/vcpkg/packages/lapack-reference_x64-windows-static-md/debug""
CMake Error at CMakeLists.txt:3 (project):
  The Ninja generator does not support Fortran using Ninja version

    1.8.2

  due to lack of required features.  Ninja 1.10 or higher is required.

**Comment by Neumann-A** [comment]
`"-DCMAKE_MAKE_PROGRAM=C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe"` is the problem. It is not using ninja from vcpkg

**Comment by Voskrese** [comment]
@Neumann-A 

add PREPEND path ?

`vcpkg_add_to_path(PREPEND ${NINJA_DIR}`

**Comment by Neumann-A** [comment]
@Voskrese Won't help NINJA_DIR would still point to the first found NINJA instead of the vcpkg internal one (which is not even downloaded if it finds ninja from VS.)
#12895 solves it by introducing a version check for ninja

**Comment by Voskrese** [comment]
I was talking about parameters in the configurator and installer

example
https://github.com/microsoft/vcpkg/blob/5bb91a9452c2155e8ccd69c88629af24507249d4/scripts/cmake/vcpkg_configure_cmake.cmake#L154

**Comment by Neumann-A** [comment]
doesn't matter because of line after that being:
`list(APPEND _csc_OPTIONS "-DCMAKE_MAKE_PROGRAM=${NINJA}")`

`vcpkg_add_to_path("${NINJA_PATH}") `  could be removed

**Comment by Voskrese** [comment]
why are these settings ignored then?
_after all, it is clearly stated here_ hmm

```
    if(GENERATOR STREQUAL "Ninja")
        vcpkg_find_acquire_program(NINJA)
        list(APPEND _csc_OPTIONS "-DCMAKE_MAKE_PROGRAM=${NINJA}")
    endif()
```

**Comment by Neumann-A** [comment]
because of how `vcpkg_find_acquire_program(NINJA)` works. It always uses the system ninja if it finds one unless it can find one in vcpkg search/download paths. Since there is a system one it will not download the internal one.

**Comment by Voskrese** [comment]
there is still such an option, I do not know how with the old version, but in 2019 so

`"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -help`

>     -no_ext : Only scripts from [VS160COMNTOOLS]\VsDevCmd\Core
>               directory are run during initialization.
>     -no_logo : Suppress printing of the developer command prompt banner.

`"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -no_ext`

```
[DEBUG:VsDevCmd] Writing pre-initialization environment to C:\temp\dd_vsdevcmd16_preinit_env.log
[DEBUG:core\vsdevcmd_start] initializing with arguments ''
[DEBUG:core\parse_cmd.bat] initializaing with arguments ''
[DEBUG:VsDevCmd.bat] Found version "16.7.1"
[DEBUG:VsDevCmd.bat] calling "core\dotnet.bat"
[DEBUG:core\dotnet.bat] init:COMPLETE
[DEBUG:VsDevCmd.bat] calling "core\msbuild.bat"
[DEBUG:core\msbuild.bat] initializing...
[DEBUG:core\msbuild.bat] init:COMPLETE
[DEBUG:VsDevCmd.bat] calling "core\winsdk.bat"
[DEBUG:winsdk.bat] initializing...
[DEBUG:core\winsdk.bat] init:COMPLETE
[DEBUG:VsDevCmd.bat] Skipping vsdevcmd\ext scripts since -no_ext was specified
[DEBUG:core\vsdevcmd_end] initializing with arguments ''
[DEBUG:VsDevCmd] Writing post-execution environment to C:\temp\dd_vsdevcmd16_env.log
```

`where ninja`

> C:\Program Files\CMake\bin\ninja.exe
> E:\tools\bin\ninja.exe


**DEFAULT**

`"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat"`

`where ninja`

> C:\Program Files\CMake\bin\ninja.exe
> E:\tools\bin\ninja.exe
> C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja\ninja.exe

**Comment by Voskrese** [comment]
` [DEBUG:VsDevCmd.bat] calling "ext\cmake.bat"`

```
:export_path

if not exist "%VSINSTALLDIR%Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin" goto :error_setting_path
if not exist "%VSINSTALLDIR%Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja" goto :error_setting_path
set "PATH=%PATH%;%VSINSTALLDIR%Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;%VSINSTALLDIR%Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja"
goto :end
```

**Comment by Voskrese** [comment]
`set VSCMD_ARG_NO_EXT=1`

```
if "%VSCMD_ARG_NO_EXT%"=="1" (
    if "%VSCMD_DEBUG%" GEQ "1" @echo [DEBUG:%~nx0] Skipping vsdevcmd\ext scripts since -no_ext was specified
    goto :ext_end
)
```

**Comment by LilyWangL** [comment]
Waiting for PR #12895 merged, this issue will be fixed and closed.

**Comment by Neumann-A** [comment]
temporary workaround until mentioned PR is merged:
use `vcpkg fetch ninja` before installing `lapack-reference`

**Comment by JackBoosY** [comment]
Close this issue via #12895 merged.
