### ISSUE TITLE
Could not run script to detect VS 2017 instances

### ISSUE THREAD

**Issue by ras0219-msft** [Microsoft/vcpkg#1288]
Migrated from https://github.com/Microsoft/vcpkg/issues/397#issuecomment-308581539 by @DragonOsman:

> I just tried the vcpkg.  I had to build it from source (is this normal?), and then I tried to install Wt by going to the directory vcpkg is on the Developer Command Prompt for VS2017 as an Admin and ran the command "vcpkg install Wt".  The result is:
>
> > Additional packages (*) will be installed to complete this operation.
> > Building package zlib:x86-windows...
> > 
> > Download cmake
> > No suitable version of cmake was found (requires 3.8.0 or higher). Download portable version?
> > [Y] Yes  [N] No  [A] Always Allow Downloads  [?] Help (default is "Y"): A
> > Could not run script to detect VS 2017 instances
> > 
> > C:\vcpkg\toolsrc\Release>vcpkg install Wt
> > The following packages will be built and installed:
> >   * boost:x86-windows
> >   * bzip2:x86-windows
> >   * cairo:x86-windows
> >   * expat:x86-windows
> >   * fontconfig:x86-windows
> >   * freetype:x86-windows
> >   * gettext:x86-windows
> >   * glib:x86-windows
> >   * harfbuzz:x86-windows
> >   * libffi:x86-windows
> >   * libiconv:x86-windows
> >   * libpng:x86-windows
> >   * libpq:x86-windows
> >   * openssl:x86-windows
> >   * pango:x86-windows
> >   * pcre:x86-windows
> >   * pixman:x86-windows
> >   * sqlite3:x86-windows
> >     wt:x86-windows
> >   * zlib:x86-windows
> > Additional packages (*) will be installed to complete this operation.
> > Building package zlib:x86-windows...
> > Could not run script to detect VS 2017 instances
> 
> So yeah, basically, it failed.  Could someone please help?  Why can't it detect VS 2017 instances?

Yes, it's 100% intended to build vcpkg on your local machine! 

The error messages you received ("Could not run script...")[1] are caused by a failure while running:
```
>powershell -NoProfile -ExecutionPolicy Bypass -Command "& {& 'C:\vcpkg\scripts\findVisualStudioInstallationInstances.ps1' }" 2>&1
```

Could you try running that command in verbose mode (listed below) and post the results?
```
>powershell -NoProfile -ExecutionPolicy Bypass -Command "& {& 'C:\vcpkg\scripts\findVisualStudioInstallationInstances.ps1' -verbose }"
```

On my machine, for example, I get:
```
VERBOSE: Examining D:\src\vcpkg\scripts for .vcpkg-root
VERBOSE: Examining D:\src\vcpkg for .vcpkg-root - Found
VERBOSE: Fetching dependency: nuget
VERBOSE: Examining D:\src\vcpkg\scripts for .vcpkg-root
VERBOSE: Examining D:\src\vcpkg for .vcpkg-root - Found
VERBOSE: Fetching dependency: nuget. Done.
VERBOSE: Fetching Microsoft.VisualStudio.Setup.Configuration.Native@1.8.24 from NuGet.
VERBOSE: Fetching Microsoft.VisualStudio.Setup.Configuration.Native@1.8.24 from NuGet. Done.
C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise
```

It's possible that NuGet failed to download Microsoft.VisualStudio.Setup.Configuration.Native due to a proxy issue.

[1]https://github.com/Microsoft/vcpkg/blob/687440f9760f3b9492de9a3105cdd6b99f9a3634/toolsrc/src/VcpkgPaths.cpp#L255

**Comment by DragonOsman** [comment]
I tried to run the verbose command (not with Wt this time, but with the CppRestSDK - I'll try it with Wt later if this works.  Anyway, here's the result:
> PS C:\vcpkg\toolsrc\Release> powershell -NoProfile -ExecutionPolicy Bypass -Command "& {& 'C:\vcpkg\scripts\findVisualSt
> udioInstallationInstances.ps1' -verbose }"
> >>
> VERBOSE: Examining C:\vcpkg\scripts for .vcpkg-root
> VERBOSE: Examining C:\vcpkg for .vcpkg-root - Found
> VERBOSE: Fetching dependency: nuget
> VERBOSE: Examining C:\vcpkg\scripts for .vcpkg-root
> VERBOSE: Examining C:\vcpkg for .vcpkg-root - Found
> VERBOSE: Fetching dependency: nuget. Done.
> VERBOSE: Fetching Microsoft.VisualStudio.Setup.Configuration.Native@1.8.24 from NuGet.
> VERBOSE: Fetching Microsoft.VisualStudio.Setup.Configuration.Native@1.8.24 from NuGet. Done.
> Feeds used:   https://api.nuget.org/v3/index.json  Package "Microsoft.VisualStudio.Setup.Configuration.Native.1.8.24"
> is already installed.
> At C:\vcpkg\scripts\findVisualStudioInstallationInstances.ps1:23 char:5
> +     throw $nugetOutput
> +     ~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : OperationStopped: (System.Object[]:Object[]) [], RuntimeException
>     + FullyQualifiedErrorId : Feeds used:   https://api.nuget.org/v3/index.json  Package "Microsoft.VisualStudio.Setup
>    .Configuration.Native.1.8.24" is already installed.

**Comment by JackBoosY** [comment]
Currently, it works fine in my machine.

**Comment by JackBoosY** [comment]
Please open a new issue if this is still a problem for you.
Thx.
