### ISSUE TITLE
boost-regex:x64-windows build failure

### ISSUE THREAD

**Issue by cgolchert** [microsoft/vcpkg#12882]
**Host Environment**
Win10
VS2015 u3

**To Reproduce**
cause from -> `./vcpkg install boost-uuid`

**Failure logs** 

Error: Building package boost-regex:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-regex:x64-windows
  Vcpkg version: 2020.06.15-nohash

[build-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/5066386/build-x64-windows-rel-out.log)

**Comment by PhoebeHui** [comment]
@cgolchert, from your log, it looks fail with ''mt' is not recognized as an internal or external command,
operable program or batch file.' do you install windows sdk?

For me, open vs2015 x64 Native tools command:
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC>where mt
C:\Program Files (x86)\Windows Kits\10\bin\x64\mt.exe
C:\Program Files (x86)\Windows Kits\10\bin\x86\mt.exe

It built successfully for with vs2015 update3:

Starting package 29/29: boost-regex:x86-windows
Building package boost-regex[core]:x86-windows...
-- Downloading https://github.com/boostorg/regex/archive/boost-1.73.0.tar.gz...
-- Extracting source E:/vcpkg/vcpkg/downloads/boostorg-regex-boost-1.73.0.tar.gz
-- Using source at E:/vcpkg/vcpkg/buildtrees/boost-regex/src/ost-1.73.0-a7219fe4ec.clean
-- Including E:/VCPKG/vcpkg/ports/boost-regex/b2-options.cmake
-- Building x86-windows-rel
-- Building x86-windows-rel done
-- Building x86-windows-dbg
-- Building x86-windows-dbg done
-- Packaging x86-windows-rel
-- Packaging x86-windows-rel done
-- Packaging x86-windows-dbg
-- Packaging x86-windows-dbg done
-- Packaging headers
-- Packaging headers done
-- Using cached E:/vcpkg/vcpkg/downloads/boost_LICENSE_1_0.txt
-- Installing: E:/vcpkg/vcpkg/packages/boost-regex_x86-windows/share/boost-regex/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package boost-regex[core]:x86-windows... done
Installing package boost-regex[core]:x86-windows...
Installing package boost-regex[core]:x86-windows... done
Elapsed time for package boost-regex:x86-windows: 45.74 s

Total elapsed time: 4.053 min

**Comment by cgolchert** [comment]
Yes, Installed the latest win 10 sdk.

I've uninstalled 2015 and JUST installed 2017 since that one....

performed a git pull and a bootstrasp-vcpkg.bat

The original 

> ./vcpkg install boost-uuid

Now dies at....

Error: Building package bzip2:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: bzip2:x64-windows
  Vcpkg version: 2020.06.15-nohash


for your mt request:
C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64\mt.exe

[mtx64.txt](https://github.com/microsoft/vcpkg/files/5072485/mtx64.txt)
[mtx86.txt](https://github.com/microsoft/vcpkg/files/5072486/mtx86.txt)


Doesn't seem to be a regex issue anymore, what do you suggest?

**Comment by PhoebeHui** [comment]
@cgolchert, could you attach the failure log for bzip2, do you build the port release only?

**Comment by cgolchert** [comment]
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/5072591/config-x64-windows-out.log)

It is an issue of the process not finding 'gdi32.lib'..
![gdi](https://user-images.githubusercontent.com/5304167/90212597-62882800-ddb9-11ea-8ca8-161002c137ef.gif)


I just opened a ticket for that.  https://github.com/microsoft/vcpkg/issues/12900

.. can probably close this one.

**Comment by cgolchert** [comment]
Fixed the issue it was a win10 sdk problem from the VS team.
