### ISSUE TITLE
Building package faild

### ISSUE THREAD

**Issue by aden4kost** [microsoft/vcpkg#12891]
Building package gdal:x64-windows faild with: BUILD_FAILD
<img width="819" alt="BUILD_FAILD" src="https://user-images.githubusercontent.com/14982078/90134320-a8250080-dd79-11ea-96b9-5ccd1177790c.png">

**Comment by NancyLi1013** [comment]
Hi @aden4kost 
Thanks for posting this issue.

This might be related with your network proxy.

Could you please check if you have access to http://download.osgeo.org/gdal/2.4.1/gdal241.zip?

If yes, please try to download http://download.osgeo.org/gdal/2.4.1/gdal241.zip manually and then put this archive to `vcpkg_root/downloads` directory. 

After doing these steps, rebuild this port.

**Comment by NancyLi1013** [comment]
I'm closing this issue for now since there seems no response.

Please feel free to reopen this if you still have the same problem.

**Comment by Fondu** [comment]
Hi @NancyLi1013 ! I ran into this error using vcpkg : 
![image](https://user-images.githubusercontent.com/28579475/233385576-174d02b8-eb5b-4938-b27e-3726802e9863.png)

Seems like there are 404 errors on mirror site for libtool. (Can't be my proxy, I have none)

**Comment by dg0yt** [comment]
@Fondu You need the updated scripts from vcpkg. If you don't want to use the last version of gdal, you must use manifest mode or provide the old gdal version as an overlay port.
Please do not add more comments to this old issue which is unrelated to your current problem.
