### ISSUE TITLE
nmake install returns U1077  'if' : return code '0x1'

### ISSUE THREAD

**Issue by vlj** [Microsoft/vcpkg#129]
I'm trying to package harfbuzz ; harfbuzz provides an nmake build for msvc : https://github.com/behdad/harfbuzz/tree/master/win32

I'm using "nmake /f Makefile.vc CFG=release DIRECTWRITE=1" to build the Library and it works however I'm having trouble getting the install target to work. I'd like to avoid copying headers and binaries in the port file so I'm using this snippet :
"vcpkg_execute_required_process(
    COMMAND ${NMAKE} -f Makefile.vc PREFIX=${CURRENT_PACKAGES_DIR} install
    WORKING_DIRECTORY ${SOURCE_PATH}/win32/
)"

Unfortunatly it doesn't work it fails with this error :
"NMAKE : fatal error U1077: 'if' : return code '0x1'
Stop."

I'm not sure why, some internet search told me that I need to run vcvarsall.bat script before running nmake but this is relevant when running nmake from console.

**Comment by ras0219-msft** [comment]
Could you paste the portfile here or push it to a branch? We do already run `vcvarsall.bat` before invoking the portfile, so I don't think that's the issue.

**Comment by vlj** [comment]
branch is here : https://github.com/vlj/vcpkg

portfile is here https://github.com/vlj/vcpkg/blob/master/ports/harfbuzz/portfile.cmake

**Comment by ras0219-msft** [comment]
Ok, I managed to find a fix! tl;dr `nmake.exe` and `cmd.exe` _really_ do not like forward slashes -- they think they're arguments. The `CURRENT_PACKAGES_DIR` variable is using generic cmake paths with forward slashes and needs to be converted to native paths via `file(TO_NATIVE_PATH...)`

```
file(TO_NATIVE_PATH "${CURRENT_PACKAGES_DIR}" NATIVE_PACKAGES_DIR)

vcpkg_execute_required_process(
    COMMAND ${NMAKE} -f Makefile.vc CFG=release "PREFIX=${NATIVE_PACKAGES_DIR}" install
    WORKING_DIRECTORY ${SOURCE_PATH}/win32/
    LOGNAME make-${TARGET_TRIPLET}-release-install
)
```

Also, please add a `LOGNAME` parameter to each of the `vcpkg_execute_required_process` calls; I'll add a check in master to ensure this isn't forgotten.

**Comment by vlj** [comment]
It works thanks ! I submitted it as #132 

By the way how are build dependencies handled ? "vcpkg.exe install harfbuzz" fails if I don't build ragel before, and vcpkg doesn't attempt to build ragel automatically despite control file having "build-depends: ragel".

**Comment by ras0219-msft** [comment]
I suspect we're doing a case-sensitive comparison. If you use `Build-Depends`, that should resolve the issue.

I'll look into adding detection logic here and give you a better error message in the future.

**Comment by sachinpatil2488** [comment]
> Ok, I managed to find a fix! tl;dr `nmake.exe` and `cmd.exe` _really_ do not like forward slashes -- they think they're arguments. The `CURRENT_PACKAGES_DIR` variable is using generic cmake paths with forward slashes and needs to be converted to native paths via `file(TO_NATIVE_PATH...)`
> 
> ```
> file(TO_NATIVE_PATH "${CURRENT_PACKAGES_DIR}" NATIVE_PACKAGES_DIR)
> 

Thanks  @ras0219-msft, I was also facing same kind issue. Fix worked for me
