### ISSUE TITLE
[ffmpeg[ffmpeg,x264]:x64-windows] build failure with latest vcpkg pull

### ISSUE THREAD

**Issue by samofoz** [microsoft/vcpkg#12904]
**Host Environment**
- OS: Windows
- Compiler: revision

**To Reproduce**
vcpkg install ffmpeg[ffmpeg,x264]:x64-windows

C:\vcpackage\vcpkg>vcpkg install ffmpeg[ffmpeg,x264]:x64-windows
Computing installation plan...
The following packages will be built and installed:
ffmpeg[avresample,core,ffmpeg,gpl,x264]:x64-windows

x264[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Starting package 1/2: x264:x64-windows
Building package x264[core]:x64-windows...
Using cached binary package: C:\Users\samof\AppData\Local\vcpkg\archives\80\803584d5f475e64bf2f465dfb329357606bc8ea4.zip
Building package x264[core]:x64-windows... done
Installing package x264[core]:x64-windows...
Installing package x264[core]:x64-windows... done
Elapsed time for package x264:x64-windows: 203.3 ms
Starting package 2/2: ffmpeg:x64-windows
Building package ffmpeg[avresample,core,ffmpeg,gpl,x264]:x64-windows...
Could not locate cached archive: C:\Users\samof\AppData\Local\vcpkg\archives\20\20a085d14f8e51af705bee60ebb9a68ee99fe9ad.zip
-- Using cached C:/vcpackage/vcpkg/downloads/ffmpeg-ffmpeg-n4.2.tar.gz
-- Cleaning sources at C:/vcpackage/vcpkg/buildtrees/ffmpeg/src/n4.2-a4d149a5c6.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpackage/vcpkg/downloads/ffmpeg-ffmpeg-n4.2.tar.gz
-- Applying patch 0001-create-lib-libraries.patch
-- Applying patch 0003-fix-windowsinclude.patch
-- Applying patch 0004-fix-debug-build.patch
-- Applying patch 0005-fix-libvpx-linking.patch
-- Applying patch 0006-fix-StaticFeatures.patch
-- Using source at C:/vcpackage/vcpkg/buildtrees/ffmpeg/src/n4.2-a4d149a5c6.clean
-- Acquiring MSYS Packages...
-- Acquiring MSYS Packages... OK
-- Building Options: --enable-asm --enable-yasm --disable-doc --enable-debug --enable-runtime-cpudetect --enable-gpl --disable-openssl --enable-ffmpeg --disable-ffplay --disable-ffprobe --disable-libvpx --enable-libx264 --disable-opencl --disable-lzma --disable-bzlib --enable-avresample --disable-cuda --disable-nvenc --disable-cuvid --disable-libnpp --disable-avisynth --disable-static --enable-shared --extra-cflags=-DHAVE_UNISTD_H=0
-- Building Release Options: --extra-cflags=-MD --extra-cxxflags=-MD
-- Building ffmpeg for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
Command failed: C:/vcpackage/vcpkg/downloads/tools/msys2/msys64/usr/bin/bash.exe --noprofile --norc C:/vcpackage/vcpkg/ports/ffmpeg\build.sh C:/vcpackage/vcpkg/buildtrees/ffmpeg/x64-windows-rel C:/vcpackage/vcpkg/buildtrees/ffmpeg/src/n4.2-a4d149a5c6.clean C:/vcpackage/vcpkg/packages/ffmpeg_x64-windows "--enable-asm --enable-yasm --disable-doc --enable-debug --enable-runtime-cpudetect --enable-gpl --disable-openssl --enable-ffmpeg --disable-ffplay --disable-ffprobe --disable-libvpx --enable-libx264 --disable-opencl --disable-lzma --disable-bzlib --enable-avresample --disable-cuda --disable-nvenc --disable-cuvid --disable-libnpp --disable-avisynth --disable-static --enable-shared --extra-cflags=-DHAVE_UNISTD_H=0 --extra-cflags=-MD --extra-cxxflags=-MD"
Working Directory: C:/vcpackage/vcpkg/buildtrees/ffmpeg/x64-windows-rel
**Error code: 1 (libx264 not found)**
See logs for more information:
C:\vcpackage\vcpkg\buildtrees\ffmpeg\build-x64-windows-rel-out.log
Call Stack (most recent call first):
ports/ffmpeg/portfile.cmake:210 (vcpkg_execute_required_process)
scripts/ports.cmake:79 (include)

Error: Building package ffmpeg:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with .\vcpkg update, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
Package: ffmpeg:x64-windows
Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/12896
