### ISSUE TITLE
boost-fusion:x64-windows build failure

### ISSUE THREAD

**Issue by DaXdata** [microsoft/vcpkg#12901]
**Host Environment**
- OS: Windows 10 [Version 10.0.17134.1610]
- Compiler: cmake 3.16.0, vcpkg 2020.06.15

**To Reproduce**
`./vcpkg install boost-fusion:x64-windows`

**Failure logs** 
PS D:\vcpkg> .\vcpkg install boost-fusion:x64-windows
Computing installation plan...
The following packages will be built and installed:
    boost-fusion[core]:x64-windows
Detecting compiler hash for triplet x64-windows...
Starting package 1/1: boost-fusion:x64-windows
Building package boost-fusion[core]:x64-windows...
Could not locate cached archive: C:\Users\Scruffy\AppData\Local\vcpkg\archives\05\05f5474f817787a2460ca703273cd81cfd0c0f31.zip
-- Using cached D:/vcpkg/downloads/boostorg-fusion-boost-1.73.0.tar.gz
-- Extracting source D:/vcpkg/downloads/boostorg-fusion-boost-1.73.0.tar.gz
CMake Error at scripts/cmake/vcpkg_extract_source_archive_ex.cmake:147 (file):
  file RENAME failed to rename

    D:/vcpkg/buildtrees/boost-fusion/src/ost-1.73.0-6ebc99e549.tmp/fusion-boost-1.73.0

  to

    D:/vcpkg/buildtrees/boost-fusion/src/ost-1.73.0-6ebc99e549.clean

  because: No such file or directory

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:139 (vcpkg_extract_source_archive_ex)
  ports/boost-fusion/portfile.cmake:3 (vcpkg_from_github)
  scripts/ports.cmake:79 (include)

Error: Building package boost-fusion:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-fusion:x64-windows
  Vcpkg version: 2020.06.15-nohash

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/8199
