### ISSUE TITLE
[New Port Request] QGIS

### ISSUE THREAD

**Issue by HPDell** [microsoft/vcpkg#12913]
Library name: QGIS

Library description: QGIS is a free, open source, cross platform (lin/win/mac) geographical information system (GIS)

Source repository URL: https://github.com/qgis/QGIS

Project homepage (if different from the source repository): http://qgis.org/

Anything else that is useful to know when adding (such as optional features the library may have that should be included): 
Nothing

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, and continue PR #7800.
