### ISSUE TITLE
Error: Building package protobuf:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by llduncangithub** [microsoft/vcpkg#12912]
**Host Environment**
- OS: Microsoft Windows [Version 10.0.18363.997]
- Compiler: Microsoft Visual Studio Enterprise 2019 Version 16.7.1 english version

**To Reproduce**
`./vcpkg install protobuf[core]:x64-windows`

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

D:\src\vcpkg>vcpkg install protobuf[core]:x64-windows
Computing installation plan...
The following packages will be built and installed:
    protobuf[core]:x64-windows
Detecting compiler hash for triplet x64-windows...
Starting package 1/1: protobuf:x64-windows
Building package protobuf[core]:x64-windows...
Could not locate cached archive: C:\Users\lldun\AppData\Local\vcpkg\archives\fd\fd31736a3f0862bb51a8d2e917adff3baedaa798.zip
-- Using cached D:/src/vcpkg/downloads/protocolbuffers-protobuf-31ebe2ac71400344a5db91ffc13c4ddfb7589f92.tar.gz
-- Extracting source D:/src/vcpkg/downloads/protocolbuffers-protobuf-31ebe2ac71400344a5db91ffc13c4ddfb7589f92.tar.gz
-- Applying patch fix-uwp.patch
-- Applying patch fix-android-log.patch
-- Applying patch fix-static-build.patch
-- Using source at D:/src/vcpkg/buildtrees/protobuf/src/dfb7589f92-61fbc4fa5f.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: D:/src/vcpkg/downloads/tools/powershell-core-6.2.1-windows/powershell.exe -noprofile -executionpolicy Bypass -nologo -file D:/src/vcpkg/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary D:/src/vcpkg/packages/protobuf_x64-windows/tools/protobuf/protoc.exe -installedDir D:/src/vcpkg/packages/protobuf_x64-windows/bin
    Working Directory: D:/src/vcpkg
    Error code: -2146232797
    See logs for more information:
      D:\src\vcpkg\buildtrees\protobuf\copy-tool-dependencies-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_copy_tool_dependencies.cmake:27 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_copy_tool_dependencies.cmake:37 (search_for_dependencies)
  scripts/cmake/vcpkg_copy_tools.cmake:55 (vcpkg_copy_tool_dependencies)
  ports/protobuf/portfile.cmake:93 (vcpkg_copy_tools)
  scripts/ports.cmake:79 (include)

Error: Building package protobuf:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: protobuf:x64-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by llduncangithub** [comment]
OS: Microsoft Windows [Version 10.0.18363.997]
Compiler: Microsoft Visual Studio Enterprise 2019 Version 16.7.1 english version
[copy-tool-dependencies-err.log](https://github.com/microsoft/vcpkg/files/5077978/copy-tool-dependencies-err.log)

PS D:\src\vcpkg> .\vcpkg.exe install protobuf[core]:x64-windows
Computing installation plan...
The following packages will be built and installed:
    protobuf[core]:x64-windows
Detecting compiler hash for triplet x64-windows...
Starting package 1/1: protobuf:x64-windows
Building package protobuf[core]:x64-windows...
Could not locate cached archive: C:\Users\lldun\AppData\Local\vcpkg\archives\fd\fd31736a3f0862bb51a8d2e917adff3baedaa798.zip
-- Using cached D:/src/vcpkg/downloads/protocolbuffers-protobuf-31ebe2ac71400344a5db91ffc13c4ddfb7589f92.tar.gz
-- Extracting source D:/src/vcpkg/downloads/protocolbuffers-protobuf-31ebe2ac71400344a5db91ffc13c4ddfb7589f92.tar.gz
-- Applying patch fix-uwp.patch
-- Applying patch fix-android-log.patch
-- Applying patch fix-static-build.patch
-- Using source at D:/src/vcpkg/buildtrees/protobuf/src/dfb7589f92-61fbc4fa5f.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: D:/src/vcpkg/downloads/tools/powershell-core-6.2.1-windows/powershell.exe -noprofile -executionpolicy Bypass -nologo -file D:/src/vcpkg/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary D:/src/vcpkg/packages/protobuf_x64-windows/tools/protobuf/protoc.exe -installedDir D:/src/vcpkg/packages/protobuf_x64-windows/bin
    Working Directory: D:/src/vcpkg
    Error code: -2146232797
    See logs for more information:
      D:\src\vcpkg\buildtrees\protobuf\copy-tool-dependencies-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_copy_tool_dependencies.cmake:27 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_copy_tool_dependencies.cmake:37 (search_for_dependencies)
  scripts/cmake/vcpkg_copy_tools.cmake:55 (vcpkg_copy_tool_dependencies)
  ports/protobuf/portfile.cmake:93 (vcpkg_copy_tools)
  scripts/ports.cmake:79 (include)


Error: Building package protobuf:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: protobuf:x64-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by sfhacker** [comment]
There seems to be a lot of recurrent issues with protobuf & vcpkg.
We just downloaded protobuf master branch and built it from source. No issues at all.

![image](https://user-images.githubusercontent.com/25817529/90311481-980a4e00-df3e-11ea-81e6-f5af1c9efe22.png)

@llduncangithub Let us know if we can be of any assistance.

**Comment by llduncangithub** [comment]
delete vcpkg\buildtrees\protobuf ,and run install opencv:x64-windows，it's ok；
