### ISSUE TITLE
[New Port Request] <OpenXLSX>

### ISSUE THREAD

**Issue by UnknownObject000** [microsoft/vcpkg#12914]
Library name: OpenXLSX

Library description:  OpenXLSX is a C++ library for reading, writing, creating and modifying Microsoft Excel® files, with the .xlsx format.

Source repository URL:  https://github.com/troldal/OpenXLSX

Project homepage (if different from the source repository):  https://github.com/troldal/OpenXLSX

Anything else that is useful to know when adding (such as optional features the library may have that should be included): Nothing

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
