### ISSUE TITLE
[New Port Request] minizip, maintained fork

### ISSUE THREAD

**Issue by ulfllorenz** [microsoft/vcpkg#12917]
Library name: minizip fork (?)

Library description: This is a fork of the minizip library that adds a slew of other features and is reasonably maintained, both in contrast to the original minizip that seems to be stable enough to just hang there. 

Source repository URL: https://github.com/nmoinvaz/minizip.git

Project homepage (if different from the source repository): https://github.com/nmoinvaz/minizip/

Anything else that is useful to know when adding (such as optional features the library may have that should be included): The library has quite a few optional features, serving as frontend to various other compression algorithms (bzip2, zstd, libz) and cryptography libraries (ssl etc.); it seems reasonable that you would not always want to have all features, which may make this port a bit tricky.

**Comment by NancyLi1013** [comment]
Hi @ulfllorenz 

Thanks for posting this request. We have a port named minzip in vcpkg now.

Could you please help confirm if this can meet your demands?
https://github.com/microsoft/vcpkg/tree/master/ports/minizip

Thanks.

**Comment by ulfllorenz** [comment]
Well, not quite. The minizip port in vcpkg is the original one from the zlib developers, which lacks quite a few features; as far as I can discern, it only allows interfacing with bzip2.

**Comment by oswjk** [comment]
I have made a simple port for nmoinvaz/minizip privately because some package depends on the old minizip and some other depends on the fork. I named the port creatively to minizipfork because it doesn't really matter to us as the port is currently a private one :-)

I can share the private port if anyone wants to work with this, there's nothing secret in that. Probably the hardest part is to decide what to do with the name. Especially if one needs to have both installed at the same time.

**Comment by ulfllorenz** [comment]
I think if we can get the private port that would be at least a useful starting point that saves the odd hour of work.

**Comment by oswjk** [comment]
Can be found from here https://github.com/oswjk/vcpkg-minizip-fork

**Comment by ulfllorenz** [comment]
It will probably take some time (days, single weeks) until we do this specific item, but thanks in any case.

**Comment by makitsune** [comment]
@oswjk Thank you so much. I hope it get's pushed to vcpkg soon

**Comment by Chronial** [comment]
@NancyLi1013 I am interested in creating a PR for this. Do you have any guidance on what the name of that port should be?

**Comment by BillyONeal** [comment]
Put my vote in for "nmoinvaz-minizip"

**Comment by NancyLi1013** [comment]
@Chronial 
I think you can make a PR for this now. For the port name, please use "nmoinvaz-minizip" proposed by @BillyONeal . Thanks for your contribution.

**Comment by Chronial** [comment]
While looking at some more inspiration for the port implementation, I noticed that the name `minizip2` seems to have established itself in other repositories ([MinGW](https://github.com/msys2/MINGW-packages/tree/0269ce94e07422bcb4734214a6df6e62a9b24765/mingw-w64-minizip2), [MacPorts](https://ports.macports.org/port/minizip2/summary), [Homebrew](https://github.com/Homebrew/homebrew-core/commit/dd07f5aa3a056c21a6af3c9279ad06895f93cbfb)). This also seems to be supported by the maintainer, who added [support for suffixes for distribution](https://github.com/nmoinvaz/minizip/commit/b671db3f583363300b182ad8af1acf231089e763).

So unless you are committed to `nmoinvaz-minizip`, I would go with `minizip2` for the sake of consistency.

**Comment by PhoebeHui** [comment]
@Chronial, thanks for the information!

I think it's fine to name it minizip2, even it may confuse with user, since we already have minizip port with different repo, 
However, we may want it to be in consistency with other repositories (MinGW, MacPorts, Homebrew).

@BillyONeal, what do you think?
