### ISSUE TITLE
show-stopper: vcpkg screwing up cmake by removing semicolons

### ISSUE THREAD

**Issue by jgehw** [microsoft/vcpkg#12922]
`execute_process(COMMAND "C:/msys2/msys64/usr/bin/echo.exe" "hello; world; line 3" OUTPUT_VARIABLE MY_OUT)`
`message(STATUS "result ${MY_OUT}")`
should result in:
`"-- result hello; world; line 3"` (which is does when just running it in a minimalistic cmake project not using vcpkg)
but actually results in:
`"-- result hello  world  line 3"`
when this code is placed in a vcpkg cmake port file. No matter what the intention behind this behaviour is, this sooner or later becomes a show-stopper, for example, when trying to find python using
`find_package(Python3)`
or using the old cmake API
`find_package(PythonInterp)`
because cmake internally tries to run
`python -c "import sys; sys.stdout.write('.'.join([str(x) for x in sys.version_info[:2]]))"`
to find the correct version, which fails because python stops on a syntax error after "import sys" because of the erased semicolon.

This occurres at least on Windows 10 (where I found it).

**Comment by jgehw** [comment]
This, BTW, is also the long-story-short root-cause behind #4320. I opened a new issue, because this is a bug, while #4320 is tracked as a feature.

**Comment by jgehw** [comment]
PS: I'm aware there is python available via `vcpkg_find_acquire_program(PYTHON3)` (why? maybe because others already stumbled across the broken `find_package(Python3)` cmake API?), but this is not only a dirty and partial (e.g. only working on linux with apt available, not other package managers such as yum) solution, but also insufficient because on Windows it installs embedded python, which is a limited distribution, where it's not possible to install further packages using pip, e.g. when numpy is required (which, BTW, could also be located using the `find_package(Python3)` cmake API).

**Comment by Neumann-A** [comment]
`vcpkg_find_acquire_program(PYTHON3)` is for portfile usage not `cmakelists.txt`. 
So the question here is do you soeak from usage within a portfile or usage within a project/cmakelists.txt?

**Comment by jgehw** [comment]
> `vcpkg_find_acquire_program(PYTHON3)` is for portfile usage not `cmakelists.txt`.
> So the question here is do you soeak from usage within a portfile or usage within a project/cmakelists.txt?

Yes, I speak from usage within a portfile. (Precisely, I'm currently improving the tensorflow-cc port, and while doing so, upgrading to recent v2.3, and, unfortunately, Google requires python with numpy being present to build tensorflow now.)

**Comment by Neumann-A** [comment]
`find_package` does not work for obvious reasons in cmake script mode.....

about 

`execute_process(COMMAND "C:/msys2/msys64/usr/bin/echo.exe" "hello; world; line 3" OUTPUT_VARIABLE MY_OUT)`

just needs escaping of the `;` for now. or try using `_execute_process` instead

**Comment by jgehw** [comment]
It took me half a day, but I finally found and fixed the root cause. The problem was the macro overriding cmake's execute_process(). It fixed it via PR #12926.

**Comment by Neumann-A** [comment]
even if that PR is merged `find_package(Python3)` is not going to work in portfiles since the module defines targets which is not allowed in script mode. (I know since I tried it.)

**Comment by jgehw** [comment]
> even if that PR is merged `find_package(Python3)` is not going to work in portfiles since the module defines targets which is not allowed in script mode. (I know since I tried it.)

I don't know what I'm doing differently, but in my case it's working in the portfile (current dev snapshot at https://github.com/jgehw/vcpkg/tree/fix-static-builds-and-more, tested for x64-windows)

**Comment by JackBoosY** [comment]
@strega-nil What do you think about?
