### ISSUE TITLE
[fluidsynth x86 / x64] build failure

### ISSUE THREAD

**Issue by Christsnatcher** [microsoft/vcpkg#12934]
**Host Environment**
- Windows 8.1 x64
- MSVC++ 14.25 Visual Studio 2019

**To Reproduce**
vcpkg install fluidsynth:x86-windows
or
vcpkg install fluidsynth:x64-windows

**Failure logs** 
```
D:\Code\Repos\vcpkg>vcpkg install fluidsynth:x86-windows
Computing installation plan...
The following packages will be built and installed:
    fluidsynth[core]:x86-windows
Detecting compiler hash for triplet x86-windows...
Starting package 1/1: fluidsynth:x86-windows
Building package fluidsynth[core]:x86-windows...
Could not locate cached archive: C:\Users\Daniel\AppData\Local\vcpkg\archives\5e\5e86e84f5b9760afee78566b4949c31b3fe8cf76.zip
-- Downloading https://github.com/FluidSynth/fluidsynth/archive/37c9ae2bf431a764032f023b3b2c0c0b86b7c272.tar.gz...
-- Extracting source D:/Code/Repos/vcpkg/downloads/FluidSynth-fluidsynth-37c9ae2bf431a764032f023b3b2c0c0b86b7c272.tar.gz
-- Applying patch force-x86-gentables.patch
-- Using source at D:/Code/Repos/vcpkg/buildtrees/fluidsynth/src/0b86b7c272-b21350e92b.clean
-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:139 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /m
    Working Directory: D:/Code/Repos/vcpkg/buildtrees/fluidsynth/x86-windows-dbg
    See logs for more information:
      D:\Code\Repos\vcpkg\buildtrees\fluidsynth\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/fluidsynth/portfile.cmake:16 (vcpkg_install_cmake)
  scripts/ports.cmake:79 (include)

Error: Building package fluidsynth:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: fluidsynth:x86-windows
  Vcpkg version: 2020.06.15-nohash
```

**Additional context**
It's exactly the same situation I described in https://github.com/microsoft/vcpkg/issues/9628 more than 6 months already, just introduced for this port with the latest update. CMake targets the Windows 8.1 SDK for configuration and the build fails because the code is compiled against the latest Win 10 SDK. As I explained in the issue I just linked a temporary "fix" is to add

CMAKE_SYSTEM_VERSION=10.1.19041.1

to the CMake configure options in the resp. portfile, but this is NO proper / valid solution, esp. seeing that now more ports starting to have the same issue. I would actually consider this a tool problem instead of a "port bug". Please check the attached .zip for all files created during the "installation" (x86), thank you.

[fluidsynth.zip](https://github.com/microsoft/vcpkg/files/5080607/fluidsynth.zip)

**Comment by NancyLi1013** [comment]
Closing this issue since it has been solved.
Please see comments here https://github.com/microsoft/vcpkg/issues/12935#issuecomment-674798858.
