### ISSUE TITLE
[libssh2] provide different crypto backends

### ISSUE THREAD

**Issue by linquize** [microsoft/vcpkg#12939]
`libssh2` should provide different crypto backends, similar to existing `libssh` port.

- openssl (default backend)
- wincng (Windows only)
- mbedtls

also make `zlib` feature optional

**Comment by NancyLi1013** [comment]
Hi @linquize 
Thanks for posting this issue.
I checked `libssh2` source codes and found that there are no any options for `openssl `,`wincng `,`mbedtls`, which is not different from `libssh`.

So it seems to be impossible to add these backends as features for `libssh2`.

Only `zlib `can be set as feature optional.

**Comment by linquize** [comment]
There are options in libssh2 `src/CMakeLists.txt`, using `CRYPTO_BACKEND` variable.
```cmake
set(CRYPTO_BACKEND OpenSSL)
set(CRYPTO_BACKEND mbedTLS)
set(CRYPTO_BACKEND WinCNG)
```

**Comment by NancyLi1013** [comment]
Thanks for your information. I will try to add these features later.

**Comment by Thomas1664** [comment]
Hi @linquize,
I made `zlib` an opt-out feature. But it is impossible to add other crypto backends as features. See the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#do-not-use-features-to-implement-alternatives):

> Do not use features to implement alternatives
> Features must be treated as additive functionality. If port[featureA] installs and port[featureB] installs, then port[featureA,featureB] must install. Moreover, if a second port depends on [featureA] and a third port depends on [featureB], installing both the second and third ports should have their dependencies satisfied.
