### ISSUE TITLE
[New Port Request] <hdf4>

### ISSUE THREAD

**Issue by Gigas002** [microsoft/vcpkg#12943]
Library name: hdf4

Source URL: https://support.hdfgroup.org/ftp/HDF/releases/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
Required for gdal's hdf4 support. HDF5 port already exists.

**Comment by PhoebeHui** [comment]
@Gigas002, we have exist port https://github.com/microsoft/vcpkg/tree/master/ports/hdf5, could you try it and see if it meet your requirements?

For hdf4, if you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by Shadow1Raven** [comment]
Hello,

the HDF5 library is not able to open HDF4 files and fails ("Not an HDF5 file"). HDF4 is not deprecated, and still used in geodata (e.g. MODIS data). Thus, adding an HDF4 port would also return vital functionality to GDAL (which depends on HDF4 to read HDF4 files). It would be nice if this port could still be added.

Kind regards.
