### ISSUE TITLE
How do I incrementally compile a port when using '--editable'. 

### ISSUE THREAD

**Issue by FishHe** [microsoft/vcpkg#12948]
I wanna change some codes in 'openmvg', and compile it many times. 
Each time, I remove the port and reinstall it with '--editable'. Is there a more convenient way to do this?

**Comment by PhoebeHui** [comment]
@FishHe, you don't need to remove the port. 

You only need to use '--editable' each time, it will use the source you modified.

**Comment by PhoebeHui** [comment]
@FishHe, please reopen this issue if it's not answer you want.

**Comment by FishHe** [comment]
However, using '--editable' each time does not work for me. Vcpkg can't detect my changes on the source code.

**Comment by PhoebeHui** [comment]
That's strange, I double confirm again, it works for me, I installed the port with --editable before, uninstall the port, modify some changes in buildtree, reinstall it with --editable again, the changes still be there.

You can  see it use the source cached before.
PS F:\vcpkg\clean> ./vcpkg install openmvg:x64-windows --editable
Computing installation plan...
The following packages will be built and installed:
    openmvg[core]:x64-windows
Detecting compiler hash for triplet x64-windows...
Starting package 1/1: openmvg:x64-windows
Building package openmvg[core]:x64-windows...
-- Note: openmvg only supports static library linkage. Building static library.
-- Using cached F:/vcpkg/clean/downloads/openMVG-openMVG-606d1c9e82123dd50de282128151a50bf42262fc.tar.gz
-- Using source at F:/vcpkg/clean/buildtrees/openmvg/src/0bf42262fc-5796248b75
-- Configuring x64-windows

**Comment by FishHe** [comment]
It is true that making complete recompilation is working with '--editable'. However, recomputing the whole port is time consuming. To **incrementally** compile a port is what I really want.

**Comment by PhoebeHui** [comment]
@FishHe, you don't need to wait it start to build, end up the thread when it finished extracting source, it should be very quick, also you does't need to uninstall the port again, sorry for the confuse.
