### ISSUE TITLE
[libhdfs3] update to 3.3.0

### ISSUE THREAD

**Issue by Gigas002** [microsoft/vcpkg#12941]
Library name: libhdfs3

New version number: 3.3.0

Other information that may be useful (release notes, etc...):
vcpkg says the latest version is "2019-11-05", I suppose it's outdated, since the website says the latest version was released on 14.07.2020 (source code available here: https://hadoop.apache.org/releases.html)

**Comment by JonLiu1993** [comment]
Hi @Gigas002 ，
We currently only upgrade the version on the official github website. I will upgrade as soon as possible after github releases version 3.3.0. Thank you for your issue.

**Comment by JonLiu1993** [comment]
@Gigas002 ,Thanks for your issue,I did not find the latest version of libhdfs3 on the link you sent. The official github has stopped updating the latest version, so I will close this issue. If there is the latest official version, you can reopen this issue.
