### ISSUE TITLE
[nlohmann-json] build failure

### ISSUE THREAD

**Issue by rsweeten** [microsoft/vcpkg#12959]
**Host Environment**
- OS: Windows
- Compiler: VIsual Studio Build Tools 16.7.1
- vcpkg version: 2020.02 (master branch) and 2020.06 release tag, 

**To Reproduce**
- cloned vcpkg 
- ran bootstrap-vcpkg.bat in powershell
`./vcpkg install nlohmann-json`
- re: Warning: different source is available for vcpkg, I ran bootstrap-vcpkg.bat again. and ran `vcpkg install nlohmann-json` again, but get the same error.
- I get the following error when trying to install anything (I don't get the version warning when I'm on 2020.06 tag)

**Failure logs** 
Warning: Different source is available for vcpkg (2020.2.4 -> 2020.6.15). Use .\bootstrap-vcpkg.bat to update.
Computing installation plan...
The following packages will be built and installed:
    nlohmann-json[core]:x86-windows
Starting package 1/1: nlohmann-json:x86-windows
Building package nlohmann-json[core]:x86-windows...
CMake Error at scripts/ports.cmake:14 (message):
          Your vcpkg executable is outdated and is not compatible with the current CMake scripts.
          Please re-build vcpkg by running bootstrap-vcpkg.

**Additional context**
Just cloned vcpkg and ran bootstrap

**Comment by NancyLi1013** [comment]
Hi @rsweeten 
Thanks for posting this issue.
It seems that you didn't run .`\bootstrap-vcpkg.bat` after you updated vcpkg to the version 6.15.
Since there are some changes for vcpkg  between these two versions. Please see here
https://github.com/microsoft/vcpkg/blob/master/scripts/ports.cmake#L9-L18

You can run `\bootstrap-vcpkg.bat` first, then try to install `nlohmann-json`.

```
Warning: Different source is available for vcpkg (2020.2.4 -> 2020.6.15). Use .\bootstrap-vcpkg.bat to update.
Computing installation plan...
The following packages will be built and installed:
nlohmann-json[core]:x86-windows
Starting package 1/1: nlohmann-json:x86-windows
Building package nlohmann-json[core]:x86-windows...
CMake Error at scripts/ports.cmake:14 (message):
Your vcpkg executable is outdated and is not compatible with the current CMake scripts.
```

**Comment by rsweeten** [comment]
Hi @NancyLi1013 , I did run it again after. however when I run it again and then check the version I still get the old version:

`vcpkg> vcpkg version
Vcpkg package management program version 2020.02.04-nohash`

**Comment by NancyLi1013** [comment]
Hi @rsweeten 
Have you run `\bootstrap-vcpkg.bat` after you used `git pull ` to update vcpkg?
 
Do you meet the same error as before if you install packages?

**Comment by rsweeten** [comment]
Hi @NancyLi1013 ,
Yes, I have run bootstrap-vcpkg.bat after git-pull and get the same error

**Comment by NancyLi1013** [comment]
@rsweeten 
Sorry for the long delay.
I noticed you used GCC compiler. In this case, you should run `bootstrap-vcpkg.sh` instead of `bootstrap-vcpkg.bat`.
So could you please try to run `bootstrap-vcpkg.sh `?

**Comment by sfhacker** [comment]
Any news/update on this issue?

![image](https://user-images.githubusercontent.com/25817529/92316000-70843e00-f031-11ea-820e-6ecb2c4aa5db.png)

**Comment by NancyLi1013** [comment]
@rsweeten 

Does this issue still exist on your machine?

**Comment by NancyLi1013** [comment]
I'm closing this issue for now since no response here.

Please feel free to reopen this issue if it is still a problem for you.

Thanks.
