### ISSUE TITLE
[New Port Request] aliyun-log

### ISSUE THREAD

**Issue by tinglou** [microsoft/vcpkg#12957]
Library name: aliyun-log

Library description: SDK for Aliyun SLS 

Source repository URL: https://github.com/aliyun/aliyun-log-c-sdk

**Comment by NancyLi1013** [comment]
Hi @tinglou 
Thanks for posting this request.
 There is a PR #12682 to add this port to vcpkg. Let's just wait for the PR merged.

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
