### ISSUE TITLE
[protobuf] undefined reference to `google::protobuf::io::FileOutputStream::FileOutputStream(int, int)'

### ISSUE THREAD

**Issue by psionic12** [microsoft/vcpkg#12958]
**Describe the bug**
Even if linked with `protobuf::libprotobuf` and `protobuf::libprotoc`, build still failed due to references not found.

**Environment**
- OS: [Ubuntu 18.04]
- Compiler: Clang 6.0 Gcc 7.5.0

**To Reproduce**
CmakeList:
```
cmake_minimum_required(VERSION 3.16)
project(untitled)

set(CMAKE_CXX_STANDARD 14)

find_package(Protobuf REQUIRED)

add_executable(untitled main.cpp)
target_link_libraries(untitled
        PRIVATE
        protobuf::libprotobuf
        protobuf::libprotoc
        )

```
main.cpp:

```
#include <google/protobuf/compiler/command_line_interface.h>
#include <google/protobuf/compiler/cpp/cpp_generator.h>
using namespace google::protobuf::compiler;
int main(int argc, char **argv) {

  CommandLineInterface cli;
  cli.AllowPlugins("protoc-");

  cpp::CppGenerator cpp_generator;
  cli.RegisterGenerator("--cpp_out", "--cpp_opt", &cpp_generator,
                        "Generate C++ header and source.");
  cli.Run(argc, argv);
}
```

**Expected behavior**
Apparently, no undefined-reference-error

**Failure logs**
Lots of undefined references error, such as:
undefined reference to `google::protobuf::io::FileOutputStream::FileOutputStream(int, int)'

**Comment by psionic12** [comment]
If I build protobuf from the source using ./configure, ./make install, then it's will works, don't know why, just for you information

**Comment by linquize** [comment]
Put `protobuf::libprotoc` before `protobuf::libprotobuf`, because on linux they are static libraries by default.
The linker requires correct order of static libraries.
```cmake
target_link_libraries(untitled PRIVATE protobuf::libprotoc protobuf::libprotobuf)
```

**Comment by psionic12** [comment]
@linquize , it works, thanks a lot.
By the way, how can I know if vcpkg use static or dynamic libraries?

**Comment by linquize** [comment]
Linux default static, windows MSVC default dynamic

**Comment by linquize** [comment]
Read triplets/*.cmake
