### ISSUE TITLE
Port request: Qt 4.8.x

### ISSUE THREAD

**Issue by Voskrese** [Microsoft/vcpkg#1296]
Maybe we should make the port Qt4 for vcpkg? most of the projects are supporting qt4
You can of course use the prebuild an https://fami.codefreak.ru/mirrors/qt/unofficial_builds/ 

I have just begun to understand and won't be able to make port

some links with patches
https://github.com/appleseedhq/appleseed/wiki/Making-Qt-4.8.7-compile-with-Visual-Studio-2015
https://fami.codefreak.ru/mirrors/qt/unofficial_builds/qt4.8.7-msvc2015/* https://fami.codefreak.ru/mirrors/qt/unofficial_builds/
https://stackoverflow.com/questions/32848962/how-to-build-qt-4-8-6-with-visual-studio-2015-without-official-support
https://forum.qt.io/topic/56453/compiling-qt4-head-with-msvc-2015-cstdint-errors/12

> может стоит сделать порт Qt4 для vcpkg? большинство проектов, имеют поддержку именно qt4
> можно конечно пользоваться prebuild https://fami.codefreak.ru/mirrors/qt/unofficial_builds/ 
> 
> я только начал разбираться и не смогу самостоятельно сделать порт
> 
> несколько ссылок с патчами
> https://github.com/appleseedhq/appleseed/wiki/Making-Qt-4.8.7-compile-with-Visual-Studio-2015
> https://fami.codefreak.ru/mirrors/qt/unofficial_builds/qt4.8.7-msvc2015/ * https://fami.codefreak.ru/mirrors/qt/unofficial_builds/
> https://stackoverflow.com/questions/32848962/how-to-build-qt-4-8-6-with-visual-studio-2015-without-official-support
> https://forum.qt.io/topic/56453/compiling-qt4-head-with-msvc-2015-cstdint-errors/12

**Comment by ras0219-msft** [comment]
It sounds like the Qt company has stopped supporting Qt4 quite some time ago[1]; its official EOL was 19th December 2015, so over a year and a half.

This means no security fixes, no compatibility fixes, no bug fixes. While I'd be fine with just adding Qt4, we would be forced to pull it out of the catalog as soon as a dependency updates in a way that is incompatible; who will do the work to make it compatible with the next version of <dependency> or the compiler? Vcpkg definitely can't take on the full support burden required of owning a project as large as Qt!

This situation would definitely be different if there were an active open source fork of Qt4 that was continuing to receive updates and compatibility fixes... does such a thing exist?

[1] http://blog.qt.io/blog/2014/11/27/qt-4-8-x-support-to-be-extended-for-another-year/

**Comment by Voskrese** [comment]
@ras0219-msft  собирал проект, в заисимостях gtk-2, gdk
через vcpkg не нашел ни lib, ни include

в vcpkg вообще какая версия 2 или 3 ? судя по библиотекам версия 3?

> collecting project zaisimostjah gtk-2, gdk
> through vcpkg not found any lib, include no
> 
> in vcpkg generally what version 2 or 3? Judging from the libraries version 3?

**Comment by ras0219-msft** [comment]
The core question is:
Can I write a program that uses _both_ gtk2 and gtk3?

If the answer is yes, then they should both be present as two different packages (`gtk2` and `gtk3`). If the answer is no, then we prefer the latest stable and supported (probably gtk3).

If the older version is still supported and receiving updates, then it might also be reasonable to have both, though that's more case-by-case.

**Comment by Voskrese** [comment]
@ras0219-msft  я портировал\подсунул методом копирования вторую версию, два проекта определили версию которую хотели\вторую. в принципе для меня с gtk-2 вопрос исчерпан, но я думаю что многие работают со старыми проектами, и будут благодарны за оф.порт

> I ported \ podsunul by copying the second version, two defined version which wanted a \. basically for me with gtk-2 question is settled, but I think many are working with old projects, and be thankful for the port.

**Comment by Voskrese** [comment]
с qt4 видимо вопрос не будет решен, поэтому закрою)
