### ISSUE TITLE
[New Port Request] Intel® Open Volume Kernel Library (Intel® Open VKL)

### ISSUE THREAD

**Issue by cgolchert** [microsoft/vcpkg#12962]
Library name:
_Intel® Open Volume Kernel Library (Intel® Open VKL)_

Library description:
_Intel® Open Volume Kernel Library (Intel® Open VKL) is a collection of high-performance volume computation kernels, developed at Intel. The target users of Open VKL are graphics application engineers who want to improve the performance of their volume rendering applications by leveraging Open VKL’s performance-optimized kernels, which include volume traversal and sampling functionality for a variety of volumetric data formats. The kernels are optimized for the latest Intel® processors with support for SSE, AVX, AVX2, and AVX-512 instructions. Open VKL is part of the Intel® oneAPI Rendering Toolkit and is released under the permissive Apache 2.0 license.

Open VKL provides a C API, and also supports applications written with the Intel® SPMD Program Compiler (ISPC) by also providing an ISPC interface to the core volume algorithms. This makes it possible to write a renderer in ISPC that automatically vectorizes and leverages SSE, AVX, AVX2, and AVX-512 instructions. ISPC also supports runtime code selection, thus ISPC will select the best code path for your application.

In addition to the volume kernels, Open VKL provides tutorials and example renderers to demonstrate how to best use the Open VKL API._

Source repository URL:
_https://github.com/openvkl/openvkl_

Project homepage (if different from the source repository):
_https://www.openvkl.org/_

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by andyzimmerer** [comment]
?

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
