### ISSUE TITLE
nugetconfig binary source ignores API key in config file

### ISSUE THREAD

**Issue by kelseyfrancis** [microsoft/vcpkg#12984]
**Is your feature request related to a problem? Please describe.**
For `nugetconfig` binary caching sources, vcpkg passes `-ApiKey AzureDevOps` as an option to the `nuget push` command, which overrides the API key specified in the nuget config file. This prevents pushing to corporate nuget repositories that require specific credentials.

**Proposed solution**
Remove `-ApiKey AzureDevOps` from the `nuget push` command for `nugetconfig` sources, or provide a vcpkg flag that causes it to be left off or overwritten with the real API key.

**Describe alternatives you've considered**
Add a `write`-only `nuget` binary source pointing at a temporary local directory, and then, after running `vcpkg install`, run a separate `nuget` command manually without the `-ApiKey` flag. This has at least a few disadvantages: more complicated config for separate `read` and `write` sources, requiring an extra step to upload and then cleanup files vs. it happening automatically, and not being able to rely on the copy of nuget vcpkg downloads for itself to use.

**Comment by BillyONeal** [comment]
Giving this to Robert since it's related to binary caching

**Comment by ekilmer** [comment]
I'm still exploring this feature, but I think including the hardcoded key in the `nuget` command is a bug.

I can open a PR to get more eyes on any consequences that may result, but here is my diff:
```patch
diff --git a/toolsrc/src/vcpkg/binarycaching.cpp b/toolsrc/src/vcpkg/binarycaching.cpp
index 4563f575e..5512182c5 100644
--- a/toolsrc/src/vcpkg/binarycaching.cpp
+++ b/toolsrc/src/vcpkg/binarycaching.cpp
@@ -393,8 +393,6 @@ namespace
                     cmd.path_arg(nuget_exe)
                         .string_arg("push")
                         .path_arg(nupkg_path)
-                        .string_arg("-ApiKey")
-                        .string_arg("AzureDevOps")
                         .string_arg("-ForceEnglishOutput")
                         .string_arg("-Source")
                         .string_arg(write_src);
@@ -426,8 +424,6 @@ namespace
                     cmd.path_arg(nuget_exe)
                         .string_arg("push")
                         .path_arg(nupkg_path)
-                        .string_arg("-ApiKey")
-                        .string_arg("AzureDevOps")
                         .string_arg("-ForceEnglishOutput")
                         .string_arg("-ConfigFile")
                         .path_arg(write_cfg);
```

ping @ras0219

**Comment by photex** [comment]
Just want to toss my 👍 here as a JetBrains Space user. I'm not able to cache anything in our private nuget feed as a result of this. All attempts return 403 as expected.
