### ISSUE TITLE
[New Port Request] <NumCpp>

### ISSUE THREAD

**Issue by veikai** [microsoft/vcpkg#12989]
Library name:NumCpp

Library description:A Templatized Header Only C++ Implementation of the Python NumPy Library

Source repository URL:https://github.com/dpilger26/NumCpp

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by NancyLi1013** [comment]
Hi @veikai 
Thanks for posting this request.
`NumCpp `has been added to vcpkg via PR #12682. 

Please try to update vcpkg to the latest version and use this port.
