### ISSUE TITLE
[<port name>] build failure

### ISSUE THREAD

**Issue by stemuser027** [microsoft/vcpkg#12996]
**Host Environment**
- OS: [e.g. Windows/Linux etc...] Windows
- Compiler: revision

**To Reproduce**
`./vcpkg install xxxx`

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

**Additional context**
I am using Visual Studio 2017 and setup to use Opengl and Freeglut.
I am getting the following error. Please help. Please tell me what I am missing.

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1104	cannot open file 'freeglut.obj'	Keyboard	c:\Users\Josep\source\repos\MainKeyboard\Keyboard\LINK	1

This is the setup I have done so far:

I have the following files under the noted directories
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\GL
       freeglut.h, freeglut_ext.h, freeglut_std.h, freeglut_ext.h, freeglut_ucall.h, glut.h

C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\lib\x64
    freeglut.lib

C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\lib\x86
    I did not put anything under this directory. There was only one freeglut.lib file 

C:\Windows\System32
        freeglut.dll

C:\Windows\SysWOW64
    freeglut.dll

**Comment by PhoebeHui** [comment]
@stemuser027, could you provide more information? like the repro steps and repro code.

Do you install the freeglut by vcpkg and copy everything to msvc toolset forlder?

**Comment by stemuser027** [comment]
Thank you so much for you response. I got the information from

http://freeglut.sourceforge.net/index.php#download

under the section for "Stable Re;ease", I selected:
freeglut 3.2.1 [Released: 29 September 2019]

If this the correct location, or do you have a recommended repo for me go get the inormation

**Comment by PhoebeHui** [comment]
@stemuser027, let me know if you have any questions about installing freeglut via vcpkg.

**Comment by PhoebeHui** [comment]
@stemuser027, vcpkg provide a very easy and simple solution for setting up the freeglut port in your project. please reopen this issue if you still have any issue for freeglut that installing by vcpkg.
