### ISSUE TITLE
Error: database corrupted

### ISSUE THREAD

**Issue by showintime** [microsoft/vcpkg#12992]
Error: database corrupted. Package tiff:x64-windows is installed but dependency libjpeg-turbo:x64-windows is not.
so how to solve this problem?

**Comment by showintime** [comment]
![image](https://user-images.githubusercontent.com/29477247/90599745-fb8ac900-e227-11ea-978c-0a610e2ff35e.png)

**Comment by NancyLi1013** [comment]
Hi @showintime 
Thanks for posting this issue.
Could you please remove tiff:x64-windows first, then install `libjpeg-turbo:x64-windows`?

Since `tiff ` depends on `libjpeg-turbo` to build.

**Comment by showintime** [comment]
> Hi @showintime
> Thanks for posting this issue.
> Could you please remove tiff:x64-windows first, then install `libjpeg-turbo:x64-windows`?
> 
> Since `tiff ` depends on `libjpeg-turbo` to build.

**Comment by showintime** [comment]
> Hi @showintime
> Thanks for posting this issue.
> Could you please remove tiff:x64-windows first, then install `libjpeg-turbo:x64-windows`?
> 
> Since `tiff ` depends on `libjpeg-turbo` to build.

Hi @NancyLi1013 
Thanks  a lot, and I have solved it by using the way you told.
I have met this problem because i inited two vcpkg instances.

**Comment by wdx04** [comment]
I'm running into the same problem. If running multiple vcpkg instances simultaneously is not supported, it should be prevented by using some locking mechanism.

**Comment by 1647606255** [comment]
I'm running into the same problem  too. it is a serious bug.

> I'm running into the same problem. If running multiple vcpkg instances simultaneously is not supported, it should be prevented by using some locking mechanism.

**Comment by sfhacker** [comment]
https://english-for-chinese.blogspot.com/2008/06/and-meet-problem.html
