### ISSUE TITLE
qt5-webengine dependency qt5-tools:x64-windows build failure

### ISSUE THREAD

**Issue by Canvis-Me** [microsoft/vcpkg#13009]
**Host Environment**
- OS: [Windows 1909 18363.1016]
- Compiler: MS Visual Studio 16.5

**To Reproduce**
A clean installation of qt5-webengine:x64-windows is fine(Clone the vcpkg main branch and build it first time). However, every time a I run a git pull command, vcpkg update and vcpkg upgrade --no-dry-run, it'll rebuild the qt5 pkg. Then it will fail to build qt5-tools:x64-windows, though I removed qt5 and some related building files.

`git pull`
`./vcpkg update`
`./vcpkg upgrade --no-dry-run`
`./vcpkg install qt5-webengine:x64-windows`

**Failure logs** 
-- Configuring x64-windows-rel
-- Configuring x64-windows-rel done
-- Configuring x64-windows-dbg
-- Configuring x64-windows-dbg done
-- Package build-x64-windows-dbg
-- Package build-x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:139 (message):
    Command failed: E:/Downloads/vcpkg/downloads/tools/jom/jom-1.1.3/jom.exe -j 9
    Working Directory: E:/Downloads/vcpkg/buildtrees/qt5-tools/x64-windows-rel
    See logs for more information:
      E:\Downloads\vcpkg\buildtrees\qt5-tools\package-build-x64-windows-rel-out.log
      E:\Downloads\vcpkg\buildtrees\qt5-tools\package-build-x64-windows-rel-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_qmake.cmake:31 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_build_qmake.cmake:67 (run_jom)
  installed/x64-windows/share/qt5/qt_build_submodule.cmake:12 (vcpkg_build_qmake)
  installed/x64-windows/share/qt5/qt_submodule_installation.cmake:8 (qt_build_submodule)
  ports/qt5-tools/portfile.cmake:3 (qt_submodule_installation)
  scripts/ports.cmake:79 (include)

[package-build-x64-windows-rel-err.log](https://github.com/microsoft/vcpkg/files/5098519/package-build-x64-windows-rel-err.log)
[package-build-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/5098520/package-build-x64-windows-rel-out.log)

**Comment by Neumann-A** [comment]
```
helpviewer.obj : error LNK2001: unresolved external symbol "protected: virtual void __cdecl HelpViewer::resizeEvent(class QResizeEvent *)" (?resizeEvent@HelpViewer@@MEAAXPEAVQResizeEvent@@@Z)
helpviewer_qwv.obj : error LNK2001: unresolved external symbol "protected: virtual void __cdecl HelpViewer::resizeEvent(class QResizeEvent *)" (?resizeEvent@HelpViewer@@MEAAXPEAVQResizeEvent@@@Z)
..\..\..\bin\assistant.exe : fatal error LNK1120: 1 unresolved externals
```

**Comment by Neumann-A** [comment]
https://bugreports.qt.io/browse/QTBUG-83938

**Comment by Neumann-A** [comment]
```
Thiago Macieira  1:16 AM
@Alexander Neumann QtWebKit is no longer supported. Just disable it and remove from your build.
```

**Comment by Canvis-Me** [comment]
Thanks, I did install qtwebkit in vcpkg. Remove it, and the build for qt5-tools works well.
