### ISSUE TITLE
[boost-compatibility] LICENSE_1_0.txt download failed

### ISSUE THREAD

**Issue by iuming** [microsoft/vcpkg#13001]
When asking a question please also include where you looked for an answer (so we can update the documentation if needed).
When I run `vcpkg install boost-compatibility` to install boost-compatibility, but it show this error, How can I solve it?
```
Computing installation plan...
The following packages will be built and installed:
    boost-compatibility[core]:x64-linux
Detecting compiler hash for triplet x64-linux...
Starting package 1/1: boost-compatibility:x64-linux
Building package boost-compatibility[core]:x64-linux...
Could not locate cached archive: /root/.cache/vcpkg/archives/01/0183611ac14bee3fe80e718b11c92d9342ba8123.zip
-- Using cached /home/local1/polatory/vcpkg/downloads/boostorg-compatibility-boost-1.73.0.tar.gz
-- Cleaning sources at /home/local1/polatory/vcpkg/buildtrees/boost-compatibility/src/ost-1.73.0-44642da97c.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/local1/polatory/vcpkg/downloads/boostorg-compatibility-boost-1.73.0.tar.gz
-- Using source at /home/local1/polatory/vcpkg/buildtrees/boost-compatibility/src/ost-1.73.0-44642da97c.clean
-- Packaging headers
-- Packaging headers done
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.73.0/LICENSE_1_0.txt...
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.73.0/LICENSE_1_0.txt... Failed. Status: 7;"Couldn't connect to server"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:176 (message):
      
      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  installed/x64-linux/share/boost-vcpkg-helpers/boost-modular-headers.cmake:17 (vcpkg_download_distfile)
  ports/boost-compatibility/portfile.cmake:12 (boost_modular_headers)
  scripts/ports.cmake:79 (include)


Error: Building package boost-compatibility:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-compatibility:x64-linux
  Vcpkg version: 2020.06.15-unknownhash

Additionally, attach any relevant sections from the log files above.
```

**Comment by BaderEddineOuaich** [comment]
CMake uses cURL to download resources, which requires HTTP/HTTPS proxy to be setup.
check out  [how to configure proxy settings in linux](https://www.serverlab.ca/tutorials/linux/administration-linux/how-to-configure-proxy-on-ubuntu-18-04/)

**Comment by StarGate-One** [comment]
Put this file in the [vcpkg-root]\downloads folder and try again. 
[boost_LICENSE_1_0.txt](https://github.com/microsoft/vcpkg/files/5099992/boost_LICENSE_1_0.txt)

**Comment by iuming** [comment]
> Put this file in the [vcpkg-root]\downloads folder and try again.
> [boost_LICENSE_1_0.txt](https://github.com/microsoft/vcpkg/files/5099992/boost_LICENSE_1_0.txt)

It is cool! Thank you very much,Thanks to your help, I solved my problem.


> CMake uses cURL to download resources, which requires HTTP/HTTPS proxy to be setup.
> check out [how to configure proxy settings in linux](https://www.serverlab.ca/tutorials/linux/administration-linux/how-to-configure-proxy-on-ubuntu-18-04/)

At the same time,I also thank you for your reply, but I did not implement the countermeasures you proposed, thank you again!

**Comment by NancyLi1013** [comment]
Hi @iuming 

Thanks for posting this issue.
It seems that you have solved this problem. Please let me know if you still have any concerns about this.

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/13348
