### ISSUE TITLE
An informative site of vcpkg ports

### ISSUE THREAD

**Issue by cloudhan** [microsoft/vcpkg#13015]
This is not an issue anyway.

https://vcpkg.info/

It was mentioned in https://www.reddit.com/r/cpp/comments/ibjgqq/vcpkginfo/

And I think vcpkg might needs something like this someday in the future.

Feel free to close this issue.

**Comment by NancyLi1013** [comment]
Hi @cloudhan 
Thanks for bringing this up.
It looks like great.

@BillyONeal 
Do you know if we have any plan to do something like this?

Thanks.

**Comment by Neumann-A** [comment]
There is also `vcpkgx.com` mentioned by someone in the vcpkg slack and the reddit post

**Comment by NancyLi1013** [comment]
@Neumann-A 
Thanks for your above information.

@cloudhan 
https://vcpkgx.com/ is similar to https://vcpkg.info/.

In my opinion, both of them can work for users now.
