### ISSUE TITLE
[expat] a few issues

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#13012]
- requires a vcpkg-cmake-wrapper.cmake to correctly set debug **&** release versions in `EXPAT_LIBRARIES` due to how cmakes FindEXPAT module works.
 - library name changed from 2.2.7 from expat.lib to libexpat.lib in >2.2.9. This will break future work on make based ports expecting the name expat and thus leads to a lot of pain and patching. upstream need to get their stuff together here and shouldn't change the library name but use versioned dll's instead to fix the observed problem which was according to the cmakelists.txt:
```
# Avoid colliding with Expat.dll of Perl's XML::Parser::Expat
if(WIN32 AND NOT MINGW)
    set(_EXPAT_TARGET libexpat)
else()
    set(_EXPAT_TARGET expat)
endif()
```
 the above changes makes supporting normal windows and mingw builds unnecessarily complex......
 - furthermore expat linkage via cmake is currently inconsistent due to https://github.com/libexpat/libexpat/issues/407

**Comment by NancyLi1013** [comment]
Hi @Neumann-A 

Thanks for posting this issue.

I also noticed that the issue you mentioned above on upstream. It seems like upstream also does some changes about the port output name.

So it might be better to fix this after there is a conclusion on upstream. What do you think about this?

**Comment by hartwork** [comment]
> library name changed from 2.2.7 from expat.lib to libexpat.lib in >2.2.9.

Not exactly. 2.2.9 is back at where 2.2.7 was: The change in 2.2.8 was mistaken and reverted. The [dedicated change log entry of 2.2.9](https://github.com/libexpat/libexpat/blob/c092d40c300c6d219cb3b111932a824022265370/expat/Changes#L54-L59) explains in more detail. To make it visual:

| Version | Artifact |
| -- | --: |
| 2.2.7 | `libexpat.lib` |
| 2.2.8 | `expat.lib` | 
| 2.2.9 | `libexpat.lib` |
