### ISSUE TITLE
Post build validation: The following DLLs have no exports

### ISSUE THREAD

**Issue by bagong** [Microsoft/vcpkg#1301]
Hi,

I am almost done with a port for aubio. Last remaining issue, I get this "The following DLLs have no exports" error in post-build validation. While the (unixy) code does in fact not contain export markup, I have created an import-lib from a def file I created outside of the build process (and added to the port dir), so I think the implib is valid. Yet the post-build-validation error prevents the "packaging" from completing, i.e. the files are not copied to the "installed" file branch. Is there a way to get around this? An exception list, or an argument or something?

**Comment by ras0219-msft** [comment]
While the import lib is valid, the DLL actually isn't valid! Without entries in the PE header indicating the _actually addresses_ corresponding to each symbol name, the DLL isn't usable.

Def files work when you include them _at link time_, which both creates an import lib and makes sure the linker puts the address/symbol mapping in the DLL header. In CMake, this is as easy as adding the `.def` file to the `add_library()` sources list. From other buildsystems, you'll need to add `/DEF:<file>` to the link line[1].

[1] https://docs.microsoft.com/en-us/cpp/build/reference/def-specify-module-definition-file

**Comment by ras0219-msft** [comment]
Also, remember that if the upstream library really only supports static linkage, that's ok. We just need to add a little switch at the top to notify the user:
```cmake
if (VCPKG_LIBRARY_LINKAGE STREQUAL dynamic)
    message(STATUS "Warning: Dynamic building not supported yet. Building static.")
    set(VCPKG_LIBRARY_LINKAGE static)
endif()
```

**Comment by bagong** [comment]
Ah, thank you!

Can I ask two more questions:

- is there a tool among the MS tools to generate such a .def file? I tried with `dumpbin /export ...`, but - while this does work with other dll's I've used - doesn't produce the symbols in the aubio case (I got the list by running mingw's `objdump ` in a msys2 build).

- I I'd fall back to building static only, will library be installed to the xXX-windows, or to the xXX-windows-static branch? Also: wouldn't that mean that - expecting aubio would be used in build where static and dynamic linking is used together - aubio-static had to be built with MD?

**Comment by ras0219-msft** [comment]
I'm not sure about the first one.

Libraries are _always_ installed to the triplet you're building them for (so if you say `install aubio:x64-windows` it will go to x64-windows). In this case, it would be built with /MD or /MDd since `triplets\x64-windows.cmake` sets `VCPKG_CRT_LINKAGE` to `dynamic`.

Each triplet is actually just a set of configuration information (see the `triplets\` folder). While we do have triplets explicitly labelled "-static", there is no reason why you can't make your own called "strawberry".

For more info on triplets, take a look at https://vcpkg.readthedocs.io/en/latest/users/triplets/.

**Comment by bagong** [comment]
> Libraries are always installed to the triplet you're building them for (so if you say install aubio:x64-windows it will go to x64-windows). In this case, it would be built with /MD or /MDd since triplets\x64-windows.cmake sets VCPKG_CRT_LINKAGE to dynamic.

Yea, but I was asking for the case `Warning: Dynamic building not supported yet - building *static*` where a user gets ab build (s)he didn't expect. I am still thinking of the imaginary triplet  xXX-windows-staticLib-dynRT. It makes so much sense in many practically relevant build scenarios, that it might be worth to promote it to one of the default triplets. In cases where a static build is done automatically because a dynamic build is not possible, CRT linkage should likely be /MD, otherwise (s)he will likely end up with a build she can't use in a context where the other libraries are built with dynamic linking.

I'll consider strawberry ;) But I think it makes a lot of sense to name triplets after projects if mixing/exceptions are used.

Thanks for all your help!

**Comment by ras0219-msft** [comment]
>In cases where a static build is done automatically because a dynamic build is not possible, CRT linkage should likely be /MD, otherwise (s)he will likely end up with a build she can't use in a context where the other libraries are built with dynamic linking.

When building a portfile, there's an imaginary `include(<triplet>.cmake)` at the top of the file. This is what pre-sets the variables `VCPKG_CRT_LINKAGE` and `VCPKG_LIBRARY_LINKAGE` (and architecture, etc).

The portfile itself can then modify these if it must; I can't think of a single instance where you would modify the `VCPKG_CRT_LINKAGE` though.

Then, commands like `vcpkg_configure_cmake()` will use the current settings of `VCPKG_CRT_LINKAGE` and `VCPKG_LIBRARY_LINKAGE` to properly configure the library to-be-built.

Finally, after the portfile finishes, vcpkg performs a post-build check to ensure that you built what you said you would :). This means we check that the CRT matches `VCPKG_CRT_LINKAGE` and other things.

So, in the case that you override `VCPKG_LIBRARY_LINKAGE`, you will (crucially) still have the same _CRT_ linkage as every other library in the triplet. In the case that the library doesn't use CMake, you should check `VCPKG_CRT_LINKAGE` and `VCPKG_LIBRARY_LINKAGE` and correctly configure the build according to those settings.

Thus, this is how the user can tell you what their CRT context is -- it's in the triplet file as the variable `VCPKG_CRT_LINKAGE`. This makes sure it's set the exact same for _every_ library in the triplet.

**Comment by bagong** [comment]
Ah so maybe I misunderstood: in the case "user tries to build dynamic library but portfile force resets to static because dynamic linking is not supported for that library" the resulting static library will still be installed to the "installed/dynamic" triplet and use /MD? That would make a lot of sense to me. But I thought as a rule you wanted to avoid such mixing. Otherwise - if the force override dynamic->static library linking would also force /MD->/MT that library could not be used in an external build that otherwise uses dynamic libraries (which default to /MD), right?

Sorry, I am likely dense here, hope not to overstress your patience...

**Comment by ras0219-msft** [comment]
> But I thought as a rule you wanted to avoid such mixing.

It would be ideal if everything was consistent, but it's better to have a library as a static lib than to not have it at all. Effectively, the normal triplets are "build everything as DLLs when possible, but static libs when it isn't".

> Otherwise - if the force override dynamic->static library linking would also force /MD->/MT

To be completely clear, _Vcpkg_ has two separate settings here: `VCPKG_CRT_LINKAGE` and `VCPKG_LIBRARY_LINKAGE`. In the snippet above, we're only changing `VCPKG_LIBRARY_LINKAGE`, which is safe. The CRT will stay as /MT or /MD (whatever it was intended to be).

It's certainly possible that the library's buildsystem won't react correctly (they might trigger /MT off of static builds). This is why the final post-build checks are there, which will catch that :).

**Comment by bagong** [comment]
Okay, great, I finally got it, and I think it's a good way to handle it ;)

**Comment by Voskrese** [comment]
@bagong 
тут есть намек на ваш вопрос, на сколько он рабочий для вашего проекта, незнаю
https://wiki.videolan.org/GenerateLibFromDll
как то так
dumpbin и dlltool и dllwrap

**Comment by bagong** [comment]
Thanks @Voskrese , that is a nice practical write-up. But according to @ras0219-msft : "Without entries in the PE header indicating the actually addresses corresponding to each symbol name, the DLL isn't usable." And those "entries in the PE header" can only be made by the linker on the creation of the dll, it seems... I'll research further. Unfortunately I have other problems with my build as well, so I can't really say which problem is owed to what atm. The weird thing is that dumpbin doesn't produce any export symbols for me (objdump does...). But thanks for your help!
