### ISSUE TITLE
[arrow] should use vcpkg provided dependencies

### ISSUE THREAD

**Issue by codicodi** [Microsoft/vcpkg#1302]
Currently flatbuffers and rapidjson are downloaded during build:
https://github.com/apache/arrow/blob/d25ea6314bce574bfc6f93e97c542c69442314b4/cpp/CMakeLists.txt#L694
https://github.com/apache/arrow/blob/d25ea6314bce574bfc6f93e97c542c69442314b4/cpp/CMakeLists.txt#L672

**Comment by JackBoosY** [comment]
Hi @codicodi , thanks for post this issue!
Since arrow update to v0.11.1, this bug has been fixed.
Plz update vcpkg and rebuild it.
Thx.

**Comment by JackBoosY** [comment]
Please open a new issue if this is still a problem for you.
Thx.
