### ISSUE TITLE
[xxhash] build failure

### ISSUE THREAD

**Issue by gleblebedev** [microsoft/vcpkg#13021]
**Host Environment**
- OS: Windows
- Compiler: VS 2019

**To Reproduce**
`./vcpkg install lz4:x64-uwp`

**Failure logs** 
1>------ Build started: Project: xxhsum, Configuration: Debug x64 ------
1>LINK : fatal error LNK1181: cannot open input file 'Debug\xxhash.lib'
![image](https://user-images.githubusercontent.com/2943937/90744860-01d08200-e2c8-11ea-9423-d115f3987cf2.png)

**Additional context**
It looks like generated project file does not reference xxhash properly.
This happens when I install lz4 dependency, but it actually fails on xxhash.

**Comment by gleblebedev** [comment]
It looks like Debug\xxhash.lib should be Debug\xxhash\xxhash.lib in generated project file.

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Did you install `lz4:x64-uwp` failed on VCPKG? I can insall it successfully with the latest VCPKG.
![image](https://user-images.githubusercontent.com/47812810/90755864-3b2be080-e30e-11ea-8476-4e16ac3377c3.png)
If you use xxhash in your project failed, please provide a repro codes.

**Comment by gleblebedev** [comment]
@LilyWangL thank you for a quick reply.

I've tried to repro it on a fresh vcpkg clone and it works fine but when I run it from powershell script it doesnt even if at a first glance both do the same thing.

I need some time to investigate this but at this point it looks like not a vcpkg issue on itself.
