### ISSUE TITLE
[boost] Update to 1.74.0

### ISSUE THREAD

**Issue by longnguyen2004** [microsoft/vcpkg#13033]
Library name: boost

New version number: 1.74.0

Other information that may be useful (release notes, etc...)
There are some mingw related fixes in boost-build that I'd like to have

**Comment by SeanFarrow** [comment]
If there were instructions on how to do this, I'm happy to help as it's something a project I'm working on needs to fully move to VCPKG as a packange manager.

**Comment by longnguyen2004** [comment]
It has something to do with [this PowerShell script](https://github.com/microsoft/vcpkg/blob/master/scripts/boost/generate-ports.ps1) I think

**Comment by SeanFarrow** [comment]
Ah… OK…, let me have a look at that and see what I can come up with!
Thanks,
Sean.

**Comment by SeanFarrow** [comment]
Ok, if you change all the references from 1.73 to 1.74 in the script you reference, change the PowerShell execution policy to unrestricted for the current session and have VCPKG somewhere on the path, you should be able to run the script and update the port locally.

There is a new header-only library with 1.74, Nowide, so I’m not sure how new libraries are handled as we might want a new installable package for that.

**Comment by longnguyen2004** [comment]
It should be automatically handled by [this line](https://github.com/microsoft/vcpkg/blob/master/scripts/boost/generate-ports.ps1#L230)

**Comment by SeanFarrow** [comment]
Ok, can you try just changing the version references from 1.73 to 1.74 and let me know how that goes.

I can’t check this myself before the weekend unfortunately.
Thanks,
Sean.

**Comment by longnguyen2004** [comment]
Alright I'll test it tomorrow

**Comment by SeanFarrow** [comment]
OK, I've now started some work on this on a private branch.
I'm struggling to get Nowide building as the jam.v2 file has changed and is now looking for config, which it searches for in the wrong directory.
I'm thinking of adding a cmake file to handle this and update where it thinks the config file is, or should we crate a patch, if so what againsh?

**Comment by longnguyen2004** [comment]
Can anyone works on this? I'm quite busy now

**Comment by SeanFarrow** [comment]
I think I know what the fix is, give me the weekend to validate my thinking.

**Comment by StarGate-One** [comment]
I see boost/STLInterfaces has been added in the 1.74 update, https://www.boost.org/users/history/version_1_74_0.html

**Comment by longnguyen2004** [comment]
I'll try to get some time to work on this tonight

**Comment by SeanFarrow** [comment]
OK, I’ve forked and finished 90 % of the work, so If you want to carry on, go to:
https://github.com/SeanFarrow/vcpkg.git
The branch you want is Issue13033.

The only issue I can see remaining is the completion of correctly building the nowide library, they changed the way this works in 1.74 and used config checks.

Thanks,
Sean.

**Comment by niclar** [comment]
-@SeanFarrow, can't see the Issue13033 branch...

**Comment by SeanFarrow** [comment]
Give me until tomorrow, I forgot to push!

**Comment by SeanFarrow** [comment]
@niclar,
This has now been pushed, the branch you want from my fork is Issue13033.
 I've updated the version in scripts/boost/generate-ports.ps1, but when I try to do:
vcpkg install boost-nowide:x86-windows-static
There is an issue around finding the config folder (we need a cmake file to copy this in.) 

Then, this library fails to build, I'm assuming because it fails to find some targets in the .bjam file.
Once these two issues have been fixed, we can do some testing and then should be good to go!
Thanks,
Sean.

**Comment by SeanFarrow** [comment]
@niclar Are you able to submit a PR to my original branch, I'll then take things from there.￼

**Comment by niclar** [comment]
sure, https://github.com/SeanFarrow/vcpkg/pull/1

**Comment by longnguyen2004** [comment]
I don't really know much about the way vcpkg handles boost, so @SeanFarrow and @niclar please finish it for me, and I'll work on the mingw part.

**Comment by niclar** [comment]
works now for linux & windows (including the latest toolset) in: https://github.com/niclar/vcpkg/tree/Issue13033

**Comment by SeanFarrow** [comment]
@niclar  if you can create a pull request to my fork, I'll fix this this weekend and we can get it merged upstream as soon as practically possible.￼

**Comment by SeanFarrow** [comment]
@longnguyen2004  Did you manage to have a look at the pull request created by @niclar?

**Comment by longnguyen2004** [comment]
I'll try to find some free time to test it with llvm-mingw.

**Comment by SeanFarrow** [comment]
Fantastic, it’s working fine with Visual Studio 2019.

**Comment by longnguyen2004** [comment]
Seems to work fine with llvm-mingw as well!

**Comment by SeanFarrow** [comment]
Are you happy to merge this?
As an FYI, when boost 1.75 is released (scheduled for around the 2nd December), I’ll create an issue/patch.
Thanks,
Sean.

**Comment by longnguyen2004** [comment]
@niclar How's the PR going? It looks pretty good to me

**Comment by longnguyen2004** [comment]
Alright we can close this now :)
