### ISSUE TITLE
[bzip2:x64-windows] build failure

### ISSUE THREAD

**Issue by alphaquant2** [microsoft/vcpkg#13036]
Hi I am sorry I could not install bzip2 package with this updated compiler version. However, with the previous version last year it worked.
would it be possible to have this problem fixed? 
Best Regards
Jérôme Garcia

**Host Environment**
- Windows 10
- Compiler: version 2020.06.15-nohash

**To Reproduce**
`./vcpkg install bzip2:x64-windows`

**Failure logs** 
Starting package 1/1: bzip2:x64-windows
Building package bzip2[core]:x64-windows...
Could not locate cached archive: C:\Users\Jérôme\AppData\Local\vcpkg/archives\fd\fdbd36227fe45ab3651e181fb29d360a45311b53.zip
-- Downloading https://github.com/past-due/bzip2-mirror/releases/download/v1.0.6/bzip2-1.0.6.tar.gz...
-- Extracting source E:/alpha/math/C++/librairies/vcpkg-master/downloads/bzip2-1.0.6.tar.gz
-- Applying patch fix-import-export-macros.patch
-- Applying patch fix-windows-include.patch
-- Using source at E:/alpha/math/C++/librairies/vcpkg-master/buildtrees/bzip2/src/1.0.6-8838f21f8e.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_fixup_pkgconfig.cmake:259 (list):
  list sub-command FILTER, mode REGEX failed to compile regex
  "E:/alpha/math/C++/librairies/vcpkg-master/packages/bzip2_x64-windows/debug/".
Call Stack (most recent call first):
  ports/bzip2/portfile.cmake:49 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:79 (include)

RegularExpression::compile(): Nested *?+.
RegularExpression::compile(): Error in compile.
Error: Building package bzip2:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: bzip2:x64-windows
  Vcpkg version: 2020.06.15-nohash

**Comment by Neumann-A** [comment]
`math/C++/librairies` rename to `math/Cpp/librairies`
There was somewhere a PR fixing it but I was not able to directly find it

**Comment by JonLiu1993** [comment]
Hi @alphaquant2 ,
Can your problem be solved according to @Neumann-A Neumann-A's suggestion? I can install it locally

**Comment by alphaquant2** [comment]
Hi, indeed in renaming the directory C++ into Cpp, it allowed the compilation to succeed. However as I have other programms working on the same C++ directory in other computers I am doing the move carefully on a test computer to see if the rest will fit. Thanks

**Comment by Neumann-A** [comment]
the relevant pr is #12964
