### ISSUE TITLE
Port request: bgfx

### ISSUE THREAD

**Issue by nuriu** [microsoft/vcpkg#1303]
[bgfx](https://github.com/bkaradzic/bgfx) is cross-platform, graphics API agnostic, "Bring Your Own Engine/Framework" style rendering library.

Is it feasible to have it among current packages?

**Comment by vii1** [comment]
Created PR #7763

**Comment by JackBoosY** [comment]
We can’t reopen this issue until a PR is opened, unfortunately, consider making a pull request!
