### ISSUE TITLE
[vcpkg - bootstrap-vcpkg.sh] clang and gcc - Unknown escape sequence in PR #12976 updated sources

### ISSUE THREAD

**Issue by StarGate-One** [microsoft/vcpkg#13039]
**Describe the bug**
Unknown escape sequence warnings when running bootstrap-vcpkg.sh

**Environment**
- OS: [Linux - openSUSE 15.2 WSL2 and Hyper-V]
- Compiler: gcc (SUSE Linux) 9.3.1 20200406 [revision 6db837a5288ee3ca5ec504fbd5a765817e556ac2]

**To Reproduce**
1. >$ git pull
2. >$ ./bootstrap-vcpkg.sh --disableMetrics
-- The CXX compiler identification is GNU 9.3.1
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting the C++ compiler in use
-- Detecting the C++ compiler in use - gcc
-- Detecting the C++ standard library
-- Detecting the C++ standard library - libstdc++
-- Detecting how to use the C++ filesystem library
-- Detecting how to use the C++ filesystem library - <filesystem>
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ac-130h/git/vcpkg/toolsrc/build.rel
[0/2] Re-checking globbed directories...
[27/80] Building CXX object CMakeFiles/vcpkglib.dir/src/vcpkg/build.cpp.o
../src/vcpkg/build.cpp: In function ‘std::string vcpkg::Build::create_user_troubleshooting_message(const vcpkg::PackageSpec&)’:
../src/vcpkg/build.cpp:1092:33: warning: unknown escape sequence: '\/'
 1092 |         auto vcpkg_update_cmd = ".\/vcpkg";
      |                                 ^~~~~~~~~~
[48/80] Building CXX object CMakeFiles/vcpkglib.dir/src/vcpkg/commands.version.cpp.o
../src/vcpkg/commands.version.cpp: In function ‘void vcpkg::Commands::Version::warn_if_vcpkg_version_mismatch(const vcpkg::VcpkgPaths&)’:
../src/vcpkg/commands.version.cpp:67:38: warning: unknown escape sequence: '\/'
   67 |                     auto bootstrap = ".\/bootstrap-vcpkg.sh";
      |                                      ^~~~~~~~~~~~~~~~~~~~~~~
[57/80] Building CXX object CMakeFiles/vcpkglib.dir/src/vcpkg/dependencies.cpp.o
../src/vcpkg/dependencies.cpp: In member function ‘vcpkg::Dependencies::{anonymous}::Cluster& vcpkg::Dependencies::ClusterGraph::get(const vcpkg::InstalledPackageView&)’:
../src/vcpkg/dependencies.cpp:263:41: warning: unknown escape sequence: '\/'
  263 |                 auto vcpkg_remove_cmd = ".\/vcpkg";
      |                                         ^~~~~~~~~~
[69/80] Building CXX object CMakeFiles/vcpkglib.dir/src/vcpkg/update.cpp.o
../src/vcpkg/update.cpp: In function ‘void vcpkg::Update::perform_and_exit(const vcpkg::VcpkgCmdArguments&, const vcpkg::VcpkgPaths&)’:
../src/vcpkg/update.cpp:81:30: warning: unknown escape sequence: '\/'
   81 |             auto vcpkg_cmd = ".\/vcpkg";
      |                              ^~~~~~~~~~
[75/80] Building CXX object CMakeFiles/vcpkglib.dir/src/vcpkg/sourceparagraph.cpp.o
../src/vcpkg/sourceparagraph.cpp: In function ‘void vcpkg::print_error_message(vcpkg::Span<const std::unique_ptr<vcpkg::Parse::ParseControlErrorInfo> >)’:
../src/vcpkg/sourceparagraph.cpp:185:30: warning: unknown escape sequence: '\/'
  185 |             auto bootstrap = ".\/bootstrap-vcpkg.sh";
      |                              ^~~~~~~~~~~~~~~~~~~~~~~
[80/80] Linking CXX executable vcpkg

**Expected behavior**
./bootstrap-vcpkg.sh should run with no errors/warnings.

**Failure logs** 
- No Logs

**Additional context**
Ran bootstrap-vcpkg.sh after yesterday's changes (08/19/2020) there were no errors, after today's (08/20/2020) updates the warnings/errors occur. No updates to openSUSE have been made since Saturday (08/15/2020).

**Comment by StarGate-One** [comment]
Update, to rule out a corrupted fork and/or instance:
1. I deleted my fork copy of vcpkg and re-forked it again
2. I deleted the vcpkg instances from both the WSL2 and Hyper-V openSUSE linux machines
3. I re-cloned the vcpkg instance from my forked copy
4. I ran bootstrap-vcpkg.sh --disableMetrics on both **with same errors**.
5. My Windows instances of vcpkg (cloned from the same forked copy of vcpkg) did not have these errors when running `.\bootstrap-vcpkg.bat -verbose -disableMetrics -win64 -withVSPath "'%VCPKG_VISUAL_STUDIO_PATH%'"` 2 each one prod, one test for each VS2017 and VS2019

**Comment by StarGate-One** [comment]
See https://github.com/microsoft/vcpkg/commit/680b2928a1b7173f7fcb420612f5536a192f9ca3#r41619715 this was brought up in the original PR #12976 by @qis but somehow was not corrected before these changes were committed to master???

**Comment by qis** [comment]
@StarGate-One Nah, I sneaked in that comment after reading those warnings when compiling `master`. It looked harmless and I was too lazy to create a PR. ^_^

**Comment by StarGate-One** [comment]
> @StarGate-One Nah, I sneaked in that comment after reading those warnings when compiling `master`. It looked harmless and I was too lazy to create a PR. ^_^

LOL - but I personally think with the introduction of the "new warnings" should have been caught and corrected before it was committed ^_^.

.

**Comment by PhoebeHui** [comment]
@StarGate-One, It's my fault, sorry for the mistake!

Fixed by PR https://github.com/microsoft/vcpkg/pull/13043

**Comment by PhoebeHui** [comment]
The PR has been merged, please get latest source and try again.
