### ISSUE TITLE
Allow upgrading to new revision of port.

### ISSUE THREAD

**Issue by rkitover** [microsoft/vcpkg#13037]
****

**Is your feature request related to a problem? Please describe.**

Today I was trying to upgrade libvorbis and it failed, because it requires a new revision of libogg with `pkg-config` support.

It did not automatically upgrade libogg, see: #12666 

When I tried to upgrade libogg manually, it did not allow me to do that either:

```
rkitover@epycwin > vcpkg update
Using local portfile versions. To update the local portfiles, use `git pull`.
The following packages differ from their port versions:
    ffmpeg:x64-windows-static        4.2#17 -> 4.2#20
    libflac:x64-windows-static       1.3.3#2 -> 1.3.3#3
    libogg:x64-windows-static        1.3.4 -> 1.3.4#2
    libvorbis:x64-windows-static     1.3.6-4d963fe -> 1.3.7
    openal-soft:x64-windows-static   1.20.1#4 -> 1.20.1#5
    zlib:x64-windows-static          1.2.11#7 -> 1.2.11#9

To update these packages and all dependencies, run
    .\vcpkg upgrade

To only remove outdated packages, run
    .\vcpkg remove --outdated

✔ ~\pkgs
rkitover@epycwin > vcpkg upgrade --no-dry-run libogg:x64-windows-static
The following packages are up-to-date:
    libogg:x64-windows-static
```

It seems that upgrades when just the revision of a port has changed are not allowed.

**Proposed solution**

At the very least allow such upgrades.

**Describe alternatives you've considered**

Implementing #10000 would also alleviate this problem.

**Additional context**

This is a serious flaw in the upgrade functionality.

**Comment by JackBoosY** [comment]
@BillyONeal What do you think about?
