### ISSUE TITLE
PowerShell 7 has been released for three months, and it is time to integrate into PowerShell 7 by default.

### ISSUE THREAD

**Issue by vistart** [microsoft/vcpkg#13049]
****

**Is your feature request related to a problem? Please describe.**

"PowerShell 7" has been released for three months, and I am using it. However, the 2020.06 version of vcpkg still uses PowerShell 6.2.1.

**Proposed solution**

It is integrated into PowerShell 7 by default。

**Describe alternatives you've considered**

Allows users to customize the version number of the integrated PowerShell.

**Comment by JackBoosY** [comment]
It's hard to say.
The new version of powershell must be compatible with many ps1 scripts in vcpkg.

**Comment by NancyLi1013** [comment]
Hi @vistart 

`PowerShell `has been updated to 7.1.0 in vcpkg now. You can update to the latest vcpkg and rebuild.

https://github.com/microsoft/vcpkg/blob/84e5852cfaa8e7875027e79a29a5534bb5d4a475/scripts/vcpkgTools.xml#L139
