### ISSUE TITLE
Memory exhausted

### ISSUE THREAD

**Issue by showintime** [microsoft/vcpkg#13042]
i try to install osg`vcpkg install install osg:x64-windows`,but it always exhausts memorys.
so how to limit memory and threads to vcpkg-compiler(MSVC Compiler)?

**Comment by JackBoosY** [comment]
You can modify _VCPKG_ROOT/ports/osg/portfile.cmake_ line 76 from
`vcpkg_install_cmake()`
to 
`vcpkg_install_cmake(DISABLE_PARALLEL)`.

**Comment by JackBoosY** [comment]
@showintime Does this issue resolved?

**Comment by showintime** [comment]
> You can modify _VCPKG_ROOT/ports/osg/portfile.cmake_ line 76 from
> `vcpkg_install_cmake()`
> to
> `vcpkg_install_cmake(DISABLE_PARALLEL)`.

thanks a lot,and i have installed osg by using `vcpkg_install_cmake(DISABLE_PARALLEL)`.

**Comment by showintime** [comment]
> @showintime Does this issue resolved?

**Comment by showintime** [comment]
> You can modify _VCPKG_ROOT/ports/osg/portfile.cmake_ line 76 from
> 
> to
> .`vcpkg_install_cmake()``vcpkg_install_cmake(DISABLE_PARALLEL)`

Could you take a look at this?
https://github.com/microsoft/vcpkg/issues/13292
