### ISSUE TITLE
[<port name>] build failure

### ISSUE THREAD

**Issue by simonouel** [microsoft/vcpkg#13041]
**Host Environment**
- OS: Windows
- Compiler: ?

**To Reproduce**
`./vcpkg install openimageio:x64-windows`

**Failure logs** 
Add any other context about the problem here, such as what you have already tried to resolve the issue.
Building package x265[core]:x64-windows...
Could not locate cached archive: C:\Users\simono\AppData\Local\vcpkg/archives\27\27b91bdd30a5d415bc5eb14cca158ea03aa5e08c.zip
-- Downloading https://bitbucket.com/multicoreware/x265/get/3.2.tar.gz...
-- Downloading https://bitbucket.com/multicoreware/x265/get/3.2.tar.gz... Failed. Status: 22;"HTTP response code said error"
CMake Error at //vmware-host/Shared Folders/raid/compile/windows10/oiio/vcpkg/scripts/cmake/vcpkg_download_distfile.cmake:176 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  //vmware-host/Shared Folders/raid/compile/windows10/oiio/vcpkg/scripts/cmake/vcpkg_from_bitbucket.cmake:127 (vcpkg_download_distfile)
  //vmware-host/Shared Folders/raid/compile/windows10/oiio/vcpkg/ports/x265/portfile.cmake:3 (vcpkg_from_bitbucket)
  //vmware-host/Shared Folders/raid/compile/windows10/oiio/vcpkg/scripts/ports.cmake:79 (include)

Error: Building package x265:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: x265:x64-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.

It seems to be a dead link.

**Comment by StarGate-One** [comment]
Looks like there is a github mirror: https://github.com/videolan/x265 there is a 3.2 tag but there is a verison 3.4 tag - do not know if upgrading it to latest version would cause incompatibilities???

If you rename the `[vcpkg-root]\ports\x265\portfile.cmake` and put this file in its place, renaming it from `portfile.cmake.txt` to `portfile.cmake` it should download/install, but no guarantees as I did not do the install, just a download to verify the SHA512 signature.
[portfile.cmake.txt](https://github.com/microsoft/vcpkg/files/5106207/portfile.cmake.txt)

**Comment by NancyLi1013** [comment]
Hi @simonouel and @StarGate-One 

Thanks for posting this issue.

It seems that the archive is not available now. We need to fix it later.

It's duplicated to #13035, so let's track this issue here.
