### ISSUE TITLE
How do I setup intel-mkl in vcpkg successfully?

### ISSUE THREAD

**Issue by iuming** [microsoft/vcpkg#13050]
When asking a question please also include where you looked for an answer (so we can update the documentation if needed).
I have successfully installed MKL (2020 Update 2), but it is on Disk E, and my vcpkg is on Disk F. Is this error caused by this reason? Still need to add some folders of MKL to the system environment variables? I don't know how to add it. According to the MKL installation manual in Intel, I have installed MKL and can use it in Visual Studio.
```
F:\RadL\Radiation_Field_Reconstruction\code\polatory\vcpkg>vcpkg install intel-mkl:x64-windows
Computing installation plan...
The following packages will be built and installed:
    intel-mkl[core]:x64-windows
Detecting compiler hash for triplet x64-windows...
Starting package 1/1: intel-mkl:x64-windows
Building package intel-mkl[core]:x64-windows...
Could not locate cached archive: C:\Users\Administrator.DESKTOP-T19EU2H\AppData\Local\vcpkg/archives\92\9252f2f10c52479593e366ba5d401fa5cddb72c7.zip
CMake Error at ports/intel-mkl/portfile.cmake:15 (message):
  Could not find MKL.  Before continuing, please download and install MKL
  (20200000 or higher) from:

      https://registrationcenter.intel.com/en/products/download/3178/



  Also ensure vcpkg has been rebuilt with the latest version (v0.0.104 or
  later)
Call Stack (most recent call first):
  scripts/ports.cmake:79 (include)


Error: Building package intel-mkl:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: intel-mkl:x64-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.
```

**Comment by JackBoosY** [comment]
Modify _VCPKG_ROOT/ports/intel-mkl/portfile.cmake_ line 10, from
```
set(INTEL_ROOT $ENV{${ProgramFilesx86}}/IntelSWTools/compilers_and_libraries/windows)
```
to 
```
set(INTEL_ROOT ${YOUR_MKI_INSTALLED_ROOT}/IntelSWTools/compilers_and_libraries/windows)
```

**Comment by iuming** [comment]
> Modify _VCPKG_ROOT/ports/intel-mkl/portfile.cmake_ line 10, from
> 
> ```
> set(INTEL_ROOT $ENV{${ProgramFilesx86}}/IntelSWTools/compilers_and_libraries/windows)
> ```
> 
> to
> 
> ```
> set(INTEL_ROOT ${YOUR_MKI_INSTALLED_ROOT}/IntelSWTools/compilers_and_libraries/windows)
> ```

Thank you very much, I have succeed install intel-mkl!

**Comment by MHumza3656** [comment]
For Linux I updated `ports/intel-mkl/portfile.cmake`
`set(INTEL_ROOT $ENV{${ProgramFilesx86}}/IntelSWTools/compilers_and_libraries/windows)`
To
`set(INTEL_ROOT /opt/intel)`
and it worked for me

**Comment by Forence1999** [comment]
> set(INTEL_ROOT /opt/intel)

Thank you! worked for me with some modifications.
 
Steps:
1. download oneAPI (the updated version of intel mkl) from https://www.intel.com/content/www/us/en/developer/tools/oneapi/onemkl-download.html?operatingsystem=linux&distributions=offline
2. install it (you can customize the installation path), and remeber it;
3. add  export MKLROOT=/your/installation/path/intel/oneapi/mkl/latest   to your env variable.
Note: 
1. the default path might be /opt/intel/oneapi/mkl/latest? I didn't check it.
2. include/mkl.h should be in the above folder. Make sure!

Reasons why this could work?
In the file ports/intel-mkl/portfile.cmake:
```
find_path(MKL_ROOT include/mkl.h
    PATHS
    $ENV{MKLROOT}
    ${INTEL_ROOT}/mkl
    $ENV{ONEAPI_ROOT}/mkl/latest
    ${ONEMKL_ROOT}
    DOC
    "Folder contains MKL")
```

try to find include/mkl.h in all these paths. Make sure this file could be found in one of them.
That's it~
