### ISSUE TITLE
[<cairo>] build failure

### ISSUE THREAD

**Issue by sumitkang** [microsoft/vcpkg#13073]
**Host Environment**
- OS:Windows
- Compiler: revision

**To Reproduce**
.\vcpkg install cairo:x64-windows

**Failure logs** 
;"SSL connect error"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:176 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_find_acquire_program.cmake:391 (vcpkg_download_distfile)
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:267 (vcpkg_find_acquire_program)
  ports/brotli/portfile.cmake:25 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:79 (include)

Error: Building package brotli:x64-windows failed with: BUILD_FAILED
[install-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/5111919/install-x64-windows-rel-out.log)

[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/5111923/install-x64-windows-dbg-out.log)

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Did you install other ports failed?

**Comment by sumitkang** [comment]
I only tried it out on this port only.

**Comment by sumitkang** [comment]
@LilyWangL  I only tried it out on this port only.

**Comment by LilyWangL** [comment]
Please provide the all log on powershell when you installing `brotli`.

**Comment by LilyWangL** [comment]
Pinging @sumitkang for response.

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
