### ISSUE TITLE
[bzip2] build failure

### ISSUE THREAD

**Issue by Cicas76** [microsoft/vcpkg#13071]
**Host Environment**
- OSX 10.15.6
- Version: 1.48.1
  Commit: 3dd905126b34dcd4de81fa624eb3a8cbe7485f13
  Date: 2020-08-19T17:09:41.484Z
  Electron: 7.3.2
  Chrome: 78.0.3904.130
  Node.js: 12.8.1
  V8: 7.8.279.23-electron.0
  OS: Darwin x64 19.6.0

**To Reproduce**
./vcpkg install boost-iostreams
or
./vcpkg install libarchive
or
./vcpkg install bzip2

**Failure logs** 
Error: Building package bzip2:x64-osx failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: bzip2:x64-osx
  Vcpkg version: 2020.06.15-unknownhash

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by NancyLi1013** [comment]
Hi @Cicas76 
Thanks for posting this issue.
I cannot reproduce this on my local machine.
Could you please provide the error log?

Thanks.

**Comment by NancyLi1013** [comment]
@Cicas76 
Please help confirm if this is the same as that in #13103.

**Comment by PhoebeHui** [comment]
It seems same issue with https://github.com/microsoft/vcpkg/issues/13103, I will resolve as duplicate to 13103, please reopen this issue if it's a diffrerent issue.
