### ISSUE TITLE
Question x64 triplet

### ISSUE THREAD

**Issue by wlemkows** [microsoft/vcpkg#1307]
Hi,
I am building all my projects only with x64 platform. 
The default one is x86, so every time I need to set my_project:**x64-windows** or set %VCPKG_DEFAULT_TRIPLET%.
My question is if there is a way to build my project without those both actions - without setting env var or :x64-windows? I've tried 
<VcpkgTriplet Condition="'$(Configuration)'=='x64'">x64-windows</VcpkgTriplet> but I am not sure how does it works, because there still is "x86" on the paths:
Building package nvml:**x86-windows**...
-- CURRENT_INSTALLED_DIR=C:/Users/Administrator/Desktop/vcpkg/installed/**x86-windows**
-- DOWNLOADS=C:/Users/Administrator/Desktop/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/Users/Administrator/Desktop/vcpkg/packages/**nvml_x86-windows**

And I got:
[...]
C:/Users/Administrator/Desktop/vcpkg/packages/nvml_x86-windows/bin/libpmemlog.dll
Expected x86, but was: x64

Found 2 error(s). Please correct the portfile:
    C:\Users\Administrator\Desktop\vcpkg\ports\nvml\portfile.cmake
-- Performing post-build validation done
Error: Building package nvml:x86-windows failed with: POST_BUILD_CHECKS_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: my_project:x86-windows
  Vcpkg version: 0.0.81-c5ac9898999b712b7bac2fbc497825882d5e9011

**Comment by ras0219-msft** [comment]
Hi @wlemkows,

First, to reconfirm your issue: you've added libraries to Vcpkg and they only support x64, which currently means that, by default, `vcpkg install nvml` will fail and you'd like to fix that?

The short answer is that (for now) you should add a check at the top of your portfile that will quickly tell the user that building for x86 is not allowed:
```cmake
if(NOT VCPKG_TARGET_ARCHITECTURE STREQUAL x64)
  message(FATAL_ERROR "NVML only supports the x64 architecture.")
endif()
```
We're working on some way to add it to the CONTROL file and detect it even earlier, but that isn't available yet.

Could you expand on why setting `%VCPKG_DEFAULT_TRIPLET%` doesn't work for you?

**Comment by wlemkows** [comment]
Currently I am using solution with FATAL_ERROR message, as you wrote and %VCPKG_DEFAULT_TRIPLET% works fine for me too.
My question was for third solution, to do not ask the user for architecture at all (because we supports only one x64). I thought that <VcpkgTriplet> tag in project can resolve the issue, but it won't work too, because CURRENT_INSTALLED_DIR is detected earlier and contains default x86 architecture, right?

**Comment by PhoebeHui** [comment]
I don't think we have a plan to support this now, please use %VCPKG_DEFAULT_TRIPLET% instead currently.
