### ISSUE TITLE
installing pcl package 

### ISSUE THREAD

**Issue by hamdy1999** [microsoft/vcpkg#13088]
**Environment**
- OS: [Windows 10]

**To Reproduce**
1. vcpkg install pcl
2. See error
Error: Building package boost-throw-exception:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-throw-exception:x86-windows
  Vcpkg version: 2020.06.15-nohash
Repro code when

**Comment by PhoebeHui** [comment]
@hamdy1999, could you attach failure logs?

I can't repro this issue locally.

Building package pcl[core]:x86-windows...
-- Downloading https://github.com/PointCloudLibrary/pcl/archive/f9f214f34a38d5bb67441140703a681c5d299906.tar.gz...
-- Extracting source F:/vcpkg/clean/downloads/PointCloudLibrary-pcl-f9f214f34a38d5bb67441140703a681c5d299906.tar.gz
-- Applying patch pcl_utils.patch
-- Applying patch pcl_config.patch
-- Applying patch use_flann_targets.patch
-- Applying patch boost-1.70.patch
-- Applying patch fix-link-libpng.patch
-- Applying patch remove-broken-targets.patch
-- Applying patch fix-check-sse.patch
-- Using source at F:/vcpkg/clean/buildtrees/pcl/src/1c5d299906-9d77bfae13.clean
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Installing: F:/vcpkg/clean/packages/pcl_x86-windows/share/pcl/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package pcl[core]:x86-windows... done
Installing package pcl[core]:x86-windows...
Installing package pcl[core]:x86-windows... done

**Comment by PhoebeHui** [comment]
Please reopen this issue with attaching the failure logs if it still be a problem for you.
