### ISSUE TITLE
 [C:\Program Files (x86)\vcpkg\toolsrc\src\vcpkg\build.cpp(1032)] with message:  no such file or directory 

### ISSUE THREAD

**Issue by fingerecho** [microsoft/vcpkg#13095]
**Host Environment**
- OS: windows10 Home
- Compiler: Microsoft Visual Studio 2019 [ Adding English pack]
-Terminal:   PowerShell 

**To Reproduce**
`git clone .....`
`./bootstrap-vcpkg.bat`
`.\vcpkg.exe intergrate install`
`.\vcpkg.exe install drogon`
`.\vcpkg.exe install trantor:x86-windows`

**Failure logs** 
PS C:\Program Files (x86)\vcpkg> .\vcpkg.exe install trantor:x86-windows                                                                   
 Computing installation plan...                                                                                                              
The following packages will be built and installed:                                                                                           
* openssl[core]:x86-windows                                                                                                                
 * openssl-windows[core]:x86-windows                                                                                                          
 trantor[core]:x86-windows                                                                                                               
Additional packages (*) will be modified to complete this operation.                                                                       
 Detecting compiler hash for triplet x86-windows...                                                                                         
 Starting package 1/3: openssl-windows:x86-windows                                                                                          
 Building package openssl-windows[core]:x86-windows...                                                                                      
 Using cached binary package: C:\Users\86175\AppData\Local\vcpkg/archives\78\78705e3dbbf1d0a697b5f87ffc51b860b926e779.zip                    
Failed at [C:\Program Files (x86)\vcpkg\toolsrc\src\vcpkg\build.cpp(1032)] with message:                                                    
no such file or directory       

PS C:\Program Files (x86)\vcpkg> ./vcpkg install drogon                                                                                    
Computing installation plan...
The following packages will be built and installed:
  * brotli[core]:x86-windows
    drogon[core]:x86-windows
  * libmariadb[core,openssl,zlib]:x86-windows
  * libpq[core,openssl,zlib]:x86-windows
  * openssl[core]:x86-windows
  * openssl-windows[core]:x86-windows
  * sqlite3[core]:x86-windows
  * trantor[core]:x86-windows
  * zlib[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x86-windows...
Starting package 1/9: brotli:x86-windows
Building package brotli[core]:x86-windows...
Could not locate cached archive: C:\Users\86175\AppData\Local\vcpkg/archives\95\9506e0df4b15dc899d035e5077eaa68ea6c044bb.zip
-- Downloading https://github.com/google/brotli/archive/v1.0.7.tar.gz...
-- Extracting source C:/Program Files (x86)/vcpkg/downloads/google-brotli-v1.0.7.tar.gz
-- Applying patch install.patch
-- Applying patch fix-arm-uwp.patch
-- Applying patch pkgconfig.patch
-- Using source at C:/Program Files (x86)/vcpkg/buildtrees/brotli/src/v1.0.7-c2af986dcd.clean
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Fixing pkgconfig file: C:/Program Files (x86)/vcpkg/packages/brotli_x86-windows/debug/lib/pkgconfig/libbrotlicommon.pc
-- Fixing pkgconfig file: C:/Program Files (x86)/vcpkg/packages/brotli_x86-windows/debug/lib/pkgconfig/libbrotlidec.pc
-- Fixing pkgconfig file: C:/Program Files (x86)/vcpkg/packages/brotli_x86-windows/debug/lib/pkgconfig/libbrotlienc.pc
-- Fixing pkgconfig file: C:/Program Files (x86)/vcpkg/packages/brotli_x86-windows/lib/pkgconfig/libbrotlicommon.pc
-- Fixing pkgconfig file: C:/Program Files (x86)/vcpkg/packages/brotli_x86-windows/lib/pkgconfig/libbrotlidec.pc
-- Fixing pkgconfig file: C:/Program Files (x86)/vcpkg/packages/brotli_x86-windows/lib/pkgconfig/libbrotlienc.pc
CMake Error at scripts/cmake/vcpkg_fixup_pkgconfig.cmake:231 (message):
  Unhandled string "-LC:/Program\ Files\
  (x86)/vcpkg/packages/brotli_x86-windows/lib" was found! If it is a system
  library use the SYSTEM_LIBRARIES parameter for the vcpkg_fixup_pkgconfig
  call! Otherwise, correct the *.pc file or add the case to
  vcpkg_fixup_pkgconfig
Call Stack (most recent call first):
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:294 (vcpkg_fixup_pkgconfig_check_files)
  ports/brotli/portfile.cmake:25 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:79 (include)

Error: Building package brotli:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: brotli:x86-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.

**Additional context**
succeed in installing other package such as `jsoncpp`, but failed in installing some packages like `drogon` or `trantor`.
I installed `trantor` package with `./vcpkg.exe install trantor:x86-windows`, but I spared too much time to download resource from http. So I downloaded the trantor resource, then copied the files to the directory downloads/temp  , however, it still downloaded from http, So I remove the directory  C:\Users\86175\AppData\Local\vcpkg/archives , then remake the directory with `mkdir -p  C:\Users\86175\AppData\Local\vcpkg/archives\78` , copied the .zip file that I download with downloading tools like `XunLei` to the directory  `C:\Users\86175\AppData\Local\vcpkg/archives\78`, then I installed it with `./vcpkg.exe install trantor:x86-windows` , the error outputed.
When I installed the `drogon` package with `./vcpkg.exe install drogon`, it still spared too much time. However, it downloaded successfully.  But output the error-log like thats.

**Comment by fingerecho** [comment]
What is the situation?

**Comment by fingerecho** [comment]
@NancyLi1013, 您这边是什么情况呢？

**Comment by NancyLi1013** [comment]
Hi @fingerecho 
Thanks for posting this issue.
For issue caused by `opnessl-windows`,

**Comment by fingerecho** [comment]
Thank you, I got it !
