### ISSUE TITLE
[Cygwin] It doesnt recognise compiler

### ISSUE THREAD

**Issue by jiri-otoupal** [microsoft/vcpkg#13096]
**Host Environment**
- OS: Windows 10
- Compiler: Cygwin

**To Reproduce**
`vcpkg install berkeleydb:x64-windows`

**Failure logs** 
[DEBUG]     Working Directory: C:/Users/jiri-/Downloads/vcpkg-master/buildtrees/detect_compiler/x64-windows-rel
[DEBUG]     Error code: 1
[DEBUG]     See logs for more information:
[DEBUG]       C/Users/jiri-/Downloads/vcpkg-master/buildtrees/detect_compiler/config-x64-windows-rel-out.log
[DEBUG]       C/Users/jiri-/Downloads/vcpkg-master/buildtrees/detect_compiler/config-x64-windows-rel-err.log
[DEBUG]
[DEBUG] Call Stack (most recent call first):
[DEBUG]   C:/Users/jiri-/Downloads/vcpkg-master/scripts/cmake/vcpkg_configure_cmake.cmake:319 (vcpkg_execute_required_process)
[DEBUG]   C:/Users/jiri-/Downloads/vcpkg-master/scripts/detect_compiler/portfile.cmake:18 (vcpkg_configure_cmake)
[DEBUG]   C:/Users/jiri-/Downloads/vcpkg-master/scripts/ports.cmake:79 (include)
[DEBUG]
[DEBUG]
[DEBUG] cmd_execute_and_stream_data() returned 1 after  3799483 us
[DEBUG]
[DEBUG] Compiler information tracking can be disabled by passing --feature-flags=-compilertracking
Error occured while detecting compiler information. Pass `--debug` for more information.
[DEBUG] C:\Users\jiri-\Downloads\vcpkg-master\toolsrc\src\vcpkg\build.cpp(525)

**Additional context**

**Comment by PhoebeHui** [comment]
@jiri-otoupal, could you attach failure log:

 C/Users/jiri-/Downloads/vcpkg-master/buildtrees/detect_compiler/config-x64-windows-rel-out.log
C/Users/jiri-/Downloads/vcpkg-master/buildtrees/detect_compiler/config-x64-windows-rel-err.log

I didn't repro this issue with msvc toolset, it built successfully for me.

**Comment by jiri-otoupal** [comment]
[config-x64-windows-rel-err.log](https://github.com/microsoft/vcpkg/files/5117008/config-x64-windows-rel-err.log)
[config-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/5117009/config-x64-windows-rel-out.log)

**Comment by PhoebeHui** [comment]
It seems the cygwin set up issue, not related to the port. I also installed cygwin and tried to build this port, Everything works.

What compiler version do you use? you might need set up the enviroment again.

Failures:
```
CMake Error at /usr/share/cmake-3.17.3/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "/usr/bin/cc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /cygdrive/c/Users/jiri-/Downloads/vcpkg-master/buildtrees/detect_compiler/x64-windows-rel/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/cygdrive/e/VisualStudio2019/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe cmTC_6b4cc && [1/2] Building C object CMakeFiles/cmTC_6b4cc.dir/testCCompiler.c.o
    FAILED: CMakeFiles/cmTC_6b4cc.dir/testCCompiler.c.o 
    /usr/bin/cc   /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP -o CMakeFiles/cmTC_6b4cc.dir/testCCompiler.c.o   -c testCCompiler.c
    CreateProcess failed: The system cannot find the file specified.
    ninja: build stopped: subcommand failed.
    
  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:13 (enable_language)
```
I don't use cygwin, has no work experience, I have vs2019 isntalled. share my config log:
```
[1/2] cmd /c "cd .. && "C:/cygwin64/home/phoebe/vcpkg/downloads/tools/cmake-3.17.2-windows/cmake-3.17.2-win32-x86/bin/cmake.exe" "C:/cygwin64/home/phoebe/vcpkg/buildtrees/berkeleydb/src/db-4-87fc9a5730.clean" "-DCMAKE_MAKE_PROGRAM=C:/cygwin64/home/phoebe/vcpkg/downloads/tools/ninja/ninja-1.10.0/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/cygwin64/home/phoebe/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v142" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/cygwin64/home/phoebe/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_TARGET_ARCHITECTURE=x64" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=C:/cygwin64/home/phoebe/vcpkg" "-D_VCPKG_INSTALLED_DIR=C:/cygwin64/home/phoebe/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=C:/cygwin64/home/phoebe/vcpkg/packages/berkeleydb_x64-windows""
-- The C compiler identification is MSVC 19.26.28806.0
-- The CXX compiler identification is MSVC 19.26.28806.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
...
```

**Comment by jiri-otoupal** [comment]
Cygwin is properly installed. Even the path to compiler is.
I will not reinstall my entire windows!

**Comment by jiri-otoupal** [comment]
I have installed visual studio 2019 too
and still vcpkg cant install anything

**Comment by jiri-otoupal** [comment]
Currently it throws this : [DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Using vcpkg-root: C:\vcpkg
[DEBUG] Using installed-root: C:\vcpkg\installed
[DEBUG] Using buildtrees-root: C:\vcpkg\buildtrees
[DEBUG] Using downloads-root: C:\vcpkg\downloads
[DEBUG] Using packages-root: C:\vcpkg\packages
[DEBUG] Using scripts-root: C:\vcpkg\scripts
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
[DEBUG] Default binary cache path is: C:\Users\jiri-\AppData\Local\vcpkg/archives
Computing installation plan...
[DEBUG] Found path: C:\cygwin64\bin/cmake.exe
[DEBUG] Found path: C:\Program Files\CMake\bin/cmake.exe
[DEBUG] CreateProcessW("C:\cygwin64\bin/cmake.exe" --version)
[DEBUG] cmd_execute_and_stream_data() returned 0 after    34766 us
[DEBUG] CreateProcessW("C:\cygwin64\bin/cmake.exe" -DVCPKG_ROOT_DIR=C:/vcpkg -DPACKAGES_DIR=C:/vcpkg/packages -DBUILDTREES_DIR=C:/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=C:/vcpkg/installed -DDOWNLOADS=C:/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "C:\vcpkg\buildtrees\0.vcpkg_tags.cmake")
[DEBUG] cmd_execute_and_stream_data() returned 0 after    63051 us
The following packages will be built and installed:
    berkeleydb[core]:x64-windows
[DEBUG] CreateProcessW("C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -all -prerelease -legacy -products * -format xml)
[DEBUG] cmd_execute_and_stream_data() returned 0 after    29137 us
Detecting compiler hash for triplet x64-windows...
[DEBUG] Found path: C:\Program Files\Git\cmd/git.exe
[DEBUG] CreateProcessW("C:\vcpkg\downloads\tools\git-2.26.2-1-windows\mingw32\bin\git.exe" --version)
[DEBUG] cmd_execute_and_stream_data() returned 0 after    24042 us
[DEBUG] CreateProcessW(cmd /c ""E:\VisualStudio2019\VC\Auxiliary\Build\vcvarsall.bat" -vcvars_ver=14.2 amd64   2>&1 <NUL" & echo cdARN4xjKueKScMy9C6H& set)
[DEBUG] cmd_execute_and_stream_data() returned 0 after  1332068 us
[DEBUG] CreateProcessW("C:\cygwin64\bin/cmake.exe" -DCURRENT_PORT_DIR=C:/vcpkg/scripts/detect_compiler -DCURRENT_BUILDTREES_DIR=C:/vcpkg/buildtrees/detect_compiler -DCURRENT_PACKAGES_DIR=C:/vcpkg/packages/detect_compiler_x64-windows -DCMD=BUILD -DTARGET_TRIPLET=x64-windows "-DTARGET_TRIPLET_FILE=C:\vcpkg\triplets\x64-windows.cmake" -DVCPKG_PLATFORM_TOOLSET=v142 -DDOWNLOADS=C:/vcpkg/downloads -DVCPKG_CONCURRENCY=9 -DGIT=C:/vcpkg/downloads/tools/git-2.26.2-1-windows/mingw32/bin/git.exe -DVCPKG_ROOT_DIR=C:/vcpkg -DPACKAGES_DIR=C:/vcpkg/packages -DBUILDTREES_DIR=C:/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=C:/vcpkg/installed -DDOWNLOADS=C:/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "C:\vcpkg\scripts\ports.cmake")
[DEBUG] -- Configuring x64-windows-rel
[DEBUG] CMake Error at C:/vcpkg/scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
[DEBUG]     Command failed: /usr/bin/cmake.exe C:/vcpkg/scripts/detect_compiler -DCMAKE_MAKE_PROGRAM=C:/vcpkg/downloads/tools/ninja/1.10.0-linux/ninja -DBUILD_SHARED_LIBS=ON -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/vcpkg/scripts/toolchains/windows.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=v142 -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_TARGET_ARCHITECTURE=x64 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -D_VCPKG_ROOT_DIR=C:/vcpkg -D_VCPKG_INSTALLED_DIR=C:/vcpkg/installed -DVCPKG_MANIFEST_INSTALL=OFF -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=C:/vcpkg/packages/detect_compiler_x64-windows
[DEBUG]     Working Directory: C:/vcpkg/buildtrees/detect_compiler/x64-windows-rel
[DEBUG]     Error code: 1
[DEBUG]     See logs for more information:
[DEBUG]       C/vcpkg/buildtrees/detect_compiler/config-x64-windows-rel-out.log
[DEBUG]       C/vcpkg/buildtrees/detect_compiler/config-x64-windows-rel-err.log
[DEBUG]
[DEBUG] Call Stack (most recent call first):
[DEBUG]   C:/vcpkg/scripts/cmake/vcpkg_configure_cmake.cmake:319 (vcpkg_execute_required_process)
[DEBUG]   C:/vcpkg/scripts/detect_compiler/portfile.cmake:18 (vcpkg_configure_cmake)
[DEBUG]   C:/vcpkg/scripts/ports.cmake:79 (include)
[DEBUG]
[DEBUG]
[DEBUG] cmd_execute_and_stream_data() returned 1 after   463702 us
[DEBUG]
[DEBUG] Compiler information tracking can be disabled by passing --feature-flags=-compilertracking
Error occurred while detecting compiler information. Pass `--debug` for more information.
[DEBUG] C:\vcpkg\toolsrc\src\vcpkg\build.cpp(527)
[DEBUG] Exiting after 1979106 us (1972619 us)

**Comment by PhoebeHui** [comment]
@jiri-otoupal, does the failure same as before in  C/vcpkg/buildtrees/detect_compiler/config-x64-windows-rel-err.log?

**Comment by PhoebeHui** [comment]
It might due to cmake installed by cygwin64, could you remove it, and try again?
[DEBUG] Found path: C:\cygwin64\bin/cmake.exe
[DEBUG] Found path: C:\Program Files\CMake\bin/cmake.exe
[DEBUG] CreateProcessW("C:\cygwin64\bin/cmake.exe" --version)

**Comment by PhoebeHui** [comment]
@jiri-otoupal, does this still be a problem for you?

**Comment by PhoebeHui** [comment]
@jiri-otoupal, please reopen this issue if it still be a problem for you.
