### ISSUE TITLE
[OpenCV] update to 4.4

### ISSUE THREAD

**Issue by MohiuddinM** [microsoft/vcpkg#13098]
Library name: OpenCV

New version number: 4.4.0

**Comment by JackBoosY** [comment]
cc @cenit feel free to update OCV to 4.4 : )

**Comment by cenit** [comment]
@JackBoosY https://github.com/microsoft/vcpkg/pull/14118
Sorry for being almost absent. Too much work recently and got overwhelmed by deadlines.
Before #14118 i still hope #12785 can be finished and merged, so that in future we have automatic checks for OpenCV and its many features in CI!
