### ISSUE TITLE
[FFmpeg] build failure，ERROR: libx264 not found

### ISSUE THREAD

**Issue by patui** [microsoft/vcpkg#13099]
CMD Run:

`D:\PublicLib\vcpkg>vcpkg install ffmpeg[gpl,nonfree,version3,mp3lame,fdk-aac,x264,x265,iconv,bzip2,zlib]:x64-windows`

My-Computer

```
D:\PublicLib\vcpkg>vcpkg list
...
...
x264:x64-windows                                   157-303c484ec... x264 is a free software library and application ...
x265:x64-windows                                   3.4              x265 is a H.265 / HEVC video encoder application...
zlib:x64-windows                                   1.2.11#9         A compression library
```

RUN Result:

D:\PublicLib\vcpkg>vcpkg install ffmpeg[gpl,nonfree,version3,mp3lame,fdk-aac,x264,x265,iconv,bzip2,zlib]:x64-windows
Computing installation plan...
The following packages will be built and installed:
    ffmpeg[avcodec,avdevice,avfilter,avformat,avresample,bzip2,core,fdk-aac,gpl,iconv,mp3lame,nonfree,postproc,swresample,swscale,version3,x264,x265,zlib]:x64-windows
Detecting compiler hash for triplet x64-windows...
Starting package 1/1: ffmpeg:x64-windows
Building package ffmpeg[avcodec,avdevice,avfilter,avformat,avresample,bzip2,core,fdk-aac,gpl,iconv,mp3lame,nonfree,postproc,swresample,swscale,version3,x264,x265,zlib]:x64-windows...
Could not locate cached archive: C:\Users\mypoi\AppData\Local\vcpkg/archives\ab\ab72643f845c86b4b5abe5d90fd16fe485904f51.zip
-- Using cached D:/PublicLib/vcpkg/downloads/ffmpeg-ffmpeg-n4.2.tar.gz
-- Cleaning sources at D:/PublicLib/vcpkg/buildtrees/ffmpeg/src/n4.2-2f6d2343f6.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/PublicLib/vcpkg/downloads/ffmpeg-ffmpeg-n4.2.tar.gz
-- Applying patch 0001-create-lib-libraries.patch
-- Applying patch 0003-fix-windowsinclude.patch
-- Applying patch 0004-fix-debug-build.patch
-- Applying patch 0005-fix-libvpx-linking.patch
-- Applying patch 0006-fix-StaticFeatures.patch
-- Applying patch 0007-fix-lib-naming.patch
-- Applying patch 0008-Fix-wavpack-detection.patch
-- Applying patch 0009-Fix-fdk-detection.patch
-- Applying patch 0010-Fix-x264-detection.patch
-- Applying patch 0011-Fix-x265-detection.patch
-- Applying patch 0012-Fix-ssl-110-detection.patch
-- Using source at D:/PublicLib/vcpkg/buildtrees/ffmpeg/src/n4.2-2f6d2343f6.clean
-- Acquiring MSYS Packages from D:/PublicLib/vcpkg/downloads/tools/msys2-20200812...
-- Acquiring MSYS Packages... OK
-- Building Options: --enable-asm --enable-yasm --disable-doc --enable-debug --enable-runtime-cpudetect --enable-nonfree --enable-gpl --enable-version3 --disable-ffmpeg --disable-ffplay --disable-ffprobe --enable-avcodec --enable-avdevice --enable-avformat --enable-avfilter --enable-postproc --enable-swresample --enable-swscale --enable-avresample --disable-avisynth --enable-bzlib --enable-iconv --enable-libfdk-aac --disable-lzma --enable-libmp3lame --disable-cuda --disable-nvenc --disable-nvdec  --disable-cuvid --disable-opencl --disable-openssl --disable-libopus --disable-sdl2 --disable-libsnappy --disable-libsoxr --disable-libspeex --disable-libtheora --disable-libvorbis --disable-libvpx --disable-libwavpack --enable-libx264 --enable-libx265 --enable-zlib  --disable-static --enable-shared --extra-cflags=-DHAVE_UNISTD_H=0
-- Building Release Options:  --extra-cflags=-MD --extra-cxxflags=-MD
-- Building ffmpeg for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: D:/PublicLib/vcpkg/downloads/tools/msys2-20200812/msys64/usr/bin/bash.exe --noprofile --norc D:/PublicLib/vcpkg/ports/ffmpeg\build.sh D:/PublicLib/vcpkg/buildtrees/ffmpeg/x64-windows-rel D:/PublicLib/vcpkg/buildtrees/ffmpeg/src/n4.2-2f6d2343f6.clean D:/PublicLib/vcpkg/packages/ffmpeg_x64-windows "--enable-asm --enable-yasm --disable-doc --enable-debug --enable-runtime-cpudetect --enable-nonfree --enable-gpl --enable-version3 --disable-ffmpeg --disable-ffplay --disable-ffprobe --enable-avcodec --enable-avdevice --enable-avformat --enable-avfilter --enable-postproc --enable-swresample --enable-swscale --enable-avresample --disable-avisynth --enable-bzlib --enable-iconv --enable-libfdk-aac --disable-lzma --enable-libmp3lame --disable-cuda --disable-nvenc --disable-nvdec  --disable-cuvid --disable-opencl --disable-openssl --disable-libopus --disable-sdl2 --disable-libsnappy --disable-libsoxr --disable-libspeex --disable-libtheora --disable-libvorbis --disable-libvpx --disable-libwavpack --enable-libx264 --enable-libx265 --enable-zlib  --disable-static --enable-shared --extra-cflags=-DHAVE_UNISTD_H=0  --extra-cflags=-MD --extra-cxxflags=-MD"
    Working Directory: D:/PublicLib/vcpkg/buildtrees/ffmpeg/x64-windows-rel
    Error code: 1
    See logs for more information:
      D:\PublicLib\vcpkg\buildtrees\ffmpeg\build-x64-windows-rel-out.log

Call Stack (most recent call first):
  ports/ffmpeg/portfile.cmake:394 (vcpkg_execute_required_process)
  scripts/ports.cmake:79 (include)

Error: Building package ffmpeg:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: ffmpeg:x64-windows
  Vcpkg version: 2020.06.15-nohash

### Log:

```
build-x64-windows-rel-out.log

=== CONFIGURING ===
ERROR: libx264 not found

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.

```

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/12896.
