### ISSUE TITLE
How do I add new port of header only?

### ISSUE THREAD

**Issue by zhangdexin** [microsoft/vcpkg#13093]
I want to add new port of no CMakeLists.txt and header only?

**Comment by zhangdexin** [comment]
It work. I have other question, for CMakeLists.txt has include dir, How can do?
INCLUDE_DIRECTORIES(STSTEM third/msgpack/include/)

**Comment by LilyWangL** [comment]
@zhangdexin Thanks for posting this issue. You can refer to `asio` and `autobahn`. All of them are header-only library.

**Comment by PhoebeHui** [comment]
@zhangdexin, please reopen this issue if it still be a question for you.
