### ISSUE TITLE
[x265] x265:x64-windows-rel build failure, cpu overload -> pc shutdown

### ISSUE THREAD

**Issue by DrGul** [microsoft/vcpkg#13109]
**Host Environment**
- OS: Windows 10
- Compiler: Some VS17 one

**To Reproduce**
`.\vcpkg install x265:x64-windows`

**Failure logs** 
```
Detecting compiler hash for triplet x64-windows...
Starting package 1/11: x265:x64-windows
Building package x265[core]:x64-windows...
Could not locate cached archive: C:\Users\nilsj\AppData\Local\vcpkg/archives\05\05c597ca5b3784fcd893848ddd12f7b0a3816b02.zip
-- Using cached C:/Dev/vcpkg/downloads/videolan-x265-07295ba7ab551bb9c1580fdaee3200f1b45711b7.tar.gz
-- Cleaning sources at C:/Dev/vcpkg/buildtrees/x265/src/f1b45711b7-44018d5a0c.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Dev/vcpkg/downloads/videolan-x265-07295ba7ab551bb9c1580fdaee3200f1b45711b7.tar.gz
-- Applying patch disable-install-pdb.patch
-- Using source at C:/Dev/vcpkg/buildtrees/x265/src/f1b45711b7-44018d5a0c.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
```

**Additional context**
VCPKG starts several compilers and the CPU usage immediately shoots of to 100% when it's building x64-windows-release. Soon there after the computer shuts down. I suppose there could be some issue with my PC, but seems strange to me that the processor usage would be that high.

**Comment by JackBoosY** [comment]
This proves that the compiler completely uses the resources of your computer.
If you don’t like it, you can replace `vcpkg_install_cmake()` to  `vcpkg_install_cmake(DISABLE_PARALLEL)` in _VCPKG_ROOT/ports/x265/portfile.cmake_ line 31 then try again.

**Comment by DrGul** [comment]
I suppose it's good that the resource are being put to work. However unfortunate when pc shuts down each time.

Thanks for the suggestion, resolved the issue.

**Comment by JackBoosY** [comment]
@DrGul You should check your cooling system.
