### ISSUE TITLE
[sqlitecpp] build failure

### ISSUE THREAD

**Issue by remz1337** [microsoft/vcpkg#13102]
**Describe the bug**
Adding the library as a dependency (without any usage in the code) prevents building the project

**Environment**
- OS: Windows 10
- Compiler: MSVC 2019

**To Reproduce**
1. Install package `./vcpkg install sqlitecpp`
2. Add package to CMakeList:
`find_package(SQLiteCpp CONFIG REQUIRED)`
`target_link_libraries(main PRIVATE SQLiteCpp)`

My program doesn't build anymore.

**Expected behavior**
Build successfully

**Failure logs** 
`.../vcpkg/scripts/buildsystems/vcpkg.cmake:349 (_add_executable):  Target "main" links to target "unofficial::sqlite3::sqlite3" but the target was not found.  Perhaps a find_package() call is missing for an IMPORTED target, or an ALIAS target is missing?`

**Comment by PhoebeHui** [comment]
@remz1337, thanks for reporting this issue!

I have summited PR #13108 to fix this issue.
