### ISSUE TITLE
bzip2 build failure

### ISSUE THREAD

**Issue by Luisrogo01** [microsoft/vcpkg#13103]
**Host Environment**
- OS: Windows
- Compiler: 10

**To Reproduce**
.\vcpkg install bzip2

**Failure logs** 
Computing installation plan...
The following packages will be built and installed:
    bzip2[core]:x86-windows
Detecting compiler hash for triplet x86-windows...
Starting package 1/1: bzip2:x86-windows
Building package bzip2[core]:x86-windows...
Could not locate cached archive: C:\Users\Luis\AppData\Local\vcpkg/archives\8d\8d6349887daee5b8b5feed1c1b0c52473567e27f.zip
-- Using cached C:/Program Files/Dev/vcpkg/vcpkg/downloads/bzip2-1.0.6.tar.gz
-- Cleaning sources at C:/Program Files/Dev/vcpkg/vcpkg/buildtrees/bzip2/src/1.0.6-8838f21f8e.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Program Files/Dev/vcpkg/vcpkg/downloads/bzip2-1.0.6.tar.gz
-- Applying patch fix-import-export-macros.patch
-- Applying patch fix-windows-include.patch
-- Using source at C:/Program Files/Dev/vcpkg/vcpkg/buildtrees/bzip2/src/1.0.6-8838f21f8e.clean
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Fixing pkgconfig file: C:/Program Files/Dev/vcpkg/vcpkg/packages/bzip2_x86-windows/lib/pkgconfig/bzip2.pc
-- CHECK_LIB_bz2_RELEASE:CHECK_LIB_bz2_RELEASE-NOTFOUND
CMake Error at scripts/cmake/vcpkg_fixup_pkgconfig.cmake:232 (message):
  Library "bz2" was not found! If it is a system library use the
  SYSTEM_LIBRARIES parameter for the vcpkg_fixup_pkgconfig call! Otherwise,
  correct the *.pc file
Call Stack (most recent call first):
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:298 (vcpkg_fixup_pkgconfig_check_files)
  ports/bzip2/portfile.cmake:49 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:79 (include)

Error: Building package bzip2:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: bzip2:x86-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.
**Additional context**
I tried to install pcl library but it keeps failling with this error. I updated to delete vcpkg and re-installed it to the latest versiona and still doesnt work. Could you guys help me ? please

**Comment by NancyLi1013** [comment]
Hi @Luisrogo01 
Thanks for posting this issue.
Sorry, I cannot reproduce this on my local. It seems something to be related with `vcpkg_fixup_pkgconfig.cmake`.
Need further investigation.

Related issue #13105.

**Comment by Hoikas** [comment]
I just built the bzip2 package successfully on the AppVeyor image that is failing to build zlib in #13105.
