### ISSUE TITLE
[New Port Request] likwid

### ISSUE THREAD

**Issue by vmiheer** [microsoft/vcpkg#13116]
Library name: likwid

Library description: Likwid is a simple to install and use toolsuite of command line applications for performance oriented programmers. It works for Intel, AMD, ARMv8 and POWER9 processors on the Linux operating system. There is support for ARMv7 and POWER8 but there is currently no test machine in our hands to test them properly.

Source repository URL: https://github.com/RRZE-HPC/likwid

Project homepage (if different from the source repository): https://hpc.fau.de/research/tools/likwid/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
