### ISSUE TITLE
[FFmpeg] Add New Feature(libass,libfreetype,fontconfig)

### ISSUE THREAD

**Issue by patui** [microsoft/vcpkg#13111]
Video player need  these Feature

libass 
` "--enable-libass --enable-filter=subtitles"`

libfreetype
`  "--enable-filter=drawtext --enable-libfreetype --enable-muxer=ass --enable-demuxer=ass --enable-muxer=srt --enable-demuxer=srt --enable-muxer=webvtt --enable-demuxer=webvtt --enable-encoder=ass --enable-decoder=ass --enable-encoder=srt --enable-decoder=srt --enable-encoder=webvtt --enable-decoder=webvtt"`

fontconfig
`"--enable-fontconfig"`

FFmpeg Official version
![offical_version](https://user-images.githubusercontent.com/3607466/91039608-70526e80-e63f-11ea-85b0-8b9c5f1b5332.jpg)

**Comment by patui** [comment]
In addition, before the software upgrade, can you give a temporary solution, such as: how do I add these features myself, and how do I deal with such problems in the future?

**Comment by ASxa86** [comment]
I would also like to add that png encoding doesn't appear to be available through the CONTROL file as well. For my project I ended up having to manually add --enable-libfreetype, --enable-encoder=png and --enable-decoder=png

**Comment by cenmmy** [comment]
i want to use drawtext filter in my project, but i don't kown how to add option --enable-libfreetype
