### ISSUE TITLE
How do I find a shaderc package?

### ISSUE THREAD

**Issue by daemyung** [microsoft/vcpkg#13110]
I have installed shaderc but there is no instructions... Usually when I install one library, vcpkg give tips like below
```
find_package(glfw3 CONFIG REQUIRED)
target_link_libraries(targetPRIVATE glfw3)
```
However shaderc doesn't give any instruction. It's installed but there is no .cmake files.
Could you help how can I find shaderc library with vcpkg?

**Comment by NancyLi1013** [comment]
Hi @daemyung 
Thanks for posting this issue.
Since there are no CMake Configs and Targets files for`shaderc `, we cannot find the port via `find_package()`.

You can use `find_library() `and `find_path()` to find `shaderc `.

**Comment by daemyung** [comment]
Thanks for your answer. Do you have a plan to make patch to support ```find_pacakge()```?

**Comment by NancyLi1013** [comment]
The upstream doesn't support this. If you have the demand, it might be better to file an issue on upstream.

Thanks.

**Comment by daemyung** [comment]
Thanks.
