### ISSUE TITLE
[protobuf:x86-atmos-md] build failure

### ISSUE THREAD

**Issue by brazhenko** [microsoft/vcpkg#13113]
**Host Environment**
- Win10
- MSVC 19.15

**To Reproduce**
`./vcpkg install --triplet x86-atmos-md protobuf`

**Failure logs** 

         libprotobuf.dir\Debug\json_objectwriter.obj
         libprotobuf.dir\Debug\json_stream_parser.obj
         libprotobuf.dir\Debug\object_writer.obj
         libprotobuf.dir\Debug\proto_writer.obj
         libprotobuf.dir\Debug\protostream_objectsource.obj
         libprotobuf.dir\Debug\protostream_objectwriter.obj
         libprotobuf.dir\Debug\type_info.obj
         libprotobuf.dir\Debug\type_info_test_helper.obj
         libprotobuf.dir\Debug\utility.obj
         libprotobuf.dir\Debug\json_util.obj
         libprotobuf.dir\Debug\message_differencer.obj
         libprotobuf.dir\Debug\time_util.obj
         libprotobuf.dir\Debug\type_resolver_util.obj
         libprotobuf.dir\Debug\wire_format.obj
         libprotobuf.dir\Debug\wrappers.pb.obj
     4>LINK : warning LNK4068: /MACHINE not specified; defaulting to X64 [C:\Users\BRAZHENKO-AS\src\atms-vcpkg-n\buildtrees\protobuf\x86-windows-atmos-md-dbg\libprotobuf.vcxproj]
     4>libprotobuf.dir\Debug\any_lite.obj : fatal error LNK1112: module machine type 'x86' conflicts with target machine type 'x64' [C:\Users\BRAZHENKO-AS\src\atms-vcpkg-n\buildtrees\protobuf\x86-windows-atmos-md-dbg\libprotobuf.vcxproj]
     4>Сборка проекта "C:\Users\BRAZHENKO-AS\src\atms-vcpkg-n\buildtrees\protobuf\x86-windows-atmos-md-dbg\libprotobuf.vcxproj" завершена (целевые объекты по умолчанию) с ошибкой.
     2>Сборка проекта "C:\Users\BRAZHENKO-AS\src\atms-vcpkg-n\buildtrees\protobuf\x86-windows-atmos-md-dbg\ALL_BUILD.vcxproj" завершена (целевые объекты по умолчанию) с ошибкой.
     1>Сборка проекта "C:\Users\BRAZHENKO-AS\src\atms-vcpkg-n\buildtrees\protobuf\x86-windows-atmos-md-dbg\install.vcxproj" завершена (целевые объекты по умолчанию) с ошибкой.

Ошибка сборки.

       "C:\Users\BRAZHENKO-AS\src\atms-vcpkg-n\buildtrees\protobuf\x86-windows-atmos-md-dbg\install.vcxproj" (целевой объект по умолчанию) (1) ->
       "C:\Users\BRAZHENKO-AS\src\atms-vcpkg-n\buildtrees\protobuf\x86-windows-atmos-md-dbg\ALL_BUILD.vcxproj" (целевой объект по умолчанию) (2) ->
       "C:\Users\BRAZHENKO-AS\src\atms-vcpkg-n\buildtrees\protobuf\x86-windows-atmos-md-dbg\libprotobuf-lite.vcxproj" (целевой объект по умолчанию) (6) ->
       (Lib конечный объект) -> 
         LINK : warning LNK4068: /MACHINE not specified; defaulting to X64 [C:\Users\BRAZHENKO-AS\src\atms-vcpkg-n\buildtrees\protobuf\x86-windows-atmos-md-dbg\libprotobuf-lite.vcxproj]

       "C:\Users\BRAZHENKO-AS\src\atms-vcpkg-n\buildtrees\protobuf\x86-windows-atmos-md-dbg\install.vcxproj" (целевой объект по умолчанию) (1) ->
       "C:\Users\BRAZHENKO-AS\src\atms-vcpkg-n\buildtrees\protobuf\x86-windows-atmos-md-dbg\ALL_BUILD.vcxproj" (целевой объект по умолчанию) (2) ->
       "C:\Users\BRAZHENKO-AS\src\atms-vcpkg-n\buildtrees\protobuf\x86-windows-atmos-md-dbg\libprotobuf.vcxproj" (целевой объект по умолчанию) (4) ->
         LINK : warning LNK4068: /MACHINE not specified; defaulting to X64 [C:\Users\BRAZHENKO-AS\src\atms-vcpkg-n\buildtrees\protobuf\x86-windows-atmos-md-dbg\libprotobuf.vcxproj]

       "C:\Users\BRAZHENKO-AS\src\atms-vcpkg-n\buildtrees\protobuf\x86-windows-atmos-md-dbg\install.vcxproj" (целевой объект по умолчанию) (1) ->
       "C:\Users\BRAZHENKO-AS\src\atms-vcpkg-n\buildtrees\protobuf\x86-windows-atmos-md-dbg\ALL_BUILD.vcxproj" (целевой объект по умолчанию) (2) ->
       "C:\Users\BRAZHENKO-AS\src\atms-vcpkg-n\buildtrees\protobuf\x86-windows-atmos-md-dbg\libprotobuf-lite.vcxproj" (целевой объект по умолчанию) (6) ->
       (Lib конечный объект) -> 
         libprotobuf-lite.dir\Debug\any_lite.obj : fatal error LNK1112: module machine type 'x86' conflicts with target machine type 'x64' [C:\Users\BRAZHENKO-AS\src\atms-vcpkg-n\buildtrees\protobuf\x86-windows-atmos-md-dbg\libprotobuf-lite.vcxproj]

       "C:\Users\BRAZHENKO-AS\src\atms-vcpkg-n\buildtrees\protobuf\x86-windows-atmos-md-dbg\install.vcxproj" (целевой объект по умолчанию) (1) ->
       "C:\Users\BRAZHENKO-AS\src\atms-vcpkg-n\buildtrees\protobuf\x86-windows-atmos-md-dbg\ALL_BUILD.vcxproj" (целевой объект по умолчанию) (2) ->
       "C:\Users\BRAZHENKO-AS\src\atms-vcpkg-n\buildtrees\protobuf\x86-windows-atmos-md-dbg\libprotobuf.vcxproj" (целевой объект по умолчанию) (4) ->
         libprotobuf.dir\Debug\any_lite.obj : fatal error LNK1112: module machine type 'x86' conflicts with target machine type 'x64' [C:\Users\BRAZHENKO-AS\src\atms-vcpkg-n\buildtrees\protobuf\x86-windows-atmos-md-dbg\libprotobuf.vcxproj]

    Предупреждений: 2
    Ошибок: 2

Прошло времени 00:00:57.66

[install-x86-windows-atmos-md-dbg-out.log](https://github.com/microsoft/vcpkg/files/5118380/install-x86-windows-atmos-md-dbg-out.log)

**Comment by JackBoosY** [comment]
```
libprotobuf-lite.dir\Debug\any_lite.obj : fatal error LNK1112: module machine type 'x86' conflicts with target machine type 'x64
```
Could you provide your custom triplet files?

**Comment by brazhenko** [comment]
@JackBoosY 
[x86-windows-atmos-md.cmake.txt](https://github.com/microsoft/vcpkg/files/5121635/x86-windows-atmos-md.cmake.txt)

**Comment by JackBoosY** [comment]
Use your custom triple, but I cannot reproduce this problem. Did we miss something?

**Comment by brazhenko** [comment]
dont know why, no problem now. thanks
