### ISSUE TITLE
[fluidsynth:x86-windows] build failure

### ISSUE THREAD

**Issue by aybe** [microsoft/vcpkg#13123]
**Host Environment**
- OS: Microsoft Windows [Version 10.0.19041.450]
- Compiler: MSVC v142 - VS 2019 C++ x64/x86 build tools (v14.27)

**To Reproduce**
`./vcpkg install fluidsynth:x86-windows`

**Failure logs** 
[install-x86-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/5121273/install-x86-windows-rel-out.log)
[install-x86-windows-rel-out-1.log](https://github.com/microsoft/vcpkg/files/5121274/install-x86-windows-rel-out-1.log)

**Additional context**
Please note that `fluidsynth:x64-windows` builds succesfully.

**Comment by JackBoosY** [comment]
```
LINK : fatal error LNK1104: cannot open file 'C:\vcpkg\buildtrees\fluidsynth\x86-windows-rel\src\Release\fluidsynth.exe'
```
Please make sure your antivirus software is turned off.

**Comment by aybe** [comment]
Thank you.
