### ISSUE TITLE
Building package curl:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by angelaresjun** [microsoft/vcpkg#13121]
**Describe the bug**
Building package curl:x86-windows failed with: BUILD_FAILED

**Environment**
- OS:  Windows
- Compiler: VS2019

**To Reproduce**
vcpkg.exe install curl

**Expected behavior**
Installing package ... done

**Failure logs** 
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: curl:x86-windows
  Vcpkg version: 2020.06.15-nohash

**Additional context**
- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:141 (message):
    Command failed: D:/Programs/CMake/bin/cmake.exe --build . --config Debug --target install -- -v
    Working Directory: F:/github/vcpkg/buildtrees/curl/x86-windows-dbg
    See logs for more information:
      F:\github\vcpkg\buildtrees\curl\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/curl/portfile.cmake:76 (vcpkg_install_cmake)
  scripts/ports.cmake:79 (include)

Error: Building package curl:x86-windows failed with: BUILD_FAILED

**Comment by JackBoosY** [comment]
Hi @angelaresjun, thanks for reporting this issue!
Please provide failure log _F:\github\vcpkg\buildtrees\curl\install-x86-windows-dbg-out.log_.

Thanks.

**Comment by JackBoosY** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
