### ISSUE TITLE
[opencv]x64-windows build failure (error C2065: '_MM_PERM_ACBD': undeclared identifier)

### ISSUE THREAD

**Issue by JunShuoMing** [microsoft/vcpkg#13122]
**Host Environment**
OS:Windows10 64bit Chinese
Compiler: visual studio 2017

**To Reproduce**
`./vcpkg install opencv:x64-windoes`
*note: x86 version can install correctly*

**Failure logs** 
-- Using cached E:/codes/vcpkg/downloads/opencv-cache/tiny_dnn/adb1c512e09ca2c7a6faef36f9c53e59-v1.0.0a3.tar.gz
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:141 (message):
    Command failed: E:/codes/vcpkg/downloads/tools/cmake-3.17.2-windows/cmake-3.17.2-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v
    Working Directory: E:/codes/vcpkg/buildtrees/opencv4/x64-windows-dbg
    See logs for more information:
      E:\codes\vcpkg\buildtrees\opencv4\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/opencv4/portfile.cmake:371 (vcpkg_install_cmake)
  scripts/ports.cmake:79 (include)

**Additional context**
***"install-x64-windows-dbg-out.log"***:    
`[97/499] C:\PROGRA~2\MIB055~1\2017\ENTERP~1\VC\Tools\MSVC\1412~1.258\bin\Hostx64\x64\cl.exe   /TP -DCVAPI_EXPORTS -DOPENCV_ALLOCATOR_STATS_COUNTER_TYPE="long long" -D_USE_MATH_DEFINES -D_VARIADIC_MAX=10 -D_WIN32_WINNT=0x0601 -D__OPENCV_BUILD=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -DCV_CPU_COMPILE_AVX2=1 -DCV_CPU_COMPILE_AVX512_COMMON=1 -DCV_CPU_COMPILE_AVX512_SKX=1 -DCV_CPU_COMPILE_AVX=1 -DCV_CPU_COMPILE_AVX_512F=1 -DCV_CPU_COMPILE_FMA3=1 -DCV_CPU_COMPILE_FP16=1 -DCV_CPU_COMPILE_POPCNT=1 -DCV_CPU_COMPILE_SSE4_1=1 -DCV_CPU_COMPILE_SSE4_2=1 -DCV_CPU_COMPILE_SSSE3=1 -DCV_CPU_DISPATCH_MODE=AVX512_SKX -IE:\codes\vcpkg\buildtrees\opencv4\src\4.3.0-0c6047baf6.clean\modules\core\src -IE:\codes\vcpkg\buildtrees\opencv4\src\4.3.0-0c6047baf6.clean\modules\core\include -Imodules\core -IE:\codes\vcpkg\installed\x64-windows\include -I. /nologo /DWIN32 /D_WINDOWS /W4 /utf-8 /GR /MP   /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise /FS     /EHa /wd4127 /wd4251 /wd4324 /wd4275 /wd4512 /wd4589  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1          /arch:AVX  /arch:AVX /arch:AVX2 /arch:AVX512 /arch:AVX512 /arch:AVX512 /showIncludes /Fomodules\core\CMakeFiles\opencv_core.dir\matmul.avx512_skx.cpp.obj /Fdlib\opencv_cored.pdb /FS -c modules\core\matmul.avx512_skx.cpp`
`FAILED: modules/core/CMakeFiles/opencv_core.dir/matmul.avx512_skx.cpp.obj`

***I run the failed command manualy, the more detail error message is:***
`C:\PROGRA~2\MIB055~1\2017\ENTERP~1\VC\Tools\MSVC\1412~1.258\bin\Hostx64\x64\cl.exe   /TP ......  -c modules\core\matmul.avx512_skx.cpp`
`E:\codes\vcpkg\buildtrees\opencv4\src\4.3.0-0c6047baf6.clean\modules\core\include\opencv2/core/hal/intrin_avx512.hpp(1740): error C2065: '_MM_PERM_ACBD': undeclared identifier`

**Comment by NancyLi1013** [comment]
Hi @JunShuoMing 
Thanks for posting this issue.

`_MM_PERM_ACBD` is defined in C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\zmmintrin.h at line 160

`_MM_PERM_ACBD = 0x27`

Could you please help confirm if you have this file on your local machine?

**Comment by JunShuoMing** [comment]
Hi @NancyLi1013 
My zmmintrin.h is at C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.12.25827\include\zmmintrin.h, but no this(_MM_PERM_ACBD) define.
I had searched all files in this include directory, but can't find this define also.

**Comment by NancyLi1013** [comment]
It seems that _MM_PERM_ACBD is not defined in `C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.12.25827\include\zmmintrin.h`. I also checked this file on my local machine.

The definition in _C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\zmmintrin.h_ is like this:
```
typedef enum {
    _MM_PERM_AAAA = 0x00, _MM_PERM_AAAB = 0x01, _MM_PERM_AAAC = 0x02,
    _MM_PERM_AAAD = 0x03, _MM_PERM_AABA = 0x04, _MM_PERM_AABB = 0x05,
    _MM_PERM_AABC = 0x06, _MM_PERM_AABD = 0x07, _MM_PERM_AACA = 0x08,
    _MM_PERM_AACB = 0x09, _MM_PERM_AACC = 0x0A, _MM_PERM_AACD = 0x0B,
    _MM_PERM_AADA = 0x0C, _MM_PERM_AADB = 0x0D, _MM_PERM_AADC = 0x0E,
    _MM_PERM_AADD = 0x0F, _MM_PERM_ABAA = 0x10, _MM_PERM_ABAB = 0x11,
    _MM_PERM_ABAC = 0x12, _MM_PERM_ABAD = 0x13, _MM_PERM_ABBA = 0x14,
    _MM_PERM_ABBB = 0x15, _MM_PERM_ABBC = 0x16, _MM_PERM_ABBD = 0x17,
    _MM_PERM_ABCA = 0x18, _MM_PERM_ABCB = 0x19, _MM_PERM_ABCC = 0x1A,
    _MM_PERM_ABCD = 0x1B, _MM_PERM_ABDA = 0x1C, _MM_PERM_ABDB = 0x1D,
    _MM_PERM_ABDC = 0x1E, _MM_PERM_ABDD = 0x1F, _MM_PERM_ACAA = 0x20,
    _MM_PERM_ACAB = 0x21, _MM_PERM_ACAC = 0x22, _MM_PERM_ACAD = 0x23,
    _MM_PERM_ACBA = 0x24, _MM_PERM_ACBB = 0x25, _MM_PERM_ACBC = 0x26,
    _MM_PERM_ACBD = 0x27, _MM_PERM_ACCA = 0x28, _MM_PERM_ACCB = 0x29,
```

Could you please try to install the toolset v14.15 or v14.16 via Visual Studio Installer in Individual components item?

These two toolsets are included this definition.
_C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.15.26726\include\zmmintrin.h_
_C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\zmmintrin.h_

**Comment by JunShuoMing** [comment]
Hi @NancyLi1013
I don't know where to install "toolset v14.15 or v14.16", but I add the define to file zmmintrin.h, and it opencv installed successful(I am not sure if it run without error).
Thanks

**Comment by NancyLi1013** [comment]
You can install it via Visual Studio Installer.
![Capture](https://user-images.githubusercontent.com/46708020/91925617-f473b880-ed07-11ea-8338-9bd3187aad34.PNG)

**Comment by JunShuoMing** [comment]
It seems that no this toolset version when vs2017 installed on windows7(I can see the options on vs2017 windows10 install)
![2017_install](https://user-images.githubusercontent.com/53216007/91926749-7f55b280-ed0a-11ea-829f-542fed73beed.PNG)

**Comment by NancyLi1013** [comment]
Could you please try to update Visual Studio 2017 to the latest version or use Visual Studio 2019 on Windows 7?
