### ISSUE TITLE
[cpp-taskflow] error with latest update to 2.5.0

### ISSUE THREAD

**Issue by remz1337** [microsoft/vcpkg#13134]
**Describe the bug**
My project (using CMake) is unable to find the library using the provided targets:
`find_package(cpp-taskflow CONFIG REQUIRED)`
`target_link_libraries(VRE PRIVATE Taskflow::Taskflow)`

**Environment**
- OS: Windows 10
- Compiler: MSVC 2019

**To Reproduce**
1. ./vcpkg install cpp-taskflow
2. Add target to project

**Expected behavior**
Find target and compile (everything is working with previous version of this port)

**Failure logs** 
`.../vcpkg/scripts/buildsystems/vcpkg.cmake:461 (_find_package): Could not find a package configuration file provided by "cpp-taskflow" with any of the following names:`
`    cpp-taskflowConfig.cmake`
`    cpp-taskflow-config.cmake`
`Add the installation prefix of "cpp-taskflow" to CMAKE_PREFIX_PATH or set "cpp-taskflow_DIR" to a directory containing one of the above files.  If "cpp-taskflow" provides a separate development package or SDK, be sure it  has been installed.`

**Additional context**
previous version (2.2.0) had a different target:
`find_package(Cpp-Taskflow CONFIG REQUIRED)`
`target_link_libraries(VRE PRIVATE Cpp-Taskflow::Cpp-Taskflow)`

**Comment by Neumann-A** [comment]
`find_package(cpp-taskflow CONFIG REQUIRED)`
is different from
`find_package(Cpp-Taskflow CONFIG REQUIRED)`
try with the previous upper case starting letters.

**Comment by remz1337** [comment]
Tried all the package names I could think of (cpp-taskflow, Cpp-Taskflow, Cpp-taskflow, Taskflow, taskflow), but didn't work

**Comment by Neumann-A** [comment]
Confirmed. The Target path for the config is wrong which is why it isn't found. Need to be share/taskflow instead of share/cpp-taskflow. Maybe the port also requires renaming?

**Comment by remz1337** [comment]
Pinging @mfornace for insights from [PR](https://github.com/microsoft/vcpkg/pull/12923)

**Comment by mfornace** [comment]
The library was indeed renamed from cpp-taskflow to taskflow... (I did not try to address the name change when doing the PR). Let me look to see what the PR messed up (sorry).

**Comment by mfornace** [comment]
I started a new #13140 pull request completing the name change from cpp-taskflow to taskflow. It works for me locally.

Sorry about the issue, my use-case wasn't testing the target_link_libraries correctly. Hopefully the fix I implemented will work.
