### ISSUE TITLE
openssl-windows:x86-windows build failure

### ISSUE THREAD

**Issue by ali-reza-zareian** [microsoft/vcpkg#13135]
**Host Environment**
- OS: windows 10 x64
- Compiler: visual studio 2019

**To Reproduce**
`./vcpkg install openssl-windows:x86-windows`

**Failure logs** 
warning: vcpkg appears to be in a Visual Studio prompt targeting x64 but is installing packages for x86-windows. Consider using --triplet x64-windows or --triplet x64-uwp.
The following packages will be built and installed:
    openssl-windows[core]:x86-windows
Detecting compiler hash for triplet x86-windows...
Starting package 1/1: openssl-windows:x86-windows
Building package openssl-windows[core]:x86-windows...
Could not locate cached archive: C:\Users\Developer\AppData\Local\vcpkg/archives\67\67c534134a55301ea62f440038438972484bcdeb.zip
-- Using cached F:/git projects/vcpkg/downloads/openssl-1.1.1g.tar.gz
-- Cleaning sources at F:/git projects/vcpkg/buildtrees/openssl-windows/src/openssl-1-bb2a9a5801.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source F:/git projects/vcpkg/downloads/openssl-1.1.1g.tar.gz
-- Using source at F:/git projects/vcpkg/buildtrees/openssl-windows/src/openssl-1-bb2a9a5801.clean
-- Downloading https://www.nasm.us/pub/nasm/releasebuilds/2.14.02/win32/nasm-2.14.02-win32.zip...
-- Downloading https://www.nasm.us/pub/nasm/releasebuilds/2.14.02/win32/nasm-2.14.02-win32.zip... Failed. Status: 6;"Couldn't resolve host name"
-- Downloading https://fossies.org/windows/misc/nasm-2.14.02-win32.zip...
-- Downloading https://fossies.org/windows/misc/nasm-2.14.02-win32.zip... Failed. Status: 35;"SSL connect error"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:176 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_find_acquire_program.cmake:496 (vcpkg_download_distfile)
  ports/openssl-windows/portfile.cmake:25 (vcpkg_find_acquire_program)
  scripts/ports.cmake:79 (include)

Error: Building package openssl-windows:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openssl-windows:x86-windows
  Vcpkg version: 2020.06.15-nohash

**Additional context**
there is not port with this version at this link https://fossies.org/windows/misc/nasm-2.14.02-win32.zip.
it seems that it could not download the last version of nasm.

**Comment by sfhacker** [comment]
Are we **STILL** having problems building OpenSSL?

![image](https://user-images.githubusercontent.com/25817529/91337450-b6155f80-e816-11ea-8117-aad3dc98db4d.png)

**Comment by ali-reza-zareian** [comment]
> 
> 
> Are we **STILL** having problems building OpenSSL?
> 
> ![image](https://user-images.githubusercontent.com/25817529/91337450-b6155f80-e816-11ea-8117-aad3dc98db4d.png)

This problem is made in Windows 10 with Visual Studio 2019 .It isn't about MinGW.

**Comment by NancyLi1013** [comment]
Hi @ali-reza-zareian 
Thanks for posting this issue.
It seems that there is something wrong when you download https://www.nasm.us/pub/nasm/releasebuilds/2.14.02/win32/nasm-2.14.02-win32.zip.

Could you please help confirm if you have access to this archive?

**Comment by ali-reza-zareian** [comment]
Yes,I have.
I have to set proxy with netsh command.(netsh winhttp import proxy source=ie)
I still have problem with vcpkg however i set HTTP_PROXY and HTTPS_PROXY in environment system settings but it is about proxy settings.
thank you for your respond.

I think its a good feature that vcpkg has an option to set proxy like cURL command.
Example:
vcpkg install \<port name\> [-x proxyserver:port]
`vcpkg install openssl-windows:x86-windows -x 127.0.0.1:5555`

**Comment by NancyLi1013** [comment]
Hi @ali-reza-zareian 
For proxy issue, there is already an issue to track this #7200. 

Thanks for your proposal.
