### ISSUE TITLE
Building package libuuid:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by conquerv** [microsoft/vcpkg#13145]
**Host Environment**
- OS: Windows 10
- Compiler: 6.2

**To Reproduce**
`vcpkg install libuuid:x64-windows`

**Failure logs** 
  Package: libuuid:x64-windows
  Vcpkg version: 2020.06.15-nohash

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by JonLiu1993** [comment]
@conquerv ,Thanks for your issue
libuuid currently only supports unix platform , Target 'Windows' not supported by libuuid!

**Comment by JonLiu1993** [comment]
@conquerv ,Sorry reply you so late, libuuid currently only supports unix platform, on windows platform There post a error
````
fatal error C1083: Cannot open include file: 'unistd.h': No such file or directory
````
unistd.h is a UNIX header, so it's not present in VC++
