### ISSUE TITLE
[gdal] update to <3.1.2>

### ISSUE THREAD

**Issue by cyh19910216** [microsoft/vcpkg#13149]
Library name: gdal

New version number: 3.1.2

Other information that may be useful (release notes, etc...)
release notes: https://github.com/OSGeo/gdal/blob/v3.1.2/gdal/NEWS
GDAL: https://gdal.org/
GitHub: https://github.com/OSGeo/GDAL

**Comment by JonLiu1993** [comment]
Hi @cyh19910216 ,Thaks for your issue.
duplicated of [#9100 ](https://github.com/microsoft/vcpkg/pull/9100)
