### ISSUE TITLE
Can not install sundials

### ISSUE THREAD

**Issue by ChrisNabold** [microsoft/vcpkg#13157]
[C:\vcpkg].\vcpkg install sundials
Computing installation plan...
The following packages will be built and installed:
    sundials[core]:x64-windows
Detecting compiler hash for triplet x64-windows...
Starting package 1/1: sundials:x64-windows
Building package sundials[core]:x64-windows...
Could not locate cached archive: C:\Users\Chris\AppData\Local\vcpkg/archives\b5\b56f2cd4558030d349b3bac9f0630d080970d9d4.zip
-- Using cached C:/vcpkg/downloads/sundials-3.1.1.tar.gz
-- Cleaning sources at C:/vcpkg/buildtrees/sundials/src/sundials-3-a93295ae22.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg/downloads/sundials-3.1.1.tar.gz
-- Applying patch uwp-c4703-warning.patch
-- Using source at C:/vcpkg/buildtrees/sundials/src/sundials-3-a93295ae22.clean
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: ninja -v
    Working Directory: C:/vcpkg/buildtrees/sundials/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\vcpkg\buildtrees\sundials\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:300 (vcpkg_execute_required_process)
  ports/sundials/portfile.cmake:18 (vcpkg_configure_cmake)
  scripts/ports.cmake:79 (include)

Error: Building package sundials:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: sundials:x64-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by PhoebeHui** [comment]
Currently sundials doesn't support x86-windows, x64-windows and arm64-windows.

See https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt#L1638

**Comment by sfhacker** [comment]
We must confess that we are not familiar with this project (sundials) at all!
This is the very first time we have built it.

Environment: Windows 10 x64

![image](https://user-images.githubusercontent.com/25817529/91339894-7b152b00-e81a-11ea-9539-a0362686c6ef.png)

![image](https://user-images.githubusercontent.com/25817529/91340043-b0217d80-e81a-11ea-9580-04b21a6f803f.png)

Can someone confirm we are on the right path?

**Comment by sfhacker** [comment]
Any news/update on this open issue?

**Comment by ChrisNabold** [comment]
Dear John,

 

Thank you for your help to install sundials for windows/vcpkg. As far as I can see you are on the right track and I will be pleased if sundials will become available for Visual Studio 2019. The results from your test correspond with the output from the sundials web page. Why do you use version 3.3.1; there are more recent versions eg. 5.3.0 or 3.1.2 ?

 

Best regards

Chris

**Comment by sfhacker** [comment]
@ChrisNabold Have you been able to sort out your issue?
I used version 3.3.1 because it is the one you used when you posted this issue!
Should I try with the master branch?

**Comment by ChrisNabold** [comment]
Thank you for your response. Version 3.3.1 was the version I tried to download from vcpkg, which did not work.

It would be fantastic if you could try it with the master branch – version 5.3. 

 

Thank you for your efforts

Best regards

Chris

**Comment by sfhacker** [comment]
How familiar are you with building projects from source on Windows? A newbie?

Just built master branch in no time!

![image](https://user-images.githubusercontent.com/25817529/92661006-f6a8c900-f33e-11ea-903d-e4cb0654376e.png)

![image](https://user-images.githubusercontent.com/25817529/92661024-ff999a80-f33e-11ea-9206-abb6f1201458.png)

Let us know how to proceed.

**Comment by sfhacker** [comment]
@ChrisNabold This issue is a month old! Any update?

**Comment by ChrisNabold** [comment]
Dear John,

 

Thank you for your help. I managed to install 5.4.0 using CMake and Make. The problem I had was that dll’s were generated and the corresponding dlls should be either moved to the file containing the exe file or the dll-file should be on the path.

I still have a problem if I want to include the static libraries instead of the dynamic ones.

 

Best regards and thank you!!

Chris

**Comment by Adela0814** [comment]
This issue has been fixed in the latest vcpkg(sundials version: 6.2.0).
