### ISSUE TITLE
error installing lapack Armadillo

### ISSUE THREAD

**Issue by ChrisNabold** [microsoft/vcpkg#13156]
Building package lapack-reference:x64-windows failed with: BUILD_FAILED
.\vcpkg install armadillo
Computing installation plan...
The following packages will be built and installed:
    armadillo[core]:x64-windows
  * lapack[core]:x64-windows
  * lapack-reference[blas-select,core,noblas]:x64-windows
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Starting package 1/3: lapack-reference:x64-windows
Building package lapack-reference[blas-select,core,noblas]:x64-windows...
Could not locate cached archive: C:\Users\Chris\AppData\Local\vcpkg/archives\d8\d8305e4c311c3ed224865cb5a11467545ebf94c6.zip
-- Using cached C:/vcpkg/downloads/Reference-LAPACK-lapack-v3.8.0.tar.gz
-- Cleaning sources at C:/vcpkg/buildtrees/lapack-reference/src/v3.8.0-954f10683f.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg/downloads/Reference-LAPACK-lapack-v3.8.0.tar.gz
-- Using source at C:/vcpkg/buildtrees/lapack-reference/src/v3.8.0-954f10683f.clean
-- The Fortran compiler identification is unknown
-- No Fortran compiler found on the PATH. Using MinGW gfortran!
-- Acquiring MSYS Packages from C:/vcpkg/downloads/tools/msys2-20200812...
-- Acquiring MSYS Packages... OK
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:141 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v
    Working Directory: C:/vcpkg/buildtrees/lapack-reference/x64-windows-dbg
    See logs for more information:
      C:\vcpkg\buildtrees\lapack-reference\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/lapack-reference/portfile.cmake:68 (vcpkg_install_cmake)
  scripts/ports.cmake:79 (include)

Error: Building package lapack-reference:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: lapack-reference:x64-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by NancyLi1013** [comment]
Hi @ChrisNabold 
Thanks for posting this issue.
Could you please provide the error info from _C:\vcpkg\buildtrees\lapack-reference\install-x64-windows-dbg-out.log_?

**Comment by ChrisNabold** [comment]
[install-x64-windows-dbg-out.zip](https://github.com/microsoft/vcpkg/files/5130103/install-x64-windows-dbg-out.zip)

**Comment by ChrisNabold** [comment]
https://github.com/microsoft/vcpkg/files/5130103/install-x64-windows-dbg-out.zip

**Comment by NancyLi1013** [comment]
```
FAILED: bin/liblapack.dll lib/liblapack.dll.a 
cmd.exe /C "cd . && C:\vcpkg\downloads\tools\msys2-20200812\msys64\mingw64\bin\gfortran.exe -mabi=ms -m64 -g   -shared -o bin\liblapack.dll -Wl,--out-implib,lib\liblapack.dll.a -Wl,--major-image-version,3,--minor-image-version,8 @CMakeFiles\lapack.rsp -Wl,--output-def,lapack.def && "C:\Program Files\CMake\bin\cmake.exe" -Dlib="C:/vcpkg/buildtrees/lapack-reference/x64-windows-dbg/CMakeFiles/CMakeGNUtoMS_lib.bat" -Ddef=lapack.def -Ddll=bin\liblapack.dll -Dimp=lib\liblapack.dll.a -P "C:/Program Files/CMake/share/cmake-3.18/Modules/Platform/GNUtoMS_lib.cmake" && cd ."
TCC: Unknown command "C:"
CMake Error at C:/Program Files/CMake/share/cmake-3.18/Modules/Platform/GNUtoMS_lib.cmake:9 (message):
  lib failed: 2


ninja: build stopped: subcommand failed.
```
I cannot reproduce this issue on my local with CMake 3.17.2 and 3.18.2.

Could you please try to update vcpkg to the latest version and rebuild this?

**Comment by sfhacker** [comment]
@ChrisNabold  Any update on this (re)open(ed) issue? Cheers.

**Comment by PhoebeHui** [comment]
@ChrisNabold has opened 2 issues for tracking the issue, duplicated of https://github.com/microsoft/vcpkg/issues/13915 and https://github.com/microsoft/vcpkg/issues/13914.

**Comment by sfhacker** [comment]
@ChrisNabold Please avoid posting duplicated issues! There are far too many already!
