### ISSUE TITLE
[brotli] build failure

### ISSUE THREAD

**Issue by DarkWarrior703** [microsoft/vcpkg#13166]
**Host Environment**
- OS: Windows
- Compiler: MS VC 2019

**To Reproduce**
./vcpkg install sfml

**Failure logs** 
CMake Error at scripts/cmake/vcpkg_fixup_pkgconfig.cmake:232 (message):
  Library "brotlicommon" was not found! If it is a system library use the
  SYSTEM_LIBRARIES parameter for the vcpkg_fixup_pkgconfig call! Otherwise,
  correct the *.pc file
Call Stack (most recent call first):
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:298 (vcpkg_fixup_pkgconfig_check_files)
  ports/brotli/portfile.cmake:25 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:79 (include)

Error: Building package brotli:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: brotli:x86-windows
  Vcpkg version: 2020.06.15-nohash

**Additional context**
I used git pull and vcpkg install brotli and failed 5 times. I wanted to build sfml, but I haven't manage to deal with brotli.

**Comment by Neumann-A** [comment]
Without any further debug output I would assume it is the same issue as #13105

**Comment by sfhacker** [comment]
@DarkWarrior703 Probably your environment is broken or 'polluted'!

![image](https://user-images.githubusercontent.com/25817529/91336356-20c59b80-e815-11ea-94eb-1673694c12d5.png)

![image](https://user-images.githubusercontent.com/25817529/91336392-29b66d00-e815-11ea-9f82-59b041e25053.png)

**Comment by sfhacker** [comment]
We have faced no issues (at all) building brotli!

![image](https://user-images.githubusercontent.com/25817529/91336644-8f0a5e00-e815-11ea-832d-2a5162c63736.png)

Pardon my ignorance, but is brotli a dependency somewhere?

**Comment by DarkWarrior703** [comment]
I think that brotli is a dependency for sfml. When I try to install sfml, vcpkg tries to install brotli.

**Comment by sfhacker** [comment]
@DarkWarrior703 When I built sfml, it didn't ask for brotli at all! I may be wrong, but ....
Can someone confirm whether or not brotli is a dependency in this case?

**Comment by Neumann-A** [comment]
```
$ ./vcpkg.exe depend-info sfml
zlib:
brotli:
bzip2:
libogg:
libpng: zlib
freetype[bzip2, png]: brotli, bzip2, libpng, zlib
libflac: libogg
libvorbis: libogg
openal-soft:
stb:
sfml: freetype, libflac, libogg, libvorbis, openal-soft, stb
```

sfml -> freetype -> brotli

**Comment by sfhacker** [comment]
It seems that brotli is an indirect dependency.
@DarkWarrior703 Can you build sfml without freetype? Just for testing purposes.

**Comment by DarkWarrior703** [comment]
I think there's a problem with CMake because brotlicommon.lib file exists. I checked the directory. How to build a library without a dependency?

**Comment by Neumann-A** [comment]
I feel like I am being ignored:
>Without any further debug output I would assume it is the same issue as #13105

**Comment by Neumann-A** [comment]
You can tryout PR #13144 which should solve the problem

**Comment by DarkWarrior703** [comment]
I changed the name of the directory. Thank you.

**Comment by sfhacker** [comment]
@DarkWarrior703 I may be wrong, but ... I don't think it is CMake's fault, but either your broken environment or vcpkg!
CMake works like a charm on my PC. I use it every day to build dozens of projects.

![image](https://user-images.githubusercontent.com/25817529/91349170-44dea800-e828-11ea-90df-586584996682.png)

> How to build a library without a dependency?

How familiar are you with building projects from source on Windows? A newbie?
If you use CMake, you can add an option like: cmake -Doption_name=OFF ..

**Comment by DarkWarrior703** [comment]
I solved the problem. It was from spaces in name. If your directory is "x y", it won't work, because of spaces. "xy" will work.

**Comment by NancyLi1013** [comment]
Thanks for posting this issue.
Let's wait for the PR #13126 merged to fix this issue.
