### ISSUE TITLE
[boost-modular-build-helpers] make build use a single codepath for all platforms

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#13163]
Currently the codepaths for windows and the others platforms are seperated. While on windows the `boost_build` function does all the work for other platforms a `CMakelists.txt` is used to setup the boost build via  a custom command. It would be a nice improvement if all platforms would use the `CMakeLists.txt` approach since it allows access to the variables set in the cmake toolchain file which are currently ignored on windows.  It also gives access to compiler ids etc. so that the correct boost toolset can be selected. 

BTW: Does anybody know a good way to download all the boost headers without downloading all of boost?

**Comment by PhoebeHui** [comment]
> BTW: Does anybody know a good way to download all the boost headers without downloading all of boost?

cc @yurybura  @autoantwort @ras0219-msft, do you know more about this?

**Comment by yurybura** [comment]
@Neumann-A I absolutely agree with you. What do you think about use original Boost's CMake files? Now every Boost library has own CMakeLists.txt.

**Comment by autoantwort** [comment]
> @Neumann-A I absolutely agree with you. What do you think about use original Boost's CMake files? Now every Boost library has own CMakeLists.txt.

According to [this post](https://www.reddit.com/r/cpp/comments/nlhwee/latest_graph_of_boost_libraries_with_cmake/) 12 days ago not every boost lib has a CMakeLists.txt

**Comment by yurybura** [comment]
> > @Neumann-A I absolutely agree with you. What do you think about use original Boost's CMake files? Now every Boost library has own CMakeLists.txt.
> 
> According to [this post](https://www.reddit.com/r/cpp/comments/nlhwee/latest_graph_of_boost_libraries_with_cmake/) 12 days ago not every boost lib has a CMakeLists.txt

@autoantwort Oh yes. Thank you for correction. But I hope this is right direction to fix this issue.

**Comment by ras0219-msft** [comment]
Closed by #20220
