### ISSUE TITLE
jsonnet: command not found, but it's available via vcpkg search jsonnet

### ISSUE THREAD

**Issue by evgeniy-rotar** [microsoft/vcpkg#13173]
Environment: Windows 10, WSL 2, Ubuntu

I tried to install jsonnet package via vcpkg. So the steps:

```
git clone https://github.com/Microsoft/vcpkg.git
cd vcpkg
./bootstrap-vcpkg.sh
./vcpkg integrate install
./vcpkg install jsonnet
```

According logs:

```
Building package jsonnet[core]:x64-linux... done
Installing package jsonnet[core]:x64-linux...
Installing package jsonnet[core]:x64-linux... done
Elapsed time for package jsonnet:x64-linux: 19.16 s
```

Trying to call jsonnet, it says:

`jsonnet: command not found`

Trying to search:

`./vcpkg search jsonnet`

Result:

```
jsonnet              0.14.0-1         Jsonnet - The data templating language

If your library is not listed, please open an issue at and/or consider making a pull request:
    https://github.com/Microsoft/vcpkg/issues
```

Where are I'm wrong?

**Comment by StarGate-One** [comment]
vcpkg is used to maintain source packages. 
vcpkg would have installed the sources, headers, libraries and in debug builds the symbols to be consumed in downstream projects requiring the functionality in port jsonnet.

**Comment by evgeniy-rotar** [comment]
As soon as I installed json port (via install jsonnet), may I somehow use `jsonnet [options]` command in terminal?

**Comment by sfhacker** [comment]
@evgeniy-rotar As soon as you install jsonnet, you should be able to use it straight away!

![image](https://user-images.githubusercontent.com/25817529/91372940-66578800-e858-11ea-982e-988e08f68420.png)

**Comment by Neumann-A** [comment]
> Where are I'm wrong?

vcpkg is not a system package manager as such you need to move to the directory where that executable is placed. (If it is installed. Normally vcpkg just install the library bits and not the tools. )

**Comment by sfhacker** [comment]
@Neumann-A Whenever you type: _make install_, that installs (or copies) everything: header files, library files, documentation and tools as well.
Having read dozens of issues here, among thousands, it seems that vcpkg, more often than not, gets confused about several points (e.g. dependencies, installation, compilation, and so on).
Another symptom could be that we (users) do not know how to use vcpkg. (or what it is!)
I leave these symptoms to your expert troubleshooting skills!

**Comment by evgeniy-rotar** [comment]
Thanks everyone for replies and clarifications

**Comment by sfhacker** [comment]
@evgeniy-rotar Can you post here how you fixed your issue? Cheers.
