### ISSUE TITLE
[gmp] Visual Studio 2019 version 16.7 breaks gmp:x64-uwp

### ISSUE THREAD

**Issue by BillyONeal** [microsoft/vcpkg#13172]
**Host Environment**
- OS: Windows
- Compiler: N/A

**To Reproduce**
`.\vcpkg.exe install gmp:x64_uwp`

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.
[build-x64-uwp-rel-out.log](https://github.com/microsoft/vcpkg/files/5132404/build-x64-uwp-rel-out.log)
[patch-x64-uwp-0-err.log](https://github.com/microsoft/vcpkg/files/5132405/patch-x64-uwp-0-err.log)
[patch-x64-uwp-1-err.log](https://github.com/microsoft/vcpkg/files/5132400/patch-x64-uwp-1-err.log)
[patch-x64-uwp-2-err.log](https://github.com/microsoft/vcpkg/files/5132401/patch-x64-uwp-2-err.log)
[stdout-x64-uwp.log](https://github.com/microsoft/vcpkg/files/5132402/stdout-x64-uwp.log)
[x64-uwp.vcpkg_abi_info.txt](https://github.com/microsoft/vcpkg/files/5132403/x64-uwp.vcpkg_abi_info.txt)

**Additional context**
This problem also occurs if one tries to build the gmp solution in Visual Studio

![image](https://user-images.githubusercontent.com/1544943/91347306-f59c6700-e796-11ea-8c38-a24b8e20b819.png)

**Comment by PhoebeHui** [comment]
Confirming with msbuild team, that mixing configurations with different application types is not supported, and this has never been supported, not sure why it works before, I will try to contact the project owner.
