### ISSUE TITLE
[fmt] build failure , install spdlog failure

### ISSUE THREAD

**Issue by junho103** [microsoft/vcpkg#13171]
**Host Environment**
- OS: [Windows 10]
- Compiler: visual studio 2015

**To Reproduce**
`./vcpkg install spdlog`

**Failure logs** 
C:\Third-party\vcpkg\vcpkg>.\vcpkg.exe install spdlog
Computing installation plan...
The following packages will be built and installed:
  * fmt[core]:x86-windows
    spdlog[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x86-windows...
Starting package 1/2: fmt:x86-windows
Building package fmt[core]:x86-windows...
Could not locate cached archive: C:\Users\junho\AppData\Local\vcpkg\archives\81\810c98b9704901b64d132a3ebebbed2328bf0e0e.zip
-- Using cached C:/Third-party/vcpkg/vcpkg/downloads/fmtlib-fmt-cd4af11efc9c622896a3e4cb599fa28668ca3d05.tar.gz
-- Cleaning sources at C:/Third-party/vcpkg/vcpkg/buildtrees/fmt/src/8668ca3d05-7f40cec0ee.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Third-party/vcpkg/vcpkg/downloads/fmtlib-fmt-cd4af11efc9c622896a3e4cb599fa28668ca3d05.tar.gz
-- Applying patch fix-warning4189.patch
-- Using source at C:/Third-party/vcpkg/vcpkg/buildtrees/fmt/src/8668ca3d05-7f40cec0ee.clean
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: ninja -v
    Working Directory: C:/Third-party/vcpkg/vcpkg/buildtrees/fmt/x86-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\Third-party\vcpkg\vcpkg\buildtrees\fmt\config-x86-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:300 (vcpkg_execute_required_process)
  ports/fmt/portfile.cmake:9 (vcpkg_configure_cmake)
  scripts/ports.cmake:79 (include)

Error: Building package fmt:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: fmt:x86-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.

C:\Third-party\vcpkg\vcpkg>

**Comment by sfhacker** [comment]
We have no idea what 'fmt' is but spdlog builds just fine!

![image](https://user-images.githubusercontent.com/25817529/91345634-02669c80-e823-11ea-9bad-d9f64d59776c.png)

![image](https://user-images.githubusercontent.com/25817529/91345691-190cf380-e823-11ea-8f0b-bb412d1470fa.png)

@junho103 Next time you post an issue on GitHub, try to be more 'professional' (<port name>)

**Comment by StarGate-One** [comment]
@BillyONeal please change title to `[fmt] build failure`  as the actual problem the op is with `port fmt` as it is a prerequisite to install `port spdlog`.

@junho103 please attached the log file: `C:\Third-party\vcpkg\vcpkg\buildtrees\fmt\config-x86-windows-out.log`

**Comment by sfhacker** [comment]
We didn't and we don't have fmt installed. However, we could build spdlog. How could this happen? Trying to answer my own question: a bundled fmt?

**Comment by junho103** [comment]
@StarGate-One 

Attach log file: **config-x86-windows-out.log** 
------------------------------------------

[1/2] cmd /c "cd ../../x86-windows-dbg && "C:/Third-party/vcpkg/vcpkg/downloads/tools/cmake-3.17.2-windows/cmake-3.17.2-win32-x86/bin/cmake.exe" "C:/Third-party/vcpkg/vcpkg/buildtrees/fmt/src/8668ca3d05-7f40cec0ee.clean" "-DFMT_CMAKE_DIR=share/fmt" "-DFMT_TEST=OFF" "-DFMT_DOC=OFF" "-DCMAKE_MAKE_PROGRAM=C:/Third-party/vcpkg/vcpkg/downloads/tools/ninja/1.10.0-windows/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/Third-party/vcpkg/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x86-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v140" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/Third-party/vcpkg/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_TARGET_ARCHITECTURE=x86" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=C:/Third-party/vcpkg/vcpkg" "-D_VCPKG_INSTALLED_DIR=C:/Third-party/vcpkg/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_INSTALL_PREFIX=C:/Third-party/vcpkg/vcpkg/packages/fmt_x86-windows/debug""
FAILED: ../../x86-windows-dbg/CMakeCache.txt 
cmd /c "cd ../../x86-windows-dbg && "C:/Third-party/vcpkg/vcpkg/downloads/tools/cmake-3.17.2-windows/cmake-3.17.2-win32-x86/bin/cmake.exe" "C:/Third-party/vcpkg/vcpkg/buildtrees/fmt/src/8668ca3d05-7f40cec0ee.clean" "-DFMT_CMAKE_DIR=share/fmt" "-DFMT_TEST=OFF" "-DFMT_DOC=OFF" "-DCMAKE_MAKE_PROGRAM=C:/Third-party/vcpkg/vcpkg/downloads/tools/ninja/1.10.0-windows/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/Third-party/vcpkg/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x86-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v140" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/Third-party/vcpkg/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_TARGET_ARCHITECTURE=x86" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=C:/Third-party/vcpkg/vcpkg" "-D_VCPKG_INSTALLED_DIR=C:/Third-party/vcpkg/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_INSTALL_PREFIX=C:/Third-party/vcpkg/vcpkg/packages/fmt_x86-windows/debug""
-- CMake version: 3.17.2
-- The CXX compiler identification is MSVC 19.0.24210.0
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_x86/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_x86/cl.exe - broken
CMake Error at C:/Third-party/vcpkg/vcpkg/downloads/tools/cmake-3.17.2-windows/cmake-3.17.2-win32-x86/share/cmake-3.17/Modules/CMakeTestCXXCompiler.cmake:53 (message):
  The C++ compiler

    "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_x86/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/Third-party/vcpkg/vcpkg/buildtrees/fmt/x86-windows-dbg/CMakeFiles/CMakeTmp
    
    Run Build Command(s):C:/Third-party/vcpkg/vcpkg/downloads/tools/ninja/1.10.0-windows/ninja.exe cmTC_1e447 && [1/2] Building CXX object CMakeFiles\cmTC_1e447.dir\testCXXCompiler.cxx.obj
    [2/2] Linking CXX executable cmTC_1e447.exe
    FAILED: cmTC_1e447.exe 
    cmd.exe /C "cd . && C:\Third-party\vcpkg\vcpkg\downloads\tools\cmake-3.17.2-windows\cmake-3.17.2-win32-x86\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_1e447.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\x64\rc.exe --mt=CMAKE_MT-NOTFOUND --manifests  -- C:\PROGRA~2\MICROS~3.0\VC\bin\AMD64_~2\link.exe /nologo CMakeFiles\cmTC_1e447.dir\testCXXCompiler.cxx.obj  /out:cmTC_1e447.exe /implib:cmTC_1e447.lib /pdb:cmTC_1e447.pdb /version:0.0  /machine:X86  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    MT: command "CMAKE_MT-NOTFOUND /nologo /manifest CMakeFiles\cmTC_1e447.dir/intermediate.manifest /out:CMakeFiles\cmTC_1e447.dir/embed.manifest /notify_update" failed (exit code 0x0) with the following output:
    지정된 파일을 찾을 수 없습니다
    ninja: build stopped: subcommand failed.
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:55 (project)


-- Configuring incomplete, errors occurred!
See also "C:/Third-party/vcpkg/vcpkg/buildtrees/fmt/x86-windows-dbg/CMakeFiles/CMakeOutput.log".
See also "C:/Third-party/vcpkg/vcpkg/buildtrees/fmt/x86-windows-dbg/CMakeFiles/CMakeError.log".
[2/2] cmd /c "cd .. && "C:/Third-party/vcpkg/vcpkg/downloads/tools/cmake-3.17.2-windows/cmake-3.17.2-win32-x86/bin/cmake.exe" "C:/Third-party/vcpkg/vcpkg/buildtrees/fmt/src/8668ca3d05-7f40cec0ee.clean" "-DFMT_CMAKE_DIR=share/fmt" "-DFMT_TEST=OFF" "-DFMT_DOC=OFF" "-DCMAKE_MAKE_PROGRAM=C:/Third-party/vcpkg/vcpkg/downloads/tools/ninja/1.10.0-windows/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/Third-party/vcpkg/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x86-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v140" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/Third-party/vcpkg/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_TARGET_ARCHITECTURE=x86" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=C:/Third-party/vcpkg/vcpkg" "-D_VCPKG_INSTALLED_DIR=C:/Third-party/vcpkg/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=C:/Third-party/vcpkg/vcpkg/packages/fmt_x86-windows""
FAILED: ../CMakeCache.txt 
cmd /c "cd .. && "C:/Third-party/vcpkg/vcpkg/downloads/tools/cmake-3.17.2-windows/cmake-3.17.2-win32-x86/bin/cmake.exe" "C:/Third-party/vcpkg/vcpkg/buildtrees/fmt/src/8668ca3d05-7f40cec0ee.clean" "-DFMT_CMAKE_DIR=share/fmt" "-DFMT_TEST=OFF" "-DFMT_DOC=OFF" "-DCMAKE_MAKE_PROGRAM=C:/Third-party/vcpkg/vcpkg/downloads/tools/ninja/1.10.0-windows/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/Third-party/vcpkg/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x86-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v140" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/Third-party/vcpkg/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_TARGET_ARCHITECTURE=x86" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=C:/Third-party/vcpkg/vcpkg" "-D_VCPKG_INSTALLED_DIR=C:/Third-party/vcpkg/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=C:/Third-party/vcpkg/vcpkg/packages/fmt_x86-windows""
-- CMake version: 3.17.2
-- The CXX compiler identification is MSVC 19.0.24210.0
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_x86/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_x86/cl.exe - broken
CMake Error at C:/Third-party/vcpkg/vcpkg/downloads/tools/cmake-3.17.2-windows/cmake-3.17.2-win32-x86/share/cmake-3.17/Modules/CMakeTestCXXCompiler.cmake:53 (message):
  The C++ compiler

    "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_x86/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/Third-party/vcpkg/vcpkg/buildtrees/fmt/x86-windows-rel/CMakeFiles/CMakeTmp
    
    Run Build Command(s):C:/Third-party/vcpkg/vcpkg/downloads/tools/ninja/1.10.0-windows/ninja.exe cmTC_1e27f && [1/2] Building CXX object CMakeFiles\cmTC_1e27f.dir\testCXXCompiler.cxx.obj
    [2/2] Linking CXX executable cmTC_1e27f.exe
    FAILED: cmTC_1e27f.exe 
    cmd.exe /C "cd . && C:\Third-party\vcpkg\vcpkg\downloads\tools\cmake-3.17.2-windows\cmake-3.17.2-win32-x86\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_1e27f.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\x64\rc.exe --mt=CMAKE_MT-NOTFOUND --manifests  -- C:\PROGRA~2\MICROS~3.0\VC\bin\AMD64_~2\link.exe /nologo CMakeFiles\cmTC_1e27f.dir\testCXXCompiler.cxx.obj  /out:cmTC_1e27f.exe /implib:cmTC_1e27f.lib /pdb:cmTC_1e27f.pdb /version:0.0  /machine:X86  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    MT: command "CMAKE_MT-NOTFOUND /nologo /manifest CMakeFiles\cmTC_1e27f.dir/intermediate.manifest /out:CMakeFiles\cmTC_1e27f.dir/embed.manifest /notify_update" failed (exit code 0x0) with the following output:
    지정된 파일을 찾을 수 없습니다
    ninja: build stopped: subcommand failed.
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:55 (project)


-- Configuring incomplete, errors occurred!
See also "C:/Third-party/vcpkg/vcpkg/buildtrees/fmt/x86-windows-rel/CMakeFiles/CMakeOutput.log".
See also "C:/Third-party/vcpkg/vcpkg/buildtrees/fmt/x86-windows-rel/CMakeFiles/CMakeError.log".
ninja: build stopped: subcommand failed.

**Comment by sfhacker** [comment]
@junho103 Are you ok? 
fmt project is a small one, so it should be straight forward to build and install.

![image](https://user-images.githubusercontent.com/25817529/91374852-7fface80-e85c-11ea-9146-fe165ded6139.png)

**Comment by NancyLi1013** [comment]
Hi @junho103 
Thanks for posting this issue.
I cannot reproduce this issue on my local with both Visual Studio 2017 and Visual Studio 2015(MSVC 19.11.25603.0).

```
CMake Error at C:/Third-party/vcpkg/vcpkg/downloads/tools/cmake-3.17.2-windows/cmake-3.17.2-win32-x86/share/cmake-3.17/Modules/CMakeTestCXXCompiler.cmake:53 (message):
The C++ compiler

"C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_x86/cl.exe"
is not able to compile a simple test program.

It fails with the following output:

Change Dir: C:/Third-party/vcpkg/vcpkg/buildtrees/fmt/x86-windows-rel/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Third-party/vcpkg/vcpkg/downloads/tools/ninja/1.10.0-windows/ninja.exe cmTC_1e27f && [1/2] Building CXX object CMakeFiles\cmTC_1e27f.dir\testCXXCompiler.cxx.obj
[2/2] Linking CXX executable cmTC_1e27f.exe
FAILED: cmTC_1e27f.exe 
cmd.exe /C "cd . && C:\Third-party\vcpkg\vcpkg\downloads\tools\cmake-3.17.2-windows\cmake-3.17.2-win32-x86\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_1e27f.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\x64\rc.exe --mt=CMAKE_MT-NOTFOUND --manifests  -- C:\PROGRA~2\MICROS~3.0\VC\bin\AMD64_~2\link.exe /nologo CMakeFiles\cmTC_1e27f.dir\testCXXCompiler.cxx.obj  /out:cmTC_1e27f.exe /implib:cmTC_1e27f.lib /pdb:cmTC_1e27f.pdb /version:0.0  /machine:X86  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
MT: command "CMAKE_MT-NOTFOUND /nologo /manifest CMakeFiles\cmTC_1e27f.dir/intermediate.manifest /out:CMakeFiles\cmTC_1e27f.dir/embed.manifest /notify_update" failed (exit code 0x0) with the following output:
지정된 파일을 찾을 수 없습니다
ninja: build stopped: subcommand failed.
```

Could you please do the steps as follows?

1) Check if you have installed Windows SDKs.

2) Check where rc.exe is located and add its path to environmment variable PATH.

3) Run developer command prompt in administrator mode.

Please to this https://stackoverflow.com/questions/57269635/unable-to-resolve-cl-exe-is-not-able-to-compile-a-simple-test-program.

**Comment by sfhacker** [comment]
There seems to be a lot of issues related to environment setup. What can we do to prevent this? A wiki? or .... documentation?

**Comment by BillyONeal** [comment]
@sfhacker vcpkg's whole reason to exist is to eliminate such issues.

**Comment by sfhacker** [comment]
> vcpkg's whole reason to exist is to eliminate such issues.

It doesn't seem to be working!


Has this issue been resolved?
There is a new issue reported just now about this same package!

![image](https://user-images.githubusercontent.com/25817529/93101055-2b28d600-f6ed-11ea-80a7-bc5f604b9844.png)

**Comment by BillyONeal** [comment]
>Has this issue been resolved?

No, we are still waiting for responses to the questions above:

> Could you please do the steps as follows?
> 
> 1. Check if you have installed Windows SDKs.
> 2. Check where rc.exe is located and add its path to environmment variable PATH.
> 3. Run developer command prompt in administrator mode.
> 
> Please to this https://stackoverflow.com/questions/57269635/unable-to-resolve-cl-exe-is-not-able-to-compile-a-simple-test-program.

The problem doesn't repro for us so we need help from folks who actually see the problem in determining what's wrong.

**Comment by NancyLi1013** [comment]
Hi @junho103 

Could you please help confirm if you have checked the above info?

**Comment by NancyLi1013** [comment]
@junho103 Please feel feel to reopen this issue if it is still a problem for you.
