### ISSUE TITLE
Building package darknet:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by BasitJaved** [microsoft/vcpkg#13183]
**Host Environment**
- OS: Windows 10
- Compiler: VS 2019

**To Reproduce**
PS C:\Users\b84145862\Yolo\vcpkg> .\vcpkg install darknet[opencv-base,cuda,cudnn]:x64-windows
Computing installation plan...
The following packages will be built and installed:
    darknet[core,cuda,cudnn,opencv-base]:x64-windows
Detecting compiler hash for triplet x64-windows...
Starting package 1/1: darknet:x64-windows
Building package darknet[core,cuda,cudnn,opencv-base]:x64-windows...
Could not locate cached archive: C:\Users\b84145862\AppData\Local\vcpkg/archives\f9\f9c04ef96ee6e022ee6ca4b7559a39cdeb41f108.zip
-- Using cached C:/Users/b84145862/Yolo/vcpkg/downloads/AlexeyAB-darknet-320e6fd8d29f6f7825ef668f15f955f90131f782.tar.gz
-- Cleaning sources at C:/Users/b84145862/Yolo/vcpkg/buildtrees/darknet/src/f90131f782-ecabfe27bf.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/b84145862/Yolo/vcpkg/downloads/AlexeyAB-darknet-320e6fd8d29f6f7825ef668f15f955f90131f782.tar.gz
-- Applying patch fix_shared_static.patch
-- Using source at C:/Users/b84145862/Yolo/vcpkg/buildtrees/darknet/src/f90131f782-ecabfe27bf.clean
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:141 (message):
    Command failed: C:/Users/b84145862/Yolo/vcpkg/downloads/tools/cmake-3.17.2-windows/cmake-3.17.2-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v
    Working Directory: C:/Users/b84145862/Yolo/vcpkg/buildtrees/darknet/x64-windows-dbg
    See logs for more information:
      C:\Users\b84145862\Yolo\vcpkg\buildtrees\darknet\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/darknet/portfile.cmake:139 (vcpkg_install_cmake)
  scripts/ports.cmake:79 (include)

Error: Building package darknet:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: darknet:x64-windows
  Vcpkg version: 2020.06.15-nohash
**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by JonLiu1993** [comment]
@BasitJaved ,
I installed successfully on windows10, Visual Studio Enterprise 2017, can you provide the log: C:\Users\b84145862\Yolo\vcpkg\buildtrees\darknet\install-x64-windows-dbg-out.log

**Comment by BasitJaved** [comment]
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/5142690/install-x64-windows-dbg-out.log)

**Comment by BasitJaved** [comment]
Log file you requested

**Comment by BasitJaved** [comment]
> @BasitJaved ,
> I installed successfully on windows10, Visual Studio Enterprise 2017, can you provide the log: C:\Users\b84145862\Yolo\vcpkg\buildtrees\darknet\install-x64-windows-dbg-out.log

kindly find the log file above... I tried with Visual Studio Enterprise 2017 still same issue

**Comment by KyryloAntoshyn** [comment]
I have the same issue
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/5158094/install-x64-windows-dbg-out.log)

**Comment by KyryloAntoshyn** [comment]
It works with this cuDNN version (7): https://developer.nvidia.com/compute/machine-learning/cudnn/secure/7.6.5.32/Production/10.1_20191031/cudnn-10.1-windows10-x64-v7.6.5.32.zip

![image](https://user-images.githubusercontent.com/26432700/91892721-d3757e00-ec9b-11ea-890c-b78f76373d62.png)

@BasitJaved

**Comment by Linch727** [comment]
@KyryloAntoshyn 
Which cuda version do you have? 
I have the same issue and am using cuda 10.2. I'm not sure if this cudnn is compatible with cuda 10.2

**Comment by KyryloAntoshyn** [comment]
@Linch727 you can use CUDA 10.2.89 with cuDNN 7.6.5.32. It works perfectly. Moreover, I use OpenCV 4.4.0 and Python 3.7.9

**Comment by Linch727** [comment]
@KyryloAntoshyn thank you so much, it works!

**Comment by JonLiu1993** [comment]
@BasitJaved ，It seems from the log that your cuda version is not compatible, my cuda version is V11.0.221, I tried twice to install successfully. You can try to download the cuda version of @KyryloAntoshyn  or download my cuda version, please try again
````
Stored binary cache: C:\Users\vzhli17\AppData\Local\vcpkg\archives\2b\2b5b9390b586a6ddf5578921159979038df948ff.zip
Building package darknet[core,cuda,cudnn,opencv-base]:x64-windows... done
Installing package darknet[core,cuda,cudnn,opencv-base]:x64-windows...
Installing package darknet[core,cuda,cudnn,opencv-base]:x64-windows... done
Elapsed time for package darknet:x64-windows: 5.224 min

Total elapsed time: 5.273 min

The package darknet:x64-windows provides CMake targets:

    find_package(Darknet CONFIG REQUIRED)
    target_link_libraries(main PRIVATE Darknet::dark)
````

**Comment by PhoebeHui** [comment]
@BasitJaved, please reopen this issue if it still be a problem for you.
