### ISSUE TITLE
[python3:x86-windows] build failure

### ISSUE THREAD

**Issue by benoit-fouletier** [microsoft/vcpkg#13184]
**Host Environment**
- OS: Windows 10
- Compiler: VS2015 Pro Update 3, Windows SDK 10.0.10586

**To Reproduce**
`./vcpkg install python3`

**Failure logs** 
```
Building package python3[core]:x86-windows...
Could not locate cached archive: C:\Users\QA\AppData\Local\vcpkg\archives\46\460146c43fbb8961c75f943531fb194bd7cea986.zip
-- Downloading https://github.com/python/cpython/archive/v3.8.3.tar.gz...
-- Extracting source C:/src/vcpkg/downloads/python-cpython-v3.8.3.tar.gz
-- Using source at C:/src/vcpkg/buildtrees/python3/src/v3.8.3-43b03f2bf0.clean
-- Building C:/src/vcpkg/buildtrees/python3/src/v3.8.3-43b03f2bf0.clean-Lib-Win/PCBuild/pythoncore.vcxproj for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: msbuild C:/src/vcpkg/buildtrees/python3/src/v3.8.3-43b03f2bf0.clean-Lib-Win/PCBuild/pythoncore.vcxproj /p:Configuration=Release /t:Rebuild /p:Platform=Win32 /p:PlatformToolset=v140 /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /p:WindowsTargetPlatformVersion=10.0.10586.0 /p:VcpkgManifestInstall=false /m
    Working Directory: C:/src/vcpkg/buildtrees/python3/x86-windows-rel
    Error code: 1
    See logs for more information:
      C:\src\vcpkg\buildtrees\python3\build-x86-windows-rel-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_msbuild.cmake:121 (vcpkg_execute_required_process)
  ports/python3/portfile.cmake:56 (vcpkg_build_msbuild)
  scripts/ports.cmake:79 (include)


Error: Building package python3:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: python3:x86-windows
  Vcpkg version: 2020.06.15-nohash
```
Also see the attached log file: [build-x86-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/5140719/build-x86-windows-rel-out.log)

**Additional context**
I'm trying to build Alembic, which has a lot of dependencies; after building a few, it fails on python3.
I've tried installing python3 directly, same issue.
It used to fail early on, and after seeing similar issues here I installed the Win SDK from the VS2015 installer... now it still fails, but later on.
Alternatively, I'd be happy to remove the python dep as I plan to use the Alembic lib directly from C++, so I'm quite sure python is not strictly needed here... unfortunately I'm unsure if it's possible, nor how.

**Comment by StarGate-One** [comment]
@benoit-fouletier I may\may not be able to assist with the issue.
1. Please attached the `C:\src\vcpkg\buildtrees\python3\build-x86-windows-rel-out.log`.
2. Port alembic does not need port python3, not directly, but is needed by one of the prerequisite dependencies to install alembic. 
3. Below is the dependency tree required to install alembic starting at the bottom to the top:
`->vcpkg depend-info alembic`
`openssl-windows:`
`libffi:`
`openssl: openssl-windows`
`python3: libffi, openssl`
`zlib:`
`openexr: python3, zlib`
`szip:`
`hdf5[szip, zlib]: szip, zlib`
`ilmbase: openexr`
`alembic: hdf5, ilmbase`

alembic requires ports hdf5 and ilmbase installed
ilmbase needs openexr to be installed
hdf5 needs szip and zlib to be installed
szip has no prerequisite dependencies
openexr needs python3 and zlib to be installed
zlib has no prerequisite dependencies
python3 needs libffi and openssl to be installed
openssl needs openssl-windows to be installed
libffi has no prerequisite dependencies
openssl-windows has no prerequisite dependencies

hope this helps understand why python3 is stopping the build of alembic. 👍🏻 
one of alembic's upstream dependencies needs python3

**Comment by benoit-fouletier** [comment]
Dammit I can't believe I forgot to attach the log file, will do tomorrow! From the log it looked like the error came from a git command, sth like `git status HEAD > something/gitbranch.txt`... weird.
In the meantime I tried building from my computer at home, it went through just fine on the first try; I have VS2017 here though, not 2015.
Thanks for the clarification on the python req. I'm new to vcpkg, but if it can solve the dep nightmare as beautifully as it just did here, it's a blessing!

**Comment by benoit-fouletier** [comment]
Here's the log file: [build-x86-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/5140719/build-x86-windows-rel-out.log) (I've also edited my original post).

**Comment by PhoebeHui** [comment]
@benoit-fouletier, what's windows sdk version do you install?

The defination for 'IO_REPARSE_TAG_APPEXECLINK' in c:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\winnt.h line# 13295 for me, so you need to check the if windows sdk setup correctly.

BTW, I tried to build it with vs2015 update3, everything built successfully for me.

Building package python3[core]:x86-windows... done
Installing package python3[core]:x86-windows...
Installing package python3[core]:x86-windows... done
Elapsed time for package python3:x86-windows: 18.52 min

Total elapsed time: 40.41 min

**Comment by PhoebeHui** [comment]
@benoit-fouletier, does this still be a problem for you?

**Comment by benoit-fouletier** [comment]
No it is not, though to be honest I don't remember if I solved the issue on the original computer, or if I simply ended up building on a different computer.

**Comment by PhoebeHui** [comment]
Thanks for your reply!
