### ISSUE TITLE
[freeglut] downloaded file hash is incorrect

### ISSUE THREAD

**Issue by TA-MEI** [microsoft/vcpkg#13193]
PS D:\Software\vcpkg> vcpkg install freeglut
Computing installation plan...
The following packages will be built and installed:
    freeglut[core]:x64-windows
Detecting compiler hash for triplet x64-windows...
Starting package 1/1: freeglut:x64-windows
Building package freeglut[core]:x64-windows...
Could not locate cached archive: C:\Users\MEI\AppData\Local\vcpkg/archives\52\5249350501ab0f81bf3e11e6c38f2756ec4d764b.zip
-- Trying auto-select mirror...
-- Downloading https://sourceforge.net/projects/freeglut/files/freeglut/3.2.1/freeglut-3.2.1.tar.gz/download...
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:99 (message):

  File does not have expected hash:

          File path: [ D:/Software/vcpkg/downloads/temp/freeglut-3.2.1.tar.gz ]
      Expected hash: [ aced4bbcd36269ce6f4ee1982e0f9e3fffbf18c94f785d3215ac9f4809b992e166c7ada496ed6174e13d77c0f7ef3ca4c57d8a282e96cbbe6ff086339ade3b08 ]
        Actual hash: [ c7f9d4c715479421640e484b2834e0a6868844b1e4986513147e911e02f9af1ef8393d6f8196aca50880fcaa870e60a9b91bc429e30199280e31b8c37fb14b3e ]

  The file may have been corrupted in transit.  This can be caused by
  proxies.  If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY
  environment variables to
  "https://user:password@your-proxy-ip-address:port/".

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:194 (test_hash)
  scripts/cmake/vcpkg_from_sourceforge.cmake:152 (vcpkg_download_distfile)
  ports/freeglut/portfile.cmake:1 (vcpkg_from_sourceforge)
  scripts/ports.cmake:79 (include)

Error: Building package freeglut:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: freeglut:x64-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by JonLiu1993** [comment]
Hi@TA-MEI, 
I installed successfully on windows10, Visual Studio Enterprise 2017, I suggest you can modify the Expected hash to Actual hash in the porfile.cmake file and then reinstall.
Expected hash: [ aced4bbcd36269ce6f4ee1982e0f9e3fffbf18c94f785d3215ac9f4809b992e166c7ada496ed6174e13d77c0f7ef3ca4c57d8a282e96cbbe6ff086339ade3b08 ]
    Actual hash: [ c7f9d4c715479421640e484b2834e0a6868844b1e4986513147e911e02f9af1ef8393d6f8196aca50880fcaa870e60a9b91bc429e30199280e31b8c37fb14b3e ]

**Comment by JackBoosY** [comment]
This may be a internal error of sourceforge, please make sure your vcpkg is latest.

**Comment by TA-MEI** [comment]
@JackBoosY @JonLiu1993 thank you· I have install it successfully.
 
I modify  modify the Expected hash to Actual hash in the porfile.cmake file and then reinstall. But,

```
λ vcpkg install freeglut
Computing installation plan...
The following packages will be built and installed:
    freeglut[core]:x64-windows
Detecting compiler hash for triplet x64-windows...
Starting package 1/1: freeglut:x64-windows
Building package freeglut[core]:x64-windows...
Could not locate cached archive: C:\Users\MEI\AppData\Local\vcpkg/archives\f0\f063a421663698794482b693b04c1ca2c4aaec39.zip
-- Trying auto-select mirror...
-- Downloading https://sourceforge.net/projects/freeglut/files/freeglut/3.2.1/freeglut-3.2.1.tar.gz/download...
-- Extracting source D:/Software/vcpkg/downloads/freeglut-3.2.1.tar.gz
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:83 (message):
    Command failed: D:/Software/Scoop/ScoopGlobal/apps/cmake/3.18.2/bin/cmake.exe -E tar xjf D:/Software/vcpkg/downloads/freeglut-3.2.1.tar.gz
    Working Directory: D:/Software/vcpkg/buildtrees/freeglut/src/c7f9d4c715-89e1177f98.tmp
    Error code: 1
    See logs for more information:
      D:\Software\vcpkg\buildtrees\freeglut\extract-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_extract_source_archive.cmake:43 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_extract_source_archive_ex.cmake:115 (vcpkg_extract_source_archive)
  scripts/cmake/vcpkg_from_sourceforge.cmake:190 (vcpkg_extract_source_archive_ex)
  ports/freeglut/portfile.cmake:1 (vcpkg_from_sourceforge)
  scripts/ports.cmake:79 (include)


Error: Building package freeglut:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: freeglut:x64-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.


```


then I delet freeglut-3.2.1.tar.gz and install hash errors showed up then I modify the Expected hash to Actual hash in the porfile.cmake file  again.

```
λ vcpkg install freeglut
Computing installation plan...
The following packages will be built and installed:
    freeglut[core]:x64-windows
Detecting compiler hash for triplet x64-windows...
Starting package 1/1: freeglut:x64-windows
Building package freeglut[core]:x64-windows...
Could not locate cached archive: C:\Users\MEI\AppData\Local\vcpkg/archives\a3\a3249d72083223829dbc1ee7dd93ec8646889083.zip
-- Trying auto-select mirror...
-- Downloading https://sourceforge.net/projects/freeglut/files/freeglut/3.2.1/freeglut-3.2.1.tar.gz/download...
-- Extracting source D:/Software/vcpkg/downloads/freeglut-3.2.1.tar.gz
-- Applying patch use_targets_to_export_x11_dependency.patch
-- Applying patch macOS_Xquartz.patch
-- Applying patch gcc10.patch
-- Applying patch fix-debug-macro.patch
-- Using source at D:/Software/vcpkg/buildtrees/freeglut/src/aced4bbcd3-d62918a414.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: D:/Software/vcpkg/packages/freeglut_x64-windows/share/freeglut/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\MEI\AppData\Local\vcpkg/archives\a3\a3249d72083223829dbc1ee7dd93ec8646889083.zip
Building package freeglut[core]:x64-windows... done
Installing package freeglut[core]:x64-windows...
Installing package freeglut[core]:x64-windows... done
Elapsed time for package freeglut:x64-windows: 26.9 s

Total elapsed time: 29.81 s

```

work it ,thanks everyone
