### ISSUE TITLE
rttr 0.9.6-1 build failure

### ISSUE THREAD

**Issue by ada-rose-dev** [microsoft/vcpkg#13191]
**Host Environment**
- OS: Windows 10
- Compiler: VS 2019

**To Reproduce**
`./vcpkg install rttr --triplet x64-windows`

**Failure logs** 
```
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: C:/dev/path/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v
    Working Directory: C:/dev/path/vcpkg/buildtrees/rttr/x64-windows-dbg
    See logs for more information:
      C:\dev\path\vcpkg\buildtrees\rttr\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/rttr/portfile.cmake:30 (vcpkg_install_cmake)
  scripts/ports.cmake:74 (include)
```

**Additional context**
vcpkg on my machine is up-to-date.

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Please provide the error log: `C:\dev\path\vcpkg\buildtrees\rttr\install-x64-windows-dbg-out.log`

**Comment by ada-rose-dev** [comment]
Thanks for the heads up! Log is attached.
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/5145661/install-x64-windows-dbg-out.log)
[install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/5145662/install-x86-windows-dbg-out.log)

**Comment by LilyWangL** [comment]
Thanks for your reply. This error has been fixed in PR #9252. Now `rttr` build depends on rapidjson which installed by VCPKG. Did you install the latest `rttr`? Now the version of `rttr` is 0.9.6-2. You can remove `[VCPKG_PATH]/buildtrees/rttr/src` and install `rttr` again.

**Comment by LilyWangL** [comment]
Pinging @ada-rose-dev for response.

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
