### ISSUE TITLE
Error: Building package minizip:x64-windows failed with: BUILD_FAILEDuild failure

### ISSUE THREAD

**Issue by Wangzefeng** [microsoft/vcpkg#13198]
**Host Environment**
- OS: Windows
- Package: minizip:x64-windows
  Vcpkg version: 2020.06.15-nohash

**To Reproduce**
vcpkg install --recurse --triplet x64-windows assimp boost-system boost-filesystem ccd eigen3 fcl

**Failure logs** 
Computing installation plan...
The following packages will be built and installed:
    assimp[core]:x64-windows
  * boost-assert[core]:x64-windows
  * boost-build[core]:x64-windows
  * boost-compatibility[core]:x64-windows
  * boost-concept-check[core]:x64-windows
  * boost-config[core]:x64-windows
  * boost-container-hash[core]:x64-windows
  * boost-conversion[core]:x64-windows
  * boost-core[core]:x64-windows
  * boost-detail[core]:x64-windows
    boost-filesystem[core]:x64-windows
  * boost-function-types[core]:x64-windows
  * boost-functional[core]:x64-windows
  * boost-fusion[core]:x64-windows
  * boost-integer[core]:x64-windows
  * boost-io[core]:x64-windows
  * boost-iterator[core]:x64-windows
  * boost-modular-build-helper[core]:x64-windows
  * boost-move[core]:x64-windows
  * boost-mpl[core]:x64-windows
  * boost-optional[core]:x64-windows
  * boost-predef[core]:x64-windows
  * boost-preprocessor[core]:x64-windows
  * boost-smart-ptr[core]:x64-windows
  * boost-static-assert[core]:x64-windows
    boost-system[core]:x64-windows
  * boost-throw-exception[core]:x64-windows
  * boost-tuple[core]:x64-windows
  * boost-type-traits[core]:x64-windows
  * boost-typeof[core]:x64-windows
  * boost-uninstall[core]:x64-windows
  * boost-utility[core]:x64-windows
  * boost-vcpkg-helpers[core]:x64-windows
  * boost-winapi[core]:x64-windows
    ccd[core]:x64-windows
    eigen3[core]:x64-windows
    fcl[core]:x64-windows
  * minizip[core]:x64-windows
  * octomap[core]:x64-windows
  * rapidjson[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Starting package 1/40: minizip:x64-windows
Building package minizip[core]:x64-windows...
Could not locate cached archive: C:\Users\13118\AppData\Local\vcpkg/archives\e3\e37ee02c8e63d19ba19f11556cb8416f1949e0a2.zip
-- Note: minizip only supports static library linkage. Building static library.
-- Using cached C:/Software/vcpkg-master/downloads/madler-zlib-v1.2.11.tar.gz
-- Cleaning sources at C:/Software/vcpkg-master/buildtrees/minizip/src/v1.2.11-bc23884f37.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Software/vcpkg-master/downloads/madler-zlib-v1.2.11.tar.gz
-- Applying patch minizip.patch
-- Using source at C:/Software/vcpkg-master/buildtrees/minizip/src/v1.2.11-bc23884f37.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:83 (message):
    Command failed: C:/Software/vcpkg-master/downloads/tools/powershell-core-6.2.1-windows/powershell.exe -noprofile -executionpolicy Bypass -nologo -file C:/Software/vcpkg-master/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary C:/Software/vcpkg-master/packages/minizip_x64-windows/tools/minizip/miniunz.exe -installedDir C:/Software/vcpkg-master/packages/minizip_x64-windows/bin
    Working Directory: C:/Software/vcpkg-master
    Error code: -2146232797
    See logs for more information:
      C:\Software\vcpkg-master\buildtrees\minizip\copy-tool-dependencies-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_copy_tool_dependencies.cmake:27 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_copy_tool_dependencies.cmake:37 (search_for_dependencies)
  ports/minizip/portfile.cmake:33 (vcpkg_copy_tool_dependencies)
  scripts/ports.cmake:79 (include)

Error: Building package minizip:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: minizip:x64-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by JonLiu1993** [comment]
Hi @Wangzefeng,
I installed successfully on windows10, Visual Studio Enterprise 2017, can you provide us with:
C:\Software\vcpkg-master\buildtrees\minizip\copy-tool-dependencies-err.log?

**Comment by Wangzefeng** [comment]
[copy-tool-dependencies-err.log](https://github.com/microsoft/vcpkg/files/5141012/copy-tool-dependencies-err.log)

**Comment by Wangzefeng** [comment]
@JonLiu1993

**Comment by JonLiu1993** [comment]
@Wangzefeng ,sorry to reply you so late,You upgrade to your version of visual studio and then rebuild, it looks like your problem is very similar to this issue #12849

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/12849.
