### ISSUE TITLE
Not able to install pcl through vcpkg

### ISSUE THREAD

**Issue by RajatGarg1** [microsoft/vcpkg#13202]
I have installed ROS on y windows machine. I am using VS 2019 and VS code.  I have tried the way it is wriiten in the support to install ros. Now when I am trying to install pcl, it is showing error. screenshot is below.

![image](https://user-images.githubusercontent.com/62656238/91556020-51e7be00-e932-11ea-9a81-a522031beb4c.png)

**Comment by StarGate-One** [comment]
Warning: Different source is available for vcpkg (2020.6.15 -> 2020.2.4). **Use .\bootstrap-vcpkg.bat to update.**

The vcpkg.exe is out of date with the ports being installed.

Follow the boldface instructions and try to install pcl again.

**Comment by NancyLi1013** [comment]
Hi @RajatGarg1 
Thanks for posting this issue.
Please do as @StarGate-One suggested above. Run `\bootstrap-vcpkg.bat ` first, then try to rebuild.

**Comment by RajatGarg1** [comment]
I tried this. First ran .\bootstrap-vcpkg.bat then build vcpkg.exe
Stilll such error is occuring

**Comment by StarGate-One** [comment]
@RajatGarg1 you many need to create a new vcpkg instance and try again.

**Comment by NancyLi1013** [comment]
![image](https://user-images.githubusercontent.com/46708020/91959112-cb205000-ed3a-11ea-8265-e224dc76f6ae.png)

It seems that `x86-windows` triplet is not detected in your Visual Studio.
Could you please try to build the triplet `x64-windows `? run `.\vcpkg install pcl:x64-windows`

**Comment by NancyLi1013** [comment]
@RajatGarg1 
Is this still a problem for you?

**Comment by RajatGarg1** [comment]
I shifted to linux. I'll still try after sometime.

**Comment by NancyLi1013** [comment]
I'm closing this issue for now since seems no update.
Please feel free to reopen this issue if it is still a problem for you.
