### ISSUE TITLE
[OGRE3D] Update to the v2.2.3

### ISSUE THREAD

**Issue by ianmanifacier** [microsoft/vcpkg#13214]
Hi,
OGRE3D v2.2.3 has been released since july 5 2020, a vcpkg search shows that the one available dates back from 2019-10-20
Best,

**Comment by JonLiu1993** [comment]
@ianmanifacier ,I did not find OGRE3D in vcpkg, only ogre, I want to know if you need to upgrade the ogre port?

**Comment by NancyLi1013** [comment]
Hi @ianmanifacier 

Sorry for the late response. Do you mean`ogre-next` here? Since there is no port named `ogre3d `in vcpkg.
