### ISSUE TITLE
[New Port Request] mfl

### ISSUE THREAD

**Issue by cpp-niel** [microsoft/vcpkg#13215]
Library name: mfl

Library description: A C++ library which computes the layout information for mathematical formulas provided in TeX-like syntax.

Source repository URL: https://github.com/cpp-niel/mfl

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

The library is CMake based, has no optional features and all dependencies are already in vcpkg

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
