### ISSUE TITLE
[qt5-base] build failure

### ISSUE THREAD

**Issue by brukted** [microsoft/vcpkg#13220]
**Host Environment**
- OS: Windows
- Compiler: msvc 2019

**To Reproduce**
`./vcpkg install qt5-base --triplet x64-windows`

**Failure logs** 
-- Figuring out qt target mkspec. Target arch x64
-- Target mkspec set to: win32-msvc
-- Host mkspec not set. Qt's own buildsystem will try to figure out the host system
-- Using cached F:/vcpkg/downloads/qtbase-everywhere-src-5.15.0.tar.xz
-- Extracting source F:/vcpkg/downloads/qtbase-everywhere-src-5.15.0.tar.xz
-- Applying patch patches/winmain_pro.patch
-- Applying patch patches/windows_prf.patch
-- Applying patch patches/qt_app.patch
-- Applying patch patches/gui_configure.patch
-- Applying patch patches/icu.patch
-- Applying patch patches/xlib.patch
-- Applying patch patches/egl.patch
-- Applying patch patches/8c44d70.diff
-- Applying patch patches/Qt5BasicConfig.patch
-- Applying patch patches/Qt5PluginTarget.patch
-- Applying patch patches/create_cmake.patch
-- Applying patch patches/Qt5GuiConfigExtras.patch
-- Using source at F:/vcpkg/buildtrees/qt5-base/src/5.15.0-f256990b37.clean
-- Configuring x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: F:/vcpkg/buildtrees/qt5-base/src/5.15.0-f256990b37.clean/configure.bat -confirm-license -opensource -verbose -system-zlib -system-libjpeg -system-libpng -system-freetype -system-pcre -system-doubleconversion -system-sqlite -system-harfbuzz -icu -no-angle -opengl dynamic -nomake examples -nomake tests LIBJPEG_LIBS=F:/vcpkg/installed/x64-windows/debug/lib/jpegd.lib ZLIB_LIBS=F:/vcpkg/installed/x64-windows/debug/lib/zlibd.lib "LIBPNG_LIBS=F:/vcpkg/installed/x64-windows/debug/lib/libpng16d.lib F:/vcpkg/installed/x64-windows/debug/lib/zlibd.lib" PCRE2_LIBS=F:/vcpkg/installed/x64-windows/debug/lib/pcre2-16d.lib "FREETYPE_LIBS=F:/vcpkg/installed/x64-windows/debug/lib/freetyped.lib F:/vcpkg/installed/x64-windows/debug/lib/bz2d.lib F:/vcpkg/installed/x64-windows/debug/lib/libpng16d.lib F:/vcpkg/installed/x64-windows/debug/lib/zlibd.lib BROTLI_ENC_DEBUG-NOTFOUND BROTLI_DEC_DEBUG-NOTFOUND BROTLI_COMMON_RELEASE-NOTFOUND" "ICU_LIBS=F:/vcpkg/installed/x64-windows/debug/lib/icuind.lib F:/vcpkg/installed/x64-windows/debug/lib/icutud.lib  F:/vcpkg/installed/x64-windows/debug/lib/icuucd.lib F:/vcpkg/installed/x64-windows/debug/lib/icuiod.lib F:/vcpkg/installed/x64-windows/debug/lib/icudtd.lib Advapi32.lib" QMAKE_LIBS_PRIVATE+=F:/vcpkg/installed/x64-windows/debug/lib/bz2d.lib QMAKE_LIBS_PRIVATE+=F:/vcpkg/installed/x64-windows/debug/lib/libpng16d.lib "PSQL_LIBS=F:/vcpkg/installed/x64-windows/debug/lib/libpq.lib F:/vcpkg/installed/x64-windows/debug/lib/libssl.lib F:/vcpkg/installed/x64-windows/debug/lib/libcrypto.lib ws2_32.lib secur32.lib advapi32.lib shell32.lib crypt32.lib user32.lib gdi32.lib" SQLITE_LIBS=F:/vcpkg/installed/x64-windows/debug/lib/sqlite3.lib "HARFBUZZ_LIBS=F:/vcpkg/installed/x64-windows/debug/lib/harfbuzz.lib F:/vcpkg/installed/x64-windows/debug/lib/freetyped.lib F:/vcpkg/installed/x64-windows/debug/lib/bz2d.lib F:/vcpkg/installed/x64-windows/debug/lib/libpng16d.lib F:/vcpkg/installed/x64-windows/debug/lib/zlibd.lib BROTLI_ENC_DEBUG-NOTFOUND BROTLI_DEC_DEBUG-NOTFOUND BROTLI_COMMON_RELEASE-NOTFOUND" "OPENSSL_LIBS=F:/vcpkg/installed/x64-windows/debug/lib/libssl.lib F:/vcpkg/installed/x64-windows/debug/lib/libcrypto.lib ws2_32.lib secur32.lib advapi32.lib shell32.lib crypt32.lib user32.lib gdi32.lib" -debug -prefix F:/vcpkg/installed/x64-windows -extprefix F:/vcpkg/installed/x64-windows -hostprefix F:/vcpkg/installed/x64-windows/tools/qt5/debug -hostlibdir F:/vcpkg/installed/x64-windows/tools/qt5/debug/lib -hostbindir F:/vcpkg/installed/x64-windows/tools/qt5/debug/bin -archdatadir F:/vcpkg/installed/x64-windows/tools/qt5/debug -datadir F:/vcpkg/installed/x64-windows/share/qt5/debug -plugindir F:/vcpkg/installed/x64-windows/debug/plugins -qmldir F:/vcpkg/installed/x64-windows/debug/qml -headerdir F:/vcpkg/installed/x64-windows/include -libexecdir F:/vcpkg/installed/x64-windows/tools/qt5/debug -bindir F:/vcpkg/installed/x64-windows/debug/bin -libdir F:/vcpkg/installed/x64-windows/debug/lib -I F:/vcpkg/installed/x64-windows/include -L F:/vcpkg/installed/x64-windows/debug/lib -L F:/vcpkg/installed/x64-windows/debug/lib/manual-link -xplatform win32-msvc
    Working Directory: F:/vcpkg/buildtrees/qt5-base/x64-windows-dbg
    Error code: 3
    See logs for more information:
      F:\vcpkg\buildtrees\qt5-base\config-x64-windows-dbg-out.log
      F:\vcpkg\buildtrees\qt5-base\config-x64-windows-dbg-err.log

Call Stack (most recent call first):
  ports/qt5-base/cmake/configure_qt.cmake:110 (vcpkg_execute_required_process)
  ports/qt5-base/portfile.cmake:299 (configure_qt)
  scripts/ports.cmake:79 (include)

[config-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/5145248/config-x64-windows-dbg-err.log)
[config-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/5145249/config-x64-windows-dbg-out.log)

**Comment by Neumann-A** [comment]
Error:
`BROTLI_ENC_DEBUG-NOTFOUND BROTLI_DEC_DEBUG-NOTFOUND BROTLI_COMMON_RELEASE-NOTFOUND`

please upgrade freetype by
```
vcpkg remove freetype
vcpkg install freetype
```

**Comment by brukted** [comment]
@Neumann-A Thanks!
