### ISSUE TITLE
I need to remake the project everytime I add vcpkg packages

### ISSUE THREAD

**Issue by ChrisMGeo** [microsoft/vcpkg#13230]
**Describe the bug**
Sorry if this seems to be an easy question, or if I'm not able to explain it correctly. I'm trying to integrate vcpkg to my VS2019 project, all I do is the following before creating a project.
```
vcpkg install library
vpkg integrate install
```
The above works for my project, but when I want to add new libraries I need to remake the project and make sure to `integrate install` before creating it.

**Environment**
- OS: Windows 10
- Compiler: VS2019(?)

**Expected behavior**
I want to not remake the project everytime I add a library.

**Comment by linquize** [comment]
You only need to run `vcpkg integrate install` once only.
You do not need to run `vcpkg integrate install` after every `vcpkg install`.

**Comment by ChrisMGeo** [comment]
@linquize yes I do understand that now, and I should have made my question more clear, but my problem is that VS2019 doesn't recognize any additional libraries I added after creating the project unless I remake the project (forget the `integrate install` thing, you are right about that).

**Comment by PhoebeHui** [comment]
@ChrisMGeo, could you give us more information? like repro steps and repro code.

I can't repro this issue locally with testing sqlite3.

**Comment by PhoebeHui** [comment]
@ChrisMGeo, please reopen this issue with repro code and repro steps if it still be a problem for you.
