### ISSUE TITLE
[gtest] build failure

### ISSUE THREAD

**Issue by ustchqf** [microsoft/vcpkg#13235]
**Host Environment**
- OS: [centos]
- Compiler: revision

**To Reproduce**
./vcpkg install gtest

**Failure logs** 
```
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:141 (message):
    Command failed: /home/qifeng/apps/Git/vcpkg/downloads/tools/cmake-3.17.2-linux/cmake-3.17.2-Linux-x86_64/bin/cmake --build . --config Debug --target install -- -v
    Working Directory: /home/qifeng/apps/Git/vcpkg/buildtrees/gtest/x64-linux-dbg
    See logs for more information:
      /home/qifeng/apps/Git/vcpkg/buildtrees/gtest/install-x64-linux-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/gtest/portfile.cmake:28 (vcpkg_install_cmake)
  scripts/ports.cmake:79 (include)


Error: Building package gtest:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: gtest:x64-linux
  Vcpkg version: 2020.06.15-unknownhash
```

I have used the command "./vcpkg update"
The information about install-x64-linux-dbg-out.log is available.
```
-- The C compiler identification is GNU 4.4.7
-- The CXX compiler identification is GNU 4.4.7
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /usr/bin/python (found version "2.6.6") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/qifeng/apps/Git/vcpkg/buildtrees/gtest/x64-linux-dbg
```
So how can i slove the problem?

**Comment by StarGate-One** [comment]
Reference vcpkg quick start for UNIX (aka Linux/osx): https://github.com/microsoft/vcpkg#quick-start-unix
>Prerequisites for Linux:
>g++ >= 6

From /home/qifeng/apps/Git/vcpkg/buildtrees/gtest/install-x64-linux-dbg-out.log:
`-- The C compiler identification is GNU 4.4.7`
`-- The CXX compiler identification is GNU 4.4.7`

**Comment by LilyWangL** [comment]
Pinging @ustchqf for response. Does this issue still occur after updating `G++`?

**Comment by ustchqf** [comment]
> Reference vcpkg quick start for UNIX (aka Linux/osx): https://github.com/microsoft/vcpkg#quick-start-unix
> 
> > Prerequisites for Linux:
> > g++ >= 6
> 
> From /home/qifeng/apps/Git/vcpkg/buildtrees/gtest/install-x64-linux-dbg-out.log:
> `-- The C compiler identification is GNU 4.4.7`
> `-- The CXX compiler identification is GNU 4.4.7`

Thank you for your reply.
Actually, I have installed the g++7.3.0. Because I am not the manager, so I am not permitted to use root. So I install the new version in my own directory. When I use "g++ -v" to clarify my g++ version, it shows 7.3.0. However, when i used vcpkg to install test, The C compiler identification is GNU 4.4.7, so can i change the default compiler directory in vcpkg?

**Comment by ustchqf** [comment]
> Pinging @ustchqf for response. Does this issue still occur after updating `G++`?

I am not permitted to use root, so i install the g++ new version in my own directory. It doesn't work because the vcpkg can't use the new version.

**Comment by LilyWangL** [comment]
Thanks for your reply. Please provide the error log: `/home/qifeng/apps/Git/vcpkg/buildtrees/gtest/install-x64-linux-dbg-out.log`

**Comment by ustchqf** [comment]
> Thanks for your reply. Please provide the error log: `/home/qifeng/apps/Git/vcpkg/buildtrees/gtest/install-x64-linux-dbg-out.log`

This is the install-x64-linux-dbg-out.log.
-- The C compiler identification is GNU 4.4.7
-- The CXX compiler identification is GNU 4.4.7
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /usr/bin/python (found version "2.6.6") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/qifeng/apps/Git/vcpkg/buildtrees/gtest/x64-linux-dbg

Thanks for you attention.

**Comment by LilyWangL** [comment]
This should be `config-x64-linux-dbg-out.log`, it is not `install-x64-linux-dbg-out.log`. You can attach `install-x64-linux-dbg-out.log` on this page.

**Comment by ustchqf** [comment]
> This should be `config-x64-linux-dbg-out.log`, it is not `install-x64-linux-dbg-out.log`. You can attach `install-x64-linux-dbg-out.log` on this page.

I am sorry for the error I have made. Here is the log file. I am new in github, so if you can't download it ,please let me know.
[install-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/5194221/install-x64-linux-dbg-out.log)

**Comment by LilyWangL** [comment]
This error should be caused by low gcc version, you can try the following steps:
1. `.\vcpkg.exe install gtest:x64-windows --editable`, it will build failed.
2. Modify _[VCPKG_path]\buildtrees\gtest\src\ase-1.10.0-7231afa423\CMakeLists.txt_, add `add_definitions(-std=c++11)` to Line 5.
3. Using `.\vcpkg.exe install gtest:x64-windows --editable` to install getst again.

**Comment by ustchqf** [comment]
> This error should be caused by low gcc version, you can try the following steps:
> 
> 1. `.\vcpkg.exe install gtest:x64-windows --editable`, it will build failed.
> 2. Modify _[VCPKG_path]\buildtrees\gtest\src\ase-1.10.0-7231afa423\CMakeLists.txt_, add `add_definitions(-std=c++11)` to Line 5.
> 3. Using `.\vcpkg.exe install gtest:x64-windows --editable` to install getst again.

Thank you for your reply. But my system is Linux(Centos), so I can't execute the commands.
I have used these commands, but it didn't work.
1. ./vcpkg install gtest --editable
2. Modify _[VCPKG_path]\buildtrees\gtest\src\ase-1.10.0-7231afa423\CMakeLists.txt_, add `add_definitions(-std=c++11)` to Line 5.
3. Using `.\vcpkg install gtest --editable` to install getst again.

I guess the problem may caused by my low gcc -version. But I am not permitted to use root. I have installed new version gcc in my own directory, when I  use the command "gcc -v", it shows that my gcc version is 7.3.0. However, when I installed the gtest, it shows that my gcc version is 4.4.7. So can I change the gcc default directory when i install the gtest?

**Comment by LilyWangL** [comment]
I have no idea how to change the gcc default directory. To resolve this error: `/home/qifeng/apps/Git/vcpkg/buildtrees/gtest/src/ase-1.10.0-7231afa423.clean/googletest/include/gtest/internal/gtest-port.h:972: error: ‘nullptr’ was not declared in this scope`, you can use `null` instead of all `nullptr` in source. Please remember to use `--editable` when you installing getst.

**Comment by ustchqf** [comment]
> I have no idea how to change the gcc default directory. To resolve this error: `/home/qifeng/apps/Git/vcpkg/buildtrees/gtest/src/ase-1.10.0-7231afa423.clean/googletest/include/gtest/internal/gtest-port.h:972: error: ‘nullptr’ was not declared in this scope`, you can use `null` instead of all `nullptr` in source. Please remember to use `--editable` when you installing getst.

Thank you very much for your reply. I will try it later.

**Comment by JackBoosY** [comment]
@ustchqf Any results?

**Comment by ustchqf** [comment]
> @ustchqf Any results?

No,now I am build new environment for it in a new linux server.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
