### ISSUE TITLE
[nettle] build failure

### ISSUE THREAD

**Issue by zhaoliangcn** [microsoft/vcpkg#13245]
**Host Environment**
- OS: [windows10 2004]
- Compiler: visual studio 2017

**To Reproduce**
`./vcpkg install nettle`

**Failure logs** 
用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
版权所有(C) Microsoft Corporation。保留所有权利。

生成启动时间为 2020/8/31 9:50:25。
     1>项目“E:\vcpkg\buildtrees\nettle\x86-windows-rel\eb52c3da41-e03f56976f.clean\SMP\libnettle.sln”在节点 1 上(Rebuild 个目标)。
     1>ValidateSolutionConfiguration:
         正在生成解决方案配置“ReleaseDLL|x86”。
       ValidateProjects:
         在解决方案配置“ReleaseDLL|x86”中未选定生成项目“desdata”。
         在解决方案配置“ReleaseDLL|x86”中未选定生成项目“eccdata”。
     1>项目“E:\vcpkg\buildtrees\nettle\x86-windows-rel\eb52c3da41-e03f56976f.clean\SMP\libnettle.sln”(1)正在节点 1 上生成“E:\vcpkg\buildtrees\nettle\x86-windows-rel\eb52c3da41-e03f56976f.clean\SMP\libnettle.vcxproj”(2) (Rebuild 个目标)。
     2>CoreClean:
         正在创建目录“E:\vcpkg\buildtrees\nettle\x86-windows-rel\eb52c3da41-e03f56976f.clean\SMP\obj\ReleaseDLL\Win32\libnettle\”。
       PrepareForBuild:
         正在创建目录“E:\vcpkg\buildtrees\nettle\x86-windows-rel\eb52c3da41-e03f56976f.clean\SMP\..\msvc\”。
         正在创建目录“E:\vcpkg\buildtrees\nettle\x86-windows-rel\eb52c3da41-e03f56976f.clean\SMP\obj\ReleaseDLL\Win32\libnettle\libnettle.tlog\”。
       InitializeBuildStatus:
         正在创建“E:\vcpkg\buildtrees\nettle\x86-windows-rel\eb52c3da41-e03f56976f.clean\SMP\obj\ReleaseDLL\Win32\libnettle\libnettle.tlog\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
       _YASM:
         x86\aes-decrypt-internal.s
         cmd.exe /D /C "C:\Users\coder\AppData\Local\Temp\tmpdb89ec94caf040228283b93e4ff7f85c.cmd"
         ""yasm.exe -Xvc -f win32 -o "E:\vcpkg\buildtrees\nettle\x86-windows-rel\eb52c3da41-e03f56976f.clean\SMP\obj\ReleaseDLL\Win32\libnettle\aes-decrypt-internal.obj" -rraw -pgas  "E:\vcpkg\buildtrees\nettle\x86-windows-rel\eb52c3da41-e03f56976f.clean\SMP\x86\aes-decrypt-internal.s"
     2>E:\vcpkg\installed\x86-windows\share\vs-yasm\yasm.targets(50,5): error MSB3721: 命令“""yasm.exe -Xvc -f win32 -o "E:\vcpkg\buildtrees\nettle\x86-windows-rel\eb52c3da41-e03f56976f.clean\SMP\obj\ReleaseDLL\Win32\libnettle\aes-decrypt-internal.obj" -rraw -pgas  "E:\vcpkg\buildtrees\nettle\x86-windows-rel\eb52c3da41-e03f56976f.clean\SMP\x86\aes-decrypt-internal.s"”已退出，返回代码为 -1073741819。 [E:\vcpkg\buildtrees\nettle\x86-windows-rel\eb52c3da41-e03f56976f.clean\SMP\libnettle.vcxproj]
     2>已完成生成项目“E:\vcpkg\buildtrees\nettle\x86-windows-rel\eb52c3da41-e03f56976f.clean\SMP\libnettle.vcxproj”(Rebuild 个目标)的操作 - 失败。
     1>已完成生成项目“E:\vcpkg\buildtrees\nettle\x86-windows-rel\eb52c3da41-e03f56976f.clean\SMP\libnettle.sln”(Rebuild 个目标)的操作 - 失败。

生成失败。

       “E:\vcpkg\buildtrees\nettle\x86-windows-rel\eb52c3da41-e03f56976f.clean\SMP\libnettle.sln”(Rebuild 目标) (1) ->
       “E:\vcpkg\buildtrees\nettle\x86-windows-rel\eb52c3da41-e03f56976f.clean\SMP\libnettle.vcxproj”(Rebuild 目标) (2) ->
       (_YASM 目标) -> 
         E:\vcpkg\installed\x86-windows\share\vs-yasm\yasm.targets(50,5): error MSB3721: 命令“""yasm.exe -Xvc -f win32 -o "E:\vcpkg\buildtrees\nettle\x86-windows-rel\eb52c3da41-e03f56976f.clean\SMP\obj\ReleaseDLL\Win32\libnettle\aes-decrypt-internal.obj" -rraw -pgas  "E:\vcpkg\buildtrees\nettle\x86-windows-rel\eb52c3da41-e03f56976f.clean\SMP\x86\aes-decrypt-internal.s"”已退出，返回代码为 -1073741819。 [E:\vcpkg\buildtrees\nettle\x86-windows-rel\eb52c3da41-e03f56976f.clean\SMP\libnettle.vcxproj]

    0 个警告
    1 个错误

已用时间 00:00:01.23

**Comment by JackBoosY** [comment]
Duplicate with #12240.
