### ISSUE TITLE
Version info not recorded

### ISSUE THREAD

**Issue by codicodi** [Microsoft/vcpkg#1325]
I've rerun the bootstrap script and all newly installed packages are out of date:

```
PS G:\dev\vcpkg> ./vcpkg install utf8proc
The following packages will be built and installed:
    utf8proc:x64-windows
Building package utf8proc:x64-windows...
   ...everything as expected...
Installing package utf8proc:x64-windows... done

PS G:\dev\vcpkg> ./vcpkg update
Using local portfile versions. To update the local portfiles, use `git pull`.
The following packages differ from their port versions:
    utf8proc:x64-windows              -> 2.1.0

To update these packages, run
    .\vcpkg remove --outdated
    .\vcpkg install utf8proc:x64-windows
```
I've rebuilt vcpkg.exe for a few recent commits and I think this one introduced this regression: https://github.com/Microsoft/vcpkg/commit/8741214bf69d1209a1e6d405ed8561d27f04436a

**Comment by ras0219-msft** [comment]
Thank you very much for reporting this and reducing the commit down!

Implicit conversion from `std::string` to `Optional<std::string>` bit me, since empty string is still a "filled" value :). This then got written into the Version field and resulted in the behavior you observed.

Thanks again!
