### ISSUE TITLE
What to validate when post build validation?

### ISSUE THREAD

**Issue by blackknifes** [microsoft/vcpkg#13265]
When asking a question please also include where you looked for an answer (so we can update the documentation if needed).
I try to build sqlite3 with VC-LTL, it throw a error:
![image](https://user-images.githubusercontent.com/9638801/91792109-57e9e180-ec47-11ea-9d0c-7ed3a45eb6b7.png)

**Comment by BillyONeal** [comment]
The set of post build checks isn't contractual; we add to the set over time as we discover ports and projects that take action hostile to cohesive function of the overall catalog.

I believe most of these post build checks are located in https://github.com/microsoft/vcpkg/blob/master/toolsrc/src/vcpkg/postbuildlint.cpp

**Comment by blackknifes** [comment]
Thanks, it is helpful.
