### ISSUE TITLE
[gmp] x64-mingw-static build failure

### ISSUE THREAD

**Issue by PanScout** [microsoft/vcpkg#13262]
**Host Environment**
- OS: Windows 10
- Compiler: revision

**To Reproduce**
`./vcpkg install gmp:x64-mingw-static`

**Failure logs** 
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:83 (message):
    Command failed: msbuild C:/tools/vcpkg/buildtrees/gmp/x64-mingw-static-rel/adcc6b3cc4-2b6258d695.clean/SMP/libgmp.sln /p:Configuration=Release /p:UseEnv=True /t:Rebuild /p:Platform=x64 /p:PlatformToolset=external /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /p:WindowsTargetPlatformVersion= /p:VcpkgTriplet=x64-mingw-static /p:VcpkgCurrentInstalledDir=C:/tools/vcpkg/installed/x64-mingw-static /p:VcpkgManifestInstall=false /m /p:WholeProgramOptimization=false /p:ForceImportBeforeCppTargets=C:/tools/vcpkg/scripts/buildsystems/msbuild/vcpkg.targets /p:VcpkgApplocalDeps=false
    Working Directory: C:/tools/vcpkg/buildtrees/gmp/x64-mingw-static-rel/adcc6b3cc4-2b6258d695.clean
    Error code: The system cannot find the file specified
    See logs for more information:

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_msbuild.cmake:162 (vcpkg_execute_required_process)
  ports/gmp/portfile.cmake:53 (vcpkg_install_msbuild)
  scripts/ports.cmake:79 (include)

Error: Building package gmp:x64-mingw-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: gmp:x64-mingw-static
  Vcpkg version: 2020.06.15-nohash

Any help would be greatly appreciated!

**Comment by JonLiu1993** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
