### ISSUE TITLE
[cuda:x64-windows] build failure

### ISSUE THREAD

**Issue by bhwqy** [microsoft/vcpkg#13270]
I installed CUDA in `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2`. Then, it seems that vcpkg failed to find where cuda is and the installation failed. How can I solve this?

**Host Environment**
- OS: Windows 10
- Compiler: Visual Studio 2019
- CUDA: 10.2

**To Reproduce**
 1. `nvcc --version`

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:32:27_Pacific_Daylight_Time_2019
Cuda compilation tools, release 10.2, V10.2.89

2. `.\vcpkg.exe install cuda:x64-windows`

Computing installation plan...
The following packages will be built and installed:
    cuda[core]:x64-windows
Detecting compiler hash for triplet x64-windows...
Starting package 1/1: cuda:x64-windows
Building package cuda[core]:x64-windows...
Could not locate cached archive: C:\Users\admin\AppData\Local\vcpkg/archives\dc\dc44fdcc6d6e0a90de6ff1e1cbd0b03b16fbade6.zip
-- Executing NVCC-NOTFOUND --version resulted in error: 1
CMake Error at ports/cuda/portfile.cmake:66 (message):
  Could not find CUDA.  Before continuing, please download and install CUDA
  (v10.1.0 or higher) from:

      https://developer.nvidia.com/cuda-downloads

Call Stack (most recent call first):
  scripts/ports.cmake:79 (include)

Error: Building package cuda:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: cuda:x64-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by bhwqy** [comment]
I find that nvcc is installed in another location by the command

`Get-Command nvcc

D:\Program Files (x86)\cuda\bin\nvcc.exe`

So is there any solution to this problem?

**Comment by JackBoosY** [comment]
Please set this path to environment var `CUDA_PATH` and try again.

**Comment by bhwqy** [comment]
Thank you, this fixes the bug.
