### ISSUE TITLE
[SOCI] SOCIConfig.cmake not found

### ISSUE THREAD

**Issue by nokutu** [microsoft/vcpkg#13272]
When installing SOCI, a cmake config file called `SOCI.cmake` is created inside the installed folder, but it should be `SOCIConfig.cmake` in order to be able to import it correctly.

**Comment by NancyLi1013** [comment]
Hi @nokutu 
Thanks for posting this issue.

I checked the source code and found that there is already `SociConfig.cmake` file in _SOURTH_PATH/cmake_ directory.
But this file seems not to be the one that we need. 

Currently, `SOCI.cmake` is the one that upstream supports. In fact, the file name have no effects on the usage. 
If you would like to use `SOCIConfig.cmake`, it would be better to report this to upstream.

Thanks.

**Comment by NancyLi1013** [comment]
@nokutu 
Please let me know if you still have any concerns about this issue.
