### ISSUE TITLE
Hash mismatch while downloading Nuget.exe

### ISSUE THREAD

**Issue by yangwuan55** [Microsoft/vcpkg#1327]
There is the error:

```

Mismatching hash of the downloaded nuget
所在位置 C:\Users\jcx\vcpkg\scripts\fetchDependency.ps1:214 字符: 14
+         throw <<<<  [System.IO.FileNotFoundException] ("Mismatching hash of t
he downloaded " + $Dependency)
    + CategoryInfo          : OperationStopped: (:) [], FileNotFoundException
    + FullyQualifiedErrorId : Mismatching hash of the downloaded nuget


```

**Comment by jasjuang** [comment]
you need to give us more information so we can help

**Comment by ras0219-msft** [comment]
Hi @yangwuan55,

It looks like the hash of the file we downloaded from [1] does not match what we expected [2].

The first thing to try would be to download the file yourself from that website and replace the version in `downloads\nuget-3.5.0\nuget.exe`, then re-run bootstrap. Let us know if you still have issues!

[1] https://dist.nuget.org/win-x86-commandline/v3.5.0/nuget.exe
[2] 399ec24c26ed54d6887cde61994bb3d1cada7956c1b19ff880f06f060c039918

**Comment by yangwuan55** [comment]
Thanks!
