### ISSUE TITLE
sqlite-orm build failure

### ISSUE THREAD

**Issue by quickiwiki** [microsoft/vcpkg#13279]
**Host Environment**
- OS: Linux Ubuntu 18.04
- Compiler: The CXX compiler identification is GNU 8.4.0

**To Reproduce**
`./vcpkg install sqlite-orm

create a basic project that uses sqlite-orm
add  to CmakeLists.txt

  find_package(SqliteOrm CONFIG REQUIRED)
     target_link_libraries(main PRIVATE sqlite_orm::sqlite_orm)

**Failure logs** 
CMake Error at /home/user/vcpkg/installed/x64-linux/share/SqliteOrm/SqliteOrmConfig.cmake:33 (include):
  include could not find load file:

    /SqliteOrmTargets.cmake
Call Stack (most recent call first):
  /home/user/vcpkg/scripts/buildsystems/vcpkg.cmake:461 (_find_package)
  CMakeLists.txt:22 (find_package)

-- Found sqlite_orm: /home/user/vcpkg/installed/x64-linux
-- Configuring incomplete, errors occurred!
See also "/home/user/SRC/project/build/CMakeFiles/CMakeOutput.log".
See also "/home/user/SRC/project/build/CMakeFiles/CMakeError.log".
make: *** No targets specified and no makefile found.  Stop.

**Additional context**

**Comment by sfhacker** [comment]
We do not use Linux, but tried anyway!

![image](https://user-images.githubusercontent.com/25817529/91854753-8a2b2b80-eca7-11ea-92bb-5a792eb9a026.png)

**Comment by NancyLi1013** [comment]
Hi @quickiwiki 
Thanks for posting this issue.
I submitted a PR #13328  to fix this issue.
Could you please help confirm if this can work for you?

**Comment by quickiwiki** [comment]
It works, thank you so much
