### ISSUE TITLE
[msys2] download components failure: SSL connect error

### ISSUE THREAD

**Issue by Christsnatcher** [microsoft/vcpkg#13286]
**Host Environment**
- Windows 8.1 Home x64
- MSVC++ 14.27 _MSC_VER == 1927 (Visual Studio 2019 Version 16.7)

**To Reproduce**
vcpkg install [ffmpeg] (no triplet does work, and no additional feature does matter)

**Failure logs** 
```
D:\Code\Repos\vcpkg>vcpkg install ffmpeg:x86-windows
Computing installation plan...
The following packages will be built and installed:
    ffmpeg[avcodec,avdevice,avfilter,avformat,avresample,core,postproc,swresample,swscale]:x86-windows
Detecting compiler hash for triplet x86-windows...
Starting package 1/1: ffmpeg:x86-windows
Building package ffmpeg[avcodec,avdevice,avfilter,avformat,avresample,core,postproc,swresample,swscale]:x86-windows...
Could not locate cached archive: C:\Users\Daniel\AppData\Local\vcpkg/archives\3f\3f551c8ffdfb689003869e2d0981ea9fa7bc696e.zip
-- Using cached D:/Code/Repos/vcpkg/downloads/ffmpeg-ffmpeg-n4.2.tar.gz
-- Extracting source D:/Code/Repos/vcpkg/downloads/ffmpeg-ffmpeg-n4.2.tar.gz
-- Applying patch 0001-create-lib-libraries.patch
-- Applying patch 0003-fix-windowsinclude.patch
-- Applying patch 0004-fix-debug-build.patch
-- Applying patch 0005-fix-libvpx-linking.patch
-- Applying patch 0006-fix-StaticFeatures.patch
-- Applying patch 0007-fix-lib-naming.patch
-- Applying patch 0008-Fix-wavpack-detection.patch
-- Applying patch 0009-Fix-fdk-detection.patch
-- Applying patch 0010-Fix-x264-detection.patch
-- Applying patch 0011-Fix-x265-detection.patch
-- Applying patch 0012-Fix-ssl-110-detection.patch
-- Using source at D:/Code/Repos/vcpkg/buildtrees/ffmpeg/src/n4.2-2f6d2343f6.clean
-- Downloading https://repo.msys2.org/msys/x86_64/bash-4.4.023-2-x86_64.pkg.tar.xz...
-- Downloading https://repo.msys2.org/msys/x86_64/bash-4.4.023-2-x86_64.pkg.tar.xz... Failed. Status: 35;"SSL connect error"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:178 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_acquire_msys.cmake:97 (vcpkg_download_distfile)
  scripts/cmake/vcpkg_acquire_msys.cmake:148 (msys_package)
  ports/ffmpeg/portfile.cmake:59 (vcpkg_acquire_msys)
  scripts/ports.cmake:79 (include)


Error: Building package ffmpeg:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: ffmpeg:x86-windows
  Vcpkg version: 2020.06.15-nohash
```

**Additional context**
Hello,

the issue here doesn't really seem to be a "port bug", because it affects all ports which need MSYS2 for building. The problem basically is that https://repo.msys2.org since a few days stricly disallows all other security protocols but TLS 1.3 - which users of other Windows OS but latest Windows 10 (like me) are unable to use for global WinHttp connections as it's simply not implemented in the resp. OS (and obviously never will be).

Since vcpkg apparently tries to acquire the package using PowerShell we are bound to WinHttp limits and the download has to fail, while 3rd-party-programs like e.g. wget, which support TLS 1.3 natively, are able to download from https://repo.msys2.org perfectly fine. So I actually have the package vcpkg tries to download for more than one hour on my HDD already, but fail to figure out where to place it so that vcpkg would pick it up (as quick bypass). Could you please tell me? Thank you.

The problem I mention here is a pretty huge one given that it effectively excludes all non-Win 10 users from the possibility to build MSYS2-dependent ports (which are not just a few as you surely know). I strongly recommend to add alternate download urls in addition to https://repo.msys2.org as soon as possible, thank you very much.

[ffmpeg.zip](https://github.com/microsoft/vcpkg/files/5158747/ffmpeg.zip)

**Comment by JackBoosY** [comment]
See https://github.com/microsoft/vcpkg/issues/13217#issuecomment-683663095 for workaround.

**Comment by Voskrese** [comment]
?
`powershell "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; (New-Object System.Net.WebClient).DownloadFile('https://repo.msys2.org/msys/x86_64/bash-4.4.023-2-x86_64.pkg.tar.xz')"`

**Comment by Christsnatcher** [comment]
@JackBoosY : Thank you very much for linking me to this workaround!

@Voskrese  Both commands fails in PS for me (see output below), also I explicitly mentioned that ONLY TLS 1.3 would work, NOT 1.2.

```
S E:\downloads\1> powershell "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; (New-Object System.Net.WebClient).DownloadFile('https://repo.msys2.org/msys/x86_64/bash-4.4.023-2-x86_64.pkg.tar.xz')"
powershell : Cannot find an overload for "DownloadFile" and the argument count: "1".
At line:1 char:1
+ powershell "[Net.ServicePointManager]::SecurityProtocol = [Net.Securi ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Cannot find an ...ent count: "1".:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
At line:1 char:82
+ ... pe]::Tls12; (New-Object System.Net.WebClient).DownloadFile('https://r ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest
 

PS E:\downloads\1> powershell -Command "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; Invoke-WebRequest https://repo.msys2.org/msys/x86_64/bash-4.4.023-2-x86_64.pkg.tar.xz -OutFile bash-4.4.023-2-x86_64.pkg.tar.xz"
powershell : Invoke-WebRequest : The request was aborted: Could not create SSL/TLS secure 
At line:1 char:1
+ powershell -Command "[Net.ServicePointManager]::SecurityProtocol = [N ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Invoke-WebReque...SSL/TLS secure :String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
channel.
At line:1 char:82
+ ... pe]::Tls12; Invoke-WebRequest https://repo.msys2.org/msys/x86_64/bash ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:Htt 
   pWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShe 
   ll.Commands.InvokeWebRequestCommand
```

**Comment by Voskrese** [comment]
TLS 1.2 work

![2020-09-02_123538](https://user-images.githubusercontent.com/10104740/91932467-d06ca300-ed18-11ea-95be-45c5e3447072.png)

**Comment by linquize** [comment]
if https:// fail,  use http:// as fallback. Since we verify file hash, transport layer security is less important.

**Comment by JackBoosY** [comment]
Hi guys, can you test if #13298 works?

**Comment by Christsnatcher** [comment]
@JackBoosY : Unfortunately it doesn't work, and it can't, since you didn't address the actual issue. Non-Windows 10 systems do NOT have TLS 1.3 implemented at all, so no matter if the version gets detected correctly, trying to connect still fails - obviously.

@Voskrese : You appaarently don't understand. TLS v1.2 does NOT work, just read the explanations on the site itself, ONLY TLS 1.3 does. Your Windows 10 PowerShell just adapts to this scenario and uses TLS 1.3 without telling you about it, that's why the command works for you - for me it obviously doesn't.

**Comment by JackBoosY** [comment]
@Christsnatcher Sorry, please pull the latest and try again, I forgot to modify some places.

**Comment by Christsnatcher** [comment]
Ah, no problem. We wrote at the same time, I edited my previous post to reflect that your fix is working perfectly fine, thank you so much- now on to merging! ;)

**Comment by Christsnatcher** [comment]
I see that commit 46e25a10d7295d3bc107d6f51ce0e2851877f393 has substituted downloads via pacman with direct downloads, but unfortunately not resolved this issue. Well, the magic word is patience I guess (though it's hard given a proper fix is available for more than one week already). Cheers!

**Comment by JackBoosY** [comment]
@Christsnatcher We are looking for a solution to enable TLS>1.2 in Windows 7.

**Comment by linquize** [comment]
@Christsnatcher what is your error message?

**Comment by Christsnatcher** [comment]
@JackBoosY: I honestly think this will be impossible if MS does not actively supports backporting. And I would still have the same issue on Windows 8.1, right?

@linquize: Please check the first post.

**Comment by allenchou13** [comment]
i add one line at scripts\cmake\vcpkg_download_distfile.cmake:161, then download ok
```cmake
string(REGEX REPLACE "^https://repo\.msys2\.org" "http://mirrors.ustc.edu.cn/msys2" url ${url})
```

**Comment by BillyONeal** [comment]
@allenchou13 That's an OK temporary fix but it wouldn't be appropriate to replace the primary mirror with one of the replicas permanently,

**Comment by Christsnatcher** [comment]
@BillyONeal : I agree 100%, there are abviously dozens of potential "workarounds" available, but an issue as severe as this one simply has to to be resolved a proper way, e.g. by the solution you suggested.

**Comment by WHULS** [comment]
> i add one line at scripts\cmake\vcpkg_download_distfile.cmake:161, then download ok
> 
> ```cmake
> string(REGEX REPLACE "^https://repo\.msys2\.org" "http://mirrors.ustc.edu.cn/msys2" url ${url})
> ```

It works for me!!!🌹🌹🌹
It's a perfect answer for Chinese users!!!

**Comment by pkgw** [comment]
I looks to me like this issue has been fixed by msys2.org starting to allow TLS1.2 again?

**Comment by Christsnatcher** [comment]
@pkgw : You're actually right, wondering what has been their reasoning behind this decision.

https://i.gyazo.com/b2a1d6d44ad623115154de56de7c649c.png

**Comment by JackBoosY** [comment]
Fixed by msys upstream.

**Comment by SuperDongNie** [comment]
good
