### ISSUE TITLE
[vcpkg] CMAKE_C_COMPILER and CMAKE_CXX_COMPILER are not set

### ISSUE THREAD

**Issue by JackBoosY** [microsoft/vcpkg#13294]
In `vcpkg-configure-cmake`, we doesn't set `CMAKE_C_COMPILER` or `CMAKE_CXX_COMPILER`, causes cmake to automatically acquire the compiler.
After llvm built clang++, when we set up and used `ninja` or `Visual Studio`, cmake obtained and detected `clang++`, which caused some parameters (such as /nologo /DWIN32 /D_WINDOWS) we set to destroy the detection process.
Example error:
```
CMake Error at D:/downloads/tools/cmake-3.18.2-windows/cmake-3.18.2-win32-x86/share/cmake-3.18/Modules/CMakeTestCCompiler.cmake:66 (message):
  The C compiler

    "D:/installed/x64-windows/bin/clang.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: D:/buildtrees/ignition-msgs1/x64-windows-rel/CMakeFiles/CMakeTmp
    
    Run Build Command(s):D:/downloads/tools/ninja/1.10.0-windows/ninja.exe cmTC_f8bc8 && [1/2] Building C object CMakeFiles/cmTC_f8bc8.dir/testCCompiler.c.obj
    FAILED: CMakeFiles/cmTC_f8bc8.dir/testCCompiler.c.obj 
    D:\installed\x64-windows\bin\clang.exe   /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP   -g -Xclang -gcodeview -O0 -D_DEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrtd -MD -MT CMakeFiles/cmTC_f8bc8.dir/testCCompiler.c.obj -MF CMakeFiles\cmTC_f8bc8.dir\testCCompiler.c.obj.d -o CMakeFiles/cmTC_f8bc8.dir/testCCompiler.c.obj -c testCCompiler.c
    clang: error: no such file or directory: '/nologo'
    clang: error: no such file or directory: '/DWIN32'
    clang: error: no such file or directory: '/D_WINDOWS'
    clang: error: no such file or directory: '/W3'
    clang: error: no such file or directory: '/utf-8'
    clang: error: no such file or directory: '/MP'
    ninja: build stopped: subcommand failed.
```

**Comment by Voskrese** [comment]
default set CC=cl CXX=cl ?

**Comment by cenit** [comment]
Mostly, clang should go to tools and not bin folder?

**Comment by BillyONeal** [comment]
Yeah, we shouldn't ever be finding a compiler in the "installed" directory. @Voskrese 's suggestion is probably the right fix.

**Comment by BillyONeal** [comment]
@cenit That also seems appropriate but I suspect it might require a more.... invasive modification of llvm's build than we would like. If that's possible it would be great!

**Comment by Neumann-A** [comment]
>default set CC=cl CXX=cl ?

That breaks make based ports which require the autotool `compile` wrapper for cl.

In my point of view it is better to include/set those values directly in the toolchain.

**Comment by BillyONeal** [comment]
Related: https://github.com/microsoft/vcpkg/issues/5721

**Comment by BillyONeal** [comment]
@strega-nil is looking at this.

This is causing `ignition-msgs1` and `ignition-msgs5` to fail sporadically in CI.
