### ISSUE TITLE
How do VCPKG copy .dll to binary build directory

### ISSUE THREAD

**Issue by jmkerloch** [microsoft/vcpkg#13308]
I'm using VCPKG to get most of my external librairies and it works really well with CMake.
One of the feature i'm really glad exists is the ability for VCPKG to copy .dll to binary build directory.
Let's say that my application App need libcurl.
I'm linking with curl with :

```
target_link_libraries(App
		PUBLIC
			${CURL_LIBRARIES}
		)
```
After building the `libcurl.dll`  is available  in my application building directory.

I would like to implement this feature in one of the external library i'm using.

Does anyone knows how VCPKG achieve this feature ?

Thanks !

**Comment by LilyWangL** [comment]
In `CMakeLists.txt`, these codes will install *.dll and *.lib to the correct directory.
```
install(
  TARGETS taret_name
  RUNTIME DESTINATION bin
  LIBRARY DESTINATION lib
  ARCHIVE DESTINATION lib
)
```

**Comment by jmkerloch** [comment]
So this should be added in the library `CMakeLists.txt` ? 
This is already available  : 
```
INSTALL(TARGETS sirius_solver
	EXPORT sirius_solver
	LIBRARY DESTINATION lib
	ARCHIVE DESTINATION lib
	RUNTIME DESTINATION bin
	INCLUDES DESTINATION include
	PUBLIC_HEADER DESTINATION include
)

INSTALL(EXPORT sirius_solver
	FILE sirius_solverConfig.cmake
	DESTINATION cmake
)
```

But when I'm linking this library with 
```
target_link_libraries(App
			PUBLIC
				sirius_solver
			)
```

The dll from the library is not installed to the App build directory.

Thanks for your quick answer !

**Comment by Hoikas** [comment]
The vcpkg toolchain file monkeypatches CMake's built-in `add_executable()` and `add_library()` functions to provide this functionality. The code can be found in the [toolchain file, here](https://github.com/microsoft/vcpkg/blob/619b29470031781e0c787eff32dbc7d8568bdbe6/scripts/buildsystems/vcpkg.cmake#L360:L408).

**Comment by JackBoosY** [comment]
Sadly, I don’t know, @strega-nil can you please answer this question?

**Comment by jmkerloch** [comment]
@Hoikas , thanks for the answer. This is exactly what I was looking for.
I managed to add almost the same functionnality but without a powershell script : 
 
```
# If done properly and if the dependency has a correct config file, IMPORTED_LOCATION_RELEASE should be defined
get_target_property( DEP_SHARED_LIB_PATH sirius_solver IMPORTED_LOCATION_RELEASE )
		
# Copy the shared lib file
add_custom_command(TARGET ${exec_name} POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy ${DEP_SHARED_LIB_PATH} $<TARGET_FILE_DIR:${exec_name}>)
```
The  downside is that I have to add this  code for every dependency.
I'm  looking  for CMake variable that will give me all dependency (with .dll full path so I can copy the .dll after build).

**Comment by Hoikas** [comment]
I'm not an expert at CMake, but I think you will want to do something like [get_target_properties(LINK_LIBRARIES)](https://cmake.org/cmake/help/latest/prop_tgt/LINK_LIBRARIES.html) to get the dependencies and copy them. I'm not sure how you get the full DLL path from there, however. Vcpkg has an advantage in that it builds everything and has hooked deeply into that process.

**Comment by JackBoosY** [comment]
I think https://github.com/microsoft/vcpkg/pull/14243 should match your request.
