### ISSUE TITLE
While running the vcvarsall.bat it stuck.

### ISSUE THREAD

**Issue by ricky001** [microsoft/vcpkg#13303]
When running the vcvarsall.bat on jenkins node it will get stuck for hours and then we have to abort it manually. Also it didn't give any error also.

x86)\Microsoft Visual Studio\2017\Professional\VC\Auxiliary\Build\vcvars32.bat"
00:22:55 [Build] **********************************************************************
00:22:55 [ Build] ** Visual Studio 2017 Developer Command Prompt v15.8.5
00:22:55 [Build] ** Copyright (c) 2017 Microsoft Corporation
00:22:55 [Build] **********************************************************************
00:22:57 [Build] [vcvarsall.bat] Environment initialized for: 'x86'
 
It will stuck for hours

Note:-This happens sometimes only not all the time.

**Comment by NancyLi1013** [comment]
Hi @ricky001 
Thanks for posting this issue. 
Please see the related issue https://github.com/microsoft/vcpkg/issues/10468#issuecomment-620254095.

Could you please also update Visual Studio to the latest version and try it again?

**Comment by ricky001** [comment]
Hello @NancyLi1013 

As we are using 2017 VS.out of 10 builds it will fail 2-3 times but other 7-8 build will pass.

Regards,
Somya Chawla

**Comment by NancyLi1013** [comment]
Thanks for your reply.
This seems to be a bug in `vcvarsall.bat`. Since this script is provided by Visual Studio, it would be better to report this issue to developer community if this is still a problem for you.

Before doing this, you can update Visual Studio 2017 to the latest version if possible.
And then verify if you will encounter the same issue.
I noticed you used v15.8.5, which is not latest version.

Thanks.

**Comment by ricky001** [comment]
Hello @NancyLi1013 

Yes we are using V 15.8.5.  I will be updating the VS version to 15.9.  Is that ok

Regards,
Somya Chawla

**Comment by NancyLi1013** [comment]
Hi @ricky001 
Please let me know if this is still a problem for you now.

Thanks.

**Comment by NancyLi1013** [comment]
I'm closing this issue for now since seems no response.

Please feel free to reopen this if it is still a problem for you.
