### ISSUE TITLE
[qt5-base] build failure

### ISSUE THREAD

**Issue by zhongshan99** [microsoft/vcpkg#13301]
Host Environment

OS: Windows 10  LTSC
Compiler: VS2019+MSVC

To Reproduce
./vcpkg install qt5-base:x64-windows

Failure logs
-- Installing: D:/C++/vcpkg/packages/qt5-base_x64-windows/share/qt5-base/copyright
-- Performing post-build validation
There should be no empty directories in D:\C++\vcpkg\packages\qt5-base_x64-windows
The following empty directories were found:

    D:/C++/vcpkg/packages/qt5-base_x64-windows/bin
    D:/C++/vcpkg/packages/qt5-base_x64-windows/debug/bin
    D:/C++/vcpkg/packages/qt5-base_x64-windows/debug/plugins/bearer
    D:/C++/vcpkg/packages/qt5-base_x64-windows/debug/plugins/generic
    D:/C++/vcpkg/packages/qt5-base_x64-windows/debug/plugins/imageformats
    D:/C++/vcpkg/packages/qt5-base_x64-windows/debug/plugins/platforms
    D:/C++/vcpkg/packages/qt5-base_x64-windows/debug/plugins/platformthemes
    D:/C++/vcpkg/packages/qt5-base_x64-windows/debug/plugins/printsupport
    D:/C++/vcpkg/packages/qt5-base_x64-windows/debug/plugins/sqldrivers
    D:/C++/vcpkg/packages/qt5-base_x64-windows/debug/plugins/styles
    D:/C++/vcpkg/packages/qt5-base_x64-windows/plugins/bearer
    D:/C++/vcpkg/packages/qt5-base_x64-windows/plugins/generic
    D:/C++/vcpkg/packages/qt5-base_x64-windows/plugins/imageformats
    D:/C++/vcpkg/packages/qt5-base_x64-windows/plugins/platforms
    D:/C++/vcpkg/packages/qt5-base_x64-windows/plugins/platformthemes
    D:/C++/vcpkg/packages/qt5-base_x64-windows/plugins/printsupport
    D:/C++/vcpkg/packages/qt5-base_x64-windows/plugins/sqldrivers
    D:/C++/vcpkg/packages/qt5-base_x64-windows/plugins/styles

If a directory should be populated but is not, this might indicate an error in the portfile.
If the directories are not needed and their creation cannot be disabled, use something like this in the portfile to remove them:

    file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/a/dir" "${CURRENT_PACKAGES_DIR}/some/other/dir")

Found 1 error(s). Please correct the portfile:
    D:\C++\vcpkg\ports\qt5-base\portfile.cmake
-- Performing post-build validation done
Error: Building package qt5-base:x64-windows failed with: POST_BUILD_CHECKS_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: qt5-base:x64-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by JackBoosY** [comment]
Please provide `build-x64-windows-dbg-err.log`, `build-x64-windows-dbg-out.log`, `config-x64-windows-dbg-err.log`, `config-x64-windows-dbg-out.log` in  _D:/C++/vcpkg/buildtrees/qt5-base_.

**Comment by zhongshan99** [comment]
这个问题后来解决了，原因是路径名中C++的+，改成字母就可以build完成。日志里的提示信息没有任何帮助。

________________________________
发件人: Jack・Boos・Yu <notifications@github.com>
发送时间: 2020年9月3日 10:52
收件人: microsoft/vcpkg <vcpkg@noreply.github.com>
抄送: zhongshan99 <zhongshan99@hotmail.com>; Author <author@noreply.github.com>
主题: Re: [microsoft/vcpkg] [qt5-base] build failure (#13301)


Please provide build-x64-windows-dbg-err.log, build-x64-windows-dbg-out.log, config-x64-windows-dbg-err.log, config-x64-windows-dbg-out.log in D:/C++/vcpkg/buildtrees/qt5-base.

―

**Comment by JackBoosY** [comment]
@zhongshan99 不要在非ascii字符的路径下安装东西，这应该是基本原则。
