### ISSUE TITLE
Boost building issue Win10/x64 

### ISSUE THREAD

**Issue by amigo421** [Microsoft/vcpkg#1331]
> Building package boost:x64-windows...
> -- CURRENT_INSTALLED_DIR=C:/dev/cxx/vcpkg/installed/x64-windows
> -- DOWNLOADS=C:/dev/cxx/vcpkg/downloads
> -- CURRENT_PACKAGES_DIR=C:/dev/cxx/vcpkg/packages/boost_x64-windows
> -- CURRENT_BUILDTREES_DIR=C:/dev/cxx/vcpkg/buildtrees/boost
> -- CURRENT_PORT_DIR=C:/dev/cxx/vcpkg/ports/boost/.
> -- Using cached C:/dev/cxx/vcpkg/downloads/boost_1_64_0.tar.bz2
> -- Testing integrity of cached file...
> -- Testing integrity of cached file... OK
> -- Extracting source C:/dev/cxx/vcpkg/downloads/boost_1_64_0.tar.bz2
> CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:43 (message):
>     Command failed: C:/dev/cxx/CMake/bin/cmake.exe;-E;tar;xjf;C:/dev/cxx/vcpkg/downloads/boost_1_64_0.tar.bz2
>     Working Directory: C:/dev/cxx/vcpkg/buildtrees/boost/src
>     See logs for more information:
>       C:\dev\cxx\vcpkg\buildtrees\boost\extract-out.log
>       C:\dev\cxx\vcpkg\buildtrees\boost\extract-err.log
> 
> Call Stack (most recent call first):
>   scripts/cmake/vcpkg_extract_source_archive.cmake:49 (vcpkg_execute_required_process)
>   scripts/cmake/vcpkg_extract_source_archive.cmake:61 (vcpkg_extract_source_archive_ex)
>   ports/boost/portfile.cmake:13 (vcpkg_extract_source_archive)
>   scripts/ports.cmake:73 (include)
> 
> 
> Error: Building package boost:x64-windows failed with: BUILD_FAILED
> Please ensure you're using the latest portfiles with `.\vcpkg update`, then
> submit an issue at https://github.com/Microsoft/vcpkg/issues including:
>   Package: boost:x64-windows
>   Vcpkg version: 0.0.81-78fff8f2ea8192a884a8ac1ee17e36fe922682c1
> 
> Additionally, attach any relevant sections from the log files above.

[build-x64-windows-rel-err-0.txt](https://github.com/Microsoft/vcpkg/files/1092310/build-x64-windows-rel-err-0.txt)
[patch-x64-windows-0-err.txt](https://github.com/Microsoft/vcpkg/files/1092311/patch-x64-windows-0-err.txt)
this is the only non-empty log files 

latest version of the tool in the use (just pull and build right now before the attempt above)
update command was also applied

**Comment by ras0219-msft** [comment]
Ok, it looks like you may not have the environment variable `NUMBER_OF_PROCESSORS` defined.

Could you try running `$env:NUMBER_OF_PROCESSORS = "4"` or `set NUMBER_OF_PROCESSORS=4` (for powershell or cmd respectively) then trying again?

**Comment by amigo421** [comment]
> PS C:\dev\cxx\vcpkg> $env:NUMBER_OF_PROCESSORS="4"
> PS C:\dev\cxx\vcpkg> vcpkg install boost:x64-windows
> The following packages will be built and installed:
>     boost:x64-windows
> Building package boost:x64-windows...
> -- CURRENT_INSTALLED_DIR=C:/dev/cxx/vcpkg/installed/x64-windows
> -- DOWNLOADS=C:/dev/cxx/vcpkg/downloads
> -- CURRENT_PACKAGES_DIR=C:/dev/cxx/vcpkg/packages/boost_x64-windows
> -- CURRENT_BUILDTREES_DIR=C:/dev/cxx/vcpkg/buildtrees/boost
> -- CURRENT_PORT_DIR=C:/dev/cxx/vcpkg/ports/boost/.
> -- Using cached C:/dev/cxx/vcpkg/downloads/boost_1_64_0.tar.bz2
> -- Testing integrity of cached file...
> -- Testing integrity of cached file... OK
> -- Extracting done
> -- Using cached C:/dev/cxx/vcpkg/downloads/boost-range-has_range_iterator-hotfix_e7ebe14707130cda7b72e0ae5e93b17157fdb6a2.diff
> -- Testing integrity of cached file...
> -- Testing integrity of cached file... OK
> -- Applying patch C:/dev/cxx/vcpkg/buildtrees/boost/src/boost-range-has_range_iterator-hotfix_e7ebe14707130cda7b72e0ae5e93b17157fdb6a2.diff.fixed
> -- Applying patch failed. This is expected if this patch was previously applied.
> -- Applying patch C:/dev/cxx/vcpkg/buildtrees/boost/src/boost-range-has_range_iterator-hotfix_e7ebe14707130cda7b72e0ae5e93b17157fdb6a2.diff.fixed done
> -- Bootstrapping done
> -- Building x64-windows-rel
> CMake Error at scripts/cmake/vcpkg_execute_required_process_repeat.cmake:21 (message):
>     Command failed: C:/dev/cxx/vcpkg/buildtrees/boost/src/boost_1_64_0/b2.exe;--stagedir=C:/dev/cxx/vcpkg/buildtrees/boost/x64-windows-rel/stage;--build-dir=C:/dev/cxx/vcpkg/buildtrees/boost/x64-windows-rel;-sZLIB_INCLUDE="C:/dev/cxx/vcpkg/installed/x64-windows\include";-sBZIP2_INCLUDE="C:/dev/cxx/vcpkg/installed/x64-windows\include";-j;--debug-configuration;--hash;-q;--without-python;threading=multi;runtime-link=shared;link=shared;address-model=64;toolset=msvc-14.1;-sZLIB_BINARY=zlib;-sZLIB_LIBPATH="C:/dev/cxx/vcpkg/installed/x64-windows\lib";-sBZIP2_BINARY=bz2;-sBZIP2_LIBPATH="C:/dev/cxx/vcpkg/installed/x64-windows\lib";variant=release;debug-symbols=on
>     Working Directory: C:/dev/cxx/vcpkg/buildtrees/boost/src/boost_1_64_0
>     See logs for more information:
>       C:\dev\cxx\vcpkg\buildtrees\boost\build-x64-windows-rel-out.log
>       C:\dev\cxx\vcpkg\buildtrees\boost\build-x64-windows-rel-err.log
> 
> Call Stack (most recent call first):
>   ports/boost/portfile.cmake:188 (vcpkg_execute_required_process_repeat)
>   scripts/ports.cmake:73 (include)
> 
> 
> Error: Building package boost:x64-windows failed with: BUILD_FAILED
> Please ensure you're using the latest portfiles with `.\vcpkg update`, then
> submit an issue at https://github.com/Microsoft/vcpkg/issues including:
>   Package: boost:x64-windows
>   Vcpkg version: 0.0.81-df3f73d8256e549ad43efd0a84cd3691d91c9c10

**Comment by amigo421** [comment]
the errors in log files are the same,
by the way , there is no files like in tool's log, just these ones (with a suffixes):

> bootstrap-err.log
> bootstrap-out.log
> build-x64-windows-rel-err-0.log
> build-x64-windows-rel-err-1.log
> build-x64-windows-rel-err-2.log
> build-x64-windows-rel-out-0.log
> build-x64-windows-rel-out-1.log
> build-x64-windows-rel-out-2.log
> extract-err.log
> extract-out.log
> patch-x64-windows-0-err.log
> patch-x64-windows-0-out.log

**Comment by JackBoosY** [comment]
Hi @amigo421 ,there is no problem build boost in the newest version.
Can you update vcpkg and repro it?
Thx.

**Comment by amigo421** [comment]
thanks team ! but actually last 1.5 years , I don't work with Windows family and can't test this... no Win hosts available at the moment, sorry

**Comment by JackBoosY** [comment]
Please open a new issue if this is still a problem for you.
Thx.
