### ISSUE TITLE
[OpenImageIO] build failure

### ISSUE THREAD

**Issue by akilaln** [microsoft/vcpkg#13317]
**Host Environment**
- OS: Windows 10
- Compiler: VS2015

**To Reproduce**
Turned below options ON in portfile.cmake
   ```
    -DBUILD_MISSING_PYBIND11=ON
    -DBUILD_MISSING_DEPS=ON
    -DUSE_PYTHON=ON
```
`./vcpkg install openimageio`

**Failure logs** 
-- Downloading https://www.python.org/ftp/python/3.8.3/python-3.8.3-embed-win32.zip...
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:83 (message):
    Command failed: ninja -v
    Working Directory: C:/test/vcpkg/buildtrees/openimageio/x86-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\test\vcpkg\buildtrees\openimageio\config-x86-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:303 (vcpkg_execute_required_process)
  ports/openimageio/portfile.cmake:49 (vcpkg_configure_cmake)
  scripts/ports.cmake:79 (include)

Error: Building package openimageio:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openimageio:x86-windows
  Vcpkg version: 2020.06.15-nohash

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by JonLiu1993** [comment]
Hi @akilaln ,
When you turn on -DUSE_PYTHON=ON, you should add feature to install, can you use this command to try it? 
./vcpkg install openimageio[pybind11]
I tried successfully.

**Comment by akilaln** [comment]
@JonLiu1993 - Thanks I'm going to try this option. Do I still need these options ON?

**Comment by akilaln** [comment]
@JonLiu1993 , Also I can see that it builds python 3 bindings by default. Is there way to build it for python 2.7? 
Thanks

**Comment by JonLiu1993** [comment]
@akilaln ,You can let these options ON
````
-DBUILD_MISSING_PYBIND11=ON
 -DBUILD_MISSING_DEPS=ON
````

**Comment by akilaln** [comment]
Hi @JonLiu1993 , thanks that worked! I also have a question about writing metadata.

I'm trying to write metadata into EXR using ImageBuf class in the following way

 buf = ImageBuf("test.exr") 
 buf.specmod().attribute("test_attr", "str_value")
 buf.write("test.exr")

The metadata seems to be getting written correctly but the file seems to be losing out on data as the files size looks much smaller. I followed your documentation adding arbitrary data but I probably am missing something specifically for EXRs.

**Comment by JonLiu1993** [comment]
@akilaln ，Sorry to reply to you so late, I don't know metadata well, so I can't provide you with this help. You can resubmit an issue to discuss your issue. I temporarily close this issue
