### ISSUE TITLE
Error on installing tiff with mozjpeg

### ISSUE THREAD

**Issue by daramkun** [microsoft/vcpkg#13323]
mozjpeg(libjpeg-turbo's fork) installed, tiff installing is fail.

```
Computing installation plan...
The following packages will be built and installed:
  * libjpeg-turbo[core]:x64-windows-static
    tiff[core]:x64-windows-static
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows-static...
Starting package 1/2: libjpeg-turbo:x64-windows-static
Building package libjpeg-turbo[core]:x64-windows-static...
Using cached binary package: C:\Users\daram\AppData\Local\vcpkg/archives\6f\6f50c25f613180f65162c2089642da02fdd392f1.zip
Building package libjpeg-turbo[core]:x64-windows-static... done
Installing package libjpeg-turbo[core]:x64-windows-static...
The following files are already installed in D:/Projects/vcpkg/installed/x64-windows-static and are in conflict with libjpeg-turbo:x64-windows-static

Installed by mozjpeg:x64-windows-static
    debug/lib/pkgconfig/libjpeg.pc
    debug/lib/pkgconfig/libturbojpeg.pc
    include/jconfig.h
    include/jerror.h
    include/jmorecfg.h
    include/jpeglib.h
    include/turbojpeg.h
    lib/jpeg.lib
    lib/pkgconfig/libjpeg.pc
    lib/pkgconfig/libturbojpeg.pc
    lib/turbojpeg.lib
```

**Comment by NancyLi1013** [comment]
Hi @daramkun 
Thanks for posting this issue.
Since `mozjpeg `is based on `libjpeg-turbo`.

Please see theses two docs:
https://github.com/mozilla/mozjpeg/blob/master/README.md
https://github.com/mozilla/mozjpeg/blob/master/README-mozilla.txt

They cannot be installed at the same time due to the conflicts.

Need to add messages for the two ports.

**Comment by daramkun** [comment]
So, is there solution? or Need to fix the code of vcpkg?

**Comment by NancyLi1013** [comment]
You can remove another port when installing one of them. There are no ways to fix this. Adding message is to remind users that these two ports are conflicts with each other.

So you can remove `mozjpeg:x64-windows-static` first, then try to build this again.

**Comment by daramkun** [comment]
But `libjpeg-turbo:x64-windows-static` install first, I cannot install `mozjpeg:x64-windows-static`. and Removing `libjpeg-turbo:x64-windows-static`, removing `tiff:x64-windows-static` too. I need `mozjpeg`'s encoder and `tiff`'s decoder.

So, no solution in vcpkg, I have to build tiff myself. Thanks.

**Comment by NancyLi1013** [comment]
Hi @daramkun 
Sorry for the long delay.
In your case, there is no solution in vcpkg now. I can only try to add the message to remind users of the conflicts, but I cannot solve the conflicts to meet your demand. I'm so sorry about this.
