### ISSUE TITLE
How To Download License_1_0.txt

### ISSUE THREAD

**Issue by ZYZ-HAHA** [microsoft/vcpkg#13335]
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.73.0/LICENSE_1_0.txt... Failed. Status: 6;"Couldn't resolve host name"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:173 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  installed/x86-windows/share/boost-vcpkg-helpers/boost-modular-headers.cmake:17 (vcpkg_download_distfile)
  ports/boost-compatibility/portfile.cmake:12 (boost_modular_headers)
  scripts/ports.cmake:79 (include)

Error: Building package boost-compatibility:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-compatibility:x86-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by ZYZ-HAHA** [comment]
The&nbsp; question about License_1_0.txt have been done,Thank you very much.
But may be I need another file :&nbsp;boostcpp.jam.
I can't download this file.






-- Extracting source C:/src/vcpkg/downloads/boostorg-build-boost-1.73.0.tar.gz
-- Using source at C:/src/vcpkg/buildtrees/boost-build/src/ost-1.73.0-018fb008dd.clean
-- Using cached C:/src/vcpkg/downloads/boost_LICENSE_1_0.txt
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.73.0/boostcpp.jam...
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.73.0/boostcpp.jam... Failed. Status: 6;"Couldn't resolve host name"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:173 (message):


&nbsp; &nbsp; &nbsp; Failed to download file.
&nbsp; &nbsp; &nbsp; If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
&nbsp; &nbsp; &nbsp; variables to "https://user:password@your-proxy-ip-address:port/".
&nbsp; &nbsp; &nbsp; Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues


Call Stack (most recent call first):
&nbsp; ports/boost-build/portfile.cmake:27 (vcpkg_download_distfile)
&nbsp; scripts/ports.cmake:79 (include)




Error: Building package boost-build:x86-windows failed with: BUILD_FAILED



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/vcpkg"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月4日(星期五) 凌晨3:56
收件人:&nbsp;"microsoft/vcpkg"<vcpkg@noreply.github.com&gt;;
抄送:&nbsp;"孤独成瘾"<1304488364@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [microsoft/vcpkg] How To Download License_1_0.txt (#13335)





 
please put the following file in [vcpkg-root]\downloads and try again.
 boost_LICENSE_1_0.txt

**Comment by NancyLi1013** [comment]
Seems this issue has been solved, so I'm closing this issue for now.
