### ISSUE TITLE
[cryptopp]:x64-windows-static build failure

### ISSUE THREAD

**Issue by pudding186** [microsoft/vcpkg#13338]
**Host Environment**
- OS: windows 10
- Compiler: vs2019

**To Reproduce**
`.\vcpkg.exe install cryptopp:x64-windows-static`

**Failure logs** 
Computing installation plan...
The following packages will be built and installed:
    cryptopp[core]:x64-windows-static
Detecting compiler hash for triplet x64-windows-static...
Error occurred while detecting compiler information. Pass `--debug` for more information.

**Comment by StarGate-One** [comment]
Please perform the following:
`cd to [vcpkg-root]`
`.\vcpkg.exe install cryptopp:x64-windows-static --debug`
Post the results here.

**Comment by PhoebeHui** [comment]
@pudding186, could you provide us more information? what's output from '.\vcpkg.exe install cryptopp:x64-windows-static --debug'

I can't repro this issue with vs2019 16.7.2.

Starting package 1/1: cryptopp:x64-windows-static
Building package cryptopp[core]:x64-windows-static...
-- Downloading https://github.com/noloader/cryptopp-cmake/archive/6d0666c457fbbf6f81819fd2b80f0cb5b6646593.tar.gz...
-- Extracting source E:/vcpkg/src/downloads/noloader-cryptopp-cmake-6d0666c457fbbf6f81819fd2b80f0cb5b6646593.tar.gz
-- Applying patch cmake.patch
-- Using source at E:/vcpkg/src/buildtrees/cryptopp/src/b5b6646593-1f0e206091.clean
-- Downloading https://github.com/weidai11/cryptopp/archive/CRYPTOPP_8_2_0.tar.gz...
-- Extracting source E:/vcpkg/src/downloads/weidai11-cryptopp-CRYPTOPP_8_2_0.tar.gz
-- Applying patch patch.patch
-- Using source at E:/vcpkg/src/buildtrees/cryptopp/src/TOPP_8_2_0-66bcedf47f.clean
-- Configuring x64-windows-static
-- Building x64-windows-static-dbg
-- Building x64-windows-static-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package cryptopp[core]:x64-windows-static... done
Installing package cryptopp[core]:x64-windows-static...
Installing package cryptopp[core]:x64-windows-static... done
Elapsed time for package cryptopp:x64-windows-static: 3.417 min

Total elapsed time: 3.689 min

The package cryptopp:x64-windows-static provides CMake targets:

    find_package(cryptopp CONFIG REQUIRED)
     target_link_libraries(main PRIVATE cryptopp-static

**Comment by PhoebeHui** [comment]
@pudding186, please reopen this issue with the suggested information if it still be an issue for you.

**Comment by baby7305** [comment]
i have the same errors

**Comment by pudding186** [comment]
U can pull tag branch


| |
Jackey
邮箱：pudding_186@163.com
|

Signature is customized by Netease Mail Master

On 11/23/2020 14:07, 学海拾贝 wrote:

i have the same errors
