### ISSUE TITLE
How do I build mongocxx for a x64 platform?

### ISSUE THREAD

**Issue by rculler** [microsoft/vcpkg#13333]
I'm trying to get a windows x64 C++ project working with the latest mongocxx driver using Visual Studio 2019. I installed the driver libraries using vcpkg:

vcpkg install mongo-cxx-driver[boost]

In VS 2019 I created a new console app and inserted the example code from the mongo driver page into main(). I built the app and ran it; everything works great. Then I noticed that it built as a win 32 app and switched it over to x64. Now the project won't build b/c it can't find the header files.

**Comment by Neumann-A** [comment]
`vcpkg install mongo-cxx-driver[boost]:x64-windows`

or

`vcpkg install mongo-cxx-driver[boost] --triplet x64-windows`

or

```
set VCPKG_DEFAULT_TRIPLET=x64-windows
vcpkg install mongo-cxx-driver[boost]
```

**Comment by NancyLi1013** [comment]
Hi @rculler 
vcpkg will install `x86-windows` triplet by default.
Since you used`mongo-cxx-driver[boost]`, which means x86-windows was installed.

If you want to use x64, you should install `mongo-cxx-driver[boost]:x64-windows`.
Please let me know if you still any concerns about this issue.

**Comment by NancyLi1013** [comment]
I'm closing this issue for now since seems no response.
