### ISSUE TITLE
[vulkan] SDK detection fails for official debian packages

### ISSUE THREAD

**Issue by jeweg** [microsoft/vcpkg#13331]
Hi, I'm having trouble with the vulkan port. That port doesn't provide anything, it checks if the Vulkan SDK is installed, and the way it does this is problematic and fails in completely valid cases.

The most common way to install the Vulkan SDK seems to be to place it under a common root dir and set (or have set
by sourcing a shipped script) the VULKAN_SDK environment variable. But this is not the only way. The officially provided
debian packages instead install files according to the filesystem hierarchy standard, e.g. '/usr/lib/x86_64-linux-gnu/libvulkan.so'
and '/usr/include/vulkan/vulkan.h'.
CMake's FindVulkan module works with both schemes by using find_path and find_library (which have enough built-in logic to successfully
find the debian files), specifying the respective VULKAN_SDK-based paths as path hints.

The vulkan portfile, however, assumes the VULKAN_SDK-based layout and fails with the debian packages.
I've tried to copy the logic in FindVulkan, but didn't get very far: there's just not enough information about the environment available from within a portfile.
It looks like there has been effort to at least make find_library work in portfiles:

    From scripts/cmake/vcpkg_common_definitions.cmake:

    #Setting these variables allows find_library to work in script mode and thus in portfiles!
    set(CMAKE_STATIC_LIBRARY_SUFFIX "${VCPKG_TARGET_STATIC_LIBRARY_SUFFIX}")
    set(CMAKE_SHARED_LIBRARY_SUFFIX "${VCPKG_TARGET_SHARED_LIBRARY_SUFFIX}")
    ...
    set(CMAKE_FIND_LIBRARY_SUFFIXES "${VCPKG_FIND_LIBRARY_SUFFIXES}" CACHE INTERNAL "") # Required by find_library
    set(CMAKE_FIND_LIBRARY_PREFIXES "${VCPKG_FIND_LIBRARY_PREFIXES}" CACHE INTERNAL "") # Required by find_library

But those variables are not enough here. In this case we'd need CMAKE_LIBRARY_ARCHITECTURE set to "x86_64-linux-gnu".

Finding vulkan.h with find_path fails for similar reasons, here we'd need something like CMAKE_C_IMPLICIT_INCLUDE_DIRECTORIES to contain usr/include.
That probably requires the C language to be activated, of course.
I get that we want to keep the environment of portfiles minimal, but do we want to support find_library and find_path in portfiles?

I see a couple of ways to proceed here:
* Replicate most of the heuristics in find_path/find_library: seems unnecessary, as we'd still need to define architecture etc, and at that point we might as well use the CMake commands.
* Check for the vulkan SDK in some other way: I can't think of any that doesn't make even more assumptions about the filesystem layout or the package manager.
* Only support the VULKAN_SDK root dir way of installing it: this seems poor and surprising to the user as the debian packages are completely official and supported even by "raw" CMake
* Remove the vulkan port and dependencies to it: I know how hard/impossible/undesirable it is for vcpkg to remove a port, so...
* Make the vulkan port a no-op: how useful is the check anyway? I'd say, not much.

**Comment by Eric-Brown** [comment]
Since it appears like this issue currently doesn't have any attention at the moment, I have a workaround for anyone who comes across this issue trying to install packages which have vulkan as a dependency in the meantime.

Navigate to `[path to vcpkg]/ports/[package name]` and edit the file `vcpkg.json`.
Inside, you'll see something like:
```
"dependencies":  [
  // dependencies,
  "vulkan",
 // more dependencies...
]
```
Simply remove the `"vulkan",` part and attempt to install again.
This workaround will likely break every time you run a git pull on vcpkg, but it will allow you to complete the installation and use the desired package in your applications.
