### ISSUE TITLE
[SQLite3_FIND_REQUIRED] CMake Error

### ISSUE THREAD

**Issue by fingerecho** [microsoft/vcpkg#13349]
**Host Environment**
- OS: [e.g. Windows10]
- Compiler: Visual Studio 2019  /Cmake 3.17.2

**To Reproduce**
`./vcpkg install SQLite3`

**Failure logs** 
CMake Error at C:/ProgramData/vcpkg/vcpkg/downloads/tools/cmake-3.17.2-windows/cmake-3.17.2-win32-x86/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:167 (message):
  Could NOT find SQLite3 (missing: SQLite3_LIBRARY) (found version "3.23.1")

**Additional context**

**Comment by NancyLi1013** [comment]
Hi @fingerecho 
Thanks for posting this issue.
Please refer to the  following usage to use `sqlite3`.

```
find_package(unofficial-sqlite3 CONFIG REQUIRED)
target_link_libraries(main PRIVATE unofficial::sqlite3::sqlite3)
```

**Comment by fingerecho** [comment]
Thank you! Although this is not my expected answer.

**Comment by fingerecho** [comment]
Please pay attention to the content of the bracket - "found version "3.23.1",
CMake Error at C:/ProgramData/vcpkg/vcpkg/downloads/tools/cmake-3.17.2-windows/cmake-3.17.2-win32-x86/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:167 (message):
Could NOT find SQLite3 (missing: SQLite3_LIBRARY) (found version "3.23.1")

**Comment by fingerecho** [comment]
May be it is just missing the LIBRARY .
How could I fix this bugs?

**Comment by fingerecho** [comment]
Add something?

**Comment by fingerecho** [comment]
What is the difference between the `PACKAGE` and the `LIBRARY`?
If my project named 'helloworld', What should I change the `main` in command `target_link_libraries(main PRIVATE unofficial::sqlite3::sqlite3)· to? When I copied this command into CMakeLists.txt , It doesn't work well.

**Comment by fingerecho** [comment]
The out-put as follows:
CMake Error at C:/ProgramData/vcpkg/vcpkg/downloads/tools/cmake-3.17.2-windows/cmake-3.17.2-win32-x86/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:165 (target_link_libraries):
  Cannot specify link libraries for target "main" which is not built by this

**Comment by fingerecho** [comment]
When I copied the `find_package` commands into ****.cmake file, out-put as follows:
CMake Error at C:/ProgramData/vcpkg/vcpkg/scripts/buildsystems/vcpkg.cmake:474 (_find_package):
  Could not find a package configuration file provided by
  "unofficial-sqlite3" with any of the following names:

    unofficial-sqlite3Config.cmake
    unofficial-sqlite3-config.cmake

  Add the installation prefix of "unofficial-sqlite3" to CMAKE_PREFIX_PATH or
  set "unofficial-sqlite3_DIR" to a directory containing one of the above
  files.  If "unofficial-sqlite3" provides a separate development package or
  SDK, be sure it has been installed.
What should I do ?

**Comment by fingerecho** [comment]
When I installed a package named `HELLOWORLD`, then opened The CMakeLists.txt with the Visual Studio 2019, the error out-put as follows:
严重性	代码	说明	项目	文件	行	禁止显示状态
错误		CMake Error at C:/ProgramData/vcpkg/vcpkg/scripts/buildsystems/vcpkg.cmake:461 (_find_package):
  By not providing "FindHELLOWORLD.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "HELLOWORLD", but
  CMake did not find one.

  Could not find a package configuration file provided by "HELLOWORLD" with any
  of the following names:

    HELLOWORLDConfig.cmake
    HELLOWORLD-config.cmake

  Add the installation prefix of "HELLOWORLD" to CMAKE_PREFIX_PATH or set
  "HELLOWORLD_DIR" to a directory containing one of the above files.  If "HELLOWORLD"
  provides a separate development package or SDK, be sure it has been
  installed.		C:/ProgramData/vcpkg/vcpkg/scripts/buildsystems/vcpkg.cmake	461

**Comment by fingerecho** [comment]
Thank you all! I got it byself.
Thanks for contributing !!

**Comment by pluveto** [comment]
How to solve this?

**Comment by yamauta77** [comment]
@pluveto @trumanz https://github.com/c0i/writting/issues/10#issuecomment-1104073834 maybe can help you.

**Comment by Jasonlhy** [comment]
I encountered this error when I put the CMake project into D drive, but vcpkg is in the C drive

**Comment by Planck35** [comment]
+1 on similar error. Window 11.

Error log:
```
"C:\Program Files\JetBrains\CLion 2022.2.4\bin\cmake\win\bin\cmake.exe" -DCMAKE_BUILD_TYPE=Debug "-DCMAKE_MAKE_PROGRAM=C:/Program Files/JetBrains/CLion 2022.2.4/bin/ninja/win/ninja.exe" -DCMAKE_TOOLCHAIN_FILE=C:\dev\vcpkg\vcpkg\scripts\buildsystems\vcpkg.cmake -G Ninja -S D:\LOL_Script -B D:\LOL_Script\cmake-build-debug
CMake Error at C:/dev/vcpkg/vcpkg/scripts/buildsystems/vcpkg.cmake:834 (_find_package):
  Could not find a package configuration file provided by
  "unofficial-sqlite3" with any of the following names:

    unofficial-sqlite3Config.cmake
    unofficial-sqlite3-config.cmake

  Add the installation prefix of "unofficial-sqlite3" to CMAKE_PREFIX_PATH or
  set "unofficial-sqlite3_DIR" to a directory containing one of the above
  files.  If "unofficial-sqlite3" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
```
