### ISSUE TITLE
build boost fail

### ISSUE THREAD

**Issue by GTchenchao** [microsoft/vcpkg#13346]
the fail message:
-- Using cached C:/src/vcpkg/downloads/boostorg-compatibility-boost-1.73.0.tar.gz
-- Cleaning sources at C:/src/vcpkg/buildtrees/boost-compatibility/src/ost-1.73.0-44642da97c.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/src/vcpkg/downloads/boostorg-compatibility-boost-1.73.0.tar.gz
-- Using source at C:/src/vcpkg/buildtrees/boost-compatibility/src/ost-1.73.0-44642da97c.clean
-- Packaging headers
-- Packaging headers done
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.73.0/LICENSE_1_0.txt...
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.73.0/LICENSE_1_0.txt... Failed. Status: 6;"Couldn't resolve host name"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:178 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  installed/x86-windows/share/boost-vcpkg-helpers/boost-modular-headers.cmake:17 (vcpkg_download_distfile)
  ports/boost-compatibility/portfile.cmake:12 (boost_modular_headers)
  scripts/ports.cmake:79 (include)

Error: Building package boost-compatibility:x86-windows failed with: BUILD_FAILED
######
also  i have no way to use chrome to access https://raw.githubusercontent.com

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/13348
