### ISSUE TITLE
How to download the boostcpp.jam

### ISSUE THREAD

**Issue by ZYZ-HAHA** [microsoft/vcpkg#13343]
The  question about License_1_0.txt have been done,Thank you very much.
But may be I need another file : boostcpp.jam.
I can't open the URL and download this file.

-- Extracting source C:/src/vcpkg/downloads/boostorg-build-boost-1.73.0.tar.gz
-- Using source at C:/src/vcpkg/buildtrees/boost-build/src/ost-1.73.0-018fb008dd.clean
-- Using cached C:/src/vcpkg/downloads/boost_LICENSE_1_0.txt
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.73.0/boostcpp.jam...
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.73.0/boostcpp.jam... Failed. Status: 6;"Couldn't resolve host name"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:173 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  ports/boost-build/portfile.cmake:27 (vcpkg_download_distfile)
  scripts/ports.cmake:79 (include)

Error: Building package boost-build:x86-windows failed with: BUILD_FAILED

**Comment by showintime** [comment]
download the following file and modify its name `boost-1.73.0-boostcpp.jam` and put it in [vcpkg-root]\downloads and try again.
[boost-1.73.0-boostcpp.jam.txt](https://github.com/microsoft/vcpkg/files/5172085/boost-1.73.0-boostcpp.jam.txt)

**Comment by NancyLi1013** [comment]
Hi @ZYZ-HAHA 
Thanks for posting this issue.
This is related with the proxy on your local network. You can use the same way to download boostcpp.jam file manually.

Please try to do as the steps that @showintime suggested above.

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/13348
