### ISSUE TITLE
[New Port Request] SCIP

### ISSUE THREAD

**Issue by pbpf** [microsoft/vcpkg#13367]
Library name: SCIP

Library description: SCIP is currently one of the fastest non-commercial solvers for mixed integer programming (MIP) and mixed integer nonlinear programming (MINLP). It is also a framework for constraint integer programming and branch-cut-and-price. It allows for total control of the solution process and the access of detailed information down to the guts of the solver.

Source repository URL : https://www.scipopt.org/download/release/scip-7.0.1.tgz

Project homepage (if different from the source repository):https://www.scipopt.org/index.php#welcome

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
