### ISSUE TITLE
[bzip2:x64-windows] Build failure - Status: 35;"SSL connect error"

### ISSUE THREAD

**Issue by igormaozao** [microsoft/vcpkg#13368]
**Host Environment**
- OS: Windows 7 x64
- Compiler: revision

**To Reproduce**
`./vcpkg install --triplet x64-windows boost-iostreams boost-asio boost-system boost-filesystem boost-variant boost-lockfree luajit libmariadb pugixml cryptopp`

**Failure logs** 
vcpkg.exe install --triplet x64-windows boost-iostreams boost-asio boost-system boost-filesystem boost-variant boost-lockfree luajit libmariadb pugixml cryptopp
Computing installation plan...
The following packages are already installed:
    boost-asio[core]:x64-windows
    boost-filesystem[core]:x64-windows
    boost-system[core]:x64-windows
The following packages will be built and installed:
    boost-iostreams[core]:x64-windows
    boost-lockfree[core]:x64-windows
  * boost-parameter[core]:x64-windows
    boost-variant[core]:x64-windows
  * bzip2[core]:x64-windows
    cryptopp[core]:x64-windows
  * liblzma[core]:x64-windows
    libmariadb[core,openssl,zlib]:x64-windows
    luajit[core]:x64-windows
    pugixml[core]:x64-windows
  * zlib[core]:x64-windows
  * zstd[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Package boost-asio:x64-windows is already installed
Package boost-filesystem:x64-windows is already installed
Package boost-system:x64-windows is already installed
Detecting compiler hash for triplet x64-windows...
Starting package 4/12: bzip2:x64-windows
Building package bzip2[core]:x64-windows...
Could not locate cached archive: C:\Users\Igor\AppData\Local\vcpkg/archives\86\863485b6b42f95ef6b7abf997470975c890ae749.zip
-- Using cached C:/Users/Igor/source/repos/vcpkg/downloads/bzip2-75a94bea3918e612b879d6a11ca64b8689526147.tar.gz
-- Cleaning sources at C:/Users/Igor/source/repos/vcpkg/buildtrees/bzip2/src/8689526147-1ef169fbaa.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/Igor/source/repos/vcpkg/downloads/bzip2-75a94bea3918e612b879d6a11ca64b8689526147.tar.gz
-- Applying patch fix-import-export-macros.patch
-- Using source at C:/Users/Igor/source/repos/vcpkg/buildtrees/bzip2/src/8689526147-1ef169fbaa.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz...
-- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz... Failed. Status: 35;"SSL connect error"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:178 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_find_acquire_program.cmake:403 (vcpkg_download_distfile)
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:270 (vcpkg_find_acquire_program)
  ports/bzip2/portfile.cmake:43 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:79 (include)

Error: Building package bzip2:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, thensubmit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: bzip2:x64-windows
  Vcpkg version: 2020.06.15-nohash

**Additional context**
I do not use any proxy, and tried to run `vcpkg update`, that tells me to actually make a `git clone`, which I did and still the same.

Thank you.

**Comment by StarGate-One** [comment]
See #13298 #13217
From what I gather, msys2 now accepts only TLS 1.2 or 1.3 connections, they have phased out TLS 1.0 and 1.1
Windows 7 not support TLS 1.2 or 1.3
A couple of options are:
1. download the files manually with a browser with TLS 1.2 or 1.3 capability (the latest versions Firefox, chrome and the new Chromium edge have TLS 1.3 enabled by default) and put them in the [vcpkg-root]\downloads directory -or-
2. you can modify the `repo.msys2.org` URLs in the *.cmake files to use **http** instead of **https**, although insecure but vcpkg does do a SHA512 checksum against the file ensuring the file has not been tampered with.

**Comment by igormaozao** [comment]
Thank you, downloading the file manually did the job.
