### ISSUE TITLE
intallation error

### ISSUE THREAD

**Issue by adilaadhu** [microsoft/vcpkg#13376]
.\vcpkg\bootstrap-vcpkg.bat

i have run this command on my windows powershell but showed some error on tab,given below on that error.

The property 'instance' cannot be found on this object. Verify that the property exists.
At C:\dev\vcpkg\scripts\bootstrap.ps1:78 char:31
+         foreach ($instance in $asXml.instances.instance)
+                               ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict

Could not find Visual Studio. VS2015, VS2017, or VS2019 (with C++) needs to be installed.
At C:\dev\vcpkg\scripts\bootstrap.ps1:143 char:9
+         throw "Could not find Visual Studio. VS2015, VS2017, or VS201 ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find ...o be installed.:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find Visual Studio. VS2015, VS2017, or VS2019 (with C++) needs to be installed.

**Comment by StarGate-One** [comment]
Have you installed Visual Studio 2015, 2017 or 2019? Visual Studio 2017/2019 Community versions are free...
https://visualstudio.microsoft.com/downloads/
With Visual Studio 2017/2019, install the Desktop Development with C++ workload, Windows SDK and the English Language pack.

**Comment by adilaadhu** [comment]
i have installed those versions.

**Comment by PhoebeHui** [comment]
@adilaadhu, does this issue still persist?

**Comment by monchin** [comment]
> @adilaadhu, does this issue still persist?

@PhoebeHui  Hello, I found this issue and I met the same error. I have installed VS2019 community, although in `D` disk
Translation on right that I've installed:
#### desktop development using c++
 including
* c++ core desktop functions
* intellicode

#### selectable:
* msvc v142
* win 10 sdk
* real-time debugger
* c++ analysing tools
* c++ cmake tools for win
* c++ atl for newest v142 generating tools
* ...

![image](https://user-images.githubusercontent.com/18521800/101286376-2293f780-3825-11eb-97ad-bf949f1a6c9a.png)

Do I need to install other things? Thank you!

**Comment by StarGate-One** [comment]
Did you include the "English" Language Pack?
![image](https://user-images.githubusercontent.com/68293825/101289697-192a7100-37cc-11eb-9e80-0661f3ee1033.png)

**Comment by monchin** [comment]
> > @adilaadhu, does this issue still persist?
> 
> @PhoebeHui Hello, I found this issue and I met the same error. I have installed VS2019 community, although in `D` disk
> Translation on right that I've installed:
> 
> #### desktop development using c++
> including
> 
> * c++ core desktop functions
> * intellicode
> 
> #### selectable:
> * msvc v142
> * win 10 sdk
> * real-time debugger
> * c++ analysing tools
> * c++ cmake tools for win
> * c++ atl for newest v142 generating tools
> * ...
> 
> ![image](https://user-images.githubusercontent.com/18521800/101286376-2293f780-3825-11eb-97ad-bf949f1a6c9a.png)
> 
> Do I need to install other things? Thank you!

it seems that there was some error when I installed the VS2019. I reinstalled it and everything went well.

**Comment by PhoebeHui** [comment]
@monchin, glad you got the issue fixed!

@adilaadhu, please reopen this issue if it still be a problem for you.
