### ISSUE TITLE
[glad] Could not find a package configuration file

### ISSUE THREAD

**Issue by domsupamoe** [microsoft/vcpkg#13372]
**Host Environment**
- OS: Linux
- Compiler: g++

**To Reproduce**

The package is installed successfully with `./vcpkg install glad`.

In the CMakeLists.txt, I added the lines for importing package:
```
find_package(glad CONFIG REQUIRED)
target_link_libraries(main PRIVATE glad::glad)
```
However, when trying to run build `cmake -S . -B build`
CMake outputs the error "Could not find a package configuration file"

**Failure logs** 
```
CMake Error at CMakeLists.txt:9 (find_package):
  Could not find a package configuration file provided by "glad" with any of
  the following names:

    gladConfig.cmake
    glad-config.cmake

  Add the installation prefix of "glad" to CMAKE_PREFIX_PATH or set
  "glad_DIR" to a directory containing one of the above files.  If "glad"
  provides a separate development package or SDK, be sure it has been
  installed.
```

**Additional context**

Temporarily resolved the issue by adding following line to `CMakeLists.txt`:
```
set(glad_DIR "/path_to_vcpkg/installed/x64-linux/share/glad")
```

**Comment by JonLiu1993** [comment]
Hi @domsupamoe, I have successfully used glad in linux environment according to your method, can you provide the CMkelists.txt? 

vwangli@vwangli004:~/Jon/test$ /home/vwangli/Jon/vcpkg/downloads/tools/cmake-3.17.2-linux/cmake-3.17.2-Linux-x86_64/bin/cmake -B /home/vwangli/Jon/test/build -S /home/vwangli/Jon/test/src . -DCMAKE_TOOLCHAIN_FILE=/home/vwangli/Jon/vcpkg/scripts/buildsystems/vcpkg.cmake
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/vwangli/Jon/test/build

**Comment by domsupamoe** [comment]
Sorry, I noticed I may typed the wrong cmake toolchain file path when I built it.

Everything is working now. Thank you for the help!

**Comment by shash29-dev** [comment]
same error. I need to set the DIR path.
Also, vscode picks up this
```C:\msys64\mingw64\bin\cmake.exe --no-warn-unused-cli -DCMAKE_TOOLCHAIN_FILE:STRING=D:\src\vcpkg\scripts\buildsystems\vcpkg.cmake -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug........ blah blah```
picks up the DCMAKE_TOOLCHAIN_FILE path correctly.

**Comment by weather-tracker** [comment]
same error but using windows and but not using cmake.

**Comment by JonLiu1993** [comment]
@shash29-dev , @weather-tracker , please open a new issue if this is still a issue for you
