### ISSUE TITLE
[New Port Request] libsigcpp-3

### ISSUE THREAD

**Issue by brukted** [microsoft/vcpkg#13379]
Library name: libsigcpp-3.0

Source repository URL: https://github.com/libsigcplusplus/libsigcplusplus

Project homepage (if different from the source repository): https://libsigcplusplus.github.io/libsigcplusplus/

**Comment by MrAviator93** [comment]
When installing the library the following way:
.\vcpkg.exe install libsigcpp-3:x64-windows-static

I get 4 errors reffering to:
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: __cdecl sigc::internal::slot_rep::slot_rep(void * (__cdecl*)(void *)

Any idea how to fix this, it seems somehow related to the config generated.
