### ISSUE TITLE
[osgearth:x64-windows] build failure

### ISSUE THREAD

**Issue by MOKOTA** [microsoft/vcpkg#13377]
**Host Environment**
- OS: windows-10
- Compiler: revision

**To Reproduce**
`./vcpkg  install osgearth:x64-windows`

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by MOKOTA** [comment]
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/5179517/install-x64-windows-dbg-out.log)

**Comment by StarGate-One** [comment]
May be related to [osgearth:x64-windows] build failure #13292

**Comment by JackBoosY** [comment]
Duplicate with #13292
