### ISSUE TITLE
Need some command like "vcpkg upgrade" for continuous integration purposes 

### ISSUE THREAD

**Issue by jasjuang** [Microsoft/vcpkg#1337]
Currently there is no easy way to upgrade the packages automatically with a `.bat` script, the closest command that is currently available is `vcpkg update` which displays what packages are available for updates, but there is no way for me to extract it and run `vcpkg remove --outdated --recurse` and `vcpkg install <new-pkgs (how-can-i-get-this-automatically?)>`

This is slightly related to #501, but the difference is I don't mind purging the dependencies and reinstall them because I will have a windows task set up everyday at 2am to upgrade the packages.

**Comment by Fleischner** [comment]
Haven't tried yet:
It should be possible to add a custom port in the ports directory. E.g 'company-deps' 
The portfile is empty.
And the CONTROL file list all your dependencies under Build-Depends: 

Then just run:
vcpkg remove --outdated --recurse 
vcpkg install company-deps

**Comment by jasjuang** [comment]
@Fleischner That actually kind of works but I am unable to do it in a way that the cmd doesn't return an error. Here is what I done,

I created a `company-deps` folder in the ports directory as you mentioned, and added a CONTROL file in it. If I am allowed to just put `Description` and `Build-Depends` in the CONTROL file then it will work, but the problem is when I run `vcpkg install company-deps` it said 

``````
Required field not present: Source
Required field not present: Version
``````

Hence I add a dummy `company-deps` into the Source section and `1.0` onto the Version section. When I do a `vcpkg install company-deps` again I get an error message 

``````
Port is missing portfile: C:/dev/vcpkg/ports/dev/./portfile.cmake
``````

Hence I add in an empty portfile and ran `vcpkg install company-deps` again and now here is the error message

``````
The folder /include is empty. This indicates the library was not correctly installed.
The software license must be available at ${CURRENT_PACKAGES_DIR}/share/dev/copyright
Found 2 error(s). Please correct the portfile:
    C:\dev\vcpkg\ports\dev\portfile.cmake
-- Performing post-build validation done
Error: Building package dev:x64-windows failed with: POST_BUILD_CHECKS_FAILED
``````

I am not sure how to proceed. I would appreciate any advice, thanks!

**Comment by ras0219-msft** [comment]
Thanks to both of you for contributing to this issue!

I've pushed `vcpkg upgrade`, which should significantly improve the ergonomics in this area 😄. Please see my comment in https://github.com/Microsoft/vcpkg/issues/501#issuecomment-351360146

**Comment by jasjuang** [comment]
Thanks a lot! I tried it on the recent assimp update and it is working great.
