### ISSUE TITLE
[boost ports] `vcpkg install` or `vcpkg upgrade` "Error: Unrecognized identifer name v120. Add to override list in triplet file."

### ISSUE THREAD

**Issue by StarGate-One** [microsoft/vcpkg#13373]
**Describe the bug**
When performing `vcpkg upgrade` or `vcpkg install` on the `boost` ports the following error message occurs since commit **Fix [boost] MSVC 2013 v120 Build (#10645)**

**Environment**
- OS: [Microsoft Windows [Version 10.0.19041.488]]
- Compiler: Visual Studio  Version: 16.7.2  VS Tools Version: 14.27.29110

**To Reproduce**
1. `git pull` as of 20200905 @ 21:00 GMT
2. `.\bootstrap-vcpkg.bat -verbose -disableMetrics -win64 -withVSPath "'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community'"`
3. `vcpkg upgrade`
4. Console output:
**`Error: Unrecognized identifer name v120. Add to override list in triplet file.`**
**`Error: Unrecognized identifer name v120. Add to override list in triplet file.`**
`The following packages will be rebuilt:`
`  * bigint[core]:x64-windows`
`  * boost[core,mpi]:x64-windows`
`  * boost-accumulators[core]:x64-windows`
`... 100 more ports...`
`  * python3[core]:x64-windows`
`  * shiva[core]:x64-windows`
`  * spdlog[benchmark,core]:x64-windows`
`  * tmx[core]:x64-windows`
`Additional packages (*) will be modified to complete this operation.`
`If you are sure you want to rebuild the above packages, run this command with the --no-dry-run option.`
5. `vcpkg upgrade --debug`
`[DEBUG] Feature flag 'binarycaching' = off`
`[DEBUG] Feature flag 'manifests' unset`
`[DEBUG] Feature flag 'compilertracking' unset`
`[DEBUG] Feature flag 'registries' unset`
`[DEBUG] Using vcpkg-root: D:\vcpkg_x64\vs2019\prod`
`[DEBUG] Using installed-root: D:\vcpkg_x64\vs2019\prod\installed`
`[DEBUG] Using buildtrees-root: D:\vcpkg_x64\vs2019\prod\buildtrees`
`[DEBUG] Using downloads-root: D:\vcpkg_x64\downloads`
`[DEBUG] Using packages-root: D:\vcpkg_x64\vs2019\prod\packages`
`[DEBUG] Using scripts-root: D:\vcpkg_x64\vs2019\prod\scripts`
`[DEBUG] Default binary cache path is: C:\Users\Tim.Autry\AppData\Local\vcpkg/archives`
`[DEBUG] Found path: C:\Program Files\CMake\bin/cmake.exe`
`[DEBUG] Found path: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin/cmake.exe`
`[DEBUG] CreateProcessW("C:\Program Files\CMake\bin/cmake.exe" --version)`
`[DEBUG] cmd_execute_and_stream_data() returned 0 after    21896 us`
`[DEBUG] CreateProcessW("C:\Program Files\CMake\bin/cmake.exe" -DVCPKG_ROOT_DIR=D:/vcpkg_x64/vs2019/prod -DPACKAGES_DIR=D:/vcpkg_x64/vs2019/prod/packages -DBUILDTREES_DIR=D:/vcpkg_x64/vs2019/prod/buildtrees -D_VCPKG_INSTALLED_DIR=D:/vcpkg_x64/vs2019/prod/installed -DDOWNLOADS=D:/vcpkg_x64/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "D:\vcpkg_x64\vs2019\prod\buildtrees\0.vcpkg_dep_info.cmake")`
`[DEBUG] cmd_execute_and_stream_data() returned 0 after    19191 us`
**`Error: Unrecognized identifer name v120. Add to override list in triplet file.`**
**`Error: Unrecognized identifer name v120. Add to override list in triplet file.`**
`[DEBUG] CreateProcessW("C:\Program Files\CMake\bin/cmake.exe" -DVCPKG_ROOT_DIR=D:/vcpkg_x64/vs2019/prod -DPACKAGES_DIR=D:/vcpkg_x64/vs2019/prod/packages -DBUILDTREES_DIR=D:/vcpkg_x64/vs2019/prod/buildtrees -D_VCPKG_INSTALLED_DIR=D:/vcpkg_x64/vs2019/prod/installed -DDOWNLOADS=D:/vcpkg_x64/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "D:\vcpkg_x64\vs2019\prod\buildtrees\1.vcpkg_dep_info.cmake")`
`[DEBUG] cmd_execute_and_stream_data() returned 0 after    13041 us`
`The following packages will be rebuilt:`
`  * bigint[core]:x64-windows`
`  * boost[core,mpi]:x64-windows`
`  * boost-accumulators[core]:x64-windows`
`... 100 more ports...`
`  * python3[core]:x64-windows`
`  * shiva[core]:x64-windows`
`  * spdlog[benchmark,core]:x64-windows`
`  * tmx[core]:x64-windows`
`Additional packages (*) will be modified to complete this operation.`
`If you are sure you want to rebuild the above packages, run this command with the --no-dry-run option.`
`[DEBUG] D:\vcpkg_x64\vs2019\prod\toolsrc\src\vcpkg\commands.upgrade.cpp(177)`
`[DEBUG] Exiting after 121982 us (121363 us)`

Repro code when

**Expected behavior**
The should be no Error referencing to VS2013 build tools v120, when using VS2015, VS2017 and/or VS2019.

**Failure logs** 
- None

**Additional context**
1. This error also occurs when doing `vcpkg install boost` libraries.
2. The error does not appear to stop the `vcpkg install boost` process
3. I do not know if it stops or effects the `vcpkg upgrade --no-dry-run` upgrade process as I have a customized script that actually removes all the ports to be upgraded and then installs the ports again since the `vcpkg upgrade` does not have the `--editable` or `--x-use-aria2` switches like the `vcpkg install`.

**Comment by StarGate-One** [comment]
Found this on the x64-windows pipeline run for this change....

https://dev.azure.com/vcpkg/public/_build/results?buildId=42551&view=logs&j=384c4415-93cb-5962-b64b-d976ffb39bd5&t=911b920d-b794-53d6-9344-822ccdf736be
![image](https://user-images.githubusercontent.com/68293825/92313884-c8259980-ef9e-11ea-9c5f-390c469a7d39.png)


It seems the CI pipeline failed to detect this error.

**Comment by PhoebeHui** [comment]
@StarGate-One, thanks for reporting this issue!

The root cause is invalid identifier '!v120' added to CONTROl file in https://github.com/microsoft/vcpkg/pull/10645.

**Comment by PhoebeHui** [comment]
cc @ManuelKugelmann

I would revert the invalid identifiler v120 for unblocking boost, and keep others changes in PR #10645 for futher fix from contributor.

**Comment by StarGate-One** [comment]
@BillyONeal @strega-nil @ras0219-msft 
Just an FYI if it is something the CI azure-pipelines should catch as an error in the future, when an invalid identified is added to the CONTROL or vcpkg.json file-
See paragraph screen grab above: https://github.com/microsoft/vcpkg/issues/13373#issuecomment-687666521

**Comment by PhoebeHui** [comment]
Thanks @StarGate-One for your suggestions!
