### ISSUE TITLE
[New Port Request] Served

### ISSUE THREAD

**Issue by dominique120** [microsoft/vcpkg#13380]
**Library name**: Served

**Library description:** Served is a C++ library for building high performance RESTful web servers. Served builds upon Boost.ASIO to provide a simple API for developers to create HTTP services in C++.

**Source repository URL:** https://github.com/meltwater/served

**Anything else that is useful to know when adding (such as optional features the library may have that should be included):**
Requires boost.asio and Ragel(already ported to vcpkg) is optional. I have already compiled it on Windows with cmake and Visual Studio 2019, however you do need to specify NOGDI for the preprocessor due to a identically named macro (its called ERROR).

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
