### ISSUE TITLE
[boost-thread:x86-mingw-dynamic] build failure

### ISSUE THREAD

**Issue by bialasjaroslaw** [microsoft/vcpkg#13389]
**Host Environment**
- OS: Windows 10
- Compiler: g++ (i686-posix-dwarf-rev0, Built by MinGW-W64 project) 8.1.0 - This is up to date version shipped with Qt

**To Reproduce**
-- In PS --
`setx PATH "C:\Qt\Tools\mingw810_32\bin"`
-- restart PS --
`git clone https://github.com/microsoft/vcpkg`
`cd vcpkg`
`./bootstrap-vcpkg.bat`
`./vcpkg --triplet x86-mingw-dynamic install boost-thread`

**Failure logs** 
This is output from build (last step, I cut off installation of required packages):
https://pastebin.com/5FkNYqWC
This is content of install-x86-mingw-dynamic-dbg-out.log
https://pastebin.com/GzbHjrsV

This is run from scratch as you can see. I tried with older mingw - 7.3.0 and with 64 bit version as well, also from scratch but with the same effect

**Comment by bialasjaroslaw** [comment]
I found out that `Jamroot.jam` contains a lot of references to libboost*.so file, while their names are *.dll.a, so by simply modifying that I am able to build package manually.

**Comment by longnguyen2004** [comment]
This should be fixed by the upgrade to boost 1.74.0 a while ago, which had much better support for mingw targets.
