### ISSUE TITLE
Build error, cmake cant find a library (which is required for another one I installed, PCL cant find Eigen)

### ISSUE THREAD

**Issue by a93a** [microsoft/vcpkg#13405]
I am running windows 10, and I am trying to add a library to my project (Android/NDK). I installed https://pointclouds.org/ suing vcpkg and I am now trying to include it in a Android/ndk project. This is my cmake:

```
cmake_minimum_required(VERSION 3.4.1)
add_library( native-lib SHARED native-lib.cpp )
find_library(log-lib log )
target_link_libraries(native-lib ${log-lib} )

set(PCL_DIR "C:\\Users\\xxx\\Desktop\\pclndk\\vcpkg\\installed\\x86-windows\\share\\pcl")
find_package(PCL 1.3 REQUIRED COMPONENTS)
include_directories(${PCL_INCLUDE_DIRS})
link_directories(${PCL_LIBRARY_DIRS})
add_definitions(${PCL_DEFINITIONS})
add_executable(pcd_write_test pcd_write.cpp)
target_link_libraries(pcd_write_test ${PCL_LIBRARIES})
```

When I try to build,  I get this error:

```
C:\Users\xxx\ndktest\app\src\main\cpp\CMakeLists.txt : C/C++ debug|armeabi-v7a : CMake Error at C:/Users/xxx/Desktop/pclndk/vcpkg/installed/x86-windows/share/pcl/PCLConfig.cmake:56 (message):
  common is required but eigen was not found
Call Stack (most recent call first):
  C:/Users/xxx/Desktop/pclndk/vcpkg/installed/x86-windows/share/pcl/PCLConfig.cmake:356 (pcl_report_not_found)
  C:/Users/xxx/Desktop/pclndk/vcpkg/installed/x86-windows/share/pcl/PCLConfig.cmake:524 (find_external_library)
  CMakeLists.txt:11 (find_package)

```

I tried setting EIGEN_DIR and/or EIGEN_ROOT by `set(EIGEN_DIR "C:\\Users\\xxx\\Desktop\\pclndk\\vcpkg\\installed\\x86-windows\\share\\eigen3")` but it does not seem to help. I still get same error. I also tried setting PCL_DIR to `set(PCL_DIR "C:\\Users\\xxx\\Desktop\\pclndk\\vcpkg\\packages\\pcl_x86-windows\\share\\pcl")` with no luck and same error message.

Any suggestions?

**Comment by NancyLi1013** [comment]
Hi @a93a 
Thanks for posting this issue.
Sorry for the delay.
I try to build `pcl` failed with the same error if I do as the above instructions.
But after I added `set(EIGEN_ROOT "F:\\vcpkg\\installed\\x86-windows\\share\\eigen3")`, the error info disappered.

In fact, if we have run `.\vcpkg integrate install` before we build the project, it's unnecessary to set the directories for `pcl `or `eigen3`.

We just need to set `CMAKE_TOOLCHAIN_FILE` in CMakeSettings.json.

Please see this https://github.com/microsoft/vcpkg/blob/master/docs/examples/installing-and-using-packages.md#cmake-toolchain-file.

**Comment by NancyLi1013** [comment]
@a93a 

Please let me know if this is still a problem for you.

Thanks.

**Comment by NancyLi1013** [comment]
Closing this issue for now since there is no response.

Please feel free to reopen this if it is still a problem for you.
