### ISSUE TITLE
How can I control Python version while building OpenImageIO binding?

### ISSUE THREAD

**Issue by a-bulygin** [microsoft/vcpkg#13403]
I'm trying to build OpenImageIO for Windows using Docker with the following parameters:
```
vcpkg install openimageio[opencolorio,pybind11,tools]:x64-windows
```
By default it makes python bindings for python 3.8. But for my project I need bindings for python 3.7. How can I change python version?

My Dockerfile is as follows:
```
# escape=`

# Use the latest Windows Server Core image with .NET Framework 4.8.
FROM mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019

SHELL ["cmd", "/S", "/C"]

# Install VS Building Tools
ADD https://aka.ms/vs/16/release/vs_buildtools.exe C:\Temp\vs_buildtools.exe
ADD https://aka.ms/vs/16/release/channel C:\Temp\VisualStudio.chman
RUN C:\Temp\vs_buildtools.exe `
    --quiet --wait --norestart --nocache `
    --installPath C:\BuildTools `
    --channelUri C:\Temp\VisualStudio.chman `
    --installChannelUri C:\Temp\VisualStudio.chman `
    --add Microsoft.VisualStudio.Workload.VCTools;includeRecommended `
    --add Microsoft.Component.MSBuild `
 || IF "%ERRORLEVEL%"=="3010" EXIT 0

SHELL ["powershell"]

# Install Chocolatey
RUN iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

# Install Git
RUN choco install git -y

# Install CMake
RUN choco install cmake -y

# Install vcpkg
WORKDIR c:\\build
RUN git clone https://github.com/Microsoft/vcpkg.git 
COPY vcpkg\ports\freeglut c:\build\vcpkg\ports\freeglut
WORKDIR c:\\build\\vcpkg
RUN .\bootstrap-vcpkg.bat

# Build oiio
RUN .\vcpkg install openimageio[opencolorio,pybind11,tools]:x64-windows

# Create libs copy batch
COPY scripts\copy_libs.bat c:\build

CMD C:\build\copy_libs.bat
```

**Comment by Hoikas** [comment]
Unfortunately, vcpkg's python3 port only supports python 3.8. You could roll back to commit ca52d42, in which the python3 port used python 3.7, or build an overlay port using its sources. Be aware though that the old python3 port will not function correctly with static triplets.

**Comment by a-bulygin** [comment]
> You could roll back to commit `ca52d42`

Yes, that's what i finally did. Thank you Adam!

**Comment by adamgranthendry** [comment]
1. First compile the VCPKG library of python3.7.1, modify the python version number in ports\python3\ portfile.cmake to
    set (PYTHON_VERSION_MAJOR 3)
    set(PYTHON_VERSION_MINOR 7)
    set(PYTHON_VERSION_PATCH 1)
2. Download the latest version of python-cpython-v3.7.1.tar.gz file to the downloads directory
3. Modify the scripts/cmake/vcpkg_download_distfile.cmake file. The purpose is to cancel the verification of whether the downloaded python-cpython-v3.7.1.tar.gz file is consistent with the server. We mainly use the function (test_hash FILE_PATH FILE_KIND CUSTOM_ERROR_ADVICE) cancel, add return() directly to the first line of the function to return.

**Comment by alejcabrera** [comment]
> First compile the VCPKG library of python3.7.1, modify the python version number in ports\python3\ portfile.cmake to
set (PYTHON_VERSION_MAJOR 3)
set(PYTHON_VERSION_MINOR 7)
set(PYTHON_VERSION_PATCH 1)
Download the latest version of python-cpython-v3.7.1.tar.gz file to the downloads directory
Modify the scripts/cmake/vcpkg_download_distfile.cmake file. The purpose is to cancel the verification of whether the downloaded python-cpython-v3.7.1.tar.gz file is consistent with the server. We mainly use the function (test_hash FILE_PATH FILE_KIND CUSTOM_ERROR_ADVICE) cancel, add return() directly to the first line of the function to return.

I'm going over the same, I'm trying your suggestion but I get this:
(  I changed from python 3.9.7 to 3.7.9)

```
PS C:\Users\voidr\vcpkg> ./vcpkg.exe install python3 --recurse
Computing installation plan...
The following packages will be built and installed:
    python3[core]:x86-windows -> 3.9.7#1
Detecting compiler hash for triplet x86-windows...
Restored 0 packages from C:\Users\voidr\AppData\Local\vcpkg\archives in 183.7 us. Use --debug to see more details.
Starting package 1/1: python3:x86-windows
Building package python3[core]:x86-windows...
-- Downloading https://github.com/python/cpython/archive/v3.7.9.tar.gz -> python-cpython-v3.7.9.tar.gz...
-- Extracting source C:/Users/voidr/vcpkg/downloads/python-cpython-v3.7.9.tar.gz
-- Applying patch 0002-use-vcpkg-zlib.patch
CMake Error at scripts/cmake/z_vcpkg_apply_patches.cmake:61 (message):
  Applying patch failed: Checking patch PCbuild/pythoncore.vcxproj...

  Hunk #1 succeeded at 407 (offset -100 lines).

  error: while searching for:

    <Target Name="_WarnAboutToolset" BeforeTargets="PrepareForBuild" Condition="$(PlatformToolset) != 'v140' and $(PlatformToolset) != 'v141' and $(PlatformToolset) != 'v142'">
      <Warning Text="Toolset $(PlatformToolset) is not used for official builds. Your build may have errors or incompatibilities." />
    </Target>
    <Target Name="_WarnAboutZlib" BeforeTargets="PrepareForBuild" Condition="!$(IncludeExternals)">
      <Warning Text="Not including zlib is not a supported configuration." />
    </Target>

  error: patch failed: PCbuild/pythoncore.vcxproj:556

  error: PCbuild/pythoncore.vcxproj: patch does not apply

Call Stack (most recent call first):
  scripts/cmake/vcpkg_extract_source_archive.cmake:230 (z_vcpkg_apply_patches)
  scripts/cmake/vcpkg_extract_source_archive_ex.cmake:32 (vcpkg_extract_source_archive)
  scripts/cmake/vcpkg_from_github.cmake:180 (vcpkg_extract_source_archive_ex)
  ports/python3/portfile.cmake:39 (vcpkg_from_github)
  scripts/ports.cmake:141 (include)


Error: Building package python3:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: python3:x86-windows
  Vcpkg version: 2021-09-10-2059ef11aa6067e6f59b0d939c5d17e3c5c47d3e
```

**Comment by p0las** [comment]
@alejcabrera facing the same issue. did you solve it by any chance?

**Comment by alejcabrera** [comment]
> @alejcabrera facing the same issue. did you solve it by any chance?

It didn't work for me, so I used Hoikas solution.
https://github.com/microsoft/vcpkg/issues/13403#issuecomment-690376518

unfortunately like this I get an outdated version of oiio, but so far so good.

**Comment by JorgeHernandezibanezinbibo** [comment]
Hello,
I have a similar problem. I need to build OpenImageIO for several python versions: 3.7, 3.9, 3.10. Do you know if it's possible to specifify the python version or use an external python installation for the compilation? It would make it more easy.

But, if is not possible to specify the version, do you know what vcpkg commit or release should I use to have OpenImageIO for Python 3.10.6?
Thx a lot.
