### ISSUE TITLE
[x86-windows] build failure Building package boost-container:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by J1mbo** [microsoft/vcpkg#13406]
**Host Environment**
- OS: Windows 10 19041.450
- Compiler: Vcpkg version: 2020.06.15-nohash

**To Reproduce**
`./vcpkg install boost`

**Failure logs** 
Starting package 1/107: boost-container:x86-windows
Building package boost-container[core]:x86-windows...
Could not locate cached archive: C:\Users\j1mbo\AppData\Local\vcpkg/archives\d3\d31a1a9692d5910719d362e3ffffa65671e4f3b6.zip
-- Using cached C:/Users/j1mbo/vcpkg/downloads/boostorg-container-boost-1.73.0.tar.gz
-- Cleaning sources at C:/Users/j1mbo/vcpkg/buildtrees/boost-container/src/ost-1.73.0-206a404164.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/j1mbo/vcpkg/downloads/boostorg-container-boost-1.73.0.tar.gz
-- Using source at C:/Users/j1mbo/vcpkg/buildtrees/boost-container/src/ost-1.73.0-206a404164.clean
CMake Error at installed/x86-windows/share/boost-build/boost-modular-build.cmake:57 (message):
  Could not find b2 in
  C:/Users/j1mbo/vcpkg/installed/x86-windows/tools/boost-build
Call Stack (most recent call first):
  ports/boost-container/portfile.cmake:12 (boost_modular_build)
  scripts/ports.cmake:79 (include)

Error: Building package boost-container:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-container:x86-windows
  Vcpkg version: 2020.06.15-nohash

**Comment by egroj97** [comment]
Happens to me too

**Comment by PhoebeHui** [comment]
It due to b2.exe is treated as a virus, and it was removed by anti-virus software。
Duplicated to https://github.com/microsoft/vcpkg/issues/13353
