### ISSUE TITLE
[ICU] CMake project cannot find Debug ICU library

### ISSUE THREAD

**Issue by kazzatso** [microsoft/vcpkg#13413]
**Describe the bug**
Debug CMake project built with Ninja cannot find the debug ICU library and fails to begin to build at all because of it.

**Environment**
- OS: Windows x64
- Compiler: MSVC 2019 16.7.2

**To Reproduce**
1. ./vcpkg install icu
   * Note that ICU builds and installs correctly for both release and debug
2. ./vcpkg integrate install (if necessary)
3. Create new CMake project using the Ninja generator in Visual Studio
4. Add appropriate find_package and target_link_libraries declarations to your CMakeLists.txt file
   * e.g., find_package(ICU REQUIRED COMPONENTS uc data i18n io)
   * e.g., target_link_libraries(main PRIVATE ICU::uc ICU::i18n ICU::data ICU::io)
5. Generate the CMake cache
   * Note that CMake correctly finds ICU during the generation phase
6. Try to build in Debug configuration
   * Note the error: "'.../vcpkg/installed/x64-windows/debug/lib/icuuc.lib', needed by 'TARGET', missing and no known rule to make it."
   * Note that it is looking for a Release version of icuuc.lib in the debug install directory (icuucd.lib has been correctly installed to this location).
   * Note that Release configurations correctly find icuuc.lib in .../<triplet>/lib/icuuc.lib.

**Expected behavior**
The project should be able to build in Debug configuration against a debug version of ICU.

**Comment by kazzatso** [comment]
I have a pull request to fix this issue at #13400.

**Comment by PhoebeHui** [comment]
@kazzatso, I can't repro this issue, could you provide the config log with us?

BTW, I don't think add the '-MDd' flag back could resolve this issue, since we already has that flag in toolchain file.

**Comment by kazzatso** [comment]
@PhoebeHui Please see attached for my CMakeLists.txt files. I'm including ICU in the library.

[Library CMakeLists.txt](https://github.com/microsoft/vcpkg/files/5236410/CMakeLists.txt)
[Application CMakeLists.txt](https://github.com/microsoft/vcpkg/files/5236444/CMakeLists.txt)

Without the flags, CMake cache generation succeeds but compilation fails before it starts building .cpp files. With the flags, everything builds as expected.

The bug may depend on ICU being built into a static library rather than into an application directly. If so, I can update the issue description.

**Comment by PhoebeHui** [comment]
@kazzatso, sorry for my late reply.

I tried your CMakeList.txt file, however I still can't repro this issue, what's cmake revision do you use? my cmake revision is 3.17

I also checked the FindICU.cmake file in cmake module, it's already handle the debug and release configuration.
The libs correctly set in CMakeCache.txt file
//ICU uc library (debug)
ICU_UC_LIBRARY_DEBUG:FILEPATH=E:/vcpkg/clean/vcpkg/installed/x64-windows/debug/lib/icuucd.lib

//ICU uc library (release)
ICU_UC_LIBRARY_RELEASE:FILEPATH=E:/vcpkg/clean/vcpkg/installed/x64-windows/lib/icuuc.lib

What I tried:
1. ./vcpkg install icu;x64-windows
2.  ./vcpkg integrate install
3. Create CMake project by Visual studio with x64-debug configuration select, and set the following variable.
     "name": "x64-Debug",
     "generator": "Ninja",
     "cmakeCommandArgs": "-DCMAKE_TOOLCHAIN_FILE=E:/vcpkg/clean/vcpkg/scripts/buildsystems/vcpkg.cmake",
      buildCommandArgs": "",

Add the following to my CMakeLists.txt file
```
find_package(OpenGL REQUIRED)
find_package(EnTT CONFIG REQUIRED)
find_package(fmt CONFIG REQUIRED)
find_package(freetype CONFIG REQUIRED)
find_package(GLEW REQUIRED)
find_package(glm CONFIG REQUIRED)
find_package(harfbuzz CONFIG REQUIRED)
find_package(ICU REQUIRED COMPONENTS uc data i18n io)
target_link_libraries(icutest PRIVATE EnTT::EnTT)
target_link_libraries(icutest PUBLIC fmt::fmt fmt::fmt-header-only)
target_link_libraries(icutest PRIVATE freetype)
target_link_libraries(icutest PRIVATE GLEW::GLEW)
target_link_libraries(icutest PUBLIC glm)
target_link_libraries(icutest PRIVATE harfbuzz::harfbuzz)
target_link_libraries(icutest PRIVATE ICU::uc ICU::i18n ICU::data ICU::io)
```
4. Generate the project
5. Build the project, everything looks correct.

**Comment by PhoebeHui** [comment]
ping @kazzatso

**Comment by PhoebeHui** [comment]
@kazzatso, feel free reopen this issue if it still be a problem for you. I will the close the PR as well, since I don't think it's needed.

**Comment by dsazonoff** [comment]
I have the same issue on windows 11, clion cmake ninja vcpkg. If I can create a small reproducible example outside of my project, I'll request to reopen this issue.
P.S. workaround that I found is to set ICU_ROOT - in this case debug libraries are resolved properly.
