### ISSUE TITLE
[pcl:x64-windows-static] build failure

### ISSUE THREAD

**Issue by yrzhanov** [microsoft/vcpkg#13419]
**Host Environment**
Windows 10 Community
Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27043 for x64

**To Reproduce**
`./vcpkg install pcl:x64-windows-static`

**Failure logs** 
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:175 (message):
    Command failed: D:/VariousCodes/vcpkg/downloads/tools/cmake-3.11.4-windows/cmake-3.11.4-win32-x86/bin/cmake.exe;--build;.;--config;Release;--target;install;--;-v;-j1
    Working Directory: D:/VariousCodes/vcpkg/buildtrees/pcl/x64-windows-static-rel
    See logs for more information:
      D:\VariousCodes\vcpkg\buildtrees\pcl\install-x64-windows-static-rel-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/pcl/portfile.cmake:72 (vcpkg_install_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package pcl:x64-windows-static failed with: BUILD_FAILED

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Did you run `git pull` and `.\bootstrap-vcpkg.bat` before installing `pcl:x64-windows-static`? I see in your log `Command failed: D:/VariousCodes/vcpkg/downloads/tools/cmake-3.11.4-windows/cmake-3.11.4-win32-x86/bin/cmake.exe;--build;.;--config;Release;--target;install;--;-v;-j1`, the version of cmake is 3.11.4, but now the version of vcpkg is 3.17.2. If you install `pcl:x64-windows-static` after running `git pull` and `.\bootstrap-vcpkg.bat`, please provide the error log: `D:\VariousCodes\vcpkg\buildtrees\pcl\install-x64-windows-static-rel-out.log`.

**Comment by LilyWangL** [comment]
Pinging @yrzhanov for response.

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
