### ISSUE TITLE
 osgearth:x64-window

### ISSUE THREAD

**Issue by ToninoTarsi** [microsoft/vcpkg#13414]
**Host Environment**
- OS: Windows
- Compiler: VS2017

**To Reproduce**
`./vcpkg install osgearth:x64-windows`

**Failure logs** 
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:141 (message):
    Command failed: I:/Openscenegraph/New2020/vcpkg/downloads/tools/cmake-3.17.2-windows/cmake-3.17.2-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v
    Working Directory: I:/Openscenegraph/New2020/vcpkg/buildtrees/osgearth/x64-windows-dbg
    See logs for more information:
      I:\Openscenegraph\New2020\vcpkg\buildtrees\osgearth\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/osgearth/portfile.cmake:25 (vcpkg_install_cmake)
  scripts/ports.cmake:79 (include)

Error: Building package osgearth:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: osgearth:x64-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.

FAILED: src/osgEarth/CMakeFiles/osgEarth.dir/GEOS.cpp.obj 
C:\PROGRA~2\MIB055~1\2017\ENTERP~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe   /TP -DCURL_STATICLIB -DOSGEARTH_HAVE_GEOS -DOSGEARTH_HAVE_MBTILES -DOSGEARTH_HAVE_MVT -DOSGEARTH_HAVE_SQLITE3 -DOSGEARTH_LIBRARY -DTIXML_USE_STL -D_CRT_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS -DosgEarth_EXPORTS -Ibuild_include -II:\Openscenegraph\New2020\vcpkg\buildtrees\osgearth\src\ecb188e593-ef25d023cd.clean\src -II:\Openscenegraph\New2020\vcpkg\installed\x64-windows\include -Isrc\osgEarth /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /Fosrc\osgEarth\CMakeFiles\osgEarth.dir\GEOS.cpp.obj /Fdsrc\osgEarth\CMakeFiles\osgEarth.dir\ /FS -c I:\Openscenegraph\New2020\vcpkg\buildtrees\osgearth\src\ecb188e593-ef25d023cd.clean\src\osgEarth\GEOS.cpp
The GEOS C++ API is unstable, please use the C API instead
HINT: #include geos_c.h
I:\Openscenegraph\New2020\vcpkg\buildtrees\osgearth\src\ecb188e593-ef25d023cd.clean\src\osgEarth\GEOS.cpp(66): error C2440: 'initializing': cannot convert from 'std::unique_ptr<geos::geom::CoordinateSequence,std::default_delete<_Ty>>' to 'geos::geom::CoordinateSequence *'
        with
        [
            _Ty=geos::geom::CoordinateSequence
        ]
I:\Openscenegraph\New2020\vcpkg\buildtrees\osgearth\src\ecb188e593-ef25d023cd.clean\src\osgEarth\GEOS.cpp(66): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
I:\Openscenegraph\New2020\vcpkg\buildtrees\osgearth\src\ecb188e593-ef25d023cd.clean\src\osgEarth\GEOS.cpp(168): error C2664: 'geos::geom::Polygon *geos::geom::GeometryFactory::createPolygon(const geos::geom::LinearRing &,const std::vector<geos::geom::LinearRing *,std::allocator<_Ty>> &) const': cannot convert argument 2 from 'std::vector<geos::geom::Geometry *,std::allocator<_Ty>> *' to 'std::vector<geos::geom::LinearRing *,std::allocator<_Ty>> *'
        with
        [
            _Ty=geos::geom::LinearRing *
        ]
        and
        [
            _Ty=geos::geom::Geometry *
        ]
        and
        [
            _Ty=geos::geom::LinearRing *
        ]

**Comment by sfhacker** [comment]
Are we **STILL** having issues building this port (as it is called)?

**Comment by JackBoosY** [comment]
Duplicate with #13292.
