### ISSUE TITLE
protobuf:x86-windows build failure

### ISSUE THREAD

**Issue by rkrimper** [microsoft/vcpkg#13410]
**Host Environment**
- OS: Windows 7
- Compiler: 2020.06.15-nohash

**To Reproduce**
`./vcpkg install protobuf`

**Failure logs** 
Building package protobuf[core]:x86-windows...
Could not locate cached archive: C:\Users\rkrimper\AppData\Local\vcpkg/archives\ae\ae1fb398f8edfecbac00f1fd289aee444af0a07e.zip
-- Using cached C:/vcpkg/downloads/protocolbuffers-protobuf-fde7cf7358ec7cd69e8db9be4f1fa6a5c431386a.tar.gz
-- Cleaning sources at C:/vcpkg/buildtrees/protobuf/src/a5c431386a-c9deea9e31.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg/downloads/protocolbuffers-protobuf-fde7cf7358ec7cd69e8db9be4f1fa6a5c431386a.tar.gz
-- Applying patch fix-uwp.patch
-- Applying patch fix-android-log.patch
-- Applying patch fix-static-build.patch
-- Using source at C:/vcpkg/buildtrees/protobuf/src/a5c431386a-c9deea9e31.clean
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Installing: C:/vcpkg/packages/protobuf_x86-windows/share/protobuf/copyright
-- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz...
-- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz... Failed. Status: 35;"SSL connect error"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:178 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_find_acquire_program.cmake:403 (vcpkg_download_distfile)
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:270 (vcpkg_find_acquire_program)
  ports/protobuf/portfile.cmake:135 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:79 (include)

-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by bialasjaroslaw** [comment]
I just build this package without any issues.
Have you tried to download file manually or use some command line tools like curl or wget?

**Comment by sfhacker** [comment]
Are we **STILL** having issues building protobuf?

![image](https://user-images.githubusercontent.com/25817529/92501200-8d8f5b80-f241-11ea-9b13-16451a348a51.png)

**Comment by rkrimper** [comment]
I was able to download the file manually. Im new to using vcpkg, where do I put it in order to get past this error?

**Comment by bialasjaroslaw** [comment]
Might be [related](https://github.com/microsoft/vcpkg/issues/13286)

**Comment by rkrimper** [comment]
I moved the downloaded files:
mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz
mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst

to c:\vcpkg\downloads

and successfully installed protobuf.
