### ISSUE TITLE
Port request: Libconfig (hyperrealm)

### ISSUE THREAD

**Issue by jtravs** [Microsoft/vcpkg#1343]
https://github.com/hyperrealm/libconfig
http://www.hyperrealm.com/libconfig/

I'm happy to have a go if someone can point me in the direction of a guide on how to port an autotools based install system. It doesn't seem to be in the docs?

**Comment by atkawa7** [comment]
@jtravs See #1366

**Comment by jtravs** [comment]
Brilliant! Thanks for that!

**Comment by atkawa7** [comment]
@jtravs Thanks for the review. I have added your suggestions.

**Comment by atkawa7** [comment]
@ras0219-msft Could you close this ?
