### ISSUE TITLE
[x264] build failure

### ISSUE THREAD

**Issue by longnguyen2004** [microsoft/vcpkg#13435]
**Host Environment**
- OS: Windows 10 2004
- Compiler: MSVC 19.27.29111

**To Reproduce**
`./vcpkg install x264`

**Failure logs** 
[config-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/5195862/config-x64-windows-dbg-err.log)

**Additional context**
This is probably caused by #13019, as seen by the missing `rm`, `grep` errors in the log.

**Comment by sfhacker** [comment]
There seems to be a lot of issues building this project (x264)!
Just downloaded master branch and we were lucky!

![image](https://user-images.githubusercontent.com/25817529/92628543-5176fc00-f310-11ea-8449-754ebd5c2c73.png)

**Comment by NancyLi1013** [comment]
Hi @longnguyen2004 
Thanks for posting this issue.
It's duplicated to #13327. Let's track this issue there.
