### ISSUE TITLE
pt5   Error 

### ISSUE THREAD

**Issue by donggua2096** [microsoft/vcpkg#13437]
nstalling Mumble dependency qt5-base ...

Computing installation plan...
The following packages will be built and installed:
qt5-base[core]:x64-windows-static-md
Detecting compiler hash for triplet x64-windows-static-md...
Starting package 1/1: qt5-base:x64-windows-static-md
Building package qt5-base[core]:x64-windows-static-md...
Could not locate cached archive: C:\Users\王睿\AppData\Local\vcpkg/archives\eb\ebde57d2d16de4e82084fbe0a2ccfff9102ca124.zip
-- Using community triplet x64-windows-static-md. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: G:\vcpkg\triplets\community\x64-windows-static-md.cmake
-- Figuring out qt target mkspec. Target arch x64
-- Target mkspec set to: win32-msvc
-- Host mkspec not set. Qt's own buildsystem will try to figure out the host system
-- Downloading http://download.qt.io/official_releases/qt/5.15/5.15.0/submodules/qtbase-everywhere-src-5.15.0.tar.xz...
-- Extracting source G:/vcpkg/downloads/qtbase-everywhere-src-5.15.0.tar.xz
-- Applying patch patches/winmain_pro.patch
-- Applying patch patches/windows_prf.patch
-- Applying patch patches/qt_app.patch
-- Applying patch patches/gui_configure.patch
-- Applying patch patches/icu.patch
-- Applying patch patches/xlib.patch
-- Applying patch patches/egl.patch
-- Applying patch patches/8c44d70.diff
-- Applying patch patches/Qt5BasicConfig.patch
-- Applying patch patches/Qt5PluginTarget.patch
-- Applying patch patches/create_cmake.patch
-- Applying patch patches/Qt5GuiConfigExtras.patch
-- Using source at G:/vcpkg/buildtrees/qt5-base/src/5.15.0-f256990b37.clean
-- Configuring x64-windows-static-md-dbg
-- Configuring x64-windows-static-md-dbg done
-- Configuring x64-windows-static-md-rel
-- Configuring x64-windows-static-md-rel done
-- Building x64-windows-static-md-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:141 (message):
Command failed: G:/vcpkg/downloads/tools/jom/jom-1.1.3/jom.exe /J 5
Working Directory: G:/vcpkg/buildtrees/qt5-base/x64-windows-static-md-dbg
See logs for more information:
G:\vcpkg\buildtrees\qt5-base\build-x64-windows-static-md-dbg-out.log
G:\vcpkg\buildtrees\qt5-base\build-x64-windows-static-md-dbg-err.log

Call Stack (most recent call first):
ports/qt5-base/cmake/install_qt.cmake:66 (vcpkg_execute_build_process)
ports/qt5-base/portfile.cmake:306 (install_qt)
scripts/ports.cmake:79 (include)

Error: Building package qt5-base:x64-windows-static-md failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with .\vcpkg update, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
Package: qt5-base:x64-windows-static-md
Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.
vcpkg_install : Failed at installing package qt5-base (x64-windows-static-md)
所在位置 G:\mumble-releng-vcpkg-master\Get-MumbleDeps.ps1:82 字符: 4

        vcpkg_install -package $dep -targetTriplet $triplet -clea ...
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CategoryInfo : NotSpecified: (:) [Write-Error], WriteErrorException
FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,vcpkg_install
image

**Comment by donggua2096** [comment]
jom 1.1.3 - empower your cores

cl : Command line warning D9025 : overriding '/Fo./' with '/Foqlibraryinfo_final.obj'
jom: G:\vcpkg\buildtrees\qt5-base\x64-windows-static-md-dbg\qmake\Makefile [qlibraryinfo_final.obj] Error 2
jom: G:\vcpkg\buildtrees\qt5-base\x64-windows-static-md-dbg\qmake\Makefile.qmake-aux [G:\vcpkg\buildtrees\qt5-base\x64-windows-static-md-dbg\qmake\qmake.exe] Error 2
Error: cannot open C:\Users?Tíyí??▓\AppData\Local\Temp\qlatincodec.obj.7124.187.jom for write
jom: G:\vcpkg\buildtrees\qt5-base\x64-windows-static-md-dbg\src\tools\bootstrap\Makefile [release] Error 1
jom: G:\vcpkg\buildtrees\qt5-base\x64-windows-static-md-dbg\src\Makefile [sub-bootstrap-make_first] Error 2
jom: G:\vcpkg\buildtrees\qt5-base\x64-windows-static-md-dbg\Makefile [sub-src-make_first] Error 2
jom: G:\vcpkg\buildtrees\qt5-base\x64-windows-static-md-dbg\Makefile [sub-qmake-qmake-aux-pro-make_first] Error 2

**Comment by donggua2096** [comment]
cd src\ && ( if not exist Makefile G:\vcpkg\buildtrees\qt5-base\x64-windows-static-md-dbg\bin\qmake.exe -o Makefile G:\vcpkg\buildtrees\qt5-base\src\5.15.0-f256990b37.clean\src\src.pro ) && G:\vcpkg\downloads\tools\jom\jom-1.1.3\jom.exe -f Makefile
cd tools\bootstrap\ && ( if not exist Makefile G:\vcpkg\buildtrees\qt5-base\x64-windows-static-md-dbg\bin\qmake.exe -o Makefile G:\vcpkg\buildtrees\qt5-base\src\5.15.0-f256990b37.clean\src\tools\bootstrap\bootstrap.pro ) && G:\vcpkg\downloads\tools\jom\jom-1.1.3\jom.exe -f Makefile
cd qmake\ && ( if not exist Makefile.qmake-aux G:\vcpkg\buildtrees\qt5-base\x64-windows-static-md-dbg\bin\qmake.exe -o Makefile.qmake-aux G:\vcpkg\buildtrees\qt5-base\src\5.15.0-f256990b37.clean\qmake\qmake-aux.pro ) && G:\vcpkg\downloads\tools\jom\jom-1.1.3\jom.exe -f Makefile.qmake-aux
G:\vcpkg\downloads\tools\jom\jom-1.1.3\jom.exe -f Makefile.qmake-aux.Debug
G:\vcpkg\downloads\tools\jom\jom-1.1.3\jom.exe binary
cl -Yuqmake_pch.h -FIqmake_pch.h -Fpqmake_pch.pch -c -Fo./ -Fdqmake.pdb -W2 -nologo -O2 /MP /wd4577 -IG:\vcpkg\buildtrees\qt5-base\src\5.15.0-f256990b37.clean\qmake -IG:\vcpkg\buildtrees\qt5-base\src\5.15.0-f256990b37.clean\qmake\library -IG:\vcpkg\buildtrees\qt5-base\src\5.15.0-f256990b37.clean\qmake\generators -IG:\vcpkg\buildtrees\qt5-base\src\5.15.0-f256990b37.clean\qmake\generators\unix -IG:\vcpkg\buildtrees\qt5-base\src\5.15.0-f256990b37.clean\qmake\generators\win32 -IG:\vcpkg\buildtrees\qt5-base\src\5.15.0-f256990b37.clean\qmake\generators\mac -IG:\vcpkg\buildtrees\qt5-base\src\5.15.0-f256990b37.clean/src/3rdparty/tinycbor/src -IG:\vcpkg\buildtrees\qt5-base\src\5.15.0-f256990b37.clean/include -IG:\vcpkg\buildtrees\qt5-base\src\5.15.0-f256990b37.clean/include\QtCore -IG:\vcpkg\buildtrees\qt5-base\src\5.15.0-f256990b37.clean/include\QtCore\5.15.0 -IG:\vcpkg\buildtrees\qt5-base\src\5.15.0-f256990b37.clean/include\QtCore\5.15.0\QtCore -I..\src\corelib\global -IG:\vcpkg\buildtrees\qt5-base\src\5.15.0-f256990b37.clean\mkspecs\win32-msvc -D_CRT_SECURE_NO_WARNINGS -D_SCL_SECURE_NO_WARNINGS -DQT_VERSION_STR="5.15.0" -DQT_VERSION_MAJOR=5 -DQT_VERSION_MINOR=15 -DQT_VERSION_PATCH=0 -DQT_BUILD_QMAKE -DQT_BOOTSTRAPPED -DPROEVALUATOR_FULL -DQT_NO_FOREACH -DUNICODE -D_ENABLE_EXTENDED_ALIGNED_STORAGE -Foqlibraryinfo_final.obj G:\vcpkg\buildtrees\qt5-base\src\5.15.0-f256990b37.clean\src\corelib\global\qlibraryinfo.cpp
qlibraryinfo.cpp
c1xx: fatal error C1083: Cannot open compiler intermediate file: 'C:\Users?T¿¬y¿¬??¿ê\AppData\Local\Temp_CL_bff8b5edex': Invalid argument
cd doc\ && ( if not exist Makefile G:\vcpkg\buildtrees\qt5-base\x64-windows-static-md-dbg\bin\qmake.exe -o Makefile G:\vcpkg\buildtrees\qt5-base\src\5.15.0-f256990b37.clean\doc\doc.pro ) && G:\vcpkg\downloads\tools\jom\jom-1.1.3\jom.exe -f Makefile
G:\vcpkg\downloads\tools\jom\jom-1.1.3\jom.exe -f Makefile.Debug
G:\vcpkg\downloads\tools\jom\jom-1.1.3\jom.exe -f Makefile.Release

**Comment by donggua2096** [comment]
I would guess this also has to do with region and language settings of your system.

**Comment by sfhacker** [comment]
And the title of this post is amazing!
Which port is this one? qt5 ...? Let me have a look at it!

**Comment by donggua2096** [comment]
yes qt5-base

**Comment by Neumann-A** [comment]
isn't that the same error as in #13418
