### ISSUE TITLE
[boost] vcpkg install boost : Error code: Operation did not complete successfully because the file contains a virus or potentially unwanted software

### ISSUE THREAD

**Issue by mariuz** [microsoft/vcpkg#13431]
**Host Environment**
- OS: Windows
- Compiler: VS 2017

**To Reproduce**
`./vcpkg install boost`

**Failure logs** 
vcpkg install boost : Error code: Operation did not complete successfully because the file contains a virus or potentially unwanted software

**Additional context**
I have added the screenshot and details here https://twitter.com/mapopa/status/1303662674430111747

**Comment by PhoebeHui** [comment]
It due to b2.exe is treated as a virus by anti-virus software。
Duplicated to #13353
