### ISSUE TITLE
[openmvg:x64-windows-static-md] build failure with static CRT linking.

### ISSUE THREAD

**Issue by FishHe** [microsoft/vcpkg#13447]
as it is mentioned in #12229 

`

main_ComputeFeatures.cpp.obj : error LNK2019: unresolved external symbol __imp_vl_constructor referenced in function "public: __cdecl openMVG::features::SIFT_Image_describer::SIFT_Image_describer(struct openMVG::features::SIFT_Image_describer::Params const &,bool)" (??0SIFT_Image_describer@features@openMVG@@QEAA@AEBUParams@012@_N@Z)

`

I would like to use **x64-windows-static-md** to build openmvg[software].

**Comment by JackBoosY** [comment]
@cenit  Could you please take a look?

Thanks.

**Comment by cenit** [comment]
It's an open issue that the software feature of openmvg does not build correctly with statically linked libs.
I will investigate it more and I hope it can be fixed soon

**Comment by JackBoosY** [comment]
Ping @cenit, any progress?

**Comment by cenit** [comment]
to be honest, i don't know.
I saw that openmvg was updated to v2.0 by others, maybe the update fixed the error? sorry i don't have much time

**Comment by FrankXie05** [comment]
@FishHe Is this issue still exist?

**Comment by MonicaLiu0311** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
