### ISSUE TITLE
[lapack] How do I use Intel Fortran Compiler for lapack ?

### ISSUE THREAD

**Issue by FishHe** [microsoft/vcpkg#13452]
I use vcpkg on windows with vs2019 and intel studio xe 2020.
I add environment variable FC="...\ifort.exe", however :

```
-- Extracting source D:/vcpkg/downloads/Reference-LAPACK-lapack-v3.8.0.tar.gz
-- Using source at D:/vcpkg/buildtrees/lapack-reference/src/v3.8.0-954f10683f.clean
-- The Fortran compiler identification is unknown
-- No Fortran compiler found on the PATH. Using MinGW gfortran!
-- Using msys root at D:/vcpkg/downloads/tools/msys2/2d316d3dcc37bb3f
-- VCPKG_LIBRARY_LINKAGE linkage for lapack-reference using vcpkg's internal gfortran cannot be static due to linking against MinGW libraries. Forcing dynamic library linkage
```

**Comment by Neumann-A** [comment]
custom triplet (setting up the environment)
+ maybe custom toolchain.

 Basically `CMakeDetermineFortranCompiler` needs to be able to detect the compiler in the used environment

**Comment by FishHe** [comment]
Could you please show me how to customize the triplet and toolchain? @Neumann-A

**Comment by Neumann-A** [comment]
https://github.com/microsoft/vcpkg/blob/master/docs/users/triplets.md
https://github.com/qis/toolchains/tree/build

**Comment by FishHe** [comment]
Thanks. The issue #13475 is that I really want.
