### ISSUE TITLE
[WSL2/Debian 10.5] build vcpkg failure

### ISSUE THREAD

**Issue by Hoikas** [microsoft/vcpkg#13455]
**Describe the bug**
`./bootstrap-vcpkg.sh` fails.

**Environment**
- OS: WSL2/Debian 10.5
- Compiler: g++8

**To Reproduce**
1. `./bootstrap-vcpkg.sh`

**Error Log**
[CMakeError.log](https://github.com/microsoft/vcpkg/files/5202973/CMakeError.log)

**Comment by JackBoosY** [comment]
cc @BillyONeal

**Comment by BillyONeal** [comment]
It looks like this is where we're trying to detect whether to use std::filesystem vs. std::experimental::filesystem and it think's we're on Windows for some reason

**Comment by NancyLi1013** [comment]
Thanks for your feedback. @Hoikas 

Since we also don't have the environment to repro this issue. So let's close this issue for now. Please ping me to reopen this issue if anyone has the same problem in the future.
