### ISSUE TITLE
How do I install a package without a feature?

### ISSUE THREAD

**Issue by PlayerVMachine** [microsoft/vcpkg#13458]
For example curl has multiple ssl options when I select `curl[openssl]` on MacOS vcpkg installs it with `openssl,sectransport,ssl` as seen here:
`Building package curl[core,non-http,openssl,sectransp,ssh,ssl]:x64-osx...`
I would like to only install curl with openssl support if possible.

**Comment by JackBoosY** [comment]
`./vcpkg install curl[core]`.

**Comment by PlayerVMachine** [comment]
Awesome thank you! That might be a handy tip to note in the documentation on features.
