### ISSUE TITLE
 Error: Building package boost-compatibility:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by Erixar** [microsoft/vcpkg#13472]
On Windows 10  of 10.0.18363
**To Reproduce**
`./vcpkg install pcl

Starting package 3/103: boost-compatibility:x86-windows
Building package boost-compatibility[core]:x86-windows...
Could not locate cached archive: C:\Users\Erixar\AppData\Local\vcpkg/archives\34\34231cecbadde1397f5d99437d20f1c9044172c1.zip
-- Downloading https://github.com/boostorg/compatibility/archive/boost-1.73.0.tar.gz...
-- Extracting source C:/dev/vcpkg-master/vcpkg-master/downloads/boostorg-compatibility-boost-1.73.0.tar.gz
-- Using source at C:/dev/vcpkg-master/vcpkg-master/buildtrees/boost-compatibility/src/ost-1.73.0-44642da97c.clean
-- Packaging headers
-- Packaging headers done
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.73.0/LICENSE_1_0.txt...
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.73.0/LICENSE_1_0.txt... Failed. Status: 6;"Couldn't resolve host name"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:181 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  installed/x86-windows/share/boost-vcpkg-helpers/boost-modular-headers.cmake:17 (vcpkg_download_distfile)
  ports/boost-compatibility/portfile.cmake:12 (boost_modular_headers)
  scripts/ports.cmake:79 (include)

Error: Building package boost-compatibility:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-compatibility:x86-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.

**Additional context**
This problem appears when I'm trying to install pcl on my new computer,and before that vcpkg failed to connected with nuget to get 7-zip. I have to download it manually. Is there some mirror sources can be used in China?

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/13348.
