### ISSUE TITLE
[macOS] What is the current way to make portfile prefer usage of Vcpkg-built library over the system one? 

### ISSUE THREAD

**Issue by wrobelda** [microsoft/vcpkg#13470]
I am trying to figure out what is the correct way of forcing a portfile I am working on to make cmake lookup and link to libiconv built by vcpkg. Currently it uses the macOS-provided library, which causes a build failure:

```
Undefined symbols for architecture x86_64:
  "_iconv", referenced from:
      __nl_find_msg in libintl.a(dcigettext.c.o)
  "_iconv_open", referenced from:
      __nl_find_msg in libintl.a(dcigettext.c.o)
  "_libiconv_set_relocation_prefix", referenced from:
      _libintl_set_relocation_prefix in libintl.a(relocatable.c.o)
  "_locale_charset", referenced from:
      __nl_find_msg in libintl.a(dcigettext.c.o)
```

This is a typical issue to iconv and has been discussed previously at least [here](https://github.com/microsoft/vcpkg/pull/11072) and [here](https://github.com/microsoft/vcpkg/pull/11065). While I see that this was solved for libxml2 on Windows by [using a vcpkg-cmake-wrapper](https://github.com/microsoft/vcpkg/blob/ef91134964e8ddec77cd0db8943b72e0eaac2ef7/ports/libxml2/vcpkg-cmake-wrapper.cmake), I don't see anything similar for macOS in the repository.

I will appreciate any help you can provide. 

EDIT: actually, it was solved for libxml2 [here](https://github.com/microsoft/vcpkg/pull/11072). However, there was some speculation there as to what was the ideal way of going about it, so I would appreciate some clarification – and possibly also a new entry to FAQ?

**Comment by wrobelda** [comment]
OK, so I managed to dig a bit deeper and can see that vcpkg uses the gettext I have installed on my system via Home-brew. I now understand I need to implement something akin to ports/exiv2/vcpkg-cmake-wrapper.cmake

**Comment by wrobelda** [comment]
OK, that wasn't sound reasoning. What I understand now is that:
1. Any new port that has a gettext or libiconv in Build-Depends needs to provide an additional vcpkg-cmake-wrapper.cmake file
1. Any other port consuming such new port needs to patch own CMakeLists.txt and include something like:
```
if(APPLE)
  find_library(LIBINTL_LIBRARY NAMES intl)
endif()

find_package(unofficial-iconv REQUIRED)
link_libraries(${LIBINTL_LIBRARY} unofficial::iconv::libiconv)
```

**Comment by wrobelda** [comment]
Related issue #13027

**Comment by wrobelda** [comment]
Another related issue: #13481

**Comment by JackBoosY** [comment]
Sorry for late.
Usually, we prefer to use configuration modes such as `find_package(OpenCV CONFIG REQUIRED)`, but there are some ports that do not export their targets, but we provide `vcpkg-cmake-wrapper`.
For these ports with ready-made cmake support, when we install them, the usage information will be printed in the console like:
```
The package libxml2 is compatible with built-in CMake targets:

    find_package(LibXml2 REQUIRED)
    target_include_directories(main PRIVATE ${LIBXML2_INCLUDE_DIR})
    target_link_libraries(main PRIVATE ${LIBXML2_LIBRARIES})
```
For those ports that **DO NOT** provide cmake support, if cmake itself provides `Find${PORT}.cmake`, you can use `find_package(${PORT})` to use it, otherwise you must implement `find_library` and `find_path` yourself.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
