### ISSUE TITLE
[New Port Request] libdatachannel

### ISSUE THREAD

**Issue by Nemirtingas** [microsoft/vcpkg#13487]
Library name: libdatachannel

Library description: 
libdatachannel is a standalone implementation of WebRTC Data Channels and WebSockets in C++17 with C bindings for POSIX platforms (including GNU/Linux, Android, and Apple macOS) and Microsoft Windows

Licensed under LGPLv2.

Source repository URL: https://github.com/paullouisageneau/libdatachannel

Project homepage (if different from the source repository): 

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
Features:
For ICE implementation: use either libjuice or libnice : [libjuice ](https://github.com/paullouisageneau/libjuice) as default
For SSL: openssl or GNUTls : openssl as default

Extra dependencies:
[nlohmann::json](https://github.com/nlohmann/json)
[plog](https://github.com/paullouisageneau/plog)

This library addition would be awesome because we don't have a lot of WebRTC C/C++ libraries out there that are easy to build.
This one even have CMake support.

**Comment by LilyWangL** [comment]
This issue will be fixed in PR https://github.com/microsoft/vcpkg/pull/13704.
