### ISSUE TITLE
[libnice] Can't build on something else than Windows

### ISSUE THREAD

**Issue by Nemirtingas** [microsoft/vcpkg#13483]
**Host Environment**
- OS: Linux
- Compiler: latest vcpkg + gcc 7.5

**To Reproduce**
`./vcpkg install libnice`

**Failure logs** 
Logs are too big and complex to be put here. The whole build system is broken. It looks statically for Windows libs and headers.
Even after fixing the port's CMakeList.txt there are build issues.

**Comment by Nemirtingas** [comment]
Nice, thanks.

**Comment by BillyONeal** [comment]
Is that a pun?

**Comment by Nemirtingas** [comment]
I didn't mean to make a pun ;). I tested libnice on Ubuntu vcpkg and it builds so thanks !
