### ISSUE TITLE
[New Port Request] ZBar

### ISSUE THREAD

**Issue by nick908** [microsoft/vcpkg#13494]
Library name: ZBar

Library description: ZBar is an open source software suite for reading bar codes from various sources, including webcams.

Source repository URL: https://github.com/mchehab/zbar

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by JaosonMa** [comment]
> If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

so  did you team have the plane to add the zbar into vcpkg?
