### ISSUE TITLE
[utfcpp] Use vcpkg_install_cmake instead of copying include files directly

### ISSUE THREAD

**Issue by longnguyen2004** [microsoft/vcpkg#13495]
****

**Is your feature request related to a problem? Please describe.**
utfcpp does provide exported targets, which in my opinion is always better than `find_path` or `find_library`, but the current portfile for utfcpp doesn't use `vcpkg_install_cmake`, so we doesn't have exported targets to work on.

**Proposed solution**
Switch to `vcpkg_install_cmake`

**Comment by JackBoosY** [comment]
Good point, thanks for this issue!
