### ISSUE TITLE
Consider supporting sharing a root between multiple platforms

### ISSUE THREAD

**Issue by wrobelda** [microsoft/vcpkg#13490]
**Is your feature request related to a problem? Please describe.**
I intend to test my ports using Linux and Windows as well, both running on their respective VMs. I shared my vcpkg root folder from my macOS to both of them and tried to re-use it. Unfortunately, while I initially thought that it wouldn't be an issue, given that the same git repository is used for all platforms, it does fail:
1. bootstrapping on Linux after having bootstrapped on macOS (and vice versa) replaces the ./vcpkg binary, since both bear the same name.
2. Windows bootstrapping fails with: `vcpkg\toolsrc\src\vcpkg\vcpkglib.cpp(214)]: no such file or directory`.

**Proposed solution**
1. Extract/pull `toolsrc` into platform-specific folders
2. Either:
  - save another binary with a suffix (e.g. `-linux`) if `./vcpkg` already exists on the file system
  - or make the `./vcpkg` a symlink to `bin/vcpkg-PLATFORM`. The consecutive binaries (e.g. `vcpkg-linux`) should be saved in `bin/` folder, with a WARNING/INFO, leaving the original symlink intact. 

**Describe alternatives you've considered**
Checking out from a forked repo independently on each platform is not really a solution in this use case, where one wants to trial and error their ports even before they consider them draft PR worthy.

**Comment by JackBoosY** [comment]
@dan-shaw Do we need to consider this situation?

**Comment by strega-nil** [comment]
This isn't really a thing we wish to support, unfortunately. The best thing to do is to use distinct vcpkg roots, but the same `overlay-ports`.
