### ISSUE TITLE
[glog:x64-windows] build failure

### ISSUE THREAD

**Issue by gaqiang** [microsoft/vcpkg#13498]
**Host Environment**
- OS: Windows10 x64 professional 10.0.18362 
- Compiler: Visual Studio Professional 2017 15.9.11Windows 10 SDK (10.0.17763.0)

**To Reproduce**
`.\vcpkg install glog[core]:x64-windows`

**Failure logs** 
E:\vs_library\vcpkg>.\vcpkg install glog[core]:x64-windows
Computing installation plan...
The following packages will be built and installed:
    glog[core]:x64-windows
Detecting compiler hash for triplet x64-windows...
Starting package 1/1: glog:x64-windows
Building package glog[core]:x64-windows...
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg/archives\3b\3b8f6e53da2d39f587e8948384357d948b18a16f.zip
-- Using cached E:/vs_library/vcpkg/downloads/google-glog-v0.4.0.tar.gz
-- Cleaning sources at E:/vs_library/vcpkg/buildtrees/glog/src/v0.4.0-46ccbc49a4.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/vs_library/vcpkg/downloads/google-glog-v0.4.0.tar.gz
-- Applying patch glog_disable_debug_postfix.patch
-- Using source at E:/vs_library/vcpkg/buildtrees/glog/src/v0.4.0-46ccbc49a4.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:141 (message):
    Command failed: E:/vs_library/vcpkg/downloads/tools/cmake-3.17.2-windows/cmake-3.17.2-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v
    Working Directory: E:/vs_library/vcpkg/buildtrees/glog/x64-windows-dbg
    See logs for more information:
      E:\vs_library\vcpkg\buildtrees\glog\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/glog/portfile.cmake:18 (vcpkg_install_cmake)
  scripts/ports.cmake:79 (include)

Error: Building package glog:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: glog:x64-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.
**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by gaqiang** [comment]
[glog.zip](https://github.com/microsoft/vcpkg/files/5212354/glog.zip)

**Comment by alek-d** [comment]
I just tried to build `glog` using freshly installed vcpkg, and it works perfectly.
However I noticed that before compiling `glog` vcpkg installs `gflags`. 
The log you included does not have this step. So it looks like you've had already installed `gflags`.

My suggestion is, that the problem may be related to `gflags` somehow.
Please try to install fresh vcpkg to separate folder, and try to build `glog` again.
If it compiles correctly, maybe try to uninstall `gflags` in you default vcpkg folder and try to rebuild `glog`.


This is how it looks on my computer:

`vcpkg install glog[core]:x64-windows`

Computing installation plan...
... _(tools installation ommited)_
The following packages will be built and installed:
  * **gflags[core]:x64-windows**
    glog[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
A suitable version of powershell-core was not found (required v7.0.3). Downloading portable powershell-core v7.0.3...
Downloading powershell-core...
  https://github.com/PowerShell/PowerShell/releases/download/v7.0.3/PowerShell-7.0.3-win-x86.zip -> C:\source\vcpkg_glog\downloads\PowerShell-7.0.3-win-x86.zip
Extracting powershell-core...
**Starting package 1/2: gflags:x64-windows
Building package gflags[core]:x64-windows...**
Could not locate cached archive: C:\Users\alek\AppData\Local\vcpkg\archives\ee\eef36077134aa47ab37e049c45733d1efe72e470.zip
-- Downloading https://github.com/gflags/gflags/archive/v2.2.2.tar.gz...
-- Extracting source C:/source/vcpkg_glog/downloads/gflags-gflags-v2.2.2.tar.gz
-- Applying patch 0001-patch-dir.patch
-- Applying patch fix_cmake_config.patch
-- Using source at C:/source/vcpkg_glog/buildtrees/gflags/src/v2.2.2-d9283b9285.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: C:/source/vcpkg_glog/packages/gflags_x64-windows/share/gflags/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\alek\AppData\Local\vcpkg\archives\ee\eef36077134aa47ab37e049c45733d1efe72e470.zip
**Building package gflags[core]:x64-windows... done
Installing package gflags[core]:x64-windows...
Installing package gflags[core]:x64-windows... done**
Elapsed time for package gflags:x64-windows: 15.69 s
**Starting package 2/2: glog:x64-windows
Building package glog[core]:x64-windows...**
Could not locate cached archive: C:\Users\alek\AppData\Local\vcpkg\archives\ed\ed4df677a90b6894cec9eab911ac3efa6895a00e.zip
-- Downloading https://github.com/google/glog/archive/v0.4.0.tar.gz...
-- Extracting source C:/source/vcpkg_glog/downloads/google-glog-v0.4.0.tar.gz
-- Applying patch glog_disable_debug_postfix.patch
-- Using source at C:/source/vcpkg_glog/buildtrees/glog/src/v0.4.0-46ccbc49a4.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: C:/source/vcpkg_glog/packages/glog_x64-windows/share/glog/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\alek\AppData\Local\vcpkg\archives\ed\ed4df677a90b6894cec9eab911ac3efa6895a00e.zip
**Building package glog[core]:x64-windows... done
Installing package glog[core]:x64-windows...
Installing package glog[core]:x64-windows... done**
Elapsed time for package glog:x64-windows: 41.92 s

**Comment by JonLiu1993** [comment]
Hi @gaqiang ,Can you try the suggestion of @alek-d ?

**Comment by gaqiang** [comment]
@alek-d @JonLiu1993  Sorry for reply to you so late.I have tried to install the VCPKG in a new folder.But the result does not change and the same problem  happens again.
my cmd lines:
git clone https://github.com/microsoft/vcpkg
cd vcpkg
.\bootstrap-vcpkg.bat
.\vcpkg install glog[core]:x64-windows
[buildtrees.zip](https://github.com/microsoft/vcpkg/files/5249809/buildtrees.zip)
[result.txt](https://github.com/microsoft/vcpkg/files/5249811/result.txt)

**Comment by RatTac** [comment]
Having the same problem, somehow build seems of gflags seems to be broken under windows.

OS: Windows 10
Compiler: Visual Studio 2017 Professional 15.9.19

Output:
`PS D:\Work\vcpkg.git> ./vcpkg install glog
Computing installation plan...
The following packages will be built and installed:
  * gflags[core]:x86-windows -> 2.2.2-1
    glog[core]:x86-windows -> 0.4.0-3
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x86-windows...
Could not locate cached archive: C:\Users\ZOTNOELL\AppData\Local\vcpkg\archives\65\65386e2449be40eb92ea5d0178c6ababb4307197.zip
Could not locate cached archive: C:\Users\ZOTNOELL\AppData\Local\vcpkg\archives\2c\2c015721f4d88e3eb2402e50ed8f92391bd548c0.zip
Starting package 1/2: gflags:x86-windows
Building package gflags[core]:x86-windows...
-- Downloading https://github.com/gflags/gflags/archive/v2.2.2.tar.gz...
-- Extracting source D:/Work/vcpkg.git/downloads/gflags-gflags-v2.2.2.tar.gz
-- Applying patch 0001-patch-dir.patch
-- Applying patch fix_cmake_config.patch
-- Using source at D:/Work/vcpkg.git/buildtrees/gflags/src/v2.2.2-d9283b9285.clean
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Installing: D:/Work/vcpkg.git/packages/gflags_x86-windows/share/gflags/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\ZOTNOELL\AppData\Local\vcpkg\archives\65\65386e2449be40eb92ea5d0178c6ababb4307197.zip
Building package gflags[core]:x86-windows... done
Installing package gflags[core]:x86-windows...
Installing package gflags[core]:x86-windows... done
Elapsed time for package gflags:x86-windows: 11.52 s
Starting package 2/2: glog:x86-windows
Building package glog[core]:x86-windows...
-- Using cached D:/Work/vcpkg.git/downloads/google-glog-v0.4.0.tar.gz
-- Cleaning sources at D:/Work/vcpkg.git/buildtrees/glog/src/v0.4.0-46ccbc49a4.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/Work/vcpkg.git/downloads/google-glog-v0.4.0.tar.gz
-- Applying patch glog_disable_debug_postfix.patch
-- Using source at D:/Work/vcpkg.git/buildtrees/glog/src/v0.4.0-46ccbc49a4.clean
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:108 (message):
    Command failed: ninja -v
    Working Directory: D:/Work/vcpkg.git/buildtrees/glog/x86-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\Work\vcpkg.git\buildtrees\glog\config-x86-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:319 (vcpkg_execute_required_process)
  ports/glog/portfile.cmake:11 (vcpkg_configure_cmake)
  scripts/ports.cmake:136 (include)


Error: Building package glog:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: glog:x86-windows
  Vcpkg version: 2020.11.12-nohash

Additionally, attach any relevant sections from the log files above.`

**Comment by JonLiu1993** [comment]
@gaqiang ,Does this problem still exist?

**Comment by JonLiu1993** [comment]
Thanks for posting this issue. Please reopen this issue if it still be a problem for you.
