### ISSUE TITLE
[cppcoro] Missing system library when linking

### ISSUE THREAD

**Issue by Chlorie** [microsoft/vcpkg#13496]
****

**Is your feature request related to a problem? Please describe.**
`cppcoro` itself builds fine in vcpkg. After specifying to link against this library, most fundamental features of this library are usable, but when using some of the synchronization primitives there're unresolved symbol errors output by the linker. Apparently `cppcoro` uses Win32 API for some of its functions (like `schedule_after`) on Windows, but the target itself doesn't link to those libraries. After manually adding linking options to several system libraries like `synchronization.lib` the user code builds fine, but I think it should not be the case that I have to manually link against those libraries.

**Proposed solution**
The cmake target of cppcoro should propagate those system libraries to consumers of the library.

**Comment by NancyLi1013** [comment]
Hi @Chlorie 
Thanks for post this issue.
I try to use the function `schedule_after` to build in cmake project and there are no any errors.

So could you please provide your project case and post the error info that you met?

My project like this:

main.cpp

```
#include <cppcoro/task.hpp>
#include <cppcoro/io_service.hpp>
#include <cppcoro/sync_wait.hpp>
#include <cppcoro/when_all.hpp>
#include <chrono>

cppcoro::task<> sleep_some(cppcoro::io_service& service)
{
  using namespace std::chrono_literals;
  co_await service.schedule_after(1s);
}

cppcoro::task<> do_thing(cppcoro::io_service& service)
{
  co_await sleep_some(service);
  co_await sleep_some(service);
}

int main()
{
  cppcoro::io_service service;
  std::thread ioThread{ [&] { service.process_events(); } };
  cppcoro::sync_wait(do_thing(service));
  service.stop();
  ioThread.join();
  return 0;
}
```
CMakeLists.txt

```
cmake_minimum_required (VERSION 3.8)
set(CMAKE_CXX_STANDARD 17) 
find_package(cppcoro CONFIG REQUIRED)
add_executable (test "main.cpp")
target_link_libraries(test PRIVATE cppcoro)
```

**Comment by Chlorie** [comment]
Oh sorry I didn't recall it correctly, my fault.
My CMake projects using `cppcoro` was building correctly. It was an MSBuild project that uses `cppcoro` which reported linking error, saying that some symbols like WSAStartup were missing. Apparently it didn't pull in the required `Ws2_32.lib`.
Sorry for the misinformation...

**Comment by NancyLi1013** [comment]
Thanks for your above details. Currently, there is no` ws2_32.lib` in vcpkg. We need to add it into system library. Please see #9840.
`synchronization.lib `is the same case with `ws2_32.lib`.

So we need to add the link manually to solve this issue in MSBuild project. 

Let's track this issue in #9840. I'm closing this issue for now.
