### ISSUE TITLE
How do I install harfbuzz/freetype/... DLLs along with my executable

### ISSUE THREAD

**Issue by christianparpart** [microsoft/vcpkg#13506]
Hi,

I tried searching all around the net. There are quite some examples on how to install Qt5 libraries into your build target directory as POST_BUILD action. That went well.

Interestingly {harfbuzz,freetype,libpng}.dll and many(!) others got automatically copied right next to be created .exe file. I had to do that manually for Qt (why?)

I also found documentation on how to install Qt DLLs using cmake install target.
However, I did not find a single documentation on how to run the cmake install target and get all these other dependencies (that got auto-copied to my own .exe file in the build tree) to copied to my desired install prefix. I'd prefer not to hard-code that. What's the trick? :) 

Many thanks in advance,
Christian.

**Comment by mathisloge** [comment]
I'm using usually a cmake macro: 
```
# This is a helper script to run BundleUtilities fixup_bundle as postbuild
# for a target. The primary use case is to copy .DLLs to the build directory for
# the Windows platform. It allows generator expressions to be used to determine
# the binary location
#
# Usage : copy_dlls_for_debug TARGET LIBS DIRS
# - TARGET : A cmake target
# - See fixup_bundle for LIBS and DIRS arguments

if(RUN_IT)
# Script ran by the add_custom_command
	include(BundleUtilities)
	include(InstallRequiredSystemLibraries)
	fixup_bundle("${TO_FIXUP_FILE}" "${TO_FIXUP_LIBS}" "${TO_FIXUP_DIRS}")
# End of script ran by the add_custom_command
else()

set(THIS_FILE ${CMAKE_CURRENT_LIST_FILE})
function(copy_dlls_for_debug _targets _libs _dirs)
	if(WIN32)
		foreach(_target ${_targets})
			add_custom_command(
				TARGET ${_target} POST_BUILD
				COMMAND ${CMAKE_COMMAND} -DRUN_IT:BOOL=ON -DTO_FIXUP_FILE=$<TARGET_FILE:${_target}> -DTO_FIXUP_LIBS=${_libs} -DTO_FIXUP_DIRS=${_dirs} -P ${THIS_FILE}
				COMMENT "Fixing up dependencies for ${_target}"
				VERBATIM
			)
		endforeach()
	endif(WIN32)
endfunction()

endif()

```

and call it with each executable like: 
```
    include(CopyDllsForDebug)
    # copy other targets on which the target depends
    add_custom_command(TARGET mytarget POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy "$<TARGET_FILE:othertarget>" ${CMAKE_CURRENT_BINARY_DIR})
    copy_dlls_for_debug(mytarget  \"\" \"${ADDITIONAL_LIBARIES_PATHS}\")
```

where `${ADDITIONAL_LIBARIES_PATHS}` points to directories like the vcpkg dir.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. This issue hasn’t been updated for a long time. Please reopen this issue if this is still a problem for you.
