### ISSUE TITLE
vcpkg integrate install doesn't work

### ISSUE THREAD

**Issue by Toninoso** [microsoft/vcpkg#13503]
**Describe the bug**
The command "vcpkg integrate install" doesn't seem to do anything, even if it reports success.

**Environment**
- OS: Windows 10 1709
- Compiler: Microsoft Visual Studio Enterprise 2019 Version 16.7.3
Visual C++ 2019   00435-60000-00000-AA401
Using v140 toolset in 2019
Vcpkg package management program version 2020.06.15-nohash

**To Reproduce**
1. install vcpkg package
2. ./vcpkg integrate install
3. Build the project that has dependency on installed vcpkg project. Include and Lib paths don't get resolved. Looking for related variables/macros of the form $vcpkg... none can be found in VS,  except for $VcpkgRoot.

**Expected behavior**
Projects don't fail looking for include and lib dependencies built with vcpkg
**Failure logs**
Standard "fatal error C1083: Cannot open include file:... " 
and unresolved externals for linker

**Additional context**
I have both VS 2017 and VS 2019 installed. Using only VS 2019 IDE but VS 2015 (v140) toolset for all the projects.
I noticed that VS 2017 has all the $vcpkg... macros available while VS 2019 doesn't. Unable to figure out how to make "vcpkg integrate install" target a specific VS version I decided to uninstall VS 2017. After VS 2017 uninstall run "vcpkg integrate install" again, hoping that it will affect now the only installed version, VS 2019 one, but it didn't, even if it keeps saying :

> Applied user-wide integration for this vcpkg root.
> 
> All MSBuild C++ projects can now #include any installed libraries.
> Linking will be handled automatically.
> Installing new libraries will make them instantly available.

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Did you run command `./vcpkg integrate project`?

**Comment by Toninoso** [comment]
I tried it, following your suggestion and it worked for me. 
Thanks!

Since I am working in a group of developers I am not sure what would be the best approach. 

Some developers have no issues with `./vcpkg integrate install`,  some, like me, do. We are sharing solution and project files in Git so we would all like to be on the same page.

Frankly, I don't find the option of a dummy nuget package, just to point to vcpkg installed package folder, very attractive.

**Comment by LilyWangL** [comment]
`./vcpkg integrate install`  is often used in cmake projects, and `./vcpkg integrate project` is often used in MSVC projects. You can run these two commands on vcpkg at the same time, there is no conflict between them.

**Comment by LilyWangL** [comment]
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.

**Comment by Herobrinemen** [comment]
idk Why But When i Run The Code It is Not Work
----------------------------------------------------------
./vcpkg : The term './vcpkg' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ ./vcpkg integrate install
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (./vcpkg:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by jleaders** [comment]
@Herobrinemen you can try `vcpkg integrate install` (assuming vcpkg is installed, AND it is in your path)

**Comment by dg0yt** [comment]
@jleaders @Herobrinemen `./vcpkg` is POSIX syntax for running a program in the current working directory. The error message you reported indicates a Windows Powershell environment. Windows uses backlslash: `.\vcpkg`

But let this old issue be silent now.
