### ISSUE TITLE
[libjpeg-turbo] Building package libjpeg-turbo:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by sabason** [microsoft/vcpkg#13509]
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libjpeg-turbo:x86-windows
  Vcpkg version: 2020.06.15-nohash

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Could you please provide the eror log?

**Comment by LilyWangL** [comment]
Pinging @sabason for response.

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
