### ISSUE TITLE
How to use VCPKG_BUILD_TYPE to avoid installing both debug and release package?

### ISSUE THREAD

**Issue by ThomsonTan** [microsoft/vcpkg#13513]
Seems VCPKG provides an environment variable `VCPKG_BUILD_TYPE` which could be used to install either debug or release package, but not both, like mentioned in #143. How do use this variable? Do I need create some customized triplet file to specify this? I’d expect a simple variable like cmake variable I could pass via command line, such as `vcpkg install somepackage -DVCPKG_BUILD_TYPE=release`.

**Comment by Hoikas** [comment]
While I suspect it is possible to pass a potentially undocumented or debug command line switch to do this, the least error prone method to accomplish this would be to append this to the bottom of your triplet:
```cmake
set(VCPKG_BUILF_TYPE "release")
```

**Comment by ThomsonTan** [comment]
Thanks @Hoikas. Sorry for my novice, what does it mean for appending `set(VCPKG_BUILD_TYPE "release")` to my triplet file? I don't have customized triplet file and I pass triplet via command line such as `vcpkg install protobuf:x64-windows`, is it required and how could I create a triplet file for this?

**Comment by PhoebeHui** [comment]
@ThomsonTan, you can reference https://github.com/microsoft/vcpkg/issues/10683#issuecomment-663508284 and create a customized under ..\triplets\community.

**Comment by PhoebeHui** [comment]
@ThomsonTan, please reopen this issue if it still be a problem for you.

**Comment by dg0yt** [comment]
Alternative to a command line parameter, an environment variable would help, too.
