### ISSUE TITLE
[SDL2] SDL2 leaks exports when building static library

### ISSUE THREAD

**Issue by IntelOrca** [Microsoft/vcpkg#1351]
When SDL2 is built as a static library, all the SDL2 functions are declared with `__declspec(dllexport)`. This means that they show up as exported functions in consumer binaries.

If SDL2 has no mechanism for preventing this, then `DECLSPEC` can be defined to blank.

**Comment by jasjuang** [comment]
If you build SDL2 from source into a static library. Does this error occur?

**Comment by IntelOrca** [comment]
I believe so. Previously we have just had to patch the source code:
https://github.com/OpenRCT2/Dependencies/blob/master/patches/sdl.diff:include/begin_code.h

This was when the SDL2 msbuild projects did not have a static configuration at all.

**Comment by KindDragon** [comment]
Plese report this bug to SDL2 project https://bugzilla.libsdl.org/

**Comment by IntelOrca** [comment]
It was raised in 2013 and still hasn't been fixed.
https://bugzilla.libsdl.org/show_bug.cgi?id=2026
