### ISSUE TITLE
[fmt] build failure

### ISSUE THREAD

**Issue by Adobe-Android** [microsoft/vcpkg#13525]
**Host Environment**
- OS: Windows 10 x64
- Compiler: VS 2019 Community Preview - 16.8.0 Preview 2.1

**To Reproduce**
`./vcpkg install fmt`

**Failure logs** 
Computing installation plan...
The following packages will be built and installed:
    fmt[core]:x86-windows
Detecting compiler hash for triplet x86-windows...
Starting package 1/1: fmt:x86-windows
Building package fmt[core]:x86-windows...
Could not locate cached archive: C:\Users\tngam\AppData\Local\vcpkg\archives\b4\b43514205308fac3b4f307da0d5beb7fc34db89a.zip
-- Using cached C:/Users/tngam/source/repos/C++/vcpkg-2020.07/downloads/fmtlib-fmt-19bd751020a1f3c3363b2eb67a039852f139a8d3.tar.gz
-- Cleaning sources at C:/Users/tngam/source/repos/C++/vcpkg-2020.07/buildtrees/fmt/src/52f139a8d3-70a26f0c4b.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/tngam/source/repos/C++/vcpkg-2020.07/downloads/fmtlib-fmt-19bd751020a1f3c3363b2eb67a039852f139a8d3.tar.gz
-- Applying patch fix-warning4189.patch
-- Using source at C:/Users/tngam/source/repos/C++/vcpkg-2020.07/buildtrees/fmt/src/52f139a8d3-70a26f0c4b.clean
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Installing: C:/Users/tngam/source/repos/C++/vcpkg-2020.07/packages/fmt_x86-windows/share/fmt/copyright
-- Fixing pkgconfig
CMake Error at scripts/cmake/vcpkg_fixup_pkgconfig.cmake:270 (list):
  list sub-command FILTER, mode REGEX failed to compile regex
  "C:/Users/tngam/source/repos/C++/vcpkg-2020.07/packages/fmt_x86-windows/debug/".
Call Stack (most recent call first):
  ports/fmt/portfile.cmake:44 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:79 (include)

RegularExpression::compile(): Nested *?+.
RegularExpression::compile(): Error in compile.
Error: Building package fmt:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: fmt:x86-windows
  Vcpkg version: 2020.06.15-nohash

**Additional context**
.\vcpkg update
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.
PS C:\Users\tngam\source\repos\C++\vcpkg-2020.07> git pull
fatal: not a git repository (or any of the parent directories): .git
This error makes sense because I'm using a release rather than pulling from a git branch. I did both anyway to show here.

**Comment by sfhacker** [comment]
There are some (open) reported issues about fmt package.

![image](https://user-images.githubusercontent.com/25817529/93098780-96bd7400-f6ea-11ea-8433-a8772d2cb3bd.png)

**Comment by Neumann-A** [comment]
`C:/Users/tngam/source/repos/C++/vcpkg-2020.07/packages/fmt_x86-windows/share/fmt/copyright`

the problem are the regex characters `++` and `.` in the path

**Comment by sfhacker** [comment]
Most of our users do not know how to setup their own environment! That causes a lot of wasted time!
Can we provide a wiki or some sort of documentation to reduce the ignorance or lack of experience?

**Comment by Adobe-Android** [comment]
Shows my ignorance. I thought the only setup was the few items in the Readme.

**Comment by Adobe-Android** [comment]
Thanks for your help @Neumann-A
