### ISSUE TITLE
libmagic build failure

### ISSUE THREAD

**Issue by stephanecharette** [microsoft/vcpkg#13528]
**Host Environment**
- OS: Windows 10 (64-bit)
- Compiler: Visual Studio 2019 v16.7.2

**To Reproduce**
`vcpkg.exe install libmagic --triplet x64-windows`

**Failure logs** 
```-- Using source at C:/src/vcpkg/buildtrees/libmagic/src/9852e25398-4363addce8.clean
-- Using msys root at C:/src/vcpkg/downloads/tools/msys2/77f3fd5f29257d6b
CMake Error at scripts/cmake/vcpkg_configure_make.cmake:407 (message):
  libmagic requires autoconf from the system package manager (example: "sudo apt-get install autoconf")
Call Stack (most recent call first):
  ports/libmagic/portfile.cmake:9 (vcpkg_configure_make)
  scripts/ports.cmake:79 (include)
Error: Building package libmagic:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libmagic:x64-windows
  Vcpkg version: 2020.06.15-nohash
```

I'm a bit confused.  Is this telling me that I need to manually install autoconf for Windows first before I can use vcpkg?  Or is this a legitimate broken package?  Shouldn't vcpkg do this automatically, like msys or various other required tools?

**Comment by sfhacker** [comment]
We use MSYS/MinGW environments and autoconf comes with them. There is no need to install autoconf at all. I'll have a go at building libmagic now.

![image](https://user-images.githubusercontent.com/25817529/93126516-c92d9800-f70f-11ea-9619-deb10c2071f6.png)

**Comment by stephanecharette** [comment]
I'm not sure I follow you.  Are you saying that this _should_ work?  I'm using the latest version:

```C:\src\vcpkg>git pull
Already up to date.

C:\src\vcpkg>git log -1
commit 76362dd2b2e4d9b03f6722219c8a1189e3a255fa (HEAD -> master, origin/master, origin/HEAD)
Author: Agustin Mendez <menduz@protonmail.com>
Date:   Sun Sep 13 23:06:16 2020 -0300```

Here is the full list of messages I'm seeing:

```C:\src\vcpkg>vcpkg.exe install libmagic --triplet x64-windows
Computing installation plan...
The following packages will be built and installed:
    libmagic[core]:x64-windows
Detecting compiler hash for triplet x64-windows...
Starting package 1/1: libmagic:x64-windows
Building package libmagic[core]:x64-windows...
Could not locate cached archive: C:\Users\stephane\AppData\Local\vcpkg/archives\3d\3dac1f5ce5955aa273a0ac578d1a5d512caa09ab.zip
-- Using cached C:/src/vcpkg/downloads/file-file-a0d5b0e4e9f97d74a9911e95cedd579852e25398.tar.gz
-- Cleaning sources at C:/src/vcpkg/buildtrees/libmagic/src/9852e25398-4363addce8.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/src/vcpkg/downloads/file-file-a0d5b0e4e9f97d74a9911e95cedd579852e25398.tar.gz
-- Using source at C:/src/vcpkg/buildtrees/libmagic/src/9852e25398-4363addce8.clean
-- Using msys root at C:/src/vcpkg/downloads/tools/msys2/77f3fd5f29257d6b
CMake Error at scripts/cmake/vcpkg_configure_make.cmake:407 (message):
  libmagic requires autoconf from the system package manager (example: "sudo
  apt-get install autoconf")
Call Stack (most recent call first):
  ports/libmagic/portfile.cmake:9 (vcpkg_configure_make)
  scripts/ports.cmake:79 (include)
Error: Building package libmagic:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libmagic:x64-windows
  Vcpkg version: 2020.06.15-nohash
Additionally, attach any relevant sections from the log files above.
```

I ran into a problem with CUDA and OpenCV4 last night prior to this.  Build crashed halfway through because of insufficient disk space.  Cleaned out some files and restarted things and it did finish correctly.  But I'm wondering if that left something in a weird state.  Running "vcpkg.exe list" does show me I have OpenCV4 and a bunch of other things installed (zlib, pthreads, ffmpeg, ...), so I thought that things were OK until I ran into this problem with libmagic.

**Comment by sfhacker** [comment]
libmagic is quite a small project! It took me two mins to build it from source without installing anything.

![image](https://user-images.githubusercontent.com/25817529/93133026-ecf5db80-f719-11ea-8e39-4132af699c0a.png)

What I meant in my previous post was that autotools (in general) should be already installed and available.
Secondly, when I built libmagic from source it didn't use/need/ask for autoconf. So ..... I'm confused as well.

**Comment by stephanecharette** [comment]
> libmagic is quite a small project! It took me two mins to build it from source without installing anything.

So...`vcpkg.exe install libmagic --triplet x64-windows`?  Or did you install it a different way?  I just need to know if I'm doing it wrong.  Is this the correct command to install it using vcpkg?  Or is there a better way I should be using vcpkg?

**Comment by StarGate-One** [comment]
@stephanecharette I am just a volunteer project contributor, not an expert by all means, but looking at the what has been posted your syntax to install libmagic is correct.

From my understanding, it appears there is an issue with the [vcpkg-root]\ports\libmagic\portfile.cmake in that it is not running the `vcpkg_acquire_msys(autoconf)` function before trying to use it... but I am not exactly sure how to make the change required, so I will leave this up to one of the Microsoft project members will need to take a look.

**Comment by stephanecharette** [comment]
Curious to know if there is something I can run or modify manually to get this to install correctly.  Anyone know?

**Comment by JackBoosY** [comment]
Duplicate to #11832, please wait for fix this issue.
