### ISSUE TITLE
VCPkg doesn't support granular selection of MSVC PlatformToolset

### ISSUE THREAD

**Issue by mschofie** [microsoft/vcpkg#13531]
VCPkg allows selecting a 'Platform Toolset' using the VCPKG_PLATFORM_TOOLSET variable in a toolchain file, but only allows three digits of precision to be specified (e.g. v140, v141 or v142), but Visual Studio ships with more detailed versions (e.g. 14.16.27023, 14.24.28314, 14.26.28801, 14.27.29110). Being able to 'pin' to a more specific Platform Toolset version would help work-around bugs or changes in the toolset, and support a more deterministic build.

****

**Is your feature request related to a problem? Please describe.**
VCPkg will prepare a 'vcvars.bat'-like environment for the cmake build to run in so that Generators that don't know how to find the VS tooling (i.e. Ninja) have an environment already prepared. But when multiple platform toolset versions exists for a given `14x` value, only the latest can be used. On my machine I have 14.24.28314, 14.26.28801, 14.27.29110, and VCPkg will only use 14.27.29110 - there isn't a way to select, say, 14.26.28801. This affects my team in the roll-out of 14.27. We build a set of packages and store them in a Universal Package. But when the Microsoft Hosted Agent was updated to 14.27, then consumers building with 14.26 would see build breaks - libprotobuf.lib built with 14.27 appears to have a dependency on `__imp___std_init_once_begin_initialize` that 14.26 doesn't have. Being able to pin VCPkg to build with 14.26 would remove the environmental non-determinism.

**Proposed solution**
The VCPKG_PLATFORM_TOOLSET should accommodate values that provide more precision. There's precedent for this, the vcvars.bat parameter `-vcvars_ver=[vc_version]` accommodates multiple levels of precision: 

```
[vc_version] : {none} for latest installed VC++ compiler toolset |
               "14.0" for VC++ 2015 Compiler Toolset |
               "14.xx" for the latest 14.xx.yyyyy toolset installed (e.g. "14.11") |
               "14.xx.yyyyy" for a specific full version number (e.g. "14.11.25503")
```

(taken from `.\vcvarsall.bat -?` output).

**Describe alternatives you've considered**
As an alternative, a triplet file could specify it's own `VCPKG_CHAINLOAD_TOOLCHAIN_FILE` - which disables the code-path in VCPkg to prepare the platform toolset environment - but that means that a custom toolchain file has to do *a lot* of heavy lifting.

**Additional context**

**Comment by ras0219-msft** [comment]
This is definitely a feature we should have and I agree with your suggested implementation.

Glad to hear how you've used vcpkg with universal packages -- we'd love to know more about your specific workflow at vcpkg@microsoft.com if you'd like to share :)

**Comment by NancyLi1013** [comment]
Duplicated to #11317.
