### ISSUE TITLE
Manifests, problem with parallel builds

### ISSUE THREAD

**Issue by sipsorcery** [microsoft/vcpkg#13530]
I've tried out the new [manifests](https://github.com/microsoft/vcpkg/blob/master/docs/specifications/manifests.md) feature with an existing multi-project solution that has been successfully using `vcpkg` for CI. The `vcpkg.json` and msbuild configuration to build and install the dependencies worked properly but there's a problem with parallel builds.

When building in Visual Studio or on the command line with `msbuild /m` there are numerous `vcpkg` step failures. From the logs below it seem there are multiple instances of the command attempting to lock ` C:\Tools\vcpkg-btc\.vcpkg-root`. Build on the command line without the `/m` option removes this error.

```
  22>VcpkgInstallManifestDependencies:
         Failed to take the filesystem lock on C:\Tools\vcpkg-btc\.vcpkg-root:
             The requested resource is in use.
    22>c:\Tools\vcpkg-btc\scripts\buildsystems\msbuild\vcpkg.targets(102,5): error MSB3073: The command ""c:\Tools\vcpkg-btc\v
       cpkg.exe" install --triplet "x64-windows-static" --vcpkg-root "c:\Tools\vcpkg-btc\\" "--x-manifest-root=c:\Dev\github\s
       ipsorcery_bitcoin\build_msvc\\" "--x-install-root=c:\Dev\github\sipsorcery_bitcoin\build_msvc\vcpkg_installed\\" --bina
       rycaching" exited with code 1. [c:\Dev\github\sipsorcery_bitcoin\build_msvc\libbitcoin_qt\libbitcoin_qt.vcxproj]
    22>Done Building Project "c:\Dev\github\sipsorcery_bitcoin\build_msvc\libbitcoin_qt\libbitcoin_qt.vcxproj" (default target
       s) -- FAILED.
    12>c:\Tools\vcpkg-btc\scripts\buildsystems\msbuild\vcpkg.targets(102,5): error MSB3073: The command ""c:\Tools\vcpkg-btc\v
       cpkg.exe" install --triplet "x64-windows-static" --vcpkg-root "c:\Tools\vcpkg-btc\\" "--x-manifest-root=c:\Dev\github\s
       ipsorcery_bitcoin\build_msvc\\" "--x-install-root=c:\Dev\github\sipsorcery_bitcoin\build_msvc\vcpkg_installed\\" --bina
       rycaching" exited with code 1. [c:\Dev\github\sipsorcery_bitcoin\build_msvc\libbitcoin_zmq\libbitcoin_zmq.vcxproj]
    12>Done Building Project "c:\Dev\github\sipsorcery_bitcoin\build_msvc\libbitcoin_zmq\libbitcoin_zmq.vcxproj" (default targ
       ets) -- FAILED.
```

**Comment by ras0219-msft** [comment]
Thanks for the issue report!

As a workaround, you can set the MSBuild property `VcpkgManifestInstall`[1] to false in your project (or on the command line via an environment variable or `/p:VcpkgManifestInstall=false`) and manually pre-install dependencies.

[1] https://github.com/microsoft/vcpkg/blob/f1bef4aa7ca7e2a6ea4f5dfe4850d95fce60b431/scripts/buildsystems/msbuild/vcpkg.props#L31
