### ISSUE TITLE
vcpkg_copy_pdbs() does not copy PDB files for static libraries

### ISSUE THREAD

**Issue by alek-d** [microsoft/vcpkg#13548]
****

**Is your feature request related to a problem? Please describe.**
After I added static linking to Scintialla port, I noticed that PDB file is not copied alongside LIB file, like it is with DLL file in case of dynamic linkage.

**Proposed solution**
`vcpkg_copy_pdbs.cmake` uses `dumpbin` to find the path to PDB file for the specified DLL, but this method doesn't work for LIB files.

In case of static libraries, `vcpkg_copy_pdbs.cmake` should try to find PDB file with the same name as the library, and copy it alongside LIB file.

**Additional context**
I'm not sure if this will work for all libraries, but I think that we can assume that the pattern `lib_name.lib` -> `lib_name.pdb` in the same directory, is the most common.

**Comment by PhoebeHui** [comment]
Related to https://github.com/microsoft/vcpkg/issues/10564

**Comment by alek-d** [comment]
@PhoebeHui I only briefly checked, and I'm not 100% sure, but it looks to me that in #10564 generating PDBs is not set in compilation settings. So, probably, there is nothing to copy there.

**Comment by NancyLi1013** [comment]
Considering the discussion in #13721, there is no need to copy PDB files for static libraries. So I think this issue can be closed now.
