### ISSUE TITLE
libpq build failure

### ISSUE THREAD

**Issue by michealowen** [microsoft/vcpkg#13542]
**Host Environment**
- OS: windows10-x64
- Compiler: 19.25.28614 for x86

**To Reproduce**
`./vcpkg install libpq`

**Failure logs** 
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: F:/owen/cpp_workspace/vcpkg/vcpkg-master/downloads/tools/perl/perl/bin/perl.exe build.pl RELEASE libpq
    Working Directory: F:/owen/cpp_workspace/vcpkg/vcpkg-master/buildtrees/libpq/x86-windows-rel/src/tools/msvc
    Error code: 53
    See logs for more information:
      F:\owen\cpp_workspace\vcpkg\vcpkg-master\buildtrees\libpq\build-libpq-x86-windows-RELEASE-out.log
      F:\owen\cpp_workspace\vcpkg\vcpkg-master\buildtrees\libpq\build-libpq-x86-windows-RELEASE-err.log

Call Stack (most recent call first):
  ports/libpq/portfile.cmake:214 (vcpkg_execute_required_process)
  scripts/ports.cmake:76 (include)

**Additional context**
in build-libpq-x86-windows-RELEASE-err.log I found this
Unable to determine OpenSSL version: The openssl.exe command wasn't found. at F:\owen\cpp_workspace\vcpkg\vcpkg-master\buildtrees\libpq\x86-windows-rel\src\tools\msvc/Mkvcbuild.pm line 147.

**Comment by JackBoosY** [comment]
Please make sure `openssl.exe` exists in _VCPKG_ROOT/installed/x86-windows/tools/openssl_.

**Comment by michealowen** [comment]
I'm sure openssl.exe exists in VCPKG_ROOT/installed/x86-windows/tools/openssl.

**Comment by JackBoosY** [comment]
@michealowen Can you provide me the configure logs in _F:\owen\cpp_workspace\vcpkg\vcpkg-master\buildtrees\libpq_ begin with `config-` ? 

Thanks.

**Comment by michealowen** [comment]
> @michealowen Can you provide me the configure logs in _F:\owen\cpp_workspace\vcpkg\vcpkg-master\buildtrees\libpq_ begin with `config-` ?
> 
> Thanks.
I can see any logs begin with config- in F:\owen\cpp_workspace\vcpkg\vcpkg-master\buildtrees\libpq

**Comment by michealowen** [comment]
> @michealowen Can you provide me the configure logs in _F:\owen\cpp_workspace\vcpkg\vcpkg-master\buildtrees\libpq_ begin with `config-` ?
> 
> Thanks.

build-libpq-x86-windows-RELEASE-err.log  patch-x86-windows-4-out.log
build-libpq-x86-windows-RELEASE-out.log  patch-x86-windows-5-err.log
extract-err.log                          patch-x86-windows-5-out.log
extract-out.log                          patch-x86-windows-6-err.log
patch-x86-windows-0-err.log              patch-x86-windows-6-out.log
patch-x86-windows-0-out.log              patch-x86-windows-7-err.log
patch-x86-windows-1-err.log              patch-x86-windows-7-out.log
patch-x86-windows-1-out.log              patch-x86-windows-8-err.log
patch-x86-windows-2-err.log              patch-x86-windows-8-out.log
patch-x86-windows-2-out.log              src
patch-x86-windows-3-err.log              stdout-x86-windows.log
patch-x86-windows-3-out.log              x86-windows.vcpkg_abi_info.txt
patch-x86-windows-4-err.log              x86-windows-rel

in F:\owen\cpp_workspace\vcpkg\vcpkg-master\buildtrees\libpq，I can find these files.

**Comment by JackBoosY** [comment]
@michealowen could you upload them here?

**Comment by michealowen** [comment]
> @michealowen could you upload them here?

ok.
build-libpq-x86-windows-RELEASE-err.log patch-x86-windows-4-out.log
`cl output Microsoft (R) C/C++ Optimizing Compiler Version 19.25.28614 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

usage: cl [ option... ] filename... [ /link linkoption... ]
.Detected hardware platform: Win32`

patch-x86-windows-0-out.log patch-x86-windows-7-err.log
`Unable to determine OpenSSL version: The openssl.exe command wasn't found. at F:\owen\cpp_workspace\vcpkg\vcpkg-master\buildtrees\libpq\x86-windows-rel\src\tools\msvc/Mkvcbuild.pm line 147.
`
extract-err.log patch-x86-windows-5-out.log is empty
extract-out.log patch-x86-windows-6-err.log is empty
patch-x86-windows-0-out is empty

patch-x86-windows-0-err
`Checking patch src/tools/msvc/Solution.pm...
Hunk #1 succeeded at 657 (offset 7 lines).
Hunk #2 succeeded at 668 (offset 7 lines).
Hunk #3 succeeded at 677 (offset 7 lines).
Hunk #4 succeeded at 705 (offset 7 lines).
Hunk #5 succeeded at 722 (offset 7 lines).
Applied patch src/tools/msvc/Solution.pm cleanly.
`

**Comment by JackBoosY** [comment]
This issue duplicated with #12443, please track that issue.

Thanks.

**Comment by michealowen** [comment]
> This issue duplicated with #12443, please track that issue.
> 
> Thanks.

ok, thanks.
