### ISSUE TITLE
[openssl-windows[core]:x64-windows] build failure

### ISSUE THREAD

**Issue by 647LiuSQ** [microsoft/vcpkg#13555]
**Host Environment**
- OS: Windows 10
- Compiler: Visual Studio 2019

**To Reproduce**
`./vcpkg install openssl-windows:x64-windows`

**Failure logs** 
PS C:\src\vcpkg-master> ./vcpkg install openssl-windows:x64-windows
Computing installation plan...
The following packages will be built and installed:
    openssl-windows[core]:x64-windows
Detecting compiler hash for triplet x64-windows...
Starting package 1/1: openssl-windows:x64-windows
Building package openssl-windows[core]:x64-windows...
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg/archives\bf\bffe8bd3bcc9c7002577b8b804731f97070a42a6.zip
-- Using cached C:/src/vcpkg-master/downloads/openssl-1.1.1g.tar.gz
-- Cleaning sources at C:/src/vcpkg-master/buildtrees/openssl-windows/src/openssl-1-bb2a9a5801.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/src/vcpkg-master/downloads/openssl-1.1.1g.tar.gz
-- Using source at C:/src/vcpkg-master/buildtrees/openssl-windows/src/openssl-1-bb2a9a5801.clean
-- Copying openssl release source files...
-- Copying openssl release source files... done
-- Configure x64-windows-rel
-- Configure x64-windows-rel done
-- Build x64-windows-rel
-- Build x64-windows-rel done
-- Copying openssl debug source files...
-- Copying openssl debug source files... done
-- Configure x64-windows-dbg
-- Configure x64-windows-dbg done
-- Build x64-windows-dbg
-- Build x64-windows-dbg done
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:85 (message):
    Command failed: C:/src/vcpkg-master/downloads/tools/powershell-core-7.0.3-windows/powershell.exe -noprofile -executionpolicy Bypass -nologo -file C:/src/vcpkg-master/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary C:/src/vcpkg-master/packages/openssl-windows_x64-windows/tools/openssl/openssl.exe -installedDir C:/src/vcpkg-master/packages/openssl-windows_x64-windows/bin
    Working Directory: C:/src/vcpkg-master
    Error code: -2146232797
    See logs for more information:
      C:\src\vcpkg-master\buildtrees\openssl-windows\copy-tool-dependencies-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_copy_tool_dependencies.cmake:27 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_copy_tool_dependencies.cmake:37 (search_for_dependencies)
  ports/openssl-windows/portfile.cmake:169 (vcpkg_copy_tool_dependencies)
  scripts/ports.cmake:79 (include)

Error: Building package openssl-windows:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openssl-windows:x64-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.

[copy-tool-dependencies-err.log](https://github.com/microsoft/vcpkg/files/5229316/copy-tool-dependencies-err.log)

**Comment by 647LiuSQ** [comment]
I tried .\vcpkg update.
It printed the following:
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/12849.
