### ISSUE TITLE
[bzip2:x64-linux] build failure

### ISSUE THREAD

**Issue by ustchqf** [microsoft/vcpkg#13561]
**Host Environment**
- OS: linux(centos 6.7)
- Compiler: gcc 7.3

**To Reproduce**
`./vcpkg install boost`

**Failure logs** 
The following packages will be built and installed:
    boost[core]:x64-linux
  * boost-accumulators[core]:x64-linux
  * boost-align[core]:x64-linux
  * boost-asio[core]:x64-linux
  * boost-assign[core]:x64-linux
  * boost-beast[core]:x64-linux
  * boost-bimap[core]:x64-linux
  * boost-callable-traits[core]:x64-linux
  * boost-compute[core]:x64-linux
  * boost-context[core]:x64-linux
  * boost-contract[core]:x64-linux
  * boost-convert[core]:x64-linux
  * boost-coroutine[core]:x64-linux
  * boost-coroutine2[core]:x64-linux
  * boost-crc[core]:x64-linux
  * boost-date-time[core]:x64-linux
  * boost-dll[core]:x64-linux
  * boost-dynamic-bitset[core]:x64-linux
  * boost-fiber[core]:x64-linux
  * boost-flyweight[core]:x64-linux
  * boost-geometry[core]:x64-linux
  * boost-gil[core]:x64-linux
  * boost-graph[core]:x64-linux
  * boost-graph-parallel[core]:x64-linux
  * boost-hana[core]:x64-linux
  * boost-heap[core]:x64-linux
  * boost-histogram[core]:x64-linux
  * boost-hof[core]:x64-linux
  * boost-icl[core]:x64-linux
  * boost-interprocess[core]:x64-linux
  * boost-iostreams[core]:x64-linux
  * boost-local-function[core]:x64-linux
  * boost-locale[core]:x64-linux
  * boost-lockfree[core]:x64-linux
  * boost-log[core]:x64-linux
  * boost-metaparse[core]:x64-linux
  * boost-msm[core]:x64-linux
  * boost-multi-array[core]:x64-linux
  * boost-multi-index[core]:x64-linux
  * boost-multiprecision[core]:x64-linux
  * boost-nowide[core]:x64-linux
  * boost-odeint[core]:x64-linux
  * boost-outcome[core]:x64-linux
  * boost-parameter[core]:x64-linux
  * boost-parameter-python[core]:x64-linux
  * boost-phoenix[core]:x64-linux
  * boost-poly-collection[core]:x64-linux
  * boost-polygon[core]:x64-linux
  * boost-pool[core]:x64-linux
  * boost-process[core]:x64-linux
  * boost-program-options[core]:x64-linux
  * boost-property-map[core]:x64-linux
  * boost-property-tree[core]:x64-linux
  * boost-proto[core]:x64-linux
  * boost-ptr-container[core]:x64-linux
  * boost-python[core]:x64-linux
  * boost-qvm[core]:x64-linux
  * boost-random[core]:x64-linux
  * boost-safe-numerics[core]:x64-linux
  * boost-scope-exit[core]:x64-linux
  * boost-serialization[core]:x64-linux
  * boost-signals2[core]:x64-linux
  * boost-sort[core]:x64-linux
  * boost-spirit[core]:x64-linux
  * boost-stacktrace[core]:x64-linux
  * boost-statechart[core]:x64-linux
  * boost-static-string[core]:x64-linux
  * boost-test[core]:x64-linux
  * boost-thread[core]:x64-linux
  * boost-timer[core]:x64-linux
  * boost-tokenizer[core]:x64-linux
  * boost-tti[core]:x64-linux
  * boost-type-erasure[core]:x64-linux
  * boost-ublas[core]:x64-linux
  * boost-units[core]:x64-linux
  * boost-uuid[core]:x64-linux
  * boost-variant[core]:x64-linux
  * boost-variant2[core]:x64-linux
  * boost-vmd[core]:x64-linux
  * boost-wave[core]:x64-linux
  * boost-xpressive[core]:x64-linux
  * boost-yap[core]:x64-linux
  * bzip2[core]:x64-linux
  * libffi[core]:x64-linux
  * libiconv[core]:x64-linux
  * liblzma[core]:x64-linux
  * openssl[core]:x64-linux
  * openssl-unix[core]:x64-linux
  * python3[core]:x64-linux
  * zlib[core]:x64-linux
  * zstd[core]:x64-linux
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-linux...
Starting package 1/91: bzip2:x64-linux
Building package bzip2[core]:x64-linux...
Could not locate cached archive: /root/.cache/vcpkg/archives/6e/6ef5e41b2d631729a9a51d4dcb821e7fbb03788c.zip
-- Fetching https://sourceware.org/git/bzip2.git...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:85 (message):
    Command failed: /usr/local/bin/git fetch https://sourceware.org/git/bzip2.git 75a94bea3918e612b879d6a11ca64b8689526147 --depth 1 -n
    Working Directory: /root/Git/vcpkg/downloads/git-tmp
    Error code: 128
    See logs for more information:
      /root/Git/vcpkg/buildtrees/bzip2/git-fetch-x64-linux-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_git.cmake:77 (vcpkg_execute_required_process)
  ports/bzip2/portfile.cmake:1 (vcpkg_from_git)
  scripts/ports.cmake:79 (include)

Error: Building package bzip2:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: bzip2:x64-linux
  Vcpkg version: 2020.06.15-unknownhash

Additionally, attach any relevant sections from the log files above.

**Additional context**
The detailed information about the "/root/Git/vcpkg/buildtrees/bzip2/git-fetch-x64-linux-err.log" is
error: Server does not allow request for unadvertised object 75a94bea3918e612b879d6a11ca64b8689526147

**Comment by ustchqf** [comment]
I have used the ./vcpkg update command, but it doesn't work

**Comment by PhoebeHui** [comment]
Could you download the attchments and put it to dowloads folder and try again?

[bzip2-75a94bea3918e612b879d6a11ca64b8689526147.tar.gz](https://github.com/microsoft/vcpkg/files/5238487/bzip2-75a94bea3918e612b879d6a11ca64b8689526147.tar.gz)

**Comment by omrta-dev** [comment]
I was also experiencing this issue on the latest version of vcpkg and after `update` the issue was not solved. 

The solution provided by @PhoebeHui did fix the issue.

**Comment by ustchqf** [comment]
> Could you download the attchments and put it to dowloads folder and try again?
> 
> [bzip2-75a94bea3918e612b879d6a11ca64b8689526147.tar.gz](https://github.com/microsoft/vcpkg/files/5238487/bzip2-75a94bea3918e612b879d6a11ca64b8689526147.tar.gz)

OK. the solution does work. Thank you very much for your help.

**Comment by PhoebeHui** [comment]
Good to know it works.
