### ISSUE TITLE
[vtk] build failure

### ISSUE THREAD

**Issue by EvaKrassnig** [microsoft/vcpkg#13563]
**Host Environment**
- OS: Windows 10
- Compiler: revision

**To Reproduce**
`./vcpkg install pcl
  Package: vtk:x86-windows
  Vcpkg version: 2020.06.15-nohash

**Failure logs** 
Computing installation plan...
The following packages will be built and installed:
    pcl[core]:x86-windows
  * vtk[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x86-windows...
Starting package 1/2: vtk:x86-windows
Building package vtk[core]:x86-windows...
Could not locate cached archive: C:\Users\KREV\AppData\Local\vcpkg/archives\ab\abc9418366cd38de28624351efbb725ee425eb30.zip
-- Using cached C:/scr/vcpkg/downloads/Kitware-VTK-96e6fa9b3ff245e4d51d49f23d40e9ad8774e85e.tar.gz
-- Cleaning sources at C:/scr/vcpkg/buildtrees/vtk/src/ad8774e85e-a44294b9ee.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/scr/vcpkg/downloads/Kitware-VTK-96e6fa9b3ff245e4d51d49f23d40e9ad8774e85e.tar.gz
-- Applying patch 6811.patch
-- Applying patch FindLZMA.patch
-- Applying patch FindLZ4.patch
-- Applying patch Findproj.patch
-- Applying patch vtkm.patch
-- Applying patch pegtl.patch
-- Applying patch pythonwrapper.patch
-- Applying patch NoUndefDebug.patch
-- Applying patch python_debug.patch
-- Applying patch fix-using-hdf5.patch
-- Applying patch FindExpat.patch
-- Using source at C:/scr/vcpkg/buildtrees/vtk/src/ad8774e85e-a44294b9ee.clean
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:83 (message):
    Command failed: ninja -v
    Working Directory: C:/scr/vcpkg/buildtrees/vtk/x86-windows-rel/vcpkg-parallel-configure
    Error code: 2
    See logs for more information:
      C:\scr\vcpkg\buildtrees\vtk\config-x86-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:303 (vcpkg_execute_required_process)
  ports/vtk/portfile.cmake:143 (vcpkg_configure_cmake)
  scripts/ports.cmake:79 (include)

Error: Building package vtk:x86-windows failed with: BUILD_FAILED

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Please provide the error log: `C:\scr\vcpkg\buildtrees\vtk\config-x86-windows-out.log`

**Comment by EvaKrassnig** [comment]
Hi, the logfile just gave the information that the installation was interrupted by user (as after a half day of installation I decided to quit the process). It was working on x64, so I will close this issue. My application is still not running due to other problems ocurring, but I will start a new issue in case I cannot get it working. Thank you for supporting!
