### ISSUE TITLE
[bzip2:x64-windows-static] Building package failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by yuyenkan** [microsoft/vcpkg#13573]
**Host Environment**
- OS: Window
- Compiler: revision

**To Reproduce**
vcpkg install --triplet x64-windows-static berkeleydb boost-filesystem boost-multi-index boost-signals2 boost-test boost-thread libevent[thread] zeromq double-conversion

**Failure logs** 
-- Fetching https://sourceware.org/git/bzip2.git...
-- Extracting source C:/xampp 7.3.7/htdocs/bc/vcpkg/downloads/bzip2-75a94bea3918e612b879d6a11ca64b8689526147.tar.gz
-- Applying patch fix-import-export-macros.patch
-- Using source at C:/xampp 7.3.7/htdocs/bc/vcpkg/buildtrees/bzip2/src/8689526147-1ef169fbaa.clean
-- Configuring x64-windows-static
-- Building x64-windows-static-dbg
-- Building x64-windows-static-rel
-- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz...
-- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst...
-- Fixing pkgconfig file: C:/xampp 7.3.7/htdocs/bc/vcpkg/packages/bzip2_x64-windows-static/lib/pkgconfig/bzip2.pc
-- CHECK_LIB_bz2_RELEASE:CHECK_LIB_bz2_RELEASE-NOTFOUND
CMake Error at scripts/cmake/vcpkg_fixup_pkgconfig.cmake:232 (message):
  Library "bz2" was not found! If it is a system library use the
  SYSTEM_LIBRARIES parameter for the vcpkg_fixup_pkgconfig call! Otherwise,
  correct the *.pc file
Call Stack (most recent call first):
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:297 (vcpkg_fixup_pkgconfig_check_files)
  ports/bzip2/portfile.cmake:43 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:79 (include)

Error: Building package bzip2:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: bzip2:x64-windows-static
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by JackBoosY** [comment]
_C:/xampp 7.3.7/htdocs/bc/vcpkg_
Please clone vcpkg in a non-space path and try again.

Thanks.

**Comment by yuyenkan** [comment]
yes it is work with path without space now.

**Comment by JackBoosY** [comment]
Please do not close this question before adapted the path with spaces.

**Comment by JackBoosY** [comment]
cc @Neumann-A

**Comment by Neumann-A** [comment]
@JackBoosY #13126 should close this.

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/13103.

**Comment by juanjuankai** [comment]
When i install vs2017 not using englist package, it also happens; install english package, then it works.
