### ISSUE TITLE
fmt[core] build failure

### ISSUE THREAD

**Issue by juniorjacob** [microsoft/vcpkg#13593]
**Compiler**
- OS: Windows
- Compiler: x64 VC++

**To Reproduce**
`./vcpkg install fmt:x64-windows`

**Failure logs** 
D:\VS\Projects\vcpkg>vcpkg.exe install spdlog:x64-windows
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
Computing installation plan...
The following packages will be built and installed:
  * fmt[core]:x64-windows
    spdlog[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Starting package 1/2: fmt:x64-windows
Building package fmt[core]:x64-windows...
Could not locate cached archive: C:\Users\EpiKD\AppData\Local\vcpkg\archives\fb\fbe85803930a7d011b016cb9dcec88c184dddb97.zip
-- Using cached D:/VS/Projects/vcpkg/downloads/fmtlib-fmt-cd4af11efc9c622896a3e4cb599fa28668ca3d05.tar.gz
-- Cleaning sources at D:/VS/Projects/vcpkg/buildtrees/fmt/src/8668ca3d05-7f40cec0ee.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/VS/Projects/vcpkg/downloads/fmtlib-fmt-cd4af11efc9c622896a3e4cb599fa28668ca3d05.tar.gz
-- Applying patch fix-warning4189.patch
-- Using source at D:/VS/Projects/vcpkg/buildtrees/fmt/src/8668ca3d05-7f40cec0ee.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: D:/VS/Projects/vcpkg/packages/fmt_x64-windows/share/fmt/copyright
-- Fixing pkgconfig file: D:/VS/Projects/vcpkg/packages/fmt_x64-windows/lib/pkgconfig/fmt.pc
-- Fixing pkgconfig file: D:/VS/Projects/vcpkg/packages/fmt_x64-windows/debug/lib/pkgconfig/fmt.pc
-- CHECK_LIB_fmt_DEBUG:CHECK_LIB_fmt_DEBUG-NOTFOUND
CMake Error at scripts/cmake/vcpkg_fixup_pkgconfig.cmake:232 (message):
  Library "fmt" was not found! If it is a system library use the
  SYSTEM_LIBRARIES parameter for the vcpkg_fixup_pkgconfig call! Otherwise,
  correct the *.pc file
Call Stack (most recent call first):
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:328 (vcpkg_fixup_pkgconfig_check_files)
  ports/fmt/portfile.cmake:44 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:79 (include)

**Additional context**
In a previous version of vcpkg, this worked just fine, it seems the fixing pkgconfig file update broke this for me.
Also I need fmt compiled to compile spdlog, I have already tried updating the prefix directory in the .pc files to accommodate for my environment path. I have also tried reinstalling older versions of vcpkg, setting up a new environment, moving environments, and updating / clearing vcpkg.

**Comment by JackBoosY** [comment]
Oh, that's because the vcpkg path contains capital letters. Duplicate to #12709.
