### ISSUE TITLE
Fails to download sources using msys2 git on the path

### ISSUE THREAD

**Issue by GyrosGeier** [microsoft/vcpkg#13602]
**Describe the bug**
We're building on a CI machine that has both msys2 and MSVC installed. The msys2 installation is in the system PATH to make msys2 git available to the rest of the system including Jenkins, which uses it to check out sources for both msys2 and MSVC based projects. Since there is only a single git installation, there are no incompatibilities between calling git from a shell script running under msys2 and calling git from the Jenkins plugin.

When building a package that pulls dependencies through vcpkg, the same git installation is used, but the PATH appears to be reset, causing git's helper subprocesses to fail to load due to missing DLLs. There are various bug reports for individual ports that fail to build with an error message similar to

```
Starting package 1/106: bzip2:x86-windows
Building package bzip2[core]:x86-windows...
Could not locate cached archive: C:\Users\Build\AppData\Local\vcpkg\archives\86\8611ad05a77a0986b4ea7a56e4257a4aba1629b8.zip
-- Fetching https://sourceware.org/git/bzip2.git...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:85 (message):
    Command failed: C:/Users/Build/kicad-winbuilder/msys64/usr/bin/git.exe fetch https://sourceware.org/git/bzip2.git 75a94bea3918e612b879d6a11ca64b8689526147 --depth 1 -n
    Working Directory: C:/Jenkins/workspace/test/vcpkg/downloads/git-tmp
    Error code: 3328
    See logs for more information:
      C:\Jenkins\workspace\test\vcpkg\buildtrees\bzip2\git-fetch-x86-windows-err.log
```

The error message in the stderr log is

     C:/Users/Build/kicad-winbuilder/msys64/usr/lib/git-core/git-remote-https.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory

This can be easily reproduced using `vcpkg env`:

```
C:\Jenkins\workspace\test>vcpkg\vcpkg env
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Jenkins\workspace\test\vcpkg>git clone https://sourceware.org/git/bzip2.git
'git' is not recognized as an internal or external command,
operable program or batch file.

C:\Jenkins\workspace\test\vcpkg>"C:\Users\Build\kicad-winbuilder\msys64\usr\bin\
git.exe" clone https://sourceware.org/git/bzip2.git
Cloning into 'bzip2'...
C:/Users/Build/kicad-winbuilder/msys64/usr/lib/git-core/git-remote-https.exe: er
ror while loading shared libraries: ?: cannot open shared object file: No such f
ile or directory
```

So it seems that the git downloader happily uses a git installation on the regular system path, but the cleaned environment is unsuitable to actually run git.

**Environment**
- OS: Windows 7
- Compiler: Visual Studio 2019 Build Tools

**To Reproduce**
1. On a fresh machine, install msys2 with git and point PATH at the msys2 git executable
2. Install Visual Studio without git integration
3. `./vcpkg install bzip2`

**Expected behavior**
I'd expect this either to fail earlier (by failing to look up git.exe along the sanitized PATH, with a sensible error message), or not at all. I'd be happy with vcpkg creating a private git installation for downloading files, as it will only access public repositories, so no consistency with the system-wide installation (e.g. ssh agent socket paths) is required.

**Failure logs** 
- https://jenkins.simonrichter.eu/job/test/59/execution/node/44/log/

**Comment by PhoebeHui** [comment]
@ras0219-msft, could you help have a look?

**Comment by NancyLi1013** [comment]
Duplicated to #16282, let's track this issue there.
