### ISSUE TITLE
recovery from failed `vcpkg.exe upgrade --no-dry-run`

### ISSUE THREAD

**Issue by rockonedege** [microsoft/vcpkg#13600]
****

**Is your feature request related to a problem? Please describe.**
the current `vcpkg upgrade --no-dry-run` starts with removing legacy packages and them download the new ones. if the upgrade fails half-way, there's no way to recover the upgrade process from running `vcpkg upgrade --no-dry-run` again.

**Proposed solution**
when `vcpkg upgrade --no-dry-run` fails halfway, it's possible the resume the process by run the command again

**Describe alternatives you've considered**
keep  a copy of package list to be upgraded before running the command

**Additional context**
None

**Comment by NancyLi1013** [comment]
Hi @rockonedege 
Thanks for posting this issue.
It seems to be duplicated to #8925.
So let's move attention there to track this issue.

Thanks.
