### ISSUE TITLE
Cannot build bzip2:x64-windows-static in visual studio 2019

### ISSUE THREAD

**Issue by dahubley** [microsoft/vcpkg#13605]
When attempting to build boost with vcpkg using Visual Studio 2019 I get the following error:

-- CHECK_LIB_bz2_RELEASE:CHECK_LIB_bz2_RELEASE-NOTFOUND
CMake Error at scripts/cmake/vcpkg_fixup_pkgconfig.cmake:232 (message):
  Library "bz2" was not found! If it is a system library use the
  SYSTEM_LIBRARIES parameter for the vcpkg_fixup_pkgconfig call! Otherwise,
  correct the *.pc file
Call Stack (most recent call first):
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:297 (vcpkg_fixup_pkgconfig_check_files)
  ports/bzip2/portfile.cmake:43 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:79 (include)

Error: Building package bzip2:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: bzip2:x64-windows-static
  Vcpkg version: 2020.06.15-nohash

**Comment by PhoebeHui** [comment]
@dahubley, does the vcpkg path with a space? it looks same issue with https://github.com/microsoft/vcpkg/issues/13103, and would fix by PR https://github.com/microsoft/vcpkg/pull/13126

**Comment by dahubley** [comment]
@PhoebeHui looks to the same. I moved the vcpkg directory to C:// and it works fine. Had to be something to do with the vcpkg location.

**Comment by PhoebeHui** [comment]
Good to know, thanks!

Duplicated to https://github.com/microsoft/vcpkg/issues/13103.

**Comment by unusual-aspect** [comment]
I have same title, different problem:

`
"C:\Windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "D:\a\_temp\70730c63-1d64-4e9f-a9d1-d0283ac330c6.cmd"
Computing installation plan...
The following packages will be built and installed:
bzip2[core]:x64-windows-static -> 1.0.8#1
Detecting compiler hash for triplet x64-windows-static...
Could not locate cached archive: C:\Users\VssAdministrator\AppData\Local\vcpkg\archives\cf\cf0f4a1478b0809f582900653988b3668f8a97c1.zip
Starting package 1/1: bzip2:x64-windows-static
Building package bzip2[core]:x64-windows-static...
-- Fetching https://sourceware.org/git/bzip2.git...
Make Error at scripts/cmake/vcpkg_execute_required_process.cmake:91 (file):
file failed to open for reading (No such file or directory):
C:/vcpkg/buildtrees/bzip2/git-init-x64-windows-static-out.log
Call Stack (most recent call first):
scripts/cmake/vcpkg_from_git.cmake:85 (vcpkg_execute_required_process)
ports/bzip2/portfile.cmake:1 (vcpkg_from_git)
scripts/ports.cmake:142 (include)
Error: Building package bzip2:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
Package: bzip2:x64-windows-static
Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

`

**Comment by PhoebeHui** [comment]
@unusual-aspect, please open a new issue to track.
