### ISSUE TITLE
Why is the key in VCPkg Manifest called version-string instead of version?

### ISSUE THREAD

**Issue by pratikpc** [microsoft/vcpkg#13604]
https://github.com/microsoft/vcpkg/blob/master/docs/specifications/manifests.md

In most such Package Managers, such as NPM, the term used is version and not version-string

So I was somewhat curious as to what led to this design choice?

**Comment by NancyLi1013** [comment]
Hi @pratikpc 
Sorry for the delay.

In fact, it is just a name, which has no specific meaning. Since this is a string, we called it `version-string`.

Please see this [here](https://github.com/microsoft/vcpkg/blob/master/docs/specifications/manifests.md#specification).
```
One (and only one) of the following version fields:
"version-string": A string. Has no semantic meaning. Equivalent to CONTROL's Version: field.
Other version fields will be defined by the Versions RFC
```

**Comment by pratikpc** [comment]
@NancyLi1013 hey a delay is absolutely fine  
It's not like anything in production was held up.

I was just wondering why they didn't end up calling it `version` like NPM and Cargo  
I thought adding `-string` to `version` was due to technical reasons or because `version` was already being used for something else.

**Comment by NancyLi1013** [comment]
@strega-nil 
Could you please help comment something about this question?

**Comment by strega-nil** [comment]
@pratikpc we have plans to use the name of the version key as a way to disambiguate the type of versions a library is using; for example:

* `"version"` -- a semver-like version, `(number).(number).(number)...`
* `"date"` -- a date, `2020-09-28`
* `"version-string"` -- a string without real meaning

etc.

**Comment by pratikpc** [comment]
@strega-nil that is actually smart

One version for the public to perform updates

Another for internal purposes to track build numbers etc and other stuff!

Can we update the docs to mention this?

**Comment by strega-nil** [comment]
Well, the idea is that only one of these three fields would be set; `port-version` is supposed to be used for changes that don't change the version of the underlying library.

**Comment by pratikpc** [comment]
Thank you

This resolves my confusion
