### ISSUE TITLE
Found both manifest and CONTROL file in port

### ISSUE THREAD

**Issue by UnknownObject000** [microsoft/vcpkg#13615]
I'm using ```vcpkg search ffmpeg``` command, but it output an error says
```Found both manifest and CONTROL file in port F:\vcpkg\ports\3fd; please rename one or the other```
I deleted the CONTROL file, and run that command again. But it pops up again:
```Found both manifest and CONTROL file in port F:\vcpkg\ports\abseil; please rename one or the other```
I deleted that too. But it seems lots of packages have that issue so that I can't use the search function.
I want to know what is calling those issue and how can I fix it at once.

**Comment by StarGate-One** [comment]
- Sounds like the copy of vcpkg may be corrupt in some way...
- I would suggest creating a new clone and go from there.
- A port can have either a CONTROL (old being phased out) or vcpkg.json (new being phased in) file, but not both. 
- In a case where both exist, it seems when the git pull is done to refresh the clone, it is not deleting the CONTROL file on the ports upgraded.
- Maybe the userid being used does not have delete authority to files/directories in vcpkg tree structure???

**Comment by PhoebeHui** [comment]
We suggest to use 'git pull' to get the latest source. @UnknownObject000, could you create a new clone and try again?

**Comment by PhoebeHui** [comment]
@UnknownObject000, please reopen this issue if the problem persist.

**Comment by UnknownObject000** [comment]
@PhoebeHui 'git pull' does not work.
The command line output as follows:
PS F:\vcpkg> git pull                                                                                                                                                  remote: Enumerating objects: 885, done.                                                                                                                                remote: Counting objects: 100% (885/885), done.                                                                                                                        Rremote: Total 1564 (delta 885), reused 885 (delta 885), pack-reused 679eceiving                                                                                       Receiving objects: 100% (1564/1564), 492.01 KiB | 429.00 KiB/s
Receiving objects: 100% (1564/1564), 530.08 KiB | 465.00 KiB/s, done.
Resolving deltas: 100% (1000/1000), completed with 466 local objects.
From https://github.com/microsoft/vcpkg
   ff1d20fd9..8776756e0  master                  -> origin/master
 + 00d97b2f5...0e8032765 dev/bion/unstable-queue -> origin/dev/bion/unstable-queu                                                                                      e  (forced update)
error: Your local changes to the following files would be overwritten by merge:
        .gitattributes
        .github/pull_request_template.md
        .gitignore
        CHANGELOG.md
        README.md
        README_zh_CN.md
        docs/about/privacy.md
        docs/examples/installing-and-using-packages.md
        docs/examples/overlay-triplets-linux-dynamic.md
        docs/examples/packaging-zipfiles.md
        docs/examples/patching.md
        docs/index.md
        docs/maintainers/control-files.md
        docs/maintainers/maintainer-guide.md
        docs/maintainers/portfile-functions.md
        docs/maintainers/vcpkg_apply_patches.md
        docs/maintainers/vcpkg_build_make.md
        docs/maintainers/vcpkg_check_linkage.md
        docs/maintainers/vcpkg_common_definitions.md
        docs/maintainers/vcpkg_configure_cmake.md
        docs/maintainers/vcpkg_configure_make.md
        docs/maintainers/vcpkg_fail_port_install.md
        docs/maintainers/vcpkg_find_acquire_program.md
        docs/maintainers/vcpkg_fixup_cmake_targets.md
        docs/maintainers/vcpkg_from_git.md
        docs/maintainers/vcpkg_prettify_command.md
        docs/tool-maintainers/testing.md
        docs/users/config-environment.md
        docs/users/integration.md
        docs/users/triplets.md
        ports/7zip/CMakeLists.txt
        ports/7zip/CONTROL
        ports/abseil/fix-lnk2019-error.patch
        ports/abseil/portfile.cmake
        ports/ace/CONTROL
        ports/ace/portfile.cmake
        ports/activemq-cpp/CONTROL
        ports/activemq-cpp/portfile.cmake
        ports/aixlog/CONTROL
        ports/aixlog/portfile.cmake
        ports/alac/CONTROL
        ports/alembic/CONTROL
        ports/alembic/fix-find-openexr-ilmbase.patch
        ports/alembic/portfile.cmake
        ports/aliyun-oss-c-sdk/CONTROL
        ports/aliyun-oss-c-sdk/portfile.cmake
        ports/allegro5/CONTROL
        ports/allegro5/portfile.cmake
        ports/ampl-mp/CONTROL
        ports/amqpcpp/CONTROL
        ports/amqpcpp/portfile.cmake
        ports/angle/001-fix-uwp.patch
        ports/angle/002-fix-builder-error.patch
        ports/angle/CMakeLists.txt
        ports/angle/CONTROL
        ports/angle/portfile.cmake
        ports/anyrpc/CONTROL
        ports/anyrpc/portfile.cmake
        ports/apr-util/CONTROL
        ports/apr-util/portfile.cmake
        ports/apr-util/use-vcpkg-expat.patch
        ports/apr/CONTROL
        ports/apr/portfile.cmake
        ports/argh/CONTROL
        ports/argh/portfile.cmake
        ports/argtable2/CONTROL
        ports/argtable2/portfile.cmake
        ports/argtable3/portfile.cmake
        ports/argumentum/CONTROL
        ports/argumentum/portfile.cmake
        ports/armadillo/CONTROL
        ports/armadillo/portfile.cmake
        ports/arrow/CONTROL
        ports/arrow/all.patch
        ports/arrow/portfile.cmake
        ports/asmjit/CONTROL
        ports/asmjit/portfile.cmake
        ports/assimp/CONTROL
        ports/assimp/portfile.cmake
        ports/atkmm/CONTROL
        ports/atkmm/portfile.cmake
        ports/aubio/CMakeLists.txt
        ports/aubio/CONTROL
        ports/avro-c/CONTROL
        ports/avro-c/avro.patch
        ports/avro-c/portfile.cmake
        ports/aws-c-common/CONTROL
        ports/aws-c-common/disable-error-4068.patch
        ports/aws-c-common/disable-internal-crt-option.patch
        ports/aws-c-common/portfile.cmake
        ports/aws-c-event-stream/CONTROL
        ports/aws-c-event-stream/portfile.cmake
        ports/aws-checksums/CONTROL
        ports/aws-checksums/portfile.cmake
        ports/aws-lambda-cpp/CONTROL
        ports/aws-lambda-cpp/portfile.cmake
        ports/aws-sdk-cpp/CONTROL
        ports/aws-sdk-cpp/CONTROL.in
        ports/aws-sdk-cpp/compute_build_only.cmake
        ports/aws-sdk-cpp/portfile.cmake
        ports/azmq/CONTROL
        ports/azmq/portfile.cmake
        ports/azure-c-shared-utility/CONTROL
        ports/azure-c-shared-utility/portfile.cmake
        ports/azure-iot-sdk-c/CONTROL
        ports/azure-iot-sdk-c/portfile.cmake
        ports/azure-kinect-sensor-sdk/CONTROL
        ports/azure-kinect-sensor-sdk/portfile.cmake
        ports/azure-macro-utils-c/CONTROL
        ports/azure-macro-utils-c/portfile.cmake
        ports/azure-storage-cpp/CONTROL
        ports/azure-storage-cpp/portfile.cmake
        ports/azure-uamqp-c/CONTROL
        ports/azure-uamqp-c/portfile.cmake
        ports/azure-uhttp-c/CONTROL
        ports/azure-uhttp-c/portfile.cmake
        ports/azure-umqtt-c/CONTROL
        ports/azure-umqtt-c/portfile.cmake
        ports/basisu/CONTROL
        ports/basisu/portfile.cmake
        ports/benchmark/CONTROL
        ports/berkeleydb/CONTROL
        ports/berkeleydb/portfile.cmake
        ports/bfgroup-lyra/CONTROL
        ports/bfgroup-lyra/portfile.cmake
        ports/bigint/CONTROL
        ports/bigint/portfile.cmake
        ports/binn/CONTROL
        ports/binn/portfile.cmake
        ports/bitserializer-cpprestjson/CONTROL
        ports/
error: The following untracked working tree files would be overwritten by merge:
        docs/examples/vcpkg_android_example_cmake/.gitignore
        docs/examples/vcpkg_android_example_cmake/CMakeLists.txt
        docs/examples/vcpkg_android_example_cmake/compile.sh
        docs/examples/vcpkg_android_example_cmake/my_lib.cpp
        docs/examples/vcpkg_android_example_cmake_script/.gitignore
        docs/examples/vcpkg_android_example_cmake_script/CMakeLists.txt
        docs/examples/vcpkg_android_example_cmake_script/cmake/vcpkg_android.cmak                                                                                      e
        docs/examples/vcpkg_android_example_cmake_script/compile.sh
        docs/examples/vcpkg_android_example_cmake_script/my_lib.cpp
        docs/maintainers/vcpkg_build_gn.md
        docs/maintainers/vcpkg_build_ninja.md
        docs/maintainers/vcpkg_clean_executables_in_bin.md
        docs/maintainers/vcpkg_configure_gn.md
        docs/maintainers/vcpkg_configure_meson.md
        docs/maintainers/vcpkg_copy_tools.md
        docs/maintainers/vcpkg_fixup_pkgconfig.md
        docs/maintainers/vcpkg_from_sourceforge.md
        docs/maintainers/vcpkg_install_gn.md
        docs/maintainers/vcpkg_install_meson.md
        docs/specifications/binarycaching.md
        docs/specifications/manifests.md
        docs/specifications/prefab.md
        docs/specifications/registries.md
        docs/users/android.md
        ports/3fd/vcpkg.json
        ports/abseil/fix-MSVCbuildfail.patch
        ports/abseil/fix-arm-build.patch
        ports/abseil/fix-cmake-threads-dependency.patch
        ports/abseil/fix-use-cxx17-stdlib-types.patch
        ports/abseil/fix-uwp-build.patch
        ports/abseil/vcpkg.json
        ports/absent/CONTROL
        ports/absent/portfile.cmake
        ports/activemq-cpp/fix-crt-linkage.patch
        ports/akali/CONTROL
        ports/akali/portfile.cmake
        ports/argh/remove_unnamespaced_license_file.patch
        ports/argparse/vcpkg.json
        ports/argtable3/vcpkg.json
        ports/armadillo/add-disable-find-package.patch
        ports/asiosdk/CONTROL
        ports/asiosdk/Findasiosdk.cmake
        ports/asiosdk/portfile.cmake
        ports/asiosdk/usage
        ports/asiosdk/vcpkg-cmake-wrapper.cmake
        ports/audiofile/portfile.cmake
        ports/audiofile/vcpkg.json
        ports/avisynthplus/portfile.cmake
        ports/avisynthplus/vcpkg.json
        ports/avro-c/snappy-pr-793.patch
        ports/avro-cpp/CONTROL
        ports/avro-cpp/install.patch
        ports/avro-cpp/portfile.cmake
        ports/aws-c-common/fix-cmake-target-path.patch
        ports/aws-c-event-stream/fix-cmake-target-path.patch
        ports/aws-checksums/fix-cmake-target-path.patch
        ports/azure-c-shared-utility/fix-utilityFunctions-conditions-preview.patc                                                                                      h
        ports/azure-c-shared-utility/fix-utilityFunctions-conditions.patch                                                                                                     ports/azure-iot-sdk-c/fix-cmake.patch
        ports/azure-kinect-sensor-sdk/fix-dependency-imgui.patch
        ports/azure-kinect-sensor-sdk/k4adeploy.ps1
        ports/basisu/fix-addostream.patch
        ports/behaviortree-cpp/001_port_fixes.patch
        ports/behaviortree-cpp/002_fix_dependencies.patch
        ports/behaviortree-cpp/portfile.cmake
        ports/behaviortree-cpp/vcpkg.json
        ports/berkeleydb/fix-conflict-macro.patch
        ports/bigint/fix-osx-usage.patch
        ports/bitmagic/CONTROL
        ports/bitmagic/portfile.cmake
        ports/bitserializer-pugixml/CONTROL
        ports/bitserializer-pugixml/portfile.cmake
        ports/bitserializer-rapidyaml/CONTROL
        ports/bitserializer-rapidyaml/portfile.cmake
        ports/blend2d/vcpkg.json
        ports/blitz/CONTROL
        ports/blitz/portfile.cmake
        ports/blosc/0002-export-blosc-config.patch
        ports/bond/skip-grpc-compilation.patch
        ports/boost-beast/0002-beast-coroutines.patch
        ports/boost-locale/0001-Fix-boost-ICU-support.patch
        ports/boost-locale/b2-options.cmake
        ports/boost-nowide/CONTROL
        ports/boost-outcome/0001-outcome-assert.patch                                                                                                                          
ports/boost-python/b2-options.cmake                                                                                                                                    
ports/boost-regex/b2-options.cmake                                                                                                                                     
ports/boost-static-string/CONTROL                                                                                                                                      
ports/boost-static-string/portfile.cmake                                                                                                                               
ports/boost-uninstall/CONTROL                                                                                                                                          
ports/boost-uninstall/portfile.cmake                                                                                                                                   
ports/boringssl/0001-vcpkg.patch                                                                                                                                       
ports/boringssl/0002-disable-waring-4065.patch                                                                                                                         
ports/boringssl/CONTROL                                                                                                                                                
ports/boringssl/portfile.cmake                                                                                                                                         
ports/box2d/export-targets.patch                                                                                                                                       
ports/brotli/fix-arm-uwp.patch                                                                                                                                         
ports/brotli/pkgconfig.patch                                                                                                                                           
ports/brpc/CONTROL                                                                                                                                                     
ports/brpc/fix_boost_ptr.patch                                                                                                                                         
ports/brpc/fix_thrift.patch                                                                                                                                            
ports/brpc/portfile.cmake                                                                                                                                              
ports/bullet3/cmake-fix.patch                                                                                                                                          
ports/bullet3/usa                                                                                                                                              
Aborting                                                                                                                                                               
Updating 0ee4f000b..8776756e0

**Comment by PhoebeHui** [comment]
@UnknownObject000, it looks have some changes in your machine so it aborted the 'git pull', I recommand to create a new clone instead.

**Comment by UnknownObject000** [comment]
OK，I'll do that.  But do you know what caused this issue? @PhoebeHui

**Comment by PhoebeHui** [comment]
@UnknownObject000, see https://stackoverflow.com/questions/7446446/getting-aborting-after-git-has-pulled-some-files

**Comment by UnknownObject000** [comment]
> @UnknownObject000, see https://stackoverflow.com/questions/7446446/getting-aborting-after-git-has-pulled-some-files

Thank you. But I mean the vcpkg issue. Why the 'manifest' and 'CONTROL' file shows up at the same time?
