### ISSUE TITLE
Boost build failed

### ISSUE THREAD

**Issue by inlmouse** [Microsoft/vcpkg#1362]
Environment
Windows 7
VS2015 update3
boost:x64-windows
-----
Due to different hash code:

`
diff --git a/include/boost/range/has_range_iterator.hpp b/include/boost/range/has_range_iterator.hpp
index 9eb58b35..88d8664d 100644
--- a/include/boost/range/has_range_iterator.hpp
+++ b/include/boost/range/has_range_iterator.hpp
@@ -37,9 +37,9 @@ namespace boost
             T,
             BOOST_DEDUCED_TYPENAME ::boost::enable_if<
                 BOOST_DEDUCED_TYPENAME mpl::eval_if<is_const<T>,
-                    has_type<range_const_iterator<
+                    has_type<boost::range_const_iterator<
                                 BOOST_DEDUCED_TYPENAME remove_const<T>::type> >,
-                    has_type<range_mutable_iterator<T> >
+                    has_type<boost::range_mutable_iterator<T> >
                 >::type
             >::type
         >
@@ -57,7 +57,7 @@ namespace boost
         struct has_range_const_iterator_impl<
             T,
             BOOST_DEDUCED_TYPENAME ::boost::enable_if<
-                has_type<range_const_iterator<T> >
+                has_type<boost::range_const_iterator<T> >
             >::type
         >
             : boost::mpl::true_
`

**Comment by frederich** [comment]
Works fine for me. What's the error message?

**Comment by KindDragon** [comment]
Fixed in f761259f34706c7c8529fc2340c5e55a9a0c69e8

**Comment by inlmouse** [comment]
Thx, it works.
