### ISSUE TITLE
[ace[core]:x64-windows] LINK fatal error

### ISSUE THREAD

**Issue by Jimmy-Hu** [microsoft/vcpkg#13627]
**Host Environment**
- OS: Windows 10 Pro 64-bit Version 2004 build 19041.508 with Windows Feature Experience Pack 120.2212.31.0
- Compiler: Microsoft Visual Studio 2019 Version 16.7.3

**To Reproduce**
`./vcpkg install ace[core]:x64-windows`

**Failure logs** 
Computing installation plan...
The following packages will be built and installed:
    ace[core]:x64-windows
Detecting compiler hash for triplet x64-windows...
Starting package 1/1: ace:x64-windows
Building package ace[core]:x64-windows...
Could not locate cached archive: C:\Users\jimmy\AppData\Local\vcpkg\archives\f7\f75ffb5e780a99ce5c63b45a19502e9745e9c081.zip
-- Using cached F:/GitHub/vcpkg/downloads/ACE-src-6.5.11.zip
-- Cleaning sources at F:/GitHub/vcpkg/buildtrees/ace/src/ACE-src-6-7fdba7a39c.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source F:/GitHub/vcpkg/downloads/ACE-src-6.5.11.zip
-- Using source at F:/GitHub/vcpkg/buildtrees/ace/src/ACE-src-6-7fdba7a39c.clean
-- Building ace/ace.sln for Release
-- Building ace/ace.sln for Debug
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:85 (message):
    Command failed: msbuild F:/GitHub/vcpkg/buildtrees/ace/x64-windows-dbg/ACE-src-6-7fdba7a39c.clean/ace/ace.sln /p:Configuration=Debug /t:Rebuild /p:Platform=x64 /p:PlatformToolset=v142 /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /p:WindowsTargetPlatformVersion=10.0.18362.0 /p:VcpkgTriplet=x64-windows /p:VcpkgCurrentInstalledDir=F:/GitHub/vcpkg/installed/x64-windows /p:VcpkgManifestInstall=false /m /p:ForceImportBeforeCppTargets=F:/GitHub/vcpkg/scripts/buildsystems/msbuild/vcpkg.targets /p:VcpkgApplocalDeps=false
    Working Directory: F:/GitHub/vcpkg/buildtrees/ace/x64-windows-dbg/ACE-src-6-7fdba7a39c.clean
    Error code: 1
    See logs for more information:
      [F:\GitHub\vcpkg\buildtrees\ace\build-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/5253229/build-x64-windows-dbg-out.log)

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_msbuild.cmake:191 (vcpkg_execute_required_process)
  ports/ace/portfile.cmake:123 (vcpkg_install_msbuild)
  scripts/ports.cmake:79 (include)

Error: Building package ace:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: ace:x64-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by NancyLi1013** [comment]
Hi @Jimmy-Hu 
Thanks for posting this issue.
 This should be a series of issues for many ports not just for `ace`. So I suggest to track this issue in #13642.

So I'm closing this issue for now. Please comment #13462 if you have any ideas about this.

Thanks.
