### ISSUE TITLE
[openimageio:x64-linux] build failure

### ISSUE THREAD

**Issue by jcc10** [microsoft/vcpkg#13621]
**Host Environment**
- OS: Pop!_OS 20.04 LTS
- Compiler: gcc version 8.4.0 (Ubuntu 8.4.0-3ubuntu2) (Is this what goes here?)

**To Reproduce**
`./vcpkg install openimageio[core,ffmpeg,freetype,opencv,gif,openjpeg,webp,tools]`
This is the command I actually need to get working, the comment below this has all 128 variants of the command and if they worked or not. 

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.
[install-x64-linux-rel-out.log](https://github.com/microsoft/vcpkg/files/5250756/install-x64-linux-rel-out.log)
```
-- Building x64-linux-dbg
-- Building x64-linux-rel
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:141 (message):
    Command failed: /home/digitalkitsune/github/vcpkg/downloads/tools/cmake-3.17.2-linux/cmake-3.17.2-Linux-x86_64/bin/cmake --build . --config Release --target install -- -v
    Working Directory: /home/digitalkitsune/github/vcpkg/buildtrees/openimageio/x64-linux-rel
    See logs for more information:
      /home/digitalkitsune/github/vcpkg/buildtrees/openimageio/install-x64-linux-rel-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/openimageio/portfile.cmake:65 (vcpkg_install_cmake)
  scripts/ports.cmake:79 (include)


Error: Building package openimageio:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openimageio:x64-linux
  Vcpkg version: 2020.06.15-unknownhash
```

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by jcc10** [comment]
STUB: success/fail command list

**Comment by jcc10** [comment]
Command checklist updated, Just to be clear, I need the command in the top one to work, the other commands are just for reference.

**Comment by jcc10** [comment]
It looks like something upstream fixed a bunch of stuff as now things are only throwing fits if tools is in the option list.

Updated the test list above with a test I just did today.

**Comment by LilyWangL** [comment]
Thanks for your testing. I will confirm it soon.

**Comment by jcc10** [comment]
> Thanks for your testing.

I figure more information is always better then less.

Tell me if you need any other logs from my end, probably better to have logs from the "least common denominator" fail. I just don't know which one(s) that is.

Thanks for the tool, I have no doubt that it saves a lot of time when it's working properly.

**Comment by dg0yt** [comment]
For linking to ffmpeg, special flags must be passed for static builds with dynamic CRT: 
https://github.com/microsoft/vcpkg/pull/23918/commits/4e29223d2a4423ac84b04a37c92c4b9d3d145f09
