### ISSUE TITLE
[New Port Request] liblqr

### ISSUE THREAD

**Issue by JustZhenya** [microsoft/vcpkg#13631]
Library name: LiquidRescale library 0.4.0 (liblqr)

Library description: The LiquidRescale (lqr) library provides a C/C++ API for performing non-uniform resizing of images by the seam-carving technique.

Source repository URL: https://github.com/carlobaldassi/liblqr

Project homepage (if different from the source repository): http://liblqr.wikidot.com/

Anything else that is useful to know when adding (such as optional features the library may have that should be included): depends on glib-2.0, uses autotools

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
