### ISSUE TITLE
[Feature Request] If No Package is installed and --x-json is specified, vcpkg list should be empty

### ISSUE THREAD

**Issue by pratikpc** [microsoft/vcpkg#13637]
****

**Is your feature request related to a problem? Please describe.**
A bit of an annoyance
I was writing an app of sorts that more tightly integrates vcpkg and CMake
During that, for obvious reasons, I had to access vcpkg list
So as I was developing an app, I used vcpkg list --x-json

When packages are Installed, output is
{
...blah blah blah
Useful info
}

When nothing is installed
Output is 
`No packages are installed. Did you mean `search`?
`
**Proposed solution**
Show output as `{}` (an Empty Object)

**Describe alternatives you've considered**
On my side, I am checking for an Exception from JSON.parse currently

**Additional context**
Not really
It's also experimental so unstable behaviour is both fair and expected

Edit:-

**Fixing This**

The place to fix this would be
https://github.com/microsoft/vcpkg/blob/2a6442cb934de2f99c8ac5bbd8a9dcf5538aee98/toolsrc/src/vcpkg/commands.list.cpp#L96

Out here if JSON Mode is enabled, it should output {}

Should I create a PR?

I can help out here

```cpp
        if (installed_ipv.empty())
        {
            if(args.output_json())
                     System::print2("{}");
            else
                     System::print2("No packages are installed. Did you mean `search`?\n");
            Checks::exit_success(VCPKG_LINE_INFO);
        }
```

**Comment by PhoebeHui** [comment]
The original message may be useful for users, however, show output as {} (an Empty Object) also make sense, @strega-nil, could you help confirm this issue?

**Comment by strega-nil** [comment]
This makes sense to me, although I'd do `System::print2(Json::stringify(Json::Object(), {}))`.

**Comment by pratikpc** [comment]
Yeah that would be the better method

Sorry

**Comment by strega-nil** [comment]
Do you want to open a PR?

**Comment by pratikpc** [comment]
@strega-nil just opened a PR
Thanks for the help!!!
