### ISSUE TITLE
[openssl-windows:x64-windows] build failure

### ISSUE THREAD

**Issue by anbull** [microsoft/vcpkg#13646]
**Host Environment**
- OS: [win10]
- Compiler: revision

**To Reproduce**
`./vcpkg install boost:x64-windows`

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

-- Build x64-windows-dbg done
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:85 (message):
    Command failed: C:/Workspace/vcpkg/downloads/tools/powershell-core-7.0.3-windows/powershell.exe -noprofile -executionpolicy Bypass -nologo -file C:/Workspace/vcpkg/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary C:/Workspace/vcpkg/packages/openssl-windows_x64-windows/tools/openssl/openssl.exe -installedDir C:/Workspace/vcpkg/packages/openssl-windows_x64-windows/bin
    Working Directory: C:/Workspace/vcpkg
    Error code: -2146232797
    See logs for more information:
      C:\Workspace\vcpkg\buildtrees\openssl-windows\copy-tool-dependencies-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_copy_tool_dependencies.cmake:27 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_copy_tool_dependencies.cmake:37 (search_for_dependencies)
  ports/openssl-windows/portfile.cmake:169 (vcpkg_copy_tool_dependencies)
  scripts/ports.cmake:79 (include)

Error: Building package openssl-windows:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openssl-windows:x64-windows
  Vcpkg version: 2020.06.15-nohash

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by JackBoosY** [comment]
Duplicate to #12849.
