### ISSUE TITLE
[vcpkg] use x64 (64-bit) compiler/linker/utilities and tools when building x64 triplets on windows

### ISSUE THREAD

**Issue by StarGate-One** [microsoft/vcpkg#13642]
**Feature Improvement to vcpkg**
[vcpkg] use x64 (64-bit) compiler/linker/utilities and tools when building x64 triplets on windows

**Is your feature request related to a problem? Please describe.**
x86 (32-bit) compiler/linker/utilities and tools often fail building 64-bit windows triplets with exhausted heap memory, memory segmentation faults, other untraceable issues, etc. 
I know I have spent literally days tracing down some issue related to a 32-bit binary, tools, utility somehow causing an issue with the build of a 64-bit binary (not just windows either, but on Linux/Unix also).
Examples I could find:
1. Issue #13627 [ace[core]:x64-windows] LINK fatal error LINK : the 32-bit linker (C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.27.29110\bin\HostX86\x64\link.exe) ran out of heap space
2. Issue #13388 building faileds on shogun repositions. C:\vcpkg\installed\x64-windows-static\include\eigen3\Eigen\src/Core/MatrixBase.h(276): fatal error C1060: compiler is out of heap space
3. Issue #1594 failure building boost (c1060) C:\externals\vcpkg-master\buildtrees\boost\src\boost_1_64_0\boost/proto/generate.hpp(456): fatal error C1060: compiler is out of heap space
4. Issue #12240 [nettle:x64-windows] build failure https://github.com/microsoft/vcpkg/issues/12240#issuecomment-653815465 seems 32-bit yasm is causing issues on 64-bit ports, using 64-bit yasm seems to fix in many cases ([gmp:x64-windows] build failure #12237, [gmp,nettle,hogweed] Add new ports #10613).

**Proposed solution**
use x64 (64-bit) compiler/linker/utilities and tools when building x64 triplets on windows (Linux/Unix/OSX) where available.
Although Linux seems to be a challenge as there is the /lib, /lib32, /libx32, /lib64, /libx64, etc depending on the flavor of Linux you are working with, as I am always having to modify the portfile.cmake to handle the /lib64 used in OpenSUSE for 64-bit binaries instead of /lib used on other "user friendly" Linux versions.

**Describe alternatives you've considered**
In my environment, vcpkg is build with the -win64 option, vcpkg_acquire_program.cmake and vcpkgTools.xml have been modified to acquire and install x64 bit versions where available, the environment variables PreferredToolArchitecture=x64 and _IsNativeEnvironment=true are set (commented out the set PreferredToolArchitecture= in both vcvars.bat and vcvars140.bat and modified visualstudio.cpp to use /HostX64 instead of /Hostx86, as I do not even build x86 ports/projects/binaries at all. 
Result is I have not had any of the issues with heap, segmentation or other unexplained problems with the 64 ports.

**Additional context**
Even though Microsoft is still update x86 versions of windows, the x86 platforms are dying out and we need to engage in the mindset to build x64 platforms and software, having the x86 (32-bit) go the way of the 4, 8 and 16-bit programs of the past.

**Comment by JackBoosY** [comment]
That must be a bug of vcpkg. We need to fix it soon.

**Comment by Neumann-A** [comment]
From --debug
`[DEBUG] CreateProcessW(cmd /c ""C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" -vcvars_ver=14.2 amd64   2>&1 <NUL" & echo cdARN4xjKueKScMy9C6H& set)`

from the script:
```
if /I "%1"=="amd64" (
    set __VCVARSALL_TARGET_ARCH=x64
    set __VCVARSALL_HOST_ARCH=x64
    set __local_ARG_FOUND=1
)
```

so the environment should be setup correctly. Maybe something is failing in vcpkg detection and is calling `vcvarsall.bat` with `x86_x64` or `x86_amd64`

**Comment by StarGate-One** [comment]
Closing, no longer an issue for me as we have chosen to no longer use vcpkg.

**Comment by JackBoosY** [comment]
Reopen this issue since it's not resolved.

**Comment by JonLiu1993** [comment]
Currently, vcpkg uses the x64 (64-bit) compiler by default when building x64 triples on Windows (Linux/Unix/OSX).
