### ISSUE TITLE
Error: Building packages bzip2:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by NewcomerBS** [microsoft/vcpkg#13655]
Hi there
I've got a problem while trying to install Boost-any and Boost libraries for Visual Studio in order to include boost/any.hpp.
Since the boost-any.hpp was not available in visual studio after installing boost-any module I also tried to install boost-module but then I experienced the following error message:

Error: Building packages bzip2:x86-windows failed with: BUILD_FAILED

Package: bzip2:x86-windows
Vcpkg version: 2020.06.15-nohash

What does this mean and what can I do about it?
Any Idea why the boost-any module is not available in visual studio after installing it?

Thanks a lot.

**Comment by PhoebeHui** [comment]
@NewcomerBS, does the vcpkg path with a space? if so, please create a clone without space in vcpkg path, it looks same issue with #13103, and would fix by PR #13126.

**Comment by NewcomerBS** [comment]
Hi PhoebeHui
Thanks for that suggestion. I'll check this out in a moment...
Best

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/13103, and please reopen this issue if it's a different issue.
