### ISSUE TITLE
[<intel-mkl>] build failure

### ISSUE THREAD

**Issue by rockydut** [microsoft/vcpkg#13651]
**Host Environment**
- OS:  windows
- Compiler: visual studio 2019

**To Reproduce**
`./vcpkg install intel-mkl:x64-windows-static

**Failure logs** 
PS D:\vcpkg> ./vcpkg install intel-mkl:x64-windows-static
Computing installation plan...
The following packages will be built and installed:
    intel-mkl[core]:x64-windows-static
Detecting compiler hash for triplet x64-windows-static...
Starting package 1/1: intel-mkl:x64-windows-static
Building package intel-mkl[core]:x64-windows-static...
Could not locate cached archive: C:\Users\tang\AppData\Local\vcpkg\archives\88\8841d97f465e29d6f62b9b16d035945721e7ab66.zip
CMake Error at ports/intel-mkl/portfile.cmake:16 (message):
  Could not find MKL.  Before continuing, please download and install MKL
  (20200000 or higher) from:

      https://registrationcenter.intel.com/en/products/download/3178/

  Also ensure vcpkg has been rebuilt with the latest version (v0.0.104 or
  later)
Call Stack (most recent call first):
  scripts/ports.cmake:79 (include)

Error: Building package intel-mkl:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: intel-mkl:x64-windows-static
  Vcpkg version: 2020.06.15-nohash

**Additional context**
I installed the intel parallel studio in "D:\IntelSWTools", however, the default locatioin in ports/iintel-mkl/portfile.cmake is set(INTEL_ROOT $ENV{${ProgramFilesx86}}/IntelSWTools/compilers_and_libraries/windows).
Even I set it to : set(INTEL_ROOT D/IntelSWTools/compilers_and_libraries/windows)
compiling is still error.

**Comment by JonLiu1993** [comment]
Hi @rockydut! 
I tried to use your modification method to modify the portfile file, but the result is the same as you, I can’t find the installed MKL. I am curious why you don’t install it directly under the C drive. I installed it on the C drive and can successfully install intel-mkl :x64-windows-static, I looked at the portfile file, it seems to look for it in the C drive file by default.
````
PS F:\test4\vcpkg> ./vcpkg install intel-mkl:x64-windows-static
Computing installation plan...
The following packages will be built and installed:
    intel-mkl[core]:x64-windows-static
Detecting compiler hash for triplet x64-windows-static...
Starting package 1/1: intel-mkl:x64-windows-static
Building package intel-mkl[core]:x64-windows-static...
Using cached binary package: C:\Users\vzhli17\AppData\Local\vcpkg\archives\de\dee7e480e14f1f81ff55caec35b77e9b3b3f8c42.zip
Building package intel-mkl[core]:x64-windows-static... done
Installing package intel-mkl[core]:x64-windows-static...
Installing package intel-mkl[core]:x64-windows-static... done
Elapsed time for package intel-mkl:x64-windows-static: 263.1 ms
````

**Comment by JonLiu1993** [comment]
@rockydut ,can you try this?
Modify VCPKG_ROOT/ports/intel-mkl/portfile.cmake line 10, from
````
set(INTEL_ROOT $ENV{${ProgramFilesx86}}/IntelSWTools/compilers_and_libraries/windows)
to
set(INTEL_ROOT ${YOUR_MKI_INSTALLED_ROOT}/IntelSWTools/compilers_and_libraries/windows)
````

**Comment by JonLiu1993** [comment]
I'm closing this issue for now since there is no response.

Please feel free to reopen this if it is still a problem for you.
