### ISSUE TITLE
[New Port Request] <mumps>

### ISSUE THREAD

**Issue by rockydut** [microsoft/vcpkg#13652]
Library name: mumps

Library description: MUMPS is a solver for sparse system of linear equations A x = b.

Source repository URL: https://github.com/scivision/mumps

Project homepage (if different from the source repository): http://mumps.enseeiht.fr/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
It is a fast sover for linear equations, which is better than suitesparse. The linear equation solver is very useful for numerical simulation such as finite element method.

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now
