### ISSUE TITLE
CMake manifests integration: custom installation location

### ISSUE THREAD

**Issue by nickaleks** [microsoft/vcpkg#13656]
Currently, when using CMake along with the manifest file, dependencies are installed inside build directory. If you have more than one configuration (for example, one for debug, one for release), all dependencies are duplicated in each directory. Moreover, each dependency contains both debug and release build, so we end up building all the dependencies twice for each build configuration. 

is there a way to provide a single location for all CMake builds? Just running `vcpkg install` in a project root does produce vcpkg_installed, but CMake ignores that and creates additional directory inside a build dir anyway.

**Comment by Neumann-A** [comment]
`set(_VCPKG_INSTALLED_DIR yourdir)` before the very first `project` call

**Comment by nickaleks** [comment]
> `set(_VCPKG_INSTALLED_DIR yourdir)` before the very first `project` call

Cool, that seems to work.
