### ISSUE TITLE
[freeimage] link failure

### ISSUE THREAD

**Issue by TheReclif** [microsoft/vcpkg#13670]
**Host Environment**
- OS: Ubuntu 20.04 LTS (WSL)
- Compiler: GNU 9.3.0

**To Reproduce**
`./vcpkg install freeimage`
Create CMakeLists.txt:
```cmake
cmake_minimum_required(VERSION 3.13)
project (FreeImageTest)

add_library(Test SHARED "")

find_package(freeimage CONFIG REQUIRED)
target_link_libraries(Test PRIVATE freeimage::FreeImage)
target_sources(Test PRIVATE Main.cpp)
```
Main.cpp:
```cpp
#include <FreeImage.h>

void foo()
{
	FreeImage_Initialise(0);
}
```
Configure and build using cmake.
**Failure logs** 
ld failed during linking stage:
```
/usr/bin/ld: /mnt/d/TheReclif/Linux/vcpkg/installed/x64-linux/lib/libtiff.a(tif_unix.c.o):(.data.rel.local+0x0): multiple definition of `_TIFFerrorHandler'; /mnt/d/TheReclif/Linux/vcpkg/installed/x64-linux/debug/lib/libFreeImaged.a(PluginTIFF.cpp.o):/mnt/d/TheReclif/Linux/vcpkg/buildtrees/freeimage/src/9d9cc7e2d5-2288df34d2.clean/Source/FreeImage/PluginTIFF.cpp:276: first defined here
/usr/bin/ld: /mnt/d/TheReclif/Linux/vcpkg/installed/x64-linux/lib/libtiff.a(tif_unix.c.o):(.data.rel.local+0x8): multiple definition of `_TIFFwarningHandler'; /mnt/d/TheReclif/Linux/vcpkg/installed/x64-linux/debug/lib/libFreeImaged.a(PluginTIFF.cpp.o):/mnt/d/TheReclif/Linux/vcpkg/buildtrees/freeimage/src/9d9cc7e2d5-2288df34d2.clean/Source/FreeImage/PluginTIFF.cpp:261: first defined here
```
**Additional context**
The problem is caused by linking to the FreeImage and libTIFF libraries at the same time and renders FreeImage unusable. Specifically, it's caused by FreeImage redefining libTIFF's warning and error handlers (lines 261 and 276 in PluginTIFF.cpp, FreeImage's source code). It can be temporarily fixed by removing link commands for libtiff.a in generated makefiles. Proposed solution: don't propagate the libTIFF link dependency from FreeImage's cmake file if that's possible.

**Comment by LilyWangL** [comment]
@TheReclif  Thanks for posting this issue. Could you please submit a PR to fix this issue?

**Comment by TheReclif** [comment]
Sure thing.
