### ISSUE TITLE
VCPKG and PCL

### ISSUE THREAD

**Issue by petrasvestartas** [microsoft/vcpkg#13686]
Hi,

I am totally new to **PCL** and **VCPKG**.

I typed the line and waiting for until it finishes:
`C:\src\vcpkg\vcpkg>.\vcpkg\vcpkg install pcl[openni2,qt,pcap]:x64-windows --featurepackages`

Could someone guide me through the process how to do the other steps to build a simple pcl project file?
I am totally new to this.

**Comment by PhoebeHui** [comment]
Hi @petrasvestartas, vcpkg provide the pcl libraries to users after it installed, so you can referenece it directly if your project depends on it, see the following docs for a start:
https://github.com/microsoft/vcpkg/blob/master/docs/examples/installing-and-using-packages.md
https://github.com/microsoft/vcpkg/blob/master/docs/users/integration.md
