### ISSUE TITLE
[nanodbc] build failure x64-linux openSUSE Leap 15.2 WSL2/Hyper-V

### ISSUE THREAD

**Issue by StarGate-One** [microsoft/vcpkg#13694]
**Host Environment**
- OS: [openSUSE Leap 15.2 running in WSL2 and Hyper-V on Microsoft Windows [Version 10.0.19041.508]]
- Compiler: gcc (SUSE Linux) 9.3.1 20200406 [revision 6db837a5288ee3ca5ec504fbd5a765817e556ac2]

**To Reproduce**

**The results are the same for separate vcpkg instances running on openSUSE Leap 15.2 within WSL2 and Hyper-V instances.**
1. `git pull`
2. commit #13662 https://github.com/microsoft/vcpkg/pull/13662/commits/d056a07cc209173d3573a299823c036d53b9a7a2 is applied and updates master
3. `./bootstrap-vcpkg.sh --disableMetrics` as `git pull` adds/changes some `[vcpkg-root]\toolsrc\` source files:
` toolsrc/include/vcpkg/base/files.h          |   4 ++`
` toolsrc/src/vcpkg-test/files.cpp            |  56 +++++++++++++++++++++`
` toolsrc/src/vcpkg/base/files.cpp            | 180 +++++++`
` toolsrc/src/vcpkg/vcpkgpaths.cpp            |  24 +++------ `
4. `./vcpkg remove nanodbc` (because vcpkg does not honor --editable from previous install or is it allowed with `./vcpkg upgrade --no-dry-run`
5. `rm -rf [vcpkg-root]/buildtrees/nanodbc` as a new version is available
6. `/vcpkg install nanodbc --editable`
 See console output below...

**Failure logs** 
- Cut and past the appropriate build messages from the console output.
`>$ vcpkg install nanodbc`
`Computing installation plan...`
`The following packages will be built and installed:`
`    nanodbc[core]:x64-linux`
`Detecting compiler hash for triplet x64-linux...`
`Starting package 1/1: nanodbc:x64-linux`
`Building package nanodbc[core]:x64-linux...`
`-- Downloading https://github.com/nanodbc/nanodbc/archive/7404a4dd7697e188df5724ab95a7553d2fc404eb.tar.gz...`
`-- Extracting source /home/ac-130h/git/vcpkg/downloads/nanodbc-nanodbc-7404a4dd7697e188df5724ab95a7553d2fc404eb.tar.gz`
`-- Using source at /home/ac-130h/git/vcpkg/buildtrees/nanodbc/src/3d2fc404eb-bbd91892af.clean`
`-- Configuring x64-linux-dbg`
`-- Configuring x64-linux-rel`
`-- Building x64-linux-dbg`
`-- Building x64-linux-rel`
`-- Installing: /home/ac-130h/git/vcpkg/packages/nanodbc_x64-linux/share/nanodbc/copyright`
`-- Performing post-build validation`
`The /lib/cmake folder should be merged with /debug/lib/cmake and moved to /share/nanodbc/cmake.`
`Please use the helper function vcpkg_fixup_cmake_targets()`
`The following cmake files were found outside /share/nanodbc. Please place cmake files in /share/nanodbc.`

`    /home/ac-130h/git/vcpkg/packages/nanodbc_x64-linux/lib/cmake/nanodbc/nanodbc-config-release.cmake`
`    /home/ac-130h/git/vcpkg/packages/nanodbc_x64-linux/lib/cmake/nanodbc/nanodbc-config.cmake`
`    /home/ac-130h/git/vcpkg/packages/nanodbc_x64-linux/debug/lib/cmake/nanodbc/nanodbc-config.cmake`
`    /home/ac-130h/git/vcpkg/packages/nanodbc_x64-linux/debug/lib/cmake/nanodbc/nanodbc-config-debug.cmake`

`The /debug/lib/cmake folder should be merged with /lib/cmake into /share/nanodbc`
`Found 3 error(s). Please correct the portfile:`
`    /home/ac-130h/git/vcpkg/ports/nanodbc/portfile.cmake`
`-- Performing post-build validation done`
`Error: Building package nanodbc:x64-linux failed with: POST_BUILD_CHECKS_FAILED`
`Please ensure you're using the latest portfiles with ./vcpkg update, then`
`submit an issue at https://github.com/Microsoft/vcpkg/issues including:`
`  Package: nanodbc:x64-linux`
`  Vcpkg version: 2020.06.15-unknownhash`

`Additionally, attach any relevant sections from the log files above.`

- Please attach any additional failure logs mentioned in the console output.
None

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by JackBoosY** [comment]
Please add `vcpkg_fixup_cmake_targets(CONFIG_PATH lib/cmake)` to _VCPKG_ROOT/ports/nanodbc/portfile.cmake_ line 28 and try again.

Thanks.

**Comment by StarGate-One** [comment]
@JackBoosY Thank you. Worked.
