### ISSUE TITLE
I want to specify a downloader for VCPKG. What should I do

### ISSUE THREAD

**Issue by limi-go** [microsoft/vcpkg#13690]
I want to specify a downloader for VCPKG. What should I do

**Comment by StarGate-One** [comment]
If you want to use aria2c in place of the OS default download method, then add this to the line:
`vcpkg install --x-use-aria2 [port] [port]`  etc.
Other than that you would most likely need to rewrite the source code.
Note: the `vcpkg upgrade --no-dry-run` has no --x-use-aria2 option so the OS will use its default download method...

**Comment by JackBoosY** [comment]
Related: #12532 #13639

**Comment by PhoebeHui** [comment]
Please reference to SGO's suggestion.
