### ISSUE TITLE
[libtorrent] update to 2.0

### ISSUE THREAD

**Issue by maxim20002000** [microsoft/vcpkg#13702]
Library name:
**libtorrent**
New version number:
**2.0**
Other information that may be useful (release notes, etc...)
_https://github.com/arvidn/libtorrent/releases_

**Comment by JonLiu1993** [comment]
Relate to #7372

**Comment by JonLiu1993** [comment]
Relate to #14755,libtorrent-2.0 shouldn't be considered as update for this port.  Should add another port for it (aka libtorrent2) and keep this one for 1.2.x.
