### ISSUE TITLE
--x-install-root does not create intermediate directories

### ISSUE THREAD

**Issue by gergondet** [microsoft/vcpkg#13716]
**Describe the bug**

When running vcpkg install in manifest mode with `--x-install-root` specified, vcpkg will not create intermediate directories if needed.

**Environment**
- OS: Linux (I did not check if it also happens on macOS and Windows)
- Compiler: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

**To Reproduce**
1. Have a valid manifest file with some dependencies (e.g. eigen3 and fmt)
2. ./vcpkg install --feature-flags='manifests,binarycaching' --x-install-root=$(pwd)/build/vcpkg_installed
3. See failure logs

It works fine if the build directory already exists

**Expected behavior**
I think vcpkg should either create the intermediary directory or fail early with a more explicit message

**Failure logs** 
```
Detecting compiler hash for triplet x64-linux...
The following packages will be built and installed:
    eigen3[core]:x64-linux
    fmt[core]:x64-linux
Starting package 1/2: eigen3:x64-linux
Building package eigen3[core]:x64-linux...
Using cached binary package: $HOME/.cache/vcpkg/archives/ee/ee61fb311fc3f626e29965b9904dbdc65badc404.zip
Building package eigen3[core]:x64-linux... done
Installing package eigen3[core]:x64-linux...
error writing file: $CURRENT_FOLDER/build/vcpkg_installed/vcpkg/updates/incomplete: Operation not permitted
```

Thanks

**Comment by PhoebeHui** [comment]
@strega-nil, could you help have a look?

**Comment by strega-nil** [comment]
I don't know if this is something that we want... cc @ras0219, any opinions?

**Comment by BillyONeal** [comment]
I note that `--x-install-root` is explicitly an `--x-` switch because we haven't considered all cases like this outside of our own CI validation process, wherein this is not necessary. We try to avoid doing unnecessary `create_directories` because that is fairly expensive (it showed up when I profiled anyway). We could make `install` create the install folder once before going though....

@gregondet Can you better describe the end scenario you're trying to solve with `--x-install-root` here?

**Comment by gergondet** [comment]
@BillyONeal Sure, this is also a CI scenario. I'm using a manifest file to get my dependencies using vcpkg. Normally I would let the cmake integration handle the `vcpk install` part but I wanted to get the debug information. So I now run `VCPKG_FEATURE_FLAGS="manifests,binary-caching" ./vcpkg install --debug --x-install-root=build/vcpkg_installed` before running cmake. It's definitely not a big deal because I can (and do) create the directory before but it definitely surprised me when I stumbled upon the issue.

**Comment by gergondet** [comment]
> That's a description of what you're doing but not why. Is the location manifests place the dependencies a problem for some reason? That kind of stuff should be part of the manifest somehow, not reliance on an intentionally-not-supported --x- switch.

Sorry if it was unclear.

"Normally I would let the cmake integration handle the vcpk install part but I wanted to get the debug information"

My objective was to get the debug information from vcpkg because I wanted to figure out what I had done wrong in setting up binary caching. I think down the line this will be achievable in a nicer way (from a discussion in #vcpkg on the #include discord). There might have been a better way to achieve this but using `--x-install-root` is what I stumbled upon first.

`build` is the directory where I will run cmake later so vcpkg will end up putting my dependencies in `build/vcpkg_installed`, it's not really special.

> an intentionally-not-supported --x- switch

On a side-note, are all `--x-` commands unsupported? They are listed as (Experimental) in the help message but that doesn't necessarily say "unsupported" to me but rather "might be broken/might change/use at your own risk"

**Comment by strega-nil** [comment]
> They are listed as (Experimental) in the help message but that doesn't necessarily say "unsupported" to me but rather "might be broken/might change/use at your own risk"

This is what unsupported means (at least to us) 😄 

Also, probably the best way right now is to `mkdir build` before `vcpkg install`ing, unfortunately. This isn't a thing we have supported just yet.

**Comment by BillyONeal** [comment]
>There might have been a better way to achieve this but using --x-install-root is what I stumbled upon first.

To clarify, I'm fishing for a gap in our official support that we need to close for you, not admonishing you here.

>build is the directory where I will run cmake later so vcpkg will end up putting my dependencies in build/vcpkg_installed, it's not really special.

I mean like, is there a specific reason you needed to rename this or is it just personal preference?

**Comment by gergondet** [comment]
> Also, probably the best way right now is to mkdir build before vcpkg installing, unfortunately. This isn't a thing we have supported just yet.

This is what I ended up doing, so the issue is definitely not a big deal :)

> I mean like, is there a specific reason you needed to rename this or is it just personal preference?

I'm not sure I follow you here, in my mind I'm not trying to rename anything, I'm just trying to emulate the install command that vcpkg's cmake toolchain will do for me if I run cmake from the build folder without running `vcpkg install` first.

In the normal scenario, I have a manifest in my source folder, I create a build directory to run cmake, the vcpkg toolchain picks up on the manifest, runs `vcpkg install` which puts everything in `vcpkg_installed` in the current folder (or in `build/vcpkg_installed` from my source folder). After the install, it will work on the assumption that things have been installed there.

I'm completely fine with this scenario but I also want to append `--debug` to the `vcpkg install` command. It is not possible atm so I am faced with using one of two unsupported options:
- run `vcpkg install` from my source folder with `--x-install-root`
- run `vcpkg install` from my build folder with `--x-manifest-root` (and this option is hidden)

Then when cmake runs in the build folder, `vcpkg install` has no extra work to do because the folder is already correctly populated.

(And now that I think about it, I could have added the flag in the toolchain)
