### ISSUE TITLE
[New Port Request] openvino inference-engine

### ISSUE THREAD

**Issue by xandox** [microsoft/vcpkg#13717]
Library name: 
openvino inference-engine

Library description: 
OpenVINO™ Toolkit - Deep Learning Deployment Toolkit repository

Source repository URL:
https://github.com/openvinotoolkit/openvino

Project homepage (if different from the source repository):
https://01.org/openvinotoolkit

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
It has different computation backend plugins. Thay could be features

**Comment by Cheney-W** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by x-bruce** [comment]
Still not added since more than 2 years past?

**Comment by artanokhov** [comment]
https://github.com/microsoft/vcpkg/blob/master/ports/openvino/vcpkg.json
