### ISSUE TITLE
[libtins] update to 4.3

### ISSUE THREAD

**Issue by cnbatch** [microsoft/vcpkg#13718]
Library name: libtins

New version number: 4.3

Other information that may be useful (release notes, etc...)

You can and you should update the version to 4.3, it's not difficult.

I'm not going to update it because I tried but someone [implies](https://github.com/microsoft/vcpkg/pull/13681) me C++11 is equal to C11. I don't know how to response to it. But I've commented.

**Comment by JonLiu1993** [comment]
Duplicate to [#13681 ](https://github.com/microsoft/vcpkg/pull/13681)
