### ISSUE TITLE
[vcpkg] allow non-existent paths in --overlay-ports and --overlay-triplets

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#13714]
Just as the title says. I have configured the corresponding environment variables with relative paths. (e.g. script/test_ports)
The problem is that this breaks manifest support since vcpkg is executed from a different path.

**Comment by strega-nil** [comment]
I feel like we shouldn't allow relative paths in overlay ports and overlay triplets, for exactly this reason. @ras0219, thoughts?

**Comment by vicroms** [comment]
Relative paths should be allowed in command line but not in environment variables.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
