### ISSUE TITLE
ogre update to 1.12.9

### ISSUE THREAD

**Issue by shybovycha** [microsoft/vcpkg#13712]
Library name: ogre

New version number: 1.12.9

Other information that may be useful (release notes, etc...): two of the **very** hot features include multi-language GPU programs and assimp plugin allowing to skip the conversion of all the meshes to the OGRE `.mesh` format. Release notes: https://www.ogre3d.org/2020/09/20/ogre-1-12-9-released

**Comment by longhuan2018** [comment]
Try this PR #14006

**Comment by traversaro** [comment]
I guess this was fixed by https://github.com/microsoft/vcpkg/pull/14006 .

**Comment by JonLiu1993** [comment]
@traversaro @longhuan2018 ,Thanks for your contribution
