### ISSUE TITLE
Building package eigen3 failed

### ISSUE THREAD

**Issue by twMr7** [Microsoft/vcpkg#1372]
> -- CURRENT_INSTALLED_DIR=C:/RnD/vcpkg/installed/x64-windows
-- DOWNLOADS=C:/RnD/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/RnD/vcpkg/packages/eigen3_x64-windows
-- CURRENT_BUILDTREES_DIR=C:/RnD/vcpkg/buildtrees/eigen3
-- CURRENT_PORT_DIR=C:/RnD/vcpkg/ports/eigen3/.
-- Using cached C:/RnD/vcpkg/downloads/eigen-3.3.3.tar.bz2
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Configuring x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:43 (message):
    Command failed: C:/RnD/cmake/bin/cmake.exe;C:/RnD/vcpkg/buildtrees/eigen3/src/eigen-eigen-67e894c6cd8f;-DBUILD_SHARED_LIBS=ON;-DVCPKG_TARGET_TRIPLET=x64-windows;-DCMAKE_CXX_FLAGS= /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP ;-DCMAKE_C_FLAGS= /DWIN32 /D_WINDOWS /W3 /utf-8 /MP ;-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON;-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE;-DCMAKE_VERBOSE_MAKEFILE=ON;-DVCPKG_APPLOCAL_DEPS=OFF;-DCMAKE_TOOLCHAIN_FILE=C:/RnD/vcpkg/scripts/buildsystems/vcpkg.cmake;-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON;-DCMAKEPACKAGE_INSTALL_DIR=C:/RnD/vcpkg/packages/eigen3_x64-windows/share/eigen3;-DCMAKE_CXX_FLAGS_RELEASE=/MD /O2 /Oi /Gy /DNDEBUG /Zi ;-DCMAKE_C_FLAGS_RELEASE=/MD /O2 /Oi /Gy /DNDEBUG /Zi ;-DCMAKE_SHARED_LINKER_FLAGS_RELEASE=/DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF ;-DCMAKE_EXE_LINKER_FLAGS_RELEASE=/DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF ;-G;Ninja;-DCMAKE_BUILD_TYPE=Release;-DCMAKE_INSTALL_PREFIX=C:/RnD/vcpkg/packages/eigen3_x64-windows
    Working Directory: C:/RnD/vcpkg/buildtrees/eigen3/x64-windows-rel
    See logs for more information:
      C:\RnD\vcpkg\buildtrees\eigen3\config-x64-windows-rel-out.log
      C:\RnD\vcpkg\buildtrees\eigen3\config-x64-windows-rel-err.log
Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:170 (vcpkg_execute_required_process)
  ports/eigen3/portfile.cmake:11 (vcpkg_configure_cmake)
  scripts/ports.cmake:73 (include)

Is it really necessary to build a header only library?

[config-x64-windows-rel-err.zip](https://github.com/Microsoft/vcpkg/files/1112185/config-x64-windows-rel-err.zip)

**Comment by twMr7** [comment]
Package: both eigen3:x64-windows and eigen3:x86-windows failed
Vcpkg version: 0.0.81-6aae6ca3c0384d23c901e80cfbd46ed32a29321d

**Comment by ras0219-msft** [comment]
Thanks for reporting this issue.

**Comment by twMr7** [comment]
The problem has gone after deleting the entire buildtrees\eigen3 directory. I was updating the port from 3.3.3 to the latest 3.3.3-3, so I try to reproduce the problem:
1. delete the entire buildtrees/eigen3 again
2. recover the portfile.cmake from 3.3.3
3. vcpkg install eigen3
4. vcpkg remove eigen3
5. replace the portfile.cmake from 3.3.3-3
6. vcpkg install eigen3

and the same problem occurs again.

**Comment by twMr7** [comment]
Forgot to mention that extract-out.log and extract-err.log are all empty all the way.

**Comment by twMr7** [comment]
Ah oh, now I have to include headers from `<eigen3/Eigen/Core>` since 3.3.3-3, if I install eigen3 correctly.  This will definitely break many, many codes. The convention Eigen codes around is to include from <Eigen/Core>.

**Comment by Voskrese** [comment]
@twMr7 
mklink /D "c:\mklink" "d:\mkfolder"
```
mklink /D  ".../.../eigen3/Eigen" ".../.../Eigen"
```

**Comment by twMr7** [comment]
yes, both symbolic link or junction will do, but how to make the link from portfile.cmake?

**Comment by ras0219-msft** [comment]
I think in this case we should probably just install the files to both directories. This does unfortunately double the number of installed files, but in the larger scheme of things Eigen isn't _that_ big of a library.

**Comment by twMr7** [comment]
Installing to both directories is ok to workaround the problem now.

However, please consider to implement some feature like `alternatives` command on Linux.  Maintaining the symbolic links is a approach not only solve the installation problem, but we can also get to install different version of the same library.

**Comment by twMr7** [comment]
Please review attached portfile.cmake, I'll make a PR if the changes are ok.
[portfile.zip](https://github.com/Microsoft/vcpkg/files/1120014/portfile.zip)

Changes:
1. Copy additional Eigen directory into include directory
2. Update Eigen to version 3.3.4

I did try to make a symbolic link once:
```
vcpkg_execute_required_process(
    COMMAND powershell -NoProfile -NoLogo -Command "& {New-Item -ItemType SymbolicLink -Name Eigen -Target eigen3/Eigen}"
    WORKING_DIRECTORY "${CURRENT_PACKAGES_DIR}/include"
    LOGNAME package-${TARGET_TRIPLET}
)
```
but the symbolic link become regular directory after installing to `installed` directory, so I fall back to use `file(COPY ${SOURCE_PATH}/Eigen DESTINATION ${CURRENT_PACKAGES_DIR}/include` instead.

**Comment by twMr7** [comment]
I think I better take two steps, the PR #1413 fix this issue only, since the missing CMakeLists.txt problem is likely to happen in version 3.3.3 only.

I will make another PR to update eigen3 to version 3.3.4 without checking for the existence of CMakeLists.txt.
