### ISSUE TITLE
[libpq] x86-windows-static build failure

### ISSUE THREAD

**Issue by gooxion** [microsoft/vcpkg#13726]
install libpq[core]:x86-windows-static with visual studio 2017 community failure:
```
H:\vcpkg>vcpkg install libpq[core]:x86-windows-static
Computing installation plan...
The following packages will be built and installed:
    libpq[core]:x86-windows-static
Warning: The following VS instances are excluded because the English language pack is unavailable.
    D:\Programs\Microsoft Visual Studio 12.0\
Please install the English language pack.
Detecting compiler hash for triplet x86-windows-static...
Starting package 1/1: libpq:x86-windows-static
Building package libpq[core]:x86-windows-static...
Could not locate cached archive: C:\Users\jiayi\AppData\Local\vcpkg\archives\c1\c11bd032889f4a5fdd7afa83858ebc2f3e4e7b1a.zip
-- Using community triplet x86-windows-static. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: H:\vcpkg\triplets\community\x86-windows-static.cmake
-- Using cached H:/vcpkg/downloads/postgresql-12.2.tar.bz2
-- Cleaning sources at H:/vcpkg/buildtrees/libpq/src/tgresql-12-c19559b5c2.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source H:/vcpkg/downloads/postgresql-12.2.tar.bz2
-- Applying patch patches/windows/install.patch
-- Applying patch patches/windows/win_bison_flex.patch
-- Applying patch patches/windows/openssl_exe_path.patch
-- Applying patch patches/windows/Solution.patch
-- Applying patch patches/windows/MSBuildProject_fix_gendef_perl.patch
-- Applying patch patches/windows/msgfmt.patch
-- Applying patch patches/windows/python_lib.patch
-- Applying patch patches/linux/configure.patch
-- Applying patch patches/windows/MSBuildProject-static-lib.patch
-- Applying patch patches/windows/Mkvcbuild-static-lib.patch
-- Applying patch patches/windows/MSBuildProject-static-crt.patch
-- Applying patch patches/windows/minimize_install.patch
-- Using source at H:/vcpkg/buildtrees/libpq/src/tgresql-12-c19559b5c2.clean
-- Copying libpq source files to H:/vcpkg/buildtrees/libpq/x86-windows-static-rel...
-- Copying libpq source files... done
-- Applying patch patches/windows/Solution_RELEASE.patch
-- Applying patch patches/windows/python3_build_RELEASE.patch
-- Patches applied!
-- Building libpq x86-windows-static-RELEASE...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:85 (message):
    Command failed: H:/vcpkg/downloads/tools/perl/5.30.0.1/perl/bin/perl.exe build.pl RELEASE libpq
    Working Directory: H:/vcpkg/buildtrees/libpq/x86-windows-static-rel/src/tools/msvc
    Error code: 1
    See logs for more information:
      H:\vcpkg\buildtrees\libpq\build-libpq-x86-windows-static-RELEASE-out.log

Call Stack (most recent call first):
  ports/libpq/portfile.cmake:215 (vcpkg_execute_required_process)
  scripts/ports.cmake:79 (include)


Error: Building package libpq:x86-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libpq:x86-windows-static
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.
```

**Comment by JackBoosY** [comment]
Please provide _H:\vcpkg\buildtrees\libpq\build-libpq-x86-windows-static-RELEASE-out.log_.

**Comment by gooxion** [comment]
> Please provide _H:\vcpkg\buildtrees\libpq\build-libpq-x86-windows-static-RELEASE-out.log_.

cl output Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27043 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

usage: cl [ option... ] filename... [ /link linkoption... ]
.Detected hardware platform: Win32
Generating win32ver.rc for src/backend
Generating win32ver.rc for src/timezone
Generating win32ver.rc for src/backend/snowball
Generating win32ver.rc for src/pl/plpgsql/src
Generating win32ver.rc for src/backend/replication/libpqwalreceiver
Generating win32ver.rc for src/backend/replication/pgoutput
Generating win32ver.rc for src/interfaces/ecpg/pgtypeslib
Generating win32ver.rc for src/interfaces/ecpg/ecpglib
Generating win32ver.rc for src/interfaces/ecpg/compatlib
Generating win32ver.rc for src/interfaces/ecpg/preproc
Generating win32ver.rc for src/interfaces/ecpg/test
Generating win32ver.rc for src/test/isolation
Generating win32ver.rc for src/bin/initdb
Generating win32ver.rc for src/bin/pgbench
Files src/bin/pgbench/exprscan.l
Files src/bin/pgbench/exprparse.y
Generating win32ver.rc for src/bin/pg_archivecleanup
Generating win32ver.rc for src/bin/pg_checksums
Generating win32ver.rc for src/bin/pg_config
Generating win32ver.rc for src/bin/pg_controldata
Generating win32ver.rc for src/bin/pg_ctl
Generating win32ver.rc for src/bin/pg_resetwal
Generating win32ver.rc for src/bin/pg_test_fsync
Generating win32ver.rc for src/bin/pg_test_timing
Generating win32ver.rc for src/bin/pg_upgrade
Generating win32ver.rc for src/bin/psql
Files src/bin/psql/psqlscanslash.l
Generating win32ver.rc for src/bin/pg_basebackup
Generating win32ver.rc for src/bin/pg_rewind
Generating win32ver.rc for src/bin/pgevent
Generating win32ver.rc for src/bin/pg_dump
Generating win32ver.rc for contrib/pgcrypto
Generating win32ver.rc for contrib/adminpack
Generating win32ver.rc for contrib/amcheck
Generating win32ver.rc for contrib/auth_delay
Generating win32ver.rc for contrib/auto_explain
Generating win32ver.rc for contrib/bloom
Generating win32ver.rc for contrib/btree_gin
Generating win32ver.rc for contrib/btree_gist
Generating win32ver.rc for contrib/citext
Generating win32ver.rc for contrib/cube
Files contrib/cube/cubescan.l
Files contrib/cube/cubeparse.y
Generating win32ver.rc for contrib/dblink
Generating win32ver.rc for contrib/dict_int
Generating win32ver.rc for contrib/dict_xsyn
Generating win32ver.rc for contrib/earthdistance
Generating win32ver.rc for contrib/file_fdw
Generating win32ver.rc for contrib/fuzzystrmatch
Generating win32ver.rc for contrib/hstore
Generating win32ver.rc for contrib/intarray
Generating win32ver.rc for contrib/isn
Generating win32ver.rc for contrib/lo
Generating win32ver.rc for contrib/ltree
Generating win32ver.rc for contrib/oid2name
Generating win32ver.rc for contrib/pageinspect
Generating win32ver.rc for contrib/passwordcheck
Generating win32ver.rc for contrib/pgrowlocks
Generating win32ver.rc for contrib/pgstattuple
Generating win32ver.rc for contrib/pg_buffercache
Generating win32ver.rc for contrib/pg_freespacemap
Generating win32ver.rc for contrib/pg_prewarm
Generating win32ver.rc for contrib/pg_standby
Generating win32ver.rc for contrib/pg_stat_statements
Generating win32ver.rc for contrib/pg_trgm
Generating win32ver.rc for contrib/pg_visibility
Generating win32ver.rc for contrib/postgres_fdw
Generating win32ver.rc for contrib/seg
Files contrib/seg/segscan.l
Files contrib/seg/segparse.y
Generating win32ver.rc for contrib/spi
Generating win32ver.rc for contrib/tablefunc
Generating win32ver.rc for contrib/tcn
Generating win32ver.rc for contrib/test_decoding
Generating win32ver.rc for contrib/tsm_system_rows
Generating win32ver.rc for contrib/tsm_system_time
Generating win32ver.rc for contrib/unaccent
Generating win32ver.rc for contrib/vacuumlo
Generating win32ver.rc for src/test/modules/dummy_seclabel
Generating win32ver.rc for src/test/modules/test_bloomfilter
Generating win32ver.rc for src/test/modules/test_ddl_deparse
Generating win32ver.rc for src/test/modules/test_integerset
Generating win32ver.rc for src/test/modules/test_parser
Generating win32ver.rc for src/test/modules/test_predtest
Generating win32ver.rc for src/test/modules/test_rbtree
Generating win32ver.rc for src/test/modules/test_rls_hooks
Generating win32ver.rc for src/test/modules/test_shm_mq
Generating win32ver.rc for src/test/modules/worker_spi
Generating win32ver.rc for src/backend/utils/mb/conversion_procs/ascii_and_mic
Generating win32ver.rc for src/backend/utils/mb/conversion_procs/cyrillic_and_mic
Generating win32ver.rc for src/backend/utils/mb/conversion_procs/euc_cn_and_mic
Generating win32ver.rc for src/backend/utils/mb/conversion_procs/euc_jp_and_sjis
Generating win32ver.rc for src/backend/utils/mb/conversion_procs/euc_kr_and_mic
Generating win32ver.rc for src/backend/utils/mb/conversion_procs/euc_tw_and_big5
Generating win32ver.rc for src/backend/utils/mb/conversion_procs/latin2_and_win1250
Generating win32ver.rc for src/backend/utils/mb/conversion_procs/latin_and_mic
Generating win32ver.rc for src/backend/utils/mb/conversion_procs/utf8_and_ascii
Generating win32ver.rc for src/backend/utils/mb/conversion_procs/utf8_and_big5
Generating win32ver.rc for src/backend/utils/mb/conversion_procs/utf8_and_cyrillic
Generating win32ver.rc for src/backend/utils/mb/conversion_procs/utf8_and_euc_cn
Generating win32ver.rc for src/backend/utils/mb/conversion_procs/utf8_and_euc_jp
Generating win32ver.rc for src/backend/utils/mb/conversion_procs/utf8_and_euc_kr
Generating win32ver.rc for src/backend/utils/mb/conversion_procs/utf8_and_euc_tw
Generating win32ver.rc for src/backend/utils/mb/conversion_procs/utf8_and_gb18030
Generating win32ver.rc for src/backend/utils/mb/conversion_procs/utf8_and_gbk
Generating win32ver.rc for src/backend/utils/mb/conversion_procs/utf8_and_iso8859
Generating win32ver.rc for src/backend/utils/mb/conversion_procs/utf8_and_iso8859_1
Generating win32ver.rc for src/backend/utils/mb/conversion_procs/utf8_and_johab
Generating win32ver.rc for src/backend/utils/mb/conversion_procs/utf8_and_sjis
Generating win32ver.rc for src/backend/utils/mb/conversion_procs/utf8_and_win
Generating win32ver.rc for src/backend/utils/mb/conversion_procs/utf8_and_uhc
Generating win32ver.rc for src/backend/utils/mb/conversion_procs/utf8_and_euc2004
Generating win32ver.rc for src/backend/utils/mb/conversion_procs/utf8_and_sjis2004
Generating win32ver.rc for src/backend/utils/mb/conversion_procs/euc2004_sjis2004
Generating win32ver.rc for src/bin/scripts
Generating win32ver.rc for src/test/regress
Generating win32ver.rc for src/bin/pg_waldump
Copying pg_config_os.h...
Generating pg_config.h...
Copying pg_config_ext.h...
Generating src/interfaces/libpq/libpqdll.def...
Generating src/interfaces/ecpg/ecpglib/ecpglib.def...
Generating src/interfaces/ecpg/compatlib/compatlib.def...
Generating src/interfaces/ecpg/pgtypeslib/pgtypeslib.def...
Generating lwlocknames.c and lwlocknames.h...
Generating probes.h...
Generating errcodes.h...
Generating plerrcodes.h...
Generating qsort_tuple.c...
Generating libpq.rc...
Generating sql_help.h...
Generating kwlist_d.h...
Generating pl_reserved_kwlist_d.h and pl_unreserved_kwlist_d.h...
Generating c_kwlist_d.h and ecpg_kwlist_d.h...
Generating preproc.y...
Generating ecpg_config.h...
Generating pg_config_paths.h...
用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
版权所有(C) Microsoft Corporation。保留所有权利。

生成启动时间为 2020/9/25 9:53:10。
     1>节点 1 上的项目“H:\vcpkg\buildtrees\libpq\x86-windows-static-rel\libpq.vcxproj”(默认目标)。
     1>项目“H:\vcpkg\buildtrees\libpq\x86-windows-static-rel\libpq.vcxproj”(1)正在节点 1 上生成“H:\vcpkg\buildtrees\libpq\x86-windows-static-rel\libpgcommon.vcxproj”(2) (默认目标)。
     2>PrepareForBuild:
         正在创建目录“.\Release\libpgcommon\”。
         正在创建目录“.\Release\libpgcommon\libpgcommon.tlog\”。
       InitializeBuildStatus:
         正在创建“.\Release\libpgcommon\libpgcommon.tlog\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
       VcpkgTripletSelection:
         Using triplet "x86-windows-static" from "H:/vcpkg/installed/x86-windows-static\"
       ClCompile:
         d:\Programs\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x86\CL.exe /c /Isrc/include /Isrc/include/port/win32 /Isrc/include/port/win32_msvc /I"H:/vcpkg/installed/x86-windows-static\include" /Zi /nologo /W3 /WX- /diagnostics:classic /Ox /Oy- /D WIN32 /D _WINDOWS /D __WINDOWS__ /D __WIN32__ /D EXEC_BACKEND /D WIN32_STACK_RLIMIT=4194304 /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D FRONTEND /D _MBCS /GF /Gm- /EHsc /MT /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo".\Release\libpgcommon\\" /Fd".\Release\libpgcommon\libpgcommon.pdb" /Gd /TC /wd4018 /wd4244 /wd4273 /wd4102 /wd4090 /wd4267 /analyze- /FC /errorReport:queue /MP src/common/base64.c src/common/config_info.c src/common/controldata_utils.c src/common/d2s.c src/common/exec.c src/common/f2s.c src/common/fe_memutils.c src/common/file_perm.c src/common/file_utils.c src/common/ip.c src/common/keywords.c src/common/kwlookup.c "src/common/link-canary.c" src/common/logging.c src/common/md5.c src/common/pg_lzcompress.c src/common/pgfnames.c src/common/psprintf.c src/common/relpath.c src/common/restricted_token.c src/common/rmtree.c src/common/saslprep.c "src/common/scram-common.c" src/common/sha2.c src/common/string.c src/common/unicode_norm.c src/common/username.c src/common/wait_error.c
         base64.c
         config_info.c
         controldata_utils.c
         d2s.c
         exec.c
         f2s.c
         fe_memutils.c
         file_perm.c
     1>项目“H:\vcpkg\buildtrees\libpq\x86-windows-static-rel\libpq.vcxproj”(1)正在节点 2 上生成“H:\vcpkg\buildtrees\libpq\x86-windows-static-rel\libpgport.vcxproj”(3) (默认目标)。
     3>PrepareForBuild:
         正在创建目录“.\Release\libpgport\”。
         正在创建目录“.\Release\libpgport\libpgport.tlog\”。
       InitializeBuildStatus:
         正在创建“.\Release\libpgport\libpgport.tlog\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
       VcpkgTripletSelection:
         Using triplet "x86-windows-static" from "H:/vcpkg/installed/x86-windows-static\"
       ClCompile:
         d:\Programs\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x86\CL.exe /c /Isrc/include /Isrc/include/port/win32 /Isrc/include/port/win32_msvc /I"H:/vcpkg/installed/x86-windows-static\include" /Zi /nologo /W3 /WX- /diagnostics:classic /Ox /Oy- /D WIN32 /D _WINDOWS /D __WINDOWS__ /D __WIN32__ /D EXEC_BACKEND /D WIN32_STACK_RLIMIT=4194304 /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D FRONTEND /D _MBCS /GF /Gm- /EHsc /MT /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo".\Release\libpgport\\" /Fd".\Release\libpgport\libpgport.pdb" /Gd /TC /wd4018 /wd4244 /wd4273 /wd4102 /wd4090 /wd4267 /analyze- /FC /errorReport:queue /MP src/port/chklocale.c src/port/crypt.c src/port/dirent.c src/port/dirmod.c src/port/dlopen.c src/port/erand48.c src/port/fls.c src/port/fseeko.c src/port/getaddrinfo.c src/port/getopt.c src/port/getopt_long.c src/port/getrusage.c src/port/gettimeofday.c src/port/inet_aton.c src/port/inet_net_ntop.c src/port/kill.c src/port/mkdtemp.c src/port/noblock.c src/port/open.c src/port/path.c src/port/pg_bitutils.c src/port/pg_crc32c_sb8.c src/port/pg_crc32c_sse42.c src/port/pg_crc32c_sse42_choose.c src/port/pg_strong_random.c src/port/pgcheckdir.c src/port/pgmkdirp.c src/port/pgsleep.c src/port/pgstrcasecmp.c src/port/pqsignal.c src/port/pread.c src/port/pwrite.c src/port/qsort.c src/port/qsort_arg.c src/port/quotes.c src/port/random.c src/port/snprintf.c src/port/sprompt.c src/port/srandom.c src/port/strerror.c src/port/strlcat.c src/port/strlcpy.c src/port/system.c src/port/tar.c src/port/thread.c src/port/win32env.c src/port/win32error.c src/port/win32security.c src/port/win32setlocale.c
     2>ClCompile:
         file_utils.c
         ip.c
         keywords.c
         kwlookup.c
         link-canary.c
         logging.c
         md5.c
         pg_lzcompress.c
     3>ClCompile:
         chklocale.c
         crypt.c
         dirent.c
         dirmod.c
         dlopen.c
         erand48.c
         fls.c
         fseeko.c
         getaddrinfo.c
     2>ClCompile:
         pgfnames.c
         psprintf.c
         relpath.c
         restricted_token.c
         rmtree.c
         saslprep.c
         scram-common.c
     3>ClCompile:
         getopt.c
     2>ClCompile:
         sha2.c
     3>ClCompile:
         getopt_long.c
         getrusage.c
     2>ClCompile:
         string.c
     3>ClCompile:
         gettimeofday.c
         inet_aton.c
         inet_net_ntop.c
     2>ClCompile:
         unicode_norm.c
         username.c
         wait_error.c
     3>ClCompile:
         kill.c
         mkdtemp.c
         noblock.c
         open.c
         path.c
         pg_bitutils.c
         pg_crc32c_sb8.c
         pg_crc32c_sse42.c
         pg_crc32c_sse42_choose.c
         pg_strong_random.c
         pgcheckdir.c
         pgmkdirp.c
         pgsleep.c
         pgstrcasecmp.c
         pqsignal.c
         pread.c
         pwrite.c
         qsort.c
         qsort_arg.c
         quotes.c
         random.c
         snprintf.c
         sprompt.c
         srandom.c
         strerror.c
         strlcat.c
         strlcpy.c
         system.c
         tar.c
         thread.c
         win32env.c
         win32error.c
         win32security.c
         win32setlocale.c
     2>Lib:
         d:\Programs\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x86\Lib.exe /OUT:".\Release\libpgcommon\libpgcommon.lib" /NOLOGO .\Release\libpgcommon\base64.obj
         .\Release\libpgcommon\config_info.obj
         .\Release\libpgcommon\controldata_utils.obj
         .\Release\libpgcommon\d2s.obj
         .\Release\libpgcommon\exec.obj
         .\Release\libpgcommon\f2s.obj
         .\Release\libpgcommon\fe_memutils.obj
         .\Release\libpgcommon\file_perm.obj
         .\Release\libpgcommon\file_utils.obj
         .\Release\libpgcommon\ip.obj
         .\Release\libpgcommon\keywords.obj
         .\Release\libpgcommon\kwlookup.obj
         ".\Release\libpgcommon\link-canary.obj"
         .\Release\libpgcommon\logging.obj
         .\Release\libpgcommon\md5.obj
         .\Release\libpgcommon\pg_lzcompress.obj
         .\Release\libpgcommon\pgfnames.obj
         .\Release\libpgcommon\psprintf.obj
         .\Release\libpgcommon\relpath.obj
         .\Release\libpgcommon\restricted_token.obj
         .\Release\libpgcommon\rmtree.obj
         .\Release\libpgcommon\saslprep.obj
         ".\Release\libpgcommon\scram-common.obj"
         .\Release\libpgcommon\sha2.obj
         .\Release\libpgcommon\string.obj
         .\Release\libpgcommon\unicode_norm.obj
         .\Release\libpgcommon\username.obj
         .\Release\libpgcommon\wait_error.obj
         libpgcommon.vcxproj -> H:\vcpkg\buildtrees\libpq\x86-windows-static-rel\.\Release\libpgcommon\libpgcommon.lib
       AppLocalFromInstalled:
         C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -ExecutionPolicy Bypass -noprofile -File "H:\vcpkg\scripts\buildsystems\msbuild\applocal.ps1" "H:\vcpkg\buildtrees\libpq\x86-windows-static-rel\.\Release\libpgcommon\libpgcommon.lib" "H:/vcpkg/installed/x86-windows-static\bin" ".\Release\libpgcommon\libpgcommon.tlog\libpgcommon.write.1u.tlog" ".\Release\libpgcommon\vcpkg.applocal.log"
       FinalizeBuildStatus:
         正在删除文件“.\Release\libpgcommon\libpgcommon.tlog\unsuccessfulbuild”。
         正在对“.\Release\libpgcommon\libpgcommon.tlog\libpgcommon.lastbuildstate”执行 Touch 任务。
     2>已完成生成项目“H:\vcpkg\buildtrees\libpq\x86-windows-static-rel\libpgcommon.vcxproj”(默认目标)的操作。
     3>Lib:
         d:\Programs\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x86\Lib.exe /OUT:".\Release\libpgport\libpgport.lib" /NOLOGO .\Release\libpgport\chklocale.obj
         .\Release\libpgport\crypt.obj
         .\Release\libpgport\dirent.obj
         .\Release\libpgport\dirmod.obj
         .\Release\libpgport\dlopen.obj
         .\Release\libpgport\erand48.obj
         .\Release\libpgport\fls.obj
         .\Release\libpgport\fseeko.obj
         .\Release\libpgport\getaddrinfo.obj
         .\Release\libpgport\getopt.obj
         .\Release\libpgport\getopt_long.obj
         .\Release\libpgport\getrusage.obj
         .\Release\libpgport\gettimeofday.obj
         .\Release\libpgport\inet_aton.obj
         .\Release\libpgport\inet_net_ntop.obj
         .\Release\libpgport\kill.obj
         .\Release\libpgport\mkdtemp.obj
         .\Release\libpgport\noblock.obj
         .\Release\libpgport\open.obj
         .\Release\libpgport\path.obj
         .\Release\libpgport\pg_bitutils.obj
         .\Release\libpgport\pg_crc32c_sb8.obj
         .\Release\libpgport\pg_crc32c_sse42.obj
         .\Release\libpgport\pg_crc32c_sse42_choose.obj
         .\Release\libpgport\pg_strong_random.obj
         .\Release\libpgport\pgcheckdir.obj
         .\Release\libpgport\pgmkdirp.obj
         .\Release\libpgport\pgsleep.obj
         .\Release\libpgport\pgstrcasecmp.obj
         .\Release\libpgport\pqsignal.obj
         .\Release\libpgport\pread.obj
         .\Release\libpgport\pwrite.obj
         .\Release\libpgport\qsort.obj
         .\Release\libpgport\qsort_arg.obj
         .\Release\libpgport\quotes.obj
         .\Release\libpgport\random.obj
         .\Release\libpgport\snprintf.obj
         .\Release\libpgport\sprompt.obj
         .\Release\libpgport\srandom.obj
         .\Release\libpgport\strerror.obj
         .\Release\libpgport\strlcat.obj
         .\Release\libpgport\strlcpy.obj
         .\Release\libpgport\system.obj
         .\Release\libpgport\tar.obj
         .\Release\libpgport\thread.obj
         .\Release\libpgport\win32env.obj
         .\Release\libpgport\win32error.obj
         .\Release\libpgport\win32security.obj
         .\Release\libpgport\win32setlocale.obj
         libpgport.vcxproj -> H:\vcpkg\buildtrees\libpq\x86-windows-static-rel\.\Release\libpgport\libpgport.lib
       AppLocalFromInstalled:
         C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -ExecutionPolicy Bypass -noprofile -File "H:\vcpkg\scripts\buildsystems\msbuild\applocal.ps1" "H:\vcpkg\buildtrees\libpq\x86-windows-static-rel\.\Release\libpgport\libpgport.lib" "H:/vcpkg/installed/x86-windows-static\bin" ".\Release\libpgport\libpgport.tlog\libpgport.write.1u.tlog" ".\Release\libpgport\vcpkg.applocal.log"
       FinalizeBuildStatus:
         正在删除文件“.\Release\libpgport\libpgport.tlog\unsuccessfulbuild”。
         正在对“.\Release\libpgport\libpgport.tlog\libpgport.lastbuildstate”执行 Touch 任务。
     3>已完成生成项目“H:\vcpkg\buildtrees\libpq\x86-windows-static-rel\libpgport.vcxproj”(默认目标)的操作。
     1>PrepareForBuild:
         正在创建目录“.\Release\libpq\”。
         正在创建目录“.\Release\libpq\libpq.tlog\”。
       InitializeBuildStatus:
         正在创建“.\Release\libpq\libpq.tlog\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
       VcpkgTripletSelection:
         Using triplet "x86-windows-static" from "H:/vcpkg/installed/x86-windows-static\"
       ClCompile:
         d:\Programs\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x86\CL.exe /c /Isrc/include /Isrc/include/port/win32 /Isrc/include/port/win32_msvc /Isrc/port /I"H:/vcpkg/installed/x86-windows-static\include" /Zi /nologo /W3 /WX- /diagnostics:classic /Ox /Oy- /D WIN32 /D _WINDOWS /D __WINDOWS__ /D __WIN32__ /D EXEC_BACKEND /D WIN32_STACK_RLIMIT=4194304 /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D FRONTEND /D UNSAFE_STAT_OK /D _MBCS /GF /Gm- /EHsc /MT /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo".\Release\libpq\\" /Fd".\Release\libpq\libpq.pdb" /Gd /TC /wd4018 /wd4244 /wd4273 /wd4102 /wd4090 /wd4267 /analyze- /FC /errorReport:queue /MP src/backend/utils/mb/encnames.c src/backend/utils/mb/wchar.c "src/interfaces/libpq/fe-auth-scram.c" "src/interfaces/libpq/fe-auth.c" "src/interfaces/libpq/fe-connect.c" "src/interfaces/libpq/fe-exec.c" "src/interfaces/libpq/fe-lobj.c" "src/interfaces/libpq/fe-misc.c" "src/interfaces/libpq/fe-print.c" "src/interfaces/libpq/fe-protocol2.c" "src/interfaces/libpq/fe-protocol3.c" "src/interfaces/libpq/fe-secure.c" "src/interfaces/libpq/legacy-pqsignal.c" "src/interfaces/libpq/libpq-events.c" src/interfaces/libpq/pqexpbuffer.c "src/interfaces/libpq/pthread-win32.c" src/interfaces/libpq/win32.c
         encnames.c
         wchar.c
         fe-auth-scram.c
         fe-auth.c
         fe-connect.c
         fe-exec.c
         fe-lobj.c
         fe-misc.c
         fe-print.c
         fe-protocol2.c
         fe-protocol3.c
         fe-secure.c
         legacy-pqsignal.c
         libpq-events.c
         pqexpbuffer.c
         pthread-win32.c
         win32.c
       ResourceCompile:
         C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x64\rc.exe /l"0x0409" /Isrc\include /I"H:/vcpkg/installed/x86-windows-static\include" /nologo /fo".\Release\libpq\libpq.res" src/interfaces/libpq/libpq.rc 
       Lib:
         d:\Programs\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x86\Lib.exe /OUT:".\Release\libpq\libpq.lib" /NOLOGO .\Release\libpq\libpq.res
         .\Release\libpq\encnames.obj
         .\Release\libpq\wchar.obj
         ".\Release\libpq\fe-auth-scram.obj"
         ".\Release\libpq\fe-auth.obj"
         ".\Release\libpq\fe-connect.obj"
         ".\Release\libpq\fe-exec.obj"
         ".\Release\libpq\fe-lobj.obj"
         ".\Release\libpq\fe-misc.obj"
         ".\Release\libpq\fe-print.obj"
         ".\Release\libpq\fe-protocol2.obj"
         ".\Release\libpq\fe-protocol3.obj"
         ".\Release\libpq\fe-secure.obj"
         ".\Release\libpq\legacy-pqsignal.obj"
         ".\Release\libpq\libpq-events.obj"
         .\Release\libpq\pqexpbuffer.obj
         ".\Release\libpq\pthread-win32.obj"
         .\Release\libpq\win32.obj
     1>LINK : warning LNK4068: /MACHINE not specified; defaulting to X64 [H:\vcpkg\buildtrees\libpq\x86-windows-static-rel\libpq.vcxproj]
     1>.\Release\libpq\encnames.obj : fatal error LNK1112: module machine type 'x86' conflicts with target machine type 'x64' [H:\vcpkg\buildtrees\libpq\x86-windows-static-rel\libpq.vcxproj]
     1>已完成生成项目“H:\vcpkg\buildtrees\libpq\x86-windows-static-rel\libpq.vcxproj”(默认目标)的操作 - 失败。

生成失败。

       “H:\vcpkg\buildtrees\libpq\x86-windows-static-rel\libpq.vcxproj”(默认目标) (1) ->
       (Lib 目标) -> 
         LINK : warning LNK4068: /MACHINE not specified; defaulting to X64 [H:\vcpkg\buildtrees\libpq\x86-windows-static-rel\libpq.vcxproj]


       “H:\vcpkg\buildtrees\libpq\x86-windows-static-rel\libpq.vcxproj”(默认目标) (1) ->
       (Lib 目标) -> 
         .\Release\libpq\encnames.obj : fatal error LNK1112: module machine type 'x86' conflicts with target machine type 'x64' [H:\vcpkg\buildtrees\libpq\x86-windows-static-rel\libpq.vcxproj]

    1 个警告
    1 个错误

已用时间 00:00:07.97

**Comment by flow-specter** [comment]
Hi, I met the same problem, have you solved it?

**Comment by gooxion** [comment]
> Hi, I met the same problem, have you solved it?

I only solved it in my scene:
My project depends on qt5-base and qt5-base depends on libpq，
but I found that seems libpq was unnecessary,
then I edit "CONTROL" file under ports (just like %vcpkgdir%\ports\qt5-base\CONTROL") ，change line
**`Build-Depends: zlib, zstd, libjpeg-turbo, libpng, freetype, pcre2, harfbuzz, sqlite3, libpq, double-conversion, openssl, angle (!windows), egl-registry, icu (!uwp), fontconfig (!windows)`**
to
**`Build-Depends: zlib, zstd, libjpeg-turbo, libpng, freetype, pcre2, harfbuzz, sqlite3,  double-conversion, openssl, angle (!windows), egl-registry, icu (!uwp), fontconfig (!windows)`**
continue with `vcpkg install qt5-base:x86-windows-static` and it worked.

Hope that helpful for u.

**Comment by JackBoosY** [comment]
Please add `/p:MACHINE=X86` to _VCPKG_ROOT/ports/libpq/portfile.cmake_ line 192:
https://github.com/microsoft/vcpkg/blob/2aaa67573085c24bcb4e224b87605d708d9a6377/ports/libpq/portfile.cmake#L192

Then try again.

Thanks.

**Comment by JonLiu1993** [comment]
@gooxion ,Could you please try @JackBoosY 's suggestion?

**Comment by JackBoosY** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
