### ISSUE TITLE
How do I ...LNK2001 Error when build with x64-windows-static-md

### ISSUE THREAD

**Issue by jsnhsu** [microsoft/vcpkg#13728]
I have boost, wxWidget, jsoncpp, and etc... which built with x64-windows-static-md as my library then use vcpkg integrate install for VS2019.

For one of my VC project which uses wxWidget only and MD/MDd, and C++17.  First of all, I have to rename vcpkg/installed/x64-windows-static-md to be x64-windows-static, otherwise it fails to build the project because of failing to find libs.  However, the biggest issue is the MD static libs only works in Debug mode but Release.  It shows the error as following

LNK2001	unresolved external symbol "class boost::unit_test::test_suite * __cdecl init_unit_test_suite(int,char * * const)" (?init_unit_test_suite@@YAPEAVtest_suite@unit_test@boost@@HQEAPEAD@Z)

I really don't get it because i don't even use boost within this project.  How come the link failed at it?  The error remains even if I vcpkg remove boost:x64-windows-static(-md).  Please advise!

**Comment by JackBoosY** [comment]
I think the problem is that the settings related to triples are incorrect.

**Comment by jsnhsu** [comment]
I use the file under vcpkg\triplets\community\x86-windows-static-md.cmake which comes with vcpkg source and and has only three variable definition. 

Does anyone support my issue?

**Comment by jsnhsu** [comment]
It's actually a configuration bug of my vcproj.  The Link/System/Subsystem wasn't configured as Windows correctly in Release mode.  The exe was built after I found and corrected it.  Case closed
