### ISSUE TITLE
[python3] build failure

### ISSUE THREAD

**Issue by chenming-wu** [microsoft/vcpkg#13741]
**Host Environment**
- OS: MacOS (Big Sur beta8)
- Compiler: Clang

**To Reproduce**
`./vcpkg install python3`

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:141 (message):
    Command failed: /Users/jast/vcpkg/buildtrees/python3/src/v3.8.3-43b03f2bf0.clean-x64-osx-release/configure --prefix=/Users/jast/vcpkg/buildtrees/python3/src/v3.8.3-43b03f2bf0.clean-x64-osx-release/../../make-build-x64-osx-release --with-openssl=/Users/jast/vcpkg/installed/x64-osx "CPPFLAGS=-I/Users/jast/vcpkg/installed/x64-osx/include -framework CoreFoundation" LDFLAGS=-L/Users/jast/vcpkg/installed/x64-osx/lib LIBS=-liconv
    Working Directory: /Users/jast/vcpkg/buildtrees/python3/src/v3.8.3-43b03f2bf0.clean-x64-osx-release
    See logs for more information:
      /Users/jast/vcpkg/buildtrees/python3/config-x64-osx-rel-out.log
      /Users/jast/vcpkg/buildtrees/python3/config-x64-osx-rel-err.log

Call Stack (most recent call first):
  ports/python3/portfile.cmake:125 (vcpkg_execute_build_process)
  scripts/ports.cmake:79 (include)

Error: Building package python3:x64-osx failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: python3:x64-osx
  Vcpkg version: 2020.06.15-unknownhash

Additionally, attach any relevant sections from the log files above.

The following packages will be built and installed:
  GNU nano 2.0.6                             File: /Users/jast/vcpkg/buildtrees/python3/config-x64-osx-rel-err.log

Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
configure: error: in `/Users/jast/vcpkg/buildtrees/python3/src/v3.8.3-43b03f2bf0.clean-x64-osx-release':
configure: error: cannot compute sizeof (long double)
See `config.log' for more details

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by JackBoosY** [comment]
Could you provide the full log?
_/Users/jast/vcpkg/buildtrees/python3/config-x64-osx-rel-out.log_
_/Users/jast/vcpkg/buildtrees/python3/config-x64-osx-rel-err.log_

Thanks.

**Comment by chenming-wu** [comment]
[config-x64-osx-rel-err.log](https://github.com/microsoft/vcpkg/files/5282325/config-x64-osx-rel-err.log)
[config-x64-osx-rel-out.log](https://github.com/microsoft/vcpkg/files/5282326/config-x64-osx-rel-out.log)

**Comment by chenming-wu** [comment]
@JackBoosY Sure, already uploaded.

**Comment by JackBoosY** [comment]
```
configure: error: cannot compute sizeof (long double)
```

**Comment by chenming-wu** [comment]
Is there any workaround to fix this error? @JackBoosY

**Comment by JackBoosY** [comment]
@chenming-wu My osx machine has problem, waiting for fix it.

**Comment by JackBoosY** [comment]
@chenming-wu Can you provide the log _/Users/jast/vcpkg/buildtrees/python3/src/v3.8.3-43b03f2bf0.clean-x64-osx-release/config.log_?

**Comment by chenming-wu** [comment]
[config.log](https://github.com/microsoft/vcpkg/files/5370937/config.log)

**Comment by JackBoosY** [comment]
`clang: error: invalid version number in 'MACOSX_DEPLOYMENT_TARGET=11.0'`
Should not be compatible with the beta version of macOS.

**Comment by chenming-wu** [comment]
Will upstream cpython to the latest version solve this problem? See https://github.com/python/cpython/pull/21113

**Comment by JackBoosY** [comment]
@chenming-wu  Maybe, you can have a try.
