### ISSUE TITLE
Error getting canonicalization of <vcpkg location>/packages

### ISSUE THREAD

**Issue by JackKenney** [microsoft/vcpkg#13744]
**Describe the bug**
Running either of the commands below results in this error:
```$ ./vcpkg install eigen3
Error getting canonicalization of /<install location>/vcpkg/packages: No such file or directory
$ ./vcpkg integrate install
Error getting canonicalization of /<install location>/vcpkg/packages: No such file or directory
```

**Environment**
- OS: Ubuntu 20.04
- Compiler: gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0

**To Reproduce**
1. ./vcpkg install eigen3
2. See error
Repro code when

**Expected behavior**
The first time I used `vcpkg` on this arch I did not encounter this issue but now on multiple machines I have experienced this issue. 

**Failure logs** 
The build did not fail

**Additional context**
Not sure what else is relevant, but if I `mkdir packages` then I get the same error for `packages/ports` and it keeps going like that for many directories.

**Comment by JackBoosY** [comment]
@JackKenney Does this path contain any special characters or empty space?

**Comment by JackKenney** [comment]
In this case it's just
/home/jack/addons/vcpkg/packages

**Comment by JackBoosY** [comment]
Don't know why, I can't repro it on my machine.
@dan-shaw Do you have any ideas?

**Comment by iskiselev** [comment]
I got similar problem after updating to latest master on windows:
```
Error getting canonicalization of C:\code\ports: The system cannot find the file specified.
```

VCPKG is executed inside docker container, C:\code and vcpkg root is mounted into C:\code.
On both host and docker container Windows 2016 Server is used.

Currently reproduced it on CI, I'll try to repro it with container locally on Win 10 2004 host.

**Comment by iskiselev** [comment]
Looks like in my case issue is different from original reporter. On windows it was introduced by commit 0bb8780a60e67320a966421e2923595fa57cbf22.
As a workaround I changed C:\appd\agent-dotnet-vcpkg\toolsrc\windows-bootstrap\vcpkg.vcxproj (set VcpkgUseStdFilesystem=0 always and add _SILENCE_EXPERIMENTAL_FILESYSTEM_DEPRECATION_WARNING definition). It helped.

**Comment by iskiselev** [comment]
Any chance that it will be fixed for docker? Should docker on windows case be moved to separate issue? There is small chance that it is actually the same issue.

**Comment by JackBoosY** [comment]
@strega-nil Can you please take a look?

Thanks.

**Comment by strega-nil** [comment]
@iskiselev yeah, please open a new issue; the fact that it fails with std::filesystem and not std::experimental::filesystem is _really weird_, and probably requires a standard library maintainer to look into it.

**Comment by strega-nil** [comment]
@JackKenney Could you rerun with `--debug` on the vcpkg command line, so we can figure out where this error is happening?

**Comment by JackKenney** [comment]
Sure, this is what the --debug flag returns
```
vcpkg install --debug eigen3
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
Error getting canonicalization of /home/jack/addons/vcpkg/packages: No such file or directory
[DEBUG] ../src/vcpkg/vcpkgpaths.cpp(230)
[DEBUG] Exiting after 1404 us (186 us)
```

**Comment by JackBoosY** [comment]
Is it a permission issue?

**Comment by strega-nil** [comment]
@JackKenney looks like you've got `VCPKG_ROOT` set in your environment to `/home/jack/addons/vcpkg/packages`. `VCPKG_ROOT` sets where vcpkg looks for the vcpkg stuff, and in general we reserve all `VCPKG_*` environment variables for our own use.

**Comment by JackKenney** [comment]
That was the issue! I didn't realize those env variables got used by `vcpkg`.
Thanks!
