### ISSUE TITLE
How to install dll files without dynamic CRT check?

### ISSUE THREAD

**Issue by UnaNancyOwen** [microsoft/vcpkg#1374]
I'm creating a new port for Kinect SDK v2.x. (#1414)
The dependent files of Kinect SDK v2 extensions (face tracking, gesture recognition, etc.) depend on dynamic CRT (msvcp110.dll, msvcr110.dll) of Visual Studio 2012.
I want to install these files without dynamic CRT check.
Do you have any good ideas?

(Note: The core features library of Kinect SDK v2 able to be installed, because it is not depend on these files. That is to say, We can also choose to give up install the libraries of extended features.)

**Comment by ras0219-msft** [comment]
We'll need to add a policy for this; `VCPKG_POLICY_ALLOW_OBSOLETE_MSVCRT` is almost what we need, but that only disables the check for msvcrt, not newer CRTs.

**Comment by UnaNancyOwen** [comment]
@ras0219-msft How to use <code>VCPKG_POLICY_ALLOW_OBSOLETE_MSVCRT</code>?

**Comment by PhoebeHui** [comment]
@UnaNancyOwen, for use VCPKG_POLICY_ALLOW_OBSOLETE_MSVCRT,  see https://github.com/microsoft/vcpkg/blob/master/ports/ecm/portfile.cmake#L30 for a usage example. 

For kinectsdk2, the ports has added to vcpkg, so I guess this issue can be closed.
