### ISSUE TITLE
[New Port Request] scotch

### ISSUE THREAD

**Issue by paspro** [microsoft/vcpkg#13743]
Library name:
scotch

Library description:
Package for graph and mesh/hypergraph partitioning, graph clustering, and sparse matrix ordering.

Source repository URL:
https://gitlab.inria.fr/scotch/scotch

Project homepage (if different from the source repository):
https://gitlab.inria.fr/scotch/scotch

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
It requires MPI. Three compressed graph formats are currently supported: bzip2, gzip and xz/lzma. In order for them to be
actually activated, the proper libraries must be available on the system. On a Linux platform, they are called "libz" for the gzip
format, "libbzip2" for the bzip2 format, and "liblzma" for the lzma format.

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
