### ISSUE TITLE
[wxWidgets: x64-mingw-static] build failure

### ISSUE THREAD

**Issue by comedinha** [microsoft/vcpkg#13747]
**Host Environment**
- OS: Windows (Insider Build 20221)
- Compiler: x64-mingw-static

**To Reproduce**
`./vcpkg --triplet x64-mingw-static install wxwidgets`

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
> CMake Error at scripts/cmake/vcpkg_copy_tools.cmake:47 (message):
>   Couldn't find this tool:
>   C:/vcpkg/packages/wxwidgets_x64-mingw-static/bin/wxrc.exe.
> Call Stack (most recent call first):
>   ports/wxwidgets/portfile.cmake:43 (vcpkg_copy_tools)
>   scripts/ports.cmake:79 (include)
> 
> 
> Error: Building package wxwidgets:x64-mingw-static failed with: BUILD_FAILED

-Please attach any additional failure logs mentioned in the console output.
> CMake Error: failed to create symbolic link 'C:/vcpkg/packages/wxwidgets_x64-mingw-dynamic/bin/wx-config': operation not permitted
> CMake Error: failed to create symbolic link 'C:/vcpkg/packages/wxwidgets_x64-mingw-dynamic/bin/wxrc.exe': operation not permitted

**Comment by JCBurnside** [comment]
Also fails on x86-mingw-static
