### ISSUE TITLE
ptex build failure

### ISSUE THREAD

**Issue by virtualritz** [microsoft/vcpkg#13758]
**Host Environment**
- OS: macOS 10.15.6
- Compiler: Apple clang version 12.0.0 (clang-1200.0.32.2)

**To Reproduce**
`./vcpkg install ptex`

**Failure logs** 
[install-x64-osx-dbg-out.log](https://github.com/microsoft/vcpkg/files/5287180/install-x64-osx-dbg-out.log)

**Comment by virtualritz** [comment]
To add: Ptex builds fine if I just check out [the repo.](https://github.com/wdas/ptex) directly and follow the build instructions (`make prefix=$PWD/install && make install`).

**Comment by virtualritz** [comment]
Bump.

**Comment by JackBoosY** [comment]
Just remove double quotes from this will solve this issue:
https://github.com/microsoft/vcpkg/blob/b14aa50824c073629f1c7b44ded905a7b4bd7152/ports/ptex/portfile.cmake#L28
