### ISSUE TITLE
[openssl-unix:arm64-android] build failure

### ISSUE THREAD

**Issue by aiyou4love** [microsoft/vcpkg#13756]
**Host Environment**
- OS: win10 win64
- Compiler: revision
Android R16b

**To Reproduce**
`./vcpkg install openssl-unix:arm64-android

**Failure logs** 
aarch64-linux-android/bin\ld: cannot find crtbegin_so.o: No such file or directory
aarch64-linux-android/bin\ld: cannot find -ldl
aarch64-linux-android/bin\ld: cannot find -lc
aarch64-linux-android/bin\ld: cannot find crtend_so.o: No such file or directory
clang.exe: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [Makefile:746: libcrypto.so] Error 1

**Comment by PhoebeHui** [comment]
This is not usual scenario we're working on now, but we accept PRs for fixing this issue. Sorry for that.

**Comment by aiyou4love** [comment]
> This is not usual scenario we're working on now, but we accept PRs for fixing this issue. Sorry for that.

set(VCPKG_TARGET_ARCHITECTURE arm64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_CMAKE_SYSTEM_NAME Android)
building sucess

but

set(VCPKG_TARGET_ARCHITECTURE arm64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_CMAKE_SYSTEM_NAME Android)

building fail

**Comment by JonLiu1993** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
