### ISSUE TITLE
[New Port Request] med

### ISSUE THREAD

**Issue by paspro** [microsoft/vcpkg#13752]
Library name:
med

Library description:
The purpose of the MED module is to provide a standard for storing and recovering computer data associated to numerical meshes and fields, and to facilitate the exchange between codes and solvers. The persistent data storage is based upon HDF format (like CGNS, a standard developed by Boeing and NASA in the area of Computational Fluid Dynamic). MED also provides structures to hold data on meshes and fields. These structures are exchanged between solvers, hide the communication level (CORBA or MPI), and offer persistence (read/write in .med files).

Source repository URL:
http://files.salome-platform.org/Salome/other/med-4.1.0.tar.gz

Project homepage (if different from the source repository):
https://www.salome-platform.org/user-section/about/med

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
Requires HDF5 and libz.

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
