### ISSUE TITLE
zlib build failure

### ISSUE THREAD

**Issue by Keithcat1** [microsoft/vcpkg#13760]
**Host Environment**
- OS: windowx-x64
- Compiler: MSVC 2019

**To Reproduce**
`./vcpkg install zlib`

**Failure logs** 
-- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.
2-1-any.pkg.tar.xz...
-- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.
2-1-any.pkg.tar.xz... Failed. Status: 35;"SSL connect error"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:181 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/is
sues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_find_acquire_program.cmake:438 (vcpkg_download_distfile)
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:270 (vcpkg_find_acquire_program)
  ports/zlib/portfile.cmake:48 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:79 (include)

**Additional context**

**Comment by NancyLi1013** [comment]
Hi @Keithcat1 
Thanks for posting this issue.
 Could you please help confirm if you can download 
https://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz 
manually?

**Comment by Keithcat1** [comment]
I was able to download it just now, but this a different computer on a different network

**Comment by NancyLi1013** [comment]
Yes, this is related with your network.

**Comment by code-deleter** [comment]
Same issue,

**Comment by Keithcat1** [comment]
Finally had time to check this, sorry.
When I click the link you provided, my browser says this:
repo.msys2.org took too long to respond.
This error is also stopping me from building the SDL2 package, looks like it's a more general error.
