### ISSUE TITLE
[skia] x86-* and *-linux triplets

### ISSUE THREAD

**Issue by Niikelion** [microsoft/vcpkg#13769]
****

**Is your feature request related to a problem? Please describe.**
Skia package only supports x64-windows, x64-windows-static and x64-osx triplets. It lacks \*-linux and x86-\* triplets.

**Proposed solution**
Add \*-linux and x86-\* triplets.

**Comment by fabinshen** [comment]
Need them.

**Comment by JackBoosY** [comment]
@fabinshen Feel free to open a PR to support them : )

**Comment by Adela0814** [comment]
Fixed. [skia supports ](https://github.com/microsoft/vcpkg/blob/1c48ec7f49d69bb753e6afefba51368e18263255/ports/skia/vcpkg.json#:~:text=%22supports%22%3A%20%22!(windows%20%26%20arm%20%26%20!arm64)%22%2C)
