### ISSUE TITLE
[Spatial] Request a libaray.

### ISSUE THREAD

**Issue by BookmanHan** [microsoft/vcpkg#13764]
****
URL: http://spatial.sourceforge.net/tutorial.html

**Is your feature request related to a problem? Please describe.**
No.

**Proposed solution**
Add it to vcpkg.

**Describe alternatives you've considered**
No.

**Additional context**
No.

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
