### ISSUE TITLE
Fuzzylite does not link with Visual Studio 2019

### ISSUE THREAD

**Issue by Stretchyfish** [microsoft/vcpkg#13779]
**Describe the bug**
The library Fuzzylite does not get reconised in visual studio. Get multiple errors about symbols missing.

**Environment**
- OS: Windows
- IDE: Visual Studio 2019

**To Reproduce**
1. ./vcpkg install Fuzzylite
2. Copy example from their website: https://www.fuzzylite.com/cpp/
3. Fix their spelling error steer => mSteer
4. Compile
2. See error

**Expected behavior**
The program should repeatly loop though code with changed steer value. Works on Linux with non vcpkg.

**Failure logs** 
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1120	3 unresolved externals	Fuzzylite_test1	C:\Users\mmaar\Google Drive\2.Skole\SDU-UNIVERSITET\5. semester\AI\Fuzzylite_test1\x64\Debug\Fuzzylite_test1.exe	1	
Error	LNK2001	unresolved external symbol "private: static bool fl::fuzzylite::_logging" (?_logging@fuzzylite@fl@@0_NA)	Fuzzylite_test1	C:\Users\mmaar\Google Drive\2.Skole\SDU-UNIVERSITET\5. semester\AI\Fuzzylite_test1\Fuzzylite_test1\ObstacleAvoidance.obj	1	
Error	LNK2001	unresolved external symbol "private: static int fl::fuzzylite::_decimals" (?_decimals@fuzzylite@fl@@0HA)	Fuzzylite_test1	C:\Users\mmaar\Google Drive\2.Skole\SDU-UNIVERSITET\5. semester\AI\Fuzzylite_test1\Fuzzylite_test1\ObstacleAvoidance.obj	1	
Error	LNK2001	unresolved external symbol "private: static int fl::fuzzylite::_scalarFormat" (?_scalarFormat@fuzzylite@fl@@0HA)	Fuzzylite_test1	C:\Users\mmaar\Google Drive\2.Skole\SDU-UNIVERSITET\5. semester\AI\Fuzzylite_test1\Fuzzylite_test1\ObstacleAvoidance.obj	1

**Comment by PhoebeHui** [comment]
@Stretchyfish, thanks for reporting this issue! 

I have summited PR #13807 to fix this issue.
