### ISSUE TITLE
Fail while installing boost

### ISSUE THREAD

**Issue by foragerDev** [microsoft/vcpkg#13772]
**Host Environment**
- OS: Windwos 10 
- Compiler: Visual C++

**To Reproduce**
`./vcpkg install boost`

**Failure logs** 
Computing installation plan...
The following packages will be built and installed:
    bzip2[core]:x86-windows
Detecting compiler hash for triplet x86-windows...
Starting package 1/1: bzip2:x86-windows
Building package bzip2[core]:x86-windows...
Could not locate cached archive: C:\Users\Al Ghani Computer\AppData\Local\vcpkg\archives\95\95552d6795ebebf13547bb3f2ca24891f8c280b9.zip
-- Using cached C:/Users/Al Ghani Computer/vcpkg/downloads/bzip2-75a94bea3918e612b879d6a11ca64b8689526147.tar.gz
-- Cleaning sources at C:/Users/Al Ghani Computer/vcpkg/buildtrees/bzip2/src/8689526147-1ef169fbaa.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/Al Ghani Computer/vcpkg/downloads/bzip2-75a94bea3918e612b879d6a11ca64b8689526147.tar.gz
-- Applying patch fix-import-export-macros.patch
-- Using source at C:/Users/Al Ghani Computer/vcpkg/buildtrees/bzip2/src/8689526147-1ef169fbaa.clean
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Fixing pkgconfig file: C:/Users/Al Ghani Computer/vcpkg/packages/bzip2_x86-windows/lib/pkgconfig/bzip2.pc
-- CHECK_LIB_bz2_RELEASE:CHECK_LIB_bz2_RELEASE-NOTFOUND
CMake Error at scripts/cmake/vcpkg_fixup_pkgconfig.cmake:232 (message):
  Library "bz2" was not found! If it is a system library use the
  SYSTEM_LIBRARIES parameter for the vcpkg_fixup_pkgconfig call! Otherwise,
  correct the *.pc file
Call Stack (most recent call first):
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:297 (vcpkg_fixup_pkgconfig_check_files)
  ports/bzip2/portfile.cmake:43 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:79 (include)

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/13103, would be fixed by PR https://github.com/microsoft/vcpkg/pull/13126

As a workaround, you can create a new clone without space in vcpkg path.
