### ISSUE TITLE
Error: Building package szip:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by xingyewuyu** [microsoft/vcpkg#13781]
When run the command: .\vcpkg install darknet[full]:x64-windows,   the error apperars as follows:

Computing installation plan...
The following packages will be built and installed:
    darknet[core,cuda,cudnn,full,opencv-cuda,weights,weights-train]:x64-windows
  * giflib[core]:x64-windows
  * hdf5[core,szip,zlib]:x64-windows
  * leptonica[core]:x64-windows
  * libjpeg-turbo[core]:x64-windows
  * liblzma[core]:x64-windows
  * libpng[core]:x64-windows
  * libwebp[core,nearlossless,simd,unicode]:x64-windows
  * opencv[core,cuda,dnn,ffmpeg,jpeg,opengl,png,tiff,webp]:x64-windows
  * opencv4[contrib,core,cuda,dnn,ffmpeg,jpeg,opengl,png,tiff,webp]:x64-windows
  * opengl[core]:x64-windows
  * protobuf[core]:x64-windows
  * pthreads[core]:x64-windows
  * stb[core]:x64-windows
  * szip[core]:x64-windows
  * tesseract[core]:x64-windows
  * tiff[core]:x64-windows
  * zlib[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Warning: The following VS instances are excluded because the English language pack is unavailable.
    e:\Program Files (x86)\Microsoft Visual Studio\2017\Professional
Please install the English language pack.
Detecting compiler hash for triplet x64-windows...
Starting package 1/18: szip:x64-windows
Building package szip[core]:x64-windows...
Could not locate cached archive: C:\Users\lxm\AppData\Local\vcpkg\archives\27\275bb50102e4195b9fa5c02d9ec579d56cd205c7.zip
-- Using cached C:/Users/lxm/vcpkg/downloads/szip-2.1.1.tar.gz
-- Cleaning sources at C:/Users/lxm/vcpkg/buildtrees/szip/src/szip-2.1.1-6b767acfa7.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/lxm/vcpkg/downloads/szip-2.1.1.tar.gz
-- Applying patch fix-szip-config-to-set-szip-found.patch
-- Using source at C:/Users/lxm/vcpkg/buildtrees/szip/src/szip-2.1.1-6b767acfa7.clean
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:85 (message):
    Command failed: ninja -v
    Working Directory: C:/Users/lxm/vcpkg/buildtrees/szip/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\Users\lxm\vcpkg\buildtrees\szip\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:305 (vcpkg_execute_required_process)
  ports/szip/portfile.cmake:17 (vcpkg_configure_cmake)
  scripts/ports.cmake:79 (include)

Error: Building package szip:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: szip:x64-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by xingyewuyu** [comment]
According to the issue "https://github.com/microsoft/vcpkg/issues/7067 ", i  add the follow path of window kit 10 as follows:
![image](https://user-images.githubusercontent.com/33115396/94440678-7e625480-01d4-11eb-8ca6-34f6e60d58ed.png)
     However, it is still no work and the same errors appears.

**Comment by xingyewuyu** [comment]
How to set the path of the window Kit 10? 
![image](https://user-images.githubusercontent.com/33115396/94442039-0f85fb00-01d6-11eb-97f3-b5e0b84d62d1.png)
 Is the path "C:\Program Files (x86)\Windows Kits\10" right ?  See the below:
![image](https://user-images.githubusercontent.com/33115396/94442210-452ae400-01d6-11eb-9cd5-e361ab450c2d.png)
However , it is still no work.

**Comment by xingyewuyu** [comment]
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/5292999/config-x64-windows-out.log)

**Comment by xingyewuyu** [comment]
![image](https://user-images.githubusercontent.com/33115396/94448601-ac986200-01dd-11eb-8832-fd9f53d41ce0.png)
How to set the working C compiler  as vs2017( i have installed according to the software requirements ) and replace the vs2015（i have installed for more one years）.

**Comment by sfhacker** [comment]
Any updates on this open issue?

**Comment by LilyWangL** [comment]
@xingyewuyu Sorry I am late. Could you please install the English language package and rebuild vcpkg and reinstall szip?

**Comment by PhoebeHui** [comment]
@xingyewuyu, this is duplicated issue with https://github.com/microsoft/vcpkg/issues/13051, this should be resolved if the English lauguage package installed. Please reopen if the issue persist.
