### ISSUE TITLE
[PCL question]

### ISSUE THREAD

**Issue by SmartKangJohn** [microsoft/vcpkg#13782]
When run the command: .\vcpkg install pcl[full]:x64-windows.
I got PCL1.11.0 and bulid ok, but lost the module 'visualization', so I can't use the function of view.

My Environment
OS: windows10-x64
Compiler: visual studio 2017
PCL Version: 1.11.0

I have another question: How to install PCL1.9.1?
path:https://github.com/PointCloudLibrary/pcl/tree/pcl-1.9.1

**Comment by NancyLi1013** [comment]
Hi @SmartKangJohn

Thanks for posting this issue. Currently it is not supported. Requires upstream update to support VTK 9.0. 
Duplicated to #11601.  Let's track this issue there.

**Comment by SmartKangJohn** [comment]
thanks！



---Original---
