### ISSUE TITLE
[Request] Better documenting of manifest "features" feature

### ISSUE THREAD

**Issue by VelocityRa** [microsoft/vcpkg#13787]
## 1.
It's not clear / documented how to specify optional features when installing via manifests.
For example, my current command I use to install is:
```
vcpkg install --feature-flags=manifests --triplet x64-windows --overlay-ports=../vcpkg-ports/ports
```
How would I specify features if I don't want the defaults?

## 2.
In the [manifests.md](https://github.com/microsoft/vcpkg/blob/master/docs/specifications/manifests.md) there should probably be an example of using the optional `"features"`, and maybe of `"default-features"`. Much faster than trying to parse their descriptions.

**Comment by VelocityRa** [comment]
Btw the issue is not just for documentation, it's a question too.
I would appreciate an answer for `1.`

**Comment by strega-nil** [comment]
@VelocityRa oh, sorry, I missed this! You can use the `VCPKG_MANIFEST_FEATURES` and `VCPKG_MANIFEST_NO_DEFAULT_FEATURES` settings of the CMake toolchain; however the actual flags are experimental. You can add the `--x-no-default-features` and `--x-feature` settings to get access to them from the CLI. For example, `vcpkg install --x-feature=f1 --x-feature=x2 --x-no-default-features`.

**Comment by VelocityRa** [comment]
@strega-nil Ah I see, thanks!

**Comment by PhoebeHui** [comment]
It has been added to https://github.com/microsoft/vcpkg/blob/master/docs/users/manifests.md.
