### ISSUE TITLE
"A suitable version of git was not found..." (after merge of: [vcpkg] add env var VCPKG_OVERLAY_TRIPLETS)

### ISSUE THREAD

**Issue by sschnug** [microsoft/vcpkg#13790]
```
A suitable version of git was not found (required v2.7.4) and unable to automatically download a portable one. Please install a newer version of git.
```

_Originally posted by @JackBoosY in https://github.com/microsoft/vcpkg/pull/12790#issuecomment-679824358_

This is happening in my CI/CD pipeline now (which was brave enough to track vcpkg/master) and vanishes if i go one commit back towards 8776756 (before the mentioned merge).

(Somehow i wasn't even able to circumvent this by using `RUN export VCPKG_FORCE_SYSTEM_BINARIES=1`)

For me, this is triggered by a Dockerfile looking like:

```
FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Berlin
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && apt-get install -y \
    build-essential autoconf git libtool pkg-config cmake doxygen ninja-build curl zip unzip tar \
    python3 python3-dev python3-pip python3-numpy \
    && apt-get clean

RUN pip3 install sphinx sphinx_rtd_theme breathe pytest grpcio protobuf psutil

WORKDIR /WORKING

RUN export VCPKG_BUILD_TYPE=release

RUN git clone https://github.com/microsoft/vcpkg \
    && ./vcpkg/bootstrap-vcpkg.sh \
    && ./vcpkg/vcpkg integrate install \
    && ./vcpkg/vcpkg install abseil \
    && ./vcpkg/vcpkg install protobuf \
    && ./vcpkg/vcpkg install grpc \
    && ./vcpkg/vcpkg install glog \
    && ./vcpkg/vcpkg install gtest \
    && ./vcpkg/vcpkg install benchmark \
    && ./vcpkg/vcpkg install liblemon
    ....
```

**Comment by coryan** [comment]
Seems like removing this line:

https://github.com/microsoft/vcpkg/pull/12790/files#diff-6881438d3612c1d09d825d25d2d08f33L1181

changed `vcpkg` to always search for tools using extensions (`.exe`, `.cmd`, `.bat`) which is not the right thing on Unices.

**Comment by yay** [comment]
Can confirm:
```
$ vcpkg x-history glm   
A suitable version of git was not found (required v2.7.4) and unable to automatically download a portable one. Please install a newer version of git.
$ git version
git version 2.28.0
```

**Comment by paspro** [comment]
I confirm this problem when trying to install any package on Ubuntu 20.04

`Detecting compiler hash for triplet x64-linux...
A suitable version of git was not found (required v2.7.4) and unable to automatically download a portable one. Please install a newer version of git.
`

**Comment by Neumann-A** [comment]
Thx for finding the oversight. Somehow nobody saw it before although it was so trivial.

**Comment by JackBoosY** [comment]
Closed this issue via #13790 merged.

**Comment by SebastienEGNER** [comment]
I still have this problem, even after using `git pull`.

```
$ git pull && git --version && ./vcpkg install tiff
Already up to date.
git version 2.28.0
Computing installation plan...
The following packages will be built and installed:
    tiff[core]:x64-linux
Detecting compiler hash for triplet x64-linux...
A suitable version of git was not found (required v2.7.4) and unable to automatically download a portable one. Please install a newer version of git.
```

**Comment by Neumann-A** [comment]
you need to rebootstrap vcpkg after git pull.

**Comment by SebastienEGNER** [comment]
Oh indeed, it worked! Thank you, I didn't know about that :)
