### ISSUE TITLE
[x264:x64-windows-static] non optimized builds

### ISSUE THREAD

**Issue by kliffgomel** [microsoft/vcpkg#13792]
Compiled x264 binary for windows x64 does not support using processor capabilities. Conversion in this mode is much slower.

Microsoft Windows [Version 10.0.19041.508]
Vcpkg package management program version 2020.06.15-nohash
Microsoft (R) C/C++ Optimizing Compiler Version 19.27.29111 for x64

**If I am using VCPKG MSVC compiled version of x264:**

x264 -V
x264 0.157.x
built on Sep 28 2020, msvc: 19.27 (192729111)
x264 configuration: --chroma-format=all
libx264 configuration: --chroma-format=all
x264 license: GPL version 2 or later

x264.exe --profile high --preset placebo --me umh --merange 32 --keyint infinite --tune ssim --bitrate 10000 --fps 50 --sar 1:1 --input-res 1920x1080 crowd_run_1080p50.y4m -o crowd_run-x264-msvc.h264

x264 [info]: using SAR=1/1
**x264 [info]: using cpu capabilities: none!**
x264 [info]: profile High, level 5.1, 4:2:0, 8-bit
x264 [info]: frame I:1     Avg QP:24.76  size:414003
x264 [info]: frame P:125   Avg QP:35.47  size: 58470
x264 [info]: frame B:374   Avg QP:38.38  size: 12636
x264 [info]: consecutive B-frames:  0.2%  0.0%  4.2% 89.6%  6.0%  0.0%  0.0%  0.0%  0.0%  0.0%  0.0%  0.0%  0.0%  0.0%  0.0%  0.0%  0.0%
x264 [info]: mb I  I16..4:  9.9% 55.0% 35.1%
x264 [info]: mb P  I16..4:  1.1%  8.1%  1.6%  P16..4: 34.9% 26.0% 12.3%  1.5%  0.1%    skip:14.4%
x264 [info]: mb B  I16..4:  0.1%  0.4%  0.0%  B16..8: 26.2% 14.2%  2.7%  direct: 2.2%  skip:54.0%  L0:33.6% L1:49.1% BI:17.3%
x264 [info]: final ratefactor: 27.01
x264 [info]: 8x8 transform intra:73.7% inter:49.6%
x264 [info]: direct mvs  spatial:97.6% temporal:2.4%
x264 [info]: coded y,uvDC,uvAC intra: 67.0% 62.7% 29.9% inter: 11.5% 5.8% 0.5%
x264 [info]: i16 v,h,dc,p: 27% 18% 25% 29%
x264 [info]: i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 24% 11% 20%  6%  6%  8%  7%  9%  9%
x264 [info]: i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 23% 11% 24%  6%  7%  8%  6%  7%  7%
x264 [info]: i8c dc,h,v,p: 36% 20% 26% 18%
x264 [info]: Weighted P-Frames: Y:0.8% UV:0.0%
x264 [info]: ref P L0: 55.3% 13.5% 10.7%  3.0%  2.8%  2.3%  2.4%  1.4%  1.5%  1.0%  0.9%  0.7%  0.8%  0.8%  1.3%  1.5%
x264 [info]: ref B L0: 96.3%  2.0%  0.6%  0.3%  0.2%  0.1%  0.1%  0.1%  0.1%  0.1%  0.0%  0.0%  0.0%  0.0%  0.0%
x264 [info]: ref B L1: 99.5%  0.5%
x264 [info]: kb/s:9958.88

**encoded 500 frames, 2.13 fps, 9958.88 kb/s** 

**If I take the REFERENCE BUILD x264 with GCC:**

Version output:
x264 0.161.3018 db0d417
(lsmash 2.16.1)
built on Sep 22 2020, gcc: 10.2.0
x264 configuration: --chroma-format=all
libx264 configuration: --chroma-format=all
x264 license: GPL version 2 or later

Encoder output:
y4m [info]: 1920x1080p 1:1 @ 50/1 fps (cfr)
x264 [info]: using SAR=1/1
**x264 [info]: using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2**
x264 [info]: profile High, level 5.1, 4:2:0, 8-bit
x264 [info]: frame I:1     Avg QP:24.73  size:414543
x264 [info]: frame P:125   Avg QP:35.46  size: 58464
x264 [info]: frame B:374   Avg QP:38.42  size: 12631
x264 [info]: consecutive B-frames:  0.2%  0.0%  4.2% 89.6%  6.0%  0.0%  0.0%  0.0%  0.0%  0.0%  0.0%  0.0%  0.0%  0.0%  0.0%  0.0%  0.0%
x264 [info]: mb I  I16..4: 10.8% 54.0% 35.2%
x264 [info]: mb P  I16..4:  1.1%  8.0%  1.6%  P16..4: 35.0% 25.9% 12.3%  1.5%  0.1%    skip:14.4%
x264 [info]: mb B  I16..4:  0.1%  0.4%  0.0%  B16..8: 26.4% 14.2%  2.7%  direct: 2.2%  skip:53.9%  L0:33.6% L1:49.1% BI:17.3%
x264 [info]: final ratefactor: 27.01
x264 [info]: 8x8 transform intra:73.5% inter:49.7%
x264 [info]: direct mvs  spatial:97.6% temporal:2.4%
x264 [info]: coded y,uvDC,uvAC intra: 67.0% 62.6% 30.0% inter: 11.5% 5.8% 0.5%
x264 [info]: i16 v,h,dc,p: 27% 18% 26% 29%
x264 [info]: i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 24% 11% 20%  6%  6%  8%  7%  9%  9%
x264 [info]: i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 23% 11% 24%  6%  7%  8%  6%  7%  7%
x264 [info]: i8c dc,h,v,p: 36% 20% 26% 18%
x264 [info]: Weighted P-Frames: Y:0.8% UV:0.0%
x264 [info]: ref P L0: 55.1% 13.5% 10.8%  3.1%  2.8%  2.3%  2.5%  1.4%  1.5%  1.1%  0.9%  0.7%  0.8%  0.9%  1.3%  1.5%
x264 [info]: ref B L0: 96.2%  2.0%  0.6%  0.3%  0.2%  0.1%  0.1%  0.1%  0.1%  0.1%  0.0%  0.0%  0.0%  0.0%  0.0%
x264 [info]: ref B L1: 99.5%  0.5%
x264 [info]: kb/s:9957.26

**encoded 500 frames, 5.85 fps, 9957.26 kb/s** 

**2.7x faster encoding speed!**

Perhaps the problem is that the portfile for x264 port contains the "--disable-asm" option, or perhaps the compiler settings for this project are not optimized.

[build-x64-windows-static-rel-err.log](https://github.com/microsoft/vcpkg/files/5294782/build-x64-windows-static-rel-err.log)
[build-x64-windows-static-rel-out.log](https://github.com/microsoft/vcpkg/files/5294783/build-x64-windows-static-rel-out.log)
[config-x64-windows-static-rel-out.log](https://github.com/microsoft/vcpkg/files/5294784/config-x64-windows-static-rel-out.log)
[install-x64-windows-static-rel-out.log](https://github.com/microsoft/vcpkg/files/5294785/install-x64-windows-static-rel-out.log)
[stdout-x64-windows-static.log](https://github.com/microsoft/vcpkg/files/5294786/stdout-x64-windows-static.log)
[x64-windows-static.vcpkg_abi_info.txt](https://github.com/microsoft/vcpkg/files/5294787/x64-windows-static.vcpkg_abi_info.txt)

**Comment by JackBoosY** [comment]
@Neumann-A Could you take a look?

Thanks.

**Comment by Neumann-A** [comment]
@JackBoosY Should be done by somebody who is using it. I wasn't the one who added the `--disable-asm` option. I assume it was added because `cl` does not support forwarding assembly sources to an assembly compiler. If you are lucky setting up CCAS and the corresponding flags is enough (requires that the makefiles correctly use CCAS instead of CC)

@kliffgomel: Comparing two different compilers is questionable since they will optimize a lot different. MSVC is known optimize not as well as gcc. So please supply an MSVC reference build.

**Comment by kliffgomel** [comment]
I am still inclined to believe that compiler optimization will not play a big role here, since most of the resource-intensive operations in this codec have been translated into assembler and are highly optimized at the code level. Therefore, I believe that the problem here is related to the parameters set during the configuration.
There are not so many reference codec assemblies compiled by msvc, I have only binaries from http://msystem.waw.pl/x265/, compiled using VS 2015.
There is an old version of the x264 codec 0.155.2901 7d0ff22, and in comparison with the gcc build of the latest version, it is 7% slower, but not 3 times slower when compared with the build from vcpkg.
I also note that I compared the compiled vcpkg and gcc versions of the x265 codec, there is no difference in performance, since the vcpkg version supported all processor optimizations, just like the gcc version.

**Comment by JackBoosY** [comment]
Hi @melchi45, can you please take a look?

Thanks.

**Comment by kliffgomel** [comment]
> 
> 
> Hi @melchi45, can you please take a look?
> 
> Thanks.

It looks like the "--disable-asm" option was set in the original potfile. But why this was done is not clear to me.
