### ISSUE TITLE
Can not find FFmpeg by find_package

### ISSUE THREAD

**Issue by linuxaged** [Microsoft/vcpkg#1379]
packages have been installed: 

    C:\Users\bugki>vcpkg list
    ffmpeg:x64-windows          3.2.4-3          a library to decode, encode, transcode, mux, demu...
    glew:x86-windows            2.0.0-1          The OpenGL Extension Wrangler Library (GLEW) is a...
    glfw3:x86-windows           3.2.1-1          GLFW is a free, Open Source, multi-platform libra...
    zlib:x64-windows            1.2.11           A compression library

My CMake script:

    cmake_minimum_required( VERSION 3.6.0 )

    project ( v2t )

    add_executable ( v2t WIN32 main.cpp H264_Decoder.cpp YUV420P_Player.cpp )

    target_compile_options( v2t PRIVATE -Wall )

    find_package( FFmpeg REQUIRED )
    target_link_libraries( v2t FFmpeg )
    target_include_directories( v2t PRIVATE ${FFMPEG_INCLUDE_DIR} )

The CMake Error:

    CMake Error at CMakeLists.txt:9 (find_package):
      By not providing "FindFFmpeg.cmake" in CMAKE_MODULE_PATH this project has
      asked CMake to find a package configuration file provided by "FFmpeg", but
      CMake did not find one.

      Could not find a package configuration file provided by "FFmpeg" with any
      of the following names:

        FFmpegConfig.cmake
        ffmpeg-config.cmake

      Add the installation prefix of "FFmpeg" to CMAKE_PREFIX_PATH or set
      "FFmpeg_DIR" to a directory containing one of the above files.  If "FFmpeg"
      provides a separate development package or SDK, be sure it has been
      installed.

And i use CMake GUI v3.8.2, The vcpkg cmake toolchain has been selected when config my project.

**Comment by jasjuang** [comment]
If you look into the original source https://github.com/FFmpeg/FFmpeg there is no CMakeLists in there. Which FFmpeg were you using originally that supports cmake?

**Comment by linuxaged** [comment]
@jasjuang Got it! FFmpeg is not supported, so I need to  use `find_path` and `find_library`  instead of `find_package`. Thanks!

    # To find and use ffmpeg
    find_path( AVCODEC_INCLUDE_DIR libavcodec/avcodec.h )
    find_library( AVCODEC_LIBRARY libavcodec )
    target_include_directories( v2t PRIVATE ${AVCODEC_INCLUDE_DIR} )
    target_link_libraries( v2t ${AVCODEC_LIBRARY} )

**Comment by Daniate** [comment]
To use `find_package`, we should change `CMAKE_PREFIX_PATH`, add it before `find_package`, for example:
```
list(APPEND CMAKE_PREFIX_PATH "C:/vcpkg/packages/ffmpeg_x64-windows")
find_package(FFMPEG REQUIRED)
target_include_directories(${PROJECT_NAME} PRIVATE ${FFMPEG_INCLUDE_DIRS})
target_link_directories(${PROJECT_NAME} PRIVATE ${FFMPEG_LIBRARY_DIRS})
target_link_libraries(${PROJECT_NAME} PRIVATE ${FFMPEG_LIBRARIES})
```
![image](https://github.com/microsoft/vcpkg/assets/1210634/6d36183d-9755-40c7-b2eb-be8e7fee1fd2)

**Comment by dg0yt** [comment]
> To use `find_package`, we should change `CMAKE_PREFIX_PATH`, add it before `find_package`, for example:
> ~~~
> list(APPEND CMAKE_PREFIX_PATH "C:/vcpkg/packages/ffmpeg_x64-windows")

No. `packages` is just a staging dir and should not be used.
What you should use is the vcpkg cmake toolchain. It is not just setting up paths but also loading wrappers for CMake modules. 

Really: vcpkg port `ffmpeg` installs a wrapper and a Find module which enables `find_package(FFMPEG)` to work.

**Comment by Daniate** [comment]
> > To use `find_package`, we should change `CMAKE_PREFIX_PATH`, add it before `find_package`, for example:
> > ```
> > list(APPEND CMAKE_PREFIX_PATH "C:/vcpkg/packages/ffmpeg_x64-windows")
> > ```
> 
> No. `packages` is just a staging dir and should not be used. What you should use is the vcpkg cmake toolchain. It is not just setting up paths but also loading wrappers for CMake modules.
> 
> Really: vcpkg port `ffmpeg` installs a wrapper and a Find module which enables `find_package(FFMPEG)` to work.

Yeah, follow the official guidelines: [https://learn.microsoft.com/en-us/vcpkg/users/buildsystems/cmake-integration](https://learn.microsoft.com/en-us/vcpkg/users/buildsystems/cmake-integration)
