### ISSUE TITLE
How do I install dlls compiled by vcpkg using cmake install() function ?

### ISSUE THREAD

**Issue by Celeborn2BeAlive** [microsoft/vcpkg#13797]
I was wondering how I can instruct CMake to install the dlls compiled by vcpkg next to my executables using the install() command (on Windows, with Visual Studio 2019 generator for CMake). Here is more explanations:

The CMakeLists of the project I'm playing with is this one: https://gitlab.com/c2ba_sandbox/c_cpp/exploring-unit-tests-in-c/-/blob/master/CMakeLists.txt

I'm linking my `test_hello_world` executable to the library `cmocka` which have been built with vcpkg (as shared library). When I compile my project, the cmocka.dll ends up correctly next to `test_hello_world.exe` in my build hierarchy, so it executes fine (I don't really know how it works behind the scene, but I guess the vcpkg CMake toolchain file is responsible in some way for copying the dll).

But when I run the install target (`cmake --build build/ --target install/ --config Release`), the `cmocka.dll` is not copied in the installation folder that I've set with CMAKE_PREFIX_PATH.

So is there any way I can instruct CMake to copy the dlls where they should be ? I know I could do that by copying the vcpkg/installed/bin/*.dll files, but I would prefer a "CMake way".

If this ends up being possible, I think it would be great to add an example to https://github.com/microsoft/vcpkg/blob/master/docs/examples/installing-and-using-packages.md

**Comment by Neumann-A** [comment]
You don't copy dlls copied by vcpkg.....

Instead you use the cmake to do it:
https://cmake.org/cmake/help/latest/command/file.html#get-runtime-dependencies

because otherwise your buildscript has a hard dependency on vcpkg. 

vcpkg does something similar as GET_RUNTIME_DEPENDENCIES just at build time. You also could do that with CMake but it requires setting up an additional custom target.

**Comment by Celeborn2BeAlive** [comment]
Interesting, it seems to be what I need, thanks for the link and the explanation, I'll give it a try !
