### ISSUE TITLE
XMP not working - exiv2[unicode]:x86-windows-static

### ISSUE THREAD

**Issue by gdiObjects** [microsoft/vcpkg#13804]
exiv2[unicode]:x86-windows-static - 0.27.3#2
I noticed that all of the sudden XMP support seems to be missing.  So I checked config-x86-windows-static-out.log and I can see the following output:
-- XMP metadata support:               NO

Before it was always included. Is there a flag I need to include (if so, how)

[config-x86-windows-static-out.log](https://github.com/microsoft/vcpkg/files/5296112/config-x86-windows-static-out.log)

**Comment by LilyWangL** [comment]
Thanks for posting this issue. `XMP metadata support` need install feature `xmp`, you need use `.\vcpkg.exe install exiv2[xmp]:x86-windows-static`.

**Comment by gdiObjects** [comment]
Thanks!  That did the trick.  XMP is now available.
