### ISSUE TITLE
[parmetis:x64-linux] build failure

### ISSUE THREAD

**Issue by paspro** [microsoft/vcpkg#13814]
**Host Environment**
- OS: Linux (Ubuntu 20.04)
- Compiler: GCC version 10.2.0

**To Reproduce**
`./vcpkg install --triplet x64-linux parmetis`

**Failure logs** 
-Cut and past the appropriate build messages from the console output

`Computing installation plan...
The following packages will be built and installed:
    parmetis[core]:x64-linux
Detecting compiler hash for triplet x64-linux...
Starting package 1/1: parmetis:x64-linux
Building package parmetis[core]:x64-linux...
Could not locate cached archive: /home/panos/.cache/vcpkg/archives/1e/1ea6afd69b35f288ac27e8078080120c4e9b1190.zip
-- Using cached /home/panos/Libraries/vcpkg/downloads/parmetis-4.0.3.tar.gz
-- Cleaning sources at /home/panos/Libraries/vcpkg/buildtrees/parmetis/src/parmetis-4-deffb29652.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/panos/Libraries/vcpkg/downloads/parmetis-4.0.3.tar.gz
-- Applying patch fix-metis-vs14-math.patch
-- Applying patch fix-gklib-vs14-math.patch
-- Applying patch fix-root-cmakelist.patch
-- Applying patch fix-libparmetis-cmakelist.patch
-- Applying patch use_stdint.patch
-- Using source at /home/panos/Libraries/vcpkg/buildtrees/parmetis/src/parmetis-4-deffb29652.clean
-- Configuring x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:85 (message):
    Command failed: /home/panos/Libraries/vcpkg/downloads/tools/cmake-3.17.2-linux/cmake-3.17.2-Linux-x86_64/bin/cmake /home/panos/Libraries/vcpkg/buildtrees/parmetis/src/parmetis-4-deffb29652.clean -DSHARED=OFF -DCMAKE_MAKE_PROGRAM=/home/panos/Libraries/vcpkg/downloads/tools/ninja-1.10.1-linux/ninja -DCMAKE_SYSTEM_NAME=Linux -DBUILD_SHARED_LIBS=OFF -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/home/panos/Libraries/vcpkg/scripts/toolchains/linux.cmake -DVCPKG_TARGET_TRIPLET=x64-linux -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=external -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=/home/panos/Libraries/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_LINKER_FLAGS_RELEASE= -DVCPKG_LINKER_FLAGS_DEBUG= -DVCPKG_TARGET_ARCHITECTURE=x64 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -D_VCPKG_ROOT_DIR=/home/panos/Libraries/vcpkg -D_VCPKG_INSTALLED_DIR=/home/panos/Libraries/vcpkg/installed -DVCPKG_MANIFEST_INSTALL=OFF -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/home/panos/Libraries/vcpkg/packages/parmetis_x64-linux/debug
    Working Directory: /home/panos/Libraries/vcpkg/buildtrees/parmetis/x64-linux-dbg
    Error code: 1
    See logs for more information:
      /home/panos/Libraries/vcpkg/buildtrees/parmetis/config-x64-linux-dbg-out.log
      /home/panos/Libraries/vcpkg/buildtrees/parmetis/config-x64-linux-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:314 (vcpkg_execute_required_process)
  ports/parmetis/portfile.cmake:23 (vcpkg_configure_cmake)
  scripts/ports.cmake:79 (include)

Error: Building package parmetis:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: parmetis:x64-linux
  Vcpkg version: 2020.06.15-unknownhash

Additionally, attach any relevant sections from the log files above.
[config-x64-linux-dbg-err.log](https://github.com/microsoft/vcpkg/files/5298712/config-x64-linux-dbg-err.log)
[config-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/5298714/config-x64-linux-dbg-out.log)

`
-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by NancyLi1013** [comment]
Hi @paspro

This should be fixed via PR #17410  now, please update to the latest vcpkg to rebuild this port.
