### ISSUE TITLE
[New Port Request] resiprocate

### ISSUE THREAD

**Issue by simgunz** [microsoft/vcpkg#13817]
Library name:
resiprocate

Library description:
The project is dedicated to maintaining a complete, correct, and commercially usable implementation of SIP and a few related protocols.

Source repository URL
 https://github.com/resiprocate/resiprocate

Project homepage (if different from the source repository):
https://www.resiprocate.org/Main_Page

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
Depends on the library sipXtapi

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
