### ISSUE TITLE
[boost-filesystem] build failure

### ISSUE THREAD

**Issue by max-1975** [microsoft/vcpkg#13828]
**Host Environment**
- OS: Linux
- Compiler: gcc-10.2.0

**To Reproduce**
I'm using the vcpkg commit 397d3d7188cdcd4903b0bdb33b260dde993c1424
and I'm using it as CMake toolchain in my project.

**Failure logs** 

This is the output in my terminal:
---------------
Starting package 51/101: boost-filesystem:x64-linux
Building package boost-filesystem[core]:x64-linux...
Could not locate cached archive: /home/martinelli/.cache/vcpkg/archives/dd/ddb8d688b35420ca2968c398aeaea0b51cdbab0a.zip
-- Using cached /home/martinelli/igatools/vcpkg/downloads/boostorg-filesystem-boost-1.73.0.tar.gz
-- Cleaning sources at /home/martinelli/igatools/vcpkg/buildtrees/boost-filesystem/src/ost-1.73.0-a6fcc786f8.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/martinelli/igatools/vcpkg/downloads/boostorg-filesystem-boost-1.73.0.tar.gz
-- Using source at /home/martinelli/igatools/vcpkg/buildtrees/boost-filesystem/src/ost-1.73.0-a6fcc786f8.clean
-- Building release...
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:141 (message):
    Command failed: /home/martinelli/igatools/vcpkg/downloads/tools/cmake-3.17.2-linux/cmake-3.17.2-Linux-x86_64/bin/cmake --build . --config Debug --target install -- -v -j33
    Working Directory: /home/martinelli/igatools/vcpkg/buildtrees/boost-filesystem/x64-linux-dbg
    See logs for more information:
      /home/martinelli/igatools/vcpkg/buildtrees/boost-filesystem/install-x64-linux-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:92 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  /home/martinelli/build_igatools_debug/vcpkg_installed/x64-linux/share/boost-build/boost-modular-build.cmake:136 (vcpkg_install_cmake)
  /home/martinelli/build_igatools_debug/vcpkg_installed/x64-linux/share/boost-build/boost-modular-build.cmake:141 (unix_build)
  ports/boost-filesystem/portfile.cmake:12 (boost_modular_build)
  scripts/ports.cmake:79 (include)

Error: Building package boost-filesystem:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-filesystem:x64-linux
  Vcpkg version: 2020.06.15-unknownhash

Additionally, attach any relevant sections from the log files above.
CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:369 (message):
  Running vcpkg install - failed
Call Stack (most recent call first):
  /usr/share/cmake/Modules/CMakeDetermineSystem.cmake:93 (include)
  CMakeLists.txt:71 (project)

CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
-- Configuring incomplete, errors occurred!

---------------

[install-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/5305711/install-x64-linux-dbg-out.log)

**Comment by max-1975** [comment]
I'm using vcpkg commit cabe5d0b7b0f2741bad9cb2926f89e37a9ecf2b4 and the issue now is on boost-atomic

    Building package boost-atomic[core]:x64-linux...
    Could not locate cached archive: 
    /home/martinelli/.cache/vcpkg/archives/26/2693649e1b13ec010d30e6b3d8ba492c65415d2a.zip
    -- Using cached /home/martinelli/igatools/vcpkg/downloads/boostorg-atomic-boost-1.73.0.tar.gz
    -- Cleaning sources at /home/martinelli/igatools/vcpkg/buildtrees/boost-atomic/src/ost-1.73.0-3741af45ab.clean. Use --editable to skip cleaning for the packages you specify.
    -- Extracting source /home/martinelli/igatools/vcpkg/downloads/boostorg-atomic-boost-1.73.0.tar.gz
    -- Using source at /home/martinelli/igatools/vcpkg/buildtrees/boost-atomic/src/ost-1.73.0-3741af45ab.clean
    -- Building release...
    -- Configuring x64-linux-dbg
    -- Configuring x64-linux-rel
    -- Building x64-linux-dbg
    CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:141 (message):
        Command failed: /home/martinelli/igatools/vcpkg/downloads/tools/cmake-3.17.2-linux/cmake-3.17.2-Linux-x86_64/bin/cmake --build . --config Debug --target install -- -v -j33
        Working Directory: /home/martinelli/igatools/vcpkg/buildtrees/boost-atomic/x64-linux-dbg
        See logs for more information:
          /home/martinelli/igatools/vcpkg/buildtrees/boost-atomic/install-x64-linux-dbg-out.log

    Call Stack (most recent call first):
      scripts/cmake/vcpkg_build_cmake.cmake:92 (vcpkg_execute_build_process)
      scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
      /home/martinelli/build_igatools_debug/vcpkg_installed/x64-linux/share/boost-build/boost-modular-build.cmake:136 (vcpkg_install_cmake)
      /home/martinelli/build_igatools_debug/vcpkg_installed/x64-linux/share/boost-build/boost-modular-build.cmake:141 (unix_build)
      ports/boost-atomic/portfile.cmake:12 (boost_modular_build)
      scripts/ports.cmake:79 (include)


    Error: Building package boost-atomic:x64-linux failed with: BUILD_FAILED
    Please ensure you're using the latest portfiles with `./vcpkg update`, then
    submit an issue at https://github.com/Microsoft/vcpkg/issues including:
      Package: boost-atomic:x64-linux
      Vcpkg version: 2020.06.15-unknownhash

    Additionally, attach any relevant sections from the log files above.
    CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:369 (message):
      Running vcpkg install - failed
    Call Stack (most recent call first):
      /usr/share/cmake/Modules/CMakeDetermineSystem.cmake:93 (include)
    CMakeLists.txt:71 (project)


    CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
    -- Configuring incomplete, errors occurred!


Then looking into the file `/home/martinelli/igatools/vcpkg/buildtrees/boost-atomic/install-x64-linux-dbg-out.log` I have:

    [1/2] cd /home/martinelli/igatools/vcpkg/buildtrees/boost-atomic/src/ost-1.73.0-3741af45ab.clean/build && /home/martinelli/build_igatools_debug/vcpkg_installed/x64-linux/tools/boost-build/b2 --user-config=/home/martinelli/igatools/vcpkg/buildtrees/boost-atomic/x64-linux-dbg/user-config.jam --stagedir=/home/martinelli/igatools/vcpkg/buildtrees/boost-atomic/x64-linux-dbg/stage --build-dir=/home/martinelli/igatools/vcpkg/buildtrees/boost-atomic/x64-linux-dbg runtime-link=static link=static address-model=64 architecture=x86 target-os=linux toolset=gcc threadapi=pthread -sZLIB_BINARY=z -sZLIB_LIBPATH="/usr/lib/libz.so" -sBZIP2_BINARY=bz2d -sBZIP2_LIBPATH="BZIP2_LIBPATH-NOTFOUND" variant=debug --layout=system --with-atomic --with-random --with-date_time --with-filesystem --with-system --with-thread --with-chrono -sZLIB_INCLUDE="/usr/include" -sBZIP2_INCLUDE="/usr/include" -sICU_PATH="/usr" -j32 -sBOOST_ROOT=/home/martinelli/build_igatools_debug/vcpkg_installed/x64-linux/tools/boost-build -sBOOST_BUILD_PATH=/home/martinelli/build_igatools_debug/vcpkg_installed/x64-linux/tools/boost-build --debug-configuration --ignore-site-config --hash -q threading=multi debug-symbols=on stage
    FAILED: CMakeFiles/boost 
    cd /home/martinelli/igatools/vcpkg/buildtrees/boost-atomic/src/ost-1.73.0-3741af45ab.clean/build && /home/martinelli/build_igatools_debug/vcpkg_installed/x64-linux/tools/boost-build/b2 --user-config=/home/martinelli/igatools/vcpkg/buildtrees/boost-atomic/x64-linux-dbg/user-config.jam --stagedir=/home/martinelli/igatools/vcpkg/buildtrees/boost-atomic/x64-linux-dbg/stage --build-dir=/home/martinelli/igatools/vcpkg/buildtrees/boost-atomic/x64-linux-dbg runtime-link=static link=static address-model=64 architecture=x86 target-os=linux toolset=gcc threadapi=pthread -sZLIB_BINARY=z -sZLIB_LIBPATH="/usr/lib/libz.so" -sBZIP2_BINARY=bz2d -sBZIP2_LIBPATH="BZIP2_LIBPATH-NOTFOUND" variant=debug --layout=system --with-atomic --with-random --with-date_time --with-filesystem --with-system --with-thread --with-chrono -sZLIB_INCLUDE="/usr/include" -sBZIP2_INCLUDE="/usr/include" -sICU_PATH="/usr" -j32 -sBOOST_ROOT=/home/martinelli/build_igatools_debug/vcpkg_installed/x64-linux/tools/boost-build -sBOOST_BUILD_PATH=/home/martinelli/build_igatools_debug/vcpkg_installed/x64-linux/tools/boost-build --debug-configuration --ignore-site-config --hash -q threading=multi debug-symbols=on stage
    /bin/sh: /home/martinelli/build_igatools_debug/vcpkg_installed/x64-linux/tools/boost-build/b2: Permission denied
    ninja: build stopped: subcommand failed.

that is suggesting that the command `/home/martinelli/build_igatools_debug/vcpkg_installed/x64-linux/tools/boost-build/b2` has the wrong permission. Checking the permission of that file I have:

    -rw-r--r-- 1 martinelli martinelli 243328 Oct  6 17:20 /home/martinelli/build_igatools_debug/vcpkg_installed/x64-linux/tools/boost-build/b2

but I think should be executable...

**Comment by PhoebeHui** [comment]
@max-1975, I can't repro this issue locally, from your log, it failed due to permission issue. it might relate to antivirus software, could also check that?

Failures:
/bin/sh: /home/martinelli/build_igatools_debug/vcpkg_installed/x64-linux/tools/boost-build/b2: Permission denied

**Comment by PhoebeHui** [comment]
@max-1975, does this still be an issue for you?

**Comment by max-1975** [comment]
I've just used the vcpkg commit 0bf3923f9fab4001 and now it's working fine.

**Comment by PhoebeHui** [comment]
Good to know.
