### ISSUE TITLE
Does vcpkg_from_github supports checking out a particular commit from a particular branch?

### ISSUE THREAD

**Issue by jasjuang** [Microsoft/vcpkg#1382]
Currently `vcpkg install ceres` compiles but when we use `find_package(Ceres REQUIRED)` in our own code there will be cmake errors as indicated in the comments in #1250. According to the comments, this error should be fixed in newer ceres commits. However, the problem is when I do `vcpkg install ceres --head` there is a compilation error related to suitesparse and I am trying to debug and figure out what commit introduces the compilation error. 

The problem is I am unable to build suitesparse successfully from source, and if I build ceres from source it's not able to identify suitesparse in vcpkg for some reason and it builds without suitesparse support. Hence I am stuck on figuring out which new commit introduces the compilation error. Does vcpkg_from_github supports checking out a particular commit? Now I can only choose between stable releases or the latest commit on github.

**Comment by atkawa7** [comment]
@jasjuang I think it does. For example I usually do this when the latest stable version does not compile
```
vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO repo
    REF commit_ref / stable_version_number
    SHA512 shar
    HEAD_REF master
)
```

**Comment by jasjuang** [comment]
@atkawa7 I tried something like

``````
vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO ceres-solver/ceres-solver
    REF 58bacda / 1.12.0
    SHA512 98468707e49f81ccee015c3cea907193878a69fe084d2cced10413dbdb57e584d5af08deb09f831f307745a2126c7629ffd9d29067636cde5de0b30f0b384613
    HEAD_REF master
)
``````

58bacda is the latest commit as indicated in here https://github.com/ceres-solver/ceres-solver/commits/master

but when I do a `vcpkg install ceres` I get an error like

``````
CMake Error at scripts/cmake/vcpkg_from_github.cmake:85 (message):
  Could not determine source path:
  'C:/dev/vcpkg/buildtrees/ceres/src/ceres-solver-58bacda' does not exist
``````

Am I doing it right?

**Comment by atkawa7** [comment]
@jasjuang I am sorry I didn't explain correctly. The / sign means or in this case

**Comment by jasjuang** [comment]
If I change it to

``````
vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO ceres-solver/ceres-solver
    REF 58bacda
    SHA512 98468707e49f81ccee015c3cea907193878a69fe084d2cced10413dbdb57e584d5af08deb09f831f307745a2126c7629ffd9d29067636cde5de0b30f0b384613
    HEAD_REF master
)
`````` 

same error occurs. What am I doing wrong?

**Comment by atkawa7** [comment]
The reason the ref is wrong. I think it should 58bacdacae143780005757c485a0b319e1aea637

**Comment by jasjuang** [comment]
@atkawa7 You are right it needs the full ref. Thanks for your help!
