### ISSUE TITLE
[android] applocal.ps1 attempts to run dumpbin on Android binaries resulting in errors, even when the build otherwise succeeds

### ISSUE THREAD

**Issue by aiyou4love** [microsoft/vcpkg#13834]
**Environment**
- OS: win10
- Compiler: revision
android r16b

**To Reproduce**
cmake .. -DVCPKG_TARGET_TRIPLET=arm64-android
  -DCMAKE_TOOLCHAIN_FILE=/vcpkg/scripts/buildsystems/vcpkg.cmake

**Failure logs** 
-(please attached failure logs)
```
-- Configuring done
-- Generating done
-- Build files have been written to: C:/unseen/unseen-cpp/source/scripts/build.obj/client.arm64
[122/123] Linking CXX shared library bridge\liblaunch.so
 C:\setup\vcpkg\vcpkg\scripts\buildsystems\msbuild\applocal.ps1:60 
+     $a = $(dumpbin /DEPENDENTS $targetBinary | ? { $_ -match "^    [^ ...
+            ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (dumpbin:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

[122/123] Install the project...
-- Install configuration: "Debug"
-- Installing: /build.bin/unity.arm64/config.json
-- Installing: /build.bin/client.arm64/liblaunch.so
```

**Comment by JonLiu1993** [comment]
Ping @aiyou4love for response

**Comment by BillyONeal** [comment]
As far as I know nothing about this should be changed.

**Comment by JackBoosY** [comment]
We should make some judgment to the android triplet.

**Comment by dg0yt** [comment]
This block has a wrong entry condition:

https://github.com/microsoft/vcpkg/blob/7e7dad5fe20cdc085731343e0e197a7ae655555b/scripts/buildsystems/vcpkg.cmake#L631-L658

**Comment by JackBoosY** [comment]
@dg0yt Yeah, macros for android should be used here.

**Comment by JackBoosY** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
