### ISSUE TITLE
Why does the port of boost-log have so many dependencies?

### ISSUE THREAD

**Issue by Markus87** [microsoft/vcpkg#13845]
I am currently trying to build all my third party libraries for android with vcpkg and it seems to work great so far.

But boost-log causes problems because it pulls so many dependencies to other boost modules.
boost-log requires boost-locale this requires libiconv and this is currently the end of me.

In the [documentation](https://www.boost.org/doc/libs/1_73_0/libs/log/doc/html/log/installation/config.html) it says:
`The logging library uses several other Boost libraries that require building too. These are Boost.Filesystem, Boost.System, Boost.DateTime, Boost.Thread and in some configurations Boost.Regex.
`

I built boost my self before and I also built it with boost-log but it never required boost-locale?
Also I have built all of those dependencies mentioned in the doc before, no need for boost-locale.

**Comment by PhoebeHui** [comment]
@Markus87, see https://github.com/boostorg/log/blob/develop/include/boost/log/detail/attachable_sstream_buf.hpp#L26, boost-log reference headers from boost-locale, so it has the dependency.

**Comment by Markus87** [comment]
Okay, thanks for pointing that out. I am still confused how this worked for me in the past.
I will dive deeper into my old builds of boosts and will get back with my findings once I understand it.

**Comment by Markus87** [comment]
@PhoebeHui I just checked my old build script for boost for android and let it run again and it works with no problem, no locale required. The header you referenced is the only locale header in all of boost log and to me it seems it is header only. There is nothing that could be missed if locale is not built alongside the log module.

For me this dependency is wrong.

**Comment by PhoebeHui** [comment]
@Markus87, no this is needed. After removing the dependency, it will fail with following error when build boost-log:x86-windows:

F:\VCPKG\clean\buildtrees\boost-log\src\ost-1.73.0-3d57ed4a83.clean\include\boost/log/detail/attachable_sstream_buf.hpp(26): **fatal error C1083: Cannot open include file: 'boost/locale/utf.hpp': No such file or directory**

**Comment by Markus87** [comment]
Ok I just did build boost myself in Windows.
```
H:\Tmp\test\boost_1_73_0> .\bootstrap.bat
H:\Tmp\test\boost_1_73_0> .\b2 --build-dir=./build_boost --prefix=./installed_boost link=shared --with-log install
```
This is what got built:
![grafik](https://user-images.githubusercontent.com/6339979/95835930-25033500-0d3f-11eb-8932-3310cbed47f7.png)

So if the header is missing I would say it is because of how the ports of boost are done in vcpkg.
Maybe the boost-log port build is looking for the headers in the installed directory. And if only headers from boost get copied for modules which got built, then it would make sense. 
If I look at my example it looks like boost just copies all the headers in the install directory.

In my oppinion the hard dependency on boost-locale is wrong.

**Comment by PhoebeHui** [comment]
If doesn't add boost-locale as dependency, it would not install its headers to install directory, so yes, only headers from boost get copied for modules which got built.

**Comment by Markus87** [comment]
Okay, so in my mind it would be better to do it like boost did it itself.
Copy all headers first and add in dependencies only what must be linked against.

Maybe this would be possible if adding a port like boost-headers(-only).
The boost-locale port just would depend on that instead of all of the stuff it really does not need.
I think the boost ports in general would profit from that, other modules also seem to add more other boost modules to the build than really necessary.

**Comment by Markus87** [comment]
I spent some time trying to understand how vcpkg builds boost and learned:
* Dependencies are automatically looked up by searching the source of the module for included headers (vcpkg\scripts\boost\generate-ports.ps1:285)
* vcpkg never downloads all of boost, but only modules that are built

Knowing this I consider my original question answered.

In order to get what I need I would need to modify it to:
* Download always all of boost
  * manually manage dependencies for modules with header only dependencies
  * or get the script to know header only headers and ignore them if found
  * or allow to have a list for a module that marks dependencies as header only to ignore them if found in the script
