### ISSUE TITLE
Rebuild option, include header dependencies scan, file hash/checksum

### ISSUE THREAD

**Issue by sq2500** [microsoft/vcpkg#1384]
## Rebuild option for rebuilding libraries
To make it easier recompiling libraries due to Windows 10 insider, Visual Studio 2017, SDK updates

## Dependencies are specified in port files
- scan of include headers would provide possible quicker dependency resolution with source-level issues
- some library builds take rather long before failing

## File hash/checksum requires continuous editing to keep with libraries being updated
- source repository download of typical compressed files already contains checksum
- library dependencies should more informatively be stated as a explicit version, until version or at least version x.y.z
- more or less defies the purpose of being able to build directly source libraries for whatever OS/SDK/compiler/static/dll combo

**Comment by cmpute** [comment]
I met a similar situation. I edit an option in a portfile of a package, and I have to remove the package and reinstall it. It's more time-consuming than just to spot the change of portfile and to recompile the package.

**Comment by LilyWangL** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen.
