### ISSUE TITLE
OpenCV's VideoCapture does not seem to work: "Found 0 plugin(s) for ..." error message

### ISSUE THREAD

**Issue by stephanecharette** [microsoft/vcpkg#13859]
If I build OpenCV myself, or I install it with `sudo apt-get install libopencv-dev` (Ubuntu 20.04) then it works fine.

But if I install it with vcpkg, then at runtime I get failures and exceptions thrown when I attempt to use the `cv::VideoCapture` class.

This is the command I used to install it:

    `./vcpkg install --triplet x64-linux opencv[core,dnn,ffmpeg,jpeg,opengl,openmp,png,tiff,webp]`

This gives me OpenCV 4.3.0-0c6047baf6.  When I attempt to use the `cv::VideoCapture` class to open a .m4v or .webp video file, I get this output indicating that it is looking for some plugins which it fails to find:

```
[ INFO:0] global /home/stephane/src/vcpkg/buildtrees/opencv4/src/4.3.0-0c6047baf6.clean/modules/videoio/src/videoio_registry.cpp (187) VideoBackendRegistry VIDEOIO: Enabled backends(7, sorted by priority): FFMPEG(1000); GSTREAMER(990); INTEL_MFX(980); V4L2(970); CV_IMAGES(960); CV_MJPEG(950); FIREWIRE(940)
[ INFO:0] global /home/stephane/src/vcpkg/buildtrees/opencv4/src/4.3.0-0c6047baf6.clean/modules/videoio/src/backend_plugin.cpp (342) getPluginCandidates VideoIO pluigin (FFMPEG): glob is 'libopencv_videoio_ffmpeg*.so', 1 location(s)
[ INFO:0] global /home/stephane/src/vcpkg/buildtrees/opencv4/src/4.3.0-0c6047baf6.clean/modules/videoio/src/backend_plugin.cpp (349) getPluginCandidates     - /home/stephane/src/DarkHelp/build/src-tool: 0
[ INFO:0] global /home/stephane/src/vcpkg/buildtrees/opencv4/src/4.3.0-0c6047baf6.clean/modules/videoio/src/backend_plugin.cpp (353) getPluginCandidates Found 0 plugin(s) for FFMPEG
[ INFO:0] global /home/stephane/src/vcpkg/buildtrees/opencv4/src/4.3.0-0c6047baf6.clean/modules/videoio/src/backend_plugin.cpp (342) getPluginCandidates VideoIO pluigin (GSTREAMER): glob is 'libopencv_videoio_gstreamer*.so', 1 location(s)
[ INFO:0] global /home/stephane/src/vcpkg/buildtrees/opencv4/src/4.3.0-0c6047baf6.clean/modules/videoio/src/backend_plugin.cpp (349) getPluginCandidates     - /home/stephane/src/DarkHelp/build/src-tool: 0
[ INFO:0] global /home/stephane/src/vcpkg/buildtrees/opencv4/src/4.3.0-0c6047baf6.clean/modules/videoio/src/backend_plugin.cpp (353) getPluginCandidates Found 0 plugin(s) for GSTREAMER
[ INFO:0] global /home/stephane/src/vcpkg/buildtrees/opencv4/src/4.3.0-0c6047baf6.clean/modules/videoio/src/backend_plugin.cpp (342) getPluginCandidates VideoIO pluigin (INTEL_MFX): glob is 'libopencv_videoio_intel_mfx*.so', 1 location(s)
[ INFO:0] global /home/stephane/src/vcpkg/buildtrees/opencv4/src/4.3.0-0c6047baf6.clean/modules/videoio/src/backend_plugin.cpp (349) getPluginCandidates     - /home/stephane/src/DarkHelp/build/src-tool: 0
[ INFO:0] global /home/stephane/src/vcpkg/buildtrees/opencv4/src/4.3.0-0c6047baf6.clean/modules/videoio/src/backend_plugin.cpp (353) getPluginCandidates Found 0 plugin(s) for INTEL_MFX
[ INFO:0] global /home/stephane/src/vcpkg/buildtrees/opencv4/src/4.3.0-0c6047baf6.clean/modules/videoio/src/cap_images.cpp (282) icvExtractPattern Pattern: set_07/%04d-10-02-082129.m4v @ 2020
[ INFO:0] global /home/stephane/src/vcpkg/buildtrees/opencv4/src/4.3.0-0c6047baf6.clean/modules/videoio/src/cap_images.cpp (313) open CAP_IMAGES: Stop scanning. Can't read image file: set_07/2020-10-02-082129.m4v
OpenCV(4.3.0) Error: Unspecified error (could not open 'set_07/2020-10-02-082129.m4v') in open, file /home/stephane/src/vcpkg/buildtrees/opencv4/src/4.3.0-0c6047baf6.clean/modules/videoio/src/cap.cpp, line 177
Caught exception: OpenCV(4.3.0) /home/stephane/src/vcpkg/buildtrees/opencv4/src/4.3.0-0c6047baf6.clean/modules/videoio/src/cap.cpp:177: error: (-2:Unspecified error) could not open 'set_07/2020-10-02-082129.m4v' in function 'open'
```

Anyone know what it might be looking for, and how I can get it built or installed using `vcpkg` versus `apt-get install`?

**Comment by JackBoosY** [comment]
@cenit could you please take a look? 
Thanks.

**Comment by cenit** [comment]
Did you try building ffmpeg with x264 feature enabled?

**Comment by stephanecharette** [comment]
The exact command I ran is this:

    ./vcpkg install --triplet x64-linux opencv[core,dnn,ffmpeg,jpeg,opengl,openmp,png,tiff,webp]

**Comment by stephanecharette** [comment]
What is **REALLY** needed is some documentation from the vcpkg project on non-trivial packages like OpenCV.  Cause it isn't obvious what all the [core,dnn,ffmpeg,...etc...] parameters are when a user wants to build a library, where to find them, etc.

And from your question, now it sounds like vcpkg may not correctly install/build the necessary dependencies?  Should I instead have run:

    ./vcpkg install --triplet x64-linux opencv[core,dnn,ffmpeg,x264,jpeg,opengl,openmp,png,tiff,webp]

?  This is what I mean, the documentation is lacking and/or non-obvious for people not deeply involved in the vcpkg project.

Another problem:  looks like highgui isn't working either.  Is there another parameter required for that?  Maybe:

    ./vcpkg install --triplet x64-linux opencv[core,dnn,ffmpeg,x264,highgui,jpeg,opengl,openmp,png,tiff,webp]

?

**Comment by JackBoosY** [comment]
@cenit Ping for response.

**Comment by JackBoosY** [comment]
Hi, does #16882 fix this issue?

**Comment by genevanmeter** [comment]
> Another problem: looks like OpenCV's Highgui API calls aren't working either. Is there another parameter required for that? Maybe:

For Linux I needed to change -DWITH_GTK=OFF to ON in ports/opencv4/portfile.cmake.  Not sure patch vcpkg to enable it if Linux is detected.

**Comment by cenit** [comment]
> For Linux I needed to change -DWITH_GTK=OFF to ON in ports/opencv4/portfile.cmake. Not sure how to patch vcpkg to enable it if Linux is detected.

#13100 is required for that

**Comment by morphogencc** [comment]
I am having this same error with opencv in windows.  My exact command was:

```
./vcpkg install --triplet x64-windows-static opencv[core,opengl]
```

Installing the `ffmpeg` option recreates the same problem as #9571

**Comment by JackBoosY** [comment]
```
F:\vcpkg\buildtrees\opencv4\x64-windows-static-dbg\modules\dnn\graph.pb.h(17): fatal error C1189: #error:  This file was generated by an older version of protoc which is
```

**Comment by cenit** [comment]
@mcmtroffaes please see if you can help here

**Comment by nixondutt** [comment]
@stephanecharette I am having the same problem on Armadillo IOT device(Linux). did you find the solution?

**Comment by nixondutt** [comment]
@stephanecharette I am having the same problem on Armadillo IOT device(Linux). did you find the solution?

**Comment by stephanecharette** [comment]
Don't ask me, I gave up on vcpkg long ago.  Once I realized that building OpenCV on Linux using vcpkg doesn't build highgui and provides zero method for doing so, that was the end as far as I was concerned.  Even the most basic "hello world" type of tutorials with OpenCV requires highgui, so by leaving it out, it means that vcpkg is unusable.

**Comment by cenit** [comment]
it has high-gui since a long time now...

**Comment by cenit** [comment]
> @stephanecharette I am having the same problem on Armadillo IOT device(Linux). did you find the solution?

can you please share some logs?

**Comment by stephanecharette** [comment]
> it has high-gui since a long time now...

The last time you commented was April of last year, at which time you said that something else was needed.  I didn't see any further comments on this ticket saying that either Highgui or the video plugins problem was solved on Linux.

**Comment by nixondutt** [comment]
> > @stephanecharette I am having the same problem on Armadillo IOT device(Linux). did you find the solution?
> 
> can you please share some logs?

In my case, installing ffmpeg and gstreamer1.0 solved the issue. Thank you for the respond.

**Comment by cenit** [comment]
> > it has high-gui since a long time now...
> 
> The last time you commented was April of last year, at which time you said that something else was needed. I didn't see any further comments on this ticket saying that either Highgui or the video plugins problem was solved on Linux.

sorry but I cannot keep track of every issue... but if you follow the links that are posted above, every PR was merged and so this issue can be closed too (try and verify if it's true, please)

**Comment by JackBoosY** [comment]
According to @nixondutt comment, this issue was not resolved until `ffmpeg` and `gstreamer` became dependencies of opencv.

**Comment by cenit** [comment]
they are feature of opencv...
