### ISSUE TITLE
[msys2][bzip2:x86-windows] build failure

### ISSUE THREAD

**Issue by Eleart** [microsoft/vcpkg#13852]
**Host Environment**
- OS: Windows
- Package: bzip2:x86-windows
- Vcpkg version: 2020.06.15-nohash

**To Reproduce**
In c:/ :
```
 git clone https://github.com/microsoft/vcpkg
.\vcpkg\bootstrap-vcpkg.bat
.\vcpkg\vcpkg install pcl
```
**Failure logs** 
```
Could not locate cached archive: C:\Users\User\AppData\Local\vcpkg\archives\65\6532da60a30562cc34425daa524b71bed22ba786.zip
-- Fetching https://sourceware.org/git/bzip2.git...
-- Extracting source C:/vcpkg/downloads/bzip2-75a94bea3918e612b879d6a11ca64b8689526147.tar.gz
-- Applying patch fix-import-export-macros.patch
-- Using source at C:/vcpkg/buildtrees/bzip2/src/8689526147-1ef169fbaa.clean
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz...
-- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz... Failed. Status: 28;"Timeout was reached"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:181 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_find_acquire_program.cmake:438 (vcpkg_download_distfile)
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:270 (vcpkg_find_acquire_program)
  ports/bzip2/portfile.cmake:43 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:79 (include)

Error: Building package bzip2:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
```

**Additional context**
 - I don't use any proxy
 - I don't have any space in the path : C:\vcpkg
 - When I do .\vcpkg update it says me : 
`Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.`

 - And when I do a git pull : 
`Already up to date.`

**Comment by StarGate-One** [comment]
Failure is the download of files from the `repo.msys2.org` as it seems to be down at this time.

**Comment by sammoth** [comment]
Wasn't this fixed in https://github.com/microsoft/vcpkg/issues/10322

**Comment by eugene123tw** [comment]
`repo.msys2.org` is down, and I have to roll back to 2020.07 and change to another mirror

```
diff --git a/scripts/cmake/vcpkg_acquire_msys.cmake b/scripts/cmake/vcpkg_acquire_msys.cmake
index a663459eb..378456029 100644
--- a/scripts/cmake/vcpkg_acquire_msys.cmake
+++ b/scripts/cmake/vcpkg_acquire_msys.cmake
@@ -84,12 +84,12 @@ function(vcpkg_acquire_msys PATH_TO_ROOT_OUT)
     # download the new keyring, without it new packages and package updates
     # might not install
     vcpkg_download_distfile(KEYRING_PATH
-        URLS http://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz
+        URLS https://www2.futureware.at/~nickoe/msys2-mirror/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz
         FILENAME msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz
         SHA512 a5023fd17ccf6364bc6e27c5e63aea25f1fc264a5247cbae4008864c828c38c3e0b4de09ded650e28d2e24e319b5fcf7a9c0da0fa3a8ac81679470fc6bd120c9
     )
     vcpkg_download_distfile(KEYRING_SIG_PATH
-        URLS http://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig
+        URLS https://www2.futureware.at/~nickoe/msys2-mirror/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig
         FILENAME msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig
         SHA512 c326fefd13f58339afe0d0dc78306aa6ab27cafa8c4d792c2d34aa81fdd1f759d490990ab79daa9664a03a6dfa14ffd2b2ad828bf19a883410112d01f5ed6c4c
     )
```

**Comment by joas77** [comment]
> `repo.msys2.org` is down, and I have to roll back to `2020.07` branch and change to another mirror
> 
> ```
> diff --git a/scripts/cmake/vcpkg_acquire_msys.cmake b/scripts/cmake/vcpkg_acquire_msys.cmake
> index a663459eb..378456029 100644
> --- a/scripts/cmake/vcpkg_acquire_msys.cmake
> +++ b/scripts/cmake/vcpkg_acquire_msys.cmake
> @@ -84,12 +84,12 @@ function(vcpkg_acquire_msys PATH_TO_ROOT_OUT)
>      # download the new keyring, without it new packages and package updates
>      # might not install
>      vcpkg_download_distfile(KEYRING_PATH
> -        URLS http://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz
> +        URLS https://www2.futureware.at/~nickoe/msys2-mirror/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz
>          FILENAME msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz
>          SHA512 a5023fd17ccf6364bc6e27c5e63aea25f1fc264a5247cbae4008864c828c38c3e0b4de09ded650e28d2e24e319b5fcf7a9c0da0fa3a8ac81679470fc6bd120c9
>      )
>      vcpkg_download_distfile(KEYRING_SIG_PATH
> -        URLS http://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig
> +        URLS https://www2.futureware.at/~nickoe/msys2-mirror/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig
>          FILENAME msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig
>          SHA512 c326fefd13f58339afe0d0dc78306aa6ab27cafa8c4d792c2d34aa81fdd1f759d490990ab79daa9664a03a6dfa14ffd2b2ad828bf19a883410112d01f5ed6c4c
>      )
> ```
> 
> `vcpkg_acquire_msys` in the current `master` made mirror adding/changing more difficult, so I have to roll back to the previous stable version.

That worked for me thanks @eugene123tw !!

**Comment by malirod** [comment]
Proposed above solution worked for me. 

Is there any plans to fix this in the vcpkg upstream?

**Comment by FranciscoPombal** [comment]
The msys acquisition scripts should probably be changed to automatically retry downloads from a list of known official mirrors in case `repo.msys2.org` fails.

**Comment by JackBoosY** [comment]
Was this issue fixed in #13889?

**Comment by FranciscoPombal** [comment]
@JackBoosY It's fixed for me.

**Comment by JackBoosY** [comment]
Fixed.
