### ISSUE TITLE
[expat:x86-windows, bzip2:x86-windows, zlib:x86-windows, protobuf:x86-windows, fmt:x86-windows, benchmark:x86-windows, fribidi:x86-windows] build failure

### ISSUE THREAD

**Issue by ray42** [microsoft/vcpkg#13862]
**This affects multiple packages with the same error/cause, I don't want to raise many issues for what is essentially the same thing**

**Host Environment**

- OS: [Windows]
- Compiler: Visual Studio 2019 - Visual C++ 14.2

**To Reproduce**

`./vcpkg install expat:x86-windows`

**Failure logs** 

C:\VcPkgTest2>vcpkg install expat
Computing installation plan...
The following packages will be built and installed:
    expat[core]:x86-windows
Detecting compiler hash for triplet x86-windows...
Starting package 1/1: expat:x86-windows
Building package expat[core]:x86-windows...
Could not locate cached archive: C:\Users\raymon.white\AppData\Local\vcpkg\archives\0f\0f48b28cd0bf56cba86b891a4c94319bb03123f2.zip
-- Using cached C:/VcPkgTest2/downloads/libexpat-libexpat-c092d40c300c6d219cb3b111932a824022265370.tar.gz
-- Cleaning sources at C:/VcPkgTest2/buildtrees/expat/src/4022265370-c332802cb4.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/VcPkgTest2/downloads/libexpat-libexpat-c092d40c300c6d219cb3b111932a824022265370.tar.gz
-- Applying patch pkgconfig.patch
-- Using source at C:/VcPkgTest2/buildtrees/expat/src/4022265370-c332802cb4.clean
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz...
-- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz... Failed. Status: 7;"Couldn't connect to server"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:181 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_find_acquire_program.cmake:438 (vcpkg_download_distfile)
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:270 (vcpkg_find_acquire_program)
  ports/expat/portfile.cmake:30 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:79 (include)

Error: Building package expat:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: expat:x86-windows
  Vcpkg version: 2020.06.15-nohash

**Additional context**

All of the build failures I'm having seems to be because VcPkg cannot download https://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz. Everything was working last month (we do an update once a month). I have tried two different machines, I get the same build failure on both.

**Comment by ray42** [comment]
I just saw quite a few other people raised the same issue about repo.msys2.org being down. Is the solution to just wait until it comes back up?

**Comment by allennjusa** [comment]
Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz... Failed. Status: 28;"Timeout was reached"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:181 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

**Comment by ray42** [comment]
I'm not using a proxy.

**Comment by Hoikas** [comment]
repo.msys2.org is down. I'm not sure if there is any way to work around this issue at present.

**Comment by fishnet37222** [comment]
There's an issue about it at the MSYS2 repository ([https://github.com/msys2/MINGW-packages/issues/7084](https://github.com/msys2/MINGW-packages/issues/7084)).  One of the comments says it can be worked around by using a mirror from [https://github.com/msys2/MSYS2-packages/tree/master/pacman-mirrors](https://github.com/msys2/MSYS2-packages/tree/master/pacman-mirrors).

**Comment by ivanius51** [comment]
> There's an issue about it at the MSYS2 repository ([msys2/MINGW-packages#7084](https://github.com/msys2/MINGW-packages/issues/7084)). One of the comments says it can be worked around by using a mirror from https://github.com/msys2/MSYS2-packages/tree/master/pacman-mirrors.

thanks, for fix need use external links and download manually to "C:\vcpkg\downloads" files what need.

**Comment by JackBoosY** [comment]
Duplicate to #13852.
