### ISSUE TITLE
[New Port Request] EigenPy

### ISSUE THREAD

**Issue by jcarpent** [microsoft/vcpkg#13865]
Library name: EigenPy

Library description: Efficient Python bindings between Numpy/Eigen

Source repository URL: https://github.com/stack-of-tasks/eigenpy

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by jcarpent** [comment]
@JackBoosY Do you have a timeline horizon for this adding EigenPy into vcpkg?

**Comment by JackBoosY** [comment]
@jcarpent We wish contributors to add it : )

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
