### ISSUE TITLE
vcpkg.exe false positive, Trojan:Script/Wacatac.B!ml

### ISSUE THREAD

**Issue by Akarinnnnn** [microsoft/vcpkg#13864]
**Describe the bug**

**Environment**
- OS: Windows 10 2004 (10.0.19041.508)
- Compiler: Visual Studio 16.8 preview 3(or 16.7.5, I don't know which one was used)

**To Reproduce**
1. Build vcpkg
2. .\vcpkg list
3. .\vcpkg list
4. file contains virus or malware

**Expected behavior**
List packages successfully, not being deleted by Windows Defender

**Failure logs** 
```powershell
PS D:\vcpkg> .\vcpkg list
No packages are installed. Did you mean `search`?
PS D:\vcpkg> .\vcpkg list
程序“vcpkg.exe”无法运行: 无法成功完成操作，因为文件包含病毒或潜在的垃圾软件。所在位置 行:1 字符: 1
+ .\vcpkg list
+ ~~~~~~~~~~~~。
所在位置 行:1 字符: 1
+ .\vcpkg list
+ ~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed

```
**Additional context**
Windows Defender version:
反恶意软件客户端版本: 4.18.2008.9
引擎版本: 1.1.17500.4
防病毒软件版本: 1.325.72.0
反间谍软件版本: 1.325.72.0

**Comment by JackBoosY** [comment]
我们也收到了误报，由于使用master版本无法签名，该问题将在vcpkg定期发布binary之后解决。

**Comment by patmadigan** [comment]
I found the same bug today, with 16.7.5.  I only saw it with a console application running on a server.  The fix (based on a similar issue a couple years ago) is to go into Build,Configuration Manager, and set the Active solution platform = x64.

**Comment by JackBoosY** [comment]
Please track issue #14995 instead.
