### ISSUE TITLE
[expat[core]] build failure

### ISSUE THREAD

**Issue by MagnusHodne** [microsoft/vcpkg#13863]
**Host Environment**
- OS: [Windows 10 Home, version 1909]
- Compiler: ?

**To Reproduce**
`./vcpkg install wxwidgets`

**Failure logs** 
-- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz... Failed. Status: 7;"Couldn't connect to server"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:181 (message):

Failed to download file.
...

Call Stack (most recent call first):
  scripts/cmake/vcpkg_find_acquire_program.cmake:438 (vcpkg_download_distfile)
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:270 (vcpkg_find_acquire_program)
  ports/expat/portfile.cmake:30 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:79 (include)

Error: Building package expat:x86-windows failed with: BUILD_FAILED
...
  Package: expat:x86-windows
  Vcpkg version: 2020.06.15-nohash

**Additional context**
Am not using a proxy. Was able to successfully install other packages (rtmidi and portmidi).

**Comment by PrexCoder** [comment]
Hi, I'm having the exact same problem, I've tried to get some info about this problem, and it seems that something happen to their server, it happened a couple of days too but usually it gets back online after a couple of hours, I did not manage to find some status for their server, so I can't provide more info than that,cheers.

**Comment by PrexCoder** [comment]
I've found a link that may help you to with your problem https://gitter.im/msys2/msys2?at=5f772485aa7388396e8d84e4, here they speak about msys2 and their server status,feel free to join them 👍

**Comment by MagnusHodne** [comment]
First time using vcpkg here, which file did you change to get it working? I'm struggling to find the broken link in a file that I can change

**Comment by PrexCoder** [comment]
you have to check all links that contain repo.msys2 and update them with a valid repo, pay attention when replacing cause there are some different locations and it may fail, if you want I think I can provide you the files for it, just let me know 👍

**Comment by MagnusHodne** [comment]
If you could provide me with the files, that would be terrific. My problem is that I don't know what files to look at to find the links

**Comment by philimat** [comment]
While the server is down you can go to [](url)https://mirror.yandex.ru/mirrors/msys2/mingw/i686/ and manually download the failed files and put them into your vcpkg/downloads folder. I was able to install eigen3 this way by doing it for 3 missing files.

**Comment by MagnusHodne** [comment]
Fantastic! Worked like a charm. I'll keep that trick in mind if I ever encounter a package with servers that are down again. Thanks!
