### ISSUE TITLE
Eigen3 not found by CMake's "find_package"

### ISSUE THREAD

**Issue by LeonineKing1199** [Microsoft/vcpkg#1386]
I just downloaded Eigen3 and when I use:
```
find_package(Eigen3 REQUIRED)
```

I receive the following:
```
By not providing "FindEigen3.cmake" in CMAKE_MODULE_PATH this project has
asked CMake to find a package configuration file provided by "Eigen3", but
CMake did not find one.

Could not find a package configuration file provided by "Eigen3" with any
of the following names:

Eigen3Config.cmake
eigen3-config.cmake

Add the installation prefix of "Eigen3" to CMAKE_PREFIX_PATH or set
"Eigen3_DIR" to a directory containing one of the above files.  If "Eigen3"
provides a separate development package or SDK, be sure it has been
installed.
```

**Comment by traversaro** [comment]
Are you using the CMake vcpkg's toolchain as described in https://github.com/Microsoft/vcpkg/blob/master/docs/examples/using-sqlite.md#cmake or some other method to let CMake discover packages installed by vcpkg?

**Comment by LeonineKing1199** [comment]
Welp, turns out I'm a total noob XD

Omg, I feel so stupid now :P

I thought for some reason that changing the CMake project configs in VS 2017 was global so I didn't even check. I was also compiling in x86 mode when I had only downloaded x64 code.

Boy, is my face red. Thanks for the heads up!
