### ISSUE TITLE
vcpkg error while installing ffmpeg

### ISSUE THREAD

**Issue by nivedps** [microsoft/vcpkg#13869]
I got an error which says
-- Downloading https://repo.msys2.org/msys/x86_64/bash-4.4.023-2-x86_64.pkg.tar.xz... Failed. Status: 7;"**Couldn't connect to server**"
![Screenshot (2)](https://user-images.githubusercontent.com/60648993/95009648-49755800-0641-11eb-87da-9eae67df838e.png)

**Comment by nivedps** [comment]
@gnu-lorien , @alexkaratarakis

**Comment by traversaro** [comment]
A quick workaround is to download directly the file https://mirror.yandex.ru/mirrors/msys2/msys/x86_64/bash-4.4.023-2-x86_64.pkg.tar.xz in the downloads directory of vcpkg.

**Comment by traversaro** [comment]
> 
> 
> A quick workaround is to download directly the file https://mirror.yandex.ru/mirrors/msys2/msys/x86_64/bash-4.4.023-2-x86_64.pkg.tar.xz in the downloads directory of vcpkg.

Actually the file needs to be downloaded in the downloads directory, and its name needs to be changed to `msys-bash-4.4.023-2-x86_64.pkg.tar.xz` .

**Comment by traversaro** [comment]
> 
> 
> > A quick workaround is to download directly the file https://mirror.yandex.ru/mirrors/msys2/msys/x86_64/bash-4.4.023-2-x86_64.pkg.tar.xz in the downloads directory of vcpkg.
> 
> Actually the file needs to be downloaded in the downloads directory, and its name needs to be changed to `msys-bash-4.4.023-2-x86_64.pkg.tar.xz` .

Actually not even that works, as for some reason the hash of that file is different.

**Comment by nivedps** [comment]
I wonder why it shows unable to connect to server. Is their server down? 
Can we update the link to the one you have given above!!

**Comment by JackBoosY** [comment]
Duplicate to #13852.
