### ISSUE TITLE
 Error

### ISSUE THREAD

**Issue by chhdao** [microsoft/vcpkg#13866]
I pull a new library(https://github.com/microsoft/vcpkg/pull/13861).    
A checks were not successful from zlib. (https://dev.azure.com/vcpkg/public/_build/results?buildId=43601&view=logs&j=5dffab7c-3299-5a76-7b02-e037cd868fad&t=70564965-7ae4-5af3-8764-a93ab8ddf245&l=71)   
I never change it.And I did not see error from my library.

**Comment by sfhacker** [comment]
The title of this issue plus its description are awesome!
I'd love to assist you but no idea how. I have read some posts about MSYS2 servers being down but ...

**Comment by JackBoosY** [comment]
Duplicate to #13852.
