### ISSUE TITLE
downloading problem: mingw-w64-i686-pkg-config

### ISSUE THREAD

**Issue by decryp2kanon** [microsoft/vcpkg#13871]
https://github.com/microsoft/vcpkg/blob/802c9c6aec1f6189e99b1fc8217977bc2995156a/scripts/cmake/vcpkg_find_acquire_program.cmake#L439-L441

https://github.com/bitcoin/bitcoin/issues/20066

workaround is using mirror. but really annoying...
```
in my case replace with this mirror

not working:
https://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz

replace:
https://mirror.yandex.ru/mirrors/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz
```

**Comment by traversaro** [comment]
A quick workaround is to download the files: 
* https://mirror.yandex.ru/mirrors/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz
* https://mirror.yandex.ru/mirrors/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst

In the downloads subdirectory of the main vcpkg directory.

**Comment by JackBoosY** [comment]
Duplicate to #13852.
