### ISSUE TITLE
[ensmallen] VCPKG Version Out of Date

### ISSUE THREAD

**Issue by Blakjak88** [microsoft/vcpkg#13879]
Library name:   ensmallen

New version number:    2.14.2

Other information that may be useful (release notes, etc...)

**Comment by JonLiu1993** [comment]
Hi @Blakjak88 ,The latest version of  ensmallen is 2.14.2, So it's your need?

**Comment by Blakjak88** [comment]
Hi, yes. The current version has missing features.

**Comment by JonLiu1993** [comment]
@Blakjak88 ,Thansk for posting this issue.
I have submitted pr to upgrade ensmallen to the latest version 2.17.0. When pr is merged, you can update vcpkg to test.
