### ISSUE TITLE
Cmake Error when deploy darknet on windows

### ISSUE THREAD

**Issue by s-kim333** [microsoft/vcpkg#13874]
I have problem when trying to configure darknet on windows 
I tried to configure it with vcpkg, it gives me error and the I tried it with cmake as well it also gives me error 

the error message I have is 
CMake Error at C:/Program Files/CMake/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find PThreads_windows (missing: PThreads_windows_LIBRARY
  PThreads_windows_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindPThreads_windows.cmake:39 (find_package_handle_standard_args)
  C:/Users/gim10/Desktop/vcpkg-master/scripts/buildsystems/vcpkg.cmake:496 (_find_package)
  CMakeLists.txt:103 (find_package)

then I checked the error log, it says:

Determining if the include file pthread.h exists failed with the following output:
Change Dir: C:/Users/gim10/Desktop/darknet-master/build/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/Bin/MSBuild.exe cmTC_04a92.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:m && .NET Framework용 Microsoft (R) Build Engine 버전 16.7.0+b89cb5fde

Copyright (C) Microsoft Corporation. All rights reserved.

  Microsoft (R) C/C++ 최적화 컴파일러 버전 19.27.29112(x64)

  CheckIncludeFile.c

  Copyright (c) Microsoft Corporation. All rights reserved.

  cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_04a92.dir\Debug\\" /Fd"cmTC_04a92.dir\Debug\vc142.pdb" /Gd /TC /errorReport:queue "C:\Users\gim10\Desktop\darknet-master\build\CMakeFiles\CMakeTmp\CheckIncludeFile.c"

C:\Users\gim10\Desktop\darknet-master\build\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'pthread.h': No such file or directory [C:\Users\gim10\Desktop\darknet-master\build\CMakeFiles\CMakeTmp\cmTC_04a92.vcxproj]

What do I need to do to fix this error?

**Comment by PhoebeHui** [comment]
@s-kim333, could you double confirm if pthreads installed? I can't repro this issue, pthreads is already added as a dependency to darknet.

Starting package 3/3: darknet:x64-windows
Building package darknet[core]:x64-windows...
-- Downloading https://github.com/AlexeyAB/darknet/archive/ecad770071eb776208a46977347e6d2410d4f50e.tar.gz...
-- Extracting source F:/vcpkg/src/downloads/AlexeyAB-darknet-ecad770071eb776208a46977347e6d2410d4f50e.tar.gz
-- Applying patch 0001-rename-_castu32_f32-to-gemm_castu32_f32.patch
-- Using source at F:/vcpkg/src/buildtrees/darknet/src/2410d4f50e-654ef90b3b.clean
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: F:/vcpkg/src/packages/darknet_x64-windows/share/darknet/copyright
-- Performing post-build validation
-- Performing post-build validation done
Installing package darknet[core]:x64-windows...
Installing package darknet[core]:x64-windows... done
Elapsed time for package darknet:x64-windows: 1.687 min

Total elapsed time: 3.152 min

The package darknet:x64-windows provides CMake targets:

    find_package(Darknet CONFIG REQUIRED)
    target_link_libraries(main PRIVATE Darknet::dark)

**Comment by PhoebeHui** [comment]
@s-kim333, does this still be a problem for you?

**Comment by PhoebeHui** [comment]
@s-kim333, please reopen this issue if it still be a problem for you.
