### ISSUE TITLE
[mlpack] update to <3.4.1>

### ISSUE THREAD

**Issue by Blakjak88** [microsoft/vcpkg#13877]
Library name:  MLPACK

New version number:   3.4.1

Other information that may be useful (release notes, etc...)

**Comment by JonLiu1993** [comment]
Duplicate to #13536

**Comment by PhoebeHui** [comment]
Mlpack has been updated to 3.4.1, please get latest source and try again, related to PR https://github.com/microsoft/vcpkg/pull/14122.
