### ISSUE TITLE
[brotli:x64-windows] build failure

### ISSUE THREAD

**Issue by xanather** [microsoft/vcpkg#13870]
**Host Environment**
- OS: Windows 10

**To Reproduce**
`./vcpkg install brotli:x64-windows`

**Failure logs** 
Starting package 2/10: brotli:x64-windows
Building package brotli[core]:x64-windows...
Could not locate cached archive: C:\Users\xanat\AppData\Local\vcpkg\archives\89\89f414094791e65fb63908591ef874a1c748df17.zip
-- Using cached C:/Users/xanat/Documents/Files/Projects/viron/third-party/vcpkg/downloads/google-brotli-e61745a6b7add50d380cfd7d3883dd6c62fc2c71.tar.gz
-- Cleaning sources at C:/Users/xanat/Documents/Files/Projects/viron/third-party/vcpkg/buildtrees/brotli/src/6c62fc2c71-a8c4ea9278.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/xanat/Documents/Files/Projects/viron/third-party/vcpkg/downloads/google-brotli-e61745a6b7add50d380cfd7d3883dd6c62fc2c71.tar.gz
-- Applying patch install.patch
-- Applying patch fix-arm-uwp.patch
-- Applying patch pkgconfig.patch
-- Using source at C:/Users/xanat/Documents/Files/Projects/viron/third-party/vcpkg/buildtrees/brotli/src/6c62fc2c71-a8c4ea9278.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz...
-- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz... Failed. Status: 7;"Couldn't connect to server"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:181 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_find_acquire_program.cmake:438 (vcpkg_download_distfile)
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:270 (vcpkg_find_acquire_program)
  ports/brotli/portfile.cmake:25 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:79 (include)

Error: Building package brotli:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: brotli:x64-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.

**Additional context**
Looks like repo.msys2.org is not a valid domain anymore?

**Comment by xanather** [comment]
Actually, it looks like repo.msys2.org is used by alot of portfiles. Whoever I think the site it just down. I will try again tomorrow and close this issue if thats the case.

**Comment by xanather** [comment]
I should've checked the issue list before posting. The last 4 issues are about the same thing. Closing.

**Comment by gqinghua** [comment]
遇到这种问题，需要通过日志查看具体出错原因，寻找Failed或Error关键字。

例如：Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.72.0/boostcpp.jam… Failed.
在vcpkg\downloads\temp文件里有一个大小为0的boost-1.72.0-boostcpp.jam文件。注意文件名不完全相同，说明它需要下载后重命名。
下载时出错，重试多次都不行，网络也没问题。那就复制地址，用浏览器下载这个文件，然后保存在vcpkg\downloads文件夹里并重命名为boost-1.72.0-boostcpp.jam就行了。
