### ISSUE TITLE
[New Port Request] fmtlib

### ISSUE THREAD

**Issue by cjwijtmans** [microsoft/vcpkg#13887]
**Library description:**
https://github.com/fmtlib/fmt/blob/master/README.rst

**Source repository URL:**
https://github.com/fmtlib/fmt

**Anything else that is useful to know when adding (such as optional features the library may have that should be included):**
msvc still doesnt support formatting from C++20

**Comment by Hoikas** [comment]
This port already exists: https://github.com/microsoft/vcpkg/blob/master/ports/fmt/CONTROL

**Comment by cjwijtmans** [comment]
well i apologise, i could not find it in my search function.
