### ISSUE TITLE
Error: Building package zlib:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by mybofy** [microsoft/vcpkg#13882]
**Host Environment**
- OS: [e.g. Windows/Linux etc...]
- Compiler: revision
Windows 10 famille  - 2004 - 19041.508

**To Reproduce**
`./vcpkg install xxxx`
.\vcpkg install libpqxx

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.
C:\Libraries\vcpkg>.\vcpkg install libpqxx
Computing installation plan...
warning: vcpkg appears to be in a Visual Studio prompt targeting x86 but is installing packages for x64-windows. Consider using --triplet x86-windows or --triplet x86-uwp.
The following packages will be built and installed:
  * libpq[core,openssl,zlib]:x64-windows
    libpqxx[core]:x64-windows
  * openssl[core]:x64-windows
  * openssl-windows[core]:x64-windows
  * zlib[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Starting package 1/5: openssl-windows:x64-windows
Building package openssl-windows[core]:x64-windows...
Could not locate cached archive: C:\Users\nuc\AppData\Local\vcpkg\archives\c1\c1180c893400f1ff0c4cb1056d034d3ba6de4a29.zip
-- Using cached C:/Libraries/vcpkg/downloads/openssl-1.1.1g.tar.gz
-- Cleaning sources at C:/Libraries/vcpkg/buildtrees/openssl-windows/src/openssl-1-bb2a9a5801.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Libraries/vcpkg/downloads/openssl-1.1.1g.tar.gz
-- Using source at C:/Libraries/vcpkg/buildtrees/openssl-windows/src/openssl-1-bb2a9a5801.clean
-- Copying openssl release source files...
-- Copying openssl release source files... done
-- Configure x64-windows-rel
-- Configure x64-windows-rel done
-- Build x64-windows-rel
-- Build x64-windows-rel done
-- Copying openssl debug source files...
-- Copying openssl debug source files... done
-- Configure x64-windows-dbg
-- Configure x64-windows-dbg done
-- Build x64-windows-dbg
-- Build x64-windows-dbg done
-- Installing: C:/Libraries/vcpkg/packages/openssl-windows_x64-windows/share/openssl-windows/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\nuc\AppData\Local\vcpkg\archives\c1\c1180c893400f1ff0c4cb1056d034d3ba6de4a29.zip
Building package openssl-windows[core]:x64-windows... done
Installing package openssl-windows[core]:x64-windows...
Installing package openssl-windows[core]:x64-windows... done
Elapsed time for package openssl-windows:x64-windows: 5.173 min
Starting package 2/5: openssl:x64-windows
Building package openssl[core]:x64-windows...
Could not locate cached archive: C:\Users\nuc\AppData\Local\vcpkg\archives\4a\4ab993bba468bc591b9f7e42ce0871edc9702e5b.zip
-- Installing: C:/Libraries/vcpkg/packages/openssl_x64-windows/share/openssl//usage
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\nuc\AppData\Local\vcpkg\archives\4a\4ab993bba468bc591b9f7e42ce0871edc9702e5b.zip
Building package openssl[core]:x64-windows... done
Installing package openssl[core]:x64-windows...
Installing package openssl[core]:x64-windows... done
Elapsed time for package openssl:x64-windows: 143.7 ms
Starting package 3/5: zlib:x64-windows
Building package zlib[core]:x64-windows...
Could not locate cached archive: C:\Users\nuc\AppData\Local\vcpkg\archives\b9\b9aff7ee65312c0d29ec2a264cca8c3988d5d73d.zip
-- Using cached C:/Libraries/vcpkg/downloads/zlib1211.tar.gz
-- Cleaning sources at C:/Libraries/vcpkg/buildtrees/zlib/src/1.2.11-63309e48e5.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Libraries/vcpkg/downloads/zlib1211.tar.gz
-- Applying patch cmake_dont_build_more_than_needed.patch
-- Applying patch 0001-Prevent-invalid-inclusions-when-HAVE_-is-set-to-0.patch
-- Applying patch add_debug_postfix_on_mingw.patch
-- Using source at C:/Libraries/vcpkg/buildtrees/zlib/src/1.2.11-63309e48e5.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz...
-- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz... Failed. Status: 7;"Couldn't connect to server"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:181 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_find_acquire_program.cmake:438 (vcpkg_download_distfile)
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:270 (vcpkg_find_acquire_program)
  ports/zlib/portfile.cmake:48 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:79 (include)

Error: Building package zlib:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zlib:x64-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by aspioupiou** [comment]
@mybofy 

I already met this issue in the past. Seems vcpkg doesn't manage to reach ` https://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz`
In my case, I had a valid network connection and the file did exist (try to download it manually). 
The temporary workaround is to either download it manually, paste it the the `download` section and retry to install zlib Or switching to another network (I used myself my Iphone hotspot and It worked perfectly)

Hope it helps

cheers

**Comment by Kolt912** [comment]
> @mybofy
> 
> I already met this issue in the past. Seems vcpkg doesn't manage to reach ` https://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz`
> In my case, I had a valid network connection and the file did exist (try to download it manually).
> The temporary workaround is to either download it manually, paste it the the `download` section and retry to install zlib Or switching to another network (I used myself my Iphone hotspot and It worked perfectly)
> 
> Hope it helps
> 
> cheers

File is not available to manually download :( But I have a mirror.

> The temporary workaround is to either download it manually, paste it the the `download` section
Can you explain me this point?

**Comment by aspioupiou** [comment]
IIRC, download the file and unzip in : 
`vcpkg\packages\zlib_x64-windows-md`
Then, again IIRC, vcpkg should build the package should using the already downloaded files. 

If the link does not exist, it might be an issue with your VCPKG version. Try updating it maybe?

**Comment by SebastienEGNER** [comment]
I have this issue aswell.

**Comment by SebastienEGNER** [comment]
This issue has been fixed by #13889.

**Comment by JackBoosY** [comment]
Fixed.
