### ISSUE TITLE
[ZLib] build failure

### ISSUE THREAD

**Issue by SergioMasson** [microsoft/vcpkg#13888]
**Host Environment**
- OS: Windows
- Compiler: revision

**To Reproduce**
`./vcpkg install zlib`

**Failure logs** 
-- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz... Failed. Status: 28;"Timeout was reached"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:181 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_find_acquire_program.cmake:438 (vcpkg_download_distfile)
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:270 (vcpkg_find_acquire_program)
  ports/zlib/portfile.cmake:48 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:79 (include)

Error: Building package zlib:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zlib:x86-windows
  Vcpkg version: 2020.06.15-nohash

**Additional context**
- Unable to build openCV due to this issue with ZLib

**Comment by daniel-piro** [comment]
I see the same issue

**Comment by zacharyneveu** [comment]
Also having this when building `curl:x64-windows`, looks like `repo.msys2.org` is down from the errors I'm getting?

**Comment by fabiencastan** [comment]
Yes, same for many packages:
```
-- Downloading https://repo.msys2.org/msys/x86_64/bash-4.4.023-2-x86_64.pkg.tar.xz... Failed. Status: 7;"Couldn't connect to server"
```

**Comment by fabiencastan** [comment]
There is a notification about troubles on https://www.msys2.org
"The primary download server is currently (since Oct 2nd) down."

**Comment by fabiencastan** [comment]
It is now fixed by https://github.com/microsoft/vcpkg/pull/13889.

**Comment by JackBoosY** [comment]
Fixed.
