### ISSUE TITLE
Can not install Superlu

### ISSUE THREAD

**Issue by ChrisNabold** [microsoft/vcpkg#13898]
I use Win10 64bit version, used the latest git download for vcpkg. . I recieve the following error
[C:\vcpkg].\vcpkg install superlu
Computing installation plan...
The following packages will be built and installed:
    superlu[core]:x64-windows
Detecting compiler hash for triplet x64-windows...
Starting package 1/1: superlu:x64-windows
Building package superlu[core]:x64-windows...
Could not locate cached archive: C:\Users\Chris\AppData\Local\vcpkg\archives\de\de3a12521e4732706e02376f740da09deda2a695.zip
-- Using cached C:/vcpkg/downloads/xiaoyeli-superlu-a3d5233770f0caad4bc4578b46d3b26af99e9c19.tar.gz
-- Cleaning sources at C:/vcpkg/buildtrees/superlu/src/6af99e9c19-18e507a628.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg/downloads/xiaoyeli-superlu-a3d5233770f0caad4bc4578b46d3b26af99e9c19.tar.gz
-- Applying patch fix-libm.patch
-- Applying patch remove-make.inc.patch
-- Using source at C:/vcpkg/buildtrees/superlu/src/6af99e9c19-18e507a628.clean
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:85 (message):
    Command failed: ninja -v
    Working Directory: C:/vcpkg/buildtrees/superlu/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\vcpkg\buildtrees\superlu\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:305 (vcpkg_execute_required_process)
  ports/superlu/portfile.cmake:14 (vcpkg_configure_cmake)
  scripts/ports.cmake:79 (include)

Error: Building package superlu:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: superlu:x64-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, att
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/5332579/config-x64-windows-out.log)
ach any relevant sections from the log files above.

**Comment by NancyLi1013** [comment]
Hi @ChrisNabold 
Thanks for posting this issue.

```
USE_XSDK_DEFAULTS = 'FALSE'
-- SuperLU will be built as a shared library.
-- The C compiler identification is unknown
-- Check for working C compiler: C:/msys64/mingw64/bin/cc.exe
-- Check for working C compiler: C:/msys64/mingw64/bin/cc.exe - broken
CMake Error at C:/msys64/mingw64/share/cmake-3.17/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "C:/msys64/mingw64/bin/cc.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/vcpkg/buildtrees/superlu/x64-windows-dbg/CMakeFiles/CMakeTmp
    
    Run Build Command(s):C:/vcpkg/downloads/tools/ninja/1.10.1-windows/ninja.exe cmTC_90162 && 
```
It seems that there is something wrong with your compiler.

Have you installed Visual Studio on your local machine?

**Comment by sfhacker** [comment]
@ChrisNabold How familiar are you with building projects from source on Windows?
I just downloaded Superlu master branch and built it on Windows 10 x64 with no issues at all!

![image](https://user-images.githubusercontent.com/25817529/95586091-e72ab600-0a8b-11eb-8189-097d10500c6b.png)

Have you contacted us before about you being unable to build several ports on Windows?

**Comment by ChrisNabold** [comment]
Dear John,

 

Thank you for your Email. As Vcpkg is available I tried to install programs like Sundials, Lapack, Armadillo etc from vcpkg. There are alternatives like Msys downloads which normally work fine using the compilers like Mingw-64. Some of the libraries are difficult to install like GSL on Visual Studio 2019, so I am glad to be able to download it via vcpkg. If you don’t want me to take the efforts of documenting the various vcpkg installation errors please let me know.

 

With regard to superlu I managed to install it using the mingw compiler suite, 

 

Best regards and have a nice weekend

 

Chris Nabold

**Comment by NancyLi1013** [comment]
Hi @ChrisNabold 

Does this issue still exist on your machine?

**Comment by NancyLi1013** [comment]
Closing this issue for no response. Please feel free to reopen this if it is still a problem for you.
