### ISSUE TITLE
Error: Building package openblas:x64-windows failed with: BUILD_FAILEDailure

### ISSUE THREAD

**Issue by seekriver** [microsoft/vcpkg#13896]
**Host Environment**
- OS: [Windows]
- Compiler: VS2019

**To Reproduce**
`./vcpkg install  openblas

**Failure logs** 
Computing installation plan...
The following packages will be built and installed:
    openblas[core]:x64-windows
Detecting compiler hash for triplet x64-windows...
Starting package 1/1: openblas:x64-windows
Building package openblas[core]:x64-windows...
Could not locate cached archive: C:\Users\locate\AppData\Local\vcpkg\archives\c0\c0155ee6a327fdc88bc02c64f6302b1ac9e7b426.zip
-- Using cached D:/Program Files/vcpkg/downloads/xianyi-OpenBLAS-v0.3.9.tar.gz
-- Cleaning sources at D:/Program Files/vcpkg/buildtrees/openblas/src/v0.3.9-34bf3bd20e.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/Program Files/vcpkg/downloads/xianyi-OpenBLAS-v0.3.9.tar.gz
-- Applying patch uwp.patch
-- Applying patch fix-space-path.patch
-- Applying patch fix-redefinition-function.patch
-- Applying patch github_2481.patch
-- Applying patch fix-pkg-config.patch
-- Using source at D:/Program Files/vcpkg/buildtrees/openblas/src/v0.3.9-34bf3bd20e.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Using msys root at D:/Program Files/vcpkg/downloads/tools/msys2/c809757c94447846
-- Fixing pkgconfig file: D:/Program Files/vcpkg/packages/openblas_x64-windows/lib/pkgconfig/openblas.pc
-- CHECK_LIB_openblas_RELEASE:CHECK_LIB_openblas_RELEASE-NOTFOUND
CMake Error at scripts/cmake/vcpkg_fixup_pkgconfig.cmake:232 (message):
  Library "openblas" was not found! If it is a system library use the
  SYSTEM_LIBRARIES parameter for the vcpkg_fixup_pkgconfig call! Otherwise,
  correct the *.pc file
Call Stack (most recent call first):
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:297 (vcpkg_fixup_pkgconfig_check_files)
  ports/openblas/portfile.cmake:105 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:79 (include)

Error: Building package openblas:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openblas:x64-windows
  Vcpkg version: 2020.06.15-nohash

how to fix it?

**Comment by JackBoosY** [comment]
Please clone vcpkg on a non-space path and try again. 
Thanks.

**Comment by seekriver** [comment]
Problem solved ! thank you !

**Comment by SUQIGUANG** [comment]
> Please clone vcpkg in a non-space path and try again. Thanks.

thanks , it works
