### ISSUE TITLE
[brotli:x64-windows] download failure

### ISSUE THREAD

**Issue by tigranmt** [microsoft/vcpkg#13902]
**Host Environment**
- OS: Windows
- Compiler: revision

**To Reproduce**
`./vcpkg install parquet:x64-windows`

**Failure logs** 
-- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz... Failed. Status: 7;"Couldn't connect to server"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:181 (message):

      -->Failed to download file. <--
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_find_acquire_program.cmake:438 (vcpkg_download_distfile)
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:270 (vcpkg_find_acquire_program)
  ports/brotli/portfile.cmake:25 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:79 (include)

Error: Building package brotli:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: brotli:x64-windows
  Vcpkg version: 2020.06.15-nohash

**Additional context**
Don't have any issue with any other package , meaning downloading compiling and using it. 
Didn't have any issues with the Linux version as well. 
`./vcpkg install parquet:x64-linux` - works.

**Comment by Zombieanfuehrer** [comment]
#13901 same issue

**Comment by faska** [comment]
repo.msys2.org is down for the 2nd week already

**Comment by Hoikas** [comment]
This issue should have been fixed in #13889. Try updating to the latest revision of vcpkg: `git pull && ./bootstrap-vcpkg.bat`

**Comment by tigranmt** [comment]
Indeed, after `git pull` it seems working properly. 
Thank you.

**Comment by JackBoosY** [comment]
Fixed.
