### ISSUE TITLE
[brotli:x64] build failure

### ISSUE THREAD

**Issue by Zombieanfuehrer** [microsoft/vcpkg#13901]
**Host Environment**
- OS: [x64-windows 10]
cmake 

**To Reproduce**
`./vcpkg install cpprestsdk:-x64windows

**Failure logs** 
cleaning for the packages you specify.
-- Extracting source C:/Projekte/SDKs/cpprestsdk-master/vcpkg/vcpkg-master/downloads/google-brotli-e61745a6b7add50d380cfd7d3883dd6c62fc2c71.tar.gz
-- Applying patch install.patch
-- Applying patch fix-arm-uwp.patch
-- Applying patch pkgconfig.patch
-- Using source at C:/Projekte/SDKs/cpprestsdk-master/vcpkg/vcpkg-master/buildtrees/brotli/src/6c62fc2c71-a8c4ea9278.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz...
-- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz... Failed. Status: 28;"Timeout was reached"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:181 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_find_acquire_program.cmake:438 (vcpkg_download_distfile)
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:270 (vcpkg_find_acquire_program)
  ports/brotli/portfile.cmake:25 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:79 (include)

Error: Building package brotli:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: brotli:x64-windows
  Vcpkg version: 2020.06.15-nohash

**Additional context**
https://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz... Failed. Status: 28;"Timeout was reached"

is it possible to manually specify older versions or alternative server paths? I am an absolute beginner with vcpkg 

Thanks!!

**Comment by Hoikas** [comment]
This issue should have been fixed in #13889. Try updating to the latest revision of vcpkg: `git pull && ./bootstrap-vcpkg.bat`
