### ISSUE TITLE
Can not install lapack-reference

### ISSUE THREAD

**Issue by ChrisNabold** [microsoft/vcpkg#13915]
[C:\vcpkg].\vcpkg install armadillo
Computing installation plan...
The following packages will be built and installed:
    armadillo[core]:x64-windows
  * lapack[core]:x64-windows
  * lapack-reference[blas-select,core,noblas]:x64-windows
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Starting package 1/3: lapack-reference:x64-windows
Building package lapack-reference[blas-select,core,noblas]:x64-windows...
Could not locate cached archive: C:\Users\Chris\AppData\Local\vcpkg\archives\88\88d20df4d891b8e5a9866b36a759dc7555ab4677.zip
-- Using cached C:/vcpkg/downloads/Reference-LAPACK-lapack-v3.8.0.tar.gz
-- Cleaning sources at C:/vcpkg/buildtrees/lapack-reference/src/v3.8.0-954f10683f.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg/downloads/Reference-LAPACK-lapack-v3.8.0.tar.gz
-- Using source at C:/vcpkg/buildtrees/lapack-reference/src/v3.8.0-954f10683f.clean
-- The Fortran compiler identification is unknown
-- No Fortran compiler found on the PATH. Using MinGW gfortran!
-- Using msys root at C:/vcpkg/downloads/tools/msys2/2d316d3dcc37bb3f
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:141 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j9
    Working Directory: C:/vcpkg/buildtrees/lapack-reference/x64-windows-dbg
    See logs for more information:
      C:\vcpkg\buildtrees\lapack-reference\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:92 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/lapack-reference/portfile.cmake:72 (vcpkg_install_cmake)
  scripts/ports.cmake:79 (include)

Error: Building package lapack-reference:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: lapack-reference:x64-windows
  Vcpkg version: 2020.06.15-nohash
CONTROL 6776f5cd4f08e0badc0d7a8810421d7f10c34311
add-disable-find-package.patch 0f47d21e1f4959b23fcfaa82c4a2e57c692da88a
cmake 3.18.4
features core
fix-CMakePath.patch 129f7ce287a5fdb12f2b9ce6601769518c45eb73
lapack db49d3129d18f1de7002881b9b457e2e2deda086
openblas 9ae02076add64fb3beaa40faa8b015991dbbb83e
portfile.cmake 3fd3a13d5fc62ab09c022efb2889d21b3e66c68c
post_build_checks 2
powershell 2e410fc5e429fc6ad478976eff3efcffe9d53a0620c7c31c2b8bfe1f0976cade74632fc202bf58959cec111f03b824ba42ad4d74c8a66d67ec21bbfe9b9c626d
remove_custom_modules.patch 68f37d268c416b4e56f31614298b00694682c3ac
triplet 3eab5c64d9cf628fc0aec277fde66dbdc69b8516-a1c0eabb0c5177b6a8fb97a58ae398880c47b352-a5a52d3ca7ad38a4f7b764d75df11399cb9f06b3
usage 814ec02f0cd86fe0ee7daac6a24c366d371ea481
vcpkg_check_linkage dc5fd80fa0a6f18c7eabee6f4da803b5abdeebcb
vcpkg_configure_cmake d9e525769b8519c26e4c0446242434961527d33b
vcpkg_copy_pdbs 4bbc15802daf8f9f8a92794c10b0a89cfca1e742
vcpkg_fixup_cmake_targets ef088786b9a6815971b8b6bd3a511183e77a8b93
vcpkg_from_git 4834edbcec7eed8d12c6b1ad3c25af63d5fa6586
vcpkg_from_gitlab 8cd52a8f5211e1320ca2ecfa97fb811836a4c253
vcpkg_install_cmake 75d1079d6f563d87d08c8c5f63b359377aa19a6e

Additionally, attach any relevant sections from the log files above.

**Comment by PhoebeHui** [comment]
Duplicated of https://github.com/microsoft/vcpkg/issues/13914
