### ISSUE TITLE
[New Port Request] Lis 2.0.23<library name here>

### ISSUE THREAD

**Issue by ChrisNabold** [microsoft/vcpkg#13917]
Library name:Lis 2.0.23

Library description: Lis: Library of Iterative Solvers for Linear Systems

Source repository URL: https://www.ssisc.org/lis/index.en.html

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
