### ISSUE TITLE
How do I run the vcpkg bootstrapper ,In the vcpkg root directory(is it input in mingw or in visual code terminal ) and do i need bootstrap extension for this

### ISSUE THREAD

**Issue by nandinikaushal35** [microsoft/vcpkg#13921]
When asking a question please also include where you looked for an answer (so we can update the documentation if needed).

**Comment by nandinikaushal35** [comment]
![image](https://user-images.githubusercontent.com/72455653/95375750-b0bf3080-08fd-11eb-8cf1-4e107a8b555c.png)

**Comment by JackBoosY** [comment]
Please see readme.

**Comment by JackBoosY** [comment]
`./bootstrap-vcpkg.sh`
