### ISSUE TITLE
Unable to link to lib zip

### ISSUE THREAD

**Issue by crjc** [microsoft/vcpkg#13925]
**Describe the bug**
Installed libzippp and its dependencies (including libzip). Build was successful. 
Attempting to link to libzippp/libzip fails.

```
CMake Error at E:/tevX/engine-v2/vcpkg/scripts/buildsystems/vcpkg.cmake:343 (_add_executable):
  Target "Test" links to target "libzip::libzip" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:7 (add_executable)
```

**Environment**
- OS: MacOS and Windows

**To Reproduce**
1. ./vcpkg install libzippp
2. attempt to link libzippp like so:
```
find_package(libzippp CONFIG REQUIRED)
target_link_libraries(${PROJECT_NAME} libzip::libzip libzippp::libzippp)
```

**Expected behavior**
No error expected. Other libraries built using Vcpkg work fine!

**Comment by carr-7** [comment]
Reverting the portfile.cmake to this https://github.com/microsoft/vcpkg/commit/4e2f4d3b03bdf5244691e549f726be5581a83fd8 commit seems to fix the issue

**Comment by NancyLi1013** [comment]
Hi @crjc 
Thanks for posting this issue.

It seems that the usage that you provided above is not right.

It should be like this:

```
find_package(libzippp CONFIG REQUIRED)
target_link_libraries(${PROJECT_NAME} PRIVATE libzip::zip libzippp::libzippp)
```

So could you please try to rebuild this?

**Comment by NancyLi1013** [comment]
Hi @crjc 

Please let me know if this is still a problem for you.

Thanks.

**Comment by NancyLi1013** [comment]
I'm closing this issue for now since no response here.

Please feel free to reopen this issue if you still  have questions.
