### ISSUE TITLE
[New Port Request] winflexbison

### ISSUE THREAD

**Issue by davidhunter22** [microsoft/vcpkg#13920]
Library name: winflexbison

Library description: Contains the flex/bison tools which are equivalents to lex/yacc

Source repository URL: https://github.com/lexxmark/winflexbison

I think this is already used internally in vcpkg as flex and bison are already listed in vcpkg_find_acquire_program but I believe this doesn't mean I can stick them in a manifest and use them in my project

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
