### ISSUE TITLE
[libmesh:x64-windows-static] build failure

### ISSUE THREAD

**Issue by rockydut** [microsoft/vcpkg#13930]
When I install the libmesh, it shows the following errors.

-- Using cached F:/Packages/vcpkg/downloads/libMesh-libmesh-21f623c837b3865ed65ec9608b357bdb1935d428.tar.gz
-- Cleaning sources at F:/Packages/vcpkg/buildtrees/libmesh/src/db1935d428-7b6bc82081.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source F:/Packages/vcpkg/downloads/libMesh-libmesh-21f623c837b3865ed65ec9608b357bdb1935d428.tar.gz
-- Using source at F:/Packages/vcpkg/buildtrees/libmesh/src/db1935d428-7b6bc82081.clean
-- Using msys root at F:/Packages/vcpkg/downloads/tools/msys2/77f3fd5f29257d6b
-- Configuring x64-windows-static-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:85 (message):
    Command failed: F:/Packages/vcpkg/downloads/tools/msys2/77f3fd5f29257d6b/usr/bin/bash.exe --noprofile --norc --debug -c "V=1 CPP='cl.exe -nologo -E' CC='cl.exe -nologo' CXX='cl.exe -nologo' AR='lib.exe -verbose' LD='link.exe -verbose' RANLIB=':' CCAS=':' STRIP=':' NM='dumpbin.exe -symbols -headers' DLLTOOL='link.exe -verbose -dll' ./../src/db1935d428-7b6bc82081.clean/configure  --disable-qhull --disable-silent-rules --verbose --disable-shared --enable-static --prefix=/F/Packages/vcpkg/installed/x64-windows-static/debug --bindir='${prefix}'/../tools/libmesh/debug/bin --sbindir='${prefix}'/../tools/libmesh/debug/sbin --includedir='${prefix}'/../include --datarootdir='${prefix}'/share/libmesh"
    Working Directory: F:/Packages/vcpkg/buildtrees/libmesh/x64-windows-static-dbg
    Error code: 1
    See logs for more information:
      F:\Packages\vcpkg\buildtrees\libmesh\config-x64-windows-static-dbg-out.log
      F:\Packages\vcpkg\buildtrees\libmesh\config-x64-windows-static-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:543 (vcpkg_execute_required_process)
  ports/libmesh/portfile.cmake:18 (vcpkg_configure_make)
  scripts/ports.cmake:79 (include)

**Comment by LilyWangL** [comment]
The related issue: #11835

**Comment by NancyLi1013** [comment]
Currently, `libmesh ` doesn't support windows. Duplicated to #11835. Let's track this issue there.
