### ISSUE TITLE
How to develop Linux + Windows application with WSL2 using the same vcpkg dir?

### ISSUE THREAD

**Issue by guyflax1234** [microsoft/vcpkg#13948]
recently I started to use WSL & vcpkg, but it has some problems when mixing windows + linux development. It seems like that installing Linux packages or Windows packages with vcpkg, mutually damage the vcpkg configuration and then vcpkg roughly says: "the package you want to install not found". (I know for sure that it exist, because it works after deletion of vcpkg and trying again)
e.g. 
vcpkg install boost:x64-linux ----> sucesss
then when exit from WSL environment and open new windows powershell instance:
vcpkg install boost:x64-windows ----> failed: "the package you want to install not found"

If it matters, the project dir is located in the "windows domain" so the WSL directing to it with "/mnt/c/Users/workspace/proj"1 .
Does Anyone already encountered this problem?

Am I doing something wrong?

Is there a better way to develop a cross-platform project with vcpkg?
again, I want to have the same project directory and with the same vcpkg directory without corrupting the vcpkg when downloading to a certain platform.

* I'm not sure if the folder corruption was made by the installation of a package or by the vcpkg bootstrapping stage.
* I can check for more details if needed, tell me if it's really needed or you already aware of the problem... 
  - I can bring you the exact error message if you need
  - I can verify again what's causing the problem if it's not known to you

my Stackoverflow post
https://stackoverflow.com/questions/64270986/how-to-develop-linux-windows-application-with-wsl2-and-visual-studio-c-2019

update me...

Thanks

**Comment by Hoikas** [comment]
In my experience this is a bad idea, especially if you are trying to use vcpkg from the Windows filesystem. IO operations from WSL2 in Windows shares is incredibly slow compared to the Linux filesystem. You are looking at much slower builds. Best to make a fresh checkout of vcpkg in the Linux filesystem.

**Comment by guyflax1234** [comment]
Hi, 
thanks for your response.  just to make sure we are both on the same page:
you wrote: "Best to make a fresh checkout of vcpkg in the Linux filesystem"
It means to create two separate projects doesn't it? 
because if one vcpkg resides in the WSL filesystem e.g /users/guy/workspace/proj1 (NOT:  /mnt/c); and one resides in the windows domain e.g. c:\workspace\proj1  then I need two different projects, right?
Hope it's not a stupid question.

**Comment by Hoikas** [comment]
Correct. I run my Windows vcpkg in `D:\vcpkg` and WSL vcpkg in `~/vcpkg`.

> Hope it's not a stupid question.

Not at all!

**Comment by guyflax1234** [comment]
It was very helpful my friend. 
many thanks !!

**Comment by JackBoosY** [comment]
So, does this issue resolved?

**Comment by PhoebeHui** [comment]
@guyflax1234, it looks you're using same vcpkg instance for windows and Linux, I think you need distinguish them, clone vcpkg source for linux and another vcpkg source for windows.

**Comment by PhoebeHui** [comment]
Please reopen this issue if it still be a problem for you.

**Comment by lalishansh** [comment]
> Correct. I run my Windows vcpkg in `D:\vcpkg` and WSL vcpkg in `~/vcpkg`.

how can i do so in Visual Studio, CMake project
it automatically picks up my ENV:VCPKG_ROOT in my windows environment (which i use for determining toolchain file location)
