### ISSUE TITLE
Add vcpkg port maintainer support

### ISSUE THREAD

**Issue by jwillemsen** [microsoft/vcpkg#13947]
There are a lot of packages in vcpkg, where most control files are maintained by a few people. The amount of changes in vcpkg is huge so I can't want all changes to see if someone has an issue or pr for a specific packages I maintain. 
 
**Proposed solution**

Add a package maintainer to the packages control file which lists the github accounts of the vcpkg package maintainers. At the moment an issue/PR is created for a specific package control file the listed package maintainers can be added automatically as watchers of the specific issue/PR so that they can give feedback on the issue/PR.

**Comment by PhoebeHui** [comment]
@jwillemsen, thanks for your suggestion! I like the idea.

**Comment by jwillemsen** [comment]
Conda solves this with a repository for each package where the maintainers are added to a team. That would require more tooling in order to keep all in sync

**Comment by jwillemsen** [comment]
https://github.com/macports/macports-ports uses a combination of email and github account, a bot can easily mention the maintainers in a new comment

**Comment by NancyLi1013** [comment]
Hi @jwillemsen 

Currently, we have supported maintainers field in manifests, please see https://github.com/microsoft/vcpkg/blob/master/docs/specifications/manifests.md#specification. So I think this can be closed now.

**Comment by jwillemsen** [comment]
Thanks, at the moment I have some spare time I will check how to update the ACE packaging at vcpkg to use this
