### ISSUE TITLE
[libusb:x64-linux] build failure

### ISSUE THREAD

**Issue by nikolskydn** [microsoft/vcpkg#13951]
**Host Environment**
- OS: Debian GNU/Linux 9.13 (stretch) [https://gemmei.ftp.acc.umu.se/cdimage/archive/9.13.0/amd64/iso-cd/debian-9.13.0-amd64-netinst.iso]
- Compiler: gcc version 6.3.0

**To Reproduce**
`$ sudo apt-get install cmake g++ git curl unzip tar dh-autoreconf libudev-dev`
`$ git clone -b 2019.06 https://github.com/microsoft/vcpkg`
`$ ./vcpkg/bootstrap-vcpkg.sh`
`$ ./vcpkg/vcpkg update`
`$ ./vcpkg/vcpkg install libusb`

**Failure logs** 

```
$ ./vcpkg/vcpkg install libusb
The following packages will be built and installed:
    libusb[core]:x64-linux
Starting package 1/1: libusb:x64-linux
Building package libusb[core]:x64-linux...
CMake Error at ports/libusb/portfile.cmake:4 (message):
  Error: the port is unsupported on your platform.  Please open an issue on
  github.com/Microsoft/vcpkg to request a fix
Call Stack (most recent call first):
  scripts/ports.cmake:73 (include)


Error: Building package libusb:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libusb:x64-linux
  Vcpkg version: 2019.06.21-unknownhash
```

**Comment by NancyLi1013** [comment]
Hi @nikolskydn 
Thanks for posting this issue.
It seems that you didn't build the latest version.
Could you please try to use `git pull` to update vcpkg to the latest commit and then rebuild this port?

**Comment by nikolskydn** [comment]
> Hi @nikolskydn
> Could you please try to use `git pull` to update vcpkg to the latest commit and then rebuild this port?


unfortunately `git pull` doesn't help build:

```
$ git pull
remote: Enumerating objects: 98, done.
remote: Counting objects: 100% (98/98), done.
remote: Total 181 (delta 98), reused 98 (delta 98), pack-reused 83
Receiving objects: 100% (181/181), 64.82 KiB | 0 bytes/s, done.
Resolving deltas: 100% (98/98), completed with 76 local objects.
From https://github.com/microsoft/vcpkg
   70f192e07..27a2418e9  master     -> origin/master
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>
```

```
$ ./vcpkg install libusb
The following packages will be built and installed:
    libusb[core]:x64-linux
Starting package 1/1: libusb:x64-linux
Building package libusb[core]:x64-linux...
CMake Error at ports/libusb/portfile.cmake:4 (message):
  Error: the port is unsupported on your platform.  Please open an issue on
  github.com/Microsoft/vcpkg to request a fix
Call Stack (most recent call first):
  scripts/ports.cmake:73 (include)


Error: Building package libusb:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libusb:x64-linux
  Vcpkg version: 2019.06.21-unknownhash

Additionally, attach any relevant sections from the log files above.
```

P.S. I am using the branch (-b 2019.06) due to the fact that vcpkg is not building to Debian 9 and gcc 6.3 [issues-13937](https://github.com/microsoft/vcpkg/issues/13937)

**Comment by NancyLi1013** [comment]
In your case, I think it would be better to update `libusb` manually on your local.
If we merge master to your branch, you might run into the same issue as that posted in #13937.

So could you please update `libusb` according to this changes https://github.com/microsoft/vcpkg/tree/master/ports/libusb?

**Comment by NancyLi1013** [comment]
@nikolskydn 
Does this issue still exist on your machine now?

**Comment by sfhacker** [comment]
@nikolskydn Are we still having issues building libusb?

**Comment by nikolskydn** [comment]
Sorry, for delaying the answer.

Custom building  helped me.
