### ISSUE TITLE
Error: Building package boost-atomic:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by guillermoacdc** [microsoft/vcpkg#13954]
**Host Environment**
- OS: Windows
- Compiler: revision

**To Reproduce**
`.\vcpkg install pcl`

**Failure logs** 
Error: Building package boost-atomic:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-atomic:x86-windows
  Vcpkg version: 2020.06.15-nohash

Additional packages (*) will be modified to complete this operation.
Warning: The following VS instances are excluded because the English language pack is unavailable.
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
Please install the English language pack.

**Additional context**
The language message does not have sense, i have english language in visual studio 2019: International Settings
[log.txt](https://github.com/microsoft/vcpkg/files/5358066/log.txt)

**Comment by PhoebeHui** [comment]
@guillermoacdc, thanks for reporting this issue!

It failed to download source, as a workaround, similar issue with https://github.com/microsoft/vcpkg/issues/13348, 
as a workaround, you can try to download the attachments, unzip it to downloads folder, and rebuild the port.
[boostorg-atomic-boost-1.73.0.tar.zip](https://github.com/microsoft/vcpkg/files/5358358/boostorg-atomic-boost-1.73.0.tar.zip)

For the message, could you check where it installed?
see https://github.com/microsoft/vcpkg/blob/0bb8780a60e67320a966421e2923595fa57cbf22/toolsrc/src/vcpkg/visualstudio.cpp#L333

Failure:
```
Building package boost-atomic
[core]:x86-windows...
Could not locate cached archive: C:\Users\guill\AppData\Local\vcpkg\archives\5b\5b52d228e1cdb19f805886b855d91fc3f60dd31c.zip
-- Downloading https://github.com/boostorg/atomic/archive/boost-1.73.0.tar.gz...
-- Downloading https://github.com/boostorg/atomic/archive/boost-1.73.0.tar.gz... Failed. Status: 6;"Couldn't resolve host name"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:181 (message):
      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues
Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:132 (vcpkg_download_distfile)
  ports/boost-atomic/portfile.cmake:3 (vcpkg_from_github)
  scripts/ports.cmake:79 (include)
Error: Building package boost-atomic:x86-windows failed with: BUILD_FAILED
```

**Comment by PhoebeHui** [comment]
@guillermoacdc, does this issue persist?

**Comment by guillermoacdc** [comment]
Thanks @PhoebeHui, the error doesnt persist. I have tried a new installation with "vcpkg install pcl:x64-windows" and that resolved all the errors.
