### ISSUE TITLE
[libpng:x64-linux] build failure on Ubuntu 18.04

### ISSUE THREAD

**Issue by jamesjr-colongan** [microsoft/vcpkg#13957]
**Host Environment**
- OS: [Ubuntu 18.04]
- Compiler: gcc (Ubuntu 10.1.0-2ubuntu1~18.04) 10.1.0
**To Reproduce**
`./vcpkg install wxwidgets:x64-linux`

**Failure logs** 

`Error: Building package libpng:x64-linux failed with: BUILD_FAILED`
- Package: libpng:x64-linux
- Vcpkg version: 2020.06.15-unknownhash

**Log File Error Messages**
```
[25/32] /usr/bin/cc -DPNG_INTEL_SSE_OPT=1 -I/home/james/DevOps/vcpkg/installed/x64-linux/include -I. -I/home/james/DevOps/vcpkg/buildtrees/libpng/src/v1.6.37-10db9f58e4.clean -fPIC -O3 -DNDEBUG -MD -MT CMakeFiles/png_static.dir/pngrtran.c.o -MF CMakeFiles/png_static.dir/pngrtran.c.o.d -o CMakeFiles/png_static.dir/pngrtran.c.o   -c /home/james/DevOps/vcpkg/buildtrees/libpng/src/v1.6.37-10db9f58e4.clean/pngrtran.c
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:141 (message):
    Command failed: /home/james/DevOps/vcpkg/downloads/tools/cmake-3.17.2-linux/cmake-3.17.2-Linux-x86_64/bin/cmake --build . --config Release --target install -- -v -j3
    Working Directory: /home/james/DevOps/vcpkg/buildtrees/libpng/x64-linux-rel
    See logs for more information:
      /home/james/DevOps/vcpkg/buildtrees/libpng/install-x64-linux-rel-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:92 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/libpng/portfile.cmake:78 (vcpkg_install_cmake)
  scripts/ports.cmake:79 (include)
```

**Comment by JackBoosY** [comment]
@jamesjr-colongan Could you provide the full log?
Can't repro in ubuntu 16.04 LTS.

**Comment by jamesjr-colongan** [comment]
@JackBoosY , I executed same command above to trace where the log files should be found.
After doing so, I got new `Error: Building package wxwidgets:x64-linux failed with: BUILD_FAILED`.

The libpng:x64-linux errors has gone. I thought it was due to continuing updates happening.

**Here is the complete Error log files for new build failure** inside _config-x64-linux-dbg-err.log_.

CMake Error at /home/james/DevOps/vcpkg/downloads/tools/cmake-3.17.2-linux/cmake-3.17.2-Linux-x86_64/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find GTK3 (missing: GTK3_INCLUDE_DIRS GTK3_LIBRARIES)
Call Stack (most recent call first):
  /home/james/DevOps/vcpkg/downloads/tools/cmake-3.17.2-linux/cmake-3.17.2-Linux-x86_64/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:445 (_FPHSA_FAILURE_MESSAGE)
  build/cmake/modules/FindGTK3.cmake:46 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  /home/james/DevOps/vcpkg/scripts/buildsystems/vcpkg.cmake:496 (_find_package)
  build/cmake/toolkit.cmake:87 (find_package)
  build/cmake/main.cmake:14 (include)
  CMakeLists.txt:69 (include)

**Comment by JackBoosY** [comment]
@jamesjr-colongan So the build failure is gone and the usage issue happend?

**Comment by jamesjr-colongan** [comment]
@JackBoosY , it seems CMake `Could NOT find GTK3 (missing: GTK3_INCLUDE_DIRS GTK3_LIBRARIES)`.

**Comment by JackBoosY** [comment]
`libpng` doesn't depends on `gtk`, so I guess you should install gtk first.

**Comment by jamesjr-colongan** [comment]
@JackBoosY 
Hello there. I tried to install gtk and got some build errors, xutils-dev,  therefore I installed it.
`_sudo apt install xutils-dev -y_`

**Then after that I got new log errors:**
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
ATK_LIBRARY
    linked by target "gtk-3" in directory /home/james/DevOps/vcpkg/buildtrees/gtk/src/gtk+-3-b723a7b846.clean
    linked by target "gailutil-3" in directory /home/james/DevOps/vcpkg/buildtrees/gtk/src/gtk+-3-b723a7b846.clean
    linked by target "gdk-3" in directory /home/james/DevOps/vcpkg/buildtrees/gtk/src/gtk+-3-b723a7b846.clean
GDK_PIXBUF_LIBRARY
    linked by target "gtk-3" in directory /home/james/DevOps/vcpkg/buildtrees/gtk/src/gtk+-3-b723a7b846.clean
    linked by target "gailutil-3" in directory /home/james/DevOps/vcpkg/buildtrees/gtk/src/gtk+-3-b723a7b846.clean
    linked by target "gdk-3" in directory /home/james/DevOps/vcpkg/buildtrees/gtk/src/gtk+-3-b723a7b846.clean
LIBINTL_LIBRARY
    linked by target "gtk-3" in directory /home/james/DevOps/vcpkg/buildtrees/gtk/src/gtk+-3-b723a7b846.clean
    linked by target "gailutil-3" in directory /home/james/DevOps/vcpkg/buildtrees/gtk/src/gtk+-3-b723a7b846.clean
    linked by target "gdk-3" in directory /home/james/DevOps/vcpkg/buildtrees/gtk/src/gtk+-3-b723a7b846.clean
PANGO_WIN32_LIBRARY
    linked by target "gtk-3" in directory /home/james/DevOps/vcpkg/buildtrees/gtk/src/gtk+-3-b723a7b846.clean
    linked by target "gailutil-3" in directory /home/james/DevOps/vcpkg/buildtrees/gtk/src/gtk+-3-b723a7b846.clean
    linked by target "gdk-3" in directory /home/james/DevOps/vcpkg/buildtrees/gtk/src/gtk+-3-b723a7b846.clean

CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_INSTALL_BINDIR
    CMAKE_INSTALL_LIBDIR
    VCPKG_PLATFORM_TOOLSET
    VCPKG_SET_CHARSET_FLAG

CMake Generate step failed.  Build files cannot be regenerated correctly.


Thanks!

**Comment by JackBoosY** [comment]
Hi @jamesjr-colongan, sorry for late.
Does this issue still exist?

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
