### ISSUE TITLE
[mdnsresponder] Add debug info to static libraries

### ISSUE THREAD

**Issue by ZeroAbility** [microsoft/vcpkg#13955]
****

**Is your feature request related to a problem? Please describe.**
Static builds do not include the debug info (DebugInformationFormat set to `ProgramDatabase`) and can cause build errors for projects that require it.

**Proposed solution**
DebugInformationFormat should be set to `OldStyle` in the port file when `VCPKG_LIBRARY_LINKAGE` equals `static`.

**Describe alternatives you've considered**
An option in the CONTROL file is also a consideration.

**Additional context**
Our project, Mumble, has this issue pertaining to the setting mentioned using triplet `x64-windows-static-md` but it also occurs with the `static` triplets:
https://github.com/mumble-voip/mumble/issues/4525

**Comment by JackBoosY** [comment]
This will obviously increase the size of the library, which I think is not a good thing.

**Comment by ZeroAbility** [comment]
Building without the setting creates a 220KB lib. With the setting is about 271KB. I agree, it's not ideal, but I don't think it's significant. Perhaps an option in the CONTROL file might help mitigate that.

**Comment by davidebeatrici** [comment]
The problem is that the PDB file is not copied.

From https://github.com/microsoft/vcpkg/pull/13721#issuecomment-699499011:
> Note that we pass /Z7 by default, which results in the debugging information being embedded in the object files (thus inside the `.lib` for static libs). This information will be then embedded in the larger application's pdb at link time.

This is not the case for mDNSResponder, because its MSBuild project sets `DebugInformationFormat` to `ProgramDatabase`.

By replacing the value with `OldStyle` we effectively achieve the wanted behavior (`/Z7`).

**Comment by Krzmbrzl** [comment]
> This will obviously increase the size of the library, which I think is not a good thing.

As long as this is optional (e.g. switchable via a CLI param), I don' think this is a problem at all. In fact I consider not being able to include PDBs is worse than needing some extra disk space :thinking:
