### ISSUE TITLE
Folly Package Failure

### ISSUE THREAD

**Issue by Maktm** [Microsoft/vcpkg#1395]
I'm using Windows 7 Ultimate and have successfully installed vcpkg with no errors. I've also managed to install curl & folly-x64 successfully without any issues. But when attempting to install folly-x86 using either one of the following commands: `.\vcpkg install folly` `.\vcpkg install folly:x86-windows` I get the following error output:

        ..\vcpkg > .\vcpkg.exe install folly:x86-windows
        The following packages will be built and installed:
            folly:x86-windows
        Building package folly:x86-windows...
        -- CURRENT_INSTALLED_DIR=E:/Projects/vcpkg/installed/x86-windows
        -- DOWNLOADS=E:/Projects/vcpkg/downloads
        -- CURRENT_PACKAGES_DIR=E:/Projects/vcpkg/packages/folly_x86-windows
        -- CURRENT_BUILDTREES_DIR=E:/Projects/vcpkg/buildtrees/folly
        -- CURRENT_PORT_DIR=E:/Projects/vcpkg/ports/folly/.
        CMake Error at ports/folly/portfile.cmake:2 (message):
        Folly only supports the x64 architecture.
        Call Stack (most recent call first):
        scripts/ports.cmake:73 (include)

Is this because the folly library itself supports x86 only, or does vcpkg not have support for the x86 version of folly yet?

**Comment by atkawa7** [comment]
@Maktm Yes folly supports x64 only
see [https://github.com/facebook/folly/blob/master/CMakeLists.txt#L29](https://github.com/facebook/folly/blob/master/CMakeLists.txt#L29)
