### ISSUE TITLE
[ mongo-c-driver:x64-windows] build failure

### ISSUE THREAD

**Issue by aiyou4love** [microsoft/vcpkg#13965]
**Host Environment**
- OS: win10
- Compiler: revision

**To Reproduce**
vcpkg install mongo-c-driver:x64-windows

**Failure logs** 
`-- Using source at C:/setup/vcpkg/vcpkg/buildtrees/mongo-c-driver/src/97251b2b2d-64741a92bf.clean
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:85 (message):
    Command failed: ninja -v
    Working Directory: C:/setup/vcpkg/vcpkg/buildtrees/mongo-c-driver/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\setup\vcpkg\vcpkg\buildtrees\mongo-c-driver\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:305 (vcpkg_execute_required_process)
  ports/mongo-c-driver/portfile.cmake:35 (vcpkg_configure_cmake)
  scripts/ports.cmake:79 (include)

Error: Building package mongo-c-driver:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: mongo-c-driver:x64-windows
  Vcpkg version: 2020.06.15-nohash`

[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/5358758/config-x64-windows-out.log)

**Comment by LilyWangL** [comment]
Thanks for posting this issue. There are the following error in your log:
```
-- Searching for libbson CMake packages
-- Could NOT find bson-1.0 (missing: bson-1.0_DIR)
CMake Error at CMakeLists.txt:10 (_message):
  System libbson not found
Call Stack (most recent call first):
  CMakeLists.txt:160 (message) 
```
Could you check `libbson` is installed on your VCPKG?

**Comment by aiyou4love** [comment]
PS C:\Users\aiyou> vcpkg install libbson:x64-windows                                                                    Computing installation plan...
The following packages are already installed:
    libbson[core]:x64-windows
Package libbson:x64-windows is already installed

Total elapsed time: 423.1 us

PS C:\Users\aiyou> vcpkg install mongo-c-driver:x64-windows                                                             Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
Computing installation plan...
The following packages will be built and installed:
    mongo-c-driver[core]:x64-windows
Detecting compiler hash for triplet x64-windows...
Starting package 1/1: mongo-c-driver:x64-windows
Building package mongo-c-driver[core]:x64-windows...
Could not locate cached archive: C:\Users\aiyou\AppData\Local\vcpkg\archives\bf\bfe9cf78a2abc11cffae6e5b35d38a29ebfe7c74.zip
-- Using cached C:/setup/vcpkg/vcpkg/downloads/mongodb-mongo-c-driver-99d422877c5b5ea52006c13ee3b48297251b2b2d.tar.gz
-- Cleaning sources at C:/setup/vcpkg/vcpkg/buildtrees/mongo-c-driver/src/97251b2b2d-64741a92bf.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/setup/vcpkg/vcpkg/downloads/mongodb-mongo-c-driver-99d422877c5b5ea52006c13ee3b48297251b2b2d.tar.gz
-- Applying patch fix-dependency-libbson.patch
-- Applying patch disable-static-when-dynamic-build.patch
-- Applying patch fix-arm-build.patch
-- Using source at C:/setup/vcpkg/vcpkg/buildtrees/mongo-c-driver/src/97251b2b2d-64741a92bf.clean
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:85 (message):
    Command failed: ninja -v
    Working Directory: C:/setup/vcpkg/vcpkg/buildtrees/mongo-c-driver/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\setup\vcpkg\vcpkg\buildtrees\mongo-c-driver\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:305 (vcpkg_execute_required_process)
  ports/mongo-c-driver/portfile.cmake:35 (vcpkg_configure_cmake)
  scripts/ports.cmake:79 (include)


Error: Building package mongo-c-driver:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: mongo-c-driver:x64-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.


> Thanks for posting this issue. There are the following error in your log:
> 
> ```
> -- Searching for libbson CMake packages
> -- Could NOT find bson-1.0 (missing: bson-1.0_DIR)
> CMake Error at CMakeLists.txt:10 (_message):
>   System libbson not found
> Call Stack (most recent call first):
>   CMakeLists.txt:160 (message) 
> ```
> 
> Could you check `libbson` is installed on your VCPKG?

**Comment by aiyou4love** [comment]
vcpkg remove libbson:x64-windows 
vcpkg install libbson:x64-windows
vcpkg install mongo-cxx-driver:x64-windows

install sucess

**Comment by LilyWangL** [comment]
> vcpkg remove libbson:x64-windows
> vcpkg install libbson:x64-windows
> vcpkg install mongo-cxx-driver:x64-windows
> 
> install sucess

This is because the version of libbson is low, reinstallation can solve this problem. This issue has been fixed, so I am closing this issue.
