### ISSUE TITLE
Include vcpkg.exe in the repo

### ISSUE THREAD

**Issue by paul-michalik** [microsoft/vcpkg#1397]
Unless I missed some important information, I see no possibility how to differentiate between updates to the vcpkg source code and changes to the "content", i.e. the portfiles and such.  This causes that uin my automation scripts I always need to call bootstrap-vcpkg which builds the executable from source. It would help a lot if you either (a) check in a compatible self-contained ``vcpkg.exe`` binary or (b) (and even better) separate the content from the package manger implementation completely. By the way, why on earth is this implemented in C++ and not is PowerShell & Co.?

**Comment by LilyWangL** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen.
