### ISSUE TITLE
opencv build failed using vcpkg

### ISSUE THREAD

**Issue by sujsin77** [microsoft/vcpkg#13974]
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/5360601/install-x64-windows-dbg-out.log)

**To Reproduce**
 .\vcpkg.exe install opencv[ffmpeg]

**Comment by JackBoosY** [comment]
Please copy `libprotobuf.dll` and `libprotoc.dll` from _C:\Software\vcpkg-master\installed\x64-windows\bin_ to _C:\Software\vcpkg-master\installed\x64-windows\tools\protobuf_ and try again.

Thanks.

**Comment by sujsin77** [comment]
@JackBoosY  both files libprotobuf.dll and libprotoc.dll are already in C:\Software\vcpkg-master\installed\x64-windows\tools\protobuf  location.

**Comment by sujsin77** [comment]
Anyway issue resolved by installing latest update of Visual C++ Redistribution 2015-2019, thanks
