### ISSUE TITLE
GeographicLib build failure: Features was expected to be an array of feature definitions

### ISSUE THREAD

**Issue by PayasR** [microsoft/vcpkg#13973]
**Host Environment**
- OS: Windows 10
- Compiler: Visual Studio 2019

**To Reproduce**
![image](https://user-images.githubusercontent.com/7341082/95669057-e5ff9480-0b30-11eb-943d-2568ca7f5b8b.png)

**Comment by NancyLi1013** [comment]
Hi @PayasR 
Thanks for posting this issue.
After using `git pull`, have you run the script `.\bootstrap-vcpkg.bat`?

**Comment by PayasR** [comment]
Ah that worked, thank you so much!
