### ISSUE TITLE
CMake fails to find the configs automatically

### ISSUE THREAD

**Issue by matteoturini** [microsoft/vcpkg#13981]
**Describe the bug**
CMake fails to find the configs for every single package that I install through vcpkg.

**Environment**
macOS Catalina
CMake 3.17
JetBrains CLion

**To Reproduce**
1. git clone https://github.com/matteoturini/sdl2-tutorial.git
2. Open the folder in CLion

**Expected behavior**
No CMake errors.

**Failure logs** 
```
Could not find a package configuration file provided by "sdl2-image" with
  any of the following names:

    sdl2-imageConfig.cmake
    sdl2-image-config.cmake

  Add the installation prefix of "sdl2-image" to CMAKE_PREFIX_PATH or set
  "sdl2-image_DIR" to a directory containing one of the above files.  If
  "sdl2-image" provides a separate development package or SDK, be sure it has
  been installed.
```

**Comment by JackBoosY** [comment]
Did you use vcpkg toolchain?

**Comment by matteoturini** [comment]
I just added it, it works. Thanks!
