### ISSUE TITLE
[bootstrap-vcpkg.bat] open failed

### ISSUE THREAD

**Issue by potato0205** [microsoft/vcpkg#13983]
In the vcpkg root directory, run the vcpkg bootstrapper:

bootstrap-vcpkg.bat (Windows) open failed.
At 9:00am,in shanghai .

**Comment by PhoebeHui** [comment]
@potato0205, what failure does it show?  I can't repro this issue locally.

**Comment by potato0205** [comment]
Cannot enter command statement, turn on auto end




---Original---

**Comment by JackBoosY** [comment]
@potato0205 Please use powershell to run that batch file.

**Comment by potato0205** [comment]
I will try,thank you.



---Original---

**Comment by PhoebeHui** [comment]
@potato0205, does the issue persist?

**Comment by PhoebeHui** [comment]
@potato0205, reopen this issue if it still be a problem for you.
