### ISSUE TITLE
[libzip] enable support for zstd compression

### ISSUE THREAD

**Issue by krab** [microsoft/vcpkg#13985]
zstd was added as compression method to zip file format specification:  
https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT
` 93 - Zstandard (zstd) Compression  `

libzip and minizip support them in latest updates:  
https://github.com/nih-at/libzip/blob/master/CMakeLists.txt#L20  
but its need to be enabled in current vcpkg port!

**Comment by krab** [comment]
apparently zstd support exist only in current git master not in 1.7.3...

**Comment by JonLiu1993** [comment]
Hi @krab ,sorry! Currently, version 1.7.3 does not support zstd, and the release of the updated version has not been released yet. I will update and add features after the latest version is released. Do you think it is okay?

**Comment by krab** [comment]
> 
> 
> Hi @krab ,sorry! Currently, version 1.7.3 does not support zstd, and the release of the updated version has not been released yet. I will update and add features after the latest version is released. Do you think it is okay?

Yeah, don't need to push unreleased git code into vcpkg repo.

**Comment by 0-wiz-0** [comment]
libzip 1.8.0 is out with zstd support.

**Comment by JonLiu1993** [comment]
> libzip 1.8.0 is out with zstd support.

OK,I will submit pr update libzip to 1.8.0
