### ISSUE TITLE
Error: Building package boost-build:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by StepLogic** [microsoft/vcpkg#13999]
**Host Environment**
- Windows
- Microsoft Visual C++

**To Reproduce**
`./vcpkg install boost`

**Failure logs** 
-Additional packages (*) will be modified to complete this operation.
Starting package 1/117: boost-build:x86-windows
Building package boost-build[core]:x86-windows...
-- Using cached C:/Users/Gyaase Elvis/source/repos/vcpkg/downloads/boostorg-build-boost-1.73.0.tar.gz
-- Using source at C:/Users/Gyaase Elvis/source/repos/vcpkg/buildtrees/boost-build/src/ost-1.73.0-018fb008dd
-- Using cached C:/Users/Gyaase Elvis/source/repos/vcpkg/downloads/boost_LICENSE_1_0.txt
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.73.0/boostcpp.jam...
-- Installing: C:/Users/Gyaase Elvis/source/repos/vcpkg/packages/boost-build_x86-windows/share/boost-build/copyright
-- Installing: C:/Users/Gyaase Elvis/source/repos/vcpkg/packages/boost-build_x86-windows/tools/boost-build/boostcpp.jam
-- Bootstrapping...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: "C:/Users/Gyaase Elvis/source/repos/vcpkg/packages/boost-build_x86-windows/tools/boost-build/bootstrap.bat" msvc
    Working Directory: C:/Users/Gyaase Elvis/source/repos/vcpkg/packages/boost-build_x86-windows/tools/boost-build
    Error code: 1
    See logs for more information:
      C:\Users\Gyaase Elvis\source\repos\vcpkg\buildtrees\boost-build\bootstrap-x86-windows-out.log
      C:\Users\Gyaase Elvis\source\repos\vcpkg\buildtrees\boost-build\bootstrap-x86-windows-err.log

Call Stack (most recent call first):
  ports/boost-build/portfile.cmake:60 (vcpkg_execute_required_process)
  scripts/ports.cmake:73 (include)

[bootstrap-x86-windows-err.log](https://github.com/microsoft/vcpkg/files/5366016/bootstrap-x86-windows-err.log)
[bootstrap-x86-windows-out.log](https://github.com/microsoft/vcpkg/files/5366017/bootstrap-x86-windows-out.log)
.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by PhoebeHui** [comment]
@StepLogic, from your log, it seems the VS toolset doesn't install correctly, could you double check?

Failrues:
'cl' is not recognized as an internal or external command,
operable program or batch file.
File Not Found

**Comment by StepLogic** [comment]
Hi i was able to locate it  in this path
 C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\bin\Hostx64\x64
I am new to c++ ,so i cant tell if its supposed to be there

**Comment by PhoebeHui** [comment]
What does 'vcpkg env --triplet x86-windows --debug' show?

**Comment by PhoebeHui** [comment]
@StepLogic, does this still be a problem for you?

**Comment by StepLogic** [comment]
@PhoebeHui  thanks ..for the support ..I am current setting up on new computer from my older computer if i encounter the same error i will do well to reopen the issue
