### ISSUE TITLE
Failed to install g2o on windows

### ISSUE THREAD

**Issue by ArtlyStyles** [microsoft/vcpkg#14017]
Hi, I am trying to use the g2o library https://github.com/RainerKuemmerle/g2o on windows. I follow the instruction to install it use the following script .bat file:

==============Start of bat file ================================
@echo off

setlocal

rem ----------------------------------
rem Locate vcpkg using environment variables falling back to sensible defaults
rem ----------------------------------
set "VcPkgDir=%USERPROFILE%\.vcpkg\vcpkg"
set "VcPkgTriplet=x64-windows"
if defined VCPKG_ROOT_DIR if /i not "%VCPKG_ROOT_DIR%"=="" set "VcPkgDir=%VCPKG_ROOT_DIR%"
if defined VCPKG_DEFAULT_TRIPLET if /i not "%VCPKG_DEFAULT_TRIPLET%"=="" set "VcPkgTriplet=%VCPKG_DEFAULT_TRIPLET%"

pushd %VcPkgDir%

rem ==============================
rem Upgrade and Install packages.
rem ==============================
set "VcPkgLibs=eigen3 suitesparse clapack openblas ceres"

echo vcpkg found at %VcPkgDir%...
echo installing %VcPkgLibs% for triplet %VcPkgTriplet%...

call vcpkg upgrade %VcPkgLibs% --no-dry-run --triplet %VcPkgTriplet%
call vcpkg install %VcPkgLibs% --triplet %VcPkgTriplet%

popd

endlocal & set "VcPkgDir=%VcPkgDir%" & set "VcPkgTriplet=%VcPkgTriplet%"

==================End of bat =========================

But I got the following errors:

Package ceres:x64-windows is already installed
Package clapack:x64-windows is already installed
Package eigen3:x64-windows is already installed
Package openblas:x64-windows is already installed
Detecting compiler hash for triplet x64-windows...
Starting package 5/4: lapack-reference:x64-windows
Building package lapack-reference[blas-select,core,noblas]:x64-windows...
Could not locate cached archive: C:\Users\gcong\AppData\Local\vcpkg\archives\02\020e39d13d0484a2c3f6f3b9ec57ea6a08bae5b6.zip
CMake Error at ports/lapack-reference/portfile.cmake:8 (message):
  Can't build lapack-reference if clapack is installed.  Please remove
  clapack:x64-windows, and try to install lapack-reference:x64-windows again.
Call Stack (most recent call first):
  scripts/ports.cmake:79 (include)

Error: Building package lapack-reference:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: lapack-reference:x64-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.

My computer:
 Windows 10
  Package: lapack-reference:x64-windows
  Vcpkg version: 2020.06.15-nohash

How can I fix it?

**Comment by NancyLi1013** [comment]
```
Can't build lapack-reference if clapack is installed. Please remove
clapack:x64-windows, and try to install lapack-reference:x64-windows again.
```
Since `lapack-reference` and `clapack ` have conflicts with each other, they cannot be installed at the same time. So Please remove `clapack ` first, then try to rebuild this.

`.\vcpkg remove clapack :x64-windows`

**Comment by NancyLi1013** [comment]
Hi @ArtlyStyles 
Please let me know if this is still a problem for you.

Thanks.

**Comment by NancyLi1013** [comment]
I'm closing this issue for now since there is no response.

Please feel free to reopen this if it is still a problem for you.

**Comment by lzyplayer** [comment]
Hi @NancyLi1013! I have come across the same problem as @ArtlyStyles. I have tried to remove `clapack` and install `lapack-reference`.  And it works well! I succeed in installing lapack-reference. However, I cannot install Clapack after that because of Conflict.
```
PS D:\Software\vcpkg> ./vcpkg install eigen3 suitesparse clapack openblas ceres --triplet x64-windows
Computing installation plan...
The following packages are already installed:
    ceres[core]:x64-windows -> 2.1.0#2
    eigen3[core]:x64-windows -> 3.4.0#2
    openblas[core]:x64-windows -> 0.3.21
The following packages will be built and installed:
    clapack[core]:x64-windows -> 3.2.1#20
  * lapack[core]:x64-windows -> 2022-02-22
  * metis[core]:x64-windows -> 2022-07-27
    suitesparse[core]:x64-windows -> 5.8.0#1
Additional packages (*) will be modified to complete this operation.
ceres:x64-windows is already installed
eigen3:x64-windows is already installed
openblas:x64-windows is already installed
Detecting compiler hash for triplet x64-windows...
Restored 1 package(s) from C:\Users\blakelin\AppData\Local\vcpkg\archives in 241.3 ms. Use --debug to see more details.
Installing 1/4 clapack:x64-windows...
The following files are already installed in D:/Software/vcpkg/installed/x64-windows and are in conflict with clapack:x64-windows

Installed by lapack-reference:x64-windows
    lib/lapack.lib
    share/lapack/FindLAPACK.cmake
    share/lapack/vcpkg-cmake-wrapper.cmake

Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+clapack
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[clapack]+Build+error
Include '[clapack] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-09-01-dfb82802c8cc562ce3b665a904a65b22314de724
    vcpkg-scripts version: 927006b24 2022-09-02 (3 days ago)
```

**Comment by jyotimadakevit** [comment]
Did anyone get a solution the above issue ?


```
The following files are already installed in D:/Software/vcpkg/installed/x64-windows and are in conflict with clapack:x64-windows

Installed by lapack-reference:x64-windows
    lib/lapack.lib
    share/lapack/FindLAPACK.cmake
    share/lapack/vcpkg-cmake-wrapper.cmake

Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+clapack
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[clapack]+Build+error
Include '[clapack] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-09-01-dfb82802c8cc562ce3b665a904a65b22314de724
    vcpkg-scripts version: 927006b24 2022-09-02 (3 days ago)
```
