### ISSUE TITLE
[New Port Request] Squirrel

### ISSUE THREAD

**Issue by raphasanori** [microsoft/vcpkg#14013]
Library name: Squirrel

Library description: Squirrel is a high level imperative, object-oriented programming language, designed to be a light-weight scripting language that fits in the size, memory bandwidth, and real-time requirements of applications like video games.

Source repository URL: https://github.com/albertodemichelis/squirrel

Project homepage (if different from the source repository): http://squirrel-lang.org

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
