### ISSUE TITLE
[New Port Request] <Spot>

### ISSUE THREAD

**Issue by DangMinh24** [microsoft/vcpkg#14010]
Library name: Spot: a platform for LTL and ω-automata manipulation

Library description: Spot is a C++14 library for LTL, ω-automata manipulation and model checking

Source repository URL: http://www.lrde.epita.fr/dload/spot/spot-2.9.4.tar.gz

Project homepage (if different from the source repository): https://spot.lrde.epita.fr/

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
