### ISSUE TITLE
[pthreads] build failure on community triplet x64-mingw-dynamic

### ISSUE THREAD

**Issue by thumpro** [microsoft/vcpkg#14012]
**Host Environment**
- OS: Windows Mingw-W64
- Compiler: g++ 10.2

**To Reproduce**
`.\vcpkg.exe install pthreads:x64-mingw-dynamic`

**Failure logs** 

> CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:85 (message):
    Command failed: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/nmake.exe" -f Makefile all install DESTROOT="C:\dev\vcpkg\packages\pthreads_x64-mingw-dynamic"
    Working Directory: C:/dev/vcpkg/buildtrees/pthreads/src/49e541b66c-bb03a1deb3.clean
    Error code: 2
    See logs for more information:
      C:\dev\vcpkg\buildtrees\pthreads\nmake-build-x64-mingw-dynamic-release-out.log
      C:\dev\vcpkg\buildtrees\pthreads\nmake-build-x64-mingw-dynamic-release-err.log

Relevant logs are in 

> C:\dev\vcpkg\buildtrees\pthreads\nmake-build-x64-mingw-dynamic-release-out.log
      C:\dev\vcpkg\buildtrees\pthreads\nmake-build-x64-mingw-dynamic-release-err.log

**Additional context**
The port required me to add `nmake` to the `$PATH` and first it failed for that reason. This is not the current issue as I added it to `$PATH` and moved on but still, I assumed `vcpkg` would take care of such toolchain issues for me. Anyways, the actual issue is apparent in the above log files:

> .\_ptw32.h(143): fatal error C1083: Cannot open include file: 'errno.h': No such file or directory

Isn't `errno.h` is a standard C header? How can nmake not found it? Note a lot of other packages have a dependency on pthreads library.

**Comment by sfhacker** [comment]
We have had no issues building pthreads on MinGW.
I wasn't aware nmake was required. Have you tried to build master branch?

**Comment by thumpro** [comment]
Yes I am using master and the portfile for pthreads was not updated for quite a while anyways. So yes, I think I am using the most up-to-date version of the port.

**Comment by sfhacker** [comment]
I have no idea where nmake comes from or why! We do not use it at all.
You seem to have prepared a salad here! You are mixing MSBuild tools with g++!
Anyway, can you provide a simple test case I can try locally?

**Comment by sfhacker** [comment]
You should not mix environments and/or compilers! You are looking for trouble!
Have you tried building pthreads from source without using NMAKE?

**Comment by thumpro** [comment]
Is it possible to not use the portfile.cmake for a port while building with vcpkg? As I explained, I am just following the intallation instructions on the `README.md`:

1. Clone vcpkg into a clean, new directory. `git clone https://github.com/microsoft/vcpkg`
2. Bootstrap it: .\bootstrap-vcpkg.bat
3. Open a MSYS2 MinGW64 shell.
4. `./vcpkg.exe install pthreads:x64-mingw-dynamic

These four simple steps always, consistently fail for me.

**Comment by sfhacker** [comment]
Perhaps, your environment is broken somehow.
Try to think of/find a workaround or ...... ask your workmates for assistance or ..... don't know what else to suggest!

**Comment by thumpro** [comment]
But I want to make sure, am I setting up vcpkg correctly up to step 4 above? 

From the docs, It is not clear how to setup your environment for mingw community triplets. (Makes sense since this is not a supported official triplet) For example, do I have to set MINGW_PATH or does vcpkg download its own version of the mingw toolchain? Should I have MSVC toolchain on my PATH even when building with 64-mingw-dynamic? Because as it stands, I can't really figure out how I might be mixing environments.

**Comment by longnguyen2004** [comment]
This port currently doesn't support mingw yet, but given that it already has winpthreads, I'm not sure why you would need it. Anyway I'll take a look

**Comment by thumpro** [comment]
I am not keen on building it but a lot of the packages depend on it and triplet is not using winpthreads that comes with MinGW installation.

**Comment by longnguyen2004** [comment]
Hmm then maybe I'll add an exception to not build pthreads4w on mingw triplets, give me some time.

**Comment by longnguyen2004** [comment]
> But I want to make sure, am I setting up vcpkg correctly up to step 4 above?
> 
> From the docs, It is not clear how to setup your environment for mingw community triplets. (Makes sense since this is not a supported official triplet).
You just have to make sure the mingw toolchain is on your PATH, then vcpkg will automatically use it when you use a mingw triplet.
I regularly mix x64-windows and x64-mingw-dynamic and haven't had a problem.

**Comment by longnguyen2004** [comment]
@thumpro Would you like to have it built on mingw anyway, or just use winpthreads?

**Comment by thumpro** [comment]
I don't have a strong preference on this particular port actually. For me, as long as ports depending on it build, that's all I need. But considering the overall philosophy of vcpkg and being able to build all dependencies from source, I guess having it buildable with MinGW would be more appropriate.

**Comment by longnguyen2004** [comment]
Right then, but I'll add a warning saying that it might be incompatible with winpthreads.

**Comment by sfhacker** [comment]
@thumpro Can you post here the screenshot showing the error messages you get when building this port from source?
I'll see what I can do to assist you.

**Comment by thumpro** [comment]
I will update as soon as I find time.

**Comment by patzf** [comment]
@thumpro : did you ever resolve that issue? I think I ran into the same problem although your issues dates back a year!

**Comment by longnguyen2004** [comment]
We decided on falling back to libwinpthreads for mingw-w64 targets. Is there any problems with that?

**Comment by patzf** [comment]
@longnguyen2004 : Thanks for the reply. To be honest, I am rather lost with https://github.com/microsoft/vcpkg/issues/22288, and somehow it seems to me that this issue could be related, but really I do not know. Could you shortly cross-check and give some feedback if you see a relation?

**Comment by dg0yt** [comment]
> I am rather lost with #22288, and somehow it seems to me that this issue could be related, but really I do not know

It is not related. Port libwebsocket is not ready for building with mingw. There are more showstoppers in the portfile.

**Comment by sfhacker** [comment]
This open issue is over a year old!

@patzf Can you post here the screenshot showing the error messages you get when building this port from source?
I'll see what I can do to assist you.

Cheers.

**Comment by JackBoosY** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
