### ISSUE TITLE
[libvorbis:x64-mingw-static] build failure

### ISSUE THREAD

**Issue by Trider12** [microsoft/vcpkg#14020]
**Host Environment**
- OS: Windows 10
- Compiler: Mingw-w64 5.0.4

**To Reproduce**
`./vcpkg install libvorbis --triplet x64-mingw-static`

**Failure logs** 
Computing installation plan...
The following packages will be built and installed:
    libvorbis[core]:x64-mingw-static
Detecting compiler hash for triplet x64-mingw-static...
Starting package 1/1: libvorbis:x64-mingw-static
Building package libvorbis[core]:x64-mingw-static...
Could not locate cached archive: C:\Users\Trider\AppData\Local\vcpkg\archives\47\473d16276b48e3a6c196a984423c6b665fa55ba7.zip
-- Using community triplet x64-mingw-static. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: D:\GitRepos\vcpkg\triplets\community\x64-mingw-static.cmake
-- Using cached D:/GitRepos/vcpkg/downloads/xiph-vorbis-v1.3.7.tar.gz
-- Cleaning sources at D:/GitRepos/vcpkg/buildtrees/libvorbis/src/v1.3.7-6c4ca9c573.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/GitRepos/vcpkg/downloads/xiph-vorbis-v1.3.7.tar.gz
-- Applying patch 0001-Dont-export-vorbisenc-functions.patch
-- Applying patch 0002-Fixup-pkgconfig-libs.patch
-- Using source at D:/GitRepos/vcpkg/buildtrees/libvorbis/src/v1.3.7-6c4ca9c573.clean
-- Configuring x64-mingw-static
-- Building x64-mingw-static-dbg
-- Building x64-mingw-static-rel
-- Using msys root at D:/GitRepos/vcpkg/downloads/tools/msys2/c809757c94447846
-- Fixing pkgconfig file: D:/GitRepos/vcpkg/packages/libvorbis_x64-mingw-static/lib/pkgconfig/vorbis.pc
-- Fixing pkgconfig file: D:/GitRepos/vcpkg/packages/libvorbis_x64-mingw-static/lib/pkgconfig/vorbisenc.pc
-- Fixing pkgconfig file: D:/GitRepos/vcpkg/packages/libvorbis_x64-mingw-static/lib/pkgconfig/vorbisfile.pc
-- CHECK_LIB_m_RELEASE:CHECK_LIB_m_RELEASE-NOTFOUND
CMake Error at scripts/cmake/vcpkg_fixup_pkgconfig.cmake:232 (message):
  Library "m" was not found! If it is a system library use the
  SYSTEM_LIBRARIES parameter for the vcpkg_fixup_pkgconfig call! Otherwise,
  correct the *.pc file
Call Stack (most recent call first):
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:297 (vcpkg_fixup_pkgconfig_check_files)
  ports/libvorbis/portfile.cmake:30 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:79 (include)

Error: Building package libvorbis:x64-mingw-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libvorbis:x64-mingw-static
  Vcpkg version: 2020.06.15-nohash

**Additional context**
Was actually trying to install SFML. vcpkg is up to date.

**Comment by PhoebeHui** [comment]
@Trider12, this is not usual scenario we're working on now, does anybody who help have a look?

I tried to build libvorbis:x64-windows-static, however, I can't repro this issue, what does D:/GitRepos/vcpkg/packages/libvorbis_x64-mingw-static/lib/pkgconfig/vorbisfile.pc look like?

**Comment by Trider12** [comment]
@PhoebeHui, Hi. These are the contents of the file:
`prefix=${pcfiledir}/../..
# libvorbisfile pkg-config source file

exec_prefix=${prefix}/bin
libdir=${prefix}/lib
includedir=${prefix}/include

Name: vorbisfile
Description: vorbisfile is a library that provides a convenient high-level API for decoding and basic manipulation of all Vorbis I audio streams
Version: 1.3.7
Requires.private: vorbis
Conflicts:
Libs: -L${libdir} -lvorbisfile
Cflags: -I${includedir}
`

**Comment by PhoebeHui** [comment]
@Trider12 , I see, the m library added by https://github.com/microsoft/vcpkg/blob/master/ports/libvorbis/0002-Fixup-pkgconfig-libs.patch#L10

It may has libm in mingw, however, the scripts/cmake/vcpkg_fixup_pkgconfig.cmake has not good support on mingw. So it can't find the library.

cc @Neumann-A

**Comment by Neumann-A** [comment]
https://github.com/microsoft/vcpkg/blob/7e3d3beac5ca6fe8aab4599d4e1d8ce270ccdea8/scripts/cmake/vcpkg_common_definitions.cmake#L126-L129 probably needs to be updated for mingw? mingw is a community triplet so I don't care enough about it to make it work.

**Comment by Trider12** [comment]
@Neumann-A, thanks! That solved the issue with libvorbis, however, I tried installing SFML again and have the following:

```
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:85 (message):
    Command failed: ninja -v
    Working Directory: D:/GitRepos/vcpkg/buildtrees/openal-soft/x64-mingw-static-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\GitRepos\vcpkg\buildtrees\openal-soft\config-x64-mingw-static-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:305 (vcpkg_execute_required_process)
  ports/openal-soft/portfile.cmake:35 (vcpkg_configure_cmake)
  scripts/ports.cmake:79 (include)


Error: Building package openal-soft:x64-mingw-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openal-soft:x64-mingw-static
  Vcpkg version: 2020.06.15-nohash
```

I checked the logs and see this error:
```
...
CMake Warning (dev) at D:/GitRepos/vcpkg/downloads/tools/cmake-3.17.2-windows/cmake-3.17.2-win32-x86/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:272 (message):
  The package name passed to `find_package_handle_standard_args` (WindowsSDK)
  does not match the name of the calling package (DSound).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/FindWindowsSDK.cmake:472 (find_package_handle_standard_args)
  cmake/FindDSound.cmake:12 (include)
  D:/GitRepos/vcpkg/scripts/buildsystems/vcpkg.cmake:530 (_find_package)
  CMakeLists.txt:884 (FIND_PACKAGE)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- No compatible version of the Windows SDK or Platform SDK found. (missing: WINDOWSSDK_DIRS) 
-- Could NOT find DSound (missing: DSOUND_LIBRARY DSOUND_INCLUDE_DIR) 
-- Looking for mmdeviceapi.h
-- Looking for mmdeviceapi.h - found
CMake Error at CMakeLists.txt:911 (MESSAGE):
  Failed to enabled required WinMM backend
```

I then checked that I do indeed have the `Windows SDK 10.0.18362.0` installed and the `dsound.lib` is there under x64. I'm guessing I need to somehow point CMake to that location?

**Comment by Neumann-A** [comment]
https://cmake.org/cmake/help/latest/command/find_package.html#search-procedure

**Comment by Trider12** [comment]
Seems to be connected with #7790

**Comment by PhoebeHui** [comment]
The PR has been merged, thanks for your contibution!
