### ISSUE TITLE
Building package google-cloud-cpp:x86-windows-static-crt-dynamic failed

### ISSUE THREAD

**Issue by heylaender** [microsoft/vcpkg#14027]
Visual Studio Professional 2017
Version 15.9.25

Error: Building package google-cloud-cpp:x86-windows-static-crt-dynamic failed with: BUILD_FAILED
Package: google-cloud-cpp:x86-windows-static-crt-dynamic
Vcpkg version: 2020.06.15-nohash

C:\PROGRA~2\MICROS~3\2017\PROFES~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x86\cl.exe   /TP -DCARES_STATICLIB -D_WIN32_WINNT=0x600 -D__CLANG_SUPPORT_DYN_ANNOTATION__ -IC:\vcpkg\buildtrees\google-cloud-cpp\src\v1.19.0-cfe480c072.clean -I. -IC:\vcpkg\installed\x86-windows-static-crt-dynamic\include -Iexternal\googleapis /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1    /W3 /experimental:external /external:W0 /external:anglebrackets /showIncludes /Fogoogle\cloud\spanner\CMakeFiles\spanner_client.dir\numeric.cc.obj /Fdgoogle\cloud\spanner\CMakeFiles\spanner_client.dir\spanner_client.pdb /FS -c C:\vcpkg\buildtrees\google-cloud-cpp\src\v1.19.0-cfe480c072.clean\google\cloud\spanner\numeric.cc
C:\vcpkg\buildtrees\google-cloud-cpp\src\v1.19.0-cfe480c072.clean\google\cloud\spanner\numeric.cc(37): error C2672: 'std::isdigit': no matching overloaded function found
C:\vcpkg\buildtrees\google-cloud-cpp\src\v1.19.0-cfe480c072.clean\google\cloud\spanner\numeric.cc(37): error C2780: 'bool std::isdigit(_Elem,const std::locale &)': expects 2 arguments - 1 provided
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include\locale(218): note: see declaration of 'std::isdigit'
C:\vcpkg\buildtrees\google-cloud-cpp\src\v1.19.0-cfe480c072.clean\google\cloud\spanner\numeric.cc(41): error C2672: 'std::isspace': no matching overloaded function found
C:\vcpkg\buildtrees\google-cloud-cpp\src\v1.19.0-cfe480c072.clean\google\cloud\spanner\numeric.cc(41): error C2780: 'bool std::isspace(_Elem,const std::locale &)': expects 2 arguments - 1 provided
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include\locale(253): note: see declaration of 'std::isspace'

[config-x86-windows-static-crt-dynamic-dbg-out.log](https://github.com/microsoft/vcpkg/files/5376735/config-x86-windows-static-crt-dynamic-dbg-out.log)
[install-x86-windows-static-crt-dynamic-dbg-out.log](https://github.com/microsoft/vcpkg/files/5376739/install-x86-windows-static-crt-dynamic-dbg-out.log)
[stdout-x86-windows-static-crt-dynamic.log](https://github.com/microsoft/vcpkg/files/5376742/stdout-x86-windows-static-crt-dynamic.log)
[x86-windows-static-crt-dynamic.vcpkg_abi_info.txt](https://github.com/microsoft/vcpkg/files/5376743/x86-windows-static-crt-dynamic.vcpkg_abi_info.txt)

**Comment by heylaender** [comment]
[x86-windows-static-crt-dynamic.cmake.txt](https://github.com/microsoft/vcpkg/files/5376809/x86-windows-static-crt-dynamic.cmake.txt)

**Comment by heylaender** [comment]
any news regarding the bug

**Comment by metal-crow** [comment]
A temporary fix I've found is to remove the `std::` part of `std::isspace` and `std::isdigit` from the lines in numeric.cc referenced in the errors.

**Comment by JonLiu1993** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue

**Comment by JonLiu1993** [comment]
@heylaender ,Thanks for posting this issue ,I can successfully install google-cloud-cpp:x86-windows-static-crt-dynamic with the latest vcpkg, I temporarily close this issue, if it is still an issue, please reopen this issue.
````
-- Performing post-build validation done
Stored binary cache: C:\Users\vzhli17\AppData\Local\vcpkg\archives\ae\ae9774c323cf860699fb289c3e58f7843f2ccbbd35ac3cab4b4d191f42d04d8a.zip
Installing package google-cloud-cpp[bigquery,bigtable,core,iam,pubsub,spanner,storage]:x86-windows-static-crt-dynamic...
Elapsed time for package google-cloud-cpp:x86-windows-static-crt-dynamic: 11.03 min

Total elapsed time: 36.68 min

The package google-cloud-cpp provides CMake targets:

    find_package(google_cloud_cpp_bigquery CONFIG REQUIRED)
    target_link_libraries(main PRIVATE google-cloud-cpp::bigquery)

    find_package(google_cloud_cpp_bigtable CONFIG REQUIRED)
    target_link_libraries(main PRIVATE google-cloud-cpp::bigtable)

    find_package(google_cloud_cpp_common CONFIG REQUIRED)
    target_link_libraries(main PRIVATE google_cloud_cpp_common google-cloud-cpp::common)

    find_package(google_cloud_cpp_googleapis CONFIG REQUIRED)
    # Note: 49 target(s) were omitted.
    target_link_libraries(main PRIVATE gRPC::grpc gRPC::grpc++ protobuf::libprotoc protobuf::libprotobuf)

    find_package(google_cloud_cpp_grpc_utils CONFIG REQUIRED)
    target_link_libraries(main PRIVATE google_cloud_cpp_grpc_utils google-cloud-cpp::grpc_utils)

    find_package(google_cloud_cpp_iam CONFIG REQUIRED)
    target_link_libraries(main PRIVATE google-cloud-cpp::iam)

    find_package(google_cloud_cpp_pubsub CONFIG REQUIRED)
    target_link_libraries(main PRIVATE google-cloud-cpp::pubsub)

    find_package(google_cloud_cpp_spanner CONFIG REQUIRED)
    target_link_libraries(main PRIVATE google-cloud-cpp::spanner)

    find_package(google_cloud_cpp_storage CONFIG REQUIRED)
    target_link_libraries(main PRIVATE CURL::libcurl google-cloud-cpp::storage google-cloud-cpp::experimental-storage-grpc)
````
