### ISSUE TITLE
[<libmysql>] build failure

### ISSUE THREAD

**Issue by rockydut** [microsoft/vcpkg#14022]
**Host Environment**
- OS: Windows
- Compiler: visual studio 2019

**To Reproduce**
`./vcpkg install libmysql:x64-windows-static`

**Failure logs** 
Computing installation plan...
The following packages will be built and installed:
  * icu[core]:x64-windows-static
  * libevent[core,thread]:x64-windows-static
    libmysql[core]:x64-windows-static
  * lz4[core]:x64-windows-static
  * xxhash[core]:x64-windows-static
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows-static...
Starting package 1/5: icu:x64-windows-static
Building package icu[core]:x64-windows-static...
Could not locate cached archive: C:\Users\rocky\AppData\Local\vcpkg\archives\15\15a67ea83360c2d3d3fa683c4826ed165261260e.zip
-- Using cached F:/Packages/vcpkg/downloads/icu4c-67_1-src.tgz
-- Cleaning sources at F:/Packages/vcpkg/buildtrees/icu/src/c-67_1-src-39ba50b26e.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source F:/Packages/vcpkg/downloads/icu4c-67_1-src.tgz
-- Applying patch F:/Packages/vcpkg/ports/icu/disable-escapestr-tool.patch
-- Applying patch F:/Packages/vcpkg/ports/icu/remove-MD-from-configure.patch
-- Applying patch F:/Packages/vcpkg/ports/icu/fix_parallel_build_on_windows.patch
-- Applying patch F:/Packages/vcpkg/ports/icu/fix-extra.patch
-- Using source at F:/Packages/vcpkg/buildtrees/icu/src/c-67_1-src-39ba50b26e.clean
-- Downloading https://repo.msys2.org/msys/x86_64/automake1.15-1.15.1-1-any.pkg.tar.xz...
-- Downloading https://repo.msys2.org/msys/x86_64/automake1.15-1.15.1-1-any.pkg.tar.xz... Failed. Status: 22;"HTTP response code said error"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:181 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_acquire_msys.cmake:97 (vcpkg_download_distfile)
  scripts/cmake/vcpkg_acquire_msys.cmake:232 (msys_package)
  ports/icu/portfile.cmake:80 (vcpkg_acquire_msys)
  scripts/ports.cmake:79 (include)

Error: Building package icu:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: icu:x64-windows-static
  Vcpkg version: 2020.06.15-nohash

**Additional context**
I think the main error is the installer try to download "automake1.15-1.15.1-1-any.pkg.tar.xz" from epo.msys2.org. However, I found there is not this file in this repository. 
There are two file named "automake1.15-1.15.1-2-any.pkg.tar.zst" and "automake1.15-1.15.1-2-any.pkg.tar.zst.sig".
Please update it to the new filename.

**Comment by PhoebeHui** [comment]
@rockydut, could you get vcpkg latest source and try again? PR#https://github.com/microsoft/vcpkg/pull/13889 has already add the mirror for msys, I tried it works. 

Starting package 1/1: icu:x86-windows
Building package icu[core]:x86-windows...
-- Using cached E:/vcpkg/clean/vcpkg/downloads/icu4c-67_1-src.tgz
-- Cleaning sources at E:/vcpkg/clean/vcpkg/buildtrees/icu/src/c-67_1-src-39ba50b26e.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/vcpkg/clean/vcpkg/downloads/icu4c-67_1-src.tgz
-- Applying patch E:/vcpkg/clean/vcpkg/ports/icu/disable-escapestr-tool.patch
-- Applying patch E:/vcpkg/clean/vcpkg/ports/icu/remove-MD-from-configure.patch
-- Applying patch E:/vcpkg/clean/vcpkg/ports/icu/fix_parallel_build_on_windows.patch
-- Applying patch E:/vcpkg/clean/vcpkg/ports/icu/fix-extra.patch
-- Using source at E:/vcpkg/clean/vcpkg/buildtrees/icu/src/c-67_1-src-39ba50b26e.clean
-- Downloading https://repo.msys2.org/msys/x86_64/automake1.15-1.15.1-1-any.pkg.tar.xz...
-- Downloading https://repo.msys2.org/msys/x86_64/automake1.15-1.15.1-1-any.pkg.tar.xz... Failed. Status: 22;"HTTP response code said error"
-- Downloading https://www2.futureware.at/~nickoe/msys2-mirror/msys/x86_64/automake1.15-1.15.1-1-any.pkg.tar.xz...
-- Using msys root at E:/vcpkg/clean/vcpkg/downloads/tools/msys2/350fcf76980ae57a

**Comment by PhoebeHui** [comment]
@rockydut, does the issue solved?

**Comment by rockydut** [comment]
Thanks, the problem has solved as what you said. Thanks.
