### ISSUE TITLE
[openssl][docker] Unable to cross-compile on Linux for Windows.

### ISSUE THREAD

**Issue by Nemirtingas** [microsoft/vcpkg#14031]
**Describe the bug**
I'm trying to cross-compile openssl for Windows and it fails.

**Environment**
- OS: Ubuntu 18.04 (docker image)
- Compiler: clang, clang-cl, llvm 9

**To Reproduce**
Get the clang cross-compiler toolchain here: https://github.com/Nemirtingas/clang-msvc-sdk
Setup the toolchain:
1. Get the Include and Lib folders of winsdk from C:\Program Files (x86)\Windows Kits\10
2. Get the include and lib folders of msvc from C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110
3. Set CLANG version: export CLANG_VER=9
4. Set LLVM version: export LLVM_VER=${CLANG_VER}
5. Set MSVC base: export MSVC_BASE=/clang_windows_sdk/msvc
6. Set WINSDK base: export WINSDK_BASE=/clang_windows_sdk/winsdk
7. Set WINSDK version: export WINSDK_VER=10.0.18362.0
8. Install dependencies: `apt -y install ninja-build build-essential python git wget curl p7zip zip unzip nasm clang-${CLANG_VER} clang-tools-${CLANG_VER} llvm-${CLANG_VER} lld-${CLANG_VER} gcc-mingw-w64-x86-64 binutils-mingw-w64-x86-64 pkg-config`
9. Add the cross-compiler triplet: /vcpkg/triplets/community/x86-windows-release.cmake
```
set(VCPKG_TARGET_ARCHITECTURE x86)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_BUILD_TYPE release)

set(ENV{HOST_ARCH} ${VCPKG_TARGET_ARCHITECTURE})

set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE /clang_windows_sdk/clang-cl-msvc.cmake)

set(ENV{VCPKG_TOOLCHAIN} "/vcpkg/scripts/toolchains/windows.cmake")
```

Build openssl
1. ./vcpkg install openssl:x86-windows-release
2. See error

**Expected behavior**
Expected it builds.

**Failure logs** 
```
-- Using source at /vcpkg/buildtrees/openssl-windows/src/openssl-1-bb2a9a5801.clean
CMake Error at scripts/cmake/vcpkg_find_acquire_program.cmake:525 (message):
  Could not find jom.  Please install it via your package manager.
Call Stack (most recent call first):
  ports/openssl-windows/portfile.cmake:29 (vcpkg_find_acquire_program)
  scripts/ports.cmake:79 (include)
```

After removing `vcpkg_find_acquire_program(JOM)` from openssl-windows, I have another error:
```
******************************************************************************
This perl implementation doesn't produce Windows like paths (with backward
slash directory separators).  Please use an implementation that matches your
building platform.

This Perl version: 5.26.1 for x86_64-linux-gnu-thread-multi
******************************************************************************
```

Then again after removing this check from /vcpkg/buildtrees/openssl-windows/src/openssl-1-bb2a9a5801/Configurations/windows-checker.pm, another error:
```
Make Error at scripts/cmake/vcpkg_execute_required_process.cmake:85 (message):
    Command failed: nmake -f makefile install_sw install_ssldirs
    Working Directory: /vcpkg/buildtrees/openssl-windows/x86-windows-release-rel
    Error code: No such file or directory
    See logs for more information:

Call Stack (most recent call first):
  ports/openssl-windows/portfile.cmake:99 (vcpkg_execute_required_process)
  scripts/ports.cmake:79 (include)
```

So I rename nmake to make:
```
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:85 (message):
    Command failed: make -f makefile install_sw install_ssldirs
    Working Directory: /vcpkg/buildtrees/openssl-windows/x86-windows-release-rel
    Error code: 2
    See logs for more information:
      /vcpkg/buildtrees/openssl-windows/build-x86-windows-release-rel-1-err.log

Call Stack (most recent call first):
  ports/openssl-windows/portfile.cmake:99 (vcpkg_execute_required_process)
  scripts/ports.cmake:79 (include)


Error: Building package openssl-windows:x86-windows-release failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openssl-windows:x86-windows-release
  Vcpkg version: 2020.06.15-unknownhash

Additionally, attach any relevant sections from the log files above.
cat /vcpkg/buildtrees/openssl-windows/build-x86-windows-release-rel-1-err.log
makefile:56: *** missing separator.  Stop.
```

This seems pretty bad, I won't be able to build openssl while cross-compiling ;).

**Comment by Nemirtingas** [comment]
I found a way to build open-ssl: https://github.com/janbar/openssl-cmake.
It works nearly out of the box. Just need 2 CMake defines to make it cross-compile for Windows.

**Comment by Nemirtingas** [comment]
For my own use, I've made a openssl cross-compile branch that uses the openssl-cmake project: https://github.com/Nemirtingas/vcpkg/tree/openssl_crosscompile_fix
I don't know if it works everywhere. Why don't openssl team just support CMake ? That would be so easier for everyone. openssl is a pain to build.

**Comment by longnguyen2004** [comment]
It is a pain to build. Why don't they just use forward slashes everywhere, and instead requires the MSVC target to use a backslash-aware Perl, which pretty much doesn't exist in Linux land? Also, they seem to be targeting obscure targets as well, which we don't really need. However I'm not the one who can decide on what to use, but I would certainly appreciate switching over to openssl-cmake.

**Comment by Nemirtingas** [comment]
The only concerning thing is that openssl-cmake is not supported by openssl team, so someone needs to keep it up to date with openssl main branch/stable releases.

**Comment by JonLiu1993** [comment]
This issue hasn’t been updated more than 3 months, if it is still an issue, please reopen this issue.

**Comment by Nemirtingas** [comment]
Hi, yes its still an issue, but I'm not sure it worth re-opening as I'm pretty sure no-one is going to fix it.
I fixed it locally by using openssl-cmake.

**Comment by dg0yt** [comment]
> Yes its still an issue, but I'm not sure it worth re-opening as I'm pretty sure no-one is going to fix it.
> I fixed it locally by using openssl-cmake.

You use a non-standard toolchain, so you are the expert to fix it. Cross-compiling on Linux for Windows basically works with mingw, but you don't seem to talk about mingw clang.

**Comment by Nemirtingas** [comment]
Does MinGW can use the MSVC libraries ? From what I read, it don't but I could be wrong. I need to be ABI compatible with MSVC thats why I use clang-cl with MSVC.

**Comment by sfhacker** [comment]
This issue has remained open for a long time and still not resolved!

> From what I read, it don't but I could be wrong.

(Maybe a typo there?)
I was told that libraries generated by MinGW (in most cases) are compatible with MSVC.

> I never successfully built openssl even when building on Linux -> Linux,

Wow! It is pretty straight forward. Just basic stuff: configure, make, .....

@Nemirtingas If you are able to provide a use (or test) case, I can check whether or not libraries are compatible for you.
