### ISSUE TITLE
[Libgit2] Setting certificate location fails because GIT_OPENSSL is not defined.

### ISSUE THREAD

**Issue by PlayerVMachine** [microsoft/vcpkg#14048]
When calling git_libgit2_opts() to set the SSL certificate file path this error is returned: 
`TLS backend doesn't support certificate locations`
Looking at the libgit2 source this error is printed when neither `GIT_OPENSSL` or `GIT_MBEDTLS` are defined. The solution since the vcpkg build of libgit2 requires openssl is to modify the OPTIONS in  `ports/libgit2/portfile.cmake` to include `-DGIT_OPENSSL=1`

This error message comes up on Win10, CentOS 7, and macOS.

**To Reproduce**
Steps to reproduce the behaviour:
1. ./vcpkg install libgit2
Use `git_libgit2_opts(GIT_OPT_SET_SSL_CERT_LOCATIONS, "path to cert file", NULL)` in some code and copile then run the code.

Super simple one line to add to fix this issue.

**Comment by JackBoosY** [comment]
Becuase we disabled the openssl feature on Windows.

**Comment by PlayerVMachine** [comment]
Ah I see, then it's not a one-liner fix. So is that something that should be added as a [option] or handled automatically depending on the platform's TLS backend?

**Comment by PlayerVMachine** [comment]
A colleague pointed out that on macOS libgit2 is also using SecureTransport and not OpenSSL which I had forgotten so likely this option only needs to be set on Linux targets.
