### ISSUE TITLE
[libflac] build failure

### ISSUE THREAD

**Issue by cbergemann** [microsoft/vcpkg#14044]
**Host Environment**
- OS: Windows 10
- Compiler: VS2019

**To Reproduce**
`./vcpkg install libflac`

**Failure logs** 
.\vcpkg.exe install libflac
Computing installation plan...
The following packages will be built and installed:
    libflac[core]:x86-windows
Detecting compiler hash for triplet x86-windows...
Starting package 1/1: libflac:x86-windows
Building package libflac[core]:x86-windows...
Could not locate cached archive: C:\Users\cbe\AppData\Local\vcpkg\archives\09\090658f2a269f3d0a3bd02a5bff0f0b3f2e3437e.zip
-- Using cached C:/Devel/vcpkg/vcpkg/downloads/xiph-flac-ce6dd6b5732e319ef60716d9cc9af6a836a4011a.tar.gz
-- Cleaning sources at C:/Devel/vcpkg/vcpkg/buildtrees/libflac/src/a836a4011a-c7a3381410.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Devel/vcpkg/vcpkg/downloads/xiph-flac-ce6dd6b5732e319ef60716d9cc9af6a836a4011a.tar.gz
-- Applying patch C:/Devel/vcpkg/vcpkg/ports/libflac/uwp-library-console.patch
-- Applying patch C:/Devel/vcpkg/vcpkg/ports/libflac/uwp-createfile2.patch
-- Using source at C:/Devel/vcpkg/vcpkg/buildtrees/libflac/src/a836a4011a-c7a3381410.clean
-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:141 (message):
    Command failed: C:/Devel/vcpkg/vcpkg/downloads/tools/cmake-3.17.2-windows/cmake-3.17.2-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v -j21
    Working Directory: C:/Devel/vcpkg/vcpkg/buildtrees/libflac/x86-windows-dbg
    See logs for more information:
      C:\Devel\vcpkg\vcpkg\buildtrees\libflac\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:92 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/libflac/portfile.cmake:37 (vcpkg_install_cmake)
  scripts/ports.cmake:79 (include)

Error: Building package libflac:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libflac:x86-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.

**Additional context**
Latest portfiles have been used.

**Comment by methot-ilya-3ds** [comment]
I am also having this issue

**Comment by NancyLi1013** [comment]
Hi @cbergemann and @methot-ilya-3ds 
Thanks for posting this issue.
Could you please help provide the log from _C:\Devel\vcpkg\vcpkg\buildtrees\libflac\install-x86-windows-dbg-out.log_?

I cannot reproduce this on my local machine with Visual Studio 2017 and Visual Studio 2019.

```
PS F:\new\vcpkg> .\vcpkg.exe install libflac
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
Computing installation plan...
The following packages will be built and installed:
    libflac[core]:x86-windows
Detecting compiler hash for triplet x86-windows...
Starting package 1/1: libflac:x86-windows
Building package libflac[core]:x86-windows...
Could not locate cached archive: C:\Users\AppData\Local\vcpkg\archives\1a\1a0e46ad3ab4cedee50eaa19ed37589de0d04617.zip
-- Using cached F:/new/vcpkg/downloads/xiph-flac-ce6dd6b5732e319ef60716d9cc9af6a836a4011a.tar.gz
-- Cleaning sources at F:/new/vcpkg/buildtrees/libflac/src/a836a4011a-c7a3381410.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source F:/new/vcpkg/downloads/xiph-flac-ce6dd6b5732e319ef60716d9cc9af6a836a4011a.tar.gz
-- Applying patch F:/new/vcpkg/ports/libflac/uwp-library-console.patch
-- Applying patch F:/new/vcpkg/ports/libflac/uwp-createfile2.patch
-- Using source at F:/new/vcpkg/buildtrees/libflac/src/a836a4011a-c7a3381410.clean
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Installing: F:/new/vcpkg/packages/libflac_x86-windows/share/libflac/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\AppData\Local\vcpkg\archives\1a\1a0e46ad3ab4cedee50eaa19ed37589de0d04617.zip
Building package libflac[core]:x86-windows... done
Installing package libflac[core]:x86-windows...
Installing package libflac[core]:x86-windows... done
Elapsed time for package libflac:x86-windows: 2.426 min

Total elapsed time: 2.563 min

The package libflac:x86-windows provides CMake targets:

    find_package(flac CONFIG REQUIRED)
    target_link_libraries(main PRIVATE FLAC::FLAC FLAC::FLAC++)
```

**Comment by cbergemann** [comment]
[install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/5385605/install-x86-windows-dbg-out.log)

Here is the requested log.

**Comment by NancyLi1013** [comment]
```
[21/60] C:\PROGRA~1\NASM\nasm.exe -IC:\Devel\vcpkg\vcpkg\buildtrees\libflac\src\a836a4011a-c7a3381410.clean\include -I. -dOBJ_FORMAT_win32   /wd4267 /wd4996 -IC:/Devel/vcpkg/vcpkg/buildtrees/libflac/src/a836a4011a-c7a3381410.clean/src/libFLAC/ia32/ -f win32 -o src\libFLAC\ia32\CMakeFiles\FLAC-asm.dir\lpc_asm.nasm.obj C:\Devel\vcpkg\vcpkg\buildtrees\libflac\src\a836a4011a-c7a3381410.clean\src\libFLAC\ia32\lpc_asm.nasm
FAILED: src/libFLAC/ia32/CMakeFiles/FLAC-asm.dir/lpc_asm.nasm.obj 
C:\PROGRA~1\NASM\nasm.exe -IC:\Devel\vcpkg\vcpkg\buildtrees\libflac\src\a836a4011a-c7a3381410.clean\include -I. -dOBJ_FORMAT_win32   /wd4267 /wd4996 -IC:/Devel/vcpkg/vcpkg/buildtrees/libflac/src/a836a4011a-c7a3381410.clean/src/libFLAC/ia32/ -f win32 -o src\libFLAC\ia32\CMakeFiles\FLAC-asm.dir\lpc_asm.nasm.obj C:\Devel\vcpkg\vcpkg\buildtrees\libflac\src\a836a4011a-c7a3381410.clean\src\libFLAC\ia32\lpc_asm.nasm
/wd4267: fatal: more than one input file specified: /wd4996
```
Why do you use `nasm.exe ` instead of `cl.exe to` build here? I cannot find anything about `nasm `in my build log.

**Comment by cbergemann** [comment]
I think nasm is required for the x86 build of libflac, there are some assembly portions used for that. Installing the x64 version with vcpkg install libflac:x64-windows seems to work correctly.

**Comment by NancyLi1013** [comment]
Hi @cbergemann 

Could you please try to update this in CMakeLists.txt to rebuild `libflac`?

diff --git a/CMakeLists.txt b/CMakeLists.txt

```
if(CMAKE_SYSTEM_PROCESSOR STREQUAL "i686" AND HAVE_STACKREALIGN_FLAG)
-    add_compile_options(-mstackrealign)
+    add_compile_options(
+    $<$<OR:$<COMPILE_LANGUAGE:C>,$<COMPILE_LANGUAGE:CXX>>:-mstackrealign>
+    )
 endif()
```
The reference from https://github.com/conan-io/conan-center-index/pull/1840

**Comment by cbergemann** [comment]
I don't think this option is the problem, the problem is with the /wd* parameters. Changing 

```
add_compile_options(
    $<$<BOOL:${MSVC}>:/wd4267>
    $<$<BOOL:${MSVC}>:/wd4996>
    $<$<BOOL:${ENABLE_WERROR}>:-Werror>
    $<$<AND:$<COMPILE_LANGUAGE:CXX>,$<BOOL:${HAVE_WEFFCXX_FLAG}>>:-Weffc++>
    $<$<AND:$<COMPILE_LANGUAGE:C>,$<BOOL:${HAVE_DECL_AFTER_STMT_FLAG}>>:-Wdeclaration-after-statement>)

```
to 

```
add_compile_options(
    $<$<BOOL:${ENABLE_WERROR}>:-Werror>
    $<$<AND:$<COMPILE_LANGUAGE:CXX>,$<BOOL:${HAVE_WEFFCXX_FLAG}>>:-Weffc++>
    $<$<AND:$<COMPILE_LANGUAGE:C>,$<BOOL:${HAVE_DECL_AFTER_STMT_FLAG}>>:-Wdeclaration-after-statement>)

```

lets the compilation succeed for x86-windows. However, I do not understand how this could compile in the first place.

**Comment by NancyLi1013** [comment]
Hi @cbergemann 
Without these two options, does it build successfully on your machine?

**Comment by cbergemann** [comment]
> 
> 
> Hi @cbergemann
> Without these two options, does it build successfully on your machine?

Yes, with those disabled, it now builds correctly.

**Comment by NancyLi1013** [comment]
Thanks for your feedback. I will try to fix this issue later.

**Comment by cbergemann** [comment]
The pull request does not help, see my comment here: https://github.com/microsoft/vcpkg/pull/14230#issuecomment-716875552
