### ISSUE TITLE
graphviz

### ISSUE THREAD

**Issue by ljr1981** [microsoft/vcpkg#14043]
Library name: graphviz

Library description: working with directed and undirected graphs

Source repository URL: https://graphviz.org/

Project homepage (if different from the source repository): https://graphviz.org/

Anything else that is useful to know when adding (such as optional features the library may have that should be included): The library already has Visual Studio project files, so it is ready to go for Windows!

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
