### ISSUE TITLE
Build failed - protobuf

### ISSUE THREAD

**Issue by jjaloszy2** [microsoft/vcpkg#14047]
This occurred while attempting to install GRPC for the x64-windows triplet.  It was a fresh vcpkg checkout from today, built with the Visual Studio 2019 compiler.  A message appeared suggesting I submit an issue here.

  Package: protobuf:x64-windows
  Vcpkg version: 2020.06.15-nohash

Here's what looks like the relevant portion from the log:

-- CHECK_LIB_protobuf-lite_RELEASE:CHECK_LIB_protobuf-lite_RELEASE-NOTFOUND
CMake Error at scripts/cmake/vcpkg_fixup_pkgconfig.cmake:232 (message):
  Library "protobuf-lite" was not found! If it is a system library use the
  SYSTEM_LIBRARIES parameter for the vcpkg_fixup_pkgconfig call! Otherwise,
  correct the *.pc file
Call Stack (most recent call first):
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:297 (vcpkg_fixup_pkgconfig_check_files)
  ports/protobuf/portfile.cmake:139 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:79 (include)

Thank you for maintaining this project.

**Comment by sfhacker** [comment]
Are we **STILL** having issues building this port? There are several reported issues about protobuf.
I thought it was already fixed!

**Comment by PhoebeHui** [comment]
@jjaloszy2, does the vcpkg path with a space, if so, please create a clone without space in vcpkg path, it looks same issue with #13103, and would fix by PR #13126.

**Comment by jjaloszy2** [comment]
@PhoebeHui the path contained a space, as you suspected.  After cloning vcpkg in a path without a space, installing grpc worked fine.   Since this issue is a duplicate, I'm closing it.  Thank you!
