### ISSUE TITLE
Spurious dependency on utf8cpp imported target in assimp CMake imported target 

### ISSUE THREAD

**Issue by traversaro** [microsoft/vcpkg#14045]
**Describe the bug**
Since https://github.com/microsoft/vcpkg/pull/13521, the assimp CMake config file contain a transitive dependency to the `utf8cpp` imported target 

**Environment**
- OS: Windows
- Compiler: Not relevant

**To Reproduce**
1. ./vcpkg install assimp
2. Inspect the assimp cmake config file, you will see:
~~~
# Create imported target assimp::assimp
add_library(assimp::assimp SHARED IMPORTED)

set_target_properties(assimp::assimp PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "utf8cpp;polyclipping::polyclipping;Irrlicht;minizip::minizip;ZLIB::ZLIB;kubazip::kubazip;poly2tri::poly2tri"
)
~~~
but no `find_dependency(utf8cpp CONFIG)` at the top:
~~~
include(CMakeFindDependencyMacro)
find_dependency(ZLIB)
find_dependency(irrlicht CONFIG)
find_dependency(polyclipping CONFIG)
find_dependency(minizip CONFIG)
find_dependency(kubazip CONFIG)
find_dependency(poly2tri CONFIG)
# Generated by CMake
~~~

However, at a first inspection it seems that `utf8cpp` is header only and not used in the public headers, so it should simply not be a public link of the `assimp::assimp` target. 

**Expected behavior**
All the imported targets linked by assimp target should be properly found in the CMake config file with a `find_dependency` call.

**Failure logs** 
-(please attached failure logs)

**Additional context**
See https://github.com/ignitionrobotics/ign-physics/issues/87#issuecomment-708549196 .

**Comment by traversaro** [comment]
fyi @JackBoosY

**Comment by JackBoosY** [comment]
@traversaro Yep, I missed `find_dependency`. And the utf8cpp is a header only library.
