### ISSUE TITLE
Use preview versions of Visual Studio before older ones.

### ISSUE THREAD

**Issue by Link1J** [microsoft/vcpkg#14053]
****

**Is your feature request related to a problem? Please describe.**
I have two versions of Visual Studio installed, 2019 Preview and 2017 Build Tools. When run `vcpkg install` it was picking Visual Studio 2017, even from a Visual Studio 2019 Powershell prompt.

**Proposed solution**
Have vcpkg pick Visual Studio 2019 Preview before Visual Studio 2017

**Describe alternatives you've considered**
If picking preview versions of Visual Studio by default is not an option, then a flag like `--use-previews` for install would also work.

**Comment by LilyWangL** [comment]
You can add `SET(VCPKG_PLATFORM_TOOLSET v142)` to _[VCPKG_path]/triplets/your_triplet.cmake_, it will use Visual Studio 2019.
