### ISSUE TITLE
[libzippp] Fix conditional check for WIN32 in portfile for vcpkg_fixup_cmake_targets

### ISSUE THREAD

**Issue by tusharb86** [microsoft/vcpkg#14057]
****

**Is your feature request related to a problem? Please describe.**
When building libzippp for Android on my Windows host, I get the following error because of the conditional on [line 21 of libzippp's portfile](https://github.com/microsoft/vcpkg/blob/master/ports/libzippp/portfile.cmake#L21):
```
CMake Error at scripts/cmake/vcpkg_fixup_cmake_targets.cmake:72 (message):
  'C:/a/4/s/__vcpkg/packages/libzippp_arm-android/debug/cmake/libzippp' does
  not exist.
Call Stack (most recent call first):
  ports/libzippp/portfile.cmake:22 (vcpkg_fixup_cmake_targets)
  scripts/ports.cmake:79 (include)

[DEBUG] cmd_execute_and_stream_data() returned 1 after  5080881 us
Error: Building package libzippp:arm-android failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libzippp:arm-android
  Vcpkg version: 2020.06.15-nohash
```

**Proposed solution**
Instead of checking `if(WIN32)`, the portfile should be checking `if(VCPKG_TARGET_IS_WINDOWS)`. Alternatively, it could check for existence of the folders/files in question to be more robust to future changes.

**Comment by NancyLi1013** [comment]
Hi @tusharb86 
Thanks for posting this issue.

I will fix this later.
