### ISSUE TITLE
[proj4] Rename to proj

### ISSUE THREAD

**Issue by oswjk** [microsoft/vcpkg#14062]
****

**Is your feature request related to a problem? Please describe.**
PROJ4 is the legacy name of the PROJ library. The name PROJ is now preferred. More can be read from https://proj.org/faq.html#what-happened-to-proj-4.

**Proposed solution**
After https://github.com/microsoft/vcpkg/issues/12449 is fixed (by merging https://github.com/microsoft/vcpkg/pull/13428), rename the proj4 port to proj.

**Describe alternatives you've considered**
An alternative is to keep calling the port proj4. In my opinion this is not acceptable. What we could do, is to provide an empty port called proj4 that would depend on proj and maybe output a warning message about the name.

**Additional context**
PROJ installs CMake config files and targets with both names (proj and proj4), see here https://github.com/OSGeo/PROJ/blob/master/cmake/CMakeLists.txt

**Comment by JackBoosY** [comment]
Generally, we use the version-free name of the library to define the port common name (such as `opencv`), not this.

**Comment by JackBoosY** [comment]
If you have other question, please ping me.
