### ISSUE TITLE
[New Port Request] serf

### ISSUE THREAD

**Issue by jelmer** [microsoft/vcpkg#14069]
Library name: Apache Serf

Library description: The serf library is a high performance C-based HTTP client library built upon the Apache Portable Runtime (APR) library.

Source repository URL: https://serf.apache.org/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

This is a dependency for Subversion and the Subversion libraries.

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now
