### ISSUE TITLE
[New Port Request] net-snmp

### ISSUE THREAD

**Issue by petesew** [microsoft/vcpkg#14068]
Library name: net-snmp

Library description: An SNMP application library, tools and daemon

Source repository URL: https://sourceforge.net/projects/net-snmp/ and https://github.com/net-snmp/net-snmp

Project home page: http://www.net-snmp.org

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now

**Comment by blackimon** [comment]
Is there any chance that this request could be reopened? -Would be nice if this would be available via vcpkg.

**Comment by petesew** [comment]
For reference: https://github.com/microsoft/vcpkg/issues/2575
