### ISSUE TITLE
[New Port Request] Sleepy Discord

### ISSUE THREAD

**Issue by Spejik** [microsoft/vcpkg#14065]
Library name: Sleepy Discord

Library description: C++ library for creating Discord Bots

Source repository URL: https://github.com/yourWaifu/sleepy-discord

Project homepage (if different from the source repository): https://yourwaifu.dev/sleepy-discord/

Anything else that is useful to know when adding (such as optional features the library may have that should be included): The library requires OpenSSL, cpr and Websocket++ to be installed

**Comment by DhairyaBahl** [comment]
@PhoebeHui I would like to work on this issue. Kindly assign it to me. 

Thanks :)

**Comment by PhoebeHui** [comment]
@DhairyaBahl, thank you for your contribution in advance!

**Comment by DhairyaBahl** [comment]
@PhoebeHui It's my first PR with Microsoft.. but I will try my best :)

Thanks :)

**Comment by DhairyaBahl** [comment]
@PhoebeHui @Spejik I have cloned this repository in my local machine and I've also cloned the sleepy-discord inside the vcpkg directory. I am a bit confused about those library names OpenSSL CPR WebSocket++ and what exactly I have to do next. Kindly guide me a bit.

Thanks for cooperation :)

**Comment by Spejik** [comment]
@DhairyaBahl The 3 libraries are [here](https://github.com/yourWaifu/sleepy-discord/blob/master/README.md#requirements)
WebSocket++ is for communicating with Discord's realtime API.
Cpr is just curl, but easier to use.
OpenSSL is for TLS/SSL encryption, so it allows cpr and WebSocket++ to use https and wss.
Sleepy Discord uses them internally, so they should be installed upon installing the package sleepy-discord.

Also, in the Sleepy Discord's [CMakeLists.txt](https://github.com/yourWaifu/sleepy-discord/blob/master/CMakeLists.txt) there are some packages the library installs before the first build.

Thanks for your contribution!

**Comment by Knightly1** [comment]
These may not be correct, but I began working on this a bit ago and didn't finish.  In case it helps, the control file that I created is:
```
Source: sleepy-discord
Version: 2020-07-05
Homepage: https://yourwaifu.dev/sleepy-discord/documentation.html
Description: C++ library for Discord
Build-Depends: cpr

Feature: websocketpp
Description: Use websocketpp for sleepy-discord
Build-Depends: openssl-windows, asio, websocketpp

Feature: uwebsockets
Description: Use uwebsockets for sleepy-discord
Build-Depends: openssl-windows, zlib, asio, uwebsockets

Feature: voice
Description: Enable voice functionality for sleepy-discord
Build-Depends: libopusenc, libsodium
```

This is the portfile I began, but note that I also have modifications to the cmakelists file in sleepy-discord that are not in this:
```
include(vcpkg_common_functions)

if ("websocketpp" IN_LIST FEATURES)
    set(USE_WEBSOCKETPP ON)
elseif("uwebsockets" IN_LIST FEATURES)
    set(USE_WEBSOCKETPP OFF)
    set(USE_UWEBSOCKETS ON)
endif()

if ("voice" IN_LIST FEATURES)
    set(USE_LIBOPUS ON)
    set(USE_LISODIUM ON)
endif()
```

Just in case that helps with where you are.

**Comment by luizfernandonb** [comment]
> @PhoebeHui I would like to work on this issue. Kindly assign it to me.
> 
> Thanks :)

do you have a forecast for when this library will be available in vcpkg?

**Comment by Knightly1** [comment]
These aren't great, but they're what I'm using right now for vcpkg in case it helps anyone else.  Note that the cmake file changes are really based around windows and would need to be cleaned up to be universal.  Also, the versioning system assumes that you don't have git, while the sleepy-discord versioning does include git, so that would probably need some reworking.  But this is also probably a good start for anyone wanting to do a vcpkg for sleepy-discord (and it does work).

CONTROL:  https://gist.github.com/Knightly1/baf6a00e130c5ed4b828e73e9aece63e

portfile.cmake:  https://gist.github.com/Knightly1/bef5b58054e14074335c21074664eba2

Patch 1:  https://gist.github.com/Knightly1/f8867db7d433f90979718dcdbcee4966

Patch 2:  https://gist.github.com/Knightly1/f1dfb5266c6d8a459bbe50c1fc618179

**Comment by NancyLi1013** [comment]
Hi all,

`sleep-discord` has been added to vcpkg now, please update to the latest vcpkg to use this port.
