### ISSUE TITLE
VS2019 fails to recognise vcpkg packages

### ISSUE THREAD

**Issue by Trider12** [microsoft/vcpkg#14075]
**Describe the bug**

I've installed several packages with the `x64-windows-static` triplet and can't include them into a VS2019 project.
Tried to do the following:
- Updated VS to the latest version and restarted windows
- Pulled the latest vcpkg
- Ran the bootstrap file
- `vcpkg update`, `vcpkg integrate remove`, `vcpkg integrate install` in an elevated powershell
- Created a completely new project in VS
- Overrode the default triplet in the `.vcxproj` file to `x64-windows-static` and switched the active project platform to `x64`
- Checked that i do indeed have the necessary files in the `vcpkgRoot\x64-windows-static\include` folder 

Still both build and IntelliSense failed to include the headers.

I then checked an old project which used `x64-windows` and had worked fine before and it also fails to include headers now.
Can't think of any recent changes that could have such an effect.

**Environment**
- OS: Windows 10
- Compiler: VS2019 16.7.6

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Did you run command `vcpkg integrate project` on VCPKG? And could you please provide a simple repro project?

**Comment by Trider12** [comment]
@LilyWangL, I've tried `vcpkg integrate project`, but it's still no use. Here is a repro [project](https://github.com/microsoft/vcpkg/files/5391571/Test.zip).

**Comment by alek-d** [comment]
@Trider12 Did you set "Use static libraries" to "yes" in "Configuration Properties/vcpkg"?

**Comment by Trider12** [comment]
@alek-d, I see no vcpkg settings in `Configuration Properties`.

**Comment by LilyWangL** [comment]
Sorry I am late. I open your project with Visual Studio 2019 16.7.6, and I can't found the error about include header file.
![image](https://user-images.githubusercontent.com/47812810/97285287-fb88f400-187c-11eb-848e-7f7303ca677f.png)

**Comment by NancyLi1013** [comment]
Hi @alek-d 

Please help check if you have set `x64-windows-static` in your project. 

```
 <PropertyGroup Label="Globals">
 <!-- .... -->
 <VcpkgTriplet Condition="'$(Platform)'=='x64'">x64-windows-static</VcpkgTriplet>
</PropertyGroup>
```

 See doc https://devblogs.microsoft.com/cppblog/vcpkg-updates-static-linking-is-now-available/

Feel free to reopen this issue if it is still a problem for you.
