### ISSUE TITLE
[libpq:x64-uwp] build failure

### ISSUE THREAD

**Issue by skealy** [microsoft/vcpkg#14072]
**Host Environment**
- OS: Windows 10
- Compiler: see output.text file attached

**To Reproduce**
I installed a fresh vcpkg at C:\src
ran .\bootstrap-vcpkg.bat
ran .\vcpkg integrate install

I then ran .\vcpkg install libpq:x64-windows. This installed correctly see output.txt

I then ran .\vcpkg install libpq:x64-uwp. This installation failed with the error reported in #12443 re openssl command not found.

I checked the content of C:\src\vcpkg\installed\x64-windows and found 7 folders bin, debug, include, lib, misc, share, tools.
The directory at C:\src\vcpkg\installed\x64-uwp contains only 5 folders (misc and tools are missing). I copied these directories from x64-windows and ran the install again. This also failed and produced a different error messages - see output.txt. The error logs were produced with no content. I attact the out and error logs for reference.
C++/WinRT projects can not use the x64-windows version and I believe require the x64:uwp version. I have tested installs of sqligh3 for x64-windows and x64-uwp and both installed correctly. 
[output.txt](https://github.com/microsoft/vcpkg/files/5386255/output.txt)

[build-libecpg_compat-x64-uwp-DEBUG-out.log](https://github.com/microsoft/vcpkg/files/5386265/build-libecpg_compat-x64-uwp-DEBUG-out.log)
[build-libecpg_compat-x64-uwp-RELEASE-out.log](https://github.com/microsoft/vcpkg/files/5386267/build-libecpg_compat-x64-uwp-RELEASE-out.log)
[build-libpq-x64-uwp-DEBUG-out.log](https://github.com/microsoft/vcpkg/files/5386272/build-libpq-x64-uwp-DEBUG-out.log)
[build-libpq-x64-uwp-RELEASE-out.log](https://github.com/microsoft/vcpkg/files/5386275/build-libpq-x64-uwp-RELEASE-out.log)

Note error log files exist but cannot be attached as they are empty.

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by skealy** [comment]
In the absence of any suggestions I have conducted further research and set out my findings. Hopefully somebody may be able to provide a final resolution. These are the steps I followed:
1 download a fresh version of vcpkg from github to c:\vcpkg and bootstrap the install.
2 run .\vcpkg install libpw:x64-uwp. The screen output is in output1.txt attached together with the log files.
[output1.txt](https://github.com/microsoft/vcpkg/files/5433221/output1.txt)
[build-libpq-x64-uwp-RELEASE-out.log](https://github.com/microsoft/vcpkg/files/5433224/build-libpq-x64-uwp-RELEASE-out.log)
[build-libpq-x64-uwp-RELEASE-err.log](https://github.com/microsoft/vcpkg/files/5433225/build-libpq-x64-uwp-RELEASE-err.log)

3 Line 81 of output.txt contails the following information:
Command failed: C:/vcpkg/downloads/tools/perl/5.30.0.1/perl/bin/perl.exe build.pl RELEASE libpq
    Working Directory: C:/vcpkg/buildtrees/libpq/x64-uwp-rel/src/tools/msvc
In the working directory I executed the command perl build.pl RELEASE libpq. This reports the same error as in the log file 
"Unable to determine OpenSSL version: The openssl.exe command wasn't found. at C:\vcpkg\buildtrees\libpq\x64-uwp-rel\src\tools\msvc/Mkvcbuild.pm line 147."
I then changed the environment path to include the path to openssh.exe which is "C:\vcpkg\downloads\tools\perl\5.30.0.1\c\bin" and ran the command perl build.pl RELEASE libpq again.
The command succedded see output2.txt. 
[output2.txt](https://github.com/microsoft/vcpkg/files/5433263/output2.txt)
Unfortunately this does not solve the problem as when .\vcpkg install libpq:x64-uwp is run it creates its own environment path settings and the same error occurs.
I looked further into where the environment path is set and found the patch file openssl_exe_path.patch which is run during the install process (see line 53 of output.txt).
This patches the file Solution.pm at lines 133 to 140 and changes the original 'my $opensslcmd = qq("openssl.exe" version 2>&1'
to 
'my $opensslcmd = "$self->{options}->{openssl}\\bin\\openssl.exe version 2>&1'
For this to be correct $self->{options}->{openssl}\\bin\\openssl.exe' should translate to C:\vcpkg\downloads\tools\perl\5.30.0.1\c\bin\openssl.exe  but does not!!!!
For the record openssl_exe_path.patch is located at C:\vcpkg\ports\libpq\patches 
and
Solution.pm is located at C:\buildtrees\libpq\x64-uwp-rel\scr\tools

I dont have sufficient knowledge of .pm files to know how to amend the patch file perhaps someone can help with this.

Presumable when this is fixed a similar problem will arise when the debug section is being processed.

**Comment by skealy** [comment]
libpq further information on uwp install.

**Comment by sfhacker** [comment]
Are we **STILL** having difficulties building libpq?

**Comment by skealy** [comment]
JohnThere is still a problem with libpq  when installing for uwp. I have found a workaround but it involves changing the code in the c++ file postbuildint.cpp. As I have concerns about the legality of this I did not publish on github. Here is a summary of  the issue.If a library is required for use with C++/WinRT it must be built with the uwp version. When vcpkg install libpq:x64-uwp is run it fails with the message "unable to find openssl.exe...".This problem can be overcome by modifying the perl script file VCPKG_ROOT/ports/libpq/profile.cmake at line 162 by substituting CURRENT_INSTALLED_DIR)/../../downloads/tools/perl/5.30.0.1/c/bin for the existing code. This enables the process to find the openssl.exe file and the install process then continues to the final stage of validating the install files. This process is handled by postbuildint.cpp.  it produces an error at line 443 to 449 as it finds that the libpq dll files do not have the App Container bit set. This appears to be a requirement of uwp applications which must satisfy the app store criteria unlike windows apps. If lines 423 to 448 are excluded and vcpkg is boot strapped again then vcpkg install libpq:x64-uwp will complete satisfactorily and the resulting headers can be used by C++/WinRT apps.Clearly this not satisfactory and I am not sure about its legality. Can you inform me where and when the App Container bit should be set? Is this part of the vcpkg process or elsewhere? I am new to windows development having come from a QT background and I am considering porting some apps to C++/WinRT as it is the only truly modern c++ environment available under windows. The difficulties being presented by the App store restrictions are not encouraging. I would appreciate a clear direction from Microsoft as to why such restrictions on the use of 3rd party libraries in uwp app are deemed  necessary. I should also mention that building the libraries on Visual Studio does not work for uwp apps as they can not be used unless built by vcpkg. I presume this is again to ensure compliance with the App store requirements.Notwithstanding my workaround I do not intend to proceed with development on C++/WinRT until I have a satisfactory response to my concerns.Regards.Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: John Sheppard <notifications@github.com> Date: 24/10/2020  22:44  (GMT+00:00) To: microsoft/vcpkg <vcpkg@noreply.github.com> Cc: Sean Kealy <skealy@cruiscin.eu>, State change <state_change@noreply.github.com> Subject: Re: [microsoft/vcpkg] [libpq:x64-uwp] build failure (#14072) 
Are we STILL having difficulties building libpq?

**Comment by JackBoosY** [comment]
Please wait me to fix this issue.

**Comment by JackBoosY** [comment]
```
-- Performing post-build validation
The following DLLs do not have the App Container bit set:

    F:/vcpkg/packages/libpq_x64-uwp/debug/bin/libecpg.dll
    F:/vcpkg/packages/libpq_x64-uwp/debug/bin/libecpg_compat.dll
    F:/vcpkg/packages/libpq_x64-uwp/debug/bin/libpgtypes.dll
    F:/vcpkg/packages/libpq_x64-uwp/debug/bin/libpq.dll
    F:/vcpkg/packages/libpq_x64-uwp/bin/libecpg.dll
    F:/vcpkg/packages/libpq_x64-uwp/bin/libecpg_compat.dll
    F:/vcpkg/packages/libpq_x64-uwp/bin/libpgtypes.dll
    F:/vcpkg/packages/libpq_x64-uwp/bin/libpq.dll

This bit is required for Windows Store apps.
Found 1 error(s). Please correct the portfile:
    F:\vcpkg\ports\libpq\portfile.cmake
-- Performing post-build validation done
Error: Building package libpq:x64-uwp failed with: POST_BUILD_CHECKS_FAILED
```
I think we should wait for upstream to support uwp.

**Comment by m-kuhn** [comment]
Is there any upstream issue to track?

**Comment by JackBoosY** [comment]
@m-kuhn  Nope, can you please report it to the upstream?

Thanks.

**Comment by sfhacker** [comment]
This issue is six months old!
libpq works just fine on our environment (Windows 10 x64).

**Comment by m-kuhn** [comment]
@sfhacker as uwp build?

@JackBoosY I am not as familiar with the ossue as others in here seem to be, but I can jump in if there's no one available.

**Comment by m-kuhn** [comment]
```
    "dev\vcpkg\buildtrees\detect_compiler\x64-uwp-rel\CMakeFiles\3.20.2\VCTargetsPath.vcxproj" (default target) (1) ->
    (_CheckForInvalidConfigurationAndPlatform target) ->
      C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(816,5): error : The BaseOutputPath/OutputPath property is not set for project 'VCTargetsPath.vcxproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='x64'.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [dev\vcpkg\buildtrees\detect_compiler\x64-uwp-rel\CMakeFiles\3.20.2\VCTargetsPath.vcxproj]

        0 Warning(s)
        1 Error(s)

    Time Elapsed 00:00:00.11


  Exit code: 1
```

It seems this fails considerably earlier here (not sure this is an upstream issue). Building for `x64-windows` succeeds just fine.

**Comment by JackBoosY** [comment]
@m-kuhn The real problem is that the App Container bit set is not set in the upstream of libpq, and we need to wait for the upstream to fix this.

**Comment by m-kuhn** [comment]
@JackBoosY sorry for my poor knowledge here, is this bit not set on the resulting dlls (I think this could be an interpretation from [your earlier comment](https://github.com/microsoft/vcpkg/issues/14072#issuecomment-716365360) but I'm not sure if those dlls are the results of an uwp build of libpq in vcpkg) or on some sources?

For me [it fails already in the configuration step](https://github.com/microsoft/vcpkg/issues/14072#issuecomment-832679729), is this also an upstream issue worth escalating?

I can do a report but I'll need at least a basic understanding of what should be reported.

**Comment by JackBoosY** [comment]
@m-kuhn Sorry for late, see document: https://docs.microsoft.com/en-us/cpp/build/reference/appcontainer-windows-store-app?view=msvc-160.

**Comment by JackBoosY** [comment]
Close this PR until upstream fixes this.

**Comment by m-kuhn** [comment]
@JackBoosY this is an issue, not a PR. Shouldn't this be kept open and an upstream issue filed in parallel?

**Comment by JackBoosY** [comment]
@m-kuhn Sorry, typo.
Since there has no progress for a long time, can you please make a upstream issue?

Thanks.

**Comment by m-kuhn** [comment]
@JackBoosY I am really not a UWP expert, I don't feel confident to open this. At least not without a template drafted by someone else.

This was more an interpretation of this warning I often see when building for community triplets. Mostly for mobile targets like Android and iOS where I try to improve the situation and contribute with community efforts.

> warning: -- Using community triplet [xxx]. This triplet configuration is not guaranteed to succeed.

which suggests that the inverse - non community triplets like `x64-uwp` - comes with some sort of guarantee.
I totally understand that this "guarantee" is stretching the scope of vcpkg and can only be interpreted with a good grain of salt. And that libpq specifically states that the triplet `x64-upw` is not supported.
Still, closing this issue just like that seems to be completely ignoring the claimed "guarantee".

**Comment by JackBoosY** [comment]
@m-kuhn The warning is just for community triplet, not for libpq's uwp support.
The fact is the libpq official doesn't support uwp, so we need to wait the upstream add uwp support first.
