### ISSUE TITLE
[New Port Request] XML-RPC for C/C++

### ISSUE THREAD

**Issue by haofeiyan** [microsoft/vcpkg#14073]
Library name:
XML-RPC for C/C++
Library description:
XML-RPC for C/C++ (Xmlrpc-c) is developed and distributed by a Sourceforge project.
Source repository URL:
http://xmlrpc-c.sourceforge.net/
Project homepage (if different from the source repository):
http://xmlrpc-c.sourceforge.net/
Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by test-suiteneglected** [comment]
@PhoebeHui https://patrick-particle16.github.io/8qnFYLjdgRTX1bgBHIt_jGCRQIKTSz8kEtMv-ifywXKmCgdplpTwbCr9ug/
