### ISSUE TITLE
error processing file vcpkg.cmake 

### ISSUE THREAD

**Issue by x0rld** [microsoft/vcpkg#14077]
**Describe the bug**
when I run the command to process cmake
` cmake -DCMAKE_BUILD_TYPE=Debug -CMAKE_TOOLCHAIN_FILE=$HOME/vcpkg/scripts/buildsystems/vcpkg.cmake ../`
```
loading initial cache file MAKE_TOOLCHAIN_FILE=/home/x0rld/vcpkg/scripts/buildsystems/vcpkg.cmake
CMake Error: Error processing file: /home/x0rld/CLionProjects/untitled4/cmake-build-debug/MAKE_TOOLCHAIN_FILE=/home/x0rld/vcpkg/scripts/buildsystems/vcpkg.cmake
```

**Environment**
- OS: fedora 32
- Compiler: gcc 10.2.1
- cmake version 3.17.4

**To Reproduce**
1. clone the repo and compile it
2. install a package ( I have test with sodium sdl2 and sqlite3 ) 
2. run the cmake command

```cmake
# CMakeLists.txt
cmake_minimum_required(VERSION 3.0)
project(test)

find_package(unofficial-sqlite3 CONFIG REQUIRED)

add_executable(main main.cpp)

target_link_libraries(main PRIVATE unofficial::sqlite3::sqlite3)```



// main.cpp
#include <sqlite3.h>
#include <stdio.h>

int main()
{
    printf("%s\n", sqlite3_libversion());
    return 0;
}
```
**Failure logs** 
[CMakeOutput.log](https://github.com/microsoft/vcpkg/files/5388247/CMakeOutput.log)

**Comment by PhoebeHui** [comment]
@x0rld, could you try below command and see if the error persist?

cmake -DCMAKE_BUILD_TYPE=Debug -**D**CMAKE_TOOLCHAIN_FILE=$HOME/vcpkg/scripts/buildsystems/vcpkg.cmake ../

I can't repro this issue locally.

cmake .. "-DCMAKE_TOOLCHAIN_FILE=/home/phoebe/vcpkg/scripts/buildsystems/vcpkg.cmake" -DCMAKE_BUILD_TYPE=Debug
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Configuring done
-- Generating done
-- Build files have been written to: /home/phoebe/vcpkgtest/sqlite3/build

$ make
Scanning dependencies of target main
[ 50%] Building CXX object CMakeFiles/main.dir/main.cpp.o
[100%] Linking CXX executable main
[100%] Built target main

**Comment by x0rld** [comment]
oh my bad I didn't see i forget the D thank you

**Comment by PhoebeHui** [comment]
Never mind.
