### ISSUE TITLE
windeployqt locates a release version of icudtXX.dll for a debug binary

### ISSUE THREAD

**Issue by seanlis** [microsoft/vcpkg#14081]
**Describe the bug**
windeployqt locates a release version of icudtXX.dll for a debug binary

**Environment**
- OS: Windows
- Compiler: msvc

**To Reproduce**
1. ``> cmd /c "set "path=d:\src\vcpkg\installed\x64-windows\debug\bin;%path%" && d:\src\vcpkg\installed\x64-windows\tools\qt5\debug\bin\windeployqt.exe --qmldir E:\tmp\Project1\QtQuickApplication1 E:\tmp\Project1\out\build\x64-Debug\QtQuickApplication1"``
2. `E:\tmp\Project1\out\build\x64-Debug\QtQuickApplication1\xxx.exe 64 bit, debug executable [QML]`
`Unable to locate ICU library icudt67.dll`

**Expected behavior**
windeployqt should have looked for icudtd67.dll

**Additional context**
Although qtdeploy.ps1 could deploy icudtd, it couldn't handle QML imports.

**Comment by owolff** [comment]
FYI: We fixed the issue upstream as well. The fix will also be cherry picked to Qt 5.15.
