### ISSUE TITLE
imgui  static build does not work with FindPackage

### ISSUE THREAD

**Issue by cmaughan** [microsoft/vcpkg#14096]
**Describe the bug**
On Windows:

- Use vcpkg to install imgui:
`vcpkg install imgui:x64-windows-static`

- Add toolchain to CMake:
`set(CMAKE_TOOLCHAIN_FILE ${CMAKE_CURRENT_SOURCE_DIR}/vcpkg/scripts/buildsystems/vcpkg.cmake CACHE STRING "Vcpkg toolchain file")`

- Add find_package to CMakeLists:
`find_package(imgui CONFIG REQUIRED)`

Error:
cannot find imgui-config.cmake, etc.

This does not happen for other libraries installed with vcpkg.  Omitting the -static seems to work, but this builds all of the imgui dependent libraries as dynamic, which I don't want.

**Environment**
- OS: Windows
- Compiler: 2019

**Comment by LilyWangL** [comment]
Thanks for posting this issue. If you want use imgui static library in your cmake project, you need set `VCPKG_TARGET_TRIPLET` in your project, like this **CMakeSettings.json**:
```
{
  "configurations": [
    {
      "name": "x64-Debug",
      "generator": "Visual Studio 16 2019 Win64",
      "configurationType": "Debug",
      "inheritEnvironments": [ "msvc_x64_x64" ],
      "buildRoot": "${projectDir}\\out\\build\\${name}",
      "installRoot": "${projectDir}\\out\\install\\${name}",
      "cmakeCommandArgs": "",
      "buildCommandArgs": "",
      "ctestCommandArgs": "",
      "cmakeToolchain": "E:/1009/vcpkg/scripts/buildsystems/vcpkg.cmake",
      "variables": [
        {
          "name": "VCPKG_TARGET_TRIPLET",
          "value": "x64-windows-static",
          "type": "STRING"
        }
      ]
    }
  ]
}
```

**Comment by cmaughan** [comment]
Thanks, indeed adding set(VCPKG_TARGET_TRIPLET "x64-windows-static") before the toolchain file sorted this and other libraries out.  It took quite a bit of searching to figure it out; it doesn't seem to be documented very well, but certainly was needed for several of the libraries I wanted to use.
