### ISSUE TITLE
semicolons missing from protobuf header file?!

### ISSUE THREAD

**Issue by ivannp** [Microsoft/vcpkg#1409]
installed protobuf. tried to build a project. failed with a lots of errors in port.h (a protobuf header).  Looking at the file, I see:

#ifdef _MSC_VER
typedef signed __int8  int8
typedef __int16 int16
typedef __int32 int32

Obviously ';' missing at the end of these lines.

The [GitHub version of the file](https://github.com/google/protobuf/blob/master/src/google/protobuf/stubs/port.h) does have semicolons. Any idea what's at fault?

**Comment by atkawa7** [comment]
@ivannp See [`https://github.com/Microsoft/vcpkg/blob/master/ports/protobuf/portfile.cmake#L91-L93`](https://github.com/Microsoft/vcpkg/blob/master/ports/protobuf/portfile.cmake#L91-L93)

It should be 

```
foreach(FILE ${CURRENT_PACKAGES_DIR}/include/google/protobuf/arena.h ${CURRENT_PACKAGES_DIR}/include/google/protobuf/stubs/port.h)
    file(READ ${FILE} _contents)
    if(VCPKG_LIBRARY_LINKAGE STREQUAL dynamic)
        string(REPLACE "defined(PROTOBUF_USE_DLLS)" "1" _contents "${_contents}")
    else()
        string(REPLACE "defined(PROTOBUF_USE_DLLS)" "0" _contents "${_contents}")
    endif()
    file(WRITE ${FILE} ${_contents})
endforeach()
```
With those semi colons

@ras0219-msft  It seems you forgot quotes in your last protobuf commit
