### ISSUE TITLE
[spdlog] build failure on x64-linux

### ISSUE THREAD

**Issue by VelocityRa** [microsoft/vcpkg#14099]
**Host Environment**
- OS: Linux Ubuntu x64 20.04 
- Compiler: gcc 10.2.0

**To Reproduce**
`./vcpkg install spdlog`

**Failure logs** 
![image](https://user-images.githubusercontent.com/6632271/96356610-9ce3ad80-10f9-11eb-9233-1d4d1a18232f.png)
[install-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/5396934/install-x64-linux-dbg-out.log)

**Comment by NancyLi1013** [comment]
Hi @VelocityRa 
Thanks for posting this issue.
I cannot reproduce this on my local with Ubuntu 18.04, gcc 9.2.0.

Have you installed system library `fmt `on your local? If so, could you please remove `fmt `first, then try to rebuild this?

**Comment by VelocityRa** [comment]
Hi @NancyLi1013 
`fmt` got forcefully rebuilt as expected (since the `spdlog` port depends on it)
Same issue after that.
[command.txt](https://github.com/microsoft/vcpkg/files/5400122/command.txt)
(the `dbg-out.log` is the same so I'm not posting it again.)

Perhaps you have to use my env to repro (Ubuntu 20.04 with GCC 10.2.0).

**Comment by VelocityRa** [comment]
Tried it again, building everything from scratch (clearing all of `vcpkg_installed`, its caches, etc) and it worked!
Thanks.
