### ISSUE TITLE
[vcpkg-gfortran:x64-windows] build failure

### ISSUE THREAD

**Issue by joel-koch** [microsoft/vcpkg#14097]
**Host Environment**
- OS: Windows
- Vcpkg version: 2020.06.15-nohash

**To Reproduce**
`./vcpkg install vcpkg-gfortran:x64-windows`

**Failure logs** 
Starting package 1/1: vcpkg-gfortran:x64-windows
Building package vcpkg-gfortran[core]:x64-windows...
Could not locate cached archive: path removed
-- The Fortran compiler identification is unknown
-- No Fortran compiler found on the PATH. Using MinGW gfortran!
-- Downloading https://repo.msys2.org/msys/x86_64/libiconv-1.16-1-x86_64.pkg.tar.xz...
-- Downloading https://repo.msys2.org/msys/x86_64/libiconv-1.16-1-x86_64.pkg.tar.xz... Failed. Status: 22;"HTTP response code said error"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:181 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_acquire_msys.cmake:97 (vcpkg_download_distfile)
  scripts/cmake/vcpkg_acquire_msys.cmake:277 (msys_package)
  scripts/cmake/vcpkg_find_fortran.cmake:67 (vcpkg_acquire_msys)
  ports/vcpkg-gfortran/portfile.cmake:3 (vcpkg_find_fortran)
  scripts/ports.cmake:79 (include)

**Comment by joel-koch** [comment]
Same problem as in #14094

**Comment by joel-koch** [comment]
There is no https://repo.msys2.org/msys/x86_64/libiconv-1.16-1-x86_64.pkg.tar.xz, but https://repo.msys2.org/msys/x86_64/libiconv-1.16-2-x86_64.pkg.tar.zst on the server

**Comment by JonLiu1993** [comment]
@joel-koch ,Please download the source code package from other link and put it into VCPKG_PATH/downloads then rebuild gfortran.

Thanks.

**Comment by JonLiu1993** [comment]
Looks like your system has disabled the non-ssl download.
 Please uzip and put [this](https://github.com/microsoft/vcpkg/files/5399586/libiconv-1.16.tar.gz.zip)  to VCPKG_ROOT/downloads and try again.

**Comment by JonLiu1993** [comment]
Duplicate ot #14094
