### ISSUE TITLE
[hypre] build failure on x64-windows-static

### ISSUE THREAD

**Issue by rockydut** [microsoft/vcpkg#14108]
**Host Environment**
- OS: windows
- Compiler: newest

**To Reproduce**
`./vcpkg install hypre:x64-windows-static

**Failure logs** 
Computing installation plan...
The following packages will be built and installed:
    hypre[core]:x64-windows-static
Detecting compiler hash for triplet x64-windows-static...
Starting package 1/1: hypre:x64-windows-static
Building package hypre[core]:x64-windows-static...
Could not locate cached archive: C:\Users\rocky\AppData\Local\vcpkg\archives\4a\4a54b434165d6af52de4fa42d62f6db2a8a5d39d.zip
-- Using cached F:/Packages/vcpkg/downloads/hypre-space-hypre-v2.19.0.tar.gz
-- Cleaning sources at F:/Packages/vcpkg/buildtrees/hypre/src/v2.19.0-c1141a738c.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source F:/Packages/vcpkg/downloads/hypre-space-hypre-v2.19.0.tar.gz
-- Using source at F:/Packages/vcpkg/buildtrees/hypre/src/v2.19.0-c1141a738c.clean
-- Configuring x64-windows-static
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:85 (message):
    Command failed: ninja -v
    Working Directory: F:/Packages/vcpkg/buildtrees/hypre/x64-windows-static-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      F:\Packages\vcpkg\buildtrees\hypre\config-x64-windows-static-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:312 (vcpkg_execute_required_process)
  ports/hypre/portfile.cmake:19 (vcpkg_configure_cmake)
  scripts/ports.cmake:79 (include)

Error: Building package hypre:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: hypre:x64-windows-static
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by JackBoosY** [comment]
Hi @rockydut, thanks for reporting this issue!
Please provide failure log _F:\Packages\vcpkg\buildtrees\hypre\config-x64-windows-static-out.log_.

Thanks.

**Comment by rockydut** [comment]
I know why it is failure, It can not find mpi.h file. I copy this file to the installed/include file, it just OK. Thanks.
