### ISSUE TITLE
vcpkg refuses to update due to SDL2 vcpkg.json error.

### ISSUE THREAD

**Issue by gregshasaliedown** [microsoft/vcpkg#14126]
On both Windows and Linux (Mint), I get the following error when I try _vcpkg update_:

> Error: There are invalid field types in the CONTROL or manifest file of D:\vcpkg\ports\sdl2\vcpkg.json
> The following fields had the wrong types:
> 
>     features was expected to be an array of feature definitions
> 
> Error: Failed to load port from sdl2

Reading the last git pull, it appears sdl2 has just changed from a CONTROL file to vcpkg.json.
This error also prevents me from updating all the other libraries in one go.

**Comment by StarGate-One** [comment]
Try ...
`git pull` on both Windows and Linux
Windows `.\bootstrap-vcpkg.bat`
Linux `./bootstrap-vcpkg.sh`
This will recompile the vcpkg binary taking in the changes made to the `vcpkg.json` file layout.
Run the `vcpkg update` or `vcpkg upgrade` again on each Windows and Linux.

**Comment by gregshasaliedown** [comment]
That worked. Thank you.
