### ISSUE TITLE
[libnoise] LNK2019 error with libnoise

### ISSUE THREAD

**Issue by Xobtah** [microsoft/vcpkg#14127]
**Describe the bug**
As described on StackOverflow : https://stackoverflow.com/questions/64441733/lnk2019-error-when-using-a-library-installed-with-vcpkg
`vcpkg` is integrated to Visual Studio 2019 and works fine with any other library, but libnoise doesn't work right away. I have installed the triplet `x64-windows`, and try to compile this C++ program in x64 : 
```C++
#include <noise/noise.h> // The header is found as well as the definition of noise::module::Perlin

int main()
{
   noise::module::Perlin noise; // The implementation is not found
}
```
I get this error : 
```
1>------ Build started: Project: Mayak, Configuration: Debug x64 ------
1>main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl noise::module::Perlin::Perlin(void)" (__imp_??0Perlin@module@noise@@QEAA@XZ) referenced in function main
1>NoiseVideoGenerator.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl noise::module::Perlin::Perlin(void)" (__imp_??0Perlin@module@noise@@QEAA@XZ)
1>main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: virtual __cdecl noise::module::Perlin::~Perlin(void)" (__imp_??1Perlin@module@noise@@UEAA@XZ) referenced in function main
1>NoiseVideoGenerator.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual __cdecl noise::module::Perlin::~Perlin(void)" (__imp_??1Perlin@module@noise@@UEAA@XZ)
1>C:\Users\***\source\repos\Mayak\x64\Debug\Mayak.exe : fatal error LNK1120: 2 unresolved externals
1>Done building project "Mayak.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Environment**
- OS: Windows 10
- Compiler: Visual Studio 2019's compiler

**To Reproduce**
1. ./vcpkg install libnoise:x64-windows
2. Compile an x64 project on VS2019 using the lib (the code I pasted in the bug description for example)

**Expected behavior**
The code should compile and the library works.

**Failure logs** 
Shown in the bug description.

**Additional context**
The library works when linked manually. I add "C:\vcpkg\installed\x64-windows\bin" in "Additional Library Directories" and "noise.lib" in "Additional Dependencies".
It doesn't work when I link manually this way : "C:\vcpkg\installed\x64-windows\lib" in "Additional Library Directories" and "noise-static.lib" in "Additional Dependencies".

**Comment by JackBoosY** [comment]
Confirmed.

**Comment by Xobtah** [comment]
I see your changes have been approved. Once merged, do I need to update the vcpkg repository and update the lib ?

> $ cd %VCPKG_ROOT% && git pull origin master

> $ vcpkg update libnoise:x64-windows # Not sure if I should upgrade as well

**Comment by JackBoosY** [comment]
@Xobtah Don't needed, the only think you need to do is update vcpkg and rebuild this port.
