### ISSUE TITLE
[ Efsw ] port does not put the share files in the right place

### ISSUE THREAD

**Issue by cmaughan** [microsoft/vcpkg#14128]
**Describe the bug**
When I install efsw:x64-windows-static, the efswConfig.cmake, etc. files wind up here:
D:\Dev\vcpkg\installed\x64-windows-static\share\efsw\efsw
(note the extra efsw directory).

This means that later on, find_package in cmake cannot find the config file.  I checked that moving these files out of the extra subdirectory fixes the problem, but I'm not sure how to fix the port file yet.

**Environment**
- OS: Windows
- Compiler: 2019

**Comment by JonLiu1993** [comment]
Hi @cmaughan ,
Thanks for posting this issue
It seems that you didn't build the latest version.
Could you please try to use git pull to update vcpkg to the latest commit and then rebuild this port?
