### ISSUE TITLE
Bring back Visual Studio output

### ISSUE THREAD

**Issue by joel-koch** [microsoft/vcpkg#14124]
****

**Is your feature request related to a problem? Please describe.**
The project setup is as follows:
A CMake project in directory root, vcpkg included as git submodule, the toolchain file is set to "${CMAKE_CURRENT_SOURCE_DIR}/vcpkg/scripts/buildsystems/vcpkg.cmake" as suggested and we use a vcpkg.json manifest file in the root directory.
We are using Visual Studio as IDE and the "open folder" method to work on the CMake project. Therefore, Visual Studio creates a new directory "out" in the root directory. 
The workflow is like this:
1. Open Visual Studio
2. Open the project folder
3. CMake runs "vcpkg install"

Until previously, the vcpkg output would be shown in the VS console. Now that behavior changed and the output is written to a vcpkg-manifest-install-out.log file. This is fine, but also makes me stare at "[CMake] -- Running vcpkg install" in Visual Studio for hours, not knowing the progress.

**Proposed solution**
Print the vcpkg output in Visual Studio in addition to logfile.

**Describe alternatives you've considered**
I activated verbose CMake output in the Visual Studio settings, this didn't change anything.

**Additional context**
Project setup:
root
-- src
-- out
----- build
------- x64-Debug
----------- vcpkg-manifest-install-err.log
----------- vcpkg-manifest-install-out.log
-- vcpkg
-- vcpkg.json
-- CMakeLists.txt

**Comment by NancyLi1013** [comment]
@BillyONeal 
Could you please help take a look?

Thanks.

**Comment by Neumann-A** [comment]
I introduced that change.
Should probably be switched to 
```
ECHO_OUTPUT_VARIABLE
ECHO_ERROR_VARIABLE
```
instead and write the contents manually to a file. 
or make a VCPKG_ variable which enables/disables manifest installation output.

Basically if you have a binary cache with all deps you want it probably disabled and enabled if you need to install something.

**Comment by NancyLi1013** [comment]
@Neumann-A 
Thanks for your above info.

Would you like to make a PR to fix this?

Thanks in advance.

**Comment by JackBoosY** [comment]
I noticed that both info and error are now printed, can you double confirm this?

**Comment by joel-koch** [comment]
We moved away from vcpkg, so I cannot, sorry.

**Comment by JackBoosY** [comment]
Okay. If anyone who meet this issue please ping me.
