### ISSUE TITLE
[libsodium] use of AVX512 is not portable

### ISSUE THREAD

**Issue by thomasgt** [microsoft/vcpkg#14134]
**Describe the bug**
We are using vcpkg to build dependencies for an application deployed as a Docker container. Our CI build machines have the AVX512 extensions, but the machines we deploy to often don't. The libsodium port [detects the availability of the AVX512 extensions](https://github.com/microsoft/vcpkg/blob/4aa08938a22f7cb90842280571005c4a637e7098/ports/libsodium/CMakeLists.txt#L358), and libsodium itself seems to perform runtime detection of CPU extensions when you call `sodium_init()`, but I suspect these runtime checks only protect against explicit use of AVX512 instructions. I believe by setting the compiler flag `-mavx512f`, this allows GCC to use these instructions in generated code. The runtime checks libsodium performs won't help here, as far as I'm aware. Ultimately, the end result is our application failing, signalling an illegal instruction when it ultimately encounters one of these AVX512 instructions while running on a machine without support for them.

I am not sure what the right course of action is. I suppose I could add an overlay port where I patch the `CMakeLists.txt` file to not light up AVX512. That would solve my immediate problem, but I think there is a bigger issue here. I am sure some users would be happy to always have the AVX512 instructions enabled if it fits their deployment model. This does speak to broader issue around portability. I'm sure libsodium isn't the only project making use of these instructions.

**Environment**
- build: machine with AVX512
- runtime: machine without AVX512

**Comment by thomasgt** [comment]
I'd be happy to provide more info to help reproduce this if there's interest. I've noticed GCC's auto-vectorization is a bit fragile, so it even with `-mavx512f`, I didn't always get binaries using the extension. It seemed to depend heavily on the version of the compiler I was using, possibly even the phase of the moon.

**Comment by thomasgt** [comment]
Found an issue that might be related: #7308

I'll note that this is a different type of problem than the one fixed in this PR: #8974. It does not seem like the CPU capabilities are being detected incorrectly. It is just that they way these extensions are enabled is not portable. According to GCC's docs [1], it seems the portable way to do this would be to disable these extensions for most of the source files, and then break out the hand-optimized implementations that take advantage of various extensions in separate translation units that can be compiled with the appropriate `-m` flags.

> These options enable GCC to use these extended instructions in generated code, even without -mfpmath=sse. Applications that perform run-time CPU detection must compile separate files for each supported architecture, using the appropriate flags. In particular, the file containing the CPU detection code should be compiled without these options.

[1] https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html#x86-Options

**Comment by thomasgt** [comment]
Looking through the project's [makefile](https://github.com/jedisct1/libsodium/blob/master/src/libsodium/Makefile.am), it appears they follow GCC's recommendation. Most of the source files are not compiled with any special intrinsics enabled. The files that do rely on intrinsics are built into separate individual libraries that each add the appropriate `-m` flag. This allows the library to be portable while enabling run-time CPU detection. It appears the port's CMake translation doesn't take this into account.

**Comment by sfhacker** [comment]
Any particular reason you need to use vcpkg?
I will build this project from source myself and report back here.

**Comment by PhoebeHui** [comment]
@thomasgt, thanks for reporting this issue! Could you provide the repro steps and failure log?

cc @myd7349

**Comment by sfhacker** [comment]
![image](https://user-images.githubusercontent.com/25817529/96713629-9ea8bc00-13ec-11eb-986f-85e4a94dc521.png)

![image](https://user-images.githubusercontent.com/25817529/96713641-a4060680-13ec-11eb-8c6a-5d9e78026155.png)

@thomasgt Can you provide a minimum use (or test) case so I can test it locally?

**Comment by thomasgt** [comment]
Here's a more detailed description of the environment:

**Environment**
- debian:buster
- gcc 8.3
- machine with AVX-512 extensions to build libsodium package
- machine without AVX-512 extensions to build and run application (where the failure happens (SIGILL)
- alternatively, you can build the entire application on the machine with AVX-512 extensions, but you'll need to ultimately run it on the machine without to see the failure.

It'll take me some time to decouple the steps to reproduce into a standalone project. I'll add this later today.

**Comment by BillyONeal** [comment]
This has come up a few times; we are torn between a desire for the built outputs to be "portable" as described and getting native CPU instructions being a common reason to build any of these ports from source in the first place. I think we have suggested that it might make sense to make this a triplet setting somehow but we have not gotten proposals as of yet.

**Comment by thomasgt** [comment]
I guess there are two issues here.

The first issue is that this port's autoconf to cmake translation is not quite faithful. The original autoconf files in the project attempt to keep the library "portable" by only enabling the native instructions where runtime detection is being enforced. So there's an argument to be made that the port's cmake translation should be updated to better reflect the library author's original intentions. I could probably whip up a patch for this. I suppose before I do this I should add some more info so someone can reproduce this and validate that my understanding of the problem is correct.

The second issue, as you've mentioned, is that someone going to the trouble of building their dependencies from source may want all the native instructions enabled. They may even want these turned on regardless of whether or not the library authors considered them and added explicit flags to their build system to enable them. Using the triplet mechanism does seem like the right way to go about this, although I am not sure if it is currently possible to set default compiler flags. In general, compiler flags seem messy, and I don't have a strong opinion on this as it is not something I have a use case for yet.

**Comment by thomasgt** [comment]
Apologies for the delay...
Here is a repo [1] with a minimal example showing off the issue. Build the Dockerfile on a machine with AVX512 support, and then try running it on a machine without. If you don't have access to a machine with AVX512 support, I've pushed an image to the repository's package repository that was built using AVX-512 that you can try out. [2]

You don't need to use Docker to see the issue. I just find it convenient.

[1] https://github.com/pathcore/vcpkg-libsodium-avx512
[2] https://github.com/pathcore/vcpkg-libsodium-avx512/packages/477151

**Comment by BillyONeal** [comment]
@thomasgt Oh I think the issue is understood at this point, we just don't have a fantastic solution at this time. `<whatever the triplet is>.cmake` is run before `portfile.cmake` so it should be possible to make restricting this some kind of triplet setting.

**Comment by sfhacker** [comment]
@thomasgt Just tried to build the minimal example provided by you but faced several issues!

![image](https://user-images.githubusercontent.com/25817529/97373720-b4494480-190a-11eb-8714-f8662c19bf6e.png)

After commenting out the offending line, I came across another issue!

![image](https://user-images.githubusercontent.com/25817529/97373769-d2af4000-190a-11eb-978d-1fd0e59d01d0.png)

After fixing this second issue, I got this:

![image](https://user-images.githubusercontent.com/25817529/97373908-23269d80-190b-11eb-8916-e362925129f2.png)

We are unable to interpret such output!

**Comment by thomasgt** [comment]
@sfhacker I am not sure you're going to be able to reproduce this using MinGW. I've only tried using GCC 8.3 from debian:buster. This is why I provided a Dockerfile, so you don't have to worry about getting a debian environment configured. The easiest way to reproduce this is to clone the repo onto a machine with AVX512 instructions, initialize the vcpkg submodule, and then build the docker image from the Dockerfile. You should be able to run the docker image on the machine with AVX512 instructions, but if you run it from a machine that doesn't support those instructions, it will fail. 

If you just want to see it fail, just pull down the docker image I linked to above and run it. It should fail after "initializing hash state".

**Comment by thomasgt** [comment]
@BillyONeal OK, understood. Would you accept a PR to update the CMakeLists file used in this port to resolve the immediate issue I'm having?

**Comment by BillyONeal** [comment]
@thomasgt If the PR update makes it blindly try to turn off acceleration that would be difficult to accept due to the aforementioned "that's why people are building from source in the first place". But if you want to do a PR adding `VCPKG_ENABLE_NATIVE_CPU_INSTRUCTIONS` or something like that we are interested.

**Comment by thomasgt** [comment]
@BillyONeal I was planning to match the behaviour of the project's autoconf buildsystem. I would leave the acceleration on for TU's where libsodium performs explicit runtime detection, but I'd turn it off everywhere else.

**Comment by BillyONeal** [comment]
That's probably OK, thanks :)

**Comment by JackBoosY** [comment]
@thomasgt  Can you please open a PR to fix that?

Thanks.

**Comment by thomasgt** [comment]
Yes, I'll take a look over the next week or so!
