### ISSUE TITLE
PCL and Eigen Reference Console Application

### ISSUE THREAD

**Issue by 9and3** [microsoft/vcpkg#14135]
Hi,

I have installed PCL using vcpkg:
`.\vcpkg install pcl:x64-windows` and `.\vcpkg integrate install`

And I am trying just to reference any pcl header file for C++ 64 bit Console Application.
But the compiler cannot find Eigen.
The VCPKG shows that I installed the 64 bit version of Eigen.
I just want to see if I can build a console application by referencing any PCL header file and that it is recognized by Visual Studio.

I attached the screenshot below:
![image](https://user-images.githubusercontent.com/50238678/96630560-7ac67700-1315-11eb-977f-e7594670fe24.png)

How I can properly reference Eigen?

**Comment by LilyWangL** [comment]
Thanks for posting this issue. If you want use header files of VCPKG in C++ project, you also need run command `.\vcpkg integrate project` on VCPKG. About use header files of Eigen3 will be fixed in PR #13739.

**Comment by 9and3** [comment]
Thanks @LilyWangL for your answer. Unfortunatelly, even by introducing modification commented at PR#13739 the problem persists. Any idea why? Thank you again,

**Comment by Cheney-W** [comment]
@9and3 I tried to install the pcl:x64-windows and eigen:x64-windows with latest vcpkg 2022-02-11-dac008bf9b55ef48e10bcc81e273b97a82bbf72d and after run .\vcpkg integrate install , I could find and build the header files of pcl and eigen in a console application with x64 platform.
![image](https://user-images.githubusercontent.com/38240633/153826200-8c3f1987-8138-46a5-9992-6e14ccd2a855.png)

**Comment by Cheney-W** [comment]
I also tested following codes and it built successfully.
```
#include <pcl/common/distances.h>    //distances.h include <Eigen/Core>
int main()
{
    std::cout << "Hello World!\n";
}
```

**Comment by 9and3** [comment]
Hello @Cheney-W , thank you for taking the time. Indeed, with the latest build it does work. Thank you again!
