### ISSUE TITLE
[qt5-base] build failure with manifests

### ISSUE THREAD

**Issue by alexsmn** [microsoft/vcpkg#14133]
**Host Environment**
- OS: Windows
- Compiler: `Microsoft (R) C/C++ Optimizing Compiler Version 19.27.29112 for x86`
- CMake: 3.18.0
- Vcpkg revision: 27a2418e91179d8607862348d7b498558e98a0ab

**To Reproduce**
```
1. Pull and bootstrap Vcpkg in `D:\vcpkg`.
1. Create a dummy CMake project in a directory on disk `C:`. Note the different disks.
1. Create `vcpkg.json` with dependencies from `qt5-base`.
1. Run CMake in the project distectory located on disk `C:` with `CMAKE_TOOLCHAIN_FILE` set to the `D:\vcpkg\scripts\buildsystems\vcpkg.cmake`.
```

**Failure logs** 
CMake output:
```
-- Running vcpkg install
CMake Error at D:/vcpkg/scripts/buildsystems/vcpkg.cmake:386 (message):
  Running vcpkg install - failed
```

`d:\vcpkg\buildtrees\qt5-base\stdout-x86-windows.log`:
```
-- Installing x86-windows-dbg
-- Package x86-windows-dbg done
-- Building x86-windows-rel
-- Fixing makefile installation path x86-windows-rel
-- Installing x86-windows-rel
-- Package x86-windows-rel done
CMake Error at ports/qt5-base/portfile.cmake:332 (file):
  file RENAME failed to rename

    D:/vcpkg/packages/qt5-base_x86-windows/lib/cmake

  to

    D:/vcpkg/packages/qt5-base_x86-windows/share/cmake

  because: File exists

Call Stack (most recent call first):
  scripts/ports.cmake:79 (include) 
```

**Additional context**
When not using manifest, `vcpkg install qt5-base` succeeds.

Although Vcpkg creates `d:\vcpkg\packages\qt5-base_x86-windows\share\qt5-base`, the directory `D:/vcpkg/packages/qt5-base_x86-windows/share/cmake`, it complains on, doesn't exist. At least after build ends.

Vcpkg uses `d:\vcpkg\buildtrees\qt5-base` for build, but it creates both `d:\vcpkg\packages\qt5-base_x86-windows` and `c:\vcpkg\packages\qt5-base_x86-windows` directories. (On two disks.)

Directory `c:\vcpkg\packages\qt5-base_x86-windows\share\qt5-base` doesn't exist as well.

**Comment by JackBoosY** [comment]
cc @Neumann-A  @strega-nil

**Comment by strega-nil** [comment]
cc @Neumann-A, I don't even know where to start with this.

**Comment by Neumann-A** [comment]
`--debug `output needed
and probably a run of 
https://github.com/microsoft/vcpkg/pull/12877
with `--trace` or `--trace-expand`
It is probably a confusion between one of the VCPKG cmake variables.

**Comment by alexsmn** [comment]
Pushed some [example code](https://github.com/alexsmn/vcpkg-sandbox/tree/main/bug-1).

Will be happy to provide more data. I guess `--debug`, `--trace`, and `--trace-expand` are `vcpkg` command line arguments. How to you specify these arguments when installing a package from manifest?

**Comment by alexsmn** [comment]
Build log with `--trace-expand`: [stdout-x86-windows.zip](https://github.com/microsoft/vcpkg/files/5471568/stdout-x86-windows.zip)

**Comment by alexsmn** [comment]
Adding drive letters at [this line](https://github.com/microsoft/vcpkg/blob/master/ports/qt5-base/cmake/qt_fix_makefile_install.cmake#L23) makes the build to succeed:

```
diff --git a/ports/qt5-base/cmake/qt_fix_makefile_install.cmake b/ports/qt5-base/cmake/qt_fix_makefile_install.cmake
index 95831d29f..70006e49a 100644
--- a/ports/qt5-base/cmake/qt_fix_makefile_install.cmake
+++ b/ports/qt5-base/cmake/qt_fix_makefile_install.cmake
@@ -20,7 +20,7 @@ function(qt_fix_makefile_install BUILD_DIR)
     foreach(MAKEFILE ${MAKEFILES})
         file(READ "${MAKEFILE}" _contents)
         #Set the correct install directory to packages
-        string(REPLACE "(INSTALL_ROOT)${INSTALLED_DIR_WITHOUT_DRIVE}" "(INSTALL_ROOT)${PACKAGES_DIR_WITHOUT_DRIVE}" _contents "${_contents}")
+        string(REPLACE "C:$(INSTALL_ROOT)${INSTALLED_DIR_WITHOUT_DRIVE}" "D:$(INSTALL_ROOT)${PACKAGES_DIR_WITHOUT_DRIVE}" _contents "${_contents}")
         file(WRITE "${MAKEFILE}" "${_contents}")
     endforeach()
 endfunction()
```

**Comment by Osyotr** [comment]
Bump.
Project location: `D:/MyProject/Sources/CMakeLists.txt`
Toolchain location: `E:/vcpkg/scripts/buildsystems/vcpkg.cmake`
Error message:
```
1> [CMake] CMake Error at ports/qt5-base/portfile.cmake:387 (file):
1> [CMake]   file RENAME failed to rename
1> [CMake]     E:/vcpkg/packages/qt5-base_x64-windows/lib/cmake
1> [CMake]   to
1> [CMake]     E:/vcpkg/packages/qt5-base_x64-windows/share/cmake
1> [CMake]   because: File exists
1> [CMake] Call Stack (most recent call first):
1> [CMake]   scripts/ports.cmake:142 (include)
```
Vcpkg version: `2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e`
HEAD is at `807a7987612bbd702be9d9b8069124be62aff857`

**Comment by alexsmn** [comment]
Thank you!
