### ISSUE TITLE
OpenColorIO not found for static build of OpenImageIO

### ISSUE THREAD

**Issue by andrew-klaassen** [microsoft/vcpkg#14132]
**Describe the bug**
I built openimageio both dynamically and statically, specifying tools and opencolorio support for both.  OpenColorIO support ended up in the dynamic build of oiiotool.exe, but it did not end up in the static build.

**Environment**
Windows 10
Visual Studio 2019

**To Reproduce**
1. vcpkg install openimageio[opencolorio,tools]:x64-windows-static --recurse
2. installed\x64-windows-static\tools\openimageio\oiiotool.exe --help

Result:
<pre>...[snip]...
Color configuration: built-in
Known color spaces: "linear", "default", "rgb", "RGB", "sRGB", "Rec709"
No OpenColorIO support was enabled at build time.
Filters available: box...
...[snip]...</pre>

**Expected behavior**
Correct result produced by the dynamic build:
installed\x64-windows\tools\openimageio\oiiotool.exe --help
<pre>...[snip]...
Color configuration: built-in
Known color spaces: "linear", "default", "rgb", "RGB", "sRGB", "Rec709"
Filters available: box...
...[snip]...</pre>

**Failure logs** 
A diff between the dynamic and static config logs (attached) seems to point to exactly what the problem is, though I have no idea how to fix it.

<pre>diff config-x64-windows-out.log config-x64-windows-static-out.log
...[snip]...
98,102c95,97
< -- Found OpenColorIO: C:/src/vcpkg/installed/x64-windows/include (found version "1.1.1")
< -- Found OpenColorIO 1.1.1
< --     OPENCOLORIO_INCLUDES = C:/src/vcpkg/installed/x64-windows/include
< --     OPENCOLORIO_INCLUDE_DIR = C:/src/vcpkg/installed/x64-windows/include
< --     OPENCOLORIO_LIBRARIES = C:/src/vcpkg/installed/x64-windows/lib/OpenColorIO.lib
---
> -- Could NOT find OpenColorIO (missing: OPENCOLORIO_LIBRARY) (found version "1.1.1")
> -- OpenColorIO library not found
> --     Try setting OpenColorIO_ROOT ?
...[snip]...
</pre>

**Additional context**
I just downloaded and installed both Visual Studio and vcpkg in the past couple of days, so this is a fairly clean build.

[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/5409962/config-x64-windows-out.log)
[config-x64-windows-static-out.log](https://github.com/microsoft/vcpkg/files/5409963/config-x64-windows-static-out.log)

**Comment by Szabolcs** [comment]
I just happened to bump into the same OCIO static linking bug on linux. Its a bit more problematic there, because static linking is  the default linking mode so compiling OIIO with OCIO support is not working on linux at all with VCPKG at the moment.

**Comment by JonLiu1993** [comment]
@andrew-klaassen, After I run the latest vcpkg according to your reproduction method, there is no display：

vcpkg install openimageio[opencolorio,tools]:x64-windows-static --recurse
````
Computing installation plan...
The following packages are already installed:
    openimageio[core,opencolorio,tools]:x64-windows-static -> 2.4.9.0#1
openimageio:x64-windows-static is already installed
Restored 0 package(s) from C:\Users\test\AppData\Local\vcpkg\archives in 160 us. Use --debug to see more details.
Total install time: 788 us
The package openimageio provides CMake targets:

    find_package(OpenImageIO CONFIG REQUIRED)
    target_link_libraries(main PRIVATE OpenImageIO::OpenImageIO)
````
installed\x64-windows-static\tools\openimageio\oiiotool.exe --help
````
PS F:\Feature-test\port-bug\vcpkg> installed\x64-windows-static\tools\openimageio\oiiotool.exe --help
PS F:\Feature-test\port-bug\vcpkg>
````
