### ISSUE TITLE
Installing on raspberry pi 3b+

### ISSUE THREAD

**Issue by advra** [microsoft/vcpkg#14140]
I installed the latest version of cmake and was following [some instructions i made ](https://github.com/advra/grpc-vcpkg-boilerplate-example)to integrate a project that used vcpkg with grpc. I compiled vcpkg from source with:
```
sudo apt-get install -y unzip build-essential
git clone https://github.com/microsoft/vcpkg
cd vcpkg/
./bootstrap-vcpkg.sh -disableMetrics
```
After installing vcpkg I try to install package with `./vcpkg install grpc` which resulted in the error bellow. The instructions worked on a OSX and Ubuntu but I run into issues with raspberry pi. 

Using `./vcpkg` result in a VCPKG_FORCE_SYSTEM_BINARIES error:
```
pi@raspberrypi:~/vcpkg $ ./vcpkg 
Environment variable VCPKG_FORCE_SYSTEM_BINARIES must be set on arm and s390x platforms.
```
I have set this ti `0` and `1` like so `$VCPKG_FORCE_SYSTEM_BINARIES=1` but neither option helps.

**Comment by JackBoosY** [comment]
Hmm...I don't have a raspberry pi, @BillyONeal could you please take a look?

Thanks.

**Comment by BillyONeal** [comment]
Isn't it:

```
export VCPKG_FORCE_SYSTEM_BINARIES=1
./vcpkg install grpc
```

in bash?

**Comment by advra** [comment]
The export command worked. Thank you for clearing that up.

**Comment by DennisDyallo** [comment]
This helped me as well
