### ISSUE TITLE
How do I safely clean vcpkg archives and disable it?

### ISSUE THREAD

**Issue by stvriver** [microsoft/vcpkg#14157]
Recently I realize that the archives folder stored in Windows at "C:\Users\usrName\AppData\Local\vcpkg\archives" is quite big. Since I do not need this archives while it occupies some precious SSD space. How can I safely remove this folder and prevent vcpkg from storing back in future?

**Comment by NancyLi1013** [comment]
Hi @stvriver 
Thanks for posting this issue.
These archives stored in _C:\Users\usrName\AppData\Local\vcpkg\archives_ are binary caches for the ports that you build.

You can delete them directly if you don't want to keep them.

**Comment by NancyLi1013** [comment]
You can disable it by updating these changes in _toolsrc/include/vcpkg/vcpkgcmdarguments.h_ file:

```
bool binary_caching_enabled() const { return binary_caching.value_or(false); }
bool compiler_tracking_enabled() const { return compiler_tracking.value_or(false); }
```
Related PR #12370.

**Comment by NancyLi1013** [comment]
Hi @stvriver 
Please let me know if this is still a problem for you.

**Comment by stvriver** [comment]
I am sorry for late checking this. Thanks NancyLi1013 for support.

After I look into vcpkg commands help, I realize that vcpkg supports disable binary caching by "_either passing_
`--no-binarycaching` _to every vcpkg command line or setting the environment variable_ `VCPKG_FEATURE_FLAGS` to `-binarycaching`."
So I think that is the way I should follow instead of changing the source as your suggestion. 
There is one thing I am not clear is where and how can I set `VCPKG_FEATURE_FLAGS` to `-binarycaching`?.

**Comment by NancyLi1013** [comment]
Hi @stvriver 

Thanks for your further investigation about binary caching. To be honest, I also didn't focus on the workaround to disable binary caching before you pointing this out. Thanks for your help.

As you mentioned above, there are two ways to disable it:

- passing --no-binarycaching to every vcpkg command line

  add the option `--no-binarycaching` to vcpkg command, such as `vcpkg install sqlite3 --no-binarycaching`.

- setting the environment variable VCPKG_FEATURE_FLAGS to -binarycaching

   add `VCPKG_FEATURE_FLAGS ` in environment variable, set the value as `-binarycaching`.
   
   Note: Please restart your machine after you set it.

**Comment by stvriver** [comment]
Hi @NancyLi1013 
With your detail expression I think my confusion is clear and the issue is solved.
Again, thanks for your support.

**Comment by NancyLi1013** [comment]
Thanks for your feedback. I'm closing this issue for now.

**Comment by talregev** [comment]
I have simple workaround it for linux.
Just delete the zip:
`sudo apt purge zip` then the vcpkg will not find zip command and stop caching. it just more easy.

**Comment by Rusching** [comment]
Hi @NancyLi1013 if I directly delete vcpkg folder listed in C:\Users\usrName\AppData\Local, will there be problems such as import errors later?

**Comment by Dave-Lowndes** [comment]
I've tried deleting the vcpkg folder in AppData\Local because I had several versions that I no longer needed. Unfortunately it's caused a problem for me - none of my projects now rebuild - they can't find header files and the packages aren't being re-created.

**Comment by dg0yt** [comment]
> I've tried deleting the vcpkg folder in AppData\Local because I had several versions that I no longer needed. Unfortunately it's caused a problem for me - none of my projects now rebuild - they can't find header files and the packages aren't being re-created.

That problem doesn't seem to be linked to deleting the compressed artifact archives in `AppData\Local`. The header files wouldn't be installed there (unless you did something unusual).

**Comment by Dave-Lowndes** [comment]
After deleting the directory VS behaved as though vcpkg wasn't available to it. After closing and re-opening VS, the vcpkg tab disappeared from the project settings.
To cut a long story short, I've found that all that's required to reinstate it is to run "vcpkg integrate install" from an admin VS command prompt. This has reconstituted the AppData\Local\vcpkg directory with these files:
config
vcpkg.path.txt
vcpkg.user.props
vcpkg.user.targets

My projects now build OK again.
