### ISSUE TITLE
[ spdlog ]Build error

### ISSUE THREAD

**Issue by whidbey** [microsoft/vcpkg#14158]
when build and install,says:
Failed at [C:\vcpkg\toolsrc\src\vcpkg\vcpkglib.cpp(214)] with message:
no such file or directory

**Environment**
- OS: win7
- Compiler: vs2019/vs2017

**To Reproduce**
cd c:/vcpkg
1.git pull
2. ./bootstrap-vcpkg.bat
3. vcpkg integrate install
4. ./vcpkg install spdlog:x86-windows-static
. See error
Repro code when

**Expected behavior**

**Failure logs** 
-(please attached failure logs)

**Additional context**

c:\vcpkg>.\vcpkg install spdlog:x86-windows-static
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete o
ur survey by running: vcpkg contact --survey
Computing installation plan...
The following packages will be built and installed:
  * fmt[core]:x86-windows-static
    spdlog[core]:x86-windows-static
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x86-windows-static...
Starting package 1/2: fmt:x86-windows-static
Building package fmt[core]:x86-windows-static...
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\arch
ives\6d\6dfd5da491a20283b333d1661d96eeb8e1143a33.zip
-- Using community triplet x86-windows-static. This triplet configuration is not
 guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: C:\vcpkg\triplets\community\x
86-windows-static.cmake
-- Using cached C:/vcpkg/downloads/fmtlib-fmt-cd4af11efc9c622896a3e4cb599fa28668
ca3d05.tar.gz
-- Extracting source C:/vcpkg/downloads/fmtlib-fmt-cd4af11efc9c622896a3e4cb599fa
28668ca3d05.tar.gz
-- Applying patch fix-warning4189.patch
-- Using source at C:/vcpkg/buildtrees/fmt/src/8668ca3d05-7f40cec0ee.clean
-- Configuring x86-windows-static
-- Building x86-windows-static-dbg
-- Building x86-windows-static-rel
-- Installing: C:/vcpkg/packages/fmt_x86-windows-static/share/fmt/copyright
-- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.
2-1-any.pkg.tar.xz...
-- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-gi
t-8.0.0.5906.c9a21571-1-any.pkg.tar.zst...
-- Using msys root at C:/vcpkg/downloads/tools/msys2/c809757c94447846
-- Fixing pkgconfig file: C:/vcpkg/packages/fmt_x86-windows-static/lib/pkgconfig
/fmt.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/fmt_x86-windows-static/debug/lib/pkg
config/fmt.pc
-- Installing: C:/vcpkg/packages/fmt_x86-windows-static/share/fmt/usage
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\Administrator\AppData\Local\vcpkg\archives\6d\6dfd
5da491a20283b333d1661d96eeb8e1143a33.zip
Building package fmt[core]:x86-windows-static... done
Installing package fmt[core]:x86-windows-static...
Failed at [C:\vcpkg\toolsrc\src\vcpkg\vcpkglib.cpp(214)] with message:

**Comment by JonLiu1993** [comment]
Hi @whidbey ,Thanks for posting this issue. Do you can install other ports successfully?

**Comment by sfhacker** [comment]
Are we still having issues building 'spdlog'?
@whidbey Have you contacted us before (several times) regarding other issues?

**Comment by whidbey** [comment]
no, openssl also the same.... can't figureout it

**Comment by whidbey** [comment]
> 
> 
> Are we still having issues building 'spdlog'?
> @whidbey Have you contacted us before (several times) regarding other issues?

before that i install zeromq serveral month ago ok.

**Comment by JonLiu1993** [comment]
@whidbey , You can try remove all instalition of vcpkg(and of course api) and install again.

**Comment by JackBoosY** [comment]
`Failed at [C:\vcpkg\toolsrc\src\vcpkg\vcpkglib.cpp(214)] with message:`
Empty message?

**Comment by whidbey** [comment]
> 
> 
> ~`Failed at [C:\vcpkg\toolsrc\src\vcpkg\vcpkglib.cpp(214)] with message:` Empty message?~
> 
> Please close your anti-virus and try again. Or clone vcpkg to a non-system partition and try again,
> 
I dont have a virus soft now... but network firewall.

> Thanks.

**Comment by whidbey** [comment]
> 
> 
> @whidbey , You can try remove all instalition of vcpkg(and of course api) and install again.

I am trying to clone a new full vcpkg to see again.
git clone https://github.com/microsoft/vcpkg.git vcpkg2

**Comment by whidbey** [comment]
a new fresh vcpkg is ok..... don't know why... but works..thanks...

**Comment by JackBoosY** [comment]
@whidbey I guess you should have permission to create directory on the system disk.

**Comment by whidbey** [comment]
> 
> 
> @whidbey I guess you should have permission to create directory on the system disk.

but why new full fresh vcpkg is ok.. can't explain....

**Comment by JackBoosY** [comment]
Sorry, I don't know either.
