### ISSUE TITLE
cmake could not find toolchain file build failure

### ISSUE THREAD

**Issue by Redwolf223** [microsoft/vcpkg#14150]
**Host Environment**
- OS: Windows
- Compiler: Visual studio 15 2017

**To Reproduce**
cmake -DCMAKE_TOOLCHAIN_FILE=<PATH_TO_VCPKG>\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -A x64 ..

**Failure logs** 
$ cmake -DCMAKE_TOOLCHAIN_FILE=C:\dev\vcpkg\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -
A x64 ..
CMake Error at C:/Program Files/CMake/share/cmake-3.19/Modules/CMakeDetermineSystem.cmake:110 (message):
  Could not find toolchain file:
  C:devvcpkgvcpkgscriptsbuildsystemsvcpkg.cmake
Call Stack (most recent call first):
  CMakeLists.txt:53 (project)

-- Configuring incomplete, errors occurred!

**Comment by Neumann-A** [comment]
Use forward slashes `/` instead of backward ones `\` or escape the backwards ones `\\`.
That is also more a CMake issue than a vcpkg issue

**Comment by NancyLi1013** [comment]
Hi @Redwolf223 

Thanks for posting this issue.

Could you please try to use the suggestion from @Neumann-A ?

**Comment by NancyLi1013** [comment]
Closing this issue for no response.

Please feel free to reopen this issue if it is still a problem for you.
