### ISSUE TITLE
[New Port Request] <coreutils>

### ISSUE THREAD

**Issue by jiangjianshan** [microsoft/vcpkg#14155]
Library name:  coreutils

Library description: The GNU Core Utilities are the basic file, shell and text manipulation utilities of the GNU operating system. These are the core utilities which are expected to exist on every operating system.

Source repository URL: https://ftp.gnu.org/gnu/coreutils/coreutils-8.32.tar.xz

Project homepage (if different from the source repository): https://www.gnu.org/software/coreutils/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by BillyONeal** [comment]
Hi there, @jiangjianshan ; when/how would someone want to use coreutils as a library? Note that we don't generally intend to provide "tools" unless they are needed to build something.

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
