### ISSUE TITLE
[qt5]Can't preview qml file via qmlscene, qtquick2plugin.dll cannot be loaded

### ISSUE THREAD

**Issue by spindensity** [microsoft/vcpkg#14156]
**Describe the bug**
Can't preview `qml` file via `qmlscene`, error `can't load library qtquick2plugin.dll` is reported when using `qmlscene` on the commond line.

**Environment**
- OS: Windows 20H1 64bit;
- Compiler: MSVC 2019 16.7.6;
- Qt: 5.15.1.

**To Reproduce**
Steps to reproduce the behavior, we assume the installation directory of vcpkg is `D:\Repository\vcpkg`:
1. `vcpkg install qt5:x64-windows`
2. `D:\Repository\vcpkg\installed\x64-windows\tools\qt5\bin\qmlscene.exe ./main.qml`
The contents of `./main.qml` are:
```qml
import QtQuick 2.15
import QtQuick.Window 2.15

Window {
    width: 640
    height: 480
    visible: true
    title: qsTr("Hello World")
}
```
3. Error happens:
```
file:///C:/test/hello-qml/main.qml:1 plugin cannot be loaded for module "QtQuick": Cannot load library D:\Repository\vcpkg\installed\x64-windows\qml\QtQuick.2\qtquick2plugin.dll：The specified module could not be found.
```

**Expected behavior**
`qmlscene` opens a preview window.

**Failure logs** 
```
file:///C:/test/hello-qml/main.qml:1 plugin cannot be loaded for module "QtQuick": Cannot load library D:\Repository\vcpkg\installed\x64-windows\qml\QtQuick.2\qtquick2plugin.dll：The specified module could not be found.
```

**Additional context**
The error message says `D:\Repository\vcpkg\installed\x64-windows\qml\QtQuick.2\qtquick2plugin.dll` can't be loaded, but the file is actually there.

**Comment by Neumann-A** [comment]
Did it work fine with Qt 5.15.0?

**Comment by spindensity** [comment]
> Did it work fine with Qt 5.15.0?

No, Qt 5.15.0 (4a3d9e22d1b104332c5faf98abfcee94b671c9ef) did not work.

By the way, `vcpkg install qt5:x64-windows` could reproduce the bug, installing `qt5[all]` is unnecessary.

**Comment by Neumann-A** [comment]
https://stackoverflow.com/questions/38030140/import-qtquick-controls-2-0-not-working-qqmlapplicationengine-failed-to-load-c

probably unrelated to `qtquick2plugin.dll`

I assume that `D:\Repository\vcpkg\installed\x64-windows\tools\qt5\bin\` does not have the required qml/quick dlls copied over from `D:\Repository\vcpkg\installed\x64-windows\bin`

I assume it is related to https://github.com/microsoft/vcpkg/issues/11056 which is an deployment issue. Try copying the extra dlls to `tools\qt5\bin\`

**Comment by spindensity** [comment]
> https://stackoverflow.com/questions/38030140/import-qtquick-controls-2-0-not-working-qqmlapplicationengine-failed-to-load-c
> 
> probably unrelated to `qtquick2plugin.dll`
> 
> I assume that `D:\Repository\vcpkg\installed\x64-windows\tools\qt5\bin\` does not have the required qml/quick dlls copied over from `D:\Repository\vcpkg\installed\x64-windows\bin`
> 
> I assume it is related to #11056 which is an deployment issue. Try copying the extra dlls to `tools\qt5\bin\`

Yes, The latest version (Qt 5.15.1, vcpkg d6032b525870f30d21aeb144e655a8e8fcba8736) did not copy some QtQuick and QML related dlls  to `tools\qt5\bin`:

![Snipaste_2020-10-22_20-32-52](https://user-images.githubusercontent.com/33576822/96872257-f9eab500-14a5-11eb-86c4-5410ca3f018e.png)

I copied these three missing dlls manually:
* `Qt5QmlWorkerScript.dll`
* `Qt5QuickParticles.dll`
* `Qt5QuickWidgets.dll`

to `tools\qt5\bin`, and the problem is solved.

Thanks.

**Comment by JackBoosY** [comment]
Did we forget to copy some libraries to the tools folder?

**Comment by upupming** [comment]
> Did we forget to copy some libraries to the tools folder?

@JackBoosY I got this bug, too when I build a QML project.

![image](https://user-images.githubusercontent.com/24741764/113137785-8f5d5280-9257-11eb-9665-40cc19553fdb.png)

It says `C:\Users\ming\projects\tooth-studio\build\Debug\qml\QtQuick.2\qtquick2plugind.dll` couldn't be found, but it exists there:

![image](https://user-images.githubusercontent.com/24741764/113137866-ab60f400-9257-11eb-927c-e22e850b1257.png)

**Comment by JackBoosY** [comment]
Does #14594 fix this issue?

**Comment by upupming** [comment]
> Does #14594 fix this issue?

No, the DLLs are copied correctly, but still got this error.

**Comment by Logiase** [comment]
same error with version 5.15.2 built 2021/7/6
