### ISSUE TITLE
[benchmark] build failure

### ISSUE THREAD

**Issue by danielbuhrig** [microsoft/vcpkg#14161]
**Host Environment**
- OS: Windows
- Compiler: cl 19.27.29112

**To Reproduce**
`./vcpkg install benchmark`

**Failure logs** 
Error: Building package benchmark:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: benchmark:x64-windows
  Vcpkg version: 2020.06.15-nohash

**Additional context**
Starting package 1/68: benchmark:x64-windows
Building package benchmark[core]:x64-windows...
Could not locate cached archive: C:\Users\tr\AppData\Local\vcpkg\archives\24\242a4abebcb170adb47e97665ec9f365eaf70713.zip
-- Note: benchmark only supports static library linkage. Building static library.
-- Downloading https://github.com/google/benchmark/archive/8039b4030795b1c9b8cedb78e3a2a6fb89574b6e.tar.gz...
-- Extracting source C:/Users/.../vcpkg/downloads/google-benchmark-8039b4030795b1c9b8cedb78e3a2a6fb89574b6e.tar.gz
-- Using source at C:/Users/.../vcpkg/buildtrees/benchmark/src/fb89574b6e-43aa35efce.clean
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:85 (message):
    Command failed: ninja -v
    Working Directory: C:/Users/.../vcpkg/buildtrees/benchmark/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\Users\...\vcpkg\buildtrees\benchmark\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:305 (vcpkg_execute_required_process)
  ports/benchmark/portfile.cmake:14 (vcpkg_configure_cmake)
  scripts/ports.cmake:79 (include)

Logfile --> 
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/5421669/config-x64-windows-out.log)

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Could you remove _[VCPKG_path]/buildtrees/benchmark_ and install `benchmark` again?

**Comment by danielbuhrig** [comment]
Hi. I did delete the folder, however, I still get the same error.

**Comment by LilyWangL** [comment]
Thanks for your reply. Do you use antivirus software on your device? And could you confirm if the file `cmTC_33940.exe` on the directory _[vcpkg_path]/buildtrees/benchmark/x64-windows-rel/CMakeFiles/CMakeTmp_?

**Comment by danielbuhrig** [comment]
Yes, this file exists, and yes, I have antivirus software. 
Antivirus software seems to be the source of the problem, at least it shows high activity during CMake configuration. 
Since I work on a corporate computer, I cannot change antivirus settings. Do you happen to have a workaround at hand?

**Comment by LilyWangL** [comment]
Maybe you can try to clone VCPKG to other disks and rebuild ports.

**Comment by NancyLi1013** [comment]
@danielbuhrig 

Is this still a problem for you?

**Comment by danielbuhrig** [comment]
It turned out its the anti-virus protection software which messes up building.
