### ISSUE TITLE
[boost_thread] build failure  x86-mingw-dynamic

### ISSUE THREAD

**Issue by x-bruce** [microsoft/vcpkg#14163]
**Host Environment**
- OS: [Windows10.]
- Compiler: QT mingw 7.3 win32

**To Reproduce**
`./vcpkg install boost-thread:x86-mingw-dynamic`

**Failure logs** 
PS C:\Tools\vcpkg-2020.07>  .\vcpkg.exe install boost-thread:x86-mingw-dynamic
Computing installation plan...
The following packages will be built and installed:
    boost-thread[core]:x86-mingw-dynamic
Detecting compiler hash for triplet x86-mingw-dynamic...
Starting package 1/1: boost-thread:x86-mingw-dynamic
Building package boost-thread[core]:x86-mingw-dynamic...
Could not locate cached archive: C:\Users\AppData\Local\vcpkg\archives\ef\ef9e49ecea3c82fae42bb397accbf2f0aa289c62.zip
-- Using community triplet x86-mingw-dynamic. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: C:\Tools\vcpkg-2020.07\triplets\community\x86-mingw-dynamic.cmake
-- Using cached C:/Tools/vcpkg-2020.07/downloads/boostorg-thread-boost-1.73.0.tar.gz
-- Cleaning sources at C:/Tools/vcpkg-2020.07/buildtrees/boost-thread/src/ost-1.73.0-dc261c4ef1.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Tools/vcpkg-2020.07/downloads/boostorg-thread-boost-1.73.0.tar.gz
-- Using source at C:/Tools/vcpkg-2020.07/buildtrees/boost-thread/src/ost-1.73.0-dc261c4ef1.clean
-- Including C:/Tools/vcpkg-2020.07/ports/boost-thread/b2-options.cmake
-- Configuring x86-mingw-dynamic
-- Building x86-mingw-dynamic-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:139 (message):
    Command failed: C:/Tools/vcpkg-2020.07/downloads/tools/cmake-3.17.2-windows/cmake-3.17.2-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v
    Working Directory: C:/Tools/vcpkg-2020.07/buildtrees/boost-thread/x86-mingw-dynamic-dbg
    See logs for more information:
      C:\Tools\vcpkg-2020.07\buildtrees\boost-thread\install-x86-mingw-dynamic-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  installed/x86-mingw-dynamic/share/boost-build/boost-modular-build.cmake:109 (vcpkg_install_cmake)
  ports/boost-thread/portfile.cmake:12 (boost_modular_build)
  scripts/ports.cmake:79 (include)

Error: Building package boost-thread:x86-mingw-dynamic failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-thread:x86-mingw-dynamic
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.

**Additional context**
[1/2] cmd.exe /C "cd /D C:\Tools\vcpkg-2020.07\buildtrees\boost-thread\src\ost-1.73.0-dc261c4ef1.clean\build && C:\Tools\vcpkg-2020.07\installed\x86-mingw-dynamic\tools\boost-build\b2.exe --user-config=C:/Tools/vcpkg-2020.07/buildtrees/boost-thread/x86-mingw-dynamic-dbg/user-config.jam --stagedir=C:/Tools/vcpkg-2020.07/buildtrees/boost-thread/x86-mingw-dynamic-dbg/stage --build-dir=C:/Tools/vcpkg-2020.07/buildtrees/boost-thread/x86-mingw-dynamic-dbg /boost/thread//boost_thread runtime-link=shared link=shared address-model=32 architecture=x86 target-os=windows toolset=gcc threadapi=win32 -sZLIB_BINARY=z -sZLIB_LIBPATH="C:/Strawberry/c/lib/libz.a" -sBZIP2_BINARY=bz2d -sBZIP2_LIBPATH="BZIP2_LIBPATH-NOTFOUND" variant=debug --layout=system --with-atomic --with-random --with-date_time --with-filesystem --with-system --with-thread --with-chrono -sZLIB_INCLUDE="C:/Strawberry/c/include" -sBZIP2_INCLUDE="C:/Strawberry/c/include" -sICU_PATH="ICU_PATH-NOTFOUND" -j4 -sBOOST_ROOT=C:/Tools/vcpkg-2020.07/installed/x86-mingw-dynamic/tools/boost-build -sBOOST_BUILD_PATH=C:/Tools/vcpkg-2020.07/installed/x86-mingw-dynamic/tools/boost-build --debug-configuration --ignore-site-config --hash -q threading=multi debug-symbols=on stage"
FAILED: CMakeFiles/boost 
cmd.exe /C "cd /D C:\Tools\vcpkg-2020.07\buildtrees\boost-thread\src\ost-1.73.0-dc261c4ef1.clean\build && C:\Tools\vcpkg-2020.07\installed\x86-mingw-dynamic\tools\boost-build\b2.exe --user-config=C:/Tools/vcpkg-2020.07/buildtrees/boost-thread/x86-mingw-dynamic-dbg/user-config.jam --stagedir=C:/Tools/vcpkg-2020.07/buildtrees/boost-thread/x86-mingw-dynamic-dbg/stage --build-dir=C:/Tools/vcpkg-2020.07/buildtrees/boost-thread/x86-mingw-dynamic-dbg /boost/thread//boost_thread runtime-link=shared link=shared address-model=32 architecture=x86 target-os=windows toolset=gcc threadapi=win32 -sZLIB_BINARY=z -sZLIB_LIBPATH="C:/Strawberry/c/lib/libz.a" -sBZIP2_BINARY=bz2d -sBZIP2_LIBPATH="BZIP2_LIBPATH-NOTFOUND" variant=debug --layout=system --with-atomic --with-random --with-date_time --with-filesystem --with-system --with-thread --with-chrono -sZLIB_INCLUDE="C:/Strawberry/c/include" -sBZIP2_INCLUDE="C:/Strawberry/c/include" -sICU_PATH="ICU_PATH-NOTFOUND" -j4 -sBOOST_ROOT=C:/Tools/vcpkg-2020.07/installed/x86-mingw-dynamic/tools/boost-build -sBOOST_BUILD_PATH=C:/Tools/vcpkg-2020.07/installed/x86-mingw-dynamic/tools/boost-build --debug-configuration --ignore-site-config --hash -q threading=multi debug-symbols=on stage"
notice: found boost-build.jam at C:/Tools/vcpkg-2020.07/installed/x86-mingw-dynamic/tools/boost-build/boost-build.jam
notice: loading B2 from C:/Tools/vcpkg-2020.07/installed/x86-mingw-dynamic/tools/boost-build/src/kernel
notice: Site configuration files will be ignored due to the
notice: --ignore-site-config command-line option.
notice: Loading explicitly specified user configuration file:
    C:\Tools\vcpkg-2020.07\buildtrees\boost-thread\x86-mingw-dynamic-dbg\user-config.jam
notice: Searching 'C:\Tools\vcpkg-2020.07\buildtrees\boost-thread\x86-mingw-dynamic-dbg' for user-config configuration file 'user-config.jam'.
notice: Loading user-config configuration file 'user-config.jam' from 'C:/Tools/vcpkg-2020.07/buildtrees/boost-thread/x86-mingw-dynamic-dbg'.
notice: will use 'C:/Qt/Tools/mingw730_32/bin/c++.exe' for gcc, condition <toolset>gcc-5.4.1
notice: using gcc libraries :: <toolset>gcc-5.4.1 :: C:/Qt/Tools/mingw730_32/bin C:/Qt/Tools/mingw730_32/lib C:/Qt/Tools/mingw730_32/lib32 C:/Qt/Tools/mingw730_32/lib64
notice: using gcc archiver :: <toolset>gcc-5.4.1 :: C:/Qt/Tools/mingw730_32/bin/ar.exe
notice: using gcc ranlib :: <toolset>gcc-5.4.1 :: C:/Qt/Tools/mingw730_32/bin/ranlib.exe
notice: using rc compiler :: <toolset>gcc-5.4.1 :: C:\Qt\Tools\mingw730_32\bin\windres.exe
error: Unable to find file or target named
error:     '/boost//C:/Tools/vcpkg-2020.07/installed/x86-mingw-dynamic/debug/lib/libboost_chrono.so'
error: referred to from project at
error:     '..'

ninja: build stopped: subcommand failed.

**Comment by x-bruce** [comment]
x86-mingw-dynamic

while the error says  “libboost_chrono.so”  ?
error: '/boost//C:/Tools/vcpkg-2020.07/installed/x86-mingw-dynamic/debug/lib/libboost_chrono.so'

In the dir of C:/Tools/vcpkg-2020.07/installed/x86-mingw-dynamic/debug/lib  I found has bellow file:
libboost_chrono.dll.a

**Comment by longnguyen2004** [comment]
Hmm weird, I'll take a look at it

**Comment by longnguyen2004** [comment]
It's a bug in Boost.Build 1.73.0, please update to 1.74.0

**Comment by PhoebeHui** [comment]
@x-bruce, boost has been upgrade to 1.74.0, could you get latest source and see if the issue still persist?

**Comment by longnguyen2004** [comment]
@PhoebeHui Can't repro on current vcpkg and boost, this is fixed.

**Comment by PhoebeHui** [comment]
@longnguyen2004, good to know, thanks for your response!
