### ISSUE TITLE
CMakelist Error No Target File When Building gRPC

### ISSUE THREAD

**Issue by advra** [microsoft/vcpkg#14169]
I have a makelist which works great for unix and windows but not atypical systems such as raspbian which require building from source. It looks like VCPKG provides some configuration settings that must be applied to the CMakeLists. 

Below are the following CMake settings required after installing `grpc` and `protobuf` respectively:
```bash
# ./vcpkg install grpc
find_package(gRPC CONFIG REQUIRED)
# Note: 4 target(s) were omitted.
target_link_libraries(main PRIVATE gRPC::gpr gRPC::grpc gRPC::grpc++ gRPC::grpc++_alts)

find_package(modules CONFIG REQUIRED)
target_link_libraries(main PRIVATE c-ares::cares)

# ./vcpkg install protobuf
find_package(protobuf CONFIG REQUIRED)
target_link_libraries(main PRIVATE protobuf::libprotoc protobuf::libprotobuf protobuf::libprotobuf-lite)
```
My assumption was to place these at the root CMakelist.txt files but the target_link_libraries is performed within the CMakelist file in the `src` folder. Here is my CMakelists.txt: https://github.com/advra/grpc-vcpkg-boilerplate-example/blob/main/src/CMakeLists.txt

I have attempted to modify the grpc makelist provided by their grpc library but run into the following errors. Note: I suppressed most of the errors as they are looped for each source file in the project.
```
pi@raspaa:~/Desktop/grpc-vcpkg-boilerplate-example/build $ cmake .. -DCMAKE_TOOLCHAIN_FILE=/home/pi/vcpkg/scripts/buildsystems/vcpkg.cmake
-- Found protoc program: /home/pi/vcpkg/installed/arm-linux/tools/protobuf/protoc
CMake Warning at protos/CMakeLists.txt:15 (message):
  The grpc_cpp_plugin plugin was not found, the gRPC classes are not being
  generated


-- Using protobuf 3.13.0.0
-- Using gRPC 1.32.0
-- Configuring done
CMake Error at src/CMakeLists.txt:138 (add_custom_command):
  Error evaluating generator expression:

    $<TARGET_FILE:gRPC::grpc_cpp_plugin>

  No target "gRPC::grpc_cpp_plugin"

CMake Error at /home/pi/vcpkg/scripts/buildsystems/vcpkg.cmake:399 (_add_executable):
  Target "greeter_server" links to target "gRPC::grpc++_reflection" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  src/CMakeLists.txt:155 (add_executable)


CMake Error at /home/pi/vcpkg/scripts/buildsystems/vcpkg.cmake:399 (_add_executable):
  Target "greeter_server" links to target "PRIVATE gRPC::gpr gRPC::grpc
  gRPC::grpc++ gRPC::grpc++_alts PRIVATE c-ares::cares" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  src/CMakeLists.txt:155 (add_executable)


CMake Error at /home/pi/vcpkg/scripts/buildsystems/vcpkg.cmake:399 (_add_executable):
  Target "greeter_server" links to target "PRIVATE protobuf::libprotoc
  protobuf::libprotobuf protobuf::libprotobuf-lite" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  src/CMakeLists.txt:155 (add_executable)

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

**Comment by NancyLi1013** [comment]
Hi @advra 
Thanks for posting this issue.

```
pi@raspaa:~/Desktop/grpc-vcpkg-boilerplate-example/build $ cmake .. -DCMAKE_TOOLCHAIN_FILE=/home/pi/vcpkg/scripts/buildsystems/vcpkg.cmake
-- Found protoc program: /home/pi/vcpkg/installed/arm-linux/tools/protobuf/protoc
CMake Warning at protos/CMakeLists.txt:15 (message):
  The grpc_cpp_plugin plugin was not found, the gRPC classes are not being
  generated
```
Do you use the triplet `arm-linux` to build your project?

**Comment by xieyubo** [comment]
Seems related to issue #14170

**Comment by advra** [comment]
_Some detail I left out:  I am unable to use vcpkg after install unless I set this variable `export VCPKG_FORCE_SYSTEM_BINARIES=1`. vcpkg was installed with `./bootstrap-vcpkg.sh -disableMetrics`. I am unsure if the installation method of my vcpkg affects the build of packages so I thought it was noteworthy.

Prior to building grpc the the dependency package `vcpkg/packages/protobuf_arm-linux/tools/protobuf` seemed incomplete as well. Protobuf should be used by grp to specify .proto files to be included in the build. But I had to manually build my protos with protoc with `protoc -I=external/protos --cpp_out=build/external/protos/ external/protos/station.proto`_

> Do you use the triplet `arm-linux` to build your project?
@NancyLi1013 that is correct. I build project with `DVCPKG_TARGET_TRIPLET=arm-linux`.

**Comment by NancyLi1013** [comment]
@xieyubo 
Thanks for your reminder and fix.

@advra 
Thanks for your detailed description.

Currently, we mainly support the triplets that listed in https://github.com/microsoft/vcpkg/tree/master/triplets folder.

For these triplets in https://github.com/microsoft/vcpkg/tree/master/triplets/community folder, we don't support them yet. So we cannot make sure if all ports can work fine now.

In your case, since you used `arm-linux` that is in community folder, which is unofficial triplets.

Could you please try to rebuild this based on the PR #14184 submitted by @xieyubo?

**Comment by advra** [comment]
@NancyLi1013  thank you for the clarification on official and community triplets. I was able to build the missing plugins using the pull request submitted by @xieyubo.

Thanks!

**Comment by NancyLi1013** [comment]
@advra 
Thanks for your feedback. 
Since PR #14184 as been merged to master now. This issue should be fixed.

So I'm closing this issue for now.
