### ISSUE TITLE
vcpkg install libyuv:x64-windows failed, could you help me?

### ISSUE THREAD

**Issue by chris-shenzhen-china** [microsoft/vcpkg#14173]
When asking a question please also include where you looked for an answer (so we can update the documentation if needed).
vcpkg install libyuv:x64-windows failed, could you help me?

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Could you please provide the error log?

**Comment by chris-shenzhen-china** [comment]
D:\project-vs\vcpkg\vcpkg>vcpkg install libyuv:x64-windows
Computing installation plan...
The following packages will be built and installed:
    libyuv[core]:x64-windows
Detecting compiler hash for triplet x64-windows...
Starting package 1/1: libyuv:x64-windows
Building package libyuv[core]:x64-windows...
Could not locate cached archive: C:\Users\test\AppData\Local\vcpkg\archives\be\beee223c4a5cf2192cea1773a3de0322a0a9244e.zip
-- Note: libyuv only supports static library linkage. Building static library.
-- Fetching https://chromium.googlesource.com/libyuv/libyuv...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:85 (message):
    Command failed: D:/project-vs/vcpkg/vcpkg/downloads/tools/git-2.26.2-1-windows/mingw32/bin/git.exe fetch https://chromium.googlesource.com/libyuv/libyuv fec9121b676eccd9acea2460aec7d6ae219701b9 --depth 1 -n
    Working Directory: D:/project-vs/vcpkg/vcpkg/downloads/git-tmp
    Error code: 128
    See logs for more information:
      D:\project-vs\vcpkg\vcpkg\buildtrees\libyuv\git-fetch-x64-windows-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_git.cmake:77 (vcpkg_execute_required_process)
  ports/libyuv/portfile.cmake:3 (vcpkg_from_git)
  scripts/ports.cmake:79 (include)


Error: Building package libyuv:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libyuv:x64-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.

D:\project-vs\vcpkg\vcpkg>

**Comment by chris-shenzhen-china** [comment]
here is the error info in cenos:
[root@centos-hw vcpkg]# ./vcpkg install libyuv:x64-linux
Computing installation plan...
The following packages will be built and installed:
    libyuv[core]:x64-linux
Detecting compiler hash for triplet x64-linux...
Starting package 1/1: libyuv:x64-linux
Building package libyuv[core]:x64-linux...
Could not locate cached archive: /root/.cache/vcpkg/archives/0e/0eefd120853f0fdf54bd2b5a7669844b30e53e4e.zip
-- Fetching https://chromium.googlesource.com/libyuv/libyuv...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:85 (message):
    Command failed: /usr/local/bin/git fetch https://chromium.googlesource.com/libyuv/libyuv fec9121b676eccd9acea2460aec7d6ae219701b9 --depth 1 -n
    Working Directory: /data/vcpkg/downloads/git-tmp
    Error code: 128
    See logs for more information:
      /data/vcpkg/buildtrees/libyuv/git-fetch-x64-linux-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_git.cmake:77 (vcpkg_execute_required_process)
  ports/libyuv/portfile.cmake:3 (vcpkg_from_git)
  scripts/ports.cmake:79 (include)


Error: Building package libyuv:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libyuv:x64-linux
  Vcpkg version: 2020.06.15-unknownhash

Additionally, attach any relevant sections from the log files above.
[root@centos-hw vcpkg]#

**Comment by LilyWangL** [comment]
Thanks for your reply. Could you please provide the log: `D:\project-vs\vcpkg\vcpkg\buildtrees\libyuv\git-fetch-x64-windows-err.log` and `/data/vcpkg/buildtrees/libyuv/git-fetch-x64-linux-err.log`? You can attach the log file on this page.

**Comment by NancyLi1013** [comment]
@chris-shenzhen-china 

Could you please help confirm which version of CMake you used?

Thanks.

**Comment by chris-shenzhen-china** [comment]
C:\vcpkg&gt;cmake --version
cmake version 3.18.4


CMake suite maintained and supported by Kitware (kitware.com/cmake).





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/vcpkg"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月12日(星期四) 下午3:47
收件人:&nbsp;"microsoft/vcpkg"<vcpkg@noreply.github.com&gt;;
抄送:&nbsp;"Lucky&amp;nbsp;Lee-0"<sz_lidong@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [microsoft/vcpkg] vcpkg install libyuv:x64-windows failed, could you help me? (#14173)





 
@chris-shenzhen-china
 
Could you please help confirm which version of CMake you used?
 
Thanks.

**Comment by chris-shenzhen-china** [comment]
I have already install libyuv ok,&nbsp;
The reason is maybe the&nbsp;network , I donwload the source from AWS server successfully, and then replace the download libyuv source, and then install ok.


anyway, thank you very much.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/vcpkg"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月12日(星期四) 下午3:47
收件人:&nbsp;"microsoft/vcpkg"<vcpkg@noreply.github.com&gt;;
抄送:&nbsp;"Lucky&amp;nbsp;Lee-0"<sz_lidong@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [microsoft/vcpkg] vcpkg install libyuv:x64-windows failed, could you help me? (#14173)





 
@chris-shenzhen-china
 
Could you please help confirm which version of CMake you used?
 
Thanks.

**Comment by NancyLi1013** [comment]
Thanks for your update. 

I'm closing this issue for now since you have solved your problem.
