### ISSUE TITLE
[pdal] build failure

### ISSUE THREAD

**Issue by sweco-nlahoo** [microsoft/vcpkg#14182]
**Host Environment**
- OS: Xubuntu 20.04
- Compiler: gcc 9.3.0

**To Reproduce**
`./vcpkg install pdal:x64-linux`

**Failure logs** 
See attachment for a log from a first attempt
[install-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/5429485/install-x64-linux-dbg-out.log)

**Additional context**
I tried quickly fixing it by getting rid of the warnings, by passing -Wno-* flags to the compiler, which eventually made me get rid of the compile issues but then linker issues arose ...

**Comment by GeorgeR** [comment]
On the top of my list for Saturday :+1:
