### ISSUE TITLE
How do I request different library linkage with manifest?

### ISSUE THREAD

**Issue by xandox** [microsoft/vcpkg#14197]
Hi all.

I have following situation. I use vcpkg with manifest mode and I prefer to use x64-windows-static-md triplet. But for some reasons, I need some libraries built as dynamic libraries. For example I have some binary proprietary library which depend on other libraries which could be installed with vcpkg but it required them as dll. As far as I can see right now it's impossible to install dependency with different library linkage with manifest (not sure about manual mode). But may be there is other ways to solve this problem?

**Comment by Neumann-A** [comment]
You want to define a custom triplet with per port customization.  https://vcpkg.readthedocs.io/en/latest/users/triplets/

**Comment by xandox** [comment]
@Neumann-A  thank you very match. It's what I looked for!

**Comment by jajabu33** [comment]
@xandox i'm having the same issue, could you share how you fixed it?
@Neumann-A your link is off.

**Comment by Neumann-A** [comment]
@jajabu33: google can actually help to retrieve the current link to the documentation if given the keywords: `user triplets vcpkg`
https://learn.microsoft.com/en-us/vcpkg/users/triplets#per-port-customization
