### ISSUE TITLE
[skyr-url] build failure

### ISSUE THREAD

**Issue by MFMokbel** [microsoft/vcpkg#14198]
**Host Environment**
- OS: Windows 10 Enterprise
- Compiler: MSVC Enterprise 2017 (version 15.9.28)

**To Reproduce**
`./vcpkg install skyr-url`

**Failure logs** 
Computing installation plan...
The following packages will be built and installed:
    skyr-url[core]:x86-windows
Detecting compiler hash for triplet x86-windows...
Starting package 1/1: skyr-url:x86-windows
Building package skyr-url[core]:x86-windows...
Could not locate cached archive: C:\Users\M. F. Mokbel\AppData\Local\vcpkg\archives\17\1708472a16f3aebb76d29b50113fadd73e25d85e.zip
-- Note: skyr-url only supports static library linkage. Building static library.
-- Using cached C:/vcpkg/downloads/cpp-netlib-url-v1.13.0.tar.gz
-- Cleaning sources at C:/vcpkg/buildtrees/skyr-url/src/v1.13.0-654c69c924.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg/downloads/cpp-netlib-url-v1.13.0.tar.gz
-- Using source at C:/vcpkg/buildtrees/skyr-url/src/v1.13.0-654c69c924.clean
-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:141 (message):
    Command failed: C:/vcpkg/downloads/tools/cmake-3.18.4-windows/cmake-3.18.4-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v -j9
    Working Directory: C:/vcpkg/buildtrees/skyr-url/x86-windows-dbg
    See logs for more information:
      C:\vcpkg\buildtrees\skyr-url\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:92 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/skyr-url/portfile.cmake:21 (vcpkg_install_cmake)
  scripts/ports.cmake:79 (include)

Error: Building package skyr-url:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: skyr-url:x86-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.

**Additional context**
The issue seems to be related to cmake.
No issues building dependencies though!
Attached is the build log.
[install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/5433297/install-x86-windows-dbg-out.log)

**Comment by cngzhnp** [comment]
Seems from log output, range-v3 library requires VS2019 and you're using VS2017 on this case. I'd recommended you to update your build environment.

**Comment by MFMokbel** [comment]
This is weird, since I'm able to build range-v3 independently with no errors.

**Comment by MFMokbel** [comment]
I confirm a successful build with Visual Studio 2019.

**Comment by MFMokbel** [comment]
Closing case since there is nothing that can be done at the vcpkg level.
