### ISSUE TITLE
Can support mips arch?

### ISSUE THREAD

**Issue by mllw** [microsoft/vcpkg#14191]

**Comment by BillyONeal** [comment]
We don't have any mips hardware to test with and it's likely that some of our dependencies like cmake aren't available there either, but there's no reason in principle why it wouldn't work there.

**Comment by mllw** [comment]
Ok thanks.

**Comment by capric8416** [comment]
Add support in following prs: [vcpkg-pr-34392](https://github.com/microsoft/vcpkg/pull/34392) [vcpkg-tool-pr-1226](https://github.com/microsoft/vcpkg-tool/pull/1226)
