### ISSUE TITLE
How do I use vcpkg in macos HighSierra? 

### ISSUE THREAD

**Issue by Alvaroalloc** [microsoft/vcpkg#14204]
When asking a question please also include where you looked for an answer (so we can update the documentation if needed).
I have looked in https://github.com/microsoft/vcpkg for this thing but I get this error when i try to use cmake:

I put:
cmake -B [build directory] -S . -DCMAKE_TOOLCHAIN_FILE=[path to vcpkg]/scripts/buildsystems/vcpkg.cmake

and i get this error:
CMake Error: The source directory "/Users/macuser/vcpkg]/scripts/buildsystems/vcpkg.cmake" does not exist.

i think it is for the ']' but when i put the full path (/Users/macuser/vcpkg/scripts/buildsystems/vcpkg.cmake) i get this:

CMake Error: The source directory "/Users/macuser" does not appear to contain CMakeLists.txt.

Help me!! I've been stuck in this for months

**Comment by JackBoosY** [comment]
cc @strega-nil

**Comment by strega-nil** [comment]
@Alvaroalloc It seems like you're not trying to build a project? You need to be in the project directory (the directory that contains a CMakeLists.txt) for this command to work.

**Comment by Alvaroalloc** [comment]
Thank you, my bad
