### ISSUE TITLE
msys libiconv missing

### ISSUE THREAD

**Issue by linquize** [microsoft/vcpkg#14209]
**Host Environment**
- OS: Win 10 x64
- Compiler: VS2019

**To Reproduce**
`./vcpkg install openssl`

**Problem** 
Fail to download libiconv
`libiconv-1.16-1-x86_64.pkg.tar.xz` no longer present on the server.
The new file name is `libiconv-1.16-2-x86_64.pkg.tar.zst`

**Comment by fabiencastan** [comment]
Same problem.
