### ISSUE TITLE
Mlpack build failure

### ISSUE THREAD

**Issue by turska79** [microsoft/vcpkg#14216]
**Host Environment**
- OS: Windows

**To Reproduce**
`./vcpkg install mlpack

**Failure logs** 
Dependency gfortran:x64-windows produces following error:
Downloading https://repo.msys2.org/msys/x86_64/libiconv-1.16-1-x86_64.pkg.tar.xz...
-- Downloading https://repo.msys2.org/msys/x86_64/libiconv-1.16-1-x86_64.pkg.tar.xz... Failed. Status: 22;"HTTP response code said error"

**Additional context**
Reason being that https://repo.msys2.org doenst contain version 1.16-1. It has only version 1.16-2?

**Comment by turska79** [comment]
This thing seemed to fix that https://github.com/microsoft/vcpkg/commit/59ea3ff752d5e8415062e9a733eafd927849667e

**Comment by PhoebeHui** [comment]
This issue would be fixed by PR https://github.com/microsoft/vcpkg/pull/14220

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/14209.
