### ISSUE TITLE
error while build libmysql for x64-windows-static-md

### ISSUE THREAD

**Issue by jsnhsu** [microsoft/vcpkg#14218]
It shows Error: Building package icu:x64-windows-static-md failed with: BUILD_FAILED****

**Comment by sfhacker** [comment]
Quite 'verbose' error message!

**Comment by FusixGit** [comment]
https://github.com/microsoft/vcpkg/pull/14220/commits/59ea3ff752d5e8415062e9a733eafd927849667e

This fix will help. Modify vcpkg_acquire_msys.cmake manually

**Comment by jsnhsu** [comment]
@FusixGit Thanks, it works
