### ISSUE TITLE
[pthreads opencv[ffmpeg]] build failure

### ISSUE THREAD

**Issue by yzich** [microsoft/vcpkg#14212]
**Host Environment**
- OS: Windows 10
- Compiler: msvc19

**To Reproduce**
`.\vcpkg install pthreads opencv[ffmpeg]`

**Failure logs** 
![image](https://user-images.githubusercontent.com/73416934/97101738-53cfc280-16d2-11eb-828a-4856bff9a796.png)

**Additional context**
I was trying to install darknet on windows using tutorial from medium.com

**Comment by sfhacker** [comment]
We have had no issues building pthreads from source on Windows.
Most probably your environment is broken somehow!

**Comment by yzich** [comment]
Is there any suggestion to how can i fix that broken environment?

**Comment by eburshaid** [comment]
I get the same issue when i tried to install darknet, any help ?

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/14209.
