### ISSUE TITLE
[ LibFTDI1 ] Update to version 1.5 

### ISSUE THREAD

**Issue by daniellongstreet** [microsoft/vcpkg#14214]
Hi, 

LibFTDI version 1.5 was released on 7/7/2020. I not sure exactly how to request an update so I thought I would start here.

https://www.intra2net.com/en/developer/libftdi/index.php

Thanks!
Daniel

**Comment by Mixaill** [comment]
Some notes:

* new functions which were added in v1.5 are missing in .def file
* find_package(libftdi1) is broken in this port

You can see my fixes here: https://github.com/Mixaill/vcpkg/commit/d41b49d11396d50c24c7698223197c22c267eda9

**Comment by JonLiu1993** [comment]
Fix by #15918
