### ISSUE TITLE
[tesseract:x86-windows-static] header not found

### ISSUE THREAD

**Issue by HoLue** [microsoft/vcpkg#14229]
Hi!

I installed tesseract (4.1.1) via vcpkg:
`vcpkg install tesseract:x86-windows-static`
This worked..., I got at the end:
```
The package tesseract:x86-windows-static provides CMake targets:

    find_package(Tesseract CONFIG REQUIRED)
    target_link_libraries(main PRIVATE libtesseract)
```
Now I wanted to include the header in a new console program (Debug, x86, C++)
`#include <tesseract/apitypes.h>`
but I got errors E1696 and C1083 - file seems to be missing....
In my vcpkg directory the file is there
`installed\x86-windows-static\include\tesseract\apitypes.h`

Remark: Comparing to other packages, e.g. OpenCV I can just include the header files.., e.g.
#include <opencv2/core.hpp>
which lies also in my vcpkg directory:
`installed\x86-windows-static\include\opencv2\core.hpp`

What's going wrong here? Maybe the message ...CONFIG REQUIRED (see above) is essential, but what must I do???

Please help....

**Comment by JackBoosY** [comment]
For msvc project, if you want to use the static library, please modify your `.vcxproj` and add the following content:
```
  <PropertyGroup Label="Globals">
...
    <VcpkgTriplet Condition="'$(Platform)'=='Win32'">x86-windows-static</VcpkgTriplet>
    <VcpkgTriplet Condition="'$(Platform)'=='x64'">x64-windows-static</VcpkgTriplet>
...
  </PropertyGroup>
```

See [documentation](https://github.com/microsoft/vcpkg/blob/5c056a65bb316f0114f536fdbb04f344b84d38c3/docs/users/integration.md#with-msbuild).

**Comment by HoLue** [comment]
Thanks a lot!! it worked!
