### ISSUE TITLE
[Qt] The _debug suffix added to .pc files renders them undetectable by pkg-config

### ISSUE THREAD

**Issue by wrobelda** [microsoft/vcpkg#14225]
**Describe the bug**

I have filed a MR for GpgMe libraries (https://github.com/microsoft/vcpkg/pull/13950), which work fine except if built with additional Qt feature.

The build fails at `Configuring x64-osx-dbg` with:

```
checking for GPGME_QT... no
```
, which corresponds to these lines in `configure` script:

`PKG_CONFIG --exists --print-errors \"Qt5Core >= 5.0.0\"`

, and to these lines in `config.log`:

```
configure:19242: checking for GPGME_QT
configure:19250: $PKG_CONFIG --exists --print-errors "Qt5Core >= 5.0.0"
Package Qt5Core was not found in the pkg-config search path.
Perhaps you should add the directory containing `Qt5Core.pc'
to the PKG_CONFIG_PATH environment variable
No package 'Qt5Core' found
configure:19253: $? = 1
```

The PKG_CONFIG variable is defined by [vcpkg_configure_make](https://github.com/microsoft/vcpkg/blob/b97849d25804ca06125f6d311c7139df1339b84c/scripts/cmake/vcpkg_configure_make.cmake#L530) as following at the runtime:

`set(ENV{PKG_CONFIG} "${PKGCONFIG} --define-variable=prefix=${_VCPKG_INSTALLED}${PATH_SUFFIX_${_buildtype}}")`

, which for `x64-osx-dbg` buildtype resolves to:

`PKG_CONFIG_PATH=/vcpkg_installed/x64-osx/debug/lib/pkgconfig:/vcpkg_installed/x64-osx/share/pkgconfig`

Now, the `/vcpkg_installed/x64-osx/debug/lib/pkgconfig` has all of Qt pkgconfig files needed, except all of them have a `_debug` suffix added, e.g. `Qt5Core_debug.pc`, which explains why pkgconfig cannot find them. For the record, according to the pkgconfig spec, the filenames _must_ correspond to the module name, so in this case `Qt5Core_debug` != `Qt5Core`.

**Environment**
- OS: macOS

**To Reproduce**
1. ./vcpkg install gpgme[qt]
2. See error

**Expected behavior**
`.pc` files in `/vcpkg_installed/*/debug/lib/pkgconfig` should not have their names changed in order for pkgconfig to correctly detect them when executed by ports depending on Qt.

**Comment by JackBoosY** [comment]
cc @Neumann-A

**Comment by Neumann-A** [comment]
currently `vcpkg_fixup_pkgconfig` is not even called on the `*.pc` files of Qt so I would not use them anyway.
So the todo would be:
- add `vcpkg_fixup_pkgconfig()` to qt.
- figure out why the pc files have a `_debug` suffix.
- make sure that the libraries still have the `_debug` suffix for debug only builds. (Qt build is a bit annyoing here since it removes debug suffixes in single configuration builds.)

**Comment by wrobelda** [comment]
@Neumann-A is there by chance any update of any of these work items?

**Comment by Neumann-A** [comment]
No i dont have an osx machine so even if I do the changes I cannot test them. Somebody who needs these changes should do them and open up an PR for it.
