### ISSUE TITLE
Specify local file with `vcpkg create'

### ISSUE THREAD

**Issue by Maktm** [microsoft/vcpkg#1423]
Hi,

Is it possible to provide a local file to the `vcpkg create` command and then possibly change the target URL in the future when I upload the project to a global URL?

Thanks

**Comment by ras0219-msft** [comment]
We don't currently support local files as arguments to `vcpkg create`, however you could edit the resulting portfile to directly unpack a local archive:
```cmake
vcpkg_extract_source_archive(C:/local/path/to/project.zip)
```
Note that the extract source archive command does invalidation based on the name of the file, so if you're updating the file in place you probably want to also purge the sources on every run.
```cmake
# Do this before vcpkg_extract_source_archive
file(REMOVE_RECURSE ${CURRENT_BUILDTREES_DIR}/src)
```
When you upload your project to a global URL, you can simply add a `vcpkg_download_distfile` or `vcpkg_from_github` directive above the extract step.

**Comment by LilyWangL** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen.

**Comment by Coderx7** [comment]
Hi, Is there any update on this? its been more  than 3 years now. 
Having this capability would be greatly appreciated
