### ISSUE TITLE
ompl[app] build failure

### ISSUE THREAD

**Issue by hortegilles** [microsoft/vcpkg#14236]
**Host Environment**
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: ompl:x86-windows
  Vcpkg version: 2020.06.15-nohash

**To Reproduce**
`vcpkg install ompl[app]`

**Failure logs** 

> Computing installation plan...
> The following packages will be built and installed:
>     ompl[app,core]:x86-windows
> Detecting compiler hash for triplet x86-windows...
> Starting package 1/1: ompl:x86-windows
> Building package ompl[app,core]:x86-windows...
> Could not locate cached archive: C:\Users\gh7\AppData\Local\vcpkg\archives\eb\eb61858ccc2af961a34dad08c6886acf4dccd06d.zip
> -- Using cached E:/WS/vcpkg/downloads/omplapp-1.5.0.tar.gz
> -- Cleaning sources at E:/WS/vcpkg/buildtrees/ompl/src/1.5.0-05dfb62559.clean. Use --editable to skip cleaning for the packages you specify.
> -- Extracting source E:/WS/vcpkg/downloads/omplapp-1.5.0.tar.gz
> -- Using source at E:/WS/vcpkg/buildtrees/ompl/src/1.5.0-05dfb62559.clean
> -- Configuring x86-windows-dbg
> CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:85 (message):
>     Command failed: E:/WS/vcpkg/downloads/tools/cmake-3.18.4-windows/cmake-3.18.4-win32-x86/bin/cmake.exe E:/WS/vcpkg/buildtrees/ompl/src/1.5.0-05dfb62559.clean -DOMPL_VERSIONED_INSTALL=OFF -DOMPL_REGISTRATION=OFF -DOMPL_BUILD_DEMOS=OFF -DOMPL_BUILD_TESTS=OFF -DOMPL_BUILD_PYBINDINGS=OFF -DOMPL_BUILD_PYTESTS=OFF -DCMAKE_MAKE_PROGRAM=E:/WS/vcpkg/downloads/tools/ninja/1.10.1-windows/ninja.exe -DBUILD_SHARED_LIBS=ON -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=E:/WS/vcpkg/scripts/toolchains/windows.cmake -DVCPKG_TARGET_TRIPLET=x86-windows -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=v141 -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=E:/WS/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_LINKER_FLAGS_RELEASE= -DVCPKG_LINKER_FLAGS_DEBUG= -DVCPKG_TARGET_ARCHITECTURE=x86 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -D_VCPKG_ROOT_DIR=E:/WS/vcpkg -D_VCPKG_INSTALLED_DIR=E:/WS/vcpkg/installed -DVCPKG_MANIFEST_INSTALL=OFF -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=E:/WS/vcpkg/packages/ompl_x86-windows/debug
>     Working Directory: E:/WS/vcpkg/buildtrees/ompl/x86-windows-dbg
>     Error code: 1
>     See logs for more information:
>       E:\WS\vcpkg\buildtrees\ompl\config-x86-windows-dbg-out.log
>       E:\WS\vcpkg\buildtrees\ompl\config-x86-windows-dbg-err.log
> 
> Call Stack (most recent call first):
>   scripts/cmake/vcpkg_configure_cmake.cmake:321 (vcpkg_execute_required_process)
>   ports/ompl/portfile.cmake:31 (vcpkg_configure_cmake)
>   scripts/ports.cmake:79 (include)
> 
> 
> Error: Building package ompl:x86-windows failed with: BUILD_FAILED

**Additional context**
`vcpkg install ompl` core lib only is OK but [app] generate the error
[config-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/5439604/config-x86-windows-dbg-out.log)
[config-x86-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/5439605/config-x86-windows-dbg-err.log)
[stdout-x86-windows.log](https://github.com/microsoft/vcpkg/files/5439609/stdout-x86-windows.log)

**Comment by hortegilles** [comment]
similar issue on CentOS Linux 7 (Core)

vcpkg install ompl[app] OK
vcpkg install ompl OK

> CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:85 (message):
>     Command failed: /home/moo/dev/vcpkg/downloads/tools/cmake-3.18.4-linux/cmake-3.18.4-Linux-x86_64/bin/cmake /home/moo/dev/vcpkg/buildtrees/ompl/src/1.5.0-05dfb62559.clean -DOMPL_VERSIONED_INSTALL=OFF -DOMPL_REGISTRATION=OFF -DOMPL_BUILD_DEMOS=OFF -DOMPL_BUILD_TESTS=OFF -DOMPL_BUILD_PYBINDINGS=OFF -DOMPL_BUILD_PYTESTS=OFF -DCMAKE_MAKE_PROGRAM=/home/moo/dev/vcpkg/downloads/tools/ninja-1.10.1-linux/ninja -DCMAKE_SYSTEM_NAME=Linux -DBUILD_SHARED_LIBS=OFF -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/home/moo/dev/vcpkg/scripts/toolchains/linux.cmake -DVCPKG_TARGET_TRIPLET=x64-linux -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=external -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=/home/moo/dev/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_LINKER_FLAGS_RELEASE= -DVCPKG_LINKER_FLAGS_DEBUG= -DVCPKG_TARGET_ARCHITECTURE=x64 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -D_VCPKG_ROOT_DIR=/home/moo/dev/vcpkg -D_VCPKG_INSTALLED_DIR=/home/moo/dev/vcpkg/installed -DVCPKG_MANIFEST_INSTALL=OFF -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/home/moo/dev/vcpkg/packages/ompl_x64-linux/debug
>     Working Directory: /home/moo/dev/vcpkg/buildtrees/ompl/x64-linux-dbg
>     Error code: 1
>     See logs for more information:
>       /home/moo/dev/vcpkg/buildtrees/ompl/config-x64-linux-dbg-out.log
>       /home/moo/dev/vcpkg/buildtrees/ompl/config-x64-linux-dbg-err.log
> 
> Call Stack (most recent call first):
>   scripts/cmake/vcpkg_configure_cmake.cmake:321 (vcpkg_execute_required_process)
>   ports/ompl/portfile.cmake:31 (vcpkg_configure_cmake)
>   scripts/ports.cmake:79 (include)
> 
> 
> Error: Building package ompl:x64-linux failed with: BUILD_FAILED
> Please ensure you're using the latest portfiles with `./vcpkg update`, then
> submit an issue at https://github.com/Microsoft/vcpkg/issues including:
>   Package: ompl:x64-linux
>   Vcpkg version: 2020.06.15-unknownhash

**Comment by PhoebeHui** [comment]
@hortegilles, thanks for reporting this issue!

Failures:
CMake Error at CMakeLists.txt:177 (include_directories):
  include_directories given empty-string as include directory.

**Comment by hortegilles** [comment]
thx for the fix on windows the build seems OK 

but on centos I still have an issue 

Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-linux...
Starting package 1/103: minizip:x64-linux
Building package minizip[core]:x64-linux...
Could not locate cached archive: /u/users/cgacxr1/.cache/vcpkg/archives/df/dfd72fa500b74cefd09242cdfa01913869d99ba3.zip
-- Using cached /home/duplo/ws/vcpkg/downloads/madler-zlib-v1.2.11.tar.gz
-- Cleaning sources at /home/duplo/ws/vcpkg/buildtrees/minizip/src/v1.2.11-a5237a6809.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/duplo/ws/vcpkg/downloads/madler-zlib-v1.2.11.tar.gz
-- Applying patch 0001-remove-ifndef-NOUNCRYPT.patch
-- Applying patch 0002-add-declaration-for-mkdir.patch
-- Using source at /home/duplo/ws/vcpkg/buildtrees/minizip/src/v1.2.11-a5237a6809.clean
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
CMake Error at scripts/cmake/vcpkg_copy_tool_dependencies.cmake:22 (message):
  Could not find PowerShell Core; please open an issue to report this.
Call Stack (most recent call first):
  ports/minizip/portfile.cmake:35 (vcpkg_copy_tool_dependencies)
  scripts/ports.cmake:135 (include)


Error: Building package minizip:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: minizip:x64-linux
  Vcpkg version: 2020.06.15-unknownhash

Additionally, attach any relevant sections from the log files above.

**Comment by PhoebeHui** [comment]
@hortegilles, please report a new issue instead.

**Comment by BillyONeal** [comment]
@hortegilles That sounds like https://github.com/microsoft/vcpkg/issues/14267 ?

**Comment by PhoebeHui** [comment]
@hortegilles, it looks same issue with https://github.com/microsoft/vcpkg/issues/14358
