### ISSUE TITLE
How do I use libraries of vcpkg with cmake?

### ISSUE THREAD

**Issue by Alvaroalloc** [microsoft/vcpkg#14258]
I'm new at vcpkg this world but i want to use libmariadb.
I already setted up my enviromnet but i don't know how to configure my CMakeLists.txt to make make it work.
I found some documentation that asks to use find_package(mariadb CONFIG REQUIRED) but its shows that theres no configuration file named mariadb-config.cmake or mariadbConfig.cmake

I'm sure it is easy but up to now i cant use any package of vcpkg

**Comment by vicroms** [comment]
As per the README, you have to set the toolchain file when invoking cmake:

```
cmake -B [build directory] -S . -DCMAKE_TOOLCHAIN_FILE=[path to vcpkg]/scripts/buildsystems/vcpkg.cmake
cmake --build [build directory]
```

**Comment by Alvaroalloc** [comment]
I've done that what i want to do is how to use the libraries in CMakeLists
I think with the toochain you only include the paths and configs, but you have to set the libraries to use in the CMakeLists.txt

**Comment by vicroms** [comment]
Hi @Alvaroalloc 

Not all libraries in vcpkg offer CMake integration support (such support depends on the library maintainers, not on vcpkg). In the case off `libmariadb` you must manually link the library and include files in your `CMakeLists.txt`. 

Here is an example of how to use packages with and without `find_package()` support. You can read more about this topic in [our documentation](https://github.com/microsoft/vcpkg/blob/master/docs/examples/installing-and-using-packages.md).

`CMakeLists.txt`
```cmake
cmake_minimum_required(VERSION 3.14)
project(example CXX)

add_executable(example main.cpp)

# With CMake integration
find_package(fmt CONFIG REQUIRED)

# Without CMake integration
find_path(LIBMARIADB_INCLUDE_DIR mysql/mariadb_version.h)
find_library(LIBMARIADB_LIBRARY libmariadb)

target_include_directories(example PRIVATE ${LIBMARIADB_INCLUDE_DIR})
target_link_libraries(example PRIVATE ${LIBMARIADB_LIBRARY} fmt::fmt)
```

**Comment by Alvaroalloc** [comment]
thank you a lot

**Comment by Alvaroalloc** [comment]
Hey now i've done that but it shows me this:

`[build] [ 50%] Linking CXX executable sql
[build] Undefined symbols for architecture x86_64:
[build]   "_OPENSSL_init_ssl", referenced from:
[build]       _ma_tls_start in libmariadb.a(openssl.c.o)
[build]   "_OpenSSL_version", referenced from:
[build]       _ma_tls_start in libmariadb.a(openssl.c.o)
[build]   "_SSL_CTX_set_options", referenced from:
[build]       _ma_tls_init in libmariadb.a(openssl.c.o)
[build]   "_X509_check_host", referenced from:
[build]       _ma_tls_verify_server_cert in libmariadb.a(openssl.c.o)
[build]   "_X509_check_ip_asc", referenced from:
[build]       _ma_tls_verify_server_cert in libmariadb.a(openssl.c.o)
[build] ld: symbol(s) not found for architecture x86_64
[build] collect2: error: ld returned 1 exit status
[build] make[3]: *** [sql] Error 1
[build] make[2]: *** [CMakeFiles/sql.dir/all] Error 2
[build] make[1]: *** [CMakeFiles/sql.dir/rule] Error 2
[build] make: *** [sql] Error 2`

**Comment by Alvaroalloc** [comment]
Now it shows this:
`
[build] Undefined symbols for architecture x86_64:
[build]   "_ERR_get_error", referenced from:
[build]       _ma_tls_init in libmariadb.a(openssl.c.o)
[build]       _ma_tls_connect in libmariadb.a(openssl.c.o)
[build]   "_ERR_peek_error", referenced from:
[build]       _ma_tls_init in libmariadb.a(openssl.c.o)
[build]   "_ERR_reason_error_string", referenced from:
[build]       _ma_tls_init in libmariadb.a(openssl.c.o)
[build]       _ma_tls_connect in libmariadb.a(openssl.c.o)
[build]   "_EVP_PKEY_free", referenced from:
[build]       _ma_tls_init in libmariadb.a(openssl.c.o)
[build]   "_EVP_PKEY_new", referenced from:
[build]       _ma_tls_init in libmariadb.a(openssl.c.o)
[build]   "_EVP_sha1", referenced from:
[build]       _ma_tls_get_finger_print in libmariadb.a(openssl.c.o)
[build]   "_OPENSSL_init_ssl", referenced from:
[build]       _ma_tls_start in libmariadb.a(openssl.c.o)
[build]   "_OpenSSL_version", referenced from:
[build]       _ma_tls_start in libmariadb.a(openssl.c.o)
[build]   "_PEM_read_PrivateKey", referenced from:
[build]       _ma_tls_init in libmariadb.a(openssl.c.o)
[build]   "_SSL_CIPHER_get_name", referenced from:
[build]       _ma_tls_get_cipher in libmariadb.a(openssl.c.o)
[build]   "_SSL_CTX_check_private_key", referenced from:
[build]       _ma_tls_init in libmariadb.a(openssl.c.o)
[build]   "_SSL_CTX_free", referenced from:
[build]       _ma_tls_init in libmariadb.a(openssl.c.o)
[build]       _ma_tls_close in libmariadb.a(openssl.c.o)
[build]   "_SSL_CTX_get_cert_store", referenced from:
[build]       _ma_tls_init in libmariadb.a(openssl.c.o)
[build]   "_SSL_CTX_load_verify_locations", referenced from:
[build]       _ma_tls_init in libmariadb.a(openssl.c.o)
[build]   "_SSL_CTX_new", referenced from:
[build]       _ma_tls_init in libmariadb.a(openssl.c.o)
[build]   "_SSL_CTX_set_cipher_list", referenced from:
[build]       _ma_tls_init in libmariadb.a(openssl.c.o)
[build]   "_SSL_CTX_set_default_verify_paths", referenced from:
[build]       _ma_tls_init in libmariadb.a(openssl.c.o)
[build]   "_SSL_CTX_set_options", referenced from:
[build]       _ma_tls_init in libmariadb.a(openssl.c.o)
[build]   "_SSL_CTX_set_verify", referenced from:
[build]       _ma_tls_init in libmariadb.a(openssl.c.o)
[build]   "_SSL_CTX_use_PrivateKey", referenced from:
[build]       _ma_tls_init in libmariadb.a(openssl.c.o)
[build]   "_SSL_CTX_use_certificate_chain_file", referenced from:
[build]       _ma_tls_init in libmariadb.a(openssl.c.o)
[build]   "_SSL_clear", referenced from:
[build]       _ma_tls_connect in libmariadb.a(openssl.c.o)
[build]   "_SSL_connect", referenced from:
[build]       _ma_tls_connect in libmariadb.a(openssl.c.o)
[build]   "_SSL_free", referenced from:
[build]       _ma_tls_init in libmariadb.a(openssl.c.o)
[build]       _ma_tls_close in libmariadb.a(openssl.c.o)
[build]   "_SSL_get_SSL_CTX", referenced from:
[build]       _ma_tls_close in libmariadb.a(openssl.c.o)
[build]   "_SSL_get_current_cipher", referenced from:
[build]       _ma_tls_get_cipher in libmariadb.a(openssl.c.o)
[build]   "_SSL_get_error", referenced from:
[build]       _ma_tls_connect in libmariadb.a(openssl.c.o)
[build]       _ma_tls_read_async in libmariadb.a(openssl.c.o)
[build]       _ma_tls_write_async in libmariadb.a(openssl.c.o)
[build]       _ma_tls_read in libmariadb.a(openssl.c.o)
[build]       _ma_tls_write in libmariadb.a(openssl.c.o)
[build]   "_SSL_get_ex_data", referenced from:
[build]       _ma_tls_connect in libmariadb.a(openssl.c.o)
[build]       _ma_tls_verify_server_cert in libmariadb.a(openssl.c.o)
[build]       _ma_tls_get_finger_print in libmariadb.a(openssl.c.o)
[build]   "_SSL_get_peer_certificate", referenced from:
[build]       _ma_tls_verify_server_cert in libmariadb.a(openssl.c.o)
[build]       _ma_tls_get_finger_print in libmariadb.a(openssl.c.o)
[build]   "_SSL_get_verify_result", referenced from:
[build]       _ma_tls_connect in libmariadb.a(openssl.c.o)
[build]   "_SSL_new", referenced from:
[build]       _ma_tls_init in libmariadb.a(openssl.c.o)
[build]   "_SSL_read", referenced from:
[build]       _ma_tls_read_async in libmariadb.a(openssl.c.o)
[build]       _ma_tls_read in libmariadb.a(openssl.c.o)
[build]   "_SSL_set_ex_data", referenced from:
[build]       _ma_tls_init in libmariadb.a(openssl.c.o)
[build]   "_SSL_set_fd", referenced from:
[build]       _ma_tls_connect in libmariadb.a(openssl.c.o)
[build]   "_SSL_set_quiet_shutdown", referenced from:
[build]       _ma_tls_close in libmariadb.a(openssl.c.o)
[build]   "_SSL_shutdown", referenced from:
[build]       _ma_tls_close in libmariadb.a(openssl.c.o)
[build]   "_SSL_version", referenced from:
[build]       _ma_tls_get_protocol_version in libmariadb.a(openssl.c.o)
[build]   "_SSL_write", referenced from:
[build]       _ma_tls_write_async in libmariadb.a(openssl.c.o)
[build]       _ma_tls_write in libmariadb.a(openssl.c.o)
[build]   "_TLS_client_method", referenced from:
[build]       _ma_tls_init in libmariadb.a(openssl.c.o)
[build]   "_X509_STORE_load_locations", referenced from:
[build]       _ma_tls_init in libmariadb.a(openssl.c.o)
[build]   "_X509_STORE_set_flags", referenced from:
[build]       _ma_tls_init in libmariadb.a(openssl.c.o)
[build]   "_X509_check_host", referenced from:
[build]       _ma_tls_verify_server_cert in libmariadb.a(openssl.c.o)
[build]   "_X509_check_ip_asc", referenced from:
[build]       _ma_tls_verify_server_cert in libmariadb.a(openssl.c.o)
[build]   "_X509_digest", referenced from:
[build]       _ma_tls_get_finger_print in libmariadb.a(openssl.c.o)
[build]   "_X509_free", referenced from:
[build]       _ma_tls_verify_server_cert in libmariadb.a(openssl.c.o)
[build]       _ma_tls_get_finger_print in libmariadb.a(openssl.c.o)
[build]   "_X509_verify_cert_error_string", referenced from:
[build]       _ma_tls_connect in libmariadb.a(openssl.c.o)
[build]   "_compress", referenced from:
[build]       __mariadb_compress in libmariadb.a(ma_compress.c.o)
[build]       __mariadb_compress_alloc in libmariadb.a(ma_compress.c.o)
[build]      (maybe you meant: __mariadb_compress_alloc, __mariadb_compress )
[build]   "_uncompress", referenced from:
[build]       __mariadb_uncompress in libmariadb.a(ma_compress.c.o)
[build]      (maybe you meant: __mariadb_uncompress)
[build] ld: symbol(s) not found for architecture x86_64
[build] collect2: error: ld returned 1 exit status
[build] make[3]: *** [sql] Error 1
[build] make[2]: *** [CMakeFiles/sql.dir/all] Error 2
[build] make[1]: *** [CMakeFiles/sql.dir/rule] Error 2
[build] make: *** [sql] Error 2
`

**Comment by PhoebeHui** [comment]
@Alvaroalloc, I can't repro this issue, what's test code in your .cpp file?

E:\vcpkg\vcpkgtest\libmariadb\build>cmake .. "-DCMAKE_TOOLCHAIN_FILE=E:/vcpkg/clean/vcpkg/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x64-windows -DVCPKG_BUILD_TYPE=debug -G "Visual Studio 16 2019"
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19042.
-- The CXX compiler identification is MSVC 19.27.29111.0
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    VCPKG_BUILD_TYPE


-- Build files have been written to: E:/vcpkg/vcpkgtest/libmariadb/build

E:\vcpkg\vcpkgtest\libmariadb\build>cmake --build .
Microsoft (R) Build Engine version 16.7.0+b89cb5fde for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  Building Custom Rule E:/vcpkg/vcpkgtest/libmariadb/CMakeLists.txt
  main.cpp
  example.vcxproj -> E:\vcpkg\vcpkgtest\libmariadb\build\Debug\example.exe
  Building Custom Rule E:/vcpkg/vcpkgtest/libmariadb/CMakeLists.txt

**Comment by vicroms** [comment]
`libmariadb` depends on OpenSSL and zlib, you may also need to link those

**Comment by Alvaroalloc** [comment]
@PhoebeHui my main.cpp is: 
`
#include <mysql/mysql.h>


using namespace std;


int main()
{

 MYSQL mysql;

 mysql_init(&mysql);
 mysql_options(&mysql,MYSQL_READ_DEFAULT_GROUP,"your_prog_name");
 if (!mysql_real_connect(&mysql,"host","user","passwd","database",0,NULL,0))
 {
     fprintf(stderr, "Failed to connect to database: Error: %s\n",
           mysql_error(&mysql));
 }
}`

**Comment by Alvaroalloc** [comment]
and my CMakeLists is: 
`
cmake_minimum_required(VERSION 3.14)
project(example CXX)
include_directories(/Users/macuser/vcpkg/installed/x64-osx/include)

find_path(LIBMARIADB_INCLUDE_DIR mysql/mysql.h)
find_library(LIBMARIADB_LIBRARY crypto ssl z mariadb )


add_executable(sql main.cpp)


target_include_directories(sql PRIVATE ${LIBMARIADB_INCLUDE_DIR})
target_link_libraries(sql PRIVATE ${LIBMARIADB_LIBRARY} )
`

**Comment by PhoebeHui** [comment]
@Alvaroalloc,  could you try this?

```
cmake_minimum_required(VERSION 3.14)
project(example CXX)

add_executable(example main.cpp)

find_path(LIBMARIADB_INCLUDE_DIR mysql/mysql.h)
find_library(LIBMARIADB_LIBRARY libmariadb)

target_include_directories(example PRIVATE ${LIBMARIADB_INCLUDE_DIR})
target_link_libraries(example PRIVATE ${LIBMARIADB_LIBRARY})
```

**Comment by Alvaroalloc** [comment]
I still get this:

`[build] Scanning dependencies of target sql
[build] [ 50%] Building CXX object CMakeFiles/sql.dir/main.cpp.o
[build] [100%] Linking CXX executable sql
[build] Undefined symbols for architecture x86_64:
[build]   "_ERR_get_error", referenced from:
[build]       _ma_tls_init in libmariadb.a(openssl.c.o)
[build]       _ma_tls_connect in libmariadb.a(openssl.c.o)
[build]   "_ERR_peek_error", referenced from:
[build]       _ma_tls_init in libmariadb.a(openssl.c.o)
[build]   "_ERR_reason_error_string", referenced from:
[build]       _ma_tls_init in libmariadb.a(openssl.c.o)
[build]       _ma_tls_connect in libmariadb.a(openssl.c.o)
[build]   "_EVP_PKEY_free", referenced from:
[build]       _ma_tls_init in libmariadb.a(openssl.c.o)
[build]   "_EVP_PKEY_new", referenced from:
[build]       _ma_tls_init in libmariadb.a(openssl.c.o)
[build]   "_EVP_sha1", referenced from:
[build]       _ma_tls_get_finger_print in libmariadb.a(openssl.c.o)
[build]   "_OPENSSL_init_ssl", referenced from:
[build]       _ma_tls_start in libmariadb.a(openssl.c.o)
[build]   "_OpenSSL_version", referenced from:
[build]       _ma_tls_start in libmariadb.a(openssl.c.o)
[build]   "_PEM_read_PrivateKey", referenced from:
[build]       _ma_tls_init in libmariadb.a(openssl.c.o)
[build]   "_SSL_CIPHER_get_name", referenced from:
[build]       _ma_tls_get_cipher in libmariadb.a(openssl.c.o)
[build]   "_SSL_CTX_check_private_key", referenced from:
[build]       _ma_tls_init in libmariadb.a(openssl.c.o)
[build]   "_SSL_CTX_free", referenced from:
[build]       _ma_tls_init in libmariadb.a(openssl.c.o)
[build]       _ma_tls_close in libmariadb.a(openssl.c.o)
[build]   "_SSL_CTX_get_cert_store", referenced from:
[build]       _ma_tls_init in libmariadb.a(openssl.c.o)
[build]   "_SSL_CTX_load_verify_locations", referenced from:
[build]       _ma_tls_init in libmariadb.a(openssl.c.o)
[build]   "_SSL_CTX_new", referenced from:
[build]       _ma_tls_init in libmariadb.a(openssl.c.o)
[build]   "_SSL_CTX_set_cipher_list", referenced from:
[build]       _ma_tls_init in libmariadb.a(openssl.c.o)
[build]   "_SSL_CTX_set_default_verify_paths", referenced from:
[build]       _ma_tls_init in libmariadb.a(openssl.c.o)
[build]   "_SSL_CTX_set_options", referenced from:
[build]       _ma_tls_init in libmariadb.a(openssl.c.o)
[build]   "_SSL_CTX_set_verify", referenced from:
[build]       _ma_tls_init in libmariadb.a(openssl.c.o)
[build]   "_SSL_CTX_use_PrivateKey", referenced from:
[build]       _ma_tls_init in libmariadb.a(openssl.c.o)
[build]   "_SSL_CTX_use_certificate_chain_file", referenced from:
[build]       _ma_tls_init in libmariadb.a(openssl.c.o)
[build]   "_SSL_clear", referenced from:
[build]       _ma_tls_connect in libmariadb.a(openssl.c.o)
[build]   "_SSL_connect", referenced from:
[build]       _ma_tls_connect in libmariadb.a(openssl.c.o)
[build]   "_SSL_free", referenced from:
[build]       _ma_tls_init in libmariadb.a(openssl.c.o)
[build]       _ma_tls_close in libmariadb.a(openssl.c.o)
[build]   "_SSL_get_SSL_CTX", referenced from:
[build]       _ma_tls_close in libmariadb.a(openssl.c.o)
[build]   "_SSL_get_current_cipher", referenced from:
[build]       _ma_tls_get_cipher in libmariadb.a(openssl.c.o)
[build]   "_SSL_get_error", referenced from:
[build]       _ma_tls_connect in libmariadb.a(openssl.c.o)
[build]       _ma_tls_read_async in libmariadb.a(openssl.c.o)
[build]       _ma_tls_write_async in libmariadb.a(openssl.c.o)
[build]       _ma_tls_read in libmariadb.a(openssl.c.o)
[build]       _ma_tls_write in libmariadb.a(openssl.c.o)
[build]   "_SSL_get_ex_data", referenced from:
[build]       _ma_tls_connect in libmariadb.a(openssl.c.o)
[build]       _ma_tls_verify_server_cert in libmariadb.a(openssl.c.o)
[build]       _ma_tls_get_finger_print in libmariadb.a(openssl.c.o)
[build]   "_SSL_get_peer_certificate", referenced from:
[build]       _ma_tls_verify_server_cert in libmariadb.a(openssl.c.o)
[build]       _ma_tls_get_finger_print in libmariadb.a(openssl.c.o)
[build]   "_SSL_get_verify_result", referenced from:
[build]       _ma_tls_connect in libmariadb.a(openssl.c.o)
[build]   "_SSL_new", referenced from:
[build]       _ma_tls_init in libmariadb.a(openssl.c.o)
[build]   "_SSL_read", referenced from:
[build]       _ma_tls_read_async in libmariadb.a(openssl.c.o)
[build]       _ma_tls_read in libmariadb.a(openssl.c.o)
[build]   "_SSL_set_ex_data", referenced from:
[build]       _ma_tls_init in libmariadb.a(openssl.c.o)
[build]   "_SSL_set_fd", referenced from:
[build]       _ma_tls_connect in libmariadb.a(openssl.c.o)
[build]   "_SSL_set_quiet_shutdown", referenced from:
[build]       _ma_tls_close in libmariadb.a(openssl.c.o)
[build]   "_SSL_shutdown", referenced from:
[build]       _ma_tls_close in libmariadb.a(openssl.c.o)
[build]   "_SSL_version", referenced from:
[build]       _ma_tls_get_protocol_version in libmariadb.a(openssl.c.o)
[build]   "_SSL_write", referenced from:
[build]       _ma_tls_write_async in libmariadb.a(openssl.c.o)
[build]       _ma_tls_write in libmariadb.a(openssl.c.o)
[build]   "_TLS_client_method", referenced from:
[build]       _ma_tls_init in libmariadb.a(openssl.c.o)
[build]   "_X509_STORE_load_locations", referenced from:
[build]       _ma_tls_init in libmariadb.a(openssl.c.o)
[build]   "_X509_STORE_set_flags", referenced from:
[build]       _ma_tls_init in libmariadb.a(openssl.c.o)
[build]   "_X509_check_host", referenced from:
[build]       _ma_tls_verify_server_cert in libmariadb.a(openssl.c.o)
[build]   "_X509_check_ip_asc", referenced from:
[build]       _ma_tls_verify_server_cert in libmariadb.a(openssl.c.o)
[build]   "_X509_digest", referenced from:
[build]       _ma_tls_get_finger_print in libmariadb.a(openssl.c.o)
[build]   "_X509_free", referenced from:
[build]       _ma_tls_verify_server_cert in libmariadb.a(openssl.c.o)
[build]       _ma_tls_get_finger_print in libmariadb.a(openssl.c.o)
[build]   "_X509_verify_cert_error_string", referenced from:
[build]       _ma_tls_connect in libmariadb.a(openssl.c.o)
[build]   "_compress", referenced from:
[build]       __mariadb_compress in libmariadb.a(ma_compress.c.o)
[build]       __mariadb_compress_alloc in libmariadb.a(ma_compress.c.o)
[build]      (maybe you meant: __mariadb_compress_alloc, __mariadb_compress )
[build]   "_uncompress", referenced from:
[build]       __mariadb_uncompress in libmariadb.a(ma_compress.c.o)
[build]      (maybe you meant: __mariadb_uncompress)
[build] ld: symbol(s) not found for architecture x86_64
[build] collect2: error: ld returned 1 exit status
[build] make[3]: *** [sql] Error 1
[build] make[2]: *** [CMakeFiles/sql.dir/all] Error 2
[build] make[1]: *** [CMakeFiles/sql.dir/rule] Error 2`

**Comment by Alvaroalloc** [comment]
found this:
[https://github.com/microsoft/vcpkg/commit/5c25a01a9c78abac984fd55d7ad5c8fa5b29041a](url)

**Comment by Alvaroalloc** [comment]
![Captura de pantalla 2020-10-28 a la(s) 09 58 30](https://user-images.githubusercontent.com/71088454/97462394-4568ed00-1904-11eb-8640-de8b8443b8ba.png)

**Comment by Alvaroalloc** [comment]
I found this. I think i have to wait for a new version of vcpkg :(

**Comment by vicroms** [comment]
@Alvaroalloc 
PR has been merged, just `git pull` the latest changes and install the package again.

**Comment by Alvaroalloc** [comment]
Ok i will try

**Comment by Alvaroalloc** [comment]
@vicroms what is PR?

**Comment by PhoebeHui** [comment]
@Alvaroalloc, the PR https://github.com/microsoft/vcpkg/pull/14196 has been merge to master, you need to execute command 'git pull' to get the latest source from master. And reinstall the port again.

**Comment by Alvaroalloc** [comment]
@PhoebeHui I did that and now shows me this:
`[cmake] CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
[cmake] Please set them or make sure they are set and tested correctly in the CMake files:
[cmake] LIBMARIADB_LIBRARY
[cmake]     linked by target "sql" in directory /Users/macuser/Desktop/x`

**Comment by Alvaroalloc** [comment]
and my CMakeLists.txt:
`cmake_minimum_required(VERSION 3.14)
project(sql CXX)

add_executable(sql main.cpp)

find_path(LIBMARIADB_INCLUDE_DIR mysql/mysql.h)
find_library(LIBMARIADB_LIBRARY libmariadb)

target_include_directories(sql PRIVATE ${LIBMARIADB_INCLUDE_DIR})
target_link_libraries(sql PRIVATE ${LIBMARIADB_LIBRARY})`

**Comment by PhoebeHui** [comment]
@Alvaroalloc, could you delete the cmake file and regenerate it again? Here is full steps:

1. git clone https://github.com/microsoft/vcpkg
2. cd ./vcpkg
3. ./bootstrap-vcpkg.bat
4. ./vcpkg install  libmariadb:x64-windows
5. ./vcpkg integrate install
6. Create test folder eg: E:\vcpkg\vcpkgtest\libmariadb
7. Create CMakeLists.txt file and main.cpp
CMakeLists.txt
```
cmake_minimum_required(VERSION 3.14)
project(example CXX)

add_executable(example main.cpp)

find_path(LIBMARIADB_INCLUDE_DIR mysql/mysql.h)
find_library(LIBMARIADB_LIBRARY libmariadb)

target_include_directories(example PRIVATE ${LIBMARIADB_INCLUDE_DIR})
target_link_libraries(example PRIVATE ${LIBMARIADB_LIBRARY})
```
main.cpp
```
#include<stdio.h>
#include <mysql/mysql.h>
using namespace std;
int main()
{
    MYSQL mysql;
    mysql_init(&mysql);
    mysql_options(&mysql,MYSQL_READ_DEFAULT_GROUP,"your_prog_name");
    if (!mysql_real_connect(&mysql,"host","user","passwd","database",0,NULL,0))
    {
        fprintf(stderr, "Failed to connect to database: Error: %s\n",
        mysql_error(&mysql));
    }
}
```
8. Create build folder and go to E:\vcpkg\vcpkgtest\libmariadb\build
9. cmake .. "-DCMAKE_TOOLCHAIN_FILE=E:/vcpkg/clean/vcpkg/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x64-windows -DVCPKG_BUILD_TYPE=debug -G "Visual Studio 16 2019"
10. cmake --build .

**Comment by Alvaroalloc** [comment]
@PhoebeHui Im in macOS

**Comment by PhoebeHui** [comment]
@Alvaroalloc, sorry for that! try below code instead.

```
cmake_minimum_required(VERSION 3.14)
project(example CXX)

add_executable(example main.cpp)

find_package(ZLIB REQUIRED)
find_package(OpenSSL REQUIRED)
find_path(LIBMARIADB_INCLUDE_DIR mysql/mysql.h)
find_library(LIBMARIADB_LIBRARY mariadb)

target_include_directories(example PRIVATE ${LIBMARIADB_INCLUDE_DIR})
target_link_libraries(example PRIVATE ZLIB::ZLIB OpenSSL::SSL OpenSSL::Crypto ${LIBMARIADB_LIBRARY})
```

**Comment by Alvaroalloc** [comment]
@PhoebeHui I had to change 
`find_path(LIBMARIADB_INCLUDE_DIR mysql/mysql.h)
find_library(LIBMARIADB_LIBRARY mariadb)` for this 
`find_path(MYSQL_INCLUDE_DIR mysql/mysql.h)
find_library(MYSQL_LIBRARY mariadb)`and works (i searched and the directory was the one  wanted.
But now it shows something of OpenSSL:
`[cmake] CMake Error at /Users/macuser/vcpkg/downloads/tools/cmake-3.18.4-osx/cmake-3.18.4-Darwin-x86_64/CMake.app/Contents/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
[cmake]   Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
[cmake]   system variable OPENSSL_ROOT_DIR (missing: OPENSSL_INCLUDE_DIR)
[cmake] Call Stack (most recent call first):
[cmake]   /Users/macuser/vcpkg/downloads/tools/cmake-3.18.4-osx/cmake-3.18.4-Darwin-x86_64/CMake.app/Contents/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
[cmake]   /Users/macuser/vcpkg/downloads/tools/cmake-3.18.4-osx/cmake-3.18.4-Darwin-x86_64/CMake.app/Contents/share/cmake-3.18/Modules/FindOpenSSL.cmake:486 (find_package_handle_standard_args)
[cmake]   CMakeLists.txt:7 (find_package)
[cmake] `

**Comment by Alvaroalloc** [comment]
I will close this i already made it up
