### ISSUE TITLE
Link error 1104: can not open file glfw3dll.lib

### ISSUE THREAD

**Issue by linuxaged** [Microsoft/vcpkg#1425]
Platform: Windows 10, Visual Studio 2017, CMake GUI 3.8.2

The vcpkg cmake toolchain has been selected when config my [project](https://github.com/linuxaged/v2t/tree/master/src)

glfw3 has been installed:

	D:\download>vcpkg list
	ffmpeg:x64-windows          3.2.4-3          a library to decode, encode, transcode, mux, demu...
	glfw3:x64-windows           3.2.1-1          GLFW is a free, Open Source, multi-platform libra...
	libpng:x64-windows          1.6.29-2         libpng is a library implementing an interface for...
	zlib:x64-windows            1.2.11           A compression library

my cmake script:

	cmake_minimum_required( VERSION 3.6.0 )

	project ( v2t )

	add_subdirectory( ./glxw glxw )

	add_executable ( v2t WIN32 main.cpp H264_Decoder.cpp YUV420P_Player.cpp )

	target_compile_options( v2t PRIVATE -Wall )

	#
	# FFmpeg
	#
	find_path( AVCODEC_INCLUDE_DIR libavcodec/avcodec.h )
	find_library( AVCODEC_LIBRARY avcodec )
	target_include_directories( v2t PRIVATE ${AVCODEC_INCLUDE_DIR} )
	target_link_libraries( v2t PRIVATE ${AVCODEC_LIBRARY})

	#
	# GLFW3
	#
	find_package( glfw3 REQUIRED )
	target_link_libraries( v2t PRIVATE glfw3dll )

	#
	# glxw
	#
	target_link_libraries( v2t PRIVATE glxw )

	#
	# libpng
	#
	find_path( LIBPNG_INCLUDE_DIR libpng16/png.h )
	find_library( LIBPNG_LIBRARY libpng16 )
	target_include_directories( v2t PRIVATE ${LIBPNG_INCLUDE_DIR} )
	target_link_libraries( v2t PRIVATE ${LIBPNG_LIBRARY} )

**Comment by Voskrese** [comment]
glfw3dll.lib -> glfw3.lib

**Comment by jasjuang** [comment]
`target_link_libraries( v2t PRIVATE glfw3 )` should solve it

**Comment by linuxaged** [comment]
use `glfw3` give the same error:

    2>LINK : fatal error LNK1104: 无法打开文件“glfw3.lib”

actually, there is no `glfw3.lib` in `vcpkg\installed\x64-windows\debug\lib` but `glfw3dll.lib`

**Comment by Voskrese** [comment]
@linuxaged 
E:\tools\vcpkg\packages\glfw_x86-windows>`ls lib`
cmake  **glfw3.lib**  pkgconfig

vcpkg install glfw3

**Comment by linuxaged** [comment]
Both 32bit and 64bit glfw3 are installed:

	D:\workspace\vcpkg\packages\glfw3_x86-windows>vcpkg list
	ffmpeg:x64-windows          3.2.4-3          a library to decode, encode, transcode, mux, demu...
	glfw3:x64-windows           3.2.1-1          GLFW is a free, Open Source, multi-platform libra...
	glfw3:x86-windows           3.2.1-1          GLFW is a free, Open Source, multi-platform libra...
	libpng:x64-windows          1.6.29-2         libpng is a library implementing an interface for...
	zlib:x64-windows            1.2.11           A compression library

How to deal with pkgconfig? Do not understand, @Voskrese

**Comment by Voskrese** [comment]
glfw3.pc
```
prefix=E:/tools/vcpkg/packages/glfw_x86-windows
exec_prefix=${prefix}
includedir=${prefix}/include
libdir=${exec_prefix}/lib

Name: GLFW
Description: A multi-platform library for OpenGL, window and input
Version: 3.3.0
URL: http://www.glfw.org/
Requires.private: 
Libs: -L${libdir} -lglfw3
Libs.private:  -lgdi32
Cflags: -I${includedir}
```
`set PKG_CONFIG_EXECUTABLE=E:\tools\Bin\pkg-config.exe`

`set PKG_CONFIG_PATH=E:\tools\vcpkg\installed\x86-windows\lib\pkgconfig;E:\tools\gstreamer\1.0\x86\lib\pkgconfig;E:\tools\vala-0.12.0\lib\pkgconfig`

**Comment by linuxaged** [comment]
fix by using `find_library`

	find_path( GLFW3_INCLUDE_DIR GLFW/glfw3.h )
	find_library( GLFW3_LIBRARY glfw3dll )
	target_include_directories( v2t PRIVATE ${GLFW3_INCLUDE_DIR} )
	target_link_libraries( v2t PRIVATE ${GLFW3_LIBRARY} )

**Comment by jasjuang** [comment]
I tried and you are right there is a problem. `find_package` should've work. I can submit a pull request later tonight to fix this

**Comment by jasjuang** [comment]
Actually nothing needs to be fixed. You just need to do `find_package(glfw3 REQUIRED)` and `target_link_libraries(${PROJECT_NAME} glfw)` then it should work. Note: glfw not glfw3 in target_link_libraries.
