### ISSUE TITLE
[New Port Request] onnxruntime 

### ISSUE THREAD

**Issue by rich-pel** [microsoft/vcpkg#14257]
Library name:
ONNXRUNTIME

Library description:
ONNX Runtime is a cross-platform inferencing and training accelerator compatible with many popular ML/DNN frameworks, including PyTorch, TensorFlow/Keras, scikit-learn, and more. aka.ms/onnxruntime

Source repository URL:
https://github.com/microsoft/onnxruntime

Project homepage (if different from the source repository):
https://github.com/microsoft/onnxruntime

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
I'm not sure if it hits the port requirements, however it would be nice to have the C++ interface to use DNNs developed and exported from multiple popular frameworks.

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, and continue PR https://github.com/microsoft/vcpkg/pull/14903.
