### ISSUE TITLE
[assimp] assimp port missing CMake version package information

### ISSUE THREAD

**Issue by traversaro** [microsoft/vcpkg#14255]
**Describe the bug**
The `assimp` port does not install any CMake version config file

**Environment**
- OS: Windows
- Compiler: Not relevant

**To Reproduce**
1. ./vcpkg install assimp
2. Run a cmake project that contains `find_package(assimp REQUIRED)` . The `assimp_VERSION` is empty, different from what happened before https://github.com/microsoft/vcpkg/pull/13264 .

**Expected behavior**
The assimp vcpkg port should install CMake version information as done by the assimp packages on other package managers. 

**Failure logs** 

**Additional context**
assimp CMake config files have been historically very problematic. PR  https://github.com/microsoft/vcpkg/pull/13264 solve most of the problems, but introduced this regression.

**Comment by PhoebeHui** [comment]
The PR has been merged, thanks for reporting this issue!
