### ISSUE TITLE
[spdlog] build failure with benchmark feature

### ISSUE THREAD

**Issue by StarGate-One** [microsoft/vcpkg#14265]
**Host Environment**
- OS: [Microsoft Windows [Version 10.0.19042.572]]
- Compiler: Visual Studio  Version: 16.7.6  VS Tools Version: 14.27.29110
  and Visual Studio  Version: 15.9.28  VS Tools Version: 14.16.27023

**To Reproduce**
`set VCPKG_CRT_LINKAGE=dynamic`
`set VCPKG_DEFAULT_TRIPLET=x64-windows`
`set VCPKG_DISABLE_METRICS=true`
`set VCPKG_DOWNLOADS=[vcpkg-root]\test\downloads`
`set VCPKG_FEATURE_FLAGS=-binarycaching,-compilertracking,-manifests,-registries`
`set VCPKG_LIBRARY_LINKAGE=dynamic`
`set VCPKG_MAX_CONCURRENCY=8`
`set VCPKG_NO_CLEAN=YES`
`set VCPKG_PLATFORM_TOOLSET=[VS Native Toolset for 2017 or 2019 - either v141 or v142`
`set VCPKG_VISUAL_STUDIO_PATH=C:\Program Files (x86)\Microsoft Visual Studio\[VS Version - either 2017 or 2019]\Community`

`git pull` current as of ~18:00 GMT ~14:00 Local
`.\bootstrap-vcpkg.bat -verbose -disableMetrics -win64 -withVSPath "'%VCPKG_VISUAL_STUDIO_PATH%'"`

Run custom script to remove/install all ports found by `.\vcpkg upgrade` as upgrade option does not support --editable and --x-use-aria2 options reference issues #12643 and #12834
log show spdlog failed during install

Try and rerun install of port spdlog with benchmark feature.
`vcpkg install spdlog[benchmark,core]:x64-windows --editable`

**Failure logs** 
- Cut and past the appropriate build messages from the console output.
`Computing installation plan...`
`The following packages will be built and installed:`
`    spdlog[benchmark,core]:x64-windows`
`Starting package 1/1: spdlog:x64-windows`
`Building package spdlog[benchmark,core]:x64-windows...`
`-- Using cached D:/vcpkg_x64/vs2019/prod/downloads/gabime-spdlog-4a9ccf7e38e257feecce0c579a782741254eaeef.tar.gz`
`-- Extracting source D:/vcpkg_x64/vs2019/prod/downloads/gabime-spdlog-4a9ccf7e38e257feecce0c579a782741254eaeef.tar.gz`
`-- Using source at D:/vcpkg_x64/vs2019/prod/buildtrees/spdlog/src/41254eaeef-2548ad24d3`
`-- Configuring x64-windows`
`-- Building x64-windows-dbg`
`CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:142 (message):`
`    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j8`
`    Working Directory: D:/vcpkg_x64/vs2019/prod/buildtrees/spdlog/x64-windows-dbg`
`    See logs for more information:`
`      D:\vcpkg_x64\vs2019\prod\buildtrees\spdlog\install-x64-windows-dbg-out.log`
` `
`Call Stack (most recent call first):`
`  scripts/cmake/vcpkg_build_cmake.cmake:93 (vcpkg_execute_build_process)`
`  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)`
`  ports/spdlog/portfile.cmake:22 (vcpkg_install_cmake)`
`  scripts/ports.cmake:79 (include)`
` `
`Error: Building package spdlog:x64-windows failed with: BUILD_FAILED`
`Please ensure you're using the latest portfiles with `.\vcpkg update`, then`
`submit an issue at https://github.com/Microsoft/vcpkg/issues including:`
`  Package: spdlog:x64-windows`
`  Vcpkg version: 2020.06.15-nohash`
` `
`Additionally, attach any relevant sections from the log files above.`

- Please attach any additional failure logs mentioned in the console output.
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/5447199/install-x64-windows-dbg-out.log)

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.
- Appears to be related to recent upgrade to port fmt https://github.com/microsoft/vcpkg/pull/14239
- Also happens using VS2017 also: 
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/5447220/install-x64-windows-dbg-out.log)

**Other things tried**
I removed spdlog dependencies (ports benchmark and fmt), deleted directories .\buildtrees\benchmark, fmt and spdlog and then tried to reinstall all three ports from scratch with same result... benchmark and fmt installed, spdlog failed with same errors.

`SYSTEM@ANDROMEDA 10/27/2020 14:04:53 D:\vcpkg_x64\vs2019\prod`
`->vcpkg remove fmt`
`The following packages will be removed:`
`    fmt:x64-windows`
`Removing package fmt:x64-windows...`
`Removing package fmt:x64-windows... done`

`SYSTEM@ANDROMEDA 10/27/2020 14:04:53 D:\vcpkg_x64\vs2019\prod`
`->vcpkg remove benchmark`
`The following packages will be removed:`
`    benchmark:x64-windows`
`Removing package benchmark:x64-windows...`
`Removing package benchmark:x64-windows... done`

`SYSTEM@ANDROMEDA 10/27/2020 14:04:53 D:\vcpkg_x64\vs2019\prod`
`->rmdir /q /s .\buildtrees\fmt`

`SYSTEM@ANDROMEDA 10/27/2020 14:05:16 D:\vcpkg_x64\vs2019\prod`
`->rmdir /q /s .\buildtrees\benchmark`

`SYSTEM@ANDROMEDA 10/27/2020 14:05:22 D:\vcpkg_x64\vs2019\prod`
`->rmdir /q /s .\buildtrees\spdlog`

`SYSTEM@ANDROMEDA 10/27/2020 14:05:27 D:\vcpkg_x64\vs2019\prod`
`->vcpkg install spdlog[benchmark,core] fmt[core] benchmark[core] --editable`
`Computing installation plan...`
`The following packages will be built and installed:`
`    benchmark[core]:x64-windows`
`    fmt[core]:x64-windows`
`    spdlog[benchmark,core]:x64-windows`
`Starting package 1/3: benchmark:x64-windows`
`Building package benchmark[core]:x64-windows...`
`-- Note: benchmark only supports static library linkage. Building static library.`
`-- Using cached D:/vcpkg_x64/vs2019/prod/downloads/google-benchmark-73d4d5e8d6d449fc8663765a42aa8aeeee844489.tar.gz`
`-- Extracting source D:/vcpkg_x64/vs2019/prod/downloads/google-benchmark-73d4d5e8d6d449fc8663765a42aa8aeeee844489.tar.gz`
`-- Using source at D:/vcpkg_x64/vs2019/prod/buildtrees/benchmark/src/eeee844489-75b6880063`
`-- Configuring x64-windows`
`-- Building x64-windows-dbg`
`-- Building x64-windows-rel`
`-- Using msys root at D:/vcpkg_x64/vs2019/prod/downloads/tools/msys2/17e91aa90d284835`
`-- Fixing pkgconfig file: D:/vcpkg_x64/vs2019/prod/packages/benchmark_x64-windows/lib/pkgconfig/benchmark.pc`
`-- Fixing pkgconfig file: D:/vcpkg_x64/vs2019/prod/packages/benchmark_x64-windows/debug/lib/pkgconfig/benchmark.pc`
`-- Installing: D:/vcpkg_x64/vs2019/prod/packages/benchmark_x64-windows/share/benchmark/copyright`
`-- Performing post-build validation`
`-- Performing post-build validation done`
`Building package benchmark[core]:x64-windows... done`
`Installing package benchmark[core]:x64-windows...`
`Installing package benchmark[core]:x64-windows... done`
`Elapsed time for package benchmark:x64-windows: 9.658 s`
`Starting package 2/3: fmt:x64-windows`
`Building package fmt[core]:x64-windows...`
`-- Using cached D:/vcpkg_x64/vs2019/prod/downloads/fmtlib-fmt-4fe0b11195b7cd71f39253c44db2c9dddf6b82d4.tar.gz`
`-- Extracting source D:/vcpkg_x64/vs2019/prod/downloads/fmtlib-fmt-4fe0b11195b7cd71f39253c44db2c9dddf6b82d4.tar.gz`
`-- Applying patch fix-warning4189.patch`
`-- Using source at D:/vcpkg_x64/vs2019/prod/buildtrees/fmt/src/dddf6b82d4-f2c5fef865`
`-- Configuring x64-windows`
`-- Building x64-windows-dbg`
`-- Building x64-windows-rel`
`-- Installing: D:/vcpkg_x64/vs2019/prod/packages/fmt_x64-windows/share/fmt/copyright`
`-- Using msys root at D:/vcpkg_x64/vs2019/prod/downloads/tools/msys2/17e91aa90d284835`
`-- Fixing pkgconfig file: D:/vcpkg_x64/vs2019/prod/packages/fmt_x64-windows/lib/pkgconfig/fmt.pc`
`-- Fixing pkgconfig file: D:/vcpkg_x64/vs2019/prod/packages/fmt_x64-windows/debug/lib/pkgconfig/fmt.pc`
`-- Installing: D:/vcpkg_x64/vs2019/prod/packages/fmt_x64-windows/share/fmt/usage`
`-- Performing post-build validation`
`-- Performing post-build validation done`
`Building package fmt[core]:x64-windows... done`
`Installing package fmt[core]:x64-windows...`
`Installing package fmt[core]:x64-windows... done`
`Elapsed time for package fmt:x64-windows: 5.134 s`
`Starting package 3/3: spdlog:x64-windows`
`Building package spdlog[benchmark,core]:x64-windows...`
`-- Using cached D:/vcpkg_x64/vs2019/prod/downloads/gabime-spdlog-4a9ccf7e38e257feecce0c579a782741254eaeef.tar.gz`
`-- Extracting source D:/vcpkg_x64/vs2019/prod/downloads/gabime-spdlog-4a9ccf7e38e257feecce0c579a782741254eaeef.tar.gz`
`-- Using source at D:/vcpkg_x64/vs2019/prod/buildtrees/spdlog/src/41254eaeef-2548ad24d3`
`-- Configuring x64-windows`
`-- Building x64-windows-dbg`
`CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:142 (message):`
`    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j8`
`    Working Directory: D:/vcpkg_x64/vs2019/prod/buildtrees/spdlog/x64-windows-dbg`
`    See logs for more information:`
`      D:\vcpkg_x64\vs2019\prod\buildtrees\spdlog\install-x64-windows-dbg-out.log`
` `
`Call Stack (most recent call first):`
`  scripts/cmake/vcpkg_build_cmake.cmake:93 (vcpkg_execute_build_process)`
`  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)`
`  ports/spdlog/portfile.cmake:22 (vcpkg_install_cmake)`
`  scripts/ports.cmake:79 (include)`
` `
`Error: Building package spdlog:x64-windows failed with: BUILD_FAILED`
`Please ensure you're using the latest portfiles with `.\vcpkg update`, then`
`submit an issue at https://github.com/Microsoft/vcpkg/issues including:`
`  Package: spdlog:x64-windows`
`  Vcpkg version: 2020.06.15-nohash`
` `
`Additionally, attach any relevant sections from the log files above.`

**Comment by StarGate-One** [comment]
Additional Notes:
1. port spdlog will install without feature benchmark, but not desirable(1)
2. port shiva depends on port spdlog, although does not require port spdlog to have feature benchmark installed, but not desirable(1)

(1) not desirable as downstream projects depend on port spdlog with feature benchmark installed using port shiva.

**Comment by StarGate-One** [comment]
I checked the azure pipeline build tests (https://dev.azure.com/vcpkg/c1ee48cb-0df2-4ab3-8384-b1df5a79fe53/_apis/build/builds/44563/logs/92) for PR upgrading port fmt #14239 and it shows spdlog was tested but **without feature benchmark**.
![image](https://user-images.githubusercontent.com/68293825/97349148-7e05b980-1865-11eb-9cd2-2680d00cd26a.png)

**Comment by sfhacker** [comment]
Are we **STILL** having issues building spdlog from source?

**Comment by StarGate-One** [comment]
Another Note: I can revert port format to version 7.0.3 and port stblog[benchmark] builds fine.

`SYSTEM@ANDROMEDA 10/27/2020 16:12:43 D:\vcpkg_x64\vs2019\test`
`->git diff ports/fmt/portfile.cmake`
`diff --git a/ports/fmt/portfile.cmake b/ports/fmt/portfile.cmake`
`index 94dfd3f04..5de78ec98 100644`
`--- a/ports/fmt/portfile.cmake`
`+++ b/ports/fmt/portfile.cmake`
`@@ -1,8 +1,8 @@`
` vcpkg_from_github(`
`     OUT_SOURCE_PATH SOURCE_PATH`
`     REPO fmtlib/fmt`
`-    REF 4fe0b11195b7cd71f39253c44db2c9dddf6b82d4#version 7.1.0`
`-    SHA512 1cb2eac5abcec0a002c505a3de04284f89a6b31923edb6868cf9e9ac2803c3985ab62e2bff55da49a30def8476bfed205cf6a5b40a03a1d3df1292feb5352e86`
`+    REF cd4af11efc9c622896a3e4cb599fa28668ca3d05#version 7.0.3`
`+    SHA512 24b42288be97849533dc82282fc08833d74642ad2afeb511e65c6389d88c709cf25345dec5b550c18af3705f4c0847fa0d4066308b51cd41ccfdda1a2c3babd0`
`     HEAD_REF master`
`     PATCHES fix-warning4189.patch`
` )`

`SYSTEM@ANDROMEDA 10/27/2020 16:08:19 D:\vcpkg_x64\vs2019\test`
`->vcpkg install fmt benchmark spdlog[benchmark] --editable`
`Computing installation plan...`
`The following packages will be built and installed:`
`    benchmark[core]:x64-windows`
`    fmt[core]:x64-windows`
`    spdlog[benchmark,core]:x64-windows`
`Starting package 1/3: benchmark:x64-windows`
`Building package benchmark[core]:x64-windows...`
`-- Note: benchmark only supports static library linkage. Building static library.`
`-- Using cached D:/vcpkg_x64/vs2019/test/downloads/google-benchmark-73d4d5e8d6d449fc8663765a42aa8aeeee844489.tar.gz`
`-- Extracting source D:/vcpkg_x64/vs2019/test/downloads/google-benchmark-73d4d5e8d6d449fc8663765a42aa8aeeee844489.tar.gz`
`-- Using source at D:/vcpkg_x64/vs2019/test/buildtrees/benchmark/src/eeee844489-75b6880063`
`-- Configuring x64-windows`
`-- Building x64-windows-dbg`
`-- Building x64-windows-rel`
`-- Using msys root at D:/vcpkg_x64/vs2019/test/downloads/tools/msys2/17e91aa90d284835`
`-- Fixing pkgconfig file: D:/vcpkg_x64/vs2019/test/packages/benchmark_x64-windows/lib/pkgconfig/benchmark.pc`
`-- Fixing pkgconfig file: D:/vcpkg_x64/vs2019/test/packages/benchmark_x64-windows/debug/lib/pkgconfig/benchmark.pc`
`-- Installing: D:/vcpkg_x64/vs2019/test/packages/benchmark_x64-windows/share/benchmark/copyright`
`-- Performing post-build validation`
`-- Performing post-build validation done`
`Building package benchmark[core]:x64-windows... done`
`Installing package benchmark[core]:x64-windows...`
`Installing package benchmark[core]:x64-windows... done`
`Elapsed time for package benchmark:x64-windows: 8.91 s`
`Starting package 2/3: fmt:x64-windows`
`Building package fmt[core]:x64-windows...`
`-- Using cached D:/vcpkg_x64/vs2019/test/downloads/fmtlib-fmt-cd4af11efc9c622896a3e4cb599fa28668ca3d05.tar.gz`
`-- Extracting source D:/vcpkg_x64/vs2019/test/downloads/fmtlib-fmt-cd4af11efc9c622896a3e4cb599fa28668ca3d05.tar.gz`
`-- Applying patch fix-warning4189.patch`
`-- Using source at D:/vcpkg_x64/vs2019/test/buildtrees/fmt/src/8668ca3d05-7f40cec0ee`
`-- Configuring x64-windows`
`-- Building x64-windows-dbg`
`-- Building x64-windows-rel`
`-- Installing: D:/vcpkg_x64/vs2019/test/packages/fmt_x64-windows/share/fmt/copyright`
`-- Using msys root at D:/vcpkg_x64/vs2019/test/downloads/tools/msys2/17e91aa90d284835`
`-- Fixing pkgconfig file: D:/vcpkg_x64/vs2019/test/packages/fmt_x64-windows/lib/pkgconfig/fmt.pc`
`-- Fixing pkgconfig file: D:/vcpkg_x64/vs2019/test/packages/fmt_x64-windows/debug/lib/pkgconfig/fmt.pc`
`-- Installing: D:/vcpkg_x64/vs2019/test/packages/fmt_x64-windows/share/fmt/usage`
`-- Performing post-build validation`
`-- Performing post-build validation done`
`Building package fmt[core]:x64-windows... done`
`Installing package fmt[core]:x64-windows...`
`Installing package fmt[core]:x64-windows... done`
`Elapsed time for package fmt:x64-windows: 4.889 s`
`Starting package 3/3: spdlog:x64-windows`
`Building package spdlog[benchmark,core]:x64-windows...`
`-- Using cached D:/vcpkg_x64/vs2019/test/downloads/gabime-spdlog-4a9ccf7e38e257feecce0c579a782741254eaeef.tar.gz`
`-- Extracting source D:/vcpkg_x64/vs2019/test/downloads/gabime-spdlog-4a9ccf7e38e257feecce0c579a782741254eaeef.tar.gz`
`-- Using source at D:/vcpkg_x64/vs2019/test/buildtrees/spdlog/src/41254eaeef-2548ad24d3`
`-- Configuring x64-windows`
`-- Building x64-windows-dbg`
`-- Building x64-windows-rel`
`-- Installing: D:/vcpkg_x64/vs2019/test/packages/spdlog_x64-windows/share/spdlog/copyright`
`-- Performing post-build validation`
`-- Performing post-build validation done`
`Building package spdlog[benchmark,core]:x64-windows... done`
`Installing package spdlog[benchmark,core]:x64-windows...`
`Installing package spdlog[benchmark,core]:x64-windows... done`
`Elapsed time for package spdlog:x64-windows: 6.809 s`
` `
`Total elapsed time: 20.76 s`
` `
`The package benchmark:x64-windows provides CMake targets:`
` `
`    find_package(benchmark CONFIG REQUIRED)`
`    target_link_libraries(main PRIVATE benchmark::benchmark benchmark::benchmark_main)`
` `
`The package fmt provides CMake targets:`
` `
`    find_package(fmt CONFIG REQUIRED)`
`    target_link_libraries(main PRIVATE fmt::fmt)`
` `
`    # Or use the header-only version`
`    target_link_libraries(main PRIVATE fmt::fmt-header-only)`
` `
`The package spdlog:x64-windows provides CMake targets:`
` `
`    find_package(spdlog CONFIG REQUIRED)`
`    target_link_libraries(main PRIVATE spdlog::spdlog spdlog::spdlog_header_only)`

**Comment by StarGate-One** [comment]
Thank you @LilyWangL @BillyONeal 
Have a wonderful day!!!
