### ISSUE TITLE
Add config/build/install checkpoints

### ISSUE THREAD

**Issue by jamesratzlaff** [microsoft/vcpkg#14264]
****

**Is your feature request related to a problem? Please describe.**
My builds builds randomly hang (which I suspect is due to some corporate software that cannot be disabled). I stop the build when this happens (pressing Ctrl+C). With exception of download and unpack step, I have to start the install process all over again. It would save me a ton of time, if there was was a *--continue* flag that could be used to continue from the last completed vcpkg step.

**Proposed solution**
In the buildtree directory for a given package add a text file that essentially indicates which step was last completed.  This way the current contents of the buildtree can be treated as a cache in its current state.

**Comment by JackBoosY** [comment]
The way to solve this problem is to reproduce it and fix the bug instead of adding checkpoints, I think.
@BillyONeal what's your opinion?

**Comment by BillyONeal** [comment]
Unfortunately offering an option like this would be expressly counter to our design goal of always producing the same output even given changes in the system; there's no way for us to know that the build tree hasn't been completely edited etc.

Moreover, we don't even have that kind of control for most ports: we invoke `portfile.cmake`, and each port does its own build/configure etc. step itself.

You might want to use a VM or similar as a workaround.
