### ISSUE TITLE
install FindCAF.cmake file to where it is found by cmake 

### ISSUE THREAD

**Issue by dajaim** [microsoft/vcpkg#14279]
i am new to cmake and vcpkg and want to use the c++ actor framework, which you can install via vcpkg.
it is basically this:  [stackoverflow question](https://stackoverflow.com/questions/64515853/unable-to-run-c-actor-framework-hello-world-code) 
summarized:
vcpkg install caf
does not provide the info how to find_package or target_link_libraries caf, because, according to the answer, the FindCAF.cmake file is not installed in the appropriate location.
my question is, if you could install the file to where it is found by cmake.

**Comment by NancyLi1013** [comment]
Hi @dajaim 
Thanks for posting this issue.

I noticed that the source code has provided `FindCAF.cmake` file, but we didn't install it to vcpkg.

Generally, we need to install the FindXXX.cmake file to _share/${PORT}_ directory. At the same time, we also need to add `vcpkg_cmake_wrapper.cmake` file to associate cmake with vcpkg. 

Only if the FindXXX.cmake file is provided by cmake, there is no need to add these files in vcpkg. 

I will try to fix this later.

**Comment by BillyONeal** [comment]
>At the same time, we also need to add vcpkg_cmake_wrapper.cmake file to associate cmake with vcpkg.

`vcpkg_cmake_wrapper` is an escape hatch when we need to override a default-comes-with-cmake module; we should be able to just publish the .config in the right place to my understanding.

**Comment by NancyLi1013** [comment]
Thanks for your above comments @BillyONeal.

I noticed that upstream has provided the config file https://github.com/actor-framework/actor-framework/blob/master/cmake/CAFConfig.cmake.in, which is in current mater branch.

In my opinion, we can remove usage and vcpkg-cmake-wrapper in next release 0.18.0 to use config.
