### ISSUE TITLE
install ffmpeg:x64-windows error

### ISSUE THREAD

**Issue by ylzf0000** [microsoft/vcpkg#14278]
Starting package 2/8: ffmpeg:x64-windows
Building package ffmpeg[avcodec,avdevice,avfilter,avformat,avresample,core,gpl,postproc,swresample,swscale]:x64-windows...
Could not locate cached archive: C:\Users\zhang\AppData\Local\vcpkg\archives\b8\b808a609a9dfa22b0faf254f1852dfe63688ced9.zip
-- Using cached D:/vcpkg/downloads/ffmpeg-ffmpeg-n4.3.1.tar.gz
-- Cleaning sources at D:/vcpkg/buildtrees/ffmpeg/src/n4.3.1-73f9ace9ef.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/vcpkg/downloads/ffmpeg-ffmpeg-n4.3.1.tar.gz
-- Applying patch 0001-create-lib-libraries.patch
-- Applying patch 0003-fix-windowsinclude.patch
-- Applying patch 0004-fix-debug-build.patch
-- Applying patch 0005-fix-libvpx-linking.patch
-- Applying patch 0006-fix-StaticFeatures.patch
-- Applying patch 0007-fix-lib-naming.patch
-- Applying patch 0008-Fix-wavpack-detection.patch
-- Applying patch 0009-Fix-fdk-detection.patch
-- Applying patch 0010-Fix-x264-detection.patch
-- Applying patch 0011-Fix-x265-detection.patch
-- Applying patch 0012-Fix-ssl-110-detection.patch
-- Using source at D:/vcpkg/buildtrees/ffmpeg/src/n4.3.1-73f9ace9ef.clean
-- Downloading https://repo.msys2.org/msys/x86_64/libiconv-1.16-1-x86_64.pkg.tar.xz...
-- Downloading https://repo.msys2.org/msys/x86_64/libiconv-1.16-1-x86_64.pkg.tar.xz... Failed. Status: 22;"HTTP response code said error"
-- Downloading https://www2.futureware.at/~nickoe/msys2-mirror/msys/x86_64/libiconv-1.16-1-x86_64.pkg.tar.xz...
-- Downloading https://www2.futureware.at/~nickoe/msys2-mirror/msys/x86_64/libiconv-1.16-1-x86_64.pkg.tar.xz... Failed. Status: 22;"HTTP response code said error"
-- Downloading https://mirror.yandex.ru/mirrors/msys2/msys/x86_64/libiconv-1.16-1-x86_64.pkg.tar.xz...
-- Downloading https://mirror.yandex.ru/mirrors/msys2/msys/x86_64/libiconv-1.16-1-x86_64.pkg.tar.xz... Failed. Status: 22;"HTTP response code said error"
-- Downloading https://mirrors.tuna.tsinghua.edu.cn/msys2/msys/x86_64/libiconv-1.16-1-x86_64.pkg.tar.xz...
-- Downloading https://mirrors.tuna.tsinghua.edu.cn/msys2/msys/x86_64/libiconv-1.16-1-x86_64.pkg.tar.xz... Failed. Status: 22;"HTTP response code said error"
-- Downloading https://mirrors.ustc.edu.cn/msys2/msys/x86_64/libiconv-1.16-1-x86_64.pkg.tar.xz...
-- Downloading https://mirrors.ustc.edu.cn/msys2/msys/x86_64/libiconv-1.16-1-x86_64.pkg.tar.xz... Failed. Status: 22;"HTTP response code said error"
-- Downloading https://mirror.bit.edu.cn/msys2/msys/x86_64/libiconv-1.16-1-x86_64.pkg.tar.xz...
-- Downloading https://mirror.bit.edu.cn/msys2/msys/x86_64/libiconv-1.16-1-x86_64.pkg.tar.xz... Failed. Status: 22;"HTTP response code said error"
-- Downloading https://mirror.selfnet.de/msys2/msys/x86_64/libiconv-1.16-1-x86_64.pkg.tar.xz...
-- Downloading https://mirror.selfnet.de/msys2/msys/x86_64/libiconv-1.16-1-x86_64.pkg.tar.xz... Failed. Status: 22;"HTTP response code said error"
-- Downloading https://mirrors.sjtug.sjtu.edu.cn/msys2/msys/x86_64/libiconv-1.16-1-x86_64.pkg.tar.xz...
-- Downloading https://mirrors.sjtug.sjtu.edu.cn/msys2/msys/x86_64/libiconv-1.16-1-x86_64.pkg.tar.xz... Failed. Status: 22;"HTTP response code said error"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:181 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_acquire_msys.cmake:87 (vcpkg_download_distfile)
  scripts/cmake/vcpkg_acquire_msys.cmake:125 (msys_package_download)
  scripts/cmake/vcpkg_acquire_msys.cmake:291 (msys_package)
  ports/ffmpeg/portfile.cmake:59 (vcpkg_acquire_msys)
  scripts/ports.cmake:79 (include)

Error: Building package ffmpeg:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: ffmpeg:x64-windows
  Vcpkg version: 2020.06.15-nohash
![image](https://user-images.githubusercontent.com/17083562/97426937-09a74500-194f-11eb-9020-4b924acf1ed4.png)

**Comment by emptyVoid** [comment]
Should be resolved by #14220. Try updating your `vcpkg` clone.
