### ISSUE TITLE
How do I run cl.exe integrate with vcpkg?

### ISSUE THREAD

**Issue by allenling** [microsoft/vcpkg#14272]
when i run `vcpkg.exe integrate install`, then run vs to compile something, it works so great.

i dont need to configure include dirs and lib dirs, and list all needed lib names manually, perfect and smooth.

and now i need to run cl.exe, not msbuild, could i run cl.exe integrate  with vcpkg?

then i dont need to configure anything to run cl.exe to compile my cpp project.

**Comment by JackBoosY** [comment]
Integrate is achieved by modifying the Visual Studio settings to add triplet, include path, and library path to the corresponding items in `*.vcxproj`. If you only use the compiler command line, I think it cannot be achieved.

**Comment by allenling** [comment]
@JackBoosY 

sad about that, but thanks very much!
