### ISSUE TITLE
Cannot install anything: "Could not automatically acquire pwsh"

### ISSUE THREAD

**Issue by lone-wolf-akela** [microsoft/vcpkg#14273]
**Describe the bug**
I cannot install any packages. All of them give me the error:
`Could not automatically acquire pwsh because there is no entry in D:\source\test\vcpkg\scripts\vcpkgTools.xml for os=windows. You may be able to install pwsh via your system package manager.`

**Environment**
- OS: Windows 10 2004 (19041.572)
- Compiler: Visual Studio 2019 16.7.6
- vcpkg version: 2020.06.15-nohash

**To Reproduce**
1. `mkdir test`
2. `cd .\test\`
3. `git clone https://github.com/microsoft/vcpkg.git`
4. `cd .\vcpkg\`
5. `.\bootstrap-vcpkg.bat`
6. `.\vcpkg.exe install fmt`
This gives:
```
Computing installation plan...
The following packages will be built and installed:
    fmt[core]:x86-windows
Detecting compiler hash for triplet x86-windows...
Could not automatically acquire pwsh because there is no entry in D:\source\test\vcpkg\scripts\vcpkgTools.xml for os=windows. You may be able to install pwsh via your system package manager.
```
7. `.\vcpkg.exe install mimalloc`
This gives:
```
Computing installation plan...
The following packages will be built and installed:
    mimalloc[core]:x86-windows
Detecting compiler hash for triplet x86-windows...
Could not automatically acquire pwsh because there is no entry in D:\source\test\vcpkg\scripts\vcpkgTools.xml for os=windows. You may be able to install pwsh via your system package manager.
```
8. `.\vcpkg.exe install ms-gsl`
This gives:
```
Computing installation plan...
The following packages will be built and installed:
    ms-gsl[core]:x86-windows
Detecting compiler hash for triplet x86-windows...
Could not automatically acquire pwsh because there is no entry in D:\source\test\vcpkg\scripts\vcpkgTools.xml for os=windows. You may be able to install pwsh via your system package manager.
```

**Expected behavior**
I should be able to install things.

**Comment by JackBoosY** [comment]
Will fixe in #14271. duplicate to #9606.
