### ISSUE TITLE
Error: Building package curl:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by HideakiAtsuyo** [microsoft/vcpkg#14284]
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: curl:x64-windows
  Vcpkg version: 2020.06.15-nohash

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Could you please provide the error log?

**Comment by HideakiAtsuyo** [comment]
> 
> 
> Thanks for posting this issue. Could you please provide the error log?
Error: Building package curl:x64-windows failed with: BUILD_FAILED

**Comment by HideakiAtsuyo** [comment]
But that's ok
`vcpkg install curl[*]:x64-windows` => `vcpkg install curl:x64-windows`
