### ISSUE TITLE
'_VCPKG_PWSH_PATH-NOTFOUND' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by jaryder** [microsoft/vcpkg#14283]
**Describe the bug**
CMake on Windows fails its C-Compiler test due to:
'_VCPKG_PWSH_PATH-NOTFOUND' is not recognized as an internal or external command

**Environment**
- OS: Windows
- Compiler: MSVC 19.27.29112.0

**To Reproduce**
1. update submodule vcpkg to latest (ead8d6bad477f0b075f31097673c3e440356cd3b)
2. Build top-level project using cmake on Windows

**Expected behavior**
The build to succeed.

**Failure logs** 
Attached
[vcpkg_cmake_failure_logs.txt](https://github.com/microsoft/vcpkg/files/5454259/vcpkg_cmake_failure_logs.txt)

**Additional context**
Possibly related to changes in vcpkg/scripts/buildsystems/vcpkg.cmake with the introduction of _VCPKG_PWSH_PATH-NOTFOUND.
@BillyONeal

**Comment by BillyONeal** [comment]
As a workaround you should be able to install powershell-core https://github.com/PowerShell/PowerShell/releases/tag/v7.0.3

**Comment by Domacles** [comment]
Really useful, Thanks. 

> As a workaround you should be able to install powershell-core https://github.com/PowerShell/PowerShell/releases/tag/v7.0.3

**Comment by nil-is-lin** [comment]
I meet this problem sometimes. It happened suddenly. If I try a few more times, maybe one of them can run.

**Comment by swq123459** [comment]
我也出现了该问题，最新的版本

**Comment by lone-wolf-akela** [comment]
A workaround is to change 
https://github.com/microsoft/vcpkg/blob/1b1c17de8206231831b2bc8a06cff80506184be1/scripts/buildsystems/vcpkg.cmake#L402
to
```
if (${_VCPKG_PWSH_PATH} STREQUAL "_VCPKG_PWSH_PATH-NOTFOUND")
```

**Comment by BillyONeal** [comment]
@lone-wolf-akela Yes, the fix will look something like that, should have a fix out for review sometime tomorrow at the latest

**Comment by DuffsDevice** [comment]
Thanks alot @BillyONeal!

**Comment by Christsnatcher** [comment]
Just wanted to mention that I ran into the very same issue after updatiing both VS 2019 and vcpkg to the latest version. Thanks in advance for fixing it!

**Comment by EricHripko** [comment]
As a workaround, reverting to https://github.com/microsoft/vcpkg/commit/c34c4189ebbf0795e1f8e2de562c527a854c8db4 seems to have fixed it for me in the meantime 👍

**Comment by unfor19** [comment]
We were using the `master` version, seems like setting it to the latest release fixes it

```
git clone https://github.com/microsoft/vcpkg --branch 2020.07
```

**Comment by fferri** [comment]
Installing `powershell-core` fixed the issue for me.

**Comment by fferri** [comment]
> A workaround is to change
> https://github.com/microsoft/vcpkg/blob/1b1c17de8206231831b2bc8a06cff80506184be1/scripts/buildsystems/vcpkg.cmake#L402
> 
> 
> to
> ```
> if (${_VCPKG_PWSH_PATH} STREQUAL "_VCPKG_PWSH_PATH-NOTFOUND")
> ```

No.

`if(_VCPKG_PWSH_PATH)` should be enough.

From the [CMake `if` documentation](https://cmake.org/cmake/help/latest/command/if.html):

> `if(<constant>)`
>
> True if the constant is `1`, `ON`, `YES`, `TRUE`, `Y`, or a non-zero number. False if the constant is `0`, `OFF`, `NO`, `FALSE`, `N`, `IGNORE`, `NOTFOUND`, the empty string, or ends in the suffix `-NOTFOUND`. Named boolean constants are case-insensitive. If the argument is not one of these specific constants, it is treated as a variable or string and the following signature is used.

**Comment by JackBoosY** [comment]
@fferri #14317 should fixed this issue.
