### ISSUE TITLE
 Port request: [win-iconv] iconv.lib

### ISSUE THREAD

**Issue by Voskrese** [Microsoft/vcpkg#1428]
`git clone https://github.com/win-iconv/win-iconv`
`cd win-iconv`
`cmake . -G "Visual Studio 14 2015" -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="E:/tools/vcpkg/installed/x86-windows" -DCMAKE_TOOLCHAIN_FILE="E:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake"`
`cmake --build . --config Release`

C:\temp\win-iconv>`ls Release`
`VCRUNTIME140.dll  iconv.dll  iconv.exp  iconv.lib  win_iconv.exe`

**Comment by KindDragon** [comment]
https://github.com/Microsoft/vcpkg/tree/master/ports/libiconv

**Comment by Voskrese** [comment]
@KindDragon только эта библиотека не работает с этим проектом. я так понимаю нужен именно win_iconv. Но я еще в полной мере не разобрался

> only this library does not work with this project. I understand need win_iconv. But I still do not fully understand

https://github.com/sakurai-youhei/pymssql/blob/proto/openssl1.1.0/README_building_and_developing.rst
https://github.com/ramiro/freetds/releases

**Comment by KindDragon** [comment]
I think they tried only with `win_iconv`, you should try with `libiconv`

> Я думаю они пробовали только с `win_iconv`, вам стоит попробовать с `libiconv`

**Comment by Voskrese** [comment]
@KindDragon попробую переименовть libiconv в iconv

> try pereimenovt libiconv in iconv

**Comment by Voskrese** [comment]
пока закрою) что то не ладится со сборкой
