### ISSUE TITLE
New to vcpkg - install of PCL taking 6+ hours

### ISSUE THREAD

**Issue by ericwilliamsneu** [microsoft/vcpkg#14280]
**vcpkg appears to hang on various steps**
This is my first attempt to use vcpkg, so I'm guessing the issue may be PEBKAC, but it doesn't feel that way. After having cloned the repository, bootstrapped it, installing Visual Studio 2019 Community (with C++ desktop support), and installing the latest and greatest version of PowerShell (v7), I attempted to install my first package (the Point Cloud Library).

The tool actually appears to be working, but so far it's taken over 6 hours. It appears that either the package manager itself, PowerShell, or something else has "hung up" and take an indefinite nap on few packages. What I've found by luck and chance is that if I spam enter into the PowerShell terminal the whole act will "wake back up" and start chugging along again. Some dependencies are flying by... some may take infinitely long unless I hit it with the enter-hammer.

Some favorites so far (from the program output in the PowerShell console that's actively running):
- Elapsed time for package openssl-windows:x86-windows: 5.192 h (just sat there, sleeping while I got some sleep myself, I suppose)
- Elapsed time for package boost-filesystem:x86-windows: 11.75 min
- Elapsed time for package boost-exception:x86-windows: 21.59 min
 
Most of the rest of the packages are taking extremely reasonable times between 5 seconds and 30 seconds.

The most common place in the routine for each package for the "hang up" is right after `-- Configuring x86-windows`.

**Environment**
- OS: Windows 10 Build 18363
- Compiler: Visual Studio 2019 with C++ (Community)

**Comment by JackBoosY** [comment]
Can you confirm that your PowerShell is not hung up?
Such as:
![image](https://user-images.githubusercontent.com/47264268/97518109-8bd84d80-19d1-11eb-8e8d-a12fd8cb942c.png)

**Comment by ericwilliamsneu** [comment]
> Can you confirm that your PowerShell is not hung up?
> Such as:
> ![image](https://user-images.githubusercontent.com/47264268/97518109-8bd84d80-19d1-11eb-8e8d-a12fd8cb942c.png)

Confirmed - the PowerShell window title is just "PowerShell 7(x64)" and nothing is selected. I've retried this process about 4 times now, it keeps getting a little further before a massive unrecoverable hang. I've seen this issue has been raised before (#7251, #3391, etc).

**Comment by JackBoosY** [comment]
cc @BillyONeal if he has some ideas.

**Comment by BillyONeal** [comment]
The ones reported before that I know about were all about `vcpkg_acquire_msys` we fixed by removing msys' pacman from the process. 

It is likely that one of the dependent ports is trying to prompt for input or something like that, but that isn't something we have seen ourselves...

**Comment by JackBoosY** [comment]
By reading the information you provided again, I believe that the build process is **NOT** really a hang, but a long time.
Can you provide the time from entering the installation command to `Configuring x86-windows` and from `Configuring x86-windows` to `Installing x86-windows`?

**Comment by ericwilliamsneu** [comment]
@JackBoosY I attempted to install the library on another machine with the intention of capturing the requested data, but unfortunately the problem shifted on this new machine. I was again required to hit enter to advance the process at certain points, but this time it would usually be after a build step, not a configure step. I'd watch the CPU usage on the machine skyrocket during the build as expected, but then it would die down to a nominal level. Several packages "hung" at this point (after the build had clearly completed, based on CPU usage) and the process did not advance until I hit enter. Immediately upon hitting enter, the process would leap forward. I'm starting to wonder if this could be a Powershell 7 problem, not a VCPKG problem.

I understand without the ability to duplicate this is impossible to investigate and squash. I'm amazed at the level of engagement you and the rest of the team have with the userbase. Thanks for providing and supporting a great tool. I don't know if you want to close this issue or leave it open with the more-information tag.

**Comment by JackBoosY** [comment]
@ericwilliamsneu Can you provide the content before and after hang up in the install log?

**Comment by mikedld** [comment]
For me, downloading of Strawberry Perl (OpenSSL's build dependency) is going way too slow and that's what is causing OpenSSL build to take a long time. I ended up downloading (with axel in 50 threads) and caching Strawberry Perl's ZIP file manually, and then copying it into downloads/ subdirectory before vcpkg starts downloading it on its own. Not sure why the speed is that low, but it might make sense to either report this to them and maybe provide an alternative download location pointing to some vcpkg or github server to speed things up.

**Comment by JackBoosY** [comment]
@mikedld  We tend to use github repo, but because some ports do not provide mirrors to github, or the version on github is too low compared to the official website, this caused this problem.

**Comment by mikedld** [comment]
I get that @JackBoosY, just thought you might be able to mirror it (or find an existing faster mirror)...

**Comment by JackBoosY** [comment]
Strawberry Perl only provides its binary on the [official website](https://strawberryperl.com/), not [github](https://github.com/StrawberryPerl/Perl-Dist-Strawberry/tags).

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

**Comment by deltaprophet** [comment]
I am facing same issue on windows 10. its already been 5+ hrs and its still not completed.
![image](https://user-images.githubusercontent.com/10917731/113387975-31f20000-9342-11eb-832e-7a8dec5a9869.png)

Library is still being built. Can you please suggest any other alternatives for installation?

**Comment by ericwilliamsneu** [comment]
The latest version of the vcpkg PCL package seems to actually correctly
build, but now is missing some critical features due to an incompatibility
with a graphics framework. One thing I did do in order to attempt to
correct this was insure that Quick Edit and Insert Mode are turned off in
PowerShell.
------------------------------
*From:* Pawan Wagh ***@***.***>
*Sent:* Friday, April 2, 2021 1:31 AM
*To:* microsoft/vcpkg ***@***.***>
*Cc:* Eric Williams ***@***.***>; Mention <
***@***.***>
*Subject:* Re: [microsoft/vcpkg] New to vcpkg - install of PCL taking 6+
hours (#14280)


I am facing same issue on windows 10. its already been 5+ hrs and its still
not completed.
[image: image]
<https://user-images.githubusercontent.com/10917731/113387975-31f20000-9342-11eb-832e-7a8dec5a9869.png>

Library is still being built. Can you please suggest any other alternatives
for installation?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/microsoft/vcpkg/issues/14280#issuecomment-812348685>,
or unsubscribe

**Comment by mzayarnyuk** [comment]
> For me, downloading of Strawberry Perl (OpenSSL's build dependency) is going way too slow (under 50 KiB/s with ZIP itself being about 140 MiB) and that's what is causing OpenSSL build to take a long time. I ended up downloading (with axel in 50 threads) and caching Strawberry Perl's ZIP file manually, and then copying it into downloads/ subdirectory before vcpkg starts downloading it on its own. Not sure why the speed is that low, but it might make sense to report this to them and maybe provide an alternative download location pointing to some vcpkg or github server to speed things up.

wow interest post; they fix it or not....
have slow arm build
