### ISSUE TITLE
[ffmpeg:x64-windows] build failure

### ISSUE THREAD

**Issue by hl1282456555** [microsoft/vcpkg#14287]
**Host Environment**
- OS: [Windows]
- Compiler: VS 2019

**To Reproduce**
`.\vcpkg.exe install ffmpeg[x264,zlib,avcodec,avformat,avisynthplus,avresample,mp3lame,nvcodec,nonfree,gpl,wavpack]:x64-windows`

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:85 (message):
    Command failed: ninja -v
    Working Directory: D:/vcpkg/buildtrees/avisynthplus/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\vcpkg\buildtrees\avisynthplus\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:305 (vcpkg_execute_required_process)
  ports/avisynthplus/portfile.cmake:13 (vcpkg_configure_cmake)
  scripts/ports.cmake:79 (include)

Error: Building package avisynthplus:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: avisynthplus:x64-windows
  Vcpkg version: 2020.06.15-nohash

[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/5455693/config-x64-windows-out.log)

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by PhoebeHui** [comment]
@hl1282456555, could you reinstall windows sdk by vs installer? see issue https://github.com/microsoft/vcpkg/issues/6324

Failures:
LINK : fatal error LNK1104: cannot open file 'ucrtd.lib'

**Comment by hl1282456555** [comment]
I installed the WDK before, which resulted in multiple versions of the Windows SDK. After uninstalling, everything worked normally.

> @hl1282456555, could you reinstall windows sdk by vs installer? see issue #6324
> 
> Failures:
> LINK : fatal error LNK1104: cannot open file 'ucrtd.lib'

Ohh, I installed the WDK before, which resulted in multiple versions of the Windows SDK. After uninstalling, everything worked normally.

**Comment by hl1282456555** [comment]
Now，the vcpkg build wavpack failed, D:\vcpkg\buildtrees\wavpack\src\f1b6756bbd-c6619d0720.clean\wavpackdll\wavpackdll.rc(10): fatal error C1083: Cannot open include file: 'afxres.h': No such file or directory

[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/5455908/install-x64-windows-dbg-out.log)

**Comment by PhoebeHui** [comment]
You need to install MFC and ATL related components.
For me, it locate in C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\atlmfc\include.

Please reference to install MFC and ATL related components
![image](https://user-images.githubusercontent.com/20694052/97521626-ecb75400-19d8-11eb-9e34-d7a2e1f315f3.png)

**Comment by hl1282456555** [comment]
Build succeeded when installed the ATL and MFC related components. Thank you.

**Comment by PhoebeHui** [comment]
Great!

**Comment by HppZ** [comment]
> .\vcpkg.exe install ffmpeg[nvcodec] --triplet=x64-uwp


failed.

=== CONFIGURING ===
ERROR: cuda requested, but not all dependencies are satisfied: ffnvcodec

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.
