### ISSUE TITLE
Bootstrap failing - recognizing the installed VS and SDKs but still throwing lots of errors

### ISSUE THREAD

**Issue by morganwest955** [microsoft/vcpkg#14289]
**Describe the bug**
I've cloned the repo and attempted running .\vcpkg\bootstrap-vcpkg.bat, but it fails with the final output as the following:

```
C:\Users\mdog9_000\Source\Repos\vcpkg\scripts\bootstrap.ps1 : Building vcpkg.exe failed. Please ensure you have
installed Visual Studio with the Desktop C++ workload and the Windows SDK for Desktop C++.
At line:1 char:4
+ & {& 'C:\Users\mdog9_000\Source\Repos\vcpkg\scripts\bootstrap.ps1' -v ...
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,bootstrap.ps1

ScriptHalted
At C:\Users\mdog9_000\Source\Repos\vcpkg\scripts\bootstrap.ps1:411 char:5
+     throw
+     ~~~~~
    + CategoryInfo          : OperationStopped: (:) [], RuntimeException
    + FullyQualifiedErrorId : ScriptHalted
```
I've attached the full verbose log.  I have gone as far as uninstalling all SDKs from the PC and reinstalling through the VS tools as I saw that work for somebody in a different bug report, but I didn't have such luck.  I also uninstalled every VS version except for 2017, and still am getting the same error.

**Environment**
- OS: Windows 10.0.19041 Build 19041
- Compiler: C++ SDK version 10.0.16299.0

**To Reproduce**
1. clone vcpkg to PC
2. navigate to vcpkg folder
3. run .\vcpkg\bootstrap-vcpkg.bat

**Expected behavior**
Failure to execute - output in logs

**Failure logs** 
[vcpkg-bootstrap-error.txt](https://github.com/microsoft/vcpkg/files/5456340/vcpkg-bootstrap-error.txt)

**Additional context**
For what it's worth, I've had this computer for 6 years and did my whole CS degree with it, so dev tools are less than organized, and everything could use some spring cleaning.

**Comment by BillyONeal** [comment]
>c:\users\mdog9_000\source\repos\vcpkg\toolsrc\include\vcpkg\base\files.h(22): error C2039: 'filesystem': is not a membe
r of 'std' [C:\Users\mdog9_000\Source\Repos\vcpkg\toolsrc\windows-bootstrap\vcpkg.vcxproj]

This looks like you have an old 2017 which is missing std::filesystem; we assume that if 2017 is in use that we should use std::filesystem rather than std::experimental::filesystem from 2015. Can you double check that that your C++ compiler is 19.18.x (which corresponds to Visual Studio 2017 version 15.9).

Here's an example from 2019 where the version is 19.28.x:

>C:\Dev>cl
>Microsoft (R) C/C++ Optimizing Compiler Version **19.28.29333** for x86
>Copyright (C) Microsoft Corporation.  All rights reserved.

**Comment by morganwest955** [comment]
There were a couple of cl.exe locations that were last modified on 4/24/2018, and they both generate this response.

```
PS C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\bin\Hostx64\x64> .\cl.exe
Microsoft (R) C/C++ Optimizing Compiler Version 19.13.26131.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.
```

So looks like it's on 19.13.x.
The VS version is Community 15.6.6, which is the most updated Community version as far as I am aware.

**Comment by StarGate-One** [comment]
The most recent version of Community Download for public consumption is VS 2017 is v15.9.28.
The cl version is:
->cl
Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27043 for x64
As @BillyONeal stated, try updating VS 2017 to the latest version, either using 
1. The currently installed Visual Studio Installer, or 
2. Help->Check For Updates within the VS 2017 IDE (Although I found on VS 2017 it does not always detect a new version where the visual studio installer does), or 
3. From https://my.visualstudio.com/Downloads?q=Visual%20Studio%202017, and download the updated Visual Studio Community 2017 (Version 15.9 dates 10/13/2020) installer - you may need to create a free Microsoft Account and Subscribe to the free "Visual Studio Dev Essentials" Subscription/Program https://my.visualstudio.com/Subscriptions

**Comment by morganwest955** [comment]
It worked!  Thank you two for your help.

**Comment by BillyONeal** [comment]
Thanks for the help @StarGate-One !

**Comment by StarGate-One** [comment]
No problem - you are welcome @morganwest955.
@BillyONeal - glad to help... You are welcome also!
