### ISSUE TITLE
[vcpkg] Locking `.vcpkg-root` fails on NFS drives

### ISSUE THREAD

**Issue by L0ric0** [microsoft/vcpkg#14281]
**Describe the bug**
When using a vcpkg in manifestmode with CMAKE_TOOLCHAIN_FILE cmake is unable to select a build program that is corresponding to "Unix Makefiles".

GNU Make is installed and in the PATH

**Environment**
- OS: Linux Debian stable
- Compiler: gcc8

**To Reproduce**
1. add vcpkg.json file
2. run cmake with CMAKE_TOOLCHAIN_FILE set to the vcpkg toolchain file

**Expected behavior**
installation of the pakages declared in the vcpkg.json file and configuration of the project

**Failure logs** 
```
16:26 $ cmake -B build/
-- Running vcpkg install
CMake Error at share/vcpkg/scripts/buildsystems/vcpkg.cmake:386 (message):
  Running vcpkg install - failed
Call Stack (most recent call first):
  /usr/share/cmake-3.13/Modules/CMakeDetermineSystem.cmake:94 (include)
  CMakeLists.txt:8 (project)


CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
```

**Additional context**
the toolchain file is selected in the CMakeLists.txt:
```
cmake_minimum_required(VERSION 3.10)

set(CMAKE_TOOLCHAIN_FILE "${CMAKE_CURRENT_SOURCE_DIR}/share/vcpkg/scripts/buildsystems/vcpkg.cmake"
    CACHE STRING "Vcpkg toolchain file")

set(CMAKE_CXX_STANDARD 17)

project(librethfeld VERSION 0.0.1)

file(GLOB_RECURSE SOURCES RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} "src/*.cpp")

add_library(librethfeld ${SOURCES})

target_include_directories(librethfeld PRIVATE include/librethfeld)
target_include_directories(librethfeld PUBLIC "${PROJECT_BINARY_DIR}/include")

find_package(Boost REQUIRED mpi serialization)
include_directories(${Boost_INCLUDE_DIRS})
target_link_libraries(librethfeld PRIVATE Boost::mpi Boost::serialization)

find_package(spdlog REQUIRED)
target_link_libraries(librethfeld PRIVATE spdlog::spdlog)
```

**Comment by JackBoosY** [comment]
cc @strega-nil

**Comment by strega-nil** [comment]
We should probably figure out a better way to do this, but basically when a toolchain is loaded, if it has a `FATAL_ERROR`, CMake then says that `CMAKE_MAKE_PROGRAM` is not set. The issue is that installing from vcpkg failed.

**Comment by L0ric0** [comment]
ok thanks. that tells me that:
```
Failed to take the filesystem lock on /home/lsteinert/scripts/monstr/share/librethfeld/share/vcpkg/.vcpkg-root:
    Bad file descriptor
```
but i know that the file exists. If it is relevant the filesystem is on a nfs volume

**Comment by strega-nil** [comment]
hm, yeah, that's probably relevant. We'll likely need to have a discussion about this... it's pretty important to lock vcpkg installations...

**Comment by strega-nil** [comment]
Likely, the solution is going to be "we'll add an environment variable to tell vcpkg not to take the lock"

**Comment by L0ric0** [comment]
is there a workaround for this for now (like telling vcpkg to use a lock file in another location)?

**Comment by strega-nil** [comment]
The lockfile is only used in manifest mode... do you mean you were able to run `vcpkg install` in your project directory?

**Comment by L0ric0** [comment]
yes

**Comment by spinicist** [comment]
> We should probably figure out a better way to do this, but basically when a toolchain is loaded, if it has a `FATAL_ERROR`, CMake then says that `CMAKE_MAKE_PROGRAM` is not set. The issue is that installing from vcpkg failed.
> 
> You should look at `build/vcpkg-manifest-install-out.log` to see the errors.

If you can somehow make the error message tell people to look at that log file, that would be great.

(This has hit me and my colleague twice now, due to errors in ports. I found this issue by searching for "CMAKE_MAKE_PROGRAM not set", but now I've looked at the log it's something else and not to do with NFS. Will report on a separate issue about the actual problem).
