### ISSUE TITLE
How do I install for x64 windows?

### ISSUE THREAD

**Issue by zliuchen** [microsoft/vcpkg#14296]
The default triplet when I run "vcpkg install xxx" is for x86. For example, after installation, "vcpkg list" shows the following

boost-vmd:x86-windows                              1.73.0           Boost vmd module

Then as I started Visual Studio, I can only run application for x86 configuration. If I change to x64, it looks like I need to install another vcpkg in order to maintain two separate library collections.
so my question is:
1. how to install for x64?
2. if I install multiple vcpkg, inside Visual Studio, how can I specify the toolchain to the correct vcpkg install?

Thanks.

**Comment by Link1J** [comment]
>1. how to install for x64?
add `:x64-windows` right after the package you want to install
>2. if I install multiple vcpkg, inside Visual Studio, how can I specify the toolchain to the correct vcpkg install?
It should detect the right one. At least with cmake it does.

**Comment by vicroms** [comment]
To get x64 libraries you need to use the `x64-windows` triplet. Use command `vcpkg help triplets` to see the list of available triplets.

To install libraries for a specific triplet you can use the notation `install <package>:<triplet>`, the command option `--triplet=<triplet>` or change you default triplet by setting a `VCPKG_DEFAULT_TRIPLET` environment variable. 

If the correct libraries are installed Visual Studio will automatically detect them when you change to x64 configuration.

Examples:

```
./vcpkg install boost-vmd:x64-windows
```

```
./vcpkg install boost-vmd --triplet=x64-windows
```

```
$env:VCPKG_DEFAULT_TRIPLET="x64-windows"
./vcpkg install rapidjson
```

**Comment by zliuchen** [comment]
Thanks for your answers!
