### ISSUE TITLE
Building package glib:x86-windows-static-md failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by tester0077** [microsoft/vcpkg#14297]
**Host Environment**
- OS: Win 10 64-bit - up-to-date
- Compiler:  MSVC 2019  - up-to-date

**To Reproduce**
 ./vcpkg install libxmlpp:x86-windows-static-md

**Failure logs** 
Computing installation plan...
The following packages will be built and installed:
  * glib[core]:x86-windows-static-md
  * glibmm[core]:x86-windows-static-md
  * libffi[core]:x86-windows-static-md
  * libsigcpp[core]:x86-windows-static-md
    libxmlpp[core]:x86-windows-static-md
  * pcre[core]:x86-windows-static-md
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x86-windows-static-md...
Starting package 1/6: libffi:x86-windows-static-md
Building package libffi[core]:x86-windows-static-md...
Could not locate cached archive: C:\Users\arnold\AppData\Local\vcpkg\archives\1d\1d8c39fd9a20fb6ecd86d52af377034b876ae321.zip
-- Using community triplet x86-windows-static-md. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: D:\pkg\vcpkg\triplets\community\x86-windows-static-md.cmake
-- Downloading https://github.com/libffi/libffi/archive/v3.3.tar.gz...
-- Extracting source D:/pkg/vcpkg/downloads/libffi-libffi-v3.3.tar.gz
-- Applying patch win64-disable-stackframe-check.patch
-- Applying patch win32-disable-stackframe-check.patch
-- Using source at D:/pkg/vcpkg/buildtrees/libffi/src/v3.3-8557367958.clean
-- Configuring x86-windows-static-md
-- Building x86-windows-static-md-dbg
-- Building x86-windows-static-md-rel
-- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz...
-- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst...
-- Using msys root at D:/pkg/vcpkg/downloads/tools/msys2/c809757c94447846
-- Fixing pkgconfig file: D:/pkg/vcpkg/packages/libffi_x86-windows-static-md/lib/pkgconfig/libffi.pc
-- Fixing pkgconfig file: D:/pkg/vcpkg/packages/libffi_x86-windows-static-md/debug/lib/pkgconfig/libffi.pc
-- Installing: D:/pkg/vcpkg/packages/libffi_x86-windows-static-md/share/libffi/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\arnold\AppData\Local\vcpkg\archives\1d\1d8c39fd9a20fb6ecd86d52af377034b876ae321.zip
Building package libffi[core]:x86-windows-static-md... done
Installing package libffi[core]:x86-windows-static-md...
Installing package libffi[core]:x86-windows-static-md... done
Elapsed time for package libffi:x86-windows-static-md: 12.42 s
Starting package 2/6: pcre:x86-windows-static-md
Building package pcre[core]:x86-windows-static-md...
Could not locate cached archive: C:\Users\arnold\AppData\Local\vcpkg\archives\39\39ef9c6c9bd54c358711833bae615ab2969d3e98.zip
-- Using community triplet x86-windows-static-md. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: D:\pkg\vcpkg\triplets\community\x86-windows-static-md.cmake
-- Downloading https://ftp.pcre.org/pub/pcre/pcre-8.44.zip...
-- Extracting source D:/pkg/vcpkg/downloads/pcre-8.44.zip
-- Applying patch pcre-8.44_suppress_cmake_and_compiler_warnings-errors.patch
-- Applying patch export-cmake-targets.patch
-- Using source at D:/pkg/vcpkg/buildtrees/pcre/src/pcre-8-5bdacbc1cb.clean
-- Configuring x86-windows-static-md
-- Building x86-windows-static-md-dbg
-- Building x86-windows-static-md-rel
-- Using msys root at D:/pkg/vcpkg/downloads/tools/msys2/c809757c94447846
-- Fixing pkgconfig file: D:/pkg/vcpkg/packages/pcre_x86-windows-static-md/lib/pkgconfig/libpcre.pc
-- Fixing pkgconfig file: D:/pkg/vcpkg/packages/pcre_x86-windows-static-md/lib/pkgconfig/libpcre16.pc
-- Fixing pkgconfig file: D:/pkg/vcpkg/packages/pcre_x86-windows-static-md/lib/pkgconfig/libpcre32.pc
-- Fixing pkgconfig file: D:/pkg/vcpkg/packages/pcre_x86-windows-static-md/lib/pkgconfig/libpcrecpp.pc
-- Fixing pkgconfig file: D:/pkg/vcpkg/packages/pcre_x86-windows-static-md/lib/pkgconfig/libpcreposix.pc
-- Fixing pkgconfig file: D:/pkg/vcpkg/packages/pcre_x86-windows-static-md/debug/lib/pkgconfig/libpcre.pc
-- Fixing pkgconfig file: D:/pkg/vcpkg/packages/pcre_x86-windows-static-md/debug/lib/pkgconfig/libpcre16.pc
-- Fixing pkgconfig file: D:/pkg/vcpkg/packages/pcre_x86-windows-static-md/debug/lib/pkgconfig/libpcre32.pc
-- Fixing pkgconfig file: D:/pkg/vcpkg/packages/pcre_x86-windows-static-md/debug/lib/pkgconfig/libpcrecpp.pc
-- Fixing pkgconfig file: D:/pkg/vcpkg/packages/pcre_x86-windows-static-md/debug/lib/pkgconfig/libpcreposix.pc
-- Installing: D:/pkg/vcpkg/packages/pcre_x86-windows-static-md/share/pcre/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\arnold\AppData\Local\vcpkg\archives\39\39ef9c6c9bd54c358711833bae615ab2969d3e98.zip
Building package pcre[core]:x86-windows-static-md... done
Installing package pcre[core]:x86-windows-static-md...
Installing package pcre[core]:x86-windows-static-md... done
Elapsed time for package pcre:x86-windows-static-md: 49.06 s
Starting package 3/6: glib:x86-windows-static-md
Building package glib[core]:x86-windows-static-md...
Could not locate cached archive: C:\Users\arnold\AppData\Local\vcpkg\archives\26\2661fc385f8ee0b223f3207975dade0ca5643092.zip
-- Using community triplet x86-windows-static-md. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: D:\pkg\vcpkg\triplets\community\x86-windows-static-md.cmake
-- Note: glib only supports dynamic library linkage. Building dynamic library.
-- Downloading https://ftp.gnome.org/pub/gnome/sources/glib/2.52/glib-2.52.3.tar.xz...
-- Extracting source D:/pkg/vcpkg/downloads/glib-2.52.3.tar.xz
-- Applying patch use-libiconv-on-windows.patch
-- Applying patch arm64-defines.patch
-- Applying patch fix-arm-builds.patch
-- Using source at D:/pkg/vcpkg/buildtrees/glib/src/2.52.3-34a15219ec.clean
-- Configuring x86-windows-static-md
-- Building x86-windows-static-md-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:142 (message):
    Command failed: D:/pkg/vcpkg/downloads/tools/cmake-3.18.4-windows/cmake-3.18.4-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v -j9
    Working Directory: D:/pkg/vcpkg/buildtrees/glib/x86-windows-static-md-dbg
    See logs for more information:
      D:\pkg\vcpkg\buildtrees\glib\install-x86-windows-static-md-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:93 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/glib/portfile.cmake:49 (vcpkg_install_cmake)
  scripts/ports.cmake:135 (include)

Error: Building package glib:x86-windows-static-md failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: glib:x86-windows-static-md
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.
PS D:\pkg\vcpkg> ./vcpkg update
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.
PS D:\pkg\vcpkg>

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by NancyLi1013** [comment]
Hi @tester0077 
Thanks for posting this issue.

Could you please try to rebuild based on this PR #14346?

**Comment by tester0077** [comment]
Hi Nancy,

unfortunately is did not fix my problem.

I'm attaching the output from my test:

    PS D:\pkg\vcpkg> ./vcpkg install libxmlpp:x86-windows-static-md
    Computing installation plan...
    The following packages will be built and installed:
       * glib[core]:x86-windows-static-md
       * glibmm[core]:x86-windows-static-md
       * libsigcpp[core]:x86-windows-static-md
         libxmlpp[core]:x86-windows-static-md
    Additional packages (*) will be modified to complete this operation.
    Detecting compiler hash for triplet x86-windows-static-md...
    Starting package 1/4: glib:x86-windows-static-md
    Building package glib[core]:x86-windows-static-md...
    Could not locate cached archive:
    C:\Users\arnold\AppData\Local\vcpkg\archives\26\2661fc385f8ee0b223f3207975dade0ca5643092.zip
    -- Using community triplet x86-windows-static-md. This triplet
    configuration is not guaranteed to succeed.
    -- [COMMUNITY] Loading triplet configuration from:
    D:\pkg\vcpkg\triplets\community\x86-windows-static-md.cmake
    -- Note: glib only supports dynamic library linkage. Building
    dynamic library.
    -- Using cached D:/pkg/vcpkg/downloads/glib-2.52.3.tar.xz
    -- Cleaning sources at
    D:/pkg/vcpkg/buildtrees/glib/src/2.52.3-34a15219ec.clean. Use
    --editable to skip cleaning for the packages you specify.
    -- Extracting source D:/pkg/vcpkg/downloads/glib-2.52.3.tar.xz
    -- Applying patch use-libiconv-on-windows.patch
    -- Applying patch arm64-defines.patch
    -- Applying patch fix-arm-builds.patch
    -- Using source at
    D:/pkg/vcpkg/buildtrees/glib/src/2.52.3-34a15219ec.clean
    -- Configuring x86-windows-static-md
    -- Building x86-windows-static-md-dbg
    CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:142
    (message):
         Command failed:
    D:/pkg/vcpkg/downloads/tools/cmake-3.18.4-windows/cmake-3.18.4-win32-x86/bin/cmake.exe
    --build . --config Debug --target install -- -v -j9
         Working Directory:
    D:/pkg/vcpkg/buildtrees/glib/x86-windows-static-md-dbg
         See logs for more information:
    D:\pkg\vcpkg\buildtrees\glib\install-x86-windows-static-md-dbg-out.log

    Call Stack (most recent call first):
       scripts/cmake/vcpkg_build_cmake.cmake:93
    (vcpkg_execute_build_process)
       scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
       ports/glib/portfile.cmake:49 (vcpkg_install_cmake)
       scripts/ports.cmake:135 (include)


    Error: Building package glib:x86-windows-static-md failed with:
    BUILD_FAILED
    Please ensure you're using the latest portfiles with `.\vcpkg
    update`, then
    submit an issue at https://github.com/Microsoft/vcpkg/issues including:
       Package: glib:x86-windows-static-md
       Vcpkg version: 2020.06.15-nohash

    Additionally, attach any relevant sections from the log files above.
    PS D:\pkg\vcpkg>

Let me know if you need anything else.

I will try to build the packages individually, and report back if I make 
any progress.

Tester0077

**Comment by tester0077** [comment]
Hi Nancy,

paying a bit more attention to the resulting messages, I think I 
understand why my build failed.

Trying to build glib[core]:x86-windows-static-md  alone, gives me the 
following error message:

/-- Note: glib only supports dynamic library linkage. Building dynamic 
library./

Looks like my efforts to build libxmlpp are doomed unless I opt for a DLL.

Not my real preference, but if I get stuck, I may have to reconsider. 
For now, I'll simply have to forget about libxmlppp

Tester0077

**Comment by NancyLi1013** [comment]
Hi @tester0077 

You're right, `glib `only supports dynamic build. Sorry, I missed this point.

**Comment by NancyLi1013** [comment]
Another point needs to be mentioned here, the triplet `x86-windows-static-md` is listed in _triplets/community_ folder, which is an unofficial triplet.

When you build these triplets, it will post the messages like this

```
  -- Using community triplet x86-windows-static-md. This triplet
    configuration is not guaranteed to succeed.
```

https://github.com/microsoft/vcpkg/blob/master/docs/users/triplets.md#community-triplets

**Comment by JonLiu1993** [comment]
@tester0077 ,Thanks for posting this issue. glib only supports dynamic build. If there are process or new change about support of static, please reopen this issue.
