### ISSUE TITLE
[<realsense2>] build failure

### ISSUE THREAD

**Issue by Zlavine** [microsoft/vcpkg#14302]
**Host Environment**
- OS: windows 10
- Compiler:  visual studio 2019 community

**To Reproduce**
`./vcpkg install realsense2

**Failure logs** 
E:\SOFTWARE\vcpkg\vcpkg>.\vcpkg install realsense2
Computing installation plan...
The following packages will be built and installed:
    realsense2[core]:x86-windows
Detecting compiler hash for triplet x86-windows...
Starting package 1/1: realsense2:x86-windows
Building package realsense2[core]:x86-windows...
Could not locate cached archive: C:\Users\cxc\AppData\Local\vcpkg\archives\db\db2b37ae15914851f6e82811d32337dcf3a4f916.zip
-- Downloading https://github.com/IntelRealSense/librealsense/archive/0adceb9dc6fce63c348346e1aef1b63c052a1db9.tar.gz...
-- Downloading https://github.com/IntelRealSense/librealsense/archive/0adceb9dc6fce63c348346e1aef1b63c052a1db9.tar.gz... Failed. Status: 35;"SSL connect error"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:182 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:133 (vcpkg_download_distfile)
  ports/realsense2/portfile.cmake:1 (vcpkg_from_github)
  scripts/ports.cmake:135 (include)

Error: Building package realsense2:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: realsense2:x86-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by PhoebeHui** [comment]
@Zlavine, could you try the following workaround?

1. Download https://github.com/IntelRealSense/librealsense/archive/0adceb9dc6fce63c348346e1aef1b63c052a1db9.tar.gz file manually
2. Put it to downloads folder.
3. Rename it to ' IntelRealSense-librealsense-0adceb9dc6fce63c348346e1aef1b63c052a1db9.tar.gz
4. Try to install it again.

**Comment by Zlavine** [comment]
> @Zlavine, could you try the following workaround?
> 
> 1. Download https://github.com/IntelRealSense/librealsense/archive/0adceb9dc6fce63c348346e1aef1b63c052a1db9.tar.gz file manually
> 2. Put it to downloads folder.
> 3. Rename it to ' IntelRealSense-librealsense-0adceb9dc6fce63c348346e1aef1b63c052a1db9.tar.gz
> 4. Try to install it again.

Thank you very much, the problem has been solved
