### ISSUE TITLE
[icu:x64-windows] build failure - CMake -E tar xzf gawk-5.1.0-1-x86_64.pkg.tar.xz

### ISSUE THREAD

**Issue by socuwn** [microsoft/vcpkg#14300]
**Host Environment**
- OS: Windows 10
- CMake: 3.18.0
- VisualStudio 2019 / msbuild: 16.7.0+b89cb5fde for .NET Framework
- cl.exe: 19.27.29112 for x64

**To Reproduce**
First discovered with:
`.\vcpkg.exe install qt5:x64-windows`

root cause:
`.\vcpkg.exe install icu:x64-windows`

**Failure logs**
```
Computing installation plan...
The following packages will be built and installed:
    icu[core]:x64-windows
Detecting compiler hash for triplet x64-windows...
Starting package 1/1: icu:x64-windows
Building package icu[core]:x64-windows...
Could not locate cached archive: C:\Users\j\AppData\Local\vcpkg\archives\7c\7c0c60f42525984e00fc215216b40650f1d4e982.zip
-- Using cached F:/vcpkg/downloads/icu4c-67_1-src.tgz
-- Cleaning sources at F:/vcpkg/buildtrees/icu/src/c-67_1-src-39ba50b26e.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source F:/vcpkg/downloads/icu4c-67_1-src.tgz
-- Applying patch F:/vcpkg/ports/icu/disable-escapestr-tool.patch
-- Applying patch F:/vcpkg/ports/icu/remove-MD-from-configure.patch
-- Applying patch F:/vcpkg/ports/icu/fix_parallel_build_on_windows.patch
-- Applying patch F:/vcpkg/ports/icu/fix-extra.patch
-- Using source at F:/vcpkg/buildtrees/icu/src/c-67_1-src-39ba50b26e.clean
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:106 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" -E tar xzf F:/vcpkg/downloads/msys-gawk-5.1.0-1-x86_64.pkg.tar.xz
    Working Directory: F:/vcpkg/downloads/tools/msys2/4fbc9d9dcfa221de.tmp
    Error code: 1
    See logs for more information:
 
Call Stack (most recent call first):
  scripts/cmake/vcpkg_acquire_msys.cmake:319 (vcpkg_execute_required_process)
  ports/icu/portfile.cmake:80 (vcpkg_acquire_msys)
  scripts/ports.cmake:135 (include)


Error: Building package icu:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: icu:x64-windows
  Vcpkg version: 2020.06.15-nohash
```

**Logfile:** ***F:\vcpkg\buildtrees\icu\msys-x64-windows-6-err.log***
```
CMake Error: Problem with archive_write_header(): Can't create '\\?\F:\vcpkg\downloads\tools\msys2\4fbc9d9dcfa221de.tmp\usr\bin\gawk.exe'
CMake Error: Current file: usr/bin/gawk.exe
CMake Error: Problem extracting tar: F:/vcpkg/downloads/msys-gawk-5.1.0-1-x86_64.pkg.tar.xz
```

**Additional context**
I have tried removing msys-gawk-5.1.0-1-x86_64.pkg.tar.xz from scripts/cmake/vcpkg_execute_required_process.cmake, and unpacking it manually. 

7-zip fails with the error:
***Can not create hard link ..\gawk.exe: ..\gawk-5.1.0.exe***

updating with:
`.\vcpkg.exe update` and `git pull` does nothing

**Comment by PhoebeHui** [comment]
@socuwn, could you try the solution from https://github.com/microsoft/vcpkg/issues/6059#issuecomment-483141555, and see if the issue still persist?

**Comment by socuwn** [comment]
@PhoebeHui, beta utf-8 was already ticked off, tried with it ticked on; but that made no difference.

I'm starting to suspect something wrong with the msys tar: `https://repo.msys2.org/msys/x86_64/gawk-5.1.0-1-x86_64.pkg.tar.xz`
I've extracted `https://cygwin.uib.no/x86_64/release/gawk/gawk-5.1.0-1.tar.xz`  successfully.
But I am failing to replace the msys with cygwin.
I am also not sure if I can just put a cygwin package in there and expect it to be compatible..(?)

**Comment by socuwn** [comment]
I forgot to mention I moved the vcpkg folder to another location / drive.

It seems windows 10 did not like creating symbolic links there or after I moved it.
Fixed problem by reinstalling vcpkg at a different location and drive.

**Comment by PhoebeHui** [comment]
Glad you got the issue fixed.

**Comment by socuwn** [comment]
@PhoebeHui me too!

Some additional information:
I suspect it might be something with the fileformat. 
The one that works is on a NTFS formatted drive. The one that failed was on FAT32.
I tried with a clean install on the FAT32 drive and got a different problem this time, much like described in #1549.
