### ISSUE TITLE
VsCode cmake-tools plugin hangs when using the vcpkg toolchain file

### ISSUE THREAD

**Issue by bjude** [Microsoft/vcpkg#1431]
The configure step (of cmake) hangs when using the cmake-tools pluging for VsCode.

I have setup vcpkg and installed it. The following lines were added to my vscode user settings in order for the cmake tool to find my toolchain file.
```
"cmake.configureSettings": {
    "CMAKE_TOOLCHAIN_FILE" : "D:/Code/vcpkg/scripts/buildsystems/vcpkg.cmake"
},
```

After running cmake with some extra flags for verbosity i could see that it hanging on the getWindowsSdk.ps1 script. More details can be found [here](https://github.com/vector-of-bool/vscode-cmake-tools/issues/202)

I got everything working by modifying the powershell call [here](https://github.com/Microsoft/vcpkg/blob/master/scripts/cmake/vcpkg_get_windows_sdk.cmake#L4) adding ```INPUT_FILE NUL``` like so:

```
execute_process(
    COMMAND powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "& {& '${VCPKG_ROOT_DIR}/scripts/getWindowsSDK.ps1'}" 2>&1
    INPUT_FILE NUL
    OUTPUT_VARIABLE WINDOWS_SDK
    RESULT_VARIABLE error_code)
```

I'll open a pull request if theres no objections here.

**Comment by ras0219-msft** [comment]
Thanks for such a detailed issue report!

I'd be happy to merge a PR if you'd make one, or I can make the change myself (I'll do that locally for testing now).

**Comment by ras0219-msft** [comment]
I was unable to use the cmake-tools extension locally to fully reproduce the issue, but it didn't introduce any regressions so I've merged the change.

Thanks again for reporting this issue!
