### ISSUE TITLE
How do I link librsync 

### ISSUE THREAD

**Issue by Amf1k** [microsoft/vcpkg#14316]
When asking a question please also include where you looked for an answer (so we can update the documentation if needed).

i have installed librsync from vcpkg and want to link it with my code.

> vcpkg.exe install librsync
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
Computing installation plan...
A suitable version of cmake was not found (required v3.17.2). Downloading portable cmake v3.17.2...
Downloading cmake...
  https://github.com/Kitware/CMake/releases/download/v3.17.2/cmake-3.17.2-win32-x86.zip -> C:\vcpkg\downloads\cmake-3.17.2-win32-x86.zip
Extracting cmake...
The following packages will be built and installed:
    librsync[core]:x86-windows
Detecting compiler hash for triplet x86-windows...
Starting package 1/1: librsync:x86-windows
Building package librsync[core]:x86-windows...
Could not locate cached archive: C:\Users\amf1k\AppData\Local\vcpkg\archives\a6\a64e4163b63ae93022322531f0bf4926a6278d11.zip
-- Note: librsync only supports static library linkage. Building static library.
-- Using cached C:/vcpkg/downloads/librsync-librsync-d1938c387e86ab5bbf7cb2e84244229c5bbd5ebf.tar.gz
-- Cleaning sources at C:/vcpkg/buildtrees/librsync/src/9c5bbd5ebf-c12dd0e075.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg/downloads/librsync-librsync-d1938c387e86ab5bbf7cb2e84244229c5bbd5ebf.tar.gz
-- Using source at C:/vcpkg/buildtrees/librsync/src/9c5bbd5ebf-c12dd0e075.clean
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Installing: C:/vcpkg/packages/librsync_x86-windows/share/librsync/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\amf1k\AppData\Local\vcpkg\archives\a6\a64e4163b63ae93022322531f0bf4926a6278d11.zip
Building package librsync[core]:x86-windows... done
Installing package librsync[core]:x86-windows...
Installing package librsync[core]:x86-windows... done
Elapsed time for package librsync:x86-windows: 31.2 s
Total elapsed time: 35.56 s

after installation i tried to call find_package (librsync) or add_library (librsync) but cmake says that

> CMake Error at C:/vcpkg/scripts/buildsystems/vcpkg.cmake:530 (_find_package):
  By not providing "Findlibrsync.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "librsync",
  but CMake did not find one.
  Could not find a package configuration file provided by "librsync" with any
  of the following names:
    librsyncConfig.cmake
    librsync-config.cmake
  Add the installation prefix of "librsync" to CMAKE_PREFIX_PATH or set
  "librsync_DIR" to a directory containing one of the above files.  If
  "librsync" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:5 (find_package)

My CmakeList.txt

> cmake_minimum_required(VERSION 3.17)
project(main)
set(CMAKE_CXX_STANDARD 17)
find_package(librsync REQUIRED)
add_executable(main main.cpp)
target_link_libraries(main PRIVATE librsync)

**Comment by PhoebeHui** [comment]
@Amf1k, not all libraries in vcpkg offer CMake integration support (such support depends on the library maintainers, not on vcpkg). In the case of `librsync ` you must manually link the library and include files in your `CMakeLists.txt`. 

Here is an example of how to use packages without `find_package()` support [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/examples/installing-and-using-packages.md#handling-libraries-without-native-cmake-support).

**Comment by PhoebeHui** [comment]
@Amf1k feel free to reopen this issue if it still be a question for you.
