### ISSUE TITLE
[darknet:x64-windows] BUILD time too long - slow download from https://pjreddie.com

### ISSUE THREAD

**Issue by fodortibi** [microsoft/vcpkg#14315]
****

**Is your feature request related to a problem? Please describe.**
I am happy to successfully build the darknet:x64-windows package finally, thank you for your great work and effort!
Unfortunately the build time was very long, about 7.2h, I felt in the Stone Age. :(
For example 7 files have been downloaded from https://pjreddie.com that took more than 2h.

-- Downloading https://pjreddie.com/media/files/yolov3.weights...
-- Downloading https://pjreddie.com/media/files/yolov3-openimages.weights...
-- Downloading https://pjreddie.com/media/files/yolov2.weights...
-- Downloading https://pjreddie.com/media/files/yolov3-tiny.weights...
-- Downloading https://pjreddie.com/media/files/yolov2-tiny.weights...
-- Downloading https://pjreddie.com/media/files/darknet53.conv.74...
-- Downloading https://pjreddie.com/media/files/darknet19_448.conv.23...

**Proposed solution**
Could you please host the mentioned files on a faster server (e.g. GitHub)?

**Describe alternatives you've considered**
N/A

**Additional context**
Depending on external servers is a risk in case of unexpected downtime.

**Comment by LilyWangL** [comment]
Thanks for posting this issue. I think it is related with download speed of internet on local. I use 1.217 hour to install `darknet[weights]`.
![image](https://user-images.githubusercontent.com/47812810/97962963-2d580880-1df1-11eb-8a0e-b84a25961fce.png)

**Comment by fodortibi** [comment]
> Thanks for posting this issue. I think it is related with download speed of internet on local. I use 1.217 hour to install `darknet[weights]`.
> ![image](https://user-images.githubusercontent.com/47812810/97962963-2d580880-1df1-11eb-8a0e-b84a25961fce.png)

Hello,
Thank you for the response.  For youe clarification, I have a good internet access with 500Mbit/s.
The mentioned 7 files are about 1GB, and should be downloaded within seconds, in worst case within minutes but not in hours.
The download from https://pjreddie.com takes too long, there seems to be a limited bandwidth.
The mentioned files should be stored directly in Github or in another fast connection site, for example Google Drive.
Thank you if you can store the mentioned files within vcpkg.

**Comment by JackBoosY** [comment]
Hi @fodortibi, can you provide the related github url?

Thanks.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
