### ISSUE TITLE
[sqlite3] Provide .pc pkg-config files 

### ISSUE THREAD

**Issue by traversaro** [microsoft/vcpkg#14327]
**Is your feature request related to a problem? Please describe.**
The `sqlite3` library on Unix system provides `.pc` files (see for example https://packages.debian.org/jessie/amd64/libsqlite3-dev/filelist), but the CMake-based build system maintained in vcpkg does not install them. This may be problematic because downstream build system that depend on `sqlite3` may expect this `.pc` files to be available on Linux/macOS .

**Proposed solution**
We should modify the `sqlite3` CMake-based build system maintained in vcpkg to emit `.pc` as done by the native `sqlite3` build system.  

**Additional context**
This issue is similar in https://github.com/microsoft/vcpkg/issues/11817 and emerged in the same context: while packaging the ignition-transport library and its .pc files.

**Comment by autoantwort** [comment]
This can be closed, there is now a `.pc` file
