### ISSUE TITLE
[New Port Request] Jinja2Cpp

### ISSUE THREAD

**Issue by AntonioCS** [microsoft/vcpkg#14332]
Library name: Jinja2Cpp

Library description: C++ implementation of the Jinja2 Python template engine. This library brings support of powerful Jinja2 template features into the C++ world, reports dynamic HTML pages and source code generation.

Source repository URL: https://github.com/jinja2cpp/Jinja2Cpp

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
There is a already a port for a somewhat similar library [jinja2cpplight](https://github.com/hughperkins/Jinja2CppLight) but this one seems to have been discontinued while Jinja2Cpp had a commit done this year (2020)

**Comment by AntonioCS** [comment]
This was not a good-first-issue.
Here is my attempt: https://github.com/AntonioCS/vcpkg/tree/feature/port/jinja2cpp/ports/jinja2cpp
This was with the help of the good people at #vcpkg in include (discord)

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
