### ISSUE TITLE
Existing cmake project does not pickup vcpkg installed cairo lib

### ISSUE THREAD

**Issue by zcream** [microsoft/vcpkg#14335]
I am using an existing cmake project via OpenFolders. The cmake build fails with the following error.

> 1> Command line: "cmd.exe" /c ""C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe"  -G "Ninja" -DCMAKE_INSTALL_PREFIX:PATH="C:\Users\Administrator\Documents\lunasvg-master\out\install\x64-Debug" -DCMAKE_CXX_COMPILER:FILEPATH="C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/HostX64/x64/cl.exe"  -DCMAKE_TOOLCHAIN_FILE="C:/Users/Administrator/vcpkg/scripts/buildsystems/vcpkg.cmake" -DCMAKE_BUILD_TYPE="Debug" -DCMAKE_MAKE_PROGRAM="C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\Ninja\ninja.exe" "C:\Users\Administrator\Documents\lunasvg-master" 2>&1"
1> Working directory: C:\Users\Administrator\Documents\lunasvg-master\out\build\x64-Debug
1> [CMake] CMake Error at C:/Users/Administrator/vcpkg/scripts/buildsystems/vcpkg.cmake:552 (_find_package):
1> [CMake]   Could not find a package configuration file provided by "cairo" with any of
1> [CMake]   the following names:
1> [CMake] 
1> [CMake]     cairoConfig.cmake
1> [CMake]     cairo-config.cmake
1> [CMake] 
1> [CMake]   Add the installation prefix of "cairo" to CMAKE_PREFIX_PATH or set
1> [CMake]   "cairo_DIR" to a directory containing one of the above files.  If "cairo"
1> [CMake]   provides a separate development package or SDK, be sure it has been
1> [CMake]   installed.
1> [CMake] Call Stack (most recent call first):
1> [CMake]   CMakeLists.txt:21 (find_package)
1> [CMake] -- Configuring incomplete, errors occurred!

cairo is built and used for other visual studio projects. 
[CMakeOutput.log](https://github.com/microsoft/vcpkg/files/5470277/CMakeOutput.log)

**Comment by JackBoosY** [comment]
Which triplet did you use to build Cairo?

**Comment by zcream** [comment]
x64-windows-static

**Comment by JackBoosY** [comment]
Sorry for late, you should use the following code instead:
```
find_package(unofficial-cairo CONFIG REQUIRED)
target_link_libraries(main PRIVATE unofficial::cairo::cairo)
```

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
