### ISSUE TITLE
failed cmake install (?) when running ./bootstrap-vcpkg.sh

### ISSUE THREAD

**Issue by CtrlAltWaverick** [microsoft/vcpkg#14334]
I get the error:

```
/home/[USERNAME]/vcpkg/downloads/tools/cmake-3.18.4-linux/cmake-3.18.4-Linux-x86_64/bin/cmake: 1: /home/[USERNAME]/vcpkg/downloads/tools/cmake-3.18.4-linux/cmake-3.18.4-Linux-x86_64/bin/cmake: ELF: not found
/home/[USERNAME]/vcpkg/downloads/tools/cmake-3.18.4-linux/cmake-3.18.4-Linux-x86_64/bin/cmake: 1: /home/[USERNAME]/vcpkg/downloads/tools/cmake-3.18.4-linux/cmake-3.18.4-Linux-x86_64/bin/cmake: Syntax error: Unterminated quoted string
```

**Comment by NancyLi1013** [comment]
Hi @CtrlAltWaverick 
Thanks for posting this issue.

I cannot reproduce this on my machine (Ubuntu 18.04 with gcc 9.2.1).
Could you please provide the environment that you build and the build process?

`�ELF�����: not found`

The symbol seems to be not recognized. Could you please help provide the proper format?

**Comment by NancyLi1013** [comment]
@CtrlAltWaverick 

Could you please provide your test environment info?

OS: 
Compiler: 
Steps to reproduce:

Thanks.

**Comment by NancyLi1013** [comment]
Closing this issue for no response.

Please feel free to reopen this issue if it is still a problem for you.
