### ISSUE TITLE
[New Port Request] intel media sdk

### ISSUE THREAD

**Issue by sstsai** [microsoft/vcpkg#14342]
Library name: intel media sdk

Library description: Intel® Media SDK provides a plain C API to access hardware-accelerated video decode, encode and filtering on Intel® Gen graphics hardware platforms.

Source repository URL: https://github.com/Intel-Media-SDK/MediaSDK

Project homepage (if different from the source repository): https://software.intel.com/content/www/us/en/develop/tools/media-sdk.html

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
