### ISSUE TITLE
[vcpkg] Enable finer-grained portfile sections

### ISSUE THREAD

**Issue by ras0219-msft** [microsoft/vcpkg#1434]
From https://github.com/Microsoft/vcpkg/pull/1205#issuecomment-308566621:
>Split the control files into cleaner stages: E.g: file-load; extract-source; patch; configure; build; copy-install. And allow install command to stop at a certain stage.

This is widely done by all other package systems. See Homebrew, Pacman, Apt, and Gentoo for examples.

**Comment by dada2048** [comment]
Allowing the install command to *start* at a certain stage would be very useful too. Rebuilding a large library every time you tweak a small detail of the install step can make developing a port a bit painful.

**Comment by PhoebeHui** [comment]
No more discussion need here, looks the feature currently supported, this issue can be closed now.
