### ISSUE TITLE
[fmt] build failure

### ISSUE THREAD

**Issue by hosongguang** [microsoft/vcpkg#14345]
**Host Environment**
- Package: fmt:x86-windows
- Vcpkg version: 2020.06.15-nohash
- OS: Windows 10 Enterprise (Build: 19041.572)

**To Reproduce**
`./vcpkg install fmt`

-- Using cached C:/Users/Nigel Ho/Documents/GitProjects/vcpkg/downloads/fmtlib-fmt-4fe0b11195b7cd71f39253c44db2c9dddf6b82d4.tar.gz
-- Cleaning sources at C:/Users/Nigel Ho/Documents/GitProjects/vcpkg/buildtrees/fmt/src/dddf6b82d4-f2c5fef865.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/Nigel Ho/Documents/GitProjects/vcpkg/downloads/fmtlib-fmt-4fe0b11195b7cd71f39253c44db2c9dddf6b82d4.tar.gz
-- Applying patch fix-warning4189.patch
-- Using source at C:/Users/Nigel Ho/Documents/GitProjects/vcpkg/buildtrees/fmt/src/dddf6b82d4-f2c5fef865.clean
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Installing: C:/Users/Nigel Ho/Documents/GitProjects/vcpkg/packages/fmt_x86-windows/share/fmt/copyright
-- Using msys root at C:/Users/Nigel Ho/Documents/GitProjects/vcpkg/downloads/tools/msys2/c809757c94447846
-- Fixing pkgconfig file: C:/Users/Nigel Ho/Documents/GitProjects/vcpkg/packages/fmt_x86-windows/lib/pkgconfig/fmt.pc
-- CHECK_LIB_fmt_RELEASE:CHECK_LIB_fmt_RELEASE-NOTFOUND
CMake Error at scripts/cmake/vcpkg_fixup_pkgconfig.cmake:232 (message):
  Library "fmt" was not found! If it is a system library use the
  SYSTEM_LIBRARIES parameter for the vcpkg_fixup_pkgconfig call! Otherwise,
  correct the *.pc file
Call Stack (most recent call first):
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:298 (vcpkg_fixup_pkgconfig_check_files)
  ports/fmt/portfile.cmake:44 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:135 (include)

Error: Building package fmt:x86-windows failed with: BUILD_FAILED

**Comment by PhoebeHui** [comment]
@hosongguang , please create a clone without space in vcpkg path, same issue with #13103, and would fix by PR #13126.
