### ISSUE TITLE
Building package bzip2:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by Max-Keyn** [microsoft/vcpkg#14353]
**Host Environment**
- OS: Windows
- Compiler: MSVC 14.27

**To Reproduce**
`./vcpkg install hpx`

**Failure logs** 
 Package: bzip2:x86-windows
  Vcpkg version: 2020.06.15-nohash

**Long Version**
Computing installation plan...
The following packages will be built and installed:
  * boost-accumulators[core]:x86-windows
  * boost-align[core]:x86-windows
  * boost-asio[core]:x86-windows
  * boost-bimap[core]:x86-windows
  * boost-compute[core]:x86-windows
  * boost-context[core]:x86-windows
  * boost-coroutine[core]:x86-windows
  * boost-date-time[core]:x86-windows
  * boost-dynamic-bitset[core]:x86-windows
  * boost-iostreams[core]:x86-windows
  * boost-locale[core]:x86-windows
  * boost-lockfree[core]:x86-windows
  * boost-multi-array[core]:x86-windows
  * boost-multi-index[core]:x86-windows
  * boost-multiprecision[core]:x86-windows
  * boost-odeint[core]:x86-windows
  * boost-parameter[core]:x86-windows
  * boost-phoenix[core]:x86-windows
  * boost-pool[core]:x86-windows
  * boost-program-options[core]:x86-windows
  * boost-property-map[core]:x86-windows
  * boost-property-tree[core]:x86-windows
  * boost-proto[core]:x86-windows
  * boost-random[core]:x86-windows
  * boost-serialization[core]:x86-windows
  * boost-spirit[core]:x86-windows
  * boost-thread[core]:x86-windows
  * boost-tokenizer[core]:x86-windows
  * boost-tti[core]:x86-windows
  * boost-ublas[core]:x86-windows
  * boost-units[core]:x86-windows
  * boost-uuid[core]:x86-windows
  * boost-variant[core]:x86-windows
  * bzip2[core]:x86-windows
    hpx[core]:x86-windows
  * hwloc[core]:x86-windows
  * liblzma[core]:x86-windows
  * openssl[core]:x86-windows
  * openssl-windows[core]:x86-windows
  * zlib[core]:x86-windows
  * zstd[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x86-windows...
Starting package 1/41: bzip2:x86-windows
Building package bzip2[core]:x86-windows...
Could not locate cached archive: C:\Users\Gigabyte B450 AorusE\AppData\Local\vcpkg\archives\c5\c5e39bafaae93755f388c629a1415676ce3994b4.zip
-- Using cached C:/Users/Gigabyte B450 AorusE/source/repos/vcpkg/downloads/bzip2-75a94bea3918e612b879d6a11ca64b8689526147.tar.gz
-- Cleaning sources at C:/Users/Gigabyte B450 AorusE/source/repos/vcpkg/buildtrees/bzip2/src/8689526147-1ef169fbaa.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/Gigabyte B450 AorusE/source/repos/vcpkg/downloads/bzip2-75a94bea3918e612b879d6a11ca64b8689526147.tar.gz
-- Applying patch fix-import-export-macros.patch
-- Using source at C:/Users/Gigabyte B450 AorusE/source/repos/vcpkg/buildtrees/bzip2/src/8689526147-1ef169fbaa.clean
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Using msys root at C:/Users/Gigabyte B450 AorusE/source/repos/vcpkg/downloads/tools/msys2/c809757c94447846
-- Fixing pkgconfig file: C:/Users/Gigabyte B450 AorusE/source/repos/vcpkg/packages/bzip2_x86-windows/lib/pkgconfig/bzip2.pc
-- CHECK_LIB_bz2_RELEASE:CHECK_LIB_bz2_RELEASE-NOTFOUND
CMake Error at scripts/cmake/vcpkg_fixup_pkgconfig.cmake:232 (message):
  Library "bz2" was not found! If it is a system library use the
  SYSTEM_LIBRARIES parameter for the vcpkg_fixup_pkgconfig call! Otherwise,
  correct the *.pc file
Call Stack (most recent call first):
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:298 (vcpkg_fixup_pkgconfig_check_files)
  ports/bzip2/portfile.cmake:43 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:135 (include)

Error: Building package bzip2:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: bzip2:x86-windows
  Vcpkg version: 2020.06.15-nohash

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by Neumann-A** [comment]
Move vcpkg to a path without spaces
