### ISSUE TITLE
[New Port Request] mavlink

### ISSUE THREAD

**Issue by seanyen** [microsoft/vcpkg#14361]
Library name: MAVLink

Library description: 
MAVLink -- Micro Air Vehicle Message Marshalling Library. 
MAVLink is a very lightweight, header-only message library for communication between drones and/or ground control stations.

Source repository URL: https://github.com/mavlink/mavlink

Project homepage (if different from the source repository): http://mavlink.io/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

C and C++ projection.

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
