### ISSUE TITLE
[vcpkg_copy_tool_dependencies] Shouldn't use PowerShell on non-Windows

### ISSUE THREAD

**Issue by jackobski** [microsoft/vcpkg#14369]
**Host Environment**
- OS: [Linux]
- Compiler: revision

**To Reproduce**
`./vcpkg install gtkmm`

**Failure logs** 
Error: Building package glib:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:

Starting package 6/29: glib:x64-linux
Building package glib[core]:x64-linux...
Could not locate cached archive: /home/jacobski/.cache/vcpkg/archives/07/0718b8f98e514b50ba35e4175ba022064f8cedec.zip
-- Downloading https://ftp.gnome.org/pub/gnome/sources/glib/2.52/glib-2.52.3.tar.xz...
-- Extracting source /home/jacobski/vcpkg/downloads/glib-2.52.3.tar.xz
-- Applying patch use-libiconv-on-windows.patch
-- Applying patch arm64-defines.patch
-- Applying patch fix-arm-builds.patch
-- Using source at /home/jacobski/vcpkg/buildtrees/glib/src/2.52.3-34a15219ec.clean
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
CMake Error at scripts/cmake/vcpkg_copy_tool_dependencies.cmake:22 (message):
  Could not find PowerShell Core; please open an issue to report this.
Call Stack (most recent call first):
  ports/glib/portfile.cmake:53 (vcpkg_copy_tool_dependencies)
  scripts/ports.cmake:135 (include)

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by JackBoosY** [comment]
Should be fixed by #14366.
Duplicated to #14358.
