### ISSUE TITLE
[vcpkg pcl:x64-windows] build failed.

### ISSUE THREAD

**Issue by Caill0429** [microsoft/vcpkg#14364]
OS Version: win10
VS version: vs2015 update3 community.
Vcpkg version: 2020.06.15-nohash
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/5478081/install-x64-windows-dbg-out.log)

error log:
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:142 (message):
    Command failed: E:/SVNRepositories/vcpkg/downloads/tools/cmake-3.18.4-windows/cmake-3.18.4-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v -j13
    Working Directory: E:/SVNRepositories/vcpkg/buildtrees/pcl/x64-windows-dbg
    See logs for more information:
      E:\SVNRepositories\vcpkg\buildtrees\pcl\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:93 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/pcl/portfile.cmake:60 (vcpkg_install_cmake)
  scripts/ports.cmake:135 (include)

Error: Building package pcl:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: pcl:x64-windows
  Vcpkg version: 2020.06.15-nohash

**Comment by tony-singh-dhami** [comment]
I'm also getting a similar traceback when building another tool.

OS Version: win10
VS version: vs2017 Professional
Vcpkg version: 2020.06.15-nohash
[install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/5483613/install-x86-windows-dbg-out.log)

-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:142 (message):
    Command failed: C:/dev/vcpkg/downloads/tools/cmake-3.18.4-windows/cmake-3.18.4-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v -j65
    Working Directory: C:/dev/vcpkg/buildtrees/openimageio/x86-windows-dbg
    See logs for more information:
      C:\dev\vcpkg\buildtrees\openimageio\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:93 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/openimageio/portfile.cmake:66 (vcpkg_install_cmake)
  scripts/ports.cmake:135 (include)

Error: Building package openimageio:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openimageio:x86-windows
  Vcpkg version: 2020.06.15-nohash

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Duplicate with #13002, so I am closing this issue for now.
