### ISSUE TITLE
a build failure of intel-mkl:x64-windows

### ISSUE THREAD

**Issue by zliuchen** [microsoft/vcpkg#14362]
I was trying to install intel math kernel lib, and used the following command:
vcpkg install intel-mkl:x64-windows

Before this command, I did vcpkg search and mkl was listed

But, this is what I got from the build:

**CMake Error at ports/intel-mkl/portfile.cmake:15 (message):
  Could not find MKL.  Before continuing, please download and install MKL
  (20200000 or higher) from:

      https://registrationcenter.intel.com/en/products/download/3178/**

Does it mean I need to register first?

**Comment by StarGate-One** [comment]
I would say yes, if Intel requires this in order for you to downloadIntel® Math Kernel Library for Windows from their website... 
It is similar to port cuda, you have to register and download/install the software from nvida and then the port is made available to other ports in vcpkg.

**Comment by JonLiu1993** [comment]
Hi @zliuchen , As @StarGate-One say,you should register first and downloadIntel® Math Kernel Library for Windows to the correct directory, The default path is：_$ENV{${ProgramFilesx86}}/IntelSWTools/compilers_and_libraries/windows_，

**Comment by JonLiu1993** [comment]
@zliuchen ,does this still be a problem for you?

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
