### ISSUE TITLE
[vcpkg/toolchain] Why not use VS_DEBUGGER_ENVIRONMENT instead of copying the DLLs for Visual Studio generators?

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#14374]
https://cmake.org/cmake/help/latest/prop_tgt/VS_DEBUGGER_ENVIRONMENT.html
Currently vcpkg automatically copies the DLLs to the build output directory with a custom command.
This seems to be the only solution for non Visual Studio Generators to run binaries while for Visual Studio generators vcpkg could set the VS_DEBUGGER_ENVIRONMENT to enable seemless debuging via VS. 
So should the vcpkg toolchain set the debugging enviromnent in VS?

**Comment by BillyONeal** [comment]
I'm not sure I would like a solution like that, since it means the resulting output directory is only usable in the VS debugger, and couldn't be run outside with things that don't know anything about `VS_DEBUGGER_ENVIRONMENT`, and those DLL copies are relatively inexpensive.

I don't feel *too* strongly about it but I imagine it would cause confusion...

**Comment by strega-nil** [comment]
Needs input from Robert.

**Comment by ras0219** [comment]
+1 for @BillyONeal's answer. When a user then wants to distribute their binary or run it anywhere outside "F5", it would be more difficult.

**Comment by BillyONeal** [comment]
Thanks for the suggestion, but given that we have multiple strong objections it doesn't look like we'll be pursuing this path forward.

**Comment by asfernandes** [comment]
I'm trying to use this expression: `set(CMAKE_VS_DEBUGGER_ENVIRONMENT "PATH=${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}$<$<CONFIG:Debug>:/debug>/bin")`

But when I run cmake (generate) for the first time, vcpkg variables are not set.

Then, if I generate again inside the previously existing directory, the values are present.

How can I have the `vcpkg_installed` path in a generator expression?
