### ISSUE TITLE
 Building package boost:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by lstrcat** [Microsoft/vcpkg#1438]
Package: boost:x86-windows
Vcpkg version: 0.0.81-df3f73d8256e549ad43efd0a84cd3691d91c9c10

![image](https://user-images.githubusercontent.com/1246297/28111334-b8426bb8-6727-11e7-8bda-e304df1628c7.png)

**Comment by KindDragon** [comment]
Please attach `build-x86-windows-rel-out.log` and  `build-x86-windows-rel-err.log` files.

**Comment by lstrcat** [comment]
this is patch-x86-windows-0-err.log
`Checking patch boost/range/has_range_iterator.hpp...
error: while searching for:
            T,?
            BOOST_DEDUCED_TYPENAME ::boost::enable_if<?
                BOOST_DEDUCED_TYPENAME mpl::eval_if<is_const<T>,?
                    has_type<range_const_iterator<?
                                BOOST_DEDUCED_TYPENAME remove_const<T>::type> >,?
                    has_type<range_mutable_iterator<T> >?
                >::type?
            >::type?
        >?

error: patch failed: boost/range/has_range_iterator.hpp:37
error: boost/range/has_range_iterator.hpp: patch does not apply
`

**Comment by NancyLi1013** [comment]
Please open a new issue if this is still a problem for you.
