### ISSUE TITLE
[vcpkg-registry] Unable to process <registry.git>

### ISSUE THREAD

**Issue by Chlorie** [microsoft/vcpkg#14381]
**Describe the bug**
vcpkg doesn't recognize git registries, directory registries work fine though.

**Environment**
- OS: Windows 10

**To Reproduce**
`vcpkg-configuration.json`:
```json
{
    "registries": [
        {
            "kind": "git",
            "repository": "https://github.com/microsoft/vcpkg",
            "path": "/ports"
        }
    ]
}
```

**Expected behavior**
When I run `vcpkg install` things should work.

**Failure logs** 
```
Errors occurred while parsing C:\UserFiles\Documents\Code\ToyProjects\vcpkg-registry-test\vcpkg-configuration.json
    $.registries[0] (a registry): unexpected field 'repository', did you mean 'path'?
    $.registries[0]: mismatched type: expected a registry
See https://github.com/Microsoft/vcpkg/tree/master/docs/specifications/registries.md for more information.
```

**Comment by JackBoosY** [comment]
cc @strega-nil

**Comment by strega-nil** [comment]
They aren't implemented yet (and won't ever be implemented as specified in the registries take 1 RFC). This feature is _not supported_ and _not recommended_ yet. Closing as "feature in progress".

**Comment by Chlorie** [comment]
> They aren't implemented yet (and won't ever be implemented as specified in the registries take 1 RFC). This feature is _not supported_ and _not recommended_ yet. Closing as "feature in progress".

OK, got it.
So when will similar featured be introduced?

**Comment by strega-nil** [comment]
@Chlorie I'm currently working on it, but it won't be stable for a while. We recommend using overlay-ports for now :)
