### ISSUE TITLE
mpg123 x64-windows-static build failure

### ISSUE THREAD

**Issue by mctynp** [microsoft/vcpkg#14398]
**Host Environment**
- OS: Windows 10 64-bit
- Compiler: MSVC 19

**To Reproduce**
```
./vcpkg --triplet x64-windows-static install mpg123
```
**Failure logs** 
Command first fails with an error about requiring yasm-tool:x86-windows:
```
 ./vcpkg --triplet x64-windows-static install mpg123
Computing installation plan...
The following packages will be built and installed:
    mpg123[core]:x64-windows-static
Detecting compiler hash for triplet x64-windows-static...
Starting package 1/1: mpg123:x64-windows-static
Building package mpg123[core]:x64-windows-static...
Could not locate cached archive: C:\Users\REDACTED\AppData\Local\vcpkg\archives\47\477acc6e4557a6a3e1d0ebdc57d846afdc2828fc.zip
-- Trying auto-select mirror...
-- Using cached H:/vcpkg/vcpkg/downloads/mpg123-1.25.8.tar.bz2
-- Skipping hash check for H:/vcpkg/vcpkg/downloads/mpg123-1.25.8.tar.bz2.
-- The default mirror is in Disaster Recovery mode, trying other mirrors...
-- Trying mirror cfhcable...
-- Using cached H:/vcpkg/vcpkg/downloads/mpg123-1.25.8.tar.bz2
-- Skipping hash check for H:/vcpkg/vcpkg/downloads/mpg123-1.25.8.tar.bz2.
-- Cleaning sources at H:/vcpkg/vcpkg/buildtrees/mpg123/src/f226317ddd-0aae5f9fd8.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source H:/vcpkg/vcpkg/downloads/mpg123-1.25.8.tar.bz2
-- Applying patch 0001-fix-crt-linking.patch
-- Applying patch 0002-fix-x86-build.patch
-- Applying patch 0003-add-arm-configs.patch
-- Applying patch 0004-add-arm64-uwp-config.patch
-- Using source at H:/vcpkg/vcpkg/buildtrees/mpg123/src/f226317ddd-0aae5f9fd8.clean
CMake Error at installed/x64-windows-static/share/yasm-tool-helper/yasm-tool-helper.cmake:16 (message):
  Cross-targetting and x64 ports requiring yasm require the x86-windows
  yasm-tool to be available.  Please install yasm-tool:x86-windows first.
Call Stack (most recent call first):
  ports/mpg123/portfile.cmake:41 (yasm_tool_helper)
  scripts/ports.cmake:135 (include)


Error: Building package mpg123:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: mpg123:x64-windows-static
  Vcpkg version: 2020.06.15-nohash
```

I then ran vcpkg install yasm-tool:x86-windows as it indicated, which appeared to work:

```
 ./vcpkg install yasm-tool:x86-windows
Computing installation plan...
The following packages will be built and installed:
    yasm-tool[core]:x86-windows
Detecting compiler hash for triplet x86-windows...
Starting package 1/1: yasm-tool:x86-windows
Building package yasm-tool[core]:x86-windows...
Could not locate cached archive: C:\Users\REDACTED\AppData\Local\vcpkg\archives\7d\7d6bbcb4c72d0a14345ce9d80241004f5ba64c07.zip
-- Downloading https://www.python.org/ftp/python/3.8.3/python-3.8.3-embed-win32.zip...
-- Downloading https://github.com/yasm/yasm/archive/009450c7ad4d425fa5a10ac4bd6efbd25248d823.tar.gz...
-- Extracting source H:/vcpkg/vcpkg/downloads/yasm-yasm-009450c7ad4d425fa5a10ac4bd6efbd25248d823.tar.gz
-- Using source at H:/vcpkg/vcpkg/buildtrees/yasm-tool/src/d25248d823-818ed1bbf4.clean
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Installing: H:/vcpkg/vcpkg/packages/yasm-tool_x86-windows/share/yasm-tool/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\REDACTED\AppData\Local\vcpkg\archives\7d\7d6bbcb4c72d0a14345ce9d80241004f5ba64c07.zip
Building package yasm-tool[core]:x86-windows... done
Installing package yasm-tool[core]:x86-windows...
Installing package yasm-tool[core]:x86-windows... done
Elapsed time for package yasm-tool:x86-windows: 24.01 s

Total elapsed time: 27.51 s
```

I re-ran the original command, which failed:
```
./vcpkg --triplet x64-windows-static install mpg123
Computing installation plan...
The following packages will be built and installed:
    mpg123[core]:x64-windows-static
Detecting compiler hash for triplet x64-windows-static...
Starting package 1/1: mpg123:x64-windows-static
Building package mpg123[core]:x64-windows-static...
Could not locate cached archive: C:\Users\REDACTED\AppData\Local\vcpkg\archives\47\477acc6e4557a6a3e1d0ebdc57d846afdc2828fc.zip
-- Trying auto-select mirror...
-- Using cached H:/vcpkg/vcpkg/downloads/mpg123-1.25.8.tar.bz2
-- Skipping hash check for H:/vcpkg/vcpkg/downloads/mpg123-1.25.8.tar.bz2.
-- The default mirror is in Disaster Recovery mode, trying other mirrors...
-- Trying mirror cfhcable...
-- Using cached H:/vcpkg/vcpkg/downloads/mpg123-1.25.8.tar.bz2
-- Skipping hash check for H:/vcpkg/vcpkg/downloads/mpg123-1.25.8.tar.bz2.
-- Cleaning sources at H:/vcpkg/vcpkg/buildtrees/mpg123/src/f226317ddd-0aae5f9fd8.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source H:/vcpkg/vcpkg/downloads/mpg123-1.25.8.tar.bz2
-- Applying patch 0001-fix-crt-linking.patch
-- Applying patch 0002-fix-x86-build.patch
-- Applying patch 0003-add-arm-configs.patch
-- Applying patch 0004-add-arm64-uwp-config.patch
-- Using source at H:/vcpkg/vcpkg/buildtrees/mpg123/src/f226317ddd-0aae5f9fd8.clean
-- Building H:/vcpkg/vcpkg/buildtrees/mpg123/src/f226317ddd-0aae5f9fd8.clean/ports/MSVC++/2015/win32/libmpg123/libmpg123.vcxproj for Release
-- Building H:/vcpkg/vcpkg/buildtrees/mpg123/src/f226317ddd-0aae5f9fd8.clean/ports/MSVC++/2015/win32/libmpg123/libmpg123.vcxproj for Debug
-- Installing
CMake Error at ports/mpg123/portfile.cmake:95 (file):
  file INSTALL cannot find
  "H:/vcpkg/vcpkg/buildtrees/mpg123/src/f226317ddd-0aae5f9fd8.clean/ports/MSVC++/2015/win32/libmpg123/x64/Debug_x86/libmpg123.pdb":
  File exists.
Call Stack (most recent call first):
  scripts/ports.cmake:135 (include)


Error: Building package mpg123:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: mpg123:x64-windows-static
  Vcpkg version: 2020.06.15-nohash

```

After the above error, there are newly built libmpg123.pdb files under buildtrees/mpg123:
```
./src/f226317ddd-0aae5f9fd8.clean/ports/MSVC++/2015/win32/libmpg123/x64/Debug_x86/libmpg123/libmpg123.pdb
./src/f226317ddd-0aae5f9fd8.clean/ports/MSVC++/2015/win32/libmpg123/x64/Release_x86/libmpg123/libmpg123.pdb
```
Both have an extra "libmpg123" subdirectory at the end which the INSTALL command error message doesn't seem to include.

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Could you please attach the file **H:/vcpkg/vcpkg/downloads/mpg123-1.25.8.tar.bz2** on this page?

**Comment by sfhacker** [comment]
It isn't clear to me what the issue is.
Just built this port from source on my old laptop (Windows 10 64-bit). It took two mins.

![image](https://user-images.githubusercontent.com/25817529/98231880-211aa980-1fb1-11eb-93c5-c6d5bbde70e1.png)

@mctynp Can you provide further details about how to reproduce your issue?

**Comment by mctynp** [comment]
Added the requested file (the .tar.bz2 archive is wrapped in a .zip file as github does not appear to allow attaching .bz2 files).

[mpg123-1.25.8.tar.bz2.zip](https://github.com/microsoft/vcpkg/files/5497807/mpg123-1.25.8.tar.bz2.zip)

**Comment by mctynp** [comment]
> 
> 
> It isn't clear to me what the issue is.
> Just built this port from source on my old laptop (Windows 10 64-bit). It took two mins.
> 
> @mctynp Can you provide further details about how to reproduce your issue?

The mpg123 libraries are a dependency of sdl2-mixer as used in a project I'm attempting to build. I stripped down the vcpkg command to the minimum needed to reproduce the issue:

```
 ./vcpkg --triplet x64-windows-static install mpg123
```

The compilation process seems to work, but the build fails during the installation process as outlined above, and the end result is that the mpg123 libraries and associated headers are not available to the project.

The 32-bit build does work (`./vcpkg --triplet x86-windows-static install mpg123`), but I need the 64-bit libraries.

Based on the errors I posted in the original comment, it seems like it may be an issue with vcpkg and not mpg123 as such. For your build of mpg123, did you use vcpkg? If so, what dependencies did it pull (or that you had to install manually, in case I missed something)? If you didn't use vcpkg, did you end up generating libraries that vcpkg can install?

The project I'm trying to build is https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/COMPILING/COMPILING-VS-VCPKG.md. Is there an issue with its instructions on using vcpkg and/or mpg123? Its command to build and install its dependencies failed on mpg123 as described in my original post. The full original command was

```
.\vcpkg --triplet x64-windows-static install sdl2 sdl2-image sdl2-mixer[dynamic-load,libflac,mpg123,libmodplug,libvorbis] sdl2-ttf gettext
```

While attempting to isolate the issue, I deleted and re-installed vcpkg several times. Does vcpkg generate state information outside of its installed subdirectory (plus archives) that has to be cleaned up?

**Comment by tobylane** [comment]
I have the same issue, on Azure Pipelines so it should be a clean and correct environment.

> -- Using source at D:/a/1/s/vcpkg/buildtrees/mpg123/src/f226317ddd-0aae5f9fd8.clean
CMake Error at installed/x64-windows/share/yasm-tool-helper/yasm-tool-helper.cmake:16 (message):
  Cross-targetting and x64 ports requiring yasm require the x86-windows
  yasm-tool to be available.  Please install yasm-tool:x86-windows first.
Call Stack (most recent call first):
  ports/mpg123/portfile.cmake:41 (yasm_tool_helper)
  scripts/ports.cmake:135 (include)
Error: Building package mpg123:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: mpg123:x64-windows
  Vcpkg version: 2020.06.15-nohash
Additionally, attach any relevant sections from the log files above.
Failed to run command :
 .\vcpkg install --triplet "x64-windows"yasm-tool:x86-windows ffmpeg freetype lua luafilesystem lpeg sdl2 
sdl2-mixer[dynamic-load,libflac,mpg123,libmodplug,libvorbis] luasocket catch2  
Exiting.

I ask for yasm-tool, it adds yasm-tool-helper as a dependency. It builds yasm-tool-helper *first* and fatally messages that yasm-tool isn't around yet.

**Comment by NancyLi1013** [comment]
Hi @mctynp 

Could you please help confirm it you can build mpg123 successfully after installing` yasm-tool:x86-windows`?

If not, please update `mpg123` to the latest version and try this again.

@tobylane 

Thanks for your further investigation and above details.

**Comment by mctynp** [comment]
Installing ```yasm-tool:x86-windows``` did not resolve the issue (I'd already had that package installed), but pulling the updates to ```mpg123``` did resolve the issue.

Thank you for the fix!
