### ISSUE TITLE
[opencv4[qt,eigen]:x64-windows] build failure

### ISSUE THREAD

**Issue by tapirnose** [microsoft/vcpkg#14390]
**Host Environment**
- OS: Windows 10
- vcpkg version: 2020.06.15-nohash
- using PowerShell as admin

**To Reproduce**
`./vcpkg install opencv4[qt,eigen]:x64-windows`

**Failure logs** 
-- Configuring x64-windows-rel
-- Configuring x64-windows-rel done
-- Configuring x64-windows-dbg
-- Configuring x64-windows-dbg done
-- Package x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:142 (message):
    Command failed: D:/code/vcpkg-2020.11-1/downloads/tools/msys2/4fbc9d9dcfa221de/usr/bin/bash.exe --noprofile --norc -c "make install"
    Working Directory: D:/code/vcpkg-2020.11-1/buildtrees/icu/x64-windows-rel
    See logs for more information:
      D:\code\vcpkg-2020.11-1\buildtrees\icu\make-install-x64-windows-rel-out.log
      D:\code\vcpkg-2020.11-1\buildtrees\icu\make-install-x64-windows-rel-err.log

Call Stack (most recent call first):
  ports/icu/portfile.cmake:143 (vcpkg_execute_build_process)
  scripts/ports.cmake:135 (include)

Error: Building package icu:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: icu:x64-windows
  Vcpkg version: 2020.06.15-nohash

**Additional context**
logs:
[make-install-x64-windows-rel-err.log](https://github.com/microsoft/vcpkg/files/5488026/make-install-x64-windows-rel-err.log)
[make-install-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/5488028/make-install-x64-windows-rel-out.log)

The error log mentions that D:/code/vcpkg-2020.11-1/packages/icu_x64-windows/lib/icudt67.dll doesn't exist, but i actually can find it in the explorer.

**Comment by JonLiu1993** [comment]
@tapirnose ，Thanks for posting this issue,This question may be related to cudnn. What is the version of cudnn you installed?

**Comment by tapirnose** [comment]
I have not yet heard of cudnn; how would I check its version or whether I have it installed at all?
It does not show up in the list of packages installed via vcpkg.

**Comment by JonLiu1993** [comment]
@tapirnose ，I successfully build，my cuda version is v11，You can try to download and install this version of cudda, and then try again：[this]( https://developer.nvidia.com/compute/machine-learning/cudnn/secure/7.6.5.32/Production/10.1_20191031/cudnn-10.1-windows10-x64-v7.6.5.32.zip)

**Comment by JonLiu1993** [comment]
@tapirnose ,Does this problem still exist?

**Comment by JonLiu1993** [comment]
Thanks for posting this issue. Please reopen this issue if it still be a problem for you.
