### ISSUE TITLE
[Catch3] Catch version 3

### ISSUE THREAD

**Issue by davidhunter22** [microsoft/vcpkg#14391]
Library name: Catch version 3
Library description: The nre version of te catch2 testing library
Source repository URL: https://github.com/catchorg/Catch2

So there is now a preview 3 version of catch https://github.com/catchorg/Catch2/releases/tag/v3.0.0-preview3.
Would be great to try this out. I did submit an issue on catch2 https://github.com/catchorg/Catch2/issues/1945 and Martin seems to be keen to avoid yet another vcpkg name as there are already
catch
catch-classic
catch2
Maybe the new version stuff can be used rather than creating a catch3. Note that catch3 is a breaking change from catch2 so simply updating the catch2 version to 3.X would probably be a bad idea.

**Comment by Link1J** [comment]
Here is my opinion on the request.
A) We should wait until version 3 comes out as a release, and not add a preview.
B) Version 3 should be an update as to match what the developer did.
C) Version 2 can become a feature so that people can still use it.

**Comment by sfhacker** [comment]
Just built this preview version on Windows 10 x64 and it seems pretty straight forward.

![image](https://user-images.githubusercontent.com/25817529/98141134-62ac4580-1f1a-11eb-9ef9-dd5f76bf996f.png)

![image](https://user-images.githubusercontent.com/25817529/98141170-6b9d1700-1f1a-11eb-84bf-1cf9d1bc4f83.png)

**Comment by davidhunter22** [comment]
Just so I understand.

So when a version 3 comes out the "catch2" package will at some point be upgraded in place to use it.
There will be a way to specify that you still want to use version 2 of the catch2 package after this happens.

If so seems good to me.

**Comment by Link1J** [comment]
Yes.
I can handle doing the update, once version 3 comes out.
