### ISSUE TITLE
[New Port Request] csfml

### ISSUE THREAD

**Issue by kdridi** [microsoft/vcpkg#14404]
Library name: CSFML

Library description: CSFML is the official binding of SFML for the C language.

Source repository URL: https://github.com/SFML/CSFML

Project homepage (if different from the source repository): https://www.sfml-dev.org/download/csfml/index.php

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
