### ISSUE TITLE
ompl:x64-windows BUILD_FAILED

### ISSUE THREAD

**Issue by ISWBenjaminKaiser** [microsoft/vcpkg#14406]
.\vcpkg.exe install ompl:x64-windows
The following packages will be built and installed:
    ompl[core]:x64-windows
Starting package 1/1: ompl:x64-windows
Building package ompl[core]:x64-windows...
-- Downloading https://bitbucket.org/ompl/ompl/downloads/ompl-1.4.2-Source.tar.gz...
-- Downloading https://bitbucket.org/ompl/ompl/downloads/ompl-1.4.2-Source.tar.gz... Failed. Status: 22;"HTTP response code said error"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:175 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  ports/ompl/portfile.cmake:14 (vcpkg_download_distfile)
  scripts/ports.cmake:94 (include)

Error: Building package ompl:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: ompl:x64-windows
  Vcpkg version: 2020.01.17-nohash

**Comment by JackBoosY** [comment]
@ISWBenjaminKaiser Thanks for reporting this issue!
Your vcpkg is outdata, please update vcpkg and try again.

Thanks.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
