### ISSUE TITLE
wxwidgets:x86-linux build failure

### ISSUE THREAD

**Issue by khill610** [microsoft/vcpkg#14409]
**Host Environment**
- OS: [Linux Ubuntu 18.04 x86_64]
- Compiler: gcc 7.5.0 (multilib)

**To Reproduce**
I've copied the x64-linux.cmake triplet file to x86-linux.cmake and changed the target architecture to x86
I've installed i386 architecture, i386 c libraries,multiarch-support, multilib gcc.g++ support and libx11-dev:i386 
`./vcpkg install wxwidgets:x86-linux`
[config-x86-linux-dbg-err.log](https://github.com/microsoft/vcpkg/files/5496075/config-x86-linux-dbg-err.log)
[config-x86-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/5496077/config-x86-linux-dbg-out.log)

**Failure logs** 
/opt/vcpkg# ./vcpkg install wxwidgets:x86-linux --debug
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Using vcpkg-root: /opt/vcpkg
[DEBUG] Using installed-root: /opt/vcpkg/installed
[DEBUG] Using buildtrees-root: /opt/vcpkg/buildtrees
[DEBUG] Using downloads-root: /opt/vcpkg/downloads
[DEBUG] Using packages-root: /opt/vcpkg/packages
[DEBUG] Using scripts-root: /opt/vcpkg/scripts
[DEBUG] Default binary cache path is: /root/.cache/vcpkg/archives
Computing installation plan...
[DEBUG] Found path: /usr/bin/cmake
[DEBUG] popen("/opt/vcpkg/downloads/tools/cmake-3.18.4-linux/cmake-3.18.4-Linux-x86_64/bin/cmake" --version 2>&1)
[DEBUG] cmd_execute_and_stream_data() returned 0 after     4147 us
[DEBUG] popen(/opt/vcpkg/downloads/tools/cmake-3.18.4-linux/cmake-3.18.4-Linux-x86_64/bin/cmake -DVCPKG_ROOT_DIR=/opt/vcpkg -DPACKAGES_DIR=/opt/vcpkg/packages -DBUILDTREES_DIR=/opt/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=/opt/vcpkg/installed -DDOWNLOADS=/opt/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P /opt/vcpkg/buildtrees/0.vcpkg_tags.cmake 2>&1)
[DEBUG] cmd_execute_and_stream_data() returned 0 after     2825 us
The following packages will be built and installed:
    wxwidgets[core]:x86-linux
Detecting compiler hash for triplet x86-linux...
[DEBUG] popen("/opt/vcpkg/downloads/tools/ninja-1.10.1-linux/ninja" --version 2>&1)
[DEBUG] cmd_execute_and_stream_data() returned 0 after     1944 us
[DEBUG] Found path: /usr/bin/git
[DEBUG] popen("/usr/bin/git" --version 2>&1)
[DEBUG] cmd_execute_and_stream_data() returned 0 after     2434 us
[DEBUG] popen(/opt/vcpkg/downloads/tools/cmake-3.18.4-linux/cmake-3.18.4-Linux-x86_64/bin/cmake -DCURRENT_PORT_DIR=/opt/vcpkg/scripts/detect_compiler -DCURRENT_BUILDTREES_DIR=/opt/vcpkg/buildtrees/detect_compiler -DCURRENT_PACKAGES_DIR=/opt/vcpkg/packages/detect_compiler_x86-linux -DCMD=BUILD -DTARGET_TRIPLET=x86-linux -DTARGET_TRIPLET_FILE=/opt/vcpkg/triplets/x86-linux.cmake -DVCPKG_PLATFORM_TOOLSET=external -DDOWNLOADS=/opt/vcpkg/downloads -DVCPKG_CONCURRENCY=3 -DGIT=/usr/bin/git -DVCPKG_ROOT_DIR=/opt/vcpkg -DPACKAGES_DIR=/opt/vcpkg/packages -DBUILDTREES_DIR=/opt/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=/opt/vcpkg/installed -DDOWNLOADS=/opt/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P /opt/vcpkg/scripts/ports.cmake 2>&1)
[DEBUG] -- Configuring x86-linux-rel
[DEBUG] -- The C compiler identification is GNU 7.5.0
[DEBUG] -- Detecting C compiler ABI info
[DEBUG] -- Detecting C compiler ABI info - done
[DEBUG] -- Check for working C compiler: /usr/bin/cc - skipped
[DEBUG] -- Detecting C compile features
[DEBUG] -- Detecting C compile features - done
[DEBUG] -- The CXX compiler identification is GNU 7.5.0
[DEBUG] -- Detecting CXX compiler ABI info
[DEBUG] -- Detecting CXX compiler ABI info - done
[DEBUG] -- Check for working CXX compiler: /usr/bin/c++ - skipped
[DEBUG] -- Detecting CXX compile features
[DEBUG] -- Detecting CXX compile features - done
[DEBUG] -- Configuring done
[DEBUG] -- Generating done
[DEBUG] -- Build files have been written to: /opt/vcpkg/buildtrees/detect_compiler/x86-linux-rel
[DEBUG] 
[DEBUG] #COMPILER_HASH#29253be9e3a320c879bf6a0158037a819b774445
[DEBUG] #COMPILER_C_HASH#5abcc06b1fcb280814b980b2a2881e304454788d
[DEBUG] #COMPILER_C_VERSION#7.5.0
[DEBUG] #COMPILER_C_ID#GNU
[DEBUG] #COMPILER_CXX_HASH#27630a02966dfd7059019855ec6560acc4d8eb28
[DEBUG] #COMPILER_CXX_VERSION#7.5.0
[DEBUG] #COMPILER_CXX_ID#GNU
[DEBUG] CMake Warning:
[DEBUG]   Manually-specified variables were not used by the project:
[DEBUG] 
[DEBUG]     BUILD_SHARED_LIBS
[DEBUG]     CMAKE_INSTALL_BINDIR
[DEBUG]     CMAKE_INSTALL_LIBDIR
[DEBUG]     VCPKG_PLATFORM_TOOLSET
[DEBUG]     VCPKG_SET_CHARSET_FLAG
[DEBUG] 
[DEBUG] 
[DEBUG] 
[DEBUG] cmd_execute_and_stream_data() returned 0 after   340507 us
[DEBUG] 
[DEBUG] Detecting compiler hash for triplet x86-linux: 29253be9e3a320c879bf6a0158037a819b774445
[DEBUG] <abientries for wxwidgets:x86-linux>
[DEBUG]   CONTROL|2911b985e2b70e7d517f8fc54f75181537547fd0
[DEBUG]   cmake|3.18.4
[DEBUG]   disable-platform-lib-dir.patch|18ac3e2ac3b573e657f99bc2317d1c6634a507c1
[DEBUG]   expat|7db4330c0dc5cae8b11e10c338a1a81298fb9fcb
[DEBUG]   features|core
[DEBUG]   fix-stl-build-vs2019-16.6.patch|8b395f5e96c7f9fce73eeb82dbe3dcda44bd1d67
[DEBUG]   libpng|6bdb383bf52f50f699fbbbe3964a45d3fda8f67b
[DEBUG]   portfile.cmake|23476c534378b299ba73e5c4d1377abd0c537adb
[DEBUG]   post_build_checks|2
[DEBUG]   tiff|d38b2bd6296997e2d923a570915afbf8dadb06a3
[DEBUG]   triplet|f765e8009f05820c06cfb37c1710def22094f87a-497032558309d954763445f6b33535bb41c0820b-29253be9e3a320c879bf6a0158037a819b774445
[DEBUG]   vcpkg_configure_cmake|ae0a97eff7f218b68bc4ab1b4bd661107893803e
[DEBUG]   vcpkg_copy_pdbs|dbca2886a2490c948893c8250a2b40a3006cf7a9
[DEBUG]   vcpkg_copy_tools|8a6d670de3e91f9fad1dd4e4d644fc57c35ddf6f
[DEBUG]   vcpkg_fail_port_install|2fda28cbb5b3e1d8d48a231fe59b318c47704665
[DEBUG]   vcpkg_from_git|f29cbe08f369138581e36c864f9d08465c840e23
[DEBUG]   vcpkg_from_github|1e4d57547e633121a17c0b047a065101aa054671
[DEBUG]   vcpkg_install_cmake|75d1079d6f563d87d08c8c5f63b359377aa19a6e
[DEBUG]   zlib|63d205abc073cff20822f5d6bdc1825026424391
[DEBUG] </abientries>
Starting package 1/1: wxwidgets:x86-linux
Building package wxwidgets[core]:x86-linux...
Could not locate cached archive: /root/.cache/vcpkg/archives/0d/0de45f0541b0e63e74abba7d83829d345c7ad95d.zip
[DEBUG] popen(/opt/vcpkg/downloads/tools/cmake-3.18.4-linux/cmake-3.18.4-Linux-x86_64/bin/cmake -DPORT=wxwidgets -DCURRENT_PORT_DIR=/opt/vcpkg/ports/wxwidgets -DVCPKG_USE_HEAD_VERSION=0 -D_VCPKG_NO_DOWNLOADS=0 -D_VCPKG_DOWNLOAD_TOOL=BUILT_IN -D_VCPKG_EDITABLE=0 -DFEATURES=core -DALL_FEATURES= -DCMD=BUILD -DTARGET_TRIPLET=x86-linux -DTARGET_TRIPLET_FILE=/opt/vcpkg/triplets/x86-linux.cmake -DVCPKG_PLATFORM_TOOLSET=external -DDOWNLOADS=/opt/vcpkg/downloads -DVCPKG_CONCURRENCY=3 -DGIT=/usr/bin/git -DVCPKG_ROOT_DIR=/opt/vcpkg -DPACKAGES_DIR=/opt/vcpkg/packages -DBUILDTREES_DIR=/opt/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=/opt/vcpkg/installed -DDOWNLOADS=/opt/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P /opt/vcpkg/scripts/ports.cmake 2>&1)
-- Using cached /opt/vcpkg/downloads/wxWidgets-wxWidgets-v3.1.4.tar.gz
-- Cleaning sources at /opt/vcpkg/buildtrees/wxwidgets/src/v3.1.4-b747a62900.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /opt/vcpkg/downloads/wxWidgets-wxWidgets-v3.1.4.tar.gz
-- Applying patch disable-platform-lib-dir.patch
-- Applying patch fix-stl-build-vs2019-16.6.patch
-- Using source at /opt/vcpkg/buildtrees/wxwidgets/src/v3.1.4-b747a62900.clean
-- Configuring x86-linux-dbg
-- Configuring x86-linux-rel
-- Building x86-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:142 (message):
    Command failed: /opt/vcpkg/downloads/tools/cmake-3.18.4-linux/cmake-3.18.4-Linux-x86_64/bin/cmake --build . --config Debug --target install -- -v -j3
    Working Directory: /opt/vcpkg/buildtrees/wxwidgets/x86-linux-dbg
    See logs for more information:
      /opt/vcpkg/buildtrees/wxwidgets/install-x86-linux-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:93 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/wxwidgets/portfile.cmake:41 (vcpkg_install_cmake)
  scripts/ports.cmake:135 (include)

[DEBUG] cmd_execute_and_stream_data() returned 256 after 84587574 us
Error: Building package wxwidgets:x86-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: wxwidgets:x86-linux
  Vcpkg version: 2020.06.15-unknownhash

Additionally, attach any relevant sections from the log files above.
[DEBUG] ../src/vcpkg/install.cpp(493)
[DEBUG] Exiting after 84948800 us (84945735 us)

-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by JonLiu1993** [comment]
@khill610 ,Thanks for posting this issue, Could you please provide the error log
````
See logs for more information:
/opt/vcpkg/buildtrees/wxwidgets/install-x86-linux-dbg-out.log
````

**Comment by JackBoosY** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
