### ISSUE TITLE
Error: Building package aws-sdk-cpp:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by GerardDR** [microsoft/vcpkg#14403]
Package: aws-sdk-cpp:x86-windows
 Vcpkg version: 2020.06.15-nohash

Windows 10, with extended file path support turned on.
Cmd: vcpkg install aws-sdk-cpp[*]:x86-windows --recurse

Following instructions at:
https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/setup.html

**Comment by PhoebeHui** [comment]
@GerardDR, could you attach the failure logs?

**Comment by GerardDR** [comment]
[
[x86-windows.vcpkg_abi_info.txt](https://github.com/microsoft/vcpkg/files/5507340/x86-windows.vcpkg_abi_info.txt)
[install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/5507341/install-x86-windows-dbg-out.log)
[stdout-x86-windows.log](https://github.com/microsoft/vcpkg/files/5507342/stdout-x86-windows.log)


](url)

**Comment by PhoebeHui** [comment]
@GerardDR, thanks for your updates!

This is a known Upstream issue https://github.com/aws/aws-sdk-cpp/issues/1418, I will confrim if it fix in latest release,
