### ISSUE TITLE
Manifest mode + cmake fails to install packages

### ISSUE THREAD

**Issue by omcnoe** [microsoft/vcpkg#14418]
**Describe the bug**
Running in manifest mode (`VCPKG_FEATURE_FLAGS="manifests"`), I pass the vcpkg toolchain file `vcpkg/scripts/buildsystems/vcpkg.cmake` to cmake. I see
```
...
-- Running vcpkg install
-- Running vcpkg install - done
...
```
in the configure log. BUT, no `vcpkg_installed` dir is created and my build fails.
If I then manually run `./vcpkg/vcpkg install` the `vcpkg_installed` dir is correctly created.

**Environment**
- OS: macOS
- Compiler: Apple clang version 12.0.0 (clang-1200.0.32.21)

**To Reproduce**
1. create vcpkg.json listing a dependency
2. run cmake, point it at the vcpkg toolchain

**Expected behavior**
Expected: vcpkg_installed directory, and a working build.

**Comment by TerensTare** [comment]
I think you should have pre-installed the packages with vcpkg before running cmake.
Eg. say you need `{fmt}`, you should have first installed `{fmt}` by calling `vcpkg install fmt` from anywhere (but not where `vcpkg.json` is located), then run cmake as usual.

**Comment by omcnoe** [comment]
I was able to do this to make my build work.

But the cmake configure output claims to run vcpkg install itself... but no vcpkg_installed dir is created.

**Comment by TerensTare** [comment]
On my pc, `vcpkg_installed` is created inside `build` directory. DId you check there?

**Comment by omcnoe** [comment]
Ahh that's the issue...

**Comment by NancyLi1013** [comment]
Hi @strega-nil 

Could you please help take a look?

**Comment by strega-nil** [comment]
I believe it's been figured out, since the `vcpkg_installed` directory is in the `build` directory?

**Comment by omcnoe** [comment]
It would be nice if the vcpkg CMake toolchain file that runs `vcpkg install` could place the `vcpkg_installed` directory in the project source directory (which is where the same toolchain file configures CMake to expect to find `vcpkg_installed` when calling `find_package`), rather than the CMake build directory.

Currently it means you can't use the automatic install functionality unless you are doing an in-tree build. In tree builds seem to be frowned upon, the CMake integration in Visual Studio and Visual Studio Code doesn't do an in-tree build.

**Comment by strega-nil** [comment]
@omcnoe That shouldn't be how it works. We should be using the same variable, `${_VCPKG_INSTALLED_DIR}`, for both things...

**Comment by omcnoe** [comment]
Well, that is the experience that I had using vcpkg in manifest mode with vscode.

**Comment by PhoebeHui** [comment]
@omcnoe, does this still be a question for you?

**Comment by NancyLi1013** [comment]
Please feel free to reopen this issue if it is still a problem for you.
