### ISSUE TITLE
Vcpkg integrating to Visual Studio conflict with Intel Performance Library

### ISSUE THREAD

**Issue by mrchipset** [microsoft/vcpkg#14419]
**Describe the bug**
I have already installed the Intel Performance library integration to Visual Studio 2019. When I have integrate vcpkg to VS2019. The Intel Performance Library Options in the project property has disappeared. And I have to remove vcpkg and re-install Intel performance library.

**Environment**
- OS: Windows
- Compiler: Visual Studio 2019 Community

**To Reproduce**
1. ./vcpkg intergrate
2. Then The intel performance library in VS project property has disappeared.

**Comment by JackBoosY** [comment]
@mrchipset Sorry for late, can you provide us a reproduce step?

Thanks.

**Comment by mrchipset** [comment]
1. First, when the intel MKL is installed, it will install an integration tool to visual studio. Then we can configure the C++ project with MKL support conveniently.
2. But when I follow the official vcpkg install document. And integrated the vcpkg to visual studio 2019. The MKL support tab has been disappeared from project property window.
3. I have tried re-install the Intel Math Kernel library, But it was not taken effect.
4. Then, I have to uninstall the vcpkg integration from VS2019 and reinstall the Intel Math Kernel library. Then the MKL integration tool can work well with VS2019.

But now, Intel MKL is released as oneMKL. I haven't try it yet.

If you need more information, please let me know.

**Comment by JackBoosY** [comment]
@ras0219 @ras0219-msft Can you please take a look?

Thanks.

**Comment by BillyONeal** [comment]
>First, when the intel MKL is installed, it will install an integration tool to visual studio. Then we can configure the C++ project with MKL support conveniently.

Can you explain what "intel MKL installed" entails? Like where can we download this thing, do you have a hello world project that uses it, etc.? The folks who maintain vcpkg do not use Intel MKL so we are unfamiliar with how to do this step.

**Comment by mrchipset** [comment]
> > First, when the intel MKL is installed, it will install an integration tool to visual studio. Then we can configure the C++ project with MKL support conveniently.
> 
> Can you explain what "intel MKL installed" entails? Like where can we download this thing, do you have a hello world project that uses it, etc.? The folks who maintain vcpkg do not use Intel MKL so we are unfamiliar with how to do this step.

Sorry for my carelessness.
You can download Intel MKL from Intel development zone. It is an vectorize math computation library. Now it is named as oneMKL. You can download the binary package from this [link](https://software.intel.com/content/www/us/en/develop/tools/oneapi/components/onemkl.html).

It was installed on my computer with default options. During the install procedure, an VS2019 integration tool will be installed. Then we can config the MKL library easily in project property window.
But when vcpkg is installed, the Intel Library configuration tab in the property window will disappear.

![image](https://user-images.githubusercontent.com/36813506/104289069-a19ae080-54f3-11eb-803b-a77993a28db7.png)

**Comment by BillyONeal** [comment]
I've gotten reassigned to some other stuff, sorry I haven't had time to look into this :/. /cc @ras0219  @ras0219-msft

**Comment by Cheney-W** [comment]
Verified this issue with following enverionment, it has been fixed:
```
Visual Studio: VS2019 16.11.4
vcpkg: 2022-05-05-67e17c1782801cf481be9ac0b3765dff3e4bdeb8
oneAPI Base Toolkit: 
```
![image](https://user-images.githubusercontent.com/38240633/173001439-615e7928-5f7d-4cf6-974d-8645638f45bb.png)


After run ./vcpkg integrate install command, reopen the VS project and opened the property of project, I could see the `vcpkg` and the `Intel Library configuration` are present at the same time.
![image](https://user-images.githubusercontent.com/38240633/173002032-02c406ea-5972-45c9-8f0f-129d8cfa725d.png)
