### ISSUE TITLE
libxslt port is not exporting tools

### ISSUE THREAD

**Issue by japj** [microsoft/vcpkg#14425]
**Describe the bug**
libxslt port is doing a lot of work to build/copy (xsltproc) tools to the tools folder,
however in the end (during clean) it actually removes the tools folder

See:
https://github.com/microsoft/vcpkg/blob/0ff75ac80b9a3770afb3d2971c572628d80a631e/ports/libxslt/portfile.cmake#L113

and:
https://github.com/microsoft/vcpkg/blob/0ff75ac80b9a3770afb3d2971c572628d80a631e/ports/libxslt/portfile.cmake#L146

**Environment**
- OS: [Windows]

**To Reproduce**
1. ./vcpkg install libxslt
Result: xsltproc.exe not available

**Expected behavior**
I expected xsltproc.exe to be present in the tools folder

**Comment by JackBoosY** [comment]
Confirmed, thanks for reporting this issue!
