### ISSUE TITLE
[glib:x64-linux] build failure

### ISSUE THREAD

**Issue by MateCheck-rar** [microsoft/vcpkg#14428]
**Host Environment**
- OS: Ubuntu 20.10

**To Reproduce**
`./vcpkg install glib`

**Failure logs** 
```
Computing installation plan...
The following packages will be built and installed:
    glib[core]:x64-linux
Detecting compiler hash for triplet x64-linux...
Starting package 1/1: glib:x64-linux
Building package glib[core]:x64-linux...
Could not locate cached archive: /home/matteo/.cache/vcpkg/archives/2e/2e96e0e7a11a569d3f082ea6a85e370cc1cc899d.zip
-- Using cached /home/matteo/vcpkg/downloads/glib-2.52.3.tar.xz
-- Cleaning sources at /home/matteo/vcpkg/buildtrees/glib/src/2.52.3-34a15219ec.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/matteo/vcpkg/downloads/glib-2.52.3.tar.xz
-- Applying patch use-libiconv-on-windows.patch
-- Applying patch arm64-defines.patch
-- Applying patch fix-arm-builds.patch
-- Using source at /home/matteo/vcpkg/buildtrees/glib/src/2.52.3-34a15219ec.clean
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:142 (message):
    Command failed: /home/matteo/vcpkg/downloads/tools/cmake-3.18.4-linux/cmake-3.18.4-Linux-x86_64/bin/cmake --build . --config Debug --target install -- -v -j9
    Working Directory: /home/matteo/vcpkg/buildtrees/glib/x64-linux-dbg
    See logs for more information:
      /home/matteo/vcpkg/buildtrees/glib/install-x64-linux-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:93 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/glib/portfile.cmake:49 (vcpkg_install_cmake)
  scripts/ports.cmake:135 (include)


Error: Building package glib:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: glib:x64-linux
  Vcpkg version: 2020.06.15-unknownhash

Additionally, attach any relevant sections from the log files above.
-Please attach any additional failure logs mentioned in the console output.

```
**Mentioned log file**
[install-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/5501288/install-x64-linux-dbg-out.log)

**Additional context**
I was trying to directly install gtkmm, then I received this error regarding glib and recreated it. I've found #7978 but following all the steps suggested there, checking that my vcpkg version is already the most recent (I installed it today) didn't make a change. Can't figure it out alone.

**Comment by JackBoosY** [comment]
```
/home/matteo/vcpkg/buildtrees/glib/src/2.52.3-34a15219ec.clean/glib/gconvert.c:60:2: error: #error GNU libiconv not in use but included iconv.h is from libiconv
```

**Comment by MateCheck-rar** [comment]
Sure.
[config-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/5509012/config-x64-linux-dbg-out.log)

[config-x64-linux-dbg-err.log](https://github.com/microsoft/vcpkg/files/5509027/config-x64-linux-dbg-err.log)

**Comment by JackBoosY** [comment]
The macro `_LIBICONV_H` shouldn't be defined, did you install libiconv using other package manager(such as apt/yum)?

**Comment by MateCheck-rar** [comment]
Just looked for it and yes, it's been installed using Anaconda. Thank you.

**Comment by JackBoosY** [comment]
@MateCheck-rar Please remove libicon using Anaconda and try again.

**Comment by JackBoosY** [comment]
`_LIBICONV_H` should be brought by the configuration files of other libraries in the system.

**Comment by MateCheck-rar** [comment]
Ok, I tried to remove libiconv using Anaconda, it didn't work due to a ton of conflicts. The report took an hour and a half to be performed and the list didn't fit my entire terminal buffer. Completely removing Anaconda (I do not need it anymore) defenitely solved the issue. Thank you for the help, I'll be more careful managing my environments.
