### ISSUE TITLE
qt5-declarative:x86-windows-static BUILD_FAILED

### ISSUE THREAD

**Issue by 96chh** [microsoft/vcpkg#14429]
@JackBoosY 
Error: Building package qt5-declarative:x86-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: qt5-declarative:x86-windows-static
  Vcpkg version: 2020.06.15-nohash

_Originally posted by @96chh in https://github.com/microsoft/vcpkg/issues/4560#issuecomment-722931044_

**Comment by JackBoosY** [comment]
Please provide the failure logs. 

Thanks.

**Comment by 96chh** [comment]
I tried again and succeeded.
