### ISSUE TITLE
[libjpeg-turbo] Please enable jpeg7 and jpeg8 APIs

### ISSUE THREAD

**Issue by Ziriax** [microsoft/vcpkg#14438]
****

**Is your feature request related to a problem? Please describe.**

Currently the `libjpeg-turbo` package is build without enabling the `jpeg7` and `jpeg8` API features.

**Proposed solution**

Enable these features.

**Describe alternatives you've considered**

I couldn't find the [regular libjpeg package](http://libjpeg.sourceforge.net) in vcpkg, the that one that has these features (_but has bad performance compared to libjpeg-turbo_)

**Additional context**

[I have pushed my code for enabling these in this fork](https://github.com/Ziriax/vcpkg/tree/libjpeg-turbo-jpeg8). I can make a PR if you prefer

**Comment by NancyLi1013** [comment]
Hi @Ziriax 

Thanks for posting this issue.

If you are interested in this issue, you can make a PR to implement these features. We're happy that you would like to do this work.
