### ISSUE TITLE
[restinio] build failure

### ISSUE THREAD

**Issue by kem0o** [microsoft/vcpkg#14434]
- OS: [e.g. Windows/Linux etc...]
- Compiler: VS2019

`./vcpkg install restinio`

**Failure logs** 
![image](https://user-images.githubusercontent.com/19430119/98397368-f0497b80-2067-11eb-8fcd-1c24acf3ddcf.png)

[config-x86-windows-out.log](https://github.com/microsoft/vcpkg/files/5502678/config-x86-windows-out.log)

i see it's something wrong with my compiler but i can't really get what's wrong 😞

**Comment by PhoebeHui** [comment]
@kem0o, do you install windows sdk? if so, could you reinstall windows sdk by vs installer? see issue https://github.com/microsoft/vcpkg/issues/6324

Failures:

 LINK : fatal error LNK1104: cannot open file 'ucrtd.lib'

**Comment by PhoebeHui** [comment]
@kem0o, please reopen this issue if it still be a problem for you.
