### ISSUE TITLE
Add support for being able to exclude certain package from ffmpeg (or maybe generic)

### ISSUE THREAD

**Issue by tapika** [microsoft/vcpkg#14445]
At the moment 

`ports\ffmpeg\CONTROL`

Lists following features:
`Default-Features: avresample, avcodec, avformat, avdevice, avfilter, postproc, swresample, swscale`

which in a turn drag a dependency on gpl licensed software => `postproc` => `gpl`.

Not every software wants to have a dependency on gpl - in fact I think most of software developers don't want it.

I would recommend to make it optional by removing `gpl and/or postproc` from there or add support into vckg to be able to
exclude certain feature from command line using command line arguments.

**Comment by tapika** [comment]
Btw, added instructions on vcpkg to official ffmpeg compilation how to's:
https://trac.ffmpeg.org/wiki/CompilationGuide/vcpkg

Otherwise it's rather difficult to figure out what needs to be done.

**Comment by vicroms** [comment]
To install a package without default features do: `vcpkg install ffmpeg[core]`. You can also add the features you want on top of the core library, e.g.: `vcpkg install ffmpeg[core,swresample,swscale]`.

**Comment by tapika** [comment]
Is this "core" applicable to all packages ? Or only ffmpeg ?

**Comment by vicroms** [comment]
Hi @tapika it works with all packages.

https://github.com/microsoft/vcpkg/blob/master/docs/users/selecting-library-features.md

**Comment by tapika** [comment]
Ah, ok - not most obvious option. Could be maybe documented better - for example from usage (vcpkg install /?), or made also differently: If you specify libraries, it would automatically override default libraries, not append new ones.

What I've briefly tested - works as expected.

Usability issue, you can close this ticket if you want.

**Comment by vicroms** [comment]
@tapika Thanks for writing the instructions on the ffmpeg wiki!
