### ISSUE TITLE
[poco:x86-windows] build failure

### ISSUE THREAD

**Issue by sersus** [microsoft/vcpkg#14449]
**Host Environment**
- OS: Windows 10 1809 build 17763.1554
- Compiler: build tools 2019

**To Reproduce**
`./vcpkg install poco`

**Failure logs** 
```
Computing installation plan...
The following packages will be built and installed:
    poco[core]:x86-windows
Detecting compiler hash for triplet x86-windows...
Starting package 1/1: poco:x86-windows
Building package poco[core]:x86-windows...
Could not locate cached archive: C:\Users\soosha\AppData\Local\vcpkg\archives\68\68a0ac815c5a2c1e837dd681028659c88cb2e912.zip
-- Downloading https://github.com/pocoproject/poco/archive/3fc3e5f5b8462f7666952b43381383a79b8b5d92.tar.gz...
-- Cleaning sources at C:/git/vcpkg/buildtrees/poco/src/a79b8b5d92-31a2ca8a23.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/git/vcpkg/downloads/pocoproject-poco-3fc3e5f5b8462f7666952b43381383a79b8b5d92.tar.gz
-- Applying patch include_pcre.patch
-- Applying patch static_pcre.patch
-- Applying patch use-vcpkg-libharu.patch
-- Applying patch arm64_pcre.patch
-- Applying patch fix_dependency.patch
-- Using source at C:/git/vcpkg/buildtrees/poco/src/a79b8b5d92-31a2ca8a23.clean
-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:142 (message):
    Command failed: C:/git/vcpkg/downloads/tools/cmake-3.18.4-windows/cmake-3.18.4-win32-x86/bin/cmake.exe --build . --config Debug --target install -- /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /m
    Working Directory: C:/git/vcpkg/buildtrees/poco/x86-windows-dbg
    See logs for more information:
      C:\git\vcpkg\buildtrees\poco\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:93 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/poco/portfile.cmake:85 (vcpkg_install_cmake)
  scripts/ports.cmake:135 (include)

```
**Additional context**
I tried to clean the buildtree directiory, it doesn't work.
[install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/5504929/install-x86-windows-dbg-out.log)

**Comment by linquize** [comment]
This is because `<WindowsTargetPlatformVersion>8.1</WindowsTargetPlatformVersion>` is generated in `DataODBC.vcxproj`.
Removing that property will work.

**Comment by linquize** [comment]
If you build poco source code with `cmake` directly without `vcpkg`, `ODBC` error also occur because Win 8.1 SDK is chosen in the generated vcxproj file.

**Comment by PhoebeHui** [comment]
It looks mixed up the window sdk revision 10.0.17763.0 and 10.0.18362.0, I noticed both are in build logs, could you reinstall the windows sdk, and try again? I can't repro this issue locally.

**Comment by sersus** [comment]
> It looks mixed up the window sdk revision 10.0.17763.0 and 10.0.18362.0, I noticed both are in build logs, could you reinstall the windows sdk, and try again? I can't repro this issue locally.

Thank you, that was the reason for the failure. I reinstalled the SDK and everything is fine now.

**Comment by linquize** [comment]
reinstalled the SDK 10.0.18362.0 does not solve the problem.
Currently, this port uses MSBuild as generator.
If use Ninja instead of MSBuild, it can build successfully.
