### ISSUE TITLE
libxml2 vcpkg-cmake-wrapper.cmake bugs

### ISSUE THREAD

**Issue by jmelas** [microsoft/vcpkg#14468]
**Describe the bug**
In file vcpkg-cmake-wrapper.cmake of package LibXml2, the target LibXml2::LibXml2 is not linked against all necessary libraries

**Environment**
- OS: Windows

**To Reproduce**
1. ./vcpkg install libxml2
2. find_package(LibXml2)
target_link_libraries(main PRIVATE LibXml2::LibXml2)
3. ZLIB_LIBRARIES and LIBLZMA_LIBRARIES are not linked, neither ws2_32 on windows

**Expected behavior**
LibXml2::LibXml2 target should link with Iconv, Charset, lzma, zlib, ws2_32 (windows only) libraries

**Comment by JackBoosY** [comment]
After the official [discussion](https://gitlab.gnome.org/GNOME/libxml2/-/issues/207) with libxml2, I think this is by design and libxml2 does not need to be linked to these dependencies.
And it actually passed the test.
