### ISSUE TITLE
Error: Building package libpq:x86-windows-static failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by ducdY** [microsoft/vcpkg#14461]
Package: libpq:x86-windows-static
  Vcpkg version: 2020.06.15-nohash

build-libpq-x86-windows-static-RELEASE-out.log

 .\Release\libpq\encnames.obj : fatal error LNK1112: module machine type 'x86' conflicts with target machine type 'x64' [D:\vcpkg\buildtrees\libpq\x86-windows-static-rel\libpq.vcxproj]

**Comment by linquize** [comment]
Could you pull latest vcpkg, delete all packages and try again?

**Comment by ducdY** [comment]
It's still the same

.\vcpkg\vcpkg.exe --triplet x86-windows-static  install qt5-base

**Comment by PhoebeHui** [comment]
Closing in favor of https://github.com/microsoft/vcpkg/issues/13726
