### ISSUE TITLE
Why vcpkg won't install a powershell when there is a _VCPKG_PWSH_PATH-NOTFOUND

### ISSUE THREAD

**Issue by TheVeryDarkness** [microsoft/vcpkg#14472]
These days I met _VCPKG_PWSH_PATH-NOTFOUND, which may be caused by my accidental uninstallation of powershell 7.0.3.
I've tried "vcpkg integrate powershell", updated some ports and libraries and installed another powershell 7.0.3, but the problem is still there when building a project with CMake, as vcpkg doesn't installed another powershell.
It says "  '_VCPKG_PWSH_PATH-NOTFOUND' is not recognized as an internal or external command, operable program or batch file."

**Comment by JackBoosY** [comment]
@BillyONeal Did your PR break this scene?

**Comment by BillyONeal** [comment]
There were a couple of commits wherein this was broken but I believe they were fixed a few days later. @TheVeryDarkness Can you post repo steps?

**Comment by TheVeryDarkness** [comment]
Okay. But I forget what I've done to vcpkg and Powershell, so I may need to reinstall a vcpkg, and it takes a little time

**Comment by BillyONeal** [comment]
@TheVeryDarkness I touched this most recently so I'm sorry if I caused you pain :(. But I've not seen the problem since https://github.com/microsoft/vcpkg/commit/b7056e9f1f34f18b6648b1f1d9c4e9d31f04e91c -- that doesn't mean that all the occurrences are gone, but it does mean that it doesn't happen in the most obvious cases.

**Comment by TheVeryDarkness** [comment]
> @TheVeryDarkness I touched this most recently so I'm sorry if I caused you pain :(. But I've not seen the problem since [b7056e9](https://github.com/microsoft/vcpkg/commit/b7056e9f1f34f18b6648b1f1d9c4e9d31f04e91c) -- that doesn't mean that all the occurrences are gone, but it does mean that it doesn't happen in the most obvious cases.

This time I run into something a bit strange..
I copy "D://vcpkg/downloads" into "D://downloads" to avoid long-time download then, and remove the folder "D://vcpkg" directly.
Then I tap some command from the root directory "D:/".
git clone https://github.com/microsoft/vcpkg.git
cd vcpkg
bootstrap-vcpkg
vcpkg install ... // Some small ports to test, and vcpkg doesn't download any dependencies.
vcpkg integrate install

Then I reopened visual studio, as I found integration may not be completed when vs in on.
And _VCPKG_PWSH_PATH-NOTFOUND is still there.

Actually, I've tried to install vcpkg when the original one is there, but I found bootstrap-vcpkg build the vcpkg.exe in the folder of the original vcpkg.
Maybe there is some settings remained though I removed the vcpkg folder?

**Comment by BillyONeal** [comment]
>Then I reopened visual studio, as I found integration may not be completed when vs in on.
And _VCPKG_PWSH_PATH-NOTFOUND is still there.

I see, your configured project in VS might still be broken from my mistake I fixed in that SHA. Can you ask VS to clear the CMake cache for the project you're building?

![image](https://user-images.githubusercontent.com/1544943/98645842-60196980-22e7-11eb-95df-ff0f7296dc1a.png)

**Comment by TheVeryDarkness** [comment]
> > Then I reopened visual studio, as I found integration may not be completed when vs in on.
> > And _VCPKG_PWSH_PATH-NOTFOUND is still there.
> 
> I see, your configured project in VS might still be broken from my mistake I fixed in that SHA. Can you ask VS to clear the CMake cache for the project you're building?
> 
> ![image](https://user-images.githubusercontent.com/1544943/98645842-60196980-22e7-11eb-95df-ff0f7296dc1a.png)

Ah, it takes effect! Thank you a lot!
I should have tried delete the cache, sorry.

**Comment by JackBoosY** [comment]
Thanks @BillyONeal !
