### ISSUE TITLE
bug when searching wampcc

### ISSUE THREAD

**Issue by kamilz98** [microsoft/vcpkg#14471]
I just upgrade vcpkg today and when I type 'vcpkg search wampcc' I got a bunch of warnings so tried 'vcpkg search wampcc -debug' and this is the result:

[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Using vcpkg-root: F:\Library\vcpkg
[DEBUG] Using installed-root: F:\Library\vcpkg\installed
[DEBUG] Using buildtrees-root: F:\Library\vcpkg\buildtrees
[DEBUG] Using downloads-root: F:\Library\vcpkg\downloads
[DEBUG] Using packages-root: F:\Library\vcpkg\packages
[DEBUG] Using scripts-root: F:\Library\vcpkg\scripts
Error: There are invalid field types in the CONTROL or manifest file of F:\Library\vcpkg\ports\abseil\vcpkg.json
The following fields had the wrong types:

    features was expected to be an array of feature definitions

Error: There are invalid field types in the CONTROL or manifest file of F:\Library\vcpkg\ports\asio\vcpkg.json
The following fields had the wrong types:

    features was expected to be an array of feature definitions

Error: There are invalid field types in the CONTROL or manifest file of F:\Library\vcpkg\ports\blend2d\vcpkg.json
The following fields had the wrong types:

    features was expected to be an array of feature definitions

Error: There are invalid field types in the CONTROL or manifest file of F:\Library\vcpkg\ports\colmap\vcpkg.json
The following fields had the wrong types:

    features was expected to be an array of feature definitions

Error: There are invalid field types in the CONTROL or manifest file of F:\Library\vcpkg\ports\cpu-features\vcpkg.json
The following fields had the wrong types:

    features was expected to be an array of feature definitions

Error: There are invalid field types in the CONTROL or manifest file of F:\Library\vcpkg\ports\faiss\vcpkg.json
The following fields had the wrong types:

    features was expected to be an array of feature definitions

Error: There are invalid field types in the CONTROL or manifest file of F:\Library\vcpkg\ports\freetds\vcpkg.json
The following fields had the wrong types:

    features was expected to be an array of feature definitions

Error: There are invalid field types in the CONTROL or manifest file of F:\Library\vcpkg\ports\geographiclib\vcpkg.json
The following fields had the wrong types:

    features was expected to be an array of feature definitions

Error: There are invalid field types in the CONTROL or manifest file of F:\Library\vcpkg\ports\infoware\vcpkg.json
The following fields had the wrong types:

    features was expected to be an array of feature definitions

Error: There are invalid field types in the CONTROL or manifest file of F:\Library\vcpkg\ports\itk\vcpkg.json
The following fields had the wrong types:

    features was expected to be an array of feature definitions

Error: There are invalid field types in the CONTROL or manifest file of F:\Library\vcpkg\ports\kenlm\vcpkg.json
The following fields had the wrong types:

    features was expected to be an array of feature definitions

Error: There are invalid field types in the CONTROL or manifest file of F:\Library\vcpkg\ports\libsndfile\vcpkg.json
The following fields had the wrong types:

    features was expected to be an array of feature definitions

Error: There are invalid field types in the CONTROL or manifest file of F:\Library\vcpkg\ports\nng\vcpkg.json
The following fields had the wrong types:

    features was expected to be an array of feature definitions

Error: There are invalid field types in the CONTROL or manifest file of F:\Library\vcpkg\ports\numcpp\vcpkg.json
The following fields had the wrong types:

    features was expected to be an array of feature definitions

Error: There are invalid field types in the CONTROL or manifest file of F:\Library\vcpkg\ports\ogre\vcpkg.json
The following fields had the wrong types:

    features was expected to be an array of feature definitions

Error: There are invalid field types in the CONTROL or manifest file of F:\Library\vcpkg\ports\restbed\vcpkg.json
The following fields had the wrong types:

    features was expected to be an array of feature definitions

Error: There are invalid field types in the CONTROL or manifest file of F:\Library\vcpkg\ports\rtabmap\vcpkg.json
The following fields had the wrong types:

    features was expected to be an array of feature definitions

Error: There are invalid field types in the CONTROL or manifest file of F:\Library\vcpkg\ports\sdl2\vcpkg.json
The following fields had the wrong types:

    features was expected to be an array of feature definitions

Error: There are invalid field types in the CONTROL or manifest file of F:\Library\vcpkg\ports\sqlcipher\vcpkg.json
The following fields had the wrong types:

    features was expected to be an array of feature definitions

Error: There are invalid field types in the CONTROL or manifest file of F:\Library\vcpkg\ports\sqlitecpp\vcpkg.json
The following fields had the wrong types:

    features was expected to be an array of feature definitions

wampcc               2019-09-04       Wampcc is C++ library that implements the Web Application Messaging Protocol (...
wampcc[examples]                      Build example apps
wampcc[utils]                         Build utility apps

If your library is not listed, please open an issue at and/or consider making a pull request:
    https://github.com/Microsoft/vcpkg/issues
[DEBUG] F:\Library\vcpkg\toolsrc\src\vcpkg\commands.search.cpp(144)
[DEBUG] Exiting after 174114 us (155177 us)

**Comment by NancyLi1013** [comment]
Hi @kamilz98 

Thanks for posting this issue.

Have you run `.\bootstrap.bat ` before you execute the search command?

I cannot reproduce this on my machine.

```
PS F:\vcpkg> .\vcpkg.exe search wampcc --debug
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Using vcpkg-root: F:\vcpkg
[DEBUG] Using installed-root: F:\vcpkg\installed
[DEBUG] Using buildtrees-root: F:\vcpkg\buildtrees
[DEBUG] Using downloads-root: F:\vcpkg\downloads
[DEBUG] Using packages-root: F:\vcpkg\packages
[DEBUG] Using scripts-root: F:\vcpkg\scripts
wampcc               2019-09-04       Wampcc is C++ library that implements the Web Application Messaging Protocol (...
wampcc[examples]                      Build example apps
wampcc[utils]                         Build utility apps

If your library is not listed, please open an issue at and/or consider making a pull request:
    https://github.com/Microsoft/vcpkg/issues
[DEBUG] F:\vcpkg\toolsrc\src\vcpkg\commands.search.cpp(176)
[DEBUG] Exiting after 1554762 us (1527971 us)
```

**Comment by NancyLi1013** [comment]
Did you use `vcpkg upgrade` or `git pull` to update vcpkg?

**Comment by kamilz98** [comment]
I run `git pull` then `vcpkg upgrade` IIRC

**Comment by StarGate-One** [comment]
When you do a **`git pull`**, if any files are changed, added or deleted in the directory/folder **`[vcpkg-root]/toolsrc`** you need to bootstrap vcpkg again:
1, open cmd, powershell prompt or sh (ksh, csh, zsh, bash, etc) terminal window
2. `cd [vcpkg-root]`
3. On:
    - Windows `.\bootstrap-vcpkg.bat`
    - Linux `./bootstrap-vcpkg.sh`

**Comment by kamilz98** [comment]
I did the bootstrap and no more error shows. Thanks.
