### ISSUE TITLE
Error: Building package atk:arm-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by DieterDorsch** [microsoft/vcpkg#14486]
**Describe the bug**
vcpkg install gtk:arm-windows go to error 

**Environment**
- OS: [e.g. Windows/Linux etc...]
- Compiler: revision
PS C:\vksrc\vcpkg> ./vcpkg install gtk:arm-windows
Computing installation plan...
The following packages will be built and installed:
  * atk[core]:arm-windows
  * brotli[core]:arm-windows
  * bzip2[core]:arm-windows
  * cairo[core,gobject]:arm-windows
  * dirent[core]:arm-windows
  * expat[core]:arm-windows
  * fontconfig[core]:arm-windows
  * freetype[bzip2,core,png]:arm-windows
  * gdk-pixbuf[core]:arm-windows
    gtk[core]:arm-windows
  * harfbuzz[core,glib]:arm-windows
  * libepoxy[core]:arm-windows
  * libpng[core]:arm-windows
  * pango[core]:arm-windows
  * pixman[core]:arm-windows
  * ragel[core]:arm-windows
  * tool-meson[core]:arm-windows
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet arm-windows...
Starting package 1/17: atk:arm-windows
Building package atk[core]:arm-windows...
Could not locate cached archive: C:\Users\Dieter\AppData\Local\vcpkg\archives\62\628d1e5d451779517a0c23f1e5e9205350e35503.zip
-- Using community triplet arm-windows. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: C:\vksrc\vcpkg\triplets\community\arm-windows.cmake
-- Using cached C:/vksrc/vcpkg/downloads/atk-2.24.0.tar.xz
-- Cleaning sources at C:/vksrc/vcpkg/buildtrees/atk/src/atk-2-ed6f4e7c74.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vksrc/vcpkg/downloads/atk-2.24.0.tar.xz
-- Applying patch fix-linux-config.patch
-- Using source at C:/vksrc/vcpkg/buildtrees/atk/src/atk-2-ed6f4e7c74.clean
-- Configuring arm-windows
-- Building arm-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:142 (message):
    Command failed: C:/vksrc/vcpkg/downloads/tools/cmake-3.18.4-windows/cmake-3.18.4-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v -j9
    Working Directory: C:/vksrc/vcpkg/buildtrees/atk/arm-windows-dbg
    See logs for more information:
      C:\vksrc\vcpkg\buildtrees\atk\install-arm-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:93 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/atk/portfile.cmake:30 (vcpkg_install_cmake)
  scripts/ports.cmake:135 (include)

Error: Building package atk:arm-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: atk:arm-windows
  Vcpkg version: 2020.06.15-nohash
[install-arm-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/5512088/install-arm-windows-dbg-out.log)
[install-arm-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/5512092/install-arm-windows-dbg-out.log)

**To Reproduce**
1. ./vcpkg install xxxx
2. See error
Repro code when

**Expected behavior**

**Failure logs** 
-(please attached failure logs)

**Additional context**

**Comment by StarGate-One** [comment]
There are many of these in the log file:
>C:\vksrc\vcpkg\buildtrees\atk\src\atk-2-ed6f4e7c74.clean\atk/atkversion.h(1): warning C4828: The file contains a character starting at offset 0x83 that is illegal in the current source character set (codepage 65001).

- You could try the fix at https://github.com/microsoft/vcpkg/issues/12865#issuecomment-673216071 
- It may help/fix the issue

**Comment by DieterDorsch** [comment]
i am sorry #12865 brings no solution
the error is the same
[install-arm-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/5516892/install-arm-windows-dbg-out.log)

**Comment by JonLiu1993** [comment]
This issue hasn’t been updated more than 3 months, if it is still an issue, please reopen this issue.
