### ISSUE TITLE
[openimageio]Inconsistente usage with vcpkg under mac windows and linux need to add Imath and OpenEXR for Mac.

### ISSUE THREAD

**Issue by jmacey** [microsoft/vcpkg#14488]
When using the current vcpkg version of openimageio under windows and linux (RHEL 7 tested) I need to use the following in my CMakeLists.txt to build

find_package(OpenImageIO CONFIG REQUIRED)
target_link_libraries(oiiotest PRIVATE OpenImageIO::OpenImageIO OpenImageIO::OpenImageIO_Util)

However when using under Mac OSX I get the errors pasted below unless I add the following

find_package(OpenImageIO CONFIG REQUIRED)
find_package(IlmBase CONFIG REQUIRED)
find_package(OpenEXR CONFIG REQUIRED)

target_link_libraries(oiiotest PRIVATE OpenImageIO::OpenImageIO OpenImageIO::OpenImageIO_Util)
target_link_libraries(oiiotest PRIVATE  IlmBase::Iex IlmBase::Half IlmBase::Imath IlmBase::IexMath)
target_link_libraries(oiiotest PRIVATE OpenEXR::IlmImf OpenEXR::IlmImfUtil OpenEXR::IlmImfConfig)

This is inconsistent and means I need to add conditional targets definitions in my CMakeLists.txt files. I'm presuming this is an issue with the port file under mac, I have also had to modify the libSquish definition in the OpenImageIOTargets.cmake to remove the \$<LINK_ONLY:Libsquish::Libsquish>; line and add ${_IMPORT_PREFIX}/lib/libsquish.a again only on mac.  

Output of broken cmake file.

-- The C compiler identification is AppleClang 11.0.3.11030032
-- The CXX compiler identification is AppleClang 11.0.3.11030032
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
CMake Error at /Users/jmacey/vcpkg/scripts/buildsystems/vcpkg.cmake:418 (_add_executable):
  Target "oiiotest" links to target "IlmBase::Imath" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:14 (add_executable)

CMake Error at /Users/jmacey/vcpkg/scripts/buildsystems/vcpkg.cmake:418 (_add_executable):
  Target "oiiotest" links to target "IlmBase::IlmThread" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:14 (add_executable)

CMake Error at /Users/jmacey/vcpkg/scripts/buildsystems/vcpkg.cmake:418 (_add_executable):
  Target "oiiotest" links to target "IlmBase::IexMath" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:14 (add_executable)

CMake Error at /Users/jmacey/vcpkg/scripts/buildsystems/vcpkg.cmake:418 (_add_executable):
  Target "oiiotest" links to target "IlmBase::Iex" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:14 (add_executable)

CMake Error at /Users/jmacey/vcpkg/scripts/buildsystems/vcpkg.cmake:418 (_add_executable):
  Target "oiiotest" links to target "IlmBase::Half" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:14 (add_executable)

CMake Error at /Users/jmacey/vcpkg/scripts/buildsystems/vcpkg.cmake:418 (_add_executable):
  Target "oiiotest" links to target "OpenEXR::IlmImfUtil" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:14 (add_executable)

CMake Error at /Users/jmacey/vcpkg/scripts/buildsystems/vcpkg.cmake:418 (_add_executable):
  Target "oiiotest" links to target "OpenEXR::IlmImf" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:14 (add_executable)

CMake Error at /Users/jmacey/vcpkg/scripts/buildsystems/vcpkg.cmake:418 (_add_executable):
  Target "oiiotest" links to target "OpenEXR::IlmImfUtil" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:14 (add_executable)

CMake Error at /Users/jmacey/vcpkg/scripts/buildsystems/vcpkg.cmake:418 (_add_executable):
  Target "oiiotest" links to target "OpenEXR::IlmImf" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:14 (add_executable)

CMake Error at /Users/jmacey/vcpkg/scripts/buildsystems/vcpkg.cmake:418 (_add_executable):
  Target "oiiotest" links to target "OpenEXR::IlmImfUtil" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:14 (add_executable)

CMake Error at /Users/jmacey/vcpkg/scripts/buildsystems/vcpkg.cmake:418 (_add_executable):
  Target "oiiotest" links to target "OpenEXR::IlmImf" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:14 (add_executable)

CMake Error at /Users/jmacey/vcpkg/scripts/buildsystems/vcpkg.cmake:418 (_add_executable):
  Target "oiiotest" links to target "IlmBase::Imath" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:14 (add_executable)

CMake Error at /Users/jmacey/vcpkg/scripts/buildsystems/vcpkg.cmake:418 (_add_executable):
  Target "oiiotest" links to target "IlmBase::IlmThread" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:14 (add_executable)

CMake Error at /Users/jmacey/vcpkg/scripts/buildsystems/vcpkg.cmake:418 (_add_executable):
  Target "oiiotest" links to target "IlmBase::IexMath" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:14 (add_executable)

CMake Error at /Users/jmacey/vcpkg/scripts/buildsystems/vcpkg.cmake:418 (_add_executable):
  Target "oiiotest" links to target "IlmBase::Iex" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:14 (add_executable)

CMake Error at /Users/jmacey/vcpkg/scripts/buildsystems/vcpkg.cmake:418 (_add_executable):
  Target "oiiotest" links to target "IlmBase::Half" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:14 (add_executable)

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by jimwang118** [comment]
I tested the latest version of `vcpkg`, the calling method of `openimageio` port under `Windows`, `linux`, and `mac-osx` is the same, no need to modify `cmakelists.txt`.

**Comment by dg0yt** [comment]
IMO this is resolved. There have been significant improvements to this package since 2021. (#23918 in 2022 might be one of the relevant changes).
