### ISSUE TITLE
Duplicate files

### ISSUE THREAD

**Issue by joshuabogue** [microsoft/vcpkg#14489]
I am noticing that are duplicate files between the installed folder and the packages folder.  In the case some of these files can take up a lot of space.  For instance, when I build the angle library from google using vcpkg install angle:x64-windows I get the following:  D:\vcpkg\installed\x64-windows\debug\lib\  where this folder contains the libANGLE.lib which is about 877mb.  I also see this in the D:\vcpkg\packages\angle_x64-windows\lib folder.

The only reason I submitting an issue for this is that I am curious if this has been looked at.  Could this be solved by using symlinks on the platforms where they are supported?

**Comment by JackBoosY** [comment]
When we reach the installation step, we install the files that need to be installed into the _packages_, and post check the files in the _packages_ (such as: crt linkage, file location, copyright, etc.). When the test passes, these files will be copied to _installed_.
If the _packages_ on your machine are too large, you can delete it completely.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
