### ISSUE TITLE
wxwidgets errors

### ISSUE THREAD

**Issue by Alvaroalloc** [microsoft/vcpkg#14492]
A few weeks ago i had problems using libmariadb, and it was solved, but now i want to use wxwidgets, but i get this:
`[cmake] CMake Error at /Users/macuser/vcpkg/downloads/tools/cmake-3.18.4-osx/cmake-3.18.4-Darwin-x86_64/CMake.app/Contents/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
[cmake]   Could NOT find wxWidgets (missing: wxWidgets_LIBRARIES
[cmake]   wxWidgets_INCLUDE_DIRS) (Required is at least version "3.1")`

My CMakeLists.txt is this:
`cmake_minimum_required(VERSION 3.0.0)
project(gui VERSION 0.1.0)

find_package(wxWidgets 3.1 COMPONENTS core base REQUIRED)
include(${wxWidgets_USE_FILE})

add_executable(gui main.cpp)

target_link_libraries(gui PRIVATE ${wxWidgets_LIBRARIES})`

**Comment by JonLiu1993** [comment]
Duplicated to [#4756 ](https://github.com/microsoft/vcpkg/issues/4756)
