### ISSUE TITLE
[vcpkg] how to disable default features

### ISSUE THREAD

**Issue by rib** [microsoft/vcpkg#14491]
This is essentially a duplicate of https://github.com/microsoft/vcpkg/issues/11097 (closed) since the answer there didn't appear to work for me.

I'm trying to build ffmpeg with with the `gpl` feature disabled. ffmpeg has over 30 features and to start with I wasn't sure how to get the list of default features so I ended up running `./vcpkg install ffmpeg` waiting for the output that showed that it was actually building/installing:
`ffmpeg[avcodec,avdevice,avfilter,avformat,avresample,core,gpl,postproc,swresample,swscale]:x64-windows`

I then stopped the build, copy & pasted the list of default features (except removing `gpl`), and ran:

`.\vcpkg install ffmpeg[avcodec,avdevice,avfilter,avformat,avresample,core,postproc,swresample,swscale]:x64-windows`

I still see `Building package ffmpeg[avcodec,avdevice,avfilter,avformat,avresample,core,gpl,postproc,swresample,swscale]:x64-windows...` in the output - so it looks like it's still including the `gpl` feature?

**Comment by vicroms** [comment]
I looked into ffmpeg's control file and the `postproc` feature has a declared dependency on `gpl`. I don't know enough about ffmpeg to know if that dependency is correct. 

You can manually modify the CONTROL file to remove the dependency, as there is now way to remove a feature that is required upon by another feature or package. 

https://github.com/microsoft/vcpkg/blob/254bd8fe89ba37d77718cefac6cd9a3f3446ebdd/ports/ffmpeg/CONTROL#L35-L37

**Comment by rib** [comment]
Ah, ok, yeah it looks like that feature is a gpl feature itself.

In this case what's really desired is that I want the default features minus anything that depends on the gpl feature.

vcpkg is making it pretty hard to configure ffmpeg features here since I need to explicitly inspect the heirachy of dependencies and subtract anything depending on `gpl`. Ideally there could be some syntax like `-gpl` (as mentioned in #11097) that could solve this automatically. Any time there's an update to the ffmpeg package I currently need to remember to re-check the heirachy of dependencies to manually subtract gpl dependent features.

Thanks for helping me understand what's going on.

**Comment by vicroms** [comment]
@rib Thanks for the report.
