### ISSUE TITLE
[vcpkg] find_package treats OPTIONAL_COMPONENTS as obligatory

### ISSUE THREAD

**Issue by wrobelda** [microsoft/vcpkg#14494]
**Describe the bug**
I have a following declaration in my CMakeLists.txt:

```
find_package(Qt5 5.6 REQUIRED
  COMPONENTS Core DBus Widgets Svg Xml Test PrintSupport
  OPTIONAL_COMPONENTS Sql Concurrent QuickWidgets)
```

Despite the fact that some components are designated as optional with `OPTIONAL_COMPONENTS`, vcpkg ignores that switch and fails:

```
CMake Error at /Volumes/External/Sourcecode/vcpkg/scripts/buildsystems/vcpkg.cmake:555 (_find_package):
  Could not find a package configuration file provided by "Qt5QuickWidgets"
  with any of the following names:

    Qt5QuickWidgetsConfig.cmake
    qt5quickwidgets-config.cmake

  Add the installation prefix of "Qt5QuickWidgets" to CMAKE_PREFIX_PATH or
  set "Qt5QuickWidgets_DIR" to a directory containing one of the above files.
  If "Qt5QuickWidgets" provides a separate development package or SDK, be
  sure it has been installed.
Call Stack (most recent call first):
  cmake-build-debugfull-vcpkg/vcpkg_installed/x64-osx/share/cmake/Qt5/Qt5Config.cmake:28 (find_package)
  /Volumes/External/Sourcecode/vcpkg/scripts/buildsystems/vcpkg.cmake:555 (_find_package)
  CMakeLists.txt:91 (find_package)
```
Only after removing the `QuickWidgets` from `OPTIONAL_COMPONENTS` altogether it continues with installation.

**Environment**
- OS: macOS

**Expected behavior**
`OPTIONAL_COMPONENTS` should be exactly that – optional.

**Comment by JackBoosY** [comment]
cc @Neumann-A

**Comment by Neumann-A** [comment]
> vcpkg ignores that switch and fails:

let me correct this: I did not make any changes to the `XXXXConfig.cmake` of Qt - which I am aware of - which would change the upstream behavior regarding those keywords. As such this is not a vcpkg issue but an upstream Qt issue. Looking at the `Qt5BasicConfig.cmake.in` there is no handling for `<PackageName>_FIND_REQUIRED_<c>` so it is highly likely that it is simply not support by the current upstream Qt configs.
From what I see in the configs you could try to use two calls instead:
```
find_package(Qt5 5.6 REQUIRED COMPONENTS Core DBus Widgets Svg Xml Test PrintSupport)
find_package(Qt5 5.6 COMPONENTS Sql Concurrent QuickWidgets)
```

**Comment by wrobelda** [comment]
> let me correct this: I did not make any changes to the `XXXXConfig.cmake` of Qt - which I am aware of - which would change the upstream behavior regarding those keywords. As such this is not a vcpkg issue but an upstream Qt issue. Looking at the `Qt5BasicConfig.cmake.in` there is no handling for `<PackageName>_FIND_REQUIRED_<c>` so it is highly likely that it is simply not support by the current upstream Qt configs.

I suppose that in this case the [cmake-packages manpage](https://cmake.org/cmake/help/v3.6/manual/cmake-packages.7.html#using-packages) is quite misleading: even if it *does* make a point that the "Handling of `COMPONENTS` and `OPTIONAL_COMPONENTS` is defined by the package", the examples it uses that it is supported by the Qt itself :

```
Both types of packages also support specifying components of a package, either after the REQUIRED keyword:

find_package(Qt5 5.1.0 CONFIG REQUIRED Widgets Xml Sql)
or as a separate COMPONENTS list:

find_package(Qt5 5.1.0 COMPONENTS Widgets Xml Sql)
or as a separate OPTIONAL_COMPONENTS list:

find_package(Qt5 5.1.0 COMPONENTS Widgets
                       OPTIONAL_COMPONENTS Xml Sql
)
Handling of COMPONENTS and OPTIONAL_COMPONENTS is defined by the package.
```

> From what I see in the configs you could try to use two calls instead:
> 
> ```
> find_package(Qt5 5.6 REQUIRED COMPONENTS Core DBus Widgets Svg Xml Test PrintSupport)
> find_package(Qt5 5.6 COMPONENTS Sql Concurrent QuickWidgets)
> ```

This does work indeed.
