### ISSUE TITLE
[vcpkg] Improving cross-platform compatibility of codebase

### ISSUE THREAD

**Issue by ras0219-msft** [Microsoft/vcpkg#1449]
From https://github.com/Microsoft/vcpkg/issues/1435#issuecomment-314929968:

>I have been thinking about helping port vcpkg to Linux. However there are currently many dependencies on Windows. The one thing that is frustrating is the wstring/string issue. Since most of the functions on Windows work with wchars which is not the same with the Linux counter parts.  What are yout thoughts on defaulting to wstring on windows then string on Linux. Something like 
>
>```
>#ifdef _WIN32
>#define CustomString std::wstring
>#define Char wchar_t
>#elif __linux__
>#define CustomString std::string
>#define Char char
>#endif
>```

This is what we did in cpprestsdk and I believe it was a mistake; it makes it _extremely_ easy to accidentally use `std::string` or `std::wstring` instead of `CustomString`, which will compile fine on your current platform but break everything else.

I think there are two possible alternatives that alleviate this:
1. Fully wrap the custom string type in a struct so the typesystem prevents you from accidentally dropping down to `std::string`. I think this could be the right answer for some tightly-controlled codebases.
2. UTF-8/`std::string` everywhere with conversions only at the IO/syscall boundaries.

For Vcpkg, we'd prefer to go with option 2 due to the _significantly_ simpler implementation impact. I'd be happy to merge changes to the code in this direction and we already have `vcpkg::Strings::to_utf16` and `vcpkg::Strings::to_utf8` helpers.

**Comment by atkawa7** [comment]
@ras0219-msft Thanks for creating the issue. Another question what is the project structure going to look like.  Are all system depended functions going to remain in  `vcpkg_system.cpp` or we would have to separate them like `support/windows/vcpkg_system.cpp` and `support/linux/vcpkg_system.cpp` like what they do with [`https://github.com/llvm-mirror/llvm/tree/master/lib/Support`](https://github.com/llvm-mirror/llvm/tree/master/lib/Support).

**Comment by usernameiwantedwasalreadytaken** [comment]
How about using the same technique as [boost::nowide](http://cppcms.com/files/nowide/html/)? It may help with option 2...

**Comment by ras0219-msft** [comment]
Yeah, boost::nowide is exactly along the lines of option 2.

@atkawa7 I would prefer to keep both implementations side-by-side in a single file for now. The reason I would see to add platform specific files is if we need to add APIs used across the codebase that aren't available everywhere, though this would need serious justification.

Example:
> On Windows, we can leverage the system threadpool and we want to wrap it in some layers that are still threadpool-specific. On Linux, not only do we not have the threadpool, we (in this hypothetical example) don't even have a way to implement a similar API surface and need #ifdefs at every usage location to do some locally custom workaround.
>
> Thus, we might have a Windows-specific file for those threadpool APIs which are entirely unused and unavailable on other platforms.

I can't think of any situation currently where it wouldn't make sense to have the API available on all platforms, thus we shouldn't need platform-specific files.

**Comment by paul-michalik** [comment]
A note on porting to Linux: are you sure this makes sense? Instead of heaving some sort of compromise, why not having something which works **perfectly** on Windows? I suggest instead to investigate support for cross-compilation scenarios on Windows for other target platforms. As far as I can tell this would be a unique feature for a "brewing" package manager and **extremely** useful.

**Comment by usernameiwantedwasalreadytaken** [comment]
@paul-michalik I think it does make a lot of sense. See #57.

**Comment by paul-michalik** [comment]
#57 is not a justification... It's just an opinion which may be subject to discussion. Still, I believe that a brewing package manager capable of serving various target platforms from Windows would be very valuable.

**Comment by atkawa7** [comment]
@ras0219-msft Just wondering. How do you deal with `__interface`. It seems when I replace it with `class + public:` or `struct` I get so many errors ` method with override specifier 'override' did not override any base class` in `vcpkg_dependencies.cpp` related to `class AdjacencyProvider`

**Comment by ras0219-msft** [comment]
@paul-michalik Sorry, I think I wasn't clear in naming this issue.

This is not representing official support from Vcpkg for running on Linux. This issue is intended to represent that we're willing to work with anyone who wants to attempt it -- which @atkawa7 has indicated he'd like to :).

I firmly believe that making the codebase more cross-platform (and therefore accessible to more compilers and static analysis tools) will improve the overall code quality and have benefits even for Windows.

As for cross-compiling from Windows to other platforms, I would personally _love_ to have that! However, there are obstacles that need ironing out:
- Every additional supported platform introduces a large burden onto maintainers, who often only care about the one or two platforms they primarily target.
- Is cross-compiling the right answer, or would it be better to just wrap a native Linux distribution instead (i.e. maybe we just wrap Gentoo/pacman/apt-get)? Wrapping should result in higher quality packages, but it would also cause version skew across platforms.

Exactly as you expressed above, every additional supported configuration is a compromise, so we are instead currently focused on making the Windows-on-Windows experience as perfect as we can!

@atkawa7 You'll need to mark all the functions as `virtual void foo() = 0`. See https://docs.microsoft.com/en-us/cpp/cpp/interface for more details.

**Comment by atkawa7** [comment]
@ras0219-msft Another question. Just wondering with these lines in `vcpkg_system.cpp` why  vcpkg uses environment to get architecture? And not using macros such as those defined here [`Architectures`](https://sourceforge.net/p/predef/wiki/Architectures/).
```c++
Optional<CPUArchitecture> to_cpu_architecture(CStringView arch)
    {
        if (Strings::case_insensitive_ascii_compare(arch, "x86") == 0) return CPUArchitecture::X86;
        if (Strings::case_insensitive_ascii_compare(arch, "x64") == 0) return CPUArchitecture::X64;
        if (Strings::case_insensitive_ascii_compare(arch, "amd64") == 0) return CPUArchitecture::X64;
        if (Strings::case_insensitive_ascii_compare(arch, "arm") == 0) return CPUArchitecture::ARM;
        if (Strings::case_insensitive_ascii_compare(arch, "arm64") == 0) return CPUArchitecture::ARM64;
        return nullopt;
    }

    CPUArchitecture get_host_processor()
    {
        auto w6432 = get_environment_variable(L"PROCESSOR_ARCHITEW6432");
        if (auto p = w6432.get()) return to_cpu_architecture(Strings::to_utf8(*p)).value_or_exit(VCPKG_LINE_INFO);

        auto procarch = get_environment_variable(L"PROCESSOR_ARCHITECTURE").value_or_exit(VCPKG_LINE_INFO);
        return to_cpu_architecture(Strings::to_utf8(procarch)).value_or_exit(VCPKG_LINE_INFO);
    }
```
See [https://github.com/Microsoft/vcpkg/blob/master/toolsrc/src/vcpkg_System.cpp#L26-L43](https://github.com/Microsoft/vcpkg/blob/master/toolsrc/src/vcpkg_System.cpp#L26-L43)

**Comment by ras0219-msft** [comment]
The host that vcpkg was built for doesn't _necessarily_ map to the true host architecture. Bootstrap always builds for x86, for example.

**Comment by atkawa7** [comment]
Thanks @ras0219-msft

**Comment by atkawa7** [comment]
So would you recommend using something like on linux 

```c++
#include <sys/utsname.h>

CPUArchitecture get_host_processor()
    {
        struct utsname info;

        if (uname(&info) == -1)
        {
            return to_cpu_architecture(std::string()).value_or_exit(VCPKG_LINE_INFO);
        }
        return to_cpu_architecture(info.machine).value_or_exit()
    }
```

**Comment by paulsapps** [comment]
I think you are just after the string "x86" or x64" here?

**Comment by ras0219-msft** [comment]
The codebase now builds on Linux! Thank you very much @atkawa7 for starting this :)

See #1528 for details on how to try it out.

**Comment by atkawa7** [comment]
@ras0219-msft Awesome !!!

**Comment by atkawa7** [comment]
@ras0219-msft Do you have a example on how we could build it?

**Comment by ras0219-msft** [comment]
In https://github.com/Microsoft/vcpkg/pull/1528#issuecomment-346975155 I (very concisely) lay out the gist of how to build it. There's a `toolsrc\CMakeLists.txt`, but it requires a recent g++ -- I've listed out the exact command lines that work in WSL inside that comment.
