### ISSUE TITLE
Wrong version of OpenSSL was installed

### ISSUE THREAD

**Issue by luizfernandonb** [microsoft/vcpkg#14508]
I recently installed OpenSSL via vcpkg, but it installed a different version than the one I had when I checked for the package, here is the version it should install:
![image](https://user-images.githubusercontent.com/42288418/98728881-d619e100-2378-11eb-8b09-1e9c97dcb38b.png)

Here is the version he installed:
![image](https://user-images.githubusercontent.com/42288418/98729034-0c576080-2379-11eb-811a-b5c9b7628bbb.png)

What went wrong? How can I force vcpkg to install the latest version?

**Comment by StarGate-One** [comment]
1. What do you get when you open a command prompt and end `where openssl`?
2. Unless you have added `[vcpkg-root]\installed\[triplet]\tools\openssl` to the windows environment variable path, windows will execute from the first place it finds an executable binary named openssl.
3. `cd [vcpkg-root]\installed\[triplet]\tools\openssl` and enter `.\openssl version` and what to you get?
4. Note: `openssl-[unix/uwp/windows]` has been deprecated and no longer used and are empty packages.
5. I see your openssl in the `vcpkg search` shows an old version.
   - `cd [vcpkg-root]`
   - `git pull` to update vcpkg with latest changes
   - `.\bootstrap-vcpkg.bat` for windows or `./bootstrap-vcpkg.sh` for linux
   - `vcpkg upgrade --no-dry-run` to upgrade all packages with new updates or upgrades

**Comment by luizfernandonb** [comment]
> 1. What do you get when you open a command and/or terminal prompt and enter `where openssl` for windows or  `whereis openssl` for linux?
> 2. Unless you have added `[vcpkg-root]\installed\[triplet]\tools\openssl` to the windows/linux environment variable PATH, windows/linux will execute from the first place it finds an executable binary named openssl.
> 3. `cd [vcpkg-root]\installed\[triplet]\tools\openssl` and enter `.\openssl version` windows or `./openssl version` linux and what to you get?
> 4. Note: `openssl-[unix/uwp/windows]` has been deprecated and no longer used and are empty packages.
> 5. I see your openssl in the `vcpkg search` shows an old version.
>    
>    * `cd [vcpkg-root]`
>    * `git pull` to update vcpkg with latest changes
>    * `.\bootstrap-vcpkg.bat` for windows or `./bootstrap-vcpkg.sh` for linux
>    * `vcpkg upgrade --no-dry-run` to upgrade all packages with new updates or upgrades

Thanks, I noticed that OpenSSL was also installed by MinGW Installation Manager when I typed `where openssl`, I removed it, but now when I type ʻopenssl`, an error appears on the console, is it normal?

**Comment by PhoebeHui** [comment]
@luizfernandonb, what error does it show in console?

For me:
F:\vcpkg\src\installed\x64-windows\tools\openssl>openssl.exe version
OpenSSL 1.1.1g  21 Apr 2020

**Comment by luizfernandonb** [comment]
> @luizfernandonb, what error does it show in console?
> 
> For me:
> F:\vcpkg\src\installed\x64-windows\tools\openssl>openssl.exe version
> OpenSSL 1.1.1g 21 Apr 2020

![image](https://user-images.githubusercontent.com/42288418/98807361-4b2cfb00-23f9-11eb-8a39-447251fd7ecc.png)

'openssl' is not recognized as an internal command
or external, an operable program or a batch file.

**Comment by sfhacker** [comment]
Are we **STILL** having issues with OpenSSL?

**Comment by Neumann-A** [comment]
@luizfernandonb You have to go to `<vcpkgroot>/installed/<triplet>/tools/openssl` to execute openssl.exe built by vcpkg. vcpkg does not magically add the path to the PATH env variable. Please lern how windows/cmd does binary/executable lookup via PATH environment. StarGate-One clearly explained how to execute openssl.exe built by vcpkg. 

@PhoebeHui Just close the issue. This has nothing to do with vcpkg.

**Comment by PhoebeHui** [comment]
@Neumann-A, thanks for your commnents!

@luizfernandonb, feel free to open an new issue if you encounter some problems in vcpkg.
