### ISSUE TITLE
CMAKE_FIND_USE_CMAKE_SYSTEM_PATH and CMAKE_FIND_USE_CMAKE_PATH to OFF blocks CMake from finding vcpkg packages

### ISSUE THREAD

**Issue by gracicot** [microsoft/vcpkg#14507]
**Describe the bug**
When setting `CMAKE_FIND_USE_CMAKE_SYSTEM_PATH` and `CMAKE_FIND_USE_CMAKE_PATH` to OFF, it cannot find packages installed by vcpkg. This was my attempt to block CMake from finding system provided libraries.

**Environment**
- OS: Linux Ubuntu 20.04 (docker)
- Compiler: GCC 10.0.1

**To Reproduce**
1. Have a simple manifest file installing a package
2. Have a CMake file that contains `set(CMAKE_FIND_USE_CMAKE_SYSTEM_PATH OFF)` and `set(CMAKE_FIND_USE_CMAKE_PATH OFF)` and try to find the package
3. Notice that it cannot found the packages located inside `build/vcpkg_installed`

**Expected behavior**
This variable is used to disable finding libraries installed in system path. Setting it to `OFF` when using a package manager is desirable, since it provides better isolation from the system. Not setting it to `OFF` may induce subtle breakage when trying to compile a project from different machines.

---

For example, the CMake user could set `set(CMAKE_FIND_PACKAGE_PREFER_CONFIG ON)` so CMake prioritize config file over its own modules, which can be very benefical for packages like boost. Let's say that our user add a dependency to `libA`, which provide a CMake find module. `libA` is installed through `vcpkg`. `find_package(libA)` finds our library installed by vcpkg. User is happy.

Then, user install `libA` through its system package manager. It installs a newer version of `libA` which exposes a CMake config module. CMake prefers that version instead and on the next cache generation, use the system provided library which introduce subtle breakage. User looses his hairs over hard to reproduce bugs since the build system acted in a surprising way.

---

If vcpkg already have a mechanism to prevent that, then feel free to close this issue. Otherwise, I would expect `CMAKE_FIND_USE_CMAKE_SYSTEM_PATH` to work by disallowing system package but still allowing vcpkg installed packages.

**Additional context**

I usually have a CMake file that contains this:

```cmake
set(CMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY ON)
set(CMAKE_FIND_USE_CMAKE_SYSTEM_PATH OFF)
set(CMAKE_FIND_PACKAGE_PREFER_CONFIG ON)
set(CMAKE_FIND_USE_CMAKE_PATH OFF)
set(CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH OFF)
```

This makes CMake finding only packages that I intended to use, the ones I added in `CMAKE_PREFIX_PATH`. Now I want to use `vcpkg` to manage my packages, but I still want isolation from system packages. Is there something that can offer me this requirement in vcpkg? Many thanks.

**Comment by Neumann-A** [comment]
>This makes CMake finding only packages that I intended to use, the ones I added in CMAKE_PREFIX_PATH

How are you setting `CMAKE_PREFIX_PATH`? (If you do a simple `set` there is your error) 
Simply check if your `CMAKE_PREFIX_PATH` contains the vcpkg paths if not you messed something up (assuming you are using the toolchain vcpkg.cmake)

**Comment by gracicot** [comment]
@Neumann-A When I was not using vcpkg, I was setting `CMAKE_PREFIX_PATH` using a file that configured everything so that `find_package` would work out of the box. (of course, I used `list(APPEND ... ....)` for that)

Now that I'm trying to change to vcpkg, I expect not touching this variable at all. I also expect that it's possible enabling vcpkg in a way that CMake won't find packages, executable, files, libraries or any paths from the system.

The situation is I'm trying to move away from [my own, home made package manager](https://github.com/gracicot/subgine-pkg) to vcpkg. The recent addition of manifest file make that move possible and I'm not too fan of conan. It's entirely made CMake and from all the weird error I got, a lot of them was due to CMake picking up system packages for a dependency's dependency in a way I didn't expected.

**Comment by gracicot** [comment]
Uh, it seem my issue is only happening with boost. In the end it might only be a problem with this particular package. Sorry that I didn't researched the problem further before posting.

Here's the project that reproduce the issue:

**vcpkg.json**
```json
{
    "name": "mypackage",
    "version-string": "0.1.0-dev",
    "dependencies": [
        "boost-mp11"
    ]
}
```

**CMakeLists.txt**
```cmake
cmake_minimum_required(VERSION 3.17)
project(test-vcpkg)

set(CMAKE_FIND_USE_CMAKE_SYSTEM_PATH OFF)
set(CMAKE_FIND_USE_CMAKE_PATH OFF)

find_package(Boost 1.74 REQUIRED COMPONENTS system)

add_executable(test-vcpkg main.cpp)
target_link_libraries(test-vcpkg PRIVATE Boost::system)
```

**main.cpp**
```c++
#include <iostream>
#include <boost/mp11.hpp>

auto main() -> int {
    std::cout << "hello" << std::endl;
}
```

Removing either `set(CMAKE_FIND_USE_CMAKE_SYSTEM_PATH OFF)` or `set(CMAKE_FIND_USE_CMAKE_PATH OFF)` make the configuration successful.

Here's the CMake output:

```
build$ rm CMakeCache.txt && cmake .. -DCMAKE_TOOLCHAIN_FILE=/root/build/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_GENERATOR=Ninja -DCMAKE_MAKE_PROGRAM=/usr/bin/ninja -DCMAKE_CXX_COMPILER=/usr/bin/g++-10 -DCMAKE_C_COMPILER=/usr/bin/gcc-10
-- Running vcpkg install
-- Running vcpkg install - done
-- The C compiler identification is GNU 10.0.1
-- The CXX compiler identification is GNU 10.0.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/gcc-10 - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++-10 - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /opt/cmake/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find Boost (missing: Boost_INCLUDE_DIR system) (Required is at
  least version "1.74")
Call Stack (most recent call first):
  /opt/cmake/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  /opt/cmake/share/cmake-3.18/Modules/FindBoost.cmake:2177 (find_package_handle_standard_args)
  /root/build/vcpkg/scripts/buildsystems/vcpkg.cmake:519 (_find_package)
  CMakeLists.txt:10 (find_package)


-- Configuring incomplete, errors occurred!
See also "/workspaces/src4/build/CMakeFiles/CMakeOutput.log".
See also "/workspaces/src4/build/CMakeFiles/CMakeError.log".
```

**Comment by Neumann-A** [comment]
according to the `find_package` documentation you want to remove `set(CMAKE_FIND_USE_CMAKE_PATH OFF)`

**Comment by gracicot** [comment]
@Neumann-A Why is that? Is it because `CMAKE_FIND_USE_CMAKE_PATH` will disable find modules that are shipped with CMake and in the case I stated we need those find modules?

**Comment by Neumann-A** [comment]
@gracicot  disabling `CMAKE_FIND_USE_CMAKE_PATH` disables usage of `CMAKE_PREFIX_PATH` which vcpkg uses/sets. It is as simple as that. Please reread https://cmake.org/cmake/help/latest/command/find_package.html

**Comment by gracicot** [comment]
Hmm, you're right. I'll close this issue. Thanks. It seems in my examples I was assuming other things and I overlooked this.
