### ISSUE TITLE
Manifest definition

### ISSUE THREAD

**Issue by OgreTransporter** [microsoft/vcpkg#14500]
In the documentation of the manifest definition the reference is missing that the line ends must be by force in the Linux format.

It would also be better that the script `Check-ManifestFormatting.ps1` tests for invalid line breaks and displays a suitable error message and not just *The formatting of the manifest files didn't match our expectation.*.

It would be even better if incorrect line breaks were corrected when running `vcpkg.exe format-manifest --all`.

The best solution would be if the line break would not play a role. Alternatively you could use gitattributes to set the line endings for all files to LF.

**Comment by strega-nil** [comment]
@OgreTransporter `format-manifest` _should_ replace the newlines... it's very odd that it doesn't.

**Comment by OgreTransporter** [comment]
@strega-nil It did not work with my port #14485. I had to change the line ends by hand with Notepad++.

**Comment by strega-nil** [comment]
@OgreTransporter that's really odd... Hopefully that doesn't happen again for you?

**Comment by JackBoosY** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.
