### ISSUE TITLE
several libraries fail to download with identical errors

### ISSUE THREAD

**Issue by tombadmanship** [microsoft/vcpkg#14506]
**Describe the bug**
vcpkg install fails with this collection of 7 libraries.

bzip2:x64-windows-static 
eigen3:x64-windows-static 
libffi:x64-windows-static 
pcre:x64-windows-static 
protobuf:x64-windows-static 
protobuf:x86-windows-static 
zlib:x64-windows-static               

**Environment**
Windows

**To Reproduce**
1. .\vcpkg install xxxx
2. See error

**Expected behavior**
I thought these packages would install properly. Several others have installed properly.

**Failure logs** 

A FEW OF THE ERRORS:

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:103 
File does not have expected hash: [File path[], Expected hash[], Actual hash[]]

  Package: xxxx
  Vcpkg version: 2020.06.15-nohash

  The file may have been corrupted in transit.  This can be caused by
  proxies.  If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY
  environment variables to
  "https://user:password@your-proxy-ip-address:port/"

ninja: build stopped: subcommand failed.

**Comment by NancyLi1013** [comment]
Hi @tombadmanship 

Thanks for posting this issue.

It seems that you didn't use the latest vcpkg.

Could you please try to use `git pull ` to update vcpkg to the latest version and then rebuild these ports?

**Comment by tombadmanship** [comment]
I'm sorry to say that this is not the issue. I re-pulled vcpkg and these ports still fail in the same way.

**Comment by NancyLi1013** [comment]
Could you please run `.\bootstrap-vcpkg.bat` then rebuild these ports?

Please make sure you have updated to the latest vcpkg 2020.11.12.

**Comment by tombadmanship** [comment]
it seems to be that i don't have the utility to unzip .xz, but that utility to unzip .xz comes from a vcpkg install.

CMake Error: Problem extracting tar: C:/vcpkg/downloads/msys-mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz

**Comment by NancyLi1013** [comment]
Could you please help provide the versions of Windows and CMake?

Please also copy the build process on the powershell console here.

Such as `./vcpkg install bzip2:x64-windows-static`

```
PS F:\new\vcpkg> .\vcpkg.exe install bzip2:x64-windows-static
Computing installation plan...
The following packages will be built and installed:
    bzip2[core]:x64-windows-static
Detecting compiler hash for triplet x64-windows-static...
Starting package 1/1: bzip2:x64-windows-static
Building package bzip2[core]:x64-windows-static...
Could not locate cached archive: C:\Users\v-ruil\AppData\Local\vcpkg\archives\56\56d8eda93f9ed8600d50548b21d171013ab4e8eb.zip
-- Using cached F:/new/vcpkg/downloads/bzip2-75a94bea3918e612b879d6a11ca64b8689526147.tar.gz
-- Cleaning sources at F:/new/vcpkg/buildtrees/bzip2/src/8689526147-1ef169fbaa.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source F:/new/vcpkg/downloads/bzip2-75a94bea3918e612b879d6a11ca64b8689526147.tar.gz
-- Applying patch fix-import-export-macros.patch
-- Using source at F:/new/vcpkg/buildtrees/bzip2/src/8689526147-1ef169fbaa.clean
-- Configuring x64-windows-static
-- Building x64-windows-static-dbg
-- Building x64-windows-static-rel
-- Using msys root at F:/new/vcpkg/downloads/tools/msys2/c809757c94447846
-- Fixing pkgconfig file: F:/new/vcpkg/packages/bzip2_x64-windows-static/lib/pkgconfig/bzip2.pc
-- Fixing pkgconfig file: F:/new/vcpkg/packages/bzip2_x64-windows-static/debug/lib/pkgconfig/bzip2.pc
-- Installing: F:/new/vcpkg/packages/bzip2_x64-windows-static/share/bzip2/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\v-ruil\AppData\Local\vcpkg\archives\56\56d8eda93f9ed8600d50548b21d171013ab4e8eb.zip
Building package bzip2[core]:x64-windows-static... done
Installing package bzip2[core]:x64-windows-static...
Installing package bzip2[core]:x64-windows-static... done
Elapsed time for package bzip2:x64-windows-static: 25.27 s

Total elapsed time: 35.53 s

The package bzip2 is compatible with built-in CMake targets:

    find_package(BZip2 REQUIRED)
    target_link_libraries(main PRIVATE BZip2::BZip2)
```

**Comment by sfhacker** [comment]
@tombadmanship Perhaps your environment is broken somehow. Try reinstalling it.

**Comment by tombadmanship** [comment]
I found the issue.

Luckily, .xz files are human readable, and the compression method of choice for the package I was using. In a log file was an error report for location settings. I was being geoblocked by a local firewall.

**Comment by NancyLi1013** [comment]
@tombadmanship 
Could you please disable firewall on your local an then try to install this again?

**Comment by tombadmanship** [comment]
I meant to imply that the problem was solved. I unblocked and was able to install.

An error such as that would be helpful to have printed to screen.

**Comment by NancyLi1013** [comment]
@tombadmanship

Thanks for your suggestion. Sorry, currently, there is no plan to implement this feature. 

Since you have solved this problem, I'm closing this issue for now.
