### ISSUE TITLE
Incorrect changelog for 2020.11

### ISSUE THREAD

**Issue by dalle** [microsoft/vcpkg#14515]
It seems as the changelog for [release 2020.11](https://github.com/microsoft/vcpkg/releases/tag/2020.11) contains duplicate entries from changelog for [release 2020.07](https://github.com/microsoft/vcpkg/releases/tag/2020.07).
The 2020.11 changelog also doesn't include a lot of updated ports in the release.

**Comment by vicroms** [comment]
Hi @dalle thanks for reporting, we are in process of migrating our CHANGELOG generator from TypeScript to PowerShell in order to publish it alongside the rest of our scripts.

Hopefully, in future releases we will be able to reduce the number of bugs in the generator.
