### ISSUE TITLE
[New Port Request] mariadb-connector-cpp

### ISSUE THREAD

**Issue by zibingrong** [microsoft/vcpkg#14514]
Library name: mariadb-connector-cpp

Library description: This is a beta release of the MariaDB Connector/C++.

Source repository URL: https://github.com/mariadb-corporation/mariadb-connector-cpp

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
