### ISSUE TITLE
[vcpkg] vcpkg requires dumpbin.exe with gcc on windows

### ISSUE THREAD

**Issue by vadi2** [microsoft/vcpkg#14525]
**Describe the bug**
Very similar to https://github.com/microsoft/vcpkg/issues/11467, but for GCC - `objdump` is not used an an error is given: `       | Neither dumpbin nor llvm-objdump could be found. Can not take care of dll dependencies.`

**Environment**
- OS: Windows
- Compiler: MinGW 8.1.0

**To Reproduce**
Build with vcpkg and mingw.

**Expected behavior**
Deploy to work with `objdump` like it already works with `llvm-objdump`.

**Failure logs** 
-(please attached failure logs)

**Additional context**
https://github.com/microsoft/vcpkg/pull/11898 already has a solution. The same solution might work for `objdump`.

**Comment by vadi2** [comment]
Workaround for the time being is to use `-DVCPKG_APPLOCAL_DEPS=OFF`.

**Comment by sfhacker** [comment]
Pardon my question: what is dumpbin needed for when building ports from source on MinGW?
We build large and complex projects from source on a regular basis and dumpbin has never been required!

**Comment by vadi2** [comment]
dumpbin is not needed with mingw, it has its own objdump.

**Comment by sfhacker** [comment]
> dumpbin is not needed with mingw, it has its own objdump.

That's good to know!

What is dumpbin doing in your MinGW environment then? Are you mixing environments and/or tools?

**Comment by vadi2** [comment]
I don't have dumpbin. That's why it's not found.

**Comment by sfhacker** [comment]
This is so confusing. There is an open issue where the user had mixed VS with MinGW. Obviously, it didn't work.

**Comment by vadi2** [comment]
I'm not mixing VS with MinGW. I'm afraid it is you who is confused. Thanks for the help anyway!

**Comment by strega-nil** [comment]
@vadi2 If you would like, you can look into adding this feature; unfortunately, we do not have experience on the team with MinGW's stuff.

@sfhacker Please keep your comments on-topic.

**Comment by vadi2** [comment]
@longnguyen2004 are you able to look into this one by chance?

**Comment by longnguyen2004** [comment]
@vadi2 It's related to the [applocal.ps1](https://github.com/microsoft/vcpkg/blob/master/scripts/buildsystems/msbuild/applocal.ps1) script, which copies the dlls over to the build directory automatically upon building. For now it only supports MS dumpbin and LLVM llvm-objdump to find the dependencies. I can try to add support for GCC objdump.

@sfhacker Please refrain from commenting if you don't understand vcpkg internals.
