### ISSUE TITLE
Binaries that statically link SDL2:x64-windows-static-md are exporting symbols

### ISSUE THREAD

**Issue by Keithcat1** [microsoft/vcpkg#14527]
Statically linking SDL2 build using the x64-windows-static-md triplet causes "dumpbin /exports out.exe" to output exported C symbols from SDL2.
I think this is also stopping the linker from doing dead code removal because it thinks the symbols are required. Can this be fixed? Thanks.

**Comment by JonLiu1993** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue
