### ISSUE TITLE
[New Port Request] XLSX I/O

### ISSUE THREAD

**Issue by pomer** [microsoft/vcpkg#14537]
Library name:
XLSX I/O
Library description:
XLSX I/O aims to provide a C library for reading and writing .xlsx files. The .xlsx file format is the native format used by Microsoft(R) Excel(TM) since version 2007.
Source repository URL:
https://github.com/brechtsanders/xlsxio
Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by linquize** [comment]
`xlsxio` version 0.2.29
It uses `minizip` by default
CMake options: `BUILD_SHARED`, `BUILD_STATIC`, `BUILD_EXAMPLES`
Tools: `xlsxio_csv2xlsx`, `xlsxio_xlsx2csv`
