### ISSUE TITLE
vcpkg install libmariadb:x64-windows-static failed,  vcpkg install libmariadb:x64-windows everything is ok.

### ISSUE THREAD

**Issue by chris-shenzhen-china** [microsoft/vcpkg#14532]
C:\vcpkg>vcpkg install libmariadb:x64-windows-static
Computing installation plan...
The following packages will be built and installed:
    libmariadb[core,openssl,zlib]:x64-windows-static
Detecting compiler hash for triplet x64-windows-static...
Starting package 1/1: libmariadb:x64-windows-static
Building package libmariadb[core,openssl,zlib]:x64-windows-static...
Could not locate cached archive: C:\Users\test\AppData\Local\vcpkg\archives\9d\9dffaabf895473251c6b4c54150101ffe15a9056.zip
-- Using cached C:/vcpkg/downloads/MariaDB-mariadb-connector-c-159540fe8c8f30b281748fe8a1b79e8b17993a67.tar.gz
-- Cleaning sources at C:/vcpkg/buildtrees/libmariadb/src/8b17993a67-c4afbe148c.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg/downloads/MariaDB-mariadb-connector-c-159540fe8c8f30b281748fe8a1b79e8b17993a67.tar.gz
-- Applying patch md.patch
-- Applying patch disable-test-build.patch
-- Applying patch fix-InstallPath.patch
-- Applying patch fix-iconv.patch
-- Applying patch export-cmake-targets.patch
-- Using source at C:/vcpkg/buildtrees/libmariadb/src/8b17993a67-c4afbe148c.clean
-- Configuring x64-windows-static
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:106 (message):
    Command failed: ninja -v
    Working Directory: C:/vcpkg/buildtrees/libmariadb/x64-windows-static-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\vcpkg\buildtrees\libmariadb\config-x64-windows-static-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:312 (vcpkg_execute_required_process)
  ports/libmariadb/portfile.cmake:30 (vcpkg_configure_cmake)
  scripts/ports.cmake:136 (include)

Error: Building package libmariadb:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libmariadb:x64-windows-static
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by JackBoosY** [comment]
Please provide failure log _C:\vcpkg\buildtrees\libmariadb\config-x64-windows-static-out.log_.

Thanks.

**Comment by chris-shenzhen-china** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/vcpkg"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月12日(星期四) 下午4:51
收件人:&nbsp;"microsoft/vcpkg"<vcpkg@noreply.github.com&gt;;
抄送:&nbsp;"Lucky&amp;nbsp;Lee-0"<sz_lidong@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [microsoft/vcpkg] vcpkg install libmariadb:x64-windows-static failed,  vcpkg install libmariadb:x64-windows everything is ok. (#14532)





 
Please provide failure log C:\vcpkg\buildtrees\libmariadb\config-x64-windows-static-out.log.
 
Thanks.

**Comment by chris-shenzhen-china** [comment]
what should i do to install libmariadb:x64-windows-static?

**Comment by JackBoosY** [comment]
Please update vcpkg using `git pull` and retry.

**Comment by chris-shenzhen-china** [comment]
I updated the vcpkg and install mariadb:windows-static, it works well, thanks then.
