### ISSUE TITLE
target_link_libraries(PRIVATE) in dependency chain leaking into the ports 

### ISSUE THREAD

**Issue by wrobelda** [microsoft/vcpkg#14531]
**Describe the bug**
We have this issue with many of the KDE's KF5 libraries. Specifically, the libraries declared as PRIVATE in target_link_libraries() by the libraries linked will somehow leak into the dependency chain and have vcpkg port fail with "target was not found" as if said libraries were linked in the main CMakeList itself. 

I have [previously reported](https://invent.kde.org/frameworks/kiconthemes/-/merge_requests/7) that to KDE framework team thinking it was on our end, despite that the libraries build fine outside vcpkg, but their [response](https://invent.kde.org/frameworks/kiconthemes/-/merge_requests/7#note_103369) confirms that this is something with vcpkg.

We observed that both with Qt5 modules as well as with KF5,  on both macOS and Windows, in several of our ports (so far: kf5crash,  kf5textwidgets, kf5xmlgui, kf5completion, kf5iconthemes, kf5bookmarks, kf5declarative, kf5service, kf5kio)

**Environment**
- OS: macOS and Windows

**To Reproduce**
1. Checkout my branch from [this](https://github.com/microsoft/vcpkg/pull/13469) PR
2. Edit the kf5xmlgui portfile, remove the `add-missing-kf5guiaddons-kf5archive-deps.patch` 
3. `./vcpkg install kf5xmlgui`
4. Notice the `Target "KF5XmlGui" links to target "KF5::GuiAddons" but the target was not found.` error.

**Expected behavior**
`KF5::GuiAddons` is defined as a PRIVATE dependency of KConfigWidgets, which itself is a dependency of kf5xmlgui, yet vcpkg somehow makes CMake treat it as was direct requirement of kf5xmlgui. 

**Failure logs** 
```
CMake Error at /Volumes/External/Sourcecode/vcpkg/scripts/buildsystems/vcpkg.cmake:453 (_add_library):
  Target "KF5XmlGui" links to target "KF5::GuiAddons" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  src/CMakeLists.txt:83 (add_library)
```

**Comment by JackBoosY** [comment]
I think the reason for this issue is the lack of `find_dependency(GuiAddons)` in the cmake file exported by some KF5 ports.
Can you check the `*config.cmake` file that depends on the KF5 port of GuiAddons exported? Their path should be _VCPKG_ROOT/installed/TRIPLET/share/PORT_NAME_.

**Comment by Neumann-A** [comment]
Ok let me deduce some things from your post

>./vcpkg install kf5xmlgui

triplet = x64-linux ? -> VCPKG_LIBRARY_LINKAGE = static -> BUILD_SHARED_LIBS = FALSE

>KF5::GuiAddons is defined as a PRIVATE dependency of KConfigWidgets, which itself is a dependency of kf5xmlgui, yet vcpkg somehow makes CMake treat it as was direct requirement of kf5xmlgui.

That is not how CMake works. If the library linkage is static private dependencies get transitively forwarded (since linkage against them is required until you build an executable / shared object). As such the targets are mentioned automatically in the INTERFACE_LINKED_LIBRARIES properties of the target.
See also https://gitlab.kitware.com/cmake/cmake/-/issues/19611 

So this is definitely an upstream issue and not a vcpkg issue.

**Comment by wrobelda** [comment]
@Neumann-A It completely flew over my head that macOS builds are also static. Yet again, I stand corrected. I brought it up with upstream and we'll discuss there. Thanks.
