### ISSUE TITLE
Port aws-sdk-cpp has a non relocatable rpath, which becomes problematic when used with (remote) vcpkg binary caching

### ISSUE THREAD

**Issue by klalumiere** [microsoft/vcpkg#14544]
**Describe the bug**
`aws-sdk-cpp` sets `CMAKE_INSTALL_RPATH_USE_LINK_PATH` to true in its **CMakeLists.txt** file. The consequence is that when we install it with vcpkg (with a triplet that uses dynamic libraries, like the triplet `x64-linux-dynamic` described [in the documentation](https://vcpkg.readthedocs.io/en/latest/examples/overlay-triplets-linux-dynamic/)), the `RPATH` of the installed libraries contains the full path where it was installed. This becomes problematic when the binary caching feature of vcpkg is used.

For instance, assume that I install `aws-sdk-cpp` with vcpkg in `/home/klalumiere/Projects/vcpkg/`. The library `/home/klalumiere/Projects/vcpkg/installed/x64-linux-dynamic/lib/libaws-cpp-sdk-core.so` now contains the RPATH `/home/klalumiere/Projects/vcpkg/installed/x64-linux-dynamic/lib`. If `VCPKG_BINARY_SOURCES` contains a Nuget server, vcpkg uploads the library on this server.

Now, my colleague, which use exactly the same "toolchain" as I do, also installs the library with vcpkg. vcpkg downloads the library from the Nuget server since it (correctly) determines that the "toolchains" (the hash) are the same. However, my colleague now has a library with a RPATH that doesn't exist on its machine. Moreover, the library is unlikely to work because it won't found its dependencies (e.g. `libcurl.so`).

**Environment**
- OS: Ubuntu 20.04.1 LTS
- Compiler: clang version 10.0.0-4ubuntu1

**To Reproduce**
1. `./vcpkg install aws-sdk-cpp:x64-linux-dynamic --overlay-triplets=../vcpkg-overlays/triplets`
2. `objdump -x installed/x64-linux-dynamic/lib/libaws-cpp-sdk-core.so | grep PATH`
3. A `RUNPATH` particular to your machine is observed.

**Expected behavior**
`RUNPATH` should be `$ORIGIN`, which is relocatable. I'll submit a pull request in a few minutes that fix the issue.

**Comment by PhoebeHui** [comment]
@klalumiere, thanks for reporting this issue! and very appreciate for your contribution!
