### ISSUE TITLE
[openni2:x64-windows] build failure

### ISSUE THREAD

**Issue by eltonhcchan** [microsoft/vcpkg#14550]
**Host Environment**
OS: Windows 10  Home Version 2004 OS build 19041.630
Package: openni2:x64-windows
Vcpkg version: 2020.11.09-nohash

**To Reproduce**
.\vcpkg install openni2:x64-windows

**Failure logs** 
c:\src\vcpkg>vcpkg install openni2:x64-windows
Computing installation plan...
The following packages will be built and installed:
    openni2[core]:x64-windows
Detecting compiler hash for triplet x64-windows...
Starting package 1/1: openni2:x64-windows
Building package openni2[core]:x64-windows...
Could not locate cached archive: 
CMake Error at ports/openni2/portfile.cmake:7 (message):
  Could not find <cor.h>.  Ensure the NETFXSDK is installed.
Call Stack (most recent call first):
  scripts/ports.cmake:136 (include)

Error: Building package openni2:x64-windows failed with: BUILD_FAILED

**log files.**

[stdout-x64-windows.log](https://github.com/microsoft/vcpkg/files/5532845/stdout-x64-windows.log)
[x64-windows.vcpkg_abi_info.txt](https://github.com/microsoft/vcpkg/files/5532846/x64-windows.vcpkg_abi_info.txt)

**Additional information**
.NET Framework 4.8 or a later update has already installed.

**Comment by StarGate-One** [comment]
When you installed the Windows SDK, did you include the NETFXSDK as the file "cor.h" included within?
It would be found in `C:\Program Files (x86)\Windows Kits\NETFXSDK\<dot-net-version>\Include\um`.

**Comment by JonLiu1993** [comment]
@eltonhcchan ,Thanks for posting this issue. If you install successfully, you will find your cor.h file in this path:C:\Program Files (x86)\Windows Kits\NETFXSDK\<dot-net-version>\Include\um, if you don’t find it, you can reinstall and try

**Comment by eltonhcchan** [comment]
it works after I reinstall NETFSDK. thx
