### ISSUE TITLE
set default triplet per vcpkg-root

### ISSUE THREAD

**Issue by playgithub** [microsoft/vcpkg#14553]
## Demand
Suppose there are 2 vckpkg-roots
* `~/vcpkg/x86-windows` (for 32bit)
* `~/vcpkg/x64-windows` (for 64bit)

needs to set default triplet for each vcpkg-root

**Comment by JackBoosY** [comment]
Hmm... I think it's not needed. Can you explain why you need that?

**Comment by playgithub** [comment]
Generally saving settings in vcpkg-root is better to saving setting in environment variables.
Practically e.g. I have an old pc that run Windows 32-bit, slow to build on it, I'll build 32-bit application on much faster computer that runs 64-bit Windows. In this case,  two vcpkg-root's is a good choice. Without proper default `triplet `, I may have to check/set/switch `triplet ` frequently, just not convienient. I think convinience for small things is important.

**Comment by JackBoosY** [comment]
@strega-nil What do you think about.
I think we can completely use the binary cache function to solve this issue.

**Comment by strega-nil** [comment]
The way we're planning on doing this is with `vcpkg-configuration.json`. It's not necessarily what we'd recommend, but it is a thing we will eventually support.
