### ISSUE TITLE
[vcpkg] build failure

### ISSUE THREAD

**Issue by istanggsh** [microsoft/vcpkg#14569]
**Host Environment**
- OS: Ubuntu 20.04
- Compiler: GNU 9.3.0

**To Reproduce**
`./bootstrap-vcpkg.sh`

**Failure logs** 
![屏幕截图 2020-11-15 003215](https://user-images.githubusercontent.com/65331757/99152028-51152b80-26da-11eb-88ad-ca10854a2d13.png)

**Comment by StarGate-One** [comment]
It looks like a `kill` command was issued to the g++ compiler PID?
As far as I know, others are more than welcome to correct me, vcpkg does not issue a `kill` command, so either some other process or someone issued a kill command to kill it. Maybe a virus scanner?

**Comment by istanggsh** [comment]
> It looks like a `kill` command was issued to the g++ compiler PID?
> As far as I know, others are more than welcome to correct me, vcpkg does not issue a `kill` command, so either some other process or someone issued a kill command to kill it. Maybe a virus scanner?

Thanks. It looks like the system kill the compiler PID. I run the virtual machine on vmware and the memory I allocate is too small, so the compilation always fails. I reallocate a big memory, and it succeeds.
