### ISSUE TITLE
[libwebp] Do not enable SSE4 support with /arch:AVX 

### ISSUE THREAD

**Issue by 0xECEAD** [microsoft/vcpkg#14568]
The library source, in file [cmake/cpu.cmake:36](https://github.com/webmproject/libwebp/blob/master/cmake/cpu.cmake) sets **/arch:AVX** compiler flag to enable SSE4 support. It even has a comment stating it is intentional.
This 'ofcause enables the AVX instruction-set, resulting in a executable that will not run on a CPU without AVX.
e.q. function WebPDecode will crash with exception 0xC000001d 'Illegal Instruction' on a Intel Atom x5 CPU (build details in my case: VS2019, Release, x86, Cross-Compiled, both Win10).

The library should be clear about which instruction-set it is using, SSE4 or AVX.

As a workaround I propose an addition to the vcpkg-patch file: '0007-fix-arm-build.patch' that removes the '/arch:AVX' option.

```
diff --git a/cmake/cpu.cmake b/cmake/cpu.cmake
index da9a42a4..cb7a050d 100644
--- a/cmake/cpu.cmake
+++ b/cmake/cpu.cmake
@@ -33,7 +33,7 @@ set(WEBP_SIMD_FILE_EXTENSIONS
     "_sse41.c;_sse2.c;_mips32.c;_mips_dsp_r2.c;_neon.c;_msa.c")
 if(MSVC)
   # MSVC does not have a SSE4 flag but AVX support implies SSE4 support.
-  set(SIMD_ENABLE_FLAGS "/arch:AVX;/arch:SSE2;;;;")
+  set(SIMD_ENABLE_FLAGS "/arch:SSE2;;;;;")
   set(SIMD_DISABLE_FLAGS)
 else()
   set(SIMD_ENABLE_FLAGS
@@ -73,7 +73,7 @@ foreach(I_SIMD RANGE ${WEBP_SIMD_FLAGS_RANGE})
     set(CMAKE_REQUIRED_FLAGS ${SIMD_COMPILE_FLAG})
     webp_check_compiler_flag(${WEBP_SIMD_FLAG} ${WEBP_ENABLE_SIMD})
   else()
-    if(MSVC)
+    if(MSVC AND NOT (CMAKE_GENERATOR_PLATFORM MATCHES "^ARM"))
       list(GET SIMD_ENABLE_FLAGS ${I_SIMD} SIMD_COMPILE_FLAG)
     else()
       set(SIMD_COMPILE_FLAG " ")
```

**Comment by JonLiu1993** [comment]
@0xECEAD ,Thanks for posting this issue，Have you tested your ideas? Is it feasible?

**Comment by 0xECEAD** [comment]
The proposed patch works. 

It still uses the SSE4 instructions, because they are included as intrinsics, (no harm done).
The compiler no longer emits AVX instructions, for code-optimization, only SSE2.

**Comment by JonLiu1993** [comment]
@0xECEAD ,I tested your suggestion but there seems to be a problem
````
-- Performing Test WEBP_HAVE_FLAG_MSA
-- Performing Test WEBP_HAVE_FLAG_MSA - Failed
CMake Error at cmake/cpu.cmake:72 (list):
  list index: 5 out of range (-5, 4)
Call Stack (most recent call first):
  cmake/deps.cmake:138 (include)
  CMakeLists.txt:51 (include)


-- Performing Test WEBP_HAVE_FLAG_MSA
-- Performing Test WEBP_HAVE_FLAG_MSA - Failed
-- Configuring incomplete, errors occurred!
````

**Comment by 0xECEAD** [comment]
Hi JonLiu, 
you are right, the patch file is not correct, sorry.
I attached a new version.
and 'successful' build log.

[0007-fix-arm-build.patch.txt](https://github.com/microsoft/vcpkg/files/5554037/0007-fix-arm-build.patch.txt)

[stdout-x64-windows.log](https://github.com/microsoft/vcpkg/files/5554038/stdout-x64-windows.log)

Best regards, 
Enceladus

**Comment by JonLiu1993** [comment]
Hi @0xECEAD ,Is your vcpkg the latest version? The patch 0007-fix-arm-build.patch already exists in the latest vcpkg, but in the patch, only _if (MSVC)_ is changed to _if (MSVC AND NOT (CMAKE_GENERATOR_PLATFORM MATCHES "^ARM"))_, I will follow the patch you provided I re-made the previous patch, but it still doesn't work, and the problem is the same. Can you check again? The following is the patch I remade and the architecture log Thanks
````
diff --git a/cmake/cpu.cmake b/cmake/cpu.cmake
index da9a42a..cb7a050 100644
--- a/cmake/cpu.cmake
+++ b/cmake/cpu.cmake
@@ -33,7 +33,7 @@ set(WEBP_SIMD_FILE_EXTENSIONS
     "_sse41.c;_sse2.c;_mips32.c;_mips_dsp_r2.c;_neon.c;_msa.c")
 if(MSVC)
   # MSVC does not have a SSE4 flag but AVX support implies SSE4 support.
-  set(SIMD_ENABLE_FLAGS "/arch:AVX;/arch:SSE2;;;;")
+  set(SIMD_ENABLE_FLAGS "/arch:SSE2;;;;")
   set(SIMD_DISABLE_FLAGS)
 else()
   set(SIMD_ENABLE_FLAGS
@@ -73,7 +73,7 @@ foreach(I_SIMD RANGE ${WEBP_SIMD_FLAGS_RANGE})
     set(CMAKE_REQUIRED_FLAGS ${SIMD_COMPILE_FLAG})
     webp_check_compiler_flag(${WEBP_SIMD_FLAG} ${WEBP_ENABLE_SIMD})
   else()
-    if(MSVC)
+    if(MSVC AND NOT (CMAKE_GENERATOR_PLATFORM MATCHES "^ARM"))
       list(GET SIMD_ENABLE_FLAGS ${I_SIMD} SIMD_COMPILE_FLAG)
     else()
       set(SIMD_COMPILE_FLAG " ")
````
[config-x86-windows-out.log](https://github.com/microsoft/vcpkg/files/5564698/config-x86-windows-out.log)

**Comment by 0xECEAD** [comment]
Hi JonLiu, thank you for testing/trying.
I just did a clean checkout, bootstrap-build vcpkg. Then I overwrite the `0007-fix-arm-build.patch` with my file `0007-fix-arm-build.patch.txt`. And install the libwebp-library. That all works without errors on my machine. See [console-my-patch.log](https://github.com/microsoft/vcpkg/files/5565029/console-my-patch.log).


When I do the same with your patch, it fails with error: `corrupt patch at line 22`. See [console-your-patch.log](https://github.com/microsoft/vcpkg/files/5565028/console-your-patch.log). 
I don't know why but it always seems complicated to patch a patch-file.. :-)


SideNote: I found that the number of items in the SIMD_ENABLE_FLAGS should stay the same, so you need to keep the number of `;` separators (5x). Your patch misses one (although that is not the cause of this error).

Best Regards, 
Enceladus

**Comment by mvfpoa** [comment]
this fix seems to have broken the libwebp:x86-windows-static build
https://github.com/microsoft/vcpkg/issues/32940

**Comment by dg0yt** [comment]
Note https://github.com/microsoft/vcpkg/pull/21644#discussion_r1284053075.
