### ISSUE TITLE
[libarchive[bzip2,core,libxml2,lz4,lzma,lzo,openssl,zstd]:x64-windows and x64-linux] build failure after PR #14535

### ISSUE THREAD

**Issue by StarGate-One** [microsoft/vcpkg#14567]
**Host Environment**
- OS: Both Windows and Linux
         [Microsoft Windows [Version 10.0.19042.630]]
         [openSUSE Leap 15.2] on WSL2 and Hyper-V
- Compiler: 
   - Windows
      - Visual Studio 2017 Version: 15.9.29  VS Tools Version: 14.16.27023
      - Visual Studio 2019 Version: 16.8.1  VS Tools Version: 14.28.29333
    - OpenSUSE
      - gcc (SUSE Linux) 9.3.1 20200406 [revision 6db837a5288ee3ca5ec504fbd5a765817e556ac2]

**To Reproduce**
- Windows
1. `git pull` with commit https://github.com/microsoft/vcpkg/commit/5dc53211caedebf4387d590155ed53ee44161f10 PR #14535 `[libarchive] Re-fix dependencies, combine patches` 
2. `.\bootstrap-vcpkg.bat -verbose -disableMetrics -win64 -withVSPath 'C:\Program Files (x86)\Microsoft Visual Studio\<2017 or 2019>\Community\' `
3. `.\vcpkg.exe remove libarchive:x64-windows`
4. `rmdir /q /s .\buildtrees\libarchive`
5. `->.\vcpkg.exe --debug --printmetrics install --x-use-aria2 --recurse --keep-going --editable   libarchive[bzip2,core,libxml2,lz4,lzma,lzo,openssl,zstd]:x64-windows`
6. Afterwards deleted and recreated vcpkg instances with same results.
- OpenSUSE
1. same as one above
2. `./bootstrap-vcpkg.sh --disableMetrics`
3. `./vcpkg remove libarchive:x64-linux`
4. `rm -rf ./buildtrees/libarchive`
5. `vcpkg --debug --printmetrics install --x-use-aria2 --recurse --keep-going --editable   libarchive[bzip2,core,libxml2,lz4,lzma,lzo,openssl,zstd]:x64-linux`

**Failure logs** 
- Cut and past the appropriate build messages from the console output.
  - Windows
`Warning: passed either --printmetrics or --no-printmetrics, but metrics are disabled.`
`[DEBUG] Feature flag 'binarycaching' = off`
`[DEBUG] Feature flag 'manifests' = off`
`[DEBUG] Feature flag 'compilertracking' = off`
`[DEBUG] Feature flag 'registries' = off`
`[DEBUG] Feature flag 'versions' unset`
`[DEBUG] Using vcpkg-root: D:\vcpkg_x64\vs2017\test`
`[DEBUG] Using installed-root: D:\vcpkg_x64\vs2017\test\installed`
`[DEBUG] Using buildtrees-root: D:\vcpkg_x64\vs2017\test\buildtrees`
`[DEBUG] Using downloads-root: D:\vcpkg_x64\vs2017\test\downloads`
`[DEBUG] Using packages-root: D:\vcpkg_x64\vs2017\test\packages`
`[DEBUG] Using scripts-root: D:\vcpkg_x64\vs2017\test\scripts`
`[DEBUG] Default binary cache path is: E:\vcpkg_x64\vs2017\test\vcpkg\archives`
`Computing installation plan...`
`[DEBUG] Found path: C:\Program Files\CMake\bin\cmake.exe`
`[DEBUG] Found path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe`
`[DEBUG] CreateProcessW("C:\Program Files\CMake\bin\cmake.exe" --version)`
`[DEBUG] cmd_execute_and_stream_data() returned 0 after    26009 us`
`[DEBUG] CreateProcessW("C:\Program Files\CMake\bin\cmake.exe" -DVCPKG_ROOT_DIR=D:/vcpkg_x64/vs2017/test -DPACKAGES_DIR=D:/vcpkg_x64/vs2017/test/packages -DBUILDTREES_DIR=D:/vcpkg_x64/vs2017/test/buildtrees -D_VCPKG_INSTALLED_DIR=D:/vcpkg_x64/vs2017/test/installed -DDOWNLOADS=D:/vcpkg_x64/vs2017/test/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "D:\vcpkg_x64\vs2017\test\buildtrees\0.vcpkg_tags.cmake")`
`[DEBUG] cmd_execute_and_stream_data() returned 0 after    15602 us`
`The following packages will be built and installed:`
`    libarchive[bzip2,core,libxml2,lz4,lzma,lzo,openssl,zstd]:x64-windows`
`[DEBUG] CreateProcessW("C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -all -prerelease -legacy -products * -format xml)`
`[DEBUG] cmd_execute_and_stream_data() returned 0 after   149396 us`
`[DEBUG] Binary caching for package libarchive:x64-windows is disabled due to --editable`
`Starting package 1/1: libarchive:x64-windows`
`Building package libarchive[bzip2,core,libxml2,lz4,lzma,lzo,openssl,zstd]:x64-windows...`
`[DEBUG] Found path: C:\Program Files\Git\cmd\git.exe`
`[DEBUG] CreateProcessW("C:\Program Files\Git\cmd\git.exe" --version)`
`[DEBUG] cmd_execute_and_stream_data() returned 0 after    18542 us`
`[DEBUG] Found path: C:\Program Files\PowerShell\7\pwsh.exe`
`[DEBUG] CreateProcessW("C:\Program Files\PowerShell\7\pwsh.exe" --version)`
`[DEBUG] cmd_execute_and_stream_data() returned 0 after   133966 us`
`[DEBUG] CreateProcessW(cmd /c ""C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" -vcvars_ver=14.1 amd64   2>&1 <NUL" & echo cdARN4xjKueKScMy9C6H& set)`
`[DEBUG] cmd_execute_and_stream_data() returned 0 after   637278 us`
`[DEBUG] CreateProcessW("C:\Program Files\CMake\bin\cmake.exe" -DPORT=libarchive -DCURRENT_PORT_DIR=D:/vcpkg_x64/vs2017/test/ports/libarchive -DVCPKG_USE_HEAD_VERSION=0 -D_VCPKG_NO_DOWNLOADS=0 -D_VCPKG_DOWNLOAD_TOOL=ARIA2 -D_VCPKG_EDITABLE=1 "-DFEATURES=bzip2;core;libxml2;lz4;lzma;lzo;openssl;zstd" "-DALL_FEATURES=bzip2;libxml2;lz4;lzma;lzo;openssl;zstd;" -DCMD=BUILD -DTARGET_TRIPLET=x64-windows "-DTARGET_TRIPLET_FILE=D:\vcpkg_x64\vs2017\test\triplets\x64-windows.cmake" -DVCPKG_PLATFORM_TOOLSET=v141 -DDOWNLOADS=D:/vcpkg_x64/vs2017/test/downloads -DVCPKG_CONCURRENCY=8 "-DGIT=C:/Program Files/Git/cmd/git.exe" -DVCPKG_ROOT_DIR=D:/vcpkg_x64/vs2017/test -DPACKAGES_DIR=D:/vcpkg_x64/vs2017/test/packages -DBUILDTREES_DIR=D:/vcpkg_x64/vs2017/test/buildtrees -D_VCPKG_INSTALLED_DIR=D:/vcpkg_x64/vs2017/test/installed -DDOWNLOADS=D:/vcpkg_x64/vs2017/test/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "D:\vcpkg_x64\vs2017\test\scripts\ports.cmake")`
`-- Using cached D:/vcpkg_x64/vs2017/test/downloads/libarchive-libarchive-fc6563f5130d8a7ee1fc27c0e55baef35119f26c.tar.gz`
`-- Extracting source D:/vcpkg_x64/vs2017/test/downloads/libarchive-libarchive-fc6563f5130d8a7ee1fc27c0e55baef35119f26c.tar.gz`
`-- Applying patch fix-buildsystem.patch`
`-- Applying patch fix-dependencies.patch`
`-- Applying patch fix-cpu-set.patch`
`-- Applying patch disable-warnings.patch`
`-- Using source at D:/vcpkg_x64/vs2017/test/buildtrees/libarchive/src/f35119f26c-c97ae2f4c9`
`-- Configuring x64-windows`
`-- Building x64-windows-dbg`
`CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:142 (message):`
`    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j8`
`    Working Directory: D:/vcpkg_x64/vs2017/test/buildtrees/libarchive/x64-windows-dbg`
`    See logs for more information:`
**`      D:\vcpkg_x64\vs2017\test\buildtrees\libarchive\install-x64-windows-dbg-out.log`**
` `
`Call Stack (most recent call first):`
`  scripts/cmake/vcpkg_build_cmake.cmake:93 (vcpkg_execute_build_process)`
`  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)`
`  ports/libarchive/portfile.cmake:66 (vcpkg_install_cmake)`
`  scripts/ports.cmake:136 (include)`
` `
` `
`[DEBUG] cmd_execute_and_stream_data() returned 1 after 54226868 us`
`Error: Building package libarchive:x64-windows failed with: BUILD_FAILED`
`Elapsed time for package libarchive:x64-windows: 55.03 s`
` `
`Total elapsed time: 55.18 s`
` `
`RESULTS`
`    libarchive:x64-windows: BUILD_FAILED: 55.03 s`
` `
`SUMMARY`
`    SUCCEEDED: 0`
`    BUILD_FAILED: 1`
`    POST_BUILD_CHECKS_FAILED: 0`
`    FILE_CONFLICTS: 0`
`    CASCADED_DUE_TO_MISSING_DEPENDENCIES: 0`
`    EXCLUDED: 0`
`[DEBUG] d:\vcpkg_x64\vs2017\test\toolsrc\src\vcpkg\install.cpp(991)`
`[DEBUG] Exiting after 55253696 us (55252954 us)`

- OpenSUSE
`[DEBUG] Feature flag 'binarycaching' = off`
`[DEBUG] Feature flag 'manifests' unset`
`[DEBUG] Feature flag 'compilertracking' unset`
`[DEBUG] Feature flag 'registries' unset`
`[DEBUG] Feature flag 'versions' unset`
`[DEBUG] Using vcpkg-root: /home/<username>/git/vcpkg`
`[DEBUG] Using installed-root: /home/<username>/git/vcpkg/installed`
`[DEBUG] Using buildtrees-root: /home/<username>/git/vcpkg/buildtrees`
`[DEBUG] Using downloads-root: /home/<username>/git/vcpkg/downloads`
`[DEBUG] Using packages-root: /home/<username>/git/vcpkg/packages`
`[DEBUG] Using scripts-root: /home/<username>/git/vcpkg/scripts`
`[DEBUG] Default binary cache path is: /home/<username>/.cache/vcpkg/archives`
`Computing installation plan...`
`[DEBUG] Found path: /usr/bin/cmake`
`[DEBUG] popen("/home/<username>/git/vcpkg/downloads/tools/cmake-3.18.4-linux/cmake-3.18.4-Linux-x86_64/bin/cmake" --version 2>&1)`
`[DEBUG] cmd_execute_and_stream_data() returned 0 after     1888 us`
`[DEBUG] popen(/home/<username>/git/vcpkg/downloads/tools/cmake-3.18.4-linux/cmake-3.18.4-Linux-x86_64/bin/cmake -DVCPKG_ROOT_DIR=/home/<username>/git/vcpkg -DPACKAGES_DIR=/home/<username>/git/vcpkg/packages -DBUILDTREES_DIR=/home/<username>/git/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=/home/<username>/git/vcpkg/installed -DDOWNLOADS=/home/<username>/git/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P /home/<username>/git/vcpkg/buildtrees/0.vcpkg_tags.cmake 2>&1)`
`[DEBUG] cmd_execute_and_stream_data() returned 0 after     2069 us`
`The following packages will be built and installed:`
`    libarchive[bzip2,core,libxml2,lz4,lzma,lzo,openssl,zstd]:x64-linux`
`[DEBUG] Binary caching for package libarchive:x64-linux is disabled due to --editable`
`Starting package 1/1: libarchive:x64-linux`
`Building package libarchive[bzip2,core,libxml2,lz4,lzma,lzo,openssl,zstd]:x64-linux...`
`[DEBUG] Found path: /usr/bin/ninja`
`[DEBUG] popen("/home/<username>/git/vcpkg/downloads/tools/ninja-1.10.1-linux/ninja" --version 2>&1)`
`[DEBUG] cmd_execute_and_stream_data() returned 0 after     2052 us`
`[DEBUG] Found path: /usr/bin/git`
`[DEBUG] popen("/usr/bin/git" --version 2>&1)`
`[DEBUG] cmd_execute_and_stream_data() returned 0 after     1831 us`
`[DEBUG] popen(/home/<username>/git/vcpkg/downloads/tools/cmake-3.18.4-linux/cmake-3.18.4-Linux-x86_64/bin/cmake -DPORT=libarchive -DCURRENT_PORT_DIR=/home/<username>/git/vcpkg/ports/libarchive -DVCPKG_USE_HEAD_VERSION=0 -D_VCPKG_NO_DOWNLOADS=0 -D_VCPKG_DOWNLOAD_TOOL=ARIA2 -D_VCPKG_EDITABLE=1 "-DFEATURES=bzip2;core;libxml2;lz4;lzma;lzo;openssl;zstd" "-DALL_FEATURES=bzip2;libxml2;lz4;lzma;lzo;openssl;zstd;" -DCMD=BUILD -DTARGET_TRIPLET=x64-linux -DTARGET_TRIPLET_FILE=/home/<username>/git/vcpkg/triplets/x64-linux.cmake -DVCPKG_PLATFORM_TOOLSET=external -DDOWNLOADS=/home/<username>/git/vcpkg/downloads -DVCPKG_CONCURRENCY=5 -DGIT=/usr/bin/git -DVCPKG_ROOT_DIR=/home/<username>/git/vcpkg -DPACKAGES_DIR=/home/<username>/git/vcpkg/packages -DBUILDTREES_DIR=/home/<username>/git/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=/home/<username>/git/vcpkg/installed -DDOWNLOADS=/home/<username>/git/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P /home/<username>/git/vcpkg/scripts/ports.cmake 2>&1)`
`-- Using cached /home/<username>/git/vcpkg/downloads/libarchive-libarchive-fc6563f5130d8a7ee1fc27c0e55baef35119f26c.tar.gz`
`-- Using source at /home/<username>/git/vcpkg/buildtrees/libarchive/src/f35119f26c-c97ae2f4c9`
`-- Configuring x64-linux-dbg`
`CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:106 (message):`
`    Command failed: /home/<username>/git/vcpkg/downloads/tools/cmake-3.18.4-linux/cmake-3.18.4-Linux-x86_64/bin/cmake /home/<username>/git/vcpkg/buildtrees/libarchive/src/f35119f26c-c97ae2f4c9 -DENABLE_BZip2=ON -DENABLE_LIBXML2=ON -DENABLE_LZ4=ON -DENABLE_LZMA=ON -DENABLE_LZO=ON -DENABLE_OPENSSL=ON -DENABLE_ZSTD=ON -DPOSIX_REGEX_LIB=NONE -DENABLE_ZLIB=ON -DENABLE_PCREPOSIX=OFF -DENABLE_NETTLE=OFF -DENABLE_EXPAT=OFF -DENABLE_LibGCC=OFF -DENABLE_CNG=OFF -DENABLE_TAR=OFF -DENABLE_CPIO=OFF -DENABLE_CAT=OFF -DENABLE_XATTR=OFF -DENABLE_ACL=OFF -DENABLE_ICONV=OFF -DENABLE_TEST=OFF -DENABLE_WERROR=OFF -DCMAKE_MAKE_PROGRAM=/home/<username>/git/vcpkg/downloads/tools/ninja-1.10.1-linux/ninja -DCMAKE_SYSTEM_NAME=Linux -DBUILD_SHARED_LIBS=OFF -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/home/<username>/git/vcpkg/scripts/toolchains/linux.cmake -DVCPKG_TARGET_TRIPLET=x64-linux -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=external -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=/home/<username>/git/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_LINKER_FLAGS_RELEASE= -DVCPKG_LINKER_FLAGS_DEBUG= -DVCPKG_TARGET_ARCHITECTURE=x64 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -D_VCPKG_ROOT_DIR=/home/<username>/git/vcpkg -D_VCPKG_INSTALLED_DIR=/home/<username>/git/vcpkg/installed -DVCPKG_MANIFEST_INSTALL=OFF -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/home/<username>/git/vcpkg/packages/libarchive_x64-linux/debug`
`    Working Directory: /home/<username>/git/vcpkg/buildtrees/libarchive/x64-linux-dbg`
`    Error code: 1`
`    See logs for more information:`
`      /home/<username>/git/vcpkg/buildtrees/libarchive/config-x64-linux-dbg-out.log`
`      /home/<username>/git/vcpkg/buildtrees/libarchive/config-x64-linux-dbg-err.log`
` `
`Call Stack (most recent call first):`
`  scripts/cmake/vcpkg_configure_cmake.cmake:321 (vcpkg_execute_required_process)`
`  ports/libarchive/portfile.cmake:46 (vcpkg_configure_cmake)`
`  scripts/ports.cmake:136 (include)`
` `
` `
`[DEBUG] cmd_execute_and_stream_data() returned 256 after 38894439 us`
`Error: Building package libarchive:x64-linux failed with: BUILD_FAILED`
`Elapsed time for package libarchive:x64-linux: 39.03 s`
` `
`Total elapsed time: 39.03 s`
` `
`RESULTS`
`    libarchive:x64-linux: BUILD_FAILED: 39.03 s`
` `
`SUMMARY`
`    SUCCEEDED: 0`
`    BUILD_FAILED: 1`
`    POST_BUILD_CHECKS_FAILED: 0`
`    FILE_CONFLICTS: 0`
`    CASCADED_DUE_TO_MISSING_DEPENDENCIES: 0`
`    EXCLUDED: 0`
`[DEBUG] ../src/vcpkg/install.cpp(991)`
`[`
`  {`
`    "ver": 1,`
`    "name": "Microsoft.ApplicationInsights.Event",`
`    "time": "2020-11-14T00:47:16.0Z",`
`    "sampleRate": 100.000000,`
`    "seq": "0:0",`
`    "iKey": "b4e88960-4393-4dd9-ab8e-97e8fe6d7603",`
`    "flags": 0,`
`    "tags": {`
`      "ai.device.os": "Other",`
`      "ai.device.osVersion": "Linux-unknown",`
`      "ai.session.id": "99f99adb-0d04-401e-98df-2237e314f46b",`
`      "ai.user.id": "51736edc-caf9-464b-85ef-1eb10736c9ab",`
`      "ai.user.accountAcquisitionDate": "2020-06-10T00:33:58.0Z"`
`    },`
`    "data": {`
`      "baseType": "EventData",`
`      "baseData": {`
`        "ver": 2,`
`        "name": "commandline_test7",`
`        "properties": {`
`          "version": "2020.11.12-unknownhash",`
`          "command": "install",`
`          "installplan_1": "9c2b7b2d88381ee218182c8cc0b6accd27697f0b1a81ff8607990e9cad55b7e2",`
`          "error": "build failed",`
`          "build_error": "libarchive:x64-linux",`
`          "buildnames_1": [`
`            "9c2b7b2d88381ee218182c8cc0b6accd27697f0b1a81ff8607990e9cad55b7e2:[09e61bc3a2412f610b1784706d9ed9e8b4d9eb29e8d0e415e888b4172beae8d3,0d45f5fd462b8c70bffb10021ac1bcff3f58f29b1faf7568595095427d42812c,e35d532a1c2504cded399563df0f302954d701b8f4bdb36264113b171547aa1b,d846fc5d0425258664cb17e29c4e6db4f40ae1bcb6a68399747cf6ed81157887,3b5d113903aa0d10ca41e52484d41cfdb06fc3452087ddac736650bcea7b1203,523b065f90e7c5aff8f9b64d62abcc29313fdbc46e7b525091267d223526e609,41ffca929b95c49690ab8815d1d1a134a5bcdd86bde407c0f46b90eabf556b05,242daddb4ed79680ac790d9f9c01ca43c8fc3a16f1af137f7cb090c086988782]"`
`          ],`
`          "buildtimes": [`
`            39028925.200000`
`          ]`
`        },`
`        "measurements": {`
`          "elapsed_us": 39097927.400000`
`        },`
`        "feature-flags": {`
`          "binarycaching": false,`
`          "compilertracking": true,`
`          "registries": false,`
`          "versions": false,`
`          "manifests": false`
`        }`
`      }`
`    }`
`  }`
`]`
` `
`[DEBUG] Exiting after 39098960 us (39097927 us)`

- Please attach any additional failure logs mentioned in the console output.
   - Windows
      - VS 2017 
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/5539799/install-x64-windows-dbg-out.log)

      - VS 2019 
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/5539801/install-x64-windows-dbg-out.log)

   - OpenSUSE 
[CMakeError.log](https://github.com/microsoft/vcpkg/files/5539941/CMakeError.log)
[CMakeOutput.log](https://github.com/microsoft/vcpkg/files/5539942/CMakeOutput.log)
[config-x64-linux-dbg-err.log](https://github.com/microsoft/vcpkg/files/5539943/config-x64-linux-dbg-err.log)
[config-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/5539944/config-x64-linux-dbg-out.log)

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.
Logs contain the following message:
- Windows
**`D:\vcpkg_x64\<vs-version>\test\buildtrees\libarchive\x64-windows-dbg\config.h(59): fatal error C1189: #error:  No 64-bit integer type was found.`** where version is either VS 2017 or VS 2019
- OpenSUSE - I have no idea where to start on this, but I included the files mentioned in console output and the CMakeError and CMakeOutput logs mentioned in the config-x64-linux-dbg-out.log

**Comment by StarGate-One** [comment]
Update:
- I created a vanilla clone of vcpkg from microsoft/vcpkg on both OpenSUSE and Windows to do this testing, thus eliminating any customizations done locally.
- I did some testing with triplets tested: x86-windows x86-windows-static x64-windows x64-windows-static x64-linux:
   - All these triplets install properly with core feature only
`->.\vcpkg.exe --debug --printmetrics install --x-use-aria2 --recurse --keep-going --editable libarchive[core]:<triplet>`
   - All these triplets fail with any other features in addition to core:
`->.\vcpkg.exe --debug --printmetrics install --x-use-aria2 --recurse --keep-going --editable libarchive[bzip2,core,libxml2,lz4,lzma,lzo,openssl,zstd]:<triplet>`

- I did some comparing between before and after the commit mentioned above:
  - The source before the commit extracts to `src\f35119f26c-ff047c825d` where after the commit is extracted to `src\f35119f26c-c97ae2f4c9` even though the same source file is downloaded and extracted. I am at a loss on why the extracted source directories/folders would be different?
  - The CMakeLists.txt files shows code dealing with the feature are somewhat different on how the feature ports are found, configured and used. I am not a CMake expert and unsure if this code implementation changes are the cause of the failures?

- In the meantime as a work around I have removed this commit from my production vcpkg instances.

**Comment by sfhacker** [comment]
There are dozens of issues about libarchive!
Perhaps it is a regression or buggy VS compiler or ... broken environment?

Just built it from source and haven't come across any of the issues reported here.

![image](https://user-images.githubusercontent.com/25817529/99157062-19c66f00-271a-11eb-9b2a-3cb6d00646c6.png)

**Comment by Matioupi** [comment]
The failure is also appearing int the CI automatic checks for most pull requests at time.
It seems to get down to int64 type mapping not being done properly and the compilation fails because it hit 

```
#if !defined(HAVE_INT64_T)
#error No 64-bit integer type was found.
#endif
```

on config.h file

**Comment by Matioupi** [comment]
it looks like CHECK_TYPE_SIZE macro is failing for all types... event 32 bytes types. I'm not getting a clue why it is so

**Comment by Matioupi** [comment]
The attached CMakeFileLists.txt solves the issue but I guess the fix is quite ugly.

I had to moved the 

#
# Check for integer types
#
#

section right after INCLUDE(CheckTypeSize)
I also add to move 
CHECK_FUNCTION_EXISTS_GLIBC(_get_timezone HAVE__GET_TIMEZONE)
earlier in the file
and modify the target lib for zstd according to static or shared builds

I have no real clue about what is happening.
I suspect strange things with push / pop variable states and cached variables.

[CMakeLists.txt](https://github.com/microsoft/vcpkg/files/5542243/CMakeLists.txt)

**Comment by linquize** [comment]
In `C:\vcpkg\buildtrees\libarchive\x64-windows-dbg\CMakeFiles\CMakeError.log`,  some of the errors are

```
src.c(2): fatal error C1083: Cannot open include file: 'dirent.h': No such file or directory
src.c(2): fatal error C1083: Cannot open include file: 'sys/ndir.h': No such file or directory
src.c(2): fatal error C1083: Cannot open include file: 'ndir.h': No such file or directory
src.c(2): fatal error C1083: Cannot open include file: 'sys/dir.h': No such file or directory
HAVE_ACL_LIBACL_H.c(3): fatal error C1083: Cannot open include file: 'acl/libacl.h': No such file or directory
HAVE_ATTR_XATTR_H.c(3): fatal error C1083: Cannot open include file: 'attr/xattr.h': No such file or directory
HAVE_COPYFILE_H.c(4): fatal error C1083: Cannot open include file: 'copyfile.h': No such file or directory
HAVE_DLFCN_H.c(5): fatal error C1083: Cannot open include file: 'dlfcn.h': No such file or directory
HAVE_EXT2FS_EXT2_FS_H.c(6): fatal error C1083: Cannot open include file: 'ext2fs/ext2_fs.h': No such file or directory
src.c(1): fatal error C1083: Cannot open include file: 'sys/ioctl.h': No such file or directory
HAVE_GRP_H.c(7): fatal error C1083: Cannot open include file: 'grp.h': No such file or directory
CheckTypeSize\ID_T.c(29): error C2065: 'id_t': undeclared identifier

LINK : fatal error LNK1104: cannot open file 'libzstd.lib'

ninja: build stopped: subcommand failed.
```

**Comment by sfhacker** [comment]
@linquize Are you on Windows or Linux?

I wonder where 'ndir.h' file comes from? I am unable to find in my Windows SDK folder.

I have also enabled zstd.

![image](https://user-images.githubusercontent.com/25817529/99185059-6f8f2b80-279b-11eb-9616-dc34793bbdea.png)

**Comment by Matioupi** [comment]
I just proposed a PR to fix the issue : https://github.com/microsoft/vcpkg/pull/14579

**Comment by StarGate-One** [comment]
I can confirm **PR #14579 [libarchive] regression fix** corrects the ports mentioned in this issue.
Thank you very much @Matioupi 😊😊👍

**Comment by JackBoosY** [comment]
Ops, sorry.

**Comment by JackBoosY** [comment]
I'm very interested in the invalidation of `CHECK_TYPE_SIZE`. My patch removed `CMAKE_PUSH_CHECK_STATE` and `CMAKE_POP_CHECK_STATE` simultaneously, so there should be no state leakage problems.

**Comment by JackBoosY** [comment]
I know, from the `CMakeError.log`: `LINK : fatal error LNK1104: cannot open file 'libzstd.lib'`.
This caused this issue.

**Comment by StarGate-One** [comment]
Thank you everyone.
@JackBoosY @strega-nil - I do not see how anyone did anything incorrectly. The patch did make it through the CI pipeline (I checked to see if the pipeline just did libarchive or libarchive with all features and all features were selected) so I do not know why it would not work locally...
It is just one of those things.
Everyone do not get discouraged by it, use it as a learning experience. 👍👍👍
