### ISSUE TITLE
[New Port Request] <Pangolin>

### ISSUE THREAD

**Issue by chatyan** [microsoft/vcpkg#14573]
Library name: Pangolin

Library description: Pangolin is a lightweight portable rapid development library for managing OpenGL display / interaction and abstracting video input. At its heart is a simple OpenGl viewport manager which can help to modularise 3D visualisation without adding to its complexity, and offers an advanced but intuitive 3D navigation handler. Pangolin also provides a mechanism for manipulating program variables through config files and ui integration, and has a flexible real-time plotter for visualising graphical data.

The ethos of Pangolin is to reduce the boilerplate code that normally gets written to visualise and interact with (typically image and 3D based) systems, without compromising performance. It also enables write-once code for a number of platforms, currently including Windows, Linux, OSX, Android and IOS.

Source repository URL: https://github.com/stevenlovegrove/Pangolin

**Comment by NancyLi1013** [comment]
Hi @chatyan 

Thanks for posting this request.

`Pangolin `has been added to vcpkg now. 

`https://github.com/microsoft/vcpkg/tree/master/ports/pangolin`

The repository URL is the same as the one that you provided above.

So I think this issue can be closed. Please let me know if you have other concerns about this port.

Thanks.

**Comment by NancyLi1013** [comment]
Closing this issue since `Pangolin ` has been added and there is no response.
