### ISSUE TITLE
vcpkg_from_github lack of documentation

### ISSUE THREAD

**Issue by FabienPean** [microsoft/vcpkg#1457]
**EDIT**
By chance, my problem is explained in issue #1206. From my point of view, the documentation is not sufficient and/or confusing. Personally, on repository where the master is the stable branch without any tag, it would seem natural to use the HEAD by default and fall back to the specified commit if it did not work. Anyway this behavior should be explained in detail in the documentation to avoid any surprise.

**ORIGINAL**
When attempting to create a package and its portfile, I wanted to use the common function
` vcpkg_from_github `

The repository I want to pull from does not have reference or tag for stable version, therefore requiring a head build. Using
```
vcpkg_from_github(   
    OUT_SOURCE_PATH SOURCE_PATH   
    REPO kmammou/v-hacd   
    HEAD_REF master   
)
```

The functions crashes at line 98 of vcpkg_from_github.cmake because the cmake function makes use of the variable VCPKG_USE_HEAD_VERSION not reported in the documentation (and not found with the search box):
https://vcpkg.readthedocs.io/en/latest/maintainers/vcpkg_from_github/

Either it is a problem of documentation and the user must set VCPKG_USE_HEAD_VERSION to true beforehand in the portfile, or the function must be fixed.

**Comment by jasjuang** [comment]
See #1382, you can do `REF <commit-number>` if that repo doesn't have any release.
