### ISSUE TITLE
Any way to build on one machine, and use on another

### ISSUE THREAD

**Issue by playgithub** [microsoft/vcpkg#14584]
Building takes a lot of disk space.
Can I build on one machine, and use the binaries in vcpkg on another machine.

BTW, after successful `vcpkg install`, are the intermediate built files like `.obj` files useful for incremental building later.

Thanks

**Comment by PhoebeHui** [comment]
@playgithub, yes, please reference 
https://github.com/microsoft/vcpkg/blob/master/docs/users/binarycaching.md
https://github.com/microsoft/vcpkg/blob/master/docs/specifications/binarycaching.md

The intermediate built files doesn't need after the port installed, all required files have move to ./installed folder.
