### ISSUE TITLE
vcpkg can install both the versions of a library.

### ISSUE THREAD

**Issue by jack17529** [microsoft/vcpkg#1458]
From vcpkg one should be able to install both the stable version and also the developing version of a library.

**Comment by PhoebeHui** [comment]
@jack17529, thanks for posting this! 

VCPKG install stable version by default, and you can use --head option(./vcpkg install xxx --head ) to install latest revision of the port, or change the revision to the commits that you want to install. So I guess we can close this issue, please reopen it if it still be an problem for you.
