### ISSUE TITLE
[nlohmann-json] build failure

### ISSUE THREAD

**Issue by swq123459** [microsoft/vcpkg#14585]
**Host Environment**
- OS: [Windows]
- Compiler: vs2019

**To Reproduce**
`./vcpkg install nlohmann-json`

**Failure logs** 
❯ .\vcpkg.exe install nlohmann-json
Computing installation plan...
The following packages will be built and installed:
    nlohmann-json[core]:x86-windows
Detecting compiler hash for triplet x86-windows...
Starting package 1/1: nlohmann-json:x86-windows
Building package nlohmann-json[core]:x86-windows...
Could not locate cached archive: C:\Users\swq123459\AppData\Local\vcpkg\archives\4d\4d07ec985f14497ac5568b931071e290aaf0768c.zip
-- Downloading https://github.com/nlohmann/json/raw/v3.9.1/CMakeLists.txt...
-- Downloading https://github.com/nlohmann/json/raw/v3.9.1/CMakeLists.txt... Failed. Status: 6;"Couldn't resolve host name"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:182 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  ports/nlohmann-json/portfile.cmake:7 (vcpkg_download_distfile)
  ports/nlohmann-json/portfile.cmake:16 (download_src)
  scripts/ports.cmake:135 (include)

**Additional context**

**Comment by JonLiu1993** [comment]
@swq123459 ,Thanks for posting this issue,you've set the HTTPS_PROXY? I believe that curl will use the HTTP_PROXY  and HTTPS_PROXY environment variable when downloading an https:// link like the one above.

**Comment by swq123459** [comment]
- I don't modify the HTTPS_PROXY  setting
- When i download nlohmann-json-v3.9.1.zip to VCPKG_PATH/downloads to perform ".\vcpkg.exe install nlohmann-json", it alse fail with follow:

  .\vcpkg.exe install nlohmann-json
Computing installation plan...
The following packages will be built and installed:
    nlohmann-json[core]:x86-windows
Detecting compiler hash for triplet x86-windows...
Starting package 1/1: nlohmann-json:x86-windows
Building package nlohmann-json[core]:x86-windows...
Could not locate cached archive: C:\Users\swq123459\AppData\Local\vcpkg\archives\4d\4d07ec985f14497ac5568b931071e290aaf0768c.zip
-- Downloading https://github.com/nlohmann/json/raw/v3.9.1/CMakeLists.txt...
-- Downloading https://github.com/nlohmann/json/raw/v3.9.1/CMakeLists.txt... Failed. Status: 6;"Couldn't resolve host name"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:182 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  ports/nlohmann-json/portfile.cmake:7 (vcpkg_download_distfile)
  ports/nlohmann-json/portfile.cmake:16 (download_src)
  scripts/ports.cmake:135 (include)

**Comment by JackBoosY** [comment]
We provide two workaround:


- use a proxy.
- Download [this file](https://github.com/microsoft/vcpkg/files/5564031/Downloads.zip) manually and unzip it to _VCPKG_ROOT_, then rerun install command. You should make sure the path is _VCPKG_ROOT/Downloads/nlohmann-json-v3.9.1/nlohmann_json.natvis_ etc., and make sure your vcpkg is latest.

**Comment by swq123459** [comment]
this work for me
