### ISSUE TITLE
How to approach libraries not natively supporting dynamic build

### ISSUE THREAD

**Issue by laserallan** [microsoft/vcpkg#1459]
I'm working on a port for a library that builds static by default and has no cmake setting for making it build dll's. What is the preferred approach for those libraries, patch them to build dll's or just provide the pull request building static libraries only?

**Comment by atkawa7** [comment]
@laserallan I think you can PR just static build or just dynamic depending on what the library supports using `VCPKG_LIBRARY_LINKAGE` in your portfile

**Comment by bagong** [comment]
I am aware of two cases, where the opposite is the case: dynamic library linkage works, static fails/is not supported. In one case (qt5) an attempt to build static is aborted:
```
if(VCPKG_LIBRARY_LINKAGE STREQUAL static)
    message(FATAL_ERROR "Qt5 doesn't currently support static builds. Please use a dynamic triplet instead.")
endif()
```
In the second (ffmpeg), "fake" dynamic libraries are built to the folders in the static triplet:
```
if(VCPKG_LIBRARY_LINKAGE STREQUAL "static")
    message(STATUS "Building as static libraries not currently supported. Building as DLLs instead.")
    set(VCPKG_LIBRARY_LINKAGE "dynamic")
endif()
```
The second approach has the advantage that a build expecting ffmpeg libraries in the static folder can still succeed, but it may be considered unclean, of course ;)

**Comment by laserallan** [comment]
Cool, it's a pretty small library with zero dependencies so I think the second approach is preferred. It will work but it will be linked statically.

**Comment by muemart** [comment]
Does the file explicitly not support dll's, or is it just hardcoded to static? Quite a few ports patch the buildsystems to support building dlls, if it isn't too much trouble. For libraries using CMake, you can use the [WINDOWS_EXPORT_ALL_SYMBOLS](https://cmake.org/cmake/help/v3.9/prop_tgt/WINDOWS_EXPORT_ALL_SYMBOLS.html#prop_tgt:WINDOWS_EXPORT_ALL_SYMBOLS) property to export all symbols, if they lack the __declspecs.

**Comment by laserallan** [comment]
That sounds interesting. It's hard coded I'll see how nasty a patch would look introducing that. If it's not too bad it might be a better approach and I'll see if I can get them to adopt it for the library.

**Comment by JackBoosY** [comment]
Hi @laserallan , good question!

You can use the following code to automatically switch to a static build and add it below  `include(vcpkg_common_functions)` in **portfile.cmake**:
> vcpkg_check_linkage(ONLY_STATIC_LIBRARY)

Thanks.
