### ISSUE TITLE
[New Port Request] <uhd>

### ISSUE THREAD

**Issue by HarvaneetKaur** [microsoft/vcpkg#14590]
Library name: uhd

Library description:
ettus uhd 
Source repository URL: https://github.com/EttusResearch/uhd

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by JackBoosY** [comment]
I think this port can be built by cmake: https://files.ettus.com/manual/page_build_guide.html

**Comment by HarvaneetKaur** [comment]
yeah I tried it .. it worked but then I got the issue with the vcpkg_check_features .. actually this ports need boost for building and when I provide boost via vcpkg_check_features it shows the below issue :-
unknown feature: boost

This is how my portfile.cmake looks like :- 

vcpkg_download_distfile(ARCHIVE
    URLS "https://github.com/EttusResearch/uhd/archive/master.zip"
    FILENAME "master.zip"
    SHA512 f9bd76658000e6411ada087c4ea784424ad76cf7b1723fd4491389abbcedf3ec1400957ab44b098c9f97b1869f98c73e9eb9ecc3c16ea210997307586f767a8c
)
vcpkg_extract_source_archive_ex(
    OUT_SOURCE_PATH /home/hkaur/Git_Repos/vcpkg/buildtrees/uhd/src/master-304908991b.clean/host
    ARCHIVE ${ARCHIVE}
)
string(COMPARE EQUAL "${VCPKG_LIBRARY_LINKAGE}" "static" BUILD_STATIC)
string(COMPARE EQUAL "${VCPKG_LIBRARY_LINKAGE}" "dynamic" BUILD_SHARED)

vcpkg_check_features(
    OUT_FEATURE_OPTIONS FEATURE_OPTIONS
    boost WITH_LIBBOOST-ALL-DEV
    )
message (STATUS "TESTING UHD ......")
vcpkg_configure_cmake(
    message (STATUS /home/hkaur/Git_Repos/vcpkg/buildtrees/uhd/src/master-304908991b.clean/host)
    SOURCE_PATH /home/hkaur/Git_Repos/vcpkg/buildtrees/uhd/src/master-304908991b.clean/host
    PREFER_NINJA # Disable this option if project cannot be built with Ninja
)
vcpkg_install_cmake()

# # Handle copyright
file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/uhd RENAME copyright)

**Comment by JackBoosY** [comment]
The `vcpkg_check_features(key value)` provides `${FEATURE_OPTIONS}` is `-Dvalue=ON` or `-Dvalue=OFF`, so you need to write other code like:
```cmake
if ("boost" IN_LIST FEATURES)
    set(BOOST_OPTS -ALL-DEV)
endif()
...
vcpkg_configure_cmake(
    ...
    OPTIONS
        ${BOOST_OPTS}
)
```

**Comment by HarvaneetKaur** [comment]
Now its saying this 
the Cmakelists.txt is inside the host and have given that path but now its showing the below error .

CMake Error: The source directory "/vcpkg/buildtrees/uhd/src/master-304908991b.clean/host" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.

**Comment by JackBoosY** [comment]
@HarvaneetKaur Could you please open a PR? I will help you on that PR.

**Comment by HarvaneetKaur** [comment]
Hi @JackBoosY ,
What does this line means..
[sanity check] The serialized binary paragraph was different from the original binary paragraph.
I am getting this after the installation of uhd .. is it some kind of error !!

**Comment by JackBoosY** [comment]
Seems like your `CONTROL` or `vcpkg.js` has something wrong.

**Comment by HarvaneetKaur** [comment]
Thank you @JackBoosY ,
Installed the uhd port successfully .. :)

**Comment by HarvaneetKaur** [comment]
Hi @JackBoosY ,
I want to install libboost-all-dev in uhd .. when I do apt-get install inside vcpkg for libboost-all-dev .. then uhd is installed inside vcpkg .. but when i Only do ./vcpkg install boost and the do ./vckg install uhd .. then uhd shows missing boost .. 

Have given the build-depends : boost-devel, boost-chrono, boost-context, boost-conversion, boost-crc, boost-date-time, boost-filesystem, boost-multi-index, boost-program-options, boost-regex, boost-system, boost-thread, boost-smart-ptr in the control file for uhd ...

Can you help me with this

**Comment by JackBoosY** [comment]
After installing the boost component, you need to implement `find_package()`/ `find_path` / `target_include_directories` / `target_link_libraries` in `CMakeLists.txt` according to the console output.
Example:
```pwsh
The package boost-crc:x86-windows is header only and can be used from CMake via:

    find_path(BOOST_CRC_INCLUDE_DIRS "boost/crc.hpp")
    target_include_directories(main PRIVATE ${BOOST_CRC_INCLUDE_DIRS})

```

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
