### ISSUE TITLE
Error: Building package v8:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by LooShes** [microsoft/vcpkg#14593]
**Host Environment**
- OS: Windows
- Compiler: MSVC

**To Reproduce**
`./vcpkg install v8`

C:\Users\lusyv\OneDrive\Documents\Elevation\projects\vcpkg>vcpkg install v8
Computing installation plan...
The following packages will be built and installed:
    v8[core]:x86-windows
Detecting compiler hash for triplet x86-windows...
Starting package 1/1: v8:x86-windows
Building package v8[core]:x86-windows...
Could not locate cached archive: C:\Users\lusyv\AppData\Local\vcpkg\archives\97\97139b1ff7a12f6b0915e05b1798ffbeaf7851ad.zip
-- Using msys root at C:/Users/lusyv/OneDrive/Documents/Elevation/projects/vcpkg/downloads/tools/msys2/b1b4e6089ab84adb
-- Using cached C:/Users/lusyv/OneDrive/Documents/Elevation/projects/vcpkg/downloads/v8-7565e93eb72cea4268028fc20186d415c22b1cff.tar.gz
-- Cleaning sources at C:/Users/lusyv/OneDrive/Documents/Elevation/projects/vcpkg/buildtrees/v8/src/15c22b1cff-c34597ce8b.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/lusyv/OneDrive/Documents/Elevation/projects/vcpkg/downloads/v8-7565e93eb72cea4268028fc20186d415c22b1cff.tar.gz
-- Applying patch C:/Users/lusyv/OneDrive/Documents/Elevation/projects/vcpkg/ports/v8/v8.patch
-- Using source at C:/Users/lusyv/OneDrive/Documents/Elevation/projects/vcpkg/buildtrees/v8/src/15c22b1cff-c34597ce8b.clean
-- Fetching submodules
-- Generating v8 build files. Please wait...
-- Generating build (x86-windows-dbg)...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:106 (message):
    Command failed: C:/Users/lusyv/OneDrive/Documents/Elevation/projects/vcpkg/downloads/tools/gn/qUkAhy9J0P7c5racy-9wB6AHNK_btS18im8S06_ehhwC/gn.exe gen C:/Users/lusyv/OneDrive/Documents/Elevation/projects/vcpkg/buildtrees/v8/x86-windows-dbg "--args=is_component_build=true target_cpu="x86" v8_monolithic=false v8_use_external_startup_data=true use_sysroot=false is_clang=false use_custom_libcxx=false v8_enable_verify_heap=false icu_use_data_file=false is_debug=true enable_iterator_debugging=true pkg_config_libdir="/cygdrive/c/Users/lusyv/OneDrive/Documents/Elevation/projects/vcpkg/installed/x86-windows/debug/lib/pkgconfig""
    Working Directory: C:/Users/lusyv/OneDrive/Documents/Elevation/projects/vcpkg/buildtrees/v8/src/15c22b1cff-c34597ce8b.clean
    Error code: 1
    See logs for more information:
      C:\Users\lusyv\OneDrive\Documents\Elevation\projects\vcpkg\buildtrees\v8\generate-x86-windows-dbg-out.log
      C:\Users\lusyv\OneDrive\Documents\Elevation\projects\vcpkg\buildtrees\v8\generate-x86-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_gn.cmake:45 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_configure_gn.cmake:53 (generate)
  ports/v8/portfile.cmake:145 (vcpkg_configure_gn)
  scripts/ports.cmake:136 (include)

Error: Building package v8:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: v8:x86-windows
  Vcpkg version: 2020.11.12-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by StarGate-One** [comment]
Please attach the log files for further review to aid in troubleshooting:
`C:\Users\lusyv\OneDrive\Documents\Elevation\projects\vcpkg\buildtrees\v8\generate-x86-windows-dbg-out.log`
`C:\Users\lusyv\OneDrive\Documents\Elevation\projects\vcpkg\buildtrees\v8\generate-x86-windows-dbg-err.log`

**Comment by Mempler** [comment]
Pretty sure you're missing the `Windows SDK 10.0.19041.0` package from VS Installer.
Install that and try again

**Comment by JackBoosY** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
