### ISSUE TITLE
Vcpkg Contributors Survey

### ISSUE THREAD

**Issue by ras0219-msft** [microsoft/vcpkg#14599]
We’ve been working as a team and a community for more than 4 years on vcpkg. Thanks to everyone who has contributed! As part of our ongoing efforts to improve the open source project experience, we’ve created a survey to better understand your individual experience of participating and contributing in this project.

We would appreciate your feedback so we can work to address shortcomings and missed opportunities. You have the option to supply contact details or send your reply anonymously.

https://www.surveymonkey.com/r/92RLF7R?Source=Microsoft/vcpkg

**Comment by danmosemsft** [comment]
@ras0219-msft @JackBoosY this survey is closed, please close this issue.
