### ISSUE TITLE
What is the binary executed in AppData?

### ISSUE THREAD

**Issue by ohhmm** [microsoft/vcpkg#14595]
![image](https://user-images.githubusercontent.com/190779/99269151-b4b06d80-282e-11eb-869b-03ddc3923921.png)

**Comment by StarGate-One** [comment]
This is where vcpkg stores default hash information about the port binaries created during installation of the port.
See https://vcpkg.readthedocs.io/en/latest/specifications/binarycaching/

**Comment by NancyLi1013** [comment]
Hi @ohhmm 

Thanks for posting this issue.

Do you mean what is the binary stored in \AppData\Local\vcpkg\archives_ folder?

For binary cache, these references might be helpful to you.

https://github.com/microsoft/vcpkg/blob/master/docs/users/binarycaching.md
https://github.com/microsoft/vcpkg/blob/master/docs/specifications/binarycaching.md

Sorry, I don't understand what's you want to express from the attachment. Please make it clear on what's problem you happened.

Thanks.

**Comment by NancyLi1013** [comment]
@ohhmm 
Please let me know if you still have other concerns about this issue.

**Comment by ohhmm** [comment]
![Uploading 99788509...]

**Comment by ohhmm** [comment]
It looks like vcpkg downloaded another binary version of vcpkg and tried to execute it. If it is so then downloaded binary should be signed.

**Comment by NancyLi1013** [comment]
Sorry, it seems that the attachment is not provided successfully.

**Comment by ohhmm** [comment]
Hi @NancyLi1013,

The question is why if it expected for vcpkg to download other vcpkg exe and launch it?

Thanks,
Serg

**Comment by NancyLi1013** [comment]
Hi @ohhmm 

Could you please try to update vcpkg to the latest version and rebuild this? Please also use PowerShell instead of cmd to build.

If you still have the same issue, please make it more clear to describe the problem you meet or provide the steps to reproduce.

**Comment by NancyLi1013** [comment]
Closing this issue for no response.

Please feel free to reopen this if it is still a problem for you.

**Comment by ohhmm** [comment]
> Hi @NancyLi1013,
> 
> The question is why if it expected for vcpkg to download other vcpkg exe and launch it?
> 
> Thanks,
> Serg

Please, do answer this before closing.
I am blocked to use the vcpkg.
I need to know was it intended vcpkg algorithm or malicious activity.

**Comment by StarGate-One** [comment]
- The binaries are **_NOT_ executed**, they are stored there until they are needed again by vcpkg. 
- The binaries are a **_copy of the binaries_** made of the **ports** one has installed with vcpkg.

>For binary cache, these references might be helpful to you.
>https://github.com/microsoft/vcpkg/blob/master/docs/users/binarycaching.md
>https://github.com/microsoft/vcpkg/blob/master/docs/specifications/binarycaching.md

>This is where vcpkg stores default hash information about the port binaries created during installation of the port.
>See https://vcpkg.readthedocs.io/en/latest/specifications/binarycaching/

>From [vcpkg-root]
>.\vcpkg.exe help binarycaching

NOTE: The PC has other issues if the binaries in `%LOCALAPPDATA%\vcpkg\archives` or `%APPDATA%\vcpkg\archives` directories are being executed.
To permanently disable binarycaching:
1. Set the environment variable `VCPKG_FEATURE_FLAGS=-binarycaching`
2. To delete the cached files run `.\vcpkg.exe install [port] [port] ... --binarycaching=clear`

________________________________________________________________________________________________________
I hope the meaning does not get lost in the google translation...

- Бінарні файли **_НЕ_ виконуються**, вони зберігаються там, поки вони знову не знадобляться vcpkg.
- Бінарні файли - це **_копія бінарних файлів_**, виготовлених із **портів**, який один встановив за допомогою vcpkg.

> Для двійкового кешу ці посилання можуть бути вам корисними.
> https://github.com/microsoft/vcpkg/blob/master/docs/users/binarycaching.md
> https://github.com/microsoft/vcpkg/blob/master/docs/specifications/binarycaching.md

> Тут vcpkg зберігає хеш-інформацію за замовчуванням про двійкові файли портів, створені під час встановлення порту.
> Див. Https://vcpkg.readthedocs.io/en/latest/specifications/binarycaching/

> Від [vcpkg-root]
>.\vcpkg.exe help binarycaching

ПРИМІТКА. У ПК виникають інші проблеми, якщо виконуються двійкові файли в каталогах `%LOCALAPPDATA%\vcpkg\ archives` або `%APPDATA%\vcpkg\archive`.
Щоб назавжди вимкнути бінарне кешування:
1. Встановіть змінну середовища `VCPKG_FEATURE_FLAGS = -binarycaching`
2. Щоб видалити кешовані файли, запустіть `. \ Vcpkg.exe встановіть [порт] [порт] ... --binarycaching = clear`
- Binarni fayly ** _ NE_ vykonuyutʹsya **, vony zberihayutʹsya tam, poky vony znovu ne znadoblyatʹsya vcpkg.
- Binarni fayly - tse **_kopiya binarnykh fayliv_**, vyhotovlenykh iz **portiv**, yakyy odyn vstanovyv za dopomohoyu vcpkg.

> Dlya dviykovoho keshu tsi posylannya mozhutʹ buty vam korysnymy.
> https://github.com/microsoft/vcpkg/blob/master/docs/users/binarycaching.md
> https://github.com/microsoft/vcpkg/blob/master/docs/specifications/binarycaching.md

> Tut vcpkg zberihaye khesh-informatsiyu za zamovchuvannyam pro dviykovi fayly portiv, stvoreni pid chas vstanovlennya portu.
> Dyv. Https://vcpkg.readthedocs.io/en/latest/specifications/binarycaching/

> Vid [vcpkg-root]
>. \ vcpkg.exe dopomozhe binarnomu keshuvannyu

PRYMITKA. U PK vynykayutʹ inshi problemy, yakshcho vykonuyutʹsya dviykovi fayly v katalohakh `%LOCALAPPDATA%\vcpkg\archives` abo `%APPDATA%\vcpkg\archive`.
Shchob nazavzhdy vymknuty binarne keshuvannya:
1. Vstanovitʹ zminnu seredovyshcha `VCPKG_FEATURE_FLAGS=-binarycaching`
2. Shchob vydalyty keshovani fayly, zapustitʹ `. \vcpkg.exe install [port] [port] ... --binarycaching=clear`

**Comment by ohhmm** [comment]
Hi,

Thanks for your detailed response.
Any idea how this happened then?
![image](https://user-images.githubusercontent.com/190779/105452132-713b0b00-5c86-11eb-858e-46f13fbff43d.jpeg)
How to prevent this?
I am blocked to use vcpkg, yet.

Thanks,
Serg

**Comment by NancyLi1013** [comment]
Since Avast detected vcpkg.exe as an virus, which prevents you to run vcpkg.

You need to follow the guideline to add vcpkg.exe exclusion or disable Avast.

**Comment by ohhmm** [comment]
@NancyLi1013,

Please, notice that path on the hint. You informed me that vcpkg.exe does not execute self from that temporary directory, right?
I didn't launch it from there.
May this be its vulnerability?
Would anyone wish me to archive and upload it somewhere to take a closer look?

@Thanks,
Serg

**Comment by ohhmm** [comment]
Hi,

I guess I must ask you to forward this to your security team or to your manager/mentor, please.

Thanks,
Serg

**Comment by JackBoosY** [comment]
@ohhmm vcpkg will **never** run itself in anywhere.

**Comment by ohhmm** [comment]
Thanks @JackBoosY,

That's what I expected.
This is why I shared this information.
Anyone wants to make vcpkg more protected?
Maybe, installer with signed binary?
Bundle it in a Visual Studio installer?

Thanks,
Serg

**Comment by JackBoosY** [comment]
@ohhmm We are realizing the release version of vcpkg (with signature), see #15474.
