### ISSUE TITLE
[tesseract] build failure

### ISSUE THREAD

**Issue by nefton** [microsoft/vcpkg#14601]
**Host Environment**
- OS: [Windows 10 x64]
- Compiler: vc14

**To Reproduce**
`./vcpkg install tesseract:x64-windows-static`

**Failure logs** 
Starting package 3/9: zlib:x64-windows-static
Building package zlib[core]:x64-windows-static...
Could not locate cached archive: C:\Users\Maxim\AppData\Local\vcpkg\archives\ba\baca8a7dc018b7e5e2c2c90ee19b87e2b0d028ab.zip
-- Downloading http://www.zlib.net/zlib-1.2.11.tar.gz...
-- Extracting source D:/PROJECTS/2020-11-17 vcpkg/vcpkg-master/downloads/zlib1211.tar.gz
-- Applying patch cmake_dont_build_more_than_needed.patch
-- Applying patch 0001-Prevent-invalid-inclusions-when-HAVE_-is-set-to-0.patch
-- Applying patch add_debug_postfix_on_mingw.patch
-- Using source at D:/PROJECTS/2020-11-17 vcpkg/vcpkg-master/buildtrees/zlib/src/1.2.11-63309e48e5.clean
-- Configuring x64-windows-static
-- Building x64-windows-static-dbg
-- Building x64-windows-static-rel
-- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz...
-- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst...
-- Using msys root at D:/PROJECTS/2020-11-17 vcpkg/vcpkg-master/downloads/tools/msys2/c809757c94447846
-- Fixing pkgconfig file: D:/PROJECTS/2020-11-17 vcpkg/vcpkg-master/packages/zlib_x64-windows-static/lib/pkgconfig/zlib.pc
-- CHECK_LIB_zlib_RELEASE:CHECK_LIB_zlib_RELEASE-NOTFOUND
CMake Error at scripts/cmake/vcpkg_fixup_pkgconfig.cmake:233 (message):
  Library "zlib" was not found! If it is a system library use the
  SYSTEM_LIBRARIES parameter for the vcpkg_fixup_pkgconfig call! Otherwise,
  correct the *.pc file
Call Stack (most recent call first):
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:299 (vcpkg_fixup_pkgconfig_check_files)
  ports/zlib/portfile.cmake:48 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:136 (include)

Error: Building package zlib:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zlib:x64-windows-static
  Vcpkg version: 2020.11.12-nohash

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/13103, this issue would be fixed by PR https://github.com/microsoft/vcpkg/pull/13126
