### ISSUE TITLE
How to get the path of "vcpkg.cmake" in portfile.cmake

### ISSUE THREAD

**Issue by playgithub** [microsoft/vcpkg#14602]
In `protfile.cmake`
```
vcpkg_configure_cmake(
    ...
    OPTIONS -DCMAKE_TOOLCHAIN_FILE=/path/to/vcpkg/scripts/buildsystems/vcpkg.cmake
    ....
)
```

**Comment by JonLiu1993** [comment]
@playgithub ,Thanks for posting this issue, You can use the command _**./vcpkg integrate install**_ to view the specific location of your own vcpkg.cmake
![Capture](https://user-images.githubusercontent.com/63675417/99352044-e4b64a00-28dc-11eb-8b88-c41d33ce8f25.PNG)

**Comment by playgithub** [comment]
When PR, it should be found dynamically

**Comment by JackBoosY** [comment]
The vcpkg tool chain can be automatically passed to `vcpkg_configure_cmake`. So you don't need to do that manually.

**Comment by playgithub** [comment]
Thanks
