### ISSUE TITLE
[New Port Request] Yojimbo

### ISSUE THREAD

**Issue by SK83RJOSH** [microsoft/vcpkg#14604]
**Library name:**
yojimbo

**Library description:**
yojimbo is a network library for client/server games written in C++.

**Source repository URL:**
https://github.com/networkprotocol/yojimbo
https://github.com/networkprotocol/netcode
https://github.com/networkprotocol/reliable

**Anything else that is useful to know when adding:**
- Static library
- Premake5 project
- Comprised of three Git Repos, with the latter two used as submodules
- Dependent on libsodium and mbedtls
- Supports building on Linux and Windows

A CMake port was started here, but unfortunately stalled out:
https://github.com/networkprotocol/yojimbo/issues/133

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by McKillroy** [comment]
There's a starter port as PR for Yojimbo here:
https://github.com/networkprotocol/yojimbo/pull/161
If we iron out the wrinkles it might work later, I think.
