### ISSUE TITLE
How do I compile qt5 with built in third party libraries

### ISSUE THREAD

**Issue by dev-gb** [microsoft/vcpkg#14608]
I would like to build QT5 .dlls without revealing third party libraries. 

For example, the Official QT5 Core Dll has no additional dependencies. 
The one built with VCPKG still needs dlls like zlib, zstd etc. 

Is it possible to build QT without any dependencies to third party libraries?

**Comment by Neumann-A** [comment]
General answer
> custom triplet with per port customization of VCPKG_LIBRARY_LINKAGE.
https://vcpkg.readthedocs.io/en/latest/users/triplets/#per-port-customization

Build everything Qt depens on statically and build Qt itself dynamically.

**Comment by dev-gb** [comment]
I created my own tripplet.

```
set(VCPKG_TARGET_ARCHITECTURE x86)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE static)
if(${PORT} MATCHES "qt5")
    set(VCPKG_LIBRARY_LINKAGE dynamic)
    set(VCPKG_CRT_LINKAGE dynamic)
endif()
```

The Build fails as soon as vcpk tries to build QT. 
Tried to modify the QT portfile, which did not help me either.

**Comment by Neumann-A** [comment]
You cannot have different CRT linkage in one triplet.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
