### ISSUE TITLE
[libpq] build failure x86-windows x64-windows with features core,icu,nls,openssl,xml,zlib

### ISSUE THREAD

**Issue by StarGate-One** [microsoft/vcpkg#14619]
**Host Environment**
- OS: [Microsoft Windows [Version 10.0.19042.630]]
- Compiler: 
   - Visual Studio 2017 Version: 15.9.29  VS Tools Version: 14.16.27023
   - Visual Studio 2019 Version: 16.8.1  VS Tools Version: 14.28.29333

**To Reproduce**
1. `git clone git@github.com:microsoft/vcpkg.git` includes PR #11776 with commit https://github.com/microsoft/vcpkg/commit/3a26eb3dc4d684ca6c1748dccc7a15684b9e8d0a `[intl/gettext/fontconfig] update to native build system #11776` - **it may be relevant, but not sure**
2. `.\bootstrap-vcpkg.bat -verbose -disableMetrics -win64`
3. `set VCPKG_DEFAULT_TRIPLET=x64-windows`
4. `.\vcpkg.exe  install --x-use-aria2 --recurse --keep-going --editable gettext[core] icu[core] libiconv[core] liblzma[core] libpq[core,icu,nls,openssl,xml,zlib] libxml2[core] openssl[core] zlib[core]`

**Failure logs** 
- Cut and past the appropriate build messages from the console output.
>Computing installation plan...
>The following packages will be built and installed:
>    gettext[core]:x64-windows
>    icu[core]:x64-windows
>    libiconv[core]:x64-windows
>    liblzma[core]:x64-windows
>    libpq[core,icu,nls,openssl,xml,zlib]:x64-windows
>    libxml2[core]:x64-windows
>    openssl[core]:x64-windows
>    zlib[core]:x64-windows
>Starting package 1/8: libiconv:x64-windows
>Building package libiconv[core]:x64-windows...
> ...
>Elapsed time for package openssl:x64-windows: 1.308 min
>Starting package 8/8: libpq:x64-windows
>Building package libpq[core,icu,nls,openssl,xml,zlib]:x64-windows...
>-- Downloading postgresql-12.2.tar.bz2...
>-- Extracting source D:/Git/vcpkg_x64/downloads/postgresql-12.2.tar.bz2
>-- Applying patch patches/windows/install.patch
>-- Applying patch patches/windows/win_bison_flex.patch
>-- Applying patch patches/windows/openssl_exe_path.patch
>-- Applying patch patches/windows/Solution.patch
>-- Applying patch patches/windows/MSBuildProject_fix_gendef_perl.patch
>-- Applying patch patches/windows/msgfmt.patch
>-- Applying patch patches/windows/python_lib.patch
>-- Applying patch patches/linux/configure.patch
>-- Applying patch patches/windows/minimize_install.patch
>-- Using source at D:/Git/vcpkg_x64/buildtrees/libpq/src/tgresql-12-3dcd887135
>-- Copying libpq source files to D:/Git/vcpkg_x64/buildtrees/libpq/x64-windows-rel...
>-- Copying libpq source files... done
>-- Applying patch patches/windows/Solution_RELEASE.patch
>-- Applying patch patches/windows/python3_build_RELEASE.patch
>-- Patches applied!
>-- Downloading msys-gettext-0.19.8.1-1-x86_64.pkg.tar.xz...
>-- Downloading msys-libgettextpo-0.19.8.1-1-x86_64.pkg.tar.xz...
>-- Downloading msys-libasprintf-0.19.8.1-1-x86_64.pkg.tar.xz...
>-- Using msys root at D:/Git/vcpkg_x64/downloads/tools/msys2/91955029573d0bcc
>-- Building libpq x64-windows-RELEASE...
>CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:106 (message):
    Command failed: D:/Git/vcpkg_x64/downloads/tools/perl/5.30.0.1/perl/bin/perl.exe build.pl RELEASE libpq
>    Working Directory: D:/Git/vcpkg_x64/buildtrees/libpq/x64-windows-rel/src/tools/msvc 
>    Error code: 1
>    See logs for more information:
>      D:\Git\vcpkg_x64\buildtrees\libpq\build-libpq-x64-windows-RELEASE-out.log
>
>Call Stack (most recent call first):
>  ports/libpq/portfile.cmake:215 (vcpkg_execute_required_process)
>  scripts/ports.cmake:136 (include)
>
>
>Error: Building package libpq:x64-windows failed with: BUILD_FAILED
>Elapsed time for package libpq:x64-windows: 35.99 s
>
>Total elapsed time: 12.87 min
> ...
- Please attach any additional failure logs mentioned in the console output.
[build-libpq-x64-windows-RELEASE-out.log](https://github.com/microsoft/vcpkg/files/5557369/build-libpq-x64-windows-RELEASE-out.log)

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.
build-libpq-x64-windows-RELEASE-out.log Contains the follow error:
>    1>LINK : fatal error LNK1181: cannot open input file 'D:\vcpkg_x64\vs2019\prod\installed\x64-windows\lib\libintl.lib' [D:\vcpkg_x64\vs2019\prod\buildtrees\libpq\x64-windows-rel\libpq.vcxproj]

Note: x86-windows-static and x64-windows-static build fine

**Comment by JackBoosY** [comment]
cc @Neumann-A

**Comment by StarGate-One** [comment]
After some further research
- The CI pipeline shows libpq passed with the PR #11776 with features core, openssl and zlib features (which I could duplicate)
- Adding any of the features icu, nls, xml the port build fails - something with of those ports may be incorrect for dynamic windows builds now?
- The libpq dependencies are as follows:
>->vcpkg depend-info libpq[core,icu,nls,openssl,xml,zlib]
>libiconv:
>liblzma:
>zlib:
>gettext: libiconv
>icu:
>libxml2: libiconv, liblzma, zlib
>openssl:
>libpq[xml, icu, zlib, nls, openssl]: gettext, icu, libxml2, openssl, zlib

**Comment by Neumann-A** [comment]
Just the library names are wrong since the PR changed the names to the correct upstream names for windows. Just needs adjustment of the patches.
