### ISSUE TITLE
Building curl with brotli-support (curl[brotli]) does not work: libcurl does not contain brotli

### ISSUE THREAD

**Issue by dadidag** [microsoft/vcpkg#14627]
**Describe the bug**
Try to build curl[brotli,tool] does result in libcurl.dll NOT containing brotli-support

**Environment**
- OS: Windows 10, Version 1903 Build 18632.1139
- Compiler: VS2017 15.9.27

**To Reproduce**

1. ./vcpkg install --recurse curl[brotli,tool,ssh,schannel,non-http,openssl,c-ares]
2. curl -V
curl 7.73.0-DEV (Windows) libcurl/7.73.0-DEV OpenSSL/1.1.1h (Schannel) zlib/1.2.11 c-ares/1.15.0 libssh2/1.9.0_DEV
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher http https imap imaps ldap mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS HTTPS-proxy IPv6 Kerberos Largefile MultiSSL NTLM SPNEGO SSL SSPI TrackMemory libz

**Expected behavior**
brotli should be shown in feature list

**Failure logs** 
CMake Warning (dev) at C:/vcpkg/downloads/tools/cmake-3.18.4-windows/cmake-3.18.4-win32-x86/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:273 (message):
  The package name passed to `find_package_handle_standard_args` (BROTLI)
  does not match the name of the calling package (Brotli).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  CMake/FindBrotli.cmake:29 (find_package_handle_standard_args)
  C:/vcpkg/scripts/buildsystems/vcpkg.cmake:582 (_find_package)
  CMakeLists.txt:656 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

**Additional context**

**Comment by JackBoosY** [comment]
Hi @dadidag, thanks for reporting this issue!
But I can't repro this:
```
PS F:\vcpkg\packages\curl_x86-windows\tools\curl> .\curl.exe -V
curl 7.73.0-DEV (Windows) libcurl/7.73.0-DEV OpenSSL/1.1.1h (Schannel) zlib/1.2.11 brotli/1.0.9 c-ares/1.15.0 libssh2/1.9.0_DEV
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher http https imap imaps ldap mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS HTTPS-proxy IPv6 Kerberos Largefile MultiSSL NTLM SPNEGO SSL SSPI TrackMemory brotli libz
```

**Comment by dadidag** [comment]
Good morning JackBoosY,
sorry to say, the mentioned file 
> VCPKG_ROOT/buildtrees/curl/config-x86-windows-dbg.log
does not exist after the build :-(

Does "VCPKG_ROOT/buildtrees/curl/config-x86-windows-static-out.log" help? 
It contains some brotli related Cmake-warnings that possibly may help.

[config-x86-windows-static-out.log](https://github.com/microsoft/vcpkg/files/5565343/config-x86-windows-static-out.log)
If not, please let me know what I can do to help you!

Regards!

**Comment by JackBoosY** [comment]
@dadidag can you please re-install port `brotli` then rebuild curl?

Thanks.

**Comment by JackBoosY** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
