### ISSUE TITLE
How do I add the /arch:IA32 compilation option by default

### ISSUE THREAD

**Issue by fawdlstty** [microsoft/vcpkg#14621]
Many computers do not support AVX or AVX2, and the software will crash if such instructions are present in the code.But some projects, such as FFMPEG or NCNN, may require the AVX2 instruction set for acceleration.How do I specify `/arch` at compile time?

**Comment by fawdlstty** [comment]
The actual test found that not only the method starting with '_mm256_' could generate AVX instruction, but std standard library such as `std::function` could also generate AVX instruction, which caused great trouble for compatibility

**Comment by fawdlstty** [comment]
![image](https://user-images.githubusercontent.com/7323999/99498400-590eed00-29b2-11eb-992d-45666d029d62.png)
![D~A{48 AN_NJ9PIUG~O@QSN](https://user-images.githubusercontent.com/7323999/99498431-66c47280-29b2-11eb-8c67-0f97b6b3690b.png)

**Comment by PhoebeHui** [comment]
@fawdlstty 

We have VCPKG_CXX_FLAGS to set additional compiler flags to be used, we also have toolchains files to set default options,  is it what you looked for?

See 
https://github.com/microsoft/vcpkg/blob/master/scripts/toolchains/windows.cmake
https://github.com/microsoft/vcpkg/blob/0fec1340eba828e95c489796eb0c7a4330120686/docs/users/triplets.md#vcpkg_cxx_flags

**Comment by fawdlstty** [comment]
Change the VCPKG_CXX_FLAGS variable of port every time when install it?

**Comment by PhoebeHui** [comment]
I think you can add that options to toolchains at once for all ports, for specific port, you add use VCPKG_CXX_FLAGS in portfile.cmake file.

**Comment by fawdlstty** [comment]
thanks
