### ISSUE TITLE
[opencascade] OpenCASCADE_INCLUDE_DIR at wrong location

### ISSUE THREAD

**Issue by socuwn** [microsoft/vcpkg#14636]
**Host Environment**
- OS: Windows
- Compiler: Visual Studio 2019

**To Reproduce**
`./vcpkg install opencascade:x64-windows`

**Log / CMake buildtime variables**
```
-- OpenCASCADE_INCLUDE_DIR=D:/vcpkg/installed/x64-windows/share/include/opencascade
-- OpenCASCADE_INSTALL_PREFIX=D:/vcpkg/installed/x64-windows/share
```

The header files are actually located in:
`D:/vcpkg/installed/x64-windows/include/opencascade`

**Context**
When including headers from opencascade they are not found.
After listing the CMake variables at buildtime I discovered that the `OpenCASCADE_INCLUDE_DIR` points to the share folder.

Source is in file `OpenCASCADEConfig.cmake:37`
`set (OpenCASCADE_INCLUDE_DIR  "${OpenCASCADE_INSTALL_PREFIX}/include/opencascade")`

Changing it to:
 `set (OpenCASCADE_INCLUDE_DIR  "${OpenCASCADE_INSTALL_PREFIX}/../include/opencascade")`
seems to do solve this.

My suggestions:
1. Do a search and replace at the portfile
or
2. Move `/include/opencascade` to `/share/include/opencascade` after build

Please advise

**Comment by Neumann-A** [comment]
`OpenCASCADE_INSTALL_PREFIX` is wrong and needs to be fixed.

**Comment by socuwn** [comment]
Yes, I think you're right
file: `OpenCASCADEConfig.cmake:24-31`
```
get_filename_component (OpenCASCADE_INSTALL_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component (OpenCASCADE_INSTALL_PREFIX "${OpenCASCADE_INSTALL_PREFIX}" PATH)
if (OpenCASCADE_INSTALL_PREFIX MATCHES "/cmake$")
  get_filename_component (OpenCASCADE_INSTALL_PREFIX "${OpenCASCADE_INSTALL_PREFIX}" PATH)
endif()
if (OpenCASCADE_INSTALL_PREFIX MATCHES "/lib$")
  get_filename_component (OpenCASCADE_INSTALL_PREFIX "${OpenCASCADE_INSTALL_PREFIX}" PATH)
endif()
```

changing it to:
```
get_filename_component (OpenCASCADE_INSTALL_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component (OpenCASCADE_INSTALL_PREFIX "${OpenCASCADE_INSTALL_PREFIX}" PATH)
get_filename_component (OpenCASCADE_INSTALL_PREFIX "${OpenCASCADE_INSTALL_PREFIX}" PATH)
if (OpenCASCADE_INSTALL_PREFIX MATCHES "/cmake$")
  get_filename_component (OpenCASCADE_INSTALL_PREFIX "${OpenCASCADE_INSTALL_PREFIX}" PATH)
endif()
if (OpenCASCADE_INSTALL_PREFIX MATCHES "/lib$")
  get_filename_component (OpenCASCADE_INSTALL_PREFIX "${OpenCASCADE_INSTALL_PREFIX}" PATH)
endif()
```
solves it

**Comment by NancyLi1013** [comment]
Hi @socuwn 

Thanks for posting this issue and providing solution to this.

This change has been merged to master, please try to update vcpkg to the latest version and rebuild this port.

**Comment by socuwn** [comment]
This issue is back again after upgrade to OCC 7.5.0,
#15997
