### ISSUE TITLE
[HighFive] unable to link against HighFive and HDF5 at the same time

### ISSUE THREAD

**Issue by L0ric0** [microsoft/vcpkg#14631]
**Describe the bug**
I'm trying to link to the highfive and the hdf5 port at the same time. As highfive depends on hdf5 it adds the `../../vcpkg_installed/x64-linux/lib/libhdf5.a` library. Now when trying to link the hdf5 libraries `../../vcpkg_installed/x64-linux/debug/lib/libhdf5_debug.a` and `../../vcpkg_installed/x64-linux/debug/lib/libhdf5_cpp_debug.a` are added, which results in `multiple definition of ...` errors at the linking step

**Environment**
- OS: Linux Debian stable
- Compiler: gcc8

**To Reproduce**
1. ./vcpkg install highfive
2. ./vcpkg install hdf5[cpp]
3. use a CMakeList.txt like:
  ```
    find_package(HighFive CONFIG REQUIRED)
    target_link_libraries(librethfeld PRIVATE HighFive)
    find_package(HDF5 CONFIG REQUIRED)
    target_link_libraries(librethfeld PRIVATE hdf5::hdf5_cpp-static)
  ```
4. compile and see the error

**Expected behavior**
Probably that instead of `../../vcpkg_installed/x64-linux/lib/libhdf5.a` `../../vcpkg_installed/x64-linux/debug/lib/libhdf5_debug.a` is used.

**Failure logs** 
```
/usr/bin/ld: ../../vcpkg_installed/x64-linux/debug/lib/libhdf5_debug.a(H5.c.o):(.bss+0x159): multiple definition of `H5_libinit_g'; ../../vcpkg_installed/x64-linux/lib/libhdf5.a(H5.c.o):(.bss+0x1): first defined here
...
```

**Additional context**
The Linking command:
```
/usr/bin/c++     CMakeFiles/librethfeld_test.dir/src/demo_test.cpp.o CMakeFiles/librethfeld_test.dir/src/main_test.cpp.o  -o librethfeld_test -Wl,-rpath,/home/lsteinert/scripts/monstr/share/librethfeld/build/vcpkg_installed/x64-linux/debug/lib -lgtest ../../vcpkg_installed/x64-linux/debug/lib/libboost_mpi.a ../../vcpk
g_installed/x64-linux/debug/lib/libboost_serialization.a ../../vcpkg_installed/x64-linux/debug/lib/libspdlogd.a -lstdc++fs ../../liblibrethfeld.a ../../vcpkg_installed/x64-linux/lib/libhdf5.a /usr/lib/x86_64-linux-gnu/libpthread.so /usr/lib/x86_64-linux-gnu/libsz.so ../../vcpkg_installed/x64-linux/debug/lib/libz.a /us
r/lib/x86_64-linux-gnu/libdl.so -lm ../../vcpkg_installed/x64-linux/debug/lib/libboost_mpi.a ../../vcpkg_installed/x64-linux/debug/lib/libboost_serialization.a -Wl,-rpath -Wl,/home/lsteinert/scripts/monstr/share/librethfeld/build/vcpkg_installed/x64-linux/lib -Wl,--enable-new-dtags -L/home/lsteinert/scripts/monstr/sha
re/librethfeld/build/vcpkg_installed/x64-linux/lib -pthread ../../vcpkg_installed/x64-linux/debug/lib/libmpi.so ../../vcpkg_installed/x64-linux/debug/lib/libspdlogd.a -lpthread ../../vcpkg_installed/x64-linux/debug/lib/libfmtd.a ../../vcpkg_installed/x64-linux/debug/lib/libhdf5_cpp_debug.a ../../vcpkg_installed/x64-li
nux/debug/lib/libhdf5_debug.a -ldl ../../vcpkg_installed/x64-linux/lib/libz.a -ldl ../../vcpkg_installed/x64-linux/lib/libz.a ../../vcpkg_installed/x64-linux/debug/lib/libszip_debug.a -lm ../../vcpkg_installed/x64-linux/lib/libgsl.a ../../vcpkg_installed/x64-linux/lib/libgslcblas.a
```

Also if the `find_package(HDF5)` line appears before the `find_package(HighFive)` line highfive is unable to find HDF5.

**Comment by PhoebeHui** [comment]
@L0ric0, thanks for reporting this issue, I will take a look tomorrow.

**Comment by PhoebeHui** [comment]
It links to release libraries when build with debug configuration, which is wrong.

**Comment by L0ric0** [comment]
so this issue should be raised with the library developers?

**Comment by JackBoosY** [comment]
Since HighFive includes all the symbols of hdf5 in its binary during static build, the same multiple symbol errors will occur when using HighFive and hdf5 at the same time.

So we only have two solutions:
1. Do not use hdf5 in HighFive (if hdf5 is optional)
2. Use dynamic build

**Comment by L0ric0** [comment]
I have tried the second option but seem to be unable to do so when using vcpkg in manifest mode. I have set `VCPKG_LIBRARY_LINKAGE` to `dynamic` bevore specifing the toolchain file but hdf5 is still bulid as a static lib

**Comment by JackBoosY** [comment]
@L0ric0 In linux, you can create a triplet `x64-linux-dynamic`.

**Comment by PhoebeHui** [comment]
@L0ric0, sorry for my late reply.

Let me clarify this issue: 
1.	After double check the 2 ports(highfive and hdf5), and found the library and dependency correctly found and linked for debug/release configuration. So you can close the issue https://github.com/BlueBrain/HighFive/issues/392
2.	The issue here is what Jack said above https://github.com/microsoft/vcpkg/issues/14631#issuecomment-732568587
3.	You can reference https://github.com/microsoft/vcpkg/blob/master/docs/examples/overlay-triplets-linux-dynamic.md to build dynamic libraries on linux instead. Could you please try again?

**Comment by JackBoosY** [comment]
Hi @L0ric0, does this issue still bother you?

**Comment by PhoebeHui** [comment]
Please reopen this issue if it still be a problem for you.
