### ISSUE TITLE
log4cplus官方配置默认支持unicode,用vcpkg安装时默认不支持？

### ISSUE THREAD

**Issue by CodeMan-P** [microsoft/vcpkg#14643]
这样安装不支持unicode,但是官方文档里是默认--with-wchar_t-support。
`vcpkg install log4cplus`
必须添加特征：
`vcpkg install log4cplus[unicode]`

当我使用最新版本vcpkg安装log4cplus后编译工程报错，查阅文档发现上述问题，旧版vcpkg也是默认支持unicode。
还有编译完成后缺失了‘U’后缀
之前是log4cplusU.lib
现在改成了log4cplus.lib

**Comment by linquize** [comment]
This port was updated 1 month ago to add an optional feature **unicode**

https://github.com/microsoft/vcpkg/commit/b1dea7104f38eae95284470af2833b628a4847bb

**Comment by CodeMan-P** [comment]
我只是困惑添加“feature”为什么要修改默认的编译选项。😅
