### ISSUE TITLE
Difference between 2020.11 and 2020.11-1 releases

### ISSUE THREAD

**Issue by traversaro** [microsoft/vcpkg#14645]
I saw that two weeks ago two new release were tagged on vcpkg: 
* 2020.11 ( https://github.com/microsoft/vcpkg/releases/tag/2020.11 )
* 2020.11-1 ( https://github.com/microsoft/vcpkg/releases/tag/2020.11-1 )

The two releases point to some different commits, and the 2020.11-1 is not in line with the naming used for releases in the past. I was wondering what are the differences between this two releases, I searched for this info and I could not found an answer.

**Comment by NancyLi1013** [comment]
Hi @traversaro 

Thanks for posting this issue.

I think this change may answer your question. Please refer to the details.
https://github.com/microsoft/vcpkg/compare/2020.11...2020.11-1

**Comment by traversaro** [comment]
Thanks @NancyLi1013 ! So this means that `2020.11` was the original release, while `2020.11-1` is a sort of a patch release, and so the latest release is `2020.11-1`? Is the naming convention for releases documented somewhere? 
I am asking because when I render the vcpkg github repo, while `2020.11-1` is correctly listed as "Latest Release" in the left menu:
![releases_1](https://user-images.githubusercontent.com/1857049/99636631-f5350480-2a43-11eb-8c71-796aa2f319a9.PNG)

When I open the Release page (https://github.com/microsoft/vcpkg/releases), the release on the top of the list is the 2020.11 : 
![releases_2](https://user-images.githubusercontent.com/1857049/99636750-257ca300-2a44-11eb-9022-2c1da234d12a.PNG)

Even if the 2020.11-1 release is correctly indicated as Latest, even if it appears later in the list:
![releases_3](https://user-images.githubusercontent.com/1857049/99636786-3200fb80-2a44-11eb-899d-d4631f777ef8.PNG)

**Comment by PhoebeHui** [comment]
@vicroms, could you please help have a look?

**Comment by Neumann-A** [comment]
https://github.com/microsoft/vcpkg/pull/14377 has a changelog. Mainly powershell fix.

**Comment by vicroms** [comment]
Hi @traversaro, 

Indeed, `2020.11-1` is the latest release.  It patches a bug that affects non-Windows platforms.

I don't know why it appears second on the branches/releases list. But if I have to guess, I believe is because GitHub assumes that `-1` is a pre-release tag, under SemVer conventions, instead of a patch update. If that's the case, then in the future using `.##` instead of `-##` may avoid this problem.

**Comment by traversaro** [comment]
Perfect, thanks a lot!
