### ISSUE TITLE
build opencv with contrib

### ISSUE THREAD

**Issue by caiqi** [Microsoft/vcpkg#1465]
when building opencv following this https://github.com/Microsoft/vcpkg/pull/862, uncommenting the lines, it throws this error: 

vcpkg\buildtrees\opencv\src\opencv_contrib-3.2.0\modules\tracking\src\gtrUtils.hpp(7): fatal error C1083: Cannot open include file: 'opencv2/datasets/track_alov.hpp': No such file or directory (compiling source file \vcpkg\buildtrees\opencv\src\opencv_contrib-3.2.0\modules\tracking\src\gtrUtils.cpp)

Package: opencv:x86-windows
Vcpkg version: 0.0.81-5a74d30aab81e2e0d1f210117fa05e76b39b5fab

**Comment by caiqi** [comment]
Manually copying dataset/include/opencv2/dataset into tracking/include/opencv2 solves this problem.

**Comment by wangli28** [comment]
Thanks for posting this issue. Please open a new issue if this is still a problem for you.
