### ISSUE TITLE
Please update release notes for vcpkg 2020.11.01 

### ISSUE THREAD

**Issue by malidiab** [microsoft/vcpkg#14657]
The same comment was used from 2020.6 in 2020.11 for [fmt] package

**vcpkg (2020.11.01)**
`(#12312) [fmt] Update to 7.0.2 + [spdlog] Update to 1.7.0 (by @kevinlul)`

**vcpkg (2020.06.16 - 2020.7.31)**
`(#12312) [fmt] Update to 7.0.2 + [spdlog] Update to 1.7.0 (by @kevinlul)`

in 2020.11 the update should : 
`               [fmt] Update to 7.1.2 + [spdlog] Update to 1.8.0`

That last update of [fmt] from 7.0.2 to 7.1.2 is causing compilation problems in windows.

**Comment by PhoebeHui** [comment]
The correct inforrmation should be '(#14239) [fmt] Update to 7.1.0 (by @cngzhnp)' for 2020.11.01, I have upated this. 
See https://github.com/microsoft/vcpkg/releases/tag/2020.11
