### ISSUE TITLE
nvtt[core]:x86-windows build failure

### ISSUE THREAD

**Issue by stevegbarry** [microsoft/vcpkg#14663]
**Host Environment**
- OS: Windows
- Compiler: VS2019

**To Reproduce**
`./vcpkg install osgearth:x86-windows`

**Failure logs** 
Computing installation plan...
The following packages will be built and installed:
  * nvtt[core]:x86-windows
  * osg[core,plugins]:x86-windows
    osgearth[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x86-windows...
Starting package 1/3: nvtt:x86-windows
Building package nvtt[core]:x86-windows...
Could not locate cached archive: xxx\770b711b12a6eee038e2814204ad5d22e8588627.zip
CMake Error at scripts/cmake/vcpkg_fail_port_install.cmake:94 (message):
  Architecture 'x86' not supported by nvtt!

Call Stack (most recent call first):
  ports/nvtt/portfile.cmake:1 (vcpkg_fail_port_install)
  scripts/ports.cmake:136 (include)

**Additional context**
NVTT is an optional dependent for osg and, according to the osgearth folks, not required for osgearth.  However, osgearth will not build for x86 without it.  NVTT and osgearth build successfully for x64.

**Comment by NancyLi1013** [comment]
Hi @stevegbarry 

Thanks for posting this issue.

Of course, `nvtt `is an optional dependent for `osg`. But we still cannot remove it from the dependency lists for feature `plugin`.

We cannot make sure other users don't need this feature.

So we can update the dependency as `nvtt (!x86) `to solve this issue.

**Comment by NancyLi1013** [comment]
@stevegbarry 

I have updated the dependency of `osg`. Please update vcpkg to the latest version to rebuild.
