### ISSUE TITLE
[Feature Request] Enable parallel installation of libaray

### ISSUE THREAD

**Issue by MichaelSuen-thePointer** [microsoft/vcpkg#14664]
Installation of boost is very slow, each of its sub-package is downloaded and built sequentially, which cause low cpu usage and low efficiency.

command line `vcpkg install boost`

**Proposed solution**
If vcpkg can enable package level parallel installation, use `vcpkg -j8` like `make -j8` to speed up package installaziton, it would be of great help

**Comment by PhoebeHui** [comment]
@MichaelSuen-thePointer, this is already supported, see https://github.com/microsoft/vcpkg/blob/4073d297e1b07b4ccbadd053680327bd13afd3d0/ports/boost-modular-build-helper/boost-modular-build.cmake#L197

You can enable it by setting NUMBER_OF_PROCESSORS environment variable.

**Comment by MichaelSuen-thePointer** [comment]
@PhoebeHui The `-jX` option applied on `b2` will only enable parallel build of one single boost module right? The bottleneck is not build time of one single module, but the sequential installation of a tons of boost modules.

So if there are mutliple boost module to be installed, the whole process is still like:

download **m1**-> unpack **m1**-> parallel build **m1**-> install **m1**-> download **m2** -> unpack **m2** -> parallel build **m2** -> install **m2**

What I wanted is like `vcpkg` spawn multiple itself and install independent module simutanously, just like I manually started multiple vcpkg process. 

Not parallel build, but parallel download, unpack and install

**Comment by strega-nil** [comment]
Hmm, in theory this is possible; let me ask the team about it :)

**Comment by strega-nil** [comment]
Apparently this is a Really Hard Problem. @ras0219 has looked into this before, and we may look back into this in the future.
