### ISSUE TITLE
[<port name>] build failure

### ISSUE THREAD

**Issue by 1807220541** [microsoft/vcpkg#14665]
**Host Environment**
- OS: Windows10
- Compiler: Visual Studio 2019

**To Reproduce**
.\vcpkg install qt5

**Failure logs** 
Computing installation plan...
The following packages will be built and installed:
  * icu[core]:x86-windows
  * jasper[core]:x86-windows
  * libjpeg-turbo[core]:x86-windows
  * libpq[core,openssl,zlib]:x86-windows
  * libwebp[core,nearlossless,simd,unicode]:x86-windows
  * openssl[core]:x86-windows
  * openssl-windows[core]:x86-windows
  * pcre2[core]:x86-windows
    qt5[activeqt,core,declarative,essentials,imageformats,multimedia,networkauth,quickcontrols2,svg,tools]:x86-windows
  * qt5-activeqt[core]:x86-windows
  * qt5-base[core]:x86-windows
  * qt5-declarative[core]:x86-windows
  * qt5-imageformats[core]:x86-windows
  * qt5-multimedia[core]:x86-windows
  * qt5-networkauth[core]:x86-windows
  * qt5-quickcontrols2[core]:x86-windows
  * qt5-svg[core]:x86-windows
  * qt5-tools[core]:x86-windows
  * sqlite3[core]:x86-windows
  * tiff[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x86-windows...
Starting package 1/20: icu:x86-windows
Building package icu[core]:x86-windows...
Could not locate cached archive: C:\Users\MSI_NB\AppData\Local\vcpkg\archives\8e\8e6da802305edf582106b60ca2c234da5745bc05.zip
-- Using cached D:/vcpkg/downloads/icu4c-67_1-src.tgz
-- Cleaning sources at D:/vcpkg/buildtrees/icu/src/c-67_1-src-39ba50b26e.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/vcpkg/downloads/icu4c-67_1-src.tgz
-- Applying patch D:/vcpkg/ports/icu/disable-escapestr-tool.patch
-- Applying patch D:/vcpkg/ports/icu/remove-MD-from-configure.patch
-- Applying patch D:/vcpkg/ports/icu/fix_parallel_build_on_windows.patch
-- Applying patch D:/vcpkg/ports/icu/fix-extra.patch
-- Using source at D:/vcpkg/buildtrees/icu/src/c-67_1-src-39ba50b26e.clean
-- Downloading https://repo.msys2.org/msys/x86_64/libiconv-1.16-1-x86_64.pkg.tar.xz...
-- Downloading https://repo.msys2.org/msys/x86_64/libiconv-1.16-1-x86_64.pkg.tar.xz... Failed. Status: 22;"HTTP response code said error"
-- Downloading https://www2.futureware.at/~nickoe/msys2-mirror/msys/x86_64/libiconv-1.16-1-x86_64.pkg.tar.xz...
-- Downloading https://www2.futureware.at/~nickoe/msys2-mirror/msys/x86_64/libiconv-1.16-1-x86_64.pkg.tar.xz... Failed. Status: 22;"HTTP response code said error"
-- Downloading https://mirror.yandex.ru/mirrors/msys2/msys/x86_64/libiconv-1.16-1-x86_64.pkg.tar.xz...
-- Downloading https://mirror.yandex.ru/mirrors/msys2/msys/x86_64/libiconv-1.16-1-x86_64.pkg.tar.xz... Failed. Status: 22;"HTTP response code said error"
-- Downloading https://mirrors.tuna.tsinghua.edu.cn/msys2/msys/x86_64/libiconv-1.16-1-x86_64.pkg.tar.xz...
-- Downloading https://mirrors.tuna.tsinghua.edu.cn/msys2/msys/x86_64/libiconv-1.16-1-x86_64.pkg.tar.xz... Failed. Status: 22;"HTTP response code said error"
-- Downloading https://mirrors.ustc.edu.cn/msys2/msys/x86_64/libiconv-1.16-1-x86_64.pkg.tar.xz...
-- Downloading https://mirrors.ustc.edu.cn/msys2/msys/x86_64/libiconv-1.16-1-x86_64.pkg.tar.xz... Failed. Status: 22;"HTTP response code said error"
-- Downloading https://mirror.bit.edu.cn/msys2/msys/x86_64/libiconv-1.16-1-x86_64.pkg.tar.xz...
-- Downloading https://mirror.bit.edu.cn/msys2/msys/x86_64/libiconv-1.16-1-x86_64.pkg.tar.xz... Failed. Status: 22;"HTTP response code said error"
-- Downloading https://mirror.selfnet.de/msys2/msys/x86_64/libiconv-1.16-1-x86_64.pkg.tar.xz...
-- Downloading https://mirror.selfnet.de/msys2/msys/x86_64/libiconv-1.16-1-x86_64.pkg.tar.xz... Failed. Status: 22;"HTTP response code said error"
-- Downloading https://mirrors.sjtug.sjtu.edu.cn/msys2/msys/x86_64/libiconv-1.16-1-x86_64.pkg.tar.xz...
-- Downloading https://mirrors.sjtug.sjtu.edu.cn/msys2/msys/x86_64/libiconv-1.16-1-x86_64.pkg.tar.xz... Failed. Status: 22;"HTTP response code said error"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:181 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_acquire_msys.cmake:87 (vcpkg_download_distfile)
  scripts/cmake/vcpkg_acquire_msys.cmake:125 (msys_package_download)
  scripts/cmake/vcpkg_acquire_msys.cmake:291 (msys_package)
  ports/icu/portfile.cmake:80 (vcpkg_acquire_msys)
  scripts/ports.cmake:79 (include)

Error: Building package icu:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: icu:x86-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.

**Additional context**
Where to find "libiconv-1.16-1-x86_64.pkg.tar.xz"?

**Comment by JackBoosY** [comment]
Please update your vcpkg and try again.

Thanks.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
