### ISSUE TITLE
python3:x64-osx build failure

### ISSUE THREAD

**Issue by sai-cartly** [microsoft/vcpkg#14672]
**Host Environment**
- OS: macos Bigsur
- Compiler: revision

**To Reproduce**
`./vcpkg install socket-io-client:x64-osx`

**Failure logs** 
clang: warning: -framework CoreFoundation: 'linker' input unused [-Wunused-command-line-argument]
Python/ast.c:3688:5: warning: code will never be executed [-Wunreachable-code]
    PyErr_SetString(PyExc_SystemError, "unhandled import name condition");
    ^~~~~~~~~~~~~~~

./Modules/getpath.c:809:49: warning: incompatible pointer types passing 'unsigned long *' to parameter of type 'uint32_t *' (aka 'unsigned int *') [-Wincompatible-pointer-types]
    else if(0 == _NSGetExecutablePath(execpath, &nsexeclength) &&
                                                ^~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/mach-o/dyld.h:98:54: note: passing argument to parameter 'bufsize' here
extern int _NSGetExecutablePath(char* buf, uint32_t* bufsize)                 __OSX_AVAILABLE_STARTING(__MAC_10_2, __IPHONE_2_0);
                                                     ^
./Modules/posixmodule.c:9221:15: error: implicit declaration of function 'sendfile' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        ret = sendfile(in, out, offset, &sbytes, &sf, flags);
              ^

make: *** [Modules/posixmodule.o] Error 1
make: *** Waiting for unfinished jobs....
1 warning generated.

------------ console logs ----------------------
-- Downloading https://github.com/python/cpython/archive/v3.8.3.tar.gz...
-- Extracting source /usr/local/Cellar/vcpkg/2020.11-1/libexec/downloads/python-cpython-v3.8.3.tar.gz
-- Using source at /usr/local/Cellar/vcpkg/2020.11-1/libexec/buildtrees/python3/src/v3.8.3-43b03f2bf0.clean
-- Configuring x64-osx-rel
-- Building x64-osx-rel
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:142 (message):
    Command failed: make install -j 9
    Working Directory: /usr/local/Cellar/vcpkg/2020.11-1/libexec/buildtrees/python3/src/v3.8.3-43b03f2bf0.clean-x64-osx-release
    See logs for more information:
      /usr/local/Cellar/vcpkg/2020.11-1/libexec/buildtrees/python3/make-build-x64-osx-release-out.log
      /usr/local/Cellar/vcpkg/2020.11-1/libexec/buildtrees/python3/make-build-x64-osx-release-err.log

Call Stack (most recent call first):
  ports/python3/portfile.cmake:150 (vcpkg_execute_build_process)
  scripts/ports.cmake:135 (include)

Error: Building package python3:x64-osx failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: python3:x64-osx
  Vcpkg version: 2020.06.15-unknownhash
----------------------------------------------------

**Comment by Hoikas** [comment]
The python3 port has been updated since this post. Could you update vcpkg and try again?

**Comment by JonLiu1993** [comment]
@sai-cartly ,Thanks for posting this issue,I have successfully installed socket-io-client: x64-osx in OSX environment following your steps. You can update your vcpkg and reinstall it. If there are still problems, please attach your error log. Thank you!

![Capture](https://user-images.githubusercontent.com/63675417/99938775-89d09700-2da3-11eb-8df5-9d32549a04ec.PNG)

**Comment by sai-cartly** [comment]
Getting a different error

Building package python3[core]:x64-osx...
Could not locate cached archive: /Users/saimatam/.cache/vcpkg/archives/4f/4f54db883683de02a27ed8e67550f466bf2eab23.zip
-- Using cached /usr/local/Cellar/vcpkg/2020.11-1/libexec/downloads/python-cpython-v3.8.3.tar.gz
-- Extracting source /usr/local/Cellar/vcpkg/2020.11-1/libexec/downloads/python-cpython-v3.8.3.tar.gz
-- Using source at /usr/local/Cellar/vcpkg/2020.11-1/libexec/buildtrees/python3/src/v3.8.3-43b03f2bf0.clean
-- Configuring x64-osx-rel
-- Building x64-osx-rel
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:142 (message):
    Command failed: make install -j 9
    Working Directory: /usr/local/Cellar/vcpkg/2020.11-1/libexec/buildtrees/python3/src/v3.8.3-43b03f2bf0.clean-x64-osx-release
    See logs for more information:
      /usr/local/Cellar/vcpkg/2020.11-1/libexec/buildtrees/python3/make-build-x64-osx-release-out.log
      /usr/local/Cellar/vcpkg/2020.11-1/libexec/buildtrees/python3/make-build-x64-osx-release-err.log

Call Stack (most recent call first):
  ports/python3/portfile.cmake:150 (vcpkg_execute_build_process)
  scripts/ports.cmake:135 (include)


Error: Building package python3:x64-osx failed with: BUILD_FAILED

**Comment by Hoikas** [comment]
Python3 was updated to 3.9.0 last week, which should fix big sur compatibility. Please update vcpkg to the latest master.

**Comment by JonLiu1993** [comment]
@sai-cartly ，You recreate a folder, then clone vcpkg and rebuild，If it still doesn't work, please provide a complete error log

**Comment by chuyanjuncn** [comment]
PS D:\vcpkg> .\vcpkg install python3:x64-windows
Computing installation plan...
The following packages will be built and installed:
    python3[core]:x64-windows
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\chuyj\AppData\Local\vcpkg\archives\66\663e5ef850aa0860a73e02d0eb95e0b62874be81.zip
Starting package 1/1: python3:x64-windows
Building package python3[core]:x64-windows...
-- Using cached D:/vcpkg/downloads/python-cpython-v3.9.0.tar.gz
-- Extracting source D:/vcpkg/downloads/python-cpython-v3.9.0.tar.gz
-- Using source at D:/vcpkg/buildtrees/python3/src/v3.9.0-e901d4bfb3.clean
-- Building D:/vcpkg/buildtrees/python3/src/v3.9.0-e901d4bfb3.clean-Lib-Win/PCBuild/pythoncore.vcxproj for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:106 (message):
    Command failed: msbuild D:/vcpkg/buildtrees/python3/src/v3.9.0-e901d4bfb3.clean-Lib-Win/PCBuild/pythoncore.vcxproj /p:Configuration=Release /t:Rebuild /p:Platform=x64 /p:PlatformToolset=v140 /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /p:WindowsTargetPlatformVersion= /p:VcpkgManifestInstall=false /m
    Working Directory: D:/vcpkg/buildtrees/python3/x64-windows-rel
    Error code: 1
    See logs for more information:
      D:\vcpkg\buildtrees\python3\build-x64-windows-rel-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_msbuild.cmake:122 (vcpkg_execute_required_process)
  ports/python3/portfile.cmake:56 (vcpkg_build_msbuild)
  scripts/ports.cmake:136 (include)


Error: Building package python3:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: python3:x64-windows
  Vcpkg version: 2020.11.12-nohash

**Comment by JonLiu1993** [comment]
@chuyanjuncn ，Can you provide me with this log：_D:\vcpkg\buildtrees\python3\build-x64-windows-rel-out.log_
I can successfully build in the window10 environment
![Capture](https://user-images.githubusercontent.com/63675417/100313273-3c486a00-2fef-11eb-8210-25a1583e9935.PNG)

**Comment by chuyanjuncn** [comment]
Microsoft (R) 生成引擎版本 14.0.25420.1
版权所有(C) Microsoft Corporation。保留所有权利。

time 2020/11/26 13:48:02。
     1>project“D:\vcpkg\buildtrees\python3\src\v3.9.0-e901d4bfb3.clean-Lib-Win\PCBuild\pythoncore.vcxproj”on node 1 上(Rebuild target)。
     1>D:\vcpkg\buildtrees\python3\src\v3.9.0-e901d4bfb3.clean-Lib-Win\PCBuild\python.props(111,31): error MSB4184: can not calculate express“[System.Version]::Parse('')”。Version string too long or too short。 [D:\vcpkg\buildtrees\python3\src\v3.9.0-e901d4bfb3.clean-Lib-Win\PCBuild\pythoncore.vcxproj]
     1>generated project“D:\vcpkg\buildtrees\python3\src\v3.9.0-e901d4bfb3.clean-Lib-Win\PCBuild\pythoncore.vcxproj”(Rebuild target) operation  - failar。

generation failar。

       “D:\vcpkg\buildtrees\python3\src\v3.9.0-e901d4bfb3.clean-Lib-Win\PCBuild\pythoncore.vcxproj”(Rebuild target) (1) ->
         D:\vcpkg\buildtrees\python3\src\v3.9.0-e901d4bfb3.clean-Lib-Win\PCBuild\python.props(111,31): error MSB4184: can not calculate express“[System.Version]::Parse('')”。Version string too long or too short。 [D:\vcpkg\buildtrees\python3\src\v3.9.0-e901d4bfb3.clean-Lib-Win\PCBuild\pythoncore.vcxproj]

    0 warning 
    1 error

using time 00:00:00.04

**Comment by JonLiu1993** [comment]
@chuyanjuncn ，This problem does not seem to be a vcpkg problem, it may be related to VS, you can try to upgrade your VS2017 first, and then try again

**Comment by chuyanjuncn** [comment]
thanks. I will try again

**Comment by sai-cartly** [comment]
Here is the error in the log:

```
./Modules/posixmodule.c:9221:15: error: implicit declaration of function 'sendfile' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        ret = sendfile(in, out, offset, &sbytes, &sf, flags);
              ^
clang: warning: -framework CoreFoundation: 'linker' input unused [-Wunused-command-line-argument]
1 error generated.
make: *** [Modules/posixmodule.o] Error 1
make: *** Waiting for unfinished jobs....
clang: warning: -framework CoreFoundation: 'linker' input unused [-Wunused-command-line-argument]
1 warning generated.
```

**Comment by Hoikas** [comment]
@sai-cartly Are you certain that you have updated to the latest vcpkg master by executing `git pull && ./bootstrap-vcpkg.sh` in the terminal? From the error log you have posted, your vcpkg is [still building Python 3.8.3](https://github.com/python/cpython/blob/v3.8.3/Modules/posixmodule.c#L9221), which does not support macOS Big Sur. [Compare with line 9221 of posixmodule.c in Python 3.9.0](https://github.com/python/cpython/blob/v3.9.0/Modules/posixmodule.c#L9221), which does support macOS Big Sur,

@chuyanjuncn and @JonLiu1993, this issue is about macOS Big Sur. I think Windows discussion should happen in a new issue. Thanks.

**Comment by sai-cartly** [comment]
@Hoikas -- You are right.

I used vcpkg to install python3 on  MacOS Catalina and succeeded.

I created a new folder vcpkg and downloaded sources from github and built vcpkg
Next I used ./vcpkg install python3  on MacOS Big Sur and it worked !

Here is the log below
`-- Installing x64-osx-dbg done
-- Installing: /Users/saimatam/soft2/vcpkg/packages/python3_x64-osx/share/python3/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: /Users/saimatam/.cache/vcpkg/archives/c4/c4eb0d53ef11052918cc111e3d28e2eb95e6e88e.zip
Building package python3[core]:x64-osx... done
Installing package python3[core]:x64-osx...
Installing package python3[core]:x64-osx... done
Elapsed time for package python3:x64-osx: 4.742 min

Total elapsed time: 9.087 min

saimatam@Sais-MacBook-Pro vcpkg % 
`

**Comment by Hoikas** [comment]
Great news! 😄

**Comment by sai-cartly** [comment]
You can close this issue as resolved.

**Comment by JonLiu1993** [comment]
@Hoikas ,thank you for your help
