### ISSUE TITLE
'vcpkg integrate powershell'  seems write the profile into wrong file.

### ISSUE THREAD

**Issue by ForeverCyril** [microsoft/vcpkg#14671]
**Describe the bug**

The `'vcpkg integrate powershell' add the content into '$HOME\Documents\PowerShell\Microsoft.PowerShell_profile.ps1'. But my `$PROFILE.CurrentUserCurrentHost` file was in `$HOME\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1` which I think is the default value due to I never change it.

**Environment**
- OS: window 20H2 (19042.630)
- Compiler: MSVC 2019

**To Reproduce**
1. 'vcpkg integrate powershell`
2. See error

**Expected behavior**

It should write into the correct powershell profile file based on the value of $PROFILE.CurrentUserCurrentHost.

**Failure logs** 
```
Adding the following line to C:\Users\<user>\Documents\PowerShell\Microsoft.PowerShell_profile.ps1

PS C:\Users\user> $PROFILE.CurrentUserCurrentHost
C:\Users\user\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1
```

**Comment by NancyLi1013** [comment]
@strega-nil 

Could you please help take a look?

**Comment by strega-nil** [comment]
@ForeverCyril unfortunately, `vcpkg integrate powershell` is designed for powershell core. We don't generally support Windows PowerShell with the integration.

**Comment by NancyLi1013** [comment]
Hi @ForeverCyril 

I'm closing this issue for now since we don't support Windows PowerShell with the integration in vcpkg.  

Thanks for your answer @strega-nil.
