### ISSUE TITLE
[libzippp] x64-windows build failure after liblzma use upstream CMakeLists.txt + Add pkgconfig. (#14615)

### ISSUE THREAD

**Issue by StarGate-One** [microsoft/vcpkg#14679]
**Issue**
[libzippp] x64-windows build failure after commit https://github.com/microsoft/vcpkg/commit/eb895b95aac6fd7485373702f29f508c42a180a0 [liblzma] use upstream CMakeLists.txt + Add pkgconfig. **(#14615)** on windows, linux (openSUSE Leap 15.2 on WSL2 and Hyper-V is fine)

**Host Environment**
- OS: Microsoft Windows [Version 10.0.19042.630]
- Compiler:
   - VS2017 Visual Studio 2017 Version: 15.9.29  VS Tools Version: 14.16.27023 
                  Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27044 for x64
   - VS2019 Visual Studio 2019 Version: 16.8.2  VS Tools Version: 14.28.29333 
                  Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29334 for x64

**To Reproduce**
1. `git pull`
2. `.\vcpkg.exe --debug install --x-use-aria2 --recurse --keep-going  libarchive[bzip2,core,libxml2,lz4,lzma,lzo,openssl,zstd]:x64-windows liblzma[core]:x64-windows libxml2[core]:x64-windows libzip[bzip2,commoncrypto,core,default-aes,liblzma,mbedtls,openssl,wincrypto]:x64-windows libzippp[core]:x64-windows`

**Failure logs** 
- Cut and past the appropriate build messages from the console output.
Warning: passed either --printmetrics or --no-printmetrics, but metrics are disabled.
[DEBUG] Feature flag 'binarycaching' = off
[DEBUG] Feature flag 'manifests' = off
[DEBUG] Feature flag 'compilertracking' = off
[DEBUG] Feature flag 'registries' = off
[DEBUG] Feature flag 'versions' unset
[DEBUG] Using vcpkg-root: D:\vcpkg_x64\vs2019\test
[DEBUG] Using installed-root: D:\vcpkg_x64\vs2019\test\installed
[DEBUG] Using buildtrees-root: D:\vcpkg_x64\vs2019\test\buildtrees
[DEBUG] Using downloads-root: D:\vcpkg_x64\vs2019\test\downloads
[DEBUG] Using packages-root: D:\vcpkg_x64\vs2019\test\packages
[DEBUG] Using scripts-root: D:\vcpkg_x64\vs2019\test\scripts
[DEBUG] Default binary cache path is: E:\vcpkg_x64\vs2019\test\vcpkg\archives
Computing installation plan...
[DEBUG] Found path: C:\Program Files\CMake\bin\cmake.exe
[DEBUG] Found path: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe
[DEBUG] CreateProcessW("C:\Program Files\CMake\bin\cmake.exe" --version)
[DEBUG] cmd_execute_and_stream_data() returned 0 after    24415 us
[DEBUG] CreateProcessW("C:\Program Files\CMake\bin\cmake.exe" -DVCPKG_ROOT_DIR=D:/vcpkg_x64/vs2019/test -DPACKAGES_DIR=D:/vcpkg_x64/vs2019/test/packages -DBUILDTREES_DIR=D:/vcpkg_x64/vs2019/test/buildtrees -D_VCPKG_INSTALLED_DIR=D:/vcpkg_x64/vs2019/test/installed -DDOWNLOADS=D:/vcpkg_x64/vs2019/test/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "D:\vcpkg_x64\vs2019\test\buildtrees\0.vcpkg_dep_info.cmake")
[DEBUG] cmd_execute_and_stream_data() returned 0 after    12566 us
[DEBUG] CreateProcessW("C:\Program Files\CMake\bin\cmake.exe" -DVCPKG_ROOT_DIR=D:/vcpkg_x64/vs2019/test -DPACKAGES_DIR=D:/vcpkg_x64/vs2019/test/packages -DBUILDTREES_DIR=D:/vcpkg_x64/vs2019/test/buildtrees -D_VCPKG_INSTALLED_DIR=D:/vcpkg_x64/vs2019/test/installed -DDOWNLOADS=D:/vcpkg_x64/vs2019/test/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "D:\vcpkg_x64\vs2019\test\buildtrees\0.vcpkg_tags.cmake")
[DEBUG] cmd_execute_and_stream_data() returned 0 after    13326 us
The following packages will be built and installed:
    libarchive[bzip2,core,libxml2,lz4,lzma,lzo,openssl,zstd]:x64-windows
    liblzma[core]:x64-windows
    libxml2[core]:x64-windows
    libzip[bzip2,commoncrypto,core,default-aes,liblzma,mbedtls,openssl,wincrypto]:x64-windows
    libzippp[core]:x64-windows
[DEBUG] CreateProcessW("C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -all -prerelease -legacy -products * -format xml)
 ...
Installing package libzip[bzip2,commoncrypto,core,default-aes,liblzma,mbedtls,openssl,wincrypto]:x64-windows... done
Elapsed time for package libzip:x64-windows: 18.73 s
Starting package 5/5: libzippp:x64-windows
Building package libzippp[core]:x64-windows...
[DEBUG] CreateProcessW("C:\Program Files\CMake\bin\cmake.exe" -DPORT=libzippp -DCURRENT_PORT_DIR=D:/vcpkg_x64/vs2019/test/ports/libzippp -DVCPKG_USE_HEAD_VERSION=0 -D_VCPKG_NO_DOWNLOADS=0 -D_VCPKG_DOWNLOAD_TOOL=ARIA2 -D_VCPKG_EDITABLE=0 -DFEATURES=core "-DALL_FEATURES=encryption;" -DCMD=BUILD -DTARGET_TRIPLET=x64-windows "-DTARGET_TRIPLET_FILE=D:\vcpkg_x64\vs2019\test\triplets\x64-windows.cmake" -DVCPKG_PLATFORM_TOOLSET=v142 -DDOWNLOADS=D:/vcpkg_x64/vs2019/test/downloads -DVCPKG_CONCURRENCY=8 "-DGIT=C:/Program Files/Git/cmd/git.exe" -DVCPKG_ROOT_DIR=D:/vcpkg_x64/vs2019/test -DPACKAGES_DIR=D:/vcpkg_x64/vs2019/test/packages -DBUILDTREES_DIR=D:/vcpkg_x64/vs2019/test/buildtrees -D_VCPKG_INSTALLED_DIR=D:/vcpkg_x64/vs2019/test/installed -DDOWNLOADS=D:/vcpkg_x64/vs2019/test/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "D:\vcpkg_x64\vs2019\test\scripts\ports.cmake")
-- Using cached D:/vcpkg_x64/vs2019/test/downloads/ctabin-libzippp-791bdc43eb18b87e3bdfa087493e3e32217e672c.tar.gz
-- Extracting source D:/vcpkg_x64/vs2019/test/downloads/ctabin-libzippp-791bdc43eb18b87e3bdfa087493e3e32217e672c.tar.gz
-- Using source at D:/vcpkg_x64/vs2019/test/buildtrees/libzippp/src/32217e672c-26e2865e9c.clean
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:106 (message):
    Command failed: ninja -v
    Working Directory: D:/vcpkg_x64/vs2019/test/buildtrees/libzippp/x64-windows-rel/vcpkg-parallel-configure
    **Error code: 1**
    **See logs for more information:**
    **D:\vcpkg_x64\vs2019\test\buildtrees\libzippp\config-x64-windows-out.log**

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:314 (vcpkg_execute_required_process)
  ports/libzippp/portfile.cmake:14 (vcpkg_configure_cmake)
  scripts/ports.cmake:136 (include)

[DEBUG] cmd_execute_and_stream_data() returned 1 after  1786896 us
Error: Building package libzippp:x64-windows failed with: BUILD_FAILED
Elapsed time for package libzippp:x64-windows: 1.788 s

Total elapsed time: 1.792 min

RESULTS
    liblzma:x64-windows: SUCCEEDED: 9.933 s
    libxml2:x64-windows: SUCCEEDED: 6.03 s
    libarchive:x64-windows: SUCCEEDED: 1.175 min
    libzip:x64-windows: SUCCEEDED: 18.73 s
    libzippp:x64-windows: BUILD_FAILED: 1.788 s

SUMMARY
    SUCCEEDED: 4
    BUILD_FAILED: 1
    POST_BUILD_CHECKS_FAILED: 0
    FILE_CONFLICTS: 0
    CASCADED_DUE_TO_MISSING_DEPENDENCIES: 0
    EXCLUDED: 0
The package liblzma provides CMake targets:
 ...

- Please attach any additional failure logs mentioned in the console output.
   - VS2017 
[vs2017-config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/5576095/vs2017-config-x64-windows-out.log)

   - VS2019 
[vs2019-config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/5576097/vs2019-config-x64-windows-out.log)

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.
- **Failure in config-x64-windows-out.log(s)**

-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
CMake Error at D:/vcpkg_x64/vs2019/test/scripts/buildsystems/vcpkg.cmake:582 (_find_package):
  By not providing "FindLibLZMA::LibLZMA.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "LibLZMA::LibLZMA", but CMake did not find one.

  Could not find a package configuration file provided by "LibLZMA::LibLZMA"
  with any of the following names:

    LibLZMA::LibLZMAConfig.cmake
    liblzma::liblzma-config.cmake

  Add the installation prefix of "LibLZMA::LibLZMA" to CMAKE_PREFIX_PATH or
  set "LibLZMA::LibLZMA_DIR" to a directory containing one of the above
  files.  If "LibLZMA::LibLZMA" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  cmake/FindLIBZIP.cmake:53 (find_package)
  D:/vcpkg_x64/vs2019/test/scripts/buildsystems/vcpkg.cmake:582 (_find_package)
  CMakeLists.txt:25 (find_package)

-- Configuring incomplete, errors occurred!

**Comment by StarGate-One** [comment]
@Neumann-A @strega-nil 
I am sure this is an easy fix, most likely the configuration package name changed, but it sure eludes me on where to make the change 😢

**Comment by StarGate-One** [comment]
- CI Pipeline appears to have just used a cached copy instead of recompiling...
- For some reason it did not pickup liblzma is a dependency of libzippp and try to recompile libzippp?
2020-11-20T02:14:57.7480814Z                      libxslt:x64-windows:       pass: 587f8ce8cf93e54055d9c96ef250b73a3c73e3d3
**2020-11-20T02:14:57.7485920Z                     libzippp:x64-windows:       pass: 6488d6120706fc2c500637b633e66f11be0e8244**
2020-11-20T02:14:57.7490999Z                    licensepp:x64-windows:       pass: 55e039259ca9531b8ac1fcc013e7f9323a33a2ee

**Comment by strega-nil** [comment]
@StarGate-One also looking into this one, thank you @StarGate-One

**Comment by Neumann-A** [comment]
> CI Pipeline appears to have just used a cached copy instead of recompiling.

that is because lzma is not a default feature of libzip.

**Comment by Neumann-A** [comment]
That is the problem:
`E:/vcpkg_folders/liblzma/buildtrees/libzippp/src/32217e672c-26e2865e9c.clean/cmake/FindLIBZIP.cmake(53):  find_package(LibLZMA::LibLZMA REQUIRED )`

basically 90% of the `find_package` calls in `FindLIBZIP.cmake` are nonesense. Wonder if it worked before.

**Comment by strega-nil** [comment]
@Neumann-A exciting. I'll make sure to fix it.

**Comment by StarGate-One** [comment]
@Neumann-A @strega-nil Thank you very much for your hard work, I am trying to learn this so I can make changes/patches and submit the PR instead of just creating issues.

- I think that is what is so confusing to me, port libzippp has `[vcpkg-root]\buildtrees\libzippp\src\32217e672c-26e2865e9c.clean\FindLIBZIP.cmake` and in turn looks like it has all the compression libraries in it for windows builds, but it does not look like the oncre created on Linux builds.
- It is more fun to research, find the problem then especially rewarding to fix the problem instead of depending on someone else. It is like a puzzle to be solved.

**Comment by strega-nil** [comment]
@StarGate-One if you're interested, you can look into it; any questions you have should be asked on the #include<C++> discord, in the #vcpkg channel :)

**Comment by Neumann-A** [comment]
`--trace` or `--trace-expand` are the magic options for cmake / `vcpkg_configure_cmake` to get enough log info to debug such errors and see what is going on.

**Comment by StarGate-One** [comment]
@Neumann-A at the risk of sounding dumb, where would I put these options - I tried modifying/adding them to then end of the command line in vcpkg_build_cmake.cmake and vcpkg_configure_cmake.cmake with no results

> `--trace` or `--trace-expand` are the magic options for cmake / `vcpkg_configure_cmake` to get enough log info to debug such errors and see what is going on.

@Neumann-A cc: @strega-nil 
> That is the problem:
> `E:/vcpkg_folders/liblzma/buildtrees/libzippp/src/32217e672c-26e2865e9c.clean/cmake/FindLIBZIP.cmake(53): find_package(LibLZMA::LibLZMA REQUIRED )`
> 
> basically 90% of the `find_package` calls in `FindLIBZIP.cmake` are nonsense. Wonder if it worked before.

I think you are absolutely correct. I doubt it ever worked correctly. A dependents of libzippp.dll before the lzma commit today and it looks like zip.dll, no lzma.dll lzo.dll lz4.dll etc even though the `[vcpkg-root]\buildtrees\libzippp\src\32217e672c-26e2865e9c.clean\FindLIBZIP.cmake` has this:
>if (LIBZIP_FOUND)
>    if (NOT TARGET libzip::zip)
> ...
>        if(_have_extra_libs MATCHES "-lbz2")
>        if(_have_extra_libs MATCHES "-lcrypto")
>        if(_have_extra_libs MATCHES "-lgnutls")
>        if(_have_extra_libs MATCHES "lgnutls")
>        if(_have_extra_libs MATCHES "-llzma")
 >       if(_have_extra_libs MATCHES "-lz")
______________________________________________________________
> ->dumpbin /dependents .\installed\x64-windows\bin\libzippp.dll
>Microsoft (R) COFF/PE Dumper Version 14.28.29334.0
>Copyright (C) Microsoft Corporation.  All rights reserved.
>
>Dump of file .\installed\x64-windows\bin\libzippp.dll
>File Type: DLL
>Image has the following dependencies:
>
>    zip.dll
>   MSVCP140.dll
>    VCRUNTIME140.dll
>    VCRUNTIME140_1.dll
>    api-ms-win-crt-runtime-l1-1-0.dll

______________________________________________________________
> ->dumpbin /dependents .\installed\x64-windows\bin\zip.dll
>Microsoft (R) COFF/PE Dumper Version 14.28.29334.0
>Copyright (C) Microsoft Corporation.  All rights reserved.
>
>Dump of file .\installed\x64-windows\bin\zip.dll
>
>File Type: DLL
>
>  Image has the following dependencies:
>
>    ADVAPI32.dll
>    bz2.dll
>    bcrypt.dll
>    zlib1.dll

______________________________________________________________
> ->dumpbin /dependents .\installed\x64-windows\bin\zlib1.dll
>Microsoft (R) COFF/PE Dumper Version 14.28.29334.0
>Copyright (C) Microsoft Corporation.  All rights reserved.
>
>Dump of file .\installed\x64-windows\bin\zlib1.dll
>
>File Type: DLL
>
>  Image has the following dependencies:
>
>    VCRUNTIME140.dll
>    api-ms-win-crt-stdio-l1-1-0.dll
>    api-ms-win-crt-heap-l1-1-0.dll
>    api-ms-win-crt-convert-l1-1-0.dll
>    api-ms-win-crt-runtime-l1-1-0.dll
>    KERNEL32.dll
>
>  Summary

**Comment by Neumann-A** [comment]
> at the risk of sounding dumb, where would I put these options - I tried modifying/adding them to then end of the command line in vcpkg_build_cmake.cmake and vcpkg_configure_cmake.cmake with no results

in the `portfile` into the `vcpkg_configure_cmake` call as `OPTIONS` parameter

somewhere in the `portfile` there should be a
```
vcpkg_configure_cmake(<something something>
                      OPTIONS --trace
                      <something something>
```´
alternativly you can use --trace-expand instead of trace

**Comment by StarGate-One** [comment]
OK @Neumann-A I give it a try a little later. Thank you👍👍👍

**Comment by StarGate-One** [comment]
It is going to take someone more experience than I to figure out how this can be fixed.

**Comment by StarGate-One** [comment]
Thank you everyone.
