### ISSUE TITLE
Mismatching hash of the downloaded nuget when AppVeyor build

### ISSUE THREAD

**Issue by crazyks** [Microsoft/vcpkg#1468]
We get a "Mismatching hash of the downloaded nuget" error when running a AppVeyor CI build.

Error message is:
Mismatching hash of the downloaded nuget
At C:\projects\guetzli\vcpkg\scripts\fetchDependency.ps1:214 char:9
         throw [System.IO.FileNotFoundException] ("Mismatching hash of ...
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        CategoryInfo          : OperationStopped: (:) [], FileNotFoundException
        FullyQualifiedErrorId : Mismatching hash of the downloaded nuget
 
Command exited with code 1

Full log is [here](https://github.com/Microsoft/vcpkg/files/1151767/log.txt)。 Please help.
Thanks!
.

**Comment by jasjuang** [comment]
Awesome to see someone attempting to get AppVeyor in vcpkg!

**Comment by ras0219-msft** [comment]
It looks like you're downloading the latest[1] instead of the 3.5.0 stable that we expect[2].

[1] https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
[2] https://dist.nuget.org/win-x86-commandline/v3.5.0/nuget.exe

**Comment by crazyks** [comment]
@ras0219-msft Thanks for your reply, I did use the latest one. I will changed it to v3.5.0.
