### ISSUE TITLE
user has no "C:\Program Files (x86)\Microsoft Visual Studio\Installer" folder

### ISSUE THREAD

**Issue by DBJDBJ** [microsoft/vcpkg#14682]
"My" test use case is "user has deleted "C:\Program Files (x86)\Microsoft Visual Studio\Installer", what then?

The bug: `bootstrap.ps1` assumes on each and every machines that folder does exist and `vswhere.exe` is in there.

The solution is perhaps simple: just include vswhere.exe with `vcpkg` ... That way `vcpkg` is decoupled from various weird and wonderful local VS installation issues.

bootstrap.ps1 line 72
```
72 >  $vswhereExe = "$programFiles\Microsoft Visual Studio\Installer\vswhere.exe"
```
I changed to:
```
72 >  $vswhereExe = "d:\vswhere.exe"
```
vshwere.exe [originates from here](https://github.com/Microsoft/vswhere/releases).

And 
```
D:\vcpkg>bootstrap-vcpkg.bat
```
It worketh ...

**Environment**
- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**
1. ./vcpkg install xxxx
2. See error
Repro code when

**Expected behavior**

**Failure logs** 
-(please attached failure logs)

**Additional context**

**Comment by vicroms** [comment]
We plan on changing the behavior of our bootstrap script to download a pre-built and signed vcpkg binary (hopefully we can get to this soon). The option to build from code will still be available via our CMake project in `toolsrc/`. 

This should fix this problem and hopefully our issues with AV software.

**Comment by DBJDBJ** [comment]
@vicroms  that's great Victor Romero ... Truth to be told Avast should not throw this big bold error dialogues on `vcpkg.exe`, for civilians to get the heart attack.
