### ISSUE TITLE
Bootstrap bat succeeds but when vcpkg.exe clicked on window opens/closes instantly 

### ISSUE THREAD

**Issue by dave-goodall** [microsoft/vcpkg#14680]
**Describe the bug**
As title.The vcpkg.exe  is 1,425,920 bytes.

**Environment**
- Windows 10

**To Reproduce**
1. Just click on vcpkg.exe in explorer

**Expected behavior**
A window that opens and presents the vcpkg home page

**Failure logs** 
There's a CHANGELOG.md in the vcpkg-master directory but on opening that it's just a list of updates for the package.  I see no other error logs in there 

**Additional context**

**Comment by vicroms** [comment]
Hi @dave-goodall 

Vcpkg is a command line tool not a GUI application. You interact with it by running commands on a terminal.

```
vcpkg help
vcpkg install boost
```

Please refer to our README or our documentation to learn how to use vcpkg.
