### ISSUE TITLE
Me thinks vcpkg need to be tested for AV's throwing false positives about it

### ISSUE THREAD

**Issue by DBJDBJ** [microsoft/vcpkg#14684]
Finally, my vcpkg.exe was built. Just to be immediately quarantined by "Avast", with the following message:

![avast](https://user-images.githubusercontent.com/145155/99599272-4967c680-29fb-11eb-9bee-de8cd438febb.png)

Now each time I run the `vcpkg.exe`, it goes through the command, and then "Avast" pops up a message (each time):

![avast](https://user-images.githubusercontent.com/145155/99600320-7917ce00-29fd-11eb-9e2e-88eb453e11bf.png)

And the sequence of "infected files" is growing:

![avast](https://user-images.githubusercontent.com/145155/99600393-a2d0f500-29fd-11eb-9fee-4885f3bea193.png)

ps: Yes I know about the AV "exclusions" to be set up and such. But, is this users duty to test and report on this?

**Environment**
- WIn10 PRO
- Compiler: cl.exe as coming with VS 2019 16.8.2

**Comment by vadi2** [comment]
This is unfortunately a false positive on the AV's side. Double-check that with https://www.virustotal.com/gui.

**Comment by JackBoosY** [comment]
Well, this issue can be solved by releasing binary version of vcpkg in the future.

**Comment by DBJDBJ** [comment]
There is a small detail to be answered: Why does e.g. Avast "thinks" vcpkg.exe is such a big malware danger?

I assume the owner of this product needs to meet with Avast and the very few of other AV vendors, perhaps.

I have not checked but the real funny issue might be if Windows Defender also "thinks" vcpkg.exe is a malware.

**Comment by NancyLi1013** [comment]
This is due to that vcpkg haven't signed in vcpkg binary.

**Comment by JackBoosY** [comment]
This seems because vcpkg will collect some informations. see https://github.com/microsoft/vcpkg#telemetry.

**Comment by DBJDBJ** [comment]
@NancyLi1013 Good. But. Avast, Avira, AVG et all might not let it through even if it is a signed binary. Hint: Because of the telemetry perhaps?
