### ISSUE TITLE
how one can specify a branch that is not the master branch to download using vcpkg?

### ISSUE THREAD

**Issue by juandent** [microsoft/vcpkg#14693]
I checked the help for vcpckg help topics and nothing seems to mention anything related to branches... I also checked the docs folder but none of the .md files mention branches

**Comment by JonLiu1993** [comment]
@juandent ,Thanks for posting this issue,When you first create a file and then use the command: _git clone https://github.com/microsoft/vcpkg_ to get the vcpkg library, and then enter the vcpkg folder and use the command git branch to find that the master branch is automatically created. When you need to You can use _git checkou -b "xxx"_ to create a new branch with your own dedicated work branch. You can do your preliminary work on this work branch and submit it to the master branch after completion. I don’t know if the suggestions I provided are helpful to your problem.

**Comment by juandent** [comment]
@JonLiu1993 thanks. however my question was on how to download a specific branch of the github project corresponding to the vcpkg.
For example I would like the dev branch for the project boost-di

**Comment by JonLiu1993** [comment]
@juandent ,Sorry, it looks like I was mistaken. Let’s take your example. If you want to get the dev branch of boost-di, you need to modify the function vcpkg_from_github in the portfile.cmake file of boost-di, and change the master branch behind HEAD_REF The commit ID corresponding to the branch you need, so that's it.
````
vcpkg_from_github(
     OUT_SOURCE_PATH SOURCE_PATH
     REPO boost-experimental/di
     REF v1.1.0
     SHA512 69f7b0567cffea9bf983aedd7eabd1a07ae20249cd56a13de98eaa0cc835cbe3b76e790da68489536dd07edeb99271a69111f4d0c6b0aa3721ce9f5ead848fe0
     HEAD_REF master
)
````

**Comment by juandent** [comment]
@JonLiu1993 don't I need to change the SHA512 so it corresponds to the branch dev?
Do you mean just doing this will be enough? 

```c++
vcpkg_from_github(
     OUT_SOURCE_PATH SOURCE_PATH
     REPO boost-experimental/di
     REF v1.1.0
     SHA512 69f7b0567cffea9bf983aedd7eabd1a07ae20249cd56a13de98eaa0cc835cbe3b76e790da68489536dd07edeb99271a69111f4d0c6b0aa3721ce9f5ead848fe0
     HEAD_REF dev
)
```

Thanks!!

**Comment by juandent** [comment]
Seems to me SHA512 is a value per branch and using the one for Master will not verify correctly the download

**Comment by JonLiu1993** [comment]
It seems that there is no need to change SHA512

**Comment by PhoebeHui** [comment]
@juandent, does this still be a problem for you? if you want use the dev branch, you need to change the REF which the commitid from dev branch, then you can install the port, it will fail, and vcpkg would give the right SHA512, replace it with right one. It will use the correct source in dev branch. Please reopen this if it still be a problem for you.

**Comment by jacksonhunter** [comment]
Oh good gosh, thank you @PhoebeHui et al.
