### ISSUE TITLE
How do I install wangle under proxy well?

### ISSUE THREAD

**Issue by gwnet** [microsoft/vcpkg#14690]
When asking a question please also include where you looked for an answer (so we can update the documentation if needed).
[DEBUG] CreateProcessW("C:\Program Files\CMake\bin\cmake.exe" -DPORT=boost-compatibility -DCURRENT_PORT_DIR=C:/Wayne/vcpkg/ports/boost-compatibility -DVCPKG_USE_HEAD_VERSION=0 -D_VCPKG_NO_DOWNLOADS=0 -D_VCPKG_DOWNLOAD_TOOL=BUILT_IN -D_VCPKG_EDITABLE=0 -DFEATURES=core -DALL_FEATURES= -DCMD=BUILD -DTARGET_TRIPLET=x86-windows "-DTARGET_TRIPLET_FILE=C:\Wayne\vcpkg\triplets\x86-windows.cmake" -DVCPKG_PLATFORM_TOOLSET=v142 -DDOWNLOADS=C:/Wayne/vcpkg/downloads -DVCPKG_CONCURRENCY=9 "-DGIT=C:/Program Files/Git/cmd/git.exe" -DVCPKG_ROOT_DIR=C:/Wayne/vcpkg -DPACKAGES_DIR=C:/Wayne/vcpkg/packages -DBUILDTREES_DIR=C:/Wayne/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=C:/Wayne/vcpkg/installed -DDOWNLOADS=C:/Wayne/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "C:\Wayne\vcpkg\scripts\ports.cmake")
-- Downloading https://github.com/boostorg/compatibility/archive/boost-1.74.0.tar.gz...
-- Downloading https://github.com/boostorg/compatibility/archive/boost-1.74.0.tar.gz... Failed. Status: 4;"A requested feature, protocol or option was not found built-in in this libcurl due to a build-time decision."
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:182 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:143 (vcpkg_download_distfile)
  ports/boost-compatibility/portfile.cmake:3 (vcpkg_from_github)
  scripts/ports.cmake:136 (include)

[DEBUG] cmd_execute_and_stream_data() returned 1 after   197881 us
Error: Building package boost-compatibility:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-compatibility:x86-windows
  Vcpkg version: 2020.11.12-nohash

Additionally, attach any relevant sections from the log files above.
[DEBUG] C:\Wayne\vcpkg\toolsrc\src\vcpkg\install.cpp(494)
[DEBUG] Exiting after 13343048 us (13322545 us)

C:\Wayne\vcpkg>

**Comment by JonLiu1993** [comment]
@gwnet , We provide two workaround:
- use a proxy.
- Download [this file](https://github.com/microsoft/vcpkg/files/5589054/Downloads.zip) manually and unzip it to _VCPKG_ROOT_, then rerun install command. You should make sure the path is _VCPKG_ROOT/Downloads/nlohmann-json-v3.9.1/nlohmann_json.natvis_ etc., and make sure your vcpkg is latest.

**Comment by gwnet** [comment]
@JonLiu1993  I tried to download this file and unzip it. but I still suffer the same error. it failed to download boost. :(

can you send me detail command to set proxy well?

Could not locate cached archive: C:\Users\gaowayne\AppData\Local\vcpkg\archives\04\04a2f36e612a1db5fa256476ff4ab5e4d5e6465a.zip
Could not locate cached archive: C:\Users\gaowayne\AppData\Local\vcpkg\archives\11\110372f0f92bff6636c0de11837f33097eaac35f.zip
Could not locate cached archive: C:\Users\gaowayne\AppData\Local\vcpkg\archives\7b\7b3dcb469bac6bb79115f82c25f224ef64d2d803.zip
Could not locate cached archive: C:\Users\gaowayne\AppData\Local\vcpkg\archives\c8\c829a1e93341a5aade32f0abc379ba6d172aa4d2.zip
Starting package 1/78: boost-compatibility:x86-windows
Building package boost-compatibility[core]:x86-windows...
[DEBUG] CreateProcessW("C:\Program Files\CMake\bin\cmake.exe" -DPORT=boost-compatibility -DCURRENT_PORT_DIR=C:/Wayne/vcpkg/ports/boost-compatibility -DVCPKG_USE_HEAD_VERSION=0 -D_VCPKG_NO_DOWNLOADS=0 -D_VCPKG_DOWNLOAD_TOOL=BUILT_IN -D_VCPKG_EDITABLE=0 -DFEATURES=core -DALL_FEATURES= -DCMD=BUILD -DTARGET_TRIPLET=x86-windows "-DTARGET_TRIPLET_FILE=C:\Wayne\vcpkg\triplets\x86-windows.cmake" -DVCPKG_PLATFORM_TOOLSET=v142 -DDOWNLOADS=C:/Wayne/vcpkg/downloads -DVCPKG_CONCURRENCY=9 "-DGIT=C:/Program Files/Git/cmd/git.exe" -DVCPKG_ROOT_DIR=C:/Wayne/vcpkg -DPACKAGES_DIR=C:/Wayne/vcpkg/packages -DBUILDTREES_DIR=C:/Wayne/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=C:/Wayne/vcpkg/installed -DDOWNLOADS=C:/Wayne/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "C:\Wayne\vcpkg\scripts\ports.cmake")
-- Downloading https://github.com/boostorg/compatibility/archive/boost-1.74.0.tar.gz...
-- Downloading https://github.com/boostorg/compatibility/archive/boost-1.74.0.tar.gz... Failed. Status: 4;"A requested feature, protocol or option was not found built-in in this libcurl due to a build-time decision."
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:182 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:143 (vcpkg_download_distfile)
  ports/boost-compatibility/portfile.cmake:3 (vcpkg_from_github)
  scripts/ports.cmake:136 (include)


[DEBUG] cmd_execute_and_stream_data() returned 1 after   284273 us
Error: Building package boost-compatibility:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-compatibility:x86-windows
  Vcpkg version: 2020.11.12-nohash

Additionally, attach any relevant sections from the log files above.
[DEBUG] C:\Wayne\vcpkg\toolsrc\src\vcpkg\install.cpp(494)
[DEBUG] Exiting after 23031240 us (22995243 us)

**Comment by JonLiu1993** [comment]
@gwnet ，Just set them in you console.you can use command to set it. Example:

set http_proxy=http://localhost:1080
set http_proxy_user=user
set http_proxy_pass=pwd

**Comment by JonLiu1993** [comment]
@gwnet ,does this still be a problem for you?

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
