### ISSUE TITLE
Missing headers - OpenVDB/viewer

### ISSUE THREAD

**Issue by ranjeethmahankali** [microsoft/vcpkg#14694]
**Describe the bug**
the `include/openvdb/viewer` folder is missing.

**Environment**
- Windows

**To Reproduce**
1. ./vcpkg install openvdb:x64-windows-static

Everything is installed normally but the include director doesn't contain the `openvdb/viewer` folder.

**Expected behavior**
`openvdb/viewer` and the headers inside should be present

**Comment by JackBoosY** [comment]
According to the [official build script](https://github.com/AcademySoftwareFoundation/openvdb/blob/ac97c17ed88dcfb392a2262076a1c7b5056298a8/openvdb/openvdb/cmd/CMakeLists.txt#L157-L176):
```cmake
if(OPENVDB_BUILD_VDB_VIEW)
  find_package(OpenGL REQUIRED)


  if(WIN32)
    find_package(GLEW REQUIRED)
  endif()


  # wraps find_package(glfw3) and sets the glfw target
  include(OpenVDBGLFW3Setup)


  set(VDB_VIEW_SOURCE_FILES
    openvdb_view.cc
    ../viewer/Camera.cc
    ../viewer/ClipBox.cc
    ../viewer/Font.cc
    ../viewer/RenderModules.cc
    ../viewer/Viewer.cc
  )


  add_executable(vdb_view ${VDB_VIEW_SOURCE_FILES})
```
`openvdb_view` is defined as an executable, and the upstream doesn't install the related headers, I think this is reasonable.
