### ISSUE TITLE
[New Port Request] MoltenVK

### ISSUE THREAD

**Issue by Haeri** [microsoft/vcpkg#14698]
Library name: MoltenVK

Library description: MoltenVK is a Vulkan Portability implementation. It layers a subset of the high-performance, industry-standard Vulkan graphics and compute API over Apple's Metal graphics framework, enabling Vulkan applications to run on iOS and macOS.

Source repository URL: https://github.com/KhronosGroup/MoltenVK

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included): This project is Mac only as it is a platform that allows Vulkan to run on MacOS, iOS and tvOS. Having this will be very beneficial to making cross platform Vulkan applications.

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, and continue PR #14819.
