### ISSUE TITLE
[osg] Please add WIN32_USE_MP define for faster windows build

### ISSUE THREAD

**Issue by remoe** [microsoft/vcpkg#14695]
OSG windows build does not have a "WIN32_USE_MP" define.

https://github.com/openscenegraph/OpenSceneGraph/blob/50de0c25f70d251a000d7972d95e6c1d4249c7dd/CMakeLists.txt#L351

The build of osg take more than an hour on github actions.

**Comment by PhoebeHui** [comment]
@remoe, thanks for reporting this issue!

I have summited  PR #14718 to enable the option.

**Comment by remoe** [comment]
@PhoebeHui, ok thanks.
