### ISSUE TITLE
Workaround for huge dependecies that are not necessary

### ISSUE THREAD

**Issue by playgithub** [microsoft/vcpkg#14697]
When porting `poppler`, it depends on a small tool `clang-format.exe`.
`vcpkg install llvm[clang-tools-extra]` leads to 102GB in `vcpkg-root/buildtrees`.
A workaround is possible.

e.g. for x64
In official site, there are prebuilt binaries
`https://github.com/llvm/llvm-project/releases/download/llvmorg-11.0.0/LLVM-11.0.0-win64.exe`
in which `clang-format` can be extracted and executed alone.

While `vcpkg` depending on other binaries like `cmake-3.18.4-win32-x86.zip` / build toolchain / etc, why not depends on official binaries of `clang` only as executable tools to save 100GB disk space and a lot of time?

**Comment by JackBoosY** [comment]
Unless we provide the built binaries, we can only use dependencies. @strega-nil what do you think?

**Comment by strega-nil** [comment]
It seems likely that `poppler` shouldn't depend on clang-format..?

**Comment by playgithub** [comment]
> It seems likely that `poppler` shouldn't depend on clang-format..?

I did a experiment on this, the result is obvious, if I no `clang-foramt.exe` in system path, camke configure failed, otherwise succeeded.
`poppler` generates C/C++ code dynamically, I don't known what it does with `clang-format`, if only formatting generated code, a patch to remove the dependcy is ok.

BTW, the official prebuilt LLVM installer is about 180M, and:
> These binaries include Clang, LLD, compiler-rt, various LLVM tools, etc. varying slightly between platforms.
So use it and less patch is another choice.

**Comment by JackBoosY** [comment]
See https://github.com/freedesktop/poppler/blob/f4d640d7ad00b30797acce47299cf7a7a59ad505/CMakeLists.txt#L531-L536:
```cmake
        add_custom_command(OUTPUT poppler/${input}.c
                       COMMAND gperf poppler/${input}.gperf > ${CMAKE_CURRENT_BINARY_DIR}/poppler/${input}.c
                       COMMAND gperf poppler/${input}.gperf > ${CMAKE_CURRENT_SOURCE_DIR}/poppler/${input}.pregenerated.c
                       COMMAND clang-format -i ${CMAKE_CURRENT_SOURCE_DIR}/poppler/${input}.pregenerated.c || true
                       DEPENDS poppler/${input}.gperf
                       WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR})
```

**Comment by JackBoosY** [comment]
@playgithub Patches are necessary in most cases, but we can reduce it's size.

**Comment by playgithub** [comment]
However without `clang-format` it'll be hard when debugging.

**Comment by strega-nil** [comment]
Yeah, let's talk about it at the next meeting.

**Comment by strega-nil** [comment]
The agreement we've come to is that `llvm` should not be a dependency of poppler; if the user wishes to clang format the code, it could be installed on the machine and that'll be picked up by the `custom_command`, for debugging purposes; else, the `|| true` part of it will make it succeed anyways.

In the future, we may add `clang-format` to `vcpkg_find_acquire_program`, in which case this'll be fixed for good.

**Comment by JackBoosY** [comment]
@strega-nil  Agreed.
