### ISSUE TITLE
Powershell fails with "reparse point" error if vcpkg is on a subst drive

### ISSUE THREAD

**Issue by ras0219-msft** [microsoft/vcpkg#147]
Repro steps:
- Win7 machine without cmake installed
- vcpkg available at "D:\src\vcpkg"

Run the following:

```
C:\>subst J: D:\src\vcpkg
C:\>J:
J:\>vcpkg build expat
```

Powershell will fail with a reparse point error while trying to `Start-BitsTransfer`.

**Comment by linquize** [comment]
Now we should not use `vcpkg build` which is an internal command.

This issue is obsolete. When downloading a file, now we use cmake function instead of powershell function `Start-BitsTransfer`. Please close issue.
