### ISSUE TITLE
[gmp:x64-windows] build failure

### ISSUE THREAD

**Issue by MFunction96** [microsoft/vcpkg#14703]
**Host Environment**
- OS: Windows 10 Pro 20H2 (19042.630)
- Compiler: Visual Studio 2019 Version: 16.8.2 VS Tools Version: 14.28.29333

**To Reproduce**
`./vcpkg install gmp:x64-windows`

**Failure logs** 
```
PS E:\Program\vcpkg> ./vcpkg install gmp:x64-windows
Computing installation plan...
The following packages will be built and installed:
    gmp[core]:x64-windows
  * yasm-tool-helper[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Using cached binary package: C:\Users\MFunction\AppData\Local\vcpkg\archives\44\442d4788218915219c269b57dd0e041578cbd532.zip
Could not locate cached archive: C:\Users\MFunction\AppData\Local\vcpkg\archives\09\09f24f18b909a1ca88015dccf29162be083ad7f8.zip
Starting package 1/2: yasm-tool-helper:x64-windows
Building package yasm-tool-helper[core]:x64-windows...
Building package yasm-tool-helper[core]:x64-windows... done
Installing package yasm-tool-helper[core]:x64-windows...
Installing package yasm-tool-helper[core]:x64-windows... done
Elapsed time for package yasm-tool-helper:x64-windows: 30.47 ms
Starting package 2/2: gmp:x64-windows
Building package gmp[core]:x64-windows...
-- Using cached E:/Program/vcpkg/downloads/ShiftMediaProject-gmp-e140dfc8668e96d7e56cbd46467945adcc6b3cc4.tar.gz
-- Cleaning sources at E:/Program/vcpkg/buildtrees/gmp/src/adcc6b3cc4-2b6258d695.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/Program/vcpkg/downloads/ShiftMediaProject-gmp-e140dfc8668e96d7e56cbd46467945adcc6b3cc4.tar.gz
-- Applying patch vs.build.patch
-- Applying patch runtime.patch
-- Applying patch prefix.patch
-- Using source at E:/Program/vcpkg/buildtrees/gmp/src/adcc6b3cc4-2b6258d695.clean
CMake Error at installed/x64-windows/share/yasm-tool-helper/yasm-tool-helper.cmake:16 (message):
  Cross-targetting and x64 ports requiring yasm require the x86-windows
  yasm-tool to be available.  Please install yasm-tool:x86-windows first.
Call Stack (most recent call first):
  ports/gmp/portfile.cmake:19 (yasm_tool_helper)
  scripts/ports.cmake:136 (include)


Error: Building package gmp:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: gmp:x64-windows
  Vcpkg version: 2020.11.12-nohash

Additionally, attach any relevant sections from the log files above.
```

**Additional context**

I noticed that the issue https://github.com/microsoft/vcpkg/issues/13642 mentioned some x64 packages built by x86 compiler/linker/utilities and tools. I think it hasn't solved completely. If I install `yasm-tool:x86-windows` manually, the building will passed.

**Comment by NancyLi1013** [comment]
Hi @MFunction96 

Thanks for posting this issue.

Currently , you need to install `yasm-tool:x86-windows` manually, then you can continue building `gmp`.

Please refer to this comment https://github.com/microsoft/vcpkg/issues/14288#issuecomment-718969380, I think this may answer your question.

**Comment by dudantas** [comment]
I used ```./vcpkg install yasm-tool: x86-windows``` and then ```./vcpkg install gmp: x64-windows```
And it works, thanks

**Comment by NancyLi1013** [comment]
@dudantas 

Thanks for your feedback.

@MFunction96 

Please see the above comments to learn about the details.

**Comment by AlienLcb** [comment]
> 我用过，然后它有效，谢谢`./vcpkg install yasm-tool: x86-windows``./vcpkg install gmp: x64-windows`

it doesn't work on my PC.

**Comment by dg0yt** [comment]
@AlienLcb This issue was closed more than two years ago. The current version of port gmp doesn't use yasm.

**Comment by AlienLcb** [comment]
> @AlienLcb This issue was closed more than two years ago. The current version of port gmp doesn't use yasm.

thanks,maybe I occurred some new error.if you are intrested in my new question,the link as:https://github.com/microsoft/vcpkg/issues/14703#issuecomment-1747455408
