### ISSUE TITLE
[libtorrent] update to 1.2.11

### ISSUE THREAD

**Issue by glassez** [microsoft/vcpkg#14702]
Library name: libtorrent

New version number: 1.2.11

Other information that may be useful (release notes, etc...)
https://github.com/arvidn/libtorrent/releases/tag/v1.2.11

**Comment by JonLiu1993** [comment]
Relate to #14755

**Comment by NancyLi1013** [comment]
Hi @glassez 

Thanks for posting this issue.

`libtorrent `1.2.11 has been merged to master. Please update vcpkg to the latest version to use it.
