### ISSUE TITLE
[opengl] cross-compilation build failure

### ISSUE THREAD

**Issue by Nemirtingas** [microsoft/vcpkg#14708]
**Host Environment**
- OS: Linux Ubuntu 18.04
- Compiler: llvm + clang-cl 9

**To Reproduce**
`./vcpkg install glew`

**Failure logs** 
```
Cannot find Windows 10.0.18362.0 SDK.  File does not exist:
/clang_windows_sdk/winsdk/Lib\10.0.18362.0\um\x86\OpenGL32.Lib
```

**Additional context**
The file DOES exist but in a Linux path format (use / instead of \\)
`ll /clang_windows_sdk/winsdk/Lib/10.0.18362.0/um/x86/OpenGL32.Lib`

**Comment by JackBoosY** [comment]
https://github.com/microsoft/vcpkg/blob/42456b785a4508386f080ae8fad2642e056b747d/ports/opengl/portfile.cmake#L4-L11
This should be replaced by `file(TO_NATIVE_PATH <path> <out-var>)`

**Comment by Nemirtingas** [comment]
Does https://github.com/microsoft/vcpkg/blob/42456b785a4508386f080ae8fad2642e056b747d/ports/opengl/portfile.cmake#L39-L42 need to be replace as well ?

**Comment by JackBoosY** [comment]
@Nemirtingas I think so.

**Comment by Nemirtingas** [comment]
Do I also need to call file(TO_NATIVE_PATH ...) or can I just use the Unix path separator `/` ? DESTINATION use the Unix separator and looks fine.

**Comment by JackBoosY** [comment]
@Nemirtingas All path should be set as UNIX style, and if you are in Windows, it should be converted by `file(TO_NATIVE_PATH <path> <out-var>)`.

**Comment by Nemirtingas** [comment]
Is it something like this that you want ? https://github.com/Nemirtingas/vcpkg/tree/opengl_port_fix

**Comment by JackBoosY** [comment]
@Nemirtingas Yes, does it work?

**Comment by Nemirtingas** [comment]
I must test on Windows but it works on Unix as TO_NATIVE_PATH doesn't change anything on Unix'es ;)
