### ISSUE TITLE
[New Port Request] Festival

### ISSUE THREAD

**Issue by Rdna123** [microsoft/vcpkg#14700]
Library name:
Festival

Library description:
Festival offers a general framework for building speech synthesis systems as well as including examples of various modules. As a whole it offers full text to speech through a number APIs: from shell level, though a Scheme command interpreter, as a C++ library, and an Emacs interface. Festival is multi-lingual (currently English (US and UK) and Spanish are distributed but a host of other voices have been developed by others) though English is the most advanced.

Source repository URL:
https://github.com/festvox/festival

Project homepage (if different from the source repository):
http://festvox.org/festival/
Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
