### ISSUE TITLE
Why does have the tagged vcpkg a wrong version?

### ISSUE THREAD

**Issue by remoe** [microsoft/vcpkg#14709]
**Describe the bug**
vcpkg get a wrong version when one checkout the 2020.11 tag. The

https://github.com/microsoft/vcpkg/blob/2020.11/toolsrc/VERSION.txt

contains: 

"2020.06.15" 

**Environment**
- OS: windows
- Compiler: VS2019

**To Reproduce**
1. git clone -b '2020.11' --single-branch --depth 1 https://github.com/microsoft/vcpkg
2. cat vcpkg/toolsrc/VERSION.txt

**Expected behavior**

A correct version: "2020.11"

**Comments**

Additionally information about VERSION.txt:

https://github.com/microsoft/vcpkg/blob/6b97dbfce2159e40d71fb69b1fe05c822c43aa90/docs/tool-maintainers/layout.md#top-level

"This is updated whenever major changes are made to the vcpkg tool."

**Comment by NancyLi1013** [comment]
Hi @remoe 

Thanks for posting this issue.

@strega-nil 

Could you please help take a look? Is the version expected in tag 2020.11 and 2020.11-1 now? Or we need to update it?

**Comment by strega-nil** [comment]
@remoe yeah... we didn't do a good job updating the VERSION.txt. However, it's also not a thing that should be the same as the release tags. It's updated whenever we make updates to the tool, so it might be updated more or less frequently than those tags.

**Comment by remoe** [comment]
@strega-nil ok, but when one build vcpkg it should be possible to verify the runtime by using "vcpkg version". It is currently not possible to check the version that is started at runtime.

**Comment by strega-nil** [comment]
@remoe Yeah, we will make sure to fix this in the future. Thanks!

**Comment by NancyLi1013** [comment]
I think @strega-nil has answered the question. Closing this issue for now.
