### ISSUE TITLE
[New Port Request]  speech_tools

### ISSUE THREAD

**Issue by Rdna123** [microsoft/vcpkg#14701]
Library name:
speech_tools

Library description:
The Edinburgh speech tools system is a library of C++ classes, functions and utility programs that are frequently used in speech software. The system compiles to a single unix library .a file which can be linked with software. At present, C++ classes for several useful speech and language classes have been written, along with audio software and some basic signal processing software.

Source repository URL:
https://github.com/festvox/speech_tools

Project homepage (if different from the source repository):
http://www.cstr.ed.ac.uk/projects/speech_tools/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
