### ISSUE TITLE
[qt5] module "QtQuick.Dialogs" is not installed

### ISSUE THREAD

**Issue by Reveares** [microsoft/vcpkg#14712]
**Describe the bug**
While #14594 fixed a few bugs related to QML deployment I still get the error
```
QQmlApplicationEngine failed to load component
qrc:/main.qml:4:1: module "QtQuick.Dialogs" is not installed
```
when I do `import QtQuick.Dialogs 1.2` inside a QML file.

**To Reproduce**
1. `./vcpkg install qt5`
(`./vcpkg install qt5-declarative` should be enough in this case, but I tested with both to be sure)
2. `import QtQuick.Dialogs 1.2` inside a QML file.
3. Build & run project.

**Expected behavior**
All imports inside a qml file should be deployed to the output folder.

**Additional context**
Inside `{output path to binary}/qml/QtQuick` the Dialogs folder is indeed missing.

**Comment by JackBoosY** [comment]
cc @Neumann-A

**Comment by Neumann-A** [comment]
@JackBoosY: My only comment to that is to use `windeployqt` instead of vcpkg own deployment script for qt. This solves this issue as well as the translation issue.

**Comment by ooeygui** [comment]
@Reveares Just curious - did you implement a workaround?

**Comment by Reveares** [comment]
@ooeygui No, I'm not even sure how I got around the problem back then. But I ditched Qt sometimes ago.
I don't know if the problem still exists.
