### ISSUE TITLE
[New Port Request]  gnutls

### ISSUE THREAD

**Issue by odskinz488** [microsoft/vcpkg#14717]
Library name: GnuTLS

Library description: GnuTLS implements the TLS/SSL (Transport Layer Security aka Secure Sockets Layer) protocol.

Source repository URL: https://github.com/gnutls/gnutls

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by JackBoosY** [comment]
Duplicated to #14746.
