### ISSUE TITLE
[poco:libmariadb] build dependency missing

### ISSUE THREAD

**Issue by yuntong613** [microsoft/vcpkg#14713]
Used: master branch, WIN7 x64
cmd > vcpkg install poco[mariadb,netssl]
vcpkg can not build the PocoDataMySQL feature, how can i do?
[config-x86-windows-out.log](https://github.com/microsoft/vcpkg/files/5580832/config-x86-windows-out.log)

**Comment by JackBoosY** [comment]
Can you re-install libmariadb and try again? 

Thanks.

**Comment by yuntong613** [comment]
I remove all directories that the position of vcpkg installed file —— buildtrees,installed,packages,%localappdata%\vcpkg\archives 

Then run the install cmd
    cmd > `vcpkg install poco[netssl,mariadb]`

PocoDataMySQL feature didn't work

[libmariadb-config-x86-windows-out.log](https://github.com/microsoft/vcpkg/files/5587691/libmariadb-config-x86-windows-out.log)
[poco-config-x86-windows-out.log](https://github.com/microsoft/vcpkg/files/5587690/poco-config-x86-windows-out.log)

**Comment by JackBoosY** [comment]
@yuntong613  Can you provide the content in _VCPKG_ROOT/buildtrees/poco/src/hash.clean/CMakeLists.txt_ line 117-122?

On my machine it should be:
```cmake
if(ENABLE_DATA_MYSQL)
    find_package(libmysql)
    if (NOT libmysql_FOUND)
        find_package(unofficial-libmariadb CONFIG REQUIRED)
    endif()
endif()
```
Note there is no `REQUIRED` on `find_package(libmysql)`, so this issue shouldn't happend.

**Comment by yuntong613** [comment]
The file on my machine is the same with yours,but the error would happen every time.

[CMakeLists.txt](https://github.com/microsoft/vcpkg/files/5587973/CMakeLists.txt)

**Comment by JackBoosY** [comment]
Did you install libmysql manually before?

**Comment by yuntong613** [comment]
I create a new machine (WIN7 x64 with VS2017) on visualbox, clone the master branch, the error happened again

**Comment by JackBoosY** [comment]
Does `vcpkg-cmake-wrapper` exists on _VCPKG_ROOT/installed/x86-windows/share/libmysql_ ?

**Comment by yuntong613** [comment]
it didn‘t have the directory which named libmysql 
![image](https://user-images.githubusercontent.com/20533580/100188607-7fd6a180-2f25-11eb-8e3c-c835b24c0524.png)

**Comment by JackBoosY** [comment]
I found there is no error in configure log:
`CMake Warning at C:/GitRepository/vcpkg/scripts/buildsystems/vcpkg.cmake:622 (_find_package):`
That just a warning message.
Did you try `./vcpkg install poco[mysql]` instead?

**Comment by yuntong613** [comment]
mysql ports (MYSQL8) doesn't support x86.
On windows system, some program components only can run on x86, so I made my branch back to MYSQL 5.7, and poco[mysql] would always be well.
Now, I just want to try make poco by mariadb, it seems to be not possible on vcpkg.

**Comment by JackBoosY** [comment]
Confirmed.
