### ISSUE TITLE
Can't build folly on x64-uwp. (libevent fails to build)

### ISSUE THREAD

**Issue by JunielKatarn** [Microsoft/vcpkg#1472]
Package `folly` fails to build apparently due to one if its dependencies (`libevent`).

* Machine setup: Windows 10 Creators Update x64, en-us. Previously installed packages such as boost, cpprestsdk and beast (x64, windows and uwp) successfully.
* Steps to reproduce
  * Run `vcpkg install folly:x64-uwp`
  * The installation will fail with the following:
```
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:43 (message):
    Command failed: D:/Extra/react/vcpkg2017/downloads/cmake-3.8.0-win32-x86/bin/cmake.exe;--build;.;--config;Release;--target;install;--;/p:VCPkgLocalAppDataDisabled=true;/p:UseIntelMKL=No;/m
    Working Directory: D:/Extra/react/vcpkg2017/buildtrees/libevent/x64-uwp-rel
    See logs for more information:
      D:\Extra\react\vcpkg2017\buildtrees\libevent\package-x64-uwp-rel-out.log
      D:\Extra\react\vcpkg2017\buildtrees\libevent\package-x64-uwp-rel-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:49 (vcpkg_execute_required_process)
  ports/libevent/portfile.cmake:14 (vcpkg_install_cmake)
  scripts/ports.cmake:73 (include)


Error: Building package libevent:x64-uwp failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libevent:x64-uwp
  Vcpkg version: 0.0.81-2055a9cd4490861aa7ce9e1af23c0232f97552c9
```
* Package versions:
  * folly `v2017.05.08.00-2`
  * libevent `2.1.8-2`

Note, pulling the latest GitHub version and running `.\vcpkg update` didn't solve the problem.
Also note, the triplet for Windows desktop (libevent:x64-windows) builds fine. It's only Windows Universal that fails.

**Comment by ras0219-msft** [comment]
Thanks for opening this issue!

It's possible that libevent doesn't support UWP at all. Could you contribute your experience to https://github.com/libevent/libevent/issues/520 so the author can look at adding support?

**Comment by JunielKatarn** [comment]
Hi. I've just confirmed that folly does not yet support UWP. I don't know about libevent.

That said, isn't there a way to warn/fail on VCPKG when trying to build an unsupported triplet?

**Comment by ras0219-msft** [comment]
There is a way that we currently use, however we'd like to make it better in the future!

For now, we try to add checks at the beginning of the portfile to fail before trying to build the port. For example: a42da34a. However, this will build all its dependencies first before running the check, which wastes time if you really only care about the final library.

In the future, we'd like to add the ability to specify this in the CONTROL file, so the tool can determine up front whether the build will fail due to unsupported platform/architecture!
