### ISSUE TITLE
[vcpkg] [libxml2] 1) after installationg, the package is not found 2) include folder doesnt contain all files

### ISSUE THREAD

**Issue by proTerm** [microsoft/vcpkg#14726]
**Describe the bug**

**Environment**
- OS: Windows 10
- Compiler: Visual Studio 2017

**To Reproduce**
1)
1. `./vcpkg install libxml2 --triplet x64-windows-static`
2. See error
```
The package libxml2 is compatible with built-in CMake targets:

    find_package(LibXml2 REQUIRED)
    target_include_directories(main PRIVATE ${LIBXML2_INCLUDE_DIR})
    target_link_libraries(main PRIVATE ${LIBXML2_LIBRARIES})
```
However,
```
CMake Error at C:/Program Files/CMake/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find LibXml2 (missing: LIBXML2_LIBRARY LIBXML2_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.18/Modules/FindLibXml2.cmake:104 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:189 (find_package)
```
2) Besides, there is no win32config.h in the include directory

**Expected behavior**
find_package to function and win32config.h to be included

**Failure logs** 
-(please attached failure logs)

**Additional context**

**Comment by JackBoosY** [comment]
Did you use vcpkg toolchain?
Step:
1. `./vcpkg integrate install`
2. `-DCMAKE_TOOLCHAIN_FILE=PATH_TO_VCPKG_TOOL_CHAIN`
3. `-DVCPKG_TARGET_TRIPLET=x64-windows-static`

**Comment by proTerm** [comment]
> Did you use vcpkg toolchain?

I dont understand your question. The package installation fails, when: `./vcpkg install libxml2 --triplet x64-windows-static`

**Comment by JackBoosY** [comment]
According to the [official makefile](https://github.com/ConradIrwin/libxml2/blob/b368604d9ba04fec68dbc93733e1c2737766747e/win32/Makefile.msvc#L306),
I think that's a bug.

**Comment by Adela0814** [comment]
@proTerm This issue no longer occurs in the latest vcpkg version, please get the latest version and try again.
