### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by Andyloris** [microsoft/vcpkg#14731]
**Host Environment**
- OS: Windows
- Compiler: Latest

**To Reproduce**
Just run bootstrap-vcpkg.bat

**Failure logs** 
-Could not detect a Windows SDK / TargetPlatformVersion
-At C:\Users\Robert\Desktop\vcpkg-2020.11-1\vcpkg-2020.11-1\scripts\bootstrap.ps1:327 : 5
+     throw "Could not detect a Windows SDK / TargetPlatformVersion
    + CategoryInfo          : OperationStopped: (Could not detec...PlatformVersion:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not detect a Windows SDK / TargetPlatformVersion

**Comment by JonLiu1993** [comment]
Hi @Andyloris   thanks for posting this issue.
Could you help confirm whether you have installed Windows SDK in your visual studio?You can check this on your local and confirm whether there are Windows SDK.

`C:\Program Files (x86)\Windows Kits\`

If you don't install them before, you can open your Visual Studio Installer and enter Individual Components page to install. Generally, we install the latest version.

**Comment by Andyloris** [comment]
Yes i've installed it

**Comment by JonLiu1993** [comment]
@Andyloris ，Can you provide your recurring environment? Windows version, compiler version, windows SDK version you installed, and complete log, thank you! I cannot reproduce your problem on window10 and VS2017.Thanks

**Comment by PhoebeHui** [comment]
This should not be a problem now, we download vcpkg.exe rather than building it in bootstrap on windows now.
