### ISSUE TITLE
Manifest file not found with msbuild or Visual Studio

### ISSUE THREAD

**Issue by sipsorcery** [microsoft/vcpkg#14735]
**Describe the bug**

**Environment**
- OS: Windows 10 Pro 10.0.19041
- Compiler: revision: Visual Studio Community 2019 v16.8.2
Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29334 for x64 
- vcpkg checked out form `master`commit ID  `097a31d4c3127f38a6fbf4002122550dd9d39b84`

**To Reproduce**
1. Create a new C++ console application using the Visual Studio template.
2. Open the properties page for the C++ project and enable vcpkg manifests.
3. Create a `vcpkg.json` file in the same directory as the project file.
4. Add the minimal valid manifest contents:
````
{
  "name": "mypackage",
  "version-string": "0.1.0-dev"
}
````
5. Copy the `vcpkg.json` file to the immediate parent directory (resulting in a copy in the same directory as the project file and its immediate parent).
6. Click `Build`.

**Expected behavior**
The C++ console application to successfully compile.

**Failure logs** 
````
Build started...
1>------ Build started: Project: CppBuildTest, Configuration: Release x64 ------
1>C:\Tools\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(47,5): error : The Vcpkg manifest was enabled, but we couldn't find a manifest file (vcpkg.json) in any directories above C:\Users\aaron\source\repos\CppBuildTest. Please add a manifest, disable manifests in your properties page, or pass /p:VcpkgEnableManifest=false.
1>Done building project "CppBuildTest.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
````

**Additional context**
Reverting to commit ID `40230b8e3f6368dcb398d649331be878ca1e9007` (this is an arbitrary commit ID that was the last time I updated vcpkg) and the vcpkg manifest mechanism works as expected.

**Comment by ZhilkinSerg** [comment]
I suspect #12774 has something to do with that.

**Comment by JackBoosY** [comment]
@strega-nil Can you please take a look?

Thanks.

**Comment by strega-nil** [comment]
MMh, yeah, I'll fix this today. Thanks @ZhilkinSerg for root-causing this.
