### ISSUE TITLE
[vcpkg-gfortran:x64-windows] build failure

### ISSUE THREAD

**Issue by aberration213** [microsoft/vcpkg#14738]
**Host Environment**
- OS: Windows 10 
- Vcpkg version: 2020.11.12-nohash

**To Reproduce**
`./vcpkg install  vcpkg-gfortran[core]:x64-windows`

**Failure logs** 
Starting package 1/6: vcpkg-gfortran:x64-windows
Building package vcpkg-gfortran[core]:x64-windows...
-- The Fortran compiler identification is unknown
-- No Fortran compiler found on the PATH. Using MinGW gfortran!
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:106 (message):
    Command failed: C:/dir/vcpkg/downloads/tools/cmake-3.18.4-windows/cmake-3.18.4-win32-x86/bin/cmake.exe -E tar xzf C:/dir/vcpkg/downloads/msys-gawk-5.1.0-1-x86_64.pkg.tar.xz
    Working Directory: C:/dir/vcpkg/downloads/tools/msys2/1b7461e9cb3487d1.tmp
    Error code: 1
    See logs for more information:
      C:\dir\vcpkg\buildtrees\vcpkg-gfortran\msys-x64-windows-22-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_acquire_msys.cmake:507 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_find_fortran.cmake:67 (vcpkg_acquire_msys)
  ports/vcpkg-gfortran/portfile.cmake:3 (vcpkg_find_fortran)
  scripts/ports.cmake:136 (include)

Error: Building package vcpkg-gfortran:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: vcpkg-gfortran:x64-windows
  Vcpkg version: 2020.11.12-nohash

Additionally, attach any relevant sections from the log files above.

**Error Log**
CMake Error: Problem with archive_write_header(): Can't create '\\?\C:\dir\vcpkg\downloads\tools\msys2\1b7461e9cb3487d1.tmp\usr\bin\gawk.exe'
CMake Error: Current file: usr/bin/gawk.exe
CMake Error: Problem extracting tar: C:/dir/vcpkg/downloads/msys-gawk-5.1.0-1-x86_64.pkg.tar.xz

**Additional context**
I have tried deleting the vcpkg folders and reclone from the git repo. Same error.

**Comment by NancyLi1013** [comment]
Hi @aberration213 

Thanks for posting this issue.

Could you please try to remove `C:/dir/vcpkg/downloads/msys-gawk-5.1.0-1-x86_64.pkg.tar.xz` and `C:/dir/vcpkg/downloads/tools/msys2/1b7461e9cb3487d1.tmp` and rebuild this?

**Comment by NancyLi1013** [comment]
Could you please also provide the error info in` C:\dir\vcpkg\buildtrees\vcpkg-gfortran\msys-x64-windows-22-err.log`?

**Comment by aberration213** [comment]
> Hi @aberration213
> 
> Thanks for posting this issue.
> 
> Could you please try to remove `C:/dir/vcpkg/downloads/msys-gawk-5.1.0-1-x86_64.pkg.tar.xz` and `C:/dir/vcpkg/downloads/tools/msys2/1b7461e9cb3487d1.tmp` and rebuild this?

Hi @NancyLi1013 

I removed the two files and got the same error. The new logs are as below:

Starting package 1/1: vcpkg-gfortran:x64-windows
Building package vcpkg-gfortran[core]:x64-windows...
-- The Fortran compiler identification is unknown
-- No Fortran compiler found on the PATH. Using MinGW gfortran!
-- Downloading https://repo.msys2.org/msys/x86_64/gawk-5.1.0-1-x86_64.pkg.tar.xz...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:106 (message):
    Command failed: C:/dir/vcpkg/downloads/tools/cmake-3.18.4-windows/cmake-3.18.4-win32-x86/bin/cmake.exe -E tar xzf C:/dir/vcpkg/downloads/msys-gawk-5.1.0-1-x86_64.pkg.tar.xz
    Working Directory: C:/dir/vcpkg/downloads/tools/msys2/1b7461e9cb3487d1.tmp
    Error code: 1
    See logs for more information:
      C:\dir\vcpkg\buildtrees\vcpkg-gfortran\msys-x64-windows-22-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_acquire_msys.cmake:507 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_find_fortran.cmake:67 (vcpkg_acquire_msys)
  ports/vcpkg-gfortran/portfile.cmake:3 (vcpkg_find_fortran)
  scripts/ports.cmake:136 (include)


Error: Building package vcpkg-gfortran:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: vcpkg-gfortran:x64-windows
  Vcpkg version: 2020.11.12-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by aberration213** [comment]
> Could you please also provide the error info in` C:\dir\vcpkg\buildtrees\vcpkg-gfortran\msys-x64-windows-22-err.log`?

I have included the content of the log in the original post, but below is the log content:

CMake Error: Problem with archive_write_header(): Can't create '\?\C:\dir\vcpkg\downloads\tools\msys2\1b7461e9cb3487d1.tmp\usr\bin\gawk.exe'
CMake Error: Current file: usr/bin/gawk.exe
CMake Error: Problem extracting tar: C:/dir/vcpkg/downloads/msys-gawk-5.1.0-1-x86_64.pkg.tar.xz

[msys-x64-windows-22-err.log](https://github.com/microsoft/vcpkg/files/5591194/msys-x64-windows-22-err.log)

**Comment by NancyLi1013** [comment]
Thanks for your update.

Could you please try the solution mentioned here?

https://github.com/microsoft/vcpkg/issues/14300#issuecomment-719396447
https://github.com/microsoft/vcpkg/issues/1549#issuecomment-318437627

**Comment by aberration213** [comment]
> Thanks for your update.
> 
> Could you please try the solution mentioned here?
> 
> [#14300 (comment)](https://github.com/microsoft/vcpkg/issues/14300#issuecomment-719396447)
> [#1549 (comment)](https://github.com/microsoft/vcpkg/issues/1549#issuecomment-318437627)

I ticked the 8-bit and did the restart, that didn't help. But moving to another directory worked. Thanks!
