### ISSUE TITLE
[icu] build failure

### ISSUE THREAD

**Issue by mortezaahmadi1** [microsoft/vcpkg#14733]
**Host Environment**
- OS:  Windows
- Compiler: revision

**To Reproduce**
`./vcpkg install icu:x64-windows`

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

**Additional context**
-- Downloading http://download.icu-project.org/files/icu4c/61.1/icu4c-61_1-src.tgz...
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:99 (message):

  File does not have expected hash:

          File path: [ D:/BuildArea/vcpkg-master/downloads/temp/icu4c-61_1-src.tgz ]
      Expected hash: [ 4c37691246db802e4bae0c8c5f6ac1dac64c5753b607e539c5c1c36e361fcd9dd81bd1d3b5416c2960153b83700ccdb356412847d0506ab7782ae626ac0ffb94 ]
        Actual hash: [ 860815f2c342b9dc758602a85abcf408d130ec62fd2341f6cf85e764339858f9d3b8f806505463bf252708876431d0378354642940c6c3a35e1c5a7a2e63a57e ]

  The file may have been corrupted in transit.  This can be caused by
  proxies.  If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY
  environment variables to
  "https://user:password@your-proxy-ip-address:port/".

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:182 (test_hash)
  ports/icu/portfile.cmake:11 (vcpkg_download_distfile)
  scripts/ports.cmake:94 (include)

Error: Building package icu:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: icu:x64-windows
  Vcpkg version: 2019.09.12-nohash

**Comment by NancyLi1013** [comment]
Hi @mortezaahmadi1 

Thanks for posting this issue.

It seems that you didn't use the latest version to build.

`icu `has been updated to 67.1. Please use `git pull ` to update vcpkg to the latest version and then rebuild `icu`.

**Comment by NancyLi1013** [comment]
Closing this issue for no response. 

Please use the latest version to rebuild.
