### ISSUE TITLE
install nlohmann-json

### ISSUE THREAD

**Issue by aa9bb** [microsoft/vcpkg#14737]
**Environment**
- OS: Window10 x64
- Compiler: vs2019

**To Reproduce**
1. ./vcpkg install nlohmann-json
2. See error: 

_Downloading https://github.com/nlohmann/json/raw/v3.9.1/CMakeLists.txt... Failed. Status: 6;"Couldn't resolve host name"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:181 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  ports/nlohmann-json/portfile.cmake:7 (vcpkg_download_distfile)
  ports/nlohmann-json/portfile.cmake:16 (download_src)
  scripts/ports.cmake:79 (include)_
**Remark**
      **[https://github.com/nlohmann/json/raw/v3.9.1/CMakeLists.txt](https://github.com/nlohmann/json/raw/v3.9.1/CMakeLists.txt )**
  This link is indeed not accessible

**Comment by JonLiu1993** [comment]
@aa9bb  ,Thanks for posting this issue,This issue duplicate to #14585
