### ISSUE TITLE
vcpkg help prints non-existing `import` command

### ISSUE THREAD

**Issue by sipsorcery** [microsoft/vcpkg#14748]
**Describe the bug**
When attempting to use the `vcpkg import` command an error message stating `invalid command: import` is received.

**Environment**
- OS: Windows 10 Pro 10.0.19041
- Compiler:  Visual Studio Community 2019 v16.8.2
Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29334 for x64
 - vcpkg checked out form master commit ID 6e073f168652a551d8f29d19481ec67be3fccac8

**To Reproduce**
1. Checkout vcpkg source and build using `bootstrap-vcpkg.bat`
2. vcpkg import

**Expected behavior**
The `vcpkg import` command help text.

**Failure logs** 
````
c:\Tools\vcpkg>vcpkg export
Must provide at least one export type: --raw --nuget --ifw --zip --7zip --chocolatey --prefab
Example:
  vcpkg export zlib zlib:x64-windows boost --nuget

c:\Tools\vcpkg>vcpkg import
invalid command: import
````

**Comment by vicroms** [comment]
Hi @sipsorcery 

The exported libraries are to be imported by your projects, vcpkg does not provide an `import` command.

After running the export command you will get instructions on how to import the produced output into your project.
```
PS D:\vcpkg> ./vcpkg export rapidjson:x86-windows rapidjson:x64-windows --nuget
The following packages are already built and will be exported:
    rapidjson:x86-windows
    rapidjson:x64-windows
Exporting package rapidjson:x86-windows...
Exporting package rapidjson:x64-windows...
Packing nuget package...
NuGet package exported at: D:\vcpkg\vcpkg-export-20201125-025052.1.0.0.nupkg

With a project open, go to Tools->NuGet Package Manager->Package Manager Console and paste:
    Install-Package vcpkg-export-20201125-025052 -Source "D:\vcpkg"
```

If what you want is to share binaries built with vcpkg between multiple instances see our [binary caching documentation](https://github.com/microsoft/vcpkg/blob/master/docs/users/binarycaching.md#configuration).

**Comment by sipsorcery** [comment]
@vicroms ok thx for the info.

The issue then becomes that the `import` command is listed in the help usage.

````
> vcpkg
  ...
  vcpkg export <pkg>... [opt]...  Exports a package
  vcpkg edit <pkg>                Open up a port for editing (uses %EDITOR%, default 'code')
  vcpkg import <pkg>              Import a pre-built library
  vcpkg create <pkg> <url> [archivename]
 ````
