### ISSUE TITLE
[gdal] link failure

### ISSUE THREAD

**Issue by epiciskandar** [microsoft/vcpkg#14740]
**Host Environment**
- OS: Linux CentOS 7.8
- Compiler: gcc8.2 / vcpkg latest(HEAD commit: 6e073f168652a551d8f29d19481ec67be3fccac8)

**To Reproduce**
`./vcpkg install gdal`

**Failure logs** 
```
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:142 (message):
    Command failed: /usr/bin/make V=1 -j 9 -f GNUmakefile all
    Working Directory: /home/user/vcpkg/buildtrees/gdal/x64-linux-dbg
    See logs for more information:
      /home/user/vcpkg/buildtrees/gdal/build-x64-linux-dbg-out.log
      /home/user/vcpkg/buildtrees/gdal/build-x64-linux-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_make.cmake:186 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_make.cmake:24 (vcpkg_build_make)
  ports/gdal/portfile.cmake:200 (vcpkg_install_make)
  scripts/ports.cmake:136 (include)


Error: Building package gdal:x64-linux failed with: BUILD_FAILED
```

**Additional context**
the `buildtrees/gdal/build-x64-linux-dbg-err.log` file says lots of this error:
```
/home/user/vcpkg/installed/x64-linux/debug/lib/libcrypto.a(threads_pthread.o): In function `fork_once_func':
threads_pthread.c:(.text+0x16): undefined reference to `pthread_atfork'
collect2: error: ld returned 1 exit status
(many same error below)
...
```

I have tried add `-pthread` at the `GDALmake.opt` line 665,like:
```
LIBS = (blah...) -pthread
```
and execute make manually at this folder:
```
/usr/bin/make V=1 -j 9 -f GNUmakefile all
```
gdal will compile and link without error

**Comment by JackBoosY** [comment]
Could you provide the full log _buildtrees/gdal/build-x64-linux-dbg-err.log_ and _buildtrees/gdal/build-x64-linux-dbg-out.log_?

Thanks.

**Comment by epiciskandar** [comment]
[config-x64-linux-dbg-err.log](https://github.com/microsoft/vcpkg/files/5596364/config-x64-linux-dbg-err.log)
[config-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/5596365/config-x64-linux-dbg-out.log)
[build-x64-linux-dbg-err.log](https://github.com/microsoft/vcpkg/files/5596366/build-x64-linux-dbg-err.log)
[build-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/5596367/build-x64-linux-dbg-out.log)
👌

**Comment by JackBoosY** [comment]
On my machine:
```
checking for cryptopp... no
checking for crypto... checking for EVP_sha256 in -lcrypto... yes
checking openssl/bio.h usability... yes
checking openssl/bio.h presence... yes
checking for openssl/bio.h... yes
...
  cryptopp support:          no
  crypto/openssl support:    yes
```
But it didn't link to gdal locally. Don't know why.

**Comment by JackBoosY** [comment]
Related: #9068.

**Comment by Sjurk** [comment]
I have a similar, if not identical issue. Trying to install GDAL in vcpkg on Ubuntu 20.04.2 LTS after installing Boost, netcdf-c and netcdf-cpp4:

usr/local/vcpkg$ sudo ./vcpkg install gdal --recurse
Computing installation plan...
The following packages will be built and installed:
    gdal[core]:x64-linux -> 3.1.3#4
Detecting compiler hash for triplet x64-linux...
Could not locate cached archive: /root/.cache/vcpkg/archives/32/32b87dcdb3f937c05f44fb64b71d39b57f647aad.zip
Starting package 1/1: gdal:x64-linux
Building package gdal[core]:x64-linux...
-- Using cached /usr/local/vcpkg/downloads/gdal313.zip
-- Cleaning sources at /usr/local/vcpkg/buildtrees/gdal/src/gdal313-b1dafdc415.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /usr/local/vcpkg/downloads/gdal313.zip
-- Applying patch 0001-Fix-debug-crt-flags.patch
-- Applying patch 0002-Fix-build.patch
-- Applying patch 0003-Fix-static-build.patch
-- Applying patch 0004-Fix-std-fabs.patch
-- Applying patch 0005-Fix-cfitsio.patch
-- Using source at /usr/local/vcpkg/buildtrees/gdal/src/gdal313-b1dafdc415.clean
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Generating configure for x64-linux
-- Finished generating configure for x64-linux
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:146 (message):
    Command failed: /usr/bin/make V=1 -j 5 -f GNUmakefile all
    Working Directory: /usr/local/vcpkg/buildtrees/gdal/x64-linux-dbg
    See logs for more information:
      /usr/local/vcpkg/buildtrees/gdal/build-x64-linux-dbg-out.log
      /usr/local/vcpkg/buildtrees/gdal/build-x64-linux-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_make.cmake:195 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_make.cmake:26 (vcpkg_build_make)
  ports/gdal/portfile.cmake:208 (vcpkg_install_make)
  scripts/ports.cmake:142 (include)


Error: Building package gdal:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: gdal:x64-linux
  Vcpkg version: 2021-01-13-unknownhash

Additionally, attach any relevant sections from the log files above.

*** The requested files are:
[build-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/6339188/build-x64-linux-dbg-out.log)
[build-x64-linux-dbg-err.log](https://github.com/microsoft/vcpkg/files/6339190/build-x64-linux-dbg-err.log)

**Comment by JackBoosY** [comment]
@Sjurk  In configure:
```
if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
        _pkg_short_errors_supported=yes
else
        _pkg_short_errors_supported=no
fi
        if test $_pkg_short_errors_supported = yes; then
	        OGDI_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "ogdi"`
        else
	        OGDI_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "ogdi"`
        fi
	# Put the nasty error message in config.log where it belongs
	echo "$OGDI_PKG_ERRORS" >&5

	{ $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
$as_echo "no" >&6; }
                :
elif test $pkg_failed = untried; then
	:
else
	OGDI_CFLAGS=$pkg_cv_OGDI_CFLAGS
	OGDI_LIBS=$pkg_cv_OGDI_LIBS
        { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
$as_echo "yes" >&6; }
	HAVE_OGDI=yes
fi
  if test "$HAVE_OGDI" = yes; then
    OGDI_INCLUDE=$OGDI_CFLAGS
    LIBS="$OGDI_LIBS $LIBS"
  else
    for ac_header in ecs.h
do :
  ac_fn_c_check_header_mongrel "$LINENO" "ecs.h" "ac_cv_header_ecs_h" "$ac_includes_default"
if test "x$ac_cv_header_ecs_h" = xyes; then :
  cat >>confdefs.h <<_ACEOF
#define HAVE_ECS_H 1
_ACEOF

fi

done
```
Should add `--with-ogdi=no` or add `--with-ogdi=${SYSTEM_OGDI_PATH}`  to `vcpkg_configure_make`.

**Comment by dg0yt** [comment]
For my set of changes wrt #9068, I plan to use `--with-ogdi=no` (and many more `--with-...=no`) unless using feature "system-libraries". In fact, I picked up all `--with-...` from `configure.ac` a few hours ago.
To appear in #17698 in the next days.

**Comment by dg0yt** [comment]
#17698 was merged a while ago. Is this issue still valid?

**Comment by JackBoosY** [comment]
Please reopen this issue if it still exist.
