### ISSUE TITLE
[New Port Request] Ybalrid/kissnet

### ISSUE THREAD

**Issue by PhilippPaetzold** [microsoft/vcpkg#14742]
Library name:
Ybalrid/kissnet 

Library description:
A lightweight, header only, crossplatform C++17 socket library. Simple, intuitive to use.

Source repository URL:
https://github.com/Ybalrid/kissnet

Project homepage (if different from the source repository):
---

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
---

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
