### ISSUE TITLE
[New Port Request] gnutls

### ISSUE THREAD

**Issue by hyperionplus** [microsoft/vcpkg#14746]
Library name: GnuTLS

Library description: GnuTLS implements the TLS/SSL (Transport Layer Security aka Secure Sockets Layer) protocol.

Source repository URL: https://github.com/gnutls/gnutls

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by odskinz488** [comment]
can you please hurry up to port this library faster?!

**Comment by sfhacker** [comment]
It is my understanding that GNUTLS is already available! Not sure what's going on here?

**Comment by odskinz488** [comment]
so, you're wrong, cause it's not available
