### ISSUE TITLE
Working with both Windows and Linux packages

### ISSUE THREAD

**Issue by sloh-ms** [microsoft/vcpkg#14759]
Hello, I'm working on a project that builds both for Windows and for Linux.  I'm trying to consume some components from a Windows program (as source code) in our Windows/Linux project.  This program depends on some packages that are obtained via vcpkg; the people who built that repo simply checked-in the binaries obtained via vcpkg to their repo.  I'm trying to instead get them via nuget:
- Clone the vcpkg repo.
- Export a nuget package of Windows binaries, and a second nuget package of Linux binaries.
- Consume both nuget packages inside the Windows/Linux project, depending on the target OS.

I've had no problem getting the Windows work done.  But I can't figure out how to import the Linux binaries.  I'm a long-time Windows user and a newbie Linux user, so probably just misunderstanding something very basic.  I'm running WSL with Ubuntu 20.04.  In https://docs.microsoft.com/en-us/cpp/build/vcpkg?view=msvc-160#target-linux-from-windows-via-wsl it *looks* like I can clone the repo just once and use it for both OS'.  Inside WSL I can go to the vcpkg repo under /mnt/c/ (in my case, /mnt/c/repos/vcpkg) and successfully run ./bootstrap-vcpkg.sh.  But when I try the ./vcpkg.exe install command, it throws an error about the compiler.
```
[DEBUG] CreateProcessW("C:\repos\vcpkg\downloads\tools\cmake-3.18.4-windows\cmake-3.18.4-win32-x86\bin\cmake.exe" -DCURRENT_PORT_DIR=C:/repos/vcpkg/scripts/detect_compiler -DCURRENT_BUILDTREES_DIR=C:/repos/vcpkg/buildtrees/detect_compiler -DCURRENT_PACKAGES_DIR=C:/repos/vcpkg/packages/detect_compiler_x64-linux -DCMD=BUILD -DTARGET_TRIPLET=x64-linux "-DTARGET_TRIPLET_FILE=C:\repos\vcpkg\triplets\x64-linux.cmake" -DVCPKG_PLATFORM_TOOLSET=external -DDOWNLOADS=C:/repos/vcpkg/downloads -DVCPKG_CONCURRENCY=9 "-DGIT=C:/Program Files/Git/cmd/git.exe" -DVCPKG_ROOT_DIR=C:/repos/vcpkg -DPACKAGES_DIR=C:/repos/vcpkg/packages -DBUILDTREES_DIR=C:/repos/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=C:/repos/vcpkg/installed -DDOWNLOADS=C:/repos/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "C:\repos\vcpkg\scripts\ports.cmake")
[DEBUG] -- Configuring x64-linux
[DEBUG] CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:106 (message):
[DEBUG]     Command failed: ninja -v
[DEBUG]     Working Directory: C:/repos/vcpkg/buildtrees/detect_compiler/x64-linux-rel/vcpkg-parallel-configure
[DEBUG]     Error code: 1
[DEBUG]     See logs for more information:
[DEBUG]       C:\repos\vcpkg\buildtrees\detect_compiler\config-x64-linux-out.log
```
the .log file:
```
[1/1] cmd /c "cd .. && "C:/repos/vcpkg/downloads/tools/cmake-3.18.4-windows/cmake-3.18.4-win32-x86/bin/cmake.exe" "C:/repos/vcpkg/scripts/detect_compiler" "-DCMAKE_MAKE_PROGRAM=C:/repos/vcpkg/downloads/tools/ninja/1.10.1-windows/ninja.exe" "-DCMAKE_SYSTEM_NAME=Linux" "-DBUILD_SHARED_LIBS=OFF" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/repos/vcpkg/scripts/toolchains/linux.cmake" "-DVCPKG_TARGET_TRIPLET=x64-linux" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=external" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/repos/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_LINKER_FLAGS_RELEASE=" "-DVCPKG_LINKER_FLAGS_DEBUG=" "-DVCPKG_TARGET_ARCHITECTURE=x64" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=C:/repos/vcpkg" "-D_VCPKG_INSTALLED_DIR=C:/repos/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=C:/repos/vcpkg/packages/detect_compiler_x64-linux""
FAILED: ../CMakeCache.txt 
cmd /c "cd .. && "C:/repos/vcpkg/downloads/tools/cmake-3.18.4-windows/cmake-3.18.4-win32-x86/bin/cmake.exe" "C:/repos/vcpkg/scripts/detect_compiler" "-DCMAKE_MAKE_PROGRAM=C:/repos/vcpkg/downloads/tools/ninja/1.10.1-windows/ninja.exe" "-DCMAKE_SYSTEM_NAME=Linux" "-DBUILD_SHARED_LIBS=OFF" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/repos/vcpkg/scripts/toolchains/linux.cmake" "-DVCPKG_TARGET_TRIPLET=x64-linux" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=external" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/repos/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_LINKER_FLAGS_RELEASE=" "-DVCPKG_LINKER_FLAGS_DEBUG=" "-DVCPKG_TARGET_ARCHITECTURE=x64" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=C:/repos/vcpkg" "-D_VCPKG_INSTALLED_DIR=C:/repos/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=C:/repos/vcpkg/packages/detect_compiler_x64-linux""
-- The C compiler identification is unknown
CMake Error at CMakeLists.txt:11 (enable_language):
  No CMAKE_C_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.

-- Configuring incomplete, errors occurred!
```
I've set these environment variables:
```
  export VCPKG_DEFAULT_TRIPLET=x64-linux
  export VCPKG_PLATFORM_TOOLSET=v142
  export CC=gcc
  export CXX=g++
```
But it *looks* like the code is running Windows tools - like that CreateProcess on "C:\repos\vcpkg\downloads\tools\cmake-3.18.4-windows\cmake-3.18.4-win32-x86\bin\cmake.exe" - that's calling out to Windows.

Did I do this wrong?  Do I need to clone the repo a second time inside WSL in order to import packages for Linux?  I've looked all over the MSDN doc above plus https://github.com/microsoft/vcpkg/blob/master/docs/index.md and haven't found the details I need for how to work with Linux *in WSL*.  Thanks for the help with my newbie question.

**Comment by sloh-ms** [comment]
Oh, gosh, the command is still running, but I think I have the answer.  I was so close - but I shouldn't call "./vcpkg.exe install" from inside Linux.  I should call "./vcpkg install" (without the .exe extension).

**Comment by JackBoosY** [comment]
@strega-nil Any ideas?
@sloh-ms By using different vcpkg binaries, ports under different platforms will be built according to different compilers.

**Comment by sloh-ms** [comment]
Thanks @JackBoosY, yeah having separate compilers is going to happen for sure.  That's expected.

Reporting back: using "./vcpkg" instead of "./vcpkg.exe" appears to have worked.  I did get a number of messages during the install like
```
sh: 1: zip: not found
Failed to store binary cache /home/sloh/.cache/vcpkg/archives/ce/ce68db8e056a815087b2e74d682e6787ef8a14fe.zip: Invalid cross-device link
```
But they appear to be benign.  The binaries were built and I was able to export a nuget package containing all of the Linux binaries.  The export likewise failed to find those cached .zip files, so the whole process is probably a lot slower than it should be.  But at least it works.

I've got a separate failure on making a nuget package that I hesitate to morph this thread with.
```
Could not automatically acquire mono because there is no entry in /mnt/c/repos/vcpkg/scripts/vcpkgTools.xml for os=linux. You may be able to install mono via your system package manager.
```
**Rather than solve either of the above here,** I just want to end with one last question -- **is my approach valid?**  Am I doing a reasonable thing by sharing the same repo for building both Windows and Linux, or should I be using two separate copies of the repo?

**Comment by strega-nil** [comment]
@sloh-ms it's absolutely valid. It's not necessarily a tested configuration, but it's something I do all the time. If you run into any bugs, please open issues :)

**Comment by strega-nil** [comment]
Also, you should really install `zip` via `sudo apt install zip`, because otherwise you don't get binary caching.

On the nuget issue, yes, you should probably open an issue about that. We should be able to export nuget packages for linux.

**Comment by sloh-ms** [comment]
Thank you for the confirmation!  I've already done the zip install, and am working on getting the nuget export to work.  I'll open an issue if I am stuck.
