### ISSUE TITLE
[New Port Request] Open3d

### ISSUE THREAD

**Issue by JanKovis** [microsoft/vcpkg#14751]
Library name: Open3d

Library description: A Modern Library for 3D Data Processing

Source repository URL: https://github.com/intel-isl/Open3D

Project homepage (if different from the source repository): http://www.open3d.org/docs/release/index.html

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by JackBoosY** [comment]
Duplicated to #11950.
