### ISSUE TITLE
Building package expat:x64-osx failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by WilliamZkl** [microsoft/vcpkg#14757]
**Describe the bug**
Building package expat:x64-osx failed with: BUILD_FAILED
Package: expat:x64-osx
Vcpkg version: 2020.11.12-unknownhash

**Environment**
- OS: macOS
- Compiler: C

**To Reproduce**
1. ./vcpkg install readosm
2. See error
CMake Error at scripts/cmake/vcpkg_find_acquire_program.cmake:533 (message):
  Could not find pkg-config.  Please install it via your package manager:
      brew install pkg-config
Call Stack (most recent call first):
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:272 (vcpkg_find_acquire_program)
  ports/expat/portfile.cmake:30 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:136 (include)

Error: Building package expat:x64-osx failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: expat:x64-osx
  Vcpkg version: 2020.11.12-unknownhash
Additionally, attach any relevant sections from the log files above.

**Expected behavior**
I hope to see the solutions to solve this error and build the package expat:x64-osx successfully.

**Failure logs** 
Error: Building package expat:x64-osx failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: expat:x64-osx
  Vcpkg version: 2020.11.12-unknownhash
Additionally, attach any relevant sections from the log files above.

**Additional context**
I want to use the Vcpkg to install the 'readosm' for Visual Studio Code because the includepath doesn't include <dos.h>.

**Comment by Hoikas** [comment]
```
Could not find pkg-config. Please install it via your package manager:
brew install pkg-config
```

**Comment by JonLiu1993** [comment]
@WilliamZkl ,Please install pkg-config first, make sure vcpkg is the latest version, and then rebuild

**Comment by longhuan2018** [comment]
If you want to use readosm in osx, you can try this PR #14951

**Comment by PhoebeHui** [comment]
@WilliamZkl, please reopen this issue if it still be a problem for you.
