### ISSUE TITLE
[Boost]  Problems when downloading the strawberry-perl-5.30.0.1-32bit.zip

### ISSUE THREAD

**Issue by mingy532** [microsoft/vcpkg#14766]
****
when download boost,it depend on strawberry-perl-5.30.0.1-32bit.zip,But it has expired
-- Downloading https://strawberry.perl.bot/download/5.30.0.1/strawberry-perl-5.30.0.1-32bit.zip...
-- Downloading https://strawberry.perl.bot/download/5.30.0.1/strawberry-perl-5.30.0.1-32bit.zip... Failed. Status: 22;"HTTP response code said error"
-- Downloading http://strawberryperl.com/download/5.30.0.1/strawberry-perl-5.30.0.1-32bit.zip...

I tried to download it manually and saw
https://strawberry.perl.bot/download/5.30.0.1/strawberry-perl-5.30.0.1-32bit.zip
404 Not Found

So I had to go to http://strawberryperl.com/release-notes/5.30.1.1-32bit.html to download it myself, but I don’t know
"USE_64_BIT_INT enabled"
What does it mean, and the download is slow, can someone update these and tell me whether to choose a version that supports USE_64_BIT_INT enabled or not?
**Is your feature request related to a problem? Please describe.**

**Proposed solution**

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered if applicable.

**Additional context**

**Comment by StarGate-One** [comment]
Looks like https://strawberry.perl.bot site is not working correctly - maybe due to the aws outtage????
Anyway, you can download https://strawberry.perl.bot/download/5.30.0.1/strawberry-perl-5.30.0.1-32bit.zip and put the file in the directory `[vcpkg-root]\downloads` and run `.\vcpkg.exe install [boost ports]` again.

**Comment by PhoebeHui** [comment]
@mingy532, the http://strawberryperl.com/download/5.30.0.1/strawberry-perl-5.30.0.1-32bit.zip is working now, could you please try to install the port again?

**Comment by mingy532** [comment]
Sorry, I have manually downloaded it from http://strawberryperl.com/release-notes/5.30.1.1-32bit.html and the installation was successful,
By the way, what does USE_64_BIT_INT enabled mean and what is the difference?

**Comment by PhoebeHui** [comment]
@mingy532, the option used when building your own perl, since we're using the pre-built perl, so we don't care that option.
It seems the version that you used is newer than the one in vcpkg, I recommand to use the version in vcpkg since it has been test, and all known issue fixed before upgrade.

See https://stackoverflow.com/questions/29770286/perl-activestate-how-to-set-integer-variable-to-32-bit-width-on-windows-x64

**Comment by mingy532** [comment]
thanks,I has download the correct version and it work find.

**Comment by StarGate-One** [comment]
@mingy532 cc @PhoebeHui 
1. The version used by vcpkg is 5.30.0.1:
https://github.com/microsoft/vcpkg/blob/539a182d3773b9a84807b978c9684ba471446bf4/scripts/cmake/vcpkg_find_acquire_program.cmake#L65-L75

**2. I guess the bigger question is why vcpkg did not fail over to the backup site in line 74 when the site in line 73 failed?**

**Comment by mingy532** [comment]
Hello, when I was installing boost, it did prompt me that downloading version 5.30.0.1 failed, and the progress bar kept stuck:
  Downloading http://strawberryperl.com/download/5.30.0.1/strawberry-perl-5.30.0.1-32bit.zip...
It was my mistake. I chose the wrong version 5.30.1.1-32bit during manual download. After half an hour, I found out and chose the correct version.
I did not "try to install boost again" as mentioned here
https://github.com/microsoft/vcpkg/issues/14766#issuecomment-734049412
Instead, the manually installed version 5.30.0.1-32bit is still used.

When I tried to install for the first time, the link displayed in the terminal
https://strawberry.perl.bot/download/5.30.0.1/strawberry-perl-5.30.0.1-32bit.zip page does show
404 Not Found nginx/1.14.2
And it remains the same to this day.
>I guess the bigger question is why vcpkg did not fail over to the backup site in line 74 when the site in line 73 failed?

No, it did try to access the alternate website, but the alternate website has never responded.

**Comment by xavier2k6** [comment]
@PhoebeHui VCPKG uses `strawberry-perl 5.30.0.1`, why wasn't it updated to `strawberry-perl 5.32.1.1`?

Few others behind in revisions too like `nuget` 5.5.1 **VS** 5.10.0 etc.

**Comment by PhoebeHui** [comment]
@xavier2k6, I reported a new issue to track instead.

**Comment by xavier2k6** [comment]
> @xavier2k6, I reported a new issue to track instead.

Thank you, I didn't open an issue myself as I thought there may have been a reason to keep them at those versions.

#### Here's a list of the rest that are behind:
GIT_VERSION 2.26.2 -> 2.32.0
PYTHON_VERSION 3.9.5 -> 3.9.6
RubyInstaller-2.6.3-1 -> 2.7.3-1 **Or** RubyInstaller-3.0.1-1
MESON_VERSION 0.58.0 -> 0.58.1
SCONS_VERSION 3.0.1 -> 4.1.0
DOXYGEN_VERSION 1.8.17 -> 1.9.1
BAZEL_VERSION 3.7.0 -> 4.1.0
ARIA2_VERSION 1.34.0 -> 1.35.0
LLVM 10.0.0 -> 10.0.1 **Or** LLVM 12.0.0

**Comment by xavier2k6** [comment]
In relation to aria2 found in `scripts/vcpkgTools.xml`

Inconsistencies:

`<version>18.01.0</version>`
`<archiveName>aria2-1.33.1-win-32bit-build1.zip</archiveName>`

ref.:
https://github.com/microsoft/vcpkg/blob/master/scripts/vcpkgTools.xml#L122:L127
