### ISSUE TITLE
[boost:x64-win] build failure

### ISSUE THREAD

**Issue by granger35** [microsoft/vcpkg#14778]
**Host Environment**
- OS: Windows 10
- Compiler: Package: boost-build:x64-windows
Vcpkg version: 2020.11.12-nohash

**To Reproduce**
`./vcpkg install boost:x64-windows`

**Failure logs** 
```
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:106 (message):
    Command failed: F:/Dev/vcpkg/packages/boost-build_x64-windows/tools/boost-build/bootstrap.bat msvc
    Working Directory: F:/Dev/vcpkg/packages/boost-build_x64-windows/tools/boost-build
    Error code: 1
```

**boostrap-x64-windows-err.log:**
```
Building the B2 engine..
Call_If_Exists "bin\VCVARS32.BAT"
###
### Using 'msvc' toolset.
###

F:\Dev\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine>cl /nologo /MP /MT /TP /Feb2 /wd4996 /O2 /GL   -DNDEBUG  builtins.cpp class.cpp command.cpp compile.cpp constants.cpp cwd.cpp debug.cpp debugger.cpp execcmd.cpp execnt.cpp filent.cpp filesys.cpp frames.cpp function.cpp glob.cpp hash.cpp hcache.cpp hdrmacro.cpp headers.cpp jam.cpp jamgram.cpp lists.cpp make.cpp make1.cpp md5.cpp mem.cpp modules.cpp native.cpp object.cpp option.cpp output.cpp parse.cpp pathnt.cpp pathsys.cpp regexp.cpp rules.cpp scan.cpp search.cpp jam_strings.cpp startup.cpp subst.cpp sysinfo.cpp timestamp.cpp variable.cpp w32_getreg.cpp modules/order.cpp modules/path.cpp modules/property-set.cpp modules/regex.cpp modules/sequence.cpp modules/set.cpp /link kernel32.lib advapi32.lib user32.lib 

F:\Dev\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine>dir *.exe 
 
Folder of F:\Dev\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine


F:\Dev\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine>copy /b .\b2.exe .\bjam.exe 
The specified file cannot be found.

Failed to build the B2 engine.
```

**Additional context**
Seems similar to issue "bootstrap build failure [#8537](https://github.com/microsoft/vcpkg/issues/8537)"

**Comment by PhoebeHui** [comment]
@granger35, could you try following steps and see if some errors occurred?

1. Open x64 Native Tools command
2. pushd F:\Dev\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine
3. Execute build.bat
4. Check if b2.exe and bjam.exe generated correctly

**Comment by granger35** [comment]
b2.exe and bjam.exe generated correctly:

```
F:\Dev\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine>copy /b .\b2.exe .\bjam.exe
        1 file(s) copied.
```

b2.exe and bjam.exe are present in F:\Dev\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine

**Comment by PhoebeHui** [comment]
How about ./vcpkg install boost-build:x64-windows now?

That means the b2.exe and bjam.exe could generated correctly, it might be removed by anti-virus software.

**Comment by granger35** [comment]
Hi,
./vcpkg install boost:x64-windows failed. 
But, looking at the warnings, the english language package was missing for VC. After installing it, boost installed well. Did you see a causal link ? Behaviour tested on two machines with French language package installed, same issue, and everything has work well after english package installation.

**Comment by PhoebeHui** [comment]
@granger35, thanks for sharing the solution here!

English package is required when using vcpkg, it cause some unexpect failures without installing it. Glad you have figured out the solution.
