### ISSUE TITLE
[devil] Installation procedure doesn't print any instructions how to use DevIL

### ISSUE THREAD

**Issue by HappySeaFox** [microsoft/vcpkg#14773]
****

**Is your feature request related to a problem? Please describe.**
Installation procedure doesn't print any instructions how to use DevIL in client applications.

**Proposed solution**
Print information how to use DevIL in client applications like other libs do.

**Describe alternatives you've considered**
Diving into installed files and attempt to use pkg-config directly (with no luck because of another issue)

**Additional context**
-

**Comment by NancyLi1013** [comment]
Hi @smoked-herring 

Thanks for posting this issue.

Currently, there are no config and targets CMake files for `devil`, so it doesn't have usage like this.
```
find_package() 
target_link_libraries()
```

**Comment by smoked-herring** [comment]
It would be great to print instructions for non-CMake libs as well. For example, for pkg-config-based like that:

```
set(PKG_CONFIG_EXECUTABLE ".../pkg-config.exe")
find_package(PkgConfig REQUIRED)

pkg_check_modules(IL IMPORTED_TARGET REQUIRED IL)

target_compile_options(main PRIVATE ...)
target_include_directories(main PRIVATE ...)
target_link_libraries(main ...)
```

**Comment by NancyLi1013** [comment]
@smoked-herring 

Sorry for my misunderstanding. This issue should be related with how to use `pkg-config` in vcpkg.

**Comment by JackBoosY** [comment]
Duplicated to https://github.com/microsoft/vcpkg/discussions/17450.
