### ISSUE TITLE
[SDL2] SYSTEM_LIBRARIES missing

### ISSUE THREAD

**Issue by comedinha** [microsoft/vcpkg#14779]
Many users are having problems with SDL2 build because SYSTEM_LIBRARIES are not being sent.

On mingw-w64 static the error is:
```
-- Using msys root at C:/vcpkg-test/downloads/tools/msys2/c809757c94447846
-- Fixing pkgconfig file: C:/vcpkg-test/packages/sdl2_x64-mingw-static/lib/pkgconfig/sdl2.pc
CMake Error at scripts/cmake/vcpkg_fixup_pkgconfig.cmake:235 (message):
  Unhandled string "-mwindows" was found! If it is a system library use the
  SYSTEM_LIBRARIES parameter for the vcpkg_fixup_pkgconfig call! Otherwise,
  correct the *.pc file or add the case to vcpkg_fixup_pkgconfig
Call Stack (most recent call first):
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:299 (vcpkg_fixup_pkgconfig_check_files)
  ports/sdl2/portfile.cmake:101 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:136 (include)


Error: Building package sdl2:x64-mingw-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: sdl2:x64-mingw-static
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above
```

I can only build the SDL2 if I put the required libraries for mingw
`SYSTEM_LIBRARIES dbus-1 mwindows mingw32 dxerr8 m SDL2dmain SDL2
`

But, this is not the correct way to fix, other related issues show many systems with the same problem.
Is it possible make vcpkg_fixup_pkgconfig auto add these libraries required from all systems?

Related issues:
https://github.com/microsoft/vcpkg/issues/14598
https://github.com/microsoft/vcpkg/issues/13963
https://github.com/microsoft/vcpkg/issues/12998

**Comment by longnguyen2004** [comment]
I'll take a look

**Comment by comedinha** [comment]
> I'll take a look. `-mwindows` shouldn't be in there.
> By the way, it is the correct fix for this case. `mingw32`, `dxerr8` and others are system libraries, which should be put into SYSTEM_LIBRARIES, `-mwindows` however, is not related to libraries, but is used to set the subsystem, so it should be put in IGNORE_FLAGS.

"Unhandled string "-mwindows" was found!", the -mwindows is required for build with mingw,

**Comment by longnguyen2004** [comment]
I mean `-mwindows` should be in IGNORE_FLAGS as it's not related to library dependencies.
Your `vcpkg_fixup_pkgconfig` should be like this:
```
vcpkg_fixup_pkgconfig(
    IGNORE_FLAGS "-Wl,-rpath,${CURRENT_PACKAGES_DIR}/lib/pkgconfig/../../lib" "-Wl,-rpath,${CURRENT_PACKAGES_DIR}/debug/lib/pkgconfig/../../lib" "-Wl,--enable-new-dtags" "-Wl,--no-undefined" "-Wl,-undefined,error" "-Wl,-compatibility_version,${DYLIB_COMPATIBILITY_VERSION}" "-Wl,-current_version,${DYLIB_CURRENT_VERSION}" "-Wl,-weak_framework,Metal" "-Wl,-weak_framework,QuartzCore" "-mwindows"
    SYSTEM_LIBRARIES dbus-1 mingw32 dxerr8 m
)
```

If you can, please create a PR, I'm working on getting #14556 merged at the moment

**Comment by comedinha** [comment]
> I mean `-mwindows` should be in IGNORE_FLAGS as it's not related to library dependencies.
> Your `vcpkg_fixup_pkgconfig` should be like this:
> 
> ```
> vcpkg_fixup_pkgconfig(
>     IGNORE_FLAGS "-Wl,-rpath,${CURRENT_PACKAGES_DIR}/lib/pkgconfig/../../lib" "-Wl,-rpath,${CURRENT_PACKAGES_DIR}/debug/lib/pkgconfig/../../lib" "-Wl,--enable-new-dtags" "-Wl,--no-undefined" "-Wl,-undefined,error" "-Wl,-compatibility_version,${DYLIB_COMPATIBILITY_VERSION}" "-Wl,-current_version,${DYLIB_CURRENT_VERSION}" "-Wl,-weak_framework,Metal" "-Wl,-weak_framework,QuartzCore" "-mwindows"
>     SYSTEM_LIBRARIES dbus-1 mingw32 dxerr8 m
> )
> ```
> 
> If you can, please create a PR, I'm working on getting #14556 merged at the moment
> 
> For someone working on `vcpkg_fixup_pkgconfig`: Can we only check flags starting with `-l`? This would prevent having to specify a bunch of flags like what happened in `sdl2`.

This change not work, SDL2 libraries is required.
```
CMake Error at scripts/cmake/vcpkg_fixup_pkgconfig.cmake:233 (message):
  Library "SDL2dmain" was not found! If it is a system library use the
  SYSTEM_LIBRARIES parameter for the vcpkg_fixup_pkgconfig call! Otherwise,
  correct the *.pc file
```

**Comment by longnguyen2004** [comment]
This is tricky...SDL2main is in the manual-link folder, because it redefines `main`, which can cause problems if it's linked automatically. But since that's mostly about Visual Studio integration, I'm gonna open another issue about this.

**Comment by longnguyen2004** [comment]
I realized...the library name is `SDL2maind`, not `SDL2dmain`. I'll fix this when I have time
