### ISSUE TITLE
[V8] vcpkg should display a warning

### ISSUE THREAD

**Issue by Mempler** [microsoft/vcpkg#14783]
**Is your feature request related to a problem? Please describe.**
V8 fails if Windows 10 SDK version 10.0.19041.0 is not installed.

**Proposed solution**
If vcpkg doesn't detect that `Windows 10 SDK version 10.0.19041.0` is installed
it should throw either an error or display a warning to prevent further confusion

**Platform**
* [x] Windows
  * [x] x86
  * [x] x64
* [ ] Linux
  * [ ] x86
  * [ ] x64
* [ ] MacOS
  * [ ] x86
  * [ ] x64

**Comment by JackBoosY** [comment]
Does this issue related to #14593?

**Comment by Mempler** [comment]
Might be, can't really tell cause I haven't got a response from the Author. But given that I had the exact same error, it's most likely related to that.

**Comment by Adela0814** [comment]
@Mempler Does this problem still exist?

**Comment by MonicaLiu0311** [comment]
V8 has been updated to `9.1.269.39#5`,  if it is still an issue, please reopen.
