### ISSUE TITLE
Cannot build VTK static lib because qt5 does not support static libs

### ISSUE THREAD

**Issue by FrankHeimes** [microsoft/vcpkg#1478]
VTK has a dependency on qt5. Building a static lib for VTK fails because qt5 currently does not support static libs:
```
vcpkg install vtk:x86-windows-static
The following packages will be built and installed:
  * qt5:x86-windows-static
    vtk:x86-windows-static
Additional packages (*) will be installed to complete this operation.
Building package qt5:x86-windows-static... 
-- CURRENT_INSTALLED_DIR=D:/GitHub/vcpkg/installed/x86-windows-static
-- DOWNLOADS=D:/GitHub/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=D:/GitHub/vcpkg/packages/qt5_x86-windows-static
-- CURRENT_BUILDTREES_DIR=D:/GitHub/vcpkg/buildtrees/qt5
-- CURRENT_PORT_DIR=D:/GitHub/vcpkg/ports/qt5/.
CMake Error at ports/qt5/portfile.cmake:11 (message):
  Qt5 doesn't currently support static builds.  Please use a dynamic triplet instead.
```
I succeeded (as far as I can tell) to remove the qt5 dependency by these two changes:
1. Removed the `qt5` entry in `vcpkg\ports\vtk\CONTROL`
2. Modified `-DVTK_Group_Qt=OFF` in `vcpkg\ports\vtk\portfile.cmake`

But now the build fails with different errors. According to `vcpkg/buildtrees/vtk/x86-windows-static-rel/CMakeFiles/CMakeError.log`, the HDF5 "hack" in `vcpkg\ports\vtk\portfile.cmake` doesn't seem to work either:
```
CMake Error at CMake/NewCMake/FindPackageHandleStandardArgs.cmake:147 (message):
  Could NOT find HDF5 (missing: HDF5_LIBRARIES HDF5_HL_LIBRARIES C) (found
  version "1.10.0.1")
Call Stack (most recent call first):
  CMake/NewCMake/FindPackageHandleStandardArgs.cmake:387 (_FPHSA_FAILURE_MESSAGE)
  CMake/NewCMake/FindHDF5.cmake:773 (find_package_handle_standard_args)
  CMake/FindHDF5.cmake:7 (include)
  CMake/vtkModuleMacros.cmake:864 (find_package)
  ThirdParty/hdf5/CMakeLists.txt:1 (vtk_module_third_party)
```
So I also removed `hdf5` from the `CONTROL` file and changed `-DVTK_USE_SYSTEM_HDF5=OFF` in the `portfile.cmake` files mentioned above.

Now the build seems to complete at least.

**Comment by sarthakpati** [comment]
Is there any way we can build VTK statically while linking to a dynamically built version of Qt (licensing issues)?

**Comment by degski** [comment]
@sarthakpati Thank Richard Stallman for the fabulous (L)GPL, we have free software, but not that free. Having said that, I do think it's intended purpose (GNU/linux) is good and proper (nobody should appropriate himself the linux kernel or GNU software). The problem comes when frameworks like Qt (and many others) start using this infectious license, they shouldn't.

**Comment by sarthakpati** [comment]
@degski actually, I did manage to get this to work properly using the following doc: https://github.com/Microsoft/vcpkg/blob/master/docs/users/triplets.md

**Comment by NancyLi1013** [comment]
Hi @FrankHeimes, thanks for posting this issue. Qt5 has supported static build. VTK can be installed successfully now. Please update and try it again.
