### ISSUE TITLE
Please improve 'vcpkg search'

### ISSUE THREAD

**Issue by gvanem** [microsoft/vcpkg#14788]
Currently `vcpkg search pattern` gives all kinds of hits unrelated to library name(s) as the
`vcpkg search --help` indicates: 
`The argument should be a substring to search for, or no argument to display all libraries.`

I read this as a *substring* should match the library name only.  

Now with e.g. `vcpkg search ares` (and combined with grep to give colours), I get these hits:

![vcpkg-search-1](https://user-images.githubusercontent.com/945271/100316239-5e73c500-2fba-11eb-87d6-202cda09a3ea.png)

How useful is it to match `ares` against `Nearest` and `squares`? 

I would request a more powerfull and precise fnmatch-style instead. Like:  `vcpkg search  lib[a-c]*`. 
Returning something like:
```
libaaplus           2.12-1         libaaplus is an astronomical computations library by naughter software
...
libcroco            0.6.13#2       A standalone css2 parsing and manipulation library
libcuckoo           0.3            A high-performance, concurrent hash table
```

**Comment by strega-nil** [comment]
This seems like two features in one request:

* Adding regex search to `vcpkg search`
* Adding an option to only search names.

These are both reasonable features, however it's unlikely to be done by us since it's lower-prio. If you're interested, we'd accept patches to add these :)

**Comment by gvanem** [comment]
> .... however it's unlikely to be done by us since it's lower-prio.

Sorry about the late reply, but what!! "*lower-prio*" according to who/what?

Okay  lets just stay with the traditional sloppy cmd-line handling Microsoft uses.

**Comment by strega-nil** [comment]
@gvanem it's lower-prio for us to implement compared to registries and versioning; we don't have unlimited time, and while this would be a nice-to-have, it's not blocking anyone. We are very willing to help anybody interested in implementing this, of course, since this is an open source project.
