### ISSUE TITLE
Typos in CONTROL files

### ISSUE THREAD

**Issue by gvanem** [microsoft/vcpkg#14787]
A quick search through the `CONTROL` files shows these **libary** typos:
 * `ports\ebml\CONTROL`: Description: a C++ **libary** to parse EBML files
 * `ports\gppanel\CONTROL`: Description: gpPanel is chart **libary** for wxWidget. It inheritance from wxPanel and ...
 * `ports\matroska\CONTROL`: Description: a C++ **libary** to parse Matroska files (.mkv and .mka)
 * `ports\polyhook2\CONTROL`: Description: C++17, x86/x64 Hooking **Libary** v2.0
 * `ports\unrar\CONTROL`: Description: rarlab's unrar **libary**

Should be easy to fix.

**Comment by NancyLi1013** [comment]
Hi @gvanem 

Thanks for posting this issue.

We will update these typos later.

**Comment by gvanem** [comment]
And what about `composable`? Used in: 
  * `ports\bfgroup-lyra\CONTROL`: Description: A simple to use, **composable**, command line parser for C++ 11 and beyond
  * `ports\wangle\CONTROL`: Description: Wangle is ... building services in a consistent, modular, and **composable way**.

Yuk!

**Comment by vicroms** [comment]
The instances of "composable" come directly from the upstream library descriptions.

As a matter of policy, we don't usually accept PRs whose only purpose is to fix typos:

https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#avoid-trivial-changes-in-untouched-files
