### ISSUE TITLE
[sdl2-image] SDL2_Image should also import SDL2

### ISSUE THREAD

**Issue by smoked-herring** [microsoft/vcpkg#14789]
****

**Is your feature request related to a problem? Please describe.**
If I use the printed instructions to include sdl2-image, project generation fails with

```
  Target "main" links to target "SDL2::SDL2" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
```

Instructions used:

```
    find_package(sdl2-image CONFIG REQUIRED)
    target_link_libraries(main PRIVATE SDL2::SDL2_image)
```

**Proposed solution**
Fix the sdl2-image configs to also import `SDL2`.

**Describe alternatives you've considered**
Import `SDL2` manually like that:

```
    find_package(sdl2 CONFIG REQUIRED)
    find_package(sdl2-image CONFIG REQUIRED)
    target_link_libraries(main PRIVATE SDL2::SDL2_image)
```

**Additional context**

**Comment by JackBoosY** [comment]
Confirmed.
