### ISSUE TITLE
pistache:x64-windows build failure

### ISSUE THREAD

**Issue by ishaantantra** [microsoft/vcpkg#14808]
**Host Environment**
- OS: Windows x64
- Compiler: Visual Studios 2019

**To Reproduce**
`vcpkg install pistache`

**Failure logs** 
Computing installation plan...
The following packages will be built and installed:
    pistache[core]:x64-windows
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\Admin\AppData\Local\vcpkg\archives\8d\8d0e6ada36d58e3456c7b7db067b037b7bb74dc0.zip
Starting package 1/1: pistache:x64-windows
Building package pistache[core]:x64-windows...
CMake Error at ports/pistache/portfile.cmake:2 (message):
  pistache currently only supports Linux platform.
Call Stack (most recent call first):
  scripts/ports.cmake:136 (include)

Error: Building package pistache:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: pistache:x64-windows
  Vcpkg version: 2020.11.12-nohash

Additionally, attach any relevant sections from the log files above.

 .\vcpkg update
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.

 git pull
warning: Pulling without specifying how to reconcile divergent branches is
discouraged. You can squelch this message by running one of the following
commands sometime before your next pull:

  git config pull.rebase false  # merge (the default strategy)
  git config pull.rebase true   # rebase
  git config pull.ff only       # fast-forward only

You can replace "git config" with "git config --global" to set a default
preference for all repositories. You can also pass --rebase, --no-rebase,
or --ff-only on the command line to override the configured default per
invocation.

Already up to date.

**Comment by JonLiu1993** [comment]
@ishaantantra ,Thanks for posting this issue,Currently pistache does not support the windows platform, if you have a need, you can contact the official pistache staff.

**Comment by PhoebeHui** [comment]
The pistache currrently only support linux on official, please report an issue to Upstream instead.
