### ISSUE TITLE
How do I can check system version in CONTROL file or static build of realsense2 under windows 7 and binary caching.

### ISSUE THREAD

**Issue by xandox** [microsoft/vcpkg#14810]
Hi all. 

There is a port of Intel librealsense2 library. It depends on some usb library. When building it under windows 10 it use builtin USB API and everything is ok. But when building under windows 7 (for example) it starts depend on libusb, but in CONTROL file libusb set as dependence only for not windows built. librealsense2 itself resolve this problem and plug libusb as cmake external project but libusb libraries will not be installed in `vcpkg_installed` directory and will leave in `vcpkg/buildtrees` and paths to them will be hardcoded in `realsense2Config.cmake`. However it still works till you would to use binary caching. 

My IMHO said that eases way to fix that is check system version in CONTROL file, but it's not possible now (as far I can see). Is any possible solutions set libusb as dependency if target system version less then windows 10?

**Comment by PhoebeHui** [comment]
@xandox, from https://github.com/IntelRealSense/librealsense/blob/master/src/win7/CMakeLists.txt. it seems that if USE_EXTERNAL_USB enabled, then it would depend on libusb, currently, we haven't enable it, so it should not been required to build under win7. Do you encounter some failures on win7?

**Comment by xandox** [comment]
>Do you encounter some failures on win7?

Problem only with binary caching.

>LINK : fatal error LNK1104: cannot open file '..\..\..\vcpkg\buildtrees\realsense2\x64-windows-rel\libusb_install\lib\usb.lib' >[C:\Jenkins\workspace\project\build\project.vcxproj]

>it seems that if USE_EXTERNAL_USB enabled, then it would depend on libusb, currently, we haven't enable it, so it should not been required to build under win7.


Unfortunately this is not full picture. The library can't be built without any usb api. So. They include [libusb_config.cmake](https://github.com/IntelRealSense/librealsense/blob/master/CMake/libusb_config.cmake) in 11 line in [win7/CMakeLists.txt](https://github.com/IntelRealSense/librealsense/blob/master/src/win7/CMakeLists.txt) this config checks is libusb could be found and if not they include [external_libusb.cmake](https://github.com/IntelRealSense/librealsense/blob/master/CMake/external_libusb.cmake) which do [set(USE_EXTERNAL_USB ON)](https://github.com/IntelRealSense/librealsense/blob/master/CMake/external_libusb.cmake#L28)

**Comment by PhoebeHui** [comment]
I see, I will take a look, thanks for reporting this issue!

**Comment by PhoebeHui** [comment]
It also has another usage issue, and confirm with librealsense team https://github.com/IntelRealSense/librealsense/issues/7947, and would fix them togather.

**Comment by JackBoosY** [comment]
Please reopen this issue when it is fixed upstream.
