### ISSUE TITLE
[New port request] ArduinoJson

### ISSUE THREAD

**Issue by ishaantantra** [microsoft/vcpkg#14811]
Library name:

1. ArduinoJson
2. croncpp

Library description:

1. ArduinoJson is a C++ JSON library for Arduino and IoT (Internet Of Things)
2. croncpp is a C++11/14/17 header-only cross-platform library for handling CRON expressions. It implements two basic operations: parsing an expression and computing the next occurence of the scheduled time

Source repository URL:

1. https://github.com/bblanchon/ArduinoJson
2. https://github.com/mariusbancila/croncpp

Project homepage (if different from the source repository):

1. https://arduinojson.org/

**Comment by JackBoosY** [comment]
Hi @ishaantantra, vcpkg already includes `croncpp`, please use command `./vcpkg install croncpp` to install it.

Thanks.

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
