### ISSUE TITLE
i have error,libfontconfig-1.dll not found,when i installed gtkmm , how can i fix this?

### ISSUE THREAD

**Issue by zhiwi1** [microsoft/vcpkg#14818]
When asking a question please also include where you looked for an answer (so we can update the documentation if needed).

**Comment by PhoebeHui** [comment]
@zhiwi1, could you remove fontconfig and rebuild it again?

**Comment by PhoebeHui** [comment]
I suspect the issue occured when using the package, it should build fine, duplicated of same issue with https://github.com/microsoft/vcpkg/issues/14944.
