### ISSUE TITLE
[New Port Request] partio

### ISSUE THREAD

**Issue by ZP-Z** [microsoft/vcpkg#14829]
Library name: partio

Library description: Computer graphics library from *Walt Disney Animation Studios*. An open-source C++ library for reading, writing and manipulating a variety of standard particle formats (GEO, BGEO, PTC, PDB, PDA).

Source repository URL: https://github.com/wdas/partio

Project homepage (if different from the source repository): http://partio.us/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
