### ISSUE TITLE
[opencv4:x64-windows] build failure

### ISSUE THREAD

**Issue by gitmehelp** [microsoft/vcpkg#14826]
**Host Environment**
- OS: Windows 10
- Compiler: Microsoft (R) Windows (R) Resource Compiler Version 10.0.10011.16384

GPU is RTX 2060

Error: Building package opencv4:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: opencv4:x64-windows
  Vcpkg version: 2020.11.12-nohash

**To Reproduce**
`.\vcpkg install darknet[full]:x64-windows`

**Failure logs** 
Starting package 1/5: opencv4:x64-windows
Building package opencv4[contrib,core,cuda,dnn,ffmpeg,jpeg,opengl,png,tiff,webp]:x64-windows...
-- Using cached C:/vcpkg/downloads/opencv-opencv-4.3.0.tar.gz
-- Cleaning sources at C:/vcpkg/buildtrees/opencv4/src/4.3.0-8460981b10.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg/downloads/opencv-opencv-4.3.0.tar.gz
-- Applying patch 0001-disable-downloading.patch
-- Applying patch 0002-install-options.patch
-- Applying patch 0003-force-package-requirements.patch
-- Applying patch 0004-fix-policy-CMP0057.patch
-- Applying patch 0006-jpeg2000_getref.patch
-- Applying patch 0009-fix-uwp.patch
-- Applying patch 0010-fix-interface_link_libraries.patch
-- Using source at C:/vcpkg/buildtrees/opencv4/src/4.3.0-8460981b10.clean
-- Using cached C:/vcpkg/downloads/opencv-cache/tiny_dnn/adb1c512e09ca2c7a6faef36f9c53e59-v1.0.0a3.tar.gz
-- Using cached C:/vcpkg/downloads/opencv-cache/nvidia_optical_flow/ca5acedee6cb45d0ec610a6732de5c15-79c6cee80a2df9a196f20afd6b598a9810964c32.zip
-- Using cached C:/vcpkg/downloads/opencv-opencv_contrib-4.3.0.tar.gz
-- Cleaning sources at C:/vcpkg/buildtrees/opencv4/src/4.3.0-795a2a992f.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg/downloads/opencv-opencv_contrib-4.3.0.tar.gz
-- Applying patch 0005-add-missing-stdexcept-include.patch
-- Using source at C:/vcpkg/buildtrees/opencv4/src/4.3.0-795a2a992f.clean
-- Using cached C:/vcpkg/downloads/opencv-cache/xfeatures2d/boostdesc/0ea90e7a8f3f7876d450e4149c97c74f-boostdesc_bgm.i
-- Using cached C:/vcpkg/downloads/opencv-cache/xfeatures2d/boostdesc/232c966b13651bd0e46a1497b0852191-boostdesc_bgm_bi.i
-- Using cached C:/vcpkg/downloads/opencv-cache/xfeatures2d/boostdesc/324426a24fa56ad9c5b8e3e0b3e5303e-boostdesc_bgm_hd.i
-- Using cached C:/vcpkg/downloads/opencv-cache/xfeatures2d/boostdesc/202e1b3e9fec871b04da31f7f016679f-boostdesc_binboost_064.i
-- Using cached C:/vcpkg/downloads/opencv-cache/xfeatures2d/boostdesc/98ea99d399965c03d555cef3ea502a0b-boostdesc_binboost_128.i
-- Using cached C:/vcpkg/downloads/opencv-cache/xfeatures2d/boostdesc/e6dcfa9f647779eb1ce446a8d759b6ea-boostdesc_binboost_256.i
-- Using cached C:/vcpkg/downloads/opencv-cache/xfeatures2d/boostdesc/0ae0675534aa318d9668f2a179c2a052-boostdesc_lbgm.i
-- Using cached C:/vcpkg/downloads/opencv-cache/xfeatures2d/vgg/e8d0dcd54d1bcfdc29203d011a797179-vgg_generated_48.i
-- Using cached C:/vcpkg/downloads/opencv-cache/xfeatures2d/vgg/7126a5d9a8884ebca5aea5d63d677225-vgg_generated_64.i
-- Using cached C:/vcpkg/downloads/opencv-cache/xfeatures2d/vgg/7cd47228edec52b6d82f46511af325c5-vgg_generated_80.i
-- Using cached C:/vcpkg/downloads/opencv-cache/xfeatures2d/vgg/151805e03568c9f490a5e3a872777b75-vgg_generated_120.i
-- Using cached C:/vcpkg/downloads/opencv-cache/data/7505c44ca4eb54b4ab1e4777cb96ac05-face_landmark_model.dat
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:142 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j13
    Working Directory: C:/vcpkg/buildtrees/opencv4/x64-windows-dbg
    See logs for more information:
      C:\vcpkg\buildtrees\opencv4\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:93 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/opencv4/portfile.cmake:369 (vcpkg_install_cmake)
  scripts/ports.cmake:136 (include)

Error: Building package opencv4:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: opencv4:x64-windows
  Vcpkg version: 2020.11.12-nohash

[8/1160] cmd.exe /C "cd /D C:\vcpkg\buildtrees\opencv4\x64-windows-dbg\modules\core\CMakeFiles\cuda_compile_1.dir\src\cuda && "C:\Program Files\CMake\bin\cmake.exe" -E make_directory C:/vcpkg/buildtrees/opencv4/x64-windows-dbg/modules/core/CMakeFiles/cuda_compile_1.dir/src/cuda/. && "C:\Program Files\CMake\bin\cmake.exe" -D verbose:BOOL=OFF -D build_configuration:STRING=Debug -D generated_file:STRING=C:/vcpkg/buildtrees/opencv4/x64-windows-dbg/modules/core/CMakeFiles/cuda_compile_1.dir/src/cuda/./cuda_compile_1_generated_gpu_mat.cu.obj -D generated_cubin_file:STRING=C:/vcpkg/buildtrees/opencv4/x64-windows-dbg/modules/core/CMakeFiles/cuda_compile_1.dir/src/cuda/./cuda_compile_1_generated_gpu_mat.cu.obj.cubin.txt -P C:/vcpkg/buildtrees/opencv4/x64-windows-dbg/modules/core/CMakeFiles/cuda_compile_1.dir/src/cuda/cuda_compile_1_generated_gpu_mat.cu.obj.Debug.cmake"
FAILED: modules/core/CMakeFiles/cuda_compile_1.dir/src/cuda/cuda_compile_1_generated_gpu_mat.cu.obj 
cmd.exe /C "cd /D C:\vcpkg\buildtrees\opencv4\x64-windows-dbg\modules\core\CMakeFiles\cuda_compile_1.dir\src\cuda && "C:\Program Files\CMake\bin\cmake.exe" -E make_directory C:/vcpkg/buildtrees/opencv4/x64-windows-dbg/modules/core/CMakeFiles/cuda_compile_1.dir/src/cuda/. && "C:\Program Files\CMake\bin\cmake.exe" -D verbose:BOOL=OFF -D build_configuration:STRING=Debug -D generated_file:STRING=C:/vcpkg/buildtrees/opencv4/x64-windows-dbg/modules/core/CMakeFiles/cuda_compile_1.dir/src/cuda/./cuda_compile_1_generated_gpu_mat.cu.obj -D generated_cubin_file:STRING=C:/vcpkg/buildtrees/opencv4/x64-windows-dbg/modules/core/CMakeFiles/cuda_compile_1.dir/src/cuda/./cuda_compile_1_generated_gpu_mat.cu.obj.cubin.txt -P C:/vcpkg/buildtrees/opencv4/x64-windows-dbg/modules/core/CMakeFiles/cuda_compile_1.dir/src/cuda/cuda_compile_1_generated_gpu_mat.cu.obj.Debug.cmake"
nvcc fatal   : Unsupported gpu architecture 'compute_30'
CMake Error at cuda_compile_1_generated_gpu_mat.cu.obj.Debug.cmake:220 (message):
  Error generating
  C:/vcpkg/buildtrees/opencv4/x64-windows-dbg/modules/core/CMakeFiles/cuda_compile_1.dir/src/cuda/./cuda_compile_1_generated_gpu_mat.cu.obj

[9/1160] cmd.exe /C "cd /D C:\vcpkg\buildtrees\opencv4\x64-windows-dbg\modules\core && "C:\Program Files\CMake\bin\cmake.exe" -DMODULE_NAME=core -DCL_DIR=C:/vcpkg/buildtrees/opencv4/src/4.3.0-8460981b10.clean/modules/core/src/opencl -DOUTPUT=C:/vcpkg/buildtrees/opencv4/x64-windows-dbg/modules/core/opencl_kernels_core.cpp -P C:/vcpkg/buildtrees/opencv4/src/4.3.0-8460981b10.clean/cmake/cl2cpp.cmake"
ninja: build stopped: subcommand failed.

**Comment by gitmehelp** [comment]
GPU is RTX 2060

**Comment by sfhacker** [comment]
@gitmehelp Are you ok?
Are we **still** having issues building opencv or darknet?

**Comment by gitmehelp** [comment]
> 
> 
> @gitmehelp Are you ok?
> Are we **still** having issues building opencv or darknet?

I tried a bunch of things and this morning it is now working.  I am not sure what all the issues were.

Probably one of the issues is that I needed to change the darknet Makefile to use the right GPU settings.  I have a GeForce RTX 2060 (which should use the 75 setting), so I uncommented the following ARCH definition:

# GeForce RTX 2080 Ti, RTX 2080, RTX 2070, Quadro RTX 8000, Quadro RTX 6000, Quadro RTX 5000, Tesla T4, XNOR Tensor Cores
ARCH= -gencode arch=compute_75,code=[sm_75,compute_75]

Thanks for checking in on me.
