### ISSUE TITLE
[pthreads] build failure with community triplet x64-windows-static-md

### ISSUE THREAD

**Issue by zaddach** [microsoft/vcpkg#14823]
**Host Environment**
- OS: x64-windows-static-md
- Compiler: VS2019

**To Reproduce**
`./vcpkg install pthreads:x64-windows-static-md`

**Failure logs** 
```
-- Extracting source C:/dev/vcpkg/downloads/pthreads4w-code-v3.0.0.zip
-- Using source at C:/dev/vcpkg/buildtrees/pthreads/src/49e541b66c-bb03a1deb3.clean
-- Building x64-windows-static-md-rel
-- Building x64-windows-static-md-rel done
-- Building x64-windows-static-md-dbg
-- Building x64-windows-static-md-dbg done
-- Installing: C:/dev/vcpkg/packages/pthreads_x64-windows-static-md/share/pthreads/copyright
-- Performing post-build validation
Expected Debug,Dynamic crt linkage, but the following libs had invalid crt linkage:

    C:/dev/vcpkg/packages/pthreads_x64-windows-static-md/debug/lib/pthreadVC3d.lib: Debug,Static
    C:/dev/vcpkg/packages/pthreads_x64-windows-static-md/debug/lib/pthreadVCE3d.lib: Debug,Static
    C:/dev/vcpkg/packages/pthreads_x64-windows-static-md/debug/lib/pthreadVSE3d.lib: Debug,Static

To inspect the lib files, use:
    dumpbin.exe /directives mylibfile.lib
Expected Release,Dynamic crt linkage, but the following libs had invalid crt linkage:

    C:/dev/vcpkg/packages/pthreads_x64-windows-static-md/lib/pthreadVC3.lib: Release,Static
    C:/dev/vcpkg/packages/pthreads_x64-windows-static-md/lib/pthreadVCE3.lib: Release,Static
    C:/dev/vcpkg/packages/pthreads_x64-windows-static-md/lib/pthreadVSE3.lib: Release,Static

To inspect the lib files, use:
    dumpbin.exe /directives mylibfile.lib
Found 2 error(s). Please correct the portfile:
    C:\dev\vcpkg\ports\pthreads\portfile.cmake
```

**Additional context**
I'm trying to use the Cargo vcpkg module to find a vcpkg library. This module uses the `x64-windows-static-md` by default.

**Comment by sfhacker** [comment]
It is my understanding that pthreads comes with your environment when it is installed and set up!
You shouldn't need to build pthreads at all. Perhaps your environment is broken?
Which project are you trying to build (provide an URL to download please) which depends on pthreads?
Cheers.

**Comment by longnguyen2004** [comment]
> It is my understanding that pthreads comes with your environment when it is installed and set up!
> You shouldn't need to build pthreads at all. Perhaps your environment is broken?
> Which project are you trying to build (provide an URL to download please) which depends on pthreads?
> Cheers.

This is MSVC, not mingw

**Comment by robbie-li** [comment]
I have the same issue when I try to install podofo which depends on pthreads4w

**Comment by longnguyen2004** [comment]
Unfortunately a lot of ports simply don't work with `static-md` at the moment, and it would take a while for everything to be sorted out. For the meantime, please use `static`, or go with full dynamic linking.

**Comment by JonLiu1993** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
