### ISSUE TITLE
Something in vcpkg seems to be interfering with Visual Studio 2019's contextual drop down menu for Managing Configurations

### ISSUE THREAD

**Issue by prithvidiamond1** [microsoft/vcpkg#14820]
**Describe the bug**
vcpkg seems to be interfering with Visual Studio 2019's contextual drop down menu for Managing Configurations. What I mean by this is, if you open a folder with miscellaneous or standalone source files that are not a part of any Visual Studio 2019 Projects or Solutions that also has vcpkg, then there will be no way for you to Manage Configurations in Visual Studio 2019 as the contextual drop down menu which should be available in the Visual Studio 2019's tool bar, will not appear. Instead it will look like this:

![image](https://user-images.githubusercontent.com/46743102/100497465-c3c5e280-3181-11eb-964f-c2ac13b94180.png)

**Environment**
- OS: [Windows 10 20H2]
- Visual Studio Installation: Visual Studio 2019 version 16.8.2 with the following installation packages:

![image](https://user-images.githubusercontent.com/46743102/100497610-99285980-3182-11eb-9899-8bfd8dec465a.png)

I also have the following Extensions installed in Visual Studio 2019:

![image](https://user-images.githubusercontent.com/46743102/100497637-d42a8d00-3182-11eb-9866-eedf67f3c910.png)

Note: The Auto Save file extension is disabled for other reasons, I don't think it is involved in this issue.

**To Reproduce**
1. git clone the vcpkg into the folder you wish to open as your working directory in Visual Studio 2019
2. Now open Visual Studio 2019 and choose to open the same folder where you cloned vcpkg
3. Notice that you can not access ```Manage Configuration``` setting in the tool bar.

**Expected behavior**
The tool bar should have appeared like this:

![image](https://user-images.githubusercontent.com/46743102/100497716-5024d500-3183-11eb-8610-aad274a32d64.png)

**Failure logs** 
There are no logs for this as Visual Studio 2019 isn't reporting this as an error and so the log files are empty.

**Additional context**
This problem occurred when I just wanted to edit some C++ source files that are not a part of any Projects or Solutions. This problem took me 4 days to figure out and was figured out thanks to [this](https://stackoverflow.com/questions/65021677/how-to-get-intellisense-working-on-standalone-c-source-files-in-visual-studio) StackOverflow question by me and Answer by user Barnett Chou. You might be wondering why I didn't report this as a bug of Visual Studio 2019, well that is because it shouldn't matter as both are intellectual property of Microsoft and while I know that these are probably handled by separate dev teams in Microsoft, reporting on Github allows me to provide information than on Microsoft's more clunky Report a Bug thing for Visual Studio 2019. I am reporting this in the interest of others, so that others don't waste hours of their time like me. Please fix this at the earliest as this could very well put off less experienced programmers and end-users.

**Comment by JackBoosY** [comment]
@strega-nil Could you please take a look?

Thanks.

**Comment by strega-nil** [comment]
I think this is a VS bug, and I do _not_ understand VS in any way shape or form. If you like, I can open an issue on their bug tracker for you, but this isn't a thing we have any real understanding of.

**Comment by prithvidiamond1** [comment]
> I think this is a VS bug, and I do _not_ understand VS in any way shape or form. If you like, I can open an issue on their bug tracker for you, but this isn't a thing we have any real understanding of.

Oh ok, fine then I shall file a report myself on Visual Studio's Report a bug thing.

Thank you for the swift reply!

Have a nice day!

**Comment by strega-nil** [comment]
@prithvidiamond1 thank you so much!

**Comment by JackBoosY** [comment]
@prithvidiamond1 Can you post the feedback link here?

**Comment by prithvidiamond1** [comment]
@JackBoosY Here you go: [Something in vcpkg seems to be interfering with Visual Studio 2019's contextual drop down menu for Managing Configurations](https://developercommunity2.visualstudio.com/t/Something-in-vcpkg-seems-to-be-interferi/1273535?entry=myactivity)

**Comment by JackBoosY** [comment]
So please track the feedback instead.
Thanks.
