### ISSUE TITLE
[opencascade] x86-windows build failure

### ISSUE THREAD

**Issue by carpolite** [microsoft/vcpkg#14831]
PS D:\vcpkg> .\vcpkg install opencascade

CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:142 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j5
    Working Directory: D:/vcpkg/buildtrees/opencascade/x86-windows-dbg
    See logs for more information:
      D:\vcpkg\buildtrees\opencascade\install-x86-windows-dbg-out.log

Error: Building package opencascade:x86-windows failed with: BUILD_FAILED

please help me

**Comment by JackBoosY** [comment]
Please provide your Windows version, Visual Studio version and log _D:\vcpkg\buildtrees\opencascade\install-x86-windows-dbg-out.log_.

Thanks.

**Comment by carpolite** [comment]
> Please provide your Windows version, Visual Studio version and log _D:\vcpkg\buildtrees\opencascade\install-x86-windows-dbg-out.log_.
> 
> Thanks.

i close the fire wall and did it, thanks your help~~
