### ISSUE TITLE
eigen3 build failure

### ISSUE THREAD

**Issue by sdoiel61** [microsoft/vcpkg#14838]
**Host Environment**
- OS: Microsoft Windows 10, Home OS build 19041.630
- Compiler: Microsoft Visual Studio Professional, Version 16.8.2

**To Reproduce**
`./vcpkg install eigen3:x86-windows`

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

Starting package 1/1: eigen3:x86-windows
Building package eigen3[core]:x86-windows...
-- Using cached C:/cpppkg/vcpkg/downloads/libeigen-eigen-3.3.7.tar.gz
-- Extracting source C:/cpppkg/vcpkg/downloads/libeigen-eigen-3.3.7.tar.gz
-- Applying patch fix-cuda-error.patch
CMake Error at scripts/cmake/vcpkg_extract_source_archive_ex.cmake:148 (file):
  file RENAME failed to rename

    C:/cpppkg/vcpkg/buildtrees/eigen3/src/3.3.7-3eb1aba727.tmp/eigen-3.3.7

  to

    C:/cpppkg/vcpkg/buildtrees/eigen3/src/3.3.7-3eb1aba727.clean

  because: No error

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_gitlab.cmake:128 (vcpkg_extract_source_archive_ex)
  ports/eigen3/portfile.cmake:3 (vcpkg_from_gitlab)
  scripts/ports.cmake:136 (include)

Error: Building package eigen3:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: eigen3:x86-windows
  Vcpkg version: 2020.11.12-nohash

**Comment by JonLiu1993** [comment]
@sdoiel61 ,Thanks for posting this issue,I cannot reproduce your problem on Windows 10. Can you create a folder on a non-C drive? , And then use the latest vcpkg to build eigen3, if it still fails, please provide the failure log

![Capture](https://user-images.githubusercontent.com/63675417/100706190-88c2e980-33e3-11eb-99c7-a3e4866c2014.PNG)

**Comment by sdoiel61** [comment]
It built ok on the non-c drive. I fetched the latest into my c repository and reran the install and it was successful as well. I don’t know if you want to pursue the issue, since it seems to have been corrected, but the version in which I experienced the failure was:  896498fdbae91d5f97bfffcadef21b066277fcf2 Regards,Steve From: JonLiu1993Sent: Monday, November 30, 2020 10:44 PMTo: microsoft/vcpkgCc: sdoiel61; MentionSubject: Re: [microsoft/vcpkg] eigen3 build failure (#14838) @sdoiel61 ,Thanks for posting this issue,I cannot reproduce your problem on Windows 10. Can you create a folder on a non-C drive? , And then use the latest vcpkg to build eigen3, if it still fails, please provide the failure log—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by JonLiu1993** [comment]
@sdoiel61 ，Now you can successfully install eigen3, can this issue be closed?

**Comment by sdoiel61** [comment]
Yes
