### ISSUE TITLE
Antlr4 update to 4.9

### ISSUE THREAD

**Issue by sdoiel61** [microsoft/vcpkg#14839]
Library name: Antlr4

New version number: 4.9

[antlr4.zip](https://github.com/microsoft/vcpkg/files/5612816/antlr4.zip)

I am not sure since I don't know enough about vcpkg, but I created the attached vcpkg.json and portfile.cmake files and the package appears to build correctly.

I can't say for certain because I can't build my project to verify since other packages (anglescript and eigen3) are currently broken.

**Comment by JonLiu1993** [comment]
Solved by #16383
