### ISSUE TITLE
angelscript build failure

### ISSUE THREAD

**Issue by sdoiel61** [microsoft/vcpkg#14837]
**Host Environment**
- OS: [Windows 10 Home]
- Compiler: Microsoft Visual Studio 2019 Version 16.8.2

**To Reproduce**
`./vcpkg install angelscript:x86-windows`

Starting package 1/1: angelscript:x86-windows
Building package angelscript[core]:x86-windows...
-- Downloading https://angelcode.com/angelscript/sdk/files/angelscript_2.34.0.zip...
-- Extracting source C:/cpppkg/vcpkg/downloads/angelscript_2.34.0.zip
-- Applying patch mark-threads-private.patch
CMake Error at scripts/cmake/vcpkg_extract_source_archive_ex.cmake:148 (file):
  file RENAME failed to rename

    C:/cpppkg/vcpkg/buildtrees/angelscript/src/elscript_2-be32c5851d.tmp/sdk

  to

    C:/cpppkg/vcpkg/buildtrees/angelscript/src/elscript_2-be32c5851d.clean

  because: No error

Call Stack (most recent call first):
  ports/angelscript/portfile.cmake:7 (vcpkg_extract_source_archive_ex)
  scripts/ports.cmake:136 (include)

Error: Building package angelscript:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: angelscript:x86-windows
  Vcpkg version: 2020.11.12-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by JonLiu1993** [comment]
@sdoiel61 ,Thanks for posting this issue,I cannot reproduce your problem on Windows 10. Can you create a folder on a non-C drive? , And then use the latest vcpkg to build angelscript , if it still fails, please provide the failure log,Thanks

**Comment by JonLiu1993** [comment]
Relate to #14838

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/8199
