### ISSUE TITLE
[vcpkg] bootstrap-vcpkg.bat fails

### ISSUE THREAD

**Issue by deva22github** [microsoft/vcpkg#14832]
I'm not sure this is still an issue that needs solving? If someone still has this issue, please ping me and open a new issue.

_Originally posted by @strega-nil in https://github.com/microsoft/vcpkg/issues/7903#issuecomment-597371500_

I'm having this issue and new to github, please help me get rid of this error

**Comment by JackBoosY** [comment]
Can you please provide more details?

**Comment by deva22github** [comment]
@JackBoosY when i bootstrap it, the command prompt screen says the following:
![Screenshot 2020-11-30 122927](https://user-images.githubusercontent.com/71824038/100578298-fac60080-3307-11eb-8617-8d55ef2422e5.png)  
and if u dont mind, as im new to github, im not clear how it is used, and has some confusions, so dont mind if i make any mistakes unknowingly in your profile

**Comment by JackBoosY** [comment]
Which version of Visual Studio did you install? Did you install the English Language Package? And please provide your Windows SDK version.

Thanks.

**Comment by deva22github** [comment]
visual studio code version :1.51.1
english language(uk) package for visual studio code has not been installed  earlier, but just now have installed it
im not sure about the sdk version

**Comment by JackBoosY** [comment]
@deva22github Sorry, did you use Windows 10? Please use powershell instead of cmd and try again.

Thanks.

**Comment by deva22github** [comment]
ok sure, thank you so much

**Comment by deva22github** [comment]
git : fatal: destination path 'vcpkg' already exists and is not an empty directory.
At line:1 char:1
+ git clone https://github.com/Microsoft/vcpkg.git
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (fatal: destinat...mpty directory.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

when using powershell, the above one was displayed @JackBoosY

**Comment by deva22github** [comment]
@JackBoosY using powershell also gives the same message

**Comment by deva22github** [comment]
@strega-nil can you please help me solve this issue?

**Comment by gvanem** [comment]
@deva22github I've created this [GNU-makefile](https://gist.github.com/gvanem/22c328b3388bc0adfb0e4bbb60e20de9) to build vcpkg. Mostly since I'm utterly sick of the obfuscated Powershell, VS-project-file junk. Maybe it will work for you?

**Comment by deva22github** [comment]
@gvanem Sorry but what should i do with this gnu-file.. i dont get it correctly.. please give my steps

**Comment by deva22github** [comment]
@gvanem sorry, the first step in the file even didnot work for me

**Comment by gvanem** [comment]
@deva22github What step? And do you even have `GNUmake.exe` or `make.exe`. You should do a `make -v` and you'll see something like:
```
GNU Make 4.3.90
Copyright (C) 1988-2020 Free Software Foundation, Inc.
..
```

**Comment by deva22github** [comment]
sorry, the first step of the file even does'nt work for me

**Comment by deva22github** [comment]
i have gnumake.exe

**Comment by gvanem** [comment]
> i have gnumake.exe

And the other POSIX tools like date, sh, sed etc? I recommend you install [Cygwin](https://cygwin.com/install.html). 
Cygwin has a package-manager/installer (setup.exe) that is far outperforms VCPKG.

**Comment by deva22github** [comment]
can you please tell me what should be done if i get this?
![Screenshot 2020-11-30 225931](https://user-images.githubusercontent.com/71824038/100643297-de55b280-335f-11eb-8964-dbd70698b17e.png)

i have installed sdk, c++ extensions, english language package

**Comment by strega-nil** [comment]
@deva22github please run:

```
> "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json
```

and post the results.

**Comment by deva22github** [comment]
@strega-nil  it says, "The system cannot find the path specified."

**Comment by strega-nil** [comment]
@deva22github then could you run `dir "C:\Program Files (x86)"`?

**Comment by deva22github** [comment]
@strega-nil 
![Screenshot 2020-12-01 001501](https://user-images.githubusercontent.com/71824038/100650731-60e36f80-336a-11eb-90d4-b290d14e65ff.png)

**Comment by StarGate-One** [comment]
- It looks like you only have Visual Studio 8 aka 2005?
- vcpkg supports later versions starting with Visual Studio 2015.3, 2017 and 2019.
- Visual Studio 2017 and 2019 community versions are free, just go here https://visualstudio.microsoft.com/ download and install.
![image](https://user-images.githubusercontent.com/68293825/100652744-5cd93280-3315-11eb-87b1-e4594840bf72.png)
**1. Select the `Community` download** https://download.visualstudio.microsoft.com/download/pr/9d2147aa-7b01-4336-b665-8fe07735e5ee/2706b53b5d7d6e8d12937b637648481eb45561a06f8fabef247350ed5233befa/vs_Community.exe
**2. Run the downloaded `vs_Community.exe`**
**3. Be sure to install the `Desktop Development with C++`**
![image](https://user-images.githubusercontent.com/68293825/100652892-91e58500-3315-11eb-89e9-fa8cb3024d84.png)
**4. the windows SDK by selecting `Individual Components` then scroll down**
![image](https://user-images.githubusercontent.com/68293825/100653070-da04a780-3315-11eb-8627-c5ca237caf41.png)
**5. and the got to `Language packs` the `English` language pack.**
![image](https://user-images.githubusercontent.com/68293825/100653244-19cb8f00-3316-11eb-989c-73e035197de3.png)

**Comment by deva22github** [comment]
@StarGate-One  i have visual studio code and not visual studio

**Comment by StarGate-One** [comment]
> @StarGate-One i have visual studio code and not visual studio

That is why it is not working - Visual Studio Code and Visual Studio are not the same.

vcpkg requirements https://github.com/microsoft/vcpkg#quick-start-windows
![image](https://user-images.githubusercontent.com/68293825/100656839-564db980-331b-11eb-977d-f22f0a1de8c9.png)

If you do not want to use Visual Studio, you must install some type of C/C++ compiler/linker for vcpkg to work, Cygwin and MSys2 have the g/g++ compiler/linker, but you will need to set Visual Studio Code up to use one of them instead.

**Comment by strega-nil** [comment]
@deva22github VS Code does not contain something to actually build the code; you'll need to install VS.

**Comment by deva22github** [comment]
@StarGate-One  then i cannot use vs code for c++, where i have installed c++ extensions in visual code market place??

**Comment by deva22github** [comment]
@StarGate-One @strega-nil thank you so much for explaining me about this <3

**Comment by StarGate-One** [comment]
@deva22github if you are on Windows, install Visual Studio 2019 Community with the basics, like I posted above, then you can use both VS Code and vcpkg.
Just because you have Visual Studio installed, does not mean you must use the Visual Studio IDE to develop/code with. You can still use VS Code to write your code and then VS Code will go out behind the scenes and use Visual Studio to compile/link your project/program.

**Comment by deva22github** [comment]
@StarGate-One 
thanks a lot!, now I understood.
