### ISSUE TITLE
[libjpeg-turbo] Installed pkg-config (.pc) debug files specify non-existent includedir

### ISSUE THREAD

**Issue by HappySeaFox** [microsoft/vcpkg#14847]
****

**Is your feature request related to a problem? Please describe.**

I'm trying to package a new port. The port uses `pkg-config` to find dependencies. It also depends on libjpeg-turbo. So in my cmake file I have

```
find_package(PkgConfig REQUIRED)
pkg_check_modules(libjpeg IMPORTED_TARGET REQUIRED libjpeg)
```

On x64-windows `vcpkg install <my port>` fails with the following error:

```
  Imported target "PkgConfig::libjpeg" includes non-existent path

   "D:/projects/git.vcpkg/installed/x64-windows/debug/include"
```

**Proposed solution**
Fix libjpeg-turbo to make sure all the paths specified in its .pc files really exist

**Describe alternatives you've considered**
Created `D:/projects/git.vcpkg/installed/x64-windows/debug/include` by hand

**Additional context**
-

**Comment by Neumann-A** [comment]
same as https://github.com/microsoft/vcpkg/issues/14849#issuecomment-735897846

But I highly discourage usage of pkgconfig in cmake since it is not configuration aware.

**Comment by NancyLi1013** [comment]
Hi @HappySeaFox 

This issue should be fixed via PR https://github.com/microsoft/vcpkg/pull/15735. Please update to the latest vcpkg and rebuild this port.
