### ISSUE TITLE
[tiff] Installed pkg-config (.pc) debug files specify non-existent includedir

### ISSUE THREAD

**Issue by HappySeaFox** [microsoft/vcpkg#14849]
****

**Is your feature request related to a problem? Please describe.**

I'm trying to package a new port. The port uses `pkg-config` to find dependencies. It also depends on `tiff`. So in my cmake file I have

```
find_package(PkgConfig REQUIRED)
pkg_check_modules(libtiff-4 IMPORTED_TARGET REQUIRED libtiff-4)
```

On x64-windows `vcpkg install <my port>` fails with the following error:

```
  CMake Error in src/sail-codecs/src/tiff/CMakeLists.txt:
  Imported target "PkgConfig::libtiff-4" includes non-existent path

    "D:/projects/git.vcpkg/packages/tiff_x64-windows/debug/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```

**Proposed solution**
Fix libtiff to make sure all the paths specified in its .pc files really exist

**Describe alternatives you've considered**
Created `D:/projects/git.vcpkg/packages/tiff_x64-windows/debug/include` by hand

**Additional context**
-

**Comment by Neumann-A** [comment]
port is missing a call to `vcpkg_fixup_pkgconfig()`

**Comment by NancyLi1013** [comment]
@HappySeaFox Please update to the latest vcpkg to rebuild this.
