### ISSUE TITLE
 Building package suitesparse:x64-windows failed

### ISSUE THREAD

**Issue by 777seV** [microsoft/vcpkg#14846]
Environment

OS: win10
Compiler: vs2019

:\vcpkg>vcpkg install g2o:x64-windows
Computing installation plan...
The following packages will be built and installed:
    g2o[core]:x64-windows
  * suitesparse[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\ed\ede17f4001ea5a12ee48042cb99172004850c8a6.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\de\ded744d08e1819c5a197d0b21c81ec90b2819a23.zip
Starting package 1/2: suitesparse:x64-windows
Building package suitesparse[core]:x64-windows...
-- Downloading https://github.com/DrTimothyAldenDavis/SuiteSparse/archive/71e330ca2bc0a2f12f416c461d23dbca21db4d8f.tar.gz...
-- Downloading https://github.com/DrTimothyAldenDavis/SuiteSparse/archive/71e330ca2bc0a2f12f416c461d23dbca21db4d8f.tar.gz... Failed. Status: 18;"Transferred a partial file"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:182 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:143 (vcpkg_download_distfile)
  ports/suitesparse/portfile.cmake:1 (vcpkg_from_github)
  scripts/ports.cmake:136 (include)

Error: Building package suitesparse:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: suitesparse:x64-windows
  Vcpkg version: 2020.11.12-nohash

Additionally, attach any relevant sections from the log files above.

**Expected behavior**
I hope to see the solutions to solve this error and build the g2o successfully.

**Failure logs**
rror: Building package suitesparse:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: suitesparse:x64-windows
  Vcpkg version: 2020.11.12-nohash

**Comment by JackBoosY** [comment]
Seems your network couldn't download the source package, please set a proxy then try again.

Thanks.

**Comment by 777seV** [comment]
How can I install this package to skip step

**Comment by JackBoosY** [comment]
vcpkg doesn't provide the binaries directly, the port should be downloaded and built.

**Comment by 777seV** [comment]
thanks
