### ISSUE TITLE
Propagate flags from triplet to build

### ISSUE THREAD

**Issue by spinicist** [microsoft/vcpkg#14854]
****

My fork of vcpkg can be found here: https://github.com/spinicist/vcpkg/tree/pkconfig

**Is your feature request related to a problem? Please describe.**

I need to build my dependencies and project with a common set of flags. For instance, enabling Address Sanitizer requires that all dependencies are built with it enabled to avoid false positives. Similarly, if you are in the horrible position of needing to use the pre-C++11 ABI with GCC (I am, due to a vendor library), then all dependencies should be built with that as well.

Currently I achieve this by having a .cmake file in `vcpkg/scripts/cmake` that defines my desired flags (see `my_flags_sanitizers.cmake` and `my_flags_abi.cmake`). I then include this in both a custom triplet file (see `x64-osx-asan.cmake`) which sets `VCPKG_CXX_FLAGS` etc., and I also include it in my main `CMakeLists.txt` file where I use it to set `CMAKE_CXX_FLAGS` etc. 

**Proposed solution**

There is a mechanism to pass `VCPKG_CXX_FLAGS` directly into `CMAKE_CXX_FLAGS` in my project.

**Describe alternatives you've considered**

My current implementation, see above. This is error prone as I have to remember to include the correct .cmake file and to set the variables in my `CMakeLists.txt`.

**Comment by strega-nil** [comment]
Thanks for opening an issue!

My opinion is that this is clearly a good feature; the discussion needed is how we want to expose it.

**Comment by Neumann-A** [comment]
You want to use a custom toolchain by setting

`set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE "${CMAKE_CURRENT_LIST_DIR}/x64-windows-llvm.toolchain.cmake")`

in your triplet and specific the build flags in the toolchain file. The triplet should not be used to define compiler flags even though it supports `VCPKG_C(XX)_FLAGS` for extending the default toolchains.

**Comment by spinicist** [comment]
1. Do you have an example of what such a toolchain file would look like? I'm struggling to see how to keep the various flags in sync.
2. What is the logic/reasoning for the vcpkg toolchain / triplet not defining compiler flags? I thought this was the exact use-case for the `CMAKE_XXX_FLAGS_INIT` variables? Certainly https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_FLAGS_INIT.html seems to imply that.

But I'm very much only a CMake user and not an expert.

**Comment by Neumann-A** [comment]
>Do you have an example of what such a toolchain file would look like? I'm struggling to see how to keep the various flags in sync.

see one of the files in https://github.com/microsoft/vcpkg/tree/master/scripts/toolchains

>What is the logic/reasoning for the vcpkg toolchain / triplet not defining compiler flags? I thought this was the exact use-case for the CMAKE_XXX_FLAGS_INIT variables? Certainly

You are mixing vcpkg/cmake related stuff up. You can use `CMAKE_XXX_FLAGS_INIT` in your toolchain but be aware they only append to CMakes default flags. The vcpkg triplet should only be used to setup vcpkg related stuff and environment settings while the toolchain should be used to setup everything else in cmake.
If you really want to apply flags to all ports your best bet currently is to set the corresponding env variables (`C(XX)FLAGS` etc. see `vcpkg_configure_make` for a rough list) which get picked up by cmake and (hopefully) all other build systems

**Comment by spinicist** [comment]
Thanks.

I think the confusion stems from running `cmake -DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake` as the first thing - that kind of implies that vcpkg is defining a toolchain, but I think from what you've said I should not think of it this way?

I suspect I've misunderstood something else but now my more fundamental question is why should a user *not* want to start from the toolchain vcpkg used to compile the dependencies to compile their project? Particularly in manifest mode, this is the behaviour I was hoping for/expecting.

Or to look at it another way, with the application that originally prompted all of this, how are users supposed to enable sanitizers properly across both their build and dependencies?

**Comment by Neumann-A** [comment]
>that kind of implies that vcpkg is defining a toolchain, but I think from what you've said I should not think of it this way?

correct. the vcpkg toolchain is just a helper to setup cmake to find dependencies via vcpkg nothing more. If you want a toolchain with flags and everything you need to set `VCPKG_CHAINLOAD_TOOLCHAIN` file. As an alternative you can always `include(<pathtovcpkgcmake>/vcpkg.cmake)` in your toolchain

> user not want to start from the toolchain vcpkg

define another compiler more/other flags, set cmake variables etc. I use https://github.com/Neumann-A/my-vcpkg-triplets

> how are users supposed to enable sanitizers properly across both their build and dependencies

setup the environment flags and hope every build picks it up. Otherwise vcpkg tries to use the provided toolchain to setup the build correctly and forward the flags but not all ports do that yet.

**Comment by spinicist** [comment]
> As an alternative you can always `include(<pathtovcpkgcmake>/vcpkg.cmake)` in your toolchain

Ahah - now that definitely sounds more like what I want. I will give that a try. Thanks again!
