### ISSUE TITLE
[New Port Request] <libgsf>

### ISSUE THREAD

**Issue by rodionbgd** [microsoft/vcpkg#14851]
Library name:
libgsf
Library description:
The library aims to provide an efficient extensible i/o abstraction for dealing with different structured file formats.
Source repository URL:
https://github.com/GNOME/libgsf
Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by rodionbgd** [comment]
> 

I've ported it to Windows.
If necessary i can share this lib.

**Comment by PhoebeHui** [comment]
@rodionbgd, thanks for your comments! we're happy to accept a PR for supporting it in vcpkg, please submit a PR for this.
