### ISSUE TITLE
[microsoft-signalr] Build failure

### ISSUE THREAD

**Issue by mprather** [microsoft/vcpkg#14860]
**Host Environment**
- OS: Ubuntu 18.04, Kali 2020.4
- Compiler: gcc 7.5, gcc 10.2

**To Reproduce**
`./vcpkg install microsoft-signalr`

**Failure logs** 
Console output
```
Building x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:142 (message):
    Command failed: /home/skipper/src/test-vcpkg/downloads/tools/cmake-3.18.4-linux/cmake-3.18.4-Linux-x86_64/bin/cmake --build . --config Debug --target install -- -v -j9
    Working Directory: /home/skipper/src/test-vcpkg/buildtrees/microsoft-signalr/x64-linux-dbg
    See logs for more information:
      /home/skipper/src/test-vcpkg/buildtrees/microsoft-signalr/install-x64-linux-dbg-out.log
```
Also see attached log file.

**Additional context**
Sometime after vcpkg was tagged with 2020.11-1, signalr stopped building. We noticed a week ago when Azure devops machines started using a commit of vcpkg from Nov 13th. 

[install-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/5619330/install-x64-linux-dbg-out.log)

**Comment by NancyLi1013** [comment]
```
omitted/test-vcpkg/installed/x64-linux/include/boost/asio/execution/any_executor.hpp: In static member function ‘static const std::type_info& boost::asio::execution::detail::any_executor_base::target_type_void()’:
omitted/test-vcpkg/installed/x64-linux/include/boost/asio/execution/any_executor.hpp:811:23: error: cannot use typeid with -fno-rtti
     return typeid(void);
                       ^
omitted/test-vcpkg/installed/x64-linux/include/boost/asio/execution/any_executor.hpp: In static member function ‘static const std::type_info& boost::asio::execution::detail::any_executor_base::target_type_ex()’:
omitted/test-vcpkg/installed/x64-linux/include/boost/asio/execution/any_executor.hpp:851:21: error: cannot use typeid with -fno-rtti
     return typeid(Ex);
```
There should be no `-fon-rtti` compile option. https://github.com/aspnet/SignalR-Client-Cpp/blob/master/src/signalrclient/CMakeLists.txt#L63

Please see these references:

[1] https://stackoverflow.com/questions/8723702/error-cannot-use-typeid-with-fno-rtti
[2] https://scc.ustc.edu.cn/zlsc/tc4600/intel/2017.0.098/compiler_c/common/core/GUID-BA6071E9-2409-4118-84B5-8E1ABE0C2B72.html
