### ISSUE TITLE
 Building package g2o:x64-windows failed

### ISSUE THREAD

**Issue by 777seV** [microsoft/vcpkg#14869]
Environment

OS: win10
Compiler: vs2019

:\vcpkg>vcpkg install g2o:x64-windows
Computing installation plan...
The following packages will be built and installed:
    g2o[core]:x64-windows
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\de\ded744d08e1819c5a197d0b21c81ec90b2819a23.zip
Starting package 1/1: g2o:x64-windows
Building package g2o[core]:x64-windows...
-- Using cached G:/vcpkg/downloads/RainerKuemmerle-g2o-fcba4eaca6f20d9a5792404cc8ef303aeb8ba5d2.tar.gz
-- Cleaning sources at G:/vcpkg/buildtrees/g2o/src/3aeb8ba5d2-bdd2f5bb54.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source G:/vcpkg/downloads/RainerKuemmerle-g2o-fcba4eaca6f20d9a5792404cc8ef303aeb8ba5d2.tar.gz
-- Using source at G:/vcpkg/buildtrees/g2o/src/3aeb8ba5d2-bdd2f5bb54.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:142 (message):
    Command failed: G:/Cmake/bin/cmake.exe --build . --config Debug --target install -- -v -j13
    Working Directory: G:/vcpkg/buildtrees/g2o/x64-windows-dbg
    See logs for more information:
      G:\vcpkg\buildtrees\g2o\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:93 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/g2o/portfile.cmake:20 (vcpkg_install_cmake)
  scripts/ports.cmake:136 (include)

Error: Building package g2o:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: g2o:x64-windows
  Vcpkg version: 2020.11.12-nohash

Additionally, attach any relevant sections from the log files above.

**Expected behavior**
I hope to see the solutions to solve this error and build the g2o successfully.

**Failure logs**
Error: Building package g2o:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: g2o:x64-windows
  Vcpkg version: 2020.11.12-nohash

**Comment by JackBoosY** [comment]
Hi @777seV, thanks for reporting this issue!
Please provide failure log _G:\vcpkg\buildtrees\g2o\install-x64-windows-dbg-out.log_.

Thanks.

**Comment by 777seV** [comment]
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/5621160/install-x64-windows-dbg-out.log)

**Comment by JackBoosY** [comment]
```
LINK : fatal error LNK1168: cannot open G:\vcpkg\buildtrees\g2o\src\3aeb8ba5d2-bdd2f5bb54.clean\bin\g2o_types_data_d.dll for writing
```
Can you please try again?

If it's still exist, please replace `vcpkg_install_cmake()` to `vcpkg_install_cmake(DISABLE_PARALLEL)` in _VCPKG_ROOT/port/g2o/portfile.cmake_ and try again.

Thanks.

**Comment by JackBoosY** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.
