### ISSUE TITLE
[alembic] Cannot open include file 'half.h'

### ISSUE THREAD

**Issue by FishHe** [microsoft/vcpkg#14875]
I use Alembic with x64-windows.
When I include <Alembic/AbcGeom/All.h>, it fails.

**Comment by NancyLi1013** [comment]
Hi @FishHe 

Thanks for posting this issue.

Could you please provide your project case? Do you use CMake project or VS project?

**Comment by FishHe** [comment]
I use it in VS project and with "integrate install".
The problem now has been solved by adding OpenEXR's Include Directory to the VS project.
