### ISSUE TITLE
zxing-cpp fail to report the exact  qrcode  position!!!

### ISSUE THREAD

**Issue by hotbroker** [microsoft/vcpkg#14870]
****

**Is your feature request related to a problem? Please describe.**
I have a image with a qrcode,but this port cant report the exact postion of the qrcode,
(image as in attachment)
collect postion:(10, 10)--(260, 260)
current repot :(51 51 218 218)

**Proposed solution**
update this library or upload a new port supportting detect qrcode 

**Describe alternatives you've considered**
not yet

![image](https://user-images.githubusercontent.com/50006539/100714175-5bc90380-33f0-11eb-8983-d5311e38ef39.png)

**Comment by JackBoosY** [comment]
@hotbroker Is this a upstream bug?

**Comment by hotbroker** [comment]
> @hotbroker Is this a upstream bug?

yes,

**Comment by hotbroker** [comment]
ps:,I just test the NU-BOOK [https://github.com/nu-book/zxing-cpp](url)
it returns the exact values i want,so,shoud vcpkg intergate this  lib?

> Text:     "this is a test."
Format:   QRCode
Position: 9x9 261x9 259x259 9x261
Rotation: 0 deg
Error:    NoError
EC Level: L
