### ISSUE TITLE
Generating CMake Package Configuration Files in portfile

### ISSUE THREAD

**Issue by joelrandria** [microsoft/vcpkg#14877]
Hello,

I'm trying to create a new port in vcpkg for a precompiled library (the corresponding archive contains only the library's headers and binaries).

To seamlessly integrate the package with our CMake build system, I'm trying to generate the ${PORT}Targets.cmake and ${PORT}Config.cmake package files as recommended by CMake: https://cmake.org/cmake/help/latest/manual/cmake-packages.7.html.

However, in modern CMake, these files are usually generated by populating and exporting imported targets or interface libraries with appropriate calls to CMake's add_library() and export() functions.

Unfortunately, this procedure does not seem to work in portfile definition. vcpkg's install command fails with output error:

```
CMake Error at ports/my_port/portfile.cmake:77 (add_library):
  add_library command is not scriptable
Call Stack (most recent call first):
  scripts/ports.cmake:136 (include)
```

Am I missing something, or what is the recommended practice to handle these scenarios with vcpkg?

Thank you for your help!

Joël

**Comment by vicroms** [comment]
Write a CMakeLists.txt and put it in the port directory. Then in the portfile have vcpkg copy it into the `SOURCE_PATH` and call `vcpkg_configure_cmake()` and `vxpkg_install_cmake()`.

**Comment by joelrandria** [comment]
Thank you,

Your suggestion works perfectly !
