### ISSUE TITLE
vcpkg build failure

### ISSUE THREAD

**Issue by memecode** [microsoft/vcpkg#14885]
Bootstrap build fails on Win10 /w vs2015

Environment:
- OS: Windows 10
- Compiler: vs2015 14.0.25431.01 Update 3

1. git clone vkpkg
2. bootstrap-vcpkg.bat

I'm expecting it to build using vs2015. But I get this:

..\src\vcpkg\install.cpp(845): error C2280: 'vcpkg::PortFileProvider::BaselineProvider::BaselineProvider(const vcpkg::PortFileProvider::BaselineProvider &)': attempting to reference a deleted function [E:\vcpkg\toolsrc\windows-bootstrap\vcpkg.vcxproj]
  E:\vcpkg\toolsrc\include\vcpkg/portfileprovider.h(84): note: compiler has generated 'vcpkg::PortFileProvider::BaselineProvider::BaselineProvider' here

Looking at the error I can't even figure out why it's trying to call the default constructor there... both calls in the lambda to construct the BaselineProvider are using non-default parameters. I did spend a little time just trying to fix the compile error but I couldn't figure it out. Seems like the compiler is just wrong here...

**Comment by PhoebeHui** [comment]
@strega-nil, could you please have a look? this issue reproed with vs 2015 update3.

**Comment by sadtab** [comment]
Hi, I got the same issue after pulling the repo. Previously I was at 539a182d3, and everything was fine, I pulled 0a457099416a843f442b6c2275b2ec57239b50d9 and I have this issue. 

On Windows 10, VS2015


`Building vcpkg.exe ...

  install.cpp
..\src\vcpkg\install.cpp(845): error C2280: 'vcpkg::PortFileProvider::BaselineProvider::BaselineProvider(const vcpkg::PortFileProvider::BaselineProvider &)': attempting to reference a deleted function [C:\tools\vcpkg\toolsrc\windows-bootstrap\vcpkg.vcxproj]
  C:\tools\vcpkg\toolsrc\include\vcpkg/portfileprovider.h(84): note: compiler has generated 'vcpkg::PortFileProvider::BaselineProvider::BaselineProvider' here
C:\tools\vcpkg\scripts\bootstrap.ps1 : Building vcpkg.exe failed. Please ensure you have installed Visual Studio with the Desktop C++ workload and the Windows SDK for Desktop C++.
Au caractère Ligne:1 : 4
+ & {& 'C:\tools\vcpkg\scripts\bootstrap.ps1' }
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,bootstrap.ps1

ScriptHalted
Au caractère C:\tools\vcpkg\scripts\bootstrap.ps1:411 : 5
+     throw
+     ~~~~~
    + CategoryInfo          : OperationStopped: (:) [], RuntimeException
    + FullyQualifiedErrorId : ScriptHalted
`

**Comment by sadtab** [comment]
So I investigated blindly on the commits, it's 4fba4b791 who broke the compilation, I tried `git revert 4fba4b791` and fixed the problem (temporarily).

**Comment by strega-nil** [comment]
cc @BillyONeal please god we need VS2015 compile testing.

**Comment by strega-nil** [comment]
I'll fix this by Soon (tm), definitely by EOD

**Comment by memecode** [comment]
Thanks everyone. Fastest turn around ever. Really appreciate it.
