### ISSUE TITLE
Ports: request for feedback on several single-file header-only libraries

### ISSUE THREAD

**Issue by martinmoene** [microsoft/vcpkg#1489]
Hi,

I've a couple of single file header-only libraries that may or may not be of interest to vcpkg. Before I'd plunge in, I'd like to hear if there's interest in one or more of the following. Please specify.

- [x] [any-lite](https://github.com/martinmoene/any-lite) - PR 26-May-2019
A single-file header-only C++17-like any, a type-safe container for single values of any type for C++98, C++11 and later.

- [x] [byte-lite](https://github.com/martinmoene/byte-lite) - PR 26-May-2019
A single-file header-only C++17-like byte type for C++98, C++11 and later .

- [x] [clue](https://github.com/martinmoene/clue)
A tiny single-file header-only C++ logging framework.

- [x] [expected-lite](https://github.com/martinmoene/expected-lite) - PR 27-May-2019
Expected objects for C++11 and later (and later perhaps C++98 ).

- [x] [observer-ptr-lite](https://github.com/martinmoene/observer-ptr-lite) - PR 28-May-2019
A single-file header-only C++98, C++03, C++11, C++14 version of ISO C++17 std::observer_ptr.

- [x] [optional-bare](https://github.com/martinmoene/optional-bare) - PR 28-May-2019
A simple version of a C++17-like optional for default-constructible, copyable types, for C++98 and  later in a single-file header-only library.

- [x] [optional-lite](https://github.com/martinmoene/optional-lite) - PR 28-May-2019
A single-file header-only version of a C++17-like optional, a nullable object for C++98, C++11 and later.

- [x] [ring-span-lite](https://github.com/martinmoene/ring-span-lite) - PR 30-May-2019
A C++yy-like ring_span type for C++98, C++11 and later in a single-file header-only library.

- [x] [span-lite](https://github.com/martinmoene/span-lite) - PR 31-May-2019
A C++20-like span for C++98, C++11 and later in a single-file header-only library.

- [x] [status-value-lite](https://github.com/martinmoene/status-value-lite)
A class for status and optional value for C++11 and later, C++98 variant provided.

- [x] [string-view-lite](https://github.com/martinmoene/string-view-lite) - PR 04-Jun-2019
A C++17-like string_view for C++98, C++11 and later in a single-file header-only library .

- [x] [type-lite](https://github.com/martinmoene/type-lite)
Strong types for C++98, C++11 and later in a single-file header-only library .

- [x] [value-ptr-lite](https://github.com/martinmoene/value-ptr-lite)
A C++ smart-pointer with value semantics for C++98, C++11 and later in a single-file header-only library.

- [x] [variant-lite](https://github.com/martinmoene/variant-lite) - PR 01-Jun-2019
A single-file header-only version of a C++17-like variant, a type-safe union for C++98, C++11 and later.

- [x] [lest](https://github.com/martinmoene/lest) - 19-Feb-2019
A modern, C++11-native, single-file header-only, tiny framework for unit-tests, TDD and BDD (includes C++98 variant). Note this is a light C++11 Catch variant, at 1/9 LOC ([and less functionality](https://github.com/martinmoene/catch-lest-other-comparison)).

**Comment by Voskrese** [comment]
если они участвуют в каких либо проектах, почему бы и нет. тем более если существует у какой либо библиотеки зависимость. кому надо, тот установит, были бы портированы заголовки  ))

If they participate in any projects, why not. even more so if you have any library dependency.

**Comment by Fleischner** [comment]
Is there a reason that all are separate ports?
I see the intention that if you put the headers directly into an project you only add the required ones, but within vcpkg there is little advantage to have one port per header. 
Wouldn't it make sense to combine all of them in a single library that offers c++17/20 backward comparability constructs for c++11/98?

**Comment by ras0219-msft** [comment]
Separate ports is fine here (and somewhat preferable) because it helps to keep changes small and isolated. When expected-lite updates, there's no need to rebuild things that use optional-lite (as an example).

However, I could see value in a metapackage that installs all of them, for someone who knows they want all of @martinmoene's great stuff in a single easy command line :)

**Comment by martinmoene** [comment]
@ras0219-msft Thanks :) Do you have a suggestion/example how such a metapackage may look like?

**Comment by grdowns** [comment]
@martinmoene check out the port [`boost`](https://github.com/microsoft/vcpkg/tree/master/ports/boost)! Simply list the build dependencies in the `CONTROL` file and call `set(VCPKG_POLICY_EMPTY_PACKAGE enabled)` in `portfile.cmake`. Note within the `boost` example that some of the build dependencies are disabled for certain triplets e.g. occurrences of `(!arm)` based on which triplets that particular port builds for, which allows the metapackage to succeed in building for a triplet even though one of the dependencies may not. Let us know if you run into any problems and we will be more than happy to lend a hand.

**Comment by NancyLi1013** [comment]
Hi @martinmoene  thanks for posting this request and your contribution. Currently all the ports you put forward have been added to vcpkg. Please try to update vcpkg and use them.
