### ISSUE TITLE
[docs/regenerate.ps1] Incorrect sorting in portfile-functions.md

### ISSUE THREAD

**Issue by Hoikas** [microsoft/vcpkg#14892]
When regenerating the documentation for #14891, the listing in `portfile-functions.md` was sorted incorrectly, causing CI to fail. The incorrect sorting can be seen in 87e3249d2c30d. This required manual intervention on my part to fix the sorting.

**Environment**
- OS: Windows 10 PowerShell 7.1
- Compiler: N/A

**To Reproduce**
1. docs/regenerate.ps1
2. Open pull request
3. Experience the failure.

**Expected behavior**
For CI to not fail.

**Failure logs** 
https://dev.azure.com/vcpkg/public/_build/results?buildId=46020&view=logs&j=912ac355-25d6-5c3c-8698-e074cc57eb78&t=44b67b4c-a5c9-5085-716c-bffa21efb028

**Additional context**

**Comment by strega-nil** [comment]
The issue is that pwsh and powershell sort differently; thus, we should do explicit sorting.
