### ISSUE TITLE
How do I use vcpkg with Clang on WSL?

### ISSUE THREAD

**Issue by gc435** [microsoft/vcpkg#14895]
In a VS2019 CMake project, I can target WSL-GCC-Debug and use `vcpkg` packages just fine.  However, I can't get VS to find packages when targeting WSL-Clang-Debug.  A typical error is:

```
1> [CMake]   Could not find a package configuration file provided by "fmt" with any of
1> [CMake]   the following names:
1> [CMake] 
1> [CMake]     fmtConfig.cmake
1> [CMake]     fmt-config.cmake
```

* I know that `fmt` is installed in WSL2 because I can build my project using `CXX=clang++ cmake -DCMAKE_TOOLCHAIN_FILE:FILEPATH=/path/to/vcpkg.cmake .. && cmake --build .`.  That works fine.
* All of my `vcpkg` packages in WSL2 were installed with the **x64-linux** triplet.
* I list the WSL `vcpkg.cmake` toolchain file in `CMakeSettings.json`.

**Question:** Any idea why VS can't find `vcpkg` packages when targeting WSL-Clang-Debug?

Where I looked for an answer:

* https://docs.microsoft.com/en-us/cpp/build/vcpkg?view=msvc-160
* https://docs.microsoft.com/en-us/windows/wsl/install-win10
* https://devblogs.microsoft.com/cppblog/targeting-windows-subsystem-for-linux-from-visual-studio/

**Comment by luncliff** [comment]
Probably `VCPKG_TARGET_TRIPLET` CMake variable?

something like this.
```json
{
    "configurations": [
        {
            "name": "x64-Debug-WSL",
            "generator": "Ninja",
            "configurationType": "Debug",
            "inheritEnvironments": [
                "clang_x64_x64"
            ],
            "buildRoot": "${projectDir}\\out\\build\\${name}",
            "installRoot": "${projectDir}\\out\\install\\${name}",
            "cmakeCommandArgs": "",
            "buildCommandArgs": "-v",
            "ctestCommandArgs": "",
            "variables": [
                {
                    "name": "CMAKE_TOOLCHAIN_FILE",
                    "value": "C:\\vcpkg\\scripts\\buildsystems\\vcpkg.cmake",
                    "type": "PATH"
                },
                {
                    "name": "VCPKG_TARGET_TRIPLET",
                    "value": "x64-linux",
                    "type": "STRING"
                }
            ]
        }
    ]
}
```

**Comment by gc435** [comment]
@luncliff Thanks, that was it.  I ticked the box **Save to JSON** in the `CMakeSettings.json` GUI editor.  Now packages are found when targeting 
**WSL-Clang-Debug**.

I wonder if I missed this step in the documentation?

**Comment by NancyLi1013** [comment]
Hi @gc435 

Thanks for posting this issue.

Do you mean that you missed this configure step?

https://github.com/microsoft/vcpkg/blob/master/docs/examples/installing-and-using-packages.md#cmake-toolchain-file

**Comment by luncliff** [comment]
@gc435 Normally we don't have to specify that when working with the terminal. (Windows Terminal, for example) 
For `VCPKG_TARGET_TRIPLET`, Here is the reference: https://github.com/microsoft/vcpkg/blob/master/docs/users/integration.md#triplet-selection

**Comment by gc435** [comment]
> Do you mean that you missed this configure step?
> 
> https://github.com/microsoft/vcpkg/blob/master/docs/examples/installing-and-using-packages.md#cmake-toolchain-file

@NancyLi1013, thanks for the reply.  Nope, I did that step.  I properly specified the toolchain file.

The step I did not know about was that `VCPKG_TARGET_TRIPLET` needs to be specified when using WSL and Clang for some reason, as suggested by @luncliff.  This is not required when using WSL and GCC.  Without specifying `VCPKG_TARGET_TRIPLET`, I cannot use **WSL-Clang-Debug** from VS.

I don't think that required step is in any documentation.

**Comment by gc435** [comment]
> @gc435 Normally we don't have to specify that when working with the terminal. (Windows Terminal, for example)
> For `VCPKG_TARGET_TRIPLET`, Here is the reference: https://github.com/microsoft/vcpkg/blob/master/docs/users/integration.md#triplet-selection

@luncliff, I confused myself.  I now see that `VCPKG_TARGET_TRIPLET` is required when targeting **WSL-GCC-Debug** and not just **WSL-Clang-Debug**.  When I opened this issue, I found that **WSL-GCC-Debug** worked but **WSL-Clang-Debug** did not.  Perhaps `VCPKG_TARGET_TRIPLET` was pulled from a cache.  Or, perhaps I made a mistake.

**Comment by ras0219-msft** [comment]
Thanks for leaving this issue!

From what I can see, the primary issue has been resolved. If not, I'd be happy to reopen this issue.
