### ISSUE TITLE
[vcpkg_fixup_pkgconfig] About libraries in manual-link

### ISSUE THREAD

**Issue by longnguyen2004** [microsoft/vcpkg#14894]
Some libraries like SDL2 redefines `main` (with SDL2main), and thus should be in the `manual-link` folder to prevent automatic linking by the VS integration. However, this breaks `vcpkg_fixup_pkgconfig`, which expect the libraries to be in the outer `lib` directory. What should we do in this case? Fix `vcpkg_fixup_pkgconfig` to look into the manual-link folder, or move the libraries into the outer `lib` folder for non-MSVC triplets?

Related: https://github.com/microsoft/vcpkg/issues/14779#issuecomment-736862588

**Comment by StarGate-One** [comment]
Just putting this out here, but maybe...
- Port gtest (GoogleTest and GoogleMock testing frameworks) has manual link libraries gmock_main.lib and gtest_main.lib. 
- Could the method used for them as done in the portfile.cmake be used with all the other manual-link libraries like SDL, SDL2, SFML, Ogre, etc?

https://github.com/microsoft/vcpkg/blob/0a457099416a843f442b6c2275b2ec57239b50d9/ports/gtest/portfile.cmake#L50-L75

If this would not work, I understand, I am still learning...

**Comment by longnguyen2004** [comment]
> * Could the method used for them as done in the portfile.cmake be used with all the other manual-link libraries like SDL, SDL2, SFML, Ogre, etc?

Yes it basically follows the same procedure

**Comment by Neumann-A** [comment]
Simply said: Fix the `-L` flag. All *.pc files should be like `-L<libpath> -l<libraryname>`. `vcpkg_fixup_pkgconfig` will look into `<libpath>`

**Comment by longnguyen2004** [comment]
Thanks for the reply, although I realized the problem isn't what I originally thought about

**Comment by strega-nil** [comment]
The world according to @ras0219:

This is a bug with a specific port, and the port should do what @Neumann-A is saying. However, `vcpkg_fixup_pkgconfig` should also offer help in fixing the problem.

**Comment by Adela0814** [comment]
@longnguyen2004 this issue has been fixed, please get latest source and try again.
