### ISSUE TITLE
[protobuf] Should not build static libraries for `x86-windows`

### ISSUE THREAD

**Issue by ras0219-msft** [Microsoft/vcpkg#149]

**Comment by KindDragon** [comment]
Why static?

**Comment by ras0219-msft** [comment]
Sorry, the title isn't clear enough. The bug is that static libraries are currently being built when using the `x86-windows` triplet. That triplet should receive DLLs; the `x86-windows-static` triplet should receive static libraries.

**Comment by KindDragon** [comment]
I remembered why I did it. I specifically build protobuf static library, otherwise, it was impossible to build grpc because of https://github.com/google/protobuf/pull/2227

**Comment by ras0219-msft** [comment]
Given the general response in the protobuf thread, I'd be happy to apply google/protobuf#2227 locally if you'd be willing to submit a PR here with the diff for it as a patch (https://patch-diff.githubusercontent.com/raw/google/protobuf/pull/2227.diff).

**Comment by dzenanz** [comment]
google/protobuf#2227 has been merged on Dec 16th and google/protobuf#2219 was fixed on Dec 23rd. Can we get grpc #535 building?

**Comment by KindDragon** [comment]
IDK, maybe better wait for the release with this commit or apply commit as the patch to latest protobuf release.

**Comment by jozefizso** [comment]
Does protobuf support DLL linkage?

**Comment by KindDragon** [comment]
Yes
