### ISSUE TITLE
[qt5-base] build failure

### ISSUE THREAD

**Issue by garry-iglesias** [microsoft/vcpkg#14907]
**Host Environment**
- OS: Windows 10
- Compiler: Visual Studio 2019... (But it's unrelated as it's "gcc ports" which is used ?)

**To Reproduce**
Steps to reproduce the behavior (from powershell):
`.\vcpkg install qt5-base`

**Failure logs** 
-- Console output:

     Building x64-windows-static-md-dbg
     CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:142 (message):
         Command failed: C:/vcpkg/downloads/tools/jom/jom-1.1.3/jom.exe /J 9
         Working Directory: C:/vcpkg/buildtrees/qt5-base/x64-windows-static-md-dbg
         See logs for more information:
           C:\vcpkg\buildtrees\qt5-base\build-x64-windows-static-md-dbg-out.log
           C:\vcpkg\buildtrees\qt5-base\build-x64-windows-static-md-dbg-err.log
     
     Call Stack (most recent call first):
       ports/qt5-base/cmake/install_qt.cmake:76 (vcpkg_execute_build_process)
       ports/qt5-base/portfile.cmake:309 (install_qt)
       scripts/ports.cmake:136 (include)

     Error: Building package qt5-base:x64-windows-static-md failed with: BUILD_FAILED
     Please ensure you're using the latest portfiles with `.\vcpkg update`, then
     submit an issue at https://github.com/Microsoft/vcpkg/issues including:
       Package: qt5-base:x64-windows-static-md
       Vcpkg version: 2020.11.12-nohash
     
     Additionally, attach any relevant sections from the log files above.
     vcpkg_install : Failed at installing package qt5-base (x64-windows-static-md)
     At E:\devel\mumble\scripts\vcpkg\get_mumble_dependencies.ps1:87 char:4
     +             vcpkg_install -package $dep -targetTriplet $triplet -clea ...
     +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
         + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,vcpkg_install

**Additional context**
Build "from scratch", discovered through "mumble dependency" install script. I've forced the vcpkg to be on the root of C: (C:\Vcpkg) so it's not related to space or path length. It's been a week that I try, waiting/hoping for ports update, with no luck until now :).
[build-x64-windows-static-md-dbg-err.log](https://github.com/microsoft/vcpkg/files/5629596/build-x64-windows-static-md-dbg-err.log)
[build-x64-windows-static-md-dbg-out.log](https://github.com/microsoft/vcpkg/files/5629597/build-x64-windows-static-md-dbg-out.log)

**Comment by JackBoosY** [comment]
cc @Neumann-A

**Comment by JonLiu1993** [comment]
@Neumann-A，Could you please take a look

**Comment by JonLiu1993** [comment]
@Neumann-A ,Could you please take a look?

**Comment by JonLiu1993** [comment]
@garry-iglesias ,Thanks for posting this issue, I can successfully install qt5-base:x64-windows-static-md with the latest vcpkg, I temporarily close this issue, if it is still an issue, please reopen this issue.
````
-- Fixing makefile installation path x64-windows-static-md-rel
-- Installing x64-windows-static-md-rel
-- Package x64-windows-static-md-rel done
-- Installing: F:/test9/vcpkg/packages/qt5-base_x64-windows-static-md/share/qt5-base/copyright
-- Performing post-build validation
-- Performing post-build validation done
Installing package qt5-base[core]:x64-windows-static-md...
Elapsed time for package qt5-base:x64-windows-static-md: 16.93 min

Total elapsed time: 29.49 min

The package qt5-base provides CMake targets:

    find_package(Qt5AccessibilitySupport CONFIG REQUIRED)
    target_link_libraries(main PRIVATE Qt::AccessibilitySupport Qt5::AccessibilitySupport Qt::AccessibilitySupportPrivate Qt5::AccessibilitySupportPrivate)

    find_package(Qt5Concurrent CONFIG REQUIRED)
    target_link_libraries(main PRIVATE Qt::Concurrent Qt5::Concurrent Qt::ConcurrentPrivate Qt5::ConcurrentPrivate)

    find_package(Qt5Core CONFIG REQUIRED)
    # Note: 2 target(s) were omitted.
    target_link_libraries(main PRIVATE Qt::Core Qt5::Core Qt::WinMain Qt5::WinMain)

    find_package(Qt5DBus CONFIG REQUIRED)
    target_link_libraries(main PRIVATE Qt::DBus Qt5::DBus Qt::DBusPrivate Qt5::DBusPrivate)

    find_package(Qt5DeviceDiscoverySupport CONFIG REQUIRED)
    target_link_libraries(main PRIVATE Qt::DeviceDiscoverySupport Qt5::DeviceDiscoverySupport Qt::DeviceDiscoverySupportPrivate Qt5::DeviceDiscoverySupportPrivate)

    find_package(Qt5EdidSupport CONFIG REQUIRED)
    target_link_libraries(main PRIVATE Qt::EdidSupport Qt5::EdidSupport Qt::EdidSupportPrivate Qt5::EdidSupportPrivate)

    find_package(Qt5EventDispatcherSupport CONFIG REQUIRED)
    target_link_libraries(main PRIVATE Qt::EventDispatcherSupport Qt5::EventDispatcherSupport Qt::EventDispatcherSupportPrivate Qt5::EventDispatcherSupportPrivate)

    find_package(Qt5FbSupport CONFIG REQUIRED)
    target_link_libraries(main PRIVATE Qt::FbSupport Qt5::FbSupport Qt::FbSupportPrivate Qt5::FbSupportPrivate)

    find_package(Qt5FontDatabaseSupport CONFIG REQUIRED)
    target_link_libraries(main PRIVATE Qt::FontDatabaseSupport Qt5::FontDatabaseSupport Qt::FontDatabaseSupportPrivate Qt5::FontDatabaseSupportPrivate)

    find_package(Qt5Gui CONFIG REQUIRED)
    # Note: 9 target(s) were omitted.
    target_link_libraries(main PRIVATE Qt::Gui Qt5::Gui Qt::GuiPrivate Qt5::GuiPrivate)

    find_package(Qt5Network CONFIG REQUIRED)
    # Note: 1 target(s) were omitted.
    target_link_libraries(main PRIVATE Qt::Network Qt5::Network Qt::NetworkPrivate Qt5::NetworkPrivate)

    find_package(Qt5OpenGL CONFIG REQUIRED)
    target_link_libraries(main PRIVATE Qt::OpenGL Qt5::OpenGL Qt::OpenGLPrivate Qt5::OpenGLPrivate)

    find_package(Qt5OpenGLExtensions CONFIG REQUIRED)
    target_link_libraries(main PRIVATE Qt::OpenGLExtensions Qt5::OpenGLExtensions Qt::OpenGLExtensionsPrivate Qt5::OpenGLExtensionsPrivate)

    find_package(Qt5PlatformCompositorSupport CONFIG REQUIRED)
    target_link_libraries(main PRIVATE Qt::PlatformCompositorSupport Qt5::PlatformCompositorSupport Qt::PlatformCompositorSupportPrivate Qt5::PlatformCompositorSupportPrivate)

    find_package(Qt5PrintSupport CONFIG REQUIRED)
    # Note: 1 target(s) were omitted.
    target_link_libraries(main PRIVATE Qt::PrintSupport Qt5::PrintSupport Qt::PrintSupportPrivate Qt5::PrintSupportPrivate)

    find_package(Qt5Sql CONFIG REQUIRED)
    # Note: 2 target(s) were omitted.
    target_link_libraries(main PRIVATE Qt::Sql Qt5::Sql Qt::SqlPrivate Qt5::SqlPrivate)

    find_package(Qt5Test CONFIG REQUIRED)
    target_link_libraries(main PRIVATE Qt::Test Qt5::Test Qt::TestPrivate Qt5::TestPrivate)

    find_package(Qt5ThemeSupport CONFIG REQUIRED)
    target_link_libraries(main PRIVATE Qt::ThemeSupport Qt5::ThemeSupport Qt::ThemeSupportPrivate Qt5::ThemeSupportPrivate)

    find_package(Qt5Widgets CONFIG REQUIRED)
    # Note: 1 target(s) were omitted.
    target_link_libraries(main PRIVATE Qt::Widgets Qt5::Widgets Qt::WidgetsPrivate Qt5::WidgetsPrivate)

    find_package(Qt5WindowsUIAutomationSupport CONFIG REQUIRED)
    target_link_libraries(main PRIVATE Qt::WindowsUIAutomationSupport Qt5::WindowsUIAutomationSupport Qt::WindowsUIAutomationSupportPrivate Qt5::WindowsUIAutomationSupportPrivate)

    find_package(Qt5Xml CONFIG REQUIRED)
    target_link_libraries(main PRIVATE Qt::Xml Qt5::Xml Qt::XmlPrivate Qt5::XmlPrivate)
````
