### ISSUE TITLE
[New Port Request] filament

### ISSUE THREAD

**Issue by rutay** [microsoft/vcpkg#14906]
Library name: filament

Library description: "Filament is a real-time physically based rendering engine for Android, iOS, Windows, Linux, macOS and WASM/WebGL"

Source repository URL: https://github.com/google/filament

Project homepage (if different from the source repository): https://google.github.io/filament/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
A part from filament library itself, it would also be useful to me (and hope also to others) having the `gltfio` library. It lies in the libs/ folder. I've not fully learned this library, thus I can't tell you more features but I feel the `filament` target is what's actually needed and mostly required.

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
