### ISSUE TITLE
Requirement of vcpkg integrate install for MSBuild projects using manifests is unacceptable

### ISSUE THREAD

**Issue by sdoiel61** [microsoft/vcpkg#14910]
IMNSHO a fundamental requirement for a project is to know exactly what external libraries are used for a project.

Manifests look like a great way to achieve that goal, but...

The instructions described in:
https://devblogs.microsoft.com/cppblog/vcpkg-accelerate-your-team-development-environment-with-binary-caching-and-manifests/

describe using "vcpkg integrate install" to use manifests.  Unfortunately that makes all packages available to projects that are not using manifests, which could lead to the unintentional use of libraries that have a license that is not compatible with the other projects.

**Comment by vicroms** [comment]
If you are using CMake, running `vcpkg integrate install` is not required. 

You can always manually pass `-DCMAKE_TOOLCHAIN_FILE=${VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake` to your CMake invocation.
