### ISSUE TITLE
sdl2 build failure

### ISSUE THREAD

**Issue by Keithcat1** [microsoft/vcpkg#14928]
**Host Environment**
- OS: x64-mingw-static
- Compiler: GCC 9.2.0

**To Reproduce**
`./vcpkg install sdl2:x64-mingw-static`

**Failure logs** 
-- Fixing pkgconfig file: C:/py/git/vcpkg/packages/sdl2_x64-mingw-static/lib/pkgconfig/sdl2.pc
CMake Error at scripts/cmake/vcpkg_fixup_pkgconfig.cmake:237 (message):
  Unhandled string "-mwindows" was found! If it is a system library use the
  SYSTEM_LIBRARIES parameter for the vcpkg_fixup_pkgconfig call! Otherwise,
  correct the *.pc file or add the case to vcpkg_fixup_pkgconfig
Call Stack (most recent call first):
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:301 (vcpkg_fixup_pkgconfig_check_files)
  ports/sdl2/portfile.cmake:101 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:136 (include)

**Additional context**

**Comment by longnguyen2004** [comment]
I'll take a look at it.

**Comment by longnguyen2004** [comment]
Issue cleanup: It should be fixed now with the changes to `vcpkg_fixup_pkgconfig`

**Comment by JonLiu1993** [comment]
@Keithcat1 ,There have a pr fix x64-mingw, Could you please try if it solves your problem
https://github.com/microsoft/vcpkg/pull/21683

**Comment by JackBoosY** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
