### ISSUE TITLE
[brotli] build failure

### ISSUE THREAD

**Issue by shuangzhiaishang** [microsoft/vcpkg#14920]
Package: brotli:x86-windows
  Vcpkg version: 2020.11.12-nohash

E:\Program Files (x86)\Microsoft Visual Studio\vcpkg>vcpkg install io2d
Computing installation plan...
The following packages will be built and installed:
  * brotli[core]:x86-windows -> 1.0.9
  * bzip2[core]:x86-windows -> 1.0.8#1
  * cairo[core]:x86-windows -> 1.16.0#8
  * dirent[core]:x86-windows -> 1.23.2
  * expat[core]:x86-windows -> 2020-08-18
  * fontconfig[core]:x86-windows -> 2.13.1
  * freetype[bzip2,core,png]:x86-windows -> 2.10.2#5
  * gettext[core]:x86-windows -> 0.21
  * graphicsmagick[core]:x86-windows -> 1.3.35-2
    io2d[core]:x86-windows -> 2020-09-14#1
  * json-c[core]:x86-windows -> 2019-09-10#1
  * libiconv[core]:x86-windows -> 1.16#6
  * libjpeg-turbo[core]:x86-windows -> 2.0.5
  * liblzma[core]:x86-windows -> 5.2.5#2
  * libpng[core]:x86-windows -> 1.6.37#13
  * pixman[core]:x86-windows -> 0.38.4#2
  * pthread[core]:x86-windows -> 3.0.0
  * pthreads[core]:x86-windows -> 3.0.0-6
  * tiff[core]:x86-windows -> 4.1.0
  * zlib[core]:x86-windows -> 1.2.11#9
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x86-windows...
Could not locate cached archive: C:\Users\shuangzhiaishang\AppData\Local\vcpkg\archives\62\62eec99298f5815ba0cacd1fd222527bb0c5abe1.zip
Could not locate cached archive: C:\Users\shuangzhiaishang\AppData\Local\vcpkg\archives\39\39f21dd9a720242ec862fdf90bce373606337899.zip
Could not locate cached archive: C:\Users\shuangzhiaishang\AppData\Local\vcpkg\archives\c6\c61d9e8d72e67b7889adc9f28574677b94f4690d.zip
Could not locate cached archive: C:\Users\shuangzhiaishang\AppData\Local\vcpkg\archives\41\414da56f44e7eb4bd00ebb6325a1263b43b7ea30.zip
Could not locate cached archive: C:\Users\shuangzhiaishang\AppData\Local\vcpkg\archives\90\90bbc24d9e9c4c91fb19c423b2401634dc905a93.zip
Could not locate cached archive: C:\Users\shuangzhiaishang\AppData\Local\vcpkg\archives\8b\8b7d4032029dd3e0becc45d3e107f3a0ce9c6a6f.zip
Could not locate cached archive: C:\Users\shuangzhiaishang\AppData\Local\vcpkg\archives\f7\f73c0ba27394b4372c9fff983546a91ab588afff.zip
Could not locate cached archive: C:\Users\shuangzhiaishang\AppData\Local\vcpkg\archives\c5\c5e1eb95a49cdf707355bff8d3dfc2dd07f1539e.zip
Could not locate cached archive: C:\Users\shuangzhiaishang\AppData\Local\vcpkg\archives\ce\ceac42441c715e04d49e2113d4becf7085955f90.zip
Could not locate cached archive: C:\Users\shuangzhiaishang\AppData\Local\vcpkg\archives\5e\5e5e187e597fe8d156fca0c4cffeb4624d8d9432.zip
Could not locate cached archive: C:\Users\shuangzhiaishang\AppData\Local\vcpkg\archives\a1\a1fc9355022392c4c1a04bf2b2d45a171a79e4c8.zip
Could not locate cached archive: C:\Users\shuangzhiaishang\AppData\Local\vcpkg\archives\da\da894a10d133a4eb1728cb5b34c4edabcdafe5b1.zip
Could not locate cached archive: C:\Users\shuangzhiaishang\AppData\Local\vcpkg\archives\eb\eb4ef26dcff3dd48cf02689d8defc36ee525205d.zip
Could not locate cached archive: C:\Users\shuangzhiaishang\AppData\Local\vcpkg\archives\8a\8a09e06948e636ed1ad94b6e387a82a1768b12cc.zip
Could not locate cached archive: C:\Users\shuangzhiaishang\AppData\Local\vcpkg\archives\6c\6c5c87c7e551f2fa24367368bb3bacf97e4b8977.zip
Could not locate cached archive: C:\Users\shuangzhiaishang\AppData\Local\vcpkg\archives\96\9677cc0d15f5e20baa454cebbf74c425c7d6f784.zip
Could not locate cached archive: C:\Users\shuangzhiaishang\AppData\Local\vcpkg\archives\9e\9ee102517fc26de95643c11dc78b077911e66862.zip
Could not locate cached archive: C:\Users\shuangzhiaishang\AppData\Local\vcpkg\archives\60\60c08b82ce75d17b5cc9af80c96601e76497946e.zip
Could not locate cached archive: C:\Users\shuangzhiaishang\AppData\Local\vcpkg\archives\96\96af57dc0ef99880ddf7ad7e7cb221c82cc9767e.zip
Could not locate cached archive: C:\Users\shuangzhiaishang\AppData\Local\vcpkg\archives\e6\e6657027cd91a8258c61ea800545dfb0913cd095.zip
Starting package 1/20: brotli:x86-windows
Building package brotli[core]:x86-windows...
-- Using cached E:/Program Files (x86)/Microsoft Visual Studio/vcpkg/downloads/google-brotli-e61745a6b7add50d380cfd7d3883dd6c62fc2c71.tar.gz
-- Cleaning sources at E:/Program Files (x86)/Microsoft Visual Studio/vcpkg/buildtrees/brotli/src/6c62fc2c71-a8c4ea9278.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/Program Files (x86)/Microsoft Visual Studio/vcpkg/downloads/google-brotli-e61745a6b7add50d380cfd7d3883dd6c62fc2c71.tar.gz
-- Applying patch install.patch
-- Applying patch fix-arm-uwp.patch
-- Applying patch pkgconfig.patch
-- Using source at E:/Program Files (x86)/Microsoft Visual Studio/vcpkg/buildtrees/brotli/src/6c62fc2c71-a8c4ea9278.clean
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Using msys root at E:/Program Files (x86)/Microsoft Visual Studio/vcpkg/downloads/tools/msys2/c809757c94447846
-- Fixing pkgconfig file: E:/Program Files (x86)/Microsoft Visual Studio/vcpkg/packages/brotli_x86-windows/lib/pkgconfig/libbrotlicommon.pc
-- Fixing pkgconfig file: E:/Program Files (x86)/Microsoft Visual Studio/vcpkg/packages/brotli_x86-windows/lib/pkgconfig/libbrotlidec.pc
-- Fixing pkgconfig file: E:/Program Files (x86)/Microsoft Visual Studio/vcpkg/packages/brotli_x86-windows/lib/pkgconfig/libbrotlienc.pc
-- CHECK_LIB_brotlicommon_RELEASE:CHECK_LIB_brotlicommon_RELEASE-NOTFOUND
CMake Error at scripts/cmake/vcpkg_fixup_pkgconfig.cmake:235 (message):
  Library "brotlicommon" was not found! If it is a system library use the
  SYSTEM_LIBRARIES parameter for the vcpkg_fixup_pkgconfig call! Otherwise,
  correct the *.pc file
Call Stack (most recent call first):
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:301 (vcpkg_fixup_pkgconfig_check_files)
  ports/brotli/portfile.cmake:25 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:136 (include)

Error: Building package brotli:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: brotli:x86-windows
  Vcpkg version: 2020.11.12-nohash

Additionally, attach any relevant sections from the log files above.

How can I solve this problem?

**Comment by shuangzhiaishang** [comment]
after adding set(PORT_DEBUG ON)
This is the output
Starting package 1/20: brotli:x86-windows
Building package brotli[core]:x86-windows...
-- Using cached E:/Program Files (x86)/Microsoft Visual Studio/vcpkg/downloads/google-brotli-e61745a6b7add50d380cfd7d3883dd6c62fc2c71.tar.gz
-- Cleaning sources at E:/Program Files (x86)/Microsoft Visual Studio/vcpkg/buildtrees/brotli/src/6c62fc2c71-a8c4ea9278.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/Program Files (x86)/Microsoft Visual Studio/vcpkg/downloads/google-brotli-e61745a6b7add50d380cfd7d3883dd6c62fc2c71.tar.gz
-- Applying patch install.patch
-- Applying patch fix-arm-uwp.patch
-- Applying patch pkgconfig.patch
-- Using source at E:/Program Files (x86)/Microsoft Visual Studio/vcpkg/buildtrees/brotli/src/6c62fc2c71-a8c4ea9278.clean
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Using msys root at E:/Program Files (x86)/Microsoft Visual Studio/vcpkg/downloads/tools/msys2/c809757c94447846
-- [DEBUG] Using pkg-config from: E:/Program Files (x86)/Microsoft Visual Studio/vcpkg/downloads/tools/msys2/c809757c94447846/mingw32/bin/pkg-config.exe
-- [DEBUG] Release Files: E:/Program Files (x86)/Microsoft Visual Studio/vcpkg/packages/brotli_x86-windows/lib/pkgconfig/libbrotlicommon.pc;E:/Program Files (x86)/Microsoft Visual Studio/vcpkg/packages/brotli_x86-windows/lib/pkgconfig/libbrotlidec.pc;E:/Program Files (x86)/Microsoft Visual Studio/vcpkg/packages/brotli_x86-windows/lib/pkgconfig/libbrotlienc.pc
-- Fixing pkgconfig file: E:/Program Files (x86)/Microsoft Visual Studio/vcpkg/packages/brotli_x86-windows/lib/pkgconfig/libbrotlicommon.pc
-- Fixing pkgconfig file: E:/Program Files (x86)/Microsoft Visual Studio/vcpkg/packages/brotli_x86-windows/lib/pkgconfig/libbrotlidec.pc
-- Fixing pkgconfig file: E:/Program Files (x86)/Microsoft Visual Studio/vcpkg/packages/brotli_x86-windows/lib/pkgconfig/libbrotlienc.pc
-- [DEBUG] Checking package (RELEASE): libbrotlicommon
-- [DEBUG] pkg-config returned:0
-- [DEBUG] pkg-config output:
-- [DEBUG] pkg-config error output:
-- [DEBUG] pkg-config returned:0
-- [DEBUG] pkg-config output:-LE:/Program Files (x86)/Microsoft Visual Studio/vcpkg/packages/brotli_x86-windows/lib -lbrotlicommon
-- [DEBUG] pkg-config error output:
-- [DEBUG] pkg-config returned:0
-- [DEBUG] pkg-config output:-LE:/Program Files (x86)/Microsoft Visual Studio/vcpkg/packages/brotli_x86-windows/lib
-- [DEBUG] pkg-config error output:
-- [DEBUG] -L LIST TRANSFORMATION:';E:/Program##Files##(x86)/Microsoft##Visual##Studio/vcpkg/packages/brotli_x86-windows/lib'
-- [DEBUG] REMOVING:'E:/Program Files (x86)/Microsoft Visual Studio/vcpkg/packages/brotli_x86-windows/lib'
-- [DEBUG] FROM:'-LE:/Program Files (x86)/Microsoft Visual Studio/vcpkg/packages/brotli_x86-windows/lib -lbrotlicommon'
-- [DEBUG] LIBS AFTER -L<path> REMOVAL:';-lbrotlicommon'
-- [DEBUG] pkg-config output lib paths after replacement (cmake style):E:/Program Files (x86)/Microsoft Visual Studio/vcpkg/packages/brotli_x86-windows/lib
-- [DEBUG] pkg-config output lib after replacement (cmake style):-lbrotlicommon
-- [DEBUG] IGNORED FLAGS:''
-- [DEBUG] BEFORE IGNORE FLAGS REMOVAL: -lbrotlicommon
-- [DEBUG] SYSTEM LIBRARIES:'advapi32;bcrypt;dinput8;gdi32;imm32;oleaut32;ole32;psapi;secur32;setupapi;shell32;shlwapi;strmiids;user32;uuid;version;vfw32;winmm;wsock32;Ws2_32;wldap32;crypt32'
-- [DEBUG] LIBRARIES in PC:'-lbrotlicommon'
-- [DEBUG] REMOVING:'advapi32'
-- [DEBUG] FROM:'-lbrotlicommon'
-- [DEBUG] AFTER REMOVAL:'-lbrotlicommon'
-- [DEBUG] REMOVING:'bcrypt'
-- [DEBUG] FROM:'-lbrotlicommon'
-- [DEBUG] AFTER REMOVAL:'-lbrotlicommon'
-- [DEBUG] REMOVING:'dinput8'
-- [DEBUG] FROM:'-lbrotlicommon'
-- [DEBUG] AFTER REMOVAL:'-lbrotlicommon'
-- [DEBUG] REMOVING:'gdi32'
-- [DEBUG] FROM:'-lbrotlicommon'
-- [DEBUG] AFTER REMOVAL:'-lbrotlicommon'
-- [DEBUG] REMOVING:'imm32'
-- [DEBUG] FROM:'-lbrotlicommon'
-- [DEBUG] AFTER REMOVAL:'-lbrotlicommon'
-- [DEBUG] REMOVING:'oleaut32'
-- [DEBUG] FROM:'-lbrotlicommon'
-- [DEBUG] AFTER REMOVAL:'-lbrotlicommon'
-- [DEBUG] REMOVING:'ole32'
-- [DEBUG] FROM:'-lbrotlicommon'
-- [DEBUG] AFTER REMOVAL:'-lbrotlicommon'
-- [DEBUG] REMOVING:'psapi'
-- [DEBUG] FROM:'-lbrotlicommon'
-- [DEBUG] AFTER REMOVAL:'-lbrotlicommon'
-- [DEBUG] REMOVING:'secur32'
-- [DEBUG] FROM:'-lbrotlicommon'
-- [DEBUG] AFTER REMOVAL:'-lbrotlicommon'
-- [DEBUG] REMOVING:'setupapi'
-- [DEBUG] FROM:'-lbrotlicommon'
-- [DEBUG] AFTER REMOVAL:'-lbrotlicommon'
-- [DEBUG] REMOVING:'shell32'
-- [DEBUG] FROM:'-lbrotlicommon'
-- [DEBUG] AFTER REMOVAL:'-lbrotlicommon'
-- [DEBUG] REMOVING:'shlwapi'
-- [DEBUG] FROM:'-lbrotlicommon'
-- [DEBUG] AFTER REMOVAL:'-lbrotlicommon'
-- [DEBUG] REMOVING:'strmiids'
-- [DEBUG] FROM:'-lbrotlicommon'
-- [DEBUG] AFTER REMOVAL:'-lbrotlicommon'
-- [DEBUG] REMOVING:'user32'
-- [DEBUG] FROM:'-lbrotlicommon'
-- [DEBUG] AFTER REMOVAL:'-lbrotlicommon'
-- [DEBUG] REMOVING:'uuid'
-- [DEBUG] FROM:'-lbrotlicommon'
-- [DEBUG] AFTER REMOVAL:'-lbrotlicommon'
-- [DEBUG] REMOVING:'version'
-- [DEBUG] FROM:'-lbrotlicommon'
-- [DEBUG] AFTER REMOVAL:'-lbrotlicommon'
-- [DEBUG] REMOVING:'vfw32'
-- [DEBUG] FROM:'-lbrotlicommon'
-- [DEBUG] AFTER REMOVAL:'-lbrotlicommon'
-- [DEBUG] REMOVING:'winmm'
-- [DEBUG] FROM:'-lbrotlicommon'
-- [DEBUG] AFTER REMOVAL:'-lbrotlicommon'
-- [DEBUG] REMOVING:'wsock32'
-- [DEBUG] FROM:'-lbrotlicommon'
-- [DEBUG] AFTER REMOVAL:'-lbrotlicommon'
-- [DEBUG] REMOVING:'Ws2_32'
-- [DEBUG] FROM:'-lbrotlicommon'
-- [DEBUG] AFTER REMOVAL:'-lbrotlicommon'
-- [DEBUG] REMOVING:'wldap32'
-- [DEBUG] FROM:'-lbrotlicommon'
-- [DEBUG] AFTER REMOVAL:'-lbrotlicommon'
-- [DEBUG] REMOVING:'crypt32'
-- [DEBUG] FROM:'-lbrotlicommon'
-- [DEBUG] AFTER REMOVAL:'-lbrotlicommon'
-- [DEBUG] Library search paths:E:/Program Files (x86)/Microsoft Visual Studio/vcpkg/packages/brotli_x86-windows/lib
-- [DEBUG] Libraries to search:-lbrotlicommon
-- [DEBUG] Library match: CMAKE_MATCH_1:brotlicommon
-- [DEBUG] CHECK_LIB_brotlicommon_RELEASE before:
-- [DEBUG] CHECK_LIB_brotlicommon_RELEASE after: CHECK_LIB_brotlicommon_RELEASE-NOTFOUND
-- [DEBUG] Searching with additional suffixes: '-s;_s;-static;_static'
-- [DEBUG] Search name: 'brotlicommon-s'
-- [DEBUG] CHECK_LIB_brotlicommon-s_RELEASE before:
-- [DEBUG] Search paths:'E:/Program Files (x86)/Microsoft Visual Studio/vcpkg/packages/brotli_x86-windows/lib' 'E:/Program Files (x86)/Microsoft Visual Studio/vcpkg/installed/x86-windows/lib'
-- [DEBUG] CHECK_LIB_brotlicommon-s_RELEASE after: CHECK_LIB_brotlicommon-s_RELEASE-NOTFOUND
-- [DEBUG] Search name: 'brotlicommon_s'
-- [DEBUG] CHECK_LIB_brotlicommon_s_RELEASE before:
-- [DEBUG] Search paths:'E:/Program Files (x86)/Microsoft Visual Studio/vcpkg/packages/brotli_x86-windows/lib' 'E:/Program Files (x86)/Microsoft Visual Studio/vcpkg/installed/x86-windows/lib'
-- [DEBUG] CHECK_LIB_brotlicommon_s_RELEASE after: CHECK_LIB_brotlicommon_s_RELEASE-NOTFOUND
-- [DEBUG] Search name: 'brotlicommon-static'
-- [DEBUG] CHECK_LIB_brotlicommon-static_RELEASE before:
-- [DEBUG] Search paths:'E:/Program Files (x86)/Microsoft Visual Studio/vcpkg/packages/brotli_x86-windows/lib' 'E:/Program Files (x86)/Microsoft Visual Studio/vcpkg/installed/x86-windows/lib'
-- [DEBUG] CHECK_LIB_brotlicommon-static_RELEASE after: CHECK_LIB_brotlicommon-static_RELEASE-NOTFOUND
-- [DEBUG] Search name: 'brotlicommon_static'
-- [DEBUG] CHECK_LIB_brotlicommon_static_RELEASE before:
-- [DEBUG] Search paths:'E:/Program Files (x86)/Microsoft Visual Studio/vcpkg/packages/brotli_x86-windows/lib' 'E:/Program Files (x86)/Microsoft Visual Studio/vcpkg/installed/x86-windows/lib'
-- [DEBUG] CHECK_LIB_brotlicommon_static_RELEASE after: CHECK_LIB_brotlicommon_static_RELEASE-NOTFOUND
-- CHECK_LIB_brotlicommon_RELEASE:CHECK_LIB_brotlicommon_RELEASE-NOTFOUND
CMake Error at scripts/cmake/vcpkg_fixup_pkgconfig.cmake:235 (message):
  Library "brotlicommon" was not found! If it is a system library use the
  SYSTEM_LIBRARIES parameter for the vcpkg_fixup_pkgconfig call! Otherwise,
  correct the *.pc file
Call Stack (most recent call first):
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:301 (vcpkg_fixup_pkgconfig_check_files)
  ports/brotli/portfile.cmake:26 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:136 (include)


Error: Building package brotli:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: brotli:x86-windows
  Vcpkg version: 2020.11.12-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by shuangzhiaishang** [comment]
content in E:\Program Files (x86)\Microsoft Visual Studio\vcpkg\packages\brotli_x86-windows\debug\lib\pkgconfig

prefix=E:/Program Files (x86)/Microsoft Visual Studio/vcpkg/packages/brotli_x86-windows/debug
exec_prefix=E:/Program Files (x86)/Microsoft Visual Studio/vcpkg/packages/brotli_x86-windows/debug
libdir=${prefix}/lib
includedir=${prefix}/include

Name: libbrotlicommon
URL: https://github.com/google/brotli
Description: Brotli common dictionary library
Version: 1.0.9
Libs: -L${libdir} -lbrotlicommon
Cflags: -I${includedir}

**Comment by JonLiu1993** [comment]
@shuangzhiaishang ,Thanks for posting this issue, I can't reproduce your problem in windows 10 environment, can you update vcpkg and reinstall it? the issue inside is the same as yours, maybe it will give you some help. #13166

**Comment by shuangzhiaishang** [comment]
@JonLiu1993 Thanks I've reinstall vcpkg and it's the latest version and i've read #13166 but because of my poor English I can hardly understand what the solution is.Could you tell me exactly what should I do to solve this,if you need more information please let me know.

**Comment by shuangzhiaishang** [comment]
I changed my directory from E:\Program Files (x86)\Microsoft Visual Studio\vcpkg> to E:\dev\vcpkg> and it's installed without problems.
