### ISSUE TITLE
VCPKG_DEFAULT_BINARY_CACHE looks to be ignored

### ISSUE THREAD

**Issue by Ceylo** [microsoft/vcpkg#14922]
I'm using macOS 10.15.7 along with Xcode 12.2. I'm trying to use a custom binary cache directory by following https://github.com/microsoft/vcpkg/blob/master/docs/users/binarycaching.md#configuration

I cloned vcpkg at tag 2020.11, then:
```
$ ./bootstrap-vcpkg.sh
$ VCPKG_DEFAULT_BINARY_CACHE=/tmp/vcpkgcache ./vcpkg install gtest
```

And nothing gets populated in /tmp/vcpkgcache. Obviously, deleting "installed" and "buildtrees" directories then re-running the above vcpkg install reconfigures and recompiles everything.

I didn't try in other platforms, so at best support for VCPKG_DEFAULT_BINARY_CACHE looks incomplete or I missed some (undocumented?) step.

**Comment by JackBoosY** [comment]
@BillyONeal Can you please take a look?

Thanks.

**Comment by Neumann-A** [comment]
maybe the directory does not exists. 
Make sure the directory exists and run the install command with `--debug`

**Comment by BillyONeal** [comment]
I have repro'd the problem and am investigating.
