### ISSUE TITLE
Is it possible to build a port against a different fork/branch/source-tweaks?

### ISSUE THREAD

**Issue by jdx-john** [microsoft/vcpkg#14939]
I am interested in using a project for which a vcpkg port is available, but it is likely we'll need to add changes to the source.
I would much rather continue to use vcpkg but I don't want to be stuck waiting for them to accept a PR (or maybe we have bespoke changes we never share) - is there a way I can use a different git URL for the same project, or otherwise override with my modified source code, against their pre-exisiting build setup?

Whether cleanly, or as some hack is fine. Even to the extent of copying my source on top...no idea if it's possible to decouple vcpkg downloading and building the sources in this way but our changes are likely just to existing CPP files.

_(apologies if I did something wrong, I raised this as a question but it seems uncategorised)_

**Comment by vicroms** [comment]
Yes, you can do custom ports using `--overlay-ports`, example:

Let's imagine you want to modify `zlib` and `ffmpeg`.
 
Copy their port folders to a different location, let's assume `D:/custom-vcpkg-ports/zlib` and then make your changes to the ports. 

Then you can do:

```
./vcpkg install --overlay-ports=D:/custom-vcpkg-ports zlib ffmpeg
```

In the near future we plan to implement custom registries, that will allow you to point vcpkg to a Git repository that contains ports.

**Comment by jdx-john** [comment]
@vicroms that's great, thankyou.
