### ISSUE TITLE
uSockets[ssl] build failure

### ISSUE THREAD

**Issue by Phantomouse** [microsoft/vcpkg#14933]
**Host Environment**
- OS: Windows 10 build 20H2
- Compiler: Visual Studio 2019

**To Reproduce**
`./vcpkg install uSockets[ssl]`

**Failure logs** 
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:145 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j5
    Working Directory: D:/vcpkg/buildtrees/usockets/x86-windows-dbg
    See logs for more information:
      D:\vcpkg\buildtrees\usockets\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:27 (vcpkg_build_cmake)
  ports/usockets/portfile.cmake:34 (vcpkg_install_cmake)
  scripts/ports.cmake:136 (include)

Error: Building package usockets:x86-windows failed with: BUILD_FAILED

[stdout-x86-windows.log](https://github.com/microsoft/vcpkg/files/5639651/stdout-x86-windows.log)
[config-x86-windows-out.log](https://github.com/microsoft/vcpkg/files/5639642/config-x86-windows-out.log)
[install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/5639652/install-x86-windows-dbg-out.log)

**Additional context**
It seems CMAKE can't find some libs from Windows Kits 10 install folder. Tried to reinstall Windows Kits or add lib folder to PATH but nothing changed.

**Comment by PhoebeHui** [comment]
@Phantomouse, thanks for reporting this issue!

I have summited PR #14935 to fix this issue.

**Comment by Phantomouse** [comment]
@PhoebeHui Thanks, works fine for me.
