### ISSUE TITLE
[libpng] Different rules to link against libpng on different platforms

### ISSUE THREAD

**Issue by smoked-herring** [microsoft/vcpkg#14930]
****

**Is your feature request related to a problem? Please describe.**
Linking against libpng requires different cmake commands on different platforms. On Windows it's

```
    find_package(libpng CONFIG REQUIRED)
    target_link_libraries(main PRIVATE png)
```

On Linux:

```
    find_package(libpng CONFIG REQUIRED)
    target_link_libraries(main PRIVATE png_static)
```

**Proposed solution**
Fix libpng to export the same cmake commands to include libpng in a cross-platform project. For example, like we do with libpng-turbo:

```
find_package(JPEG REQUIRED)
target_link_libraries(main PRIVATE ${JPEG_LIBRARIES})
target_include_directories(main PRIVATE ${JPEG_INCLUDE_DIR})
```

**Describe alternatives you've considered**
if/else branching:

```
if (WIN32)
    find_package(libpng CONFIG REQUIRED)
    target_link_libraries(main PRIVATE png)
else()
    find_package(libpng CONFIG REQUIRED)
    target_link_libraries(main PRIVATE png_static)
endif()
```

**Additional context**
None

**Comment by Neumann-A** [comment]
a) that is an upstream issue.
b) you could use https://cmake.org/cmake/help/latest/module/FindPNG.html instead of the config

**Comment by smoked-herring** [comment]
`FindPNG` has a similar issue on Linux:

```
        find_package(PNG)
        target_link_libraries(png-test PRIVATE png)
```

results in

```
usr/bin/ld: /home/rob/src/git.vcpkg/installed/x64-linux/lib/libpng.a(png.c.o): in function `png_build_16bit_table':
png.c:(.text+0x4b50): undefined reference to `pow'
```

It looks like `FindPNG` is not aware of the fact that libpng could be built statically, and doesn't add `-lm` on Linux. So I still need

```
    if (WIN32)
        find_package(PNG)
        target_link_libraries(png-test PRIVATE png)
    else()
        find_package(PNG)
        target_link_libraries(png-test PRIVATE png m)
    endif()
```

Maybe it's worth patching libpng in vcpkg so it exports the same linking target ("png") on all platforms?

**Comment by Neumann-A** [comment]
>Maybe it's worth patching libpng in vcpkg so it exports the same linking target ("png") on all platforms?

No since upstream is in control of its exported targets and all downstream targets will depend on that naming. 

If you don't like the if else block use a generator expression in the target_link_libraries instead. Just chain `$<IF:condition,true_string,false_string>` and `$<TARGET_EXISTS:target>` with the exported targets or use `$<PLATFORM_ID:platform_ids>` to conditionally link `-lm`. An alternative would be to supply an patch upstream to libpng.

**Comment by smoked-herring** [comment]
OK, thanks for the clarification.
