### ISSUE TITLE
[realsense2] CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:145

### ISSUE THREAD

**Issue by mohdsuperb** [microsoft/vcpkg#14949]
**Host Environment**

OS: Windows 10 build 20H2
Compiler: Visual Studio 2019

**To Reproduce**
./vcpkg install realsense2

**Failure logs**
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:145 (message):
    Command failed: C:/Users/khmohd/vcpkg/downloads/tools/cmake-3.18.4-windows/cmake-3.18.4-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v -j9
    Working Directory: C:/Users/khmohd/vcpkg/buildtrees/realsense2/x86-windows-dbg
    See logs for more information:
      C:\Users\khmohd\vcpkg\buildtrees\realsense2\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:27 (vcpkg_build_cmake)
  ports/realsense2/portfile.cmake:47 (vcpkg_install_cmake)
  scripts/ports.cmake:136 (include)

Error: Building package realsense2:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: realsense2:x86-windows
  Vcpkg version: 2020.11.12-nohash

Additionally, attach any relevant sections from the log files above.
[install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/5646025/install-x86-windows-dbg-out.log)

**Comment by StarGate-One** [comment]
1. The log file has many errors containing: ` fatal error C1083: Cannot open include file: 'atlstr.h': No such file or directory`
2. Make sure you have installed option `C++ ATL for latest v142 build tools (x86 & x64)` in Visual Studio.
![image](https://user-images.githubusercontent.com/68293825/101268597-cea8e600-3732-11eb-8fdd-9821490ddce7.png)

**Comment by NancyLi1013** [comment]
Hi @mohdsuperb 

Thanks for posting this issue.

Please also refer to this https://developercommunity.visualstudio.com/content/problem/518592/2019-fatal-error-c1083-cannot-open-include-file-at.html.

**Comment by NancyLi1013** [comment]
Please try to use the above guidelines to rebuild this port. Feel free to reopen this issue if it is still a problem for you.
