### ISSUE TITLE
FontConfig misnamed DLL (x64-windows)

### ISSUE THREAD

**Issue by gnieboer** [microsoft/vcpkg#14944]
**Host Environment**
- OS: x64-windows
- Compiler: VS2019?
- vcpkg date of last pull: 12/3/2020

**To Reproduce**
`./vcpkg install cairo`
cairo will install fontconfig and then link against it
Run depends.exe or similar on cairo.dll found in .../installed/x64-windows/bin
cairo.dll will be dependent on "libfontconfig-1.dll"
But the fontconfig package installs "fontconfig-1.dll" 
so load of the DLL will fail

**Failure logs** 
![image](https://user-images.githubusercontent.com/3222377/101177195-8647d600-3615-11eb-8dd9-2a19796539bd.png)

**Additional context**
The Cairo cmake cache shows it finding the correct fontconfig.lib file, but in the /lib directory, fontconfig.def ends with "LIBRARY libfontconfig-1.dll", and the .lib file references libfontconfig-1.dll so Cairo is linking to the DLL fontconfig provides, but it doesn't exist as FontConfig actually outputs fontconfig-1.dll (which would be the correct windows naming convention).

Recommend altering the fontconfig build to target that naming standard.

**Comment by gnieboer** [comment]
So I think the problem is not really Cairo's problem, it's FontConfig's.  

The Cairo cmake cache shows it finding the correct fontconfig.lib file, but in the /lib directory, fontconfig.def ends with "LIBRARY libfontconfig-1.dll", and the .lib file references libfontconfig-1.dll so Cairo is linking to the DLL fontconfig provides, but it doesn't exist as FontConfig actually outputs fontconfig-1.dll (which would be the correct windows naming convention). 

Recommend altering the fontconfig build to target that naming standard.

**Comment by Neumann-A** [comment]
`src/Makefile.am` line `58` probably needs to be patched from 
```
fontconfig.lib : libfontconfig.la
	lib -name:libfontconfig-@LIBT_CURRENT_MINUS_AGE@.dll -def:fontconfig.def -out:$@
```
to
```
fontconfig.lib : libfontconfig.la
	lib -name:fontconfig-@LIBT_CURRENT_MINUS_AGE@.dll -def:fontconfig.def -out:$@
```
