### ISSUE TITLE
[osgEarth] update to 3.1

### ISSUE THREAD

**Issue by chuyanjuncn** [microsoft/vcpkg#14942]
Library name:  osgEarth

New version number:   3.1

Other information that may be useful (release notes, etc...)

https://github.com/gwaldron/osgearth/releases/tag/osgearth-3.1

**Comment by NancyLi1013** [comment]
Hi @chuyanjuncn 

Thanks for posting this issue. `osgearth `has been updated to 3.1 in vcpkg master. Please try to update vcpkg to the latest version to rebuild.
