### ISSUE TITLE
How do I find the generated .vcxproj files?

### ISSUE THREAD

**Issue by jdx-john** [microsoft/vcpkg#14940]
Apologies if I misunderstood totally but I thought vcpkg internally uses CMake to build C++ ports? I am using VS2019 and so I expected CMake would create .vcxproj projects which VS then builds - it's been many years since I last used CMake.

Inspecting the folders on disk, I can see some of the dependency libs _do_ have vcxproj files but not the port I'm building. I want to inspect these files to see how the dependencies are working... is vcpkg maybe deleting them after installing the port, if so can I ask it not to?

**Comment by vicroms** [comment]
May I ask why do you need the project files for the libraries? 

Vcpkg builds the libraries from source using whatever build system the upstream library uses. Many of the libraries in vcpkg don't use MS Build at all. So there are no project files whatsoever.

The intended use for vcpkg is for you to link the libraries built by vcpkg in your project. If you are using Visual Studio with MS Build then after running `vcpkg integrate install` all libraries installed with vcpkg will be available for you to use in your projects.

If you're using CMake, you need to pass `-DCMAKE_TOOLCHAIN_FILE` to your command line invocation (again, if you're using Visual Studio 2019 there's some automatic integration after running `vcpkg integrate install`).

**Comment by jdx-john** [comment]
@vicroms I need to pre-build a port and add the binaries+headers to our bespoke (ancient) toolchain package that all our developers use for various precompiled libs. This will likely involve a mess of dependency include folders so I figured if I could see a project file, I could save some time finding them all.

I assume that `vcpkg integrate install` isn't a solution for my use case of centralised building the library, since developers won't individually have vcpkg installed? Or _can_ I run this on my dev machine and inspect/export the changes it makes to VS for others to re-use?

Ideally we might add vcpkg to development workstations as part of the toolchain, but realistically this is unlikely for a single library on such an old codebase that is not being heavily developed.

If that wasn't clear let me know and I'll try harder!

**Comment by jdx-john** [comment]
I suppose a linked question is, what _exactly_ does `integrate` _do_? I understand the functionality (https://docs.microsoft.com/en-us/cpp/build/vcpkg?view=msvc-160#integrate-with-visual-studio-windows) but not what changes it actually makes, and where?

**Comment by linquize** [comment]
vcpkg may build the libraries with **ninja** internally,  if possible.  In this case, **.vcxproj** is not generated.

**Comment by vicroms** [comment]
The output of vcpkg goes to predefined locations.

Note: all paths below are prefixed by `{VCPKG_ROOT}/installed/{target triplet}`, e.g.: D:\vcpkg\installed\x64-windows`.

* Header files go into `include/`
* Library files (`.lib`) go into `lib/` or `debug/lib` depending on configuration (release or debug)
* Shared library files (`.dll`) go into `bin/` or `debug/bin` depending on configuration (release or debug)
* If a library defines its own `main` then you'll find their (`.lib`, e.g.: SDL2) files in `lib/manual-link/` or `debug/lib/manual-link`
* If a library produces executables (`.exe`} they will be found in `tools`
* Any other output, like CMake integration files, documentation, license, etc. Goes into `share/`.

**Comment by jdx-john** [comment]
@vicroms what does `integrate install` actually _do_? i.e. it makes VS know to look in `{VCPKG_ROOT}/installed/include` for `#include` but where in VS can I find this setting? I'm assuming it's some visible option not a hidden setting.

**Comment by vicroms** [comment]
I'm not sure about the specifics of `integrate install`. cc @ras0219-msft @dan-shaw 

I think `vcpkg integrate install` writes a few files to `%LOCALAPPDATA%/vcpkg`, Visual Studio knows to look into that location to detect if a user has vcpkg installed.  The files contain the location of the vcpkg instance. Then Visual Studio sets up the correct paths (add include paths, add lib paths) accordingly.

**Comment by PhoebeHui** [comment]
@jdx-john, does this still be a question for you?

**Comment by jdx-john** [comment]
@PhoebeHui how would I do this?

**Comment by PhoebeHui** [comment]
If you create a cmake project via visual studio, you can update it by editting the CMakeSettings.json file:

![image](https://user-images.githubusercontent.com/20694052/110310502-97054f00-803d-11eb-8acf-f780ca87f0c8.png)

**Comment by PhoebeHui** [comment]
@jdx-john, have you try above suggestion? does it work for you?

**Comment by PhoebeHui** [comment]
@jdx-john, please reopen this issue if it still be a question for you.
