### ISSUE TITLE
[New Port Request] bgfx

### ISSUE THREAD

**Issue by Pevernow** [microsoft/vcpkg#14955]
Library name:bgfx

Library description:Cross-platform, graphics API agnostic, "Bring Your Own Engine/Framework" style rendering library

Source repository URL:https://github.com/bkaradzic/bgfx

Project homepage (if different from the source repository):https://bkaradzic.github.io/bgfx/overview.html

Anything else that is useful to know when adding (such as optional features the library may have that should be included):bx,bimg

May be it can help us to add this port: https://github.com/widberg/bgfx.cmake

**Comment by ompadu** [comment]
I'd also like to support this port request

**Comment by PhoebeHui** [comment]
Related to https://github.com/microsoft/vcpkg/pull/10465

**Comment by Brouilles** [comment]
Also interested.

**Comment by michaelkroener** [comment]
https://github.com/julianxhokaxhiu/FFNx/tree/master/.vcpkg/ports/bgfx
This project has a custom repository including bgfx

**Comment by bwrsandman** [comment]
I wrote a local port using the cmake wrapper from https://github.com/bkaradzic/bgfx

```json
{
  "name": "bgfx",
  "version-date": "2021-10-30",
  "description": "Cross-platform, graphics API agnostic, Bring Your Own Engine/Framework style rendering library.",
  "homepage": "https://github.com/bkaradzic/bgfx",
  "dependencies": [
    {
      "name": "vcpkg-cmake",
      "host": true
    },
    {
      "name": "vcpkg-cmake-config",
      "host": true
    }
  ],
  "features": {
    "tools": {
      "description": "Shader, Texture and Geometry compilers for bgfx"
    }
  }
}
```

```cmake
# For a list of common variables see https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_common_definitions.md

vcpkg_check_linkage(ONLY_STATIC_LIBRARY)

vcpkg_from_github(OUT_SOURCE_PATH SOURCE_PATH
    REPO "bkaradzic/bgfx.cmake"
    HEAD_REF master
    REF a01e8e043fe213a55b0bea9623f45fad80d067bc
    SHA512 9967046cea4ad9c00126cd112089ac8aa099ea2db08dc1691f6bcf2aa95e8e5c6e52c6b98a9542b5c4232d712041aca211b6fc8f98c97e69b308de8fa8a3237b
)

vcpkg_from_github(OUT_SOURCE_PATH SOURCE_PATH_BX
    REPO "bkaradzic/bx"
    HEAD_REF master
    REF 51c326484623c719bf0d0de8ff7ca0511a01feb4
    SHA512 acba2375c5f17deff1a53121e1fee27f014fdac7748d7d933210120b5b6e21fc07eb5d2b463faaf2396358a3c70cc169ef8b68dbcb39708a94411fb22935b5fd
)

vcpkg_from_github(OUT_SOURCE_PATH SOURCE_PATH_BIMG
    REPO "bkaradzic/bimg"
    HEAD_REF master
    REF 9e4d2b167ffb4ecf4dba625dee59f6be7cf2587a
    SHA512 dfb8b8e87282d520347f587eab6cb7074c71f4379d42b0e96aec8b30c57f5b320dd6f2ef2ba3b0a8807e3b022f6a9aaebf629f2629458868bcb09a9c1be24e65
)

vcpkg_from_github(OUT_SOURCE_PATH SOURCE_PATH_BGFX
    REPO "bkaradzic/bgfx"
    HEAD_REF master
    REF 932d2f21e7b6c327ef536f9ce868222049a29078
    SHA512 a309e142fad01548d99d381d1372c44d1a5ce66f5b5324d143ee839713e20fd30e529a103800c5b0f25fe9355d671e473bc5def333f26db90bcfb3c11a82a23e
)

vcpkg_check_features(OUT_FEATURE_OPTIONS FEATURE_OPTIONS
    FEATURES
        tools       BGFX_BUILD_TOOLS
)

vcpkg_cmake_configure(
    SOURCE_PATH ${SOURCE_PATH}
    OPTIONS
        -DBX_DIR=${SOURCE_PATH_BX}
        -DBIMG_DIR=${SOURCE_PATH_BIMG}
        -DBGFX_DIR=${SOURCE_PATH_BGFX}
        -DBGFX_LIBRARY_TYPE="STATIC"
        -DBGFX_BUILD_EXAMPLES="OFF"
        ${FEATURE_OPTIONS}
)

vcpkg_cmake_install()
vcpkg_cmake_config_fixup(CONFIG_PATH "lib/cmake/${PORT}")
vcpkg_copy_pdbs()

if (BGFX_BUILD_TOOLS)
    vcpkg_copy_tools(
        TOOL_NAMES shaderc geometryc geometryv texturec texturev
        AUTO_CLEAN)
endif()

# Handle copyright
file(INSTALL "${CURRENT_PACKAGES_DIR}/share/licences/${PORT}/LICENSE" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)

file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/share/licences"
                    "${CURRENT_PACKAGES_DIR}/debug/include"
                    "${CURRENT_PACKAGES_DIR}/debug/share"
                    "${CURRENT_PACKAGES_DIR}/debug/bin")
```

**Comment by MrROBUST** [comment]
Just checked the @bwrsandman port localy with [this example](https://github.com/pr0g/sdl-bgfx-imgui-starter) and it works perfectly for VS2022!
I think it worth to update vcpkg_from_github REFs add the amagamated cmake options:
-DBGFX_AMALGAMATED=On
-DBX_AMALGAMATED=On

**Comment by arsdever** [comment]
Any update on this thread?

**Comment by bwrsandman** [comment]
We use a local manifest and it works fine for our needs https://github.com/openblack/openblack/tree/master/.vcpkg/ports/bgfx
@bkaradzic probably would probably want to be aware of a port hosted on vcpkg

**Comment by JackBoosY** [comment]
@bwrsandman I request your permission to add this port using your code.

**Comment by bwrsandman** [comment]
My issue with giving you permission to add this port or to do it myself is that the library owner, @bkaradzic, has expressed concerns with releasing bgfx on package managers.
If he is okay with it, I would gladly add and maintain the port.

**Comment by bwrsandman** [comment]
There are also technical issue and conflicts with other packages to resolve.
Off the top of my head is shaderc and the spirv libraries that are used.

**Comment by bwrsandman** [comment]
Looks like he has changed his mind
https://discord.com/channels/712512073522872352/712512073522872355/1023083285989052477
https://discord.com/channels/712512073522872352/712512073522872355/1023084750178619412
https://discord.com/channels/712512073522872352/712512073522872355/1048305080723574945
