### ISSUE TITLE
How to let a custome port be built in C++17?

### ISSUE THREAD

**Issue by playgithub** [microsoft/vcpkg#14965]
I have to custom port `poppler`, while `vcpkg install poppler` succeeded, it could be used in a C++14 project in VS2019, but when changed to C++17, there is a link error.
How to let the custome port be built in C++17?

In poppler's `CMakeLists.txt`, there is `set(CMAKE_CXX_STANDARD 14)`, does it mean a patch is necessary?

**Comment by vicroms** [comment]
If you want to test quickly, it may be worth a try, setting it during the configure call. 

```cmake
vcpkg_configure_cmake(
    ...
    -DCMAKE_CXX_STANDARD 17
)
```

But if that doesn't work, then yes, you would need to patch that line out.

I would also recommend setting `CMAKE_CXX_STANDARD` as part of a custom triplet.
