### ISSUE TITLE
What is the most convenient way to find out SHA512 in vcpkg_from_github?

### ISSUE THREAD

**Issue by playgithub** [microsoft/vcpkg#14968]
Take poppler for exmaple, 

.tar.gz at https://github.com/freedesktop/poppler/releases/tag/poppler-20.12.0 is different from the file download by
```
vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO freedesktop/poppler
	REF 8766a45a1e101538724d2b767b3efd0ec210357c # poppler-20.12.0
    SHA512 6211a6cebe21ebeb1dd3eb29e552d8ed7c809c295f702710a90882b8c188a9e2ca7957a5a48242662a71354af364a6e9fb3e57bbf9063cbb75022b2e5341b3c5
    HEAD_REF master
)
```
so the SHA512 is different.

**Comment by Hoikas** [comment]
Run `vcpkg build poppler` - the build will error and tell you the expected hash.

**Comment by StarGate-One** [comment]
1. Download the file to a temp directory: 
Example: `C:\Temp`
2. vcpkg hash <file> [alg] - Hash a file by specific algorithm, **default SHA512**
Example: `vcpkg hash C:\Temp\poppler-poppler-20.12.0.tar.gz`
da08c45a2c361beb25ac391a71f7516d5442577ede40e4e4464ea006b66b9243a855333330090ed08a303c2e4aece7d4734f202b7f5072fdbf75cc038993692d

**Comment by felixf4xu** [comment]
> According to https://vcpkg.readthedocs.io/en/latest/maintainers/vcpkg_from_github, temporarily set SHA512 to 0, vcpkg install , get the SHA512 from the error message.

new link address: https://learn.microsoft.com/en-us/vcpkg/maintainers/functions/vcpkg_from_github#parameters
