### ISSUE TITLE
[opencv2] build failure

### ISSUE THREAD

**Issue by Elizraa** [microsoft/vcpkg#14961]
**Host Environment**
- OS: Windows
- Compiler: revision

**To Reproduce**
`vcpkg install opencv2:x86-windows`

**Failure logs** 
  Package: opencv2:x86-windows
  Vcpkg version: 2020.11.12-nohash
**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by vicroms** [comment]
Hi @Elizraa 

I wasn't able to reproduce this issue.
Please provide the failure logs for `vcpkg install opencv2:x86-windows`.

**Comment by Elizraa** [comment]
Sorry, the failure log say about opencv4 is already installed, even though I don't remember installing it, but now I already solved this issue by doing

vcpkg uninstall opencv4

Thank you
