### ISSUE TITLE
What is the default value for VCPKG_CRT_LINKAGE for msvc?

### ISSUE THREAD

**Issue by playgithub** [microsoft/vcpkg#14973]
and any way to query VCPKG_CRT_LINKAGE of an installed package?

**Comment by JackBoosY** [comment]
For static library on Windows, it should be `static` --- `MT/MTd`.
For dynamic library, the default value is `dynamic` --- `MD/MDd`, and you can set it to `static`.
See [documentation](https://docs.microsoft.com/en-us/cpp/build/reference/md-mt-ld-use-run-time-library?view=msvc-160).

**Comment by playgithub** [comment]
How to query an installed package for this?

**Comment by playgithub** [comment]
Thanks
The binary name shows the link type

**Comment by playgithub** [comment]
@JackBoosY 
In "vcpkg-root\installed\x64-windows\bin", the file names are like this:
`boost_chrono-vc142-mt-x64-1_74.dll`
Is it linked statically with C runtime library?
But I have used the default settings, except setting `VCPKG_DEFAULT_TRIPLET=x64-windows` as an environment variable.
