### ISSUE TITLE
[VTK]: Using find_package(VTK....) in a outside project leads to CMake Error

### ISSUE THREAD

**Issue by dweckmann** [microsoft/vcpkg#14978]
**Describe the bug**
We have a big project that use VTK, and specifically `vtkIOImport` component. By doing:

```cmake
find_package(VTK QUIET COMPONENTS vtkIOImport REQUIRED)
```

CMake returns:

```
CMake Error at E:/Work/vcpkg/installed/x64-windows/share/vtk/FindLZ4.cmake:2 (set_target_properties):
  Attempt to promote imported target "lz4::lz4" to global scope (by setting
  IMPORTED_GLOBAL) which is not built in this directory.
```

Which seems perfectly normal since the `find_package()` is done outside VTK source or VCPKG tree.

**Environment**
- OS: Winwdows 10 x64
- Compiler: Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29334 for x64
- Triplet: x64-windows
- CMake: cmake version 3.19.1

**To Reproduce**
Use

```cmake
find_package(VTK QUIET COMPONENTS vtkIOImport REQUIRED)
```

in a CMakeList.txt, outside VCPKG tree.

**Expected behavior**
No CMake errors

**Additional context**

A quick fix is to simply delete the `FindLZ4.cmake` in `vcpkg\installed\x64-windows\share\vtk`. Or, for a cleaner solution, to patch the port file to remove it prior installing. Not sure this should not be done for some other `FindXXX.cmake` as it seems that the:

```cmake
set_target_properties(XXXX PROPERTIES IMPORTED_GLOBAL TRUE)
```

are problematic, and  `vcpkg\installed\x64-windows\share\lz4` should provide what is required to use LZ4, even for VTK, ITK, PCL, OpenCV, Paraview..

If removing `FindLZ4.cmake` is the right way to fix that, I could propose a PR for that.

Regards,

**Comment by nil-is-lin** [comment]
> find_package(vtk CONFIG REQUIRED)
> ...
> target_link_libraries(${PROJECT_NAME} PRIVATE LZ4::LZ4 OGG::OGG VTK::lz4 VTK::ogg)
then cmake, it throw
1> CMake generation started for default configuration: 'x64-Debug (default)'.
1> Found and using vcpkg toolchain file (E:/vcpkg/scripts/buildsystems/vcpkg.cmake).
1> Command line: "cmd.exe" /c "%SYSTEMROOT%\System32\chcp.com 65001 >NUL && "C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe"  -G "Ninja"  -DCMAKE_BUILD_TYPE:STRING="Debug" -DCMAKE_INSTALL_PREFIX:PATH="G:\vcpkg_project\test_hello_window\out\install\x64-Debug (default)" -DCMAKE_C_COMPILER:FILEPATH="C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe" -DCMAKE_CXX_COMPILER:FILEPATH="C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe"  -DCMAKE_MAKE_PROGRAM="C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\Ninja\ninja.exe" -DCMAKE_TOOLCHAIN_FILE="E:/vcpkg/scripts/buildsystems/vcpkg.cmake" "G:\vcpkg_project\test_hello_window" 2>&1"
1> Working directory: G:\vcpkg_project\test_hello_window\out\build\x64-Debug (default)
1> [CMake] -- Searching for PEGTL
1> [CMake] -- Searching for PEGTL - found target taocpp::pegtl
1> [CMake] CMake Error at E:/vcpkg/installed/x64-windows/share/vtk/patches/99/FindHDF5.cmake:4 (set_target_properties):
1> [CMake]   Attempt to promote imported target "hdf5::hdf5-shared" to global scope (by
1> [CMake]   setting IMPORTED_GLOBAL) which is not built in this directory.
1> [CMake] Call Stack (most recent call first):
1> [CMake]   E:/vcpkg/installed/x64-windows/share/hdf5/vcpkg-cmake-wrapper.cmake:17 (_find_package)
1> [CMake]   E:/vcpkg/scripts/buildsystems/vcpkg.cmake:573 (include)
1> [CMake]   E:/vcpkg/installed/x64-windows/share/vtk/VTK-vtk-module-find-packages.cmake:256 (find_package)
1> [CMake]   E:/vcpkg/installed/x64-windows/share/vtk/vtk-config.cmake:129 (include)
1> [CMake]   E:/vcpkg/scripts/buildsystems/vcpkg.cmake:622 (_find_package)
1> [CMake]   gtest/CMakeLists.txt:21 (find_package)
1> [CMake] CMake Error at E:/vcpkg/installed/x64-windows/share/vtk/patches/99/FindHDF5.cmake:13 (set_target_properties):
1> [CMake]   Attempt to promote imported target "hdf5::hdf5_hl-shared" to global scope
1> [CMake]   (by setting IMPORTED_GLOBAL) which is not built in this directory.
1> [CMake] Call Stack (most recent call first):
1> [CMake]   E:/vcpkg/installed/x64-windows/share/hdf5/vcpkg-cmake-wrapper.cmake:17 (_find_package)
1> [CMake]   E:/vcpkg/scripts/buildsystems/vcpkg.cmake:573 (include)
1> [CMake]   E:/vcpkg/installed/x64-windows/share/vtk/VTK-vtk-module-find-packages.cmake:256 (find_package)
1> [CMake]   E:/vcpkg/installed/x64-windows/share/vtk/vtk-config.cmake:129 (include)
1> [CMake]   E:/vcpkg/scripts/buildsystems/vcpkg.cmake:622 (_find_package)
1> [CMake]   gtest/CMakeLists.txt:21 (find_package)
1> [CMake] -- Searching for PEGTL
1> [CMake] -- Searching for PEGTL - found target taocpp::pegtl
1> [CMake] CMake Error at E:/vcpkg/installed/x64-windows/share/vtk/FindPEGTL.cmake:26 (set_target_properties):
1> [CMake]   Attempt to promote imported target "taocpp::pegtl" to global scope (by
1> [CMake]   setting IMPORTED_GLOBAL) which is not built in this directory.
1> [CMake] Call Stack (most recent call first):
1> [CMake]   E:/vcpkg/scripts/buildsystems/vcpkg.cmake:622 (_find_package)
1> [CMake]   E:/vcpkg/installed/x64-windows/share/vtk/VTK-vtk-module-find-packages.cmake:491 (find_package)
1> [CMake]   E:/vcpkg/installed/x64-windows/share/vtk/vtk-config.cmake:129 (include)
1> [CMake]   E:/vcpkg/scripts/buildsystems/vcpkg.cmake:622 (_find_package)
1> [CMake]   gtest/CMakeLists.txt:21 (find_package)
1> [CMake] CMake Error at E:/vcpkg/installed/x64-windows/share/vtk/FindLZ4.cmake:2 (set_target_properties):
1> [CMake]   Attempt to promote imported target "lz4::lz4" to global scope (by setting
1> [CMake]   IMPORTED_GLOBAL) which is not built in this directory.
1> [CMake] Call Stack (most recent call first):
1> [CMake]   E:/vcpkg/scripts/buildsystems/vcpkg.cmake:622 (_find_package)
1> [CMake]   E:/vcpkg/installed/x64-windows/share/vtk/VTK-vtk-module-find-packages.cmake:1008 (find_package)
1> [CMake]   E:/vcpkg/installed/x64-windows/share/vtk/vtk-config.cmake:129 (include)
1> [CMake]   E:/vcpkg/scripts/buildsystems/vcpkg.cmake:622 (_find_package)
1> [CMake]   gtest/CMakeLists.txt:21 (find_package)
1> [CMake] -- Configuring incomplete, errors occurred!
1> [CMake] See also "G:/vcpkg_project/test_hello_window/out/build/x64-Debug (default)/CMakeFiles/CMakeOutput.log".
1> [CMake] See also "G:/vcpkg_project/test_hello_window/out/build/x64-Debug (default)/CMakeFiles/CMakeError.log".

**Comment by Neumann-A** [comment]
change
```
+find_package(LZ4 CONFIG REQUIRED)
+set_target_properties(lz4::lz4 PROPERTIES IMPORTED_GLOBAL TRUE)
+add_library(LZ4::LZ4 ALIAS lz4::lz4)
```
to
```
+find_package(LZ4 CONFIG REQUIRED)
+if(NOT TARGET LZ4::LZ4)
+    add_library(LZ4::LZ4 INTERFACE IMPORTED)
+    target_link_libraries(LZ4::LZ4 INTERFACE lz4::lz4)
+endif()
```
(and fix the git diff header)

I found that using an imported interface target instead of an alias is more robust and less problematic in general.

**Comment by JackBoosY** [comment]
Duplicated to #9947.

**Comment by dweckmann** [comment]
> change

I forgot to reply, but yes your suggestion is working ! Thanks

**Comment by drescherjm** [comment]
I believe I am still experiencing this with the current vtk in vcpkg.

**Comment by JackBoosY** [comment]
@drescherjm 
But I saw the changes is :
```
+find_package(LZ4 CONFIG REQUIRED)
+set_target_properties(lz4::lz4 PROPERTIES IMPORTED_GLOBAL TRUE)
+if(NOT TARGET LZ4::LZ4)
+add_library(LZ4::LZ4 ALIAS lz4::lz4)
+endif()
```

**Comment by drescherjm** [comment]
For me having 
set_target_properties(lz4::lz4 PROPERTIES IMPORTED_GLOBAL TRUE)

causes the error that was originally reported. If you delete the FindLZ4.cmake file from the installed\x64-windows\share\vtk folder or use the fix from https://github.com/microsoft/vcpkg/issues/14978#issuecomment-740077047 it works.

**Comment by JackBoosY** [comment]
@drescherjm Okay, thanks for your info, I will fix this later.

**Comment by dg0yt** [comment]
> For me having
> 
> ```cmake
> set_target_properties(lz4::lz4 PROPERTIES IMPORTED_GLOBAL TRUE)
> ```
> 
> causes the same error that was originally reported when using vtk in a project that uses cmake

I guess `set_target_properties(lz4::lz4 PROPERTIES IMPORTED_GLOBAL TRUE)` breaks if the `lz4..lz4` target wasn't  created in the immediate line before but by a transitive `find_package(lz4 ...)` for another dependency before. So don't modify `IMPORTED_GLOBAL` unless you created it in the same file.

> I will fix this later.

There is #23352.

**Comment by drescherjm** [comment]
Thanks.

**Comment by drescherjm** [comment]
I am sure this will fix the issue but will test tomorrow or Saturday with a clean vcpkg and report if there is any issue.

**Comment by drescherjm** [comment]
Found a related problem in the recent LZMA patch. I commented on that pull request.
