### ISSUE TITLE
bzip2 build failure

### ISSUE THREAD

**Issue by trangtv57** [microsoft/vcpkg#14974]
**Host Environment**
- OS: ubuntu 16.04

**To Reproduce**
`./vcpkg install bzip2

**Failure logs**
 Building package bzip2[core]:x64-linux...
-- Fetching https://sourceware.org/git/bzip2.git...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:108 (message):
    Command failed: /usr/bin/git fetch https://sourceware.org/git/bzip2.git 75a94bea3918e612b879d6a11ca64b8689526147 --depth 1 -n
    Working Directory:/vcpkg/downloads/git-tmp
    Error code: 128
    See logs for more information:
../vcpkg/buildtrees/bzip2/git-fetch-x64-linux-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_git.cmake:80 (vcpkg_execute_required_process)
  ports/bzip2/portfile.cmake:1 (vcpkg_from_git)
  scripts/ports.cmake:136 (include)

Error: Building package bzip2:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: bzip2:x64-linux
  Vcpkg version: 2020.11.12-unknownhash

**Comment by StarGate-One** [comment]
@trangtv57 cc: @JonLiu1993 
- You may wish to read issue **[vcpkg_from_git] fetching explicit ref using old gits fails #14424** for background information
   - What version of git is installed?
   - Open a terminal and type `git --version`
- We have found older versions of git (at least 2.7.x and older) do not work with some modern created git repositories.
- An interim fix would be to upgrade the version of git... as Ubuntu 16.04 LTS has an older version of git installed by default.
- You most likely will have to go outside the normal package manager.
