### ISSUE TITLE
Any way to find out build params?

### ISSUE THREAD

**Issue by playgithub** [microsoft/vcpkg#14982]
Because on Windows different C++ standards are not always compatible.
e.g.
When I'm using `wxWidgets` and `poppler` together in an app using C++17 in Visual Studio 2019.
The code is very simple
```
#define WXUSINGDLL
#include <wx/log.h> // this leads to memory leak, if comment out this line, no memory leak will
#include <poppler/cpp/poppler-page.h>

int main()
{
    poppler::page * __page = nullptr;
    if (__page != nullptr)
        delete __page;
    return 0;
}
```

`poppler` causes link error, after check the `CMakeLists.txt`, It is not hard to know it uses C++14. After patching it to use C++17, the link error is gone.
But the app leaks when using `wxWidgets` and `poppler` together, I can't find what C++ standard does `wxWdigets` use easily.
Is there any way to find out build params? e.g.
* C++ standard
* CRT link type
...

**Comment by BillyONeal** [comment]
These seem to be questions you would need to bring up with the developers of poppler or wxwidgets, not with vcpkg. We only package the library in question, we are not the clearinghouse for all potential upstream bugs.

**Comment by playgithub** [comment]
OK, incompatibility in this case is an exception, so it should be fixed by the lib.
