### ISSUE TITLE
[New Port Request] mathfu

### ISSUE THREAD

**Issue by rlam1** [microsoft/vcpkg#14987]
Library name: MathFu

Library description: MathFu is a C++ math library developed primarily for games focused on simplicity and efficiency.

Source repository URL: https://github.com/google/mathfu

Project homepage (if different from the source repository): https://google.github.io/mathfu/

Anything else that is useful to know when adding (such as optional features the library may have that should be included): The library has support for x86 and ARM SIMD instructions that can be configured using the build configurator specified at https://google.github.io/mathfu/group__mathfu__build__config.html

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by cyrilcourvoisier** [comment]
Why was this request closed? Do you plan to include MathFu in the future?
