### ISSUE TITLE
Provide pre-built binaries through GitHub action

### ISSUE THREAD

**Issue by Banyc** [microsoft/vcpkg#14995]
****

**Is your feature request related to a problem? Please describe.**

There are no pre-built binaries available.

It is too expensive to build vcpkg in some machines. It includes massive time consumption:

- on cloning the whole repository,
- on the building process,
- and on possible trouble-shootings.

If the prebuilt releases are available, it has advantages of:

- reducing the costs listed above,
- reducing the total time consumption spread to every end-users.

**Proposed solution**

Provide pre-built binaries through GitHub action

**Describe alternatives you've considered**

Or compile them manually...

**Additional context**

**Comment by JackBoosY** [comment]
Work in progress.

**Comment by BillyONeal** [comment]
Note that while we can provide a pre-built `vcpkg.exe`, the cloning of the git repo can't be avoided in the general case because the ports tree lives in there too.
