### ISSUE TITLE
[libx264] build failure on linux

### ISSUE THREAD

**Issue by sandro-qiang** [microsoft/vcpkg#14993]
**Host Environment**
- OS: Alpine Linux
- Compiler: gcc 9.3.0

**To Reproduce**
`./vcpkg install ffmpeg[avresample,bzip2,core,avcodec,avdevice,avformat,avfilter,postproc,swresample,swscale,openssl,mp3lame,x264]`

**Additional context**
It's a minor error in ports/x264/portfile.cmake

line17

 `set(ENV{PATH} "$ENV{PATH};${NASM_EXE_PATH}")`

should be 

```
if(VCPKG_TARGET_IS_WINDOWS)
    set(ENV{PATH} "$ENV{PATH};${NASM_EXE_PATH}")
else()
    set(ENV{PATH} "$ENV{PATH}:${NASM_EXE_PATH}")
endif()
```
and another minor error in installed/x64-linux/share/mp3lame/mp3lame-config.cmake

line6 and line 7

```
set(_mp3lame_rel_lib "${_mp3lame_root}/lib/libmp3lame..a")
set(_mp3lame_dbg_lib "${_mp3lame_root}/debug/lib/libmp3lame..a")
```
should be 

```
set(_mp3lame_rel_lib "${_mp3lame_root}/lib/libmp3lame.a")
set(_mp3lame_dbg_lib "${_mp3lame_root}/debug/lib/libmp3lame.a")
```

**Comment by NancyLi1013** [comment]
Hi @sandro-qiang 

Thanks for posting this issue.

The issue for `mp3lame` seems a bug, we need to fix this.

For `x264`, I noticed there were no any differences between Windows and Unix.

Also could you please help confirm if there are any problem when building `ffmpeg[avresample,bzip2,core,avcodec,avdevice,avformat,avfilter,postproc,swresample,swscale,openssl,mp3lame,x264]`?

**Comment by sandro-qiang** [comment]
On alpine linux, `;` in `$PATH` seems making whole `$PATH` empty, cmake report bash not found.

**Comment by NancyLi1013** [comment]
Currently, on my local, it will post this message on Linux if I didn't install `nasm` manually.

```
CMake Error at scripts/cmake/vcpkg_find_acquire_program.cmake:535 (message):
  Could not find nasm.  Please install it via your package manager:

      sudo apt-get install nasm
```

If I install it via` sudo apt-get install nasm`, x264 can build fine.

**Comment by NancyLi1013** [comment]
It seems that `nasm `is only supported for Windows platform.

Please see https://github.com/Microsoft/vcpkg/blob/master/scripts/cmake/vcpkg_find_acquire_program.cmake#L86-L89

set(URL
      "https://www.nasm.us/pub/nasm/releasebuilds/${NASM_VERSION}/win32/nasm-${NASM_VERSION}-win32.zip"
      "https://fossies.org/windows/misc/nasm-${NASM_VERSION}-win32.zip"
    )

**Comment by sandro-qiang** [comment]
It's not a nasm problem. Windows use `;` as path separator in envirment variable `PATH`, Unix use `:` as path separator in envirment variable `PATH`.

**Comment by NancyLi1013** [comment]
@sandro-qiang 

Thanks for pointing this out. Perhaps, we can use `vcpkg_add_to_path()` to avoid the path problem due to different platforms.
