### ISSUE TITLE
vcpkg help arch prints "Unknown topic"

### ISSUE THREAD

**Issue by Morten242** [Microsoft/vcpkg#15]
According to https://github.com/Microsoft/vcpkg/blob/master/docs/EXAMPLES.md `vcpkg help arch` should print all supported targets, but it seems it's not implemented yet?

**Comment by ras0219-msft** [comment]
Looks like a documentation bug! The right command is `vcpkg help triplet`; the code is here: https://github.com/Microsoft/vcpkg/blob/master/toolsrc/src/commands_help.cpp#L46
