### ISSUE TITLE
[double-conversion] Does not build DLLs

### ISSUE THREAD

**Issue by ras0219-msft** [Microsoft/vcpkg#150]
The upstream's vcxproj files only support building static libraries; this should get automatically fixed by using CMake instead.

**Comment by barcharcraz** [comment]
I'm working on cleaning this up as it's used by qt

**Comment by barcharcraz** [comment]
I think this was fixed in the pr that made double conversion use cmake.

**Comment by ras0219-msft** [comment]
Yes, thanks for checking back in on this issue :)
