### ISSUE TITLE
coin:arm64-linux failed.

### ISSUE THREAD

**Issue by romezxy** [microsoft/vcpkg#15004]
Package: coin:arm64-linux               
Vcpkg version: 2020.11.12-unknownhash

CMake Error at scripts/cmake/vcpkg_fail_port_install.cmake:97 (message):          
Architecture 'arm' not supported by coin!                                                                               Architecture 'arm64' not supported by coin!                                                                           Call Stack (most recent call first):      ports/coin/portfile.cmake:1 (vcpkg_fail_port_install)                           scripts/ports.cmake:136 (include)                                                                                     Error: Building package coin:arm64-linux failed with: BUILD_FAILED

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. `coin` doesn't support architecture `arm`. If there are process or new change about support of `coin`, please reopen this issue.
