### ISSUE TITLE
[New Port Request] <Simd>

### ISSUE THREAD

**Issue by Gigas002** [microsoft/vcpkg#15008]
Library name: Simd

Library description: The Simd Library is a free open source image processing and machine learning library, designed for C and C++ programmers. It provides many useful high performance algorithms for image processing such as: pixel format conversion, image scaling and filtration, extraction of statistic information from images, motion detection, object detection (HAAR and LBP classifier cascades) and classification, neural network.

Source repository URL: https://github.com/ermig1979/Simd

Anything else that is useful to know when adding (such as optional features the library may have that should be included): Builds pretty easily, info in repo's readme.

**Comment by Gigas002** [comment]
DLL builds on windows for both x86 and x64 in Debug/Release without any problems as is from source, just pull and build. Different projects for building are located in this directory: https://github.com/ermig1979/Simd/tree/master/prj.
Static windows build require you to change project's output type to `Static Library` and uncomment `#define SIMD_STATIC` in `simd/src/Simd/SimdConfig.h`. After that build as good as dll for all types (x86, x64; Debug/Release).
For linux libs cmake can be used (https://github.com/ermig1979/Simd/tree/master/prj/cmake), instructions are in readme (https://github.com/ermig1979/Simd/blob/master/README.md). Though library builds for linux, I didn't test if it actually works.

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
