### ISSUE TITLE
[Crashpad] for x86 build failure

### ISSUE THREAD

**Issue by Rdna123** [microsoft/vcpkg#15017]
**Host Environment**
- OS: [Windows 10]
- Compiler: x86

**To Reproduce**
`./vcpkg install crashpad`

**Failure logs** 
Error: Building package crashpad:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: crashpad:x86-windows
  Vcpkg version: 2020.11.12-nohash

**Additional context**
Is available for x64 not for x86

**Comment by JonLiu1993** [comment]
@Rdna123 ,Thanks for posting this issue,The port Crashpad doesn't support x86-windows triplet
````
CMake Error at scripts/cmake/vcpkg_fail_port_install.cmake:97 (message):
  Architecture 'x86' not supported by crashpad!
````
