### ISSUE TITLE
[coin:x64-linux] build failure

### ISSUE THREAD

**Issue by adili36** [microsoft/vcpkg#15019]
**Host Environment**
- OS: x64-Linux

**To Reproduce**
`./vcpkg install xxxx`

**Failure logs** 
Starting package 1/35: coin:x64-linux
Building package coin[core,simage,zlib]:x64-linux...
-- Using cached /home/l23394/Libs/vcpkg/vcpkg/downloads/Coin3D-coin-Coin-4.0.0.tar.gz
-- Cleaning sources at /home/l23394/Libs/vcpkg/vcpkg/buildtrees/coin/src/Coin-4.0.0-7b7f81da8d.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/l23394/Libs/vcpkg/vcpkg/downloads/Coin3D-coin-Coin-4.0.0.tar.gz
-- Applying patch disable-cpackd.patch
-- Using source at /home/l23394/Libs/vcpkg/vcpkg/buildtrees/coin/src/Coin-4.0.0-7b7f81da8d.clean
-- Configuring x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:108 (message):
    Command failed: /home/l23394/Libs/vcpkg/vcpkg/downloads/tools/cmake-3.18.4-linux/cmake-3.18.4-Linux-x86_64/bin/cmake /home/l23394/Libs/vcpkg/vcpkg/buildtrees/coin/src/Coin-4.0.0-7b7f81da8d.clean -DCOIN_BUILD_DOCUMENTATION=OFF -DCOIN_BUILD_MSVC_STATIC_RUNTIME=ON -DCOIN_BUILD_SHARED_LIBS=OFF -DCOIN_BUILD_TESTS=OFF -DCMAKE_MAKE_PROGRAM=/home/l23394/Libs/vcpkg/vcpkg/downloads/tools/ninja-1.10.1-linux/ninja -DCMAKE_SYSTEM_NAME=Linux -DBUILD_SHARED_LIBS=OFF -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/home/l23394/Libs/vcpkg/vcpkg/scripts/toolchains/linux.cmake -DVCPKG_TARGET_TRIPLET=x64-linux -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=external -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=/home/l23394/Libs/vcpkg/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_LINKER_FLAGS_RELEASE= -DVCPKG_LINKER_FLAGS_DEBUG= -DVCPKG_TARGET_ARCHITECTURE=x64 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -D_VCPKG_ROOT_DIR=/home/l23394/Libs/vcpkg/vcpkg -D_VCPKG_INSTALLED_DIR=/home/l23394/Libs/vcpkg/vcpkg/installed -DVCPKG_MANIFEST_INSTALL=OFF -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/home/l23394/Libs/vcpkg/vcpkg/packages/coin_x64-linux/debug
    Working Directory: /home/l23394/Libs/vcpkg/vcpkg/buildtrees/coin/x64-linux-dbg
    Error code: 1
    See logs for more information:
      /home/l23394/Libs/vcpkg/vcpkg/buildtrees/coin/config-x64-linux-dbg-out.log
      /home/l23394/Libs/vcpkg/vcpkg/buildtrees/coin/config-x64-linux-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:328 (vcpkg_execute_required_process)
  ports/coin/portfile.cmake:21 (vcpkg_configure_cmake)
  scripts/ports.cmake:136 (include)

Error: Building package coin:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: coin:x64-linux
  Vcpkg version: 2020.11.12-unknownhash

Additionally, attach any relevant sections from the log files above.

**Comment by JonLiu1993** [comment]
@adili36 , Sorry to reply you so late, could you please git pull your vcpkg and try again, if always failed please provide the detail error log

**Comment by JonLiu1993** [comment]
@adili36 ,Thanks for posting this issue. Please reopen this issue if it still be a problem for you.
