### ISSUE TITLE
[ suitesparse:x64-windows ] build failure

### ISSUE THREAD

**Issue by yu-zhui** [microsoft/vcpkg#15016]
**Host Environment**
- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**
`./vcpkg install xxxx`

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by JonLiu1993** [comment]
@yu-zhui ,Thanks for posting this issue,I wasn't able to reproduce this issue.
Please provide the failure logs for vcpkg install suitesparse:x64-windows.

**Comment by yu-zhui** [comment]
PS E:\vcpkg-master&gt; ./vcpkg install suitesparse:x64-windows
Computing installation plan...
The following packages will be built and installed:
&nbsp; &nbsp; suitesparse[core]:x64-windows
Detecting compiler hash for triplet x64-windows...
Starting package 1/1: suitesparse:x64-windows
Building package suitesparse[core]:x64-windows...
Could not locate cached archive: C:\Users\余恒\AppData\Local\vcpkg\archives\26\26c7a9c9f749180d349be8c892467bc88613dc39.zip
-- Downloading https://github.com/DrTimothyAldenDavis/SuiteSparse/archive/71e330ca2bc0a2f12f416c461d23dbca21db4d8f.tar.gz...
-- Downloading https://github.com/DrTimothyAldenDavis/SuiteSparse/archive/71e330ca2bc0a2f12f416c461d23dbca21db4d8f.tar.gz... Failed. Status: 18;"Transferred a partial file"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:182 (message):


&nbsp; &nbsp; &nbsp; Failed to download file.
&nbsp; &nbsp; &nbsp; If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
&nbsp; &nbsp; &nbsp; variables to "https://user:password@your-proxy-ip-address:port/".
&nbsp; &nbsp; &nbsp; Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues


Call Stack (most recent call first):
&nbsp; scripts/cmake/vcpkg_from_github.cmake:143 (vcpkg_download_distfile)
&nbsp; ports/suitesparse/portfile.cmake:1 (vcpkg_from_github)
&nbsp; scripts/ports.cmake:136 (include)




Error: Building package suitesparse:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
&nbsp; Package: suitesparse:x64-windows
&nbsp; Vcpkg version: 2020.11.12-nohash


Additionally, attach any relevant sections from the log files above.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/vcpkg"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月9日(星期三) 下午2:30
收件人:&nbsp;"microsoft/vcpkg"<vcpkg@noreply.github.com&gt;;
抄送:&nbsp;"慢慢"<2265735053@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [microsoft/vcpkg] [ suitesparse:x64-windows ] build failure (#15016)





 
@yu-zhui ,Thanks for posting this issue,I wasn't able to reproduce this issue.
 Please provide the failure logs for vcpkg install suitesparse:x64-windows.

**Comment by JonLiu1993** [comment]
@yu-zhui ,Use a proxy,you can use command to set it. Example:

set http_proxy=http://localhost:1080
set http_proxy_user=user
set http_proxy_pass=pwd

**Comment by PhoebeHui** [comment]
@yu-zhui, please reopen this issue if it still be a problem for you.
