### ISSUE TITLE
assimp: build failure on macOS

### ISSUE THREAD

**Issue by virtualritz** [microsoft/vcpkg#15012]
This port seemingly pulls all of the *optional* dependencies of `assimp` in. I was able to build `assimp` from the official repository on macOS w/o installing *any* optional dependencies.

Specifically `assimp` is broken for me on macOS because `irrlicht` (an *optional* dep.) is blocked on macOS. However, unblocking `irrlicht` doesn't make it build on macOS – there is probably something else missing there. See also #15011.

In any case, `irrlicht` (and the other optional deps) are not needed to make this port build.

I suggest to remove each optional dependency of this port on macOS first to make it build at all and then add them one by one as they each get fixed/building on that target.

**Comment by PhoebeHui** [comment]
Duplicated to issue https://github.com/microsoft/vcpkg/issues/14015.
