### ISSUE TITLE
Packages that rely on PYTHON2 need to be built in administrator mode because of .msi installation on Windows

### ISSUE THREAD

**Issue by dweckmann** [microsoft/vcpkg#15020]
****

**Is your feature request related to a problem? Please describe.**
Some packages requires python2 which is fine. Unfortunately, on windows, an msi package is downloaded and the installation fails almost silently, which of course, prevent further building. I believe Qt is one of this package.

**Proposed solution**
At least, a proper warning or error message in case the installation fails for that reason. A better solution would be to get ride of msi package, or to find a way to install msi without administrator rights, or, at last ressort, to make a temporary privilege escalation, the time of installation.

**Comment by NancyLi1013** [comment]
Hi @dweckmann 

Thanks for posting this issue.

Could you please help confirm which `msi` package that you needs to install?

**Comment by dweckmann** [comment]
Hi ,

At least in qt5-base, you can find `vcpkg_find_acquire_program(PYTHON2)` wich trigger `vcpkg_find_acquire_program.cmake->set(ARCHIVE "python-${PYTHON_VERSION}.amd64.msi")`.

**Comment by NancyLi1013** [comment]
@BillyONeal 

Could you please help take a look about this issue?

Thanks.

**Comment by BillyONeal** [comment]
Is Python 2 distributed in any form that is not an MSI? The number of ports that need python 2 should decline substantially over time now that there is no Python 2 in support.

**Comment by Hoikas** [comment]
Python 2 doesn't have an embedded zip distribution like Python 3 does. To be honest, given the age of Python 2 and the fact that it was officially sunsetted almost an entire year ago, it would make more sense to see if the ports that use Python 2 could be somehow updated to Python 3. For example, cppcms uses Python 2, but upstream was working on updating to Python 3 two months ago.

**Comment by dweckmann** [comment]
You are indeed right for python 2, most package will anyway be updated one day or another to use python 3. I'm just wondering if there is no other build program that are distributed as an msi (which could obviously trigger the same problem). If there is only python 2, then yes, we could live with that.

**Comment by NancyLi1013** [comment]
@dweckmann 

Is this still a problem for you now?

**Comment by dweckmann** [comment]
not really, I could live with it ;)

**Comment by NancyLi1013** [comment]
Thanks for your response. Now I'm closing this issue. Please open a new issue if you have other questions.
