### ISSUE TITLE
[New Port Request] qt6

### ISSUE THREAD

**Issue by alexreinking** [microsoft/vcpkg#15029]
Library name: Qt 6

Library description: Qt6 Application Framework

Source repository URL: Various URLs under https://download.qt.io/official_releases/qt/6.0/6.0.0/submodules/

Project homepage (if different from the source repository): https://www.qt.io/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

As a new major version, Qt 6 has breaking changes versus Qt5, which will continue to be LTS for some time. The ports `qt5` and `qt6` could potentially be used to create separate artifacts in the same build, so `qt6` should be considered as a separate port.

**Comment by Neumann-A** [comment]
Soembody should remove the good-first-issue label. This is definitly not a good first issue.....
