### ISSUE TITLE
boost-timer:x64-windows  but visual studio cannot find the dependencies

### ISSUE THREAD

**Issue by gladguy** [microsoft/vcpkg#15021]
**boost-timer:x64-windows  but visual studio cannot find the dependencies**

./vcpkg install boost-timer:x64-windows
Package boost-timer:x64-windows is already installed

./vcpkg integrate install
Applied user-wide integration for this vcpkg root.

There were no errors.

But when I try to compile a project with Boost dependency

Trying to Build KGraph from https://github.com/aaalgo/kgraph

Dependencies not found:

Error and Visual Studio Version is attached in the image

![image](https://user-images.githubusercontent.com/2222905/101603995-c80fbc80-3a19-11eb-84f1-c7533dc63d8f.png)
![image](https://user-images.githubusercontent.com/2222905/101604239-158c2980-3a1a-11eb-816f-722fb0d15100.png)

![image](https://user-images.githubusercontent.com/2222905/101604115-eecdf300-3a19-11eb-8ac0-3aed8f9495d0.png)

Is there any specific way to point visual studio project to the specific libraries?

**Comment by PhoebeHui** [comment]
@gladguy, you need to include the  ${Boost_INCLUDE_DIRS} in https://github.com/aaalgo/kgraph/blob/master/CMakeLists.txt, please add the following code and try again.

target_include_directories(kgraph PRIVATE  ${Boost_INCLUDE_DIRS})

**Comment by PhoebeHui** [comment]
@gladguy, please reopen this issue if it still be a problem for you.
