### ISSUE TITLE
[New Port Request]  moneycpp 

### ISSUE THREAD

**Issue by IshaanKarnik** [microsoft/vcpkg#15033]
Library name: 
moneycpp 

Library description: 
A C++ 17 header-only, cross-platform library for handling monetary values, currencies, rounding and other related features.

Source repository URL:
https://github.com/mariusbancila/moneycpp.git

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
