### ISSUE TITLE
Error: Building package opencv4:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by WYH-sys** [microsoft/vcpkg#15055]
PS F:\code\vcpkg> .\vcpkg install darknet[full]:x64-windows
Computing installation plan...
The following packages will be built and installed:
    darknet[core,cuda,cudnn,full,opencv-cuda,weights,weights-train]:x64-windows
  * opencv[core,cuda,dnn,ffmpeg,jpeg,opengl,png,tiff,webp]:x64-windows
  * opencv4[contrib,core,cuda,dnn,ffmpeg,jpeg,opengl,png,tiff,webp]:x64-windows
  * pthreads[core]:x64-windows
  * stb[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\wyh\AppData\Local\vcpkg\archives\76\7676fe92adcaf0c0cb4879fa627c687d7f34779f.zip
Could not locate cached archive: C:\Users\wyh\AppData\Local\vcpkg\archives\39\398101ce0221883ae2da992ff80d1c0f0bd117c8.zip
Could not locate cached archive: C:\Users\wyh\AppData\Local\vcpkg\archives\b1\b19d7e3daa7049dde0b7a2eba613f425bf8c2c81.zip
Could not locate cached archive: C:\Users\wyh\AppData\Local\vcpkg\archives\46\46759ea795a34705697cac2253f6d6bbeca0a754.zip
Could not locate cached archive: C:\Users\wyh\AppData\Local\vcpkg\archives\5d\5dd4e25906add65da48aee27226f42382de0cd76.zip
Starting package 1/5: opencv4:x64-windows
Building package opencv4[contrib,core,cuda,dnn,ffmpeg,jpeg,opengl,png,tiff,webp]:x64-windows...
-- Using cached F:/code/vcpkg/downloads/opencv-opencv-4.3.0.tar.gz
-- Cleaning sources at F:/code/vcpkg/buildtrees/opencv4/src/4.3.0-8460981b10.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source F:/code/vcpkg/downloads/opencv-opencv-4.3.0.tar.gz
-- Applying patch 0001-disable-downloading.patch
-- Applying patch 0002-install-options.patch
-- Applying patch 0003-force-package-requirements.patch
-- Applying patch 0004-fix-policy-CMP0057.patch
-- Applying patch 0006-jpeg2000_getref.patch
-- Applying patch 0009-fix-uwp.patch
-- Applying patch 0010-fix-interface_link_libraries.patch
-- Using source at F:/code/vcpkg/buildtrees/opencv4/src/4.3.0-8460981b10.clean
-- Using cached F:/code/vcpkg/downloads/opencv-cache/tiny_dnn/adb1c512e09ca2c7a6faef36f9c53e59-v1.0.0a3.tar.gz
-- Using cached F:/code/vcpkg/downloads/opencv-cache/nvidia_optical_flow/ca5acedee6cb45d0ec610a6732de5c15-79c6cee80a2df9a196f20afd6b598a9810964c32.zip
-- Using cached F:/code/vcpkg/downloads/opencv-opencv_contrib-4.3.0.tar.gz
-- Cleaning sources at F:/code/vcpkg/buildtrees/opencv4/src/4.3.0-795a2a992f.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source F:/code/vcpkg/downloads/opencv-opencv_contrib-4.3.0.tar.gz
-- Applying patch 0005-add-missing-stdexcept-include.patch
-- Using source at F:/code/vcpkg/buildtrees/opencv4/src/4.3.0-795a2a992f.clean
-- Downloading https://raw.githubusercontent.com/opencv/opencv_3rdparty/34e4206aef44d50e6bbcd0ab06354b52e7466d26/boostdesc_bgm.i...
-- Downloading https://raw.githubusercontent.com/opencv/opencv_3rdparty/34e4206aef44d50e6bbcd0ab06354b52e7466d26/boostdesc_bgm.i... Failed. Status: 6;"Couldn't resolve host name"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:182 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  ports/opencv4/portfile.cmake:134 (vcpkg_download_distfile)
  scripts/ports.cmake:136 (include)

Error: Building package opencv4:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: opencv4:x64-windows
  Vcpkg version: 2020.11.12-nohash

**Comment by WYH-sys** [comment]
I cant solve this problem all the time. Do you have any suggestions.I will be appreciated.

**Comment by cenit** [comment]
try using aria2 for download, for example

`./vcpkg install opencv --x-use-aria2`

**Comment by JonLiu1993** [comment]
@WYH-sys ,Can you try @cenit's method? I used the method he said to successfully build.

**Comment by cenit** [comment]
aria2 is much more robust than the download method integrated in CMake when behind a proxy. It is really a weakness of vcpkg when used in an enterprise because CMake is very prone to fail without reasons behind proxy. There should be an env variable to force aria2 always (@JonLiu1993 😉 😉 ); also (very very important) being able to use aria2 during the upgrade process (there is no way to use aria2 in a `./vcpkg upgrade` call)
