### ISSUE TITLE
Improvements to per-port static/dynamic customization process?

### ISSUE THREAD

**Issue by aggieNick02** [microsoft/vcpkg#15067]
I'm happy to work to implement improvements here, but first wanted to discuss and see what others thought.

I've got a solution using vcpkg linking to everything static with dynamic runtime (community triplets `x64-windows-static-md` and `x86-windows-static-md`). I had been pulling in ffmpeg manually (not with vcpkg) and dynamically (for licensing and size reasons), and wanted to move to pulling in using vcpkg.

I can totally do this with a custom triplet as shown in the triplets.md readme. But there are some pain points.

- I have to add the custom triplet to `vcpkg/triplets` in my fork of vcpkg. (I pull in this fork as a subrepo in my repo to keep things stable, and pull the latest from `microsoft/vcpkg` as needed.) Now I've got a commit in my fork that will never be in `microsoft/vcpkg`, and feels like noise in my fork - it's definitely a triplet that would never be merged back into `microsoft/vcpkg`.
A way to add a triplet without having to pollute my fork would be nice. Maybe there already is and I just missed it?
- Switching to a new triplet is a little painful. I have to update all of my projects (not too bad) and all of my dependencies will be rebuilt (a couple hours). Not the end of the world, but I'd rather not need to do that. ;-)

Port files are allowed to ignore the library linkage preference, as some projects only build static or dynamic, not both. What I really want to install is `ffmpeg~dynamic` - that is, an ffmpeg that builds dynamic regardless of the library linkage preference. What if vcpkg allowed specifying this via something like:
```vcpkg install ffmpeg~dynamic```?

For a given port, you would only be allowed to install one of the regular flavor (no special suffix), `~dynamic`, or `~static`.

FFmpeg is not the only library that can be built dynamic or static but where clients often have a preference for one option regardless of how their other dependencies are being linked. An example going the other way is protobuf, which builds both static and dynamic, but which recommends on its github page that only static linkage be used.

**Comment by aggieNick02** [comment]
Attempting this via a custom triplet actually revealed that path isn't great for another reason. ffmpeg has many dependencies, and they need to be built dynamically too. Which means my triplet file had this added:
```if(PORT STREQUAL "ffmpeg")
    set(VCPKG_LIBRARY_LINKAGE dynamic)
endif()```
actually needs that added for each of its 25 dependencies too.

**Comment by Neumann-A** [comment]
> actually needs that added for each of its 25 dependencies too.

not so difficult use. 
```
if(PORT MATCHES"(ffmpeg|otherdep1|otherdep2)")
    set(VCPKG_LIBRARY_LINKAGE dynamic)
endif()
```

> I have to add the custom triplet to vcpkg/triplets in my fork of vcpkg.

ever heard of overlay triplets?

**Comment by aggieNick02** [comment]
Thanks for the help @Neumann-A . When the installation plan is made for ffmpeg and it lists the dependencies, is that list complete recursively, if that makes sense? Or might one of those dependencies itself have a dependency that I also need to add to the list.

I had not seen overlay triplets. That's perfect! :-)

**Comment by Neumann-A** [comment]
use `vcpkg depend-info <port>` to get the complete list of dependencies of a port. The installation plan is only complete if you start with zero deps being installed.

**Comment by aggieNick02** [comment]
Awesome, thank you! Quite excited to have ffmpeg building in my project via vcpkg. Tried it on a dummy project and it was great having source and debugging automatically.

**Comment by aggieNick02** [comment]
I'm successfully building exactly what I want now with overlay-triplets. `vckpg depend-info` is also great to know - in this case I ended up only building ffmpeg with dynamic linking and not it's dependencies, as that mirrors how I used to be consuming it. Thank you again.
