### ISSUE TITLE
portfile.cmake does not recognize some environmental variables

### ISSUE THREAD

**Issue by jasjuang** [Microsoft/vcpkg#1507]
I am testing out porting caffe to vcpkg. It requires opencv and my opencv is built from source instead of from vcpkg because I need the cuda functionalities. The problem is caffe fails to compile through vcpkg because of the below error 

``````
CMake Error at cmake/Dependencies.cmake:122 (find_package):
  By not providing "FindOpenCV.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OpenCV", but
  CMake did not find one.
 
  Could not find a package configuration file provided by "OpenCV" with any
  of the following names:
 
    OpenCVConfig.cmake
    opencv-config.cmake
 
  Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
  "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"
  provides a separate development package or SDK, be sure it has been
  installed.
``````

Which indicates that the environmental variable `OpenCV_DIR` is not set. However when I do a `echo %OpenCV_DIR%` in the terminal it shows the correct path. If I go into the portfile and add the line `message("test" $ENV{OpenCV_DIR})` it shows only "test" and nothing else. Another test I did was `message("test" $ENV{PATH})` it does show the correct path. If I create another random environmental variable called TEST_ENV, again `echo %TEST_ENV%` shows the correct value but when I do `message("test" $ENV{TEST_ENV})` in the portfile nothing shows.

Why is portfile.cmake not being able to recognize some environmental variables?

**Comment by ras0219-msft** [comment]
We run builds inside a specially prepared clean environment to maximize consistency. You can enter this environment directly using `vcpkg env`, which will drop you into a shell.

Could you modify the opencv port inside Vcpkg to build with cuda instead? That's where we'd like to be in the future once feature packages land.

**Comment by jasjuang** [comment]
I tried dropping into `vcpkg env` and tried something like `setx` but it doesn't work. Is there any place I can set environmental variables?

Not everyone will have NVIDIA GPU in their computer so building with cuda might not work for some people. Is it possible to specify an optional flag? I also need opencv_contrib too.
