### ISSUE TITLE
building vcpkg.exe failure

### ISSUE THREAD

**Issue by innovativebureau** [microsoft/vcpkg#15074]
**Host Environment**
- OS: [ Windows.]

**Failure logs** 
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(413,
5): error MSB3191: Unable to create directory "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\vcpkg-m
aster\toolsrc\windows-bootstrap\msbuild.x86.release\vcpkg\". Access to the path 'C:\Program Files (x86)\Microsoft Visua
l Studio\2019\Community\VC\vcpkg-master\toolsrc\windows-bootstrap\msbuild.x86.release\vcpkg\' is denied. [C:\Program Fi
les (x86)\Microsoft Visual Studio\2019\Community\VC\vcpkg-master\toolsrc\windows-bootstrap\vcpkg.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\vcpkg-master\scripts\bootstrap.ps1 : Building
vcpkg.exe failed. Please ensure you have installed Visual Studio with the Desktop C++ workload and the Windows SDK for
Desktop C++.
At line:1 char:4
+ & {& 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\V ...
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,bootstrap.ps1

ScriptHalted
At C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\vcpkg-master\scripts\bootstrap.ps1:411 char:5
+     throw
+     ~~~~~
    + CategoryInfo          : OperationStopped: (:) [], RuntimeException
    + FullyQualifiedErrorId : ScriptHalted

**Additional context**
installed all packages for desktop c++ workload

**Comment by StarGate-One** [comment]
>**Access to the path 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\vcpkg-master\toolsrc\windows-bootstrap\msbuild.x86.release\vcpkg' is denied**

Try `C:\vcpkg` or `D:\vcpkg`  or `C:\Users\<username>\repos\vcpkg` for the vcpkg root.

**Comment by JonLiu1993** [comment]
@innovativebureau ,Thanks for posting this issue,Can you provide me with your steps to reproduce and a complete error log?

**Comment by PhoebeHui** [comment]
@innovativebureau, does this still be a problem for you? Have you try the solution that StarGate-One provided?

**Comment by PhoebeHui** [comment]
@innovativebureau, please reopen this issue if it still be a problem for you.
