### ISSUE TITLE
[qt5-webengine] build failure

### ISSUE THREAD

**Issue by junknet** [microsoft/vcpkg#15086]
**Host Environment**
- OS: Windows10
- Compiler: mscv

**To Reproduce**
`vcpkg.exe install qt5-webengine:x64-windows`

**Failure logs** 
PS C:\Users\junknet\Desktop> vcpkg.exe install qt5-webengine:x64-windows
Computing installation plan...
The following packages will be built and installed:
  * qt5-location[core]:x64-windows
  * qt5-tools[core]:x64-windows
  * qt5-webchannel[core]:x64-windows
    qt5-webengine[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Starting package 1/4: qt5-location:x64-windows
Building package qt5-location[core]:x64-windows...
Could not locate cached archive: C:\Users\junknet\AppData\Local\vcpkg\archives\34\34ff4e22398b9003a149d37c7e0a528ff9e1839d.zip
-- Downloading https://codereview.qt-project.org/gitweb?p=qt%2Fqtlocation.git;a=commitdiff_plain;h=6b2cf7e9d150b7be709fcd688c5045949cedc3d9;hp=7769ea903f87efc4ad55530a2749f104eddff2e4...
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:103 (message):

  File does not have expected hash:

          File path: [ C:/src/vcpkg-2020.11/downloads/temp/qt5-location-rename-99d16fb0.patch ]
      Expected hash: [ 99d16fb0e88a2250de3896815abbb22ff5aa4d3920397610cf37be701fe03a7241e0586aae5b85755aeb958926183c96a0482a8837335d20a2171ebb2a66e640 ]
        Actual hash: [ 5d2079d608abee80ba6f7ced78965f754116655ea5768135d45d2a88e1d199fa9d05b0f45da4cc62243146d982ba69de21f845a0a22a7bfb124c1e53ed006b63 ]

  The file may have been corrupted in transit.  This can be caused by
  proxies.  If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY
  environment variables to
  "https://user:password@your-proxy-ip-address:port/".

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:189 (test_hash)
  ports/qt5-location/portfile.cmake:1 (vcpkg_download_distfile)
  scripts/ports.cmake:135 (include)

Error: Building package qt5-location:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: qt5-location:x64-windows
  Vcpkg version: 2020.06.15-nohash

**Additional context**
This is not a problem with network proxy.
" https://codereview.qt-project.org/gitweb?p=qt%2Fqtlocation.git;a=commitdiff_plain;h=6b2cf7e9d150b7be709fcd688c5045949cedc3d9;hp=7769ea903f87efc4ad55530a2749f104eddff2e4..."
I use a browser to access this address, it looks like Qt let me login.So I cannot get this file `qt5-location-rename-99d16fb0.patch`

**Comment by JackBoosY** [comment]
I confirmed this issue was fixed in master branch, please ensure your vcpkg is latest.

Thanks.

**Comment by junknet** [comment]
> 
> 
> I confirmed this issue was fixed in master branch, please ensure your vcpkg is latest.
> 
> Thanks.

Maybe you need to keep looking.
**Failure logs**

PS C:\src\vcpkg> .\vcpkg.exe  install qt5[webengine]:x64-windows
Computing installation plan...
The following packages will be built and installed:
    qt5[activeqt,core,declarative,essentials,imageformats,multimedia,networkauth,quickcontrols2,svg,tools,webengine]:x64-windows -> 5.15.1
  * qt5-webengine[core]:x64-windows -> 5.15.1#1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\junknet\AppData\Local\vcpkg\archives\f9\f93123049d1cbcd6aa6927590db62e7cb518ba99.zip
Could not locate cached archive: C:\Users\junknet\AppData\Local\vcpkg\archives\50\50b54311d15f63b6dc50c4d682c8bc7ca0e73c77.zip
Starting package 1/2: qt5-webengine:x64-windows
Building package qt5-webengine[core]:x64-windows...
-- qt5-webengine requires a lot of free disk space (>300GB), ram (>32 GB) and time (>4h per configuration) to be successfully build.
-- As such qt5-webengine is not properly tested.
-- If qt5-webengine fails post build validation please open up an issue.
-- If it fails due to post validation the successfully installed files can be found in C:/src/vcpkg/packages/qt5-webengine_x64-windows
-- and just need to be copied into C:/src/vcpkg/installed/x64-windows
-- Using cached C:/src/vcpkg/downloads/qtwebengine-everywhere-src-5.15.1.tar.xz
-- Cleaning sources at C:/src/vcpkg/buildtrees/qt5-webengine/src/5.15.1-8798b27a4c.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/src/vcpkg/downloads/qtwebengine-everywhere-src-5.15.1.tar.xz
-- Applying patch common.pri.patch
-- Applying patch gl.patch
-- Using source at C:/src/vcpkg/buildtrees/qt5-webengine/src/5.15.1-8798b27a4c.clean
-- Using msys root at C:/src/vcpkg/downloads/tools/msys2/c809757c94447846
-- Configuring x64-windows-rel
-- Configuring x64-windows-rel done
-- Configuring x64-windows-dbg
-- Configuring x64-windows-dbg done
-- Package build-x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:145 (message):
    Command failed: C:/src/vcpkg/downloads/tools/jom/jom-1.1.3/jom.exe -j 17
    Working Directory: C:/src/vcpkg/buildtrees/qt5-webengine/x64-windows-dbg
    See logs for more information:
      C:\src\vcpkg\buildtrees\qt5-webengine\package-build-x64-windows-dbg-out.log
      C:\src\vcpkg\buildtrees\qt5-webengine\package-build-x64-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_qmake.cmake:43 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_build_qmake.cmake:79 (run_jom)
  installed/x64-windows/share/qt5/qt_build_submodule.cmake:12 (vcpkg_build_qmake)
  installed/x64-windows/share/qt5/qt_submodule_installation.cmake:8 (qt_build_submodule)
  ports/qt5-webengine/portfile.cmake:46 (qt_submodule_installation)
  scripts/ports.cmake:136 (include)


Error: Building package qt5-webengine:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: qt5-webengine:x64-windows
  Vcpkg version: 2020.11.12-nohash
VCPKG is the latest git version.

`"C:\src\vcpkg\buildtrees\qt5-webengine\package-build-x64-windows-dbg-err.log":`

jom 1.1.3 - empower your cores

Project MESSAGE: C:\src\vcpkg\buildtrees\qt5-webengine\src\5.15.1-8798b27a4c.clean\src\3rdparty\gn\build\gen.py --no-last-commit-position --out-path C:/src/vcpkg/buildtrees/qt5-webengine/x64-windows-dbg/src/3rdparty/gn/out/Release --cc "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\Hostx64\x64\cl.exe" --cxx "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\Hostx64\x64\cl.exe" --ld "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\Hostx64\x64\link.exe" --use-lto
Project MESSAGE: Running: C:\src\vcpkg\buildtrees\qt5-webengine\x64-windows-dbg\src\3rdparty\gn\out\Release\gn.exe gen C:\src\vcpkg\buildtrees\qt5-webengine\x64-windows-dbg\src\core\debug --script-executable=C:\src\vcpkg\downloads\tools\python\python-2.7.16-x64\python.exe --args="use_qt=true closure_compile=false is_component_build=false is_shared=true enable_debugallocation=false enable_media_remoting=false enable_message_center=false enable_nacl=false enable_remoting=false enable_reporting=false enable_resource_whitelist_generation=false enable_swiftshader=false angle_enable_swiftshader=false enable_web_auth=true enable_web_speech=false enable_widevine=true has_native_accessibility=false optimize_webui=false safe_browsing_mode=0 strip_absolute_paths_from_debug_symbols=false toolkit_views=false treat_warnings_as_errors=false use_allocator_shim=false use_allocator=\"none\" use_custom_libcxx=false v8_use_external_startup_data=false forbid_non_component_debug_builds=false jumbo_build_excluded=[\"browser\"] enable_precompiled_headers=false is_official_build=false is_unsafe_developer_build=false is_debug=true use_debug_fission=false enable_iterator_debugging=true v8_optimized_debug=false blink_symbol_level=0 remove_v8base_debug_symbols=true use_sysroot=false enable_session_service=false ninja_use_custom_environment_files=false is_multi_dll_chrome=false win_linker_timing=true com_init_check_hook_disabled=true heterogeneous_executables=true is_clang=false use_lld=false is_win_fastlink=false use_incremental_linking=false visual_studio_version=2019 visual_studio_path=\"C:/Program Files ^(x86^)/Microsoft Visual Studio/2019/Community\" windows_sdk_path=\"C:/Program Files ^(x86^)/Windows Kits/10\" target_cpu=\"x64\" enable_basic_printing=true enable_print_preview=true enable_pdf=true enable_plugins=true enable_spellcheck=true enable_webrtc=true proprietary_codecs=false enable_extensions=true use_kerberos=true have_nodejs=false use_browser_spellchecker=false qtwebengine_target=\"C:\src\vcpkg\buildtrees\qt5-webengine\x64-windows-dbg\src\core\debug:QtWebEngineCore\"" --root=C:\src\vcpkg\buildtrees\qt5-webengine\src\5.15.1-8798b27a4c.clean\src\3rdparty\chromium 
Project MESSAGE: Running: C:\src\vcpkg\buildtrees\qt5-webengine\x64-windows-dbg\src\3rdparty\gn\out\Release\gn.exe gen C:\src\vcpkg\buildtrees\qt5-webengine\x64-windows-dbg\src\core\release --script-executable=C:\src\vcpkg\downloads\tools\python\python-2.7.16-x64\python.exe --args="use_qt=true closure_compile=false is_component_build=false is_shared=true enable_debugallocation=false enable_media_remoting=false enable_message_center=false enable_nacl=false enable_remoting=false enable_reporting=false enable_resource_whitelist_generation=false enable_swiftshader=false angle_enable_swiftshader=false enable_web_auth=true enable_web_speech=false enable_widevine=true has_native_accessibility=false optimize_webui=false safe_browsing_mode=0 strip_absolute_paths_from_debug_symbols=false toolkit_views=false treat_warnings_as_errors=false use_allocator_shim=false use_allocator=\"none\" use_custom_libcxx=false v8_use_external_startup_data=false forbid_non_component_debug_builds=false jumbo_build_excluded=[\"browser\"] enable_precompiled_headers=false is_official_build=true is_debug=false symbol_level=0 blink_symbol_level=0 remove_v8base_debug_symbols=true use_sysroot=false enable_session_service=false ninja_use_custom_environment_files=false is_multi_dll_chrome=false win_linker_timing=true com_init_check_hook_disabled=true heterogeneous_executables=true is_clang=false use_lld=false is_win_fastlink=false use_incremental_linking=false visual_studio_version=2019 visual_studio_path=\"C:/Program Files ^(x86^)/Microsoft Visual Studio/2019/Community\" windows_sdk_path=\"C:/Program Files ^(x86^)/Windows Kits/10\" target_cpu=\"x64\" enable_basic_printing=true enable_print_preview=true enable_pdf=true enable_plugins=true enable_spellcheck=true enable_webrtc=true proprietary_codecs=false enable_extensions=true use_kerberos=true have_nodejs=false use_browser_spellchecker=false qtwebengine_target=\"C:\src\vcpkg\buildtrees\qt5-webengine\x64-windows-dbg\src\core\release:QtWebEngineCore\"" --root=C:\src\vcpkg\buildtrees\qt5-webengine\src\5.15.1-8798b27a4c.clean\src\3rdparty\chromium 
jom: C:\src\vcpkg\buildtrees\qt5-webengine\x64-windows-dbg\src\core\Makefile.gn_run.Debug [run_ninja] Error 1
jom: C:\src\vcpkg\buildtrees\qt5-webengine\x64-windows-dbg\src\core\Makefile.gn_run [debug] Error 2
jom: C:\src\vcpkg\buildtrees\qt5-webengine\x64-windows-dbg\src\core\Makefile [sub-gn_run-pro-make_first] Error 2
jom: C:\src\vcpkg\buildtrees\qt5-webengine\x64-windows-dbg\src\Makefile [sub-core-make_first] Error 2
jom: C:\src\vcpkg\buildtrees\qt5-webengine\x64-windows-dbg\Makefile [sub-src-make_first] Error 2

**Comment by JackBoosY** [comment]
@junknet  Please provide full log _C:\src\vcpkg\buildtrees\qt5-webengine\package-build-x64-windows-dbg-out.log_.

**Comment by junknet** [comment]
> 
> 
> @junknet Please provide full log _C:\src\vcpkg\buildtrees\qt5-webengine\package-build-x64-windows-dbg-out.log_.
I'm sorry, but the file is too big.I uploaded it to one of my Git repositories.

[package-build-x64-windows-dbg-out.log](https://raw.githubusercontent.com/junknet/s3-upload/master/package-build-x64-windows-dbg-out.log)

**Comment by Brooklyn2001** [comment]
Confirm this bug


jom 1.1.3 - empower your cores

Project MESSAGE: D:\dev\vcpkg\buildtrees\qt5-webengine\src\5.15.1-8798b27a4c.clean\src\3rdparty\gn\build\gen.py --no-last-commit-position --out-path D:/dev/vcpkg/buildtrees/qt5-webengine/x64-windows-rel/src/3rdparty/gn/out/Release --cc "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\Hostx64\x64\cl.exe" --cxx "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\Hostx64\x64\cl.exe" --ld "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\Hostx64\x64\link.exe" --use-lto
Project MESSAGE: Running: D:\dev\vcpkg\buildtrees\qt5-webengine\x64-windows-rel\src\3rdparty\gn\out\Release\gn.exe gen D:\dev\vcpkg\buildtrees\qt5-webengine\x64-windows-rel\src\core\release --script-executable=D:\dev\vcpkg\downloads\tools\python\python-2.7.16-x64\python.exe --args="use_qt=true closure_compile=false is_component_build=false is_shared=true enable_debugallocation=false enable_media_remoting=false enable_message_center=false enable_nacl=false enable_remoting=false enable_reporting=false enable_resource_whitelist_generation=false enable_swiftshader=false angle_enable_swiftshader=false enable_web_auth=true enable_web_speech=false enable_widevine=true has_native_accessibility=false optimize_webui=false safe_browsing_mode=0 strip_absolute_paths_from_debug_symbols=false toolkit_views=false treat_warnings_as_errors=false use_allocator_shim=false use_allocator=\"none\" use_custom_libcxx=false v8_use_external_startup_data=false forbid_non_component_debug_builds=false jumbo_build_excluded=[\"browser\"] enable_precompiled_headers=false is_official_build=true is_debug=false symbol_level=0 blink_symbol_level=0 remove_v8base_debug_symbols=true use_sysroot=false enable_session_service=false ninja_use_custom_environment_files=false is_multi_dll_chrome=false win_linker_timing=true com_init_check_hook_disabled=true heterogeneous_executables=true is_clang=false use_lld=false is_win_fastlink=false use_incremental_linking=false visual_studio_version=2019 visual_studio_path=\"C:/Program Files ^(x86^)/Microsoft Visual Studio/2019/Community\" windows_sdk_path=\"C:/Program Files ^(x86^)/Windows Kits/10\" target_cpu=\"x64\" enable_basic_printing=true enable_print_preview=true enable_pdf=true enable_plugins=true enable_spellcheck=true enable_webrtc=true proprietary_codecs=false enable_extensions=true use_kerberos=true have_nodejs=false use_browser_spellchecker=false qtwebengine_target=\"D:\dev\vcpkg\buildtrees\qt5-webengine\x64-windows-rel\src\core\release:QtWebEngineCore\"" --root=D:\dev\vcpkg\buildtrees\qt5-webengine\src\5.15.1-8798b27a4c.clean\src\3rdparty\chromium 
Project MESSAGE: Running: D:\dev\vcpkg\buildtrees\qt5-webengine\x64-windows-rel\src\3rdparty\gn\out\Release\gn.exe gen D:\dev\vcpkg\buildtrees\qt5-webengine\x64-windows-rel\src\core\debug --script-executable=D:\dev\vcpkg\downloads\tools\python\python-2.7.16-x64\python.exe --args="use_qt=true closure_compile=false is_component_build=false is_shared=true enable_debugallocation=false enable_media_remoting=false enable_message_center=false enable_nacl=false enable_remoting=false enable_reporting=false enable_resource_whitelist_generation=false enable_swiftshader=false angle_enable_swiftshader=false enable_web_auth=true enable_web_speech=false enable_widevine=true has_native_accessibility=false optimize_webui=false safe_browsing_mode=0 strip_absolute_paths_from_debug_symbols=false toolkit_views=false treat_warnings_as_errors=false use_allocator_shim=false use_allocator=\"none\" use_custom_libcxx=false v8_use_external_startup_data=false forbid_non_component_debug_builds=false jumbo_build_excluded=[\"browser\"] enable_precompiled_headers=false is_official_build=false is_unsafe_developer_build=false is_debug=true use_debug_fission=false enable_iterator_debugging=true v8_optimized_debug=false blink_symbol_level=0 remove_v8base_debug_symbols=true use_sysroot=false enable_session_service=false ninja_use_custom_environment_files=false is_multi_dll_chrome=false win_linker_timing=true com_init_check_hook_disabled=true heterogeneous_executables=true is_clang=false use_lld=false is_win_fastlink=false use_incremental_linking=false visual_studio_version=2019 visual_studio_path=\"C:/Program Files ^(x86^)/Microsoft Visual Studio/2019/Community\" windows_sdk_path=\"C:/Program Files ^(x86^)/Windows Kits/10\" target_cpu=\"x64\" enable_basic_printing=true enable_print_preview=true enable_pdf=true enable_plugins=true enable_spellcheck=true enable_webrtc=true proprietary_codecs=false enable_extensions=true use_kerberos=true have_nodejs=false use_browser_spellchecker=false qtwebengine_target=\"D:\dev\vcpkg\buildtrees\qt5-webengine\x64-windows-rel\src\core\debug:QtWebEngineCore\"" --root=D:\dev\vcpkg\buildtrees\qt5-webengine\src\5.15.1-8798b27a4c.clean\src\3rdparty\chromium 
jom: D:\dev\vcpkg\buildtrees\qt5-webengine\x64-windows-rel\src\core\Makefile.gn_run.Release [run_ninja] Error 1
jom: D:\dev\vcpkg\buildtrees\qt5-webengine\x64-windows-rel\src\core\Makefile.gn_run [release] Error 2
jom: D:\dev\vcpkg\buildtrees\qt5-webengine\x64-windows-rel\src\core\Makefile [sub-gn_run-pro-make_first] Error 2
jom: D:\dev\vcpkg\buildtrees\qt5-webengine\x64-windows-rel\src\Makefile [sub-core-make_first] Error 2
jom: D:\dev\vcpkg\buildtrees\qt5-webengine\x64-windows-rel\Makefile [sub-src-make_first] Error 2

**Comment by JackBoosY** [comment]
cc @Neumann-A

**Comment by Neumann-A** [comment]
should be fixed in #14678
