### ISSUE TITLE
Cannot include mpg123 for x64-windows in manifest due to missing x86-windows yasm-tool

### ISSUE THREAD

**Issue by MCJack123** [microsoft/vcpkg#15087]
**Describe the bug**
If `mpg123` (or `libvpx` as I've seen) is added as a dependency in a manifest (either as a direct dependency or through another package such as `sdl2-mixer`), building the package for anything other than `x86-windows-*` will fail due to a soft dependency on `yasm-tool` for the `x86-windows` triplet. Trying to install it manually using `--x-install-root` will install it, but upon installing the manifest for `x64-windows` (or any other triplet) will cause it to be purged before installing `mpg123`, failing to install again.

This still happens when `yasm-tool` is directly depended on in the manifest. vcpkg will continue to uninstall the x86 version, queueing the x64 version instead (which will specifically not work).

**Environment**
- OS: Windows 10 (20H2, 19042.631)
- Compiler: Microsoft Visual Studio 2019 v16.8.3, `cl.exe` version 19.28.29335
- vcpkg version: 2020.11.12-nohash (latest commit)

**To Reproduce**
1. Make a new directory anywhere, and `cd` into it
2. Create a `vcpkg.json` in that directory requiring `mpg123` in some way, such as this:
```json
{
    "name": "test",
    "version-string": "1.0",
    "description": "Test package",
    "dependencies": ["3fd"]
}
```
3. Run `vcpkg --feature-flags=manifests install --target=x64-windows`
4. Notice failure
5. Run `vcpkg --x-install-root=vcpkg_installed install yasm-tool:x86-windows` to attempt to fix failure
6. Run `vcpkg --feature-flags=manifests install --target=x64-windows` again
7. Notice how `yasm-tool` is purged, and `mpg123` fails again

**Expected behavior**
Either `yasm-tool` remains installed during manifest installation, or there should be some way to declare installation of `yasm-tool:x86-windows` in the manifest.

**Failure logs** 
<details>
<summary>Logs</summary>
<pre>
Computing installation plan...
The following packages will be built and installed:
    yasm-tool[core]:x86-windows -> 2020-10-12
Detecting compiler hash for triplet x86-windows...
Using cached binary package: C:\Users\jackb_000\AppData\Local\vcpkg\archives\73\73f71f1c170eaaf362d3c5f757a2c52e1fee59dd.zip
Starting package 1/1: yasm-tool:x86-windows
Building package yasm-tool[core]:x86-windows...
Building package yasm-tool[core]:x86-windows... done
Installing package yasm-tool[core]:x86-windows...
Installing package yasm-tool[core]:x86-windows... done
Elapsed time for package yasm-tool:x86-windows: 13.5 ms

Total elapsed time: 4.016 s
</pre>
<pre>
Detecting compiler hash for triplet x64-windows...
The following packages will be removed:
    yasm-tool:x86-windows
The following packages will be built and installed:
  * mpg123[core]:x64-windows -> 1.26.3
  * opus[core]:x64-windows -> 1.3.1#5
  * opusfile[core]:x64-windows -> 0.12
    pdcurses[core]:x64-windows -> 3.9
    pngpp[core]:x64-windows -> 0.2.10
    poco[core]:x64-windows -> 1.10.1#3
    sdl2[core]:x64-windows -> 2.0.12#8
    sdl2-mixer[core,dynamic-load,fluidsynth,libflac,libmodplug,libvorbis,mpg123,nativemidi,opusfile]:x64-windows -> 2.0.4#10
Additional packages (*) will be modified to complete this operation.
Starting package 1/9: yasm-tool:x86-windows
Removing package yasm-tool:x86-windows...
Removing package yasm-tool:x86-windows... done
Elapsed time for package yasm-tool:x86-windows: 7.359 ms
Could not locate cached archive: C:\Users\jackb_000\AppData\Local\vcpkg\archives90\901b97c5c2efbfc84fa4d0f7596ae853d1760322.zip
Could not locate cached archive: C:\Users\jackb_000\AppData\Local\vcpkg\archives\f2\f26f63c63a7cce103e30aac390f8596dacae0982.zip
Could not locate cached archive: C:\Users\jackb_000\AppData\Local\vcpkg\archives\c9\c9bbf3f6f1fd7e20405ffa0d4fbe78b97f9b5061.zip
Could not locate cached archive: C:\Users\jackb_000\AppData\Local\vcpkg\archives\79\79485ca3be49f4b3238f298584a1a78721e011bb.zip
Could not locate cached archive: C:\Users\jackb_000\AppData\Local\vcpkg\archives\0e\0ea0e20954cff081a87e4a237ca245d7c4c5da23.zip
Could not locate cached archive: C:\Users\jackb_000\AppData\Local\vcpkg\archives\9f\9f8e86d610c7d567af9961b2f666930f94997172.zip
Could not locate cached archive: C:\Users\jackb_000\AppData\Local\vcpkg\archives\f6\f68d66d6a6fab5794997a5abff0f9324fba5e082.zip
Could not locate cached archive: C:\Users\jackb_000\AppData\Local\vcpkg\archives\0f\0f1802e11d6f5aa6a26f1751e923c15b0306d81d.zip
Starting package 2/9: mpg123:x64-windows
Building package mpg123[core]:x64-windows...
-- Trying auto-select mirror...
-- Using cached C:/Users/jackb_000/Downloads/vcpkg/downloads/mpg123-1.26.3.tar.bz2
-- Skipping hash check for C:/Users/jackb_000/Downloads/vcpkg/downloads/mpg123-1.26.3.tar.bz2.
-- The default mirror is in Disaster Recovery mode, trying other mirrors...
-- Trying mirror cfhcable...
-- Using cached C:/Users/jackb_000/Downloads/vcpkg/downloads/mpg123-1.26.3.tar.bz2
-- Skipping hash check for C:/Users/jackb_000/Downloads/vcpkg/downloads/mpg123-1.26.3.tar.bz2.
-- Cleaning sources at C:/Users/jackb_000/Downloads/vcpkg/buildtrees/mpg123/src/7574331afa-116bac1a58.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/jackb_000/Downloads/vcpkg/downloads/mpg123-1.26.3.tar.bz2
-- Applying patch 0001-fix-x86-build.patch
-- Using source at C:/Users/jackb_000/Downloads/vcpkg/buildtrees/mpg123/src/7574331afa-116bac1a58.clean
CMake Error at C:/Users/jackb_000/Downloads/ComputerCraft/CraftOS-PC-2/vcpkg_installed/x64-windows/share/yasm-tool-helper/yasm-tool-helper.cmake:16 (message):
  Cross-targetting and x64 ports requiring yasm require the x86-windows
  yasm-tool to be available.  Please install yasm-tool:x86-windows first.
Call Stack (most recent call first):
  ports/mpg123/portfile.cmake:37 (yasm_tool_helper)
  scripts/ports.cmake:136 (include)

EXEC : error : Building package mpg123:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: mpg123:x64-windows
  Vcpkg version: 2020.11.12-nohash

Additionally, attach any relevant sections from the log files above.
</pre>
</details>

**Additional context**
I'm mainly installing the manifest through Visual Studio, but this issue persists when manually installing with `vcpkg install`.

**Comment by PhoebeHui** [comment]
@MCJack123, I can't repro this issue with latest clean source, I added mpg123 to 3fd, and remove others dependency to speed up the building process.

I think you should not add '--x-install-root=vcpkg_installed' in command line, it will install yasm-tool in another directory.

However, it's weired to remove 'yasm-tool:x86-windows' before installing other ports, do you have some special setup?
Could you try with latest clean source and see if the issue persist?

```
 PS E:\vcpkg\src> ./vcpkg --feature-flags=manifests install yasm-tool:x86-windows
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
Computing installation plan...
The following packages will be built and installed:
    yasm-tool[core]:x86-windows -> 2020-10-12
Detecting compiler hash for triplet x86-windows...
Could not locate cached archive: C:\Users\phoebe\AppData\Local\vcpkg\archives\48\48e9787bab490d3a8c48a5d23fbb4ccada43d871.zip
Starting package 1/1: yasm-tool:x86-windows
Building package yasm-tool[core]:x86-windows...
-- Downloading https://www.python.org/ftp/python/3.9.0/python-3.9.0-embed-win32.zip...
-- Downloading https://github.com/yasm/yasm/archive/009450c7ad4d425fa5a10ac4bd6efbd25248d823.tar.gz...
-- Extracting source E:/vcpkg/src/downloads/yasm-yasm-009450c7ad4d425fa5a10ac4bd6efbd25248d823.tar.gz
-- Using source at E:/vcpkg/src/buildtrees/yasm-tool/src/d25248d823-818ed1bbf4.clean
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Installing: E:/vcpkg/src/packages/yasm-tool_x86-windows/share/yasm-tool/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\phoebe\AppData\Local\vcpkg\archives\48\48e9787bab490d3a8c48a5d23fbb4ccada43d871.zip
Building package yasm-tool[core]:x86-windows... done
Installing package yasm-tool[core]:x86-windows...
Installing package yasm-tool[core]:x86-windows... done
Elapsed time for package yasm-tool:x86-windows: 1.013 min

Total elapsed time: 1.108 min

PS E:\vcpkg\src> ./vcpkg --feature-flags=manifests install 3fd:x64-windows
Computing installation plan...
The following packages will be built and installed:
    3fd[core]:x64-windows -> 2.6.3
  * mpg123[core]:x64-windows -> 1.26.3
  * yasm-tool-helper[core]:x64-windows -> 2020-10-12
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\phoebe\AppData\Local\vcpkg\archives\62\62488264c7e11d8dff36d117464d7c1b6534e97f.zip
Could not locate cached archive: C:\Users\phoebe\AppData\Local\vcpkg\archives\fe\fe2e05cc06878f4a703c37a412567c7801910c35.zip
Could not locate cached archive: C:\Users\phoebe\AppData\Local\vcpkg\archives\7a\7ac5fc2255b25ed05dc538c191ffc10368c5ff2c.zip
Starting package 1/3: yasm-tool-helper:x64-windows
Building package yasm-tool-helper[core]:x64-windows...
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\phoebe\AppData\Local\vcpkg\archives\62\62488264c7e11d8dff36d117464d7c1b6534e97f.zip
Building package yasm-tool-helper[core]:x64-windows... done
Installing package yasm-tool-helper[core]:x64-windows...
Installing package yasm-tool-helper[core]:x64-windows... done
Elapsed time for package yasm-tool-helper:x64-windows: 275.3 ms
Starting package 2/3: mpg123:x64-windows
Building package mpg123[core]:x64-windows...
-- Trying auto-select mirror...
-- Using cached E:/vcpkg/src/downloads/mpg123-1.26.3.tar.bz2
-- Skipping hash check for E:/vcpkg/src/downloads/mpg123-1.26.3.tar.bz2.
-- The default mirror is in Disaster Recovery mode, trying other mirrors...
-- Trying mirror cfhcable...
-- Using cached E:/vcpkg/src/downloads/mpg123-1.26.3.tar.bz2
-- Skipping hash check for E:/vcpkg/src/downloads/mpg123-1.26.3.tar.bz2.
-- Cleaning sources at E:/vcpkg/src/buildtrees/mpg123/src/7574331afa-116bac1a58.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/vcpkg/src/downloads/mpg123-1.26.3.tar.bz2
-- Applying patch 0001-fix-x86-build.patch
-- Using source at E:/vcpkg/src/buildtrees/mpg123/src/7574331afa-116bac1a58.clean
-- Building ports/MSVC++/2015/win32/libmpg123/libmpg123.vcxproj for Release
-- Building ports/MSVC++/2015/win32/libmpg123/libmpg123.vcxproj for Debug
-- Installing: E:/vcpkg/src/packages/mpg123_x64-windows/include/mpg123.h
-- Installing: E:/vcpkg/src/packages/mpg123_x64-windows/include/fmt123.h
-- Installing: E:/vcpkg/src/packages/mpg123_x64-windows/include/mpg123.h.in
-- Installing: E:/vcpkg/src/packages/mpg123_x64-windows/share/mpg123/copyright
-- Installing done
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\phoebe\AppData\Local\vcpkg\archives\fe\fe2e05cc06878f4a703c37a412567c7801910c35.zip
Building package mpg123[core]:x64-windows... done
Installing package mpg123[core]:x64-windows...
Installing package mpg123[core]:x64-windows... done
Elapsed time for package mpg123:x64-windows: 22.1 s
Starting package 3/3: 3fd:x64-windows
Building package 3fd[core]:x64-windows...
-- Note: 3fd only supports static library linkage. Building static library.
-- Using cached E:/vcpkg/src/downloads/faburaya-3fd-3a0fe606268721d1560b88dcca8647c67c0b275c.tar.gz
-- Cleaning sources at E:/vcpkg/src/buildtrees/3fd/src/c67c0b275c-accfc8aba3.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/vcpkg/src/downloads/faburaya-3fd-3a0fe606268721d1560b88dcca8647c67c0b275c.tar.gz
-- Applying patch rapidxml.patch
-- Using source at E:/vcpkg/src/buildtrees/3fd/src/c67c0b275c-accfc8aba3.clean
-- Building 3FD/3FD.vcxproj for Release
...
```

**Comment by MCJack123** [comment]
I've tried running the commands you used, but vcpkg does not accept a package argument when `manifests` is enabled.
```
>vcpkg --feature-flags=manifests install yasm-tool:x86-windows
Error: 'install' requires 0 arguments, but 1 were provided.
Example:
  vcpkg install --triplet x64-windows

Options:
[ ... ]
```
Also, this is involving manifest dependencies, not installing the package manually. I'm running only `vcpkg --feature-flags=manifests install` without specifying a package name. I'm also using Visual Studio to run this command automatically during build time.

I used `--x-install-root` when installing `yasm-tool` because manifest packages are installed to a local directory, so I needed to change the install root to make sure the package was installed there, and not to the global store. I understand it's an experimental flag, but it was the best option for what I needed.

I also realize I forgot to mention the vcpkg version. I'm running version 2020.11.12-nohash from the latest commit. I had pulled the repo and re-ran `bootstrap-vcpkg.bat` just before running the commands (and pulled it again just now), so it's up-to-date.

**Comment by PhoebeHui** [comment]
```
I've tried running the commands you used, but vcpkg does not accept a package argument when `manifests` is enabled.
```
>vcpkg --feature-flags=manifests install yasm-tool:x86-windows
Error: 'install' requires 0 arguments, but 1 were provided.
Example:
  vcpkg install --triplet x64-windows

Options:
[ ... ]
```

```

@MCJack123, this looks weird for me, do you have any particular setting? what's output from 'git rev-parse HEAD' command? 

For me
```
E:\vcpkg\src>git rev-parse HEAD
2aaa67573085c24bcb4e224b87605d708d9a6377

E:\vcpkg\src>vcpkg --feature-flags=manifests install yasm-tool:x86-windows
Computing installation plan...
The following packages will be built and installed:
    yasm-tool[core]:x86-windows -> 2020-10-12
Detecting compiler hash for triplet x86-windows...
Could not locate cached archive: C:\Users\phoebe\AppData\Local\vcpkg\archives\48\48e9787bab490d3a8c48a5d23fbb4ccada43d871.zip
Starting package 1/1: yasm-tool:x86-windows
Building package yasm-tool[core]:x86-windows...
-- Using cached E:/vcpkg/src/downloads/yasm-yasm-009450c7ad4d425fa5a10ac4bd6efbd25248d823.tar.gz
-- Cleaning sources at E:/vcpkg/src/buildtrees/yasm-tool/src/d25248d823-818ed1bbf4.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/vcpkg/src/downloads/yasm-yasm-009450c7ad4d425fa5a10ac4bd6efbd25248d823.tar.gz
-- Using source at E:/vcpkg/src/buildtrees/yasm-tool/src/d25248d823-818ed1bbf4.clean
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Installing: E:/vcpkg/src/packages/yasm-tool_x86-windows/share/yasm-tool/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\phoebe\AppData\Local\vcpkg\archives\48\48e9787bab490d3a8c48a5d23fbb4ccada43d871.zip
Building package yasm-tool[core]:x86-windows... done
Installing package yasm-tool[core]:x86-windows...
Installing package yasm-tool[core]:x86-windows... done
Elapsed time for package yasm-tool:x86-windows: 43.04 s

Total elapsed time: 48.69 s
```

**Comment by MCJack123** [comment]
```
>git rev-parse HEAD
2aaa67573085c24bcb4e224b87605d708d9a6377
```

I see now why it was refusing to install - I was attempting to run it in the directory I have the manifest in, which causes it to expect a manifest install, and not a package install. The code above works when in another directory; however, it does not affect the installation prefix where Visual Studio looks for packages when automatic manifest dependency downloading is enabled.

I think the thing you're missing is that this issue specifically affects manifest files. Try making a new directory (outside the main `vcpkg` root), and add a `vcpkg.json` file with these contents:
```json
{
    "name": "test",
    "version-string": "1.0",
    "description": "Test package",
    "dependencies": ["3fd"]
}
```
Then run `vcpkg --feature-flags=manifests install --target=x64-windows` inside the same directory as `vcpkg.json`. I'll add this to the repro instructions in the OP as well.

For reference, here is my (approximate) directory structure:
```
CraftOS-PC-2
├─ CraftOS-PC 2.sln
├─ CraftOS-PC 2.vcxproj
├─ src
│  └─ C++ source files
├─ vcpkg.json
└─ vcpkg_installed
   ├─ x64-windows
   └─ vcpkg
      ├─ info
      ├─ updates
      └─ status
```

Here's my `vcpkg.json`:
```json
{
    "name": "craftos-pc",
    "version-string": "v2.5",
    "description": "Advanced ComputerCraft emulator",
    "dependencies": [
        "sdl2",
        "poco",
        {
            "name": "dirent",
            "platform": "windows"
        }
    ],
    "default-features": ["cli", "speaker", "pdf-printer", "png-screenshots"],
    "features": {
        "cli": {
            "description": "Console interface",
            "dependencies": [
                {
                    "name": "pdcurses",
                    "platform": "windows"
                }
            ]
        },
        "speaker": {
            "description": "Speaker/sound support",
            "dependencies": [
                {
                    "name": "sdl2-mixer",
                    "default-features": true,
                    "features": [ "dynamic-load", "libflac", "mpg123", "libmodplug", "libvorbis", "opusfile", "fluidsynth" ]
                },
                {
                    "name": "yasm-tool",
                    "platform": "windows & x86"
                }
            ]
        },
        "pdf-printer": {
            "description": "Print to PDF file with printer",
            "dependencies": [ "libharu" ]
        },
        "png-screenshots": {
            "description": "Take screenshots in PNG format",
            "dependencies": [ "pngpp" ]
        }
    }
}
```

In my VC++ project, I have the `vcpkg > Use Vcpkg Manifest` and `vcpkg > Install Vcpkg Dependencies` set to `Yes`. Upon clicking "▶ Local Windows Debugger", it attempts to download the dependencies (through `vcpkg --feature-flags=manifests install --target=x64-windows` or similar in the project directory, I assume), and in the process removes any and all packages that are not declared in the manifest or used for the present target, including `yasm-tool:x86-windows` if previously installed. I can see this being a problem for developers that use manifests and frequently switch between building for x86 and x64, as changing targets ends up deleting the opposite target's build files, and switching back will cause those packages to be re-downloaded (or cached) and re-built, costing a lot of time.

I think the best solution for now would be to not remove undeclared packages, especially not if they're still declared for a different target than is being built for. Ideally it would be possible to install packages for different targets in the manifest (e.g. `{"name": "yasm-tool:x86-windows", "platform": "!(windows & x86)"}`), as I wouldn't have to direct people who are building my code from source to install `yasm-tool:x86-windows` manually, but I don't know how vcpkg's current architecture would work with that, since it seems to change a lot of things when you switch targets.

**Comment by PhoebeHui** [comment]
@MCJack123, thanks for the details!

This issue reprod, @strega-nil, could you please take a look?

Repro steps:
1. Add mpg123 to 3fd as a dependency, and remove others dependency to speed up the building process.
2. Create a C++ console project
3. Create vcpkg.json file under the project, same directory with the soultion file.
```
{
    "name": "test",
    "version-string": "1.0",
    "description": "Test package",
    "dependencies": ["3fd"]
}
```
3. Set 'Use Vcpkg manifest' to Yes.
4. Build the project with x86 configuration, and it will build and install yasm-tool:x86-windows
5. Switch to build the project with x64 configuration, it will remove yasm-tool:x86-windows. Then mpg123 build failed, since it requires yasm-tool:x86-windows.

The issue here is pre-build yasm-tool:x86-windows required to build mpg123 with triplet x64-windows, however, all x86-window ports removed in vs solution when with build x64-windows ports.

**Comment by PhoebeHui** [comment]
Currently, we have 5 ports need pre-build with x86-windows. See https://github.com/microsoft/vcpkg/blob/master/scripts/azure-pipelines/test-modified-ports.ps1#L121

**Comment by strega-nil** [comment]
Yeah, this is just not a thing that manifest mode supports, and is a major reason that manifest mode is still in beta. It's a thing that we will be working on Soon (TM).

**Comment by soumyamahunt** [comment]
This could be fixed if manifest supports defining triplet for dependencies explicitly.

**Comment by strega-nil** [comment]
@soumyamahunt that is not a feature that we are interested in supporting, since we don't think it's useful enough to outweigh the downsides. However, with the new host ports feature, we should now be able to support mpg123 on x64-windows.

**Comment by ssaue** [comment]
I notice that this issue was closed in May 21, but I just came across the same problem now when installing the x64-windows triplet ("Please install yasm-tool:x86-windows first"). How is the fix meant to work? Is there remaining work in the mpg123 port?

Should a simple manifest file like the one below work with the x64-triplet or does it require me to manually install yasm-tool for x86-windows first? I really love the manifest feature of vcpkg combined with CMake presets, and this is the first hurdle so far.

```
{
  "name": "main",
  "version-string": "latest",
  "dependencies": [
    "eigen3",
    "libflac",
    "libogg",
    "libvorbis",
    "opus",
    "mp3lame",
    "mpg123"
  ]
}
```

**Comment by dg0yt** [comment]
@ssaue Did you `git pull` to update the repository you use?

**Comment by ssaue** [comment]
@dg0yt I'm not sure that I follow you. This is a repository that we host ourselves. I've just updated the manifest file to install the new dependencies (the audio libs, including mpg123) when i ran into the problem with mpg123 and yasm-tool.

**Comment by dg0yt** [comment]
@ssaue But at some point, you do use mpg123 from the vcpkg repository, right?

**Comment by ssaue** [comment]
@dg0yt Yes, but I haven't been able to install mpg123 yet. Hence my question. Vcpkg itself is (automatically) installed as part of the Cmake toolchain (CMakePresets.json).

**Comment by ssaue** [comment]
You pointed me in the right direction and it works for me now. Is has all to do with vcpkg version, which I naively thought would be updated. I will look into how I can use versioning to solve this in a robust way.
