### ISSUE TITLE
Additional packages (*) will be modified to complete this operation. If you are sure you want to rebuild the above packages, run the command with the --recurse option

### ISSUE THREAD

**Issue by jamesben6688** [microsoft/vcpkg#15085]
Everytime when I install a new package, I get the message:
`
Additional packages (*) will be modified to complete this operation.
If you are sure you want to rebuild the above packages, run the command with the --recurse option
`
Then it will rebuild the packages that I already installed and reinstall it again, which wastes me lots of time. Is there any way that I can skip reinstalling the installed packages?

**Comment by MCJack123** [comment]
Have you upgraded your packages recently? It might be reinstalling them because they are old, and when you install packages that depend on them it upgrades them. Try running `vcpkg upgrade` and see if that helps.

**Comment by StarGate-One** [comment]
@jamesben6688 
- In addition to what @MCJack123 mentions, a port one choses to install may depend on other ports having specific features installed and the port may not have been installed with said required features.
- Example:
  - `.\vcpkg.exe install freetype[core]`
    port `freetype` is installed normally
  - At a later time you decide to install port `sfml`
    `.\vcpkg.exe install sfml[core]`
    - vcpkg checks on the dependencies of `sfml` and it needs port `freetype` with features `brotli, bzip2, zlib, and png` installed but `freetype` was installed with only the `core` features.
    - vcpkg sees this and says I need to remove `freetype` and install with features `brotli, bzip2, png and zlib`.
    - vcpkg will also see if ports `brotli, bzip2, zlib,  libpng` are installed, if not it will also install `brotli, bzip2, libpnb and zlib` as required in order to configure `freetype` properly to be used by port `sfml`.
- One can use the `.\vcpkg.exe depend-info <port[features]>` to see what other ports[features] are required to install the port. This way one can plan ahead of time what features need to be in each port to reduce the remove/install to add features to a dependent port.

**Comment by jamesben6688** [comment]
Gotcha. That solved my confusion, tku.
