### ISSUE TITLE
Update not working.

### ISSUE THREAD

**Issue by jack17529** [microsoft/vcpkg#1508]
Both GSL and folly have changed there structures , folly now has detail directory and thus changes in namespaces. Whereas GSL has changed many files including gsl folder. But still there is no updates for both when I try `vcpkg update` , I am very sorry but it is very bad for me if nothing is done here.

Please help me.

**Comment by atkawa7** [comment]
@jack17529 I was confused at first but now I understand what you are alluding to. vcpkg does not update when code in some repository changes. Someone has to manually update the portfile to the latest versions. In this case no one has volunteered just yet. If you want the latest version you could change the version in your portfile and see if it works. If it works you might consider a PR. I am sure @ras0219-msft would be glad to review it.

**Comment by Mixaill** [comment]
We need in upstream monitoring. Something like:
* Anitya: https://github.com/release-monitoring/anitya
* Repology: https://repology.org
* Debian watch: https://wiki.debian.org/debian/watch

**Comment by wangli28** [comment]
Hi @jack17529, thank you for posting this issue! GSL and folly have been upgraded to latest version, you can update vcpkg and rebuild them.
