### ISSUE TITLE
[flashlight-cuda] build failure

### ISSUE THREAD

**Issue by maxlvoad22** [microsoft/vcpkg#15096]
**Host Environment**
- OS: linux ubuntu 18
- Compiler: didn't change

**To Reproduce**
./vcpkg install flashlight-cuda

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-linux...
Could not locate cached archive: /root/.cache/vcpkg/archives/94/9461d479eeaca417a1a9db9165bf07e6341cb2aa.zip
Could not locate cached archive: /root/.cache/vcpkg/archives/9d/9d4584aa78b8744697826542f5b024007bd6d2fa.zip
Could not locate cached archive: /root/.cache/vcpkg/archives/e7/e79b02fc9e618588591b79657f74188d59cbf2ba.zip
Could not locate cached archive: /root/.cache/vcpkg/archives/3c/3c3d0dafe726bbdd2ad19c1b3ebd830fe4b909fe.zip
Could not locate cached archive: /root/.cache/vcpkg/archives/a1/a101044c27e887ad3214c26288a491183bea2700.zip
Could not locate cached archive: /root/.cache/vcpkg/archives/79/79fc2219cb2aeddec048e22278e66c6271614b5c.zip
Could not locate cached archive: /root/.cache/vcpkg/archives/18/1817b30199276a2cd605384ba64f5fbdfbcefee9.zip
Could not locate cached archive: /root/.cache/vcpkg/archives/02/0270aed018c32d0b485bfd6397bd166ba903fb71.zip
Could not locate cached archive: /root/.cache/vcpkg/archives/12/1257c50efa5b171cd9ca7dae51c43ba7818c75e6.zip
Could not locate cached archive: /root/.cache/vcpkg/archives/92/929a85a1bee6dcb53a82ad35fca20daec5b257c3.zip
Could not locate cached archive: /root/.cache/vcpkg/archives/c4/c41c4d4cdc7b7c63c16df73b915854bd4dcf929d.zip
Could not locate cached archive: /root/.cache/vcpkg/archives/3c/3cc47394b61d99e572ccab32a18a7c47c43281db.zip
Could not locate cached archive: /root/.cache/vcpkg/archives/d3/d310905afa5d16836257de36ef105d81563fcd0b.zip
Could not locate cached archive: /root/.cache/vcpkg/archives/ee/ee76809a3c735d9f2af33b0bbd1ff9165351d844.zip
Could not locate cached archive: /root/.cache/vcpkg/archives/43/439551bd9a186d4b762d9050a8406dd0c0470bc3.zip
Could not locate cached archive: /root/.cache/vcpkg/archives/9a/9ac56176f73e9e9d1ee20a677156b41b7c7c60ee.zip
Could not locate cached archive: /root/.cache/vcpkg/archives/e8/e86a8b158d51cdd2aa70f743d71b1bb7b58993ef.zip
Could not locate cached archive: /root/.cache/vcpkg/archives/48/484d339d0139a6f966d8712757ed1eba46721a6d.zip
Could not locate cached archive: /root/.cache/vcpkg/archives/de/de65c2e40541c1654c6cd44594b4ee69cdb9c20b.zip
Could not locate cached archive: /root/.cache/vcpkg/archives/ad/adaac1792e74cd9385037e4204ffcb45864591db.zip
Starting package 1/20: intel-mkl:x64-linux
Building package intel-mkl[core]:x64-linux...
CMake Error at ports/intel-mkl/portfile.cmake:15 (message):
  Could not find MKL.  Before continuing, please download and install MKL
  (20200000 or higher) from:

      https://registrationcenter.intel.com/en/products/download/3178/

  Also ensure vcpkg has been rebuilt with the latest version (v0.0.104 or
  later)
Call Stack (most recent call first):
  scripts/ports.cmake:136 (include)

Error: Building package intel-mkl:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: intel-mkl:x64-linux
  Vcpkg version: 2020.11.12-unknownhash

Additionally, attach any relevant sections from the log files above.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by Hoikas** [comment]
```
Could not find MKL. Before continuing, please download and install MKL
(20200000 or higher) from:

  https://registrationcenter.intel.com/en/products/download/3178/
```

**Comment by StarGate-One** [comment]
>Could not locate cached archive: /root/.cache/vcpkg/archives/94/9461d479eeaca417a1a9db9165bf07e6341cb2aa.zip
>... ... ... etc etc etc
>Could not locate cached archive: /root/.cache/vcpkg/archives/ad/adaac1792e74cd9385037e4204ffcb45864591db.zip

- This is an informative message saying vcpkg could not find a previously compiled suitable cached version of the ports one has specified on the `vcpkg install` command line. 
- This is part of the binary caching feature with vcpkg to reduce build/compile/link/install time.
- References: 
https://github.com/microsoft/vcpkg/blob/master/docs/users/binarycaching.md -and-
https://vcpkg.readthedocs.io/en/latest/specifications/binarycaching/ -and-
https://devblogs.microsoft.com/cppblog/vcpkg-accelerate-your-team-development-environment-with-binary-caching-and-manifests/


>CMake Error at ports/intel-mkl/portfile.cmake:15 (message):
>Could not find MKL. Before continuing, please download and install MKL (20200000 or higher) from:
>
>  https://registrationcenter.intel.com/en/products/download/3178/
> 

- One needs to go to the website register/subscribe, download and install Intel MKL before you can install it within vcpkg. 
- It is similar to ports atlmfc, cuda, vulkan - one has to register/subscribe/download/install the software before the port can be installed in vcpkg.
- vcpkg does not actually install these ports, vcpkg just provides a reference to the files so other ports are able to find/use them.

**Comment by PhoebeHui** [comment]
You can also reference https://github.com/microsoft/vcpkg/issues/15309#issuecomment-752341675.

**Comment by AND2797** [comment]
Is this only for windows? What about Linux? It appears no registration is required for that but the error still persists.

**Comment by AND2797** [comment]
It looks like the Linux version does not require registration, but the error still persists?
