### ISSUE TITLE
[New Port Request] qt5-service

### ISSUE THREAD

**Issue by phoenix741** [microsoft/vcpkg#15094]
Library name: qt5-service

Library description: Add service capability to qt5

Source repository URL: https://github.com/Skycoder42/QtService

Project homepage (if different from the source repository): https://github.com/Skycoder42/QtService

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

 * QtProject that can be build with qmake
 * Dependant of qt5

Thanks a lot

**Comment by phoenix741** [comment]
To build (as it's qmake) i have put this on linux (environment variable):

ENV QMAKE_LINK=clang++
ENV QMAKE_CXX=clang++
ENV QTDIR=/src/vcpkg/installed/x64-linux/lib
ENV QMAKESPEC=/src/vcpkg/installed/x64-linux/tools/qt5/mkspecs/linux-g++
ENV PATH=/src/vcpkg/installed/x64-linux/tools/qt5/bin/:$PATH
ENV QT_PLUGIN_PATH=/src/vcpkg/installed/x64-linux/plugins/
ENV QTTOOLDIR=/src/vcpkg/installed/x64-linux/bin
ENV QTLIBDIR=/src/vcpkg/installed/x64-linux/lib
ENV QT_SELECT=vcpkg

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
