### ISSUE TITLE
[lcms]x64-windows failed

### ISSUE THREAD

**Issue by gm8811** [microsoft/vcpkg#15098]
**Host Environment**
- OS:Win10 professional
  Package: jasper:x64-windows
  Vcpkg version: 2020.11.12-nohash

**To Reproduce**
/vcpkg.exe install devil:x64-windows

**Failure logs** 
Error: Building package jasper:x64-windows failed with: BUILD_FAILED

**Additional context**
Reinstall is failed too.

**Comment by gm8811** [comment]
This issue should be fixed in Windows SDK 10.0.18362.0 and later versions. please update the version of your Windows SDK.

**Comment by JonLiu1993** [comment]
@gm8811,Can you send out your complete error log? I cannot reproduce your problem on windows10

**Comment by gm8811** [comment]
@JonLiu1993 
CMake Error at scripts/ports.cmake:68 (message):
  Unable to empty directory: E:/Git/vcpkg/packages/lcms_x64-windows
    Files are likely in use.


I delete the directory, and it worked.
