### ISSUE TITLE
[opencv2:x64-windows-static-md] build failure

### ISSUE THREAD

**Issue by azzoti** [microsoft/vcpkg#15107]
**Host Environment**
- OS: [Windows 10]
- Compiler: revision

**To Reproduce**
.\vcpkg install opencv2:x64-windows-static-md

**Failure logs** 
C:\dev\vcpkg>vcpkg install opencv2:x64-windows-static-md
Computing installation plan...
The following packages will be built and installed:
    opencv2[core,eigen,jpeg,opengl,png,tiff]:x64-windows-static-md -> 2.4.13.7#4
Detecting compiler hash for triplet x64-windows-static-md...
Could not locate cached archive: C:\Users\timaz\AppData\Local\vcpkg\archives\d8\d86326e640dece127f57306f7db3b5911f5153d1.zip
Starting package 1/1: opencv2:x64-windows-static-md
Building package opencv2[core,eigen,jpeg,opengl,png,tiff]:x64-windows-static-md...
-- Using community triplet x64-windows-static-md. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: C:\dev\vcpkg\triplets\community\x64-windows-static-md.cmake
-- Using cached C:/dev/vcpkg/downloads/opencv-opencv-2.4.13.7.tar.gz
-- Cleaning sources at C:/dev/vcpkg/buildtrees/opencv2/src/2.4.13.7-64eb3208d2.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/dev/vcpkg/downloads/opencv-opencv-2.4.13.7.tar.gz
-- Applying patch 0002-install-options.patch
-- Applying patch 0003-force-package-requirements.patch
-- Applying patch 0004-add-ffmpeg-missing-defines.patch
-- Applying patch 0005-fix-cuda.patch
-- Using source at C:/dev/vcpkg/buildtrees/opencv2/src/2.4.13.7-64eb3208d2.clean
-- Configuring x64-windows-static-md
-- Building x64-windows-static-md-dbg
-- Building x64-windows-static-md-rel
-- Installing: C:/dev/vcpkg/packages/opencv2_x64-windows-static-md/share/opencv2/copyright
-- Performing post-build validation
Expected Debug,Dynamic crt linkage, but the following libs had invalid crt linkage:

    C:/dev/vcpkg/packages/opencv2_x64-windows-static-md/debug/lib/opencv_calib3dd.lib: Debug,Static
    C:/dev/vcpkg/packages/opencv2_x64-windows-static-md/debug/lib/opencv_contribd.lib: Debug,Static
    C:/dev/vcpkg/packages/opencv2_x64-windows-static-md/debug/lib/opencv_cored.lib: Debug,Static
    C:/dev/vcpkg/packages/opencv2_x64-windows-static-md/debug/lib/opencv_features2dd.lib: Debug,Static
    C:/dev/vcpkg/packages/opencv2_x64-windows-static-md/debug/lib/opencv_flannd.lib: Debug,Static
    C:/dev/vcpkg/packages/opencv2_x64-windows-static-md/debug/lib/opencv_gpud.lib: Debug,Static
    C:/dev/vcpkg/packages/opencv2_x64-windows-static-md/debug/lib/opencv_highguid.lib: Debug,Static
    C:/dev/vcpkg/packages/opencv2_x64-windows-static-md/debug/lib/opencv_imgprocd.lib: Debug,Static
    C:/dev/vcpkg/packages/opencv2_x64-windows-static-md/debug/lib/opencv_legacyd.lib: Debug,Static
    C:/dev/vcpkg/packages/opencv2_x64-windows-static-md/debug/lib/opencv_mld.lib: Debug,Static
    C:/dev/vcpkg/packages/opencv2_x64-windows-static-md/debug/lib/opencv_nonfreed.lib: Debug,Static
    C:/dev/vcpkg/packages/opencv2_x64-windows-static-md/debug/lib/opencv_objdetectd.lib: Debug,Static
    C:/dev/vcpkg/packages/opencv2_x64-windows-static-md/debug/lib/opencv_ocld.lib: Debug,Static
    C:/dev/vcpkg/packages/opencv2_x64-windows-static-md/debug/lib/opencv_photod.lib: Debug,Static
    C:/dev/vcpkg/packages/opencv2_x64-windows-static-md/debug/lib/opencv_stitchingd.lib: Debug,Static
    C:/dev/vcpkg/packages/opencv2_x64-windows-static-md/debug/lib/opencv_superresd.lib: Debug,Static
    C:/dev/vcpkg/packages/opencv2_x64-windows-static-md/debug/lib/opencv_tsd.lib: Debug,Static
    C:/dev/vcpkg/packages/opencv2_x64-windows-static-md/debug/lib/opencv_videod.lib: Debug,Static
    C:/dev/vcpkg/packages/opencv2_x64-windows-static-md/debug/lib/opencv_videostabd.lib: Debug,Static

**Additional context**
Tried vcpkg update and git pull  / vcpkg update - same result

**Comment by Cheney-W** [comment]
This issue has not been updated for over 3 months, so if it is still an issue, please reopen the issue.
