### ISSUE TITLE
CMake find_package(wxWidgets) fails with vcpkg wxwidgets package

### ISSUE THREAD

**Issue by LegalizeAdulthood** [microsoft/vcpkg#15106]
**Describe the bug**
vcpkg builds and installs wxwidgets but CMake find_package can't locate wxwidgets from vcpkg package

**Environment**
- OS: Windows
- Compiler: VS 2019

**To Reproduce**
1. Unpack attached zip [example-wxwidgets.zip](https://github.com/microsoft/vcpkg/files/5690499/example-wxwidgets.zip)
2. Run CMake with the vcpkg toolchain file to generate a build
3. CMake fails at configure time attempting to find wxwidgets because setup.h is in the wrong directory (see my comments on this [related issue](https://github.com/microsoft/vcpkg/issues/11247) and this [pull request](https://github.com/microsoft/vcpkg/pull/4846))

**Expected behavior**
The package created by vcpkg should be compatible with existing CMake wxWidgets find modules.

**Failure logs** 
- See attached zip

**Additional context**
n/a

**Comment by LegalizeAdulthood** [comment]
Since this fails at configure time, a regression test case would simply build vcpkg and attempt to configure the example in the ZIP. 
 The example is ['Hello World!"](https://docs.wxwidgets.org/3.0/overview_helloworld.html) from the wxwidgets.org site.  If the configure step in CMake succeeds, then we successfully found wxWidgets via find_package from the package created by vcpkg.

**Comment by LegalizeAdulthood** [comment]
OK, it seems that wxWidgets find modules expect a directory layout that is similar to what you get after a build of wxWidgets and vcpkg is re-organizing the entire directory tree, confusing the find modules.

I don't think vcpkg should be reorganizing the directories into a form not recognized by the find modules in CMake.

**Comment by NancyLi1013** [comment]
Hi @LegalizeAdulthood 

Thanks for posting this issue.

It's duplicated to #4756, which will be fixed via PR #13361.

Let's move the attention to #4756.
