### ISSUE TITLE
Will FEATURE override variables in CMakeLists.txt?

### ISSUE THREAD

**Issue by playgithub** [microsoft/vcpkg#15100]
If yes, when? after patches?

**Comment by vicroms** [comment]
You can check what variables will be affected by a feature by reading the `portfile.cmake` of the port. 

In general the following steps occur when executing a portfile.

* Download and extract sources.
* (Optional) Apply patches. 
* (Optional) Evaluate features.
* Configure CMake (this is when variables set by features are passed to CMake).
* Build and install package.
* (Optional) Fix CMake target files.
* Clean up library output.
* Run post-build validations.
