### ISSUE TITLE
ffmpeg pkg-config files generate cygwin paths

### ISSUE THREAD

**Issue by jmoguillansky-gpsw** [microsoft/vcpkg#15111]
**Describe the bug**
when building ffmpeg:x64-windows, the pkg-config files have cygwin paths, e.g. /cygdrive/c/Users/...
How can we build ffmpeg:x64-windows so that the pkg-config files have windows paths?

**Environment**
- OS: Windows
- Compiler: Visual Studio 2019

**To Reproduce**
1. ./vcpkg install ffmpeg[ffmpeg]:x64-windows
2. Look at generated pkg-config file in installed/x64-windows/lib/pkgconfig

**Expected behavior**
The pkg-config files should have windows paths not cygwin paths?  

**Failure logs** 
-(please attached failure logs)

**Additional context**

**Comment by jmoguillansky-gpsw** [comment]
The ffmpeg script ports/ffmpeg/build.sh.in currently generates cygwin paths:

PATH_TO_PACKAGE_DIR=$(cygpath "@INST_PREFIX@")
sh "$PATH_TO_SRC_DIR/configure" "--prefix=$PATH_TO_PACKAGE_DIR" @CONFIGURE_OPTIONS@

I think we should use windows paths by default?  Maybe there can be a config option to build for cygwin target?

**Comment by JackBoosY** [comment]
I think the reason why the prefix is `/cygdrive/` is that we use a cross-compilation system (msys2).
