### ISSUE TITLE
Build failure using ./bootstrap-vcpkg.sh in arm64 Ubuntu 18.04.5 LTS

### ISSUE THREAD

**Issue by moonriseny** [microsoft/vcpkg#15118]
**Describe the bug**
When I ran ./bootstrap-vcpkg.sh, I got following error,

FAILED: CMakeFiles/vcpkglib.dir/src/vcpkg/base/files.cpp.o
/usr/bin/g++-8 -DVCPKG_USE_STD_FILESYSTEM=1 -I../include -O3 -DNDEBUG -include /home/moonriseny/Json/vcpkg/toolsrc/include/pch.h -pthread -std=c++17 -MD -MT CMakeFiles/vcpkglib.dir/src/vcpkg/base/files.cpp.o -MF CMakeFiles/vcpkglib.dir/src/vcpkg/base/files.cpp.o.d -o CMakeFiles/vcpkglib.dir/src/vcpkg/base/files.cpp.o -c ../src/vcpkg/base/files.cpp
g++-8: fatal error: Killed signal terminated program cc1plus
compilation terminated.

**Environment**
- OS: [e.g. Windows/Linux etc...]
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

- Compiler: revision
gcc (Ubuntu/Linaro 8.4.0-1ubuntu1~18.04) 8.4.0

**To Reproduce**
1. ./bootstrap-vcpkg.sh 
2. See error

**Expected behavior**
vcpkg is installed sucessfully.

**Failure logs** 
I have tried 3 different version of gcc, gcc6, gcc7, and gcc8, they were all failed, I've attached all of them
[bootstrap-vcpkg_gcc6.log](https://github.com/microsoft/vcpkg/files/5692770/bootstrap-vcpkg_gcc6.log)
[bootstrap-vcpkg_gcc7.log](https://github.com/microsoft/vcpkg/files/5692771/bootstrap-vcpkg_gcc7.log)
[bootstrap-vcpkg_gcc8.log](https://github.com/microsoft/vcpkg/files/5692772/bootstrap-vcpkg_gcc8.log)

**Additional context**

**Comment by PhoebeHui** [comment]
@moonriseny, unfortunately this is not official support, I don't have the environment to confirm, but from the failure log, it looks a compiler issue.

**Comment by moonriseny** [comment]
Thanks for your prompt response, @PhoebeHui, did you mean the OS or CPU (arm64) not official support? Here is my compiler info:

gcc (Ubuntu/Linaro 8.4.0-1ubuntu1~18.04) 8.4.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by PhoebeHui** [comment]
@moonriseny, we don't support arm64 on linux officially, however, we have community triplet for arm64-linux, we haven't get any issue reported about building vcpkg in this environment before. I tried to build vcpkg with x64-linux via gcc7.5 on ubuntu 18.04, everything built successfully.

Failures from your logs, the errors usually indicate that have a bug in compiler, not vcpkg.  You may need to report the error to the compiler team.
```
gcc6/gcc7: internal compiler error: Killed (program cc1plus)
g++-8: fatal error: Killed signal terminated program cc1plus
```

**Comment by moonriseny** [comment]
@PhoebeHui Thanks, I will file a bug report to GCC. By the way, what is "community triplet for arm64-linux", where I can download it?

**Comment by PhoebeHui** [comment]
Here is https://github.com/microsoft/vcpkg/blob/master/triplets/community/arm64-linux.cmake.

See more information from https://github.com/microsoft/vcpkg/blob/master/docs/users/triplets.md

**Comment by moonriseny** [comment]
I've tried to run "vcpkg install boost:arm64-linux" on our x64-linux machine, it failed with compiler aarch64-linux-gnu-gcc error, my OS is CentOS 7, anyway, thanks for your support, I'll wait for your official support for arm64.
