### ISSUE TITLE
[New Port Request] <HP-Socket>

### ISSUE THREAD

**Issue by a952135763** [microsoft/vcpkg#15119]
Library name:HP-Socket

Library description:High Performance Network Framework

Source repository URL:https://github.com/ldcsaa/HP-Socket

This is the build script for some other tools↓
Xmake script: https://github.com/xmake-io/xmake-repo/blob/master/packages/h/hpsocket/xmake.lua

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
