### ISSUE TITLE
How to handle submodules in git, when create a new port?

### ISSUE THREAD

**Issue by saedrna** [Microsoft/vcpkg#1513]
I would like to port [openMVG](https://github.com/openMVG/openMVG), a widely used photogrammetry library, and currently almost all the deps are in vcpkg. However, when release the code, openMVG doesn't package all the submodules in a folder named "dependencies".

So my question is, is it possible to use command like `git clone url --recursive` rather than download a package to initialize the port? This is the only way I know to init the submodules.

**Comment by Voskrese** [comment]
@saedrna hmm..
https://ci.appveyor.com/project/pmoulon/openmvg/build/job/r9f4lnpjm53lqxnr
`git submodule update --init --recursive`
`git clone --recursive https://github.com/openMVG/openMVG.git openMVG`

**Comment by saedrna** [comment]
@Voskrese 

The following are all included in vcpkg
```
-- EIGEN: 3.3.1 (internal)
-- CERES: 1.11.0 (internal)
-- FLANN: 1.8.4 (internal)
-- LIBTIFF:  (internal)
-- LIBPNG:  (internal)
-- LIBJPEG (internal)
```

And we could just use the internal deps of Coin-Or tools and Lemon by openmvg ?

**Comment by bagong** [comment]
This is a general problem. Internal dependencies can use different versions than the ones current in vcpkg...

**Comment by ras0219-msft** [comment]
> So my question is, is it possible to use command like git clone url --recursive rather than download a package to initialize the port? This is the only way I know to init the submodules.

You can use a second argument to `vcpkg_extract_source_archive()`[1] to specify where a given archive should be extracted -- this means you can download each of the submodules and unpack them into the appropriate locations if they're truly needed.

However, as you've pointed out, most of the submodules are already available in Vcpkg. In this case, I would recommend doing the minimum required to satisfy their CMake build and instead use Vcpkg's prebuilt copies instead. For example:
```cmake
file(MAKE_DIRECTORY ${SOURCE_PATH}/dependencies/cereal/include)
```

Ideally, we should package `osi`, `clp`, and `coinutils` separately and enable the non-internal usage mode by defining `OSI_INCLUDE_DIR_HINTS`, `CLP_INCLUDE_DIR_HINTS`, and `COINUTILS_INCLUDE_DIR_HINTS`.

**Comment by pmoulon** [comment]
@saedrna Did you made any progress on this?
Does there is a way to run manually a command like `git submodule init` and `git submodule update`?

**Comment by saedrna** [comment]
@pmoulon , Nope, there should be substantially changes in handling the deps library. In vcpkg, the ideal way is to port all the deps separately and setting the the `CMAKE_******_PATH_HINTS` to let cmake find it. 

In addition, even if we just use cmake to dowload other libraries from github master and extract into the right place (it's possible), there should be a lot changes in installing cmake config files. Probably, installing shared libs in vcpkg is simpler, by setting `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=ON`, and do not install the static libraries such as `osi`, `clp` and `coinutils` in openmvg.

**Comment by pmoulon** [comment]
I think the VCPKG could consider to add GIT to https://github.com/Microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_find_acquire_program.md so this way we would be able to run a git command from https://github.com/Microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_execute_required_process.md

The advantage of using git submodule is that you can have your own version of some library.

@ras0219-msft Any new comment about make git command available to everyone?

You already allow python, bash, so allowing git should not be a problem!
