### ISSUE TITLE
[ New Port Request ] : pHash

### ISSUE THREAD

**Issue by hanumantmule** [microsoft/vcpkg#15133]
Library name: pHash

Library description: pHash is an open source software library released under the GPLv3 license that implements several perceptual hashing algorithms, and provides a C-like API to use those functions in your own programs. pHash itself is written in C++.

Source repository URL: https://github.com/aetilius/pHash/

Project homepage (if different from the source repository): 

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
