### ISSUE TITLE
[protobuf] build failure:  'compiler is broken', can't open ucrtd.lib (I have 17 ucrtd.lib files)

### ISSUE THREAD

**Issue by MrScottAtt** [microsoft/vcpkg#15145]
**Host Environment**
- OS: Windows:  (per command window output) Microsoft Windows [Version 10.0.19041.630]
- Compiler: Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27043 for x64, installed at:  C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64\cl.exe
- Hardware:  HP ZBook 15 G2, virtualization enabled

**To Reproduce**
Have VS2017 Professional (licensed) and Community editions installed.
In command prompt window:
1. Create new directory, here C:\src\vcpkg
2. CD to C:\src\
3. Execute (which succeeds):   `.\vcpkg\bootstrap-vcpkg.bat`
4. CD to C:\src\vcpkg\
5. Execute (fails, perhaps because no triplet at first):  '.\vcpkg install protobuf'
6. Try again in PowerShell window, with triplet:
    'PS C:\src\vcpkg> .\vcpkg install protobuf --triplet x64-windows-static'

Same thing happens in a PowerShell window and a PowerShell window with Admin privileges.

**Failure logs** 
[config-x64-windows-static-out.log](https://github.com/microsoft/vcpkg/files/5699055/config-x64-windows-static-out.log)
** Console Output**
```
C:\src>.\vcpkg\bootstrap-vcpkg.bat

Building vcpkg.exe ...

  pch.cpp
  archives.cpp
  checks.cpp
  chrono.cpp
  cofffilereader.cpp
  downloads.cpp
  enums.cpp
  files.cpp
  hash.cpp
  json.cpp
  machinetype.cpp
  parse.cpp
  strings.cpp
  stringview.cpp
  system.cpp
  system.print.cpp
  system.process.cpp
  unicode.cpp
  xmlserializer.cpp
  binarycaching.cpp
  binaryparagraph.cpp
  build.cpp
  buildenvironment.cpp
  cmakevars.cpp
  commands.autocomplete.cpp
  commands.buildexternal.cpp
  commands.cache.cpp
  commands.ci.cpp
  commands.ciclean.cpp
  commands.contact.cpp
  commands.cpp
  commands.create.cpp
  commands.dependinfo.cpp
  commands.edit.cpp
  commands.env.cpp
  commands.fetch.cpp
  commands.format-manifest.cpp
  commands.hash.cpp
  commands.info.cpp
  commands.integrate.cpp
  commands.list.cpp
  commands.owns.cpp
  commands.porthistory.cpp
  commands.portsdiff.cpp
  commands.search.cpp
  commands.setinstalled.cpp
  commands.upgrade.cpp
  commands.upload-metrics.cpp
  commands.version.cpp
  commands.xvsinstances.cpp
  configuration.cpp
  dependencies.cpp
  export.cpp
  export.chocolatey.cpp
  export.ifw.cpp
  export.prefab.cpp
  globalstate.cpp
  help.cpp
  input.cpp
  install.cpp
  platform-expression.cpp
  metrics.cpp
  packagespec.cpp
  paragraphs.cpp
  portfileprovider.cpp
  postbuildlint.buildtype.cpp
  postbuildlint.cpp
  registries.cpp
  remove.cpp
  sourceparagraph.cpp
  statusparagraph.cpp
  statusparagraphs.cpp
  tools.cpp
  triplet.cpp
  update.cpp
  userconfig.cpp
  vcpkgcmdarguments.cpp
  vcpkglib.cpp
  vcpkgpaths.cpp
  versiondeserializers.cpp
  versions.cpp
  versiont.cpp
  visualstudio.cpp
  vcpkg.cpp
  Generating code
  All 27506 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Finished generating code
  vcpkg.vcxproj -> C:\src\vcpkg\toolsrc\windows-bootstrap\msbuild.x86.release\vcpkg.exe

Building vcpkg.exe... done.

Telemetry
---------
vcpkg collects usage data in order to help us improve your experience.
The data collected by Microsoft is anonymous.
You can opt-out of telemetry by re-running the bootstrap-vcpkg script with -disableMetrics,
passing --disable-metrics to vcpkg on the command line,
or by setting the VCPKG_DISABLE_METRICS environment variable.

Read more about vcpkg telemetry at docs/about/privacy.md
```
```
C:\src>.\vcpkg\vcpkg install protobuf
Computing installation plan...
A suitable version of cmake was not found (required v3.18.4). Downloading portable cmake v3.18.4...
Downloading cmake...
  https://github.com/Kitware/CMake/releases/download/v3.18.4/cmake-3.18.4-win32-x86.zip -> C:\src\vcpkg\downloads\cmake-3.18.4-win32-x86.zip
Extracting cmake...
A suitable version of 7zip was not found (required v18.1.0). Downloading portable 7zip v18.1.0...
Downloading 7zip...
  https://www.nuget.org/api/v2/package/7-Zip.CommandLine/18.1.0 -> C:\src\vcpkg\downloads\7-zip.commandline.18.1.0.nupkg
Extracting 7zip...
A suitable version of nuget was not found (required v5.5.1). Downloading portable nuget v5.5.1...
Downloading nuget...
  https://dist.nuget.org/win-x86-commandline/v5.5.1/nuget.exe -> C:\src\vcpkg\downloads\22ea847d-nuget.exe
The following packages will be built and installed:
    protobuf[core]:x86-windows -> 3.14.0
Detecting compiler hash for triplet x86-windows...
A suitable version of powershell-core was not found (required v7.0.3). Downloading portable powershell-core v7.0.3...
Downloading powershell-core...
  https://github.com/PowerShell/PowerShell/releases/download/v7.0.3/PowerShell-7.0.3-win-x86.zip -> C:\src\vcpkg\downloads\PowerShell-7.0.3-win-x86.zip
Extracting powershell-core...
Could not locate cached archive: C:\Users\scottw\AppData\Local\vcpkg\archives\93\93dc2b3e1c16d1d56968c5d7139b150cd8dc103e.zip
Starting package 1/1: protobuf:x86-windows
Building package protobuf[core]:x86-windows...
-- Downloading https://github.com/protocolbuffers/protobuf/archive/2514f0bd7da7e2af1bed4c5d1b84f031c4d12c10.tar.gz...
-- Extracting source C:/src/vcpkg/downloads/protocolbuffers-protobuf-2514f0bd7da7e2af1bed4c5d1b84f031c4d12c10.tar.gz
-- Applying patch fix-static-build.patch
-- Using source at C:/src/vcpkg/buildtrees/protobuf/src/31c4d12c10-72e3050aec.clean
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:108 (message):
    Command failed: ninja -v
    Working Directory: C:/src/vcpkg/buildtrees/protobuf/x86-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\src\vcpkg\buildtrees\protobuf\config-x86-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:319 (vcpkg_execute_required_process)
  ports/protobuf/portfile.cmake:45 (vcpkg_configure_cmake)
  scripts/ports.cmake:136 (include)


Error: Building package protobuf:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: protobuf:x86-windows
  Vcpkg version: 2020.11.12-nohash

Additionally, attach any relevant sections from the log files above.
```
```
C:\src>set
AF_PATH=C:\Program Files\ArrayFire\v3
AF_PATH_v3=C:\Program Files\ArrayFire\v3
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\scottw\AppData\Roaming
CAMEXPERTDIR=C:\Program Files\Teledyne DALSA\Sapera\CamExpert
ChocolateyInstall=C:\ProgramData\chocolatey
ChocolateyLastPathUpdate=132460587140336592
ChocolateyToolsLocation=C:\tools
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=BC20041
ComSpec=C:\WINDOWS\system32\cmd.exe
CORSNIDDIR=C:\Program Files\Teledyne DALSA\Network Interface
CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2
CUDA_PATH_V9_2=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2
DriverData=C:\Windows\System32\Drivers\DriverData
GENICAM_CACHE_V2_4=C:\ProgramData\GenICam\xml\cache
GENICAM_LOG_CONFIG_V2_4=C:\Program Files\GenICam_v2_4\log\config\DebugLogging.properties
GENICAM_ROOT_V2_4=C:\Program Files\GenICam_v2_4
HOMEDRIVE=C:
HOMEPATH=\Users\scottw
LOCALAPPDATA=C:\Users\scottw\AppData\Local
LOGONSERVER=\\ATT-DC1
MOSQUITTO_DIR=C:\Program Files\mosquitto
NUMBER_OF_PROCESSORS=8
NVCUDASAMPLES9_2_ROOT=C:\ProgramData\NVIDIA Corporation\CUDA Samples\v9.2
NVCUDASAMPLES_ROOT=C:\ProgramData\NVIDIA Corporation\CUDA Samples\v9.2
NVTOOLSEXT_PATH=C:\Program Files\NVIDIA Corporation\NvToolsExt\
OneDrive=C:\Users\scottw\OneDrive - ATT Metrology Services
OneDriveCommercial=C:\Users\scottw\OneDrive - ATT Metrology Services
OPENCV_DIR=C:\tools\opencv\Build\x64\vc17
OS=Windows_NT
Path=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2\libnvvp;C:\Python39\Scripts\;C:\Python39\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\ProgramData\chocolatey\bin;C:\Program Files\OpenSSL\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\GenICam_v2_4\bin\Win64_x64;C:\Program Files\CameraLink\Serial;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\Git\cmd;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Users\scottw\.poetry\bin;C:\Users\scottw\AppData\Local\Microsoft\WindowsApps;C:\tools\opencv\Build\x64\vc17;C:\Program Files\CMake\bin;C:\Users\scottw\.dotnet\tools
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=3c03
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=$P$G
PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
PUBLIC=C:\Users\Public
SAPERADIR=C:\Program Files\Teledyne DALSA\Sapera
SESSIONNAME=Console
SystemDrive=C:
SystemRoot=C:\WINDOWS
TELEDYNE_DALSA_GENICAM_ROOT=C:\Program Files\Teledyne DALSA\GenICam
TEMP=C:\Users\scottw\AppData\Local\Temp
TMP=C:\Users\scottw\AppData\Local\Temp
USERDNSDOMAIN=ATTINC.COM
USERDOMAIN=ATTINC
USERDOMAIN_ROAMINGPROFILE=ATTINC
USERNAME=scottw
USERPROFILE=C:\Users\scottw
VS140COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\
windir=C:\WINDOWS
```

**Additional context**
PowerShell version:   PS C:\src\vcpkg> (get-host).Version
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      19041  610

 - Question:  it's complaining that it cannot find 'ucrtd.lib'.  Where is ucrtd.lib expected to be, how does it get there, how is the search patch created / what is the search path used?  Wondering whether systems set up for developing and testing vcpkg have that .lib file installed or an environment variable set that allows them to find it. 

**Other attempts to resolve**

- Re-ran in PowerShell.
- Looking at config-x64-windows-static-out.log, it decided that my C compiler was broken because it could not open ucrtd.lib.
- Note that looking in CMakeError.log and CMakeOutput.log, **'ucrtd.lib' is not listed** in the command lines.  Was this an implicit inclusion, or missing from the command line?
- I definitely have 'ucrtd.lib', being on a project with multiple Windows SDKs installed; there are 17 ucrtd.lib files on my system, for various architectures.  Where is it looking for the file?
- See [](https://social.msdn.microsoft.com/Forums/en-US/7a2f61b7-3c01-4767-9a30-e897dc240e60/lnk1104-cannot-open-file-ucrtdlib) which suggests that Windows SDK 10.0.10240.0 contains the file.
- Interestingly, while I see that SDK in directory listings, it's not showing up in "Apps & features".
```
C:\Users\scottw\source\repos\CommonTeam\CommonLibs\x64\Release>dir /s C:\ucrtd.lib
 Volume in drive C has no label.
 Volume Serial Number is AC60-D99F

 Directory of C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\SDK\ScopeCppSDK\SDK\lib

11/30/2020  01:47 PM           249,628 ucrtd.lib
               1 File(s)        249,628 bytes

 Directory of C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10240.0\ucrt\arm

07/09/2015  06:15 PM           248,856 ucrtd.lib
               1 File(s)        248,856 bytes

 Directory of C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10240.0\ucrt\arm64

07/09/2015  06:08 PM           248,686 ucrtd.lib
               1 File(s)        248,686 bytes

 Directory of C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10240.0\ucrt\x64

07/09/2015  06:37 PM           249,628 ucrtd.lib
               1 File(s)        249,628 bytes

 Directory of C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10240.0\ucrt\x86

07/09/2015  07:10 PM           263,290 ucrtd.lib
               1 File(s)        263,290 bytes

 Directory of C:\Program Files (x86)\Windows Kits\10\Lib\10.0.16299.0\ucrt\arm

09/28/2017  04:37 PM           248,856 ucrtd.lib
               1 File(s)        248,856 bytes

 Directory of C:\Program Files (x86)\Windows Kits\10\Lib\10.0.16299.0\ucrt\arm64

09/28/2017  04:41 PM           248,686 ucrtd.lib
               1 File(s)        248,686 bytes

 Directory of C:\Program Files (x86)\Windows Kits\10\Lib\10.0.16299.0\ucrt\x64

09/28/2017  05:12 PM           249,628 ucrtd.lib
               1 File(s)        249,628 bytes

 Directory of C:\Program Files (x86)\Windows Kits\10\Lib\10.0.16299.0\ucrt\x86

09/28/2017  04:51 PM           263,290 ucrtd.lib
               1 File(s)        263,290 bytes

 Directory of C:\Program Files (x86)\Windows Kits\10\Lib\10.0.17134.0\ucrt\arm

04/19/2018  11:01 AM           248,856 ucrtd.lib
               1 File(s)        248,856 bytes

 Directory of C:\Program Files (x86)\Windows Kits\10\Lib\10.0.17134.0\ucrt\arm64

04/19/2018  11:02 AM           248,686 ucrtd.lib
               1 File(s)        248,686 bytes

 Directory of C:\Program Files (x86)\Windows Kits\10\Lib\10.0.17134.0\ucrt\x64

04/19/2018  11:04 AM           249,628 ucrtd.lib
               1 File(s)        249,628 bytes

 Directory of C:\Program Files (x86)\Windows Kits\10\Lib\10.0.17134.0\ucrt\x86

04/19/2018  11:07 AM           263,290 ucrtd.lib
               1 File(s)        263,290 bytes

 Directory of C:\Program Files (x86)\Windows Kits\10\Lib\10.0.17763.0\ucrt\arm

10/22/2018  07:53 PM           248,856 ucrtd.lib
               1 File(s)        248,856 bytes

 Directory of C:\Program Files (x86)\Windows Kits\10\Lib\10.0.17763.0\ucrt\arm64

10/22/2018  07:43 PM           248,686 ucrtd.lib
               1 File(s)        248,686 bytes

 Directory of C:\Program Files (x86)\Windows Kits\10\Lib\10.0.17763.0\ucrt\x64

10/22/2018  07:45 PM           249,628 ucrtd.lib
               1 File(s)        249,628 bytes

 Directory of C:\Program Files (x86)\Windows Kits\10\Lib\10.0.17763.0\ucrt\x86

10/22/2018  08:08 PM           263,290 ucrtd.lib
               1 File(s)        263,290 bytes

     Total Files Listed:
              17 File(s)      4,291,468 bytes
               0 Dir(s)  12,867,289,088 bytes free
```
[CMakeError.log](https://github.com/microsoft/vcpkg/files/5699154/CMakeError.log)
[CMakeOutput.log](https://github.com/microsoft/vcpkg/files/5699156/CMakeOutput.log)

**Comment by JackBoosY** [comment]
It looks like your Visual Studio configuration may have been modified and broken, can you fix Visual Studio using Visual Studio Installer and try again?

Thanks.

**Comment by JackBoosY** [comment]
And 2 more question I need to ask:
1. Did you use powershell to run `bootstrap-vcpkg.bat`?
2. Did you modifiy the Visual Studio configuration?

**Comment by MrScottAtt** [comment]
I tried to demonstrate the issue to a colleague just now, building in Admin PS:  this time, it worked.

I've lost track of everything I've done; I think it included VS2017 settings changes, installing Hyper-V as an alternative build environment so I could try in there, etc.

What I will suggest for tracking this down is an iterative approach:  adding code that records clues and reports it when this error occurs.  Refine based on results.

PS output:
PS C:\> cd src
PS C:\src> .\vcpkg\bootstrap-vcpkg.bat

Building vcpkg.exe ...

  pch.cpp
  archives.cpp
  checks.cpp
  chrono.cpp
  cofffilereader.cpp
  downloads.cpp
  enums.cpp
  files.cpp
  hash.cpp
  json.cpp
  machinetype.cpp
  parse.cpp
  strings.cpp
  stringview.cpp
  system.cpp
  system.print.cpp
  system.process.cpp
  unicode.cpp
  xmlserializer.cpp
  binarycaching.cpp
  binaryparagraph.cpp
  build.cpp
  buildenvironment.cpp
  cmakevars.cpp
  commands.autocomplete.cpp
  commands.buildexternal.cpp
  commands.cache.cpp
  commands.ci.cpp
  commands.ciclean.cpp
  commands.contact.cpp
  commands.cpp
  commands.create.cpp
  commands.dependinfo.cpp
  commands.edit.cpp
  commands.env.cpp
  commands.fetch.cpp
  commands.format-manifest.cpp
  commands.hash.cpp
  commands.info.cpp
  commands.integrate.cpp
  commands.list.cpp
  commands.owns.cpp
  commands.porthistory.cpp
  commands.portsdiff.cpp
  commands.search.cpp
  commands.setinstalled.cpp
  commands.upgrade.cpp
  commands.upload-metrics.cpp
  commands.version.cpp
  commands.xvsinstances.cpp
  configuration.cpp
  dependencies.cpp
  export.cpp
  export.chocolatey.cpp
  export.ifw.cpp
  export.prefab.cpp
  globalstate.cpp
  help.cpp
  input.cpp
  install.cpp
  platform-expression.cpp
  metrics.cpp
  packagespec.cpp
  paragraphs.cpp
  portfileprovider.cpp
  postbuildlint.buildtype.cpp
  postbuildlint.cpp
  registries.cpp
  remove.cpp
  sourceparagraph.cpp
  statusparagraph.cpp
  statusparagraphs.cpp
  tools.cpp
  triplet.cpp
  update.cpp
  userconfig.cpp
  vcpkgcmdarguments.cpp
  vcpkglib.cpp
  vcpkgpaths.cpp
  versiondeserializers.cpp
  versions.cpp
  versiont.cpp
  visualstudio.cpp
  vcpkg.cpp
  Generating code
  All 27506 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Finished generating code
  vcpkg.vcxproj -> C:\src\vcpkg\toolsrc\windows-bootstrap\msbuild.x86.release\vcpkg.exe

Building vcpkg.exe... done.

Telemetry
---------
vcpkg collects usage data in order to help us improve your experience.
The data collected by Microsoft is anonymous.
You can opt-out of telemetry by re-running the bootstrap-vcpkg script with -disableMetrics,
passing --disable-metrics to vcpkg on the command line,
or by setting the VCPKG_DISABLE_METRICS environment variable.

Read more about vcpkg telemetry at docs/about/privacy.md
PS C:\src> cd vcpkg
PS C:\src\vcpkg> .\vcpkg install protobuf
Computing installation plan...
The following packages will be built and installed:
    protobuf[core]:x86-windows -> 3.14.0
Detecting compiler hash for triplet x86-windows...
Could not locate cached archive: C:\Users\scottw\AppData\Local\vcpkg\archives\93\93dc2b3e1c16d1d56968c5d7139b150cd8dc103e.zip
Starting package 1/1: protobuf:x86-windows
Building package protobuf[core]:x86-windows...
-- Using cached C:/src/vcpkg/downloads/protocolbuffers-protobuf-2514f0bd7da7e2af1bed4c5d1b84f031c4d12c10.tar.gz
-- Cleaning sources at C:/src/vcpkg/buildtrees/protobuf/src/31c4d12c10-72e3050aec.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/src/vcpkg/downloads/protocolbuffers-protobuf-2514f0bd7da7e2af1bed4c5d1b84f031c4d12c10.tar.gz
-- Applying patch fix-static-build.patch
-- Using source at C:/src/vcpkg/buildtrees/protobuf/src/31c4d12c10-72e3050aec.clean
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz...
-- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst...
-- Using msys root at C:/src/vcpkg/downloads/tools/msys2/c809757c94447846
-- Fixing pkgconfig file: C:/src/vcpkg/packages/protobuf_x86-windows/lib/pkgconfig/protobuf-lite.pc
-- Fixing pkgconfig file: C:/src/vcpkg/packages/protobuf_x86-windows/lib/pkgconfig/protobuf.pc
-- Fixing pkgconfig file: C:/src/vcpkg/packages/protobuf_x86-windows/debug/lib/pkgconfig/protobuf-lite.pc
-- Fixing pkgconfig file: C:/src/vcpkg/packages/protobuf_x86-windows/debug/lib/pkgconfig/protobuf.pc
-- Installing: C:/src/vcpkg/packages/protobuf_x86-windows/share/protobuf/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\scottw\AppData\Local\vcpkg\archives\93\93dc2b3e1c16d1d56968c5d7139b150cd8dc103e.zip
Building package protobuf[core]:x86-windows... done
Installing package protobuf[core]:x86-windows...
Installing package protobuf[core]:x86-windows... done
Elapsed time for package protobuf:x86-windows: 4.141 min

Total elapsed time: 4.236 min

The package protobuf:x86-windows provides CMake targets:

    find_package(protobuf CONFIG REQUIRED)
    target_link_libraries(main PRIVATE protobuf::libprotoc protobuf::libprotobuf protobuf::libprotobuf-lite)

**Comment by JackBoosY** [comment]
> I think it included VS2017 settings changes, installing Hyper-V as an alternative build environment so I could try in there, etc.

So I think the Visual Studio seeting changes and the environment changes break this.

> adding code that records clues and reports it when this error occurs. Refine based on results.
It seems so complicated, do you have any other details?

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
