### ISSUE TITLE
vcpkg fails to build glog with cmake 3.8 msvc 2017

### ISSUE THREAD

**Issue by atkawa7** [Microsoft/vcpkg#1514]
[logs.zip](https://github.com/Microsoft/vcpkg/files/1167702/logs.zip)

**Comment by jasjuang** [comment]
are you able to build glog from source with msvc 2017?

**Comment by atkawa7** [comment]
@jasjuang Using source it works but fails with vcpkg

**Comment by jasjuang** [comment]
I checked the log, the compilation error doesn't seem to be vcpkg specific. I wonder if vcpkg alters any compilation flag when compiling things. I am still on msvc 2015 because I am still waiting for the next cuda to support msvc 2017.

**Comment by ras0219-msft** [comment]
@atkawa7 Could you confirm that this issue still reproduces on the latest master?

**Comment by atkawa7** [comment]
@ras0219 @jasjuang I am still having the same problem
[glog.zip](https://github.com/Microsoft/vcpkg/files/1243882/glog.zip)

**Comment by atkawa7** [comment]
@jasjuang @ras0219-msft Finally found the problem.  Try installing  `ctemplate` first and then `glog` causes the error or vice versa. The error is caused by both projects using similar definitions and headers. See this line. 

https://github.com/OlafvdSpek/ctemplate/blob/master/src/windows/config.h#L19

```cpp
#define GOOGLE_NAMESPACE  ctemplate
```

and  on this https://github.com/google/glog/blob/master/src/windows/config.h#L4

```cpp
#define GOOGLE_NAMESPACE  google
```

**Comment by jasjuang** [comment]
Wow that's a measure blunder by google. They even mentioned in their coding guide https://google.github.io/styleguide/cppguide.html that macros should be avoided whenever possible.

Maybe you can file an issue on both glog and ctemplate to ask them to fix it?

**Comment by OlafvdSpek** [comment]
I'm confused, isn't config.h a private header?
