### ISSUE TITLE
[dbghelp] build failure

### ISSUE THREAD

**Issue by zh1an** [microsoft/vcpkg#15155]
**Host Environment**
- OS: Windows 10
- Compiler: VS2015 with update 3

**To Reproduce**
`./vcpkg install crashrpt`

**Failure logs** 
PS F:\vcpkg> .\vcpkg.exe install crashrpt                                                                               Computing installation plan...
The following packages will be built and installed:
    crashrpt[core]:x86-windows -> 1.4.3
  * dbghelp[core]:x86-windows -> 0.0
  * libjpeg-turbo[core]:x86-windows -> 2.0.5#1
  * libogg[core]:x86-windows -> 1.3.4#3
  * libpng[core]:x86-windows -> 1.6.37#14
  * libtheora[core]:x86-windows -> 1.2.0alpha1-20170719#2
  * tinyxml[core]:x86-windows -> 2.6.2-7
  * wtl[core]:x86-windows -> 10.0.10077
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x86-windows...
Could not locate cached archive: C:\Users\Zh1an\AppData\Local\vcpkg\archives\8c\8ce4e73cf94ef06f6f75c1e3b68f66514bf0db5d.zip
Could not locate cached archive: C:\Users\Zh1an\AppData\Local\vcpkg\archives\f9\f9f301a8487720b00ce4b3b1d82145612840e014.zip
Could not locate cached archive: C:\Users\Zh1an\AppData\Local\vcpkg\archives\80\80ef01147697615d0f589261984c2c4bd17c62c3.zip
Could not locate cached archive: C:\Users\Zh1an\AppData\Local\vcpkg\archives\b2\b2f31aa5539784fc14c6a78b6ae05a14483d22ae.zip
Could not locate cached archive: C:\Users\Zh1an\AppData\Local\vcpkg\archives\57\573fffb5df1c63926c200d0bd91cfb59e349d790.zip
Could not locate cached archive: C:\Users\Zh1an\AppData\Local\vcpkg\archives\52\52d83abeeb8344ddac41fa75b1c5565a8ff65009.zip
Could not locate cached archive: C:\Users\Zh1an\AppData\Local\vcpkg\archives\00\00dea03b3b29952d4f3f070d4b0d9cbc03a5c222.zip
Could not locate cached archive: C:\Users\Zh1an\AppData\Local\vcpkg\archives\44\446eba319830f4b41b7b857a9c210f6c3e4f58e6.zip
Starting package 1/8: dbghelp:x86-windows
Building package dbghelp[core]:x86-windows...
CMake Error at ports/dbghelp/portfile.cmake:14 (message):
  Portfile not yet configured for Windows SDK with version:
Call Stack (most recent call first):
  scripts/ports.cmake:136 (include)

Error: Building package dbghelp:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: dbghelp:x86-windows
  Vcpkg version: 2020.11.12-nohash

Additionally, attach any relevant sections from the log files above.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by JonLiu1993** [comment]
@zh1an ，Can you provide us with your windows SDK version?

**Comment by zh1an** [comment]
@JonLiu1993 Just now, I installed Windows Kits 10.0.19.041.0.

![image](https://user-images.githubusercontent.com/30436038/102477869-e3bd3780-4097-11eb-845b-d437f6acfcd6.png)

**Comment by zh1an** [comment]
I've installed Visual studio 2015 with update 3, WinDbg before.

**Comment by zh1an** [comment]
@JonLiu1993 after I installed the Windows Kits 10.0.19041.0, I execute the command `.\vcpkg.exe install dbghelp` and failed.

```
PS F:\vcpkg> .\vcpkg.exe install dbghelp                                                                                Computing installation plan...
The following packages will be built and installed:
    dbghelp[core]:x86-windows -> 0.0
Detecting compiler hash for triplet x86-windows...
Could not locate cached archive: C:\Users\Zh1an\AppData\Local\vcpkg\archives\c4\c41fbe296732d62d2743fd693465a08809e75d67.zip
Starting package 1/1: dbghelp:x86-windows
Building package dbghelp[core]:x86-windows...
-- C:/Program Files (x86)/Windows Kits/10
CMake Error at ports/dbghelp/portfile.cmake:17 (message):
  Portfile not yet configured for Windows SDK with version:
Call Stack (most recent call first):
  scripts/ports.cmake:136 (include)


Error: Building package dbghelp:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: dbghelp:x86-windows
  Vcpkg version: 2020.11.12-nohash

Additionally, attach any relevant sections from the log files above.
PS F:\vcpkg>                                                                                                                                                                                                                                                                   
```

**Comment by JonLiu1993** [comment]
@zh1an ,You need to install the windows SDK 10.0.18362.0 version, then use [this website](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debugger-download-tools) to download the debug tools, and then try again

**Comment by zh1an** [comment]
@JonLiu1993 It's working. Thanks.
