### ISSUE TITLE
[VTK|OpenCV4|libharu:x64-windows] build failure: silent exit just after libharu[core,notiffsymbols] successful build/install

### ISSUE THREAD

**Issue by dweckmann** [microsoft/vcpkg#15153]
**Host Environment**
- OS: Windows
- Compiler: Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29335 for x64

**To Reproduce**
`./vcpkg install --triplet x64-windows vtk opencv4[VTK]`

**Failure logs** 
No real logs (Please tell me what could help..), but the last output is:

```
Building package libharu[core,notiffsymbols]:x64-windows... done
Installing package libharu[core,notiffsymbols]:x64-windows...
Installing package libharu[core,notiffsymbols]:x64-windows... done

>  command prompt (nothing more)
````

No errors are reported. But if I relaunch the same command (`./vcpkg install --triplet x64-windows vtk opencv4[VTK]`), the build continue and all package is rightly built, without any error. 

And more problematic for me, is that the export command won't work:
`vcpkg.exe export --triplet x64-windows --x-all-installed --7zip --output=perlimpinpin`

will perform things, without errors, but at the end, no archive are present. It seems to block also on libharu. No problem without VTK, and with VTK alone.

Please tell me if there is a verbose/debug mode, or some logs, for this operation, so I can maybe give you better information.

**Comment by JackBoosY** [comment]
Hi @dweckmann, thanks for reporting this issue!
Can you use command `./vcpkg install --triplet x64-windows vtk opencv4[VTK] --debug` and provide the output?

Thanks.

**Comment by dweckmann** [comment]
` .\vcpkg.exe install --triplet x64-windows --debug vtk opencv4[VTK] > build.log`
[build.log](https://github.com/microsoft/vcpkg/files/5702555/build.log)

**Comment by JackBoosY** [comment]
According to the log you provided, I found that the content of the final log is inconsistent with the information you provided before: it seems that vcpkg is stuck when preparing to build `libogg[core]:x64-windows`.

Please make sure that the anti-virus is turned off, and check whether the vcpkg process has exited through the task manager and whether the process has cpu/disk operations.

Thanks.

**Comment by dweckmann** [comment]
Hi @JackBoosY,

I've tested again, with antivirus fully deactivated and not only with directory "excluded", and I the problem seems to be gone. 

Thanks for your help !

**Comment by dweckmann** [comment]
Since the issue seems to be resolved, I close it :)
