### ISSUE TITLE
OPTIONS in vcpkg_configure_cmake can not override variables in CMakeLists.txt

### ISSUE THREAD

**Issue by playgithub** [microsoft/vcpkg#15157]
The line `OPTIONS -DCMAKE_CXX_STANDARD=${CXX_STANDARD}` take effect only if `0005-remove-CMAKE_CXX_STANDARD.patch` (i.e. remove `set(CMAKE_CXX_STANDARD 14)` in the original `CMakeLists.txt`) is applied.
Why can't it override the variables defined in `CMakeLists.txt`?

ports/poppler/portfile.cmake

```cmake
vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO freedesktop/poppler
    REF poppler-20.12.1
    SHA512 f692682689c0b0fcc3953a1cc157b6e1d2ce3ccab185189d6dc0807f1dd3ea2d1a9773d0b805079a30b3c8a3b0cf3ee83239ed48d7b08dc7762eba29c2033674
    HEAD_REF master
    PATCHES
        0001-remove-tests.patch
        0002-remove-utils.patch
        0003-remove-glib-and-GObject-introspection.patch
        0004-remove-Qt5-and-Qt6-support.patch
        0005-remove-CMAKE_CXX_STANDARD.patch
)

if("cpp17" IN_LIST FEATURES)
    set(CXX_STANDARD 17)
else()
    set(CXX_STANDARD 14)
endif()

message(${CXX_STANDARD})

vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA # Disable this option if project cannot be built with Ninja
    OPTIONS -DCMAKE_CXX_STANDARD=${CXX_STANDARD}
    #OPTIONS -DCMAKE_CXX_STANDARD=${CXX_STANDARD}
    # OPTIONS -DUSE_THIS_IN_ALL_BUILDS=1 -DUSE_THIS_TOO=2
    # OPTIONS_RELEASE -DOPTIMIZE=1
    # OPTIONS_DEBUG -DDEBUGGABLE=1
)

vcpkg_install_cmake()

file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")

file(INSTALL ${SOURCE_PATH}/COPYING DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)
```

---

BTW, for the sample code at https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_check_features.md
```
# ports/mimalloc/portfile.cmake
vcpkg_check_features(OUT_FEATURE_OPTIONS FEATURE_OPTIONS
  # Keyword FEATURES is optional if INVERTED_FEATURES are not used
    asm       MI_SEE_ASM
    override  MI_OVERRIDE
    secure    MI_SECURE
)

vcpkg_configure_cmake(
  SOURCE_PATH ${SOURCE_PATH}
  PREFER_NINJA
  OPTIONS
    # Expands to "-DMI_SEE_ASM=ON; -DMI_OVERRIDE=OFF; -DMI_SECURE=ON"
    ${FEATURE_OPTIONS}
)
```
It seems that `OPTIONS` can override the variables defined in `CMakeLists.txt`

**Comment by vicroms** [comment]
Hi @playgithub 

The `OPTIONS` parameter in `vcpkg_configure_cmake` can override options but not variables. If a variable it's not set, it is possible to set it with `OPTIONS`; but if the `CMakeLists.txt` declares the variable, it won't be overridden.

* Options are declared using `option(<option_name> "description" <value>)` 
* Variables are declared using `set(<variable_name> <value>)`

You can read more here: https://cmake.org/cmake/help/latest/command/option.html

In the case of `CXX_STANDARD`, I think the best thing to do would be to create a patch that removes the hard-coded `set(CXX_STANDARD 14)` and instead let users control the standard using a toolchain file or a custom triplet.

**Comment by playgithub** [comment]
> let users control the standard using a toolchain file or a custom triplet

Use a triplet to control C++ standard is nice, has it been implemented?
