### ISSUE TITLE
[tbb] update to 2021.1.1, use new CMake build system

### ISSUE THREAD

**Issue by longnguyen2004** [microsoft/vcpkg#15152]
Library name: tbb

New version number: 2021.1.1

Other information that may be useful (release notes, etc...)
TBB 2021 comes with a new CMake build system, which can eliminate many of the work we have to do, and instead just use `vcpkg_install_cmake`. This will also make it easier for me to add support for llvm-mingw in the future.

**Comment by JonLiu1993** [comment]
Fix by #16321

**Comment by PhoebeHui** [comment]
Closing in favor of https://github.com/microsoft/vcpkg/issues/18074.
