### ISSUE TITLE
[qt5] qsqlmysql is missing

### ISSUE THREAD

**Issue by jepessen** [microsoft/vcpkg#15160]
I build the qt5 package correctly but when I go to installed/plugins/sqldrivers the qsqlmysql.dll library is missing. What should I do in order to build it?

**Comment by Neumann-A** [comment]
currently qt5 only has libpq as a dependency. It has to be changed to also use mysql and build the mysql driver

**Comment by Neumann-A** [comment]
@Adela0814  @Cheney-W close? https://github.com/microsoft/vcpkg/pull/15170 was merged a long time ago
