### ISSUE TITLE
[boost-regex] Ubuntu-Android armv7 build failure -the x86 boost-build tools must be installed to build for non-x86/x64

### ISSUE THREAD

**Issue by DiegoAvila123** [microsoft/vcpkg#15165]
**Host Environment**
- OS: Linux (Ubuntu 18.04)
- Compiler: GIT HEAD : 595777db2332a3442b73f9af9f656355f207aec9

**To Reproduce**
`cd $VCPKG_ROOT

echo "
set(VCPKG_TARGET_ARCHITECTURE arm)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_CMAKE_SYSTEM_NAME Android)
" > triplets/community/arm-android.cmake
`./vcpkg install boost:x64-linux`
`./vcpkg install boost:arm-android`

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.
-- Using community triplet arm-android. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: /home/diego/Repos/vcpkg/triplets/community/arm-android.cmake
-- Using cached /home/diego/Repos/vcpkg/downloads/boostorg-regex-boost-1.74.0.tar.gz
-- Cleaning sources at /home/diego/Repos/vcpkg/buildtrees/boost-regex/src/ost-1.74.0-ccd5cfd86e.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/diego/Repos/vcpkg/downloads/boostorg-regex-boost-1.74.0.tar.gz
-- Using source at /home/diego/Repos/vcpkg/buildtrees/boost-regex/src/ost-1.74.0-ccd5cfd86e.clean
-- Including /home/diego/Repos/vcpkg/ports/boost-regex/b2-options.cmake
CMake Error at installed/arm-android/share/boost-build/boost-modular-build.cmake:47 (message):
  The x86 boost-build tools must be installed to build for non-x86/x64
  platforms.  Please run `vcpkg install boost-build:x86-windows`.
Call Stack (most recent call first):
  ports/boost-regex/portfile.cmake:12 (boost_modular_build)
  scripts/ports.cmake:136 (include)

Error: Building package boost-regex:arm-android failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-regex:arm-android
  Vcpkg version: 2020.11.12-unknownhash

**Additional context**
I modify the installed/arm-android/share/boost-build/boost-modular-build.cmake file  by adding 
`elseif(VCPKG_CMAKE_SYSTEM_NAME STREQUAL "Android" AND VCPKG_TARGET_ARCHITECTURE STREQUAL "arm")
        set(BOOST_BUILD_PATH "${CURRENT_INSTALLED_DIR}/../arm-android/tools/boost-build")`
also i tried
`elseif(VCPKG_CMAKE_SYSTEM_NAME STREQUAL "Android" AND VCPKG_TARGET_ARCHITECTURE STREQUAL "arm")
        set(BOOST_BUILD_PATH "${CURRENT_INSTALLED_DIR}/../x64-linux/tools/boost-build")`
but i got those errors in both cases:
`...failed gcc.link.dll /home/diego/Repos/vcpkg/buildtrees/boost-regex/arm-android-dbg/boost/build/63f7c0b17978503420f3177974debf04/libboost_regex.so.1.74.0...
...skipped <p/home/diego/Repos/vcpkg/buildtrees/boost-regex/arm-android-dbg/stage/lib>libboost_regex.so.1.74.0 for lack of <p/home/diego/Repos/vcpkg/buildtrees/boost-regex/arm-android-dbg/boost/build/63f7c0b179$
...skipped <p/home/diego/Repos/vcpkg/buildtrees/boost-regex/arm-android-dbg/stage/lib>libboost_regex.so.1 for lack of <p/home/diego/Repos/vcpkg/buildtrees/boost-regex/arm-android-dbg/stage/lib>libboost_regex.so$
...failed updating 1 target...`

**Comment by PhoebeHui** [comment]
@DiegoAvila123, this is not usual scenario we're working on now, but we accept PRs for fixing this issue. Sorry for that.

**Comment by fabinshen** [comment]
Hit the same issue.

**Comment by PhoebeHui** [comment]
@DiegoAvila123,  this issue should be fixed now, could you try vcpkg latest source and see if it still be a problem for you?

**Comment by Cheney-W** [comment]
This issue has not been updated for over 3 months, so if it is still an issue, please reopen the issue.
