### ISSUE TITLE
[boost-stacktrace] build failure when building dependencies from vcpkg manifest in arm64-windows triplet

### ISSUE THREAD

**Issue by soumyamahunt** [microsoft/vcpkg#15166]
**Host Environment**
- OS: Windows
- Compiler: revision

**To Reproduce**
1. Create a C++ console application in visual studio and enable "Use vcpkg manifest" for the project.
2. Specify `boost-stacktrace` as one of the dependencies in vcpkg manifest file.
3. Switch build configuration to "ARM64" platform and try building the project in visual studio.

**Failure logs** 
```
CMake Error at installed/arm64-windows/share/boost-build/boost-modular-build.cmake:47 (message):
  The x86 boost-build tools must be installed to build for non-x86/x64
  platforms.  Please run `vcpkg install boost-build:x86-windows`.
Call Stack (most recent call first):
  ports/boost-stacktrace/portfile.cmake:12 (boost_modular_build)
  scripts/ports.cmake:136 (include)
```

**Additional context**
As the error message specifies `boost-build:x86-windows` is required to build `boost-stacktrace:arm64-windows`. Disabling "Use vcpkg manifest" and then after that manually installing `boost-build:x86-windows` and then `boost-stacktrace:arm64-windows` works fine. But enabling "Use vcpkg manifest" always results in build failure for ARM64.

**Comment by DiegoAvila123** [comment]
Got the same error on linux building arm architecture , one quick fix is modifying the installed/arm64-windows/share/boost-build/boost-modular-build.cmake file to set the correct boost path

**Comment by PhoebeHui** [comment]
@soumyamahunt, thanks for reporting this issue, please try the workround that @DiegoAvila123 provided.

It's a similar issue with https://github.com/microsoft/vcpkg/issues/15087. I will use that issue to track.

**Comment by soumyamahunt** [comment]
@PhoebeHui I tried building with latest vcpkg commit and build for `arm64-windows` triplet now succeeds but for `arm-windows` triplet it fails. May be whatever work done to pass the build for` arm64-windows` triplet could be done for `arm-windows` triplet too.
