### ISSUE TITLE
[New Port Request] Microsoft glTF-SDK

### ISSUE THREAD

**Issue by neil3d** [microsoft/vcpkg#15174]
Library name: Microsoft glTF-SDK

Library description:  glTF-SDK is a C++ Software Development Kit for glTF (GL Transmission Format -https://github.com/KhronosGroup/glTF).

Source repository URL:https://github.com/microsoft/glTF-SDK

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
- A C++ Deserializer/Serializer for glTF
- glTF & glB support, including embedded Base64 support

**Comment by luncliff** [comment]
Hi @neil3d, The #14971 did this work recently. Would you check the port works for you? WIll be glad to hear from you :)

**Comment by PhoebeHui** [comment]
Thanks luncliff for making this possible!
