### ISSUE TITLE
Workflow using vcpkg projects... do I just need to know to add windows .lib files to my linker inputs?

### ISSUE THREAD

**Issue by aggieNick02** [microsoft/vcpkg#15184]
Using vcpkg has been a breath of fresh air, making adding a new dependency so much less painful than before. :)

Sometimes though I'll end up with unresolved external symbols and need to add certain windows .lib files to my linker inputs to get things to compile.

For example, I made a dummy project using grpc:x64-windows-static. Everything compiles, but when linking, I get a ton of unresolved external symbols in grpc.lib, libcrypto.lib, address_sorting.lib, cares.lib (e.g. __imp_CertOpenStore) . To resolve them I have to add ws2_32.lib and crypt32.lib to the linker inputs.

Is this just expected? Vcpkg handles so much that I was surprised when I hit this.

**Comment by JackBoosY** [comment]
For cmake projects, they are not needed because the exported cmake configuration files will set the dependent Windows libraries into itself.
For MSVC projects, vcpkg does not currently support this feature, I think we should support it in the future.

**Comment by aggieNick02** [comment]
Thanks for the info. Just curious how I could look at dependencies and cmake files to figure this out in the visual studio case? For the errors I got, googling was enough to find the libraries I needed to link, but I'm wondering how I'd figure it out otherwise.

I just started grep-ing trying to understand a bit more, and found the ws2_32.lib setting in winsock2\portfile.cmake . Is that what I'm looking for? It's the only cmake file that does that, but winsock2 is not a dependency of grpc, so I'm a little confused.

**Comment by JackBoosY** [comment]
For cmake configuration files, you can check the folder _VCPKG_ROOT/installed/TRIPLET/share/PORT_NAME_.
Some of the ports are not support to exported them(such as winsock2), so you have two choice:
1. Use the cmake provided `Find*.cmake` if cmake provided it. See [Documentation](https://cmake.org/cmake/help/latest/command/find_package.html#id2).
2. Manually implement `find_path` and `find_library`.

All ports have a separate `portfile.cmake`, but this does not mean that they are all built by cmake. Some ports need to use makefile, some use jom, etc.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

**Comment by aggieNick02** [comment]
Thanks for the help with this. I still don't understand 100% but that is due to my slowly learning more details about how the different make systems work, etc. The answers were very helpful in progressing my learning.
