### ISSUE TITLE
Where to find the candidate values for VCPKG_CXX_FLAGS & VCPKG_C_FLAGS?

### ISSUE THREAD

**Issue by playgithub** [microsoft/vcpkg#15189]

**Comment by JackBoosY** [comment]
See [documentation](https://github.com/microsoft/vcpkg/blob/9a81392e48e88ac4789107b100b93504d4ac713c/docs/users/triplets.md#vcpkg_cxx_flags).

**Comment by playgithub** [comment]
> See [documentation](https://github.com/microsoft/vcpkg/blob/9a81392e48e88ac4789107b100b93504d4ac713c/docs/users/triplets.md#vcpkg_cxx_flags).
e.g. for C++17, it should be
`set(VCPKG_CXX_FLAGS "-std=c++17")`
but in Visual Studio, the command line option is `/std:c++17`
I have read the doc, but not find the candidate values.

**Comment by JackBoosY** [comment]
Oh, this way of writing is not created by vcpkg, we use cmake's way of writing flags. See [CXXFLAGS](https://cmake.org/cmake/help/latest/envvar/CXXFLAGS.html).

**Comment by playgithub** [comment]
That's ok, thanks.

**Comment by playgithub** [comment]
@JackBoosY
After some tests, I think the flags are native flags.
So for msvc it should be `/std:c++17` & `std:c17`, for gcc it should be `-std-c++17` and `-std=c++17` and -std=c17, right?

**Comment by JackBoosY** [comment]
@playgithub Completely right!
