### ISSUE TITLE
How do I add my own library to vcpkg

### ISSUE THREAD

**Issue by Spidy104** [microsoft/vcpkg#15198]
I went upon the whole documentation of vcpkg but could not find anything proper about how to to submit our own library to vcpkg, So can anyone help me out so as to how to contribute to vcpkg?

**Comment by vicroms** [comment]
Hi @Spidy104 

Thanks for the interest in contributing to vcpkg! 

Here's an example of how to [package a library from a GitHub repo](https://github.com/microsoft/vcpkg/blob/master/docs/examples/packaging-github-repos.md).
If you want to publish your port, just open a PR to our repository and we'll review it and merge it. 

If you need any help with the porting process you can contact us through Slack or Discord (links are in our [`README.md`](https://github.com/microsoft/vcpkg).

**Comment by Spidy104** [comment]
Thanks for the helping me out @vicroms.

**Comment by JonLiu1993** [comment]
@Spidy104 ,Thanks for posting this issue,It seems that vector has solved your problem. I will close this issue. If you still have problems, you can reopen this issue. Thank you
