### ISSUE TITLE
Will Visual Studio vcpkg plugin try to find the most proper binaries when multiple triplets exists?

### ISSUE THREAD

**Issue by playgithub** [microsoft/vcpkg#15190]
e.g.

x64-Windows.cmake
```
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
```

x64-Windows-cpp17.cmake
```
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_CXX_FLAGS "/std:c++17")
set(VCPKG_C_FLAGS  "/std:c17")
```

`vcpkg install somelib:x64-Windows`

Here when build an application in C++17, it'll use the lib in C++14 (default).

`vcpkg install somelib:x64-Windows-cpp17`

Here when build an application in C++17, will it use the lib in C++17.

**Comment by NancyLi1013** [comment]
@BillyONeal 

Could you please help answer this question? I'm not clear about this point.

Thanks.

**Comment by playgithub** [comment]
In Visual Studio vcpkg plugin settings, there is an option called "Triplet". It works.
