### ISSUE TITLE
How do I install mlir library?

### ISSUE THREAD

**Issue by lovely-error** [microsoft/vcpkg#15199]
Hello. I have installed the vcpkg and searched for a package called mlir. I have found one, but the installation fails with error `Error: while loading port `mlir`: Port definition not found
`. A quick search on google suggested that it might be a bug in the pm itself. Is it correct, or am I missing something? Thanks in advance <3

**Comment by StarGate-One** [comment]
To find if there is an mlir port in vcpkg:
>->vcpkg search mlir
>llvm[mlir]                            Build Multi-Level IR Compiler Framework.

Appears mlir does not exist as a stand alone port in vcpkg, but is a feature of port llvm
>->vcpkg install llvm[mlir] 
>Computing installation plan...
>The following packages will be built and installed:
    llvm[clang,core,default-targets,disable-abi-breaking-checks,disable-assertions,disable-clang-static-analyzer,enable-rtti,lld,**mlir**,target-x86,tools]:x64-windows -> 11.0.0

If this is not the `mlir` referenced in original post, then one may complete an issue request to have the port added https://github.com/microsoft/vcpkg/issues/new?assignees=&labels=new+port+request+-+consider+making+a+PR%21&template=request-a-new-port.md&title=%5BNew+Port+Request%5D+%3Clibrary+name+here%3E ?

**Comment by lovely-error** [comment]
Yeah, the first thing I tried is bold `vcpkg search + vcpkg install`, and indeed the desired package has been found, but my installation diverges from your example right here ...

> vcpkg install llvm[mlir]
> Computing installation plan...
> The following packages will be built and installed:
> llvm[clang,core,default-targets,disable-abi-breaking-checks,disable-assertions,disable-clang-static-analyzer,enable-> rtti,lld,mlir,target-x86,tools]:x64-windows -> 11.0.0

The only thing I see is `zsh: no matches found: llvm[mlir]`. I am on osx 10.15.6(Catalina).
Hope this brings more context.

**Comment by lovely-error** [comment]
Oh, nevermind. This one explains a lot!
https://github.com/microsoft/vcpkg/issues/9000
