### ISSUE TITLE
[libpq:x64-windows] build failure

### ISSUE THREAD

**Issue by flow-specter** [microsoft/vcpkg#15193]
**Host Environment**
- OS: Windows
- Compiler: 19.27.29111

**To Reproduce**
`.\vcpkg.exe install libpq:x64-windows`

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.
![image](https://user-images.githubusercontent.com/29993289/102584975-74e8e880-4142-11eb-8145-edb60b0928a4.png)

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

       “E:\vcpkg\buildtrees\libpq\x64-windows-rel\libpq.vcxproj”(默认目标) (1) ->
       (Link 目标) -> 
         fe-auth.obj : error LNK2019: unresolved external symbol __imp_GetUserNameA referenced in function pg_fe_getauthname [E:\vcpkg\buildtrees\libpq\x64-windows-rel\libpq.vcxproj]
         fe-connect.obj : error LNK2019: unresolved external symbol __imp_SHGetFolderPathA referenced in function pqGetHomeDirectory [E:\vcpkg\buildtrees\libpq\x64-windows-rel\libpq.vcxproj]
         libpgport.lib(pg_strong_random.obj) : error LNK2019: unresolved external symbol __imp_CryptAcquireContextA referenced in function pg_strong_random [E:\vcpkg\buildtrees\libpq\x64-windows-rel\libpq.vcxproj]
         libpgport.lib(pg_strong_random.obj) : error LNK2019: unresolved external symbol __imp_CryptGenRandom referenced in function pg_strong_random [E:\vcpkg\buildtrees\libpq\x64-windows-rel\libpq.vcxproj]
         .\Release\libpq\libpq.dll : fatal error LNK1120: 4 unresolved externals [E:\vcpkg\buildtrees\libpq\x64-windows-rel\libpq.vcxproj]

    0 个警告
    5 个错误

**Comment by JonLiu1993** [comment]
@flow-specter ,Thanks for posting this issue,I cannot reproduce this on my machine.Can you update vcpkg and try again? If it fails, please send your complete error log. Thank you

**Comment by PhoebeHui** [comment]
Please reopen this issue if it still be a problem for you.
