### ISSUE TITLE
Qt5 Windows Static - Fail

### ISSUE THREAD

**Issue by Voskrese** [Microsoft/vcpkg#1520]
Сам еще не проверял, использую внешнюю сборку, процесс сборки Qt очень долгий )) ошибка появилась недавно, возможно из за изменений

> Sam has not yet tested the build Qt very long)) error appeared recently, possibly because of changes

https://github.com/Microsoft/vcpkg/commit/9467c1bd81c655b060aa9df5aeb0047b87e93058#diff-261ad181c16e17acae7baf8fb2b321d9

здесь описывается что JOM падает при многопоточности, надо выставить либо один процесс либо использовать NMAKE
возможно так же, что обновление JOM повлияло, как на счет Ninja?

> Describes that JOM falls when multithreading, you must set either one process or use NMAKE

https://github.com/Kitware/fletch/blob/e6a31469326985c92d3c8f64b459f37216076885/CMake/External_Qt.cmake#L95

если кто то попробует, отпишитесь, работает ли такая схема на static

> If someone tries to post whether this scheme on static

**Comment by sdcb** [comment]
Is this duplicated by: https://github.com/Microsoft/vcpkg/issues/513

**Comment by Voskrese** [comment]
@sdcb ???

 https://github.com/Kitware/fletch/blob/e6a31469326985c92d3c8f64b459f37216076885/CMake/External_Qt.cmake#L95

>  # Qt has a race condition (https://bugreports.qt.io/browse/QTBUG-28132) where
>   # multi-thread builds can intermittantly fail.  Essentially during the install
>   # step different targets will check if a directory exists and call MD when it doesn't.
>   # On windows if the race is a tie and two threads see that the directory doesn't exist,
>   # the second thread will error out because MD fails if the directory exists.  A
> # Work around is to turn off multi threaded builds for install:

**Comment by Voskrese** [comment]
видимо проблема решена) закрываю
