### ISSUE TITLE
Problem with bitdefender and vcpkg (access to vcpkg.exe denied)

### ISSUE THREAD

**Issue by daef** [Microsoft/vcpkg#1521]
I had troubles compiling vcpkg on a co-workers machine:
The linker said it had no access to toolsrc\Release\vcpkg.exe

After half an hour of headbanging we found that his bitdefender supposedly found "gen.variant.razy.206573" in the binary and locked access to the *PATH* toolsrc\Release\vcpkg.exe from there on. (We couldn't manually create a file with that name in that place, even after completely deleting the Release subfolder) When we renamed the Release folder to Release_something we could touch vcpkg.exe again - but as soon as the directory was named back (or recreated via bootstrap) all access to vcpkg.exe was denied again.

bitdefender never showed any indications that it tried to help (which was not very helpful). Adding the whole vcpkg folder to it's exclusion list + reboot helped thou.

Leaving this info here just in case others experience the same problem.

**Comment by daef** [comment]
Also see virustotal - I just uploaded my local build: https://www.virustotal.com/en/file/7d756f7c343e5ff2a90c631a5984c805e35a2913f2228fd9604d163db1217f17/analysis/1500964387/

**Comment by ras0219-msft** [comment]
Is it possible that your co-worker's machine is compromised? Malware could easily intercept the compilation step and inject its own payload into the binary as it's written out.

Obviously, we don't intend for any malware to be in the binary -- you can see the entire source code inside the `toolsrc\` directory.

Could you upload the successfully compiled vcpkg from your machine (instead of your co-worker's)?

**Comment by Mixaill** [comment]
0/62 from my machine https://www.virustotal.com/en/file/c7dd5df965510d299628e367bd17276605c4e6f61f84b29c9d9df5505ac15d23/analysis/1501005250/

You can be really compromised.

**Comment by daef** [comment]
Sorry for the delay, I completely forgot about this issue.

> Could you upload the successfully compiled vcpkg from your machine (instead of your co-worker's)?
>
That's what I did with virustotal the day after the first finding. That's where the 9/63 came from.

Now I just deleted my vcpkg.exe and re-ran bootstrap-vcpkg.bat: [0/63] (https://www.virustotal.com/en/file/5ac504bb2bd0a54fa69680050ba572514d76567ef9a07a06fe77b68beaf9e605/analysis/1502091258/)

Bitdefenders homepage doesn't seem to tell me anything about `gen.variant.razy.206573`.
I think this was just a messed up heuristic going false positive, but how should I really know?

**Comment by ras0219-msft** [comment]
I'm not sure, however you might try contacting your antivirus provider (Bitdefender?).

Since this isn't a vcpkg issue, I'll close this.

**Comment by daef** [comment]
I don't use antivirus software - and my colleague that uses bitdefender already contacted them. Sorry for the disruption :)

**Comment by ThrashAbaddon** [comment]
@daef What did the BitDefender say? I have the same problem.

**Comment by daef** [comment]
@medvedeg did you get a response from BitDefender?

**Comment by Hendiadyoin1** [comment]
I have/had the same problem, for the most part it helps to add the whole vcpkg foder to the ignored list for all actions, but Bitdefender still slips through sometimes
