### ISSUE TITLE
vcpkg toolchain file prevents CMake from finding non-vcpkg packages

### ISSUE THREAD

**Issue by gvcallen** [microsoft/vcpkg#15218]
**Describe the bug**
I have a clean vcpkg installation, and have pointed CMake to it using CMAKE_TOOLCHAIN_FILE. I have wxWidgets installed externally, independently of vcpkg (I could never get vcpkg and wxWidgets to work, but nevertheless this issue is not wxWidgets-specific I believe). Without including CMAKE_TOOLCHAIN_FILE, my program builds perfectly, however when pointing CMake to vcpkg, I get the following error and wxWidgets cannot be found. I believe this is undesired behaviour - one should not HAVE to use vcpkg - you should be able to call find_package() on vcpkg and non-vcpkg CMake packages.

**Environment**
- OS: Windows 10
- Compiler: msvc 2019

**To Reproduce**
1. Install wxWidgets independently of CMake and test it in a CMake project
2. Install vcpkg from scratch and add it to a CMake project using CMAKE_TOOLCHAIN_FILE
3. Notice that when adding CMAKE_TOOLCHAIN_FILE, there is an error

**Failure logs** 
[cmake] CMake Error at C:/Program Files/CMake/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
[cmake]   Could NOT find wxWidgets (missing: core base)
[cmake] Call Stack (most recent call first):
[cmake]   C:/Program Files/CMake/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
[cmake]   C:/Program Files/CMake/share/cmake-3.18/Modules/FindwxWidgets.cmake:1083 (find_package_handle_standard_args)
[cmake]   F:/Resources/Programming/DevTools/vcpkg/scripts/buildsystems/vcpkg.cmake:625 (_find_package)
[cmake]   wxWidgets-Sandbox/CMakeLists.txt:4 (find_package)

**Comment by JackBoosY** [comment]
We do not recommend using packages that are outside of vcpkg and are included by vcpkg, because this will affect the dependencies between ports.
If the packages you want to use are not included in vcpkg, there are two ways to find them:
1. Add the cmake configure file path to `CMAKE_PREFIX_PATH`.
2. Set the cmake configure file path to `${PACKAGE_NAME}_dir`.

**Comment by gvcallen** [comment]
@JackBoosY oh okay, that is very unfortunate. I am looking to use vcpkg as a full solution but unfortunately I have had troubles setting it up with both wxWidgets and several other libraries, and after posting my issue on GitHub for some they were still unresolved. So if any future packages do not work in vcpkg for me, I will be unable to use them completely.

It would nice to then be able to "disable" a package completely in vcpkg i.e. prevent vcpkg from providing any data on that package, so that if a package does not work for a user, they can still install it themselves and continue to use vcpkg for other libraries.

Hope that makes sense

**Comment by JackBoosY** [comment]
@gvcallen In fact, you can use the vcpkg `export` function to export the installed port files and use them in custom projects.

**Comment by gvcallen** [comment]
@JackBoosY to my knowledge, the export command still requires you to provide CMake with a toolchain file. My optimal workflow for the export command would be for a folder to be created that I could simply place inside my CMAKE_PREFIX_PATH folder, and have the library "installed" on global level, thereafter forgetting about it.

**Comment by JackBoosY** [comment]
@gvcallen We can use the exported file through the vcpkg toolchain, but it is not necessary. You can directly use the files in _EXPOTE_PATH/installed/TRIPLET_.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
