### ISSUE TITLE
[protobuf and grpc] The installation location of protoc.exe, grpc_cpp_plugin.exe, etc. is not correct

### ISSUE THREAD

**Issue by sighingnow** [microsoft/vcpkg#15217]
****

**Is your feature request related to a problem? Please describe.**

I have noticed that the `protoc`, as well as `grpc_cpp_plugin` are installed into `$ROOT/tools/{protobuf/grpc}`, rather than `$ROOT/bin`. If I understand it correctly the program `protoc` has assumption about the relative path of `protoc.exe` and `include/google/protobuf/...`, otherwise if user's protobuf includes those proto files, e.g., `google/protobuf/any.proto`, the code generation would fail.

**Proposed solution**

Install those binaries to `$ROOT/bin`.

**Describe alternatives you've considered**

Currently we have to copy those binaries to `bin/` directory to make everything work as expected.

**Comment by JackBoosY** [comment]
In vcpkg, according to our policy, tools should be installed in _VCPKG_ROOT/installed/TRIPLET/tools_, and only dynamic libraries and pdbs should be placed in the folder _bin_.

> otherwise if user's protobuf includes those proto files, e.g., google/protobuf/any.proto, the code generation would fail.

If this issue exists, then we should use other methods to fix it.

**Comment by sighingnow** [comment]
For more information about the issue, please see the logic of adding default path in protobuf:

https://github.com/protocolbuffers/protobuf/blob/64dd751868d633421563e53e68da831a0a02c923/src/google/protobuf/compiler/command_line_interface.cc#L234-L273

**Comment by JackBoosY** [comment]
It will be resolved tomorrow.
