### ISSUE TITLE
Why does boost 1.64-5 not create libboost-filesystem-XXXXX.lib?

### ISSUE THREAD

**Issue by juandent** [Microsoft/vcpkg#1522]
Hi,
I am happy to use vcpkg.exe but find someting strange in using boost. I am wondering why some libraries only appear as boost_xxxxx.lib while a few also defined libboost_xxxxx.lib.

In particular, one lib that is not compiled with the lib prefix is filesystem-xxxxx.lib. Why is this? If I compile the filesystem library using the b2 program, the libfilesystem-xxx.lib gets constructed.

Is there a way to force creation of libboost_filesystem-vc141-mt-1_64.lib?

Thanks!
Juan

**Comment by atkawa7** [comment]
see  #1338

**Comment by Voskrese** [comment]
?
`cd ..vcpkg\installed\x64-windows-static\lib`
`mklink boost_filesystem-vc141-mt-1_64.lib libboost_filesystem-vc141-mt-1_64.lib `

**Comment by juandent** [comment]
Got it! I had not built using 

`vcpkg install boost:x86-windows-static`

Thanks,
Juan
