### ISSUE TITLE
[Port feature] <LLVM 11.0>

### ISSUE THREAD

**Issue by Dorbmon** [microsoft/vcpkg#15228]
Library name: LLVM 11.0

Library description: LLVM set.

Source repository URL:https://github.com/llvm/llvm-project/releases/tag/llvmorg-11.0.0

Project homepage (if different from the source repository):https://llvm.org/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):When on windows,the official package of llvm 11.0 lacks some files.So I think a full version of LLVM should be built.

**Comment by yurybura** [comment]
Dear @Dorbmon,
Please tell which files were lost. I can add them.
Thank you.

**Comment by Dorbmon** [comment]
> Dear @Dorbmon,
> Please tell which files were lost. I can add them.
> Thank you.

The version in vcpkg of llvm lacks plenty of LIBS and headfiles.You can try to compare it to other systems' precompiled package.

According my poor language I can't describe it very well.

**Comment by yurybura** [comment]
Dear @Dorbmon,
I can add new libs by request. Let me check all libs later.
Thank you.
