### ISSUE TITLE
[libiconv] build failure

### ISSUE THREAD

**Issue by jadczak** [microsoft/vcpkg#15226]
**Host Environment**
- OS: Windows
- Compiler: Visual Studio 2015, Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24210

**To Reproduce**
`./vcpkg install libiconv:x64-windows`

**Failure logs** 

> Starting package 1/9: libiconv:x64-windows
> Building package libiconv[core]:x64-windows...
> -- Using cached C:/Users/XXXXXXX/source/vcpkg/downloads/libiconv-1.16.tar.gz
> -- Cleaning sources at C:/Users/XXXXXXX/source/vcpkg/buildtrees/libiconv/src/1.16-de9101a181.clean. Use --editable to skip cleaning for the packages you specify.
> -- Extracting source C:/Users/XXXXXXX/source/vcpkg/downloads/libiconv-1.16.tar.gz
> -- Applying patch 0002-Config-for-MSVC.patch
> -- Applying patch 0003-Add-export.patch
> -- Using source at C:/Users/XXXXXXX/source/vcpkg/buildtrees/libiconv/src/1.16-de9101a181.clean
> -- Configuring x64-windows
> -- Using msys root at C:/Users/XXXXXXX/source/vcpkg/downloads/tools/msys2/827af5fc5a9ac05f
> -- Using msys root at C:/Users/XXXXXXX/source/vcpkg/downloads/tools/msys2/c809757c94447846
> -- Configuring x64-windows-dbg
> CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:108 (message):
>     Command failed: C:/Users/XXXXXXX/source/vcpkg/downloads/tools/msys2/827af5fc5a9ac05f/usr/bin/bash.exe --noprofile --norc --debug -c "V=1 CPP='compile cl.exe -E' CC='compile cl.exe' CC_FOR_BUILD='compile cl.exe' CXX='compile cl.exe' RC='windres-rc rc.exe' WINDRES='windres-rc rc.exe' AR='ar-lib lib.exe' LD='link.exe -verbose' RANLIB=':' STRIP=':' NM='dumpbin.exe -symbols -headers' DLLTOOL='link.exe -verbose -dll' CCAS=':' AS=':' ./../src/1.16-de9101a181.clean/configure --build=x86_64-pc-mingw32 --enable-relocatable --enable-extra-encodings --without-libiconv-prefix --without-libintl-prefix ac_cv_prog_ac_ct_STRIP=: gl_cv_double_slash_root=yes ac_cv_func_memmove=yes --disable-silent-rules --verbose --enable-shared --disable-static --prefix=/C/Users/XXXXXXX/source/vcpkg/installed/x64-windows/debug --bindir='${prefix}'/../tools/libiconv/debug/bin --sbindir='${prefix}'/../tools/libiconv/debug/sbin --includedir='${prefix}'/../include --datarootdir='${prefix}'/share/libiconv"
>     Working Directory: C:/Users/XXXXXXX/source/vcpkg/buildtrees/libiconv/x64-windows-dbg
>     Error code: 1
>     See logs for more information:
>       C:\Users\XXXXXXX\source\vcpkg\buildtrees\libiconv\config-x64-windows-dbg-out.log
>       C:\Users\XXXXXXX\source\vcpkg\buildtrees\libiconv\config-x64-windows-dbg-err.log
> 
> Call Stack (most recent call first):
>   scripts/cmake/vcpkg_configure_make.cmake:679 (vcpkg_execute_required_process)
>   ports/libiconv/portfile.cmake:24 (vcpkg_configure_make)
>   scripts/ports.cmake:136 (include)
> 
> 
> Error: Building package libiconv:x64-windows failed with: BUILD_FAILED
> Please ensure you're using the latest portfiles with `.\vcpkg update`, then
> submit an issue at https://github.com/Microsoft/vcpkg/issues including:
>   Package: libiconv:x64-windows
>   Vcpkg version: 2020.11.12-nohash
> 
> Additionally, attach any relevant sections from the log files above.

[config-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/5721689/config-x64-windows-dbg-err.log)
[config-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/5721690/config-x64-windows-dbg-out.log)

**Additional context**
Experienced the issue when trying to install tesseract
`./vcpkg install tesseract:x64-windows`

confirmed issue by running `./vcpkg install libiconv:x64-windows` outside of the tesseract install.
`./vcpkg install libiconv` installs the x86 version without issue.

**Comment by JackBoosY** [comment]
Hi @jadczak, thanks for reporting this issue!
Please update Visual Studio to 2017 and try again.

Thanks.

**Comment by jadczak** [comment]
installing VS fixed the issue.
