### ISSUE TITLE
[graphicsmagick] No `delegates.mgk` file generated

### ISSUE THREAD

**Issue by ghassanpl** [microsoft/vcpkg#15239]
**Describe the bug**
Apparently the latest version of GM requires the use of a `modules.mgk` file (apparently among other files, like image format modules?), which is not accessible or even installed by the build.

**Environment**
- OS: Windows 10
- Compiler: VS2019 latest preview

**To Reproduce**
1. ./vcpkg install graphicsmagick
2. Try to read a file using the gm API
3. GM exception is thrown: reason: `Unable to access configuration file`, description: `delegates.mgk`

I basically use this code:
```c++
InitializeMagick(argv[0]);
ExceptionInfo exception{};
GetExceptionInfo(&exception);
auto ii = CloneImageInfo(nullptr);
strcpy_s(ii->filename, path.string().c_str());
auto psd_file = ReadImage(ii, &exception);
if (!psd_file)
	...
```

**Expected behavior**
Ability to open and read data from all GM-accessible formats.

**Comment by NancyLi1013** [comment]
Hi @ghassanpl 

Thanks for posting this issue.

I submitted a PR to add delegates.mgk. 
Could you please help test if this can work fine for you?
