### ISSUE TITLE
exiv2 lib & MSVC 2019 

### ISSUE THREAD

**Issue by tester0077** [microsoft/vcpkg#15241]
**Describe the bug**
trying to link exiv2lib statically 

**Environment**
- OS: Windows 10 64-bit
- Compiler: MSVC 2019 community edition, current update
- installed exiv2:x64-windows-static-md                        0.27.3#3         Image metadata library and tools
                exiv2:x86-windows-static-md                        0.27.3#3         Image metadata library and tools

**To Reproduce**
1.compile 64-bit debug version
**Expected behavior**
complete link 

**Failure logs** 
-(please attached failure logs)
get Linker errors:
6>exiv2.lib(convert.cpp.obj) : error LNK2019: unresolved external symbol _libiconv_open referenced in function "bool __cdecl `anonymous namespace'::convertStringCharsetIconv(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &,char const *,char const *)" (?convertStringCharsetIconv@?A0xccb74868@@YA_NAAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PBD1@Z)
6>exiv2.lib(convert.cpp.obj) : error LNK2019: unresolved external symbol _libiconv referenced in function "bool __cdecl `anonymous namespace'::convertStringCharsetIconv(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &,char const *,char const *)" (?convertStringCharsetIconv@?A0xccb74868@@YA_NAAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PBD1@Z)
6>exiv2.lib(convert.cpp.obj) : error LNK2019: unresolved external symbol _libiconv_close referenced in function "bool __cdecl `anonymous namespace'::convertStringCharsetIconv(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &,char const *,char const *)" (?convertStringCharsetIconv@?A0xccb74868@@YA_NAAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PBD1@Z)
6>D:\pkg\wx\MSVC2019\_3.1.4_2019\wxIDiff\Win32\DebUniStat\wxIDiff.exe : fatal error LNK1120: 3 unresolved externals

**Additional context**
- the code links& runs when I use a locally compiled copy of latest exiv2 from Github

**Comment by Cheney-W** [comment]
I could install this port successfully with the latest vcpkg 2021-12-09-724cea8b33cbf06c645f5095fa29773697da9761. Could you please have a try?

**Comment by JackBoosY** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.
