### ISSUE TITLE
[osgearth] build failure

### ISSUE THREAD

**Issue by nduboys** [microsoft/vcpkg#15253]
**Host Environment**
- OS: [Linux Ubunutu 20.04]
- Compiler: gcc 9.3.0-17

**To Reproduce**
`./vcpkg install osgearth`

**Failure logs** 
omputing installation plan...
The following packages will be built and installed:
    osgearth[core]:x64-linux -> 3.1
Detecting compiler hash for triplet x64-linux...
Could not locate cached archive: /home/nikoko/.cache/vcpkg/archives/ae/aefa7875b41ad0567112080fbe10fb4aae72ced7.zip
Starting package 1/1: osgearth:x64-linux
Building package osgearth[core]:x64-linux...
-- Note: osgearth only supports dynamic library linkage. Building dynamic library.
CMake Error at ports/osgearth/portfile.cmake:6 (message):
  Could not determine osg version
Call Stack (most recent call first):
  scripts/ports.cmake:136 (include)

Error: Building package osgearth:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: osgearth:x64-linux
  Vcpkg version: 2020.11.12-unknownhash

I have OSG installed, see :
nikoko@XPS:~/Dev/Others/vcpkg$ ./vcpkg list osg
osg:x64-linux                                      3.6.5#5          The OpenSceneGraph is an open source high perfor...
osg[plugins]:x64-linux                                              Build OSG Plugins - Disable for compile testing ...

**Comment by NancyLi1013** [comment]
Hi @nduboys 

Thanks for posting this issue.

Currently `osgearth `cannot build successfully on Linux. https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt#L1125
It's duplicated to #11614. Let's track this issue there.

**Comment by nduboys** [comment]
Hi Nancy

 

OK thank you very much !

 

Regards

Nicolas

 

De : NancyLi1013 <notifications@github.com> 
Envoyé : mercredi 23 décembre 2020 03:37
À : microsoft/vcpkg <vcpkg@noreply.github.com>
Cc : nduboys <nicolas.duboys@yahoo.fr>; Mention <mention@noreply.github.com>
Objet : Re: [microsoft/vcpkg] [osgearth] build failure (#15253)

 

Hi @nduboys <https://github.com/nduboys> 

Thanks for posting this issue.

Currently osgearth cannot build successfully on Linux. https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt#L1125
It's duplicated to #11614 <https://github.com/microsoft/vcpkg/issues/11614> . Let's track this issue there.
