### ISSUE TITLE
[ode:x64-windows] build failure

### ISSUE THREAD

**Issue by editing00** [microsoft/vcpkg#15250]
**Host Environment**
- OS: windows 10
- Compiler: vs 2019 (latest)

**To Reproduce**
`c:\src\vcpkg>vcpkg install --recurse --triplet x64-windows dartsim`
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/5728979/config-x64-windows-out.log)

**Failure logs** 
  Package: ode:x64-windows
  Vcpkg version: 2020.11.12-nohash

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by JonLiu1993** [comment]
@editing00 ,What is the exact version of GCC that you are using?

**Comment by editing00** [comment]
Dear JonLiu
 
I'm using visual studio 2019, CMAKE and vcpkg on the windos 10. 
 
 
   from namkyung Yoon 
 
 
 
 
-----Original Message-----

**Comment by editing00** [comment]
cmake 3.19.1   visual studio 2019     Qt 5.12.1     vcpkg 2020-11-12-nohash

**Comment by JonLiu1993** [comment]
@editing00 ,I can successfully build ode on my computer,I investigated some related issues and found that the version of Cmake does affect the construction of the port. My cmake version is cmake-3.18.4-win32-x86, you can try to build with the old version

**Comment by editing00** [comment]
> @editing00 ,I can successfully build ode on my computer,I investigated some related issues and found that the version of Cmake does affect the construction of the port. My cmake version is cmake-3.18.4-win32-x86, you can try to build with the old version

Yes It works with cmake, but I mean, it doesn't work with vcpkg command

**Comment by traversaro** [comment]
By inspecting the log, the error seems to be: 

> CMake Error: install(EXPORT "ODE" ...) includes target "ODE" more than once in the export set.

I guess this is due to this bug in CMake 3.19.0 and 3.19.1 : https://gitlab.kitware.com/cmake/cmake/-/issues/21529 . I did not checked, but I guessed probably it should be fixed by using CMake 3.19.2 .

**Comment by JonLiu1993** [comment]
@editing00 ,Thanks for posting this issuse, please use CMake 3.19.2, Please reopen this issue if it still be a problem for you
