### ISSUE TITLE
[darknet]  yolo v4 weights's hash need to update

### ISSUE THREAD

**Issue by dwh1121** [microsoft/vcpkg#15256]
Hello maintainers,

The following hash needs to be updated:

https://github.com/microsoft/vcpkg/blob/b23b7ea09f9c9aa95cb6e5042e3b1ab1bb8d710d/ports/darknet/portfile.cmake#L59
new hash ---> `SHA512 7d4d9fe150f9fe3ea7d2310f1445fe983b31fbf06d301c70ecfe00e8559e6f1bf940198c2dd55db772238f23ea0092fb6553558e5414f3ee173b8b28e53c5b54`

and

https://github.com/microsoft/vcpkg/blob/b23b7ea09f9c9aa95cb6e5042e3b1ab1bb8d710d/ports/darknet/portfile.cmake#L102
new hash ---> `SHA512 d145deb80aea3d422752e784323d89919281ed7a37d15f939f5b680ff62e502072a30e074c34a09026669126d360c7d6817ea1afa53cfa53c56bd1e16333a602`

Thank you :)

**Comment by JonLiu1993** [comment]
@dwh1121 ，Where did you find this hash value, I can still successfully build darknet on my local computer,

**Comment by dwh1121** [comment]
Hello @JonLiu1993,

I followed this procedure to install vcpkg and darknet.
[how-to-compile-on-windows-using-cmake](https://github.com/AlexeyAB/darknet#how-to-compile-on-windows-using-cmake)

The two weight files will be cached in:
vcpkg/downloads/darknet-cache/yolov4-tiny.weights
vcpkg/downloads/darknet-cache/yolov4-tiny.conv.29

You may reproduce the error if you delete these two cache files or clone a new vcpkg. 

This new hash value is displayed in the error message.
![image](https://user-images.githubusercontent.com/22817133/103008536-40c15d80-4570-11eb-80dd-7bafe1b5efcf.png)

![image](https://user-images.githubusercontent.com/22817133/103008963-e83e9000-4570-11eb-97fa-616e5b14caef.png)

**Comment by sailor239** [comment]
Hi, I encountered the same issue. May I ask how was this issue solved?

**Comment by vvojtas** [comment]
This commit seems to reverse the hash change:
https://github.com/JonLiu1993/vcpkg/commit/a528e6ac1f239dbbae281e3a59ad3696bb4a8ee5#diff-4ff1b978633c585d806f107f18e6bdca8afffa929b0349a3101e09ec42f259b5

But they seem to be fix things here:
https://github.com/microsoft/vcpkg/issues/16011

**Comment by soltkreig** [comment]
I got the same problem. Anyone know how to solve this?

**Comment by vicroms** [comment]
Make sure that you have the latest portfiles by doing a `git pull`. 

If the error persists try deleting the downloaded darknet sources in `{vcpkg-root}/downloads/`. As a last option you can overwrite the SHA by modifying `{vcpkg-root}/ports/darknet/portfile.cmake`.
