### ISSUE TITLE
[libpng] Build failure: zlib cannot be found by pkg-config

### ISSUE THREAD

**Issue by ShinNoNoir** [microsoft/vcpkg#15268]
**Host Environment**
- OS: Windows 10 20H2 (19042.685)
- Compiler: VS2017 15.9.29; VS2019 16.8.3 *(not sure which one is being used by `vcpkg`)*

**To Reproduce**
`./vcpkg install libpng`
or:
`./vcpkg install libpng:x64-windows`

**Failure logs** 
```
Starting package 1/1: libpng:x64-windows
Building package libpng[core]:x64-windows...
-- Using cached C:/repos/vcpkg/downloads/glennrp-libpng-v1.6.37.tar.gz
-- Extracting source C:/repos/vcpkg/downloads/glennrp-libpng-v1.6.37.tar.gz
-- Applying patch *snip*
-- Using source at C:/repos/vcpkg/buildtrees/libpng/src/v1.6.37-05658d6f1a.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Using msys root at C:/repos/vcpkg/downloads/tools/msys2/c809757c94447846
-- Fixing pkgconfig file: C:/repos/vcpkg/packages/libpng_x64-windows/lib/pkgconfig/libpng.pc
-- Fixing pkgconfig file: C:/repos/vcpkg/packages/libpng_x64-windows/lib/pkgconfig/libpng16.pc
-- pkg_cfg_cmd call with:C:/repos/vcpkg/downloads/tools/msys2/c809757c94447846/mingw32/bin/pkg-config.exe --exists libpng failed
-- ENV{PKG_CONFIG_PATH}:C:/repos/vcpkg/installed/x64-windows/lib/pkgconfig;C:/repos/vcpkg/installed/x64-windows/share/pkgconfig;C:/repos/vcpkg/packages/libpng_x64-windows/lib/pkgconfig;C:/repos/vcpkg/packages/libpng_x64-windows/share/pkgconfig
-- pkg-config call failed with error code:1
-- pkg-config output:
CMake Error at scripts/cmake/vcpkg_fixup_pkgconfig.cmake:79 (message):
  pkg-config error output:Package zlib was not found in the pkg-config search
  path.

  Perhaps you should add the directory containing `zlib.pc'

  to the PKG_CONFIG_PATH environment variable

  Package 'zlib', required by 'libpng', not found
Call Stack (most recent call first):
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:180 (vcpkg_fixup_pkgconfig_check_files)
  ports/libpng/portfile.cmake:138 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:136 (include)


Error: Building package libpng:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libpng:x64-windows
  Vcpkg version: 2020.11.12-nohash
```

**Additional context**
- I have not set the `$env:PKG_CONFIG_PATH` environment variable.
- The file `zlib.pc` is available in the following folders, but not in `vcpkg/installed`:
    - `vcpkg/buildtrees/zlib/x64-windows-dbg/zlib.pc`
    - `vcpkg/buildtrees/zlib/x64-windows-rel/zlib.pc`
    - `vcpkg/buildtrees/zlib/x86-windows-dbg/zlib.pc`
    - `vcpkg/buildtrees/zlib/x86-windows-rel/zlib.pc`

Possibly the `libpng` port can be fixed by having the `zlib` port install its `.pc` file.

**Comment by StarGate-One** [comment]
1. vcpkg should install the `zlib.pc` files in the following locations:
`[vcpkg-root]\installed\[triplet]\lib\pkgconfig`
`[vcpkg-root]\installed\[triplet]\debug\lib\pkgconfig`
`[vcpkg-root]\packages\zlib_[triplet]\lib\pkgconfig`
`[vcpkg-root]\packages\zlib_[triplet]\debug\lib\pkgconfig`
2. It would seem something has gone wrong with the zlib installation, I would try removing and reinstalling port `zlib`
3. If that does not work, it is possible the vcpkg instance has become corrupt, I would then try creating a new instance of vcpkg
4. From one of my test instances of vcpkg:
`My-UserID@My-PC 12/23/2020 15:32:23 D:\vcpkg_x64\vs2019\test`
`->dir /s zlib.pc`
` Volume in drive D is Dev01`
` Volume Serial Number is 72B7-8EE4`
` `
` Directory of D:\vcpkg_x64\vs2019\test\buildtrees\zlib\x64-windows-dbg`
` `
`12/22/2020  23:30               509              My-PC\My-UserID zlib.pc`
`               1 File(s)            509 bytes`
` `
` Directory of D:\vcpkg_x64\vs2019\test\buildtrees\zlib\x64-windows-rel`
` `
`12/22/2020  23:30               478              My-PC\My-UserID zlib.pc`
`               1 File(s)            478 bytes`
` `
` Directory of D:\vcpkg_x64\vs2019\test\downloads\tools\perl\5.30.0.1\c\lib\pkgconfig`
` `
`05/22/2019  14:57               268              My-PC\My-UserID zlib.pc`
`               1 File(s)            268 bytes`
` `
**` Directory of D:\vcpkg_x64\vs2019\test\installed\x64-windows\debug\lib\pkgconfig`**
` `
`12/22/2020  23:30               294              My-PC\My-UserID zlib.pc`
`               1 File(s)            294 bytes`
` `
**` Directory of D:\vcpkg_x64\vs2019\test\installed\x64-windows\lib\pkgconfig`**
` `
`12/22/2020  23:30               290              My-PC\My-UserID zlib.pc`
`               1 File(s)            290 bytes`
` `
**` Directory of D:\vcpkg_x64\vs2019\test\packages\zlib_x64-windows\debug\lib\pkgconfig`**
` `
`12/22/2020  23:30               294              My-PC\My-UserID zlib.pc`
`               1 File(s)            294 bytes`
` `
**` Directory of D:\vcpkg_x64\vs2019\test\packages\zlib_x64-windows\lib\pkgconfig`**
` `
`12/22/2020  23:30               290              My-PC\My-UserID zlib.pc`
`               1 File(s)            290 bytes`
` `
`     Total Files Listed:`
`               7 File(s)          2,423 bytes`
`               0 Dir(s)  584,097,222,656 bytes free`

**Comment by NancyLi1013** [comment]
Hi @ShinNoNoir 

Thanks for posting this issue.

Could you please remove `zlib: x86-windows` or `zlib:x64-windows` then try to rebuild `libpng`?

`zlib.pc` should be installed to _installed\triplet\lib\pkgconfig_ directory as @StarGate-One said above.

 I think you might have installed `zlib` before this change. https://github.com/microsoft/vcpkg/commit/273b5eddaa2d38b7df285efe915a0ce0ba12b7c5#diff-1ee0dc969989c37c35076df21135495f4ae6bcca0ccae404ecef27037077a98c

**Comment by ShinNoNoir** [comment]
I'm currently unable to look into it, but I will when I get back on Monday.

**Comment by ShinNoNoir** [comment]
Update: Removing `zlib` (and having it installed again when rebuilding `libpng`) fixed it.
