### ISSUE TITLE
Consider providing vcpkg binaries in releases

### ISSUE THREAD

**Issue by cjdb** [microsoft/vcpkg#15261]
****

**Is your feature request related to a problem? Please describe.**
I use GitHub Actions for CI on a private repository, which as I understand it, has a monthly budget of minutes. As such, I'd like to minimise the amount of time any given CI run takes.

I've observed that building vcpkg takes roughly 2-3 minutes, not including building the libraries I wish to install.

**Proposed solution**
I'd be neat if prebuilt binaries were downloadable with each release, not unlike Ninja. It'd also be cool if a script was provided so that the workflow could be:

```
git clone https://github.com/Microsoft/vcpkg.git
cd vcpkg
./get-latest-vcpkg-for-ci.sh # downloads whatever the latest binary is and unzips it
./vcpkg install catch2
```

**Describe alternatives you've considered**
No alternatives considered (other than a different release cadence), but I'm open to suggestions.

**Comment by JackBoosY** [comment]
Yes, we are prepare to publish vcpkg binary in the future.

Duplicated to #14995.
