### ISSUE TITLE
[dlib] features list provided during install is not being respected

### ISSUE THREAD

**Issue by Kicer86** [microsoft/vcpkg#15267]
**Describe the bug**
I want to install dlib with cuda support, but vcpkg also enables fftw3 and sqlite3 features

**Environment**
- OS: Windows
- Compiler: 16.8.3

**To Reproduce**
1. ./vcpkg install dlib[cuda]
2. See that other features are also being applied: dlib[core,cuda,fftw3,sqlite3]:x86-windows -> 19.21#4
(including sqlite3 and fftw3 libraries)

**Expected behavior**
I'd expect only cuda to be included

Here I attach whole output:
vcpkg.exe install dlib[cuda]
Computing installation plan...
The following packages will be built and installed:
  * blas[core]:x86-windows -> 1
  * cuda[core]:x86-windows -> 10.1#5
    dlib[core,cuda,fftw3,sqlite3]:x86-windows -> 19.21#4
  * fftw3[core]:x86-windows -> 3.3.8-7
  * lapack[core]:x86-windows -> 3#1
  * lapack-reference[blas-select,core,noblas]:x86-windows -> 3.8.0#4
  * libjpeg-turbo[core]:x86-windows -> 2.0.5#1
  * libpng[core]:x86-windows -> 1.6.37#14
  * openblas[core]:x86-windows -> 0.3.10
  * sqlite3[core]:x86-windows -> 3.33.0
  * vcpkg-gfortran[core]:x86-windows -> 3
  * zlib[core]:x86-windows -> 1.2.11#9
Additional packages (*) will be modified to complete this operation.

**Comment by Kicer86** [comment]
Another weird thing is that even when cuda is being selected, it seems to be not used, as after installation dlib/config.h contains:

// You should also consider telling dlib to link against libjpeg, libpng, libgif, fftw, CUDA, 
// and a BLAS and LAPACK library.  To do this you need to uncomment the following #defines.
#define DLIB_JPEG_SUPPORT
#define DLIB_PNG_SUPPORT
/* #undef DLIB_GIF_SUPPORT */
#define DLIB_USE_FFTW
#define DLIB_USE_BLAS
#define DLIB_USE_LAPACK
/* #undef DLIB_USE_CUDA */
/* #undef DLIB_USE_MKL_FFT */

**Comment by StarGate-One** [comment]
1. Port `dlib` default features are fftw3 and sqlite3 whether cuda feature is used or not (see `[vcpkg-root]\ports\dlib\CONTROL` file - `Default-Features: fftw, sqlite3`)
2. Try `vcpkg install dlib[core,cuda]` to get only dlib core features with cuda
3. I do not have/need the use of port dlib, so I am unable to answer whether cuda is used in the actual build/link/install of port dlib with feature cuda?

**Comment by Kicer86** [comment]
1. & 2. helped for the main issue.

I did some research and installing cudnn port fixed the problem (dlib needs cuda and cudnn). So it is a missing dependency issue.

I have a fix for it. Should I open a PR?
