### ISSUE TITLE
vcpkg demands latest version of ninja and falls over if it's not a system binary

### ISSUE THREAD

**Issue by cjdb** [microsoft/vcpkg#15260]
**Describe the bug**
I attempt to install a library with my custom triplet and vcpkg fails unless ninja is at least v10.0.1 _and_ is a system binary (i.e. the one it insists on downloading isn't working). It's a huge time sink of GitHub Actions minutes and I'd prefer not to need to build this from source there.

**Environment**
- OS: Ubuntu 20.04
- Compiler: clang++-11, clang++-12

**To Reproduce**
1. ./vcpkg install --triplet=clang_libstdcxx catch2
2. See error

**Expected behavior**
catch2 installs.

**Failure logs** 
- [failure.txt](https://github.com/microsoft/vcpkg/files/5733120/failure.txt)
- [clang_libstdcxx.cmake](https://github.com/microsoft/vcpkg/files/5733121/clang_libstdcxx.cmake.txt)

**Comment by NancyLi1013** [comment]
Hi @cjdb 

Thanks for posting this issue.

vcpkg has updated `Ninja `to 1.10.1. We should use the version that vcpkg provides.

I noticed that it had found Ninja 1.10.0 on your local. So you need to remove Ninja from your local and then rebuild.

```
/home/runner/work/project/project/vcpkg/scripts/ports.cmake 2>&1)
[DEBUG] -- Found ninja('1.10.0') but at least version 1.10.1 is required! Trying to use internal version if possible!
[DEBUG] -- Using cached /home/runner/work/project/project/vcpkg/downloads/ninja-linux-1.10.1.zip
[DEBUG] CMake Error at scripts/cmake/vcpkg_find_acquire_program.cmake:494 (message):
[DEBUG]   Unable to find ninja with min version of 1.10.1
[DEBUG] Call Stack (most recent call first):
[DEBUG]   scripts/cmake/vcpkg_find_acquire_program.cmake:591 (do_find)
[DEBUG]   scripts/cmake/vcpkg_configure_cmake.cmake:164 (vcpkg_find_acquire_program)
[DEBUG]   scripts/detect_compiler/portfile.cmake:18 (vcpkg_configure_cmake)
[DEBUG]   scripts/ports.cmake:136 (include)
```

**Comment by cjdb** [comment]
That's the Ubuntu-installed version of Ninja, which I need for other projects. I can't uninstall it.

**Comment by cjdb** [comment]
It's also worth noting that this issue doesn't occur if I use the default triple.

**Comment by NancyLi1013** [comment]
You add`set(CMAKE_FIND_ROOT_PATH "/usr/")` to your triplet.

Now Ninja was found in these paths:

```
[DEBUG] Found path: /usr/bin/ninja
[DEBUG] Found path: /bin/ninja
[DEBUG] popen("/usr/bin/ninja" --version 2>&1)
```
Could you please try to remove this line and rebuild? Or is it possible to upgrade Ninja to 1.10.1 on your local?

**Comment by cjdb** [comment]
Thanks @NancyLi1013! Looks like it's working again. Both options work, but I'll go with the former since it's probably more robust.
