### ISSUE TITLE
[catch2] failure when trying to install from head

### ISSUE THREAD

**Issue by cjdb** [microsoft/vcpkg#15272]
**Host Environment**
- OS: Ubuntu 20.04 (native, WSL2), Ubuntu 20.10 (native), Windows 10
- Compiler: n/a

**To Reproduce**
`./vcpkg install --head catch2`

**Failure logs** 
[catch-failure.txt](https://github.com/microsoft/vcpkg/files/5736697/catch-failure.txt)

**Additional context**
This is specifically for catch2; I have no issue with `./vcpkg install --head catch`, which I believe to be an alias for catch2.

**Comment by JonLiu1993** [comment]
@cjdb ,catch2 have updated to 2.13.7,Could you please update your vcpkg and try again?
