### ISSUE TITLE
MinGW cross-compile from Linux fails because compiler executables don't have .exe extension

### ISSUE THREAD

**Issue by hectorchu** [microsoft/vcpkg#15270]
**Describe the bug**

In scripts/toolchains/mingw.cmake, there are these 3 lines:

find_file(CMAKE_C_COMPILER "${CMAKE_SYSTEM_PROCESSOR}-w64-mingw32-gcc.exe")
find_file(CMAKE_CXX_COMPILER "${CMAKE_SYSTEM_PROCESSOR}-w64-mingw32-g++.exe")
find_file(CMAKE_RC_COMPILER "${CMAKE_SYSTEM_PROCESSOR}-w64-mingw32-windres.exe")

But on Linux those executables don't have an .exe extension.

This file needs to be able to check for them as well.

**Environment**
- OS: Linux (Ubuntu)
- Compiler: revision

**To Reproduce**
1. ./vcpkg install xxxx
2. See error
Repro code when

**Expected behavior**

**Failure logs** 
-(please attached failure logs)

**Additional context**

**Comment by JackBoosY** [comment]
cc @longnguyen2004

**Comment by longnguyen2004** [comment]
Will fix now.

**Comment by longnguyen2004** [comment]
@hectorchu Please test #15282

**Comment by hectorchu** [comment]
Works perfectly!
