### ISSUE TITLE
[cairo:x64-windows] build failure

### ISSUE THREAD

**Issue by proTerm** [microsoft/vcpkg#15275]
**Host Environment**
- OS: [Windows]
- Compiler: MSVC 19.27.29112.0
- Vcpkg version: 2020.11.12-nohash

**To Reproduce**
`./vcpkg install cairo --triplet x64-windows`

**Failure logs** 
- `CMake Error at C:/vcpkg/installed/x64-windows/share/unofficial-pixman/unofficial-pixman-config.cmake:73`
- [config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/5737042/config-x64-windows-out.log)

**Comment by StarGate-One** [comment]
1. Looks like port `pixman` either did not install properly or the lib files were moved/renamed/deleted.
2. I would try to remove/reinstall port pixman
3. From the error log `config-x64-windows-out.log`
>CMake Error at C:/vcpkg/installed/x64-windows/share/unofficial-pixman/unofficial-pixman-config.cmake:73 (message):
>  The imported target "unofficial::pixman::pixman-1" references the file
>
>     "C:/vcpkg/installed/x64-windows/lib/pixman-1.lib"
>
>  but this file does not exist.  Possible reasons include:
>
**>  * The file was deleted, renamed, or moved to another location.**
>
**>  * An install or uninstall procedure did not complete successfully.**
>
**>  * The installation package was faulty and contained**
>
>    "C:/vcpkg/installed/x64-windows/share/unofficial-pixman/unofficial-pixman-config.cmake"
>
>  but not all the files it references.
4. From one of my vcpkg instances:
`My-UserID@My-PC 12/23/2020 16:10:59 D:\vcpkg_x64\vs2019\test`
`->dir /s pixman-1.lib`
` Volume in drive D is Dev01`
` Volume Serial Number is 72B7-8EE4`
` `
` Directory of D:\vcpkg_x64\vs2019\test\buildtrees\pixman\x64-windows-rel`
` `
`12/16/2020  19:55         4,836,262              My-PC\My-UserID pixman-1.lib`
`               1 File(s)      4,836,262 bytes`
` `
**` Directory of D:\vcpkg_x64\vs2019\test\installed\x64-windows\lib`**
` `
**`12/16/2020  19:55         4,836,262              My-PC\My-UserID pixman-1.lib`**
`               1 File(s)      4,836,262 bytes`
` `
**` Directory of D:\vcpkg_x64\vs2019\test\packages\pixman_x64-windows\lib`**
` `
**`12/16/2020  19:55         4,836,262              My-PC\My-UserID pixman-1.lib`**
`               1 File(s)      4,836,262 bytes`
` `
`     Total Files Listed:`
`               3 File(s)     14,508,786 bytes`
`               0 Dir(s)  584,097,222,656 bytes free`

**Comment by JackBoosY** [comment]
Hi @proTerm, thanks for reporting this issue!
According to the log content, the library may have been deleted by anti-virus.
Please remove and reinstall the port.

Thanks.

**Comment by proTerm** [comment]
We could close this. I dont know what the reason was.
I did removed `pixman`, and newly installed pixman, before I posted this.

For those whove experienced something as muddy as mine issue, I would like to mention is that timeline
- **Before** I posted the issue:
-- Got the error with `2020.06.11-nohash` -> made `vckpg update ; vckpg upgrade --no-dry-run` -> got the error again -> made `git pull` for `vcpkg` -> run the `bootstrap-vcpkg.bat` -> got the **error again** -> Posted the **issue**
- **After**
-- made `vckpg update ; vckpg upgrade --no-dry-run`  -> the **error was gone**

**Comment by JackBoosY** [comment]
@proTerm Glad to know the issue is gone.
I'm pretty sure this is caused by anti-virus behavior, you can check the anti-virus security logs.

**Comment by proTerm** [comment]
> I'm pretty sure this is caused by anti-virus behavior,

@JackBoosY I couldnt confirm that. I only have Windows Defender, and its live protection is switched off. Thread History or EventViewer->...->WindowsDefender -> Logs dont show any removal of a file.

**Comment by JackBoosY** [comment]
@proTerm Maybe related to pixman, just maybe. There must be an executable delete it.

**Comment by proTerm** [comment]
@JackBoosY What is the reason for starting a cairo rebuild again, after a successful build ?
I wouldnt have asked, but it takes really long to build everything (the biggest chunk of the `cairo` dependencies: `libiconv` (45mins), `fontconfig`(35min) etc. takes too long). Are there options to use more cores, currently one one core is being used?
Is it connected with the missing locate cached archive ? (Why is it missing actually?)
```
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\UsrA\AppData\Local\vcpkg\archives\fb\fb9ef54be652219dc209878df3a1de3ed77e06bb.zip
Could not locate cached archive: C:\Users\UsrA\AppData\Local\vcpkg\archives\b2\b2a2da795e077d59ff4c2658a57b0a5d8709fb42.zip
Could not locate cached archive: C:\Users\UsrA\AppData\Local\vcpkg\archives\a1\a1ccd327a2347f31ac14b44ae0604b5a57bf6339.zip
Could not locate cached archive: C:\Users\UsrA\AppData\Local\vcpkg\archives\5b\5b70adfc1f9074cc8a01e70b447673450a224807.zip
Could not locate cached archive: C:\Users\UsrA\AppData\Local\vcpkg\archives\a1\a120635b31e637991086a6e470d376eb36948786.zip
Could not locate cached archive: C:\Users\UsrA\AppData\Local\vcpkg\archives\a6\a665f20a4c6ba408a25ec18288187e60d5844901.zip
Could not locate cached archive: C:\Users\UsrA\AppData\Local\vcpkg\archives\4e\4e1e4abf16d28490e34c2f4f47b0f3ce5159d890.zip
Could not locate cached archive: C:\Users\UsrA\AppData\Local\vcpkg\archives\8d\8dee8ae050d4523dc05a1bd15a3ec1306fe529ff.zip
Could not locate cached archive: C:\Users\UsrA\AppData\Local\vcpkg\archives\60\6099d867e4b4b986f1575a324219ed656921b33a.zip
```

**Comment by JackBoosY** [comment]
@proTerm The only reason for rebuilding is that the port is updated.
All cpu cores should be used to build cario.
Missing cache has nothing to do with this.

**Comment by proTerm** [comment]
@JackBoosY couldnt quite understand your answer: what port has been updated?
How do you enable all cpu cores? I would have suggested that vcpkg does it by default?
Are these compile times "normal" ?
What does the missing cache mean?

**Comment by JackBoosY** [comment]
vcpkg will compare the status of the port when it is installed with the status of the current port to determine which port should be updated (According to the `portfile.cmake` / patches / `CONTROL` / `vcpkg.json` and other tool-related cmakes).

vcpkg will also automatically obtain the number of cpu cores and use all cores.

I think there is no problem with the current compile time. Cross compiling these ports in windows is very time consuming.

The missing cache may be a vcpkg bug.
