### ISSUE TITLE
[sdl2] Update to 2.0.14

### ISSUE THREAD

**Issue by MCJack123** [microsoft/vcpkg#15278]
Library name: SDL2

New version number: 2.0.14

Other information that may be useful (release notes, etc...)
Release notes are [on the Mercurial repo](https://hg.libsdl.org/SDL/file/e52d96ea04fc/WhatsNew.txt).

I'd work on this PR myself, but I'm busy at the moment, and I don't know what each patch is supposed to do and whether they will be necessary anymore. If anyone wants to update it sooner, then go ahead.

**Comment by DJm00n** [comment]
Please also fix minor issue with copyright line in resource:
![image](https://user-images.githubusercontent.com/1285934/103211948-37d6e000-4912-11eb-818a-af0d1d7a1b4b.png)
I didn't had such issue when building manually via CMake.
![image](https://user-images.githubusercontent.com/1285934/103212013-6a80d880-4912-11eb-984b-e0250de43e69.png)

**Comment by DJm00n** [comment]
I investigated this encoding issue a bit.
It is because vcpkg [adding `-c65001` into `CMAKE_RC_FLAGS`](https://github.com/microsoft/vcpkg/blob/master/scripts/toolchains/windows.cmake#L24) but `src\main\windows\version.rc` file is in CP1252. Just need patch it and convert to UTF-8.

**Comment by JonLiu1993** [comment]
Solved by #15398
