### ISSUE TITLE
[boost-di] update to 1.2

### ISSUE THREAD

**Issue by byxrolland** [microsoft/vcpkg#15280]
Library name: boost-di

New version number: 1.2

Please update the port. It's more than a year old.

**Comment by StarGate-One** [comment]
- I think the library has moved to https://github.com/boost-ext/di 
- https://github.com/boost-experimental/di gives me a redirect back over to https://github.com/boost-ext/di

**Comment by lgrossi** [comment]
@BillyONeal I see that this was completed in 2020, but I don't see boost-di in the current ports in the latest version or master.
Was it removed?

I can install boost-di perfectly using manifest:
```
  "dependencies": [
    ...
    "boost-di",
    ...
  ],

...
boost-di is header-only and can be used from CMake via:

    find_path(BOOST_DI_INCLUDE_DIRS "boost/di.hpp")
    target_include_directories(main PRIVATE ${BOOST_DI_INCLUDE_DIRS})
```

However, if I install it doesn't recognize the port:
```
lgrossi@DESKTOP-6LG06VA:~/otbr$ ~/vcpkg/vcpkg install boost-di
Computing installation plan...
error: while looking for boost-di:x64-linux:
error: while loading boost-di:
error: boost-di does not exist
```

We do have a solution that allows the user to choose if they want to build using manifest or manually installing the ports, and the second is broken for boost-di.

Pinging here for sanity check before opening a new ticket.
