### ISSUE TITLE
Multiple nuget exports

### ISSUE THREAD

**Issue by IlTeo285** [microsoft/vcpkg#15289]
****

Exporting two ore more nuget packages and importing them into visual studio doesn't work as expected.
Only the last installed package is correctely injected into the project. 
From what I've seen the internal `vckpg.props` and `vcpkg.targets` define the same tags.

**Proposed solution**
Create tags according to --nuget.id definition

**Comment by NancyLi1013** [comment]
@BillyONeal 

Could you please help take a look?

Thanks.

**Comment by PhoebeHui** [comment]
Closing in favor of https://github.com/microsoft/vcpkg/issues/3954
