### ISSUE TITLE
Building package bzip2:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by InnovationLou** [microsoft/vcpkg#15287]
**Host Environment**
- OS:Windows10
- Compiler: revision

**To Reproduce**
`./vcpkg install allegro5`

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.
Computing installation plan...
A suitable version of cmake was not found (required v3.18.4). Downloading portable cmake v3.18.4...
Downloading cmake...
  https://github.com/Kitware/CMake/releases/download/v3.18.4/cmake-3.18.4-win32-x86.zip -> D:\cpppacks\vcpkg\downloads\cmake-3.18.4-win32-x86.zip
Extracting cmake...
A suitable version of 7zip was not found (required v18.1.0). Downloading portable 7zip v18.1.0...
Downloading 7zip...
  https://www.nuget.org/api/v2/package/7-Zip.CommandLine/18.1.0 -> D:\cpppacks\vcpkg\downloads\7-zip.commandline.18.1.0.nupkg
Extracting 7zip...
A suitable version of nuget was not found (required v5.5.1). Downloading portable nuget v5.5.1...
Downloading nuget...
  https://dist.nuget.org/win-x86-commandline/v5.5.1/nuget.exe -> D:\cpppacks\vcpkg\downloads\22ea847d-nuget.exe
The following packages will be built and installed:
    allegro5[core]:x86-windows -> 5.2.6.0
  * brotli[core]:x86-windows -> 1.0.9
  * bzip2[core]:x86-windows -> 1.0.8#1
  * freetype[brotli,bzip2,core,png,zlib]:x86-windows -> 2.10.2#7
  * libflac[core]:x86-windows -> 1.3.3#5
  * libogg[core]:x86-windows -> 1.3.4#3
  * libpng[core]:x86-windows -> 1.6.37#14
  * libtheora[core]:x86-windows -> 1.2.0alpha1-20170719#2
  * libvorbis[core]:x86-windows -> 1.3.7#1
  * openal-soft[core]:x86-windows -> 1.20.1#5
  * opengl[core]:x86-windows -> 0.0#8
  * opus[core]:x86-windows -> 1.3.1#5
  * opusfile[core]:x86-windows -> 0.12
  * physfs[core]:x86-windows -> 3.0.2-2
  * zlib[core]:x86-windows -> 1.2.11#9
Additional packages (*) will be modified to complete this operation.
Warning: The following VS instances are excluded because the English language pack is unavailable.
    D:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools
Please install the English language pack.
Detecting compiler hash for triplet x86-windows...
A suitable version of git was not found (required v2.26.2). Downloading portable git v2.26.2...
Downloading git...
  https://github.com/git-for-windows/git/releases/download/v2.26.2.windows.1/PortableGit-2.26.2-32-bit.7z.exe -> D:\cpppacks\vcpkg\downloads\PortableGit-2.26.2-32-bit.7z.exe
Extracting git...
A suitable version of powershell-core was not found (required v7.1.0). Downloading portable powershell-core v7.1.0...
Downloading powershell-core...
  https://github.com/PowerShell/PowerShell/releases/download/v7.1.0/PowerShell-7.1.0-win-x86.zip -> D:\cpppacks\vcpkg\downloads\PowerShell-7.1.0-win-x86.zip
Extracting powershell-core...
Could not locate cached archive: C:\Users\admin\AppData\Local\vcpkg\archives\ef\efeaa070e7d687e716766a3d1d4401078e83cc99.zip
Could not locate cached archive: C:\Users\admin\AppData\Local\vcpkg\archives\06\064f45b799e9d035c5fce7675a781d31d14146e9.zip
Could not locate cached archive: C:\Users\admin\AppData\Local\vcpkg\archives\17\17994859a88241960fe19bbcdf611c9e9c96c677.zip
Could not locate cached archive: C:\Users\admin\AppData\Local\vcpkg\archives\f3\f3d761ae7da45aa279505322551f38139cee4450.zip
Could not locate cached archive: C:\Users\admin\AppData\Local\vcpkg\archives\4d\4d717c1552f1cdef95f382624dd4ec036e8b3fa4.zip
Could not locate cached archive: C:\Users\admin\AppData\Local\vcpkg\archives\86\8647801d9770ba246d534fb5293096effc6b7855.zip
Could not locate cached archive: C:\Users\admin\AppData\Local\vcpkg\archives\12\1201aa50a00eee3612b04aa0cc64117b5e4b9fc0.zip
Could not locate cached archive: C:\Users\admin\AppData\Local\vcpkg\archives\4a\4ab850f8171b287417d477ef853b81fae6e3db98.zip
Could not locate cached archive: C:\Users\admin\AppData\Local\vcpkg\archives\94\94a9bcf530e02c01aa2e7836203ae927dac1cb3b.zip
Could not locate cached archive: C:\Users\admin\AppData\Local\vcpkg\archives\1d\1de4c674ccb77daa92ccda4ccbe991b212030a53.zip
Could not locate cached archive: C:\Users\admin\AppData\Local\vcpkg\archives\19\19fc09df5cbbcd729a2f0d62539706000125727f.zip
Could not locate cached archive: C:\Users\admin\AppData\Local\vcpkg\archives\1a\1a0eb1a8405a84c8c3b09f2504e1efc432414bdd.zip
Could not locate cached archive: C:\Users\admin\AppData\Local\vcpkg\archives\e0\e0653c88d515eab57fa154f2fa8b0fb5eeb4578b.zip
Could not locate cached archive: C:\Users\admin\AppData\Local\vcpkg\archives\a6\a63c7a1131f14dd66c85c4863d2af2bfe4c3bc35.zip
Could not locate cached archive: C:\Users\admin\AppData\Local\vcpkg\archives\57\570c9206ba7647da91a423352d0aa7dae91e9aba.zip
Starting package 1/15: bzip2:x86-windows
Building package bzip2[core]:x86-windows...
-- Fetching https://sourceware.org/git/bzip2.git...
-- Extracting source D:/cpppacks/vcpkg/downloads/bzip2-75a94bea3918e612b879d6a11ca64b8689526147.tar.gz
-- Applying patch fix-import-export-macros.patch
-- Using source at D:/cpppacks/vcpkg/buildtrees/bzip2/src/8689526147-1ef169fbaa.clean
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:108 (message):
    Command failed: ninja -v
    Working Directory: D:/cpppacks/vcpkg/buildtrees/bzip2/x86-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\cpppacks\vcpkg\buildtrees\bzip2\config-x86-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:319 (vcpkg_execute_required_process)
  ports/bzip2/portfile.cmake:12 (vcpkg_configure_cmake)
  scripts/ports.cmake:136 (include)

Error: Building package bzip2:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: bzip2:x86-windows
  Vcpkg version: 2020.11.12-nohash

Additionally, attach any relevant sections from the log files above.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by StarGate-One** [comment]
Please attach (drag & drop)  the log file `D:\cpppacks\vcpkg\buildtrees\bzip2\config-x86-windows-out.log`  for  additional research/trouble diagnosis.
![image](https://user-images.githubusercontent.com/68293825/103106764-3ea9de00-4606-11eb-8f6c-bb32671c4355.png)

**Comment by InnovationLou** [comment]
[config-x86-windows-out.log](https://github.com/microsoft/vcpkg/files/5740817/config-x86-windows-out.log)

**Comment by JonLiu1993** [comment]
@InnovationLou ,in my opinion the fault of non-English environment \unicode ?
````
Please install the English language pack.
Detecting compiler hash for triplet x86-windows...
A suitable version of git was not found (required v2.26.2). Downloading portable git v2.26.2...
````

**Comment by InnovationLou** [comment]
Thanks. This issues can be marked as solved now.
