### ISSUE TITLE
opencv4 build error on windows

### ISSUE THREAD

**Issue by dorbodwolf** [microsoft/vcpkg#15294]
### summary

Error: Building package opencv4:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with .\vcpkg update, then

**Package: opencv4:x64-windows
Vcpkg version: 2020.11.12-nohash**
### details

C:\vcpkg-master> .\vcpkg.exe install darknet[full]:x64-windows
Computing installation plan...
The following packages will be built and installed:
  * darknet[core,cuda,cudnn,full,opencv-cuda,weights,weights-train]:x64-windows -> 2020-08-30#1
  * opencv[core,cuda,dnn,ffmpeg,jpeg,opengl,png,tiff,webp]:x64-windows -> 4.3.0
  * opencv4[contrib,core,cuda,dnn,ffmpeg,jpeg,opengl,png,tiff,webp]:x64-windows -> 4.3.0#4
  * pthreads[core]:x64-windows -> 3.0.0-6
  * stb[core]:x64-windows -> 2020-09-14
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\9e\9e63137afe26778df6515b86153894e95c8a20fe.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\30\30ae5b582f700cbbaa12c6764913e1916d4bf76f.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\55\55b946bc43535bad6ac194f0ebe1c0a016d8983a.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\d6\d6c2a30e7f143335ace401bf88e126e5e92f7854.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\a3\a36320fdec254fb2e8312270f440a68174a35dd8.zip
Starting package 1/5: opencv4:x64-windows
Building package opencv4[contrib,core,cuda,dnn,ffmpeg,jpeg,opengl,png,tiff,webp]:x64-windows...
-- Using cached C:/vcpkg-master/downloads/opencv-opencv-4.3.0.tar.gz
-- Cleaning sources at C:/vcpkg-master/buildtrees/opencv4/src/4.3.0-58520c6ae3.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg-master/downloads/opencv-opencv-4.3.0.tar.gz
-- Applying patch 0001-disable-downloading.patch
-- Applying patch 0002-install-options.patch
-- Applying patch 0003-force-package-requirements.patch
-- Applying patch 0004-fix-policy-CMP0057.patch
-- Applying patch 0006-fix-vtk9.patch
-- Applying patch 0006-jpeg2000_getref.patch
-- Applying patch 0009-fix-uwp.patch
-- Applying patch 0010-fix-interface_link_libraries.patch
-- Using source at C:/vcpkg-master/buildtrees/opencv4/src/4.3.0-58520c6ae3.clean
-- Using cached C:/vcpkg-master/downloads/opencv-cache/tiny_dnn/adb1c512e09ca2c7a6faef36f9c53e59-v1.0.0a3.tar.gz
-- Using cached C:/vcpkg-master/downloads/opencv-cache/nvidia_optical_flow/ca5acedee6cb45d0ec610a6732de5c15-79c6cee80a2df9a196f20afd6b598a9810964c32.zip
-- Using cached C:/vcpkg-master/downloads/opencv-opencv_contrib-4.3.0.tar.gz
-- Cleaning sources at C:/vcpkg-master/buildtrees/opencv4/src/4.3.0-1c7c3cc613.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg-master/downloads/opencv-opencv_contrib-4.3.0.tar.gz
-- Applying patch 0005-add-missing-stdexcept-include.patch
-- Applying patch 0007-fix-vtk9-contrib.patch
-- Using source at C:/vcpkg-master/buildtrees/opencv4/src/4.3.0-1c7c3cc613.clean
-- Using cached C:/vcpkg-master/downloads/opencv-cache/xfeatures2d/boostdesc/0ea90e7a8f3f7876d450e4149c97c74f-boostdesc_bgm.i
-- Using cached C:/vcpkg-master/downloads/opencv-cache/xfeatures2d/boostdesc/232c966b13651bd0e46a1497b0852191-boostdesc_bgm_bi.i
-- Using cached C:/vcpkg-master/downloads/opencv-cache/xfeatures2d/boostdesc/324426a24fa56ad9c5b8e3e0b3e5303e-boostdesc_bgm_hd.i
-- Using cached C:/vcpkg-master/downloads/opencv-cache/xfeatures2d/boostdesc/202e1b3e9fec871b04da31f7f016679f-boostdesc_binboost_064.i
-- Using cached C:/vcpkg-master/downloads/opencv-cache/xfeatures2d/boostdesc/98ea99d399965c03d555cef3ea502a0b-boostdesc_binboost_128.i
-- Using cached C:/vcpkg-master/downloads/opencv-cache/xfeatures2d/boostdesc/e6dcfa9f647779eb1ce446a8d759b6ea-boostdesc_binboost_256.i
-- Using cached C:/vcpkg-master/downloads/opencv-cache/xfeatures2d/boostdesc/0ae0675534aa318d9668f2a179c2a052-boostdesc_lbgm.i
-- Using cached C:/vcpkg-master/downloads/opencv-cache/xfeatures2d/vgg/e8d0dcd54d1bcfdc29203d011a797179-vgg_generated_48.i
-- Using cached C:/vcpkg-master/downloads/opencv-cache/xfeatures2d/vgg/7126a5d9a8884ebca5aea5d63d677225-vgg_generated_64.i
-- Using cached C:/vcpkg-master/downloads/opencv-cache/xfeatures2d/vgg/7cd47228edec52b6d82f46511af325c5-vgg_generated_80.i
-- Using cached C:/vcpkg-master/downloads/opencv-cache/xfeatures2d/vgg/151805e03568c9f490a5e3a872777b75-vgg_generated_120.i
-- Using cached C:/vcpkg-master/downloads/opencv-cache/data/7505c44ca4eb54b4ab1e4777cb96ac05-face_landmark_model.dat
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:145 (message):
    Command failed: C:/vcpkg-master/downloads/tools/cmake-3.18.4-windows/cmake-3.18.4-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v -j41
    Working Directory: C:/vcpkg-master/buildtrees/opencv4/x64-windows-dbg
    See logs for more information:
      C:\vcpkg-master\buildtrees\opencv4\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:27 (vcpkg_build_cmake)
  ports/opencv4/portfile.cmake:362 (vcpkg_install_cmake)
  scripts/ports.cmake:136 (include)

Error: Building package opencv4:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then

  **Package: opencv4:x64-windows
  Vcpkg version: 2020.11.12-nohash**

Additionally, attach any relevant sections from the log files above.

**Comment by dorbodwolf** [comment]
[#15055](https://github.com/microsoft/vcpkg/issues/15055)

**Comment by JonLiu1993** [comment]
@dorbodwolf ,Thanks for posting this issue,Duplicate to #15055
