### ISSUE TITLE
[fontconfig] Switch to meson build system with fontconfig 2.13.93

### ISSUE THREAD

**Issue by ankurvdev** [microsoft/vcpkg#15303]
****
fontconfig port currently uses Makefiles which are a problem to maintain and debug issues.
The port is also currently broken for x64-windows-static-md
It used to be a custom-CmakeLists.txt based build but sometime back it was swapped out in favor of using the native Makefile based build which broke the community port.

**Proposed solution**
Given that fontconfig now has a meson-build system. I propose we move this port to the meson based build system for easier maintainance and wider availability
https://github.com/freedesktop/fontconfig/blob/master/meson.build

**Describe alternatives you've considered**
The alternative would be to keep fixing the Makefiles with additional patches 

**Additional context**

https://github.com/freedesktop/fontconfig/blob/master/meson.build

**Comment by NancyLi1013** [comment]
Hi @ankurverma85 

Thanks for posting this issue.

Would you like to make a PR to implement this?

**Comment by ankurverma85** [comment]
Unfortunately i dont think i have enough skill to implement this

**Comment by Neumann-A** [comment]
2.13.93 is more of a beta release and not a stable version release. As such vcpkg needs to wait for 2.13.4 or 2.14.0 (whatever comes first).
And trying to reproduce the issue the failure seems to occur in pthreads?

**Comment by dg0yt** [comment]
vcpkg has fontconfig 2.13.94 and builds with meson.

**Comment by Cheney-W** [comment]
Solved by PR https://github.com/microsoft/vcpkg/pull/19285
