### ISSUE TITLE
Integrating vcpkg with VS Code

### ISSUE THREAD

**Issue by AayushBoliya** [microsoft/vcpkg#15300]
**Describe the bug**
After cloning vcpkg on C drive, when I command `bootstrap-vcpkg.bat` in the same directory on cmd, it can't find the Visual Studio.

**Environment**
- OS: Windows
- Compiler: Current (25 Dec, 2020)

**To Reproduce**
1. ./vcpkg install in drive same as VS Code dir.
2. Open cmd, command: `bootstrap-vcpkg.bat`  

**Expected behavior**
_**idk**_

**Failure logs** 
`Could not find Visual Studio. VS2015, VS2017, or VS2019 (with C++) needs to be installed.`
`At C:\Program Files\Microsoft Visual Studio\vcpkg\scripts\bootstrap.ps1:143 char:9`
`+         throw "Could not find Visual Studio. VS2015, VS2017, or VS201 ...`
`+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
`    + CategoryInfo          : OperationStopped: (Could not find ...o be installed.:String) [], RuntimeException`
`    + FullyQualifiedErrorId : Could not find Visual Studio. VS2015, VS2017, or VS2019 (with C++) needs to be installed.`

I checked the powershell file at the above address, with above conditional message. I shifted the files to the given address there, and still doesn't work.

**Comment by StarGate-One** [comment]
- VS Code is _**not**_ Visual Studio - you need to download/install Visual Studio to use vcpkg on Windows or use msys2, but vcpkg integrates with Visual Studio on windows well.
- You may need to register, but the Community edition is free.
https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=Community&rel=16
- From within the Visual Studio Installer the minimum needs to be installed:
1. Desktop development with C++
2. Windows SDK
3. English Language Pack
