### ISSUE TITLE
kf5archive:x64-windows build failure

### ISSUE THREAD

**Issue by Hendiadyoin1** [microsoft/vcpkg#15304]
**Host Environment**
- OS: Windows
- Compiler: idk, propably newest msvc as of dec2020

**To Reproduce**
`vcpkg install kf5archive:x64-windows`

**Failure logs** 
CMake Error at ports/kf5archive/portfile.cmake:27 (file):
  file INSTALL cannot find
  "C:/src/vcpkg/buildtrees/kf5archive/src/846e042ef9-c883a6cc46.clean/COPYING.LIB":
  No such file or directory.
Call Stack (most recent call first):
  scripts/ports.cmake:136 (include)

  Package: kf5archive:x64-windows
  Vcpkg version: 2020.11.12-nohash

**Comment by Hendiadyoin1** [comment]
Was able to fix the issue by replacing the "COPYING.LIB" with the "LICNENSES" folder referen e, which actually exists

**Comment by JackBoosY** [comment]
Close this issue via #15314 merged.
