### ISSUE TITLE
FFmpeg can not find zlib, so png support failed.

### ISSUE THREAD

**Issue by AeolusLau** [microsoft/vcpkg#1530]
My env is latest version of windows 10, VS2015, cmake 3.8.2.
I installed zlib by vcpkg first, then I installed ffmpeg. No error occurred.
Then I use ffmpeg to open some kinds of images, BMP, JPEG and WEBP are all OK, but PNG is failed.
The reason is that FFmpeg needs zlib to support PNG, but when building FFmpeg, it can not find zlib, which has already been installed.
Is this a bug, or do I miss some thing?
Any help will be appreciated!

**Comment by AlvinZhangH** [comment]
Hi @AeolusLau How you use ffmpeg to open some kinds of images? Example in FFmpeg/doc/examples/ or another code?

**Comment by AeolusLau** [comment]
@AlvinZhangH I have left that project for about two years, and I'm doing totally different things now. I can't remember the details. Very sorry.

**Comment by AlvinZhangH** [comment]
Please reopen this issue if it still bothers you.
thanks.

**Comment by AlvinZhangH** [comment]
@AeolusLau  Please reopen this issue if it still bothers you.
thanks.

**Comment by rlavarec-gpsw** [comment]
Hello,
We got exactly the same problem.

After installing ffmpeg
> .\vcpkg.exe install --triplet x64-windows ffmpeg[ffmpeg,ffprobe]

And using ffprobe
>  ffprobe -show_format -show_streams -of json -i c:\path_to_media\file.png

It do not give the "pix_fmt" information for png.

Could you please look at it.
Thanks a lot for the great work @vcpkg

Renan

**Comment by rlavarec-gpsw** [comment]
This is not a problem, 
If we add zlib, it will build correctly with it.
` .\vcpkg.exe install --triplet x64-windows ffmpeg[ffmpeg,ffprobe,zlib] `
