### ISSUE TITLE
[New Port Request] libcint

### ISSUE THREAD

**Issue by Hendiadyoin1** [microsoft/vcpkg#15315]
Library name:  libcint

Library description:  
libcint is an open source library for analytical Gaussian integrals.
It provides C/Fortran API to evaluate one-electron / two-electron
integrals for Cartesian / real-spheric / spinor Gaussian type functions.

Source repository URL:  
https://github.com/sunqm/libcint

**Comment by Hendiadyoin1** [comment]
WIP CONTROL File:
```
Source: libcint
Version: 4.0.7
Description: An open source library for analytical Gaussian integrals
Build-Depends:  blas[core]
Homepage: https://github.com/sunqm/libcint
```
WIP portfile.cmake:
```cmake
vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO sunqm/libcint
    HEAD_REF master 
)

vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    OPTIONS 
        -DBUILD_HTML_DOCS=OFF
        -DBUILD_MAN_DOCS=OFF
        -DBUILD_QTHELP_DOCS=OFF
        -DBUILD_TESTING=OFF
)

vcpkg_install_cmake()
vcpkg_fixup_cmake_targets(CONFIG_PATH lib/cmake/libcint)
vcpkg_copy_pdbs()

file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/include)
file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/etc)
file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/etc)
file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/share)
file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)
```
Problems:
- encountering a lot of syntax errors
TODO:
- add REF and SHA256 tags for installation without --head
- readd Prefer ninja line

**Comment by Hendiadyoin1** [comment]
Corresponding Issue in the libraries repo: [link](https://github.com/sunqm/libcint/issues/49)

**Comment by linquize** [comment]
A lot of complex number problem in MSVC.

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
