### ISSUE TITLE
[freetype] build failure

### ISSUE THREAD

**Issue by Zingam** [microsoft/vcpkg#15312]
C:\SDKs\vcpkg>.\vcpkg.exe install freetype  --triplet x64-windows
Computing installation plan...
The following packages will be built and installed:
  * brotli[core]:x64-windows -> 1.0.9
  * bzip2[core]:x64-windows -> 1.0.8#1
    freetype[brotli,bzip2,core,png,zlib]:x64-windows -> 2.10.2#7
  * libpng[core]:x64-windows -> 1.6.37#14
  * zlib[core]:x64-windows -> 1.2.11#9
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
A suitable version of git was not found (required v2.26.2). Downloading portable git v2.26.2...
Downloading git...
  https://github.com/git-for-windows/git/releases/download/v2.26.2.windows.1/PortableGit-2.26.2-32-bit.7z.exe -> C:\SDKs\vcpkg\downloads\PortableGit-2.26.2-32-bit.7z.exe
Extracting git...
A suitable version of 7zip was not found (required v18.1.0). Downloading portable 7zip v18.1.0...
Downloading 7zip...
  https://www.nuget.org/api/v2/package/7-Zip.CommandLine/18.1.0 -> C:\SDKs\vcpkg\downloads\7-zip.commandline.18.1.0.nupkg
Extracting 7zip...
A suitable version of nuget was not found (required v5.5.1). Downloading portable nuget v5.5.1...
Downloading nuget...
  https://dist.nuget.org/win-x86-commandline/v5.5.1/nuget.exe -> C:\SDKs\vcpkg\downloads\22ea847d-nuget.exe
Could not locate cached archive: C:\Users\HH\AppData\Local\vcpkg\archives\6c\6cb774c2f1df4781e4d075e37a3adcb11e72d5ed.zip
Could not locate cached archive: C:\Users\HH\AppData\Local\vcpkg\archives\b2\b2703dcebd24fe0f1e043834d22f4a3c34cad7a5.zip
Could not locate cached archive: C:\Users\HH\AppData\Local\vcpkg\archives\c3\c3e4e9c1d9363bf418d3562ccc1394e06d19fc51.zip
Could not locate cached archive: C:\Users\HH\AppData\Local\vcpkg\archives\34\3422b23e1c00d47b6f963d116da1bc949c718bbd.zip
Could not locate cached archive: C:\Users\HH\AppData\Local\vcpkg\archives\6e\6eeae9f968c934b9c667be426f51c253d229de6c.zip
Starting package 1/5: brotli:x64-windows
Building package brotli[core]:x64-windows...
-- Downloading https://github.com/google/brotli/archive/e61745a6b7add50d380cfd7d3883dd6c62fc2c71.tar.gz...
-- Extracting source C:/SDKs/vcpkg/downloads/google-brotli-e61745a6b7add50d380cfd7d3883dd6c62fc2c71.tar.gz
-- Applying patch install.patch
-- Applying patch fix-arm-uwp.patch
-- Applying patch pkgconfig.patch
-- Using source at C:/SDKs/vcpkg/buildtrees/brotli/src/6c62fc2c71-a8c4ea9278.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_copy_tool_dependencies.cmake:26 (message):
  Could not find PowerShell Core; please open an issue to report this.
Call Stack (most recent call first):
  ports/brotli/portfile.cmake:23 (vcpkg_copy_tool_dependencies)
  scripts/ports.cmake:136 (include)

Error: Building package brotli:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: brotli:x64-windows
  Vcpkg version: 2020.11.12-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by Zingam** [comment]
This maybe related: https://github.com/microsoft/vcpkg/issues/14574

**Comment by JonLiu1993** [comment]
See #8975
The rational behind vcpkg downloading it's own version of powershell is it uses specific commands and/or command syntax that may/may not be found in an older/newer version.

**Comment by JonLiu1993** [comment]
See #8975
The rational behind vcpkg downloading it's own version of powershell is it uses specific commands and/or command syntax that may/may not be found in an older/newer version.

**Comment by Zingam** [comment]
@JonLiu1993 So vcpkg fails to download and install PowerShell?

I had a few libraries installed a while ago. I decided to upgrade them. I did: git pull then run upgrade. The build failed and the libraries got delisted vcpkg list didn't show them any longer. I cleaned up vcpkg and then I tried installing freetype.

**Comment by JonLiu1993** [comment]
@Zingam ,You re-create a folder, then re-git clone vcpkg and try again. I tried again just now, and it can still build normally on my machine.
````
PS F:\test\vcpkg> ./vcpkg install freetype --triplet x64-windows
Computing installation plan...
The following packages will be built and installed:
    freetype[brotli,bzip2,core,png,zlib]:x64-windows -> 2.10.2#7
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\vzhli17\AppData\Local\vcpkg\archives\95\95b35ed12f0104cd1c96b28c22cf85f2865bded4.zip
Starting package 1/1: freetype:x64-windows
Building package freetype[brotli,bzip2,core,png,zlib]:x64-windows...
-- Trying auto-select mirror...
-- Using cached F:/test/vcpkg/downloads/freetype-2.10.2.tar.xz
-- Skipping hash check for F:/test/vcpkg/downloads/freetype-2.10.2.tar.xz.
-- The default mirror is in Disaster Recovery mode, trying other mirrors...
-- Trying mirror cfhcable...
-- Using cached F:/test/vcpkg/downloads/freetype-2.10.2.tar.xz
-- Skipping hash check for F:/test/vcpkg/downloads/freetype-2.10.2.tar.xz.
-- Cleaning sources at F:/test/vcpkg/buildtrees/freetype/src/cf45089bd8-41dc4963c4.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source F:/test/vcpkg/downloads/freetype-2.10.2.tar.xz
-- Applying patch 0001-Fix-install-command.patch
-- Applying patch 0003-Fix-UWP.patch
-- Applying patch pkgconfig.patch
-- Applying patch brotli-static.patch
-- Applying patch fix-exports.patch
-- Using source at F:/test/vcpkg/buildtrees/freetype/src/cf45089bd8-41dc4963c4.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Using msys root at F:/test/vcpkg/downloads/tools/msys2/c809757c94447846
-- Fixing pkgconfig file: F:/test/vcpkg/packages/freetype_x64-windows/lib/pkgconfig/freetype2.pc
-- Fixing pkgconfig file: F:/test/vcpkg/packages/freetype_x64-windows/debug/lib/pkgconfig/freetype2.pc
-- Installing: F:/test/vcpkg/packages/freetype_x64-windows/share/freetype/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\vzhli17\AppData\Local\vcpkg\archives\95\95b35ed12f0104cd1c96b28c22cf85f2865bded4.zip
Building package freetype[brotli,bzip2,core,png,zlib]:x64-windows... done
Installing package freetype[brotli,bzip2,core,png,zlib]:x64-windows...
Installing package freetype[brotli,bzip2,core,png,zlib]:x64-windows... done
Elapsed time for package freetype:x64-windows: 17.36 s

Total elapsed time: 21.08 s

The package freetype:x64-windows provides CMake targets:

    find_package(freetype CONFIG REQUIRED)
    target_link_libraries(main PRIVATE freetype)
````

**Comment by Zingam** [comment]
I noticed that you run your test in PS terminal. I run your command in Windows Terminal PowerShell 7.1 shell too and it succeeded. When it previously failed I used Command Prompt:

PS C:\SDKs\vcpkg> ./vcpkg install freetype --triplet x64-windows
Computing installation plan...
The following packages will be built and installed:
  * brotli[core]:x64-windows -> 1.0.9
  * bzip2[core]:x64-windows -> 1.0.8#1
    freetype[brotli,bzip2,core,png,zlib]:x64-windows -> 2.10.2#7
  * libpng[core]:x64-windows -> 1.6.37#14
  * zlib[core]:x64-windows -> 1.2.11#9
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\HGH\AppData\Local\vcpkg\archives\6c\6cb774c2f1df4781e4d075e37a3adcb11e72d5ed.zip
Could not locate cached archive: C:\Users\HGH\AppData\Local\vcpkg\archives\b2\b2703dcebd24fe0f1e043834d22f4a3c34cad7a5.zip
Could not locate cached archive: C:\Users\HGH\AppData\Local\vcpkg\archives\c3\c3e4e9c1d9363bf418d3562ccc1394e06d19fc51.zip
Could not locate cached archive: C:\Users\HGH\AppData\Local\vcpkg\archives\34\3422b23e1c00d47b6f963d116da1bc949c718bbd.zip
Could not locate cached archive: C:\Users\HGH\AppData\Local\vcpkg\archives\6e\6eeae9f968c934b9c667be426f51c253d229de6c.zip
Starting package 1/5: brotli:x64-windows
Building package brotli[core]:x64-windows...
-- Using cached C:/SDKs/vcpkg/downloads/google-brotli-e61745a6b7add50d380cfd7d3883dd6c62fc2c71.tar.gz
-- Cleaning sources at C:/SDKs/vcpkg/buildtrees/brotli/src/6c62fc2c71-a8c4ea9278.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/SDKs/vcpkg/downloads/google-brotli-e61745a6b7add50d380cfd7d3883dd6c62fc2c71.tar.gz
-- Applying patch install.patch
-- Applying patch fix-arm-uwp.patch
-- Applying patch pkgconfig.patch
-- Using source at C:/SDKs/vcpkg/buildtrees/brotli/src/6c62fc2c71-a8c4ea9278.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz...
-- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst...
-- Using msys root at C:/SDKs/vcpkg/downloads/tools/msys2/c809757c94447846
-- Fixing pkgconfig file: C:/SDKs/vcpkg/packages/brotli_x64-windows/lib/pkgconfig/libbrotlicommon.pc
-- Fixing pkgconfig file: C:/SDKs/vcpkg/packages/brotli_x64-windows/lib/pkgconfig/libbrotlidec.pc
-- Fixing pkgconfig file: C:/SDKs/vcpkg/packages/brotli_x64-windows/lib/pkgconfig/libbrotlienc.pc
-- Fixing pkgconfig file: C:/SDKs/vcpkg/packages/brotli_x64-windows/debug/lib/pkgconfig/libbrotlicommon.pc
-- Fixing pkgconfig file: C:/SDKs/vcpkg/packages/brotli_x64-windows/debug/lib/pkgconfig/libbrotlidec.pc
-- Fixing pkgconfig file: C:/SDKs/vcpkg/packages/brotli_x64-windows/debug/lib/pkgconfig/libbrotlienc.pc
-- Installing: C:/SDKs/vcpkg/packages/brotli_x64-windows/share/brotli/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\HGH\AppData\Local\vcpkg\archives\6c\6cb774c2f1df4781e4d075e37a3adcb11e72d5ed.zip
Building package brotli[core]:x64-windows... done
Installing package brotli[core]:x64-windows...
Installing package brotli[core]:x64-windows... done
Elapsed time for package brotli:x64-windows: 22.18 s
Starting package 2/5: bzip2:x64-windows
Building package bzip2[core]:x64-windows...
-- Fetching https://sourceware.org/git/bzip2.git...
-- Extracting source C:/SDKs/vcpkg/downloads/bzip2-75a94bea3918e612b879d6a11ca64b8689526147.tar.gz
-- Applying patch fix-import-export-macros.patch
-- Using source at C:/SDKs/vcpkg/buildtrees/bzip2/src/8689526147-1ef169fbaa.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Using msys root at C:/SDKs/vcpkg/downloads/tools/msys2/c809757c94447846
-- Fixing pkgconfig file: C:/SDKs/vcpkg/packages/bzip2_x64-windows/lib/pkgconfig/bzip2.pc
-- Fixing pkgconfig file: C:/SDKs/vcpkg/packages/bzip2_x64-windows/debug/lib/pkgconfig/bzip2.pc
-- Installing: C:/SDKs/vcpkg/packages/bzip2_x64-windows/share/bzip2/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\HGH\AppData\Local\vcpkg\archives\b2\b2703dcebd24fe0f1e043834d22f4a3c34cad7a5.zip
Building package bzip2[core]:x64-windows... done
Installing package bzip2[core]:x64-windows...
Installing package bzip2[core]:x64-windows... done
Elapsed time for package bzip2:x64-windows: 9.48 s
Starting package 3/5: zlib:x64-windows
Building package zlib[core]:x64-windows...
-- Downloading http://www.zlib.net/zlib-1.2.11.tar.gz...
-- Extracting source C:/SDKs/vcpkg/downloads/zlib1211.tar.gz
-- Applying patch cmake_dont_build_more_than_needed.patch
-- Applying patch 0001-Prevent-invalid-inclusions-when-HAVE_-is-set-to-0.patch
-- Applying patch add_debug_postfix_on_mingw.patch
-- Using source at C:/SDKs/vcpkg/buildtrees/zlib/src/1.2.11-63309e48e5.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Using msys root at C:/SDKs/vcpkg/downloads/tools/msys2/c809757c94447846
-- Fixing pkgconfig file: C:/SDKs/vcpkg/packages/zlib_x64-windows/lib/pkgconfig/zlib.pc
-- Fixing pkgconfig file: C:/SDKs/vcpkg/packages/zlib_x64-windows/debug/lib/pkgconfig/zlib.pc
-- Installing: C:/SDKs/vcpkg/packages/zlib_x64-windows/share/zlib/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\HGH\AppData\Local\vcpkg\archives\c3\c3e4e9c1d9363bf418d3562ccc1394e06d19fc51.zip
Building package zlib[core]:x64-windows... done
Installing package zlib[core]:x64-windows...
Installing package zlib[core]:x64-windows... done
Elapsed time for package zlib:x64-windows: 8.534 s
Starting package 4/5: libpng:x64-windows
Building package libpng[core]:x64-windows...
-- Downloading https://github.com/glennrp/libpng/archive/v1.6.37.tar.gz...
-- Extracting source C:/SDKs/vcpkg/downloads/glennrp-libpng-v1.6.37.tar.gz
-- Applying patch use_abort.patch
-- Applying patch cmake.patch
-- Applying patch pkgconfig.patch
-- Applying patch pkgconfig.2.patch
-- Applying patch fix-export-targets.patch
-- Applying patch macos-arch-fix.patch
-- Using source at C:/SDKs/vcpkg/buildtrees/libpng/src/v1.6.37-05658d6f1a.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Using msys root at C:/SDKs/vcpkg/downloads/tools/msys2/c809757c94447846
-- Fixing pkgconfig file: C:/SDKs/vcpkg/packages/libpng_x64-windows/lib/pkgconfig/libpng.pc
-- Fixing pkgconfig file: C:/SDKs/vcpkg/packages/libpng_x64-windows/lib/pkgconfig/libpng16.pc
-- Fixing pkgconfig file: C:/SDKs/vcpkg/packages/libpng_x64-windows/debug/lib/pkgconfig/libpng.pc
-- Fixing pkgconfig file: C:/SDKs/vcpkg/packages/libpng_x64-windows/debug/lib/pkgconfig/libpng16.pc
-- Installing: C:/SDKs/vcpkg/packages/libpng_x64-windows/share/libpng/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\HGH\AppData\Local\vcpkg\archives\34\3422b23e1c00d47b6f963d116da1bc949c718bbd.zip
Building package libpng[core]:x64-windows... done
Installing package libpng[core]:x64-windows...
Installing package libpng[core]:x64-windows... done
Elapsed time for package libpng:x64-windows: 9.887 s
Starting package 5/5: freetype:x64-windows
Building package freetype[brotli,bzip2,core,png,zlib]:x64-windows...
-- Trying auto-select mirror...
-- Downloading https://sourceforge.net/projects/freetype/files/freetype2/2.10.2/freetype-2.10.2.tar.xz/download...
-- Skipping hash check for C:/SDKs/vcpkg/downloads/temp/freetype-2.10.2.tar.xz.
-- The default mirror is in Disaster Recovery mode, trying other mirrors...
-- Trying mirror cfhcable...
-- Using cached C:/SDKs/vcpkg/downloads/freetype-2.10.2.tar.xz
-- Skipping hash check for C:/SDKs/vcpkg/downloads/freetype-2.10.2.tar.xz.
-- Extracting source C:/SDKs/vcpkg/downloads/freetype-2.10.2.tar.xz
-- Applying patch 0001-Fix-install-command.patch
-- Applying patch 0003-Fix-UWP.patch
-- Applying patch pkgconfig.patch
-- Applying patch brotli-static.patch
-- Applying patch fix-exports.patch
-- Using source at C:/SDKs/vcpkg/buildtrees/freetype/src/cf45089bd8-41dc4963c4.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Using msys root at C:/SDKs/vcpkg/downloads/tools/msys2/c809757c94447846
-- Fixing pkgconfig file: C:/SDKs/vcpkg/packages/freetype_x64-windows/lib/pkgconfig/freetype2.pc
-- Fixing pkgconfig file: C:/SDKs/vcpkg/packages/freetype_x64-windows/debug/lib/pkgconfig/freetype2.pc
-- Installing: C:/SDKs/vcpkg/packages/freetype_x64-windows/share/freetype/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\HGH\AppData\Local\vcpkg\archives\6e\6eeae9f968c934b9c667be426f51c253d229de6c.zip
Building package freetype[brotli,bzip2,core,png,zlib]:x64-windows... done
Installing package freetype[brotli,bzip2,core,png,zlib]:x64-windows...
Installing package freetype[brotli,bzip2,core,png,zlib]:x64-windows... done
Elapsed time for package freetype:x64-windows: 17.27 s

Total elapsed time: 1.22 min

The package freetype:x64-windows provides CMake targets:

    find_package(freetype CONFIG REQUIRED)
    target_link_libraries(main PRIVATE freetype)

PS C:\SDKs\vcpkg>
PS C:\SDKs\vcpkg>

**Comment by PhoebeHui** [comment]
Duplicated this issue to https://github.com/microsoft/vcpkg/issues/15681.
