### ISSUE TITLE
[New Port Request] GiNaC

### ISSUE THREAD

**Issue by tueda** [microsoft/vcpkg#15313]
Library name: GiNaC

Library description: A C++ library providing an extensive set of algebraic capabilities that are needed for computer algebra systems (symbolic operations on polynomials, mathematical functions, vectors and matrices etc.).

Source repository URL: https://www.ginac.de/ginac.git/

Project homepage (if different from the source repository): https://www.ginac.de/

Anything else that is useful to know when adding (such as optional features the library may have that should be included): GiNac depends on a separate library [CLN](https://www.ginac.de/CLN/), which should be configured with the GNU GMP library for performance gain. (Maybe I should open another issue also for CLN?)

**Comment by FishHe** [comment]
Is there any alternative for GiNaC in VCPKG?

**Comment by FishHe** [comment]
I have found the alternative in my case: **exptk**

**Comment by tueda** [comment]
Yes, `exprtk` or `symengine` may be sufficient for some use cases. But, as far as I know, they haven't implemented operations like partial fraction decomposition (i.e., Wolfram's [Apart](https://reference.wolfram.com/language/ref/Apart.html)) or multivariate polynomial factorisation (Wolfram's [Factor](https://reference.wolfram.com/language/ref/Factor.html)), etc.

**Comment by tueda** [comment]
I have a prototype port [here](https://github.com/tueda/vcpkg/commits/wip-new-port-ginac), which is based on the traditional `./configure` script. (`cln` doesn't support CMake build. `ginac` has `CMakeLists.txt` but it didn't work to me for some reason.) For now, to use this prototype, it requires manually writing some lines of CMake scripts like:
```cmake
find_path(GINAC_INCLUDE_DIRS ginac/ginac.h REQUIRED)
find_library(GINAC_LIBRARY ginac REQUIRED)
find_library(CLN_LIBRARY cln REQUIRED)
find_library(GMP_LIBRARY gmp REQUIRED)

add_executable(main main.cpp)
target_compile_features(main PRIVATE cxx_std_11)
target_include_directories(main PRIVATE ${GINAC_INCLUDE_DIRS})
target_link_libraries(main PRIVATE ${GINAC_LIBRARY} ${CLN_LIBRARY} ${GMP_LIBRARY})
```
This should be improved, but I'm not sure the best way to do that.

**Comment by sfhacker** [comment]
@tueda Can you post here the error message(s) you get when building GiNaC from source on Windows?

Just built the latest version on Windows 10 x64.

![image](https://user-images.githubusercontent.com/25817529/105388128-64102300-5c6a-11eb-89eb-7927352cf848.png)

**Comment by tueda** [comment]
@sfhacker I'm not using Windows for development, so it's on Linux. Errors occurred when I tried to use CMake for GiNaC with my [wip-new-port-ginac-cmake](https://github.com/tueda/vcpkg/commits/wip-new-port-ginac-cmake) branch. [Here](https://gist.githubusercontent.com/tueda/0aaf93482ed23e2eaae74843d5087bfa/raw/5e54d75a410d9c43965d4f6fd6b913a98f4c615d/install-x64-linux-dbg-out.log) is a build log, which sounds the linker flags have some troubles to build executables.

To use GiNaC as a library, building executables is not mandatory. So, a few weeks ago, I tried to patch/intervene to the CMake script (I don't remember what I did exactly) to disable building executables. The build worked, but I think I got a problem that when I tried to build an example using GiNaC installed via vcpkg, CMake was not able to find CLN due to a lack of `FindCLN.cmake`.

**Comment by fknfilewalker** [comment]
@sfhacker How could you get it compile on windows, I just can't wrap my head around it?

**Comment by sfhacker** [comment]
This open issue is OVER a YEAR old!
Anyway, @fknfilewalker Can you post here the steps to repro your issue? Can you also include the error(s) messages you are getting?

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.

**Comment by nook0110** [comment]
@sfhacker (Now it is over 2 years old). 
I think I built a cln, and I'm not sure about that. After that some more obscure libraries are required from me... 
Also, in some files GiNaC includes "function.h", and i have some problems with it.
Preferably, if we could communicate outside this closed-issue.

**Comment by sfhacker** [comment]
@nook0110 Most issues are never never fixed properly and they keep popping up all the time! It is embarrassing.
I am more than happy to assist you. Just drop me a line.

**Comment by nook0110** [comment]
> @nook0110 Most issues are never never fixed properly and they keep popping up all the time! It is embarrassing. I am more than happy to assist you. Just drop me a line.

@sfhacker Cmake wants from me FIG2DEV and MAKEINFO, what is this? (I am not very familiar with cmake...)

**Comment by nook0110** [comment]
Im compiling with msvc (visual studio 17 2022)
MSB3073 "setlocal
"C:\Program Files\CMake\bin\cmake.exe" -DBUILD_TYPE=Debug -P cmake_install.cmake
if %errorlevel% neq 0 goto :cmEnd
:cmEnd
endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
:cmErrorLevel
exit /b %1
:cmDone
if %errorlevel% neq 0 goto :VCEnd
:VCEnd" с кодом 1.	INSTALL	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets	159

**Comment by nook0110** [comment]
I DID IT, HOORAY
@sfhacker Thx you!

**Comment by sfhacker** [comment]
@nook0110 You are ready to work for Microsoft!
