### ISSUE TITLE
[New Port Request] <Cista++>

### ISSUE THREAD

**Issue by Michael1249** [microsoft/vcpkg#15319]
Library name: Cista++

Library description: Cista++ is a simple, open source (MIT license) C++17 compatible way of (de-)serializing C++ data structures.

Source repository URL: https://github.com/felixguendling/cista

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
