### ISSUE TITLE
[libxml2] Build the tools: xmllint, xmlcatalog

### ISSUE THREAD

**Issue by linquize** [microsoft/vcpkg#15311]
libxml2 has tools: `xmllint`, `xmlcatalog`
Let's build them and install to `tools/libxml2`

**Comment by JackBoosY** [comment]
@linquize Do you have official documentation about these 2 tools?

**Comment by linquize** [comment]
http://xmlsoft.org/xmllint.html

http://www.xmlsoft.org/xmlcatalog_man.html

**Comment by JackBoosY** [comment]
@linquize  Do you have build documentation?

**Comment by linquize** [comment]
https://github.com/GNOME/libxml2/blob/79301d3d5e553d46fc3201f48dcec3a93068c5a2/CMakeLists.txt#L516

Simply build xmllint.c into xmllint executable, and xmlcatalog.c into xmlcatalog executable

**Comment by JackBoosY** [comment]
Since libxml2 officially added cmake support this year, I will update it after the next new version is released.

But now, we can completely modify our CMakeLists according to the official CMakeLists.txt.

**Comment by Neumann-A** [comment]
@JackBoosY Close? libxml2 has feature tools now.
