### ISSUE TITLE
[glib] glib-2.0 .pc file contains non-existing include directory 

### ISSUE THREAD

**Issue by traversaro** [microsoft/vcpkg#15326]
**Describe the bug**
The file `installed/x64-linux/debug/lib/pkgconfig/glib-2.0.pc` contains a reference to a non-existing include directory.

**Environment**
- OS: Linux
- Compiler: Not Relevant

**To Reproduce**
1. ./vcpkg install gts:x64-linux
2. Inspect the file `installed/x64-linux/debug/lib/pkgconfig/glib-2.0.pc` . It contains a reference to ` -I"${includedir}/glib-2.0"` that expands to `installed/x64-linux/include/glib-2.0`  `-I"${libdir}/glib-2.0/include"`, that expands to  `installed/x64-linux/debug/lib/glib-2.0/include` . However, both directories do not exists, as the only directory that exists is ``installed/x64-linux/include/glib`.

**Expected behavior**
The `.pc`  file of glib should only contain references to existing directories.

**Failure logs** 
The PR https://github.com/microsoft/vcpkg/pull/11273 fails with the following error due to this bug:
~~~
CMake Error in graphics/src/CMakeLists.txt:
  Imported target "GTS::GTS" includes non-existent path

    "/mnt/vcpkg-ci/installed/x64-linux/debug/lib/pkgconfig/../../../include/glib-2.0"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
~~~

**Additional details** 

Related PR: https://github.com/microsoft/vcpkg/pull/11884 .

**Comment by PhoebeHui** [comment]
@traversaro, thanks for bringing this up! 

I have submitted PR #15360 to fix this issue.

**Comment by traversaro** [comment]
Thanks @PhoebeHui for providing the fix!
