### ISSUE TITLE
How do I add "src" folder to opencv or pcl libraries

### ISSUE THREAD

**Issue by davidbun** [microsoft/vcpkg#15328]
Recently I updated VCPKG to the newest one and now I cannot find the "src" folder under opencv or pcl libraries
How can I build the all the libraries in such a way that I will bring the source cpp files as well?
Thx in advance

**Comment by JackBoosY** [comment]
@davidbun Why do you need to do this? Does src refer to your own code?
I think you should use the `integrate` feature. See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/users/integration.md).

**Comment by davidbun** [comment]
> @davidbun Why do you need to do this? Does src refer to your own code?
> I think you should use the `integrate` feature. See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/users/integration.md).

I would like to see the original source files of the library
I have several libraries that I have "src" folder under "builtrees\port" and some libraries that does not have the src folder inside
Some time looking on the source can explain me in details what is done and why

**Comment by davidbun** [comment]
I have to say, that I fixed the problem by deleting vcpkg folder from users\MyName\Local\AppData
Why does it help?
What did I do that made opencv and pcl libraries missing "src" folder under their "builtrees\port" location?
Just want to know to prevent the same behavior next time
Just to note, both libraries are fully compiled, linked and work well with my code - I just could not see the source code (cpp files of the libraries)
Thx in advance

**Comment by JackBoosY** [comment]
@davidbun Oh I see, that's because you've enabled the `binarycaching` feature.
When you installed this port last time, vcpkg archived the files generated by this port, so if the port has not been changed during the next installation, the cache will be installed directly without building.

And you can use many ways to disable it, such as delete the cache folders(_%LOCALAPPDATA%/vcpkg_).

See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/specifications/binarycaching.md).

**Comment by davidbun** [comment]
> @davidbun Oh I see, that's because you've enabled the `binarycaching` feature.
> When you installed this port last time, vcpkg archived the files generated by this port, so if the port has not been changed during the next installation, the cache will be installed directly without building.
> 
> And you can use many ways to disable it, such as delete the cache folders(_%LOCALAPPDATA%/vcpkg_).
> 
> See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/specifications/binarycaching.md).

I did not enabled binarycaching
Or at least did not wanted to enable it
I will read what does it mean and probably will decide if it is good for me or no
But can you kindly let me know how to disable it (if I really made it enabled)?
Thx a lot in advance

**Comment by JackBoosY** [comment]
@davidbun Because it's enabled automaticlly, please add an environment variable `VCPKG_FEATURE_FLAGS` and set it to `-binarycaching`.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
