### ISSUE TITLE
How do I use mpir library, really?

### ISSUE THREAD

**Issue by one-thunder** [microsoft/vcpkg#15327]
I was following docs and made a simple CMake based solution.

Project **A** - Shared library
Project **B** - Executable

For Project A I successfully used 2 dependencies, `zlib` and `yaml-cpp` which works great as follows:
```cmake
# Add dependencies
find_package(ZLIB REQUIRED)
target_link_libraries(A PRIVATE ZLIB::ZLIB)

find_package(yaml-cpp CONFIG REQUIRED)
target_link_libraries(A PRIVATE yaml-cpp)
```

So when I installed mpir, first I noticed the absence of a short usage sample printed at the end, and when trying different variations of the above code with changed naming for the mpir lib, neither did work.

After reading docs again I found that the libs that don't provide "native" cmake support we should find them manually.
In this is actually the case, my question will be: **How paths should look like when I will be using find_library/find_path, relative or absolute? Because absolute are a no-no for being able to publish it on github**

**Comment by linquize** [comment]
```cmake
find_path(MPIR_INCLUDE_DIR mpir.h)
find_library(MPIR_LIBRARY mpir)
target_include_directories(main PRIVATE ${MPIR_INCLUDE_DIR})
target_link_libraries(main PRIVATE ${MPIR_LIBRARY})
```

**Comment by one-thunder** [comment]
It worked, thanks, any docs on how vcpkg generates `MPIR_INCLUDE_DIR` this variables internally?

**Comment by linquize** [comment]
Create a usage file `ports/mpir/usage` and write the hints.
After `vcpkg install mpir`, it will print the usage file.
