### ISSUE TITLE
[ogre] Cannot open include file

### ISSUE THREAD

**Issue by celadaris** [microsoft/vcpkg#15333]
****

**Is your feature request related to a problem? Please describe.**
when downloading ogre with vcpkg
`./vcpkg install ogre`
 all of the header files are not correctly included, they are all included with quotations "" rather than with brackets <> and the location of the header files are not accurate either. 

for example:
a header in Ogre.h will have this by default
`#include "OgreAnimation.h"`
when it should have
`#include <OGRE/OgreAnimation.h>`

**Proposed solution**
i can rewrite hundreds of header files manually to maybe get ogre to work but a update may break the changes...

**Describe alternatives you've considered**
i'm very new to c++ and i just wanted to dabble with it, sorry...
**Additional context**
i am running on windows 10

**Comment by celadaris** [comment]
I was able to get it running from building the source code in [this](https://youtu.be/5Hi24WnbU-s) helpful guide! It's a long process so if you could get vcpkg to work for ogre it would be cool but I'll be able to work on it on the meantime, so no rush! :)

**Comment by traversaro** [comment]
Hi @celadaris ! How are you consuming OGRE? When OGRE is used from a project with a CMake build system, if I recall correctly the `OGRE` include directories are passed to the compiler, so the `#include "OgreAnimation.h"` works fine.

**Comment by NancyLi1013** [comment]
@traversaro 

Thanks for your focus on this issue.

I also tried to build the project on my local. If I used `#include "OgreAnimation.h"`, which can be compiled successfully.

But if I used #include "OGRE/OgreAnimation.h", which posted C1083 error.

To my confusion, all the headers are installed to _include/OGRE/_ folder and the include path also points to _include/OGRE_ in OGREConfig.cmake:

`get_filename_component(OGRE_INCLUDE_DIRS "${OGRE_PREFIX_DIR}/include/OGRE" ABSOLUTE)`

I used ogre as follows:
```
find_package(OGRE CONFIG REQUIRED)
# Add source to this project's executable.
add_executable (CMakeProject21 "CMakeProject21.cpp" "CMakeProject21.h")
target_link_libraries(CMakeProject21 PRIVATE OgreMain OgreBites OgrePaging OgreVolume)
```

The path in building like this:
```
OGRE_LIBRARY_DIRS:F:/tool/vcpkg/installed/x64-windows/lib
OGRE_INCLUDE_DIRS:F:/tool/vcpkg/installed/x64-windows/include/OGRE
```
So I don't know what's wrong here.

**Comment by celadaris** [comment]
i'm going to re-install it and try and provide better details soon...

**Comment by celadaris** [comment]
perhaps i gave a bad example by specifically mentioning `#include "OgreAnimation.h"` but i have multiple other header files that cannot be opened when trying to use ogre in a very simple manner (which is what is shown in the video). But then after i recorded, i try to manually fix the header files and then more header files show up as errors... the code I've written up is supposed to simply open a black window. i can run the code just fine on my other computer that i built the ogre source code with, but vcpkg gives me errors when i try to use it... I will include a video and a link to the code i used.

https://github.com/celadaris/OgreTutorial/blob/main/OgreTutorial.cpp

https://user-images.githubusercontent.com/12479149/103394306-51804f00-4aed-11eb-8528-a189b1bbfd05.mp4

**Comment by NancyLi1013** [comment]
Hi @celadaris 

Thanks for your test and the video.

Have you tried to update the headers like this?
  
```
#include "Ogre.h"
#include "Bites/OgreApplicationContext.h"
```

**Comment by celadaris** [comment]
yes, here is a pic..
in the meantime I tried running `./vcpkg install ogre:x64-windows` and no luck with that either

![Capture](https://user-images.githubusercontent.com/12479149/103398357-fd339a00-4b01-11eb-9caa-06d83c8a82be.PNG)

**Comment by NancyLi1013** [comment]
It's so weird. I can build successfully if I included the headers without `OGRE`.

**Comment by celadaris** [comment]
it's okay, thanks for your time! i have notifications turned on so I'll be around.

**Comment by celadaris** [comment]
I also should have mentioned that on the build i did with cmake from the source code, it also works without `OGRE` the pic i provided earlier was using vcpkg.

**Comment by NancyLi1013** [comment]
@celadaris 

Sorry for the delay.

Also sorry for my misunderstanding about this issue.

Since `OGRE `subfolder has been included in `OGRE_INCLUDE_DIRS` in OGREConfig.cmake. It's unnecessary to include `OGRE `anymore when using headers.

We just need to use like this: `#include "OgreAnimation.h"`.

So the current behavior is correct. Sorry again for my confusion.

**Comment by celadaris** [comment]
Okay so then referring back to the video I made. How would I get my code to run without errors about opening the source files?

**Comment by NancyLi1013** [comment]
@celadaris @@

Sorry for the long delay.

Could you please help provide your whole project sample here? Have you tried cmake project? Does it work normally?
I will try to reproduce this on my machine and confirm if this is a bug.

**Comment by celadaris** [comment]
hi, sorry for the delay as well. I'm not really sure I understand your latest post because i feel as though the information your asking for has already been presented from when i posted the video. Perhaps it was hard to understand because this is one of the very few times that ive ever tried to work out a code related problem with someone so my posts may not be very well thought out.
 
I'll try to re-answer some of your questions but please let me know if maybe these aren't the answers your looking for, perhaps due to a misunderstanding on my part.

> Could you please help provide your whole project sample here?

[this](https://github.com/celadaris/OgreTutorial/blob/main/OgreTutorial.cpp) is the project sample i wanted to try to run, i said earlier that "the code I've written up is supposed to simply open a black window."

> Have you tried cmake project?

"i can run the code just fine on my other computer that i built the ogre source code with" (i built it with cmake in [this](https://www.youtube.com/watch?v=5Hi24WnbU-s) helpful guide)

> Does it work normally?

yes when it's built with cmake... "but vcpkg gives me errors when i try to use it"

**Comment by NancyLi1013** [comment]
Sorry for the long delay. I have tested your project on my machine. There are some errors.

But the headers should be included like this:

```
#include "Ogre.h"
#include "Bites/OgreApplicationContext.h"
```

And update` #include "OgreRTShaderSystem.h"` as` #include "../RTShaderSystem/OgreRTShaderSystem.h"` in _../Bites/OgreSGTechniqueResolverListener.h_ file.

There are also some build errors like this:

```
ConsoleApplication8.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class Ogre::Root * __thiscall OgreBites::ApplicationContextBase::getRoot(void)const " (__imp_?getRoot@ApplicationContextBase@OgreBites@@QBEPAVRoot@Ogre@@XZ) referenced in function _main
1>ConsoleApplication8.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: void __thiscall OgreBites::ApplicationContextBase::initApp(void)" (__imp_?initApp@ApplicationContextBase@OgreBites@@QAEXXZ) referenced in function _main
1>ConsoleApplication8.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: void __thiscall OgreBites::ApplicationContextBase::closeApp(void)" (__imp_?closeApp@ApplicationContextBase@OgreBites@@QAEXXZ) referenced in function _main
1>ConsoleApplication8.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: virtual void __thiscall OgreBites::ApplicationContextBase::setup(void)" (__imp_?setup@ApplicationContextBase@OgreBites@@UAEXXZ) referenced in function "public: virtual void __thiscall OgreTutorial::setup(void)" (?setup@OgreTutorial@@UAEXXZ)
1>ConsoleApplication8.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __thiscall OgreBites::ApplicationContextSDL::ApplicationContextSDL(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (__imp_??0ApplicationContextSDL@OgreBites@@QAE@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) referenced in function "public: __thiscall OgreTutorial::OgreTutorial(void)" (??0OgreTutorial@@QAE@XZ)
1>ConsoleApplication8.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: virtual __thiscall OgreBites::ApplicationContextSDL::~ApplicationContextSDL(void)" (__imp_??1ApplicationContextSDL@OgreBites@@UAE@XZ) referenced in function "public: virtual __thiscall OgreTutorial::~OgreTutorial(void)" (??1OgreTutorial@@UAE@XZ)
1>ConsoleApplication8.obj : error LNK2001: unresolved external symbol "protected: virtual void __thiscall OgreBites::ApplicationContextSDL::_destroyWindow(struct OgreBites::NativeWindowPair const &)" (?_destroyWindow@ApplicationContextSDL@OgreBites@@MAEXABUNativeWindowPair@2@@Z)
1>ConsoleApplication8.obj : error LNK2001: unresolved external symbol "public: virtual void __thiscall OgreBites::ApplicationContextSDL::addInputListener(struct SDL_Window *,struct OgreBites::InputListener *)" (?addInputListener@ApplicationContextSDL@OgreBites@@UAEXPAUSDL_Window@@PAUInputListener@2@@Z)
1>ConsoleApplication8.obj : error LNK2001: unresolved external symbol "public: virtual void __thiscall OgreBites::ApplicationContextBase::createRoot(void)" (?createRoot@ApplicationContextBase@OgreBites@@UAEXXZ)
1>ConsoleApplication8.obj : error LNK2001: unresolved external symbol "public: virtual struct OgreBites::NativeWindowPair __thiscall OgreBites::ApplicationContextSDL::createWindow(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,unsigned int,unsigned int,class std::map<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,struct std::less<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,class std::allocator<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > >)" (?createWindow@ApplicationContextSDL@OgreBites@@UAE?AUNativeWindowPair@2@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@IIV?$map@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V12@U?$less@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$allocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V12@@std@@@2@@5@@Z)
1>ConsoleApplication8.obj : error LNK2001: unresolved external symbol "public: virtual bool __thiscall OgreBites::ApplicationContextBase::frameEnded(struct Ogre::FrameEvent const &)" (?frameEnded@ApplicationContextBase@OgreBites@@UAE_NABUFrameEvent@Ogre@@@Z)
1>ConsoleApplication8.obj : error LNK2001: unresolved external symbol "public: virtual bool __thiscall OgreBites::ApplicationContextBase::frameRenderingQueued(struct Ogre::FrameEvent const &)" (?frameRenderingQueued@ApplicationContextBase@OgreBites@@UAE_NABUFrameEvent@Ogre@@@Z)
1>ConsoleApplication8.obj : error LNK2001: unresolved external symbol "public: virtual bool __thiscall OgreBites::ApplicationContextBase::frameStarted(struct Ogre::FrameEvent const &)" (?frameStarted@ApplicationContextBase@OgreBites@@UAE_NABUFrameEvent@Ogre@@@Z)
1>ConsoleApplication8.obj : error LNK2001: unresolved external symbol "public: virtual void __thiscall OgreBites::ApplicationContextBase::loadResources(void)" (?loadResources@ApplicationContextBase@OgreBites@@UAEXXZ)
1>ConsoleApplication8.obj : error LNK2001: unresolved external symbol "public: virtual void __thiscall OgreBites::ApplicationContextBase::locateResources(void)" (?locateResources@ApplicationContextBase@OgreBites@@UAEXXZ)
1>ConsoleApplication8.obj : error LNK2001: unresolved external symbol "public: virtual bool __thiscall OgreBites::ApplicationContextBase::oneTimeConfig(void)" (?oneTimeConfig@ApplicationContextBase@OgreBites@@UAE_NXZ)
1>ConsoleApplication8.obj : error LNK2001: unresolved external symbol "public: virtual void __thiscall OgreBites::ApplicationContextSDL::pollEvents(void)" (?pollEvents@ApplicationContextSDL@OgreBites@@UAEXXZ)
1>ConsoleApplication8.obj : error LNK2001: unresolved external symbol "public: virtual void __thiscall OgreBites::ApplicationContextBase::reconfigure(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::map<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,struct std::less<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,class std::allocator<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > > &)" (?reconfigure@ApplicationContextBase@OgreBites@@UAEXABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AAV?$map@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V12@U?$less@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$allocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V12@@std@@@2@@4@@Z)
1>ConsoleApplication8.obj : error LNK2001: unresolved external symbol "public: virtual void __thiscall OgreBites::ApplicationContextSDL::removeInputListener(struct SDL_Window *,struct OgreBites::InputListener *)" (?removeInputListener@ApplicationContextSDL@OgreBites@@UAEXPAUSDL_Window@@PAUInputListener@2@@Z)
1>ConsoleApplication8.obj : error LNK2001: unresolved external symbol "public: virtual void __thiscall OgreBites::ApplicationContextSDL::setWindowGrab(struct SDL_Window *,bool)" (?setWindowGrab@ApplicationContextSDL@OgreBites@@UAEXPAUSDL_Window@@_N@Z)
1>ConsoleApplication8.obj : error LNK2001: unresolved external symbol "public: virtual void __thiscall OgreBites::ApplicationContextSDL::shutdown(void)" (?shutdown@ApplicationContextSDL@OgreBites@@UAEXXZ)
1>ConsoleApplication8.obj : error LNK2001: unresolved external symbol "public: virtual void __thiscall OgreBites::ApplicationContextBase::windowClosed(class Ogre::RenderWindow *)" (?windowClosed@ApplicationContextBase@OgreBites@@UAEXPAVRenderWindow@Ogre@@@Z)
1>ConsoleApplication8.obj : error LNK2001: unresolved external symbol "public: virtual bool __thiscall OgreBites::ApplicationContextBase::windowClosing(class Ogre::RenderWindow *)" (?windowClosing@ApplicationContextBase@OgreBites@@UAE_NPAVRenderWindow@Ogre@@@Z)
1>ConsoleApplication8.obj : error LNK2001: unresolved external symbol "public: virtual void __thiscall OgreBites::ApplicationContextBase::windowFocusChange(class Ogre::RenderWindow *)" (?windowFocusChange@ApplicationContextBase@OgreBites@@UAEXPAVRenderWindow@Ogre@@@Z)
1>ConsoleApplication8.obj : error LNK2001: unresolved external symbol "public: virtual void __thiscall OgreBites::ApplicationContextBase::windowMoved(class Ogre::RenderWindow *)" (?windowMoved@ApplicationContextBase@OgreBites@@UAEXPAVRenderWindow@Ogre@@@Z)
1>ConsoleApplication8.obj : error LNK2001: unresolved external symbol "public: virtual void __thiscall OgreBites::ApplicationContextBase::windowResized(class Ogre::RenderWindow *)" (?windowResized@ApplicationContextBase@OgreBites@@UAEXPAVRenderWindow@Ogre@@@Z)
1>C:\Users\source\repos\ConsoleApplication8\Debug\ConsoleApplication8.exe : fatal error LNK1120: 26 unresolved externals
```

**Comment by ianmanifacier** [comment]
Just in case, you need to make sure your library and your compiler are both either 32 or 64 bits.

**Comment by sauntheninja2** [comment]
I have the same problem anyone found a solution yet seems like i will have to instead use cmake to build the project

**Comment by traversaro** [comment]
> 
> 
> I have the same problem anyone found a solution yet seems like i will have to instead use cmake to build the project

If you refer just to the include problems, I guess that when using a non-CMake build system, a possible workaround is to pass `<vcpkg_dir>/installed/x64-windows/include/OGRE` as additional include path explicitly (change `x64-windows` with your triplet if you are using another triplet).

**Comment by NancyLi1013** [comment]
As @traversaro said above, you need to add `<vcpkg_dir>/installed/x64-windows/include/OGRE` to C/C++ -> General -> Additional Directories explicitly in your MSbuild project. 

For the link error, it is due to lack of `OgreMain.lib`.
Since `OgreMain.lib` is installed in `lib/manual-link` directory, also need to add `<vcpkg_dir>/installed/x64-windows/lib/manual-link/OgreMain.lib` as `Linker-> Input -> Additional Dependencies`.

So we only need to fix the problem that the header cannot be found.

Should update #include "OgreRTShaderSystem.h" as #include "../RTShaderSystem/OgreRTShaderSystem.h" in ../Bites/OgreSGTechniqueResolverListener.h file.

I will submit a PR to fix this.

**Comment by celadaris** [comment]
Hi, i have a couple more issues with ogre. I will try my best to walk you through reproducing the errors that i have, i made a short video on it [here](https://vimeo.com/587369432) sorry for the bad quality, vimeo compressed the video when i uploaded it.

**Comment by NancyLi1013** [comment]
@celadaris 

Thanks for your details.

Seems the original problem that the header file cannot be found and the link error has been solved now, right?

I looked through your video, the current problem you met is that some plugins cannot be built in your project. I noticed that you commented these plugins in plugin.cfg file, then you can continued to build.

Can you provide the link to get `ogre-sdk-v1.12.9-msvc141-x64.zip`?

I can only get the latest version https://www.ogre3d.org/download/sdk/sdk-ogre.

I'm not sure if the problem still exists on the latest version 1.13.0. I need to reproduce this on my local first on the version 1.12.9.

**Comment by celadaris** [comment]
> Seems the original problem that the header file cannot be found and the link error has been solved now, right?

my original problem was that i did not know i had to do the following:
1. add `<vcpkg_dir>/installed/x64-windows/include/OGRE` to C/C++ -> General -> Additional Directories explicitly in MSbuild project.
2. add `<vcpkg_dir>/installed/x64-windows/lib/manual-link/OgreMain.lib` as Linker-> Input -> Additional Dependencies

but your instructions solved that!

As for updating #include "OgreRTShaderSystem.h" as #include "../RTShaderSystem/OgreRTShaderSystem.h" in ../Bites/OgreSGTechniqueResolverListener.h file. that is a new issue that I still have to manually do every time, which i believe you're working on.

The issues I'm having with plugins are non-related to the header file.

I did not realize until just now that there is a page dedicated to downloading previous MSVC SDK builds (as shown in the image), no need for the method i used in the video, [here](https://dl.cloudsmith.io/public/ogrecave/ogre/raw/files/ogre-sdk-v1.12.9-vc15-x64.zip) is the download. If however you would prefer to focus on the latest version of ogre and porting that instead I'm alright with that.

![Screenshot 2021-08-17 234414](https://user-images.githubusercontent.com/12479149/129838334-39b6e26c-29a6-41f0-bc05-4eb24e077689.jpg)

**Comment by NancyLi1013** [comment]
Thanks for your clarification. I will try this on my machine and will update the status once completed.

**Comment by NancyLi1013** [comment]
I can reproduce this on my machine with 1.12.9. But since the .dll files are from external binaries instead of built by vcpkg. 

We recommend to use all the binaries from vcpkg. I noticed these .dll files are also provided by vcpkg. 

So could you please try to copy these .dll files to your project and rebuild this?

**Comment by celadaris** [comment]
copying the .dll files from `vcpkg\installed\x64-windows\bin`  into the name folder of the project worked! i have a black window which is what was originally requested :partying_face:. The original problem is pretty much completely solved

We can close this and make a new thread if u want, but now using resources.cfg causes an error. resources.cfg is needed for anything that you would want to do with ogre besides open a black window.

if you solve this problem and the black window runs then maybe we can try [this](https://github.com/celadaris/NinjaSlash) neat project i made a while back, to test ogre :D (_warning: i did not test it in 1.12.9 so it might not be the best test x.x_)

**Comment by celadaris** [comment]
1. I tried adding all of the additional Include Directories as seen [here](https://pastebin.com/Spm0feun)
2. I tried adding all of the additional Dependencies as seen [here](https://pastebin.com/raMS5tu1)

It helped a little, there's probably something in there that needed to be added, but still results in an error when trying to use resources.cfg maybe im just doing something wrong 🤷‍♂️

**Comment by NancyLi1013** [comment]
I think you can open an new issue to report the new problems you encountered.

**Comment by NancyLi1013** [comment]
Since this is described as expected behavior by Ogre maintainers. there is nothing reasonable vcpkg can do to fix it. MSBuild customers will need to do manual modifications to use Ogre. Please see https://github.com/OGRECave/ogre/issues/2172.
