### ISSUE TITLE
[ glib:x64-osx] build failure

### ISSUE THREAD

**Issue by luisgj2805** [microsoft/vcpkg#15330]
Error: Building package glib:x64-osx failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: glib:x64-osx
  Vcpkg version: 2020.11.12-unknownhash

**Comment by JonLiu1993** [comment]
@luisgj2805 ,Thanks for posting this issue，Can you provide a complete build process and error log? Thank you

**Comment by JonLiu1993** [comment]
Duplicate to #9012
