### ISSUE TITLE
How do I use "cppwinrt"?

### ISSUE THREAD

**Issue by Zingam** [microsoft/vcpkg#15339]
How am I supposed to use cppwinrt? I doesn't seem to integrate into MSVC automatically and I don't see any instructions if I should use find_package?

**Comment by PhoebeHui** [comment]
@Zingam, cppwinrt is header only, if you install winddows sdk, it should contains the headers. In vcpkg, it only check the header file in portfile.cmake. https://github.com/microsoft/vcpkg/blob/master/ports/cppwinrt/portfile.cmake#L1. You can incude the headers #include <winrt/base.h> directly.

**Comment by Zingam** [comment]
@PhoebeHui If that is so then the current package doesn't work with C++20 in MSVC 16.8.

**Comment by BillyONeal** [comment]
@Zingam cppwinrt was moved out of its own distribution channels and into the Windows SDK, so if you're using an update to date Windows SDK the parts should be there.

**Comment by PhoebeHui** [comment]
@Zingam, please reopen this issue if it still be a question for you.

**Comment by Zingam** [comment]
@PhoebeHui If this is a "deprecated" feature/port in VCPKG is it possible to mark it as such or hint the user to use an up-to-date method. The current method seems to be to install a NuGet package but that's not trivial with CMake. There is a feature in CMake to install NuGet packages but MSBuild doesn't support anything but C# so it doesn't work for C++.
https://cmake.org/cmake/help/latest/prop_tgt/VS_PACKAGE_REFERENCES.html
https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files

**Comment by BillyONeal** [comment]
@Zingam The current method is to install a current Windows SDK, not a NuGet package. It normally comes with your compiler https://developer.microsoft.com/en-US/windows/downloads/windows-10-sdk/

**Comment by soumyamahunt** [comment]
What about msbuild?? When I switch to using vcpkg port instead of nuget package I get linking errors. Is the cppwinrt port only for cmake??

**Comment by Zingam** [comment]
@soumyamahunt I find the situation a bit confusing. I read somewhere that "Project Reunion" components will be delivered as NuGet packages. Then it is clear that MSBbuild doesn't support C++ properly. I use CMake because I don't want to support multiple build systems for my cross-platform project. Updates to cppwinrt are delivered via NuGet packages. The latest VS version and the included Windows SDK don't have a cppwinrt version which works with C++20.

**Comment by equeim** [comment]
There is value in having it in vcpkg since C++/WinRT is updated more frequently than Windows SDK and its new versions contain important fixes. For example, latest C++/WinRT version is 17 versions ahead of one shipped with latest version of Windows SDK.

However using cppwinrt from vcpkg is currently broken if some dependency uses C++/WinRT but doesn't have dependency on it in its vcpkg.json, because of linker errors due to mismatched versions:
```
E:\projects\libtremotesf\out\build\windows-multi\Qt6Cored.lib(qlocale_win.cpp.obj) : error LNK2038: mismatch detected for 'C++/WinRT version': value '2.0.220110.5' doesn't match value '2.0.230207.1' in formatters.cpp.obj
```

So having it in vcpkg is not very useful unless all ports that use C++/WinRT actually depend on cppwinrt port.

**Comment by BillyONeal** [comment]
> So having it in vcpkg is not very useful unless all ports that use C++/WinRT actually depend on cppwinrt port.

Can we set up our CI somehow such that the one that comes from the Windows SDK is unavailable so we can detect this rather than silently doing the wrong thing?

**Comment by computerquip-work** [comment]
I'm still unclear on this. I'm trying to use cppwinrt with CMake. Adding the cppwinrt package and including base.h seems to work fine but it's not clear if this is the right way of handling this. I wouldn't mind using the SDK's version (seems to be relatively recent now) but it's not convenient to do so with CMake (without hard coding a variable it seems). I'd also prefer not to rely on Visual Studio functionality.

**Comment by fredemmott** [comment]
The vcpkg version has regressed in the last few months; attempting to use it in previously-working projects now results in:

```
[build] PlatformGUI_windows.obj : error LNK2019: unresolved external symbol WINRT_IMPL_RoOriginateLanguageException referenced in function "private: void __cdecl winrt::hresult_error::originate(struct winrt::hresult,void *,struct std::source_location const &)" (?originate@hresult_error@winrt@@AEAAXUhresult@2@PEAXAEBUsource_location@std@@@Z) [C:\Users\fred\code\OpenXR-API-Layers-GUI\build\src\gui-hklm.vcxproj]
```

**Comment by fredemmott** [comment]
The `Microsoft::CppWinRT` target is missing a dependency on `RuntimeObject.lib`, which provides `RoOriginateLanguageException`; this resolves `WINRT_IMPL_RoOriginateLanguageException` due to an `alternatename` linker pragma deep in the C++/WinRT sources

So, `target_link_libraries("${TARGET}" PRIVATE Microsoft::CppWinRT RuntimeObject)` is what's currently needed.
