### ISSUE TITLE
How do I disable vcpkg for a given project

### ISSUE THREAD

**Issue by soufianekhiat** [microsoft/vcpkg#15347]
Ref issue:
https://github.com/microsoft/vcpkg/issues/281

I would like to disable vcpkg integration only for a given project in a solution.
I tried to add:
```
  <PropertyGroup Label="Globals">
  	<UseVcpkg>No</UseVcpkg>
  </PropertyGroup>
```
On top of the project after:
`<Project DefaultTargets="Build" ToolsVersion="16.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">`
Nevertheless it's still visible on the project setting:
![image](https://user-images.githubusercontent.com/4236325/103229383-294cf080-4933-11eb-85ec-4e398b368938.png)

**Comment by BillyONeal** [comment]
Is this a UI bug or are you actually seeing that project use vcpkg?

**Comment by soufianekhiat** [comment]
It's not seem to be an UI Bug but he really load the wrong API.
Until I switch with the UI to "No".

Tested with Halide builded by myself vs the one from vcpkg (older version).
With:
```
  <PropertyGroup Label="Globals">
  	<UseVcpkg>No</UseVcpkg>
  </PropertyGroup>
```
Visual Studio still use the version from vcpkg.

**Comment by belkiss** [comment]
https://github.com/microsoft/vcpkg/blob/50ea8c0ab7aca3bb9245bba7fc877ad2f2a4464c/scripts/buildsystems/msbuild/vcpkg-general.xml#L16

I think you confused the property Name and DisplayName. So in the vcxproj you need to write `<VcpkgEnabled>false</VcpkgEnabled>`

**Comment by soufianekhiat** [comment]
[Fixed]
My bad thanks.
