### ISSUE TITLE
pcl[cuda]:x64-windows build failure

### ISSUE THREAD

**Issue by matt6801** [microsoft/vcpkg#15348]
**Host Environment**
- OS: Windows 10 Enterprise (10.0.18362 Build 18362)
- Compiler: Microsoft (R) C/C++ Optimizing Compiler Version 19.15.26730 for x64; NVIDIA (R) Cuda compiler driver 10.0.130
- Package: pcl:x64-windows
- Vcpkg version: 2020.11.12-nohash

**To Reproduce**
`./vcpkg install pcl[cuda]:x64-windows`
OR
`./vcpkg install pcl[core,cuda,opengl,tools,vtk]:x64-windows`

**Failure logs** 
- Console messages::
```
Starting package 1/1: pcl:x64-windows
Building package pcl[core,cuda,opengl,tools,vtk]:x64-windows...
-- Using cached C:/vcpkg/downloads/PointCloudLibrary-pcl-d98313133b014553ab1b1b5b112f9aade837d55c.tar.gz
-- Cleaning sources at C:/vcpkg/buildtrees/pcl/src/ade837d55c-34e4d7a2fa.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg/downloads/PointCloudLibrary-pcl-d98313133b014553ab1b1b5b112f9aade837d55c.tar.gz
-- Applying patch pcl_utils.patch
-- Applying patch pcl_config.patch
-- Applying patch use_flann_targets.patch
-- Applying patch boost-1.70.patch
-- Applying patch fix-link-libpng.patch
-- Applying patch remove-broken-targets.patch
-- Applying patch fix-check-sse.patch
-- Applying patch realsense2.patch
-- Using source at C:/vcpkg/buildtrees/pcl/src/ade837d55c-34e4d7a2fa.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:145 (message):
    Command failed: C:/vcpkg/downloads/tools/cmake-3.18.4-windows/cmake-3.18.4-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v -j9
    Working Directory: C:/vcpkg/buildtrees/pcl/x64-windows-dbg
    See logs for more information:
      C:\vcpkg\buildtrees\pcl\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:27 (vcpkg_build_cmake)
  ports/pcl/portfile.cmake:61 (vcpkg_install_cmake)
  scripts/ports.cmake:136 (include)

Error: Building package pcl:x64-windows failed with: BUILD_FAILED
```
- Additional failure log attached.  Information in the attached log, e.g. "C:\vcpkg\installed\x64-windows\include\boost/mpl/not.hpp(47): error: identifier "BOOST_PP_WHILE_2" is undefined" suggests an issue with compiler's use of references to Boost library.
[PCL CUDA Fail Log - install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/5748515/PCL.CUDA.Fail.Log.-.install-x64-windows-dbg-out.log)

**Additional context**
- Running `./vcpkg install pcl[core,opengl,tools,vtk]:x64-windows` (i.e. excluding the cuda feature) allowed pcl to run to completion successfully
- 'Visualization' module is not built, which means the very useful visualization tools are absent from the tools folder.  I'll put some info in here in case someone else Googles this issue.  This is due to PCL not yet supporting VTK 9.  Details can be found in the following issues:

https://github.com/microsoft/vcpkg/issues/11462
https://github.com/microsoft/vcpkg/issues/15130
https://github.com/PointCloudLibrary/pcl/pull/4262
https://github.com/PointCloudLibrary/pcl/issues/4412

- Main reason to compile this was to get cuda support, which cannot be had via the "AllInOne" PCL installer package
- Note that intallation of vtk with the cuda feature a few hours earlier completed successfully on this system.
- NIVIDIA CUDA 10.0 and 11.2 are both installed on this system, including the Development, Runtime and Visual Studio Integration components.
- Boost library version 1.75 is currently installed in the vcpkg repository

**Comment by JackBoosY** [comment]
Please ensure your vcpkg is latest, remove `boost-uninstall` and rebuild pcl.

Thanks.

**Comment by matt6801** [comment]
Sorry, no easy solution to this one : )  Vcpkg and every package within it, including boost, was installed in the context of the same few hours from the sources pointed to by vcpkg.

**Comment by VXallset** [comment]
Hello, I can use vcpkg to install pcl by using `.\vcpkg install pcl[core,opengl,tools,vtk]:x64-windows`. But I got the same problem that  'Visualization' module is not built. I find that the _vtk:x64-windows 9.0.1#3_ version and _pcl[vtk]:x64-windows_ were installed, but there is no visualization subfolder in the _\vcpkg\installed\x64-windows\include\pcl_  folder.
Any suggestions pls?

**Comment by JackBoosY** [comment]
@VXallset Please see #15130.

**Comment by pmdifran** [comment]
@JackBoosY is there any progress on build issues? I'm getting the same build failure when executing:
``` vcpkg install pcl[cuda]:x64-windows```

**Host Environment**
- Windows 10 Pro (Build 19042)
- *not sure where to check my compiler version :)

**Command prompt after installing pcl[cuda] dependencies:**
```
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:146 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j25
    Working Directory: C:/PMD_Working/Dev/Projects/pcl_CUDA/vcpkg/buildtrees/pcl/x64-windows-dbg
    See logs for more information:
      C:\PMD_Working\Dev\Projects\pcl_CUDA\vcpkg\buildtrees\pcl\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:104 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:44 (vcpkg_build_cmake)
  ports/pcl/portfile.cmake:62 (vcpkg_install_cmake)
  scripts/ports.cmake:139 (include)


Error: Building package pcl:x64-windows failed with: BUILD_FAILED
```

**Comment by JackBoosY** [comment]
@pmdifran Can you please provide _C:\PMD_Working\Dev\Projects\pcl_CUDA\vcpkg\buildtrees\pcl\install-x64-windows-dbg-out.log_?

**Comment by JackBoosY** [comment]
@matt6801  Does this issue resolved?

**Comment by pmdifran** [comment]
@JackBoosY I gave it another try today - its installed fine! Thanks for getting back to me. 

It worked with running command prompt regularly, and as admin.
