### ISSUE TITLE
[paho-mqtt] wrong include path

### ISSUE THREAD

**Issue by sandro97git** [microsoft/vcpkg#15349]
****

**Is your feature request related to a problem? Please describe.**
If I link to the target `eclipse-paho-mqtt-c::paho-mqtt3as` the header files can't be found. The `INTERFACE_INCLUDE_DIRECTORIES` point to `/home/sandro/vcpkg/installed/x64-linux/include` whereas the headers are located in `/home/sandro/vcpkg/installed/x64-linux/include/paho-mqtt`.

I want an to inlcude the header files with `#include "MqttAsync.h` and not with `#include "paho-mqtt/MqttAsync.h`

**Proposed solution**
The fix-install-path patch does the following:
```diff
-    DESTINATION ${CMAKE_INSTALL_INCLUDEDIR})
+    DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/paho-mqtt)
```
If this patch is removed it works as expected.
I'm not sure if this is the right solution or if there isn't even a problem at all.
Maybe my expectation is just wrong.

**Comment by JonLiu1993** [comment]
@sandro97git ,Thanks for posting this issue,I created a project under linux environment to link paho-mqtt, and it was not successful, but your problem did not reproduce. Can you provide the CMakeLists.txt and .CPP files you tested? I want to verify your issue before modifying this issue, thank you,

**Comment by sandro97git** [comment]
```c
// main.c
//#include "paho-mqtt/MQTTAsync.h" with this line it works!
#include "MQTTAsync.h"

int main(int argc, char const *argv[])
{
  MQTTAsync client;
  MQTTAsync_create(&client, "ssl://test.mosquitto.org:8883", "paho-test-client-id", MQTTCLIENT_PERSISTENCE_NONE, NULL);
  return 0;
}

```
```
cmake_minimum_required(VERSION 3.10)

# set the project name
project(paho-mqtt-test)

find_package(eclipse-paho-mqtt-c REQUIRED)
find_package(OpenSSL REQUIRED)

get_target_property(include_dir eclipse-paho-mqtt-c::paho-mqtt3as-static INTERFACE_INCLUDE_DIRECTORIES)
message(${include_dir})

# add the executable
add_executable(paho-mqtt-test main.c)
target_link_libraries(paho-mqtt-test PUBLIC eclipse-paho-mqtt-c::paho-mqtt3as-static)

```

**Comment by sandro97git** [comment]
@JonLiu1993 Do you have an update regarding this issue?

**Comment by JonLiu1993** [comment]
@sandro97git ,I am going to submit a new pr to solve this problem.
