### ISSUE TITLE
can't find source file in VS2019

### ISSUE THREAD

**Issue by michealowen** [microsoft/vcpkg#15368]
I use vcpkg successfully build sfml, and i run command ".\vcpkg.exe integrate install". But when i include the headers in my project, the IDE shows "SFML/Window.hpp: No such file or directory".
here is my CMakeLists.txt

[CMakeLists.txt](https://github.com/microsoft/vcpkg/files/5750866/CMakeLists.txt)

I added "SET(CMAKE_TOOLCHAIN_FILE "F:/owen/cpp_workspace/vcpkg/vcpkg-master/scripts/buildsystems/vcpkg.cmake")", but it failed to work.

**Comment by NancyLi1013** [comment]
Hi @michealowen 

Thanks for posting this issue.

Could you please try to update the usage of  `sfml `as follows and then rebuild your project?

```
    find_package(SFML CONFIG REQUIRED)
    # Note: 7 target(s) were omitted.
    target_link_libraries(main PRIVATE FLAC OpenAL OpenGL Vorbis)
```

**Comment by michealowen** [comment]
> Hi @michealowen
> 
> Thanks for posting this issue.
> 
> Could you please try to update the usage of `sfml `as follows and then rebuild your project?
> 
> ```
>     find_package(SFML CONFIG REQUIRED)
>     # Note: 7 target(s) were omitted.
>     target_link_libraries(main PRIVATE FLAC OpenAL OpenGL Vorbis)
> ```

I added "target_link_libraries(SimpleNES sfml-window sfml-graphics sfml-audio)" and now it worked. Thanks for your advice.

**Comment by NancyLi1013** [comment]
Since this issue has been solved, I'm closing this issue for now.
