### ISSUE TITLE
[openimageio:x86-windows] build failure

### ISSUE THREAD

**Issue by wiedziorek** [microsoft/vcpkg#15369]
**Host Environment**
- Windows 10 Pro. My machine is using the en-us locale.
- Visual Studio 2019 16.8.3
- Windows SDK 10.0.19041

**To Reproduce**
- Steps to reproduce the behavior:
`.\vcpkg install openimageio[pybind11]`

**Failure logs** 
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:145 (message):
    Command failed: C:/Users/Kamil/Downloads/vcpkg-master/downloads/tools/cmake-3.19.2-windows/cmake-3.19.2-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v -j13
    Working Directory: C:/Users/Kamil/Downloads/vcpkg-master/buildtrees/openimageio/x86-windows-dbg
      C:\Users\Kamil\Downloads\vcpkg-master\buildtrees\openimageio\install-x86-windows-dbg-out.log
Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:27 (vcpkg_build_cmake)
  ports/openimageio/portfile.cmake:66 (vcpkg_install_cmake)
  scripts/ports.cmake:136 (include)
Error: Building package openimageio:x86-windows failed with: BUILD_FAILED

**Additional context**
- I ensured that I'm using the latest profiles with `.\vcpkg update`.

**Log file**
[install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/5750890/install-x86-windows-dbg-out.log)

**Comment by JackBoosY** [comment]
Can you please provide your Visual Studio version (16.*.*)?

**Comment by JackBoosY** [comment]
Confirmed.

**Comment by JackBoosY** [comment]
This should be a upstream bug.
The definition of `copysign` conflicts with the definition in the Windows SDK ucrt component (_ucrt\corecrt_math.h_).

**Comment by JackBoosY** [comment]
Python officially fixed this issuein https://github.com/python/cpython/commit/9cc9e277254023c0ca08e1a9e379fd89475ca9c2 by removing the macro definition `copysign`.

**Comment by wiedziorek** [comment]
Hi JackBoosY, thank you for your reply :)

I am using:
Visual Studio 2019 16.8.3
Windows SDK 10.0.19041

**Comment by JackBoosY** [comment]
The upstream is trying to fix this issue now.

**Comment by ras0219-msft** [comment]
Should be fixed in the latest master!
