### ISSUE TITLE
«Lt;port name»gt;» сбой сборки

### ISSUE THREAD

**Issue by irinazheltisheva** [microsoft/vcpkg#15367]
**Host Environment**
- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**
`./vcpkg install xxxx`

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by JackBoosY** [comment]
Invalid issue.
