### ISSUE TITLE
[antlr4,python3] Conflicting ports

### ISSUE THREAD

**Issue by BillyONeal** [microsoft/vcpkg#15377]
Repro:

```
vcpkg.exe install antlr4
vcpkg.exe install python3 --editable
```

results in output like:

```
     3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29333\include\cstdint(21,1): error C2061: syntax error: identifier 'std' [D:\buildtrees\python3\x86-windows-rel\v3.9.0-664bf2a259.clean\PCbuild\pythoncore.vcxproj]
     3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29333\include\cstdint(21,1): error C2059: syntax error: ';' [D:\buildtrees\python3\x86-windows-rel\v3.9.0-664bf2a259.clean\PCbuild\pythoncore.vcxproj]
```

This is why the python3 port currently fails in our ci.

This is because Python wants to use a header named "token.h", and Antlr installs a Token.h. I got a preprocessed python file from both environments and diffed them to get this result; the broken build is on the left and the working one is on the right:

![image](https://user-images.githubusercontent.com/1544943/103313581-5a7dfd00-49d5-11eb-9a70-08cdd2c5342f.png)

**Comment by BillyONeal** [comment]
This regression was probably caused by building the python interpreter added in https://github.com/microsoft/vcpkg/pull/14891 ; the right fix is probably to patch Python's build scripts to put its own include directories in front of vcpkg's include directories.

**Comment by Hoikas** [comment]
In the python3 port, the python_vcpkg.props.in file is used to massage the python build system into something we can use. It currently has this snippet:
```xml
      <AdditionalIncludeDirectories>
        ${CURRENT_INSTALLED_DIR}/include;%(AdditionalIncludeDirectories)
      </AdditionalIncludeDirectories>
```

Would inverting that to:
```xml
      <AdditionalIncludeDirectories>
        %(AdditionalIncludeDirectories);${CURRENT_INSTALLED_DIR}/include
      </AdditionalIncludeDirectories>
```

be sufficient? I'm not certain what the fully expanded value of `AdditionalIncludeDirectories` is. :/

**Comment by BillyONeal** [comment]
@Hoikas Yes, that's what I landed on. (I first tried adding PySrcDir\Include in front but after seeing that we never hydrate PySrcDir\externals decided that was a better fix)

**Comment by Hoikas** [comment]
Right, I discovered as part of #14891 that the vendored dependencies (and worse, the in-repo vendored dependencies) caused non-determinant failures similar to this one. Thanks for sniffing this out!

**Comment by BillyONeal** [comment]
@Hoikas What vendored dependencies? As far as I can tell they're all supposed to come from $/externals but we never hydrate that.

**Comment by Hoikas** [comment]
Python has an in-repo copy of zlib and expat, but that's all untangled by the patches.
