### ISSUE TITLE
Failed to download file  | boost-math:x64-windows

### ISSUE THREAD

**Issue by pengguanjun** [microsoft/vcpkg#15370]
Host Environment

```
OS: [Windows]
Compiler: VS2017
```
To Reproduce
`.\vcpkg.exe install boost-math:x64-windows`

I don't know how to act this:
` If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment`

```
Starting package 1/49: boost-math:x64-windows
Building package boost-math[core]:x64-windows...
-- Downloading https://github.com/boostorg/math/archive/boost-1.75.0.tar.gz...
-- Downloading https://github.com/boostorg/math/archive/boost-1.75.0.tar.gz... Failed. Status: 18;"Transferred a partial file"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:184 (message):

      **Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment**
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:147 (vcpkg_download_distfile)
  ports/boost-math/portfile.cmake:3 (vcpkg_from_github)
  scripts/ports.cmake:136 (include)
Error: Building package boost-math:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-math:x64-windows
  Vcpkg version: 2020.11.12-nohash
```

**Comment by PhoebeHui** [comment]
@pengguanjun, If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment variables to "https://user:password@your-proxy-ip-address:port/"

http://cmake.3232098.n2.nabble.com/ExternalProject-Add-and-proxy-td7591815.html

**Comment by pengguanjun** [comment]
@PhoebeHui 
Thx, I use win system only, maybe I will try your method in linux of cloud server.
I solved it in this way:
I got the file name in dir of C:\vcpkg\downloads\temp, and downloaded it by web to https://github.com/boostorg/math/archive/boost-1.75.0.tar.gz.
And I tried to rename pkgs manually. After rename step, I replaced it in dir of C:\vcpkg\downloads.
It worked, but silly and slow.

**Comment by wirusoal** [comment]
The same problem occurs when loading this link through a browser. The download is interrupted.

**Comment by PhoebeHui** [comment]
You can reference the solution from similar issue https://github.com/microsoft/vcpkg/issues/13348, it really depends on the network environment that time, you can try again when it interrupted.
