### ISSUE TITLE
Prefab export: invalid Java package name

### ISSUE THREAD

**Issue by baarmaley** [microsoft/vcpkg#15376]
**Describe the bug**
if the name package contains a '-' character (eg "boost-endian") then the generated package name will be wrong in AndroidManifest.xml

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.vcpkg.ndk.support.boost-endian" a>
    <uses-sdk android:minSdkVersion="16" android:targetSdkVersion="29" />
</manifest>
```

https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html

**Environment**

- OS: Ubuntu 20.04.1 LTS
- Compiler: gcc 9.3.0

**To Reproduce**
1. ./vcpkg install boost-endian:arm-android boost-endian:arm64-android boost-endian:x86-android boost-endian:x64-android
1. ./vcpkg export --triplet x64-android boost-endian --prefab --prefab-maven --prefab-debug
1. add implementation 'com.vcpkg.ndk.support:boost-endian:1.75.0' in app/build.gradle
1. click build in android studio

**Expected behavior**
Build success.

**Failure logs** 

```
> Task :app:processDebugResources FAILED

Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Package 'com.vcpkg.ndk.support.boost-endian' from AndroidManifest.xml is not a valid Java package name as 'boost-endian' is not a valid Java identifier.
```

**Comment by JackBoosY** [comment]
Lack of android knowledge, @vicroms can you please take a look?

Thanks.

**Comment by holmescn** [comment]
I am meetting the same issue. but this is an error of [vcpkg-tool](https://github.com/microsoft/vcpkg-tool). There are some errors there and I am trying to fix them.

**Comment by baarmaley** [comment]
I don't think doing it manually is the solution to the problem. :)

**Comment by JackBoosY** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
