### ISSUE TITLE
expat build failure

### ISSUE THREAD

**Issue by tihohod** [microsoft/vcpkg#15382]
**Host Environment**
- OS: [Windows]
- Compiler: Visual Studio 2019

**To Reproduce**
`./vcpkg install expat`

**Failure logs** 
D:\HLDI_new\Watson\vcpkg>vcpkg owns expat                                                                              
 expat:x64-windows-static: x64-windows-static/debug/lib/libexpatdMD.lib                                                  
 expat:x64-windows-static: x64-windows-static/lib/libexpatMD.lib

**Additional context**
Tried to use expat in my project, but after installing it into vcpkg repository using x64-windows-static triplet, I discovered that libexpatMD.lib libraries (that use dll crt) were built instead of MT versions, as this triplet requires. This makes expat from vcpkg repo unusable in my project.

**Comment by JackBoosY** [comment]
I think it's just the library name wrong.

**Comment by JackBoosY** [comment]
vcpkg will automatically detect the CRT linkage of the library after the build, so you don’t need to worry about that.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
