### ISSUE TITLE
vcpkg federation stabilization

### ISSUE THREAD

**Issue by BillyONeal** [microsoft/vcpkg#15381]
Currently we make concurrent edits to the tool, to scripts, and to the ports tree, but as we do federation, we lose the ability to make such edits. We need to arrive at a solution to allow us to detect problematic behavior, and potentially make improvements to the portfile authoring experience.

This issue contains a list of potential changes we would want to make; we'll revisit this issue when designing whatever system we end up doing.

* We want to increase the set of banned names (like `token.h`) because we have evidence those names break customers.
* We want to make `PREFER_NINJA` the default for `vcpkg_configure_cmake`.
* We want to make `vcpkg_test_cmake` do something.

**Comment by Neumann-A** [comment]
- Better crosscompiling strategy/design? (Requires at least #15424)

> We want to make PREFER_NINJA the default for vcpkg_configure_cmake.

probably with a global escape hatch like VCPKG_NO_NINJA or defining the cmake generator globally in the triplet.

**Comment by JackBoosY** [comment]
Related #15173.

**Comment by JackBoosY** [comment]
> We want to make PREFER_NINJA the default for vcpkg_configure_cmake.
Will be resolved in the near future.

**Comment by BillyONeal** [comment]
@strega-nil did this
