### ISSUE TITLE
[New Port Request] LibGamerzilla

### ISSUE THREAD

**Issue by dulsi** [microsoft/vcpkg#15380]
Library name: libgamerzilla

Library description:
Gamerzilla is trophy/achievement system for games. It integrates with a
hubzilla plugin to display your results online. Games can either connect
directly to hubzilla or connect to a game launcher with using this
library.

Source repository URL: https://github.com/dulsi/libgamerzilla

Project homepage (if different from the source repository): http://identicalsoftware.com/gamerzilla/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
I've built the library and am willing to incorporate changes if I can to add it to vcpkg. I will not be able to contribute directly due to the Contributor License Agreement.

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
