### ISSUE TITLE
[Brotli] build failure

### ISSUE THREAD

**Issue by Spejik** [microsoft/vcpkg#15397]
**Host Environment**
- OS: Debian 10
- Compiler: Probably gcc or g++

**To Reproduce**
`./vcpkg install pngwriter`

**Failure logs** 
-Cut and paste the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.
https://pastebin.com/Fe8Jx7V2

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.
Executing vcpkg with sudo, updating vcpkg, installing just brotli

**Comment by Hoikas** [comment]
```
  Could not find pkg-config.  Please install it via your package manager:
 
      sudo apt-get install pkg-config
```

**Comment by NancyLi1013** [comment]
Hi @Spejik 

Thanks for posting this issue.

Could you please try to install pkg-config via `sudo apt-get install pkg-config` and rebuild this port?

@Hoikas 

Thanks for your help.

**Comment by Spejik** [comment]
@NancyLi1013 Oh, I didn't notice that. I installed it and now it works. Thanks
