### ISSUE TITLE
mingw64 build error 

### ISSUE THREAD

**Issue by ccaza** [microsoft/vcpkg#15392]
My compile toochan is mysy2 mingw64 .

# config cmake .
   cd toolsrc && cmake -G "MinGW Makefiles" -B build  -S .  -DCMAKE_BUILD_TYPE=Release 
# build vcpkg 
   cmake --build build 

# get some  errors : 
     ....... 
     ../include/vcpkg/base/files.h:49:17: note:   candidate expects 1 argument, 2 provided

# fix it at file src/vcpkg/commands.edit.cpp

 bfore  - line 212 :   candidate_paths.push_back(fs::u8path(first,comma));

 //  need call .base() method for  mingw64 .
 afer   + line 212 :   candidate_paths.push_back(fs::u8path(first.base(),comma.base()));

// now i can compile success vcpkg .

so , we need  fix it  for  mingw64 toolchan .

**Comment by JackBoosY** [comment]
I think anyway, you have to use `bootstrap-vcpkg` script to build vcpkg instead of calling CMakeLists.txt in _toolsrc_ directly.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
