### ISSUE TITLE
Error: Building package protobuf:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by walterdelavega** [microsoft/vcpkg#15399]
I can´t install opencv using vcpkg, i have this message:
Building package protobuf:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: protobuf:x64-windows
  Vcpkg version: 2020.02.04-nohash-external

Thanks for your help!

**Comment by JackBoosY** [comment]
More information please? 
Can you provide the failure logs?

**Comment by walterdelavega** [comment]
Thanks for your answerer, this is error log:
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: C:/Users/walte/OneDrive/Documents/c++/visualStudio_projectsVega/libc_vega/instaladorBibiotecas/vcpkg-master/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v
    Working Directory: C:/Users/walte/OneDrive/Documents/c++/visualStudio_projectsVega/libc_vega/instaladorBibiotecas/vcpkg-master/buildtrees/protobuf/x64-windows-dbg
    See logs for more information:
      C:\Users\walte\OneDrive\Documents\c++\visualStudio_projectsVega\libc_vega\instaladorBibiotecas\vcpkg-master\buildtrees\protobuf\install-x64-windows-dbg-out.log
      C:\Users\walte\OneDrive\Documents\c++\visualStudio_projectsVega\libc_vega\instaladorBibiotecas\vcpkg-master\buildtrees\protobuf\install-x64-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/protobuf/portfile.cmake:53 (vcpkg_install_cmake)
  scripts/ports.cmake:90 (include)


ninja: error: mkdir(CMakeFiles/libprotobuf-lite.dir/C_/Users/walte/OneDrive/Documents/c++/visualStudio_projectsVega/libc_vega/instaladorBibiotecas): No such file or directory
Thank you!

**Comment by JackBoosY** [comment]
_C:\Users\walte\OneDrive\Documents\c++\visualStudio_projectsVega\libc_vega\instaladorBibiotecas\vcpkg-master\buildtrees\x64-windows-dbg\CMakeFiles/libprotobuf-lite.dir/C_/Users/walte/OneDrive/Documents/c++/visualStudio_projectsVega/libc_vega/instaladorBibiotecas_
The path is too long, pleaes clone vcpkg in root dir.

**Comment by walterdelavega** [comment]
Thank you so much, i will try, i just installed in the c:\ file program\opencv
nthen i was setting visual studio, now it are working good, but i am not sure if it is this correct way, for build my project in c++, using visual studio, because i need use opencv library for use in c++.

clone vcpkg in root dir. you mind, i need clone in C:\program Files?
Thank you so much!

**Comment by JackBoosY** [comment]
@walterdelavega Please do not use the path contains empty space, because although vcpkg supports paths with spaces, some ports do not. And don't clone vcpkg in a path that contains non-ascii codes for the same reason as above.

**Comment by ALittleDruid** [comment]
> Thank you so much, i will try, i just installed in the c:\ file program\opencv
> nthen i was setting visual studio, now it are working good, but i am not sure if it is this correct way, for build my project in c++, using visual studio, because i need use opencv library for use in c++.
> 
> clone vcpkg in root dir. you mind, i need clone in C:\program Files?
> Thank you so much!

clone vcpkg in C:\vcpkg

**Comment by JackBoosY** [comment]
Hi @walterdelavega, is this issue resolved?

**Comment by PhoebeHui** [comment]
@walterdelavega, please reopen this issue if it still be a problem for you.

**Comment by walterdelavega** [comment]
Thanks for write me,
I solved this issue, the address location for access the package it was
very long, i change th location in the troy of system, it solved that
problem.
Best regards,
