### ISSUE TITLE
[wxWidgets] non-static builds are missing regex and scintilla  .lib

### ISSUE THREAD

**Issue by jjYBdx4IL** [microsoft/vcpkg#15403]
**Host Environment**
- OS: win10 amd64
- Compiler: latest MSVC 2019

**To Reproduce**
any non-static x64/x86 install

**Failure logs** 
<pre>
$ cd vcpkg/installed
$ find . -wholename '*lib*regex*'
./x64-windows-static/debug/lib/wxregexud.lib
./x64-windows-static/lib/wxregexu.lib
./x86-windows-static/debug/lib/wxregexud.lib
./x86-windows-static/lib/wxregexu.lib

$ find . -wholename '*bin*regex*'
[nothing]
</pre>
**Additional context**
The upstream build (for comparison) builds and installs wxregex(ud).lib files into wxWidgets/lib/vc_dll. There is, however, no correspondingly named regex .dll file in the upstream build.

Upstream (wxwidgets 3.1.4 github repo) build result:
<pre>
E:\dev\wxWidgets\lib\vc_dll>dir *.dll *.lib

 Directory of E:\dev\wxWidgets\lib\vc_dll

31.12.2020  11:34           303.616 wxbase314ud_net_vc_custom.dll
31.12.2020  11:34         3.834.880 wxbase314ud_vc_custom.dll
31.12.2020  11:37           312.320 wxbase314ud_xml_vc_custom.dll
31.12.2020  11:36            36.864 wxmsw314ud_adv_vc_custom.dll
31.12.2020  11:37           932.864 wxmsw314ud_aui_vc_custom.dll
31.12.2020  11:36        12.324.352 wxmsw314ud_core_vc_custom.dll
31.12.2020  11:38           150.016 wxmsw314ud_gl_vc_custom.dll
31.12.2020  11:36         1.069.056 wxmsw314ud_html_vc_custom.dll
31.12.2020  11:36           203.776 wxmsw314ud_media_vc_custom.dll
31.12.2020  11:37         1.227.776 wxmsw314ud_propgrid_vc_custom.dll
31.12.2020  11:37           233.984 wxmsw314ud_qa_vc_custom.dll
31.12.2020  11:37           599.552 wxmsw314ud_ribbon_vc_custom.dll
31.12.2020  11:38         2.616.320 wxmsw314ud_richtext_vc_custom.dll
31.12.2020  11:38         2.462.720 wxmsw314ud_stc_vc_custom.dll
31.12.2020  11:36           275.968 wxmsw314ud_webview_vc_custom.dll
31.12.2020  11:37         1.211.392 wxmsw314ud_xrc_vc_custom.dll

 Directory of E:\dev\wxWidgets\lib\vc_dll

31.12.2020  11:34         3.102.364 wxbase31ud.lib
31.12.2020  11:34           119.270 wxbase31ud_net.lib
31.12.2020  11:37            35.370 wxbase31ud_xml.lib
31.12.2020  11:33           500.382 wxexpatd.lib
31.12.2020  11:33           797.774 wxjpegd.lib
31.12.2020  11:36             2.134 wxmsw31ud_adv.lib
31.12.2020  11:37           719.860 wxmsw31ud_aui.lib
31.12.2020  11:36         7.515.910 wxmsw31ud_core.lib
31.12.2020  11:38            47.632 wxmsw31ud_gl.lib
31.12.2020  11:36           568.594 wxmsw31ud_html.lib
31.12.2020  11:36           101.392 wxmsw31ud_media.lib
31.12.2020  11:37           852.244 wxmsw31ud_propgrid.lib
31.12.2020  11:37            22.914 wxmsw31ud_qa.lib
31.12.2020  11:37           316.346 wxmsw31ud_ribbon.lib
31.12.2020  11:38         1.722.140 wxmsw31ud_richtext.lib
31.12.2020  11:38           327.556 wxmsw31ud_stc.lib
31.12.2020  11:36            56.020 wxmsw31ud_webview.lib
31.12.2020  11:37           367.932 wxmsw31ud_xrc.lib
31.12.2020  11:33           924.248 wxpngd.lib
31.12.2020  11:33           224.192 wxregexud.lib
31.12.2020  11:34        19.575.658 wxscintillad.lib
31.12.2020  11:33         1.215.740 wxtiffd.lib
31.12.2020  11:33           230.598 wxzlibd.lib
              39 File(s)     67.141.726 bytes
               0 Dir(s)  464.901.242.880 bytes free
</pre>

Looking at the vcpkg buildtrees folders I can see that regex (and scintilla) libs get built. So it seems to be effectively only an installation stage problem.

**Comment by JackBoosY** [comment]
`wxregex` is indeed generated during non-static build, but due to upstream rules, these built-in libraries will not be installed during dynamic build.

See https://github.com/wxWidgets/wxWidgets/blob/b58ee58a7bf7a954a34680d3765f42fffd962860/build/cmake/functions.cmake#L510-L512

If you still think that's a bug, please report it to the upstream.

Thanks.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
