### ISSUE TITLE
prometheus-cpp update to v0.11.0

### ISSUE THREAD

**Issue by draveness** [microsoft/vcpkg#15406]
Library name: prometheus-cpp

New version number: v0.11.0

Other information that may be useful (release notes, etc...)

https://github.com/jupp0r/prometheus-cpp

**Comment by JonLiu1993** [comment]
@draveness , Thanks for posting this issue,I noticed that the latest version of prometheus-cpp has been v0.11.0, you can update the latest vcpkg and try to build and use, I will close this issue
