### ISSUE TITLE
Multiple License

### ISSUE THREAD

**Issue by atkawa7** [microsoft/vcpkg#1540]
Just wondering how does vcpkg support  ports  with multiple licenses

**Comment by ras0219-msft** [comment]
In the end, it is always up to the user to correctly obey the license(s).

However, we make a best effort attempt to provide all the material they need inside the share folder, ideally as a file named copyright.

Therefore, I think we should
- Always install the more permissive license as `copyright` (if it is obvious)
- Make the other license available as an alternative file; perhaps `copyright.GPLv3` or whatever is appropriate.

**Comment by LilyWangL** [comment]
This issue hasn’t been updated in a year, if it is still an issue, please reopen.
