### ISSUE TITLE
How do I update vcpkg itself?

### ISSUE THREAD

**Issue by XsongyangX** [microsoft/vcpkg#15417]
I looked at the FAQ of "readthedocs" and I can't find a clear way of updating vcpkg itself. Can someone tell me the procedure?

**Comment by VegeHime** [comment]
git pull & run bootstrap-vcpkg.bat (on Windows)

**Comment by talregev** [comment]
Can you add the answer to the main readme file in the repo?

**Comment by XsongyangX** [comment]
Once added to the readme and faqs docs, close the issue

**Comment by JackBoosY** [comment]
Any project on github uses `git pull` to pull the latest changes, so I don't think it needs to be added to the document.

**Comment by XsongyangX** [comment]
But bootstrapping is not for any github project

**Comment by JackBoosY** [comment]
@XsongyangX  If there are major changes to vcpkg, an error will be reported when installing any port: you must rebuild vcpkg first using bootstrap.

**Comment by talregev** [comment]
It not good enough. I didn't remember I needed to do git pull to update vcpkg itself.
First I searched in main readme file how to do it, then  I searched in google how to do it.
Until I got it here. It take me some time. And it not the first issue that open about it.
It confusing. Even it not confusing, why not to put this vital information on the readme file?

Also I will add a feature request that there will be command in vcpkg itself to update iteslf.
Don't count on user git, when bootstrap you can download portable git and use it, like you do in case of cmake.

Please open the issue that other can see the request.

**Comment by JackBoosY** [comment]
cc @vicroms
