### ISSUE TITLE
Improve the output after installed  a package

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [microsoft/vcpkg#15414]
****

**Is your feature request related to a problem? Please describe.**
This feature request is actually very lightweight. Right now when you installed a package, vcpkg outputs this when it completed.
```
The package cpr:x64-windows provides CMake targets:

    find_package(cpr CONFIG REQUIRED)
    target_link_libraries(main PRIVATE cpr)
```
Quite often you need to change the `main` part to your project name.  Considering cmake already provided the variable `${PROJECT_NAME}`, why not change `target_link_libraries(main PRIVATE cpr)` to `target_link_libraries(${PROJECT_NAME} PRIVATE cpr)`?

**Proposed solution**
After installed a package, output something like this:
```
find_package(cpr CONFIG REQUIRED)
target_link_libraries(${PROJECT_NAME} PRIVATE cpr)
```

**Comment by JackBoosY** [comment]
Because a project may contain many targets, and `PROJECT_NAME` only refers to one of them.

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
Yes, but `main` also only refers to one of them and is a fixed literal. Maybe  `PROJECT_NAME` is a little bit useful than `main`?

**Comment by JackBoosY** [comment]
@0x7FFFFFFFFFFFFFFF We will have a discuss later.
