### ISSUE TITLE
[New Port Request] HElib

### ISSUE THREAD

**Issue by tosone** [microsoft/vcpkg#15418]
Library name:

HElib

Library description:

HElib is an open-source software library that implements homomorphic encryption. It supports the BGV scheme with bootstrapping and the Approximate Number CKKS scheme. HElib also includes optimizations for efficient homomorphic evaluation, focusing on effective use of ciphertext packing techniques and on the Gentry-Halevi-Smart optimizations.

Source repository URL:

https://github.com/homenc/HElib

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
