### ISSUE TITLE
.\vcpkg install darknet[full]:x64-windows build failure

### ISSUE THREAD

**Issue by wivach** [microsoft/vcpkg#15412]
**Host Environment**
- OS: [Windows 10]
- Compiler: 2020.11.12-nohash

**To Reproduce**
.\vcpkg install darknet[full]:x64-windows

(base) PS C:\Users\XXXX\vcpkg> .\vcpkg install darknet[full]:x64-windows
Computing installation plan...
The following packages will be built and installed:
    darknet[core,cuda,cudnn,full,opencv-cuda,weights,weights-train]:x64-windows -> 2020-08-30#1
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\XXXX\AppData\Local\vcpkg\archives\a4\a46d6226e9b18296bc258b72fe4914a129c365ff.zip
Starting package 1/1: darknet:x64-windows
Building package darknet[core,cuda,cudnn,full,opencv-cuda,weights,weights-train]:x64-windows...
-- Using cached C:/Users/XXXX/vcpkg/downloads/AlexeyAB-darknet-ecad770071eb776208a46977347e6d2410d4f50e.tar.gz
-- Cleaning sources at C:/Users/XXXX/vcpkg/buildtrees/darknet/src/2410d4f50e-654ef90b3b.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/XXXX/vcpkg/downloads/AlexeyAB-darknet-ecad770071eb776208a46977347e6d2410d4f50e.tar.gz
-- Applying patch 0001-rename-_castu32_f32-to-gemm_castu32_f32.patch
-- Using source at C:/Users/XXXX/vcpkg/buildtrees/darknet/src/2410d4f50e-654ef90b3b.clean
-- Downloading https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v4_pre/yolov4-tiny.weights...
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:105 (message):

  File does not have expected hash:

          File path: [ C:/Users/XXXX/vcpkg/downloads/temp/darknet-cache/yolov4-tiny.weights ]
      Expected hash: [ 804ca2ab8e3699d31c95bf773d22f901f186703487c7945f30dc2dbb808094793362cb6f5da5cd0b4b83f820c8565a3cba22fafa069ee6ca2a925677137d95f4 ]
        Actual hash: [ 7d4d9fe150f9fe3ea7d2310f1445fe983b31fbf06d301c70ecfe00e8559e6f1bf940198c2dd55db772238f23ea0092fb6553558e5414f3ee173b8b28e53c5b54 ]

  The file may have been corrupted in transit.  This can be caused by
  proxies.  If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY
  environment variables to
  "https://user:password@your-proxy-ip-address:port/".

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:191 (test_hash)
  ports/darknet/portfile.cmake:56 (vcpkg_download_distfile)
  scripts/ports.cmake:136 (include)

Error: Building package darknet:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: darknet:x64-windows
  Vcpkg version: 2020.11.12-nohash

**Comment by NancyLi1013** [comment]
Hi @wivach 

Thanks for posting this issue.

It's duplicated to #15256, Let's track this issue there.
