### ISSUE TITLE
[pangolin] build failure

### ISSUE THREAD

**Issue by aizuon** [microsoft/vcpkg#15429]
**Host Environment**
- OS: Windows 10
- Compiler: msvc-14.2

**To Reproduce**
`./vcpkg install pangolin:x64-windows-static`

**Failure logs** 
[install-x64-windows-static-dbg-out.log](https://github.com/microsoft/vcpkg/files/5761516/install-x64-windows-static-dbg-out.log)

**Additional context**
Looks like a linking issue

**Comment by NancyLi1013** [comment]
Hi @aizuon 

Thanks for posting this issue.

It seems like you installed `ffmpge[avcodec,mp3lame,snappy] `on your machine.

If you remove ffmpge:x64-windows-static, then try to rebuild `pangolin:x64-windows-static`, which can be built successfully.

**Comment by NancyLi1013** [comment]
I'm trying to reproduce this on my local with these features for `ffmpeg`. 
Will update the results here once done.

**Comment by aizuon** [comment]
> 
> 
> Hi @aizuon
> 
> Thanks for posting this issue.
> 
> It seems like you installed `ffmpge[avcodec,mp3lame,snappy] `on your machine.
> 
> If you remove ffmpge:x64-windows-static, then try to rebuild `pangolin:x64-windows-static`, which can be built successfully.

Thanks, would it be possible to fix this issue so that ffmpeg with specified features and pangolin can be installed at the same time? Would installing pangolin first and then ffmpeg circumvent this error? FFMPEG is a library i regularly use, so its not something i can give up on. Thank you for your response again.

**Comment by NancyLi1013** [comment]
@aizuon 

Sorry for the delay.

I submitted a PR #15593 to fix this issue. Could you please help test if this can work for you?

Thanks.

**Comment by aizuon** [comment]
> 
> 
> @aizuon
> 
> Sorry for the delay.
> 
> I submitted a PR #15593 to fix this issue. Could you please help test if this can work for you?
> 
> Thanks.

Hello,

Thank you for your time and effort. However, the issue still seems to persist. But I think the output log is different, now there are errors with opencl and libavcodec(?).

[install-x64-windows-static-dbg-out.log](https://github.com/microsoft/vcpkg/files/5801927/install-x64-windows-static-dbg-out.log)

**Comment by NancyLi1013** [comment]
Have you rebuilt `ffmpeg`? Or you can add `cmake_policy(SET CMP0012 NEW)` in  _C:\vcpkg\installed\x64-windows-static\share\ffmpeg\vcpkg-cmake-wrapper.cmake_. Then try to rebuild `pangolin`.

**Comment by aizuon** [comment]
> 
> 
> Have you rebuilt `ffmpeg`? Or you can add `cmake_policy(SET CMP0012 NEW)` in _C:\vcpkg\installed\x64-windows-static\share\ffmpeg\vcpkg-cmake-wrapper.cmake_. Then try to rebuild `pangolin`.

Hello,

I've rebuilt ffmpeg, and the issue still persists. Log can be reviewed below. 

[install-x64-windows-static-dbg-out.log](https://github.com/microsoft/vcpkg/files/5807547/install-x64-windows-static-dbg-out.log)

I am also adding a list of my installed packages below for reference for any other packages that might be causing this issue. 

[packages.txt](https://github.com/microsoft/vcpkg/files/5807553/packages.txt)

**Comment by NancyLi1013** [comment]
Thanks for your test and above info.

I will check this again on my local.

**Comment by NancyLi1013** [comment]
Hi @aizuon 

I try to rebuild this on a new repo and I still cannot reproduce this now.

First, I clone a new vcpkg instance and install `ffmpeg[avcodec,avdevice,avfilter,avformat,avresample,core,fdk-aac,ffmpeg,gpl,lzma,mp3lame,nonfree,nvcodec,opencl,opus,postproc,snappy,swresample,swscale,vorbis,vpx,wavpack,x264,x265,zlib]:x64-windows-static`.

Then I install `pangolin:x64-windows-static` and it failed with the error like this:

```
avcodec.lib(hapenc.o) : error LNK2019: unresolved external symbol snappy_compress referenced in function hap_encode
avcodec.lib(hapenc.o) : error LNK2019: unresolved external symbol snappy_max_compressed_length referenced in function hap_init
avcodec.lib(tiff.o) : error LNK2019: unresolved external symbol lzma_code referenced in function tiff_uncompress_lzma
avcodec.lib(tiff.o) : error LNK2019: unresolved external symbol lzma_end referenced in function tiff_uncompress_lzma
avcodec.lib(tiff.o) : error LNK2019: unresolved external symbol lzma_stream_decoder referenced in function tiff_uncompress_lzma
avcodec.lib(libfdk-aacenc.o) : error LNK2019: unresolved external symbol aacEncOpen referenced in function aac_encode_init
avcodec.lib(libfdk-aacenc.o) : error LNK2019: unresolved external symbol aacEncClose referenced in function aac_encode_close
avcodec.lib(libfdk-aacenc.o) : error LNK2019: unresolved external symbol aacEncEncode referenced in function aac_encode_init
avcodec.lib(libfdk-aacenc.o) : error LNK2019: unresolved external symbol aacEncInfo referenced in function aac_encode_init
avcodec.lib(libfdk-aacenc.o) : error LNK2019: unresolved external symbol aacEncoder_SetParam referenced in function aac_encode_init
avcodec.lib(libfdk-aacdec.o) : error LNK2019: unresolved external symbol aacDecoder_AncDataInit referenced in function fdk_aac_decode_init
avcodec.lib(libfdk-aacdec.o) : error LNK2019: unresolved external symbol aacDecoder_SetParam referenced in function fdk_aac_decode_init
avcodec.lib(libfdk-aacdec.o) : error LNK2019: unresolved external symbol aacDecoder_Open referenced in function fdk_aac_decode_init
avcodec.lib(libfdk-aacdec.o) : error LNK2019: unresolved external symbol aacDecoder_ConfigRaw referenced in function fdk_aac_decode_init
avcodec.lib(libfdk-aacdec.o) : error LNK2019: unresolved external symbol aacDecoder_Fill referenced in function fdk_aac_decode_frame
avcodec.lib(libfdk-aacdec.o) : error LNK2019: unresolved external symbol aacDecoder_DecodeFrame referenced in function fdk_aac_decode_frame
avcodec.lib(libfdk-aacdec.o) : error LNK2019: unresolved external symbol aacDecoder_Close referenced in function fdk_aac_decode_close
avcodec.lib(libfdk-aacdec.o) : error LNK2019: unresolved external symbol aacDecoder_GetStreamInfo referenced in function get_stream_info
avcodec.lib(libmp3lame.o) : error LNK2019: unresolved external symbol lame_init referenced in function mp3lame_encode_init
avcodec.lib(libmp3lame.o) : error LNK2019: unresolved external symbol lame_set_in_samplerate referenced in function mp3lame_encode_init
avcodec.lib(libmp3lame.o) : error LNK2019: unresolved external symbol lame_set_num_channels referenced in function mp3lame_encode_init
avcodec.lib(libmp3lame.o) : error LNK2019: unresolved external symbol lame_set_out_samplerate referenced in function mp3lame_encode_init
avcodec.lib(libmp3lame.o) : error LNK2019: unresolved external symbol lame_set_bWriteVbrTag referenced in function mp3lame_encode_init
avcodec.lib(libmp3lame.o) : error LNK2019: unresolved external symbol lame_set_quality referenced in function mp3lame_encode_init
avcodec.lib(libmp3lame.o) : error LNK2019: unresolved external symbol lame_set_mode referenced in function mp3lame_encode_init
avcodec.lib(libmp3lame.o) : error LNK2019: unresolved external symbol lame_set_brate referenced in function mp3lame_encode_init
avcodec.lib(libmp3lame.o) : error LNK2019: unresolved external symbol lame_set_disable_reservoir referenced in function mp3lame_encode_init
avcodec.lib(libmp3lame.o) : error LNK2019: unresolved external symbol lame_set_VBR referenced in function mp3lame_encode_init
avcodec.lib(libmp3lame.o) : error LNK2019: unresolved external symbol lame_set_VBR_quality referenced in function mp3lame_encode_init
avcodec.lib(libmp3lame.o) : error LNK2019: unresolved external symbol lame_set_VBR_mean_bitrate_kbps referenced in function mp3lame_encode_init
```
I add `file(REMOVE ${SOURCE_PATH}/CMakeModules/FindFFMPEG.cmake)` to portfile.cmake and add `cmake_policy(SET CMP0012 NEW)` to _F:\ffmpeg\vcpkg\installed\x64-windows-static\share\ffmpeg\vcpkg-cmake-wrapper.cmake_. Then try to rebuild pangolin. It failed with :

```
F:\ffmpeg\vcpkg\buildtrees\pangolin\src\v0.5-0134903124\include\pangolin/video/drivers/ffmpeg.h(98): error C3646: 'fmtout': unknown override specifier
F:\ffmpeg\vcpkg\buildtrees\pangolin\src\v0.5-0134903124\include\pangolin/video/drivers/ffmpeg.h(98): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
F:\ffmpeg\vcpkg\buildtrees\pangolin\src\v0.5-0134903124\include\pangolin/video/drivers/ffmpeg.h(146): error C3646: 'fmtsrc': unknown override specifier
F:\ffmpeg\vcpkg\buildtrees\pangolin\src\v0.5-0134903124\include\pangolin/video/drivers/ffmpeg.h(146): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
F:\ffmpeg\vcpkg\buildtrees\pangolin\src\v0.5-0134903124\include\pangolin/video/drivers/ffmpeg.h(147): error C3646: 'fmtdst': unknown override specifier
F:\ffmpeg\vcpkg\buildtrees\pangolin\src\v0.5-0134903124\include\pangolin/video/drivers/ffmpeg.h(147): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
[28/67] "E:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29333\bin\Hostx64\x64\cl.exe"   /TP  -IF:\ffmpeg\vcpkg\buildtrees\pangolin\src\v0.5-0134903124\include -Isrc\include -IF:\ffmpeg\vcpkg\installed\x64-windows-static\include -IF:\ffmpeg\vcpkg\installed\x64-windows-static\include\eigen3 /EHs  /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MTd /Z7 /Ob0 /Od /RTC1 /showIncludes /Fosrc\CMakeFiles\pangolin.dir\var\vars.cpp.obj /Fdsrc\CMakeFiles\pangolin.dir\pangolin.pdb /FS -c F:\ffmpeg\vcpkg\buildtrees\pangolin\src\v0.5-0134903124\src\var\vars.cpp
[29/67] "E:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29333\bin\Hostx64\x64\cl.exe"   /TP  -IF:\ffmpeg\vcpkg\buildtrees\pangolin\src\v0.5-0134903124\include -Isrc\include -IF:\ffmpeg\vcpkg\installed\x64-windows-static\include -IF:\ffmpeg\vcpkg\installed\x64-windows-static\include\eigen3 /EHs  /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MTd /Z7 /Ob0 /Od /RTC1 /showIncludes /Fosrc\CMakeFiles\pangolin.dir\video\drivers\debayer.cpp.obj /Fdsrc\CMakeFiles\pangolin.dir\pangolin.pdb /FS -c F:\ffmpeg\vcpkg\buildtrees\pangolin\src\v0.5-0134903124\src\video\drivers\debayer.cpp
ninja: build stopped: subcommand failed.
```

I add `add_definitions(-DHAVE_FFMPEG_AVPIXELFORMAT)` to _F:\ffmpeg\vcpkg\buildtrees\pangolin\src\v0.5-0134903124\src\CMakeLists.txt_. Then build `pangolin `again. I can build it successfully this time.

Could you please try to build `pangolin `on a new vcpkg repo? I'm sorry, I don't know what your problem is now.

Here are the packages I installed on my new repo.

[package.txt](https://github.com/microsoft/vcpkg/files/5813017/package.txt)

**Comment by NancyLi1013** [comment]
@aizuon 

Does it work now?

**Comment by aizuon** [comment]
> 
> 
> @aizuon
> 
> Does it work now?

Sorry i've been quite busy nowadays, will test and report back ASAP...

**Comment by aizuon** [comment]
@NancyLi1013 

Hello again,

I can confirm that i am now able to build in a clean repo. I'll try tomorrow to apply your changes and test on the repo i use again. Rebuilding FFMPEG takes quite a while because i also have to rebuild OpenCV and stuff. Sorry for the long delay again. Thanks.

**Comment by NancyLi1013** [comment]
Thanks for your reply. It doesn't mater.
I completely understand this. Since I also spent much time testing this issue.

Waiting for your news.

**Comment by NancyLi1013** [comment]
@aizuon 

Since this PR has been merged now, you can update vcpkg to the latest version to rebuild this. Please feel free to reopen this issue if you are still bothered by the same problem.

**Comment by aizuon** [comment]
Happy to say it's fixed now. I actually forgot this issue existed. I apologize for making the pull request wait a really long time... Thank you for this fix!

![image](https://user-images.githubusercontent.com/44760523/110897062-cce05700-830d-11eb-95b0-553f15c6ea02.png)

**Comment by NancyLi1013** [comment]
I'm so glad to hear the good news. Thanks for your feedback @aizuon.
