### ISSUE TITLE
[New Port Request] bgfx

### ISSUE THREAD

**Issue by japhib** [microsoft/vcpkg#15426]
Library name: bgfx

Library description: Cross-platform rendering library

Source repository URL: https://github.com/bkaradzic/bgfx

I just started using vcpkg and it is awesome. Really makes package management easy. I don't own (or even contribute to) bgfx but it's an awesome library, and fairly widely used, so I'd love to see it included in vcpkg. Thanks.

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/14955.
