### ISSUE TITLE
[New Port Request] mpfi

### ISSUE THREAD

**Issue by printempts** [microsoft/vcpkg#15430]
Library name: mpfi

Library description: a multiple-precision interval arithmetic library based on mpfr

Project Filelist for MPFI: https://gforge.inria.fr/frs/?group_id=157

I just started using vcpkg and it is awesome. Really makes package management easy. I don't own (or even contribute to) mpfi but it's an awesome library, and fairly widely used, so I'd love to see it included in vcpkg. Many thanks.

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
