### ISSUE TITLE
[CMake] find_package() won't find packages installed via vcpkg

### ISSUE THREAD

**Issue by Holzhaus** [microsoft/vcpkg#15433]
Apparently it's not as straightforward to use vcpkg-installed dependencies in a CMake project as the documentation suggests. I can't get `find_package` detect a vcpkg-installed dependency, it always fails with an error message like this:

```
  Could not find a package configuration file provided by "FFTW3" with any of
See also "D:/a/vcpkg-cmake-example/vcpkg-cmake-example/build/CMakeFiles/CMakeOutput.log".
  the following names:

    FFTW3Config.cmake
    fftw3-config.cmake
```

For demonstration purposes I've set up a minimal example repository here: https://github.com/Holzhaus/vcpkg-cmake-example

Here's the complete CMakeLists.txt for the project:
```cmake
cmake_minimum_required(VERSION 3.18)
project(example)

find_package(FFTW3 CONFIG REQUIRED)

add_executable(example src/example.cpp)
target_link_libraries(example PRIVATE FFTW3::fftw3)
```

And here's the windows batch file that first installs the dependency and then builds the project:
```batch
git clone --depth=1 https://github.com/microsoft/vcpkg.git
call vcpkg\bootstrap-vcpkg.bat
.\vcpkg\vcpkg install fftw3:x64-windows-static
mkdir build
cd build
cmake -DCMAKE_TOOLCHAIN_FILE=..\vcpkg\scripts\buildsystems\vcpkg.cmake ..
cmake --build .
```

It always fails: https://github.com/Holzhaus/vcpkg-cmake-example/runs/1639882790?check_suite_focus=true#step:4:278

Is there a working example that uses vcpkg with a CMake project? I can't believe that this is such a rare use case that I'm the only one having this issue.

**Comment by JackBoosY** [comment]
For static triplet, you also need to add `-DVCPKG_TARGET_TRIPLET=x64-windows-static` to cmake.

See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/users/integration.md#with-cmake).

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
