### ISSUE TITLE
Ports based on rust ?

### ISSUE THREAD

**Issue by proTerm** [microsoft/vcpkg#15441]
Is it planned to have ports written in `rust` ? So far, only` c/c++` projects have been ported with `vcpkg` ?

For example, [librsvg](https://github.com/microsoft/vcpkg/tree/master/ports/librsvg) has been ported, but it represents the last version written in `c`, before `librsvg` had been translated into `rust`. So right now, `vcpkg` offers only an **old version** of the package, while with the new `rust` version many bugs have been apparently being removed.

**Comment by BillyONeal** [comment]
One of the things vcpkg is "selling" is the ability to change the compiler used for everything; including other languages is not categorically out of order but certainly isn't something we're intending to support soon. It seems like we should just remove the `librsvg` port, changing it to say "please go install this one from cargo" or similar?

**Comment by proTerm** [comment]
> other languages is not categorically out of order but certainly isn't something we're intending to support soon

Why other languages could be a problem? Especially `rust`'s integration can be seamless. I compiled rust `librsvg` on `Windows` with (almost no) problems. That is to say, `rust` could be just added and integrated, without bringing any substantial problems. I would only encourage `vcpkg` to accelerate its integration.

**Comment by BillyONeal** [comment]
> Why other languages could be a problem? Especially `rust`'s integration can be seamless.

Because there's no msvc or gcc rust compiler, for example, so it is not seamless.

There is some precedent for it (we have 1 or 2 ports that depend on gfortran on macos for example) but it isn't a first class experience.

**Comment by lebdron** [comment]
It is currently possible to install Go with `vcpkg_find_acquire_program`. Does it make sense to extend the functionality of this function with Rust?

**Comment by BillyONeal** [comment]
@lebdron Again it is possible but it isn't something we would encourage since any port that touches lose many useful benefits the aforementioned triplet system provides, such as good support for cross-compilation.

**Comment by proTerm** [comment]
> Because there's no msvc or gcc rust compiler, for example, so it is not seamless.
Why the rust compiler must be msvc&gcc based ?

>  any port that touches lose many useful benefits the aforementioned triplet system provides
What benefits do you mean?

I would rather think of another explanation: that because rust is LLVM based, it would not need the help of porting (would be given by the llvm design).

**Comment by BillyONeal** [comment]
>Why the rust compiler must be msvc&gcc based ?

Because one of the features we offer is the ability for the user to plug in their own compiler via a triplet.

>What benefits do you mean?

The ability for a customer to set the compiler used.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
