### ISSUE TITLE
[New Port Request] timercpp

### ISSUE THREAD

**Issue by cnSchwarzer** [microsoft/vcpkg#15443]
Library name:
timercpp

Library description:
A clean Timer implementing Javascript's `setTimeout()` and `setInterval()` functions. Also very useful for people finding C#'s Timer alternative in C++.

Source repository URL:
https://github.com/99x/timercpp

**Comment by cnSchwarzer** [comment]
Also, check Issue 3 for more compatibility.

**Comment by cnSchwarzer** [comment]
Need to put `stop()` in separate timercpp.cpp

**Comment by cnSchwarzer** [comment]
However, the detached thread may cause read access violation (this->clear) after the Timer instance being destructed, a more reliable implementation is needed, I will fork the repo and make some changes.

**Comment by cnSchwarzer** [comment]
https://github.com/cnSchwarzer/TimerCpp
My implementation solved read access violation, please take a look.
However it uses `boost.thread` as dependency.

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue with a PR, but we're closing it for now.
