### ISSUE TITLE
[New Port Request] ormpp

### ISSUE THREAD

**Issue by gansaihua** [microsoft/vcpkg#15440]
Library name: ormpp

Library description: modern C++ ORM, C++17, support mysql, postgresql,sqlite

Source repository URL: https://github.com/qicosmos/ormpp

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
