### ISSUE TITLE
osg,qt5,libpng build failed(win10 + vs2015u3)

### ISSUE THREAD

**Issue by yaoyu** [microsoft/vcpkg#1544]
PS D:\Develop\GitOthers\vcpkg> ./vcpkg install libpng
The following packages will be built and installed:
    libpng:x64-windows
Building package libpng:x64-windows...
-- CURRENT_INSTALLED_DIR=D:/Develop/GitOthers/vcpkg/installed/x64-windows
-- DOWNLOADS=D:/Develop/GitOthers/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=D:/Develop/GitOthers/vcpkg/packages/libpng_x64-windows
-- CURRENT_BUILDTREES_DIR=D:/Develop/GitOthers/vcpkg/buildtrees/libpng
-- CURRENT_PORT_DIR=D:/Develop/GitOthers/vcpkg/ports/libpng/.
-- Using cached D:/Develop/GitOthers/vcpkg/downloads/libpng-1.6.30.tar.xz
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Applying patch D:/Develop/GitOthers/vcpkg/ports/libpng/use-abort-on-all-platforms.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch D:/Develop/GitOthers/vcpkg/ports/libpng/use-abort-on-all-platforms.patch done
-- Configuring x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:43 (message):
    Command failed: D:/Develop/GitOthers/vcpkg/downloads/cmake-3.9.0-win32-x86/bin/cmake.exe;D:/Develop/GitOthers/vcpkg/
buildtrees/libpng/src/libpng-1.6.30;-DPNG_STATIC=OFF;-DPNG_SHARED=ON;-DPNG_TESTS=OFF;-DSKIP_INSTALL_PROGRAMS=ON;-DSKIP_I
NSTALL_EXECUTABLES=ON;-DSKIP_INSTALL_FILES=ON;-DCMAKE_SYSTEM_PROCESSOR=AMD64;-DBUILD_SHARED_LIBS=ON;-DVCPKG_TARGET_TRIPL
ET=x64-windows;-DCMAKE_CXX_FLAGS= /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP ;-DCMAKE_C_FLAGS= /DWIN32 /D_WINDOWS /W3 /
utf-8 /MP ;-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_SYS
TEM_PACKAGE_REGISTRY=ON;-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE;-DCMAKE_VERBOSE_MAKEFILE=ON;-DVCPKG_APPLOCAL_DEPS=
OFF;-DCMAKE_TOOLCHAIN_FILE=D:/Develop/GitOthers/vcpkg/scripts/buildsystems/vcpkg.cmake;-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL
_DESTINATION=ON;-DCMAKE_CXX_FLAGS_RELEASE=/MD /O2 /Oi /Gy /DNDEBUG /Zi ;-DCMAKE_C_FLAGS_RELEASE=/MD /O2 /Oi /Gy /DNDEBUG
 /Zi ;-DCMAKE_SHARED_LINKER_FLAGS_RELEASE=/DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF ;-DCMAKE_EXE_LINKER_FLAGS_RELEASE=/DE
BUG /INCREMENTAL:NO /OPT:REF /OPT:ICF ;-G;Ninja;-DCMAKE_BUILD_TYPE=Release;-DCMAKE_INSTALL_PREFIX=D:/Develop/GitOthers/v
cpkg/packages/libpng_x64-windows
    Working Directory: D:/Develop/GitOthers/vcpkg/buildtrees/libpng/x64-windows-rel
    See logs for more information:
      D:\Develop\GitOthers\vcpkg\buildtrees\libpng\config-x64-windows-rel-out.log
      D:\Develop\GitOthers\vcpkg\buildtrees\libpng\config-x64-windows-rel-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:170 (vcpkg_execute_required_process)
  ports/libpng/portfile.cmake:32 (vcpkg_configure_cmake)
  scripts/ports.cmake:73 (include)

Error: Building package libpng:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libpng:x64-windows
  Vcpkg version: 0.0.81-4ae13d4031654ea19005da0557d262778e11939c

Additionally, attach any relevant sections from the log files above.

**Comment by yaoyu** [comment]
CMake Error at D:/Develop/GitOthers/vcpkg/downloads/cmake-3.9.0-win32-x86/share/cmake-3.9/Modules/CMakeTestCCompiler.cmake:51 (message):
  The C compiler "C:/Program Files (x86)/Microsoft Visual Studio
  14.0/VC/bin/amd64/cl.exe" is not able to compile a simple test program.

  It fails with the following output:

   Change Dir: D:/Develop/GitOthers/vcpkg/buildtrees/openjpeg/x64-windows-rel/CMakeFiles/CMakeTmp


  Run Build
  Command:"D:/Develop/GitOthers/vcpkg/downloads/tools/ninja/ninja-1.7.2/ninja.exe"
  "cmTC_1b230"

  ninja: error: build.ninja:30: loading 'rules.ninja':
  系统找不到指定的文件。

  include rules.ninja

                     ^ near here

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:27 (project)

**Comment by Voskrese** [comment]
cmake-3.9.0 + ninja = fail
https://github.com/Microsoft/vcpkg/pull/1526

3.8.2 ok

**Comment by zabulus** [comment]
Using latest vcpkg version:
```
Building package libpng:x64-windows... done
Installing package libpng:x64-windows...
Installing package libpng:x64-windows... done
```
As I said in linked issue, there is issue with environment CMake works at.

**Comment by Voskrese** [comment]
@zabulus все что нас окружает и есть среда, но от этого проблема не уходит и каждый будет сталкиваться с ней. есть решение? я лично не нашел

> all that surrounds us and there Wednesday, but this problem is not going away and everyone will face it. is there a solution? I personally have not found

**Comment by ras0219-msft** [comment]
I'm not able to reproduce this issue; CMake 3.9.0 and Ninja are building libpng fine on my machine.

Perhaps it is an issue with CMake 3.9.0 + Ninja + VS 2015? Could you try installing VS 2017 community and confirm that you still hit this issue?

**Comment by Voskrese** [comment]
@ras0219-msft у меня стоит 2015 и 2017, через env консоли пробыал, ошибки те же. у меня догадки на счет /UNICODE

> I have 2015 and 2017, through the console, probyal env error the same. I have my guesses on the account/Unicode

**Comment by ras0219-msft** [comment]
Aha! So perhaps CMake 3.9 has moved where it puts some temporary files and they now end up on paths that contain Unicode (which didn't happen under 3.8)?

Can you get the contents of the failing build.ninja file and check if it contains Unicode?

**Comment by Voskrese** [comment]
@ras0219-msft **gflags**
```
cmake --version
cmake version 3.9.0

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

> msbuild

```
cmake . -L
Re-run cmake no build system arguments
-- Building for: Visual Studio 15 2017
-- The CXX compiler identification is MSVC 19.10.25019.0
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.10.25017/bin/HostX86/x86/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.10.25017/bin/HostX86/x86/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The C compiler identification is MSVC 19.10.25019.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.10.25017/bin/HostX86/x86/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.10.25017/bin/HostX86/x86/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check size of __int32
-- Check size of __int32 - done
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Configuring done
-- Generating done
-- Build files have been written to: E:/tools/vcpkg/buildtrees/folly2/third/gflags
-- Cache values
BUILD_PACKAGING:BOOL=OFF
BUILD_SHARED_LIBS:BOOL=OFF
BUILD_TESTING:BOOL=OFF
BUILD_gflags_LIB:BOOL=ON
BUILD_gflags_nothreads_LIB:BOOL=ON
REGISTER_BUILD_DIR:BOOL=OFF
REGISTER_INSTALL_PREFIX:BOOL=ON
```
`del CMakeCache.txt`
> Ninja

```
cmake . -L -GNinja
Re-run cmake no build system arguments
-- The CXX compiler identification is MSVC 19.0.24218.1
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe -- broken
CMake Error at C:/Program Files/CMake/share/cmake-3.9/Modules/CMakeTestCXXCompiler.cmake:44 (message):
  The C++ compiler "C:/Program Files (x86)/Microsoft Visual Studio
  14.0/VC/bin/amd64/cl.exe" is not able to compile a simple test program.

  It fails with the following output:

   Change Dir: E:/tools/vcpkg/buildtrees/folly2/third/gflags/CMakeFiles/CMakeTmp



  Run Build Command:"E:/tools/Bin/ninja.exe" "cmTC_e8463"

  ninja: error: build.ninja:30: loading 'rules.ninja': ═х єфрхЄё 
  эрщЄш єърчрээ√щ Їрщы.



  include rules.ninja

                     ^ near here





  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:94 (project)


-- Configuring incomplete, errors occurred!
See also "E:/tools/vcpkg/buildtrees/folly2/third/gflags/CMakeFiles/CMakeOutput.log".
See also "E:/tools/vcpkg/buildtrees/folly2/third/gflags/CMakeFiles/CMakeError.log".
-- Cache values
CMAKE_BUILD_TYPE:STRING=Debug
CMAKE_INSTALL_PREFIX:PATH=C:/Program Files/gflags
```

**Comment by Voskrese** [comment]
`del CMakeCache.txt`
```
cmake --version
cmake version 3.8.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```
```
cmake . -L -GNinja
Re-run cmake no build system arguments
-- The CXX compiler identification is MSVC 19.0.24218.1
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The C compiler identification is MSVC 19.0.24218.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check size of __int32
-- Check size of __int32 - done
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Configuring done
-- Generating done
-- Build files have been written to: E:/tools/vcpkg/buildtrees/folly2/third/gflags
-- Cache values
BUILD_PACKAGING:BOOL=OFF
BUILD_SHARED_LIBS:BOOL=OFF
BUILD_TESTING:BOOL=OFF
BUILD_gflags_LIB:BOOL=ON
BUILD_gflags_nothreads_LIB:BOOL=ON
CMAKE_BUILD_TYPE:STRING=Debug
REGISTER_BUILD_DIR:BOOL=OFF
REGISTER_INSTALL_PREFIX:BOOL=ON
```

**Comment by Voskrese** [comment]
--trace or --trace-expand

`cmake . -L -GNinja --trace -Wno-dev`

```
....

C:/Program Files/CMake/share/cmake-3.9/Modules/CMakeCXXInformation.cmake(254):  if(NOT CMAKE_CXX_CREATE_SHARED_LIBRARY )
C:/Program Files/CMake/share/cmake-3.9/Modules/CMakeCXXInformation.cmake(260):  if(NOT CMAKE_CXX_CREATE_SHARED_MODULE )
C:/Program Files/CMake/share/cmake-3.9/Modules/CMakeCXXInformation.cmake(267):  if(NOT DEFINED CMAKE_CXX_ARCHIVE_CREATE )
C:/Program Files/CMake/share/cmake-3.9/Modules/CMakeCXXInformation.cmake(268):  set(CMAKE_CXX_ARCHIVE_CREATE <CMAKE_AR> qc <TARGET> <LINK_FLAGS> <OBJECTS> )
C:/Program Files/CMake/share/cmake-3.9/Modules/CMakeCXXInformation.cmake(270):  if(NOT DEFINED CMAKE_CXX_ARCHIVE_APPEND )
C:/Program Files/CMake/share/cmake-3.9/Modules/CMakeCXXInformation.cmake(271):  set(CMAKE_CXX_ARCHIVE_APPEND <CMAKE_AR> q  <TARGET> <LINK_FLAGS> <OBJECTS> )
C:/Program Files/CMake/share/cmake-3.9/Modules/CMakeCXXInformation.cmake(273):  if(NOT DEFINED CMAKE_CXX_ARCHIVE_FINISH )
C:/Program Files/CMake/share/cmake-3.9/Modules/CMakeCXXInformation.cmake(274):  set(CMAKE_CXX_ARCHIVE_FINISH <CMAKE_RANLIB> <TARGET> )
C:/Program Files/CMake/share/cmake-3.9/Modules/CMakeCXXInformation.cmake(278):  if(NOT CMAKE_CXX_COMPILE_OBJECT )
C:/Program Files/CMake/share/cmake-3.9/Modules/CMakeCXXInformation.cmake(283):  if(NOT CMAKE_CXX_LINK_EXECUTABLE )
C:/Program Files/CMake/share/cmake-3.9/Modules/CMakeCXXInformation.cmake(288):  mark_as_advanced(CMAKE_VERBOSE_MAKEFILE CMAKE_CXX_FLAGS CMAKE_CXX_FLAGS_RELEASE CMAKE_CXX_FLAGS_RELWITHDEBINFO CMAKE_CXX_FLAGS_MINSIZEREL CMAKE_CXX_FLAGS_DEBUG )
C:/Program Files/CMake/share/cmake-3.9/Modules/CMakeCXXInformation.cmake(296):  set(CMAKE_CXX_INFORMATION_LOADED 1 )
C:/Program Files/CMake/share/cmake-3.9/Modules/CMakeTestCXXCompiler.cmake(5):  if(CMAKE_CXX_COMPILER_FORCED )
C:/Program Files/CMake/share/cmake-3.9/Modules/CMakeTestCXXCompiler.cmake(12):  include(CMakeTestCompilerCommon )
C:/Program Files/CMake/share/cmake-3.9/Modules/CMakeTestCompilerCommon.cmake(5):  function(PrintTestCompilerStatus LANG MSG )

C:/Program Files/CMake/share/cmake-3.9/Modules/CMakeTestCXXCompiler.cmake(16):  unset(CMAKE_CXX_COMPILER_WORKS CACHE )
C:/Program Files/CMake/share/cmake-3.9/Modules/CMakeTestCXXCompiler.cmake(23):  if(NOT CMAKE_CXX_COMPILER_WORKS )
C:/Program Files/CMake/share/cmake-3.9/Modules/CMakeTestCXXCompiler.cmake(24):  PrintTestCompilerStatus(CXX  )
C:/Program Files/CMake/share/cmake-3.9/Modules/CMakeTestCompilerCommon.cmake(6):  message(STATUS Check for working ${LANG} compiler: ${CMAKE_${LANG}_COMPILER}${MSG} )
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/Preview/Enterprise/VC/Tools/MSVC/14.11.25503/bin/HostX64/x64/cl.exe
C:/Program Files/CMake/share/cmake-3.9/Modules/CMakeTestCXXCompiler.cmake(25):  file(WRITE ${CMAKE_BINARY_DIR}${CMAKE_FILES_DIRECTORY}/CMakeTmp/testCXXCompiler.cxx #ifndef __cplusplus\n # error \"The CMAKE_CXX_COMPILER is set to a C compiler\"\n #endif\n int main(){return 0;}\n )
C:/Program Files/CMake/share/cmake-3.9/Modules/CMakeTestCXXCompiler.cmake(30):  try_compile(CMAKE_CXX_COMPILER_WORKS ${CMAKE_BINARY_DIR} ${CMAKE_BINARY_DIR}${CMAKE_FILES_DIRECTORY}/CMakeTmp/testCXXCompiler.cxx OUTPUT_VARIABLE __CMAKE_CXX_COMPILER_OUTPUT )
C:/Program Files/CMake/share/cmake-3.9/Modules/CMakeTestCXXCompiler.cmake(34):  set(CMAKE_CXX_COMPILER_WORKS ${CMAKE_CXX_COMPILER_WORKS} )
C:/Program Files/CMake/share/cmake-3.9/Modules/CMakeTestCXXCompiler.cmake(35):  unset(CMAKE_CXX_COMPILER_WORKS CACHE )
C:/Program Files/CMake/share/cmake-3.9/Modules/CMakeTestCXXCompiler.cmake(36):  set(CXX_TEST_WAS_RUN 1 )
C:/Program Files/CMake/share/cmake-3.9/Modules/CMakeTestCXXCompiler.cmake(39):  if(NOT CMAKE_CXX_COMPILER_WORKS )
C:/Program Files/CMake/share/cmake-3.9/Modules/CMakeTestCXXCompiler.cmake(40):  PrintTestCompilerStatus(CXX  -- broken )
C:/Program Files/CMake/share/cmake-3.9/Modules/CMakeTestCompilerCommon.cmake(6):  message(STATUS Check for working ${LANG} compiler: ${CMAKE_${LANG}_COMPILER}${MSG} )
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/Preview/Enterprise/VC/Tools/MSVC/14.11.25503/bin/HostX64/x64/cl.exe -- broken
C:/Program Files/CMake/share/cmake-3.9/Modules/CMakeTestCXXCompiler.cmake(41):  file(APPEND ${CMAKE_BINARY_DIR}${CMAKE_FILES_DIRECTORY}/CMakeError.log Determining if the CXX compiler works failed with  the following output:\n${__CMAKE_CXX_COMPILER_OUTPUT}\n\n )
C:/Program Files/CMake/share/cmake-3.9/Modules/CMakeTestCXXCompiler.cmake(44):  message(FATAL_ERROR The C++ compiler \"${CMAKE_CXX_COMPILER}\"  is not able to compile a simple test program.\nIt fails  with the following output:\n ${__CMAKE_CXX_COMPILER_OUTPUT}\n\n CMake will not be able to correctly generate this project. )
CMake Error at C:/Program Files/CMake/share/cmake-3.9/Modules/CMakeTestCXXCompiler.cmake:44 (message):
  The C++ compiler "C:/Program Files (x86)/Microsoft Visual
  Studio/Preview/Enterprise/VC/Tools/MSVC/14.11.25503/bin/HostX64/x64/cl.exe"
  is not able to compile a simple test program.

  It fails with the following output:

   Change Dir: E:/tools/vcpkg/buildtrees/folly2/third/gflags/CMakeFiles/CMakeTmp



  Run Build Command:"E:/tools/Bin/ninja.exe" "cmTC_d07e4"

  ninja: error: build.ninja:30: loading 'rules.ninja': ═х єфрхЄё
```

**Comment by Voskrese** [comment]
@ras0219-msft **build.ninja** не смогу проверить, он не формируется из за выше указанной ошибки ))

> I won't be able to check it is not formed due to above errors))

**Comment by Voskrese** [comment]
@ras0219-msft  оказывается можно принудительно использовать якобы не поддерживаемый компилятор

> -DCMAKE_C_COMPILER_FORCED=ON -DCMAKE_CXX_COMPILER_FORCED=ON

`cmake . -L -GNinja --trace -Wno-dev -DCMAKE_CL_64=1 -DMSVC14=1 -DC_TEST_WAS_RUN=0 -DCMAKE_C_COMPILER_FORCED=ON -DCMAKE_CXX_COMPILER_FORCED=ON`

в этом случае конфигурация создается

**Comment by Voskrese** [comment]
error
 [GFLAGS_]INTTYPES_FORMAT to either C99, BSD, or VC7 and try again.
```
CMake Error at CMakeLists.txt:273 (message):
  Do not know how to define a 32-bit integer quantity on your system! Neither
  uint32_t, u_int32_t, nor __int32 seem to be available.  Set
  [GFLAGS_]INTTYPES_FORMAT to either C99, BSD, or VC7 and try again.


-- Configuring incomplete, errors occurred!
See also "E:/tools/vcpkg/buildtrees/folly2/third/gflags/CMakeFiles/CMakeOutput.log".
See also "E:/tools/vcpkg/buildtrees/folly2/third/gflags/CMakeFiles/CMakeError.log".
-- Cache values
BUILD_PACKAGING:BOOL=OFF
BUILD_SHARED_LIBS:BOOL=OFF
BUILD_TESTING:BOOL=OFF
BUILD_gflags_LIB:BOOL=ON
BUILD_gflags_nothreads_LIB:BOOL=ON
CMAKE_BUILD_TYPE:STRING=Debug
REGISTER_BUILD_DIR:BOOL=OFF
REGISTER_INSTALL_PREFIX:BOOL=ON
```

**Comment by Voskrese** [comment]
@ras0219-msft во как, проблема старая оказывается и известная, только вот почему вылезла на cmake 3.9 - https://github.com/ninja-build/ninja/issues/613
в общем если по умолчанию язык консоли не chcp 65001 = UTF-8 ... ?, а возможно другой, то .... ? ninja не правильно или ему подают в неправильном формате заголовки 
`chcp 866`; `chcp 1251` - fail
`chcp 65001` - work

**Comment by yaoyu** [comment]
On my computer, I replace CMake3.9 with CMake3.8.2, it works fine!

**Comment by NancyLi1013** [comment]
Hi @yaoyu, thanks for posting this issue. I can't reproduce it on my machine with VS2015 + CMake 3.14.0.
Please feel free to reopen it if this is still a problem for you.
