### ISSUE TITLE
[llvm] find_package(llvm ...) fails on Windows

### ISSUE THREAD

**Issue by tsnl** [microsoft/vcpkg#15448]
Hello!

When using vcpkg as a git submodule with the CMake build tool, bootstrapping vcpkg and installing `llvm` 11.0.0 succeeds, but `find_package` does not work. It looks like `vcpkg` successfully installed the package, but did not configure CMake correctly.

**Environment**
- OS: Windows 10 (64 bit)
- Compiler: Visual Studio Community 2019 (MSVC 19.28.29334.0)
- CMake: 3.19.1

_Note:_
- I've tested the same `CMakeLists.txt` file on macOS Big Sur 11.1, and it works fine there.
- I'm tested the same on Linux (Ubuntu 20.04 Server), and it works fine there.

**To Reproduce**
1. Clone [the branch `vcpkg-integration` of my repository here](https://github.com/tsnl/pdm); the `CMakeLists.txt` file sets up everything you need.
    
    `> git clone https://github.com/tsnl/pdm pdm-vcpkg --branch vcpkg-integration`
2. Navigate into the directory you just cloned. Download dependency git submodules:

    `> cd pdm-vcpkg`
    `> git submodule update --init --recursive`

3. Run CMake to configure the build.

    `> cmake .`

    This file...
    1. bootstraps vcpkg
    2. sets the CMAKE_TOOLCHAIN_FILE before loading the project (from README.md)
    3. fails on **line 67** [so disregard further output]

**Expected behavior**
`find_package` succeeds.

**Failure logs** 

1. [AppOutput.txt](https://github.com/microsoft/vcpkg/files/5766390/AppOutput.txt)
2. [CMakeOutput.log](https://github.com/microsoft/vcpkg/files/5766391/CMakeOutput.log)

**Additional context**
- I've tested the same `CMakeLists.txt` file on macOS Big Sur 11.1, and it works fine there.
- I'm tested the same on Linux (Ubuntu 20.04 Server), and it works fine there.
- My goal is to provide users with a single, cross-platform configuration point using CMake and VCPkg. Thus, if triplets/platforms can be inferred correctly, this would be a plus.
- I have already verified llvm is installed (using `vcpkg list`) and tried cleaning and re-bootstrapping `vcpkg`.

Thanks for your time, help, and the great work so far. 😄

**Comment by NancyLi1013** [comment]
Hi @tsnl 

Thanks for posting this issue.

```
CMake Error at dev/vcpkg/scripts/buildsystems/vcpkg.cmake:634 (_find_package):
  Could not find a package configuration file provided by "LLVM" with any of
  the following names:

    LLVMConfig.cmake
    llvm-config.cmake

  Add the installation prefix of "LLVM" to CMAKE_PREFIX_PATH or set
  "LLVM_DIR" to a directory containing one of the above files.  If "LLVM"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:67 (find_package)
```
Could you please help provide what it is in  `CMakeLists.txt:67 (find_package)`?

**Comment by tsnl** [comment]
Hi @NancyLi1013

Thanks for taking the time to help. I really appreciate it.

The `CMakeLists.txt` and all referenced files are found at `https://github.com/tsnl/pdm`, on the `vcpkg-integration` branch.

Here's the latest [CMakeLists.txt](https://github.com/microsoft/vcpkg/files/5771731/CMakeLists.txt) for your reference.

Please let me know if you need anything else.

**Comment by NancyLi1013** [comment]
It seems that you installed `llvm:x86-windows`. But you build your project with x64.

Could you please check this? 

Also the install path should be _C:/Users/tsnl/Pandemonium/pdm.vcpkg/dev/vcpkg/installed/x86-windows_.

```
Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building grammar using Bison
-- Installing Clang,LLVM in C:/Users/tsnl/Pandemonium/pdm.vcpkg/dev/vcpkg
Computing installation plan...
The following packages are already installed:
    llvm[clang,core,default-targets,disable-abi-breaking-checks,disable-assertions,disable-clang-static-analyzer,enable-rtti,lld,target-x86,tools]:x86-windows -> 11.0.0      
Package llvm:x86-windows is already installed

Total elapsed time: 30 us

The package llvm:x86-windows provides CMake targets:
```

**Comment by tsnl** [comment]
Hello,

It looks like CMake's new Visual Studio 2019 Generators require an extra flag (`-A`) to specify the architecture, otherwise defaulting to x86. Previous generators included the architecture in the generator name.
```
$ cmake -G    # intentionally wrong
Generators
* Visual Studio 16 2019        = Generates Visual Studio 2019 project files.
                                 Use -A option to specify architecture.
  Visual Studio 15 2017 [arch] = Generates Visual Studio 2017 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 14 2015 [arch] = Generates Visual Studio 2015 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 12 2013 [arch] = Generates Visual Studio 2013 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 11 2012 [arch] = Generates Visual Studio 2012 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 10 2010 [arch] = Generates Visual Studio 2010 project files.
                                 Optional [arch] can be "Win64" or "IA64".
  Visual Studio 9 2008 [arch]  = Generates Visual Studio 2008 project files.
                                 Optional [arch] can be "Win64" or "IA64".
  Borland Makefiles            = Generates Borland makefiles.
  NMake Makefiles              = Generates NMake makefiles.

```

**Comment by NancyLi1013** [comment]
@tsnl 

Thanks for your details.

vcpkg will install x86-windows by default if you don't set triplet for the port you install. So If you want to install llvm:x64-windows, you need to set the triplet when installing. Such as `.\vcpkg install x64-windows`.

For building project via cmake, you can use `cmake -G "Visual Studio 16 2019"` or `cmake -A x64` to build x64 architecture.

**Comment by tsnl** [comment]
@NancyLi1013 

Got it. Your help is deeply appreciated, hope you have a great rest of your day.

**Comment by TSWorld1314** [comment]
Hello @tsnl ,Have you solve this problem？I also want to use LLVM on Windows，but I also have same problem.Thanks a lot!

**Comment by TSWorld1314** [comment]
I want to know how to solve this problem

**Comment by TSWorld1314** [comment]
I see you meet same problem about LLVM on Windows!
Let me tell you some retails：
First，I git clone llvm-project. The path is `D:\llvm-project`
And then :
`cd llvm-project`
`mkdir build`
`cd build`
`cmake -G "Visual Studio 16 2019" ../llvm`
`cmake --build . --target install`
Do above these commands,I build my project.The path is `D:\kaleodoscope`,and then:
`cd kaleodoscope`
`mkdir build`
`cd build`
`cmake ..`
it will be error!
this is  
[CMakeOutput.log](https://github.com/tsnl/pdm/files/9784182/CMakeOutput.log)
```
Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.19044.
-- The C compiler identification is MSVC 19.29.30146.0
-- The CXX compiler identification is MSVC 19.29.30146.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:10 (find_package):
  Could not find a package configuration file provided by "LLVM" with any of
  the following names:

    LLVMConfig.cmake
    llvm-config.cmake

  Add the installation prefix of "LLVM" to CMAKE_PREFIX_PATH or set
  "LLVM_DIR" to a directory containing one of the above files.  If "LLVM"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
```
Thanks a lot !
