### ISSUE TITLE
[vcpkg] Add command to print complete port description

### ISSUE THREAD

**Issue by nurbles** [microsoft/vcpkg#15446]
I have searched the command line reference and FAQ and not found any way to have the `vcpkg search [pkg]` command to list the FULL text of the package description.  Many are quite short, but many others end with '...' after about 63 columns, regardless of how wide my terminal may be (using **Windows Terminal v 1.4.3243.0**)

If this option exists, what is it?

If not, please consider adding it, because it can be very helpful to read the full description of a package before installing it.

**Comment by JackBoosY** [comment]
I think we should add a `detail` option to vcpkg.

**Comment by JackBoosY** [comment]
And you can see the description in _VCPKG_ROOT/port/PORT_NAME/CONTROL_ or _VCPKG_ROOT/port/PORT_NAME/vcpkg.json_.

**Comment by nurbles** [comment]
To clarify for those of us who only rarely use vcpkg, both of the places referenced where one may "see the description" are (or are not) available **WITHOUT** installing the package?

I am interested in this because my nearly 40 years of experience with all sorts of software packages (on both Windows and Linux) has shown that few completely and cleanly _remove_ themselves after having been installed.  That's why I **really** want to read the full description of a package _before_ I install it.
