### ISSUE TITLE
[cppitertool] build failure on CentOS 7

### ISSUE THREAD

**Issue by remz1337** [microsoft/vcpkg#15450]
**Host Environment**
- OS: CentOS 7
- Compiler: Gcc 9.3.0

**To Reproduce**
`./vcpkg install cppitertools`

**Failure logs** 
CMake Error at cmake_install.cmake:46 (file):
  file INSTALL cannot copy file
  "/project/6000253/remz1337/source/vcpkg/buildtrees/cppitertools/src/bb5c89f5f6-22c9aa306d.clean/./dropwhile.hpp"
  to
  "/project/6000253/remz1337/source/vcpkg/packages/cppitertools_x64-linux/debug/include/cppitertools/./dropwhile.hpp":
  Success.

**Additional context**
No issue building on my Windows machine. Needed to compile my project on a Linux cluster and got stuck installing cppitertools

**Comment by remz1337** [comment]
Hello @strega-nil, @Roy-Fokker, could you please have a look at this? I tried to update the port the head of the master branch of the cppitertools repo since I saw there have been some changes there but still get the issue. Thank you

**Comment by JackBoosY** [comment]
Hi @remz1337, thanks for reporting this issue!
Does _/project/6000253/remz1337/source/vcpkg/buildtrees/cppitertools/src/bb5c89f5f6-22c9aa306d.clean/./dropwhile.hpp_ exist?

**Comment by remz1337** [comment]
The file does exists at this location: vcpkg/buildtrees/cppitertools/src/b9d808694c-497269dbee.clean/dropwhile.hpp
which should be equivalent, but might be something to investigate (why is there a "." in the filepath cmake is using?)

**Comment by remz1337** [comment]
I deployed CentOS 7 on my Windows machine through WSL and it seems to work fine there. There must be something different on the remote cluster where I'm trying to build my project.

I tested with a few other ports and here are the results:

- cxxopts 👍 (Success)
- fast-cpp-csv-parser 👍(Success)
- edlib 👍 (Success)
- cityhash 👍 (Success)
- taskflow 👎 (Failure)
- sqlitecpp 👎 (Failure)

They all fail with the same error "Unable to copy file". I don't know why some work and some don't

Thanks

**Comment by JackBoosY** [comment]
@remz1337 Did you use WSL in this scene?

**Comment by remz1337** [comment]
Sorry for the confusion. To clarify, I tested all these ports on 3 environments: my Windows 10 machine, a virtualized CentOS7 through WSL2 on my Windows 10 machine and a remote compute cluster running CentOS7.

- Windows 10: No issues
- CentOS7 through WSL2: No issues
- CentOS7 on compute cluster: Some ports fail (results in previous comment)

So I think it's has something to do with that specific environment (which I am simply a user) but at the same time I would like to understand why some ports work and others don't, then maybe I could raise a ticket with their system administrator.

Do you have a clue what would be the differences between ports that work and those that don't? I've looked at their portfile but all look pretty standard to me.

Thanks

**Comment by JackBoosY** [comment]
I've no idea... @vicroms can you please take a look?

Thanks.

**Comment by PhoebeHui** [comment]
@remz1337, do you solve the issue finally?

**Comment by remz1337** [comment]
Unfortunately, no. I just tested with a fresh clone of the repo but still get the same error. I'm thinking it could be a permission issue since it's a shared compute cluster where I'm only a user and it happens for a few packages. Probably something to do with the install script of those specific packages (or a dependency).

Anyway, I know this is a very niche issue so I don't mind if you want to close it.

**Comment by PhoebeHui** [comment]
@remz1337, thanks for your response! It looks a permission issue and I don't think vcpkg could do something now, closing this issue now.
