### ISSUE TITLE
Show detailed download, configuration and compilation process

### ISSUE THREAD

**Issue by julian-zhuang** [microsoft/vcpkg#15458]
Is it possible to display the detailed download, configuration, and compilation process? I thought it was dead and the console remained unchanged for a long time. In fact, it did not die.
such as
Configuring x64-windows
Configuring x64-windows-dbg
Configuring x64-windows-rel

**Comment by JackBoosY** [comment]
Duplicated to https://github.com/microsoft/vcpkg/discussions/19067.
