### ISSUE TITLE
How do I pass configure options for dependencies in the manifest file?

### ISSUE THREAD

**Issue by jgbradley1** [microsoft/vcpkg#15459]
In a manifest file, is there a *simple* way to override or pass custom cmake options to a dependency?

As an example, I would like to declare [OpenCV](https://github.com/opencv/opencv) as a dependency in my project. The build system in OpenCV is modular so when building from source you can enable/disable specific modules to build smaller binaries.

I would like to build OpenCV with the following cmake variables defined:
```
-DBUILD_LIST=core,imgproc -DBUILD_PERF_TESTS=OFF -DBUILD_TESTS=OFF -DBUILD_DOCS=OFF -DBUILD_SHARED_LIBS=OFF -DWITH_GTK=OFF
```
so is it possible to declare these options in the manifest file?

The manifest definitions and examples listed [here](https://vcpkg.readthedocs.io/en/latest/specifications/manifests) don't appear to provide a clear answer.

My best quess is I should define a custom portfile and use `vcpkg_from_github` and `vcpkg_configure_cmake` but where should the portfile be saved? Are custom portfiles meant to be stored in the same repository as `vcpkg.json`?

**Comment by JackBoosY** [comment]
Due to my lack of knowledge of manifest, let us ask @strega-nil to answer this question.

**Comment by strega-nil** [comment]
@jgbradley1 unfortunately, we don't have the full stuff worked out for this. However, yes, your understanding is correct; you should be using the `overlay-ports` feature.

I would recommend placing all ports that you want to override into a directory, maybe called `overlay-ports` in the root of your repository. Then, once you've done this, add the following to your `CMakeLists.txt`, before the `project()` line:

```cmake
if (NOT DEFINED VCPKG_OVERLAY_PORTS)
    set(VCPKG_OVERLAY_PORTS "${CURRENT_LIST_DIR}/overlay-ports")
endif()
```

**Comment by jgbradley1** [comment]
Thanks @strega-nil . I think having the ability to pass additional configuration parameters to a library build is a feature many users will want for multiple use cases.

As of right now, vcpkg must assume that a single library's default behavior will build support across all platforms and hardware devices out of the box when that is very much not the case. A good example is building a library with/without CUDA support.

Closing the issue for now as my question was answered. Thanks again.

**Comment by strega-nil** [comment]
@jgbradley1 for what it's worth, that's what features are for.

**Comment by hacostar1** [comment]
I'm following these thread but I'm getting an error saying:
_Unknown Cmake command vcpkg_from_github_

What do I need to include in order to solve the vcpkg commands in cmake?
