### ISSUE TITLE
[v8] build failure

### ISSUE THREAD

**Issue by cnSchwarzer** [microsoft/vcpkg#15461]
**Host Environment**
- OS: Windows 10 20H2
- Compiler:  Visual Studio 2019 16.8 MSVC 14 (Latest) x64

**To Reproduce**
1. `./vcpkg install v8:x64-windows`
2. Create `C++ Console Application` on VS2019, switch target to Debug, x64.
3. Replace with the following expected working code:
```c++
#include <v8.h>
#include <libplatform/libplatform.h>

int main(int argc, char** argv)
{
	using namespace v8;
	V8::InitializeICUDefaultLocation(argv[0]);
	V8::InitializeExternalStartupData(argv[0]);
	std::unique_ptr<Platform> platform = platform::NewDefaultPlatform();
	V8::InitializePlatform(platform.get());
	V8::Initialize();
	Isolate::CreateParams create_params;
	create_params.array_buffer_allocator = ArrayBuffer::Allocator::NewDefaultAllocator();
	Isolate* isolate = Isolate::New(create_params);
	{
		Isolate::Scope isolate_scope(isolate);
		HandleScope handle_scope(isolate);
		Local<Context> context = Context::New(isolate);
		Context::Scope context_scope(context);
		Local<String> source = String::NewFromUtf8(isolate, "'Hello' + ', World!'", NewStringType::kNormal).
			ToLocalChecked();
		Local<Script> script = Script::Compile(context, source).ToLocalChecked();
		Local<Value> result = script->Run(context).ToLocalChecked();
		String::Utf8Value utf8(isolate, result);
		printf("%s\n", *utf8);
	}
	// Dispose the isolate and tear down V8.
	isolate->Dispose();
	V8::Dispose();
	V8::ShutdownPlatform();
	delete create_params.array_buffer_allocator;
} 
```
However, `#include <v8.h>` won't work, as v8 installed into `include/v8.h`, which is a little bit confusing, and need user to manually add path `E:\vcpkg\installed\x64-windows\include\include` to project include paths, otherwise the `libplatform` can't find its includes.
![image](https://user-images.githubusercontent.com/29846655/103639387-40ba5800-4f89-11eb-930a-5879790f90bc.png)

4. Let's continue with adding the path to project, click on Build.
```
已启动生成…
1>------ 已启动生成: 项目: regression, 配置: Debug x64 ------
1>main.cpp
1>regression.vcxproj -> E:\Work\ixwebsocket_regression\x64\Debug\regression.exe
========== 生成: 成功 1 个，失败 0 个，最新 0 个，跳过 0 个 ==========
```
It should build successfully, however, let's take a look at build output folder.
![image](https://user-images.githubusercontent.com/29846655/103638511-f7b5d400-4f87-11eb-92e2-40900db2ca14.png)
The file `snapshot_blob.bin` is not being copied to the output folder, and need user to manually copy from `E:\vcpkg\buildtrees\v8\x64-windows-rel` or `E:\vcpkg\buildtrees\v8\x64-windows-dbg`, is there any method to do this automation?
![image](https://user-images.githubusercontent.com/29846655/103638674-3186da80-4f88-11eb-9faa-4fab2206a119.png)
5. Let's continue by copy the file to the folder, and run it from powershell.
```shell
PS E:\Work\ixwebsocket_regression\x64\Debug> ./regression.exe


#
# Fatal error in ../src/15c22b1cff-c34597ce8b.clean/src/api/api.cc, line 5696
# Embedder-vs-V8 build configuration mismatch. On embedder side pointer compression is DISABLED while on V8 side it's ENABLED.
#
#
#
#FailureMessage Object: 000000030D0FEE90
==== C stack trace ===============================

        v8::base::Time::ToFiletime [0x00007FFBF09A6DEB+151275]
        v8::platform::DefaultForegroundTaskRunner::HasPoppableTaskInQueue [0x00007FFBF92C32C2+71519]
        v8::base::Time::ToFiletime [0x00007FFBF09920B7+65975]
        v8_inspector::V8StackTrace::V8StackTrace [0x00007FFB9F9D6575+10644743]
        v8::V8::Initialize [0x00007FF62D022780+176] (E:\vcpkg\installed\x64-windows\include\include\v8.h:9655)
        main [0x00007FF62D022F08+264] (E:\Work\ixwebsocket_regression\main.cpp:12)
        invoke_main [0x00007FF62D023A19+57] (d:\agent\_work\63\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:79)
        __scrt_common_main_seh [0x00007FF62D0238BE+302] (d:\agent\_work\63\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
        __scrt_common_main [0x00007FF62D02377E+14] (d:\agent\_work\63\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:331)
        mainCRTStartup [0x00007FF62D023AA9+9] (d:\agent\_work\63\s\src\vctools\crt\vcstartup\src\startup\exe_main.cpp:17)
        BaseThreadInitThunk [0x00007FFC4EAA7034+20]
        RtlUserThreadStart [0x00007FFC50A7D0D1+33]
```
It says `Embedder-vs-V8 build configuration mismatch. On embedder side pointer compression is DISABLED while on V8 side it's ENABLED.`, which is also solveable by adding a macro `V8_COMPRESS_POINTERS` to project predefined symbols setting.
![image](https://user-images.githubusercontent.com/29846655/103639068-bd006b80-4f88-11eb-81d4-1cff7c28469e.png)
6. Let's continue by rebuilding the program with `V8_COMPRESS_POINTERS`.
![image](https://user-images.githubusercontent.com/29846655/103639264-123c7d00-4f89-11eb-9493-f45f39b6b152.png)
Finally, we successfully run V8.

**Comment by JackBoosY** [comment]
Should be a port bug, @Kwizatz can you please take a look?

Thanks.

**Comment by Kwizatz** [comment]
@cnSchwarzer Are you configuring your project with CMake? If so, post your CMakeLists.txt file, if not, look for a file named V8Config.cmake somewhere under the installed folder, it may give you some hints on what flags to use.

**Comment by Kwizatz** [comment]
Also you may want to look at #13500 for some example usage of the configuration script.

**Comment by cnSchwarzer** [comment]
@Kwizatz No, I am not using cmake, I'm using vcpkg directly from vcxproj/msbuild.
Is that mean that the integration of this developing method cannot automatically does these jobs? (Copy snapshot_blob.bin, add `E:\vcpkg\installed\x64-windows\include\include` to include paths, and add compiler flag)
By the way, i think a port should not put include files in a folder named `include`, could we rename it from `E:\vcpkg\installed\x64-windows\include\include` to `E:\vcpkg\installed\x64-windows\include\v8`?

**Comment by cnSchwarzer** [comment]
@Kwizatz This type of project.
![image](https://user-images.githubusercontent.com/29846655/103726448-e74b3b00-5013-11eb-9123-e0bfc311fa26.png)

**Comment by Kwizatz** [comment]
Correct, using cmake's find_package(V8)  should provide you with a set of variables to add to your include path, library path, and snapshot location so you can automate all with CMake.

I don't know if vcpkg supports something else TBH. 

The include path issue can be worked around by adding the path to the include path in the project settings for the compiler, again, CMake does this for you. The problem with changing this is that this is how it is in V8, changing it may break code that already expects it to be like this.

**Comment by Kwizatz** [comment]
> @Kwizatz This type of project.
Right, that type of project requires you to set everything manually 😕

**Comment by cnSchwarzer** [comment]
@Kwizatz Thanks, it seems that I need to learn how to use cmake ^_^. This issue is solved now?

**Comment by Kwizatz** [comment]
No problem. 👍
Yes I think that may be too complicated, though I am not sure how well integrated VS is with CMake and vcpkg. I usually generate the solution and project files directly with CMake and then open the solution file with VS.

**Comment by JackBoosY** [comment]
Thanks @Kwizatz !
