### ISSUE TITLE
Found both manifest and CONTROL file in ......

### ISSUE THREAD

**Issue by kuelite** [microsoft/vcpkg#15464]
****

**Is your feature request related to a problem? Please describe.**
the problem is : when i used .\vcpkg search, messages such as "Found both manifest and CONTROL  file in ......  ; please rename one or the other" , So i couldnt stand it and had to rename all the CONTROL files with anothor filename and remain all the 
vcpkg.json files.

I hope to fix the annoying problem ,Thank you!

PS E:\src\vcpkg> .\vcpkg search
Found both manifest and CONTROL file in port E:\src\vcpkg\ports\mpg123; please rename one or the other
PS E:\src\vcpkg> .\vcpkg search
Found both manifest and CONTROL file in port E:\src\vcpkg\ports\nlopt; please rename one or the other
PS E:\src\vcpkg> .\vcpkg search
Found both manifest and CONTROL file in port E:\src\vcpkg\ports\oatpp; please rename one or the other
PS E:\src\vcpkg> .\vcpkg search
Found both manifest and CONTROL file in port E:\src\vcpkg\ports\oatpp-libressl; please rename one or the other
PS E:\src\vcpkg> .\vcpkg search
Found both manifest and CONTROL file in port E:\src\vcpkg\ports\oatpp-sqlite; please rename one or the other
PS E:\src\vcpkg> .\vcpkg search
Found both manifest and CONTROL file in port E:\src\vcpkg\ports\oatpp-swagger; please rename one or the other
PS E:\src\vcpkg> .\vcpkg search
Found both manifest and CONTROL file in port E:\src\vcpkg\ports\ois; please rename one or the other
PS E:\src\vcpkg> .\vcpkg search
Found both manifest and CONTROL file in port E:\src\vcpkg\ports\openexr; please rename one or the other
PS E:\src\vcpkg> .\vcpkg search
Found both manifest and CONTROL file in port E:\src\vcpkg\ports\opentracing; please rename one or the other
PS E:\src\vcpkg> .\vcpkg search
Found both manifest and CONTROL file in port E:\src\vcpkg\ports\python3; please rename one or the other
PS E:\src\vcpkg> .\vcpkg search
Found both manifest and CONTROL file in port E:\src\vcpkg\ports\sobjectizer; please rename one or the other
PS E:\src\vcpkg> .\vcpkg search
Found both manifest and CONTROL file in port E:\src\vcpkg\ports\span-lite; please rename one or the other
PS E:\src\vcpkg> .\vcpkg search
Found both manifest and CONTROL file in port E:\src\vcpkg\ports\wepoll; please rename one or the other
PS E:\src\vcpkg> .\vcpkg search
Found both manifest and CONTROL file in port E:\src\vcpkg\ports\x-plane; please rename one or the other

**Comment by PhoebeHui** [comment]
@kuelite, it looks the source messed up, could you get latest clean source and try again?

**Comment by kuelite** [comment]
@PhoebeHui  ，No，I didnt  get latest clean source and try again.  how can i do ?  just re-compiled VTK and GSL once more that i compiled a few days ago?

**Comment by StarGate-One** [comment]
1. cd [vcpkg-root]
2. `git pull`
3. `.\bootstrap-vcpkg.bat` on Windows or `./bootstrap-vcpkg.sh` on Linux
4. `vcpkg search [search term]`
5. If the above steps fail - delete/recreate vcpkg instance - **NOTE** _This will delete all ports already installed!!!_
6. `vcpkg list >..\list.txt` (Create a list of installed ports in the directory above [vcpkg-root])
7. `cd ..` (to move up a directory)
8. `rmdir /q /s [vcpkg-root]` on Windows or `rm -rf [vcpkg-root]` on Linux
9. `git clone https://github.com/microsoft/vcpkg.git`
10. `cd [vcpkg-root]` 
11. `.\bootstrap-vcpkg.bat` on Windows or `./bootstrap-vcpkg.sh` on Linux
12. Install all the ports from `list.txt` above
13. `vcpkg search [search term]` should now work
