### ISSUE TITLE
How do I solve this : This projec t doesn't contain the Configuration and Platform combination of Debug|Win32?

### ISSUE THREAD

**Issue by okayabc** [microsoft/vcpkg#15465]
Currently i use cmake to build cpprest in the powershell.

First, i type this command to download the necessary file:
.\vcpkg.exe install --triplet x86-windows zlib openssl boost-system boost-date-time boost-regex boost-interprocess websocketpp brotli 

then i type this command to generate sln file:
cmake ../Release -A x86 -DCMAKE_TOOLCHAIN_FILE=i:\cpprest\cpprest\vcpkg\scripts\buildsystems\vcpkg.cmake

Unfortunately, the shell reports the following error:

PS I:\cpprest\cpprest\vcpkg> cmake ../Release -A x86 -DCMAKE_TOOLCHAIN_FILE=i:\cpprest\cpprest\vcpkg\scripts\buildsystem
s\vcpkg.cmake
-- Building for: Visual Studio 14 2015
CMake Error at CMakeLists.txt:9 (project):
  Failed to run MSBuild command:

    C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild.exe

  to get the value of VCTargetsPath:

    C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(349,5): error MSB8013: This projec
t doesn't contain the Configuration and Platform combination of Debug|Win32. [I:\cpprest\cpprest\vcpkg\CMakeFiles\3.14.0
\VCTargetsPath.vcxproj]

      C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(349,5): error MSB8013: This proj
ect doesn't contain the Configuration and Platform combination of Debug|Win32. [I:\cpprest\cpprest\vcpkg\CMakeFiles\3.14
.0\VCTargetsPath.vcxproj]

  Exit code: 1

-- Configuring incomplete, errors occurred!

**Comment by okayabc** [comment]
Btw, x64 can work correctly.

.\vcpkg.exe install --triplet x64-windows zlib openssl boost-system boost-date-time boost-regex boost-interprocess websocketpp brotli
cmake ../Release -A x64 -DCMAKE_TOOLCHAIN_FILE=i:\cpprest\cpprest\vcpkg\scripts\buildsystems\vcpkg.cmake

.\vcpkg.exe install --triplet x86-windows zlib openssl boost-system boost-date-time boost-regex boost-interprocess websocketpp brotli
cmake ../Release -A x64 -DCMAKE_TOOLCHAIN_FILE=i:\cpprest\cpprest\vcpkg\scripts\buildsystems\vcpkg.cmake

**Comment by NancyLi1013** [comment]
Hi @okayabc 

Thanks for posting this issue.

It seems that` cmake -A x86` cannot be supported by Visual Studio. This issue also exists on Visual Studio 2019.

You can remove `-A x86` or update it as  `-G "Visual Studio 14 2015"` or `-DCMAKE_GENERATOR_PLATFORM=WIN32` to build x86 architecture.

**Comment by okayabc** [comment]
Thank you, i have used -DCMAKE_GENERATOR_PLATFORM=WIN32 and tested it is useful!

**Comment by louis-langholtz** [comment]
> Hi @okayabc
> 
> Thanks for posting this issue.
> 
> It seems that` cmake -A x86` cannot be supported by Visual Studio. This issue also exists on Visual Studio 2019.
> 
> You can remove `-A x86` or update it as `-G "Visual Studio 14 2015"` or `-DCMAKE_GENERATOR_PLATFORM=WIN32` to build x86 architecture.

Thank you @NancyLi1013 for your post and suggested work around! I seem to have come across this same issue.

Appears that `cmake -A Win32` didn't work for me either. After hours of trying various other changes, I finally found and have tried your suggestion. Happily, using `cmake -DCMAKE_GENERATOR_PLATFORM=WIN32` has worked now for me.

Curiously, using `cmake -DCMAKE_GENERATOR_PLATFORM=%platform%` where `%platform%` was `Win32` (mixed case) did not work for me  though (this was on AppVeyor).

**Comment by LWSS** [comment]
yeah uhh in my case it had to be exactly

`CMAKE .. -G"Visual Studio 17 2022" -DCMAKE_GENERATOR_PLATFORM=WIN32`

no mixed case, can't be specified in the CMakeLists. This is the only way it will work... Cool...
