### ISSUE TITLE
[opencv4] arm64-windows build failure

### ISSUE THREAD

**Issue by andrewderryfarrell** [microsoft/vcpkg#15479]
**Host Environment**
- OS: Windows 10 Pro 20H2
- Compiler: Visual Studio 2019, Version 16.8.3

**To Reproduce**
`./vcpkg install opencv4[core]:arm64-windows`

**Failure logs** 
-- Configuring arm64-windows
-- Building arm64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:145 (message):
    Command failed: C:/vcpkg/downloads/tools/cmake-3.19.2-windows/cmake-3.19.2-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v -j9
    Working Directory: C:/vcpkg/buildtrees/opencv4/arm64-windows-dbg
    See logs for more information:
      C:\vcpkg\buildtrees\opencv4\install-arm64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:27 (vcpkg_build_cmake)
  ports/opencv4/portfile.cmake:362 (vcpkg_install_cmake)
  scripts/ports.cmake:136 (include)

Error: Building package opencv4:arm64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: opencv4:arm64-windows
  Vcpkg version: 2020.11.12-nohash

[install-arm64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/5776671/install-arm64-windows-dbg-out.log)

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by StarGate-One** [comment]
>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29333\include\emmintrin.h(24): fatal error C1189: #error:  **This header is specific to X86 and X64 targets**
>./vcpkg install opencv4[core]:**arm64-windows**

Arm configuration(s) is/are not supported according to the message from the compiler.
You may need to install the C++ Arm components in Visual Studio
1. Open the Visual Studio Installer
2. Select `Individual Components` from the menu
3. Scroll down and check all items with `ARM` in the description - the list is long, so keep scrolling/checking items with `ARM` until you reach the bottom.
![image](https://user-images.githubusercontent.com/68293825/103803365-73faf680-501e-11eb-9a5a-4a55351f8011.png)
![image](https://user-images.githubusercontent.com/68293825/103803448-94c34c00-501e-11eb-8c14-ff66b0479a25.png)
etc etc etc

**Comment by andrewderryfarrell** [comment]
@StarGate-One 
Thanks for the suggestion. I verified that my VS2019 has the ARM64 build tools for the latest version, 14.28. It appears that is the version that vcpkg is using for opencv as well. I can also successfully build other packages such as boost for arm64-windows which makes me believe I have the required build tools. Are you saying that you can successfully build opencv for arm64-windows on your machine?

I did some digging and found this similar issue in opencv a few years ago in the following bug. It looks like opencv added code to support arm64, at least the UWP version. The emmintrin.h file should not be included when building as ARM64. It's almost like this triplet is not specifying that is an ARM64 build as the code expects it.

**Comment by StarGate-One** [comment]
- This may indeed an ARM bug with opencv4, maybe @cenit could take a moment to see something we cannot?
- No, I have not tried compiling it, as I do not need any of the opencv ports, and they take so long to compile/link/install. I was just responding based on the error in the log file.

**Comment by JackBoosY** [comment]
cc @cenit
