### ISSUE TITLE
How do I install OpenVR with vxpkg

### ISSUE THREAD

**Issue by tiaoyuedexin** [microsoft/vcpkg#15480]
When I installed OpenVR with VCPKG，I Always fails to install it. Show such a problem :
CMake Error at scripts/cmake/vcpkg_check_linkage.cmake:45 (message):
  Refusing to build unexpected dynamic library against the static CRT.  If
  this is desired, please configure your triplet to directly request this
  configuration.
Call Stack (most recent call first):
  ports/openvr/portfile.cmake:2 (vcpkg_check_linkage)
  scripts/ports.cmake:136 (include)
Error: Building package openvr:x64-windows-static failed with: BUILD_FAILED

my Vcpkg version  is  2020.11.12-nohash

can you help me, thank you

**Comment by JackBoosY** [comment]
Temporary, you can build openvr: x64-windows instead.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

**Comment by lightbulblighter** [comment]
@JackBoosY This doesn't really work if you're building with x64-windows-static for everything via manifest mode as vcpkg doesn't have the option to specify triplets for specific packages. All other packages than OpenVR just default to x64-windows if it can't do static. Is it possible that OpenVR can replicate this behavior?

**Comment by JackBoosY** [comment]
@lightbulblighter dynamic runtime can't be used in static build on Windows.

**Comment by dg0yt** [comment]
There is also x64-windows-static-md. It uses dynamic linkage for the CRT.

And even in manifest mode, there are variables to pass options to vcpkg. So you can use an overlay triplet which sets special options for a particular port. (This is how it works in general: triplets can set special options for ports.)
