### ISSUE TITLE
Cannot find libssh2

### ISSUE THREAD

**Issue by simon-p-r** [microsoft/vcpkg#15496]
**Host Environment**
- OS:  Windows 10
- Compiler: Visual Studio 2015, 2017 and 2019

**To Reproduce**
```
./vcpkg install libssh2:x86-windows-static
```

**Failure logs** 
```javascript
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.19042.
CMake Error at D:/Development/c/tools/vcpkg/scripts/buildsystems/vcpkg.cmake:634 (_find_package):
  Could not find a package configuration file provided by "Libssh2" with any
  of the following names:

    Libssh2Config.cmake
    libssh2-config.cmake

  Add the installation prefix of "Libssh2" to CMAKE_PREFIX_PATH or set
  "Libssh2_DIR" to a directory containing one of the above files.  If
  "Libssh2" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:5 (find_package)
```

**Additional context**
I had this issue before, see #2233

**Comment by NancyLi1013** [comment]
Hi @simon-p-r 

Thanks for posting this issue.

Could you please help confirm if you have set `CMAKE_TOOLCHAIN_FILE `and `VCPKG_TARGET_TRIPLET`?

**Comment by simon-p-r** [comment]
I reinstalled vcpkg and it is working, problem was with ```VCPKG_TARGET_TRIPLET```.  However I am getting ```WinHttpSendRequest() failed: 12029``` errors when downloading tools, I have manually downloaded for now
