### ISSUE TITLE
Error: Building package openssl:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by jaxanc** [Microsoft/vcpkg#1549]
Can't seem to install openssl. Build exits with the following logs.

//---------------------------------------------------------------------------------------------------
The following packages will be built and installed:
    openssl:x86-windows
Building package openssl:x86-windows...
-- CURRENT_INSTALLED_DIR=E:/Develop/vcpkg/installed/x86-windows
-- DOWNLOADS=E:/Develop/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=E:/Develop/vcpkg/packages/openssl_x86-windows
-- CURRENT_BUILDTREES_DIR=E:/Develop/vcpkg/buildtrees/openssl
-- CURRENT_PORT_DIR=E:/Develop/vcpkg/ports/openssl/.
CMake Error: Problem with archive_write_finish_entry(): Can't restore time
CMake Error: Problem extracting tar: E:/Develop/vcpkg/downloads/strawberry-perl-5.24.1.1-32bit-portable.zip
CMake Error: Problem with archive_write_finish_entry(): Can't restore time
CMake Error: Problem extracting tar: E:/Develop/vcpkg/downloads/jom_1_1_2.zip
-- Using cached E:/Develop/vcpkg/downloads/openssl-1.0.2l.tar.gz
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Applying patch E:/Develop/vcpkg/ports/openssl/PerlScriptSpaceInPathFixes.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch E:/Develop/vcpkg/ports/openssl/PerlScriptSpaceInPathFixes.patch done
-- Applying patch E:/Develop/vcpkg/ports/openssl/ConfigureIncludeQuotesFix.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch E:/Develop/vcpkg/ports/openssl/ConfigureIncludeQuotesFix.patch done
-- Applying patch E:/Develop/vcpkg/ports/openssl/STRINGIFYPatch.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch E:/Develop/vcpkg/ports/openssl/STRINGIFYPatch.patch done
-- Build x86-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:43 (message):
    Command failed: PERL-NOTFOUND;Configure;enable-static-engine;enable-capieng;no-ssl2;VC-WIN32;--prefix=E:/Develop/vcpkg/packages/openssl_x86-windows;--openssldir=E:/Develop/vcpkg/packages/openssl_x86-windows;-FS
    Working Directory: E:/Develop/vcpkg/buildtrees/openssl/x86-windows-rel/openssl-1.0.2l
    See logs for more information:
      E:\Develop\vcpkg\buildtrees\openssl\configure-perl-x86-windows--rel-out.log
      E:\Develop\vcpkg\buildtrees\openssl\configure-perl-x86-windows--rel-err.log

Call Stack (most recent call first):
  ports/openssl/portfile.cmake:63 (vcpkg_execute_required_process)
  scripts/ports.cmake:73 (include)

//---------------------------------------------------------------------------------------
configure-perl-x86-windows--rel-out.log and configure-perl-x86-windows--rel-err.log don't give any meaningful info. Any help will be much appreciated.

**Comment by ras0219-msft** [comment]
Thanks for reporting this!

> Command failed: PERL-NOTFOUND;...

It looks like we couldn't find PERL. Looking earlier in the log...

>CMake Error: Problem with archive_write_finish_entry(): Can't restore time
> CMake Error: Problem extracting tar: E:/Develop/vcpkg/downloads/strawberry-perl-5.24.1.1-32bit-portable.zip
> CMake Error: Problem with archive_write_finish_entry(): Can't restore time
> CMake Error: Problem extracting tar: E:/Develop/vcpkg/downloads/jom_1_1_2.zip

I'm not sure what could cause this issue. Some suggest it might be caused by FAT32[1]; could you confirm that your E:\ drive is NTFS formatted?

[1] https://community.amd.com/thread/167645

**Comment by ArseniyShestakov** [comment]
I have similar problem and my drive D is NTFS formatted. Log files mentioned are empty.

```
$ ./vcpkg install qt5
The following packages will be built and installed:
  * double-conversion:x86-windows
  * libpq:x86-windows
  * openssl:x86-windows
    qt5:x86-windows
Additional packages (*) will be installed to complete this operation.
Building package openssl:x86-windows...
-- CURRENT_INSTALLED_DIR=D:/DEV/vcpkg/installed/x86-windows
-- DOWNLOADS=D:/DEV/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=D:/DEV/vcpkg/packages/openssl_x86-windows
-- CURRENT_BUILDTREES_DIR=D:/DEV/vcpkg/buildtrees/openssl
-- CURRENT_PORT_DIR=D:/DEV/vcpkg/ports/openssl/.
-- Using cached D:/DEV/vcpkg/downloads/openssl-1.0.2l.tar.gz
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Applying patch D:/DEV/vcpkg/ports/openssl/PerlScriptSpaceInPathFixes.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch D:/DEV/vcpkg/ports/openssl/PerlScriptSpaceInPathFixes.patch done
-- Applying patch D:/DEV/vcpkg/ports/openssl/ConfigureIncludeQuotesFix.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch D:/DEV/vcpkg/ports/openssl/ConfigureIncludeQuotesFix.patch done
-- Applying patch D:/DEV/vcpkg/ports/openssl/STRINGIFYPatch.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch D:/DEV/vcpkg/ports/openssl/STRINGIFYPatch.patch done
-- Build x86-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:43 (message):
    Command failed: D:/DEV/vcpkg/downloads/tools/msys2/msys64/usr/bin/perl.exe;Configure;enable-static-engine;enable-capieng;no-ssl2;VC-WIN32;--prefix=D:/DEV/vcpkg/packages/openssl_x86-windows;--openssldir=D:/DEV/vcpkg/packages/openssl_x86-windows;-FS
    Working Directory: D:/DEV/vcpkg/buildtrees/openssl/x86-windows-rel/openssl-1.0.2l
    See logs for more information:
      D:\DEV\vcpkg\buildtrees\openssl\configure-perl-x86-windows--rel-out.log
      D:\DEV\vcpkg\buildtrees\openssl\configure-perl-x86-windows--rel-err.log

Call Stack (most recent call first):
  ports/openssl/portfile.cmake:73 (vcpkg_execute_required_process)
  scripts/ports.cmake:72 (include)


Error: Building package openssl:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openssl:x86-windows
  Vcpkg version: 0.0.81-c22ab980bcab362134ef3e5db329a81c1767c2c9

Additionally, attach any relevant sections from the log files above.
```

**Comment by jaxanc** [comment]
Thanks for the help. Yes, you were right. My E drive was formatted to extFAT. After switching to another drive running NTFS the issue went away.

**Comment by NancyLi1013** [comment]
Please open a new issue if this is still a problem for you.
