### ISSUE TITLE
[libLAS] Features not being checked in the portfile

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#15494]
portfile seems to be at least missing a `vcpkg_check_features` call.
The configure call is also using
```
        -DCMAKE_DISABLE_FIND_PACKAGE_ZLIB=${CMAKE_DISABLE_FIND_PACKAGE_ZLIB}
        -DCMAKE_DISABLE_FIND_PACKAGE_JPEG=${CMAKE_DISABLE_FIND_PACKAGE_JPEG}
```
but the variables `CMAKE_DISABLE_FIND_PACKAGE_X ` are actually never set within the portfile.

**Comment by LilyWangLL** [comment]
This issue has been fixed in PR https://github.com/microsoft/vcpkg/pull/25664. There are the following description for `jpeg` and `zlib` features.

```
    "jpeg": {
      "description": "This feature does nothing. It is retained for compatibility."
    },
    "zlib": {
      "description": "This feature does nothing. It is retained for compatibility."
    }
```
