### ISSUE TITLE
[glslang] update to 11.1.0

### ISSUE THREAD

**Issue by Luke-Filewalker** [microsoft/vcpkg#15498]
Library name: glslang

New version number: 11.1.0 or whatever version that is included in the current sdk

In the version currently included with vcpkg, the KHR implementation for ray tracing is not present, please update to newer version.

**Comment by Luke-Filewalker** [comment]
I implemented the change myself. You can find the pull request here: microsoft/vcpkg#15691

**Comment by JonLiu1993** [comment]
Sloved by #15719
