### ISSUE TITLE
ogre toolchain_fixes.patch mistake

### ISSUE THREAD

**Issue by polelf** [microsoft/vcpkg#15499]
**Host Environment**
- OS: Windows
- Compiler: visual studio 2019

**To Reproduce**
`./vcpkg install ogre`

in file ports/ogre/toolchain_fixes.patch:

--- a/CMake/Packages/FindZZip.cmake
+++ b/CMake/Packages/FindZZip.cmake
@@ -39,12 +39,12 @@ use_pkgconfig(ZZip_PKGC zziplib)
 
 findpkg_framework(ZZip)
 
-find_path(ZZip_INCLUDE_DIR NAMES zzip/zzip.h HINTS ${ZZip_INC_SEARCH_PATH} ${ZZip_PKGC_INCLUDE_DIRS})
+find_path(ZZip_INCLUDE_DIRS NAMES zzip/zzip.h HINTS ${ZZip_INC_SEARCH_PATH} ${ZZip_PKGC_INCLUDE_DIRS})

it will casuse cmake configure 'Can not locate ZZip' 

it shoud be ZZip_INCLUDE_DIR not ZZip_INCLUDE_DIRS

**Comment by JackBoosY** [comment]
Hi @polelf,
When I use:
```
add_executable (CMakeProject2 "CMakeProject2.cpp" "CMakeProject2.h")
find_package(OGRE CONFIG REQUIRED)
target_link_libraries(CMakeProject2 PRIVATE OgreMain OgreBites OgrePaging OgreVolume)
```

No errors occur here.
Can you provide a sample project to repro it?

Thanks.

**Comment by polelf** [comment]
to build ogre samples Browser



polelf@tom.com
 
From: Jack·Boos·Yu
Date: 2021-01-08 17:02
To: microsoft/vcpkg
CC: qiujun; Mention
Subject: Re: [microsoft/vcpkg] ogre toolchain_fixes.patch mistake (#15499)
Hi @polelf,
When I use:
add_executable (CMakeProject2 "CMakeProject2.cpp" "CMakeProject2.h")
find_package(OGRE CONFIG REQUIRED)
target_link_libraries(CMakeProject2 PRIVATE OgreMain OgreBites OgrePaging OgreVolume)

No errors occur here.
Can you provide a sample project to repro it?
Thanks.

**Comment by JackBoosY** [comment]
Will try to repro this tomorrow.

**Comment by JackBoosY** [comment]
The only place where zzip is used is in _source\OgreMain\CMakeLists.txt_ line 160:
```
if (OGRE_CONFIG_ENABLE_ZIP)
  include_directories("${ZZip_INCLUDE_DIRS}")
  list(APPEND HEADER_FILES include/OgreZip.h)
  list(APPEND SOURCE_FILES src/OgreZip.cpp)
...
```

So I don't think that has problems.

**Comment by polelf** [comment]
FindZZip fail cause OGRE_CONFIG_ENABLE_ZIP=0 then OGRE_NO_ZIP_ARCHIVE=1 ogre::ZipArchive Will not compile, so the zip resource cannot be opened

**Comment by JackBoosY** [comment]
@polelf  The change you provided only changes the path where _zzip/zzip.h_ is saved from `ZZip_INCLUDE_DIR` to `ZZip_INCLUDE_DIRS`. Since `ZZip_INCLUDE_DIRS` is not used elsewhere, this should not cause any change in the result.

**Comment by polelf** [comment]
OGRE_NO_ZIP_ARCHIVE macro Decide whether ogre::ZipArchive is compiled

**Comment by JackBoosY** [comment]
cc @longhuan2018

**Comment by JackBoosY** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.

**Comment by mdubepsi** [comment]
@polelf thanks for this, I just ran into the same issue: features zziplib is enabled but I ended up with an ogre library not supporting zip archive.  By reverting to ```find_path(ZZip_INCLUDE_DIR NAMES zzip/zzip.h HINTS ${ZZip_INC_SEARCH_PATH} ${ZZip_PKGC_INCLUDE_DIRS})``` (ZZip_INCLUDE_DIR without the ending S) zziplib was found properly.

**Comment by dg0yt** [comment]
On building `ogre[core,zziplib]:x64-linux`, this is logged in `config...log`:
~~~
-- Checking for module 'zziplib'
--   Found zziplib, version 0.13.72
-- Could not locate ZZip
~~~
Pretty clear.

And `toolchain_fixes.patch` is really strange.
