### ISSUE TITLE
[lua] cmake can not return on linux, while compiling, the cpu usage is 100%, and the task will never end

### ISSUE THREAD

**Issue by williamxin** [microsoft/vcpkg#15497]
**Describe the bug**
when i use lua
cmake can not return on linux, while compiling, the cpu usage is 100%, and the task will never end

**Environment**
- OS: Ubuntu20
- Compiler: cmake 3.16

**To Reproduce**
vcpkg install lua
cmake .. "-DCMAKE_TOOLCHAIN_FILE=~/.vcpkg/scripts/buildsystems/vcpkg.cmake"

**Expected behavior**
compile complete successfully

**Failure logs** 
-not any logs

**Additional context**
the same code can run perfectly on win10.

```
# CMakeLists.txt
cmake_minimum_required(VERSION 3.0)
project(test)

include(FindLua)
find_package(Lua REQUIRED)

add_executable(main main.cpp)

target_link_libraries(main PRIVATE ${LUA_LIBRARIES})

```

**Comment by JackBoosY** [comment]
Confirmed. Thanks for reporting this issue!

**Comment by williamxin** [comment]
can anybody fix it?

**Comment by JackBoosY** [comment]
This issue is in my list to be fixed.

**Comment by JackBoosY** [comment]
Why did you close this PR? It's not resolved yet.

**Comment by williamxin** [comment]
now i can compile lua project, the problem might have been fixed

> Why did you close this PR? It's not resolved yet.
