### ISSUE TITLE
64-bit only

### ISSUE THREAD

**Issue by ZeroCrunch** [Microsoft/vcpkg#155]
I want to add Intel's TBB, which is 64-bit only, how can I make the portfile.cmake insist on 64-bit only architecture?

**Comment by ras0219-msft** [comment]
The most robust way to do this (with respect to possible future triplets) is to add a check to the portfile which spits out a FATAL_ERROR message if there's a mismatch.
```cmake
if(NOT VCPKG_TARGET_ARCHITECTURE STREQUAL x64)
  message(FATAL_ERROR "Intel TBB only supports the x64 architecture.")
endif()
```

**Comment by ZeroCrunch** [comment]
Awesome! Thank you!

So, how do I make TARGET_TRIPLET be 64-bit?!

**Comment by ras0219-msft** [comment]
You can either use the `--triplet` switch or append a `:<triplet>` to the end of the library name on install:

```
  --triplet <t>                   Specify the target architecture triplet.
                                  (default: %VCPKG_DEFAULT_TRIPLET%, see 'vcpkg help triplet')
```
or
```
C:\vcpkg>vcpkg install zlib:x64-windows
```

**Comment by ZeroCrunch** [comment]
Great! Thank you!
