### ISSUE TITLE
More defensive coding against overwriting env variables accidentally

### ISSUE THREAD

**Issue by stekyne** [Microsoft/vcpkg#1550]
I recently ran into an issue with VCPKG and a project whereby it was partially finding files and sometimes not at all (it seemed to depend on which package I was trying to install). I eventually found the issue however and it was due to me setting the cmake_prefix_path with my own libs. 

The fix involved appending this path instead, which I assume was to not overwrite whatever vcpkg.cmake had done. 

This was a bit hard to find and very easily done, is there anything that can be done on VCPKGs end to warn the user maybe?

**Comment by ras0219-msft** [comment]
We might be able to use the `CMAKE_SYSTEM_XYZ` variables, which would be cleaner since they're intended to be owned by the "system" instead of the project.
