### ISSUE TITLE
vcpkg install opencv[contrib] does not work neither for x86 nor for x64

### ISSUE THREAD

**Issue by DietmarSchulz** [microsoft/vcpkg#15505]
```
vcpkg install opencv[contrib]:x64-windows --recurse
Computing installation plan...
The following packages will be built and installed:
    opencv[contrib,core,dnn,jpeg,opengl,png,tiff,webp]:x64-windows -> 4.3.0
  * opencv4[contrib,core,dnn,jpeg,opengl,png,tiff,webp]:x64-windows -> 4.3.0#4
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\dietm\AppData\Local\vcpkg\archives\ac\ac57bea7aa3d11b451ca3851ada5eaf5e1ef1e37.zip
Could not locate cached archive: C:\Users\dietm\AppData\Local\vcpkg\archives\62\62b23222e7643ad892d51090f69e703bafa2c2b1.zip
Starting package 1/2: opencv4:x64-windows
Building package opencv4[contrib,core,dnn,jpeg,opengl,png,tiff,webp]:x64-windows...
CMake Error at ports/opencv4/portfile.cmake:6 (message):
  OpenCV 3 is installed, please uninstall and try again:

      vcpkg remove opencv3
Call Stack (most recent call first):
  scripts/ports.cmake:136 (include)


Error: Building package opencv4:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: opencv4:x64-windows
  Vcpkg version: 2020.11.12-nohash
```

**Comment by StarGate-One** [comment]
>OpenCV 3 is installed, please uninstall and try again:
>
>vcpkg remove opencv3

- **opencv3** is already **_installed_**, so vcpkg will **not** install _opencv, opencv2 or opencv4_ until **opencv3** is **_removed_**.

- vcpkg at present allows only one opencv port installed at a time:
  Either opencv **OR** opencv2 **OR** opencv3 **OR** opencv4.

**Comment by DietmarSchulz** [comment]
Thanks, that helped!

 

Does that also apply to opencv3[cuda]:x64-windows?

Thanks in advance!

 

Regards

Dietmar

 

Von: StarGate-One <notifications@github.com> 
Gesendet: Donnerstag, 7. Januar 2021 22:07
An: microsoft/vcpkg <vcpkg@noreply.github.com>
Cc: DietmarSchulz <dietmar@schulzi-family.de>; Author <author@noreply.github.com>
Betreff: Re: [microsoft/vcpkg] vcpkg install opencv[contrib] does not work neither for x86 nor for x64 (#15505)

 

OpenCV 3 is installed, please uninstall and try again:

vcpkg remove opencv3

*	opencv3 is already installed, so vcpkg will not install opencv, opencv2 or opencv4 until opencv3 is removed.
*	vcpkg at present allows only one opencv port installed at a time:
Either opencv OR opencv2 OR opencv3 OR opencv4.

**Comment by DietmarSchulz** [comment]
No, it doesn’t:

 

vcpkg install opencv3[cuda]:x64-windows --recurse

Computing installation plan...

The following packages will be rebuilt:

    opencv3[contrib,core,cuda,dnn,ffmpeg,flann,jpeg,opengl,png,tiff,webp]:x64-windows -> 3.4.10#4

Starting package 1/2: opencv3:x64-windows

Removing package opencv3:x64-windows...

Removing package opencv3:x64-windows... done

Elapsed time for package opencv3:x64-windows: 132.9 ms

Detecting compiler hash for triplet x64-windows...

Could not locate cached archive: C:\Users\dietm\AppData\Local\vcpkg\archives\cc\cc6e755ac64751f50bc7b30a13d399f01ac561ff.zip

Starting package 2/2: opencv3:x64-windows

Building package opencv3[contrib,core,cuda,dnn,ffmpeg,flann,jpeg,opengl,png,tiff,webp]:x64-windows...

-- Using cached D:/Programming/vcpkg_clone/downloads/opencv-opencv-3.4.10.tar.gz

-- Cleaning sources at D:/Programming/vcpkg_clone/buildtrees/opencv3/src/3.4.10-9aff0f8998.clean. Use --editable to skip cleaning for the packages you specify.

-- Extracting source D:/Programming/vcpkg_clone/downloads/opencv-opencv-3.4.10.tar.gz

-- Applying patch 0001-disable-downloading.patch

-- Applying patch 0002-install-options.patch

-- Applying patch 0003-force-package-requirements.patch

-- Applying patch 0005-fix-vtk9.patch

-- Applying patch 0009-fix-uwp.patch

-- Using source at D:/Programming/vcpkg_clone/buildtrees/opencv3/src/3.4.10-9aff0f8998.clean

-- Using cached D:/Programming/vcpkg_clone/downloads/opencv-cache/tiny_dnn/adb1c512e09ca2c7a6faef36f9c53e59-v1.0.0a3.tar.gz

-- Using cached D:/Programming/vcpkg_clone/downloads/opencv-opencv_contrib-3.4.10.tar.gz

-- Cleaning sources at D:/Programming/vcpkg_clone/buildtrees/opencv3/src/3.4.10-3d1dc84cf7.clean. Use --editable to skip cleaning for the packages you specify.

-- Extracting source D:/Programming/vcpkg_clone/downloads/opencv-opencv_contrib-3.4.10.tar.gz

-- Applying patch 0004-add-missing-stdexcept-include.patch

-- Using source at D:/Programming/vcpkg_clone/buildtrees/opencv3/src/3.4.10-3d1dc84cf7.clean

-- Using cached D:/Programming/vcpkg_clone/downloads/opencv-cache/data/7505c44ca4eb54b4ab1e4777cb96ac05-face_landmark_model.dat

-- Configuring x64-windows

CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:108 (message):

    Command failed: ninja -v

    Working Directory: D:/Programming/vcpkg_clone/buildtrees/opencv3/x64-windows-rel/vcpkg-parallel-configure

    Error code: 1

    See logs for more information:

      D:\Programming\vcpkg_clone\buildtrees\opencv3\config-x64-windows-out.log

 

Call Stack (most recent call first):

  scripts/cmake/vcpkg_configure_cmake.cmake:319 (vcpkg_execute_required_process)

  ports/opencv3/portfile.cmake:240 (vcpkg_configure_cmake)

  scripts/ports.cmake:136 (include)

 

 

Error: Building package opencv3:x64-windows failed with: BUILD_FAILED

Please ensure you're using the latest portfiles with `.\vcpkg update`, then

submit an issue at https://github.com/Microsoft/vcpkg/issues including:

  Package: opencv3:x64-windows

  Vcpkg version: 2020.11.12-nohash

 

Von: dietmar@schulzi-family.de <dietmar@schulzi-family.de> 
Gesendet: Donnerstag, 7. Januar 2021 22:32
An: 'microsoft/vcpkg' <reply@reply.github.com>
Betreff: AW: [microsoft/vcpkg] vcpkg install opencv[contrib] does not work neither for x86 nor for x64 (#15505)

 

Thanks, that helped!

 

Does that also apply to opencv3[cuda]:x64-windows?

Thanks in advance!

 

Regards

Dietmar

 

Von: StarGate-One <notifications@github.com> 
Gesendet: Donnerstag, 7. Januar 2021 22:07
An: microsoft/vcpkg <vcpkg@noreply.github.com>
Cc: DietmarSchulz <dietmar@schulzi-family.de>; Author <author@noreply.github.com>
Betreff: Re: [microsoft/vcpkg] vcpkg install opencv[contrib] does not work neither for x86 nor for x64 (#15505)

 

OpenCV 3 is installed, please uninstall and try again:

vcpkg remove opencv3

*	opencv3 is already installed, so vcpkg will not install opencv, opencv2 or opencv4 until opencv3 is removed.
*	vcpkg at present allows only one opencv port installed at a time:
Either opencv OR opencv2 OR opencv3 OR opencv4.

**Comment by StarGate-One** [comment]
> Thanks, that helped! 
>Does that also apply to opencv3[cuda]:x64-windows? 
>Thanks in advance! 

Yes, regardless of the features selected only 1 opencv**X** port can be installed.

If you `vcpkg install opencv3[contrib,core,cuda,dnn,ffmpeg,flann,jpeg,opengl,png,tiff,webp]:x64-windows` then
`vcpkg install opencv3[contrib,core,png,tiff,webp]:x64-windows` will fail.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
