### ISSUE TITLE
Fix the vcpkg installation for qt5 libraries with triplet support

### ISSUE THREAD

**Issue by apattnaik0721013** [Microsoft/vcpkg#1551]
with vcpkg (0.0.81-5), it failed to install qt5 with triplet format.
i tried the following to install qt5:
vcpkg.exe install qt5:x86-windows-v140

**Comment by apattnaik0721013** [comment]
need to check port for qt5 for dynamic support

**Comment by Voskrese** [comment]
???
 vcpkg.exe install qt5:x86-windows-**v140**

 vcpkg.exe install qt5:x86-windows or  vcpkg.exe install qt5:x86-windows-static
