### ISSUE TITLE
prometheus-cpp update to 0.11.0

### ISSUE THREAD

**Issue by draveness** [microsoft/vcpkg#15515]
Library name: prometheus-cpp

New version number: 0.11.0

Other information that may be useful (release notes, etc...)

**Comment by JonLiu1993** [comment]
@draveness ,Thanks for posting this issue,I noticed that the latest version of prometheus-cpp has been v0.11.0, you can update the latest vcpkg and try to build and use

**Comment by JonLiu1993** [comment]
Duplicate to #15406

**Comment by draveness** [comment]
> Duplicate to #15406

sorry, forget already raise the issue
