### ISSUE TITLE
hope support libsnark 

### ISSUE THREAD

**Issue by NauhWuun** [microsoft/vcpkg#15511]
Library name: libsnark

Library description: a C++ library for zkSNARK proofs

Source repository URL: https://github.com/scipr-lab/libsnark

Project homepage (if different from the source repository): https://github.com/scipr-lab/libsnark
 
Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
