### ISSUE TITLE
[yoga] <add .cmake configuration for paths and libs>

### ISSUE THREAD

**Issue by cmaughan** [microsoft/vcpkg#15524]
****

**Is your feature request related to a problem? Please describe.**
vcpkg install yoga does not return any CMake package instructions; so it is hard to link to the libraries or get the headers

**Proposed solution**
Add the usual CMake/find_package support

**Describe alternatives you've considered**
Is there a clean way to get the paths to the library or headers that have been installed?

**Additional context**
Here's the output from the build command:
-- Building x86-windows-rel                                                                                               
-- Installing: D:/Dev/rez/vcpkg/packages/yoga_x86-windows/include/yoga                                                    
-- Installing: D:/Dev/rez/vcpkg/packages/yoga_x86-windows/include/yoga/Bitfield.h                                         
-- Installing: D:/Dev/rez/vcpkg/packages/yoga_x86-windows/include/yoga/CompactValue.h                                     
-- Installing: D:/Dev/rez/vcpkg/packages/yoga_x86-windows/include/yoga/event                                              
-- Installing: D:/Dev/rez/vcpkg/packages/yoga_x86-windows/include/yoga/event/event.h                                      
-- Installing: D:/Dev/rez/vcpkg/packages/yoga_x86-windows/include/yoga/internal                                           
-- Installing: D:/Dev/rez/vcpkg/packages/yoga_x86-windows/include/yoga/internal/experiments-inl.h                         
-- Installing: D:/Dev/rez/vcpkg/packages/yoga_x86-windows/include/yoga/internal/experiments.h                             
-- Installing: D:/Dev/rez/vcpkg/packages/yoga_x86-windows/include/yoga/log.h                                              
-- Installing: D:/Dev/rez/vcpkg/packages/yoga_x86-windows/include/yoga/Utils.h                                            
-- Installing: D:/Dev/rez/vcpkg/packages/yoga_x86-windows/include/yoga/YGConfig.h                                         
-- Installing: D:/Dev/rez/vcpkg/packages/yoga_x86-windows/include/yoga/YGEnums.h                                          
-- Installing: D:/Dev/rez/vcpkg/packages/yoga_x86-windows/include/yoga/YGFloatOptional.h                                  
-- Installing: D:/Dev/rez/vcpkg/packages/yoga_x86-windows/include/yoga/YGLayout.h                                         
-- Installing: D:/Dev/rez/vcpkg/packages/yoga_x86-windows/include/yoga/YGMacros.h                                         
-- Installing: D:/Dev/rez/vcpkg/packages/yoga_x86-windows/include/yoga/YGNode.h                                           
-- Installing: D:/Dev/rez/vcpkg/packages/yoga_x86-windows/include/yoga/YGNodePrint.h                                      
-- Installing: D:/Dev/rez/vcpkg/packages/yoga_x86-windows/include/yoga/YGStyle.h                                          
-- Installing: D:/Dev/rez/vcpkg/packages/yoga_x86-windows/include/yoga/YGValue.h                                          
-- Installing: D:/Dev/rez/vcpkg/packages/yoga_x86-windows/include/yoga/Yoga-internal.h                                    
-- Installing: D:/Dev/rez/vcpkg/packages/yoga_x86-windows/include/yoga/Yoga.h                                             
-- Installing: D:/Dev/rez/vcpkg/packages/yoga_x86-windows/lib/yogacore.lib                                                
-- Installing: D:/Dev/rez/vcpkg/packages/yoga_x86-windows/debug/lib/yogacore.lib                                          
-- Installing: D:/Dev/rez/vcpkg/packages/yoga_x86-windows/share/yoga/copyright                                            
-- Performing post-build validation                                                                                       
-- Performing post-build validation done                                                                                  
Stored binary cache: C:\Users\cmaughan\AppData\Local\vcpkg\archives\b2\b21f8f3b53d66f476f4e4f2f2c92630f2ed7eb24.zip       
Building package yoga[core]:x86-windows... done                                                                           
Installing package yoga[core]:x86-windows...                                                                              
Installing package yoga[core]:x86-windows... done                                                                         
Elapsed time for package yoga:x86-windows: 13.03 s

**Comment by PhoebeHui** [comment]
@cmaughan, could you also report this issue to Upstream as well? it's better to support this officially.

**Comment by cmaughan** [comment]
Yes, will do.
