### ISSUE TITLE
[draco] Can't link drakodec.lib with target_link_libraries, usage file missing

### ISSUE THREAD

**Issue by MrROBUST** [microsoft/vcpkg#15527]
Hello, after installing this library in vcpkg, it doesn't show how to use it.

I am trying to use the [draco] decoding support of the [tinygltf] library with this simple program example (main.cpp):

> ```
> #include <nlohmann\json.hpp>
> 
> #define TINYGLTF_NO_STB_IMAGE
> #define TINYGLTF_NO_STB_IMAGE_WRITE
> #define TINYGLTF_IMPLEMENTATION
> #define TINYGLTF_NO_INCLUDE_JSON
> #define TINYGLTF_ENABLE_DRACO
> #include <tiny_gltf.h>
> 
> int main()
> {
>   using namespace tinygltf;
> 
>   Model model;
>   TinyGLTF loader;
>   std::string err;
>   std::string warn;
> 
>   if (!loader.LoadBinaryFromFile(&model, &err, &warn, "models/viking_room.glb"))
>   {
>     throw std::runtime_error(warn + "\n" + err);
>   }
> 
>   return EXIT_SUCCESS;
> }
> ```

CMakeLists.txt

> ```
> cmake_minimum_required (VERSION 3.8)
> 
> project(TinyGltfDraco)
> 
> add_executable(TinyGltfDraco main.cpp)
> 
> set_target_properties(TinyGltfDraco
> PROPERTIES
>   CXX_STANDARD 17
>   CXX_EXTENSIONS OFF
> )
> 
> find_package(nlohmann_json CONFIG REQUIRED)
> target_link_libraries(TinyGltfDraco PRIVATE nlohmann_json nlohmann_json::nlohmann_json)
> 
> find_path(TINYGLTF_INCLUDE_DIRS "tiny_gltf.h")
> target_include_directories(TinyGltfDraco PRIVATE ${TINYGLTF_INCLUDE_DIRS})
> ```

The project is built by Cmake using the vcpkg toolkit. Building with the Visual Studio 2019 compilers generates some linkage errors:

> [build]   main.cpp
> [build] main.obj : error LNK2019: unresolved external symbol "public: __cdecl draco::Options::Options(void)" (??0Options@draco@@QEAA@XZ) referenced in function "public: __cdecl draco::DracoOptions<enum draco::GeometryAttribute::Type>::DracoOptions<enum draco::GeometryAttribute::Type>(void)" (??0?$DracoOptions@W4Type@GeometryAttribute@draco@@@draco@@QEAA@XZ) [%path%\build\TinyGltfDraco.vcxproj]

It looks like Draco header files can be found automatically with no additions to CMakeLists, but dracodec.lib or draco.lib is not passed to the linker.

If I add these lines to CMakeLists:

> ```
> find_package(Draco CONFIG REQUIRED)
> target_link_libraries(TinyGltfDraco PRIVATE draco)
> ```

I got that error:

> [build] LINK : fatal error LNK1104: cannot open file 'draco.lib' [%path%\build\TinyGltfDraco.vcxproj]

But something like this works (for a debug build):

> ```
> find_package(Draco CONFIG REQUIRED)
> target_link_libraries(TinyGltfDraco PRIVATE "${draco_LIBRARY_DIR}/../debug/lib/dracodec.lib")
> ```

I am wondering if I am doing something wrong or the port is missing some exports?

**Additional context:**
Draco's github page says we need to link the draco_dec (https://github.com/google/draco#c-decoder-api) but it's probably a typo (https://stackoverflow.com/questions/62313136/how-to-include-the-draco-dec-library). I have both draco.lib and dracodec.lib working so I'm not sure what should be linked by default. Should these be separate targets, like: `target_link_libraries(TinyGltfDraco PRIVATE draco::draco)` or `target_link_libraries(TinyGltfDraco PRIVATE draco::dracodec)`?

**Comment by NancyLi1013** [comment]
Hi @MrROBUST 

Thanks for posting this issue.

It seems that there are no CMake config and targets files for `draco `now.

So you cannot use `find_package()`.

**Comment by JackBoosY** [comment]
I think draco expoted `DracoConfig.cmake` is incomplete. It only contains difficult macros.

**Comment by LesleyLai** [comment]
Draco updated to 1.5.0 and reworked its `find_package` support in [this PR](https://github.com/google/draco/pull/775). Probably that will fix the issue once vcpkg supports Draco 1.5.0

**Comment by JackBoosY** [comment]
@LesleyLai  No it wasn't.
The draco-config.cmake still can't be used in Windows.

**Comment by JackBoosY** [comment]
I opened a PR to the upstream to fix this issue: https://github.com/google/draco/pull/787
Let's see what happened.

**Comment by LesleyLai** [comment]
Thank you for doing this!

**Comment by Tradias** [comment]
Since draco 1.5.3 there is now a proper dracoConfig.cmake + dracoTargets.cmake which support imported targets. The usage information is also helpful now:

```
 draco provides CMake targets:
 
     # this is heuristically generated, and may not be correct
     find_package(draco CONFIG REQUIRED)
     target_link_libraries(main PRIVATE draco::draco)

```

See https://github.com/microsoft/vcpkg/pull/27145
