### ISSUE TITLE
opencv:x64-uwp has issue

### ISSUE THREAD

**Issue by bigdimboom** [Microsoft/vcpkg#1552]
Error: Building package opencv:x64-uwp failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: opencv:x64-uwp
  Vcpkg version: 0.0.81-59792e9e463d3781c7b95d96c49e24e1f9b7f154

**Comment by bigdimboom** [comment]
![image](https://user-images.githubusercontent.com/6119906/28831482-ab9c5a92-76a7-11e7-8213-7a57fa919d3e.png)

**Comment by ras0219-msft** [comment]
Hi, thanks for reporting this issue!

I'm unable to reproduce the problem locally; could you attach the package-x64-uwp-rel-*.log files mentioned in the error message?

**Comment by JackBoosY** [comment]
Hi @bigdimboom , please open a new issue if this is still a problem for you.
Thx.
