### ISSUE TITLE
[mlpack[tools]:x64-windows] build failure

### ISSUE THREAD

**Issue by shubhamr2511** [microsoft/vcpkg#15535]
**Host Environment**
- OS: Windows 10 Pro
- Compiler: MinGW-w64 8.1.0

**To Reproduce**
`./vcpkg install mlpack[tools]:x64-windows`

**Failure logs** 

Starting package 164/164: mlpack:x64-windows
Building package mlpack[core,tools]:x64-windows...
-- Downloading https://github.com/mlpack/mlpack/archive/7ae9ddda86c1751b6509ceb48b27d182feaae439.tar.gz...
-- Extracting source C:/Users/Shubham/vcpkg/vcpkg/downloads/mlpack-mlpack-7ae9ddda86c1751b6509ceb48b27d182feaae439.tar.gz
-- Applying patch cmakelists.patch
-- Using source at C:/Users/Shubham/vcpkg/vcpkg/buildtrees/mlpack/src/82feaae439-2cf793ee94.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:145 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Release --target install -- -v -j9
    Working Directory: C:/Users/Shubham/vcpkg/vcpkg/buildtrees/mlpack/x64-windows-rel
    See logs for more information:
      C:\Users\Shubham\vcpkg\vcpkg\buildtrees\mlpack\install-x64-windows-rel-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:27 (vcpkg_build_cmake)
  ports/mlpack/portfile.cmake:37 (vcpkg_install_cmake)
  scripts/ports.cmake:136 (include)

Error: Building package mlpack:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: mlpack:x64-windows
  Vcpkg version: 2020.11.12--unknownhash

**Additional context**
checked for latest portfiles:
C:\Users\Shubham\vcpkg\vcpkg>.\vcpkg update
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.

How this issue can be resolved ?

**Comment by StarGate-One** [comment]
Please attach the file `C:\Users\Shubham\vcpkg\vcpkg\buildtrees\mlpack\install-x64-windows-rel-out.log` to this issue in the dashed box below the write tab and above the comment button

**Comment by shubhamr2511** [comment]
[install-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/5789760/install-x64-windows-rel-out.log)

**Comment by StarGate-One** [comment]
>C:\Users\Shubham\vcpkg\vcpkg\buildtrees\mlpack\src\82feaae439-2cf793ee94.clean\src\mlpack\core\util\io_impl.hpp(34) : **fatal error C1001: Internal compiler error.**
(compiler file 'd:\A01\_work\3\s\src\vctools\Compiler\Utc\src\p2\main.c', line 212)
 To work around this problem, try simplifying or changing the program near the locations listed above.
If possible please provide a repro here: https://developercommunity.visualstudio.com 
Please choose the Technical Support command on the Visual C++ 
 Help menu, or open the Technical Support help file for more information

I would suggest making sure the compiler/linker are up to date.

Hopefully someone else may have a suggestion.

**Comment by longnguyen2004** [comment]
If you want to use a Mingw-w64 toolchain, you need to use the `x64-mingw-statc` or `x64-mingw-dynamic` triplet, not `x64-windows`

**Comment by shubhamr2511** [comment]
@longnguyen2004 thanks!

**Comment by longnguyen2004** [comment]
@shubhamr2511 Are there any other problems?

**Comment by PhoebeHui** [comment]
@shubhamr2511, please reopen this issue if it still be problem for you.
