### ISSUE TITLE
What about supports for auto checking for different C++ standards?

### ISSUE THREAD

**Issue by playgithub** [microsoft/vcpkg#15539]
some package in vcpkg repo doesn't support C++ 17 well, it can block the job.
What about let auto checking on github check for different C/C++ standards.

**Comment by JackBoosY** [comment]
Hmm... How can we do that?
@BillyONeal Do you have any suggestions?

**Comment by BillyONeal** [comment]
I don't have any such suggestions. Generally speaking well-behaved ports don't care about the consuming project's standard mode being greater than that the port uses.

**Comment by playgithub** [comment]
@BillyONeal 
> I don't have any such suggestions. Generally speaking well-behaved ports don't care about the consuming project's standard mode being greater than that the port uses.

When building `poppler` in C++17, I have found 2 ports that are not C++17 compatible:
* https://github.com/libjpeg-turbo/libjpeg-turbo (fixed)
* https://github.com/boostorg/exception (blocking my project now)

I know it's time consuming to check for different C/C++ standards, but in the future, when newer C++ standard become a default compiler option, some port will not work by default. Is it a problem?

**Comment by JackBoosY** [comment]
@playgithub Yep, but before that, upstream should already support cxx17.
