### ISSUE TITLE
[cpprestsdk] build failure

### ISSUE THREAD

**Issue by Fechulo** [microsoft/vcpkg#15536]
**Host Environment**
- OS: Windows 10
- Compiler: Visual Studio 2019 (I'm not sure that's what you're looking for)

**To Reproduce**
`.vcpkg install cpprestsdk`

**Failure logs** 
```
1>   Creating library C:\Users\fhand\source\repos\VATeirPlugin\Debug\VATeirPlugin.lib and object C:\Users\fhand\source\repos\VATeirPlugin\Debug\VATeirPlugin.exp
1>CVATeirPlugin.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __thiscall web::uri::uri(unsigned short const *)" (__imp_??0uri@web@@QAE@PBG@Z) referenced in function "public: virtual void __thiscall CVATeirPlugin::OnTimer(int)" (?OnTimer@CVATeirPlugin@@UAEXH@Z)
1>C:\Users\fhand\source\repos\VATeirPlugin\Debug\VATeirPlugin.dll : fatal error LNK1120: 1 unresolved externals
1>Done building project "VATeirPlugin.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Additional context**
I'm not sure whether this is the right place to post, but any help would be appreciated. I'm trying to implement a simple websocket client using the cpprest library. I'm using [this thread](https://stackoverflow.com/questions/34423092/websocket-library) for reference. I installed vcpkg as per the readme on this repo, and installed cpprest as per the readme [here](https://github.com/Microsoft/cpprestsdk). For some reason I'm getting a link error when trying to build the project. I've tried linking the library manually but it doesn't work either (I'm quite new to this all so I could be doing this wrong but as I understand vcpkg should handle it all for me). I briefly tried using a different library and I didn't have any issues when building the project. I also tried using the cpprest library (using the same code) on a console app as opposed to an MFC dll, and it worked fine there. I'm aware there is likely something I'm missing and not a bug with vcpkg but I'd appreciate a few pointers.

Thanks

**Comment by mathisloge** [comment]
I think you need to provide a bit more information. How does your cmake look or how do you invoke your compiler?

**Comment by Fechulo** [comment]
Hi @mathisloge thanks for getting back to me. I'm not sure I know how to answer those questions to be honest. I'm not using cmake (not knowingly anyway), I'm letting Visual Studio do the work for me. I'm using the MFC Dynamic-Link Library project template and building and testing the solution through VS. I hope that helps?

**Comment by NancyLi1013** [comment]
Hi @Fechulo 

Thanks for posting this issue.

Could you please help provide your project case?

**Comment by Fechulo** [comment]
Hi @NancyLi1013, sorry for my ineptitude but could you clarify what you mean by project case? I'm happy to provide any information you need, I'll just need a bit more help as I'm very unfamiliar with well all of this...

**Comment by NancyLi1013** [comment]
How do you use `cpprestsdk` in your project? Please provide the code here.

**Comment by Fechulo** [comment]
After doing some more research, I came across a thread in cpprestsdk's github page, that described a similar issue. It seems to be an incompatibility between cpprestsdk and another library I'm using (On requires WChar_t to be treated as a built-in type, the other one requires it not to be). I still haven't gotten the code to work, but I'm confident enough that the problem has nothing to do with vcpkg (as I originally thought). Thanks for your help, closing :)
