### ISSUE TITLE
HttpSendRequest fails with error code 12029

### ISSUE THREAD

**Issue by Straubm** [microsoft/vcpkg#15532]
Hi there,
this is my first post here, so greetings to all.

Since a few days, out of the blue, I'm getting a HttpSendRequest error 12029 when installing a package. That's from Windows 10 cmd.
The URL works in the browser though.

I did not change anything AFAIK. Might be there was a WIndows update meanwhile.

Any ideas?

**Comment by StarGate-One** [comment]
>HttpSendRequest error 12029

Cause
This problem occurs because Windows is not configured to use TLS 1.2 or 1.3 protocol and the hosted site has disabled support for TLS 1.0 and 1.1 in their on-premises environment (TLS 1.0 and 1.1 are nearing end-of-life, not to mention a security risk and many hosting sites have started disabling/phasing it out). 

Error "12029" is a WinHTTP error code that indicates that a socket connection failed because encrypted communication could not be established.

- Your browser (Chrome, Edge, FireFox, Brave, Opera, etc are independently TLS 1.2 and 1.3 enabled) works independently from Windows
- Windows and vcpkg uses the internal winhttp to download files.

**Comment by Straubm** [comment]
TLS 1.1, TLS 1.2, TLS 1.3 both are enabled for winhttp (at least now). I checked the relevant registry keys.

Still no luck.

Btw, the mirror site/file is https://github.com/Kitware/CMake/releases/download/v3.19.2/cmake-3.19.2-win32-x86.zip

But then, thanks for your help anyways.

 

Von: StarGate-One <notifications@github.com> 
Gesendet: 08 January 2021 23:49
An: microsoft/vcpkg <vcpkg@noreply.github.com>
Cc: Martin Straub <Develop@worldinone.at>; Author <author@noreply.github.com>
Betreff: Re: [microsoft/vcpkg] HttpSendRequest fails with error code 12029 (#15532)

 

HttpSendRequest error 12029

Cause
This problem occurs because Windows is not configured to use TLS 1.2 or 1.3 protocol and the hosted site has disabled support for TLS 1.0 and 1.1 in their on-premises environment (TLS 1.0 and 1.1 are nearing end-of-life, not to mention a security risk and many hosting sites have started disabling/phasing it out).

Error "12029" is a WinHTTP error code that indicates that a socket connection failed because encrypted communication could not be established.

*	Your browser (Chrome, Edge, FireFox, Brave, Opera, etc are independently TLS 1.2 and 1.3 enabled) works independently from Windows
*	Windows and vcpkg uses the internal winhttp to download files.

**Comment by Straubm** [comment]
Ah, on more question. Which IP ports are used for the connection?

 

Von: StarGate-One <notifications@github.com> 
Gesendet: 08 January 2021 23:49
An: microsoft/vcpkg <vcpkg@noreply.github.com>
Cc: Martin Straub <Develop@worldinone.at>; Author <author@noreply.github.com>
Betreff: Re: [microsoft/vcpkg] HttpSendRequest fails with error code 12029 (#15532)

 

HttpSendRequest error 12029

Cause
This problem occurs because Windows is not configured to use TLS 1.2 or 1.3 protocol and the hosted site has disabled support for TLS 1.0 and 1.1 in their on-premises environment (TLS 1.0 and 1.1 are nearing end-of-life, not to mention a security risk and many hosting sites have started disabling/phasing it out).

Error "12029" is a WinHTTP error code that indicates that a socket connection failed because encrypted communication could not be established.

*	Your browser (Chrome, Edge, FireFox, Brave, Opera, etc are independently TLS 1.2 and 1.3 enabled) works independently from Windows
*	Windows and vcpkg uses the internal winhttp to download files.

**Comment by Straubm** [comment]
I'm closing the issue. Obviously vcpkg is not involved. After downloading one or two files manually, package installation miraculously worked. I'm suspecting it's the virus protection (Bitdefender). Not so much that it would block something (there would be an alert/report), I feel it's more of a timing issue. Why that should lead to error 12029 I cannot conceive.
