### ISSUE TITLE
Failed builds result in silent removal of packages to be upgraded

### ISSUE THREAD

**Issue by wolfpld** [microsoft/vcpkg#15534]
Duplicate of #13892, as expected, as there was no proper fix for the original issue, due to lack of interest in understanding the core problem here.

```
[19:46 wolf@oberon:/mnt/c/vcpkg]% git pull
From https://github.com/Microsoft/vcpkg
   981e65ce0..2a42024b5  master     -> origin/master

> bootstrap.bat...

[19:46 wolf@oberon:/mnt/c/vcpkg]% ./vcpkg.exe update
Using local portfile versions. To update the local portfiles, use `git pull`.
The following packages differ from their port versions:
    avisynthplus:x64-windows         3.6.0#1 -> 3.6.1
    curl:x64-windows                 7.74.0 -> 7.74.0#1
    freetype:x64-windows-static      2.10.2#6 -> 2.10.4
    sdl2:x64-windows                 2.0.12#8 -> 2.0.14

To update these packages and all dependencies, run
    .\vcpkg upgrade

To only remove outdated packages, run
    .\vcpkg remove --outdated

[19:46 wolf@oberon:/mnt/c/vcpkg]% ./vcpkg.exe upgrade --no-dry-run
A suitable version of cmake was not found (required v3.19.2). Downloading portable cmake v3.19.2...
Downloading cmake...
  https://github.com/Kitware/CMake/releases/download/v3.19.2/cmake-3.19.2-win32-x86.zip -> C:\vcpkg\downloads\cmake-3.19.2-win32-x86.zip
Extracting cmake...
The following packages will be rebuilt:
  * avisynthplus[core]:x64-windows -> 3.6.1
  * curl[core,non-http,schannel,ssl,sspi,winssl]:x64-windows -> 7.74.0#1
  * freetype[brotli,bzip2,core,png,zlib]:x64-windows-static -> 2.10.4
  * sdl2[core,vulkan]:x64-windows -> 2.0.14
Additional packages (*) will be modified to complete this operation.
Starting package 1/8: avisynthplus:x64-windows
Removing package avisynthplus:x64-windows...
Removing package avisynthplus:x64-windows... done
Elapsed time for package avisynthplus:x64-windows: 20.67 ms
Starting package 2/8: curl:x64-windows
Removing package curl:x64-windows...
Removing package curl:x64-windows... done
Elapsed time for package curl:x64-windows: 23.17 ms
Starting package 3/8: freetype:x64-windows-static
Removing package freetype:x64-windows-static...
Removing package freetype:x64-windows-static... done
Elapsed time for package freetype:x64-windows-static: 34.24 ms
Starting package 4/8: sdl2:x64-windows
Removing package sdl2:x64-windows...
Removing package sdl2:x64-windows... done
Elapsed time for package sdl2:x64-windows: 32.73 ms
Detecting compiler hash for triplet x64-windows...
A suitable version of powershell-core was not found (required v7.1.0). Downloading portable powershell-core v7.1.0...
Downloading powershell-core...
  https://github.com/PowerShell/PowerShell/releases/download/v7.1.0/PowerShell-7.1.0-win-x86.zip -> C:\vcpkg\downloads\PowerShell-7.1.0-win-x86.zip
Failed to download from mirror set:
https://github.com/PowerShell/PowerShell/releases/download/v7.1.0/PowerShell-7.1.0-win-x86.zip: WinHttpReceiveResponse() failed: 12152

[19:47 wolf@oberon:/mnt/c/vcpkg]% ./vcpkg.exe upgrade --no-dry-run
All installed packages are up-to-date with the local portfiles.
```

Left with broken environment and unable to easily redo the upgrade operation...

**Comment by StarGate-One** [comment]
@wolfpld To be honest I stopped using vcpkg upgrade about 3-4 months ago. 
It is problematic and seems to have been forgotten functionality in the zest to add new features.
- There is no help documentation `vcpkg help upgrade` give Error: unknown topic upgrade
- When it fails there is no recovery, except manual methods
- The option to download with aria2c does not exist
- The option of --editable  does not exist
- It deletes the source after it is done (some SOX compliancy requires us to keep sources)
What I have done is create a script which basically does this:
- Run the `vcpkg upgrade` command and capture the output to a file
- Massage the data in the file into a temp script added by the original script with only 1 command:
  `set vcpkg_ports_to_upgrade=[port]:[triplet] [port]:[triplet] [port]:[triplet]` etc etc etc
- The original scripts runs the temp script, setting the environment variable then runs 2 functions:
  `.\vcpkg.exe remove --recurse %vcpkg_ports_to_upgrade%`
  `.\vcpkg.exe install --x-use-aria2 --keep-going %vcpkg_ports_to_upgrade%`
- Everything is ported to a log file I can review
- It is not foolproof, as when a when a change is made to a port which now makes it fail, or a feature of the port is removed, but it only effects that port and any ports depending on it (a cascade effect), the rest or the ports will continue to install.
- But it is logged and I have a temp cmd file listing all the ports we are working for.
- Although a manual process it is much much easier to recovery from, plus it eliminates my issues with sources being deleted, the sources can be editable, it is as buggy as the upgrade command and I can use aria2c as a download tool.

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/4360.
