### ISSUE TITLE
[intel-mkl] not detecting intel mkl from Intel oneAPI

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#15548]
OneAPI MKL is located in 
`Program Files (x86)/Intel/oneAPI/mkl/latest`

and not 
`Program Files (x86)/IntelSWTools/compilers_and_libraries/windows`

**Comment by StarGate-One** [comment]
Similar - same software, directory changed - different platform(s) `[intel-mkl:x64-linux] build failure` #15204

**Comment by Voskrese** [comment]
ENV = INTEL_ROOT

`Program Files (x86)/Intel/oneAPI/mkl/latest`

or

`Program Files (x86)/IntelSWTools/compilers_and_libraries/windows`

?

**Comment by JackBoosY** [comment]
Will be fixed in #15233.

**Comment by MVoz** [comment]
OpenAPI only VS 2017 and VS 2019 ?

![2021-02-03_075816](https://user-images.githubusercontent.com/10104740/106700419-c7616400-661f-11eb-8e0f-7879ed41bc18.png)

**Comment by MVoz** [comment]
oneAPI 
`C:\Program Files (x86)\Intel\oneAPI\mkl\latest\env` -->> **vars.bat**
![2021-02-03_080957](https://user-images.githubusercontent.com/10104740/106703648-9edc6880-6625-11eb-90cf-4dc321354dc7.png)
![2021-02-03_081207](https://user-images.githubusercontent.com/10104740/106703663-a56ae000-6625-11eb-8a95-1966feab6c3b.png)

**Comment by LYP951018** [comment]
My workaround here:

It seems that Intel changed MKL's versioning strategy (mkl_version.h):

```cpp
#define INTEL_MKL_VERSION      202101
```

So I first changed `MKL_REQUIRED_VERSION` variable to `202000` defined at ports\intel-mkl\portfile.cmake

And then tried

```powershell
$env:MKLROOT="C:\Program Files (x86)\Intel\oneAPI\mkl\latest"
$env:VCPKG_KEEP_ENV_VARS="MKLROOT"
vcpkg install intel-mkl:x64-windows
```

**Comment by 9prady9** [comment]
Why aren't all environment variables passed down automatically ? what is the reason behind this choice ?

**Comment by JackBoosY** [comment]
@9prady9 Not all the env vars are passed down.
