### ISSUE TITLE
Error: Building package boost-build:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by byliut** [microsoft/vcpkg#15550]
When asking a question please also include where you looked for an answer (so we can update the documentation if needed).
operating system: windows 10 2004
when i execute "vcpkg install pcl", it shows like that:
C:\dev\vcpkg\vcpkg>vcpkg  install pcl
Computing installation plan...
The following packages will be built and installed:
  * boost-algorithm[core]:x86-windows -> 1.75.0
  * boost-align[core]:x86-windows -> 1.75.0
  * boost-any[core]:x86-windows -> 1.75.0
  * boost-asio[core]:x86-windows -> 1.75.0
  * boost-atomic[core]:x86-windows -> 1.75.0
  * boost-bimap[core]:x86-windows -> 1.75.0
  * boost-build[core]:x86-windows -> 1.75.0.beta1#1
  * boost-chrono[core]:x86-windows -> 1.75.0
  * boost-circular-buffer[core]:x86-windows -> 1.75.0
  * boost-container[core]:x86-windows -> 1.75.0
  * boost-container-hash[core]:x86-windows -> 1.75.0
  * boost-context[core]:x86-windows -> 1.75.0
  * boost-conversion[core]:x86-windows -> 1.75.0
  * boost-coroutine[core]:x86-windows -> 1.75.0
  * boost-date-time[core]:x86-windows -> 1.75.0
  * boost-dynamic-bitset[core]:x86-windows -> 1.75.0
  * boost-endian[core]:x86-windows -> 1.75.0
  * boost-exception[core]:x86-windows -> 1.75.0
  * boost-filesystem[core]:x86-windows -> 1.75.0
  * boost-foreach[core]:x86-windows -> 1.75.0
  * boost-format[core]:x86-windows -> 1.75.0
  * boost-function[core]:x86-windows -> 1.75.0
  * boost-function-types[core]:x86-windows -> 1.75.0
  * boost-functional[core]:x86-windows -> 1.75.0
  * boost-fusion[core]:x86-windows -> 1.75.0
  * boost-graph[core]:x86-windows -> 1.75.0
  * boost-integer[core]:x86-windows -> 1.75.0
  * boost-interprocess[core]:x86-windows -> 1.75.0
  * boost-intrusive[core]:x86-windows -> 1.75.0
  * boost-io[core]:x86-windows -> 1.75.0
  * boost-iostreams[core]:x86-windows -> 1.75.0
  * boost-iterator[core]:x86-windows -> 1.75.0
  * boost-lambda[core]:x86-windows -> 1.75.0
  * boost-lexical-cast[core]:x86-windows -> 1.75.0
  * boost-math[core]:x86-windows -> 1.75.0
  * boost-modular-build-helper[core]:x86-windows -> 1.75.0#2
  * boost-move[core]:x86-windows -> 1.75.0
  * boost-mp11[core]:x86-windows -> 1.75.0
  * boost-mpl[core]:x86-windows -> 1.75.0
  * boost-multi-array[core]:x86-windows -> 1.75.0
  * boost-multi-index[core]:x86-windows -> 1.75.0
  * boost-multiprecision[core]:x86-windows -> 1.75.0
  * boost-numeric-conversion[core]:x86-windows -> 1.75.0
  * boost-optional[core]:x86-windows -> 1.75.0
  * boost-parameter[core]:x86-windows -> 1.75.0
  * boost-phoenix[core]:x86-windows -> 1.75.0
  * boost-pool[core]:x86-windows -> 1.75.0
  * boost-predef[core]:x86-windows -> 1.75.0
  * boost-property-map[core]:x86-windows -> 1.75.0
  * boost-property-tree[core]:x86-windows -> 1.75.0
  * boost-proto[core]:x86-windows -> 1.75.0
  * boost-ptr-container[core]:x86-windows -> 1.75.0
  * boost-random[core]:x86-windows -> 1.75.0
  * boost-range[core]:x86-windows -> 1.75.0
  * boost-ratio[core]:x86-windows -> 1.75.0
  * boost-rational[core]:x86-windows -> 1.75.0
  * boost-regex[core]:x86-windows -> 1.75.0
  * boost-serialization[core]:x86-windows -> 1.75.0
  * boost-signals2[core]:x86-windows -> 1.75.0
  * boost-smart-ptr[core]:x86-windows -> 1.75.0
  * boost-sort[core]:x86-windows -> 1.75.0
  * boost-spirit[core]:x86-windows -> 1.75.0
  * boost-system[core]:x86-windows -> 1.75.0
  * boost-test[core]:x86-windows -> 1.75.0
  * boost-thread[core]:x86-windows -> 1.75.0
  * boost-tokenizer[core]:x86-windows -> 1.75.0
  * boost-tti[core]:x86-windows -> 1.75.0
  * boost-tuple[core]:x86-windows -> 1.75.0
  * boost-type-index[core]:x86-windows -> 1.75.0
  * boost-typeof[core]:x86-windows -> 1.75.0
  * boost-unordered[core]:x86-windows -> 1.75.0
  * boost-utility[core]:x86-windows -> 1.75.0
  * boost-uuid[core]:x86-windows -> 1.75.0
  * boost-variant[core]:x86-windows -> 1.75.0
  * boost-winapi[core]:x86-windows -> 1.75.0
  * boost-xpressive[core]:x86-windows -> 1.75.0
  * bzip2[core]:x86-windows -> 1.0.8#1
  * eigen3[core]:x86-windows -> 3.3.9
  * flann[core]:x86-windows -> 2019-04-07#1
  * liblzma[core]:x86-windows -> 5.2.5#2
  * libpng[core]:x86-windows -> 1.6.37#14
  * lz4[core]:x86-windows -> 1.9.2-2
  * openssl[core]:x86-windows -> 1.1.1h#5
    pcl[core]:x86-windows -> 1.11.1#1
  * qhull[core]:x86-windows -> 8.0.2
  * xxhash[core]:x86-windows -> 0.8.0#1
  * zlib[core]:x86-windows -> 1.2.11#9
  * zstd[core]:x86-windows -> 1.4.5#1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x86-windows...
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\7c\7c34c0abfbb0562e56b0293849df76c137b763ef.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\b7\b764d08cc80982e70d2847365d69320bc375997f.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\5c\5c7f81dce21a127814ac1cc92a38eb9026ae19f1.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\d8\d87e847c01c820ed359b001e2a6aa8fa1b3934dd.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\c2\c2adc88d318d6c5b6ed470453a5cf98341547986.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\78\78efff020dc2cdedefe6adda2affbc694084e64c.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\20\201d089cf277c11d79637dd3637370479b39575d.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\f6\f64d508aa6e0f3e570dbf36642b4f09e2fdb691f.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\b9\b9fdc66ca5fa263ba53f8650c7fae7c091465c97.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\16\1697ea100ae85cd206a4684e73c8671aa725dd30.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\20\2022a89841ce4a096daae5a3731a621659033d62.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\bc\bc5f5836ee97299f004e96a705c476c8eab0d0cd.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\4e\4e1346e81f5acf1780587e516597ac389febdfbe.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\6c\6cbe995a6858cf6c7accee37f777f718529acabb.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\6d\6d696956d03fcc4a9133a4131fd5a1244bfd8d97.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\c4\c4b0255d32190626d3311725afa2cee5d8c29bd7.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\0f\0f29feed31b182673959175ea109429bbed1e5ac.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\c4\c47250e9d8d07ba8226ba5676143a81e074b3804.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\98\983d3c5265fbbe0b0fa5935df7cd014b91968ef4.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\0d\0d3c1950c79351ee7a310a834c0f85e94982379f.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\32\32c00ee2aebf5d03cc4caaead5006a7043366fa1.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\c9\c971f604245600f89c7c21dc38a177942c0fe111.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\e7\e70ec082409afc18090d7eba037fe2e0f0b76118.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\d3\d3fad80f769922bb72d91f12cc955314a24b2333.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\8f\8fd5ad227d70fa1bc8460281eac0fb9dea88a399.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\be\bea3bc00bfc92feb66b745f40caa59bedd48e25b.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\c6\c6969c1ab8b4f36f3580809b4c1e493f9ccdfb11.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\c2\c2fc0401927280ae1fe35f89966aa19f84e0023d.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\c0\c0e7e01a9e8220ea8cef0dacaa5f0405276dd9c9.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\53\532a8c57a501252510f8063ecca21bec863faac9.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\99\9938d7931291cef9aaec0c7af13801eeb5021431.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\b3\b32b550915b91d258f146216db4a3b6b322ef478.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\a0\a086d55c3631abe71975dce8305fb86d3632c092.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\12\12e5507c78e95ec05e8cc884adbee4a305055be1.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\c1\c1dfb8b3fa83fd372db356bc6f7a8cdbc7c032e1.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\ad\ad0f5ae336516b5cb30ef24ddfeeb81d072038c7.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\b8\b8cc91c5ef7a76839705aaf396e0e4c8f9344b7b.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\49\49ef04978b13a40991a40b58df5127afcae398a7.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\77\77977c0f235772c20d25d205f1addf502ad5dcc5.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\54\54c438f65ca2a82ce6b2fcebda261d8a822670ca.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\d2\d287e66bebe2556c098f05f41e2491b59ba25006.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\a3\a324b2427c2477a9800906ab53982b8cec201e7b.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\1c\1c9503c57f393d2c5df09d3e65ab2c582a1ce38d.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\ca\ca04c75631ae85a452ae53fbdb167fc4357ae260.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\de\de37cea3401b6ae77fb05d4eaf234df43966bcb0.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\c4\c487a5048078bb9c41a31b034fb2f5dc8192ebc7.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\8d\8d9cf29dd4ab61242afa943f8a933085650d81a1.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\6c\6cd32fa0107cea78188a2d95e8bc477870d3e5f5.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\cf\cfce439f6bca26aa2d42e892193d99d1b0aa15ec.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\ed\edf8d9dc0b2670cf31a40a9bc672b5d23aba4908.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\81\810c1a1790b5be27e26d5c6dd1af0a87e413743d.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\64\64f5acd13cd059cc5801e0e895cb708e76f87ec2.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\14\142f8231c6eed03caf251b9b7a54a91b0d423f52.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\3d\3dc810bd88815e58ec8cf33723bedff0345b99f8.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\ee\ee21a1f2a3954de6ba63030b8f0391033da1256c.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\03\03270de6f74cb9de6aee92c20b2d2fee663228ca.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\88\881c04ae5edb64a4a029cc46aed11745e3804713.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\3f\3f5a83749b6322020a0b4116e0a1879415351792.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\11\11c00f732983176d98e83c35879b3e8b560a3066.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\ff\ffcfaebc96f298989b79432939e00f88dd31d652.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\4f\4fed8b9e20ad92fadabd2ba10ef4f2db38e0e8e0.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\0a\0acede83b7937903607526443e45c3b81dfd28c2.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\2e\2ece67208300ac07a54df4ca90f5a62e69dbf35a.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\62\62a14a4ec0e847f8cefd492c6095ecd1cca208ff.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\fb\fb44b937196e19569c84657e98bf7359102c2441.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\9e\9e89a0493b4109ac5f025bcbefd908fa7afa9a02.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\5e\5e6c705380adae28ed6b48753682d0eab9617b54.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\db\db81a1f823063c88e7061095ff0330569c0d613a.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\54\5447f41e5e8a199d2dd3ece2328fbe740a5a04fc.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\34\3403ec6acded9a7482a97e2c53b36876c047c7b2.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\40\40ff7ff6ccdd3aa3921f11aeb77c6faa39377dad.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\e5\e5ff38aa707bd6cfd219cfab98a7a5b1b46b490b.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\a6\a63f19a5e5d54de46df27b86704a568ab9ff4a86.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\72\72321d8d458dc7f1f6cb3fe424ca5fda4dea61e3.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\96\96c17ee572495a395882b3afe6467191b5a4342a.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\2a\2a3038172f3000d2b8c0b4c1d34732c04450b786.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\bd\bd0d2f469cf4303969b00c0437cefd1022693b2a.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\24\2453b3cbad271680b5d77e7d913540beab3c17c2.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\6e\6ec76226b096d5867e8270a356cd88bb37ad27d4.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\e6\e6291148e456c8d1023cab9ab7b69d58dd6a2af6.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\ff\ff046ba0048cc6a29adac305cde4ae2c229978cc.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\69\69f8b981bbec32bede01b6c7a178fad56f0b369e.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\eb\eb80b9c123697f3a041e4deaade3b0d7a6e13247.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\f6\f6350c8e2a595f6cbfb42d38a1af1780704f8bbb.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\57\57bc0b81b53d8670d4dd962c29d82468f7fe843d.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\b7\b7b0cb369808b15f4df51dcbd08afbcbd0d7f966.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\f4\f4a5243aa29085d53d2d4e6671464ebd89a03561.zip
Could not locate cached archive: C:\Users\LT\AppData\Local\vcpkg\archives\b4\b46f9d65883a197b1ef6b78779ac0a0d5acaf1ba.zip
Starting package 1/88: boost-build:x86-windows
Building package boost-build[core]:x86-windows...
-- Using cached C:/dev/vcpkg/vcpkg/downloads/boostorg-build-boost-1.75.0.beta1.tar.gz
-- Cleaning sources at C:/dev/vcpkg/vcpkg/buildtrees/boost-build/src/75.0.beta1-4371cdd5cf.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/dev/vcpkg/vcpkg/downloads/boostorg-build-boost-1.75.0.beta1.tar.gz
-- Applying patch fix_options.patch
-- Using source at C:/dev/vcpkg/vcpkg/buildtrees/boost-build/src/75.0.beta1-4371cdd5cf.clean
-- Using cached C:/dev/vcpkg/vcpkg/downloads/boost_LICENSE_1_0.txt
-- Using cached C:/dev/vcpkg/vcpkg/downloads/boost-1.75.0.beta1-boostcpp.jam
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:105 (message):

  File does not have expected hash:

          File path: [ C:/dev/vcpkg/vcpkg/downloads/boost-1.75.0.beta1-boostcpp.jam ]
      Expected hash: [ 8cf929fa4a602342c859a6bbd5f9dda783ac29431d951bcf6cae4cb14377c1b3aed90bacd902b0f7d1807591cf5e1a244cf8fc3c6cc6e0a4056db145b58f51df ]
        Actual hash: [ 9df059209dcb1759a9b68509868ec11322873183509c3c387427291418f9840922399b286d5da9d09c99329bb08ed423fcdf2ce451b5cd76e81eef1745eff903 ]

  Please delete the file and retry if this file should be downloaded again.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:118 (test_hash)
  ports/boost-build/portfile.cmake:25 (vcpkg_download_distfile)
  scripts/ports.cmake:136 (include)

Error: Building package boost-build:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-build:x86-windows
  Vcpkg version: 2020.11.12--unknownhash

Additionally, attach any relevant sections from the log files above.

I searched in all issues but still failed to solve the problem, did anyone know why？

**Comment by StarGate-One** [comment]
>Please delete the file and retry if this file should be downloaded again.
>I searched in all issues but still failed to solve the problem, did anyone know why

- Delete file `C:/dev/vcpkg/vcpkg/downloads/boost-1.75.0.beta1-boostcpp.jam` and try again. Possible it became corrupt.
- Verified current file hash for `boost-1.75.0.beta1-boostcpp.jam` is `8cf929fa4a602342c859a6bbd5f9dda783ac29431d951bcf6cae4cb14377c1b3aed90bacd902b0f7d1807591cf5e1a244cf8fc3c6cc6e0a4056db145b58f51df`

**Comment by PhoebeHui** [comment]
@byliut, could you try the solution provided by StarGate-One?

**Comment by byliut** [comment]
> > Please delete the file and retry if this file should be downloaded again.
> > I searched in all issues but still failed to solve the problem, did anyone know why
> 
> * Delete file `C:/dev/vcpkg/vcpkg/downloads/boost-1.75.0.beta1-boostcpp.jam` and try again. Possible it became corrupt.
> * Verified current file hash for `boost-1.75.0.beta1-boostcpp.jam` is `8cf929fa4a602342c859a6bbd5f9dda783ac29431d951bcf6cae4cb14377c1b3aed90bacd902b0f7d1807591cf5e1a244cf8fc3c6cc6e0a4056db145b58f51df`
yeah you are right, I deleted the file C:/dev/vcpkg/vcpkg/downloads/boost-1.75.0.beta1-boostcpp.jam and downloaded from https://raw.githubusercontent.com/boostorg/boost/boost-1.75.0.beta1/boostcpp.jam, and vcpkg install pcl, it worked.

**Comment by byliut** [comment]
> @byliut, could you try the solution provided by StarGate-One?

I have try the solution and it works, thank you all.

**Comment by pat18** [comment]
@byliut How did you do this step?
