### ISSUE TITLE
Can we get a roadmap update?

### ISSUE THREAD

**Issue by Starl1ght** [microsoft/vcpkg#15559]
Currently the [roadmap](https://github.com/microsoft/vcpkg/wiki/Roadmap) is kinda outdated, with many features are being still being planned for Dec 20.

Can you update it with current realistic dates?

**Comment by AugP** [comment]
I updated the roadmap with some new dates for things. Registries and versioning are very, very close at this point for us to be able to announce them. VS & VS Code integration is still in the design stages as there are a number of challenges we are trying to plan around.
