### ISSUE TITLE
[New Port Request] V-EZ

### ISSUE THREAD

**Issue by MrROBUST** [microsoft/vcpkg#15566]
Library name: V-EZ

Library description: V-EZ is an open source, cross-platform (Windows and Linux) wrapper intended to alleviate the inherent complexity and application responsibility of using the Vulkan API.

Source repository URL: https://github.com/GPUOpen-LibrariesAndSDKs/V-EZ

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
Requires [vulkan] dependency

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
