### ISSUE TITLE
Whether vcpkg will now accept LLFIO or not?

### ISSUE THREAD

**Issue by ned14** [microsoft/vcpkg#15563]
Historically, LLFIO did not operate a formal release process other than "whatever master branch currently is", and so was unsuitable for distribution by vcpkg.

Seeing as a user asked (https://github.com/ned14/llfio/issues/69), and that as of Nov 2020 LLFIO does now issue formal versioned releases with prebuilt binaries (https://github.com/ned14/llfio/releases), would this situation have changed?

I suspect the remaining problem will be LLFIO's dependencies Outcome and QuickCppLib. Outcome does have a formal versioned release process which tracks the Boost release cycle, and LLFIO is pinned to the last release of Outcome. However, QuickCppLib remains on a pure "whatever master branch currently is" release process.

**Comment by JackBoosY** [comment]
@ned14 We accept adding ports that do not provide a release version, it can use a more stable commit version.

Feel free to open a PR to add LLFIO, and I will help you.

Thanks.

**Comment by ned14** [comment]
I looked into making the Outcome package cmake targets based, rather than the present single header include basis. LLFIO requires proper Outcome beforehand, so it's a good place to start.

The present situation seems similar to back when I last attempted a vcpkg port submission in 2017:

- You disable the use of git by cmake (`find_package(Git)` is force disabled).
- Outcome's cmake therefore can't fetch its _internal_ dependencies.
- Configure therefore fails.

The advice in 2017 was to package up the internal dependencies as vcpkg libraries, but as I said at the time, I don't want those appearing to vcpkg users as libraries being suggested for public use. I'd still hold that opinion.

Now it would seem that in the past three years vcpkg has become dramatically more powerful and can now express internal private dependencies, so I tried this portfile:

```
set(OUTCOME_VERSION v2.2.0)
set(OUTCOME_GITCOMMIT 8d657c8fcf7099da092fdc93e2ee15312a847104)
set(OUTCOME_HASH 94ca56f91a273d4550fc1d80e913ef7ecfb30e249473fc2c8517c5ed0471c3804b1bd12548d77063587fa51dda02c6525a2f3739d37d9d6dfd628bea27b6dcd3)
set(QUICKCPPLIB_HASH 7c07860a18386604a4b25a5962108c57429417fc1684f936591bc9d21be2151797e44dd26c3639a52a02df0d17017c4679b39767001b0019aa805a69341d5f17)

# Install Outcome's private dependency QuickCppLib
vcpkg_download_distfile(
  QUICKCPPLIB_SOURCE_TARBALL
  URLS "https://github.com/ned14/quickcpplib/archive/master.zip"
  FILENAME "quickcpplib-${OUTCOME_GITCOMMIT}.tar.xz"
  SHA512 ${QUICKCPPLIB_HASH}
)

vcpkg_extract_source_archive_ex(
  SKIP_PATCH_CHECK
  OUT_SOURCE_PATH SOURCE_PATH_QUICKCPPLIB
  ARCHIVE "${QUICKCPPLIB_SOURCE_TARBALL}"
  REF "quickcpplib-${OUTCOME_GITCOMMIT}"
)

vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH_QUICKCPPLIB}
    PREFER_NINJA
    OPTIONS
        -DPROJECT_IS_DEPENDENCY=On
)
vcpkg_install_cmake()

vcpkg_fixup_cmake_targets(CONFIG_PATH cmake)

# Now Outcome itself
vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO ned14/outcome
    REF ${OUTCOME_GITCOMMIT} #v2.2.0 
    SHA512 ${OUTCOME_HASH}
    HEAD_REF develop
)

# Use Outcome's own build process, skipping examples and tests
vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA
    OPTIONS
        -DPROJECT_IS_DEPENDENCY=On
)
vcpkg_install_cmake()

vcpkg_fixup_cmake_targets(CONFIG_PATH cmake)

file(INSTALL ${SOURCE_PATH}/License.txt DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)
file(INSTALL ${CMAKE_CURRENT_LIST_DIR}/usage DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT})
```
Alas, quickcpplib still blows up because it can't find git. Before I invest more work in this, I'd like to know if the above approach for handling internal private dependencies would be acceptable to vcpkg lest I waste effort.

**Comment by JackBoosY** [comment]
@ned14 For git, you should use `vcpkg_find_acquire_program(git)`. See example:
https://github.com/microsoft/vcpkg/blob/9c63f97fa1d4915a7dfc5f32d5cdb6ee8fe9bf8b/ports/infoware/portfile.cmake#L21-L32

**Comment by ned14** [comment]
Ok, PR implementing install based Outcome can be found at https://github.com/microsoft/vcpkg/pull/15603. Feedback welcome.

**Comment by ned14** [comment]
Curious what the `requires:discussion` label means in terms of next process?

**Comment by JackBoosY** [comment]
@ned14  The label simply means we will have a discuss.
