### ISSUE TITLE
[openssl] port is hard-coded to compile to x86_64, doesn't support arm64 for Apple M1 chip macs

### ISSUE THREAD

**Issue by heckj** [microsoft/vcpkg#15560]
**Describe the bug**
I installed vcpkg package port openssl with the requested triplet 'arm64-osx' to get an arm64 native openssl library:
`./vcpkg install openssl --triplet arm64-osx`

The resulting binary for the library reports that it's x86_64, even though it's labelled arm64:
```
lipo -info /Users/heckj/bin/vcpkg/installed/arm64-osx/debug/lib/libssl.a
Non-fat file: /Users/heckj/bin/vcpkg/installed/arm64-osx/debug/lib/libssl.a is architecture: x86_64
```

**Environment**
- OS: macOS 11.1 (BigSur) w/ M1 chip MacBook Pro
- Compiler: Xcode 12 (clang)

**To Reproduce**
1. `./vcpkg install openssl --triplet arm64-osx`
2. `lipo -info ./installed/arm64-osx/debug/lib/libssl.a`

`Non-fat file: /Users/heckj/bin/vcpkg/installed/arm64-osx/debug/lib/libssl.a is architecture: x86_64`

**Expected behavior**
Expected the binary to report as arm64

I tracked the issue down the port's CMakeLists.txt, line 27:
```
elseif(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
    set(PLATFORM darwin64-x86_64-cc)
```

**Comment by heckj** [comment]
Digging around for a potential resolution, upstream OpenSSL version 1.1.1i includes a new target from this OpenSSL PR: https://github.com/openssl/openssl/pull/12369 that enables a new configuration target : `darwin64-arm64-cc`

**Comment by lebdron** [comment]
Resolved in https://github.com/microsoft/vcpkg/pull/15298
