### ISSUE TITLE
Allow custom configure options in manifest

### ISSUE THREAD

**Issue by jgbradley1** [microsoft/vcpkg#15562]
**Is your feature request related to a problem?**
A lot of times, it is simpler for a developer to download and build a library from the original git repo due to the need to customize the library build. In this context, I would like to propose an expansion to the list of possible definitions in the manifest to allow for custom configuration of libraries. A good example is building opencv from source where you can enable/disable features that are not needed (i.e. CUDA optimization).

Related issue: https://github.com/microsoft/vcpkg/issues/15459

**Proposed solution**
It would be great if I could declare a manifest file like such

```
{
  "name": "example",
  "version-string": "0.0.1",
  "dependencies": [
    "fmt",
    {
        name: "opencv",
        source_build: true,                                                                # forces a source build instead of using a port (git_url must be defined)
        git_url: "https://github.com/opencv/opencv.git",                                   # url to any git repo (i.e. Github, Gitlab)
        version: "4.4.0",                                                                  # use "master" as default value
        configure_options: "-DBUILD_LIST=core,imgproc -DBUILD_TESTS=OFF -DWITH_GTK=OFF",   # pass additional configure options to the build
    }
  ]
}
```

I made up some of the key names (`source_build`, `git_url`, `configure_options`) to illustrate my point so I'm open to suggestions. If npm `package.json`  rules have a similar command, I would suggest copying their naming.

**Comment by vicroms** [comment]
Hi @jgbradley1 

This is the kind of issue that [port features](https://github.com/microsoft/vcpkg/blob/master/docs/specifications/feature-packages.md) aim to solve.  I concede that they are not as convenient as declaratively toggling the options, but port features are more flexible in that they allow for more complex scenarios where toggling a feature may requires new dependencies to be installed, new patches to be made, special handling of its output, etc.

**Comment by JackBoosY** [comment]
For existing corresponding features, you can set these features to enable or disable. See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/users/manifests.md#features-and-default-features-fields).
For those who don't, you can use overlay-port to solve this issue. See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/specifications/ports-overlay.md).

**Comment by PhoebeHui** [comment]
@jgbradley1, please reopen this issue if it still bother you.
