### ISSUE TITLE
[zlib][x64-uwp] Generated dll can not pass Windows App Certification Validation

### ISSUE THREAD

**Issue by Magicicesea** [microsoft/vcpkg#15570]
I am developing an app with SDK which is directly calling API from curl.dll. So I built these dlls with vcpkg.
Specific command are as following: 
vcpkg install curl[http2,ssl,openssl,ssh] --triplet x64-uwp

I have make some modifications on openssl so it works on uwp. But it failed on some zlib api calls as following:

- API deflate in zlib1.dll is not supported for this application type. libssh2.dll calls this API.
- API deflateEnd in zlib1.dll is not supported for this application type. libssh2.dll calls this API.
- API deflateInit_ in zlib1.dll is not supported for this application type. libssh2.dll calls this API.
- API inflate in zlib1.dll is not supported for this application type. libssh2.dll calls this API.
- API inflateEnd in zlib1.dll is not supported for this application type. libssh2.dll calls this API.
- API inflateInit_ in zlib1.dll is not supported for this application type. libssh2.dll calls this API.
- API inflate in zlib1.dll is not supported for this application type. libcurl.dll calls this API.
- API inflateEnd in zlib1.dll is not supported for this application type. libcurl.dll calls this API.
- API inflateInit2_ in zlib1.dll is not supported for this application type. libcurl.dll calls this API.
- API inflateInit_ in zlib1.dll is not supported for this application type. libcurl.dll calls this API.
- API zlibVersion in zlib1.dll is not supported for this application type. libcurl.dll calls this API. 

I am assuming these API does not work because some of functions inside API is specified for windows.

But when I am confirming with zlibVersion() in zlib.h. I found it just returns a constant version number within same file define it. I am don't understand why it does not work with UWP. 

I think as this lib is for x64-uwp it should be a bug, but if I misunderstanding this problem please let me know.

Backgrounds of this problem: 
vcpkg version: commit a8fa84e4
Target platform: x64 uwp
zlib version: 1.2.11 same as source code.

**Comment by JackBoosY** [comment]
Hmm... @dan-shaw can you please take a look?
I'm not good at uwp build and usage.

**Comment by Magicicesea** [comment]
@JackBoosY Thanks for your reply! And hope @dan-shaw can find some time join our discussion.

Except of this bug, I have another question needs your folks help.  

After analyzing my code I think I can build curl and libssh2 without zlib. I try to modified this line:
file: vcpkg\ports\libssh2\portfile.cmake
line 17 from "-DENABLE_ZLIB_COMPRESSION=ON" to "-DENABLE_ZLIB_COMPRESSION=OFF"
which resolve errors caused by libssh2.

But I try to do the same thing with curl by adding this line:
file: vcpkg\ports\curl\portfile.cmake
line 60+ "-DENABLE_ZLIB_COMPRESSION=OFF" which can not solve the errors in same way.

Am I using vcpkg_configure_cmake() in wrong way? if so how can I build curl without zlib?

Thanks!

**Comment by BillyONeal** [comment]
@Magicicesea vcpkg made sure that these ports build with UWP settings but we haven't actually tried to submit them through the WACK ourselves; if the upstream code is doing something the WACK does not like it's likely that some additional fixes are required either to upstream or to patches vcpkg applies.

**Comment by JackBoosY** [comment]
Close this PR until upstream fixes this.
