### ISSUE TITLE
[pango] update to 1.48.0

### ISSUE THREAD

**Issue by Augus518** [microsoft/vcpkg#15576]
vcpkg only can install pango 1.40, i want to install pango 1.48 ,what can i do?

**Comment by JonLiu1993** [comment]
@Augus518 ,That's not your problem, I will update pango to 1.48.0, and then you can install to 1.48.0

**Comment by Augus518** [comment]
is there any method to update pango version by myself?

**Comment by JonLiu1993** [comment]
I'm updating pango. If you want to know how to update, you can learn about the update issues that have been resolved before.

**Comment by Augus518** [comment]
ok,thank you!

**Comment by JonLiu1993** [comment]
Solved by #17668

**Comment by PhoebeHui** [comment]
Pango has been upgraded to 1.48.4, please get latest source and try again.
