### ISSUE TITLE
Problems using VCPKG_PLATFORM_TOOLSET

### ISSUE THREAD

**Issue by jdx-john** [microsoft/vcpkg#15599]
I have previously built x64-windows against VS2019 `vcpkg install prometheus-cpp --triplet=x64-windows`
I realise I need to target VS2017 with my existing project, which I think should be case of:
```
set VCPKG_PLATFORM_TOOLSET = v141
vcpkg install prometheus-cpp --triplet=x64-windows
```
However it detects the library as already built and does nothing. Does this mean it is not picking up my v141 setting, or merely that it doesn't realise it should rebuild?

A side query, can I pass VCPKG_PLATFORM_TOOLSET directly in a call to install or only as an environment var / triplet script?

**Comment by jdx-john** [comment]
So I've been playing around and it seems simply setting VCPKG_PLATFORM_TOOLSET on my command-line before running vcpkg.exe doesn't work because: _"On Windows, vcpkg builds packages in a special clean environment that is isolated from the current command prompt to ensure build reliability and consistency."_ - https://vcpkg.readthedocs.io/en/latest/users/triplets/#windows-variables

It mentions `VCPKG_ENV_PASSTHROUGH` but I cannot find any instruction how to use this. Looking at the `vcpkg env` command I am very unclear what this is doing, some sort of nested command-prompt to let me see the 'special clean environment' but again nothing I does appears to modify this so I am rather stuck.

**Comment by jdx-john** [comment]
I tried creating my own triplet file x86-windows-v141.cmake:
```
set(VCPKG_TARGET_ARCHITECTURE x86)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_PLATFORM_TOOLSET "v141")

```

But then it's not visible to x86 builds in VC++ after integration. I assume some hard-coded x86/x64 directories are used.
So I just edited the x86-windows with the above. 

Now I get a build error:
```
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:108 (message):
    Command failed: ninja -v
    Working Directory: C:/github/microsoft/vcpkg/buildtrees/prometheus-cpp/x86-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\github\microsoft\vcpkg\buildtrees\prometheus-cpp\config-x86-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:319 (vcpkg_execute_required_process)
  ports/prometheus-cpp/portfile.cmake:24 (vcpkg_configure_cmake)
  scripts/ports.cmake:136 (include)


Error: Building package prometheus-cpp:x86-windows failed with: BUILD_FAILED
```

I saw some reference to Ninja before but I thought VCPKG_PLATFORM_TOOLSET was working fully now?

**Comment by StarGate-One** [comment]
Maybe this will help:
Open a Visual Studio 2017 or 2019 x64 or x86 native command prompt
`cd to [vcpkg-root]`
`set VCPKG_VISUAL_STUDIO_PATH=%VSINSTALLDIR%`
`set VCPKG_PLATFORM_TOOLSET=v141`
`set VCPKG_KEEP_ENV_VARS=VCPKG_PLATFORM_TOOLSET;VCPKG_VISUAL_STUDIO_PATH` any number of environment variables can be added, separating them by a semi-colon. NOTE: you use the environment variable name without the %% signs on windows or $ sign on Linux, and not the values of the variable itself.
`vcpkg env` puts you in a clean vcpkg environment just like when you run `vcpkg install port port port`
`set VCPKG` lists all variables starting with VCPKG
`->VCPKG_PLATFORM_TOOLSET=v141`
`->VCPKG_VISUAL_STUDIO_PATH=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\`
`exit` to return to the native command prompt
Warning, be careful using `VCPKG_KEEP_ENV_VARS` as you could introduce unpredictable results and/or issues which can not be reproduced by the vcpkg team using a vanilla vcpkg. This is why before opening any issue I create a fresh/clean vanilla instance and try to install the problem ports. If the problem port installs cleanly then I know it is something in my local customizations causing it, and it is up to me to trace it down. If the vanilla install fails also, I know it is a vcpkg/port issue and open an issue on the vcpkg github page.

**Comment by JackBoosY** [comment]
I don’t know if we should make judgments based on these contents, @dan-shaw can you please take a look?

Thanks.

**Comment by jdx-john** [comment]
@JackBoos @dan-shaw sorry for the slightly rambling description, the nature of the problem evolved as I was investigating.

My problem is that now my custom trip let appears to be working, I get the error:
`Command failed: ninja -v`

Which suggests forcing v140 is not working properly? I can raise a new bug or edit if it's helpful.

**Comment by JackBoosY** [comment]
@jdx-john Can you provide more info?

Is vcpkg still unable to build normally? Or does the issue become a build failure when using the port installed by vcpkg?

If the issue contents is changed, please close this issue and open a new issue to report that,

Thanks.

**Comment by jdx-john** [comment]
I found this old issue which seems to reference my problem: https://github.com/microsoft/vcpkg/issues/766#issuecomment-285918864
But it's from March 2017 so I had thought this fixed - note it explicitly mentions Ninja.

vcpkg was working fine, until I set `VCPKG_PLATFORM_TOOLSET` so this appears to be the specific thing. If this looks like a genuine issue I'll re-raise a specific bug.
