### ISSUE TITLE
Missing CMAKE defines

### ISSUE THREAD

**Issue by ZeroCrunch** [Microsoft/vcpkg#156]
Is it possible CMAKE_INSTALL_LIBDIR and CMAKE_INSTALL_INCLUDEDIR are not defined?

**Comment by ras0219-msft** [comment]
They are not currently defined anywhere within vcpkg that I'm aware of; if you're authoring a `CMakeLists.txt` I think you need to `include(GNUInstallDirs)` which will provide appropriate defaults. We explicitly designed the final layout to be maximally compatible with those defaults, so portfiles should never need to override them.

https://cmake.org/cmake/help/v3.0/module/GNUInstallDirs.html

**Comment by ZeroCrunch** [comment]
Hmm. Bizarre.

I'm looking at PTex (http://github.com/wdas/ptex). The output I get is:

> CMake Error at CMakeLists.txt:27 (install):
>   install FILES given no DESTINATION!

The CMakeLists.txt refers  to /vcpkg/buildtrees/ptex/src/ptex-2.1.28/src/ptex.

Even if I include(GNUInstallDirs) in the portfile.cmake. Any ideas?


[CONTROL.txt](https://github.com/Microsoft/vcpkg/files/539820/CONTROL.txt)
[portfile.cmake.txt](https://github.com/Microsoft/vcpkg/files/539821/portfile.cmake.txt)
