### ISSUE TITLE
7zip failed while extracting PowerShell-7.1.0-win-x86.zip

### ISSUE THREAD

**Issue by ZhouYangUSTC** [microsoft/vcpkg#15602]
**When I installed vcpkg and started the installation, the following problems occurred, how can I solve them？**

```
vcpkg.exe install eigen3:x64-windows

Computing installation plan...
The following packages will be built and installed:
    eigen3[core]:x64-windows -> 3.3.9
Detecting compiler hash for triplet x64-windows...
A suitable version of powershell-core was not found (required v7.1.0). Downloading portable powershell-core v7.1.0...
Extracting powershell-core...
7zip failed while extracting 'D:\ProgramFile\vcpkg\vcpkg\downloads\PowerShell-7.1.0-win-x86.zip' with message:

7-Zip (a) 18.01 (x86) : Copyright (c) 1999-2018 Igor Pavlov : 2018-01-28

Scanning the drive for archives:
1 file, 91500161 bytes (88 MiB)

Extracting archive: D:\ProgramFile\vcpkg\vcpkg\downloads\PowerShell-7.1.0-win-x86.zip
--
Path = D:\ProgramFile\vcpkg\vcpkg\downloads\PowerShell-7.1.0-win-x86.zip
Type = zip
Physical Size = 91500161

**ERROR: Can not open output file : ܾʡ : D:\ProgramFile\vcpkg\vcpkg\downloads\tools\powershell-core-7.1.0-windows.partial.20496\mi.dll
ERROR: Can not open output file : ܾʡ : D:\ProgramFile\vcpkg\vcpkg\downloads\tools\powershell-core-7.1.0-windows.partial.20496\Microsoft.Management.Infrastructure.Native.Unmanaged.dll
ERROR: Can not open output file : ܾʡ : D:\ProgramFile\vcpkg\vcpkg\downloads\tools\powershell-core-7.1.0-windows.partial.20496\miutils.dll
ERROR: Can not open output file : ܾʡ : D:\ProgramFile\vcpkg\vcpkg\downloads\tools\powershell-core-7.1.0-windows.partial.20496\pwrshplugin.dll
ERROR: Can not open output file : ܾʡ : D:\ProgramFile\vcpkg\vcpkg\downloads\tools\powershell-core-7.1.0-windows.partial.20496\ucrtbase.dll**

Sub items Errors: 5

Archives with Errors: 1

Sub items Errors: 5
```

**Comment by StarGate-One** [comment]
- The PowerShill-7.1.0-win-x86.zip may be corrupted, maybe during download or an aggressive anti-virus program/setting?
- Delete the file `D:\ProgramFile\vcpkg\vcpkg\downloads\PowerShell-7.1.0-win-x86.zip`
- Delete the directory `D:\ProgramFile\vcpkg\vcpkg\downloads\tools\powershell-core-7.1.0-windows`
- Try `vcpkg.exe install eigen3:x64-windows` again. Vcpkg should detect Powershell is missing and download/install it again, hopefully without any corruption this time.

**Comment by PhoebeHui** [comment]
@ZhouYangUSTC, could you try the solution that provided by StarGate-One?

**Comment by ZhouYangUSTC** [comment]
> * The PowerShill-7.1.0-win-x86.zip may be corrupted, maybe during download or an aggressive anti-virus program/setting?
> * Delete the file `D:\ProgramFile\vcpkg\vcpkg\downloads\PowerShell-7.1.0-win-x86.zip`
> * Delete the directory `D:\ProgramFile\vcpkg\vcpkg\downloads\tools\powershell-core-7.1.0-windows`
> * Try `vcpkg.exe install eigen3:x64-windows` again. Vcpkg should detect Powershell is missing and download/install it again, hopefully without any corruption this time.

I tried many times last night but failed,This moring,i tried again and it works.thank u for your help.

**Comment by ZhouYangUSTC** [comment]
> @ZhouYangUSTC, could you try the solution that provided by StarGate-One?

Year,i tried,and it works.thank u.
