### ISSUE TITLE
How do I just do a clean build

### ISSUE THREAD

**Issue by jdx-john** [microsoft/vcpkg#15601]
I've spent ages now trying to do a clean build. Despite deleting pretty much everything, it turns out vcpkg is hiding files outside its own directory.
`
Using cached binary package: C:\Users\jdx-john\AppData\Local\vcpkg\archives\51\513e1e783a43eda643507c366669d62cd8e226cd.zip`

Normal advice is you can have multiple installations, and removing the vcpkg dir should remove everything... clearly not the case. This is getting ridiculous, I'm going to have to give up and spend hours rebuilding every single project for every single triplet I use, because I can't find a way to remove a project and all its dependencies neatly.

**Comment by StarGate-One** [comment]
I do not know if this will help:
- I have 4 instances of vcpkg, test and prod, built with VS2017 and 2019.
- I have 4 VS developer cmd prompts shortcuts, one each environment passed variables of VS2017/VS2019 and prod/test.
- That said those shortcuts set many environment variables, a few which are:
  - `set vcpkg_source=D:\vcpkg`
  - `set VCPKG_ROOT=%vcpkg_source%\%vs_version%\%vs_environment% `where the result is either:
    `D:\vcpkg\vs2017\prod` or `D:\vcpkg\vs2019\prod` or  `D:\vcpkg\vs2017\test` or `D:\vcpkg\vs2019\test`
  - `set VCPKG_DEFAULT_BINARY_CACHE=%VCPKG_ROOT%`
  - `set VCPKG_BINARY_SOURCES=clear;files,%VCPKG_ROOT%\archives,readwrite`
This will put the cached binaries within the vcpkg instance directory structure.

Another option is turn binary caching or other features off using VCPKG_FEATURE_FLAGS
`set VCPKG_FEATURE_FLAGS=-binarycaching,-compilertracking,-manifests,-registries,-versions`

**Comment by jdx-john** [comment]
Do you find/recommend using vs2017 for vs2017 projects rather than try to use 2019?

**Comment by StarGate-One** [comment]
- I try to use VS2019 for any new project, but there are rare exceptions where a new project is created in VS2017 (like supporting binaries where there is no open-source code to build in VS2019 or the open-source does not yet support VS2019). 
- As a general rule the VS2017 is used for only existing projects needing maintenance changes, bugs, security, etc until it is decided to either sunset/end-of-life or upgrade to VS2019 the VS2017 version.

**Comment by NancyLi1013** [comment]
Hi @jdx-john 

Thanks for posting this issue.

I think what makes you feel confused and annoyed is binary caches:

`Using cached binary package: C:\Users\jdx-john\AppData\Local\vcpkg\archives\51\513e1e783a43eda643507c366669d62cd8e226cd.zip`

This is stored in Windows at _C:\Users\usrName\AppData\Local\vcpkg\archives_, which cannot be removed automatically even if  you remove all your vcpkg repos. But you can remove the archive folder manually if you don't need it.

Besides this, if you don't want to store binary caches, there are two ways to disable it while you install any packages:

- passing --no-binarycaching to every vcpkg command line

   add the option --no-binarycaching to vcpkg command, such as vcpkg install sqlite3 --no-binarycaching.

- setting the environment variable VCPKG_FEATURE_FLAGS to -binarycaching

   add VCPKG_FEATURE_FLAGS in environment variable, set the value as -binarycaching.

Please refer to https://github.com/microsoft/vcpkg/issues/14157#issuecomment-718304161.

**Comment by NancyLi1013** [comment]
I think this issue should be solved, closing it for now.

Please feel free to reopen this if you still have concerns.
