### ISSUE TITLE
[fastrtps] update to <2.1>

### ISSUE THREAD

**Issue by AlessiaBarlascini** [microsoft/vcpkg#15610]
Library name: **fastrtps**

New version number: 2.1

Other information that may be useful (release notes, etc...) 
Released on:
Thursday, 17 December 2020 01:00

**Comment by JonLiu1993** [comment]
Hi @AlessiaBarlascini ,Can you provide me with the latest version of the source? I did not find a version that matches the information you provided on the Internet

**Comment by AlessiaBarlascini** [comment]
Hi,
thank you for your prompt reply!
I downloaded the latest version from the eProsima website. https://www.eprosima.com/index.php/component/ars/repository/eprosima-fast-dds/eprosima-fast-dds-2-1-0
(you need to register in order to access this link).
thanks again
