### ISSUE TITLE
[directxtk12] build failure on windows due to change in makespritefont.exe and xwbtool.exe files

### ISSUE THREAD

**Issue by StarGate-One** [microsoft/vcpkg#15629]
**Describe the bug**
- vcpkg on Windows architecture 64 downloads ancillary files `makespritefont.exe` and `xwbtool.exe` 
- directxtk12.cmake has no provision to anticipate if the tools have been upgraded with new hashes
- When new versions are downed, since there are no versions associated with these files in their names or elsewhere in vcpkg, vcpkg compares hashes and fails

**Environment**
- OS: [Microsoft Windows [Version 10.0.19042.746]]
- Compiler: 
   - Visual Studio 2017 Version: 15.9.31  VS Tools Version: 14.16.27023
   - Visual Studio 2019 Version: 16.8.4  VS Tools Version: 14.28.29333

**To Reproduce**
1. a previous version of directxtk12 had been installed with `set VCPKG_DEFAULT_TRIPLET=x64-windows`
    - After commit of PR directxmesh, directxtex, and uvatlas now support linux #15554 implemented
    - git pull
    - `vcpkg remove directxtk12` (I would assume a `vcpkg upgrade --no-dry-run` would fail also)
    - `vcpkg install directxtk12` fails 
      - 1st time hash on makespritefont.exe does not match (deleted over version of makespritefont.exe file in [vcpkg-root]\downloads)
      - 2nd time hash on xwbtool.exe does not match  (deleted over version of xwbtool.exe file in [vcpkg-root]\downloads)
      - 3rd time install success
2. Repro code when
Basically vcpkg failed twice due to mismatched hashes, requiring manual intervention twice (deleting the mismatched file from [vcpkg-root]\downloads) before a successful reinstall from version upgrade

**Expected behavior**
When `vcpkg install directxtk12` is done after removing a previous version of the port it should install successfully.

**Failure logs** 
- (please attached failure logs) 
[directxtk12_console.log](https://github.com/microsoft/vcpkg/files/5811220/directxtk12_console.log)

**Additional context**
1. Having to manually intervene on a port upgrade is a bad user experience.
2. In the `portfile.cmake` when the additional files `makespritefont.exe` and `xwbtool.exe` are downloaded they should have some type of version attached in the name such as `makespritefont-jan2021.exe` and `xwbtool-jan2021.exe` then the portfile can copy/install them in the `tools/directxtk12` directory without the `-jan2021` or whatever the decided version scheme is, but to be consistent in how other ports in vcpkg download `tools` files.

Example boost-build:
https://github.com/microsoft/vcpkg/blob/8414e15973097e70fe40149e922c402799804b3d/ports/boost-build/portfile.cmake#L19-L30

**Comment by JackBoosY** [comment]
@walbourn Can you please take a look?

Thanks.

**Comment by JackBoosY** [comment]
https://github.com/microsoft/vcpkg/blob/fd67439f01bfec989f7b1505f3b2f10f771470a3/ports/directxtk12/portfile.cmake#L23-L27
https://github.com/microsoft/vcpkg/blob/fd67439f01bfec989f7b1505f3b2f10f771470a3/ports/directxtk12/portfile.cmake#L29-L33

Should add an option such as `FILE_DISAMBIGUATOR`.

**Comment by walbourn** [comment]
Hmm... The ``FILE_DISAMBIGUATOR`` won't fix it since I provide a filename. It has to be a different name, and then renamed... I ran into this with some other files.

**Comment by JackBoosY** [comment]
@walbourn Do you have any suggestions?

**Comment by walbourn** [comment]
@JackBoosY  This PR https://github.com/microsoft/vcpkg/pull/15639

**Comment by walbourn** [comment]
The fix has been merged, so this issue should be closed.

**Comment by StarGate-One** [comment]
Appears to be working great now. Thank you @walbourn 👍👍👍😊
