### ISSUE TITLE
does not work with 32 versions SDL2 !!!!! 

### ISSUE THREAD

**Issue by kaizer1** [microsoft/vcpkg#15621]
- OS:  Windows 10]
- Compiler: revision 309r2019834

vcpkg install SDL2

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

And he downloads version 32 from which nothing can be collected !!!! Some kind of horror. Why do I need 32 version ?????

**Comment by StarGate-One** [comment]
1. vcpkg help triplet
2. https://github.com/microsoft/vcpkg/blob/master/docs/users/triplets.md
3. vcpkg install SDL2:x64-windows -or-
4. vcpkg install SDL2:x64-windows-static -or-
5. vcpkg install SDL2 --triplet=x64-windows -or-
6. vcpkg install SDL2 --triplet=x64-windows-static -or-
7. set VCPKG_DEFAULT_TRIPLET=x64-windows -or-
   set VCPKG_DEFAULT_TRIPLET=x64-windows-static then
  vcpkg install SDL2
