### ISSUE TITLE
Error: Building package sentencepiece:x64-linux failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by hassani24** [microsoft/vcpkg#15646]
Error when trying to use vcpkg to install sentencepiece in a google colab environment.  adding new issue as suggested by the output

Package: sentencepiece:x64-linux
Vcpkg version: 2020.11.12-

contents of extract-err.log
CMake Error: Problem with archive_write_header(): Can't create 'sentencepiece-0.1.82/python/test/botchan.txt'
CMake Error: Current file: sentencepiece-0.1.82/python/test/botchan.txt
CMake Error: Problem extracting tar: /content/drive/MyDrive/translators/translation/fairseq/vcpkg/downloads/google-sentencepiece-v0.1.82.tar.gz

CMake projects should use: "-DCMAKE_TOOLCHAIN_FILE=/content/drive/MyDrive/translators/translation/fairseq/vcpkg/scripts/buildsystems/vcpkg.cmake"
Computing installation plan...
The following packages will be built and installed:
    sentencepiece[core]:x64-linux -> v0.1.82
Detecting compiler hash for triplet x64-linux...
Could not locate cached archive: /root/.cache/vcpkg/archives/5a/5aba758998b2ba0fb8b4f77f09ecddcfede95c95.zip
Starting package 1/1: sentencepiece:x64-linux
Building package sentencepiece[core]:x64-linux...
-- Using cached /content/drive/MyDrive/translators/translation/fairseq/vcpkg/downloads/google-sentencepiece-v0.1.82.tar.gz
-- Extracting source /content/drive/MyDrive/translators/translation/fairseq/vcpkg/downloads/google-sentencepiece-v0.1.82.tar.gz
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:108 (message):
    Command failed: /content/drive/MyDrive/translators/translation/fairseq/vcpkg/downloads/tools/cmake-3.19.2-linux/cmake-3.19.2-Linux-x86_64/bin/cmake -E tar xjf /content/drive/MyDrive/translators/translation/fairseq/vcpkg/downloads/google-sentencepiece-v0.1.82.tar.gz
    Working Directory: /content/drive/MyDrive/translators/translation/fairseq/vcpkg/buildtrees/sentencepiece/src/v0.1.82-78b42c73ce.tmp
    Error code: 1

**Comment by NancyLi1013** [comment]
Hi @hassani24 

Thanks for posting this issue.

```
CMake Error: Problem with archive_write_header(): Can't create 'sentencepiece-0.1.82/python/test/botchan.txt'
CMake Error: Current file: sentencepiece-0.1.82/python/test/botchan.txt
CMake Error: Problem extracting tar: /content/drive/MyDrive/translators/translation/fairseq/vcpkg/downloads/google-sentencepiece-v0.1.82.tar.gz
```
Seems like a CMake bug. We encountered this kinds of issues on Windows.

Could you please try to build this in another driver on your machine?

**Comment by hassani24** [comment]
Hi @NancyLi1013 .  Thanks for the support.  Can you please clarify what you mean by "build this in another driver on your machine"?

**Comment by hassani24** [comment]
Hello - I found a pre-built binary of sentencepiece so I no longer have a need to build on my own.  It would still be useful to learn how to use vcpkg in a colab notebook but I no longer need the support

**Comment by NancyLi1013** [comment]
Sorry for the delay. 



> Hi @NancyLi1013 . Thanks for the support. Can you please clarify what you mean by "build this in another driver on your machine"?

I mean you can build this port in another disk, such as you build it in disk a, you can create a new vcpkg repo in disk b to build. But I'm not sure if this is useful for you since I only met this problem on Windows platform.
