### ISSUE TITLE
Error: Building package bzip2:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by alhaas** [microsoft/vcpkg#15648]
I am having issues with the bzip2 installation. Due to a proxy issue I manually downloaded the file and placed it in the download folder, vcpkg seems to find it and extracts it to the buildtree directory, however from there on the installation fails. Did I miss something when placing files manually in the downloads directory?

Starting package 1/1: bzip2:x86-windows
Building package bzip2[core]:x86-windows...
-- Using cached ***/bzip2-75a94bea3918e612b879d6a11ca64b8689526147.tar.gz
-- Extracting source ***/bzip2-75a94bea3918e612b879d6a11ca64b8689526147.tar.gz
-- Applying patch fix-import-export-macros.patch
CMake Error at scripts/cmake/vcpkg_apply_patches.cmake:63 (message):
  Applying patch failed.  Checking patch bzlib.h...

  error: bzlib.h: No such file or directory

Call Stack (most recent call first):
  scripts/cmake/vcpkg_extract_source_archive_ex.cmake:145 (vcpkg_apply_patches)
  scripts/cmake/vcpkg_from_git.cmake:132 (vcpkg_extract_source_archive_ex)
  ports/bzip2/portfile.cmake:1 (vcpkg_from_git)
  scripts/ports.cmake:136 (include)

Error: Building package bzip2:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: bzip2:x86-windows
  Vcpkg version: 2020.11.12--unknownhash

Additionally, attach any relevant sections from the log files above.

**Comment by JackBoosY** [comment]
Can you make sure `bzlib.h` is in _VCPKG_ROOT/buildtrees/bzip2/src/****_?

**Comment by alhaas** [comment]
`bzlib.h` is located here: VCPKG_ROOT\buildtrees\bzip2\src\8689526147-336d4794a3.tmp\bzip2-1.0.8\bzlib.h

**Comment by JackBoosY** [comment]
Can you please remove the bzip2 archive and put [this](https://github.com/microsoft/vcpkg/files/5819446/bzip2-75a94bea3918e612b879d6a11ca64b8689526147.tar.gz) to _VCPKG_ROOT/downloads_ then try again?

Thanks.

**Comment by alhaas** [comment]
It worked, thank you very much!

**Comment by 2021se7en** [comment]
i delete bzip2 archive and put it to VCPKG_ROOT/downloads then failed

**Comment by JackBoosY** [comment]
@2021se7en  Can you please make sure your vcpkg is latest?

**Comment by 2021se7en** [comment]
> @2021se7en Can you please make sure your vcpkg is latest?

yes already update to latest version

**Comment by 2021se7en** [comment]
> @2021se7en Can you please make sure your vcpkg is latest?

need i set up nmake？

**Comment by JackBoosY** [comment]
@2021se7en  That's not needed. Can you please open a new issue to report that?
And please attach the failure logs.

Thanks.
