### ISSUE TITLE
Is there a difference between "install <port>:x64-windows" and "install <port> --triplet=x64-windows"

### ISSUE THREAD

**Issue by jdx-john** [microsoft/vcpkg#15642]
I've seen the former option given as an example in `help install` but is it equivalent to using `--triplet` or is there a subtle difference?

**Comment by Neumann-A** [comment]
If you only install one port directly there is no difference. The difference is only when you install two ports. 
e.g.
`vcpkg install hdf5 mesa --triplet=x64-windows-static`
install all ports with triplet x64-windows-static
`vcpkg install hdf5:x64-windows-static mesa (--triplet=x64-windows)`
will only install hdf5 with x64-windows-static

**Comment by NancyLi1013** [comment]
Hi @jdx-john 

Thanks for posing this issue.

**Supplement:**

If you install more than two ports, the result is the same as above from @Neumann-A .

- vcpkg install zlib sqlite3 libuv:x64-windows
  will only install  libuv:x64-windows, other ports are x86-windows
- vcpkg install zlib sqlite3 libuv --triplet=x64-windows
  will install all ports with x64-windows

**Conclude:**

If you want to install more than two ports with the same triplet, you can use --triplet=x64-windows;

If you want to install more than two ports with different triplets, you can choose both ways.

**Note:**
If you use these two ways at the same time, the port which is not pointing triplet, it will be installed with the same triplet from --triplet=x64-windows.

eg: `vcpkg.exe install zlib sqlite3:x64-windows libuv --triplet=x64-windows-static`
will install zlib and libuv with x64-windows-static, sqlite3 with x64-windows.

**Comment by NancyLi1013** [comment]
I think this issue should be solved, closing it for now.
