### ISSUE TITLE
[New Port Request] restc-cpp

### ISSUE THREAD

**Issue by lejcik** [microsoft/vcpkg#15654]
Library name: restc-cpp

Library description: Modern C++ REST Client library

Source repository URL: https://github.com/jgaa/restc-cpp

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by lejcik** [comment]
I prepared an initial port for this library, but as the [Contribution Guidelines](https://github.com/Microsoft/vcpkg/blob/master/CONTRIBUTING.md#pull-requests) says:

> we highly encourage opening an issue to discuss whether the PR you're thinking about making will be acceptable

If anybody is interested, the port is available here:

https://github.com/lejcik/vcpkg/tree/restc-cpp-port/ports/restc-cpp

As this is my first contribution to _vcpkg_, I'd appreciate any help. Thanks.

Vilo

**Comment by ras0219** [comment]
Thanks for opening this issue; we'd love to see this as a PR!
