### ISSUE TITLE
libpng-uwp build error

### ISSUE THREAD

**Issue by bigdimboom** [Microsoft/vcpkg#1565]
Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:49 (vcpkg_execute_required_process)
  ports/libpng/portfile.cmake:47 (vcpkg_install_cmake)
  scripts/ports.cmake:72 (include)

Error: Building package libpng:x64-uwp failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libpng:x64-uwp
  Vcpkg version: 0.0.81-63454f618996baefef3f60f90767cd4c02d7590d

**Comment by ras0219-msft** [comment]
Hi @bigdimboom, thanks for reporting this issue!

Could you post the log files associated with the failure? The full paths should have been printed to the console during the failure.

**Comment by ras0219-msft** [comment]
I was able to reproduce an issue with libpng and it should be fixed in the latest master (4735040f). Please also try out this version and let us know if your issue still appears!

**Comment by yaoyu** [comment]
change cmake3.9.0 to cmake3.8.2

**Comment by bigdimboom** [comment]
![image](https://user-images.githubusercontent.com/6119906/28831384-6d79059e-76a7-11e7-8934-5881bb3e65c1.png)

**Comment by Cheney-W** [comment]
@bigdimboom , I can install libpng:x64-uwp successfully with the latest vcpkg: 2018.11.23-nohash, so close this issue.
