### ISSUE TITLE
How do I build/install podofo with OpenSSL support?

### ISSUE THREAD

**Issue by DietmarSchulz** [microsoft/vcpkg#15663]
I couldn't find any answer why vcpkg install podofo:x64-windows doesn't find the crypto libs and includes of open ssl, neither in Microsoft's Docs nor in Podofo's.
I had a look on ...\vcpkg_clone\buildtrees\podofo\src\35c1a45775-329e7b758d.clean\cmake\modules\FindLIBCRYPTO.cmake but couldn't figure out why FIND_PATH(LIBCRYPTO_INCLUDE_DIR openssl/sha.h) desn't work. Should there be some environment variables?
I have installed:
curl[ssl]:x64-windows                                               Default SSL backend
curl[winssl]:x64-windows                                            Legacy name for schannel
freetds[openssl]:x64-windows                                        OpenSSL support
libpq[openssl]:x64-windows                                          support for encrypted client connections and ran...
libressl:x64-windows                               2.9.1#3          LibreSSL is a version of the TLS/crypto stack fo...
libressl[tools]:x64-windows                                         Build openssl and ocspcheck executables
openssl:x64-windows                                1.1.1i           OpenSSL is an open source project that provides ...
wt[openssl]:x64-windows                                             TLS support
libidn2:x64-windows                                2.3.0#1          GNU Libidn is an implementation of the Stringpre...
libzip:x64-windows                                 1.7.3#1          A library for reading, creating, and modifying z...
libzip[bzip2]:x64-windows                                           Support bzip2-compressed zip archives
libzip[default-aes]:x64-windows                                     Use default AES
libzip[wincrypto]:x64-windows                                       AES (encryption) support using Windows Crypto API
zlib:x64-windows                                   1.2.11#9         A compression library

**Comment by JackBoosY** [comment]
Confirmed.

**Comment by JackBoosY** [comment]
```
OpenSSL's libCrypto not found. Encryption support will be disabled
Libidn not found. AES-256 Encryption support will be disabled
```
