### ISSUE TITLE
ERROR: "Could not find Visual Studio. VS2015, VS2017, or VS2019 (with C++) needs to be installed."

### ISSUE THREAD

**Issue by starbvuks** [microsoft/vcpkg#15665]
Even though I have VS2019 installed with the C/C++ package when running ` .\bootstrap-vcpkg.bat ` it gives the following error:

```
Could not find Visual Studio. VS2015, VS2017, or VS2019 (with C++) needs to be installed.
At C:\Users\kalar\vcpkg\scripts\bootstrap.ps1:143 char:9
+         throw "Could not find Visual Studio. VS2015, VS2017, or VS201 ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find ...o be installed.:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find Visual Studio. VS2015, VS2017, or VS2019 (with C++) needs to be installed
   .
```

I'm pretty new to programming and am trying to code with C in Visual Studio but it seems like there's a problem every step of the way. Any help would be massively appreciated

**Comment by walbourn** [comment]
VS 2017 and VS 2019 have a very modular setup, so it can be a little challenging to get the right bits installed. Which workgroups did you install?

**Comment by JackBoosY** [comment]
Please make sure you have installed  the English Language Package using Visual Studio Installer, and installed Windows 10 SDK. 

Thanks.

**Comment by PhoebeHui** [comment]
This should not be a problem now, please get latest source and try again.
