### ISSUE TITLE
[libmysql:x64-windows] build failure

### ISSUE THREAD

**Issue by wukakuki** [microsoft/vcpkg#15668]
**Host Environment**
- OS: Windows
- Compiler: VS2019 16.8.4 | Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29336 for x64

**To Reproduce**
`./vcpkg install libmysql:x64-windows`

**Failure logs** 
`Computing installation plan...
The following packages will be built and installed:
    libmysql[core]:x64-windows -> 8.0.20#1
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\lion\AppData\Local\vcpkg\archives\22\22546e8eafa1f955e7ae9f6b6f903d070967e37d.zip
Starting package 1/1: libmysql:x64-windows
Building package libmysql[core]:x64-windows...
-- Using cached D:/vcpkg/downloads/mysql-mysql-server-7d10c82196c8e45554f27c00681474a9fb86d137.tar.gz
-- Cleaning sources at D:/vcpkg/buildtrees/libmysql/src/a9fb86d137-b8e0688382.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/vcpkg/downloads/mysql-mysql-server-7d10c82196c8e45554f27c00681474a9fb86d137.tar.gz
-- Applying patch ignore-boost-version.patch
-- Applying patch system-libs.patch
-- Applying patch rename-version.patch
-- Applying patch export-cmake-targets.patch
-- Using source at D:/vcpkg/buildtrees/libmysql/src/a9fb86d137-b8e0688382.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:145 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j49
    Working Directory: D:/vcpkg/buildtrees/libmysql/x64-windows-dbg
    See logs for more information:
      D:\vcpkg\buildtrees\libmysql\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:27 (vcpkg_build_cmake)
  ports/libmysql/portfile.cmake:70 (vcpkg_install_cmake)
  scripts/ports.cmake:136 (include)

Error: Building package libmysql:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libmysql:x64-windows
  Vcpkg version: 2020.11.12--unknownhash

Additionally, attach any relevant sections from the log files above.`

attach log
D:\vcpkg\buildtrees\libmysql\install-x64-windows-dbg-out.log
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/5820472/install-x64-windows-dbg-out.log)

I want to install qt which requires libmysql. how can I get rid of this error? I appreciate any help.

**Comment by JackBoosY** [comment]
```
[289/435] cmd.exe /C "cd . && C:\PROGRA~2\MICROS~2\2019\Community\VC\Tools\MSVC\14.28.29333\bin\Hostx64\x64\lib.exe  /machine:x64 /nologo  optimized D:/vcpkg/installed/x64-windows/debug/lib/libssl.lib debug D:/OpenSSL-Win64/lib/VC/libssl64MDd.lib optimized D:/vcpkg/installed/x64-windows/debug/lib/libcrypto.lib debug D:/OpenSSL-Win64/lib/VC/libcrypto64MDd.lib /out:archive_output_directory\mysqlclient.lib @CMakeFiles\mysqlclient.rsp  && cd ."
FAILED: archive_output_directory/mysqlclient.lib 
cmd.exe /C "cd . && C:\PROGRA~2\MICROS~2\2019\Community\VC\Tools\MSVC\14.28.29333\bin\Hostx64\x64\lib.exe  /machine:x64 /nologo  optimized D:/vcpkg/installed/x64-windows/debug/lib/libssl.lib debug D:/OpenSSL-Win64/lib/VC/libssl64MDd.lib optimized D:/vcpkg/installed/x64-windows/debug/lib/libcrypto.lib debug D:/OpenSSL-Win64/lib/VC/libcrypto64MDd.lib /out:archive_output_directory\mysqlclient.lib @CMakeFiles\mysqlclient.rsp  && cd ."
LINK : fatal error LNK1181: cannot open input file 'optimized'
```

**Comment by JackBoosY** [comment]
@wukakuki  Can you provide configure log _D:\vcpkg\buildtrees\libmysql\config-x64-windows-dbg-out.log_  and _D:\vcpkg\buildtrees\libmysql\config-x64-windows-dbg-err.log_?

Thanks.

**Comment by andylizi** [comment]
I've encountered the same issue and here're my logs:

* [install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/6046086/install-x64-windows-dbg-out.log)
* [config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/6046087/config-x64-windows-out.log)

`config-x64-windows-dbg-err.log` is empty.

My build log has some `unresolved external` errors that OP didn't have, but given that they both seems to be related to OpenSSL, I think they could be caused by the same problem.

**Comment by JackBoosY** [comment]
@andylizi  This is definitely a bug when parsing and using openssl in cmake.

**Comment by JackBoosY** [comment]
That caused by these code:
https://github.com/mysql/mysql-server/blob/8.0/cmake/libutils.cmake#L351-L358
```cmake
  IF(WIN32 AND ${TARGET} STREQUAL "mysqlclient")
    SET(LINKER_EXTRA_FLAGS "")
    FOREACH(LIB ${SSL_LIBRARIES})
      STRING_APPEND(LINKER_EXTRA_FLAGS " ${LIB}")
    ENDFOREACH()
    SET_TARGET_PROPERTIES(${TARGET}
      PROPERTIES STATIC_LIBRARY_FLAGS "${LINKER_EXTRA_FLAGS}")
  ENDIF()
```

**Comment by JackBoosY** [comment]
Hi guys, can you please test PR https://github.com/microsoft/vcpkg/pull/16426?

Thanks.

**Comment by andylizi** [comment]
`cannot open input file 'optimized'` is indeed fixed, but I'm still getting `unresolved external symbol` (same logs as before, only without the `optimized` part). Should be a separate issue through.

**Comment by JackBoosY** [comment]
@andylizi  Can you please provide the full log?

**Comment by andylizi** [comment]
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/6048369/config-x64-windows-out.log)
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/6048371/install-x64-windows-dbg-out.log)

**Comment by JackBoosY** [comment]
@andylizi 
```
-- Found OpenSSL: optimized;C:/vcpkg/installed/x64-windows/lib/libcrypto.lib;debug;C:/Program Files/OpenSSL/lib/VC/libeay32MDd.lib (found version "1.1.1i")  
```

Please uninstall openssl that you manually installed in _C:/Program Files/OpenSSL_, then try again.

**Comment by andylizi** [comment]
It works correctly now, thanks!

> -- Found OpenSSL: C:/vcpkg/installed/x64-windows/lib/libcrypto.lib (found version "1.1.1i")  

Still, it's a bit weird that cmake would randomly pickup a library. It's not like `C:/Program Files/OpenSSL/lib/VC/` are in the PATH, where did it even find it...
