### ISSUE TITLE
add vcpkg.disable-metrics to gitingore

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#15670]
see title

**Comment by JackBoosY** [comment]
cc @dan-shaw

**Comment by NancyLi1013** [comment]
`vcpkg.disable-metrics` has been added to `gitingore `now. So close this issue.
Please see 
https://github.com/microsoft/vcpkg/blob/e6dcc079c81161786eb7b052209a2047e79f2c6c/.gitignore#L311
