### ISSUE TITLE
vcpkg uses UWP triplet in WinUI on desktop projects

### ISSUE THREAD

**Issue by sylveon** [microsoft/vcpkg#15685]
**Describe the bug**
When creating a WinUI on Desktop project, vcpkg will use the `arch-uwp` triplet instead of `arch-windows` triplet.

**Environment**
- OS: Windows
- Compiler: Visual Studio 16.9 Preview 2

**To Reproduce**
1. Create a new C++ WinUI on desktop project (using https://marketplace.visualstudio.com/items?itemName=Microsoft-WinUI.WinUIProjectTemplates)
2. Run `vcpkg install fmt:x86-windows`
3. Try to `#include <fmt/format.h>` in the project
4. Observe include error

**Expected behavior**
vcpkg looks up in the desktop triplet for libraries.

**Additional context**
The file isn't found because vcpkg thinks it is in a UWP project when it is not in a UWP project, so it will lookup for libraries in the UWP triplet, in which `fmt` isn't installed.

**Comment by soumyamahunt** [comment]
I think this is related to #15409, there already is a PR #15410 that should fix this issue.

**Comment by sylveon** [comment]
That indeed seems like it, thanks!
