### ISSUE TITLE
[opensubdiv] build failure on macOS

### ISSUE THREAD

**Issue by virtualritz** [microsoft/vcpkg#15695]
~The reason is that this lib requires OpenMP support which Apple Clang does not have.~
~But a 'normal' `clang` installation does.~

~The build script should detect that it is on macOS, look for a non-Apple `clang` compiler and use that. Or print an informative error, if absent.~

[CMakeError.log](https://github.com/microsoft/vcpkg/files/5824866/CMakeError.log)

**Comment by JonLiu1993** [comment]
@virtualritz ,Sorry to reply you so late，Can you provide your re-steps? I cannot reproduce your problem on my local computer，Thanks

**Comment by virtualritz** [comment]
I only ran:
```
./vcpgk install opensubdiv
```
> I cannot reproduce your problem on my local computer, [...]

I updated `vcpkg` & retried and I get a different error now, unrelated to OpenMP:
[config-x64-osx-dbg-err.log](https://github.com/microsoft/vcpkg/files/5835849/config-x64-osx-dbg-err.log)

**Comment by virtualritz** [comment]
I created a PR with a fix for this. See above.

**Comment by JonLiu1993** [comment]
@virtualritz ,Thanks for your contribution
