### ISSUE TITLE
Support github mirror

### ISSUE THREAD

**Issue by cathaysia** [microsoft/vcpkg#15690]
There is a feather request.

Hi, github are very slow in my area. But Github has a lot of mirror website, such as 

https://github.xiu2.xyz/https://github.com/microsoft/vcpkg/archive/2020.11-1.zip
https://gh.con.sh/https://github.com/microsoft/vcpkg/archive/2020.11-1.zip
https://gh.api.99988866.xyz/https://github.com/microsoft/vcpkg/archive/2020.11-1.zip
and etc.

I can use proxy to  intercept vcpkg's requests. But if vcpkg support it inside, it's more convenience

**Comment by JackBoosY** [comment]
In fact #13639 is doing this.

**Comment by JackBoosY** [comment]
Duplicated tp #13690.
