### ISSUE TITLE
[openblas] Support feature single-thread

### ISSUE THREAD

**Issue by TonyXiang8787** [microsoft/vcpkg#15698]
The BLAS library `openblas` provides a setting `make USE_THREAD=0` to build a single-thread library. See here
https://fossies.org/linux/OpenBLAS/USAGE.md

However, if I do `vcpkg install openblas`, I have no idea how to specify this option. I have read the help of `vcpkg install`, it does not seem to provide a way to pass through a make build option.

The question can be generalized to: if a package author provides multiple `make` or `cmake` options to customize the build, how can `vcpkg` pass through these options when using `vcpkg install`?

**Comment by JackBoosY** [comment]
We can implement this feature through the options `OPTIONS` /`OPTIONS_DEBUG` /`OPTIONS_RELEASE` in `vcpkg_configure_cmake` or `vcpkg_configure_make` etc., see [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_configure_cmake.md#options).

**Comment by TonyXiang8787** [comment]
@JackBoosY @JonLiu1993 Thanks for the reply. I have read the [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_configure_cmake.md#options) you referred. If I understand correctly, this is a way to specify a build option when you create a port.

But after the port has been created (without a build option), how can I pass an additional build option at install time via `vcpkg install`?

**Comment by JackBoosY** [comment]
@TonyXiang8787 For example, see:
https://github.com/microsoft/vcpkg/blob/1d415e8dc3afef0ae85b4d00ea56013b2f26bb46/ports/libiconv/portfile.cmake#L24-L36

**Comment by JonLiu1993** [comment]
@TonyXiang8787 ,Does it still a question for you?

**Comment by TonyXiang8787** [comment]
@JonLiu1993  Thanks for the answer. If I understand correctly, I have to modify the `portfile.cmake` file of `openblas` to add build options. This file is however part of the GIT version control. So does it mean my version of `vcpkg` diverges from the main?

**Comment by JackBoosY** [comment]
I need to confirm some thing:
1. Openblas provides two related feature: `USE_THREAD` and `USE_SIMPLE_THREADED_LEVEL3`, which one do you mean?
2. Seems that if we enable `USE_SIMPLE_THREADED_LEVEL3`, we need to enable `USE_THREAD`, right?

**Comment by TonyXiang8787** [comment]
@JackBoosY I am self only familiar with the option USE_THREAD. I set USE_THREAD=0 if I want to build open blad manually in single thread.
