### ISSUE TITLE
[libpng] build failure

### ISSUE THREAD

**Issue by JoseAmancio5597851** [microsoft/vcpkg#15703]
**Host Environment**
- OS: [Windows 10]
- Compiler: revision

**To Reproduce**
`./vcpkg install assimp`

**Failure logs** 
C:\Users\jose.amancio\Downloads\vcpkg-master\vcpkg>vcpkg install assimp
Computing installation plan...
The following packages will be built and installed:
    assimp[core]:x86-windows -> 5.0.1#4
  * irrlicht[core]:x86-windows -> 1.8.4-10
  * kubazip[core]:x86-windows -> 0.1.19
  * libpng[core]:x86-windows -> 1.6.37#14
  * minizip[core]:x86-windows -> 1.2.11#7
  * poly2tri[core]:x86-windows -> 2020-07-21
  * polyclipping[core]:x86-windows -> 6.4.2#6
  * rapidjson[core]:x86-windows -> 2020-09-14
  * stb[core]:x86-windows -> 2020-09-14
  * utfcpp[core]:x86-windows -> 3.1.2#1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x86-windows...
Could not locate cached archive: C:\Users\jose.amancio\AppData\Local\vcpkg\archives\1c\1ce00bb8bfc564dcd02d2b00de1cf523fbfbfbb5.zip
Could not locate cached archive: C:\Users\jose.amancio\AppData\Local\vcpkg\archives\f8\f8d1eb59b7029a5e27495ac25d422e611d26b005.zip
Could not locate cached archive: C:\Users\jose.amancio\AppData\Local\vcpkg\archives\b7\b7655d3aa04d9a5f36e3b242056f94abf2e1fa8c.zip
Could not locate cached archive: C:\Users\jose.amancio\AppData\Local\vcpkg\archives\39\399c19d950baa9d82424737b1b3a106bd9d187d9.zip
Could not locate cached archive: C:\Users\jose.amancio\AppData\Local\vcpkg\archives\67\67733d650fc345aa56ebfe5fbc6420a4374fa95e.zip
Could not locate cached archive: C:\Users\jose.amancio\AppData\Local\vcpkg\archives\56\5618873b806199fcd13c1fdb1a5cb04819a82273.zip
Could not locate cached archive: C:\Users\jose.amancio\AppData\Local\vcpkg\archives\fe\fe76a5bac329d5bd883dfd9485a3388c7abb9595.zip
Could not locate cached archive: C:\Users\jose.amancio\AppData\Local\vcpkg\archives\d7\d71ddaa86d2d04bed4ed3c8d825b9d3dca27d667.zip
Could not locate cached archive: C:\Users\jose.amancio\AppData\Local\vcpkg\archives\ec\ecf67d2af56f1337eaeea89e20af943931261f57.zip
Could not locate cached archive: C:\Users\jose.amancio\AppData\Local\vcpkg\archives\9a\9a7134ee078aa9f14531dc628ca02a2f6d387a88.zip
Starting package 1/10: libpng:x86-windows
Building package libpng[core]:x86-windows...
-- Using cached C:/Users/jose.amancio/Downloads/vcpkg-master/vcpkg/downloads/glennrp-libpng-v1.6.37.tar.gz
-- Cleaning sources at C:/Users/jose.amancio/Downloads/vcpkg-master/vcpkg/buildtrees/libpng/src/v1.6.37-05658d6f1a.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/jose.amancio/Downloads/vcpkg-master/vcpkg/downloads/glennrp-libpng-v1.6.37.tar.gz
-- Applying patch use_abort.patch
-- Applying patch cmake.patch
-- Applying patch pkgconfig.patch
-- Applying patch pkgconfig.2.patch
-- Applying patch fix-export-targets.patch
-- Applying patch macos-arch-fix.patch
-- Using source at C:/Users/jose.amancio/Downloads/vcpkg-master/vcpkg/buildtrees/libpng/src/v1.6.37-05658d6f1a.clean
-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:145 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j9
    Working Directory: C:/Users/jose.amancio/Downloads/vcpkg-master/vcpkg/buildtrees/libpng/x86-windows-dbg
    See logs for more information:
      C:\Users\jose.amancio\Downloads\vcpkg-master\vcpkg\buildtrees\libpng\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:27 (vcpkg_build_cmake)
  ports/libpng/portfile.cmake:85 (vcpkg_install_cmake)
  scripts/ports.cmake:136 (include)

Error: Building package libpng:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libpng:x86-windows
  Vcpkg version: 2020.11.12--unknownhash

Additionally, attach any relevant sections from the log files above.

C:\Users\...\vcpkg-master\vcpkg>

**Comment by JackBoosY** [comment]
Please provide failure log _ C:\Users\jose.amancio\Downloads\vcpkg-master\vcpkg\buildtrees\libpng\install-x86-windows-dbg-out.log_. 

Thanks.

**Comment by JoseAmancio5597851** [comment]
Enviado desde Correo para Windows 10 De: Jack·Boos·YuEnviado: lunes, 18 de enero de 2021 1:55Para: microsoft/vcpkgCC: JoseAmancio5597851; AuthorAsunto: Re: [microsoft/vcpkg] [assimp] build failure (#15703) Please provide failure log _ C:\Users\jose.amancio\Downloads\vcpkg-master\vcpkg\buildtrees\libpng\install-x86-windows-dbg-out.log_.Thanks.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by JackBoosY** [comment]
@JoseAmancio5597851  I think that's not the log content.

**Comment by JoseAmancio5597851** [comment]
Perform the installation again, with the English language in MSVS, the error is repeated:C:\Users\jose.amancio>vcpkg install libpngComputing installation plan...The following packages will be built and installed:    libpng[core]:x86-windows -> 1.6.37#14Detecting compiler hash for triplet x86-windows...Could not locate cached archive: C:\Users\jose.amancio\AppData\Local\vcpkg\archives\1c\1ce00bb8bfc564dcd02d2b00de1cf523fbfbfbb5.zipStarting package 1/1: libpng:x86-windowsBuilding package libpng[core]:x86-windows...-- Using cached C:/Dev.app/src/vcpkg/downloads/glennrp-libpng-v1.6.37.tar.gz-- Cleaning sources at C:/Dev.app/src/vcpkg/buildtrees/libpng/src/v1.6.37-05658d6f1a.clean. Use --editable to skip cleaning for the packages you specify.-- Extracting source C:/Dev.app/src/vcpkg/downloads/glennrp-libpng-v1.6.37.tar.gz-- Applying patch use_abort.patch-- Applying patch cmake.patch-- Applying patch pkgconfig.patch-- Applying patch pkgconfig.2.patch-- Applying patch fix-export-targets.patch-- Applying patch macos-arch-fix.patch-- Using source at C:/Dev.app/src/vcpkg/buildtrees/libpng/src/v1.6.37-05658d6f1a.clean-- Configuring x86-windows-- Building x86-windows-dbgCMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:145 (message):    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j9    Working Directory: C:/Dev.app/src/vcpkg/buildtrees/libpng/x86-windows-dbg    See logs for more information:      C:\Dev.app\src\vcpkg\buildtrees\libpng\install-x86-windows-dbg-out.log Call Stack (most recent call first):  scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)  scripts/cmake/vcpkg_install_cmake.cmake:27 (vcpkg_build_cmake)  ports/libpng/portfile.cmake:85 (vcpkg_install_cmake)  scripts/ports.cmake:136 (include)  Error: Building package libpng:x86-windows failed with: BUILD_FAILEDPlease ensure you're using the latest portfiles with `.\vcpkg update`, thensubmit an issue at https://github.com/Microsoft/vcpkg/issues including:  Package: libpng:x86-windows  Vcpkg version: 2020.11.12--unknownhash Additionally, attach any relevant sections from the log files above.    Enviado desde Correo para Windows 10 De: Jack·Boos·YuEnviado: miércoles, 27 de enero de 2021 3:28Para: microsoft/vcpkgCC: JoseAmancio5597851; MentionAsunto: Re: [microsoft/vcpkg] [assimp] build failure (#15703) @JoseAmancio5597851 I think that's not the log content.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by JackBoosY** [comment]
Please upload your failure log _C:\Dev.app\src\vcpkg\buildtrees\libpng\install-x86-windows-dbg-out.log_ here so I can figure out why this issue happened.

**Comment by JoseAmancio5597851** [comment]
this it's failure log C:\Dev.app\src\vcpkg\buildtrees\libpng\install-x86-windows-dbg-out.log:  Enviado desde Correo para Windows 10 De: Jack·Boos·YuEnviado: jueves, 28 de enero de 2021 3:27Para: microsoft/vcpkgCC: JoseAmancio5597851; MentionAsunto: Re: [microsoft/vcpkg] [assimp] build failure (#15703) Please upload your failure log C:\Dev.app\src\vcpkg\buildtrees\libpng\install-x86-windows-dbg-out.log here so I can figure out why this issue happened.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by JackBoosY** [comment]
@JoseAmancio5597851  Seems you didn't upload it...

**Comment by JoseAmancio5597851** [comment]
I do not understand to you, the file that I attach is not, or does not reach you? Anyway I copy its content.  [1/21] C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1428~1.293\bin\Hostx64\x86\cl.exe   -D_CRT_SECURE_NO_DEPRECATE -I. -IC:\Dev.app\src\vcpkg\buildtrees\libpng\src\v1.6.37-05658d6f1a.clean -IC:\Dev.app\src\vcpkg\installed\x86-windows\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\png-fix-itxt.dir\contrib\tools\png-fix-itxt.c.obj /FdCMakeFiles\png-fix-itxt.dir\ /FS -c C:\Dev.app\src\vcpkg\buildtrees\libpng\src\v1.6.37-05658d6f1a.clean\contrib\tools\png-fix-itxt.c[2/21] cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\png-fix-itxt.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1428~1.293\bin\Hostx64\x86\link.exe  CMakeFiles\png-fix-itxt.dir\contrib\tools\png-fix-itxt.c.obj  /out:png-fix-itxt.exe /implib:png-fix-itxt.lib /pdb:png-fix-itxt.pdb /version:0.0 /machine:X86 /nologo    /debug /INCREMENTAL /subsystem:console  C:\Dev.app\src\vcpkg\installed\x86-windows\debug\lib\zlibd.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."[3/21] C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1428~1.293\bin\Hostx64\x86\cl.exe   -DPNG_BUILD_DLL -D_CRT_SECURE_NO_DEPRECATE -I. -IC:\Dev.app\src\vcpkg\buildtrees\libpng\src\v1.6.37-05658d6f1a.clean -IC:\Dev.app\src\vcpkg\installed\x86-windows\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\png.dir\pngmem.c.obj /FdCMakeFiles\png.dir\ /FS -c C:\Dev.app\src\vcpkg\buildtrees\libpng\src\v1.6.37-05658d6f1a.clean\pngmem.c[4/21] C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1428~1.293\bin\Hostx64\x86\cl.exe   -DPNG_BUILD_DLL -D_CRT_SECURE_NO_DEPRECATE -I. -IC:\Dev.app\src\vcpkg\buildtrees\libpng\src\v1.6.37-05658d6f1a.clean -IC:\Dev.app\src\vcpkg\installed\x86-windows\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\png.dir\pngrtran.c.obj /FdCMakeFiles\png.dir\ /FS -c C:\Dev.app\src\vcpkg\buildtrees\libpng\src\v1.6.37-05658d6f1a.clean\pngrtran.c[5/21] C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1428~1.293\bin\Hostx64\x86\cl.exe   -DPNG_BUILD_DLL -D_CRT_SECURE_NO_DEPRECATE -I. -IC:\Dev.app\src\vcpkg\buildtrees\libpng\src\v1.6.37-05658d6f1a.clean -IC:\Dev.app\src\vcpkg\installed\x86-windows\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\png.dir\pngget.c.obj /FdCMakeFiles\png.dir\ /FS -c C:\Dev.app\src\vcpkg\buildtrees\libpng\src\v1.6.37-05658d6f1a.clean\pngget.c[6/21] C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1428~1.293\bin\Hostx64\x86\cl.exe   -DPNG_BUILD_DLL -D_CRT_SECURE_NO_DEPRECATE -I. -IC:\Dev.app\src\vcpkg\buildtrees\libpng\src\v1.6.37-05658d6f1a.clean -IC:\Dev.app\src\vcpkg\installed\x86-windows\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\png.dir\pngerror.c.obj /FdCMakeFiles\png.dir\ /FS -c C:\Dev.app\src\vcpkg\buildtrees\libpng\src\v1.6.37-05658d6f1a.clean\pngerror.c[7/21] C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1428~1.293\bin\Hostx64\x86\cl.exe   -DPNG_BUILD_DLL -D_CRT_SECURE_NO_DEPRECATE -I. -IC:\Dev.app\src\vcpkg\buildtrees\libpng\src\v1.6.37-05658d6f1a.clean -IC:\Dev.app\src\vcpkg\installed\x86-windows\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\png.dir\pngpread.c.obj /FdCMakeFiles\png.dir\ /FS -c C:\Dev.app\src\vcpkg\buildtrees\libpng\src\v1.6.37-05658d6f1a.clean\pngpread.c[8/21] C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1428~1.293\bin\Hostx64\x86\cl.exe   -DPNG_BUILD_DLL -D_CRT_SECURE_NO_DEPRECATE -I. -IC:\Dev.app\src\vcpkg\buildtrees\libpng\src\v1.6.37-05658d6f1a.clean -IC:\Dev.app\src\vcpkg\installed\x86-windows\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\png.dir\png.c.obj /FdCMakeFiles\png.dir\ /FS -c C:\Dev.app\src\vcpkg\buildtrees\libpng\src\v1.6.37-05658d6f1a.clean\png.c[9/21] C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1428~1.293\bin\Hostx64\x86\cl.exe   -DPNG_BUILD_DLL -D_CRT_SECURE_NO_DEPRECATE -I. -IC:\Dev.app\src\vcpkg\buildtrees\libpng\src\v1.6.37-05658d6f1a.clean -IC:\Dev.app\src\vcpkg\installed\x86-windows\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\png.dir\pngrutil.c.obj /FdCMakeFiles\png.dir\ /FS -c C:\Dev.app\src\vcpkg\buildtrees\libpng\src\v1.6.37-05658d6f1a.clean\pngrutil.c[10/21] C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1428~1.293\bin\Hostx64\x86\cl.exe   -DPNG_BUILD_DLL -D_CRT_SECURE_NO_DEPRECATE -I. -IC:\Dev.app\src\vcpkg\buildtrees\libpng\src\v1.6.37-05658d6f1a.clean -IC:\Dev.app\src\vcpkg\installed\x86-windows\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\png.dir\pngrio.c.obj /FdCMakeFiles\png.dir\ /FS -c C:\Dev.app\src\vcpkg\buildtrees\libpng\src\v1.6.37-05658d6f1a.clean\pngrio.c[11/21] C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1428~1.293\bin\Hostx64\x86\cl.exe   -D_CRT_SECURE_NO_DEPRECATE -I. -IC:\Dev.app\src\vcpkg\buildtrees\libpng\src\v1.6.37-05658d6f1a.clean -IC:\Dev.app\src\vcpkg\installed\x86-windows\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\pngfix.dir\contrib\tools\pngfix.c.obj /FdCMakeFiles\pngfix.dir\ /FS -c C:\Dev.app\src\vcpkg\buildtrees\libpng\src\v1.6.37-05658d6f1a.clean\contrib\tools\pngfix.c[12/21] C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1428~1.293\bin\Hostx64\x86\cl.exe   -DPNG_BUILD_DLL -D_CRT_SECURE_NO_DEPRECATE -I. -IC:\Dev.app\src\vcpkg\buildtrees\libpng\src\v1.6.37-05658d6f1a.clean -IC:\Dev.app\src\vcpkg\installed\x86-windows\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\png.dir\pngread.c.obj /FdCMakeFiles\png.dir\ /FS -c C:\Dev.app\src\vcpkg\buildtrees\libpng\src\v1.6.37-05658d6f1a.clean\pngread.c[13/21] C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1428~1.293\bin\Hostx64\x86\cl.exe   -DPNG_BUILD_DLL -D_CRT_SECURE_NO_DEPRECATE -I. -IC:\Dev.app\src\vcpkg\buildtrees\libpng\src\v1.6.37-05658d6f1a.clean -IC:\Dev.app\src\vcpkg\installed\x86-windows\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\png.dir\pngtrans.c.obj /FdCMakeFiles\png.dir\ /FS -c C:\Dev.app\src\vcpkg\buildtrees\libpng\src\v1.6.37-05658d6f1a.clean\pngtrans.c[14/21] C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1428~1.293\bin\Hostx64\x86\cl.exe   -DPNG_BUILD_DLL -D_CRT_SECURE_NO_DEPRECATE -I. -IC:\Dev.app\src\vcpkg\buildtrees\libpng\src\v1.6.37-05658d6f1a.clean -IC:\Dev.app\src\vcpkg\installed\x86-windows\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\png.dir\pngwio.c.obj /FdCMakeFiles\png.dir\ /FS -c C:\Dev.app\src\vcpkg\buildtrees\libpng\src\v1.6.37-05658d6f1a.clean\pngwio.c[15/21] C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1428~1.293\bin\Hostx64\x86\cl.exe   -DPNG_BUILD_DLL -D_CRT_SECURE_NO_DEPRECATE -I. -IC:\Dev.app\src\vcpkg\buildtrees\libpng\src\v1.6.37-05658d6f1a.clean -IC:\Dev.app\src\vcpkg\installed\x86-windows\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\png.dir\pngwrite.c.obj /FdCMakeFiles\png.dir\ /FS -c C:\Dev.app\src\vcpkg\buildtrees\libpng\src\v1.6.37-05658d6f1a.clean\pngwrite.c[16/21] C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1428~1.293\bin\Hostx64\x86\cl.exe   -DPNG_BUILD_DLL -D_CRT_SECURE_NO_DEPRECATE -I. -IC:\Dev.app\src\vcpkg\buildtrees\libpng\src\v1.6.37-05658d6f1a.clean -IC:\Dev.app\src\vcpkg\installed\x86-windows\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\png.dir\pngwutil.c.obj /FdCMakeFiles\png.dir\ /FS -c C:\Dev.app\src\vcpkg\buildtrees\libpng\src\v1.6.37-05658d6f1a.clean\pngwutil.cFAILED: CMakeFiles/png.dir/pngwutil.c.obj C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1428~1.293\bin\Hostx64\x86\cl.exe   -DPNG_BUILD_DLL -D_CRT_SECURE_NO_DEPRECATE -I. -IC:\Dev.app\src\vcpkg\buildtrees\libpng\src\v1.6.37-05658d6f1a.clean -IC:\Dev.app\src\vcpkg\installed\x86-windows\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\png.dir\pngwutil.c.obj /FdCMakeFiles\png.dir\ /FS -c C:\Dev.app\src\vcpkg\buildtrees\libpng\src\v1.6.37-05658d6f1a.clean\pngwutil.cC:\Dev.app\src\vcpkg\buildtrees\libpng\src\v1.6.37-05658d6f1a.clean\pngwutil.c(557): warning C4013: 'offsetof' undefined; assuming extern returning intC:\Dev.app\src\vcpkg\buildtrees\libpng\src\v1.6.37-05658d6f1a.clean\pngwutil.c(558): error C2275: 'png_compression_buffer': illegal use of this type as an expressionC:\Dev.app\src\vcpkg\buildtrees\libpng\src\v1.6.37-05658d6f1a.clean\pngstruct.h(65): note: see declaration of 'png_compression_buffer'C:\Dev.app\src\vcpkg\buildtrees\libpng\src\v1.6.37-05658d6f1a.clean\pngwutil.c(558): error C2065: 'output': undeclared identifierC:\Dev.app\src\vcpkg\buildtrees\libpng\src\v1.6.37-05658d6f1a.clean\pngwutil.c(944): error C2275: 'png_compression_buffer': illegal use of this type as an expressionC:\Dev.app\src\vcpkg\buildtrees\libpng\src\v1.6.37-05658d6f1a.clean\pngstruct.h(65): note: see declaration of 'png_compression_buffer'C:\Dev.app\src\vcpkg\buildtrees\libpng\src\v1.6.37-05658d6f1a.clean\pngwutil.c(944): error C2065: 'output': undeclared identifier[17/21] C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1428~1.293\bin\Hostx64\x86\cl.exe   -DPNG_BUILD_DLL -D_CRT_SECURE_NO_DEPRECATE -I. -IC:\Dev.app\src\vcpkg\buildtrees\libpng\src\v1.6.37-05658d6f1a.clean -IC:\Dev.app\src\vcpkg\installed\x86-windows\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\png.dir\pngset.c.obj /FdCMakeFiles\png.dir\ /FS -c C:\Dev.app\src\vcpkg\buildtrees\libpng\src\v1.6.37-05658d6f1a.clean\pngset.c[18/21] C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1428~1.293\bin\Hostx64\x86\cl.exe   -DPNG_BUILD_DLL -D_CRT_SECURE_NO_DEPRECATE -I. -IC:\Dev.app\src\vcpkg\buildtrees\libpng\src\v1.6.37-05658d6f1a.clean -IC:\Dev.app\src\vcpkg\installed\x86-windows\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\png.dir\pngwtran.c.obj /FdCMakeFiles\png.dir\ /FS -c C:\Dev.app\src\vcpkg\buildtrees\libpng\src\v1.6.37-05658d6f1a.clean\pngwtran.cninja: build stopped: subcommand failed.De: Jack·Boos·YuEnviado: viernes, 29 de enero de 2021 3:27Para: microsoft/vcpkgCC: JoseAmancio5597851; MentionAsunto: Re: [microsoft/vcpkg] [assimp] build failure (#15703) @JoseAmancio5597851 Seems you didn't upload it...—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by JackBoosY** [comment]
```
[16/21] C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1428~1.293\bin\Hostx64\x86\cl.exe   -DPNG_BUILD_DLL -D_CRT_SECURE_NO_DEPRECATE -I. -IC:\Dev.app\src\vcpkg\buildtrees\libpng\src\v1.6.37-05658d6f1a.clean -IC:\Dev.app\src\vcpkg\installed\x86-windows\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\png.dir\pngwutil.c.obj /FdCMakeFiles\png.dir\ /FS -c C:\Dev.app\src\vcpkg\buildtrees\libpng\src\v1.6.37-05658d6f1a.clean\pngwutil.c
FAILED: CMakeFiles/png.dir/pngwutil.c.obj C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1428~1.293\bin\Hostx64\x86\cl.exe   -DPNG_BUILD_DLL -D_CRT_SECURE_NO_DEPRECATE -I. -IC:\Dev.app\src\vcpkg\buildtrees\libpng\src\v1.6.37-05658d6f1a.clean -IC:\Dev.app\src\vcpkg\installed\x86-windows\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\png.dir\pngwutil.c.obj /FdCMakeFiles\png.dir\ /FS -c C:\Dev.app\src\vcpkg\buildtrees\libpng\src\v1.6.37-05658d6f1a.clean\pngwutil.cC:\Dev.app\src\vcpkg\buildtrees\libpng\src\v1.6.37-05658d6f1a.clean\pngwutil.c(557): warning C4013: 'offsetof' undefined; assuming extern returning int
C:\Dev.app\src\vcpkg\buildtrees\libpng\src\v1.6.37-05658d6f1a.clean\pngwutil.c(558): error C2275: 'png_compression_buffer': illegal use of this type as an expression
C:\Dev.app\src\vcpkg\buildtrees\libpng\src\v1.6.37-05658d6f1a.clean\pngstruct.h(65): note: see declaration of 'png_compression_buffer'
C:\Dev.app\src\vcpkg\buildtrees\libpng\src\v1.6.37-05658d6f1a.clean\pngwutil.c(558): error C2065: 'output': undeclared identifier
C:\Dev.app\src\vcpkg\buildtrees\libpng\src\v1.6.37-05658d6f1a.clean\pngwutil.c(944): error C2275: 'png_compression_buffer': illegal use of this type as an expression
C:\Dev.app\src\vcpkg\buildtrees\libpng\src\v1.6.37-05658d6f1a.clean\pngstruct.h(65): note: see declaration of 'png_compression_buffer'
C:\Dev.app\src\vcpkg\buildtrees\libpng\src\v1.6.37-05658d6f1a.clean\pngwutil.c(944): error C2065: 'output': undeclared identifier
```

**Comment by JackBoosY** [comment]
Can you make sure your vcpkg is latest?

**Comment by JoseAmancio5597851** [comment]
vcpkg versionVcpkg package management program version 2020.11.12--unknownhash Enviado desde Correo para Windows 10 De: Jack·Boos·YuEnviado: lunes, 1 de febrero de 2021 10:36Para: microsoft/vcpkgCC: JoseAmancio5597851; MentionAsunto: Re: [microsoft/vcpkg] [libpng] build failure (#15703) Can you make sure your vcpkg is latest?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by JackBoosY** [comment]
According to the error messages, the corresponding variable cannot correspond to the number of lines in the code, so I think your libpng source is out of date.
Can you please remove _C:\Dev.app\src\vcpkg\buildtrees\libpng\src\v1.6.37-05658d6f1a.clean_ manually and try again?

Thanks.

**Comment by JackBoosY** [comment]
>C:\Dev.app\src\vcpkg\buildtrees\libpng\src\v1.6.37-05658d6f1a.clean\pngwutil.c(557): warning C4013: 'offsetof' undefined; assuming extern returning int

pngwutil.c(557):
```cpp
next = png_voidcast(png_compression_bufferp, png_malloc_base
```

> C:\Dev.app\src\vcpkg\buildtrees\libpng\src\v1.6.37-05658d6f1a.clean\pngwutil.c(558): error C2275: 'png_compression_buffer': illegal use of this type as an expression
 C:\Dev.app\src\vcpkg\buildtrees\libpng\src\v1.6.37-05658d6f1a.clean\pngwutil.c(558): error C2065: 'output': undeclared identifier

pngwutil.c(558):
```cpp
(png_ptr, PNG_COMPRESSION_BUFFER_SIZE(png_ptr)));
```

> C:\Dev.app\src\vcpkg\buildtrees\libpng\src\v1.6.37-05658d6f1a.clean\pngwutil.c(944): error C2275: 'png_compression_buffer': illegal use of this type as an expression
C:\Dev.app\src\vcpkg\buildtrees\libpng\src\v1.6.37-05658d6f1a.clean\pngwutil.c(944): error C2065: 'output': undeclared identifier

pngwutil.c(944):
```cpp
png_malloc(png_ptr, PNG_COMPRESSION_BUFFER_SIZE(png_ptr)));
```

**Comment by JackBoosY** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.
