### ISSUE TITLE
Can't load glfw3 with find_package in CMake

### ISSUE THREAD

**Issue by NauticalMile64** [Microsoft/vcpkg#1570]
I'm trying to build a target for ([this project](https://github.com/louis-langholtz/PlayRho)) using CMake. Command line installation verification:

```
C:\WINDOWS\system32>vcpkg list glfw
glfw3:x64-windows           3.2.1-1          GLFW is a free, Open Source, multi-platform libra...
glfw3:x64-windows-static    3.2.1-1          GLFW is a free, Open Source, multi-platform libra...
```

According to the final comment in issue #1425 the `find_package` method should be able to load `glfw3`. In addition, the [official glfw website also gives this as the preferred linking method]( http://www.glfw.org/docs/latest/build_guide.html#build_link_cmake_package). Yet when I try to do this:

```
find_package(glfw3 REQUIRED)
```

the `configure` step fails with the error:

```
CMake Error at Testbed/CMakeLists.txt:3 (find_package):
  By not providing "Findglfw3.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "glfw3", but
  CMake did not find one.

  Could not find a package configuration file provided by "glfw3" with any of
  the following names:

    glfw3Config.cmake
    glfw3-config.cmake

  Add the installation prefix of "glfw3" to CMAKE_PREFIX_PATH or set
  "glfw3_DIR" to a directory containing one of the above files.  If "glfw3"
  provides a separate development package or SDK, be sure it has been
  installed.
```

Of course the `Findglfw3.cmake` is absent from the indicated directory. Is this file supposed to be installed as part of the installation process? Or is there another preferred way to load this library?

**Comment by jasjuang** [comment]
Did you input the vcpkg toolchain file when you are cmaking the downstream project?

**Comment by NauticalMile64** [comment]
`CMAKE_TOOLCHAIN_FILE` is set to the full file path of the `vcpkg.cmake` file.

**Comment by jasjuang** [comment]
Hmm this is very bizarre. Are you able to reproduce this problem with a minimal repository?

To answer you last question, `Findglfw3.cmake` is not necessary because `find_package` should be able to find glfw3 automatically through glfw3Config.cmake via config mode. See more details [here](https://cmake.org/cmake/help/v3.0/command/find_package.html)

**Comment by NauticalMile64** [comment]
I just tried to load `zlib` and `metis` in a similar way. It couldn't find either of them (although `zlib` has a `FindZLIB.cmake` so it used the search method in that file before failing).

I just wrote:
```
message(STATUS "HELLO WORLD!")
```
At the top of my `vcpkg.cmake` file. The message was not printed when I `configure`d. So I guess it's not reading the `CMAKE_TOOLCHAIN_FILE` variable.

I even re-installed CMake earlier today, as well as pulling the latest from vcpkg, re-running the bootstrap batch file and re-running the `vcpkg integrate install` with no changes.

Hang on... does the `CMAKE_TOOLCHAIN_FILE` need to be specified from the command line interface? Up until now I've been setting it in the cmake-gui. Any other ideas?

**Comment by jasjuang** [comment]
I always used it on the command line. `cmake -A x64 -DCMAKE_TOOLCHAIN_FILE=/path/to/vcpkg.cmake`

**Comment by ras0219-msft** [comment]
CMake unfortunately doesn't respond well to changing the toolchain file after it has been configured the first time. Please try deleting the build directory and specifying it on the command line!

**Comment by NauticalMile64** [comment]
Ok the command-line specification with a clean build directory was the key. I used:`cmake -A x64 -DCMAKE_TOOLCHAIN_FILE=%VCPKG_CMAKE% -DCMAKE_VS_PLATFORM_TOOLSET=v140 --build ../..`

The reason I was trying to get away from this is I have to set a lot (~10 or so) CMake flags during the build process, and make sure the project builds with different combinations of selected flags. This is a hassle with the command line. Fortunately, after the initial command line build, I can edit the build configuration using `cmake-gui`, and it continues to load the libraries without issue.

Thanks everyone!

**Comment by ras0219-msft** [comment]
Unsolicited suggestion 😄: you might find CMake's "provide a cache file" functionality useful (the -C option)[1]. It _is_ a bit tricky to set up, though; you have to author the file with a bunch of "set" commands. Alternatively, you might try just putting the full command line in a batch file.

[1] https://cmake.org/cmake/help/v3.9/manual/cmake.1.html

**Comment by NauticalMile64** [comment]
@ras0219-msft Great idea. I'll make use of that chache file option at some point.
