### ISSUE TITLE
[New Port Request] Cinder

### ISSUE THREAD

**Issue by morphogencc** [microsoft/vcpkg#15704]
Library name: Cinder

Library description: Cinder is a library for 2d/3d graphics, computational geometry, and media i/o that is often used for graphical multimedia applications.

Source repository URL: https://github.com/cinder/cinder

Project homepage (if different from the source repository): https://libcinder.org/

Anything else that is useful to know when adding (such as optional features the library may have that should be included): None that I'm aware of at this time.

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by morphogencc** [comment]
No problem -- any particular reason / anything I could do to make it easier to port in the future?

**Comment by PhoebeHui** [comment]
For supporting new ports, we're happy to answer any questions we can to support this effort, but for now we prefer to support contributors as a mainainer than to take ownership ourselves, none of our core team is very familiar with cinder, we feel the contributors do a much better job than we could, so if you're failmilar with cinder, you can draft a PR, we're happy to review and accept the PR.
