### ISSUE TITLE
[aws-sdk-cpp] transcribestreaming component missing

### ISSUE THREAD

**Issue by sjpritchard** [microsoft/vcpkg#15702]
****

**Is your feature request related to a problem? Please describe.**
The aws-sdk-cpp v1.8.83#4 package only appears to include the batch transcribe component, and does not include the transcribestreaming component of the SDK

**Proposed solution**
Add the transcribestreaming component

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by teo-tsirpanis** [comment]
Feature exists in the latest version. https://github.com/microsoft/vcpkg/blob/7a3c94878b9b5d3e9eb2a31cd544609a4954b380/ports/aws-sdk-cpp/vcpkg.json#L831-L833
