### ISSUE TITLE
[IXWebsocket] Invalid options handling

### ISSUE THREAD

**Issue by ludekvodicka** [microsoft/vcpkg#15708]
**Host Environment**
- OS: [Windows]
- Compiler:  VS2019

**To Reproduce**
vcpkg install ixwebsocket[openssl]

**Failure** 
Although OpenSSL option is selected, the [mbedtls] option is used too.

The following packages will be built and installed:
    ixwebsocket[core,mbedtls,openssl,ssl]:x64-windows -> 11.0.4
  * mbedtls[core]:x64-windows -> 2.24.0#1
  * openssl[core]:x64-windows -> 1.1.1i
  * zlib[core]:x64-windows -> 1.2.11#9

**Comment by JonLiu1993** [comment]
@ludekvodicka ,As the feature of ixwebsocket, opensssl is also the backend of SSL. At the same time, feature ssl is the default backend of SSL. Its build depends on ixwebsocket[openssl], ixwebsocket[mbedtls], etc. When you build ixwebsocket[openssl], ixwebsocket[mbedtls] will be also installed.

**Comment by ludekvodicka** [comment]
Thanks for the reply, but I'm not sure if I understand it correctly.

When I'm building IXWebsocket manually, I don't need mbedtls and it's sufficient to use OpenSSL only. So I expected that the same should be true also when IXWebsocket is compilad via vcpkg.

In case there will be no other way, I will solve it by manual IXWebsocket compilation. I believe it's not optimal to increase deploy packages by adding also `mbedtls` libraries only because of some unnecessary dependency.

**Comment by JonLiu1993** [comment]
@ludekvodicka ,Thank you for your reply, I will pay attention to and optimize this issue next

**Comment by JackBoosY** [comment]
```cmake
    if (APPLE)
      if (NOT USE_MBED_TLS AND NOT USE_OPEN_SSL) # unless we want something else
        set(USE_SECURE_TRANSPORT ON)
      endif()
    # default to mbedtls on windows if nothing is configured
    elseif (WIN32)
      if (NOT USE_OPEN_SSL) # unless we want something else
        set(USE_MBED_TLS ON)
      endif()
    else() # default to OpenSSL on all other platforms
      if (NOT USE_MBED_TLS) # Unless mbedtls is requested
        set(USE_OPEN_SSL ON)
      endif()
    endif()
```
Openssl and tls should be mutually exclusive in Windows.

**Comment by LilyWangLL** [comment]
This issue has been fixed by PR https://github.com/microsoft/vcpkg/pull/33340, so I am closing this issue for now.
