### ISSUE TITLE
Azure tests are broken?

### ISSUE THREAD

**Issue by Luke-Filewalker** [microsoft/vcpkg#15713]
**Describe the bug**
It seems that some windows tests for updated ports are failing because the system on Azure/cmake can not find python. See pull request: microsoft/vcpkg#15719 
For target x64-windows, the error log from Azure is the following:

-- Detecting CXX compile features - done
CMake Error at D:/downloads/tools/cmake-3.19.2-windows/cmake-3.19.2-win32-x86/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
  Could NOT find PythonInterp (missing: PYTHON_EXECUTABLE) (Required is at
  least version "3")
Call Stack (most recent call first):
  D:/downloads/tools/cmake-3.19.2-windows/cmake-3.19.2-win32-x86/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:582 (_FPHSA_FAILURE_MESSAGE)
  D:/downloads/tools/cmake-3.19.2-windows/cmake-3.19.2-win32-x86/share/cmake-3.19/Modules/FindPythonInterp.cmake:169 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  C:/a/1/s/scripts/buildsystems/vcpkg.cmake:644 (_find_package)
  CMakeLists.txt:233 (find_package)
  CMakeLists.txt:239 (find_host_package)

-- Configuring incomplete, errors occurred!

Linux and macOS have no problems.

**Comment by Hoikas** [comment]
If a port requires Python, then you must install python in your portfile.cmake by:
```cmake
vcpkg_find_acquire_program(PYTHON3)
get_filename_component(PYTHON_PATH ${PYTHON3} DIRECTORY)
vcpkg_add_to_path("${PYTHON_PATH}")
```

**Comment by Luke-Filewalker** [comment]
Thanks, that solved it
