### ISSUE TITLE
Package: zlib:x64-windows-static

### ISSUE THREAD

**Issue by wangweiwei1188** [microsoft/vcpkg#15726]
**Host Environment**
- OS: Win10

**To Reproduce**
.\vcpkg install zlib:x64-windows-static

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
 Downloading https://mirror.bit.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz... Failed
-Please attach any additional failure logs mentioned in the console output.
I visit the https://mirror.bit.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz via IE browser,  the file is not existed.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by helloworld11133** [comment]
> The pkg-config in this mirror was update to 0.29.2-2:
> mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst

yeah, it's update to 0.29.2-2, but when I process the command .\vcpkg install zlib:x64-windows-static, it  download the 0.29.2-1, how can I replace 0.29.2-1 to 0.29.2-2?

**Comment by JackBoosY** [comment]
@wangweiwei1188  Will fix later.

**Comment by wangweiwei1188** [comment]
It's ok now.
