### ISSUE TITLE
[libgeotiff]  find_package(geotiff) does not work on Linux

### ISSUE THREAD

**Issue by Max-Manning** [microsoft/vcpkg#15723]
**Describe the bug**
After using vcpkg to install libgeotiff on linux, Cmake is unable to find the package correctly. (*Edit* - I found that the same thing happens on windows as well.)

**Environment**
- OS: Ubuntu 20.04 LTS
- Compiler: GCC 9.3

**To Reproduce**
1. ./vcpkg install libgeotiff
2. Use `find_package(geotiff CONFIG REQUIRED)` in a `CMakeLists.txt` file.

**Expected behavior**
CMake finds libgeotiff.

**Failure logs** 
After `find_package(geotiff CONFIG REQUIRED)`, Cmake produces the following error:
```
CMake Error at /home/max/code/vcpkg/scripts/buildsystems/vcpkg.cmake:644 (_find_package):
  Could not find a configuration file for package "geoTIFF" that is
  compatible with requested version "".

  The following configuration files were considered but not accepted:

    /home/max/code/vcpkg/installed/x64-linux/share/GeoTIFF/geotiff-config.cmake, version: 1.6.0

Call Stack (most recent call first):
  CMakeLists.txt:6 (find_package)
```

**Comment by NancyLi1013** [comment]
Hi @Max-Manning 
Thanks for posting this issue.

It should be `find_package(GeoTIFF CONFIG REQUIRED)`.

I have submitted a PR to fix it. Could you please help test if this can work fine for you?

**Comment by Max-Manning** [comment]
Yes, that fixes it. Thanks for your help!

**Comment by NancyLi1013** [comment]
Thanks for your feedback.

Please keep this issue open until the PR merged.

**Comment by MohamedNumair** [comment]
This issue seems to re-surface.
latest stable Julia version 1.11
tried resolve, removing manifest, and isolating the package. 
Error is "InitError: could not load library "C:\Users\mnumair\.julia\artifacts\cb61d24895a5cdb6a03e51121c4d1c439b77fef4\bin\libproj_9.dll" 

![Image](https://github.com/user-attachments/assets/95d1b575-5a79-4121-bdad-8827e192a1af)
