### ISSUE TITLE
Flann failed to build on cmake 3.9 because of FindHDF5.cmake related error

### ISSUE THREAD

**Issue by jasjuang** [Microsoft/vcpkg#1572]
I am on vs2015 and cmake 3.9. I am unable to build flann successfully because of FindHDF5.cmake related error. I suspect it's similar to the problem related to #1545. @ousttrue could you please help me look into this. I am trying to test #1283 and flann is one of the prerequisite. Below is the error log

``````
CMake Warning (dev) at CMakeLists.txt:17 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:21 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at C:/Program Files/CMake/share/cmake-3.9/Modules/FindHDF5.cmake:450 (get_target_property):
  get_target_property called with incorrect number of arguments
Call Stack (most recent call first):
  C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:145 (_find_package)
  cmake/flann_utils.cmake:25 (find_package)
  CMakeLists.txt:76 (find_hdf5)


CMake Warning at CMakeLists.txt:117 (message):
  gtest library not found, some tests will not be run


CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.9/Modules/FindOpenMP.cmake:212 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.9/Modules/FindOpenMP.cmake:324 (_OPENMP_GET_FLAGS)
  C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:145 (_find_package)
  CMakeLists.txt:122 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.9/Modules/FindOpenMP.cmake:277 (if):
  if given arguments:

    "TRUE"

  An argument named "TRUE" appears in a conditional statement.  Policy
  CMP0012 is not set: if() recognizes numbers and boolean constants.  Run
  "cmake --help-policy CMP0012" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.9/Modules/FindOpenMP.cmake:380 (_OPENMP_GET_SPEC_DATE)
  C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:145 (_find_package)
  CMakeLists.txt:122 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.9/Modules/FindOpenMP.cmake:277 (if):
  if given arguments:

    "TRUE"

  An argument named "TRUE" appears in a conditional statement.  Policy
  CMP0012 is not set: if() recognizes numbers and boolean constants.  Run
  "cmake --help-policy CMP0012" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.9/Modules/FindOpenMP.cmake:380 (_OPENMP_GET_SPEC_DATE)
  C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:145 (_find_package)
  CMakeLists.txt:122 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at test/CMakeLists.txt:4 (add_custom_target):
  Policy CMP0037 is not set: Target names should not be reserved and should
  match a validity pattern.  Run "cmake --help-policy CMP0037" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  The target name "test" is reserved or not valid for certain CMake features,
  such as generator expressions, and may result in undefined behavior.
This warning is for project developers.  Use -Wno-dev to suppress it.

``````

**Comment by ousttrue** [comment]
ok. I try to build ``vcpkg install flann`` and get same error.

error message

```
CMake Error at C:/Program Files/CMake/share/cmake-3.9/Modules/FindHDF5.cmake:450 (get_target_property):
  get_target_property called with incorrect number of arguments
```

is problem.

I comment out ``find_package(HDF5)`` of ``flann-1.9.1/cmake/flann_utils.cmake`` , then I successfully build flann.

**Comment by jasjuang** [comment]
@ousttrue Is there a way to solve this through modifying the port file?

**Comment by ousttrue** [comment]
@jasjuang ``CMakeLists.txt`` of flann has no option for hdf5. ``find_hd5()`` is top level.

**Comment by jasjuang** [comment]
@ousttrue Got it. Do you know how to solve it?

**Comment by ousttrue** [comment]
@jasjuang I think that There is a need to modify ``flann-1.9.1/CMakeLists.txt``.　
Patch is required.

How to create patch is here.

* https://github.com/Microsoft/vcpkg/blob/master/docs/examples/patching-libpng.md#patching-the-code-to-improve-compatibility

**Comment by UnaNancyOwen** [comment]
@jasjuang @ousttrue I think that character code is this cause.
Please execute the following command to set character code to UTF-8, before install FLANN port.
```
chcp 65001
vcpkg install flann
```
This work was not necessary previously.
I don't know why it is necessary to change charactor code to UTF-8.
(@ras0219-msft may know.)

**Comment by jasjuang** [comment]
@UnaNancyOwen Unfortunately `chcp 65001` does nothing for me. It still fails to compile.

**Comment by UnaNancyOwen** [comment]
@jasjuang Which version of vcpkg are you using?
I confirmed that it will be successfully installed using the latest vcpkg (f8ee92bacefaa95347b6c1eec5fda4dcf4666fe4).
![2017-08-02_18h26_25](https://user-images.githubusercontent.com/816705/28867320-a390b49c-77b0-11e7-9b32-8afc2f5b0b8e.png)
I defined the custom triplet (x86-windows-v140.cmake) for Visual Studio 2015.
```cmake
set(VCPKG_TARGET_ARCHITECTURE x86)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_PLATFORM_TOOLSET v140)
```

**Comment by jasjuang** [comment]
@UnaNancyOwen I am on the latest vcpkg but I was trying to build the 64 bit version, which is `x64-windows`

**Comment by UnaNancyOwen** [comment]
@jasjuang The x64 triplet install was also successful.
![2017-08-02_23h56_34](https://user-images.githubusercontent.com/816705/28879971-8b73b9c6-77de-11e7-8b03-9efa588388b6.png)

**Comment by jasjuang** [comment]
@UnaNancyOwen That's weird, but @ousttrue also confirmed that he can reproduce the error. Are you on cmake 3.9?

**Comment by UnaNancyOwen** [comment]
@jasjuang Yes, I'm using the CMake 3.9.0 (vcpkg/downloads/cmake-3.9.0-win32-x86) that downloaded and installed by vcpkg.

**Comment by atkawa7** [comment]
@jasjuang @UnaNancyOwen Just wondering. Does vcpkg prefer the bundled one over  locally installed cmake?

**Comment by UnaNancyOwen** [comment]
@jasjuang @atkawa7 I tried using local CMake 3.9.0, but FLANN port install was also successful.

**Comment by KindDragon** [comment]
> I tried using local installed CMake 3.9.0, but FLANN port install was also successful.

Try remove `vcpkg\buildtrees\flann` before installing it

**Comment by UnaNancyOwen** [comment]
@KindDragon I tried it, but install was successful.

**Comment by jasjuang** [comment]
I tried removing  vcpkg\buildtrees\flann and install it but the
installation is still unsuccessful. I even tried switching to windows
powershell and rerun bootstrap-vcpkg.bat, but it still fails to compile for
me

**Comment by KindDragon** [comment]
Error for me too (only with CMake 3.9):
```
CMake Error at D:/Work/vcpkg/downloads/cmake-3.9.0-win32-x86/share/cmake-3.9/Modules/FindHDF5.cmake:450 (get_target_property):
  get_target_property called with incorrect number of arguments
Call Stack (most recent call first):
  D:/Work/vcpkg/scripts/buildsystems/vcpkg.cmake:145 (_find_package)
  cmake/flann_utils.cmake:25 (find_package)
  CMakeLists.txt:76 (find_hdf5)
```

**Comment by ras0219-msft** [comment]
It seems like we should probably intercept the call to `find_package(HDF5)` inside our toolchain file and just "do the right thing" if the cmake version is 2.9. This would properly fix all of the portfiles and any user code. Something like [1].

[1] https://github.com/Microsoft/vcpkg/blob/6f112cf9611cabbe5641cc6ce0bd13d0144f50be/scripts/buildsystems/vcpkg.cmake#L141-L146

**Comment by KindDragon** [comment]
Changes in FindHDF5.cmake between CMake 3.8 and 3.9 https://gist.github.com/KindDragon/3cd8bd383ce3d145690335758b389b4c

**Comment by jasjuang** [comment]
@ras0219-msft @KindDragon  with the newly merged PCL I am eager to see this fixed, however I am unsure what should be added in vcpkg.cmake in order to fix this, could you give me some hints?

**Comment by alexkaratarakis** [comment]
@atkawa7 The downloaded copy is preferred over the system installed one. You can see the order here:
https://github.com/Microsoft/vcpkg/blob/master/toolsrc/src/VcpkgPaths.cpp#L107

**Comment by albertziegenhagel** [comment]
Have you tried passing `-DHDF5_NO_FIND_PACKAGE_CONFIG_FILE=ON` to cmake? This will disable using the hdf5-config.cmake completely in the FindHDF5 module.

Besides that CMake 3.10 will include a FindHDF5.cmake with some fixes that are especially relevant on Windows. See the merge requests [1] and [2]. I think the commit [3] is the one that fixes the problems you are facing. Maybe you can just copy the most recent FindHDF5.cmake file from the CMake repository into the FLANN modules directory from your portfile.


[1] https://gitlab.kitware.com/cmake/cmake/merge_requests/1023
[2] https://gitlab.kitware.com/cmake/cmake/merge_requests/1064/diffs
[3] https://gitlab.kitware.com/krthie/cmake/commit/fc9828448d54a63b7fc09ee044b6b0246632e011

**Comment by jasjuang** [comment]
@albertziegenhagel `-DHDF5_NO_FIND_PACKAGE_CONFIG_FILE=ON` works like magic. I will submit a PR shortly
