### ISSUE TITLE
How do I  Package: zeromq:x64-windows   Vcpkg version: 2020.11.12--unknownhash

### ISSUE THREAD

**Issue by sundayleemeng** [microsoft/vcpkg#15733]
When asking a question please also include where you looked for an answer (so we can update the documentation if needed).

**Comment by JackBoosY** [comment]
Did you mean `export` function or `install` function?

**Comment by sundayleemeng** [comment]
> Did you mean `export` function or `install` function?
I did .\vcpkg.exe install cppzmq:x64-windows and then reported this error

**Comment by JackBoosY** [comment]
If you encounter a build failure, please provide the output in Powershell and provide the failure log mentioned in the output.

Thanks.

**Comment by PhoebeHui** [comment]
@sundayleemeng, please reopen this issue with failure logs if it still be a problem for you.
