### ISSUE TITLE
Trouble installing cpprestsdk: openssl build fails

### ISSUE THREAD

**Issue by alexbryant** [Microsoft/vcpkg#1573]
Error: Building package openssl:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openssl:x86-windows
  Vcpkg version: 0.0.81-285c28000ad0460f62a3e7895311b975042b4be5

I tried checking for updates but it was already the most updated version of vcpkg

**Comment by yaoyu** [comment]
change cmake3.9.0 to cmake3.8.2

**Comment by ras0219-msft** [comment]
Thank you for reporting this issue!

It's most likely due to the strawberry perl website being down; we're investigating alternatives.

**Comment by ras0219-msft** [comment]
I've pushed c22ab980 which should resolve the issue. Please try updating to that version and rebuilding!

**Comment by JunielKatarn** [comment]
@ras0219 The issue doesn't seem to be resolved by that commit.

**Comment by ArseniyShestakov** [comment]
@yaoyu I tried to downgrade CMake from 3.9 to 3.8.2 too. Didn't work.

**Comment by ArseniyShestakov** [comment]
Problem is that MinGW that vcpkg install doesn't include Perl by default. As temporary solution you can download [perl-mingw](https://sourceforge.net/projects/perl-mingw) and put it into ```\vcpkg\downloads\tools\msys2\msys64\usr```.

Proper fix would be better though.

**Comment by ArseniyShestakov** [comment]
Also there 5 another ports depend on Strawberry Perl: libvpx, openblas, openssl-uwp, qca, qt5.

**Comment by ras0219-msft** [comment]
Thanks, I think I've corrected all the fallout issues due to this.

`vcpkg_find_acquire_program(PERL)` should now properly dispatch to Msys2, installing perl if it isn't present. This should fix all of the above mentioned portfiles as well.

**Comment by ArseniyShestakov** [comment]
@ras0219-msft I could confirm it's works now. I made clean install on Windows 10 VM and openssl build passed fine.

**Comment by codicodi** [comment]
opessl:x86-windows builds fine for me to, but openssl:x64-windows doesn't seem to work.
`Can't open perl script "cryptoperlasm/x86_64-xlate.pl": No such file or directory`
The file is `crypto/perlasm/x86_64-xlate.pl` Looks like path separator issue

**Comment by codicodi** [comment]
According to https://github.com/openssl/openssl/issues/264 msvc build with msys perl is not supported :( 

> Criteria for supported configuration is that perl is supposed to "match" build system. If you use Microsoft nmake, then you are expected to use "native" Windows perl such as ActivePerl, if you build under MSYS using MinGW, you should use MSYS perl, etc. Note that this requirement is not only about path delimiters, but also about the way exit codes and pipes are handled.

**Comment by ras0219-msft** [comment]
Ugh. Thanks for pointing that out, @codicodi.

Since the strawberry perl website appears to be back up, I'll restore using it as an immediate fix. In the longer term, we'll look at:
- Whether ActivePerl's license is compatible with Vcpkg's usage
- Improving openssl's build to support msys2 perl (it works in 32-bit, so it shouldn't be _that_ hard)
- Mirroring strawberryperl
- Rewriting openssl's buildsystem in something that doesn't require perl

**Comment by codicodi** [comment]
> Improving openssl's build to support msys2 perl (it works in 32-bit, so it shouldn't be that hard)

It kinda works, but I noticed that it creates `NUL` file in the buildtree (probably as part of mentioned pipe problems...).

> Rewriting openssl's buildsystem in something that doesn't require perl

Perl is needed for some scripts to translate assembly files from AT&T to Intels syntax, so I don't think we can get rid of it easily.

> Whether ActivePerl's license is compatible with Vcpkg's usage

No idea about licenses, but looks like only the most recent version is availible for free, so the download would break quite often.
