### ISSUE TITLE
AntTweakBar

### ISSUE THREAD

**Issue by JoseAmancio5597851** [microsoft/vcpkg#15742]
****

**Is your feature request related to a problem? Please describe.**

**Proposed solution**
AntTweakBar is a small and easy-to-use C/C++ library that allows programmers to quickly add a light and intuitive graphical user interface into graphic applications based on OpenGL (compatibility and core profiles), DirectX 9, DirectX 10 or DirectX 11 to interactively tweak parameters on-screen. 
**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered if applicable.

**Additional context**

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
