### ISSUE TITLE
[ffmpeg[openssl, x264]] build failure

### ISSUE THREAD

**Issue by HppZ** [microsoft/vcpkg#15745]
**Host Environment**
- OS: Windows 10 19041.631
- Compiler: msvc2019/vs2019 16.8.4
 
PS C:\Users\username> vcpkg install ffmpeg[openssl,x264] --triplet=x64-uwp
Computing installation plan...
The following packages will be rebuilt:
    ffmpeg[avcodec,avdevice,avfilter,avformat,avresample,core,gpl,nonfree,openssl,postproc,swresample,swscale,x264]:x64-uwp -> 4.3.1#9
The following packages will be built and installed:
  * x264[core]:x64-uwp -> 157-303c484ec828ed0#14
Additional packages (*) will be modified to complete this operation.
If you are sure you want to rebuild the above packages, run the command with the --recurse option
PS C:\Users\username> vcpkg install ffmpeg[openssl,x264] --triplet=x64-uwp --recurse
Computing installation plan...
The following packages will be rebuilt:
    ffmpeg[avcodec,avdevice,avfilter,avformat,avresample,core,gpl,nonfree,openssl,postproc,swresample,swscale,x264]:x64-uwp -> 4.3.1#9
The following packages will be built and installed:
  * x264[core]:x64-uwp -> 157-303c484ec828ed0#14
Additional packages (*) will be modified to complete this operation.
Starting package 1/3: ffmpeg:x64-uwp
Removing package ffmpeg:x64-uwp...
Removing package ffmpeg:x64-uwp... done
Elapsed time for package ffmpeg:x64-uwp: 301.3 ms
Detecting compiler hash for triplet x64-uwp...
Could not locate cached archive: C:\Users\username\AppData\Local\vcpkg\archives\16\16e23e65c52f12e9bf9ac2b2ba421d673ed17e53.zip
Could not locate cached archive: C:\Users\username\AppData\Local\vcpkg\archives\49\49611a3d7e4b075e2f1ec51a61c19611d9e75253.zip
Starting package 2/3: x264:x64-uwp
Building package x264[core]:x64-uwp...
-- Using cached C:/Users/username/Documents/username/opensource/vcpkg/downloads/mirror-x264-303c484ec828ed0d8bfe743500e70314d026c3bd.tar.gz
-- Cleaning sources at C:/Users/username/Documents/username/opensource/vcpkg/buildtrees/x264/src/14d026c3bd-bca2ebf740.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/username/Documents/username/opensource/vcpkg/downloads/mirror-x264-303c484ec828ed0d8bfe743500e70314d026c3bd.tar.gz
-- Applying patch uwp-cflags.patch
-- Using source at C:/Users/username/Documents/username/opensource/vcpkg/buildtrees/x264/src/14d026c3bd-bca2ebf740.clean
-- Configuring x64-uwp
-- Using msys root at C:/Users/username/Documents/username/opensource/vcpkg/downloads/tools/msys2/23ab37a7454cafa4
-- Using msys root at C:/Users/username/Documents/username/opensource/vcpkg/downloads/tools/msys2/c809757c94447846
-- Configuring x64-uwp-dbg
-- Configuring x64-uwp-rel
-- Using msys root at C:/Users/username/Documents/username/opensource/vcpkg/downloads/tools/msys2/b1b4e6089ab84adb
-- Building x64-uwp-dbg
-- Installing x64-uwp-dbg
-- Building x64-uwp-rel
-- Installing x64-uwp-rel
CMake Error at scripts/cmake/vcpkg_copy_tools.cmake:51 (message):
  Couldn't find this tool:
  C:/Users/username/Documents/username/opensource/vcpkg/packages/x264_x64-uwp/bin/x264.exe.
Call Stack (most recent call first):
  ports/x264/portfile.cmake:54 (vcpkg_copy_tools)
  scripts/ports.cmake:136 (include)

Error: Building package x264:x64-uwp failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: x264:x64-uwp
  Vcpkg version: 2020.11.12--unknownhash

Additionally, attach any relevant sections from the log files above.

**Comment by NancyLi1013** [comment]
Hi @HppZ 

Thanks for posting this issue.

It's duplicated to #15744. Let's track this issue there.

Thanks.
