### ISSUE TITLE
[cpr] callbacks update

### ISSUE THREAD

**Issue by Paristha** [microsoft/vcpkg#15762]
Library name: [cpr](https://github.com/whoshuu/cpr)

cpr recently introduced [new callbacks](https://github.com/whoshuu/cpr/pull/446/files). Although this merge occurred before v1.5.2, [1.5.2's source code](https://github.com/whoshuu/cpr/releases/tag/1.5.2) did not include them and I'm not sure when a version will be posted that does. The new callbacks allow cpr to handle response streams among other new features, and are already included in the [documentation](https://whoshuu.github.io/cpr/advanced-usage.html#setting-callbacks).

**Comment by JonLiu1993** [comment]
Duplicate to #16960
