### ISSUE TITLE
ANGLE dependency for qt5-base

### ISSUE THREAD

**Issue by JoergAtGithub** [microsoft/vcpkg#15766]
**Describe the bug**
We noticed, that the ANGLE DLLs (https://github.com/google/angle) for OpenGL emulation are missing in qt5-base

**Environment**
Windows 10

**Expected behavior**
The ANGLE DLLs are default shipped with qt5 for Windows, but not if qt5 comes from vcpkg: https://doc.qt.io/qt-5/windows-requirements.html

We looked at https://github.com/microsoft/vcpkg/blob/9255e8bf06ef15fdbc2faac40d520c6fd7ced0b2/ports/qt5-base/portfile.cmake#L126 and it seems that he dependency is inverted. ANGLE is only needed on Windows, since it translate OpenGL to Windows DirectX

**Comment by Neumann-A** [comment]
`vcpkg install angle` ?

angle is not a build requirement for qt5-base. OpenGL is dynamically selected in Qt so you might also use mesa.

**Comment by JoergAtGithub** [comment]
It's a runtime requirement, not a build requirement. It's shipped with all official Qt5 versions, but not with Qt6.
ANGLE is always dynamical linked, even if Qt itself is linked static. If Qt detects no or an unsuported OpenGL driver, like the popular Intel HD graphics 3000, it trys to load ANGLE.

**Comment by Neumann-A** [comment]
> It's a runtime requirement

And as such it does not belong into the build dependency graph.

you can always do `vcpkg install angle` or use a port overlay to change the qt build

**Comment by Hoikas** [comment]
Per the [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/control-files.md#build-depends):

> Vcpkg does not distinguish between build-only dependencies and runtime dependencies. The complete list of dependencies needed to successfully use the library should be specified.
>
> For example: websocketpp is a header only library, and thus does not require any dependencies at install time. However, downstream users need boost and openssl to make use of the library. Therefore, websocketpp lists boost and openssl as dependencies

Ergo, qt5 needs to install ANGLE.

**Comment by Neumann-A** [comment]
> The complete list of dependencies needed to successfully use the library should be specified.

this actually needs a definition for successfully. ANGLE is not needed to use the libraries. 
It might be used to run an application: (according to the OpenGL section)
https://doc.qt.io/qt-5/windows-requirements.html

Just saying this discussion will not lead to qt5 being changed to build with angle. It will just change the `Build-Depends` to include angle and probably mesa with llvmpipe to provide a software renderer.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
