### ISSUE TITLE
libpng build failed (windows 7)

### ISSUE THREAD

**Issue by jumpinjackie** [Microsoft/vcpkg#1576]
OS: Windows 7 SP1 (64-bit)
VS: VS2017 Update 2
Package: libpng (1.6.31)
Vcpkg version: 0.0.81-8b49289b77472ba078dfa0d08dcd77a903e2c1ca

Building `libpng:x86-windows` and `libpng:x64-windows` both fail at the package phase. The static triplets (`x86-windows-static`, `x64-windows-static`) build and install without issues.

This is the output I get when in build `libpng:x86-windows` (`x64-windows` output is just `s/x86-windows/x64-windows/g`)
```
The following packages will be built and installed:
    libpng:x86-windows
Building package libpng:x86-windows...
-- CURRENT_INSTALLED_DIR=D:/Workspace/vcpkg-origin/installed/x86-windows
-- DOWNLOADS=D:/Workspace/vcpkg-origin/downloads
-- CURRENT_PACKAGES_DIR=D:/Workspace/vcpkg-origin/packages/libpng_x86-windows
-- CURRENT_BUILDTREES_DIR=D:/Workspace/vcpkg-origin/buildtrees/libpng
-- CURRENT_PORT_DIR=D:/Workspace/vcpkg-origin/ports/libpng/.
-- Using cached D:/Workspace/vcpkg-origin/downloads/libpng-1.6.31.tar.xz
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Applying patch D:/Workspace/vcpkg-origin/ports/libpng/use-abort-on-all-platforms.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch D:/Workspace/vcpkg-origin/ports/libpng/use-abort-on-all-platforms.patch done
-- Configuring x86-windows-rel
-- Configuring x86-windows-rel done
-- Configuring x86-windows-dbg
-- Configuring x86-windows-dbg done
-- Package x86-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:43 (message):
    Command failed: D:/Workspace/vcpkg-origin/downloads/cmake-3.9.0-win32-x86/bin/cmake.exe;--build;.;--config;Release;--target;install;--;-v
    Working Directory: D:/Workspace/vcpkg-origin/buildtrees/libpng/x86-windows-rel
    See logs for more information:
      D:\Workspace\vcpkg-origin\buildtrees\libpng\package-x86-windows-rel-out.log
      D:\Workspace\vcpkg-origin\buildtrees\libpng\package-x86-windows-rel-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:49 (vcpkg_execute_required_process)
  ports/libpng/portfile.cmake:47 (vcpkg_install_cmake)
  scripts/ports.cmake:72 (include)


Error: Building package libpng:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libpng:x86-windows
  Vcpkg version: 0.0.81-8b49289b77472ba078dfa0d08dcd77a903e2c1ca

Additionally, attach any relevant sections from the log files above.
```

Attached are all the relevant log files I could find.

vcpkg output files:

[config-x86-windows-rel-out.log](https://github.com/Microsoft/vcpkg/files/1187579/config-x86-windows-rel-out.log.txt)
[config-x86-windows-rel-err.log](https://github.com/Microsoft/vcpkg/files/1187581/config-x86-windows-rel-err.log.txt)
[package-x86-windows-rel-out.log](https://github.com/Microsoft/vcpkg/files/1187580/package-x86-windows-rel-out.log.txt)

[config-x64-windows-rel-err.log.txt](https://github.com/Microsoft/vcpkg/files/1187647/config-x64-windows-rel-err.log.txt)
[config-x64-windows-rel-out.log.txt](https://github.com/Microsoft/vcpkg/files/1187648/config-x64-windows-rel-out.log.txt)
[package-x64-windows-rel-out.log.txt](https://github.com/Microsoft/vcpkg/files/1187646/package-x64-windows-rel-out.log.txt)

CMake

[x86-windows-rel/CMakeFiles/CMakeOutput.log](https://github.com/Microsoft/vcpkg/files/1187592/CMakeOutput.log.txt)
[x86-windows-rel/CMakeFiles/CMakeError.log](https://github.com/Microsoft/vcpkg/files/1187593/CMakeError.log.txt)

[x64-windows-rel/CMakeFiles/CMakeOutput.log](https://github.com/Microsoft/vcpkg/files/1187649/CMakeOutput.log.txt)
[x64-windows-rel/CMakeFiles/CMakeError.log](https://github.com/Microsoft/vcpkg/files/1187650/CMakeError.log.txt)

For (log file) reference: `D:/Workspace/vcpkg-origin` is where I cloned vcpkg to

**Comment by atkawa7** [comment]
@jumpinjackie Try downgrading to cmake 3.8.2

**Comment by ras0219-msft** [comment]
Thanks for sending so much information!

From the logs:
> C:/Program Files (x86)/Windows Kits/10/bin/10.0.15063.0/x64/mt.exe : general error c101008d: Failed to write the updated manifest to the resource of file "png-fix-itxt.exe". The operation failed.

Does building it a second time reproduce the error reliably?

**Comment by jumpinjackie** [comment]
@ras0219-msft This is strange, the build failure is erratic (some attempts pass, some attempts fail), but the error is at least consistent (error c101008d with `mt.exe`) in the `package-<triplet>-<config>-out.log` file

**Comment by jumpinjackie** [comment]
@atkawa7 I tried "downgrading" cmake by deleting the contents of the downloaded 3.9.0 install directory and unzipping the 3.8.2 files into that directory. Still the same `mt.exe` error in the package phase. Also tried with cmake 3.8.0.

**Comment by atkawa7** [comment]
@jumpinjackie Do you have anti malware?
It could be related to this
https://stackoverflow.com/questions/40843447/unsure-why-im-getting-error-msb6006-mt-exe-exited-with-code-31-on-first-build
https://stackoverflow.com/questions/16680717/error-msb6006-mt-exe-exited-with-code-31

**Comment by jumpinjackie** [comment]
@atkawa7 I do have MS security essentials running, but I never had to whitelist the vcpkg clone dir in the past. I guess I'll whitelist the vcpkg clone dir and see how it goes.

**Comment by jumpinjackie** [comment]
Ok, after whitelisting the vcpkg clone dir and doing at least 5 repeated install/uninstalls of the affected triplets, I can no longer reproduce the `mt.exe` error.

Guess nothing practical can be done here besides whitelisting the vcpkg clone dir in MSSE/[your AV software]

**Comment by atkawa7** [comment]
@ras0219-msft Just wondering if vcpkg has a list of FAQ.  This would be a good candidate to add to the list.
