### ISSUE TITLE
[opencolorio] installs incorrect CMake file

### ISSUE THREAD

**Issue by wrosecrans** [microsoft/vcpkg#15765]
****
Installing opencolorio on Windows-64 installed these cmake files:
./installed/x64-windows/share/opencolorio/OpenColorIO-debug.cmake
./installed/x64-windows/share/opencolorio/OpenColorIO-release.cmake
./installed/x64-windows/share/opencolorio/OpenColorIO.cmake

But trying to use the package with find_package(OpenColorIO) looks for [ OpenColorIOConfig.cmake, opencolorio-config.cmake, or FindOpenColorIO.cmake ] according to CMake's output.  As a result, CMake fails to find the package.

Additionally, the instructions after a successful install say to use "opencolorio" with find_package(), but the cmake files on disk are named "OpenColorIO" with upper case letters.

**Proposed solution**

The .cmake files installed by installing the package should follow the persnickety naming rules of CMake.

**Comment by ras0219-msft** [comment]
Thanks again!
