### ISSUE TITLE
[New Port Request] libbacktrace

### ISSUE THREAD

**Issue by autoantwort** [microsoft/vcpkg#15774]
Library name: libbacktrace

Library description: "Sample uses would be to print a detailed backtrace when an error occurs or to gather detailed profiling information."

Source repository URL: https://github.com/ianlancetaylor/libbacktrace

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
No. But the lib can be used for [boost stacktrace to get meaningful stacktraces on any compiler on POSIX, or MinGW, or MinGW-w64](https://www.boost.org/doc/libs/1_75_0/doc/html/stacktrace/configuration_and_build.html)

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by autoantwort** [comment]
Only you can reopen it, I can't

**Comment by PhoebeHui** [comment]
@autoantwort, thanks for the PR! I have reopened this issue.
