### ISSUE TITLE
install boringssl:x86-windows  failed

### ISSUE THREAD

**Issue by wangweiwei1188** [microsoft/vcpkg#15772]
**Host Environment**
- OS: win10
**To Reproduce**
vcpkg install boringssl

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
Downloading https://github.com/google/boringssl/archive/5902657734e2a796a514731e0fd0e80081ae43dc.tar.gz... Failed. Status: 4;"A requested feature, protocol or option was not found built-in in this libcurl due to a build-time decision."
-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by JonLiu1993** [comment]
@wangweiwei1188 ,Thanks for posting this issue,I can successfully build on my local computer，I investigated it and it seems that your problem is related to curl, you can try to reinstall curl to see if it can solve your problem：[https://curl.haxx.se/download.html](https://curl.haxx.se/download.html)

**Comment by JackBoosY** [comment]
Can you download https://github.com/google/boringssl/archive/5902657734e2a796a514731e0fd0e80081ae43dc.tar.gz manually?
It seems that your Windows 10 doesn't support SSL yet.

**Comment by wangweiwei1188** [comment]
> Can you download https://github.com/google/boringssl/archive/5902657734e2a796a514731e0fd0e80081ae43dc.tar.gz manually?
> It seems that your Windows 10 doesn't support SSL yet.

Oh，it's the gateway's error yesterday.I can download it now.Thanks very much.
