### ISSUE TITLE
[crossguid] build failure

### ISSUE THREAD

**Issue by cmaughan** [microsoft/vcpkg#15773]
**Host Environment**
- OS: Mac
- Compiler: Clang 12

**To Reproduce**
`./vcpkg install crossguid`

**Failure logs** 
vcpkg/buildtrees/crossguid/src/365d430337-f320045b03.clean/src/guid.cpp:403:7: error: unused function 'swap' [-Werror,-Wunused-function]
        void swap(xg::Guid &lhs, xg::Guid &rhs)

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by NancyLi1013** [comment]
Hi @cmaughan
 
Thanks for posting this issue.

It's duplicated to https://github.com/microsoft/vcpkg/issues/15594, let's track this issue there.
