### ISSUE TITLE
Error vcpkg install zeromq

### ISSUE THREAD

**Issue by xbotuk** [microsoft/vcpkg#15779]
vcpkg install zeromq

Computing installation plan...
The following packages will be built and installed:
    zeromq[core]:x64-windows -> 2019-09-20#2
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\user\AppData\Local\vcpkg\archives\d5\d581f14ba6de98821d2ebd556287740dc0ac9bc6.zip
Starting package 1/1: zeromq:x64-windows
Building package zeromq[core]:x64-windows...
-- Downloading https://github.com/zeromq/libzmq/archive/8d34332ff2301607df0fc9971a2fbe903c0feb7c.tar.gz -> zeromq-libzmq-8d34332ff2301607df0fc9971a2fbe903c0feb7c.tar.gz...
-- Downloading https://github.com/zeromq/libzmq/archive/8d34332ff2301607df0fc9971a2fbe903c0feb7c.tar.gz... Failed. Status: 7;"Couldn't connect to server"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:184 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".

      If error with status 4 (Issue #15434),
      try setting "http://user:password@your-proxy-ip-address:port/".

      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:147 (vcpkg_download_distfile)
  ports/zeromq/portfile.cmake:1 (vcpkg_from_github)
  scripts/ports.cmake:136 (include)

**Error: Building package zeromq:x64-windows failed with: BUILD_FAILED**
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zeromq:x64-windows
  Vcpkg version: 2020.11.12--unknownhash

Additionally, attach any relevant sections from the log files above.

**Comment by NancyLi1013** [comment]
Hi @xbotuk 

Thanks for posting this issue.

Could you please try to download  `https://github.com/zeromq/libzmq/archive/8d34332ff2301607df0fc9971a2fbe903c0feb7c.tar.gz` manually?

Then put this archive to _vcpkg_root_path/downloads/_ folder.
