### ISSUE TITLE
[nlohmann-json-v3.9.1] build failure : Failed. Status: 35;"SSL connect error"

### ISSUE THREAD

**Issue by rocketman123456** [microsoft/vcpkg#15781]
**Host Environment**
- OS: macos catalina
- Compiler: clang

**To Reproduce**
`./vcpkg install nlohmann-json`

**Failure logs** 
Computing installation plan...
The following packages will be built and installed:
  * nlohmann-json[core]:x64-osx -> 3.9.1
    tinygltf[core]:x64-osx -> 2020-07-28
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-osx...
Could not locate cached archive: /Users/developer/.cache/vcpkg/archives/ac/ac6fad1caf576c9d96b4c9eadea7af42e56c7a80.zip
Could not locate cached archive: /Users/developer/.cache/vcpkg/archives/2d/2d4b406b4045024304a4d7e141d1b0d1462b7847.zip
Starting package 1/2: nlohmann-json:x64-osx
Building package nlohmann-json[core]:x64-osx...
-- Downloading https://github.com/nlohmann/json/raw/v3.9.1/CMakeLists.txt -> nlohmann-json-v3.9.1/CMakeLists.txt...
-- Downloading https://github.com/nlohmann/json/raw/v3.9.1/CMakeLists.txt... Failed. Status: 35;"SSL connect error"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:184 (message):
      
      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      
      If error with status 4 (Issue #15434),
      try setting "http://user:password@your-proxy-ip-address:port/".
      
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  ports/nlohmann-json/portfile.cmake:7 (vcpkg_download_distfile)
  ports/nlohmann-json/portfile.cmake:16 (download_src)
  scripts/ports.cmake:136 (include)

Error: Building package nlohmann-json:x64-osx failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: nlohmann-json:x64-osx
  Vcpkg version: 2020.11.12-

Additionally, attach any relevant sections from the log files above.

**Comment by rocketman123456** [comment]
I can install other package, but fail to build this one

**Comment by NancyLi1013** [comment]
Hi @rocketman123456 

Thanks for posting this issue.

It seems that there is something wrong with your network. I tried to download and install this port without any problems.

```
vcpkg@VCPKGMM-12 vcpkg % ./vcpkg install nlohmann-json --editable
Computing installation plan...
The following packages will be built and installed:
    nlohmann-json[core]:x64-osx -> 3.9.1
Could not locate cached archive: /Users/vcpkg/.cache/vcpkg/archives/.zip
Starting package 1/1: nlohmann-json:x64-osx
Building package nlohmann-json[core]:x64-osx...
-- Downloading https://github.com/nlohmann/json/raw/v3.9.1/CMakeLists.txt -> nlo                                                                             hmann-json-v3.9.1/CMakeLists.txt...
-- Downloading https://github.com/nlohmann/json/raw/v3.9.1/LICENSE.MIT -> nlohma                                                                             nn-json-v3.9.1/LICENSE.MIT...
-- Downloading https://github.com/nlohmann/json/raw/v3.9.1/nlohmann_json.natvis                                                                              -> nlohmann-json-v3.9.1/nlohmann_json.natvis...
-- Downloading https://github.com/nlohmann/json/raw/v3.9.1/cmake/config.cmake.in                                                                              -> nlohmann-json-v3.9.1/cmake/config.cmake.in...
-- Downloading https://github.com/nlohmann/json/raw/v3.9.1/cmake/pkg-config.pc.i                                                                             n -> nlohmann-json-v3.9.1/cmake/pkg-config.pc.in...
-- Downloading https://github.com/nlohmann/json/raw/v3.9.1/cmake/nlohmann_jsonCo                                                                             nfigVersion.cmake.in -> nlohmann-json-v3.9.1/cmake/nlohmann_jsonConfigVersion.cm                                                                             ake.in...
-- Downloading https://github.com/nlohmann/json/releases/download/v3.9.1/include                                                                             .zip -> nlohmann-json-v3.9.1-include.zip...
-- Extracting source /Users/vcpkg/Nancy/vcpkg/downloads/nlohmann-json-v3.9.1-inc                                                                             lude.zip
-- Using source at /Users/vcpkg/Nancy/vcpkg/buildtrees/nlohmann-json/3.9.1-74ced                                                                             61d52
-- Configuring x64-osx-dbg
-- Configuring x64-osx-rel
-- Building x64-osx-dbg
-- Building x64-osx-rel
-- Installing: /Users/vcpkg/Nancy/vcpkg/packages/nlohmann-json_x64-osx/share/nlo                                                                             hmann-json/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package nlohmann-json[core]:x64-osx... done
Installing package nlohmann-json[core]:x64-osx...
Installing package nlohmann-json[core]:x64-osx... done
Elapsed time for package nlohmann-json:x64-osx: 5.586 s

Total elapsed time: 5.586 s

The package nlohmann-json:x64-osx provides CMake targets:

    find_package(nlohmann_json CONFIG REQUIRED)
    target_link_libraries(main PRIVATE nlohmann_json nlohmann_json::nlohmann_jso                                                                             n)
```
Could you please try to download these files manually?

**Comment by rocketman123456** [comment]
I tried, web browser can open and download files, while wget get same ssl error

**Comment by rocketman123456** [comment]
And win10 bootcamp could install this package without problem

**Comment by NancyLi1013** [comment]
Could you please test if this can work fine for you?

Update portfile.cmake as the follows:

```
vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO nlohmann/json
    REF db78ac1d7716f56fc9f1b030b715f872f93964e4 # v3.9.1
    SHA512 29cc71821e7595ce432142a1d167b69b280d1232e0331c0765f2c5edc302e5d717e6009d1a3347fffa0dbe49765ecd6be5d6d4705f71ccb1129f9226d9cc4016
    HEAD_REF master
)

vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA
    OPTIONS 
        -DJSON_BuildTests=0 
        -DJSON_MultipleHeaders=ON
)

vcpkg_install_cmake()

vcpkg_fixup_cmake_targets(CONFIG_PATH lib/cmake/nlohmann_json TARGET_PATH share/nlohmann_json)

vcpkg_replace_string(
    ${CURRENT_PACKAGES_DIR}/share/nlohmann_json/nlohmann_jsonTargets.cmake
    "{_IMPORT_PREFIX}/nlohmann_json.natvis"
    "{_IMPORT_PREFIX}/share/nlohmann_json/nlohmann_json.natvis"
)

file(REMOVE_RECURSE
    ${CURRENT_PACKAGES_DIR}/debug
    ${CURRENT_PACKAGES_DIR}/lib
)

if(EXISTS ${CURRENT_PACKAGES_DIR}/nlohmann_json.natvis)
    file(RENAME
        ${CURRENT_PACKAGES_DIR}/nlohmann_json.natvis
        ${CURRENT_PACKAGES_DIR}/share/nlohmann_json/nlohmann_json.natvis
    )
endif()

# Handle copyright
file(INSTALL ${SOURCE_PATH}/LICENSE.MIT DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)
```

**Comment by rocketman123456** [comment]
thank for your help, I found that, this problem is i cannot get correct raw.githubusercontent.com 's ip, it always get wrong ip address. setting /ect/hosts  directly to the correct ip will solve this problem
