### ISSUE TITLE
[libVLC] any chance to add libVLC into the repository?

### ISSUE THREAD

**Issue by amigo421** [microsoft/vcpkg#1578]
the request to add cross-platform video playback package - VideoLAN (aka VLC) 
http://git.videolan.org/git/vlc.git 

the repository includes the player itself, but only SDK in the request, libVLC.
which mostly consists from lib, include and plugins folders (and some files from src)

note: in case of positive decision to add the library, pay your attention that for successful usage this lib, it needs to be included - the plugins from full distribution.

currently this uses autotools for the build, as far as I see it can be built by  vc as well as mingw

**Comment by Voskrese** [comment]
@amigo421 https://github.com/sunqueen/vlc-2.2.6.32-2015
`-G"Visual Studio 14 2015" -T"v120"`, как то так

**Comment by Voskrese** [comment]
VLC for Windows 10 Desktop
https://github.com/videolan/vlc-winrt

https://github.com/videolan/vlc-winrt/blob/master/build/VLC.sln

**Comment by JackBoosY** [comment]
We can’t reopen this issue until a PR is opened, unfortunately, consider making a pull request!

**Comment by stephanecharette** [comment]
I also need this.  But I'm confused about the `closed` status.  Does this mean this isn't going to be added?

**Comment by JackBoosY** [comment]
@stephanecharette Nope, we hope that anyone can create a new PR to add it.

**Comment by stephanecharette** [comment]
> @stephanecharette Nope, we hope that anyone can create a new PR to add it.

If I knew how to build it, I wouldn't be using vcpkg.  I think this text on the main vcpkg page is misleading:

> If a library you need is not present in the vcpkg catalog, you can open an issue on the GitHub repo

If issues asking for new ports are simply closed with people saying "figure it out and submit a PR", then why bother opening an issue?

**Comment by JackBoosY** [comment]
@stephanecharette This issue has been closed due to our policy, you can open a new issue to request this port.

Thanks.

**Comment by stephanecharette** [comment]
> @stephanecharette This issue has been closed due to our policy, you can open a new issue to request this port.

What policy?

**Comment by JackBoosY** [comment]
@stephanecharette We prioritize bugs and features.

**Comment by Cheney-W** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
