### ISSUE TITLE
fontconfig:x64-linux build failure

### ISSUE THREAD

**Issue by kwiechen** [microsoft/vcpkg#15780]
**Host Environment**
- OS: [Ubuntu Linux]
- gcc 9.3.0

**To Reproduce**
`./vcpkg install fontconfig`

**Failure logs** 
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:108 (message):
    Command failed: /usr/bin/autoreconf -vfi
    Working Directory: /home/kai/vcpkg/buildtrees/fontconfig/src/75c13b2421-4651fd65ce.clean/
    Error code: 1
    See logs for more information:
      /home/kai/vcpkg/buildtrees/fontconfig/autoconf-x64-linux-out.log
      /home/kai/vcpkg/buildtrees/fontconfig/autoconf-x64-linux-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:536 (vcpkg_execute_required_process)
  ports/fontconfig/portfile.cmake:25 (vcpkg_configure_make)
  scripts/ports.cmake:136 (include)

**Comment by JackBoosY** [comment]
I can confirmed this issue was reported, but I don't remember which PR is fixing this issue.
@Neumann-A Do you remember the PR num?

**Comment by Neumann-A** [comment]
Without a log I cannot tell what is missing. I assuem AX_PTHREAD or something similar which requires autoconf-archive on linux.

**Comment by JackBoosY** [comment]
@kwiechen Please provide your failure log _/home/kai/vcpkg/buildtrees/fontconfig/autoconf-x64-linux-err.log_.
Thanks.

In my side, here is my log:
```
autoreconf: Entering directory `.'
autoreconf: running: autopoint --force
autopoint: *** The AM_GNU_GETTEXT_VERSION declaration in your configure.ac
               file requires the infrastructure from gettext-0.19.8 but this version
               is older. Please upgrade to gettext-0.19.8 or newer.
autopoint: *** Stop.
autoreconf: autopoint failed with exit status: 1
```

This is strange because I have updated gettext, autotool and autopoint using apt in my ubuntu machine.

**Comment by kwiechen** [comment]
solved for me, libtool was not correctly installed

Am Do., 21. Jan. 2021 um 09:53 Uhr schrieb Jack·Boos·Yu <
notifications@github.com>:

**Comment by JackBoosY** [comment]
Alright, only I have this issue now.
