### ISSUE TITLE
[snappy] Support for non-BMI2 build

### ISSUE THREAD

**Issue by ludekvodicka** [microsoft/vcpkg#15794]
We migrated the snappy library from our build to vcpkg. Unfortunately on some of our Windows virtual machines running on ESXI we're getting illegal instruction crash:

![chrome_2021-01-21_14-42-39](https://user-images.githubusercontent.com/3900551/105358825-f080fe00-5bf6-11eb-8964-09b4b2a73120.png)

Based on this post (https://stackoverflow.com/questions/61053436/how-to-build-snappy-on-windows-10-in-vs2015)  it's necessary to disable SNAPPY_HAVE_BMI2 option.

Would be great to have a port option to build SNAPPY without BMI2 support

**Comment by ludekvodicka** [comment]
This seems to be an issue in the Snappy: https://github.com/conda-forge/snappy-feedstock/issues/24

This piece of code wrongly detects BMI2 also on non-supported platforms:

```
check_cxx_source_compiles("
#include <immintrin.h>
int main() {
  return _bzhi_u32(0, 1);
}" SNAPPY_HAVE_BMI2) 
```

**Comment by JackBoosY** [comment]
Hmm... that seems like a upstream bug, can you report this to the upstream?

Thanks.

**Comment by ludekvodicka** [comment]
By upstream bug, you mean a bug directly in the snappy library?

I tried to report it but there is no "issue" section in the snappy repo and I didn't find any other way how to let them know.

**Comment by JackBoosY** [comment]
@ludekvodicka Here https://groups.google.com/forum/#!forum/snappy-compression.

**Comment by BlueAmulet** [comment]
Still running into this problem, finding bzhi instructions in code that uses snappy from vcpkg.

**Comment by FrankXie05** [comment]
@ludekvodicka Is still work for this issue? Does the problem still exist?

**Comment by JackBoosY** [comment]
Close this PR until upstream fixes this.
