### ISSUE TITLE
[libiconv] build failure on macos

### ISSUE THREAD

**Issue by ludekvodicka** [microsoft/vcpkg#15801]
**Host Environment**
- OS: 10.15 and 10.13
- Compiler: clang 12.0.0 (clang-1200.0.32.21) x86_64-apple-darwin19.6.0

**To Reproduce**
`./vcpkg install libiconv`

**Failure logs** 
There is no compiled iconv library after this instalation. Package folder contains only `BUILD_INFO`, `CONTROL ` and Share folder with `vcpkg-cmake-wrapper.cmake` and `vcpkg_abi_info.txt` . buildtrees/libiconv folder is also almost empty 

This is also probably the reason why libxml/libxslt can't be compiled on macos.

The strange is that `./vcpkg install libiconv` doesn't report any error:

![vmrc_2021-01-21_19-55-02](https://user-images.githubusercontent.com/3900551/105398403-9e55d200-5c22-11eb-8631-331ee94b3a7c.png)

**Comment by StarGate-One** [comment]
- Looks like it is an empty package on everything except windows, at least according to the portfile.cmake:
https://github.com/microsoft/vcpkg/blob/68a74950d0400f5a803026d0860f49853984bf11/ports/libiconv/portfile.cmake#L1-L7
- Explains why the directories are mostly empty
- An empty package normally means it is using software installed from other sources (CUDA and Vulkan are examples) or part of the development environment or operating system?

**Comment by StarGate-One** [comment]
- A quick google search show MacOS includes its own version of libiconv, but it has its own symbol naming convention (no _lib) which is not compatible with the rest of the software world.
Reference: https://mw.gl/posts/libiconv_mac/
- Another article shows installing a different libiconv can cause other issues with Apple software
Reference: https://gist.github.com/lamont-granquist/a6c231eb2e0b2d45641d#file-iconv_warnings-md
- It looks like (linux/unix) distros have there versions also as it is found on both my OpenSUSE VMs.
- I would guess the reason `vcpkg` installs an empty package on everything but windows is `vcpkg` is creating a place holder as the OS has its own...

**Comment by ludekvodicka** [comment]
Thanks for the detailed info. I also found info about different iconv naming in the native Apple version. This was the reason why I thought that this is a bug and that libiconv should be compiled separately via vcpkg.

Another reason was that libxslt doesn't work because of missing libiconv in the vcpkg. But probably this is not connected because libxslt port works ok under linux distros.

Sorry for the false alarm.

**Comment by NancyLi1013** [comment]
Hi @ludekvodicka 

Thanks for posting this issue and your focus on `iconv`.

I think @StarGate-One has answered your confusion about iconv on osx. So I'm closing this isseu for now.

@StarGate-One thanks again for your help.
