### ISSUE TITLE
[IXWebsocket] build failure on macos

### ISSUE THREAD

**Issue by ludekvodicka** [microsoft/vcpkg#15805]
**Host Environment**
- OS: 10.15
- Compiler: clang 12.0.0 (clang-1200.0.32.21) x86_64-apple-darwin19.6.0

**To Reproduce**
`./vcpkg install ixwebsocket[openssl]`

**Failure logs** 

When using ixwebsocket compiled via vcpkg on macos (works ok on linux and windows), there are missing symbols for SockerOpenSSL:

```
Undefined symbols for architecture x86_64:
  "ix::SocketOpenSSL::SocketOpenSSL(ix::SocketTLSOptions const&, int)", referenced from:
      std::__1::unique_ptr<ix::SocketOpenSSL, std::__1::default_delete<ix::SocketOpenSSL> > ix::make_unique<ix::SocketOpenSSL, ix::SocketTLSOptions const&, int&>(ix::SocketTLSOptions const&, int&) in libixwebsocket.a(IXSocketFactory.cpp.o)
  "ix::SocketOpenSSL::~SocketOpenSSL()", referenced from:
      std::__1::default_delete<ix::SocketOpenSSL>::operator()(ix::SocketOpenSSL*) const in libixwebsocket.a(IXSocketFactory.cpp.o)
ld: symbol(s) not found for architecture x86_64
```

Library works correctly when compiled manually:

```
CMAKE_OPENSSL="-DOPENSSL_ROOT_DIR=$OPENSSL_PATH -DOPENSSL_INCLUDE_DIR=$OPENSSL_PATH/include -DOPENSSL_LIBRARIES=$OPENSSL_PATH/lib"
CMAKE_ZLIB="-DZLIB_INCLUDE_DIR=$ZLIB_PATH/include -DZLIB_LIBRARY_DEBUG=$ZLIB_PATH/lib/libz.so -DZLIB_LIBRARY_RELEASE=$ZLIB_PATH/lib/libz.so"
CMAKE_SWITCHES="-DUSE_TLS=1 -DUSE_OPEN_SSL=1 -DCMAKE_INSTALL_PREFIX=$DEST_PATH $CMAKE_OPENSSL $CMAKE_ZLIB"

echo $CMAKE_SWITCHES

cmake ../ -G "Unix Makefiles" $CMAKE_SWITCHES -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE
```

**Comment by NancyLi1013** [comment]
Hi @ludekvodicka 

Thanks for posting this issue.

Could you please help provide your project case?

Also I wonder how you install this feature `openssl `on your local?

Currently, vcpkg cannot support feature on osx.

```
vcpkg@VCPKGMM-12 vcpkg % ./vcpkg install ixwebsocket[openssl]
zsh: no matches found: ixwebsocket[openssl]
```

**Comment by ludekvodicka** [comment]
Hi, I would be glad to help. What do you mean by "project case"? You mean where is IXWebsocket used?

Regarding openssl, I'm using openssl from vcpkg in both cases (in my own script as same as in vcpkg script). 

OpenSSL is installed via `vcpkg install openssl`

But you're right that ixwebsocket[openssl] doesn't work on macos. So maybe I tried to link different/old version of ixwebsocket. I will try it later and let you know.

**Comment by ludekvodicka** [comment]
Hi, I'm totally confused.

You're right that `vcpkg install ixwebsocket[openssl]` doesn't work.

BUT when I have the exact same command in the bash script, there is no error:
![chrome_2021-01-22_09-29-08](https://user-images.githubusercontent.com/3900551/105466305-52437580-5c94-11eb-8042-988411b5cea4.png)

This was the reason why I didn't noticed that features are not supported on macos. Do you have any idea why is this happening? ;-)

**Comment by NancyLi1013** [comment]
Sorry, I'm not sure why it can work if we write the command into the script.

For the original issue, you install `openssl` and `ixwebsockets `separately, right?

```
vcpkg install openssl
vcpkg install ixwebsockets
```
The project case is how you used `ixwebsockets `and `openssl ` in your project or application.

**Comment by ludekvodicka** [comment]
yes, openssl is installed separately because it's used also by other libraries.

**Comment by ludekvodicka** [comment]
vcpkg-install and vcpkg-copy-to-dest are helper scripts used to build and copy files to shared folders.

Regarding project case, it's Qt application for processing markets data.

This is .PRI to include OpenSSL + Curl

```
	OSWIN:CURL_PLATFORM = curl$${BIT_POSTFIX}

	#include
	OSWIN:INCLUDEPATH += $$SHARED_LIBS_PATH/$$CURL_PLATFORM/include
	OSWIN:INCLUDEPATH += $$SHARED_LIBS_PATH/openssl$${BIT_POSTFIX}/include

	OSLIN:INCLUDEPATH += $$SHARED_LIBS_PATH/curl/include
	OSLIN:INCLUDEPATH += $$SHARED_LIBS_PATH/openssl/include

	OSMAC:INCLUDEPATH += $$SHARED_LIBS_PATH/curl/include
	OSMAC:INCLUDEPATH += $$SHARED_LIBS_PATH/openssl/include

	#libraries
	OSWIN:LIBS 	+= $$SHARED_LIBS_PATH/$$CURL_PLATFORM/$${AX_SHLIBS_DIR_LIB}/libcurl$${AX_SHLIBS_LIB_POSTFIX}.lib
	OSLIN:LIBS 	+= $$SHARED_LIBS_PATH/curl/$${AX_SHLIBS_DIR_LIB}/libcurl$${AX_SHLIBS_LIB_POSTFIX}.a
	OSMAC:LIBS 	+= $$SHARED_LIBS_PATH/curl/$${AX_SHLIBS_DIR_LIB}/libcurl$${AX_SHLIBS_LIB_POSTFIX}.a

	#libraires openssl
	OSWIN:LIBS  += $$SHARED_LIBS_PATH/openssl$${BIT_POSTFIX}/$${AX_SHLIBS_DIR_LIB}/libcrypto.lib 
	OSWIN:LIBS  += $$SHARED_LIBS_PATH/openssl$${BIT_POSTFIX}/$${AX_SHLIBS_DIR_LIB}/libssl.lib 
	OSLIN:LIBS  += $$SHARED_LIBS_PATH/openssl/$${AX_SHLIBS_DIR_LIB}/libcrypto.a
	OSLIN:LIBS  += $$SHARED_LIBS_PATH/openssl/$${AX_SHLIBS_DIR_LIB}/libssl.a
	OSMAC:LIBS  += $$SHARED_LIBS_PATH/openssl/$${AX_SHLIBS_DIR_LIB}/libcrypto.a
	OSMAC:LIBS  += $$SHARED_LIBS_PATH/openssl/$${AX_SHLIBS_DIR_LIB}/libssl.a

```
This is .PRI file to include IXWebsocket to the app
```
OSWIN:INCLUDEPATH += $$SHARED_LIBS_PATH/ixwebsocket$${BIT_POSTFIX}/include
OSLIN:INCLUDEPATH += $$SHARED_LIBS_PATH/ixwebsocket/include
OSMAC:INCLUDEPATH += $$SHARED_LIBS_PATH/ixwebsocket/include

OSWIN:LIBS 	+= $$SHARED_LIBS_PATH/ixwebsocket$${BIT_POSTFIX}/$${AX_SHLIBS_DIR_LIB}/ixwebsocket.lib
OSWIN:LIBS  += Ws2_32.lib Shlwapi.lib
	
OSLIN:LIBS 	+= $$SHARED_LIBS_PATH/ixwebsocket/$${AX_SHLIBS_DIR_LIB}/libixwebsocket.a
OSMAC:LIBS 	+= $$SHARED_LIBS_PATH/ixwebsocket/$${AX_SHLIBS_DIR_LIB}/libixwebsocket.a

include (../../axCompression.pri) #because of ZLIB
include (../../axCurlNetworkHelper.pri) #because of OPENSSL

#temporary fix, until port will be fixed
OSWIN:LIBS  += $$SHARED_LIBS_PATH/mbedtls$${BIT_POSTFIX}/$${AX_SHLIBS_DIR_LIB}/mbedcrypto.lib
OSWIN:LIBS  += $$SHARED_LIBS_PATH/mbedtls$${BIT_POSTFIX}/$${AX_SHLIBS_DIR_LIB}/mbedx509.lib
OSWIN:LIBS  += $$SHARED_LIBS_PATH/mbedtls$${BIT_POSTFIX}/$${AX_SHLIBS_DIR_LIB}/mbedtls.lib

```

**Comment by NancyLi1013** [comment]
@ludekvodicka 

Sorry, I'm not familiar with these .PRI  files. So I don't know how to reproduce this in this way.

Could you please provide another simple application that uses `openssl `and `ixwebsocket`?

**Comment by NancyLi1013** [comment]
@ludekvodicka 

Is this sill a problem for you?

**Comment by NancyLi1013** [comment]
After install `ixwebsocket[openssl]` successfully, I can build without any errors with the following usge.

```
find_package(ixwebsocket CONFIG REQUIRED)

target_link_libraries(main PRIVATE ixwebsocket::ixwebsocket)
```
Please feel free to reopen this issue if it is still a problem for you. Note: Please provide your project sample here.
