### ISSUE TITLE
soil build failure

### ISSUE THREAD

**Issue by AmeliaMesdag** [microsoft/vcpkg#15800]
**Host Environment**
- OS: Any
- Compiler: Any

**To Reproduce**
`./vcpkg install soil`

**Failure logs** 
Building package soil[core]:x86-windows...
-- Downloading http://www.lonesock.net/files/soil.zip -> soil-2008.07.07.zip...
-- Downloading http://www.lonesock.net/files/soil.zip... Failed. Status: 22;"HTTP response code said error"

**Comment by StarGate-One** [comment]
- Port soil2 is an updated version, it may/may not be sufficient for your needs?
- If not, then information about soil can be found on the Wayback Machine Archives: https://web.archive.org/web/20200728145723/http://lonesock.net/soil.html 
- Download the file: https://web.archive.org/web/20200104042737/http://www.lonesock.net/files/soil.zip
  - Rename the file from `soil` to `soil-2008.07.07.zip`
  - Move the file into the `[vcpkg-root]/downloads` directory
  - Run `./vcpkg install soil` again
 
 /cc: @BillyONeal @JackBoosY 
- Looks like the primary site and download link shows NOT SECURE in web browser
- A web page is never loaded, just a white screen 
- The host www.lonesock.net is pingable, just no web sites
- This could be a candidate to remove from vcpkg as the source can only be found on the Wayback Machine Archives?

**Comment by JackBoosY** [comment]
The official page is invalid now.

**Comment by JackBoosY** [comment]
@StarGate-One Is `web.archive.org` stable? I think this cache will be deleted in the future.

**Comment by StarGate-One** [comment]
@JackBoosY I am not sure you would want to use web.archive.org for download sources - it could disappear at any time.

**Comment by BillyONeal** [comment]
Right, we should not point to archive.org; if upstream is gone the port should be delisted.

**Comment by JackBoosY** [comment]
At last, I found this issue was found and solved in #13000, we will remove this port after 2021-03-01.

**Comment by NancyLi1013** [comment]
This has been solved in PR #17012. Please update to the latest vcpkg to rebuild this.
