### ISSUE TITLE
Can't include headers

### ISSUE THREAD

**Issue by wmeister** [microsoft/vcpkg#15818]
I did the following:

```
PS D:\vcpkg> .\vcpkg.exe install sdl2
Computing installation plan...
The following packages are already installed:
    sdl2[core]:x86-windows
Package sdl2:x86-windows is already installed

Total elapsed time: 3.087 ms

The package sdl2:x86-windows provides CMake targets:

    find_package(SDL2 CONFIG REQUIRED)
    target_link_libraries(main PRIVATE SDL2::SDL2 SDL2::SDL2main)

PS D:\vcpkg> .\vcpkg.exe integrate install
Applied user-wide integration for this vcpkg root.

All MSBuild C++ projects can now #include any installed libraries.
Linking will be handled automatically.
Installing new libraries will make them instantly available.

```

Now when I goto `#include <SDL.h>` in visual studio 2019 it is not found.

**Comment by maxkunes** [comment]
Have you tried including <sdl2/SDL.h>?

From my experience, it seems the include directory is set to the vcpkg folder that stores all the headers for the installed packages. But, each package has its own folder I believe. You should be able to check the correct path in your vcpkg installed packages folder / include.

**Comment by wmeister** [comment]
that doesn't work either sadly

**Comment by maxkunes** [comment]
@wmeister What triplet is visual studio using? VCPKG installed x64-windows, so if your project is x64, you wouldn't see the include.  Is vcpkg integration enabled in the project settings? You can change the build output verbosity in VS2019 to see a bit more of what is being searched for. The exact option to change is somewhere in a readme. Not sure the exact location, sorry!

**Comment by wmeister** [comment]
i was able to fix it by doing the follow:

```
PS D:\vcpkg> .\vcpkg.exe install sdl2:x64-windows
Computing installation plan...
The following packages will be built and installed:
    sdl2[core]:x64-windows
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\a\AppData\Local\vcpkg\archives\40\40fba019cf2d2b4cef761d4b7bcafaeea53c12fe.zip
Starting package 1/1: sdl2:x64-windows
Building package sdl2[core]:x64-windows...
-- Using cached D:/vcpkg/downloads/SDL2-2.0.12.tar.gz
-- Cleaning sources at D:/vcpkg/buildtrees/sdl2/src/SDL2-2-7528f85a66.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/vcpkg/downloads/SDL2-2.0.12.tar.gz
-- Applying patch export-symbols-only-in-shared-build.patch
-- Applying patch enable-winrt-cmake.patch
-- Applying patch disable-hidapi-for-uwp.patch
-- Applying patch fix-space-in-path.patch
-- Applying patch disable-wcslcpy-and-wcslcat-for-windows.patch
-- Applying patch fix-EventToken-header-reference.patch
-- Applying patch 0006-sdl2-Enable-creation-of-pkg-cfg-file-on-windows.patch
-- Applying patch 0007-sdl2-skip-ibus-on-linux.patch
-- Applying patch 0008-fix-macos-metal-test.patch
-- Using source at D:/vcpkg/buildtrees/sdl2/src/SDL2-2-7528f85a66.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Using msys root at D:/vcpkg/downloads/tools/msys2/c809757c94447846
-- Fixing pkgconfig file: D:/vcpkg/packages/sdl2_x64-windows/lib/pkgconfig/sdl2.pc
-- Fixing pkgconfig file: D:/vcpkg/packages/sdl2_x64-windows/debug/lib/pkgconfig/sdl2.pc
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\a\AppData\Local\vcpkg\archives\40\40fba019cf2d2b4cef761d4b7bcafaeea53c12fe.zip
Building package sdl2[core]:x64-windows... done
Installing package sdl2[core]:x64-windows...
Installing package sdl2[core]:x64-windows... done
Elapsed time for package sdl2:x64-windows: 49.43 s

Total elapsed time: 59.27 s

The package sdl2:x64-windows provides CMake targets:

    find_package(SDL2 CONFIG REQUIRED)
    target_link_libraries(main PRIVATE SDL2::SDL2 SDL2::SDL2main)
```

**Comment by maxkunes** [comment]
Sounds like your VS project is x64 dynamic, so you installed the correct version of the library for that.

**Comment by wmeister** [comment]
Thanks for your help @maxkunes

How would I configure my project to use the 32bit version?

**Comment by NancyLi1013** [comment]
Hi @wmeister 

Thanks for posting this issue.

Do you use CMake project or msbuild in Visual Studio?

Note: the header should be `#include <SDL2/SDL.h>`.

**Comment by wmeister** [comment]
msbuild in VS.

**Comment by hgbutte** [comment]
I have a similar issue:

I did the following steps:
```
vcpkg install sqlpp11
vcpkg integrate install
```

Downloading manually sqlpp11-connector-odbc (as it is not included in vcpkg) from https://github.com/Erroneous1/sqlpp11-connector-odbc

Then did the following steps:
```
cmake .. -G"Visual Studio 16 2019" -A Win32 -DCMAKE_TOOLCHAIN_FILE="D:\Tools\vcpkg\scripts\buildsystems\vcpkg.cmake" -DSQLPP11_ODBC_DISABLE_SHARED=ON
cmake --build . --target "sqlpp11-odbc-static"
```

cmake build calls tells me not finding the headers of sqlpp11

When using VS2019 to open generated vcxproj file "sqlpp11-odbc-static,vcproj" i can see that in the project settings the "Use Vcpkg" is set to "NO". 

If i switch this to "YES", i can compile in VS2019 or cmake successfully.

Is this a problem of vcpkg.cmake or sqlpp11-connector-odbc?

**Comment by NancyLi1013** [comment]
@wmeister 
Please provide your project sample.

@hgbutte 
It seems that you use a static library in your project. 
For cmake project, you need to add `-DVCPKG_TARGET_TRIPLET=x86-windows-static` to cmake command.

For msbuild project, you need to add this to your project.

```
 <PropertyGroup Label="Globals">
 <!-- .... -->
 <VcpkgTriplet Condition="'$(Platform)'=='Win32'">x86-windows-static</VcpkgTriplet>
 <VcpkgTriplet Condition="'$(Platform)'=='x64'">x64-windows-static</VcpkgTriplet>
</PropertyGroup>
```
Please see https://devblogs.microsoft.com/cppblog/vcpkg-updates-static-linking-is-now-available/

Also please use `sqlpp11 `like this if you install it via vcpkg.
```
 find_package(Sqlpp11 CONFIG REQUIRED)
 target_link_libraries(main PRIVATE sqlpp11::sqlpp11)
```

**Comment by NancyLi1013** [comment]
@wmeister and @hgbutte 

Please let me know if this is still a problem for you.

**Comment by hgbutte** [comment]
@NancyLi1013 

Now i understand the problem. 
I haven't realized that it is looking for sqlpp11:x86-windows-static. Output isn't very verbose on this, just telling that it cannot find sqlpp11.
But thank you for your information. Problem solved so far.

**Comment by NancyLi1013** [comment]
Thanks for your feedback @hgbutte.

Closing this issue for now. Please feel free to reopen this issue if it is still a problem for you @wmeister.
