### ISSUE TITLE
[openvdb] update to v8.0.0

### ISSUE THREAD

**Issue by orbingol** [microsoft/vcpkg#15811]
Library name: OpenVDB

New version number: v8.0.0

Other information that may be useful (release notes, etc...)

* Release notes: https://github.com/AcademySoftwareFoundation/openvdb/releases/tag/v8.0.0
* v8.0.0 comes with a new tool/extension called [OpenVDB AX](https://www.openvdb.org/documentation/doxygen/openvdbax.html). This could be added as a feature package.

**Comment by orbingol** [comment]
OpenVDB has a bugfix release v8.0.1. I see that the PR is still on hold. Would it be possible to directly update to v8.0.1

* Release notes: https://github.com/AcademySoftwareFoundation/openvdb/releases/tag/v8.0.1

I can also open a new request if you think it is more convenient.

**Comment by JonLiu1993** [comment]
@orbingol ,I can modify my pr and re-update to the first version 8.0.1,

**Comment by orbingol** [comment]
> @orbingol ,I can modify my pr and re-update to the first version 8.0.1,

That would be great. Eventually, v8.0.1 is a bugfix release and it would be more convenient for users to use the latest bugfix release for v8.0.x series.

**Comment by orbingol** [comment]
Just wanted to check in to see if there are any updates on this port update
