### ISSUE TITLE
7zip failed while extracting 7-zip.commandline.18.1.0.nupkg

### ISSUE THREAD

**Issue by BadHomer** [microsoft/vcpkg#15817]
When I installed vcpkg and started the installation, the following problems occurred, how can I solve them？
`C:\Users\Влад\Documents\GitHub\vcpkg>vcpkg install uwebsockets
Computing installation plan...
A suitable version of cmake was not found (required v3.19.2). Downloading portable cmake v3.19.2...
Extracting cmake...
A suitable version of 7zip was not found (required v18.1.0). Downloading portable 7zip v18.1.0...
Downloading 7zip...
  https://www.nuget.org/api/v2/package/7-Zip.CommandLine/18.1.0 -> C:\Users\Влад\Documents\GitHub\vcpkg\downloads\7-zip.commandline.18.1.0.nupkg
Extracting 7zip...
A suitable version of nuget was not found (required v5.5.1). Downloading portable nuget v5.5.1...
Downloading nuget...
  https://dist.nuget.org/win-x86-commandline/v5.5.1/nuget.exe -> C:\Users\Влад\Documents\GitHub\vcpkg\downloads\22ea847d-nuget.exe
Failed to extract 'C:\Users\Влад\Documents\GitHub\vcpkg\downloads\7-zip.commandline.18.1.0.nupkg' with message:
Feeds used:
  C:\Users\Влад\Documents\GitHub\vcpkg\downloads

Attempting to gather dependency information for package '7-zip.commandline.18.1.0' with respect to project 'C:\Users\Р’Р»Р°Рґ\Documents\GitHub\vcpkg\downloads\tools\7zip-18.1.0-windows.partial.25508', targeting 'Any,Version=v0.0'
Gathering dependency information took 105.12 ms
Attempting to resolve dependencies for package '7-zip.commandline.18.1.0' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package '7-zip.commandline.18.1.0'
Resolved actions to install package '7-zip.commandline.18.1.0'
Retrieving package '7-Zip.CommandLine 18.1.0' from 'C:\Users\Влад\Documents\GitHub\vcpkg\downloads'.
Adding package '7-Zip.CommandLine.18.1.0' to folder 'C:\Users\Р’Р»Р°Рґ\Documents\GitHub\vcpkg\downloads\tools\7zip-18.1.0-windows.partial.25508'
WARNING: Install failed. Rolling back...
Executing nuget actions took 287.98 ms
Access to the path 'C:\Users\Р’Р»Р°Рґ\Documents\GitHub\vcpkg\downloads\tools\7zip-18.1.0-windows.partial.25508\7-Zip.CommandLine.18.1.0' is denied.`

**Comment by NancyLi1013** [comment]
Hi @BadHomer 

Thanks for posting this issue.

```
WARNING: Install failed. Rolling back...
Executing nuget actions took 287.98 ms
Access to the path 'C:\Users\Р’Р»Р°Рґ\Documents\GitHub\vcpkg\downloads\tools\7zip-18.1.0-windows.partial.25508\7-Zip.CommandLine.18.1.0' is denied.`
```
Seems you don't have permission to get access to the path 'C:\Users\Р’Р»Р°Рґ\Documents\GitHub\vcpkg\downloads\tools\7zip-18.1.0-windows.partial.25508\7-Zip.CommandLine.18.1.0'.

Could you please try to build on another folder that is not in C driver?

**Comment by NancyLi1013** [comment]
@BadHomer 

Please let me know if you still have this problem.

**Comment by NancyLi1013** [comment]
Closing this issue for inactive. Please feel free to reopen this if it is still a problem for you.
