### ISSUE TITLE
[New Port Request] OpenXLSX

### ISSUE THREAD

**Issue by ivanovmp** [microsoft/vcpkg#15824]
Library name: OpenXLSX

Library description: C++ library for reading, writing, creating and modifying Microsoft Excel® files, with the .xlsx format

Source repository URL: [https://github.com/troldal/OpenXLSX](https://github.com/troldal/OpenXLSX)

There is another issue concerning this library, but that was closed a few months ago, so I'd like to ask sir @gritukan whether he has an ambition strong enough to handle this port.

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
