### ISSUE TITLE
[New Port Request] stun

### ISSUE THREAD

**Issue by curtisgray** [microsoft/vcpkg#15827]
Library name: stun

Library description: STUN library, client, and server, written in C++, for getting NAT type and external IP. Compliant with the latest RFCs including 5389, 5769, and 5780. Also includes backwards compatibility for RFC 3489. Supports both UDP and TCP on both IPv4 and IPv6.

Source repository URL: https://github.com/alhasanmridha/stun

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
