### ISSUE TITLE
arm64 VS CMake integration with vcpkg manifest file failing upon configure 

### ISSUE THREAD

**Issue by esweet431** [microsoft/vcpkg#15823]
**Describe the bug**
I'm trying to configure a CMake project in Visual Studio. My toolset is msvc_arm64_x64 and I have a vcpkg.json with 4 packages that support arm64-windows. The configure step is failing. 

**Environment**
- OS: Windows
- Compiler: msvc arm64 (latest installed with VS 2019 16.9 Preview 3)

**To Reproduce**
1. Create CMake project in Visual Studio 2019 version 16.9 Preview 3. Ensure the latest arm64 build tools are installed
2. Add a new arm64-debug CMake configuration to CMakeSettings.json 
3. Add a vcpkg manifest file to the root of the CMake project with glad, glfw3, imgui, gtest
4. Make the arm64-debug configuration the active CMake configuration in Visual Studio
5. Attempt to configure the project
6. See error, failure logs below

**Expected behavior**
vcpkg will automatically build and install the arm64-windows triplet of the 4 libraries listed in vcpkg.json and the arm64-debug configuration of my CMake project will successfully configure. 

**Failure logs** 
Detecting compiler hash for triplet arm64-windows...
Unsupported toolchain combination. Target was: arm64 but supported ones were:
x86,amd64,x86_amd64,amd64_x86

**Comment by strega-nil** [comment]
Logs from `cmake -B build-compilertracking -S scripts/detect_compiler -A arm64`:

```
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
-- The C compiler identification is MSVC 19.28.29812.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Preview/VC/Tools/MSVC/14.28.29812/b
in/Hostx64/arm64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- The CXX compiler identification is MSVC 19.28.29812.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Preview/VC/Tools/MSVC/14.28.29812
/bin/Hostx64/arm64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
#COMPILER_HASH#9306dc21c1ae74a9f79ebb3310835a3ba81392ca
#COMPILER_C_HASH#5a57d8a31bb0d527d01ebe06fe7438085538c548
#COMPILER_C_VERSION#19.28.29812.0
#COMPILER_C_ID#MSVC
#COMPILER_CXX_HASH#5a57d8a31bb0d527d01ebe06fe7438085538c548
#COMPILER_CXX_VERSION#19.28.29812.0
#COMPILER_CXX_ID#MSVC
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/ersweet/vcpkg/build-compilertracking
```

so clearly the ARM64 compilers work. cc @ras0219

**Comment by ras0219** [comment]
We likely selected a different visual studio than CMake does by default. You can see the list of visual studio instances we detected via
```
vcpkg x-vsinstances
```
sorted by our preference. If you want us to use a different one, you can set that in the environment variable `VCPKG_VISUAL_STUDIO_PATH`: https://github.com/microsoft/vcpkg/blob/master/docs/users/config-environment.md#vcpkg_visual_studio_path

**Comment by esweet431** [comment]
That helped a bit, I'm now hitting this: 

Detecting compiler hash for triplet arm64-windows...
Error occurred while detecting compiler information. Pass `--debug` for more information.

**Comment by ras0219** [comment]
What does it say when you pass `--debug`?

**Comment by esweet431** [comment]
CMake is invoking vcpkg for me. How do I pass --debug? Should I run vcpkg install from cmd?

**Comment by ras0219** [comment]
The easiest way to repro this issue will be to switch to just using the cli directly to install something simple, like `vcpkg install zlib:arm64-windows`.

**Comment by esweet431** [comment]
>vcpkg install zlib:arm64-windows --debug
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' = on
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Using vcpkg-root: C:\Users\ersweet\vcpkg
[DEBUG] Using installed-root: C:\Users\ersweet\vcpkg\installed
[DEBUG] Using buildtrees-root: C:\Users\ersweet\vcpkg\buildtrees
[DEBUG] Using downloads-root: C:\Users\ersweet\vcpkg\downloads
[DEBUG] Using packages-root: C:\Users\ersweet\vcpkg\packages
[DEBUG] Using scripts-root: C:\Users\ersweet\vcpkg\scripts
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
[DEBUG] Default binary cache path is: C:\Users\ersweet\AppData\Local\vcpkg/archives
Computing installation plan...
Error: There are invalid field types in the CONTROL or manifest file of C:\Users\ersweet\vcpkg\ports\boost-locale\vcpkg.json
The following fields had the wrong types:

    features was expected to be an array of feature definitions

Error: Failed to load port boost-locale from C:\Users\ersweet\vcpkg\ports\boost-locale
[DEBUG] C:\Users\ersweet\vcpkg\toolsrc\src\vcpkg\portfileprovider.cpp(153)
[DEBUG] Exiting after 100639 us (53426 us)

**Comment by ras0219** [comment]
That looks like an out-of-date vcpkg issue; Did you re-run `./bootstrap-vcpkg.bat` after running `git pull`?

**Comment by esweet431** [comment]
Oops, no. Sorry about that. I re-ran it and it's working correctly now. Thank you both!

**Comment by esweet431** [comment]
Resolved.
