### ISSUE TITLE
PCL Visualization

### ISSUE THREAD

**Issue by ChaimDryzun1980** [microsoft/vcpkg#15829]
****

I  tried to install PCL (point cloud library) with the x64-windows triplet (including the core, opengl, openni, qt, and vtk options). The installation was successful, but it seems it does not include the visualization files (include, lib and dlls).

Can the relevant visualization files be added to the pcl installation?

**Is your feature request related to a problem? Please describe.**

**Proposed solution**

**Describe alternatives you've considered**

**Additional context**

**Comment by JackBoosY** [comment]
Duplicated to #15130.
