### ISSUE TITLE
[New Port Request] tvision

### ISSUE THREAD

**Issue by ViniDalvino** [microsoft/vcpkg#15839]
Library name:
turbo vision
Library description:
A modern port of Turbo Vision 2.0, the classical framework for text-based user interfaces. Now cross-platform and with Unicode support.
Source repository URL:
https://github.com/magiblot/tvision
Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included): Idk if it is possible but it would be cool tosupport dos

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by NancyLi1013** [comment]
Hi @ViniDalvino
 
`tvision`  has been added to vcpkg now, please update to the latest vcpkg to use it.
