### ISSUE TITLE
Impossible to install successfully new ports after a custom port has been installed strikes back

### ISSUE THREAD

**Issue by traversaro** [microsoft/vcpkg#15836]
**Describe the bug**
With the current `master` branch since the PR has been merged https://github.com/microsoft/vcpkg/pull/15709 the use of custom ports at some point prevents to install any further non-custom port from vcpkg.

**Environment**
- OS: Windows
- Compiler: VS2019

**To Reproduce**
~~~
git clone https://github.com/microsoft/vcpkg  C:/vcpkg
git clone https://github.com/robotology/robotology-vcpkg-binary-ports C:/robotology-vcpkg-binary-ports
C:/vcpkg/bootstrap-vcpkg.sh
C:/vcpkg/vcpkg.exe --overlay-ports=C:/robotology-vcpkg-binary-ports install --triplet x64-windows ipopt-binary
C:/vcpkg/vcpkg.exe  install --triplet x64-windows asio
~~~
The last command will fail with the following error:
~~~
Computing installation plan...
Error: while loading  ipopt-binary:
The port directory (C:\vcpkg\ports\ipopt-binary) does not exist
Error: failed to load port from C:\vcpkg\ports\ipopt-binary
Note: Updating vcpkg by rerunning bootstrap-vcpkg may resolve this failure.
~~~

**Expected behavior**
The `asio` port should be installed correctly, even if the custom port `ipopt-binary` had been installed before. 

**Failure logs** 
See https://github.com/robotology/robotology-vcpkg-ports/issues/18 for more details and the bisection that lead to identify the PR https://github.com/microsoft/vcpkg/pull/15709 . This is a regression that re-created the already existing issue https://github.com/microsoft/vcpkg/issues/10119 .

**Comment by glindsey** [comment]
I am running into the same issue when attempting to update Boost. I'm getting the following error message:
`Error: while loading boost-disjoint-sets:
The port directory (D:\personal\projects\vcpkg\ports\boost-disjoint-sets) does not exist
Error: failed to load port from D:\personal\projects\vcpkg\ports\boost-disjoint-sets
Note: Updating vcpkg by rerunning bootstrap-vcpkg may resolve this failure.`

(Re-running `bootstrap-vcpkg` does not help.)

**Comment by JackBoosY** [comment]
@glindsey Although this is a vcpkg bug, I prefer you to use the manifest mode to avoid this temporary.

**Comment by wrobelda** [comment]
Personally, this is the biggest annoyance right now when working with vcpkg and actively developing ports while often switching branches.

**Comment by JackBoosY** [comment]
Requires next release.
