### ISSUE TITLE
How do I completely reinstall a package?

### ISSUE THREAD

**Issue by BullyWiiPlaza** [microsoft/vcpkg#15835]
I had a problem with `Boost` so I wanted to fully reinstall it. I tried `vcpkg remove Boost` but the process finished surpringly fast and didn't delete the leftover files. After running `vcpkg install Boost` it again finished very quickly. How do I fully remove `Boost` and perform a clean reinstall (this approximately takes 2 hours)? If there is no command for it such as `vcpkg reinstall`, how can I properly clean a package from the `vcpkg` folder manually so I can perform a true clean reinstall via `vcpkg install`?

**Comment by StarGate-One** [comment]
Have you tried `vcpkg remove boost-uninstall`?
You may also have to remove all the files in the vcpkg archives directory to remove any cached binaries - varies depends on OS vcpkg is installed on.
Reference: https://github.com/microsoft/vcpkg/blob/master/docs/users/binarycaching.md#configuration.

**Comment by BullyWiiPlaza** [comment]
@StarGate-One Thanks a lot, `vcpkg remove boost-uninstall:x64-windows --recurse` did the trick (since I'm on Windows).
