### ISSUE TITLE
[libjpeg-turbo] Linking fails on Windows w/ VS and CMake

### ISSUE THREAD

**Issue by BTOdell** [microsoft/vcpkg#15830]
**Describe the bug**
Code is not linking after following installation instructions for `libjpeg-turbo`.

**Environment**
- OS: Windows 10 x64
- Compiler: MSVC (VS2019)
- Visual Studio 2019 using CMake with vcpkg as a submodule

**To Reproduce**
1. Install library:
```powershell
PS> ./vcpkg.exe install libjpeg-turbo:x64-windows
```
2. Add recommended configuration to CMakeLists.txt:
```cmake
find_package(JPEG REQUIRED)
target_include_directories(main PRIVATE ${JPEG_INCLUDE_DIR})
target_link_libraries(main PRIVATE ${JPEG_LIBRARIES})
```
3. Include the library in your code:
```c++
#include <turbojpeg.h>
```
4. Use the library:
```c++
int main() {
    tjhandle handle = tjInitCompress();
    tjDestroy(handle);
    return 0;
}
```
5. Compile code and see error:
```
error LNK2019: unresolved external symbol tjInitCompress referenced in function main
error LNK2019: unresolved external symbol tjDestroy referenced in function main
```
6. Add cmake print statements to debug link libraries:
```cmake
message("JPEG_INCLUDE_DIR: ${JPEG_INCLUDE_DIR}")
message("JPEG_LIBRARIES: ${JPEG_LIBRARIES}")
```
7. Observe output:
```
...
[CMake] -- Found JPEG: optimized;D:/Programming/LinuxTestProject/vcpkg/installed/x64-windows/lib/jpeg.lib;debug;D:/Programming/LinuxTestProject/vcpkg/installed/x64-windows/debug/lib/jpegd.lib (found version "62") 
[CMake] JPEG_INCLUDE_DIR: D:/Programming/LinuxTestProject/vcpkg/installed/x64-windows/include
[CMake] JPEG_LIBRARIES: optimized;D:/Programming/LinuxTestProject/vcpkg/installed/x64-windows/lib/jpeg.lib;debug;D:/Programming/LinuxTestProject/vcpkg/installed/x64-windows/debug/lib/jpegd.lib
...
```

~~It seems that the `JPEG_LIBRARIES` variable is getting corrupted. There should be spaces or semicolons between the `optimized` and `debug` tokens and the file paths. I took a look at the FindJPEG.cmake file that defines this variable, but I couldn't identify the problem - I'm a novice when it comes to cmake.~~

Seems like the `turbojpeg.lib` file is just not getting included in the `${JPEG_LIBRARIES}` variable. I followed the usage instructions provided here: https://github.com/microsoft/vcpkg/blob/master/ports/libjpeg-turbo/usage
Maybe I'm misunderstanding what these instructions do...

**Expected behavior**
Code should link without error.

**Failure logs** 
- Please see error logs above.

**Additional context**
N/A

**Comment by Neumann-A** [comment]
Nothing corrupted you just neef to put the variable inside the " to print it correctly. Try using the target JPEG::JPEG instead of the old vars

**Comment by Neumann-A** [comment]
To further add to this:
I don't think that `tjInitCompress` and `tjDestroy` are jpeg symbols but turbo-jpeg symbols. jpeg symbols are prefixed with `jpeg_` . So you probably need to link turbo-jpeg instead of JPEG or use the actual jpeg equivalents.

**Comment by BTOdell** [comment]
Yes, I am trying to use turbojpeg functions. I simply followed the cmake usage instructions as I have done for other packages, but for this package it's not working out of the box: https://github.com/microsoft/vcpkg/blob/master/ports/libjpeg-turbo/usage

Maybe I have misinterpreted what these usage instructions do. It says "compatible with built-in CMake targets". I assumed this meant that the package can be configured with cmake. I'm not familiar with cmake vocabulary, so maybe this is actually saying something different.

It seems the `${JPEG_LIBRARIES}` variable only includes `jpeg.lib` and not `turbojpeg.lib` (which is in the same directory).

**Comment by JackBoosY** [comment]
Confirmed.

**Comment by Neumann-A** [comment]
@JackBoosY:

Yeah but that is not a vcpkg bug. There are no exported targets for turbo-jpeg so the user has to create a `FindTurboJPEG.cmake` on their own using `find_library` and stuff. JPEG::JPEG is only the general JPEG interface shared across different jpeg implementations.

**Comment by JackBoosY** [comment]
@Neumann-A Yes, but if it is clear that you need to find additional libraries, this issue should be a compiler error rather than a link error. This issue is caused by the library pointed to by `JPEG::JPEG` that depends on turbo-jpeg.
So we should add a wrapper to handle this.

**Comment by Neumann-A** [comment]
> JPEG::JPEG that depends on turbo-jpeg.
@JackBoosY no it is not. The user here is directly using turbo-jpeg symbols and not jpeg symbols.

**Comment by JackBoosY** [comment]
@Neumann-A Does `turbo-jpeg` have same symbols with `openjpeg` so this caused the wrong library to be used?

**Comment by Neumann-A** [comment]
@JackBoosY No. turbo-jpeg installs two libraries. One is called `jpeg.lib` whit `jpeg_` prefixed symbols which are the general used JPEG symbols which are need for ports using FindJPEG. The user here is explicitly using `tj_` prefixed symbols which are unique to turbo-jpeg and the second installed library `libturbo-jpeg.lib`. As such the user needs to define a `FindTurboJPEG` to find the required libraries. OpenJPEG exports symbols prefixed with `opj_`. I don't know if the port can be setup to also export a general jpeg lib with `jpeg_` prefixed symbols but I don't thing the version in vcpkg is setup to provide those for openjpeg if it is even possible.

**Comment by sfhacker** [comment]
Are we mixing two (or three) different ports at the same time?
Just tried the code snippet provided by the user and no issues at all.

![image](https://user-images.githubusercontent.com/25817529/105713363-2a436300-5f6f-11eb-8c2f-b232a2658f53.png)

**Comment by BTOdell** [comment]
https://libjpeg-turbo.org/About/TurboJPEG
I can understand if this package wasn't meant to expose the "TurboJPEG" API. Although it exposing the header file for TurboJPEG, `turbojpeg.h`, so I would assume it would link against it.

**Comment by sfhacker** [comment]
@BTOdell To be honest, we do not understand what your issue is!
You could try the same thing (e.g. linking) without using vcpkg. If that works fine, then try again with vcpkg.
Post screenshots here of all your attempts. We will guide you.

**Comment by BTOdell** [comment]
The issue is that the `libjpeg-turbo` package does not export the `turbojpeg.lib` as a link target.
In my CMakeLists.txt:
```cmake
project("server")

# Specify dependencies
find_package(JPEG REQUIRED)

file(GLOB_RECURSE SRC ${CMAKE_CURRENT_SOURCE_DIR}/*.cpp)
add_executable (server ${SRC})

message("JPEG_INCLUDE_DIR: ${JPEG_INCLUDE_DIR}")
message("JPEG_LIBRARIES: ${JPEG_LIBRARIES}")

target_include_directories(server PRIVATE ${JPEG_INCLUDE_DIR})
target_link_libraries(server PRIVATE ${JPEG_LIBRARIES})
#target_link_libraries(server PRIVATE optimized;${CMAKE_SOURCE_DIR}/build/x64-Debug/vcpkg_installed/x64-windows/lib/turbojpeg.lib;debug;${CMAKE_SOURCE_DIR}/build/x64-Debug/vcpkg_installed/x64-windows/debug/lib/turbojpegd.lib)
```

The cmake output is:
```
...
1> [CMake] -- Found JPEG: optimized;D:/Programming/LinuxTestProject/build/x64-Debug/vcpkg_installed/x64-windows/lib/jpeg.lib;debug;D:/Programming/LinuxTestProject/build/x64-Debug/vcpkg_installed/x64-windows/debug/lib/jpegd.lib (found version "62") 
1> [CMake] JPEG_INCLUDE_DIR: D:/Programming/LinuxTestProject/build/x64-Debug/vcpkg_installed/x64-windows/include
1> [CMake] JPEG_LIBRARIES: optimized;D:/Programming/LinuxTestProject/build/x64-Debug/vcpkg_installed/x64-windows/lib/jpeg.lib;debug;D:/Programming/LinuxTestProject/build/x64-Debug/vcpkg_installed/x64-windows/debug/lib/jpegd.lib
...
```
and I get link errors when I build.

If I uncomment the last line of my CMakeLists.txt (which explicitly includes the `turbojpeg.lib` as a link target) then my code links and builds successfully.

I would expect the `libjpeg-turbo` package to automatically export `turbojpeg.lib` as a link target so consumers of the package don't have to manually link the library like I have done. The library will be installed differently on different platforms (e.g. Windows vs Linux).

**Comment by JackBoosY** [comment]
@Neumann-A Yes, you are right, but we should provide a way to find and use turbo-jpeg.

**Comment by Neumann-A** [comment]
@JackBoosY that is just the same as providing `unofficial` targets. Either get upstream to export targets/pc files or submit a module to CMake. For vcpkg there is nothing to do here except to introduce vcpkg specific fixes into downstream projects which is not the intention of vcpkg. Furthermore it looks like that version 2.0.7 will include the export of targets since the current master branch seems to install cmake targets. 
@BTOdell ignore sfhacker he is a known to be "not helpful" to say it nicely.

**Comment by BTOdell** [comment]
@Neumann-A Yes, it looks like the 2.0.9 release includes proper CMake targets: https://github.com/libjpeg-turbo/libjpeg-turbo/releases/tag/2.0.90 (see 10 in the changelist).
And there is already a draft PR for updating to that version: #15178
Is it just the failed Windows CI build that is preventing the PR from being accepted?

**Comment by JackBoosY** [comment]
@BTOdell  We will handle that.

**Comment by arsdever** [comment]
Hi guys. Any updates on this thread?

**Comment by Neumann-A** [comment]
> Hi guys. Any updates on this thread?

has been updated to 2.1.2 and exports config now. so just do `find_package(libjpeg-turbo)` and link target `libjpeg-turbo::turbojpeg-static` or `libjpeg-turbo::turbojpeg(-shared?)`. Probably needs logic to deal with that extra suffix.

**Comment by arsdever** [comment]
@Neumann-A After upgrading the package to version 2.1.2 everything works as expected. Huge thanks.
