### ISSUE TITLE
VS2019 include intellisense not seeing VCPKG packages.

### ISSUE THREAD

**Issue by maxkunes** [microsoft/vcpkg#15843]
**Describe the bug**
VS2019 intellisense, _or #include autocomplete_, is not seeing any VCPKG packages when writing a `#include` in a C++ file in a 2019 project. 
VS2019 will mark the line as an invalid include for a few seconds even if I manually type the path in, and then it is able to resolve it correctly. The project can also compile properly, so the compiler can see the package fine. This worked very recently on a different version of VS2019. My previous version was VS2019 community (unk version number).

**Environment**
- OS: Windows
- VS2019 Enterprise 16.8.4

**To Reproduce**
1. Install a vcpkg package. Happens to any package I install.
2. Begin typing a `#include "` and try to type a package name. Nothing will autocomplete for me. Even though for any other header file, autocomplete works fine.

**Expected behavior**
I expect that the packages should be properly put into the include path such that autocomplete can see them. This has worked in the past for me, but at least since I've upgraded to 2019 Enterprise 16.8.4, autocomplete for vcpkg packages has failed to work.

**Comment by JackBoosY** [comment]
Did you use command `./vcpkg integrate install` and `./vcpkg integrate project` first?

**Comment by maxkunes** [comment]
I've used integrate install. Does integrate project also need to be ran?

**Comment by JackBoosY** [comment]
@maxkunes Yes, please run that command then rerun your Visual Studio.

**Comment by maxkunes** [comment]
That command and following the instructions given in console did not help

**Comment by JackBoosY** [comment]
@maxkunes So I assume that this issue is still unresolved?

**Comment by maxkunes** [comment]
Yes. I'm still having the same issue.

**Comment by JackBoosY** [comment]
Normally, if vcpkg was integrated to Visual Studio succesfullly, you will see this option in the project property pages:
![image](https://user-images.githubusercontent.com/47264268/105804972-fd796500-5fdb-11eb-92d7-802f01a088b0.png)

Does this option exist?

**Comment by maxkunes** [comment]
Yes, it does.

**Comment by JackBoosY** [comment]
@maxkunes Can you describe it more accurately?

**Comment by maxkunes** [comment]
> @maxkunes Can you describe it more accurately?

here is my project settings for vcpkg and a gif of the issue. It is not autocompleting.

![image of project settings](https://i.imgur.com/zaj2g2y.png)

![gif of failed autocomplete](https://i.imgur.com/FsdOacK.gif)

Is the problem that I configure the triplet to explicitly `x64-windows-static`. I am doing this because changing the triplet to `x64-windows` and setting static to true causes my project not to find the dependencies. Something here is bugged, but considering the project compiles using the dependencies, the autocomplete issue seems like the actual issue.

**Comment by NancyLi1013** [comment]
Hi @maxkunes

Have you restarted Visual Studio 2019 after run` .\vcpkg integrate install` or` .\vcpkg integrate project`?

I can use the headers successfully with Visual Studio 2019 16.8.4 Enterprise version on my machine.

**Comment by maxkunes** [comment]
Yes, I have restarted VS2019 multiple times since running those commands.

**Comment by JackBoosY** [comment]
Maybe the other Visual Studio plugins you installed conflict with vcpkg

**Comment by maxkunes** [comment]
> Maybe the other Visual Studio plugins you installed conflict with vcpkg

I just did some researching and it seems visual assist has a known issue that is causing the includes not to work with vcpkg.

So it looks like I just have to wait till they push a fix, or add the path explicitly to the includes of the project.

**Comment by JackBoosY** [comment]
@maxkunes Glad you found the reason!

**Comment by NancyLi1013** [comment]
Closing this issue for now since there is no active thread.

Please feel free to reopen this if it is still a problem for you.

**Comment by LIHU577** [comment]
> **Describe the bug** VS2019 intellisense, _or #include autocomplete_, is not seeing any VCPKG packages when writing a `#include` in a C++ file in a 2019 project. VS2019 will mark the line as an invalid include for a few seconds even if I manually type the path in, and then it is able to resolve it correctly. The project can also compile properly, so the compiler can see the package fine. This worked very recently on a different version of VS2019. My previous version was VS2019 community (unk version number).
> 
> **Environment**
> 
> * OS: Windows
> * VS2019 Enterprise 16.8.4
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Install a vcpkg package. Happens to any package I install.
> 2. Begin typing a `#include "` and try to type a package name. Nothing will autocomplete for me. Even though for any other header file, autocomplete works fine.
> 
> **Expected behavior** I expect that the packages should be properly put into the include path such that autocomplete can see them. This has worked in the past for me, but at least since I've upgraded to 2019 Enterprise 16.8.4, autocomplete for vcpkg packages has failed to work.

So，we cann't use VA and vcpkg at same time，emmmmmm,     it’s not a good meesage......

**Comment by JackBoosY** [comment]
@LIHU577 Yeah... as I said in zhihu, we have not and cannot test the conflict between unofficial Visual Studio plugins (such as Intel plugins) and vcpkg.
Please also report this issue to Visual Assistant.

Thanks.
