### ISSUE TITLE
[New Port Request] ApprovalTests.cpp

### ISSUE THREAD

**Issue by claremacrae** [microsoft/vcpkg#15847]
Library name: ApprovalTests.cpp

Library description: Approval Tests allow you to verify a chunk of output (such as a file) in one operation as opposed to writing test assertions for each element.

Source repository URL: https://github.com/approvals/ApprovalTests.cpp

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

* It's released as a single-header-only file
* Dependency on unit test frameworks
  * ApprovalTests.cpp is effectively a convenience layer on top of other unit test frameworks.
  * As of January 2021, the supported test frameworks are [GoogleTest](https://github.com/google/googletest), [Catch2](https://github.com/catchorg/Catch2), [CppUTest](http://cpputest.github.io/), [doctest](https://github.com/onqtam/doctest), [Boost.Test](https://www.boost.org/doc/libs/1_72_0/libs/test/doc/html/index.html), [\[Boost\].UT](https://github.com/boost-experimental/ut)
  * So I presume that somehow the vcpkg port will need to give users a way to specify which one of those libraries to add a dependency on
  * See [the option names used for that in Conan](https://github.com/conan-io/conan-center-index/blob/83f47fb28ed53fcbfcbb6cf8441a3f0c83efb627/recipes/approvaltests.cpp/all/conanfile.py#L16-L26)

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
