### ISSUE TITLE
[New Port Request] SDL mixer 1.2

### ISSUE THREAD

**Issue by bjaraujo** [microsoft/vcpkg#15849]
Library name:
SDL mixer

Library description:
SDL mixer 1.2

Source repository URL:
https://www.libsdl.org/projects/SDL_mixer/release-1.2.html

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
@bjaraujo, we already have port https://github.com/microsoft/vcpkg/tree/master/ports/sdl2-mixer with revision 2.0.4.

**Comment by bjaraujo** [comment]
@PhoebeHui  That is SDL mixer 2 not SDL mixer 1. Some project use SDL1 not SDL2.

**Comment by PhoebeHui** [comment]
@bjaraujo, does the port sdl2 match your requirements?

**Comment by bjaraujo** [comment]
No SDL2 is not backwards compatible with SDL1 that's why the package would be useful. I believe you have a SDL1 package but not a SDL1_mixer package.

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
