### ISSUE TITLE
[New Port Request] Intel(r) SPMD Program Compiler

### ISSUE THREAD

**Issue by xarthurx** [microsoft/vcpkg#15846]
Library name:
Intel(r) SPMD Program Compiler

Library description:
ispc is a compiler for a variant of the C programming language, with extensions for single program, multiple data programming. Under the SPMD model, the programmer writes a program that generally appears to be a regular serial program, though the execution model is actually that a number of program instances execute in parallel on the hardware.

Source repository URL:
https://github.com/ispc/ispc/

Project homepage (if different from the source repository):
https://ispc.github.io

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
https://github.com/microsoft/vcpkg/issues/8698

I submit it before, but don't know why it was closed.

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now. We can only reopen this issue if there has a PR for it.
