### ISSUE TITLE
[nvcodec] build failure

### ISSUE THREAD

**Issue by Eahom** [microsoft/vcpkg#15858]
**Host Environment**
- OS: Windows
- Compiler: MS VS 2019

**To Reproduce**
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: ffmpeg:x64-uwp
  Vcpkg version: 2020.11.12--0c94afc7883faee9f188c36232d628ffa94cf27f

`./vcpkg install  ffmpeg[openssl,x264,nvcodec] --triplet=x64-uwp`

**Failure logs** 
=== CONFIGURING ===
ERROR: cuda requested, but not all dependencies are satisfied: ffnvcodec

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.

**Comment by JackBoosY** [comment]
Since ffmpeg has been updated just now, can you please update your vcpkg and rebuild it?

Thanks.

**Comment by HppZ** [comment]
PS C:\Users\haopeng\Documents\haopeng\opensource\vcpkg2\vcpkg> .\vcpkg.exe install ffmpeg[nvcodec] --triplet=x64-uwp
Computing installation plan...
The following packages will be built and installed:
    ffmpeg[avcodec,avdevice,avfilter,avformat,avresample,core,gpl,nvcodec,postproc,swresample,swscale]:x64-uwp -> 4.3.1#10
Starting package 1/1: ffmpeg:x64-uwp
Building package ffmpeg[avcodec,avdevice,avfilter,avformat,avresample,core,gpl,nvcodec,postproc,swresample,swscale]:x64-uwp...
-- Using cached C:/Users/haopeng/Documents/haopeng/opensource/vcpkg2/vcpkg/downloads/ffmpeg-ffmpeg-n4.3.1.tar.gz
-- Cleaning sources at C:/Users/haopeng/Documents/haopeng/opensource/vcpkg2/vcpkg/buildtrees/ffmpeg/src/n4.3.1-3a99257db6.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/haopeng/Documents/haopeng/opensource/vcpkg2/vcpkg/downloads/ffmpeg-ffmpeg-n4.3.1.tar.gz
-- Applying patch 0001-create-lib-libraries.patch
-- Applying patch 0003-fix-windowsinclude.patch
-- Applying patch 0004-fix-debug-build.patch
-- Applying patch 0005-fix-libvpx-linking.patch
-- Applying patch 0006-fix-StaticFeatures.patch
-- Applying patch 0007-fix-lib-naming.patch
-- Applying patch 0008-Fix-wavpack-detection.patch
-- Applying patch 0009-Fix-fdk-detection.patch
-- Applying patch 0010-Fix-x264-detection.patch
-- Applying patch 0011-Fix-x265-detection.patch
-- Applying patch 0012-Fix-ssl-110-detection.patch
-- Applying patch 0013-define-WINVER.patch
-- Using source at C:/Users/haopeng/Documents/haopeng/opensource/vcpkg2/vcpkg/buildtrees/ffmpeg/src/n4.3.1-3a99257db6.clean
-- Using msys root at C:/Users/haopeng/Documents/haopeng/opensource/vcpkg2/vcpkg/downloads/tools/msys2/969c0913b9df89e1
-- Building Options: --toolchain=msvc --enable-asm --enable-x86asm --disable-doc --enable-debug --enable-runtime-cpudetect --enable-gpl --disable-ffmpeg --disable-ffplay --disable-ffprobe --enable-avcodec --enable-avdevice --enable-avformat --enable-avfilter --enable-postproc --enable-swresample --enable-swscale --enable-avresample --disable-avisynth --disable-bzlib --disable-iconv --disable-libfdk-aac --disable-lzma --disable-libmp3lame --enable-cuda --enable-nvenc --enable-nvdec --enable-cuvid --disable-opencl --disable-openssl --disable-libopus --disable-sdl2 --disable-libsnappy --disable-libsoxr --disable-libspeex --disable-libtheora --disable-libvorbis --disable-libvpx --disable-libwavpack --disable-libx264 --disable-libx265 --disable-zlib --disable-programs --extra-cflags=-DWINAPI_FAMILY=WINAPI_FAMILY_APP --extra-cflags=-D_WIN32_WINNT=0x0A00  --enable-cross-compile --target-os=win32 --arch=x64 --disable-static --enable-shared --extra-ldflags=-APPCONTAINER --extra-ldflags=WindowsApp.lib --extra-cflags=-DHAVE_UNISTD_H=0
-- Building Release Options:  --extra-cflags=-MD --extra-cxxflags=-MD
-- Building ffmpeg for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:108 (message):
    Command failed: C:/Users/haopeng/Documents/haopeng/opensource/vcpkg2/vcpkg/downloads/tools/msys2/969c0913b9df89e1/usr/bin/bash.exe ./build.sh
    Working Directory: C:/Users/haopeng/Documents/haopeng/opensource/vcpkg2/vcpkg/buildtrees/ffmpeg/x64-uwp-rel
    Error code: 1
    See logs for more information:
      C:\Users\haopeng\Documents\haopeng\opensource\vcpkg2\vcpkg\buildtrees\ffmpeg\build-x64-uwp-rel-out.log

Call Stack (most recent call first):
  ports/ffmpeg/portfile.cmake:432 (vcpkg_execute_required_process)
  scripts/ports.cmake:128 (include)


Error: Building package ffmpeg:x64-uwp failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: ffmpeg:x64-uwp
  Vcpkg version: 2021-01-13-768d8f95c9e752603d2c5901c7a7c7fbdb08af35

Additionally, attach any relevant sections from the log files above.

**Comment by HppZ** [comment]
=== CONFIGURING ===
ERROR: cuda requested, but not all dependencies are satisfied: ffnvcodec

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.

**Comment by JackBoosY** [comment]
I think #15787 should fix this issue.

**Comment by HppZ** [comment]
waiting for fix.

**Comment by Sibras** [comment]
nvcodec cannot be used in uwp builds. ffnvcodec requires runtime dll loading using LoadLibrary which is not supported in uwp.

**Comment by HppZ** [comment]
how about using LoadPackagedLibrary?

**Comment by Sibras** [comment]
nvcodec loads a system library supplied by specific nvidia drivers on capable hardware and so the required dll is not distributed as part of the lib and so cant be added to a package. This is a limitation of uwp as only directx11 hardware accelerated video is supported.

**Comment by HppZ** [comment]
got you.
thanks~

**Comment by JackBoosY** [comment]
Is this issue resolved?

**Comment by Eahom** [comment]
> Since ffmpeg has been updated just now, can you please update your vcpkg and rebuild it?
> 
> Thanks.

Update vcpkg and rebuild, the question also existed.

**Comment by Eahom** [comment]
> Is this issue resolved?

Update vcpkg and rebuild, the question also existed.

**Comment by PhoebeHui** [comment]
nvcodec doesn't support uwp, openssl and x264 passed with lastest source, please get latest source and try  './vcpkg install ffmpeg[openssl,x264] --triplet=x64-uwp' again.
