### ISSUE TITLE
Package: boost-compatibility:x64-windows

### ISSUE THREAD

**Issue by 814734522** [microsoft/vcpkg#15854]
**Describe the bug**

**Environment**
- OS: Windows
- Compiler: 10th

**To Reproduce**
1. ./vcpkg install pcl
2. See error
Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.74.0/LICENSE_1_0.txt... Failed. Status: 7;"Couldn't connect to server"
Error: Building package boost-compatibility:x64-windows failed with: BUILD_FAILED
Package: boost-compatibility:x64-windows
 Vcpkg version: 2021-01-13-unknownhash

**Expected behavior**

**Failure logs** 
 Status: 7;"Couldn't connect to server"

**Additional context**

**Comment by PhoebeHui** [comment]
@814734522, could you try the solution provided in issue https://github.com/microsoft/vcpkg/issues/13348?

**Comment by PhoebeHui** [comment]
@814734522, please reopen this issue if the solution doesn't work for you.
