### ISSUE TITLE
[New Port Request] SMLite

### ISSUE THREAD

**Issue by fawdlstty** [microsoft/vcpkg#15864]
Library name: SMLite

Library description: State machine library for C++ & C#

Source repository URL: <https://github.com/fawdlstty/SMLite>

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
