### ISSUE TITLE
[libmagic] build failure

### ISSUE THREAD

**Issue by yxw1993** [microsoft/vcpkg#15865]
**Host Environment**
- OS: [win10]
- Compiler: vs2019-x86

**To Reproduce**
`./vcpkg install libmagic`

**Failure logs** 
Computing installation plan...
The following packages will be built and installed:
    libmagic[core]:x86-windows -> 5.37#2
Detecting compiler hash for triplet x86-windows...
Could not locate cached archive: C:\Users\Y\AppData\Local\vcpkg\archives\65\659383d69a3994c159f909e69bd190a658caf2dc.zip
Starting package 1/1: libmagic:x86-windows
Building package libmagic[core]:x86-windows...
-- Downloading https://github.com/file/file/archive/a0d5b0e4e9f97d74a9911e95cedd579852e25398.tar.gz -> file-file-a0d5b0e4e9f97d74a9911e95cedd579852e25398.tar.gz...
-- Cleaning sources at C:/tools/vcpkg/buildtrees/libmagic/src/9852e25398-4363addce8.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/tools/vcpkg/downloads/file-file-a0d5b0e4e9f97d74a9911e95cedd579852e25398.tar.gz
-- Using source at C:/tools/vcpkg/buildtrees/libmagic/src/9852e25398-4363addce8.clean
-- Configuring x86-windows
-- Using msys root at C:/tools/vcpkg/downloads/tools/msys2/9c897ff883069dc3
-- Using msys root at C:/tools/vcpkg/downloads/tools/msys2/50864d9fae363d6e
-- Generating configure for x86-windows
-- Finished generating configure for x86-windows
-- Configuring x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:108 (message):
    Command failed: C:/tools/vcpkg/downloads/tools/msys2/9c897ff883069dc3/usr/bin/bash.exe --noprofile --norc --debug -c "V=1 CPP='compile cl.exe -E' CC='compile cl.exe' CC_FOR_BUILD='compile cl.exe' CXX='compile cl.exe' RC='windres-rc rc.exe' WINDRES='windres-rc rc.exe' AR='ar-lib lib.exe' LD='link.exe -verbose' RANLIB=':' STRIP=':' NM='dumpbin.exe -symbols -headers' DLLTOOL='link.exe -verbose -dll' CCAS=':' AS=':' ./../src/9852e25398-4363addce8.clean/configure --build=x86_64-pc-mingw32 --host=i686-pc-mingw32 ac_cv_prog_ac_ct_STRIP=: gl_cv_double_slash_root=yes ac_cv_func_memmove=yes --disable-silent-rules --verbose --enable-shared --disable-static --prefix=/C/tools/vcpkg/installed/x86-windows/debug --bindir='${prefix}'/../tools/libmagic/debug/bin --sbindir='${prefix}'/../tools/libmagic/debug/sbin --includedir='${prefix}'/../include --datarootdir='${prefix}'/share/libmagic"
    Working Directory: C:/tools/vcpkg/buildtrees/libmagic/x86-windows-dbg
    Error code: 1
    See logs for more information:
      C:\tools\vcpkg\buildtrees\libmagic\config-x86-windows-dbg-out.log
      C:\tools\vcpkg\buildtrees\libmagic\config-x86-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:684 (vcpkg_execute_required_process)
  ports/libmagic/portfile.cmake:9 (vcpkg_configure_make)
  scripts/ports.cmake:128 (include)

Error: Building package libmagic:x86-windows failed with: BUILD_FAILED
Elapsed time for package libmagic:x86-windows: 2.181 min

Total elapsed time: 2.263 min

RESULTS
    libmagic:x86-windows: BUILD_FAILED: 2.181 min

SUMMARY
    SUCCEEDED: 0
    BUILD_FAILED: 1
    POST_BUILD_CHECKS_FAILED: 0
    FILE_CONFLICTS: 0
    CASCADED_DUE_TO_MISSING_DEPENDENCIES: 0
    EXCLUDED: 0

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

[config-x86-windows-dbg-err.log]
[config-x86-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/5867273/config-x86-windows-dbg-err.log)

configure: WARNING: using cross tools not prefixed with host triplet
./../src/9852e25398-4363addce8.clean/configure: line 12998: gl_VISIBILITY: command not found
configure: error: libgnurx is required to build file(1) with MinGW

**Comment by NancyLi1013** [comment]
Hi @yxw1993

Thanks for posting this issue. It's duplicated to #11832. Let's track this issue there.

**Comment by sfhacker** [comment]
Are we STILL having issues with libmagic project?
The referenced issue is over six months old!
