### ISSUE TITLE
[aws-sdk-cpp] Undefined reference to Aws::Utils::EnumParseOverflowContainer::StoreOverflow

### ISSUE THREAD

**Issue by ludekvodicka** [microsoft/vcpkg#15863]
**Describe the bug**
undefined reference to `Aws::Utils::EnumParseOverflowContainer::StoreOverflow`

I'm not sure if it's necessary to install anything else, but I'm not able to link my app when only `aws-sdk-cpp[email]`.

Missing `Aws::Utils::EnumParseOverflowContainer::StoreOverflow` should be implemented in Aws::Utils namespace https://sdk.amazonaws.com/cpp/api/LATEST/namespace_aws_1_1_utils.html but I didn't find any `utils` feature/port.

Order of the libraries should be ok (please see bellow, sdk-email is linked as last and all libs compiled by to port are included).

Thanks for any hint.

**Environment**
- OS: Ubuntu 18.04
- Compiler: gcc 7.5.0

**To Reproduce**
1. ./vcpkg install aws-sdk-cpp[email] 

link library order:
`/home/dev/dev/SharedLibraries/vcpkg/lib_debug/libaws-c-common.a /home/dev/dev/SharedLibraries/vcpkg/lib_debug/libaws-c-event-stream.a /home/dev/dev/SharedLibraries/vcpkg/lib_debug/libaws-checksums.a /home/dev/dev/SharedLibraries/vcpkg/lib_debug/libaws-cpp-sdk-core.a /home/dev/dev/SharedLibraries/vcpkg/lib_debug/libaws-cpp-sdk-dynamodb.a /home/dev/dev/SharedLibraries/vcpkg/lib_debug/libaws-cpp-sdk-kinesis.a /home/dev/dev/SharedLibraries/vcpkg/lib_debug/libaws-cpp-sdk-s3.a /home/dev/dev/SharedLibraries/vcpkg/lib_debug/libaws-cpp-sdk-email.a`

2. See an error

```
/home/dev/dev/SharedLibraries/vcpkg/lib_debug/libaws-cpp-sdk-email.a(ub_EMAIL.cpp.o): In function `Aws::SES::Model::BehaviorOnMXFailureMapper::GetBehaviorOnMXFailureForName(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/dev/dev/ExternalLibraries/vcpkg/buildtrees/aws-sdk-cpp/src/1c85d0a8c9-fb0dd46991.clean/aws-cpp-sdk-email/source/model/BehaviorOnMXFailure.cpp:41: undefined reference to `Aws::Utils::EnumParseOverflowContainer::StoreOverflow(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/home/dev/dev/SharedLibraries/vcpkg/lib_debug/libaws-cpp-sdk-email.a(ub_EMAIL.cpp.o): In function `Aws::SES::Model::BehaviorOnMXFailureMapper::GetNameForBehaviorOnMXFailure[abi:cxx11](Aws::SES::Model::BehaviorOnMXFailure)':
/home/dev/dev/ExternalLibraries/vcpkg/buildtrees/aws-sdk-cpp/src/1c85d0a8c9-fb0dd46991.clean/aws-cpp-sdk-email/source/model/BehaviorOnMXFailure.cpp:60: undefined reference to `Aws::Utils::EnumParseOverflowContainer::RetrieveOverflow[abi:cxx11](int) const'
/home/dev/dev/SharedLibraries/vcpkg/lib_debug/libaws-cpp-sdk-email.a(ub_EMAIL.cpp.o): In function `Aws::SES::Model::BounceTypeMapper::GetBounceTypeForName(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/dev/dev/ExternalLibraries/vcpkg/buildtrees/aws-sdk-cpp/src/1c85d0a8c9-fb0dd46991.clean/aws-cpp-sdk-email/source/model/BounceType.cpp:61: undefined reference to `Aws::Utils::EnumParseOverflowContainer::StoreOverflow(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/home/dev/dev/SharedLibraries/vcpkg/lib_debug/libaws-cpp-sdk-email.a(ub_EMAIL.cpp.o): In function `Aws::SES::Model::BounceTypeMapper::GetNameForBounceType[abi:cxx11](Aws::SES::Model::BounceType)':
/home/dev/dev/ExternalLibraries/vcpkg/buildtrees/aws-sdk-cpp/src/1c85d0a8c9-fb0dd46991.clean/aws-cpp-sdk-email/source/model/BounceType.cpp:88: undefined reference to `Aws::Utils::EnumParseOverflowContainer::RetrieveOverflow[abi:cxx11](int) const'
/home/dev/dev/SharedLibraries/vcpkg/lib_debug/libaws-cpp-sdk-email.a(ub_EMAIL.cpp.o): In function `Aws::SES::Model::BulkEmailStatusMapper::GetBulkEmailStatusForName(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/dev/dev/ExternalLibraries/vcpkg/buildtrees/aws-sdk-cpp/src/1c85d0a8c9-fb0dd46991.clean/aws-cpp-sdk-email/source/model/BulkEmailStatus.cpp:101: undefined reference to `Aws::Utils::EnumParseOverflowContainer::StoreOverflow(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
...
```

**Comment by ludekvodicka** [comment]
Hmm, strange.

I tried to place libaws-cpp-email.a as first dependency and now it's working.  I always thought that dependencies should be ordered from the left to right. 

`
/home/dev/dev/SharedLibraries/vcpkg/lib_debug/libaws-cpp-sdk-email.a /home/dev/dev/SharedLibraries/vcpkg/lib_debug/libaws-c-common.a /home/dev/dev/SharedLibraries/vcpkg/lib_debug/libaws-c-event-stream.a /home/dev/dev/SharedLibraries/vcpkg/lib_debug/libaws-checksums.a /home/dev/dev/SharedLibraries/vcpkg/lib_debug/libaws-cpp-sdk-core.a`

So it's probably solved now.

**Comment by sfhacker** [comment]
You have raised numerous issues lately!
There are many online tutorials you can read. Then you try simple test cases.

**Comment by ludekvodicka** [comment]
So? I raised numerous issues and also committed a lot of fixes for these issues. Feel free to check my PRs.

Also, I already closed this issue and posted info for anyone other who will have this issue.

So, I see your comment as completely useless and rude.
