### ISSUE TITLE
tesseract:arm-ios build failure

### ISSUE THREAD

**Issue by csatacsirke** [microsoft/vcpkg#15866]
**Host Environment**
- OS: MacOS
- Compiler: llvm - xcode command line tools
- Target: cross compile to ios arm or arm64

**To Reproduce**
`./vcpkg install tesseract:arm-ios` or `./vcpkg install tesseract:arm64-ios` 

**Failure logs** 
```
  Package: tesseract:arm-ios
  Vcpkg version: 2020.06.15-unknownhash

From the error log:
CMake Error at CMakeLists.txt:540 (install):
  install TARGETS given no BUNDLE DESTINATION for MACOSX_BUNDLE executable
  target "tesseract".

```

**Additional context**
When i tried compiling without vcpkg, in cmake i needed this parameter: 
CMAKE_MACOSX_BUNDLE:UNINITIALIZED=FALSE

**Comment by Cheney-W** [comment]
This issue has not been updated for over 3 months, so if it is still an issue, please reopen the issue.
