### ISSUE TITLE
cannot install armadillo

### ISSUE THREAD

**Issue by GopherJ** [microsoft/vcpkg#15870]
**Describe the bug**
```
vcpkg install armadillo
```
throws out this:

![image](https://user-images.githubusercontent.com/33961674/105749008-239ef680-5f43-11eb-9006-55ff06e60fbe.png)

**Environment**
- OS: `Linux mint v20`
- Compiler: `gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0`

**To Reproduce**
1. ./vcpkg install armadillo
2. See error
Repro code when

**Expected behavior**

**Failure logs** 
-(please attached failure logs)

**Additional context**

**Comment by JonLiu1993** [comment]
@GopherJ ,Thanks for posting this issue,you've set the HTTPS_PROXY? I believe that armadillo  will use the HTTP_PROXY and HTTPS_PROXY environment variable when downloading an https:// link like the one above. Just set them in you console.you can use command to set it. Example:

set http_proxy=http://localhost:1080
set http_proxy_user=user
set http_proxy_pass=pwd

If the above method does not work，Please download the source package manually and put it into VCPKG_PATH/downloads and rebuild armadillo .

**Comment by GopherJ** [comment]
@JonLiu1993 Hi, I didn't set any proxy, do I need to have one?

**Comment by JonLiu1993** [comment]
@GopherJ ，Yes, you can reinstall after setting up the proxy

**Comment by vd** [comment]
The repo has reached its download rate from gitlab so it is (propably) not related to your proxy settings @GopherJ.
You get following response code when the zip/tar download link is requested:
> This archive has been requested too many times. Try again later.

**Comment by GopherJ** [comment]
actually I also had this issue with other packages.  I'm wondering if vcpkg can automatically re-run download some time later because I ran vcpkg in container and I really need it to succeed for most of the time to be able to produce the same results

**Comment by JackBoosY** [comment]
This issue was fixed by #15973.
