### ISSUE TITLE
[harfbuzz] x64-windows build failure with features glib or graphite2

### ISSUE THREAD

**Issue by StarGate-One** [microsoft/vcpkg#15877]
**Host Environment**
- OS: [Microsoft Windows [Version 10.0.19042.782]]
- Compiler: 
   - Visual Studio 2017 Version: 15.9.31  VS Tools Version: 14.16.27023 
     Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29336 for x64
   - Visual Studio 2019 Version: 16.8.4  VS Tools Version: 14.28.29333
     Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27045 for x64
- After commit of PR **[harfbuzz] Use meson and update to 2.7.0** https://github.com/microsoft/vcpkg/pull/12860
/cc: @vejmartin @PhoebeHui @LilyWangL @JackBoosY @Neumann-A @BillyONeal 

**To Reproduce**
`cd [vcpkg-root]`
`git pull` as of 2021/01/25 16:15:44 EST GMT -5:00
`.\bootstrap-vcpkg.bat -win64 -verbose -disableMetrics -withVSPath "'C:\Program Files (x86)\Microsoft Visual Studio\[VS Version]\Community\'"`
`.\vcpkg.exe install  harfbuzz[core,glib,graphite2,icu]:x64-windows`
**Failure logs** 
- Cut and past the appropriate build messages from the console output.
>-Computing installation plan...
>The following packages will be built and installed:
>  * brotli[core]:x64-windows -> 1.0.9
>  * bzip2[core]:x64-windows -> 1.0.8#1
>  * freetype[brotli,bzip2,core,png,zlib]:x64-windows -> 2.10.4
>  * gettext[core]:x64-windows -> 0.21
>  * glib[core]:x64-windows -> 2.52.3#25
>  * graphite2[core]:x64-windows -> 1.3.14
>    harfbuzz[core,glib,graphite2,icu]:x64-windows -> 2.7.4
>  * icu[core]:x64-windows -> 67.1#7
>  * libffi[core]:x64-windows -> 3.3#6
>  * libiconv[core]:x64-windows -> 1.16#7
>  * libpng[core]:x64-windows -> 1.6.37#14
>  * pcre[core]:x64-windows -> 8.44#8
>  * zlib[core]:x64-windows -> 1.2.11#9
>Additional packages (*) will be modified to complete this operation.`
> ... ... ...
> Compiling Pre-Requisite Ports ~~~
> ... ... ...
>Starting package 13/13: harfbuzz:x64-windows
>Building package harfbuzz[core,glib,graphite2,icu]:x64-windows...
>-- Downloading https://github.com/harfbuzz/harfbuzz/archive/7236c7e29cef1c2d76c7a284c5081ff4d3aa1127.tar.gz -> harfbuzz-harfbuzz-7236c7e29cef1c2d76c7a284c5081ff4d3aa1127.tar.gz...
>-- Extracting source D:/Git/vcpkg/vcpkg_test/downloads/harfbuzz-harfbuzz-7236c7e29cef1c2d76c7a284c5081ff4d3aa1127.tar.gz
>-- Applying patch 0002-fix-uwp-build.patch
>-- Using source at D:/Git/vcpkg/vcpkg_test/buildtrees/harfbuzz/src/f4d3aa1127-a820a32874.clean
>-- Configuring x64-windows
>-- Downloading https://github.com/mesonbuild/meson/archive/f5871f434a5b768ad9fcafa797a6db0286421842.tar.gz -> meson-f5871f434a5b768ad9fcafa797a6db0286421842.tar.gz...
>-- Using msys root at D:/Git/vcpkg/vcpkg_test/downloads/tools/msys2/50864d9fae363d6e
>-- Configuring x64-windows-dbg
>-- Configuring x64-windows-dbg done
>-- Configuring x64-windows-rel
>-- Configuring x64-windows-rel done
>-- Package x64-windows-rel
>-- Package x64-windows-dbg
>-- Using msys root at D:/Git/vcpkg/vcpkg_test/downloads/tools/msys2/50864d9fae363d6e
>-- Fixing pkgconfig file: D:/Git/vcpkg/vcpkg_test/packages/harfbuzz_x64-windows/lib/pkgconfig/harfbuzz-icu.pc
>-- Fixing pkgconfig file: D:/Git/vcpkg/vcpkg_test/packages/harfbuzz_x64-windows/lib/pkgconfig/harfbuzz-subset.pc
>-- Fixing pkgconfig file: D:/Git/vcpkg/vcpkg_test/packages/harfbuzz_x64-windows/lib/pkgconfig/harfbuzz.pc
>-- Fixing pkgconfig file: D:/Git/vcpkg/vcpkg_test/packages/harfbuzz_x64-windows/debug/lib/pkgconfig/harfbuzz-icu.pc
>-- Fixing pkgconfig file: D:/Git/vcpkg/vcpkg_test/packages/harfbuzz_x64-windows/debug/lib/pkgconfig/harfbuzz-subset.pc
>-- Fixing pkgconfig file: D:/Git/vcpkg/vcpkg_test/packages/harfbuzz_x64-windows/debug/lib/pkgconfig/harfbuzz.pc
>-- Installing: D:/Git/vcpkg/vcpkg_test/packages/harfbuzz_x64-windows/share/harfbuzz/copyright
>-- Performing post-build validation

**The following EXEs were found in /bin or /debug/bin. EXEs are not valid distribution targets.**

**D:/Git/vcpkg/vcpkg_test/packages/harfbuzz_x64-windows/bin/hb-ot-shape-closure.exe**
**D:/Git/vcpkg/vcpkg_test/packages/harfbuzz_x64-windows/bin/hb-shape.exe**
**D:/Git/vcpkg/vcpkg_test/packages/harfbuzz_x64-windows/bin/hb-subset.exe**

**The following EXEs were found in /bin or /debug/bin. EXEs are not valid distribution targets.**

 **D:/Git/vcpkg/vcpkg_test/packages/harfbuzz_x64-windows/debug/bin/hb-ot-shape-closure.exe**
 **D:/Git/vcpkg/vcpkg_test/packages/harfbuzz_x64-windows/debug/bin/hb-shape.exe**
 **D:/Git/vcpkg/vcpkg_test/packages/harfbuzz_x64-windows/debug/bin/hb-subset.exe**

**Found 2 error(s). Please correct the portfile:**

>    D:\Git\vcpkg\vcpkg_test\ports\harfbuzz\portfile.cmake
>-- Performing post-build validation done
>Error: Building package harfbuzz:x64-windows failed with: POST_BUILD_CHECKS_FAILED
>Please ensure you're using the latest portfiles with `.\vcpkg update`, then
>submit an issue at https://github.com/Microsoft/vcpkg/issues including:
>  Package: harfbuzz:x64-windows
>  Vcpkg version: 2021-01-13-unknownhash
>
>Additionally, attach any relevant sections from the log files above.

- Please attach any additional failure logs mentioned in the console output.
None

**Additional context**
- CI Pipe was tested harfbuzz[core,icu] features only and passed
- Using either additional feature of **glib _and/or_ graphite2** results in build failure during post validation

**Comment by Neumann-A** [comment]
fixed in #13100

**Comment by StarGate-One** [comment]
Closing, no longer an issue for me as we have chosen to no longer use vcpkg.

**Comment by StarGate-One** [comment]
Closing, no longer an issue for me as we have chosen to no longer use vcpkg.

**Comment by PhoebeHui** [comment]
Reopen this issue for tracking the port bug.

**Comment by tan-wei** [comment]
Met the same issue.
