### ISSUE TITLE
installing a package that only has a port on another Git branch breaks installing every other package

### ISSUE THREAD

**Issue by Be-ing** [microsoft/vcpkg#15884]
**Describe the bug**
When I install a package that I added on one Git branch, then switch to a different branch that doesn't have a port for that new package, I cannot install any new packages.

**Environment**
- OS: Linux (Fedora 33)
- Compiler: gcc-10.2.1-9.fc33.x86_64

**To Reproduce**
1. Checkout Git branch that has a new port
2. ./vcpkg install new-port-name
3. Checkout another Git branch without the new port
4. ./vcpkg install any-other-port

**Expected behavior**
Installing new packages should work even if there is a package installed that does not have a port in the current branch.

**Failure logs** 
```
Computing installation plan...
Error: while loading libkeyfinder:
The port directory (/home/be/sw/vcpkg/ports/libkeyfinder) does not exist
Error: failed to load port from /home/be/sw/vcpkg/ports/libkeyfinder
Note: Updating vcpkg by rerunning bootstrap-vcpkg may resolve this failure.
```

**Additional context**
Rebootstrapping as the error suggests does not solve the issue.

This issue can be worked around by uninstalling the package that does not exist on the current Git branch.

**Comment by viromer** [comment]
Probably cause by the same issue in #15836

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/15836.
