### ISSUE TITLE
support offline network repository

### ISSUE THREAD

**Issue by idanbis-rnd** [microsoft/vcpkg#15888]
****

**Is your feature request related to a problem? Please describe.**
At work, we are working in an offline network, that does not have direct internet connection.  
I understand that one solution would be to install on other PC and copy locally via USB / etc.  
However I would love to see some feature that allows to install some own repository, possible on some enterprise github, or gitlab, etc.

**Proposed solution**
In same manner that nuget allows to configure some local PC repsoitories, allow to configure vcpkg to have some "local repository" that assuming we have it, it would fetch all dependencies from there.

**Describe alternatives you've considered**
Only alternative is as seen in some old closed issue, dated from 2018, that suggest performing this on other online PC and copy it via USB.

**Additional context**
n/a

**Comment by JackBoosY** [comment]
Yep, so we support `export` function, you can use that to export the installed packages.

**Comment by vicroms** [comment]
Hi @idanbis-rnd 
 
The main issue is that vcpkg needs to download form the Internet the source code of a library before building it. But there are few options you can try:
* A) Build in a computer with Internet access and export produced binaries.
* B) Download sources for all ports and copy them to your offline machines.
* C) Mirror all downloads required by vcpkg in an internal network.

Option A)
This method is the easier one, but it has some downsides. You need to have the same environment on all your computers (same triplet, compiler, and compiler versions for instance) and can be accomplished by using [binary caching](https://github.com/microsoft/vcpkg/blob/master/docs/users/binarycaching.md) with a file share in your internal network or with a Nuget feed.

If you don't have an internal network then you can use the [`vcpkg export` method](https://github.com/microsoft/vcpkg/blob/master/docs/users/integration.md#export-command).

Option B)
Use the existing `--only-downloads` on all the packages you need and then copy the sources that have been extracted to `buildtrees/`. The "benefit" of this method is that each machine will do their own build of the libraries (in the case that they have different environments). 

Option C)
This would require you to figure out how to mirror and redirect all downloads made by vcpkg to your internal network. We plan to support source redirection as a feature of vcpkg but it is not currently implemented and we don't have any set timeline for it.

Extra option)
Create custom ports for the libraries you need that point to local resources (see [overlay ports](https://github.com/microsoft/vcpkg/blob/master/docs/specifications/ports-overlay.md)).

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

**Comment by KUGA2** [comment]
Before downloading the packages, it will run always bootstrap.sh. There it downloads glibc. I found no way to stop this. I need to solve this before I can really try the options.
**How do I run bootstrap in an offline machine?**

Any news on implemting Option C?

**Comment by JackBoosY** [comment]
bootstrap.sh just downloaded the binaries, you can directly downloaded them from your custom network directory instead.

**Comment by KUGA2** [comment]
Ok. The message with glibc suggests it would build it, but if you read the code closely, it does not :) Thanks.

Any news on implemting Option C?
