### ISSUE TITLE
yasm-tool build failure

### ISSUE THREAD

**Issue by lovettchris** [microsoft/vcpkg#15880]
**Host Environment**
- OS: Windows
- Compiler: Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29333

**To Reproduce**
`./vcpkg install yasm-tool:x86-windows`

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

```
C:\git\vcpkg>vcpkg install yasm-tool:x86-windows
Computing installation plan...
The following packages will be built and installed:
    yasm-tool[core]:x86-windows -> 2020-10-12
Detecting compiler hash for triplet x86-windows...
Could not locate cached archive: C:\Users\lovet\AppData\Local\vcpkg\archives\8a\8a6e93e80d4e15fc541bc275e31b3872352ec784.zip
Starting package 1/1: yasm-tool:x86-windows
Building package yasm-tool[core]:x86-windows...
-- Using cached C:/git/vcpkg/downloads/yasm-yasm-009450c7ad4d425fa5a10ac4bd6efbd25248d823.tar.gz
-- Cleaning sources at C:/git/vcpkg/buildtrees/yasm-tool/src/d25248d823-818ed1bbf4.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/git/vcpkg/downloads/yasm-yasm-009450c7ad4d425fa5a10ac4bd6efbd25248d823.tar.gz
-- Using source at C:/git/vcpkg/buildtrees/yasm-tool/src/d25248d823-818ed1bbf4.clean
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:108 (message):
    Command failed: C:/Users/lovet/.dotnet/tools/pwsh.exe -noprofile -executionpolicy Bypass -nologo -file C:/git/vcpkg/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary C:/git/vcpkg/packages/yasm-tool_x86-windows/tools/yasm-tool/yasm.exe -installedDir C:/git/vcpkg/packages/yasm-tool_x86-windows/bin
    Working Directory: C:/git/vcpkg
    Error code: -532462766
    See logs for more information:
      C:\git\vcpkg\buildtrees\yasm-tool\copy-tool-dependencies-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_copy_tool_dependencies.cmake:31 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_copy_tool_dependencies.cmake:41 (search_for_dependencies)
  scripts/cmake/vcpkg_copy_tools.cmake:62 (vcpkg_copy_tool_dependencies)
  ports/yasm-tool/portfile.cmake:27 (vcpkg_copy_tools)
  scripts/ports.cmake:128 (include)


Error: Building package yasm-tool:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: yasm-tool:x86-windows
  Vcpkg version: 2021-01-13-unknownhash

Additionally, attach any relevant sections from the log files above.

```

[copy-tool-dependencies-err.log](https://github.com/microsoft/vcpkg/files/5870636/copy-tool-dependencies-err.log)

**Additional context**

I need this to build GMP which is needed to build GCAL which is needed to build colmap...

**Comment by JackBoosY** [comment]
`Unhandled exception. System.ComponentModel.Win32Exception (2): The system cannot find the file specified.`

Can you try to re-clone vcpkg in non-system disk and try again?

Thanks.

**Comment by lovettchris** [comment]
@JackBoosY , I tried my d: drive and got the same error.

**Comment by JackBoosY** [comment]
Seems another powershell issue.
Related: #12849.

**Comment by sfhacker** [comment]
Are we still having issues with yasm?

**Comment by JackBoosY** [comment]
cc @BillyONeal 
Due to the incompatibility between powershell versions, I always think we should stick to the powershell inside vcpkg.

**Comment by BillyONeal** [comment]
> Related: #12849.

I don't believe this is related; the call stacks here are completely different. That case is only happening for Powershell 5 whereas this is happening to a Powershell 7.

@lovettchris 

>C:/Users/lovet/.dotnet/tools/pwsh.exe

That's a strange location for pwsh to live. Can you run `C:\Users\lovet\.dotnet\tools\pwsh.exe --version` and let us know what it says?

**Comment by BillyONeal** [comment]
Appears to be fallout from https://github.com/PowerShell/PowerShell/issues/12126

**Comment by lovettchris** [comment]
Thanks - that's the default location for pwsh when you install it like this:

```
dotnet tool install --global Powershell
You can invoke the tool using the following command: pwsh
Tool 'powershell' (version '7.1.1') was successfully installed.

(ell) d:\temp>where pwsh
C:\Users\lovet\.dotnet\tools\pwsh.exe
```

**Comment by lovettchris** [comment]
But so I uninstalled this version of powershell and now `vcpkg install yasm-tool:x86-windows` works! Yay.
