### ISSUE TITLE
[New Port Request] opentelemetry-cpp

### ISSUE THREAD

**Issue by skywalkerisnull** [microsoft/vcpkg#15899]
Library name:
opentelemetry-cpp

Library description:
An observability framework for cloud-native software.

OpenTelemetry is a collection of tools, APIs, and SDKs. You use it to instrument, generate, collect, and export telemetry data (metrics, logs, and traces) for analysis in order to understand your software's performance and behavior.

Source repository URL:
https://github.com/open-telemetry/opentelemetry-cpp

Project homepage (if different from the source repository):
https://opentelemetry.io/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
Work is already underway in a number of areas in the library to make it more compatible with VCPKG: https://github.com/open-telemetry/opentelemetry-cpp/issues?q=vcpkg

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by JonLiu1993** [comment]
Sloved by #19536
