### ISSUE TITLE
Unable to build sdl2-mixer[mpg123]

### ISSUE THREAD

**Issue by ToxiClay** [microsoft/vcpkg#15890]
**Host Environment**
- OS: Windows 10
- Compiler: Unknown

**To Reproduce**
1. Attempt to install sdl2-mixer[mpg123] under the x64-windows triplet.
2. Read failure message indicating yasm-tool and portfiles.
3. Attempt to install yasm-tool and yasm-tool-helper under the x86-windows triplet.
4. Attempt to update portfiles.

**Failure logs** 
```
Omega@DESKTOP-BE8J914 MINGW64 /c/dev/vcpkg (master)
$ ./vcpkg --triplet x64-windows-static install sdl2-mixer[mpg123]
Computing installation plan...
The following packages will be built and installed:
  * mpg123[core]:x64-windows-static -> 1.26.3
  * sdl2[core]:x64-windows-static -> 2.0.14#1
    sdl2-mixer[core,mpg123,nativemidi]:x64-windows-static -> 2.0.4#10
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows-static...
Could not locate cached archive: C:\Users\Omega\AppData\Local\vcpkg\archives\a2\a29ee779752109fb663181a7e9d9b9a4f31b898b.zip
Could not locate cached archive: C:\Users\Omega\AppData\Local\vcpkg\archives\05\05fb7b23fa3ac9366018f27c508ac45fab28b3aa.zip
Could not locate cached archive: C:\Users\Omega\AppData\Local\vcpkg\archives\fe\fe2cd4e3331050ae82077e6e527b9fe6492b8075.zip
Starting package 1/3: mpg123:x64-windows-static
Building package mpg123[core]:x64-windows-static...
-- Trying auto-select mirror...
-- Using cached C:/dev/vcpkg/downloads/mpg123-1.26.3.tar.bz2
-- Skipping hash check for C:/dev/vcpkg/downloads/mpg123-1.26.3.tar.bz2.
-- The default mirror is in Disaster Recovery mode, trying other mirrors...
-- Trying mirror cfhcable...
-- Using cached C:/dev/vcpkg/downloads/mpg123-1.26.3.tar.bz2
-- Skipping hash check for C:/dev/vcpkg/downloads/mpg123-1.26.3.tar.bz2.
-- Cleaning sources at C:/dev/vcpkg/buildtrees/mpg123/src/7574331afa-116bac1a58.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/dev/vcpkg/downloads/mpg123-1.26.3.tar.bz2
-- Applying patch 0001-fix-x86-build.patch
-- Using source at C:/dev/vcpkg/buildtrees/mpg123/src/7574331afa-116bac1a58.clean
CMake Error at installed/x64-windows-static/share/yasm-tool-helper/yasm-tool-helper.cmake:16 (message):
  Cross-targetting and x64 ports requiring yasm require the x86-windows
  yasm-tool to be available.  Please install yasm-tool:x86-windows first.
Call Stack (most recent call first):
  ports/mpg123/portfile.cmake:37 (yasm_tool_helper)
  scripts/ports.cmake:128 (include)


Error: Building package mpg123:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: mpg123:x64-windows-static
  Vcpkg version: 2021-01-13-unknownhash

Additionally, attach any relevant sections from the log files above.

Omega@DESKTOP-BE8J914 MINGW64 /c/dev/vcpkg (master)
$ ./vcpkg --triplet x86-windows-static install yasm-tool yasm-tool-helper
Computing installation plan...
The following packages are already installed:
    yasm-tool[core]:x86-windows-static -> 2020-10-12
    yasm-tool-helper[core]:x86-windows-static -> 2020-10-12
Package yasm-tool:x86-windows-static is already installed
Package yasm-tool-helper:x86-windows-static is already installed

Total elapsed time: 34.7 us

Omega@DESKTOP-BE8J914 MINGW64 /c/dev/vcpkg (master)
$ ./vcpkg update
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.

Omega@DESKTOP-BE8J914 MINGW64 /c/dev/vcpkg (master)
$ git pull
Already up to date.
```

**Comment by StarGate-One** [comment]
You need to install the x86-windows triplet of yasm-tool, not x86-windows-static.

**Comment by ToxiClay** [comment]
OK, that seems to have worked without a hitch; thanks a lot!

That's throwing me off, though, just as a note. I hear "triplet" and I think there has to be three parameters; the architecture, the OS, and then *something,* and I interpreted "static" to be that third thing.

What's the meaning of "triplet" here, if not "must pass three parameters"?

**Comment by StarGate-One** [comment]
In this case, dynamic would be the 3rd parameter.
vcpkg defaults to dynamic on windows, static on linux/unix, so the default parameter is often left out.

**Comment by ToxiClay** [comment]
Aha, now I understand. Again, thank you very much. :)

**Comment by StarGate-One** [comment]
You are welcome!

**Comment by JackBoosY** [comment]
@ToxiClay Is this issue resolved?

**Comment by ToxiClay** [comment]
Almost. I noticed that the command will fail if I explicitly include `-dynamic` at the end of the triplet. The failure spits out a list of recognized triplets, so the user isn't left completely in the cold, but I think it might still be worth noting.

**Comment by JackBoosY** [comment]
@ToxiClay I don't understand what you mean.
According to the error message:
```
Cross-targetting and x64 ports requiring yasm require the x86-windows
  yasm-tool to be available.  Please install yasm-tool:x86-windows first.
```
You should alway install `yasm-tool:x86-windows` first, not the `-dynamic` triplet.

**Comment by ToxiClay** [comment]
> In this case, dynamic would be the 3rd parameter.
> vcpkg defaults to dynamic on windows, static on linux/unix, so the default parameter is often left out.

Explicitly specifying the apparently-default parameter causes a failure. I was doing that as a test, to see if it did in fact accept the `dynamic` parameter.

**Comment by StarGate-One** [comment]
The dynamic on windows and static on linux/unix is implied, you do not actually put those in.

The triplet name matches the names of the triplet files found in directory [vcpkg-root]/triplets and [vcpkg-root]/triplets/community.

You could create you own dynamic for windows by copying the [vcpkg-root]/triplets/x64-windows to [vcpkg-root]/triplets/community/x64-windows-dynamic. Then from the [vcpkg-root] run vcpkg install bzip2:x64-windows-dynamic if it makes you happy.
Just remember now the installed libs, symbols, includes and binaries will be under [vcpkg-root]/installed/x64-windows-dynamic.
Really this is not necessary as x64-windows implies dynamic.
Hope this helps you to understand.



Sent from my Verizon, Samsung Galaxy smartphone



-------- Original message --------

**Comment by ToxiClay** [comment]
Right, right; sorry for the questions, I was just curious about the implementation/effects.
