### ISSUE TITLE
How do I install the lastest upstream sources when the libraries is headers only

### ISSUE THREAD

**Issue by tic80** [microsoft/vcpkg#15897]
I would like to install the lastest version of sophus, currently 1.1.0 using the command 
`./vcpkg install sophus --head --keep-going`
it looks like that it cannot succeed as vcpkg looks for a library, which it will never found as the library is headers only.
when looking to `vcpkg/packages/sophus_x64-osx`, everything looks to be there.
Do you have any workaround ?

Here is the log:

Computing installation plan...
The following packages will be built and installed:
    sophus[core]:x64-osx -> 1.0.0-6 (+HEAD)
Could not locate cached archive: /.cache/vcpkg/archives/.zip
Starting package 1/1: sophus:x64-osx
Building package sophus[core]:x64-osx from HEAD...
-- Purging cached /vcpkg/downloads/strasdat-Sophus-master.tar.gz to fetch latest (use --no-downloads to suppress)
-- Downloading https://api.github.com/repos/strasdat/Sophus/git/refs/heads/master -> strasdat-Sophus-master.tar.gz.version...
-- Skipping hash check for /vcpkg/downloads/temp/strasdat-Sophus-master.tar.gz.version.
-- Downloading https://github.com/strasdat/Sophus/archive/master.tar.gz -> strasdat-Sophus-master.tar.gz...
-- Skipping hash check for /vcpkg/downloads/temp/strasdat-Sophus-master.tar.gz.
-- Extracting source /vcpkg/downloads/strasdat-Sophus-master.tar.gz
-- Applying patch fix_cmakelists.patch
-- Using source at /vcpkg/buildtrees/sophus/src/head/master-3a09787c51.clean
-- Configuring x64-osx-dbg
-- Configuring x64-osx-rel
-- Building x64-osx-dbg
-- Building x64-osx-rel
**CMake Error at scripts/cmake/vcpkg_fixup_cmake_targets.cmake:81 (message):
  '/vcpkg/packages/sophus_x64-osx/debug/lib/cmake/Sophus' does
  not exist.**
Call Stack (most recent call first):
  ports/sophus/portfile.cmake:17 (vcpkg_fixup_cmake_targets)
  scripts/ports.cmake:128 (include)

Error: Building package sophus:x64-osx failed with: BUILD_FAILED
Elapsed time for package sophus:x64-osx: 57.25 s

Total elapsed time: 57.25 s

RESULTS
    sophus:x64-osx: BUILD_FAILED: 57.25 s

SUMMARY
    SUCCEEDED: 0
    BUILD_FAILED: 1
    POST_BUILD_CHECKS_FAILED: 0
    FILE_CONFLICTS: 0
    CASCADED_DUE_TO_MISSING_DEPENDENCIES: 0
    EXCLUDED: 0
`

**Comment by NancyLi1013** [comment]
Hi @tic80 

Thanks for posting this issue.

You can update `vcpkg_fixup_cmake_targets(CONFIG_PATH lib/cmake/Sophus)` as `vcpkg_fixup_cmake_targets(CONFIG_PATH share/sophus/cmake)` to rebuild.

**Comment by tic80** [comment]
Thank you. It works perfectly! 
I have also seen that the integration with cmake of this version of sophus is now cleaner, similar to other libraries.

Although the author have pushed to the 1.1.0 version, I think you're waiting for a new tag to update their library or do you think this is something you can do ?

**Comment by NancyLi1013** [comment]
> Although the author have pushed to the 1.1.0 version, I think you're waiting for a new tag to update their library or do you think this is something you can do ?

Yes, since the current version 1.1.0 is old. We will update it to next release if there is a new tag. I think we can do nothing about this. It would be better to post the request to upstream.

**Comment by tic80** [comment]
thank you again!
