### ISSUE TITLE
[New Port Request] zap-zpp

### ISSUE THREAD

**Issue by jiangdawhy** [microsoft/vcpkg#15895]
Library name: 
zpp
Library description:
API Library that allows C++ developers to interact with the Zap Smart Contracts on the Ethereum Blockchain
Source repository URL:
https://github.com/zapproject/zpp 
Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
Still under construction.

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
