### ISSUE TITLE
[libLAS] improve suggested cmake targets

### ISSUE THREAD

**Issue by grandmaster789** [microsoft/vcpkg#15908]
****

**Is your feature request related to a problem? Please describe.**
When installing the libLAS package, the following CMake targets are suggested:
```
    The package liblas:x64-windows provides CMake targets:

        find_package(liblas CONFIG REQUIRED)
        target_link_libraries(main PRIVATE liblas liblas_c)
```

However when I placed this in a project verbatim, I received a CMake error message:
```
    Could not find a configuration file for package "liblas" that is compatible with requested version "".
        The following configuration files were considered but not accepted:
        [..........]/share/liblas/liblas-config.cmake, version: 1.8.1 (package = libLAS, NOT liblas)
```

**Proposed solution**
The find_package line is **case sensitive**, so instead of:
`    find_package(liblas CONFIG REQUIRED)`
The correct cmake target that should be suggested is:
`    find_package(libLAS CONFIG REQUIRED)`

**Describe alternatives you've considered**
Alternatively users could figure this out on their own

**Comment by JackBoosY** [comment]
Confirmed.
