### ISSUE TITLE
openvdb: cmake get_prerequisites error

### ISSUE THREAD

**Issue by Fedr** [microsoft/vcpkg#15901]
**Description**
After installing and integrating the latest vcpkg, and
```
    ./vcpkg install openvdb
```
it reports success:

    The package openvdb provides CMake targets:

    find_package(OpenVDB CONFIG REQUIRED)
    target_link_libraries(main PRIVATE OpenVDB::openvdb)

But after I add this find_package line in my CMakeLists.txt I get an error from cmake:
```
CMake Error at /home/fed/vcpkg/downloads/tools/cmake-3.19.2-linux/cmake-3.19.2-Linux-x86_64/share/cmake-3.19/Modules/GetPrerequisites.cmake:843 (message):
  /usr/bin/ldd failed: 1

Call Stack (most recent call first):
  /home/fed/vcpkg/installed/x64-linux/share/openvdb/FindOpenVDB.cmake:507 (get_prerequisites)
  /home/fed/vcpkg/installed/x64-linux/share/openvdb/vcpkg-cmake-wrapper.cmake:8 (_find_package)
  /home/fed/vcpkg/scripts/buildsystems/vcpkg.cmake:597 (include)
  CMakeLists.txt:8 (find_package)
```
Find for other packages installed by vcpkg works fine, so this is something openvdb specific.

**Environment**
Ubuntu 18.04 LTS inside Windows Subsystem Linux
GCC 9.3

**To Reproduce**
1. ./vcpkg install openvdb
2. add find_package(OpenVDB CONFIG REQUIRED) to CMakeLists.txt
3. See error

**Expected behavior**
Cmake finds openvdb package without an error.

**Comment by JackBoosY** [comment]
Confirmed.
