### ISSUE TITLE
Building package bzip2:x64-linux failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by zupalex** [microsoft/vcpkg#15911]
On a fresh clone of vcpkg, trying to install avro-cpp. I did try the update command but it just told me there's nothing to update.

Building package bzip2[core]:x64-linux...
-- Fetching https://sourceware.org/git/bzip2.git...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:108 (message):
    Command failed: /usr/bin/git fetch https://sourceware.org/git/bzip2.git 75a94bea3918e612b879d6a11ca64b8689526147 --depth 1 -n
    Working Directory: /home/alepaill/git/vcpkg/downloads/git-tmp
    Error code: 128

Error: Building package bzip2:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
 Package: bzip2:x64-linux
 Vcpkg version: 2021-01-13-unknownhash

Content of vcpkg/buildtrees/bzip2/git-fetch-x64-linux-err.log
     error: no such remote ref 75a94bea3918e612b879d6a11ca64b8689526147

**Comment by NancyLi1013** [comment]
Hi @zupalex 

Thanks for posting this issue.

Seems to be related with git. Please update git version to try it again.

Duplicated to #14424.

**Comment by zupalex** [comment]
Sorry I failed to find it when I searched for issues. Thanks!
