### ISSUE TITLE
Vcpkg problems when i run  C:\vcpkg>.\bootstrap-vcpkg.bat

### ISSUE THREAD

**Issue by rupengzhang** [microsoft/vcpkg#1591]
I have a problem about install vcpkg. I cloned the Vcpke,then i started to run C:\vcpkg>.\bootstrap-vcpkg.bat,there were problems happened.

3> .. \ src \ vcpkg_System.cpp (208): error C2664: "DWORD GetEnvironmentVariableW (LPCWSTR, LPWSTR, DWORD)": Can not get parameter 2 from "cons
       T wchar_t * "to" LPWSTR "[C: \ vcpkg \ toolsrc \ vcpkglib \ vcpkglib.vcxproj]
         .. \ src \ vcpkg_System.cpp (208): note: Convert the missing qualifier
     3> .. \ src \ vcpkg_System.cpp (209): error C3536: "sz2": Can not use [C: \ vcpkg \ toolsrc \ vcpkglib \ vcpkglib.vcxproj] before initialization
     3> .. \ src \ vcpkg_System.cpp (234): error C2440: "reinterpret_cast": Can not convert from "const wchar_t *" to "LPBYTE" [C: \ vcpkg \ toolsrc
       \ Vcpkglib \ vcpkglib.vcxproj]
         .. \ src \ vcpkg_System.cpp (234): note: Convert the missing qualifier
     3> .. \ src \ vcpkg_System.cpp (234): error C2660: "RegQueryValueExW": The function does not accept 5 arguments [C: \ vcpkg \ toolsrc \ vcpkglib \ vcpkglib.v
       Cxproj]
     3> has completed the operation of the build "C: \ vcpkg \ toolsrc \ vcpkglib \ vcpkglib.vcxproj" (default target) - failed.
     2> has completed the operation of the build "C: \ vcpkg \ toolsrc \ vcpkg \ vcpkg.vcxproj" (Build target) - failed.
     1> has completed the operation of the build "C: \ vcpkg \ toolsrc \ dirs.proj" (default target) - failed.

Failed to generate.

       "C: \ vcpkg \ toolsrc \ dirs.proj" (default) (1) ->
       "C: \ vcpkg \ toolsrc \ vcpkg \ vcpkg.vcxproj" (Build target) (2: 2) ->
       "C: \ vcpkg \ toolsrc \ vcpkglib \ vcpkglib.vcxproj" (default target) (3: 4) ->
       (ClCompile target) ->
         C: \ program \ (xv)
        [C: \ vcpkg \ toolsrc \ vcpkglib \ vcpkglib.vcxproj]
         C: \ program \ xxx \ windows \ v7.1a \ include \ spec \ Vcxproj]
         C: \ Program Files (x86) \ Microsoft SDKs \ Windows \ v7.1A \ Include \ shlobj.h (1151): warning C4091: "typedef": When no variables are declared
       Ignore the left side of "tagGPFIDL_FLAGS" [C: \ vcpkg \ toolsrc \ vcpkglib \ vcpkglib.vcxproj]

       "C: \ vcpkg \ toolsrc \ dirs.proj" (default) (1) ->
       "C: \ vcpkg \ toolsrc \ vcpkg \ vcpkg.vcxproj" (Build target) (2: 2) ->
       "C: \ vcpkg \ toolsrc \ vcpkglib \ vcpkglib.vcxproj" (default target) (3: 4) ->
       (ClCompile target) ->
         .. \ src \ vcpkg_System.cpp (208): error C2664: "DWORD GetEnvironmentVariableW (LPCWSTR, LPWSTR, DWORD)": Can not get parameter 2 from "co
       Nst wchar_t * "to" LPWSTR "[C: \ vcpkg \ toolsrc \ vcpkglib \ vcpkglib.vcxproj]
         .. \ src \ vcpkg_System.cpp (209): error C3536: "sz2": Can not use [C: \ vcpkg \ toolsrc \ vcpkglib \ vcpkglib.vcxproj] before initialization
         .. \ src \ vcpkg_System.cpp (234): error C2440: "reinterpret_cast": Can not convert from "const wchar_t *" to "LPBYTE" [C: \ vcpkg \ tools
       Rc \ vcpkglib \ vcpkglib.vcxproj]
         .. \ src \ vcpkg_System.cpp (234): error C2660: "RegQueryValueExW": The function does not accept 5 arguments [C: \ vcpkg \ toolsrc \ vcpkglib \ vcpkglib
       .vcxproj]

    3 warnings
    4 wrong

Used time 00: 00: 32.56
Copy-Item: The path "C: \ vcpkg \ toolsrc \ Release \ vcpkg.exe" could not be found because the path does not exist.
Location C: \ vcpkg \ scripts \ bootstrap.ps1: 34 characters: 5
+ Copy-Item $ vcpkgSourcesPath \ Release \ vcpkg.exe $ vcpkgRootDir \ vcpkg ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~
    + CategoryInfo: ObjectNotFound: (C: \ vcpkg \ toolsrc \ Release \ vcpkg.exe: String) [Copy-Item], ItemNotFoundExc
   Eption
    + FullyQualifiedErrorId: PathNotFound, Microsoft.PowerShell.Commands.CopyItemCommand

Copy-Item: The path "C: \ vcpkg \ toolsrc \ Release \ vcpkgmetricsuploader.exe" could not be found because the path does not exist.
Location C: \ vcpkg \ scripts \ bootstrap.ps1: 35 characters: 5
+ Copy-Item $ vcpkgSourcesPath \ Release \ vcpkgmetricsuploader.exe $ vcp ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~
    + CategoryInfo: ObjectNotFound: (C: \ vcpkg \ toolsr ... icsuploader.exe: String) [Copy-Item], ItemNotFoundExce
   Ption
    + FullyQualifiedErrorId: PathNotFound, Microsoft.PowerShell.Commands.CopyItemCommand

**Comment by ras0219-msft** [comment]
I see, it looks like we somehow tried to use the 7.1 SDK -- we should fix this.

The Windows 8.1 desktop SDK is the latest supported SDK for building Windows 8, Windows 7, Windows Vista applications and it's what we currently require. Could you try installing the Windows 8.1 SDK and rebuilding vcpkg?

https://developer.microsoft.com/en-us/windows/downloads/windows-8-1-sdk

**Comment by top1st** [comment]
c:\src\vcpkg>bootstrap-vcpkg.bat
WARNING: The binding of default value 'System.Net.NetworkCredential' to parameter 'ProxyCredential' failed: Cannot
process argument transformation on parameter 'ProxyCredential'. userName

What is this problem?
Waiting no reply
What i can do?

**Comment by LilyWangL** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen.
