### ISSUE TITLE
[angle:x86-android] build failure

### ISSUE THREAD

**Issue by painor** [microsoft/vcpkg#15914]
**Host Environment**
- OS: Windows10
- Compiler: 5f215c65fe6e5ae19df981ad02c2d7c29f778a84

**To Reproduce**
`./vcpkg install angle:x86-android`

**Failure logs** 
```
-- Building x86-android-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:145 (message):
    Command failed: G:/vcpkg/downloads/tools/cmake-3.19.2-windows/cmake-3.19.2-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v -j9
    Working Directory: G:/vcpkg/buildtrees/angle/x86-android-dbg
    See logs for more information:
      G:\vcpkg\buildtrees\angle\install-x86-android-dbg-out.log
 ```
 Relevant log from `G:\vcpkg\buildtrees\angle\install-x86-android-dbg-out.log`
 ```
G:/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c.clean/src\libANGLE/renderer/gl/glx/platform_glx.h:169:10: fatal error: 'X11/Xlib.h' file not found
#include <X11/Xlib.h>
         ^~~~~~~~~~~~
1 error generated.
```
**Additional context**
All android related builds I tried fail because they all need to install android-dbg which fails because windows doesn't use X11
I am also using the community triplet configuration for android x86

**Comment by lorenzoST0820** [comment]
Hi, I have the same issue when building from a Linux machine having arm64-android as the target

**Comment by Cheney-W** [comment]
This issue has not been updated for over 3 months, so if it is still an issue, please reopen the issue.

**Comment by kafeg** [comment]
If you need `angle` just as dependency for Qt, then just remove it from `qt5-base/vcpkg.json` because Qt builds with `-no-angle` option.
