### ISSUE TITLE
CMake 3.9 required?

### ISSUE THREAD

**Issue by stekyne** [Microsoft/vcpkg#1592]
Additional packages (*) will be installed to complete this operation.
Building package eigen3:x64-windows...

Download cmake
**No suitable version of cmake was found (requires 3.9.0 or higher). Download portable version?
[Y] Yes  [N] No  [A] Always Allow Downloads  [?] Help (default is "Y"):**

It seems that CMake 3.9 is required now? That's kind of broken my appveyor build (their images have 3.8.2) because it's waiting for a manual user acknowledgement. Would it be possible to at least put a timeout or something so it will proceed eventually?

**Comment by ras0219-msft** [comment]
Thanks for reporting this!

The best immediate workaround is to create a file `downloads/AlwaysAllowDownloads` [1] which will automatically accept any prompts.

I think there're strong arguments that we should
- Automatically do this if we detect we're in AppVeyor (downside is inconsistency)
- Never prompt (downside is less transparency)
however we haven't taken action on either of those yet.

[1] https://github.com/Microsoft/vcpkg/blob/e288a87b9f048b53ecf20bebc429ab1ab732220a/scripts/internalCI.ps1#L4

**Comment by stekyne** [comment]
Ah great stuff, I've added that line and it's working normally now. That really had me stumped. The prompt doesn't appear in the appveyor log and locally I had all the packages downloaded so I wasn't installing them regularly.

Both options seem OK to me, I'd probably prefer the second one.
