### ISSUE TITLE
[ceres] How do I build Ceres with EigenSparse from manifest?

### ISSUE THREAD

**Issue by r-f-a** [microsoft/vcpkg#15927]
Edit: This seems related to https://github.com/microsoft/vcpkg/issues/3417

What I want to achieve is to use ceres with `EigenSparse`, namely solver options like:

```cpp
solver_options.sparse_linear_algebra_library_type = ceres::EIGEN_SPARSE;
solver_options.linear_solver_type = ceres::SPARSE_NORMAL_CHOLESKY;
```

But this is what I get on program execution:

```
FAILURE (Can't use SPARSE_NORMAL_CHOLESKY with Solver::Options::sparse_linear_algebra_library_type = EIGEN_SPARSE, because support was not enabled when Ceres Solver was built.)
```

This is my json manifest:

```json
{
  "name": "manifest",
  "version-string": "0.0.1",
  "dependencies": [
    "catch2",
    "eigen3",
    "boost-math",
    {
      "name": "ceres",
      "features": [ "eigensparse" ]
    }
  ]
}
```

This is part of my `CMakeLists.txt`:

```cmake
find_package(Eigen3 3.3 CONFIG REQUIRED)
find_package(Ceres 2.0 REQUIRED)
set(CMAKE_CXX_STANDARD 17)

# ...

target_link_libraries(${my_lib_objs} PUBLIC Eigen3::Eigen)
target_link_libraries(${my_lib_objs} PUBLIC Ceres::ceres)
```

In VS CMake output I confirm it can't find the `EigenSparse` component
but that contradicts the manifest build instructions from above:

```
1> [CMake] -- Running vcpkg install - done
1> [CMake] -- Using toolchain file: C:/Users/Me/vcpkg/scripts/buildsystems/vcpkg.cmake
1> [CMake] -- Found required Ceres dependency: Eigen version 3.3.9 in C:/src/proj/out/build/x64-windows_vs/vcpkg_installed/x64-windows/include/eigen3
1> [CMake] -- Found Ceres version: 2.0.0 installed in: C:/src/proj/out/build/x64-windows_vs/vcpkg_installed/x64-windows/share with components: [SchurSpecializations, Multithreading]
```

I'm having the same issue after deleting all VS build directories,
vcpkg directory  `C:/Users/Me/vcpkg` (and bootstraping it again then)
and vcpkg cache directory (`C:\Users\Me\AppData\Local\vcpkg`).

I'm also having this from a command-line clean build (i.e. removing VS from the equation).

I'm bootstraping vcpkg from the latest master as of yesterday (Jan-27-2021).

**Comment by JackBoosY** [comment]
@strega-nil Can you please take a look?

Thanks.

**Comment by strega-nil** [comment]
@r-f-a this is an issue with manifests rn; it will be fixed as soon as #15474 is merged.

**Comment by r-f-a** [comment]
Thanks for the response.

I git pulled the latest master and bootstrapped it.

After that I clean built my project using the json manifest from my first message
but had the same outcome on both x64-Windows and x64-Linux.

**Comment by strega-nil** [comment]
@r-f-a could you run `git rev-parse HEAD` and `vcpkg version`, and give the output?

**Comment by r-f-a** [comment]
Sure.

```
> git rev-parse HEAD
5eea585548058540c3b73d087eb101c033b5fa85

> .\vcpkg.exe version
Vcpkg package management program version 2021-01-13-768d8f95c9e752603d2c5901c7a7c7fbdb08af35

See LICENSE.txt for license information.
```

**Comment by strega-nil** [comment]
Ohhh! I think I understand.

This is a serious bug in vcpkg, and @ras0219 is looking at it.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
