### ISSUE TITLE
Error: Building package gmp:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by sagil100** [microsoft/vcpkg#15924]
Package: gmp:x64-windows
  Vcpkg version: 2021-01-13-unknownhash
  
  using latest portfiles.

**Comment by PhoebeHui** [comment]
@sagil100, could you provide us more information, likes the failures logs and the environment?

I can't repro this issue locally.
```
Starting package 3/3: gmp:x64-windows
Building package gmp[core]:x64-windows...
-- Downloading https://github.com/ShiftMediaProject/gmp/archive/0018c44e8dfcc3b64b43e0aea4b3f419f0b65fd0.tar.gz -> ShiftMediaProject-gmp-0018c44e8dfcc3b64b43e0aea4b3f419f0b65fd0.tar.gz...
-- Extracting source E:/vcpkg/clean/vcpkg/downloads/ShiftMediaProject-gmp-0018c44e8dfcc3b64b43e0aea4b3f419f0b65fd0.tar.gz
-- Applying patch vs.build.patch
-- Applying patch runtime.patch
-- Applying patch adddef.patch
-- Using source at E:/vcpkg/clean/vcpkg/buildtrees/gmp/src/19f0b65fd0-9b395bc164.clean
-- Building SMP/libgmp.sln for Release
-- Building SMP/libgmp.sln for Debug
-- Installing: E:/vcpkg/clean/vcpkg/packages/gmp_x64-windows/share/gmp/copyright
-- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst -> msys-mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst...
-- Using msys root at E:/vcpkg/clean/vcpkg/downloads/tools/msys2/50864d9fae363d6e
-- Fixing pkgconfig file: E:/vcpkg/clean/vcpkg/packages/gmp_x64-windows/lib/pkgconfig/gmp.pc
-- Fixing pkgconfig file: E:/vcpkg/clean/vcpkg/packages/gmp_x64-windows/lib/pkgconfig/gmpxx.pc
-- Fixing pkgconfig file: E:/vcpkg/clean/vcpkg/packages/gmp_x64-windows/debug/lib/pkgconfig/gmp.pc
-- Fixing pkgconfig file: E:/vcpkg/clean/vcpkg/packages/gmp_x64-windows/debug/lib/pkgconfig/gmpxx.pc
-- Performing post-build validation
-- Performing post-build validation done
Building package gmp[core]:x64-windows... done
Installing package gmp[core]:x64-windows...
Installing package gmp[core]:x64-windows... done
Elapsed time for package gmp:x64-windows: 5.701 min

Total elapsed time: 6.394 min

```

**Comment by 1156477988** [comment]
Starting package 1/11: gmp:x64-windows
Building package gmp[core]:x64-windows...
-- Using cached C:/openMVG_MVS/vcpkg/downloads/ShiftMediaProject-gmp-0018c44e8dfcc3b64b43e0aea4b3f419f0b65fd0.tar.gz
-- Cleaning sources at C:/openMVG_MVS/vcpkg/buildtrees/gmp/src/19f0b65fd0-9b395bc164.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/openMVG_MVS/vcpkg/downloads/ShiftMediaProject-gmp-0018c44e8dfcc3b64b43e0aea4b3f419f0b65fd0.tar.gz
-- Applying patch vs.build.patch
-- Applying patch runtime.patch
-- Applying patch adddef.patch
-- Using source at C:/openMVG_MVS/vcpkg/buildtrees/gmp/src/19f0b65fd0-9b395bc164.clean
CMake Error at installed/x64-windows/share/yasm-tool-helper/yasm-tool-helper.cmake:16 (message):
  Cross-targetting and x64 ports requiring yasm require the x86-windows
  yasm-tool to be available.  Please install yasm-tool:x86-windows first.
Call Stack (most recent call first):
  ports/gmp/portfile.cmake:19 (yasm_tool_helper)
  scripts/ports.cmake:142 (include)

**Comment by 1156477988** [comment]
@PhoebeHui 

Starting package 1/11: gmp:x64-windows
Building package gmp[core]:x64-windows...
-- Using cached C:/openMVG_MVS/vcpkg/downloads/ShiftMediaProject-gmp-0018c44e8dfcc3b64b43e0aea4b3f419f0b65fd0.tar.gz
-- Cleaning sources at C:/openMVG_MVS/vcpkg/buildtrees/gmp/src/19f0b65fd0-9b395bc164.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/openMVG_MVS/vcpkg/downloads/ShiftMediaProject-gmp-0018c44e8dfcc3b64b43e0aea4b3f419f0b65fd0.tar.gz
-- Applying patch vs.build.patch
-- Applying patch runtime.patch
-- Applying patch adddef.patch
-- Using source at C:/openMVG_MVS/vcpkg/buildtrees/gmp/src/19f0b65fd0-9b395bc164.clean
CMake Error at installed/x64-windows/share/yasm-tool-helper/yasm-tool-helper.cmake:16 (message):
  Cross-targetting and x64 ports requiring yasm require the x86-windows
  yasm-tool to be available.  Please install yasm-tool:x86-windows first.
Call Stack (most recent call first):
  ports/gmp/portfile.cmake:19 (yasm_tool_helper)
  scripts/ports.cmake:142 (include)

**Comment by PhoebeHui** [comment]
This issue would be fixed by PR https://github.com/microsoft/vcpkg/pull/16478. Duplicate to https://github.com/microsoft/vcpkg/pull/16674.
