### ISSUE TITLE
[libmysql] build failure

### ISSUE THREAD

**Issue by kgday** [microsoft/vcpkg#15923]
**Host Environment**
- OS: windows 10
- Compiler: Microsoft c++

**To Reproduce**
`./vcpkg install libmysql --triplet=x64-windows`

**Failure Logs**
-- Downloading https://github.com/mysql/mysql-server/archive/7d10c82196c8e45554f27c00681474a9fb86d137.tar.gz -> mysql-mysql-server-7d10c82196c8e45554f27c00681474a9fb86d137.tar.gz...
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:105 (message):

  File does not have expected hash:

          File path: [ C:/vcpkg/downloads/temp/mysql-mysql-server-7d10c82196c8e45554f27c00681474a9fb86d137.tar.gz ]
      Expected hash: [ 9f5e8cc254ea2a4cf76313287c7bb6fc693400810464dd2901e67d51ecb27f8916009464fd8aed8365c3038314b845b3d517db6e82ae5c7908612f0b3b72335f ]
        Actual hash: [ 83999fe4483b0b1064758f9e321c6e3bf4af56913526fa7cdd04480f352261f6be172811753a5115eeec8755ff53d7eb444542f237cb787b78b47c8aae28f2b8 ]

  The file may have been corrupted in transit.  This can be caused by
  proxies.  If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY
  environment variables to
  "https://user:password@your-proxy-ip-address:port/".

**Comment by JonLiu1993** [comment]
@kgday ,I can successfully install libmysql[core]:x64-windows on my local Windows 10 computer：
````
Stored binary cache: C:\Users\...\AppData\Local\vcpkg\archives\b3\b3b365cd3a8758f2536ebc201cbfdfe4041f3c7e.zip
Building package libmysql[core]:x64-windows... done
Installing package libmysql[core]:x64-windows...
Installing package libmysql[core]:x64-windows... done
Elapsed time for package libmysql:x64-windows: 6.916 min

Total elapsed time: 33 min

The package libmysql provides CMake targets:

    find_package(libmysql REQUIRED)
    target_link_libraries(main PRIVATE ${MYSQL_LIBRARIES})

````
You recreate a folder and reinstall after git clone vcpkg

**Comment by kgday** [comment]
Thank you for trying.  Tried again a few times still get the same error but a different actual hash each time  I have no proxies set up that I know of.  It must be an internet connection related thing somehow or simply a problematic file.

**Comment by JackBoosY** [comment]
Hi @kgday, please make sure your vcpkg is latest, and I can confirm you downloaded package is broken.
Can you please test if you can extract C:/vcpkg/downloads/temp/mysql-mysql-server-7d10c82196c8e45554f27c00681474a9fb86d137.tar.gz manually?

Thnaks.

**Comment by kgday** [comment]
Hi @JackBoosY  
I had done a git put only a few hours ago.  I have just done another and notice a changed to a cpp file so  I am now doing a fresh bootstrap.

I cannot manually extract the file in the temp folder. I am getting an unexpected end of data

I will try again after the fresh bootstrap is completed.

**Comment by kgday** [comment]
bootstrap done.  Tried to install libmysql again but still same issue.  Actual hash different again.

C:\vcpkg>vcpkg install libmysql --triplet=x64-windows
Computing installation plan...
The following packages will be built and installed:
    libmysql[core]:x64-windows -> 8.0.20#1
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\kevin\AppData\Local\vcpkg\archives\84\84ca78b2aa6280a4771b100dc71ef898da3c8d08.zip
Starting package 1/1: libmysql:x64-windows
Building package libmysql[core]:x64-windows...
-- Downloading https://github.com/mysql/mysql-server/archive/7d10c82196c8e45554f27c00681474a9fb86d137.tar.gz -> mysql-mysql-server-7d10c82196c8e45554f27c00681474a9fb86d137.tar.gz...
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:105 (message):


  File does not have expected hash:

          File path: [ C:/vcpkg/downloads/temp/mysql-mysql-server-7d10c82196c8e45554f27c00681474a9fb86d137.tar.gz ]
      Expected hash: [ 9f5e8cc254ea2a4cf76313287c7bb6fc693400810464dd2901e67d51ecb27f8916009464fd8aed8365c3038314b845b3d517db6e82ae5c7908612f0b3b72335f ]
        Actual hash: [ 7558135cb9d0498e0d0b3a80a0dd118b9410b5c901227bb34c1fe5084881ccd0af14fabccb1e795d49902fd0a3ebc1226a2c3944ec2c1fff76768e5e7b854e91 ]

  The file may have been corrupted in transit.  This can be caused by
  proxies.  If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY
  environment variables to
  "https://user:password@your-proxy-ip-address:port/".

**Comment by kgday** [comment]
Same error: Unexpected end of data with a manual extraction (I did delete the previous one before trying to install again)

**Comment by JackBoosY** [comment]
Can you download _https://github.com/mysql/mysql-server/archive/7d10c82196c8e45554f27c00681474a9fb86d137.tar.gz_ manually then put it into _VCPKG_ROOT/downloads_ and try again?

Thanks.

**Comment by kgday** [comment]
I downloaded it manually on a linux machine and then tried to extract using the linux archive manager.  It gave me error: 'truncated gzip input'

**Comment by JackBoosY** [comment]
@kgday So I can be sure that there is a problem with your network, maybe a program corrupted the downloaded content. 
Can you try another network?

**Comment by kgday** [comment]
I can only try to bypass some of the network infrastructure I have for the household and connect directly to the cell modem (3g).  I will try that and let you know.

**Comment by kgday** [comment]
No that didn't help.  I'll leave it for now and when I get the opportunity to download it in town I'll try again.

**Comment by JonLiu1993** [comment]
@kgday ,I will close this issue, if you still have questions, please reopen the issue
