### ISSUE TITLE
[vcpkg tools] Use system internal tools

### ISSUE THREAD

**Issue by Starl1ght** [microsoft/vcpkg#15930]
****

**Is your feature request related to a problem? Please describe.**
We have our whole depends already built and uploaded to nuget.
However, on CI runs (clear VM) VCPKG is wasting time on downloading git (why do we need git there?)
And only after this downloading finishes - VCPKG checks if all the files are already cached somewhere, and downloads them.

**Proposed solution**
Check if artifacts are already cached, and only then download necessary stuff for building, like git.

**Describe alternatives you've considered**
We are going to put necessary things like latest git, powershell etc in VM image, but still...

**Additional context**
All the dependencies are just downloaded from Nuget, without any building.
![image](https://user-images.githubusercontent.com/3275752/106204127-860b2780-61cd-11eb-8f23-e2eece7fde77.png)

**Comment by JackBoosY** [comment]
As you can see, vcpkg did not find the suitable tool versions.

**Comment by NancyLi1013** [comment]
Hi @Starl1ght 

Currently, vcpkg can support system tools. If the tool version is less than the version that vcpkg provides, it will be downloaded. Otherwise, you can use the tools that already on your machine.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
