### ISSUE TITLE
directxsdk is no longer a valid port

### ISSUE THREAD

**Issue by walbourn** [microsoft/vcpkg#15946]
The download referenced by https://github.com/microsoft/vcpkg/blob/master/ports/directxsdk/portfile.cmake no longer exists. It was removed along with all other SHA-1 content.

**Comment by walbourn** [comment]
Note also that the bulk of this content is already in the Windows SDK so there's no need for it to be in a vcpkg.

* D3DCSX(D).LIB
* D3DCompiler.lib
* D2D1.LIB
* D3D9.LIB
* D3D10.LIB
* D3D10_1.LIB
* D3D11.LIB
* DINPUT8.LIB
* DSOUND.LIB
* DWRITE.LIB
* DXGI.LIB
* DXGUID.LIB
* XINPUT.LIB

I'm working on a solution for the D3DX9/D3DX10/D3DX11 legacy libraries:

* D3DX11(D).LIB
* D3DX10(D).LIB
* D3DX9(D).LIB
* D3DXOF.LIB

For XAudio2, the correct solution is to use [XAudio2Redist](https://aka.ms/xaudio2redist) instead:

* XAPOBASE(D).LIB
* X3DAUDIO.LIB
* XAPOFX.LIB

> XACT; XAudio 2.7 or earlier; XInput 1.1, 1.2, or 1.3; and DirectSetup are all deprecated and should no longer be used at all.

**Comment by Hoikas** [comment]
The DirectX included with the Windows SDK removes a great many legacy features that many applications potentially rely on. Off the top of my head, they are DirectDraw and compiling Direct3D9 shaders from assembly. These seemingly have no upgrade paths that are publicly available. Perhaps the port should be updated to use archive.org instead of simply being deleted?

**Comment by walbourn** [comment]
Well the DirectX SDK including the used in this port hasn't supported assembly shaders in many year DirectDraw also works fine from the Windows SDK.

The only scenario that is an issue is D3DX which 
I'm working on finding a solution.

**Comment by walbourn** [comment]
I'm also working on a port for  the xaudio2redist

**Comment by Hoikas** [comment]
I just updated an application using the June 2010 DX SDK (the one in the port) to the Windows SDK version few months back, and the points I mentioned were the ones I had to work on the most :wink:. To be fair, it was Direct Draw 7, so really old. The application initially targeted a much older DirectX SDK from around 2004, so I don't know how relevant those points are, but I know from experience the math changes are very much trivial in comparison 😄 .

**Comment by NancyLi1013** [comment]
Hi @walbourn 

Thanks for posting this issue.

Is it possible that you provide the archive file DXSDK_Jun10.exe to a public website to make the file available for users?

Thanks.

**Comment by Hoikas** [comment]
@NancyLi1013 As mentioned above, the DirectX libraries included in the Windows SDK do not include all of the DirectX SDK. The DirectX SDK (June 2010) can still be downloaded from archive.org: https://archive.org/details/dxsdk_jun10

**Comment by walbourn** [comment]
I'm very mixed on the right choice here...

The real problem with the legacy DirectX SDK is that you don't need *most* of it, but people are always unclear on what exactly they DO need it for...

Using the archive is worthwhile for Windows XP because that's really the only option--to use the "xp" toolset in Visual C++ you are using the Windows 7.1A SDK and *not* the Windows 8/10 SDK so you end up on the 'before integration' side of the story.

But for Windows 7 or later, the better option is to completely avoid using the legacy DirectX SDK at all.

Another issue is that the archive.org does *not* have the legacy DirectSetup packages, so the only way to do deployment is to use the REDIST from the legacy DXSDK itself...

How about this for a proposed solution:

* Update this port to use the archive.org copy--I've verified it is the genuine download.
* Add a message to the port that explain why you shouldn't use it :)

**Comment by walbourn** [comment]
For review https://github.com/microsoft/vcpkg/pull/16010
