### ISSUE TITLE
[New Port Request] Magick++

### ISSUE THREAD

**Issue by ViniDalvino** [microsoft/vcpkg#15959]
Library name:
Magick++
Library description:
Magick++ is the object-oriented C++ API to the ImageMagick image-processing library, the most comprehensive open-source image processing package available
Source repository URL:
https://github.com/ImageMagick/ImageMagick/tree/main/Magick%2B%2B
Project homepage (if different from the source repository):
http://www.imagemagick.org/Magick++/
Anything else that is useful to know when adding (such as optional features the library may have that should be included):
every image codec to be supported

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by PhoebeHui** [comment]
See https://github.com/microsoft/vcpkg/blob/master/docs/examples/packaging-github-repos.md, let me know if you have any questions about that.

**Comment by sean1832** [comment]
> > If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
> 
> Can you send me a guide onto how to add ports @PhoebeHui

Did you manage to add the ports?
