### ISSUE TITLE
"DLLs should not be present in a static build" error installing grpc

### ISSUE THREAD

**Issue by dalebrubaker** [Microsoft/vcpkg#1595]
Window 10 Pro
,\vcpkg install grpc
Error below requested that I file this issue.

-- Package x86-windows-dbg done
-- Installing: D:/GitFoss/vcpkg/packages/grpc_x86-windows/share/grpc/copyright
-- Performing post-build validation
DLLs should not be present in a static build, but the following DLLs were found:

    D:/GitFoss/vcpkg/packages/grpc_x86-windows/tools/grpc/zlib1.dll
    D:/GitFoss/vcpkg/packages/grpc_x86-windows/tools/grpc/SSLEAY32.dll
    D:/GitFoss/vcpkg/packages/grpc_x86-windows/tools/grpc/libprotoc.dll
    D:/GitFoss/vcpkg/packages/grpc_x86-windows/tools/grpc/libprotobuf.dll
    D:/GitFoss/vcpkg/packages/grpc_x86-windows/tools/grpc/LIBEAY32.dll

Found 1 error(s). Please correct the portfile:
    D:\GitFoss\vcpkg\ports\grpc\portfile.cmake
-- Performing post-build validation done
Error: Building package grpc:x86-windows failed with: POST_BUILD_CHECKS_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: grpc:x86-windows
  Vcpkg version: 0.0.81-b33632943c51a53c61fbbfe38b4f23c1767dc602

Additionally, attach any relevant sections from the log files above.
PS D:\GitFoss\vcpkg> .\vcpkg.exe update
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.
PS D:\GitFoss\vcpkg>

**Comment by codicodi** [comment]
`> Vcpkg version: 0.0.81-b33632943c51a53c61fbbfe38b4f23c1767dc602`

That's fairly old build. I suspect you pulled https://github.com/Microsoft/vcpkg/commit/4267c86b1f7cfe20e88fe7a1eaaa4caaca8c5d77 which requires `vcpkg.exe` to be rebuilt.
I'd recommend you run `git pull` once more (just to be sure) and then rebuild vcpkg with `.\bootstrap-vcpkg.bat`

**Comment by dalebrubaker** [comment]
Yes, that fixed it, thank you.
