### ISSUE TITLE
How do I use fontconfig via vcpkg/cmake?

### ISSUE THREAD

**Issue by christianparpart** [microsoft/vcpkg#15958]
Hey guys, I am already successfully using freetype and harfbuzz on windows via vcpkg. But I just can't get cmake to find fontconfig on windows (using cmake/vcpkg).

The problem is also that `vcpkg install fontconfig` just insists in NOT telling me how to import fontconfig in my cmake project, and looking in the internet only reveals tickets of build failures but not how to actually "use" it via vcpkg/cmake on Windows .

Any ideas?
Many thanks,
Chris.

**Comment by Neumann-A** [comment]
```
find_package(Fontconfig)
target_link_libraris(Whatever PRIVATE Fontconfig::Fontconfig)
```
vcpkg does not help with simple cmake modules:
https://cmake.org/cmake/help/latest/module/FindFontconfig.html

**Comment by NancyLi1013** [comment]
Hi @christianparpart 

Please let me know if you still have other concerns about this issue.

**Comment by christianparpart** [comment]
Hey @NancyLi1013. It actually worked, I am glad, many thanks for this. Although, I actually missed that hint in the post-install notes in `vcpkg install ...`, but maybe I was just used to see that (especially since on Linux/osx I'm again using other ways to detect fontconfig).
