### ISSUE TITLE
atkmm build failure

### ISSUE THREAD

**Issue by kazssym** [microsoft/vcpkg#15963]
**Host Environment**
- OS: Windows
- Compiler: Microsoft(R) C/C++ Optimizing Compiler Version 19.28.29336

**To Reproduce**
`./vcpkg install atkmm`

**Failure logs** 
```
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:108 (message):
    Command failed: msbuild E:/UserData/Kaz/Programs/vcpkg/buildtrees/atkmm/src/atkmm-2-de808b48b0.clean/MSVC_Net2013/atkmm.sln /p:Configuration=Release /t:atkmm /p:Platform=Win32 /p:PlatformToolset=v142 /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /p:WindowsTargetPlatformVersion=10.0.18362.0 /p:VcpkgManifestInstall=false /m /p:ForceImportBeforeCppTargets=E:/UserData/Kaz/Programs/vcpkg/scripts/buildsystems/msbuild/vcpkg.targets /p:VcpkgTriplet=x86-windows /p:VcpkgCurrentInstalledDir=E:/UserData/Kaz/Programs/vcpkg/installed/x86-windows
    Working Directory: E:/UserData/Kaz/Programs/vcpkg/buildtrees/atkmm/x86-windows-rel
    Error code: 1
    See logs for more information:
      E:\UserData\Kaz\Programs\vcpkg\buildtrees\atkmm\build-x86-windows-rel-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_msbuild.cmake:123 (vcpkg_execute_required_process)
  ports/atkmm/portfile.cmake:26 (vcpkg_build_msbuild)
  scripts/ports.cmake:128 (include)


Error: Building package atkmm:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: atkmm:x86-windows
  Vcpkg version: 2021-01-13-unknownhash
```
[build-x86-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/5898716/build-x86-windows-rel-out.log)

**Additional context**
It looks like the default code page 932 causes the failure. Apparently, glibmm installs headers with Unicode characters. It would require the `/utf-8` compiler option.

**Comment by JackBoosY** [comment]
See [workaround](https://github.com/microsoft/vcpkg/issues/13268#issuecomment-684635572).

**Comment by kazssym** [comment]
It is much easier to comment out the following pragma in msvc_recommended_pragmas.h

```
#pragma warning(error:4819)
```

**Comment by JackBoosY** [comment]
@kazssym Without setting this, you will encounter other issues.
So I think that's the best way instead of your solution.

**Comment by kazssym** [comment]
I cannot understand why I must change a system-wide setting just to build a few packages. It could be a real option if it didn't affect other applications at all.

**Comment by JackBoosY** [comment]
@kazssym Because this problem involves many ports, not just atkmm.

You can make a patch to add this option to compile process.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
