### ISSUE TITLE
Why is compilation with MSVC significantly faster than with GCC?

### ISSUE THREAD

**Issue by BullyWiiPlaza** [microsoft/vcpkg#15961]
When I build my code on `Windows` using `Visual Studio`, the compilation time is signficantly lower than if I build my code on `Ubuntu` using `WSL` and `GCC`. The code base is exactly identical and uses `CMake`. All dependencies are of course installed with `vcpkg` exactly in the same way. What could be the reason for this major performance difference?

`MSVC`: ~36 seconds
`GCC`: ~1:10 minutes

The libraries I'm linking against are:
* `Boost`
* `Catch2`
* `Loguru`
* `CLI11`

I suspect that `MSVC` might use precompiled headers to gain such a speed boost or maybe `vcpkg` can install precompiled headers for libraries too? Some header-only libraries can be a major pain to include and wait for on every recompilation.

**Comment by cenit** [comment]
Are you comparing static triplets between them or not?

**Comment by BullyWiiPlaza** [comment]
@cenit Yes, I installed the static triplets on `Windows` but on `Linux` they don't exist so I use the "normal" `x64-linux` versions. Both compile into a static executable without dynamic libraries though.

**Comment by cenit** [comment]
Yes sure, the important thing is that you compare apples to apples.
Then maybe your problem might be due to WSL: is it WSL1 or 2? If WSL2, are you using a folder inside /mnt? If so, try using a folder in your home and enjoy the speed boost!

**Comment by StarGate-One** [comment]
This article may also shed some light as WSL2 file operations are slower than WSL1 - Reference: https://vxlabs.com/2019/12/06/wsl2-io-measurements/#discussion

**Comment by BullyWiiPlaza** [comment]
> Yes sure, the important thing is that you compare apples to apples.
> Then maybe your problem might be due to WSL: is it WSL1 or 2? If WSL2, are you using a folder inside /mnt? If so, stop using it and try using a folder in your /home and enjoy the speed boost!

Yes, I'm using `WSL 2` and my code is indeed under `/mnt` to make it shared between `Windows` and `WSL` for working on the same code base. I can't seem to open my code in the `/home` folder using an IDE like `CLion` on `Windows` and I'm running into troubles compiling it from the command line so I didn't benchmark the difference yet. This might be the solution for the speed issues but still it's not very practical for the aforementioned issues.

**Comment by cenit** [comment]
Yeah with WSL1 it was the opposite.
To have code under /home and use a windows ide is complicated now. Only tools like VSCode with remote WSL experience can benefit from this config. Otherwise you have to accept very slow fs performances
