### ISSUE TITLE
[New Port Request] <ZBAR>

### ISSUE THREAD

**Issue by JaosonMa** [microsoft/vcpkg#15968]
Library name: zbar

Library description: qrcode/ barcode ocr same with z-xing

Source repository URL: https://github.com/ZBar/ZBar

Project homepage (if different from the source repository):
https://github.com/ZBar/ZBar
Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
Related to PR https://github.com/microsoft/vcpkg/pull/16113

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
