### ISSUE TITLE
[ curl ] build failure

### ISSUE THREAD

**Issue by Gladaed** [microsoft/vcpkg#15964]
**Host Environment**
- OS: Windows
- Compiler: revision

**To Reproduce**
Get latest vcpkg zip file from https://github.com/microsoft/vcpkg/releases (e.g. https://github.com/microsoft/vcpkg/archive/2019.09.zip) and extract it to a folder of your choice (e.g. C:\vcpkg\)
Open Developer Command Prompt for VS 2017 (see Windows Start menu or %PROGRAMDATA%\Microsoft\Windows\Start Menu\Programs\Visual Studio 2017\Visual Studio Tools\) and cd to C:\vcpkg\
Run bootstrap-vcpkg.bat
Run vcpkg.exe integrate install
Run vcpkg.exe install curl

**Failure logs** 
```
C:\Program Files (x86)\vcpkg-2020.11>.\vcpkg update
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.

C:\Program Files (x86)\vcpkg-2020.11>git pull
fatal: not a git repository (or any of the parent directories): .git

C:\Program Files (x86)\vcpkg-2020.11>vcpkg.exe install curl
Computing installation plan...
The following packages will be built and installed:
    curl[core,non-http,schannel,ssl,sspi,winssl]:x86-windows
  * zlib[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x86-windows...
Starting package 1/2: zlib:x86-windows
Building package zlib[core]:x86-windows...
Could not locate cached archive: C:\Users\******\AppData\Local\vcpkg\archives\17\1703e3666a1907432b9037386b4c28afe42b977b.zip
-- Using cached C:/Program Files (x86)/vcpkg-2020.11/downloads/zlib1211.tar.gz
-- Cleaning sources at C:/Program Files (x86)/vcpkg-2020.11/buildtrees/zlib/src/1.2.11-63309e48e5.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Program Files (x86)/vcpkg-2020.11/downloads/zlib1211.tar.gz
-- Applying patch cmake_dont_build_more_than_needed.patch
-- Applying patch 0001-Prevent-invalid-inclusions-when-HAVE_-is-set-to-0.patch
-- Applying patch add_debug_postfix_on_mingw.patch
-- Using source at C:/Program Files (x86)/vcpkg-2020.11/buildtrees/zlib/src/1.2.11-63309e48e5.clean
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Using msys root at C:/Program Files (x86)/vcpkg-2020.11/downloads/tools/msys2/c809757c94447846
-- Fixing pkgconfig file: C:/Program Files (x86)/vcpkg-2020.11/packages/zlib_x86-windows/lib/pkgconfig/zlib.pc
-- CHECK_LIB_zlib_RELEASE:CHECK_LIB_zlib_RELEASE-NOTFOUND
CMake Error at scripts/cmake/vcpkg_fixup_pkgconfig.cmake:232 (message):
  Library "zlib" was not found! If it is a system library use the
  SYSTEM_LIBRARIES parameter for the vcpkg_fixup_pkgconfig call! Otherwise,
  correct the *.pc file
Call Stack (most recent call first):
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:298 (vcpkg_fixup_pkgconfig_check_files)
  ports/zlib/portfile.cmake:48 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:135 (include)


Error: Building package zlib:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zlib:x86-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.

C:\Program Files (x86)\vcpkg-2020.11>
```
**Additional context**
Tried to use vcpkg for a quick curl installation according to https://stackoverflow.com/questions/53861300/how-do-you-properly-install-libcurl-for-use-in-visual-studio-2017

did try twice, this is the second output. The complete log: https://pastebin.com/h57NPLnC

**Comment by JackBoosY** [comment]
```
CMake Error at scripts/cmake/vcpkg_fixup_pkgconfig.cmake:232 (message):
  Library "zlib" was not found! If it is a system library use the
  SYSTEM_LIBRARIES parameter for the vcpkg_fixup_pkgconfig call! Otherwise,
  correct the *.pc file
```

Please re-install zlib then try to rebuild curl.

Thanks.

**Comment by longnguyen2004** [comment]
@JackBoosY We're having issues with `zlib`'s pkg-config file, so we should investigate what's wrong there.

**Comment by longnguyen2004** [comment]
Can you give us the content of the file `C:/Program Files (x86)/vcpkg-2020.11/packages/zlib_x86-windows/lib/pkgconfig/zlib.pc`, and also the content of the folder `C:/Program Files (x86)/vcpkg-2020.11/packages/zlib_x86-windows/lib`?

**Comment by Gladaed** [comment]
C:\Program Files (x86)\vcpkg-2020.11\packages\zlib_x86-windows\lib\pkgconfig:

prefix=${pcfiledir}/../..

exec_prefix=${prefix}
libdir=${prefix}/lib
sharedlibdir=${prefix}/lib
includedir=${prefix}/include

Name: zlib
Description: zlib compression library
Version: 1.2.11

Requires:
Libs: -L${libdir} -L${sharedlibdir} -lzlib
Cflags: -I${includedir}


The whole directory (C:/Program Files (x86)/vcpkg-2020.11/packages/zlib_x86-windows):
https://www.dropbox.com/s/x6g4z8z1jiq5t7h/zlib_x86-windows.7z?dl=0

**Comment by longnguyen2004** [comment]
Can you try updating vcpkg and try again?
(run `git pull` then `bootstrap-vcpkg.bat`)

**Comment by JackBoosY** [comment]
@Gladaed I can confirm your zlib is out-dated, please update vcpkg, remove zlib and re-install zlib again.

**Comment by PhoebeHui** [comment]
@Gladaed, please reopen this issue if it still be a problem for you.
