### ISSUE TITLE
How do I export arrayfire path on Linux, so vcpkg can find arrayfire?

### ISSUE THREAD

**Issue by EmreOzkose** [microsoft/vcpkg#15969]
I am installing flashlight, and arrayfire is necessary for flashlight. When I am installing arrayfire, I got error. I think that error is related to path issue.

Pipeline:
1. I installed arrayfire by following these instructions: https://arrayfire.org/docs/installing.htm#Linux.
2. I also install to /usr/local instead of /opt path according to documentation (https://arrayfire.com/setting-up-an-arrayfire-project-on-linux/)
3. When I run test of arrafire, there is not any error about installation.

4. when I run `vcpkg install cuda intel-mkl fftw3 cub kenlm arrayfire[cuda] cudnn nccl openmpi cereal stb gflags glog libsndfile gtest`, I got this error message:

> Computing installation plan...
The following packages are already installed:
    cereal[core]:x64-linux -> 1.3.0
    cub[core]:x64-linux -> 1.8.0-1
    cuda[core]:x64-linux -> 10.1#5
    cudnn[core]:x64-linux -> 7.6#4
    fftw3[core]:x64-linux -> 3.3.8-7
    gflags[core]:x64-linux -> 2.2.2-1
    glog[core]:x64-linux -> 0.4.0-3
    gtest[core]:x64-linux -> 1.10.0#3
    intel-mkl[core]:x64-linux -> 2020.0.0
    kenlm[core]:x64-linux -> 20200924#1
    libsndfile[core,external-libs]:x64-linux -> 1.0.30#1
    nccl[core]:x64-linux -> 2.4.6
    openmpi[core]:x64-linux -> 4.0.3#3
    stb[core]:x64-linux -> 2020-09-14
The following packages will be built and installed:
    arrayfire[core,cpu,cuda,unified]:x64-linux -> 3.7.3#3
Package cub:x64-linux is already installed
Package cuda:x64-linux is already installed
Package cudnn:x64-linux is already installed
Package intel-mkl:x64-linux is already installed
Package cereal:x64-linux is already installed
Package fftw3:x64-linux is already installed
Package gflags:x64-linux is already installed
Package glog:x64-linux is already installed
Package gtest:x64-linux is already installed
Package kenlm:x64-linux is already installed
Package libsndfile:x64-linux is already installed
Package nccl:x64-linux is already installed
Package openmpi:x64-linux is already installed
Package stb:x64-linux is already installed
Detecting compiler hash for triplet x64-linux...
Could not locate cached archive: 
HOMEPATH/.cache/vcpkg/archives/4d/4d1636a2361e71cfdc66bf53276ec78ba688576d.zip
Starting package 1/1: arrayfire:x64-linux
Building package arrayfire[core,cpu,cuda,unified]:x64-linux...
-- Using cached INSTALLATIONPATH/vcpkg/downloads/arrayfire-arrayfire-59ac7b980d1ae124aae914fb29cbf086c948954d.tar.gz
-- Cleaning sources at INSTALLATIONPATH/vcpkg/buildtrees/arrayfire/src/86c948954d-c996b9f837.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source INSTALLATIONPATH/vcpkg/downloads/arrayfire-arrayfire-59ac7b980d1ae124aae914fb29cbf086c948954d.tar.gz
-- Applying patch build.patch
-- Using source at INSTALLATIONPATH/vcpkg/buildtrees/arrayfire/src/86c948954d-c996b9f837.clean
-- Using cached INSTALLATIONPATH/vcpkg/downloads/arrayfire-threads-b666773940269179f19ef11c8f1eb77005e85d9a.tar.gz
-- Cleaning sources at INSTALLATIONPATH/vcpkg/buildtrees/arrayfire/src/7005e85d9a-64aebcce4b.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source INSTALLATIONPATH/vcpkg/downloads/arrayfire-threads-b666773940269179f19ef11c8f1eb77005e85d9a.tar.gz
-- Using source at INSTALLATIONPATH/vcpkg/buildtrees/arrayfire/src/7005e85d9a-64aebcce4b.clean
-- Using cached INSTALLATIONPATH/vcpkg/downloads/arrayfire-forge-1a0f0cb6371a8c8053ab5eb7cbe3039c95132389.tar.gz
-- Cleaning sources at INSTALLATIONPATH/vcpkg/buildtrees/arrayfire/src/9c95132389-511398ace8.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source INSTALLATIONPATH/vcpkg/downloads/arrayfire-forge-1a0f0cb6371a8c8053ab5eb7cbe3039c95132389.tar.gz
-- Using source at INSTALLATIONPATH/vcpkg/buildtrees/arrayfire/src/9c95132389-511398ace8.clean
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:145 (message):
    Command failed:INSTALLATIONPATH/vcpkg/downloads/tools/cmake-3.19.2-linux/cmake-3.19.2-Linux-x86_64/bin/cmake --build . --config Debug --target install -- -v -j49
    Working Directory: INSTALLATIONPATH/vcpkg/buildtrees/arrayfire/x64-linux-dbg
    See logs for more information:
      INSTALLATIONPATH/vcpkg/buildtrees/arrayfire/install-x64-linux-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:27 (vcpkg_build_cmake)
  ports/arrayfire/portfile.cmake:76 (vcpkg_install_cmake)
  scripts/ports.cmake:128 (include)

Error: Building package arrayfire:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: arrayfire:x64-linux
  Vcpkg version: 2021-01-13-unknownhash

Additionally, attach any relevant sections from the log files above.

How can I set arrayfire path, so vcpkg can find the installation?

NOTE: vcpkg is up to date

**Comment by JackBoosY** [comment]
Please provide the failure log _INSTALLATIONPATH/vcpkg/buildtrees/arrayfire/install-x64-linux-dbg-out.log_.

Thanks.

**Comment by EmreOzkose** [comment]
After running `sudo apt-get install libarrayfire-dev`, I can install arrayfire[cpu] , but I cannot install arrayfire[cuda]. I opened log file and I think the interesting part is :

> [350/833] cd INSTALLATIONPATH/vcpkg/buildtrees/arrayfire/x64-linux-dbg/src/backend/cuda/CMakeFiles/af_cuda_static_cuda_library.dir && INSTALLATIONPATH/vcpkg/downloads/tools/cmake-3.19.2-linux/cmake-3.19.2-Linux-x86_64/bin/cmake -E make_directory INSTALLATIONPATH/vcpkg/buildtrees/arrayfire/x64-linux-dbg/src/backend/cuda/CMakeFiles/af_cuda_static_cuda_library.dir//. && INSTALLATIONPATH/vcpkg/downloads/tools/cmake-3.19.2-linux/cmake-3.19.2-Linux-x86_64/bin/cmake -D verbose:BOOL=OFF -D build_configuration:STRING=Debug -D generated_file:STRING=INSTALLATIONPATH/vcpkg/buildtrees/arrayfire/x64-linux-dbg/src/backend/cuda/CMakeFiles/af_cuda_static_cuda_library.dir//./af_cuda_static_cuda_library_generated_blas.cu.o -D generated_cubin_file:STRING=INSTALLATIONPATH/vcpkg/buildtrees/arrayfire/x64-linux-dbg/src/backend/cuda/CMakeFiles/af_cuda_static_cuda_library.dir//./af_cuda_static_cuda_library_generated_blas.cu.o.cubin.txt -P INSTALLATIONPATH/vcpkg/buildtrees/arrayfire/x64-linux-dbg/src/backend/cuda/CMakeFiles/af_cuda_static_cuda_library.dir//af_cuda_static_cuda_library_generated_blas.cu.o.Debug.cmake
FAILED: src/backend/cuda/CMakeFiles/af_cuda_static_cuda_library.dir/af_cuda_static_cuda_library_generated_blas.cu.o 
cd INSTALLATIONPATH/vcpkg/buildtrees/arrayfire/x64-linux-dbg/src/backend/cuda/CMakeFiles/af_cuda_static_cuda_library.dir && INSTALLATIONPATH/vcpkg/downloads/tools/cmake-3.19.2-linux/cmake-3.19.2-Linux-x86_64/bin/cmake -E make_directory INSTALLATIONPATH/vcpkg/buildtrees/arrayfire/x64-linux-dbg/src/backend/cuda/CMakeFiles/af_cuda_static_cuda_library.dir//. && INSTALLATIONPATH/vcpkg/downloads/tools/cmake-3.19.2-linux/cmake-3.19.2-Linux-x86_64/bin/cmake -D verbose:BOOL=OFF -D build_configuration:STRING=Debug -D generated_file:STRING=INSTALLATIONPATH/vcpkg/buildtrees/arrayfire/x64-linux-dbg/src/backend/cuda/CMakeFiles/af_cuda_static_cuda_library.dir//./af_cuda_static_cuda_library_generated_blas.cu.o -D generated_cubin_file:STRING=INSTALLATIONPATH/vcpkg/buildtrees/arrayfire/x64-linux-dbg/src/backend/cuda/CMakeFiles/af_cuda_static_cuda_library.dir//./af_cuda_static_cuda_library_generated_blas.cu.o.cubin.txt -P INSTALLATIONPATH/vcpkg/buildtrees/arrayfire/x64-linux-dbg/src/backend/cuda/CMakeFiles/af_cuda_static_cuda_library.dir//af_cuda_static_cuda_library_generated_blas.cu.o.Debug.cmake
cc: error trying to exec 'cc1plus': execvp: No such file or directory
nvcc fatal   : Failed to detect host compiler properties.
CMake Error at af_cuda_static_cuda_library_generated_blas.cu.o.Debug.cmake:220 (message):
  Error generating
  INSTALLATIONPATH/vcpkg/buildtrees/arrayfire/x64-linux-dbg/src/backend/cuda/CMakeFiles/af_cuda_static_cuda_library.dir//./af_cuda_static_cuda_library_generated_blas.cu.o
[351/833] cd INSTALLATIONPATH/vcpkg/buildtrees/arrayfire/x64-linux-dbg/src/backend/cuda/CMakeFiles/af_cuda_static_cuda_library.dir && INSTALLATIONPATH/vcpkg/downloads/tools/cmake-3.19.2-linux/cmake-3.19.2-Linux-x86_64/bin/cmake -E make_directory INSTALLATIONPATH/vcpkg/buildtrees/arrayfire/x64-linux-dbg/src/backend/cuda/CMakeFiles/af_cuda_static_cuda_library.dir//. && INSTALLATIONPATH/vcpkg/downloads/tools/cmake-3.19.2-linux/cmake-3.19.2-Linux-x86_64/bin/cmake -D verbose:BOOL=OFF -D build_configuration:STRING=Debug -D generated_file:STRING=INSTALLATIONPATH/vcpkg/buildtrees/arrayfire/x64-linux-dbg/src/backend/cuda/CMakeFiles/af_cuda_static_cuda_library.dir//./af_cuda_static_cuda_library_generated_cufft.cu.o -D generated_cubin_file:STRING=INSTALLATIONPATH/vcpkg/buildtrees/arrayfire/x64-linux-dbg/src/backend/cuda/CMakeFiles/af_cuda_static_cuda_library.dir//./af_cuda_static_cuda_library_generated_cufft.cu.o.cubin.txt -P INSTALLATIONPATH/vcpkg/buildtrees/arrayfire/x64-linux-dbg/src/backend/cuda/CMakeFiles/af_cuda_static_cuda_library.dir//af_cuda_static_cuda_library_generated_cufft.cu.o.Debug.cmake
FAILED: src/backend/cuda/CMakeFiles/af_cuda_static_cuda_library.dir/af_cuda_static_cuda_library_generated_cufft.cu.o 
cd INSTALLATIONPATH/vcpkg/buildtrees/arrayfire/x64-linux-dbg/src/backend/cuda/CMakeFiles/af_cuda_static_cuda_library.dir && INSTALLATIONPATH/vcpkg/downloads/tools/cmake-3.19.2-linux/cmake-3.19.2-Linux-x86_64/bin/cmake -E make_directory INSTALLATIONPATH/vcpkg/buildtrees/arrayfire/x64-linux-dbg/src/backend/cuda/CMakeFiles/af_cuda_static_cuda_library.dir//. && INSTALLATIONPATH/vcpkg/downloads/tools/cmake-3.19.2-linux/cmake-3.19.2-Linux-x86_64/bin/cmake -D verbose:BOOL=OFF -D build_configuration:STRING=Debug -D generated_file:STRING=INSTALLATIONPATH/vcpkg/buildtrees/arrayfire/x64-linux-dbg/src/backend/cuda/CMakeFiles/af_cuda_static_cuda_library.dir//./af_cuda_static_cuda_library_generated_cufft.cu.o -D generated_cubin_file:STRING=INSTALLATIONPATH/vcpkg/buildtrees/arrayfire/x64-linux-dbg/src/backend/cuda/CMakeFiles/af_cuda_static_cuda_library.dir//./af_cuda_static_cuda_library_generated_cufft.cu.o.cubin.txt -P INSTALLATIONPATH/vcpkg/buildtrees/arrayfire/x64-linux-dbg/src/backend/cuda/CMakeFiles/af_cuda_static_cuda_library.dir//af_cuda_static_cuda_library_generated_cufft.cu.o.Debug.cmake
cc: error trying to exec 'cc1plus': execvp: No such file or directory
nvcc fatal   : Failed to detect host compiler properties.
CMake Error at af_cuda_static_cuda_library_generated_cufft.cu.o.Debug.cmake:220 (message):
  Error generating
  INSTALLATIONPATH/vcpkg/buildtrees/arrayfire/x64-linux-dbg/src/backend/cuda/CMakeFiles/af_cuda_static_cuda_library.dir//./af_cuda_static_cuda_library_generated_cufft.cu.o
  
 I think issue is something related to cuda path instead of vcpkg?

**Comment by 9prady9** [comment]
@EmreOzkose I am from ArrayFire's dev team. I think you are mixing instructions from two sets of workflows.

`libarrayfire-dev` is a development arrayfire package provided on ubuntu which is a self contained apt package with all files necessary for development applications using arrayfire.

vcpkg port is a completely alternative way to fetch arrayfire for applicant development.

There are kind of mutually exclusive routes for using arrayfire for development. You don't need to install `libarrayfire-dev` if you plan to use vcpkg port of arrayfire and vice-versa.

The log shared has a message `nvcc fatal : Failed to detect host compiler properties.` which essentially means something from your CUDA installation is not being picked by vcpkg scripts. I have never used CUDA toolkit via vcpkg, perhaps @jacobkahn has some hints for you or anyone who has used vcpkg CUDA port. I do think it is an environment issue though.

**Comment by jacobkahn** [comment]
@EmreOzkose — as @9prady9 mentioned, `libarrayfire-dev` is an apt package that's orthogonal to a vcpkg installation and shouldn't be used in conjunction with it.

It's not immediately obvious what the issue is given the nvcc error message - a quick search gave a bunch of different potential causes (running out of disk space, etc) — either way, it doesn't look like an issue with vcpkg and looks like an internal nvcc compiler error.

**Comment by JackBoosY** [comment]
`cc: error trying to exec 'cc1plus': execvp: No such file or directory`

Did you installed g++ using command `sudo apt-get install g++`?

**Comment by EmreOzkose** [comment]
Running this command helped me, thank you. 
`sudo apt-get install libarrayfire-dev`

**Comment by jacobkahn** [comment]
@EmreOzkose — `sudo apt-get install libarrayfire-dev` is wrong and will install an old version of the ArrayFire CPU backend. That's not a vcpkg installation.

**Comment by EmreOzkose** [comment]
I tried a lot of things. In the end, they are all mixed up :). However the last thing that I tired was `apt-get install libarrayfire-dev`. After that, I didn't get above error, but another one. I could not deal with that and tried installing from source. That worked.

**Comment by JackBoosY** [comment]
Please remove libarrayfire-dev temporary and re-install arrayfire using vcpkg, and provide me the failure log _INSTALLATIONPATH/vcpkg/buildtrees/arrayfire/install-x64-linux-dbg-out.log_.

Without log, I can't figure out why this issue happenend.

**Comment by JackBoosY** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
