### ISSUE TITLE
[libpqxx] build failure

### ISSUE THREAD

**Issue by gkellerer** [microsoft/vcpkg#15979]
**Host Environment**
- OS: Windows
- Compiler: Visual Studio 2017, V15.9.28307.1274

**To Reproduce**
`./vcpkg install libpqxx`

**Failure logs** 
```
-- Using cached C:/dev/vcpkg/downloads/jtv-libpqxx-9e55cea0116febb5c536ed18ede9a7b2c647e631.tar.gz
-- Cleaning sources at C:/dev/vcpkg/buildtrees/libpqxx/src/b2c647e631-5d91723e5b.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/dev/vcpkg/downloads/jtv-libpqxx-9e55cea0116febb5c536ed18ede9a7b2c647e631.tar.gz
-- Using source at C:/dev/vcpkg/buildtrees/libpqxx/src/b2c647e631-5d91723e5b.clean
-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:145 (message):
    Command failed: C:/dev/vcpkg/downloads/tools/cmake-3.19.2-windows/cmake-3.19.2-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v -j5
    Working Directory: C:/dev/vcpkg/buildtrees/libpqxx/x86-windows-dbg
    See logs for more information:
      C:\dev\vcpkg\buildtrees\libpqxx\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:27 (vcpkg_build_cmake)
  ports/libpqxx/portfile.cmake:18 (vcpkg_install_cmake)
  scripts/ports.cmake:128 (include)
```

**Additional context**
[install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/5904055/install-x86-windows-dbg-out.log)

**Comment by JackBoosY** [comment]
Please update your vcpkg to the latest then retry.

Thanks.

**Comment by gkellerer** [comment]
Good morning,

i updated the archive and compiled vcpkg again but the error still is the same.

Thanks,
Georg

Von: Jack·Boos·Yu <notifications@github.com>
Gesendet: Dienstag, 2. Februar 2021 04:06
An: microsoft/vcpkg <vcpkg@noreply.github.com>
Cc: Kellerer, Georg (LfU) <Georg.Kellerer@lfu.bayern.de>; Author <author@noreply.github.com>
Betreff: Re: [microsoft/vcpkg] [libpqxx] build failure (#15979)


Please update your vcpkg to the latest then retry.

Thanks.

**Comment by JackBoosY** [comment]
Good morning @gkellerer, can you please provide the failure logs again?

Thanks.

**Comment by gkellerer** [comment]
[install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/5910062/install-x86-windows-dbg-out.log)

**Comment by gkellerer** [comment]
File from 20210202 7:40 added

**Comment by JackBoosY** [comment]
Confirmed.

**Comment by JackBoosY** [comment]
@tomlankhorst  Can you please take a look? It seems that your update breaks the build.

**Comment by JackBoosY** [comment]
Fixed in upstream, PR: https://github.com/jtv/libpqxx/pull/406.
Will update libpqxx to fix this issue.

**Comment by tomlankhorst** [comment]
Thank you @JackBoosY
