### ISSUE TITLE
Linking against glfw in CMake when lib may have been installed using vcpkg

### ISSUE THREAD

**Issue by NauticalMile64** [Microsoft/vcpkg#1597]
I am trying to figure out how to load and link against `glfw` when the package might have been loaded in one of two ways:

```
find_package(GLFW3) # First try to find using the find_package method (works with vcpkg)

if(NOT GLFW3_FOUND) # Works with some other methods
	message(STATUS "GLFW3 not found... Searching using pkg-config")
	find_package(PkgConfig REQUIRED)
	pkg_search_module(GLFW REQUIRED glfw3)
	message(STATUS "GLFW_FOUND=${GLFW_FOUND}")

	find_library(GLFW_LIBRARY NAMES glfw3)
	message(STATUS "GLFW_LIBRARY=${GLFW_LIBRARY}")
	message(STATUS "GLFW_LIBRARY_DIRS=${GLFW_LIBRARY_DIRS}")
endif()

#...#

include_directories (
	...
	${GLFW_INCLUDE_DIRS}
	...
)

link_directories (
	${GLFW_LIBRARY_DIRS}
)

#...#

target_link_libraries (
	target1
	target2
	glfw # <-- I don't really understand what this is; it's not a cmake variable anyway.
	${GLFW_STATIC_LIBRARIES}
	${OTHER_LIBRARY1}
	${OTHER_LIBRARY2}
)

```

I inserted the `glfw` argument as suggested by @jasjuang  in issue #1425, but the build doesn't pass anymore on linux (see [report here](https://travis-ci.org/louis-langholtz/PlayRho/jobs/261177788)). It reports `cannot find -lglfw`.

How can I change this code so it consistently links the library, regardless of the method used to load it? I also would like to avoid any `vcpkg`-specific checks.

**Comment by jasjuang** [comment]
It's lower case `find_package(glfw3)`. I don't think `find_package(GLFW3)` works with vcpkg.

Also I suggest you to use `target_include_directories` instead of `include_directories`. I believe `include_directories` is soon going to be depreciated.

**Comment by NauticalMile64** [comment]
@jasjuang Thanks for your suggestions.

Uppercase library names are working (for `glew` also) but I'll keep this in mind if there are any other problems in the future. I guess this is really a CMake issue (or my misunderstanding of CMake). I'll close this issue, but I've also [posted a question on SO about this](https://stackoverflow.com/q/45524666/1542146) if you have time to take a look.
