### ISSUE TITLE
[New Port Request] <ZBAR>

### ISSUE THREAD

**Issue by JaosonMa** [microsoft/vcpkg#15970]
Library name: 
ZBAR
Library description:
 跟zxing一样属于开源的二维码/条码识别库 
Source repository URL:
https://github.com/ZBar/ZBar
Project homepage (if different from the source repository):
https://github.com/ZBar/ZBar
Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by JackBoosY** [comment]
Duplicated to #15968.
