### ISSUE TITLE
llvm:x64-windows build failure

### ISSUE THREAD

**Issue by tfiner** [microsoft/vcpkg#15987]
**Host Environment**
- OS: Windows 10
- Compiler: Visual Studio 2019 16.8.4

**To Reproduce**
`.\vcpkg.exe install llvm:x64-windows`

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

**Additional context**
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/5906636/install-x64-windows-dbg-out.log)
  Vcpkg version: 2021-01-13-unknownhash

Update:
I took out the prefer ninja bit from the port file, to get more information (is there a command line way to do this?  That'd be handy since ninja seems to swallow all useful debug information).

I got this:
`(ClCompile target) -> 
         C:\Work\vcpkg\buildtrees\llvm\src\org-11.0.0-9a84d27ce8.clean\llvm\include\llvm\DebugInfo\PDB\DIA\DIASupport.h(25,10): fatal error C1083: Cannot open include file: 'atlbase.h': No such file or directory (compiling source file C:\Work\vcpkg\buildtrees\llvm\src\org-11.0.0-9a84d27ce8.clean\llvm\lib\DebugInfo\PDB\PDB.cpp) [C:\Work\vcpkg\buildtrees\llvm\x64-windows-dbg\lib\DebugInfo\PDB\LLVMDebugInfoPDB.vcxproj]`

I initially tried to install llvm from a prompt set to use VS 2019 build tools, for which I do not have ATL or MFC installed.  Pretty bizarre that LLVM would need those headers?

**Comment by NancyLi1013** [comment]
Hi @tfiner 

Thanks for posting this issue.

Could you please try to install the ATL libs corresponding to your build tools version via Visual Studio Installer?

![Capture](https://user-images.githubusercontent.com/46708020/106562763-beac5780-6565-11eb-802b-14088ef3b3f2.PNG)

**Comment by tfiner** [comment]
I did this right after I filed it, and it built everything correctly!

**Comment by NancyLi1013** [comment]
Thanks for your feedback. Closing it for now.
