### ISSUE TITLE
[New Port Request] Libzdb

### ISSUE THREAD

**Issue by gansaihua** [microsoft/vcpkg#15982]
Library name: libzdb

Library description:
A small, easy to use Open Source Database Connection Pool Library with the following features:
Thread safe Database Connection Pool
Connect to multiple database systems
Zero runtime configuration, connect using a URL scheme
Supports MySQL, PostgreSQL, SQLite and Oracle

Source repository URL: http://www.tildeslash.com/libzdb/

Project homepage (if different from the source repository): 

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
