### ISSUE TITLE
[openimageio] Runtime crash due to incorrect dll naming

### ISSUE THREAD

**Issue by mathijs727** [microsoft/vcpkg#15981]
**Describe the bug**
The CMakeLists.txt in the OpenImageIO project sets `CMAKE_DEBUG_POSTFIX` to an empty string by default. This causes the debug lib/dll files to have the same names as the release binaries. For the lib files this is ok because `find_package(...)` will point CMake to the right files. For the dll files this is problematic though because it will always pick the same dll independent of whether the program links to the debug or release library files (it just picks whatever comes first in the search path). In practice this causes access violation errors as a result of ABI incompatibility.

**Fix**
This can be fixed by setting a non-empty debug post fix by passing `-DCMAKE_DEBUG_POSTFIX=DEBUG_POSTFIX_HERE` to `vcpkg_configure_cmake` in the `portfile.cmake` of OpenImageIO.

**Environment**
- OS: Windows 10
- Compiler: MSVC 16.8.4

**Comment by JackBoosY** [comment]
Can you provide a sample projec to repro this?

Thanks.

**Comment by Neumann-A** [comment]
> it just picks whatever comes first in the search path

So why is your search path broken in that way? 

> OpenImageIO project sets CMAKE_DEBUG_POSTFIX to an empty string by default. 
 
If this is a real issue this is an upstream issue but nevertheless I don't think it is an issue at all. It just a totally messed up `PATH` variable somehow.

**Comment by JackBoosY** [comment]
Agreed with @Neumann-A

**Comment by PhoebeHui** [comment]
@mathijs727, please reopen this issue and provide the repro code if it still be a problem for you.
