### ISSUE TITLE
[New Port Request] Open3D

### ISSUE THREAD

**Issue by ChaimDryzun1980** [microsoft/vcpkg#15980]
Library name:
Open3D

Library description:
open-source library that supports rapid development of software that deals with 3D data

Source repository URL:
https://github.com/intel-isl/Open3D

Project homepage (if different from the source repository):
http://www.open3d.org/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by cenit** [comment]
https://github.com/microsoft/vcpkg/pull/12199

I did it a long time ago, but it was never merged.

**Comment by cenit** [comment]
@JonLiu1993 I'd remove the info:good-first-issue tag 😄 . It's a very complicated port. Very much...

**Comment by JonLiu1993** [comment]
@cenit ,Thank you so much for your continued contributions, it's great！

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue and continue above PR, but we're closing it for now.
