### ISSUE TITLE
Add Thrift

### ISSUE THREAD

**Issue by madduci** [Microsoft/vcpkg#16]
It would be great to have Apache Thrift in the available list of packages

**Comment by josuegomes** [comment]
I'm working on a Thrift port. 

Leaving this as reference for myself:

`cmake -G "Visual Studio 14 2015" -DWITH_SHARED_LIB=off -DCMAKE_TOOLCHAIN_FILE=c:\Projects\vcpkg\scripts\buildsystems\vcpkg.cmake -DBUILD_TESTING=off -DBUILD_JAVA=off -DBUILD_C_GLIB=off -DBUILD_PYTHON=off -DBUILD_HASKELL=off -DBUILD_TUTORIALS=off 
`

@ras0219-msft Thrift has no support for dynamic libraries on Windows. How do I politely block dynamic build on the portfile?

**Comment by ras0219-msft** [comment]
For libraries that only support dynamic or static _library_ linkage, we can just redirect to the style that is supported [1]. Note that this should not be done for CRT linkage, if that proves to be an issue.

[1] https://github.com/Microsoft/vcpkg/blob/89ad7d6b22e71ed058c2386c147154603da4bee9/ports/cryptopp/portfile.cmake#L1-L4

**Comment by atkawa7** [comment]
@ras0219-msft thrift  has been added

**Comment by bagong** [comment]
I am sorry to report a problem delayed (and I have contributed to it ;) ): PROGNAME=win_flex and PROGNAME=win_bison apparently trigger downloads to be extracted to tools\winflex and tools\win_bison. As a consequence the PATHS-setting pointing to `winflexbison` are wrong. A consequence I observed now, is that a FindBison- and FindFlex-cmake module will not find the executables automatically. So I think the two paths statements have to be adjusted.
Opposed to what I thought PATHS does not *set* a directory, but just stores the folderinformation determined by other factors (PROGNAME and internal structure of downloaded archive, and SUBFOLDERS, it seems)

**Comment by atkawa7** [comment]
Thanks  @bagong will definitely look at it. Just wondering what happens when you use --head

**Comment by madduci** [comment]
That's fantastic!

**Comment by atkawa7** [comment]
@ras0219-msft Could you close this?
