### ISSUE TITLE
Add C++/WinRT

### ISSUE THREAD

**Issue by profiler-bg** [Microsoft/vcpkg#160]
For the devs out there that want to write UWP apps with C++ and no language extensions, this new library would be awesome. Having it on vcpkg would reduce the setup time.

repo: https://github.com/Microsoft/cppwinrt

**Comment by sdcb** [comment]
I think we already have one here:
https://github.com/Microsoft/vcpkg/tree/master/ports/cppwinrt
PR here:
https://github.com/Microsoft/vcpkg/pull/154

Please update vcpkg to newest version and search again.

**Comment by profiler-bg** [comment]
Sorry, didn't see it, as it wasn't labelled as a request.
