### ISSUE TITLE
[libLAS] GDAL support

### ISSUE THREAD

**Issue by grandmaster789** [microsoft/vcpkg#16005]
****

The pointclouds I work with have specific requirements for georeferencing; when using libLAS I need its optional WITH_GDAL feature enabled (it's off by default); however the vcpkg port doesn't provide this option. It would certainly be nice though.

**Proposed solution**
Please add an option for GDAL support (libLAS already provides a WITH_GDAL option, I *think* this could be exposed as a vcpkg port option)

**Comment by dg0yt** [comment]
"As of 2018, libLAS has been replaced by the PDAL project and it is in hibernation or maintenance mode." 
https://liblas.org/

**Comment by dg0yt** [comment]
I think this change won't come for port liblas, and this issue can be closed.
