### ISSUE TITLE
[log4cxx ] CMake fails for Linux build when log4cxx is specified as a package

### ISSUE THREAD

**Issue by SergeiDelov** [microsoft/vcpkg#16006]
Using Visual Studio 19 and WSL.

CMakeLists.txt fragment:
find_package(log4cxx CONFIG REQUIRED)
target_link_libraries(${PROJECT_NAME} PRIVATE log4cxx)

CMake output:
1> [CMake] CMake Error at /mnt/c/vcpkg/scripts/buildsystems/vcpkg.cmake:433 (_add_library):
1> [CMake]   Target "XXX" links to target "EXPAT::EXPAT" but the target was not found.
1> [CMake]   Perhaps a find_package() call is missing for an IMPORTED target, or an
1> [CMake]   ALIAS target is missing?

I updated all vcpkg packages project uses, it didn't help.

Attempt to add expat
    find_package(expat CONFIG REQUIRED)
    target_link_libraries(${PROJECT_NAME}  PRIVATE expat::expat)
didn't help either.

**Comment by Hoikas** [comment]
`EXPAT::EXPAT` is the name of the built-in target. The config target is `expat::expat`.

**Comment by SergeiDelov** [comment]
> EXPAT::EXPAT is the name of the built-in target. The config target is expat::expat.
Not sure what this statement means. I do not use expat directly. 

"find_package(expat CONFIG REQUIRED)" is irrelevant to log4cxx config problem, it was action in distress.

Something is wrong with log4cxx Linux config.

**Comment by SergeiDelov** [comment]
This is more generic problem. I didn't notice all error messages -- there are a lot of included CMakeLists.txt files.

1> [CMake]   Target "Cn" links to target "OpenSSL::SSL" but the target was not
1> [CMake]   Target "Cn" links to target "OpenSSL::Crypto" but the target was not
1> [CMake]   Target "EO" links to target "OpenSSL::SSL" but the target was not
1> [CMake]   Target "EO" links to target "OpenSSL::Crypto" but the target was
1> [CMake]   Target "EO" links to target "ZLIB::ZLIB" but the target was not

The common feature between these targets is  -- our CMake files do not include these packages directly.

cmake version 3.17.20032601-MSVC_2

**Comment by NancyLi1013** [comment]
Hi @SergeiDelov 

Thanks for posting this issue.

```
 [CMake] CMake Error at /mnt/c/vcpkg/scripts/buildsystems/vcpkg.cmake:433 (_add_library):
 [CMake] Target "XXX" links to target "EXPAT::EXPAT" but the target was not found.
```
This is due to incorrect usage of expat in log4cxx. Just needs to update expat.patch and add find_dependency(expat) in log4cxxConfig.cmake.

I have submitted a PR to fix this issue. Could you please help test if this can work fine for you?

**Comment by SergeiDelov** [comment]
log4cxx is blocking issue for me, will test fix ASAP.

**Comment by Hoikas** [comment]
The failure you experienced above is unrelated to log4cxx and expat. Don't use your Windows vcpkg from WSL. There is a performance penalty for doing this under WSL2, and you *will* encounter errors. Vcpkg cannot build your x64-linux ports on Windows nor can it build your Windows ports on Linux, so you will see errors when trying to upgrade.
