### ISSUE TITLE
vcpkg install bzip2  error:no such remote ref 75a94bea3918e612b879d6a11ca64b8689526147

### ISSUE THREAD

**Issue by JaosonMa** [microsoft/vcpkg#16015]
**Describe the bug**
install bzip2 
but Error:

**Environment**
- OS: [Linux ubuntu 4.15]
- Compiler: gxx 6.3

**To Reproduce**
1. ./vcpkg install bzip2
2. See error

> -- Fetching https://sourceware.org/git/bzip2.git...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:108 (message):
    Command failed: /usr/bin/git fetch https://sourceware.org/git/bzip2.git 75a94bea3918e612b879d6a11ca64b8689526147 --depth 1 -n
    Working Directory: /home/ubuntu/qqm/vcpkg/downloads/git-tmp
    Error code: 128
    See logs for more information:
      /home/ubuntu/qqm/vcpkg/buildtrees/bzip2/git-fetch-x64-linux-err.log

> Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_git.cmake:91 (vcpkg_execute_required_process)
  ports/bzip2/portfile.cmake:1 (vcpkg_from_git)
  scripts/ports.cmake:128 (include)

Error: Building package bzip2:x64-linux failed with: BUILD_FAILED

**Failure logs** 

> cat /home/ubuntu/qqm/vcpkg/buildtrees/bzip2/git-fetch-x64-linux-err.log
error: no such remote ref 75a94bea3918e612b879d6a11ca64b8689526147

**Comment by JaosonMa** [comment]
@JackBoosY @NancyLi1013

**Comment by JackBoosY** [comment]
Does this issue resolved?
