### ISSUE TITLE
vcpkg install x86 system.

### ISSUE THREAD

**Issue by eubean7** [microsoft/vcpkg#16017]
vcpkg install libheif. then
![image](https://user-images.githubusercontent.com/75243276/106726276-8a13cb00-664d-11eb-87a2-6be5ba8a6d18.png)

why install x86-windows? my computer is x64.
please let me know for newbie.

**Comment by Osyotr** [comment]
See #53

**Comment by eubean7** [comment]
Thank for your help, i solving this problem!!

**Comment by eubean7** [comment]
> See #53

awesome! how can you find it?

**Comment by eubean7** [comment]
> See #53
awesome! how can you find it?
