### ISSUE TITLE
[fontconfig:x64-windows-static] build failure

### ISSUE THREAD

**Issue by zcream** [microsoft/vcpkg#16016]
**Host Environment**
- OS: Window 7 x64
- Vcpkg version: 2021-01-13-unknownhash
- fontconfig[core]:x64-windows-static -> 2.13.1#3

**To Reproduce**
`./vcpkg install fontconfig`

**Failure logs** 
-- Extracting source C:/Users/Administrator/vcpkg/downloads/fontconfig-fontconfig-844d8709a1f3ecab45015b24b72dd775c13b2421.tar.gz
-- Applying patch remove_tests.patch
-- Applying patch build.patch
-- Applying patch build2.patch
-- Applying patch disable-install-data.patch
-- Applying patch fix_def_dll_name.patch
-- Using source at C:/Users/Administrator/vcpkg/buildtrees/fontconfig/src/75c13b2421-828c91b8d5.clean
-- Configuring x64-windows-static
-- Using msys root at C:/Users/Administrator/vcpkg/downloads/tools/msys2/e11fa1e2c730d07f
-- Using msys root at C:/Users/Administrator/vcpkg/downloads/tools/msys2/50864d9fae363d6e
-- Generating configure for x64-windows-static
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:108 (message):

    Command failed: C:/Users/Administrator/vcpkg/downloads/tools/msys2/e11fa1e2c730d07f/usr/bin/bash.exe --noprofile --norc --debug -c "autoreconf -vfi"
    Working Directory: C:/Users/Administrator/vcpkg/buildtrees/fontconfig/src/75c13b2421-828c91b8d5.clean/
    Error code: 1
    See logs for more information:
      C:\Users\Administrator\vcpkg\buildtrees\fontconfig\autoconf-x64-windows-static-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:574 (vcpkg_execute_required_process)
  ports/fontconfig/portfile.cmake:25 (vcpkg_configure_make)
  scripts/ports.cmake:128 (include)

Error: Building package fontconfig:x64-windows-static failed with: BUILD_FAILED

**Additional context**
Tried git pull to update portfiles and vcpkg upgrade

**Comment by zcream** [comment]
Also the log from       C:\Users\Administrator\vcpkg\buildtrees\fontconfig\autoconf-x64-windows-st
atic-err.log - 
`autoreconf: Entering directory `.'
autoreconf: running: autopoint --force
/usr/bin/autopoint: line 487: tar: command not found
autopoint: *** infrastructure files for version 0.19.8 not found; this is autopoint from GNU gettext-tools 0.19.8.1
autopoint: *** Stop.
autoreconf: autopoint failed with exit status: 1
`

**Comment by sfhacker** [comment]
Are we still having issues building fontconfig?
We will have a go at it now!
@zcream Have you contacted us before?

**Comment by sfhacker** [comment]
![image](https://user-images.githubusercontent.com/25817529/106754620-4c309a00-6681-11eb-8827-c0185ddab245.png)

If you require further assistance, let us know!

**Comment by zcream** [comment]
@sfhacker  have not contacted you regarding this issue. I think the issue is specific to windows 7. Msys is unable to access tar. I think it's related to this issue. https://github.com/microsoft/vcpkg/issues/15508

**Comment by zcream** [comment]
@sfhacker  just saw your post in the other thread. I am indeed the last poster there.

**Comment by zcream** [comment]
This problem only came up with the latest version of vcpkg. Is there a version conflict in the autotools used in vcpkg infrastructure.
autopoint: *** infrastructure files for version 0.19.8 not found; this is autopoint from GNU gettext-tools 0.19.8.1

**Comment by sfhacker** [comment]
@zcream I can see several issues raised by you!
Are you using Visual Studio (VS) or MSys? If you mix toolchains, you are looking for trouble.
Perhaps you should install gettext before attemping to build fontconfig.

![image](https://user-images.githubusercontent.com/25817529/106769779-71c59f80-6691-11eb-8483-9661337dd34d.png)

**Comment by zcream** [comment]
gettext is already installed.
`PS C:\Users\Administrator\vcpkg> .\vcpkg.exe install gettext
Computing installation plan...
The following packages are already installed:
    gettext[core]:x64-windows-static -> 0.21
Package gettext:x64-windows-static is already installed`

I think vcpkg uses msys as a part of the build.
`-- Configuring x64-windows-static
-- Using msys root at C:/Users/Administrator/vcpkg/downloads/tools/msys2/e11fa1e
2c730d07f
-- Using msys root at C:/Users/Administrator/vcpkg/downloads/tools/msys2/50864d9
fae363d6e
-- Generating configure for x64-windows-static
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:108 (message):`

I use Vs for my build. So its the default settings that vcpkg installs with.

**Comment by zcream** [comment]
I had a separate install of cmake. Which I uninstalled. Then I re-ran bootstrap-vcpkg

I'm back to square one. I have no idea why vcpkg is using msys. I thought it uses that toolchain on its own. Here is the complete dump.

`PS C:\Users\Administrator\vcpkg> .\vcpkg.exe install cairo
Computing installation plan...
The following packages will be built and installed:
    cairo[core]:x64-windows-static -> 1.16.0#8
  * fontconfig[core]:x64-windows-static -> 2.13.1#3
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows-static...
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\arch
ives\79\792c6d69403a0dad134634e59d17fc74f7dd7c47.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\arch
ives\d2\d2e9febf1b441dc931a0559b90a9f06e933a2298.zip
Starting package 1/2: fontconfig:x64-windows-static
Building package fontconfig[core]:x64-windows-static...
-- Using cached C:/Users/Administrator/vcpkg/downloads/fontconfig-fontconfig-844
d8709a1f3ecab45015b24b72dd775c13b2421.tar.gz
-- Cleaning sources at C:/Users/Administrator/vcpkg/buildtrees/fontconfig/src/75
c13b2421-828c91b8d5.clean. Use --editable to skip cleaning for the packages you
specify.
-- Extracting source C:/Users/Administrator/vcpkg/downloads/fontconfig-fontconfi
g-844d8709a1f3ecab45015b24b72dd775c13b2421.tar.gz
-- Applying patch remove_tests.patch
-- Applying patch build.patch
-- Applying patch build2.patch
-- Applying patch disable-install-data.patch
-- Applying patch fix_def_dll_name.patch
-- Using source at C:/Users/Administrator/vcpkg/buildtrees/fontconfig/src/75c13b
2421-828c91b8d5.clean
-- Configuring x64-windows-static
-- Using msys root at C:/Users/Administrator/vcpkg/downloads/tools/msys2/e11fa1e
2c730d07f
-- Using msys root at C:/Users/Administrator/vcpkg/downloads/tools/msys2/50864d9
fae363d6e
-- Generating configure for x64-windows-static
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:108 (message):

    Command failed: C:/Users/Administrator/vcpkg/downloads/tools/msys2/e11fa1e2c
730d07f/usr/bin/bash.exe --noprofile --norc --debug -c "autoreconf -vfi"
    Working Directory: C:/Users/Administrator/vcpkg/buildtrees/fontconfig/src/75
c13b2421-828c91b8d5.clean/
    Error code: 1
    See logs for more information:
      C:\Users\Administrator\vcpkg\buildtrees\fontconfig\autoconf-x64-windows-st
atic-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:574 (vcpkg_execute_required_process)
  ports/fontconfig/portfile.cmake:25 (vcpkg_configure_make)
  scripts/ports.cmake:128 (include)


Error: Building package fontconfig:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: fontconfig:x64-windows-static
  Vcpkg version: 2021-01-13-unknownhash`

**Comment by zcream** [comment]
For some progress, I tried to execute that command manually.

`C:\Users\Administrator\vcpkg\downloads\tools\msys2\e11fa1e2c730d07f\usr\bin\bash.exe --noprofile --norc --debug -c "autoreconf -vfi"
Get-Command: Cannot bind parameter 'CommandType'. Cannot convert value "autoreconf -vfi" to type "System.Management.Automation.CommandTypes". Error: "Unable to
match the identifier name autoreconf -vfi to a valid enumerator name. Specify one of the following enumerator names and try again:
Alias, Function, Filter, Cmdlet, ExternalScript, Application, Script, Configuration, All"
`

At least we know why autoreconf is failing. But I cannot proceed further as I do not understand the build system.

**Comment by sfhacker** [comment]
> Get-Command: Cannot bind parameter 'CommandType'.
> System.Management.Automation.CommandTypes"

Where is this error message coming from?
It looks like you are mixing toolchains here.
Have you tried other alternatives rather than vcpkg? Hopefully comparing alternatives you can figure out what the issue is.

We have had no issues so far. I don't know what else I can advise. I'm lost.
Perhaps your environment is broken or polluted. Try reinstalling it.

> autoreconf (GNU Autoconf) 2.69
> Copyright (C) 2012 Free Software Foundation, Inc.
> License GPLv3+/Autoconf: GNU GPL version 3 or later
> <http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
>
> Written by David J. MacKenzie and Akim Demaille.

**Comment by zcream** [comment]
There is a version of msys inside vcpkg and another one inside git. I started fresh, I removed the vcpkg folder and uninstalled git. I had the same problem with a fresh install.
The next stage is to try a rollback.

`PS C:\vcpkg> .\vcpkg x-history fontconfig
             version          date    vcpkg commit
            2.13.1#2    2020-12-14    887fa81c66c37c5ee184ae9cbb40f7ea6fd7bde1`

`PS C:\vcpkg> git reset 887fa81c66c37c5ee184ae9cbb40f7ea6fd7bde1`

Now if I build fontconfig it will pickup the new version 2.13.1#2 

`PS C:\vcpkg> .\vcpkg.exe install fontconfig
Computing installation plan...
The following packages will be built and installed:
    fontconfig[core]:x64-windows-static -> 2.13.1#3`

How do I install a previous version of fontconfig ?

**Comment by zcream** [comment]
@sfhacker I used the command that failed. 
`C:\Users\Administrator\vcpkg\downloads\tools\msys2\e11fa1e2c730d07f\usr\bin\bash.exe --noprofile --norc --debug -c "autoreconf -vfi"`

I am now trying a fresh install.

> 
> > Get-Command: Cannot bind parameter 'CommandType'.
> > System.Management.Automation.CommandTypes"
> 
> Where is this error message coming from?
> It looks like you are mixing toolchains here.
> Have you tried other alternatives rather than vcpkg? Hopefully comparing alternatives you can figure out what the issue is.
> 
> We have had no issues so far. I don't know what else I can advise. I'm lost.
> Perhaps your environment is broken or polluted. Try reinstalling it.
>

**Comment by zcream** [comment]
https://github.com/microsoft/vcpkg/issues/12321 - this method should be documented. 

`$ mkdir pinned-ports`
`$ git checkout <copied commit> -- ports/<port-name>`
`$ mv ports/<port-name> pinned-ports`
`$ git checkout HEAD -- ports`
`and then proceed to use vcpkg with the additional flag --overlay-ports=./pinned-ports`

I built a previous version of fontconfig and still the same error. Now I will try as a fresh user

**Comment by NancyLi1013** [comment]
Hi @zcream 

Thanks for posting this issue.
Sorry for the late response. 

```
autoreconf: Entering directory .'
autoreconf: running: autopoint --force
/usr/bin/autopoint: line 487: tar: command not found
autopoint: *** infrastructure files for version 0.19.8 not found; this is autopoint from GNU gettext-tools 0.19.8.1
autopoint: *** Stop.
autoreconf: autopoint failed with exit status: 1
```
From the error info you provided above, which is related with your build environment Windows7.

Since it's duplicated to #15508, let's track this issue there.

**Comment by sfhacker** [comment]
@zcream Please avoid duplicating issues next time.
Have you been able to resolve this painful issue?

**Comment by zcream** [comment]
@sfhacker I didnt know it was duplicate when I filed it. I'll definitely take care next time. I'm still working through earlier versions to fix this. I'll post on the other open issue
