### ISSUE TITLE
[tesseract] update to 5.x.x

### ISSUE THREAD

**Issue by Shreeshrii** [microsoft/vcpkg#16019]
Library name: tesseract

New version number: 5.0.0-alpha-20201231

https://github.com/tesseract-ocr/tesseract/releases/tag/5.0.0-alpha-20201231

https://abi-laboratory.pro/?view=timeline&l=tesseract
5.0.0-alpha is only 36% backward compatible.
So vcpkg should have options to build the old 4.1.1 as well as new 5.0.0-alpha (with HEAD_REF master).

Opening a new issue as suggested by @NancyLi1013 in https://github.com/microsoft/vcpkg/issues/10624#event-4283543880

**Comment by JonLiu1993** [comment]
@Shreeshrii ,The latest stable version of tesseract is 4.1.1. 5.0.0 is a pre-release and very unstable. After the upgrade, it may affect the ports that depend on it, so we will not upgrade for the time being. I will upgrade after the latest stable version is released. ,Thanks.

**Comment by Shreeshrii** [comment]
@JonLiu1993 Can you advise what changes I need to make, if I want to create a local port for tesseract5  with  the latest HEAD_REF from master branch?

**Comment by JonLiu1993** [comment]
@Shreeshrii ,Modify it like this and install it locally：
CONTROL:
````
Source: tesseract
Version: 5.0.0
Homepage: https://github.com/tesseract-ocr/tesseract
Description: An OCR Engine that was developed at HP Labs between 1985 and 1995... and now at Google.
Build-Depends: leptonica, libarchive

Feature: training-tools
Description: build training tools
Build-Depends: icu, pango, cairo, fontconfig

Feature: cpu-independed
Description: build on any cpu extension commands support
````
portfile.cmake
````
vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO tesseract-ocr/tesseract
    REF ca114ace387f86821ce061713dc9aa3cc33a3cad #pre-V 5.0.0
    SHA512 017723a2268be789fe98978eed02fd294968cc8050dde376dee026f56f2b99df42db935049ae5e72c4519a920e263b40af1a6a40d9942e66608145b3131a71a2
    HEAD_REF master
    PATCHES
        fix-tiff-linkage.patch
        fix-text2image.patch
        fix-training-tools.patch
)

# The built-in cmake FindICU is better
file(REMOVE ${SOURCE_PATH}/cmake/FindICU.cmake)

string(COMPARE EQUAL "${VCPKG_LIBRARY_LINKAGE}" "static" BUILD_STATIC)

vcpkg_check_features(OUT_FEATURE_OPTIONS FEATURE_OPTIONS
    training-tools  BUILD_TRAINING_TOOLS
)

if("cpu-independed" IN_LIST FEATURES)
    set(TARGET_ARCHITECTURE none)
else()
    set(TARGET_ARCHITECTURE auto)
endif()

vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA
    OPTIONS ${FEATURE_OPTIONS}
        -DSTATIC=${BUILD_STATIC}
        -DUSE_SYSTEM_ICU=True
        -DCMAKE_DISABLE_FIND_PACKAGE_LibArchive=ON
        -DCMAKE_DISABLE_FIND_PACKAGE_OpenCL=ON
        -DLeptonica_DIR=YES
        -DTARGET_ARCHITECTURE=${TARGET_ARCHITECTURE}
)

vcpkg_install_cmake()

vcpkg_fixup_cmake_targets(CONFIG_PATH cmake)
file(READ ${CURRENT_PACKAGES_DIR}/share/tesseract/TesseractConfig.cmake TESSERACT_CONFIG)
string(REPLACE "find_package(Leptonica REQUIRED)"
               "find_package(Leptonica REQUIRED)
find_package(OpenSSL REQUIRED)
find_package(ZLIB REQUIRED)
find_package(BZip2 REQUIRED)
find_package(LibXml2 REQUIRED)
find_package(zstd REQUIRED)
find_package(LibLZMA REQUIRED)" TESSERACT_CONFIG "${TESSERACT_CONFIG}")
file(WRITE ${CURRENT_PACKAGES_DIR}/share/tesseract/TesseractConfig.cmake "${TESSERACT_CONFIG}")

vcpkg_copy_tools(TOOL_NAMES tesseract AUTO_CLEAN)

if("training-tools" IN_LIST FEATURES)
    list(APPEND TRAINING_TOOLS
        ambiguous_words classifier_tester combine_tessdata
        cntraining dawg2wordlist mftraining shapeclustering
        wordlist2dawg combine_lang_model lstmeval lstmtraining
        set_unicharset_properties unicharset_extractor text2image
    )
    vcpkg_copy_tools(TOOL_NAMES ${TRAINING_TOOLS} AUTO_CLEAN)
endif()

vcpkg_copy_pdbs()

file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/include)

# Handle copyright
file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)

````

**Comment by JonLiu1993** [comment]
You can directly copy my control file and portfile file to your local corresponding file and build

**Comment by Shreeshrii** [comment]
Thank you for the files. I tried using them on AArch64 but the build is failing - relative to webP. I opened a new issue for that at https://github.com/microsoft/vcpkg/issues/16040

I also tried using --head option in Github Actions. That too is failing.
https://github.com/Shreeshrii/tesseract/actions/runs/536880153

Without the --head option, the SHA didn't match.
https://github.com/Shreeshrii/tesseract/actions/runs/536925557

I am now trying after changing the SHA for REF.
https://github.com/Shreeshrii/tesseract/actions/runs/537076508

**Comment by Shreeshrii** [comment]
My workaround for building tesseract 5 on windows is to use vcpkg for leptonica and then build tesseract from --head of master branch using cmake. https://github.com/tesseract-ocr/tesseract/blob/master/.github/workflows/vcpkg.yml

**Comment by JonLiu1993** [comment]
@Shreeshrii ,It looks great, but I'm sorry, I don't know the ymal file you wrote very well, so I can't give my advice.

**Comment by Shreeshrii** [comment]
Tesseract 5.0.0 has been released. Please update vcpkg to use the new version.

**Comment by huhuang03** [comment]
Yes, tesseract readme has blow:

```
Major version 5 is the current stable version and started with release 5.0.0 on November 30, 2021. Newer minor versions and bugfix versions are available from GitHub.
```

Any plan for update?

**Comment by quaesitor-scientiam** [comment]
How  can I get my vcpkg Tesseract to update to 5.1?  I tried  with --head and it still only does 4.1.1

**Comment by quaesitor-scientiam** [comment]
How long before 5.1 is available to install?

**Comment by quaesitor-scientiam** [comment]
vcpkg search tesseract still only brings back 4.1.1

**Comment by JonLiu1993** [comment]
@quaesitor-scientiam ,I will update tesseract to 5.1.0

**Comment by quaesitor-scientiam** [comment]
Performed a git pull this morning 
Still no 5.1 listed
```
PS S:\GitRepro\vcpkg> vcpkg search tesseract
ffmpeg[tesseract]                         Tesseract, needed for ocr filter
tesseract                4.1.1#10         An OCR Engine that was developed at HP Labs between 1985 and 1995... and n...
tesseract[cpu-independed]                 build on any cpu extension commands support
tesseract[training-tools]                 build training tools
The result may be outdated. Run `git pull` to get the latest results.
```

**Comment by quaesitor-scientiam** [comment]
![image](https://user-images.githubusercontent.com/60949191/164453627-02202907-61d7-4b64-b0b2-6c32c96f9b70.png)

**Comment by JonLiu1993** [comment]
> ![image](https://user-images.githubusercontent.com/60949191/164453627-02202907-61d7-4b64-b0b2-6c32c96f9b70.png)

@quaesitor-scientiam, I'm really sorry, when I submitted this pr, the test was successful locally, but when I submitted it to CI for testing, it couldn't be tested successfully on both windows and linux, and I tried to solve it in the past but there is still a block, I Will try to solve these problems as soon as possible, I hope you can understand

**Comment by quaesitor-scientiam** [comment]
Thanks for the update.  I am not familiar with how the Github CI works and how to see status.  Eventually I might figure that out.

**Comment by bakashigure** [comment]
I overwrote my local config directly with these changes in this pr  https://github.com/microsoft/vcpkg/pull/24114 and it works fine
![image](https://user-images.githubusercontent.com/33803916/165137846-e05bf9ab-fac7-4c0c-adbd-938a00c030c2.png)

It's hard to understand why CI tests fail...

**Comment by JonLiu1993** [comment]
> I overwrote my local config directly with these changes in this pr #24114 and it works fine ![image](https://user-images.githubusercontent.com/33803916/165137846-e05bf9ab-fac7-4c0c-adbd-938a00c030c2.png)
> 
> It's hard to understand why CI tests fail...

Yes，I'm also confused, I did the 5.1.0 version update locally early on, but it's wrong on CI I'm confused, I tried to modify it, but I put it on hold for other things in the middle

**Comment by venabled** [comment]
Also for reference, 4.1.1 won't build on mac-osx arm64, their cmake tooling tries to optimize for an architecture that doesn't exist

**Comment by amitdo** [comment]
@JonLiu1993

Hi,

Tesseract is the 10th most stared project among the C++ based projects in GitHub.

Tesseract version 5.2.0 was release a few days ago. Could you please finish the work you started in February?

**Comment by JonLiu1993** [comment]
> @JonLiu1993
> 
> Hi,
> 
> Tesseract is the 10th most stared project among the C++ based projects in GitHub.
> 
> Tesseract version 5.2.0 was release a few days ago. Could you please finish the work you started in February?

I will finished it
