### ISSUE TITLE
[gRPC] Allow gRPC to build with BUILD_SHARED_LIBS

### ISSUE THREAD

**Issue by IIFE** [microsoft/vcpkg#16026]
Hi,

I've noticed the gRPC port only allows gRPC to be built as a static lib:
```
if(VCPKG_TARGET_IS_WINDOWS)
    vcpkg_check_linkage(ONLY_STATIC_LIBRARY)
endif()
```

Is there a specific reason for this? According to [this](https://github.com/grpc/grpc/pull/25106#issuecomment-769749557) comment the `BUILD_SHARED_LIBS` can be used to build gRPC as a DLL. Would it be possible to do that please?

Thanks.

**Comment by JonLiu1993** [comment]
@IIFE ,Thanks for posting this issue,Currently grpc does not officially support BUILD_SHARED_LIBS, you can ask questions in upstream.

**Comment by IIFE** [comment]
@JonLiu1993 They don't officially support maintaining issues related to BUILD_SHARED_LIBS, but they do allow it to be built with that option. Is it possible to add that as an option to the vcpkg port so that consumers can choose to use BUILD_SHARED_LIBS?

**Comment by JackBoosY** [comment]
@IIFE According to the link you provided, the official said that building grpc as a dynamic library will be unstable, and we cannot guarantee its stability too.
If you want to do this, please delete the following content in _VCPKG_ROOT/ports/grpc/portfile.cmake_ and rebuild grpc:
```cmake
if(VCPKG_TARGET_IS_WINDOWS)
    vcpkg_check_linkage(ONLY_STATIC_LIBRARY)
endif()
```

**Comment by JonLiu1993** [comment]
@IIFE ,I will close this issue, if you still have questions, please reopen the issue
