### ISSUE TITLE
[New Port Request] <MLT>

### ISSUE THREAD

**Issue by pengguoqing** [microsoft/vcpkg#16024]
Library name:
MLT

Library description:
MLT is a LGPL multimedia framework designed for television broadcasting

Source repository URL:
https://github.com/mltframework/mlt.git

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
Develop  video and audio editor in VS2019

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
