### ISSUE TITLE
CMake Error "cannot specify link libraries for target main which is not build by this project"

### ISSUE THREAD

**Issue by ViniDalvino** [microsoft/vcpkg#16023]
I am trying to use nana with cmake however cmake throw me this error:
```
Severity	Code	Description	File	Line	Suppression State
Error		CMake Error at C:\Users\ASD\Project\cplusplus\projet\Consulat Proj\CMakeLists.txt:9 (target_link_libraries):
  Cannot specify link libraries for target "main" which is not built by this
  project.	C:\Users\ASD\Project\cplusplus\projet\Consulat Proj\CMakeLists.txt	9	
```
Here is my cmakelist:
```cmake
# CMakeList.txt : CMake project for Consulat Proj, include source and define
# project specific logic here.
#
cmake_minimum_required (VERSION 3.8)

project ("Consulat Proj")

# find libraries
find_package(unofficial-nana CONFIG REQUIRED)
target_link_libraries(main PRIVATE unofficial::nana::nana)

# Add source to this project's executable.
add_executable (CMakeTarget "Consulat Proj.cpp" "Consulat Proj.h")

# TODO: Add tests and install targets if needed.
```

I tried using the command `vcpkg integrate install` to integrate to visual studio cmake however I still have the error.

**Comment by JonLiu1993** [comment]
@ViniDalvino ,Are you using Windows? What is the VS version? Nana default triplets or other? I need you to provide this information to reproduce your problem.Thanks

**Comment by JackBoosY** [comment]
Use the following code instead:
```cmake
# CMakeList.txt : CMake project for Consulat Proj, include source and define
# project specific logic here.
#
cmake_minimum_required (VERSION 3.8)

project ("Consulat Proj")

# find libraries
find_package(unofficial-nana CONFIG REQUIRED)

# Add source to this project's executable.
add_executable (CMakeTarget "Consulat Proj.cpp" "Consulat Proj.h")
target_link_libraries(CMakeTarget PRIVATE unofficial::nana::nana)

# TODO: Add tests and install targets if needed.
```

**Comment by ViniDalvino** [comment]
@JonLiu1993 how do I get the visual studio version that I’m running

**Comment by JonLiu1993** [comment]
@ViniDalvino ,It can be viewed like the following, but I suggest you to try again as @JackBoosY  suggested CMakeLists. Maybe your problem is that target_link_libraries(main PRIVATE unofficial::nana::nana) is written in the wrong location
![捕获](https://user-images.githubusercontent.com/63675417/106980789-c6edd800-679b-11eb-987e-f8937275d70b.PNG)

**Comment by JonLiu1993** [comment]
@ViniDalvino ,Has the problem been solved？

**Comment by ViniDalvino** [comment]
nah I didn't tried to solve the issue - I ambandoned the problem. thanks for worrying and helping me.

**Comment by ViniDalvino** [comment]
> @ViniDalvino ,Has the problem been solved？

nah I gave up on it when I closed the issue however I now need nana so I reopneed the issue as I no longer gave up on the issue

**Comment by ViniDalvino** [comment]
oh annd my visual studio version is the following
![image](https://user-images.githubusercontent.com/37189791/106986447-5b731e80-6739-11eb-86bf-10b97cd28604.png)

**Comment by ViniDalvino** [comment]
is there a magic cmake command/function that include all the vcpkg module to make thing simple?

**Comment by JonLiu1993** [comment]
Have you tried @JackBoosY 's suggestion?

**Comment by ViniDalvino** [comment]
yes and it didn't worked.

**Comment by JackBoosY** [comment]
@ViniDalvino Please see [official docs](https://cmake.org/cmake/help/latest/command/target_link_libraries.html) about `target_link_libraries`.
