### ISSUE TITLE
[New Port Request] <libopenshot>

### ISSUE THREAD

**Issue by pengguoqing** [microsoft/vcpkg#16025]
Library name:
libopenshot

Library description:
OpenShot Video Library (libopenshot) is a free, open-source C++ library dedicated to delivering high quality video editing, animation, and playback solutions to the world

Source repository URL:
https://github.com/OpenShot/libopenshot.git

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
Develop video and audio editor software in VS2019

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
