### ISSUE TITLE
How do I link to Boost statically on Windows?

### ISSUE THREAD

**Issue by BullyWiiPlaza** [microsoft/vcpkg#16049]
For my `Windows` `Visual C++` application I want to link to `Boost` statically (e.g. merge all `Boost` `DLL`s into my `EXE`). I installed `Boost` with `vcpkg install Boost:x64-windows-static`. My build system is `CMake`. By default, `Visual Studio` links to all libraries dynamically so I receive my `EXE` and some `DLL`s.

My `CMakeLists.txt`:
```
find_package(Boost COMPONENTS filesystem REQUIRED)
include_directories(${Boost_INCLUDE_DIRS})
# ...
target_link_libraries(${TARGET_NAME} ${Boost_LIBRARIES})
```

In my `CMakeSettings.json` I see the value of `VCPKG_TARGET_TRIPLET` being set to `x64-windows` which would explain why certain libraries are linked dynamically by default. If I change this setting to `x64-windows-static` e.g. `cURL` is now linked statically and no more `cURL` `DLL`s appear in the build folder. However, with `Boost` this doesn't seem so simple. I'm getting
```
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in main.obj 	D:\Cpp\MyProject\MyProject	D:\Cpp\MyProject\boost_filesystem-vc140-mt.lib(path_traits.obj)	1
```
I furthermore found [this](https://blog.iany.me/2017/03/vcpkg-static-linking/) post and it essentially suggests the following `CMakeLists.txt` changes:
```
if(MSVC)
  string(REPLACE "/MD" "/MT" CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS})
  string(REPLACE "/MD" "/MT" CMAKE_CXX_FLAGS_DEBUG ${CMAKE_CXX_FLAGS_DEBUG})
  string(REPLACE "/MD" "/MT" CMAKE_CXX_FLAGS_RELEASE ${CMAKE_CXX_FLAGS_RELEASE})
else()
  set(Boost_USE_STATIC_LIBS ON)
  set(Boost_USE_STATIC_RUNTIME ON)
endif()

find_package(Boost COMPONENTS filesystem REQUIRED) 
```
If I try these changes, my project still runs into the same linker error. My folder `C:\vcpkg\installed\x64-windows-static\lib` has the `boost_filesystem-vc140-mt.lib` file:
![image](https://user-images.githubusercontent.com/7620135/107037610-9cac1280-67bb-11eb-89bb-eae337e2222c.png)

How can I resolve this and/or make `Visual Studio` properly link against my static `Boost` libraries?

Without using `vcpkg` (e.g. by downloading a `Boost` distribution and compiling it myself) and using a `Windows Solution` without `CMake`, statically linking works seamlessly:
![image](https://user-images.githubusercontent.com/7620135/107036598-2eb31b80-67ba-11eb-980d-2949b56759af.png)
![image](https://user-images.githubusercontent.com/7620135/107036682-4c808080-67ba-11eb-8241-b1807d6bc31e.png)
![image](https://user-images.githubusercontent.com/7620135/107036637-3a9edd80-67ba-11eb-8fb8-d0b012c15ed7.png)
![image](https://user-images.githubusercontent.com/7620135/107038062-468b9f00-67bc-11eb-931e-939d7f72f4aa.png)

**Comment by woodkatu** [comment]
try add
```
if(PORT MATCHES "^boost-")
    set(VCPKG_LIBRARY_LINKAGE static)
endif()
```
in x64-windows.cmake
then reinstall boost

**Comment by PhoebeHui** [comment]
@BullyWiiPlaza, you need set VCPKG_TARGET_TRIPLET for static build, see https://github.com/microsoft/vcpkg/blob/master/docs/users/integration.md#with-cmake for more information.

The error LNK2038 emitted due to the mismatch crt linkage, you can fix it by setting C/C++ -> Code Generation -> Runtime Library to Multi-threaded Debug (/MTd) in you project.

**Comment by BullyWiiPlaza** [comment]
> try add
> 
> ```
> if(PORT MATCHES "^boost-")
>     set(VCPKG_LIBRARY_LINKAGE static)
> endif()
> ```
> 
> in x64-windows.cmake
> then reinstall boost

Does not work, I edited my `C:\vcpkg\triplets\x64-windows.cmake` and did `vcpkg remove Boost` and `vcpkg install Boost` but same linker error.

> @BullyWiiPlaza, you need set VCPKG_TARGET_TRIPLET for static build, see https://github.com/microsoft/vcpkg/blob/master/docs/users/integration.md#with-cmake for more information.
> 
> The error LNK2038 emitted due to the mismatch crt linkage, you can fix it by setting C/C++ -> Code Generation -> Runtime Library to Multi-threaded Debug (/MTd) in you project.
As explained above, I'm already setting `VCPKG_TARGET_TRIPLET` to x64-windows-static via my `CMakeSettings.json` in `Visual Studio`:

![image](https://user-images.githubusercontent.com/7620135/107150369-c4d37700-695d-11eb-9d6a-7359bf7f083c.png)
This works for forcing static linking but I'm getting the `mismatch detected` error by `Boost`.

Since I'm using `CMake`, I cannot go to this settings path and change the runtime library:
https://docs.microsoft.com/en-us/cpp/build/customize-cmake-settings

Maybe someone can reproduce my "simple" setup with `vcpkg`, `CMake`, Visual Studio and `Boost` with `static linking` on `Windows` and see for themselves how to get this working? Thank you very much.

**Comment by PhoebeHui** [comment]
@BullyWiiPlaza, the mismatch detected linker error is expected, the crt linkage for boost is static, however, it's default to dynamic in your project, so the crt linkage is mismatch. you can fix it by setting C/C++ -> Code Generation -> Runtime Library to **Multi-threaded Debug (/MTd)** in you project.


![image](https://user-images.githubusercontent.com/20694052/107166356-aff3f380-69f0-11eb-86f9-f5e9d82e548f.png)

**Comment by woodkatu** [comment]
```
if(PORT MATCHES "^boost-")
    set(VCPKG_LIBRARY_LINKAGE static)
endif()
```
in `x64-windows` tells vcpkg to build boost as static lib. As the triplet file is x64-windows, you need to use triplet `x64-windows`, not `x64-windows-static`, which requires "/MT"

And for `x64-windows-static`,  cmake command 
```
  string(REPLACE "/MD" "/MT" CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS})
  string(REPLACE "/MD" "/MT" CMAKE_CXX_FLAGS_DEBUG ${CMAKE_CXX_FLAGS_DEBUG})
  string(REPLACE "/MD" "/MT" CMAKE_CXX_FLAGS_RELEASE ${CMAKE_CXX_FLAGS_RELEASE})
```
may do nothing because in default, CMAKE_CXX_FLAGS, CMAKE_CXX_FLAGS_DEBUG, CMAKE_CXX_FLAGS_RELEASE does not contains "/MD". Add `set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS} /MTd") ` , `set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} /MT")` should work
use `message("CMAKE_CXX_FLAGS: ${CMAKE_CXX_FLAGS}")` to check if flags is correctly setted

here is an example CMakeLists.txt 
```
cmake_minimum_required(VERSION 3.16)
project(staticboost)

find_package(Boost REQUIRED COMPONENTS
    filesystem)

set(target ptest)
add_executable(${target} main.cpp)
target_link_libraries(${target} PRIVATE Boost::filesystem)
```
and CMakeSetting.json
```
{
  "configurations": [
    {
      "name": "x64-Debug (default)",
      "generator": "Ninja",
      "configurationType": "Debug",
      "inheritEnvironments": [ "msvc_x64_x64" ],
      "buildRoot": "${projectDir}\\out\\build\\${name}",
      "installRoot": "${projectDir}\\out\\install\\${name}",
      "cmakeCommandArgs": "-DVCPKG_TARGET_TRIPLET=x64-windows",
      "buildCommandArgs": "",
      "ctestCommandArgs": "",
      "cmakeToolchain": "${env.VCPKG_TOOLCHAIN}",
      "variables": []
    }
  ]
}
```
${env.VCPKG_TOOLCHAIN} in CMakeSetting.json is my environment variable contains the path to vcpkg.cmake

**Comment by BullyWiiPlaza** [comment]
> ```
> if(PORT MATCHES "^boost-")
>     set(VCPKG_LIBRARY_LINKAGE static)
> endif()
> ```
> 
> in `x64-windows` tells vcpkg to build boost as static lib. As the triplet file is x64-windows, you need to use triplet `x64-windows`, not `x64-windows-static`, which requires "/MT"

Why would I set it to `x64-windows` when I want to link to all libraries statically? This would also revert other libraries to dynamic linking again which can't be the solution. Also, uninstalling and reinstalling `Boost` with `vcpkg` seems to work too fast to be reasonable so it didn't really work and `vcpkg` probably just reused `Boost` from the cache. Now if I only knew how to wipe that cache and force a true rebuild as I wanted...

I'm still getting the linker errors after following your suggestion though.

> use message("CMAKE_CXX_FLAGS: ${CMAKE_CXX_FLAGS}") to check if flags is correctly setted

On a simple hello world example I shouldn't have to try to debug anything like compilation flags, it should just be straight forward. Anyway, my output is: `1> [CMake] CMAKE_CXX_FLAGS: /DWIN32 /D_WINDOWS /GR /EHsc`
No indication of `/MT` or `/MD`.

> @BullyWiiPlaza, the mismatch detected linker error is expected, the crt linkage for boost is static, however, it's default to dynamic in your project, so the crt linkage is mismatch. you can fix it by setting C/C++ -> Code Generation -> Runtime Library to **Multi-threaded Debug (/MTd)** in you project.
> 
> ![image](https://user-images.githubusercontent.com/20694052/107166356-aff3f380-69f0-11eb-86f9-f5e9d82e548f.png)

This menu cannot be accessed when using a `CMakeLists.txt` project (it's not the same as a Windows `.sln` project) hence I'm trying to use `CMake` only. My platform-independent `CMake` project setup roughly looks like this:

![image](https://user-images.githubusercontent.com/7620135/107410853-1ae71c80-6b0e-11eb-80c4-b94e73e27f41.png)

**Comment by BullyWiiPlaza** [comment]
Alright, I finally found the solution which ended up being really simple:
`set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")`
[Here](https://cmake.org/cmake/help/latest/variable/CMAKE_MSVC_RUNTIME_LIBRARY.html#variable:CMAKE_MSVC_RUNTIME_LIBRARY) is the official documentation for it.

@PhoebeHui was essentially right but it couldn't be used in `CMake`.

**Comment by PhoebeHui** [comment]
@BullyWiiPlaza, thanks for sharing the soultion here!

**Comment by jdx-john** [comment]
@BullyWiiPlaza isn't this the same as #10221? They mention using a special -md triplet which would be simpler?

**Comment by xorz57** [comment]
I leave this here in case you find it useful!

```cmake
if(VCPKG_TARGET_TRIPLET MATCHES "-static$")
    set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
endif()
```

**Comment by goodtrailer** [comment]
For those looking more recently like me, try using the new-ish triplet `x64-windows-static-md` instead of `x64-windows-static` (this triplet was added in December 2024). This has the benefit of still using dynamic linking for the MSVC STL, which saves some file-size (and is generally default behavior).

Correction: `x64-windows-static-md` has existed as a community triplet since 2020, and was only promoted to official in 2024.
