### ISSUE TITLE
Spurious failure building ffmpeg - logs show avformat/cxdl.c was not compiled, but why?

### ISSUE THREAD

**Issue by aggieNick02** [microsoft/vcpkg#16046]
I did a "clean" install of my vcpkg dependencies by removing `%localappdata%\vcpkg` and grabbing a fresh copy of my vcpkg branch repo, then running bootstrap/integrate and the usual install commands for my packages. I've done this before without any issues.

This time, however, my ffmpeg install failed. The way it failed has me scratching my head. The error was:
`Object does not exist: libavformat/cdxl.o`
I went and examined the relevant `buildtress/ffmpeg/<triplet>-rel` folder, and oddly found `cdxl.d` but `cdxl.o` was missing. This seemed weird because `builtdrees/fmpeg/src/n4.3.1-73f9ace9ef.clean/libavformat/cdxl.c` was present.

I checked the config.log which contained  `cdxl_demuxer`,`cdxl_demuxer=yes`. Everything looks right as far as I can tell, except that in the log for the actual build, `libavformat/cdxl.c` just isn't compiled. It's like the compilation of the file was skipped, but I've no idea why.

Running the ffmpeg install again resulted in success. Repeating the steps from scratch (removing `%localappdata%\vcpkg` and grabbing a fresh copy of my vcpkg branch repo) would not reproduce the issue.

Any ideas what could have happened or where I might look in the logs to try to figure out why `libavformat/cdxl.c` was skipped this one time? I'm attaching the logs from when the build failed, and for when it succeeded after repeating the steps from scratch, along with a screenshot of a diff of the relevant portion.
![build_log_diff](https://user-images.githubusercontent.com/16806169/106926579-d5be8700-66d6-11eb-9f02-0a23fb41c883.png)
[failure_build-x64-windows-static-md-ffmpeg-rel-out.log](https://github.com/microsoft/vcpkg/files/5927249/failure_build-x64-windows-static-md-ffmpeg-rel-out.log)
[success_build-x64-windows-static-md-ffmpeg-rel-out.log](https://github.com/microsoft/vcpkg/files/5927250/success_build-x64-windows-static-md-ffmpeg-rel-out.log)
There are no noticeable differences (just order that *.c files were compiled in), except for the missing compilation of `libavformat/cdxl.c` . I've added a mark `!!!!-area_of_interest-!!!!` in the out files next to where the `libavformat/cdxl.c` compilation should be/is. To avoid confusion, note that there is also a file named `libavcodec/cdxl.c` - this file built fine in both cases.

Apologies I don't have reliable steps to reproduce. Any pointers on where to look in logs or things to try are appreciated. If useful, I can automate the steps and run them over and over to see if I can reproduce the failure.

This failure happened on a high-core-count machine (Threadripper 3970X), in case that may be relevant. I'm also using a custom overlay triplet to build some components as dlls and others as shared libraries.

**Comment by JackBoosY** [comment]
Hmm... @cenit can you please take a look?

Thanks.

**Comment by cenit** [comment]
It might be a bug in the upstream build script. As you said, you're using a high number of threads and maybe you're able to run so many steps of the build to uncover two of them that are distant and dependent but that do not wait one each other (because of the missing explicit dependency). An upstream bug might be the best option. Do you have time to investigate this build step problem in the makefile, so to check if this idea is reasonable?

**Comment by aggieNick02** [comment]
I'm not very experienced with makefiles, but am happy to look and see what I can. I appreciate just having a second set of eyes to look at this and make sure I'm not missing something obvious. It feels like "make did the wrong thing" but I know that is exceedingly unlikely.

From what I can tell, everything looks pretty straightforward and single-sourced, There is `ffmpeg/libavformat/Makefile` which lists `cdxl.o` when `$(CONFIG_CDXL_DEMUXER)` is set appropriately. I believe the presence of that leads to both the compilation of `cdxl.c` and the linking of `cdxl.o` via `ffmpeg/ffbuild/common.mak` (see `%.o: %.c` entry). Here my lack of makefile knowledge shows...

If it's all single-sourced, it is hard to understand how the file would not be compiled but would try to be linked, I'm at a bit of a loss. `ffmpeg/ffbuild/config.mak` sets `CONFIG_CDXL_DEMUXER=yes` unconditionally, and the logs go with that too. If somehow `config.mak` was not processed, then I would have expected many other things to be not compiled in the logs, and that's not the case.

I realize this issue gives very little to go on, so if there aren't any ideas on what might have happened, closing is probably the best choice. If it happens to me again, I can see if automating and rebuilding repeatedly can make it happen again.

**Comment by cenit** [comment]
My problem is always time. Your issue is well detailed and your knowledge of makefile which you consider not so deep is not an obstacle at all. If just retrying works for you, it is the quickest fix (see my opening message). Keep the issue open anyway

**Comment by JackBoosY** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.
