### ISSUE TITLE
opencv4[contrib]:x64-linux-dynamic --overlay-triplets=custom-triplets  build faild

### ISSUE THREAD

**Issue by JaosonMa** [microsoft/vcpkg#16043]
**Host Environment**
- OS: [Ubuntu]
- Compiler: gcc 6.3.0

**To Reproduce**
`./vcpkg install opencv4[contrib]:x64-linux-dynamic --overlay-triplets=custom-triplets`

> https://github.com/microsoft/vcpkg/blob/master/docs/examples/overlay-triplets-linux-dynamic.md

**Failure logs** 
`-- Building x64-linux-dynamic-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:145 (message):
    Command failed: /home/ubuntu/qqm/vcpkg/downloads/tools/cmake-3.19.2-linux/cmake-3.19.2-Linux-x86_64/bin/cmake --build . --config Debug --target install -- -v -j49
    Working Directory: /home/ubuntu/qqm/vcpkg/buildtrees/opencv4/x64-linux-dynamic-dbg
    See logs for more information:
      /home/ubuntu/qqm/vcpkg/buildtrees/opencv4/install-x64-linux-dynamic-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:27 (vcpkg_build_cmake)
  ports/opencv4/portfile.cmake:385 (vcpkg_install_cmake)
  scripts/ports.cmake:128 (include)

Error: Building package opencv4:x64-linux-dynamic failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: opencv4:x64-linux-dynamic
  Vcpkg version: 2021-01-13-unknownhash

Additionally, attach any relevant sections from the log files above.`

**Additional context**

[install-x64-linux-dynamic-dbg-out.log](https://github.com/microsoft/vcpkg/files/5926513/install-x64-linux-dynamic-dbg-out.log)

install-x64-linux-dynamic-dbg-err.log is empty!

Add any other context about the problem here, such as what you have already tried to resolve the issue.

I try to slove this by looking in the issues,but no one can fix my problem, can you help me ?

@JackBoosY  can you help me ?

**Comment by JaosonMa** [comment]
#9297
but my Linux can not reboot,

**Comment by JaosonMa** [comment]
> #9297
> but my Linux can not reboot,

i found some error, just pass this

**Comment by JackBoosY** [comment]
```
/home/ubuntu/qqm/vcpkg/installed/x64-linux-dynamic/tools/protobuf/protoc: error while loading shared libraries: libprotoc.so.3.14.0.0: cannot open shared object file: No such file or directory
```

I think libprotoc.so.3.14.0.0 wasn't installed to _/home/ubuntu/qqm/vcpkg/installed/x64-linux-dynamic/tools/protobuf_.
Right?

**Comment by JaosonMa** [comment]
> ```
> /home/ubuntu/qqm/vcpkg/installed/x64-linux-dynamic/tools/protobuf/protoc: error while loading shared libraries: libprotoc.so.3.14.0.0: cannot open shared object file: No such file or directory
> ```
> 
> I think libprotoc.so.3.14.0.0 wasn't installed to _/home/ubuntu/qqm/vcpkg/installed/x64-linux-dynamic/tools/protobuf_.
> Right?

yes，it is an error.

I think it may have something to do with the fact that I have compiled the opencv static library, so I cleared all my installation packages and recompiled them with reference to the dynamic library compilation operation. The result is still this error, which is not found in this path libprotoc.so There is only protocol-3.14.0.0 and its link.

![image](https://user-images.githubusercontent.com/23551774/106983825-809b7780-67a1-11eb-8c6b-d9ee245a964a.png)

i try to rebuild protobuf-3.14.0 with dynamic，but the same resoult .  what should i going to try? @JackBoosY

**Comment by JaosonMa** [comment]
> > ```
> > /home/ubuntu/qqm/vcpkg/installed/x64-linux-dynamic/tools/protobuf/protoc: error while loading shared libraries: libprotoc.so.3.14.0.0: cannot open shared object file: No such file or directory
> > ```
> > 
> > 
> > I think libprotoc.so.3.14.0.0 wasn't installed to _/home/ubuntu/qqm/vcpkg/installed/x64-linux-dynamic/tools/protobuf_.
> > Right?
> 
> yes，it is an error.
> 
> I think it may have something to do with the fact that I have compiled the opencv static library, so I cleared all my installation packages and recompiled them with reference to the dynamic library compilation operation. The result is still this error, which is not found in this path libprotoc.so There is only protocol-3.14.0.0 and its link.
> 
> ![image](https://user-images.githubusercontent.com/23551774/106983825-809b7780-67a1-11eb-8c6b-d9ee245a964a.png)
> 
> i try to rebuild protobuf-3.14.0 with dynamic，but the same resoult . what should i going to try? @JackBoosY

> ubuntu@ubuntu:~/qqm/vcpkg$ ls /home/ubuntu/qqm/vcpkg/installed/x64-linux/tools/protobuf/
protoc  protoc-3.14.0.0

**Comment by JackBoosY** [comment]
I'll have a try to repro this.

**Comment by JaosonMa** [comment]
> > > ```
> > > /home/ubuntu/qqm/vcpkg/installed/x64-linux-dynamic/tools/protobuf/protoc: error while loading shared libraries: libprotoc.so.3.14.0.0: cannot open shared object file: No such file or directory
> > > ```
> > > 
> > > 
> > > I think libprotoc.so.3.14.0.0 wasn't installed to _/home/ubuntu/qqm/vcpkg/installed/x64-linux-dynamic/tools/protobuf_.
> > > Right?
> > 
> > 
> > yes，it is an error.
> > I think it may have something to do with the fact that I have compiled the opencv static library, so I cleared all my installation packages and recompiled them with reference to the dynamic library compilation operation. The result is still this error, which is not found in this path libprotoc.so There is only protocol-3.14.0.0 and its link.
> > ![image](https://user-images.githubusercontent.com/23551774/106983825-809b7780-67a1-11eb-8c6b-d9ee245a964a.png)
> > i try to rebuild protobuf-3.14.0 with dynamic，but the same resoult . what should i going to try? @JackBoosY
> 
> > ubuntu@ubuntu:~/qqm/vcpkg$ ls /home/ubuntu/qqm/vcpkg/installed/x64-linux/tools/protobuf/
> > protoc  protoc-3.14.0.0

but in the path vcpkg/install/x64-linux/lib  there have the libprotoc.so.3.14.0, and its link , 

> ~/qqm/vcpkg/installed/x64-linux/lib$ ll

> lrwxrwxrwx 1 ubuntu ubuntu      28 2月   5 10:55 libprotobuf-lite.so -> libprotobuf-lite.so.3.14.0.0
-rw-r--r-- 1 ubuntu ubuntu  724520 2月   5 10:55 libprotobuf-lite.so.3.14.0.0
lrwxrwxrwx 1 ubuntu ubuntu      23 2月   5 10:55 libprotobuf.so -> libprotobuf.so.3.14.0.0
-rw-r--r-- 1 ubuntu ubuntu 3494600 2月   5 10:55 libprotobuf.so.3.14.0.0
lrwxrwxrwx 1 ubuntu ubuntu      21 2月   5 10:55 libprotoc.so -> libprotoc.so.3.14.0.0
-rw-r--r-- 1 ubuntu ubuntu 3481792 2月   5 10:55 libprotoc.so.3.14.0.0

**Comment by JackBoosY** [comment]
https://github.com/microsoft/vcpkg/blob/5eea585548058540c3b73d087eb101c033b5fa85/ports/protobuf/portfile.cmake#L110-L116
Dynamic build in *inx is not considered here.

**Comment by JaosonMa** [comment]
> https://github.com/microsoft/vcpkg/blob/5eea585548058540c3b73d087eb101c033b5fa85/ports/protobuf/portfile.cmake#L110-L116
> 
> 
> Dynamic build in *inx is not considered here.

Can you tell me how to make changes to achieve dynamic compilation? I need dynamic library for my project.
 
will you consider this in ther feature version?

**Comment by JackBoosY** [comment]
@JaosonMa Add these code in line 116:
```cmake
 file(GLOB DEPENDS ${CURRENT_PACKAGES_DIR}/lib/*) 
 foreach(D IN LISTS DEPENDS) 
     file(INSTALL ${D} DESTINATION ${CURRENT_PACKAGES_DIR}/tools/${PORT} 
             PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_WRITE GROUP_EXECUTE WORLD_READ) 
 endforeach() 
```

**Comment by JackBoosY** [comment]
Or use the following command:
```sh
export LD_LIBRARY_PATH=VCPKG_ROOT/installed/x64-linux-dynamic/lib:$LD_LIBRARY_PATH
sudo ldconfig
```

**Comment by JaosonMa** [comment]
> @JaosonMa Add these code in line 116:
> 
> ```cmake
>  file(GLOB DEPENDS ${CURRENT_PACKAGES_DIR}/lib/*) 
>  foreach(D IN LISTS DEPENDS) 
>      file(INSTALL ${D} DESTINATION ${CURRENT_PACKAGES_DIR}/tools/${PORT} 
>              PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_WRITE GROUP_EXECUTE WORLD_READ) 
>  endforeach() 
> ```

i was not sure about what you mean by "in the line 116" so 
first:
![image](https://user-images.githubusercontent.com/23551774/106995024-f19a5980-67b8-11eb-9567-b2c2c353e495.png)

the same error .

second:
![image](https://user-images.githubusercontent.com/23551774/106996222-7b4b2680-67bb-11eb-94e2-c0a9cac28597.png)

same erro too.

**Comment by JaosonMa** [comment]
> Or use the following command:
> 
> ```shell
> export LD_LIBRARY_PATH=VCPKG_ROOT/installed/x64-linux-dynamic/lib:$LD_LIBRARY_PATH
> sudo ldconfig
> ```

this worked!  and i can understand why , but I would like to solve this problem with the first method you provided

> -- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: /home/ubuntu/.cache/vcpkg/archives/b1/b1da48412913aef9815ebfc9e18b734188755c87.zip
Building package opencv4[contrib,core,dnn,jpeg,png,quirc,tiff,webp]:x64-linux... done
Installing package opencv4[contrib,core,dnn,jpeg,png,quirc,tiff,webp]:x64-linux...
Installing package opencv4[contrib,core,dnn,jpeg,png,quirc,tiff,webp]:x64-linux... done
Elapsed time for package opencv4:x64-linux: 3.096 min

Total elapsed time: 3.106 min

The package opencv4:x64-linux provides CMake targets:

    find_package(OpenCV CONFIG REQUIRED)
    # Note: 45 target(s) were omitted.
    target_link_libraries(main PRIVATE opencv_ml opencv_dnn opencv_dpm opencv_hdf)

**Comment by JackBoosY** [comment]
@JaosonMa This is why the default x64-linux is static: the path of the dynamic library in Linux has not been added to `LD_LIBRARY_PATH`.
