### ISSUE TITLE
[New Port Request] manif

### ISSUE THREAD

**Issue by GiulioRomualdi** [microsoft/vcpkg#16058]
Library name: manif

Library description: manif is a header-only C++11 Lie theory library for state-estimation targeted at robotics applications.

Source repository URL:  https://github.com/artivis/manif

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

The only dependency is `eigen3`

cc @traversaro @artivis

**Comment by traversaro** [comment]
> The only dependency is eigen3

I inspected a bit and I noticed that in https://github.com/artivis/manif/tree/devel/external/lt/lt a copy of `lt-optional` (that is available in vcpkg, see https://github.com/Microsoft/vcpkg/tree/master/ports/tl-optional) is used in public header, so it could make sense to patch manif to use the vcpkg's provided lt-optional.

**Comment by traversaro** [comment]
However, the version used in manif is an 0.2 while the one provided by vcpkg is 1.0, so probably we need to make sure that it works correctly.

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
