### ISSUE TITLE
gmp:x64-windows build failure for install cgal:x64-windows

### ISSUE THREAD

**Issue by michael-schw** [microsoft/vcpkg#16056]
**Host Environment**
- OS:  Windows 10
- Compiler: 14

**To Reproduce**
`./vcpkg install cgal:x64-windows`
`./vcpkg install yasm-tool:x64-windows`

**Failure logs** 

> Starting package 86/89: gmp:x64-windows
> Building package gmp[core]:x64-windows...
> -- Downloading https://github.com/ShiftMediaProject/gmp/archive/0018c44e8dfcc3b64b43e0aea4b3f419f0b65fd0.tar.gz -> ShiftMediaProject-gmp-0018c44e8dfcc3b64b43e0aea4b3f419f0b65fd0.tar.gz...
> -- Extracting source C:/dev/vcpkg-master/downloads/ShiftMediaProject-gmp-0018c44e8dfcc3b64b43e0aea4b3f419f0b65fd0.tar.gz
> -- Applying patch vs.build.patch
> -- Applying patch runtime.patch
> -- Applying patch adddef.patch
> -- Using source at C:/dev/vcpkg-master/buildtrees/gmp/src/19f0b65fd0-9b395bc164.clean
> CMake Error at installed/x64-windows/share/yasm-tool-helper/yasm-tool-helper.cmake:16 (message):
>   Cross-targetting and x64 ports requiring yasm require the x86-windows
>   yasm-tool to be available.  Please install yasm-tool:x86-windows first.
> Call Stack (most recent call first):
>   ports/gmp/portfile.cmake:19 (yasm_tool_helper)
>   scripts/ports.cmake:128 (include)
> 
> 
> Error: Building package gmp:x64-windows failed with: BUILD_FAILED
> Please ensure you're using the latest portfiles with `.\vcpkg update`, then
> submit an issue at https://github.com/Microsoft/vcpkg/issues including:
>   Package: gmp:x64-windows
>   Vcpkg version: 2021-01-13-768d8f95c9e752603d2c5901c7a7c7fbdb08af35
> 
> Additionally, attach any relevant sections from the log files above.
> 

AAAnd after 'vcpkg.exe install yasm-tool:x64-windows'

> C:\dev\vcpkg-master>vcpkg.exe install yasm-tool:x64-windows
> Computing installation plan...
> The following packages will be built and installed:
>     yasm-tool[core]:x64-windows -> 2020-10-12
> Detecting compiler hash for triplet x64-windows...
> Could not locate cached archive: C:\Users\micha\AppData\Local\vcpkg\archives\79\79db3c7378802a050ddba550225330089f448832.zip
> Starting package 1/1: yasm-tool:x64-windows
> Building package yasm-tool[core]:x64-windows...
> CMake Error at scripts/cmake/vcpkg_fail_port_install.cmake:97 (message):
>   The yasm-tool port is only intended to be built for x86 Windows
> 
>   Architecture 'x64' not supported by yasm-tool!
> 
> Call Stack (most recent call first):
>   ports/yasm-tool/portfile.cmake:1 (vcpkg_fail_port_install)
>   scripts/ports.cmake:128 (include)
> 
> 
> Error: Building package yasm-tool:x64-windows failed with: BUILD_FAILED
> Please ensure you're using the latest portfiles with `.\vcpkg update`, then
> submit an issue at https://github.com/Microsoft/vcpkg/issues including:
>   Package: yasm-tool:x64-windows
>   Vcpkg version: 2021-01-13-768d8f95c9e752603d2c5901c7a7c7fbdb08af35
> 
> Additionally, attach any relevant sections from the log files above.
> -Please attach any additional failure logs mentioned in the console output.

**Additional context**
I have already done `.\vcpkg update`:

> C:\dev\vcpkg-master>.\vcpkg update
> Using local portfile versions. To update the local portfiles, use `git pull`.
> No packages need updating.
>
> There is no log file at installed/x64-windows/share/yasm-tool-helper/yasm-tool-helper.cmake

**Comment by NancyLi1013** [comment]
Hi @michael-schw 

Thanks for posting this issue.

```
CMake Error at installed/x64-windows/share/yasm-tool-helper/yasm-tool-helper.cmake:16 (message):
Cross-targetting and x64 ports requiring yasm require the x86-windows
yasm-tool to be available. Please install yasm-tool:x86-windows first.
```
Please install `yasm-tool:x86-windows` first, then rebuild `cgal:x64-windows`.

**Comment by michael-schw** [comment]
Thanks for replying,
as above mentioned (but not highlight visible) I have already installed yasm-tool with 'vcpkg.exe install yasm-tool:x64-windows'
The Error Message was:

C:\dev\vcpkg-master>vcpkg.exe install yasm-tool:x64-windows
Computing installation plan...
The following packages will be built and installed:
yasm-tool[core]:x64-windows -> 2020-10-12
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\micha\AppData\Local\vcpkg\archives\79\79db3c7378802a050ddba550225330089f448832.zip
Starting package 1/1: yasm-tool:x64-windows
Building package yasm-tool[core]:x64-windows...
CMake Error at scripts/cmake/vcpkg_fail_port_install.cmake:97 (message):
The yasm-tool port is only intended to be built for x86 Windows

Architecture 'x64' not supported by yasm-tool!

Call Stack (most recent call first):
ports/yasm-tool/portfile.cmake:1 (vcpkg_fail_port_install)
scripts/ports.cmake:128 (include)

Error: Building package yasm-tool:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with .\vcpkg update, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
Package: yasm-tool:x64-windows
Vcpkg version: 2021-01-13-768d8f95c9e752603d2c5901c7a7c7fbdb08af35

**Comment by michael-schw** [comment]
I downloaded cgal for 32 bit (which is obviously wrong) with `vcpkg.exe install cgal` and somehow I was able to finish the my installation for my 64 bit windows system. I have no clue why this worked for me.
