### ISSUE TITLE
[New Port Request] <frei0r >

### ISSUE THREAD

**Issue by pengguoqing** [microsoft/vcpkg#16054]
Library name:
frei0r

Library description:
Frei0r is a minimalistic plugin API for video effects.

Source repository URL:
https://github.com/dyne/frei0r.git

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
Develop video editor in VS2019

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by jaromil** [comment]
Hi there! I'm the upstream maintainer of frei0r and would like to add the port myself, I just managed to include MSVC builds in our CI and I'm confident it will be easy. Is there something I should absolutely know and read besides the guidelines and sign the CLA? thanks!
