### ISSUE TITLE
 Visual Studio does not recognize 64-bit packages

### ISSUE THREAD

**Issue by luizfernandonb** [microsoft/vcpkg#16050]
**Describe the bug**
I recently installed vcpkg and installed only 64-bit packages, but when I created a project in Visual Studio 2019, no package was available to include in the project, to work I have to download the 32-bit version of this same package

**Environment**
- OS: Windows 10 - 2004
- Compiler: MSVC

**To Reproduce**
1. ./vcpkg install xxxx:x64-windows (Install only 64 bits)
2. Create a project in Visual Studio 2019
3. Try include the library

**Expected behavior**
The library included

**Comment by StarGate-One** [comment]
Did you by chance do the `vcpkg integrate install` which connects visual studio to vcpkg?
Or did you happen to select `x64` in the Visual Studio project configuration?

**Comment by JackBoosY** [comment]
Please see [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/users/integration.md).

**Comment by luizfernandonb** [comment]
> Did you by chance do the `vcpkg integrate install` which connects visual studio to vcpkg?
> Or did you happen to select `x64` in the Visual Studio project configuration?


I've run `vcpkg integrate install` since I installed vcpkg, and I didn't select x64 in Visual Studio, I believe that might be it

**Comment by JackBoosY** [comment]
So is this issue resolved?

**Comment by luizfernandonb** [comment]
> > Did you by chance do the `vcpkg integrate install` which connects visual studio to vcpkg?
> > Or did you happen to select `x64` in the Visual Studio project configuration?
> 
> I've run `vcpkg integrate install` since I installed vcpkg, and I didn't select x64 in Visual Studio, I believe that might be it

Yes

**Comment by luizfernandonb** [comment]
> So is this issue resolved?

Yes
