### ISSUE TITLE
Support OpenBLAS 2.20 and x64-UWP

### ISSUE THREAD

**Issue by neilsh-msft** [Microsoft/vcpkg#1606]
OpenBLAS 0.2.20 has been released.  The build process now uses SED and AWK.  Also UWP is now supported.  A couple issues is that SED and AWK aren't discoverable with the current vcpkg.  However sed and awk are installed with git but not made part of the default path.  Also to build UWP binaries, non-UWP helper executables must be built first which are used during the UWP build process.

**Comment by ras0219-msft** [comment]
Fixes in #1607, thanks for sending us a PR!
