### ISSUE TITLE
[spdlog] Respect VCPKG_LIBRARY_LINKAGE

### ISSUE THREAD

**Issue by Fedr** [microsoft/vcpkg#16075]
Currently spdlog port always builds static library even when VCPKG_LIBRARY_LINKAGE=dynamic

**Proposed solution**
Write in ports\spdlog\portfile.cmake:
```
if(VCPKG_LIBRARY_LINKAGE STREQUAL dynamic)
    set(SPDLOG_BUILD_SHARED_LIBS ON)
else()
    set(SPDLOG_BUILD_SHARED_LIBS OFF)
endif()

vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA
    OPTIONS
        ${FEATURE_OPTIONS}
        -DSPDLOG_FMT_EXTERNAL=ON
        -DSPDLOG_INSTALL=ON
        -DSPDLOG_BUILD_SHARED=${SPDLOG_BUILD_SHARED_LIBS}
)
```

Please let me know if pull request from my side is necessary,

**Comment by JonLiu1993** [comment]
@Fedr ,Thanks for posting this issue,
I built spdlog locally after modifying it according to your suggestion. The modified config-x6-windows-out.log shows "-DSPDLOG_BUILD_BENCH=OFF", and it seems that the result is the same as before.

**Comment by JonLiu1993** [comment]
@Fedr ,Thanks for posting this issue,We tried your suggestion locally and it is correct. I will submit the pr as soon as possible to change it. Thank you for your contribution
