### ISSUE TITLE
[qt5] build failure

### ISSUE THREAD

**Issue by 200201141** [microsoft/vcpkg#16076]
**Host Environment**
- OS: Windows 10
- Compiler: Visual Studio 2019

**To Reproduce**
`./vcpkg install qt5'

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:145 (message):
    Command failed: C:/vcpkg/downloads/tools/jom/jom-1.1.3/jom.exe /J 9
    Working Directory: C:/vcpkg/buildtrees/qt5-base/x86-windows-rel
    See logs for more information:
      C:\vcpkg\buildtrees\qt5-base\build-x86-windows-rel-out.log
      C:\vcpkg\buildtrees\qt5-base\build-x86-windows-rel-err.log

Call Stack (most recent call first):
  ports/qt5-base/cmake/install_qt.cmake:92 (vcpkg_execute_build_process)
  ports/qt5-base/portfile.cmake:348 (install_qt)
  scripts/ports.cmake:128 (include)

Error: Building package qt5-base:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: qt5-base:x86-windows
  Vcpkg version: 2021-01-13-unknownhash

Additionally, attach any relevant sections from the log files above.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by JackBoosY** [comment]
Please provide failure log _C:\vcpkg\buildtrees\qt5-base\build-x86-windows-rel-out.log_ and _C:\vcpkg\buildtrees\qt5-base\build-x86-windows-rel-err.log_.

Thanks.

**Comment by 200201141** [comment]
[build-x86-windows-rel-err.log](https://github.com/microsoft/vcpkg/files/5939725/build-x86-windows-rel-err.log)
[build-x86-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/5939726/build-x86-windows-rel-out.log)

Thank you for your interest.

**Comment by JackBoosY** [comment]
```
C:\vcpkg\buildtrees\qt5-base\src\5.15.2-70178539f6.clean\src\corelib\global\qt_pch.h(83): fatal error C1085: Cannot write precompiled header file: '.pch\release\Qt5FbSupport_pch.pch': Diskte yeterli yer yok.
```
Seems your disk is full.

**Comment by 200201141** [comment]
I feel very sorry that i entered a comment without checking the logs carefully. 
I cleaned up some space in my disk and succesfully installed qt5.

**Comment by 200201141** [comment]
Thank you.
