### ISSUE TITLE
[New Port Request] ImGuiFileDialog

### ISSUE THREAD

**Issue by kareemsayed** [microsoft/vcpkg#16079]
Library name: ImGuiFileDialog

Library description: ImGuiFileDialog is a file selection dialog built for (and using only) Dear ImGui.

Source repository URL:  https://github.com/aiekick/ImGuiFileDialog

Project homepage (if different from the source repository):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
