### ISSUE TITLE
[New Port Request] libao

### ISSUE THREAD

**Issue by ghost** [microsoft/vcpkg#16074]
Library name: libao

Library description: Libao is a cross-platform audio library that allows programs to output audio using a simple API on a wide variety of platforms

Source repository URL: https://github.com/xiph/libao

Project homepage:  https://www.xiph.org/ao/

Please add this library to vcpkg :)

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by xiaoyifang** [comment]
why close it?

**Comment by xiaoyifang** [comment]
https://github.com/microsoft/vcpkg/issues/21791
