### ISSUE TITLE
Keeping multiple triplets when use vcpkg install

### ISSUE THREAD

**Issue by autoantwort** [microsoft/vcpkg#16083]
**Describe the bug**
We have a solution with multiple projects, some are x64 and some x86. We use a manifest file for the whole solution to specify the dependencies. The problem is, that when you build a x64 project, it removes the x86 versions of the dependencies and the other way around.

**Environment**
- OS: Windows
- Compiler: Visual Studio 2015

**To Reproduce**
1. Use a manifest file
2. Have a solution with x86 and x64 Projects
3. Build the solution

**Expected behavior**
Do not remove the installed versions of other triplets.

**Additional context**
Maybe the same as #12525, but we don't use cmake

**Comment by JackBoosY** [comment]
@strega-nil Can you please take a look?

**Comment by strega-nil** [comment]
@autoantwort What we recommend here is to set the installed directory based upon the thing you're building for; in your settings, you should be able to set the installed directory to, for example, `vcpkg-installed_x64` for x64, and `vcpkg-installed_win32` for win32, or whatever you wish.

Unfortunately, it seems like we don't actually have that option in the vcpkg properties pane; I will open an issue for that, and it should be a pretty easy fix.

**Comment by autoantwort** [comment]
> in your settings

Which settings? Do you mean the `*.vcxproj` project files? 

> Unfortunately, it seems like we don't actually have that option in the vcpkg properties pane; I will open an issue for that, and it should be a pretty easy fix.
https://github.com/microsoft/vcpkg/blob/5eea585548058540c3b73d087eb101c033b5fa85/scripts/buildsystems/msbuild/vcpkg-general.xml#L58

Probably you only have to remove `Visible="false"`

But imho this is not a very user friendly and intuitive solution. It would be more user friendly if you don't remove installed packages from other triplets. Then vcpkg just works out of the box.

**Comment by autoantwort** [comment]
When I change `VcpkgCurrentInstalledDir`, nothing changed. If I change `VcpkgInstalledDir`, vcpkg initially does not work anymore, because you have to create the installed dirs yourself (copy existing installed dir and rename it).  
Finally it worked with:
```xml
  <PropertyGroup Label="Vcpkg">
    <VcpkgInstalledDir>$(VcpkgRoot)$(VcpkgPlatformTarget)_installed\</VcpkgInstalledDir>
  </PropertyGroup>
```
I used a property sheet, because I don't want to change that manuelly in over hundred projects ...

**Comment by autoantwort** [comment]
Btw, if I change `VcpkgCurrentInstalledDir` and `VcpkgInstalledDir`, vcpkg only returns 1 and does nothing.

**Comment by strega-nil** [comment]
@autoantwort unfortunately, this isn't really a thing we can do? There's too much cross-talk, especially with #15424, to really support having two different triplets installed.

**Comment by autoantwort** [comment]
Ok. My naive assumption was that you can simply ignore packages from other triplets in the implementation, but it seems to be more complicated.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

**Comment by autoantwort** [comment]
BTW this is now fixed in the latest master

**Comment by russelltg** [comment]
This would be great to have--using `--x-install-root` is a workaround but it's not ideal.
