### ISSUE TITLE
[boost-python] build failure with [python2] feature

### ISSUE THREAD

**Issue by zzattack** [microsoft/vcpkg#16081]
**Host Environment**
- OS: Win10, Server 2019
- Compiler: Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29335 for x86

**To Reproduce**
`.\vcpkg install boost-python[python2]`

**Failure logs** 
[build-x86-windows-rel-err.log](https://github.com/microsoft/vcpkg/files/5937916/build-x86-windows-rel-err.log)
[build-x86-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/5937917/build-x86-windows-rel-out.log)

**Additional context**
Tried on various pc's and a fully fresh vcpkg instance. MSVC is updated to latest revision. System only has python 2.7 installed.

**Comment by PhoebeHui** [comment]
@zzattack, thanks for reporting this issue! I have submitted PR #16087 to fix this issue.

**Comment by zzattack** [comment]
Works perfectly, thank you for the quick resolution!
