### ISSUE TITLE
Wrong visual studio version selected when manually setting VCPKG_PLATFORM_TOOLSET

### ISSUE THREAD

**Issue by edo9300** [microsoft/vcpkg#16093]
**Describe the bug**
I have visual studio 2019, and am using the v141 platform toolset to build my program (i installed from the visual studio installer standalone, not from a visual studio 2017 installation). When I manually set VCPKG_PLATFORM_TOOLSET to v141 in my triplets, https://github.com/microsoft/vcpkg/blob/5eea585548058540c3b73d087eb101c033b5fa85/scripts/cmake/vcpkg_configure_cmake.cmake#L131-L132 automatically assumes `Visual Studio 15 2017` as generator based on the toolset, while, in my case, it should pick  `Visual Studio 16 2019`, thus causing issues with libraries that don't use another generator (like `Ninja`).

**Environment**
- OS: Windows
- Compiler: Visual Studio 2019 (v141 toolset)

**To Reproduce**
1. Have ONLY Visual Studio 2019 installed and have the v141 toolset installed separately from the Visual Studio Installer
2. Create a triplet for Visual Studio manually setting ```VCPKG_PLATFORM_TOOLSET``` to v141
3. Attempt to install a library depending on ``vcpkg_configure_cmake`` and not using ``Ninja``, for example libssh2

**Expected behavior**
The library compiles correctly.

**Failure logs**
```
[1/2] cmd /c "cd .. && "C:/Program Files/CMake/bin/cmake.exe" "D:/vcpkg/buildtrees/libssh2/src/3534322d64-e9146b9288.clean" "-DBUILD_EXAMPLES=OFF" "-DBUILD_TESTING=OFF" "-DENABLE_ZLIB_COMPRESSION=ON" "-DBUILD_SHARED_LIBS=OFF" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=D:/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x86-windows-static" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v141" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=D:/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=static" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_TARGET_ARCHITECTURE=x86" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=D:/vcpkg" "-D_VCPKG_INSTALLED_DIR=D:/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF" "-G" "Visual Studio 15 2017" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=D:/vcpkg/packages/libssh2_x86-windows-static""
FAILED: ../CMakeCache.txt 
cmd /c "cd .. && "C:/Program Files/CMake/bin/cmake.exe" "D:/vcpkg/buildtrees/libssh2/src/3534322d64-e9146b9288.clean" "-DBUILD_EXAMPLES=OFF" "-DBUILD_TESTING=OFF" "-DENABLE_ZLIB_COMPRESSION=ON" "-DBUILD_SHARED_LIBS=OFF" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=D:/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x86-windows-static" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v141" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=D:/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=static" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_TARGET_ARCHITECTURE=x86" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=D:/vcpkg" "-D_VCPKG_INSTALLED_DIR=D:/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF" "-G" "Visual Studio 15 2017" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=D:/vcpkg/packages/libssh2_x86-windows-static""
CMake Deprecation Warning at CMakeLists.txt:36 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Error at CMakeLists.txt:40 (project):
  Generator

    Visual Studio 15 2017

  could not find any instance of Visual Studio.



-- Configuring incomplete, errors occurred!
See also "D:/vcpkg/buildtrees/libssh2/x86-windows-static-rel/CMakeFiles/CMakeOutput.log".
```

**Comment by NancyLi1013** [comment]
Hi @edo9300 

Thanks for posting this issue.

Since you only installed Visual Studio 2019, but you used toolset v141, which is not supported in vcpkg now.
One generator is only for one toolset. Please see the doc:
https://github.com/microsoft/vcpkg/blob/master/docs/users/triplets.md#vcpkg_platform_toolset

Note: You can use a workaround to solve your prblem.
pass `GENERATOR "Visual Studio 16 2019"` in `vcpkg_configure_cmake()` 

```
vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    GENERATOR "Visual Studio 16 2019"
    OPTIONS
        -DBUILD_EXAMPLES=OFF
        -DBUILD_TESTING=OFF
        -DENABLE_ZLIB_COMPRESSION=ON
    OPTIONS_DEBUG
        -DENABLE_DEBUG_LOGGING=OFF
)
```

**Comment by edo9300** [comment]
I see, I suspected it might have been by design, but couldn't it be possible to add another triplet option like we have for VCPKG_PLATFORM_TOOLSET to override this behaviour at triplet level, rather than changing every single port manually?

**Comment by NancyLi1013** [comment]
@edo9300 

Thanks for your suggestion. Generally, we use one kind of toolset in the specific Visual Studio as you can see it in `vcpkg_configure_cmake()`. So we will keep current status. I'm sorry, it might be impossible to implement your proposal in the near future.

**Comment by NancyLi1013** [comment]
Duplicated to #7318, let's track this issue there.
