### ISSUE TITLE
Cannot include vcpkg library in VSCode and CMake under Windows

### ISSUE THREAD

**Issue by DennisPodbicanin** [microsoft/vcpkg#16091]
**Describe the bug**
I am using VSCode with CMake under Windows and I installed the C ++ library boolinq via `vcpkg install boolinq`. But when I wanted to use boolinq, I got the error that VSCode can't find the header, and the build didn't work either. 

**Environment**
- OS: Windows 10
- Compiler: MSVC v. 16.8.4

**To Reproduce**
1. vcpkg install boolinq
2. Create a CMake project in VSCode 
3. Follow the instructions at github.com/Microsoft/vcpkg and the last time vcpkg was called
4. Look at the bug in VSCode or build the project
Repro code when

**Expected behavior**
No errors.

**Failure logs** 
no 

**Additional context**
I don't know if this question belongs here.
Also, if allowed, I would like to refer to my question on StackOverflow: https://stackoverflow.com/questions/66060463/vscode-c-the-file-source-cannot-be-opened-boolinq-boolinq-h

**Comment by JonLiu1993** [comment]
@DennisPodbicanin ,Thanks for posting this issue,Can you provide your CMakeLists and your error log?

**Comment by JackBoosY** [comment]
@DennisPodbicanin  Can you please provide a sample project to reproduce this issue?

Thanks.

**Comment by DennisPodbicanin** [comment]
Hi, I have solved my problem.
Thanks for your help.

**Comment by Heming9** [comment]
I have the same issue can you tell me how to fix this problem?

**Comment by JackBoosY** [comment]
@Heming9  Since our VS Code plugin is not done, please add vcpkg tool-chain to the cmake configration in VS Code.

**Comment by Heming9** [comment]
> @Heming9 Since our VS Code plugin is not done, please add vcpkg tool-chain to the cmake configration in VS Code.

Thanks for your reply, I had tried adding vcpkg.make to the CMake configuration or the CMakeLists but it still occurs headers not found. For now, I‘m using third packages from vcpkg by including manually in CMakeLists and it compiles successfully. Looking forward to your VS Code plugin :D

**Comment by JackBoosY** [comment]
@Heming9  Did you install the ports using static triplet?

**Comment by JackBoosY** [comment]
@Heming9 Please pass `-DVCPKG_TARGET_TRIPLET=x86-windows` or `-DVCPKG_TARGET_TRIPLET=x86-windows-static` to the cmake parameters.
