### ISSUE TITLE
[New Port Request] <Open3D>

### ISSUE THREAD

**Issue by wenduof** [microsoft/vcpkg#16104]
Library name:Open3D

Library description:A Modern Library for 3D Data Processing

Source repository URL: https://github.com/intel-isl/Open3D

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by NancyLi1013** [comment]
Hi @wenduof 

Thanks for posting this issue. It's duplicated to #15980. 
So let's track this issue there.
