### ISSUE TITLE
cpp-redis portfile.cmake has an error

### ISSUE THREAD

**Issue by fxconfig** [Microsoft/vcpkg#1610]
there's no such cmkelist file in port/cpp-redis/tacopie/

`The following packages will be built and installed:
    cpp-redis:x86-windows-static
Building package cpp-redis:x86-windows-static...
-- CURRENT_INSTALLED_DIR=D:/gitt/vcpkg/installed/x86-windows-static
-- DOWNLOADS=D:/gitt/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=D:/gitt/vcpkg/packages/cpp-redis_x86-windows-static
-- CURRENT_BUILDTREES_DIR=D:/gitt/vcpkg/buildtrees/cpp-redis
-- CURRENT_PORT_DIR=D:/gitt/vcpkg/ports/cpp-redis/.
-- Downloading https://github.com/Cylix/cpp_redis/archive/3.5.2.tar.gz...
-- Downloading https://github.com/Cylix/cpp_redis/archive/3.5.2.tar.gz... OK
-- Testing integrity of downloaded file...
-- Testing integrity of downloaded file... OK
-- Extracting done
CMake Error at ports/cpp-redis/portfile.cmake:15 (file):
  file COPY cannot find
  "D:/gitt/vcpkg/ports/cpp-redis/tacopie/CMakeLists.txt".
Call Stack (most recent call first):
  scripts/ports.cmake:72 (include)

Error: Building package cpp-redis:x86-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: cpp-redis:x86-windows-static
  Vcpkg version: 0.0.81-b277b4dda3a2793fd59a6cca5de96f8bc65f1357`

**Comment by ras0219-msft** [comment]
Thanks for reporting this issue!

It should be fixed in the latest master.
