### ISSUE TITLE
Regression - vcpkg caches binaries in C:\Users\%username%\AppData\Local\vcpkg\

### ISSUE THREAD

**Issue by heydojo** [microsoft/vcpkg#16100]
**Describe the bug**

In an unwelcome change, vcpkg now stores built binaries in `C:\Users\%username%\AppData\Local\vcpkg\
`
This is a regression. As the copying of binaries to a location on the C:\ is almost always unnecessary. 

**Environment**
- OS: Windows 10 Pro
- Compiler: The CXX compiler identification is MSVC 19.28.29335.0

**To Reproduce**
1. Build something using vcpkg and the code sitting in git
2. Check `C:\Users\%username%\AppData\Local\vcpkg\` after successfully building any package.

**Expected behavior**

Binaries are saved by default somewhere inside of the vcpkg directory and not in `C:\Users\%username%\AppData\Local\vcpkg\` There should be a properly documented command line switch to stipulate the path also.

**Additional context**

Please note the following:

- Common use for vcpkg is CI/CD builds. CI/CD builds in most instances need to cache output binaries. `C:\Users\%username%\AppData\Local\vcpkg\` isn't the place for this cache to exist.
- Modern PC desktop machines used for developing software almost always have two hard drives. The operating system resides on the main hard drive, which is a solid state drive. Solid state drives are no good for building software on. The write speed is too slow. This is why software developers attach another (usually mechanical) drive to build the software on. SSD drives are traditionally smaller than their mechanical counter parts and often don't have the space available for vcpkg to spam a ton of binaries onto (Qt is around 600MB alone.)
- vcpkg doing anything with vcpkg outside of the vcpkg tree is a huge no from me. It raises suspicions of foul play as their is literally no reason to do so.

Please use a .gitignore entry for a binaries directory. Then add the binary cache directory where you can guarantee to be able to cache built binaries successfully, by default. This should be somewhere inside of the cloned vcpkg directory so that wherever vcpkg is built, the cache can be saved easily, won't bog down the operating system and be hidden away from the build directory.

If there are command line switches for changing any of what has been described, please:

- Document them
- Set defaults inline with general expectations instead of what currently happens

Thanks

**Comment by Hoikas** [comment]
[Documentation is available](https://github.com/microsoft/vcpkg/blob/master/docs/users/binarycaching.md#configuration) for this feature and seems to address all of your questions.

**Comment by JackBoosY** [comment]
cc @ras0219

**Comment by StarGate-One** [comment]
- use the VCPKG_BINARY_SOURCES environment variable to move the caching to a directory within the vcpkg instance tree i.e. `VCPKG_BINARY_SOURCES           clear;files,[vcpkg-root]\archives,readwrite` -or-
- use the VCPKG_FEATURE_FLAGS environment variable to turn off binary caching ie
`VCPKG_FEATURE_FLAGS            -binarycaching,-compilertracking,-manifests,-registries,-versions`

**Comment by PazerOP** [comment]
I have encountered this same issue after an upgrade, and did indeed use the solution that @StarGate-One suggested. I have to ask, though,

> Solid state drives are no good for building software on. The write speed is too slow. This is why software developers attach another (usually mechanical) drive to build the software on.

???

**Comment by ras0219-msft** [comment]
Thanks for opening this issue!

We've added automatic binary caching to significantly accelerate use of multiple vcpkg instances and manifests.

There are several ways to configure it, including redirecting the default folder or disabling binary caching entirely in the documentation: https://github.com/microsoft/vcpkg/blob/master/docs/users/binarycaching.md.

Specifically:

1. The environment variable `VCPKG_DEFAULT_BINARY_CACHE` will redirect where binaries will be stored by default
2. Setting the environment variable `VCPKG_BINARY_SOURCES` to `clear` will clear out the default binary source while still enabling you to add new ones on the command line
3. `--feature-flags=-binarycaching` will disable binary caching entirely (however this is a feature flag and may be changed or removed at any time).
