### ISSUE TITLE
[Leptonica] build failure on osx

### ISSUE THREAD

**Issue by Shreeshrii** [microsoft/vcpkg#16116]
**Host Environment**
- Operating System
  Mac OS X
  10.15.7
  19H114
Virtual Environment
  Environment: macos-10.15
  Version: 20210130.1
  Included Software: https://github.com/actions/virtual-environments/blob/macOS-10.15/20210130.1/images/macos/macos-10.15-Readme.md

**To Reproduce**
`./vcpkg install leptonica:x64-osx`

**Failure logs** 
```
Starting package 10/19: leptonica:x64-osx
Building package leptonica[core]:x64-osx...
-- Downloading https://github.com/DanBloomberg/leptonica/archive/1ac72c93fef1a5eb76b76d6723d2aee843dd6e51.tar.gz -> DanBloomberg-leptonica-1ac72c93fef1a5eb76b76d6723d2aee843dd6e51.tar.gz...
-- Extracting source /Users/runner/work/tesseract/tesseract/vcpkg/downloads/DanBloomberg-leptonica-1ac72c93fef1a5eb76b76d6723d2aee843dd6e51.tar.gz
-- Applying patch fix-cmakelists.patch
-- Applying patch find-dependency.patch
-- Applying patch fix-find-libwebp.patch
-- Using source at /Users/runner/work/tesseract/tesseract/vcpkg/buildtrees/leptonica/src/e843dd6e51-82c465ff89.clean
-- Configuring x64-osx-dbg
-- Configuring x64-osx-rel
-- Building x64-osx-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:145 (message):
    Command failed: /Users/runner/work/tesseract/tesseract/vcpkg/downloads/tools/cmake-3.19.2-osx/cmake-3.19.2-macos-universal/CMake.app/Contents/bin/cmake --build . --config Debug --target install -- -v -j4
    Working Directory: /Users/runner/work/tesseract/tesseract/vcpkg/buildtrees/leptonica/x64-osx-dbg
    See logs for more information:
      /Users/runner/work/tesseract/tesseract/vcpkg/buildtrees/leptonica/install-x64-osx-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:27 (vcpkg_build_cmake)
  ports/leptonica/portfile.cmake:24 (vcpkg_install_cmake)
  scripts/ports.cmake:128 (include)


Error: Building package leptonica:x64-osx failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: leptonica:x64-osx
  Vcpkg version: 2021-01-13-unknownhash

Additionally, attach any relevant sections from the log files above.
Error: Process completed with exit code 1.
```

**Additional context**
Problem faced when trying to build Tesseract. Builds for Linux and Windows are ok.
See https://github.com/Shreeshrii/tesseract/runs/1861772983?check_suite_focus=true#step:11:1 for more details

**Comment by JonLiu1993** [comment]
@Shreeshrii ,I can successfully build leptonica:x64-osx locally, can you send me this error log?
_/Users/runner/work/tesseract/tesseract/vcpkg/buildtrees/leptonica/install-x64-osx-dbg-out.log_

**Comment by Shreeshrii** [comment]
@JonLiu1993 I am not building it locally (don't have a Mac). It is part of a Github Actiosn Workflow.

The build is still failing. The _/Users/runner/work/tesseract/tesseract/vcpkg/buildtrees/leptonica/install-x64-osx-dbg-out.log_ can be seen at 

https://github.com/Shreeshrii/tesseract/runs/1861772983?check_suite_focus=true#step:11:1

**Comment by Shreeshrii** [comment]
Here is the error log copied from the above.

[lept-mac-log.txt](https://github.com/microsoft/vcpkg/files/5950428/lept-mac-log.txt)

**Comment by NancyLi1013** [comment]
@Shreeshrii 

From https://github.com/Shreeshrii/tesseract/runs/1861772983?check_suite_focus=true#step:11:1, we get the error like this:
```
/Users/runner/work/tesseract/tesseract/vcpkg/buildtrees/leptonica/src/e843dd6e51-82c465ff89.clean/src/gifio.c:180:54: error: too many arguments to function call, expected 2, have 3
    if ((gif = DGifOpen((void*)&buffer, gifReadFunc, NULL)) == NULL)
               ~~~~~~~~                              ^~~~
/Applications/Xcode_12.3.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include/sys/_types/_null.h:30:15: note: expanded from macro 'NULL'
#define NULL  __DARWIN_NULL
              ^~~~~~~~~~~~~
/Applications/Xcode_12.3.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include/sys/_types.h:52:23: note: expanded from macro '__DARWIN_NULL'
#define __DARWIN_NULL ((void *)0)
                      ^~~~~~~~~~~
/Library/Frameworks/Mono.framework/Headers/gif_lib.h:188:1: note: 'DGifOpen' declared here
GifFileType *DGifOpen(void *userPtr, InputFunc readFunc);    /* new one
```
It seems that this is related with your test environment, maybe Xcode version, please see https://github.com/Shreeshrii/tesseract/runs/1861772983?check_suite_focus=true#step:11:1

https://developer.apple.com/forums/thread/661030

https://developer.apple.com/forums/thread/666701

**Comment by Shreeshrii** [comment]
Thanks for investigating this.

Which xcode version do you recommend that I use?

Are you able to build tesseract with the latest version of vcpkg and ports? Or should I be using an older commit?

**Comment by Shreeshrii** [comment]
@NancyLi1013 I have tried with multiple Xcode versions. Still not able to build leptonica on osx.

See https://github.com/Shreeshrii/tesseract/actions/workflows/vcpkg-4.11.yml

and

https://github.com/Shreeshrii/tesseract/runs/2077177621?check_suite_focus=true#step:7:1

**Comment by JonLiu1993** [comment]
@Shreeshrii ,Is this still a problem for you？

**Comment by Shreeshrii** [comment]
@JonLiu1993 Yes. It still fails. Please see https://github.com/Shreeshrii/tesseract/runs/2147039594?check_suite_focus=true

I am cloning vcpkg repo and building. I have tried with diff Xcode compilers.

Can you try building it without using the cached packages?

**Comment by JonLiu1993** [comment]
@Shreeshrii ,I repo vcpkg on my local machine, and rebuilt Leptonica, it can be successfully built, I read your build log, it seems that it is related to your build environment

**Comment by Shreeshrii** [comment]
Thanks for checking @JonLiu1993 .
Which Xcode compiler did you use?

**Comment by JonLiu1993** [comment]
@Shreeshrii ，I investigated my local machine, but it did not use xcodebuild：
Clang: 12.0 build 1200
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.1-x86_64
CLT: 12.3.0.0.1.1607026830
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11

**Comment by Shreeshrii** [comment]
Thank you. Appreciate the investigation. 
I am building in macOS 10.15 vm. I will try with clang and share results.

**Comment by adelpit** [comment]
I am seeing the same issue.  I was on native macos 10.15 when I first saw the issue.  I then upgraded to 11.2 and am still seeing it.

**Comment by TheKuko** [comment]
I ended up with the same problem. I believe the root of the problem is that the build uses system's version of `giflib` instead of the one built by `vcpkg`. 

When you look closely at the log that @Shreeshrii posted, you can see, for example, that during the build of `gifio.c` it uses `gif_lib.h` located at `/Library/Frameworks/Mono.framework/Headers` instead of the one that `vcpkg` downloaded and built as `leptonica`'s dependency.

I suppose it hapenning because in the build command:
```
2021-02-09T09:44:28.9473890Z /Applications/Xcode_12.3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -DDEBUG -DHAVE_CONFIG_H -I/Users/runner/work/tesseract/tesseract/vcpkg/buildtrees/leptonica/src/e843dd6e51-82c465ff89.clean/src -Isrc -I/Library/Frameworks/Mono.framework/Headers -isystem /Users/runner/work/tesseract/tesseract/vcpkg/installed/x64-osx/include -fPIC -g -Wall -Wextra -Werror=format-security -pedantic -Og -g3 -fdebug-prefix-map=/Users/runner/work/tesseract/tesseract/vcpkg/buildtrees/leptonica/src/e843dd6e51-82c465ff89.clean=. -arch x86_64 -isysroot /Applications/Xcode_12.3.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -mmacosx-version-min=10.15 -MD -MT src/CMakeFiles/leptonica.dir/gifio.c.o -MF src/CMakeFiles/leptonica.dir/gifio.c.o.d -o src/CMakeFiles/leptonica.dir/gifio.c.o -c /Users/runner/work/tesseract/tesseract/vcpkg/buildtrees/leptonica/src/e843dd6e51-82c465ff89.clean/src/gifio.c
```
the `-I/Library/Frameworks/Mono.framework/Headers` parameter is placed BEFORE `-isystem /Users/runner/work/tesseract/tesseract/vcpkg/installed/x64-osx/include` so it takes the system's `giflib` version and therefore function declarations do not fit what `leptonica` uses. 

I'm not a CMake master and even after several hours I could not locate where the path to Mono.framework headers comes from so in the end I just renamed system's folder so its headers were not used. Then I was able to build both `leptonica` and `tesseract` without any problem.

**Comment by JonLiu1993** [comment]
@Shreeshrii ,Does this problem still exist?

**Comment by JonLiu1993** [comment]
Thanks for posting this issue. Please reopen this issue if it still be a problem for you.
