### ISSUE TITLE
Working with OMPL

### ISSUE THREAD

**Issue by 200201141** [microsoft/vcpkg#16118]
I needed to run an application which is dependent to vcpkg libraries. 
I installed vcpkg and required libraries like boost, eigen and ompl. I just tried to create a Helloworld app with OMPL but 
it failed.  It seems it is about boost installation. 

I think boost is up-to-date, is there anything else to do after installing boost via vcpkg?  

CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find Boost (missing: Boost_INCLUDE_DIR serialization filesystem
  system program_options) (Required is at least version "1.58")		

C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake	165

**Comment by MVoz** [comment]
As an variant
rename folder
`C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/` -->> `__CMake__`
old version cmake

**Comment by PhoebeHui** [comment]
@200201141, ompl depends on boost, please add the following code in your cmake porject and try again.

```
find_package(Boost REQUIRED COMPONENTS filesystem)
target_link_libraries(main PRIVATE ${Boost_LIBRARIES})
target_include_directories(main PRIVATE ${Boost_INCLUDE_DIRS})
```

**Comment by 200201141** [comment]
I'm using Visual Studio 2019. Would you recommend me a guide about how to set boost settings in Visual Studio?

**Comment by PhoebeHui** [comment]
@200201141, please reference https://github.com/microsoft/vcpkg/blob/master/docs/examples/installing-and-using-packages.md to get a guide. Let me know if you have any questions about it.

**Comment by 200201141** [comment]
The problem is solved right now, thank you.

**Comment by PhoebeHui** [comment]
Great!
