### ISSUE TITLE
[New Port Request] LimeReport

### ISSUE THREAD

**Issue by Jihadist** [microsoft/vcpkg#16117]
Library name:
LimeReport
Library description:
Report generator engine for Qt framework
Source repository URL:
https://github.com/fralx/LimeReport
Project homepage (if different from the source repository):
https://limereport.ru/en/index.php
Anything else that is useful to know when adding (such as optional features the library may have that should be included):
LimeReport has additional depends under different licences, QZint (Qt wrapper for zint) licensed under GPL while core zint licensed under BSD, other dependencies licensed under MIT but LimeReport licensed under LGPL so it should be build under LGPL (without Zint) and under GPL (with Zint).

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by liangyu304** [comment]
So, does vcpkg not have LimeReport yet?
