### ISSUE TITLE
(a dependency): unexpected field 'version=', did you mean 'version>='?

### ISSUE THREAD

**Issue by Coderx7** [microsoft/vcpkg#16133]
**Describe the bug**
I'm creating a vcpkg package for my own library and it requires specific version of protobuf (i.e. 3.11.4). Based on the documentation available [here ](https://github.com/microsoft/vcpkg/blob/master/docs/specifications/versioning.md#42-declaring-minimum-version-constraints) I should be able to specify the package version using `version=` or `version>=` like the provided example shows i.e. : 
```json
{
  "name": "project",
  "version-semver": "1.0.0",
  "dependencies": [
    { "name": "zlib", "version>=": "1.2" },
    { "name": "rapidjson", "version>=": "2020-02-01" }
  ]
}
```
However upon trying to use `version=` instead of `version>=` I face the aforementioned error : 
```
D:\External libs\vcpkg>vcpkg install fv-windows:x64-windows-static --feature-flags=versions
Computing installation plan...
Errors occurred while parsing D:\External libs\vcpkg\ports\fv-windows\vcpkg.json
    $.dependencies[1] (a dependency): unexpected field 'version=', did you mean 'version>='?
Error: failed to load port from D:\External libs\vcpkg\ports\fv-windows
Note: Updating vcpkg by rerunning bootstrap-vcpkg may resolve this failure.
```
And t his is how my vcpk.json looks like : 
```json
{
  "name": "fv-windows",
  "version-string": "1.1.0",
  "homepage": "github.com",
  "description": "some description....",
  "dependencies":[
  "opencv4",
  { "name": "protobuf", "version=": "3.11.4" }
  ]
}
```

I also tried override to no avail which looked like this : 
```json
{
  "name": "fv-windows",
  "version-string": "1.1.0",
  "homepage": "github.com",
  "description": "some description....",
  "dependencies":[
  "opencv4","protobuf"
  ],
  "overrides": [{"name": "protobuf", "version": "3.11.4"}]
}
```
It does not issue any errors, but it always grabs the latest version of the protobuf so this wasn't a solution either. 
**Environment**
- OS: Windows
- Compiler: v16.8.4

**To Reproduce**
1. set a specific dependency version on any package
2. See error

**Expected behavior**
should be able to specify the version and only install the respective dependency

**Failure logs** 
-(please attached failure logs)

**Additional context**

**Comment by JackBoosY** [comment]
cc @vicroms

**Comment by vicroms** [comment]
Hi @Coderx7

The spec was written before we started implementation and some things changed along the way. 
One thing that changes is that we removed "version=" constraints.

Try reading our most up-to-date [documentation regarding constraints](https://github.com/microsoft/vcpkg/blob/master/docs/users/versioning.md#constraints) and our [Getting Started with Versioning guide](https://github.com/microsoft/vcpkg/blob/master/docs/users/versioning.getting-started.md).
I'm still working on the documentation, so any bit of feedback helps!

Back to your manifest: you had it right with using `overrides` to force a specific version, but you are lacking a `builtin-baseline`. **Setting a baseline is required to enable versioning**, otherwise you will get the current versions on the ports directory. It was my understanding that we would print an error when version constraints were used without a baseline, but it seems that is not the case.

You can run `git rev-parse HEAD` to get the current commit of vcpkg and set it as the `builtin-baseline`.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

**Comment by george-tsiros** [comment]
i just want to vcpkg install glfw3 version 3.3.1 instead of 3.3.4

i have read through two threads that span 4 years

how did you manage to create a tool that makes things WORSE?

**Comment by JackBoosY** [comment]
@george-tsiros 
```
PS F:\vcpkg> .\vcpkg.exe x-history glfw3
             version          date    vcpkg commit
             3.3.4#0    2021-05-18    03c81310b52433a4137bb483b0c715aec8e70081
             3.3.3#0    2021-03-29    8a8eb7194187f9e79fcd79601573a8b0c17ebf0d
             3.3.2#1    2021-02-10    087869eb3a70f17dd98b4a9ebd7182ab31a4b1e4
             3.3.2#0    2020-02-02    6d1cd558e6183e1b821150681b0c703badcdb591
             3.3.1#0    2020-01-14    d73e5209e89308a61d4e08547db48b3ccfb6e8bd
             3.3-3#0    2019-10-07    726c11148105a97aef39bec024fdb7c140b1b154
             3.3-2#0    2019-09-10    dce685696ae8450c6cf6c801012feeecc1d3119d
             3.3-1#0    2019-07-31    bcff929875d76ade98c251038eea6f48171facc6
               3.3#0    2019-06-15    18b029a5e3997fa4fdc7d3d06d56568a1d6f74ad
           3.2.1-3#0    2018-11-06    ab0212d6930011041683f7acc016323bd4ecf4fe
           3.2.1-2#0    2017-09-09    26516fe485b0e9048dd4809256a7e4526957c6e9
           3.2.1-1#0    2017-03-30    e8441676e3c2ef8e65087306457a7e6ec36dc89f
             3.2.1#0    2016-11-16    21c4404d393ec7fdb6513eaba01e63073e5f8e33
             3.1.2#0    2016-09-28    36799555441089420f29fcb2724d9fde23bc9ec1
```
If you use the command line, please reset vcpkg to d73e5209e89308a61d4e08547db48b3ccfb6e8bd and rebuild glfw3.
If you use manifest, please see our [versioning document](https://github.com/microsoft/vcpkg/blob/master/docs/users/versioning.md#version-1).
