### ISSUE TITLE
[New Port Request] workflow

### ISSUE THREAD

**Issue by dengjunplusplus** [microsoft/vcpkg#16139]
Library name: workflow

Library description: About C++ Parallel Computing and Asynchronous Networking Engine

Source repository URL: https://github.com/sogou/workflow

**Comment by dengjunplusplus** [comment]
[related pull request](https://github.com/microsoft/vcpkg/pull/16140)

**Comment by JonLiu1993** [comment]
Solved by #16140

**Comment by autoantwort** [comment]
You can close this issue
