### ISSUE TITLE
[Windows] python3 build failure

### ISSUE THREAD

**Issue by derossm** [microsoft/vcpkg#16132]
Package: python3:x64-windows
Vcpkg version: 2021-01-13-unknownhash

using very latest available pull of vcpkg as of this moment (same issue with previous pull yesterday, so not new to the latest)

**Host Environment**
- OS: Windows 10
- Compiler: msvc 16.9 preview 3

**To Reproduce**
`./vcpkg install python3`

**Failure logs** 
Error: Building package python3:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: python3:x64-windows
  Vcpkg version: 2021-01-13-unknownhash

Additionally, attach any relevant sections from the log files above.
PS G:\dev\vcpkg> vcpkg update
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.
PS G:\dev\vcpkg> git pull
Already up to date.
PS G:\dev\vcpkg> vcpkg upgrade
All installed packages are up-to-date with the local portfiles.
PS G:\dev\vcpkg> vcpkg install python3
Computing installation plan...
The following packages will be built and installed:
    python3[core]:x64-windows -> 3.9.0#3
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\deros\AppData\Local\vcpkg\archives\96\96e412890ca9d403439faef09e7f7e9b33ec4489.zip
Starting package 1/1: python3:x64-windows
Building package python3[core]:x64-windows...
-- Using cached G:/dev/vcpkg/downloads/python-cpython-v3.9.0.tar.gz
-- Cleaning sources at G:/dev/vcpkg/buildtrees/python3/src/v3.9.0-664bf2a259.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source G:/dev/vcpkg/downloads/python-cpython-v3.9.0.tar.gz
-- Applying patch 0002-use-vcpkg-zlib.patch
-- Applying patch 0003-devendor-external-dependencies.patch
-- Applying patch 0004-dont-copy-vcruntime.patch
-- Applying patch 0005-only-build-required-projects.patch
-- Applying patch 0006-fix-duplicate-symbols.patch
-- Using source at G:/dev/vcpkg/buildtrees/python3/src/v3.9.0-664bf2a259.clean
-- Building PCbuild/pcbuild.proj for Release
-- Building PCbuild/pcbuild.proj for Debug
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:108 (message):
    Command failed: msbuild G:/dev/vcpkg/buildtrees/python3/x64-windows-dbg/v3.9.0-664bf2a259.clean/PCbuild/pcbuild.proj /p:Configuration=Debug /p:IncludeExtensions=true /p:IncludeExternals=true /p:IncludeCTypes=true /p:IncludeSSL=true /p:IncludeTkinter=false /p:IncludeTests=false /p:ForceImportBeforeCppTargets=G:/dev/vcpkg/buildtrees/python3/src/v3.9.0-664bf2a259.clean/PCbuild/python_vcpkg.props /p:IncludeUwp=false /p:_VcpkgPythonLinkage=DynamicLibrary /t:Rebuild /p:Platform=x64 /p:PlatformToolset=v142 /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /p:WindowsTargetPlatformVersion=10.0.19041.0 /p:VcpkgTriplet=x64-windows /p:VcpkgCurrentInstalledDir=G:/dev/vcpkg/installed/x64-windows /p:VcpkgManifestInstall=false /m
    Working Directory: G:/dev/vcpkg/buildtrees/python3/x64-windows-dbg/v3.9.0-664bf2a259.clean
    Error code: 1
    See logs for more information:
      G:\dev\vcpkg\buildtrees\python3\build-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_msbuild.cmake:194 (vcpkg_execute_required_process)
  ports/python3/portfile.cmake:101 (vcpkg_install_msbuild)
  scripts/ports.cmake:128 (include)

Error: Building package python3:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: python3:x64-windows
  Vcpkg version: 2021-01-13-unknownhash

Additionally, attach any relevant sections from the log files above.

**Additional context**
N/A - issue is unknown hash

**Comment by NancyLi1013** [comment]
Hi @derossm 

Thanks for posting this issue.
Could you please provide the error log `G:\dev\vcpkg\buildtrees\python3\build-x64-windows-dbg-out.log`?

**Comment by frank-jeo** [comment]
I 'm building osgEarth package and also have this problem. It seems to be the same problem.  
the release build is fine, and failed to built the debug version. I checked the log file and found that problem might came with the _“**python_d.exe**”_ generated in [_D:\vcpkg\buildtrees\python3\x64-windows-dbg\v3.9.0-664bf2a259.clean\PCbuild\amd64_] directory. Running the program in the DOS shell caused the program to crash directly。

I checked the event viewer, there is the msg:

 python_d.exe 
   3.9.150.1013 
   602d4c46 
   ucrtbased.dll 
   10.0.18362.1 
   b3fe38ca 
   80000003 
   00000000000c8036 
   d58c 
   01d7054ef49fa63d 
   D:\vcpkg\buildtrees\python3\x64-windows-dbg\v3.9.0-664bf2a259.clean\PCbuild\amd64\python_d.exe 
   C:\Windows\system32\ucrtbased.dll 

I have no any more idea to do further check,  I'm using  Visual Studio 2019 and Windows 7.

**ensurepip-x64-windows-err.log:**:
Traceback (most recent call last):
  File "D:\vcpkg\packages\python3_x64-windows\tools\python3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\vcpkg\packages\python3_x64-windows\tools\python3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\vcpkg\packages\python3_x64-windows\tools\python3\lib\ensurepip\__main__.py", line 5, in <module>
    sys.exit(ensurepip._main())
  File "D:\vcpkg\packages\python3_x64-windows\tools\python3\lib\ensurepip\__init__.py", line 210, in _main
    return _bootstrap(
  File "D:\vcpkg\packages\python3_x64-windows\tools\python3\lib\ensurepip\__init__.py", line 129, in _bootstrap
    return _run_pip(args + [p[0] for p in _PROJECTS], additional_paths)
  File "D:\vcpkg\packages\python3_x64-windows\tools\python3\lib\ensurepip\__init__.py", line 38, in _run_pip
    return subprocess.run([sys.executable, "-c", code], check=True).returncode
  File "D:\vcpkg\packages\python3_x64-windows\tools\python3\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "D:\vcpkg\packages\python3_x64-windows\tools\python3\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\vcpkg\packages\python3_x64-windows\tools\python3\lib\subprocess.py", line 1416, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,FileNotFoundError: [WinError 2] 


**build-x64-windows-dbg-out.log**
D:\vcpkg\buildtrees\python3\x64-windows-dbg\v3.9.0-664bf2a259.clean\PCbuild\ pcbuild.proj (rebuild target) (1) - >
“D:\vcpkg\buildtrees\python3\x64-windows-dbg\v3.9.0-664bf2a259.clean\PCbuild\ python.vcxproj ”(build goal) (4:2) - >
(validateucrtbase target) - >
D:\vcpkg\buildtrees\python3\x64-windows-dbg\v3.9.0-664bf2a259.clean\PCbuild\ python.vcxproj (123,5): warning MSB3073: command "setlocal D:\vcpkg\buildtrees\python3\x64-windows-dbg\v3.9.0-664bf2a259.clean\PCbuild\ python.vcxproj (123,5): warning MSB3073: set PYTHONPATH=D:\vcpkg\buildtrees\python3\x64-windows-dbg\v3.9.0-664bf2a259.clean\Lib

D:\vcpkg\buildtrees\python3\x64-windows-dbg\v3.9.0-664bf2a259.clean\PCbuild\ python.vcxproj (123,5): warning MSB3073: "D:\vcpkg\buildtrees\python3\x64-windows-dbg\v3.9.0-664bf2a259.clean\PCbuild\amd64\python_ d.exe" "D:\vcpkg\buildtrees\python3\x64-windows-dbg\v3.9.0-664bf2a259.clean\PC\validate_ ucrtbase.py "Ucrtbased" exited with code - 2147483645.

D:\vcpkg\buildtrees\python3\x64-windows-dbg\v3.9.0-664bf2a259.clean\PCbuild\ python.vcxproj (123,5): warning msb4181: "exec" task returned false, but no error was recorded.

**Comment by Hoikas** [comment]
@frank-jeo At this time, the Python 3 port does not function on Windows 7. Python broke compatibility with anything older than Windows 8 with Python 3.9.0

**Comment by joe-ieta** [comment]
Thank you @Hoikas ,may be it's my turn to drop windows 7.

**Comment by JonLiu1993** [comment]
@derossm , Could you please provide the error log G:\dev\vcpkg\buildtrees\python3\build-x64-windows-dbg-out.log?

**Comment by JonLiu1993** [comment]
> Thank you @Hoikas ,may be it's my turn to drop windows 7. But it's strange, why it is OK with release build but failure with debug build? any advice or idea ?

@Hoikas ,Could you please take a look?

**Comment by JonLiu1993** [comment]
> Thank you @Hoikas ,may be it's my turn to drop windows 7. But it's strange, why it is OK with release build but failure with debug build? any advice or idea ?

@Hoikas ,Could you explain the reason for this?

**Comment by JonLiu1993** [comment]
Thanks for posting this issue. Please reopen this issue if it still be a problem for you.
