### ISSUE TITLE
[boost-math] build failure

### ISSUE THREAD

**Issue by fl0kng** [microsoft/vcpkg#16141]
**Host Environment**
- OS: Windows 10
- Compiler: revision

**To Reproduce**
`./vcpkg install pcl`

**Failure logs** 
Building package boost-math[core]:x86-windows...
-- Using cached D:/dev/vcpkg/downloads/boostorg-math-boost-1.75.0.tar.gz
-- Cleaning sources at D:/dev/vcpkg/buildtrees/boost-math/src/ost-1.75.0-eaa6889798.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/dev/vcpkg/downloads/boostorg-math-boost-1.75.0.tar.gz
-- Using source at D:/dev/vcpkg/buildtrees/boost-math/src/ost-1.75.0-eaa6889798.clean
-- Building x86-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:108 (message):
    Command failed: D:/dev/vcpkg/installed/x86-windows/tools/boost-build/b2.exe --stagedir=D:/dev/vcpkg/buildtrees/boost-math/x86-windows-rel/stage --build-dir=D:/dev/vcpkg/buildtrees/boost-math/x86-windows-rel --user-config=D:/dev/vcpkg/buildtrees/boost-math/x86-windows-rel/user-config.jam -j8 --debug-configuration --debug-building --debug-generators --disable-icu --ignore-site-config --hash -q -sZLIB_INCLUDE=D:/dev/vcpkg/installed/x86-windows/include -sBZIP2_INCLUDE=D:/dev/vcpkg/installed/x86-windows/include -sLZMA_INCLUDE=D:/dev/vcpkg/installed/x86-windows/include -sZSTD_INCLUDE=D:/dev/vcpkg/installed/x86-windows/include threading=multi threadapi=win32 runtime-link=shared link=shared address-model=32 architecture=x86 -sZLIB_BINARY=zlib -sZLIB_LIBPATH=D:/dev/vcpkg/installed/x86-windows/lib -sBZIP2_BINARY=bz2 -sBZIP2_LIBPATH=D:/dev/vcpkg/installed/x86-windows/lib -sLZMA_BINARY=lzma -sLZMA_LIBPATH=D:/dev/vcpkg/installed/x86-windows/lib -sZSTD_BINARY=zstd -sZSTD_LIBPATH=D:/dev/vcpkg/installed/x86-windows/lib variant=release debug-symbols=on
    Working Directory: D:/dev/vcpkg/buildtrees/boost-math/src/ost-1.75.0-eaa6889798.clean/build
    Error code: 1
    See logs for more information:
      D:\dev\vcpkg\buildtrees\boost-math\build-x86-windows-rel-out.log

Call Stack (most recent call first):
  installed/x86-windows/share/boost-build/boost-modular-build.cmake:364 (vcpkg_execute_required_process)
  ports/boost-math/portfile.cmake:12 (boost_modular_build)
  scripts/ports.cmake:128 (include)

Error: Building package boost-math:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-math:x86-windows
  Vcpkg version: 2021-01-13-768d8f95c9e752603d2c5901c7a7c7fbdb08af35

[build-x86-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/5950420/build-x86-windows-rel-out.log)

**Comment by PhoebeHui** [comment]
@fl0kng, could you check if 'boost_math_tr1f-vc142-mt-x32-1_75.dll' generated correctly? I can't repro this issue locally, it built successfully for me.

Failures
```
LINK : fatal error LNK1104: cannot open file 'D:\dev\vcpkg\buildtrees\boost-math\x86-windows-rel\boost\build\d74f77589f5a5baab084c0bf23014c62\boost_math_tr1f-vc142-mt-x32-1_75.dll'
```

**Comment by fl0kng** [comment]
No it isn't. Some others are though:

09.02.2021  10:34            35 328 boost_math_c99-vc142-mt-x32-1_75.dll
09.02.2021  10:34            34 816 boost_math_c99f-vc142-mt-x32-1_75.dll
09.02.2021  10:34            33 280 boost_math_c99l-vc142-mt-x32-1_75.dll
09.02.2021  10:34           122 368 boost_math_tr1-vc142-mt-x32-1_75.dll

> @fl0kng, could you check if 'boost_math_tr1f-vc142-mt-x32-1_75.dll' generated correctly? I can't repro this issue locally, it built successfully for me.
> 
> Failures
> 
> ```
> LINK : fatal error LNK1104: cannot open file 'D:\dev\vcpkg\buildtrees\boost-math\x86-windows-rel\boost\build\d74f77589f5a5baab084c0bf23014c62\boost_math_tr1f-vc142-mt-x32-1_75.dll'
> ```

**Comment by PhoebeHui** [comment]
@fl0kng, could you try the following step and see if boost_math_tr1f-vc142-mt-x32-1_75.dll generate?

1. Open x86 Native tools command prompt for vs2019
2. Go to D:\dev\vcpkg\buildtrees\boost-math\x86-windows-rel
3. Execute the following command
```
link /NOLOGO /INCREMENTAL:NO /DLL /DEBUG /MACHINE:X86 /MANIFEST:EMBED /OPT:REF,ICF /subsystem:console /out:"D:\dev\vcpkg\buildtrees\boost-math\x86-windows-rel\boost\build\d74f77589f5a5baab084c0bf23014c62\boost_math_tr1f-vc142-mt-x32-1_75.dll" /IMPLIB:"D:\dev\vcpkg\buildtrees\boost-math\x86-windows-rel\boost\build\d74f77589f5a5baab084c0bf23014c62\boost_math_tr1f-vc142-mt-x32-1_75.lib"     @"D:\dev\vcpkg\buildtrees\boost-math\x86-windows-rel\boost\build\d74f77589f5a5baab084c0bf23014c62\boost_math_tr1f-vc142-mt-x32-1_75.dll.rsp"
```
4. Check if D:\dev\vcpkg\buildtrees\boost-math\x86-windows-rel\boost\build\d74f77589f5a5baab084c0bf23014c62\boost_math_tr1f-vc142-mt-x32-1_75.dll generate

**Comment by fl0kng** [comment]
> @fl0kng, could you try the following step and see if boost_math_tr1f-vc142-mt-x32-1_75.dll generate?
> 
> 1. Open x86 Native tools command prompt for vs2019
> 2. Go to D:\dev\vcpkg\buildtrees\boost-math\x86-windows-rel
> 3. Execute the following command
> 
> ```
> link /NOLOGO /INCREMENTAL:NO /DLL /DEBUG /MACHINE:X86 /MANIFEST:EMBED /OPT:REF,ICF /subsystem:console /out:"D:\dev\vcpkg\buildtrees\boost-math\x86-windows-rel\boost\build\d74f77589f5a5baab084c0bf23014c62\boost_math_tr1f-vc142-mt-x32-1_75.dll" /IMPLIB:"D:\dev\vcpkg\buildtrees\boost-math\x86-windows-rel\boost\build\d74f77589f5a5baab084c0bf23014c62\boost_math_tr1f-vc142-mt-x32-1_75.lib"     @"D:\dev\vcpkg\buildtrees\boost-math\x86-windows-rel\boost\build\d74f77589f5a5baab084c0bf23014c62\boost_math_tr1f-vc142-mt-x32-1_75.dll.rsp"
> ```
> 
> 1. Check if D:\dev\vcpkg\buildtrees\boost-math\x86-windows-rel\boost\build\d74f77589f5a5baab084c0bf23014c62\boost_math_tr1f-vc142-mt-x32-1_75.dll generate

It did generate the file.

**Comment by PhoebeHui** [comment]
That's interesting, can this problem be reproduced stably in your machine?

**Comment by fl0kng** [comment]
> That's interesting, can this problem be reproduced stably in your machine?

Yes. I tried building it multiple times. Also deleted buildtrees and download. It still doesn't build...

**Comment by fl0kng** [comment]
@PhoebeHui I have not used vcpkg for anything else than building pcl (boost-math is a dependency). So maybe my installation is broken? Does that make sense?
What steps to take to clean my system and reinstall everything properly?

**Comment by fl0kng** [comment]
@PhoebeHui Also when i look at the following excerpt from the log it tells me that boost_math_**tr1**-vc142-mt-x32-1_75.dll has been build, but it tries to link boost_math_**tr1f**-vc142-mt-x32-1_75.dll

Does that make sense? I don't think so...


msvc.link.dll D:\dev\vcpkg\buildtrees\boost-math\x86-windows-rel\boost\build\d74f77589f5a5baab084c0bf23014c62\boost_math_tr1-vc142-mt-x32-1_75.dll
   Creating library D:\dev\vcpkg\buildtrees\boost-math\x86-windows-rel\boost\build\d74f77589f5a5baab084c0bf23014c62\boost_math_tr1-vc142-mt-x32-1_75.lib and object D:\dev\vcpkg\buildtrees\boost-math\x86-windows-rel\boost\build\d74f77589f5a5baab084c0bf23014c62\boost_math_tr1-vc142-mt-x32-1_75.exp
msvc.link.dll D:\dev\vcpkg\buildtrees\boost-math\x86-windows-rel\boost\build\d74f77589f5a5baab084c0bf23014c62\boost_math_tr1f-vc142-mt-x32-1_75.dll
LINK : fatal error LNK1104: cannot open file 'D:\dev\vcpkg\buildtrees\boost-math\x86-windows-rel\boost\build\d74f77589f5a5baab084c0bf23014c62\boost_math_tr1f-vc142-mt-x32-1_75.dll'

**Comment by PhoebeHui** [comment]
The 'boost_math_tr1f-vc142-mt-x32-1_75.dll' could be generated correctly with above command, that means it doesn't have compiler issue. 

If you take a look at D:\dev\vcpkg\buildtrees\boost-math\x86-windows-rel\boost\build\d74f77589f5a5baab084c0bf23014c62\boost_math_tr1f-vc142-mt-x32-1_75.dll.rsp file, you will notice that the .obj files that used to llink to boost_math_tr1f-vc142-mt-x32-1_75.dll, It may be relate to multi process.

You can clone a clean vcpkg source, and try to install boost-math again, and see if the dll could be generated.

**Comment by PhoebeHui** [comment]
@fl0kng, does this issue still persist with vcpkg clean source?

**Comment by fl0kng** [comment]
> @fl0kng, does this issue still persist with vcpkg clean source?

yes, same issue.

**Comment by fl0kng** [comment]
Got it to build on a different machine...
