### ISSUE TITLE
vcpkg installed dir is not next to vcpkg.json

### ISSUE THREAD

**Issue by autoantwort** [microsoft/vcpkg#16157]
**Describe the bug**
The installed dir is not next to the vcpkg.json file.

**Environment**
- OS: Windows
- Compiler: Visual Studio 2015

**To Reproduce**
1. Create Project with Solution
2. Add vcpkg as submodule, boostrap, integrate install
3. Create vcpkg file, enable manifest mode in visual studio
4. Build solution

**Expected behavior**
It should be next to the vcpkg,json file?

**Additional context**
Example Repo [here](https://github.com/autoantwort/VcpkgBug).  
Comes from #16069

**Comment by JackBoosY** [comment]
cc @strega-nil

**Comment by autoantwort** [comment]
Fixed by #19767
