### ISSUE TITLE
SPDLOG recent commit is propagating warnings

### ISSUE THREAD

**Issue by prateek9623** [microsoft/vcpkg#16153]
**Describe the bug**
commit https://github.com/microsoft/vcpkg/commit/8a95605a7b757d7a66f4f6e972780e2eaf62d67d is propagating warning /wd4251 /wd4275 to our CUDA based application. Which doesn't go well with warning flags. Is there anything that can be done about this?

**Environment**
- OS: Windows
- Compiler: MSVC(14.28.29333), NVCC 11.2 

**To Reproduce**
link with CUDA based application

**Expected behavior**
the warning should not propagate from spdlog

**Comment by NancyLi1013** [comment]
Hi @prateek9623 

Thanks for posting this issue.

The warning is from upstream, there is no way to solve this. Please see
```
    if(MSVC)
        target_compile_options(spdlog PUBLIC /wd4251 /wd4275)
    endif()
```
https://github.com/gabime/spdlog/blob/v1.x/CMakeLists.txt#L134-L136

You can port an issue to upstream if this blocks your application.

**Comment by prateek9623** [comment]
cant we create a patch to rectify this

**Comment by prateek9623** [comment]
> Hi @prateek9623 
> 
> Thanks for posting this issue.
> 
> The warning is from upstream, there is no way to solve this. Please see
> ```
>     if(MSVC)
>         target_compile_options(spdlog PUBLIC /wd4251 /wd4275)
>     endif()
> ```
> https://github.com/gabime/spdlog/blob/v1.x/CMakeLists.txt#L134-L136
> 
> You can port an issue to upstream if this blocks your application.

cant we create a patch to rectify this

**Comment by prateek9623** [comment]
recent commit in spdlog: https://github.com/gabime/spdlog/commit/8fbc853b0dde6ba5f739cdacd0f3b538876f5695 fixes this issue

**Comment by NancyLi1013** [comment]
Thanks for your kindly reminder @prateek9623. I will use the patch to fix it later.
