### ISSUE TITLE
How do I use QT in my camke project?

### ISSUE THREAD

**Issue by nil-is-lin** [microsoft/vcpkg#16164]
I have installed the qt5 using command `.\vcpkg.exe install qt5:x64-windows`, however, when i use it in my cmakelits with 
`find_package(Qt5 COMPONENTS Widgets Concurrent CONFIG REQUIRED)`,
it throw 

> 严重性	代码	说明	项目	文件	行	禁止显示状态
> 错误		CMake Error at I:\临时存储文件\CppWorkSpace\CMakeLists.txt:38 (find_package):
>   Could not find a package configuration file provided by "Qt5" with any of
>   the following names:
> 
>     Qt5Config.cmake
>     qt5-config.cmake
> 
>   Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
>   to a directory containing one of the above files.  If "Qt5" provides a
>   separate development package or SDK, be sure it has been installed.		I:\临时存储文件\CppWorkSpace\CMakeLists.txt	38	

when i use `find_package(Qt5Gui CONFIG REQUIRED)`, it throws

> CMake Error at I:\临时存储文件\CppWorkSpace\RoughSurface\CMakeLists.txt:38 (find_package):
>   Could not find a package configuration file provided by "Qt5Gui" with any
>   of the following names:
> 
>     Qt5GuiConfig.cmake
>     qt5gui-config.cmake
> 
>   Add the installation prefix of "Qt5Gui" to CMAKE_PREFIX_PATH or set
>   "Qt5Gui_DIR" to a directory containing one of the above files.  If "Qt5Gui"
>   provides a separate development package or SDK, be sure it has been
>   installed.		I:\临时存储文件\CppWorkSpace\RoughSurface\CMakeLists.txt	38	

In fact, it works in my old project. But now all of them failed. I have keep my vcpkg and vs updated with newest version.

**Comment by JackBoosY** [comment]
cc @Neumann-A

**Comment by Neumann-A** [comment]
@JackBoosY: Probably forgot to pass the `vcpkg.cmake` toolchain or correctly set `VCPKG_TARGET_TRIPLET` in the cmake configure call. As long as ParaView/CMake etc. build in CI there is no problem with `find_package(Qt5 COMPONENTS <whatever>)`

**Comment by nil-is-lin** [comment]
@Neumann-A, vcpkg.cmake toolchain means `SET(CMAKE_TOOLCHAIN_FILE "I:/vcpkg/scripts/buildsystems/vcpkg.cmake" CACHE STRING "Vcpkg toolchain file")`, it is in my cmakelists file. Maybe this parameter is wrong, because it can not even use gtest with the same problem. However, this parameter is generated by `.\vcpkg.exe integrate install` . 

> .\vcpkg.exe integrate install
> Applied user-wide integration for this vcpkg root.
> 
> All MSBuild C++ projects can now #include any installed libraries.
> Linking will be handled automatically.
> Installing new libraries will make them instantly available.
> 
> CMake projects should use: "-DCMAKE_TOOLCHAIN_FILE=I:/vcpkg/scripts/buildsystems/vcpkg.cmake"

So it made me confused.
I suspect it's because of the change of the USB drive ID assignment from G to I. How can I check the configuration file corresponding to integrate install?

**Comment by nil-is-lin** [comment]
My problem disappeared. I think the problem may be due to the fact that I used `vcpkg integrate install` in two places at the same time, making the environment conflict. There is nothing wrong with the installer and the usage itself.I'm sorry for the delay because of my native environment issues.
