### ISSUE TITLE
what is the magic behind this tool?

### ISSUE THREAD

**Issue by juandent** [Microsoft/vcpkg#1616]
Hi,

How can all the include files for all installed packages appear in VStudio 2017? Is the include path extended to include the folder within vcpkg? How are the correct libraries selected automatically? Some #pragma comment(lib, "xxxx")? Is the library path also extended to include the libraries within vcpkg?

I just need to know how it works to use it well.

Regards,
Juan Dent

**Comment by ras0219-msft** [comment]
Our `integrate install` command effectively adds an MSBuild targets file[1] to all projects built inside VS 2015 or 2017. This file adds the appropriate include path and adds all "regular" libraries to your link line. The linker then determines the libraries that are used by your binary and only pulls in references to those libraries. By "regular" libraries, I mean libraries that do not override any standard C/C++ components like `main()` or `malloc()`.

Finally, we run a powershell script[2] on executables as a post-build action that copies any required DLLs to the output folder based on the _true_ runtime dependencies. This means that if you only use header-only components, you won't get any unneeded runtime DLLs!

[1] https://github.com/Microsoft/vcpkg/blob/d5659ea88d6bfa656f82d22f2cd186fe2ebb3b27/scripts/buildsystems/msbuild/vcpkg.targets
[2] https://github.com/Microsoft/vcpkg/blob/d5659ea88d6bfa656f82d22f2cd186fe2ebb3b27/scripts/buildsystems/msbuild/applocal.ps1
