### ISSUE TITLE
openmvg build error

### ISSUE THREAD

**Issue by seuwanglang** [microsoft/vcpkg#16171]
When asking a question please also include where you looked for an answer (so we can update the documentation if needed).
hello ，when i do the  “vcpkg install openmvg[core,openmp]:x64-windows”，an error came out saying
 “CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:108 (message):
    Command failed: ninja -v 
   Working Directory: E:/openMVG_MVS/vcpkg/buildtrees/lapack/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      E:\openMVG_MVS\vcpkg\buildtrees\lapack\config-x64-windows-out.log“   config-x64-windows-out.log said 
”cmd /c "cd .. && "E:/set up/cmake/bin/cmake.exe" "E:/openMVG_MVS/vcpkg/ports/lapack" "-DCMAKE_PREFIX_PATH="E:/openMVG_MVS/vcpkg/packages/lapack_x64-windows"" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=E:/openMVG_MVS/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v140" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=E:/openMVG_MVS/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_LINKER_FLAGS_RELEASE=" "-DVCPKG_LINKER_FLAGS_DEBUG=" "-DVCPKG_TARGET_ARCHITECTURE=x64" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=E:/openMVG_MVS/vcpkg" "-D_VCPKG_INSTALLED_DIR=E:/openMVG_MVS/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF" "-G" "Visual Studio 14 2015 Win64" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=E:/openMVG_MVS/vcpkg/packages/lapack_x64-windows""
-- Selecting Windows SDK version  to target Windows 10.0.17134.
-- The C compiler identification is MSVC 19.0.24215.1
-- The CXX compiler identification is MSVC 19.0.24215.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: E:/set up/vs2015/VC/bin/x86_amd64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: E:/set up/vs2015/VC/bin/x86_amd64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for sgemm_
-- Looking for sgemm_ - not found
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE  
-- Looking for sgemm_
-- Looking for sgemm_ - found
-- Found BLAS: E:/openMVG_MVS/vcpkg/installed/x64-windows/lib/openblas.lib  
-- Looking for cheev_
-- Looking for cheev_ - not found
-- Looking for cheev_
-- Looking for cheev_ - not found
-- Looking for cheev_
-- Looking for cheev_ - not found
CMake Error at E:/set up/cmake/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
  Could NOT find LAPACK (missing: LAPACK_LIBRARIES)
Call Stack (most recent call first):
  E:/set up/cmake/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:582 (_FPHSA_FAILURE_MESSAGE)
  E:/set up/cmake/share/cmake-3.19/Modules/FindLAPACK.cmake:524 (find_package_handle_standard_args)
  E:/openMVG_MVS/vcpkg/scripts/buildsystems/vcpkg.cmake:653 (_find_package)
  CMakeLists.txt:4 (find_package)

-- Configuring incomplete, errors occurred!
See also "E:/openMVG_MVS/vcpkg/buildtrees/lapack/x64-windows-rel/CMakeFiles/CMakeOutput.log".
See also "E:/openMVG_MVS/vcpkg/buildtrees/lapack/x64-windows-rel/CMakeFiles/CMakeError.log".
ninja: build stopped: subcommand failed.
“

**Comment by NancyLi1013** [comment]
Hi @seuwanglang 

Thanks for posting this issue.

```
CMake Error at E:/set up/cmake/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
Could NOT find LAPACK (missing: LAPACK_LIBRARIES)
```
Could you please help confirm you have installed `lapack`? 

This is the build log on my machine.
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/6008331/config-x64-windows-out.log)

**Comment by NancyLi1013** [comment]
@seuwanglang 

Please let me know if this is still a problem for you.

**Comment by NancyLi1013** [comment]
Closing this issue since there is no active thread now. Please reopen this if it is still a problem for you.

**Comment by seuwanglang** [comment]
hello @NancyLi1013  i have not install lapack which is i am installing

**Comment by seuwanglang** [comment]
hello @NancyLi1013   this is cmake error log 
Determining if the function sgemm_ exists failed with the following output:
Change Dir: F:/setup/vcpkg/vcpkg/buildtrees/lapack/x64-windows-dbg/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild.exe cmTC_58f8d.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=14.0 /v:m && Microsoft (R) 生成引擎版本 14.0.25420.1

版权所有(C) Microsoft Corporation。保留所有权利。



  CheckFunctionExists.c

CheckFunctionExists.obj : error LNK2019: 无法解析的外部符号 sgemm_，该符号在函数 main 中被引用 [F:\setup\vcpkg\vcpkg\buildtrees\lapack\x64-windows-dbg\CMakeFiles\CMakeTmp\cmTC_58f8d.vcxproj]

F:\setup\vcpkg\vcpkg\buildtrees\lapack\x64-windows-dbg\CMakeFiles\CMakeTmp\Debug\cmTC_58f8d.exe : fatal error LNK1120: 1 个无法解析的外部命令 [F:\setup\vcpkg\vcpkg\buildtrees\lapack\x64-windows-dbg\CMakeFiles\CMakeTmp\cmTC_58f8d.vcxproj]




Determining if the include file pthread.h exists failed with the following output:
Change Dir: F:/setup/vcpkg/vcpkg/buildtrees/lapack/x64-windows-dbg/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild.exe cmTC_0971c.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=14.0 /v:m && Microsoft (R) 生成引擎版本 14.0.25420.1

版权所有(C) Microsoft Corporation。保留所有权利。



  CheckIncludeFile.c

F:\setup\vcpkg\vcpkg\buildtrees\lapack\x64-windows-dbg\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: 无法打开包括文件: “pthread.h”: No such file or directory [F:\setup\vcpkg\vcpkg\buildtrees\lapack\x64-windows-dbg\CMakeFiles\CMakeTmp\cmTC_0971c.vcxproj]




Determining if the function cheev_ exists failed with the following output:
Change Dir: F:/setup/vcpkg/vcpkg/buildtrees/lapack/x64-windows-dbg/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild.exe cmTC_b6263.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=14.0 /v:m && Microsoft (R) 生成引擎版本 14.0.25420.1

版权所有(C) Microsoft Corporation。保留所有权利。



  CheckFunctionExists.c

CheckFunctionExists.obj : error LNK2019: 无法解析的外部符号 cheev_，该符号在函数 main 中被引用 [F:\setup\vcpkg\vcpkg\buildtrees\lapack\x64-windows-dbg\CMakeFiles\CMakeTmp\cmTC_b6263.vcxproj]

F:\setup\vcpkg\vcpkg\buildtrees\lapack\x64-windows-dbg\CMakeFiles\CMakeTmp\Debug\cmTC_b6263.exe : fatal error LNK1120: 1 个无法解析的外部命令 [F:\setup\vcpkg\vcpkg\buildtrees\lapack\x64-windows-dbg\CMakeFiles\CMakeTmp\cmTC_b6263.vcxproj]




Determining if the function cheev_ exists failed with the following output:
Change Dir: F:/setup/vcpkg/vcpkg/buildtrees/lapack/x64-windows-dbg/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild.exe cmTC_81ecd.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=14.0 /v:m && Microsoft (R) 生成引擎版本 14.0.25420.1

版权所有(C) Microsoft Corporation。保留所有权利。



  CheckFunctionExists.c

CheckFunctionExists.obj : error LNK2019: 无法解析的外部符号 cheev_，该符号在函数 main 中被引用 [F:\setup\vcpkg\vcpkg\buildtrees\lapack\x64-windows-dbg\CMakeFiles\CMakeTmp\cmTC_81ecd.vcxproj]

F:\setup\vcpkg\vcpkg\buildtrees\lapack\x64-windows-dbg\CMakeFiles\CMakeTmp\Debug\cmTC_81ecd.exe : fatal error LNK1120: 1 个无法解析的外部命令 [F:\setup\vcpkg\vcpkg\buildtrees\lapack\x64-windows-dbg\CMakeFiles\CMakeTmp\cmTC_81ecd.vcxproj]




Determining if the function cheev_ exists failed with the following output:
Change Dir: F:/setup/vcpkg/vcpkg/buildtrees/lapack/x64-windows-dbg/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild.exe cmTC_cd3ac.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=14.0 /v:m && Microsoft (R) 生成引擎版本 14.0.25420.1

版权所有(C) Microsoft Corporation。保留所有权利。



  CheckFunctionExists.c

F:\setup\vcpkg\vcpkg\installed\x64-windows\debug\lib\lapack.lib : fatal error LNK1127: 库已损坏 [F:\setup\vcpkg\vcpkg\buildtrees\lapack\x64-windows-dbg\CMakeFiles\CMakeTmp\cmTC_cd3ac.vcxproj]

**Comment by seuwanglang** [comment]
hello ，i still do not know how to fix the error。please tell me if you receive the message，this is the error log
Determining if the function sgemm_ exists failed with the following output:
Change Dir: F:/setup/vcpkg/vcpkg/buildtrees/lapack/x64-windows-dbg/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild.exe cmTC_58f8d.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=14.0 /v:m && Microsoft (R) 生成引擎版本 14.0.25420.1

版权所有(C) Microsoft Corporation。保留所有权利。



CheckFunctionExists.c

CheckFunctionExists.obj : error LNK2019: 无法解析的外部符号 sgemm_，该符号在函数 main 中被引用 [F:\setup\vcpkg\vcpkg\buildtrees\lapack\x64-windows-dbg\CMakeFiles\CMakeTmp\cmTC_58f8d.vcxproj]

F:\setup\vcpkg\vcpkg\buildtrees\lapack\x64-windows-dbg\CMakeFiles\CMakeTmp\Debug\cmTC_58f8d.exe : fatal error LNK1120: 1 个无法解析的外部命令 [F:\setup\vcpkg\vcpkg\buildtrees\lapack\x64-windows-dbg\CMakeFiles\CMakeTmp\cmTC_58f8d.vcxproj]




Determining if the include file pthread.h exists failed with the following output:
Change Dir: F:/setup/vcpkg/vcpkg/buildtrees/lapack/x64-windows-dbg/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild.exe cmTC_0971c.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=14.0 /v:m && Microsoft (R) 生成引擎版本 14.0.25420.1

版权所有(C) Microsoft Corporation。保留所有权利。



CheckIncludeFile.c

F:\setup\vcpkg\vcpkg\buildtrees\lapack\x64-windows-dbg\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: 无法打开包括文件: “pthread.h”: No such file or directory [F:\setup\vcpkg\vcpkg\buildtrees\lapack\x64-windows-dbg\CMakeFiles\CMakeTmp\cmTC_0971c.vcxproj]




Determining if the function cheev_ exists failed with the following output:
Change Dir: F:/setup/vcpkg/vcpkg/buildtrees/lapack/x64-windows-dbg/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild.exe cmTC_b6263.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=14.0 /v:m && Microsoft (R) 生成引擎版本 14.0.25420.1

版权所有(C) Microsoft Corporation。保留所有权利。



CheckFunctionExists.c

CheckFunctionExists.obj : error LNK2019: 无法解析的外部符号 cheev_，该符号在函数 main 中被引用 [F:\setup\vcpkg\vcpkg\buildtrees\lapack\x64-windows-dbg\CMakeFiles\CMakeTmp\cmTC_b6263.vcxproj]

F:\setup\vcpkg\vcpkg\buildtrees\lapack\x64-windows-dbg\CMakeFiles\CMakeTmp\Debug\cmTC_b6263.exe : fatal error LNK1120: 1 个无法解析的外部命令 [F:\setup\vcpkg\vcpkg\buildtrees\lapack\x64-windows-dbg\CMakeFiles\CMakeTmp\cmTC_b6263.vcxproj]




Determining if the function cheev_ exists failed with the following output:
Change Dir: F:/setup/vcpkg/vcpkg/buildtrees/lapack/x64-windows-dbg/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild.exe cmTC_81ecd.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=14.0 /v:m && Microsoft (R) 生成引擎版本 14.0.25420.1

版权所有(C) Microsoft Corporation。保留所有权利。



CheckFunctionExists.c

CheckFunctionExists.obj : error LNK2019: 无法解析的外部符号 cheev_，该符号在函数 main 中被引用 [F:\setup\vcpkg\vcpkg\buildtrees\lapack\x64-windows-dbg\CMakeFiles\CMakeTmp\cmTC_81ecd.vcxproj]

F:\setup\vcpkg\vcpkg\buildtrees\lapack\x64-windows-dbg\CMakeFiles\CMakeTmp\Debug\cmTC_81ecd.exe : fatal error LNK1120: 1 个无法解析的外部命令 [F:\setup\vcpkg\vcpkg\buildtrees\lapack\x64-windows-dbg\CMakeFiles\CMakeTmp\cmTC_81ecd.vcxproj]




Determining if the function cheev_ exists failed with the following output:
Change Dir: F:/setup/vcpkg/vcpkg/buildtrees/lapack/x64-windows-dbg/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild.exe cmTC_cd3ac.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=14.0 /v:m && Microsoft (R) 生成引擎版本 14.0.25420.1

版权所有(C) Microsoft Corporation。保留所有权利。



CheckFunctionExists.c

F:\setup\vcpkg\vcpkg\installed\x64-windows\debug\lib\lapack.lib : fatal error LNK1127: 库已损坏 [F:\setup\vcpkg\vcpkg\buildtrees\lapack\x64-windows-dbg\CMakeFiles\CMakeTmp\cmTC_cd3ac.vcxproj]



At 2021-03-11 15:10:06, "NancyLi1013" <notifications@github.com> wrote:

Closing this issue since there is no active thread now. Please reopen this if it is still a problem for you.

**Comment by NancyLi1013** [comment]
@seuwanglang 

Could you please install English package via Visual Studio Installer first and rebuild this on a clean environment?

**Comment by seuwanglang** [comment]
thank you。 i will try



At 2021-03-11 18:14:37, "NancyLi1013" ***@***.***> wrote:

@seuwanglang

Could you please install English package via Visual Studio Installer first and rebuild this on a clean environment?

**Comment by NancyLi1013** [comment]
Is this still a problem for you now? @seuwanglang

**Comment by NancyLi1013** [comment]
Closing this issue for now. Please open a new issue if you still have problems on a new repo with Visual Studio that has installed English package.
