### ISSUE TITLE
 Package: mesa:x64-windows BUILD_FAILED

### ISSUE THREAD

**Issue by llduncangithub** [microsoft/vcpkg#16174]
.\vcpkg.exe install mesa:x64-windows
Computing installation plan...
The following packages will be built and installed:
    mesa[core,default-features,gles1,gles2,llvm,opengl]:x64-windows -> 20.2.2#1
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\sg01\AppData\Local\vcpkg\archives\9c\9c89720943f47b776250d5f8693ece93666cd7d4.zip
Starting package 1/1: mesa:x64-windows
Building package mesa[core,default-features,gles1,gles2,llvm,opengl]:x64-windows...
-- Using cached D:/src/vcpkg/downloads/mesa-mesa-df2977f871fc70ebd6be48c180d117189b5861b5.tar.gz
-- Cleaning sources at D:/src/vcpkg/buildtrees/mesa/src/189b5861b5-bd40f385ca.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/src/vcpkg/downloads/mesa-mesa-df2977f871fc70ebd6be48c180d117189b5861b5.tar.gz
-- Applying patch dual-osmesa.patch
-- Applying patch dual-osmesa-part2.patch
-- Applying patch swravx512.patch
-- Using source at D:/src/vcpkg/buildtrees/mesa/src/189b5861b5-bd40f385ca.clean
Requirement already satisfied: setuptools in .\downloads\tools\python\python-3.9.0-x64\lib\site-packages (53.0.0)
Requirement already satisfied: mako in .\downloads\tools\python\python-3.9.0-x64\lib\site-packages (1.1.4)
Requirement already satisfied: MarkupSafe>=0.9.2 in .\downloads\tools\python\python-3.9.0-x64\lib\site-packages (from mako) (1.1.1)
-- Configuring x64-windows
-- Using msys root at D:/src/vcpkg/downloads/tools/msys2/50864d9fae363d6e
-- Configuring x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
    Command failed:
    Working Directory: D:/src/vcpkg/buildtrees/mesa/x64-windows-dbg
    Error code: 1
    See logs for more information:
      D:\src\vcpkg\buildtrees\mesa\config-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_meson.cmake:477 (vcpkg_execute_required_process)
  ports/mesa/portfile.cmake:168 (vcpkg_configure_meson)
  scripts/ports.cmake:131 (include)
[config-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/5962673/config-x64-windows-dbg-out.log)
[meson-log.txt](https://github.com/microsoft/vcpkg/files/5962674/meson-log.txt)

**Comment by Neumann-A** [comment]
I think you have an outdated version of libzstd installed. Please try from a new checkout or remove and reinstall libzstd. If you don't want to reinstall libzstd install libzstd in a new vcpkg instance and copy the *.pc files for libzstd located in (/debug)/lib/pkgconfig over.

**Comment by JonLiu1993** [comment]
@llduncangithub ，@Neumann-A gave a good suggestion.

**Comment by PhoebeHui** [comment]
@llduncangithub, please try above suggestion and reopen this issue if the issue persist.
