### ISSUE TITLE
[New Port Request] sqlpp11-connector-odbc

### ISSUE THREAD

**Issue by hgbutte** [microsoft/vcpkg#16176]
Please add the following connector
https://github.com/Erroneous1/sqlpp11-connector-odbc

Thank you.

**Comment by hgbutte** [comment]
Found some problems in sqlpp11-connector-odbc that might be a problem adding the connector out of the box:

https://github.com/Erroneous1/sqlpp11-connector-odbc/issues/21

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
