### ISSUE TITLE
Error getting canonicalization of =: The system cannot find the file specified.

### ISSUE THREAD

**Issue by jdx-john** [microsoft/vcpkg#16181]
I have had this several times that any vcpkg command gives this error, and I can never remember what changed to cause/fix the issue.

e.g.:
```
c:\github\microsoft\vcpkg>vcpkg install magic_enum
Error getting canonicalization of =: The system cannot find the file specified.
```

I get the error for install, search, and other common commands - it works for version but that's about it. I have launched a clean `cmd` window in Windows 10.
Please help!

**Comment by vicroms** [comment]
Hmm, usually you should have a path in that error message `Error getting canonicalization of /some/path/here`. 
Do you have any `VCPKG_*` environment variable set? 

@strega-nil @BillyONeal as our filesystem experts do you have any input?

**Comment by BillyONeal** [comment]
Canonical requires that the target exist.



________________________________

**Comment by strega-nil** [comment]
Please run `set`; you have an environment variable set wrong.

**Comment by JackBoosY** [comment]
I prefer to use `powershell` instead of `cmd`.

**Comment by jdx-john** [comment]
Thanks @vicroms  and @strega-nil I somehow had "_VCPKG_VISUAL_STUDIOPATH==_" though no idea why or how. I'll know what to look out for when I see this again now.

Closing...
