### ISSUE TITLE
msgpack cmake error with ninja 

### ISSUE THREAD

**Issue by killvxk** [Microsoft/vcpkg#1618]
in file ports\msgpack\portfile.cmake.

the line PREFER_NINJA is not necessary at all.

**Comment by codicodi** [comment]
I wasn't able to reproduce any problems with Ninja generator. Could you specify what errors you've got?

**Comment by killvxk** [comment]
in log file::

  Run Build Command:"B:/vcpkg/downloads/tools/ninja/ninja-1.7.2/ninja.exe"
  "cmTC_1787c"

  ninja: error: build.ninja:30: loading 'rules.ninja':
