### ISSUE TITLE
What happened to issue https://github.com/microsoft/vcpkg/issues/16179 ?

### ISSUE THREAD

**Issue by StarGate-One** [microsoft/vcpkg#16186]
Subject has question...
@RyanYCT created this issue:
[microsoft/vcpkg] Failed to install sqlite3 with error msg "Could not locate a complete toolset."(#16179)
He was still having issues accord to this email, but when I went to issues with #16179 to try add more advice, github gives me a 404 page error not found.

**The email I received I was going to reply to, now issue missing**
>RyanYCT <notifications@github.com>
>Fri 2021-02-12 00:54
>VS Code does not have its own compiler/linker.
>You need to install a compiler/linker such as Visual Studio 2017/2019 (Community Editions are Free), Intel, Cygwin, or Msys2 to name a few.

I try to install Cygwin and SQLlite with it. After adding Cygwin directory to VS Code includePath that's ok to compile c file.

But after I installed Visual Studio 2019 (English language pack), and do integrate remove and install to vcpkg. I can't still install any package with vcpkg.

C:\vcpkg>vcpkg install sqlite3
Computing installation plan...
The following packages will be built and installed:
    sqlite3[core]:x86-windows -> 3.33.0
Could not locate a complete toolset.
The following paths were examined:
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat
I do the search for vcvarsall.bat in Microsoft Visual Studio directory and found nothing.
p.s. Under this path C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary, there is no Build folder in it.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by StarGate-One** [comment]
Looks like @RyanYCT is missing. 
Does not one's profile turn into a **Ghost** image if they deactivate it?
How would the whole profile just go missing from yesterday to today?

**Comment by JackBoosY** [comment]
I think that's a github bug maybe?
I don't know why.

**Comment by JackBoosY** [comment]
I've create a github ticket to answer the github team.

**Comment by StarGate-One** [comment]
> I've create a github ticket to ask for the github team.

It looks like it is back now, along with the user profile... Thank you @JackBoosY ✔✨👍
