### ISSUE TITLE
[Jasper] build failure

### ISSUE THREAD

**Issue by kossiBlaise** [microsoft/vcpkg#16206]
**Host Environment**
- OS: [Windows.]
- Compiler: revision : vs 2017

**To Reproduce**
`.\vcpkg install Jasper

**Failure logs** 
Package: jasper:x86-windows
Vcpkg version: 2021-01-13-768d8f95c9e752603d2c5901c7a7c7fbdb08af35

RESULTS
    jasper:x86-windows: BUILD_FAILED: 27.9 s

SUMMARY
    SUCCEEDED: 0
    BUILD_FAILED: 1
    POST_BUILD_CHECKS_FAILED: 0
    FILE_CONFLICTS: 0
    CASCADED_DUE_TO_MISSING_DEPENDENCIES: 0

**Comment by autoantwort** [comment]
Can you provide the failure logs?

**Comment by autoantwort** [comment]
Have you tried the solution from #15035?

**Comment by kossiBlaise** [comment]
Hello,

Updating to the newest version of powershell solved the build problem.

Thank you.

Cheers,
