### ISSUE TITLE
[Vmime] libvmime

### ISSUE THREAD

**Issue by kossiBlaise** [microsoft/vcpkg#16209]
Library name: vmime

Library description:

Source repository URL:https://osdn.net/projects/sfnet_vmime/downloads/vmime/0.7/libvmime-0.7.1.tar.bz2/

Project homepage (if different from the source repository):https://osdn.net/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by StarGate-One** [comment]
@kossiBlaise 
- I would use the actively maintained version 0.9.2 of the VMime repository at https://github.com/kisli/vmime
- The osdn version 0.7.1 of VMime is stored on sourceforge and has not been updated since 2013.

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
