### ISSUE TITLE
How do I force vcpkg to use modified code under buildtrees?

### ISSUE THREAD

**Issue by zcream** [microsoft/vcpkg#16204]
Last year, I modified some code in a fltk buildtrees/ and then I did
`vcpkg remove fltk`
`vcpkg install fltk`

Due to recent change, vcpkg caches binary image, and simply installs from that. I deleted the cached binary image, and now vcpkg uses the downloaded tag.gz to populate the buildtrees/ dir. 

`-- Using cached C:/vcpkg/downloads/fltk-1.3.5.tar.gz`
`-- Extracting source C:/vcpkg/downloads/fltk-1.3.5.tar.gz`

This overwrites my changes. I want vcpkg to not use the cached binary image, and I do not want vcpkg using the downloaded archive sources. I want vcpkg to build the source it has already extracted to buildtrees/ in a previous install.

How do I achieve this ?

**Comment by StarGate-One** [comment]
`./vcpkg install port[features] --editable`
make your changes to the source in buildtrees
`./vcpkg install port[features] --editable`
You will know you did it correctly if the source directory does not have `.clean` extension.

**Comment by zcream** [comment]
Hi. The first command - the source dir did not have .clean extension.
The second command did not do anything - do I need to remove the port[features] first ?

`C:\vcpkg [(2020.11-1)]> .\vcpkg.exe install fltk --editable
Computing installation plan...
The following packages are already installed:
    fltk[core]:x64-windows-static
Package fltk:x64-windows-static is already installed

Total elapsed time: 1.17 ms

The package fltk:x64-windows-static provides CMake targets:

    find_package(FLTK CONFIG REQUIRED)
    target_link_libraries(main PRIVATE fltk fltk_gl fltk_forms fltk_images)`

**Comment by zcream** [comment]
Got it. The sequence is

./vcpkg install port[features] --editable

Make your changes.

Thanks!

./vcpkg remove port[features]
./vcpkg install port[features] --editable
