### ISSUE TITLE
[proj4:x64-linux] build failure  : File does not have expected hash when down load package

### ISSUE THREAD

**Issue by frank-jeo** [microsoft/vcpkg#16200]
**Host Environment**
- OS: ubuntu 20.04 LTS

I'm build osgEarth ,  when build  proj4, i got ：

...
Could not locate cached archive: /home/ieta/.cache/vcpkg/archives/74/744569fb2637aada9c036531b5acdd1f6cd70471.zip
Starting package 1/23: proj4:x64-linux
Building package proj4[core,database,tiff]:x64-linux...
-- Downloading https://github.com/OSGeo/PROJ/archive/7.2.1.tar.gz -> OSGeo-PROJ-7.2.1.tar.gz...
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:105 (message):
  

  File does not have expected hash:

          File path: [ /home/ieta/vcpkg/downloads/temp/OSGeo-PROJ-7.2.1.tar.gz ]
      Expected hash: [ e6e77266dcd70c939c16667c916cccab8de161221d2ef600cfca43382f50da2dc8d790561556b4416adbb4ac6fba939004e0cc936c278e0e808dc3566e9a70d4 ]
        Actual hash: [ 3f0081ed14221e12a330dd3b2a6e87e28aeafd3d372cfbcef6501a465637ecf5a61ffccacf795825c8b20d453474134fde7f499e856c3b6fbc963ca03244c8e4 ]

  The file may have been corrupted in transit.  This can be caused by
  proxies.  If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY
  environment variables to
  "https://user:password@your-proxy-ip-address:port/".

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:195 (test_hash)
  scripts/cmake/vcpkg_from_github.cmake:147 (vcpkg_download_distfile)
  ports/proj4/portfile.cmake:1 (vcpkg_from_github)
  scripts/ports.cmake:131 (include)

Error: Building package proj4:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: proj4:x64-linux
  Vcpkg version: 2021-01-13-unknownhash

Additionally, attach any relevant sections from the log files above.

I does not using any proxy,  and using the most updated vcpkg.  
I downloaded the package using browser and replaced the files in download dir, the error still the same. how can i fix this ?

ps: I'm using a vmware virtual mathine.

**Comment by StarGate-One** [comment]
Must have downloaded a partial or the file was corrupted in download.
Try again or try to download manually.
I just downloaded and verified the `expected` hash is correct:
`e6e77266dcd70c939c16667c916cccab8de161221d2ef600cfca43382f50da2dc8d790561556b4416adbb4ac6fba939004e0cc936c278e0e808dc3566e9a70d4  OSGeo-PROJ-7.2.1.tar.gz`

**Comment by frank-jeo** [comment]
thank u @StarGate-One . I  try to download manually，it works！and I found manual downloading is much faster than vcpkg.
