### ISSUE TITLE
[vcpkg] bootstrap failure

### ISSUE THREAD

**Issue by kossiBlaise** [microsoft/vcpkg#16207]
**Host Environment**
- OS: [Windows]
- Compiler: revision VS 2017/vs2019

**To Reproduce**
bootstrap-vcpkg.bat

**Failure logs** 

L:\vcpkg>bootstrap-vcpkg.bat
Method invocation failed because [System.String] doesn't contain a method named
 'IsNullOrWhiteSpace'.
At L:\vcpkg\scripts\bootstrap.ps1:28 char:38
+ if (-Not [string]::IsNullOrWhiteSpace <<<< ($withVSPath))
    + CategoryInfo          : InvalidOperation: (IsNullOrWhiteSpace:String) []
   , RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

Method invocation failed because [System.String] doesn't contain a method named
 'IsNullOrWhiteSpace'.
At L:\vcpkg\scripts\bootstrap.ps1:33 char:38
+ if (-Not [string]::IsNullOrWhiteSpace <<<< ($withWinSDK))
    + CategoryInfo          : InvalidOperation: (IsNullOrWhiteSpace:String) []
   , RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

Downloading https://github.com/microsoft/vcpkg-tool/releases/download/2021-01-13
-768d8f95c9e752603d2c5901c7a7c7fbdb08af35/vcpkg.exe -> L:\vcpkg/vcpkg.exe
Done.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by StarGate-One** [comment]
What version of Powershell is installed?
From a command prompt, run `powershell`, from the powershell prompt type in `$PSVersionTable.PSVersion`.
If the major version is less than 3, you need to upgrade powershell to version 3 or higher.
Windows 10 comes with Powershell 5, are your running Windows 7?
You may have to download and install powershell core, make sure to have it add itself to your PATH environment variable during install. I would recommend v7.1.2 or v7.0.5 at https://github.com/PowerShell/PowerShell/releases

Example:
>**********************************************************************
>** Visual Studio 2017 Developer Command Prompt v15.9.33
>** Copyright (c) 2017 Microsoft Corporation
>**********************************************************************
>
>SYSTEM@ANDROMEDA 02/13/2021 16:57:30 C:\Windows\System32
>->powershell
>Windows PowerShell
>Copyright (C) Microsoft Corporation. All rights reserved.
>
>Try the new cross-platform PowerShell https://aka.ms/pscore6
>
>PS C:\Windows\System32> $PSVersionTable.PSVersion
>
>Major  Minor  Build  Revision
>-----  -----  -----  --------
>5      1      19041  610
>
>PS C:\Windows\System32> exit

**Comment by kossiBlaise** [comment]
Thank you very much. I am running Win 7. Updating Power shell solved my problem.
More power to you guys.
