### ISSUE TITLE
Error when running ".\vcpkg.exe install freetype:x64-windows" on windows

### ISSUE THREAD

**Issue by HyperbolaZz** [microsoft/vcpkg#16214]
**Host Environment**
- OS: Windows
- Package: brotli:x64-windows
- Vcpkg version: 2021-01-13-768d8f95c9e752603d2c5901c7a7c7fbdb08af35

**To Reproduce**
`.\vcpkg.exe install freetype:x64-windows`

**Failure logs** 
PS C:\src\vcpkg> .\vcpkg.exe install freetype:x64-windows
Computing installation plan...
The following packages will be built and installed:
  * brotli[core]:x64-windows -> 1.0.9
  * bzip2[core]:x64-windows -> 1.0.8#1
    freetype[brotli,bzip2,core,png,zlib]:x64-windows -> 2.10.4
  * libpng[core]:x64-windows -> 1.6.37#14
  * zlib[core]:x64-windows -> 1.2.11#9
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\hyper\AppData\Local\vcpkg\archives\90\90367e9ef5dc9c68b4ccc0233dcdda4b881443b4.zip
Could not locate cached archive: C:\Users\hyper\AppData\Local\vcpkg\archives\8e\8eefd61fb3035dba413f8fd5c604f2bb1431bf20.zip
Could not locate cached archive: C:\Users\hyper\AppData\Local\vcpkg\archives\64\64f5e31a62b9fdb190845e95d4156cae434ba778.zip
Could not locate cached archive: C:\Users\hyper\AppData\Local\vcpkg\archives\fa\fa6029a9656bfc472259fd9678424ebe8a0bf1f3.zip
Could not locate cached archive: C:\Users\hyper\AppData\Local\vcpkg\archives\95\952052f7ea3296f95271ccda133d637f9138b472.zip
Starting package 1/5: brotli:x64-windows
Building package brotli[core]:x64-windows...
-- Using cached C:/src/vcpkg/downloads/google-brotli-e61745a6b7add50d380cfd7d3883dd6c62fc2c71.tar.gz
-- Cleaning sources at C:/src/vcpkg/buildtrees/brotli/src/6c62fc2c71-a8c4ea9278.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/src/vcpkg/downloads/google-brotli-e61745a6b7add50d380cfd7d3883dd6c62fc2c71.tar.gz
-- Applying patch install.patch
-- Applying patch fix-arm-uwp.patch
-- Applying patch pkgconfig.patch
-- Using source at C:/src/vcpkg/buildtrees/brotli/src/6c62fc2c71-a8c4ea9278.clean
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
    Command failed: ninja -v
    Working Directory: C:/src/vcpkg/buildtrees/brotli/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\src\vcpkg\buildtrees\brotli\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:319 (vcpkg_execute_required_process)
  ports/brotli/portfile.cmake:13 (vcpkg_configure_cmake)
  scripts/ports.cmake:131 (include)

Error: Building package brotli:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: brotli:x64-windows
  Vcpkg version: 2021-01-13-768d8f95c9e752603d2c5901c7a7c7fbdb08af35

Additionally, attach any relevant sections from the log files above.

**Comment by StarGate-One** [comment]
Please attach (drag & drop) file `C:\src\vcpkg\buildtrees\brotli\config-x64-windows-out.log` for further diagnostic review.

**Comment by HyperbolaZz** [comment]
> Please attach (drag & drop) file `C:\src\vcpkg\buildtrees\brotli\config-x64-windows-out.log` for further diagnostic review.


[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/5979225/config-x64-windows-out.log)

**Comment by StarGate-One** [comment]
CMake is not able to generate the project properly - 
Check to make sure Visual Studio 2019 has the following installed:
- Desktop Development with C++
- One of the Windows SDKs, preferably the latest 19041
- English Language Pack

**Comment by HyperbolaZz** [comment]
> CMake is not able to generate the project properly -
> Check to make sure Visual Studio 2019 has the following installed:
> 
> * Desktop Development with C++
> * One of the Windows SDKs, preferably the latest 19041
> * English Language Pack

It starts downloading. I missed the SDKs.
