### ISSUE TITLE
yaml-cpp not usable

### ISSUE THREAD

**Issue by yamcenutzer** [Microsoft/vcpkg#1621]
the way yaml-cpp is built it is not usable.
the default seems to create a shared lib, but that has unresolved externals when used.

I only ever got ot use yaml-cpp by building it as a static lib with dynamic runtime and using it that way.

**Comment by codicodi** [comment]
Sounds like a problem with import macros. I'll look into it

**Comment by yamcenutzer** [comment]
I don't know, it seems yaml-cpp can't be built as a dll on windows (unless the issue was silently resolved over there, but not that I know of).

Right now, in vcpkg,  I've changed the default target triplet to:
```
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
if(PORT STREQUAL "yaml-cpp")
    set(VCPKG_LIBRARY_LINKAGE static)
endif()    
```
That way, it's built as static lib with dynamic runtime and remains usaeable

**Comment by codicodi** [comment]
I was able to reproduce linker errors and they all seem to be related to incorrect import declarations.
Could you checkout #1622 and see if it fixes your issue?
If not, could you show code that can't be linked correctly?

**Comment by yamcenutzer** [comment]
Does it work for you?

the simple test is to have a 2-liner in your code:
```
YAML::Node a = Loadfile("something`);
YAML::Node b = a["test"];

```
It doesn't do anything for me. Still the same unresolved external

**Comment by codicodi** [comment]
Well, for current port it fails for me with:
`foo.obj : error LNK2001: unresolved external symbol "public: static class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > YAML::detail::node_data::empty_scalar" (?empty_scalar@node_data@detail@YAML@@2V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@A)`
With  #1622 applied it seems to works fine.

**Comment by yamcenutzer** [comment]
then I porobably didn't manage to get your build .
Anyway, are you intending to PR this to the 'original' repo, because, imho that is missing there too:
https://github.com/jbeder/yaml-cpp/issues/461

**Comment by alexkaratarakis** [comment]
@yamcenutzer The fix was merged, so you can try it by pulling the latest version.

**Comment by yamcenutzer** [comment]
Thx,
works here too now.

**Comment by yamcenutzer** [comment]
Sorry, that was too fast,
The fix gets you past the errors on the 2-liner above, but if you start using it you still get a lot of warnings about linkage (it does compile though):
```
warning C4251: 'YAML::detail::memory_holder::m_pMemory': class 'std::shared_ptr<YAML::detail::memory>' needs to have dll-interface to be used by clients of class 'YAML::detail::memory_holder'
warning C4251: 'YAML::detail::node_data::empty_scalar': class 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>' needs to have dll-interface to be used by clients of class 'YAML::detail::node_data'
warning C4251: 'YAML::detail::node_data::m_tag': class 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>' needs to have dll-interface to be used by clients of class 'YAML::detail::node_data'
 . . . 
etc.
```

**Comment by codicodi** [comment]
I wouldn't worry too much about those. The standard library classes are defined identically in your application and in yaml-cpp, so you should be fine and the warning can be disabled. 
The warning would matter if you used different version of the standard library than yaml-cpp, but mixing stdlib versions (or modes: debug/release) is a very bad idea anyway.

**Comment by yamcenutzer** [comment]
I see you closed this.
So it is the expected behaviour, that parsing a node effectively disables emitting?
