### ISSUE TITLE
bootstrap-vcpkg.bat fails when vcpkg repository cloned, if git obeys executable permissions of tls12-download.exe

### ISSUE THREAD

**Issue by yuri-sevatz** [microsoft/vcpkg#16211]
**Describe the bug**
I just tried cloning the official `vcpkg` repository using Cygwin's `git`, and then tried `bootstrap-vcpkg.bat` from Windows Command Prompt.  These steps had previously worked fine during December 2020,

There seems to be something wrong with one of the executable permissions that had recently been merged into `vcpkg`.

**Environment**
- Windows 10 20H2 19042.804
- Compiler: Visual Studio Community 2019 16.8.5

**To Reproduce**
1. Launch Cygwin Terminal
2. (Cygwin Terminal) `git clone git@github.com:microsoft/vcpkg.git`
3. Launch Windows Command Prompt
4. (Command Prompt) `bootstrap-vcpkg.bat`

**Expected behavior**
4. Bootstrap should not encounter any Access denied errors.

**Failure logs** 
```
C:\src\vcpkg>bootstrap-vcpkg.bat
Program 'tls12-download.exe' failed to run: Access is deniedAt C:\src\vcpkg\scripts\bootstrap.ps1:48 char:1
+ & "$scriptsDir/tls12-download.exe" github.com "/microsoft/vcpkg-tool/ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
At C:\src\vcpkg\scripts\bootstrap.ps1:48 char:1
+ & "$scriptsDir/tls12-download.exe" github.com "/microsoft/vcpkg-tool/ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed


The variable '$LASTEXITCODE' cannot be retrieved because it has not been set.
At C:\src\vcpkg\scripts\bootstrap.ps1:51 char:5
+ if ($LASTEXITCODE -ne 0)
+     ~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (LASTEXITCODE:String) [], RuntimeException
    + FullyQualifiedErrorId : VariableIsUndefined

Telemetry
---------
vcpkg collects usage data in order to help us improve your experience.
The data collected by Microsoft is anonymous.
You can opt-out of telemetry by re-running the bootstrap-vcpkg script with -disableMetrics,
passing --disable-metrics to vcpkg on the command line,
or by setting the VCPKG_DISABLE_METRICS environment variable.

Read more about vcpkg telemetry at docs/about/privacy.md
```

**Additional context**

Doing a little detective work:

```
$ ls -Al scripts/tls12-download.exe
-rw-r--r-- 1 Jet Jet 18312 Feb 13 18:10 scripts/tls12-download.exe
```
It looks like the executable was cloned and assigned the permissions that had been merged into git, at the time the executable was checked in: microsoft/vcpkg@aa60b7efa56a83ead743718941d8b320ef4a05af

I believe you can overcome this by just setting the mode to 0755, then merging it.  Thiis is the default mode windows assigns executables, if you had just downloaded the executable from the internet:

```
$ chmod 0755 scripts/tls12-download.exe
$ ls -Al scripts/tls12-download.exe
-rwxr-xr-x 1 Jet Jet 18312 Feb 13 18:10 scripts/tls12-download.exe
```

Then from Windows Command-Prompt:
```
C:\src\vcpkg>bootstrap-vcpkg.bat
Downloading https://github.com/microsoft/vcpkg-tool/releases/download/2021-01-13-768d8f95c9e752603d2c5901c7a7c7fbdb08af35/vcpkg.exe -> C:\src\vcpkg/vcpkg.exe
Done.

Telemetry
---------
vcpkg collects usage data in order to help us improve your experience.
The data collected by Microsoft is anonymous.
You can opt-out of telemetry by re-running the bootstrap-vcpkg script with -disableMetrics,
passing --disable-metrics to vcpkg on the command line,
or by setting the VCPKG_DISABLE_METRICS environment variable.

Read more about vcpkg telemetry at docs/about/privacy.md
```

I'll try and open a PR to correct the mode.  This is only .exe in the repository so far, and the problem doesn't seem to affect .bat files.

Otherwise everything else cloned from within Cygwin works great!

**Comment by MVoz** [comment]
/cc msft

Why two repository?
why is there no description to build?
https://github.com/microsoft/vcpkg-tool <<-- (build only static)

**Comment by yuri-sevatz** [comment]
> /cc msft
> 
> Why two repository?
> why is there no description to build?
> https://github.com/microsoft/vcpkg-tool <<-- (build only static)
> 
> @yuri-sevatz
> download - copy
> https://github.com/microsoft/vcpkg-tool/releases

@MVoz I hope that the ticket I have filed and fixed here is not being used a generic "catch all" support ticket for unrelated questions.

I don't know what those other repositories are for.  And I don't work for Microsoft :-).  Though you can find documentation on installing and using `vcpkg` on Microsoft's website:

https://docs.microsoft.com/en-us/cpp/build/install-vcpkg?view=msvc-160&tabs=windows

Please try not to spam unrelated issues when seeking support.  There's a special type of issue you can file, for "how do I..." questions.

**Comment by JackBoosY** [comment]
cc @BillyONeal
