### ISSUE TITLE
llvm build failure

### ISSUE THREAD

**Issue by NickStrupat** [microsoft/vcpkg#16215]
**Host Environment**
- OS: Windows 10
- Compiler: 2021-01-13-768d8f95c9e752603d2c5901c7a7c7fbdb08af35

**To Reproduce**
`.\vcpkg.exe install --triplet x64-windows llvm[core,lld,target-x86]`

**Failure logs** 
```
...
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_fixup_cmake_targets.cmake:126 (message):
  'C:/Dev/vcpkg/packages/llvm_x64-windows/debug/share/lld' does not exist.
Call Stack (most recent call first):
  ports/llvm/portfile.cmake:207 (vcpkg_fixup_cmake_targets)
  scripts/ports.cmake:131 (include)


Error: Building package llvm:x64-windows failed with: BUILD_FAILED
```

**Comment by yurybura** [comment]
Hello @NickStrupat,
lld is part of LLVM tools.
Please try:
`.\vcpkg.exe install --triplet x64-windows llvm[core,tools,lld,target-x86]`
Anyway I will add a new check in the build script.
Thank you.

**Comment by NickStrupat** [comment]
Thank you @yurybura for your kind help and effort!

**Comment by NickStrupat** [comment]
So that build worked, but when I compile against it with `msvc` i'm getting...

`fatal error LNK1104: cannot open file 'grpc++.lib'`

Wondering if you've seen that before or know off the top of your head how to address that?

My CMakeLists.txt incase that gives any quick hints:

```
cmake_minimum_required (VERSION 3.8)

set(INCLUDE_DIR "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include")
message(${INCLUDE_DIR})
include_directories(${INCLUDE_DIR})

find_package(LLD CONFIG REQUIRED)
find_package(LLVM CONFIG REQUIRED)

add_executable (main "main.cpp" )

target_link_libraries(main PRIVATE lldELF lldCOFF lldCore lldWasm)
target_link_libraries(main PRIVATE LTO LLVMMC grpc++ LLVMLTO)
```

...and my main.cpp is...

```
#include "llvm/ADT/APFloat.h"
#include "llvm/ADT/Optional.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/LegacyPassManager.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Verifier.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Host.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Support/TargetSelect.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetOptions.h"
using namespace llvm;

int main()
{
	LLVMContext context;
	Module module("Module", context);
	IRBuilder<> builder(context);

	// Initialize the target registry etc.
	InitializeAllTargetInfos();
	InitializeAllTargets();
	InitializeAllTargetMCs();
	InitializeAllAsmParsers();
	InitializeAllAsmPrinters();

	auto targetTriple = sys::getDefaultTargetTriple();
	module.setTargetTriple(targetTriple);

	return 0;
}
```

**Comment by NickStrupat** [comment]
I just removed grpc++` from that `target_link_libraries` entry and it seems fine.

**Comment by NickStrupat** [comment]
@yurybura I know this is off-topic, but do you happen to know where I can find an example or even a tutorial showing how to use LLD programmatically? You seem to have a strong handle on LLVM in general. I'm hoping to put together a basic front-to-back example of using the LLVM builder and then going all the way to linking an executable binary. So many of the examples I've found seem to gloss over at least a few things.

I've gotten as far as outputting an object file for a given module, but I can't find anything about integrating the linker without `system("<lld>")` type of thing.

**Comment by yurybura** [comment]
@NickStrupat Unfortunately, I don't know better documentation for programmable API than the source code.
I think for beginning is better to use [MCJT](https://llvm.org/docs/MCJITDesignAndImplementation.html) for generating executable binary in your code. MCJIT is much better documented.

Later you may try to use LLD as is for linking your binary from the LLVM module (IR).
