### ISSUE TITLE
[shogun] build failure

### ISSUE THREAD

**Issue by borient** [microsoft/vcpkg#16219]
package: shogun:x64-windows

**To Reproduce**
`./vcpkg install shogun:x64-windows`

**Failure logs** 
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:145 (message):
    Command failed: C:/src/vcpkg/downloads/tools/cmake-3.18.4-windows/cmake-3.18.4-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v -j5
    Working Directory: C:/src/vcpkg/buildtrees/shogun/x64-windows-dbg
    See logs for more information:
      C:\src\vcpkg\buildtrees\shogun\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:27 (vcpkg_build_cmake)
  ports/shogun/portfile.cmake:48 (vcpkg_install_cmake)
  scripts/ports.cmake:136 (include)

Error: Building package shogun:x64-windows failed with: BUILD_FAILED

I checked the log file (C:\src\vcpkg\buildtrees\shogun\install-x64-windows-dbg-out.log). The error part is
```
C:\src\vcpkg\buildtrees\shogun\src\b686d6e1cc-534b82672e.clean\src\shogun/lib/parameter_observers/ObservedValue.h(190): warning C4244: 'return': conversion from '_Rep' to 'double', possible loss of data
        with
        [
            _Rep=__int64
        ]
c:\src\vcpkg\installed\x64-windows\include\openblas/openblas_config.h(56): error C2371: 'BLASLONG': redefinition; different basic types
c:\src\vcpkg\installed\x64-windows\include\eigen\src\core\util\../../misc/blas.h(15): note: see declaration of 'BLASLONG'
c:\src\vcpkg\installed\x64-windows\include\openblas/openblas_config.h(57): error C2371: 'BLASULONG': redefinition; different basic types
c:\src\vcpkg\installed\x64-windows\include\eigen\src\core\util\../../misc/blas.h(16): note: see declaration of 'BLASULONG'
c:\src\vcpkg\installed\x64-windows\include\openblas_common.h(18): warning C4005: 'BLASFUNC': macro redefinition
c:\src\vcpkg\installed\x64-windows\include\eigen\src\core\util\../../misc/blas.h(9): note: see previous definition of 'BLASFUNC'
C:\src\vcpkg\buildtrees\shogun\src\b686d6e1cc-534b82672e.clean\src\shogun\lib\SGMatrix.cpp(783): warning C4244: '=': conversion from 'double' to 'T', possible loss of data
```

**Comment by JonLiu1993** [comment]
@borient ，Please upgrade your Visual Studio version and try again

**Comment by borient** [comment]
I am using version 15.9.33 of VS 2017. The latest package is upgraded via Visual Studio installer. The problem still persists.

**Comment by JackBoosY** [comment]
@borient Seems this bug has been fixed. Can you please remove openblas and rebuild shogun?

Thanks.

**Comment by borient** [comment]
thanks, the issue is solved.
