### ISSUE TITLE
[fontconfig] build failure

### ISSUE THREAD

**Issue by kossiBlaise** [microsoft/vcpkg#16213]
**Host Environment**
- OS: Windows 7
- Compiler: VS2017, VS2019

**To Reproduce**
`./vcpkg install fontconfig

**Failure logs** 
-- Extracting source L:/vcpkg/downloads/fontconfig-fontconfig-844d8709a1f3ecab45
015b24b72dd775c13b2421.tar.gz
-- Applying patch remove_tests.patch
-- Applying patch build.patch
-- Applying patch build2.patch
-- Applying patch disable-install-data.patch
-- Applying patch fix_def_dll_name.patch
-- Using source at L:/vcpkg/buildtrees/fontconfig/src/75c13b2421-828c91b8d5.clea
n
-- Configuring x86-windows
-- Using msys root at L:/vcpkg/downloads/tools/msys2/e11fa1e2c730d07f
-- Using msys root at L:/vcpkg/downloads/tools/msys2/50864d9fae363d6e
-- Generating configure for x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):

    Command failed: L:/vcpkg/downloads/tools/msys2/e11fa1e2c730d07f/usr/bin/bash
.exe --noprofile --norc --debug -c "autoreconf -vfi"
    Working Directory: L:/vcpkg/buildtrees/fontconfig/src/75c13b2421-828c91b8d5.
clean/
    Error code: 1
    See logs for more information:
      L:\vcpkg\buildtrees\fontconfig\autoconf-x86-windows-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:574 (vcpkg_execute_required_process)
  ports/fontconfig/portfile.cmake:25 (vcpkg_configure_make)
  scripts/ports.cmake:131 (include)

Error: Building package fontconfig:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: fontconfig:x86-windows
  Vcpkg version: 2021-01-13-768d8f95c9e752603d2c5901c7a7c7fbdb08af35
[autoconf-x86-windows-err.log](https://github.com/microsoft/vcpkg/files/5976850/autoconf-x86-windows-err.log)

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by sfhacker** [comment]
Are we STILL having issues with fontconfig?

**Comment by kossiBlaise** [comment]
Affirmative. I cannot finish the building process. Apparently it is not finding "tar.exe". 
Tar.exe can be reached through $PATH

Any help is appreciated.

Thank you

**Comment by Neumann-A** [comment]
you could try running `vcpkg env` and then try `tar`. If it errors it has to do how the clean env is setup in vcpkg on Win 7.

**Comment by JackBoosY** [comment]
Duplicate to #15508, please provide the result what @Neumann-A asked in #15508.

**Comment by kossiBlaise** [comment]
When i issued vcpkg env, and tried to run tar on a file, tar could not be found. I therefor copied tar.exe to windows folder, and all went well.

It seems like the env created by vcpkg, may be missing some few tricks.
