### ISSUE TITLE
armadillo: build failure

### ISSUE THREAD

**Issue by borient** [microsoft/vcpkg#16221]
**Host Environment**
 Windows

**To Reproduce**
`./vcpkg install armadillo:x64-windows`

**Failure logs** 
Building package armadillo[core]:x64-windows...
-- Note: armadillo only supports static library linkage. Building static library.
-- Downloading https://gitlab.com/conradsnicta/armadillo-code/-/archive/24b4762cbfbd3ad14c99a4854acd3560559a3195/armadillo-code-24b4762cbfbd3ad14c99a4854acd3560559a3195.tar.gz...
-- Downloading https://gitlab.com/conradsnicta/armadillo-code/-/archive/24b4762cbfbd3ad14c99a4854acd3560559a3195/armadillo-code-24b4762cbfbd3ad14c99a4854acd3560559a3195.tar.gz... Failed. Status: 22;"HTTP response code said error"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:184 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_gitlab.cmake:133 (vcpkg_download_distfile)
  ports/armadillo/portfile.cmake:3 (vcpkg_from_gitlab)
  scripts/ports.cmake:136 (include)

Error: Building package armadillo:x64-windows failed with: BUILD_FAILED

I tried to directly download from https://gitlab.com/conradsnicta/armadillo-code/-/archive/24b4762cbfbd3ad14c99a4854acd3560559a3195/armadillo-code-24b4762cbfbd3ad14c99a4854acd3560559a3195.tar.gz

It reports: 

**This archive has been requested too many times. Try again later.**

**Comment by StarGate-One** [comment]
There are limits on GitLab, but it would be hard for me to believe they were exceeded - reference https://docs.gitlab.com/ee/user/gitlab_com/#gitlabcom-specific-rate-limits

**Comment by borient** [comment]
I completely agree. It does not seem to be a limit issue.

**Comment by NancyLi1013** [comment]
Hi @borient 

Thanks for posting this issue.

Since there is something wrong with the server on GitLab. we have moved the repository to sourceforge.

Please see https://github.com/microsoft/vcpkg/pull/15973#issue-565002414

So you can update vcpkg to the latest version to rebuild `armadillo`.
