### ISSUE TITLE
How do I use MSBuild vcpkg.targets and GitHub Actions?

### ISSUE THREAD

**Issue by thewavelength** [microsoft/vcpkg#16228]
# Situation

I'm using MSBuild / Visual Studio Project and used the integration provided by vcpkg by adding the following line to my `.vcxproj` file:

```
<Import Project="$(SolutionDir)vcpkg\scripts\buildsystems\msbuild\vcpkg.targets" />
```

I have installed vcpkg in `$(SolutionDir)` as a Git submodule which works perfectly for local development.

I also want to build the project/solution with GitHub Actions.

To do that, I have two options:

1. I either have to checkout and compile vcpkg as a Git submodule on the runner every time, which costs time and useless resources
1. I can use the pre-installed vcpkg installation on the Windows runner provided by GitHub

Option 1 works as expected, but it slows down the action and wastes resources which shouldn't be necessary.

Option 2 doesn't work though because my `.vcxproj` file somehow contains an absolute path to the `vcpkg.targets` file. Obviously the variable `$(VcpkgRoot)` will not be available because it is only introduced by the `vcpkg.targets` file.

# Question

How can I add `vcpkg.targets` to my `.vcxproj` file so it works universally with the GitHub Actions provided vcpkg installation as well as a Git submodule installation?

**Comment by thewavelength** [comment]
Found two solutions.

## Environment variables

In the feature list of the [GitHub Actions Windows Machine](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md) we find the environment variable `VCPKG_INSTALLATION_ROOT`. MSBuild supports conditionals on environment variables, resulting in the following snippet to be put in ones `.vcxproj` file:

```
<PropertyGroup>
    <VCPKG_INSTALLATION_ROOT Condition=" '$(VCPKG_INSTALLATION_ROOT)' == '' ">$(SolutionDir)vcpkg</VCPKG_INSTALLATION_ROOT>
</PropertyGroup>
<Import Project="$(VCPKG_INSTALLATION_ROOT)\scripts\buildsystems\msbuild\vcpkg.targets" />
```

Added benefit: even a local user could set the environment variable and avoid vcpkg being utilized from the submodule.

## Directory junction

This is not tested but probably it would work to create a directory junction using `mklink /J` in the place where the submodule would normally be.

**Comment by vSzemkel** [comment]
As of June 2022 the command:
`vcpkg integrate install` just works in Github Actions environment.
For example see my [GitHub][1]


  [1]: https://github.com/vSzemkel/Manam/blob/master/.github/workflows/msbuild.yml
