### ISSUE TITLE
How do I install boost-numpy

### ISSUE THREAD

**Issue by petulka8s** [microsoft/vcpkg#16233]
Hi,

I installed python by vcpkg install **boost-python:x64-windows**, but there is not **numpy** package.
Please could you help me how to install boost python numpy to the solution?

**Comment by autoantwort** [comment]
Boost python is a c++ library to write python bindings, not an environment with preinstalled packages.

**Comment by petulka8s** [comment]
Sorry, I am quite new to this topic.
I just installed boost by using vcpkg and everything is going well.

The only problem is that:
**vcpkg install boost** - doesnt contain boost_numpyxxx.dll
**conda install boost** - contains boost_numpyxxx.dll

I don't know what I am doing wrong.

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/5732.
