### ISSUE TITLE
[boost-build] build failure (cross compile linux -> windows)

### ISSUE THREAD

**Issue by autoantwort** [microsoft/vcpkg#16237]
**Describe the bug**
I [got the message](https://git.rwth-aachen.de/leander.schulten/Lichtsteuerung/-/jobs/1473226#L668):
```
-- Installing: /builds/leander.schulten/Lichtsteuerung/vcpkg/packages/boost-build_x64-linux-windows-static/share/boost-build/copyright
-- Installing: /builds/leander.schulten/Lichtsteuerung/vcpkg/packages/boost-build_x64-linux-windows-static/tools/boost-build/boostcpp.jam
-- Bootstrapping...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
    Command failed: /builds/leander.schulten/Lichtsteuerung/vcpkg/packages/boost-build_x64-linux-windows-static/tools/boost-build/bootstrap.sh
    Working Directory: /builds/leander.schulten/Lichtsteuerung/vcpkg/packages/boost-build_x64-linux-windows-static/tools/boost-build
    Error code: 1
    See logs for more information:
      /builds/leander.schulten/Lichtsteuerung/vcpkg/buildtrees/boost-build/bootstrap-x64-linux-windows-static-out.log
      /builds/leander.schulten/Lichtsteuerung/vcpkg/buildtrees/boost-build/bootstrap-x64-linux-windows-static-err.log
Call Stack (most recent call first):
  ports/boost-build/portfile.cmake:64 (vcpkg_execute_required_process)
  scripts/ports.cmake:131 (include)
Error: Building package boost-build:x64-linux-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-build:x64-linux-windows-static
  Vcpkg version: 2021-01-13-unknownhash
```

<details>
<summary>bootstrap-x64-linux-windows-static-out.log</summary>

<pre>

Building the B2 engine..

###
###
###
###

> /usr/src/mxe/usr/bin/x86_64-w64-mingw32.shared.posix-g++ --version
x86_64-w64-mingw32.shared.posix-g++ (GCC) 8.4.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

###
###

> /usr/src/mxe/usr/bin/x86_64-w64-mingw32.shared.posix-g++ -x c++ -std=c++11 -O2 -s -DNDEBUG builtins.cpp class.cpp command.cpp compile.cpp constants.cpp cwd.cpp debug.cpp debugger.cpp execcmd.cpp filesys.cpp frames.cpp function.cpp glob.cpp hash.cpp hcache.cpp hdrmacro.cpp headers.cpp jam.cpp jamgram.cpp lists.cpp make.cpp make1.cpp md5.cpp mem.cpp modules.cpp native.cpp object.cpp option.cpp output.cpp parse.cpp pathsys.cpp regexp.cpp rules.cpp scan.cpp search.cpp jam_strings.cpp startup.cpp subst.cpp sysinfo.cpp timestamp.cpp variable.cpp w32_getreg.cpp modules/order.cpp modules/path.cpp modules/property-set.cpp modules/regex.cpp modules/sequence.cpp modules/set.cpp execnt.cpp filent.cpp pathnt.cpp -o b2
> cp b2 bjam

</pre>
</details>

<details><summary>bootstrap-x64-linux-windows-static-err.log</summary><pre>cp: cannot stat 'b2': No such file or directory
Failed to build the B2 engine.
</pre></details>

```bash
$ ls vcpkg/packages/boost-build_x64-linux-windows-static/tools/boost-build/src/engine
...
b2.exe
...
```

**Environment**
- OS: Linux (Docker Container with [mxe](https://github.com/mxe/mxe))
- Compiler: x86_64-w64-mingw32.shared.posix-gcc (GCC) 8.4.0

**To Reproduce**
1. Use the mxe environment 
1. ./vcpkg install boost-asio --triplet=x64-linux-windows-static
2. See error

**Expected behavior**
No error / b2 should be build for the Host environment and not the target environment  

**Failure logs** 
See [here](https://git.rwth-aachen.de/leander.schulten/Lichtsteuerung/-/jobs/1472927#L320) for additional logs (on the right you can browse through all files).

`cat x64-linux-windows-static.cmake`
```cmake
# from https://stackoverflow.com/questions/58777810/how-to-integrate-vcpkg-in-linux-with-cross-build-toolchain-as-well-as-sysroot

set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_CMAKE_SYSTEM_NAME MinGW)

set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE /usr/src/mxe/usr/x86_64-w64-mingw32.shared.posix/share/cmake/mxe-conf.cmake)

```

**Comment by longnguyen2004** [comment]
`boost-build` is not intended to be cross-compiled. It is a build system for Boost libraries, so it needs to be built with the native triplet.
(Unless you actually want to cross-compile it, in that case why?)

**Comment by autoantwort** [comment]
> It is a build system for Boost libraries, so it needs to be built with the native triplet.

Exactly. But how?

**Comment by longnguyen2004** [comment]
Just build `boost-build` separately using the native triplet, then build the rest of `boost` using the cross triplet of your choice.

**Comment by autoantwort** [comment]
Afaik this is not possible when using manifest files, but it seems #15424 solves this issue.

**Comment by autoantwort** [comment]
Works now
