### ISSUE TITLE
Could not find PowerShell Core (Linux -> Windows cross compile)

### ISSUE THREAD

**Issue by autoantwort** [microsoft/vcpkg#16236]
**Describe the bug**
I [got the message](https://git.rwth-aachen.de/leander.schulten/Lichtsteuerung/-/jobs/1472927#L320):
```
CMake Error at scripts/cmake/vcpkg_copy_tool_dependencies.cmake:26 (message):
  Could not find PowerShell Core; please open an issue to report this.
```

**Environment**
- OS: Linux (Docker Container with [mxe](https://github.com/mxe/mxe))
- Compiler: x86_64-w64-mingw32.shared.posix-gcc (GCC) 8.4.0

**To Reproduce**
1. Use the mxe environment 
1. ./vcpkg install aubio --triplet=x64-linux-windows-static
2. See error

**Expected behavior**
Do error

**Failure logs** 
See [here](https://git.rwth-aachen.de/leander.schulten/Lichtsteuerung/-/jobs/1472927#L320) for additional logs (on the right you can browse through all files).

`cat x64-linux-windows-static.cmake`
```cmake
# from https://stackoverflow.com/questions/58777810/how-to-integrate-vcpkg-in-linux-with-cross-build-toolchain-as-well-as-sysroot

set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_CMAKE_SYSTEM_NAME MinGW)

set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE /usr/src/mxe/usr/x86_64-w64-mingw32.shared.posix/share/cmake/mxe-conf.cmake)

```

**Additional context**
Used vcpkg + #16051

**Comment by longnguyen2004** [comment]
Can you try installing `pwsh` on your Docker container before running `vcpkg`?
(see [this link](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7.1) for more info)

**Comment by autoantwort** [comment]
That worked 👍

**Comment by longnguyen2004** [comment]
Probably needs some documentation update then. Do you know who to cc?

**Comment by autoantwort** [comment]
I have created a PR

**Comment by longnguyen2004** [comment]
Thanks for the PR!
It's nice seeing others help to maintain the mingw ports, seeing sfhacker everywhere is frustrating...

**Comment by JackBoosY** [comment]
@longnguyen2004 Just ignore him.

**Comment by kxgy** [comment]
cmake -DMINGW:BOOL="TRUE" ...

**Comment by WentsingNee** [comment]
> cmake -DMINGW:BOOL="TRUE" ...

It works for me! Thank U
