### ISSUE TITLE
[expat] build failure

### ISSUE THREAD

**Issue by davidsummers** [microsoft/vcpkg#16241]
**Host Environment**
- OS: MacOS Catalina 10.5.7
- Compiler: Apple clang version 12.0.0 (clang-1200.0.32.29)

**To Reproduce**
`./vcpkg install expat`

**Failure logs** 
SumMac:vcpkg-master david$ ./vcpkg install expat
Computing installation plan...
The following packages will be built and installed:
    expat[core]:x64-osx -> 2020-08-18
Detecting compiler hash for triplet x64-osx...
Could not locate cached archive: /Users/david/.cache/vcpkg/archives/c1/c19d0e363fba2c97fbcfc742b206b8d4f780d2d5.zip
Starting package 1/1: expat:x64-osx
Building package expat[core]:x64-osx...
-- Using cached /Users/david/.local/share/pmm/1.5.1/vcpkg-master/downloads/libexpat-libexpat-c092d40c300c6d219cb3b111932a824022265370.tar.gz
-- Cleaning sources at /Users/david/.local/share/pmm/1.5.1/vcpkg-master/buildtrees/expat/src/4022265370-c332802cb4.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /Users/david/.local/share/pmm/1.5.1/vcpkg-master/downloads/libexpat-libexpat-c092d40c300c6d219cb3b111932a824022265370.tar.gz
-- Applying patch pkgconfig.patch
-- Using source at /Users/david/.local/share/pmm/1.5.1/vcpkg-master/buildtrees/expat/src/4022265370-c332802cb4.clean
-- Configuring x64-osx-dbg
-- Configuring x64-osx-rel
-- Building x64-osx-dbg
-- Building x64-osx-rel
CMake Error at scripts/cmake/vcpkg_find_acquire_program.cmake:535 (message):
  Could not find pkg-config.  Please install it via your package manager:

      brew install pkg-config
Call Stack (most recent call first):
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:112 (vcpkg_find_acquire_program)
  ports/expat/portfile.cmake:30 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:131 (include)

Error: Building package expat:x64-osx failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: expat:x64-osx
  Vcpkg version: 2021-01-13-unknownhash

**Additional context**
I was trying to install wxWidgets 3.1.4 on MacOS when I discovered this dependency of wxWidgets that wasn't building correctly.

This appears to build correctly on Windows but not on MacOS (currently).

My understanding is that MacOS Catalina and above don't require HomeBrew installed????  Is that correct?  That is what vcpkg Quick Start says, if I understand it correctly.

I *do* have HomeBrew installed for several binary packages, including Telnet.  Is it possible VCPKG or EXPAT is detecting HomeBrew and trying to configure for it?

**Comment by NancyLi1013** [comment]
Hi @davidsummers 

Thanks for posting this issue.

Please try to  `brew install pkg-config` and then rebuild `expat`. Since it requires `pkg-config` program.

On Windows, it will be installed automatically included in msys2. Please see the build process:

```
The following packages will be built and installed:
    expat[core]:x86-windows -> 2020-08-18
Starting package 1/1: expat:x86-windows
Building package expat[core]:x86-windows...
A suitable version of powershell-core was not found (required v7.1.0). Downloading portable powershell-core v7.1.0...
Downloading powershell-core...
  https://github.com/PowerShell/PowerShell/releases/download/v7.1.0/PowerShell-7.1.0-win-x86.zip -> F:\tool\vcpkg\downloads\PowerShell-7.1.0-win-x86.zip
Extracting powershell-core...
-- Downloading https://github.com/libexpat/libexpat/archive/c092d40c300c6d219cb3b111932a824022265370.tar.gz -> libexpat-libexpat-c092d40c300c6d219cb3b111932a824022265370.tar.gz...
-- Extracting source F:/tool/vcpkg/downloads/libexpat-libexpat-c092d40c300c6d219cb3b111932a824022265370.tar.gz
-- Applying patch pkgconfig.patch
-- Using source at F:/tool/vcpkg/buildtrees/expat/src/4022265370-c332802cb4
-- Found ninja('1.8.2') but at least version 1.10.1 is required! Trying to use internal version if possible!
-- Downloading https://github.com/ninja-build/ninja/releases/download/v1.10.1/ninja-win.zip -> ninja-win-1.10.1.zip...
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst -> msys-mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst...
-- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst -> msys-mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst...
-- Using msys root at F:/tool/vcpkg/downloads/tools/msys2/50864d9fae363d6e
-- Fixing pkgconfig file: F:/tool/vcpkg/packages/expat_x86-windows/lib/pkgconfig/expat.pc
-- Fixing pkgconfig file: F:/tool/vcpkg/packages/expat_x86-windows/debug/lib/pkgconfig/expat.pc
-- Installing: F:/tool/vcpkg/packages/expat_x86-windows/share/expat/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package expat[core]:x86-windows... done
Installing package expat[core]:x86-windows...
Installing package expat[core]:x86-windows... done
Elapsed time for package expat:x86-windows: 1.151 min

Total elapsed time: 1.155 min

The package expat:x86-windows provides CMake targets:

    find_package(expat CONFIG REQUIRED)
    target_link_libraries(main PRIVATE expat::expat)
```

**Comment by davidsummers** [comment]
Sure, I can do that.

It just didn't sound like that should be needed for MacOS Big Sur????

**Comment by davidsummers** [comment]
That worked, thanks!

It is just surprising that vcpkg also requires pkg-config?

Or is it just using pkg-config for expat because it detected HomeBrew on my system?

Is there a way to get it to install without requiring HomeBrew (pkg-config)?

Thanks!

**Comment by longnguyen2004** [comment]
> The VCPKG instructions say HomeBrew might be needed for MacOS Before Catalina.

It said that MacOS before Catalina needs to install `gcc` from homebrew, not homebrew itself

> Question: It is just surprising that vcpkg also requires pkg-config?

`vcpkg` itself doesn't require `pkg-config`, but many libraries create `pc` files to help build systems find the libraries, so `vcpkg` need to "fix" the files to make it work, and that requires `pkg-config`

**Comment by NancyLi1013** [comment]
Seems this issue has been solved now. @longnguyen2004, thanks for your help.

**Comment by davidsummers** [comment]
Thanks for the information.  It was unclear from reading the documentation.

I thought VCPKG was stand-alone and it seems that sometimes it is not.

That is fine, I just didn't know until now.
