### ISSUE TITLE
[Boost] static build is not visible via DCMAKE_TOOLCHAIN_FILE

### ISSUE THREAD

**Issue by dsazonoff** [microsoft/vcpkg#16242]
**Host Environment**
- OS: Windows
- Compiler: MSVS 2019

**To Reproduce**
1) `vcpkg install boost:x64-windows-static`
2) Build any cmake project with `-DCMAKE_TOOLCHAIN_FILE=./extern/vcpkg/scripts/buildsystems/vcpkg.cmake`

**Failure logs** 
Boost is not found:
`Could NOT find Boost (missing: Boost_INCLUDE_DIR program_options)`

**Additional context**
If I install boost with `vcpkg install boost:x64-windows` it will find a boost, but there will be always a dynamic linkage, even with `set(Boost_USE_STATIC_LIBS ON)`
Seems that there is a similar issue: https://stackoverflow.com/questions/60132392/using-static-boost-libraries-with-vcpkg-and-cmake

**Comment by autoantwort** [comment]
You have to set the triplet to `x64-windows-static` when compiling your program, the default is `x64-windows`.

**Comment by dsazonoff** [comment]
> You have to set the triplet to `x64-windows-static` when compiling your program, the default is `x64-windows`.

That is exactly what I did. See 1 step.

**Comment by autoantwort** [comment]
> > You have to set the triplet to `x64-windows-static` when compiling your program, the default is `x64-windows`.
> 
> That is exactly what I did. See 1 step.

No, you have set the triplet while installing the dependency, but not when building your application

**Comment by autoantwort** [comment]
See https://github.com/microsoft/vcpkg/blob/master/docs/users/integration.md#with-cmake

**Comment by dsazonoff** [comment]
Yes, you are right, I did it in a wrong way. My issue appears after switching to a static linkage.
So, ticket should be closed, thanks.
