### ISSUE TITLE
[glibmm] update to ver. 2.68.0

### ISSUE THREAD

**Issue by ketchup98** [microsoft/vcpkg#16249]
Library name: glibmm

New version number: 2.68.0

https://github.com/GNOME/glibmm

**Comment by Neumann-A** [comment]
requires glib to be updated. Closed by #13100

**Comment by PikachuHy** [comment]
When I use glibmm (glibmm-2.68) with MSVC, I meet
```
“glibmmconfig.h”: No such file or directory
```

see https://github.com/microsoft/vcpkg/pull/6621

**Comment by Neumann-A** [comment]
this is not related to #6621. The header is installed into `lib/include/glibmm-2.68` if my memory serves me right and this case is not correctly covered by the lazy MSBuild integration.
