### ISSUE TITLE
Why is HowardHinnant Date library not included in vcpkg?

### ISSUE THREAD

**Issue by juandent** [Microsoft/vcpkg#1624]
**https://github.com/HowardHinnant/date** is a superb addition to the chronos library in std. I have no doubt that it should be among vcpkg's packages.

Best regards,
Juan Dent

**Comment by ras0219-msft** [comment]
We'd love to accept a PR for this library!

**Comment by juandent** [comment]
ok, with pleasure. ... what is the procedure?

**Comment by atkawa7** [comment]
@juandent see https://github.com/Microsoft/vcpkg/blob/master/docs/examples/packaging-zlib.md

**Comment by juandent** [comment]
I created the port with:

>vcpkg.exe create date  https://github.com/HowardHinnant/date.git date.git

for which I got:

>-- Generated portfile: C:\Users\Juan Dent\C++ Development\Source Components\vcpkg-master\ports\date\portfile.cmake
-- Generated CONTROL: C:\Users\Juan Dent\C++ Development\Source Components\vcpkg-master\ports\date\CONTROL

Now when I try to build, with:

>vcpkg.exe build date

I get these messages:

>-- CURRENT_INSTALLED_DIR=C:/Users/Juan Dent/C++ Development/Source Components/vcpkg-master/installed/x86-windows
-- DOWNLOADS=C:/Users/Juan Dent/C++ Development/Source Components/vcpkg-master/downloads
-- CURRENT_PACKAGES_DIR=C:/Users/Juan Dent/C++ Development/Source Components/vcpkg-master/packages/date_x86-windows
-- CURRENT_BUILDTREES_DIR=C:/Users/Juan Dent/C++ Development/Source Components/vcpkg-master/buildtrees/date
-- CURRENT_PORT_DIR=C:/Users/Juan Dent/C++ Development/Source Components/vcpkg-master/ports/date/.
-- Using cached C:/Users/Juan Dent/C++ Development/Source Components/vcpkg-master/downloads/date.git
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting source C:/Users/Juan Dent/C++ Development/Source Components/vcpkg-master/downloads/date.git
CMake Error at C:/Users/Juan Dent/C++ Development/Source Components/vcpkg-master/scripts/cmake/vcpkg_execute_required_process.cmake:43 (message):
    Command failed: C:/Program Files/CMake/bin/cmake.exe;-E;tar;xjf;C:/Users/Juan Dent/C++ Development/Source Components/vcpkg-master/downloads/date.git
    Working Directory: C:/Users/Juan Dent/C++ Development/Source Components/vcpkg-master/buildtrees/date/src
    See logs for more information:
      C:\Users\Juan Dent\C++ Development\Source Components\vcpkg-master\buildtrees\date\extract-out.log
      C:\Users\Juan Dent\C++ Development\Source Components\vcpkg-master\buildtrees\date\extract-err.log
Call Stack (most recent call first):
  C:/Users/Juan Dent/C++ Development/Source Components/vcpkg-master/scripts/cmake/vcpkg_extract_source_archive.cmake:49 (vcpkg_execute_required_process)
  C:/Users/Juan Dent/C++ Development/Source Components/vcpkg-master/scripts/cmake/vcpkg_extract_source_archive.cmake:61 (vcpkg_extract_source_archive_ex)
  C:/Users/Juan Dent/C++ Development/Source Components/vcpkg-master/ports/date/portfile.cmake:20 (vcpkg_extract_source_archive)
  C:/Users/Juan Dent/C++ Development/Source Components/vcpkg-master/scripts/ports.cmake:73 (include)Call Stack (most recent call first):
  C:/Users/Juan Dent/C++ Development/Source Components/vcpkg-master/scripts/cmake/vcpkg_extract_source_archive.cmake:49 (vcpkg_execute_required_process)
  C:/Users/Juan Dent/C++ Development/Source Components/vcpkg-master/scripts/cmake/vcpkg_extract_source_archive.cmake:61 (vcpkg_extract_source_archive_ex)
  C:/Users/Juan Dent/C++ Development/Source Components/vcpkg-master/ports/date/portfile.cmake:20 (vcpkg_extract_source_archive)
  C:/Users/Juan Dent/C++ Development/Source Components/vcpkg-master/scripts/ports.cmake:73 (include) 
Error: Building package date:x86-windows failed with: BUILD_FAILED

I am not a CMAKE expert so I am at a loss here...

Thanks for any help.

Juan Dent

**Comment by atkawa7** [comment]
@juandent  vcpkg `create` is expecting archive url i.e [`https://github.com/HowardHinnant/date/archive/v2.2.zip`](https://github.com/HowardHinnant/date/archive/v2.2.zip)
[`https://github.com/HowardHinnant/date/archive/v2.2.tar.gz`](https://github.com/HowardHinnant/date/archive/v2.2.tar.gz) but you gave it this instead `https://github.com/HowardHinnant/date.git` . 

Should have been 

`vcpkg.exe create date https://github.com/HowardHinnant/date/archive/v2.2.zip date.zip`

 Another issue that you will likely come across is `HowardHinnant/date.git` doesn't have CMakeLists.txt and you might have to create a custom CMakeLists.txt depending on whether it a header only lib. 

- For header only projects see
    - https://github.com/Microsoft/vcpkg/blob/master/ports/nuklear/portfile.cmake. 
    - https://github.com/Microsoft/vcpkg/blob/master/ports/aurora/portfile.cmake.
- For non header  projects see
     - https://github.com/Microsoft/vcpkg/tree/master/ports/minizip
    - https://github.com/Microsoft/vcpkg/tree/master/ports/uriparser
    - https://github.com/Microsoft/vcpkg/tree/master/ports/pystring

**Comment by atkawa7** [comment]
@juandent  see #1748

**Comment by atkawa7** [comment]
@ras0219-msft Should this be closed?
