### ISSUE TITLE
[New Port Request] SimpleAmqpClient

### ISSUE THREAD

**Issue by humayunkhan** [microsoft/vcpkg#16247]
Library name: SimpleAmqpClient

Library description: SimpleAmqpClient is an easy-to-use C++ wrapper around the rabbitmq-c C library

Source repository URL: https://github.com/alanxz/SimpleAmqpClient

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
