### ISSUE TITLE
Error: Building package ffmpeg:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by Prince3141** [microsoft/vcpkg#16253]
Error: Building package ffmpeg:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: ffmpeg:x64-windows
  Vcpkg version: 2021-01-13-768d8f95c9e752603d2c5901c7a7c7fbdb08af35

Additionally, attach any relevant sections from the log files above.
PS C:\Users\prince brahmenia\temp\vcpkg> .\vcpkg update
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.

**Comment by JonLiu1993** [comment]
@Prince3141 ,Can you send a complete error log? I can build normally locally：
````
-- Installing: F:/test2/vcpkg/packages/ffmpeg_x64-windows/share/ffmpeg/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\vzhli17\AppData\Local\vcpkg\archives\01\01bb2c7e11b630248a7735d497ae0ee7197d1d4b.zip
Building package ffmpeg[avcodec,avdevice,avfilter,avformat,avresample,core,gpl,postproc,swresample,swscale]:x64-windows... done
Installing package ffmpeg[avcodec,avdevice,avfilter,avformat,avresample,core,gpl,postproc,swresample,swscale]:x64-windows...
Installing package ffmpeg[avcodec,avdevice,avfilter,avformat,avresample,core,gpl,postproc,swresample,swscale]:x64-windows... done
Elapsed time for package ffmpeg:x64-windows: 16.54 min

Total elapsed time: 16.62 min
````

**Comment by Prince3141** [comment]
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\prince brahmenia> cd temp
PS C:\Users\prince brahmenia\temp> dir


    Directory: C:\Users\prince brahmenia\temp


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        16-02-2021     21:46                vcpkg


PS C:\Users\prince brahmenia\temp>  git clone https://github.com/microsoft/vcpkg
fatal: destination path 'vcpkg' already exists and is not an empty directory.
PS C:\Users\prince brahmenia\temp> cd vcpkg
PS C:\Users\prince brahmenia\temp\vcpkg> $env:VCPKG_ROOT=$PWD
PS C:\Users\prince brahmenia\temp\vcpkg>  .\bootstrap-vcpkg.bat
Downloading https://github.com/microsoft/vcpkg-tool/releases/download/2021-01-13-768d8f95c9e752603d2c5901c7a7c7fbdb08af35/vcpkg.exe -> C:\Users\prince brahmenia\temp\vcpkg/vcpkg.exe
Done.

Telemetry
---------
vcpkg collects usage data in order to help us improve your experience.
The data collected by Microsoft is anonymous.
You can opt-out of telemetry by re-running the bootstrap-vcpkg script with -disableMetrics,
passing --disable-metrics to vcpkg on the command line,
or by setting the VCPKG_DISABLE_METRICS environment variable.

Read more about vcpkg telemetry at docs/about/privacy.md
PS C:\Users\prince brahmenia\temp\vcpkg>  .\vcpkg install darknet[opencv-base,cuda,cudnn]:x64-windows
Computing installation plan...
The following packages will be built and installed:
    darknet[core,cuda,cudnn,opencv-base]:x64-windows -> 2021-01-21
  * ffmpeg[avcodec,avdevice,avfilter,avformat,avresample,core,gpl,postproc,swresample,swscale]:x64-windows -> 4.3.1#11
  * libjpeg-turbo[core]:x64-windows -> 2.0.6
  * liblzma[core]:x64-windows -> 5.2.5#2
  * libpng[core]:x64-windows -> 1.6.37#14
  * libwebp[core,nearlossless,simd,unicode]:x64-windows -> 1.1.0#1
  * opencv[core,dnn,ffmpeg,jpeg,png,quirc,tiff,webp]:x64-windows -> 4.5.1
  * opencv4[core,dnn,ffmpeg,jpeg,png,quirc,tiff,webp]:x64-windows -> 4.5.1
  * protobuf[core]:x64-windows -> 3.14.0#1
  * pthreads[core]:x64-windows -> 3.0.0-6
  * quirc[core]:x64-windows -> 1.1#2
  * stb[core]:x64-windows -> 2020-09-14
  * tiff[core]:x64-windows -> 4.1.0#1
  * zlib[core]:x64-windows -> 1.2.11#9
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\prince brahmenia\AppData\Local\vcpkg\archives\fc\fce80883566c01f3cb1e93e7a2452ea80013aa7e.zip
Could not locate cached archive: C:\Users\prince brahmenia\AppData\Local\vcpkg\archives\47\4784bd6c17f975d3bd69ddb5f4456f49920f360e.zip
Could not locate cached archive: C:\Users\prince brahmenia\AppData\Local\vcpkg\archives\ac\acebc5718aec98de91f8973f583ca53938bc6a3f.zip
Could not locate cached archive: C:\Users\prince brahmenia\AppData\Local\vcpkg\archives\55\551fba95a7cfb8f68dbae2f9cb188784855f8833.zip
Could not locate cached archive: C:\Users\prince brahmenia\AppData\Local\vcpkg\archives\ba\ba2f2e27a247f9d4db85ba72c1f3669701378281.zip
Could not locate cached archive: C:\Users\prince brahmenia\AppData\Local\vcpkg\archives\14\14f7bd1dad626fa95e87d3067637e7d5c3f7e120.zip
Could not locate cached archive: C:\Users\prince brahmenia\AppData\Local\vcpkg\archives\78\784efad290065b3955ba68ce2ad62e28604c7bdd.zip
Could not locate cached archive: C:\Users\prince brahmenia\AppData\Local\vcpkg\archives\5f\5f6ce083eee780eb60483f10de3cf98ff25651a7.zip
Could not locate cached archive: C:\Users\prince brahmenia\AppData\Local\vcpkg\archives\4d\4d6d82e4575b29cf73117eb662f9efac71022ec4.zip
Could not locate cached archive: C:\Users\prince brahmenia\AppData\Local\vcpkg\archives\86\86874c39320860fb061575214a15c721e73b5893.zip
Could not locate cached archive: C:\Users\prince brahmenia\AppData\Local\vcpkg\archives\2c\2c78b0c3f197b1e520bf8cfcfb746cf8592f983f.zip
Could not locate cached archive: C:\Users\prince brahmenia\AppData\Local\vcpkg\archives\48\4884e4de1548a5a029f121acd8e08f79f2ba2a1f.zip
Could not locate cached archive: C:\Users\prince brahmenia\AppData\Local\vcpkg\archives\44\44a8cc1d919d763ae57011b0e74dc2ea251d5988.zip
Could not locate cached archive: C:\Users\prince brahmenia\AppData\Local\vcpkg\archives\7a\7aea902549b37766bfa704fba6472ad9052c6e80.zip
Starting package 1/14: ffmpeg:x64-windows
Building package ffmpeg[avcodec,avdevice,avfilter,avformat,avresample,core,gpl,postproc,swresample,swscale]:x64-windows...
-- Using cached C:/Users/prince brahmenia/temp/vcpkg/downloads/ffmpeg-ffmpeg-n4.3.1.tar.gz
-- Cleaning sources at C:/Users/prince brahmenia/temp/vcpkg/buildtrees/ffmpeg/src/n4.3.1-a2a92eb697.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/prince brahmenia/temp/vcpkg/downloads/ffmpeg-ffmpeg-n4.3.1.tar.gz
-- Applying patch 0001-create-lib-libraries.patch
-- Applying patch 0003-fix-windowsinclude.patch
-- Applying patch 0004-fix-debug-build.patch
-- Applying patch 0005-fix-libvpx-linking.patch
-- Applying patch 0006-fix-StaticFeatures.patch
-- Applying patch 0007-fix-lib-naming.patch
-- Applying patch 0008-Fix-wavpack-detection.patch
-- Applying patch 0009-Fix-fdk-detection.patch
-- Applying patch 0010-Fix-x264-detection.patch
-- Applying patch 0011-Fix-x265-detection.patch
-- Applying patch 0012-Fix-ssl-110-detection.patch
-- Applying patch 0013-define-WINVER.patch
-- Applying patch 0014-avfilter-dependency-fix.patch
-- Using source at C:/Users/prince brahmenia/temp/vcpkg/buildtrees/ffmpeg/src/n4.3.1-a2a92eb697.clean
CMake Error at ports/ffmpeg/portfile.cmake:24 (message):
  Error: ffmpeg will not build with spaces in the path.  Please use a
  directory with no spaces
Call Stack (most recent call first):
  scripts/ports.cmake:131 (include)


Error: Building package ffmpeg:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: ffmpeg:x64-windows
  Vcpkg version: 2021-01-13-768d8f95c9e752603d2c5901c7a7c7fbdb08af35

Additionally, attach any relevant sections from the log files above.
PS C:\Users\prince brahmenia\temp\vcpkg>

**Comment by JonLiu1993** [comment]
Hi @Prince3141 ,

_C:\Users\prince brahmenia\temp\vcpkg_

Since building ffmpeg in a path with spaces will cause some errors, please re-clone vcpkg and install ffmpeg in a path that does not contain spaces.

Thanks.

**Comment by JackBoosY** [comment]
```
CMake Error at ports/ffmpeg/portfile.cmake:24 (message):
Error: ffmpeg will not build with spaces in the path. Please use a
directory with no spaces
```

**Comment by S0nathan** [comment]
Exactly the same error log, and my understanding is too low for the syntax provided in the error message and the reply here.

**Comment by JonLiu1993** [comment]
@Prince3141 ,Have you tried the advice that @JackBoosY  and I gave you? Has this problem been resolved?

**Comment by PhoebeHui** [comment]
The vcpkg path 'C:/Users/prince brahmenia/temp/vcpkg' contains space, please clone vcpkg without space in path and try again.
