### ISSUE TITLE
Opencascade "Cannot open include file: 'Standard.hxx'"

### ISSUE THREAD

**Issue by fauder** [microsoft/vcpkg#16252]
**Describe the bug**
Opencascade 7.5.0 builds (as windows-x64-static) without any errors. 
However Visual Studio 2019 can not find the header files for Opencascade itself whenever a header from said library is included.
For example when I want to `#include <opencascade/gp.hxx>`, Visual Studio 2019 says:
`1>C:\Sys\vcpkg\installed\x64-windows-static\include\opencascade\gp.hxx(20,10): fatal error C1083: Cannot open include file: 'Standard.hxx': No such file or directory`

**Environment**
- OS: Windows 10
- Compiler: Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29337 for x86

**To Reproduce**
1. ./vcpkg install opencascade.
2. Create empty project (C++) in Visual Studio 2019.
3. Create a .cpp file and `#include <opencascade/gp.hxx>`.
4. See error: `1>C:\Sys\vcpkg\installed\x64-windows-static\include\opencascade\gp.hxx(20,10): fatal error C1083: Cannot open include file: 'Standard.hxx': No such file or directory`.

**Comment by fauder** [comment]
And yes I did run bootstrap.bat and `vcpkg integrate install`. I also use various libraries via vcpkg such as Magnum, Corrade and wxWidgets. All work fine.

**Comment by Dejauxvue** [comment]
I solved the problem for me locally, I think there are two issues:
1. the opencascade does not export include/opencascade as public include directory
this can be fixed by: 
<details>
<summary> add include/opencascade to include_libraries</summary>

```
---
 CMakeLists.txt | 9 +++++++++
 1 file changed, 9 insertions(+)

diff --git a/CMakeLists.txt b/CMakeLists.txt
index 100d613..464f95a 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -1171,6 +1171,15 @@ foreach (OCCT_MODULE ${OCCT_MODULES})
 endforeach()
 set (OCCT_MODULES_ENABLED ${OCCT_MODULES_ENABLED_SORTED})
 
+foreach (OCCT_LIBRARY ${OCCT_LIBRARIES})
+	target_include_directories(
+		${OCCT_LIBRARY} 
+		INTERFACE
+		#$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/source>
+		$<INSTALL_INTERFACE:include/opencascade>)
+
+endforeach()
+
 # Add all targets to the build-tree export set
 export (TARGETS ${OCCT_LIBRARIES} FILE "${CMAKE_BINARY_DIR}/OpenCASCADETargets.cmake")
 
-- 
2.14.3.windows.1

```
 
</details>
Then, everything works fine, when using Visual Studio's CMakeLists.txt integration.




2. However when using `vcpkg integrate install` these include directories seem to get ignored and the problem remains.

For some reason, opencascade uses `#include<...>` for internal headers. The following fix worked for me.

<details>
<summary> replace `#include<...>` with `#include "..."` for internal headers</summary>

```
---
 ports/opencascade/portfile.cmake | 27 ++++++++++++++++++++++++++-
 1 file changed, 26 insertions(+), 1 deletion(-)

diff --git a/ports/opencascade/portfile.cmake b/ports/opencascade/portfile.cmake
index f686de586..f704d952f 100644
--- a/ports/opencascade/portfile.cmake
+++ b/ports/opencascade/portfile.cmake
@@ -46,6 +46,30 @@ vcpkg_install_cmake()
 
 vcpkg_fixup_cmake_targets(CONFIG_PATH lib/cmake/opencascade TARGET_PATH share/opencascade)
 
+
+
+#make occt includes relative to source_file
+
+list(APPEND ADDITIONAL_HEADERS 
+      "ExprIntrp.tab.h"
+	  "FlexLexer.h"
+	  "glext.h"
+	  "igesread.h"
+	  "NCollection_Haft.h"
+	  "OSD_PerfMeter.h"
+	  "Standard_values.h"
+    )
+
+file(GLOB files "${CURRENT_PACKAGES_DIR}/include/opencascade/[a-zA-Z0-9_]*\.[hgl]xx")
+foreach(file_name ${files})
+	file(READ ${file_name} filedata)
+	string(REGEX REPLACE "#include \<([a-zA-Z0-9_]*\.[hgl]xx|ExprIntrp.tab.h|FlexLexer.h|glext.h|igesread.h|NCollection_Haft.h|OSD_PerfMeter.h|Standard_values.h)\>" "#include \"\\1\"" filedata "${filedata}")
+	foreach(extra_header ${ADDITIONAL_HEADERS})
+		string(REGEX REPLACE "#include \<${extra_header}\>" "#include \"${extra_header}\"" filedata "${filedata}")
+	endforeach()
+	file(WRITE ${file_name} "${filedata}")
+endforeach()
+
 # Remove libd to lib, libd just has cmake files we dont want too
 file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/lib)
 file(RENAME ${CURRENT_PACKAGES_DIR}/debug/libd ${CURRENT_PACKAGES_DIR}/debug/lib)
@@ -86,4 +110,5 @@ else()
 endif()
 
 file(INSTALL ${SOURCE_PATH}/OCCT_LGPL_EXCEPTION.txt DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)
-file(COPY ${CURRENT_PACKAGES_DIR}/include/opencascade DESTINATION ${CURRENT_PACKAGES_DIR}/include)
+#file(INSTALL ${CURRENT_PACKAGES_DIR}/include/opencascade/ DESTINATION ${CURRENT_PACKAGES_DIR}/include)
+
-- 
2.14.3.windows.1

```
 
</details>

**Comment by NancyLi1013** [comment]
Hi @Dejauxvue 

Thanks for posting this issue.

Have you set `<VcpkgTriplet Condition="'$(Platform)'=='x64'">x64-windows-static</VcpkgTriplet>` in your project?

When building a static library, please refer to this:
https://devblogs.microsoft.com/cppblog/vcpkg-updates-static-linking-is-now-available/#using-static-libraries

**Comment by fauder** [comment]
As I said before, everything else (vcpkg-related) works without any issues. I have wxWidgets, Corrade, Magnum, fmt, utfcpp (and one or two other libraries I forgot) that I use in this project **with** vcpkg. This is not a usage error, but a bug.

As @Dejauxvue said, the problem is with the #includes in opencascade's internal headers. Yes I can temporarily solve it by editing those includes to point to directories with actual headers inside. But it should also be handled on the vcpkg side as it is a bug.

**Comment by fauder** [comment]
> 
> 
> I solved the problem for me locally, I think there are two issues:
> 
>     1. the opencascade does not export include/opencascade as public include directory
>        this can be fixed by:
> 
> 
> add include/opencascade to include_libraries
> 
> ```
> ---
>  CMakeLists.txt | 9 +++++++++
>  1 file changed, 9 insertions(+)
> 
> diff --git a/CMakeLists.txt b/CMakeLists.txt
> index 100d613..464f95a 100644
> --- a/CMakeLists.txt
> +++ b/CMakeLists.txt
> @@ -1171,6 +1171,15 @@ foreach (OCCT_MODULE ${OCCT_MODULES})
>  endforeach()
>  set (OCCT_MODULES_ENABLED ${OCCT_MODULES_ENABLED_SORTED})
>  
> +foreach (OCCT_LIBRARY ${OCCT_LIBRARIES})
> +	target_include_directories(
> +		${OCCT_LIBRARY} 
> +		INTERFACE
> +		#$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/source>
> +		$<INSTALL_INTERFACE:include/opencascade>)
> +
> +endforeach()
> +
>  # Add all targets to the build-tree export set
>  export (TARGETS ${OCCT_LIBRARIES} FILE "${CMAKE_BINARY_DIR}/OpenCASCADETargets.cmake")
>  
> -- 
> 2.14.3.windows.1
> ```
> 
> Then, everything works fine, when using Visual Studio's CMakeLists.txt integration.
> 
>     1. However when using `vcpkg integrate install` these include directories seem to get ignored and the problem remains.
> 
> 
> For some reason, opencascade uses `#include<...>` for internal headers. The following fix worked for me.
> replace `#include<...>` with `#include "..."` for internal headers
> 
> ```
> ---
>  ports/opencascade/portfile.cmake | 27 ++++++++++++++++++++++++++-
>  1 file changed, 26 insertions(+), 1 deletion(-)
> 
> diff --git a/ports/opencascade/portfile.cmake b/ports/opencascade/portfile.cmake
> index f686de586..f704d952f 100644
> --- a/ports/opencascade/portfile.cmake
> +++ b/ports/opencascade/portfile.cmake
> @@ -46,6 +46,30 @@ vcpkg_install_cmake()
>  
>  vcpkg_fixup_cmake_targets(CONFIG_PATH lib/cmake/opencascade TARGET_PATH share/opencascade)
>  
> +
> +
> +#make occt includes relative to source_file
> +
> +list(APPEND ADDITIONAL_HEADERS 
> +      "ExprIntrp.tab.h"
> +	  "FlexLexer.h"
> +	  "glext.h"
> +	  "igesread.h"
> +	  "NCollection_Haft.h"
> +	  "OSD_PerfMeter.h"
> +	  "Standard_values.h"
> +    )
> +
> +file(GLOB files "${CURRENT_PACKAGES_DIR}/include/opencascade/[a-zA-Z0-9_]*\.[hgl]xx")
> +foreach(file_name ${files})
> +	file(READ ${file_name} filedata)
> +	string(REGEX REPLACE "#include \<([a-zA-Z0-9_]*\.[hgl]xx)\>" "#include \"\\1\"" filedata "${filedata}")
> +	foreach(extra_header ${ADDITIONAL_HEADERS})
> +		string(REGEX REPLACE "#include \<${extra_header}\>" "#include \"${extra_header}\"" filedata "${filedata}")
> +	endforeach()
> +	file(WRITE ${file_name} "${filedata}")
> +endforeach()
> +
>  # Remove libd to lib, libd just has cmake files we dont want too
>  file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/lib)
>  file(RENAME ${CURRENT_PACKAGES_DIR}/debug/libd ${CURRENT_PACKAGES_DIR}/debug/lib)
> @@ -86,4 +110,5 @@ else()
>  endif()
>  
>  file(INSTALL ${SOURCE_PATH}/OCCT_LGPL_EXCEPTION.txt DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)
> -file(COPY ${CURRENT_PACKAGES_DIR}/include/opencascade DESTINATION ${CURRENT_PACKAGES_DIR}/include)
> +#file(INSTALL ${CURRENT_PACKAGES_DIR}/include/opencascade/ DESTINATION ${CURRENT_PACKAGES_DIR}/include)
> +
> -- 
> 2.14.3.windows.1
> ```

As a complete CMake newbie, I applied the changes you mentioned to my local copy of vcpkg repository. To make these changes actually "apply" do I have to vcpkg remove opencascade and then vcpkg install opencascade again ? It takes 40 minutes on my laptop so I want to make sure before moving on.

**Comment by Dejauxvue** [comment]
I think so. Haven't found another way myself

**Comment by fauder** [comment]
@Dejauxvue Removed and reinstalled opencascade with your changes to 2 files you mentioned. Works like a charm. Thanks.

**Comment by NancyLi1013** [comment]
@Dejauxvue 

Thanks for figuring this issue out.

Would you like to submit a pull request to upstream?

**Comment by Dejauxvue** [comment]
sure, I hope everything is in line with your conventions
and I can only test on windows Visual Studio 2019
