### ISSUE TITLE
Using vcpkg on CLion but still getting "Undefined reference to" errors

### ISSUE THREAD

**Issue by TNtube** [microsoft/vcpkg#16258]
**Host Environment**
- OS: Windows 10
- Compiler: TDM-GCC

**To Reproduce**
`./vcpkg install opencv4:x64-windows`
__CMakeFile.txt__
```
cmake_minimum_required(VERSION 3.17)

project(AsciiArt)

set(CMAKE_CXX_STANDARD 14)

find_package(OpenCV CONFIG REQUIRED)

add_executable(AsciiArt main.cpp)

target_link_libraries(AsciiArt ${OpenCV_LIBS})
```

__main.cpp__
```cpp
#include <iostream>
#include <opencv2/opencv.hpp>

int main() {
    cv::Mat frame;
    std::cout << "Hello, World!" << std::endl;
    return 0;
}
```

**Failure logs** 
```
C:\Users\TNtube\AppData\Local\JetBrains\Toolbox\apps\CLion\ch-0\203.7148.70\bin\cmake\win\bin\cmake.exe --build C:\Users\TNtube\CLionProjects\AsciiArt\cmake-build-debug --target AsciiArt -- -j 9
[ 50%] Linking CXX executable AsciiArt.exe
CMakeFiles\AsciiArt.dir\build.make:119: recipe for target 'AsciiArt.exe' failed
CMakeFiles\Makefile2:94: recipe for target 'CMakeFiles/AsciiArt.dir/all' failed
CMakeFiles\Makefile2:101: recipe for target 'CMakeFiles/AsciiArt.dir/rule' failed
Makefile:137: recipe for target 'AsciiArt' failed
C:/PROGRA~1/TDM-GCC/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\AsciiArt.dir/objects.a(main.cpp.obj): in function `main':
C:/Users/TNtube/CLionProjects/AsciiArt/main.cpp:5: undefined reference to `cv::Mat::Mat()'
C:/PROGRA~1/TDM-GCC/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Users/TNtube/CLionProjects/AsciiArt/main.cpp:5: undefined reference to `cv::Mat::~Mat()'
C:/PROGRA~1/TDM-GCC/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Users/TNtube/CLionProjects/AsciiArt/main.cpp:5: undefined reference to `cv::Mat::~Mat()'
collect2.exe: error: ld returned 1 exit status
mingw32-make.exe[3]: *** [AsciiArt.exe] Error 1
mingw32-make.exe[2]: *** [CMakeFiles/AsciiArt.dir/all] Error 2
mingw32-make.exe[1]: *** [CMakeFiles/AsciiArt.dir/rule] Error 2
mingw32-make.exe: *** [AsciiArt] Error 2
```

**Additional context**
I try to use vcpkg with CLion but I still have the same problem as above. In the CMake options that are set in the IDE, I put the option `-DCMAKE_TOOLCHAIN_FILE=C:/src/vcpkg/scripts/buildsystems/vcpkg.cmake`. The IDE recognizes the module, I have auto-completion which works but I can't build my project. The CMakeFile.txt doesn't produce any error when you launch it. Also, I am able to build the project in CLI with command lines but I can't launch anything in the IDE. The library is well installed, in command line everything works but CLion stubbornly doesn't work.

Thanks to those who will take the time to help me.

**Comment by rongworld** [comment]
I also encountered this problem

**Comment by NancyLi1013** [comment]
Hi @TNtube 

Thanks for posting this issue.

In vcpkg, `opencv2`, `opencv3 `and `opencv4 `cannot be installed at the same time.

So I wonder how you can install opencv4 successfully if you have installed `opencv2`.

@rongworld 

Could you please help confirm if you have installed different versions for `opencv`?

**Comment by TNtube** [comment]
Hello @NancyLi1013 

Only, I have not installed any other version of OpenCV. 

Once the command `./vcpkg install opencv4:x64-windows` is done, this is the only folder that appears in the `include` folder.

So now that you answer me this, I guess it's not normal. Do you have any idea how to fix this? 

Thank you in advance.

**Comment by TNtube** [comment]
![image](https://user-images.githubusercontent.com/51389578/108363607-e7725500-71d3-11eb-922f-c1028ee006bb.png)
There is a screenshot of my include folder in vcpkg

**Comment by NancyLi1013** [comment]
Thanks for your reply and above information. I will check this on my local.

**Comment by TNtube** [comment]
thank you for your time

**Comment by NancyLi1013** [comment]
I can reproduce this with compiler TMD-GCC on my machine. But it can compile successfully with compiler Visual Studio.

Sorry, I also have no idea about this issue.

@cenit 

Are you clear the error?

```
[ 50%] Building CXX object CMakeFiles/AsciiArt.dir/main.cpp.obj
[100%] Linking CXX executable AsciiArt.exe
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\AsciiArt.dir/objects.a(main.cpp.obj):main.cpp:(.text+0x1e): undefined reference to `cv::Mat::Mat()'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\AsciiArt.dir/objects.a(main.cpp.obj):main.cpp:(.text+0x51): undefined reference to `cv::Mat::~Mat()'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\AsciiArt.dir/objects.a(main.cpp.obj):main.cpp:(.text+0x64): undefined reference to `cv::Mat::~Mat()'
collect2.exe: error: ld returned 1 exit status
CMakeFiles\AsciiArt.dir\build.make:109: recipe for target 'AsciiArt.exe' failed
mingw32-make.exe[2]: *** [AsciiArt.exe] Error 1
CMakeFiles\Makefile2:93: recipe for target 'CMakeFiles/AsciiArt.dir/all' failed
mingw32-make.exe[1]: *** [CMakeFiles/AsciiArt.dir/all] Error 2
Makefile:101: recipe for target 'all' failed
mingw32-make.exe: *** [all] Error 2
```

**Comment by TNtube** [comment]
I just tried it with the Visual Studio compiler and it finally worked! Thank you very much, it helped me a lot. It's a pity that TDM-GCC doesn't work, but I'll make do with it.

Thanks again!

**Comment by cenit** [comment]
sorry i don’t have time to test that environment. 
judging from the error, it looks like the linker was not receiving proper libs to link.
did you build vcpkg and ports using the same compiler? you have to, of course...

**Comment by NancyLi1013** [comment]
Thanks for your info @cenit.

@TNtube 
Could you please try to build vcpkg and ports with the same compiler TMD-GCC?

**Comment by TNtube** [comment]
With pleasure, can you just tell me how to build vcpkg with TDM-GCC please? I have no idea how to do that, since I only run the famous `.\vcpkg\bootstrap-vcpkg.bat`. 

Thank you in advance!

**Comment by NancyLi1013** [comment]
Currently, it's unnecessary to build vcpkg. Run .\bootstrap-vcpkg.bat will download vcpkg.exe automatically.

So I also have no idea how to do this. I'm so sorry.

But I'm not sure whether it makes sense if we install the port with TMG-GCC compiler.

**Comment by cenit** [comment]
closed because you solved somehow? can you share your solution, in case other users might become interested in future?

**Comment by TNtube** [comment]
Hello, the issue seems to be from the compiler. For some reasons, MinGW refuse to build while MSVC with the same configuration work very well

**Comment by NancyLi1013** [comment]
Do we need to solve this issue on vcpkg side? @cenit 
To be honest, I have no idea how to handle this with TDM-GCC.

**Comment by cenit** [comment]
me too, i was hoping for @TNtube to have solved it and for him sharing the solution, but it seems that the best option was just dumping TDM-GCC and using MSVC

**Comment by NancyLi1013** [comment]
Thanks for your suggestion @cenit.

**Comment by wrxhardworking** [comment]
This error occurs when linking 
D:/c++projet/Thestereotype/main.cpp:78: undefined reference to `testing::Message::Message()'

**Comment by TNtube** [comment]
I'm not sure to understand what does it have to do with that almost 2yo issue

**Comment by wrxhardworking** [comment]
@TNtube so do you already console the problem?

**Comment by kakinIA** [comment]
@wrxhardworking What the compiler are you using?

**Comment by kakinIA** [comment]
@TNtube @NancyLi1013 @cenit  It also happen when i use "assimp" library on Windows. It work for me to use MSVC. But what the reason cause MinGW makes problem? Does it cause by some libraries or header files in MinGW? By the way, vcpkg on Clion has no problem on MacOS in my case.

**Comment by yuxiang40** [comment]
I also met this problem when using jsoncpp.Does anyone know how to solve that?My dev environment is clion23 on windows
