### ISSUE TITLE
[New Port Request] Flite: Small Text-To-Speech Engine

### ISSUE THREAD

**Issue by PhilLab** [microsoft/vcpkg#16251]
Library name: **Flite**

Library description: **A small run-time speech synthesis engine from the Carnegie Mellon University** 

Source repository URL: **https://github.com/festvox/flite**

Project homepage (if different from the source repository): - 

Anything else that is useful to know when adding (such as optional features the library may have that should be included): -

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
