### ISSUE TITLE
How do I install <sys/ipc.h> and <sys/msg.h>

### ISSUE THREAD

**Issue by gtsompanoglou** [microsoft/vcpkg#16279]
When asking a question please also include where you looked for an answer (so we can update the documentation if needed).

**Comment by gtsompanoglou** [comment]
I have already install vcpkg and intergrated it in my vscode editor , but when i search for those two C libraries I get nothing but this link to report any issues.

**Comment by NancyLi1013** [comment]
Hi @gtsompanoglou 

Thanks for posting this issue.

Seems `<sys/ipc.h>` and `<sys/msg.h>` are the files in GNU C library, which doesn't exist in vcpkg now. So you cannot install it via vcpkg.

You can open a new issue [here ](https://github.com/microsoft/vcpkg/issues/new?assignees=&labels=new+port+request+-+consider+making+a+PR%21&template=request-a-new-port.md&title=%5BNew+Port+Request%5D+%3Clibrary+name+here%3E)to post your request if you want to add this port in vcpkg.
