### ISSUE TITLE
[Community triplet] Add android triplet

### ISSUE THREAD

**Issue by hanseuljun** [microsoft/vcpkg#16275]
While trying to build for Android, I saw the below document.
https://github.com/microsoft/vcpkg/blob/master/docs/users/android.md

I don't mean it is super complicated or something, since I already really appreciate the mere existence of any support, is there a reason for the cmake files in the "Create the android triplets" to not exist inside vcpkg/triplets/community?

Since placing inside community does not mean official support with CI, I think it is okay to place them there since it is less demanded but a still somehow supported.

The main cause for this question is due to seeing like below. I want to avoid seeing a message like below when I type git status after following the instructions given above...

![image](https://user-images.githubusercontent.com/5001447/108337808-617dec00-718a-11eb-87f7-10920a1fbe08.png)

**Comment by JackBoosY** [comment]
We welcome the addition of android triplet to the community triplet, but this means that we must add android to the common functions in vcpkg, and these stuff are now being implemented.
We hope that users do not need to set other options besides installing the necessary SDK when using android triplet, just like other triplets.

See related PR:
https://github.com/microsoft/vcpkg/pull/16260
https://github.com/microsoft/vcpkg/pull/15605
https://github.com/microsoft/vcpkg/pull/12634
etc.

**Comment by hanseuljun** [comment]
Thanks for answering! Seeing actual examples helps understanding the ongoing effort much better which I really appreciate! Seems like community triplets have higher standards than I thought (I mean this as a positive thing since this means all other community triplets are pretty well supported!).

**Comment by JackBoosY** [comment]
I hope some contributors will do this.

**Comment by Zingam** [comment]
What about: manifest mode + prefab generation and consumption + examples and better docs?

**Comment by Cheney-W** [comment]
This issue has not been updated for over 3 months, so if it is still an issue, please reopen the issue.

**Comment by JackBoosY** [comment]
This issue was resolved.

**Comment by Zingam** [comment]
So there is a official Android support now? I need to check this!

**Comment by JackBoosY** [comment]
@Zingam 
- arm-android
- arm64-android
- armv6-android
- x64-android
- x86-android
