### ISSUE TITLE
imgui[docking-experimental,glfw-binding,opengl3-glbinding-binding] version 1.81#1 build failure

### ISSUE THREAD

**Issue by rtoumazet** [microsoft/vcpkg#16276]
**Host Environment**
- OS: Windows
- Compiler: cl.exe (Visual Studio 2019)

**To Reproduce**
`./vcpkg install imgui[docking-experimental,glfw-binding,opengl3-glbinding-binding]`

**Failure logs** 
vcpkg install imgui[docking-experimental,glfw-binding,opengl3-glbinding-binding]
Computing installation plan...
The following packages will be built and installed:
    imgui[core,docking-experimental,glfw-binding,opengl3-glbinding-binding]:x86-windows -> 1.81#1
Detecting compiler hash for triplet x86-windows...
Could not locate cached archive: C:\Users\Runik\AppData\Local\vcpkg\archives\9c\9c737409ab92c71ab19f461e32c97ac14bc96603.zip
Starting package 1/1: imgui:x86-windows
Building package imgui[core,docking-experimental,glfw-binding,opengl3-glbinding-binding]:x86-windows...
-- Note: imgui only supports static library linkage. Building static library.
-- Using cached D:/Dev/Libraries/vcpkg/downloads/ocornut-imgui-682249396f02b8c21e5ff333ab4a1969c89387ad.tar.gz
-- Cleaning sources at D:/Dev/Libraries/vcpkg/buildtrees/imgui/src/69c89387ad-b99c0b72cb.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/Dev/Libraries/vcpkg/downloads/ocornut-imgui-682249396f02b8c21e5ff333ab4a1969c89387ad.tar.gz
-- Using source at D:/Dev/Libraries/vcpkg/buildtrees/imgui/src/69c89387ad-b99c0b72cb.clean
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
    Command failed: ninja -v
    Working Directory: D:/Dev/Libraries/vcpkg/buildtrees/imgui/x86-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\Dev\Libraries\vcpkg\buildtrees\imgui\config-x86-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:319 (vcpkg_execute_required_process)
  ports/imgui/portfile.cmake:64 (vcpkg_configure_cmake)
  scripts/ports.cmake:131 (include)

Error: Building package imgui:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: imgui:x86-windows
  Vcpkg version: 2021-01-13-768d8f95c9e752603d2c5901c7a7c7fbdb08af35

Additionally, attach any relevant sections from the log files above.
[config-x86-windows-out.log](https://github.com/microsoft/vcpkg/files/6002112/config-x86-windows-out.log)

**Additional context**
Tried to copy the missing imgui_tables.cpp to the directory using --editable switch, it fixes this one error but throws a bunch more ... so I reverted back to version 1.79#4 for now.

**Comment by learn-more** [comment]
The problem is that only the 'master' version is updated, not the one with the feature 'docking-experimental'

This is still on an old build (1.79) where the file `imgui_tables.cpp` does not exist yet.

**Comment by BrianPeek** [comment]
> The problem is that only the 'master' version is updated, not the one with the feature 'docking-experimental'
> 
> This is still on an old build (1.79) where the file `imgui_tables.cpp` does not exist yet.

Ah right.  Didn't think to update that as I thought it might be stuck to a particular check-in on purpose.  I can update to the latest commit in that branch which does include the imgui_tables.cpp file if that seems like an appropriate fix?

**Comment by BrianPeek** [comment]
Looks like #16268 will fix this.  Sorry for the breakage!

**Comment by rtoumazet** [comment]
Thanks a lot to everyone involved 👍

**Comment by hiradyazdan** [comment]
Is this issue regressed on v1.89 for vcpkg or there's versioning mismatch/conflict between `vulkan-binding` and `docking-experimental`, since can't build vulkan-binding if only docking-experimental included as well? Same error log as above. However, `install-x64-windows-dbg-out.log` gives this:

```shell
C:\dev\vcpkg\buildtrees\imgui\src\725fcbd0e3-ce3e4747fa.clean\backends\imgui_impl_vulkan.cpp(1684): error C2065: 'VkRenderingAttachmentInfo': undeclared identifier
C:\dev\vcpkg\buildtrees\imgui\src\725fcbd0e3-ce3e4747fa.clean\backends\imgui_impl_vulkan.cpp(1684): error C2146: syntax error: missing ';' before identifier 'attachmentInfo'
C:\dev\vcpkg\buildtrees\imgui\src\725fcbd0e3-ce3e4747fa.clean\backends\imgui_impl_vulkan.cpp(1684): error C2065: 'attachmentInfo': undeclared identifier
C:\dev\vcpkg\buildtrees\imgui\src\725fcbd0e3-ce3e4747fa.clean\backends\imgui_impl_vulkan.cpp(1684): error C3079: an initializer list cannot be used as the right operand of this assignment operator
C:\dev\vcpkg\buildtrees\imgui\src\725fcbd0e3-ce3e4747fa.clean\backends\imgui_impl_vulkan.cpp(1685): error C2065: 'attachmentInfo': undeclared identifier
C:\dev\vcpkg\buildtrees\imgui\src\725fcbd0e3-ce3e4747fa.clean\backends\imgui_impl_vulkan.cpp(1686): error C2065: 'attachmentInfo': undeclared identifier
C:\dev\vcpkg\buildtrees\imgui\src\725fcbd0e3-ce3e4747fa.clean\backends\imgui_impl_vulkan.cpp(1687): error C2065: 'attachmentInfo': undeclared identifier
C:\dev\vcpkg\buildtrees\imgui\src\725fcbd0e3-ce3e4747fa.clean\backends\imgui_impl_vulkan.cpp(1688): error C2065: 'attachmentInfo': undeclared identifier
C:\dev\vcpkg\buildtrees\imgui\src\725fcbd0e3-ce3e4747fa.clean\backends\imgui_impl_vulkan.cpp(1689): error C2065: 'attachmentInfo': undeclared identifier
C:\dev\vcpkg\buildtrees\imgui\src\725fcbd0e3-ce3e4747fa.clean\backends\imgui_impl_vulkan.cpp(1690): error C2065: 'attachmentInfo': undeclared identifier
C:\dev\vcpkg\buildtrees\imgui\src\725fcbd0e3-ce3e4747fa.clean\backends\imgui_impl_vulkan.cpp(1691): error C2065: 'attachmentInfo': undeclared identifier
```
