### ISSUE TITLE
[llvm] default clang resource dir is incorrect

### ISSUE THREAD

**Issue by mcurtis-cadence** [microsoft/vcpkg#16284]
****
Default resource directory for clang is constructed relative to the location of the clang executable:

From `clang/lib/Driver/Driver.cpp`:
```
std::string Driver::GetResourcesPath(StringRef BinaryPath,
                                     StringRef CustomResourceDir) {
...
  // Dir is bin/ or lib/, depending on where BinaryPath is.
  std::string Dir = llvm::sys::path::parent_path(BinaryPath);
...
    P = llvm::sys::path::parent_path(Dir);
    llvm::sys::path::append(P, Twine("lib") + CLANG_LIBDIR_SUFFIX, "clang",
                            CLANG_VERSION_STRING);
...
}
```

Vcpkg moves clang to `tools/llvm` adding a subdirectory. As a result the above code produces `tools/lib/clang/11.0.0` which does not exist. Clang is therefore unable to find header files under `lib/clang/11.0.0`.

From `clang/lib/Driver/ToolChains/Clang.cpp`:

```
  // Pass the path to compiler resource files.
  CmdArgs.push_back("-resource-dir");
  CmdArgs.push_back(D.ResourceDir.c_str());
```

I have worked around the problem by adding this to my `ports/llvm/portfile.cmake`

```
list(APPEND FEATURE_OPTIONS
     -DCLANG_RESOURCE_DIR=../../lib/clang/11.0.0
)
```

**Comment by JackBoosY** [comment]
Thanks for reporting this issue!
