### ISSUE TITLE
Error: Building package openssl:x64-uwp failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by ian-wevr** [Microsoft/vcpkg#1628]
Performed "vcpkg update", then "vcpkg --triplet x64-uwp install openssl".
Please see the attached logs. Let me know if there's any more information I can provide.

[make-openssl-x64-uwp-err.log.txt](https://github.com/Microsoft/vcpkg/files/1216307/make-openssl-x64-uwp-err.log.txt)
[make-openssl-x64-uwp-out.log.txt](https://github.com/Microsoft/vcpkg/files/1216308/make-openssl-x64-uwp-out.log.txt)

**Comment by ras0219-msft** [comment]
Hi @ian-wevr, thanks for posting your issue and sorry for the delay!

We've seen this issue before with certain versions of the Windows SDK. Could you update to the latest Vcpkg version, then run `.\scripts\getWindowsSDK.ps1 -verbose` and post the results?

**Comment by ian-wevr** [comment]
> sorry for the delay!

All good, vcpkg has already saved me hours of time, so if I have to muddle through the builds for a few projects by hand I still come out ahead!

> Could you update to the latest Vcpkg version, then run .\scripts\getWindowsSDK.ps1 -verbose and post the results?

10.0.16257.0

However, when I originally posted this I believe I was using Creator's Update (15063) SDK -- not 100% positive, but it was definitely a release version SDK. I was also using Visual Studio 15.2 and build tools 15.2 should that matter.

I just reran (this time with SDK 16257) "vcpkg --triplet x64-uwp install openssl" and it fails with the same outwardly symptoms -- here's a fresh copy of the logs in case they're different.

Also:
> Please ensure you're using the latest portfiles with `.\vcpkg update`, then
> submit an issue at https://github.com/Microsoft/vcpkg/issues including:
>  Package: openssl:x64-uwp
>  Vcpkg version: 0.0.84-3c34cca36adfce1d3388b30e643294be58b3ec8f

[make-openssl-x64-uwp-out.log.txt](https://github.com/Microsoft/vcpkg/files/1247499/make-openssl-x64-uwp-out.log.txt)
[make-openssl-x64-uwp-err.log.txt](https://github.com/Microsoft/vcpkg/files/1247500/make-openssl-x64-uwp-err.log.txt)

**Comment by ras0219-msft** [comment]
Ok, I've pushed some changes in 1081778b which _might_ improve this situation[1]. Basically, instead of hardcoding a fixed number of versions, we'll just add the available ones, which should handle SDK upgrades much better in the future.

Could you pull this version and try once again? You shouldn't need to re-bootstrap vcpkg.

[1] https://github.com/Microsoft/vcpkg/blob/1081778b849da6c6412379b50ca66d049228c1e7/ports/openssl/make-openssl.bat#L5-L6

**Comment by ian-wevr** [comment]
Great, looks like it works!

**Comment by JackBoosY** [comment]
Hi @ian-wevr , thanks for reporting this issue!
Please open a new issue if this is still a problem for you.
Thx.
