### ISSUE TITLE
Unable to install libgpg-error

### ISSUE THREAD

**Issue by folklore212** [microsoft/vcpkg#16292]
**Host Environment**
- OS: Windows 10
- Compiler: libgpg-error[core]:x86-windows -> 1.39

**To Reproduce**
`vcpkg install libgcrypt`
`vcpkg install libgpg-error`

**Failure logs** 
  Package: libgpg-error:x86-windows
  Vcpkg version: 2021-01-13-768d8f95c9e752603d2c5901c7a7c7fbdb08af35

**Additional context**
Computing installation plan...
The following packages will be built and installed:
    libgpg-error[core]:x86-windows -> 1.39
Detecting compiler hash for triplet x86-windows...
Could not locate cached archive: xxxxxxxxxxxxxxxxxxxxxxxxx.zip
Starting package 1/1: libgpg-error:x86-windows
Building package libgpg-error[core]:x86-windows...
CMake Error at scripts/cmake/vcpkg_fail_port_install.cmake:97 (message):
  libgpg-error currently only supports unix platform
  Target 'Windows' not supported by libgpg-error!
Call Stack (most recent call first):
  ports/libgpg-error/portfile.cmake:1 (vcpkg_fail_port_install)
  scripts/ports.cmake:131 (include)

Error: Building package libgpg-error:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libgpg-error:x86-windows
  Vcpkg version: 2021-01-13-768d8f95c9e752603d2c5901c7a7c7fbdb08af35

**Comment by JackBoosY** [comment]
```
libgpg-error currently only supports unix platform
Target 'Windows' not supported by libgpg-error!
```

**Comment by sfhacker** [comment]
@tangying212 Have you contacted us before?
Just built libgpg-error from source on Windows 10 x64. No issues at all.

![image](https://user-images.githubusercontent.com/25817529/115970093-ac015780-a583-11eb-9777-9863f92551f9.png)

**Comment by JackBoosY** [comment]
Please keep this issue open until we support Windows.

**Comment by tangying212** [comment]
> Please keep this issue open until we support Windows.

Ok

**Comment by dg0yt** [comment]
Port libgpg-error supports windows since #16932, 2021-06.

**Comment by dg0yt** [comment]
#27668 will remove the windows support from port `libgpg-error` and add port `shiftmedia-libgpg-error` instead.
Port `libgcrypt` doesn't support windows, but already has as `shiftmedia-libgcrypt` counter part.
(Shiftmedia Project (aka SMP) is an unofficial fork.)

**Comment by dg0yt** [comment]
This issue is obsolete. There is `shiftmedia-libgpg-error` for MSVC.
