### ISSUE TITLE
How do I use features in manifest mode?

### ISSUE THREAD

**Issue by cenit** [microsoft/vcpkg#16297]
Let's suppose that I have a personal project with a vcpkg.json in the root folder.
I am building the project right now with CMake and the manifest mode is correctly auto-enabled and it works.

I know that I can also install project dependencies with

```
${VCPKG_ROOT}/vcpkg --feature-flags=manifests install 
```

from inside the root folder of my project, and it works ok, installing dependencies. But it does not trigger the project build afterwards so I almost never use it.

I'd like to add features to my project, like those that we have in ports, being able to enable/disable parts of it depending on my personal choice. How should I tell vcpkg which features to build, in my project's CMakeLists.txt or in command line above? If I use --x-feature=featureName on the command line, with featureName defined in the vcpkg.json, it just install dependencies related to that feature, but the build is not triggered in any special way. 
In another words, how should I integrate my project as a "dynamic port"?

or, again: would it be wrong to think about exposing through features a cmake variable, in order to infer from inside cmakelists.txt, if the feature is enabled or disabled during building?

**Comment by strega-nil** [comment]
They are in fact already exposed! `VCPKG_MANIFEST_FEATURES` is a list variable that you can set to set the set of features which are set :3

Additionally, for default features, you can turn those off with `VCPKG_MANIFEST_NO_DEFAULT_FEATURES`.

**Comment by PhoebeHui** [comment]
Also see relate docs https://github.com/microsoft/vcpkg/blob/master/docs/users/manifests.md, please reopen this issue if it still be a question for you.
