### ISSUE TITLE
How to use with CMake on MacOS

### ISSUE THREAD

**Issue by cdcseacave** [microsoft/vcpkg#16306]
On MacBook Air M1 trying:
```
cmake .. -DCMAKE_TOOLCHAIN_FILE=/Users/user/vcpkg/scripts/buildsystems/vcpkg.cmake -G "Unix Makefiles"
```
but I get this error:
```
Unable to determine target architecture, continuing without vcpkg
```
I tried adding also:
```
-DVCPKG_DEFAULT_TRIPLET=arm64-osx
```
but with no luck

**Comment by JackBoosY** [comment]
I suggest you can not use the -G option, the default generator is makefile.

**Comment by cdcseacave** [comment]
not using `-G` option does not change anything

**Comment by JackBoosY** [comment]
@strega-nil Can you please take a look?

Thanks.

**Comment by strega-nil** [comment]
hrm. @cdcseacave could you post the result of:

```
message(STATUS "${CMAKE_HOST_SYSTEM_PROCESSOR}")
```

**Comment by cdcseacave** [comment]
the result is:
```
arm64
```
which is correct.

I found a way to make it work with a hack to `vcpkg.cmake` by adding around the if at line 341 `if(VCPKG_TARGET_TRIPLET)` these lines:
```
set(CPY_CMAKE_GENERATOR_PLATFORM ${CMAKE_GENERATOR_PLATFORM})
set(CMAKE_GENERATOR_PLATFORM "arm64")
..................
set(CMAKE_GENERATOR_PLATFORM ${CPY_CMAKE_GENERATOR_PLATFORM})
```
[vcpkg.zip](https://github.com/microsoft/vcpkg/files/6024271/vcpkg.zip)

**Comment by JackBoosY** [comment]
I suddenly remembered that MacBook recently switched from x64 to arm64 platform.

**Comment by cdcseacave** [comment]
Just a note: MacBook  did not switched entirely to arm64, there are still x64 MacBooks produced

Additionally both x64 and arm64 can be compiled on both versions of native platforms

**Comment by FrankXie05** [comment]
vcpkg has now added confirmation for `arm64` architecture by PR #18112

**Comment by Cheney-W** [comment]
Thanks for posting this issue. Please reopen this issue if it still be a problem for you.

**Comment by jcs090218** [comment]
I've issue similar to this using GitHub Actions, see the log https://github.com/jayces-lang/jayces/actions/runs/7321648566/job/19942284291#step:6:15. I've the same settings on all platforms (Windows, Linux, macOS), but only the macOS failed to generate the build project. Any idea? 🤔

**Comment by JackBoosY** [comment]
> I've issue similar to this using GitHub Actions, see the log https://github.com/jayces-lang/jayces/actions/runs/7321648566/job/19942284291#step:6:15. I've the same settings on all platforms (Windows, Linux, macOS), but only the macOS failed to generate the build project. Any idea? 🤔

`cmake -S . -B build/ninja/ -GNinja` doesn't contains vcpkg toolchain.

**Comment by jcs090218** [comment]
Thank you for the response! 👍 The solution is in https://github.com/microsoft/vcpkg/discussions/35869.
