### ISSUE TITLE
Use the binary cache for tools

### ISSUE THREAD

**Issue by Chronial** [microsoft/vcpkg#16300]
With the new binary cache feature, if vcpkg is integrated into a stable build pipeline, vcpkg can resolve all dependencies without internet access. That is a very useful for the following reasons:
* Build speed
* Resistance against internet outages
* Building old states of a software for which external references might be gone

But there is currently one exception to this: The [tools required by vcpkg](https://github.com/microsoft/vcpkg/blob/master/scripts/vcpkgTools.xml). I would propose that vcpkg could also have an option for storing the downloaded tools in the binary cache, so following installations have less internet dependencies.

**Comment by StarGate-One** [comment]
Would vcpkg need to cache all the variations of the [MSYS2 tools](https://github.com/microsoft/vcpkg/blob/master/scripts/cmake/vcpkg_acquire_msys.cmake) used also?

**Comment by ras0219** [comment]
Great suggestion!

Our current work towards that is here: https://github.com/microsoft/vcpkg-tool/pull/10

However, it _currently_ is a separate system than binary caching. We're actively developing it, so this may change in the future.

**Comment by Chronial** [comment]
@ras0219 That looks great and would definitely address our issue.

Using the binary cache is definitely not a requirement. Setting a second path is obviously no problem and IMO also makes more sense: I might want to clear the binary cache for a variety of toolchain related reasons. The only reason why I would ever want to clear the mirror is to safe disk-space.

**Comment by NancyLi1013** [comment]
@Chronial 

Could you please help confirm if the feature `X_VCPKG_ASSET_SOURCES` can meet your demands?  You can refer to [this ](https://github.com/microsoft/vcpkg/blob/master/docs/users/assetcaching.md)doc to know more about this feature.

**Comment by Chronial** [comment]
The doc you linked to makes no explicit mention of the tools used by vcpkg, but I assume they fall under the umbrella term of "assets"?

As far as I understand that documentation, vcpkg only supports using a azure blob storage as storage location? No local folders, no network shares? If that is the case than X_VCPKG_ASSET_SOURCES does not really meet my demands. Of the three goals listed in my first post, only the last one seems to be covered by the current implementation.

**Comment by autoantwort** [comment]
You can also use network shares: https://github.com/microsoft/vcpkg/blob/master/docs/users/assetcaching.md#x-azurl

I think this issue can be closed.
