### ISSUE TITLE
[glslang] Update to 11.1.0

### ISSUE THREAD

**Issue by axsaucedo** [microsoft/vcpkg#16305]
**Describe the bug**
Currently the KhrosnoGroup/glslang seems to have released a build that does not seem to align with the current official tags of the repository https://github.com/KhronosGroup/glslang - example would include official versions such as `11.1.0`, `11.0.0`, etc.

**Environment**
- OS: All OS
- Compiler: revision

**To Reproduce**
Install any package of glslang

**Expected behavior**
The stable tags being used instead

**Failure logs** 
N/A

**Additional context**
N/A

**Comment by NancyLi1013** [comment]
Hi @axsaucedo 

Thanks for posting this issue.

I think you mean we should update `glslang` to a stable version, such as 11.0.0 or 11.1.1 instead of stable branch.

**Comment by axsaucedo** [comment]
Oh thank  you for the heads up - it seems I had the title wrong, but the description does outline the correct points, yes it would be to update glslang to a stable version. The main reason is also because the Include locations differ quite significantly between 11.1 and master, so there are too many breaking changes for it to be the main one to use.

I have also opened an issue in KhronosGroup/glslang confirming that 11.1.0 is the correct version to use https://github.com/KhronosGroup/glslang/issues/2539

**Comment by NancyLi1013** [comment]
Thanks for your clarification. I will try to update it to the latest stable version and check if it can work fine.

**Comment by axsaucedo** [comment]
Great, thank you @NancyLi1013, let me know once successful and I can also confirm that it works as expected as I have a project that currently integrates with glslang 11.1.0

**Comment by NancyLi1013** [comment]
@axsaucedo 

I noticed that there was another issue #15498 that requested to update `glslang` to 11.1.0.

So let's track this issue there. The related PR #15719.
