### ISSUE TITLE
[fribidi] build failure

### ISSUE THREAD

**Issue by Wedge009** [microsoft/vcpkg#16314]
**Host Environment**
- OS: Windows 7
- Compiler: Visual Studio v16.8.5 / C++ v19.28.29337

**To Reproduce**
`./vcpkg install fribidi:x64-windows`

**Failure logs** 
```
-- Using cached D:/git/vcpkg/downloads/fribidi-fribidi-5464c284034da9c058269377b7f5013bb089f553.tar.gz
-- Cleaning sources at D:/git/vcpkg/buildtrees/fribidi/src/3bb089f553-744296bd76.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/git/vcpkg/downloads/fribidi-fribidi-5464c284034da9c058269377b7f5013bb089f553.tar.gz
-- Using source at D:/git/vcpkg/buildtrees/fribidi/src/3bb089f553-744296bd76.clean
-- Configuring x64-windows
-- Using msys root at D:/git/vcpkg/downloads/tools/msys2/50864d9fae363d6e
-- Configuring x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
    Command failed: D:/git/vcpkg/downloads/tools/python/python-3.9.0-x64/python.exe D:/git/vcpkg/downloads/tools/meson/meson-f5871f434a5b768ad9fcafa797a6db0286421842/meson.py -Ddocs=false -Dbin=false -Dtests=false --buildtype plain --backend ninja --wrap-mode nodownload --native D:/git/vcpkg/buildtrees/fribidi/meson-nativ-x64-windows.log --default-library shared --libdir lib --native D:/git/vcpkg/buildtrees/fribidi/meson-nativ-x64-windows-debug.log -Ddebug=true --prefix D:/git/vcpkg/packages/fribidi_x64-windows/debug --includedir ../include -Dcmake_prefix_path=['D:/git/vcpkg/installed/x64-windows/debug','D:/git/vcpkg/installed/x64-windows','D:/git/vcpkg/installed/x64-windows/share'] D:/git/vcpkg/buildtrees/fribidi/src/3bb089f553-744296bd76.clean
    Working Directory: D:/git/vcpkg/buildtrees/fribidi/x64-windows-dbg
    Error code: Exit code 0xc0000135

  

    See logs for more information:

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_meson.cmake:482 (vcpkg_execute_required_process)
  ports/fribidi/portfile.cmake:9 (vcpkg_configure_meson)
  scripts/ports.cmake:133 (include)


Error: Building package fribidi:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: fribidi:x64-windows
  Vcpkg version: 2021-01-13-768d8f95c9e752603d2c5901c7a7c7fbdb08af35

```
**Additional context**
I could not find any other reports specific to `fribidi` on Windows - other issues referred to Linux and Meson.

Pretty sure when I last used vcpkg (October 2019 according to the logs) fribidi compilation worked just fine.

All I can see from the logs is that a Python call appears to have failed for some reason.

**Comment by Wedge009** [comment]
Attempting to run the Python command manually results in the dialogue:
> The program can't start because api-ms-win-core-path-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem.

I'm assuming this is an expected DLL on Windows 10. Is there any work-around for Windows 7?

**Comment by Hoikas** [comment]
@Wedge009 Unfortunately, Python has dropped support for Windows 7.

**Comment by Wedge009** [comment]
I see, thank you for the quick response.

**Comment by thangpn24** [comment]
I got the same error on win11
-- Package x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: "C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" install -v
    Working Directory: C:/Tools/Works/Test/Open_source/vcpkg-master/buildtrees/fribidi/x64-windows-dbg
    Error code: 1
    See logs for more information:
      C:\Tools\Works\Test\Open_source\vcpkg-master\buildtrees\fribidi\package-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-tool-meson/vcpkg_install_meson.cmake:33 (vcpkg_execute_required_process)
  ports/fribidi/portfile.cmake:28 (vcpkg_install_meson)
  scripts/ports.cmake:203 (include)


error: building fribidi:x64-windows failed with: BUILD_FAILED
See https://learn.microsoft.com/vcpkg/troubleshoot/build-failures?WT.mc_id=vcpkg_inproduct_cli for more information.
Elapsed time to handle fribidi:x64-windows: 1.5 min
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+fribidi
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[fribidi]+Build+error+on+x64-windows&body=Copy%20issue%20body%20from%20C%3A%2FTools%2FWorks%2FTest%2FOpen_source%2Fvcpkg-master%2Finstalled%2Fvcpkg%2Fissue_body.md
