### ISSUE TITLE
[New Port Request] <LibTorch>

### ISSUE THREAD

**Issue by Allan-Yoriichi** [microsoft/vcpkg#16319]
Library name: LibTorch

Library description: The Pytorch C++ API

Source repository URL: 
https://download.pytorch.org/libtorch/cu102/libtorch-win-shared-with-deps-1.7.1.zip
https://download.pytorch.org/libtorch/cu102/libtorch-win-shared-with-deps-debug-1.7.1.zip

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by luncliff** [comment]
### Related Issues
* #16319
* #15763
* #6345 #5209

**Comment by LilyWangLL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
