### ISSUE TITLE
Error: Building package libepoxy:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by t-sharp** [Microsoft/vcpkg#1631]
I performed ".\vcpkg update" and then ".\vcpkg install gtk". The output was:

>The following packages will be built and installed:
>    gtk:x86-windows
>  \* libepoxy:x86-windows
>Additional packages (*) will be installed to complete this operation.
>Building package libepoxy:x86-windows...
>-- CURRENT_INSTALLED_DIR=C:/Program Files (x86)/vcpkg/vcpkg/installed/x86-windows
>-- DOWNLOADS=C:/Program Files (x86)/vcpkg/vcpkg/downloads
>-- CURRENT_PACKAGES_DIR=C:/Program Files (x86)/vcpkg/vcpkg/packages/libepoxy_x86-windows
>-- CURRENT_BUILDTREES_DIR=C:/Program Files (x86)/vcpkg/vcpkg/buildtrees/libepoxy
>-- CURRENT_PORT_DIR=C:/Program Files (x86)/vcpkg/vcpkg/ports/libepoxy/.
>-- Using cached C:/Program Files (x86)/vcpkg/vcpkg/downloads/anholt-libepoxy-1.4.3.tar.gz
>-- Testing integrity of cached file...
>-- Testing integrity of cached file... OK
>-- Extracting done
>-- Configuring x86-windows-rel
>CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:43 (message):
>    Command failed: C:/Program Files (x86)/vcpkg/vcpkg/downloads/tools/python/python.exe;C:/Program Files (x86)/vcpkg/vcpkg/downloads/tools/meson/meson-0.40.1/meson.py;-Denable-glx=no;-Denable-egl=no;--buildtype;plain;--backend;ninja;--default-library;shared;--prefix;C:/Program Files (x86)/vcpkg/vcpkg/packages/libepoxy_x86-windows;C:/Program Files (x86)/vcpkg/vcpkg/buildtrees/libepoxy/src/libepoxy-1.4.3
>    Working Directory: C:/Program Files (x86)/vcpkg/vcpkg/buildtrees/libepoxy/x86-windows-rel
>    See logs for more information:
>      C:\Program Files (x86)\vcpkg\vcpkg\buildtrees\libepoxy\config-x86-windows-rel-out.log
>      C:\Program Files (x86)\vcpkg\vcpkg\buildtrees\libepoxy\config-x86-windows-rel-err.log
>
>Call Stack (most recent call first):
>  scripts/cmake/vcpkg_configure_meson.cmake:51 (vcpkg_execute_required_process)
>  ports/libepoxy/portfile.cmake:14 (vcpkg_configure_meson)
>  scripts/ports.cmake:72 (include)
>
>
>Error: Building package libepoxy:x86-windows failed with: BUILD_FAILED
>Please ensure you're using the latest portfiles with `.\vcpkg update`, then
>submit an issue at https://github.com/Microsoft/vcpkg/issues including:
>  Package: libepoxy:x86-windows
>  Vcpkg version: 0.0.82-f2c655c7dfa02fe0fcca4a6207f3f1cc55da540c
>
>Additionally, attach any relevant sections from the log files above.

Please see the attached logs. Let me know if there's any more information I can provide.
[config-x86-windows-rel-err.log.txt](https://github.com/Microsoft/vcpkg/files/1217165/config-x86-windows-rel-err.log.txt)
[config-x86-windows-rel-out.log.txt](https://github.com/Microsoft/vcpkg/files/1217166/config-x86-windows-rel-out.log.txt)

**Comment by ras0219-msft** [comment]
Hi @t-sharp, thanks for posting your issue and sorry for the delay!

This is probably due to the codepage handling regression in CMake 3.9.0 (#1660). Could you try running `chcp 65001` in your console before invoking Vcpkg?

**Comment by t-sharp** [comment]
Hello @ras0219-msft, your suggestion was to run `chcp 65001` before invoking Vcpkg and your suggestion worked. I successfully built gtk. Thank you for your help. Have a nice day!

**Comment by alexkaratarakis** [comment]
Please report if the latest master fixes things for you.

**Comment by t-sharp** [comment]
Hello @alexkaratarakis, yes; the latest master fixed this issue for me. Thank you and have a nice weekend.
