### ISSUE TITLE
python3:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by DanielLiamAnderson** [microsoft/vcpkg#16311]
**Host Environment**
- OS: Windows 10 Education, Build 18363
- Compiler: MSVC 19.25.28614.0

**To Reproduce**
`./vcpkg install python3`

**Failure logs** 

Console output:

```
-- Building PCbuild/pcbuild.proj for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
Command failed: msbuild C:/dev/vcpkg/buildtrees/python3/x86-windows-rel/v3.9.0-664bf2a259.clean/PCbuild/pcbuild.proj /p:Configuration=Release /p:IncludeExtensions=true /p:IncludeExternals=true /p:IncludeCTypes=true /p:IncludeSSL=true /p:IncludeTkinter=false /p:IncludeTests=false /p:ForceImportBeforeCppTargets=C:/dev/vcpkg/buildtrees/python3/src/v3.9.0-664bf2a259.clean/PCbuild/python_vcpkg.props /p:IncludeUwp=false /p:_VcpkgPythonLinkage=DynamicLibrary /t:Rebuild /p:Platform=Win32 /p:PlatformToolset=v142 /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /p:WindowsTargetPlatformVersion=10.0.18362.0 /p:VcpkgTriplet=x86-windows /p:VcpkgInstalledDir=C:/dev/vcpkg/installed /p:VcpkgManifestInstall=false /m
Working Directory: C:/dev/vcpkg/buildtrees/python3/x86-windows-rel/v3.9.0-664bf2a259.clean
Error code: 1
See logs for more information:
C:\dev\vcpkg\buildtrees\python3\build-x86-windows-rel-out.log
Call Stack (most recent call first):
scripts/cmake/vcpkg_install_msbuild.cmake:165 (vcpkg_execute_required_process)
ports/python3/portfile.cmake:101 (vcpkg_install_msbuild)
scripts/ports.cmake:133 (include)
```

The final section of build-x86-windows-rel-out.log:

```
"C:\dev\vcpkg\buildtrees\python3\x86-windows-rel\v3.9.0-664bf2a259.clean\PCbuild\pcbuild.proj" (Rebuild target) (1) ->
       "C:\dev\vcpkg\buildtrees\python3\x86-windows-rel\v3.9.0-664bf2a259.clean\PCbuild\_freeze_importlib.vcxproj" (Build target) (2:2) ->
       (_RebuildImportLib target) -> 
         C:\dev\vcpkg\buildtrees\python3\x86-windows-rel\v3.9.0-664bf2a259.clean\PCbuild\_freeze_importlib.vcxproj(131,5): error MSB3073: The command ""C:\dev\vcpkg\buildtrees\python3\x86-windows-rel\v3.9.0-664bf2a259.clean\PCbuild\win32\_freeze_importlib.exe" "importlib._bootstrap" "C:\dev\vcpkg\buildtrees\python3\x86-windows-rel\v3.9.0-664bf2a259.clean\Lib\importlib\_bootstrap.py" "C:\dev\vcpkg\buildtrees\python3\x86-windows-rel\v3.9.0-664bf2a259.clean\PCbuild\obj\39win32_Release\_freeze_importlib\importlib.g.h"" exited with code -1073741515.
```

The full log is attached.
[build-x86-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/6013609/build-x86-windows-rel-out.log)

**Comment by DanielLiamAnderson** [comment]
Funnily enough, it looks like the exact same issue was submitted while I was typing mine out, just 15 minutes earlier: https://github.com/microsoft/vcpkg/issues/16310

**Comment by Hoikas** [comment]
#16310 is describing expected behavior though. Python 3.9 does not work on Windows 7, but you're on Windows 10 😕.

**Comment by JackBoosY** [comment]
The error code is `0xC0000135`, [docs](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/596a1078-e883-4972-9bbc-49e60bebca55) shows us:
```
{Unable To Locate Component} This application has failed to start because %hs was not found. Reinstalling the application might fix this problem.
```
Can you please manually run command `"C:\dev\vcpkg\buildtrees\python3\x86-windows-rel\v3.9.0-664bf2a259.clean\PCbuild\win32\_freeze_importlib.exe" "importlib._bootstrap" "C:\dev\vcpkg\buildtrees\python3\x86-windows-rel\v3.9.0-664bf2a259.clean\Lib\importlib\_bootstrap.py" "C:\dev\vcpkg\buildtrees\python3\x86-windows-rel\v3.9.0-664bf2a259.clean\PCbuild\obj\39win32_Release\_freeze_importlib\importlib.g.h"` in cmd?

Thanks.

**Comment by DanielLiamAnderson** [comment]
The output is attached.
![error](https://user-images.githubusercontent.com/20237923/108769562-27646f80-7527-11eb-81cf-534588439fe0.png)

**Comment by JackBoosY** [comment]
Please close your anti-virus and rebuild again.

**Comment by chuyanjuncn** [comment]
I got a failure when I am using windows 10 VS2015 with update3 to build Python 3.9. X86.

Following is the console information:
 F:\vcpkg-master> .\vcpkg install python3:x86-windows
Computing installation plan...
The following packages will be built and installed:
    python3[core]:x86-windows -> 3.9.0#1
Detecting compiler hash for triplet x86-windows...
Could not locate cached archive: C:\Users\chuyj\AppData\Local\vcpkg\archives\34\346a4ccfc609e735db0d22580f0dcc223e397208.zip
Starting package 1/1: python3:x86-windows
Building package python3[core]:x86-windows...
-- Using cached F:/vcpkg-master/downloads/python-cpython-v3.9.0.tar.gz
-- Cleaning sources at F:/vcpkg-master/buildtrees/python3/src/v3.9.0-664bf2a259.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source F:/vcpkg-master/downloads/python-cpython-v3.9.0.tar.gz
-- Applying patch 0002-use-vcpkg-zlib.patch
-- Applying patch 0003-devendor-external-dependencies.patch
-- Applying patch 0004-dont-copy-vcruntime.patch
-- Applying patch 0005-only-build-required-projects.patch
-- Applying patch 0006-fix-duplicate-symbols.patch
-- Using source at F:/vcpkg-master/buildtrees/python3/src/v3.9.0-664bf2a259.clean
-- Building PCbuild/pcbuild.proj for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:108 (message):
    Command failed: msbuild F:/vcpkg-master/buildtrees/python3/x86-windows-rel/v3.9.0-664bf2a259.clean/PCbuild/pcbuild.proj /p:Configuration=Release /p:IncludeExtensions=true /p:IncludeExternals=true /p:IncludeCTypes=true /p:IncludeSSL=true /p:IncludeTkinter=false /p:IncludeTests=false /p:ForceImportBeforeCppTargets=F:/vcpkg-master/buildtrees/python3/src/v3.9.0-664bf2a259.clean/PCbuild/python_vcpkg.props /p:IncludeUwp=false /p:_VcpkgPythonLinkage=DynamicLibrary /t:Rebuild /p:Platform=Win32 /p:PlatformToolset=v140 /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /p:WindowsTargetPlatformVersion= /p:VcpkgTriplet=x86-windows /p:VcpkgCurrentInstalledDir=F:/vcpkg-master/installed/x86-windows /p:VcpkgManifestInstall=false /m
    Working Directory: F:/vcpkg-master/buildtrees/python3/x86-windows-rel/v3.9.0-664bf2a259.clean
    Error code: 1
    See logs for more information:
      F:\vcpkg-master\buildtrees\python3\build-x86-windows-rel-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_msbuild.cmake:165 (vcpkg_execute_required_process)
  ports/python3/portfile.cmake:101 (vcpkg_install_msbuild)
  scripts/ports.cmake:136 (include)

Error: Building package python3:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: python3:x86-windows
  Vcpkg version: 2020.11.12-nohash

And the attachment is the log file. 
[Uploading build-x86-windows-rel-out.log…]()

**Comment by JackBoosY** [comment]
@chuyanjuncn Can you please try to use Visual Studio 2017 to build python3?

**Comment by joe-ieta** [comment]
@chuyanjuncn  windows 10 with Visual Studio 2019 works fine.

**Comment by rrozema** [comment]
I think this is caused by a buffer overrun in _freeze_importlib.c: The build log reports a weird return value -1073741515 when executing _freeze_importlib.exe, whereas the code only returns 0, 1 or 2.

       "C:\github\rrozema\domoticz\msbuild\vcpkg\buildtrees\python3\x86-windows-rel\v3.9.2-cc9ebdcfd9\PCbuild\_freeze_importlib.vcxproj" (Build target) (2:2) ->
       (_RebuildImportLib target) -> 
         C:\github\rrozema\domoticz\msbuild\vcpkg\buildtrees\python3\x86-windows-rel\v3.9.2-cc9ebdcfd9\PCbuild\_freeze_importlib.vcxproj(131,5): error MSB3073: The command ""C:\github\rrozema\domoticz\msbuild\vcpkg\buildtrees\python3\x86-windows-rel\v3.9.2-cc9ebdcfd9\PCbuild\win32\_freeze_importlib.exe" "importlib._bootstrap" "C:\github\rrozema\domoticz\msbuild\vcpkg\buildtrees\python3\x86-windows-rel\v3.9.2-cc9ebdcfd9\Lib\importlib\_bootstrap.py" "C:\github\rrozema\domoticz\msbuild\vcpkg\buildtrees\python3\x86-windows-rel\v3.9.2-cc9ebdcfd9\PCbuild\obj\39win32_Release\_freeze_importlib\importlib.g.h"" exited with code -1073741515.

The reason is probably line 37 " char buf[100];" is too small when the files are stored in deeper folder structures and/or longer folder names. I suggest to cahneg line 37 to " char buf[513];", plus change line 102 into "snprintf(buf, 513, "<frozen %s>", name);". I have not been able to verify this.

**Comment by JackBoosY** [comment]
@rrozema  According to your message, I think this is a upstream bug.
I will report it later.

**Comment by tonygould** [comment]
> I think this is caused by a buffer overrun in _freeze_importlib.c

thanks, we tried your fix as a patch prior in the vcpkg build but it didn't help. Upgrading from win 7 to win 10 did fix the problem though. (We're on vs2019)

**Comment by JackBoosY** [comment]
The reason for `0xC0000135` is the lack of dependent dynamic libraries.
`_freeze_importlib.exe` depends on `python39.dll`, please check whether the library is in the executable directory at the same level.

**Comment by JonLiu1993** [comment]
@DanielLiamAnderson ,Could you check whether the library is in the executable directory at the same level?

**Comment by JonLiu1993** [comment]
@DanielLiamAnderson ,I've never been able to repro this issue
````
Building package python3[core]:x86-windows...
-- Using cached python-cpython-v3.10.1.tar.gz.
-- Extracting source F:/test9/vcpkg/downloads/python-cpython-v3.10.1.tar.gz
-- Applying patch 0002-use-vcpkg-zlib.patch
-- Applying patch 0003-devendor-external-dependencies.patch
-- Applying patch 0004-dont-copy-vcruntime.patch
-- Applying patch 0005-only-build-required-projects.patch
-- Applying patch 0008-fix-parallel-install.patch
-- Applying patch 0009-python-embed.pc.patch
-- Using source at F:/test9/vcpkg/buildtrees/python3/src/v3.10.1-8497f83e7f
-- Building PCbuild/pcbuild.proj for Release
-- Building PCbuild/pcbuild.proj for Debug
-- Installing: F:/test9/vcpkg/packages/python3_x86-windows/share/python3/copyright
-- Fixing pkgconfig file: F:/test9/vcpkg/packages/python3_x86-windows/lib/pkgconfig/python-3.10-embed.pc
-- Fixing pkgconfig file: F:/test9/vcpkg/packages/python3_x86-windows/lib/pkgconfig/python-3.10.pc
-- Using cached msys-mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst.
-- Using msys root at F:/test9/vcpkg/downloads/tools/msys2/aa5af7b2aa7e90e8
-- Fixing pkgconfig file: F:/test9/vcpkg/packages/python3_x86-windows/debug/lib/pkgconfig/python-3.10-embed.pc
-- Fixing pkgconfig file: F:/test9/vcpkg/packages/python3_x86-windows/debug/lib/pkgconfig/python-3.10.pc
-- Installing: F:/test9/vcpkg/packages/python3_x86-windows/share/python3/usage
-- Installing cmake wrappers
-- Performing post-build validation
-- Performing post-build validation done
Installing package python3[core]:x86-windows...
Elapsed time for package python3:x86-windows: 4.538 min

Total elapsed time: 20.04 min

The package python3 is compatible with built-in CMake targets:

    find_package(Python3 COMPONENTS Development REQUIRED)
    target_link_libraries(main PRIVATE Python3::Python)
````

**Comment by FrankXie05** [comment]
@DanielLiamAnderson , I have not reproduced locally, please make sure you are using the latest vcpkg, if the problem still exists, please reopen. :)
