### ISSUE TITLE
[python3] failure on Windows 7 

### ISSUE THREAD

**Issue by WooXZerah** [microsoft/vcpkg#16310]
**Host Environment**
- OS: Windows 7
- Compiler: Visual Studio Community 2019

**To Reproduce**
`.\\vcpkg install python3:x64-windows`

**Failure logs** 
`Building package python3[core]:x64-windows...
-- Using cached C:/Users/Leo/vcpkg/downloads/python-cpython-v3.9.0.tar.gz
-- Cleaning sources at C:/Users/Leo/vcpkg/buildtrees/python3/src/v3.9.0-664bf2a259.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/Leo/vcpkg/downloads/python-cpython-v3.9.0.tar.gz
-- Applying patch 0002-use-vcpkg-zlib.patch
-- Applying patch 0003-devendor-external-dependencies.patch
-- Applying patch 0004-dont-copy-vcruntime.patch
-- Applying patch 0005-only-build-required-projects.patch
-- Applying patch 0006-fix-duplicate-symbols.patch
-- Using source at C:/Users/Leo/vcpkg/buildtrees/python3/src/v3.9.0-664bf2a259.clean
-- Building PCbuild/pcbuild.proj for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
    Command failed: msbuild C:/Users/Leo/vcpkg/buildtrees/python3/x64-windows-rel/v3.9.0-664bf2a259.clean/PCbuild/pcbuild.proj /p:Configuration=Release /p:IncludeExtensions=true /p:IncludeExternals=true /p:IncludeCTypes=true /p:IncludeSSL=true /p:IncludeTkinter=false /p:IncludeTests=false /p:ForceImportBeforeCppTargets=C:/Users/Leo/vcpkg/buildtrees/python3/src/v3.9.0-664bf2a259.clean/PCbuild/python_vcpkg.props /p:IncludeUwp=false /p:_VcpkgPythonLinkage=DynamicLibrary /t:Rebuild /p:Platform=x64 /p:PlatformToolset=v142 /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /p:WindowsTargetPlatformVersion=10.0.18362.0 /p:VcpkgTriplet=x64-windows /p:VcpkgInstalledDir=C:/Users/Leo/vcpkg/installed /p:VcpkgManifestInstall=false /m
    Working Directory: C:/Users/Leo/vcpkg/buildtrees/python3/x64-windows-rel/v3.9.0-664bf2a259.clean
    Error code: 1
    See logs for more information:
      C:\Users\Leo\vcpkg\buildtrees\python3\build-x64-windows-rel-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_msbuild.cmake:165 (vcpkg_execute_required_process)
  ports/python3/portfile.cmake:101 (vcpkg_install_msbuild)
  scripts/ports.cmake:133 (include)

Error: Building package python3:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: python3:x64-windows
  Vcpkg version: 2021-01-13-768d8f95c9e752603d2c5901c7a7c7fbdb08af35

Additionally, attach any relevant sections from the log files above.
`

-Please attach any additional failure logs mentioned in the console output.
[build-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/6013560/build-x64-windows-rel-out.log)

**Additional context**
Same exact error happens when trying to install x32 version too.

**Comment by Hoikas** [comment]
@WooXZerah Upstream Python has dropped support for Windows 7. On Windows, Python is run as part of the build process, so the build will fail. The python3 port will build correctly on Windows 8 or higher.

**Comment by NancyLi1013** [comment]
Hi @WooXZerah 

Thanks for posting this issue.

As @Hoikas said above, python3 has dropped support for Windows 7. So please use it on Windows 8 or higher.
So I'm closing this issue for now.

@Hoikas thanks for your help and information.

**Comment by WooXZerah** [comment]
> @WooXZerah Upstream Python has dropped support for Windows 7. On Windows, Python is run as part of the build process, so the build will fail. The python3 port will build correctly on Windows 8 or higher.

I was actually trying to install boost at first `.\\vcpkg install boost:x64-windows` and on packages to be installed Python is among them, there's any way to skip this specific package to install boost or make it work with a previous version of it? I have Python 3.7 working on Windows 7.

**Comment by Hoikas** [comment]
It looks like the main boost port installs almost every boost library, including boost-python 😞 . As a workaround, you could remove the dependency on boost-python locally.

**Comment by WooXZerah** [comment]
@Hoikas Thank you for your help. I decided I will be upgrading to Windows 10 soon (it's about time already :sweat_smile:).
