### ISSUE TITLE
[ace] Would it be possible to adapt the configuration of ACE via overlayed custom ports? 

### ISSUE THREAD

**Issue by e-geisler** [microsoft/vcpkg#16326]
Hi,

The current port/ace/portfile.cmake is unable to add|remove any custom configurations to ace/config.h, to mpc's dynamicflags|staticflags or others. For instance someone cannot add preprocessor variables like _ITERATOR_DEBUG_LEVEL=0 to the produced ace binaries/libraries without overwriting the original port file.
To work arround this issues someone has to:

1. modify the original portfile.cmake,
2. copy the original portfile.cmake to a custom overlay-port, changing it and call install with --overlay-ports=....

Both solutions have a serious drawback. Changes to the original file by the ACE maintainer are likely to be hidden (2.) or overwritten (1.).

My proposal is to use --overlay-ports with a custom portfile which sets appropriate CMAKE variables, which in turn are used by the original [ace]portfile to fill the ace/config.h or set the corresponding dynamicflags|staticflags in the MPC files e.g.:

[custom portfile.cmake]
```
set (ACE_OVERLAY_PORTS_CONFIG "
    #define ACE_HAS_NONSTATIC_OBJECT_MANAGER 1
")

\# Something similar with adding|removing dynamicflags|staticflags etc.
set (ACE_OVERLAY_PORTS_STATICFLAGS_REMOVE <...>)
set (ACE_OVERLAY_PORTS_STATICFLAGS_ADD "_ITERATOR_DEBUG_LEVEL=0")

\# Trigger default actions like downloading from github.com, configuration und building ace.
include (\<path-to-original-ace-portfile\>)
[]
```
Of course, the original port file must be able to take some actions if those variables are provided.

Tweaking ACE's configuration without touching the original portfile would be easy then:

- vcpkg install ace:x64-windows --overlay-ports=<custom-ports>/ports/ace

**Comment by JackBoosY** [comment]
@strega-nil what do you think about?

**Comment by strega-nil** [comment]
The correct way to handle this is via custom triplets, not via overlay ports; using a custom triplet, you'd be able to do something like:

```cmake
if(PORT STREQUAL "ace")
  set(ACE_STATICFLAGS_REMOVE <...>)
  set(ACE_STATICFLAGS_ADD "_ITERATOR_DEBUG_LEVEL=0")
endif()
```
or whatever.

**Comment by e-geisler** [comment]
Well, I have now understood the principle of adapting the package. I hadn't noticed the adapted triplets.  I suspect that the adaptation of the port file is the ACE project team respketive their contributors task?

**Comment by JackBoosY** [comment]
cc @jwillemsen

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

**Comment by JackBoosY** [comment]
Please note that the author of the port in vcpkg is not necessarily the owner of the upstream.

**Comment by jwillemsen** [comment]
A major rework of the ACE port file is not something I have spare time for, see https://github.com/DOCGroup/ACE_TAO/wiki/ACE-and-TAO-Commercial-support for the commercial support options for ACE/TAO, including @RemedyIT, the company I work for. Anyone can open a PR on the ACE port file here at vcpkg, contributions are welcome
