### ISSUE TITLE
[libusb] macOS build failure

### ISSUE THREAD

**Issue by adammpolak** [microsoft/vcpkg#16328]
**Host Environment**
- OS: macOS 11.0.1
- Compiler: revision

**To Reproduce**
`./vcpkg install libusb`

**Failure logs** 
```./vcpkg install libusb
Computing installation plan...
The following packages will be built and installed:
    libusb[core]:x64-osx -> 1.0.24#3
Detecting compiler hash for triplet x64-osx...
Could not locate cached archive: /Users/adammac/.cache/vcpkg/archives/98/98a5dab200cd044a17f4c9c9302cf72f6efc77a9.zip
Starting package 1/1: libusb:x64-osx
Building package libusb[core]:x64-osx...
-- Using cached /Users/adammac/dev/vcpkg-macos/vcpkg/downloads/libusb-libusb-c6a35c56016ea2ab2f19115d2ea1e85e0edae155.tar.gz
-- Cleaning sources at /Users/adammac/dev/vcpkg-macos/vcpkg/buildtrees/libusb/src/5e0edae155-faf13d1dff.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /Users/adammac/dev/vcpkg-macos/vcpkg/downloads/libusb-libusb-c6a35c56016ea2ab2f19115d2ea1e85e0edae155.tar.gz
-- Using source at /Users/adammac/dev/vcpkg-macos/vcpkg/buildtrees/libusb/src/5e0edae155-faf13d1dff.clean
-- Configuring x64-osx-dbg
-- Configuring x64-osx-rel
-- Generating configure for x64-osx
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
    Command failed: /usr/local/bin/autoreconf -vfi
    Working Directory: /Users/adammac/dev/vcpkg-macos/vcpkg/buildtrees/libusb/src/5e0edae155-faf13d1dff.clean/
    Error code: 1
    See logs for more information:
      /Users/adammac/dev/vcpkg-macos/vcpkg/buildtrees/libusb/autoconf-x64-osx-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:580 (vcpkg_execute_required_process)
  ports/libusb/portfile.cmake:53 (vcpkg_configure_make)
  scripts/ports.cmake:133 (include)


Error: Building package libusb:x64-osx failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libusb:x64-osx
  Vcpkg version: 2021-01-13-unknownhash

Additionally, attach any relevant sections from the log files above.```

```
Building package libusb[core]:x64-osx...
-- Using cached /Users/adammac/dev/vcpkg-macos/vcpkg/downloads/libusb-libusb-c6a35c56016ea2ab2f19115d2ea1e85e0edae155.tar.gz
-- Cleaning sources at /Users/adammac/dev/vcpkg-macos/vcpkg/buildtrees/libusb/src/5e0edae155-faf13d1dff.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /Users/adammac/dev/vcpkg-macos/vcpkg/downloads/libusb-libusb-c6a35c56016ea2ab2f19115d2ea1e85e0edae155.tar.gz
-- Using source at /Users/adammac/dev/vcpkg-macos/vcpkg/buildtrees/libusb/src/5e0edae155-faf13d1dff.clean
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
aclocal: warning: couldn't open directory 'm4': No such file or directory
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/local/Cellar/autoconf/2.69/bin/autoconf --force
autoreconf: running: /usr/local/Cellar/autoconf/2.69/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:23: installing './compile'
configure.ac:26: installing './install-sh'
configure.ac:26: installing './missing'
Makefile.am: installing './INSTALL'
examples/Makefile.am: installing './depcomp'
libusb/Makefile.am:6: error: Libtool library used but 'LIBTOOL' is undefined
libusb/Makefile.am:6:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
libusb/Makefile.am:6:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
libusb/Makefile.am:6:   If 'LT_INIT' is in 'configure.ac', make sure
libusb/Makefile.am:6:   its definition is in aclocal's search path.
autoreconf: automake failed with exit status:```

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by adammpolak** [comment]
`brew install libtool` fixed this issue

**Comment by JonLiu1993** [comment]
@adammpolak ，I can successfully install libusb on my local osx machine, please send me the complete error log

**Comment by adammpolak** [comment]
@JonLiu1993 it appears that i needed to have run `brew install libtool` before, now libusb was able to be installed.

But I am not able to find libusb even though it is installed when trying to install azure-kinect-sensor-sdk on macos https://github.com/microsoft/vcpkg/issues/16329 (I believe you are also assigned there)

**Comment by JackBoosY** [comment]
@adammpolak If you have other issues, please open an new issue to report them.

Thanks.
