### ISSUE TITLE
[New Port Request] SoX

### ISSUE THREAD

**Issue by Nexure** [microsoft/vcpkg#16333]
Library name: SoX

Library description: SoX is the Swiss Army Knife of sound processing utilities. It can convert audio files to other popular audio file types and also apply sound effects and filters during the conversion.

Source repository URL: https://sourceforge.net/projects/sox/

Project homepage (if different from the source repository): http://sox.sourceforge.net/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
