### ISSUE TITLE
[wxWidgets] failure to compile application on MacOS - it seems to be using Windows include file on MacOS.

### ISSUE THREAD

**Issue by davidsummers** [microsoft/vcpkg#16338]
**Describe the bug**
When trying to compile and link my application with wxWidgets on MacOS Big Sur I get a compiler error indicating that it can't find '../../lib/mswu/wx/setup.h' file.

**Environment**
- OS: MacOS Big Sur
- Compiler: Apple clang version 12.0.0 (clang-1200.0.32.29)

**To Reproduce**
Compile and link application with wxWidgets on MacOS using CMAKE 3.19.5.

*** Notice in the below error log that it seems to be trying to use the WINDOWS include files!
(../../lib/mswu/wx/setup.h)

**Expected behavior**
It should not be trying to use the WINDOWS include files on MACOS.

I believe this may have broken when issue #16154 was implemented a few days ago as it looks like that commit added the include for the WINDOWS version of the include file setup.h.

**Failure logs** 
In file included from /Users/david/projects/favor/src/favor/favor_app.cpp:13:
In file included from /Users/david/.local/share/pmm/1.5.1/vcpkg-master/packages/wxwidgets_x64-osx/include/wx-3.1/wx/wxprec.h:12:
In file included from /Users/david/.local/share/pmm/1.5.1/vcpkg-master/packages/wxwidgets_x64-osx/include/wx-3.1/wx/defs.h:45:
In file included from /Users/david/.local/share/pmm/1.5.1/vcpkg-master/packages/wxwidgets_x64-osx/include/wx-3.1/wx/platform.h:160:
/Users/david/.local/share/pmm/1.5.1/vcpkg-master/installed/x64-osx/include/wx/setup.h:4:10: fatal error: '../../lib/mswu/wx/setup.h' file not found
#include "../../lib/mswu/wx/setup.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

**Comment by JackBoosY** [comment]
In _include/wx/setup.h_:
```c
  1 #ifdef _DEBUG
  2 #include "../../debug/lib/mswud/wx/setup.h"
  3 #else
  4 #include "../../lib/mswu/wx/setup.h"
  5 #endif
```
