### ISSUE TITLE
boringssl install error

### ISSUE THREAD

**Issue by wangweiwei1188** [microsoft/vcpkg#16357]
**Describe the bug**
when use boringssl,  SSL_set_quic_early_data_context function is not found.

**Environment**
- OS: Windows
- Compiler: visual studio2017

**To Reproduce**
1. ./vcpkg install boringssl is ok. When use boringssl, 
2. dumpbin.exe -exports E:\work\windows_quic\vcpkg-master\packages\boringssl_x86-windows\debug\bin\ssl.dll > symbol.txt 
no SSL_set_quic_early_data_context   function found.

**Comment by Cheney-W** [comment]
Thanks for reporting this issue to us. 
I could reproduce the same result in my side, but this result is expected. The version of boringssl currently used by vcpkg is 2020-04-07, and the SSL_set_quic_early_data_context() function does not exist on this version.

For fixing this issue, we need to update the version of boringssl to the latest one. You could try to submit a PR to update this version or submit an issue which named"[boringssl] Update version", and then we will update this version of boringssl.
