### ISSUE TITLE
[New Port Request] Mobile Robot Programming Toolkit (MRPT)

### ISSUE THREAD

**Issue by jlblancoc** [microsoft/vcpkg#16351]
Library name: MRPT

Library description:
Mobile Robot Programming Toolkit (MRPT) provides C++ libraries aimed at researchers in mobile robotics and computer vision. Libraries include SLAM solutions, 3D(6D) geometry, SE(2)/SE(3) Lie groups, probability density functions (pdfs) over points, landmarks, poses and maps, Bayesian inference (Kalman filters, particle filters), image processing, obstacle avoidance, etc. MRPT also provides GUI apps for Stereo camera calibration, dataset inspection, and much more.

Source repository URL: https://github.com/MRPT/mrpt

Disclaimer: I'm the upstream author, and would be willing to open a PR to support it in vcpkg, but following the instructions, it seems opening an issue like this is *strongly* recommended first ;-)

**Comment by bpoebiapl** [comment]
If MRPT is ported to vcpkg, many people will be able to more easily access the powerful features of mrpt.
Sincerely hope that this port can be done successfully.

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
