### ISSUE TITLE
Why vcpkg always downloads cuda although it has already been installed by official installer?

### ISSUE THREAD

**Issue by EternalSaga** [microsoft/vcpkg#16355]
OS: windows10 20H2
My GPU is RTX30 series and it only supports cuda 11. I installed the cuda 11.1 package from nvidia site.
I want to build the opencv4.5 with cuda support but the vcpkg always download the cuda 10.1 itself.
How can I make the vcpkg to find the cuda11.1? CUDA_PATH and CUDA_BIN_PATH have already existed in the system environment varialbes.

**Comment by EternalSaga** [comment]
In fact, this situation is not only affect CUDA but also many other package.
For example, I have already installed python, the vcpkg still downloads python. I have already installed perl, the vcpkg still downloads perl.

**Comment by NancyLi1013** [comment]
Hi @EternalSaga 

Thanks for posting this issue.

For CUDA, I think it is due to cuda 11.1 hasn't added to `CUDA_PATHS` lists. So you cannot find it even though you have installed cuda11.1 on your machine.

Could you please try to add ENV CUDA_PATH_V11_1 to `CUDA_PATHS` and then rebuild cuda?

```
    set(CUDA_PATHS 
            ENV CUDA_PATH
            ENV CUDA_HOME
            ENV CUDA_BIN_PATH
            ENV CUDA_PATH_V11_1
            ENV CUDA_PATH_V11_0
            ENV CUDA_PATH_V10_2
            ENV CUDA_PATH_V10_1)
```
https://github.com/microsoft/vcpkg/blob/master/ports/cuda/vcpkg_find_cuda.cmake#L10-L16

For other tools like python and perl, please make sure the versions are greater than the ones that vcpkg provides. Also you are only installed when required by the ports. If they cannot be found, vcpkg will download them.

**Comment by EternalSaga** [comment]
> Hi @EternalSaga
> 
> Thanks for posting this issue.
> 
> For CUDA, I think it is due to cuda 11.1 hasn't added to `CUDA_PATHS` lists. So you cannot find it even though you have installed cuda11.1 on your machine.
> 
> Could you please try to add ENV CUDA_PATH_V11_1 to `CUDA_PATHS` and then rebuild cuda?
> 
> ```
>     set(CUDA_PATHS 
>             ENV CUDA_PATH
>             ENV CUDA_HOME
>             ENV CUDA_BIN_PATH
>             ENV CUDA_PATH_V11_1
>             ENV CUDA_PATH_V11_0
>             ENV CUDA_PATH_V10_2
>             ENV CUDA_PATH_V10_1)
> ```
> 
> https://github.com/microsoft/vcpkg/blob/master/ports/cuda/vcpkg_find_cuda.cmake#L10-L16
> 
> For other tools like python and perl, please make sure the versions are greater than the ones that vcpkg provides. Also you are only installed when required by the ports. If they cannot be found, vcpkg will download them.

Unfortunately, I tried this solution, vcpkg still tried to download cuda 10.1. I upgrade the cuda to 11.2 now. I think there is no difference between 11.1 and 11.2.
`    set(CUDA_REQUIRED_VERSION "11.2.0")

    set(CUDA_PATHS 
            ENV CUDA_PATH
            ENV CUDA_HOME
            ENV CUDA_BIN_PATH
            ENV CUDA_PATH_V11_2
            )`

**Comment by NancyLi1013** [comment]
Hi @EternalSaga 

Have you restart your machine after installing CUDA?

Also `CUDA_PATH `in System variables like this:

![image](https://user-images.githubusercontent.com/46708020/108940316-1b46f200-768e-11eb-9305-c1150e332dc1.png)

I can install cuda 11.2 successfully on my local.

```
PS F:\tool\vcpkg> .\vcpkg.exe install cuda
Computing installation plan...
The following packages will be built and installed:
    cuda[core]:x86-windows -> 10.1#5
Detecting compiler hash for triplet x86-windows...
Starting package 1/1: cuda:x86-windows
Building package cuda[core]:x86-windows...
-- Found CUDA V11.2.142
-- Performing post-build validation
-- Performing post-build validation done
Building package cuda[core]:x86-windows... done
Installing package cuda[core]:x86-windows...
Installing package cuda[core]:x86-windows... done
Elapsed time for package cuda:x86-windows: 123.1 ms

Total elapsed time: 2.746 s
```

**Comment by EternalSaga** [comment]
> Hi @EternalSaga
> 
> Have you restart your machine after installing CUDA?
> 
> Also `CUDA_PATH `in System variables like this:
> 
> ![image](https://user-images.githubusercontent.com/46708020/108940316-1b46f200-768e-11eb-9305-c1150e332dc1.png)
> 
> I can install cuda 11.2 successfully on my local.
> 
> ```
> PS F:\tool\vcpkg> .\vcpkg.exe install cuda
> Computing installation plan...
> The following packages will be built and installed:
>     cuda[core]:x86-windows -> 10.1#5
> Detecting compiler hash for triplet x86-windows...
> Starting package 1/1: cuda:x86-windows
> Building package cuda[core]:x86-windows...
> -- Found CUDA V11.2.142
> -- Performing post-build validation
> -- Performing post-build validation done
> Building package cuda[core]:x86-windows... done
> Installing package cuda[core]:x86-windows...
> Installing package cuda[core]:x86-windows... done
> Elapsed time for package cuda:x86-windows: 123.1 ms
> 
> Total elapsed time: 2.746 s
> ```

Yes, I restart my computer and the environment variables exist in my system path.
![Screenshot 2021-02-24 110739](https://user-images.githubusercontent.com/15174504/108941755-93aeb280-7690-11eb-95ab-db64c79da623.png)

**Comment by NancyLi1013** [comment]
Sorry, I have no idea what your problem is on your machine.

Could you please provide the detailed error info or install process?

**Comment by EternalSaga** [comment]
> Sorry, I have no idea what your problem is on your machine.
> 
> Could you please provide the detailed error info or install process?

It's my fault, I only saw the message 
```
The following packages will be built and installed:
    cuda[core]:x86-windows -> 10.1#5
```
and I ignored the following message.

**Comment by NancyLi1013** [comment]
`cuda[core]:x86-windows -> 10.1#5`

The version is decided by `Version `and `Port-Version` in CONTROL, which is not related with the version you downloaded and installed via https://developer.nvidia.com/cuda-downloads.
