### ISSUE TITLE
How do I know when the next scheduled release might be? Just looking for an estimate

### ISSUE THREAD

**Issue by aggieNick02** [microsoft/vcpkg#16365]
Apologies if this is answered somewhere and I missed it. Is there a way to tell when the target is for the next scheduled release? I'm assuming the releases are generally considered more likely to be "stable" than an arbitrary commit hash? If so, knowing when the next release might be is useful for planning when my subrepo will move to that release and be able to easily take advantage of new ports and features.

**Comment by NancyLi1013** [comment]
cc @vicroms 

Could you please help answer this issue?

**Comment by vicroms** [comment]
With the separation of the tool source code from the ports we are working on reviewing our release process. 
I don't have an estimate but we will bring it for discussion on our Thursday's meeting.

**Comment by aggieNick02** [comment]
Great, thanks! Just any general info or outlook is useful - my need to update isn't urgent, it's just something I'd like to do when the next stable release happens.

**Comment by ras0219** [comment]
> I'm assuming the releases are generally considered more likely to be "stable" than an arbitrary commit hash?

To directly answer this question: we don't consider the releases to be more stable; we provide them as a convenience for communication (it's easy to compare two releases, it's hard to compare two SHAs).

**Comment by aggieNick02** [comment]
> > I'm assuming the releases are generally considered more likely to be "stable" than an arbitrary commit hash?
> 
> To directly answer this question: we don't consider the releases to be more stable; we provide them as a convenience for communication (it's easy to compare two releases, it's hard to compare two SHAs).

That's really useful to know. Thanks!

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

**Comment by cblade-gpt** [comment]
vcpkg is unreliable use direct libraries, 4 years later and still unreliable haha
