### ISSUE TITLE
[macOS] OpenCV is not found in cmakes even when having run ./vcpkg integrate install and using -DCMAKE_TOOLCHAIN_FILE

### ISSUE THREAD

**Issue by adammpolak** [microsoft/vcpkg#16363]
**Describe the bug**

Was able to install opencv3 by running ./vcpkg opencv3

```Stored binary cache: /Users/adammac/.cache/vcpkg/archives/78/78a544af7b01601bc4dddc09a4223411808a5869.zip
Building package opencv3[core,dnn,flann,jpeg,png,quirc,tiff,webp]:x64-osx... done
Installing package opencv3[core,dnn,flann,jpeg,png,quirc,tiff,webp]:x64-osx...
Installing package opencv3[core,dnn,flann,jpeg,png,quirc,tiff,webp]:x64-osx... done
Elapsed time for package opencv3:x64-osx: 12.06 min

Total elapsed time: 12.12 min

The package opencv3:x64-osx provides CMake targets:

    find_package(OpenCV CONFIG REQUIRED)
    # Note: 13 target(s) were omitted.
    target_link_libraries(main PRIVATE opencv_ml opencv_dnn opencv_core opencv_flann)

```

**Environment**
- OS: 11.0.1
- Compiler: revision

**To Reproduce**
0. ./vcpkg integrate install
1. ./vcpkg install opencv3
2. Successfully install opencv3
3. Add `find_package(OpenCV CONFIG REQUIRED)` to a cmake file
4. Run cmake with `-DCMAKE_TOOLCHAIN_FILE=` and get:
```CMake Error at CMakeLists.txt:20 (find_package):Could not find a package configuration file provided by "OpenCV" with any
of the following names:

  OpenCVConfig.cmake
  opencv-config.cmake

Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
"OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"
provides a separate development package or SDK, be sure it has been
installed.CMake (find_package)
```

Even adding `if(DEFINED ENV{VCPKG_ROOT} AND NOT DEFINED CMAKE_TOOLCHAIN_FILE)
  set(CMAKE_TOOLCHAIN_FILE "$ENV{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake"
      CACHE STRING "")
endif()`

**Expected behavior**
Would expect that OpenCV would be found because have installed using vcpkg and have used integrate install so these packages should be found.

**Failure logs** 
```CMake Error at CMakeLists.txt:20 (find_package):
  No "FindOpenCV.cmake" found in CMAKE_MODULE_PATH.


CMake Warning (dev) at CMakeLists.txt:20 (find_package):
  FindOpenCV.cmake must either be part of this project itself, in this case
  adjust CMAKE_MODULE_PATH so that it points to the correct location inside
  its source tree.

  Or it must be installed by a package which has already been found via
  find_package().  In this case make sure that package has indeed been found
```

**Additional context**
Not able to build with cmake and find OpenCV even though OpenCV was installed with ./vcpkg install opencv3

**Comment by JackBoosY** [comment]
cc @cenit

**Comment by JackBoosY** [comment]
Is `$ENV{VCPKG_ROOT}` empty? I can't reproduce this issue.
Please pass `-DCMAKE_TOOLCHAIN_FILE=PATH_TO_VCPKG/scripts/buildsystems/vcpkg.cmake` directly.

**Comment by adammpolak** [comment]
@JackBoosY how could I check if $ENV{VCPKG_ROOT} is empty from terminal?

I ran `./vcpkg integrate install` , I thought that would set VCPKG_ROOT?

**Comment by cenit** [comment]
from shell, just do

```
echo $VCPKG_ROOT
```

**Comment by adammpolak** [comment]
@cenit It seems like running bash bootstrap-vcpkg.sh did not set $VCPKG_ROOT which was the issue.

When I use `-DCMAKE_TOOLCHAIN_FILE=PATH_TO_VCPKG/scripts/buildsystems/vcpkg.cmake` the library is found.

**Comment by cenit** [comment]
bootstrap does not set that env variable. Is it written somewhere that it should? in that case it has to be fixed

**Comment by adammpolak** [comment]
I guess I thought it was implied @cenit when it said it would "set things up" (was the gist I got but clearly it was more granular. I should not have assumed that paths would be set but that is usually what happens when I install packages so I thought that is what it did).

I am sure it was user error, thank you!
