### ISSUE TITLE
How do I speed up slow buildtime for packages

### ISSUE THREAD

**Issue by smufu** [microsoft/vcpkg#16361]
I noticed that vcpkg is not using all the available cores, at least it looks like that.
I am using a 3990x with (128 threads) and enough ram.
But for some reason the CPU usage always stays below 40% most of the time less than 2% are utilized.

For comparison: when building the Linux kernel (native x86 64 defconfig) it takes less than 30 seconds from a tmpfs mount or ~3 minutes from an ssd, but all cores get used.
Installing a few packages with vcpkg can easily take an hour or longer.

This is especially annoying for big packages like Qt.
But also small packages take surprisingly long (probably git / download).

Is there an easy way to configure vcpkg in a way that it will install packages in parallel, to combat the slow git clones and to speed up compilation a bit by using all cores?

**Comment by JackBoosY** [comment]
Hi @smufu, thanks for reporting this issue!
Vcpkg only provides automatic build, and does not directly provide binaries. 
According to your description, the compiler does use all the cores, but this does not mean that the CPU load can be fully used. There are many factors that affect compilation time.

**Comment by smufu** [comment]
Ok, then I just have to live with it.
If you find some ways to tweak vcpkg let me now.
I can also test and report if you have some ideas in mind.

Sadly something like this
`for package in <packages>; do ./vcpkg install "$package"& disown; done`
seems to break the install.

I will see if i can do something about it if not i will close this issue.
Thanks for you reply.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
