### ISSUE TITLE
Adding support for customized Project configurations?

### ISSUE THREAD

**Issue by paercebal** [Microsoft/vcpkg#1638]
For now, VCPKG only supports 'Debug' and 'Release' configurations, which means other configurations do not profit from the automatic include, linking, and binaries copying to the output directory at compilation time.

I propose to add a partial support based on configuration name prefix, instead of strict configuration name.

## Pre-requisite

The pre-requisite is the following: It is possible to offer different but compatible configurations binaries.

For example, if I create a using a custom configuration called "ReleaseDev" based on "Release", but disabling optimizations, my DLL "ReleaseDev" should work flawlessly with a "Release" DLL compiled with VCPKG.

AFAIK, the main breaking difference between Debug and Release is the use of the debug or release runtime DLL. Everything else should be compatible (_please correct me on the flags I'm wrong_).

## How it currently works

Currently, the "magic" is done in vcpkg.targets: https://github.com/Microsoft/vcpkg/blob/master/scripts/buildsystems/msbuild/vcpkg.targets

For example:

```
      <AdditionalDependencies Condition="'$(VcpkgConfiguration)' == 'Debug' and '$(VcpkgAutoLink)' != 'false'">%(AdditionalDependencies);$(VcpkgRoot)debug\lib\*.lib</AdditionalDependencies>
```

## The change I propose

Instead of supporting only 'Release' or 'Debug', I propose to support all configurations starting with 'Release' or 'Debug'.

This would result in something like the following change in vcpkg.targets file:

```
      <AdditionalDependencies Condition="$(VcpkgConfiguration.StartsWith('Debug')) and '$(VcpkgAutoLink)' != 'false'">%(AdditionalDependencies);$(VcpkgRoot)debug\lib\*.lib</AdditionalDependencies>
```
... the difference being `$(VcpkgConfiguration.StartsWith('Debug'))` replacing `'$(VcpkgConfiguration)' == 'Debug'`.

## Question

I've successfully tested the proposed modification above on my machine.

And, IMHO, adding to the specification that all user-defined configuration starting with "Release" should be compatible with the default "Release" (same for "Debug") is a good compromise.

So, is this something worth exploring? Either with the solution above, or a variation?

Edit: Just in case the solution above is good enough, I proposed the change in the request below.

Thanks,

**Comment by martin-s** [comment]
What about other schemes of configurations? For example, RelWithDebInfo and others cmake provides...

**Comment by ras0219-msft** [comment]
@martin-s The `VcpkgConfiguration` variable is initialized with your solution configuration by default[1], but you can override it inside your MSBuild.

So, you could add:
```xml
<PropertyGroup>
  <VcpkgConfiguration Condition="'$(Configuration)' == 'RelWithDebInfo'">Release</VcpkgConfiguration>
</PropertyGroup>
```
to your project file's globals section and we'll see and match against "Release".

[1] https://github.com/Microsoft/vcpkg/blob/45fcdbc7f26a80ba37baa48f403d20a1e1063bf2/scripts/buildsystems/msbuild/vcpkg.targets#L38

**Comment by paercebal** [comment]
@ras0219-msft Is your solution what you recommend for all the cases (including the ones I describe)?

_(i.e. I didn't realize this was a possible solution, even in my case. I find your solution actually better than the "hack" in my pull requests, or the hacks I tried at home - I actually went through a few hacks to produce similar results, after failing to find a way to do it cleanly)._

If yes, is there a documentation on the subject?



If there isn't a documentation, I suggest we should update the FAQ:

https://github.com/Microsoft/vcpkg/blob/master/docs/about/faq.md

... with something like:

> I have non-standard configurations that are compatible with standard configuration. How can I profit from VCPKG integration?
> 
> In your project file, you can add the following:
> ```
> <PropertyGroup>
>   <VcpkgConfiguration Condition="'$(Configuration)' == 'YOUR_CONFIGURATON_NAME_HERE'">Release</VcpkgConfiguration>
> </PropertyGroup>
> ```
>
> ... to have VCPKG consider your non-standard configuration as a "Release" one (the same for "Debug")."

If everyone agrees, I can cancel this issue and the associated pull request, and update the FAQ documentation instead.

**Comment by ras0219-msft** [comment]
While the solution I've posted would work for your cases, I think that your proposed change will make for a better "by-default" experience. In parallel though, we _should_ improve the FAQ and I'd be delighted if you added that section to your PR.

**Comment by paercebal** [comment]
Ok.

I have two questions, and one proposal:

# Questions

## Do we make this case-insensitive?

Do we make the test case insensitive as suggested by @pravic ?

```
$(VcpkgConfiguration.StartsWith('Debug', $true))
$(VcpkgConfiguration.StartsWith('Release', $true))
```

## What about other CMake "configurations" 

For the sake of a better "by-default" experience, should the pull request also support CMake's "configurations" (for lack of a better term)? That is:
- MinSizeRel
- RelWithDebInfo (this is the only CMake "Release"-compatible configuration with PDBs)

(I've looked at VCXPROJ files generated by CMake, and they seem compatible with "Release")

# Proposal

I propose two pull requests:

1. one pull request to update the documentation about the manual support for other configurations
2. followed by another to extend the automatic support of other, compatible, configurations, as well as the relevant documentation update

**Comment by paercebal** [comment]
The basic support (for strict "Release"/"Debug" prefix), as well as the relevant documentation was done:

- https://github.com/Microsoft/vcpkg/pull/1639
- https://github.com/Microsoft/vcpkg/pull/1743

Do I close this issue now? Or do I conclude by providing:

- support of case insensitive prefixes (e.g. "releaseGizmo" will also work)
- and/or support for default CMake configs (i.e. "MinSizeRel" and "RelWithDebInfo")

... as well as the relevant documentation update?

**Comment by bjornpiltz** [comment]
👍  for adding support for default CMake configs (i.e. "MinSizeRel" and "RelWithDebInfo").

**Comment by ras0219-msft** [comment]
Yep, both of those CMake configs were added to autodetection.

I'd be happy to accept documentation updates or case-insensitivity changes, but I think this is good enough to call this issue closed.

Thanks @paercebal for working through this!
