### ISSUE TITLE
[opencv3] missing opencv_worldxxxx.libs

### ISSUE THREAD

**Issue by Goru1890** [microsoft/vcpkg#16389]
After the  compilation of darknet using https://github.com/AlexeyAB/darknet/blob/master/scripts/setup.ps1 I'm missing a couple of opencv_worldxxxx.lib for the compilation of [Yolo Mark](https://github.com/AlexeyAB/Yolo_mark).

And if a try to install again only opencv3[world] it deletes my darknet package.

**Comment by JackBoosY** [comment]
@Goru1890  Is this an usage issue or build issue? Can you describe in more detail?

Thanks.

**Comment by Goru1890** [comment]
Just as described in the title of the issue, after the installation of darknet with vckpg (darknet[opencv3-cuda,cdnn] ), the installation also installs opencv3 with cuda. But I'm missing some opencv libraries as opencv_worldxxx.dll in the opencv installation.

I'm using windows 10.

**Comment by JackBoosY** [comment]
@Goru1890  So I assume this issue is about opencv3 and not darknet?

**Comment by Goru1890** [comment]
Yes

**Comment by JackBoosY** [comment]
cc @cenit

**Comment by JackBoosY** [comment]
Should `darknet[opencv3-cuda]` depends on `opencv3[world]`?

**Comment by Goru1890** [comment]
![image](https://user-images.githubusercontent.com/35274844/109154495-a1d30080-776e-11eb-801a-d801403bc512.png)

**Comment by cenit** [comment]
opencv3[world], like opencv4[world], are just special builds in which ALL opencv libs are built in a single library. Which is not the best way to build opencv.

Given that, darknet has dependencies clearly explained. If you later rebuild opencv3 with the world feature, vcpkg will rebuild any dependent package considering the new feature and darknet will work the same. You have to let it rebuild with the --recurse flag!

I hope it is more clear to you.
About Yolo mark, if you use this version https://github.com/cenit/yolo_mark/tree/dev/cenit%2Fcmake you will find that it builds correctly. The original version has some problems but unfortunately Alexey never had time to merge my PR

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
