### ISSUE TITLE
How do I transfer and install built packages onto a machine without internet access?

### ISSUE THREAD

**Issue by jdx-john** [microsoft/vcpkg#16391]
Our build machine is isolated from the internet, which means we cannot get vcpkg from Git or download any packages.
I know I can generate Nugets from vcpkg but is that my best/only option? It would be far preferable if the build machine builds the packages from source so we 'trust' who has done the building, rather than some developer do it and copy binaries across.

Is there some way I can run vcpkg locally to just get all the sources, then copy this to another machine for doing all the compilation? Open to ideas generally on this scenario.

**Comment by vicroms** [comment]
Yes, in a computer with internet access run: 

```
vcpkg install <package> --only-downloads
```

All zipped source files and some tools will be downloaded to `{vcpkg-root}/downloads`. Copy that folder into your build machine's vcpkg folder and run `vcpkg install`. After that, vcpkg should use the already downloaded files.

**Comment by jdx-john** [comment]
When running `vcpkg install` will it attempt to look for newer versions, or will it use the local sources only? Because conversely, we want our developers to be using the same versions of packages as our build machine - so it might make sense we use `--only-downloads` and share this folder around, periodically updating it, since AFAIK vcpkg doesn't yet have full support for specifying historical versions of packages?

**Comment by vicroms** [comment]
Recently we added support for [versioning through manifest files](https://devblogs.microsoft.com/cppblog/take-control-of-your-vcpkg-dependencies-with-versioning-support/). Using the same manifest file in all your development machines will result in the same versions being installed. 

By default `vcpkg install` will use the versions of libraries currently in `ports/`. If you use a manifest file and enable versioning, it will use the versions you specify.

**Comment by jdx-john** [comment]
I think I will probably have some further question on versioning, but since my main question on offline use is answered that might be best in a dedicated issue?

**Comment by NancyLi1013** [comment]
@jdx-john 

You can open a new issue for `versioning` if you have any questions about this.

**Comment by NancyLi1013** [comment]
Closing this issue for now. Please feel free to reopen this issue if it is still a problem for you.
