### ISSUE TITLE
[zstr] zstr_make_unique_polyfill.h missing, causing compile errors on C++11 projects

### ISSUE THREAD

**Issue by dan9er** [microsoft/vcpkg#16402]
**Host Environment**
- OS: Xubuntu 20.04.2 LTS
- Compiler: Clang 10

**To Reproduce**
1. `[...]/vcpkg$ ./vcpkg install zstr`
2. Create these files:
- CMakeLists.txt:
```cmake
add_executable(foo src/foo.cpp)

set_target_properties(foo PROPERTIES
    CXX_STANDARD 11
    CXX_STANDARD_REQUIRED ON
)

find_package(ZLIB REQUIRED)
find_path(ZSTR_INCLUDE_DIRS "zstr/strict_fstream.hpp")

target_link_libraries(foo PRIVATE ZLIB::ZLIB)
target_include_directories(foo PRIVATE ${ZSTR_INCLUDE_DIRS})
```
- src/foo.cpp:
```cpp
#include <zstr/zstr.hpp>

int main()
    {return 0;}
```
3. `[...]/build$ cmake .. -DCMAKE_TOOLCHAIN_FILE:FILEPATH=[...]/vcpkg/scripts/buildsystems/vcpkg.cmake`
4. `[...]/build$ cmake --build .`

**Failure logs** 
```
In file included from [...]/src/foo.cpp:1:
[...]/vcpkg/installed/x64-linux/include/zstr/zstr.hpp:20:10: fatal error: zstr_make_unique_polyfill.h: No such file or directory
   20 | #include <zstr_make_unique_polyfill.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Additional context**
https://github.com/mateidavid/zstr/blob/v1.0.4/src/zstr.hpp#L19-L21

**Comment by dan9er** [comment]
Simply inserting `${SOURCE_PATH}/src/zstr_make_unique_polyfill.h` into here will fix this
https://github.com/microsoft/vcpkg/blob/a3db16a4475b963cacf0260068c497fb72c8f3c0/ports/zstr/portfile.cmake#L9-L12

**Comment by dg0yt** [comment]
> I think the following is the wrong approach:
> 
> > ```cmake
> > find_path(ZSTR_INCLUDE_DIRS "zstr/strict_fstream.hpp")
> > ```
> 
> because you will get the directory were "zstr/strict_fstream.hpp" is. But you seem to need the directory where "strict_fstream.hpp" is. How about the following:
> 
> ```cmake
> find_path(ZSTR_INCLUDE_DIRS "zstr.hpp" PATH_SUFFIXES "zstr")
> ```
> 
> (Note: the public header, not the implementation detail.)
> 
> Then you can also use
> 
> ```c
> #include <zstr.hpp>
> ```

**Comment by dan9er** [comment]
@dg0yt That is relevant to the other issue I've made, not this one.
