### ISSUE TITLE
[caffe2:x64-windows] build failure

### ISSUE THREAD

**Issue by SyntheseyResine** [microsoft/vcpkg#16412]
**Host Environment**
OS: Windows10
Compiler: revision

**To Reproduce**

vcpkg install caffe2

Computing installation plan...
The following packages will be built and installed:
    caffe2[core]:x86-windows
Detecting compiler hash for triplet x86-windows...
Starting package 1/1: caffe2:x86-windows
Building package caffe2[core]:x86-windows...
Could not locate cached archive: C:\Users\user\AppData\Local\vcpkg\archives\ff\fff8e82b4e42d7f962411eb7a9b9e60f7af50ca7.zip
-- Note: caffe2 only supports static library linkage. Building static library.
CMake Error at ports/caffe2/portfile.cmake:6 (message):
  Caffe2 cannot be built for the x86 architecture
Call Stack (most recent call first):
  scripts/ports.cmake:79 (include)

Error: Building package caffe2:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: caffe2:x86-windows
  Vcpkg version: 2020.06.15-nohash

**Comment by JackBoosY** [comment]
```
CMake Error at ports/caffe2/portfile.cmake:6 (message):
Caffe2 cannot be built for the x86 architecture
```

**Comment by JonLiu1993** [comment]
Hi @SyntheseyResine ，What you installed is not caffe2:x64-windows, caffe2 does not support caffe2:x84-windows, please use the command. ./vcpkg install caffe2:x64-windows
