### ISSUE TITLE
[freetype] [libpng] Crash in Freetype when loading TrueType CBDT fonts on Windows x64

### ISSUE THREAD

**Issue by jwtowner** [microsoft/vcpkg#16418]
**Describe the bug**
libpng uses `setjmp`/`longjmp` for error handling by default and it allocates memory using `malloc` by default (see [here](https://github.com/glennrp/libpng/blob/dbe3e0c43e549a1602286144d94b0666549b18e6/pngmem.c#L95)). Freetype uses libpng for CBDT/CBLC emoji & icon fonts containing png images for each font glyph (see [here](https://gitlab.freedesktop.org/freetype/freetype/-/blob/master/src/sfnt/pngshim.c#L295)). Freetype additionally uses the default `setjmp`/`longjmp` mechanism for error handling with libpng and it does not provide user-defined memory allocation/deallocation functions to libpng.

The alignment of `jmp_buf` on x64 is 16-bytes when compiling with MSVC++ 2017 and 2019. `png_struct_def` defines a `jmp_buf` member variable so `alignof(png_struct_def) >= alignof(jmp_buf)` is true, which is what we want. The problem occurs when creating a `png_struct` through the `png_create_*` suite of APIs. By default, these functions simply call `malloc`, which only guarantees that the returned pointer has 8-byte alignment on Windows x64. When calling `setjmp( png_jmpbuf( png_ptr ) )` this often results in an access violation executing a `MOVDQA` instruction when the given `jmp_buf` address is not aligned to 16-bytes. With user-defined memory allocation functions provided to `png_create_*`, this problem can be avoided since we can call `_aligned_malloc`.

However, Freetype simply uses the default memory allocation behavior with libpng, and it does not publicly expose any means by which we can override how the `png_struct` is created.

I'm wondering how best to fix this for Vcpkg users. Should we patch Freetype so that uses `_aligned_malloc` and `_aligned_free` on Windows and UWP platforms? Should this be fixed upstream in Freetype?

**Environment**
- OS: Windows 10 x64 (Version 20H2)
- Platforms: Windows Desktop and UWP
- Compiler: MSVC++ 2017 (14.16.27023) and MSVC++ 2019 (14.28.29333)

**To Reproduce**
1. Build freetype[png]
2. Using Freetype, write a program that opens a TrueType or OpenType font containing CBDT glyphs, such as the Noto Sans Emoji font.
3. Get an access violation inside of `__intrinsic_setjmp` after Freetype calls `setjmp` in [src/sfnt/pngshim.c(313)](https://gitlab.freedesktop.org/freetype/freetype/-/blob/master/src/sfnt/pngshim.c#L313), with a stacktrace matching the output logged below.

**Expected behavior**
No crash should occur, the font should be loaded and execution should proceed.

**Failure logs** 
Unhandled Exception At 0x007ffb8046fa5b -- Access violation reading location 0xffffffffffffffff

--- STACKTRACE ---
 0# 0x007ffb8046fa5b in VCRUNTIME140.dll
 1# Load_SBit_Png at vcpkg\buildtrees\freetype\src\827cda734a-239082ca76.clean\src\sfnt\pngshim.c(313)
 2# tt_sbit_decoder_load_png at vcpkg\buildtrees\freetype\src\827cda734a-239082ca76.clean\src\sfnt\ttsbit.c(1098)
 3# tt_sbit_decoder_load_bitmap at vcpkg\buildtrees\freetype\src\827cda734a-239082ca76.clean\src\sfnt\ttsbit.c(1242)
 4# tt_sbit_decoder_load_image at vcpkg\buildtrees\freetype\src\827cda734a-239082ca76.clean\src\sfnt\ttsbit.c(1438)
 5# tt_face_load_sbit_image at vcpkg\buildtrees\freetype\src\827cda734a-239082ca76.clean\src\sfnt\ttsbit.c(1646)
 6# TT_Load_Glyph at vcpkg\buildtrees\freetype\src\827cda734a-239082ca76.clean\src\truetype\ttgload.c(2829)
 7# FT_Load_Glyph at vcpkg\buildtrees\freetype\src\827cda734a-239082ca76.clean\src\base\ftobjs.c(951)
 8# ...

**Additional Context**
Note that "Access violation reading location 0xffffffffffffffff" is a red-herring. In the debugger disassembly, the CPU is trying to execute `00007FFDA7DFE68B  movdqa      xmmword ptr [rcx+60h],xmm6` where `rcx` has a value of `0x00000206460BB038`.

**Comment by jwtowner** [comment]
Issue filed upstream: https://gitlab.freedesktop.org/freetype/freetype/-/issues/1037

**Comment by jwtowner** [comment]
I have pending merge request upstream that fixes the issue here: https://gitlab.freedesktop.org/freetype/freetype/-/merge_requests/15

**Comment by apodtele** [comment]
Microsoft describes [malloc](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/malloc) with 16-byte (128-bit) alignment on Windows x64. Are you sure??? Why did you mention HeapAlloc elsewhere?

**Comment by jwtowner** [comment]
> Microsoft describes malloc with 16-byte (128-bit) alignment on Windows x64. Are you sure??? Why did you mention HeapAlloc elsewhere?

You're right, this issue actually doesn't exist in libpng or with malloc. False alarm on my end caused by third-party middleware hooking the HeapAlloc function that I was unaware of, that did not provide the 16-byte alignment guarantee. My apologies for not having noticed it sooner. Closing this issue.
