### ISSUE TITLE
[New Port Request] Visualization Library

### ISSUE THREAD

**Issue by EPLKleijntjens** [microsoft/vcpkg#16414]
Library name:
Visualization Library

Library description:
Visualization Library is a C++ middleware for high-performance 2D and 3D graphics applications based on the industry standard OpenGL 1.x-4.x, designed to develop portable applications for the Windows, Linux and Mac OS X operating systems.

Source repository URL:
https://github.com/MicBosi/VisualizationLibrary

Project homepage (if different from the source repository):
https://visualizationlibrary.org

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
