### ISSUE TITLE
dll removed before debugging

### ISSUE THREAD

**Issue by trojanfoe** [microsoft/vcpkg#16432]
**Describe the bug**
The dependent library (pugixml in this case) is successfully linked and the dll copied into $(TargetDir) (I see it in File Explorer), however when I run the .exe the .dll file gets removed. After this happens the dll will never be copied into $(TargetDir) again during subsequent builds.

**Environment**
- OS: Windows 10 20H2 x64
- Compiler: 19.28.29337
- vcpkg: 2021-01-13-768d8f95c9e752603d2c5901c7a7c7fbdb08af35

**To Reproduce**
1. ./vcpkg install pugixml:x64-windows
2. Build project auto-linking with pugixml in VS.
3. Look at $(TargetDir) in file explorer and note pugixml_d.dll exists.
4. Run/Debug and get error message about missing dll.

**Expected behavior**
The dll remains in the $(TargetDir).

**Failure logs** 
Error dialog produced:
The code execution cannot proceed because pugixml_d.dll was not found. Reinstalling... blah blah.

**Additional context**

**Comment by trojanfoe** [comment]
When rebuilding, I see this in the build log:

```
Using "Delete" task from assembly "Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
1>  Task "Delete"
1>    Deleting file "C:\Users\Andy\Documents\Source\PixelEngine\x64\Debug\pugixml_d.dll".
1>  Done executing task "Delete".
```

**Comment by trojanfoe** [comment]
When rebuilding, I see this in the build output:

```
Using "Delete" task from assembly "Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
1>  Task "Delete"
1>    Deleting file "C:\Users\Andy\Documents\Source\ProjectName\x64\Debug\pugixml_d.dll".
1>  Done executing task "Delete".
```

**Comment by trojanfoe** [comment]
I am wondering if this is because vcpkg/msbuild doesn't realise there is a dependency on pugixml because it's the only header file that isn't installed into it's own sub-directory; instead it's installed into the top-level `vcpkg\installed\x64-windows\include` directory?

**Comment by trojanfoe** [comment]
Add a vcpkg manifest file to my project and set "use manifest" to "yes" in the VS project in order to explicitly state my dependencie:

```
{
    "name": "projectname",
    "version-string": "0.0.1",
    "dependencies": [ "directxtk", "pugixml", "effolkronium-random", "utfcpp", "yaml-cpp" ]
}
```

Didn't make a difference, so it's not a dependency issue.

**Comment by Cheney-W** [comment]
Thanks for reporting this issue to us! 
In order to investigate this issue, could you please provide us with your ProjectName.vcxproj file? Through this file, we may find out why the delelate task is triggered.

**Comment by trojanfoe** [comment]
Hi there, I have tried to checkout the previous commit showing the error but I have been unable to get it working.  I therefore created a test project to try and reproduce the issue but of course this works perfectly and the dll is being copied into `$(TargetDir)` as expected.
Sorry to waste your time on this :|

**Comment by trojanfoe** [comment]
@Cheney-W I have managed to reproduce the issue.
[MyProject.vcxproj.txt](https://github.com/microsoft/vcpkg/files/6068208/MyProject.vcxproj.txt)

**Comment by trojanfoe** [comment]
After initial build I see the following references to `pugixml` in the output window:
```
Task "Message"
1>    C:\Users\...\x64\Debug\pugixml_d.dll
1>  Done executing task "Message".
...
 Did not copy from file "C:\Users\...\x64\Debug\pugixml_d.dll" to file "C:\Users\...\x64\Debug\pugixml_d.dll" because the "SkipUnchangedFiles" parameter was set to "true" in the project and the files' sizes and timestamps match.
```
and running the `.exe` from File Explorer works fine.

Then hit `F5` and I see:

```
Task "Delete"
1>    Deleting file "C:\Users\...\x64\Debug\pugixml_d.dll".
1>  Done executing task "Delete".
```

and an error dialog.

**Comment by Cheney-W** [comment]
@trojanfoe Thanks for your reply! I have some questions need confirm with you:
1. Does this issue occur in a new console application project?
2. Does this issue only occur in your current MyProject project?
3. I saw there are 2 custombuildsteps in your vcxproj file, are this you expected?
4. Could you please provide me with the ProcessContent.py file?

**Comment by trojanfoe** [comment]
@Cheney-W 

1. No, it's works perfectly.
2. Yes, when I change to the triplet x64-windows.  I am currently using x64-windows-static-md and everything works fine.
3. There is actually only one, which might have been misconfigured at the time of posting the project file (The Output field was missing so it wasn't running).
4. It's attached, but it's nothing special.

[ProcessContent.py.txt](https://github.com/microsoft/vcpkg/files/6074534/ProcessContent.py.txt)

**Comment by PhoebeHui** [comment]
I can't repro this issue, could you attach full log from build output?

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

**Comment by sakiodre** [comment]
I also have this issue for some reason, I'm running on my own vcpkg fork with a port updated if that matters.
I fixed it by cd to vcpkg directory and re-run [these commands](https://github.com/microsoft/vcpkg#quick-start-windows):
```
bootstrap-vcpkg.bat
vcpkg integrate install
```
