### ISSUE TITLE
cpr update to v1.5.2

### ISSUE THREAD

**Issue by Upbolt** [microsoft/vcpkg#16439]
Library name: cpr

New version number: 1.5.2

![image](https://user-images.githubusercontent.com/58544287/109355348-effe0780-7833-11eb-8be2-c2da60371018.png)
![image](https://user-images.githubusercontent.com/58544287/109355369-f68c7f00-7833-11eb-9403-9f023f71405c.png)

**Comment by JonLiu1993** [comment]
Solved by #14131
