### ISSUE TITLE
[mongoose] update to 7.1

### ISSUE THREAD

**Issue by jimellert** [microsoft/vcpkg#16437]
Library name:  mongoose

New version number:  7.1

Other information that may be useful (release notes, etc...)
I use the SSL version.   I also have to locally update CMakeLists.txt to add
 -DMG_ENABLE_CALLBACK_USERDATA so that mongoose passes my userdata through to callbacks.  Is there a better way to do this?

**Comment by JonLiu1993** [comment]
Hi @jimellert ,I have updated the mongoose port to the latest version 7.1.0. I see your problem. I think it can be achieved by adding features, but I did not find the MG_ENABLE_CALLBACK_USERDATA options in the source. Is this a problem when using this port?

**Comment by jimellert** [comment]
Hi Jon,

Thanks for the update.

It looks like version 7.1 has eliminated the need for MG_ENABLE_CALLBACK_USERDATA, so we’re good there.

I’m having trouble with mongoose and am working with cesanta to get it fixed.  I would imagine there’s yet another version coming soon.

Jim

**Comment by JonLiu1993** [comment]
@jimellert ,Okay, that sounds great, I will update the latest version in time

**Comment by jimellert** [comment]
Hi Jon, I have a question…

I did a git pull from my vcpkg dir,   then vcpkg update.   But I don’t see mongoose 7.1.   Do I need to do something else?

 

It shows the following:

C:\Projects\github\microsoft\vcpkg>vcpkg update

Using local portfile versions. To update the local portfiles, use `git pull`.

The following packages differ from their port versions:

    gtest:x64-windows-static         1.10.0#2 -> 1.10.0#4

    gtest:x86-windows-static         1.10.0#2 -> 1.10.0#4

    libiconv:x64-windows-static      1.16#5 -> 1.16#8

    libiconv:x86-windows-static      1.16#5 -> 1.16#8

    liblzma:x64-windows-static       5.2.5#1 -> 5.2.5#2

    liblzma:x86-windows-static       5.2.5#1 -> 5.2.5#2

    libxml2:x64-windows-static       2.9.10 -> 2.9.10#2

    libxml2:x86-windows-static       2.9.10 -> 2.9.10#2

    openssl:x86-windows-static       1.1.1g#1 -> 1.1.1i

    openssl-windows:x86-windows-static 1.1.1h -> 1.1.1h#1

 

To update these packages and all dependencies, run

    .\vcpkg upgrade

 

To only remove outdated packages, run

    .\vcpkg remove --outdated

 

Jim

**Comment by JonLiu1993** [comment]
@jimellert ,At present, my update has not been merged to master, so you cannot get the latest version. Please wait for this pr to be merged and you will get the latest version by git pull
