### ISSUE TITLE
nuget package exported from vcpkg does not work with UWP

### ISSUE THREAD

**Issue by HppZ** [microsoft/vcpkg#16430]
**Describe the bug**

build log from visual studio 16.8.4:
   AppContainerApplication = true
   VcpkgOSTarget = windows
   VcpkgTriplet = x64-windows

**Environment**
- OS: [Windows]
- Compiler: 16.8.4

**Expected behavior**

VcpkgOSTarget should be 'uwp'

**Comment by HppZ** [comment]
https://github.com/microsoft/vcpkg/pull/15410
https://github.com/microsoft/vcpkg/issues/15409

updated vcpkg and regenerated nuget package. it still does not work.

**Comment by HppZ** [comment]
@JackBoosY

**Comment by NancyLi1013** [comment]
Hi @HppZ 

Could you please help confirm where do you get the messages?

```
AppContainerApplication = true
VcpkgOSTarget = windows
VcpkgTriplet = x64-windows
```
Also could you please try to add `x64-uwp` as Triplet in your project to rebuild?

![image](https://user-images.githubusercontent.com/46708020/129336066-7334dd7b-83c1-4b72-aa11-30966daa44e5.png)

**Comment by JonLiu1993** [comment]
@HppZ , Can you provide your steps to reproduce? and try add x64-uwp as Triplet in your project to rebuild

**Comment by MonicaLiu0311** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
