### ISSUE TITLE
How do I specify compiler type ?

### ISSUE THREAD

**Issue by Mr-Leshiy** [microsoft/vcpkg#16444]
Is it possible to specify the compiler type for package that I want to build and download throw 'install' command. 
Here is the case where it should be necessary https://github.com/google/googletest/blob/master/googletest/README.md#incorporating-into-an-existing-cmake-project.

**Comment by MrROBUST** [comment]
Likely a duplicate of #16368

**Comment by JonLiu1993** [comment]
Thanks for posting this issue,Duplicate of #16368
