### ISSUE TITLE
[vcpkg-tool] clone date/sha commit out of sync with downloadable binary/source date/sha commit

### ISSUE THREAD

**Issue by StarGate-One** [microsoft/vcpkg#16441]
**Describe the bug**
As of 02/26/2021 00:48 UTC
1. Clone https://github.com/microsoft/vcpkg-tool
Build vcpkg binary using CMake
`vcpkg version` yields:
`Vcpkg package management program version 2021-01-13-8027bea90b47d50fd6090bbf5ded330f00f87570`
This is the latest date in CMakeLists.txt and latest sha commit to repository.

2. Vcpkg latest downloadable file https://github.com/microsoft/vcpkg-tool/releases/tag/2021-02-24-d67989bce1043b98092ac45996a8230a059a2d7e vcpkg.exe
`vcpkg version` yields:
`Vcpkg package management program version 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e`
The `CMakeLists.txt` date still has 2021-01-13 in the downloadable source [Souce Code zip](https://github.com/microsoft/vcpkg-tool/archive/2021-02-24-d67989bce1043b98092ac45996a8230a059a2d7e.zip) and [Source Code tar.gz](https://github.com/microsoft/vcpkg-tool/archive/2021-02-24-d67989bce1043b98092ac45996a8230a059a2d7e.tar.gz) even though the Release tag shows a date of [2024-02-24](https://github.com/microsoft/vcpkg-tool/releases/tag/2021-02-24-d67989bce1043b98092ac45996a8230a059a2d7e)

3. There was a change to vcpkg bootstrap.sh and bootstrap.ps1 for [microsoft/vcpkg commit 2bd1faf](https://github.com/microsoft/vcpkg/commit/2bd1faf3599d4677d31c9af179238c565e48dd2c) shows the newer date than in [microsoft/vcpkg-tool](https://github.com/microsoft/vcpkg-tool) github repository and downloadable sources.

4. I can understand as ongoing fixes and development happen how the commit/sha can be different.

5. So I am wondering if the timing just got the dates out of sync?

6.  Also you all are doing great work by the way.👍👏👏✔😎

**Comment by PhoebeHui** [comment]
@StarGate-One, thanks for reporting this issue!

As 2021-02-24-d67989bce1043b98092ac45996a8230a059a2d7e released, the version should be 
```
2021-02-24-d67989bce1043b98092ac45996a8230a059a2d7e
```

However it shows wrong version with 'vcpkg version' command, this should be a vcpkg bug. @ras0219-msft, could you please take a look?

```
PS F:\vcpkg\clean> ./vcpkg version
Vcpkg package management program version 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e
```

**Comment by StarGate-One** [comment]
Closing as this does not seem to be fixed.

**Comment by PhoebeHui** [comment]
Reopen this issue for tracking the bug, related to PR https://github.com/microsoft/vcpkg-tool/pull/51, this issue should be fixed in next release.

**Comment by NancyLi1013** [comment]
This issue should be fixed on latest version now. The date in tag name is consistent with that in vcpkg version.
Please try to update vcpkg to rebuild.
```
PS F:\latest\vcpkg> .\bootstrap-vcpkg.bat
Downloading https://github.com/microsoft/vcpkg-tool/releases/download/2021-08-12/vcpkg.exe -> F:\latest\vcpkg\vcpkg.exe... done.
Validating signature... done.

Telemetry
---------
vcpkg collects usage data in order to help us improve your experience.
The data collected by Microsoft is anonymous.
You can opt-out of telemetry by re-running the bootstrap-vcpkg script with -disableMetrics,
passing --disable-metrics to vcpkg on the command line,
or by setting the VCPKG_DISABLE_METRICS environment variable.

Read more about vcpkg telemetry at docs/about/privacy.md
PS F:\latest\vcpkg> .\vcpkg.exe version
Vcpkg package management program version 2021-08-12-85ab112d5ee102bc6eac8cdbbfdd173a71374e04

See LICENSE.txt for license information.
PS F:\latest\vcpkg>
```
