### ISSUE TITLE
[New Port Request] <unofficial-sqlite3>

### ISSUE THREAD

**Issue by llduncangithub** [microsoft/vcpkg#16442]
Library name:
unofficial-sqlite3
Library description:

Source repository URL:

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by Cheney-W** [comment]
@llduncangithub Could you please provide the download path of the source of this port?

**Comment by PhoebeHui** [comment]
We already have the port, see https://github.com/microsoft/vcpkg/blob/master/ports/sqlite3/CMakeLists.txt.
