### ISSUE TITLE
error with cmake

### ISSUE THREAD

**Issue by God-Staff** [Microsoft/vcpkg#1644]
The error is happened while me install bzip2 and boost!
I'am not know cmake's Grammar rules。So...you know it!

CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:43 (message):
    Command failed: D:/Tools/Cmake/bin/cmake.exe;D:/ThridLibraryPackages/buildtrees/bzip2/src/bzip2-1.0.6;-DBUILD_SHARED_LIBS=ON;-DVCPKG_TARGET_TRIPLET=x86-windows;-DCMAKE_CXX_FLAGS= /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP ;-DCMAKE_C_FLAGS= /DWIN32 /D_WINDOWS /W3 /utf-8 /MP ;-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON;-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE;-DCMAKE_VERBOSE_MAKEFILE=ON;-DVCPKG_APPLOCAL_DEPS=OFF;-DCMAKE_TOOLCHAIN_FILE=D:/ThridLibraryPackages/scripts/buildsystems/vcpkg.cmake;-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON;-DCMAKE_CXX_FLAGS_RELEASE=/MD /O2 /Oi /Gy /DNDEBUG /Zi ;-DCMAKE_C_FLAGS_RELEASE=/MD /O2 /Oi /Gy /DNDEBUG /Zi ;-DCMAKE_SHARED_LINKER_FLAGS_RELEASE=/DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF ;-DCMAKE_EXE_LINKER_FLAGS_RELEASE=/DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF ;-G;Ninja;-DCMAKE_BUILD_TYPE=Release;-DCMAKE_INSTALL_PREFIX=D:/ThridLibraryPackages/packages/bzip2_x86-windows
    Working Directory: D:/ThridLibraryPackages/buildtrees/bzip2/x86-windows-rel
    See logs for more information:
      D:\ThridLibraryPackages\buildtrees\bzip2\config-x86-windows-rel-out.log
      D:\ThridLibraryPackages\buildtrees\bzip2\config-x86-windows-rel-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:170 (vcpkg_execute_required_process)
  ports/bzip2/portfile.cmake:18 (vcpkg_configure_cmake)
  scripts/ports.cmake:72 (include)

Error: Building package bzip2:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: bzip2:x86-windows
  Vcpkg version: 0.0.83

**Comment by atkawa7** [comment]
@God-Staff Could you upload the logs as well

**Comment by vmaks** [comment]
I have exactly the same issue.
I have Windows 10 x64 and Visual Studio 2017 (with VS 2015 as well).
I can't install any package.
Could you help me?
Thanks in advance!

```
vcpkg install sqlite3
The following packages will be built and installed:
    sqlite3:x86-windows
Building package sqlite3:x86-windows...
-- CURRENT_INSTALLED_DIR=C:/tmp-maks/vcpkg/installed/x86-windows
-- DOWNLOADS=C:/tmp-maks/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/tmp-maks/vcpkg/packages/sqlite3_x86-windows
-- CURRENT_BUILDTREES_DIR=C:/tmp-maks/vcpkg/buildtrees/sqlite3
-- CURRENT_PORT_DIR=C:/tmp-maks/vcpkg/ports/sqlite3/.
-- Using cached C:/tmp-maks/vcpkg/downloads/sqlite-amalgamation-3190100.zip
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Configuring x86-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:43 (message):
    Command failed: C:/tmp-maks/vcpkg/downloads/cmake-3.9.1-win32-x86/bin/cmake.exe;C:/tmp-maks/vcpkg/buildtrees/sqlite3/src/sqlite-amalgamation-3190100;-DSOURCE=C:/tmp-maks/vcpkg/buildtrees/sqlite3/src/sqlite-amalgamation-3190100;-DVCPKG_CMAKE_SYSTEM_NAME=;-DBUILD_SHARED_LIBS=ON;-DVCPKG_TARGET_TRIPLET=x86-windows;-DCMAKE_CXX_FLAGS= /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP ;-DCMAKE_C_FLAGS= /DWIN32 /D_WINDOWS /W3 /utf-8 /MP ;-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON;-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE;-DCMAKE_VERBOSE_MAKEFILE=ON;-DVCPKG_APPLOCAL_DEPS=OFF;-DCMAKE_TOOLCHAIN_FILE=C:/tmp-maks/vcpkg/scripts/buildsystems/vcpkg.cmake;-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON;-DCMAKE_CXX_FLAGS_RELEASE=/MD /O2 /Oi /Gy /DNDEBUG /Zi ;-DCMAKE_C_FLAGS_RELEASE=/MD /O2 /Oi /Gy /DNDEBUG /Zi ;-DCMAKE_SHARED_LINKER_FLAGS_RELEASE=/DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF ;-DCMAKE_EXE_LINKER_FLAGS_RELEASE=/DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF ;-G;Ninja;-DCMAKE_BUILD_TYPE=Release;-DCMAKE_INSTALL_PREFIX=C:/tmp-maks/vcpkg/packages/sqlite3_x86-windows
    Working Directory: C:/tmp-maks/vcpkg/buildtrees/sqlite3/x86-windows-rel
    See logs for more information:
      C:\tmp-maks\vcpkg\buildtrees\sqlite3\config-x86-windows-rel-out.log
      C:\tmp-maks\vcpkg\buildtrees\sqlite3\config-x86-windows-rel-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:170 (vcpkg_execute_required_process)
  ports/sqlite3/portfile.cmake:15 (vcpkg_configure_cmake)
  scripts/ports.cmake:72 (include)


Error: Building package sqlite3:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: sqlite3:x86-windows
  Vcpkg version: 0.0.83-cd7f4cccffd915edc2d4b625ff32dea970ec073f

Additionally, attach any relevant sections from the log files above.
```

**Comment by atkawa7** [comment]
@vmaks Could you rerun bootstrap?

**Comment by vmaks** [comment]
@atkawa7 I rerun a bootstrap, but it doesn't help.

I rerun the bootstrap with the following script:
```C:\src\vcpkg> .\bootstrap-vcpkg.bat```

**Comment by atkawa7** [comment]
@vmaks Could you upload the logs as well?

**Comment by vmaks** [comment]
@atkawa7 yes, I added my log files below.

config-x86-windows-rel-err.log
```CMake Error at C:/tmp-maks/vcpkg/downloads/cmake-3.9.1-win32-x86/share/cmake-3.9/Modules/CMakeTestCCompiler.cmake:51 (message):
  The C compiler "C:/Program Files (x86)/Microsoft Visual
  Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX64/x86/cl.exe" is
  not able to compile a simple test program.

  It fails with the following output:

   Change Dir: C:/tmp-maks/vcpkg/buildtrees/sqlite3/x86-windows-rel/CMakeFiles/CMakeTmp

  

  Run Build
  Command:"C:/tmp-maks/vcpkg/downloads/tools/ninja/ninja-1.7.2/ninja.exe"
  "cmTC_09891"

  ninja: error: build.ninja:30: loading 'rules.ninja': The system cannot find
  the file specified.

  

  include rules.ninja

                     ^ near here

  

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)



```

config-x86-windows-rel-out.log

```
-- The C compiler identification is MSVC 19.10.25019.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX64/x86/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX64/x86/cl.exe -- broken
-- Configuring incomplete, errors occurred!
See also "C:/tmp-maks/vcpkg/buildtrees/sqlite3/x86-windows-rel/CMakeFiles/CMakeOutput.log".
See also "C:/tmp-maks/vcpkg/buildtrees/sqlite3/x86-windows-rel/CMakeFiles/CMakeError.log".
```

**Comment by atkawa7** [comment]
@vmaks Could you comment this ` PREFER_NINJA` in you portfile. Its this line
https://github.com/Microsoft/vcpkg/blob/master/ports/sqlite3/portfile.cmake#L17

**Comment by vmaks** [comment]
@atkawa7 yes, it helps. Thank you very much!

However, I have the same issue with libpng, liblzma, libjpeg-turbo, tiff.
Could you fix the issue with "PREFER_NINJA" completely?

Could you also tell how to compile libraries with help of Visual Studio 2015 compiler in Visual Studio 2017. How to change the compiler in vcpkg?

**Comment by martin-s** [comment]
Create another triplet for your architecture, platform, complier and use it: `vcpkg install <port>:<triplet>`

**Comment by ras0219-msft** [comment]
Here's the documentation on triplets (including how to specify the compiler): https://github.com/Microsoft/vcpkg/blob/master/docs/users/triplets.md

**Comment by fcharlie** [comment]
@vmaks Can you tell me your console Codepage?

**Comment by ras0219-msft** [comment]
@fcharlie I think this is most likely due to the codepage issue as well, so I'll close this as a duplicate for now. We can open a new issue if this is still a problem after we fix our codepage handling.

**Comment by vmaks** [comment]
@fcharlie Excuse me for delay with answer.
Could you tell me how to check console Codepage?

**Comment by fcharlie** [comment]
@vmaks Open Console, type `chcp`, will show console codepage

**Comment by vmaks** [comment]
Console Codepage:
```Active code page: 866```

**Comment by Mixaill** [comment]
execute
```
chcp 65001
```
and try to install port

**Comment by vmaks** [comment]
@Mixaill yes, it works, thank you very much!

**Comment by alexkaratarakis** [comment]
Please report if the latest master fixes things for you.

**Comment by vmaks** [comment]
@alexkaratarakis, excuse me for delay with answer.
Yes, with the latest version everything works great!
