### ISSUE TITLE
[New Port Request] Blackbone

### ISSUE THREAD

**Issue by ViniDalvino** [microsoft/vcpkg#16452]
Library name:
BlackBone
Library description:
Windows memory hacking library
Source repository URL:
https://github.com/DarthTon/Blackbone
Project homepage (if different from the source repository):
Do not differ from source repository
Anything else that is useful to know when adding (such as optional features the library may have that should be included):
The library is windows only

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by ViniDalvino** [comment]
Why did the port request is unresolved ?
