### ISSUE TITLE
[poco] OpenSSL support incorrectly configured

### ISSUE THREAD

**Issue by kuriboshi** [microsoft/vcpkg#16456]
****

**Is your feature request related to a problem? Please describe.**
I think that the configuration for OpenSSL when enabling `netssl` is incorrect.  It turns on ENABLE_NETSSL_WIN which causes the NetSSL_Win library to be used.  This has an API which is different from what's documented in the pocoproject online documentation.  I don't know what the correct thing to do here but if `netssl` is supposed to use OpenSSL and now depends on the openssl port then I think it should not use NetSSL_Win.  It's possible that this is a new behavior since Poco 1.10.

**Proposed solution**
I think that `ENABLE_NETSSL_WIN` should be `OFF` and that `FORCE_OPENSSL` should be `ON` when the feature `netssl` is turned on.

**Describe alternatives you've considered**
If instead the `netssl` feature is supposed to really enable NETSSL_WIN on Windows then perhaps there should be a different feature called `openssl`.

**Additional context**
Not turning off `ENABLE_NETSSL_WIN` and leaving `FORCE_OPENSSL` to the default value of `OFF` leads to compilation errors in code which depends on the OpenSSL interface of the Poco NetSSL library.

**Comment by JackBoosY** [comment]
I think that's by design or a upstream bug, in https://github.com/pocoproject/poco/blob/master/CMakeLists.txt#L80-L87 :
```cmake
option(ENABLE_NETSSL_WIN "Enable NetSSL Windows" OFF)
option(FORCE_OPENSSL "Force usage of OpenSSL even under windows" OFF)

if(ENABLE_CRYPTO OR ENABLE_NETSSL OR ENABLE_JWT)
	find_package(OpenSSL REQUIRED)
else()
	find_package(OpenSSL)
endif()
```

**Comment by kuriboshi** [comment]
If it's an upstream bug it looks more like a documentation bug.  I think the `ENABLE_NETSSL` and `ENABLE_NETSSL_WIN` are mutually exclusive on Windows and it seems that the latter takes precedence over the former.  I need to investigate this some more.  NetSSL_OpenSSL and NetSSL_Win have a different API (mentioned in `NetSSL_Win/doc/README.txt`).  As it is now there is no way for the `poco` port in `vcpkg` to offer the NetSSL_OpenSSL API on Windows (or is there?) and I think that should either be the default of the `netssl` feature or at least an option.

The `poco` option `FORCE_OPENSSL` appears to do nothing so I think that removing `ENABLE_NETSSL_WIN` is enough.

**Comment by JackBoosY** [comment]
According to the option name in cmake, it is reasonable for this feature to be named netssl. I think the upstream has not done special treatment for names.
There are only a few things about netssl:
1. 
```cmake
	if((NOT POCO_DISABLE_INTERNAL_OPENSSL) AND (ENABLE_NETSSL OR ENABLE_CRYPTO OR (ENABLE_DATA_MYSQL AND MINGW)))
		include(UseEmbeddedOpenSSL)
	endif()
```
2.
```cmake
if(ENABLE_CRYPTO OR ENABLE_NETSSL OR ENABLE_JWT)
	find_package(OpenSSL REQUIRED)
endif()
```
3.
```cmake
if(ENABLE_NETSSL_WIN)
	set(ENABLE_UTIL ON CACHE BOOL "Enable Util" FORCE)
	if(ENABLE_TESTS)
		set(ENABLE_CRYPTO ON CACHE BOOL "Enable Crypto" FORCE)
	endif()
endif()
```
4.
```cmake
if(WIN32 AND EXISTS ${PROJECT_SOURCE_DIR}/NetSSL_Win AND ENABLE_NETSSL_WIN)
    message("use netssl win")
	add_subdirectory(NetSSL_Win)
	list(APPEND Poco_COMPONENTS "NetSSL_Win")
endif(WIN32 AND EXISTS ${PROJECT_SOURCE_DIR}/NetSSL_Win AND ENABLE_NETSSL_WIN)
```
5.
```cmake
if(OPENSSL_FOUND)
	if(EXISTS ${PROJECT_SOURCE_DIR}/NetSSL_OpenSSL AND ENABLE_NETSSL)
		add_subdirectory(NetSSL_OpenSSL)
		list(APPEND Poco_COMPONENTS "NetSSL_OpenSSL")
	endif()
	if(EXISTS ${PROJECT_SOURCE_DIR}/Crypto AND ENABLE_CRYPTO)
		add_subdirectory(Crypto)
		list(APPEND Poco_COMPONENTS "Crypto")
	endif()
endif(OPENSSL_FOUND)
```
According to the above code, I don’t think netssl conflicts with openssl.

**Comment by kuriboshi** [comment]
I agree on the name netssl since that's the terminology that Poco uses.

However, both the NetSSL_OpenSSL and NetSSL_Win directories contain header files which have the same name for both OpenSSL and Win.  See for example NetSSL_{OpenSSL,Win}/include/Poco/Net/Context.h.  They are different and only one of them gets installed.  Which one?  Is it deterministic?  I don't know.  In my project I got the Win version on Windows.  On Unix (not using vcpkg) I naturally use the OpenSSL version since that's the only option on Unix.  They are different, e.g. the Context::Context constructor takes different number of arguments depending on which one is chosen.

This is why I think choosing to set both ENABLE_NETSSL and ENABLE_NETSSL_WIN to ON on Windows leads to conflict.  This is also why I think it may be necessary to offer the choice between these two options.  Personally I'm not interested in anything other than the OpenSSL API even on Windows but others may want or need that.

**Comment by JackBoosY** [comment]
Sadly, according to our [policy](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#do-not-use-features-to-implement-alternatives), since these two features are in conflict, I have to disable them. 
If you need to use one of them, please use the overlay-port implementation. Please see [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/specifications/versioning.md#44-declaring-overrides).
