### ISSUE TITLE
Visual studio auto install

### ISSUE THREAD

**Issue by paveb85394** [microsoft/vcpkg#16469]
is there anyway in visual studio to make it automatically check if a pkg is installed if not install it from visual studio when it is opened or even at build time?

**Comment by autoantwort** [comment]
Yes, see [here](https://github.com/microsoft/vcpkg/blob/master/docs/users/manifests.md#msbuild-integration)

**Comment by PhoebeHui** [comment]
@paveb85394, please reopen this issue if it still be a question for you.
