### ISSUE TITLE
[scripts-audit] Rollup PR 2021-02-26 - cmake scripts not found #16440

### ISSUE THREAD

**Issue by StarGate-One** [microsoft/vcpkg#16463]
**Describe the bug**
- See PR #16440 vcpkg helper cmake port scripts not found
- Vcpkg appears to not know how to find the new portfile functions `vcpkg_cmake_build` `vcpkg_cmake_configure` `vcpkg_cmake_install` and `vcpkg_cmake_config_fixup` 

**Environment**
- OS: [Microsoft Windows [Version 10.0.19042.844]] 
        (I have not tested this on my Linux OpenSUSE 15.2 on WSL2 and Hyper-V)
- Compiler: 
  - Visual Studio 2017 Edition [Version 15.9.33]
    - Visual Studio Toolset [Version 14.16.27023]
    - Microsoft (R) C/C++ Optimizing Compiler [Version 19.16.27045 for x64]
  - Visual Studio 2019 Edition [Version 16.8.6]
    - Visual Studio Toolset [Version 14.28.29333]
    - Microsoft (R) C/C++ Optimizing Compiler [Version 19.28.29337 for x64]

**To Reproduce**
1. System default triplet is `x64-windows`
2. From Powershell Core 7.2 prompt with VS variables set
3.  `git pull`  updates vcpkg instance with PR #16640
4. Update local port(s) portfile.cmake to use new vcpkg CMake port helper functions from #16440 as the following messages are now present:
   - See attached: [New vcpkg CMake Deprecation Warnings.txt](https://github.com/microsoft/vcpkg/files/6058754/New.vcpkg.CMake.Deprecation.Warnings.txt)
5. `./vcpkg install vcpkg-cmake vcpkg-cmake-config --recurse --keep-going` installed successfully for x64-windows
6. `./vcpkg install [port]` - in this case a local copy of rapidstring as vcpkg no longer maintains the port
7. See error - console log only:
>PS D:\vcpkgMgr\2019\test> vcpkg install rapidstring
>Computing installation plan...
>The following packages will be built and installed:
>    rapidstring[core]:x64-windows -> 2018-08-03#1002
>Starting package 1/1: rapidstring:x64-windows
>Building package rapidstring[core]:x64-windows...
>-- Using cached D:/vcpkgMgr/2019/test/downloads/cenit-rapidstring-2a5fa4a42b37b00e1388f4161b1a96876e25b555.tar.gz
>-- Cleaning sources at D:/vcpkgMgr/2019/test/buildtrees/rapidstring/src/876e25b555-4a0d79fa33.clean. Use --editable to skip cleaning for the packages you specify.
>-- Extracting source D:/vcpkgMgr/2019/test/downloads/cenit-rapidstring-2a5fa4a42b37b00e1388f4161b1a96876e25b555.tar.gz
>-- Using source at D:/vcpkgMgr/2019/test/buildtrees/rapidstring/src/876e25b555-4a0d79fa33.clean
>CMake Error at ports/rapidstring/portfile.cmake:11 (vcpkg_cmake_configure):
>  **Unknown CMake command "vcpkg_cmake_configure".**
>Call Stack (most recent call first):
>scripts/ports.cmake:139 (include)
>
>Error: Building package rapidstring:x64-windows failed with: BUILD_FAILED
>Please ensure you're using the latest portfiles with `.\vcpkg update`, then
>submit an issue at https://github.com/Microsoft/vcpkg/issues including:
>  Package: rapidstring:x64-windows
>  Vcpkg version: 2021-01-13-8027bea90b47d50fd6090bbf5ded330f00f87570

**Expected behavior**
vcpkg should install port using new helper cmake port scripts

**Failure logs** 
-None - only console log shown above

**Additional context**
After install the ports vcpkg
- The new scripts are located  at these locations after install:
  - Port vcpkg-cmake-config
    - [vcpkg-root]\installed\x64-windows\share\vcpkg-cmake-config
    - [vcpkg-root]\packages\vcpkg-cmake-config_x64-windows\share\vcpkg-cmake-config
    - [vcpkg-root]\ports\vcpkg-cmake-config
  - Port vcpkg-cmake
    - [vcpkg-root]\installed\x64-windows\share\vcpkg-cmake
    - [vcpkg-root]\packages\vcpkg-cmake-config_x64-windows\share\vcpkg-cmake
    - [vcpkg-root]\ports\vcpkg-cmake
  - Vcpkg List showing x64-windows version of ports installed:
>PS D:\vcpkgMgr\2019\test> vcpkg list
>vcpkg-cmake-config:x64-windows                     2021-02-26
>vcpkg-cmake:x64-windows                            2021-02-26
>vcpkg-gfortran:x64-windows                         3                Metaport to install gfortran dependencies from m...
>vcpkg-gfortran:x86-windows                         3                Metaport to install gfortran dependencies from m...
>yasm-tool-helper:x64-windows                       2020-10-12       This port provides helper functions for ports ne...
>yasm-tool-helper:x86-windows                       2020-10-12       This port provides helper functions for ports ne...
>yasm-tool:x86-windows                              2020-10-12       A modular assembler. This port is intended to bu...

Note 1: Vcpkg.exe was built from the latest clone of microsoft/vcpkg-tool with CMake as of ~ 03/01/2021 01:45 UTC
Note 2: Downloaded [vcpkg.exe](https://github.com/microsoft/vcpkg-tool/releases/download/2021-02-24-d67989bce1043b98092ac45996a8230a059a2d7e/vcpkg.exe) with same results only difference is the sha commit string version Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e 
Note 3: Tried to install ports `vcpkg-cmake:x86-windows` and `vcpkg-cmake-config:x86-windows` in case it is like port `yasm-tool` which is only installed as x86-windows, but was not allowed to install x86-windows triplet with message: 
>PS D:\vcpkgMgr\2019\test> vcpkg install vcpkg-cmake vcpkg-cmake-config --triplet=x86-windows --recurse --keep-going
>Computing installation plan...
>warning: vcpkg appears to be in a Visual Studio prompt targeting x64 but is installing packages for x86-windows. Consider using --triplet x64-windows or --triplet x64-uwp.
>The following packages will be built and installed:
>    vcpkg-cmake[core]:x86-windows -> 2021-02-26
>    vcpkg-cmake-config[core]:x86-windows -> 2021-02-26
>Starting package 1/2: vcpkg-cmake:x86-windows
>Building package vcpkg-cmake[core]:x86-windows...
>CMake Error at ports/vcpkg-cmake/portfile.cmake:2 (message):
>  vcpkg-cmake is a host-only port; please mark it as a host port in your
  dependencies.
>Call Stack (most recent call first):
>  scripts/ports.cmake:139 (include)
>
>Error: Building package vcpkg-cmake:x86-windows failed with: BUILD_FAILED
>Elapsed time for package vcpkg-cmake:x86-windows: 712.7 ms
>Starting package 2/2: vcpkg-cmake-config:x86-windows
>Building package vcpkg-cmake-config[core]:x86-windows...
>CMake Error at ports/vcpkg-cmake-config/portfile.cmake:2 (message):
>  vcpkg-cmake-config is a host-only port; please mark it as a host port in
  your dependencies.
>Call Stack (most recent call first):
>  scripts/ports.cmake:139 (include)
>
>Error: Building package vcpkg-cmake-config:x86-windows failed with: BUILD_FAILED
>Elapsed time for package vcpkg-cmake-config:x86-windows: 32.85 ms

**Attached**
- Portfiles for local copy of `rapidstring`:
  - CMakeLists.txt: [CMakeLists.txt](https://github.com/microsoft/vcpkg/files/6058639/CMakeLists.txt)
  - portfile.cmake: [portfile.cmake.txt](https://github.com/microsoft/vcpkg/files/6058641/portfile.cmake.txt) with updates as follows:
    - vcpkg_install_cmake has been deprecated in favor of vcpkg_cmake_install
    - vcpkg_build_cmake has been deprecated in favor of vcpkg_cmake_build
    - vcpkg_fixup_cmake_targets has been deprecated in favor of  vcpkg_cmake_config_fixup
  - vcpkg.json: [vcpkg.json.txt](https://github.com/microsoft/vcpkg/files/6058642/vcpkg.json.txt)

**Comment by StarGate-One** [comment]
/cc: @strega-nil 
I forgot to cc you on this.
Thank you for all the hard work! 👍✨

**Comment by JackBoosY** [comment]
@strega-nil Seems you forgot to revert some files.

**Comment by strega-nil** [comment]
Hmm, right; the issue is that these deprecation warnings are only meant to be followed for people who are writing ports, not for people who are installing ports... @ras0219, any ideas?

**Comment by StarGate-One** [comment]
@strega-nil 
- In one respect, I was writing a port, a local one, one that is no longer maintained in vcpkg (which is beside the point), I was just getting a head start on converting my local ports over to use the new scripts, but yes the message first popped up after updating vcpkg with a `git pull` and then doing a `vcpkg remove` then `vcpkg install` of the ports changed, as it installed the 2 vcpkg-cmake ports first and then displayed the deprecation messages on the rest of the ports installed. So I tried to change a port over and learn how to use it.
- Another question I had was where should they be stored/installed? 
  - As the only common location was [vcpkg-root]\ports\vcpkg-cmake and [vcpkg-root]\ports\vcpkg-cmake-config.
  - The other 2 locations the scripts were installed was:
    - [vcpkg-root]\installed\x64-windows\share for the installed
    - [vcpkg-root]\packages\vcpkg-cmake-_x64-windows, [vcpkg-root]\packages\vcpkg-cmake-config_x64-windows  directories for the packages.
  - The reason I ask is after they were installed for x64-windows it would not allow installation for x86-windows which is unlike the vcpkg-gfortran port, which can be installed for both x64-windows and x86-windows if needed?
  
![image](https://user-images.githubusercontent.com/68293825/109556282-9ea87f00-7aa4-11eb-9b37-b39dfa6a2848.png)

Or are these installed once to a default triplet, then used by all triplets, like port yasm-tool?

**Comment by strega-nil** [comment]
@StarGate-One the point of these ports is that the user _should never_ be installing these on their own; they are only used as helpers. The whole point of them is that ports like this are supposed to replace the scripts tree for certain scripts. Therefore, the only "useful" way to use them is as a host port, since it's a tool.

**Comment by StarGate-One** [comment]
@strega-nil 
1. We did not install them, vcpkg did on both Windows and then both Linux installs on WSL2 and Hyper-V... A total of 8 vcpkg instances.
2. We did try to install the x86-windows which failed, when vcpkg could not find the x64-windows it did install.
3. Since we have local ports, which are not in the ports provided on the vcpkg repo (and never will since they are proprietary), we should not use the new scripts and stay with the old ones until they are deleted or should we convert our proprietary ports when vcpkg can see these scripts?
Thank you and have a wonderful evening, sorry if we have caused problems.

**Comment by StarGate-One** [comment]
Additional Information, it appears there are 3 ports already using the new cmake scripts:

>PS D:\vcpkgMgr\2017\prod> vcpkg remove vcpkg-cmake-config vcpkg-cmake
>The following packages will be removed:
>  * fmt:x64-windows
>  * shiva:x64-windows
>  * spdlog:x64-windows
>    vcpkg-cmake:x64-windows
>    vcpkg-cmake-config:x64-windows
>Additional packages (*) need to be removed to complete this operation.
>If you are sure you want to remove them, run the command with the --recurse option
>PS D:\vcpkgMgr\2017\prod>

**Comment by StarGate-One** [comment]
There is an additional deprecation about FEATURES keyword now:
>Starting package 8/9: spdlog:x64-windows
>Building package spdlog[benchmark,core]:x64-windows...
>-- Using cached D:/vcpkgMgr/2017/prod/downloads/gabime-spdlog-4a9ccf7e38e257feecce0c579a782741254eaeef.tar.gz
>-- Cleaning sources at D:/vcpkgMgr/2017/prod/buildtrees/spdlog/src/41254eaeef-61b213204a.clean. Use --editable to skip cleaning for the packages you specify.
>-- Extracting source D:/vcpkgMgr/2017/prod/downloads/gabime-spdlog-4a9ccf7e38e257feecce0c579a782741254eaeef.tar.gz
>-- Applying patch fix-featurebuild.patch
>-- Using source at D:/vcpkgMgr/2017/prod/buildtrees/spdlog/src/41254eaeef-61b213204a.clean
>CMake Deprecation Warning at scripts/cmake/vcpkg_check_features.cmake:182 (message):
  calling `vcpkg_check_features` without the `FEATURES` keyword has been
  deprecated.
>
>     Please add the `FEATURES` keyword to the call.
>Call Stack (most recent call first):
>  ports/spdlog/portfile.cmake:10 (vcpkg_check_features)
>  scripts/ports.cmake:139 (include)

We do set the environment variable `VCPKG_FEATURE_FLAGS` to **turn off** all the features we are not using:
`VCPKG_FEATURE_FLAGS=-binarycaching,-compilertracking,-manifests,-registries,-versions`
Does this mean to change our scripts to somehow other disable these features we do not want to use?

**Comment by strega-nil** [comment]
@StarGate-One alright, I'll answer your questions one at a time:

1. Yeah, correct
2. Don't try to install these yourself, they're just helper ports to be depended upon by other ports
3. Yes, you should switch to the new scripts if you have the time; you should depend on the `vcpkg-cmake` port as a host dependency (i.e., in `"dependencies"` of your vcpkg.json, you'd put `{ "name": "vcpkg-cmake", "host": true }`
4. yep, correct (technically, only `fmt` uses it, the other two depend on fmt)
5. these are for _port features_, not vcpkg's feature flags; spdlog uses the `vcpkg_check_features` function without the `FEATURES` keyword, which is now deprecated (but still works fine).

**Comment by StarGate-One** [comment]
@strega-nil Thanks,
We figured out the problem with the new scripts not found, we had to add the dependencies for them in the vcpkg.json file:
https://github.com/microsoft/vcpkg/blob/a44feca8c4167c9e2b7ff1d877053bc2a9ea8e9b/ports/fmt/vcpkg.json#L7-L16

Now we need to figure out how to convert:

vcpkg_fixup_cmake_targets(CONFIG_PATH share/cmake/rapidstring TARGET_PATH share/unofficial-rapidstring)
-to-
vcpkg_cmake_config_fixup()

Again I appreciate all of you alls hard work, really not just saying, but it is from the heart❤, the work is appreciated✨✔👏😊.

Yes I did figure out to not install them and let vcpkg install them when it figures out they are not installed, but are a dependency of a port you are installing. 😎

*Do you want me to close this or do you need it open for a while?*

**Comment by strega-nil** [comment]
@StarGate-One I say leave it open until we merge #16480
