### ISSUE TITLE
Failed to take the filesystem lock on /home/USER/vcpkg/.vcpkg-root, need to pkill curl to unlock

### ISSUE THREAD

**Issue by SoftwareApe** [microsoft/vcpkg#16476]
**Describe the bug**
When running vcpkg install it works (exit code 0). When running it again, it says:

`Failed to take the filesystem lock on /home/USER/vcpkg/.vcpkg-root`

**Environment**
- OS: Ubuntu 18.04
- Corporate Proxy

**To Reproduce**
Have an install only install local overlay ports and a corporate proxy blocking access to the outside internet. However vcpkg shouldn't need internet access for any of these if the resources are local.

1. ./vcpkg install
2. ./vcpkg install

**Expected behavior**
Lock is given up after install finishes.

**Failure logs** 
None

**Additional context**
1. Running `pkill curl` allows executing vcpkg again, but only once. `lsof curl | rg -i vcpkg` shows that curl seems to be hanging here and keeping the file system locked.
2. I did use `-disableMetrics` when bootstrapping vcpkg. So it shouldn't be any telemetrics. But maybe this flag is ignored.
3. vcpkg was built from latest tag:
```bash
$ vcpkg version
Vcpkg package management program version 2020.06.15-unknownhash
```

**Comment by JackBoosY** [comment]
@ras0219 @ras0219-msft Can you please take a look?

Thanks.

**Comment by SoftwareApe** [comment]
@JackBoosY I found out how to fix it locally. I forked and made a PR, starting from the last tag that I'm using as a base branch. I couldn't find the file in master. So maybe something changed here.

**Comment by SoftwareApe** [comment]
@JackBoosY I'm wondering a bit though that this curl call is called even though I build with `-disableMetrics`. It seems something here doesn't work.

**Comment by JackBoosY** [comment]
Will be fixed by https://github.com/microsoft/vcpkg-tool/pull/22.

**Comment by NancyLi1013** [comment]
Hi @SoftwareApe 

Since the new vcpkg tool has been released. This issue should be fixed now.
