### ISSUE TITLE
[hiredis] include path is broken

### ISSUE THREAD

**Issue by alexreinking** [microsoft/vcpkg#16474]
****

**Is your feature request related to a problem? Please describe.**
The `hiredis::hiredis` imported target (on `x64-linux`, at least) sets up the include paths to be the vcpkg install prefix (ie. `installed/x64-linux`), rather than `installed/x64-linux/include`, so builds using it fail to `#include <hiredis/hiredis.h>`.

**Proposed solution**
Fix the include paths with a patch or appropriate CMake settings. Upstream build fixes if possible.

**Describe alternatives you've considered**
Here's a hack to make things work a little better:

```
find_package(hiredis REQUIRED)

# vcpkg has broken include paths
find_path(hiredis_path hiredis REQUIRED)
target_include_directories(hiredis::hiredis INTERFACE "${hiredis_path}")
```

**Additional context**
N/A

**Comment by NancyLi1013** [comment]
Hi @alexreinking 

Thanks for posting this issue.

I submit a PR to fix this issue. Could you please help test if this can work for you?

Thanks.
