### ISSUE TITLE
[poco] build failure, Could NOT find ZLIB

### ISSUE THREAD

**Issue by acceleratxr** [microsoft/vcpkg#16484]
**Host Environment**
- OS: Windows
- Compiler: MSVC2019

**To Reproduce**
Create a cmake file with the following...
```
set(ZLIB_INCLUDE_DIR ${VCPKG_ROOT}/installed/${TRIPLET}/include)
if (MSVC)
  set(ZLIB_LIBRARY ${VCPKG_ROOT}/installed/${TRIPLET}/lib/zlib.lib)
else()
  set(ZLIB_LIBRARY ${VCPKG_ROOT}/installed/${TRIPLET}/lib/libz.a)
endif()

find_package(ZLIB REQUIRED)
find_package(OpenSSL REQUIRED)
find_package(Poco CONFIG REQUIRED COMPONENTS Foundation JSON Net Util)
```

**Failure logs** 
```
Total elapsed time: 41.9 us

The package openssl is compatible with built-in CMake targets:

    find_package(OpenSSL REQUIRED)
    target_link_libraries(main PRIVATE OpenSSL::SSL OpenSSL::Crypto)

The package poco:x86-windows-static provides CMake targets:

    find_package(Poco CONFIG REQUIRED)
    # Note: 9 target(s) were omitted.
    target_link_libraries(main PRIVATE Poco::Net Poco::XML Poco::Zip Poco::Data)

The package spdlog:x86-windows-static provides CMake targets:

    find_package(spdlog CONFIG REQUIRED)
    target_link_libraries(main PRIVATE spdlog::spdlog spdlog::spdlog_header_only)

The package zlib is compatible with built-in CMake targets:

    find_package(ZLIB REQUIRED)
    target_link_libraries(main PRIVATE ZLIB::ZLIB)

-- Found ZLIB: C:\Users\jpsaxr\vcpkg/installed/x86-windows-static/lib/zlib.lib (found version "1.2.11")
-- Found OpenSSL: C:/Users/jpsaxr/vcpkg/installed/x86-windows-static/lib/libcrypto.lib (found version "1.1.1i")
CMake Error at C:/Program Files/CMake/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find ZLIB (missing: ZLIB_INCLUDE_DIR) (found version "1.2.11")
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.18/Modules/FindZLIB.cmake:115 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  C:/Program Files/CMake/share/cmake-3.18/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  C:/Users/jpsaxr/vcpkg/installed/x86-windows-static/share/poco/PocoConfig.cmake:12 (find_dependency)
  CMakeLists.txt:114 (find_package)


-- Configuring incomplete, errors occurred!
See also "C:/Users/jpsaxr/gitlab/sdk_cpp/CMakeFiles/CMakeOutput.log".
See also "C:/Users/jpsaxr/gitlab/sdk_cpp/CMakeFiles/CMakeError.log".
```

**Comment by JackBoosY** [comment]
Please also add `-DVCPKG_TARGET_TRIPLET=x86-windows-static` to cmake options.

**Comment by JonLiu1993** [comment]
@acceleratxr ，Have you tried the advice @JackBoosY gave you?

**Comment by acceleratxr** [comment]
@JonLiu1993 @JackBoosY Yes I tried that. No difference.

**Comment by dg0yt** [comment]
The call stack indicates that you are using binary output from vcpkg, but not vcpkg's cmake toolchain. It would appear in the `find_package` call stack.

**Comment by JackBoosY** [comment]
You don't need the following code:
```cmake
set(ZLIB_INCLUDE_DIR ${VCPKG_ROOT}/installed/${TRIPLET}/include)
if (MSVC)
  set(ZLIB_LIBRARY ${VCPKG_ROOT}/installed/${TRIPLET}/lib/zlib.lib)
else()
  set(ZLIB_LIBRARY ${VCPKG_ROOT}/installed/${TRIPLET}/lib/libz.a)
endif()
```
Can you provide the full cmake options?

**Comment by acceleratxr** [comment]
I've put together a simple reproduction case for you to look at. It's available at:

https://github.com/acceleratxr/vcpkg-16484

**Comment by JackBoosY** [comment]
Will try to reproduce this issue tomorrow.

**Comment by JackBoosY** [comment]
1. You should use `find_package(Poco CONFIG COMPONENTS Foundation JSON Net ZIP DATA Util REQUIRED)`
2. You should run command `./vcpkg integrate install` and pass the cmake toolchain option in the output to cmake configure command line.
3. You should also pass `-DVCPKG_TARGET_TRIPLET=x86-windows-static` to cmake configure command line.

**Comment by acceleratxr** [comment]
It looks like adding ` -DVCPKG_TARGET_TRIPLET=x86-windows-static` was sufficient to get my build working. Thanks for the suggestion!

Also note using `./vcpkg integrate install` doesn't really work because I need this to function on a CI server, not just locally.

**Comment by acceleratxr** [comment]
OK this partially works. If I sync to the official tags it doesnt' work, but if I sync to HEAD it works.

**Comment by dg0yt** [comment]
In the current state of the repro, `CMAKE_TOOLCHAIN_FILE` is set too late. It must be done before the `project` command. And this implies that all vcpkg setup needs to go before the `project` command.

**Comment by acceleratxr** [comment]
> In the current state of the repro, `CMAKE_TOOLCHAIN_FILE` is set too late. It must be done before the `project` command. And this implies that all vcpkg setup needs to go before the `project` command.

Ah okay. I'll move that around. Thanks!
