### ISSUE TITLE
How do I use Qt in github workflows

### ISSUE THREAD

**Issue by m-kuhn** [microsoft/vcpkg#16485]
I have an application I would like to build in a ci, preferably github workflows. Among the dependencies is Qt.

I have tried to build it and it failed with qt5-declarative. I could go on and open an issue for this error, hopefully fix it and then live with the cached build until the next version update of qt.

Now I'm not particularly keen to burn cpu cycles and maintain this build, so before doing that I wondered if there are alternative supported ways.
For example using a precompiled system Qt and skip buildingqt5 packages in vcpkg?
Or maybe there is a public binary package cache somewhere? It seems this could be populated from the azure pipeline that is building all packages (with default features) in this repository already if I'm not wrong, maybe that could be extended for branches (I'm ignoring the complexity of dependencies here).
Other ideas?

Thank you very much.

**Comment by JackBoosY** [comment]
Please open a new issue to report the `qt5-declarative` build failure.

You can use two ways:
1. Build once and use the export command to export these packages, and then import the stored binary with the general command import during the CI process. See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/specifications/export-command.md).
2. Use the binary cache, automatically use the built ports. See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/users/binarycaching.md).

**Comment by m-kuhn** [comment]
Thanks for the reply @JackBoosY 

I am currently preparing a clean repository with reproducible steps to open a report. Once that's working, point 2. becomes interesting.
Point 1. could be interesting as a short term solution until the github workflow is fixed. I'm hesitating to introduce manual steps because of the maintenance burden. I am also not completely sure how to import it (but that's more of a documentation question, there's lots of export docs but I found almost nothing for import)

To finish this issue, is there any plans / discussions for hosting a set of precompiled (heavy) binaries to avoid having CIs and dev machines all over the world rebuilding the exact same packages?

**Comment by JackBoosY** [comment]
@m-kuhn Sorry but no, vcpkg only provides the build method and download address, and does not provide the source code and binary of the third-party library

**Comment by m-kuhn** [comment]
Does it make sense to open a new discussion with respect to this?

I assume there must have been similar discussion before somewhere but can't find anything.

**Comment by JackBoosY** [comment]
@m-kuhn  For qt5-declarative issue, please open a new one.
For binary cache, that's vcpkg policy. Sorry.

**Comment by m-kuhn** [comment]
> @m-kuhn For qt5-declarative issue, please open a new one.

On it, build takes ~1.5 hours to fail  when the log is there I'll open it.

> For binary cache, that's vcpkg policy. Sorry.

Nothing to be sorry about.

I can understand that Microsoft has such a policy, but if I'm not wrong the vcpkg system itself would technically allow for this with binary caching. And builds are passing on a CI (azure) so it seems there is just a little gap. This can be done from this repository under MS or a forked one.

My question would be where such a discussion would need to be started.

Thanks again !

**Comment by m-kuhn** [comment]
And here we go with the issue report: https://github.com/microsoft/vcpkg/issues/16495
