### ISSUE TITLE
Calls to find_dependency with package name 'glew' fail.

### ISSUE THREAD

**Issue by errata-c** [microsoft/vcpkg#16483]
**Describe the bug**
Calls to `find_dependency` with package name `glew` fail even when the library is installed.

**Environment**
- OS: Windows 10 64 bit, OS build 19042.804
- Compiler: MSVC 19.28.29337.0
- Vcpkg package management program version 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

**To Reproduce**
1. ./vcpkg install glew:x64-windows
2. call `find_dependency(glew)` in a package config file 
3. should report that dependency glew could not be found
OR
1. ./vcpkg install glew:x64-windows
2. call `find_package(glew)`
3. variable `glew_FOUND` will be undefined

**Expected behavior**
Call to `find_dependency(glew)` should succeed.

**Additional context**
I'm not entirely sure why this is happening, but I do know what the problem is. It seems that for some reason the call to 
`find_package(glew)` does not set `glew_FOUND`, but instead sets `GLEW_FOUND `. Both variations of the find_package call
do successfully find the package, but they only report under the package name GLEW. This is different from the behavior of 
of other libraries, for example `find_package(fmt)` sets `fmt_FOUND` and `find_package(FMT)` sets `FMT_FOUND`, in both 
instances correctly locating the library.

This is clearly not a serious issue, and even if it can't be fixed I'd like this issue report to exist in case someone else stumbles across the same issue.

**Comment by Cheney-W** [comment]
@errata-c 
Thanks for reporting this issue to us. About the Step #2: call find_dependency(glew) in a package config file, could you please provide us with a demo repro(cmake project)?

**Comment by errata-c** [comment]
Ok, I have a minimal [reproduction here](https://github.com/errata-c/find_dependency-glew.git), fails to build on my system.

**Comment by Cheney-W** [comment]
Thnanks for your reply. I could reproduce this issue in my side, and I'm trying to fix it. 
BTW, If you have any suggestions to fix this issue, please let me know. Thank you!

**Comment by errata-c** [comment]
I've managed to fix this issue on my end, but using a method I'm not sure is reliable. 
It seems the issue is in the `vcpkg-cmake-wrapper.cmake` file, inside that file there is a call to `_find_package` using the uppercase name `GLEW`. This explains why it always reported found with the upper case name. The way I fixed it was using the `${PACKAGE_NAME}` variable defined in the `find_package` function in `vcpkg.cmake`. However, I'm not sure if I can rely on this variable always being available. This also shows that its possible any other `vcpkg-cmake-wrapper.cmake` file could also have a hard-coded package name, and thus also have this exact same issue.

**Comment by errata-c** [comment]
In that case the fix could just be a simple `set(${PACKAGE_NAME}_FOUND ${GLEW_FOUND} PARENT_SCOPE)` right after the _find_package call.

**Comment by NancyLi1013** [comment]
@errata-c Thanks for looking into this issue.

I think the key point we discuss here is why we use `GLEW `here instead of how to fix it. As you can see here https://github.com/microsoft/vcpkg/pull/7967#issue-312273877.

@Neumann-A 
Could you please help comment something here?

Thanks.

**Comment by Neumann-A** [comment]
Just do:
`set(glew_FOUND ${GLEW_FOUND})` in the cmake wrapper?

**Comment by errata-c** [comment]
That will work for the lower case name. The cmake docs say that names in find_package calls will be treated as case-insensitive (https://cmake.org/cmake/help/latest/command/find_package.html#search-procedure). In order to support this, without changing anything else in the cmake wrapper, I recommend adding `set(${PACKAGE_NAME}_FOUND ${GLEW_FOUND})`. This guarantees the right name is reported back, not just the uppercase and lowercase. This will not  break anything in PR #7967.

**Comment by Neumann-A** [comment]
> The cmake docs say that names in find_package calls will be treated as case-insensitive

that is incorrect. This only applies to `<lowercasepackagename>-config.cmake`. Everything else will be case sensitive. 
So the question here is does glew install its own config as  `glew-config.cmake`.

**Comment by errata-c** [comment]
You can try it yourself, call find_package with a random set of upper and lower case letters for a package name. It works, I just tried it since you made me doubt myself. While yes, the config file can only be one of two forms, the find_package function is much more lenient. The docs I just linked say: "In all cases the <name> is treated as case-insensitive and corresponds to any of the names specified (<PackageName> or names given by NAMES)."

**Comment by Neumann-A** [comment]
> You can try it yourself, call find_package with a random set of upper and lower case letters for a package name. It works, I just tried it since you made me doubt myself. While yes, the config file can only be one of two forms, the find_package function is much more lenient. The docs I just linked say: "In all cases the is treated as case-insensitive and corresponds to any of the names specified ( or names given by NAMES)."

Platform? Probably Windows or WSL

**Comment by errata-c** [comment]
Okay, I've tried it on Windows 10, and Ubuntu 5.8.0. Works on both.

**Comment by errata-c** [comment]
Sorry, I misinterpreted what you meant by "This only applies to <lowercasepackagename>-config.cmake. Everything else will be case sensitive." I assumed you were talking about the naming required for package config files themselves. After reading the CMake source (https://github.com/Kitware/CMake/blob/master/Source/cmFindPackageCommand.cxx lines 625 to 629) I see what you mean. It just so happens that all the packages I tried were the `<lowercasepackagename>-config.cmake` variety. Regardless, looking the installed package files for glew, it does have a `glew-config.cmake`, so using `set(${PACKAGE_NAME}_FOUND ${GLEW_FOUND})` is still valid.

**Comment by Neumann-A** [comment]
you mean: `set(${CMAKE_FIND_PACKAGE_NAME}_FOUND ${GLEW_FOUND})`

**Comment by errata-c** [comment]
Well the cmake wrapper calls the actual find_package function internally, which changes the CMAKE_FIND_PACKAGE_NAME variable. The PACKAGE_NAME variable defined by vcpkg itself is still valid at that point.

**Comment by JackBoosY** [comment]
If you use the module mode in `find_package`, according to the cmake [docs](https://cmake.org/cmake/help/latest/module/FindGLEW.html), you should use `find_package(GLEW REQUIRED)`, please note the upper-case.
And, the var `GLEW_FOUND` is set to `ON` when glew was found.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. This issue hasn’t been updated in five months. Please reopen this issue if this is still a problem for you.
