### ISSUE TITLE
Error: Building package cudnn:x86-windows failed with BUILD_FAILED

### ISSUE THREAD

**Issue by annie14dec** [microsoft/vcpkg#16498]
Package: cudnn:x86-windows
 Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

Please help!

**Comment by NancyLi1013** [comment]
Hi @annie14dec 

Thanks for posting this issue.

Since currently, cudnn only supports `x64 `architecture, please try to build `cudnn:x64-windows`.

**Comment by NancyLi1013** [comment]
```
if(NOT VCPKG_TARGET_ARCHITECTURE STREQUAL "x64")
  message(FATAL_ERROR "This port is only for x64 architectures")
endif()
```

Closing this issue for now. Since this is intend behavior.
