### ISSUE TITLE
[qt5-declarative] build failure on github workflows

### ISSUE THREAD

**Issue by m-kuhn** [microsoft/vcpkg#16495]
**Host Environment**
- OS: [Windows Server 2019](https://github.com/actions/virtual-environments/blob/win19/20210219.1/images/win/Windows2019-Readme.md#microsoft-windows-server-2019-datacenter)
- Compiler: [16.8.31005.135](https://github.com/actions/virtual-environments/blob/win19/20210219.1/images/win/Windows2019-Readme.md#visual-studio-enterprise-2019)

**To Reproduce**

https://github.com/m-kuhn/qt-for-vcpkg/blob/2c54305c5dd587a53e354377698d940f3925792e/.github/workflows/build.yaml#L31-L34

**Failure logs** 

```
CMake Error at D:/a/qt-for-vcpkg/qt-for-vcpkg/scripts/cmake/vcpkg_execute_build_process.cmake:144 (message):
    Command failed: V:/downloads/tools/jom/jom-1.1.3/jom.exe -j 3
```

https://github.com/m-kuhn/qt-for-vcpkg/runs/2011231880?check_suite_focus=true

More logs coming soon, build running here: https://github.com/m-kuhn/qt-for-vcpkg/runs/2011946737?check_suite_focus=true

**Additional context**

The github workflow checks out the latest vcpkg source creates a `subst` on `V:` to avoid any potential long path issues and installs `qt5-declarative`.

**Comment by JackBoosY** [comment]
Can you please provide full failure logs?
_V:\buildtrees\qt5-declarative\package-build-x64-windows-dbg-out.log_
_V:\buildtrees\qt5-declarative\package-build-x64-windows-dbg-err.log_

Thanks.

**Comment by m-kuhn** [comment]
More logs coming soon, build running here: https://github.com/m-kuhn/qt-for-vcpkg/runs/2011946737?check_suite_focus=true

**Comment by m-kuhn** [comment]
This seems conclusive:

```
..\..\include\QtQuickParticles\QtQuickParticlesDepends(8): fatal error C1085: Cannot write precompiled header file: '.pch\debug\Qt5QuickParticlesd_pch.pch': There is not enough space on the disk.
```

https://github.com/m-kuhn/qt-for-vcpkg/runs/2011946737?check_suite_focus=true#step:8:1169

I'll try to cleanup some space by removing build folders

**Comment by m-kuhn** [comment]
(as a side effect, I hope this helps as an illustration why prebuilt packages would be desirable, this could free up development resources for other tasks)

**Comment by m-kuhn** [comment]
Moving the build to the C: drive with more space fixes the build.

**Comment by JackBoosY** [comment]
@m-kuhn Please note qt5 doesn't support long path and will take huge space.

**Comment by m-kuhn** [comment]
For future reference

- Currently there are [~12GB of space on drive D: (default build drive) and ~85GB of space on drive C: (writable as well)](https://github.com/m-kuhn/qt-for-vcpkg/runs/2019697487?check_suite_focus=true#step:2:1).
- [Long paths are enabled](https://github.com/m-kuhn/qt-for-vcpkg/runs/2019697487?check_suite_focus=true#step:3:1)
- We can build in a folder like `C:\src`
