### ISSUE TITLE
[New Port Request] onnxruntime (CPU version)

### ISSUE THREAD

**Issue by duanqn** [microsoft/vcpkg#16509]
Library name:
onnxruntime
Library description:
ONNX Runtime is a cross-platform inference and training machine-learning accelerator compatible with deep learning frameworks, PyTorch and TensorFlow/Keras, as well as classical machine learning libraries such as scikit-learn, and more.
Source repository URL:
https://github.com/Microsoft/onnxruntime
Project homepage (if different from the source repository):
https://www.onnxruntime.ai/
Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by luncliff** [comment]
Probably #14903 ?

**Comment by duanqn** [comment]
@luncliff  You're right. Let me close this issue.
