### ISSUE TITLE
Wrong host triplet for arm macs

### ISSUE THREAD

**Issue by autoantwort** [microsoft/vcpkg#16504]
**Describe the bug**
Use the `arm64-osx` triplet as host triplet on arm Apple Computers

**Environment**
- OS: macOS with Apple M1

**To Reproduce**
Install port with `host` dependencies

**Expected behavior**
Use the `arm64-osx` triplet as host triplet on arm devices

The responsible code can be found [here](https://github.com/microsoft/vcpkg-tool/blob/8027bea90b47d50fd6090bbf5ded330f00f87570/src/vcpkg/triplet.cpp#L89)

**Comment by strega-nil** [comment]
@autoantwort could you try the tool from https://github.com/microsoft/vcpkg-tool/pull/23?

**Comment by autoantwort** [comment]
Yes that works now. (But) it will also change the default triplet, but I think it is a good idea to make the `arm64-osx` triplet the default triplet on arm macs. But you should definitely consider to make `arm64-osx` an official triplet.

**Comment by strega-nil** [comment]
We want to make it official, but we need to add testing for it.

**Comment by ras0219-msft** [comment]
As a workaround, you can set `VCPKG_HOST_TRIPLET` as an environment variable or pass `--host-triplet=` on the command line to change which triplet to use as the host.
