### ISSUE TITLE
Script that check new version of ports from GitHub

### ISSUE THREAD

**Issue by KindDragon** [microsoft/vcpkg#1651]
JFYI https://gist.github.com/KindDragon/0312346f8d2cc70d52d12e5c69188d73

Script result: https://gist.github.com/KindDragon/97a424b03a56ccb4cc74e44f5072bd93

**Comment by alexkaratarakis** [comment]
Wow, this is great! 💯

**Comment by LilyWangL** [comment]
This issue hasn’t been updated in a year, if it is still an issue, please reopen.
