### ISSUE TITLE
uwp app using libxml2 can't launch.

### ISSUE THREAD

**Issue by HppZ** [microsoft/vcpkg#16529]
**Describe the bug**
uwp app using libxml2 can't launch.
I have libxml2:x64-uwp 2.9.10#2 installed using vcpkg.
repo to reproduce the bug: https://github.com/HppZ/libxml2-uwp
 
**Environment**
- OS: [Windows 19042.844]
- Compiler: vs2019 16.8.6

**To Reproduce**
1.  vcpkg install libxml2 --triplet=x64-uwp
2. run the libxml2-uwp app and it **can't** launch.
https://github.com/HppZ/libxml2-uwp
3. comment out the call `xmlNewTextWriterFilename("test", 1);` , **rebuild** the app and run again, it **can** launch.

**Expected behavior**
the app should launch.

**Failure logs** 
Unable to activate Windows Store app '1a2ed2c1-b8c3-4a00-ab03-f5d6312dc55e_kmdshx21vdgze!App'. The App5.exe process started, but the activation request failed with error 'The target process aborted before activation completed. More information may be available in the Debug pane of the Output window (Debug->Windows->Output)'.

**Comment by HppZ** [comment]
@JackBoosY PLEASE help.

**Comment by JackBoosY** [comment]
I can't repro your issue on my local machine:
![image](https://user-images.githubusercontent.com/47264268/110090084-daf41c00-7dd1-11eb-989d-dd64f613a899.png)

**Comment by HppZ** [comment]
I was on master branch.
show I use the latest tag in production env?

**Comment by JackBoosY** [comment]
@HppZ I'm on latest master too.
Can you provide me the full logs?

**Comment by HppZ** [comment]
[libxml2.zip](https://github.com/microsoft/vcpkg/files/6089992/libxml2.zip)

**Comment by HppZ** [comment]
BTW, I was on master (c47216ac7904b09187c119c7e4d010dcf993e3d5).

**Comment by HppZ** [comment]
Vcpkg package management program version 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e
new log: [libxml2.zip](https://github.com/microsoft/vcpkg/files/6090058/libxml2.zip)

**Comment by HppZ** [comment]
I think maybe your local binary is OK so that you can't repro this issue.

**Comment by HppZ** [comment]
building libxml2:x64-uwp succeed on tags/2020.11-1, but apps using it can't pass WACK test.
build libxml2:x86-uwp failed on on tags/2020.11-1.
https://github.com/microsoft/vcpkg/pull/368

**Comment by JackBoosY** [comment]
@HppZ No, I use the latest generated libxml2.

**Comment by HppZ** [comment]
that is strange.

**Comment by JackBoosY** [comment]
Please provide more information in Debug->Windows->Output.

**Comment by HppZ** [comment]
https://github.com/microsoft/vcpkg/pull/15787

**Comment by HppZ** [comment]
Can I contact you personally? my email: haopengzi@outlook.com

**Comment by HppZ** [comment]
check this output: https://github.com/microsoft/vcpkg/pull/15787#issuecomment-791884690

**Comment by HppZ** [comment]
vcpkg install libxml2 --triplet=x64-uwp
on vcpkg master commit c47216ac7904b09187c119c7e4d010dcf993e3d5
binaries:
[x64-uwp.zip](https://github.com/microsoft/vcpkg/files/6095115/x64-uwp.zip)

**Comment by HppZ** [comment]
![image](https://user-images.githubusercontent.com/12285582/110202635-0ac02400-7ea5-11eb-8385-a2336d9b1c02.png)

**Comment by HppZ** [comment]
vcpkg install libxml2 --triplet=x86-uwp
c47216ac7904b09187c119c7e4d010dcf993e3d5
[App5.zip](https://github.com/microsoft/vcpkg/files/6098842/App5.zip)

**Comment by JackBoosY** [comment]
Confirmed.
