### ISSUE TITLE
Missing include in libharu

### ISSUE THREAD

**Issue by albertziegenhagel** [Microsoft/vcpkg#1652]
The `libharu` port does not install a header `hpdf_config.h` that is referenced in `hpdf.h`.

This header is configured and put into the directories for `${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-rel\include` and `${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-deb`. The problem is that the release and the debug version are different: The debug version defines the macro `LIBHPDF_DEBUG` while the release version does not.

**Comment by atkawa7** [comment]
@albertziegenhagel My assumption was this would pick it up. 

https://github.com/Microsoft/vcpkg/blob/master/ports/libharu/portfile.cmake#L37

I will look at it

**Comment by albertziegenhagel** [comment]
I think you can not use `CMAKE_BINARY_DIR` in the portfile. You should use either `${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-rel` or `${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-dbg` (don't know whether there are shorter variables defined for that).

Nevertheless the issue with the `LIBHPDP_DEBUG` macro remains.

**Comment by Mixaill** [comment]
`${CMAKE_BINARY_DIR}` for portfile points to `vcpkg.exe` location

**Comment by atkawa7** [comment]
@albertziegenhagel  what are you thoughts on disabling it

**Comment by atkawa7** [comment]
@albertziegenhagel see #1658

**Comment by albertziegenhagel** [comment]
I had a quick look into what that macro actually controls and it seems that it really just enables some more debug output, so I think it is more indented to be used when developing libharu itself.

So just disabling it seems to be the right thing to do in my opinion.
