### ISSUE TITLE
[New Port Request] <MPV>

### ISSUE THREAD

**Issue by pengguoqing** [microsoft/vcpkg#16524]
Library name:
mpv

Library description:
Media player plugin

Source repository URL:
https://github.com/mpv-player/mpv

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
Develop player in windows

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by Chaojimengnan** [comment]
@PhoebeHui Hi, Could you please add the port for libmpv ? My project requires this library

**Comment by capric8416** [comment]
I have opened a pull request to add libmpv port https://github.com/microsoft/vcpkg/pull/40587

**Comment by sfhacker** [comment]
This is from 2021! God save us all!
