### ISSUE TITLE
[boost-locale:x64-android] build failure

### ISSUE THREAD

**Issue by w-Yuan** [microsoft/vcpkg#16521]
Package: boost-locale:x64-android
  Vcpkg version: 2020.06.15-nohash

CMake Error at installed/x64-android/share/boost-build/boost-modular-build.cmake:149 (message):
  **No libraries were produced.  This indicates a failure while building the boost library.**
Call Stack (most recent call first):
  ports/boost-locale/portfile.cmake:14 (boost_modular_build)
  scripts/ports.cmake:135 (include)

Let me know if more information is needed. Thanks!

**Comment by Cheney-W** [comment]
This issue has not been updated for over 3 months, so if it is still an issue, please reopen the issue.
