### ISSUE TITLE
[New Port Request] XQuilla

### ISSUE THREAD

**Issue by christophe-calmejane** [microsoft/vcpkg#16531]
**Library name:**
XQuilla

**Library description:**
XQilla is an XQuery∞ and XPath 2∞ library and command line utility written in C++, implemented on top of the Xerces-C∞ library. It is made available under the terms of the Apache License v2.

**Source repository URL:**
https://sourceforge.net/p/xqilla/xqilla/ci/default/tree/
(hg clone http://hg.code.sf.net/p/xqilla/xqilla xqilla-xqilla)

**Project homepage (if different from the source repository):**
http://xqilla.sourceforge.net/HomePage

The latest version is 2.3.4

**Comment by christophe-calmejane** [comment]
Looks like there was a request for that a long time ago (#12313) I don't know why it didn't show in the search results.
Anyway, this port would be a nice addition with minimal support as this library is not evolving much.

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
