### ISSUE TITLE
CMake cannot find target "unofficial::sqlite3::sqlite3" when using port poco[sqlite3]

### ISSUE THREAD

**Issue by fishnet37222** [microsoft/vcpkg#16538]
**Describe the bug**
I'm using a manifest to specify the dependencies for my CMake project.  One of the dependencies is "poco[sqlite3]" specified using the correct manifest syntax.  In my CMakeLists.txt file, I've used the usual `find_package()` and `target_link_libraries()` commands to find and link to "poco[sqlite3]".  When I configure the project, I get the following error from CMake:  `Target "fnirc" links to target "unofficial::sqlite3::sqlite3" but the target was not found.  Perhaps a find_package() call is missing for an IMPORTED target, or an ALIAS target is missing?`

**Environment**
- OS: Arch Linux
- Compiler: GCC 10.2.0

**To Reproduce**
1. Create a CMake project with a vcpkg manifest that specifies "poco[sqlite3]" as a dependency.
2. Configure the project.

**Expected behavior**
CMake finds Poco along with all of its dependencies.

**Failure logs** 
No logs generated.

**Comment by fishnet37222** [comment]
I can verify that this issue also occurs on Windows.
![2021-03-04_18-24-39](https://user-images.githubusercontent.com/1977106/110044352-fd752f00-7d16-11eb-8302-9700ffcbb392.png)

**Comment by NancyLi1013** [comment]
Hi @fishnet37222 

Thanks for posting this issue.

Since it still uses `SQLite3 `instead of `unofficial-sqlite3` in Data/SQLite/cmake/PocoDataSQLiteConfig.cmake.

So just need to update the package name.

```
-	find_dependency(SQLite3 REQUIRED)
+	find_dependency(unofficial-sqlite3 REQUIRED)
```

I have submitted a PR #16549 to fix it. It should work now.
