### ISSUE TITLE
[wxWidgets] Using static triplet fails because of missing png.lib

### ISSUE THREAD

**Issue by brad-anderson** [microsoft/vcpkg#16543]
**Describe the bug**
The cmake wrapper for wxWidgets expects libpng to always be called `png.lib` but it is not on static triplets so it fails to find the library to link when you try to use wxWidgets.

**Environment**
- OS: Windows
- Compiler: cl.exe 19.28.29910

**To Reproduce**
1. ./vcpkg install wxwidgets:x64-windows-static
2. Try to use wxWidgets from your own statically linked project via CMake

**Expected behavior**
Successful linking

**Failure logs** 
    fatal error LNK1104: cannot open file 'png.lib'

**Additional context**
libpng's library for static triplets is called `png_static` so using `png` won't work.

I have a pull request ready that I will add after filing this issue.

**Comment by JackBoosY** [comment]
In `libpng-targets.cmake`:
```cmake
...
# Create imported target png_static
add_library(png_static STATIC IMPORTED)
...
```

In `libpng-targets-debug.cmake`:
```cmake
...
set_target_properties(png_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/debug/lib/libpng16d.lib"
  )

list(APPEND _IMPORT_CHECK_TARGETS png_static )
list(APPEND _IMPORT_CHECK_FILES_FOR_png_static "${_IMPORT_PREFIX}/debug/lib/libpng16d.lib" )
...
```

So I don't think that have some problems.
And also, I can't repro this issue.

Can you please make sure your vcpkg is latest?

Thanks.

**Comment by JackBoosY** [comment]
Oh I know that, that's a usage issue.
in `vcpkg-cmake-wrapper.cmake`:
```cmake
...
if(wxWidgets_LIBRARIES AND NOT wxWidgets_LIBRARIES MATCHES "TIFF::TIFF;png;expat::expat;ZLIB::ZLIB")
    list(APPEND wxWidgets_LIBRARIES "TIFF::TIFF;png;expat::expat;ZLIB::ZLIB")
endif()
...
```

**Comment by brad-anderson** [comment]
Yes, my vcpkg is at the latest. Yes, it's an issue with the way wxWidgets references libpng (the library name isn't the same between static and dynamic builds of it so you can't use it for both).

Alternatively the wrapper could be updated to change the libpng library name conditional on linkage but that's doesn't seem necessary when there is a perfectly good CMake PNG::PNG target to use (and is what the other libraries wxWidgets depends on are all doing already).

**Comment by JackBoosY** [comment]
@brad-anderson  Fixing...
