### ISSUE TITLE
[Crashpad] Does not expose handler exe target

### ISSUE THREAD

**Issue by ilia-glushchenko** [microsoft/vcpkg#16542]
****

**Is your feature request related to a problem? Please describe.**
Hello everyone. Good day to you. 
If I understand correctly there is no easy way to get access to crashpad_handler executable target with the current version crashpadConfig file. Or at least I don't see one. This is really frustrating if you want to configure a build system to ship the handler with the build without some `find` tricks.

**Proposed solution**
Expose handler target to users. So we could use CMake to copy the executable. 

**Describe alternatives you've considered**
I can access the executable via VCPKG `installed\<triplet-name>\tools` folder but this looks more like a workaround to me.

**Additional context**
The whole idea of the crashpad is having an out-of-process handler of crashes. Really hard to use it if I can't even get access to it from my CMakeLists.txt. 
Please see for more info:
`vcpkg/ports/crashpad/crashpadConfig.cmake.in`
`vcpkg/ports/crashpad/portfile.cmake`
 Look for the `handler` target.  

If I missed something. Or just don't know how to properly use CMake, please let me know :)
Thanks!

**Comment by JackBoosY** [comment]
Hi @ilia-glushchenko, sorry for late.
I think you should use `find_program` to find crashpad executable, and use feature `X_VCPKG_APPINSTALL_DEPS_INSTALL` to copy it.
See https://github.com/microsoft/vcpkg/pull/14243.

**Comment by ilia-glushchenko** [comment]
Okay. Thanks for the reply.

**Comment by JackBoosY** [comment]
@ilia-glushchenko Please reopen this issue if you have other questions.
