### ISSUE TITLE
Are graphics.h and iostream.h included?

### ISSUE THREAD

**Issue by g-e-o-m-e-t-r-i-c** [microsoft/vcpkg#16541]
When asking a question please also include where you looked for an answer (so we can update the documentation if needed).

**Comment by Cheney-W** [comment]
Sorry, I don't quite understand what you mean. Do you want to ask whether vcpkg can provide these two header files or whether vcpkg uses these two header files when developing vcpkg?

**Comment by g-e-o-m-e-t-r-i-c** [comment]
I was asking whether vcpkg can provide these two header files. Thank you!

**Comment by vicroms** [comment]
Hi @g-e-o-m-e-t-r-i-c ,

The `iostream.h` header is part of the standard library headers, there is no need to use vcpkg to acquire it. In modern C++ you include `#include <iostream>` (without the `.h`). The other one, `graphics.h`, isn't a standard header. Most likely you are referring to the [very antiquated header included with the Borland compiler](https://stackoverflow.com/questions/7860569/how-i-can-get-and-use-the-header-file-graphics-h-in-my-c-program).

I'm not sure whether a library in vcpkg offers a drop-in replacement, but there are plenty of [graphic libraries that are already available as ports](https://vcpkgx.com/?search=graphics), I suggest you take a look at any of those instead.

If you are new to C++, I would also suggest joining the [#includecpp Discord](https://www.includecpp.org/discord/) and ask things in the learning channels. There's a lot of folks there that will be happy to help you.
