### ISSUE TITLE
How do I find a port's dependency in its portfile ?

### ISSUE THREAD

**Issue by tlestang** [microsoft/vcpkg#16554]
Hi there,

I'm adding a feature to the [current port for sundials](https://github.com/microsoft/vcpkg/tree/master/ports/sundials), which would allow the build of sundials with the "KLU" solver enabled. In practice this makes the build dependent on another library, SuiteSparse, which provides the KLU solver. Thankfully, SuiteSparse is already [available through vcpkg](https://github.com/microsoft/vcpkg/tree/master/ports/suitesparse).

To build sundials with KLU enabled, I must pass the location the SuiteSparse headers and libraries, for instance:
```cmake
if ("klu" IN_LIST FEATURES)
  set(ENABLE_KLU ON)
  set(KLU_INCLUDE_DIR <location suitesparse headers>)
  set(KLU_LIBRARY_DIR <location of suitesparse libraries)
endif()

vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA
    OPTIONS 
        -DENABLE_KLU=${ENABLE_KLU}
        -DKLU_INCLUDE_DIR=${KLU_INCLUDE_DIR}
        -DKLU_LIBRARY_DIR=${KLU_LIBRARY_DIR}
        # ...
)
```
In this context, SuiteSparse is a dependency of sundials and is therefore installed by vcpkg before configuring the sundials build:
```json
{
    "name": "sundials",
    "description": "SUNDIALS (SUite of Nonlinear and DIfferential/ALgebraic equation Solvers)",
    ...
    "features": {
	"klu": {
	    "description": "KLU support for SUNDIALS",
	    "dependencies": ["suitesparse"]
	}
    }
}
```
**My question is**: how do I set `KLU_INCLUDE_DIR` and `KLU_LIBRARY_DIR` ? In other words, how do I "find" (in CMake sense) SuiteSparse in sundials' portfile?

Looking at various portfiles, I figured something along those lines could work:
```cmake
set(KLU_LIBRARY_DIR ${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/lib)
```
Unfortunately, the variable `VCPKG_TARGET_TRIPLET` doesn't seem to be defined at this stage, but rather later, in the `vcpkg_configure_cmake` function.

What is the best way to find a port's dependency in its own portfile?

**Comment by JackBoosY** [comment]
1. You can view the dependencies from CONTROL or vcpkg.json.
2. Modify the source code and add code to find these directories or files (make a patch to appy it).

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
