### ISSUE TITLE
[libmysql] CMake warning about ncurses requirement on Linux

### ISSUE THREAD

**Issue by fishnet37222** [microsoft/vcpkg#16555]
**Host Environment**
- OS: [Linux Mint]
- Compiler: gcc 9.3.0

**To Reproduce**
`./vcpkg install poco[mysql]`

**Warning logs** 
```
Starting package 1/3: libmysql:x64-linux
Building package libmysql[core]:x64-linux...
CMake Warning at ports/libmysql/portfile.cmake:8 (message):
  libmysql needs ncurses on LINUX, please install ncurses first.

  On Debian/Ubuntu, package name is libncurses5-dev, on Redhat and derivates
  it is ncurses-devel.
Call Stack (most recent call first):
  scripts/ports.cmake:139 (include)
```

**Additional context**
I already have libncurses5-dev installed as shown below:
```
dave [ ~ ]
% sudo apt install libncurses5-dev        
[sudo] password for dave:           
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libncurses5-dev is already the newest version (6.2-0ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

The package seems to build fine otherwise.

**Comment by NancyLi1013** [comment]
Hi @fishnet37222 

Thanks for posting this issue.

This is expected. Since we added this message on Linux for `libmysql`. Adding this message is just to reminder users when installing this port. You can ignore this information if you have installed the library.

Please see 

```
if (VCPKG_TARGET_IS_LINUX)
    message(WARNING "${PORT} needs ncurses on LINUX, please install ncurses first.\nOn Debian/Ubuntu, package name is libncurses5-dev, on Redhat and derivates it is ncurses-devel.")
endif()
```

https://github.com/microsoft/vcpkg/blob/master/ports/libmysql/portfile.cmake#L7-L9

**Comment by NancyLi1013** [comment]
Closing this issue for intend behavior. Please feel free to reopen this if it is still a problem for you.

Thanks.
