### ISSUE TITLE
Is the CUDA ToolKit - Cuda Runtime api available?

### ISSUE THREAD

**Issue by Goru1890** [microsoft/vcpkg#16571]
Is the CUDA ToolKit - Cuda Runtime api available on vcpkg?
I  need the [cuda runtime API lib](https://docs.nvidia.com/cuda/cuda-runtime-api/index.html)

**Comment by NancyLi1013** [comment]
Hi @Goru1890 

Thanks for posting this issue.

Currently, there is only CUDA driver in vcpkg. Please see https://github.com/microsoft/vcpkg/tree/master/ports/cuda

You can request to add a new port for CUDA runtime API if you are required this.

**Comment by NancyLi1013** [comment]
Closing this issue for now. Please open a new issue if you still have the request to add Cuda Runtime api as a new port.
