### ISSUE TITLE
[New Port Request] <Cuda runtime API>

### ISSUE THREAD

**Issue by Goru1890** [microsoft/vcpkg#16588]
Library name: Cuda Runtime API

Library description: I find this library specialy useful to handle cuda errors in my project.

Source repository URL: https://developer.nvidia.com/cuda-downloads

Project homepage (if different from the source repository): https://docs.nvidia.com/cuda/cuda-runtime-api/index.html

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

http://developer.download.nvidia.com/compute/DevZone/docs/html/C/doc/html/group__CUDART.html

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
