### ISSUE TITLE
[tiff] allow zstd support

### ISSUE THREAD

**Issue by ghesketh** [microsoft/vcpkg#16585]
**Issue**
libtiff already supports zstd compression codec, but the existing "tiff" port explicitly disallows it

**Solution**
- Add `Feature: zstd` to `CONTROL`
- Remove `-Dzstd=OFF` from `portfile.make`

I am happy to make a PR, but the contribution guidelines urge creating an issue first.

**Comment by JackBoosY** [comment]
@ghesketh  Please make a PR and I will help you.
