### ISSUE TITLE
[flashlight-cpu/onednn] build fail

### ISSUE THREAD

**Issue by walenty500** [microsoft/vcpkg#16586]
**Host Environment**

    OS: Ubuntu 18.04 
    Compiler: gcc

**To Reproduce**

`./vcpkg install flashlight-cpu`

**Failure logs**

```
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:144 (message):
    Command failed: /home/krzysztof/vcpkg/downloads/tools/cmake-3.19.2-linux/cmake-3.19.2-Linux-x86_64/bin/cmake --build . --config Debug --target install -- -v -j9
    Working Directory: /home/krzysztof/vcpkg/buildtrees/onednn/x64-linux-dbg
    See logs for more information:
      /home/krzysztof/vcpkg/buildtrees/onednn/install-x64-linux-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:105 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:45 (vcpkg_build_cmake)
  ports/onednn/portfile.cmake:20 (vcpkg_install_cmake)
  scripts/ports.cmake:139 (include)


Error: Building package onednn:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: onednn:x64-linux
  Vcpkg version: 2021-01-13-unknownhash

Additionally, attach any relevant sections from the log files above.
```

Previously had problems with the same build, but with MLK (had to change MLK_REQUIRED_VERSION at ports/intel-mkl/portfile.cmake from 20200000 to 202101)
 
When doing ./vcpkg update :

`Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.`

When doing git pull : Already up to date

Attaching install-x64-linux-dbg-out.log:

[install-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/6098141/install-x64-linux-dbg-out.log)

**Comment by JackBoosY** [comment]
Please check if the memory and hard disk are free.

Thanks.

**Comment by walenty500** [comment]
Thank you for the reply!

As it turned out the problem was with my memory size. I had only 8GB of RAM and 2GB of swap, so i changed the swapfile's size to 8GB, and after this didn't work i resized it to 16GB and it worked... 

Until I ran out of hard disk space...

I will try to build flashlight using docker probably.

Once again, thank you for the reply and have a nice day.

**Comment by JackBoosY** [comment]
Maybe we should pick this error message and notice user in the output.
