### ISSUE TITLE
vcpkg_install cmake function

### ISSUE THREAD

**Issue by Mr-Leshiy** [microsoft/vcpkg#16582]
I looking how to simplify the build process of the c++ applications, so here it is my suggestion.
In my opinion, building some c++ package it is convenient when all dependencies installing automatically. And with such tool as vcpkg and cmake it is possible do it in the very simple way, just adding the following function.

```
function(vcpkg_install package)
    find_program(VCPKG_FOUND ccache)
    if(VCPKG_FOUND)
        execute_process(COMMAND vcpkg install ${package})
    endif(VCPKG_FOUND)
endfunction()
```
Generally it is possible to improve it and make it more general and specify the concrete triplet or the version of the package that you need.

To add this function into the vcpkg, so the any user will have possibility to use it after they install vcpkg, it is needed to add ```vcpkg-config.cmake``` and specify the path to this file into the ```CMAKE_PREFIX_PATH``` variable. It is possible to update the following lines in the vcpkg.cmake file.
https://github.com/microsoft/vcpkg/blob/c47216ac7904b09187c119c7e4d010dcf993e3d5/scripts/buildsystems/vcpkg.cmake#L483 .

As a result, it will be use the vcpkg cmake functions like ```vcpkg_install``` in the other projects in the following way.

```
find_package(vcpkg CONFIG REQUIRED)

vcpkg_install(boost)

```

**Comment by autoantwort** [comment]
I think you are searching for the [manifest mode](https://github.com/microsoft/vcpkg/blob/master/docs/users/manifests.md).

**Comment by Mr-Leshiy** [comment]
Yes, thank you !!! It is look like that it is what I mean. 
I close this issue.
