### ISSUE TITLE
Error: Building package msmpi:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by KillJoke** [microsoft/vcpkg#16581]
PS D:\DEV\vcpkg> .\vcpkg install msmpi
Computing installation plan...
The following packages will be built and installed:
    msmpi[core]:x86-windows -> 10.1
Detecting compiler hash for triplet x86-windows...
Could not locate cached archive: C:\Users\TUF\AppData\Local\vcpkg\archives\de\dee58b67601d83664c05216e1e858e6bcca798da.zip
Starting package 1/1: msmpi:x86-windows
Building package msmpi[core]:x86-windows...
-- Using cached D:/DEV/vcpkg/downloads/msmpisdk-10.1.12498.msi
-- Using cached D:/DEV/vcpkg/downloads/msmpisetup-10.1.12498.exe
CMake Error at ports/msmpi/portfile.cmake:59 (message):
    Could not find:
      C:\Program Files/Microsoft MPI/Bin/mpiexec.exe
    Please install the MSMPI redistributable package before trying to install this port.
    The appropriate installer has been downloaded to:
      D:/DEV/vcpkg/downloads/msmpisetup-10.1.12498.exe

Call Stack (most recent call first):
  scripts/ports.cmake:139 (include)

Error: Building package msmpi:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: msmpi:x86-windows
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

Additionally, attach any relevant sections from the log files above.

**Comment by JonLiu1993** [comment]
@KillJoke ,Thanks for posting this issue,Please install this exe first and then reinstall：
````
Please install this exe first and then reinstall
````

**Comment by JonLiu1993** [comment]
@KillJoke ,Have you tried the advice I gave you?

**Comment by KillJoke** [comment]
> @KillJoke ,Have you tried the advice I gave you?

Ty for trying to help but it didnt work, email notification came to spam so i didnt see your reply.
I am still not able to fix this problem.

**Comment by KillJoke** [comment]
> > @KillJoke ,Have you tried the advice I gave you?
Yes m firstly i installed wrong exe, but your advice actually worked,thanks a lot )
