### ISSUE TITLE
How do I vcpkg in the manifest mode choose the compiler ?

### ISSUE THREAD

**Issue by Mr-Leshiy** [microsoft/vcpkg#16598]
I am working on the Linux system, so I have the following question.
Does the vcpkg build the package, that are provided in the ```vcpkg.json``` manifest file, builds with the same compiler which are specified for the project during the cmake build process via the ```CC``` and the ```CXX``` env. vars.
Here is the command line for the cmake:
```
CC=clang CXX=clang++ cmake -b build . -DCMAKE_TOOLCHAIN_FILE=D:\src\vcpkg\scripts\buildsystems\vcpkg.cmake 
```

**Comment by Neumann-A** [comment]
Since vcpkg ist not creating its own environment on linux it or more precise cmake should be able to pick up those env variables. You can always check the build logs to make sure it does.
