### ISSUE TITLE
[kinectsdk1] Outdated Kinect SDK Setup.exe hash

### ISSUE THREAD

**Issue by ilia-glushchenko** [microsoft/vcpkg#16599]
**Is your feature request related to a problem? Please describe.**
It looks like Kinect SDK Setup.exe was updated. 
It no longer matches the SHA512 hash sum in the port file (see `\vcpkg\ports\kinectsdk1\portfile.cmake:9`). 
New hash you get while installing the port: `ee8a0f70c86aad80fe214108e315e4550a90ed39f278ce00a7137532174ee5bf3bdeb1d0b499fc5ffdb5e176adecfd68963ee3731e1d2f00d69d32d1b8a3c555`. 
Current hash sum in the port is: `d7e886d639b4310addc7c1350311f81289ffbcd653237882da7bf3d4074281ed35d217cb8be101579cac880c574dd89c62cd6a87772d60905c446d0be5fd1932`. 
It error breaks the installation of the port.

**Proposed solution**
Update hash sum to match the one on the official website.

**Comment by JonLiu1993** [comment]
Hi @ilia-glushchenko ,Thanks for posting this issue,I saw that SHA512 is correct after git pull in vcpkg, please update vcpkg and try again
