### ISSUE TITLE
How do I build on one machine and distribute built files to integrate on another?

### ISSUE THREAD

**Issue by jdx-john** [microsoft/vcpkg#16594]
Building a lot of dependencies can take a long time, so pre-building vcpkg dependencies on one machine would sometimes be useful.

What I would like is something like the following workflow:

1. Developer installs vcpkg locally.
2. Developer copies required files from <build-server> to their local machine
3. Developer runs `vcpkg integrate install`

How feasible is this, which folders would they need to copy and what commands to run to ensure vcpkg doesn't download sources and rebuild? It is not a requirement developers have the sources locally, unless vcpkg requires this.

Would distributing a Nuget be the better option? I was thinking my approach above would allow a developer to install a new library they are using in a feature more easily.

**Comment by autoantwort** [comment]
See the [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/users/binarycaching.md)

**Comment by jdx-john** [comment]
I can't make head nor tail of that :) Most of the discussion seems to be about CI and so on, I don't see any explanation what I should copy to my local box and how I should use it.

**Comment by jdx-john** [comment]
I think export might be easier (https://devblogs.microsoft.com/cppblog/vcpkg-introducing-export-command/)
Developers can presumably run vcpkg in parallel if they are adding a new library dependency.

**Comment by autoantwort** [comment]
If you have a shared network drive, you could use `binarycache` `files,<path>[,<rw>] | Adds a custom file-based location`.

**Comment by jdx-john** [comment]
Yeah that's a good point.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
