### ISSUE TITLE
[darknet] build failure

### ISSUE THREAD

**Issue by ADerSchreiber** [microsoft/vcpkg#16597]
**Host Environment**
- OS: Windows 10 Home
- Compiler: revision

**To Reproduce**
`.\vcpkg install darknet[opencv-base,cuda,cudnn]:x64-windows`

**Failure logs** 
CMake Error: Problem with archive_write_header(): Can't create '\\?\D:\OneFolder\AnotherFolder\vcpkg\downloads\tools\msys2\969c0913b9df89e1.tmp\usr\bin\gawk.exe'
CMake Error: Current file: usr/bin/gawk.exe
CMake Error: Problem extracting tar: D:/OneFolder/AnotherFolder/vcpkg/downloads/msys-gawk-5.1.0-1-x86_64.pkg.tar.xz

**Console output**

PS D:\OneFolder\AnotherFolder\vcpkg> .\vcpkg install darknet[opencv-base,cuda,cudnn]:x64-windows
Computing installation plan...
The following packages will be built and installed:
    darknet[core,cuda,cudnn,opencv-base]:x64-windows -> 2021-01-21
  * ffmpeg[avcodec,avdevice,avfilter,avformat,avresample,core,gpl,postproc,swresample,swscale]:x64-windows -> 4.3.1#11
  * libjpeg-turbo[core]:x64-windows -> 2.0.6
  * liblzma[core]:x64-windows -> 5.2.5#2
  * libpng[core]:x64-windows -> 1.6.37#14
  * libwebp[core,nearlossless,simd,unicode]:x64-windows -> 1.1.0#1
  * opencv[core,dnn,ffmpeg,jpeg,png,quirc,tiff,webp]:x64-windows -> 4.5.1
  * opencv4[core,dnn,ffmpeg,jpeg,png,quirc,tiff,webp]:x64-windows -> 4.5.1
  * protobuf[core]:x64-windows -> 3.14.0#1
  * pthreads[core]:x64-windows -> 3.0.0-6
  * quirc[core]:x64-windows -> 1.1#2
  * stb[core]:x64-windows -> 2020-09-14
  * tiff[core]:x64-windows -> 4.1.0#1
  * zlib[core]:x64-windows -> 1.2.11#9
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\Anonymous\AppData\Local\vcpkg\archives\f4\f44896aae58174d960a566c50389c807fc32909e.zip
Could not locate cached archive: C:\Users\Anonymous\AppData\Local\vcpkg\archives\84\84d23ecf93b0a154d0203df554d36da725bf4723.zip
Could not locate cached archive: C:\Users\Anonymous\AppData\Local\vcpkg\archives\0d\0dc385e774289116f79f3a0aea6ba5c079f6edea.zip
Could not locate cached archive: C:\Users\Anonymous\AppData\Local\vcpkg\archives\c1\c102f744aa36ff99afd3bf534cdaf5b9700809ab.zip
Could not locate cached archive: C:\Users\Anonymous\AppData\Local\vcpkg\archives\dc\dcc87fe3692dcc3f99fea50d828458d402fad4b3.zip
Could not locate cached archive: C:\Users\Anonymous\AppData\Local\vcpkg\archives\87\8779007db10d4335640bb3f3d7c44752c179b889.zip
Could not locate cached archive: C:\Users\Anonymous\AppData\Local\vcpkg\archives\64\64ddab5d0faec69d56760954ca3ee658ea7672c5.zip
Could not locate cached archive: C:\Users\Anonymous\AppData\Local\vcpkg\archives\f0\f07b3caf92fbc6fdbafe32ee226e5df6d386601d.zip
Could not locate cached archive: C:\Users\Anonymous\AppData\Local\vcpkg\archives\88\88f9a17f3c30e003c8898df0ebeeb249f92f43e5.zip
Could not locate cached archive: C:\Users\Anonymous\AppData\Local\vcpkg\archives\6b\6b2be708ad1b125e3e8072d785a4ad366b5dbd82.zip
Could not locate cached archive: C:\Users\Anonymous\AppData\Local\vcpkg\archives\df\df91c5ec1687b09034fdd16d0ca7b9865135648b.zip
Could not locate cached archive: C:\Users\Anonymous\AppData\Local\vcpkg\archives\78\780c05d5bc5b43d96eab68399a2f5427dcbe2b39.zip
Could not locate cached archive: C:\Users\Anonymous\AppData\Local\vcpkg\archives\07\0792da7d6b882c3c0d22a11fee579f77b7714bbd.zip
Could not locate cached archive: C:\Users\Anonymous\AppData\Local\vcpkg\archives\a1\a18b92823a72fb0d06afe40c61cd7b89b9814f0c.zip
Starting package 1/14: ffmpeg:x64-windows
Building package ffmpeg[avcodec,avdevice,avfilter,avformat,avresample,core,gpl,postproc,swresample,swscale]:x64-windows...
-- Using cached D:/OneFolder/AnotherFolder/vcpkg/downloads/ffmpeg-ffmpeg-n4.3.1.tar.gz
-- Cleaning sources at D:/OneFolder/AnotherFolder/vcpkg/buildtrees/ffmpeg/src/n4.3.1-a2a92eb697.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/OneFolder/AnotherFolder/vcpkg/downloads/ffmpeg-ffmpeg-n4.3.1.tar.gz
-- Applying patch 0001-create-lib-libraries.patch
-- Applying patch 0003-fix-windowsinclude.patch
-- Applying patch 0004-fix-debug-build.patch
-- Applying patch 0005-fix-libvpx-linking.patch
-- Applying patch 0006-fix-StaticFeatures.patch
-- Applying patch 0007-fix-lib-naming.patch
-- Applying patch 0008-Fix-wavpack-detection.patch
-- Applying patch 0009-Fix-fdk-detection.patch
-- Applying patch 0010-Fix-x264-detection.patch
-- Applying patch 0011-Fix-x265-detection.patch
-- Applying patch 0012-Fix-ssl-110-detection.patch
-- Applying patch 0013-define-WINVER.patch
-- Applying patch 0014-avfilter-dependency-fix.patch
-- Using source at D:/OneFolder/AnotherFolder/vcpkg/buildtrees/ffmpeg/src/n4.3.1-a2a92eb697.clean
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
    Command failed: D:/OneFolder/AnotherFolder/vcpkg/downloads/tools/cmake-3.19.2-windows/cmake-3.19.2-win32-x86/bin/cmake.exe -E tar xzf D:/OneFolder/AnotherFolder/vcpkg/downloads/msys-gawk-5.1.0-1-x86_64.pkg.tar.xz
    Working Directory: D:/OneFolder/AnotherFolder/vcpkg/downloads/tools/msys2/969c0913b9df89e1.tmp
    Error code: 1
    See logs for more information:
      D:\OneFolder\AnotherFolder\vcpkg\buildtrees\ffmpeg\msys-x64-windows-6-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_acquire_msys.cmake:519 (vcpkg_execute_required_process)
  ports/ffmpeg/portfile.cmake:69 (vcpkg_acquire_msys)
  scripts/ports.cmake:139 (include)

Error: Building package ffmpeg:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: ffmpeg:x64-windows
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

**Additional context**
There are three archive folders in \AppData\Local\vcpkg\archives, namely:

1b
58
a2

with one .zip each.

**Comment by autoantwort** [comment]
Please attach D:\OneFolder\AnotherFolder\vcpkg\buildtrees\ffmpeg\msys-x64-windows-6-err.log

**Comment by NancyLi1013** [comment]
Hi @ADerSchreiber 

Thanks for posting this issue.

```
CMake Error: Problem with archive_write_header(): Can't create '\?\D:\OneFolder\AnotherFolder\vcpkg\downloads\tools\msys2\969c0913b9df89e1.tmp\usr\bin\gawk.exe'
CMake Error: Current file: usr/bin/gawk.exe
CMake Error: Problem extracting tar: D:/OneFolder/AnotherFolder/vcpkg/downloads/msys-gawk-5.1.0-1-x86_64.pkg.tar.xz
```

Could you please try to install vcpkg to another driver?

Please see the details here https://github.com/microsoft/vcpkg/issues/14300#issuecomment-719396447

**Comment by ADerSchreiber** [comment]
> Hi @ADerSchreiber
> 
> Thanks for posting this issue.
> 
> ```
> CMake Error: Problem with archive_write_header(): Can't create '\?\D:\OneFolder\AnotherFolder\vcpkg\downloads\tools\msys2\969c0913b9df89e1.tmp\usr\bin\gawk.exe'
> CMake Error: Current file: usr/bin/gawk.exe
> CMake Error: Problem extracting tar: D:/OneFolder/AnotherFolder/vcpkg/downloads/msys-gawk-5.1.0-1-x86_64.pkg.tar.xz
> ```
> 
> Could you please try to install vcpkg to another driver?
> 
> Please see the details here [#14300 (comment)](https://github.com/microsoft/vcpkg/issues/14300#issuecomment-719396447)

Thanks, this seems to have been the issue, D:\ was exFAT. Build is now in progress on an NTFS-Partition. I assume this taking 3+ hours in total is to be expected? Went fairly quickly until it arrived at _Building x64-windows-dbg_, which I could understand taking more time than building the release.
![building_dbg](https://user-images.githubusercontent.com/79848228/110447280-5bf82f80-80c0-11eb-8010-3adfa389b548.PNG) 

Looks like this ever since.

Using:
Intel Core i7 6 Cores, 12 Threads; 
16 GB RAM; 
NVIDIA GeForce RTX 2080.

**Comment by ADerSchreiber** [comment]
Nevermind, executing the command anew with 

.\vcpkg install darknet[opencv-base,cuda,cudnn]:x64-windows

instead of 

.\vcpkg install darknet[full]:x64-windows

did not throw an error. Issue can be closed.

**Comment by NancyLi1013** [comment]
Thanks for your feedback @ADerSchreiber.

For the problem you encountered, it is a bug, I will fix this soon.

```
-- Downloading https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v4_pre/yolov4-tiny.weights -> darknet-cache/yolov4-tiny.weights...
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:105 (message):


  File does not have expected hash:

          File path: [ C:/Facetracking/vcpkg/downloads/temp/darknet-cache/yolov4-tiny.weights ]
      Expected hash: [ 804ca2ab8e3699d31c95bf773d22f901f186703487c7945f30dc2dbb808094793362cb6f5da5cd0b4b83f820c8565a3cba22fafa069ee6ca2a925677137d95f4 ]
        Actual hash: [ 7d4d9fe150f9fe3ea7d2310f1445fe983b31fbf06d301c70ecfe00e8559e6f1bf940198c2dd55db772238f23ea0092fb6553558e5414f3ee173b8b28e53c5b54 ]

```
