### ISSUE TITLE
How do I install static boost 1.75 lib with vs2019(v142) compiled?

### ISSUE THREAD

**Issue by icegull** [microsoft/vcpkg#16608]
Today what I do, pull the newest vcpkg repo and get the newest vcpkg.exe:
1. Add "set(VCPKG_PLATFORM_TOOLSET v142)" into "vcpkg\triplets\community\x64-windows-static-md.cmake"
2. ".\vcpkg.exe install boost:x64-windows-static-md"
3. I get vc140 lib like "vcpkg\installed\x64-windows-static-md\lib\boost_atomic-vc140-mt.lib"
4. I link boost lib into a project and check it with depenency, I do see "vcruntime140.dll"

What I suppose to get vc142 static boost lib. So what's wrong with my steps? Thanks for the answer. ;-)

**Comment by NancyLi1013** [comment]
Hi @icegull 

Thanks for posting this issue.

The library name is not related with toolset version. Since it will be renamed as '-vc140'. Please see the code in _/scripts/buildsystems/vcpkg.cmake_

```
    if("${CMAKE_VS_PLATFORM_TOOLSET}" STREQUAL "v120")
            set(Boost_COMPILER "-vc120")
     else()
            set(Boost_COMPILER "-vc140")
     endif()
```
https://github.com/microsoft/vcpkg/blob/master/scripts/buildsystems/vcpkg.cmake#L818-L822

Also you can get the details here to know why vcpkg do like this:

https://github.com/microsoft/vcpkg/issues/601#issuecomment-276220946

**Comment by icegull** [comment]
> Hi @icegull
> 
> Thanks for posting this issue.
> 
> The library name is not related with toolset version. Since it will be renamed as '-vc140'. Please see the code in _/scripts/buildsystems/vcpkg.cmake_
> 
> ```
>     if("${CMAKE_VS_PLATFORM_TOOLSET}" STREQUAL "v120")
>             set(Boost_COMPILER "-vc120")
>      else()
>             set(Boost_COMPILER "-vc140")
>      endif()
> ```
> 
> https://github.com/microsoft/vcpkg/blob/master/scripts/buildsystems/vcpkg.cmake#L818-L822
> 
> Also you can get the details here to know why vcpkg do like this:
> 
> [#601 (comment)](https://github.com/microsoft/vcpkg/issues/601#issuecomment-276220946)

Thank you very much. More clear for me.

**Comment by NancyLi1013** [comment]
Please let me know if you still have other problems for this.

**Comment by icegull** [comment]
> Please let me know if you still have other problems for this.

No. Thanks for your kindly reply. We can close it now.
