### ISSUE TITLE
[New Port Request] plusaes

### ISSUE THREAD

**Issue by BullyWiiPlaza** [microsoft/vcpkg#16601]
Library name: plusaes

Library description: Header only C++ AES cipher library

Source repository URL: https://github.com/kkAyataka/plusaes

Project homepage (if different from the source repository): -

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
No, it's a simple header only library.

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
