### ISSUE TITLE
[brotli] build failure

### ISSUE THREAD

**Issue by bieging** [microsoft/vcpkg#16600]
**Host Environment**
- OS: Windows 10
- Compiler: revision

**To Reproduce**
vcpkg install irrlicht zlib curl[winssl] openal-soft libvorbis libogg sqlite3 freetype luajit gmp jsoncpp --triplet x64-windows

Installation command from Minetest project

**Failure logs** 
```
C:\Users\andre\Downloads\vcpkg\vcpkg>vcpkg install irrlicht zlib curl[winssl] openal-soft libvorbis libogg sqlite3 freetype luajit gmp jsoncpp --triplet x64-windows
Computing installation plan...
The following packages will be built and installed:
  * brotli[core]:x64-windows -> 1.0.9#1
  * bzip2[core]:x64-windows -> 1.0.8#1
    curl[core,non-http,schannel,ssl,sspi,winssl]:x64-windows -> 7.74.0#3
    freetype[brotli,bzip2,core,png,zlib]:x64-windows -> 2.10.4
    gmp[core]:x64-windows -> 6.2.1#3
    irrlicht[core]:x64-windows -> 1.8.4-10
    jsoncpp[core]:x64-windows -> 1.9.4
  * libjpeg-turbo[core]:x64-windows -> 2.0.6
    libogg[core]:x64-windows -> 1.3.4#3
  * libpng[core]:x64-windows -> 1.6.37#14
    libvorbis[core]:x64-windows -> 1.3.7#1
    luajit[core]:x64-windows -> 2.0.5-3
    openal-soft[core]:x64-windows -> 1.21.1
    sqlite3[core]:x64-windows -> 3.34.1
  * vs-yasm[core]:x64-windows -> 0.5.0#1
  * yasm-tool-helper[core]:x64-windows -> 2020-10-12
    zlib[core]:x64-windows -> 1.2.11#9
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
A suitable version of powershell-core was not found (required v7.1.0). Downloading portable powershell-core v7.1.0...
Downloading powershell-core...
  https://github.com/PowerShell/PowerShell/releases/download/v7.1.0/PowerShell-7.1.0-win-x86.zip -> C:\Users\andre\Downloads\vcpkg\vcpkg\downloads\PowerShell-7.1.0-win-x86.zip
Extracting powershell-core...
A suitable version of 7zip was not found (required v18.1.0). Downloading portable 7zip v18.1.0...
Downloading 7zip...
  https://www.nuget.org/api/v2/package/7-Zip.CommandLine/18.1.0 -> C:\Users\andre\Downloads\vcpkg\vcpkg\downloads\7-zip.commandline.18.1.0.nupkg
Extracting 7zip...
A suitable version of nuget was not found (required v5.5.1). Downloading portable nuget v5.5.1...
Downloading nuget...
  https://dist.nuget.org/win-x86-commandline/v5.5.1/nuget.exe -> C:\Users\andre\Downloads\vcpkg\vcpkg\downloads\22ea847d-nuget.exe
Could not locate cached archive: C:\Users\andre\AppData\Local\vcpkg\archives\cc\cc7d28a453a3500422befc5f7a38153e7ec2a87a.zip
Could not locate cached archive: C:\Users\andre\AppData\Local\vcpkg\archives\31\31909c171066fa3a16ffbd302a576121905a3644.zip
Could not locate cached archive: C:\Users\andre\AppData\Local\vcpkg\archives\0b\0b3b81d01700c10a9dae68e98267f76b4348c345.zip
Could not locate cached archive: C:\Users\andre\AppData\Local\vcpkg\archives\b1\b156424026d08671f0ee61cc1567ed578c4347d4.zip
Could not locate cached archive: C:\Users\andre\AppData\Local\vcpkg\archives\9a\9aaac8459a816e2283bf77cab39548cd2dd59470.zip
Could not locate cached archive: C:\Users\andre\AppData\Local\vcpkg\archives\ad\adbaabc05b190c90f6f6ed71def8ad04bd5e12e8.zip
Could not locate cached archive: C:\Users\andre\AppData\Local\vcpkg\archives\5f\5f2538248d740bb8abc26f0f51ae24c15e15a1a6.zip
Could not locate cached archive: C:\Users\andre\AppData\Local\vcpkg\archives\25\2557a10ef69e2bee000aa796ae47125c5df59a76.zip
Could not locate cached archive: C:\Users\andre\AppData\Local\vcpkg\archives\07\07f87de0402126b04fac0850b6bdde363d547df3.zip
Could not locate cached archive: C:\Users\andre\AppData\Local\vcpkg\archives\e5\e5170c9f10aae8e2072ae57368f401112571c7c3.zip
Could not locate cached archive: C:\Users\andre\AppData\Local\vcpkg\archives\96\962dd2a026887ba45d124497d5efc5b53f6415c1.zip
Could not locate cached archive: C:\Users\andre\AppData\Local\vcpkg\archives\fd\fd1594e1319b30b12de02e501c1c26d631af3005.zip
Could not locate cached archive: C:\Users\andre\AppData\Local\vcpkg\archives\7b\7ba0e3ee82d82b8a73cd9685b4e324bbaa7820d9.zip
Could not locate cached archive: C:\Users\andre\AppData\Local\vcpkg\archives\62\62111f4cad68a618f52202bf6fdee56d59907b97.zip
Could not locate cached archive: C:\Users\andre\AppData\Local\vcpkg\archives\99\990ddccfbc679f5d96f556cd2fb2f9d6838e5d1f.zip
Could not locate cached archive: C:\Users\andre\AppData\Local\vcpkg\archives\29\295e2adde728480b931fdd85876625bb69a7e00d.zip
Could not locate cached archive: C:\Users\andre\AppData\Local\vcpkg\archives\a6\a6a52a136617be950ca2019410d00043b7d59718.zip
Starting package 1/17: brotli:x64-windows
Building package brotli[core]:x64-windows...
-- Downloading https://github.com/google/brotli/archive/e61745a6b7add50d380cfd7d3883dd6c62fc2c71.tar.gz -> google-brotli-e61745a6b7add50d380cfd7d3883dd6c62fc2c71.tar.gz...
-- Extracting source C:/Users/andre/Downloads/vcpkg/vcpkg/downloads/google-brotli-e61745a6b7add50d380cfd7d3883dd6c62fc2c71.tar.gz
-- Applying patch install.patch
-- Applying patch fix-arm-uwp.patch
-- Applying patch pkgconfig.patch
-- Applying patch fix-ios.patch
-- Using source at C:/Users/andre/Downloads/vcpkg/vcpkg/buildtrees/brotli/src/6c62fc2c71-7c6c2710e9.clean
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
    Command failed: ninja -v
    Working Directory: C:/Users/andre/Downloads/vcpkg/vcpkg/buildtrees/brotli/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\Users\andre\Downloads\vcpkg\vcpkg\buildtrees\brotli\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:324 (vcpkg_execute_required_process)
  ports/brotli/portfile.cmake:14 (vcpkg_configure_cmake)
  scripts/ports.cmake:139 (include)


Error: Building package brotli:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: brotli:x64-windows
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e
```
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/6103265/config-x64-windows-out.log)

**Additional context**
Error log attached

**Comment by bieging** [comment]
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/6103277/config-x64-windows-out.log)

**Comment by JonLiu1993** [comment]
@bieging ,Thanks for posting this issue
CMake is not able to generate the project properly -
Check to make sure Visual Studio 2019 has the following installed:

Desktop Development with C++
One of the Windows SDKs, preferably the latest 19041
English Language Pack

**Comment by bieging** [comment]
@JonLiu1993 

I updated the Windows SDK to the latest version and brotli installed correctly, but the package gmp still failed. See cmd log 
 below.

**Failure Logs**
C:\Users\andre\Downloads\vcpkg\vcpkg>vcpkg install irrlicht zlib curl[winssl] openal-soft libvorbis libogg sqlite3 freetype luajit gmp jsoncpp --triplet x64-windows
Computing installation plan...
The following packages are already installed:
    curl[core,non-http,schannel,ssl,sspi,winssl]:x64-windows -> 7.74.0#3
    freetype[brotli,bzip2,core,png,zlib]:x64-windows -> 2.10.4
    zlib[core]:x64-windows -> 1.2.11#9
The following packages will be built and installed:
    gmp[core]:x64-windows -> 6.2.1#3
    irrlicht[core]:x64-windows -> 1.8.4-10
    jsoncpp[core]:x64-windows -> 1.9.4
  * libjpeg-turbo[core]:x64-windows -> 2.0.6
    libogg[core]:x64-windows -> 1.3.4#3
    libvorbis[core]:x64-windows -> 1.3.7#1
    luajit[core]:x64-windows -> 2.0.5-3
    openal-soft[core]:x64-windows -> 1.21.1
    sqlite3[core]:x64-windows -> 3.34.1
Additional packages (*) will be modified to complete this operation.
Package curl:x64-windows is already installed
Package freetype:x64-windows is already installed
Package zlib:x64-windows is already installed
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\andre\AppData\Local\vcpkg\archives\0c\0cc0ab0ba4d280ed7af47ee765e9254c18e78d75.zip
Could not locate cached archive: C:\Users\andre\AppData\Local\vcpkg\archives\41\419b682cb632f02169dbad9948bbe6b9ec1a9122.zip
Could not locate cached archive: C:\Users\andre\AppData\Local\vcpkg\archives\6d\6da5df586116acce888251c0d8198199ae3877df.zip
Could not locate cached archive: C:\Users\andre\AppData\Local\vcpkg\archives\f2\f2ed59af09696978517d9907e9d5bfff6fceb54f.zip
Could not locate cached archive: C:\Users\andre\AppData\Local\vcpkg\archives\76\763068f5be651d81935afce9ebb4437b85492f91.zip
Could not locate cached archive: C:\Users\andre\AppData\Local\vcpkg\archives\52\5225482dc47d8d93f3df6644ee5a189467727321.zip
Could not locate cached archive: C:\Users\andre\AppData\Local\vcpkg\archives\f5\f5484879d34adf034369a17735497c99a2101795.zip
Could not locate cached archive: C:\Users\andre\AppData\Local\vcpkg\archives\4f\4f0283f16ca94bd7028a26e0e0f6d1a31ec3eb38.zip
Could not locate cached archive: C:\Users\andre\AppData\Local\vcpkg\archives\04\0449fac1665fd197c74d3a1c6d419c00b89e8f86.zip
Starting package 1/9: gmp:x64-windows
Building package gmp[core]:x64-windows...
-- Using cached C:/Users/andre/Downloads/vcpkg/vcpkg/downloads/ShiftMediaProject-gmp-0018c44e8dfcc3b64b43e0aea4b3f419f0b65fd0.tar.gz
-- Cleaning sources at C:/Users/andre/Downloads/vcpkg/vcpkg/buildtrees/gmp/src/19f0b65fd0-9b395bc164.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/andre/Downloads/vcpkg/vcpkg/downloads/ShiftMediaProject-gmp-0018c44e8dfcc3b64b43e0aea4b3f419f0b65fd0.tar.gz
-- Applying patch vs.build.patch
-- Applying patch runtime.patch
-- Applying patch adddef.patch
-- Using source at C:/Users/andre/Downloads/vcpkg/vcpkg/buildtrees/gmp/src/19f0b65fd0-9b395bc164.clean
CMake Error at installed/x64-windows/share/yasm-tool-helper/yasm-tool-helper.cmake:16 (message):
  Cross-targetting and x64 ports requiring yasm require the x86-windows
  yasm-tool to be available.  Please install yasm-tool:x86-windows first.
Call Stack (most recent call first):
  ports/gmp/portfile.cmake:19 (yasm_tool_helper)
  scripts/ports.cmake:139 (include)


Error: Building package gmp:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: gmp:x64-windows
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

Additionally, attach any relevant sections from the log files above.

**Comment by StarGate-One** [comment]
>Cross-targetting and x64 ports requiring yasm require the x86-windows
>yasm-tool to be available. Please install yasm-tool:x86-windows first.
1. `vcpkg install yasm-tool:x86-windows`
2. `vcpkg install irrlicht openal-soft libvorbis libogg sqlite3 luajit gmp jsoncpp --triplet x64-windows`

**Comment by bieging** [comment]
@StarGate-One it worked now, thanks!

**Comment by StarGate-One** [comment]
> @StarGate-One it worked now, thanks!

@bieging You are most welcome! Glad it works for you now.👍👏

**Comment by JackBoosY** [comment]
@StarGate-One  Can you please open a PR to notice the user to install `yasm-tool:x86-windows` first?

Thanks.

**Comment by StarGate-One** [comment]
> @StarGate-One Can you please open a PR to notice the user to install `yasm-tool:x86-windows` first?
> 
> Thanks.
@JackBoosY 
I guess we need to reopen the issue, so we have issue tracking to PR #16674 ?
I hope this is something like you are looking for?
It is a start, for review/suggestions.
I went ahead and updated all three ports using the yasm-tool:x86-windows, ports gmp, mpg123 and nettle.
