### ISSUE TITLE
[vcpkg upgrade] Upgrade deletes existing packages and then aborts

### ISSUE THREAD

**Issue by Krzmbrzl** [microsoft/vcpkg#16618]
**Describe the bug**
When updating my local vcpkg installation the steps I usually perform are
1. `git pull`
2. `vcpg upgrade --no-dry-run`

In these cases vcpkg figures out that there are packages that need an upgrade. It then proceed by removing the old packages. However when it comes to actually downloading and building the new packages (at least I assume that this is what would happen next), the process exits telling me I have to run the bootstrap script again in order to update the vcpkg executable itself.

The issue with that is that now all these old packages are gone already and thus after having run the bootstrap script, `vcpkg upgrade` tells me that all packages are up-to-date (which makes sense given that it just deleted the ones that weren't).

That means that I then have to manually reinstall these packages.

**Environment**
- OS: Linux

**Expected behavior**
The check for whether the bootstrap script needs to be run should be done before removing any packages, so that once the script is run, I can simply call `vcpkg upgrade --no-dry-run` again to upgrade my packages without having to reinstall them manually.

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/4360.
