### ISSUE TITLE
Struggling with differences in abi_info and build failures with binarycaching

### ISSUE THREAD

**Issue by meastp** [microsoft/vcpkg#16615]
I am trying to use vcpkg for building in Azure Pipelines (CI, Microsoft Hosted Agent windows-2019 and vs2017-win2016) and to be able to reuse the binary packages produced on my dev machine.

Everything except two packages compile successfully in Azure, but the binary package hashes are different. The two packages that fail (libpq and ocilib, with an error about corrupt patch) does compile successfully on my dev machine.

Here is an example from the abi_info on ocilib:

Dev machine (builds ok):
```
CONTROL 9241a03e2bb576c99b871f63a5b0c8b2ed4c2a95
cmake 3.19.2
features core
portfile.cmake 0657a4f80fd0e53da0ec80d0aa805ad7f53211ae
post_build_checks 2
powershell 7.1.1
triplet x64-windows-v141
triplet_abi 3e1e1ba8308fbe92aa7777d17951828b7098c537-a1c0eabb0c5177b6a8fb97a58ae398880c47b352-b9e2480dca17932aec14cc7258376a7b281aa769
vcpkg_configure_make e1a003f885d4091e1e3fab0f82be37ab3d8d88a7
vcpkg_fail_port_install 69f61f498784f900b570c22b1e8bee2ca8995840
vcpkg_from_git 99e83c6ffac2dd07afaf73d795988ca5dec2dc8b
vcpkg_from_github a9dd1453b8873c9702731c6c36e79fb0ab6ae486
vcpkg_install_make 6b7345be4d3363747f6d75839e87d441025f04d5
vcpkg_install_msbuild b1f007c6cc36e1fb840cba9ee18057b3a8d648e6
```

CI (build fails):
```
CONTROL 9241a03e2bb576c99b871f63a5b0c8b2ed4c2a95
cmake 3.19.5
features core
portfile.cmake 0657a4f80fd0e53da0ec80d0aa805ad7f53211ae
post_build_checks 2
powershell 7.1.2
triplet x64-windows-v141
triplet_abi ed6353d74e9e730073fb23380c6237636df93252-a1c0eabb0c5177b6a8fb97a58ae398880c47b352-b9e2480dca17932aec14cc7258376a7b281aa769
vcpkg_configure_make e1a003f885d4091e1e3fab0f82be37ab3d8d88a7
vcpkg_fail_port_install 69f61f498784f900b570c22b1e8bee2ca8995840
vcpkg_from_git 99e83c6ffac2dd07afaf73d795988ca5dec2dc8b
vcpkg_from_github a9dd1453b8873c9702731c6c36e79fb0ab6ae486
vcpkg_install_make 6b7345be4d3363747f6d75839e87d441025f04d5
vcpkg_install_msbuild b1f007c6cc36e1fb840cba9ee18057b3a8d648e6
```

I see that these are different:
- cmake patch version
- powershell patch version
- the first part of triplet_abi

I'm hoping that patch versions don't affect the binary hash version of the binary packages?

Could you explain the last difference (triplet_abi)? I would like to produce binary packages that I can reuse between machines, and (obviously) successfully build libpq and ocilib in Azure.

**Comment by meastp** [comment]
btw, this is the message i get for building libpq (both v141 and v142):
```
Starting package 157/187: libpq:x64-windows-v142
         Building package libpq[core,openssl,zlib]:x64-windows-v142...
         -- [OVERLAY] Loading triplet configuration from: D:\a\1\s\triplets\x64-windows-v142.cmake
         -- Installing port from location: C:\Users\VssAdministrator\AppData\Local\vcpkg\registries\git-trees\d68450074a2fbc7a2aaeb23b9f4fdda0532e5897
         -- Downloading https://ftp.postgresql.org/pub/source/v12.2/postgresql-12.2.tar.bz2 -> postgresql-12.2.tar.bz2...
         -- Extracting source C:/vcpkg-latest/downloads/postgresql-12.2.tar.bz2
         -- Applying patch patches/windows/install.patch
         -- Applying patch patches/windows/win_bison_flex.patch
         CMake Error at scripts/cmake/z_vcpkg_apply_patches.cmake:57 (message):
##[error]Applying patch failed(0,0): Error : corrupt patch at line 39
     5>Applying patch failed : error : corrupt patch at line 39 [D:\a\1\s\src\myproj.vcxproj]
         
         Call Stack (most recent call first):
           scripts/cmake/vcpkg_extract_source_archive_ex.cmake:144 (z_vcpkg_apply_patches)
           C:/Users/VssAdministrator/AppData/Local/vcpkg/registries/git-trees/d68450074a2fbc7a2aaeb23b9f4fdda0532e5897/portfile.cmake:65 (vcpkg_extract_source_archive_ex)
           scripts/ports.cmake:139 (include)
```

the message for ocilib is more or less equal. I can't see how the patch is corrupt. (And, as I mentioned, this only happens in the microsoft hosted azure pipeline)

**Comment by PhoebeHui** [comment]
@meastp, do you install git locally, if so, what's revision do you use?

**Comment by meastp** [comment]
@PhoebeHui 

locally: 99dc49dae7e170c3be63dd097230007f3bb73c4f

I also download the latest revision in Azure.

**Comment by PhoebeHui** [comment]
@meastp, could you manualy update the EOL of 'ports/libpq/patches/windows/openssl_exe_path.patch' file to LF, and see if the patch could apply successfully?

**Comment by meastp** [comment]
@PhoebeHui I opened all windows patch files in notepad++ (which shows line endings), and when comparing the patches with the source files they apply to, I see differences in line endings in multiple patch files. Not sure if this is a problem for all the files:

- openssl_exe_path.patch (as you noticed, the patch is consistently crlf, the source is consistently lf)
- msgfmt.patch (the Install.pm file contains a mix of line endings, and is not consistent)
- python_lib.patch (the patch is consistently crlf, the source is consistently lf)
- Solution.patch (the patch is consistently crlf, the source is consistently lf)
- Mkvcbuild-static-lib.patch (the patch is consistently crlf, the source is consistently lf)

**Comment by PhoebeHui** [comment]
@meastp, I can't repro this issue locally, so could you help confirm if these patches could apply successfully when update all EOL from CRLF to LF in your machine?

**Comment by meastp** [comment]
@PhoebeHui I could never reproduce this locally - it only happens on the Microsoft hosted azure pipeline agent. I'm not sure why...

**Comment by meastp** [comment]
@PhoebeHui could this be a git (global) setting on the agent that handles crlf/lf differently than on our local machines?

**Comment by PhoebeHui** [comment]
It may be relate to the git gloable setting, @strega-nil, do you know more about this?

Relate to https://github.com/microsoft/vcpkg/blob/master/scripts/cmake/z_vcpkg_apply_patches.cmake#L48

**Comment by meastp** [comment]
I have added the following git config to my pipeline yaml script:
before:
```yaml    
    - powershell: |
        git clone https://github.com/microsoft/vcpkg.git vcpkg-latest
      workingDirectory: 'C:\'
      
```
after:
```yaml
    - powershell: |
        git config --global core.autocrlf false
        git clone https://github.com/microsoft/vcpkg.git vcpkg-latest
      workingDirectory: 'C:\'
```
We will se if this makes a difference

**Comment by meastp** [comment]
@PhoebeHui The core.autocrlf false did work for libpq. The failure with ocilib is an entirely different issue. Thank you for helping me with this! :)

Could you please explain the differences in the first part of triplet_abi so I can perhaps fix it/consolidate and reuse the binary packages between CI and my dev machine? :)

**Comment by PhoebeHui** [comment]
From https://github.com/microsoft/vcpkg-tool/blob/main/src/vcpkg/build.cpp#L444, the differences in the first part of triplet_abi seems due to the triplet_entry.hash is different. 

@ras0219-msft, could you please take a look at the abi info?

**Comment by meastp** [comment]
@ras0219-msft perhaps the parts making up (at least the first part of) `triplet_abi` could be printed as text as well (like the cmake version and powershell version is)? I'm really interested in keeping the same binary package between CI and dev machine(s) (and making sure all have identical abi_triplets when possible).

**Comment by ras0219-msft** [comment]
We do have a [`.gitattributes`](https://github.com/microsoft/vcpkg/blob/master/.gitattributes) which should have ensured all files are checked out using the original line endings, so I'm very confused as to why https://github.com/microsoft/vcpkg/issues/16615#issuecomment-793892069 made a difference. Assuming that's the problem, it's likely that the triplet file you're using has different line endings across your machines, which makes the hash different.

I also agree it'd be good to improve visibility of the precise factors; maybe improving https://github.com/microsoft/vcpkg/blob/master/docs/users/binarycaching.md#implementation-notes-internal-details-subject-to-change-without-notice is the right first step.

**Comment by meastp** [comment]
@ras0219-msft Thank you for the explanation. So, you're saying that the first hash of the triplet_abi is computed from only the triplet file? Or could this be caused by multiple reasons? Would the difference in CMake versions 3.19.5 vs 3.19.2 contribute at all?

I would think being able to reuse the binary packages across machines is pretty important, so more documentation would help troubleshooting/pinpoint the issue.

**Comment by aee11** [comment]
I also encountered the `error : corrupt patch at line 39` on the `libpq` `win_bison_flex.patch`. That file has LF line endings under `ports/libpq` but under the versioning directory `C:/vcpkg/buildtrees/versioning/versions/libpq/04f39fd5eb9744d0d5a649098fe92281028d30f1/patches/windows/win_bison_flex.patch` has CRLF endings.  I manually changed the patch's line endings under the `versions/libpq` folder and applied the same `git apply` command as vcpkg attempts: 

```
C:/vcpkg/downloads/tools/git-2.26.2-1-windows/mingw32/bin/git.exe" -c core.longpaths=true -c core.autocrlf=false --work-tree=. --git-dir=.git apply "C:/vcpkg/buildtrees/versioning/versions/libpq/04f39fd5eb9744d0d5a649098fe92281028d30f1/patches/windows/win_bison_flex.patch" --ignore-whitespace --whitespace=nowarn --verbose
```
and it was successfully applied.

So is there some way to preserve the line endings when the patches are replicated to the `versioning` directory?

**Comment by meastp** [comment]
@ras0219-msft This solved neither my build issue with libpq (when I tried to remove autocrlf false) nor the first part of abi_info. Could you please point to where this hash is computed? I'd like to have debug output for a single package to try to pinpoint the difference...

Should I open a new issue?

**Comment by PhoebeHui** [comment]
@meastp, I reopen this issue, so you don't need to open a new issue.

**Comment by vicroms** [comment]
The relevant part of the code is [here](https://github.com/microsoft/vcpkg-tool/blob/main/src/vcpkg/build.cpp#L447-L481).  

The `triplet_abi` entry is composed of `{triplet file hash}-{toolchain file hash}-{compiler info hash}`. There must be something that causes your triplet files to hash differently, it could be something hard to notice like a whitespace or an extra line skip.

**Comment by meastp** [comment]
@vicroms Thank you - this was useful info indeed! :)

By looking at the source code, I saw that the SHA1 algorithm is used, and tried powershell's `Get-FileHash` method, which made it easy to spot the difference. By changing from LF to CRLF in the triplet files, I got identical hashes both locally and in the Azure Pipelines Hosted Agent (`Get-FileHash -Path .\triplets\x64-windows-v141.cmake`).

There is still a mismatch, and by using `Get-FileHash` I think my assumption that nuget binary caching simply use the hash of the *.vcpkg_abi_info.txt for the library as the package name. Is this correct? This would mean that the versions of both Powershell and CMake needs to match _exactly_, even the patch versions. Isn't this too strict? At least if the tools aren't downloaded by vcpkg as part of the build (I guess cmake is but powershell is not?)

This is the diff between my local build and the Azure build that stops the binary cached packages from being reused:
(unified diff)
```diff
--- C:\Users\mattar\Source\Repos\vcpkg-original\buildtrees\zlib\x64-windows-v141.vcpkg_abi_info.txt	2021-03-30 08:54:47.536000000 +0200
+++ C:\Users\mattar\Downloads\vcpkg-latest-buildtrees-zlib-v141-x64\x64-windows-v141.vcpkg_abi_info.txt	2021-03-30 10:17:36.522000000 +0200
@@ -2,13 +2,13 @@
 CONTROL 196dc885ee80e1c31c2ddf996f3e1615005895de
 LICENSE e23c6e5f40647ee2f817439d3858531fb0753c9d
 add_debug_postfix_on_mingw.patch 5116458a27323c83389ea15ddf12156e8f63e0ec
-cmake 3.19.2
+cmake 3.19.6
 cmake_dont_build_more_than_needed.patch 380b131349bf645f05637612e4a9a04ed8ba6349
 features core
 portfile.cmake f6bb80c53f45830cb9f72c5d6b27cad5bf154eba
 ports.cmake c969892a7210e71589dca21c1563c85b195a04bf
 post_build_checks 2
-powershell 7.1.1
+powershell 7.1.2
 triplet x64-windows-v141
 triplet_abi 3769d15368d152eb2b06b6b2a3bbc2cfc16a848e-a1c0eabb0c5177b6a8fb97a58ae398880c47b352-b9e2480dca17932aec14cc7258376a7b281aa769
 usage b446f7466dead962527355c13bbb617213098938

```
(traditional diff)
```diff
5c5
< cmake 3.19.2
---
> cmake 3.19.6
11c11
< powershell 7.1.1
---
> powershell 7.1.2

```

I will try to upgrade cmake and powershell and see if this helps, but I do think it should depend on major.minor versions only...

**Comment by JackBoosY** [comment]
> I think this problem will only happen if you use manifest mode & run `CMake Build` from the VSCode command palette (which use a [child process](https://github.com/microsoft/vscode-cmake-tools/blob/develop/src/proc.ts#L5) of the extension to run cmake), if I just use powershell to execute `.\vcpkg.exe install` icu or qt, it did succeed.

**Comment by meastp** [comment]
The problem that remains is that there is no way to force vcpkg to always use downloaded tools, and ignore system installed tools (explained in #vcpkg (slack) by @ras0219-msft). This is needed to have consistent versions between dev machine and ci, but there is currently no way to force this behaviour.

**Comment by strega-nil** [comment]
@BillyONeal don't use the words of power!

**Comment by JackBoosY** [comment]
Since we published the latest version, was this issue resolved?

**Comment by meastp** [comment]
@JackBoosY Not really - see this comment for what's missing: https://github.com/microsoft/vcpkg/issues/16615#issuecomment-813845762

**Comment by PhoebeHui** [comment]
The new triplet option VCPKG_DISABLE_COMPILER_TRACKING would be used to disable compiler tracking, and it should be included in next release. 

Related https://github.com/microsoft/vcpkg-tool/commit/5e55749af91660a404d3c8a3b44544a2706eb4bc

**Comment by meastp** [comment]
@PhoebeHui Isn't that for the compiler? Does it turn the entire abi_tracking off? What I need is the tools version to either be ignored or (ideally) forced to always downloaded through vcpkg - I still want the compiler version to be tracked.

**Comment by Be-ing** [comment]
I am also stumbling over this issue. vcpkg is using the version of cmake from the outside environment in the ABI info rather than the cmake version downloaded to vcpkg/downloads/tools.

**Comment by Be-ing** [comment]
I found the problem. vcpkg searches for tools from the system before downloading them. If the system tool version >= the minimum required version, vcpkg does not use the cmake version it downloads:
https://github.com/microsoft/vcpkg-tool/blob/cb1e40d6fe1a97ec4e29b79c3a0b4bcb02acc532/src/vcpkg/tools.cpp#L240

There is the VCPKG_FORCE_SYSTEM_BINARIES environment variable, but that does the opposite of what I want. I want vcpkg to *only* use the fetched version of cmake.

**Comment by Be-ing** [comment]
Wait... debug output does show that vcpkg uses the version of cmake it downloads?? Then why is that not used in the ABI info?

```
-- Installing port from location: /Users/be/sw/mixxx/vcpkg/overlay/osx/qt5-base
[DEBUG] Found path: /usr/local/bin/ninja
[DEBUG] popen(/Users/be/sw/mixxx/vcpkg/downloads/tools/ninja-1.10.2-osx/ninja --version 2>&1)
[DEBUG] cmd_execute_and_stream_data() returned 0 after    38586 us
[DEBUG] Found path: /usr/bin/git
[DEBUG] popen(/usr/bin/git --version 2>&1)
[DEBUG] cmd_execute_and_stream_data() returned 0 after    21592 us
[DEBUG] popen(/Users/be/sw/mixxx/vcpkg/downloads/tools/cmake-3.21.1-osx/cmake-3.21.1-macos-universal/CMake.app/Contents/bin/cmake -DALL_FEATURES= -DCURRENT_PORT_DIR=/Users/be/sw/mixxx/vcpkg/overlay/osx/qt5-base -D_HOST_TRIPLET=x64-osx -DFEATURES=core -DPORT=qt5-base -DVCPKG_USE_HEAD_VERSION=0 -D_VCPKG_DOWNLOAD_TOOL=BUILT_IN -D_VCPKG_EDITABLE=0 -D_VCPKG_NO_DOWNLOADS=0 -DCMD=BUILD -DDOWNLOADS=/Users/be/sw/mixxx/vcpkg/downloads -DTARGET_TRIPLET=x64-osx -DTARGET_TRIPLET_FILE=/Users/be/sw/mixxx/vcpkg/overlay/triplets/x64-osx.cmake -DVCPKG_BASE_VERSION=2021-08-03 -DVCPKG_CONCURRENCY=5 -DVCPKG_PLATFORM_TOOLSET=external -DGIT=/usr/bin/git -DVCPKG_ROOT_DIR=/Users/be/sw/mixxx/vcpkg -DPACKAGES_DIR=/Users/be/sw/mixxx/vcpkg/packages -DBUILDTREES_DIR=/Users/be/sw/mixxx/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=/Users/be/sw/mixxx/build/vcpkg_installed -DDOWNLOADS=/Users/be/sw/mixxx/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P /Users/be/sw/mixxx/vcpkg/scripts/ports.cmake 2>&1
```

**Comment by Be-ing** [comment]
Oh, nevermind, I got myself into a weird state by deleting vcpkg/downloads... 🙃 Not sure why I did that. vcpkg *does* use the version of cmake it downloads if I don't interfere with it 😆 

```
brew install cmake # installs CMake 3.21.3 currently
rm -rf vcpkg/vcpkg vcpkg/download build
# vcpkg bootstrap downloads CMake 3.21.1, matching the CI server
cmake -D VCPKG_INSTALL_OPTIONS="--debug" -S . -B build
```

Now it works.

**Comment by Be-ing** [comment]
@JoergAtGithub seems to be [dealing with](https://github.com/mixxxdj/mixxx/pull/4432#issuecomment-946137200) the same or similar issue on Windows with vcpkg on GitHub Actions using CMake 3.21.3 but locally vcpkg uses the copy of CMake 3.21.1 that it downloads.

**Comment by Be-ing** [comment]
> I still believe that always using a downloaded copy is incorrect; large initial downloads like that to use anything have been a consistent end user complaint which is why we try to use the system copy if it is new enough.

In general, this is good. Checking for a minimum required version of a tool and using the system's copy of the tool is appropriate in most cases. But it is not appropriate when the version of the tool is included in the cache key. IMO either vcpkg should unconditionally download its own copy of CMake or the CMake version should not be used in the cache key.

**Comment by Be-ing** [comment]
> I still believe that always using a downloaded copy is incorrect; large initial downloads like that to use anything have been a consistent end user complaint which is why we try to use the system copy if it is new enough.

In general, this is good. Checking for a minimum required version of a tool and using the system's copy of the tool is appropriate in most cases. But it is not appropriate when the version of the tool is included in the cache key. IMO either vcpkg should unconditionally download its own copy of CMake or the CMake version should not be used in the cache key.

**Comment by Be-ing** [comment]
This is finally fixed with https://github.com/microsoft/vcpkg-tool/pull/234 and https://github.com/microsoft/vcpkg/pull/21471. You need to use the new `--x-abi-tools-use-exact-versions` command line option in addition to disabling compiler tracking. So at the top of your CMakeLists.txt, before `project()`:

```
set(VCPKG_FEATURE_FLAGS "-compilertracking,manifests,registries,versions")
set(VCPKG_INSTALL_OPTIONS "--x-abi-tools-use-exact-versions")
```

**Comment by meastp** [comment]
@Be-ing Great, thanks! I didn't find documentation for the two features. Do I need to use the two in combination, or can I keep compiler tracking (I'm assuming this means the exact compiler version/update is ignored?) while using consistent versions of tools?

**Comment by ras0219-msft** [comment]
Yes, they should function independently so you can use one or the other (or both or neither). For changing compiler tracking, I recommend using the documented triplet variable `VCPKG_DISABLE_COMPILER_TRACKING` [1] instead of the experimental-by-design feature flags approach.

[1]: https://github.com/microsoft/vcpkg/blob/master/docs/users/triplets.md#vcpkg_disable_compiler_tracking

**Comment by Be-ing** [comment]
I was thinking these options should be combined into one, so I'm curious what kind of setup you have where including the compiler in the abi_info is desired but not the tool versions?

**Comment by meastp** [comment]
Thanks,both :) 

@Be-ing Well, the primary motivation for the tools feature is to be able to share binary caching between the Azure build agent and local developer machines. I still would like to trigger a rebuild when the compiler revision is changed. Since the build agent is the one that gets new compiler versions first (it's a Microsoft-Hosted Agent, so it is usually updated switfly), rebuilding do not affect us too much, and the binarycache is ready when devs upgrade their local compiler version.

How do you trigger a rebuild of the packages in case of a compiler bug? Perhaps VCPKG_DISABLE_COMPILER_TRACKING instead should be a version number that can be increased from 1 in case of this happening? Or have you solved this some other way?

**Comment by ras0219-msft** [comment]
We do hash the triplet file itself, so you can manually force a rebuild by changing a comment in the file. However, I generally would recommend against `VCPKG_DISABLE_COMPILER_TRACKING` if possible.
