### ISSUE TITLE
Add Blitz++

### ISSUE THREAD

**Issue by ivannp** [microsoft/vcpkg#1661]

**Comment by slayoo** [comment]
why is it closed? :)
for the record, Blitz++ is now hosted at github: http://github.com/blitzpp/blitz

**Comment by slayoo** [comment]
thanks, note that the blitzpp/blitz repo has Appveyor continuous integration set up using Visual Studio toolset - might be helpful

**Comment by slayoo** [comment]
also, when done let's add info here: https://github.com/blitzpp/blitz/wiki/Package-availability

**Comment by NancyLi1013** [comment]
Hi @ivannp and @slayoo thanks for posting this request.
`Blitz `has been added to vcpkg. Please update vcpkg and try to use it.

**Comment by slayoo** [comment]
Thank you!
I've added a reference to the wiki:
https://github.com/blitzpp/blitz/wiki/Package-availability

**Comment by slayoo** [comment]
@citibeth, @pguio, @papadop, @toddrme2178, @David-A-Blankenship, @AnderOne 
Good news!
