### ISSUE TITLE
[manifests] Simultaneous support for normal and head-only dependencies

### ISSUE THREAD

**Issue by PazerOP** [microsoft/vcpkg#16624]
****

**Is your feature request related to a problem? Please describe.**
After a brief discussion on the #include-cpp discord with @strega-nil about https://github.com/microsoft/vcpkg/pull/16613 and https://github.com/microsoft/vcpkg-tool/pull/24, she suggested I create this issue.

As mentioned in #16613, I am developing a library of shared code for use in personal projects, and I really do want to be using the newest version of my code at all times (aka the behavior of `--head`). The alternative is updating versions, sha hashes, and git refs for personal ports for every commit to a shared library. Of course, that could be automated, but it is ultimately doing a lot of work just to get the behavior of `--head`.

This is an issue because currently, head-only ports require that you pass `--head` on the command line to vcpkg. But when using manifests with the CMake toolchain, all ports are installed at once, so you are forced to have all your dependencies on head revisions if you have a single head-only dependency.

I fully understand the view that head-only ports can be undesirable for "real" ports, but I still believe there is a valid use case for them for individual or small projects.

**Proposed solution**
https://github.com/microsoft/vcpkg/pull/16613 and https://github.com/microsoft/vcpkg-tool/pull/24 provide a solution that works automatically, but that approach loses the explicitness of the previous `--head` experience when installing libraries. Perhaps the manifests json could have a `head` property added instead?
```json
{
  "name": "example",
  "version-string": "0.0.1",
  "dependencies": [
    "fmt"
    {
      "name": "nlohmann-json",
      "head": true
    }
  ]
}
```

**Describe alternatives you've considered**
If this feature request does not align with the goals of vcpkg, I plan to return to git submodules for these kinds of frequently-updated dependencies. However, I find submodules to be difficult and/or confusing to manage once you start having nested submodules. For example, if two submodule dependencies `A` and `B` use submodules themselves to satisfy a dependency on `C`, there will now be two instances of the `C` repo in the project. vcpkg can handle this situation easily, as well as providing advanced functionality like binarycaching.

**Comment by strega-nil** [comment]
I am personally of the opinion that the solution given is the correct solution. Adding requires:discussion so that we can discuss it on Thursday.

**Comment by PazerOP** [comment]
> the solution given
@strega-nil Do you mean the existing PRs I submitted, or the manifest json proposed solution?

**Comment by ras0219-msft** [comment]
Have you considered `FetchContent()`? https://cmake.org/cmake/help/latest/module/FetchContent.html

I think this will do more along the lines of what you want: several unversioned, experimental pieces. You'll still need to `union` the set of external dependencies yourself into each repo's `vcpkg.json`.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

**Comment by ChilledCosmonaut** [comment]
@JackBoosY and @strega-nil is planned to integrate this feature still or should one just default back to fetch_content?
I really think that it would benefit private registries as they are most often used for internal bleeding edge development as well.

**Comment by strega-nil** [comment]
I don't know anything about this, I'm no longer on the team that works on this product :)

**Comment by ChilledCosmonaut** [comment]
Oh sorry. Didn't know! 😅
