### ISSUE TITLE
Unable to install Xerces-c

### ISSUE THREAD

**Issue by jubrane** [microsoft/vcpkg#16620]
Error: Building package xerces-c:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: xerces-c:x86-windows
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

**Comment by JonLiu1993** [comment]
Hi @jubrane ,Thanks for posting this issue,Please attach the error logs.

**Comment by JonLiu1993** [comment]
@jubrane ,Please attach the error logs.

**Comment by PhoebeHui** [comment]
@jubrane, please provide us full failure logs if it still be a problem for you.
