### ISSUE TITLE
install llvm error

### ISSUE THREAD

**Issue by 276585877** [Microsoft/vcpkg#1662]
Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:170 (vcpkg_execute_required_process

  ports/llvm/portfile.cmake:19 (vcpkg_configure_cmake)
  scripts/ports.cmake:72 (include)

Error: Building package llvm:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: llvm:x86-windows
  Vcpkg version: 0.0.83-unknownhash

**Comment by KindDragon** [comment]
Please add log files

**Comment by 276585877** [comment]
openssl also error   
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:43 (message):
    Command failed: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/a
md64/nmake.exe;-f;ms\ntdll.mak;install
    Working Directory: D:/vcpkg/buildtrees/openssl/x86-windows-rel/openssl-1.0.2
l
    See logs for more information:
      D:\vcpkg\buildtrees\openssl\build-x86-windows-rel-1-out.log
      D:\vcpkg\buildtrees\openssl\build-x86-windows-rel-1-err.log

Call Stack (most recent call first):
  ports/openssl/portfile.cmake:85 (vcpkg_execute_required_process)
  scripts/ports.cmake:72 (include)

LOg:
jom 1.1.2 - empower your cores

jom: Option /K specified. Continuing.
jom: Option /K specified. Continuing.
jom: D:\vcpkg\buildtrees\openssl\x86-windows-rel\openssl-1.0.2l\ms\ntdll.mak [tmp32dll\uplink.obj] Error 2
jom: Option /K specified. Continuing.
jom: D:\vcpkg\buildtrees\openssl\x86-windows-rel\openssl-1.0.2l\ms\ntdll.mak [tmp32dll\mem_dbg.obj] Error 2
jom: D:\vcpkg\buildtrees\openssl\x86-windows-rel\openssl-1.0.2l\ms\ntdll.mak [tmp32dll\cryptlib.obj] Error 2
jom: Option /K specified. Continuing.
jom: D:\vcpkg\buildtrees\openssl\x86-windows-rel\openssl-1.0.2l\ms\ntdll.mak [tmp32dll\mem.obj] Error 2
jom: Option /K specified. Continuing.
jom: D:\vcpkg\buildtrees\openssl\x86-windows-rel\openssl-1.0.2l\ms\ntdll.mak [tmp32dll\ex_data.obj] Error 2
jom: Option /K specified. Continuing.
jom: D:\vcpkg\buildtrees\openssl\x86-windows-rel\openssl-1.0.2l\ms\ntdll.mak [tmp32dll\cpt_err.obj] Error 2
jom: Option /K specified. Continuing.
jom: D:\vcpkg\buildtrees\openssl\x86-windows-rel\openssl-1.0.2l\ms\ntdll.mak [tmp32dll\uid.obj] Error 2
jom: Option /K specified. Continuing.
jom: D:\vcpkg\buildtrees\openssl\x86-windows-rel\openssl-1.0.2l\ms\ntdll.mak [tmp32dll\cversion.obj] Error 2
jom: D:\vcpkg\buildtrees\openssl\x86-windows-rel\openssl-1.0.2l\ms\ntdll.mak [tmp32dll\o_time.obj] Error 2
jom: Option /K specified. Continuing.
jom: D:\vcpkg\buildtrees\openssl\x86-windows-rel\openssl-1.0.2l\ms\ntdll.mak [tmp32dll\o_str.obj] Error 2
jom: Option /K specified. Continuing.
jom: D:\vcpkg\buildtrees\openssl\x86-windows-rel\openssl-1.0.2l\ms\ntdll.mak [tmp32dll\o_dir.obj] Error 2
jom: Option /K specified. Continuing.
jom: D:\vcpkg\buildtrees\openssl\x86-windows-rel\openssl-1.0.2l\ms\ntdll.mak [tmp32dll\o_fips.obj] Error 2
jom: Option /K specified. Continuing.
jom: D:\vcpkg\buildtrees\openssl\x86-windows-rel\openssl-1.0.2l\ms\ntdll.mak [tmp32dll\o_init.obj] Error 2
jom: Option /K specified. Continuing.
jom: D:\vcpkg\buildtrees\openssl\x86-windows-rel\openssl-1.0.2l\ms\ntdll.mak [tmp32dll\md4_dgst.obj] Error 2
jom: Option /K specified. Continuing.
jom: D:\vcpkg\buildtrees\openssl\x86-windows-rel\openssl-1.0.2l\ms\ntdll.mak [tmp32dll\md4_one.obj] Error 2
jom: Option /K specified. Continuing.
jom: D:\vcpkg\buildtrees\openssl\x86-windows-rel\openssl-1.0.2l\ms\ntdll.mak [tmp32dll\md5_dgst.obj] Error 2
jom: Option /K specified. Continuing.
jom: D:\vcpkg\buildtrees\openssl\x86-windows-rel\openssl-1.0.2l\ms\ntdll.mak [tmp32dll\md5_one.obj] Error 2
jom: Option /K specified. Continuing.
jom: D:\vcpkg\buildtrees\openssl\x86-windows-rel\openssl-1.0.2l\ms\ntdll.mak [tmp32dll\sha_dgst.obj] Error 2
jom: Option /K specified. Continuing.
jom: D:\vcpkg\buildtrees\openssl\x86-windows-rel\openssl-1.0.2l\ms\ntdll.mak [tmp32dll\sha1dgst.obj] Error 2
jom: Option /K specified. Continuing.
jom: D:\vcpkg\buildtrees\openssl\x86-windows-rel\openssl-1.0.2l\ms\ntdll.mak [tmp32dll\sha_one.obj] Error 2

**Comment by 276585877** [comment]
llvm log :
CMake Error at D:/vcpkg-master/downloads/cmake-3.9.1-win32-x86/share/cmake-3.8/Modules/CMakeTestCCompiler.cmake:51 (message):
  The C compiler "C:/Program Files (x86)/Microsoft Visual Studio
  14.0/VC/bin/amd64_x86/cl.exe" is not able to compile a simple test program.

  It fails with the following output:

   Change Dir: D:/vcpkg-master/buildtrees/llvm/x86-windows-rel/CMakeFiles/CMakeTmp

  

  Run Build
  Command:"D:/vcpkg-master/downloads/tools/ninja/ninja-1.7.2/ninja.exe"
  "cmTC_103f8"

  [1/2] Building C object CMakeFiles\cmTC_103f8.dir\testCCompiler.c.obj

  [2/2] Linking C executable cmTC_103f8.exe

  FAILED: cmTC_103f8.exe 

  cmd.exe /C "cd .  &&
  D:\vcpkg-master\downloads\cmake-3.9.1-win32-x86\bin\cmake.exe -E
  vs_link_exe --intdir=CMakeFiles\cmTC_103f8.dir --manifests --
  C:\PROGRA~2\MICROS~3.0\VC\bin\AMD64_~2\link.exe /nologo
  CMakeFiles\cmTC_103f8.dir\testCCompiler.c.obj /out:cmTC_103f8.exe
  /implib:cmTC_103f8.lib /pdb:cmTC_103f8.pdb /version:0.0 /machine:X86 /debug
  /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib
  winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib
  advapi32.lib && cmd.exe /C "cd /D
  D:\vcpkg-master\buildtrees\llvm\x86-windows-rel\CMakeFiles\CMakeTmp &&
  powershell -noprofile -executionpolicy Bypass -file
  D:/vcpkg-master/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary
  D:/vcpkg-master/buildtrees/llvm/x86-windows-rel/CMakeFiles/CMakeTmp/cmTC_103f8.exe
  -installedDir D:/vcpkg-master/installed/x86-windows/debug/bin -OutVariable
  out""

  LINK : fatal error LNK1104: 鏃犳硶鎵撳紑鏂囦欢鈥渦crtd.lib鈥?

  LINK Pass 1 failed.  with 1104

  ninja: build stopped: subcommand failed.

  

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:47 (project)

**Comment by yuehuang010** [comment]
I hit this same issue, Link.exe uses 5-6GB each.  So on a 4 core machine, you will need 20gb.  
Try turning on Disk Page Memory (aka Windows Virtual Memory) and restart your computer to take effect.

**Comment by JackBoosY** [comment]
Hi @276585877 , thanks for reporting this issue!
Please open a new issue if this is still a problem for you.
Thx.
