### ISSUE TITLE
[magic-enum] build failure

### ISSUE THREAD

**Issue by jdx-john** [microsoft/vcpkg#16623]
I'm on a clean install of vcpkg on a network drive (setting up our build machine which has no internet). I'm running `vcpkg install magic-enum --only-downloads` as my first action after bootstrapping

> B:\vcpkg>vcpkg install magic-enum --only-downloads
> Computing installation plan...
> A suitable version of cmake was not found (required v3.19.2). Downloading portable cmake v3.19.2...
> Downloading cmake...
>   https://github.com/Kitware/CMake/releases/download/v3.19.2/cmake-3.19.2-win32-x86.zip -> B:\vcpkg\downloads\cmake-3.19.2-win32-x86.zip
> Extracting cmake...
> A suitable version of 7zip was not found (required v18.1.0). Downloading portable 7zip v18.1.0...
> Downloading 7zip...
>   https://www.nuget.org/api/v2/package/7-Zip.CommandLine/18.1.0 -> B:\vcpkg\downloads\7-zip.commandline.18.1.0.nupkg
> Extracting 7zip...
> A suitable version of nuget was not found (required v5.5.1). Downloading portable nuget v5.5.1...
> Downloading nuget...
>   https://dist.nuget.org/win-x86-commandline/v5.5.1/nuget.exe -> B:\vcpkg\downloads\22ea847d-nuget.exe
> The following packages will be built and installed:
>     magic-enum[core]:x86-windows -> 0.7.2
> Detecting compiler hash for triplet x86-windows...
> A suitable version of powershell-core was not found (required v7.1.0). Downloading portable powershell-core v7.1.0...
> Downloading powershell-core...
>   https://github.com/PowerShell/PowerShell/releases/download/v7.1.0/PowerShell-7.1.0-win-x86.zip -> B:\vcpkg\downloads\PowerShell-7.1.0-win-x86.zip
> Extracting powershell-core...
> Error: while detecting compiler information:
> The log content at B:\vcpkg\buildtrees\detect_compiler\stdout-x86-windows.log is:
> -- Found ninja('1.8.2') but at least version 1.10.1 is required! Trying to use internal version if possible!
> -- Downloading https://github.com/ninja-build/ninja/releases/download/v1.10.1/ninja-win.zip -> ninja-win-1.10.1.zip...
> -- Configuring x86-windows
> CMake Error at //ntsbuild/c$/vcpkg/scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
>     Command failed: ninja -v
>     Working Directory: B:/vcpkg/buildtrees/detect_compiler/x86-windows-rel/vcpkg-parallel-configure
>     Error code: 1
>     See logs for more information:
>       B:\vcpkg\buildtrees\detect_compiler\config-x86-windows-err.log
> 
> Call Stack (most recent call first):
>   //ntsbuild/c$/vcpkg/scripts/cmake/vcpkg_configure_cmake.cmake:324 (vcpkg_execute_required_process)
>   scripts/detect_compiler/portfile.cmake:18 (vcpkg_configure_cmake)
>   //ntsbuild/c$/vcpkg/scripts/ports.cmake:139 (include)
> 
> 
> 
> Error: vcpkg was unable to detect the active compiler's information. See above for the CMake failure output.

If I'm not compiling, why is it even trying to detect the compiler anyway? I am doing this on a PC which already has vcplkg working just fine, so I definitely have VS 2019 present and correct

**Comment by NancyLi1013** [comment]
Closing this issue for inactive thread. Please feel free to reopen this issue if it is still a problem for you.
