### ISSUE TITLE
How do I ...No suitable Visual Studio instances were found

### ISSUE THREAD

**Issue by andyzhshg** [microsoft/vcpkg#16638]
When asking a question please also include where you looked for an answer (so we can update the documentation if needed).

I have visual studio 2019 installed.

vcpkg returns this error when I try to install any library.

```
PS C:\develop\vcpkg> vcpkg install openssl
Computing installation plan...
The following packages will be built and installed:
    openssl[core]:x86-windows -> 1.1.1i
No suitable Visual Studio instances were found
PS C:\develop\vcpkg>
```

**Comment by JonLiu1993** [comment]
Hi @andyzhshg ,Thanks for posting this issue ，Is the Visual Studio you installed in English? If not, please install the English version and try again

**Comment by andyzhshg** [comment]
> Hi @andyzhshg ,Thanks for posting this issue ，Is the Visual Studio you installed in English? If not, please install the English version and try again

Thanks for replying.

Yes, my installation is in English. But my windows system is in Chinese. The Visual Studio installer is in Chinese, but I didn't install Chinese language pack, I choose to install English language pack only.

**Comment by andyzhshg** [comment]
I solved this problem by uninstall and then reinstall Visual Studio.

**Comment by tecandrew** [comment]
Seeing this error, but in a Windows Container environment using https://hub.docker.com/_/microsoft-dotnet-framework-sdk as a base image.

it has the `Visual Studio Build Tools`, but vcpkg doesn't seem to see this as a valid compiler.
