### ISSUE TITLE
[arm64-osx] Multi-arch triplets result in a CMake error

### ISSUE THREAD

**Issue by omartijn** [microsoft/vcpkg#16637]
**Describe the bug**
Setting multiple architectures in triplet file results in an error.

**Environment**
- OS: macOS Big Sur
- Compiler: Apple clang version 12.0.0 (clang-1200.0.32.29)

**To Reproduce**
1. Create a new triplet file, copied from `triplets/community/arm64-osx.cmake`
2. Change the last line (containing `VCPKG_OSX_ARCHITECTURES`) to contain both archs: `set(VCPKG_OSX_ARCHITECTURES "arm64;x86_64")`
3. Try to install any package.

**Expected behavior**
The package should build

**Failure logs** 
```
CMake Error: The source directory "/Users/omartijn/git/vcpkg/buildtrees/detect_compiler/universal-osx-rel/x86_64" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
```

**Additional context**
According to the docs, th `VCPKG_OSX_ARCHITECTURES` maps directory to `CMAKE_OSX_ARCHITECTURES`, which works just fine with multiple architectures set.

**Comment by omartijn** [comment]
Unless I'm misunderstanding something, the issue category "community triplet" is for issues where a community triplet doesn't work for some port. That's not the case here. Multi-arch triplets don't work _at all_, due to a bug in vcpkg.

I believe the issue category is therefore wrong. It's a vcpkg bug, not a triplet bug. Can this be changed?

**Comment by PhoebeHui** [comment]
@omartijn, sorry for misunderstand the issue, could you attach full failure log?

I'm not sure if it supports in vcpkg now, @vicroms, could you help confirm?

**Comment by omartijn** [comment]
[config-universal-osx-rel-err.log](https://github.com/microsoft/vcpkg/files/6196528/config-universal-osx-rel-err.log)
[vcpkg.log](https://github.com/microsoft/vcpkg/files/6196529/vcpkg.log)

I added the output from running vcpkg, as well as the file containing additional information mentioned in the output.

Looking at the vcpkg it looks like the error is that the `detect_compiler` script is run with incorrect arguments. The `CMAKE_OSX_ARCHITECTURES` argument (which is an array for multi-arch builds) is split, with the second option (x86_64) just being passed as a standalone parameter.

If I manually go to the referenced directory (buildtrees/detect_compiler/universal-osx-rel) and execute the command with fixed parameters it completes successfully (albeit with a number of warnings about manually-specified variables not being used by the project).

**Comment by omartijn** [comment]
Could somebody with access please fix the labels? This issue is still misclassified as 'community triplet', while it's an actual bug in vcpkg itself.

**Comment by PhoebeHui** [comment]
Duplicated of https://github.com/microsoft/vcpkg/issues/14932.
