### ISSUE TITLE
cudnn support for 8.x 

### ISSUE THREAD

**Issue by IlTeo285** [microsoft/vcpkg#16636]
With the new RTX 30x0 GPU family it is necessary to use **CUDA 11.x + cudnn 8.x**
Currently, building opencv4 with the cuda backend fails due to the cudnn port being referenced to cudnn 7.6

I can build opencv4 modyfing (quickly and dirty) the cudnn port with these major changes:

- downloading the package from [https://anaconda.org/conda-forge/cudnn/8.1.0.77/download/win-64/cudnn-8.1.0.77-h3e0f4f4_0.tar.bz2](https://anaconda.org/conda-forge/cudnn/8.1.0.77/download/win-64/cudnn-8.1.0.77-h3e0f4f4_0.tar.bz2)
`    set(CUDNN_DOWNLOAD_LINK "https://anaconda.org/conda-forge/cudnn/8.1.0.77/download/win-64/cudnn-8.1.0.77-h3e0f4f4_0.tar.bz2")
    set(SHA512_CUDNN "820fcd1986eba673f2821f16c20c4ae97f444488d3e03ba11b307e59678b0e141ed39235f0396433b3c63e2d901902a8096175fe91391be24104e9eb5dcb9cb1")
    set(CUDNN_OS "windows")`
- With cuda 11 Nvidia splits header and lib files across multiple files. It's now required to install all of them 
`    file(INSTALL "${SOURCE_PATH}/Library/include/" DESTINATION ${CURRENT_PACKAGES_DIR}/include FILES_MATCHING PATTERN "*.h")
    file(INSTALL "${SOURCE_PATH}/Library/lib/" DESTINATION ${CURRENT_PACKAGES_DIR}/lib FILES_MATCHING PATTERN "*.lib")
    file(INSTALL "${SOURCE_PATH}/Library/bin/" DESTINATION ${CURRENT_PACKAGES_DIR}/bin FILES_MATCHING PATTERN "*.dll")`

- Nvidia rename license and change path.
`file(INSTALL "${SOURCE_PATH}/info/licenses/NVIDIA_SLA_cuDNN_Support.txt" DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)`

I hope this could help in speeding up the update of portfile in order to make it working with new cuda & cudnn

**Comment by NancyLi1013** [comment]
Hi @IlTeo285 

Thanks for posting this issue.

It seems that you have further investigation about this. Would you like to create a pull request to update `cudnn`?

**Comment by IlTeo285** [comment]
Hi @NancyLi1013,

I'm no so skilled in CMake but I'm gonna try

**Comment by FrankXie05** [comment]
@IlTeo285 Is still work for this issue? At present, `cudnn` will keep the old version open, and will not be updated for the time being. According to the current prorfile, it will automatically match the local cudnn version.  :)

**Comment by FrankXie05** [comment]
This issue hasn’t been updated for a long time; if it is still an issue, please reopen this issue.
