### ISSUE TITLE
Error: Building package opencv[eigen,ffmpeg,webp,contrib,nonFree,cuda]:x64-windows failed with: BUILD_FAILED, when installing OMPL

### ISSUE THREAD

**Issue by HaoChenga** [microsoft/vcpkg#16639]
I'm sorry to trouble you. When I was building OpenCV, I met two problems. One was why it appeared "-- Restarting Build without parallelism because memory exceeded", and how it could be solved.
Second question, why it appeared "LINK: fatal error LNK1104: cannot open file 'bin\opencv_highguid.dll"
Looking forward to the answer, thanks!

-- Restarting Build without parallelism because memory exceeded
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:144 (message):
    Command failed: D:/Lab_programm/ThirdLib/vcpkg/downloads/tools/cmake-3.19.2-windows/cmake-3.19.2-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v -j9
    Working Directory: D:/Lab_programm/ThirdLib/vcpkg/buildtrees/opencv4/x64-windows-dbg
    See logs for more information:
      D:\Lab_programm\ThirdLib\vcpkg\buildtrees\opencv4\install-x64-windows-dbg-out.log
      D:\Lab_programm\ThirdLib\vcpkg\buildtrees\opencv4\install-x64-windows-dbg-out-1.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:105 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:45 (vcpkg_build_cmake)
  ports/opencv4/portfile.cmake:385 (vcpkg_install_cmake)
  scripts/ports.cmake:139 (include)

install-x64-windows-dbg-out.log:iFINAL LINK: command "C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1428~1.293\bin\Hostx64\x64\link.exe modules\highgui\CMakeFiles\opencv_highgui.dir\src\window.cpp.obj modules\highgui\CMakeFiles\opencv_highgui.dir\src\roiSelector.cpp.obj modules\highgui\CMakeFiles\opencv_highgui.dir\src\window_w32.cpp.obj modules\highgui\CMakeFiles\opencv_highgui.dir\vs_version.rc.res modules\highgui\CMakeFiles\opencv_highgui.dir\opencv_highgui_main.cpp.obj /out:bin\opencv_highguid.dll /implib:lib\opencv_highguid.lib /pdb:bin\opencv_highguid.pdb /dll /version:4.5 /machine:x64 /nologo /debug /INCREMENTAL /NODEFAULTLIB:atlthunk.lib /NODEFAULTLIB:atlsd.lib /NODEFAULTLIB:libcmt.lib /DEBUG lib\opencv_videoiod.lib comctl32.lib gdi32.lib ole32.lib setupapi.lib ws2_32.lib lib\opencv_imgcodecsd.lib lib\opencv_imgprocd.lib lib\opencv_cored.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:modules\highgui\CMakeFiles\opencv_highgui.dir/intermediate.manifest modules\highgui\CMakeFiles\opencv_highgui.dir/manifest.res" failed (exit code 1104) with the following output:
**LINK : fatal error LNK1104: cannot open file 'bin\opencv_highguid.dll'**

**Comment by HaoChenga** [comment]
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/6116518/install-x64-windows-dbg-out.log)
[install-x64-windows-dbg-out-1.log](https://github.com/microsoft/vcpkg/files/6116521/install-x64-windows-dbg-out-1.log)

**Comment by NancyLi1013** [comment]
Hi @HaoChenga 

Thanks for posting this issue.

For your first question:

`- Restarting Build without parallelism because memory exceeded`

I'm not sure what the root cause of this problem is. There are also someone else encountering the same problem. 
Could you please help confirm if you have installed security software on your machine? Please see the details here https://github.com/microsoft/vcpkg/issues/7543#issuecomment-535782536

For your second question:

`LINK: fatal error LNK1104: cannot open file 'bin\opencv_highguid.dll`

This linker error may be related with your first problem. Since it failed to build successfully, which will cause some unexpected errors like this.

**Comment by HaoChenga** [comment]
Thank you for your answer. It worked well after the security software was turned off.

**Comment by adamgranthendry** [comment]
I'm confused. Is this a false negative? I have more than plenty of RAM on my machine (192 GB), but please let me know. I receive this message when running

```bash
> vcpkg install itk[cuda,cufftw,opencl,python,rtk,tbb,tools,vtk] --recurse
```

and I have set `VTK_DEFAULT_TRIPLET` to `x64-windows`.

If not, what needs to be done to fix this "error"? In lines `119-123` of the `itk` `portfile.cmake` file:

```cmake
file(REMOVE_RECURSE "${SOURCE_PATH}/CMake/FindOpenCL.cmake")
vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA
    DISABLE_PARALLEL_CONFIGURE
```

**Comment by NancyLi1013** [comment]
Please check if you installed any antivirus software on your machine.

**Comment by adamgranthendry** [comment]
@NancyLi1013 

1. Who are you asking?
2. Why are you asking this?
3. How does this answer the question?

**Comment by NancyLi1013** [comment]
> @NancyLi1013
> 
> 1. Who are you asking?


I'm asking you.
> 2. Why are you asking this?

Maybe I misunderstand your question above. Since you comment here, I thought you have the same problem as the original one. 
`- Restarting Build without parallelism because memory exceeded` or
`LINK: fatal error LNK1104: cannot open file 'bin\opencv_highguid.dll`

So I commented to check  antivirus software.

> 3. How does this answer the question?
But seems you have the different problem. Is your confusion that why you met the message?

`vcpkg install itk[cuda,cufftw,opencl,python,rtk,tbb,tools,vtk] --recurse`

If not, please describe your problems more clearly.

Thanks.

**Comment by adamgranthendry** [comment]
@NancyLi1013 My question is whether this is actually a false negative. Also, my antivirus is turned off.

**Comment by NancyLi1013** [comment]
`> vcpkg install itk[cuda,cufftw,opencl,python,rtk,tbb,tools,vtk] --recurse`

This message means some ports will be removed and then some ports need to be rebuilt in installing.

This is intended behavior, which is not related with your disk space.

If some ports have been installed on your machine before you update to the latest vcpkg. And these ports also been updated in the latest vcpkg. In this case, these ports will be rebuilt if you install the port that depends on these ports.

**Comment by adamgranthendry** [comment]
@NancyLi1013 Correct, but I am still getting the message

```
- Restarting Build without parallelism because memory exceeded
```

even with antivirus turned off.

**Comment by NancyLi1013** [comment]
You can check the install log to confirm if it is due to out of memory.
