### ISSUE TITLE
assimp:x64-linux build failure

### ISSUE THREAD

**Issue by raul-physna** [microsoft/vcpkg#16634]
**Host Environment**
- Ubuntu 18.04
- g++ 10.2.0

**To Reproduce**
`./vcpkg install assimp`

**Failure logs** 
Starting package 4/11: irrlicht:x64-linux
Building package irrlicht[core]:x64-linux...
-- Trying auto-select mirror...
-- Downloading https://sourceforge.net/projects/irrlicht/files/Irrlicht%20SDK/1.8/1.8.4/irrlicht-1.8.4.zip/download -> irrlicht-1.8.4.zip...
-- Skipping hash check for /opt/app/mojo/3rdparty/vcpkg/downloads/temp/irrlicht-1.8.4.zip.
-- The default mirror is in Disaster Recovery mode, trying other mirrors...
-- Trying mirror cfhcable...
-- Using cached /opt/app/mojo/3rdparty/vcpkg/downloads/irrlicht-1.8.4.zip
-- Skipping hash check for /opt/app/mojo/3rdparty/vcpkg/downloads/irrlicht-1.8.4.zip.
-- Extracting source /opt/app/mojo/3rdparty/vcpkg/downloads/irrlicht-1.8.4.zip
-- Applying patch fix-encoding.patch
-- Applying patch fix-sysctl.patch
-- Using source at /opt/app/mojo/3rdparty/vcpkg/buildtrees/irrlicht/src/de69ddd2c6-1cdb4cb3bd.clean
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:144 (message):
    Command failed: /opt/app/mojo/3rdparty/vcpkg/downloads/tools/cmake-3.19.2-linux/cmake-3.19.2-Linux-x86_64/bin/cmake --build . --config Debug --target install -- -v -j7
    Working Directory: /opt/app/mojo/3rdparty/vcpkg/buildtrees/irrlicht/x64-linux-dbg
    See logs for more information:
      /opt/app/mojo/3rdparty/vcpkg/buildtrees/irrlicht/install-x64-linux-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:105 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:45 (vcpkg_build_cmake)
  ports/irrlicht/portfile.cmake:32 (vcpkg_install_cmake)
  scripts/ports.cmake:139 (include)

Error: Building package irrlicht:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: irrlicht:x64-linux
  Vcpkg version: 2021-01-13-unknownhash

[install-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/6113230/install-x64-linux-dbg-out.log)

**Comment by NancyLi1013** [comment]
Hi @raul-physna 

Thanks for posting this issue.

```
/opt/app/mojo/3rdparty/vcpkg/buildtrees/irrlicht/src/de69ddd2c6-1cdb4cb3bd.clean/source/Irrlicht/CIrrDeviceLinux.h:21:10: fatal error: GL/gl.h: No such file or directory
   21 | #include <GL/gl.h>
      |          ^~~~~~~~~
compilation terminated.
```
Seems you missed <GL/gl.h> on your machine.

Could you please try to run `sudo apt-get install libglfw3-dev libgl1-mesa-dev libglu1-mesa-dev` and then rebuild `assimp`?

**Comment by raul-physna** [comment]
Hi @NancyLi1013 , thank you for the guidance! Running the apt-get statements fixed the issue and I'm able to compile `assimp` successfully now.
