### ISSUE TITLE
[opencascade] Linking against wrong freetype build type

### ISSUE THREAD

**Issue by marekr** [microsoft/vcpkg#16648]
Opencascade is currently linking agaisnt "freetype.dll" instead of "freetyped.dll" for debug libraries.

![image](https://user-images.githubusercontent.com/1838013/110740492-24dd6780-8201-11eb-9b4f-c27ff88cec04.png)

Just leaving the footnote here, I will probably try and submit a PR for it later

**Comment by JonLiu1993** [comment]
Hi @marekr ,Thanks for posting this issue,
