### ISSUE TITLE
[boost-json] CMake integration not working

### ISSUE THREAD

**Issue by mark-harsch** [microsoft/vcpkg#16644]
**Describe the bug**
I want to use the boost-json library only and try to integrate it into my CMakeLists.txt as described by the package itself after proper installation through vcpkg

Statement after installation:
```
The package boost is compatible with built-in CMake targets:

    find_package(Boost REQUIRED [COMPONENTS <libs>...])
    target_link_libraries(main PRIVATE Boost::boost Boost::<lib1> Boost::<lib2> ...)
```
How I apply it:
```
find_package(Boost REQUIRED COMPONENTS json)
target_link_libraries(${PROJECT_NAME} PRIVATE Boost::boost Boost::json)
```
However I get errors reported by CMake (see error log section).
For other libraries like cpr or cpprestsdk the integration was already possible (and cpr is still in use).

**Environment**
- OS: Linux (Fedora 33)
- Compiler: clang11
- IDE/Editor: Visual Studio Code with CMake Tools

**To Reproduce**
1. ./vcpkg install boost-json
2. See error
Repro code when

**Expected behavior**
I would expect that when I add the library according to the information provided after installation it works out of the box.
In the same CMakeLists.txt I use cpr library without any issues.

**Failure logs** 
```
[cmake] CMake Warning at /usr/share/cmake/Modules/FindBoost.cmake:1187 (message):
[cmake]   New Boost version may have incorrect or missing dependencies and imported
[cmake]   targets
[cmake] Call Stack (most recent call first):
[cmake]   /usr/share/cmake/Modules/FindBoost.cmake:1311 (_Boost_COMPONENT_DEPENDENCIES)
[cmake]   /usr/share/cmake/Modules/FindBoost.cmake:1919 (_Boost_MISSING_DEPENDENCIES)
[cmake]   /home/mark/bin/vcpkg/scripts/buildsystems/vcpkg.cmake:824 (_find_package)
[cmake]   CMakeLists.txt:30 (find_package)
[cmake] 
[cmake] 
[cmake] CMake Warning at /usr/share/cmake/Modules/FindBoost.cmake:2018 (message):
[cmake]   No header defined for json; skipping header check (note: header-only
[cmake]   libraries have no designated component)
[cmake] Call Stack (most recent call first):
[cmake]   /home/mark/bin/vcpkg/scripts/buildsystems/vcpkg.cmake:824 (_find_package)
[cmake]   CMakeLists.txt:30 (find_package)
[cmake] 
[cmake] 
[cmake] CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
[cmake]   Could NOT find Boost (missing: json) (found version "1.75.0")
[cmake] Call Stack (most recent call first):
[cmake]   /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
[cmake]   /usr/share/cmake/Modules/FindBoost.cmake:2177 (find_package_handle_standard_args)
[cmake]   /home/mark/bin/vcpkg/scripts/buildsystems/vcpkg.cmake:824 (_find_package)
[cmake]   CMakeLists.txt:30 (find_package)
```

**Additional context**
As reference my current CMakeLists.txt:
```
cmake_minimum_required(VERSION 3.10.0)
project(weatherapp VERSION 0.1.0)

set(CPACK_PROJECT_NAME ${PROJECT_NAME})
set(CPACK_PROJECT_VERSION ${PROJECT_VERSION})
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)


# App files and executable
include_directories(
src
src/parsing
src/ui
src/weatherservice
)

file(GLOB SOURCES
src/*.cpp
src/**/*.cpp
)

add_executable(${PROJECT_NAME} ${SOURCES})

# vcpkg libraries used
include($ENV{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake)
find_package(cpr CONFIG REQUIRED)
target_link_libraries(${PROJECT_NAME} PRIVATE cpr)
find_package(Boost REQUIRED COMPONENTS json)
target_link_libraries(${PROJECT_NAME} PRIVATE Boost::boost Boost::json)
```
VS Code settings.json:
```
    "cmake.configureSettings": {
        "CMAKE_TOOLCHAIN_FILE": "/home/mark/bin/vcpkg/scripts/buildsystems/vcpkg.cmake"
    }
```

**Comment by PhoebeHui** [comment]
@mark-harsch, boost-json is header only, it depends on boost-container, could you try the following code instead?

```
find_package(Boost REQUIRED COMPONENTS container)
target_link_libraries(main PRIVATE ${Boost_LIBRARIES})
target_include_directories(main PRIVATE ${Boost_INCLUDE_DIRS})
```

**Comment by mark-harsch** [comment]
@PhoebeHui: Thanks for your fast reply. As I understood the [documentation](https://www.boost.org/doc/libs/1_75_0/libs/json/doc/html/json/overview.html), header-only is just an option but maybe my understanding here is wrong (using boost the first time).

I managed to get it working as followed:
Usage in Code:
```C++
#include <boost/json/src.hpp> // header-only usage of Boost.JSON
```
CMakeLists.txt
```
find_package(Boost REQUIRED)
target_link_libraries(${PROJECT_NAME} PRIVATE Boost::boost)
```
Strangely it even works without adding the two statements in my CMakeLists.txt. Could it be the case that cmake is retrieving it from another place than from vcpkg (also not that familiar with cmake and what default paths for includes/libs it maybe considers implicitly)?
I double checked that cmake is invoked with respective value for `CMAKE_TOOLCHAIN_FILE` and it is like you can see as followed:
```
[proc] Befehl wird ausgeführt: /usr/bin/cmake --no-warn-unused-cli -DCMAKE_TOOLCHAIN_FILE:STRING=/home/mark/bin/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/clang-11 -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/clang++-11 -H/home/mark/GitHub/mark-harsch/udemy-solid-principles/weatherApp -B/home/mark/GitHub/mark-harsch/udemy-solid-principles/weatherApp/build -G "Unix Makefiles"
```

**Comment by PhoebeHui** [comment]
@mark-harsch, the 2 statements is required if you want to use the headers installed by vcpkg directly, it will emit error without it when build the project. However, if you use the port which depends on boost, then you may don't need to add the statements, since the port will handle the dependency port.
