### ISSUE TITLE
.\vcpkg install darknet[full]:x64-windows build opencv4 failure

### ISSUE THREAD

**Issue by hendra24** [microsoft/vcpkg#16641]
**Host Environment**
- OS: Windows
- Compiler: revision

I am using GTX 1650 Max Q and CUDA 10.2 , CUDN 8.1.1. , Visual studio community 2019

**To Reproduce**
for install yolov4

`./vcpkg install darknet[full]:x64`

**Failure logs** 
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/6116998/install-x64-windows-dbg-out.log)

**Comment by JonLiu1993** [comment]
Hi @hendra24 ,Thanks for posting this issue,I cannot reproduce your problem locally. I found out that "unresolved external symbol cudnnGetConvolutionForwardAlgorithm referenced in function" is related to CUDN and cuda version. Please upgrade to the latest version and try again

**Comment by JonLiu1993** [comment]
Duplicate to #16748
