### ISSUE TITLE
[flint:x86-windows] build failure

### ISSUE THREAD

**Issue by Xofuu** [microsoft/vcpkg#16654]
**Host Environment**
- OS: Windows 10
- Compiler: revision

**To Reproduce**
`./vcpkg install flint

**Failure logs** 
```
Building package mpfr[core]:x86-windows... done
Installing package mpfr[core]:x86-windows...
Installing package mpfr[core]:x86-windows... done
Elapsed time for package mpfr:x86-windows: 11.51 min
Starting package 7/9: mpir:x86-windows
Building package mpir[core]:x86-windows...
CMake Error at ports/mpir/portfile.cmake:4 (message):
  Can't build mpir if gmp is installed.  Please remove gmp, and try to
  install mpir again if you need it.
Call Stack (most recent call first):
  scripts/ports.cmake:142 (include)


Error: Building package mpir:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: mpir:x86-windows
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e
```
**Additional context**
I didn't know what to put in the "Compiler" section. Basically, I downloaded vcpkg from GitHub, unzipped it in my Documents folder and run the Bootstrap to install it. Then, I tried to install the Flint library, for this purpose vcpkg started to download and build some dependencies such as gmp, mpfr, mpir, pthreads and gettimeofday. After installing everything successfully up to mpir, vcpkg shows a message error because apparently mpir cannot be installed when gmp is?? 
I tried removing all packages and installing mpir first but then when I try to install gmp, vcpkg tells me that gmp is in conflict with mpir so impossible as well.

**Comment by StarGate-One** [comment]
@Xofuu 
>Can't build mpir if gmp is installed. Please remove gmp, and try to install mpir again if you need it.

-Both ports `gmp` and `mpir` cannot be installed on the same vcpkg instance at the `same time`. 
-Either `gmp` or `mpir` can be installed but not both.

**Comment by Xofuu** [comment]
Hi StarGate-One, thanks for your reply. I'm aware of this, because they share the same headers files "gmp.h" and "gmpxx.h" but the issue is more about the dependencies on Flint I guess. By default, if one checks the official documentation about Flint, we only need either gmp with mpfr OR mpir with mpfr. However, mpfr depends on gmp according to vcpkg and ultimately, Flint depends on gmp, mpfr and mpir according to vcpkg. Obviously, as you noted, this causes errors.

For the people interested, I fixed the problem and was able to successfully install Flint by building gmp, mpir and mpfr with vcpkg. Then installing only gmp and mpfr and doing the installation of mpir manually and then modifying the "statut" and info files manually to let vcpkg thinks that mpir was installed successfully as well. After this, Flint can be built and installed without any issues whatsoever.
That's why I really think that the issue above is quite "superficial".

Have a nice day

**Comment by StarGate-One** [comment]
@Xofuu  /cc: @JonLiu1993 
I see what you mean... verified this needs to be fixed...
From an update-to-date clean vanilla vcpkg clone as of Friday 2021-03-21 at 15:30 UTC this is what I get:

>PS D:\vcpkgMgr\2019\test> vcpkg install flint[core] --dry-run
>Computing installation plan...
>The following packages will be built and installed:
>    flint[core]:x64-windows -> 2.5.2-4
>  * gmp[core]:x64-windows -> 6.2.1#3
>  * mpfr[core]:x64-windows -> 4.1.0
>  * mpir[core]:x64-windows -> 3.0.0#10
>  * vs-yasm[core]:x64-windows -> 0.5.0#1
> Additional packages (*) will be modified to complete this operation.

As you can see, flint[core] has dependencies of ports gmp, mpfr, mpir and vs-yasm, but as we know both ports gmp and mpir check to see if the other is installed, in other words:
- gmp checks to see if mpir is installed, if mpir is installed an error message is produced and gmp is not installed.
- mpir checks to see if gmp is installed, if gmp is installed an error message is produced and mpir is not installed.
- so we have the proverbial catch-22, we can not install port flint because it has dependencies of gmp and mpir but these 2 ports can not coexist simultaneously on the same instance.

**Comment by JackBoosY** [comment]
Yes, it's hard to solve.
See https://github.com/microsoft/vcpkg/issues/11756.

**Comment by JackBoosY** [comment]
@ras0219 @ras0219-msft Should we remove this port since the dependencies has conflict?

**Comment by strega-nil** [comment]
I think we need to solve this issue. This is a bug in flint, and it should be able to depend on gmp (though it might need some munging).

**Comment by Cheney-W** [comment]
Fixed by PR https://github.com/microsoft/vcpkg/pull/20050
