### ISSUE TITLE
[qt5-declarative]: Post-build validation fail with --x-install-root

### ISSUE THREAD

**Issue by Krzmbrzl** [microsoft/vcpkg#16671]
**Describe the bug**
I have my vcpkg tree on a different drive. Let's just say it's on `S:\vcpkg`. In there I already have all dependencies of the `qt5-declarative` package (using the same triplet `x64-windows-static-md`).

Now I run the following command in a vcpkg tree on a different drive (faster but less capacity - thus the idea is to build it there but store the final result on S):
```
vcpkg install qt5-declarative:x64-windows-static-md --x-install-root=S:\vcpkg\installed
```

The build works fine, but when it's time to do the installation I get
```
-- Package build-x64-windows-static-md-dbg
-- Package build-x64-windows-static-md-rel
-- Package install-x64-windows-static-md-dbg
-- Package install-x64-windows-static-md-rel
-- Installing: C:/Users/dev-user/vcpkg/packages/qt5-declarative_x64-windows-static-md/share/qt5-declarative/copyright
-- Performing post-build validation
The folder /include is empty or not present. This indicates the library was not correctly installed.
Found 1 error(s). Please correct the portfile:
    C:\Users\dev-user\vcpkg\ports\qt5-declarative\portfile.cmake
-- Performing post-build validation done
Error: Building package qt5-declarative:x64-windows-static-md failed with: POST_BUILD_CHECKS_FAILED
```
So I assume the post-build validation check  (or in fact the entire install procedure) is not picking up the correct install-directory (I verified that `S:\vcpkg\installed\include` exists and already contains content - Nothing that appears related to QtDeclarative though).

Note however that it did figure out that all dependencies are already installed on S: (they are not in the tree on C:).
Note also, that the same procedure (on the same machine) has worked for packages `icu` and `poco`.

**Environment**
- OS: Windows
- Compiler: VS2019

**Comment by Neumann-A** [comment]
> The folder /include is empty or not present. This indicates the library was not correctly installed.

typically means that it is not picking up required dependencies and not building anything at all.

**Comment by Krzmbrzl** [comment]
But ir compiled for > 3h. So it mudt have done _something_. During that time I also saw various instances of jom, qmake and c++ compiler in the task manager.

So I think it'd be odd if it didn't build anything :thinking:

**Comment by JackBoosY** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
