### ISSUE TITLE
[sdl2-mixer[mpg123]:x64-windows] build failure

### ISSUE THREAD

**Issue by ArneDJ** [microsoft/vcpkg#16673]
**Host Environment**
- OS: Windows
- Compiler: Visual Studio 2019

**To Reproduce**
`./vcpkg install sdl2-mixer[mpg123]:x64-windows`

**Failure logs** 
`Computing installation plan...`
`The following packages will be built and installed:`
    `sdl2-mixer[core,mpg123,nativemidi]:x64-windows -> 2.0.4#10`
`Detecting compiler hash for triplet x64-windows...`
`Could not locate cached archive:` `C:\Users\Arne\AppData\Local\vcpkg\archives\89\89c6e549893b23c3246667d3f512f9c9f5f1ec42.zip`
`Starting package 1/1: sdl2-mixer:x64-windows`
`Building package sdl2-mixer[core,mpg123,nativemidi]:x64-windows...`
`-- Using cached C:/dev/vcpkg/downloads/SDL2_mixer-2.0.4.zip`
`-- Cleaning sources at C:/dev/vcpkg/buildtrees/sdl2-mixer/src/2.0.4-a895b09396.clean. Use --editable to skip cleaning for the packages you specify.`
`-- Extracting source C:/dev/vcpkg/downloads/SDL2_mixer-2.0.4.zip`
`-- Using source at C:/dev/vcpkg/buildtrees/sdl2-mixer/src/2.0.4-a895b09396.clean`
`CMake Deprecation Warning at scripts/cmake/vcpkg_check_features.cmake:182 (message):`
`  calling `vcpkg_check_features` without the `FEATURES` keyword has been
  deprecated.`

    `  Please add the FEATURES keyword to the call.`
`Call Stack (most recent call first):`
`  ports/sdl2-mixer/portfile.cmake:30 (vcpkg_check_features)`
  `scripts/ports.cmake:142 (include)`

`-- Found external ninja('1.10.2').`
`-- Configuring x64-windows`
`-- Building x64-windows-dbg`
`CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:144 (message):`
  `  Command failed: C:/dev/vcpkg/downloads/tools/cmake-3.19.2-windows/cmake-3.19.2-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v -j5`
    `Working Directory: C:/dev/vcpkg/buildtrees/sdl2-mixer/x64-windows-dbg`
   ` See logs for more information:`
    `  C:\dev\vcpkg\buildtrees\sdl2-mixer\install-x64-windows-dbg-out.log`

`Call Stack (most recent call first):`
 ` scripts/cmake/vcpkg_build_cmake.cmake:105 (vcpkg_execute_build_process)`
 ` scripts/cmake/vcpkg_install_cmake.cmake:45 (vcpkg_build_cmake)`
`  ports/sdl2-mixer/portfile.cmake:50 (vcpkg_install_cmake)`
 ` scripts/ports.cmake:142 (include)`

`Error: Building package sdl2-mixer:x64-windows failed with: BUILD_FAILED`

**Additional context**
Trying to install the SDL2 mixer package with mp3 support fails.

**Comment by ArneDJ** [comment]
Fixed by following:
https://github.com/microsoft/vcpkg/issues/16067

**Comment by frankhale** [comment]
WOW, you got it installed okay? I cannot build sdl2-mixer with mpg123 support because it's complaining about unresolved symbols. You didn't have this issue? I'll file a new issue.

```
   Creating library SDL2_mixer.lib and object SDL2_mixer.exp
music_mpg123.c.obj : error LNK2019: unresolved external symbol _mpg123_init referenced in function _MPG123_Load
music_mpg123.c.obj : error LNK2019: unresolved external symbol _mpg123_exit referenced in function _MPG123_Load
music_mpg123.c.obj : error LNK2019: unresolved external symbol _mpg123_new referenced in function _MPG123_Load
music_mpg123.c.obj : error LNK2019: unresolved external symbol _mpg123_delete referenced in function _MPG123_Load
music_mpg123.c.obj : error LNK2019: unresolved external symbol _mpg123_plain_strerror referenced in function _MPG123_Load
music_mpg123.c.obj : error LNK2019: unresolved external symbol _mpg123_strerror referenced in function _MPG123_Load
music_mpg123.c.obj : error LNK2019: unresolved external symbol _mpg123_rates referenced in function _MPG123_Load
music_mpg123.c.obj : error LNK2019: unresolved external symbol _mpg123_format_none referenced in function _MPG123_Load
music_mpg123.c.obj : error LNK2019: unresolved external symbol _mpg123_format referenced in function _MPG123_Load
music_mpg123.c.obj : error LNK2019: unresolved external symbol _mpg123_getformat referenced in function _MPG123_Load
music_mpg123.c.obj : error LNK2019: unresolved external symbol _mpg123_open_handle referenced in function _MPG123_Load
music_mpg123.c.obj : error LNK2019: unresolved external symbol _mpg123_close referenced in function _MPG123_Load
music_mpg123.c.obj : error LNK2019: unresolved external symbol _mpg123_read referenced in function _MPG123_Load
music_mpg123.c.obj : error LNK2019: unresolved external symbol _mpg123_seek referenced in function _MPG123_Load
music_mpg123.c.obj : error LNK2019: unresolved external symbol _mpg123_replace_reader_handle referenced in function _MPG123_Load
SDL2_mixer.dll : fatal error LNK1120: 15 unresolved externals
```
