### ISSUE TITLE
Error: Building package llvm:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by raavann** [microsoft/vcpkg#16686]
Error: Building package llvm:x64-windows failed with: BUILD_FAILED

  Package: llvm:x64-windows
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

Vcpkg is up to date.

**Comment by NancyLi1013** [comment]
Hi @raavann 

Thanks for posting this issue.

Could you please help provide the detailed error info?

**Comment by raavann** [comment]
> Hi @raavann 
> 
> Thanks for posting this issue.
> 
> Could you please help provide the detailed error info?

Hie.
There was a 2 dollar signs in my path which somehow converted to 4 dollar signs... However I chnaged the name of directory and it works fine now.
