### ISSUE TITLE
Documentation for vcpkg_install_msbuild list two example ports that use it, but those ports no longer do

### ISSUE THREAD

**Issue by aggieNick02** [microsoft/vcpkg#16680]
https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_install_msbuild.md

This documentation lists `xalan-c` and `libimobiledevice` at the end as examples of ports that use the command. But neither port uses the command anymore. These examples should be removed and, ideally, a current one added.

**Comment by NancyLi1013** [comment]
These documents have been updated in vcpkg now via #18838.
