### ISSUE TITLE
[websocketpp] Add feature to build without boost

### ISSUE THREAD

**Issue by joefocusrite** [microsoft/vcpkg#16682]
The [websocketpp](https://github.com/zaphoyd/websocketpp) library supports building with Boost ASIO (boost-asio), or standalone ASIO (asio), or no ASIO to use a custom transport system.

The current port only supports Boost, which can add long build times to projects that don't already depend on Boost.

I have had a stab in #16675, but I could do with some help! The CI build fails on x86_windows because it says there already exists a port with that version number. I can't see any other ports with that version number in the log. I have tried with port version 1 and port version 2.

Any help would be greatly appreciated!

**Comment by StarGate-One** [comment]
@joefocusrite I had the same issue the other day.
I was given this information to fix the issue on my local vcpkg instance fix branch, which I pushed up to my git fork then over to microsoft/vcpkg PR:
>./vcpkg x-add-version openjpeg --overwrite-version
>git add .
>git commit -m "Update json file"
>git push

**Comment by PhoebeHui** [comment]
This issue has been fixed, appreciate your effort very much!
