### ISSUE TITLE
[New Port Request] <mailio>

### ISSUE THREAD

**Issue by karastojko** [microsoft/vcpkg#16695]
Library name: mailio

Library description: "mailio is a cross platform C++ library for MIME format and SMTP, POP3 and IMAP protocols. It is based on the standard C++ 17 and Boost library."

Source repository URL: https://github.com/karastojko/mailio

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by TaeZStkyoht** [comment]
It is a very useful library.
