### ISSUE TITLE
ixwebsocket wired install location

### ISSUE THREAD

**Issue by xarthurx** [microsoft/vcpkg#16699]
**Describe the bug**
installing `ixwebsocket` (without any additional label) gives output of:
```
    find_package(share CONFIG REQUIRED)
    target_link_libraries(main PRIVATE ixwebsocket::ixwebsocket)
```

Notice the word `share` in the above `cmd` output.

I tried different ways to find the package but in vain.
After some debug, it seems like the default `.cmake` file is located in the wrong location, a folder one level up:

Here is a screenshot of `vcpkg\installed\x64-windows\share`:
![image](https://user-images.githubusercontent.com/1921878/111082915-2c578600-850b-11eb-9e5b-1b58dec5c436.png)

**Environment**
- OS: Windows

**To Reproduce**
1. ./vcpkg install ixwebsocket
2. check the location of `ixwebsocket-config.cmake`

The file is located in `vcpkg\installed\x64-windows\share`

**Expected behavior**
The file should be located in `vcpkg\installed\x64-windows\share\ixwebsocket`

**Additional Notes**
Manually move the three `.cmake` files into the `ixwebsocket` folder solves the problem.
I guess this is a type in the postprocess script and should be an easy fix.

**Comment by NancyLi1013** [comment]
Hi @xarthurx 

Thanks for posting this issue.

I will fix this soon.
