### ISSUE TITLE
[New Port Request] <libopenshot>

### ISSUE THREAD

**Issue by PengGuoqing1993** [microsoft/vcpkg#16690]
Library name:
Libopenshot

Library description:
Video process, video effect

Source repository URL:
https://github.com/OpenShot/libopenshot

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
It is easy to develop video editor

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
