### ISSUE TITLE
vcpkg upgrade only upgrade specific triplets

### ISSUE THREAD

**Issue by longnguyen2004** [microsoft/vcpkg#16704]
****

**Is your feature request related to a problem? Please describe.**
I use a variety of different compilers to test the various ports. I'd like to have `vcpkg upgrade` only upgrades ports of a specific triplet, using the `--triplet` flag.

**Proposed solution**
Add `--triplet` option to `vcpkg upgrade`

**Comment by NancyLi1013** [comment]
Hi @longnguyen2004 

Thanks for posting this issue.

I think this is the same issue as #13239. Could you please help confirm if the proposal can meet your demands? https://github.com/microsoft/vcpkg/issues/13239#issuecomment-683603519

**Comment by longnguyen2004** [comment]
Yeah it is, but I want to specify `--triplet` instead of specifying each packages by hand.

**Comment by NancyLi1013** [comment]
Thanks for your reply. Let's track this issue there #13239.
