### ISSUE TITLE
[OpenSSL] Explicitly set OPENSSL_ROOT_DIR

### ISSUE THREAD

**Issue by Krzmbrzl** [microsoft/vcpkg#16709]
**Is your feature request related to a problem? Please describe.**

We have received reports from users on macOS and on Windows that are using vcpkg to install our dependencies. One of these is OpenSSL. However it can happen that cmake doesn't link to vcpkg's OpenSSL version but uses a system version instead (as well?).
This will then create link conflicts with the version packaged in vcpkg due to symbols being defined multiple times.

We assume that this happens because we also have Qt in our dependencies which itself links to OpenSSL and maybe it links to vcpkg's OpenSSL whereas our cmake files will end up picking the system libraries.

Explicitly setting `OPENSSL_ROOT_DIR` to point to vcpkg's OpenSSL directory usually resolves the issue.

**Proposed solution**

I propose explicitly setting this variable from within cmake when the vcpkg toolchain file is used (maybe only if it was not explicitly set on the command line).

**Additional context**

It seems that performing a Debug build vs a Release build can have an impact on which library version is being chosen.

For context see: https://github.com/mumble-voip/mumble/issues/4854

**Comment by JackBoosY** [comment]
In fact, this question is a dilemma:
-If we force `find_package` or `find_library` to find the library in vcpkg, it will not be found for libraries of different versions that third-party libraries (such as qt and openssl) rely on.
-If we do not force it, this type of problem may occur: the library in the system is found.

In addition, for libraries such as openssl, we use FindPORT.cmake provided by cmake to find, instead of using the generated config.cmake to import the target, caused this issue.

So, I think you should use static librar or triplet `x86-windows-static-md` / `x64-windows-static-md` to avoid this issue.

cc @ras0219 @ras0219-msft

**Comment by Krzmbrzl** [comment]
> So, I think you should use static librar or triplet x86-windows-static-md / x64-windows-static-md to avoid this issue.

Sorry I should have mentioned it earlier: We are in fact using the `x64-windows-static-md` triplet. So using this does not fix the issue.

> If we force find_package or find_library to find the library in vcpkg, it will not be found for libraries of different versions that third-party libraries (such as qt and openssl) rely on.

I think I can't quite follow here. Is this about someone potentially having OpenSSL installed via vcpkg but in another project they want to use the system's version instead (while using other packages from vcpkg)?

Maybe there could be a cmake flag that could be set that determines whether or not vcpkg will set the root path or not? Something like `VCPKG_SET_OPENSSL_ROOT_DIR=ON` or something like this.
This could allow projects to opt in to this behavior while all other code should remain unaffected.

**Comment by JackBoosY** [comment]
In this case, I think you can only use the same dependent library in vcpkg as much as possible. Vcpkg also supports building qt. Can you switch to using qt in vcpkg?

**Comment by Krzmbrzl** [comment]
We already build all of our dependencies via vcpkg (including Qt).

**Comment by Krzmbrzl** [comment]
I also wondered whether there is a way to obtain the directory of any given vcpkg package from within cmake (assuming the vcpkg toolchain file is loaded of course)? With something like that we could manually set the root dir as needed.

**Comment by JackBoosY** [comment]
@ras0219 @ras0219-msft Do you have any ideas?

**Comment by strega-nil** [comment]
We should use `vcpkg-cmake-wrapper.cmake` in order to inject this variable, that should solve this problem.

**Comment by SamuelMarks** [comment]
Yeah I've got to say this isn't fun:
```
export VCPKG="$MY_DIR"'/vcpkg';
export OPENSSL_ROOT_DIR="$VCPKG"'/packages/openssl_x64-osx';
cmake .. \
         -DCMAKE_BUILD_TYPE='Debug' \
         -DCMAKE_TOOLCHAIN_FILE="$VCPKG"'/scripts/buildsystems/vcpkg.cmake' \
         -DCRYPTO_LIB='OpenSSL' \
         -DOPENSSL_ROOT_DIR="$OPENSSL_ROOT_DIR" \
         -DOPENSSL_INCLUDE_DIR="$OPENSSL_ROOT_DIR"'/include' \
         -DOPENSSL_CRYPTO_LIBRARY="$OPENSSL_ROOT_DIR"'/lib/libssl.a' \
         -G='CodeBlocks - Unix Makefiles'
```

**Comment by JackBoosY** [comment]
@SamuelMarks Should be 
```bash
export VCPKG="$MY_DIR"'/vcpkg';
export OPENSSL_ROOT_DIR="$VCPKG"'/installed/x64-osx';
cmake .. \
         -DCMAKE_BUILD_TYPE='Debug' \
         -DCMAKE_TOOLCHAIN_FILE="$VCPKG"'/scripts/buildsystems/vcpkg.cmake' \
         -DCRYPTO_LIB='OpenSSL' \
         -DOPENSSL_ROOT_DIR="$OPENSSL_ROOT_DIR" \
         -DOPENSSL_INCLUDE_DIR="$OPENSSL_ROOT_DIR"'/include' \
         -DOPENSSL_CRYPTO_LIBRARY="$OPENSSL_ROOT_DIR"'/lib/libssl.a' \
         -G='CodeBlocks - Unix Makefiles'
```

**Comment by SamuelMarks** [comment]
@JackBoosY Hmm that didn't work

```cmake
find_package(OpenSSL REQUIRED)
if (DEFINED OPENSSL_INCLUDE_DIR)
    if (EXISTS "${OPENSSL_INCLUDE_DIR}/openssl/sha.h")
        set(HAVE_OPENSSL_SSL_H "ON")
    endif()
else()
    check_include_file("openssl/ssl.h" HAVE_OPENSSL_SSL_H)
endif()
if (NOT HAVE_OPENSSL_SSL_H)
    find_package(PkgConfig REQUIRED)
    pkg_search_module(OPENSSL REQUIRED openssl)
    message(FATAL_ERROR "OpenSSL installation doesn't have the required header files, install or use alt SSL")
endif ()
```

(I always get that `FATAL_ERROR`)
