### ISSUE TITLE
How do I get passed this error: "No suitable Visual Studio instances were found"

### ISSUE THREAD

**Issue by thecodedoctorr** [microsoft/vcpkg#16718]
So I am installing vcpkg on windows to use it with vs code. I noticed that my installation doesn't go as planned. 
When I first try to bootstrap it, it says its done and it looks fine.  However, from what I've seen on tutorials, my installation is way too quick (2 to 3 seconds).
In the output, for bootstraping and installing, I don't get any errors. commands (search, list, help) work fine but when I try to install a packages  afterward I get this error: 
`No suitable Visual Studio instances were found`. 

![vcpkgbootstrap](https://user-images.githubusercontent.com/80653616/111223452-75780a80-85dd-11eb-9776-10839b2f736b.png)

any idea of what is the issue?

**Comment by vicroms** [comment]
Do you have **Visual Studio** installed on your PC? 

> When I first try to bootstrap it, it says its done and it looks fine. However, from what I've seen on tutorials, my installation is way too quick (2 to 3 seconds).

Recently we changed bootstrap to download an executable file instead of building the tool from source. That's why it is so fast now.

**Comment by thecodedoctorr** [comment]
I do have visual studio installed. I removed vcpkg.  I uninstalled visual studio, installed it again and redid everything and now it is working. thank you

**Comment by cdecompilador** [comment]
Here with the same error having VS2019 installed

**Comment by naming1086** [comment]
> Here with the same error having VS2019 installed

install english language in VS2019
i have sloved the same error by doing that

**Comment by aiwebops** [comment]
I solved the problem  by attach ":x64-windows" after the package name.

**Comment by dg0yt** [comment]
> I solved the problem by attach ":x64-windows" after the package name.

The default triplet in vcpkg on windows is still x86-windows. Does x86-windows need VS components which are not installed by default on an x64-host?
