### ISSUE TITLE
[msbuild]DLLs aren't copied to output folder for MSIX packaged app

### ISSUE THREAD

**Issue by soumyamahunt** [microsoft/vcpkg#16715]
**Describe the bug**
When using `vcpkg` with `msbuild`, DLLs are copied to only the project output folder but not the [MSIX](https://github.com/microsoft/msix-packaging) packaging project output folder.

**Environment**
- OS: Windows
- Compiler: revision

**To Reproduce**
1. Create a sample console application project in visual studio and use any package that produces DLL for the application.
2. [Create a MSIX packaging project and add the previous console app as reference to "Applications" node.](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/modernize-wpf-tutorial-5)
3. Deploy the MSIX packaged app and run the app.
4. See the error.

**Expected behavior**
DLLs should be copied to MSIX package like before (recent changes are causing this behavior).

**Failure logs** 

![Screenshot 2021-03-15 183440](https://user-images.githubusercontent.com/51203900/111157690-30dc7700-85bd-11eb-9b42-ced8224b040a.png)
<h3 align="center">Error when using "fmt"</h3>

**Additional context**
This is probably happening due to recent changes in `vcpkg` as it didn't happen before.

**Comment by Cheney-W** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/16184
