### ISSUE TITLE
[cpp-httplib] update to 0.8.4

### ISSUE THREAD

**Issue by MFMokbel** [microsoft/vcpkg#16729]
Library name: cpp-httplib

New version number: 0.8.4

Other information that may be useful (release notes, etc...)

- Current available version on vcpkg is 0.7.0. Latest release is at version 0.8.4.
- Major bug fixes between those versions

**Comment by JonLiu1993** [comment]
Relate to #16591

**Comment by JonLiu1993** [comment]
Hi @MFMokbel, thank you for posting this issue, cpp-httplib has been updated to 0.8.4, please git pull the vcpkg and try again
