### ISSUE TITLE
[forest] remove from vcpkg

### ISSUE THREAD

**Issue by xorz57** [microsoft/vcpkg#16735]
Library name: forest

New version number: 0

Other information that may be useful (release notes, etc...)

I want to remove this library from vcpkg.

**Comment by PhoebeHui** [comment]
@xorz57, could you please tell us why you want to remove this port from vcpkg?

**Comment by xorz57** [comment]
Sure!
First I renamed the repository from forest to OpenDS.
Second, I need to fix my CMakeLists.txt and then I will make another pull request to include it in vcpkg.

**Comment by PhoebeHui** [comment]
@xorz57, thanks for the information! I will submit a PR to remove this port.
