### ISSUE TITLE
brotli:x64-windows build failure

### ISSUE THREAD

**Issue by a30f49** [microsoft/vcpkg#16732]
**Host Environment**
- OS: Windows
- Compiler: Vcpkg package management program version 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

**To Reproduce**
`./vcpkg install cpprestsdk:x64-windows`

**Failure logs** 
-- Installing: E:/dev/vcpkg/packages/brotli_x64-windows/share/brotli/copyright
-- Performing post-build validation
Detected outdated dynamic CRT in the following files:

    E:\dev\vcpkg\packages\brotli_x64-windows\bin\brotlicommon.dll: msvcr120.dll
    E:\dev\vcpkg\packages\brotli_x64-windows\bin\brotlidec.dll: msvcr120.dll
    E:\dev\vcpkg\packages\brotli_x64-windows\bin\brotlienc.dll: msvcr120.dll

To inspect the dll files, use:
    dumpbin.exe /dependents mydllfile.dll
Found 1 error(s). Please correct the portfile:
    E:\dev\vcpkg\ports\brotli\portfile.cmake
-- Performing post-build validation done
Error: Building package brotli:x64-windows failed with: POST_BUILD_CHECKS_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: brotli:x64-windows
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by NancyLi1013** [comment]
Hi @a30f49 

Thanks for posting this issue. I cannot reproduce this issue on my machine.

I noticed that there was already a related issue reported to upstream. But it seems it has no conclusion about it now.

Upstream issue https://github.com/microsoft/cpprestsdk/issues/717

**Comment by JonLiu1993** [comment]
@a30f49 ,I successfully reinstalled cpprestsdk:x64-windows locally. From pr#12345, many people reported this error in upstream, which may be related to upstream
````
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: F:/test-pr/test/vcpkg/packages/cpprestsdk_x64-windows/share/cpprestsdk/copyright
-- Performing post-build validation
-- Performing post-build validation done
Installing package cpprestsdk[brotli,compression,core,default-features]:x64-windows...
Elapsed time for package cpprestsdk:x64-windows: 1.21 min

Total elapsed time: 2.623 min

The package cpprestsdk provides CMake targets:

    find_package(cpprestsdk CONFIG REQUIRED)
    target_link_libraries(main PRIVATE cpprestsdk::cpprest cpprestsdk::cpprestsdk_zlib_internal cpprestsdk::cpprestsdk_brotli_internal)

````

**Comment by Cheney-W** [comment]
@a30f49 Does this issue still exist in your side?

**Comment by JonLiu1993** [comment]
Thanks for posting this issue. Please reopen this issue if it still be a problem for you.
