### ISSUE TITLE
fail to install libpng 

### ISSUE THREAD

**Issue by flcker** [Microsoft/vcpkg#1673]
Package: libpng:x86-windows
  Vcpkg version: 0.0.83-

**Comment by alexkaratarakis** [comment]
Please try the latest version (0.0.84) and post the output of the failure so we can investigate.

**Comment by NancyLi1013** [comment]
@flcker , can this isue be reproduced on your machine now? I can't repro it.  If it occurs on your machine recently, please post the output of the failure.
Thanks.

**Comment by NancyLi1013** [comment]
Please open a new issue if this is still a probem for you.
