### ISSUE TITLE
[angle] eglext_angle.h missing

### ISSUE THREAD

**Issue by hanseuljun** [microsoft/vcpkg#16731]
****

**Is your feature request related to a problem? Please describe.**
ANGLE has its own extension functions and they are inside eglext_angle.h.
![image](https://user-images.githubusercontent.com/5001447/111393516-229e6180-8676-11eb-896b-7be7676a7911.png)

However, when ANGLE is installed by vcpkg, eglext_angle.h is missing.
![image](https://user-images.githubusercontent.com/5001447/111393545-35189b00-8676-11eb-9061-75c4b171b05f.png)

I think the implementation of the functions for eglext_angle.h are also missing since I could not have access to the ANGLE-specific EGL functions by copy & pasting eglext_angle.h to my project.

**Proposed solution**
I am not sure about the details but I guess including the source files related to the extension functions while building ANGLE?

**Describe alternatives you've considered**
I have none. I may try taking a loot at this more later but I will need to take some rest before doing further since ANGLE's original build system is gn, which I am not used to...

**Comment by NancyLi1013** [comment]
Hi @hanseuljun 

Thanks for posting this issue.
Since it's duplicated to #14890, let's track this issue there.

**Comment by hanseuljun** [comment]
Thanks for the quick feedback!
