### ISSUE TITLE
about vcpkg install libmysql

### ISSUE THREAD

**Issue by wangdaxian201** [microsoft/vcpkg#16736]
VCPKG install libmariadb:
Building package libmariadb:x64-osx failed with: BUILD_FAILED
And prompt:
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:184 (message):

Failed to download file.
If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
variables to "https://user:password@your-proxy-ip-address:port/".

**Comment by NancyLi1013** [comment]
Hi @wangdaxian201 

Thanks for posting this issue.

It seems that there is something wrong when downloading the file.

Could you please provide the specific filename here? Or post the full error log here.

**Comment by NancyLi1013** [comment]
@wangdaxian201 

Is this still a problem for you? If yes, please provide the full error log here.

**Comment by NancyLi1013** [comment]
Closing this issue for now. Please feel free to reopen this issue if it is still a problem for you.
