### ISSUE TITLE
Problem with zlib dependency DLL on 32/64 bit build

### ISSUE THREAD

**Issue by jdx-john** [microsoft/vcpkg#16746]
We are using prometheus-cpp build, which has several dependencies including zlib, zlib is the only one which produces a DLL rather than .lib: *zlib1.dll*
Our main solution has a load of different projects, most 32-bit, a few 64-bit and both depend on prometheus-cpp. Everything works fine, including automagically copying zlib1.dll into our build directory... until our software won't run when deployed because the last project built is 64-bit, so we are distributing _only_ the 64-bit version of zlib1.dll... 32-bit modules with this dependency don't run. Everytime VS builds a project with this dependency, I guess it copies zlib1.dll from either C:\github\microsoft\vcpkg\installed\x86-windows\bin or C:\github\microsoft\vcpkg\installed\x64-windows\bin => <build-dir>
I didn't detect this in dev testing because every-time I built one module in isolation, the correct zlib1.dll was in my build-dir :)

I'm scratching my head figuring out why it's happening this way, when vcpkg has great support for different platforms/targets. It seems more likely it's an issue with the port (either prometheus-cpp or zlib) but what can/should I do about this? If only it was called zlib1_64.dll I wouldn't have this issue, is that feasible?

**Comment by JackBoosY** [comment]
Hi @jdx-john, thanks for reporting this issue!
I think you should use `X_VCPKG_APPLOCAL_DEPS_INSTALL ` to avoid this situation, please see https://github.com/microsoft/vcpkg/pull/16723.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
