### ISSUE TITLE
issue with ./bootstrap-vcpkg.bat !

### ISSUE THREAD

**Issue by NioGizer** [microsoft/vcpkg#16743]
hello every one 
i am trying to install the vcpkg to use it with Visual Studio code and add some libraries for c/c++
i cannot get the " building vcpkg.exe" when i run the command " ./bootstrap-vcpkg.ba "
i get a " download for vcpkg.exe!?
i almost tried every thing like rebooting and reinstalling .....
here is a screen shoot for the installing process .
![image](https://user-images.githubusercontent.com/76810608/111485331-c417c880-86f3-11eb-813f-96dbabd91892.png)

**Comment by StarGate-One** [comment]
@NioGizer 
- On Windows, vcpkg no longer builds the vcpkg binary from source, a prebuilt, compiled, linked binary `vcpkg.exe` is downloaded and put into the [vcpkg-root] directory.
- For all other supported platforms other than windows, vcpkg still builds the binary from source.
- If you still want to build the binary for Windows (or any other platform) from source, you will can download the source in the https://github.com/microsoft/vcpkg-tool repo and build with CMake and copy to the [vcpkg-root].

**Comment by JackBoosY** [comment]
For Windows, due to signatures and other reasons, the bootstrap script will directly download the vcpkg binary instead of compiling it.

**Comment by JonLiu1993** [comment]
@NioGizer ,Please reopen this issue if it still be a problem for you.
