### ISSUE TITLE
How long does it usually take to build ' Building x64-windows-dbg' for the first time.

### ISSUE THREAD

**Issue by shreeman1000** [microsoft/vcpkg#16745]

**Comment by shreeman1000** [comment]
It has been running for 3 straight hours from
'-- Configuring x64-windows
-- Building x64-windows-dbg'
but hasnt moved forward

![image](https://user-images.githubusercontent.com/64922271/111495007-f6154300-8764-11eb-8ce2-4ee241846492.png)

cmake is also barely using memory 1/2 Mbps and no cpu

**Comment by shreeman1000** [comment]
Powershell is not stuck, at least it doesnt seem to be -
![image](https://user-images.githubusercontent.com/64922271/111495535-7c318980-8765-11eb-9456-7c1d0b9ed417.png)

**Comment by StarGate-One** [comment]
@shreeman1000 
Port opencv can take hours, depending on features selected and the hardware it is built on (ie cpu, number of cores, memory available, disk drive type and speed, bus speed, etc).

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

**Comment by JackBoosY** [comment]
And we already have a feature issue about progress bar.

**Comment by erikpa1** [comment]
Any progress in it ? because I'm waiting for QT library like hour now ? still no progress bar, its 2023
