### ISSUE TITLE
openssl  error

### ISSUE THREAD

**Issue by 276585877** [Microsoft/vcpkg#1674]
why choose C:\Program Files (x86)\Windows Kits\10\include\10.0.10586.0 ? 

C:\Program Files (x86)\Windows Kits\10\include\10.0.10586.0\um\winnt.h(34): fatal error C1083: 无法打开包括文件: “ctype.h”: No such file or directory
d:\vcpkg-master\buildtrees\openssl\x86-windows-rel\openssl-1.0.2l\crypto\cryptlib.h(62): fatal error C1083: 无法打开包括文件: “stdlib.h”: No such file or directory
	cl /Fotmp32dll\cpt_err.obj  -Iinc32 -Itmp32dll -FS  /MD /Ox /O2 /Ob2 -DOPENSSL_THREADS  -DDSO_WIN32 -FS -W3 -Gs0 -GF -Gy -nologo -DOPENSSL_SYSNAME_WIN32 -DWIN32_LEAN_AND_MEAN -DL_ENDIAN -D_CRT_SECURE_NO_DEPRECATE -DOPENSSL_BN_ASM_PART_WORDS -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DRMD160_ASM -DAES_ASM -DVPAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DOPENSSL_USE_APPLINK -I. -DOPENSSL_NO_RC5 -DOPENSSL_NO_MD2 -DOPENSSL_NO_SSL2 -DOPENSSL_NO_KRB5 -DOPENSSL_NO_JPAKE -DOPENSSL_NO_WEAK_SSL_CIPHERS -DOPENSSL_NO_DYNAMIC_ENGINE /Zi /Fdtmp32dll/lib -D_WINDLL  -DOPENSSL_BUILD_SHLIBCRYPTO -c .\crypto\cpt_err.c
cpt_err.c
.\crypto\cpt_err.c(62): fatal error C1083: 无法打开包括文件: “stdio.h”: No such file or directory
	cl /Fotmp32dll\cversion.obj  -Iinc32 -Itmp32dll -FS  /MD /Ox /O2 /Ob2 -DOPENSSL_THREADS  -DDSO_WIN32 -FS -W3 -Gs0 -GF -Gy -nologo -DOPENSSL_SYSNAME_WIN32 -DWIN32_LEAN_AND_MEAN -DL_ENDIAN -D_CRT_SECURE_NO_DEPRECATE -DOPENSSL_BN_ASM_PART_WORDS -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DRMD160_ASM -DAES_ASM -DVPAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DOPENSSL_USE_APPLINK -I. -DOPENSSL_NO_RC5 -DOPENSSL_NO_MD2 -DOPENSSL_NO_SSL2 -DOPENSSL_NO_KRB5 -DOPENSSL_NO_JPAKE -DOPENSSL_NO_WEAK_SSL_CIPHERS -DOPENSSL_NO_DYNAMIC_ENGINE /Zi /Fdtmp32dll/lib -D_WINDLL  -DOPENSSL_BUILD_SHLIBCRYPTO -DMK1MF_BUILD -DMK1MF_PLATFORM_VC_WIN32 -c .\crypto\cversion.c

**Comment by ras0219-msft** [comment]
Thanks for posting your issue!

By default, we pick the latest Windows SDK version installed on your machine. In this case, it looks like we've accidentally selected one which doesn't have the Desktop C++ component installed.

The easiest way to fix this is by launching the VS2017 installer and making sure that the optional "Windows SDK (10.0.xyz) for Desktop C++" component is selected in the right hand side under "Desktop development with C++".

**Comment by NancyLi1013** [comment]
Please open a new issue if this is still a problem for you.
