### ISSUE TITLE
[opencv4] build error

### ISSUE THREAD

**Issue by shreeman1000** [microsoft/vcpkg#16748]
**Host Environment**
- OS: [windows 10]

**To Reproduce**
`.\vcpkg install darknet[full]:x64-windows`

**Failure logs** 
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:146 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j9
    Working Directory: D:/Deep_learning/yolo/vcpkg/buildtrees/opencv4/x64-windows-dbg
    See logs for more information:
      D:\Deep_learning\yolo\vcpkg\buildtrees\opencv4\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:105 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:45 (vcpkg_build_cmake)
  ports/opencv4/portfile.cmake:385 (vcpkg_install_cmake)
  scripts/ports.cmake:142 (include)

**Comment by StarGate-One** [comment]
>See logs for more information:
>D:\Deep_learning\yolo\vcpkg\buildtrees\opencv4\install-x64-windows-dbg-out.log

@shreeman1000 Please attach the aforementioned file to this issue for further review and/or troubleshooting.

**Comment by shreeman1000** [comment]
[Uploading install-x64-windows-dbg-out.log…]()

**Comment by shreeman1000** [comment]
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/6159142/install-x64-windows-dbg-out.log)

**Comment by StarGate-One** [comment]
Looks like there are some unresolved symbols dealing with **cudnn**:
>\opencv_dnn.dir/intermediate.manifest modules\dnn\CMakeFiles\opencv_dnn.dir/manifest.res" failed (exit code 1120) with the following output:
>   Creating library lib\opencv_dnnd.lib and object lib\opencv_dnnd.exp
convolution_layer.cpp.obj : error LNK2019: unresolved external symbol cudnnGetConvolutionForwardAlgorithm referenced in function "public: __cdecl cv::dnn::cuda4dnn::csl::cudnn::ConvolutionAlgorithm<float>::ConvolutionAlgorithm<float>(class cv::dnn::cuda4dnn::csl::cudnn::Handle const &,class cv::dnn::cuda4dnn::csl::cudnn::ConvolutionDescriptor<float> const &,class cv::dnn::cuda4dnn::csl::cudnn::FilterDescriptor<float> const &,class cv::dnn::cuda4dnn::csl::cudnn::TensorDescriptor<float> const &,class cv::dnn::cuda4dnn::csl::cudnn::TensorDescriptor<float> const &)" (??0?$ConvolutionAlgorithm@M@cudnn@csl@cuda4dnn@dnn@cv@@QEAA@AEBVHandle@12345@AEBV?$ConvolutionDescriptor@M@12345@AEBV?$FilterDescriptor@M@12345@AEBV?$TensorDescriptor@M@12345@3@Z)
convolution_layer.cpp.obj : error LNK2019: unresolved external symbol cudnnGetConvolutionBackwardDataAlgorithm referenced in function "public: __cdecl cv::dnn::cuda4dnn::csl::cudnn::TransposeConvolutionAlgorithm<float>::TransposeConvolutionAlgorithm<float>(class cv::dnn::cuda4dnn::csl::cudnn::Handle const &,class cv::dnn::cuda4dnn::csl::cudnn::ConvolutionDescriptor<float> const &,class cv::dnn::cuda4dnn::csl::cudnn::FilterDescriptor<float> const &,class cv::dnn::cuda4dnn::csl::cudnn::TensorDescriptor<float> const &,class cv::dnn::cuda4dnn::csl::cudnn::TensorDescriptor<float> const &)" (??0?$TransposeConvolutionAlgorithm@M@cudnn@csl@cuda4dnn@dnn@cv@@QEAA@AEBVHandle@12345@AEBV?$ConvolutionDescriptor@M@12345@AEBV?$FilterDescriptor@M@12345@AEBV?$TensorDescriptor@M@12345@3@Z)
**bin\opencv_dnnd.dll : fatal error LNK1120: 2 unresolved externals**

**Comment by shreeman1000** [comment]
> Looks like there are some unresolved symbols dealing with **cudnn**:

so what should i do to resolve this?

**Comment by JackBoosY** [comment]
```
LINK Pass 1: command "C:\PROGRA~2\MIB055~1\2019\BUILDT~1\VC\Tools\MSVC\1428~1.299\bin\Hostx64\x64\link.exe @CMakeFiles\opencv_dnn.rsp /out:bin\opencv_dnnd.dll /implib:lib\opencv_dnnd.lib /pdb:bin\opencv_dnnd.pdb /dll /version:4.5 /machine:x64 /nologo /debug /INCREMENTAL /NODEFAULTLIB:libc /DEBUG /MANIFEST /MANIFESTFILE:modules\dnn\CMakeFiles\opencv_dnn.dir/intermediate.manifest modules\dnn\CMakeFiles\opencv_dnn.dir/manifest.res" failed (exit code 1120) with the following output:
   Creating library lib\opencv_dnnd.lib and object lib\opencv_dnnd.exp
convolution_layer.cpp.obj : error LNK2019: unresolved external symbol cudnnGetConvolutionForwardAlgorithm referenced in function "public: __cdecl cv::dnn::cuda4dnn::csl::cudnn::ConvolutionAlgorithm<float>::ConvolutionAlgorithm<float>(class cv::dnn::cuda4dnn::csl::cudnn::Handle const &,class cv::dnn::cuda4dnn::csl::cudnn::ConvolutionDescriptor<float> const &,class cv::dnn::cuda4dnn::csl::cudnn::FilterDescriptor<float> const &,class cv::dnn::cuda4dnn::csl::cudnn::TensorDescriptor<float> const &,class cv::dnn::cuda4dnn::csl::cudnn::TensorDescriptor<float> const &)" (??0?$ConvolutionAlgorithm@M@cudnn@csl@cuda4dnn@dnn@cv@@QEAA@AEBVHandle@12345@AEBV?$ConvolutionDescriptor@M@12345@AEBV?$FilterDescriptor@M@12345@AEBV?$TensorDescriptor@M@12345@3@Z)
convolution_layer.cpp.obj : error LNK2019: unresolved external symbol cudnnGetConvolutionBackwardDataAlgorithm referenced in function "public: __cdecl cv::dnn::cuda4dnn::csl::cudnn::TransposeConvolutionAlgorithm<float>::TransposeConvolutionAlgorithm<float>(class cv::dnn::cuda4dnn::csl::cudnn::Handle const &,class cv::dnn::cuda4dnn::csl::cudnn::ConvolutionDescriptor<float> const &,class cv::dnn::cuda4dnn::csl::cudnn::FilterDescriptor<float> const &,class cv::dnn::cuda4dnn::csl::cudnn::TensorDescriptor<float> const &,class cv::dnn::cuda4dnn::csl::cudnn::TensorDescriptor<float> const &)" (??0?$TransposeConvolutionAlgorithm@M@cudnn@csl@cuda4dnn@dnn@cv@@QEAA@AEBVHandle@12345@AEBV?$ConvolutionDescriptor@M@12345@AEBV?$FilterDescriptor@M@12345@AEBV?$TensorDescriptor@M@12345@3@Z)
bin\opencv_dnnd.dll : fatal error LNK1120: 2 unresolved externals
```

Missing link to `cudnn.lib`.

**Comment by shreeman1000** [comment]
I checked but i had installed cudnn as showing in the documentation by copy pasting the files in the correct directory cuda lib, include, bin so how should i resolve it?

**Comment by JackBoosY** [comment]
@shreeman1000 Can you please provide configure log _D:\Deep_learning\yolo\vcpkg\buildtrees\opencv4\config-x64-windows-dbg-out.log_  and _D:\Deep_learning\yolo\vcpkg\buildtrees\opencv4\config-x64-windows-dbg-err.log_ ?

**Comment by shreeman1000** [comment]
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/6171796/config-x64-windows-out.log)

config-x64-windows-dbg-err.log file is empty and above is the config-x64-windows-dbg-out.log file

**Comment by shreeman1000** [comment]
These files are not present in the folder opencv4 the ones present are-
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/6171811/config-x64-windows-out.log)
config-x64-windows-out.log attached above
and config-x64-windows-err.log which is empty

**Comment by JackBoosY** [comment]
```
-- Found CUDNN: D:/Deep_learning/darknet_with_vcpkg/vcpkg/installed/x64-windows/include (found suitable version "7.6.0", minimum required is "7.5") 
...
--     Extra dependencies:          ... cudnn.lib ...
...
--   cuDNN:                         YES (ver 7.6.0)

**Comment by shreeman1000** [comment]
I had build opencv4.5.1 (for trying to build darknet with cmake) too is this clashing with that or something?

**Comment by tfaehse** [comment]
I seem to be facing the same issue, or at least something related. If there's anything I can test or provide you with, do not hesitate to ask. I'm trying to `vcpkg install darknet[full]:x64-windows`

- Windows 10, 5820K, GTX 1060 6GB
- Vcpkg version 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e
- CUDA Toolkit 11.1
- cuDNN 8.0.5
- CUDA_PATH is set

cuDNN seems to work fine, I can use GPU acceleration in TensorFlow for example. Like @JackBoosY commented, cuDNN is found and the extra dependency on cudnn.lib is marked in the config log.

Here are my config- and build logs:
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/6188543/config-x64-windows-out.log)
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/6188544/install-x64-windows-dbg-out.log)

**Comment by JonLiu1993** [comment]
@shreeman1000 ,Does this problem still exist?

**Comment by shreeman1000** [comment]
@JonLiu1993 I was trying to use darknet moreover yolov3 and the other method to make it work using visual studio on windows worked for me after a update in that repository and I didn't find any solution to this.

**Comment by Cheney-W** [comment]
darknet[full]:x64-windows could be installed successfully with the latest vcpkg 2021-12-09-724cea8b33cbf06c645f5095fa29773697da9761 now. 
@shreeman1000 Could you please try the latest vcpkg?

**Comment by JackBoosY** [comment]
@shreeman1000 Ping for response.

**Comment by JackBoosY** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
