### ISSUE TITLE
How do I specify a custom triplet in a solution-wide props file?

### ISSUE THREAD

**Issue by jdx-john** [microsoft/vcpkg#16752]
I have created custom triplets x86/64-windows-custom. I have shown this works when set in Visual studio on a per-project basis, under the vcpkg project properties GUI section. It overrides the default triplets as expected.

I then removed this and and tried to add it to our main Custom.props file, which is used across our solution:
```
  <PropertyGroup Label="Globals">
    <VcpkgTriplet Condition="'$(Platform)'=='Win32'">x86-windows-custom</VcpkgTriplet>
    <VcpkgTriplet Condition="'$(Platform)'=='x64'">x64-windows-custom</VcpkgTriplet>
  </PropertyGroup>

```
When I do this, it reverts to using the default triplets e.g.x86-windows. I have hundreds of projects so how should I be setting this up, I know the docs say I can but I haven't used props files much.

**Comment by jdx-john** [comment]
Also, from vcppkg.targets, how come I never see any of these messages in my VC++ build output?

```
  <Target Name="VcpkgTripletSelection" BeforeTargets="ClCompile">
    <Message Text="Using triplet &quot;$(VcpkgTriplet)&quot; from &quot;$(VcpkgCurrentInstalledDir)&quot;"
             Importance="Normal" Condition="'$(VcpkgEnabled)' == 'true'"/>
    <Message Text="Not using Vcpkg because VcpkgEnabled is &quot;$(VcpkgEnabled)&quot;"
             Importance="Normal" Condition="'$(VcpkgEnabled)' != 'true'"/>
    <Message Text="Vcpkg is unable to link because we cannot decide between Release and Debug libraries. Please define the property VcpkgConfiguration to be 'Release' or 'Debug' (currently '$(VcpkgConfiguration)')."
             Importance="High" Condition="'$(VcpkgEnabled)' == 'true' and '$(VcpkgNormalizedConfiguration)' == ''"/>
  </Target>

```

**Comment by PhoebeHui** [comment]
@ras0219-msft, any suggestions?
