### ISSUE TITLE
seal:x86-windows

### ISSUE THREAD

**Issue by prizomil** [microsoft/vcpkg#16750]
Package: seal:x86-windows
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

vcpkg install seal:x86-windows
Computing installation plan...
The following packages will be built and installed:
    seal[core,ms-gsl,zlib,zstd]:x86-windows -> 3.6.2
Detecting compiler hash for triplet x86-windows...
Could not locate cached archive: C:\Users\Panos\AppData\Local\vcpkg\archives\fa\fa7aaca01caf537a17d7cbf6de05a3b04e1f0e61.zip
Starting package 1/1: seal:x86-windows
Building package seal[core,ms-gsl,zlib,zstd]:x86-windows...
-- Note: seal only supports static library linkage. Building static library.
-- Using cached C:/aplis/vcpkg/downloads/microsoft-SEAL-5c586e2480dc0a43fb76a23a3dcc3daecb3764e8.tar.gz
-- Cleaning sources at C:/aplis/vcpkg/buildtrees/seal/src/aecb3764e8-a3a4e1e192.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/aplis/vcpkg/downloads/microsoft-SEAL-5c586e2480dc0a43fb76a23a3dcc3daecb3764e8.tar.gz
-- Using source at C:/aplis/vcpkg/buildtrees/seal/src/aecb3764e8-a3a4e1e192.clean
-- Found external ninja('1.10.2').
-- Configuring x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" C:/aplis/vcpkg/buildtrees/seal/src/aecb3764e8-a3a4e1e192.clean -DSEAL_BUILD_DEPS=OFF -DSEAL_BUILD_EXAMPLES=OFF -DSEAL_BUILD_TESTS=OFF -DSEAL_BUILD_SEAL_C=OFF -DSEAL_USE_MSGSL=ON -DSEAL_USE_ZLIB=ON -DSEAL_USE_ZSTD=ON -DSEAL_THROW_ON_TRANSPARENT_CIPHERTEXT=ON "-DCMAKE_MAKE_PROGRAM=C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -DBUILD_SHARED_LIBS=OFF -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/aplis/vcpkg/scripts/toolchains/windows.cmake -DVCPKG_TARGET_TRIPLET=x86-windows -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=v142 -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=C:/aplis/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_LINKER_FLAGS_RELEASE= -DVCPKG_LINKER_FLAGS_DEBUG= -DVCPKG_TARGET_ARCHITECTURE=x86 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -D_VCPKG_ROOT_DIR=C:/aplis/vcpkg -D_VCPKG_INSTALLED_DIR=C:/aplis/vcpkg/installed -DVCPKG_MANIFEST_INSTALL=OFF -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=C:/aplis/vcpkg/packages/seal_x86-windows/debug
    Working Directory: C:/aplis/vcpkg/buildtrees/seal/x86-windows-dbg
    Error code: 1
    See logs for more information:
      C:\aplis\vcpkg\buildtrees\seal\config-x86-windows-dbg-out.log
      C:\aplis\vcpkg\buildtrees\seal\config-x86-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:333 (vcpkg_execute_required_process)
  ports/seal/portfile.cmake:21 (vcpkg_configure_cmake)
  scripts/ports.cmake:142 (include)

**Comment by StarGate-One** [comment]
>See logs for more information:
>C:\aplis\vcpkg\buildtrees\seal\config-x86-windows-dbg-out.log
>C:\aplis\vcpkg\buildtrees\seal\config-x86-windows-dbg-err.log

@prizomil  Please attach the aforementioned logs to this issue for further review and/or troubleshooting.

**Comment by prizomil** [comment]
[config-x86-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/6159000/config-x86-windows-dbg-err.log)
[config-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/6159001/config-x86-windows-dbg-out.log)

**Comment by StarGate-One** [comment]
From x86-windows-dbg-error.log:
>CMake Error at CMakeLists.txt:195 (message):
> Zstandard: must be static

From x86-windows-dbg-out.log:
>-- Configuring incomplete, errors occurred!
>See also "C:/aplis/vcpkg/buildtrees/seal/x86-windows-dbg/CMakeFiles/CMakeOutput.log".

**Comment by Cheney-W** [comment]
This port currently only support !windows | (windows & static).

**Comment by MonicaLiu0311** [comment]
Fixed by https://github.com/microsoft/vcpkg/pull/11588.
