### ISSUE TITLE
protobuf:x86-windows build failure

### ISSUE THREAD

**Issue by cditto123** [microsoft/vcpkg#16751]
**Host Environment**
- OS: Windows
- Compiler: Visual C++ 2019 - 00435-60000-00000-AA199

**To Reproduce**
vcpkg install protobuf protobuf:x86-windows-static

**Failure logs** 

-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- mt.exe has failed. This may be the result of anti-virus. Disabling anti-virus on the buildtree folder may improve build speed
-- Restarting Build x86-windows-rel because of mt.exe file locking issue. Iteration: 1
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:122 (file):
  file failed to open for reading (No such file or directory):

    C:/Users/cditto/Documents/vcpkg/-out-1.log
Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:105 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:45 (vcpkg_build_cmake)
  ports/protobuf/portfile.cmake:58 (vcpkg_install_cmake)
  scripts/ports.cmake:142 (include)

Error: Building package protobuf:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: protobuf:x86-windows
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

**Additional context**
No log file was generated.

**Comment by ionutcosminmihaipfa** [comment]
This is working now with https://github.com/microsoft/vcpkg/pull/16479

**Comment by cditto123** [comment]
There is definitely anti-virus.  An evil one at that.  I can’t disable it.  Only IT admin can and only temporarily.  I’ll try again when I can get access to non-network machine.  Thanks for the update.

**Comment by NancyLi1013** [comment]
Any updates? @cditto123

**Comment by cditto123** [comment]
No joy.  With anti-virus disabled I get the following…

======================================================================

C:\000space\vcpkg>vcpkg install protobuf protobuf:x86-windows-static
Computing installation plan...
The following packages will be built and installed:
  * protobuf[core]:x64-windows -> 3.15.8
    protobuf[core]:x86-windows -> 3.15.8
    protobuf[core]:x86-windows-static -> 3.15.8
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Detecting compiler hash for triplet x86-windows...
Detecting compiler hash for triplet x86-windows-static...
Could not locate cached archive: C:\Users\cditto\AppData\Local\vcpkg\archives\7a\7a1db80f1dd4295f8079717a05e4ba3e51da2901.zip
Could not locate cached archive: C:\Users\cditto\AppData\Local\vcpkg\archives\04\040872b9f4e077071fe8b657c10306f46bfef2a0.zip
Could not locate cached archive: C:\Users\cditto\AppData\Local\vcpkg\archives\fe\fe79a3cf0d8fb2ddb90bde4cdfc99d3347c781a2.zip
Starting package 1/3: protobuf:x64-windows
Building package protobuf[core]:x64-windows...
-- Downloading https://github.com/protocolbuffers/protobuf/archive/436bd7880e458532901c58f4d9d1ea23fa7edd52.tar.gz -> protocolbuffers-protobuf-436bd7880e458532901c58f4d9d1ea23fa7edd52.tar.gz...
-- Extracting source C:/000space/vcpkg/downloads/protocolbuffers-protobuf-436bd7880e458532901c58f4d9d1ea23fa7edd52.tar.gz
-- Applying patch fix-static-build.patch
-- Applying patch fix-default-proto-file-path.patch
-- Using source at C:/000space/vcpkg/buildtrees/protobuf/src/23fa7edd52-3ba2225d30.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- mt.exe has failed. This may be the result of anti-virus. Disabling anti-virus on the buildtree folder may improve bui
ld speed
-- Restarting Build x64-windows-rel because of mt.exe file locking issue. Iteration: 1
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:122 (file):
  file failed to open for reading (No such file or directory):

    C:/000space/vcpkg/-out-1.log
Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:105 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:45 (vcpkg_build_cmake)
  ports/protobuf/portfile.cmake:46 (vcpkg_install_cmake)
  scripts/ports.cmake:142 (include)


Error: Building package protobuf:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: protobuf:x64-windows
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

Additionally, attach any relevant sections from the log files above.

==========================================================================

If appears that debug versions x64 and x86 were built.  No release versions or static libraries were.

**Comment by JackBoosY** [comment]
Can you please Repair your Visual Studio using Visual Studio Installer?
And please use `powershell` instead of `cmd` on Windows.

**Comment by PhoebeHui** [comment]
@cditto123, does this still be a problem for you?

**Comment by cditto123** [comment]
I was unable to resolve the issue in my build environment; however, I found a alternative build strategy that did work so I haven’t revisited it.

**Comment by sfhacker** [comment]
It seems there are STILL unresolved issues with this protobuf in general.
Just built protobuf from source on Windows (x64, sorry no x86 available). No issues at all.
How can I reproduce this issue locally? My antivirus is enabled at the moment.

**Comment by PhoebeHui** [comment]
@cditto123, thanks for your reply.
