### ISSUE TITLE
[llvm] build failure

### ISSUE THREAD

**Issue by BookmanHan** [microsoft/vcpkg#16759]
**Host Environment**
- OS: Ubuntu 18.04
- Compiler: clang, gcc

**To Reproduce**
`./vcpkg install llvm`

**Failure logs** 
Computing installation plan...
The following packages will be built and installed:
    llvm[clang,core,default-targets,disable-abi-breaking-checks,disable-assertions,disable-clang-static-analyzer,enable-rtti,lld,target-x86,tools]:x64-linux -> 11.0.0#1
Detecting compiler hash for triplet x64-linux...
Could not locate cached archive: /home/bookman/.cache/vcpkg/archives/a9/a90e4eb1aaf99e3a5320fdfa087b77920410dea4.zip
Starting package 1/1: llvm:x64-linux
Building package llvm[clang,core,default-targets,disable-abi-breaking-checks,disable-assertions,disable-clang-static-analyzer,enable-rtti,lld,target-x86,tools]:x64-linux...
-- Using cached /home/bookman/vcpkg/downloads/llvm-llvm-project-llvmorg-11.0.0.tar.gz
-- Cleaning sources at /home/bookman/vcpkg/buildtrees/llvm/src/org-11.0.0-9a84d27ce8.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/bookman/vcpkg/downloads/llvm-llvm-project-llvmorg-11.0.0.tar.gz
-- Applying patch 0001-add-msvc-options.patch
-- Applying patch 0002-fix-install-paths.patch
-- Applying patch 0003-fix-openmp-debug.patch
-- Applying patch 0004-fix-dr-1734.patch
-- Applying patch 0005-fix-tools-path.patch
-- Applying patch 0006-workaround-msvc-bug.patch
-- Using source at /home/bookman/vcpkg/buildtrees/llvm/src/org-11.0.0-9a84d27ce8.clean
CMake Deprecation Warning at scripts/cmake/vcpkg_check_features.cmake:182 (message):
  calling `vcpkg_check_features` without the `FEATURES` keyword has been
  deprecated.

      Please add the `FEATURES` keyword to the call.
Call Stack (most recent call first):
  ports/llvm/portfile.cmake:20 (vcpkg_check_features)
  scripts/ports.cmake:142 (include)

-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:146 (message):
    Command failed: /home/bookman/vcpkg/downloads/tools/cmake-3.19.2-linux/cmake-3.19.2-Linux-x86_64/bin/cmake --build . --config Debug --target install -- -v -j49
    Working Directory: /home/bookman/vcpkg/buildtrees/llvm/x64-linux-dbg
    See logs for more information:
      /home/bookman/vcpkg/buildtrees/llvm/install-x64-linux-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:105 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:45 (vcpkg_build_cmake)
  ports/llvm/portfile.cmake:185 (vcpkg_install_cmake)
  scripts/ports.cmake:142 (include)

Error: Building package llvm:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: llvm:x64-linux
  Vcpkg version: 2021-01-13-unknownhash

Additionally, attach any relevant sections from the log files above.

**Additional context**
Thank you very much for helping me.

**Comment by NancyLi1013** [comment]
Hi @BookmanHan 

Thanks for posting this issue.

I can build it successfully with Ubuntu 18.04 gcc 10.0.0 on my machine.
Could you please provide the error from `/home/bookman/vcpkg/buildtrees/llvm/install-x64-linux-dbg-out.log
`?

**Comment by yurybura** [comment]
Dear @BookmanHan, could you try changes from this PR #16232 too?
Thank you.

**Comment by NancyLi1013** [comment]
Please try to update vcpkg to the latest version to rebuild `llvm`. @BookmanHan 

Closing this issue for now. Please feel free to reopen this issue if it is still a problem for you.
