### ISSUE TITLE
How do I use nuget caches on linux?

### ISSUE THREAD

**Issue by ASxa86** [microsoft/vcpkg#16754]
I am attempting to take a nuget cache generated from an internet machine and load it into an artifactory nuget repository on an "air-gapped" network.

I have successfully gotten this to work on windows by running the following command in my project directory with a `vcpkg.json` manifest file:
`vcpkg.exe install --triplet=x64-windows --feature-flags=-compilertracking,manifests --binarysource=clear;nuget,Artifactory,read --overlay-ports=D:\myproject\myports --debug`

Unfortunately, this doesn't seem to work or do much of anything else when I attempt the same command on RedHat 7 linux.
`./vcpkg install --triplet=x64-linux-dynamic --feature-flags=-compilertracking,manifests --binarysource=clear;nuget,Artifactory,read --overlay-ports=/home/myproject/myports --debug`

Am I doing something wrong here? I've configured nuget to point to my artifactory repo the exact same way I did on windows. I even tried to run `mono vcpkg/downloads/tools/nuget-5.5.1-linux/nuget.exe` to no avail.

I also noticed I'm getting 0 extra output by providing the debug flag and vcpkg doesn't output that its looking at my custom port directories like it does on windows.

**Comment by ASxa86** [comment]
So, I think I figured out my issue for anyone else who may come across this.

My problem was the use of `;` after `--binarysource=clear;`. On linux this was prematurely ending my command preventing any flags following it to be called.

**Comment by JackBoosY** [comment]
Nuget can only be used in Windows.

**Comment by JackBoosY** [comment]
@ras0219 @ras0219-msft Can you please take a look?

Thanks.

**Comment by ASxa86** [comment]
I think I've got this working as expected. My issues was the use of a ';' in my call to '--binarysource=clear;nuget,Artifactory,read'.
I was able to resolve this by adding quotes '--binarysource="clear;nuget,Artifactory,read"'.

**Comment by JackBoosY** [comment]
Glad to see your issue was resolved.
