### ISSUE TITLE
[New Port Request] polyscope

### ISSUE THREAD

**Issue by xarthurx** [microsoft/vcpkg#16769]
Library name:
Polyscope 

Library description:
Polyscope is a C++/Python viewer and user interface for 3D data, like meshes and point clouds. Scientists, engineers, artists, and hackers can use Polyscope to prototype algorithms—it is designed to easily integrate with existing codebases and popular libraries. The lofty objective of Polyscope is to offer a useful visual interface to your data via a single line of code.

Source repository URL:
https://github.com/nmwsharp/polyscope

Project homepage (if different from the source repository):
https://polyscope.run

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
