### ISSUE TITLE
[zlib:x64-windows] build failure

### ISSUE THREAD

**Issue by irenjie** [microsoft/vcpkg#16762]
**Host Environment**
- OS: windows10
- Compiler: cmake version 3.20.0-rc3

**To Reproduce**
`vcpkg install zlib`

**Failure logs** 
Computing installation plan...
The following packages will be built and installed:
    zlib[core]:x64-windows -> 1.2.11#9
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\17398\AppData\Local\vcpkg\archives\1f\1f9d421e6146e8cf65cb180d1dbb744e05b49fd4.zip
Starting package 1/1: zlib:x64-windows
Building package zlib[core]:x64-windows...
-- Using cached D:/Program/morestuff/vcpkg/downloads/zlib1211.tar.gz
-- Cleaning sources at D:/Program/morestuff/vcpkg/buildtrees/zlib/src/1.2.11-63309e48e5.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/Program/morestuff/vcpkg/downloads/zlib1211.tar.gz
-- Applying patch cmake_dont_build_more_than_needed.patch
-- Applying patch 0001-Prevent-invalid-inclusions-when-HAVE_-is-set-to-0.patch
-- Applying patch add_debug_postfix_on_mingw.patch
-- Using source at D:/Program/morestuff/vcpkg/buildtrees/zlib/src/1.2.11-63309e48e5.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
    Command failed: ninja -v
    Working Directory: D:/Program/morestuff/vcpkg/buildtrees/zlib/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\Program\morestuff\vcpkg\buildtrees\zlib\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:324 (vcpkg_execute_required_process)
  ports/zlib/portfile.cmake:22 (vcpkg_configure_cmake)
  scripts/ports.cmake:142 (include)

Error: Building package zlib:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zlib:x64-windows
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

Additionally, attach any relevant sections from the log files above.

**Additional context**
in config-x86-windows-out.log      
CMake Error at D:/Software/cmake-3.20.0/share/cmake-3.20/Modules/CMakeTestCCompiler.cmake:66 (message):
  The C compiler

    "D:/Software/VS19Community/IDE/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: D:/Program/morestuff/vcpkg/buildtrees/zlib/x64-windows-dbg/CMakeFiles/CMakeTmp
    
    Run Build Command(s):D:/Software/VS19Community/IDE/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe cmTC_74671 && [1/2] Building C object CMakeFiles\cmTC_74671.dir\testCCompiler.c.obj
    [2/2] Linking C executable cmTC_74671.exe
    FAILED: cmTC_74671.exe 
    cmd.exe /C "cd . && D:\Software\cmake-3.20.0\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_74671.dir --rc=rc --mt=CMAKE_MT-NOTFOUND --manifests  -- D:\Software\VS19Community\IDE\VC\Tools\MSVC\14.28.29910\bin\Hostx64\x64\link.exe /nologo CMakeFiles\cmTC_74671.dir\testCCompiler.c.obj  /out:cmTC_74671.exe /implib:cmTC_74671.lib /pdb:cmTC_74671.pdb /version:0.0 /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    RC Pass 1: command "rc /fo CMakeFiles\cmTC_74671.dir/manifest.res CMakeFiles\cmTC_74671.dir/manifest.rc" failed (exit code 0) with the following output:
    系统找不到指定的文件。
    ninja: build stopped: subcommand failed.

**Comment by JonLiu1993** [comment]
@irenjie ,CMake is not able to generate the project properly -
Check to make sure Visual Studio 2019 has the following installed:

- Desktop Development with C++
- One of the Windows SDKs, preferably the latest 19041
- English Language Pack

**Comment by irenjie** [comment]
Zlib build successful after I redownload Windows SDKs.Thinks
