### ISSUE TITLE
Building package ffmpeg:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by soltkreig** [microsoft/vcpkg#16772]
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
    Command failed: C:/Users/Ruslan/vcpkg/downloads/tools/msys2/969c0913b9df89e1/usr/bin/bash.exe ./build.sh
    Working Directory: C:/Users/Ruslan/vcpkg/buildtrees/ffmpeg/x64-windows-dbg
    Error code: 1
    See logs for more information:
      C:\Users\Ruslan\vcpkg\buildtrees\ffmpeg\build-x64-windows-dbg-out.log

Call Stack (most recent call first):
  ports/ffmpeg/portfile.cmake:456 (vcpkg_execute_required_process)
  scripts/ports.cmake:142 (include)

Error: Building package ffmpeg:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: ffmpeg:x64-windows
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

from build-x64-windows-dbg-out:
=== CONFIGURING ===
cl.exe is unable to create an executable file.
If cl.exe is a cross-compiler, use the --enable-cross-compile option.
Only do this if you know what cross compiling means.
C compiler test failed.

**Comment by NancyLi1013** [comment]
Hi @soltkreig 

Thanks for posting this issue.

```
cl.exe is unable to create an executable file.
If cl.exe is a cross-compiler, use the --enable-cross-compile option.
Only do this if you know what cross compiling means.
C compiler test failed.
```
Do you build on cross-compiler? Please try to add the option `--enable-cross-compile` to rebuild.

**Comment by NancyLi1013** [comment]
Closing this issue for now. Please feel free to reopen this issue if it is still a problem for you.

**Comment by kotx** [comment]
This still remains a problem for me, as vcpkg does not recognize the `--enable-cross-compile` flag.

**Comment by kotx** [comment]
Turns out I was missing the Win10 SDK from the Visual Studio Installer. Installing it fixed my issue.
