### ISSUE TITLE
[ci] skip lists also skip host ports

### ISSUE THREAD

**Issue by strega-nil** [microsoft/vcpkg#16773]
There are some ports which are host-only; these ports should be skipped on non-native triplets in CI. However, we have an issue where those skips for the target also become skips for the host.

In commands.ci.cpp, line 537, we need to check if the action is a host port or not.

**Comment by autoantwort** [comment]
Is this also the reason why [here](https://dev.azure.com/vcpkg/public/_build/results?buildId=50659&view=logs&jobId=67167230-dc6a-522f-6bed-e189fa130338&j=a6e72ce0-e588-59fa-ea7b-9242eb853448&t=04a839e0-5dca-5a72-6942-c706553e040e) the mailio port was not build? (And now the pipeline in other PR fails)

**Comment by autoantwort** [comment]
Is this also the reason why in the mailio pr (#16696) the pipeline succeeded because the port was not tested but in reality the port does not build on uwp?

**Comment by NancyLi1013** [comment]
Seems https://github.com/microsoft/vcpkg-tool/pull/34 and https://github.com/microsoft/vcpkg-tool/pull/72 have solved this issue. Also the changes have been merged to vcpkg master branch. So closing this issue for now.
