### ISSUE TITLE
[protobuf:x64-windows] build failure

### ISSUE THREAD

**Issue by vkphd** [microsoft/vcpkg#16786]
**Host Environment**
- OS: Windows 10
- Compiler: MSVC 2017

**To Reproduce**
`./vcpkg install protobuf:x64-windows`

**Failure logs** 

> -- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:146 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j13
    Working Directory: C:/temp/vcpkg/buildtrees/protobuf/x64-windows-dbg
    See logs for more information:
      C:\temp\vcpkg\buildtrees\protobuf\install-x64-windows-dbg-out.log

> Call Stack (most recent call first):
>   scripts/cmake/vcpkg_build_cmake.cmake:105 (vcpkg_execute_build_process)
>   scripts/cmake/vcpkg_install_cmake.cmake:45 (vcpkg_build_cmake)
>   ports/protobuf/portfile.cmake:58 (vcpkg_install_cmake)
>   scripts/ports.cmake:142 (include)
> 
> Error: Building package protobuf:x64-windows failed with: BUILD_FAILED
> Please ensure you're using the latest portfiles with `.\vcpkg update`, then
> submit an issue at https://github.com/Microsoft/vcpkg/issues including:
>   Package: protobuf:x64-windows
>  Vcpkg version: 2021-01-13-768d8f95c9e752603d2c5901c7a7c7fbdb08af35

LOG: "C:\temp\vcpkg\buildtrees\protobuf\install-x64-windows-dbg-out.log"
```
> C:\temp\vcpkg\buildtrees\protobuf\src\31c4d12c10-2e3bb0fe91.clean\src\google/protobuf/map_field.h(495): note: see declaration of 'google::protobuf::internal::TypeDefinedMapFieldBase<google::protobuf::MapKey,google::protobuf::MapValueRef>::InternalGetIterator'
> C:\temp\vcpkg\buildtrees\protobuf\src\31c4d12c10-2e3bb0fe91.clean\src\google\protobuf\util\message_differencer.cc(2098): warning C4661: 'void google::protobuf::internal::TypeDefinedMapFieldBase<google::protobuf::MapKey,google::protobuf::MapValueRef>::InitializeIterator(google::protobuf::MapIterator *) const': no suitable definition provided for explicit template instantiation request
> C:\temp\vcpkg\buildtrees\protobuf\src\31c4d12c10-2e3bb0fe91.clean\src\google/protobuf/map_field.h(499): note: see declaration of 'google::protobuf::internal::TypeDefinedMapFieldBase<google::protobuf::MapKey,google::protobuf::MapValueRef>::InitializeIterator'
> C:\temp\vcpkg\buildtrees\protobuf\src\31c4d12c10-2e3bb0fe91.clean\src\google\protobuf\util\message_differencer.cc(2098): warning C4661: 'void google::protobuf::internal::TypeDefinedMapFieldBase<google::protobuf::MapKey,google::protobuf::MapValueRef>::DeleteIterator(google::protobuf::MapIterator *) const': no suitable definition provided for explicit template instantiation request
> C:\temp\vcpkg\buildtrees\protobuf\src\31c4d12c10-2e3bb0fe91.clean\src\google/protobuf/map_field.h(500): note: see declaration of 'google::protobuf::internal::TypeDefinedMapFieldBase<google::protobuf::MapKey,google::protobuf::MapValueRef>::DeleteIterator'
> C:\temp\vcpkg\buildtrees\protobuf\src\31c4d12c10-2e3bb0fe91.clean\src\google\protobuf\util\message_differencer.cc(2098): warning C4661: 'void google::protobuf::internal::TypeDefinedMapFieldBase<google::protobuf::MapKey,google::protobuf::MapValueRef>::CopyIterator(google::protobuf::MapIterator *,const google::protobuf::MapIterator &) const': no suitable definition provided for explicit template instantiation request
> C:\temp\vcpkg\buildtrees\protobuf\src\31c4d12c10-2e3bb0fe91.clean\src\google/protobuf/map_field.h(501): note: see declaration of 'google::protobuf::internal::TypeDefinedMapFieldBase<google::protobuf::MapKey,google::protobuf::MapValueRef>::CopyIterator'
> C:\temp\vcpkg\buildtrees\protobuf\src\31c4d12c10-2e3bb0fe91.clean\src\google\protobuf\util\message_differencer.cc(2098): warning C4661: 'void google::protobuf::internal::TypeDefinedMapFieldBase<google::protobuf::MapKey,google::protobuf::MapValueRef>::IncreaseIterator(google::protobuf::MapIterator *) const': no suitable definition provided for explicit template instantiation request
> C:\temp\vcpkg\buildtrees\protobuf\src\31c4d12c10-2e3bb0fe91.clean\src\google/protobuf/map_field.h(503): note: see declaration of 'google::protobuf::internal::TypeDefinedMapFieldBase<google::protobuf::MapKey,google::protobuf::MapValueRef>::IncreaseIterator'
> [197/201] C:\PROGRA~2\MIB055~1\2017\PROFES~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe   /TP -DGOOGLE_PROTOBUF_CMAKE_BUILD -DLIBPROTOBUF_EXPORTS -DPROTOBUF_USE_DLLS -Dlibprotobuf_EXPORTS -I. -IC:\temp\vcpkg\buildtrees\protobuf\src\31c4d12c10-2e3bb0fe91.clean\src /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1    /MP /wd4018 /wd4065 /wd4146 /wd4244 /wd4251 /wd4267 /wd4305 /wd4307 /wd4309 /wd4334 /wd4355 /wd4506 /wd4800 /wd4996 /bigobj /showIncludes /FoCMakeFiles\libprotobuf.dir\C_\temp\vcpkg\buildtrees\protobuf\src\31c4d12c10-2e3bb0fe91.clean\src\google\protobuf\util\type_resolver_util.cc.obj /FdCMakeFiles\libprotobuf.dir\ /FS -c C:\temp\vcpkg\buildtrees\protobuf\src\31c4d12c10-2e3bb0fe91.clean\src\google\protobuf\util\type_resolver_util.cc
> [198/201] cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_dll --intdir=CMakeFiles\libprotobuf.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100177~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100177~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MIB055~1\2017\PROFES~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\link.exe  @CMakeFiles\libprotobuf.rsp  /out:libprotobufd.dll /implib:libprotobufd.lib /pdb:libprotobufd.pdb /dll /version:3.14 /machine:x64 /nologo    /debug /INCREMENTAL  && cd ."
> FAILED: libprotobufd.dll libprotobufd.lib 
> cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_dll --intdir=CMakeFiles\libprotobuf.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100177~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100177~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MIB055~1\2017\PROFES~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\link.exe  @CMakeFiles\libprotobuf.rsp  /out:libprotobufd.dll /implib:libprotobufd.lib /pdb:libprotobufd.pdb /dll /version:3.14 /machine:x64 /nologo    /debug /INCREMENTAL  && cd ."
>    Creating library libprotobufd.lib and object libprotobufd.exp
> FINAL LINK: command "C:\PROGRA~2\MIB055~1\2017\PROFES~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\link.exe @CMakeFiles\libprotobuf.rsp /out:libprotobufd.dll /implib:libprotobufd.lib /pdb:libprotobufd.pdb /dll /version:3.14 /machine:x64 /nologo /debug /INCREMENTAL /MANIFEST /MANIFESTFILE:CMakeFiles\libprotobuf.dir/intermediate.manifest CMakeFiles\libprotobuf.dir/manifest.res" failed (exit code 1168) with the following output:
> LINK : fatal error LNK1168: cannot open libprotobufd.dll for writing
> ninja: build stopped: subcommand failed.
```

**Additional context**
The x86 build works perfectly. It is only when trying to do the x64 build that this error occurs.

**Comment by autoantwort** [comment]
> Linker Tools Error LNK1168
>
>cannot open filename for writing
>
> The linker can’t write to filename. The file may be in use and its file handle locked by another process, or you may not have write permission for the file, or for the directory or network share it is located in. This error is often caused by a transient condition—for example, a lock held by an anti-virus program, a file search indexing process, or a delay in releasing a lock held by the Visual Studio build system.

**Comment by vkphd** [comment]
> > Linker Tools Error LNK1168
> > cannot open filename for writing
> > The linker can’t write to filename. The file may be in use and its file handle locked by another process, or you may not have write permission for the file, or for the directory or network share it is located in. This error is often caused by a transient condition—for example, a lock held by an anti-virus program, a file search indexing process, or a delay in releasing a lock held by the Visual Studio build system.

A few comments: 1) The build location is in a local folder, 2) I have admin permissions, 3) this is a repeatable error.

**Comment by vkphd** [comment]
I have updated my Visual Studio to 2019 and this issue is resolved when using VS2019. However, I believe that it is a repeatable issue for me when using VS2017.

**Comment by autoantwort** [comment]
Strange, but it seems that you are not the only one: see [here](https://github.com/microsoft/vcpkg/issues/11075#issuecomment-622723979)

**Comment by JackBoosY** [comment]
```
LINK : fatal error LNK1168: cannot open libprotobufd.dll for writing
```
Please clone vcpkg in non-system partition, close your anti-virus and try again.

Thanks.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

**Comment by michaeladamkatz** [comment]
@JackBoosY thanks for the tip on closing anti-virus. In my case, disabling "Real-time protection" in Windows Security (Windows 11 Home) stopped the random failures in several packages, including protobuf. May I strongly suggest that turning off real-time protection be one of the standard suggestions in https://learn.microsoft.com/en-us/vcpkg/troubleshoot/build-failures ?

**Comment by JackBoosY** [comment]
> [@JackBoosY](https://github.com/JackBoosY) thanks for the tip on closing anti-virus. In my case, disabling "Real-time protection" in Windows Security (Windows 11 Home) stopped the random failures in several packages, including protobuf. May I strongly suggest that turning off real-time protection be one of the standard suggestions in https://learn.microsoft.com/en-us/vcpkg/troubleshoot/build-failures ?

I think it's reasonable since the generated binary doesn't contains signature or certificate.
