### ISSUE TITLE
Package soil fetches from a dead website.

### ISSUE THREAD

**Issue by johan-forsberg** [microsoft/vcpkg#16785]
Error: Building package soil:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: soil:x86-windows
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

**Comment by autoantwort** [comment]
Is [this](https://github.com/littlstar/soil) the same library?

**Comment by johan-forsberg** [comment]
Yes, or a newer version. Is it available with vcpkg

**Comment by autoantwort** [comment]
I just discovered that there is already a soil2 package

**Comment by autoantwort** [comment]
And i have found #13008

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/15800.
