### ISSUE TITLE
[<port name>] build failure

### ISSUE THREAD

**Issue by electron271** [microsoft/vcpkg#16797]
**Host Environment**
- OS: Windows 10
- Compiler: Unknown

**To Reproduce**
`./vcpkg install GTKmm`

**Failure logs** 
  Package: expat:x86-windows
  Vcpkg version: 2020.11.12--unknownhash

**Comment by seckujdivad** [comment]
Hi, did you manage to fix this? I have started getting the same error (on the same package and version) using the following: gtest
wxwidgets
glm
opengl
nlohmann-json
glew
--triplet
x86-windows
