### ISSUE TITLE
A bootstrapped vcpkg tool `version` command should match the downloaded version

### ISSUE THREAD

**Issue by coryan** [microsoft/vcpkg#16790]
**Is your feature request related to a problem? Please describe.**

As I write this, the bootstrap script downloads version `2021-02-24-d67989bce1043b98092ac45996a8230a059a2d7e`:

https://github.com/microsoft/vcpkg/blob/9986c28da97f316fe3c79be0538af8f46a200796/scripts/bootstrap.sh#L279

However, once bootstrapped the `version` command reports:

```console
$ vcpkg  version
Vcpkg package management program version 2021-01-13-unknownhash

See LICENSE.txt for license information.
```

That seems confusing to me.

**Proposed solution**

I would like the vcpkg tool to report the version it was actually bootstrapped with. Seems like this could be done by setting `-DVCPKG_BASE_VERSION` to the correct value here:

https://github.com/microsoft/vcpkg/blob/9986c28da97f316fe3c79be0538af8f46a200796/scripts/bootstrap.sh#L301

**Describe alternatives you've considered**

Have not thought of any at this point.

**Additional context**

N/A

**Comment by PhoebeHui** [comment]
Related to https://github.com/microsoft/vcpkg/issues/16441, the VCPKG_BASE_VERSION also wrong on windows.

**Comment by PhoebeHui** [comment]
@coryan, this issue has been fixed in latest source. thanks for reporting the issue!

```
PS E:\vcpkg\clean\vcpkg> ./vcpkg version
Vcpkg package management program version 2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9

See LICENSE.txt for license information.
```
