### ISSUE TITLE
Cannot use gettext in UWP application

### ISSUE THREAD

**Issue by levinli303** [microsoft/vcpkg#16801]
**Describe the bug**
When I try to use gettext in a UWP application, the application failed to start.

**Environment**
- OS: Windows 10 20H2
- Compiler: VS 2019

**To Reproduce**
1. ./vcpkg install gettext:x64-uwp
2. Create a new project, UWP app, C++/CX
3. #include <intl.h> and use gettext somewhere in code
4. Build and run

**Expected behavior**
Should run without any issue.

**Failure logs** 
The target process aborted before activation completed.
The program '[1064] GettextTest.exe' has exited with code -1073741502 (0xc0000142) 'DLL Initialization Failed'.

**Additional context**
intl-8.dll iconv-2.dll ucrtbased.dll are present in the .exe folder.

**Comment by JackBoosY** [comment]
Confirmed.

**Comment by levinli303** [comment]
I tried to use libiconv only and it led to the  same error.

**Comment by levinli303** [comment]
@JackBoosY  I tested with the commit before #11776 is merged and it was working.

**Comment by levinli303** [comment]
@JackBoosY

I could see that in libiconv, it used GetModuleFileName to get the path and then used strchr to find the path separator.
GetModuleFileName mapped to GetModuleFileNameW but strchr is ANSI, which caused the failure in DLL initialization
