### ISSUE TITLE
ethash

### ISSUE THREAD

**Issue by suifeng0000** [microsoft/vcpkg#16808]
Library name:

Library description:

Source repository URL:

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by suifeng0000** [comment]
https://codeload.github.com/chfast/ethash/zip/refs/heads/master

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
