### ISSUE TITLE
[boost-compatibility] build failure

### ISSUE THREAD

**Issue by lpiert** [microsoft/vcpkg#16814]
Package: boost-compatibility:x86-windows
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

**Comment by autoantwort** [comment]
Without an error log it is hard to help

**Comment by JackBoosY** [comment]
Please provide output in Powershell and provide the failure logs.

Thanks.

**Comment by PhoebeHui** [comment]
@lpiert, please reopen this issue with failure logs if it still be a problem for you.
