### ISSUE TITLE
[secp256k1-zkp] build failure: The port directory does not exist

### ISSUE THREAD

**Issue by ndcroos** [microsoft/vcpkg#16812]
**Host Environment**
- OS: Debian 10
- Compiler: revision

**To Reproduce**
`./vcpkg install secp256k1-zkp`

**Failure logs** 

Computing installation plan...
Error: while loading secp256k1-zkp:
The port directory (<my project directory>/vcpkg/ports/secp256k1-zkp) does not exist
Error: failed to load port from <my project directory>/vcpkg/ports/secp256k1-zkp
Note: Updating vcpkg by rerunning bootstrap-vcpkg may resolve this failure.

**Additional context**
I have already tried rerunning bootstrap-vcpkg, but the issue remains.

**Comment by autoantwort** [comment]
There is no port `secp256k1-zkp`

**Comment by ndcroos** [comment]
Thanks, maybe it is an idea to request one.
