### ISSUE TITLE
[New Port Request]  libmt32emu

### ISSUE THREAD

**Issue by kcgen** [microsoft/vcpkg#16813]
**Name**:  libmt32emu

**Description**: libmt32emu is a stand-alone C and C++ library within the MT-32 emulator Munt software package. It's used in several game packages including ScummVM and DOSBox Staging. 

**Source URL**: https://github.com/munt/munt/tree/master/mt32emu (the library sub-project)

**Project homepage**: https://github.com/munt/munt

**Helpful information:**

Munt is a Cmake project.

libmt32emu is a subdirectory (`src/mt32emu`) within the `Munt` repository.  We are only interested in this stand-alone library for vcpkg.

To build it, we suggest using options that produce a stand-alone library without dependencies, such as:

``` shell
cd src/mt32emu
cmake \
  -DCMAKE_INSTALL_PREFIX:PATH=C:/vcpkg/installed/<your target>
  -DCMAKE_BUILD_TYPE:STRING=Release \
  -Dlibmt32emu_WITH_INTERNAL_RESAMPLER=true \
  -Dlibmt32emu_SHARED=false \
  .
make
ls libmt32emu.a
make install
```

**Comment by autoantwort** [comment]
Do you use specific versions or simply the master branch?

**Comment by kcgen** [comment]
Thanks @autoantwort!

We prefer to use the latest current release.   

The authors release updated versions roughly three times a year, and use a backward-compatible versioned API scheme.

**Comment by autoantwort** [comment]
Ok, so the [latest release](https://github.com/munt/munt/releases) tag for `libmt32emu` is `libmt32emu_2_4_2`?

**Comment by kcgen** [comment]
> Ok, so the [latest release](https://github.com/munt/munt/releases) tag for `libmt32emu` is `libmt32emu_2_4_2`?

Thanks for the clarification (I mentioned 2.4.0 above, but that's for the entire project).

Yes, `libmt32emu_2_4_2` for `libmt32emu`.

**Comment by Raffaello** [comment]
it looks like that the CMake config file of libmt32emu is not present after install with vcpkg,
I have created this issue: https://github.com/microsoft/vcpkg/issues/22273 to report it as it looks like to me that a cmake config file should be shipped to.
