### ISSUE TITLE
[protobuf] build failure

### ISSUE THREAD

**Issue by HppZ** [microsoft/vcpkg#16811]
Starting package 1/5: protobuf:x86-uwp
Building package protobuf[core]:x86-uwp...
-- Using community triplet x86-uwp. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: C:\Users\haopeng\Documents\UserName\code\opensource\vcpkg\triplets\community\x86-uwp.cmake
-- Using cached C:/Users/haopeng/Documents/UserName/code/opensource/vcpkg/downloads/protocolbuffers-protobuf-2514f0bd7da7e2af1bed4c5d1b84f031c4d12c10.tar.gz
-- Cleaning sources at C:/Users/haopeng/Documents/haopeng/code/opensource/vcpkg/buildtrees/protobuf/src/31c4d12c10-2e3bb0fe91.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/haopeng/Documents/haopeng/code/opensource/vcpkg/downloads/protocolbuffers-protobuf-2514f0bd7da7e2af1bed4c5d1b84f031c4d12c10.tar.gz
-- Applying patch fix-static-build.patch
-- Applying patch fix-default-proto-file-path.patch
-- Using source at C:/Users/UserName/Documents/haopeng/code/opensource/vcpkg/buildtrees/protobuf/src/31c4d12c10-2e3bb0fe91.clean
CMake Error at ports/protobuf/portfile.cmake:21 (message):
  Cross-targetting protobuf requires the x86-windows protoc to be available.
  Please install protobuf:x86-windows first.
Call Stack (most recent call first):
  scripts/ports.cmake:142 (include)

Error: Building package protobuf:x86-uwp failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: protobuf:x86-uwp
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

Additionally, attach any relevant sections from the log files above.

@JackBoosY

**Comment by autoantwort** [comment]
> Cross-targetting protobuf requires the x86-windows protoc to be available.
Please install protobuf:x86-windows first.

Have you read the error message? :)

**Comment by JackBoosY** [comment]
Should change to host port.
