### ISSUE TITLE
Specify triplet in manifest mode

### ISSUE THREAD

**Issue by acgetchell** [microsoft/vcpkg#16829]
****

**Is your feature request related to a problem? Please describe.**
The package `cgal` requires `gmp`, which on Windows requires `yasm-tool:x86-windows`, even when building using `x64-windows`. The `vcpkg.json` file does not have an option to set this.

**Proposed solution**
A triplet attribute, e.g.
```
{
  "name": "cdt-plusplus",
  "version": "0.1.8",
  "dependencies": [
    "catch2",
    "docopt",
    "date",
    "fmt",
    "ms-gsl",
    "eigen3",
    "pcg",
    "tbb",
    {
      "name": "yasm-tool",
      "platform": "windows",
      "triplet": "x86-windows"
    },
    "cgal"
  ]
}
```

**Describe alternatives you've considered**
I have to build in classic mode, but it gets confusing when you build in manifest mode on Travis-CI and GitHub actions, but then have to build in classic mode on AppVeyor. So far, this only works with a `CMakeLists.txt` such as:

https://github.com/acgetchell/CDT-plusplus/blob/develop/CMakeLists.txt

(All the lines before `project()`).

**Additional context**
https://ci.appveyor.com/project/acgetchell/cdt-plusplus#L557

**Comment by Pospelove** [comment]
@acgetchell 
Hey! Just seen your issue and it seems that I have a workaround for you.

1. Create a [custom triplet.](https://github.com/skyrim-multiplayer/skyrim-platform/blob/ed5fd257af3bbeccdb54f567d42788ae07514ec6/overlay_triplets/x64-windows-sp.cmake) In my case I need to link everything statically except Chakracore.
```cmake
set(VCPKG_TARGET_ARCHITECTURE x64)

set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE static)

if(${PORT} MATCHES "chakracore")
  set(VCPKG_CRT_LINKAGE dynamic)
  set(VCPKG_LIBRARY_LINKAGE dynamic)
endif()
```
2. Tell vcpkg where is your custom triplet located. In my case, I have added this to the CMakeLists.txt [directly](https://github.com/skyrim-multiplayer/skyrim-platform/blob/8501a04b17f1f5b0cfa9db531ea18bd3d3de0fbe/CMakeLists.txt#L2). See also [an official overlay triplets example](https://vcpkg.readthedocs.io/en/latest/examples/overlay-triplets-linux-dynamic/).

**Comment by autoantwort** [comment]
Maybe you want to set the [VCPKG_DEFAULT_HOST_TRIPLET](https://github.com/microsoft/vcpkg/blob/master/docs/users/config-environment.md#vcpkg_default_host_triplet) variable

**Comment by autoantwort** [comment]
But I think you depend on #16478

**Comment by JackBoosY** [comment]
Yes, #16478 will solve this issue.

**Comment by acgetchell** [comment]
Setting `VCPKG_DEFAULT_HOST_TRIPLET` does not work, vcpkg still uninstalls x86-windows packages and attempts to install x64-windows ones, until it reaches gmp and fails.

https://ci.appveyor.com/project/acgetchell/cdt-plusplus/builds/38375679#L3658

**Comment by autoantwort** [comment]
You have to wait until #16478 gets merged, or you use the branch from the PR
