### ISSUE TITLE
[libusb] Use Visual Studio 2019 for Platform v142

### ISSUE THREAD

**Issue by jamiehankins** [microsoft/vcpkg#16832]
In the portfile.cmake file, there's this:
```
  if(VCPKG_PLATFORM_TOOLSET MATCHES "v142")
    set(MSVS_VERSION 2017)  #they are abi compatible, so it should work
```
I changed it locally to 2019, and it seems to work fine. Is there a solid reason for forcing it to use the 2017 sln file?

**Comment by NancyLi1013** [comment]
Hi @jamiehankins 

Thanks for posting this issue. I can also build it successfully with Visual Studio 2019.

@cenit 
Could you please help confirm why you use 2017 instead of 2019 here?

Thanks.

**Comment by cenit** [comment]
because MSVS_VERSION (a variable defined by the project) equal to 2019 was not resolving into anything back in time. Is it now?

**Comment by jamiehankins** [comment]
@cenit it's used to select the correct project file. Maybe the 2019 one wasn't available before. It is now.

**Comment by NancyLi1013** [comment]
@cenit and @jamiehankins Thanks for your clarification and information.
Seems the current version has supported Visual Studio 2019. So I think we can use 2019 now. I will create a PR to fix it later.

**Comment by NancyLi1013** [comment]
@jamiehankins Sorry, I noticed your information just now. I have submitted a PR to fix this. Factually, we're glad to see that contributors can joining with us. So you can do this work if you would like next time.

**Comment by jamiehankins** [comment]
@NancyLi1013 oh, no problem at all. I get plenty of chances to submit PRs in my day job. I'm just happy it's getting fixed. 🙂
