### ISSUE TITLE
[CGAL] build failure 

### ISSUE THREAD

**Issue by ctgeorge** [microsoft/vcpkg#16841]
Hi,
I'm very new to installing this sort of stuff, but I'm having problems installing CGAL - I get the error messages
````
-- Installing: C:/dev/vcpkg/packages/boost-regex_x86-windows/share/boost-regex/copyright
-- Performing post-build validation
Detected outdated dynamic CRT in the following files:

    C:\dev\vcpkg\packages\boost-regex_x86-windows\bin\boost_regex-vc120-mt-x32-1_75.dll: msvcp120.dll

To inspect the dll files, use:
    dumpbin.exe /dependents mydllfile.dll
Found 1 error(s). Please correct the portfile:
    C:\dev\vcpkg\ports\boost-regex\portfile.cmake
-- Performing post-build validation done
Error: Building package boost-regex:x86-windows failed with: POST_BUILD_CHECKS_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-regex:x86-windows
  Vcpkg version: 2021-01-13-768d8f95c9e752603d2c5901c7a7c7fbdb08af35
````
Additionally, attach any relevant sections from the log files above.

Thanks
Charles

**Comment by JonLiu1993** [comment]
@ctgeorge ,Thanks for posting this issue. I cannot reproduce this issue on my machine.There are several related issues here about Detected outdated dynamic CRT in the following files, but they have not been resolved yet, so we wait for other related issues.[#717](https://github.com/microsoft/cpprestsdk/issues/717) #16732

**Comment by JonLiu1993** [comment]
@ctgeorge ,Does this problem still exist?

**Comment by JonLiu1993** [comment]
Thanks for posting this issue. Please reopen this issue if it still be a problem for you.
