### ISSUE TITLE
[apr] provides CMake targets

### ISSUE THREAD

**Issue by pengliaoye** [microsoft/vcpkg#16840]
****

**Is your feature request related to a problem? Please describe.**
vcpkg install apr,
don't display find_package and target_link_libraries  cmake info

**Proposed solution**
support and display find_package  and target_link_libraries  config

**Describe alternatives you've considered**

**Additional context**.

**Comment by pengliaoye** [comment]
@JonLiu1993 also add apr_util package CMake targets

**Comment by JonLiu1993** [comment]
@pengliaoye ,Please reopen an issue. Regarding apr_util, this issue only solves apr
