### ISSUE TITLE
[bzip2] build failure

### ISSUE THREAD

**Issue by yurybura** [microsoft/vcpkg#16846]
**Host Environment**
- OS: Ubuntu 16.04.7 LTS (WSL)
- Compiler: gcc (Ubuntu 7.5.0-3ubuntu1~16.04) 7.5.0

**To Reproduce**
`./vcpkg install bzip2`

**Failure logs** 
Starting package 1/1: bzip2:x64-linux
Building package bzip2[core]:x64-linux...
-- Fetching https://sourceware.org/git/bzip2.git...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
    Command failed: /usr/bin/git fetch https://sourceware.org/git/bzip2.git 75a94bea3918e612b879d6a11ca64b8689526147 --depth 1 -n
    Working Directory: /mnt/d/libs/vcpkg/downloads/git-tmp
    Error code: 128
    See logs for more information:
      /mnt/d/libs/vcpkg/buildtrees/bzip2/git-fetch-x64-linux-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_git.cmake:91 (vcpkg_execute_required_process)
  ports/bzip2/portfile.cmake:1 (vcpkg_from_git)
  scripts/ports.cmake:142 (include)

Error: Building package bzip2:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: bzip2:x64-linux
  Vcpkg version: 2021-01-13-unknownhash

Additionally, attach any relevant sections from the log files above.

[git-fetch-x64-linux-err.log](https://github.com/microsoft/vcpkg/files/6190462/git-fetch-x64-linux-err.log)

**Comment by StarGate-One** [comment]
@yurybura 
- See https://github.com/microsoft/vcpkg/issues/14424 - this is a known issue due to the old version of git installed with Ubuntu 16.04 LTS.
- Upgrading git version to a newer version (I believe it has to be done manually) and it will be able to download the repo file just fine.

**Comment by yurybura** [comment]
@StarGate-One Thank you.
Duplicate of https://github.com/microsoft/vcpkg/issues/14424
