### ISSUE TITLE
building bzip2:x86-windows-static out of the box just fails

### ISSUE THREAD

**Issue by thierryba** [Microsoft/vcpkg#1684]
I'm using visual studio 2015 express.
in config-x86-windows-static-rel.log, I can see

CMake Error at C:/github/vcpkg/scripts/buildsystems/vcpkg.cmake:32 (message):
  Unable to determine target architecture.
Call Stack (most recent call first):
  C:/github/vcpkg/downloads/cmake-3.9.1-win32-x86/share/cmake-3.9/Modules/CMakeDetermineSystem.cmake:94 (include)
  CMakeLists.txt:2 (project)

CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage

**Comment by thierryba** [comment]
ah it seems it is just because I had set CL=/MP to make my other builds fast.. And cmake does not like that..

**Comment by thierryba** [comment]
For the record it is not the only package that just fails like that.

**Comment by alexkaratarakis** [comment]
This might have something to do with the Express edition.
Does the default (x86-windows) work for you?

**Comment by thierryba** [comment]
Hi. No the non static one does not work either. It semés To be a problem
with and cmake based package.

**Comment by thierryba** [comment]
hmm I just tried something I had found on another GitHub issue and it worked: I commented PREFER_NINJA in the portfile.cmake. Is that a known issue?
And, is there a way to globally disable the PREFER_NINJA option?

**Comment by Mixaill** [comment]
It's probably #1660 bug. Do you use non-English Microsoft Visual Studio?

**Comment by thierryba** [comment]
I'm using an english Visual Studio. I tried the workaround with no luck.

**Comment by thierryba** [comment]
For the record I've just tried to build openssl and it fails as well but this time in the logs I can see:

'cl' is not recognised as an internal or external command.

So it seems it has big problems finding the compiler...

**Comment by thierryba** [comment]
aha, I think I found something and it seems indeed related to having an express edition.
when I tried vcpkg env --debug I've seen that it tries to call vcvarsall amd64_x86 but that does not work on express. So I patched the code to call it with x86 and suddenly openssl builds fine as does bzip2.

Anything else you'd need from me?

**Comment by Mixaill** [comment]
Working on it.

**Comment by thierryba** [comment]
Thanks a lot. I love vcpkg. It Will simplify a lot our build process on
windows.

Le 24 août 2017 11:30 AM, "Mikhail Paulyshka" <notifications@github.com> a
écrit :

**Comment by Mixaill** [comment]
Pleasy try to rebuild vcpkg.exe from #1690

**Comment by thierryba** [comment]
works like a charm.
