### ISSUE TITLE
[Python3] Cannot find Python3

### ISSUE THREAD

**Issue by lukedan** [microsoft/vcpkg#16853]
**Host Environment**
- OS: Windows 10 20H2
- Compiler: Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29913 for x64

**To Reproduce**
`./vcpkg install python3:x64-windows`

**Failure logs** 

With `find_package(Python3 CONFIG COMPONENTS Development REQUIRED)`:

```
1> [CMake] CMake Error at D:/Software/vcpkg/installed/x64-windows/share/python3/vcpkg-cmake-wrapper.cmake:67 (_find_package):
1> [CMake]   Could not find a package configuration file provided by "Python3" with any
1> [CMake]   of the following names:
1> [CMake] 
1> [CMake]     Python3Config.cmake
1> [CMake]     python3-config.cmake
1> [CMake] 
1> [CMake]   Add the installation prefix of "Python3" to CMAKE_PREFIX_PATH or set
1> [CMake]   "Python3_DIR" to a directory containing one of the above files.  If
1> [CMake]   "Python3" provides a separate development package or SDK, be sure it has
1> [CMake]   been installed.
1> [CMake] Call Stack (most recent call first):
1> [CMake]   D:/Software/vcpkg/scripts/buildsystems/vcpkg.cmake:815 (include)
1> [CMake]   plugins/python_plugin_host_pybind11/CMakeLists.txt:12 (find_package)
1> [CMake] -- Configuring incomplete, errors occurred!
1> [CMake] See also "D:/Documents/Projects/codepad/out/build/x64-Debug/CMakeFiles/CMakeOutput.log".
```

`CMakeOutput.log` mainly only contains feature-test results and does not contain anything useful.

With `find_package(pybind11 CONFIG REQUIRED)`:

```
1> [CMake] CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
1> [CMake]   Could NOT find PythonInterp (missing: PYTHON_EXECUTABLE)
1> [CMake] Call Stack (most recent call first):
1> [CMake]   C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:582 (_FPHSA_FAILURE_MESSAGE)
1> [CMake]   C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.19/Modules/FindPythonInterp.cmake:169 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
1> [CMake]   D:/Software/vcpkg/installed/x64-windows/share/pythoninterp/vcpkg-cmake-wrapper.cmake:10 (_find_package)
1> [CMake]   D:/Software/vcpkg/scripts/buildsystems/vcpkg.cmake:815 (include)
1> [CMake]   D:/Software/vcpkg/installed/x64-windows/share/pybind11/FindPythonLibsNew.cmake:96 (find_package)
1> [CMake]   D:/Software/vcpkg/scripts/buildsystems/vcpkg.cmake:861 (_find_package)
1> [CMake]   D:/Software/vcpkg/installed/x64-windows/share/pybind11/pybind11Tools.cmake:38 (find_package)
1> [CMake]   D:/Software/vcpkg/installed/x64-windows/share/pybind11/pybind11Common.cmake:195 (include)
1> [CMake]   D:/Software/vcpkg/installed/x64-windows/share/pybind11/pybind11Config.cmake:249 (include)
1> [CMake]   D:/Software/vcpkg/scripts/buildsystems/vcpkg.cmake:861 (_find_package)
1> [CMake]   plugins/python_plugin_host_pybind11/CMakeLists.txt:13 (find_package)
1> [CMake] -- Configuring incomplete, errors occurred!
1> [CMake] See also "D:/Documents/Projects/codepad/out/build/x64-Debug/CMakeFiles/CMakeOutput.log".
```

**Additional context**

Make sure you don't have Python3 installed system-wide before attempting to reproduce this issue.

**Comment by NancyLi1013** [comment]
Hi @lukedan 

Thanks for posting this issue.

Seems you didn't use python3 correctly.
The usage should be like this:

```
find_package(Python3 COMPONENTS Development REQUIRED)
target_link_libraries(main PRIVATE Python3::Python)
```
Since there is no *config.cmake file for python3, `CONFIG ` should not be added here.

**Comment by lukedan** [comment]
Aha! So that's what I've been missing. However, the issue with `pybind11` is still present: `pybind11` uses `FindPythonInterp` which cannot find the Python3 libraries installed by `vcpkg`.

**Comment by lukedan** [comment]
Update: Now I'm running into the error `fatal error LNK1104: cannot open file 'python39.lib'`.

**Comment by lukedan** [comment]
[An issue of the `pybind11` repository](https://github.com/pybind/pybind11/issues/2661) indicates that using `-DPYBIND11_FINDPYTHON=ON` can make `pybind11` use `FindPython2/3` instead of the deprecated `FindPythonInterp`.

**Comment by lukedan** [comment]
Also, I checked `vcpkg\installed\x64-windows\lib` and `python39.lib` **is** there.

**Comment by lukedan** [comment]
@NancyLi1013 Were you able to reproduce this issue?

**Comment by lukedan** [comment]
Opened separate issue #16956.

**Comment by qgbcs** [comment]
Call Stack (most recent call first):    
  /opt/vcpkg/scripts/buildsystems/vcpkg.cmake:813 (include)                      
  /opt/vcpkg/installed/x64-linux/share/pybind11/FindPythonLibsNew.cmake:98 (find_package)                                                                         
  /opt/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package)                
  /opt/vcpkg/installed/x64-linux/share/pybind11/pybind11Tools.cmake:50 (find_package)                                                                             
  /opt/vcpkg/installed/x64-linux/share/pybind11/pybind11Common.cmake:188 (include)                                                                                
  /opt/vcpkg/installed/x64-linux/share/pybind11/pybind11Config.cmake:250 (include)                                                                                
  /opt/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package)                
  CMakeLists.txt:18 (find_package)      
This warning is for project developers.  Use -Wno-dev to suppress it.            

CMake Error at /opt/cmake/share/cmake-3.28/Modules/FindPackageHandleStandardArgs.cmake:230 (message):                                                             
  Could NOT find PythonInterp (missing: PYTHON_EXECUTABLE) (Required is at       
  least version "3.6")                  
Call Stack (most recent call first):    
  /opt/cmake/share/cmake-3.28/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)                                                            
  /opt/cmake/share/cmake-3.28/Modules/FindPythonInterp.cmake:182 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)                                                              
  /opt/vcpkg/installed/x64-linux/share/pythoninterp/vcpkg-cmake-wrapper.cmake:10 (_find_package)                                                                  
  /opt/vcpkg/scripts/buildsystems/vcpkg.cmake:813 (include)                      
  /opt/vcpkg/installed/x64-linux/share/pybind11/FindPythonLibsNew.cmake:98 (find_package)                                                                         
  /opt/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package)
