### ISSUE TITLE
[cfitsio] build failure

### ISSUE THREAD

**Issue by zyplmn** [microsoft/vcpkg#16854]
**Host Environment**
- OS: Windows10
- Compiler: VS2017

**To Reproduce**
`.\vcpkg.exe install pdal:x64-windows`

**Failure logs** 
Build messages from the console output：
PS E:\vcpkg\vcpkg> .\vcpkg.exe install pdal:x64-windows
Computing installation plan...
The following packages will be built and installed:
  * cfitsio[core]:x64-windows -> 3.49
  * curl[core,non-http,schannel,ssl,sspi,winssl]:x64-windows -> 7.74.0#3
  * expat[core]:x64-windows -> 2020-08-18
  * gdal[core]:x64-windows -> 3.1.3#2
  * geos[core]:x64-windows -> 3.9.1
  * hdf5[core,szip,zlib]:x64-windows -> 1.12.0
  * jsoncpp[core]:x64-windows -> 1.9.4
  * laszip[core]:x64-windows -> 3.4.3
  * libgeotiff[core]:x64-windows -> 1.6.0#1
  * libiconv[core]:x64-windows -> 1.16#8
  * libjpeg-turbo[core]:x64-windows -> 2.0.6
  * liblzma[core]:x64-windows -> 5.2.5#2
  * libpng[core]:x64-windows -> 1.6.37#14
  * libpq[core,openssl,zlib]:x64-windows -> 12.2#13
  * libwebp[core,nearlossless,simd,unicode]:x64-windows -> 1.1.0#1
  * libxml2[core]:x64-windows -> 2.9.10#3
  * netcdf-c[core]:x64-windows -> 4.7.4#2
  * openjpeg[core]:x64-windows -> 2.3.1#3
  * openssl[core]:x64-windows -> 1.1.1j
    pdal[core]:x64-windows -> 1.7.1#11
  * proj4[core,database,tiff]:x64-windows -> 7.2.1#1
  * sqlite3[core,tool]:x64-windows -> 3.35.0
  * szip[core]:x64-windows -> 2.1.1-6
  * tiff[core]:x64-windows -> 4.1.0#1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\zyplm\AppData\Local\vcpkg\archives\f6\f6b1daaf2d8935589415b46f5dc1ef08966f268c.zip
Could not locate cached archive: C:\Users\zyplm\AppData\Local\vcpkg\archives\1f\1f401b08e31209369fdcf910048922a54e689aaf.zip
Could not locate cached archive: C:\Users\zyplm\AppData\Local\vcpkg\archives\7f\7f49aac96bcf1d64d9ea6a97f531ab9e7990124a.zip
Could not locate cached archive: C:\Users\zyplm\AppData\Local\vcpkg\archives\d1\d1ff6927556558f7cbf2d18e4d5c94e191526209.zip
Could not locate cached archive: C:\Users\zyplm\AppData\Local\vcpkg\archives\ae\ae27fbd28e5dd2d1f9b0d32db117d087405cf810.zip
Could not locate cached archive: C:\Users\zyplm\AppData\Local\vcpkg\archives\58\581f2ea9106e8a541568c68c5ed61c608891285c.zip
Could not locate cached archive: C:\Users\zyplm\AppData\Local\vcpkg\archives\eb\ebe4c4bd9652fc442f749c77ff658030881d236a.zip
Could not locate cached archive: C:\Users\zyplm\AppData\Local\vcpkg\archives\ac\ace82f1cb419c6a1214d835ecd6263447eddb7ec.zip
Could not locate cached archive: C:\Users\zyplm\AppData\Local\vcpkg\archives\8c\8c695c8bd9748fb350c39043178e2a6b0e5c00d6.zip
Could not locate cached archive: C:\Users\zyplm\AppData\Local\vcpkg\archives\6e\6e15c8958c19726c9ff602eafde43bd7c1144eca.zip
Could not locate cached archive: C:\Users\zyplm\AppData\Local\vcpkg\archives\84\8478c9fefc6303baa08e4e8cff21217a49801676.zip
Could not locate cached archive: C:\Users\zyplm\AppData\Local\vcpkg\archives\29\29d5d89676d4acf17a1d5f35abc6f2664d45d071.zip
Could not locate cached archive: C:\Users\zyplm\AppData\Local\vcpkg\archives\14\14a10c591530a7d44bf43aa0cdafee4884cde5b1.zip
Could not locate cached archive: C:\Users\zyplm\AppData\Local\vcpkg\archives\17\176934adc95a58eb54f41700407f34c7609ca05b.zip
Could not locate cached archive: C:\Users\zyplm\AppData\Local\vcpkg\archives\07\07ae40f63e2bf1fa04040e2aa1cd6e29b0dc23b6.zip
Could not locate cached archive: C:\Users\zyplm\AppData\Local\vcpkg\archives\c2\c2d1763a414927c0acc691f3d76d1b993b69ece1.zip
Could not locate cached archive: C:\Users\zyplm\AppData\Local\vcpkg\archives\95\95fa1c759ce3b6939d29a655e2207125acc97fc6.zip
Could not locate cached archive: C:\Users\zyplm\AppData\Local\vcpkg\archives\d0\d0cdb8f60f5a52e96b2bc9c660ae1f9b5443add5.zip
Could not locate cached archive: C:\Users\zyplm\AppData\Local\vcpkg\archives\44\445cfe2ebbd88c10e2757e27bc544211d49b1d2e.zip
Could not locate cached archive: C:\Users\zyplm\AppData\Local\vcpkg\archives\2e\2e49328c20b9b69283bb6bf9872579111763db17.zip
Could not locate cached archive: C:\Users\zyplm\AppData\Local\vcpkg\archives\34\34644730667e74890254b10c79d803e728be9755.zip
Could not locate cached archive: C:\Users\zyplm\AppData\Local\vcpkg\archives\77\7729a66bf489eb1185d326985c4d885fb45483bb.zip
Could not locate cached archive: C:\Users\zyplm\AppData\Local\vcpkg\archives\b7\b7bf77808f451404290c0244107c84dcfe670423.zip
Could not locate cached archive: C:\Users\zyplm\AppData\Local\vcpkg\archives\b3\b328f1fda6bb4999c1d093ea8c5f0714c6398070.zip
Starting package 1/24: cfitsio:x64-windows
Building package cfitsio[core]:x64-windows...
-- Using cached E:/vcpkg/vcpkg/downloads/cfitsio-3.49.tar.gz
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:105 (message):

  File does not have expected hash:

          File path: [ E:/vcpkg/vcpkg/downloads/cfitsio-3.49.tar.gz ]
      Expected hash: [ 9836a4af3bbbfed1ea1b4c70b9d500ac485d7c3d8131eb8a25ee6ef6662f46ba52b5161c45c709ed9a601ff0e9ec36daa5650eaaf4f2cc7d6f4bb5640f10da15 ]
        Actual hash: [ a7b279c404e969d5b11d018694ec656a57914bbb360d868b2edbd35cbc831e3b7c85e51042115566846fd3a6dbabe5d53775a8cdb94718ec5007a473abb03447 ]

  Please delete the file and retry if this file should be downloaded again.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:118 (test_hash)
  ports/cfitsio/portfile.cmake:1 (vcpkg_download_distfile)
  scripts/ports.cmake:142 (include)

Error: Building package cfitsio:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: cfitsio:x64-windows
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

Additionally, attach any relevant sections from the log files above.

**Additional context**
Failure logs：
-- Using cached E:/vcpkg/vcpkg/downloads/cfitsio-3.49.tar.gz
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:105 (message):
  

  File does not have expected hash:

          File path: [ E:/vcpkg/vcpkg/downloads/cfitsio-3.49.tar.gz ]
      Expected hash: [ 9836a4af3bbbfed1ea1b4c70b9d500ac485d7c3d8131eb8a25ee6ef6662f46ba52b5161c45c709ed9a601ff0e9ec36daa5650eaaf4f2cc7d6f4bb5640f10da15 ]
        Actual hash: [ a7b279c404e969d5b11d018694ec656a57914bbb360d868b2edbd35cbc831e3b7c85e51042115566846fd3a6dbabe5d53775a8cdb94718ec5007a473abb03447 ]

  Please delete the file and retry if this file should be downloaded again.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:118 (test_hash)
  ports/cfitsio/portfile.cmake:1 (vcpkg_download_distfile)
  scripts/ports.cmake:142 (include)

**Comment by NancyLi1013** [comment]
Hi @zyplmn 

Thanks for posting this issue.
Could you please help check if you have downloaded `E:/vcpkg/vcpkg/downloads/cfitsio-3.49.tar.gz ` here? If so, please remove this file and try to rebuild this.

I can download it successfully on my machine.

```
PS F:\tool\vcpkg> .\vcpkg.exe install cfitsio --editable
Computing installation plan...
The following packages will be built and installed:
    cfitsio[core]:x86-windows -> 3.49
Starting package 1/1: cfitsio:x86-windows
Building package cfitsio[core]:x86-windows...
-- Downloading http://heasarc.gsfc.nasa.gov/FTP/software/fitsio/c/cfitsio-3.49.tar.gz -> cfitsio-3.49.tar.gz...
-- Extracting source F:/tool/vcpkg/downloads/cfitsio-3.49.tar.gz
-- Applying patch 0001-fix-dependencies.patch
-- Applying patch 0002-export-cmake-targets.patch
-- Applying patch 0003-add-Wno-error-implicit-funciton-declaration-to-cmake.patch
-- Using source at F:/tool/vcpkg/buildtrees/cfitsio/src/cfitsio-3-7822097674
CMake Deprecation Warning at scripts/cmake/vcpkg_check_features.cmake:182 (message):
  calling `vcpkg_check_features` without the `FEATURES` keyword has been
  deprecated.

      Please add the `FEATURES` keyword to the call.
Call Stack (most recent call first):
  ports/cfitsio/portfile.cmake:16 (vcpkg_check_features)
  scripts/ports.cmake:142 (include)


-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Using msys root at F:/tool/vcpkg/downloads/tools/msys2/50864d9fae363d6e
-- Fixing pkgconfig file: F:/tool/vcpkg/packages/cfitsio_x86-windows/lib/pkgconfig/cfitsio.pc
-- Fixing pkgconfig file: F:/tool/vcpkg/packages/cfitsio_x86-windows/debug/lib/pkgconfig/cfitsio.pc
-- Installing: F:/tool/vcpkg/packages/cfitsio_x86-windows/share/unofficial-cfitsio/FindPthreads.cmake
-- Installing: F:/tool/vcpkg/packages/cfitsio_x86-windows/share/cfitsio/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package cfitsio[core]:x86-windows... done
Installing package cfitsio[core]:x86-windows...
Installing package cfitsio[core]:x86-windows... done
Elapsed time for package cfitsio:x86-windows: 40.7 s

Total elapsed time: 40.75 s

The package cfitsio:x86-windows provides CMake targets:

    find_package(unofficial-cfitsio CONFIG REQUIRED)
    target_link_libraries(main PRIVATE cfitsio)
```

**Comment by zyplmn** [comment]
Thanks for your recommendation. Firstly, I check the file in E:/vcpkg/vcpkg/downloads, the cfitsio-3.49.tar.gz is Exist. However, if i removed cfitsio-3.49.tar.gz and install cfitsio, the error imformation would appear:

PS E:\vcpkg\vcpkg> .\vcpkg.exe install cfitsio --editable
Computing installation plan...
The following packages will be built and installed:
    cfitsio[core]:x86-windows -> 3.49
  * zlib[core]:x86-windows -> 1.2.11#9
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x86-windows...
Could not locate cached archive: C:\Users\zyplm\AppData\Local\vcpkg\archives\55\55fd4ac77a83e0229c7d97ae1f31f886477e1c0b.zip
Could not locate cached archive: C:\Users\zyplm\AppData\Local\vcpkg\archives\.zip
Starting package 1/2: zlib:x86-windows
Building package zlib[core]:x86-windows...
-- Using cached E:/vcpkg/vcpkg/downloads/zlib1211.tar.gz
-- Cleaning sources at E:/vcpkg/vcpkg/buildtrees/zlib/src/1.2.11-63309e48e5.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/vcpkg/vcpkg/downloads/zlib1211.tar.gz
-- Applying patch cmake_dont_build_more_than_needed.patch
-- Applying patch 0001-Prevent-invalid-inclusions-when-HAVE_-is-set-to-0.patch
-- Applying patch add_debug_postfix_on_mingw.patch
-- Using source at E:/vcpkg/vcpkg/buildtrees/zlib/src/1.2.11-63309e48e5.clean
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Using msys root at E:/vcpkg/vcpkg/downloads/tools/msys2/50864d9fae363d6e
-- Fixing pkgconfig file: E:/vcpkg/vcpkg/packages/zlib_x86-windows/lib/pkgconfig/zlib.pc
-- Fixing pkgconfig file: E:/vcpkg/vcpkg/packages/zlib_x86-windows/debug/lib/pkgconfig/zlib.pc
-- Installing: E:/vcpkg/vcpkg/packages/zlib_x86-windows/share/zlib/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\zyplm\AppData\Local\vcpkg\archives\55\55fd4ac77a83e0229c7d97ae1f31f886477e1c0b.zip
Building package zlib[core]:x86-windows... done
Installing package zlib[core]:x86-windows...
Installing package zlib[core]:x86-windows... done
Elapsed time for package zlib:x86-windows: 25.35 s
Starting package 2/2: cfitsio:x86-windows
Building package cfitsio[core]:x86-windows...
-- Downloading http://heasarc.gsfc.nasa.gov/FTP/software/fitsio/c/cfitsio-3.49.tar.gz -> cfitsio-3.49.tar.gz...
-- Downloading http://heasarc.gsfc.nasa.gov/FTP/software/fitsio/c/cfitsio-3.49.tar.gz... Failed. Status: 28;"Timeout was reached"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:184 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".

      If error with status 4 (Issue #15434),
      try setting "http://user:password@your-proxy-ip-address:port/".

      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  ports/cfitsio/portfile.cmake:1 (vcpkg_download_distfile)
  scripts/ports.cmake:142 (include)


Error: Building package cfitsio:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: cfitsio:x86-windows
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

**Comment by NancyLi1013** [comment]
Seems there is something wrong with your network. In this case, you can download _http://heasarc.gsfc.nasa.gov/FTP/software/fitsio/c/cfitsio-3.49.tar.gz_ manually if have access to this file.

Then you can put this archive to _E:/vcpkg/vcpkg/downloads/_ folder. 
At last, you can run `.\vcpkg.exe install cfitsio` to rebuild this port.

**Comment by NancyLi1013** [comment]
If you still failed with the same error as before, please change hash `9836a4af3bbbfed1ea1b4c70b9d500ac485d7c3d8131eb8a25ee6ef6662f46ba52b5161c45c709ed9a601ff0e9ec36daa5650eaaf4f2cc7d6f4bb5640f10da15` as `a7b279c404e969d5b11d018694ec656a57914bbb360d868b2edbd35cbc831e3b7c85e51042115566846fd3a6dbabe5d53775a8cdb94718ec5007a473abb03447` in _E:/vcpkg/vcpkg/ports/bzip2/portfile.cmake_ and try to build `cfitsio `again.

**Comment by zyplmn** [comment]
Perfect answer !

**Comment by zyplmn** [comment]
Good answer ! 
As you said, There is the same error as before.  However，the change hash does not exist in _E:/vcpkg/vcpkg/ports/bzip2/portfile.cmake_. The right path of change hash exist in _E:/vcpkg/vcpkg/ports/cfitsio/portfile.cmake_. Then build cfitsio. Thanks a lot !

**Comment by NancyLi1013** [comment]
Sorry for my mistake. And thanks for your kindly reminder. It should be `cfitsio` instead of `bzip2`.

**Comment by NancyLi1013** [comment]
Can you download `cfitsio` now? @zyplmn

**Comment by NancyLi1013** [comment]
Please feel free to reopen this issue if it is still a problem @zyplmn.
