### ISSUE TITLE
"Total elapsed time" can not be right

### ISSUE THREAD

**Issue by autoantwort** [microsoft/vcpkg#16850]
**Describe the bug**
When I run `./vcpkg install --triplet=x64-osx`, the `Total elapsed time`is 2.25 us. But the time is definitely longer than a second. When I run with `time`:
```
➜  vcpkg git:(aubio) $ time ./vcpkg install --triplet=x64-osx
/Users/leanderSchulten/git_projekte/Lichtsteuerung
Detecting compiler hash for triplet x64-osx...
All requested packages are currently installed.

Total elapsed time: 2.25 us

./vcpkg install --triplet=x64-osx  1.61s user 0.24s system 95% cpu 1.945 total
``` 

**Environment**
- OS: happens everwhere
- Compiler: is not important

**Expected behavior**
The `Total elapsed time` should display the real total elapsed time, not some "random" very short subtime

**Alternative Solutions**
Rename `Total elapsed time` to `Time to install packages` (I don't know what this time should indicate).  
But a real `Total elapsed time` would be helpful

**Comment by autoantwort** [comment]
For example, in a pipeline environment it would be interesting how long vcpkg waited on the `.vcpkg-root` file lock

**Comment by JackBoosY** [comment]
I personally think this is a bug, but I don't have a clue about this.
