### ISSUE TITLE
[libsoundio] Add Linux support

### ISSUE THREAD

**Issue by joefocusrite** [microsoft/vcpkg#16864]
It would great if the port for libsoundio would support Linux.

Would it be as simple as `-DENABLE_ALSA=${VCPKG_TARGET_IS_LINUX}` in the [portfile](https://github.com/microsoft/vcpkg/blob/3166bcc15b156b57667d9e573fba9775ceef3eb1/ports/libsoundio/portfile.cmake#L17)?

Should it support options to allow different backends (e.g. ALSA, Jack, PulseAudio), or should it default to ALSA?

I'm happy to put in a PR but I would appreciate some guidance first. Thanks!

**Comment by JackBoosY** [comment]
Sadly, we doesn't have a port named `ALSA`.

**Comment by joefocusrite** [comment]
It's included in most Linux distributions and will be automatically found by libsoundio (see [here](https://github.com/andrewrk/libsoundio/blob/a46b0f21c397cd095319f8c9feccf0f1e50e31ba/CMakeLists.txt#L82))

**Comment by ras0219-msft** [comment]
This seems fixed by #16891 -- thanks for the PR!
