### ISSUE TITLE
[libarchive] Should the default features include gpl-v2 lzo?

### ISSUE THREAD

**Issue by Thieum** [microsoft/vcpkg#16868]
the port of libarchive default features contain lzo: 

```
Source: libarchive
...
Default-Features: bzip2, libxml2, lz4, lzma, lzo, openssl, zstd

```
https://github.com/microsoft/vcpkg/blob/master/ports/libarchive/CONTROL

lzo being [GPLv2 ](http://www.oberhumer.com/opensource/lzo/)and libarchive being [BSD](https://raw.githubusercontent.com/libarchive/libarchive/master/COPYING), Shouldn't lzo be an optional feature? 

Otherwise it could come as a surprise when taking a dependency on libarchive without checking the features selected.

**Comment by PhoebeHui** [comment]
I think https://github.com/microsoft/vcpkg/pull/16852/ declare how we set a feature as a default feature, I'm not sure if this would be one of the special conditions.

@ras0219-msft, @vicroms  could you help confirm?

**Comment by vicroms** [comment]
I think it's ok to make `lzo` a non-default feature since the other dependencies already provide a reasonably good collection of compression algorithms. We would have to make sure that ports that depend on `libarchive` are not affected by the removal of these default feature.
