### ISSUE TITLE
Error Installing CMake in Windows64

### ISSUE THREAD

**Issue by madeline-m** [microsoft/vcpkg#16869]
**Describe the bug**

https://github.com/YDLIDAR/YDLidar-SDK/blob/master/doc/howto/how_to_build_and_install.md
We are following the instructions above and kept getting the error:
error while loading cmake, the port directory does not exist, error: failed to load port from C:\src\win64\vcpkg\portd\cmake
note: uploading vcpkg by rerunning bootstrap-vcpkg may resolve this failure

We made a directory called cmake inside of ports and now we are getting this error: 
![Screenshot (118)](https://user-images.githubusercontent.com/80481155/112409747-73eec680-8cf0-11eb-984c-ef3e15690ae5.png)

**Environment**
- OS: Window
- Compiler: revision

**To Reproduce**
1. ./vcpkg install cmake
2. See error
Repro code when

**Expected behavior**
successfully install and move to next step (integrate install, cc build && \ cmake .."-DCMAKE_TOOLCHAIN_FILE.....)

**Failure logs** 

**Additional context**
https://github.com/YDLIDAR/YDLidar-SDK/blob/master/doc/howto/how_to_build_and_install.md
We are trying to follow these instructions to use python to interface with the X2 YDLiDar for a project. We are trying to extract the raw data from the sensor

**Comment by NancyLi1013** [comment]
Hi @madeline-m 

Thanks for posting this issue.

Since cmake is listed in _scripts/test_port/cmake_, which is different from these ports in _ports/_ directory.
So It cannot be installed like this.

You can copy `cmake `folder in https://github.com/microsoft/vcpkg/tree/master/scripts/test_ports to [ports ](https://github.com/microsoft/vcpkg/tree/master/ports)folder, then try to rebuild.

**Comment by NancyLi1013** [comment]
Just to make it clear, the port cmake provided by vcpkg in _test_ports/_ folder is used to test these ports in vcpkg. 
I'm not clear about this document https://github.com/YDLIDAR/YDLidar-SDK/blob/master/doc/howto/how_to_build_and_install.md. But I think this is not the proper way to install cmake.

**Comment by NancyLi1013** [comment]
Closing this issue since it should not a problem in vcpkg.
