### ISSUE TITLE
[opencv3] build failure

### ISSUE THREAD

**Issue by i-Maker** [microsoft/vcpkg#16878]
**Host Environment**
- OS: Windows10
- Compiler: mingw7.3

**To Reproduce**
`vcpkg.exe install opencv3:x64-mingw-static`

**Failure logs** 
PS C:\src\vcpkg> vcpkg.exe install opencv3:x64-mingw-static
Computing installation plan...
The following packages will be built and installed:
    opencv3[core,dnn,flann,jpeg,png,quirc,tiff,webp]:x64-mingw-static -> 3.4.13
Detecting compiler hash for triplet x64-mingw-static...
Could not locate cached archive: C:\Users\12729\AppData\Local\vcpkg\archives\19\1999ff527fc5bb42ea318e916964e8c5cac6c2e9.zip
Starting package 1/1: opencv3:x64-mingw-static
Building package opencv3[core,dnn,flann,jpeg,png,quirc,tiff,webp]:x64-mingw-static...
-- Using community triplet x64-mingw-static. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: C:\src\vcpkg\triplets\community\x64-mingw-static.cmake
-- Using cached C:/src/vcpkg/downloads/opencv-opencv-3.4.13.tar.gz
-- Cleaning sources at C:/src/vcpkg/buildtrees/opencv3/src/3.4.13-1d83403e4f.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/src/vcpkg/downloads/opencv-opencv-3.4.13.tar.gz
-- Applying patch 0001-disable-downloading.patch
-- Applying patch 0002-install-options.patch
-- Applying patch 0003-force-package-requirements.patch
-- Applying patch 0004-fix-eigen.patch
-- Applying patch 0005-fix-vtk9.patch
-- Applying patch 0006-fix-uwp.patch
-- Applying patch 0008-devendor-quirc.patch
-- Using source at C:/src/vcpkg/buildtrees/opencv3/src/3.4.13-1d83403e4f.clean
CMake Deprecation Warning at scripts/cmake/vcpkg_check_features.cmake:182 (message):
  calling `vcpkg_check_features` without the `FEATURES` keyword has been
  deprecated.

      Please add the `FEATURES` keyword to the call.
Call Stack (most recent call first):
  ports/opencv3/portfile.cmake:41 (vcpkg_check_features)
  scripts/ports.cmake:142 (include)

-- Using cached C:/src/vcpkg/downloads/opencv-cache/tiny_dnn/adb1c512e09ca2c7a6faef36f9c53e59-v1.0.0a3.tar.gz
-- Configuring x64-mingw-static
-- Building x64-mingw-static-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:146 (message):
    Command failed: C:/src/vcpkg/downloads/tools/cmake-3.19.2-windows/cmake-3.19.2-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v -j17
    Working Directory: C:/src/vcpkg/buildtrees/opencv3/x64-mingw-static-dbg
    See logs for more information:
      C:\src\vcpkg\buildtrees\opencv3\**install-x64-mingw-static-dbg-out.log**

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:105 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:45 (vcpkg_build_cmake)
  ports/opencv3/portfile.cmake:346 (vcpkg_install_cmake)
  scripts/ports.cmake:142 (include)

Error: Building package opencv3:x64-mingw-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: opencv3:x64-mingw-static
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

Additionally, attach any relevant sections from the log files above.

**install-x64-mingw-static-dbg-out.log** 
[install-x64-mingw-static-dbg-out.log](https://github.com/microsoft/vcpkg/files/6204272/install-x64-mingw-static-dbg-out.log)

**Comment by i-Maker** [comment]
how to build opencv3 debug x64-windows? now I only build release.

**Comment by Cheney-W** [comment]
This issue has not been updated for over 3 months, so if it is still an issue, please reopen the issue.
