### ISSUE TITLE
opencv 3.2.0 installation Errors on ubuntu 16.04 

### ISSUE THREAD

**Issue by Aqdus01** [Microsoft/vcpkg#1688]
Hi 
I am new user of Ubuntu.  I am installing cuda8.0.,  cudnn5.1,  opencv3.2.0, torch, lua and other dependencies on system for deep learning applications. While installing openCV3.2 i got this error. I don't know why is it so I am asking your help to solve that problem. 

 Configuring incomplete, errors occurred!
See also "/home/chaudhary/opencv-3.2.0/build/CMakeFiles/CMakeOutput.log".
See also "/home/chaudhary/opencv-3.2.0/build/CMakeFiles/CMakeError.log".
 I have attached the CMake error log and Output log as well. 

[CmakeErrorlog.txt](https://github.com/Microsoft/vcpkg/files/1248392/CmakeErrorlog.txt)
[CMakeOutputlog.txt](https://github.com/Microsoft/vcpkg/files/1248397/CMakeOutputlog.txt)

Please guide me. Thanks in advance

**Comment by Mixaill** [comment]
Looks like OpenCV bugtracker is the most suitable place for this bugreport 😉 

https://github.com/opencv/opencv/issues

**Comment by Aqdus01** [comment]
Sure I check there as well.  But if you have seen the errors can you guide me ?

**Comment by Mixaill** [comment]
It's a HUGE offtopic for vcpkg but try to set up `-DWITH_V4L=OFF` flag for cmake

**Comment by Aqdus01** [comment]
i have done with it  (-DWITH_V4L=OFF)
 but still i am having errors like ..
Performing Test HAVE_CXX_WNO_UNNAMED_TYPE_TEMPLATE_ARGS - Failed
-- Performing Test HAVE_C_WNO_UNNAMED_TYPE_TEMPLATE_ARGS
-- Performing Test HAVE_C_WNO_UNNAMED_TYPE_TEMPLATE_ARGS - Failed
Performing Test HAVE_CXX_WSTRICT_PROTOTYPES - Failed

-- Checking for module 'gtk+-3.0'
--   Found gtk+-3.0, version 3.18.9
-- Checking for module 'gthread-2.0'
--   Found gthread-2.0, version 2.48.2
-- Checking for module 'gstreamer-base-1.0'
--   No package 'gstreamer-base-1.0' found
-- Checking for module 'gstreamer-video-1.0'
--   No package 'gstreamer-video-1.0' found
-- Checking for module 'gstreamer-app-1.0'
--   No package 'gstreamer-app-1.0' found
-- Checking for module 'gstreamer-riff-1.0'
--   No package 'gstreamer-riff-1.0' found
-- Checking for module 'gstreamer-pbutils-1.0'
--   No package 'gstreamer-pbutils-1.0' found
-- Checking for module 'gstreamer-base-0.10'
--   Found gstreamer-base-0.10, version 0.10.36
-- Checking for module 'gstreamer-video-0.10'
--   Found gstreamer-video-0.10, version 0.10.36
-- Checking for module 'gstreamer-app-0.10'
--   Found gstreamer-app-0.10, version 0.10.36
-- Checking for module 'gstreamer-riff-0.10'
--   Found gstreamer-riff-0.10, version 0.10.36
-- Checking for module 'gstreamer-pbutils-0.10'
--   Found gstreamer-pbutils-0.10, version 0.10.36
-- Checking for module 'libdc1394-2'

**Comment by Aqdus01** [comment]
Thanks for prompt answers, I am also looking at said forum but still could not find solution

**Comment by ras0219-msft** [comment]
Closing as off topic, please seek further help in the opencv mailing list and issue tracker!

**Comment by Mixaill** [comment]
There is no errors in this log. It's only misssing optional dependencies and compiler features.

**Comment by Aqdus01** [comment]
https://github.com/opencv/opencv/issues/8372
I have pasted here full error report. How can i make it workable :(
