### ISSUE TITLE
msbuild AppLocalFromInstalled target fails: "-ExecutionPolicy" invalid argument on pwsh.exe

### ISSUE THREAD

**Issue by zvilius** [microsoft/vcpkg#16888]
**Describe the bug**
VS2019 (msbuild) project that uses vcpkg in manifest mode gets the following build error:
```
1>Target "AppLocalFromInstalled" in file "C:\xxx\projects\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets" from project "C:\xxx\projects\icp\xxx\xxx.vcxproj" (target "RegisterOutput" depends on it):
  Task "Message"
    [vcpkg] Starting VcpkgApplocalDeps
  Done executing task "Message".
  Task "Exec"
    pwsh.exe -ExecutionPolicy Bypass -noprofile -File "C:\xxx\projects\vcpkg\scripts\buildsystems\msbuild\applocal.ps1" "C:\xxx\projects\icp\_output\xxx\x64_Debug\xxx.exe" "C:\xxx\projects\icp\vcpkg_installed\x64-windows\debug\bin" "x64_Debug\xxx.tlog\xxx.write.1u.tlog" "x64_Debug\vcpkg.applocal.log"
    -ExecutionPolicy : The term '-ExecutionPolicy' is not recognized as the name of a cmdlet, function, script file, or operable program.
```
The project builds and links, but fails to run when launched from VS because it does not find fmt.dll / fmtd.dll from "fmt" provided by vcpkg.

**Environment**
- OS: Windows 10 Pro
- IDE: VS 2019 16.9.2
- vcpkg version 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

**To Reproduce**
1. ./vcpkg install fmt -- powershell-core was installed during this process, among other things
2. ./vcpkg integrate install
3. See attached vcpkg.json:
[vcpkg.json.txt](https://github.com/microsoft/vcpkg/files/6207551/vcpkg.json.txt)
4. Set "Use Vcpkg Manifest" to "Yes" in VS project settings.
5. Build and get the above error.
6. Try to run and get dialog reporting missing dll.

**Expected behavior**
Build without error, and run correctly.

**Failure logs** 
See above.

**Additional context**
I get the same error when running pwsh by hand with the ExecutionPolicy flag:
```
~\bin> pwsh -executionpolicy bypass -noprofile -file ./hello.ps1
-executionpolicy : The term '-executionpolicy' is not recognized as the name of a cmdlet, function, script file, or operable program.
...
~\bin> c:\windows\system32\where.exe pwsh
C:\Users\xxx\.dotnet\tools\pwsh.exe
```

**Comment by PhoebeHui** [comment]
Confirmed, I can repro this issue locally.

**Comment by zvilius** [comment]
I should add that I saw this issue using the "vcpkg integrate project" usage pattern as well.
I completely reinstalled vcpkg and switched to using "manifests" in an attempt to resolve it.
So I don't think this issue is specific to "manifests."

Thank you.
Mark Z.

**Comment by zvilius** [comment]
I recently installed PowerShell 7.1.3 and I no longer have this problem.
Previously I was using PowerShell 6.2.3, which apparently had a problem with the -ExecutionPolicy flag.

**Comment by PhoebeHui** [comment]
This should be fixed now.
