### ISSUE TITLE
[libodb-mysql] provides cmake targets should be updated

### ISSUE THREAD

**Issue by zkcrescent** [microsoft/vcpkg#16896]
****

*the provided targets not work*

when I installed libodb-mysql,  shows provided targets: 

```
    find_package(odb CONFIG REQUIRED)
    target_link_libraries(main PRIVATE odb::libodb-mysql)
```

but it doesn't work when i use in my `CmakeLists`

```
[build] CMake Error at /vcpkg/scripts/buildsystems/vcpkg.cmake:418 (_add_executable):
[build]   Target "main" links to target "odb::libodb-mysql" but the target
[build]   was not found.
```

I cheak vpckg odb share path `/vcpkg/installed/x64-osx/share/odb` and find cmake file `odb_mysqlConfig.cmake`, then i change my `CmakeLists` to 

``` 
find_package(odb CONFIG REQUIRED COMPONENTS libodb mysql)

target_link_libraries(main PRIVATE  odb::libodb odb::libodb-mysql)
```

it shows 
```
No rule to make target `vcpkg/installed/x64-osx/lib/libmysql.lib'
```
need help. thx.

**Additional context**
host ：macos catalina 10.15.1 (19B88)
cmake version 3.19.6
vcpkg version 2020.06.15-unknownhash

**Comment by JackBoosY** [comment]
Thanks for point out this!
