### ISSUE TITLE
[fontconfig] build failure

### ISSUE THREAD

**Issue by stuartZhang** [microsoft/vcpkg#16895]
**Host Environment**
- OS: Windows 10
- Compiler: Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24210 for x86

**To Reproduce**
`./vcpkg install gtk`

**Failure logs** 

Starting package 1/9: fontconfig:x86-windows
Building package fontconfig[core]:x86-windows...
-- Downloading https://gitlab.freedesktop.org/fontconfig/fontconfig/-/archive/844d8709a1f3ecab45015b24b72dd775c13b2421/fontconfig-844d8709a1f3ecab45015b24b72dd775c13b2421.tar.gz -> fontconfig-fontconfig-844d8709a1f3ecab45015b24b72dd775c13b2421.tar.gz...       
-- Extracting source H:/github_projects/vcpkg/downloads/fontconfig-fontconfig-844d8709a1f3ecab45015b24b72dd775c13b2421.tar.gz
-- Applying patch remove_tests.patch
-- Applying patch build.patch
-- Applying patch build2.patch
-- Applying patch disable-install-data.patch
-- Applying patch fix_def_dll_name.patch
-- Using source at H:/github_projects/vcpkg/buildtrees/fontconfig/src/75c13b2421-828c91b8d5.clean
-- Configuring x86-windows
-- Using msys root at H:/github_projects/vcpkg/downloads/tools/msys2/b24ec64736bbaa92
-- Using msys root at H:/github_projects/vcpkg/downloads/tools/msys2/50864d9fae363d6e
-- Generating configure for x86-windows
-- Finished generating configure for x86-windows
-- Configuring x86-windows-dbg
-- Configuring x86-windows-rel
-- Using msys root at H:/github_projects/vcpkg/downloads/tools/msys2/969c0913b9df89e1
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:146 (message):
    Command failed: H:/github_projects/vcpkg/downloads/tools/msys2/b24ec64736bbaa92/usr/bin/make.exe -j 5 --trace -f Makefile all
    Working Directory: H:/github_projects/vcpkg/buildtrees/fontconfig/x86-windows-dbg
    See logs for more information:
      H:\github_projects\vcpkg\buildtrees\fontconfig\build-x86-windows-dbg-out.log
      H:\github_projects\vcpkg\buildtrees\fontconfig\build-x86-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_make.cmake:195 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_make.cmake:26 (vcpkg_build_make)
  ports/fontconfig/portfile.cmake:46 (vcpkg_install_make)
  scripts/ports.cmake:142 (include)

Error: Building package fontconfig:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: fontconfig:x86-windows
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

Additionally, attach any relevant sections from the log files above.

**Additional context**

[build-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/6209171/build-x86-windows-dbg-out.log)

[build-x86-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/6209173/build-x86-windows-dbg-err.log)

**Comment by NancyLi1013** [comment]
Hi @stuartZhang

Thanks for posting this issue.

The failures from above build log:
```
H:/github_projects/vcpkg/buildtrees/fontconfig/x86-windows-dbg/fc-case/fc-case.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
make[3]: *** [Makefile:669: fccase.h] Error 1
make[2]: *** [Makefile:414: all] Error 2
make[1]: *** [Makefile:601: all-recursive] Error 1
make: *** [Makefile:485: all] Error 2
```
But I cannot reproduce this on my machine.

**Comment by stuartZhang** [comment]
@NancyLi1013 Is your dev box Linux/Unix? My dev box is Windows 10. I suspect the error originates from Windows-dedicated [SafeDllSearchMode](https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order). Because the DLL files under the (C:/Windows/System32) directory are always loaded in higher priority, the unexpected DLL files are erroneously linked which have the same file name as what we want. For example, (C:/Windows/System32/zlib1.dll) always shadows (D:/msys2/mingw64/bin/zlib1.dll), due to their same file name.

**Comment by NancyLi1013** [comment]
My dev box is Windows 10. 

`error while loading shared libraries: ?: cannot open shared object file: No such file or directory`

Do you know which shared library cannot be found here?  If there is the same file name as what we want, can you try to disable the feature `SafeDllSearchMode`? Then rebuild this?

**Comment by NancyLi1013** [comment]
Any updates here? @stuartZhang
