### ISSUE TITLE
[llvm:x64-windows] build failure

### ISSUE THREAD

**Issue by haikunzhang95** [microsoft/vcpkg#16894]
**Host Environment**
- OS: windows 10 x64
- Compiler: revision

**To Reproduce**
`.\vcpkg install llvm[target-all,clang-tools-extra]:x64-windows `

**Failure logs** 
Error: Building package llvm:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: llvm:x64-windows
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

**Additional context**
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:146 (message):
    Command failed: D:/vcpkg/downloads/tools/cmake-3.19.2-windows/cmake-3.19.2-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v -j13
    Working Directory: D:/vcpkg/buildtrees/llvm/x64-windows-dbg
    See logs for more information:
      D:\vcpkg\buildtrees\llvm\install-x64-windows-dbg-out.log

**Comment by haikunzhang95** [comment]
My platform is: Windows 10 x64. Follow the "Building Halide with CMake", I install ''libpng:x64-windows'', '' libjpeg-turbo:x64-windows'', and '' llvm[target-all,clang-tools-extra]:x64-windows'' respectively. I successfully installed the first two, but there was a problem installing the last package. When the Windows PowerShell display“--Building x64-windows-dbg”, the cursor keeps blinking, and notning happened. I waited for several hours and did not see the message of successful installation. So, what should I do? What is the possible reason？

**Comment by PhoebeHui** [comment]
@haikunzhang95, could you please try if https://github.com/microsoft/vcpkg/pull/16232 works for you?

**Comment by yurybura** [comment]
@haikunzhang95 @PhoebeHui 
I've tested your install command with #16232. The build has succeeded, but build directory takes ~157 GB on disk.
In default build not all targets are enabled to reduce used disk space.

**Comment by haikunzhang95** [comment]
@yurybura Thank you for your reply. Using such installation commands (**.\vcpkg install llvm[target-all,clang-tools-extra]:x64-windows**) takes too much time and takes up more disk space. I think the reason for the above error is that my network environment is too bad, and I've solved this problem now. Thank you again!
