### ISSUE TITLE
[boost-json] Fails to build static library

### ISSUE THREAD

**Issue by LeonineKing1199** [microsoft/vcpkg#16907]
Boost.JSON by default is a compiled library yet boost-json treats it like a header-only target and does not create a `libboost_json.a`.

While `b2` should be capable of producing the library, Boost.JSON is built by a single TU including a `src.hpp` file which end-users then compile and link against.

**Comment by vynilas** [comment]
Hi,
I've just compiled boost_1_77, but still, libboost_json is not generated.
Are you sure that the fix has been propagated to boost 1_77 ?
cheers

**Comment by yurybura** [comment]
@vynilas Have you tried this PR #19556?

**Comment by vynilas** [comment]
Sounds like I post my comment in the wrong place : I've been compiling on Ubuntu, not Windows.
Hence I guess that the PR#19556 does not apply to my issue ?

**Comment by yurybura** [comment]
Actual master contains version 1.76.0. Update to 1.77.0 hasn't been ready yet.

**Comment by vynilas** [comment]
Thanks a lot Yury.
