### ISSUE TITLE
Problem with MSYS2

### ISSUE THREAD

**Issue by lazyhamster** [Microsoft/vcpkg#1691]
I'm trying to install ffmpeg package but it keeps failing.

> vcpkg install ffmpeg

Judging by the log files problem is with MSYS2 updating, GPG doesn't check signatures properly.

> Package: ffmpeg:x86-windows
> Vcpkg version: 0.0.84-bed70f54bc2dd7181a54bbbb94d2fe3a1a0b35cc

Log files are attached (changed extension cause GitHub refuses to accept .log extension).
[build-x86-windows-rel-err.log.txt](https://github.com/Microsoft/vcpkg/files/1248747/build-x86-windows-rel-err.log.txt)
[build-x86-windows-rel-out.log.txt](https://github.com/Microsoft/vcpkg/files/1248748/build-x86-windows-rel-out.log.txt)

**Comment by NancyLi1013** [comment]
Please open a new issue if this is still a problem for you.
