### ISSUE TITLE
[wasm32-emscripten]  Failed to fetch compiler version information / VCPKG_ENV_PASSTHROUGH  for EMSDK PATH may not be enough

### ISSUE THREAD

**Issue by Markus87** [microsoft/vcpkg#16917]
****

**Is your feature request related to a problem? Please describe.**
For emsdk 1.39.8 and latest(2.0.16) the compiler detection in the toolchain file of emsdk fails. (tested with `vcpkg install zlib:wasm32-emscripten`)
```
  Failed to fetch compiler version information with command  "'<emsdk_path>/upstream/emscripten/emcc.bat' -v"! 
  Process returned with error code 1.  
  Error:shared:ERROR: BINARYEN_ROOT is set to empty value in C:\Users\Alex/.emscripten
```

**Proposed solution**
emsdk_env sets the following environment variables:
```
PATH = ...
EMSDK = <emdsk_path>
EM_CONFIG = <emdsk_path>\.emscripten
EMSDK_NODE = <emdsk_path>\node\14.15.5_64bit\bin\node.exe
JAVA_HOME = <emdsk_path>\java\8.152_64bit
EM_CACHE = <emdsk_path>/upstream/emscripten\cache
```
I think those should all be added in the `wasm32-emscripten.cmake`.
```cmake
set(VCPKG_ENV_PASSTHROUGH EMSDK PATH  EM_CONFIG EM_CACHE EMSDK_NODE EMSDK_PYTHON JAVA_HOME)
```

****

If nobody sees any error in this I can also do a pulls request for this.
If I am doing anything wrong please tell me what I am missing. 🤔

**Comment by matus-z** [comment]
Thanks, @Markus87 👍 This solution works for me.

**Comment by JackBoosY** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.

**Comment by JackBoosY** [comment]
Please feel free to make a PR to fix that.
