### ISSUE TITLE
Error: Building package boost-exception:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by ZiniuLu** [microsoft/vcpkg#16929]
**Host Environment**
- OS: Windows 10
- Compiler: VS 2019 Community 16.9.2
- vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

**To Reproduce**

- `./vcpkg install yasm-tool:x86-windows`     -- succeed
- `./vcpkg install cgal:x64-windows`    -- failed

**Prompt Text** 
.
.
.
Building package boost-modular-build-helper[core]:x64-windows... done
Installing package boost-modular-build-helper[core]:x64-windows...
Installing package boost-modular-build-helper[core]:x64-windows... done
Elapsed time for package boost-modular-build-helper:x64-windows: 186.6 ms
Starting package 37/105: boost-exception:x64-windows
Building package boost-exception[core]:x64-windows...
-- Downloading https://github.com/boostorg/exception/archive/boost-1.75.0.tar.gz -> boostorg-exception-boost-1.75.0.tar.gz...
-- Extracting source E:/Code/vcpkg/downloads/boostorg-exception-boost-1.75.0.tar.gz
-- Using source at E:/Code/vcpkg/buildtrees/boost-exception/src/ost-1.75.0-89fb56d2c9.clean
-- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
    Command failed: E:/Code/vcpkg/installed/x64-windows/tools/boost-build/b2.exe --stagedir=E:/Code/vcpkg/buildtrees/boost-exception/x64-windows-rel/stage --build-dir=E:/Code/vcpkg/buildtrees/boost-exception/x64-windows-rel --user-config=E:/Code/vcpkg/buildtrees/boost-exception/x64-windows-rel/user-config.jam -j4 --debug-configuration --debug-building --debug-generators --disable-icu --ignore-site-config --hash -q -sZLIB_INCLUDE=E:/Code/vcpkg/installed/x64-windows/include -sBZIP2_INCLUDE=E:/Code/vcpkg/installed/x64-windows/include -sLZMA_INCLUDE=E:/Code/vcpkg/installed/x64-windows/include -sZSTD_INCLUDE=E:/Code/vcpkg/installed/x64-windows/include threading=multi threadapi=win32 runtime-link=shared link=shared address-model=64 architecture=x86 -sZLIB_BINARY=zlib -sZLIB_LIBPATH=E:/Code/vcpkg/installed/x64-windows/lib -sBZIP2_BINARY=bz2 -sBZIP2_LIBPATH=E:/Code/vcpkg/installed/x64-windows/lib -sLZMA_BINARY=lzma -sLZMA_LIBPATH=E:/Code/vcpkg/installed/x64-windows/lib -sZSTD_BINARY=zstd -sZSTD_LIBPATH=E:/Code/vcpkg/installed/x64-windows/lib variant=release debug-symbols=on
    Working Directory: E:/Code/vcpkg/buildtrees/boost-exception/src/ost-1.75.0-89fb56d2c9.clean/build
    Error code: 1
    See logs for more information:
      E:\Code\vcpkg\buildtrees\boost-exception\build-x64-windows-rel-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/boost-build/boost-modular-build.cmake:332 (vcpkg_execute_required_process)
  ports/boost-exception/portfile.cmake:15 (boost_modular_build)
  scripts/ports.cmake:142 (include)

**Error: Building package boost-exception:x64-windows failed with: BUILD_FAILED**
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-exception:x64-windows
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

Additionally, attach any relevant sections from the log files above.

**Additional context**

1. tried `./vcpkg update` and `git pull`  --> already up to date
2. tried the way in #6330 : installed MSVC 140, 141, 142 in VS Installer and modified the env variable `VS150COMNTOOLS` --> same error
3. tried with cmd, powershell, developer command prompt for vs2019 --> same error

**Comment by ZiniuLu** [comment]
**Log Info**

from "E:\Code\vcpkg\buildtrees\boost-exception\build-x64-windows-rel-out.log"
.
.
.
 SUCCESS:  [ <relevant>address-model <relevant>architecture <relevant>archiveflags <relevant>debug-symbols <relevant>runtime-debugging <relevant>toolset <relevant>toolset-msvc:version <relevant>user-interface <relevant>windows-api ] { msvc%msvc.archive-libboost_exception-vc142-mt-x64-1_75.lib.STATIC_LIB { msvc%msvc.compile.c++-clone_current_exception_non_intrusive.obj.OBJ { clone_current_exception_non_intrusive.cpp.CPP } } }

      returned [ <relevant>address-model <relevant>architecture <relevant>archiveflags <relevant>asynch-exceptions <relevant>cflags <relevant>cxxflags <relevant>cxxstd <relevant>debug-store <relevant>debug-symbols <relevant>define <relevant>exception-handling <relevant>extern-c-nothrow <relevant>force-include <relevant>include <relevant>inlining <relevant>instruction-set <relevant>link <relevant>lto <relevant>mc-input-encoding <relevant>mc-output-encoding <relevant>mc-set-customer-bit <relevant>optimization <relevant>pch <relevant>pch-file <relevant>pch-header <relevant>pch-source <relevant>rtti <relevant>runtime-debugging <relevant>runtime-link <relevant>threading <relevant>toolset <relevant>toolset-msvc:version <relevant>undef <relevant>user-interface <relevant>warnings <relevant>warnings-as-errors <relevant>windows-api ] { msvc%msvc.archive-libboost_exception-vc142-mt-x64-1_75.lib.STATIC_LIB { msvc%msvc.compile.c++-clone_current_exception_non_intrusive.obj.OBJ { clone_current_exception_non_intrusive.cpp.CPP } } }
           generator msvc.archive  spawned 
           { msvc%msvc.archive-libboost_exception-vc142-mt-x64-1_75.lib.STATIC_LIB { msvc%msvc.compile.c++-clone_current_exception_non_intrusive.obj.OBJ { clone_current_exception_non_intrusive.cpp.CPP } } }
           with usage requirements: [ <relevant>address-model <relevant>architecture <relevant>archiveflags <relevant>asynch-exceptions <relevant>cflags <relevant>cxxflags <relevant>cxxstd <relevant>debug-store <relevant>debug-symbols <relevant>define <relevant>exception-handling <relevant>extern-c-nothrow <relevant>force-include <relevant>include <relevant>inlining <relevant>instruction-set <relevant>link <relevant>lto <relevant>mc-input-encoding <relevant>mc-output-encoding <relevant>mc-set-customer-bit <relevant>optimization <relevant>pch <relevant>pch-file <relevant>pch-header <relevant>pch-source <relevant>rtti <relevant>runtime-debugging <relevant>runtime-link <relevant>threading <relevant>toolset <relevant>toolset-msvc:version <relevant>undef <relevant>user-interface <relevant>warnings <relevant>warnings-as-errors <relevant>windows-api ]
     returned [ <relevant>address-model <relevant>architecture <relevant>archiveflags <relevant>asynch-exceptions <relevant>cflags <relevant>cxxflags <relevant>cxxstd <relevant>debug-store <relevant>debug-symbols <relevant>define <relevant>exception-handling <relevant>extern-c-nothrow <relevant>force-include <relevant>include <relevant>inlining <relevant>instruction-set <relevant>link <relevant>lto <relevant>mc-input-encoding <relevant>mc-output-encoding <relevant>mc-set-customer-bit <relevant>optimization <relevant>pch <relevant>pch-file <relevant>pch-header <relevant>pch-source <relevant>rtti <relevant>runtime-debugging <relevant>runtime-link <relevant>threading <relevant>toolset <relevant>toolset-msvc:version <relevant>undef <relevant>user-interface <relevant>warnings <relevant>warnings-as-errors <relevant>windows-api ] { msvc%msvc.archive-libboost_exception-vc142-mt-x64-1_75.lib.STATIC_LIB { msvc%msvc.compile.c++-clone_current_exception_non_intrusive.obj.OBJ { clone_current_exception_non_intrusive.cpp.CPP } } }
       generator builtin.lib-generator  spawned 
       { msvc%msvc.archive-libboost_exception-vc142-mt-x64-1_75.lib.STATIC_LIB { msvc%msvc.compile.c++-clone_current_exception_non_intrusive.obj.OBJ { clone_current_exception_non_intrusive.cpp.CPP } } }
       with usage requirements: [ <relevant>address-model <relevant>architecture <relevant>archiveflags <relevant>asynch-exceptions <relevant>cflags <relevant>cxxflags <relevant>cxxstd <relevant>debug-store <relevant>debug-symbols <relevant>define <relevant>exception-handling <relevant>extern-c-nothrow <relevant>force-include <relevant>include <relevant>inlining <relevant>instruction-set <relevant>link <relevant>lto <relevant>mc-input-encoding <relevant>mc-output-encoding <relevant>mc-set-customer-bit <relevant>optimization <relevant>pch <relevant>pch-file <relevant>pch-header <relevant>pch-source <relevant>rtti <relevant>runtime-debugging <relevant>runtime-link <relevant>threading <relevant>toolset <relevant>toolset-msvc:version <relevant>undef <relevant>user-interface <relevant>warnings <relevant>warnings-as-errors <relevant>windows-api ]
             Usage requirements from boost_exception:  <relevant>address-model <relevant>architecture <relevant>asynch-exceptions <relevant>cxxstd <relevant>cxxstd-dialect <relevant>debug-store <relevant>debug-symbols <relevant>deduced-address-model <relevant>deduced-architecture <relevant>exception-handling <relevant>extern-c-nothrow <relevant>inlining <relevant>instruction-set <relevant>link <relevant>lto <relevant>lto-mode <relevant>optimization <relevant>pch <relevant>rtti <relevant>runtime-debugging <relevant>runtime-link <relevant>segmented-stacks <relevant>threading <relevant>toolset <relevant>toolset-msvc:vendor <relevant>toolset-msvc:version <relevant>variant <relevant>warnings <relevant>warnings-as-errors <relevant>windows-api

         Usage requirements for stage:  <relevant>address-model <relevant>architecture <relevant>asynch-exceptions <relevant>cxxstd <relevant>cxxstd-dialect <relevant>debug-store <relevant>debug-symbols <relevant>deduced-address-model <relevant>deduced-architecture <relevant>exception-handling <relevant>extern-c-nothrow <relevant>inlining <relevant>instruction-set <relevant>link <relevant>lto <relevant>lto-mode <relevant>optimization <relevant>pch <relevant>rtti <relevant>runtime-debugging <relevant>runtime-link <relevant>segmented-stacks <relevant>threading <relevant>toolset <relevant>toolset-msvc:vendor <relevant>toolset-msvc:version <relevant>variant <relevant>warnings <relevant>warnings-as-errors <relevant>windows-api
         Build properties:  <address-model>64 <architecture>x86 <asynch-exceptions>off <coverage>off <debug-store>object <debug-symbols>on <define>BOOST_ALL_NO_LIB=1 <define>NDEBUG <embed-manifest-via>linker <embed-manifest>on <exception-handling>on <extern-c-nothrow>off <hardcode-dll-paths>false <host-os>windows <include>../include&&/E:/Code/vcpkg/installed/x64-windows/include <inlining>full <install-dependencies>off <link>static <location>/E:/Code/vcpkg/buildtrees/boost-exception/x64-windows-rel/stage/lib <midl-robust>yes <midl-stubless-proxy>yes <optimization>speed <os>NT <pch>on <profiling>off <relevant>address-model <relevant>architecture <relevant>asynch-exceptions <relevant>cxxstd <relevant>cxxstd-dialect <relevant>debug-store <relevant>debug-symbols <relevant>deduced-address-model <relevant>deduced-architecture <relevant>exception-handling <relevant>extern-c-nothrow <relevant>inlining <relevant>instruction-set <relevant>link <relevant>lto <relevant>lto-mode <relevant>optimization <relevant>pch <relevant>rtti <relevant>runtime-debugging <relevant>runtime-link <relevant>segmented-stacks <relevant>threading <relevant>threading:<relevant>runtime-link <relevant>threading:<relevant>toolset <relevant>toolset <relevant>toolset-msvc:vendor <relevant>toolset-msvc:version <relevant>variant <relevant>warnings <relevant>warnings-as-errors <relevant>windows-api <rtti>on <runtime-debugging>off <runtime-link>shared <stdlib>native <strip>off <suppress-import-lib>false <symlink-location>project-relative <tag>@Jamfile<E:\Code\vcpkg\buildtrees\boost-exception\src\ost-1.75.0-89fb56d2c9.clean>%Jamfile<E:\Code\vcpkg\buildtrees\boost-exception\src\ost-1.75.0-89fb56d2c9.clean>.tag <target-os>windows <threadapi>win32 <threading>multi <toolset-msvc:version>14.2 <toolset>msvc <translate-path>@Jamfile<E:\Code\vcpkg\buildtrees\boost-exception\src\ost-1.75.0-89fb56d2c9.clean\build>%Jamfile<E:\Code\vcpkg\buildtrees\boost-exception\src\ost-1.75.0-89fb56d2c9.clean\build>.stage-translate-path <user-interface>console <variant>release <vectorize>off <warnings-as-errors>off <warnings>on <windows-api>desktop
         Usage requirements from stage:  <relevant>address-model <relevant>architecture <relevant>asynch-exceptions <relevant>cxxstd <relevant>cxxstd-dialect <relevant>debug-store <relevant>debug-symbols <relevant>deduced-address-model <relevant>deduced-architecture <relevant>exception-handling <relevant>extern-c-nothrow <relevant>inlining <relevant>instruction-set <relevant>link <relevant>lto <relevant>lto-mode <relevant>optimization <relevant>pch <relevant>rtti <relevant>runtime-debugging <relevant>runtime-link <relevant>segmented-stacks <relevant>threading <relevant>toolset <relevant>toolset-msvc:vendor <relevant>toolset-msvc:version <relevant>variant <relevant>warnings <relevant>warnings-as-errors <relevant>windows-api
...patience...
...found 261 targets...
...updating 12 targets...
msvc.write-setup-script E:\Code\vcpkg\buildtrees\boost-exception\x64-windows-rel\boost\standalone\msvc\999faa3b40e90a2a5abbbc32b31cdb11\msvc-setup.bat
The system cannot find the path specified.

    type "C:\Users\张紫薇\AppData\Local\Temp\jam3e407064.000" > "E:\Code\vcpkg\buildtrees\boost-exception\x64-windows-rel\boost\standalone\msvc\999faa3b40e90a2a5abbbc32b31cdb11\msvc-setup.bat"

...failed msvc.write-setup-script E:\Code\vcpkg\buildtrees\boost-exception\x64-windows-rel\boost\standalone\msvc\999faa3b40e90a2a5abbbc32b31cdb11\msvc-setup.bat...
...removing E:\Code\vcpkg\buildtrees\boost-exception\x64-windows-rel\boost\standalone\msvc\999faa3b40e90a2a5abbbc32b31cdb11\msvc-setup.bat
...skipped <pE:\Code\vcpkg\buildtrees\boost-exception\x64-windows-rel\boost\build\6d04714fc9fd8b46418a491bbf63a921>clone_current_exception_non_intrusive.obj for lack of <pE:\Code\vcpkg\buildtrees\boost-exception\x64-windows-rel\boost\standalone\msvc\999faa3b40e90a2a5abbbc32b31cdb11>msvc-setup.nup...
...failed updating 1 target...
...skipped 1 target...
...updated 9 targets...

**Comment by NancyLi1013** [comment]
Hi @ZiniuLu 

Thanks for posting this issue.
Could you please help attach the log _E:\Code\vcpkg\buildtrees\boost-exception\build-x64-windows-rel-out.log_?

Please also help confirm if you have installed English package in Visual Studio 2019 Installer.

**Comment by ZiniuLu** [comment]
[build-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/6227684/build-x64-windows-rel-out.log)

Hi @NancyLi1013 

Thanks for your help!

Yep. I have installed the English package in VS 2019.

**Comment by NancyLi1013** [comment]
```
The system cannot find the path specified.

    type "C:\Users\ÕÅ×ÏÞ±\AppData\Local\Temp\jam2cf0f12f.000" > "E:\Code\vcpkg\buildtrees\boost-exception\x64-windows-rel\boost\standalone\msvc\999faa3b40e90a2a5abbbc32b31cdb11\msvc-setup.bat"

...failed msvc.write-setup-script 
```
Seems that the path is not correct, since it contains some special characters.

**Comment by ZiniuLu** [comment]
Hello @NancyLi1013 

Exactly this problem! These "special characters" as actually the username in chinese.

I've just created a new user account (which is in English) in the system and finally successfully installed the boost library!

Thanks again for your help!
