### ISSUE TITLE
Unable to access library after `integrate install` and/or `integrate project` in Visual Studio / Win10

### ISSUE THREAD

**Issue by zipzit** [microsoft/vcpkg#16924]
**Describe the bug**
Visual Studio reports "cannot open source file "zmq.hpp"

**Environment**
- OS: 
- Edition	Windows 10 Home, Version 20H2, Installed on ‎6/‎11/‎2020,  OS build 19042.870
- Experience Windows Feature Experience Pack 120.2212.551.0
- Processor	Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz   3.40 GHz  Installed RAM	32.0 GB
- System type	64-bit operating system, x64-based processor
- Visual Studio Community 2019, Version 16.9.1
- Visual C++ 2019 -- 00435-60000-00000-AA449

VCPKG installed via: 
$ `git clone https://github.com/microsoft/vcpkg`
   ` .\vcpkg\bootstrap-vcpkg.bat`
   `.\vcpkg\vcpkg install cppzmq`
    `.\vcpkg\vcpkg integrate install`

Note: I installed VCPKG on my M drive.  VCPKG is installed no where else on this computer (typically I use virtual machines.. not this time...)  Operating system located on C drive.. 

Install reports success:
   ```
The package cppzmq:x86-windows provides CMake targets:
        find_package(cppzmq CONFIG REQUIRED)
        target_link_libraries(main PRIVATE cppzmq cppzmq-static)
```
Integrate Install also successful:
```
    PS M:\> .\vcpkg\vcpkg integrate install
    Applied user-wide integration for this vcpkg root.
      All MSBuild C++ projects can now #include any installed libraries.
      Linking will be handled automatically.   
      Installing new libraries will make them instantly available.
```
I can see that both CPPZMQ and its base ZEROMQ are successfully installed.  I can search VCPKG folder and see the .h files my program can't find.

PS M:\vcpkg> `./vcpkg list`
`cppzmq:x86-windows                                 4.7.1#1          lightweight messaging kernel, C++ bindings`
`zeromq:x86-windows                                 2019-09-20#2     The ZeroMQ lightweight messaging kernel is a lib...`

After an initial search I discovered [this posting,](https://github.com/microsoft/vcpkg/issues/9432)  I attempted to use `$ ./vcpkg integrate project`  From what I can see that was successful, too.  

```
    PS M:\vcpkg> `./vcpkg integrate project`
    `Created nupkg: M:\vcpkg\scripts\buildsystems\vcpkg.M.vcpkg.1.0.0.nupkg`

    `With a project open, go to Tools->NuGet Package Manager->Package Manager Console and paste:`
        `Install-Package vcpkg.M.vcpkg -Source "M:\vcpkg\scripts\buildsystems"`

    `Package Manager Console Host Version 5.9.0.7134`

    PM> `Install-Package vcpkg.M.vcpkg -Source "M:\vcpkg\scripts\buildsystems"`
    Attempting to gather dependency information for package 'vcpkg.M.vcpkg.1.0.0' with respect to project
    'Games\FactoryEnvCollect', targeting 'native,Version=v0.0'
    Gathering dependency information took 310 ms
    Attempting to resolve dependencies for package 'vcpkg.M.vcpkg.1.0.0' with DependencyBehavior 'Lowest'
    Resolving dependency information took 0 ms
    Resolving actions to install package 'vcpkg.M.vcpkg.1.0.0'
    Resolved actions to install package 'vcpkg.M.vcpkg.1.0.0'
    Retrieving package 'vcpkg.M.vcpkg 1.0.0' from 'M:\vcpkg\scripts\buildsystems'.
    Adding package 'vcpkg.M.vcpkg.1.0.0' to folder 'M:\FactoryEnvCollect\packages'
    Added package 'vcpkg.M.vcpkg.1.0.0' to folder 'M:\FactoryEnvCollect\packages'
    Added package 'vcpkg.M.vcpkg.1.0.0' to 'packages.config'
    Successfully installed 'vcpkg.M.vcpkg 1.0.0' to FactoryEnvCollect
    Executing nuget actions took 1.83 sec
    Time Elapsed: 00:00:02.4203787
    PM>
```

**To Reproduce**
See above.  Everything looks right.  I can see the packages.config file within my project.  

```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="vcpkg.M.vcpkg" version="1.0.0" targetFramework="native" />
</packages>
```

**Failure logs** 
Everything looks good, but it just doesn't work.  I get a bunch of errors displayed starting with "cannot open source file zmq.hpp".  Compiler shows "fatal error C1083: Cannot open include file 'zmaq.hpp': No such file or directory.  Sigh.  

Is there a better way to point my project at the packages within vcpkg?  (Note, I've never touched NuGet package manager before.. I need to study up a bit on that...)

**Comment by zipzit** [comment]
oops.  I can't believe the default install on a 64 bit windows box installed the 32 bit windows library.  Big ouch.  It's certainly okay to have off standard behavior AS LONG AS YOU TELL US THAT IN THE INSTRUCTIONS.  

Can we update the readme.md at https://github.com/microsoft/vcpkg ?
  - https://github.com/microsoft/vcpkg/blob/master/README.md 
  - https://github.com/microsoft/vcpkg/blob/master/README_es.md
  - https://github.com/microsoft/vcpkg/blob/master/README_fr.md
  - https://github.com/microsoft/vcpkg/blob/master/README_ko_KR.md
  - https://github.com/microsoft/vcpkg/blob/master/README_zh_CN.md

and add the following lines (or whatever makes sense) to the Windows quickstart paragraph:

Please note, Windows 64bit (x64) may not be the default package used when installing packages.  You may discover that the Windows 32bit (x86) version is installed.  Please verify that you have the correct intended package installed.  Note:  If you want to install a particular library you would do so via:
 
`vcpkg install  myDesiredCppPackage:x64-windows`      or    `vcpkg install myDesiredCppPackage:x86-windows`

You may also override the default via the system environment variable `VCPKG_DEFAULT_TRIPLET=x64-windows` (Go to control panel -> system -> environment variables )

And can we not close this issue UNTIL the README's are improved?  many thanks.

**Comment by zipzit** [comment]
One note:  With the fix mentioned above, I was able to preclude visible errors within Visual Studio  (i.e. the program was able to find the XXX.hpp file, no more squiggley red error lines.)    It turns out I was still unable to compile with the library, but that one is on me.  Apparently for C++ Unreal Game Engine programming, you are only able to use third party libraries via their own plugin system.  [See reference.](https://docs.unrealengine.com/en-US/ProductionPipelines/BuildTools/UnrealBuildTool/ThirdPartyLibraries/index.html)  Info offered here in case others hit this pothole.

**Comment by jeremyong** [comment]
Can we please consider changing the default for 64 bit windows to be 64 bit? Is there an issue someone can link to explaining the rationale? I'd be open to creating a PR that at the very minimum lets the user change the result, but my terminal is filled with C-c's followed immediately by `remove [pkg]` and `install [pkg]:x64-windows`

**Comment by StarGate-One** [comment]
@zipzit  /cc: @jeremyong @ras0219-msft @BillyONeal 
Reference https://github.com/microsoft/vcpkg/issues/53#issuecomment-249276675 and other comments in #1254
- From my understanding (@ras0219 @BillyONeal can chime in and correct me if I am wrong) vcpkg defaults to x86-windows for windows to streamline the customer experience as it relates to Visual Studio as it also defaults to x86 on windows when creating a new project.
- I myself agree it should default to x86 on 32-bit windows and x64 on 64-bit windows, but we would need to have the Visual Studio team make the same change to maintain the customer experience.
- I set the default triplet using one or more of the provided methods:
  - set the environment variable `VCPKG_DEFAULT_TRIPLET`
    from command prompt `set VCPKG_DEFAULT_TRIPLET=x64-windows`
    from powershell prompt `${env:VCPKG_DEFAULT_TRIPLET} = "x64-windows"`
  - add `--triplet x64-windows` to the command line
    Example: `\.vcpkg.exe install boost[core,mpi] --triplet x64-windows`
  - concatenate  `:x64-windows` after the `port[features]`
    Example: `.\vcpkg.exe install boost[core,mpi]:x64-windows`
- I myself have also created a series of powershell scripts using powershell core to maintain the various instances of vcpkg being used, triplet type needed, production or test environment, version of C/C++ ie Visual Studio, sets the various other vcpkg environment variables and or directory paths, etc.

**Comment by zipzit** [comment]
I'm (now) totally aware of the issue, but that does not begin to address my humble proposed interim fix.    Update the frigging readme file, particularly for the quickstart paragraph.  I get that code changes take time and argument and design and propogation and testing.  In the meantime, update the written instructions.   

If you can't find translators for each of the languages provided, we understand that.  Write the doggone recommendations in English on each document and ask for help.  Folks, this is open source time.  Move this along.  No excuses for easy fixes that at least get users productive again.   

Recommended additions at the bottom of the text I mentioned above...

***_translation help required here! Can you help us with a pull request?  Many thanks_***    Don't delay.

**Comment by StarGate-One** [comment]
- Reference https://github.com/microsoft/vcpkg/blob/master/docs/users/triplets.md#additional-remarks
- Unfortunately `everyone` who runs across an issue where there is existing documentation for their issue in the multitude `rtm` pages thinks the issue they had should be moved to be up front in the initial readme pages.
- `[vcpkg-root]\docs` contains a plethora of information, if I cannot find it within then I do a search of google with keywords `vcpkg`  `blob`  `<search terms>` helps me find what I am looking for about 95% of the time. 
- Example: `vcpkg`  `blob`  `"default"` `"triplet"` yields a page with the first listing the complete page containing the link mentioned above.
![image](https://user-images.githubusercontent.com/68293825/112922481-8e52e680-90da-11eb-8abe-1bd1b9393848.png)

**Comment by PhoebeHui** [comment]
@zipzit, does the issue still repro when you installed the port with x64-windows?

**Comment by zipzit** [comment]
Check my comments above.  No, the package seems to be working in that my intellisense no longer reports a missing header file.  In my case, I'm using Unreal Game Engine and they have some sort of block in place from users adding any third party libraries.  This has to do with the plugin design system that controls the entire engine.  You have to add the libraries back in carefully organized plugins.  So from what I can see, when installed as 64 bit on a Win64 bit machine everything from the VCPKG side is good.

**Comment by PhoebeHui** [comment]
@zipzit, the PR has been merged, the notes has been added to Quick Start, so close this issue now.
