### ISSUE TITLE
Unable to load automake1.15-1.15.1-1-any.pkg.tar.xz file

### ISSUE THREAD

**Issue by vlad-mal** [microsoft/vcpkg#16933]
Starting package 1/1: icu:x86-windows-mega
Building package icu[core]:x86-windows-mega...
-- [OVERLAY] Loading triplet configuration from: D:\Cpp\Lib\mega\sdk\contrib\cmake\vcpkg_extra_triplets\x86-windows-mega.cmake
CMake Warning at scripts/cmake/vcpkg_common_functions.cmake:3 (message):
  vcpkg_common_functions has been removed and all values are automatically
  provided in all portfile.cmake invocations.  Please remove
  `include(vcpkg_common_functions)`.
Call Stack (most recent call first):
  ports/icu/portfile.cmake:5 (include)
  scripts/ports.cmake:142 (include)

-- Using cached D:/Cpp/Lib/mega/3rdParty/vcpkg/downloads/icu4c-61_1-src.tgz
-- Cleaning sources at D:/Cpp/Lib/mega/3rdParty/vcpkg/buildtrees/icu/src/c-61_1-src-b2757af884.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/Cpp/Lib/mega/3rdParty/vcpkg/downloads/icu4c-61_1-src.tgz
-- Applying patch D:/Cpp/Lib/mega/3rdParty/vcpkg/ports/icu/disable-escapestr-tool.patch
-- Applying patch D:/Cpp/Lib/mega/3rdParty/vcpkg/ports/icu/remove-MD-from-configure.patch
-- Applying patch D:/Cpp/Lib/mega/3rdParty/vcpkg/ports/icu/fix_parallel_build_on_windows.patch
-- Using source at D:/Cpp/Lib/mega/3rdParty/vcpkg/buildtrees/icu/src/c-61_1-src-b2757af884.clean
-- Downloading https://repo.msys2.org/msys/x86_64/automake1.15-1.15.1-1-any.pkg.tar.xz -> msys-automake1.15-1.15.1-1-any.pkg.tar.xz...
-- Downloading https://repo.msys2.org/msys/x86_64/automake1.15-1.15.1-1-any.pkg.tar.xz... Failed. Status: 22;"HTTP response code said error"
-- Downloading https://www2.futureware.at/~nickoe/msys2-mirror/msys/x86_64/automake1.15-1.15.1-1-any.pkg.tar.xz -> msys-automake1.15-1.15.1-1-any.pkg.tar.xz...
-- Downloading https://www2.futureware.at/~nickoe/msys2-mirror/msys/x86_64/automake1.15-1.15.1-1-any.pkg.tar.xz... Failed. Status: 22;"HTTP response code said error"
-- Downloading https://mirror.yandex.ru/mirrors/msys2/msys/x86_64/automake1.15-1.15.1-1-any.pkg.tar.xz -> msys-automake1.15-1.15.1-1-any.pkg.tar.xz...
-- Downloading https://mirror.yandex.ru/mirrors/msys2/msys/x86_64/automake1.15-1.15.1-1-any.pkg.tar.xz... Failed. Status: 22;"HTTP response code said error"
-- Downloading https://mirrors.tuna.tsinghua.edu.cn/msys2/msys/x86_64/automake1.15-1.15.1-1-any.pkg.tar.xz -> msys-automake1.15-1.15.1-1-any.pkg.tar.xz...
-- Downloading https://mirrors.tuna.tsinghua.edu.cn/msys2/msys/x86_64/automake1.15-1.15.1-1-any.pkg.tar.xz... Failed. Status: 22;"HTTP response code said error"
-- Downloading https://mirrors.ustc.edu.cn/msys2/msys/x86_64/automake1.15-1.15.1-1-any.pkg.tar.xz -> msys-automake1.15-1.15.1-1-any.pkg.tar.xz...
-- Downloading https://mirrors.ustc.edu.cn/msys2/msys/x86_64/automake1.15-1.15.1-1-any.pkg.tar.xz... Failed. Status: 22;"HTTP response code said error"
-- Downloading https://mirror.bit.edu.cn/msys2/msys/x86_64/automake1.15-1.15.1-1-any.pkg.tar.xz -> msys-automake1.15-1.15.1-1-any.pkg.tar.xz...
-- Downloading https://mirror.bit.edu.cn/msys2/msys/x86_64/automake1.15-1.15.1-1-any.pkg.tar.xz... Failed. Status: 6;"Couldn't resolve host name"
-- Downloading https://mirror.selfnet.de/msys2/msys/x86_64/automake1.15-1.15.1-1-any.pkg.tar.xz -> msys-automake1.15-1.15.1-1-any.pkg.tar.xz...
-- Downloading https://mirror.selfnet.de/msys2/msys/x86_64/automake1.15-1.15.1-1-any.pkg.tar.xz... Failed. Status: 22;"HTTP response code said error"
-- Downloading https://mirrors.sjtug.sjtu.edu.cn/msys2/msys/x86_64/automake1.15-1.15.1-1-any.pkg.tar.xz -> msys-automake1.15-1.15.1-1-any.pkg.tar.xz...
-- Downloading https://mirrors.sjtug.sjtu.edu.cn/msys2/msys/x86_64/automake1.15-1.15.1-1-any.pkg.tar.xz... Failed. Status: 22;"HTTP response code said error"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:184 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".

      If error with status 4 (Issue #15434),
      try setting "http://user:password@your-proxy-ip-address:port/".

      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_acquire_msys.cmake:90 (vcpkg_download_distfile)
  scripts/cmake/vcpkg_acquire_msys.cmake:128 (msys_package_download)
  scripts/cmake/vcpkg_acquire_msys.cmake:288 (msys_package)
  ports/icu/portfile.cmake:85 (vcpkg_acquire_msys)
  scripts/ports.cmake:142 (include)

Error: Building package icu:x86-windows-mega failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: icu:x86-windows-mega
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

Additionally, attach any relevant sections from the log files above.
Failed: vcpkg install --triplet x86-windows-mega  icu    --overlay-triplets=D:\Cpp\Lib\mega\sdk\contrib\cmake\vcpkg_extra_triplets

**Comment by Neumann-A** [comment]
Looking at https://repo.msys2.org/msys/x86_64/ it looks like the tar was bumped to https://mirrors.sjtug.sjtu.edu.cn/msys2/msys/x86_64/automake1.15-1.15.1-2-any.pkg.tar.xz

**Comment by PhoebeHui** [comment]
This issue has been fixed, please get latest source and try again.
