### ISSUE TITLE
Error while bulding libraries

### ISSUE THREAD

**Issue by Frankyuz** [microsoft/vcpkg#16947]
**Describe the bug**
Evertyrime I run this command I get this message, which is not supposed to happen.

**Environment**
- OS: Windows
- Compiler: VSC

**To Reproduce**
1.PS C:\dev\vcpkg> .\bootstrap-vcpkg.bat
2. See error
3. Repeat the same command line
4. Nothing

**Expected behavior**
It should have printed out all the libraries

**Failure logs** 
Downloading https://github.com/microsoft/vcpkg-tool/releases/download/2021-02-24/vcpkg.exe -> C:\dev\vcpkg/vcpkg.exe
Done.

**Additional context**
I've tried to install it multiple times, but never worked.

**Comment by StarGate-One** [comment]
`.\bootstrap-vcpkg.bat` downloads the vcpkg binary on windows, and downloads the source, builds, compiles and links the vcpkg binary on linux/osx.

From the [vcpkg-root] directory:

`.\vcpkg.exe search` will list all available ports
`.\vcpkg.exe list` will list all the ports you have installed

`.\vcpke.exe search  [something]` where something is say `boost`
Example:
`.\vcpkg.exe search boost` will list all available ports where boost is part of the port name or in the description

`.\vcpkg.exe list [something]` where something is say `boost`
Example:
`.\vpckg.exe list boost` will list  all installed ports where boost is part of the port name or in the description

**Comment by Frankyuz** [comment]
Oh I see, actually everything was correct right?

**Comment by NancyLi1013** [comment]
Hi @Frankyuz 

Seems @StarGate-One has solved your question.

Please let me know if you have other concerns about this issue.
