### ISSUE TITLE
[cmake|linux] build failure

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#16942]
see https://dev.azure.com/vcpkg/public/_build/results?buildId=51173&view=logs&jobId=e43d08a3-46a6-5c05-c22b-b8b3a7ac1517&j=e43d08a3-46a6-5c05-c22b-b8b3a7ac1517&t=341b2070-72fd-5058-0746-f056592aaa91
probably reason:

`harfbuzz` build without `glib` feature.
`qt5-base` build with `glib` being available <- thinks harfbuzz was build with glib enabled and links it for harfbuzz (or even links it itself; missing -no-glib flag?)
-> build error 

Needed to fix: Intropspection into already build ports and the selection of features those ports are build with!

**Comment by NancyLi1013** [comment]
Related PR #16954
