### ISSUE TITLE
Error: Building package boost-regex:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by ShiverZm** [microsoft/vcpkg#16941]
**Describe the bug**
Error: Building package boost-regex:x86-windows failed with: BUILD_FAILED

**Environment**
- OS: win10 19041
- Compiler: vs2015/vs2019

**To Reproduce**
1.  .\vcpkg install boost:x86-windows boost:x86-windows-static openssl:x86-windows openssl:x86-windows-static nlohmann-json:x86-windows nlohmann-json:x86-windows-static curl:x86-windows curl:x86-windows-static
2. See error
Error code: 1

**Expected behavior**
i use latest vcpkg in github,and  run bat ,then add vcpkg to PATH,then install boost
**Failure logs** 
[build-x86-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/6220657/build-x86-windows-rel-out.log)

**Additional context**

**Comment by PhoebeHui** [comment]
@ShiverZm, Could you double check if English language package installed by VS  installer?

Failures:
```
msvc.link.dll D:\dev-tools\vcpkg\buildtrees\boost-regex\x86-windows-rel\boost\build\64c60debac8240633333a6301148bbec\boost_regex-vc140-mt-x32-1_75.dll
  ÕýÔÚ´´½¨¿â D:\dev-tools\vcpkg\buildtrees\boost-regex\x86-windows-rel\boost\build\64c60debac8240633333a6301148bbec\boost_regex-vc140-mt-x32-1_75.lib ºÍ¶ÔÏó D:\dev-tools\vcpkg\buildtrees\boost-regex\x86-windows-rel\boost\build\64c60debac8240633333a6301148bbec\boost_regex-vc140-mt-x32-1_75.exp
LINK : fatal error LNK1158: ÎÞ·¨ÔËÐÐ¡°rc.exe¡±
```

**Comment by ShiverZm** [comment]
thanks,it has been solved as you told me .

**Comment by PhoebeHui** [comment]
Good to know!
