### ISSUE TITLE
[szip] build failure

### ISSUE THREAD

**Issue by zhouhang95** [microsoft/vcpkg#16958]
**Host Environment**
- OS: x86
- Compiler: vs 2015

**To Reproduce**
`./vcpkg install szip`

**Failure logs** 
Computing installation plan...
The following packages will be built and installed:
    szip[core]:x86-windows -> 2.1.1-6
Detecting compiler hash for triplet x86-windows...
Could not locate cached archive: C:\Users\zhouhang\AppData\Local\vcpkg\archives\8d\8da24b4b9f4b2ad84f64225836d2716b31f92f08.zip
Starting package 1/1: szip:x86-windows
Building package szip[core]:x86-windows...
-- Using cached E:/vcpkg/downloads/szip-2.1.1.tar.gz
-- Cleaning sources at E:/vcpkg/buildtrees/szip/src/szip-2.1.1-6b767acfa7.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/vcpkg/downloads/szip-2.1.1.tar.gz
-- Applying patch fix-szip-config-to-set-szip-found.patch
-- Using source at E:/vcpkg/buildtrees/szip/src/szip-2.1.1-6b767acfa7.clean
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
    Command failed: ninja -v
    Working Directory: E:/vcpkg/buildtrees/szip/x86-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      E:\vcpkg\buildtrees\szip\config-x86-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:324 (vcpkg_execute_required_process)
  ports/szip/portfile.cmake:15 (vcpkg_configure_cmake)
  scripts/ports.cmake:142 (include)

Error: Building package szip:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: szip:x86-windows
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

Additionally, attach any relevant sections from the log files above.

[config-x86-windows-out.log](https://github.com/microsoft/vcpkg/files/6226996/config-x86-windows-out.log)

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by JonLiu1993** [comment]
@zhouhang95 ,CMake is not able to generate the project properly -
Check to make sure Visual Studio 2015 has the following installed:

- Desktop Development with C++
- One of the Windows SDKs, preferably the latest 19041
- English Language Pack
