### ISSUE TITLE
libjpeg-turbo:x64-windows

### ISSUE THREAD

**Issue by manncyam** [Microsoft/vcpkg#1696]
While trying to install opencv 
```
vcpkg install opencv:x64-windows
```
I got an error due to 
Error: Building package libjpeg-turbo:x64-windows failed with: BUILD_FAILED
Package: libjpeg-turbo:x64-windows
Vcpkg version: 0.0.84-a3e607c8f1b759fee75ef5dd7b420ef7df48da1a

**Comment by Mixaill** [comment]
-Try to execute `chcp 65001` before `vcpkg` command
-Attach logs from `[VCPKG_DIRECTORY]/buildtrees/opencv`

**Comment by ras0219-msft** [comment]
This should be fixed in the latest master. Please let us know if you still experience the problem!

**Comment by manncyam** [comment]
Yes I still get the same error.
[libjpeg-turbo.zip](https://github.com/Microsoft/vcpkg/files/1258459/libjpeg-turbo.zip)

**Comment by alexkaratarakis** [comment]
Judging from the logs, this doesn't seem to be the codepage issue.

**Comment by Cheney-W** [comment]
@manncyam 
I can install libjpeg-turbo and opencv successfully with the latest VCPKG and VS2017 15.9.7.
