### ISSUE TITLE
[imgui] mingw not linking to -limm32 and -ldwmapi 

### ISSUE THREAD

**Issue by famouzkk** [microsoft/vcpkg#16964]
OS: Linux
Target: Windows
Triplet: x64-mingw-static

ImGui in 1.82 reenabled ime functions by default in mingw (https://github.com/ocornut/imgui/commit/edf135c18de82aa4112ef561ecfc1ed824b8859b), now when we want to crosscompile using mingw, we are getting those errors:
```sh
/usr/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld: ../../vcpkg/installed/x64-mingw-static/lib/libimgui.a(imgui.cpp.obj):imgui.cpp:(.text+0x935): undefined reference to `ImmGetContext'
/usr/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld: ../../vcpkg/installed/x64-mingw-static/lib/libimgui.a(imgui.cpp.obj):imgui.cpp:(.text+0x964): undefined reference to `ImmSetCompositionWindow'
/usr/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld: ../../vcpkg/installed/x64-mingw-static/lib/libimgui.a(imgui.cpp.obj):imgui.cpp:(.text+0x96f): undefined reference to `ImmReleaseContext'
```
Even if we specify `CMAKE_EXE_LINKER_FLAGS_INIT` in toolchain file with `-limm32 -ldwmapi` it still fails. When I revert to 1.81 version everything is working. Should imgui portfile be updated? Thanks in advance.

**Comment by longnguyen2004** [comment]
I'll see what I can do about it.

**Comment by Cheney-W** [comment]
This issue has not been updated for over 3 months, so if it is still an issue, please reopen the issue.
