### ISSUE TITLE
[vcpkg repo] Open github discussions?

### ISSUE THREAD

**Issue by strega-nil** [microsoft/vcpkg#16972]
Should we open github discussions? What are the benefits and the drawbacks? cc @AugP

**Comment by unixwitch** [comment]
not everyone is on Discord or Slack (or wants to be on there) and there doesn't seem to be any mailing list or newsgroup for vcpkg, so having a forum for peer support seems like a good idea.

**Comment by AugP** [comment]
This sounds like a good idea to me as well, it would help us separate out questions or general discussion from future work.

**Comment by Neumann-A** [comment]
I think an extra discussion place would be could. For example just recently #16974 was opened which could be discussed there instead. I agree with @Hoikas here that the Issues page has to many No-Issues/Questions and needs to be better cleaned up for real or fixable issues. I would also suggest a more strict issue policy which closes issues which don't have a repro or a clean description within a month or two after opening. 

The main drawback of course is it will need extra attention

**Comment by strega-nil** [comment]
Alright, the team has agreed to open discussions. I will look at opening up discussions with @AugP over the next week or so

**Comment by strega-nil** [comment]
Discussions are now open! Please introduce yourselves in the [pinned post](https://github.com/microsoft/vcpkg/discussions/17048) :)
