### ISSUE TITLE
How do I ...download lib for ldap

### ISSUE THREAD

**Issue by paulgualambo** [microsoft/vcpkg#16973]
When asking a question please also include where you looked for an answer (so we can update the documentation if needed).

C:\src>.\vcpkg\vcpkg search ldap

If your library is not listed, please open an issue at and/or consider making a pull request:
    https://github.com/Microsoft/vcpkg/issues

**Comment by NancyLi1013** [comment]
Hi @paulgualambo 

Thanks for posting this issue.
Since `ldap `is not available in vcpkg now. You can open a new issue to track this or create a pull request to add this port if you have the demand for `ldap`.

Please let me know if have other questions about this issue.

**Comment by NancyLi1013** [comment]
Please open a new issue [here ](https://github.com/microsoft/vcpkg/issues/new?assignees=&labels=new+port+request+-+consider+making+a+PR%21&template=request-a-new-port.md&title=%5BNew+Port+Request%5D+%3Clibrary+name+here%3E)
