### ISSUE TITLE
Using the vtk port

### ISSUE THREAD

**Issue by trebahl** [microsoft/vcpkg#16970]
The vtk includes are no longer directly in installed/<platform>/include but in a subdirectory thereof (vtk-9.0). This means that

#include <vtkSomething.h>

no longer finds the include when using VS integration. I would need to write

#include <vtk-9.0/vtkSomething.h>

but that would make the source code dependent on the vtk version, which is a bad thing.

The only solution I found is to add g:\dev\vcpkg\installed\x64-windows\include\vtk-9.0 to AdditionalIncludeDirectories for the projects using vtk, which defeats the purpose of vtk integration.

Is there a better solution?

**Comment by Neumann-A** [comment]
> Is there a better solution?

Use CMake. It automatically adds the subdirectory if you link against a vtk target.

**Comment by NancyLi1013** [comment]
I think @Neumann-A has answered your question. Please use CMake project @trebahl . 

Closing this issue for now since there is no active thread.
