### ISSUE TITLE
Conditional dependency

### ISSUE THREAD

**Issue by prateek9623** [microsoft/vcpkg#16974]
Can we have a way to manage conditional dependency using Manifest file or some vcpkg specific function? 

As most projects don't always require a complete build, so can we have a way to ignore dependency for ignored part of the project.

For e.g. Projects have test cases and they depend on some libraries like gtest. But, we don't always need to build them. In CMake, we can disable those test cases using some option/variable. But if I have added gtest in the Manifest file, vcpkg will download gtest even if it is not required.

Proposal: we can have a vcpkg specific CMake variable through which we can find is vcpkg toolchain file is used or not. And a function through which we can tell vcpkg to download a dependency.

If there is something like this please let me know.

**Comment by Neumann-A** [comment]
Look into: port features in your manifest. You need to pass the features you want explicitly in your cmake build after that (but i forgot the variable name for that).

**Comment by prateek9623** [comment]
cool, I had to just some more in https://vcpkg.readthedocs.io/en/latest/users/manifests/#cmake-integration, I don't know how did I miss that
