### ISSUE TITLE
Could NOT find ZLIB build failure with cmake

### ISSUE THREAD

**Issue by acceleratxr** [microsoft/vcpkg#16989]
**Host Environment**
- OS: Windows
- Compiler: MSVC 2019

**To Reproduce**
1. `./vcpkg install cpr:x64-windows-static`
Attempt to build cmake project that uses `find_package` on anything that relies on `zlib` (including zlib itself).
2. Execute one of the following commands. In this example, `find_package(cpr CONFIG REQUIRED)`
a. `cmake -G"Visual Studio 16 2019" -A x64 .`
b. `cmake -G"Visual Studio 16 2019" -A x64 -DVCPKG_TARGET_TRIPLET=x64-windows-static .`
c. `cmake -G"Visual Studio 16 2019" -A x64 -DZLIB_INCLUDE_DIR=/path/to/vcpkg/installed/x64-windows-static/include .`
d. `cmake -G"Visual Studio 16 2019" -A x64 -DVCPKG_TARGET_TRIPLET=x64-windows-static -DZLIB_INCLUDE_DIR=/path/to/vcpkg/installed/x64-windows-static/include .` 

**Failure logs** 
```
-- Found OpenSSL: C:/Users/jpsaxr/gitlab/sdk_cpp/.vcpkg/installed/x64-windows-static/lib/libcrypto.lib (found version "1.1.1j")
-- Found ZLIB: C:/Users/jpsaxr/gitlab/sdk_cpp/.vcpkg/installed/x64-windows-static/lib/zlib.lib (found version "1.2.11")
CMake Error at C:/Program Files/CMake/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find ZLIB (missing: ZLIB_INCLUDE_DIR) (found suitable version
  "1.2.11", minimum required is "1")
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.18/Modules/FindZLIB.cmake:115 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  C:/Program Files/CMake/share/cmake-3.18/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  .vcpkg/installed/x64-windows-static/share/curl/CURLConfig.cmake:53 (find_dependency)
  C:/Program Files/CMake/share/cmake-3.18/Modules/FindCURL.cmake:58 (find_package)
  C:/Program Files/CMake/share/cmake-3.18/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  .vcpkg/installed/x64-windows-static/share/cpr/cprConfig.cmake:31 (find_dependency)
  CMakeLists.txt:141 (find_package)
```

**Additional context**
The behavior is ultimately inconsistent. Sometimes it works but most of the time it doesn't. If opening the project in Visual Studio and adding these arguments to the `CMakeSettings.json` file it will usually build. However, this blocker for any automated build system that relies purely on cmake since it's not possible to build from the developer prompt.

**Comment by NancyLi1013** [comment]
Hi @acceleratxr 

Thanks for posting this issue.
Seems you didn't set `CMAKE_TOOLCHAIN_FILE` in your cmake command.

You can try to build via the command like this: 
`cmake  -G "Visual Studio 16 2019" -DCMAKE_TOOLCHAIN_FILE=F:\tool\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static`

Since Visual Studio 2019 will build x64 by default. So it's unnecessary to add `-A x64`.

Note: Before running the command, please make sure you have run` .\vcpkg integrate install`.

**Comment by NancyLi1013** [comment]
@acceleratxr 

Please let me know if this is still a problem for you.

**Comment by NancyLi1013** [comment]
Closing this issue for now since no response here.
