### ISSUE TITLE
[New Port Request] bddisasm

### ISSUE THREAD

**Issue by ianichitei** [microsoft/vcpkg#16982]
Library name: bddisasm

Library description: x86/x86_64 instruction decoder and emulator

Source repository URL: https://github.com/bitdefender/bddisasm

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

I've already prepared a port [here](https://github.com/ianichitei/vcpkg/tree/d94604ac43e16abed8614c3c7ad1589ecde3d818/ports/bddisasm), but the contributing guidelines recommend opening an issue to discuss the port, instead of opening directly a PR.

I've tested the port with GCC and Clang on Linux and MSVC on Windows when building with CMake. I also checked the MSBuild integration with Visual Studio 2019 16.7.1. Everything seems to work, but I'm not entirely sure if I did everything right in the portfile.

**Comment by aizuon** [comment]
bddisasm is an interesting library that i wanted to use in some of my projects for quite a while but because it wasnt supported by vcpkg, i never had the opportunity. Thank you for your contribution!

**Comment by ianichitei** [comment]
> bddisasm is an interesting library that i wanted to use in some of my projects for quite a while but because it wasnt supported by vcpkg, i never had the opportunity. Thank you for your contribution!

I'm glad to here that. Writing the port was a good motivation for modernizing some aspects of our build scripts :)

**Comment by ianichitei** [comment]
Any updates on this? Is there anything I can/should do?

**Comment by PhoebeHui** [comment]
@ianichitei, could you submit a PR for this?

**Comment by NancyLi1013** [comment]
Thanks for posting this request and also for your PR @ianichitei. 
Closing this issue for now since this port has been added to vcpkg.
