### ISSUE TITLE
Is there a way to determine if a static or shared runtime is needed when using the toolchain file?

### ISSUE THREAD

**Issue by Ghabry** [microsoft/vcpkg#16981]
Hello,

Is there a way to automatically set the correct C++ runtime linkage based on the VCPKG triplet when using the toolchain file?

Lets say I want to build my application using this cmake config command:

```
cmake . -DVCPKG_TARGET_TRIPLET=x64-windows-static^
    -DCMAKE_TOOLCHAIN_FILE=%VCPKG%\scripts\buildsystems\vcpkg.cmake
```

Because this is the static triplet my application must be built with MTd/MT.

CMake provides ``CMAKE_MSVC_RUNTIME_LIBRARY ``, so I could append this to my CMake line:

```
cmake [...] -DCMAKE_MSVC_RUNTIME_LIBRARY=Multithreaded
```
Problem here is that the debug build in Visual Studio will use now the non-debug static runtime making the build fail. (I could also use a generator expression on the command line to solve this but this is soooo ugly)

--------

Internally (when building ports) they have access to a variable ``VCPKG_CRT_LINKAGE`` which contains the necessary information but this variable is not exposed by the toolchain file.

It would be super useful to have this variable exposed because then I could just do the following in my CMakeLists.txt and it would just work:

```
set(CMAKE_MSVC_RUNTIME_LIBRARY
  "MultiThreaded$<$<CONFIG:Debug>:Debug>$<$<STREQUAL:${VCPKG_CRT_LINKAGE},dynamic>:DLL>"
  CACHE STRING "")
```
-----

Is there a recommended solution how to handle this?

I could parse the triplet string directly ("x64-windows-static") to look for "static" but this is imo also very ugly and can break easily. E.g. for one use case I want to use the community triplet "x64-windows-static-md" which means I would be also required to check for "md" in the string.

**Comment by Ghabry** [comment]
I have now this code here to automatically configure it. Imo this just feels "dirty" compared to the possible one-liner in the previous comment.

```cmake
string(REPLACE "-" ";" TRIPLET ${VCPKG_TARGET_TRIPLET})
set(DYNAMIC ON)
foreach(t ${TRIPLET})
    if(${t} STREQUAL "static")
        set(DYNAMIC OFF)
    elseif(${t} STREQUAL "md")
        set(DYNAMIC ON)
    endif()
endforeach()
set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>$<$<BOOL:${DYNAMIC}>:DLL>" CACHE STRING "")
```

**Comment by JackBoosY** [comment]
https://github.com/microsoft/vcpkg/blob/13640c56717dec1bba16c6eb0815d3889dbe1c4d/triplets/x64-windows-static.cmake#L2
https://github.com/microsoft/vcpkg/blob/13640c56717dec1bba16c6eb0815d3889dbe1c4d/triplets/community/x64-windows-static-md.cmake#L2

**Comment by Ghabry** [comment]
Did you forget to write some text? I only see cited code.

I know about ``VCPKG_CRT_LINKAGE`` but as explained above this variable is not available when using vcpkg as a ``CMAKE_TOOLCHAIN_FILE``.

**Comment by tly000** [comment]
the script `/scripts/toolchains/windows.cmake` sets the value of `CMAKE_MSVC_RUNTIME_LIBRARY`. is this script also loaded by the toolchain file (i.e. `scripts/buildsystems/vcpkg.cmake`) ?

**Comment by Ghabry** [comment]
No, this is not loaded by the toolchain file.

This is actually the line I copy-pasted in my CMakeLists. Even chainloading this cmake file would not work because ``VCPKG_CRT_LINKAGE`` is unavailable. (is set somewhere else)

**Comment by tly000** [comment]
this is my hack to find the CRT linkage value:
```cmake
if(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC" AND CMAKE_TOOLCHAIN_FILE AND VCPKG_TARGET_TRIPLET)
    get_filename_component(TOOLCHAIN_NAME ${CMAKE_TOOLCHAIN_FILE} NAME)
    if (TOOLCHAIN_NAME STREQUAL "vcpkg.cmake")
        get_filename_component(TOOLCHAIN_DIR ${CMAKE_TOOLCHAIN_FILE} DIRECTORY)
        get_filename_component(VCPKG_ROOT ${TOOLCHAIN_DIR}/../../ ABSOLUTE)
        if (NOT EXISTS "${VCPKG_ROOT}/.vcpkg-root")
            message(FATAL_ERROR "The directory ${VCPKG_ROOT} is not a valid vcpkg root directory.")
        endif()
        # read the CRT linkage from the target file:
        file(GLOB_RECURSE TARGET_FILE "${VCPKG_ROOT}/triplets/${VCPKG_TARGET_TRIPLET}.cmake")
        if (NOT TARGET_FILE)
            message(FATAL_ERROR "Could not find target file for triplet ${VCPKG_TARGET_TRIPLET}.")
        endif()
        include(${TARGET_FILE})
        message(STATUS "VCPKG_CRT_LINKAGE is ${VCPKG_CRT_LINKAGE}")
        if (VCPKG_CRT_LINKAGE STREQUAL "static")
            set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
        else()
            set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>DLL")
        endif()
    endif()
endif()
```

**Comment by Ghabry** [comment]
Thanks for that code this is more reliable than my version 👍

**Comment by JackBoosY** [comment]
For official triplets, all dyanmic triplets use dynamic CRT linkage, and all static triplets use static CRT linkage.
- If you need to use dynamic CRT linkage in static build, you should use command `./vcpkg install PORT:x86-windows-static-md` or `./vcpkg install PORT:x64-windows-static-md`.
- If you need to use static CRT linkage in dynamic build, you should create a new triplet file in _VCPKG_ROOT/triplets/community_ named `x86-windows-mt.cmake` / `x64-windows-mt.cmake` and add the following codes:
```cmake
set(VCPKG_TARGET_ARCHITECTURE x86)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE dynamic)
```
or
```cmake
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE dynamic)
```
Then use command `./vcpkg install PORT:x86-windows-mt` or `./vcpkg install PORT:x64-windows-mt`, and add parameter `-DVCPKG_TARGET_TRIPLET=${TRIPLET_NAME}` to cmake.

**Comment by Ghabry** [comment]
This is not what I meant. The installing of libraries through vcpkg works excellent.

It is about **consuming** the libraries.

When I invoke e.g. 

```cmake
cmake . -DVCPKG_TARGET_TRIPLET=x64-windows-static^
    -DCMAKE_TOOLCHAIN_FILE=%VCPKG%\scripts\buildsystems\vcpkg.cmake
```

then the resulting Visual Studio Project is configured as ``MD`` which is wrong (this is the shared runtime).

Is there any way to recommended way to automatically set this correctly based on the triplet?

**Comment by JackBoosY** [comment]
You need to choose the triplet to be used according to the custom project, not the other way around.

**Comment by Ghabry** [comment]
Uhm okay this makes no sense to me. Imo the consumer of vcpkg is not responsible for this but the toolchain file.
But okay I will keep the hack and close that issue. Thanks
