### ISSUE TITLE
error could not locate cached archive .\vcpkg install

### ISSUE THREAD

**Issue by amoxicilinaaa** [microsoft/vcpkg#16995]
when using the command:  **.\vcpkg install --triplet x64-windows boost-asio boost-filesystem boost-iostreams boost-lockfree boost-system boost-variant cryptopp curl jsoncpp libmariadb luajit mpir pugixml**

this error appears to me, follow the image for a better interpretation. I would like a solution for him.

![erro could not locate](https://user-images.githubusercontent.com/38027045/113228816-203e2900-926c-11eb-9008-6dafedeca642.png)

thank you all.

**Comment by NancyLi1013** [comment]
Hi @amoxicilinaaa 

Thanks for posting this issue.

Seems the URL https://strawberry.perl.bot/download/5.30.0.1/strawberry-perl-5.30.0.1-32bit.zip has broken now.

But another URL http://strawberryperl.com/download/5.30.0.1/strawberry-perl-5.30.0.1-32bit.zip can be available to access it.

So could you please remove the cache and download it again?
If it still failed, please try to download it manually and then put it into _vcpkg_root/downloads/_ directory. And then rebuild the port.

**Comment by NancyLi1013** [comment]
@amoxicilinaaa 
Please let me know if this is still a problem for you.

**Comment by amoxicilinaaa** [comment]
Oops sorry my friend I have been these days without access to the computer I just did the manual steps that were informed up there and everything went well.

thanks @NancyLi1013 .

**Comment by NancyLi1013** [comment]
Thanks for your feedback. I'm closing this for now since you have solved the problem.
