### ISSUE TITLE
[OpenXLSX] build failure

### ISSUE THREAD

**Issue by mdsadiqueinam** [microsoft/vcpkg#16996]
**Host Environment**
- OS: Windows 10
- Compiler: revision

**To Reproduce**
`./vcpkg create https://github.com/troldal/OpenXLSX/archive/refs/heads/master.zip`
`./vcpkg edit OpenXLSX (edited the version and name)`
`./vcpkg install OpenXLSX`

**Failure logs** 
 Computing installation plan...
The following packages will be built and installed:
    openxlsx[core]:x86-windows -> 0.2.0-dev
Detecting compiler hash for triplet x86-windows...
Could not locate cached archive: C:\Users\mdsad\AppData\Local\vcpkg\archives\a6\a65b57a825ef41b3f43716c6ebd3fd7aedafb4f2.zip
Starting package 1/1: openxlsx:x86-windows
Building package openxlsx[core]:x86-windows...
-- Using cached C:/Users/mdsad/vcpkg/downloads/master.zip
-- Cleaning sources at C:/Users/mdsad/vcpkg/buildtrees/openxlsx/src/master-77bd609386.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/mdsad/vcpkg/downloads/master.zip
-- Using source at C:/Users/mdsad/vcpkg/buildtrees/openxlsx/src/master-77bd609386.clean
-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:146 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j5
    Working Directory: C:/Users/mdsad/vcpkg/buildtrees/openxlsx/x86-windows-dbg
    See logs for more information:
      C:\Users\mdsad\vcpkg\buildtrees\openxlsx\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:105 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:45 (vcpkg_build_cmake)
  ports/OpenXLSX/portfile.cmake:70 (vcpkg_install_cmake)
  scripts/ports.cmake:142 (include)

Error: Building package openxlsx:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openxlsx:x86-windows
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

Additionally, attach any relevant sections from the log files above.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.
[log.txt](https://github.com/microsoft/vcpkg/files/6241455/log.txt)

**Comment by NancyLi1013** [comment]
Hi @mdsadiqueinam 

Thanks for posting this issue.

Seems `openxlsx ` is not available in vcpkg now. Please open a [new port request](https://github.com/microsoft/vcpkg/issues/new?assignees=&labels=new+port+request+-+consider+making+a+PR%21&template=request-a-new-port.md&title=%5BNew+Port+Request%5D+%3Clibrary+name+here%3E) if you want to add this port in vcpkg.

Also I cannot get the error info since the attachment is wrong.
