### ISSUE TITLE
[libLAS - arm64] build failure

### ISSUE THREAD

**Issue by MikeCernea** [microsoft/vcpkg#16993]
**Host Environment**
- OS: MacOS - building for iOS
- Compiler: AppleClang 12.0.0.12000032

**To Reproduce**
`sudo ./vcpkg install --triplet=arm64-osx liblas`

After fixing the dependencies: 
 * libffi fix - replace ARM64 with arm64 in line 14 in ~/vcpkg/ports/libffi/CMakeLists.txt
 * proj4 fix - build proj4 for x64 and copy ~/vcpkg/installed/arm64-osx/tools/sqlite3 from x64-osx

It came the time for libLas to compile and it fails with an error in ../incluide/liblas/detail/endian.hpp as arm64 does not have a definition to decide on LIBLAS_LITTLE_ENDIAN and LIBLAS_BYTE_ORDER.

**Failure logs** 
The error is found in install-arm64-osx-dbg-out.log as follows:
vcpkg/buildtrees/liblas/src/libLAS-1-100581b933.clean/src/../include/liblas/detail/endian.hpp:96:3: error: The file liblas/detail/endian.hpp needs to be set up for your CPU type.
# error The file liblas/detail/endian.hpp needs to be set up for your CPU type.
  ^
1 error generated.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. `liblas:x64-osx` can install succeed. `arm64-osx` is a community triplet, and there are no update about this issue for a long time. If there are new process or change of this issue, please reopen this issue.
