### ISSUE TITLE
[gnome libs] Move away from ftp.gnome.org

### ISSUE THREAD

**Issue by autoantwort** [microsoft/vcpkg#17009]
The pipelines often fails with something like
```
-- Downloading https://ftp.gnome.org/pub/GNOME/sources/atkmm/2.24/atkmm-2.24.2.tar.xz... Failed. Status: 28;"Timeout was reached"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:184 (message):
      
      Failed to download file.
```
We could switch to https://download.gnome.org/sources/ which is hopefully more stable

**Comment by Neumann-A** [comment]
maybe after #13100 is merged.

**Comment by autoantwort** [comment]
That is an large PR. You already have updated gtk to https://download.gnome.org/sources/ . Since you updated all versions anyway, you could maybe also switch to https://download.gnome.org/sources/, but that doesn't make the pr smaller 🙈

**Comment by Neumann-A** [comment]
ah no. after #16959 is merged I will put #13100 out of draft and somebody else can take over. I don't intend to sink even more time in stuff I don't use ;)

**Comment by autoantwort** [comment]
I feel you. But thank you for this incredible amount of work!

**Comment by Neumann-A** [comment]
```
Building package libcroco[core]:arm64-windows...
-- Downloading https://download.gnome.org/sources/libcroco/0.6/libcroco-0.6.13.tar.xz -> libcroco-0.6.13.tar.xz...
-- Downloading https://download.gnome.org/sources/libcroco/0.6/libcroco-0.6.13.tar.xz... Failed. Status: 28;"Timeout was reached"

```

the other url seems not to be better.

**Comment by autoantwort** [comment]
Hm ok -.-  
Another source is maybe https://gitlab.gnome.org/Archive/libcroco. Sometimes the libs have a github mirror, which is probably the most stable variant

**Comment by autoantwort** [comment]
Imho it is super annoying that currently nearly every pipeline fails if you do some work on the "base" ports because of this. Maybe we can ask the gnome mirror maintainers why there are so often timeouts. Or the pipeline should cache downloads

**Comment by Neumann-A** [comment]
> Or the pipeline should cache downloads

at least the PR pipeline could use cached downloads. The real CI pipeline should download everything. This way contributors don't have to deal with downloading issues of unrelated ports and the amount of traffic vcpkg generates gets reduced. (CI probably gets rejected from downloading due to too many download requests considering that each CI downloads.)

**Comment by autoantwort** [comment]
The ci now caches the downloads
