### ISSUE TITLE
Error: Building package boost-compatibility:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by Foward-Fu** [microsoft/vcpkg#17000]
When I install pcl with using vcpkg , there are some questions.
Environment:Windows10
Failure logs:
D:\vcpkg>.\vcpkg install pcl
Computing installation plan...
The following packages will be built and installed:
  * boost-algorithm[core]:x86-windows -> 1.75.0
  * boost-align[core]:x86-windows -> 1.75.0
  * boost-any[core]:x86-windows -> 1.75.0
  * boost-array[core]:x86-windows -> 1.75.0
  * boost-asio[core]:x86-windows -> 1.75.0#1
  * boost-assert[core]:x86-windows -> 1.75.0
  * boost-atomic[core]:x86-windows -> 1.75.0#1
  * boost-bimap[core]:x86-windows -> 1.75.0
  * boost-bind[core]:x86-windows -> 1.75.0
  * boost-build[core]:x64-windows -> 1.75.0.beta1#1
  * boost-chrono[core]:x86-windows -> 1.75.0#1
  * boost-circular-buffer[core]:x86-windows -> 1.75.0
  * boost-compatibility[core]:x86-windows -> 1.75.0
  * boost-concept-check[core]:x86-windows -> 1.75.0#2
  * boost-config[core]:x86-windows -> 1.75.0
  * boost-container[core]:x86-windows -> 1.75.0#1
  * boost-container-hash[core]:x86-windows -> 1.75.0
  * boost-context[core]:x86-windows -> 1.75.0#3
  * boost-conversion[core]:x86-windows -> 1.75.0
  * boost-core[core]:x86-windows -> 1.75.0
  * boost-coroutine[core]:x86-windows -> 1.75.0#1
  * boost-date-time[core]:x86-windows -> 1.75.0#1
  * boost-detail[core]:x86-windows -> 1.75.0
  * boost-dynamic-bitset[core]:x86-windows -> 1.75.0
  * boost-endian[core]:x86-windows -> 1.75.0
  * boost-exception[core]:x86-windows -> 1.75.0#1
  * boost-filesystem[core]:x86-windows -> 1.75.0#1
  * boost-foreach[core]:x86-windows -> 1.75.0
  * boost-format[core]:x86-windows -> 1.75.0
  * boost-function[core]:x86-windows -> 1.75.0
  * boost-function-types[core]:x86-windows -> 1.75.0
  * boost-functional[core]:x86-windows -> 1.75.0
  * boost-fusion[core]:x86-windows -> 1.75.0
  * boost-graph[core]:x86-windows -> 1.75.0#1
  * boost-integer[core]:x86-windows -> 1.75.0
  * boost-interprocess[core]:x86-windows -> 1.75.0
  * boost-intrusive[core]:x86-windows -> 1.75.0
  * boost-io[core]:x86-windows -> 1.75.0
  * boost-iostreams[core]:x86-windows -> 1.75.0#1
  * boost-iterator[core]:x86-windows -> 1.75.0
  * boost-lambda[core]:x86-windows -> 1.75.0
  * boost-lexical-cast[core]:x86-windows -> 1.75.0
  * boost-math[core]:x86-windows -> 1.75.0#1
  * boost-modular-build-helper[core]:x64-windows -> 1.75.0#8
  * boost-move[core]:x86-windows -> 1.75.0
  * boost-mp11[core]:x86-windows -> 1.75.0
  * boost-mpl[core]:x86-windows -> 1.75.0
  * boost-multi-array[core]:x86-windows -> 1.75.0
  * boost-multi-index[core]:x86-windows -> 1.75.0
  * boost-multiprecision[core]:x86-windows -> 1.75.0
  * boost-numeric-conversion[core]:x86-windows -> 1.75.0
  * boost-optional[core]:x86-windows -> 1.75.0
  * boost-parameter[core]:x86-windows -> 1.75.0
  * boost-phoenix[core]:x86-windows -> 1.75.0
  * boost-pool[core]:x86-windows -> 1.75.0
  * boost-predef[core]:x86-windows -> 1.75.0
  * boost-preprocessor[core]:x86-windows -> 1.75.0
  * boost-property-map[core]:x86-windows -> 1.75.0
  * boost-property-tree[core]:x86-windows -> 1.75.0
  * boost-proto[core]:x86-windows -> 1.75.0
  * boost-ptr-container[core]:x86-windows -> 1.75.0
  * boost-random[core]:x86-windows -> 1.75.0#1
  * boost-range[core]:x86-windows -> 1.75.0
  * boost-ratio[core]:x86-windows -> 1.75.0
  * boost-rational[core]:x86-windows -> 1.75.0
  * boost-regex[core]:x86-windows -> 1.75.0#1
  * boost-serialization[core]:x86-windows -> 1.75.0#1
  * boost-signals2[core]:x86-windows -> 1.75.0
  * boost-smart-ptr[core]:x86-windows -> 1.75.0
  * boost-sort[core]:x86-windows -> 1.75.0
  * boost-spirit[core]:x86-windows -> 1.75.0
  * boost-static-assert[core]:x86-windows -> 1.75.0
  * boost-system[core]:x86-windows -> 1.75.0#1
  * boost-test[core]:x86-windows -> 1.75.0#1
  * boost-thread[core]:x86-windows -> 1.75.0#1
  * boost-throw-exception[core]:x86-windows -> 1.75.0
  * boost-tokenizer[core]:x86-windows -> 1.75.0
  * boost-tti[core]:x86-windows -> 1.75.0
  * boost-tuple[core]:x86-windows -> 1.75.0
  * boost-type-index[core]:x86-windows -> 1.75.0
  * boost-type-traits[core]:x86-windows -> 1.75.0
  * boost-typeof[core]:x86-windows -> 1.75.0
  * boost-uninstall[core]:x64-windows -> 1.75.0
  * boost-unordered[core]:x86-windows -> 1.75.0
  * boost-utility[core]:x86-windows -> 1.75.0
  * boost-uuid[core]:x86-windows -> 1.75.0
  * boost-variant[core]:x86-windows -> 1.75.0
  * boost-winapi[core]:x86-windows -> 1.75.0
  * boost-xpressive[core]:x86-windows -> 1.75.0
  * bzip2[core]:x86-windows -> 1.0.8#1
  * eigen3[core]:x86-windows -> 3.3.9
  * flann[core]:x86-windows -> 2019-04-07#1
  * liblzma[core]:x86-windows -> 5.2.5#2
  * libpng[core]:x86-windows -> 1.6.37#14
  * lz4[core]:x86-windows -> 1.9.2-2
  * openssl[core]:x86-windows -> 1.1.1j
    pcl[core]:x86-windows -> 1.11.1#2
  * qhull[core]:x86-windows -> 8.0.2
  * xxhash[core]:x86-windows -> 0.8.0#1
  * zlib[core]:x86-windows -> 1.2.11#9
  * zstd[core]:x86-windows -> 1.4.9
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x86-windows...
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\73\73af2c434d98bb4e99e39e43abe8cda79e291b1e.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\f1\f1feb5e3f5ef88e246fb6f3e20a5fa2b2d9e1d15.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\24\24c65a61f0c8b37a78b9984c597f8f22e9e6d6f0.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\bc\bc992aa978bb19f4d2131c4c7619252003d094ff.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\32\3201200c1d4f9da5c23c89f49c2ca48f0b4d73cf.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\8b\8b1c898845792d9a2adc2eef51da2e8d7828fa43.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\39\399967a31617f4c84ec68cbcd0861c4661a3878a.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\06\06190127f705d5c90297942a84454dd7d06be095.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\78\78c328c8dd90b60168c9c9c5dc45df549985a34f.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\76\7628b3304b1e9a590673bb454561ca1eb1a24361.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\0c\0c3a584d3671fbde1e6f24643d76c05965c75f03.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\ab\ab74adc0598e7a4530f5129bb0eef276e931b183.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\12\12823a4ca5aaa2bb3c10a8b8b440cd5c9927148e.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\ad\ade6addd338439d74983f4d3b6a24ec680be33b8.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\90\902f16f017306eab36e1dba15049d84d2c128260.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\47\47a21a28a439fed9682a7d5f5154281526d30832.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\0e\0e08a6827842893fea422f9b2ace0c60a6e3a5cc.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\f2\f28bc01196f64655b52134c26365088887ca28ef.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\c1\c128963c5f47a037fb25643c2ba6cd427891ee97.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\97\97b376c8ef9362beaeebabd81969be7721173f6a.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\f7\f7bb249710aee4f226348c211c3e66f09ca6971e.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\ed\ed07c2fa8f6bcdcc04cedd74d92431bed061c6ed.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\e6\e61af551d9c16e8a532b35248c89cfcf0f2d6068.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\ea\ea15646297b9630580c1b759e0b303f7b88ce7ef.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\74\749ea33e65f5b4ef72bc2f3451c48d9825e7f0cc.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\b3\b31b378dc24fc7d0e2c17bf0bbd846be98c3281f.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\52\5294a7473a99548ecc15398b5b1f2d398a2fcfff.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\c8\c8aa72454bc092b93f1a99a4babef67e4666607f.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\87\8786ff3839fd6cf1f51c2f98c156890a0d2872ad.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\44\447e3699f5510e0f7aa99b16342d0b62bfd04200.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\b0\b0d85e40743eabe9ebb371ddca3f7aec81b0ec6f.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\f2\f22e7b9bb8162e1808ff518861496f096db7e4ff.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\72\72408e7d392a313b0a52e46bb676b13bfe677b20.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\68\68c49725b7a35ac6089a816b1b945380b35d03c7.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\01\0175dd69581fac22a14de6877d4d873c7ebf4fb0.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\08\08eaca2d7db18c8bcf19f05a1757588ba46c1e34.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\3f\3f448ff992dafc1741ef1aa9fa90f1f1439d8dcb.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\c1\c123a2966aa8d76514d51a274fb87a07c831ee9f.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\a5\a59bddbd72ff1ea89d965eb893e4aa19a687723d.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\47\477d118e94833eb4fa4b39a514bf50c4b92a0bb6.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\55\55d76632a944193775d22567b9561c02a38aeabc.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\28\281917962dfc7c8395afa1c4a622644bad0009fe.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\94\948f7b0d26d52ec1f9fa11abf317c5a9347771f8.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\02\025c44f0f04355fed9b38c590eea906e24337420.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\71\71c39129b5a96b6738cad75ae2558f2e7c6e86fb.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\e2\e2eff831054bdcc605e2a91c51d60822fa337abb.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\e1\e198ec5c8963ba1909e438693df98372640847c7.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\a0\a0ad5bdf0995e6228664a255be174e84c80119b6.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\19\1930a639ae77bb93f4ec6ec9cf7f3c3c2fc71225.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\ce\cec45e880229d3007a4b2aa4f4f05dfdf497fa64.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\9d\9dc65e5539f98d5baee44e08b56a0ded48a46679.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\59\59a2d49f177e71f259aaf4d1f40c5d3cbc0a19df.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\fe\fe929b58decc099acc5cc1a8fd914dd1672dfdc9.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\bb\bb535129b68f3200fdad1dc8e7a2d8b2476eadc4.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\5e\5eb642bfe97f03f9a9ad7d5e09013ca83d36da8d.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\b1\b1149f0ed93162a81b66ce138fd061d42ec9c917.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\39\3912d4e960665aa5623ebfc49e56ca132f672cad.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\d5\d558b88dd47b395b367a6b969d3b3acb928a7e14.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\2b\2bf3b488de6950f81b89bab0ab88b751e588a991.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\f1\f1f2c6ee2ba1a2e0c9b188ca9b174b401a84907a.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\3a\3a55de07d2a4d0ecae822df72c4041ee109f3bf4.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\b5\b52fb1840668a12e471d737d71f48fb546551d67.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\6f\6f8852f67c4d68646c410d35131626bd1a28ede2.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\65\6521535a9400eeacf828080b7084e4789175f8c7.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\66\6665a91c7d8b1187a2395731309f362c2ff50cda.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\79\79b978bed38898632ccdf6fe2fe07a1952b83472.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\08\08f74900bf2d685a7e12633fe6be01151e1f6b42.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\ff\ff6124dac6ce399f4b4a1e2e93e8d6dc492be379.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\d3\d365d8ae280fede312b42f81b7f5fd208e3af04e.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\0f\0fbca063a69fba6f14a55d414bb22b92120c37b2.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\25\25d749493398c40ce652d055b263803dbc918d52.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\14\14f53138593b0f65ce5dfabcd058306c3c0152fc.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\76\76cdbaf8576dd1ced1154226d8aa7d696ae6a736.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\b6\b6ed9b31371a916734c3745707331190380d1fcc.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\0b\0b5d2dccdb326091ac81ddda22fecb8159dd52ff.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\cb\cb6d91169d823cd21b76cee2c6df54e9cce7e9af.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\ef\eff88fdebef4202b6d9effbcec0c943a962afae7.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\01\01c4bb450a2f99a70f9ffc1f5a4d76d2e69ef2d8.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\1a\1a477b5254a173284bbd815e6c808d30085759f8.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\af\afaf8eba5f5f2a2ef9bbe22547318fc0992fe63a.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\4c\4c398e02ad8d72c8fe0fc7bb6e8717ffa14fcf2c.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\b5\b503d2906c5260e12203afa81eeb7d6f37b3a205.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\1a\1a1a5979b6d08168908c6aeac770f1846437e8c2.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\ff\ffc1a745549decb38a8f418eb079bd3416181b21.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\0c\0c91eb75a62f186fb8523278d1a7b6d11b801037.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\a8\a8440a767fdbd2a28f9d5d0b45dba1100dfe0256.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\8d\8d56c9d48b9fc65b817e595bb72cd72415db6ed1.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\c4\c42811b502f6dae64c6243202de536883c813075.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\7c\7c8279dae038852c1c933fd692f249bec06240b5.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\56\56bfbd9341081f49427d4619b19ee8c7f0a0d850.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\ce\ce82a98ba951a8832ad78971eea522ee20460c04.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\be\beec86af229e1598dc6846ea2b45bd150f82a211.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\61\61ef322d318fbd081e4aafc48ac5b42ca251da3d.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\49\49626bd03a1d8455417f5e0b3801725789f18c38.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\6d\6df2c4bd3b7e88441116f2585587cb1f5eaf1b84.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\8c\8c5dcaca067354b20abd8c19e1b679fb2a8cf1e9.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\13\1304f4ff996b8a3674922286fd43778ad5ef8b87.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\a4\a4da1a4c7fe24548fd76b5236cc9268fdc0689b4.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\07\07e4b92114a3ad7b86a5a38f4f7d034b5dad59d6.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\b3\b30c39945e3df86f903f1a678a93067bf5ae4937.zip
Could not locate cached archive: C:\Users\73190\AppData\Local\vcpkg\archives\b1\b15c0b2e97ebfda04e470848cb1ad6665f1bd8f5.zip
Starting package 1/101: boost-compatibility:x86-windows
Building package boost-compatibility[core]:x86-windows...
-- Downloading https://github.com/boostorg/compatibility/archive/boost-1.75.0.tar.gz -> boostorg-compatibility-boost-1.75.0.tar.gz...
-- Extracting source D:/vcpkg/downloads/boostorg-compatibility-boost-1.75.0.tar.gz
-- Using source at D:/vcpkg/buildtrees/boost-compatibility/src/ost-1.75.0-b473de8f4d.clean
-- Packaging headers
-- Packaging headers done
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.74.0/LICENSE_1_0.txt -> boost_LICENSE_1_0.txt...
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.74.0/LICENSE_1_0.txt... Failed. Status: 6;"Couldn't resolve host name"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:184 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".

      If error with status 4 (Issue #15434),
      try setting "http://user:password@your-proxy-ip-address:port/".

      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  installed/x86-windows/share/boost-vcpkg-helpers/boost-modular-headers.cmake:17 (vcpkg_download_distfile)
  ports/boost-compatibility/portfile.cmake:12 (boost_modular_headers)
  scripts/ports.cmake:142 (include)

Error: Building package boost-compatibility:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-compatibility:x86-windows
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

Additionally, attach any relevant sections from the log files above.

I don`t konw what I should do to solve the questions.
Thank you for your help.

**Comment by PhoebeHui** [comment]
@Foward-Fu, could you try the solution provided in issue https://github.com/microsoft/vcpkg/issues/13348?

**Comment by Foward-Fu** [comment]
> @Foward-Fu, could you try the solution provided in issue #13348?

Thank you ,the solution can resolve my questions.I Set the HTTPS_PROXY and HTTP_PROXY environment.
