### ISSUE TITLE
Failing to build zeromq as static lib with dynamic CRT

### ISSUE THREAD

**Issue by thierryba** [Microsoft/vcpkg#1700]
Hi,

For smaller libs, what I'm currently using is static libs but linked against the dynamic CRT (MD/MDd).
So I tried ti create a triplet like that:
set(VCPKG_TARGET_ARCHITECTURE x86) 
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

but then if I try to build zeromq, it fails saying that the lib has "invalid art linkage". The lib is linked against MT/MTd.

Is it possible at all to achieve what I'm trying with vcpkg? (it works fine outside of vcpkg)

**Comment by thierryba** [comment]
For the record it seems to work fine for simple things like lib or bzip2... So it must be specific to zeromq.

**Comment by ras0219-msft** [comment]
Thanks for reporting this issue!

I believe this is fixed by 5a920ef7. Let us know if you still encounter any problems!

**Comment by thierryba** [comment]
@ras0219-msft 👍 indeed
