### ISSUE TITLE
[vcpkg/toolchain] Toolchain does not know about host triplets

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#17001]
The following code is wrong considering the existence of host triplets:

https://github.com/microsoft/vcpkg/blob/13640c56717dec1bba16c6eb0815d3889dbe1c4d/scripts/buildsystems/vcpkg.cmake#L654-L660

the toolchain needs to know `VCPKG_HOST_TRIPLET` which will be set to `VCPKG_TARGET_TRIPLET` if not explicitly requested otherwise. This also needs to be forward to the manifest invocation in the toolchain and furthermore added to `vcpkg_configure_cmake` via `-DVCPKG_HOST_TRIPLET=${HOST_TRIPLET}`

cc @ras0219-msft @strega-nil

**Comment by strega-nil** [comment]
I think that this solution is not necessarily the right one. `find_program`, by spec, seems to search for programs in the target, not for the host. This is not necessarily how most people do use it, but we may consider instead adding something like `find_host_program`, similar to https://github.com/solrex/android-cmake/blob/master/android.toolchain.cmake#L1557. More research is needed.

**Comment by Neumann-A** [comment]
According to https://cmake.org/cmake/help/latest/command/find_program.html it is not well defined. It searches paths for the host and the target according to the docs. 
I believe the intention here is to have a similar logic to `find_library` and have people overwrite the variables in the toolchain if cross-compiling or define the `CMAKE_` variables controlling the behavior of `find_program`  (like done in the linked find_host_program example). 
In the context of vcpkg I don't see any reason why the result of `find_program` should ever point to a target program instead of a host program. Unless it is doing something strange like generating another script with the absolut paths to the tools on the target [or something like this] which is then intended to run on the target or a simulator.

**Comment by dg0yt** [comment]
> In the context of vcpkg I don't see any reason why the result of `find_program` should ever point to a target program instead of a host program. Unless it is doing something strange like generating another script with the absolut paths to the tools on the target [or something like this] which is then intended to run on the target or a simulator.
> (or the script is being strange and tries to link against an executable)

For completeness, some packages create programs which are meant to be run on the host in cross-builds. For example, `gdal` has or had `gdal-config`, and Qt5 has `qmake` which behaves different from a host `qmake`. This can be resolved by providing and using a dedicated install path for such tools, and `find_program` has to use this path before normal host paths.

**Comment by strega-nil** [comment]
Probably, the best way forward here is to extend the documentation to add workarounds for this, since `find_program` is really for finding target programs.

**Comment by dg0yt** [comment]
Hm. As long as cmake is operating in script mode, I don't think there is something like a "target" in a cmake sense.

**Comment by Neumann-A** [comment]
> Probably, the best way forward here is to extend the documentation to add workarounds for this, since find_program is really for finding target programs (as messed up as that might seem)

I disagree. Neither `find_library` nor `find_program` nor `find_file` know/define a context in which it should find anything. This even applies to `find_package`. As @dg0yt says in script mode there is no concept of target and still those functions need to work. It is thus up to the toolchain/script to define the context for those functions to work which brings us to the most common use case we are expecting within vcpkg. In my opinion the most common context within vcpkg would be:

`find_library`: Find library for the target machine.
`find_program`: Find program able to run on the build/host machine (e.g. code generators [For Qt moc, uic whatever] or similar). 
`find_file`: depends highly on context. Most likely looking for a header to setup an include directory for the target.
`find_package`: find package for the target machine.

It should be noted that the context of all this calls can be manipulated by setting corresponding catch variables, so defining the context as above in the vcpkg toolchain is not a problem for uses since they still can overwrite the behavior by explicitly setting the values or manipulting the setup of the corresponding controling cache variables themself.

**Comment by dg0yt** [comment]
`ports.cmake` already consumes `VCPKG_PORT_CONFIGS`. Can't this pattern be used to adjust search contexts in a controlled way? (Shouldn't this controlled mechanism replace the uncontrolled globbing of directories in `tools`?)
Maybe some of these installed config files need to track the triplet they were built for and the triplet they are used for.

**Comment by past-due** [comment]
I just encountered this issue in a cross-build scenario.

In my case, the intent of the `find_program` call was to find a program able to run on the host/build machine, just as @Neumann-A specifies.

In fact, a quick audit of other `find_program` uses in this particular project found that all of them are intended to find a program to run *on the host*/build machine.
