### ISSUE TITLE
[New Port Request] OpenXLSX

### ISSUE THREAD

**Issue by mdsadiqueinam** [microsoft/vcpkg#17002]
Library name: OpenXLSX

Library description: OpenXLSX is a C++ library for reading, writing, creating and modifying Microsoft Excel® files, with the .xlsx format.

Source repository URL: https://github.com/troldal/OpenXLSX

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by sean1832** [comment]
I don't get it. Why is this closed?
