### ISSUE TITLE
How do I know how to use a port after installation?

### ISSUE THREAD

**Issue by upupming** [microsoft/vcpkg#17034]
From the [installing-and-using-packages docs](https://github.com/microsoft/vcpkg/blob/f3221c0405b6f99c6eff113cb4ca8c81c3ad3a84/docs/examples/installing-and-using-packages.md), I know the usage of the package will be printed to console after successful installation:

```powershell
...

The package sqlite3:x86-windows provides CMake targets:

    find_package(unofficial-sqlite3 CONFIG REQUIRED)
    target_link_libraries(main PRIVATE unofficial::sqlite3::sqlite3))

```

However, when I have plenty of packages installed I will forget this usage, but I cannot get any information on how to use this package. I think we can add a feature such as `vcpkg usage` command, for example:

```
>  .\vcpkg.exe list
sqlite3:x64-windows                                3.35.2           SQLite is a software library that implements a s...
>  .\vcpkg.exe usage
The package sqlite3:x86-windows provides CMake targets:

    find_package(unofficial-sqlite3 CONFIG REQUIRED)
    target_link_libraries(main PRIVATE unofficial::sqlite3::sqlite3))
```

It may seem to be a naive question, please let me know if I missed any documentation. Is there any way to know how to use a package from the port cmake file or any vcpkg command?

**Comment by NancyLi1013** [comment]
Hi @upupming 

Thanks for posting this issue.

Currently there is only one way to know how to use a port via the usage or the printed message for those ports.

But now, we have a plan to implement this feature `vcpkg-usage` , please see more details here #16951.

**Comment by mathisloge** [comment]
> It may seem to be a naive question, please let me know if I missed any documentation. Is there any way to know how to use a package from the port cmake file or any vcpkg command?

just type `vcpkg install <yourpackage>` again, to see the usage info.

**Comment by NancyLi1013** [comment]
@upupming 

Please let me know if this is still a problem for you.

**Comment by upupming** [comment]
> @upupming 
> 
> Please let me know if this is still a problem for you.

No problem, thanks!
