### ISSUE TITLE
Vcpkg with code runner

### ISSUE THREAD

**Issue by mdsadiqueinam** [microsoft/vcpkg#17035]
Vcpkg works perfectly with code runner in linux then it is not working with windows

**Comment by NancyLi1013** [comment]
Hi @mdsadiqueinam 

Thanks for posting this issue.

Currently, vcpkg doesn't support Code Runner. Please see https://github.com/microsoft/vcpkg/issues/10217#issuecomment-596839642.

Since duplicated to #10217. Let's track this issue #10217.
