### ISSUE TITLE
[x264] build failure on osx pipeline

### ISSUE THREAD

**Issue by autoantwort** [microsoft/vcpkg#17039]
**Host Environment**
- OS: macOS CI
- Compiler: unknown

**To Reproduce**
Run pipeline of #16577

**Failure logs** 
https://dev.azure.com/vcpkg/public/_build/results?buildId=51429&view=logs&jobId=0a61404f-5c45-5632-e83c-408b7fcca1d6&j=2644860b-263e-5de8-c39e-3f62c017aad0&t=0c846259-ebdc-51ce-09bf-fc9ed3a241c7

install-x64-osx-dbg-err.log:
```
install: mkdir /Users/vagrant/Data/packages/x264_x64-osx/Users/vagrant/Data: File exists
make: *** [install-lib-dev] Error 71
make: *** Waiting for unfinished jobs....
```

**Comment by JackBoosY** [comment]
Should be a random issue. Already passed.

**Comment by autoantwort** [comment]
@JackBoosY But I also have this issue locally, please reopen

**Comment by JackBoosY** [comment]
@autoantwort Can you please provide more info?

**Comment by autoantwort** [comment]
What do you need, I simply do `vcpkg install x264` and get the error above?

**Comment by JackBoosY** [comment]
@autoantwort Yes please.

**Comment by autoantwort** [comment]
@JackBoosY ?

**Comment by JackBoosY** [comment]
Can you please reproduce this issue locally and provide the failure log and output?

**Comment by autoantwort** [comment]
>  I simply do `vcpkg install x264` and get the error above

to reproduce:
`vcpkg install x264`

error log:
```
install: mkdir /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/packages/x264_x64-osx/Users: File exists
make: *** [install-lib-dev] Error 71
make: *** Waiting for unfinished jobs....
```

If you can not reproduce this an a mac, maybe try installing -> removing (but don't) remove the packages folder -> installing

**Comment by autoantwort** [comment]
Happened again in #17073

**Comment by Greisby** [comment]
Happens also here.
The pblm is that the installation targets holds twice the target path:
*buildtrees/x264/src/14d026c3bd-bca2ebf740.clean/Makefile*:
> install-cli: cli
>	$(INSTALL) -d $(DESTDIR)$(bindir)
>	$(INSTALL) x264$(EXE) $(DESTDIR)$(bindir)
>
>install-lib-dev:
>	$(INSTALL) -d $(DESTDIR)$(includedir) $(DESTDIR)$(libdir)/pkgconfig
>	$(INSTALL) -m 644 $(SRCPATH)/x264.h x264_config.h $(DESTDIR)$(includedir)
>	$(INSTALL) -m 644 x264.pc $(DESTDIR)$(libdir)/pkgconfig
>
>install-lib-static: lib-static install-lib-dev
>	$(INSTALL) -d $(DESTDIR)$(libdir)
>	$(INSTALL) -m 644 $(LIBX264) $(DESTDIR)$(libdir)
>	$(if $(RANLIB), $(RANLIB) $(DESTDIR)$(libdir)/$(LIBX264))

*buildtrees/x264/install-x64-osx-dbg-out.log*:
>install -d /Volumes/Development/Releases/Mac/vcpkg/packages/x264_x64-osx/Volumes/Development/Releases/Mac/vcpkg/installed/x64-osx/debug/bin
>install -d /Volumes/Development/Releases/Mac/vcpkg/packages/x264_x64-osx/Volumes/Development/Releases/Mac/vcpkg/installed/x64-osx/debug/include /Volumes/Development/Releases/Mac/vcpkg/packages/x264_x64-osx/Volumes/Development/Releases/Mac/vcpkg/installed/x64-osx/debug/lib/pkgconfig
>install -m 644 ../src/14d026c3bd-bca2ebf740.clean/x264.h x264_config.h /Volumes/Development/Releases/Mac/vcpkg/packages/x264_x64-osx/Volumes/Development/Releases/Mac/vcpkg/installed/x64-osx/debug/include
>install -m 644 x264.pc /Volumes/Development/Releases/Mac/vcpkg/packages/x264_x64-osx/Volumes/Development/Releases/Mac/vcpkg/installed/x64-osx/debug/lib/pkgconfig

*bindir*, *includedir* and *libdir* already contain *DESTDIR*.
It should therefore be empty.

**Comment by JackBoosY** [comment]
@Greisby I remember that's by design. @Neumann-A right?

**Comment by Neumann-A** [comment]
> bindir, includedir and libdir already contain DESTDIR.

`$(DESTDIR) => ${CURRENT_PACKAGES_DIR}` -> This is the staging area. everything has to go there
`$(libdir) => ${CURRENT_INSTALLED_DIR}` -> this is the final install location. Make should not install into here. This is required for ports hardcoding `${prefix}` into something. 

SO the questing here is why is the path doubled. bindir, includedir and libdir shouldn't contain CURRENT_PACKAGES_DIR so something is messing up the environment.

**Comment by Greisby** [comment]
I succeeded the first part of the installation, into packages, by adding the following to the portfile:
```
if(VCPKG_TARGET_IS_OSX)
	list(APPEND OPTIONS --bindir=/bin)
	list(APPEND OPTIONS --libdir=/lib)
	list(APPEND OPTIONS --includedir=/include)
endif()
```
The files are installed at the right place, but then the vcpkg internals fails with the same double path problem.
```
-- Building x64-osx-dbg
-- Installing x64-osx-dbg
-- Building x64-osx-rel
-- Installing x64-osx-rel
CMake Error at scripts/cmake/vcpkg_build_make.cmake:236 (file):
  file RENAME failed to rename

    /Volumes/Development/Releases/Mac/vcpkg/packages/x264_x64-osx_tmp/Volumes/Development/Releases/Mac/vcpkg/installed/x64-osx

  to

    /Volumes/Development/Releases/Mac/vcpkg/packages/x264_x64-osx
```

So it seems that it is indeed designed to install to that strange double path, but to finally move the leaf folder at the right place.

So I rolled back and tried to understand why the install to this double path fails.
The error is:
```
-- Configuring x64-osx-rel
-- Building x64-osx-dbg
-- Installing x64-osx-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:146 (message):
    Command failed: /usr/bin/make -j 9 -f Makefile install DESTDIR=/Volumes/Development/Releases/Mac/vcpkg/packages/x264_x64-osx
    Working Directory: /Volumes/Development/Releases/Mac/vcpkg/buildtrees/x264/x64-osx-dbg
    See logs for more information:
      /Volumes/Development/Releases/Mac/vcpkg/buildtrees/x264/install-x64-osx-dbg-out.log
      /Volumes/Development/Releases/Mac/vcpkg/buildtrees/x264/install-x64-osx-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_make.cmake:214 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_make.cmake:26 (vcpkg_build_make)
  ports/x264/portfile.cmake:65 (vcpkg_install_make)
  scripts/ports.cmake:139 (include)
```
Looking into the logs, there is only a strange error:
```
install: mkdir /Volumes/Development/Releases/Mac/vcpkg/packages/x264_x64-osx/Volumes/Development: File exists
make: *** [install-lib-dev] Error 71
make: *** Waiting for unfinished jobs....
```
No idea why it fails. Executing the command by hand on the console works.
Could maybe the problem come from the fact that my vcpkg is located in a mounted samba share?

**Comment by Greisby** [comment]
It seems to be an OS problem (at least /usr/bin/install).
I modified the Makefile by hand and replaced *install* with *mkdir -p*
The installation then succeeds.
I don't see any other reason than an issue with vcpkg being on a mounted samba share.

**Comment by JackBoosY** [comment]
cc @strega-nil-ms

**Comment by JackBoosY** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.
