### ISSUE TITLE
 because it uses overrides and the `versions` feature flag is disabled.

### ISSUE THREAD

**Issue by sainttelant** [microsoft/vcpkg#17036]
Hi， everyone , i want to use vcpkg install the library of uwebsocket,  when i tried to install its older repo(version  v0.14.0 or 14.0.0), i changed the vcpkg.json file as the example displayed :
```json
{
  "name": "uwebsockets",
  "version": "14.0.0.0",
  "description": "Simple, secure & standards compliant web I/O for the most demanding of applications",
  "homepage": "https://github.com/uWebSockets/uWebSockets",
  "dependencies": [
    "usockets",
    "zlib"
  ],
  "overrides": [
    {
      "name": "uwebsockets",
      "version": "14.0.0"
    }
  ]
}
```
however, when i put  .\vcpkg install uwebsockets:x64-windows in the terminate, the error occurred as follows:
Computing installation plan...
Parsing manifest failed: F:\vcpkg-master\vcpkg-master\ports\uwebsockets was rejected because it uses overrides and the `versions` feature flag is disabled.
This can be fixed by removing "overrides".
See `vcpkg help versioning` for more information.
Note: Updating vcpkg by rerunning bootstrap-vcpkg may resolve this failure.

Anyhelp will be very appreciated!!!!

**Comment by sainttelant** [comment]
@vicroms ,   could you please give me some guidances to install the library of uwebsockets, i wanne install the older version v0.14.0, i tried to add the overrides line as above in vcpkg.json, however, it didn' work, and then, i noticed you 've answered some similar questions, so i ask you for assistance if you don't mind , i will appreciate so much. Thank you in advance.

should i specifiy the "builtin-baseline": "......"   there?

**Comment by vicroms** [comment]
Hi @sainttelant 

You need to enable the `versions` feature flag. There are a couple of ways to do this on Windows.

The easiest one is to create an environment variable `VCPKG_FEATURE_FLAGS` with `versions` as its value. Other ways to do it are described in the [versioning announcement blog post](https://devblogs.microsoft.com/cppblog/take-control-of-your-vcpkg-dependencies-with-versioning-support/#getting-started-with-versions).

You do need to set the `builtin-baseline` which can be set to the latest commit of vcpkg.

**Comment by PhoebeHui** [comment]
@sainttelant, does this still be a question for you?

**Comment by sainttelant** [comment]
@PhoebeHui @vicroms   Thanks for your help. it works  now
