### ISSUE TITLE
cannot install opencv

### ISSUE THREAD

**Issue by designfusionjb** [Microsoft/vcpkg#1704]
Command:
c:\vcpkg> .\vcpkg.exe install opencv

Produces error:
Contains invalid characters. Only alphanumeric lowercase ASCII characters and dashes are allowed

Other packages install without any error.

**Comment by alexkaratarakis** [comment]
Please try running:
`.\vcpkg.exe install opencv --debug`

**Comment by zhanMan** [comment]
## D:\vs2015\vcpkg-master>.\vcpkg.exe install opencv --debug
The following packages will be built and installed:
  * libjpeg-turbo:x86-windows
  * liblzma:x86-windows
  * libpng:x86-windows
    opencv:x86-windows
  * tiff:x86-windows
  * zlib:x86-windows
Additional packages (*) will be installed to complete this operation.
Building package zlib:x86-windows...
[DEBUG] _wpopen("where.exe cmake 2>&1")
[DEBUG] _wpopen() returned 1
[DEBUG] _wpopen(""D:\vs2015\vcpkg-master\downloads\cmake-3.9.1-win32-x86\bin\cmake.exe" --version 2>&1")
[DEBUG] _wpopen() returned 0
[DEBUG] _wpopen("where.exe git 2>&1")
[DEBUG] _wpopen() returned 1
[DEBUG] _wpopen(""D:\vs2015\vcpkg-master\downloads\MinGit-2.14.1-32-bit\cmd\git.exe" --version 2>&1")
[DEBUG] _wpopen() returned 1
[DEBUG] _wpopen(""C:\Program Files\git\cmd\git.exe" --version 2>&1")
[DEBUG] _wpopen() returned 0
[DEBUG] _wpopen(""C:\Program Files (x86)\git\cmd\git.exe" --version 2>&1")
[DEBUG] _wpopen() returned 1
[DEBUG] _wpopen("powershell -NoProfile -ExecutionPolicy Bypass -Command "& {& 'D:\vs2015\vcpkg-master\scripts\fetchDependency.ps1' -Dependency git}" 2>&1")
[DEBUG] _wpopen() returned 1
Launching powershell failed or was denied when trying to fetch git version 2.14.1.
(No sufficient installed version was found)
[DEBUG] ..\src\VcpkgPaths.cpp(95)

**Comment by designfusionjb** [comment]
I managed to fix this issue by running the following commands:
git pull
./vcpkg update
.\bootstrap-vcpkg.bat

When I did a "vcpkg update" it told me to do a "git pull" but not the "bootstrap-vcpkg.bat". This should be added to the instructions for "vcpkg update after doing the git pull step."

**Comment by alexkaratarakis** [comment]
Thanks for the suggestion!
In general, `bootstrap-vcpkg.bat` is not needed in every single `git pull`.
Instead, if we do an interesting change, we bump the version. We have added a warning that you need to rerun `bootstrap-vcpkg.bat` if the built `vcpkg.exe` does not match the version of the tree.

This should avoid such an issue in the future.
