### ISSUE TITLE
[TGUI] Install fails without error on macOS 11.1 (20C69)

### ISSUE THREAD

**Issue by SamuelMarks** [microsoft/vcpkg#17056]
**Is your feature request related to a problem? Please describe.**

### `CMakeLists.txt`
```cmake
cmake_minimum_required(VERSION 3.0)
cmake_policy(SET CMP0048 NEW)
project(pp VERSION 0.0.0 LANGUAGES CXX)

set(src src/main.cpp)
find_package(TGUI CONFIG REQUIRED)
add_executable(${PROJECT_NAME} ${src})
target_link_libraries(${PROJECT_NAME} PRIVATE tgui)
````

### `src/main.cpp`
First example at the top of https://tgui.eu/tutorials/0.9/sdl-backend/

### `shell`
```sh
$ [path]/vcpkg install tgui
$ mkdir build && cd $_
$ cmake -DCMAKE_TOOLCHAIN_FILE=[path]/vcpkg/scripts/buildsystems/vcpkg.cmake ..
-- The CXX compiler identification is AppleClang 12.0.0.12000032
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at vcpkg/installed/x64-osx/share/tgui/TGUIConfig.cmake:86 (message):
  Requested TGUI configuration (Shared) was not found
Call Stack (most recent call first):
  vcpkg/scripts/buildsystems/vcpkg.cmake:861 (_find_package)
  CMakeLists.txt:6 (find_package)


CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:861 (_find_package):
  Found package configuration file:

    vcpkg/installed/x64-osx/share/tgui/TGUIConfig.cmake

  but it set TGUI_FOUND to FALSE so package "TGUI" is considered to be NOT
  FOUND.
Call Stack (most recent call first):
  CMakeLists.txt:6 (find_package)


-- Configuring incomplete, errors occurred!
See also "/tmp/a/build/CMakeFiles/CMakeOutput.log".
See also "/tmp/a/build/CMakeFiles/CMakeError.log".
```

**Proposed solution**
Would be nice if the example would build

**Describe alternatives you've considered**
I'm trying other cross-platform GUI frameworks that vcpkg 'supports', e.g., see the trackbacks at https://github.com/microsoft/vcpkg/issues/17052

**Comment by sfhacker** [comment]
Have you contacted us before?
Just build TGUI from source on Windows 10 x64 (no Apple sorry!) without issues.

![image](https://user-images.githubusercontent.com/25817529/114388649-51591a80-9bd7-11eb-872c-9ab091f858e9.png)

Most probably your environment is broken!

**Comment by SamuelMarks** [comment]
@sfhacker Maybe it works on Windows [and Linux]. Would be great if someone else, with macOS, can confirm it works for them.

(and no I haven't contacted before about TGUI… but have for 9 other cross-platform GUI frameworks in vcpkg [and others])
