### ISSUE TITLE
Error: Building package boost-compatibility:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by Alive59** [microsoft/vcpkg#17050]
Package: boost-compatibility:x86-windows
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

**Comment by autoantwort** [comment]
Maybe solved by  #13348

Without filling out the issue template it is hard to help... :)

**Comment by PhoebeHui** [comment]
@Alive59, could you provide us failure logs? if it failed with network issue, please try the solution that provided by issue #13348 and see if it works for you?

**Comment by PhoebeHui** [comment]
@Alive59, please reopen this issue with failure log if it still be a problem for you.
