### ISSUE TITLE
[libidn2] build failure on osx pipeline

### ISSUE THREAD

**Issue by autoantwort** [microsoft/vcpkg#17057]
**Host Environment**
- OS: macOS CI
- Compiler: unknown

**To Reproduce**
Run pipeline of #17049

**Failure logs** 
https://dev.azure.com/vcpkg/c1ee48cb-0df2-4ab3-8384-b1df5a79fe53/_apis/build/builds/51476/artifacts?artifactName=failure%20logs%20for%20x64-osx&api-version=6.0&%24format=zip

autoconf-x64-osx-err.log:
```
autoreconf: export WARNINGS=
autoreconf: Entering directory '.'
autoreconf: running: autopoint --force
autoreconf: running: aclocal --force -I m4 -I unistring/m4
autoreconf: configure.ac: tracing
autoreconf: running: glibtoolize --copy --force
autoreconf: configure.ac: not using Intltool
autoreconf: running: gtkdocize --copy
Can't exec "gtkdocize": No such file or directory at /usr/local/Cellar/autoconf/2.71/share/autoconf/Autom4te/FileUtils.pm line 293.
autoreconf: error: gtkdocize failed with exit status: 2
```

**Additional context**
It seems to be similar to #16990

**Comment by autoantwort** [comment]
Maybe you have to run https://apple.stackexchange.com/questions/108513/cant-exec-glibtoolize-no-such-file-or-directory
on the build nodes

**Comment by NancyLi1013** [comment]
Hi @autoantwort 

Thanks for posting this issue.
I noticed that all CI checks have passed on #17049 now. Does this issue also exist on your machine?

On my virtual box machine, the failures like this:

```
  autoreconf: Entering directory `.'
  autoreconf: running: autopoint --force
  Can't exec "autopoint": No such file or directory at /usr/local/Cellar/autoconf/2.69/share/autoconf/Autom4te/FileUtils.pm line 345.
  autoreconf: failed to run autopoint: No such file or directory
  autoreconf: autopoint is needed because this package uses Gettext
```
I investigated this error and found the reference https://dausruddin.com/autoreconf-failed-to-run-autopoint-no-such-file-or-directory/ and http://tutorialspots.com/how-to-fix-error-autoreconf-failed-to-run-autopoint-no-such-file-or-directory-on-centos-4724.html.

Seems need to install `gettext`. But I cannot install it without permission.

So I'm not sure if it can solve the problem. If possible, you can try on your local machine.

**Comment by autoantwort** [comment]
> Does this issue also exist on your machine?

Yes

**Comment by autoantwort** [comment]
`brew install gtk-doc` solves the issue

**Comment by NancyLi1013** [comment]
Thanks for your reply. This seems be related our test environment. For me, `gettext` is required.

**Comment by dg0yt** [comment]
IMO this is a problem with the ports which rely on autoconf:
While some host dependencies (such as gettext, gtk-doc) could be disabled by parameters to `configure`, they are mandatory when running `autoconf`.

**Comment by strega-nil** [comment]
Seems like this should be solved by changing the array [here](https://github.com/microsoft/vcpkg/blob/master/scripts/azure-pipelines/osx/configuration/Vagrantfile#L17) to also include `gettext` (and perhaps gtk-doc?)

Once this is PR'd, I can do the actual updates.

**Comment by dg0yt** [comment]
gtk-doc is already waiting for your review at #17227. I will add gettext and comment there.

**Comment by NancyLi1013** [comment]
`brew install gettext` solves the issue on my machine. We may need to add message to reminder users to install required dependency library. 

But I'm not sure if other users have the same required dependency as mine. For now, I cannot confirm which one is needed for this port. Such as `gettext ` or `gtk-doc`.

**Comment by dg0yt** [comment]
#17419 got merged, so this should be solved.

**Comment by NancyLi1013** [comment]
Thanks for your information @dg0yt
