### ISSUE TITLE
jxrlib does not build because of hash mismatch (again)

### ISSUE THREAD

**Issue by lazyhamster** [Microsoft/vcpkg#1705]
I'm trying to build freeimage and one of the dependencies - jxrlib - failed to build.
Error message indicates SHA512 hash mismatch of the downloaded archive.

I've found issues #1669 with the same problem.
However in my case downloaded file has same hash as it was before the fix for #1669.

> Expected hash: [ c4f42c690a2543b00ef9fe6e4f479b582e966b27c13e8b0efad39fa85d70b4edb60eac91a856c371a4e875e7a2769e0aba31b508ee61f7314150c6eb34a19c0b ]
> Actual hash: [ 6e8b579108444e9bea8d01f57e2ac3b63963c084adb8e265cfd82bb1199b8bd168b8aa41319cf34b87e97db1d72d0f3cc2d3dac881fcd1a6f398fe808d55772d ]

When I change hash in portfile.cmake build completes without successfully.

Could maybe somebody else try to build jxrlib so we can find which hash is the right one after all?

**Comment by ras0219-msft** [comment]
I get the same hash listed as your "actual" hash.

>6e8b579108444e9bea8d01f57e2ac3b63963c084adb8e265cfd82bb1199b8bd168b8aa41319cf34b87e97db1d72d0f3cc2d3dac881fcd1a6f398fe808d55772d

**Comment by lazyhamster** [comment]
Thank you for the test.
So should then hash be fixed in port file (technically do a revert of previous fix)?

**Comment by ras0219-msft** [comment]
Yep! I've pushed the revert. Thanks for opening this issue and confirming the fix 👍.
