### ISSUE TITLE
How do I link my program in Debug with Release packages?

### ISSUE THREAD

**Issue by Fedr** [microsoft/vcpkg#17061]
I would like to link my program in Debug configuration with Release version of vcpkg packages. Is it possible? In particular in
1. Visual Studio
2. Linux/Cmake

If yes, please suggest how.

**Comment by JackBoosY** [comment]
Hmm. so you should manually find the libraries because we always provide the suitable configuration.

**Comment by Fedr** [comment]
Yes, it would be nice to get an answer.

**Comment by JackBoosY** [comment]
For Visual Studio, there is no way to solve your question.
For cmake, you should implement find_library manually.

I don't know why you need to do this.

**Comment by dg0yt** [comment]
@JackBoosY On Linux systems, it is fairly common to build projects in debug mode but link to release versions of 3rd-party components (unless you really want to debug into a particular component). That's probably the reason why it is soooooooo alien to vcpkg newbies that it builds both release and debug variants, significantly increasing build time and disk space. I would even say it is a barrier to wider adoption of vcpkg.

**Comment by JackBoosY** [comment]
@ras0219 @ras0219-msft what do you think about this?

**Comment by Fedr** [comment]
Agree with @dg0yt . This was the primary reason of asking this question for Linux.

On Windows one can try this way:
![image](https://user-images.githubusercontent.com/3136125/120627101-0091cf80-c46c-11eb-9537-67296711883e.png)
But it is necessary to override macro ```_ITERATOR_DEBUG_LEVEL=0``` and still one can get errors from static library linking:
```
1>cpr.lib(cprtypes.cpp.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug'
1>gdcmDSED.lib(gdcmMediaStorage.cxx.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug'
```

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
