### ISSUE TITLE
[fmt] build failure, triplet mingw but depend msvc

### ISSUE THREAD

**Issue by Sodacooky** [microsoft/vcpkg#17092]
**Host Environment**
- OS: Windows10
- Compiler: mingw

**To Reproduce**
`./vcpkg install fmt --triplet=x64-mingw-dynamic`

**Failure logs** 
```
Computing installation plan...
The following packages will be built and installed:
    fmt[core]:x64-mingw-dynamic -> 7.1.3#2
  * vcpkg-cmake[core]:x64-windows -> 2021-02-28#1
Additional packages (*) will be modified to complete this operation.
No suitable Visual Studio instances were found
```

**Additional context**
I think it's improper to need a Visual Studio to build a MinGW package, or its dependence.
Tried to edit the portfile but it didn't work.

**Comment by dg0yt** [comment]
`vcpkg-cmake[core]` is a host dependency. You must explicitly set the host triplet to mingw if you don't have MSVC.

**Comment by dg0yt** [comment]
FTR, `vcpkg-cmake` doesn't strictly depend on Visual Studio, but there seems to be no way to express this in terms of vcpkg ports.
