### ISSUE TITLE
CMake Error for zlib:x86-windows

### ISSUE THREAD

**Issue by tp2043** [microsoft/vcpkg#17097]
.\vcpkg install curl[tool]
Computing installation plan...
The following packages will be built and installed:
    curl[core,non-http,schannel,ssl,sspi,tool,winssl]:x86-windows -> 7.74.0#3
  * zlib[core]:x86-windows -> 1.2.11#9
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x86-windows...
Could not locate cached archive: C:\Users\Tanvi Palekar\AppData\Local\vcpkg\archives\f9\f9055bd2e31511a3e7cf0d2cda1af5ed91b357fd.zip
Could not locate cached archive: C:\Users\Tanvi Palekar\AppData\Local\vcpkg\archives\a6\a611b4a775a847047b5c58220a7f24f63edd9825.zip
Starting package 1/2: zlib:x86-windows
Building package zlib[core]:x86-windows...
-- Using cached C:/Users/Tanvi Palekar/vcpkg/downloads/zlib1211.tar.gz
-- Cleaning sources at C:/Users/Tanvi Palekar/vcpkg/buildtrees/zlib/src/1.2.11-63309e48e5.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/Tanvi Palekar/vcpkg/downloads/zlib1211.tar.gz
-- Applying patch cmake_dont_build_more_than_needed.patch
-- Applying patch 0001-Prevent-invalid-inclusions-when-HAVE_-is-set-to-0.patch
-- Applying patch add_debug_postfix_on_mingw.patch
-- Using source at C:/Users/Tanvi Palekar/vcpkg/buildtrees/zlib/src/1.2.11-63309e48e5.clean
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
    Command failed: ninja -v
    Working Directory: C:/Users/Tanvi Palekar/vcpkg/buildtrees/zlib/x86-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\Users\Tanvi Palekar\vcpkg\buildtrees\zlib\config-x86-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:324 (vcpkg_execute_required_process)
  ports/zlib/portfile.cmake:22 (vcpkg_configure_cmake)
  scripts/ports.cmake:142 (include)

Error: Building package zlib:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zlib:x86-windows
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

Additionally, attach any relevant sections from the log files above.

**Comment by JonLiu1993** [comment]
@tp2043 ,Thanks for posting this issue,please send the error log _C:\Users\Tanvi Palekar\vcpkg\buildtrees\zlib\config-x86-windows-out.log_

**Comment by tp2043** [comment]
[config-x86-windows-out.log](https://github.com/microsoft/vcpkg/files/6262935/config-x86-windows-out.log)

**Comment by JonLiu1993** [comment]
@tp2043 ,CMake is not able to generate the project properly -
Check to make sure Visual Studio 2019 has the following installed:

Desktop Development with C++
One of the Windows SDKs, preferably the latest 19041
English Language Pack

**Comment by tp2043** [comment]
Done and resolved. thank you
