### ISSUE TITLE
[gdal] build failure

### ISSUE THREAD

**Issue by MikeCernea** [microsoft/vcpkg#17090]
**Host Environment**
- OS: Windows
- Compiler: revision

**To Reproduce**
`./vcpkg install gdal`

**Failure logs** 
the log file shows:
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64\link.EXE"' : return code '0xc0000005'

console shows:
Error: Building package gdal:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: gdal:x64-windows
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

**Additional context**
Please notice the same package fails building on mac(arm64) there the issue is "configure.ac: error: required file 'config.rpath' not found"

**Comment by JackBoosY** [comment]
Yeah, we think that's a compiler bug, but we couldn't repro it.
Duplicated to #15324.
