### ISSUE TITLE
Error: Building package libjpeg-turbo:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by ShiverZm** [microsoft/vcpkg#17109]
**Describe the bug**
i use vcpkg install opencv,but met this problem.And i install this libjpeg-turbo,it still did not work.

**Environment**
- OS: win10 19041
- Compiler: vs2015

**To Reproduce**
1. ./vcpkg  install libjpeg-turbo:x64-windows
2. See error

> CMake Deprecation Warning at scripts/cmake/vcpkg_check_features.cmake:182 (message):
>   calling `vcpkg_check_features` without the `FEATURES` keyword has been
>   deprecated.
> 
>       Please add the `FEATURES` keyword to the call.
> Call Stack (most recent call first):
>   ports/libjpeg-turbo/portfile.cmake:35 (vcpkg_check_features)
>   scripts/ports.cmake:142 (include)
> 
> 
> -- Configuring x64-windows
> CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
>     Command failed: ninja -v
>     Working Directory: D:/dev-tools/vcpkg/buildtrees/libjpeg-turbo/x64-windows-rel/vcpkg-parallel-configure
>     Error code: 1
>     See logs for more information:
>       D:\dev-tools\vcpkg\buildtrees\libjpeg-turbo\config-x64-windows-out.log
> 
> Call Stack (most recent call first):
>   scripts/cmake/vcpkg_configure_cmake.cmake:324 (vcpkg_execute_required_process)
>   ports/libjpeg-turbo/portfile.cmake:40 (vcpkg_configure_cmake)
>   scripts/ports.cmake:142 (include)

**Expected behavior**

**Failure logs** 
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/6262496/config-x64-windows-out.log)

**Comment by JonLiu1993** [comment]
@ShiverZm ,Thanks for posting this issue,The error log you send looks can't open,can you send me again? 
![Capture](https://user-images.githubusercontent.com/63675417/113677331-0b401a80-96f0-11eb-99dc-f5d3ea683c57.PNG)

**Comment by ShiverZm** [comment]
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/6264260/config-x64-windows-out.log)

**Comment by JonLiu1993** [comment]
@ShiverZm ,CMake is not able to generate the project properly -
Check to make sure Visual Studio 2019 has the following installed:

Desktop Development with C++
One of the Windows SDKs, preferably the latest 19041
English Language Pack

**Comment by JonLiu1993** [comment]
@ShiverZm ,If this is still a problem for you, please reopen
