### ISSUE TITLE
[allegro5] How do I use it?

### ISSUE THREAD

**Issue by SamuelMarks** [microsoft/vcpkg#17108]
After doing
```sh
vcpkg install allegro5 imgui[allegro5-binding]
```
I've tried, in my `CMakeLists.txt` these three lines (independently):
```cmake
find_package(allegro5 CONFIG REQUIRED)
```
```cmake
find_package(allegro CONFIG REQUIRED)
```
```cmake
find_path(ALLEGRO5_INCLUDE_DIRS "allegro5.h")
```

But none succeeded.

Here is a full example:

### `CMakeLists.txt`
```cmake
cmake_minimum_required(VERSION 3.0)
cmake_policy(SET CMP0048 NEW)
project(pp VERSION 0.0.0 LANGUAGES C)

file(DOWNLOAD https://raw.githubusercontent.com/liballeg/allegro5/0b3a999/examples/common.c src/common.c
     EXPECTED_HASH SHA256=6c9f62f2a5ea9fac1a75ed51033511a31e08671b7edcb70413dd6c623a486e95)

file(DOWNLOAD https://raw.githubusercontent.com/liballeg/allegro5/0b3a999/examples/ex_get_path.c src/main.c
     EXPECTED_HASH SHA256=bedf8955e8b7f709b5b8a64392dd2d4d06a0de78e1f317c4ae012a169def065d)

set(src ${CMAKE_CURRENT_BINARY_DIR}/src/main.c)

# find_package(allegro5 CONFIG REQUIRED)  # Could not find a package configuration file
# find_package(allegro CONFIG REQUIRED)   # Could not find a package configuration file
# find_path(ALLEGRO5_INCLUDE_DIRS "allegro5.h")  # ALLEGRO5_INCLUDE_DIRS-NOTFOUND
add_executable(${PROJECT_NAME} ${src})

# target_link_libraries(${PROJECT_NAME} PRIVATE allegro)   # ld: library not found for -lallegro
# target_link_libraries(${PROJECT_NAME} PRIVATE allegro5)  # ld: library not found for -lallegro5
```

### `sh`
```sh
$ [path]/vcpkg install allegro5 imgui[allegro5-binding]
$ mkdir build && cd $_
$ cmake -DCMAKE_TOOLCHAIN_FILE=[root]/vcpkg/scripts/buildsystems/vcpkg.cmake ..
$ cmake --build .
# `fatal error: 'allegro5/allegro.h' file not found` when everything is commented. 
# Also tried with `<>` rather than `""`.
```

**Comment by PhoebeHui** [comment]
@SamuelMarks, allegrao5 doesn't provide cmake config and targets file officially, so please use find_path() and find_library() instead.
See [installing-and-using-packages](https://github.com/microsoft/vcpkg/blob/master/docs/examples/installing-and-using-packages.md#handling-libraries-without-native-cmake-support). Please also submit a request to Upstream.

**Comment by JackBoosY** [comment]
The changes in my PR #19493 will provide the following usage:
```
The package allegro5:x86-windows provides CMake targets:

    find_package(unofficial-allegro5 CONFIG REQUIRED)
    # Note: 9 target(s) were omitted.
    target_link_libraries(main PRIVATE allegro allegro_ttf allegro_font allegro_main)
```

**Comment by dg0yt** [comment]
> The changes in my PR #19493 will provide the following usage:
> 
> ```
> The package allegro5:x86-windows provides CMake targets:
> 
>     find_package(unofficial-allegro5 CONFIG REQUIRED)
>     # Note: 9 target(s) were omitted.
>     target_link_libraries(main PRIVATE allegro allegro_ttf allegro_font allegro_main)
> ```

This is auto-generated? It seems inconsistent to have `unofficial` in the `find_package()` call but not in the target names.

**Comment by JackBoosY** [comment]
@dg0yt  Yes. it's auto-generated. Since the we use the origin target names, it's reasonable.

**Comment by JackBoosY** [comment]
@dg0yt  That's why it's `unofficial`.

**Comment by Spongman** [comment]
how to add the correct include directories?
