### ISSUE TITLE
Registries is hard to use

### ISSUE THREAD

**Issue by cnSchwarzer** [microsoft/vcpkg#17107]
We have to
1. Commit our source repo
2. Get commit id
3. Update it in 'ports/(portname)/portfile.cmake'
4. Use overlay feature and '--head' to get SHA512, or need to update git-tree in versions, which is more annoying
5. Update SHA512
6. Use 'rev-parse HEAD:ports/xx' to get git-tree object id
7. Update in versions/x-/xx.json and baseline.json

😅 Too complicated to do this every time

**Comment by strega-nil** [comment]
So, I agree in theory; however, I'm not sure exactly what to do about it. I would like more information on how you might like this process to work; what might make a difference in your case, what features we could create. I think this is better suited for a discussion, where people can make suggestions and we can spin out PRs and issues from that discussion, so I'll move it over there :)
