### ISSUE TITLE
Error: Building package fmt:x64-mingw-dynamic failed with: POST_BUILD_CHECKS_FAILED

### ISSUE THREAD

**Issue by Aragami1408** [microsoft/vcpkg#17114]
**Host Environment**
- OS: Windows
- Compiler: MinGW g++ 

**To Reproduce**
Steps to reproduce the behaviour:
`./vcpkg install fmt:x64-MinGW-dynamic`

**Failure logs** 
When I try to install the package it stated:
```
The following files were built for an incorrect architecture:

    D:\GitProject\vcpkg\packages\fmt_x64-mingw-dynamic\debug\bin\libfmtd.dll
Expected x64, but was: x86

    D:\GitProject\vcpkg\packages\fmt_x64-mingw-dynamic\bin\libfmt.dll
Expected x64, but was: x86

Found 1 error(s). Please correct the portfile:
    D:\GitProject\vcpkg\ports\fmt\portfile.cmake
-- Performing post-build validation done
Error: Building package fmt:x64-MinGW-dynamic failed with: POST_BUILD_CHECKS_FAILED
```
**Additional Context**:
This type of problem also occurred while installing other packages like glfw3,.etc

**Comment by longnguyen2004** [comment]
@Aragami1408 Do you have the correct toolchain on your PATH? If you're building for x64, you need to have it on your PATH.

**Comment by LilyWangLL** [comment]
This issue hasn’t been updated more than 3 months, if it is still an issue, please reopen this issue.
