### ISSUE TITLE
applocal.ps1: custom target directory for dependencies

### ISSUE THREAD

**Issue by arthurzam** [microsoft/vcpkg#17118]
**Is your feature request related to a problem? Please describe.**
The `applocal.ps1` script (which is very wonderful I must say) selects automatically into which directory to copy all dependencies (the directory of the target binary), which is selected [here](https://github.com/microsoft/vcpkg/blob/master/scripts/buildsystems/msbuild/applocal.ps1#L68-L69). After this variable is set, the `resolve` function passes it as the target to all deployment functions.

It would be very useful for me to have an option to pass to this script custom target directory.

**Proposed solution**
I have thought maybe as a fifth parameter to the script, but my knowledge of powershell isn't quite good, therefore I don't know how to set default value to this parameter (as all usage currently passes 4 params only).
Another possible option is an environment variable, but I have no idea if such an idea is acceptable?

**Describe alternatives you've considered**
It is possible to copy my binaries to the desired folder, run the script, and then move the binary only back to original place. But I think this is backward approach.

**Additional context**
This need had risen in one of my projects, which uses a main executable and additional modules which are loaded during runtime, and all the dependencies of the modules should be in the same directory of the main executable.

**Comment by BillyONeal** [comment]
I'm not sure what the purpose of such a feature would be, applocal.ps1 already copies next to the main executable.

>which uses a main executable and additional modules which are loaded during runtime

The proposed feature wouldn't help with that because we can't don't know that things are loaded during runtime.
