### ISSUE TITLE
[DOCKER][--clean-after-build] file DOWNLOAD cannot open file for write

### ISSUE THREAD

**Issue by DemetriouJohn** [microsoft/vcpkg#17121]
**Describe the bug**
When attempting to run vcpkg-bootstrap.bat error is throwing regarding not finding MSBuild, but the path that vcpkg is looking for is in the wrong place. 

**Environment**
windows server core 20H2 base image

**To Reproduce**
1. Install msbuild visual studio tools in docker using the following
```
FROM mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-20H2

SHELL ["powershell", "-command"]

# Download the Build Tools bootstrapper.
ADD https://aka.ms/vs/16/release/vs_buildtools.exe C:\TEMP\vs_buildtools.exe

# Download vs installation channel
ADD https://aka.ms/vs/16/release/channel C:\TEMP\VisualStudio.chman

# Install Build Tools excluding workloads and components with known issues.
RUN C:\TEMP\install.cmd C:\TEMP\vs_buildtools.exe modify --quiet --wait --norestart --nocache `
    --installPath 'C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools' `
    --channelUri C:\TEMP\VisualStudio.chman `
    --installChannelUri C:\TEMP\VisualStudio.chman `
    --add Microsoft.VisualStudio.Workload.VCTools `
    --includeRecommended 
```
2. Setup/bootstrap vcpkg
```
# Install vcpkg
ADD https://github.com/microsoft/vcpkg/archive/2020.11.zip C:\TEMP\vcpkg.zip
RUN Expand-Archive 'C:\TEMP\vcpkg.zip' 'C:\TEMP\'
RUN mkdir C:\src\
RUN mv 'C:\TEMP\vcpkg-2020.11' 'C:\src\vcpkg\'
WORKDIR 'C:\src\vcpkg\'
RUN .\bootstrap-vcpkg.bat
```

**Expected behavior**
vcpkg bootstrap copmletes successfully.

**Failure logs** 
```
Building vcpkg.exe ...

& : The term 'C:\Program Files (x86)\Microsoft Visual
Studio\2019\TestAgent\MSBuild\Current\Bin\MSBuild.exe' is not recognized as
the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is
correct and try again.
At line:1 char:56
+ ... per.ps1"; & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Test ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program File...Bin\MSBuild.e
   xe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

C:\src\vcpkg\scripts\bootstrap.ps1 : Building vcpkg.exe failed. Please ensure
you have installed Visual Studio with the Desktop C++ workload and the Windows
SDK for Desktop C++.
At line:1 char:4
+ & {& 'C:\src\vcpkg\scripts\bootstrap.ps1' }
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorExcep
   tion
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorExceptio
   n,bootstrap.ps1
```

**Comment by PhoebeHui** [comment]
@DevsAnon, could you get vcpkg latest source and try again? it doesn't need to build vcpkg on windows, it will download the latest release version instead.

**Comment by DevsAnon** [comment]
I would say this kind of solved the above problem, but I am getting issues with installation of packages and builds failing. Should I maintain this issue or open new one?

**Comment by DevsAnon** [comment]
```
Building package abseil[core]:x64-windows... done
Installing package abseil[core]:x64-windows...
Installing package abseil[core]:x64-windows... done
Elapsed time for package abseil:x64-windows: 1.214 min
Starting package 2/14: abseil:x64-windows-static
Building package abseil[core]:x64-windows-static...
-- Downloading https://github.com/abseil/abseil-cpp/archive/997aaf3a28308eba1b9156aa35ab7bca9688e9f6.tar.gz -> abseil-abseil-cpp-997aaf3a28308eba1b9156aa35ab7bca9688e9f6.tar.gz...
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:170 (file):
  file DOWNLOAD cannot open file for write.
Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:147 (vcpkg_download_distfile)
  ports/abseil/portfile.cmake:5 (vcpkg_from_github)
  scripts/ports.cmake:142 (include)
```

This is the error I am receiving now

**Comment by strega-nil** [comment]
This container looks pretty broken, from what I can see, if `file(DOWNLOAD` can't open a file for writing

**Comment by DevsAnon** [comment]
But this is a docker build command not trying to run an already built image in a container. And all the code is in the dockerfile is stated above, except the vcppkg install command. In fact I run
```
RUN .\vcpkg install protobuf:x64-windows-static --clean-after-build --disable-metrics;
RUN .\vcpkg install spdlog:x64-windows-static --clean-after-build --disable-metrics;
```
One after the other. Could that be a the root cause?

**Comment by strega-nil** [comment]
@DevsAnon I'm not sure; the fact that it's failing at `file(DOWNLOAD` is really, really suspicious. @ras0219, @BillyONeal you have any ideas?

**Comment by BillyONeal** [comment]
Maybe the downloads directory is set somewhere to which the current user has no write permissions?

**Comment by DevsAnon** [comment]
I tried running 
```
RUN takeown /R /A /F 'C:\src\vcpkg' /D N;
RUN	icacls 'C:\src\vcpkg' /grant Everyone:F /T /C;
```
before running bootstrapper and install commands but still had the same outcome

**Comment by DevsAnon** [comment]
I don't understand why this require repro. With the image I posted and the steps I posted, this gets reproduced on demand by calling docker build.

**Comment by JackBoosY** [comment]
@DevsAnon Can you make sure you have enough permission in that directory?

**Comment by DevsAnon** [comment]
As I said earlier, I tried forcing access by adding these two commands 
```
RUN takeown /R /A /F 'C:\src\vcpkg' /D N;
RUN	icacls 'C:\src\vcpkg' /grant Everyone:F /T /C;
```

in my dockerfile and yet got the same result

**Comment by PhoebeHui** [comment]
@DevsAnon, does this issue repro if you only execute './vcpkg install abseil:x64-windows-static'? I noticed you have already  installed abseil[core]:x64-windows successfully, so it's strange for me.

**Comment by DevsAnon** [comment]
@PhoebeHui So I should try to only install abseil:x64 manually or install only that one?

**Comment by PhoebeHui** [comment]
Could you please try to install the failed port with by executing './vcpkg install abseil:x64-windows-static' and see if the issue persist?

**Comment by DevsAnon** [comment]
Running it alone was installed normally but if I put
```
RUN .\vcpkg install abseil:x64-windows-static --clean-after-build
RUN .\vcpkg install protobuf:x64-windows-static --clean-after-build
```
in my docker file, then it fails with the following error
```
Starting package 2/2: protobuf:x64-windows-static
Building package protobuf[core]:x64-windows-static...
-- Downloading https://github.com/protocolbuffers/protobuf/archive/2514f0bd7da7e2af1bed4c5d1b84f031c4d12c10.tar.gz -> protocolbuffers-protobuf-2514f0bd7da7e2af1bed4c5d1b84f031c4d12c10.tar.gz...
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:170 (file):
  file DOWNLOAD cannot open file for write.
Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:147 (vcpkg_download_distfile)
  ports/protobuf/portfile.cmake:1 (vcpkg_from_github)
  scripts/ports.cmake:142 (include)


Error: Building package protobuf:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: protobuf:x64-windows-static
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

Additionally, attach any relevant sections from the log files above.
```

extra info
```
Starting package 1/2: protobuf:x64-windows
Building package protobuf[core]:x64-windows...
```

Succeeds

**Comment by DevsAnon** [comment]
I am also using latest version of vcpkg directly from git as suggested earlier in order to resolve another issue

**Comment by DevsAnon** [comment]
Running without `--clean-after-build` flags succeeds.

**Comment by DevsAnon** [comment]
Next step in dockerfile
`RUN .\vcpkg install spdlog:x64-windows-static --clean-after-build`
failed with the same error. Executed again without the flag, and it succeeded. Not sure how that helps, but this is my flow. 
How repro and how to avoid

**Comment by PhoebeHui** [comment]
@DevsAnon, the "--clean-after-build" is used to cleaning buildtrees, packages and downloads after building each package, it may due to the flag in docker containner, I don't have docker environment, I just try to install the port with the flag, however, everything built successfully.

**Comment by DevsAnon** [comment]
How may I clean it after words though? just rm buildtrees?

**Comment by PhoebeHui** [comment]
If you don't need them, I think you can try it, but for downloads folder, please don't remove downloads\tools folder, since it contains tools which used to build the ports.

**Comment by DevsAnon** [comment]
I want to have a smaller image basically with only the stuff required in order to proceed. How about this?
```
rm buildtrees -Recurse -Force -ErrorAction Ignore; exit 0;
rm downloads\*.gz -Force -ErrorAction Ignore
rm downloads\*.zip -Force -ErrorAction Ignore
```

Will I be missing something vital?

**Comment by PhoebeHui** [comment]
You can also remove packages folder.

**Comment by DevsAnon** [comment]
Ok, so issue is not fully resolved (running with clean after build fails) but we have a workaround

**Comment by PhoebeHui** [comment]
Yes, however, we don't have docker related environment to confrim this issue now, so we're not sure if it's a problem for other users as well. We will keep this issue open.

**Comment by DevsAnon** [comment]
Just to be clear in order to help with your search. When using
`sdk:4.8-windowsservercore-1909 `
instead of 
`sdk:4.8-windowsservercore-20H2`
things go smoothly with everything

**Comment by PhoebeHui** [comment]
BTW, we would accept PRs for fixing this issue.

**Comment by JackBoosY** [comment]
Now we can directly download vcpkg binary instead of building vcpkg.
