### ISSUE TITLE
Buffer / pointer corruption?

### ISSUE THREAD

**Issue by OlafvdSpek** [Microsoft/vcpkg#1712]
```
PS C:\vc\vcpkg> ./vcpkg install libpng
The following packages will be built and installed:
    libpng:x86-windows
Building package libpng:x86-windows...
Expected dependency downloaded path to be C:\vc\vcpkg\downloads\MinGit-2.14.1-32-bit\cmd\git.exe, 
but was ├»┬╗┬┐C:\vc\vcpkg\downloads\MinGit-2.14.1-32-bit\cmd\git.exe

PS C:\vc\vcpkg> ./vcpkg install libpng
The following packages will be built and installed:
    libpng:x86-windows
Building package libpng:x86-windows...
Could not locate a complete toolset.
The following paths were examined:
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
    ├»┬╗┬┐C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat```

Windows 7 x64

**Comment by Mixaill** [comment]
Please check [utf-1702](https://github.com/Microsoft/vcpkg/tree/utf-1702) branch

**Comment by OlafvdSpek** [comment]
Why? Note it's not (just) a display issue and I don't have special characters in my paths.

```
PS C:\vc\vcpkg> git checkout utf-1702
Switched to a new branch 'utf-1702'
Branch utf-1702 set up to track remote branch utf-1702 from origin.

PS C:\vc\vcpkg> .\bootstrap-vcpkg.bat

...

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:53.08

PS C:\vc\vcpkg> ./vcpkg install libpng
The following packages will be built and installed:
    libpng:x86-windows
Building package libpng:x86-windows...
Could not locate a complete toolset.
The following paths were examined:
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
    ├â┬»├é┬╗├é┬┐C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat

PS C:\vc\vcpkg> git branch
  master
* utf-1702

PS C:\vc\vcpkg>
```

**Comment by name-name** [comment]
Same problem here - note that the other reported issue ([https://github.com/Microsoft/vcpkg/issues/1711](https://github.com/Microsoft/vcpkg/issues/1711)) might be related (I got the same thing).

**Comment by ras0219-msft** [comment]
I'm still not sure what the root cause is, but I've pushed (what I believe to be) a workaround to utf-1702 (commit id 5b42ec9b).

Could you try that commit and let me know if it suppresses the issue for now?

**Comment by OlafvdSpek** [comment]
```
PS C:\vc\vcpkg> git pull
Already up-to-date.

// bootstrap

PS C:\vc\vcpkg> ./vcpkg install ctemplate
The following packages will be built and installed:
    ctemplate:x86-windows
Building package ctemplate:x86-windows...
Could not locate a complete toolset.
The following paths were examined:
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
    ├»┬╗┬┐C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat
```

**Comment by name-name** [comment]
Hi, short version: it worked - kinda.. :-)

long version: I did a fresh checkout of that commit, the bootstrap (in which #1711 was visible again) and the very first package I tried to install gave me this (same as reported above #1712#issue-253153870)

> C:\Users\new\vcpkg>.\vcpkg install libuv
> The following packages will be built and installed:
>     libuv:x86-windows
> Building package libuv:x86-windows...
> Expected dependency downloaded path to be C:\Users\new\vcpkg\downloads\MinGit-2.
> 14.1-32-bit\cmd\git.exe, but was Ã¯Â»Â¿C:\Users\new\vcpkg\downloads\MinGit-2.14.
> 1-32-bit\cmd\git.exe

However, running the same line again works now and doesn't give me the same error as reported in the second message above (#1712#issuecomment-325193614).

So now I can install libraries again - thank you! :-)

**Comment by alexkaratarakis** [comment]
@OlafvdSpek @name-name 
I tried reproducing the issue in Russian Windows+VS but I wasn't able to. If you are able to provide me with the following info, I can try some more environments:

1) Windows version + locale
2) Visual Studio version(s) + language used
2) Output of `chcp`

In the meantime, the workaround (read: horrible hack) is checked-in to master so you can build.

**Comment by name-name** [comment]
Hi, 

as requested:
1) Windows 7 professional, service pack 1 + German as system language 
2) VS Community 2017, version 15.3.2 + languages: only English installed
3) output: Aktive Codepage: 850.

**Comment by OlafvdSpek** [comment]
1. English Windows 7 
2. English MSVC 15.3.3
3. Active code page: 437

**Comment by alexkaratarakis** [comment]
I have managed to reproduce this on Win7. Investigating...

**Comment by alexkaratarakis** [comment]
Found the issue: Windows 7's powershell adds a byte-order-mark at the beginning of the string.
Added a proper fix and removed the workaround. 

Thanks for the info @name-name @OlafvdSpek, the Windows 7 hint was key!
