### ISSUE TITLE
[spdlog] build failure when #include'ing header

### ISSUE THREAD

**Issue by ifexception** [microsoft/vcpkg#17134]
**Host Environment**
- OS: Windows
- Compiler: Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29913 for x64

**To Reproduce**
`./vcpkg install spdlog:x64-windows`
Create basic vcxproj project
Include spdlog
Build the solution

**Failure logs** 
> C:\Microsoft\vcpkg\installed\x64-windows\include\spdlog\fmt\chrono.h(17,10): fatal error C1083: Cannot open include file: 'spdlog/fmt/bundled/chrono.h': No such file or directory

**Additional context**
![image](https://user-images.githubusercontent.com/17222073/113912936-022c7780-97dc-11eb-8a55-657b5071580c.png)

vcpkg directory:
![image](https://user-images.githubusercontent.com/17222073/113912995-12445700-97dc-11eb-9dff-70b14d21a53d.png)

**Comment by NancyLi1013** [comment]
Hi @ifexception 

Thanks for posting this issue.

Since we have set `SPDLOG_FMT_EXTERNAL` as `ON`, we should use the header provided by external `fmt`.
So we can solve this problem with the same way as other headers.

```
vcpkg_replace_string(${CURRENT_PACKAGES_DIR}/include/spdlog/fmt/chrono.h
    "#if !defined(SPDLOG_FMT_EXTERNAL)"
    "#if 0 // !defined(SPDLOG_FMT_EXTERNAL)"
)
```
I will submit a PR to fix this soon.
