### ISSUE TITLE
cmake v3.20.0,  cmake --build --config Release does not function as required.

### ISSUE THREAD

**Issue by tom2068** [microsoft/vcpkg#17149]
**Describe the bug**
this command does not work properly as before:
cmake --build . -j --config Release -- -m -v:m

this command does work properly:
cmake --build . -j --config Release -- -p:Configuration=Release -m -v:m

There must be something wrong with CMAKE VERSION 3.20.0, I guess.

**Environment**
- OS: Windows
- Compiler: msvc 2019

**Comment by PhoebeHui** [comment]
@tom2068, could you report this issue to CMake instead? Or if you use cmake in VS, you can create a feedback tickets to VS.

BTW, I tried it with CMake latest release version 3.20.1, it looks worked.
E:\vcpkg\PhoebeHui\manifest\build>"C:\Program Files\CMake\bin\cmake.exe" --build . --config Release
Microsoft (R) Build Engine version 16.9.0+5e4b48a27 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  main.vcxproj -> E:\vcpkg\PhoebeHui\manifest\build\Release\main.exe
  Building Custom Rule E:/vcpkg/PhoebeHui/manifest/CMakeLists.txt

**Comment by tom2068** [comment]
PhoebeHui, Thank you very much! You are right!
