### ISSUE TITLE
Realsense2 vcpkg compatibalitiy

### ISSUE THREAD

**Issue by Yossarius** [microsoft/vcpkg#17144]
**Describe the bug**
I'm using realsense2 as in my QT project. It seems there is a version compatibality issue, the installaed packages are 32 bits and my system is 64 (didn't think it would be a problem). Also, the error specifies an empty requested version for some reason, maybe this is the issue!

**Environment**
- OS: Windows 10/64 bits
- Qt 5.15.2

**To Reproduce**
```
git clone https://github.com/Microsoft/vcpkg.git
cd vcpkg
bootstrap-vcpkg.sh
vcpkg integrate install
vcpkg install realsense2
```

in my project cmakelists: 
`find_package(realsense2 REQUIRED)`

**Failure logs** 

```
CMake Error at CMakeLists.txt:31 (find_package):
  Could not find a configuration file for package "realsense2" that is
  compatible with requested version "".

  The following configuration files were considered but not accepted:

    C:/realsense2/vcpkg/packages/realsense2_x86-windows/share/realsense2/realsense2Config.cmake, version: 2.42.0 (32bit)

```

**Additional context**
I have searched online for a 64-bit vcpkg version in case that is the issue, but couln't find one.

**Comment by autoantwort** [comment]
Use `vcpkg install realsense2:x64-windows` to install the 64 bit version

**Comment by Yossarius** [comment]
Yup. That was the issue. I removed the package and reinstalled the 64 bit version. Worked without any issues. Thank you very much

**Comment by autoantwort** [comment]
@Yossarius Maybe we should update the documentation?
