### ISSUE TITLE
[New Port Request] D3D12MemAlloc

### ISSUE THREAD

**Issue by DethRaid** [microsoft/vcpkg#17157]
Library name: D3D12 Memory Allocator

Library description: Simple-to-use GPU memory allocator for the D3D12 GPU API

Source repository URL: https://github.com/GPUOpen-LibrariesAndSDKs/D3D12MemoryAllocator/

Project homepage (if different from the source repository): https://gpuopen.com/d3d12-memory-allocator/

Anything else that is useful to know when adding (such as optional features the library may have that should be included): Nothing else I'm aware of

**Comment by DethRaid** [comment]
I copied `src/D3D12MemAlloc.h` and `src/D3D12MemAlloc.cpp` into my build tree and added them to my VS solution

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
