### ISSUE TITLE
[New Port Request] <aricpp>

### ISSUE THREAD

**Issue by daniele77** [microsoft/vcpkg#17162]
Library name: aricpp

Library description: Asterisk ARI interface bindings for modern C++

Source repository URL: https://github.com/daniele77/aricpp

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by daniele77** [comment]
So you didn't add the library?
What was wrong with my request? 
Should I do a PR instead of open an issue to add a library?

**Comment by PhoebeHui** [comment]
@daniele77, we can reopen this issue if you have a PR for this, none of our core team is very familiar with aricpp, we're happy to answer any questions we can to support this effort, but for now we'd prefer to support you or other contributors than to take ownership ourselves.

**Comment by daniele77** [comment]
@PhoebeHui ok, so the workflow to have a library added to vcpkg is:

1. open an issue
2. send a PR

right?
I'm afraid it's not very clear. In CONTRIBUTING.md it's not clearly stated which steps a developer should do to add a new package.

Anyway, I'm gonna submit a PR and ask to reopen the issue.

Thank you!

**Comment by PhoebeHui** [comment]
@daniele77, right, thanks your contribution!

**Comment by daniele77** [comment]
PR #18048
Please, reopen the issue.
Thanks
