### ISSUE TITLE
[live555] build failure

### ISSUE THREAD

**Issue by moonyl** [microsoft/vcpkg#17165]
**Host Environment**
- OS: [Windows]
- Compiler: MSVC 19.16.27045

**To Reproduce**
`./vcpkg install live555 --head`

**Failure logs** 
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/6282509/install-x64-windows-dbg-out.log)

**Additional context**
none

**Comment by JackBoosY** [comment]
```
F:\dev-tool\vcpkg-report\buildtrees\live555\src\555-latest-775e7a0b73.clean\groupsock\GroupsockHelper.cpp(46): fatal error C1083: Cannot open include file: 'ifaddrs.h': No such file or directory
```

**Comment by ahugeat** [comment]
I have the same issue but have found a [stackoverflow thread](https://stackoverflow.com/questions/66673249/fatal-error-c1083-cannot-open-include-file-ifaddrs-h-no-such-file-or-direct) 
Add this condition 
```cmake
if (WIN32)
    add_definitions(-DNO_GETIFADDRS)
endif(WIN32)
```
Fix the issue but I am not familiar with live555 and Windows API so I don't kown if it's best way to fix the build

**Comment by roalz** [comment]
I patched the live555 CMakeLists.txt as described, but then I get this other compile error:

C:\Project\_tools\vcpkg\buildtrees\live555\src\555-latest-9b8fcaac25.clean\groupsock\GroupsockHelper.cpp(183): error C2664: 'int setsockopt(SOCKET,int,int,const char *,int)': cannot convert argument 4 from 'const int *' to 'const char *'
