### ISSUE TITLE
find_package(Boost ...) does not find the vcpkg boost version

### ISSUE THREAD

**Issue by autoantwort** [microsoft/vcpkg#17163]
**Describe the bug**
I use 
```cmake
    find_package(Boost REQUIRED COMPONENTS thread context coroutine)
    target_link_libraries(lichtsteuerung ${Boost_LIBRARIES})
    target_include_directories(lichtsteuerung PRIVATE ${Boost_INCLUDE_DIRS})
```
to use boost in [my project](https://git.rwth-aachen.de/leander.schulten/Lichtsteuerung/-/blob/feature/cmake-pipeline/src/CMakeLists.txt#L142), but it finds the following:
```
-- Found Boost: /usr/src/mxe/usr/x86_64-w64-mingw32.shared.posix/include (found version "1.60.0") found components: thread context coroutine chrono system date_time atomic 
```

**Environment**
- OS: linux ( -> windows crosscompile)
- Compiler: mingw 
- [Dockerfile](https://git.rwth-aachen.de/leander.schulten/Lichtsteuerung/-/blob/feature/cmake-pipeline/Dockerfile)

**To Reproduce**
Steps to reproduce the behavior: (from gitlab.ci)
git submodule update --init --recursive

    - rm -rf vcpkg/packages vcpkg/buildtrees
    - CC=/usr/bin/gcc
    - CXX=/usr/bin/g++
    - export VCPKG_BINARY_SOURCES="clear;files,$CI_PROJECT_DIR/vcpkg_cache,readwrite"
    - ./vcpkg/bootstrap-vcpkg.sh
    - cp x64-linux-windows-static.cmake ./vcpkg/triplets/community
    - mkdir -p build
    - cd build
    - cmake -G Ninja .. -DVCPKG_TARGET_TRIPLET=x64-linux-windows-static
    - ninja

**Expected behavior**

`find_package(Boost ...)` should find the vcpkg version of boost

**Additional context**
You find the project with the CMakeList.txt files [here](https://git.rwth-aachen.de/leander.schulten/Lichtsteuerung/-/tree/feature/cmake-pipeline)  
You find the build log [here](https://git.rwth-aachen.de/leander.schulten/Lichtsteuerung/-/jobs/1593099#L352)

**Comment by PhoebeHui** [comment]
@autoantwort, it looks boost was installed to mingw locally, It may cause this issue, I'm not sure, could you be able to remove it and try again?

**Comment by autoantwort** [comment]
> it looks boost was installed to mingw locally

No, boost was installed to vcpkg_installed, that worked. (And the vcpkg boost version is 1.75.0 and not 1.60.0)

**Comment by autoantwort** [comment]
When I change the line to the following
```cmake
find_package(Boost 1.75.0 REQUIRED COMPONENTS thread context coroutine)
```
I get the error:
```
CMake Error at /usr/src/mxe/usr/x86_64-pc-linux-gnu/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
  Could NOT find Boost: Found unsuitable version "1.60.0", but required is at
  least "1.75.0" (found
  /usr/src/mxe/usr/x86_64-w64-mingw32.shared.posix/include, found components:
  thread context coroutine chrono system date_time atomic)
Call Stack (most recent call first):
  /usr/src/mxe/usr/x86_64-pc-linux-gnu/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:580 (_FPHSA_FAILURE_MESSAGE)
  /usr/src/mxe/usr/x86_64-pc-linux-gnu/share/cmake-3.19/Modules/FindBoost.cmake:2193 (find_package_handle_standard_args)
  vcpkg/scripts/buildsystems/vcpkg.cmake:828 (_find_package)
  src/CMakeLists.txt:139 (find_package)
```

**Comment by autoantwort** [comment]
If I do
```cmake
set(BOOST_ROOT ${_VCPKG_INSTALLED_DIR})
set(Boost_DIR ${_VCPKG_INSTALLED_DIR})
set(Boost_NO_SYSTEM_PATHS ON)
find_package(Boost 1.75.0 REQUIRED COMPONENTS thread context coroutine PATHS ${_VCPKG_INSTALLED_DIR})
```
 I get 
```
CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:828 (_find_package):
  Could not find a package configuration file provided by "Boost" (requested
  version 1.75.0) with any of the following names:
    BoostConfig.cmake
    boost-config.cmake
  Add the installation prefix of "Boost" to CMAKE_PREFIX_PATH or set
  "Boost_DIR" to a directory containing one of the above files.  If "Boost"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  src/CMakeLists.txt:142 (find_package)
```

**Comment by autoantwort** [comment]
The only thing that "worked" is not using `find_package(Boost ...)` and linking the libs directly 
```cmake
target_link_libraries(lichtsteuerung "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/lib/libboost_thread.a;${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/lib/libboost_context.a;${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/lib/libboost_coroutine.a;${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/lib/libboost_chrono.a;${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/lib/libboost_date_time.a;${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/lib/libboost_atomic.a")
target_include_directories(lichtsteuerung PRIVATE "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include")
```

**Comment by PhoebeHui** [comment]
@autoantwort, does boost was installed as optional part of mingw locally? I'm not sure, it looks boost 1.60.0 was installed locally.

**Comment by longnguyen2004** [comment]
Do we have a CMake wrapper for boost in vcpkg?

**Comment by longnguyen2004** [comment]
> Call Stack (most recent call first):
  /usr/src/mxe/usr/x86_64-pc-linux-gnu/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:580 (_FPHSA_FAILURE_MESSAGE)
  /usr/src/mxe/usr/x86_64-pc-linux-gnu/share/cmake-3.19/Modules/FindBoost.cmake:2193 (find_package_handle_standard_args)
  vcpkg/scripts/buildsystems/vcpkg.cmake:828 (_find_package)
  src/CMakeLists.txt:139 (find_package)

CMake is prioritizing `FindBoost.cmake` in your MXE installation.

**Comment by autoantwort** [comment]
> @autoantwort, does boost was installed as optional part of mingw locally? I'm not sure, it looks boost 1.60.0 was installed locally.

Maybe as a dependency, but I have not requested it.

**Comment by autoantwort** [comment]
> CMake is prioritizing `FindBoost.cmake` in your MXE installation.

Is there a way to change it?

**Comment by longnguyen2004** [comment]
Maybe have a look at the toolchain file, and see where the extra module dir is injected?

**Comment by autoantwort** [comment]
> Maybe have a look at the toolchain file, and see where the extra module dir is injected?

[here](https://github.com/mxe/mxe/blob/master/src/cmake/conf/mxe-conf.cmake.in) is the toolchain file, it adds a module path. But afaics only to [this](https://github.com/mxe/mxe/tree/master/src/cmake/modules) dir

**Comment by longnguyen2004** [comment]
https://github.com/mxe/mxe/blob/34a1eb775764cf8a35cff15dae26fffdcfe4240b/src/cmake/conf/mxe-conf.cmake.in#L71
Try removing this line.

**Comment by longnguyen2004** [comment]
Also, you should try ignoring the MXE toolchain file and just use the vcpkg toolchain file. Simply add the compiler path into PATH and it should work.

**Comment by autoantwort** [comment]
Ok i will try this. I will also try to use the default cmake executable and not cmake from mxe

**Comment by autoantwort** [comment]
> Also, you should try ignoring the MXE toolchain file and just use the vcpkg toolchain file. Simply add the compiler path into PATH and it should work.

I have tried it, but then Qt is not found (I have installed Qt with mxe):
```
CMake Error at CMakeLists.txt:28 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.
  Could not find a package configuration file provided by "Qt5" with any of
  the following names:
    Qt5Config.cmake
    qt5-config.cmake
  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.
-- Configuring incomplete, errors occurred!
```

**Comment by autoantwort** [comment]
I have found a "solution" after hours! Or workaround is better...  
When I add the following to my CMakeLists.txt is works:
```cmake
list(POP_FRONT CMAKE_FIND_ROOT_PATH) # /usr/src/mxe/usr/x86_64-w64-mingw32.shared.posix is the first entry
list(APPEND CMAKE_FIND_ROOT_PATH /usr/src/mxe/usr/x86_64-w64-mingw32.shared.posix)
```
But why findBoost exists after the first wrong match and does not continue searching?

**Comment by longnguyen2004** [comment]
Maybe you can take a look at MXE's `FindBoost.cmake`. Maybe it prioritizes the MXE installation, and terminates after it founds a library.
> I have tried it, but then Qt is not found (I have installed Qt with mxe):

That's to be expected, since you're skipping the custom MXE modules.
Maybe we should add mingw support to the Qt port? 😊

**Comment by autoantwort** [comment]
> Maybe you can take a look at MXE's FindBoost.cmake

It is the default `FindBoost.cmake` file provided by cmake in the folder `/usr/src/mxe/usr/x86_64-pc-linux-gnu/share/cmake-3.19/Modules`. It is a normal cmake installation. 

> Maybe we should add mingw support to the Qt port?

I tried it 2 months ago, but there were too many build error. But now with host dependencies and after #17073 it maybe works.

**Comment by Neumann-A** [comment]
```
set(BOOST_ROOT ${_VCPKG_INSTALLED_DIR})
#set(Boost_DIR ${_VCPKG_INSTALLED_DIR}) # don't set this one. 
set(Boost_NO_SYSTEM_PATHS ON)
set(Boost_NO_BOOST_CMAKE  ON) # additional set this one
```

**Comment by autoantwort** [comment]
@Neumann-A With these lines:
```
CMake Error at /usr/src/mxe/usr/x86_64-pc-linux-gnu/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
  Could NOT find Boost: Found unsuitable version "1.60.0", but required is at
  least "1.75.0" (found
  /usr/src/mxe/usr/x86_64-w64-mingw32.shared.posix/include, found components:
  thread context coroutine chrono system date_time atomic)
Call Stack (most recent call first):
  /usr/src/mxe/usr/x86_64-pc-linux-gnu/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:580 (_FPHSA_FAILURE_MESSAGE)
  /usr/src/mxe/usr/x86_64-pc-linux-gnu/share/cmake-3.19/Modules/FindBoost.cmake:2193 (find_package_handle_standard_args)
  vcpkg/scripts/buildsystems/vcpkg.cmake:828 (_find_package)
  src/CMakeLists.txt:134 (find_package)
-- Configuring incomplete, errors occurred!
```

**Comment by Neumann-A** [comment]
@autoantwort  a yeah forgot it needs to be:
`set(BOOST_ROOT ${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET})`

it is different from `CURRENT_INSTALLED_DIR` in the toolchain

**Comment by autoantwort** [comment]
Still the same error :(

**Comment by Neumann-A** [comment]
If additionally setting:
`set(BOOST_INCLUDEDIR "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include")`
does not help you want to run configure with `--trace/--trace-expand` and debug the `FindBoost.cmake` to figure out what is happening

**Comment by autoantwort** [comment]
> does not help you want to run configure with `--trace` and debug the `FindBoost.cmake` to figure out what is happening

`Job's log exceeded limit of 4194304 bytes.`  
RIP 😒

**Comment by autoantwort** [comment]
I have found out that you can se `set(Boost_DEBUG ON)` to get debugging output. But WTF!?:
```
-- [ /usr/src/mxe/usr/x86_64-pc-linux-gnu/share/cmake-3.19/Modules/FindBoost.cmake:1621 ] _boost_INCLUDE_SEARCH_DIRS = "/builds/leander.schulten/Lichtsteuerung/build/vcpkg_installed/x64-linux-windows-static/include;/builds/leander.schulten/Lichtsteuerung/build/vcpkg_installed/x64-linux-windows-static/include;/builds/leander.schulten/Lichtsteuerung/build/vcpkg_installed/x64-linux-windows-static;NO_CMAKE_SYSTEM_PATH;NO_SYSTEM_ENVIRONMENT_PATH"
-- [ /usr/src/mxe/usr/x86_64-pc-linux-gnu/share/cmake-3.19/Modules/FindBoost.cmake:1622 ] _boost_PATH_SUFFIXES = <unset>
-- [ /usr/src/mxe/usr/x86_64-pc-linux-gnu/share/cmake-3.19/Modules/FindBoost.cmake:1637 ] location of version.hpp: /usr/src/mxe/usr/x86_64-w64-mingw32.shared.posix/include/boost/version.hpp
```
So `_boost_INCLUDE_SEARCH_DIRS` is `/builds/leander.schulten/Lichtsteuerung/build/vcpkg_installed/x64-linux-windows-static/include;/builds/leander.schulten/Lichtsteuerung/build/vcpkg_installed/x64-linux-windows-static/include;/builds/leander.schulten/Lichtsteuerung/build/vcpkg_installed/x64-linux-windows-static;NO_CMAKE_SYSTEM_PATH;NO_SYSTEM_ENVIRONMENT_PATH` looks good.
Then the following is called:
```cmake
  find_path(Boost_INCLUDE_DIR
    NAMES         boost/config.hpp
    HINTS         ${_boost_INCLUDE_SEARCH_DIRS}
    PATH_SUFFIXES ${_boost_PATH_SUFFIXES}
    )
```
And the result is `Boost_INCLUDE_DIR` = `/usr/src/mxe/usr/x86_64-w64-mingw32.shared.posix/include/`.  
Are they kidding me? 😅

**Comment by autoantwort** [comment]
Ok seems like that the `HINTS` are checked after the default paths... - therefore the result. 
When I manually patch the FindBoost.cmake file to
```cmake
  find_path(Boost_INCLUDE_DIR
    NAMES         boost/config.hpp
    HINTS         ${_boost_INCLUDE_SEARCH_DIRS}
    PATH_SUFFIXES ${_boost_PATH_SUFFIXES}
    NO_DEFAULT_PATH
    )
```
it finds the right version (`NO_DEFAULT_PATH` added (`NO_CMAKE_PATH` also seems to work)). Adding `NO_CMAKE_FIND_ROOT_PATH` does not work.
 
 But I don't want to manually patch FindBoost to use it correctly, but it seems that FindBoost always selects the first found installation. And the vcpkg installation is behind the toolchains one in the `CMAKE_FIND_ROOT_PATH` list. So I see no other solution than #17336

**Comment by cenit** [comment]
you're not passing vcpkg toolchain to your cmake command!

**Comment by autoantwort** [comment]
> you're not passing vcpkg toolchain to your cmake command!

But I do it in my [CMakeLists.txt](https://git.rwth-aachen.de/leander.schulten/Lichtsteuerung/-/blob/feature/test-boost/CMakeLists.txt)

**Comment by longnguyen2004** [comment]
Anyway, now we know the cause, which is CMake prioritizing the local installation, because the vcpkg path is appended, not prepended to CMake root path. Now we have 2 options:
1. Prepend instead of append (easy, might cause other problems)
2. Use [`boost_install`](https://github.com/boostorg/boost_install), which will generate a CMake config file when building boost (medium/hard? but in my opinion the best solution)
