### ISSUE TITLE
Install grpc error : Could not find a package configuration file provided by "modules" 

### ISSUE THREAD

**Issue by DachuanZhao** [microsoft/vcpkg#17177]
**Host Environment**
- OS: wsl2 ubuntu20.04
- Compiler: gcc9

**To Reproduce**
`./vcpkg install grpc`

**Failure logs** 
Install successfully :
```
...
The package grpc:x64-linux provides CMake targets:

    find_package(gRPC CONFIG REQUIRED)
    # Note: 7 target(s) were omitted.
    target_link_libraries(main PRIVATE gRPC::gpr gRPC::grpc gRPC::grpc++ gRPC::grpc++_alts)

    find_package(modules CONFIG REQUIRED)
    target_link_libraries(main PRIVATE re2::re2 c-ares::cares)
```

**Additional context**
I add ```find_package(modules CONFIG REQUIRED)``` to CMakeLists.txt , I raise error : 
```
[main] Configuring folder: test 
[proc] Executing command: /usr/bin/cmake --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_C_COMPILER:FILEPATH=/bin/gcc-9 -DCMAKE_CXX_COMPILER:FILEPATH=/bin/g++-9 -H/home/zhaodachuan/test -B/home/zhaodachuan/test/build -G "Unix Makefiles"
[cmake] Not searching for unused variables given on the command line.
[cmake] /home/zhaodachuan/test/vcpkg/scripts/buildsystems/vcpkg.cmake
[cmake] -- Found RE2 via CMake.
[cmake] CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:857 (_find_package):
[cmake]   Could not find a package configuration file provided by "modules" with any
[cmake]   of the following names:
[cmake] 
[cmake]     modulesConfig.cmake
[cmake]     modules-config.cmake
[cmake] 
[cmake]   Add the installation prefix of "modules" to CMAKE_PREFIX_PATH or set
[cmake]   "modules_DIR" to a directory containing one of the above files.  If
[cmake]   "modules" provides a separate development package or SDK, be sure it has
[cmake]   been installed.
[cmake] Call Stack (most recent call first):
[cmake]   CMakeLists.txt:26 (find_package)
[cmake] 
[cmake] 
[cmake] -- Configuring incomplete, errors occurred!
```

**Comment by Tradias** [comment]
Possible workaround: Replace the call to `find_package(module CONFIG REQUIRED)` with `find_package(protobuf)` then you can use functions like `protobuf_generate_cpp` within the same directory.

**Comment by Tradias** [comment]
I think I didn't fully understand the initial problem, but I hope that I can clear things up.

If you just intend on using gRPC after installing it with vcpkg then the following will do:

```cmake
find_package(gRPC CONFIG REQUIRED)
add_executable(my_app main.cpp)
target_link_libraries(my_app PRIVATE gRPC::grpc++)
```

in other words, simply ignore `find_package(modules CONFIG REQUIRED)`. Why does that work? Looking at `<vcpkg_root>\packages\grpc_x64-windows-static\share\grpc\gRPCTargets.cmake` you will see that it declares `re2::re2` and `c-ares::cares` as `INTERFACE_LINK_LIBRARIES` which means anything that links with `gRPC::grpc++` will also link with those. Additionally, in `<vcpkg_root>\packages\grpc_x64-windows-static\share\grpc\gRPCConfig.cmake` you can see the calls to `find_package(re2)` and `find_package(c-ares)` which take care of making those packages available.

If you want to use re2 or c-ares directly then I recommend that you `vcpkg install re2` (or even better add it to your [manifest file](https://github.com/microsoft/vcpkg/blob/master/docs/users/manifests.md)) and:

```cmake
find_package(re2 CONFIG REQUIRED)
target_link_libraries(my_app PRIVATE re2::re2)
```

Now my thought was that you want to use [protobuf_generate_cpp](https://cmake.org/cmake/help/latest/module/FindProtobuf.html) in which case `find_package(gRPC CONFIG REQUIRED)` will be enough to make it available in the current directory. No need to `find_package(protobuf)` as I initially thought.

The source of confusion for vcpkg regarding `find_package(modules CONFIG REQUIRED)` seems to come from the subdirectory called `modules` in `<vcpkg_root>\packages\grpc_x64-windows-static\share\grpc\` which contains `Findre2.cmake` and `Findc-ares.cmake`. I suspect that modifying gRPC's portfile (`<vcpkg_root>/ports\grpc`) by adding `file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/share/grpc/modules)` and patching the `gRPCConfig.cmake` file to remove the `list(APPEND CMAKE_MODULE_PATH ${CMAKE_CURRENT_LIST_DIR}/modules)` from it should remove the message. I know that @JonLiu1993 is working on updating the gRPC port at the moment, so I wouldn't want to interfere for now.

**Comment by NangiDev** [comment]
Thanks for the  explanation! It makes more sense now.
I tried setting it up on a windows machine instead and it almost works. 

My generated protos files has a hard time finding PROTOBUF_NAMESPACE_OPEN inside google/protobuf folder.
It says ``this declaration has no storage class or type specifier``

**Comment by Tradias** [comment]
I haven't seen that error before but here is what I would try

* Make sure you are using the most recent vcpkg version. E.g. if you have cloned it then 
```shell
cd <vcpkg_root>
git checkout master
git pull
./bootstrap-vcpkg.bat
./vcpkg install grpc
```
* Make sure that the proto files were generated with the same version of protobuf that you are linking with. If you are using [protobuf_generate_cpp](https://cmake.org/cmake/help/latest/module/FindProtobuf.html#command:protobuf_generate_cpp) then that should be taken care of though. If you are looking for the `protoc.exe` it will be in `<vcpkg_root>\packages\protobuf_x64-windows\tools\protobuf\`

On my Windows machine it works fine using MSVC and clang-cl and using the `windows-x64` and `windows-x64-static` vcpkg triplet. So keep trying!

**Comment by Tradias** [comment]
@NangiDev did you have time to test my example and if so can you say what the problem was? I am asking because other people that stumble across this issue might find it helpful to know :)

**Comment by NangiDev** [comment]
Hey @Tradias
I am sorry I havn't had time.
We found a completelly different solution that is not related to this discussion at all, but I will try this at home as soon as possible for completeness of the discussion :)

**Comment by PhoebeHui** [comment]
This wrong information had been fixed now with latest vcpkg.

```
Installing 11/11 grpc:x64-linux...
Building grpc[codegen,core]:x64-linux...
-- Downloading https://github.com/grpc/grpc/archive/v1.51.1.tar.gz -> grpc-grpc-v1.51.1.tar.gz...
-- Extracting source /data/phoebe/vcpkg/downloads/grpc-grpc-v1.51.1.tar.gz
-- Applying patch 00001-fix-uwp.patch
-- Applying patch 00002-static-linking-in-linux.patch
-- Applying patch 00003-undef-base64-macro.patch
-- Applying patch 00004-link-gdi32-on-windows.patch
-- Applying patch 00005-fix-uwp-error.patch
-- Applying patch 00009-use-system-upb.patch
-- Applying patch snprintf.patch
-- Applying patch 00012-fix-use-cxx17.patch
-- Applying patch 00014-pkgconfig-upbdefs.patch
-- Applying patch 00015-disable-download-archive.patch
-- Using source at /data/phoebe/vcpkg/buildtrees/grpc/src/v1.51.1-1066d25324.clean
-- Configuring x64-linux
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Fixing pkgconfig file: /data/phoebe/vcpkg/packages/grpc_x64-linux/lib/pkgconfig/gpr.pc
-- Fixing pkgconfig file: /data/phoebe/vcpkg/packages/grpc_x64-linux/lib/pkgconfig/grpc++.pc
-- Fixing pkgconfig file: /data/phoebe/vcpkg/packages/grpc_x64-linux/lib/pkgconfig/grpc++_unsecure.pc
-- Fixing pkgconfig file: /data/phoebe/vcpkg/packages/grpc_x64-linux/lib/pkgconfig/grpc.pc
-- Fixing pkgconfig file: /data/phoebe/vcpkg/packages/grpc_x64-linux/lib/pkgconfig/grpc_unsecure.pc
-- Fixing pkgconfig file: /data/phoebe/vcpkg/packages/grpc_x64-linux/debug/lib/pkgconfig/gpr.pc
-- Fixing pkgconfig file: /data/phoebe/vcpkg/packages/grpc_x64-linux/debug/lib/pkgconfig/grpc++.pc
-- Fixing pkgconfig file: /data/phoebe/vcpkg/packages/grpc_x64-linux/debug/lib/pkgconfig/grpc++_unsecure.pc
-- Fixing pkgconfig file: /data/phoebe/vcpkg/packages/grpc_x64-linux/debug/lib/pkgconfig/grpc.pc
-- Fixing pkgconfig file: /data/phoebe/vcpkg/packages/grpc_x64-linux/debug/lib/pkgconfig/grpc_unsecure.pc
-- Installing: /data/phoebe/vcpkg/packages/grpc_x64-linux/share/grpc/copyright
-- Performing post-build validation
Stored binaries in 1 destinations.
Elapsed time to handle grpc:x64-linux: 10 min
Total install time: 11 min
grpc provides CMake targets:

    # this is heuristically generated, and may not be correct
    find_package(gRPC CONFIG REQUIRED)
    # note: 7 additional targets are not displayed.
    target_link_libraries(main PRIVATE gRPC::gpr gRPC::grpc gRPC::grpc++ gRPC::grpc++_alts)

```
