### ISSUE TITLE
How do I configure OpenSSL package?

### ISSUE THREAD

**Issue by Fedr** [microsoft/vcpkg#17183]
In the latest OpenSSL package for Linux, one can find in opensslconf.h among other things:

    #ifndef OPENSSL_NO_BF
    # define OPENSSL_NO_BF
    #endif

This effectively removes Blowfish encoding functions from the library. Can some option be added for us to reenable them somehow in the package?
Why Blowfish was removed only from Linux build and not from Windows?

**Comment by NancyLi1013** [comment]
Hi @Fedr 

Thanks for posting this issue.

Could you please try to rebuild openssl according to PR #16937 and confirm if it is the same problem as current version?

**Comment by Fedr** [comment]
Hello,
I have checked the PR and it does not change anything related to this question. Still Blowfish is enabled in Windows build and disabled in Linux build, and I do not see a way how to reenable it.

**Comment by NancyLi1013** [comment]
@Neumann-A 
Could you please help take a look?

**Comment by NancyLi1013** [comment]
@Fedr 
Please update to the latest vcpkg to rebuild `openssl`. `Blowfish `has been restored on Unix.
