### ISSUE TITLE
Error: Building package qt5-base:x64-linux failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by lulou** [microsoft/vcpkg#17189]
**Describe the bug**
Compiling qt5-base throws the error
ERROR: Feature 'xcb' was enabled, but the pre-condition 'features.thread && libs.xcb && tests.xcb_syslibs && features.xkbcommon-x11' failed.
in 
./vcpkg/buildtrees/qt5-base/config-x64-linux-dbg-err.log
tried running
sudo apt install libxkbcommon-x11-dev
then reinstalling did not solve the problem

**Environment**
Operating System: Debian GNU/Linux 10 (buster)
Kernel: Linux 4.19.0-14-amd64
Architecture: x86-64
gcc (Debian 8.3.0-6) 8.3.0
 Package: qt5-base:x64-linux
 Vcpkg version: 2021-01-13-unknownhash

**To Reproduce**
./vcpkg install qt5-base qt5-svg qt5-tools grpc boost-accumulators opus poco libvorbis libogg libflac libsndfile libmariadb zlib

**Expected behavior**
It should build qt.
[config-x64-linux-dbg-err.log](https://github.com/microsoft/vcpkg/files/6288711/config-x64-linux-dbg-err.log)

**Failure logs** 
-(please attached failure logs)

**Additional context**

**Comment by Neumann-A** [comment]
> ERROR: Feature 'xcb' was enabled, but the pre-condition 'features.thread && libs.xcb && tests.xcb_syslibs && features.xkbcommon-x11' failed.


Missing system libs.  Please check:
https://github.com/microsoft/vcpkg/blob/master/scripts/azure-pipelines/linux/provision-image.sh

**Comment by lulou** [comment]
indeed, running the below apt commands solved my issue.
apt install libxext-dev libxfixes-dev libxrender-dev libxcb1-dev libx11-xcb-dev libxcb-glx0-dev libxcb-util0-dev
apt install libxkbcommon-dev libxcb-keysyms1-dev libxcb-image0-dev libxcb-shm0-dev libxcb-icccm4-dev libxcb-sync0-dev libxcb-xfixes0-dev libxcb-shape0-dev libxcb-randr0-dev libxcb-render-util0-dev libxcb-xinerama0-dev libxcb-xkb-dev libxcb-xinput-dev

would be great if there is a notification somewhere that recommends running apt installations after building vcpkg.

**Comment by autoantwort** [comment]
> would be great if there is a notification somewhere that recommends running apt installations after building vcpkg.

You get this when #16280 gets merged
