### ISSUE TITLE
[drogon:x64-windows-static] build failure (v1.4.1)

### ISSUE THREAD

**Issue by O-Tom** [microsoft/vcpkg#17192]
**Host Environment**
- OS: Windows 10 build 1607
- Compiler: Visual C++ 2017 00370-20001-21499-AA108 / VisualStudio.15.Release/15.9.29+28307.1300
- Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

**To Reproduce**
`./vcpkg install drogon --triplet=x64-windows-static`

**Failure logs** 
[install-x64-windows-static-dbg-out.log](https://github.com/microsoft/vcpkg/files/6289432/install-x64-windows-static-dbg-out.log)

**Additional context**
Port dependencies compile and install without any trouble
It looks like drogon is also almost successful and only fails at linking the `drogon_ctl.exe` tool
`x64-windows` triplet installs fine on the same machine/same configuration

**Comment by O-Tom** [comment]
Well, this issue is actually a duplicate of https://github.com/an-tao/drogon/issues/510

As I also found out, the `[c-ares:w64-windows-static]` port does not switch the source to static mode correctly.
The portfile.cmake should be modified to define `CARES_STATICLIB`, not `CARES_STATIC` or `CARES_SHARED` that are unknown to the current c-ares code.
I modified my local copy of the port with the following code and solved the c-ares missing symbols issues.
```
set(OPTIONS)
if(VCPKG_LIBRARY_LINKAGE STREQUAL static)
    list(APPEND OPTIONS -DCARES_STATICLIB=1)
endif()

vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA
    OPTIONS
        ${OPTIONS}
)
```

**Drogon still fails on libpq.lib though**
[install-x64-windows-static-dbg-out.log](https://github.com/microsoft/vcpkg/files/6291292/install-x64-windows-static-dbg-out.log)

**Comment by O-Tom** [comment]
Digging a little more around libpq, I found https://github.com/jtv/libpqxx/issues/431 then https://github.com/microsoft/vcpkg/issues/16968
These really look like the same issue and may fix drogon along with the c-ares patch.

**Comment by JackBoosY** [comment]
Confirmed.

**Comment by O-Tom** [comment]
Sorry @JackBoosY, but I was wrong with `c-ares`, as the actual problem is in the `trantor` makefiles.
`trantor` includes `c-ares` headers but does not define `CARES_STATICLIB` when it is itself in static mode.
The `trantor` static lib is therefore linked to shared definitions of `c-ares` functions that are not satisfied by the static version of `c-ares`.
This is what the `drogon` fail log was telling in a first place...

I created the following patch for the `trantor` port and applied it in my local copy of vcpkg.
Not only did this solve the `drogon` port build failure but it also solved linking issues in `drogon` dependant executables

[c-ares_static.patch for trantor](https://github.com/microsoft/vcpkg/files/6295677/c-ares_static.patch.txt)

![c-ares_static patch](https://user-images.githubusercontent.com/6274985/114376496-f6e39e00-9b85-11eb-842f-eb26250d4cf4.png)

**Comment by JackBoosY** [comment]
@O-Tom #17230 and #17232 will fix this issue.

**Comment by Coderx7** [comment]
When will this be merged? I noticed its been 13 days already and seemingly all is fine

**Comment by JackBoosY** [comment]
Should be fixed.
