### ISSUE TITLE
Matio cmake error after upgrading to cmake 3.9

### ISSUE THREAD

**Issue by cjvaijo** [Microsoft/vcpkg#1722]
It seems matio fails to build after cmake has been upgraded to 3.9. All dependent libs build fine. I get the following output and logs:

Error: Building package matio:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: matio:x86-windows
  Vcpkg version: 0.0.85-2017-08-27-8a79566c645e4b2862d7b094d2e2c4a1fd889b7f

config-x86-windows-rel-err.txt:
CMake Error at C:/Program Files/CMake/share/cmake-3.9/Modules/FindHDF5.cmake:450 (get_target_property):
  get_target_property called with incorrect number of arguments
Call Stack (most recent call first):
  D:/WorkingFolder/git/vcpkg/scripts/buildsystems/vcpkg.cmake:145 (_find_package)
  CMakeLists.txt:33 (find_package)

**Comment by albertziegenhagel** [comment]
You can try to edit the portfile and pass `-DHDF5_NO_FIND_PACKAGE_CONFIG_FILE=ON` to the CMake configure command.

See #1572 for a similar issue. This problem should be fixed in CMake 3.10 (when released).

**Comment by cjvaijo** [comment]
That did the trick, thanks for the quit response.
