### ISSUE TITLE
[realsense2] build failure

### ISSUE THREAD

**Issue by Rad0n1** [microsoft/vcpkg#17234]
**Host Environment**
- OS: Windows 10 Home (10.0.19042 Build 19042)
- Compiler: Not sure

**To Reproduce**
`./vcpkg install realsense2`

**Failure logs** 
  Package: realsense2:x86-windows
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

D:\vcpkg\buildtrees\realsense2\src\e9ef1b269d-8a10138e79.clean\src\metadata-parser.h(375): warning C4018: '<': signed/unsigned mismatch
D:\vcpkg\buildtrees\realsense2\src\e9ef1b269d-8a10138e79.clean\src\pipeline\resolver.h(294): warning C4018: '<': signed/unsigned mismatch
Unknown compiler version - please run the configure tests and report the results
D:\vcpkg\buildtrees\realsense2\src\e9ef1b269d-8a10138e79.clean\third-party\realsense-file\boost\boost/format/alt_sstream_impl.hpp(1): warning C4828: The file contains a character starting at offset 0x1df3 that is illegal in the current source character set (codepage 65001).
ninja: build stopped: subcommand failed.

**Additional context**
I hope I have put enough information, please let me know if you need more! I have also attached the full log, in case that is needed.

[install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/6295443/install-x86-windows-dbg-out.log)

**Comment by JackBoosY** [comment]
```
D:\vcpkg\buildtrees\realsense2\src\e9ef1b269d-8a10138e79.clean\src\winusb\device-winusb.h(14): fatal error C1083: Cannot open include file: 'atlstr.h': No such file or directory
```
Please install Visual Studio ATL components using Visual Studio Installer.

Thanks.

**Comment by Rad0n1** [comment]
Oh wow, I can't believe I forgot to install the c++ desktop package for visual studio.

Thank you so much for your quick response, it worked.
