### ISSUE TITLE
build failure: Error: Building package boost-exception:x64-osx failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by jqiu2** [microsoft/vcpkg#17241]
Hello, I am new to vcpkg and I am facing some errors during installation. Could you please help me?
**Host Environment**
- OS: [Mac OS BigSur]
- Compiler: Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.0 (clang-1200.0.32.28)
Target: x86_64-apple-darwin20.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**To Reproduce**
`./vcpkg install flashlight-cpu`

**Failure logs** 
Error: Building package boost-exception:x64-osx failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-exception:x64-osx
  Vcpkg version: 2021-01-13-unknownhash

**Additional context**
I invoked.  ./vcpkg update     but the terminal is saying ./vcpkg is a directory 

A lot of thanks in advance!!

**Comment by autoantwort** [comment]
Can you please provide the full failure logs

**Comment by autoantwort** [comment]
But probably #13348 solved this.

**Comment by PhoebeHui** [comment]
@jqiu2, please reopen this issue with failure logs if it still be a problem for you.
