### ISSUE TITLE
Grpc installed libraries difference between x64-windows and x86-windows

### ISSUE THREAD

**Issue by yusuke-kadowaki** [microsoft/vcpkg#17247]
After installing grpc with the command below, I cannot find some libraries like grpc++_refletion.lib for x86-windows. Is this supposed to be so or am I missing something?

- The machine setup
Windows10

- package and version you're building
grpc 1.33.1#3

- Installation process
```
$ git clone https://github.com/Microsoft/vcpkg.git
$ ./bootstrap-vcpkg.sh
$ ./vcpkg integrate install
$ vcpkg install grpc
```

- Libraries for x64-windows
```
vcpkg\packages\grpc_x64-windows\lib> Get-ChildItem -Name
pkgconfig
address_sorting.lib
gpr.lib
grpc++.lib
grpc++_alts.lib
grpc++_error_details.lib
grpc++_reflection.lib
grpc++_unsecure.lib
grpc.lib
grpcpp_channelz.lib
grpc_csharp_ext.lib
grpc_plugin_support.lib
grpc_unsecure.lib
```
- Libraries for x86-windows
```
vcpkg\packages\grpc_x86-windows\lib> Get-ChildItem -name
pkgconfig
address_sorting.lib
gpr.lib
grpc++.lib
grpc++_alts.lib
grpc++_unsecure.lib
grpc.lib
grpc_csharp_ext.lib
grpc_plugin_support.lib
grpc_unsecure.lib
```

**Comment by yusuke-kadowaki** [comment]
I think this is a regression of this.
https://github.com/microsoft/vcpkg/commit/b5bb1511f0a07be530e0bde3ae098eb3d8e83e68

Reverting ports/grpc/portfile.cmake solved the situation.

**Comment by JonLiu1993** [comment]
@yusuke-kadowaki ,Could you commit a pr to solve this issue？
