### ISSUE TITLE
openal-soft build failure

### ISSUE THREAD

**Issue by sssnakesss** [Microsoft/vcpkg#1724]
Got a no-go when trying to build openal-soft, as part of building sfml.

[config-x64-windows-rel-err.log.txt](https://github.com/Microsoft/vcpkg/files/1259033/config-x64-windows-rel-err.log.txt)
[config-x64-windows-rel-out.log.txt](https://github.com/Microsoft/vcpkg/files/1259034/config-x64-windows-rel-out.log.txt)
[CMakeError.log.txt](https://github.com/Microsoft/vcpkg/files/1259037/CMakeError.log.txt)
[CMakeOutput.log.txt](https://github.com/Microsoft/vcpkg/files/1259036/CMakeOutput.log.txt)

**Comment by NancyLi1013** [comment]
Please open a new issue if this is still a problem for you.
