### ISSUE TITLE
[New Port Request] prometheus-client-c

### ISSUE THREAD

**Issue by draveness** [microsoft/vcpkg#17275]
Library name: prometheus-client-c

Library description:

Source repository URL: https://github.com/digitalocean/prometheus-client-c

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by draveness** [comment]
so the reason for closing this issue?
