### ISSUE TITLE
[cudnn:x64-windows] build failure while installing opencv

### ISSUE THREAD

**Issue by rubenpraets** [microsoft/vcpkg#17283]
**Host Environment**
- OS: Windows 10
- Compiler: Visual studio 19?

**To Reproduce**
install cuda (v11.0.221) with cudnn (v8.0.2) separately
`./vcpkg install opencv[contrib,eigen,tiff,cuda,opengl,ipp,tbb]:x64-windows`

**Failure logs** 
Building package cudnn[core]:x64-windows...
-- Found CUDA V11.0.221
CMake Error at ports/cudnn/portfile.cmake:138 (message):
  Please install manually cuDNN for your CUDA v11.0
Call Stack (most recent call first):
  scripts/ports.cmake:142 (include)

Error: Building package cudnn:x64-windows failed with: BUILD_FAILED

**Additional context**
As stated above, I have CUDA version 11.0 and cuDNN version 8.0.2 installed as per the nvidia installation instructions. This includes a CUDA_PATH environment variable that points to the correct location. The vcpkg script however fails to find the cuDNN installation. 

I already went into the [cudnn portfile](https://github.com/microsoft/vcpkg/blob/master/ports/cudnn/portfile.cmake) and it seems that all the path hints provided to the find_path and find_library calls are empty. As a workaround I moved lines 67 and 68 (that look for the cuda installation) before these calls and added ${CUDA_TOOLKIT_ROOT} as a hint to both. As a result, opencv is now happily building in the background.

Is there maybe something I missed on my part, or can you guys fix this?

**Comment by JackBoosY** [comment]
```
CMake Error at ports/cudnn/portfile.cmake:138 (message):
Please install manually cuDNN for your CUDA v11.0
```

**Comment by PBoog** [comment]
@JackBoosY I ran into the same issue: "Please install manually cuDNN for your CUDA v11.0" 
However I already did this based on the instructions found [here](https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html#install-windows). So this looks like an issue and not only a question :)

Thanks @rubenpraets for the workaround that did the trick!

For reference, I moved the include lines in the portfile to just after where the minimun version for cuDNN is set and added the hints on the following lines. Small clip from my portfile:
``` CMAKE
...

set(MINIMUM_CUDNN_VERSION "7.6.5")

include(${CURRENT_INSTALLED_DIR}/share/cuda/vcpkg_find_cuda.cmake)
vcpkg_find_cuda(OUT_CUDA_TOOLKIT_ROOT CUDA_TOOLKIT_ROOT OUT_CUDA_VERSION CUDA_VERSION)

# Try to find CUDNN if it exists; only download if it doesn't exist
find_path(CUDNN_INCLUDE_DIR NAMES cudnn.h cudnn_v8.h cudnn_v7.h
  HINTS ${CUDA_HOME} ${CUDA_PATH} $ENV{CUDA_TOOLKIT_ROOT_DIR} $ENV{cudnn} $ENV{CUDNN} $ENV{CUDNN_ROOT_DIR} ${CUDA_TOOLKIT_ROOT}
  PATH_SUFFIXES cuda/include include)
find_library(CUDNN_LIBRARY NAMES cudnn cudnn8 cudnn7
  HINTS ${CUDA_HOME} ${CUDA_PATH} $ENV{CUDA_TOOLKIT_ROOT_DIR} $ENV{cudnn} $ENV{CUDNN} $ENV{CUDNN_ROOT_DIR} ${CUDA_TOOLKIT_ROOT}
  PATH_SUFFIXES lib lib64 cuda/lib cuda/lib64 lib/x64)

...
```
