### ISSUE TITLE
[New Port Request] Boost.UI

### ISSUE THREAD

**Issue by SamuelMarks** [microsoft/vcpkg#17296]
Library name: Boost.IO

Library description:
> Boost.UI is a C++ User Interface (GUI) Boost library that
>
>    - is cross-platform
>    - uses native system-provided widgets
>    - has STL-like and Boost-like API
>    - compatible with other Boost libraries
>    - supports modern C++11/14/17 features
>
> It supports [Graphics](https://kosenko.github.io/boost.ui/group__graphics.html), various [Widgets](https://kosenko.github.io/boost.ui/group__widget.html), [Events](https://kosenko.github.io/boost.ui/group__event.html), [Layouts](https://kosenko.github.io/boost.ui/group__layout.html).

Source repository URL: https://github.com/kosenko/ui

Project homepage (if different from the source repository): https://kosenko.github.io/boost.ui

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

See build-instructions https://github.com/kosenko/ui/blob/master/build/README.md - seems to depend both on WxWidgets and some Boost libraries…

**Comment by wildmichael** [comment]
That repo doesn't have a single tag or release. No version number mentioned anywhere that I could find. I'm not really sure this is ready to be packaged yet.

**Comment by SamuelMarks** [comment]
@wildmichael It hasn't been touched since December but I was thinking if it were in vcpkg people might be more inclined to maintain it. In terms of versioning I found with nuklear—and other packages—that a simple date serves as a reasonable version number. The Boost.UI approach seems rather neat, and like most Boost libraries is trying to set itself up as something future C++ standards can be based upon. With the exception of Boost it seems really lightweight also. So an exercise might be reducing its dependencies to header-only and OS-specific builtin libraries.

**Comment by wildmichael** [comment]
That could work. But there are other problems I see. For one, it is not really part of Boost. And then it wants to be built inside a full Boost source tree. Also, I don't see any explicitly declared dependencies on individual Boost modules. A naive `git-grep` search turns up the following headers being included from the `src/` and `include/` directories:

```ps1
PS1> git grep '<boost/' | ag -v '<boost/ui' | ag '^include/|^src/' | ag -o '#include <boost/.*' | Sort-Object | Get-Unique
#include <boost/bind.hpp>
#include <boost/chrono.hpp>
#include <boost/config.hpp>
#include <boost/config/auto_link.hpp>
#include <boost/core/scoped_enum.hpp>
#include <boost/cstdint.hpp>
#include <boost/date_time/gregorian/greg_date.hpp>
#include <boost/date_time/posix_time/posix_time.hpp>
#include <boost/date_time/time_duration.hpp>
#include <boost/exception/get_error_info.hpp>
#include <boost/filesystem.hpp>
#include <boost/function.hpp>
#include <boost/functional/hash.hpp>
#include <boost/geometry.hpp> // TODO: Remove hotfix
#include <boost/geometry/geometries/box.hpp>
#include <boost/geometry/geometries/point_xy.hpp>
#include <boost/logic/tribool.hpp>
#include <boost/move/utility.hpp>
#include <boost/noncopyable.hpp>
#include <boost/optional.hpp>
#include <boost/polygon/point_data.hpp>
#include <boost/polygon/rectangle_data.hpp>
#include <boost/range/begin.hpp>
#include <boost/range/end.hpp>
#include <boost/range/size.hpp>
#include <boost/scoped_ptr.hpp>
#include <boost/throw_exception.hpp>
```

So, that indicates already a substantial number of dependencies, apart from wxWidgets.

Probably you could give it a go (looking at how other boost modules are built) and then submit a pull-request. At least that's how I would go about it :-)

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
