### ISSUE TITLE
Xapian Not found 

### ISSUE THREAD

**Issue by hudengjunai** [microsoft/vcpkg#17303]
When asking a question please also include where you looked for an answer (so we can update the documentation if needed).
I want to test some C++ search engine support with Xapian.[https://github.com/xapian/xapian]
but cannot search the lib with vcpkg search xapian.

**Comment by NancyLi1013** [comment]
Hi @hudengjunai 

Thanks for posting this issue.

Of course, `xapian `is not in vcpkg now. You can [open a new issue](https://github.com/microsoft/vcpkg/issues/new?assignees=&labels=new+port+request+-+consider+making+a+PR%21&template=request-a-new-port.md&title=%5BNew+Port+Request%5D+%3Clibrary+name+here%3E) or comment here #8946 if you wish to add `xapian `
in vcpkg.

Thanks.

**Comment by NancyLi1013** [comment]
Closing this issue for now, please open a new issue if you still have the request for `xapian`.

**Comment by xiaoyifang** [comment]
https://github.com/microsoft/vcpkg/issues/8946

**Comment by xiaoyifang** [comment]
https://github.com/microsoft/vcpkg/pull/27038
