### ISSUE TITLE
blas[core]:x64-windows Build Failure

### ISSUE THREAD

**Issue by lwrobinson12356** [microsoft/vcpkg#17307]
Building package blas[core]:x64-windows...
-- Found external ninja('1.10.2').
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
    Command failed: ninja -v
    Working Directory: E:/Users/Lawrence/Documents/Visual Studio 2019/vcpkg/buildtrees/blas/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      E:\Users\Lawrence\Documents\Visual Studio 2019\vcpkg\buildtrees\blas\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:324 (vcpkg_execute_required_process)
  ports/blas/portfile.cmake:4 (vcpkg_configure_cmake)
  scripts/ports.cmake:142 (include)

Error: Building package blas:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: blas:x64-windows
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/6318454/config-x64-windows-out.log)

**Comment by cenit** [comment]
use the `subst` command to reduce your build path and remove the blank space in it

**Comment by lwrobinson12356** [comment]
Thank you – that fixed it.

 

Larry Robinson
