### ISSUE TITLE
Add SourceLink to the vcpkg.exe main tool.

### ISSUE THREAD

**Issue by frivard-coveo** [microsoft/vcpkg#17325]
****

**Is your feature request related to a problem? Please describe.**
I was recently investigating #17269 , and I observed that the vcpkg-tool itself doesn't have SourceLink enabled.

**Proposed solution**
Add sourcelink (when possible) to the link options of vcpkg-tool.

**Describe alternatives you've considered**
Figure out the version used by looking inside bootstrapvcpkg.ps1, then checkout that specific tag localy on computer, then tell VisualStudio where those files are.

**Additional context**
I recently added that same functionality to my own repos, so I know the routine. I will submit a PR.

**Comment by NancyLi1013** [comment]
This should be fixed in vcpkg now, since a new vcpkg tool 2021-07-21 has been released. Please update to the latest vcpkg via `git pull` and run` .\bootstrap-vcpkg.bat` to rebuild.
