### ISSUE TITLE
vxl:x64-windows build failure

### ISSUE THREAD

**Issue by gdidomenico** [microsoft/vcpkg#17329]
**Host Environment**
- OS: Windows 10
- Compiler: visual studio 2017

**To Reproduce**
`./vcpkg install vxl`

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
-------------------------------------------------------------------------------------------------------------------
vcpkg install vxl
Info about the package - 
Package: vxl:x64-windows
Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e
------------------------------------------------------------------------------------------------------------------
-Please attach any additional failure logs mentioned in the console output.
------------------------------------------------------------------------------------------------------------------
Starting package 4/4: vxl:x64-windows
Building package vxl[core]:x64-windows...
-- Downloading https://github.com/vxl/vxl/archive/dac1c7ed8e183e9c6de8b928c8b0294a7bd1d8ee.tar.gz -> vxl-vxl-dac1c7ed8e183e9c6de8b928c8b0294a7bd1d8ee.tar.gz...
-- Extracting source D:/Software/vcpkg/downloads/vxl-vxl-dac1c7ed8e183e9c6de8b928c8b0294a7bd1d8ee.tar.gz
-- Applying patch fix_dependency.patch
-- Using source at D:/Software/vcpkg/buildtrees/vxl/src/4a7bd1d8ee-117a1e1557.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:146 (message):
    Command failed: D:/Software/vcpkg/downloads/tools/cmake-3.19.2-windows/cmake-3.19.2-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v -j9
    Working Directory: D:/Software/vcpkg/buildtrees/vxl/x64-windows-dbg
    See logs for more information:
      D:\Software\vcpkg\buildtrees\vxl\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:105 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:45 (vcpkg_build_cmake)
  ports/vxl/portfile.cmake:48 (vcpkg_install_cmake)
  scripts/ports.cmake:142 (include)
Error: Building package vxl:x64-windows failed with: BUILD_FAILED
-----------------------------------------------------------------------------------------------------------
**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by NancyLi1013** [comment]
Hi @gdidomenico 
Could you please help confirm if the error you encountered like this?

```
FAILED: core/vsl/CMakeFiles/vsl.dir/Templates/vsl_vector_io+uint_64-.cxx.obj 
C:\PROGRA~2\MICROS~1\2017\ENTERP~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x86\cl.exe   /TP -D /MP  -DVXL_WARN_DEPRECATED -DVXL_WARN_DEPRECATED_ONCE -D_CRT_FAR_MAPPINGS_NO_DEPRECATE -D_CRT_IS_WCTYPE_NO_DEPRECATE -D_CRT_MANAGED_FP_NO_DEPRECATE -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_DEPRECATE_GLOBALS -D_CRT_SETERRORMODE_BEEP_SLEEP_NO_DEPRECATE -D_CRT_TIME_FUNCTIONS_NO_DEPRECATE -D_CRT_VCCLRIT_NO_DEPRECATE -D_SCL_SECURE_NO_DEPRECATE -Dvsl_EXPORTS -Ivcl -IF:\vcpkg\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557\vcl -Icore -IF:\vcpkg\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557\core -Icore\vsl -IF:\vcpkg\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557\core\vsl /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP   /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /Focore\vsl\CMakeFiles\vsl.dir\Templates\vsl_vector_io+uint_64-.cxx.obj /Fdcore\vsl\CMakeFiles\vsl.dir\ /FS -c F:\vcpkg\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557\core\vsl\Templates\vsl_vector_io+uint_64-.cxx
F:\vcpkg\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557\core\vsl/vsl_vector_io.hxx(115): error C2668: 'vsl_print_summary': ambiguous call to overloaded function
```

**Comment by NancyLi1013** [comment]
Upstream issue https://github.com/vxl/vxl/issues/565, which has been fixed by upstream https://github.com/vxl/vxl/pull/564.

But there is no new release version since v2.0.2.

**Comment by gdidomenico** [comment]
Hi @NancyLi1013 
I copy and paste the error message cuts from log file:
[533/1128] C:\PROGRA~2\MIB055~1\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64\cl.exe   /TP -D /MP  -DVXL_WARN_DEPRECATED -DVXL_WARN_DEPRECATED_ONCE -D_CRT_FAR_MAPPINGS_NO_DEPRECATE -D_CRT_IS_WCTYPE_NO_DEPRECATE -D_CRT_MANAGED_FP_NO_DEPRECATE -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_DEPRECATE_GLOBALS -D_CRT_SETERRORMODE_BEEP_SLEEP_NO_DEPRECATE -D_CRT_TIME_FUNCTIONS_NO_DEPRECATE -D_CRT_VCCLRIT_NO_DEPRECATE -D_SCL_SECURE_NO_DEPRECATE -Dvbl_io_EXPORTS -Ivcl -ID:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\vcl -Icore -ID:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core -ID:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vbl\io -ID:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vbl -ID:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vsl /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP   /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /Focore\vbl\io\CMakeFiles\vbl_io.dir\Templates\vbl_io_array_2d+double-.cxx.obj /Fdcore\vbl\io\CMakeFiles\vbl_io.dir\ /FS -c D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vbl\io\Templates\vbl_io_array_2d+double-.cxx
FAILED: core/vbl/io/CMakeFiles/vbl_io.dir/Templates/vbl_io_array_2d+double-.cxx.obj 
C:\PROGRA~2\MIB055~1\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64\cl.exe   /TP -D /MP  -DVXL_WARN_DEPRECATED -DVXL_WARN_DEPRECATED_ONCE -D_CRT_FAR_MAPPINGS_NO_DEPRECATE -D_CRT_IS_WCTYPE_NO_DEPRECATE -D_CRT_MANAGED_FP_NO_DEPRECATE -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_DEPRECATE_GLOBALS -D_CRT_SETERRORMODE_BEEP_SLEEP_NO_DEPRECATE -D_CRT_TIME_FUNCTIONS_NO_DEPRECATE -D_CRT_VCCLRIT_NO_DEPRECATE -D_SCL_SECURE_NO_DEPRECATE -Dvbl_io_EXPORTS -Ivcl -ID:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\vcl -Icore -ID:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core -ID:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vbl\io -ID:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vbl -ID:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vsl /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP   /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /Focore\vbl\io\CMakeFiles\vbl_io.dir\Templates\vbl_io_array_2d+double-.cxx.obj /Fdcore\vbl\io\CMakeFiles\vbl_io.dir\ /FS -c D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vbl\io\Templates\vbl_io_array_2d+double-.cxx
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vbl/io/vbl_io_array_2d.hxx(47): error C2665: 'vsl_b_read': none of the 14 overloads could convert all the argument types
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vsl/vsl_binary_io.h(416): note: could be 'void vsl_b_read(vsl_b_istream &,double &)'
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vsl/vsl_binary_io.h(407): note: or       'void vsl_b_read(vsl_b_istream &,float &)'
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vsl/vsl_binary_io.h(374): note: or       'void vsl_b_read(vsl_b_istream &,unsigned long &)'
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vsl/vsl_binary_io.h(366): note: or       'void vsl_b_read(vsl_b_istream &,long &)'
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vsl/vsl_binary_io.h(358): note: or       'void vsl_b_read(vsl_b_istream &,unsigned short &)'
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vsl/vsl_binary_io.h(350): note: or       'void vsl_b_read(vsl_b_istream &,short &)'
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vsl/vsl_binary_io.h(342): note: or       'void vsl_b_read(vsl_b_istream &,unsigned int &)'
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vsl/vsl_binary_io.h(332): note: or       'void vsl_b_read(vsl_b_istream &,int &)'
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vsl/vsl_binary_io.h(306): note: or       'void vsl_b_read(vsl_b_istream &,char *)'
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vsl/vsl_binary_io.h(294): note: or       'void vsl_b_read(vsl_b_istream &,std::string &)'
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vsl/vsl_binary_io.h(286): note: or       'void vsl_b_read(vsl_b_istream &,unsigned char &)'
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vsl/vsl_binary_io.h(278): note: or       'void vsl_b_read(vsl_b_istream &,signed char &)'
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vsl/vsl_binary_io.h(270): note: or       'void vsl_b_read(vsl_b_istream &,char &)'
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vsl/vsl_binary_io.h(262): note: or       'void vsl_b_read(vsl_b_istream &,bool &)'
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vbl/io/vbl_io_array_2d.hxx(47): note: while trying to match the argument list '(vsl_b_istream, size_type)'
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vbl\io\Templates\vbl_io_array_2d+double-.cxx(2): note: see reference to function template instantiation 'void vsl_b_read<double>(vsl_b_istream &,vbl_array_2d<double> &)' being compiled
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vbl/io/vbl_io_array_2d.hxx(48): error C2665: 'vsl_b_read': none of the 14 overloads could convert all the argument types
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vsl/vsl_binary_io.h(416): note: could be 'void vsl_b_read(vsl_b_istream &,double &)'
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vsl/vsl_binary_io.h(407): note: or       'void vsl_b_read(vsl_b_istream &,float &)'
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vsl/vsl_binary_io.h(374): note: or       'void vsl_b_read(vsl_b_istream &,unsigned long &)'
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vsl/vsl_binary_io.h(366): note: or       'void vsl_b_read(vsl_b_istream &,long &)'
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vsl/vsl_binary_io.h(358): note: or       'void vsl_b_read(vsl_b_istream &,unsigned short &)'
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vsl/vsl_binary_io.h(350): note: or       'void vsl_b_read(vsl_b_istream &,short &)'
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vsl/vsl_binary_io.h(342): note: or       'void vsl_b_read(vsl_b_istream &,unsigned int &)'
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vsl/vsl_binary_io.h(332): note: or       'void vsl_b_read(vsl_b_istream &,int &)'
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vsl/vsl_binary_io.h(306): note: or       'void vsl_b_read(vsl_b_istream &,char *)'
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vsl/vsl_binary_io.h(294): note: or       'void vsl_b_read(vsl_b_istream &,std::string &)'
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vsl/vsl_binary_io.h(286): note: or       'void vsl_b_read(vsl_b_istream &,unsigned char &)'
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vsl/vsl_binary_io.h(278): note: or       'void vsl_b_read(vsl_b_istream &,signed char &)'
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vsl/vsl_binary_io.h(270): note: or       'void vsl_b_read(vsl_b_istream &,char &)'
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vsl/vsl_binary_io.h(262): note: or       'void vsl_b_read(vsl_b_istream &,bool &)'
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vbl/io/vbl_io_array_2d.hxx(48): note: while trying to match the argument list '(vsl_b_istream, size_type)'
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vbl/io/vbl_io_array_2d.hxx(24): error C2668: 'vsl_b_write': ambiguous call to overloaded function
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vsl/vsl_binary_io.h(414): note: could be 'void vsl_b_write(vsl_b_ostream &,double)'
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vsl/vsl_binary_io.h(405): note: or       'void vsl_b_write(vsl_b_ostream &,float)'
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vsl/vsl_binary_io.h(372): note: or       'void vsl_b_write(vsl_b_ostream &,unsigned long)'
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vsl/vsl_binary_io.h(364): note: or       'void vsl_b_write(vsl_b_ostream &,long)'
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vsl/vsl_binary_io.h(356): note: or       'void vsl_b_write(vsl_b_ostream &,unsigned short)'
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vsl/vsl_binary_io.h(348): note: or       'void vsl_b_write(vsl_b_ostream &,short)'
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vsl/vsl_binary_io.h(340): note: or       'void vsl_b_write(vsl_b_ostream &,unsigned int)'
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vsl/vsl_binary_io.h(330): note: or       'void vsl_b_write(vsl_b_ostream &,int)'
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vsl/vsl_binary_io.h(284): note: or       'void vsl_b_write(vsl_b_ostream &,unsigned char)'
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vsl/vsl_binary_io.h(276): note: or       'void vsl_b_write(vsl_b_ostream &,signed char)'
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vsl/vsl_binary_io.h(268): note: or       'void vsl_b_write(vsl_b_ostream &,char)'
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vsl/vsl_binary_io.h(260): note: or       'void vsl_b_write(vsl_b_ostream &,bool)'
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vbl/io/vbl_io_array_2d.hxx(24): note: while trying to match the argument list '(vsl_b_ostream, size_type)'
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vbl\io\Templates\vbl_io_array_2d+double-.cxx(2): note: see reference to function template instantiation 'void vsl_b_write<double>(vsl_b_ostream &,const vbl_array_2d<double> &)' being compiled
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vbl/io/vbl_io_array_2d.hxx(25): error C2668: 'vsl_b_write': ambiguous call to overloaded function
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vsl/vsl_binary_io.h(414): note: could be 'void vsl_b_write(vsl_b_ostream &,double)'
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vsl/vsl_binary_io.h(405): note: or       'void vsl_b_write(vsl_b_ostream &,float)'
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vsl/vsl_binary_io.h(372): note: or       'void vsl_b_write(vsl_b_ostream &,unsigned long)'
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vsl/vsl_binary_io.h(364): note: or       'void vsl_b_write(vsl_b_ostream &,long)'
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vsl/vsl_binary_io.h(356): note: or       'void vsl_b_write(vsl_b_ostream &,unsigned short)'
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vsl/vsl_binary_io.h(348): note: or       'void vsl_b_write(vsl_b_ostream &,short)'
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vsl/vsl_binary_io.h(340): note: or       'void vsl_b_write(vsl_b_ostream &,unsigned int)'
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vsl/vsl_binary_io.h(330): note: or       'void vsl_b_write(vsl_b_ostream &,int)'
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vsl/vsl_binary_io.h(284): note: or       'void vsl_b_write(vsl_b_ostream &,unsigned char)'
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vsl/vsl_binary_io.h(276): note: or       'void vsl_b_write(vsl_b_ostream &,signed char)'
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vsl/vsl_binary_io.h(268): note: or       'void vsl_b_write(vsl_b_ostream &,char)'
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vsl/vsl_binary_io.h(260): note: or       'void vsl_b_write(vsl_b_ostream &,bool)'
D:\Software\vcpkg\buildtrees\vxl\src\4a7bd1d8ee-117a1e1557.clean\core\vbl/io/vbl_io_array_2d.hxx(25): note: while trying to match the argument list '(vsl_b_ostream, size_type)'

**Comment by Cheney-W** [comment]
This is an upstream problem that requires an upstream fix. Dup to https://github.com/microsoft/vcpkg/issues/20701, so that the same issues can be dealt with centrally.
