### ISSUE TITLE
[gamenetworkingsockets] unable to include headers

### ISSUE THREAD

**Issue by aizuon** [microsoft/vcpkg#17337]
Hello, 

The header steam/steamnetworkingtypes.h has `#include <minbase/minbase_identify.h>` and `#include <minbase/minbase_decls.h>` which can't be included because includes doesn't use relative path. If they are patched as `#include "../minbase/minbase_identify.h"` and `#include "../minbase/minbase_decls.h"`, then they can be included. 

![image](https://user-images.githubusercontent.com/44760523/115128128-442b9980-9fe4-11eb-86c6-37b5091cfdda.png)

Also, this library doesn't support static builds in vcpkg but I checked their GitHub repo. and it looks like they support static builds. Is there a reason why it's not supported in vcpkg?

**Comment by JonLiu1993** [comment]
@aizuon,thanks for your issue, please provide your environment and reproduction steps

**Comment by aizuon** [comment]
> @aizuon,thanks for your issue, please provide your environment and reproduction steps

OS: Windows 10
Compiler: MSVC 14.2
IDE: VS 2019

Steps to reproduce the issue:
* Install `gamenetworkingsockets` via vcpkg by the following command: `vcpkg install gamenetworkingsockets:x86-windows`
* Create an empty console application
* Include the following header: `gamenetworkingsockets/steamnetworkingtypes.h`
* Compile

Looks like this issue wouldn't happen in `master branch` of `gamenetworkingsockets` (https://github.com/ValveSoftware/GameNetworkingSockets/tree/master/include), because include folder doesn't have the `minbase` folder, assuming they have been integrated into the headers that needed them.

**Comment by JonLiu1993** [comment]
@aizuon ,I will update the GameNetworkingSockets version to the latest submission to solve this problem

**Comment by JonLiu1993** [comment]
@aizuon, thanks for your contribution, I have submitted a PR to update this port, you can wait for my PR merge to try again.
