### ISSUE TITLE
[New Port Request] <HX711.h>

### ISSUE THREAD

**Issue by jpnaranjo20** [microsoft/vcpkg#17339]
Library name: HX711.h

Library description: An Arduino library to interface the Avia Semiconductor HX711 24-Bit Analog-to-Digital Converter (ADC) for reading load cells / weight scales.

It supports the architectures atmelavr, espressif8266, espressif32, atmelsam, teensy and ststm32 by corresponding PlatformIO targets.

Source repository URL: https://github.com/bogde/HX711

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
