### ISSUE TITLE
Building package curl:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by k3v1n1990s** [Microsoft/vcpkg#1733]
C:\Users\test\Desktop\vcpkg>vcpkg.exe install CPR
The following packages will be built and installed:
    cpr:x86-windows
  * curl:x86-windows
Additional packages (*) will be installed to complete this operation.
Building package curl:x86-windows...
-- CURRENT_INSTALLED_DIR=C:/Users/test/Desktop/vcpkg/installed/x86-windows
-- DOWNLOADS=C:/Users/test/Desktop/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/Users/test/Desktop/vcpkg/packages/curl_x86-windows
-- CURRENT_BUILDTREES_DIR=C:/Users/test/Desktop/vcpkg/buildtrees/curl
-- CURRENT_PORT_DIR=C:/Users/test/Desktop/vcpkg/ports/curl/.
-- Using cached C:/Users/test/Desktop/vcpkg/downloads/curl-curl-curl-7_55_1.tar.
gz
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Applying patch C:/Users/test/Desktop/vcpkg/ports/curl/0001_cmake.patch
-- Applying patch failed. This is expected if this patch was previously applied.

-- Applying patch C:/Users/test/Desktop/vcpkg/ports/curl/0001_cmake.patch done
-- Applying patch C:/Users/test/Desktop/vcpkg/ports/curl/0002_fix_uwp.patch
-- Applying patch failed. This is expected if this patch was previously applied.

-- Applying patch C:/Users/test/Desktop/vcpkg/ports/curl/0002_fix_uwp.patch done

-- Configuring x86-windows-rel
-- Configuring x86-windows-rel done
-- Configuring x86-windows-dbg
-- Configuring x86-windows-dbg done
-- Package x86-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:43 (message):
    Command failed: C:/Users/test/Desktop/cmake-3.9.1-win64-x64/bin/cmake.exe;--
build;.;--config;Release;--target;install;--;-v
    Working Directory: C:/Users/test/Desktop/vcpkg/buildtrees/curl/x86-windows-r
el
    See logs for more information:
      C:\Users\test\Desktop\vcpkg\buildtrees\curl\package-x86-windows-rel-out.lo
g
      C:\Users\test\Desktop\vcpkg\buildtrees\curl\package-x86-windows-rel-err.lo
g

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:49 (vcpkg_execute_required_process)
  ports/curl/portfile.cmake:51 (vcpkg_install_cmake)
  scripts/ports.cmake:72 (include)

Error: Building package curl:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: curl:x86-windows
  Vcpkg version: 0.0.85-2017-08-28-28e581599e263e3f0b021ad5b6914d80fa9640f8

Additionally, attach any relevant sections from the log files above.

C:\Users\test\Desktop\vcpkg>

[package-x86-windows-rel-out.log.zip](https://github.com/Microsoft/vcpkg/files/1262118/package-x86-windows-rel-out.log.zip)

**Comment by ras0219-msft** [comment]
Hi @k3v1n1990s, this may be fixed in the latest master.

Could you try updating and let us know if the problem still repro's?

**Comment by k3v1n1990s** [comment]
C:\vcpkg>vcpkg install curl
The following packages will be built and installed:
    curl:x86-windows
  * libssh2:x86-windows
  * openssl:x86-windows
  * zlib:x86-windows
Additional packages (*) will be installed to complete this operation.
Starting package 1/4: zlib:x86-windows
Building package zlib:x86-windows...
-- CURRENT_INSTALLED_DIR=C:/vcpkg/installed/x86-windows
-- DOWNLOADS=C:/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/vcpkg/packages/zlib_x86-windows
-- CURRENT_BUILDTREES_DIR=C:/vcpkg/buildtrees/zlib
-- CURRENT_PORT_DIR=C:/vcpkg/ports/zlib/.
-- Using cached C:/vcpkg/downloads/zlib1211.tar.gz
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Configuring x86-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:43 (message):
    Command failed: C:/vcpkg/downloads/cmake-3.9.3-win32-x86/bin/cmake.exe;C:/vcpkg/buildtrees/zlib/src/zlib-1.2.11;-DSKIP_INSTALL_FILES=ON;-DBUILD_SHARED_LIBS=ON;-DVCPKG_TARGET_TRIPLET=x86-windows;-DCMAKE_CXX_FLAGS= /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP ;-DCMAKE_C_FLAGS= /DWIN32 /D_WINDOWS /W3 /utf-8 /MP ;-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON;-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE;-DCMAKE_VERBOSE_MAKEFILE=ON;-DVCPKG_APPLOCAL_DEPS=OFF;-DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake;-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON;-DCMAKE_CXX_FLAGS_RELEASE=/MD /O2 /Oi /Gy /DNDEBUG /Z7 ;-DCMAKE_C_FLAGS_RELEASE=/MD /O2 /Oi /Gy /DNDEBUG /Z7 ;-DCMAKE_SHARED_LINKER_FLAGS_RELEASE=/DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF ;-DCMAKE_EXE_LINKER_FLAGS_RELEASE=/DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF ;-G;Ninja;-DCMAKE_BUILD_TYPE=Release;-DCMAKE_INSTALL_PREFIX=C:/vcpkg/packages/zlib_x86-windows
    Working Directory: C:/vcpkg/buildtrees/zlib/x86-windows-rel
    See logs for more information:
      C:\vcpkg\buildtrees\zlib\config-x86-windows-rel-out.log
      C:\vcpkg\buildtrees\zlib\config-x86-windows-rel-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:170 (vcpkg_execute_required_process)
  ports/zlib/portfile.cmake:10 (vcpkg_configure_cmake)
  scripts/ports.cmake:72 (include)


Error: Building package zlib:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zlib:x86-windows
  Vcpkg version: 0.0.89-2017-09-23-67e876c76555c466e4faf49d6cd80a88b835f972

Additionally, attach any relevant sections from the log files above.

**Comment by kwaxi** [comment]
Still failing.

**Comment by miurahr** [comment]
It seems to build it fine in current master (https://github.com/Microsoft/vcpkg/commit/05edef92233854e944baa3cbde4d5b004f717bdd) to build curl:x64-windows on Windows 10 Evaluation image( https://developer.microsoft.com/en-us/windows/downloads/virtual-machines) .

Still reproduce?

**Comment by NancyLi1013** [comment]
Please open a new issue if this is still a problem for you.
