### ISSUE TITLE
OpenCV4 GAPI not being built when ADE is enabled

### ISSUE THREAD

**Issue by l90lpa** [microsoft/vcpkg#17345]
**Describe the bug**
Installing opencv4[ade] should lead to the OpenCV4 GAPI being built, but currently the cmake configuration step is disabling it from being built by passing `"-DBUILD_WITH_GAPI="` instead of `"-DBUILD_WITH_GAPI=ON"`. 

The problem lies in the portfile.cmake. The cmake variable `BUILD_opencv_gapi` is being set correctly but where it should be getting used, we're instead using the variable `DBUILD_opencv_gapi` which is empty. See:
 https://github.com/microsoft/vcpkg/blob/414bec05f2a97cfc0ddb8e22fd4635dfe2a20ab8/ports/opencv4/portfile.cmake#L378

Correcting the typo (to -DBUILD_opencv_gapi=${BUILD_opencv_gapi}) fixes the bug.

**Environment**
- OS: Windows
- Compiler: VS 16.9.4

**To Reproduce**
1. `./vcpkg install opencv4[ade]:x64-windows`
2. Check `vcpkg/buildtree/opencv4/x64-windows-*/modules` you should see that there is no gapi directory. Also you can check the `vcpkg/buildtree/opencv4/config-x64-windows-out.log` and see that the cmake configure command has `"-DBUILD_opencv_gapi="`.

**Expected behavior**
The modules directory should have a gapi directory. Furthermore the cmake configure command should have `"-DBUILD_opencv_gapi=ON"`.

**Comment by NancyLi1013** [comment]
Hi @l90lpa 

Thanks for reposting this issue.

This should be a mistake. I'll fix this soon.
