### ISSUE TITLE
希望能优化一下vcpkg的下载功能

### ISSUE THREAD

**Issue by fldx** [microsoft/vcpkg#17349]
****
在相同的系统环境下vcpkg下载特别慢,使用Chrome浏览器几秒钟下载完,vcpkg半个小时过去还在下载一个文件.不少包我用浏览器下载然后复制到vcpkg的缓存目录下才解决问题.
**Is your feature request related to a problem? Please describe.**

**Proposed solution**

**Describe alternatives you've considered**

**Additional context**

**Comment by JackBoosY** [comment]
Therefore, we need to wait https://github.com/microsoft/vcpkg/pull/13639 merge first.

**Comment by JackBoosY** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/11040.
