### ISSUE TITLE
[libwebp] build failure

### ISSUE THREAD

**Issue by larshg** [microsoft/vcpkg#17359]
**Host Environment**
- OS: Windows x64
- Compiler: VS2019 

**To Reproduce**
Using a triplet file, where only release library is build
`./vcpkg install libwebp[core,nearlossless,simd,unicode]:x64-windows-rel`

**Failure logs** 
```

CMake Error at scripts/cmake/vcpkg_replace_string.cmake:13 (file):
  file failed to open for reading (No such file or directory):

    C:/vcpkg/packages/libwebp_x64-windows-rel/debug/lib/pkgconfig/libwebp.pc
Call Stack (most recent call first):
  ports/libwebp/portfile.cmake:64 (vcpkg_replace_string)
  scripts/ports.cmake:142 (include)
```

https://dev.azure.com/PointCloudLibrary/pcl/_build/results?buildId=18719&view=logs&j=645d9b2d-e6a8-55a6-fe5b-40842942afe7&t=07185e79-ad4d-5c13-c1d1-201b01637442&l=4141

**Additional context**
Probably due to hard coded paths in this:

https://github.com/microsoft/vcpkg/commit/85a48c1ed558210cab67a03209510c4bf6e5e285#diff-b7fda08137df905438eca706b25d715b4ceb70d81c9f7c9d3c485c726931b406R64-R68

**Comment by JonLiu1993** [comment]
@larshg ,Are you using the latest vcpkg

**Comment by larshg** [comment]
Its run with master from two days ago, however the hardcoded paths are still in master:
https://github.com/microsoft/vcpkg/blob/807a7987612bbd702be9d9b8069124be62aff857/ports/libwebp/portfile.cmake#L64

And its set to only build release version, so there shouldnt  be any debug folder nor files in it.

**Comment by JonLiu1993** [comment]
@larshg ,Thanks for your issue,Currently, we do not support a single relase or debug install

**Comment by cenit** [comment]
> @larshg ,Thanks for your issue,Currently, we do not support a single relase or debug install

the pity is that libwebp was working in a release only triplet before, so it's always a problem when things go in the wrong direction if left by themselves...

**Comment by cenit** [comment]
as @larshg , i also have some ci pipelines that are now broken due to this change.

#15983 for me is very important. I hope it can be reconsidered soon, to avoid problems like this

**Comment by dg0yt** [comment]
Fixed waiting in #17172...

**Comment by JackBoosY** [comment]
@dg0yt  #17172 was already merged, can you please open a PR to fix this?

Thanks.

**Comment by larshg** [comment]
Yes, thanks. I'll close this - I haven't verified it however. This will probably happen over the weekend 😄

**Comment by larshg** [comment]
Just looked at some docker buildlogs and it does build now, thanks 👍
