### ISSUE TITLE
libpq for x86-windows-static fails with "module machine type 'x86' conflicts with target machine type 'x64'"

### ISSUE THREAD

**Issue by limison** [microsoft/vcpkg#17357]
Package: libpq:x86-windows-static
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

-- Applying patch patches/windows/Solution_RELEASE.patch
-- Applying patch patches/windows/python3_build_RELEASE.patch
-- Patches applied!
-- Building libpq x86-windows-static-RELEASE...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
    Command failed: D:/Code/VC/Librarys/vcpkg/downloads/tools/perl/5.30.0.1/perl/bin/perl.exe build.pl RELEASE libpq
    Working Directory: D:/Code/VC/Librarys/vcpkg/buildtrees/libpq/x86-windows-static-rel/src/tools/msvc
    Error code: 1
    See logs for more information:
      D:\Code\VC\Librarys\vcpkg\buildtrees\libpq\build-libpq-x86-windows-static-RELEASE-out.log

Call Stack (most recent call first):
  ports/libpq/portfile.cmake:216 (vcpkg_execute_required_process)
  scripts/ports.cmake:142 (include)

![image](https://user-images.githubusercontent.com/4509578/115223382-a202d300-a103-11eb-9c76-05969fe0c24d.png)

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. `libpq:x64-windows-static` can install succeed. `x86-windows-static` is a community triplet, and there are no update about this issue for a long time. If there are new process or change of this issue, please reopen this issue.
