### ISSUE TITLE
I m trying to install dlib using vcpkg. I m using Visual studio 2019 community version. The installation process got hang at "Configuring x64-windows" for the last 1 hour.

### ISSUE THREAD

**Issue by aboongm** [microsoft/vcpkg#17368]
When asking a question please also include where you looked for an answer (so we can update the documentation if needed).

**Comment by aboongm** [comment]
Here is the complete process 

PS D:\Dev\vcpkg> ./vcpkg search dlib
constexpr            1.0-1            Small MIT License Library of general stdlib functions written as C++11 constex...
dlib                 19.21#4          Modern C++ toolkit containing machine learning algorithms and tools for creati...
dlib[cuda]                            CUDA support for dlib
dlib[fftw3]                           fftw3 support for dlib
dlib[sqlite3]                         sqlite3 support for dlib
edlib                1.2.6            Lightweight, super fast C/C++ (& Python) library for sequence alignment using ...
fdlibm               5.3-4            FDLIBM (Freely Distributable LIBM) is a C math library for machines that suppo...

If your library is not listed, please open an issue at and/or consider making a pull request:
    https://github.com/Microsoft/vcpkg/issues
PS D:\Dev\vcpkg> ./vcpkg install dlib dlib:x64-windows
Computing installation plan...
A suitable version of cmake was not found (required v3.19.2). Downloading portable cmake v3.19.2...
Downloading cmake...
  https://github.com/Kitware/CMake/releases/download/v3.19.2/cmake-3.19.2-win32-x86.zip -> D:\Dev\vcpkg\downloads\cmake-3.19.2-win32-x86.zip
Extracting cmake...
The following packages will be built and installed:
  * blas[core]:x64-windows -> 1
  * blas[core]:x86-windows -> 1
    dlib[core,fftw3,sqlite3]:x64-windows -> 19.21#4
    dlib[core,fftw3,sqlite3]:x86-windows -> 19.21#4
  * fftw3[core]:x64-windows -> 3.3.8-7
  * fftw3[core]:x86-windows -> 3.3.8-7
  * lapack[core]:x64-windows -> 3#1
  * lapack[core]:x86-windows -> 3#1
  * lapack-reference[blas-select,core,noblas]:x64-windows -> 3.8.0#4
  * lapack-reference[blas-select,core,noblas]:x86-windows -> 3.8.0#4
  * libjpeg-turbo[core]:x64-windows -> 2.0.6
  * libjpeg-turbo[core]:x86-windows -> 2.0.6
  * libpng[core]:x64-windows -> 1.6.37#14
  * libpng[core]:x86-windows -> 1.6.37#14
  * openblas[core]:x64-windows -> 0.3.10
  * openblas[core]:x86-windows -> 0.3.10
  * vcpkg-gfortran[core]:x64-windows -> 3
  * vcpkg-gfortran[core]:x86-windows -> 3
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Detecting compiler hash for triplet x86-windows...
Could not locate cached archive: C:\Users\hp\AppData\Local\vcpkg\archives\ad\ad187cf132317c5233c6ca20e469ba825198b8c0.zip
Could not locate cached archive: C:\Users\hp\AppData\Local\vcpkg\archives\e1\e1557b3296ffcc5c9539524d67ce9f7f4a1f0321.zip
Could not locate cached archive: C:\Users\hp\AppData\Local\vcpkg\archives\18\18011a6ee32336fd387c306fa8440af0f0f8df47.zip
Could not locate cached archive: C:\Users\hp\AppData\Local\vcpkg\archives\2b\2b4f5f22cc4838a9d9a8101e545940d4349d4443.zip
Could not locate cached archive: C:\Users\hp\AppData\Local\vcpkg\archives\b8\b852675bb34a4baf6e778f62b9449861915dff62.zip
Could not locate cached archive: C:\Users\hp\AppData\Local\vcpkg\archives\2f\2f07ea5a4ef1742a2924b7171e47964129cdaa5e.zip
Could not locate cached archive: C:\Users\hp\AppData\Local\vcpkg\archives\ca\ca7179c066cd5170d0cbc8b671b116945c04fbf2.zip
Could not locate cached archive: C:\Users\hp\AppData\Local\vcpkg\archives\70\7083d2877cf151fa1d6614f95c9ae242437508dd.zip
Could not locate cached archive: C:\Users\hp\AppData\Local\vcpkg\archives\04\0450bd0763dd6653fd38da2474e9e3204071168c.zip
Could not locate cached archive: C:\Users\hp\AppData\Local\vcpkg\archives\2d\2dca458fd87e1a90e7be34d45b1caedbb1638b24.zip
Could not locate cached archive: C:\Users\hp\AppData\Local\vcpkg\archives\d6\d6a9b4ffc38c989bf6422d6c9d3ed03e4c9d3941.zip
Could not locate cached archive: C:\Users\hp\AppData\Local\vcpkg\archives\32\32f0341bffa848bedd013e953c3ee4da67f3c51a.zip
Could not locate cached archive: C:\Users\hp\AppData\Local\vcpkg\archives\cc\cc0c41af4836a24d8946a7af5d5da06662591e90.zip
Could not locate cached archive: C:\Users\hp\AppData\Local\vcpkg\archives\10\1077415dce355b9203d835d6a7336905ec0fa5e7.zip
Could not locate cached archive: C:\Users\hp\AppData\Local\vcpkg\archives\58\584b1a1b09bb06f0f80870b2cee6f3d82217de25.zip
Could not locate cached archive: C:\Users\hp\AppData\Local\vcpkg\archives\23\23d4e565bf07f6de5ad65465f900565ae4d33cdb.zip
Could not locate cached archive: C:\Users\hp\AppData\Local\vcpkg\archives\ef\efa0955a338d842363646dbaf018f72406e4d50d.zip
Could not locate cached archive: C:\Users\hp\AppData\Local\vcpkg\archives\6d\6d066fe20848c4c1cfa26ae03f9520861cc1dba6.zip
Starting package 1/18: openblas:x64-windows
Building package openblas[core]:x64-windows...
-- Using cached D:/Dev/vcpkg/downloads/xianyi-OpenBLAS-63b03efc2af332c88b86d4fd8079d00f4b439adf.tar.gz
-- Extracting source D:/Dev/vcpkg/downloads/xianyi-OpenBLAS-63b03efc2af332c88b86d4fd8079d00f4b439adf.tar.gz
-- Applying patch uwp.patch
-- Applying patch fix-space-path.patch
-- Applying patch fix-redefinition-function.patch
-- Applying patch fix-pkg-config.patch
-- Applying patch fix-uwp-build.patch
-- Using source at D:/Dev/vcpkg/buildtrees/openblas/src/0f4b439adf-917c2f6847.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows

**Comment by PhoebeHui** [comment]
@aboongm, I can't repro this issue locally, are there any messages in config log? could you remove the ninja in your local machine, and see if this issue persist?

```
-- Found external ninja('1.10.2').
-- Configuring x64-windows
```

**Comment by aboongm** [comment]
Thanks PhoebeHui.
There is no config.log in buildtrees. I had to Ctrl+C to stop the powershell after getting hang at 'Configuring x64-windows".
Also, How to remove the ninja from the local machine.

**Comment by PhoebeHui** [comment]
@aboongm, could you check where it is placed in your machine?

**Comment by aboongm** [comment]
@PhoebeHui, I think ninja is not a problem in the installation. I just install xtensor and same thing happen viz "Found external  ninja("1.10.2") and the xtensor is working now in visual studio 2019 community.
Here is the xtensor installation process:

PS D:\Dev\vcpkg> ./vcpkg install xtensor xtensor:x64-windows
Computing installation plan...
The following packages will be built and installed:
  * nlohmann-json[core]:x64-windows -> 3.9.1
  * nlohmann-json[core]:x86-windows -> 3.9.1
    xtensor[core]:x64-windows -> 0.21.9
    xtensor[core]:x86-windows -> 0.21.9
  * xtl[core]:x64-windows -> 0.6.21
  * xtl[core]:x86-windows -> 0.6.21
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Detecting compiler hash for triplet x86-windows...
Could not locate cached archive: C:\Users\hp\AppData\Local\vcpkg\archives\cc\cc46f9b8b8c6f510b1f19a7b3a082137d7f8883a.zip
Could not locate cached archive: C:\Users\hp\AppData\Local\vcpkg\archives\72\72915e4251a310bde1f283748722809122eb1abf.zip
Could not locate cached archive: C:\Users\hp\AppData\Local\vcpkg\archives\b7\b70b19eae06f91289290b27c0c6a626f8b3d3cba.zip
Could not locate cached archive: C:\Users\hp\AppData\Local\vcpkg\archives\51\51e0e0bd4bb66beec284069a92085fbb17dd0456.zip
Could not locate cached archive: C:\Users\hp\AppData\Local\vcpkg\archives\a2\a2548b44630455c58f59b6082d122623cb611a96.zip
Could not locate cached archive: C:\Users\hp\AppData\Local\vcpkg\archives\2a\2af5ddd4fb8ebf1f3c7594d0d1d92cdf9da29c6c.zip
Starting package 1/6: nlohmann-json:x64-windows
Building package nlohmann-json[core]:x64-windows...
-- Downloading https://github.com/nlohmann/json/raw/v3.9.1/CMakeLists.txt -> nlohmann-json-v3.9.1/CMakeLists.txt...
-- Downloading https://github.com/nlohmann/json/raw/v3.9.1/LICENSE.MIT -> nlohmann-json-v3.9.1/LICENSE.MIT...
-- Downloading https://github.com/nlohmann/json/raw/v3.9.1/nlohmann_json.natvis -> nlohmann-json-v3.9.1/nlohmann_json.natvis...
-- Downloading https://github.com/nlohmann/json/raw/v3.9.1/cmake/config.cmake.in -> nlohmann-json-v3.9.1/cmake/config.cmake.in...
-- Downloading https://github.com/nlohmann/json/raw/v3.9.1/cmake/pkg-config.pc.in -> nlohmann-json-v3.9.1/cmake/pkg-config.pc.in...
-- Downloading https://github.com/nlohmann/json/raw/v3.9.1/cmake/nlohmann_jsonConfigVersion.cmake.in -> nlohmann-json-v3.9.1/cmake/nlohmann_jsonConfigVersion.cmake.in...
-- Downloading https://github.com/nlohmann/json/releases/download/v3.9.1/include.zip -> nlohmann-json-v3.9.1-include.zip...
-- Extracting source D:/Dev/vcpkg/downloads/nlohmann-json-v3.9.1-include.zip
-- Using source at D:/Dev/vcpkg/buildtrees/nlohmann-json/3.9.1-74ced61d52.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: D:/Dev/vcpkg/packages/nlohmann-json_x64-windows/share/nlohmann-json/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\hp\AppData\Local\vcpkg\archives\cc\cc46f9b8b8c6f510b1f19a7b3a082137d7f8883a.zip
Building package nlohmann-json[core]:x64-windows... done
Installing package nlohmann-json[core]:x64-windows...
Installing package nlohmann-json[core]:x64-windows... done
Elapsed time for package nlohmann-json:x64-windows: 27.54 s
Starting package 2/6: nlohmann-json:x86-windows
Building package nlohmann-json[core]:x86-windows...
-- Using cached D:/Dev/vcpkg/downloads/nlohmann-json-v3.9.1/CMakeLists.txt
-- Using cached D:/Dev/vcpkg/downloads/nlohmann-json-v3.9.1/LICENSE.MIT
-- Using cached D:/Dev/vcpkg/downloads/nlohmann-json-v3.9.1/nlohmann_json.natvis
-- Using cached D:/Dev/vcpkg/downloads/nlohmann-json-v3.9.1/cmake/config.cmake.in
-- Using cached D:/Dev/vcpkg/downloads/nlohmann-json-v3.9.1/cmake/pkg-config.pc.in
-- Using cached D:/Dev/vcpkg/downloads/nlohmann-json-v3.9.1/cmake/nlohmann_jsonConfigVersion.cmake.in
-- Using cached D:/Dev/vcpkg/downloads/nlohmann-json-v3.9.1-include.zip
-- Cleaning sources at D:/Dev/vcpkg/buildtrees/nlohmann-json/3.9.1-74ced61d52.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/Dev/vcpkg/downloads/nlohmann-json-v3.9.1-include.zip
-- Using source at D:/Dev/vcpkg/buildtrees/nlohmann-json/3.9.1-74ced61d52.clean
-- Found external ninja('1.10.2').
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Installing: D:/Dev/vcpkg/packages/nlohmann-json_x86-windows/share/nlohmann-json/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\hp\AppData\Local\vcpkg\archives\72\72915e4251a310bde1f283748722809122eb1abf.zip
Building package nlohmann-json[core]:x86-windows... done
Installing package nlohmann-json[core]:x86-windows...
Installing package nlohmann-json[core]:x86-windows... done
Elapsed time for package nlohmann-json:x86-windows: 7.907 s
Starting package 3/6: xtl:x64-windows
Building package xtl[core]:x64-windows...
-- Downloading https://github.com/xtensor-stack/xtl/archive/6c017f4a81a59bd52008025a785ce745e5b7f49c.tar.gz -> xtensor-stack-xtl-6c017f4a81a59bd52008025a785ce745e5b7f49c.tar.gz...
-- Extracting source D:/Dev/vcpkg/downloads/xtensor-stack-xtl-6c017f4a81a59bd52008025a785ce745e5b7f49c.tar.gz
-- Using source at D:/Dev/vcpkg/buildtrees/xtl/src/45e5b7f49c-287ec8dc4d.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: D:/Dev/vcpkg/packages/xtl_x64-windows/share/xtl/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\hp\AppData\Local\vcpkg\archives\b7\b70b19eae06f91289290b27c0c6a626f8b3d3cba.zip
Building package xtl[core]:x64-windows... done
Installing package xtl[core]:x64-windows...
Installing package xtl[core]:x64-windows... done
Elapsed time for package xtl:x64-windows: 7.287 s
Starting package 4/6: xtensor:x64-windows
Building package xtensor[core]:x64-windows...
-- Downloading https://github.com/xtensor-stack/xtensor/archive/a377fb84c29624e91b6b2451018f3aa3abec1c4f.tar.gz -> xtensor-stack-xtensor-a377fb84c29624e91b6b2451018f3aa3abec1c4f.tar.gz...
-- Extracting source D:/Dev/vcpkg/downloads/xtensor-stack-xtensor-a377fb84c29624e91b6b2451018f3aa3abec1c4f.tar.gz
-- Using source at D:/Dev/vcpkg/buildtrees/xtensor/src/a3abec1c4f-a7da6a8e69.clean
CMake Deprecation Warning at scripts/cmake/vcpkg_check_features.cmake:182 (message):
  calling `vcpkg_check_features` without the `FEATURES` keyword has been
  deprecated.

      Please add the `FEATURES` keyword to the call.
Call Stack (most recent call first):
  ports/xtensor/portfile.cmake:11 (vcpkg_check_features)
  scripts/ports.cmake:142 (include)


-- Found external ninja('1.10.2').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: D:/Dev/vcpkg/packages/xtensor_x64-windows/share/xtensor/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\hp\AppData\Local\vcpkg\archives\51\51e0e0bd4bb66beec284069a92085fbb17dd0456.zip
Building package xtensor[core]:x64-windows... done
Installing package xtensor[core]:x64-windows...
Installing package xtensor[core]:x64-windows... done
Elapsed time for package xtensor:x64-windows: 9.311 s
Starting package 5/6: xtl:x86-windows
Building package xtl[core]:x86-windows...
-- Using cached D:/Dev/vcpkg/downloads/xtensor-stack-xtl-6c017f4a81a59bd52008025a785ce745e5b7f49c.tar.gz
-- Cleaning sources at D:/Dev/vcpkg/buildtrees/xtl/src/45e5b7f49c-287ec8dc4d.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/Dev/vcpkg/downloads/xtensor-stack-xtl-6c017f4a81a59bd52008025a785ce745e5b7f49c.tar.gz
-- Using source at D:/Dev/vcpkg/buildtrees/xtl/src/45e5b7f49c-287ec8dc4d.clean
-- Found external ninja('1.10.2').
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Installing: D:/Dev/vcpkg/packages/xtl_x86-windows/share/xtl/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\hp\AppData\Local\vcpkg\archives\a2\a2548b44630455c58f59b6082d122623cb611a96.zip
Building package xtl[core]:x86-windows... done
Installing package xtl[core]:x86-windows...
Installing package xtl[core]:x86-windows... done
Elapsed time for package xtl:x86-windows: 5.577 s
Starting package 6/6: xtensor:x86-windows
Building package xtensor[core]:x86-windows...
-- Using cached D:/Dev/vcpkg/downloads/xtensor-stack-xtensor-a377fb84c29624e91b6b2451018f3aa3abec1c4f.tar.gz
-- Cleaning sources at D:/Dev/vcpkg/buildtrees/xtensor/src/a3abec1c4f-a7da6a8e69.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/Dev/vcpkg/downloads/xtensor-stack-xtensor-a377fb84c29624e91b6b2451018f3aa3abec1c4f.tar.gz
-- Using source at D:/Dev/vcpkg/buildtrees/xtensor/src/a3abec1c4f-a7da6a8e69.clean
CMake Deprecation Warning at scripts/cmake/vcpkg_check_features.cmake:182 (message):
  calling `vcpkg_check_features` without the `FEATURES` keyword has been
  deprecated.

      Please add the `FEATURES` keyword to the call.
Call Stack (most recent call first):
  ports/xtensor/portfile.cmake:11 (vcpkg_check_features)
  scripts/ports.cmake:142 (include)


-- Found external ninja('1.10.2').
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Installing: D:/Dev/vcpkg/packages/xtensor_x86-windows/share/xtensor/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\hp\AppData\Local\vcpkg\archives\2a\2af5ddd4fb8ebf1f3c7594d0d1d92cdf9da29c6c.zip
Building package xtensor[core]:x86-windows... done
Installing package xtensor[core]:x86-windows...
Installing package xtensor[core]:x86-windows... done
Elapsed time for package xtensor:x86-windows: 5.722 s

Total elapsed time: 1.661 min

The package xtensor:x64-windows provides CMake targets:

    find_package(xtensor CONFIG REQUIRED)
    target_link_libraries(main PRIVATE xtensor xtensor::use_TBB xtensor::optimize xtensor::use_xsimd)

The package xtensor:x86-windows provides CMake targets:

    find_package(xtensor CONFIG REQUIRED)
    target_link_libraries(main PRIVATE xtensor xtensor::use_TBB xtensor::optimize xtensor::use_xsimd)

**Comment by PhoebeHui** [comment]
So this issue only could repro for openblas[core]:x64-windows in your side, right? if any other ports have similar issue?

**Comment by aboongm** [comment]
@PhoebeHui , I think you are right. openblas seems to be the problem. I tried installing shogun. And the installation got stuck same like dlib after starting building openblas. Here is the process:

 D:\Dev\vcpkg> ./vcpkg install shogun shogun:x64-windows
Computing installation plan...
The following packages will be built and installed:
  * blas[core]:x64-windows -> 1
  * blas[core]:x86-windows -> 1
  * curl[core,non-http,schannel,ssl,sspi,winssl]:x64-windows -> 7.74.0#3
  * curl[core,non-http,schannel,ssl,sspi,winssl]:x86-windows -> 7.74.0#3
  * dirent[core]:x64-windows -> 1.23.2
  * dirent[core]:x86-windows -> 1.23.2
  * libiconv[core]:x64-windows -> 1.16#8
  * libiconv[core]:x86-windows -> 1.16#8
  * libxml2[core]:x64-windows -> 2.9.10#5
  * libxml2[core]:x86-windows -> 2.9.10#5
  * lzo[core]:x64-windows -> 2.10#6
  * lzo[core]:x86-windows -> 2.10#6
  * nlopt[core]:x64-windows -> 2.7.0
  * nlopt[core]:x86-windows -> 2.7.0
  * openblas[core]:x64-windows -> 0.3.10
  * openblas[core]:x86-windows -> 0.3.10
  * rxcpp[core]:x64-windows -> 4.1.0-1
  * rxcpp[core]:x86-windows -> 4.1.0-1
    shogun[core]:x64-windows -> 6.1.4#4
    shogun[core]:x86-windows -> 6.1.4#4
  * snappy[core]:x64-windows -> 1.1.8
  * snappy[core]:x86-windows -> 1.1.8
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Detecting compiler hash for triplet x86-windows...
Could not locate cached archive: C:\Users\hp\AppData\Local\vcpkg\archives\ad\ad187cf132317c5233c6ca20e469ba825198b8c0.zip
Could not locate cached archive: C:\Users\hp\AppData\Local\vcpkg\archives\e1\e1557b3296ffcc5c9539524d67ce9f7f4a1f0321.zip
Could not locate cached archive: C:\Users\hp\AppData\Local\vcpkg\archives\18\18011a6ee32336fd387c306fa8440af0f0f8df47.zip
Could not locate cached archive: C:\Users\hp\AppData\Local\vcpkg\archives\2b\2b4f5f22cc4838a9d9a8101e545940d4349d4443.zip
Could not locate cached archive: C:\Users\hp\AppData\Local\vcpkg\archives\f8\f8705df274b3a3235a730136cb1cf3f475ab6f18.zip
Could not locate cached archive: C:\Users\hp\AppData\Local\vcpkg\archives\cb\cb314a8b1c01f6109e3eb0f3df6a67d6300701e8.zip
Could not locate cached archive: C:\Users\hp\AppData\Local\vcpkg\archives\63\6350b58c2912fd59a988bd9c99027ccd365f7a16.zip
Could not locate cached archive: C:\Users\hp\AppData\Local\vcpkg\archives\3d\3de68128c3ea57f64b27386d03b9230adaf54e32.zip
Could not locate cached archive: C:\Users\hp\AppData\Local\vcpkg\archives\a0\a0226380f9f66bb81e8c76bb9f313105248d24e5.zip
Could not locate cached archive: C:\Users\hp\AppData\Local\vcpkg\archives\c7\c740f929ea47854a5c14092978fc7b9253e02dde.zip
Could not locate cached archive: C:\Users\hp\AppData\Local\vcpkg\archives\c9\c953a4c5d8e51b44604ccf6d594e1a6864594853.zip
Could not locate cached archive: C:\Users\hp\AppData\Local\vcpkg\archives\10\1089cba9f48073efc1aecbc3ab7b570e32e0bf18.zip
Could not locate cached archive: C:\Users\hp\AppData\Local\vcpkg\archives\b9\b917a98505649b30131d680cc9143507dc1ed512.zip
Could not locate cached archive: C:\Users\hp\AppData\Local\vcpkg\archives\e9\e94d56fb51e0d0d04695047f633709f7a9298a67.zip
Could not locate cached archive: C:\Users\hp\AppData\Local\vcpkg\archives\ee\ee74fda9d43a60117bae02f2727255d756ec87ca.zip
Could not locate cached archive: C:\Users\hp\AppData\Local\vcpkg\archives\6d\6dbd84d09beb804c5d42217f86c4ae9531564eff.zip
Could not locate cached archive: C:\Users\hp\AppData\Local\vcpkg\archives\05\0532e99735651e69326e53ea7207753c0edb80ec.zip
Could not locate cached archive: C:\Users\hp\AppData\Local\vcpkg\archives\ba\ba046312e68f9b1546e915ddc5973f0fe5c1abd0.zip
Could not locate cached archive: C:\Users\hp\AppData\Local\vcpkg\archives\43\43fc7c37ba25c55db52d22bd2cd7e446786a08af.zip
Could not locate cached archive: C:\Users\hp\AppData\Local\vcpkg\archives\1e\1eb2a7c9f9761af8d42061b9ffea255d990d7ea7.zip
Could not locate cached archive: C:\Users\hp\AppData\Local\vcpkg\archives\24\2453240e6b2cbd86a3f1b25b79664b6188e7840b.zip
Could not locate cached archive: C:\Users\hp\AppData\Local\vcpkg\archives\b3\b3598decc08ed402e9b7ef18c37aebd8823212c7.zip
Starting package 1/22: openblas:x64-windows
Building package openblas[core]:x64-windows...
-- Using cached D:/Dev/vcpkg/downloads/xianyi-OpenBLAS-63b03efc2af332c88b86d4fd8079d00f4b439adf.tar.gz
-- Extracting source D:/Dev/vcpkg/downloads/xianyi-OpenBLAS-63b03efc2af332c88b86d4fd8079d00f4b439adf.tar.gz
-- Applying patch uwp.patch
-- Applying patch fix-space-path.patch
-- Applying patch fix-redefinition-function.patch
-- Applying patch fix-pkg-config.patch
-- Applying patch fix-uwp-build.patch
-- Using source at D:/Dev/vcpkg/buildtrees/openblas/src/0f4b439adf-917c2f6847.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows

**Comment by aboongm** [comment]
@PhoebeHui, Thanks for your help..
Dlib is now installed. I think the problem probably was in installing openblas. What I did is to install from a different user in the same machine from the same vcpkg folder and install dlib.

**Comment by PhoebeHui** [comment]
Glad you got the issue solved, it may be relate to the permission, sorry for not being of much help.
