### ISSUE TITLE
Error: Building package cudnn:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by albertseo1990** [microsoft/vcpkg#17377]
PS C:\Users\Albert Jin Young Seo\ML\vcpkg> .\vcpkg install darknet[opencv-base,cuda,cudnn]:x64-windows
Computing installation plan...
The following packages will be built and installed:
  * cuda[core]:x64-windows -> 10.1#7
  * cudnn[core]:x64-windows -> 7.6.5#1
    darknet[core,cuda,cudnn,opencv-base]:x64-windows -> 2021-01-21
  * ffmpeg[avcodec,avdevice,avfilter,avformat,avresample,core,gpl,postproc,swresample,swscale]:x64-windows -> 4.3.2#4
  * libjpeg-turbo[core]:x64-windows -> 2.0.6
  * liblzma[core]:x64-windows -> 5.2.5#2
  * libpng[core]:x64-windows -> 1.6.37#14
  * libwebp[core,nearlossless,simd,unicode]:x64-windows -> 1.1.0#2
  * opencv[core,dnn,ffmpeg,jpeg,png,quirc,tiff,webp]:x64-windows -> 4.5.1
  * opencv4[core,dnn,ffmpeg,jpeg,png,quirc,tiff,webp]:x64-windows -> 4.5.1
  * protobuf[core]:x64-windows -> 3.15.8
  * pthreads[core]:x64-windows -> 3.0.0#8
  * quirc[core]:x64-windows -> 1.1#2
  * stb[core]:x64-windows -> 2020-09-14
  * tiff[core]:x64-windows -> 4.1.0#1
  * zlib[core]:x64-windows -> 1.2.11#9
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\Albert Jin Young Seo\AppData\Local\vcpkg\archives\01\01b2212e6e551bd035918947d9087307212340fd.zip
Could not locate cached archive: C:\Users\Albert Jin Young Seo\AppData\Local\vcpkg\archives\be\bea8927a5d7760f61d1a40fddcb2614f8ea39773.zip
Could not locate cached archive: C:\Users\Albert Jin Young Seo\AppData\Local\vcpkg\archives\60\60c2c8b8cb076903b6487be2486b13d31e40b649.zip
Could not locate cached archive: C:\Users\Albert Jin Young Seo\AppData\Local\vcpkg\archives\04\0450bd0763dd6653fd38da2474e9e3204071168c.zip
Could not locate cached archive: C:\Users\Albert Jin Young Seo\AppData\Local\vcpkg\archives\0a\0a44375346c1de27f5690fd650041a7d2b295a71.zip
Could not locate cached archive: C:\Users\Albert Jin Young Seo\AppData\Local\vcpkg\archives\9e\9e50bd27e37b755c49867011461edd542bf62755.zip
Could not locate cached archive: C:\Users\Albert Jin Young Seo\AppData\Local\vcpkg\archives\67\67167e3830868c2f121f046df434504e16761a89.zip
Could not locate cached archive: C:\Users\Albert Jin Young Seo\AppData\Local\vcpkg\archives\f8\f83273467bf666bf19630cc12418698b677781f5.zip
Could not locate cached archive: C:\Users\Albert Jin Young Seo\AppData\Local\vcpkg\archives\e8\e832ebb0e1b02c4e399009c7da969a83450ed892.zip
Could not locate cached archive: C:\Users\Albert Jin Young Seo\AppData\Local\vcpkg\archives\ae\aea367c21a310054191163fd140ab44373ff43d0.zip
Could not locate cached archive: C:\Users\Albert Jin Young Seo\AppData\Local\vcpkg\archives\70\70bc38e56cb6860446e9235bc9d75cbce585b6bc.zip
Could not locate cached archive: C:\Users\Albert Jin Young Seo\AppData\Local\vcpkg\archives\71\7180d1fd49f1ed6ea92de72d8aa3085baed6cb8f.zip
Could not locate cached archive: C:\Users\Albert Jin Young Seo\AppData\Local\vcpkg\archives\c4\c4d01aaa9b47208f36a7e81bc0e241756c494689.zip
Could not locate cached archive: C:\Users\Albert Jin Young Seo\AppData\Local\vcpkg\archives\86\868f42fda0c7e9818a93dac3eb4ebe37b9c1612e.zip
Could not locate cached archive: C:\Users\Albert Jin Young Seo\AppData\Local\vcpkg\archives\dd\dd0aa44e1fb14a35b79a197a1578f651affa3b44.zip
Could not locate cached archive: C:\Users\Albert Jin Young Seo\AppData\Local\vcpkg\archives\f0\f074c536f499e58fd0322e66c93a455b19a887c7.zip
Starting package 1/16: cuda:x64-windows
Building package cuda[core]:x64-windows...
-- Found CUDA V11.3.58
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\Albert Jin Young Seo\AppData\Local\vcpkg\archives\01\01b2212e6e551bd035918947d9087307212340fd.zip
Building package cuda[core]:x64-windows... done
Installing package cuda[core]:x64-windows...
Installing package cuda[core]:x64-windows... done
Elapsed time for package cuda:x64-windows: 624.7 ms
Starting package 2/16: cudnn:x64-windows
Building package cudnn[core]:x64-windows...
-- Found CUDA V11.3.58
-- CUDNN_INCLUDE_DIR: CUDNN_INCLUDE_DIR-NOTFOUND
-- CUDNN_LIBRARY: CUDNN_LIBRARY-NOTFOUND
CMake Error at ports/cudnn/portfile.cmake:136 (message):
  Please install manually cuDNN for your CUDA v11.3
Call Stack (most recent call first):
  scripts/ports.cmake:142 (include)

Error: Building package cudnn:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: cudnn:x64-windows
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

Please let me know what is the issue,

Very respectfully,

**Comment by NancyLi1013** [comment]
Hi @albertseo1990 

Thanks for posting this issue.

@cenit Could you please help take a look?
 It seems that it still have problems.

**Comment by cenit** [comment]
unfortunately for cuda 11.3 users have to install cudnn manually and then let the portfile find it... vcpkg is not redistributing cudnn8 for cuda 11.3. 
There was a PR hanging around to add it for some cuda versions but my pr was to fix finding cudnn already installed, not install it

**Comment by NancyLi1013** [comment]
This will be fixed by PR #17331.

**Comment by cenit** [comment]
it will *not* be fixed. It will stay the same, on the contrary the portfile will *NOT* download any cudnn anymore for no-one, not even for cuda versions that were automatic before

**Comment by NancyLi1013** [comment]
Thanks for your information @cenit.

Can you help try to fix this?

**Comment by cenit** [comment]
unfortunately is not fixable.
As @BillyONeal said in https://github.com/microsoft/vcpkg/pull/17331#issuecomment-824302062, due to licensing problems vcpkg cannot redistribute cudnn anymore, so cudnn will always ask users to install cudnn manually if missing.
@albertseo1990 has to download cudnn manually on his system as the log in the initial message is already saying

```
-- Found CUDA V11.3.58
-- CUDNN_INCLUDE_DIR: CUDNN_INCLUDE_DIR-NOTFOUND
-- CUDNN_LIBRARY: CUDNN_LIBRARY-NOTFOUND
CMake Error at ports/cudnn/portfile.cmake:136 (message):
Please install manually cuDNN for your CUDA v11.3
Call Stack (most recent call first):
scripts/ports.cmake:142 (include)
```

**Comment by NancyLi1013** [comment]
So this is intended. We have to download it manually now.

**Comment by cenit** [comment]
> So this is intended. We have to download it manually now.

unfortunately, yes

**Comment by BillyONeal** [comment]
I did make the error message suggest how the user might remediate the problem rather than just saying "go install this" so at least something got better, but yeah, not a good situation

**Comment by NancyLi1013** [comment]
@albertseo1990 
Please download `cudnn `manually. I think this issue can be closed now.
