### ISSUE TITLE
[pthreads] build failure

### ISSUE THREAD

**Issue by casaburf** [microsoft/vcpkg#17387]
Hello, I'm trying to install pthreads, but I get this error...

**Host Environment**
- OS: [Windows 10 ]
- Compiler: VS 2019

**To Reproduce**
`.cd c:/vcpkg
bootstrap-vcpkg.bat
vcpkg.exe install pthread

**Failure logs** 
C:\Windows\System32> cd c:/vcpkg

c:\vcpkg>git clone https://github.com/microsoft/vcpkg
Cloning into 'vcpkg'...
remote: Enumerating objects: 108118, done.
remote: Counting objects: 100% (194/194), done.
remote: Compressing objects: 100% (157/157), done.
remote: Total 108118 (delta 93), reused 80 (delta 37), pack-reused 107924Receiving objects: 100% (108118/108118), 33.00 Receiving objects: 100% (108118/108118), 33.17 MiB | 809.00 KiB/s, done.

Resolving deltas: 100% (67993/67993), done.
Updating files: 100% (7512/7512), done.

c:\vcpkg>cd vcpkg

c:\vcpkg\vcpkg>git pull
Already up to date.

c:\vcpkg\vcpkg>bootstrap-vcpkg.bat
Downloading https://github.com/microsoft/vcpkg-tool/releases/download/2021-02-24-d67989bce1043b98092ac45996a8230a059a2d7e/vcpkg.exe -> C:\vcpkg\vcpkg\vcpkg.exe
Done.

Telemetry
---------
vcpkg collects usage data in order to help us improve your experience.
The data collected by Microsoft is anonymous.
You can opt-out of telemetry by re-running the bootstrap-vcpkg script with -disableMetrics,
passing --disable-metrics to vcpkg on the command line,
or by setting the VCPKG_DISABLE_METRICS environment variable.

Read more about vcpkg telemetry at docs/about/privacy.md

c:\vcpkg\vcpkg>vcpkg.exe install pthread
Computing installation plan...
The following packages will be built and installed:
    pthread[core]:x86-windows -> 3.0.0
  * pthreads[core]:x86-windows -> 3.0.0#8
Additional packages (*) will be modified to complete this operation.
Warning: The following VS instances are excluded because the English language pack is unavailable.
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
Please install the English language pack.
Detecting compiler hash for triplet x86-windows...
A suitable version of powershell-core was not found (required v7.1.0). Downloading portable powershell-core v7.1.0...
Downloading powershell-core...
  https://github.com/PowerShell/PowerShell/releases/download/v7.1.0/PowerShell-7.1.0-win-x86.zip -> C:\vcpkg\vcpkg\downloads\PowerShell-7.1.0-win-x86.zip
Extracting powershell-core...
A suitable version of 7zip was not found (required v18.1.0). Downloading portable 7zip v18.1.0...
Downloading 7zip...
  https://www.nuget.org/api/v2/package/7-Zip.CommandLine/18.1.0 -> C:\vcpkg\vcpkg\downloads\7-zip.commandline.18.1.0.nupkg
Extracting 7zip...
A suitable version of nuget was not found (required v5.5.1). Downloading portable nuget v5.5.1...
Downloading nuget...
  https://dist.nuget.org/win-x86-commandline/v5.5.1/nuget.exe -> C:\vcpkg\vcpkg\downloads\22ea847d-nuget.exe
Could not locate cached archive: C:\Users\faust\AppData\Local\vcpkg\archives\b6\b619447183099038b230eb5efd5f388de6b95831.zip
Could not locate cached archive: C:\Users\faust\AppData\Local\vcpkg\archives\d7\d7a8dacbbc73b2a40e431c3e8638df98a3454638.zip
Starting package 1/2: pthreads:x86-windows
Building package pthreads[core]:x86-windows...
-- Trying auto-select mirror...
-- Downloading https://sourceforge.net/projects/pthreads4w//files/pthreads4w-code-v3.0.0.zip/download -> pthreads4w-code-v3.0.0.zip...
-- Skipping hash check for C:/vcpkg/vcpkg/downloads/temp/pthreads4w-code-v3.0.0.zip.
-- The default mirror is in Disaster Recovery mode, trying other mirrors...
-- Trying mirror cfhcable...
-- Using cached C:/vcpkg/vcpkg/downloads/pthreads4w-code-v3.0.0.zip
-- Skipping hash check for C:/vcpkg/vcpkg/downloads/pthreads4w-code-v3.0.0.zip.
-- Extracting source C:/vcpkg/vcpkg/downloads/pthreads4w-code-v3.0.0.zip
-- Applying patch fix-arm-macro.patch
-- Applying patch use-md.patch
-- Using source at C:/vcpkg/vcpkg/buildtrees/pthreads/src/49e541b66c-53502e357c.clean
-- Building x86-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
    Command failed: "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/nmake.exe" -f Makefile all install DESTROOT="C:\\vcpkg\\vcpkg\\packages\\pthreads_x86-windows"
    Working Directory: C:/vcpkg/vcpkg/buildtrees/pthreads/src/49e541b66c-53502e357c.clean
    Error code: 2
    See logs for more information:
      C:\vcpkg\vcpkg\buildtrees\pthreads\nmake-build-x86-windows-release-out.log
      C:\vcpkg\vcpkg\buildtrees\pthreads\nmake-build-x86-windows-release-err.log

Call Stack (most recent call first):
  ports/pthreads/portfile.cmake:38 (vcpkg_execute_required_process)
  scripts/ports.cmake:142 (include)

Error: Building package pthreads:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: pthreads:x86-windows
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

Additionally, attach any relevant sections from the log files above.

c:\vcpkg\vcpkg>

**Comment by JonLiu1993** [comment]
@casaburf ,please provide logs:
````
C:\vcpkg\vcpkg\buildtrees\pthreads\nmake-build-x86-windows-release-out.log
C:\vcpkg\vcpkg\buildtrees\pthreads\nmake-build-x86-windows-release-err.log
````

**Comment by casaburf** [comment]
Hello, 
[nmake-build-x86-windows-release-err.log](https://github.com/microsoft/vcpkg/files/6342422/nmake-build-x86-windows-release-err.log)
[nmake-build-x86-windows-release-out.log](https://github.com/microsoft/vcpkg/files/6342423/nmake-build-x86-windows-release-out.log)


> @casaburf ,please provide logs:
> 
> ```
> C:\vcpkg\vcpkg\buildtrees\pthreads\nmake-build-x86-windows-release-out.log
> C:\vcpkg\vcpkg\buildtrees\pthreads\nmake-build-x86-windows-release-err.log
> ```

HEllo, here the logs

[nmake-build-x86-windows-release-err.log](https://github.com/microsoft/vcpkg/files/6342427/nmake-build-x86-windows-release-err.log)
[nmake-build-x86-windows-release-out.log](https://github.com/microsoft/vcpkg/files/6342428/nmake-build-x86-windows-release-out.log)

**Comment by JonLiu1993** [comment]
@casaburf ,It seems that your issue not related to vcpkg. I have investigated a lot of related information on the Internet. You can refer to this [one](https://social.msdn.microsoft.com/Forums/en-US/c521da50-7326-4697-9cd6-d2d9e0a9b8be/nmake-fatal-error-u1077-quotcprogram-filesmicrosoft-visual-studio-8vcbinclexequot?forum=Vsexpressvc).

**Comment by casaburf** [comment]
> @casaburf ,It seems that your issue not related to vcpkg. I have investigated a lot of related information on the Internet. You can refer to this [one](https://social.msdn.microsoft.com/Forums/en-US/c521da50-7326-4697-9cd6-d2d9e0a9b8be/nmake-fatal-error-u1077-quotcprogram-filesmicrosoft-visual-studio-8vcbinclexequot?forum=Vsexpressvc).

HEllo @JonLiu1993 sorry, I read the topic, but I didn't understant what I should do...

**Comment by JonLiu1993** [comment]
Please reinstall the visual studio English installation package, clone VCPKG again, and then reinstall

**Comment by casaburf** [comment]
> Please reinstall the visual studio English installation package, clone VCPKG again, and then reinstall

Hello @JonLiu1993 thank you! I think the installation was succesfully


```
C:\Windows\System32>cd C:\vcpkg

C:\vcpkg>git clone https://github.com/microsoft/vcpkg
Cloning into 'vcpkg'...
remote: Enumerating objects: 108118, done.
remote: Counting objects: 100% (193/193), done.
remote: Compressing objects: 100% (146/146), done.
remote: Total 108118 (delta 95), reused 99 (delta 47), pack-reused 107925Receiving objects: 100% (108118/108118), 32.58 Receiving objects: 100% (108118/108118), 32.92 MiB | 717.00 KiB/s, done.

Resolving deltas: 100% (67987/67987), done.
Updating files: 100% (7512/7512), done.

C:\vcpkg>git pull
fatal: not a git repository (or any of the parent directories): .git

C:\vcpkg>cd vcpkg

C:\vcpkg\vcpkg>git pull
Already up to date.

C:\vcpkg\vcpkg>bootstrap-vcpkg.bat
Downloading https://github.com/microsoft/vcpkg-tool/releases/download/2021-02-24-d67989bce1043b98092ac45996a8230a059a2d7e/vcpkg.exe -> C:\vcpkg\vcpkg\vcpkg.exe
Done.

Telemetry
---------
vcpkg collects usage data in order to help us improve your experience.
The data collected by Microsoft is anonymous.
You can opt-out of telemetry by re-running the bootstrap-vcpkg script with -disableMetrics,
passing --disable-metrics to vcpkg on the command line,
or by setting the VCPKG_DISABLE_METRICS environment variable.

Read more about vcpkg telemetry at docs/about/privacy.md

C:\vcpkg\vcpkg>vcpkg.exe install pthread
Computing installation plan...
The following packages will be built and installed:
    pthread[core]:x86-windows -> 3.0.0
  * pthreads[core]:x86-windows -> 3.0.0#8
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x86-windows...
A suitable version of powershell-core was not found (required v7.1.0). Downloading portable powershell-core v7.1.0...
Downloading powershell-core...
  https://github.com/PowerShell/PowerShell/releases/download/v7.1.0/PowerShell-7.1.0-win-x86.zip -> C:\vcpkg\vcpkg\downloads\PowerShell-7.1.0-win-x86.zip
Extracting powershell-core...
A suitable version of 7zip was not found (required v18.1.0). Downloading portable 7zip v18.1.0...
Downloading 7zip...
  https://www.nuget.org/api/v2/package/7-Zip.CommandLine/18.1.0 -> C:\vcpkg\vcpkg\downloads\7-zip.commandline.18.1.0.nupkg
Extracting 7zip...
A suitable version of nuget was not found (required v5.5.1). Downloading portable nuget v5.5.1...
Downloading nuget...
  https://dist.nuget.org/win-x86-commandline/v5.5.1/nuget.exe -> C:\vcpkg\vcpkg\downloads\22ea847d-nuget.exe
Could not locate cached archive: C:\Users\faust\AppData\Local\vcpkg\archives\3d\3dca9685414f3684bb63e67420bcf1bf0b2a1c56.zip
Could not locate cached archive: C:\Users\faust\AppData\Local\vcpkg\archives\94\94e9a1b8a804d9c95cd33d3fedad99cddd8e273b.zip
Starting package 1/2: pthreads:x86-windows
Building package pthreads[core]:x86-windows...
-- Trying auto-select mirror...
-- Downloading https://sourceforge.net/projects/pthreads4w//files/pthreads4w-code-v3.0.0.zip/download -> pthreads4w-code-v3.0.0.zip...
-- Skipping hash check for C:/vcpkg/vcpkg/downloads/temp/pthreads4w-code-v3.0.0.zip.
-- The default mirror is in Disaster Recovery mode, trying other mirrors...
-- Trying mirror cfhcable...
-- Using cached C:/vcpkg/vcpkg/downloads/pthreads4w-code-v3.0.0.zip
-- Skipping hash check for C:/vcpkg/vcpkg/downloads/pthreads4w-code-v3.0.0.zip.
-- Extracting source C:/vcpkg/vcpkg/downloads/pthreads4w-code-v3.0.0.zip
-- Applying patch fix-arm-macro.patch
-- Applying patch use-md.patch
-- Using source at C:/vcpkg/vcpkg/buildtrees/pthreads/src/49e541b66c-53502e357c.clean
-- Building x86-windows-rel
-- Building x86-windows-rel done
-- Building x86-windows-dbg
-- Building x86-windows-dbg done
-- Installing: C:/vcpkg/vcpkg/packages/pthreads_x86-windows/share/pthreads/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\faust\AppData\Local\vcpkg\archives\3d\3dca9685414f3684bb63e67420bcf1bf0b2a1c56.zip
Building package pthreads[core]:x86-windows... done
Installing package pthreads[core]:x86-windows...
Installing package pthreads[core]:x86-windows... done
Elapsed time for package pthreads:x86-windows: 51.41 s
Starting package 2/2: pthread:x86-windows
Building package pthread[core]:x86-windows...
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\faust\AppData\Local\vcpkg\archives\94\94e9a1b8a804d9c95cd33d3fedad99cddd8e273b.zip
Building package pthread[core]:x86-windows... done
Installing package pthread[core]:x86-windows...
Installing package pthread[core]:x86-windows... done
Elapsed time for package pthread:x86-windows: 116.1 ms

Total elapsed time: 4.079 min


C:\vcpkg\vcpkg>

```
