### ISSUE TITLE
vcpkg manifest install dies with no output

### ISSUE THREAD

**Issue by wjk** [microsoft/vcpkg#17383]
**Describe the bug**

I am using vcpkg to manage the dependencies for my vcxproj-based Windows C++ project. I recently reimaged my dev box, and installed the latest version of vcpkg. Now, when I build my vcxproj, vcpkg exits with code 1 immediately after “Detecting compiler hash for triplet” with no error message and no context as to what’s going wrong. It simply dies.

**Environment**

* Windows 10, build 23159
* Visual Studio version 16.10.0 preview 2.0
* MSVC cl.exe version 19.29.30031
* `$env:VCPKG_BINARY_SOURCES` value is `files,D:\William\Documents\.vcpkg-cache,readwrite`
* `$env:VCPKG_FEATURE_FLAGS` value is `manifest`
* vcpkg release 2021-02-24-d67989bce1043b98092ac45996a8230a059a2d7e

Command line:

```
"D:\William\Documents\vcpkg\scripts\buildsystems\msbuild\..\..\..\vcpkg.exe" install  --x-wait-for-lock --triplet "x64-windows" --vcpkg-root "D:\William\Documents\vcpkg\scripts\buildsystems\msbuild\..\..\..\\" "--x-manifest-root=D:\Projects\Sunburst.MRTCore\\" "--x-install-root=D:\Projects\Sunburst.MRTCore\vcpkg_installed\\"
```

**To Reproduce**

1. `git clone git@github.com:SunburstApps/MRTCore`
2. Open `src\MrtCore.sln` in Visual Studio
3. Build `MRM` project

**Expected behavior**

It should install the packages listed in `vcpkg.json`.

**Failure logs**

There aren't any.

**Comment by PhoebeHui** [comment]
@wjk, this is a VS issue in preview version, it's already tracked by vs feedback tickets https://developercommunity.visualstudio.com/t/vcvarsallbat-now-fails-if--vcvars_ver-i/1400395.

Related to https://github.com/microsoft/vcpkg/issues/17319.
BTW, I can't repro this issue with VS2019 16.9.3.

**Comment by PhoebeHui** [comment]
I reopened issue https://github.com/microsoft/vcpkg/issues/17319 for tracking this issue, may be we could add some message for this.
