### ISSUE TITLE
[inih] Library and include paths aren't exposed

### ISSUE THREAD

**Issue by SamuelMarks** [microsoft/vcpkg#17385]
**Host Environment**
- OS: macOS 11.1 (20C69)
- Compiler: Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin20.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**To Reproduce**
`./vcpkg install inih`

**Failure logs** 
No error but no hints on how to include the library.

**Additional context**
Experimented a little with different approaches, see:
```cmake
cmake_minimum_required(VERSION 3.4)
cmake_policy(SET CMP0048 NEW)
project(pp VERSION 0.0.0 LANGUAGES C)

set(src "src/main.c")

find_path(INIH_INCLUDE_DIRS "ini.h")
message(INIH_INCLUDE_DIRS = ${INIH_INCLUDE_DIRS})
#find_library(ini REQUIRED)
get_filename_component(INIH_LIB_DIR ${INIH_INCLUDE_DIRS} DIRECTORY)
set(INIH_LIB_DIR "${INIH_LIB_DIR}/lib")
#add_library(inih IMPORTED "${INIH_LIB_DIR}/libinih.a")
find_library(libinih PATHS ${INIH_LIB_DIR} REQUIRED)  # Could not find libinih using the following names:
# find_package(inih CONFIG REQUIRED HINTS ${INIH_LIB_DIR})

add_executable("${PROJECT_NAME}" "${src}")
target_include_directories("${PROJECT_NAME}" PRIVATE "${INIH_INCLUDE_DIRS}")
target_link_libraries("${PROJECT_NAME}" PRIVATE libinih)
```

But even though I can see `"${INIH_LIB_DIR}/libinih.a"` right there I can't add it as a dependency (at least not without cheating and adding the full absolute path to `target_link_libraries`).

EDIT: Started working directly with meson and upgrade the package in #17388

**Comment by JackBoosY** [comment]
After swith to meson, I think we should add a `unofficial-inih-config.cmake.in` to solve this. 
See [example](https://github.com/microsoft/vcpkg/blob/master/ports/libvpx/unofficial-libvpx-config.cmake.in).

**Comment by SamuelMarks** [comment]
@JackBoosY Hmm I'm confused on what that should look like. I committed it up though anyway.

**Comment by mulderp** [comment]
After running vcpkg install inih I got the inih.lib file but no CMake directions how to link it into my project.
I tried add_target_library(main inih) but this was not giving the desired result. What should be the right way to build a project with this lib?

**Comment by SamuelMarks** [comment]
@mulderp For my own project I hacked together this, note that on Windows you'll need to install pkg-config (e.g., from [here](https://sourceforge.net/projects/pkgconfiglite/files/0.28-1/)):

```cmake
include(FindPkgConfig)

pkg_search_module(INIH libinih)
find_path(INIH_INCLUDE_DIRS "ini.h")

if (pkgcfg_lib_INIH_inih STREQUAL "" OR NOT DEFINED pkgcfg_lib_INIH_inih OR CMAKE_SYSTEM_NAME STREQUAL "Windows")
    get_filename_component(INIH_LIBS "${INIH_INCLUDE_DIRS}" DIRECTORY)
    set(pkgcfg_lib_INIH_inih "${INIH_LIBS}/lib/inih.lib")
    if (NOT EXISTS "${pkgcfg_lib_INIH_inih}")
        set(pkgcfg_lib_INIH_inih "${INIH_LIBS}/lib/libinih.a")
    endif ()
endif ()

if (CMAKE_SYSTEM_NAME STREQUAL "Windows")
    get_filename_component(INIH_LIBS "${INIH_INCLUDE_DIRS}" DIRECTORY)
endif ()

target_link_libraries (
        "${PROJECT_NAME}"
        PRIVATE
        "${pkgcfg_lib_INIH_inih}"
)
```
