### ISSUE TITLE
[New Port Request] NVIDIA Flex

### ISSUE THREAD

**Issue by morphogencc** [microsoft/vcpkg#17382]
Library name: NVIDIA Flex

Library description: FleX is a particle based simulation technique for real-time visual effects.  It's developed by NVIDIA and complementary to PhysX, which is already ported to vcpkg.

Source repository URL: https://github.com/NVIDIAGameWorks/FleX

Project homepage (if different from the source repository): https://developer.nvidia.com/flex

Anything else that is useful to know when adding (such as optional features the library may have that should be included): It is designed to run with either CUDA or DirectX; this would be a good option to make sure is included.

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by morphogencc** [comment]
@PhoebeHui NVIDIA Flex has come up again in my workflow; is it possible to re-open this issue?

**Comment by PhoebeHui** [comment]
Unfortunately, we can’t reopen this issue until a PR is opened.

**Comment by morphogencc** [comment]
I see -- it doesn't seem like it's being worked on if it's closed, so reading between the lines here, is the only way it's going to be added to vcpkg is if I do it myself and submit a PR?

**Comment by PhoebeHui** [comment]
We're happy to answer any questions we can to support this effort, but for now we'd prefer to support you or other contributors than to take ownership ourselves. None of our core team is very familiar with NVIDIA Flex, so we feel you'll do a much better job than we could! so please consider making a PR for this.
