### ISSUE TITLE
[New Port Request] taoPQ

### ISSUE THREAD

**Issue by caseyuhrig** [microsoft/vcpkg#17384]
Library name: taoPQ

Library description: A modern client library for PostgreSQL

Source repository URL: https://github.com/taocpp/taopq

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included): Requires libpq which vcpkg already supports!

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
