### ISSUE TITLE
[forge:x64-windows] Compiles ok, but Forge_FOUND==false after find_package

### ISSUE THREAD

**Issue by HWiman-ICONIC** [microsoft/vcpkg#17396]
vcpkg version  2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e
forge version 1.0.5
OS Windows 10

- `.\vcpkg.exe install forge:x64-windows` successful
- find_package(Forge CONFIG REQUIRED),    target_link_libraries(main PRIVATE Forge::forge) provided
- VisualStudio->Create New CMake project
- Insert `find_package(Forge CONFIG REQUIRED)` in generated CMakeLists.txt
- Error: 
[CMake] CMake Error at C:/Dev/vcpkg/scripts/buildsystems/vcpkg.cmake:861 (_find_package):
1> [CMake]   Found package configuration file:
1> [CMake] 
1> [CMake]     C:/Dev/vcpkg/installed/x64-windows/share/forge/ForgeConfig.cmake
1> [CMake] 
1> [CMake]   but it set Forge_FOUND to FALSE so package "Forge" is considered to be NOT
1> [CMake]   FOUND.
1> [CMake] Call Stack (most recent call first):
1> [CMake]   forgetest/CMakeLists.txt:6 (find_package)
1> [CMake] -- Configuring incomplete, errors occurred!

[CMakeOutput.log](https://github.com/microsoft/vcpkg/files/6345678/CMakeOutput.log)

**Comment by autoantwort** [comment]
Please set the toolchain file: https://github.com/microsoft/vcpkg/blob/master/docs/users/integration.md#cmake-toolchain-file-recommended-for-open-source-cmake-projects

**Comment by JackBoosY** [comment]
Confirmed.
