### ISSUE TITLE
[<netcdf>] build failure

### ISSUE THREAD

**Issue by Sjurk** [microsoft/vcpkg#17398]
**Host Environment**
- Ubuntu Mate
- Compiler: cxx 9

When including netcdf-c in a project, hdf5 is also included, and in turn szip & zlib.
The error message is:

CMake Error at /usr/local/vcpkg/packages/hdf5_x64-linux/share/hdf5/hdf5-config.cmake:146 (include):
  include could not find requested file:

    /usr/local/vcpkg/packages/szip_x64-linux/share/hdf5/hdf5-targets.cmake

The missing file's path is concatenated from "/usr/local/vcpkg/packages/szip_x64-linux" and "/share/hdf5/hdf5-targets.cmake", the former contained in ${PACKAGE_PREFIX_DIR}. 
It seems that this variable is changed in the call chain, causing cmake to look for hdf5-targets.cmake somewhere down the szip tree.

**Comment by NancyLi1013** [comment]
Hi @Sjurk 

Thanks for posting this issue. 

Could you please help provide your project sample?

**Comment by Sjurk** [comment]
Thanks,
Not sure if this will make things any clearer. My tree of CMakeLists.txt files was
originally created by CMakeConverter. An underlying problem is that I'm a noob 
in Linux, CMake, and vcpkg; trying to migrate from Visual Studio IDE. For clarity,
I omit the subprojects' CMakeLists.txt files, since the error occurs at root level.

## CMakeLists.txt:

cmake_minimum_required(VERSION 3.20 FATAL_ERROR)

set(CMAKE_SYSTEM_VERSION 10.0.17134.0 CACHE STRING "" FORCE)

#specify the C++ standard
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED True)

project(ENKI C CXX)

#Set target arch type if empty. Visual studio solution generator provides it.
if(NOT CMAKE_VS_PLATFORM_NAME)
    set(CMAKE_VS_PLATFORM_NAME "x64")
endif()
message( STATUS "${CMAKE_VS_PLATFORM_NAME} architecture in use")
message( STATUS "${CMAKE_SYSTEM_NAME} operating system is targeted")

if(NOT ("${CMAKE_VS_PLATFORM_NAME}" STREQUAL "Any CPU"
     OR "${CMAKE_VS_PLATFORM_NAME}" STREQUAL "Mixed Platforms"
     OR "${CMAKE_VS_PLATFORM_NAME}" STREQUAL "linux_x64"
     OR "${CMAKE_VS_PLATFORM_NAME}" STREQUAL "x64"))
    message(FATAL_ERROR "${CMAKE_VS_PLATFORM_NAME} arch is not supported!")
endif()

#Global configuration types
set(CMAKE_CONFIGURATION_TYPES
    "Debug"
    "Release"
    CACHE STRING "" FORCE
)

#Global compiler options
if(MSVC)
    # remove default flags provided with CMake for MSVC
    set(CMAKE_C_FLAGS "")
    set(CMAKE_C_FLAGS_DEBUG "")
    set(CMAKE_C_FLAGS_RELEASE "")
    set(CMAKE_CXX_FLAGS "")
    set(CMAKE_CXX_FLAGS_DEBUG "")
    set(CMAKE_CXX_FLAGS_RELEASE "")
endif()

#Global linker options
if(MSVC)
    # remove default flags provided with CMake for MSVC
    set(CMAKE_EXE_LINKER_FLAGS "")
    set(CMAKE_MODULE_LINKER_FLAGS "")
    set(CMAKE_SHARED_LINKER_FLAGS "")
    set(CMAKE_STATIC_LINKER_FLAGS "")
    set(CMAKE_EXE_LINKER_FLAGS_DEBUG "${CMAKE_EXE_LINKER_FLAGS}")
    set(CMAKE_MODULE_LINKER_FLAGS_DEBUG "${CMAKE_MODULE_LINKER_FLAGS}")
    set(CMAKE_SHARED_LINKER_FLAGS_DEBUG "${CMAKE_SHARED_LINKER_FLAGS}")
    set(CMAKE_STATIC_LINKER_FLAGS_DEBUG "${CMAKE_STATIC_LINKER_FLAGS}")
    set(CMAKE_EXE_LINKER_FLAGS_RELEASE "${CMAKE_EXE_LINKER_FLAGS}")
    set(CMAKE_MODULE_LINKER_FLAGS_RELEASE "${CMAKE_MODULE_LINKER_FLAGS}")
    set(CMAKE_SHARED_LINKER_FLAGS_RELEASE "${CMAKE_SHARED_LINKER_FLAGS}")
    set(CMAKE_STATIC_LINKER_FLAGS_RELEASE "${CMAKE_STATIC_LINKER_FLAGS}")
endif()

#Nuget packages function stub.
function(use_package TARGET PACKAGE VERSION)
    message(WARNING "No implementation of use_package. Create yours. "
                    "Package \"${PACKAGE}\" with version \"${VERSION}\" "
                    "for target \"${TARGET}\" is ignored!")
endfunction()

#Common utils
#include(CMake/Utils.cmake)

#Additional Global Settings(add specific info there)
include(CMake/GlobalSettingsInclude.cmake OPTIONAL)

#Use solution folders feature
set_property(GLOBAL PROPERTY USE_FOLDERS ON)

#Make projects should use: "-DCMAKE_TOOLCHAIN_FILE=/usr/local/vcpkg/scripts/buildsystems/vcpkg.cmake"

#https://stackoverflow.com/questions/28887680/linking-boost-library-with-boost-use-static-lib-off-on-windows

#Set warnings on and enable debugging
SET( CMAKE_C_FLAGS "-Wall -q" )

#set(Boost_DEBUG ON)
if("${CMAKE_SYSTEM_NAME}" STREQUAL "Linux")
    SET (${cmakeExecutable}: "/snap/cmake/current/bin/cmake")
endif()

#SET (BOOST_ROOT "$ENV{BOOST_ROOT}")

set(CMAKE_FIND_LIBRARY_SUFFIXES ".so" ".a")    # Prefer dynamic libs

set (CMAKE_MODULE_PATH "/snap/cmake/858/share/cmake-3.20/Modules/FindPython3.cmake")

include(FindBoost)
include(FindPython3)
#include(FindHDF5)

set(Boost_USE_STATIC_LIBS OFF)
set(Boost_USE_MULTITHREADED ON)
set(Boost_USE_STATIC_RUNTIME OFF)
add_definitions( -DBOOST_ALL_NO_LIB )
add_definitions( -DBOOST_ALL_DYN_LINK )

set(CMAKE_THREAD_LIBS_INIT "-lpthread")
set(CMAKE_HAVE_THREADS_LIBRARY 1)
set(CMAKE_USE_WIN32_THREADS_INIT 0)
set(CMAKE_USE_PTHREADS_INIT 1)
set(THREADS_PREFER_PTHREAD_FLAG ON)
set(python_DIR "/usr/bin")
set(Eigen3_DIR "/usr/local/vcpkg/installed/x64-linux/share/eigen3")
set(szip_DIR "/usr/local/vcpkg/packages/szip_x64-linux/share/szip")
set(hdf5_DIR "/usr/local/vcpkg/packages/hdf5_x64-linux/share/hdf5")
#set(netCDF_DIR "/usr/local/vcpkg/packages/netcdf-c_x64-linux/share/netcdf")
set(netCDFCxx_DIR "/usr/local/vcpkg/packages/netcdf-cxx4_x64-linux/share/netCDFCxx")


### Section of find_package calls, with messages showing the value of ${PACKAGE_PREFIX_DIR} beteen each call

message( STATUS "pre-boost PACKAGE_PREFIX_DIR " ${PACKAGE_PREFIX_DIR})

find_package(Boost COMPONENTS chrono filesystem locale serialization thread REQUIRED)  # date_time 
if( Boost_FOUND )
    message( STATUS "Boost found at " ${Boost_DIR})
endif()

message( STATUS "pre-eigen PACKAGE_PREFIX_DIR " ${PACKAGE_PREFIX_DIR})

find_package(Eigen3 CONFIG REQUIRED)
if( Eigen3_FOUND )
    message( STATUS "Eigen3 found at " ${Eigen3_DIR} )
endif()

message( STATUS "pre-gdal PACKAGE_PREFIX_DIR " ${PACKAGE_PREFIX_DIR})

find_package(GDAL REQUIRED)  # date_time 
if( GDAL_FOUND )
    message( STATUS "GDAL found at " ${GDAL_DIR} )
endif()

message( STATUS "pre-python PACKAGE_PREFIX_DIR " ${PACKAGE_PREFIX_DIR})

find_package(PythonLibs 3 REQUIRED)  # date_time 
if( PythonLibs_FOUND )
    message( STATUS "python3 found at " ${PythonLibs_DIR}  )
endif()

message( STATUS "pre-hdf5 PACKAGE_PREFIX_DIR " ${PACKAGE_PREFIX_DIR})

find_package(hdf5 CONFIG REQUIRED)
if( hdf5_FOUND )
    message( STATUS "hdf5 found at " ${hdf5_DIR} )
endif()

message( STATUS "pre-netcdf PACKAGE_PREFIX_DIR " ${PACKAGE_PREFIX_DIR})

find_package(netCDF CONFIG REQUIRED)
if( netCDF_FOUND )
    message( STATUS "netCDF found at " ${netCDF_DIR} )
endif()

message( STATUS "pre-netcdfcxx PACKAGE_PREFIX_DIR " ${PACKAGE_PREFIX_DIR})

find_package(netCDFCxx CONFIG REQUIRED)
if( netCDFCxx_FOUND )
    message( STATUS "netCDFCxx found at " ${netCDFCxx_DIR}  )
endif()


### Sub-projects
add_subdirectory(DHM)
add_subdirectory(Methods)
add_subdirectory(EnkiAPI)
add_subdirectory(PyEnki)


## Console Output from root CMaksLists.txt

sjur@enkilinux:~/EnkiServer$ sudo rm -r build
sjur@enkilinux:~/EnkiServer$ sudo /snap/bin/cmake -S . -B build
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- x64 architecture in use
-- Linux operating system is targeted
-- Found Boost: /usr/local/lib/cmake/Boost-1.75.0/BoostConfig.cmake (found version "1.75.0")  
-- Found Python3: /usr/bin/python3.8 (found version "3.8.5") found components: Interpreter 
-- pre-boost PACKAGE_PREFIX_DIR 
-- Found Boost: /usr/local/lib/cmake/Boost-1.75.0/BoostConfig.cmake (found version "1.75.0") found components: chrono filesystem locale serialization thread 
-- Boost found at /usr/local/lib/cmake/Boost-1.75.0
-- pre-eigen PACKAGE_PREFIX_DIR 
-- Eigen3 found at /usr/local/vcpkg/installed/x64-linux/share/eigen3
-- pre-gdal PACKAGE_PREFIX_DIR /usr/local/vcpkg/installed/x64-linux
-- Found GDAL: /usr/lib/libgdal.so (found version "3.2.1") 
-- GDAL found at 
-- pre-python PACKAGE_PREFIX_DIR /usr/local/vcpkg/installed/x64-linux
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.8.so (found suitable version "3.8.5", minimum required is "3") 
-- python3 found at 
-- pre-hdf5 PACKAGE_PREFIX_DIR /usr/local/vcpkg/installed/x64-linux
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
CMake Error at /usr/local/vcpkg/packages/hdf5_x64-linux/share/hdf5/hdf5-config.cmake:146 (include):
  include could not find requested file:

    /usr/local/vcpkg/packages/szip_x64-linux/share/hdf5/hdf5-targets.cmake
Call Stack (most recent call first):
  CMakeLists.txt:197 (find_package)


-- hdf5 found at /usr/local/vcpkg/packages/hdf5_x64-linux/share/hdf5
-- pre-netcdf PACKAGE_PREFIX_DIR /usr/local/vcpkg/packages/szip_x64-linux
-- netCDF found at /usr/lib/x86_64-linux-gnu/cmake/netCDF
-- pre-netcdfcxx PACKAGE_PREFIX_DIR /usr
-- netCDFCxx found at /usr/local/vcpkg/packages/netcdf-cxx4_x64-linux/share/netCDFCxx

## Console Output from four sub-project CMaksLists.txt

Starting on DHM.CMakeLists
-- Boost_INCLUDE_DIRS = /usr/local/include
-- Boost_LIBRARY_DIRS = /usr/local/lib
-- Boost_LIBRARIES = Boost::chronoBoost::filesystemBoost::localeBoost::serializationBoost::thread


Starting on Methods.CMakeLists
-- Boost_INCLUDE_DIRS = /usr/local/include
-- Boost_LIBRARY_DIRS = /usr/local/lib
-- Boost_LIBRARIES = Boost::chronoBoost::filesystemBoost::localeBoost::serializationBoost::thread


Starting on EnkiAPI.CMakeLists


Starting on PyEnki.CMakeLists
-- Configuring incomplete, errors occurred!
See also "/home/sjur/EnkiServer/build/CMakeFiles/CMakeOutput.log".
See also "/home/sjur/EnkiServer/build/CMakeFiles/CMakeError.log".
sjur@enkilinux:~/EnkiServer$ 

[CMakeError.log](https://github.com/microsoft/vcpkg/files/6348668/CMakeError.log)
[CMakeOutput.log](https://github.com/microsoft/vcpkg/files/6348671/CMakeOutput.log)

**Comment by NancyLi1013** [comment]
Why do you set these paths?

```
set(szip_DIR "/usr/local/vcpkg/packages/szip_x64-linux/share/szip")
set(hdf5_DIR "/usr/local/vcpkg/packages/hdf5_x64-linux/share/hdf5")
#set(netCDF_DIR "/usr/local/vcpkg/packages/netcdf-c_x64-linux/share/netcdf")
set(netCDFCxx_DIR "/usr/local/vcpkg/packages/netcdf-cxx4_x64-linux/share/netCDFCxx")
```
Factually, we suggest to use the libraries like this:

```
    find_package(netCDF CONFIG REQUIRED)
    target_link_libraries(main PRIVATE netCDF::netcdf)

    find_package(hdf5 CONFIG REQUIRED)
    target_link_libraries(main PRIVATE hdf5::hdf5-static hdf5::hdf5_hl-static)

    find_package(szip CONFIG REQUIRED)
    target_link_libraries(main PRIVATE szip-static)

```
And pass `-DCMAKE_TOOLCHAIN_FILE=vcpkg_root_path\vcpkg\scripts\buildsystems\vcpkg.cmake` to cmake command or set it in CMakeLists.txt.

**Comment by NancyLi1013** [comment]
We must set `CMAKE_TOOLCHAIN_FILE` in CMakeLists.txt or cmake command line in a cmake project. Please see the reference here https://github.com/microsoft/vcpkg/blob/master/docs/examples/installing-and-using-packages.md.

From the error you encountered, I can confirm you didn't set `CMAKE_TOOLCHAIN_FILE ` or set it incorrectly in your project.

**Comment by Sjurk** [comment]
Hello again,

Thanks, it passes that hurdle now :-)

**Comment by NancyLi1013** [comment]
Please let me if you still have other problems about this issue.

**Comment by NancyLi1013** [comment]
Closing this issue for now since inactive thread. Please feel free to reopen this issue if it is still a problem for you.
