### ISSUE TITLE
[qt5-webengine]build failure gen\net/third_party/quiche/src/quic/core/proto/cached_network_parameters.pb.h(17): fatal error C1189

### ISSUE THREAD

**Issue by lhd1996** [microsoft/vcpkg#17414]
[package-build-x64-windows-rel-err.log](https://github.com/microsoft/vcpkg/files/6350631/package-build-x64-windows-rel-err.log)
[package-build-x64-windows-rel-out.zip](https://github.com/microsoft/vcpkg/files/6350645/package-build-x64-windows-rel-out.zip)
package-build-x64-windows-rel-out.log
line 30275: FAILED: obj/QtWebEngineCore/browser_message_filter_qt.obj 
line 30279: gen\net/third_party/quiche/src/quic/core/proto/cached_network_parameters.pb.h(17): fatal error C1189: #error:  This file was generated by an older version of protoc which is

need help...

**Comment by Neumann-A** [comment]
> fatal error C1189: #error: This file was generated by an older version of protoc which is

You cannot have protobuf installed for installing qt5-webengine. If you first install qt5-webengine and then protobuf everything is fine.

**Comment by lhd1996** [comment]
it worked, thanks
