### ISSUE TITLE
[matplot++] <requires nodesoup and fftw3[threads]>

### ISSUE THREAD

**Issue by SKNo** [microsoft/vcpkg#17416]
****

**Is your feature request related to a problem? Please describe.**
I've built `Matplot++` library without any problem `(x64-windows and x64-windows-static)`. However I cannot build simple examples (linktime error).

`Matplot++` requires `nodesoup` (`nodesoup` is available on https://github.com/olvb/nodesoup)
- `error LNK2019: unresolved external symbol "class std::vector<struct nodesoup::Point2D,class std::allocator<struct nodesoup ...`

`Matlab++` seems to require `fftw3[threads]` because of `Cimg`
- `Matplot++` requires  `Cimg` and the `Cimg` built by vcpkg requires  `fftw3[threads]`, so `vcpkg` should build `fftw3[threads]` as a prerequisite for `Cimg`, or if possible `Cimg` should be built with installed version of `fftw3`. I had to rebuild `fftw3 `with `threads` (which forced me to rebuild other packages such as `dlib`). 

**Proposed solution**
Just my thoughts :
- Evidently add `nodesoupe`
- If possible , building `ftw3[threads]` uniquely for `Cimg` or buildind `Cimg` with already `installed` version of `fftw3` such as `fftw3` or `fftw3[openmp]`.   

**Describe alternatives you've considered**
At this moment I would try binary packages of ` Matplotlib++` provided by author https://alandefreitas.github.io/matplotplusplus/.

**Additional context**
Thank you

**Comment by SKNo** [comment]
@leha-bot @JackBoosY  
I've double checked : `vcpkg` builds `nodesoup`, and it copies it at subdirectory `VcpkgDir\installed\x64-windows\debug\lib\Matplot++` (like binary distribution by the author) so I had to add it manually for linking.

**Comment by JackBoosY** [comment]
Confirmed.

**Comment by ras0219-msft** [comment]
Reopened because fftw3[threads] may still not be solved
