### ISSUE TITLE
Building package gflags:x86-mingw-dynamic failed

### ISSUE THREAD

**Issue by zaoguole** [microsoft/vcpkg#17412]
The following files were built for an incorrect architecture:

    D:\code\vcpkg\packages\gflags_x86-mingw-dynamic\debug\bin\libgflags_debug.dll
Expected x86, but was: x64

    D:\code\vcpkg\packages\gflags_x86-mingw-dynamic\bin\libgflags.dll
Expected x86, but was: x64

Found 1 error(s). Please correct the portfile:
    D:\code\vcpkg\ports\gflags\portfile.cmake
-- Performing post-build validation done
Error: Building package gflags:x86-mingw-dynamic failed with: POST_BUILD_CHECKS_FAILED

**Comment by longnguyen2004** [comment]
Do you have the correct compiler on your PATH? Maybe there's a 64 bit compiler that's shadowing the 32 bit compiler.
