### ISSUE TITLE
How do I use the yara port?

### ISSUE THREAD

**Issue by VelocityRa** [microsoft/vcpkg#17427]
Normally when installing a port, doing simply:
```cmake
find_package(myport CONFIG REQUIRED)
target_link_libraries(myproj PRIVATE myport)
```
works.
But the [yara port](https://github.com/microsoft/vcpkg/tree/master/ports/yara) does not seem to install a config file, so the `find_package` fails. I also tried just the `target_link_libraries` with both `yara` and `libyara` (the installed `.lib` is called this) to no avail.

Whatever the method is, it would be useful for instruction to be printed when you install the port, like some ports do. Especially since it seems that you need a non-'standard' way to install it (or I am missing something glaringly obvious).

**Comment by NancyLi1013** [comment]
Hi @VelocityRa 

Thanks for posting this issue.

As you said above, there are no config cmake file and FindYara.cmake for `yara`. So you cannot use `find_package()` to find `yara`.

For most ports that don't provide these files(xxxConfig.cmake or Findxxx.cmake), we use the ports like this:

```
find_library()
find_path()
```

**Comment by VelocityRa** [comment]
Thanks @NancyLi1013!

For anyone coming across this, I ended up using:
```cmake
# Dependency: jansson (needed by yara)
find_package(jansson CONFIG REQUIRED)
target_link_libraries(myproj PRIVATE jansson::jansson)

# Dependency: yara
find_library(YARA_LIBRARY libyara)
target_link_libraries(myproj PRIVATE ${YARA_LIBRARY})
```

I tried to commit these as a helpful message when installing the yara port to save people some time but I actually can't find example code of existing ports that do this 🤔 I'm pretty sure I remember some doing it, was it removed?

Anyway, feel free to close this.

**Comment by NancyLi1013** [comment]
Thanks for your help to do this work.
Do you mean the usage of ports? You want to add the usage for yara, but you cannot find example code of others ports that how to add usage. Please help me confirm if i understand this correctly.

**Comment by VelocityRa** [comment]
Correct, I wanted to make vcpkg print usage instructions for yara, specifically the code i posted above (or similar).

**Comment by NancyLi1013** [comment]
Maybe you can search `usage ` in _ports/_ folder, you will find many usage files listed in `ports/PortName`.

You can refer some of them. Such as https://github.com/microsoft/vcpkg/blob/master/ports/libqrencode/usage
https://github.com/microsoft/vcpkg/blob/master/ports/discord-game-sdk/usage
https://github.com/microsoft/vcpkg/blob/master/ports/nethost/usage

You can install the usage file to `share/${PORT} ` in portfile.cmake.

Note: Please make sure the usage can be used correctly in a cmake project.
