### ISSUE TITLE
How do I set Intel OneAPI MKL as default in vcpkg builds?

### ISSUE THREAD

**Issue by SKNo** [microsoft/vcpkg#17426]
Hi
I am new on `vcpkg` so please bear with me if the answer to my question is obvious.
I would like to set `Intel OneAPI MKL` currently at version `2021.2.0` as my default `blas/lapack` for  all `vcpkg`  builds (instead of `openblas / lapack-refernce`)  ...  example for building, `ArrayFire`, `armadillo`,  etc.
How can I do that?

Thank you

**Comment by PhoebeHui** [comment]
@SKNo, blas/lapack are empty packages and depends on openblas/lapack-refernce now, so even the ports depend on blas/lapack, it actually rely on openblas/lapack-refernce. If you want to change that, you can update https://github.com/microsoft/vcpkg/blob/master/ports/armadillo/CONTROL#L5 to 'openblas, lapack-refernce'.

**Comment by SKNo** [comment]
Got it
thanks
