### ISSUE TITLE
There is a new version of cppwinrt but vcpkg update reports no updates available!

### ISSUE THREAD

**Issue by juandent** [microsoft/vcpkg#1742]
Hi,
I installed the cppwinrt available through vcpkg some months ago. I thought typing 

> vcpkg update

would alert me to the presence of a new version but this is not happening. I know for a fact there is a new version (see  [https://github.com/Microsoft/cppwinrt](url) ) ... is something not working here?

Regards,
Juan

**Comment by ras0219-msft** [comment]
`vcpkg update` is made extremely fast by relying on the locally available port files. These are, in turn, updated to the master copy hosted here during a `git pull` (which is mentioned in the tool output).

However, this master copy must be updated via PRs from users like yourself! This builds a first line of defense against accidental upstream breakages.

It's very easy to submit an upgrade PR and we'd be happy to pull one from you for cppwinrt! There's a bunch of past PRs you can use as reference; for example: https://github.com/Microsoft/vcpkg/pull/1715/files.

To get started, use `vcpkg edit cppwinrt`.

**Comment by juandent** [comment]
I seem to have VS Code installed incorrectly in my machine because I get an error when trying 
> vcpkg edit cppwinrt
How can I fix this?

**Comment by alexkaratarakis** [comment]
@juandent 
Does the following command open VSCode?

`code .`

**Comment by juandent** [comment]
yes

**Comment by juandent** [comment]
One question: how do I get the SHA512?
I got a SHA512 from the commits page but it seems too short compared to what it was before

**Comment by juandent** [comment]
I have a new portfile.cmake file - I would like to propose it via a pull request. How do I do that?

**Comment by KindDragon** [comment]
https://help.github.com/articles/creating-a-pull-request/

**Comment by juandent** [comment]
how do I get the SHA512 for the port file.cmake file?

**Comment by alexkaratarakis** [comment]
@juandent 
If the hash is wrong, `vcpkg` will inform you of that fact and output the correct one.
Alternatively, there is `vcpkg hash <file>`. Without any options, it gives you SHA512.

**Comment by NancyLi1013** [comment]
Hi @juandent, thanks for posting this issue. It seems that this issue has been solved. Please open a new issue if this is still a problem for you.
