### ISSUE TITLE
[Building package realsense2:x86-windows failed with: BUILD_FAILED] build failure

### ISSUE THREAD

**Issue by ritabt** [microsoft/vcpkg#17430]
**Host Environment**
- OS: Windows

**To Reproduce**
git clone https://github.com/Microsoft/vcpkg.git
cd vcpkg
bootstrap-vcpkg.sh
vcpkg integrate install
vcpkg install realsense2

**Failure logs** 

-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:146 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j9
    Working Directory: C:/Users/ritat/source/repos/vcpkg/buildtrees/realsense2/x86-windows-dbg
    See logs for more information:
      C:\Users\ritat\source\repos\vcpkg\buildtrees\realsense2\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:105 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:45 (vcpkg_build_cmake)
  ports/realsense2/portfile.cmake:53 (vcpkg_install_cmake)
  scripts/ports.cmake:142 (include)

Error: Building package realsense2:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: realsense2:x86-windows
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

Additionally, attach any relevant sections from the log files above.

**Additional context**
I can't build librealsense by following the steps on the librealsense github. 
How can I fix this?

**Comment by NancyLi1013** [comment]
Hi @ritabt 

Thanks for posting this issue.

Could you please help provide _C:\Users\ritat\source\repos\vcpkg\buildtrees\realsense2\install-x86-windows-dbg-out.log_?

**Comment by NancyLi1013** [comment]
Closing this for now since there is no active thread.
