### ISSUE TITLE
vcpkg.readthedocs.io is broken: 404 everywhere

### ISSUE THREAD

**Issue by PhilLab** [microsoft/vcpkg#17434]
**Describe the bug**
The documentation https://vcpkg.readthedocs.io, linked to from the main README is broken. I tested on different browsers and systems and the page is lacking the CSS, the Javascript and every site shows a 404:

![grafik](https://user-images.githubusercontent.com/1710255/115671071-69086f80-a34a-11eb-8e5d-9e960f45e30e.png)

**Comment by PhoebeHui** [comment]
@PhilLab, thanks for reporting this issue!

I don't know what happened, @strega-nil, do you know more about this?

**Comment by dg0yt** [comment]
It is not exactly *everywhere*. There is just nothing moving you from https://vcpkg.readthedocs.io/en/latest/ from https://vcpkg.readthedocs.io/en/latest/README/.

**Comment by PhoebeHui** [comment]
@PhilLab, AFAIK, we would migrate documentation from readthedocs to vcpkg new website, and it's very close to the release of the new website currently.

**Comment by PhilLab** [comment]
@PhoebeHui Thanks for the update. What is the URL of the new website?

**Comment by PhoebeHui** [comment]
@PhilLab, https://vcpkg.io/en/index.html is now available to view as a draft! We really appreciate any and all feedback.

**Comment by dg0yt** [comment]
> We really appreciate any and all feedback.

For feedback, simply open news issues?

**Comment by PhoebeHui** [comment]
You can report new issues in https://github.com/vcpkg/vcpkg.github.io/issues.

**Comment by PhoebeHui** [comment]
BTW, you can also find the docs from https://github.com/microsoft/vcpkg/tree/master/docs.
