### ISSUE TITLE
[New Port Request] libopenmpt-modplug

### ISSUE THREAD

**Issue by mxmilkiib** [microsoft/vcpkg#17443]
Library name: libopenmpt-modplug

Library description: libopenmpt can be built in a way that emulates libmodplug, for compatibility with older libmodplug using apps.

Source repository URL: see #503 and #2669

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

`--enable-libmodplug`, available in a few distros already
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=libopenmpt-modplug#n21
https://packages.debian.org/sid/libopenmpt-modplug-dev

This is request related to DJing software Mixxx.

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
