### ISSUE TITLE
[opencv/vcpkg] missing webp.dll from build folder

### ISSUE THREAD

**Issue by cenit** [Microsoft/vcpkg#1744]
Win10 15063.540
vcpkg  0.0.85-2017-08-29-6b1fc769a64eb18ec25e289347ce2043968f706f
VS 15.3.3

I have a strange problem, and I hope that trying to build what is inside this simplified repo you can see an example better than I'll ever be able to explain: https://github.com/cenit/webpdll_test
I don't know why, because from CONTROL file I cannot see any dependencies, not even nested, but it seems that webp.dll is required when running executables dynamically linked with OpenCV. Unfortunately vcpkg does *not* copy webp.dll if I build the solution with the x86-windows triplet, while it (found by accident!) copies it if I build with the x64 one.
I tried to find the problem by myself in order also to prepare a PR with the fix, but without any luck.
Thanks a lot in advance for your help

**Comment by jasjuang** [comment]
The dlls from the current OpenCV port won't copied correctly to your downstream project. My PR #1619 should solve it. Please let me know if it didn't. Hope they will merge it soon.

**Comment by cenit** [comment]
sorry for taking so long to answer. I tried to build you branch but it stops saying
"openblas can only be built for x64 currently". I still would like to build an x86 executable. In 64 bit the webp.dll problem does not even exist in the main branch, so I am not going to test it sorry

**Comment by cenit** [comment]
Sorry I didn't keep up to date with this issue, but now webp.dll is correctly copied to the build folder
