### ISSUE TITLE
[skia] <Vulkan support>

### ISSUE THREAD

**Issue by Joaopmoliveira** [microsoft/vcpkg#17465]
**Is your feature request related to a problem? Please describe.**
When I try creating a GrContext through the makeVulkan function, I receive a null pointer because the macro SK_VULKAN is undefined. This I assume is due to the way vcpkg installs skia on my system.

**Proposed solution**
Build the library with the option "skia_use_vulkan=true" although then it would be difficult to identify if the vulkan SDK is installed?

**Describe alternatives you've considered**
I tried to add the option to the port file but the build process fails. (I am not well versed with build systems...).

**Comment by faserg1** [comment]
@PhoebeHui should be closed? I think Vulkan already supported.

**Comment by FrankXie05** [comment]
@Joaopmoliveira @faserg1  
`Vulkan `is now supported. 
https://github.com/microsoft/vcpkg/blob/6a3dd0874f153f8b375ec26210ea6d41dee3bb26/ports/skia/portfile.cmake#L181
