### ISSUE TITLE
[feature][<opencv>] install vcpkg opencv[python]

### ISSUE THREAD

**Issue by talregev** [microsoft/vcpkg#17474]
`install vcpkg opencv[python]`
Add a python binding of opencv compilation.

**Comment by talregev** [comment]
Disable this line:
https://github.com/microsoft/vcpkg/blob/master/ports/opencv4/0002-install-options.patch#L10
Also opencv looking for numpy in python. 
How we can add a numpy? (with pip?)

**Comment by talregev** [comment]
I change the L10 and remove this change.
after compile with vcpkg:
`-- Could NOT find PythonLibs: Found unsuitable version "3.9.2", but required is exact version "3.9.4" (found optimized;D:/src/vcpkg/installed/x64-windows-static/lib/python39.lib;debug;D:/src/vcpkg/installed/x64-windows-static/lib/python.lib)`

why it demanding exact version of python lib 3.9.4?
also latest python3 of vcpkg is 3.9.2.
also opencv can compile with python 3.2 and more. Where I need to change that?

**Comment by luncliff** [comment]
Probably the file `${SOURCE_PATH}/cmake/OpenCVDetectPython.cmake`? 

https://github.com/microsoft/vcpkg/blob/4b6289b936c71bbdb8f5c65973249132c0946235/ports/opencv4/0002-install-options.patch#L11

[The file](https://github.com/opencv/opencv/blob/master/cmake/OpenCVDetectPython.cmake) is a bit complicated but at a glance, I think specifying `PYTHON_EXECUTABLE` can make different result. 

```cmake
# in portfile.cmake ...
if("python" IN_LIST FEATURES)
    vcpkg_find_acquire_program(PYTHON3)
    list(APPEND ADDITIONAL_BUILD_FLAGS -DPYTHON_EXECUTABLE=${PYTHON3})
endif()
```

https://github.com/microsoft/vcpkg/blob/4b6289b936c71bbdb8f5c65973249132c0946235/ports/opencv4/portfile.cmake#L286-L288

**Comment by luncliff** [comment]
Related Issue: https://github.com/microsoft/vcpkg/discussions/17316

**Comment by luncliff** [comment]
For numpy search, `find_package(Python3)` will do the work. https://cmake.org/cmake/help/latest/module/FindPython3.html

```cmake
cmake_minimum_required(VERSION 3.14)
find_package(Python3 REQUIRED
COMPONENTS
    Interpreter NumPy
)
```

**Comment by talregev** [comment]
It not relevant anymore. Thank you for consider.
