### ISSUE TITLE
vcpkg.txt support!

### ISSUE THREAD

**Issue by cathaysia** [microsoft/vcpkg#17478]
Can I write a vcpkg.txt to tell vcpkg what packages I need? just like requirements.

The VCPKG_TARGET_TRIPLET should not show in this file.

such I has a file:
```txt
# vcpkg.txt
spdlog
cpr
...
```
then `vcpkg -r vcpkg.txt --triplet=x64-windows`

**Comment by Neumann-A** [comment]
as far as I remember vcpkg supports response files. So `./vcpkg.exe @somefile` should work.

**Comment by cathaysia** [comment]
yes, thanks :)

**Comment by cathaysia** [comment]
> 
> 
> as far as I remember vcpkg supports response files. So `./vcpkg.exe @somefile` should work.

But what's the format of response file? Can you give a sample?

**Comment by cathaysia** [comment]
the response like:
```txt
cpr
gettext
spdlog
cxxopts
fmt
```
then the command like: `vcpkg install @vcpkg.txt --triplet=x64-windows`
