### ISSUE TITLE
VCPKG build error on 2020.06  build failure

### ISSUE THREAD

**Issue by kalijana** [microsoft/vcpkg#17476]
**Debian 9 **
- OS: linux
- Compiler: revision
the ./bootstrap-vcpkg.sh fails to build while compiling
CMakeFiles/vcpkglib.dir/src/vcpkg/base/cofffilereader.cpp.o
please find the attached file for details

**Comment by kalijana** [comment]
[vcpkgerror.zip](https://github.com/microsoft/vcpkg/files/6368277/vcpkgerror.zip)

**Comment by autoantwort** [comment]
Your compiler is too old, you need at least gcc 7.x (or another compiler with c++17 support)

**Comment by NancyLi1013** [comment]
Hi @kalijana 

Please let me know if this is still a problem for you when you update gcc to new version.

**Comment by kalijana** [comment]
Hi Nancy it worked with néw gcc , We wanted some help on how to do use the library for a new adruino board . My developments environment is windows with visual studio code

kali

**Comment by JackBoosY** [comment]
@kalijana  Please open an new issue. Thanks.
