### ISSUE TITLE
[New Port Request] playfab/gsdk

### ISSUE THREAD

**Issue by jseward** [microsoft/vcpkg#17477]
Library name: playfab/gsdk

Library description: PlayFab Game Server SDK for C#, C++, and Java environments. The GSDK is used to integrate with PlayFab Multiplayer Servers.

Source repository URL: https://github.com/PlayFab/gsdk

NOTE: Will need cmake support added. See https://github.com/PlayFab/gsdk/pull/70

**Comment by PhoebeHui** [comment]
@jseward, https://github.com/PlayFab/gsdk/pull/70 has been merged, we're happy to accept a PR for this.

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
