### ISSUE TITLE
The library file was not installed correctly

### ISSUE THREAD

**Issue by tangying212** [microsoft/vcpkg#17479]
I used "vcpkg install libssh" to install the library file, everything was successful, but Visual Studio 2019 told me I did not have this library file when I included the header file. This was fine until I reinstalled my Windows system. I don't know what went wrong.

D:\Windows\Program\Vcpkg\App>vcpkg install libssh
Computing installation plan...
The following packages will be built and installed:
    libssh[core,crypto,mbedtls]:x86-windows -> 0.9.5#3
Detecting compiler hash for triplet x86-windows...
Using cached binary package: C:\Users\tangying212\AppData\Local\vcpkg\archives\12\1246a1c404fd1809a0553eee55f4d99e68eba268.zip
Starting package 1/1: libssh:x86-windows
Building package libssh[core,crypto,mbedtls]:x86-windows...
Building package libssh[core,crypto,mbedtls]:x86-windows... done
Installing package libssh[core,crypto,mbedtls]:x86-windows...
Installing package libssh[core,crypto,mbedtls]:x86-windows... done
Elapsed time for package libssh:x86-windows: 72.81 ms

Total elapsed time: 3.18 s

The package libssh is compatible with built-in CMake targets:

    find_package(libssh CONFIG REQUIRED)
    target_link_libraries(main PRIVATE ssh)

D:\Windows\Program\Vcpkg\App>

**Comment by Neumann-A** [comment]
Wrong triplet? Are you maybe building for x64 windows instead of x86?

**Comment by tangying212** [comment]
> rong triplet? Are you maybe building for x64 windows instead of x86?

In fact, I have tried both and neither of them solved the problem I encountered

**Comment by tangying212** [comment]
> Wrong triplet? Are you maybe building for x64 windows instead of x86?

thanks!
