### ISSUE TITLE
vcpkg-tool : problem with cmake tar followed by folder rename

### ISSUE THREAD

**Issue by frivard-coveo** [microsoft/vcpkg#17475]
**Describe the bug**
Features in use : "-compilertracking,manifests,registries,versions"
This is a very rare bug that we observe from time to time on our CI build servers. It has proved incredibly hard to reproduce on-demand.
The symptom is the following:
during the "vcpkg install" phase with registries, sometimes the build would fail with the following output:
```
11:26:34  -- Running vcpkg install
11:26:36  warning: attempting to set builtin baseline in both vcpkg.json and vcpkg-configuration.json
11:26:36      (only one of these should be used; the baseline from vcpkg-configuration.json will be used)C:\jenkins\slaves\516853b941de4b369fcb2ca40e4bdbe9,C:/jenkins/slaves/516853b941de4b369fcb2ca40e4bdbe9/RelWithDebInfo/coveo-cache/ports
11:26:38  A suitable version of cmake was not found (required v3.19.0). Downloading portable cmake v3.19.0...
11:26:38  Downloading cmake...
11:26:38    https://github.com/Kitware/CMake/releases/download/v3.19.2/cmake-3.19.2-win32-x86.zip -> C:\BuildTools\vcpkg\downloads\cmake-3.19.2-win32-x86.zip
11:26:38  Extracting cmake...
11:26:38  A suitable version of 7zip was not found (required v18.1.0). Downloading portable 7zip v18.1.0...
11:26:38  Downloading 7zip...
11:26:38    https://www.nuget.org/api/v2/package/7-Zip.CommandLine/18.1.0 -> C:\BuildTools\vcpkg\downloads\7-zip.commandline.18.1.0.nupkg
11:26:38  Extracting 7zip...
11:26:38  A suitable version of nuget was not found (required v5.5.0). Downloading portable nuget v5.5.0...
11:26:38  Downloading nuget...
11:26:38    https://dist.nuget.org/win-x86-commandline/v5.5.1/nuget.exe -> C:\BuildTools\vcpkg\downloads\22ea847d-nuget.exe
11:27:11  Error: while checking out port vcpkg-cmake with git tree b627b47898864ee5a880cea03b4dea64b9d81953
11:27:11  Error: while renaming C:\BuildTools\vcpkg\buildtrees\versioning\versions\vcpkg-cmake\b627b47898864ee5a880cea03b4dea64b9d81953.tmp to C:\BuildTools\vcpkg\buildtrees\versioning\versions\vcpkg-cmake\b627b47898864ee5a880cea03b4dea64b9d81953: Access is denied.
```
(this is the console output of our Jenkins build server)

The actual problem (Access denied) can happen with pretty much any port, it is not specific to any one. And it seems random (bad) luck; re-running the CI with the exact same conditions and the build will pass just fine. Note that in our environment, a new VM is started for every build, so it's not a case of re-using a VM, and our CI is configured for a single build executor per node, so it is not a concurrency issue.

The error string happens when vcpkg is extracting versions: the pattern is
- create a temp folder
- `git archive` to produce a tar file
- `cmake -E tar xf` to extract the tar file inside the temp folder
- rename temp folder to final name

The error is with the last step. After days of various trial-and-errors, I became convinced that the problem is due to the call to `cmake -E tar xf` by vcpkg; so I opened up the code of CMake, hoping to shed some light into it. And I stumbled upon this:
```
#ifdef WIN32
        // OK, on windows 7 after we untar some files,
        // sometimes we can not rename the directory after
        // the untar is done. This breaks the external project
        // untar and rename code.  So, by default we will wait
        // 1/10th of a second after the untar.  If CMAKE_UNTAR_DELAY
        // is set in the env, its value will be used instead of 100.
        int delay = 100;
        std::string delayVar;
        if (cmSystemTools::GetEnv("CMAKE_UNTAR_DELAY", delayVar)) {
          delay = atoi(delayVar.c_str());
        }
        if (delay) {
          cmSystemTools::Delay(delay);
        }
#endif
```
[Ref here](https://github.com/Kitware/CMake/blob/master/Source/cmcmd.cxx#L1462).

How interesting! Same problem as we have. And -- big surprise! -- adding a random sleep delay does not completely fix the issue. I added `CMAKE_UNTAR_DELAY=0` in the hope of reproducing the error more often, but somehow (I can't explain it) the error happens even *less* often.

I open this issue because I believe some other customers might be unlucky and face the same error.

**Environment**
- OS: Windows Server 2019 (latest patched LTS release)
- Compiler: MSVC Build Tools 16.8.5
- Computer : AWS EC2 with EBS-optimized storage, type C5.2xlarge.

**To Reproduce**
I would really like to give you a nice and easy steps to reproduce it, but I can't.
1. Have a project with vcpkg.json, including dependencies such as much of the boost libraries (they end up like 80 different packages to install)
2. Enable manifests, registries and versions features
2. cmake configure your project (this in turn calls vcpkg install)
2. See error
The error happens at the very beginning, before any compilation happens.

**Expected behavior**
The folder rename should not fail.

**Failure logs** 
Available on-demand (ping me directly), but you won't get much more info than what's described here.

**Additional context**
I made a fork of vcpkg-tool [to which I added a retry step](https://github.com/frivard-coveo/vcpkg-tool/commit/ad06323bbd2b6ca4fbe3e9fa67bf0a3762e3e15d). I did see my debug-log a few times, so I can attest that it does indeed fix the issue for me, but that is really not satisfying. Just adding more random sleep. 
If you have some contacts inside Microsoft that could explain why the directory can't be renamed after the CMake process has returned its exit code, that would be nice.

**Comment by klalumiere** [comment]
I dig a little bit in the CMake code and I found out that they seem to use [libarchive](https://www.libarchive.org/) as backend. I tried to see if some issues were known about `libarchive` on Windows. I found many google posts about having `Access is denied` errors, especially with `7z`, but probably that most (all?) of them are related to actual permission errors, so I'm not sure that they are useful.

**Comment by dg0yt** [comment]
> I added `CMAKE_UNTAR_DELAY=0` in the hope of reproducing the error more often, but somehow (I can't explain it) the error happens even _less_ often.

I dont't think this really maps to zero delay:
https://github.com/Kitware/CMake/blob/88f5d4b24ffce8698c45a61b59ab6cde1bc00a15/Source/kwsys/SystemTools.cxx#L4225-L4227

**Comment by JackBoosY** [comment]
We'll have a discuss later.

**Comment by JackBoosY** [comment]
cc @strega-nil, I think we should consider about this.

**Comment by frivard-coveo** [comment]
We have recently upgraded our CI servers to use the latest release of vcpkg-tool (as well as update to MSVC 16.10!).
And this error happened again today, giving me random build failures. That is really annoying, so I'm making a PR about this.

**Comment by MichaelGoulding** [comment]
I believe ran into this as well as both folders were present after I saw the error:
-- Using source at E:/vcpkg/buildtrees/c4core/src/deps/279dcee24f-d3432006da.clean
CMake Error at ports/c4core/portfile.cmake:50 (file):
  file RENAME failed to rename

    E:/vcpkg/buildtrees/c4core/src/deps/279dcee24f-d3432006da.clean

  to

    E:/vcpkg/buildtrees/c4core/src/4e0d4c0337-8aab8071b0.clean/ext/debugbreak

  because: No such file or directory

Call Stack (most recent call first):
  scripts/ports.cmake:142 (include)

**Comment by simon-winter** [comment]
Note to the apove mentioned ticket i opened: For me it crashes a 100% times at the same package (angle).
I tried using vcpkg install and also manifest mdoe, it doesnt work

**Comment by JackBoosY** [comment]
Okay, please reopen this issue if you meet it again.
