### ISSUE TITLE
[VTK] build failure

### ISSUE THREAD

**Issue by ZhouJJJKKK** [microsoft/vcpkg#17480]
**Host Environment**
- OS: Windows 10
- Compiler: visual studio 2019

**To Reproduce**
`.\vcpkg install vtk:x64-windows'

**Failure logs** 
Firstly, Failed. Status: 56;"Failure when receiving data from the peer".
Then I tried downloading it employing the browser with the source " https://github.com/Kitware/VTK/archive/v8.2.0.tar.gz" and successfully got VTK-8.2.0.tar.gz. I revised its name and copy it into "D:\vcpkg-master\downloads", then run `.\vcpkg install vtk:x64-windows' again.  A new error appeared:
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:96 (message):
  File does not have expected hash:

          File path: [ D:/vcpkg-master/downloads/Kitware-VTK-v8.2.0.tar.gz ]
      Expected hash: [ fd1d9c2872baa6eca7f8105b0057b56ec554e9d5eaf25985302e7fc032bdce72255d79e3f5f16ca50504151bda49cb3a148272ba32e0f410b4bdb70959b8f3f4 ]
        Actual hash: [ 20823cd0dce0d422c35b0220227e957992571406cc8e486ea2d5f23ac542bc6ec3d2310b6de6d93f4a06c57bfdc4c0aade829204c0801b6460f00c47bad544b5 ]

  Please delete the file and retry if this file should be downloaded again.

I searched a solution by change the expected hash with the actual hash, editing "vcpkg-master\ports\vtk\portfile". after this, the building process could start. but a new error appeared:
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: ninja -v
    Working Directory: D:/vcpkg-master/buildtrees/vtk/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\vcpkg-master\buildtrees\vtk\config-x64-windows-out.log

the config-x64-windows-out.log is attached here.

[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/6369414/config-x64-windows-out.log)

**Comment by Neumann-A** [comment]
VTK has been updated a long time ago to 9.0 so you are not on the current master.

**Comment by ZhouJJJKKK** [comment]
> VTK has been updated a long time ago to 9.0 so you are not on the current master.

Thank your for the remind!
