### ISSUE TITLE
In install package in vcpkg had error

### ISSUE THREAD

**Issue by WangHHY19931001** [microsoft/vcpkg#17485]
**Describe the bug**

**Environment**
- OS: windows 10 20H2
- Compiler: revision

**To Reproduce**
1. .\vcpkg install cuda cudnn opencl
2. See error
Repro code when

**Expected behavior**

**Failure logs** 
.\vcpkg install cuda cudnn opencl
Computing installation plan...
The following packages will be built and installed:
    cuda[core]:x86-windows -> 10.1#7
    cudnn[core]:x86-windows -> 7.6.5#1
    opencl[core]:x86-windows -> 2.2#7
Detecting compiler hash for triplet x86-windows...
Error: while detecting compiler information:
The log content at D:\vcpkg\buildtrees\detect_compiler\stdout-x86-windows.log is:
CMake Error at D:/vcpkg/scripts/ports.cmake:51 (message):
  Cannot find port:

    Directory does not exist: D;/vcpkg/scripts/detect_compiler

Error: vcpkg was unable to detect the active compiler's information. See above for the CMake failure output.

**Additional context**

**Comment by JackBoosY** [comment]
Can you please run command `.\vcpkg install cuda cudnn opencl --debug` then provide the output?
And also, please make sure you have enough permission.

Thanks.

**Comment by autoantwort** [comment]
Maybe the same as #16448

**Comment by JackBoosY** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!

**Comment by WangHHY19931001** [comment]
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] BuiltinRegistry initialized with: ""
[DEBUG] Using vcpkg-root: D:\vcpkg
[DEBUG] Using installed-root: D:\vcpkg\installed
[DEBUG] BuiltinRegistry initialized with: ""
[DEBUG] Using buildtrees-root: D:\vcpkg\buildtrees
[DEBUG] Using downloads-root: D:\vcpkg\downloads
[DEBUG] Using packages-root: D:\vcpkg\packages
[DEBUG] Using scripts-root: D:\vcpkg\scripts
[DEBUG] Using ports-root: D:\vcpkg\ports
[DEBUG] Using versions-root: D:\vcpkg\versions
[DEBUG] Default binary cache path is: C:\Users\wangh\AppData\Local\vcpkg\archives
Computing installation plan...
[DEBUG] Found path: C:\Program Files\CMake\bin\cmake.exe
[DEBUG] CreateProcessW("D:\vcpkg\downloads\tools\cmake-3.20.2-windows\cmake-3.20.2-windows-i386\bin\cmake.exe" --version)
[DEBUG] cmd_execute_and_stream_data() returned 0 after   308802 us
[DEBUG] CreateProcessW("D:\vcpkg\downloads\tools\cmake-3.20.2-windows\cmake-3.20.2-windows-i386\bin\cmake.exe" -DVCPKG_ROOT_DIR=D:/vcpkg -DPACKAGES_DIR=D:/vcpkg/packages -DBUILDTREES_DIR=D:/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=D:/vcpkg/installed -DDOWNLOADS=D:/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "D:\vcpkg\buildtrees\0.vcpkg_tags.cmake")
[DEBUG] cmd_execute_and_stream_data() returned 0 after    58411 us
The following packages will be built and installed:
    cuda[core]:x86-windows -> 10.1#7
    cudnn[core]:x86-windows -> 7.6.5#4
    opencl[core]:x86-windows -> 2.2#7
[DEBUG] CreateProcessW("C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -all -prerelease -legacy -products * -format xml)
[DEBUG] cmd_execute_and_stream_data() returned 0 after    40511 us
Detecting compiler hash for triplet x86-windows...
[DEBUG] Found path: C:\Program Files\Git\cmd\git.exe
[DEBUG] CreateProcessW("D:\vcpkg\downloads\tools\git-2.32.0.2-windows\mingw32\bin\git.exe" --version)
[DEBUG] cmd_execute_and_stream_data() returned 0 after   320766 us
[DEBUG] Found path: C:\Program Files\PowerShell\7\pwsh.exe
[DEBUG] CreateProcessW("C:\Program Files\PowerShell\7\pwsh.exe" --version)
[DEBUG] cmd_execute_and_stream_data() returned 0 after   616029 us
[DEBUG] CreateProcessW(cmd /c "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" -vcvars_ver=14.2 amd64_x86   2>&1 <NUL  & echo cdARN4xjKueKScMy9C6H & set)
[DEBUG] cmd_execute_and_stream_data() returned 0 after  1632543 us
[DEBUG] command line: cmd /c "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" -vcvars_ver=14.2 amd64_x86   2>&1 <NUL  & echo cdARN4xjKueKScMy9C6H & set
[DEBUG] **********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.10.4
** Copyright (c) 2021 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64_x86'
cdARN4xjKueKScMy9C6H
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\wangh\AppData\Roaming
CommandPromptType=Cross
CommonProgramFiles=C:\Program Files (x86)\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=LAPTOP-5H67EC71
ComSpec=C:\WINDOWS\system32\cmd.exe
DevEnvDir=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\
ExtensionSdkDir=C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10\ExtensionSDKs
Framework40Version=v4.0
FrameworkDir=C:\Windows\Microsoft.NET\Framework64\
FrameworkDir32=C:\Windows\Microsoft.NET\Framework\
FrameworkDir64=C:\Windows\Microsoft.NET\Framework64\
FrameworkVersion=v4.0.30319
FrameworkVersion32=v4.0.30319
FrameworkVersion64=v4.0.30319
FSHARPINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\FSharp\Tools
HOMEDRIVE=C:
HOMEPATH=\Users\wangh
HTMLHelpDir=C:\Program Files (x86)\HTML Help Workshop
IFCPATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\ifc\x86
INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\ATLMFC\include;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\include;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt
LIB=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\ATLMFC\lib\x86;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\lib\x86;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x86;C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x86;C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x86
LIBPATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\ATLMFC\lib\x86;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\lib\x86;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\lib\x86\store\references;C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.19041.0;C:\Program Files (x86)\Windows Kits\10\References\10.0.19041.0;C:\Windows\Microsoft.NET\Framework64\v4.0.30319
LOCALAPPDATA=C:\Users\wangh\AppData\Local
LOGONSERVER=\\LAPTOP-5H67EC71
NETFXSDKDir=C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\
NUMBER_OF_PROCESSORS=8
OS=Windows_NT
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW
Platform=x86
PreferredToolArchitecture=x64
PROCESSOR_ARCHITECTURE=x86
PROCESSOR_ARCHITEW6432=AMD64
PROCESSOR_IDENTIFIER=AMD64 Family 23 Model 24 Stepping 1, AuthenticAMD
PROCESSOR_LEVEL=23
PROCESSOR_REVISION=1801
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files (x86)
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=$P$G
PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
PUBLIC=C:\Users\Public
SystemDrive=C:
SystemRoot=C:\WINDOWS
TEMP=C:\Users\wangh\AppData\Local\Temp
TMP=C:\Users\wangh\AppData\Local\Temp
UCRTVersion=10.0.19041.0
UniversalCRTSdkDir=C:\Program Files (x86)\Windows Kits\10\
USERDOMAIN=LAPTOP-5H67EC71
USERDOMAIN_ROAMINGPROFILE=LAPTOP-5H67EC71
USERNAME=wangh
USERPROFILE=C:\Users\wangh
VCIDEInstallDir=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\VC\
VCINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\
VCToolsInstallDir=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\
VCToolsRedistDir=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Redist\MSVC\14.29.30036\
VCToolsVersion=14.29.30037
VisualStudioVersion=16.0
VS160COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\
VSCMD_ARG_app_plat=Desktop
VSCMD_ARG_HOST_ARCH=x64
VSCMD_ARG_TGT_ARCH=x86
VSCMD_ARG_VCVARS_VER=14.2
VSCMD_VER=16.10.4
VSINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\
VSSDK150INSTALL=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VSSDK
VSSDKINSTALL=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VSSDK
windir=C:\WINDOWS
CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4
NVCUDASAMPLES_ROOT=C:\ProgramData\NVIDIA Corporation\CUDA Samples\v11.4
NVTOOLSEXT_PATH=C:\Program Files\NVIDIA Corporation\NvToolsExt\
VULKAN_SDK=C:\VulkanSDK\1.2.182.0
Path=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\\Extensions\Microsoft\IntelliCode\CLI;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\bin\HostX64\x86;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\bin\Roslyn;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Team Tools\Performance Tools;D:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\;C:\Program Files (x86)\HTML Help Workshop;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\FSharp\Tools;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\devinit;C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\\MSBuild\Current\Bin;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\;C:\Program Files\PowerShell\7;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\system32\Wbem;C:\WINDOWS\system32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\Llvm\x64\bin;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\VC\Linux\bin\ConnectionManagerExe
VSLANG=1033
VSCMD_SKIP_SENDTELEMETRY=1
VCPKG_COMMAND=D:/vcpkg/vcpkg.exe
WindowsLibPath=C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.19041.0;C:\Program Files (x86)\Windows Kits\10\References\10.0.19041.0
WindowsSdkBinPath=C:\Program Files (x86)\Windows Kits\10\bin\
WindowsSdkDir=C:\Program Files (x86)\Windows Kits\10\
WindowsSDKLibVersion=10.0.19041.0\
WindowsSdkVerBinPath=C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\
WindowsSDKVersion=10.0.19041.0\
WindowsSDK_ExecutablePath_x64=C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\
WindowsSDK_ExecutablePath_x86=C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\
X_VCPKG_RECURSIVE_DATA={}

__devinit_path=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\devinit\devinit.exe
__DOTNET_ADD_32BIT=1
__DOTNET_ADD_64BIT=1
__DOTNET_PREFERRED_BITNESS=64
__VSCMD_PREINIT_PATH=C:\Program Files\PowerShell\7;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\system32\Wbem;C:\WINDOWS\system32\WindowsPowerShell\v1.0\
__VSCMD_script_err_count=0

[DEBUG] CreateProcessW("D:\vcpkg\downloads\tools\cmake-3.20.2-windows\cmake-3.20.2-windows-i386\bin\cmake.exe" -DCURRENT_PORT_DIR=D:/vcpkg/scripts/detect_compiler -DCURRENT_BUILDTREES_DIR=D:/vcpkg/buildtrees/detect_compiler -DCURRENT_PACKAGES_DIR=D:/vcpkg/packages/detect_compiler_x86-windows -D_HOST_TRIPLET=x86-windows -DCMD=BUILD -DDOWNLOADS=D:/vcpkg/downloads -DTARGET_TRIPLET=x86-windows "-DTARGET_TRIPLET_FILE=D:\vcpkg\triplets\x86-windows.cmake" -DVCPKG_BASE_VERSION=2021-08-03 -DVCPKG_CONCURRENCY=9 -DVCPKG_PLATFORM_TOOLSET=v142 -DGIT=D:/vcpkg/downloads/tools/git-2.32.0.2-windows/mingw32/bin/git.exe -DVCPKG_ROOT_DIR=D:/vcpkg -DPACKAGES_DIR=D:/vcpkg/packages -DBUILDTREES_DIR=D:/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=D:/vcpkg/installed -DDOWNLOADS=D:/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "D:\vcpkg\scripts\ports.cmake")
[DEBUG] -- Found external ninja('1.10.2').
[DEBUG] -- Configuring x86-windows
[DEBUG] [1/1] cmd /c "cd .. && "D:/vcpkg/downloads/tools/cmake-3.20.2-windows/cmake-3.20.2-windows-i386/bin/cmake.exe" "D:/vcpkg/scripts/detect_compiler" "-DCMAKE_MAKE_PROGRAM=C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=D:/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x86-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v142" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=D:/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_LINKER_FLAGS_RELEASE=" "-DVCPKG_LINKER_FLAGS_DEBUG=" "-DVCPKG_TARGET_ARCHITECTURE=x86" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=D:/vcpkg" "-D_VCPKG_INSTALLED_DIR=D:/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=D:/vcpkg/packages/detect_compiler_x86-windows""
[DEBUG] -- The C compiler identification is MSVC 19.29.30040.0
[DEBUG] -- The CXX compiler identification is MSVC 19.29.30040.0
[DEBUG] #COMPILER_HASH#c31a7b2e66159473cd6682d159efdc0962c7671f
[DEBUG] #COMPILER_C_HASH#96b71d161902eecc839d96acd60d13487768e4db
[DEBUG] #COMPILER_C_VERSION#19.29.30040.0
[DEBUG] #COMPILER_C_ID#MSVC
[DEBUG] #COMPILER_CXX_HASH#96b71d161902eecc839d96acd60d13487768e4db
[DEBUG] #COMPILER_CXX_VERSION#19.29.30040.0
[DEBUG] #COMPILER_CXX_ID#MSVC
[DEBUG] -- Configuring done
[DEBUG] -- Generating done
[DEBUG] CMake Warning:
[DEBUG]   Manually-specified variables were not used by the project:
[DEBUG]
[DEBUG]     BUILD_SHARED_LIBS
[DEBUG]     CMAKE_INSTALL_BINDIR
[DEBUG]     CMAKE_INSTALL_LIBDIR
[DEBUG]     VCPKG_TARGET_ARCHITECTURE
[DEBUG]     _VCPKG_ROOT_DIR
[DEBUG]
[DEBUG]
[DEBUG] -- Build files have been written to: D:/vcpkg/buildtrees/detect_compiler/x86-windows-rel
[DEBUG]
[DEBUG] cmd_execute_and_stream_data() returned 0 after  3970553 us
[DEBUG]
[DEBUG] Detected compiler hash for triplet x86-windows: c31a7b2e66159473cd6682d159efdc0962c7671f
[DEBUG] <abientries for cuda:x86-windows>
[DEBUG]   CONTROL|9d9e827a593f4624b096f16cdd3865c2f9a86ec404c7b3ae046a3cee52b912f7
[DEBUG]   cmake|3.20.2
[DEBUG]   features|core
[DEBUG]   portfile.cmake|02c005459ef82c306b09c7abe30e81a60bbca8d9a146cf87a01526caccbbd255
[DEBUG]   ports.cmake|c0512f9b1ab58726dcf19e52a9c6e3bd4198eae07083b506dec408dfc53b704a
[DEBUG]   post_build_checks|2
[DEBUG]   powershell|7.1.3
[DEBUG]   triplet|x86-windows
[DEBUG]   triplet_abi|3e71dd1d4afa622894ae367adbbb1ecbd42c57c51428a86b675fa1c8cad3a581-b569c9954a47274946415ff01b1a344c8549f3fc19cb931d50bc09d1e5630c1d-c31a7b2e66159473cd6682d159efdc0962c7671f
[DEBUG]   vcpkg_find_cuda.cmake|801f4fa306fed4aaf7a4abddea1abbae0afb1682e4e624e9facac6b8d2f2839f
[DEBUG] </abientries>
[DEBUG] <abientries for cudnn:x86-windows>
[DEBUG]   FindCUDNN.cmake|99bbe8a5ace4aca0784081e87bf6fa32788cb48a157f219223f363d1fa0129a2
[DEBUG]   cmake|3.20.2
[DEBUG]   cuda|5c115921ce6847461c3ab32079cb758629a9806bf729eecfafdec070e10ab86b
[DEBUG]   features|core
[DEBUG]   portfile.cmake|09697182c1ac60ed8cb4050da3f8fceb6d69133625d6a3b82af838ce6e0d5c8a
[DEBUG]   ports.cmake|c0512f9b1ab58726dcf19e52a9c6e3bd4198eae07083b506dec408dfc53b704a
[DEBUG]   post_build_checks|2
[DEBUG]   powershell|7.1.3
[DEBUG]   triplet|x86-windows
[DEBUG]   triplet_abi|3e71dd1d4afa622894ae367adbbb1ecbd42c57c51428a86b675fa1c8cad3a581-b569c9954a47274946415ff01b1a344c8549f3fc19cb931d50bc09d1e5630c1d-c31a7b2e66159473cd6682d159efdc0962c7671f
[DEBUG]   usage|f7475870c87c504eda1b1a668fc93f2b33d74b38ffb8d319ce5a84931ce48dd3
[DEBUG]   vcpkg-cmake-wrapper.cmake|55cdd870b374833b3614406e7d4c022838c92855818599286754a80e97bc13d7
[DEBUG]   vcpkg.json|b8bb0ad8098548a7d6e1bf523872d5d80e747b3d13e153edcc1e353253f82213
[DEBUG]   vcpkg_check_linkage|e5ad99ba10a67fae84fbf9b077a1d136a0a751343fbc8ec18c7bd83cab7eba6b
[DEBUG] </abientries>
[DEBUG] <abientries for opencl:x86-windows>
[DEBUG]   0001-include-unistd-for-gete-ug-id.patch|05e831120c4003a911052192baf93aa73132a476dfd8303d3e5dd8c80f2f104e
[DEBUG]   CONTROL|ffabc735960c7b255324e434872f91dbdc8be20ac74223351e5f30fb21cf91f1
[DEBUG]   cmake|3.20.2
[DEBUG]   features|core
[DEBUG]   portfile.cmake|3bb6c57ab7f9a3841aa10f03db4745a285381444a301431654974d44b52b4caf
[DEBUG]   ports.cmake|c0512f9b1ab58726dcf19e52a9c6e3bd4198eae07083b506dec408dfc53b704a
[DEBUG]   post_build_checks|2
[DEBUG]   powershell|7.1.3
[DEBUG]   triplet|x86-windows
[DEBUG]   triplet_abi|3e71dd1d4afa622894ae367adbbb1ecbd42c57c51428a86b675fa1c8cad3a581-b569c9954a47274946415ff01b1a344c8549f3fc19cb931d50bc09d1e5630c1d-c31a7b2e66159473cd6682d159efdc0962c7671f
[DEBUG]   usage|d2be786ccaed1b17034bacabbd4c07d14286010d060795aeef2e542ee0320d6d
[DEBUG]   vcpkg-cmake-wrapper.cmake|03fd465f466888f4e827dad442be2df9a00a3ee4f593f072837257c8f8466eb4
[DEBUG]   vcpkg_build_cmake|0f5c3c1874719a47dbc9c86a9d1ad9d5a0abf37de32dc2507a273646750438e7
[DEBUG]   vcpkg_configure_cmake|7ef59fb404a8ff25d9fe36e8a1a081de7f6b5aa9b52628207e1a955365f30a1f
[DEBUG]   vcpkg_copy_pdbs|9ee48632c443dc39542e8159c53d4a71e081141845f190566bf725d3b8f40dae
[DEBUG]   vcpkg_execute_required_process|89bb8aa5ff2be96910b186c103fbcc20035fcd043232518314a993384208e84d
[DEBUG]   vcpkg_find_acquire_program|fa98384a1dc55674af27424ec70ddfd5d80375514abbecc4380fde4ae52fe7b1
[DEBUG]   vcpkg_from_git|5a1a6937291b670fa030244fe1b2d08cff60da4ef8997c33447260fecbffce6e
[DEBUG]   vcpkg_from_github|2f5640e66a80bd2dced292099108f6b8a5ca4f5a27efc230e622424627c8fa72
[DEBUG] </abientries>
Could not locate cached archive: C:\Users\wangh\AppData\Local\vcpkg\archives\5c\5c115921ce6847461c3ab32079cb758629a9806bf729eecfafdec070e10ab86b.zip
Could not locate cached archive: C:\Users\wangh\AppData\Local\vcpkg\archives\bb\bba4956dadcf5c427d6a4df9798b4906931db1c5be30dd26b05b07444f2f62af.zip
Could not locate cached archive: C:\Users\wangh\AppData\Local\vcpkg\archives\74\7411697d06d83d42b22e5b844ceca5dcea398b8c38c7f834033fd97a392e42c9.zip
Starting package 1/3: cuda:x86-windows
Building package cuda[core]:x86-windows...
[DEBUG] CreateProcessW("D:\vcpkg\downloads\tools\cmake-3.20.2-windows\cmake-3.20.2-windows-i386\bin\cmake.exe" -DALL_FEATURES= -DCURRENT_PORT_DIR=D:/vcpkg/ports/cuda -D_HOST_TRIPLET=x64-windows -DFEATURES=core -DPORT=cuda -DVCPKG_USE_HEAD_VERSION=0 -D_VCPKG_DOWNLOAD_TOOL=BUILT_IN -D_VCPKG_EDITABLE=0 -D_VCPKG_NO_DOWNLOADS=0 -DCMD=BUILD -DDOWNLOADS=D:/vcpkg/downloads -DTARGET_TRIPLET=x86-windows "-DTARGET_TRIPLET_FILE=D:\vcpkg\triplets\x86-windows.cmake" -DVCPKG_BASE_VERSION=2021-08-03 -DVCPKG_CONCURRENCY=9 -DVCPKG_PLATFORM_TOOLSET=v142 -DGIT=D:/vcpkg/downloads/tools/git-2.32.0.2-windows/mingw32/bin/git.exe -DVCPKG_ROOT_DIR=D:/vcpkg -DPACKAGES_DIR=D:/vcpkg/packages -DBUILDTREES_DIR=D:/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=D:/vcpkg/installed -DDOWNLOADS=D:/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "D:\vcpkg\scripts\ports.cmake")
-- Found CUDA V11.4.48
[DEBUG] cmd_execute_and_stream_data() returned 0 after   132448 us
-- Performing post-build validation
-- Performing post-build validation done
A suitable version of 7zip was not found (required v19.0.0). Downloading portable 7zip v19.0.0...
Downloading 7zip...
  https://www.7-zip.org/a/7z1900-x64.msi -> D:\vcpkg\downloads\7z1900-x64.msi
[DEBUG] Downloading https://www.7-zip.org/a/7z1900-x64.msi
Extracting 7zip...
[DEBUG] CreateProcessW(cmd /c msiexec /a "D:\vcpkg\downloads\7z1900-x64.msi" /qn TARGETDIR="D:\vcpkg\downloads\tools\7zip-19.00-windows.partial.14744")
[DEBUG] cmd_execute_and_stream_data() returned 0 after   618822 us
[DEBUG] CreateProcessW("D:\vcpkg\downloads\tools\7zip-19.00-windows\Files\7-Zip\7z.exe" a "D:\vcpkg\buildtrees\cuda\x86-windows.zip" "D:\vcpkg\packages\cuda_x86-windows\*")
[DEBUG] cmd_execute_and_stream_data() returned 0 after    65307 us
Stored binary cache: C:\Users\wangh\AppData\Local\vcpkg\archives\5c\5c115921ce6847461c3ab32079cb758629a9806bf729eecfafdec070e10ab86b.zip
Building package cuda[core]:x86-windows... done
Installing package cuda[core]:x86-windows...
Installing package cuda[core]:x86-windows... done
Elapsed time for package cuda:x86-windows: 13.4 s
Starting package 2/3: cudnn:x86-windows
Building package cudnn[core]:x86-windows...
[DEBUG] CreateProcessW("D:\vcpkg\downloads\tools\cmake-3.20.2-windows\cmake-3.20.2-windows-i386\bin\cmake.exe" -DALL_FEATURES= -DCURRENT_PORT_DIR=D:/vcpkg/ports/cudnn -D_HOST_TRIPLET=x64-windows -DFEATURES=core -DPORT=cudnn -DVCPKG_USE_HEAD_VERSION=0 -D_VCPKG_DOWNLOAD_TOOL=BUILT_IN -D_VCPKG_EDITABLE=0 -D_VCPKG_NO_DOWNLOADS=0 -DCMD=BUILD -DDOWNLOADS=D:/vcpkg/downloads -DTARGET_TRIPLET=x86-windows "-DTARGET_TRIPLET_FILE=D:\vcpkg\triplets\x86-windows.cmake" -DVCPKG_BASE_VERSION=2021-08-03 -DVCPKG_CONCURRENCY=9 -DVCPKG_PLATFORM_TOOLSET=v142 -DGIT=D:/vcpkg/downloads/tools/git-2.32.0.2-windows/mingw32/bin/git.exe -DVCPKG_ROOT_DIR=D:/vcpkg -DPACKAGES_DIR=D:/vcpkg/packages -DBUILDTREES_DIR=D:/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=D:/vcpkg/installed -DDOWNLOADS=D:/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "D:\vcpkg\scripts\ports.cmake")
CMake Error at ports/cudnn/portfile.cmake:6 (message):
  This port is only for x64 architectures
Call Stack (most recent call first):
  scripts/ports.cmake:141 (include)


[DEBUG] cmd_execute_and_stream_data() returned 1 after    92563 us
Error: Building package cudnn:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: cudnn:x86-windows
  Vcpkg version: 2021-08-03-1a6d67b8150e94b7f473c6ab1c0cfdd794316a64

Additionally, attach any relevant sections from the log files above.
[DEBUG] C:\a\1\s\src\vcpkg\install.cpp(494)
[DEBUG] Exiting after 20999488 us (20988019 us)

**Comment by JackBoosY** [comment]
```
CMake Error at ports/cudnn/portfile.cmake:6 (message):
  This port is only for x64 architectures
```

**Comment by JackBoosY** [comment]
Since the original issue has been resolved, close this now.
