### ISSUE TITLE
Angle copies libGLES2, but not libEGL into the target folder.

### ISSUE THREAD

**Issue by arkiruthis** [microsoft/vcpkg#17486]
I am using a CMake project, with vcpkg as a submodule and included as a toolchain at the top of CMakeLists.txt as recommended. This is working fine.

I have installed the "angle:x64-windows" package which I am using alongside libSDL2.

When my targets are built (either Debug or Release) all the relevant DLLs are copied to the target output folder... except for **libEGL.dll** which I am having to copy over manually from vcpkg's own internal bin folders.

Is there an extra setting I'm missing to have this done?

This is the line recommended by the install to use in CMakeLists.txt
`target_link_libraries(${PROJECT_NAME} PRIVATE unofficial::angle::libEGL unofficial::angle::libANGLE unofficial::angle::libGLESv2 unofficial::angle::angle_common)`

Feels like it should be including the libEGL.dll?

**Comment by NancyLi1013** [comment]
Hi @arkiruthis 

Thanks for posting this issue. The problem is that you need to copy `libEGL.dll` manually to your target output folder, right?

If possible, could you please help provide your project sample here?

Thanks.

**Comment by arkiruthis** [comment]
Hi @NancyLi1013 , I believe I know what has happend, and whilst it's unusual I think this issue can be closed.

In my project, I use SDL2 to create a surface for ANGLE, **but I never explicitly call EGL functions anywhere**.

e.g., 
```
#if defined(_WIN32)
        SDL_SetHint(SDL_HINT_OPENGL_ES_DRIVER, "1"); // Force SDL to use ANGLE for it's OpenGLES2 implementation
#endif

        SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_ES);
        SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 3);
        SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 0);
```

If I add the following (and basically just ignore it's return value)
```
        eglGetError(); // totally unused, but explicitly calling EGL in my local code
```

The `libEGL.dll` is properly copied into the Project Output folder correctly.

So, to summarize, I think VCPKG is working as intended. :)

**Comment by NancyLi1013** [comment]
Thanks for looking into this. I'm also glad to hear the good news. Please let me know if you have other concerns about this issue.
