### ISSUE TITLE
[New Port Request] <Project Chrono>

### ISSUE THREAD

**Issue by georgelyu** [microsoft/vcpkg#17497]
Library name: Project Chrono

Library description: Chrono is a physics-based modelling and simulation infrastructure based on a platform-independent open-source design implemented in C++. A Project Chrono library can be embedded in a software project to simulate, for instance, wheeled and tracked vehicles operating on deformable terrains, robots, mechatronic systems, compliant mechanisms, and fluid solid interaction phenomena. Systems can be made of rigid and flexible/compliant parts with constraints, motors and contacts; parts can have three-dimensional shapes for collision detection.

Source repository URL: https://github.com/projectchrono/chrono

Project homepage (if different from the source repository): https://projectchrono.org/

Anything else that is useful to know when adding (such as optional features the library may have that should be included): Project Chrono does have a lot of modules, so more modules supported the better.

Thanks!!

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
