### ISSUE TITLE
[New Port Request] LAPACKE

### ISSUE THREAD

**Issue by Wongboo** [microsoft/vcpkg#17498]
Library name:
LAPACKE
Library description:
LAPACKE
Source repository URL:
?
Project homepage (if different from the source repository):
https://www.netlib.org/lapack/#_lapack_for_windows
Anything else that is useful to know when adding (such as optional features the library may have that should be included):
The existing LAPACK library doesn't work with Eigen when using LAPACKE library, because current build does not contain LAPACKE, more can be seen on [here](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwi8_vqCuZnwAhVNPnAKHeR6B_YQFjACegQIEhAD&url=https%3A%2F%2Fgithub.com%2FMicrosoft%2Fvcpkg%2Fblob%2Fmaster%2Fports%2Flapack-reference%2Fportfile.cmake&usg=AOvVaw1Kv5_fQNpW50PfY5qDbxEf)

**Comment by JackBoosY** [comment]
We already have `clapack`  `lapack` and `lapack-reference`, is it one of them?

**Comment by Neumann-A** [comment]
@JackBoosY It could be a feature of lapack-reference but i am uncertain if it can be its own port

**Comment by Wongboo** [comment]
@JackBoosY No help, actually when installing LAPACK, lapack-reference will be automatically installed as dependence, and CLAPACK differs from LAPACKE as well. you can easily try to compile an Eigen program with EIGEN_USE_LAPACKE_STRICT, ends with failure.

**Comment by Wongboo** [comment]
@Neumann-A  [lapack-reference](https://github.com/microsoft/vcpkg/blob/84e5852cfaa8e7875027e79a29a5534bb5d4a475/ports/lapack-reference/portfile.cmake#L4)'s portfile suggests that LAPACKE may should be another port

**Comment by JackBoosY** [comment]
Obviously, it is consistent with the source code of lapack-reference.

**Comment by Neumann-A** [comment]
@Wongboo check the git blame ;) I cannot remember if it can be build without lapack-reference or to be more precise without building lapack at all.

**Comment by Wongboo** [comment]
according to [lapack's CMakeLists](https://github.com/Reference-LAPACK/lapack/blob/7b16a30525d02cf098c13b30865a710d3699692c/CMakeLists.txt#L348), it may be should along with lapack-reference and may be turn on the option "LAPACKE" will solve everything

**Comment by Wongboo** [comment]
But I don't think think it should be a complete new port! Something looks like ```lapack-reference[lapacke]``` just like ```lapack-reference[cblas]``` might be better, since ```cblas``` and ```lapacke``` both represents a build option in lapack-reference!

**Comment by Neumann-A** [comment]
> But I don't think think it should be a complete new port! 

I think it could be with: `-DUSE_OPTIMIZED_LAPACK=ON`. Then it does not build the lapack part.

**Comment by Wongboo** [comment]
@Neumann-A But we should carefully use ```USE_OPTIMIZED_LAPACK```, if user already build lapack of the same version or they choose to use ```clapcke```, then we use it, otherwise don't! It works just like ```USE_OPTIMIZED_BLAS``` but a little bit more confusing and complicated.

**Comment by JonLiu1993** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
