### ISSUE TITLE
How do I create a pull request here?

### ISSUE THREAD

**Issue by Endleon201** [microsoft/vcpkg#17503]
I looked around the project for how to create a pull request and even when I do find the button it's grayed out for me, please tell me how I can do this.

**Comment by JackBoosY** [comment]
Please fork vcpkg, (create a branch), make changes them commit to your branch. Then refresh https://github.com/microsoft/vcpkg/pulls.

**Comment by mathisloge** [comment]
https://guides.github.com/activities/forking/

https://jarv.is/notes/how-to-pull-request-fork-github/



Some short guides :)
