### ISSUE TITLE
Where does CMake download dependencies for manifest mode?

### ISSUE THREAD

**Issue by BewareMyPower** [microsoft/vcpkg#17515]
From the https://github.com/microsoft/vcpkg/blob/master/docs/users/manifests.md#cmake-integration I see 
> Vcpkg will be automatically bootstrapped if missing and invoked to install your dependencies into your local build directory (${CMAKE_BINARY_DIR}/vcpkg_installed).

However, when I run

```bash
cmake -B _builds -S . -DCMAKE_TOOLCHAIN_FILE="$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake"
```

vcpkg tried to install dependencies to `$VCPKG_ROOT/buildtrees`. I tried to remove `CMAKE_TOOLCHAIN_FILE` option, but it wouldn't download dependencies after that.

When I run it in CMD

```bash
vcpkg install --feature-flags=manifests
```

The dependencies were installed to `./vcpkg_installed`. 

Platform: Windows 10

**Comment by PhoebeHui** [comment]
@BewareMyPower, this is correct, with manifest mode, all dependencies would be installed to ./vcpkg_installed. and in classic mode. it will installed to $VCPKG_ROOT/installed folder.

**Comment by PhoebeHui** [comment]
@BewareMyPower, does this  still be a question for you?

**Comment by BewareMyPower** [comment]
@PhoebeHui Sorry for the late reply. I just misunderstood the `CMAKE_BINARY_DIR`  before.
