### ISSUE TITLE
How do I have a suitable Visual Studio instance?

### ISSUE THREAD

**Issue by Huarkiou** [microsoft/vcpkg#17514]
### Problem : 
When I use  command "vcpkg install <name>" to install packages, it comes like
```
Computing installation plan...
The following packages will be built and installed:
***(many lines)
Additional packages (*) will be modified to complete this operation.
No suitable Visual Studio instances were found
```
There are issues about this problem and the solution is to install VS2019's English language pack.But I have already installed this pack.Even if I reinstall VS2019, it still complains.I don't know how to solve this problem.

### Dev Environment
```
Vcpkg package management program version 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e
```
```
Microsoft Visual Studio 2019 Version 16.9.4.
Copyright (C) Microsoft Corp. All rights reserved.
```
```
OS : Windows 10 Home
Version : 20H2
OS Build : 19042.928
```

**Comment by JackBoosY** [comment]
Can you please run command `vcpkg install PORT_NAME --debug`  then commit the output?

Thanks.

**Comment by Huarkiou** [comment]
```
PS C:\Users\huarkiou> vcpkg install intel-mkl --debug
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] BuiltinRegistry initialized with: ""
[DEBUG] Using vcpkg-root: D:\mysdk\vcpkg
[DEBUG] Using installed-root: D:\mysdk\vcpkg\installed
[DEBUG] BuiltinRegistry initialized with: ""
[DEBUG] Using buildtrees-root: D:\mysdk\vcpkg\buildtrees
[DEBUG] Using downloads-root: D:\mysdk\vcpkg\downloads
[DEBUG] Using packages-root: D:\mysdk\vcpkg\packages
[DEBUG] Using scripts-root: D:\mysdk\vcpkg\scripts
[DEBUG] Using ports-root: D:\mysdk\vcpkg\ports
[DEBUG] Using versions-root: D:\mysdk\vcpkg\versions
[DEBUG] Default binary cache path is: C:\Users\huarkiou\AppData\Local\vcpkg\archives
Computing installation plan...
[DEBUG] Found path: D:\mysdk\CMake\bin\cmake.exe
[DEBUG] CreateProcessW("D:\mysdk\vcpkg\downloads\tools\cmake-3.19.2-windows\cmake-3.19.2-win32-x86\bin\cmake.exe" --version)
[DEBUG] cmd_execute_and_stream_data() returned 0 after    88092 us
[DEBUG] CreateProcessW("D:\mysdk\vcpkg\downloads\tools\cmake-3.19.2-windows\cmake-3.19.2-win32-x86\bin\cmake.exe" -DVCPKG_ROOT_DIR=D:/mysdk/vcpkg -DPACKAGES_DIR=D:/mysdk/vcpkg/packages -DBUILDTREES_DIR=D:/mysdk/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=D:/mysdk/vcpkg/installed -DDOWNLOADS=D:/mysdk/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "D:\mysdk\vcpkg\buildtrees\0.vcpkg_tags.cmake")
[DEBUG] cmd_execute_and_stream_data() returned 0 after    74249 us
The following packages will be built and installed:
    intel-mkl[core]:x64-windows -> 2020.0.0
[DEBUG] Could not locate a complete Visual Studio instance
[DEBUG] The following paths were examined:
No suitable Visual Studio instances were found
[DEBUG] C:\A\1\70\s\src\vcpkg\vcpkgpaths.cpp(1033)
[DEBUG] Exiting after 513579 us (500202 us)
```

**Comment by Huarkiou** [comment]
Ok.The reason is that my visual studio 2019 is not installed in %ProgramFiles(x86)%.

**Comment by JackBoosY** [comment]
We'll have a discuss with it.

**Comment by JackBoosY** [comment]
cc @strega-nil, should we handle this situation?

**Comment by raisinbl** [comment]
Hello I have the same issue like you, I've installed VScode on my Windows 10 before but I don't know why the problem is about VS. Can anybody help me?
`C:\Users\dell\vcpkg>vcpkg install libsodium
Computing installation plan...
The following packages will be built and installed:
    libsodium[core]:x86-windows -> 1.0.18#5
  * vcpkg-cmake[core]:x64-windows -> 2021-09-13
  * vcpkg-cmake-config[core]:x64-windows -> 2021-09-27
Additional packages (*) will be modified to complete this operation.
No suitable Visual Studio instances were found`

**Comment by strega-nil-ms** [comment]
We need vswhere.exe in order to find visual studio installations; we could in theory download vswhere, however I don't think it's something we want to do right now... @ras0219 any opinions?

**Comment by strega-nil-ms** [comment]
@raisinbl could you run `vcpkg install libsodium --debug`?

**Comment by dg0yt** [comment]
> Hello I have the same issue like you, I've installed VScode on my Windows 10 before but I don't know why the problem is about VS.

@raisinbl Do you really mean Visual Studio Code? That's a great editor, but unlike Visual studio, it doesn't come with any compilers etc.

**Comment by raisinbl** [comment]
@strega-nil-ms here's my `vcpkg install libsodium --debug`:
`
C:\Users\dell\vcpkg>vcpkg install libsodium --debug
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] BuiltinRegistry initialized with: ""
[DEBUG] Using vcpkg-root: C:\Users\dell\vcpkg
[DEBUG] Using installed-root: C:\Users\dell\vcpkg\installed
[DEBUG] BuiltinRegistry initialized with: ""
[DEBUG] Using buildtrees-root: C:\Users\dell\vcpkg\buildtrees
[DEBUG] Using downloads-root: C:\Users\dell\vcpkg\downloads
[DEBUG] Using packages-root: C:\Users\dell\vcpkg\packages
[DEBUG] Using scripts-root: C:\Users\dell\vcpkg\scripts
[DEBUG] Using ports-root: C:\Users\dell\vcpkg\ports
[DEBUG] Using versions-root: C:\Users\dell\vcpkg\versions
[DEBUG] Default binary cache path is: C:\Users\dell\AppData\Local\vcpkg\archives
Computing installation plan...
[DEBUG] CreateProcessW("C:\Users\dell\vcpkg\downloads\tools\cmake-3.21.1-windows\cmake-3.21.1-windows-i386\bin\cmake.exe" --version)
[DEBUG] cmd_execute_and_stream_data() returned 0 after    73975 us
[DEBUG] CreateProcessW("C:\Users\dell\vcpkg\downloads\tools\cmake-3.21.1-windows\cmake-3.21.1-windows-i386\bin\cmake.exe" -DVCPKG_ROOT_DIR=C:/Users/dell/vcpkg -DPACKAGES_DIR=C:/Users/dell/vcpkg/packages -DBUILDTREES_DIR=C:/Users/dell/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=C:/Users/dell/vcpkg/installed -DDOWNLOADS=C:/Users/dell/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "C:\Users\dell\vcpkg\buildtrees\0.vcpkg_tags.cmake")
[DEBUG] cmd_execute_and_stream_data() returned 0 after    41062 us
The following packages will be built and installed:
    libsodium[core]:x86-windows -> 1.0.18#5
  * vcpkg-cmake[core]:x64-windows -> 2021-09-13
  * vcpkg-cmake-config[core]:x64-windows -> 2021-09-27
Additional packages (*) will be modified to complete this operation.
[DEBUG] CreateProcessW("C:\Program Files (x86)\Microsoft Visual Studio/Installer/vswhere.exe" -all -prerelease -legacy -products * -format xml)
[DEBUG] cmd_execute_and_stream_data() returned 0 after    36387 us
[DEBUG] Could not locate a complete Visual Studio instance
[DEBUG] The following paths were examined:
[DEBUG]     C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary/Build\vcvarsall.bat
No suitable Visual Studio instances were found
[DEBUG] D:\a\_work\1\s\src\vcpkg\vcpkgpaths.cpp(1096)
[DEBUG] Exiting after 199.4 ms us (188392 us)
`

**Comment by strega-nil-ms** [comment]
Could you run
`"C:\Program Files (x86)\Microsoft Visual Studio/Installer/vswhere.exe" -all -prerelease -legacy -products * -format xml`
in a cmd prompt?

**Comment by JackBoosY** [comment]
Ping @strega-nil-ms for response.

**Comment by strega-nil-ms** [comment]
I'm so sorry, I missed this because I went out of office for a month; @Huarkiou if you're still around, can you run `"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Auxiliary\Build\vcvarsall.bat"`, and then run `cl`?

**Comment by JonLiu1993** [comment]
@Huarkiou ,Does this problem still exist? could you try @strega-nil-ms 's suggestion？

**Comment by JackBoosY** [comment]
Please check the Visual Studio components in https://github.com/microsoft/vcpkg-tool/pull/314, or repair your Visual Studio using Visual Studio Installer.

**Comment by JackBoosY** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.
