### ISSUE TITLE
[New Port Request] oatpp-openssl

### ISSUE THREAD

**Issue by xanderdunn** [microsoft/vcpkg#17513]
Library name: [oatpp-openssl](https://github.com/oatpp/oatpp-openssl)

Library description: Currently vcpkg contains ports for oatpp and oatpp-libressl. oatpp-openssl is the openssl version of oatpp-libressl. Most systems have openssl rather than LibreSSL installed, so this package is more convenient to install and use. oatpp-openssl uses openssl to authenticate HTTP requests.

Source repository URL: https://github.com/oatpp/oatpp-openssl

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
