### ISSUE TITLE
Issue of VTK8.2 hdf5 install 

### ISSUE THREAD

**Issue by Erixar** [microsoft/vcpkg#17529]
I'm trying to install vtk 8.2 via vcpkg [by](https://github.com/microsoft/vcpkg/issues/14040)  ,and got some problem about hdf5 compiling

`PS F:\dev\vcpkg-master\vcpkg-master> ./vcpkg install vtk
Computing installation plan...
The following packages will be built and installed:
  * hdf5[core,szip,zlib]:x86-windows
  * jsoncpp[core]:x86-windows
  * libharu[core,notiffsymbols]:x86-windows
  * libiconv[core]:x86-windows
  * libjpeg-turbo[core]:x86-windows
  * libxml2[core]:x86-windows
  * lz4[core]:x86-windows
  * netcdf-c[core]:x86-windows
  * proj4[core,database]:x86-windows
  * sqlite3[core,tool]:x86-windows
  * tiff[core]:x86-windows
    vtk[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/12: hdf5:x86-windows
Building package hdf5[core,szip,zlib]:x86-windows...
-- Using cached F:/dev/vcpkg-master/vcpkg-master/downloads/CMake-hdf5-1.10.5.tar.gz
-- Using source at F:/dev/vcpkg-master/vcpkg-master/buildtrees/hdf5/src/hdf5-69d2d96f64
-- Configuring x86-windows-dbg
-- Configuring x86-windows-rel
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: F:/dev/vcpkg-master/vcpkg-master/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cma
ke.exe --build . --config Debug --target install -- -v
    Working Directory: F:/dev/vcpkg-master/vcpkg-master/buildtrees/hdf5/x86-windows-dbg
    See logs for more information:
      F:\dev\vcpkg-master\vcpkg-master\buildtrees\hdf5\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/hdf5/portfile.cmake:62 (vcpkg_install_cmake)
  scripts/ports.cmake:90 (include)

Error: Building package hdf5:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: hdf5:x86-windows
  Vcpkg version: 2020.02.04-nohash

Additionally, attach any relevant sections from the log files above.` 

and the last line of log is:

[318/321] "F:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\bin\Hostx64\x86\cl.exe"   -DDEBUG -DH5_BUILT_AS_DYNAMIC_LIB -DSZ_BUILT_AS_DYNAMIC_LIB=1 -D_BIND_TO_CURRENT_VCLIBS_VERSION=1 -D_CONSOLE -D_CRT_SECURE_NO_WARNINGS -Dhdf5_shared_EXPORTS -IF:\dev\vcpkg-master\vcpkg-master\buildtrees\hdf5\src\hdf5-69d2d96f64\hdf5-1.10.5\src -I. -IF:\dev\vcpkg-master\vcpkg-master\installed\x86-windows\include /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /Fosrc\CMakeFiles\hdf5-shared.dir\__\shared\H5Tinit.c.obj /Fdsrc\CMakeFiles\hdf5-shared.dir\ /FS -c shared\H5Tinit.c
Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29914 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

ninja: build stopped: subcommand failed.

**Comment by JackBoosY** [comment]
cc @Neumann-A

**Comment by NancyLi1013** [comment]
Hi @Erixar 

Thanks for posting this issue.

Do you try these steps to build vtk8.2  https://github.com/microsoft/vcpkg/issues/14040#issuecomment-708850966?

**Comment by Erixar** [comment]
> Hi @Erixar
> 
> Thanks for posting this issue.
> 
> Do you try these steps to build vtk8.2 [#14040 (comment)](https://github.com/microsoft/vcpkg/issues/14040#issuecomment-708850966)?

Yes I did. Actually, I cloned many different vcpkg,some of them can handle the problem about hdf5 ,but all of them get trouble during libharu building.

**Comment by NancyLi1013** [comment]
Can you help provide _F:\dev\vcpkg-master\vcpkg-master\buildtrees\libharu\install-x86-windows-dbg-out.log_?

**Comment by Erixar** [comment]
> Can you help provide _F:\dev\vcpkg-master\vcpkg-master\buildtrees\libharu\install-x86-windows-dbg-out.log_?

[install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/6396267/install-x86-windows-dbg-out.log)

**Comment by JackBoosY** [comment]
```
F:\dev\vcpkg-master\vcpkg-master\installed\x86-windows\include\hpdf_objects.h(1): warning C4828: The file contains a character starting at offset 0xb25 that is illegal in the current source character set (codepage 65001).
F:\dev\vcpkg-master\vcpkg-master\installed\x86-windows\include\hpdf_objects.h(1): warning C4828: The file contains a character starting at offset 0xb30 that is illegal in the current source character set (codepage 65001).
F:\dev\vcpkg-master\vcpkg-master\buildtrees\libharu\src\2457fbc371-4d4e4f544f\include\hpdf_objects.h(1): warning C4828: The file contains a character starting at offset 0xb25 that is illegal in the current source character set (codepage 65001).
F:\dev\vcpkg-master\vcpkg-master\buildtrees\libharu\src\2457fbc371-4d4e4f544f\include\hpdf_objects.h(1): warning C4828: The file contains a character starting at offset 0xb30 that is illegal in the current source character set (codepage 65001).
F:\dev\vcpkg-master\vcpkg-master\installed\x86-windows\include\hpdf.h(39): warning C4005: 'HPDF_EXPORT': macro redefinition
F:\dev\vcpkg-master\vcpkg-master\installed\x86-windows\include\hpdf.h(26): note: see previous definition of 'HPDF_EXPORT'
F:\dev\vcpkg-master\vcpkg-master\installed\x86-windows\include\hpdf.h(57): error C2371: 'HPDF_Boolean': redefinition; different basic types
F:\dev\vcpkg-master\vcpkg-master\installed\x86-windows\include\hpdf_objects.h(136): note: see declaration of 'HPDF_Boolean'
```

**Comment by JonLiu1993** [comment]
@Erixar, According to [this ](https://github.com/microsoft/vcpkg/issues/14040#issuecomment-708850966)step, I can successfully install vtk 8.2.0 on the local machine. 
````
Installing package pugixml[core]:x64-windows...
Installing package pugixml[core]:x64-windows... done
Elapsed time for package pugixml:x64-windows: 10.06 s
Starting package 27/27: vtk:x64-windows
Building package vtk[core]:x64-windows...
-- Downloading https://github.com/Kitware/VTK/archive/v8.2.0.tar.gz...
-- Extracting source F:/test-pr/test/VTK/vcpkg/downloads/Kitware-VTK-v8.2.0.tar.gz
-- Applying patch fix-find-lz4.patch
-- Applying patch fix_ogg_linkage.patch
-- Applying patch fix-pugixml-link.patch
-- Applying patch hdf5_static.patch
-- Applying patch fix-find-lzma.patch
-- Applying patch fix-proj4.patch
-- Applying patch fix-VTKConfig-cmake.patch
-- Using source at F:/test-pr/test/VTK/vcpkg/buildtrees/vtk/src/v8.2.0-713722961b
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: F:/test-pr/test/VTK/vcpkg/packages/vtk_x64-windows/share/vtk/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package vtk[core]:x64-windows... done
Installing package vtk[core]:x64-windows...
Installing package vtk[core]:x64-windows... done
Elapsed time for package vtk:x64-windows: 19.11 min

Total elapsed time: 33.93 min

The package vtk:x64-windows provides CMake targets:

    find_package(VTK CONFIG REQUIRED)
    # Note: 102 target(s) were omitted.
    target_link_libraries(main PRIVATE foo vtksys somelib verdict)
````
Can you provide the source code involved in your error?
````
F:\dev\vcpkg-master\vcpkg-master\installed\x86-windows\include\hpdf.h(57): error C2371: 'HPDF_Boolean': redefinition; different basic types
````

**Comment by Erixar** [comment]
Sorry, I've lost my old disk after an accident so I can't provide it .  XD 
I'll close this issue later and thx for your helping.

> @Erixar, According to [this ](https://github.com/microsoft/vcpkg/issues/14040#issuecomment-708850966)step, I can successfully install vtk 8.2.0 on the local machine.
> 
> ```
> Installing package pugixml[core]:x64-windows...
> Installing package pugixml[core]:x64-windows... done
> Elapsed time for package pugixml:x64-windows: 10.06 s
> Starting package 27/27: vtk:x64-windows
> Building package vtk[core]:x64-windows...
> -- Downloading https://github.com/Kitware/VTK/archive/v8.2.0.tar.gz...
> -- Extracting source F:/test-pr/test/VTK/vcpkg/downloads/Kitware-VTK-v8.2.0.tar.gz
> -- Applying patch fix-find-lz4.patch
> -- Applying patch fix_ogg_linkage.patch
> -- Applying patch fix-pugixml-link.patch
> -- Applying patch hdf5_static.patch
> -- Applying patch fix-find-lzma.patch
> -- Applying patch fix-proj4.patch
> -- Applying patch fix-VTKConfig-cmake.patch
> -- Using source at F:/test-pr/test/VTK/vcpkg/buildtrees/vtk/src/v8.2.0-713722961b
> -- Configuring x64-windows
> -- Building x64-windows-dbg
> -- Building x64-windows-rel
> -- Installing: F:/test-pr/test/VTK/vcpkg/packages/vtk_x64-windows/share/vtk/copyright
> -- Performing post-build validation
> -- Performing post-build validation done
> Building package vtk[core]:x64-windows... done
> Installing package vtk[core]:x64-windows...
> Installing package vtk[core]:x64-windows... done
> Elapsed time for package vtk:x64-windows: 19.11 min
> 
> Total elapsed time: 33.93 min
> 
> The package vtk:x64-windows provides CMake targets:
> 
>     find_package(VTK CONFIG REQUIRED)
>     # Note: 102 target(s) were omitted.
>     target_link_libraries(main PRIVATE foo vtksys somelib verdict)
> ```
> 
> Can you provide the source code involved in your error?
> 
> ```
> F:\dev\vcpkg-master\vcpkg-master\installed\x86-windows\include\hpdf.h(57): error C2371: 'HPDF_Boolean': redefinition; different basic types
> ```
