### ISSUE TITLE
[New Port Request] libstudxml

### ISSUE THREAD

**Issue by Endleon201** [microsoft/vcpkg#17524]
Library name: libstudxml

Library description: serialize and parse XML

Source repository URL: https://github.com/windoze/libstudxml

Project homepage (if different from the source repository): https://git.codesynthesis.com/cgit/libstudxml/libstudxml/

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
