### ISSUE TITLE
VMs must prohibit all except TLS1.2

### ISSUE THREAD

**Issue by BillyONeal** [microsoft/vcpkg#17521]
Microsoft security folks are requiring that we deploy a policy to VMs which prohibit SSL2, SSL3, TLS1.0, and TLS1.1, and explicitly enables TLS 1.2.

It is likely some ports with bad upstreams will need to be skipped :(

https://lens.msftcloudes.com/#/dashboard/2c37cbdd-458d-4246-8cd4-e047666bf65c?_g=(ws:a87b7f92-6a82-4035-ab60-be5395cf8032)&params=(filters:!((k:ServiceId,v:'70512567-b69e-4c72-be49-87ee14b91e84')))

**Comment by JackBoosY** [comment]
Sadly.
