### ISSUE TITLE
Error: Building package liblzma:x86-uwp failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by liujie1982** [microsoft/vcpkg#17539]
Hi guys please help me,

\vcpkg>.\vcpkg install opencv[contrib]:x86-uwp --recurse
Computing installation plan...
The following packages will be built and installed:
  * liblzma[core]:x86-uwp -> 5.2.5#2
  * libpng[core]:x86-uwp -> 1.6.37#14
  * libwebp[core,nearlossless,simd,unicode]:x86-uwp -> 1.1.0#2
    opencv[contrib,core,dnn,jpeg,png,quirc,tiff,webp]:x86-uwp -> 4.5.1
  * opencv4[contrib,core,dnn,jpeg,png,quirc,tiff,webp]:x86-uwp -> 4.5.1
  * protobuf[core]:x86-uwp -> 3.15.8
  * quirc[core]:x86-uwp -> 1.1#2
  * tiff[core]:x86-uwp -> 4.1.0#2
  * zlib[core]:x86-uwp -> 1.2.11#10
Additional packages (*) will be modified to complete this operation.
Warning: The following VS instances are excluded because the English language pack is unavailable.
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community
    C:\Program Files (x86)\Microsoft Visual Studio 12.0\
Please install the English language pack.
Detecting compiler hash for triplet x86-uwp...
Could not locate cached archive: C:\Users\Liu Jie
[install-x86-uwp-dbg-out.log](https://github.com/microsoft/vcpkg/files/6386116/install-x86-uwp-dbg-out.log)
\AppData\Local\vcpkg\archives\4e\4ed0aeee67f0c0898caea3f4e416ef5f64acc6ba.zip
Could not locate cached archive: C:\Users\Liu Jie\AppData\Local\vcpkg\archives\0d\0ddac2a10cb09971c8dd942327dd1e41c3b9a6fa.zip
Could not locate cached archive: C:\Users\Liu Jie\AppData\Local\vcpkg\archives\cd\cd958ab625de916dd3cba7d6430ce6f6aadcc4ca.zip
Could not locate cached archive: C:\Users\Liu Jie\AppData\Local\vcpkg\archives\b8\b8fd60904072cd9738ef1fd25bcfc6a2bfdc6432.zip
Could not locate cached archive: C:\Users\Liu Jie\AppData\Local\vcpkg\archives\fb\fb0fa37b5ff379f4d563dae62d897a0a358bd8b7.zip
Could not locate cached archive: C:\Users\Liu Jie\AppData\Local\vcpkg\archives\e2\e2590fff5c54ab7da6f3fe6abb6e5662a3c15494.zip
Could not locate cached archive: C:\Users\Liu Jie\AppData\Local\vcpkg\archives\cd\cd238cd2944403dc5a2d3f0d027e0ebce6f4ff1b.zip
Could not locate cached archive: C:\Users\Liu Jie\AppData\Local\vcpkg\archives\ed\edcdcc1de8a935dee523823e9803136155e34963.zip
Could not locate cached archive: C:\Users\Liu Jie\AppData\Local\vcpkg\archives\1a\1a36e2bc2bbc78c6eabce6a30052944659b85f0d.zip
Starting package 1/9: liblzma:x86-uwp
Building package liblzma[core]:x86-uwp...
-- Using community triplet x86-uwp. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: E:\Goddard\microsoft\vcpkg\triplets\community\x86-uwp.cmake
-- Using cached E:/Goddard/microsoft/vcpkg/downloads/xz-mirror-xz-v5.2.5.tar.gz
-- Cleaning sources at E:/Goddard/microsoft/vcpkg/buildtrees/liblzma/src/v5.2.5-77236e0e89.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/Goddard/microsoft/vcpkg/downloads/xz-mirror-xz-v5.2.5.tar.gz
-- Applying patch enable-uwp-builds.patch
-- Applying patch fix_config_include.patch
-- Applying patch win_output_name.patch
-- Using source at E:/Goddard/microsoft/vcpkg/buildtrees/liblzma/src/v5.2.5-77236e0e89.clean
-- Configuring x86-uwp
-- Building x86-uwp-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:146 (message):
    Command failed: E:/Goddard/microsoft/vcpkg/downloads/tools/cmake-3.20.1-windows/cmake-3.20.1-windows-i386/bin/cmake.exe --build . --config Debug --target install -- /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /m
    Working Directory: E:/Goddard/microsoft/vcpkg/buildtrees/liblzma/x86-uwp-dbg
    See logs for more information:
      E:\Goddard\microsoft\vcpkg\buildtrees\liblzma\install-x86-uwp-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:105 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:45 (vcpkg_build_cmake)
  ports/liblzma/portfile.cmake:19 (vcpkg_install_cmake)
  scripts/ports.cmake:142 (include)

Error: Building package liblzma:x86-uwp failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: liblzma:x86-uwp
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

Additionally, attach any relevant sections from the log files above.

**Comment by liujie1982** [comment]
[install-x86-uwp-dbg-out.log](https://github.com/microsoft/vcpkg/files/6386124/install-x86-uwp-dbg-out.log)

**Comment by liujie1982** [comment]
stream_encoder_mt.obj : error LNK2019: 无法解析的外部符号(Unresolved external symbol ) _GetTickCount，该符号在函数(The symbol in the function ) _mythread_cond_timedwait 中被引用(Cited in) [E:\Goddard\microsoft\vcpkg\buildtrees\liblzma\x86-uwp-dbg\liblzma.vcxproj]

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. `liblzma:x86-uwp` can install succeed now. And this issue hasn’t been updated more than 3 months, if it is still an issue, please reopen this issue.
```
Installing package liblzma[core]:x86-uwp...
Elapsed time for package liblzma:x86-uwp: 39.36 s

Total elapsed time: 56.97 s
```
