### ISSUE TITLE
[python3[core]:x64-windows -> 3.9.2#1] build failure

### ISSUE THREAD

**Issue by warm-dawn** [microsoft/vcpkg#17530]
**Host Environment**
- OS: Windows10

**To Reproduce**
`vcpkg install python3`

**Failure logs** 
`
PS D:\env\vcpkg> vcpkg install python3
Computing installation plan...
A suitable version of cmake was not found (required v3.20.1). Downloading portable cmake v3.20.1...
Downloading cmake...
  https://github.com/Kitware/CMake/releases/download/v3.20.1/cmake-3.20.1-windows-i386.zip -> D:\env\vcpkg\downloads\cmake-3.20.1-windows-i386.zip
Extracting cmake...
The following packages will be built and installed:
    python3[core]:x64-windows -> 3.9.2#1
Warning: The following VS instances are excluded because the English language pack is unavailable.
    D:\Program Files (x86)\Microsoft Visual Studio 12.0\
Please install the English language pack.
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\.zip
Starting package 1/1: python3:x64-windows
Building package python3[core]:x64-windows...
-- Using cached D:/env/vcpkg/downloads/python-cpython-v3.9.2.tar.gz
-- Cleaning sources at D:/env/vcpkg/buildtrees/python3/src/v3.9.2-cc9ebdcfd9.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/env/vcpkg/downloads/python-cpython-v3.9.2.tar.gz
-- Applying patch 0002-use-vcpkg-zlib.patch
-- Applying patch 0003-devendor-external-dependencies.patch
-- Applying patch 0004-dont-copy-vcruntime.patch
-- Applying patch 0005-only-build-required-projects.patch
-- Applying patch 0006-fix-duplicate-symbols.patch
-- Using source at D:/env/vcpkg/buildtrees/python3/src/v3.9.2-cc9ebdcfd9.clean
-- Building PCbuild/pcbuild.proj for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
    Command failed: msbuild D:/env/vcpkg/buildtrees/python3/x64-windows-rel/v3.9.2-cc9ebdcfd9.clean/PCbuild/pcbuild.proj /p:Configuration=Release /p:IncludeExtensions=true /p:IncludeExternals=true /p:IncludeCTypes=true /p:IncludeSSL=true /p:IncludeTkinter=false /p:IncludeTests=false /p:ForceImportBeforeCppTargets=D:/env/vcpkg/buildtrees/python3/src/v3.9.2-cc9ebdcfd9.clean/PCbuild/python_vcpkg.props /p:IncludeUwp=false /p:_VcpkgPythonLinkage=DynamicLibrary /t:Rebuild /p:Platform=x64 /p:PlatformToolset=v142 /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /p:WindowsTargetPlatformVersion=10.0.19041.0 /p:VcpkgTriplet=x64-windows /p:VcpkgInstalledDir=D:/env/vcpkg/installed /p:VcpkgManifestInstall=false /m
    Working Directory: D:/env/vcpkg/buildtrees/python3/x64-windows-rel/v3.9.2-cc9ebdcfd9.clean
    Error code: 1
    See logs for more information:
      D:\env\vcpkg\buildtrees\python3\build-x64-windows-rel-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_msbuild.cmake:165 (vcpkg_execute_required_process)
  ports/python3/portfile.cmake:110 (vcpkg_install_msbuild)
  scripts/ports.cmake:142 (include)

Error: Building package python3:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: python3:x64-windows
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

Additionally, attach any relevant sections from the log files above.
`

**Additional context**
'
       “D:\env\vcpkg\buildtrees\python3\x64-windows-rel\v3.9.2-cc9ebdcfd9.clean\PCbuild\pcbuild.proj”(Rebuild 目标) (1) ->
       “D:\env\vcpkg\buildtrees\python3\x64-windows-rel\v3.9.2-cc9ebdcfd9.clean\PCbuild\_ssl.vcxproj”(Build 目标) (25:2) ->
         LINK : fatal error LNK1181: cannot open input file 'CRYPTO_RELEASE-NOTFOUND.obj' [D:\env\vcpkg\buildtrees\python3\x64-windows-rel\v3.9.2-cc9ebdcfd9.clean\PCbuild\_ssl.vcxproj]
'

**Comment by PhoebeHui** [comment]
@warm-dawn, could you attach full failure log 'D:\env\vcpkg\buildtrees\python3\build-x64-windows-rel-out.log'?

**Comment by warm-dawn** [comment]
yes is ok.
