### ISSUE TITLE
[v8] build failure

### ISSUE THREAD

**Issue by omartijn** [microsoft/vcpkg#17536]
**Host Environment**
- OS: Linux
- Compiler: Clang 12

**To Reproduce**
`./vcpkg install v8`

**Failure logs** 
/bin/sh: 1: g++: not found

**Additional context**
v8 fails to build if g++ isn't installed. Since vcpkg ports shouldn't assume a particular compiler, this is clearly a port bug.

**Comment by JackBoosY** [comment]
cc @Neumann-A @Kwizatz

**Comment by Neumann-A** [comment]
That is probably a case for somebody knowing vcpkg_configure_gn instead of me. Probably missing usage of vcpkg_get_cmake_vars

**Comment by Kwizatz** [comment]
is_clang=false is hard coded in the portfile, it may be possible to add a feature to turn it on, but right now you can change the value directly and see if that works, it should since that's the default compiler used by upstream. Please report back :)

**Comment by omartijn** [comment]
Thanks, @Kwizatz. I've tried removing the `is_clang=false` as well as changing is for `is_clang=true`, which now gives me a different error. The output of `buildtrees/v8/generate-x64-linux-dbg-out.log` is as follows:

```
ERROR at //build/config/compiler/BUILD.gn:1235:22: Script returned non-zero exit code.
    clang_revision = exec_script("//tools/clang/scripts/update.py",
                     ^----------
Current dir: /home/omartijn/git/vcpkg/buildtrees/v8/x64-linux-dbg/
Command: python /home/omartijn/git/vcpkg/buildtrees/v8/src/58ffcee747-a9d685497a.clean/tools/clang/scripts/update.py --print-revision --verify-version=13.0.0
Returned 2.
stderr:

python: can't open file '/home/omartijn/git/vcpkg/buildtrees/v8/src/58ffcee747-a9d685497a.clean/tools/clang/scripts/update.py': [Errno 2] No such file or directory

See //BUILD.gn:438:5: which caused the file to be included.
    "//build/config/compiler:wexit_time_destructors",
    ^-----------------------------------------------
```

A few things stand out:

- It's trying to execute a python file that _should_ be in the v8 folder, but isn't
- It seems like it's trying to verify my clang version is 13.0

Now, I'm running clang 12.0, which is the latest stable. 13.0 is still just the current `master` branch of clang.

**Comment by Kwizatz** [comment]
tools/clang/scripts/ may be a third party repo that needs to be added to the build, I don't see it anywhere.
As for the version, I don't know if that's going to be a problem, I do know that the default depot tools Linux build downloads its own toolchain and sysroot, so we may find some problems there.

**Comment by omartijn** [comment]
I think I found the right repo. https://chromium.googlesource.com/chromium/src/tools seems to contain the right files at the right location. No idea how to actually use it, though, adding a `v8_fetch` to `ports/v8/portfile.cmake` doesn't do anything and strangely enough, running `./vcpkg install v8` reverts the change.

**Comment by Kwizatz** [comment]
This is the correct one:
https://chromium.googlesource.com/chromium/src/tools/clang.git
you'll have to add"
```
v8_fetch(
        DESTINATION tools/clang
        URL https://chromium.googlesource.com/chromium/src/tools/clang.git
        REF ba668f13d135f1d01faf9b03c9a05f5877ac3f51
        SOURCE ${SOURCE_PATH})
```
to the v8_fetch section of the portfile.

**Comment by JackBoosY** [comment]
@Kwizatz Should we also update the changes into vcpkg?

**Comment by omartijn** [comment]
Hmm, that looks suspiciously like what I wrote yesterday, yet your changes don't magically disappear like they did for me. Looks like you're right about getting into further problems. It fails with the following error now:

`/bin/sh: 1: ../src/58ffcee747-a9d685497a.clean/third_party/llvm-build/Release+Asserts/bin/clang++: not found`

They probably want to build clang from source there. Maybe there's a flag to get `gn` to simply use the system-default compiler. It makes no sense to always build clang from source just to build a package.

**Comment by Kwizatz** [comment]
> @Kwizatz Should we also update the changes into vcpkg?

No, there is more to be done, like checking the CMAKE_C_COMPILER and CMAKE_CXX_COMPILER flags to determine if clang should be used and then only download the clang bits if so.


> Hmm, that looks suspiciously like what I wrote yesterday, yet your changes don't magically disappear like they did for me. Looks like you're right about getting into further problems. It fails with the following error now:
> 
> `/bin/sh: 1: ../src/58ffcee747-a9d685497a.clean/third_party/llvm-build/Release+Asserts/bin/clang++: not found`
> 
> They probably want to build clang from source there. Maybe there's a flag to get `gn` to simply use the system-default compiler. It makes no sense to always build clang from source just to build a package.

Yes, that is probably it. third_party/llvm-build/Release+Asserts/bin is part of the main v8 repo, so there is probably some download script we're missing, but either way we want to use system clang. I think this https://github.com/AeonGames/build/tree/master/toolchain/linux/unbundle might be a good start to figure it out. I'll take a go at it later in the week.

**Comment by Kwizatz** [comment]
@omartijn 

So, yes, in the portfile in the same string where is_clang=false/true is add the gn vars: custom_toolchain="//build/toolchain/linux/unbundle:default" host_toolchain="//build/toolchain/linux/unbundle:default" escaping quotes.
