### ISSUE TITLE
Building package  xxhash:x64-windows failed with : BUILD_FAILED

### ISSUE THREAD

**Issue by Skrotice** [microsoft/vcpkg#17532]
Package: xxhash:x64-windows
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

**Comment by JackBoosY** [comment]
Please provide the full output on Powershell.

Thanks.

**Comment by Skrotice** [comment]
> Please provide the full output on Powershell.
> 
> Thanks.

 .\vcpkg install blosc:x64-windows
Computing installation plan...
The following packages will be built and installed:
    blosc[core]:x64-windows -> 1.18.1-1
  * lz4[core]:x64-windows -> 1.9.3
  * snappy[core]:x64-windows -> 1.1.8
  * xxhash[core]:x64-windows -> 0.8.0#1
  * zstd[core]:x64-windows -> 1.4.9
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\wangy\AppData\Local\vcpkg\archives\b3\b3b72c85d705963b1c01ee54d6bef4fe78699acc.zip
Could not locate cached archive: C:\Users\wangy\AppData\Local\vcpkg\archives\a7\a75c88d7af49980e625b074d4108b5539d2c6ae5.zip
Could not locate cached archive: C:\Users\wangy\AppData\Local\vcpkg\archives\f6\f6bb28b369ca622c446251db215eaf79e8dcc642.zip
Could not locate cached archive: C:\Users\wangy\AppData\Local\vcpkg\archives\60\6038106ce5f930f2d7be79697fb339125111c1e7.zip
Could not locate cached archive: C:\Users\wangy\AppData\Local\vcpkg\archives\70\706df8ef11e726ecf0b8feed28fc18a891ad2423.zip
Starting package 1/5: xxhash:x64-windows
Building package xxhash[core]:x64-windows...
-- Using cached D:/codepage/vcpkg/downloads/Cyan4973-xxHash-94e5f23e736f2bb67ebdf90727353e65344f9fc0.tar.gz
-- Cleaning sources at D:/codepage/vcpkg/buildtrees/xxhash/src/65344f9fc0-10f42fcb8c.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/codepage/vcpkg/downloads/Cyan4973-xxHash-94e5f23e736f2bb67ebdf90727353e65344f9fc0.tar.gz
-- Using source at D:/codepage/vcpkg/buildtrees/xxhash/src/65344f9fc0-10f42fcb8c.clean
CMake Deprecation Warning at scripts/cmake/vcpkg_check_features.cmake:182 (message):
  calling `vcpkg_check_features` without the `FEATURES` keyword has been
  deprecated.

      Please add the `FEATURES` keyword to the call.
Call Stack (most recent call first):
  ports/xxhash/portfile.cmake:9 (vcpkg_check_features)
  scripts/ports.cmake:142 (include)


-- Found external ninja('1.10.2').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: D:/codepage/vcpkg/packages/xxhash_x64-windows/share/xxhash/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\wangy\AppData\Local\vcpkg\archives\b3\b3b72c85d705963b1c01ee54d6bef4fe78699acc.zip
Building package xxhash[core]:x64-windows... done
Installing package xxhash[core]:x64-windows...
Installing package xxhash[core]:x64-windows... done
Elapsed time for package xxhash:x64-windows: 10.42 s
Starting package 2/5: lz4:x64-windows
Building package lz4[core]:x64-windows...
-- Downloading https://github.com/lz4/lz4/archive/v1.9.3.tar.gz -> lz4-lz4-v1.9.3.tar.gz...
-- Extracting source D:/codepage/vcpkg/downloads/lz4-lz4-v1.9.3.tar.gz
-- Using source at D:/codepage/vcpkg/buildtrees/lz4/src/v1.9.3-4743bd4e50.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: D:/codepage/vcpkg/packages/lz4_x64-windows/share/lz4/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\wangy\AppData\Local\vcpkg\archives\a7\a75c88d7af49980e625b074d4108b5539d2c6ae5.zip
Building package lz4[core]:x64-windows... done
Installing package lz4[core]:x64-windows...
Installing package lz4[core]:x64-windows... done
Elapsed time for package lz4:x64-windows: 11.59 s
Starting package 3/5: snappy:x64-windows
Building package snappy[core]:x64-windows...
-- Downloading https://github.com/google/snappy/archive/537f4ad6240e586970fe554614542e9717df7902.tar.gz -> google-snappy-537f4ad6240e586970fe554614542e9717df7902.tar.gz...
-- Downloading https://github.com/google/snappy/archive/537f4ad6240e586970fe554614542e9717df7902.tar.gz... Failed. Status: 28;"Timeout was reached"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:184 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".

      If error with status 4 (Issue #15434),
      try setting "http://user:password@your-proxy-ip-address:port/".

      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:147 (vcpkg_download_distfile)
  ports/snappy/portfile.cmake:1 (vcpkg_from_github)
  scripts/ports.cmake:142 (include)


Error: Building package snappy:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: snappy:x64-windows
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

I've tried again and the package xxhash  is installed, but package snappy failed.

**Comment by Skrotice** [comment]
> Please provide the full output on Powershell.
> 
> Thanks.

I tried again and the BUILD_FAILED reason was "Failed to download file"

**Comment by JackBoosY** [comment]
Please download https://github.com/Cyan4973/xxHash/archive/94e5f23e736f2bb67ebdf90727353e65344f9fc0.tar.gz manually then put it into _VCPKG_ROOT/downloads_, then rebuild xxhash.

**Comment by NancyLi1013** [comment]
@Skrotice 

Please let me know if this is still a problem for you now.

**Comment by Skrotice** [comment]
@NancyLi1013 It's solved by downloading the package directly.
