### ISSUE TITLE
Update docs manifest

### ISSUE THREAD

**Issue by mathisloge** [microsoft/vcpkg#17548]
**Describe the bug**
https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/manifest-files.md#version-fields

it only says that version-string exists. however, version, version-string and version-semver exist (to my knowledge). 

It would be good if someone with deeper knowlege would add the new version types.

**Comment by JackBoosY** [comment]
It's in https://github.com/microsoft/vcpkg/blob/master/docs/specifications/versioning.md#22-package-versions.

**Comment by mathisloge** [comment]
maybe we should cross link this?

**Comment by JackBoosY** [comment]
Yes.
