### ISSUE TITLE
Error: Building package fontconfig:x64-osx failed with: BUILD_FAILED ...

### ISSUE THREAD

**Issue by arc-yong** [microsoft/vcpkg#17547]
-- Configuring x64-osx-dbg
-- Configuring x64-osx-rel
CMake Error at scripts/cmake/vcpkg_configure_make.cmake:575 (message):
  fontconfig requires autoconf from the system package manager (example:
  "sudo apt-get install autoconf")
Call Stack (most recent call first):
  ports/fontconfig/portfile.cmake:26 (vcpkg_configure_make)
  scripts/ports.cmake:142 (include)

Error: Building package fontconfig:x64-osx failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: fontconfig:x64-osx
  Vcpkg version: 2021-01-13-unknownhash

**Comment by JackBoosY** [comment]
`  fontconfig requires autoconf from the system package manager`
Did you install autoconf first?

**Comment by dg0yt** [comment]
On macOS, the recommendation should be like
`brew install autoconf automake`

**Comment by nil-is-lin** [comment]
> On macOS, the recommendation should be like
> `brew install autoconf automake`

after this，it throws a new error:

> CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
>     Command failed: /usr/local/bin/autoreconf -vfi
>     Working Directory: /Users/linli/vcpkg/buildtrees/fontconfig/src/75c13b2421-12bdc6f9c0.clean/
>     Error code: 2
>     See logs for more information:
>       /Users/linli/vcpkg/buildtrees/fontconfig/autoconf-x64-osx-err.log
> 
> Call Stack (most recent call first):
>   scripts/cmake/vcpkg_configure_make.cmake:638 (vcpkg_execute_required_process)
>   ports/fontconfig/portfile.cmake:26 (vcpkg_configure_make)
>   scripts/ports.cmake:139 (include)
> 
> 
> Error: Building package fontconfig:x64-osx failed with: BUILD_FAILED
> Please ensure you're using the latest portfiles with `./vcpkg update`, then
> submit an issue at https://github.com/Microsoft/vcpkg/issues including:
>   Package: fontconfig:x64-osx
>   Vcpkg version: 2021-05-05-unknownhash

OS: MacOS Big Sur 11.4, any help?

**Comment by dg0yt** [comment]
You didn't provide `/Users/linli/vcpkg/buildtrees/fontconfig/autoconf-x64-osx-err.log`. I wouldn't be surprised if you also need to `brew install gettext`, for the program `autopoint`.

**Comment by nil-is-lin** [comment]
> You didn't provide `/Users/linli/vcpkg/buildtrees/fontconfig/autoconf-x64-osx-err.log`. I wouldn't be surprised if you also need to `brew install gettext`, for the program `autopoint`.

yes, `brew install gettext` works well for me. Many THX.

**Comment by nil-is-lin** [comment]
In my /Users/linli/vcpkg/buildtrees/fontconfig/autoconf-x64-osx-err.log, I found:

> src/Makefile.am:166: error: Libtool library used but 'LIBTOOL' is undefined
> src/Makefile.am:166:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
> src/Makefile.am:166:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
> src/Makefile.am:166:   If 'LT_INIT' is in 'configure.ac', make sure
> src/Makefile.am:166:   its definition is in aclocal's search path.
> autoreconf: error: automake failed with exit status: 1

It throw another error.

**Comment by dg0yt** [comment]
Well, the answer will be similar. You can see what is installed with `brew` for CI here:
https://github.com/microsoft/vcpkg/blob/master/scripts/azure-pipelines/osx/configuration/vagrant-box-configuration.json
but that may be too much for you case.

**Comment by nil-is-lin** [comment]
> Well, the answer will be similar. You can see what is installed with `brew` for CI here:
> https://github.com/microsoft/vcpkg/blob/master/scripts/azure-pipelines/osx/configuration/vagrant-box-configuration.json
> but that may be too much for you case.

It did, and to save me the trouble, I installed all  using the brew install pkgname command and everything went smoothly.

At last, may your code be bug-free forever.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
