### ISSUE TITLE
Error: Building package abseil:wasm32-emscripten failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by giffordlocke** [microsoft/vcpkg#17546]
Starting package 1/15: abseil:wasm32-emscripten
Building package abseil[core]:wasm32-emscripten...
-- Using community triplet wasm32-emscripten. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: D:\vcpkg\triplets\community\wasm32-emscripten.cmake
-- Using cached D:/vcpkg/downloads/abseil-abseil-cpp-997aaf3a28308eba1b9156aa35ab7bca9688e9f6.tar.gz
-- Cleaning sources at D:/vcpkg/buildtrees/abseil/src/ca9688e9f6-e4cda1d679.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/vcpkg/downloads/abseil-abseil-cpp-997aaf3a28308eba1b9156aa35ab7bca9688e9f6.tar.gz
-- Applying patch fix-cxx-standard.patch
-- Using source at D:/vcpkg/buildtrees/abseil/src/ca9688e9f6-e4cda1d679.clean
-- Configuring wasm32-emscripten-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):

    Command failed: D:/vcpkg/downloads/tools/cmake-3.20.1-windows/cmake-3.20.1-windows-i386/bin/cmake.exe D:/vcpkg/buildtrees/abseil/src/ca9688e9f6-e4cda1d679.clean -DABSL_USE_CXX17=OFF -DCMAKE_MAKE_PROGRAM=D:/vcpkg/downloads/tools/ninja/1.10.1-windows/ninja.exe -DCMAKE_SYSTEM_NAME=Emscripten -DBUILD_SHARED_LIBS=OFF -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=D:/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DVCPKG_TARGET_TRIPLET=wasm32-emscripten -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=external -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=D:/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_LINKER_FLAGS_RELEASE= -DVCPKG_LINKER_FLAGS_DEBUG= -DVCPKG_TARGET_ARCHITECTURE=wasm32 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -D_VCPKG_ROOT_DIR=D:/vcpkg -D_VCPKG_INSTALLED_DIR=D:/vcpkg/installed -DVCPKG_MANIFEST_INSTALL=OFF -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=D:/vcpkg/packages/abseil_wasm32-emscripten/debug
    Working Directory: D:/vcpkg/buildtrees/abseil/wasm32-emscripten-dbg
    Error code: 1
    See logs for more information:
      D:\vcpkg\buildtrees\abseil\config-wasm32-emscripten-dbg-out.log
      D:\vcpkg\buildtrees\abseil\config-wasm32-emscripten-dbg-err.log

 D:\vcpkg\buildtrees\abseil 
[abseil.zip](https://github.com/microsoft/vcpkg/files/6388933/abseil.zip)

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:333 (vcpkg_execute_required_process)
  ports/abseil/portfile.cmake:25 (vcpkg_configure_cmake)
  scripts/ports.cmake:142 (include)

Error: Building package abseil:wasm32-emscripten failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: abseil:wasm32-emscripten
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

**Comment by MoAlyousef** [comment]
What version of Emscripten are you running?
It seems to be failing on Threads, which is a recent addition to Emscripten, and requires a certain linker flag “-s USE_PTHREADS=1”.

**Comment by giffordlocke** [comment]
> What version of Emscripten are you running?
> It seems to be failing on Threads, which is a recent addition to Emscripten, and requires a certain linker flag “-s USE_PTHREADS=1”.

emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.38.27
clang version 6.0.1  (emscripten 1.38.27 : 1.38.27)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: D:\emsdk\fastcomp-clang\e1.38.27_64bit
shared:INFO: (Emscripten: Running sanity checks)

This error occurs when I run  “vcpkg install grpc --triplet=wasm32-emscripten ”
how to use  the “-s USE_PTHREADS=1”?

**Comment by LilyWangLL** [comment]
This issue hasn’t been updated more than 3 months, if it is still an issue, please reopen this issue.
