### ISSUE TITLE
How do I set _ITERATOR_DEBUG_LEVEL=0 for every static library I build?

### ISSUE THREAD

**Issue by LeeGDavis** [microsoft/vcpkg#17545]
I am statically linking against a library that has `_ITERATOR_DEBUG_LEVEL` set to `0` for Debug and want to do this for everything Debug I build with vcpkg, as it appears the default is `2`.

Currently using the `VCPKG_DEFAULT_TRIPLET="x64-windows-static"` It seems this might be possible with a custom triplet, but not sure if I can just set this value for a given triplet or inline when I run vcpkg install xxxxxx for example?

**Comment by JackBoosY** [comment]
https://github.com/microsoft/vcpkg/blob/b9cd2a7958dec657fb869ec487d2a98cf39a8d48/scripts/toolchains/windows.cmake#L28-L29

**Comment by LeeGDavis** [comment]
@JackBoosY I created a custom triplet and that seemed to work fine, however are you indicating that I can just set VCPKG_CXX_FLAGS_DEBUG to something like "-D_ITERATOR_DEBUG_LEVEL=0" when running vcpkg install boost-xxxxxx?  That would be much preferable, but I couldn't seem to get that to work.

**Comment by JackBoosY** [comment]
@LeeGDavis  Yep, you need to modify the toolchain file.

**Comment by LeeGDavis** [comment]
@JackBoosY Sorry I'm not 100% getting this.

I have tried the following without any luck.  Hopefully I'm just doing something stupid and have misunderstood you.

```
$env:VCPKG_CXX_FLAGS_DEBUG="/D_ITERATOR_DEBUG_LEVEL=0"
$env:VCPKG_C_FLAGS_DEBUG="/D_ITERATOR_DEBUG_LEVEL=0"
.\vcpkg install `
  boost-algorithm `
  boost-filesystem `
```
and
```
$env:VCPKG_CXX_FLAGS_DEBUG="-D_ITERATOR_DEBUG_LEVEL=0"
$env:VCPKG_C_FLAGS_DEBUG="-D_ITERATOR_DEBUG_LEVEL=0"
.\vcpkg install `
  boost-algorithm `
  boost-filesystem `
```

It seems to add the default triplet just fine using $env:VCPKG_DEFAULT_TRIPLET = "x64-windows-static"

**Comment by JackBoosY** [comment]
https://github.com/microsoft/vcpkg/blob/b9cd2a7958dec657fb869ec487d2a98cf39a8d48/scripts/toolchains/windows.cmake#L28-L29
Please change these 2 lines to:
```
    set(CMAKE_CXX_FLAGS_DEBUG "${VCPKG_CRT_LINK_FLAG_PREFIX}d /Z7 /Ob0 /Od /RTC1 ${VCPKG_CXX_FLAGS_DEBUG}" CACHE STRING "")
    set(CMAKE_C_FLAGS_DEBUG "${VCPKG_CRT_LINK_FLAG_PREFIX}d /Z7 /Ob0 /Od /RTC1 ${VCPKG_C_FLAGS_DEBUG}" CACHE STRING "")
```
And try again.
BTW, which port do you use?

**Comment by LeeGDavis** [comment]
This is basically what we are doing on our builds box atm.   Now just dynamically setting that existing triplet.
```
$env:VCPKG_DEFAULT_TRIPLET = "x64-windows-static"
Add-Content triplets\x64-windows-static.cmake 'set(VCPKG_CXX_FLAGS_DEBUG "-D_ITERATOR_DEBUG_LEVEL=0")'
Add-Content triplets\x64-windows-static.cmake 'set(VCPKG_C_FLAGS_DEBUG "-D_ITERATOR_DEBUG_LEVEL=0")'
.\vcpkg install `
    boost-algorithm `
    boost-filesystem `
    boost-interprocess `
    boost-format `
    curl `
    jsoncpp `
    log4cxx
```

We then setup cmake the following way:
```
exec { & "cmake" -G "Visual Studio 16 2019" -A x64 "-DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows-static" }
```

If it is necessary to update the toolchain file to achieve the same results, is this also a suitable alternative?  I would like to do this the most _correct_ way and if the toolchain modification is that, we can certainly change things around.

**Comment by JackBoosY** [comment]
@BillyONeal Do you know that? I think even if we modify it, post check will not pass.

**Comment by JackBoosY** [comment]
@LeeGDavis And why you need to do this? Can you only use the release library?

**Comment by PhoebeHui** [comment]
If you only apply the option to x64-windows-static, I think adding it to triplet is more suitable. If you want to apply it to all triplets, adding the option to the toolchain is good. Please make sure that the _ITERATOR_DEBUG_LEVEL macro in your project is the same with installed ports.

**Comment by LeeGDavis** [comment]
@JackBoosY We need both debug and release for this particular product.  Release is all the customer ever sees, but internally our SQA folks and Developers use a debug version if any issues crop up.  The reason our debug version needs this is we have another dependency that requires this same debug level, CEF/Chromium.  Iterator debugging has been disabled by default (_HAS_ITERATOR_DEBUGGING=0) for CEF/Chromium builds using clang/LLVM since 2018 and because of this difference it creates some crash scenarios. 
See: https://bugs.chromium.org/p/chromium/issues/detail?id=539996

@JackBoosY and @PhoebeHui Thanks again for all your help with this!

**Comment by JackBoosY** [comment]
For ports built using cmake/msbuild/makefile/meson, adding these two lines to the triplet file should solve this. But I am worried that there are other default compilation options that will override it.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

**Comment by JackBoosY** [comment]
BTW, you can use overlay-triplet. See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/examples/overlay-triplets-linux-dynamic.md).
