### ISSUE TITLE
graphicsmagick:x86-windows-static-md build failure

### ISSUE THREAD

**Issue by tester0077** [microsoft/vcpkg#17558]
**Host Environment**
Win 10 latest update
MSVC 2019 Community edition

**To Reproduce**
`./vcpkg install graphicsmagick:x86-windows-static-md`

**Failure logs** 
trying to link for 32-bit system gives linking errors:
graphicsmagick.lib(jbig.c.obj) : error LNK2019: unresolved external symbol __imp__jbg_enc_init referenced in function _WriteJBIGImage
...
1>graphicsmagick.lib(jbig.c.obj) : error LNK2019: unresolved external symbol __imp__jbg_dec_free referenced in function _ReadJBIGImage

issue 1 - it is intended to be a statically linked app
issue 2 - no indication that a library built for GM contains either of these 2 statically linked functions

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. `graphicsmagick:x86-windows-static-md` can install succeed now. If it is still an issue, please reopen this issue.
```
Installing package graphicsmagick[core]:x86-windows-static-md...
Elapsed time for package graphicsmagick:x86-windows-static-md: 1.067 min

Total elapsed time: 4.095 min
```
