### ISSUE TITLE
[grpc] gRPC doesn't build code generators

### ISSUE THREAD

**Issue by alexsmn** [microsoft/vcpkg#17555]
****

**Is your feature request related to a problem? Please describe.**
When building gRPC for `x86-windows` triplet from `x64-windows` host, `grpc_cpp_plugin.exe` isn't build.

**Proposed solution**
Allow building all code generators for 32-bit architecture under 64-bit platform.

**Describe alternatives you've considered**
Install both gRPC for both `x86-windows` and `x64-windows` triplets. And directly reference `grpc_cpp_plugin.exe` from `x64-windows` installation. That would require hard-coding the full path to `grpc_cpp_plugin.exe`. As well as it doesn't seem clean.

**Additional context**
To reproduce run on 64-bit host:
```
.\vcpkg install grpc:x86-windows
```
Check tool directory `%VCPKG%\installed\x86-windows\tools\grpc` does not exist.

**Comment by alexsmn** [comment]
Note that this regression was introduced by [this change](https://github.com/microsoft/vcpkg/commit/b5bb1511f0a07be530e0bde3ae098eb3d8e83e68#diff-b830bfa42a485b6f2f5f01bab642bdbd043b8b950f37578b50ccf6f44a14bfe5R24) relatively recently.

**Comment by alexsmn** [comment]
Seems this is not an issue when using manifests. Though it's not clear to me why both x86 and x64 sets of dependencies need to be built to obtain code generators.

**Comment by JackBoosY** [comment]
Now, the code is:
https://github.com/microsoft/vcpkg/blob/6a274ad4b370b3b729d3af6227f57257ec708b43/ports/grpc/portfile.cmake#L25-L43

So does this issue still exist?

**Comment by alexsmn** [comment]
Yes, it's fixed partially for non-manifest mode too. Now code generators are at least built under `installed\x64-windows`. The remaining issue is that in such implementation you have to hard-code code-generator path, while you should be able to get it from the CMake target output or just using `find_program`, like in the [example](https://github.com/googleapis/google-cloud-cpp/blob/main/cmake/FindgRPC.cmake#L44). Here is the [usage example](https://github.com/grpc/grpc/blob/master/examples/cpp/helloworld/CMakeLists.txt#L35).

Also building another `x64-windows` set of dependencies seems redundant when you need only `x86-windows`.

**Comment by JackBoosY** [comment]
The path is indeed hard-coded, because we need to find host-related executables and should not find others..

**Comment by alexsmn** [comment]
I'd like to separate it onto different points, since I don't know how it fits to the current design. It would be nice to resolve at least the first one.

1. If codegen path has to be hard-coded, there should be a way to obtain the hard-coded value. Because currently codegen path configuration needs to be updated on each build environment depending on it using manifest or non-manifest mode.

2. Ideally, there's no need to build a separate set of `x64-windows` tools when you build `x86-windows` packages, because x86 tools perfectly run on x64 platform.

3. Generally, it seems like x86 configurations are treated as cross-compiling when built on x64 platform, so it causes building of different set of tools that can be executed on the host platform. There should probably be a list of compatible platforms, that don't require such separation. I.e. `x64-windows` hosts support `x86-windows` configurations, but not vice versa.

**Comment by JackBoosY** [comment]
I think this issue is same with https://github.com/microsoft/vcpkg/issues/19027, please track that issue.
