### ISSUE TITLE
[ffmpeg] missing libraries create unresolved external symbols

### ISSUE THREAD

**Issue by morphogencc** [microsoft/vcpkg#17569]
**Host Environment**
- OS: Windows 10
- VS2019
- Built with x64-windows-static triplet

**To Reproduce**
`./vcpkg install ffmpeg`

Try to instantiate any classes from `avformat.lib`, `avcodec.lib`, or `avutils.lib`.  Immediately get a LNK2019 error "unresolved external symbol".  All functions and classes seem to trace back to missing Secur32.lib and Bcrypt.lib.

**Failure logs** 
```
avformat.lib(tls_schannel.o) : error LNK2019: unresolved external symbol AcquireCredentialsHandleA referenced in function tls_open
avformat.lib(tls_schannel.o) : error LNK2019: unresolved external symbol __imp_FreeCredentialsHandle referenced in function tls_close
avformat.lib(tls_schannel.o) : error LNK2019: unresolved external symbol InitializeSecurityContextA referenced in function tls_close
avformat.lib(tls_schannel.o) : error LNK2019: unresolved external symbol __imp_DeleteSecurityContext referenced in function tls_close
avformat.lib(tls_schannel.o) : error LNK2019: unresolved external symbol __imp_ApplyControlToken referenced in function tls_close
avformat.lib(tls_schannel.o) : error LNK2019: unresolved external symbol QueryContextAttributesA referenced in function tls_write
avformat.lib(tls_schannel.o) : error LNK2019: unresolved external symbol FreeContextBuffer referenced in function tls_close
avformat.lib(tls_schannel.o) : error LNK2019: unresolved external symbol EncryptMessage referenced in function tls_write
avformat.lib(tls_schannel.o) : error LNK2019: unresolved external symbol DecryptMessage referenced in function tls_read
avutil.lib(random_seed.o) : error LNK2019: unresolved external symbol BCryptOpenAlgorithmProvider referenced in function av_get_random_seed
avutil.lib(random_seed.o) : error LNK2019: unresolved external symbol BCryptCloseAlgorithmProvider referenced in function av_get_random_seed
avutil.lib(random_seed.o) : error LNK2019: unresolved external symbol BCryptGenRandom referenced in function av_get_random_seed
```
**Additional context**
I've tried using a few different build options -- `ffmpeg[openssl]`, `ffmpeg[all]`, `ffmpeg[all-nonfree]` did not solve the problem.

Searching for this issue I found a previous ticket about the problem, but no resolution: [here](https://github.com/microsoft/vcpkg/issues/9571)

**Comment by JackBoosY** [comment]
Is you vcpkg latest?

**Comment by Sibras** [comment]
Are you using cmake (and by association FindFFmpeg.cmake) to link against ffmpeg?
secur32 and bcrypt should be added by cmake as they are included in the above script
[https://github.com/microsoft/vcpkg/blob/6537078e8ae397e5fb959e839c79e86c836065c2/ports/ffmpeg/FindFFMPEG.cmake.in#L341](https://github.com/microsoft/vcpkg/blob/6537078e8ae397e5fb959e839c79e86c836065c2/ports/ffmpeg/FindFFMPEG.cmake.in#L341)

**Comment by morphogencc** [comment]
@Sibras I'm using the manifest system; I added a `vcpkg.json` to my project with:

```
	"dependencies": [
		{
			"name": "ffmpeg",
			"features": [
				"nvcodec"
			]
		}
	]
```

and I enabled "Use vcpkg" and "Using vcpkg manifest" in my project's VS2019 Configuration Properties.

**Comment by JackBoosY** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/9571, please track this issue in #9571.
