### ISSUE TITLE
[detours] Expose CMake package for this library

### ISSUE THREAD

**Issue by MichaelGoulding** [microsoft/vcpkg#17564]
It's unclear to me how to include this package from CMake as it doesn't appear to create or export a package.

**Comment by JackBoosY** [comment]
Please see [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/users/integration.md).

**Comment by MichaelGoulding** [comment]
Can the port be edited to export a CMake package like most other ports?

**Comment by JackBoosY** [comment]
Unfortunately, detours is generated by nmake, so we need to add `Finddetours.cmake` or `detours-config.cmake.in`.

**Comment by lowleveldesign** [comment]
In case, someone is also struggling with this problem, here is a port you may use: https://github.com/mbeckh/vcpkg-registry/tree/master/ports/detours (by Michael Beckh). Example command line:

```
vcpkg install detours --overlay-ports=c:/repos/vcpkg-registry/ports/detours --triplet=x86-windows
```

**Comment by Adela0814** [comment]
`detours` provide the usage now, please get the latest vcpkg.
