### ISSUE TITLE
icu build failure

### ISSUE THREAD

**Issue by MrAhmedSayedAli** [microsoft/vcpkg#17576]
**Host Environment**
- OS: windows10

**To Reproduce**
`./vcpkg install icu`

**Failure logs** 
vcpkg install icu
Computing installation plan...
The following packages will be built and installed:
    icu[core]:x86-windows -> 69.1#8
Detecting compiler hash for triplet x86-windows...
Could not locate cached archive: C:\Users\mrahm\AppData\Local\vcpkg\archives\5d\5d41ea0cb09f9e33daab280b0f9f5660255aa4fd.zip
Starting package 1/1: icu:x86-windows
Building package icu[core]:x86-windows...
-- Using cached F:/CPP/vcpkg/downloads/icu4c-69_1-src.tgz
-- Cleaning sources at F:/CPP/vcpkg/buildtrees/icu/src/c-69_1-src-78c1b28057.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source F:/CPP/vcpkg/downloads/icu4c-69_1-src.tgz
-- Applying patch F:/CPP/vcpkg/ports/icu/disable-escapestr-tool.patch
-- Applying patch F:/CPP/vcpkg/ports/icu/remove-MD-from-configure.patch
-- Applying patch F:/CPP/vcpkg/ports/icu/fix_parallel_build_on_windows.patch
-- Applying patch F:/CPP/vcpkg/ports/icu/fix-extra.patch
-- Using source at F:/CPP/vcpkg/buildtrees/icu/src/c-69_1-src-78c1b28057.clean
-- Using msys root at F:/CPP/vcpkg/downloads/tools/msys2/20befe66cf35bf25
-- Configuring x86-windows-rel
-- Configuring x86-windows-rel done
-- Configuring x86-windows-dbg
-- Configuring x86-windows-dbg done
-- Package x86-windows-rel
-- Restarting Build without parallelism because memory exceeded
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:146 (message):
    Command failed: F:/CPP/vcpkg/downloads/tools/msys2/20befe66cf35bf25/usr/bin/bash.exe --noprofile --norc -c "make -j 13"
    Working Directory: F:/CPP/vcpkg/buildtrees/icu/x86-windows-rel
    See logs for more information:
      F:\CPP\vcpkg\buildtrees\icu\make-build-x86-windows-rel-out.log
      F:\CPP\vcpkg\buildtrees\icu\make-build-x86-windows-rel-err.log
      F:\CPP\vcpkg\buildtrees\icu\make-build-x86-windows-rel-out-1.log
      F:\CPP\vcpkg\buildtrees\icu\make-build-x86-windows-rel-err-1.log

[make-build-x86-windows-rel-err.log](https://github.com/microsoft/vcpkg/files/6400680/make-build-x86-windows-rel-err.log)
[make-build-x86-windows-rel-err-1.log](https://github.com/microsoft/vcpkg/files/6400681/make-build-x86-windows-rel-err-1.log)
[make-build-x86-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/6400682/make-build-x86-windows-rel-out.log)
[make-build-x86-windows-rel-out-1.log](https://github.com/microsoft/vcpkg/files/6400683/make-build-x86-windows-rel-out-1.log)

Call Stack (most recent call first):
  ports/icu/portfile.cmake:164 (vcpkg_execute_build_process)
  scripts/ports.cmake:142 (include)

Error: Building package icu:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: icu:x86-windows
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

**Comment by autoantwort** [comment]
Maybe try to restart the computer (I mean it for real :D). `Restarting Build without parallelism because memory exceeded` Maybe the build crashed and now the file is locked and you get `LINK : fatal error LNK1104: cannot open file '..\..\bin\pkgdata.exe'`

**Comment by PhoebeHui** [comment]
@MrAhmedSayedAli, could you also check if bin\pkgdata.exe exist? I can't repro this issue locally.

**Comment by MrAhmedSayedAli** [comment]
@autoantwort same Error After Restart    - But Delete Content of downloads & buildtrees   . it work

**Comment by PhoebeHui** [comment]
@MrAhmedSayedAli, it may due to the linker ran out of memory during execution with parallelism, good to know it works for you now.
