### ISSUE TITLE
[New Port Request] LimeReport

### ISSUE THREAD

**Issue by embeddedmz** [microsoft/vcpkg#17572]
Library name: LimeReport

Library description: Report generator for Qt Framework

Source repository URL: https://github.com/fralx/LimeReport

Project homepage (if different from the source repository): https://limereport.ru/en/index.php

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
