### ISSUE TITLE
[New Port Request] libvlcpp

### ISSUE THREAD

**Issue by morphogencc** [microsoft/vcpkg#17570]
Library name: libvlcpp

Library description:  libvlcpp is a header-only, C++ bindings for the libvlc crossplatform multimedia API. It is an official binding over the VideoLAN libvlc library and can be used on many platforms.  libVLC is the core engine and the interface to the multimedia framework on which VLC media player is based.

libVLC is modularized into hundreds of plugins, which may be loaded at runtime. This architecture provides great flexibility to developers (both VLC devs and devs consuming the library). It allows developers to create a wide range of multimedia applications using the VLC features.

Source repository URL: https://code.videolan.org/videolan/libvlcpp

Project homepage (if different from the source repository): https://www.videolan.org/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by mathisloge** [comment]
https://code.videolan.org/videolan/vlc would be needed as a dependency.

**Comment by morphogencc** [comment]
@mathisloge Ah, you're right -- and actually, libvlc would meet my purposes just fine, and looks like it's header-only.  Should I go ahead and change the ticket for just libvlc or create a new one?

**Comment by mathisloge** [comment]
@morphogencc libvlc isn't header only. libvlcpp is header only. But libvlcpp depends on libvlc.

**Comment by mathisloge** [comment]
The ticket thus includes both Libs. And it isn't a big deal to add libvlcpp, but libvlc looks loke a bit more work (to get it right).

**Comment by morphogencc** [comment]
Is there any movement on this issue or information I can provide?

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
