### ISSUE TITLE
Problems installing libwebsockets:x86-windows

### ISSUE THREAD

**Issue by deciobarrosjr** [microsoft/vcpkg#17582]
```
Installing package zlib[core]:x86-windows... done
Elapsed time for package zlib:x86-windows: 232.9 ms
Starting package 4/4: libwebsockets:x86-windows
Building package libwebsockets[core]:x86-windows...
-- Using cached C:/src/vcpkg/downloads/warmcat-libwebsockets-736f0739ed8c75db0e29c7678b5a9194e957c347.tar.gz
-- Cleaning sources at C:/src/vcpkg/buildtrees/libwebsockets/src/94e957c347-0c9531b65b.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/src/vcpkg/downloads/warmcat-libwebsockets-736f0739ed8c75db0e29c7678b5a9194e957c347.tar.gz
-- Applying patch fix-dependency-libuv.patch
-- Applying patch fix-build-error.patch
-- Applying patch export-include-path.patch
-- Using source at C:/src/vcpkg/buildtrees/libwebsockets/src/94e957c347-0c9531b65b.clean
-- Found external ninja('1.10.2').
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
    Command failed: ninja -v
    Working Directory: C:/src/vcpkg/buildtrees/libwebsockets/x86-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\src\vcpkg\buildtrees\libwebsockets\config-x86-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:324 (vcpkg_execute_required_process)
  ports/libwebsockets/portfile.cmake:135 (vcpkg_configure_cmake)
  scripts/ports.cmake:142 (include)


Error: Building package libwebsockets:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libwebsockets:x86-windows
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

Additionally, attach any relevant sections from the log files above.
```

**Comment by autoantwort** [comment]
> C:\src\vcpkg\buildtrees\libwebsockets\config-x86-windows-out.log

> Additionally, attach any relevant sections from the log files above.

**Comment by NancyLi1013** [comment]
I can install it successfully on my machine:
```
Starting package 5/5: libwebsockets:x86-windows
Building package libwebsockets[core]:x86-windows...
-- Downloading https://github.com/warmcat/libwebsockets/archive/736f0739ed8c75db0e29c7678b5a9194e957c347.tar.gz -> warmcat-libwebsockets-736f0739ed8c75db0e29c7678b5a9194e957c347.tar.gz...
-- Extracting source F:/new/vcpkg/downloads/warmcat-libwebsockets-736f0739ed8c75db0e29c7678b5a9194e957c347.tar.gz
-- Applying patch fix-dependency-libuv.patch
-- Applying patch fix-build-error.patch
-- Applying patch export-include-path.patch
-- Using source at F:/new/vcpkg/buildtrees/libwebsockets/src/94e957c347-0c9531b65b
-- Found external ninja('1.10.2').
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Installing: F:/new/vcpkg/packages/libwebsockets_x86-windows/share/libwebsockets/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package libwebsockets[core]:x86-windows... done
Installing package libwebsockets[core]:x86-windows...
Installing package libwebsockets[core]:x86-windows... done
Elapsed time for package libwebsockets:x86-windows: 3.563 min

Total elapsed time: 4.538 min

The package libwebsockets:x86-windows provides CMake targets:

    find_package(libwebsockets CONFIG REQUIRED)
    target_link_libraries(main PRIVATE websockets_shared)
```
Please provide the error log as @autoantwort suggested above @deciobarrosjr.

**Comment by deciobarrosjr** [comment]
Following my config-x64-windows-out file. It´s working on my notebook but is not working on my desktop. Still trying to figurout what is the problem.

[1/2] cmd /c "cd .. && "C:/Program Files/CMake/bin/cmake.exe" "C:/src/vcpkg/buildtrees/libwebsockets/src/94e957c347-0c9531b65b.clean" "-DLWS_WITH_STATIC=0" "-DLWS_WITH_SHARED=1" "-DLWS_WITH_GENCRYPTO=ON" "-DLWS_WITH_TLS=ON" "-DLWS_WITH_BUNDLED_ZLIB=OFF" "-DLWS_WITHOUT_TESTAPPS=ON" "-DLWS_IPV6=ON" "-DLWS_WITH_HTTP2=ON" "-DLWS_WITH_HTTP_STREAM_COMPRESSION=ON" "-DLWS_WITH_LIBUV=ON" "-DCMAKE_MAKE_PROGRAM=C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/src/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v142" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/src/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_LINKER_FLAGS_RELEASE=" "-DVCPKG_LINKER_FLAGS_DEBUG=" "-DVCPKG_TARGET_ARCHITECTURE=x64" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=C:/src/vcpkg" "-D_VCPKG_INSTALLED_DIR=C:/src/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=C:/src/vcpkg/packages/libwebsockets_x64-windows""
FAILED: ../CMakeCache.txt 
cmd /c "cd .. && "C:/Program Files/CMake/bin/cmake.exe" "C:/src/vcpkg/buildtrees/libwebsockets/src/94e957c347-0c9531b65b.clean" "-DLWS_WITH_STATIC=0" "-DLWS_WITH_SHARED=1" "-DLWS_WITH_GENCRYPTO=ON" "-DLWS_WITH_TLS=ON" "-DLWS_WITH_BUNDLED_ZLIB=OFF" "-DLWS_WITHOUT_TESTAPPS=ON" "-DLWS_IPV6=ON" "-DLWS_WITH_HTTP2=ON" "-DLWS_WITH_HTTP_STREAM_COMPRESSION=ON" "-DLWS_WITH_LIBUV=ON" "-DCMAKE_MAKE_PROGRAM=C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/src/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v142" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/src/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_LINKER_FLAGS_RELEASE=" "-DVCPKG_LINKER_FLAGS_DEBUG=" "-DVCPKG_TARGET_ARCHITECTURE=x64" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=C:/src/vcpkg" "-D_VCPKG_INSTALLED_DIR=C:/src/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=C:/src/vcpkg/packages/libwebsockets_x64-windows""
-- The C compiler identification is MSVC 19.28.29914.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Compiled with LWS_WITH_DIR and LWS_WITH_LEJP_CONF
SMD requires pthreads
-- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.31.1.windows.1") 
Git commit hash: 2020.11-1-1165-g2f03bdc3f
-- CMAKE_TOOLCHAIN_FILE='C:/src/vcpkg/scripts/buildsystems/vcpkg.cmake'
CMake Error at C:/src/vcpkg/scripts/buildsystems/vcpkg.cmake:861 (_find_package):
  By not providing "Findpthreads_windows.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "pthreads_windows", but CMake did not find one.

  Could not find a package configuration file provided by "pthreads_windows"
  with any of the following names:

    pthreads_windowsConfig.cmake
    pthreads_windows-config.cmake

  Add the installation prefix of "pthreads_windows" to CMAKE_PREFIX_PATH or
  set "pthreads_windows_DIR" to a directory containing one of the above
  files.  If "pthreads_windows" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:426 (find_package)


-- Configuring incomplete, errors occurred!
See also "C:/src/vcpkg/buildtrees/libwebsockets/x64-windows-rel/CMakeFiles/CMakeOutput.log".
[2/2] cmd /c "cd ../../x64-windows-dbg && "C:/Program Files/CMake/bin/cmake.exe" "C:/src/vcpkg/buildtrees/libwebsockets/src/94e957c347-0c9531b65b.clean" "-DLWS_WITH_STATIC=0" "-DLWS_WITH_SHARED=1" "-DLWS_WITH_GENCRYPTO=ON" "-DLWS_WITH_TLS=ON" "-DLWS_WITH_BUNDLED_ZLIB=OFF" "-DLWS_WITHOUT_TESTAPPS=ON" "-DLWS_IPV6=ON" "-DLWS_WITH_HTTP2=ON" "-DLWS_WITH_HTTP_STREAM_COMPRESSION=ON" "-DLWS_WITH_LIBUV=ON" "-DCMAKE_MAKE_PROGRAM=C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/src/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v142" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/src/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_LINKER_FLAGS_RELEASE=" "-DVCPKG_LINKER_FLAGS_DEBUG=" "-DVCPKG_TARGET_ARCHITECTURE=x64" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=C:/src/vcpkg" "-D_VCPKG_INSTALLED_DIR=C:/src/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_INSTALL_PREFIX=C:/src/vcpkg/packages/libwebsockets_x64-windows/debug""
FAILED: ../../x64-windows-dbg/CMakeCache.txt 
cmd /c "cd ../../x64-windows-dbg && "C:/Program Files/CMake/bin/cmake.exe" "C:/src/vcpkg/buildtrees/libwebsockets/src/94e957c347-0c9531b65b.clean" "-DLWS_WITH_STATIC=0" "-DLWS_WITH_SHARED=1" "-DLWS_WITH_GENCRYPTO=ON" "-DLWS_WITH_TLS=ON" "-DLWS_WITH_BUNDLED_ZLIB=OFF" "-DLWS_WITHOUT_TESTAPPS=ON" "-DLWS_IPV6=ON" "-DLWS_WITH_HTTP2=ON" "-DLWS_WITH_HTTP_STREAM_COMPRESSION=ON" "-DLWS_WITH_LIBUV=ON" "-DCMAKE_MAKE_PROGRAM=C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/src/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v142" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/src/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_LINKER_FLAGS_RELEASE=" "-DVCPKG_LINKER_FLAGS_DEBUG=" "-DVCPKG_TARGET_ARCHITECTURE=x64" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=C:/src/vcpkg" "-D_VCPKG_INSTALLED_DIR=C:/src/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_INSTALL_PREFIX=C:/src/vcpkg/packages/libwebsockets_x64-windows/debug""
-- The C compiler identification is MSVC 19.28.29914.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Compiled with LWS_WITH_DIR and LWS_WITH_LEJP_CONF
SMD requires pthreads
-- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.31.1.windows.1") 
Git commit hash: 2020.11-1-1165-g2f03bdc3f
-- CMAKE_TOOLCHAIN_FILE='C:/src/vcpkg/scripts/buildsystems/vcpkg.cmake'
CMake Error at C:/src/vcpkg/scripts/buildsystems/vcpkg.cmake:861 (_find_package):
  By not providing "Findpthreads_windows.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "pthreads_windows", but CMake did not find one.

  Could not find a package configuration file provided by "pthreads_windows"
  with any of the following names:

    pthreads_windowsConfig.cmake
    pthreads_windows-config.cmake

  Add the installation prefix of "pthreads_windows" to CMAKE_PREFIX_PATH or
  set "pthreads_windows_DIR" to a directory containing one of the above
  files.  If "pthreads_windows" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:426 (find_package)


-- Configuring incomplete, errors occurred!
See also "C:/src/vcpkg/buildtrees/libwebsockets/x64-windows-dbg/CMakeFiles/CMakeOutput.log".
ninja: build stopped: subcommand failed.

**Comment by NancyLi1013** [comment]
Hi @deciobarrosjr 

Sorry for the long delay. Could you please try to remove `pthreads `to rebuild this? If still failed, please try to use `find_package(pthreads REQUIRED)` to rebuild.

https://github.com/microsoft/vcpkg/blob/8acb35e27fc52c183e8f450346a073ea1bbce888/ports/libwebsockets/fix-build-error.patch#L10

**Comment by JonLiu1993** [comment]
Thanks for posting this issue. This issue hasn’t been updated in four months. Please reopen this issue if this is still a problem for you.

**Comment by JackBoosY** [comment]
Ping for response.

**Comment by dg0yt** [comment]
> If still failed, please try to use `find_package(pthreads REQUIRED)` to rebuild.

FTR this cannot work. pthreads comes with a wrapper which is misimplemented as a Find module for the Pthreads4W prefix. It cannot properly interact with the `find_package` interface variables.

(I picked pthreads and libwebsockets into my vcpkg-cmake-validate test set. But this is work in progress. The pthreads wrapper is spread over three package names (but lacks `PThreads4W`!) and needs consolidation. libwebsockets needs adjustments for mingw.)

**Comment by JackBoosY** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.
