### ISSUE TITLE
[cgal] build failure

### ISSUE THREAD

**Issue by acgetchell** [microsoft/vcpkg#17584]
**Host Environment**
- OS: Windows
- Compiler: Visual Studio 2019 with clang-cl

**To Reproduce**
`./vcpkg install cgal:x64-windows`

**Failure logs** 
```
Building package yasm-tool[core]:x64-windows...
CMake Error at scripts/cmake/vcpkg_fail_port_install.cmake:97 (message):
  The yasm-tool port is only intended to be built for x86 Windows
  Architecture 'x64' not supported by yasm-tool!
Call Stack (most recent call first):
  ports/yasm-tool/portfile.cmake:1 (vcpkg_fail_port_install)
  scripts/ports.cmake:142 (include)
Error: Building package yasm-tool:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: yasm-tool:x64-windows
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e
```

**Additional context**

Some commit after 6537078e8 broke cgal:x64-windows. 

Here's a successful build 9 hours ago:

https://ci.appveyor.com/project/acgetchell/cdt-plusplus/builds/38937799

And here's a failed build using commit 6b4754924 4 hours ago:

https://ci.appveyor.com/project/acgetchell/cdt-plusplus#L317

`yasm-tool:x86-windows` is required in order to build CGAL on Windows. You can see that it builds here:

https://ci.appveyor.com/project/acgetchell/cdt-plusplus/builds/38942915#L302

Via the old cgal build:

https://ci.appveyor.com/project/acgetchell/cdt-plusplus/builds/38937799#L225

But now instead of `yasm-tool-helper:x64-windows`:

https://ci.appveyor.com/project/acgetchell/cdt-plusplus/builds/38937799#L1046

It tries to build `yasm-tool:x64-windows`, which fails.

https://ci.appveyor.com/project/acgetchell/cdt-plusplus/builds/38942915#L1140

Perhaps commit https://github.com/microsoft/vcpkg/commit/c6f8dbac62fe769fe754ed59f6101896c4902512 broke it?

**Comment by acgetchell** [comment]
Pinning vcpkg to https://github.com/microsoft/vcpkg/commit/56c0313c4b46eb3d25e62d27b3986ed2ac557902 (which is the commit before https://github.com/microsoft/vcpkg/commit/c6f8dbac62fe769fe754ed59f6101896c4902512) fixes the issue:

https://ci.appveyor.com/project/acgetchell/cdt-plusplus/builds/38944944

**Comment by acgetchell** [comment]
Confirmed. Pinning vcpkg to https://github.com/microsoft/vcpkg/commit/c6f8dbac62fe769fe754ed59f6101896c4902512  breaks cgal:x64-windows:

https://ci.appveyor.com/project/acgetchell/cdt-plusplus/builds/38945066#L1064

**Comment by acgetchell** [comment]
And reverting the commit fixes it again:

https://ci.appveyor.com/project/acgetchell/cdt-plusplus/builds/38945090

**Comment by JackBoosY** [comment]
cc @xandox

**Comment by JackBoosY** [comment]
Please track this issue in https://github.com/microsoft/vcpkg/issues/17627.
