### ISSUE TITLE
[raylib] update to 3.7

### ISSUE THREAD

**Issue by drako0812** [microsoft/vcpkg#17594]
Library name: raylib

New version number: 3.7

Release notes can be found at https://github.com/raysan5/raylib/releases/tag/3.7.0

**Comment by VincenzoLaSpesa** [comment]
I think there is a missing dependency in the description.
I tried to build it on a fresh linux and by following the:

`sudo apt install libgl1-mesa-dev libx11-dev libxcursor-dev libxinerama-dev libxrandr-dev`

I didn't manage, the right list of dependencies suggested on the project page is:

`sudo apt install libasound2-dev mesa-common-dev libx11-dev libxrandr-dev libxi-dev xorg-dev libgl1-mesa-dev libglu1-mesa-dev`

But i suppose that `libasound2-dev` can be omitted

**Comment by JonLiu1993** [comment]
@VincenzoLaSpesa ,Could you please open a issue about your question? We will investigate and resolve in a new issue, thanks
