### ISSUE TITLE
Add GLib

### ISSUE THREAD

**Issue by geraldcombs** [Microsoft/vcpkg#176]
Downloads: https://ftp.gnome.org/pub/GNOME/sources/glib/
Build instructions: https://wiki.gnome.org/Projects/GTK+/Win32/MSVCCompilationOfGTKStack#GLib

This requires Gettext, ZLib, libFFI, and optionally PCRE.

**Comment by barcharcraz** [comment]
For anyone taking this on I'd recommend writing a file that recreates what the VS solution does, instead of trying to upgrade the solution and then configure it.

(I hope to take this on soon, making Glib, Cairo, GTK, and family available easily to MSVC would be awesome)

**Comment by Orvid** [comment]
As an extra source of reference, there's also https://github.com/winlibs/glib which is what's used for compiling PHP on Windows.

**Comment by vlj** [comment]
Did anyone start a gettext port ?

**Comment by mikebmcl** [comment]
There is a gettext port though I haven't tried it out. I just submitted a pull request with pixman and cairo. The pieces needed to get Glib and GTK are coming together.
