### ISSUE TITLE
[New Port Request] QtAV

### ISSUE THREAD

**Issue by DougRogers** [microsoft/vcpkg#17602]
Library name: QtAV

Library description: QtAV is a multimedia playback library based on Qt and FFmpeg.

Source repository URL: https://github.com/wang-bin/QtAV

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included): Very useful video playback library.

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
