### ISSUE TITLE
[poco] build failure

### ISSUE THREAD

**Issue by yezenyounan** [microsoft/vcpkg#17600]
**Host Environment**
- OS: Ubuntu x64
- Compiler: gcc 9.3, clang v10.0.0-4ubuntu1
[install-arm64-android-dbg-out.log](https://github.com/microsoft/vcpkg/files/6408546/install-arm64-android-dbg-out.log)

**To Reproduce**
`./vcpkg install poco:arm64-android`

**Failure logs** 
Computing installation plan...
The following packages will be built and installed:
  * pcre[core]:arm64-android -> 8.44#8
    poco[core]:arm64-android -> 1.10.1#5
  * zlib[core]:arm64-android -> 1.2.11#10
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet arm64-android...
Could not locate cached archive: /home/xyz/.cache/vcpkg/archives/0f/0f0b2f4ca66459d394d84a5cdaa9296292554774.zip
Could not locate cached archive: /home/xyz/.cache/vcpkg/archives/db/dbc7a870bdf7e60268575609e72546b73018b093.zip
Could not locate cached archive: /home/xyz/.cache/vcpkg/archives/cf/cf1df4f53b879d2eff7fa7230e17e5f0d416cafd.zip
Starting package 1/3: pcre:arm64-android
Building package pcre[core]:arm64-android...
-- Using community triplet arm64-android. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: /home/xyz/vcpkg_arm/triplets/community/arm64-android.cmake
-- Using cached /home/xyz/vcpkg_arm/downloads/pcre-8.44.zip
-- Cleaning sources at /home/xyz/vcpkg_arm/buildtrees/pcre/src/pcre-8-5bdacbc1cb.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/xyz/vcpkg_arm/downloads/pcre-8.44.zip
-- Applying patch pcre-8.44_suppress_cmake_and_compiler_warnings-errors.patch
-- Applying patch export-cmake-targets.patch
-- Using source at /home/xyz/vcpkg_arm/buildtrees/pcre/src/pcre-8-5bdacbc1cb.clean
-- Configuring arm64-android-dbg
-- Configuring arm64-android-rel
-- Building arm64-android-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:146 (message):
    Command failed: /home/xyz/vcpkg_arm/downloads/tools/cmake-3.20.1-linux/cmake-3.20.1-linux-x86_64/bin/cmake --build . --config Debug --target install -- -v -j2
    Working Directory: /home/xyz/vcpkg_arm/buildtrees/pcre/arm64-android-dbg
    See logs for more information:
      /home/ngld-m-dev/xyz/buildtrees/pcre/install-arm64-android-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:105 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:45 (vcpkg_build_cmake)
  ports/pcre/portfile.cmake:55 (vcpkg_install_cmake)
  scripts/ports.cmake:142 (include)

Error: Building package pcre:arm64-android failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: pcre:arm64-android
  Vcpkg version: 2021-01-13-unknownhash

**Additional context**
Additional packages have installed successfully.

**Comment by JackBoosY** [comment]
Please provide failure log _/home/ngld-m-dev/xyz/buildtrees/pcre/install-arm64-android-dbg-out.log_.

Thanks.

**Comment by yezenyounan** [comment]
@JackBoosY There is a link to the log file under the Host Environment section.  But it's attached here too.
Thanks.
[install-arm64-android-dbg-out.log](https://github.com/microsoft/vcpkg/files/6416240/install-arm64-android-dbg-out.log)

**Comment by JackBoosY** [comment]
```
[48/75] /home/xyz/Android/Sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=aarch64-none-linux-android21 --gcc-toolchain=/home/xyz/Android/Sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/home/xyz/Android/Sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/sysroot -DHAVE_CONFIG_H -Dpcrecpp_EXPORTS -I. -I/home/xyz/vcpkg_arm/buildtrees/pcre/src/pcre-8-5bdacbc1cb.clean -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -frtti -fexceptions  -fPIC   -O0 -fno-limit-debug-info    -fPIC -MD -MT CMakeFiles/pcrecpp.dir/pcrecpp.cc.o -MF CMakeFiles/pcrecpp.dir/pcrecpp.cc.o.d -o CMakeFiles/pcrecpp.dir/pcrecpp.cc.o -c /home/xyz/vcpkg_arm/buildtrees/pcre/src/pcre-8-5bdacbc1cb.clean/pcrecpp.cc
FAILED: CMakeFiles/pcrecpp.dir/pcrecpp.cc.o 
/home/xyz/Android/Sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=aarch64-none-linux-android21 --gcc-toolchain=/home/xyz/Android/Sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/home/xyz/Android/Sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/sysroot -DHAVE_CONFIG_H -Dpcrecpp_EXPORTS -I. -I/home/xyz/vcpkg_arm/buildtrees/pcre/src/pcre-8-5bdacbc1cb.clean -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -frtti -fexceptions  -fPIC   -O0 -fno-limit-debug-info    -fPIC -MD -MT CMakeFiles/pcrecpp.dir/pcrecpp.cc.o -MF CMakeFiles/pcrecpp.dir/pcrecpp.cc.o.d -o CMakeFiles/pcrecpp.dir/pcrecpp.cc.o -c /home/xyz/vcpkg_arm/buildtrees/pcre/src/pcre-8-5bdacbc1cb.clean/pcrecpp.cc
/home/xyz/vcpkg_arm/buildtrees/pcre/src/pcre-8-5bdacbc1cb.clean/pcrecpp.cc:885:17: error: use of undeclared identifier 'strtoq'; did you mean 'strtol'?
  long long r = strtoq(str, &end, radix);
                ^~~~~~
                strtol
/home/xyz/Android/Sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/stdlib.h:91:6: note: 'strtol' declared here
long strtol(const char* __s, char** __end_ptr, int __base);
     ^
/home/xyz/vcpkg_arm/buildtrees/pcre/src/pcre-8-5bdacbc1cb.clean/pcrecpp.cc:917:26: error: use of undeclared identifier 'strtouq'; did you mean 'strtoul'?
  unsigned long long r = strtouq(str, &end, radix);
                         ^~~~~~~
                         strtoul
/home/xyz/Android/Sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/stdlib.h:93:15: note: 'strtoul' declared here
unsigned long strtoul(const char* __s, char** __end_ptr, int __base);
              ^
2 errors generated.
```
The upstream should suitable for android arch.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. This issue should be a upstream issue, upstream should suitable for android arch. And this issue hasn’t been updated more than 3 months, if it is still an issue, please reopen this issue.
