### ISSUE TITLE
[yasm-tool] build failure: Building package yasm-tool:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by ZiniuLu** [microsoft/vcpkg#17621]
**Host Environment**
- OS: Windows 10 Home
- Compiler: Windows PowerShell

**To Reproduce**
I've installed cgal via vcpkg on Mar. 28 and was going to update this library.
`git pull`  --> succeed
`vcpkg update` --> succeed
`vcpkg upgrade --no-dry-run` --> got this error when installing `cgal:x64-windows`

**Failure logs** 

> PS E:\Code\vcpkg> vcpkg install cgal:x64-windows
Computing installation plan...
The following packages will be built and installed:
    cgal[core]:x64-windows -> 5.2#3
>  * gmp[core]:x64-windows -> 6.2.1#5
>  * mpfr[core]:x64-windows -> 4.1.0
>  * yasm-tool[core]:x64-windows -> 2020-10-12
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\luzin\AppData\Local\vcpkg\archives\7e\7eca5bf29b570d95a5c12070c73fb98ce287c749.zip
Could not locate cached archive: C:\Users\luzin\AppData\Local\vcpkg\archives\86\8654405577114b7f9ed59ce7b0ecfdbac2fb73a6.zip
Could not locate cached archive: C:\Users\luzin\AppData\Local\vcpkg\archives\60\6099532fddccd770b8978b5e4cdcebe1fb2975f3.zip
Could not locate cached archive: C:\Users\luzin\AppData\Local\vcpkg\archives\2c\2c0d057e3d4d96ae9bd34991ef01eeab507c87cd.zip
Starting package 1/4: yasm-tool:x64-windows
Building package yasm-tool[core]:x64-windows...
CMake Error at scripts/cmake/vcpkg_fail_port_install.cmake:97 (message):
  The yasm-tool port is only intended to be built for x86 Windows

>  Architecture 'x64' not supported by yasm-tool!

>Call Stack (most recent call first):
  ports/yasm-tool/portfile.cmake:1 (vcpkg_fail_port_install)
  scripts/ports.cmake:142 (include)

>Error: Building package yasm-tool:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: yasm-tool:x64-windows
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

>Additionally, attach any relevant sections from the log files above.

**Additional context**
`vcpkg install yasm-tool:x86-windows` --> `already installed`
'vcpkg install yasm-tool-helper:x64-windows' --> `already installed`
`vcpkg install yasm-tool-helper:x86-windows` --> succeed
`vcpkg install yasm-tool:x64-windows` --> same error
`vcpkg install cgal:x64-windows` --> same error
retried these commands in Command Prompt --> same error

Actually the building of `CGAL` cannot pass even I have installed the `x86` version of `yasm-tool` manually.

**Question**
 Which log file should I attach?

**Comment by JackBoosY** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/17627.
