### ISSUE TITLE
[yasm-tool:x64-windows] build failure

### ISSUE THREAD

**Issue by CiaranGruber** [microsoft/vcpkg#17627]
**Host Environment**
- OS: Windows 10 Home Build 19042
- Compiler: revision

**To Reproduce**
`./vcpkg install yasm-tool:x64-windows`

**Failure logs** 
```
Starting package 1/1: yasm-tool:x64-windows
Building package yasm-tool[core]:x64-windows...
CMake Error at scripts/cmake/vcpkg_fail_port_install.cmake:97 (message):
  The yasm-tool port is only intended to be built for x86 Windows

  Architecture 'x64' not supported by yasm-tool!

Call Stack (most recent call first):
  ports/yasm-tool/portfile.cmake:1 (vcpkg_fail_port_install)
  scripts/ports.cmake:142 (include)


Error: Building package yasm-tool:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: yasm-tool:x64-windows
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e
```

**Additional context**
This error initially popped up when trying to install the _gmp_ package and so I attempted to install _yasm-tool:x64-windows_ to reproduce the error. Furthermore, attempting to install _yasm-tool:x86-windows_ yields no errors

**Comment by Jingqiao-Hu** [comment]
The same issue. When I try to install gmp:x64-windows, the vcpkg will try to install yasm-tool:x64-windows and fail. (and I have installed yasm-tool:x86-windows)

**Comment by JackBoosY** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/17584, but I prefer to track this issue here.

**Comment by JackBoosY** [comment]
cc @BillyONeal

**Comment by sfhacker** [comment]
Are we still having issues with yasm?
Our environment shows:

yasm -a help
Available yasm architectures:
    x86         x86 (IA-32 and derivatives), AMD64
    lc3b        LC-3b

**Comment by BillyONeal** [comment]
> Are we still having issues with yasm?

It is still very flaky. @strega-nil was working on changing it to use host ports in #16478
