### ISSUE TITLE
[apr[private-headers]] Missing headers like arch\win32\apr_arch_thread_mutex.h

### ISSUE THREAD

**Issue by saiejp** [microsoft/vcpkg#17626]
Is there a reason why headers like arch\win32\apr_arch_thread_mutex.h are not included in the package that is installed or is there an option that needs to be specified ? Surely it would make sense to include all header files from the arch\win32\ in the APR package in the vcpkg package ?

**Comment by NancyLi1013** [comment]
Hi @saiejp 

Thanks for posting this issue.

I checked `apr `source codes and found the following codes in CMakeLists.txt:
```

    IF(APR_INSTALL_PRIVATE_H)
  # Kludges for unexpected dependencies of httpd 2.x, not installed by default
  SET(APR_PRIVATE_H_FOR_HTTPD
    include/arch/win32/apr_arch_file_io.h
    include/arch/win32/apr_arch_misc.h
    include/arch/win32/apr_arch_utf8.h
    include/arch/win32/apr_private.h
    )
  INSTALL(FILES ${​​​​​APR_PRIVATE_H_FOR_HTTPD}​​​​​ DESTINATION include/arch/win32)
  INSTALL(FILES include/arch/apr_private_common.h DESTINATION include/arch)
ENDIF()

```
Since this is intended behavior in upstream, not in vcpkg. So it would be better to report this to upstream if you have the request.

**Comment by saiejp** [comment]
Thanks @NancyLi1013 

Understood. Apologies, I assumed it had to do with vcpkg. I'll raise this upstream as you suggest.

**Comment by NancyLi1013** [comment]
You can keep this issue open until there is a conclusion from upstream.

**Comment by saiejp** [comment]
OK. I'm signing up to the APR bugzilla to ask the question.

**Comment by Cheney-W** [comment]
Are there any conclusions or responses from upstream?

**Comment by jimwang118** [comment]
Check the latest upstream version, there is no installation process to add this header file.
