### ISSUE TITLE
Homebrew on Mac thinks it installs vcpkg 2020.11-1 but vcpkg itself reports version 2020.06.15-unknownhash

### ISSUE THREAD

**Issue by kuvaldini** [microsoft/vcpkg#17630]
**Describe the bug**
Homebrew on Mac thinks it installs vcpkg 2020.11-1 but vcpkg itself reports version 2020.06.15-unknownhash

**Environment**
- OS: MacOS Big Sur

**To Reproduce**
```
>>> brew upgrade vcpkg
Updating Homebrew...
Warning: vcpkg 2020.11-1 already installed
>>> vcpkg version
Vcpkg package management program version 2020.06.15-unknownhash

See LICENSE.txt for license information.
>>> > brew info vcpkg
vcpkg: stable 2020.11-1 (bottled), HEAD
C++ Library Manager
https://github.com/microsoft/vcpkg
/usr/local/Cellar/vcpkg/2020.11-1 (5,205 files, 10.6MB) *
  Poured from bottle on 2021-03-03 at 21:54:02
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/vcpkg.rb
License: MIT
==> Dependencies
Build: cmake ✔, ninja ✔
==> Options
--HEAD
        Install HEAD version
==> Analytics
install: 220 (30 days), 678 (90 days), 2,621 (365 days)
install-on-request: 220 (30 days), 680 (90 days), 2,616 (365 days)
build-error: 0 (30 days)
```

More details:
```
>>> which vcpkg
/usr/local/bin/vcpkg
>>> ll /usr/local/bin/vcpkg
/usr/local/bin/vcpkg -> ../Cellar/vcpkg/2020.11-1/bin/vcpkg
>>> /usr/local/Cellar/vcpkg/2020.11-1/bin/vcpkg version
Vcpkg package management program version 2020.06.15-unknownhash

See LICENSE.txt for license information.
```

**Expected behavior**
Versions MUST coinside, aren't they?

**Comment by JackBoosY** [comment]
cc @strega-nil

**Comment by luncliff** [comment]
With my experience, I think the message is for https://github.com/microsoft/vcpkg-tool now.  
It would be more informative if the command provides both the version of the tool itself(release of the `vcpkg-tool`) and port registry(commit of `vcpkg`?)

**Comment by strega-nil-ms** [comment]
This is mostly homebrew's problem; we don't support the brew installer, and don't recommend using it.

**Comment by kuvaldini** [comment]
@luncliff I have added another issue related to your idea. Thank you.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
