### ISSUE TITLE
[port libtorrent] CMake project generation error.

### ISSUE THREAD

**Issue by al-sabr** [microsoft/vcpkg#17638]
https://github.com/arvidn/libtorrent/issues/6178

**Comment by FranciscoPombal** [comment]
The vcpkg port currently only supports libtorrent 1.2.x, not 2.x, so you have to checkout the `RC_1_2` branch.

**Comment by al-sabr** [comment]
Used the 1.2 version of the library and it compiled.

**Comment by JonLiu1993** [comment]
Libtorrent have updated to 1.2.14, please update to the latest version and use port
