### ISSUE TITLE
How to disable debug build in header-only library in port file in vcpkg?

### ISSUE THREAD

**Issue by igormironchik** [microsoft/vcpkg#17658]
I want to port one my library to vcpkg. This library is header-only. I created `portfile.cmake`, everything is fine. But `vcpkg install <mylibname>` builds release and debug. I have to say, that this build process is for internal for library generator of C++ code. So I want to have build only in release mode. How can I make it?

This was the first question. And from it the second one is coming. This generator places in `bin` folder and I have an error like

```
There should be no bin\ directory in a static build...
```

How can I enable to have `bin` directory with generator for header-only library in vcpkg?

**Comment by NancyLi1013** [comment]
Hi @igormironchik 

Thanks for posting this issue.

- For build type, you can add `set(VCPKG_BUILD_TYPE release)` in the triplet that you need to build. Such as x86-windows or x64-windows
- For `bin ` folder, if you build static library, there is no `bin `directory. Since you build header-only library, there should be no any files generated in `bin `directory. I wonder why you want to enable `bin ` directory.

**Comment by igormironchik** [comment]
Hi @NancyLi1013 

Yes, I want to port in vcpkg header-only library, but this library provides build tool (generator of C++ code from declarative description of configuration file), and I want `bin` folder with this generator to be in the package.

Is it ok if portfile will explicitly set build type as release?

**Comment by NancyLi1013** [comment]
> Hi @NancyLi1013
> 
> Yes, I want to port in vcpkg header-only library, but this library provides build tool (generator of C++ code from declarative description of configuration file), and I want `bin` folder with this generator to be in the package.

You can move the executable files to `tools/${PORT} `instead of `bin `folder.
> Is it ok if portfile will explicitly set build type as release?

Yes, it's ok.

**Comment by dg0yt** [comment]
> You can move the executable files to `tools/${PORT} `instead of `bin `folder.

You may want to use [vcpkg_copy_tools](https://vcpkg.io/en/docs/maintainers/vcpkg_copy_tools.html).

**Comment by igormironchik** [comment]
Big thanks guys. You totally answered on my questions.
