### ISSUE TITLE
[libgnutls] Static use depends on -ldl, not carried in pc file

### ISSUE THREAD

**Issue by dg0yt** [microsoft/vcpkg#17650]
**Describe the bug**
While trying to update port libmicrohttpd, I stumbled over unresolved symbols when using static build of port libgnutls in config.log:

~~~
configure:24362: checking whether GnuTLS is usable
configure:24385: gcc -o conftest -I/home/kpa/Projekte/installed/x64-linux/debug/lib/pkgconfig/../../../include -fPIC -g -fno-strict-aliasing  -L/home/kpa/Projekte/installed/x64-linux/debug/lib  conftest.c  -L/home/kpa/Projekte/installed/x64-linux/debug/lib/pkgconfig/../../lib -lgnutls -pthread -ltspi -lgmp -latomic -lhogweed -lgmp -lnettle -ltasn1 -lidn2 >&5
/home/kpa/Projekte/installed/x64-linux/debug/lib/libgnutls.a(tpm.o): In function `check_init':
/home/kpa/Projekte/buildtrees/libgnutls/x64-linux-dbg/lib/.././../src/3.6.15-4050d06d46.clean/lib/tpm.c:123: undefined reference to `dlopen'
/home/kpa/Projekte/buildtrees/libgnutls/x64-linux-dbg/lib/.././../src/3.6.15-4050d06d46.clean/lib/tpm.c:129: undefined reference to `dlsym'
/home/kpa/Projekte/buildtrees/libgnutls/x64-linux-dbg/lib/.././../src/3.6.15-4050d06d46.clean/lib/tpm.c:129: undefined reference to `dlclose'
...
collect2: error: ld returned 1 exit status
...
configure:24397: result: no
configure:24407: WARNING: pkg-config reports that GnuTLS is present, but GnuTLS can't be used
~~~

I'm not sure if this is desired for the static build, or if it is just a bug in the `.pc` files.

**Environment**
- OS: linux
- Triplet: default (x64-linux)

**To Reproduce**
1. Add libgnutls dependency to libmicrohttpd
2. Add `--with-https` to OPTIONS for vcpkg_configure_make in libmicrohttpd portfile.
3. `./vcpkg install libmicrohttpd`
4. Inspect config.log

**Expected behavior**
No undefined references when consuming libgnutls via .pc files in a static build

**Comment by wrobelda** [comment]
I just tried the same under Ubuntu 18.04.5 LTS and getting:

```
configure:24362: checking whether GnuTLS is usable
configure:24385: gcc -o conftest -I/home/cromo/vcpkg/installed/x64-linux/debug/../include -fPIC -g -fno-strict-aliasing  -L/home/cromo/vcpkg/installed/x64-linux/d
ebug/lib  conftest.c  -L/home/cromo/vcpkg/installed/x64-linux/debug/lib -lgnutls -pthread -lgmp -latomic -lhogweed -lgmp -lnettle -ltasn1 -lidn2 >&5
configure:24385: $? = 0
configure:24387: result: yes
configure:24714: checking for gnutls_privkey_import_x509_raw()
configure:24743: gcc -o conftest -I/home/cromo/vcpkg/installed/x64-linux/debug/../include -fPIC -g -fno-strict-aliasing -I/home/cromo/vcpkg/installed/x64-linux/de
bug/../include  -L/home/cromo/vcpkg/installed/x64-linux/debug/lib -lgnutls -pthread -lgmp -latomic -lhogweed -lgmp -lnettle -ltasn1 -lidn2 -L/home/cromo/vcpkg/ins
talled/x64-linux/debug/lib  conftest.c  -L/home/cromo/vcpkg/installed/x64-linux/debug/lib -lgnutls -pthread -lgmp -latomic -lhogweed -lgmp -lnettle -ltasn1 -lidn2
 >&5
configure:24743: $? = 0
configure:24750: result: yes
```

**Comment by dg0yt** [comment]
@wrobelda Briefly, do you want to say you cannot reproduce the issue?

The build of gnutls might have enabled additional features based on system introspection. This would still be a port bug. Maybe we should compare stdout of configure before entering config.log.

**Comment by wrobelda** [comment]
@dg0yt yes, precisely – I cannot reproduce that behavior. Attaching my gnutls bulld logs.

[Archive.zip](https://github.com/microsoft/vcpkg/files/6527134/Archive.zip)

**Comment by dg0yt** [comment]
@wrobelda Thanks for sharing the logs. I could spot a difference, and it is already present in your comment: 
On my system, vcpkg port libgnutls carries `-ltspi` which is a system library discovered during libgnutls build. 

So this a bug in port libgnutls. There is no such port in vcpkg. I will prepare a PR to build libgnutls `--without-tpm`.
