### ISSUE TITLE
Confusion about `supports` field in `features`

### ISSUE THREAD

**Issue by dg0yt** [microsoft/vcpkg#17651]
Under the `"features"` and `"default-features"` headline, the [manifest documentation for users states](https://github.com/microsoft/vcpkg/blob/master/docs/users/manifests.md#features-and-default-features):
> There's also the `"supports"` field, which again acts exactly like the [`"supports"`](#supports) field on the global package.

https://github.com/microsoft/vcpkg/blame/master/docs/users/manifests.md#L228-L229

However, there is no such field in the schema:

https://github.com/microsoft/vcpkg/blob/95836f4883ffb481b7dd5f89569bc6ef55c31a7e/scripts/vcpkg.schema.json#L193-L215

And the vcpkg tool complains if you try to use it (here the attempt to use it for a new feature *in a port*, not in manifest mode):

~~~
$ ./vcpkg format-manifest ports/libmicrohttpd/vcpkg.json 
Failed to parse manifest file: /vcpkg/ports/libmicrohttpd/vcpkg.json
Errors occurred while parsing /vcpkg/ports/libmicrohttpd/vcpkg.json
    $.features.https (a feature): unexpected field 'supports', did you mean 'description'?
~~~

So what is the state of the `supports` field in ~dependencies~features?

**Comment by strega-nil-ms** [comment]
@dg0yt it was originally intended to be added, and we documented it as if it got in, but I think that PR never actually landed. As of right now it's a docs bug, although one which we do intend to implement as a feature in the future.

**Comment by mathisloge** [comment]
This would become more important since the PR review process will now include the feature testing. PR`s which does need this, would need a workaround as for example #19581

**Comment by autoantwort** [comment]
What should happen when a feature is a default one and has a support field that evaluates to false? I would say then the feature is silently dropped like a dependency with a `platform` field. But when I have a dependency to a feature that has a supports field that is evaluated to false that should be an error.

**Comment by mathisloge** [comment]
Sounds good to me. Maybe a warning of the dropped default feature should be printed. But a error of a indirect dependency is good.

Or it should be the policy, that default features should support all platforms.

**Comment by autoantwort** [comment]
> Or it should be the policy, that default features should support all platforms.

I think there are valid use cases where a feature should be the default, but it is not supported on every platform. 

Maybe we then need a new way to request features that are not supported on every platform, because 
```json
{
  "dependencies": [
    {
      "name": "foo",
      "default-features": false,
      "features": ["everywhere"]
    },
    {
      "name": "foo",
      "default-features": false,
      "features": ["only_windoes"],
      "platform": "windows"
    }
  ]
}
``` 
seems pretty verbose.  

Maybe 
```json
{
  "dependencies": [
    {
      "name": "foo",
      "default-features": false,
      "features": ["everywhere", {"name": "only_windoes", "platform: windows"}]
    }
  ]
}
``` 
or 
```json
{
  "dependencies": [
    {
      "name": "foo",
      "default-features": false,
      "features": ["everywhere", "only_windoes"],
      "ignore-unsupported-features": true
    }
  ]
}
```
The benefit of the second solution is that you don't have to repeat the `supports` field. And if the `supports` fields is updated you automatically also have the change, you don't have to update the `platform` field manually.

**Comment by autoantwort** [comment]
> default features should support all platforms.

In my PR it is now implemented that way. Maybe needs an option to disable the checks.
