### ISSUE TITLE
build librdkafka[ssl] error

### ISSUE THREAD

**Issue by chrisHasBeenTaken** [microsoft/vcpkg#17654]
When asking a question please also include where you looked for an answer (so we can update the documentation if needed).
C:\Dev\vcpkg>vcpkg.exe install librdkafka[ssl]
Computing installation plan...
The following packages will be built and installed:
    librdkafka[core,ssl]:x86-windows -> 1.5.0
Detecting compiler hash for triplet x86-windows...
Could not locate cached archive: C:\Users\Chris Chen\AppData\Local\vcpkg\archives\e1\e1aca0b1de60afbc096b9b10a38218a9cdbff793.zip
Starting package 1/1: librdkafka:x86-windows
Building package librdkafka[core,ssl]:x86-windows...
-- Using cached C:/Dev/vcpkg/downloads/edenhill-librdkafka-39796d359898c07ea422849e6d7cd34cd13ec466.tar.gz
-- Cleaning sources at C:/Dev/vcpkg/buildtrees/librdkafka/src/4cd13ec466-b5965b8a2a.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Dev/vcpkg/downloads/edenhill-librdkafka-39796d359898c07ea422849e6d7cd34cd13ec466.tar.gz
-- Applying patch fix-arm64.patch
-- Using source at C:/Dev/vcpkg/buildtrees/librdkafka/src/4cd13ec466-b5965b8a2a.clean
CMake Deprecation Warning at scripts/cmake/vcpkg_check_features.cmake:182 (message):
  calling `vcpkg_check_features` without the `FEATURES` keyword has been
  deprecated.

      Please add the `FEATURES` keyword to the call.
Call Stack (most recent call first):
  ports/librdkafka/portfile.cmake:13 (vcpkg_check_features)
  scripts/ports.cmake:142 (include)

-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:146 (message):
    Command failed: C:/Dev/vcpkg/downloads/tools/cmake-3.20.1-windows/cmake-3.20.1-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j13
    Working Directory: C:/Dev/vcpkg/buildtrees/librdkafka/x86-windows-dbg
    See logs for more information:
      C:\Dev\vcpkg\buildtrees\librdkafka\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:105 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:45 (vcpkg_build_cmake)
  ports/librdkafka/portfile.cmake:42 (vcpkg_install_cmake)
  scripts/ports.cmake:142 (include)

Error: Building package librdkafka:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: librdkafka:x86-windows
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

Additionally, attach any relevant sections from the log files above.

**Comment by PhoebeHui** [comment]
@chrisHasBeenTaken, could you please attach failure log 'C:\Dev\vcpkg\buildtrees\librdkafka\install-x86-windows-dbg-out.log'?

**Comment by PhoebeHui** [comment]
@chrisHasBeenTaken, please reopen this issue and provide us the failure logs if it still be a problem for you.
