### ISSUE TITLE
Is there plans of putting the xDevApi in vcpkg?

### ISSUE THREAD

**Issue by Alvaroalloc** [microsoft/vcpkg#17664]
### I use a lot the "new" connector of mysql with cpp, and i would like to have it in vcpkg, I think it is a very good library to put in.
Repo link: https://github.com/mysql/mysql-connector-cpp/

I don't put this in _**New port Category**_ because I've got no idea how to port this into the package manager

**Comment by JackBoosY** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/17674.
