### ISSUE TITLE
[] build failure boost-math package

### ISSUE THREAD

**Issue by qiuyudu** [microsoft/vcpkg#17660]
**Host Environment**
- OS: Windows
- Compiler: vc++

**To Reproduce**
By executing `./vcpkg install boost-asio:x86-windows` will a set of package installed, and only the boost-math has LNK1104 build Error.
however it work fine with `./vcpkg install boost-asio:x64-windows` 

But i could not understand why only the boost-math package has this failure with x86, while the other several tens of package can be build normally, and how could i also take deeper look into this problem and make the successful build for x86?

**Failure logs** 
[consoleOutput.txt](https://github.com/microsoft/vcpkg/files/6421546/consoleOutput.txt)
[build-x86-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/6421559/build-x86-windows-rel-out.log)

I noticed this issue are somehow similar to my problem:
https://github.com/microsoft/vcpkg/issues/16141
but that issue seems to be not actually solved.

would be thankful for any help about this problem!

**Comment by PhoebeHui** [comment]
@qiuyudu, thanks for reporting this issue, it looks same issue with https://github.com/microsoft/vcpkg/issues/16141, however, I still can't repro this issue locally. It may relate to the parallelism, if you only execute the command, it will generate the dll successfully, could you try the following steps and see if the problem persist?

1. Git clone https://github.com/microsoft/vcpkg 
2. Execute ./bootstrap-vcpkg.bat
3. Open ./ports/boost-modular-build-helper/boost-modular-build.cmake, line#170, change '${NUMBER_OF_PROCESSORS}' to 1.
 [boost-modular-build.cmake#L170](https://github.com/microsoft/vcpkg/blob/master/ports/boost-modular-build-helper/boost-modular-build.cmake#L170)
4. ./vcpkg install boost-math

Failures
```
msvc.link.dll C:\Projekt\OpenSources\vcpkg\buildtrees\boost-math\x86-windows-rel\boost\build\d74f77589f5a5baab084c0bf23014c62\boost_math_tr1f-vc142-mt-x32-1_75.dll
LINK : fatal error LNK1104: cannot open file 'C:\Projekt\OpenSources\vcpkg\buildtrees\boost-math\x86-windows-rel\boost\build\d74f77589f5a5baab084c0bf23014c62\boost_math_tr1f-vc142-mt-x32-1_75.dll'
```

**Comment by PhoebeHui** [comment]
@qiuyudu, does this still be a problem for you?

**Comment by qiuyudu** [comment]
@PhoebeHui Thanks for your contribution. Sorry for my late reply. 
I tried the steps you gave, the problem still perssist, but this time i noticed that my antivirus software Bitdenfender has removed the boost_math_tr1f-vc142-mt-x32-1_75.dll. I guess this must be the reason.

**Comment by PhoebeHui** [comment]
Yes, that's the common reason which may cause this issue, closing antivirus software should not block this port. thanks for your response!

**Comment by hackmaster0110** [comment]
I have the same issue. But I disabled bitdefender and rebuild. Still same issue.
