### ISSUE TITLE
[cgal] build failure

### ISSUE THREAD

**Issue by rolf-1** [microsoft/vcpkg#17667]
I want to build cgal (for use with openMVS) with x64-windows flag. Build of cgal failed due to a fail of building yasm-tool
I have tried three different approaches (described below), all three failed

**Host Environment**
- OS: Win 10, Pro Education N, Version 20H2
- Compiler: VisualStudio 2019, 16.9.4

**To Reproduce**
`./vcpkg install cgal[core]`

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

C:\xxx>.\vcpkg\vcpkg install cgal[core]  --triplet=x64-windows
Computing installation plan...
The following packages will be built and installed:
    cgal[core]:x64-windows -> 5.2#3
  * gmp[core]:x64-windows -> 6.2.1#5
  * mpfr[core]:x64-windows -> 4.1.0
  * yasm-tool[core]:x64-windows -> 2020-10-12
  * yasm-tool-helper[core]:x64-windows -> 2020-10-12
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\x\AppData\Local\vcpkg\archives\7e\7eca5bf29b570d95a5c12070c73fb98ce287c749.zip
Could not locate cached archive: C:\Users\x\AppData\Local\vcpkg\archives\83\83e930cc6b9659aaea1041aa5d7096ca1cef771d.zip
Could not locate cached archive: C:\Users\x\AppData\Local\vcpkg\archives\1f\1ff7de1bce0923739a2d9981c6cac25b5adade4f.zip
Could not locate cached archive: C:\Users\x\AppData\Local\vcpkg\archives\15\15b3316beef351dbca978e2be31b8412ca407fdf.zip
Could not locate cached archive: C:\Users\x\AppData\Local\vcpkg\archives\e3\e3328835afb3550d24306e7b8adbfc1a338071f6.zip
Starting package 1/5: yasm-tool:x64-windows
Building package yasm-tool[core]:x64-windows...
CMake Error at scripts/cmake/vcpkg_fail_port_install.cmake:97 (message):
  The yasm-tool port is only intended to be built for x86 Windows

  Architecture 'x64' not supported by yasm-tool!

Call Stack (most recent call first):
  ports/yasm-tool/portfile.cmake:1 (vcpkg_fail_port_install)
  scripts/ports.cmake:142 (include)

Error: Building package yasm-tool:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: yasm-tool:x64-windows
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

********************
Actually, I need cgal as X64 libs. Nevertheless, I have tried to build it as X86 libs with >.\vcpkg\vcpkg install cgal[core]  --triplet=x86-windows, but this doesn't work, too, since the build process try to build everything with x86-windows flag, but not yasm-tool. It is still tried to build it with x64-windows option.

C:\xxxx>.\vcpkg\vcpkg install cgal[core]  --triplet=x86-windows
Computing installation plan...
The following packages will be built and installed:
    cgal[core]:x86-windows -> 5.2#3
  * gmp[core]:x86-windows -> 6.2.1#5
  * mpfr[core]:x86-windows -> 4.1.0
  * yasm-tool[core]:x64-windows -> 2020-10-12
  * yasm-tool-helper[core]:x64-windows -> 2020-10-12
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Detecting compiler hash for triplet x86-windows...
Could not locate cached archive: C:\Users\x\AppData\Local\vcpkg\archives\7e\7eca5bf29b570d95a5c12070c73fb98ce287c749.zip
Could not locate cached archive: C:\Users\x\AppData\Local\vcpkg\archives\83\83e930cc6b9659aaea1041aa5d7096ca1cef771d.zip
Could not locate cached archive: C:\Users\x\AppData\Local\vcpkg\archives\37\3728e98d875591a2ba98f2decd743eed465d17cf.zip
Could not locate cached archive: C:\Users\x\AppData\Local\vcpkg\archives\c6\c6c506cb78e3f338db1fece3d04a6d1965dfd959.zip
Could not locate cached archive: C:\Users\x\AppData\Local\vcpkg\archives\a0\a09b941ef8faa03e7c0eb1242cf8e92c0b4d3229.zip
Starting package 1/5: yasm-tool:x64-windows
Building package yasm-tool[core]:x64-windows...
CMake Error at scripts/cmake/vcpkg_fail_port_install.cmake:97 (message):
  The yasm-tool port is only intended to be built for x86 Windows

  Architecture 'x64' not supported by yasm-tool!

Call Stack (most recent call first):
  ports/yasm-tool/portfile.cmake:1 (vcpkg_fail_port_install)
  scripts/ports.cmake:142 (include)

Error: Building package yasm-tool:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: yasm-tool:x64-windows
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

********
It is possible to build yasm-tool directly with x86-windows flag. But even, if this was done successfully. A new call of vcpkg install cgal[core] fails with the same error as described above.

....
Installing package yasm-tool[core]:x86-windows... done
Elapsed time for package yasm-tool:x86-windows: 82.4 ms

Total elapsed time: 3.597 s
C:\xxxx>.\vcpkg\vcpkg install cgal[core]  --triplet=x86-windows

Computing installation plan...
The following packages will be built and installed:
    cgal[core]:x86-windows -> 5.2#3
  * gmp[core]:x86-windows -> 6.2.1#5
  * mpfr[core]:x86-windows -> 4.1.0
  * yasm-tool[core]:x64-windows -> 2020-10-12
  * yasm-tool-helper[core]:x64-windows -> 2020-10-12
Additional packages (*) will be modified to complete this operation.
....
Building package yasm-tool[core]:x64-windows...
CMake Error at scripts/cmake/vcpkg_fail_port_install.cmake:97 (message):
  The yasm-tool port is only intended to be built for x86 Windows

  Architecture 'x64' not supported by yasm-tool!
.....

**Comment by SamuelJamesFisher** [comment]
Same issue with colmap

**Comment by mike-crabcat** [comment]
I've also been looking at this issue for the past day too.   One thing you can do is to remove the dependencies listed in ports/gmp/vcpkg.json and then just install these packages first: yasm-tool:x86-windows, vs-yasm:x64-windows, yasm-tool-helper:x64-windows (all of these arch. specifically!).  In my build I use a custom port folder for gmp with this change.
  
It seems like the dependency list doesn't support cross-arch. dependency which is currently required due to yasm issues.

I'm still working on mpfr issues on both windows and linux however...

**Comment by dg0yt** [comment]
IIUC the yasm-tool issue is tracked in  #17627, and there is a draft PR in #16478.

**Comment by rolf-1** [comment]
Thank you mike-crabat. Your proposal has solved my current problem.

Since I'm not familiar with vcpkg details (actually my first usage): 
What is the official update mechanism, e.g. dg0yt: "there is a draft PR in #16478"
in "#16478" there are "proofed changes". When will the changes (dealing with "#16478" and with "17667") officially be available?

**Comment by JackBoosY** [comment]
Duplicated to #17627,
