### ISSUE TITLE
[New Port Request] mysql-connector-cpp

### ISSUE THREAD

**Issue by pratikpc** [microsoft/vcpkg#17674]
Library name:
MySQL Connector/C++

Library description:
MySQL Connector/C++ is a MySQL database connector for C++. It lets you develop C++ and C applications that connect to MySQL Server.

Source repository URL:
https://github.com/mysql/mysql-connector-cpp

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
