### ISSUE TITLE
[boost] build failure 

### ISSUE THREAD

**Issue by Jokercheng** [microsoft/vcpkg#17677]
**Describe the bug**
Trying to install the boost-locale for window 64 bits, however, the downloaded file do not have the same hash content as program expected.

Already try the following methods:
1) Update to latest vcpkg version and using git pull
2) Download the file directly from git and put into downloads folder
3) Remove the downloads folder and re-run
4) Reinstall vcpkg

**Environment**
- OS: Window 10 Professional
- Compiler: Visual Studio Professional 2017 15.9.35

**To Reproduce**
1. ./vcpkg install boost-locale:x64-windows

**Failure logs** 
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:105 (message):

File does not have expected hash:

File path: [ C:/Users/kicheng/vcpkg/downloads/boostorg-build-boost-1.75.0.tar.gz ]
Expected hash: [ dc5784cdcc908591a8c8814dac32849fb00b5f5b2d48de963d51a0571fd9f5a0419d6bb569f3375bf8fbfae28d680db4ce869604667b717023e76869836534f4 ]
Actual hash: [ 925eb37d2e76d80cccfa537ae92f58bda7d8c0ee8bcd3c3da54199834af3fad62f59451405129be48fdf8f9a5e0f4532b9388e449b04ab0fecbfe9f6c4bb1270 ]

Please delete the file and retry if this file should be downloaded again.

Call Stack (most recent call first):
scripts/cmake/vcpkg_download_distfile.cmake:118 (test_hash)
scripts/cmake/vcpkg_from_github.cmake:147 (vcpkg_download_distfile)
ports/boost-build/portfile.cmake:9 (vcpkg_from_github)
scripts/ports.cmake:142 (include)

Error: Building package boost-build:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
Package: boost-build:x64-windows
Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

-[stdout-x64-windows.log](https://github.com/microsoft/vcpkg/files/6425955/stdout-x64-windows.log)

**Comment by PhoebeHui** [comment]
@Jokercheng, could you try the following steps and see if the issue persist?

1. Update to latest vcpkg version and using git pull
2. Download the file directly from https://github.com/boostorg/build/archive/boost-1.75.0.tar.gz
3. Rename it to boostorg-build-boost-1.75.0.tar.gz and put into downloads folder
4. ./vcpkg install boost-build;x64-windows
 
```
Starting package 15/57: boost-build:x64-windows
Building package boost-build[core]:x64-windows...
-- Downloading https://github.com/boostorg/build/archive/boost-1.75.0.tar.gz -> boostorg-build-boost-1.75.0.tar.gz...
-- Extracting source F:/vcpkg/src/downloads/boostorg-build-boost-1.75.0.tar.gz
-- Applying patch fix_options.patch
-- Using source at F:/vcpkg/src/buildtrees/boost-build/src/ost-1.75.0-a06f9834b9.clean
-- Using cached F:/vcpkg/src/downloads/boost_LICENSE_1_0.txt
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.75.0/boostcpp.jam -> boost-1.75.0-boostcpp.jam...
-- Installing: F:/vcpkg/src/packages/boost-build_x64-windows/share/boost-build/copyright
-- Bootstrapping...
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\phoebe\AppData\Local\vcpkg\archives\65\6586c10f3cf0cef2f7c0fc32272b4396b75d4718.zip
Building package boost-build[core]:x64-windows... done
Installing package boost-build[core]:x64-windows...
Installing package boost-build[core]:x64-windows... done
```

**Comment by Jokercheng** [comment]
Still have the same error.

Building package boost-build[core]:x64-windows...
-- Using cached C:/Users/kicheng/vcpkg/downloads/boostorg-build-boost-1.75.0.tar.gz
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:105 (message):


File does not have expected hash:

File path: [ C:/Users/kicheng/vcpkg/downloads/boostorg-build-boost-1.75.0.tar.gz ]
Expected hash: [ dc5784cdcc908591a8c8814dac32849fb00b5f5b2d48de963d51a0571fd9f5a0419d6bb569f3375bf8fbfae28d680db4ce869604667b717023e76869836534f4 ]
Actual hash: [ 925eb37d2e76d80cccfa537ae92f58bda7d8c0ee8bcd3c3da54199834af3fad62f59451405129be48fdf8f9a5e0f4532b9388e449b04ab0fecbfe9f6c4bb1270 ]

Please delete the file and retry if this file should be downloaded again.

Call Stack (most recent call first):
scripts/cmake/vcpkg_download_distfile.cmake:118 (test_hash)
scripts/cmake/vcpkg_from_github.cmake:147 (vcpkg_download_distfile)
ports/boost-build/portfile.cmake:9 (vcpkg_from_github)
scripts/ports.cmake:142 (include)


Error: Building package boost-build:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
Package: boost-build:x64-windows
Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

![image](https://user-images.githubusercontent.com/11346313/117277697-ad3f5800-ae92-11eb-998a-485335c9316d.png)

**Comment by PhoebeHui** [comment]
Could you use the following file and try again?
[boostorg-build-boost-1.75.0.tar.gz](https://github.com/microsoft/vcpkg/files/6433612/boostorg-build-boost-1.75.0.tar.gz)

**Comment by PhoebeHui** [comment]
@Jokercheng, does this still be a problem for you?

**Comment by Jokercheng** [comment]
Sry for the late reply, we find that it is because network traffic is blocked when file transfer.
Thanks for your kindly help.
