### ISSUE TITLE
Provide a vcpkg argument to list the dependency tree of a package

### ISSUE THREAD

**Issue by Firefly35** [microsoft/vcpkg#17678]
It would be useful to be able to get the full dependency tree for a package, in either a "flat" string list (such as brew does with brew deps [package_name]) or a "tree" view (such as brew does with brew deps --tree [package_name]).

**Comment by dg0yt** [comment]
Did you try `vcpkg depend-info`?
It even has a `--dot` option.

**Comment by JackBoosY** [comment]
Please use `./vcpkg depend-info ${PORT_NAME}` to show its dependency tree.

**Comment by Firefly35** [comment]
Thanks a lot, I don't know why I didn't figure it out while using the help.

**Comment by Firefly35** [comment]
The depend-info shows either forward or backward dependencies. I expected the command to provide only dependencies the ${PORT_NAME} relies on (for instance, vcpkg depend-info grpc shoud list protobuf, abseil and so on, but not the ports that depend on grpc). I need a command to get the ${PORT_NAME} dependencies list, not the list of the ports depending on ${PORT_NAME}

**Comment by dg0yt** [comment]
> for instance, vcpkg depend-info grpc shoud list protobuf, abseil and so on, but not the ports that depend on grpc

I don't see a single port which depends on grpc:
~~~
$ ./vcpkg depend-info grpc
abseil: 
c-ares: 
openssl: 
protobuf: 
re2: 
upb: 
zlib: 
grpc: abseil, c-ares, openssl, protobuf, re2, upb, zlib
~~~

**Comment by Firefly35** [comment]
I used the grpc port as an example of the feature I expect. I could have used boost-detail for instance.
"depend-info" on boost-filesystem provides the dependencies in reverse order, with each sub-dependencies having its own dependency line and with some dependencies appearing twice or more (see boost-vcpkg-helpers below) :
`./vcpkg depend-info boost-detail
boost-uninstall: 
boost-vcpkg-helpers: boost-uninstall
boost-compatibility: boost-vcpkg-helpers
boost-config: boost-compatibility, boost-vcpkg-helpers
boost-preprocessor: boost-vcpkg-helpers
boost-detail: boost-compatibility, boost-config, boost-preprocessor, boost-vcpkg-helpers
` 
I expect to have the full flat dependency list with each dependency appearing only once for the package i.e. (an argument -flat to depend-info should be a good option) :
`$ ./vcpkg depend-info -flat boost-detail
boost-compatibility, boost-config, boost-preprocessor, boost-vcpkg-helpers, boost-uninstall`

**Comment by dg0yt** [comment]
Not a `-flat` option, but:
~~~
$ ./vcpkg depend-info --max-recurse=0 boost-detail
boost-detail: boost-compatibility, boost-config, boost-preprocessor, boost-vcpkg-helpers
~~~

**Comment by dg0yt** [comment]
Also useful:

~~~
$./vcpkg install --dry-run boost-detail
Computing installation plan...
The following packages will be built and installed:
  * boost-compatibility[core]:x64-mingw-dynamic -> 1.75.0
  * boost-config[core]:x64-mingw-dynamic -> 1.75.0
    boost-detail[core]:x64-mingw-dynamic -> 1.75.0
  * boost-preprocessor[core]:x64-mingw-dynamic -> 1.75.0
  * boost-uninstall[core]:x64-mingw-dynamic -> 1.75.0
  * boost-vcpkg-helpers[core]:x64-mingw-dynamic -> 7#2
Additional packages (*) will be modified to complete this operation.
~~~

**Comment by dg0yt** [comment]
> `$./vcpkg install --dry-run boost-detail`

Or rather:

~~~
./vcpkg install --dry-run --x-install-root=/tmp/empty boost-detail
~~~

**Comment by PhoebeHui** [comment]
This issue should be fixed in latest release.
