### ISSUE TITLE
[New Port Request] Sleef 

### ISSUE THREAD

**Issue by Remotion** [microsoft/vcpkg#17681]
Library name:  Sleef 

Library description:  SIMD Library for Evaluating Elementary Functions, vectorized libm and DFT 

Source repository URL:  https://github.com/shibatch/sleef

Project homepage:   https://sleef.org/

**Comment by NancyLi1013** [comment]
Hi @Remotion 

`sleef `has been added to vcpkg now, please update to the latest vcpkg to use this port.

Thanks for adding this port @luncliff.
