### ISSUE TITLE
tls2-downlload.exe get error 0x00000057 behind http proxy

### ISSUE THREAD

**Issue by ChanthMiao** [microsoft/vcpkg#17688]
**Describe the bug**
scripts/bootstrap.ps1 failed, because tls2-downlload.exe get error 0x00000057 behind http proxy

**Environment**
- OS: windows 10 v10.0.19042.0
- shell: powershell 5.1.19041.906

**To Reproduce**
1. $Env:HTTP_PROXY=http://192.168.32.1:8080; $Env:HTTPS_PROXY=http://192.168.32.1:8080 # Setup http proxy
2. .\bootstrap-vcpkg.bat
2. See error

**Expected behavior**
Download vcpkg.exe successifully.

**Failure logs** 
![image](https://user-images.githubusercontent.com/39488343/117179370-a1598480-ae05-11eb-821a-680fb5d94b13.png)

**Additional context**
There is nothing wrong with my proxy. At my local branch, I modified the 'scripts/bootstrap.ps1' to replace tls2-download.exe with aria2c, which installed by scoop. Then, downloading successed.
![image](https://user-images.githubusercontent.com/39488343/117180260-96532400-ae06-11eb-82f6-8c82a2ba2354.png)

**Comment by ChanthMiao** [comment]
Can vcpkg allow windows powershell users to select their own download program, instead of tls2-download.exe.
Or, considering the tiny size of vcpkg.exe, just use powershell builtin function `Invoke-WebRequest`.

**Comment by BillyONeal** [comment]
> Can vcpkg allow windows powershell users to select their own download program, instead of tls2-download.exe?

Download programs tend to not have consistent interfaces; you can do the download indicated in the program output yourself if you wish though; that's all it does on Windows now.

> Or, considering the tiny size of vcpkg.exe, just use powershell builtin function `Invoke-WebRequest`.

That failed in testing due to the TLS 1.2 enforcement requirement (that's why we had to write our own tool to do it even though we're already running powershell).

**Comment by BillyONeal** [comment]
> That failed in testing due to the TLS 1.2 enforcement requirement (that's why we had to write our own tool to do it even though we're already running powershell).

(Come to think of it, it's possible that this failure was Windows version dependent; I know Win7 failed to download anything but on Win10 it might work.... that said, comments about 'we should handle proxies the same way' from https://github.com/microsoft/vcpkg-tool/pull/49 apply here)

**Comment by ras0219-msft** [comment]
Based on my inspection, we actually didn't ever ship the new version of tls-download:

```
PS C:\src\vcpkg> git log --oneline .\scripts\tls12-download.exe
3a588ab16 [vcpkg] Change scripts/tls12-download.exe mode from 100644 to 100755 (#16211) (#16212)
aa60b7efa [vcpkg] Download vcpkg.exe rather than building it in bootstrap on Windows. (#15474)
PS C:\src\vcpkg>
```

@ChanthMiao Could you try a few other things to help us check this issue?

```
$Env:HTTP_PROXY=http://192.168.32.1:8080
$Env:HTTPS_PROXY=http://192.168.32.1:8080
curl.exe https://github.com/microsoft/vcpkg-tool/releases/download/2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/vcpkg.exe --output vcpkg.exe
```

Second, could you try replacing `scripts/tls12-download.exe` with https://github.com/microsoft/vcpkg-tool/releases/download/2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/tls12-download.exe and then re-run bootstrap? This newer version has better support for Windows' built-in proxy settings, so it might work around our mishandling of the `XYZ_PROXY` environment variables.

**Comment by cnSchwarzer** [comment]
It might be my fault as I mangled tls12-download.exe in (https://github.com/microsoft/vcpkg-tool/pull/49). But we don't know your version. Could you provide your tls12-download.exe's SHA512?
Also, try 'git pull' to get version 2021-05-05 and try again.
@ras0219-msft Do you mean that the (https://github.com/microsoft/vcpkg-tool/pull/49)'s change doesn't compiled in the 05-05's build?

**Comment by ChanthMiao** [comment]
> Second, could you try replacing `scripts/tls12-download.exe` with https://github.com/microsoft/vcpkg-tool/releases/download/2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/tls12-download.exe and then re-run bootstrap? This newer version has better support for Windows' built-in proxy settings, so it might work around our mishandling of the `XYZ_PROXY` environment variables.

It works!
![image](https://user-images.githubusercontent.com/39488343/117527661-48097500-b000-11eb-9133-628c412fcf8e.png)

**Comment by ChanthMiao** [comment]
> It might be my fault as I modified tls12-download.exe in ([microsoft/vcpkg-tool#49](https://github.com/microsoft/vcpkg-tool/pull/49)). But we don't know your version. Could you provide your tls12-download.exe's SHA512?

SHA512: 2DD63ACB7B5C11E68AE1340ABC1A05CC794041D5B6FC54FD51048102C012AD68E8E733F88CDC8DDB8AB951E3303288FE1A62593E75F78619F31C807D4C3FF50C

> Also, try 'git pull' to get version 2021-05-05 and try again.

Already tried. It is the same.

**Comment by ChanthMiao** [comment]
> Download programs tend to not have consistent interfaces; you can do the download indicated in the program output yourself if you wish though; that's all it does on Windows now.

Well, the only thing we need to know it whether the downloading successed. That means, we may not need to handle program's output (disable output), since the exitcode is enough. For example, https://aria2.github.io/manual/en/html/aria2c.html#exit-status.

> That failed in testing due to the TLS 1.2 enforcement requirement (that's why we had to write our own tool to do it even though we're already running powershell).

It may be possible to handle it by `[System.Net.ServicePointManager]::SecurityProtocol = ([System.Net.ServicePointManager]::SecurityProtocol -bor [System.Net.SecurityProtocolType]::Tls12)`. I have no win7/8.1 machine, no able to test this.

**Comment by cnSchwarzer** [comment]
I have looked into this and found:
- The vcpkg doesn't currently shipping 2021-05-05 release's tls12-download.exe, so it has nothing to do with https://github.com/microsoft/vcpkg-tool/pull/49.
- Your proxy settings will be automatically detected in 2021-05-05 version if you use Global Proxy mode in your proxy software, and if the proxy setting page is like this:
![image](https://user-images.githubusercontent.com/29846655/117529398-f0700700-b009-11eb-881b-c2a6d41b41e1.png)
Then this IE Proxy Setting will be automatically used in both vcpkg.exe and tls12-download.exe. There's no need to manually setting `HTTP_PROXY` and `HTTPS_PROXY` now.

**Comment by ChanthMiao** [comment]
>   Then this IE Proxy Setting will be automatically used in both vcpkg.exe and tls12-download.exe. There's no need to manually setting `HTTP_PROXY` and `HTTPS_PROXY` now.

Thanks for your working. The new version tls2.download.exe works well. 
(I just prefer to use HTTP_PROXY` and `HTTPS_PROXY`  instead of global proxy setting.

**Comment by JackBoosY** [comment]
Solved.

**Comment by witty-one** [comment]
> **Describe the bug** scripts/bootstrap.ps1 failed, because tls2-downlload.exe get error 0x00000057 behind http proxy
> 
> **Environment**
> 
> * OS: windows 10 v10.0.19042.0
> * shell: powershell 5.1.19041.906
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. $Env:HTTP_PROXY=http://192.168.32.1:8080; $Env:HTTPS_PROXY=http://192.168.32.1:8080 # Setup http proxy
> 2. .\bootstrap-vcpkg.bat
> 3. See error
> 
> **Expected behavior** Download vcpkg.exe successifully.
> 
> **Failure logs** ![image](https://user-images.githubusercontent.com/39488343/117179370-a1598480-ae05-11eb-821a-680fb5d94b13.png)
> 
> **Additional context** There is nothing wrong with my proxy. At my local branch, I modified the 'scripts/bootstrap.ps1' to replace tls2-download.exe with aria2c, which installed by scoop. Then, downloading successed. ![image](https://user-images.githubusercontent.com/39488343/117180260-96532400-ae06-11eb-82f6-8c82a2ba2354.png)

Here in 2023 experiencing the same issue! Thank you for the aria2c solution!
