### ISSUE TITLE
[New Port Request] BearLibTerminal

### ISSUE THREAD

**Issue by bradJM** [microsoft/vcpkg#17693]
Library name: BearLibTerminal

Library description: BearLibTerminal provides a pseudoterminal window with a grid of character cells and a simple yet powerful API for flexible textual output and uncomplicated input processing.

Source repository URL: https://github.com/cfyzium/bearlibterminal

Project homepage (if different from the source repository): http://foo.wyrd.name/en:bearlibterminal

Anything else that is useful to know when adding (such as optional features the library may have that should be included): The repository owner is interested in getting the library into more package managers, but did suggest the build script may need some attention: https://github.com/cfyzium/bearlibterminal/issues/11#issuecomment-831765882

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
