### ISSUE TITLE
[libtorrent] How to proceed with future upgrades, given that at least two branches/version series are actively maintained?

### ISSUE THREAD

**Issue by FranciscoPombal** [microsoft/vcpkg#17694]
Asking because I could not find a clear answer to this in the versioning documentation or in the maintainer's guide.

I've been one of the main contributors for the libtorrent port as of late. I basically just did upgrades from the 1.2.x series. The last upgrade was to 1.2.13 plus a few commits ahead: https://github.com/microsoft/vcpkg/pull/17166. The 1.2.x series is still maintained, and in the near future, 1.2.14 should be released.

However, a while back, libtorrent 2.0.x was released. The most recent stable release is 2.0.3. Many people, including me, would like to include this more recent version in the vcpkg port. Still, we can't leave the people using 1.2.x out the cold. The problem is that we can't keep postponing the upgrade to 2.0.x as long as there are 1.2.x releases (which is potentially indefinitely, at least for the sake of argument). On the other hand, it would seem that as soon as the jump is made to 2.0.x, no more 1.2.x upgrades can be ported.

Versioning apparently provides a solution for this as long as it's OK to have "out-of-order" versions in the [versions file](https://github.com/microsoft/vcpkg/blob/master/versions/l-/libtorrent.json), for the case where the upgrade to 2.0.3 is contributed before the one to 1.2.14, for instance. The issue is that a certain baseline could end up with 2.0.3, and a later baseline with 1.2.14. That _probably_ works, even if it makes the versions file slightly harder to navigate. Is there a show stopper you can think of with this approach? I think it might break the `upgrade` command, and users won't expect that a more recent vcpkg commit could install a previous version of a library...

If the previous solution is not viable, is a separate port named, say, `libtorrent2` a viable option?

The 3rd and only other solution I can think of is to tell users on 1.2.x to just use the latest version that included the 1.2.x port and simply use the `--head` argument when installing, but I don't consider that a satisfactory solution.

Any help is appreciated.

**Comment by JackBoosY** [comment]
Please create a new port called "libtorrent2" and rename the current port to "libtorrent1", and then make "libtorrent" depend on "libtorrent2".

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
