### ISSUE TITLE
How do I add curl with openssl version 3 to vcpkg? 

### ISSUE THREAD

**Issue by ahrzeroday** [microsoft/vcpkg#17703]
Hello
Default version of openssl in vcpkg is 1.1.1k but i need openssl version 3 so

I have a question 
How can i add openssl version 3?

How can i add curl with ssl(openssl version 3)?

Thanks your help

**Comment by JackBoosY** [comment]
You should use overlay-port and versioning.
See documentations:
1. https://github.com/microsoft/vcpkg/blob/master/docs/specifications/ports-overlay.md
2. https://github.com/microsoft/vcpkg/blob/master/docs/specifications/versioning.md

**Comment by ahrzeroday** [comment]
I do but i give this error

CMake Error at ports/openssl/windows/portfile.cmake:170 (file):
  file INSTALL cannot find
  "C:/vcpkg/buildtrees/openssl/src/openssl-3-d5990ef489.clean/LICENSE": File
  exists.
Call Stack (most recent call first):
  ports/openssl/portfile.cmake:19 (include)
  scripts/ports.cmake:142 (include)


Error: Building package openssl:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openssl:x64-windows
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e
  
  How can i fix it?

**Comment by ahrzeroday** [comment]
thanks i fix this but i give new 3 error can you help me how can i fix it?



-- Installing: C:/vcpkg/packages/openssl_x64-windows/share/openssl/copyright
-- Installing: C:/vcpkg/packages/openssl_x64-windows/share/openssl/usage
-- Performing post-build validation

The following dlls were found in /lib or /debug/lib. Please move them to /bin or /debug/bin, respectively.

    C:/vcpkg/packages/openssl_x64-windows/lib/ossl-modules/legacy.dll


The following dlls were found in /lib or /debug/lib. Please move them to /bin or /debug/bin, respectively.

    C:/vcpkg/packages/openssl_x64-windows/debug/lib/ossl-modules/legacy.dll

There should be no empty directories in C:\vcpkg\packages\openssl_x64-windows
The following empty directories were found:

    C:/vcpkg/packages/openssl_x64-windows/debug/lib/engines-3
    C:/vcpkg/packages/openssl_x64-windows/lib/engines-3

If a directory should be populated but is not, this might indicate an error in the portfile.
If the directories are not needed and their creation cannot be disabled, use something like this in the portfile to remove them:

    file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/a/dir" "${CURRENT_PACKAGES_DIR}/some/other/dir")


Found 3 error(s). Please correct the portfile:
    C:\vcpkg\ports\openssl\portfile.cmake
-- Performing post-build validation done
Error: Building package openssl:x64-windows failed with: POST_BUILD_CHECKS_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openssl:x64-windows
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

Additionally, attach any relevant sections from the log files above.

**Comment by NancyLi1013** [comment]
```
The following dlls were found in /lib or /debug/lib. Please move them to /bin or /debug/bin, respectively.

C:/vcpkg/packages/openssl_x64-windows/lib/ossl-modules/legacy.dll
The following dlls were found in /lib or /debug/lib. Please move them to /bin or /debug/bin, respectively.

C:/vcpkg/packages/openssl_x64-windows/debug/lib/ossl-modules/legacy.dll
```
*.dll files should be in /bin or /debug/bin folder. So please move these files to /bin or /debug/bin folder.
```
file(RENAME "${CURRENT_PACKAGES_DIR}/lib/ossl-modules/legacy.dll" "${CURRENT_PACKAGES_DIR}/bin/ossl-modules/legacy.dll")

file(RENAME "${CURRENT_PACKAGES_DIR}/debug/lib/ossl-modules/legacy.dll" "${CURRENT_PACKAGES_DIR}/debug/bin/ossl-modules/legacy.dll")
```

```
The following empty directories were found:

C:/vcpkg/packages/openssl_x64-windows/debug/lib/engines-3
C:/vcpkg/packages/openssl_x64-windows/lib/engines-3
```
For this error, we can remove these directories if there are no any libs generated.
```
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/lib/engines_3")
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/lib/engines_3")

```

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
