### ISSUE TITLE
bzip2:x86-windows build failure

### ISSUE THREAD

**Issue by jorgemin99** [microsoft/vcpkg#17704]
**Host Environment**
- OS: Windows
- Compiler: 2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9

**To Reproduce**
`./vcpkg install pcl`

**Failure logs** 
Building package bzip2[core]:x86-windows...
-- Fetching https://sourceware.org/git/bzip2.git...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
    Command failed: "C:/Program Files/Git/cmd/git.exe" fetch https://sourceware.org/git/bzip2.git 75a94bea3918e612b879d6a11ca64b8689526147 --depth 1 -n
    Working Directory: C:/vcpkg/downloads/git-tmp
    Error code: 128
    See logs for more information:
      C:\vcpkg\buildtrees\bzip2\git-fetch-x86-windows-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_git.cmake:91 (vcpkg_execute_required_process)
  ports/bzip2/portfile.cmake:1 (vcpkg_from_git)
  scripts/ports.cmake:142 (include)

Error: Building package bzip2:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: bzip2:x86-windows
  Vcpkg version: 2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9

Additionally, attach any relevant sections from the log files above.

C:\vcpkg> .\vcpkg update
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.

C:\vcpkg>git pull
fatal: not a git repository (or any of the parent directories): .git
*********************************************************************************

[git-fetch-x86-windows-err.log](https://github.com/microsoft/vcpkg/files/6436803/git-fetch-x86-windows-err.log)

**Comment by JonLiu1993** [comment]
@jorgemin99 ,you can do so by setting HTTP_PROXY, and HTTPS_PROXY environment variables.

See "[Syncing with github](https://stackoverflow.com/questions/5377703/syncing-with-github/5378094#5378094)":
````
set HTTPS_PROXY=http://<login_internet>:<password_internet>@aproxy:aport
set HTTP_PROXY=http://<login_internet>:<password_internet>@aproxy:aport
set NO_PROXY=localhost,my.company
````

**Comment by JonLiu1993** [comment]
@jorgemin99 ,does this still be a problem for you?

**Comment by NancyLi1013** [comment]
`fatal: unable to access 'https://sourceware.org/git/bzip2.git/': Could not resolve host: sourceware.org`

Please make sure if you have access to https://sourceware.org/git/bzip2.git/.

Closing this issue for now for inactive thread. Please feel free to reopen this issue if it is still a problem for you.
