### ISSUE TITLE
Error: Building package boost-container:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by GrayMay** [microsoft/vcpkg#17713]
Starting package 1/132: boost-container:x64-windows
Building package boost-container[core]:x64-windows...
-- Using cached D:/Learn/vcpkg/downloads/boostorg-container-boost-1.75.0.tar.gz
-- Cleaning sources at D:/Learn/vcpkg/buildtrees/boost-container/src/ost-1.75.0-707de84ce8.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/Learn/vcpkg/downloads/boostorg-container-boost-1.75.0.tar.gz
-- Using source at D:/Learn/vcpkg/buildtrees/boost-container/src/ost-1.75.0-707de84ce8.clean
-- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
    Command failed: D:/Learn/StarEngine/vcpkg_installed/x64-windows/tools/boost-build/b2.exe --stagedir=D:/Learn/vcpkg/buildtrees/boost-container/x64-windows-rel/stage --build-dir=D:/Learn/vcpkg/buildtrees/boost-container/x64-windows-rel --user-config=D:/Learn/vcpkg/buildtrees/boost-container/x64-windows-rel/user-config.jam -j8 --debug-configuration --debug-building --debug-generators --disable-icu --ignore-site-config --hash -q -sZLIB_INCLUDE=D:/Learn/StarEngine/vcpkg_installed/x64-windows/include -sBZIP2_INCLUDE=D:/Learn/StarEngine/vcpkg_installed/x64-windows/include -sLZMA_INCLUDE=D:/Learn/StarEngine/vcpkg_installed/x64-windows/include -sZSTD_INCLUDE=D:/Learn/StarEngine/vcpkg_installed/x64-windows/include threading=multi threadapi=win32 runtime-link=shared link=shared address-model=64 architecture=x86 -sZLIB_BINARY=zlib -sZLIB_LIBPATH=D:/Learn/StarEngine/vcpkg_installed/x64-windows/lib -sBZIP2_BINARY=bz2 -sBZIP2_LIBPATH=D:/Learn/StarEngine/vcpkg_installed/x64-windows/lib -sLZMA_BINARY=lzma -sLZMA_LIBPATH=D:/Learn/StarEngine/vcpkg_installed/x64-windows/lib -sZSTD_BINARY=zstd -sZSTD_LIBPATH=D:/Learn/StarEngine/vcpkg_installed/x64-windows/lib variant=release debug-symbols=on
    Working Directory: D:/Learn/vcpkg/buildtrees/boost-container/src/ost-1.75.0-707de84ce8.clean/build
    Error code: 1
    See logs for more information:
      D:\Learn\vcpkg\buildtrees\boost-container\build-x64-windows-rel-out.log

Call Stack (most recent call first):
  D:/Learn/StarEngine/vcpkg_installed/x64-windows/share/boost-build/boost-modular-build.cmake:332 (vcpkg_execute_required_process)
  ports/boost-container/portfile.cmake:15 (boost_modular_build)
  scripts/ports.cmake:142 (include)

Error: Building package boost-container:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-container:x64-windows
  Vcpkg version: 2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9

**Comment by PhoebeHui** [comment]
@GrayMay, could you attach failure log 'D:\Learn\vcpkg\buildtrees\boost-container\build-x64-windows-rel-out.log'?

**Comment by GrayMay** [comment]
and the logs

...found 216 targets...
...updating 22 targets...
msvc.write-setup-script D:\Learn\vcpkg\buildtrees\boost-container\x64-windows-rel\boost\standalone\msvc\999faa3b40e90a2a5abbbc32b31cdb11\msvc-setup.bat
The system cannot find the path specified.

    type "C:\Users\查人\AppData\Local\Temp\jam3904f50d.000" > "D:\Learn\vcpkg\buildtrees\boost-container\x64-windows-rel\boost\standalone\msvc\999faa3b40e90a2a5abbbc32b31cdb11\msvc-setup.bat"

...failed msvc.write-setup-script D:\Learn\vcpkg\buildtrees\boost-container\x64-windows-rel\boost\standalone\msvc\999faa3b40e90a2a5abbbc32b31cdb11\msvc-setup.bat...
...removing D:\Learn\vcpkg\buildtrees\boost-container\x64-windows-rel\boost\standalone\msvc\999faa3b40e90a2a5abbbc32b31cdb11\msvc-setup.bat
...skipped <pD:\Learn\vcpkg\buildtrees\boost-container\x64-windows-rel\boost\build\f7648d467bd0eca359a8f1c09d34fcab>alloc_lib.obj for lack of <pD:\Learn\vcpkg\buildtrees\boost-container\x64-windows-rel\boost\standalone\msvc\999faa3b40e90a2a5abbbc32b31cdb11>msvc-setup.nup...

**Comment by PhoebeHui** [comment]
@GrayMay, the Chinese characters cause this issue, this is a boost b2/bjam bug, as a workaround, you may need create a account with English name instead.

Duplicated to https://github.com/microsoft/vcpkg/issues/15201
