### ISSUE TITLE
[gdal] does not support access to hdf5 files

### ISSUE THREAD

**Issue by xiaoke0O** [microsoft/vcpkg#17725]
****

**Is your feature request related to a problem? Please describe.**
Although hdf5 is a dependency of gdal, the compiled GDAL cannot read hdf5 files. And dependency_win.cmake and portfile.cmake in the ports/gdal folder do not define the path of the hdf5 library.

**Proposed solution**
Define the path of the hdf5 library in dependency_win.cmake and portfile.cmake in the ports/gdal folder.

**Additional context**
![gdalinfo not support hdf5](https://user-images.githubusercontent.com/46664191/117461955-b9094800-af80-11eb-9dc6-fb120c4e97db.png)

**Comment by xiaoke0O** [comment]
![gdalinfo not support hdf5file](https://user-images.githubusercontent.com/46664191/117466639-8877dd00-af85-11eb-8303-6a3ecd741043.png)

**Comment by JackBoosY** [comment]
Can you please move the h5 file to other disk and try again?

Thanks.

**Comment by xiaoke0O** [comment]
> Can you please move the h5 file to other disk and try again?
> 
> Thanks.


I moved the h5 file to the F drive, but gdalinfo still cannot access the h5 file. I think this has nothing to do with the location of the h5 file, but is related to whether the compiled gdal has the function of accessing the hdf5 file enabled. I found that there is no related configuration information of hdf5 in the [dependency_win.cmake](https://github.com/microsoft/vcpkg/blob/master/ports/gdal/dependency_win.cmake) and [portfile.cmake](https://github.com/microsoft/vcpkg/blob/master/ports/gdal/portfile.cmake) of gdal, which leads to the compiled gdal does not have the function of accessing hdf5 files (maybe this is the cause of the problem?). Can you use gdal compiled by vcpkg to access hdf5 files?

我将h5文件移动到了F盘，但是gdalinfo 依然不能访问h5文件。我想这和h5文件所在位置无关，而与编译的gdal是否开启了hdf5功能有关。我发现在gdal的[dependency_win.cmake](https://github.com/microsoft/vcpkg/blob/master/ports/gdal/dependency_win.cmake)和[portfile.cmake](https://github.com/microsoft/vcpkg/blob/master/ports/gdal/portfile.cmake)中并没有hdf5的相关配置信息，这导致编译好的gdal没有访问hdf5文件的功能（可能这是问题的原因？）。你可以使用通过vcpkg编译的gdal访问hdf5文件吗？

![gdalinfo not support hdf5file_2](https://user-images.githubusercontent.com/46664191/117540741-24b3e980-b043-11eb-9e13-fda2e07aa005.png)

**Comment by xiaoke0O** [comment]
I submitted a pull request(#17753 ) to solve the problem that GDAL does not support hdf5 files. Below are my test results.

我提交了一个拉取请求(#17753)，解决了GDAL不支持hdf5文件的问题。下面是我的测试结果。

![gdalinfo support hdf5](https://user-images.githubusercontent.com/46664191/117560777-5076b400-b0c3-11eb-8047-9a3711ab2feb.png)
![gdalinfo support hdf5-2](https://user-images.githubusercontent.com/46664191/117560779-51a7e100-b0c3-11eb-919a-c49be87eaada.png)

**Comment by dg0yt** [comment]
Is this issue still valid? Port gdal was switched to a CMake build system with 3.5.0.

**Comment by JackBoosY** [comment]
> Is this issue still valid? Port gdal was switched to a CMake build system with 3.5.0.

I will checkout this later.

**Comment by dg0yt** [comment]
Is this issue still valid? Port gdal was switched to a CMake build system with 3.5.0.
