### ISSUE TITLE
vcpkg install (manifest mode) fails: "vcvarsall.bat failed with exit code 255"

### ISSUE THREAD

**Issue by zvilius** [microsoft/vcpkg#17730]
**Describe the bug**
Run "vcpkg install" in a project directory with a vcpkg.json (manifest mode): fails with "Run vcvarsall.bat to get Visual Studio env failed with exit code 255"

**Environment**
- OS: Windows 10 build 19042.928
- Compiler: Visual Studio 2019 16.10.0 Preview 2.1
- Using msbuild

**To Reproduce**
1. ./vcpkg install
2. See failure log below

**Expected behavior**
Successful installation of packages in my vcpkg.json manifest.

**Failure logs** 
C:\Users\Zest\projects\xxx [master ≡]> ../vcpkg/vcpkg install --debug
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] BuiltinRegistry initialized with: ""
[DEBUG] Using vcpkg-root: C:\Users\Zest\projects\vcpkg
[DEBUG] Using manifest-root: C:\Users\Zest\projects\xxx
[DEBUG] Using vcpkg_installed-root: C:\Users\Zest\projects\xxx\vcpkg_installed
[DEBUG] BuiltinRegistry initialized with: ""
[DEBUG] Using buildtrees-root: C:\Users\Zest\projects\vcpkg\buildtrees
[DEBUG] Using downloads-root: C:\Users\Zest\projects\vcpkg\downloads
[DEBUG] Using packages-root: C:\Users\Zest\projects\vcpkg\packages
[DEBUG] Using scripts-root: C:\Users\Zest\projects\vcpkg\scripts
[DEBUG] Using ports-root: C:\Users\Zest\projects\vcpkg\ports
[DEBUG] Using versions-root: C:\Users\Zest\projects\vcpkg\versions
[DEBUG] Default binary cache path is: C:\Users\Zest\AppData\Local\vcpkg\archives
[DEBUG] Using overlay: C:\Users\Zest\projects\xxx
[DEBUG] CreateProcessW("C:\Users\Zest\projects\vcpkg\downloads\tools\cmake-3.20.1-windows\cmake-3.20.1-windows-i386\bin\cmake.exe" --version)
[DEBUG] cmd_execute_and_stream_data() returned 0 after    65458 us
[DEBUG] CreateProcessW("C:\Users\Zest\projects\vcpkg\downloads\tools\cmake-3.20.1-windows\cmake-3.20.1-windows-i386\bin\cmake.exe" -DVCPKG_ROOT_DIR=C:/Users/Zest/projects/vcpkg -DPACKAGES_DIR=C:/Users/Zest/projects/vcpkg/packages -DBUILDTREES_DIR=C:/Users/Zest/projects/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=C:/Users/Zest/projects/xxx/vcpkg_installed -DDOWNLOADS=C:/Users/Zest/projects/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "C:\Users\Zest\projects\vcpkg\buildtrees\0.vcpkg_dep_info.cmake")
[DEBUG] cmd_execute_and_stream_data() returned 0 after    36665 us
[DEBUG] Using overlay: C:\Users\Zest\projects\xxx
[DEBUG] CreateProcessW("C:\Users\Zest\projects\vcpkg\downloads\tools\cmake-3.20.1-windows\cmake-3.20.1-windows-i386\bin\cmake.exe" -DVCPKG_ROOT_DIR=C:/Users/Zest/projects/vcpkg -DPACKAGES_DIR=C:/Users/Zest/projects/vcpkg/packages -DBUILDTREES_DIR=C:/Users/Zest/projects/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=C:/Users/Zest/projects/xxx/vcpkg_installed -DDOWNLOADS=C:/Users/Zest/projects/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "C:\Users\Zest\projects\vcpkg\buildtrees\0.vcpkg_tags.cmake")
[DEBUG] cmd_execute_and_stream_data() returned 0 after    42896 us
[DEBUG] CreateProcessW("C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -all -prerelease -legacy -products * -format xml)
[DEBUG] cmd_execute_and_stream_data() returned 0 after    35562 us
Detecting compiler hash for triplet x64-windows...
[DEBUG] Found path: C:\Program Files\Git\cmd\git.exe
[DEBUG] CreateProcessW("C:\Program Files\Git\cmd\git.exe" --version)
[DEBUG] cmd_execute_and_stream_data() returned 0 after    33362 us
[DEBUG] Found path: C:\Program Files\PowerShell\7\pwsh.exe
[DEBUG] CreateProcessW("C:\Program Files\PowerShell\7\pwsh.exe" --version)
[DEBUG] cmd_execute_and_stream_data() returned 0 after   297144 us
[DEBUG] CreateProcessW(cmd /c "C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Auxiliary\Build\vcvarsall.bat" -vcvars_ver=14.2 amd64   2>&1 <NUL  & echo cdARN4xjKueKScMy9C6H & set)
[DEBUG] cmd_execute_and_stream_data() returned 255 after  1351111 us
**Run vcvarsall.bat to get Visual Studio env failed with exit code 255**
[DEBUG] C:\A\1\121\s\src\vcpkg\base\system.process.cpp(594)
[DEBUG] Exiting after 1950341 us (1950143 us)

**Additional context**
Trying to run the command by hand I get the following:
\> vcvarsall.bat -vcvars_ver="14.2" amd64
\**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.10.0-pre.2.1
** Copyright (c) 2021 Microsoft Corporation
\**********************************************************************
**: was unexpected at this time.**

**Comment by pratikpc** [comment]
Are you on VS 2019 Preview?

Does this file exist?
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Auxiliary\Build\vcvarsall.bat

**Comment by NancyLi1013** [comment]
Since this is a bug in Visual Studio 2019 and it will be fixed in VS2019 16.10 Preview 3. By the way, you can modify your local file as below to fix this issue.

![Capture](https://user-images.githubusercontent.com/46708020/117529746-e7803500-b00b-11eb-81c7-e255ed38a377.PNG)

**Comment by zvilius** [comment]
Thank you, Nancy. That modset resolved the issue for me.

**Comment by jeanga** [comment]
I hit this issue today.
To be honest, I find this kind of error blocking the entire toolchain in a bat file pretty lame in 2021....
Other lnguages/toolchains don't have this kind of lame errors.

**Comment by NancyLi1013** [comment]
This issue has been reported here https://developercommunity.visualstudio.com/t/vcvarsallbat-now-fails-if--vcvars_ver-i/1400395 and fixed in Visual Studio 2019 version 16.10 Preview 3. Please wait for the new version released.
