### ISSUE TITLE
How do I configure "Additional Library Directories" for Static Library project in Visual Studio

### ISSUE THREAD

**Issue by Brouilles** [microsoft/vcpkg#17732]
Hi,
I have a Static Library project with "Additional Dependencies" setup in the **Librarian/General** menu in VS of the project.
But I need to setup manually the path to the lib folder `C:\dev\vcpkg\installed\x64-windows\debug\lib`. Else, I have a `cannot open input file *.lib`. I think I have missed a step.

I'm on Windows with Visual Studio 2019. `.\vcpkg\vcpkg integrate install` is setup and working fine with a .exe project and dependencies setup in the Linker. My problem is only on Static Library.

My dependencies
```
winmm.lib
pdh.lib
d3d11.lib
dxgi.lib
d3dcompiler.lib
DirectXTex.lib
d2d1.lib
dwrite.lib
Ws2_32.lib
xaudio2.lib
mfreadwrite.lib
mfplat.lib
mfuuid.lib
rpcrt4.lib
assimp-vc142-mtd.lib
PhysX_64.lib
PhysXCommon_64.lib
PhysXFoundation_64.lib
```

Working when I specified manually the **Additional Library Directories**. But I am not a big fan of hard path.
![image](https://user-images.githubusercontent.com/1573282/117529289-129c6180-afd7-11eb-9b79-6daea2ea399e.png)

Not Working. Link error.
![image](https://user-images.githubusercontent.com/1573282/117529318-3f507900-afd7-11eb-8af7-04ff4a58615e.png)

**Comment by Brouilles** [comment]
Seems good with `$(VcpkgInstalledDir)$(VcpkgTriplet)\$(VcpkgConfigSubdir)lib` for the **Additional Library Directories**.
It's the solution?

Thanks.

**Comment by JackBoosY** [comment]
Can you please run `./vcpkg integrate project` then retry?

Thanks.

**Comment by NancyLi1013** [comment]
Could you please try to set `Use Static Libraries` as `Yes `to rebuild your project? @Brouilles 
![image](https://user-images.githubusercontent.com/46708020/121330425-989a2800-c948-11eb-8a90-140c65b0b2ca.png)

**Comment by Brouilles** [comment]
I have updated vcpkg and it's working now. 
Thanks.
