### ISSUE TITLE
wxwidgets installation error on macOS

### ISSUE THREAD

**Issue by mig-29fulcrum** [microsoft/vcpkg#17744]
**Describe the bug**
I am trying to install the wxwidgets package on my mac, but the build fails. I am unable to get the package

**Environment**
- OS: Mac OS M1
- Compiler: Visual studio code

**To Reproduce**
1. ./vcpkg install wxwidgets

Repro code when

**Expected behavior**

**Failure logs** 
-Package: expat:arm64-osx
 -Vcpkg version: 2021-05-05-unknownhash

**Additional context**

**Comment by autoantwort** [comment]
Please provide the failure logs

**Comment by JackBoosY** [comment]
Both `wxwidgets:x64-osx` and `wxwidgets:arm64-osx` can be built succesfully, please provide the output in console and provide the mentioned logs.

**Comment by JackBoosY** [comment]
@mig-29fulcrum  Is this issue resolved?
You should install pkg-config first.

**Comment by mig-29fulcrum** [comment]
Hi Jack, 
Yes indeed, I am able to install the widget after adding the vsc package. 

thanks
