### ISSUE TITLE
[New Port Request] ut

### ISSUE THREAD

**Issue by cjdb** [microsoft/vcpkg#17757]
Library name: UT / μt

Library description: C++ single header/single module, macro-free μ(micro)/Unit Testing Framework

Source repository URL: https://github.com/boost-ext/ut

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by autoantwort** [comment]
It was already added in #16822?

**Comment by cjdb** [comment]
Thanks!
