### ISSUE TITLE
[Skia] Bump Version

### ISSUE THREAD

**Issue by lukedan** [microsoft/vcpkg#17758]
**Is your feature request related to a problem? Please describe.**
The current port of Skia uses a version of source code from ~~2017~~ EDIT: 2020. The old version has different API and missing functionality compared to the latest version (EDIT: Such as `GrDirectContext` and `SkSamplingOptions`).

**Proposed solution**
Add new versions of Skia to the library. Since vcpkg already has the mechanism for dealing with package versions this should be relatively easy.

**Describe alternatives you've considered**
Use a new package name (e.g., skia-m91). This is more of a last resort.

**Comment by lukedan** [comment]
This would also require updating `gn`. I have no idea what would be the proper way to do this, but simply replacing the executable in `tools/gn/` seems to work. (Besides updating the portfile, of course.)

Some other issues with the code:

1. In `scripts/cmake/vcpkg_install_gn.cmake`, in function `z_vcpkg_install_gn_install` around line 84, the `for` loop iterates over the variable `OUTPUTS`, but the variable name should be `outputs`, lower case.
2. `skiaConfig.cmake.in` does not define macros for RelWithDebInfo.

**Comment by lukedan** [comment]
(Also, `gn desc` just straight up gives you a list of macros to define. Why would you want to set that list yourself?)

**Comment by JonLiu1993** [comment]
@lukedan ，Thanks for your suggestion. Can you submit a pr to help solve this issue?

**Comment by lukedan** [comment]
@JonLiu1993 As I've said - I don't know how to properly update `gn`. I can certainly give it a shot if you point me to some documentation/examples of updating tools, but since it's the beginning of the week it's gonna take a while before I can get to it.

**Comment by JonLiu1993** [comment]
@lukedan ，I understand, then I will refer to your suggestion and submit a pr to update it

**Comment by JonLiu1993** [comment]
Fixed by #24066
