### ISSUE TITLE
Build failed on cpprestsdk x86-windows

### ISSUE THREAD

**Issue by DT777** [Microsoft/vcpkg#1775]
I'm running Windows 7 
  Package: cpprestsdk:x86-windows
  Vcpkg version: 0.0.85-unknownhash
Using command :vcpkg install cpprestsdk cpprestsdk:x64-windows

Error: Building package cpprestsdk:x86-windows failed with: BUILD_FAILED
Log attached
[log_extract.txt](https://github.com/Microsoft/vcpkg/files/1273345/log_extract.txt)

**Comment by ras0219-msft** [comment]
Hi @DT777, thanks for reporting this issue!

Could you please post the contents of:
>C:\src\vcpkg\buildtrees\cpprestsdk\package-x86-windows-rel-out.log
      C:\src\vcpkg\buildtrees\cpprestsdk\package-x86-windows-rel-err.log

**Comment by DT777** [comment]
Contents of log files, as requested.

[config-x86-windows-rel-err.txt](https://github.com/Microsoft/vcpkg/files/1288895/config-x86-windows-rel-err.txt)
[config-x86-windows-rel-out.txt](https://github.com/Microsoft/vcpkg/files/1288896/config-x86-windows-rel-out.txt)

**Comment by DT777** [comment]
Sorry, wrong log files-  Here are the correct version


[package-x86-windows-rel-out.txt](https://github.com/Microsoft/vcpkg/files/1288920/package-x86-windows-rel-out.txt)

The package-x86-windows-rel-err is empty

**Comment by atkawa7** [comment]
@DT777 The issue might be due to available space on your machine. Are you using a virtual machine?
`Fatal error C1085: Cannot write precompiled header file: 'stdafx.pch': There is not enough space on the disk`

**Comment by NancyLi1013** [comment]
This issue doesn't belong to vcpkg issue. So close it.
