### ISSUE TITLE
portfile.cmake SHA512 values maybe should not care about lowercase/uppercase?

### ISSUE THREAD

**Issue by TomasJohansson** [microsoft/vcpkg#17756]
Is it necessary to consider SHA512 values as different just because of different uppercase/lowercase letters?
I got the error message below but I think the hashes should be considered as equal.

`vcpkg install --feature-flags=registries,manifests`

> ...
> CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:105 (message):
> ...
>   File does not have expected hash:
> 	...
> 	Expected hash: [ 381E8DA2CD0A841525CAD67625E18D8605E302168ADE0F88AF68415369DCD5CB6CCFD31738D92E138D8400E4F6B610E51AE9463B99752A89BCEC56ABCB15CD78 ]
> 	Actual hash:   [ 381e8da2cd0a841525cad67625e18d8605e302168ade0f88af68415369dcd5cb6ccfd31738d92e138d8400e4f6b610e51ae9463b99752a89bcec56abcb15cd78 ]

**Comment by JackBoosY** [comment]
Should be lowercase.

**Comment by JackBoosY** [comment]
cc @strega-nil

**Comment by PhoebeHui** [comment]
This issue should be fixed in latest release.
