### ISSUE TITLE
Windows GTK library build failure

### ISSUE THREAD

**Issue by SudhirProg** [microsoft/vcpkg#17762]
**Host Environment**
- OS: Windows 10 Home
- Compiler: revision 16 (VS Community 2019, Msys2 MinGW GCC 10.3)

**To Reproduce**
./vcpkg install gtk

**Failure logs** 
-Cut and past the appropriate build messages from the console output - 
The log content at C:\prg_file\vcpkg\buildtrees\detect_compiler\stdout-x86-windows.log is:
CMake Error at C:/prg_file/vcpkg/scripts/ports.cmake:51 (message):
  Cannot find port:

    Directory does not exist: C;/prg_file/vcpkg/scripts/detect_compiler
    **NOTE **;** in path name could be th error**

Error: vcpkg was unable to detect the active compiler's information. See above for the CMake failure output.

The path C:/prg_file/vcpkg/scripts/detect_compiler is valid.

-Please attach any additional failure logs mentioned in the console output.
None

**Additional context**
I have tried watching youtube videos and followed successful steps exactly with no success.  The path name mentioned is "C;/prg_file/vcpkg/scripts/detect_compiler".  you will notice this contains a semi colon (;).  I cannot find a way of correcting this. 

Searching in stackexchange and other forums did not show a solution.

Downloading gvsbuild results in a successful build but I do not know how to integrate this with VS Community 2019. 

Any help to resolve this will be appreciated.

**Comment by Neumann-A** [comment]
Run from a normal cmd prompt instead of a msys one? I only can imagin a msys path conversion here which interpretes : as a path seperator and converts it to ;

**Comment by SudhirProg** [comment]
Hi. Thank you for your response. I run this from powershell and CMD. In both cases, I get the same error. I have not win this from msys command. On 10 May 2021 14:14, Alexander Neumann ***@***.***> wrote:
Run from a normal cmd prompt instead of a msys one? I only can imagin a msys path conversion here which interpretes : as a path seperator and converts it to ;

**Comment by SudhirProg** [comment]
I have managed to solve this.  Powershell has a PATH variable that bears no resemblance to the path set in environment variables.  When using the cmd, the path for MSYS2 was before cmake path for windows.  Amending the path so cmake was before msys seems to have solved the problem.

I will update when build is complete.  Hope this helps others.

**Comment by dg0yt** [comment]
@SudhirProg I have seen a few similar reports before. I'm curious how to diagnose this reliably. Can you run `cmake -G` in the original cmd setup (where vcpkg failed)? If it is cmake from MSYS2, it won't list Visual Studio generators, and it won't handle Windows paths.

**Comment by Neumann-A** [comment]
Hmm the vcpkg team should add a tag for issues like these: `broken-user-env`

**Comment by JackBoosY** [comment]
@BillyONeal what do you think about this?

**Comment by BillyONeal** [comment]
Without an understanding of where the ; is coming from I don't believe there's much we can do about this.

**Comment by JonLiu1993** [comment]
@SudhirProg, I can install GTK successfully with powershell and cmd, does this problem still exist?
powerrshell:
````
PS F:\test\vcpkg> ./vcpkg install gtk
Computing installation plan...
The following packages will be built and installed:
    gtk[core]:x86-windows -> 4.6.2
Detecting compiler hash for triplet x86-windows...
Restored 1 packages from C:\Users\vzhli17\AppData\Local\vcpkg\archives in 1.527 s. Use --debug to see more details.
Starting package 1/1: gtk:x86-windows
Installing package gtk[core]:x86-windows...
Elapsed time for package gtk:x86-windows: 1.245 s

Total elapsed time: 5.557 s
````
cmd:
````
F:\test\vcpkg>vcpkg install gtk 
Computing installation plan...
The following packages will be built and installed:
    gtk[core]:x86-windows -> 4.6.2
Detecting compiler hash for triplet x86-windows...
Restored 1 packages from C:\Users\vzhli17\AppData\Local\vcpkg\archives in 1.543 s. Use --debug to see more details.
Starting package 1/1: gtk:x86-windows
Installing package gtk[core]:x86-windows...
Elapsed time for package gtk:x86-windows: 1.079 s

Total elapsed time: 5.439 s
````

**Comment by JackBoosY** [comment]
_C;/prg_file/vcpkg/scripts/detect_compiler_
`;` should be `:`, maybe a `vcpkg-host_path` issue.

**Comment by dg0yt** [comment]
> _C;/prg_file/vcpkg/scripts/detect_compiler_ `;` should be `:`, maybe a `vcpkg-host_path` issue.

`vcpkg_host_path_list` didn't exist in May 2021. I guess the problem is gone.

**Comment by JackBoosY** [comment]
So please re-open this issue if it still exists.
