### ISSUE TITLE
[New Port Request] rubberband

### ISSUE THREAD

**Issue by dreuter** [microsoft/vcpkg#17768]
Library name: rubberband

Library description: High quality software library for audio time-stretching and pitch-shifting.

Source repository URL: https://hg.sr.ht/~breakfastquay/rubberband

Project homepage (if different from the source repository): https://www.breakfastquay.com/rubberband/

I would be happy to create a draft pull request with my portfile, which probably still needs a bit of work to not accidentally pick up system libraries.

**Comment by dreuter** [comment]
Should I go ahead and create the draft PR?
Your community guidelines state that one should create the issue first ;) which I've done here, but should I wait for feedback or create the PR now?

**Comment by autoantwort** [comment]
> but should I wait for feedback or create the PR now?

I think you can create right now and don't have to wait

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
