### ISSUE TITLE
[hunspell] build failure

### ISSUE THREAD

**Issue by BenKey** [microsoft/vcpkg#17781]
**Host Environment**
- OS: Windows 10 Pro Version 20H2 build 19042.964 with Windows Feature Experience Pack 120.2212.2020.0
- Compiler: Microsoft Visual Studio Community 2019 Version 16.9.4

**To Reproduce**
`./vcpkg install atk atkmm gtk gtkmm hunspell hunspell[tools] --triplet x64-windows`

**Failure logs** 
```
Command failed: D:/vcpkg/downloads/tools/msys2/f04a632dd84902ee/usr/bin/make.exe -j 9 --trace -f Makefile all
Working Directory: D:/vcpkg/buildtrees/hunspell/x64-windows-dbg
See logs for more information:
D:\vcpkg\buildtrees\hunspell\build-x64-windows-dbg-out.log
D:\vcpkg\buildtrees\hunspell\build-x64-windows-dbg-err.log
```

[build-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/6455496/build-x64-windows-dbg-err.log)
[build-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/6455498/build-x64-windows-dbg-out.log)

**Comment by BenKey** [comment]
What is the status of this? What does it mean that this issue has been flagged as category:port-bug?

**Comment by JackBoosY** [comment]
@BenKey Fixing...
