### ISSUE TITLE
Error: Building package boost:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by lstrcat** [Microsoft/vcpkg#1782]
Package: boost:x86-windows
  Vcpkg version: 0.0.86-2017-09-04-97104258a782630a1a0d9a2504a533a550c50b69

**patch-x86-windows-0-err.log**
`
Checking patch boost/range/has_range_iterator.hpp...
error: while searching for:
            T,?
            BOOST_DEDUCED_TYPENAME ::boost::enable_if<?
                BOOST_DEDUCED_TYPENAME mpl::eval_if<is_const<T>,?
                    has_type<range_const_iterator<?
                                BOOST_DEDUCED_TYPENAME remove_const<T>::type> >,?
                    has_type<range_mutable_iterator<T> >?
                >::type?
            >::type?
        >?

error: patch failed: boost/range/has_range_iterator.hpp:37
error: boost/range/has_range_iterator.hpp: patch does not apply

`

**Comment by ras0219-msft** [comment]
Hi @lstrcat,

Thanks for posting the patch log, but a failed patch doesn't immediately cause the build to fail. Could you post the log for the failing step?

**Comment by lstrcat** [comment]
Hello @ras0219-msft ,
here is log:

> 
The following packages will be built and installed:
    boost:x86-windows
Building package boost:x86-windows...
-- CURRENT_INSTALLED_DIR=D:/Documents/vcpkg/installed/x86-windows
-- DOWNLOADS=D:/Documents/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=D:/Documents/vcpkg/packages/boost_x86-windows
-- CURRENT_BUILDTREES_DIR=D:/Documents/vcpkg/buildtrees/boost
-- CURRENT_PORT_DIR=D:/Documents/vcpkg/ports/boost/.
-- Using cached D:/Documents/vcpkg/downloads/boost_1_65_0.7z
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Using cached D:/Documents/vcpkg/downloads/boost_1_65_0.patch
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Applying patch D:/Documents/vcpkg/downloads/boost_1_65_0.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch D:/Documents/vcpkg/downloads/boost_1_65_0.patch done
-- Using cached D:/Documents/vcpkg/downloads/boost-range-has_range_iterator-hotfix_e7ebe14707130cda7b72e0ae5e93b17157fdb6a2-2.diff
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Applying patch D:/Documents/vcpkg/buildtrees/boost/src/boost-range-has_range_iterator-hotfix_e7ebe14707130cda7b72e0ae5e93b17157fdb6a2.diff.fixed
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch D:/Documents/vcpkg/buildtrees/boost/src/boost-range-has_range_iterator-hotfix_e7ebe14707130cda7b72e0ae5e93b17157fdb6a2.diff.fixed done
-- Bootstrapping
-- Bootstrapping done
-- Building x86-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process_repeat.cmake:21 (message):
    Command failed: D:/Documents/vcpkg/buildtrees/boost/src/boost_1_65_0/b2.exe;--stagedir=D:/Documents/vcpkg/buildtrees/boost/x86-windows-rel/stage;--build-dir=D:/Documents/vcpkg/buildtrees/boost/x86-windows-rel;-sZLIB_INCLUDE="D:/Documents/vcpkg/installed/x86-windows\include";-sBZIP2_INCLUDE="D:/Documents/vcpkg/installed/x86-windows\include";-j8;--debug-configuration;--hash;-q;--without-python;threading=multi;runtime-link=shared;link=shared;toolset=msvc-14.0;-sZLIB_BINARY=zlib;-sZLIB_LIBPATH="D:/Documents/vcpkg/installed/x86-windows\lib";-sBZIP2_BINARY=bz2;-sBZIP2_LIBPATH="D:/Documents/vcpkg/installed/x86-windows\lib";variant=release;debug-symbols=on
    Working Directory: D:/Documents/vcpkg/buildtrees/boost/src/boost_1_65_0
    See logs for more information:
      D:\Documents\vcpkg\buildtrees\boost\build-x86-windows-rel-out.log
      D:\Documents\vcpkg\buildtrees\boost\build-x86-windows-rel-err.log

Call Stack (most recent call first):
  ports/boost/portfile.cmake:198 (vcpkg_execute_required_process_repeat)
  scripts/ports.cmake:72 (include)


Error: Building package boost:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost:x86-windows
  Vcpkg version: 0.0.86-2017-09-04-97104258a782630a1a0d9a2504a533a550c50b69

**Comment by JackBoosY** [comment]
Hi @lstrcat , thanks for post this issue!
This problem seems to not appear in the latest version. Can you repro it?
Thx.

**Comment by JackBoosY** [comment]
Please open a new issue if this is still a problem for you.
Thx.
