### ISSUE TITLE
Support C++20 Module

### ISSUE THREAD

**Issue by soroshsabz** [microsoft/vcpkg#17849]
ITNOA

I think the [C++20 Module](https://devblogs.microsoft.com/cppblog/standard-c20-modules-support-with-msvc-in-visual-studio-2019-version-16-8/) is the next era of [C++ dependency management](https://stackoverflow.com/q/57300495/1539100). So I think VCPKG need some good integration with it, and port all of its ports to support C++20 Module. and maybe `vcpkg` can play role like cargo for C++ so I think it is very important to fast decision and good design to make deep integration with C++20 Module.

The good news is [CMake 3.20 is support C++20 Module natively](https://gitlab.kitware.com/cmake/cmake/-/blob/master/Help/dev/experimental.rst) (also is experimental still now) and I think we can get help from that.

**Comment by soroshsabz** [comment]
related to #11177

**Comment by PhoebeHui** [comment]
@soroshsabz, thanks for bringing this up! we'd perfer to change this to discussion.
