### ISSUE TITLE
[openimageio] post-build validation failure due to iv.exe

### ISSUE THREAD

**Issue by ashwinbhat** [microsoft/vcpkg#17843]
**Host Environment**
- OS: Windows 10
- Compiler: Microsoft Visual Studio Professional 2019 Version 16.7.9

**To Reproduce**
`./vcpkg install openimageio[tools]:x64-windows-static`

**Failure logs** 
...
-- Installing: F:/vcpkg/packages/openimageio_x64-windows-static/share/openimageio/copyright
-- Performing post-build validation
The following EXEs were found in /bin or /debug/bin. EXEs are not valid distribution targets.

    F:/vcpkg/packages/openimageio_x64-windows-static/bin/iv.exe

The following EXEs were found in /bin or /debug/bin. EXEs are not valid distribution targets.

    F:/vcpkg/packages/openimageio_x64-windows-static/debug/bin/iv.exe

There should be no bin\ directory in a static build, but F:\vcpkg\packages\openimageio_x64-windows-static\bin is present.
There should be no debug\bin\ directory in a static build, but F:\vcpkg\packages\openimageio_x64-windows-static\debug\bin is present.
If the creation of bin\ and/or debug\bin\ cannot be disabled, use this in the portfile to remove them

    if(VCPKG_LIBRARY_LINKAGE STREQUAL "static")
        file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/bin" "${CURRENT_PACKAGES_DIR}/debug/bin")
    endif()

Found 3 error(s). Please correct the portfile:
    F:\vcpkg\ports\openimageio\portfile.cmake
-- Performing post-build validation done
Error: Building package openimageio:x64-windows-static failed with: POST_BUILD_CHECKS_FAILED
**Additional context**
Package: openimageio:x64-windows-static
Vcpkg version: 2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9

If we add iv to `portfile.cmake` it works but then I'm unclear how to make this conditional
```
 if("tools" IN_LIST FEATURES)
     vcpkg_copy_tools(
-        TOOL_NAMES iconvert idiff igrep iinfo maketx oiiotool
+        TOOL_NAMES iv iconvert idiff igrep iinfo maketx oiiotool
         AUTO_CLEAN
     )
 endif()```

**Comment by NancyLi1013** [comment]
Hi @ashwinbhat 

Thanks for posting this issue.

Have you installed `qt5 `and `opengl `on your machine? Since I checked the source codes and found that only `QT5 `and `opengl `have been found, the executable `iv `will be built.

https://github.com/OpenImageIO/oiio/blob/master/src/iv/CMakeLists.txt#L11

**Comment by NancyLi1013** [comment]
If this executable is not needed, I think we can disable it. https://github.com/OpenImageIO/oiio/blob/master/INSTALL.md#optional-dependencies----features-may-be-disabled-if-not-found

**Comment by ashwinbhat** [comment]
@NancyLi1013 Thank you for looking into this. 
If qt and opengl are present, oiio builds iv.exe.  But vcpkg reports this error
`The following EXEs were found in /bin or /debug/bin. EXEs are not valid distribution targets`
I think this error is reported because openimageio's `portfile.cmake` does not expect iv.exe
Now, If I add iv to portfile.cmake it works but I think it won't work if users don't have qt.

I think we need portfile.cmake to have some sort of conditional checks to support optional components.

**Comment by NancyLi1013** [comment]
@ashwinbhat 

Thanks for your information and suggestion.

> I think this error is reported because openimageio's `portfile.cmake` does not expect iv.exe
> Now, If I add iv to portfile.cmake it works but I think it won't work if users don't have qt.
> 
> I think we need portfile.cmake to have some sort of conditional checks to support optional components.

This is good point. But currently, vcpkg doesn't support optional components. Since `iv `is included in `tool `feature, there is no better way to check `vi `out from tool modules except for adding dependency for `tool `features.
