### ISSUE TITLE
[cpr] update to 1.6.2

### ISSUE THREAD

**Issue by MFMokbel** [microsoft/vcpkg#17841]
Library name: cpr

New version number: 1.6.2

Current vcpkg support is for version 1.5.2 and latest available version is 1.6.2. https://github.com/whoshuu/cpr

**Comment by MFMokbel** [comment]
Hello,

Any update on this request?

**Comment by JonLiu1993** [comment]
> Hello,
> 
> Any update on this request?

This pr has encountered some obstacles, I will deal with it

**Comment by NancyLi1013** [comment]
@MFMokbel 

`cpr `has been updated to 1.6.2, please update to the latest vcpkg to rebuild this port.

**Comment by MFMokbel** [comment]
Thank you, @NancyLi1013. All's good.
