### ISSUE TITLE
[dbghelp] build failure

### ISSUE THREAD

**Issue by zh1an** [microsoft/vcpkg#17855]
**Host Environment**
- OS: Windows 10
- Compiler: Visual Studio 2015 with update 3

**To Reproduce**
`./vcpkg install dbhelp`

**Failure logs** 
Starting package 1/7: dbghelp:x86-windows
Building package dbghelp[core]:x86-windows...
-- C:/Program Files (x86)/Windows Kits/10
CMake Error at ports/dbghelp/portfile.cmake:17 (message):
  Portfile not yet configured for Windows SDK with version:
Call Stack (most recent call first):
  scripts/ports.cmake:136 (include)

Error: Building package dbghelp:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: dbghelp:x86-windows
  Vcpkg version: 2020.11.12-nohash

Additionally, attach any relevant sections from the log files above.

**Additional context**
[stdout-x86-windows.log](https://github.com/microsoft/vcpkg/files/6464050/stdout-x86-windows.log)

**Comment by zh1an** [comment]
> **Host Environment**
> 
> * OS: Windows 10
> * Compiler: Visual Studio 2015 with update 3
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> `./vcpkg install dbhelp`
> 
> **Failure logs**
> Starting package 1/7: dbghelp:x86-windows
> Building package dbghelp[core]:x86-windows...
> -- C:/Program Files (x86)/Windows Kits/10
> CMake Error at ports/dbghelp/portfile.cmake:17 (message):
> Portfile not yet configured for Windows SDK with version:
> Call Stack (most recent call first):
> scripts/ports.cmake:136 (include)
> 
> Error: Building package dbghelp:x86-windows failed with: BUILD_FAILED
> Please ensure you're using the latest portfiles with `.\vcpkg update`, then
> submit an issue at https://github.com/Microsoft/vcpkg/issues including:
> Package: dbghelp:x86-windows
> Vcpkg version: 2020.11.12-nohash
> 
> Additionally, attach any relevant sections from the log files above.
> 
> **Additional context**
> [stdout-x86-windows.log](https://github.com/microsoft/vcpkg/files/6464050/stdout-x86-windows.log)

```
-- C:/Program Files (x86)/Windows Kits/10
CMake Error at ports/dbghelp/portfile.cmake:17 (message):
  Portfile not yet configured for Windows SDK with version:
Call Stack (most recent call first):
  scripts/ports.cmake:136 (include)
```

**Comment by zh1an** [comment]
```
Portfile not yet configured for Windows SDK with version
```

**Comment by PhoebeHui** [comment]
@zh1an, have you installed the windows sdk? if not, could you install it and try again?

BTW, I can't repro this issue with vs2015 update3, it built successfully for me.
