### ISSUE TITLE
opencv:x64-windows build failure

### ISSUE THREAD

**Issue by S4pi3nti4** [microsoft/vcpkg#17888]
**Host Environment**
- OS: x64-windows
- Compiler: revision

**To Reproduce**
./vcpkg install opencv:x64-windows`
or
./vcpkg install libwebp:x64-windows`

**Failure logs** 
PS D:\CPPLibs\vcpkg-2021.04.30> .\vcpkg install opencv:x64-windows
Computing installation plan...
The following packages will be built and installed:
  * libwebp[core,nearlossless,simd,unicode]:x64-windows -> 1.1.0#3
    opencv[core,dnn,jpeg,png,quirc,tiff,webp]:x64-windows -> 4.5.1
  * opencv4[core,dnn,jpeg,png,quirc,tiff,webp]:x64-windows -> 4.5.1#1
  * protobuf[core]:x64-windows -> 3.15.8
  * quirc[core]:x64-windows -> 1.1#2
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\Epic 001\AppData\Local\vcpkg\archives\60\609dd09596d9bde148ce3613348735048243e0b6.zip
Could not locate cached archive: C:\Users\Epic 001\AppData\Local\vcpkg\archives\64\64e90174c14f4299b277868976e40047f2349d70.zip
Could not locate cached archive: C:\Users\Epic 001\AppData\Local\vcpkg\archives\ac\ac1889c782b6b5ea607299280bfabb66e8224447.zip
Could not locate cached archive: C:\Users\Epic 001\AppData\Local\vcpkg\archives\df\df58f624b7c86ad045f3f74fb147387a08007ebc.zip
Could not locate cached archive: C:\Users\Epic 001\AppData\Local\vcpkg\archives\f3\f3675b5f8de8a047d6d8d570644c2f017476d845.zip
Starting package 1/5: libwebp:x64-windows
Building package libwebp[core,nearlossless,simd,unicode]:x64-windows...
-- Using cached D:/CPPLibs/vcpkg-2021.04.30/downloads/webmproject-libwebp-d7844e9762b61c9638c263657bd49e1690184832.tar.gz
-- Cleaning sources at D:/CPPLibs/vcpkg-2021.04.30/buildtrees/libwebp/src/1690184832-82bbc619db.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/CPPLibs/vcpkg-2021.04.30/downloads/webmproject-libwebp-d7844e9762b61c9638c263657bd49e1690184832.tar.gz
-- Applying patch 0001-build.patch
-- Applying patch 0002-cmake-config-add-backwards-compatibility.patch
-- Applying patch 0003-always-mux.patch
-- Applying patch 0004-add-missing-linked-library.patch
-- Applying patch 0006-fix-dependecies-platform.patch
-- Applying patch 0007-fix-arm-build.patch
-- Applying patch 0008-sdl.patch
-- Applying patch 0009-glut.patch
-- Using source at D:/CPPLibs/vcpkg-2021.04.30/buildtrees/libwebp/src/1690184832-82bbc619db.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Using msys root at D:/CPPLibs/vcpkg-2021.04.30/downloads/tools/msys2/50864d9fae363d6e
-- Fixing pkgconfig file: D:/CPPLibs/vcpkg-2021.04.30/packages/libwebp_x64-windows/lib/pkgconfig/libwebp.pc
-- Fixing pkgconfig file: D:/CPPLibs/vcpkg-2021.04.30/packages/libwebp_x64-windows/lib/pkgconfig/libwebpdecoder.pc
-- Fixing pkgconfig file: D:/CPPLibs/vcpkg-2021.04.30/packages/libwebp_x64-windows/lib/pkgconfig/libwebpdemux.pc
-- Fixing pkgconfig file: D:/CPPLibs/vcpkg-2021.04.30/packages/libwebp_x64-windows/lib/pkgconfig/libwebpmux.pc
-- Fixing pkgconfig file: D:/CPPLibs/vcpkg-2021.04.30/packages/libwebp_x64-windows/debug/lib/pkgconfig/libwebp.pc
-- Fixing pkgconfig file: D:/CPPLibs/vcpkg-2021.04.30/packages/libwebp_x64-windows/debug/lib/pkgconfig/libwebpdecoder.pc
-- Fixing pkgconfig file: D:/CPPLibs/vcpkg-2021.04.30/packages/libwebp_x64-windows/debug/lib/pkgconfig/libwebpdemux.pc
-- Fixing pkgconfig file: D:/CPPLibs/vcpkg-2021.04.30/packages/libwebp_x64-windows/debug/lib/pkgconfig/libwebpmux.pc
CMake Error at scripts/cmake/vcpkg_copy_tool_dependencies.cmake:29 (message):
  Could not find PowerShell Core; please open an issue to report this.
Call Stack (most recent call first):
  ports/libwebp/portfile.cmake:84 (vcpkg_copy_tool_dependencies)
  scripts/ports.cmake:142 (include)

Error: Building package libwebp:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libwebp:x64-windows
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

Additionally, attach any relevant sections from the log files above.

**Additional context**
I found this problem in older forums and it seemed to be fixed... but i am still getting this problem. When I try to build opencv, it always fails to build libwebp:x64-windows package.

EDIT
---
I also tried to build libwebp:x64-windows directly, but i got pretty much the same error.

**Comment by NancyLi1013** [comment]
Hi @S4pi3nti4 

Thanks for posting this issue. Since it's duplicated to #15681, let's track this issue there.
