### ISSUE TITLE
Building package geogram:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by aPSopt** [Microsoft/vcpkg#1788]
Win10
MSVS2017

Building package geogram:x64-windows failed with: BUILD_FAILED
See log below:

> PS C:\Users\DevUser> .$env:vcpkg install geogram:x64-windows
> The following packages will be built and installed:
>     geogram:x64-windows
> Building package geogram:x64-windows...
> -- CURRENT_INSTALLED_DIR=L:/vcpkg/installed/x64-windows
> -- DOWNLOADS=L:/vcpkg/downloads
> -- CURRENT_PACKAGES_DIR=L:/vcpkg/packages/geogram_x64-windows
> -- CURRENT_BUILDTREES_DIR=L:/vcpkg/buildtrees/geogram
> -- CURRENT_PORT_DIR=L:/vcpkg/ports/geogram/.
> -- Using cached L:/vcpkg/downloads/geogram-1.4.9.zip
> -- Testing integrity of cached file...
> -- Testing integrity of cached file... OK
> -- Extracting done
> -- Applying patch L:/vcpkg/ports/geogram/fix-cmake-config-and-install.patch
> -- Applying patch failed. This is expected if this patch was previously applied.
> -- Applying patch L:/vcpkg/ports/geogram/fix-cmake-config-and-install.patch done
> -- Configuring x64-windows-rel
> -- Configuring x64-windows-rel done
> -- Configuring x64-windows-dbg
> -- Configuring x64-windows-dbg done
> -- Package x64-windows-rel
> CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:43 (message):
>     Command failed: L:/vcpkg/downloads/cmake-3.9.1-win32-x86/bin/cmake.exe;--build;.;--config;Release;--target;install;-
> -;/p:VCPkgLocalAppDataDisabled=true;/p:UseIntelMKL=No;/m
>     Working Directory: L:/vcpkg/buildtrees/geogram/x64-windows-rel
>     See logs for more information:
>       L:\vcpkg\buildtrees\geogram\package-x64-windows-rel-out.log
>       L:\vcpkg\buildtrees\geogram\package-x64-windows-rel-err.log
> 
> Call Stack (most recent call first):
>   scripts/cmake/vcpkg_install_cmake.cmake:49 (vcpkg_execute_required_process)
>   ports/geogram/portfile.cmake:56 (vcpkg_install_cmake)
>   scripts/ports.cmake:72 (include)
> 
> 
> Error: Building package geogram:x64-windows failed with: BUILD_FAILED
> Please ensure you're using the latest portfiles with `.\vcpkg update`, then
> submit an issue at https://github.com/Microsoft/vcpkg/issues including:
>   Package: geogram:x64-windows
>   Vcpkg version: 0.0.86-2017-09-04-97104258a782630a1a0d9a2504a533a550c50b69
> 
> Additionally, attach any relevant sections from the log files above.

**Comment by ras0219-msft** [comment]
Hi @aPSopt, could you please attach the contents of
>L:\vcpkg\buildtrees\geogram\package-x64-windows-rel-out.log
L:\vcpkg\buildtrees\geogram\package-x64-windows-rel-err.log

**Comment by aPSopt** [comment]
Hi @ras0219-msft, here it is:

[geogram.zip](https://github.com/Microsoft/vcpkg/files/1303110/geogram.zip)

**Comment by kahlan78** [comment]
Hi,
with Win10 and MSVS2017 i have the same problem. The following file is the log:
[install-x64-windows-rel-out.log](https://github.com/Microsoft/vcpkg/files/1656572/install-x64-windows-rel-out.log)

Any ideas?
