### ISSUE TITLE
[boost] Fix dependency generation by vcpkg/scripts/boost/generate-ports.ps1

### ISSUE THREAD

**Issue by FabienPean** [microsoft/vcpkg#17882]
**Is your feature request related to a problem? Please describe.**
Boost modular ports generated by a script in vcpkg do not report the correct list of dependencies in "vcpkg.json" files. Observed while working on a new port relying on boost dynamic-bitset #17848 

Currently, the generator script searches in the include and source directories for strings to find included headers files and deduce the dependency.

```powershell
        if ($IsWindows)
        {
            $groups = $(
                findstr /si /C:"include <boost/" include/*
                findstr /si /C:"include <boost/" src/*
            ) | % { $_ -replace "^[^:]*:","" }
        }
        else
        {
            $groups = $(
                grep -irhs "include <boost/" include src
            )
        }
```
However, it searches only headers starting as `<boost/` and omits the one starting as `"boost/`

I did not manage to run the script successfully for testing it, so I leave this here as an issue.

**Proposed solution**
Search also for header file starting with `"boost/`

**Comment by autoantwort** [comment]
I have started with that, but #17372 must be merged first.
