### ISSUE TITLE
[New Port Request] aff3ct

### ISSUE THREAD

**Issue by topadi** [microsoft/vcpkg#17887]
Library name:aff3ct

Library description: A Fast Forward Error Correction Toolbox

Source repository URL:https://github.com/aff3ct/aff3ct

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
