### ISSUE TITLE
[New Port Request] libunistd

### ISSUE THREAD

**Issue by topadi** [microsoft/vcpkg#17893]
Library name:libunistd

Library description: libunistd is a lightweight Windows POSIX library that enables typical Linux C/C++ code to build in Windows Microsoft Visual Studio. If you're maintaining C++ code across Windows, Linux and MacOS you need a Windows POSIX library to make single codebase work. This is it.

Source repository URL:https://github.com/robinrowe/libunistd

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
