### ISSUE TITLE
[New Port Request] <CineReader>

### ISSUE THREAD

**Issue by awagdi0** [microsoft/vcpkg#17899]
Library name:  CineReader

Library description: 
CineReader is a C++ library to read raw Cine video files produced by the VisionResearch's Phantom line of cameras. Currently, the library has been tested with raw Cines produced by the Phantom V10 and V9.

Source repository URL: https://github.com/nwadhwa/CineReader

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by awagdi0** [comment]
Reopen

**Comment by PhoebeHui** [comment]
@awagdi0, unfortunately we can’t reopen this issue until a PR is opened, we're happy to answer any questions we can to support this effort, but for now we'd prefer to support your role as a maintainer than to take ownership ourselves. None of our core team is very familiar with CineReader, so I feel you'll do a much better job than we could! consider making a pull request.
