### ISSUE TITLE
[fmt] download failed

### ISSUE THREAD

**Issue by dengzikun** [Microsoft/vcpkg#1791]
Downloading https://github.com/fmtlib/fmt/archive/4.0.0.tar.gz... Failed. Status: 4;"A requested feature, protocol or option was not found built-in in this libcurl due to a build-time decision."

**Comment by ras0219-msft** [comment]
Hi @dengzikun,

I'm not able to trivially reproduce this issue. Could you elaborate on:
- Your system configuration (OS/VS)
- Your network setup (are you using a proxy?)
- What commands reproduce this issue

**Comment by dengzikun** [comment]
windows 10 profressional 64bit  vs 2017 enterprise
using network proxy. 
set http_proxy=http://192.168.3.50:8118
set https_proxy=https://192.168.3.50:8118

(Through the proxy, I use IE or EDGE can normally download spdlog and fmt)

vcpkg install spdlog

The following packages will be built and installed:
  * fmt:x86-windows
    spdlog:x86-windows
Additional packages (*) will be installed to complete this operation.
Building package fmt:x86-windows...
-- CURRENT_INSTALLED_DIR=D:/development/Tools/git/vcpkg/installed/x86-windows
-- DOWNLOADS=D:/development/Tools/git/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=D:/development/Tools/git/vcpkg/packages/fmt_x86-windows
-- CURRENT_BUILDTREES_DIR=D:/development/Tools/git/vcpkg/buildtrees/fmt
-- CURRENT_PORT_DIR=D:/development/Tools/git/vcpkg/ports/fmt/.
-- Downloading https://github.com/fmtlib/fmt/archive/4.0.0.tar.gz...
-- Downloading https://github.com/fmtlib/fmt/archive/4.0.0.tar.gz... Failed. Status: 4;"A requested feature, protocol or option was not found built-in in this libcurl due to a build-time decision."
CMake Error at D:/development/Tools/git/vcpkg/scripts/cmake/vcpkg_download_distfile.cmake:82 (message):


      Failed to download file.
      Add mirrors or submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  D:/development/Tools/git/vcpkg/scripts/cmake/vcpkg_from_github.cmake:103 (vcpkg_download_distfile)
  D:/development/Tools/git/vcpkg/ports/fmt/portfile.cmake:2 (vcpkg_from_github)
  D:/development/Tools/git/vcpkg/scripts/ports.cmake:72 (include)


Error: Building package fmt:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: fmt:x86-windows
  Vcpkg version: 0.0.86-2017-09-06-23c014d43e53fcab98f6d4c9d648213cd1ff7de8

Additionally, attach any relevant sections from the log files above.

**Comment by JackBoosY** [comment]
Hi @dengzikun , thanks for reporting this issue!
Please open a new issue if this is still a problem for you.
Thx.
