### ISSUE TITLE
[MPFR] build failure

### ISSUE THREAD

**Issue by grafster** [microsoft/vcpkg#17915]
**Host Environment**
- OS: Windows 10
- Compiler: Visual Studio 2019

**To Reproduce**
`git remote add origin https://github.com/microsoft/vcpkg.git`
`git fetch origin refs/tags/2021.04.30`
`git reset --hard FETCH_HEAD`

`call bootstrap-vcpkg.bat -disableMetrics`

`vcpkg install mpfr:x64-windows mpfr:x86-windows`

**Failure logs** 
Starting package 1/7: vs-yasm:x64-windows
Building package vs-yasm[core]:x64-windows...
Building package vs-yasm[core]:x64-windows... done
Installing package vs-yasm[core]:x64-windows...
Installing package vs-yasm[core]:x64-windows... done
Elapsed time for package vs-yasm:x64-windows: 60.54 ms
Starting package 2/7: yasm-tool:x64-windows
Building package yasm-tool[core]:x64-windows...
CMake Error at scripts/cmake/vcpkg_fail_port_install.cmake:97 (message):
  The yasm-tool port is only intended to be built for x86 Windows

  Architecture 'x64' not supported by yasm-tool!

Call Stack (most recent call first):
  ports/yasm-tool/portfile.cmake:1 (vcpkg_fail_port_install)
  scripts/ports.cmake:142 (include)

Error: Building package yasm-tool:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: yasm-tool:x64-windows
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

**Additional context**
The dependencies seem to have changed since 2020.07 - mpfr used to depend on mpir, which builds ok, but gmp doesn't seem to.

**Comment by NancyLi1013** [comment]
Hi @grafster 

Thanks for posting this issue.

Since it's duplicated to #17627. Let's track this issue there.
