### ISSUE TITLE
[pixman] build failure on Window 7 

### ISSUE THREAD

**Issue by zcream** [microsoft/vcpkg#17924]
**Host Environment**
- OS: Windows 7

**To Reproduce**
On Windows 7,
`./vcpkg install pixman`

**Failure logs** 
```
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):

    Command failed: D:/vcpkg/downloads/tools/python/python-3.9.2-x64/python.exe
D:/vcpkg/downloads/tools/meson/meson-753954be868ed78b3e339e8811fd1d29eb2af237/me
son.py -Dmmx=enabled -Dsse2=enabled -Dssse3=enabled -Dlibpng=enabled --buildtype
 plain --backend ninja --wrap-mode nodownload --native D:/vcpkg/buildtrees/pixma
n/meson-nativ-x64-windows-static.log --default-library static --libdir lib --nat
ive D:/vcpkg/buildtrees/pixman/meson-nativ-x64-windows-static-debug.log -Ddebug=
true --prefix D:/vcpkg/packages/pixman_x64-windows-static/debug --includedir ../
include -Dcmake_prefix_path=['D:/vcpkg/installed/x64-windows-static/debug','D:/v
cpkg/installed/x64-windows-static','D:/vcpkg/installed/x64-windows-static/share'
] D:/vcpkg/buildtrees/pixman/src/0.40.0-9a8e17d6df.clean
    Working Directory: D:/vcpkg/buildtrees/pixman/x64-windows-static-dbg
    Error code: Exit code 0xc0000135



    See logs for more information:

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_meson.cmake:455 (vcpkg_execute_required_process)

  ports/pixman/portfile.cmake:45 (vcpkg_configure_meson)
  scripts/ports.cmake:142 (include)
```

[CMakeOutput.log](https://github.com/microsoft/vcpkg/files/6477043/CMakeOutput.log)

**Additional context**
For all other libraries, I built the x64 version for the x64-windows-static triplet, pixman insists on using AMD64. It should be the same, unless some AMD-specific assembly is being thrown in.

I was able to build using 2020-11 version of vcpkg. I believe it is the 2021-04-26 commit that has caused issues.
    version          date    vcpkg commit
   0.40.0#0    2021-04-26    546813ae7b9e2873dd3d38e78b27ac5582feae10
   0.38.4#2    2020-10-28    ce46c257f2c1789f82cdaf12edb5b683f3cc1251

**Comment by JackBoosY** [comment]
It seems that meson is missing some dependent dlls.
cc @Neumann-A

**Comment by zcream** [comment]
Is there something I can do to fix the build in my local version ?

**Comment by marekr** [comment]
> It seems that meson is missing some dependent dlls.
> cc @Neumann-A

FYI, Python 3.9.2 will no longer run on Windows 7 as it has switched to newer Windows 8.1+ win32 API, this is most likely @zcream's issue.

**Comment by zcream** [comment]
@marekr That seems to be the issue. Since vcpkg does support windows 7 for other build, can the install scripts check for the windows version and install python 3.8.10 instead ? 

I dont think VCPKG_FORCE_SYSTEM_BINARIES works for picking up the python install. When I use it, I get this bug - https://github.com/microsoft/vcpkg/issues/10066

It just prints `Computing installation plan...` and exits

**Comment by zcream** [comment]
The version needed by me is python3 - 0.56.0 and tool-meson - 3.8.10 
I thought of using the manifest method to force these versions but python 3.9.2 is still being downloaded. Could someone suggest how I can force tool-meson and python to these values ?

I tried all the following :- 
1. ports/pixman.vcpkg.json 
```
 "builtin-baseline": "57142be41cf432aa01a5ce5a9cff2c76706e82fa",
  "overrides": [
    { "name": "tool-meson", "version": "0.56.0" }
  ]
```
2. versions/baseline.json
```
    "python3": {
      "baseline": "3.8.10",
      "port-version": 2
    },
```

```
   "tool-meson": {
      "baseline": "0.56.0",
      "port-version": 0
    },
```
3. python3/vcpkg.json
```
  "name": "python3",
  "version-string": "3.8.10",
  "port-version": 2,
```
4. tool-meson/vcpkg.json
```
  "name": "tool-meson",
  "version": "0.56.0",
```

**Comment by marekr** [comment]
The python3 port is not used for the "tool" portion, it's hardcoded download in `vcpkg_find_acquire_program.cmake`

**Comment by zcream** [comment]
Got the build to work.

I changed the version to 
```
  elseif(VAR MATCHES "PYTHON3")
    if(CMAKE_HOST_WIN32)
      set(PROGNAME python)
      set(PYTHON_VERSION 3.9.2)
```
And
```
      else()
        set(SUBDIR "python-${PYTHON_VERSION}-x64")
        set(URL "https://www.python.org/ftp/python/${PYTHON_VERSION}/python-${PYTHON_VERSION}-embed-amd64.zip")
        set(ARCHIVE "python-${PYTHON_VERSION}-embed-amd64.zip")
        set(HASH	86e55911be78205a61f886feff2195c78a6f158a760cc1697ce4340dcb5ca118360251de2f707b6d2a78b7469d92c87b045b7326d6f194bfa92e665af1cd55a5)
```

I removed 
`      set(POST_INSTALL_COMMAND ${CMAKE_COMMAND} -E rm python39._pth)`

**Comment by zcream** [comment]
Going forward, some of us have to support users on Windows 7 but obviously the Contributors cannot be expected to support Windows 7. Is it possible to document the last version of vcpkg where meson 0.56 and python 3.8.10 are being used ?

Then the users can use a snapshot of vcpkg from that checkin and build all libs against it. Also, the manifest method clearly did not work this time due to the hardwiring of python version. What other method can we use to use the last working vcpkg snapshot for Windows 7 ?

**Comment by zcream** [comment]
For anyone wishing to use vcpkg on Windows 7.

`D:\vcpkg [(2020.11-1)]> git clone https://github.com/Microsoft/vcpkg.git`
`D:\vcpkg [(2020.11-1)]> cd .\vcpkg\`
`D:\vcpkg [(2020.11-1)]> git checkout 2020.11-1`
`D:\vcpkg [(2020.11-1)]> .\bootstrap-vcpkg.bat`

**Comment by zcream** [comment]
@PhoebeHui once I have frozen vcpkg, is there a way to update individual packages only ?
For example curl is at 7.77 at github but I am at 7.73 
I only want to update curl and leave everything else untouched.
