### ISSUE TITLE
How do I include this header to my project?

### ISSUE THREAD

**Issue by earthnash** [microsoft/vcpkg#17930]
When asking a question please also include where you looked for an answer (so we can update the documentation if needed).
I have installed gRPC version 1.37.0.
after that I use command vcpkg integrate install to enable User-wide integration.
I include serveral gRPC header files and everything seems to be fine.
But when I try to include grpcpp/ext/proto_server_reflection_plugin.h in my project(visual studio 2019),
It doesn't automatically include this files for me.

I have tried to remove User-wide integration and install it again but The problem still exits.

**Comment by NancyLi1013** [comment]
Hi @earthnash 

Thanks for posting this issue.
I tried to include the headers on my machine, it can be automatically included. Do you use CMake project or MSBuild Project?

![image](https://user-images.githubusercontent.com/46708020/118350572-1c4f3780-b58a-11eb-9a15-f110b30c4b71.png)

**Comment by earthnash** [comment]
Many thanks for the prompt reply.
I used MSBuild with my project.

**Comment by NancyLi1013** [comment]
I used MSBuild with my project too. But as you can see, I can include `grpcpp/ext/proto_server_reflection_plugin.h` in my project.

**Comment by earthnash** [comment]
After I complete remove and install both Visual Studio and vpckg. 
The problem solves.
