### ISSUE TITLE
[aria2] use environment variable to select download tool

### ISSUE THREAD

**Issue by cenit** [microsoft/vcpkg#17934]
**Is your feature request related to a problem? Please describe.**
At the moment, I am unable to use ARIA2 in manifest mode. Is it possible to think about selecting the download tool through an environment variable?

**Comment by cenit** [comment]
@JackBoosY since you self-assigned this to yourself, may I ask you if you are working on a PR on this problem?
it would be wonderful.
i can try to help you but i cannot do it alone, because i am really overworked right now

**Comment by JackBoosY** [comment]
Sadly, I don't have much time either. This issue is queued.

**Comment by MonicaLiu0311** [comment]
Fixed by https://github.com/microsoft/vcpkg/pull/20971, https://github.com/microsoft/vcpkg-tool/pull/229, https://github.com/microsoft/vcpkg/pull/20585.

You can use the following command:
* Classic Mode: `.\vcpkg --x-use-aria2 install portName`
* Manifest mode: `.\vcpkg --x-use-aria2 install`
