### ISSUE TITLE
[<port name>] build failure

### ISSUE THREAD

**Issue by Karsteski** [microsoft/vcpkg#17943]
**Host Environment**
- OS: [Linux]
- Compiler: revision

**To Reproduce**
`./vcpkg install glfw3`

**Failure logs** 
These can be installed on Ubuntu systems via sudo apt install libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev
-- Configuring x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
    Command failed: /vcpkg/downloads/tools/cmake-3.20.2-linux/cmake-3.20.2-linux-x86_64/bin/cmake /vcpkg/buildtrees/glfw3/src/3.3.3-47325b0495.clean -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF -DCMAKE_MAKE_PROGRAM=/vcpkg/downloads/tools/ninja-1.10.1-linux/ninja -DCMAKE_SYSTEM_NAME=Linux -DBUILD_SHARED_LIBS=OFF -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/vcpkg/scripts/toolchains/linux.cmake -DVCPKG_TARGET_TRIPLET=x64-linux -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=external -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_LINKER_FLAGS_RELEASE= -DVCPKG_LINKER_FLAGS_DEBUG= -DVCPKG_TARGET_ARCHITECTURE=x64 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -D_VCPKG_ROOT_DIR=/vcpkg -D_VCPKG_INSTALLED_DIR=/vcpkg/installed -DVCPKG_MANIFEST_INSTALL=OFF -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/vcpkg/packages/glfw3_x64-linux/debug
    Working Directory: /vcpkg/buildtrees/glfw3/x64-linux-dbg
    Error code: 1
    See logs for more information:
      /vcpkg/buildtrees/glfw3/config-x64-linux-dbg-out.log
      /vcpkg/buildtrees/glfw3/config-x64-linux-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:332 (vcpkg_execute_required_process)
  ports/glfw3/portfile.cmake:20 (vcpkg_configure_cmake)
  scripts/ports.cmake:142 (include)

Error: Building package glfw3:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: glfw3:x64-linux
  Vcpkg version: 2021-05-05-unknownhash

**Additional context**
I reinstalled my OS (Pop!_OS 21.10) and now vcpkg doesn't work for any packages(GLFW3, GLEW). It worked perfectly fine before :(

[config-x64-linux-dbg-err.log](https://github.com/microsoft/vcpkg/files/6481034/config-x64-linux-dbg-err.log)
[config-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/6481035/config-x64-linux-dbg-out.log)

**Comment by dg0yt** [comment]
config-x64-linux-dbg-err.log: `Could NOT find X11 (missing: X11_X11_INCLUDE_PATH X11_X11_LIB)`

So you will need to install some `-dev` packages from you Linux distribution.

**Comment by Karsteski** [comment]
Which ones would that be? I'm trying to find out what would be required for this but not sure where to look... Is there just something similar to "build-essentials"?

**Comment by Karsteski** [comment]
> config-x64-linux-dbg-err.log: `Could NOT find X11 (missing: X11_X11_INCLUDE_PATH X11_X11_LIB)`
> 
> So you will need to install some `-dev` packages from you Linux distribution.

**Comment by Karsteski** [comment]
I figured it out. I needed to install the `xorg-dev` packages using `sudo apt install xorg-dev`
