### ISSUE TITLE
cudnn[core]:x64-linux build failure

### ISSUE THREAD

**Issue by bobluoluo** [microsoft/vcpkg#17940]
**Host Environment**
- OS: Ubuntu 18.04 
- Compiler: gcc 7.5

**To Reproduce**
`./vcpkg install cudnn

**Failure logs** 
Computing installation plan...
The following packages will be built and installed:
    cudnn[core]:x64-linux -> 7.6.5#2
Detecting compiler hash for triplet x64-linux...
Could not locate cached archive: /home/bob/.cache/vcpkg/archives/5d/5dfee48e7a77bdcec119a8aa2e8f26018c5c96fc.zip
Starting package 1/1: cudnn:x64-linux
Building package cudnn[core]:x64-linux...
-- Note: cudnn only supports dynamic library linkage. Building dynamic library.
CMake Error at ports/cudnn/portfile.cmake:13 (include):
  include could not find requested file:

    /home/bob/dev/vcpkg/installed/x64-linux/share/cuda/vcpkg_find_cuda.cmake
Call Stack (most recent call first):
  scripts/ports.cmake:142 (include)

Error: Building package cudnn:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: cudnn:x64-linux
  Vcpkg version: 2021-05-05-unknownhash

**Additional context**
1. it has no issue of "installing" cuda: vcpkg install cuda
2. locate libcudnn verifies files are there. 
![image](https://user-images.githubusercontent.com/56043227/118310934-3b33c800-b4bd-11eb-810e-d47e4a003ff5.png)

**Comment by cenit** [comment]
output of

ls -l /home/bob/dev/vcpkg/installed/x64-linux/share/

and

ls -l /home/bob/dev/vcpkg/installed/x64-linux/share/cuda 

?

**Comment by bobluoluo** [comment]
bob@bob-C9Z390-PGW:~$ ls -l /home/bob/dev/vcpkg/installed/x64-linux/share/cuda
total 4
-rw-r--r-- 1 bob bob 309 Jul 17  2020 vcpkg_abi_info.txt
bob@bob-C9Z390-PGW:~$ ls -l /home/bob/dev/vcpkg/installed/x64-linux/share/
total 368
drwxr-xr-x 2 bob bob 4096 Jul  3  2020 aclocal
drwxr-xr-x 2 bob bob 4096 Nov 13 23:25 angle
drwxrwxr-x 2 bob bob 4096 Apr  8 14:39 asio
drwxr-xr-x 2 bob bob 4096 Aug 17  2020 assimp
drwxr-xr-x 2 bob bob 4096 Nov 13 15:14 aws-c-common
drwxr-xr-x 2 bob bob 4096 Nov 13 15:14 aws-c-event-stream
drwxr-xr-x 2 bob bob 4096 Nov 13 15:14 aws-checksums
drwxr-xr-x 2 bob bob 4096 Nov 13 15:16 aws-cpp-sdk-core
drwxr-xr-x 2 bob bob 4096 Nov 13 15:16 aws-cpp-sdk-dynamodb
drwxr-xr-x 2 bob bob 4096 Nov 13 15:16 aws-cpp-sdk-kinesis
drwxr-xr-x 2 bob bob 4096 Nov 13 15:16 aws-cpp-sdk-rekognition
drwxr-xr-x 2 bob bob 4096 Nov 13 15:16 aws-cpp-sdk-s3
drwxr-xr-x 2 bob bob 4096 Nov 13 15:16 aws-sdk-cpp
drwxr-xr-x 3 bob bob 4096 Jul  9  2020 azure_macro_utils_c
drwxr-xr-x 2 bob bob 4096 Jul  9  2020 azure-macro-utils-c
drwxr-xr-x 2 bob bob 4096 Aug 17  2020 basisu
drwxr-xr-x 2 bob bob 4096 Aug 17  2020 bullet3
drwxr-xr-x 2 bob bob 4096 Aug 17  2020 bzip2
drwxr-xr-x 2 bob bob 4096 Jul  9  2020 cjson
drwxr-xr-x 7 bob bob 4096 Aug 17  2020 cmake
drwxr-xr-x 2 bob bob 4096 Aug 17  2020 corrade
drwxr-xr-x 2 bob bob 4096 Jul 17  2020 cuda
drwxr-xr-x 2 bob bob 4096 Nov 13 15:15 curl
drwxr-xr-x 2 bob bob 4096 Aug 17  2020 devil
drwxr-xr-x 2 bob bob 4096 Nov 13 23:25 dirent
drwxr-xr-x 4 bob bob 4096 Nov 13 23:25 doc
drwxr-xr-x 2 bob bob 4096 Nov 13 23:25 double-conversion
drwxr-xr-x 2 bob bob 4096 Jul  9  2020 ebml
drwxr-xr-x 2 bob bob 4096 Nov 13 23:23 egl-registry
drwxr-xr-x 2 bob bob 4096 Aug 17  2020 eigen3
drwxr-xr-x 2 bob bob 4096 Nov 13 23:25 expat
drwxr-xr-x 2 bob bob 4096 Nov 13 16:16 fast-cpp-csv-parser
drwxr-xr-x 2 bob bob 4096 Jul  2  2020 fmt
drwxr-xr-x 2 bob bob 4096 Nov 13 23:25 fontconfig
drwxr-xr-x 2 bob bob 4096 Aug 17  2020 freeglut
drwxr-xr-x 2 bob bob 4096 Aug 17  2020 freetype
drwxr-xr-x 2 bob bob 4096 Feb  3 11:31 glew
drwxr-xr-x 2 bob bob 4096 Jul  9  2020 glfw3
drwxr-xr-x 2 bob bob 4096 Jul  3  2020 glm
drwxr-xr-x 2 bob bob 4096 Aug 17  2020 glut
drwxr-xr-x 2 bob bob 4096 Jul  9  2020 gtest
drwxr-xr-x 2 bob bob 4096 Aug 17  2020 harfbuzz
drwxr-xr-x 2 bob bob 4096 Nov 13 23:27 icu
drwxr-xr-x 2 bob bob 4096 Jul  3  2020 imgui
drwxr-xr-x 2 bob bob 4096 Aug 17  2020 jasper
drwxr-xr-x 2 bob bob 4096 Jul  9  2020 jpeg
drwxr-xr-x 2 bob bob 4096 Aug 17  2020 lcms
drwxr-xr-x 2 bob bob 4096 Nov 13 23:25 libiconv
drwxr-xr-x 2 bob bob 4096 Jul  9  2020 libjpeg-turbo
drwxr-xr-x 2 bob bob 4096 Aug 17  2020 liblzma
drwxr-xr-x 2 bob bob 4096 Aug 17  2020 libpng
drwxr-xr-x 3 bob bob 4096 Nov 13 23:27 libpq
drwxr-xr-x 2 bob bob 4096 Jul  9  2020 libsoundio
drwxr-xr-x 2 bob bob 4096 Feb  9 10:41 libusb
drwxr-xr-x 2 bob bob 4096 Nov 13 18:15 libwebp
drwxr-xr-x 3 bob bob 4096 Aug 10  2020 lodepng
drwxr-xr-x 2 bob bob 4096 Aug 17  2020 magnum
drwxr-xr-x 2 bob bob 4096 Aug 17  2020 magnum-integration
drwxr-xr-x 2 bob bob 4096 Aug 17  2020 magnum-plugins
drwxr-xr-x 2 bob bob 4096 Oct 29  2020 Microsoft.GSL
drwxr-xr-x 2 bob bob 4096 Aug 17  2020 minizip
drwxr-xr-x 2 bob bob 4096 Oct 29  2020 ms-gsl
drwxr-xr-x 2 bob bob 4096 Aug 10  2020 nlohmann_json
drwxr-xr-x 2 bob bob 4096 Aug 10  2020 nlohmann-json
drwxr-xr-x 4 bob bob 4096 Jul  3  2020 openal
drwxr-xr-x 2 bob bob 4096 Jul  3  2020 openal-soft
drwxr-xr-x 2 bob bob 4096 Aug 17  2020 openexr
drwxr-xr-x 2 bob bob 4096 Aug 17  2020 opengl
drwxr-xr-x 2 bob bob 4096 Nov 13 23:23 opengl-registry
drwxr-xr-x 2 bob bob 4096 Jul  9  2020 openssl
drwxr-xr-x 2 bob bob 4096 Jul  9  2020 openssl-unix
drwxr-xr-x 2 bob bob 4096 Nov 13 23:28 pcre2
drwxr-xr-x 2 bob bob 4096 Nov 13 23:27 postgresql
drwxr-xr-x 2 bob bob 4096 Nov 13 18:15 protobuf
drwxr-xr-x 3 bob bob 4096 Jul 12  2020 pybind11
drwxr-xr-x 2 bob bob 4096 Aug 17  2020 ragel
drwxr-xr-x 2 bob bob 4096 Aug 17  2020 rapidjson
drwxr-xr-x 2 bob bob 4096 Jul  3  2020 sdl2
drwxr-xr-x 2 bob bob 4096 Jul  2  2020 spdlog
drwxr-xr-x 2 bob bob 4096 Nov 13 23:28 sqlite3
drwxr-xr-x 2 bob bob 4096 Feb  3 15:32 tbb
drwxr-xr-x 2 bob bob 4096 Aug 17  2020 tiff
drwxr-xr-x 2 bob bob 4096 Jul  9  2020 umock_c
drwxr-xr-x 2 bob bob 4096 Jul  9  2020 umock-c
drwxr-xr-x 2 bob bob 4096 Nov 13 23:25 unofficial-angle
drwxr-xr-x 2 bob bob 4096 Nov 13 23:25 unofficial-fontconfig
drwxr-xr-x 2 bob bob 4096 Nov 13 23:25 unofficial-iconv
drwxr-xr-x 2 bob bob 4096 Nov 13 23:28 unofficial-sqlite3
drwxr-xr-x 2 bob bob 4096 Nov 13 18:15 WebP
drwxr-xr-x 2 bob bob 4096 Oct 29  2020 xxhash
drwxr-xr-x 2 bob bob 4096 Jul  9  2020 zlib
drwxr-xr-x 2 bob bob 4096 Nov 13 23:28 zstd
bob@bob-C9Z390-PGW:~$

**Comment by cenit** [comment]
go to vcpkg root folder and do 
./bootstrap-vcpkg.sh
./vcpkg update
./vcpkg upgrade --no-dry-run

**Comment by bobluoluo** [comment]
![image](https://user-images.githubusercontent.com/56043227/118337915-d9865480-b4e2-11eb-933c-d72cd80a6d95.png)

**Comment by JackBoosY** [comment]
@cenit ping for reply.

**Comment by cenit** [comment]
didn't reply because the screenshot was clear enough

the user needs to update cuda to at least v10.2

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
