### ISSUE TITLE
[New Port Request] wxcharts

### ISSUE THREAD

**Issue by playgithub** [microsoft/vcpkg#17950]
Library name:
wxcharts

Library description:
A library to create charts in wxWidgets applications.

Source repository URL:
https://github.com/wxIshiko/wxCharts

Project homepage (if different from the source repository):
https://www.wxishiko.com/wxCharts/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
Is there any good library for charts in vcpkg now?
BTW, there is a port called `wxchartdir`, but it is a wrapper of a commercial one.

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
