### ISSUE TITLE
How do I build c++ src for platform iOS(arm64/arm/x86/x64) with vcpkg tool?

### ISSUE THREAD

**Issue by fallending** [microsoft/vcpkg#17968]
### First, get protobuf older version 2.6.1

https://github.com/maketea-tech/mt-protobuf-2_6_1

### Try to build protobuf-2_6_1 with vcpkg tool

```
toolchain := $(VCPKG_HOME)/scripts/buildsystems/vcpkg.cmake
ios_toolchain := ${VCPKG_HOME}/scripts/toolchains/ios.cmake
```

- cmake .. -GXcode -DCMAKE_TOOLCHAIN_FILE=$(ios_toolchain) -DVCPKG_TARGET_TRIPLET=arm64-ios && cmake --build . --config Debug
- cmake .. -GXcode -DCMAKE_TOOLCHAIN_FILE=${toolchain} -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=$(ios_toolchain) -DVCPKG_TARGET_TRIPLET=arm64-ios -DVCPKG_CMAKE_SYSTEM_NAME=iOS && cmake --build . --config Debug

build failed with these scripts above...

any advices??

**Comment by fallending** [comment]
Any response?

**Comment by JackBoosY** [comment]
That's related to the toolchain, I prefer @alcroito @psfrolov to have a reply.

**Comment by LilyWangLL** [comment]
Ping @alcroito @psfrolov for response. Could you help take a look this issue? Thanks in advance.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. This is a community issue and there are no updates more than 3 months, please reopen this issue if this is still a problem for you.
