### ISSUE TITLE
[New Port Request]: pkcs11-helper

### ISSUE THREAD

**Issue by anjiao1989** [microsoft/vcpkg#17977]
Library name: pkcs11-helper

Library description:pkcs11-helper is a library that simplifies the interaction with	PKCS#11 providers for end-user applications.

Source repository URL:https://github.com/OpenSC/pkcs11-helper

Project homepage (if different from the source repository):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
