### ISSUE TITLE
[fmt] build failure with CMake, MinGW

### ISSUE THREAD

**Issue by Jerome-AJAM** [microsoft/vcpkg#17979]
**Host Environment**
- OS: Windows 10 x64 19042.985
- Compiler: GCC 10.2.0 x86_64-w64-mingw32

**To Reproduce**
`./vcpkg install fmt`
`find_package(fmt CONFIG REQUIRED)`
`target_link_libraries(target_name PRIVATE fmt::fmt)`

**Failure logs** 
```
[build] [100%] Linking CXX executable OpenFA.exe
[build] Warning: corrupt .drectve at end of def file
[build] D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\OpenFA.dir/objects.a(engine.cpp.obj): in function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > fmt::v7::format<char [31], char const*, char>(char const (&) [31], char const*&&)':
[build] D:/Misc/Development/vcpkg/installed/x64-windows/include/fmt/core.h:2076: undefined reference to `__imp__ZN3fmt2v76detail7vformatB5cxx11ENS0_17basic_string_viewIcEENS0_11format_argsE'
[build] D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/Misc/Development/vcpkg/installed/x64-windows/include/fmt/core.h:2076: undefined reference to `__imp__ZN3fmt2v76detail7vformatB5cxx11ENS0_17basic_string_viewIcEENS0_11format_argsE'
[build] D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\OpenFA.dir/objects.a(engine.cpp.obj): in function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > fmt::v7::format<char [30], unsigned char const*, char>(char const (&) [30], unsigned char const*&&)':
[build] D:/Misc/Development/vcpkg/installed/x64-windows/include/fmt/core.h:2076: undefined reference to `__imp__ZN3fmt2v76detail7vformatB5cxx11ENS0_17basic_string_viewIcEENS0_11format_argsE'
[build] D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\OpenFA.dir/objects.a(engine.cpp.obj): in function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > fmt::v7::format<char [24], char const*, char>(char const (&) [24], char const*&&)':
[build] D:/Misc/Development/vcpkg/installed/x64-windows/include/fmt/core.h:2076: undefined reference to `__imp__ZN3fmt2v76detail7vformatB5cxx11ENS0_17basic_string_viewIcEENS0_11format_argsE'
[build] D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\OpenFA.dir/objects.a(engine.cpp.obj): in function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > fmt::v7::format<char [27], std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, char>(char const (&) [27], std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)':
[build] D:/Misc/Development/vcpkg/installed/x64-windows/include/fmt/core.h:2076: undefined reference to `__imp__ZN3fmt2v76detail7vformatB5cxx11ENS0_17basic_string_viewIcEENS0_11format_argsE'
[build] D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\OpenFA.dir/objects.a(gl.cpp.obj):D:/Misc/Development/vcpkg/installed/x64-windows/include/fmt/core.h:2076: more undefined references to `__imp__ZN3fmt2v76detail7vformatB5cxx11ENS0_17basic_string_viewIcEENS0_11format_argsE' follow
[build] collect2.exe: error: ld returned 1 exit status
```

**Additional context**
- Looks practically identical to https://github.com/microsoft/vcpkg/issues/10419#issuecomment-599227675.
- Can guarantee my vcpkg installation is up-to-date with the master branch as of the time of this post.
- At this time, that package is the only available port of {fmt}; none are advertised as being MinGW-specific. MSYS2 offers a MinGW-specific {fmt} via Pacman, and it builds successfully in this same configuration, though this becomes a problem if I try to link Quill from vcpkg (which is not offered by Pacman).
- The complete CMake setup with {fmt} and Quill builds fine from vcpkg on my Linux Mint 20 machine.
- Prior to migrating to vcpkg, I built {fmt} from a submodule using a CMake subdirectory (`fmt::fmt-header-only`), and that was always fine.
- In `fmt::fmt-header-only` configuration, this same setup builds fine.
- I already tried defining the FMT_SHARED macro, even though {fmt}'s config CMake should cover this already, just to be certain.
- The error logs posted above are from a more elaborate project of mine but I made sure to test this on a completely fresh CMake project with only the one library, and received identical results.

**Comment by NancyLi1013** [comment]
Hi @Jerome-AJAM 
Thanks for posting this issue.

Did you install fmt:x64-windows or other triplet?

Can you please help provide your whole project sample including CMakeLists.txt and *.cpp? Also please provide your repro steps, including build command. 

Did you install fmt with `GCC 10.2.0 x86_64-w64-mingw32` or compile your project with `GCC 10.2.0 x86_64-w64-mingw32`?

**Comment by Jerome-AJAM** [comment]
The triplet is `fmt:x64-windows`, yes.
{fmt} was not installed with MinGW. Only the project was built that way.

Please find attached the files needed to reproduce. The only thing otherwise needed is to specify in a `settings.json` that CMake uses vcpkg's cmake file as a toolchain.
[fmt_test.zip](https://github.com/microsoft/vcpkg/files/6500746/fmt_test.zip)

The build command was auto-generated using CMake Tools for VSCode, which was also used to generate the project and cache:
`D:\Program Files\CMake\bin\cmake.EXE -build d:/Misc/Development/fmt_quill_test/build --config Debug --target all -j 14`

Thanks for the quick reply.

**Comment by NancyLi1013** [comment]
I have no VSCode environment. So I'm not sure the status on it. I build it with VS without any error.

**Comment by NancyLi1013** [comment]
I used your project to build, the result is as follows:
```
PS F:\tool\vcpkg\cprtest\build> cmake .. "-DCMAKE_TOOLCHAIN_FILE=F:\tool\vcpkg\scripts\buildsystems\vcpkg.cmake" -- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19043.
-- The C compiler identification is MSVC 19.28.29914.0
-- The CXX compiler identification is MSVC 19.28.29914.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: F:/tool/vcpkg/cprtest/build
PS F:\tool\vcpkg\cprtest\build> cmake --build .
Microsoft (R) Build Engine version 16.9.0+5e4b48a27 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  Building Custom Rule F:/tool/vcpkg/cprtest/CMakeLists.txt
  main.cpp
  main.vcxproj -> F:\tool\vcpkg\cprtest\build\Debug\main.exe
  Building Custom Rule F:/tool/vcpkg/cprtest/CMakeLists.txt
```

**Comment by dg0yt** [comment]
> {fmt} was not installed with MinGW. Only the project was built that way.

This is explicitly mixing MSVC (fmt) and Mingw. I wonder why you don't build fmt with Mingw then.

**Comment by Jerome-AJAM** [comment]
> > {fmt} was not installed with MinGW. Only the project was built that way.
> 
> This is explicitly mixing MSVC (fmt) and Mingw. I wonder why you don't build fmt with Mingw then.

I spent a few hours reading vcpkg's documentation while troubleshooting and never got the impression I was able to choose what build tools it used when I ran an install command on any given package. I understand I can use `--only-downloads` but if I can instead use one command to change {fmt} to a MinGW lib instead of a VC lib I would like to know what it is.

**Comment by dg0yt** [comment]
You need to choose the target triplet. There are different ways to do that:
- parameters for the vcpkg command
- with `:` after the package name when running vcpkg, e.g. `./vcpkg install fmt:x64-mingw-dynamic`
- environment variables
- parameters for the build system if using manifest mode

For mingw, there is now also https://github.com/microsoft/vcpkg/blob/master/docs/users/mingw.md

**Comment by Jerome-AJAM** [comment]
I had mistakenly believed that the `x64-windows` triplet was for both MSVC and MinGW. Apologies.
Curiously, the test project builds fine with {fmt} from `static` but not `dynamic`.
I'm tentatively closing this issue since this build pipeline isn't officially supported and I no longer have the full picture on whether or not my whole dependency chain works with MinGW. The good news is that I switched to MSVC yesterday anyway and that's working fine so far.
Thanks to all involved for the patience.
