### ISSUE TITLE
I can't install any package: No suitable Visual Studio instances were found.

### ISSUE THREAD

**Issue by leiniercs** [microsoft/vcpkg#17971]
Hello. I want to install a library and I can't because 'vcpkg' halts with an error: No suitable Visual Studio instances were found.

I read the installation instructions and I installed the required tools:

- Microsoft Visual Studio Professional 2017. C++ tools. Windows 10 SDK (v141), Windows 8.1 SDK. English package language. Git.
- I cloned the repository into 'C:\Qt\vcpkg\' and executed it with path prefix ('.\bootstrap-vcpkg.bat' and '.\vcpkg.exe').
- The Visual Studio is installed on 'C:\Program Files (x86)\Microsoft Visual Studio'.

What is happening? Why is 'vcpkg' showing me that error?

**Comment by jamescavallo** [comment]
Same issue here

**Comment by PhoebeHui** [comment]
@leiniercs, @jamescavallo, could you try to reinstall the VS and see if the issue persists?

**Comment by leiniercs** [comment]
Hello, @PhoebeHui, reinstallation of the Visual Studio 2017 is not the solution. Clearly it is a problem of the 'vcpkg' software. I uninstalled Visual Studio 2017 and installed Visual Studio 2019. 'vcpkg' worked on the first installation request.

**Comment by PhoebeHui** [comment]
This generally since something wrong in VS setting, we can't get relate environment correctly, I think we don't have any plan to improve this currently.
