### ISSUE TITLE
[New Port Request] tomlc99

### ISSUE THREAD

**Issue by calloatti** [microsoft/vcpkg#17982]
Library name: tomlc99

Library description: TOML parsing library. Compatible with TOML v1.0.0., Provides very simple and intuitive interface.

Source repository URL: https://github.com/cktan/tomlc99

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
