### ISSUE TITLE
[osgearth] build failure with x64-linux unresolved references 

### ISSUE THREAD

**Issue by ankurverma85** [microsoft/vcpkg#17992]
**Host Environment**
- OS: [e.g. Windows/Linux etc...] Fedora 34
- Compiler: GCC11 Libstdc++11

**To Reproduce**
`./vcpkg install osgearth:x64-linux`

**Failure logs** 
Undefined references from GDAL around openjpeg and xml2

**Additional context**

**Comment by NancyLi1013** [comment]
Hi @ankurverma85 

Thanks for posting this issue.

Is it possible to post the detailed error info here?

**Comment by dg0yt** [comment]
The GDAL issues on Linux are wellknown. See #9068. I'm working on it, but I need to fix problems with incoming dependencies first. And some vcpkg build system problems which turn out on the way.
https://github.com/microsoft/vcpkg/pulls/dg0yt is another way to look at it.
Once gdal builds with clean dependencies, it will also have a complete pc file for consumers.
