### ISSUE TITLE
[vcpkg upgrade][ffmpeg[wavpack]] - 'vcpkg upgrade': Package ffmpeg does not have a wavpack feature

### ISSUE THREAD

**Issue by traumedy** [microsoft/vcpkg#17995]
After `git pull` last night, `vcpkg upgrade` results in:
```
C:\vcpkg>vcpkg upgrade
Package ffmpeg does not have a wavpack feature
Note: Updating vcpkg by rerunning bootstrap-vcpkg may resolve this failure.
```
`bootstrap-vcpkg` does NOT resolve his failure.

**Environment**
- OS: Windows 10 Version 10.0.19042.985
- Compiler: Visual Studio 2017/2019

**To Reproduce**
Seems to be related to having ffmpeg[wavpack] installed, `vcpkg search ffmpeg` no longer lists wavpack module for ffmpeg.
After `git pull` last night, `vcpkg upgrade` displays above behavior.  Also performed `bootstrap-vcpkg`.

**Expected behavior**
Should display installed packages that can be upgraded.

**Failure logs** 
```
C:\vcpkg>vcpkg upgrade --debug
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] BuiltinRegistry initialized with: ""
[DEBUG] Using vcpkg-root: C:\vcpkg
[DEBUG] Using installed-root: C:\vcpkg\installed
[DEBUG] BuiltinRegistry initialized with: ""
[DEBUG] Using buildtrees-root: C:\vcpkg\buildtrees
[DEBUG] Using downloads-root: C:\vcpkg\downloads
[DEBUG] Using packages-root: C:\vcpkg\packages
[DEBUG] Using scripts-root: C:\vcpkg\scripts
[DEBUG] Using ports-root: C:\vcpkg\ports
[DEBUG] Using versions-root: C:\vcpkg\versions
[DEBUG] Default binary cache path is: C:\Users\Josh\AppData\Local\vcpkg\archives
Package ffmpeg does not have a wavpack feature
Note: Updating vcpkg by rerunning bootstrap-vcpkg may resolve this failure.
[DEBUG] C:\A\1\121\s\src\vcpkg\dependencies.cpp(835)
[DEBUG] Exiting after 411185 us (395525 us)
```

**Comment by mcmtroffaes** [comment]
I guess I'm the guilty party! 😄 The feature was removed in #17735 as libwavpack support is removed in ffmpeg 4.4. There's no loss in functionality as you can simply use the native wavpack encoder/decoder.

However, the real issue here appears to be that vcpkg upgrade does not recognize that the feature is gone. Is there a way to remove/deprecate features in a way that does not break vcpkg upgrades? Ideally, vcpkg upgrade would continue with the upgrade even if a feature is gone (maybe with a message to the user). The quick solution is to uninstall ffmpeg, then upgrade vcpkg and reinstall ffmpeg.

**Comment by JackBoosY** [comment]
@mcmtroffaes  I think that's what we should do.

**Comment by skycommand** [comment]
I assume this can be safely closed.

**Comment by JackBoosY** [comment]
@skycommand No, the related vcpkg bug doesn't resolved yet.

**Comment by traumedy** [comment]
This issue occurred again with the `halide` port:
```
C:\vcpkg>vcpkg upgrade
Package halide does not have a target-opengl feature
Note: Updating vcpkg by rerunning bootstrap-vcpkg may resolve this failure.
```

**Comment by PhoebeHui** [comment]
For the vcpkg upgrade issue, we already have issue https://github.com/microsoft/vcpkg/issues/11482#issuecomment-631850698 to track.
