### ISSUE TITLE
 [opencv4:x64-windows] Building package failed

### ISSUE THREAD

**Issue by AsturTriala2021** [microsoft/vcpkg#18006]
A failure when it tries to install opencv-4.5.1
Error: Building package opencv4:x64-windows failed with: BUILD_FAILED

**Environment**
- OS: Windows10 Pro 19042.985
- Compiler: Microsoft Visual Studio Community 2019 Version 16.9.6

**To Reproduce**
To compile the last version of scripts/buildsystems/vcpkg.cmake into the visual studio.

**Failure logs** 
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/6508277/config-x64-windows-out.log)

**Comment by PhoebeHui** [comment]
@AsturTriala2021, this issue has been fixed, please get latest source and try again. See history tracking issue https://github.com/microsoft/vcpkg/issues/17973.
