### ISSUE TITLE
[OpenColorIO] update to 2.0.1

### ISSUE THREAD

**Issue by romainaugier** [microsoft/vcpkg#18004]
Library name: OpenColorIO

New version number: 2.0.1

https://github.com/AcademySoftwareFoundation/OpenColorIO

**Comment by JonLiu1993** [comment]
Wait for pr #19272 merged

**Comment by JonLiu1993** [comment]
@romainaugier ,OpenColorIO has been updated to 2.2.17, please update vcpkg to use it

**Comment by jixingcn** [comment]
> @romainaugier ,OpenColorIO has been updated to 2.2.17, please update vcpkg to use it

Not 2.2.17, should be 2.0.1

**Comment by JonLiu1993** [comment]
> > @romainaugier ,OpenColorIO has been updated to 2.2.17, please update vcpkg to use it
> 
> Not 2.2.17, should be 2.0.1

@jixingcn, sorry, I made a mistake, it should be 2.0.1
