### ISSUE TITLE
Support WinUI outputs

### ISSUE THREAD

**Issue by mattleibow** [microsoft/vcpkg#18017]
**Is your feature request related to a problem? Please describe.**
I am trying to build ANGLE for WinUI/ProjectReunion, but the generated project files are either Win32 or UWP. I know that WinUI is not a new platform as such, but the issue is that I want to generate Win32 projects, but using the UWP settings - and then have the WinUI nugets installed.

 - Microsoft.Windows.AbiWinRT
 - Microsoft.Windows.MidlRT
 - Microsoft.ProjectReunion

For ANGLE, I managed to get the libANGLE compiling using the things, but this was a manual edit of the project files - which are generated as Universal Windows.

I'll be honest, this is more a info finding issue because it might be the case that it is ANGLE's gn files that need to do this work. But it might not be. I am not super familiar with vcpkg and all the build things.

**Proposed solution**
Not sure if this is a new triplet or just an arg, but I would expect that there would be some way to generate a library that would work with WinUI types instead of the UWP, but not be UWP. I can understand if the code does not work - and I can fix that either as a path locally or in the upstream. For example, the changes to get libANGLE to compile was just a few small moving the namespaces from ABI::Windows::UI to ABI::Microsoft::UI.

**Describe alternatives you've considered**
I manually went into the vcxproj and made changes to install nugets and things, but this is not really useful in CI or anywhere.

**Additional context**

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. This should be a community triplet, and there are no update about this issue for a long time. If there are new process or change of this issue, please reopen this issue.
