### ISSUE TITLE
[Android][curl] Wrong zlib on android compilation 

### ISSUE THREAD

**Issue by talregev** [microsoft/vcpkg#18015]
Robert Schumacher Can I ask improvement of libcurl.pc when compile android?
pkg-config libcurl.pc --libs
-Llibcurl.pc/../../lib -lcurl -lc -lgcc -ldl -pthread libcurl.pc/../../lib/libssl.a libcurl.pc/../../lib/libcrypto.a /home/tal/boinc/3rdParty/android/android-ndk-r15c/platforms/android-16/arch-arm/usr/lib/libz.so

It give libz.so Although it compile libcurl.a with libz.a from vcpkg. Can we fix libcurl.pc that it will give the correct libz flag location? zlib.pc/../../lib/libz.a?

@ras0219-msft @ras0219 

---
Edit:
I find the problem that vcpkg find the zlib from the ndk instead the zlib inside vcpkg.

**Comment by talregev** [comment]
@JackBoosY Maybe you can also help? 
Maybe the issue is how the curl is compile. 
Maybe in android it find the libz that come with the ndk instead to take zlib that come with the ndk.
How I can force `find_package` to detect the zlib from vcpkg? 
https://github.com/curl/curl/blob/3085ccfae996bb0fa606d2c7bc6783dc15d76a30/CMakeLists.txt#L636
https://github.com/curl/curl/blob/3085ccfae996bb0fa606d2c7bc6783dc15d76a30/CMake/Macros.cmake#L116

**Comment by talregev** [comment]
Also why curl/control file was deleted? 
How curl know that he will compile with zlib? 
https://github.com/microsoft/vcpkg/commit/e6dcc079c81161786eb7b052209a2047e79f2c6c#diff-a6411f1fd1bac0e7c25451306467d99c12bccbe5a300bd10c208edfcae05ba7b

**Comment by dg0yt** [comment]
> Also why ports/curl/CONTROL file was deleted?

The deprecated CONTROL file has been replaced by vcpkg.json.

> How curl know that he will compile with zlib?

This controlled by configuration options in portfile.cmake, and by find_... commands in curl's own CMakeLists.txt. If the behaviour of the find commands isn't satisfying, there is some influence via options in the portfile.

**Comment by talregev** [comment]
@dg0yt Thank you for the info!
Can you teach me? How to compile curl with zlib from vcpkg? 
We can talk on discord if you like.

**Comment by dg0yt** [comment]
No discord on my side... 
I was already trying to look at the context. What you could do is: provide logs. In buildtrees/curl, there are "config-...-out.log" from the cmake configuration step. You will be able to find out which zlib it discovered.
curl uses plain `find_package(ZLIB)`, and vcpkg doesn't seem to provide any particular configuration hints. Seems to work well for plain linux, so why shouldn't it work for android?

**Comment by talregev** [comment]
Because for android there is another set of libraries like that come with ndk, and I think the vcpkg curl find the libz of ndk instead libz from vcpkg. Maybe for other user that ok, but for me, I want the program will stay up to date with the latest zlib.

**Comment by talregev** [comment]
I will search the logs now and upload it here, we can look at them together.

**Comment by dg0yt** [comment]
> Because for android there is another set of libraries like that come with ndk, and I think the vcpkg curl find the libz of ndk instead libz from vcpkg. Maybe for other user that ok, but for me, I want the program will stay up to date with the latest zlib.

Sure. A) My linux box comes with zlib, too. B) I must use a more recent zlib on android, too. I just don't use vcpkg for android yet.

**Comment by talregev** [comment]
[config-armv6-android-rel-out.log](https://github.com/microsoft/vcpkg/files/6526652/config-armv6-android-rel-out.log)
[config-armv6-android-dbg-out.log](https://github.com/microsoft/vcpkg/files/6526653/config-armv6-android-dbg-out.log)

**Comment by talregev** [comment]
```
-- Looking for dlopen in dl;-pthread;OpenSSL::SSL;OpenSSL::Crypto
-- Looking for dlopen in dl;-pthread;OpenSSL::SSL;OpenSSL::Crypto - found
-- Found ZLIB: /home/tal/boinc/3rdParty/android/android-ndk-r15c/platforms/android-16/arch-arm/usr/lib/libz.so (found version "1.2.11") 
```

The version is not correct.

**Comment by talregev** [comment]
How we can give hint for `find_package(ZLIB)` that will point out to vcpkg install library?

**Comment by talregev** [comment]
If you want me to provide more logs, I will happy to upload them here.

**Comment by dg0yt** [comment]
I don't think I can help you to dig deeper for NDK 15 armv6. 

The documentation for the ZLIB find module is: https://cmake.org/cmake/help/latest/module/FindZLIB.html
The key hook is ZLIB_ROOT, but for vcpkg you would need to deal with release and debug variants.
The ZLIB find module does just find_path for the header, and find_library for the lib. The source code is at
https://github.com/Kitware/CMake/blob/master/Modules/FindZLIB.cmake
It contains some variables which might be used for configuration, too (e.g. ZLIB_LIBRARY)

(Make sure that your cmake toolchain doesn't set one of these variables.)

**Comment by talregev** [comment]
maybe it does. 
What about `find_package hint path`. Can You tell me how I can give the current path of zlib as hint path?

**Comment by talregev** [comment]
https://stackoverflow.com/questions/49816206/cmake-find-package-specify-path

**Comment by dg0yt** [comment]
> find_package hint path

Read about \<PackageName>_DIR here:
https://cmake.org/cmake/help/latest/command/find_package.html#full-signature-and-config-mode
I don't see that there is a dir which provides cmake configuration for zlib in vcpkg.

**Comment by talregev** [comment]
for vcpkg there is a variable that tell me where is the current install/arm-android/lib of?

**Comment by talregev** [comment]
maybe it `${CURRENT_PACKAGES_DIR}/lib` ?

**Comment by talregev** [comment]
I will make a patch and let you know

**Comment by talregev** [comment]
[0001-fix-dependency-zlib.zip](https://github.com/microsoft/vcpkg/files/6526795/0001-fix-dependency-zlib.zip)

**Comment by talregev** [comment]
I will try it on my local curl android compilation

**Comment by talregev** [comment]
I take example from here:
https://github.com/microsoft/vcpkg/blob/7f1708740708b7fd912af5c0ade23a3b48712ce1/ports/qt5-base/portfile.cmake#L155-L156

**Comment by talregev** [comment]
@dg0yt 
I create this patch and it didn't work. Can you help?

```patch
From 60ccc12b04e4d81c01bad0b4cf58e86ba1aae48e Mon Sep 17 00:00:00 2001
From: Tal Regev 
Date: Sat, 22 May 2021 20:36:20 +0300
Subject: [PATCH] fix-dependency-zlib

---
 CMakeLists.txt | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)

diff --git a/CMakeLists.txt b/CMakeLists.txt
index 63944877a..0cdb4f2e8 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -635,7 +635,8 @@ check_library_exists("${CURL_LIBS}" dlopen "" HAVE_DLOPEN)
 set(HAVE_LIBZ OFF)
 set(HAVE_ZLIB_H OFF)
 set(USE_ZLIB OFF)
-optional_dependency(ZLIB)
+find_library(ZLIB NAMES z zlib PATHS "${CURRENT_INSTALLED_DIR}/lib" NO_DEFAULT_PATH)
+find_library(ZLIB NAMES z zlib zd zlibd PATHS "${CURRENT_INSTALLED_DIR}/debug/lib" NO_DEFAULT_PATH)
 if(ZLIB_FOUND)
   set(HAVE_ZLIB_H ON)
   set(HAVE_LIBZ ON)
-- 
2.28.0.windows.1

```

**Comment by talregev** [comment]
@dg0yt 
I think I fix this issue in #18092
Can you take a look?

**Comment by autoantwort** [comment]
Seems similar to #17163. What is the value of `CMAKE_FIND_ROOT_PATH`? So [this](https://github.com/microsoft/vcpkg/issues/17163#issuecomment-821909773) was the problem for me and [this](https://github.com/microsoft/vcpkg/issues/17163#issuecomment-821983844) possible solutions

**Comment by talregev** [comment]
@autoantwort I can print `CMAKE_FIND_ROOT_PATH` from profile.cmake and write it here.

**Comment by talregev** [comment]
@autoantwort from profile.cmake file the `CMAKE_FIND_ROOT_PATH` is empty.
I will try to see the value of `CMAKE_FIND_ROOT_PATH` from the CmakeLists.txt of lib curl.

**Comment by talregev** [comment]
@autoantwort 
CMAKE_FIND_ROOT_PATH=/home/tal/boinc/3rdParty/android/android-ndk-r15c/home/tal/boinc/3rdParty/android/vcpkg/installed/armv6-android/debug/home/tal/boinc/3rdParty/android/vcpkg/installed/armv6-android

It the same like in your issue, the `CMAKE_FIND_ROOT_PATH` if point out first for the ndk, then to vcpkg.
