### ISSUE TITLE
Build at lower than normal CPU priority

### ISSUE THREAD

**Issue by OlafvdSpek** [Microsoft/vcpkg#1802]
Would it be possible to build at lower than normal (CPU) priority such that performance of (foreground) processes isn't affected so much?

**Comment by alexkaratarakis** [comment]
This should already be the case, according to this:
https://github.com/Microsoft/vcpkg/blob/master/toolsrc/src/vcpkg_System.cpp#L141

**Comment by OlafvdSpek** [comment]
My PC felt sluggish while building but I guess that's due to other factors then.
