### ISSUE TITLE
[vcpkg.io] Add Links to Repository in Browse Packages

### ISSUE THREAD

**Issue by sclel016** [microsoft/vcpkg#18023]
****

**Is your feature request related to a problem? Please describe.**
It would be great if someone browsing the packages on vcpkg.io could easily click through to the relevant repository.

**Proposed solution**
Add a link to the hosted repository for each package.

**Describe alternatives you've considered**
Google the package name and click on the hosted repository

**Comment by JackBoosY** [comment]
Thanks for the suggestion! Can you please also open an issue in https://github.com/vcpkg/vcpkg.github.io ?

Thanks.

**Comment by sclel016** [comment]
Done, see new issue at  https://github.com/vcpkg/vcpkg.github.io/issues/50

**Comment by JackBoosY** [comment]
Close this issue since it was reported to github.io.
