### ISSUE TITLE
[New Port Request] EPANET

### ISSUE THREAD

**Issue by boinst** [microsoft/vcpkg#18020]
Library name: EPANET

Library description: EPANET is a hydraulic solver for modelling water networks. Originally developed and released by the United States EPA, it is now maintained by OWA.

Source repository URL: https://github.com/OpenWaterAnalytics/EPANET

Project homepage (if different from the source repository): http://wateranalytics.org/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

The build seems to be straightforward, I was hoping to contribute a pull request myself. Would it be welcome?

**Comment by boinst** [comment]
I'm stuck already. 

Following the new contributer documentation, my portfile has this code:

```
vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA
)
```

Which generates the cmake command line mentioned in the below error message:

```
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:146 (message):
    Command failed: C:/Code/boinst/vcpkg/downloads/tools/cmake-3.20.2-windows/cmake-3.20.2-windows-i386/bin/cmake.exe --build . --config Debug --target install -- /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /m
```


However the upstream repo wants cmake executed without `--target install`. i.e. just `cmake.exe --build . --config Debug`. How can I modify the cmake command line to omit "`--target install`"?

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
