### ISSUE TITLE
Error: Building package log4cplus:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by lineCode** [Microsoft/vcpkg#1803]
Package: log4cplus:x86-windows
Vcpkg version: 0.0.88-2017-09-09-3ef9df647299eeec7bcaf06aedb4281359e1a816

CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:43 (message):
    Command failed: D:/vcpkg/vcpkg/downloads/cmake-3.9.1-win32-x86/bin/cmake.exe;--build;.;--config;Release;--target;install;--;-v
    Working Directory: D:/vcpkg/vcpkg/buildtrees/log4cplus/x86-windows-rel
    See logs for more information:
      D:\vcpkg\vcpkg\buildtrees\log4cplus\package-x86-windows-rel-out.log
      D:\vcpkg\vcpkg\buildtrees\log4cplus\package-x86-windows-rel-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:49 (vcpkg_execute_required_process)
  ports/log4cplus/portfile.cmake:16 (vcpkg_install_cmake)
  scripts/ports.cmake:72 (include)

config-x86-windows-rel-err.log:
-- Generating build for Log4cplus version 1.2.1
CMake Warning:
  Manually-specified variables were not used by the project:

    WITH_UNIT_TESTS

package-x86-windows-rel-err.log:
ninja: fatal: CreateProcess: %1 is not a valid win32 application

**Comment by soshiant1992** [comment]
i have the same prob

**Comment by JackBoosY** [comment]
Hi @lineCode  @soshiant1992 , thanks for post this issue!
Build log4cplus looks fine in latest version, can you update vcpkg and repro it?
Thx.

**Comment by JackBoosY** [comment]
Please open a new issue if this is still a problem for you.
Thx.
