### ISSUE TITLE
can't automatic include .h file then i make a new triplets

### ISSUE THREAD

**Issue by libxengine** [microsoft/vcpkg#18036]
vcpkg.exe install openssl:x86-windows-mt
vcpkg integrate install

open vs2019 ..

#include <openssl/rsa.h>

int main()
{
 .. ....
}

compile 
fatal error C1083: cant open include file: “openssl/rsa.h”: No such file or directory

but openssl/rsa.h file is existed in D:\vcpkg\installed\x86-windows-mt\include\openssl 
Ver:2021.5.12

**Comment by JackBoosY** [comment]
Please run command `./vcpkg integrate project` also.

**Comment by libxengine** [comment]
o just too many protject that need to add.....

**Comment by JackBoosY** [comment]
@libxengine The `project` refers to the name of the option, not the name of your custom project.

**Comment by libxengine** [comment]
o yes. he said:i need to set up for every project in vcxproj
like this :
<PropertyGroup Label="Globals">
...
<VcpkgTriplet Condition="'$(Platform)'=='Win32'">x86-windows-mt</VcpkgTriplet>

**Comment by libxengine** [comment]
o whatever
i mean is i want debug use dynamic runtime library and release use static runtime library...
