### ISSUE TITLE
[New Port Request] AFNI

### ISSUE THREAD

**Issue by DougRogers** [microsoft/vcpkg#18030]
Library name: AFNI

Library description: Analysis of Functional NeuroImages

Source repository URL: https://github.com/afni/afni

Project homepage (if different from the source repository):

Suite of programs for looking at and analyzing MRI brain images. It comprises a suite of C, Python, R programs and shell scripts primarily developed for the analysis and display of multiple MRI modalities: anatomical, functional MRI (FMRI) and diffusion weighted (DW) data. It has graphical displays for both slice-wise and surface-based viewing

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
