### ISSUE TITLE
[New Port Request] ImageMagick

### ISSUE THREAD

**Issue by DougRogers** [microsoft/vcpkg#18038]
Library name: ImageMagick

Library description: Use ImageMagick® to create, edit, compose, or convert bitmap images. It can read and write images in a variety of formats (over 200) including PNG, JPEG, GIF, HEIC, TIFF, DPX, EXR, WebP, Postscript, PDF, and SVG. Use ImageMagick to resize, flip, mirror, rotate, distort, shear and transform images, adjust image colors, apply various special effects, or draw text, lines, polygons, ellipses and Bézier curves.

Source repository URL: https://github.com/ImageMagick

**Comment by SamuelMarks** [comment]
FYI: There is a port for https://github.com/microsoft/vcpkg/tree/master/ports/graphicsmagick which is derived from ImageMagick. So you might be able to use that to create an ImageMagick port.

**Comment by SamuelMarks** [comment]
FYI: There is a [port](https://github.com/microsoft/vcpkg/tree/master/ports/graphicsmagick) for [graphicsmagick](https://sourceforge.net/projects/graphicsmagick) which is derived from ImageMagick. So you might be able to use that to create an ImageMagick port.

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
