### ISSUE TITLE
Add option to show usage information for installed library.

### ISSUE THREAD

**Issue by Roy-Fokker** [microsoft/vcpkg#18053]
****

**Is your feature request related to a problem? Please describe.**
Currently in vcpkg there is no easy way to find usage information for an already installed library.
Especially when using manifest json file.

**Proposed solution**
It would be good to have some means to see this info. Screenshot 
![image](https://user-images.githubusercontent.com/11281115/119193039-08ef1100-ba4f-11eb-90af-7efa2b5d7552.png)

Something like this option could be added to vcpkg command options
```sh
vcpkg use <library name>
```
example
```sh
vcpkg use fmt
```
With output of this call printing information in above screenshot

**Describe alternatives you've considered**
I understand i can always repeat install command. 
But this command doesn't really work well when used with manifest json file. As it seem to install the library globally, which might not be desired by users.

**Another alternative** is to show this information on vcpkg.io. 
This would avoid having to add this option to vcpkg executable. Slightly less convenient but acceptable in my mind.

**Comment by JackBoosY** [comment]
Unfortunately, most of the usage is generated through the build process. If the port is not installed, the usage cannot be displayed explicitly.
For the installed ports, we first need to install them.

We're trying to add it in https://github.com/microsoft/vcpkg-tool/pull/82.

Duplcated to https://github.com/microsoft/vcpkg/issues/15242
