### ISSUE TITLE
cpprestsdk missing pplx threadpool

### ISSUE THREAD

**Issue by acceleratxr** [microsoft/vcpkg#18056]
**Describe the bug**
When installing the cpprestsdk package not pplx threadpool is not copied to the `installed/{triplet}/include` folder and is missing from the compiled library.

**Environment**
- OS: Windows, Linux
- Compiler: vs2019, clang, gcc

**To Reproduce**
1. ./vcpkg install cpprestsdk
2. Look at ./vcpkg/installed/{triplet}/include/pplx
3. Compile code with reference to threadpool.h functions

**Expected behavior**
All headers and symbols are present.

**Comment by PhoebeHui** [comment]
@acceleratxr, may be you need to add '#include "pplx/threadpool.h" to your project? could you provide us the repro code?

BTW, I can't repro this issue with CMake project 

1. ./vcpkg install cpprestsdk
2. ./vcpkg integrate install
3. Creat a test with following code:
```
#CMakeLists.txt
cmake_minimum_required(VERSION 3.0)
project(main)
add_executable(main main.cpp)
find_package(cpprestsdk CONFIG REQUIRED)
target_link_libraries(main PRIVATE cpprestsdk::cpprest cpprestsdk::cpprestsdk_zlib_internal cpprestsdk::cpprestsdk_boost_internal cpprestsdk::cpprestsdk_openssl_internal)
```
```
//main.cpp
#include "pplx/threadpool.h"
int main()
{ 
   return 0;
}
```
4.  cmake "-DCMAKE_TOOLCHAIN_FILE=/home/test/vcpkg/scripts/buildsystems/vcpkg.cmake" ..
5.  cmake  --build .

**Comment by PhoebeHui** [comment]
@acceleratxr, please reopen this issue and provide us the repro code if it still be a problem for you.
