### ISSUE TITLE
[New Port Request] xtensor-zarr

### ISSUE THREAD

**Issue by xanderdunn** [microsoft/vcpkg#18057]
Library name: xtensor-zarr

Library description: A library from the xtensor team to support storing n-dimensional tensors in the zarr local/cloud binary compressed format.

Source repository URL: https://github.com/xtensor-stack/xtensor-zarr

Project homepage (if different from the source repository):https://xtensor-zarr.readthedocs.io/en/latest/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
This is a new library (1 year old) from the same team that created the xtensor libraries that are already a part of vcpkg. vcpkg currently has ports for all of xtensor-zarr's dependencies except for [zarray](https://github.com/xtensor-stack/zarray)

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
