### ISSUE TITLE
[zstr] zstr.hpp can't include strict_fstream.hpp due to being installed inside include/zstr

### ISSUE THREAD

**Issue by dan9er** [microsoft/vcpkg#18067]
**Host Environment**
- OS: Windows 10
- Compiler: Clang 11

**To Reproduce**
1. `[...]/vcpkg$ ./vcpkg install zstr`
2. Create these files:
- CMakeLists.txt:
```cmake
add_executable(foo src/foo.cpp)

find_package(ZLIB REQUIRED)
find_path(ZSTR_INCLUDE_DIRS "zstr/strict_fstream.hpp")

target_link_libraries(foo PRIVATE ZLIB::ZLIB)
target_include_directories(foo PRIVATE ${ZSTR_INCLUDE_DIRS})
```
- src/foo.cpp:
```cpp
#include <zstr/zstr.hpp>

int main()
    {return 0;}
```
3. `[...]/build$ cmake .. -DCMAKE_TOOLCHAIN_FILE:FILEPATH=[...]/vcpkg/scripts/buildsystems/vcpkg.cmake`
4. `[...]/build$ cmake --build .`

**Failure logs** 
```
In file included from [...]/src/foo.cpp:1:
[...]/vcpkg/installed/x64-windows-static/include\zstr/zstr.hpp:15:10: error: 'strict_fstream.hpp' file not found with <angled> include; use "quotes" instead
#include <strict_fstream.hpp>
          ^
```

**Comment by dan9er** [comment]
Simply inserting `${SOURCE_PATH}/src/zstr.hpp` into here will fix this
https://github.com/microsoft/vcpkg/blob/a3db16a4475b963cacf0260068c497fb72c8f3c0/ports/zstr/portfile.cmake#L9-L12

**Comment by dan9er** [comment]
It appears zstr expects to be installed directly in `include/`, not `include/zstr/`. There's two fixes that could be made:

#### 1. Install directly into `include/`
Change this line:
https://github.com/microsoft/vcpkg/blob/a3db16a4475b963cacf0260068c497fb72c8f3c0/ports/zstr/portfile.cmake#L12
to:
```cmake
     DESTINATION ${CURRENT_PACKAGES_DIR}/include)
```
This is the simplest fix, although segmentation is lost. This may be an issue especially with `strict_fstream.hpp`.

#### 2. Patch includes to point inside `include/zstr/`
Prepend all of zstr's internal includes with `zstr/`. This keeps segmentation, but is more complicated. Plus, the contributing guidelines state to avoid patching whenever possible.

**Comment by dg0yt** [comment]
I think the following is the wrong approach:

> ```cmake
> find_path(ZSTR_INCLUDE_DIRS "zstr/strict_fstream.hpp")
> ```

because you will get the directory were "zstr/strict_fstream.hpp" is. But you seem to need the directory where "strict_fstream.hpp" is. How about the following:

```cmake
find_path(ZSTR_INCLUDE_DIRS "zstr.hpp" PATH_SUFFIXES "zstr")
```
(Note: the public header, not the implementation detail.)

Then you can also use

```c
#include <zstr.hpp>
```

**Comment by dan9er** [comment]
@dg0yt 
> I think the following is the wrong approach:
> 
> > ```cmake
> > find_path(ZSTR_INCLUDE_DIRS "zstr/strict_fstream.hpp")
> > ```

That is the CMake line vcpkg tells users to put in their CMakeLists (5568f110b509a9fd90711978a7cb76bae75bb092):
```
PS C:\Users\dan9e\vcpkg> .\vcpkg.exe install zstr
Computing installation plan...
The following packages will be built and installed:
    zstr[core]:x64-windows-static -> 1.0.4
Detecting compiler hash for triplet x64-windows-static...
Using cached binary package: C:\Users\dan9e\AppData\Local\vcpkg\archives\87\8719da0297c06d5457e816a72ee405477de695bb.zipStarting package 1/1: zstr:x64-windows-static
Building package zstr[core]:x64-windows-static...
Building package zstr[core]:x64-windows-static... done
Installing package zstr[core]:x64-windows-static...
Installing package zstr[core]:x64-windows-static... done
Elapsed time for package zstr:x64-windows-static: 58.23 ms

Total elapsed time: 10.75 s

The package zstr:x64-windows-static is header only and can be used from CMake via:

    find_path(ZSTR_INCLUDE_DIRS "zstr/strict_fstream.hpp")
    target_include_directories(main PRIVATE ${ZSTR_INCLUDE_DIRS})
```
Is there a way to change this message to the one you've mentioned?

**Comment by dg0yt** [comment]
> Is there a way to change this message to the one you've mentioned?

AFAIU this message is auto-generated in newer versions of the vcpkg tool. But I don't think the tool can know the canonical use. It doesn't even know the main include.

The portfile might install a message with the filepath `share/${PORT}/usage`.

Could you verify that my proposal works?
