### ISSUE TITLE
[zlib 1.2.11] update to [zlib-ng 2.0.3]

### ISSUE THREAD

**Issue by JoergAtGithub** [microsoft/vcpkg#18062]
The original zlib from https://github.com/madler/zlib (zlib.net) is no longer maintained. All the development moved to https://github.com/zlib-ng/zlib-ng . Please update the package to the latest release 2.0.3.

The version 2.x.x of zlib is much faster (more than factor 2x in most cases) and therefore saves a lot of energy for computition power. The more applications use 2.x.x of zlib, the higher the world wide energy savings.
Furthermore the CMake setup is improved a lot since version 1.2.11.

**Comment by luncliff** [comment]
### Similar Issue?
* #17101 (minizip-ng)
