### ISSUE TITLE
[flashlight-cpu] build failure

### ISSUE THREAD

**Issue by SKRohit** [microsoft/vcpkg#18064]
**Host Environment**
- OS: Ubuntu 20.04.2 LTS
- Compiler: gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

**To Reproduce**
`./vcpkg install flashlight-cpu`

**Failure logs** 
Computing installation plan...
The following packages will be built and installed:
flashlight-cpu[core,fl]:x64-linux -> 0.3#1
Detecting compiler hash for triplet x64-linux...
Could not locate cached archive: /home/skrrohit/.cache/vcpkg/archives/7a/7a2dc37ebb8421a968bf31f3f3e288f81b4352c1.zip
Starting package 1/1: flashlight-cpu:x64-linux
Building package flashlight-cpu[core,fl]:x64-linux...
-- Using cached /home/skrrohit/my_repos/projects/vcpkg/downloads/flashlight-flashlight-626914e79073c5547513de649af706f7e2b796ad.tar.gz
-- Cleaning sources at /home/skrrohit/my_repos/projects/vcpkg/buildtrees/flashlight-cpu/src/f7e2b796ad-c1bedb72d5.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/skrrohit/my_repos/projects/vcpkg/downloads/flashlight-flashlight-626914e79073c5547513de649af706f7e2b796ad.tar.gz
-- Using source at /home/skrrohit/my_repos/projects/vcpkg/buildtrees/flashlight-cpu/src/f7e2b796ad-c1bedb72d5.clean
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
CMake Error at scripts/cmake/vcpkg_fixup_cmake_targets.cmake:95 (message):

'/home/skrrohit/my_repos/projects/vcpkg/packages/flashlight-cpu_x64-linux/debug/share/flashlight-cpu'
does not exist.
Call Stack (most recent call first):
ports/flashlight-cpu/portfile.cmake:47 (vcpkg_fixup_cmake_targets)
scripts/ports.cmake:141 (include)

Error: Building package flashlight-cpu:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with ./vcpkg update, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
Package: flashlight-cpu:x64-linux
Vcpkg version: 2021-05-05-unknownhash

**Additional context**
Above error is coming because compiler is looking for cmake files in the folder `/home/skrrohit/my_repos/projects/vcpkg/packages/flashlight-cpu_x64-linux/debug/share/flashlight-cpu` but when I checked the location cmake files were present in `home/skrrohit/my_repos/projects/vcpkg/packages/flashlight-cpu_x64-linux/share/flashlight-cpu` so I copied these files to `home/skrrohit/my_repos/projects/vcpkg/packages/flashlight-cpu_x64-linux/debug/share/flashlight-cpu` and flashlight-cpu built successfully. But I  am geeting CMake Error when I am trying to use `flashlight` in my own code. The CMake Error is below: 

```
CMake Error at /home/skrrohit/my_repos/projects/vcpkg/scripts/buildsystems/vcpkg.cmake:664 (_add_executable):
  Target "arr_exe" links to target "flashlight::flashlight" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:8 (add_executable)
```
The contents of the corresponding CMakeLists.txt file is:

```
cmake_minimum_required(VERSION 3.10)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

find_package(flashlight CONFIG REQUIRED)

add_executable(arr_exe main.cpp)

target_link_libraries(arr_exe PRIVATE flashlight::flashlight)
```

**Comment by JackBoosY** [comment]
Confirmed.
