### ISSUE TITLE
[New Port Request] libldap

### ISSUE THREAD

**Issue by dimdin** [microsoft/vcpkg#18072]
Library name: OpenLDAP libldap and its dependency liblber

Library description: Lightweight Directory Access Protocol API

Source repository URL:
https://git.openldap.org/openldap/openldap/-/tree/master/libraries/libldap
https://git.openldap.org/openldap/openldap/-/tree/master/libraries/liblber

Project homepage (if different from the source repository):
https://www.openldap.org

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
https://man7.org/linux/man-pages/man3/ldap.3.html
OpenLDAP libldap supports replication as specified in RFC 4533 (syncrepl).

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
