### ISSUE TITLE
[pthreads:x86-windows / pthreads:x64-windows] build failure

### ISSUE THREAD

**Issue by Leonzen** [microsoft/vcpkg#18085]
**Host Environment**
- OS: Windows 10
- Compiler: 2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9

**To Reproduce**
`./vcpkg install pthreads`

**Failure logs** 
CMake Error: Problem with archive_write_finish_entry(): Can't restore time
CMake Error: Problem extracting tar: D:/TOOLS/vcpkg/downloads/pthreads4w-code-v3.0.0.zip

Call Stack (most recent call first):
  scripts/cmake/vcpkg_extract_source_archive.cmake:46 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_extract_source_archive_ex.cmake:118 (vcpkg_extract_source_archive)
  scripts/cmake/vcpkg_from_sourceforge.cmake:229 (vcpkg_extract_source_archive_ex)
  ports/pthreads/portfile.cmake:21 (vcpkg_from_sourceforge)
  scripts/ports.cmake:141 (include)

**Comment by JackBoosY** [comment]
It's a cmake bug, see https://gitlab.kitware.com/cmake/cmake/-/issues/19132.

Please track this issue in https://github.com/microsoft/vcpkg/issues/17489.
