### ISSUE TITLE
[cairo:x86-windows-static] build failure

### ISSUE THREAD

**Issue by jpcima** [microsoft/vcpkg#18082]
**Host Environment**
- OS: GH Actions windows-2019
- Compiler: Visual Studio 2019

**To Reproduce**
`./vcpkg install cairo:x86-windows-static`

**Failure logs** 
`error LNK2019: unresolved external symbol __imp__cairo_script_interpreter_destroy referenced in function _main`
(many of these, see log file)
[7.txt](https://github.com/microsoft/vcpkg/files/6528539/7.txt)

**Additional context**
vcpkgGitCommitId: a3db16a4475b963cacf0260068c497fb72c8f3c0
It fails compiling the executables under static library configuration. It looks like as if it tries linking the DLL symbols.
Also I'm not interested in building these programs, only library, I'd skip these if possible.

**Comment by brad-anderson** [comment]
This was caused by the cairo version update #17620

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Now `cairo:x86-windows-static` can install succeed on latest VCPKG. If it is still an issue, please reopen this issue.
