### ISSUE TITLE
[gtkmm] build failure

### ISSUE THREAD

**Issue by acromarcopolo** [microsoft/vcpkg#18084]
**Host Environment**
- OS: macOS Big Sur 11.3.1
- Compiler: Apple clang version 12.0.5 (clang-1205.0.22.9)
Target: x86_64-apple-darwin20.4.0
Thread model: posix

**To Reproduce**
`./vcpkg install gtk`
or
`./vcpkg install gtkmm`

**Failure logs** 
-- Configuring x64-osx-dbg
-- Configuring x64-osx-rel
CMake Error at scripts/cmake/vcpkg_configure_make.cmake:590 (message):
  fontconfig requires autoconf from the system package manager (example:
  "sudo apt-get install autoconf")
Call Stack (most recent call first):
  ports/fontconfig/portfile.cmake:26 (vcpkg_configure_make)
  scripts/ports.cmake:141 (include)

Error: Building package fontconfig:x64-osx failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: fontconfig:x64-osx
  Vcpkg version: 2021-05-05-unknownhash

**Additional context**
calling g++ or gcc --version indicates that clang is actually called.
should i install g++ with vcpkg?  will that possibly have unexpected consequences?  
I am using Visual Studio Code, and have created the vcpkg folder in my workspace

**Comment by NancyLi1013** [comment]
Hi @acromarcopolo 
Thanks for posting this issue.

```
CMake Error at scripts/cmake/vcpkg_configure_make.cmake:590 (message):
fontconfig requires autoconf from the system package manager (example:
"sudo apt-get install autoconf")
Call Stack (most recent call first):
ports/fontconfig/portfile.cmake:26 (vcpkg_configure_make)
scripts/ports.cmake:141 (include)
```
Can you try to install `autoconf` and then rebuild this?

**Comment by acromarcopolo** [comment]
hi Nancy,
see below, should i submit a new issue?
now the error for  $ ./vcpkg install gtk  is:

...

-- Configuring x64-osx-rel

-- Generating configure for x64-osx

CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105
(message):

    Command failed: /usr/local/bin/autoreconf -vfi

    Working Directory:
/Users/marcbauchet/Dropbox/projects/RandomBits/vcpkg/buildtrees/fontconfig/src/75c13b2421-12bdc6f9c0.clean/

    Error code: 2

    See logs for more information:


/Users/marcbauchet/Dropbox/projects/RandomBits/vcpkg/buildtrees/fontconfig/autoconf-x64-osx-err.log


Call Stack (most recent call first):

  scripts/cmake/vcpkg_configure_make.cmake:600
(vcpkg_execute_required_process)

  ports/fontconfig/portfile.cmake:26 (vcpkg_configure_make)

  scripts/ports.cmake:141 (include)



Error: Building package fontconfig:x64-osx failed with: BUILD_FAILED

Please ensure you're using the latest portfiles with `./vcpkg update`, then

submit an issue at https://github.com/Microsoft/vcpkg/issues including:

  Package: fontconfig:x64-osx

  Vcpkg version: 2021-05-05-unknownhash


Additionally, attach any relevant sections from the log files above.

NOTE 1:
does it make a difference WHERE I run vcpkg?  I wasn't quite sure from the
documentation.
In this case, this ./vcpkg install gtk was run in the directory vcpkg/ which
is where my VSCode .code-workspace and source files are

NOTE 2:
 not sure if that's an issue, but before that there are some 17 lines of
this:

Could not locate cached archive:
/Users/marcbauchet/.cache/vcpkg/archives/1c/1c8cb7de0f682c3f9233bd5de49934902c36d902.zip

Could not locate cached archive:
/Users/marcbauchet/.cache/vcpkg/archives/85/851bbe7e50a91bc622f782155b0717591947ffc2.zip

Could not locate cached archive:
/Users/marcbauchet/.cache/vcpkg/archives/3d/3dbda4b3e6c936aa9dcbc596d6d062e5cfd3f4b0.zip

....

cheers,
marc

Marc Bauchet
Mobile & WhatsApp: +33 (0)7 57 42 68 97
Mobile: +49 (0)176 2873 1028

**Comment by NancyLi1013** [comment]
Have you solved the original problem via `brew install autoconf`?

On Linux, we generally use `apt-get `to install system libraries, on macOS, it might be `brew`.
Please post the error info here when you install `gtk`.

**Comment by dg0yt** [comment]
When it comes to port fontconfig, you might also need to install brew`s gettext.

**Comment by acromarcopolo** [comment]
still stuck.  so i filed https://github.com/microsoft/vcpkg/issues/18118

**Comment by NancyLi1013** [comment]
Still stuck, but I think the original issue should be solved now.

```
CMake Error at scripts/cmake/vcpkg_configure_make.cmake:590 (message):
fontconfig requires autoconf from the system package manager (example:
"sudo apt-get install autoconf")
```

**Comment by acromarcopolo** [comment]
indeed, thanks.

**Comment by acromarcopolo** [comment]
indeed, thanks.
