### ISSUE TITLE
[darknet] build failure

### ISSUE THREAD

**Issue by stephanecharette** [microsoft/vcpkg#18081]
**Host Environment**
- OS: Windows 10
- Compiler: Visual Studio 2019

**To Reproduce**
`vcpkg.exe install opencv[contrib,core,dnn,ffmpeg,jpeg,png,quirc,tiff,webp]:x64-windows darknet[opencv-base]:x64-windows`

**Failure logs** 

```
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: C:/src/vcpkg/packages/darknet_x64-windows/tools/darknet/scripts/download_weights.ps1
-- To download weight files, please go to C:/src/vcpkg/installed/x64-windows/tools/darknet/scripts and run ./download_weights.ps1
-- Installing: C:/src/vcpkg/packages/darknet_x64-windows/share/darknet/copyright
-- Performing post-build validation
The following EXEs were found in /bin or /debug/bin. EXEs are not valid distribution targets.

    C:/src/vcpkg/packages/darknet_x64-windows/bin/uselib_track.exe

The following EXEs were found in /bin or /debug/bin. EXEs are not valid distribution targets.

    C:/src/vcpkg/packages/darknet_x64-windows/debug/bin/uselib_track.exe

Found 2 error(s). Please correct the portfile:
    C:\src\vcpkg\ports\darknet\portfile.cmake
-- Performing post-build validation done
Error: Building package darknet:x64-windows failed with: POST_BUILD_CHECKS_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: darknet:x64-windows
  Vcpkg version: 2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9
```

**Comment by JackBoosY** [comment]
cc @cenit

**Comment by stephanecharette** [comment]
Why was the title changed to OpenCV?  Isn't the error with Darknet?

**Comment by cenit** [comment]
yes it's with darknet. But still, it's related to opencv! It seems that newer opencv versions moved a module that was available only with CUDA extensions also in the normal distribution, and so darknet is able to build also what it wasn't supposed to be able to.
I will investigate if that's the case and open a PR

**Comment by cenit** [comment]
in any case @JonLiu1993 please revert title change

**Comment by cenit** [comment]
will be fixed upstream extremely soon, and I will open a PR with an update here just after the fix lands upstream

**Comment by cenit** [comment]
fixed upstream. Tomorrow i will add a PR to update version here

**Comment by stephanecharette** [comment]
In the meantime, is there a way for me to get past this error locally?

**Comment by stephanecharette** [comment]
The thing I don't understand is I'm trying to use vcpkg in C:\src\vcpkg.  But the error message I'm getting is about C:\src\darknet, which should be unrelated.

My PWD:  C:\src\vcpkg

The error message:

The following EXEs were found in /bin or /debug/bin. EXEs are not valid distribution targets.

    C:/src/darknet/vcpkg/packages/darknet_x64-windows/bin/uselib_track.exe

The following EXEs were found in /bin or /debug/bin. EXEs are not valid distribution targets.

    C:/src/darknet/vcpkg/packages/darknet_x64-windows/debug/bin/uselib_track.exe

Found 2 error(s). Please correct the portfile:
    C:\src\darknet\vcpkg\ports\darknet\portfile.cmake

Why is vcpkg attempting to use C:\src\darknet, and how does it even know that directory exists?

**Comment by cenit** [comment]
you still have the VCPKG_ROOT env variable enabled from the build.ps1 which you ran before (see chat we had on discord).
You didn't reset your powershell, so your active vcpkg is still the "deleted" one, no matter how many times you clone it.

vcpkg uses this env variable to select one preferred installation
