### ISSUE TITLE
[windows, embree] find_package failure with embree 

### ISSUE THREAD

**Issue by n-taka** [microsoft/vcpkg#18096]
**Describe the bug**
When I try to find embree by using `find_package(embree 3 CONFIG REQUIRED)`, cmake fails to find it.

**Environment**
- OS: Windows 
- Compiler: Visual Studio Community 2019 16.9.6
- Build system: cmake 3.20.0

**To Reproduce**
Directory tree
```
vcpkg/
example/
  CMakeLists.txt
  main.cpp
```
main.cpp
```
#include <iostream>

int main()
{
    std::cout << "Hello world!" << std::endl;
    return 0;
}
```
CMakeLists.txt
```
cmake_minimum_required(VERSION 3.14)

project(example)

find_package(embree 3 CONFIG REQUIRED)

add_executable(example main.cpp)
```
1. cd vcpkg
2. ./bootstrap-vcpkg.sh
3. ./vcpkg.exe install --triplet=x64-windows embree3
4. cd ../example
5. cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake
6. **failure happens**

**Expected behavior**
cmake successfully finds embree3 finishes configuration

**Failure logs** 
```
KazutakaNakashima@taka-skull ~/Documents/git/example
$ cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19043.
-- The C compiler identification is MSVC 19.28.29915.0
-- The CXX compiler identification is MSVC 19.28.29915.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at C:/Users/KazutakaNakashima/Documents/git/vcpkg/installed/x64-windows/share/embree/embree-config.cmake:72 (INCLUDE):
  INCLUDE could not find requested file:

    C:/Users/KazutakaNakashima/Documents/git/vcpkg/installed/lib/cmake/embree-3.12.2/embree-targets.cmake
Call Stack (most recent call first):
  C:/Users/KazutakaNakashima/Documents/git/vcpkg/scripts/buildsystems/vcpkg.cmake:861 (_find_package)
  CMakeLists.txt:5 (find_package)


-- Configuring incomplete, errors occurred!
See also "C:/Users/KazutakaNakashima/Documents/git/example/build/CMakeFiles/CMakeOutput.log".
```

**Additional context**
- As error log says, `C:/Users/KazutakaNakashima/Documents/git/vcpkg/installed/x64-windows/share/embree/embree-config.cmake:72 (INCLUDE):` try to include a file that doesn't exit. I guess paths `...  ${EMBREE_ROOT_DIR}/lib/cmake/embree-3.12.2 ... ` in `C:/Users/KazutakaNakashima/Documents/git/vcpkg/installed/x64-windows/share/embree/embree-config.cmake` are incorrect.
- When I try manifests, cmake also fails configuring embree3.

**Comment by NancyLi1013** [comment]
Hi @n-taka 

Thanks for posting this issue. I submitted a PR #18146 to fix this issue. Can you please help test if this can work fine for you?

**Comment by n-taka** [comment]
Hi @NancyLi1013 

Thank you for quickly fixes the issue. I tested your PR, and it works fine for me.
