### ISSUE TITLE
How do I include installed package in CMakeLists.txt?

### ISSUE THREAD

**Issue by li3793** [microsoft/vcpkg#18095]
OS: Mac OS 10.15, Ubuntu 20.04
cmake version: 3.20
vcpkg version: 2021-05-05

Built vcpkg successfully in both MacOS and Ubuntu, then install the azure-core library via
./vcpkg install azure-core-cpp

again, everything went fine.

Create a test cmake file with this line

find_package(azure-core-cp CONFIG REQUIRED)

when I ran cmake, got this  

  Could not find a package configuration file provided by "azure-core-cpp"
  with any of the following names:

    azure-core-cppConfig.cmake
    azure-core-cpp-config.cmake

  Add the installation prefix of "azure-core-cpp" to CMAKE_PREFIX_PATH or set
  "azure-core-cpp_DIR" to a directory containing one of the above files.  If
  "azure-core-cpp" provides a separate development package or SDK, be sure it
  has been installed.

I did include the this in my VS Code Settings.json
  "cmake.configureSettings": {
      "CMAKE_TOOLCHAIN_FILE": "/Volumes/DATA/proj/c/vcpkg/scripts/buildsystems/vcpkg.cmake"
    }
and also tried

cmake .. -DCMAKE_TOOLCHAIN_FILE="/Volumes/DATA/proj/c/vcpkg/scripts/buildsystems/vcpkg.cmake"

got the same error.

Did I miss anything? Anybody ran into similar issues?

Thanks

**Comment by gvanem** [comment]
Edit you `$CMAKE_MODULE_PATH` to include the path where `vcpkg` put those `azure-core-*.cmake` files.
The `share` sub-dir normally. In my case, a:
```
set CMAKE_MODULE_PATH=%VCPKG_ROOT%\installed\x86-windows\share
```
should do it. But I do not use Cmake....

**Comment by li3793** [comment]
thanks gvanem, turn out setting CMAKE_MODULE_PATH didn't help.

Finally figure it out, have to set CMAKE_PREFIX_PATH, something like

list(APPEND CMAKE_PREFIX_PATH "Absolute Path to azure-core-cpp cmake file")

after that, no more error.
