### ISSUE TITLE
Use latest VS version

### ISSUE THREAD

**Issue by ZeroCrunch** [Microsoft/vcpkg#181]
If I'm porting some existing software that was targeted to VS2008, is there a way for me to tell vcpkg to upgrade the *.sln and *.vcproj files to use VS2015?

Or do I need to make a patch again?

Thanks.

**Comment by barcharcraz** [comment]
devenv /upgrade may help. Also consider writing a cake based build system for the package. It's sometimes easier

**Comment by ZeroCrunch** [comment]
Sorry, do you mean avoid using the vcpkg_common_functions functions?

**Comment by barcharcraz** [comment]
Well you can run upgrade as a separate step (vcpkg_execute_required_process I think) it does create a mess of backups though. Maybe there's a switch to disable that.

I just mean make a CMakeLists.txt for the project and copy it to the source directory before you configure. I'll submit a pr for London where I do exactly that in a few hours (it uses an old vc solution as well)

**Comment by ras0219-msft** [comment]
If you want to use the `.sln` files, patches are generally the most robust option for fixing them; it's common that the upgraded `.vcxproj` files will still need tweaking so you'll need a patch anyway.

Git makes it very easy to create patches; you generally just need to check your "intial" state into git, then make whatever changes you want (for example, using the IDE to upgrade the projects), then use `git diff` or `git format-patch`.

Here are some links that might help:
https://ariejan.net/2009/10/26/how-to-create-and-apply-a-patch-with-git/
https://git-scm.com/docs/git-format-patch

**Comment by adam4813** [comment]
Which particular software are you porting maybe that can help us guide you better?

**Comment by ZeroCrunch** [comment]
It's Python 2.7.9.

**Comment by ras0219-msft** [comment]
Closing assuming this question has been answered fully.
