### ISSUE TITLE
[libheif] Fix static linking

### ISSUE THREAD

**Issue by Ziriax** [microsoft/vcpkg#18107]
**Is your feature request related to a problem? Please describe.**

When I created a DLL (Windows) and SO (Linux) that statically linked to `libheif` and `libde265`, I got a lot of linker errors on Windows, or `library not found` when running on Linux.

To fix this, I had to patch the `CMakeLists.txt` of both `libde265` and `libheif` as follows:

For `libde265`:

```patch
 option(BUILD_SHARED_LIBS "Build shared library" ON)
-if(NOT BUILD_SHARED_LIBS)
+if(BUILD_SHARED_LIBS)
+  add_definitions(-DLIBDE265_EXPORTS)
+else()
   add_definitions(-DLIBDE265_STATIC_BUILD)
 endif()
```

For `libheif`:
```patch
-target_compile_definitions(heif
+# Enable static linking when building from vcpkg
+if(NOT BUILD_SHARED_LIBS)
+    target_compile_definitions(heif
+                               PUBLIC
+                                LIBHEIF_STATIC_BUILD
+                                LIBDE265_STATIC_BUILD)
+else()
+    target_compile_definitions(heif
                            PUBLIC
                                LIBHEIF_EXPORTS
                                HAVE_VISIBILITY)
+endif()
 
 if(LIBDE265_FOUND)
     target_compile_definitions(heif PRIVATE HAVE_LIBDE265=1)
```

With these patches, static linking works and runs fine. However, the Linux SO is 4 times larger than the Windows DLL; I haven't figured out why this is (maybe unreachable code is not aggressively removed on Linux)

**Proposed solution**

Apply the above patches to fix the static linking problems.

**Additional context**

On Windows, I got linker errors like:
```log
Creating library Release\eXpress.Imaging.Heif.Native.lib and object Release\eXpress.Imaging.Heif.Native.exp
heif.lib(heif_decoder_libde265.cc.obj) : error LNK2019: unresolved external symbol __imp_de265_get_version referenced in function "char const * __cdecl libde265_plugin_name(void)" (?libde265_plugin_name@@YAPEBDXZ)
```

I also reported the issue [here](https://github.com/strukturag/libheif/issues/513)

**I can provide a PR if you feel the patches above are appropriate**

**Comment by Ziriax** [comment]
This could also fix #13354

**Comment by Ziriax** [comment]
[This is my fork](  https://github.com/Ziriax/vcpkg)

I also upgraded to newer versions in this fork

**Comment by NancyLi1013** [comment]
Hi @Ziriax 
Thanks for posting this issue.
 
Can you provide the steps to repro this issue? Seems you didn't use official triplets to build.

If possible, you can submit a PR to fix this.

**Comment by Ziriax** [comment]
Initially I just used the official triplets `x64-windows-static` and `x64-linux`. I was just experimenting with fully static linking on Linux, e.g. also statically linking the CRT library, so I tried these overlays. 

I'll provide minimum example.

**Comment by Ziriax** [comment]
I've made a tiny demo the reproduces the problem in [this repository](https://github.com/Ziriax/heif-static-test)

See the `README.md` on how to run it, showing both the problem and the fix.

I only showed the problem on Windows for now, if needed I can try Linux and MacOS too.

**Comment by NancyLi1013** [comment]
Thanks for your further investigation. Looking forward to your good news.

**Comment by JackBoosY** [comment]
Hi guys, can anyone test whether https://github.com/microsoft/vcpkg/pull/22818 fix this issue?

**Comment by dg0yt** [comment]
> Hi guys, can anyone test whether [#22818](https://github.com/microsoft/vcpkg/pull/22818) fix this issue?

The answer is no. https://github.com/microsoft/vcpkg/pull/46317
