### ISSUE TITLE
fontconfig:x64-linux failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by fldx** [microsoft/vcpkg#18105]
**Host Environment**
- OS: [Linux.]
- Compiler: revision

**To Reproduce**

`./vcpkg install cairo`

**Failure logs** 
```
Computing installation plan...
The following packages will be built and installed:
    cairo[core,fontconfig,freetype]:x64-linux -> 1.17.4#1
  * fontconfig[core]:x64-linux -> 2.13.1#7
  * lzo[core]:x64-linux -> 2.10#6
  * pixman[core]:x64-linux -> 0.40.0
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-linux...
Could not locate cached archive: /home/dev/.cache/vcpkg/archives/8f/8f780878876c45b6a813f7792e1d74c899d5c7a9.zip
Could not locate cached archive: /home/dev/.cache/vcpkg/archives/32/3238886b407dff30ec72081629bd6211845ecd6d.zip
Could not locate cached archive: /home/dev/.cache/vcpkg/archives/8d/8d8cc41ec3213ce8d67fadf513878119259dd246.zip
Could not locate cached archive: /home/dev/.cache/vcpkg/archives/c7/c73de3f332fbb7f9bc01c14bd7fe1ba2556fd7be.zip
Starting package 1/4: fontconfig:x64-linux
Building package fontconfig[core]:x64-linux...
-- Using cached /home/dev/vcpkg/downloads/fontconfig-fontconfig-844d8709a1f3ecab45015b24b72dd775c13b2421.tar.gz
-- Cleaning sources at /home/dev/vcpkg/buildtrees/fontconfig/src/75c13b2421-12bdc6f9c0.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/dev/vcpkg/downloads/fontconfig-fontconfig-844d8709a1f3ecab45015b24b72dd775c13b2421.tar.gz
-- Applying patch remove_tests.patch
-- Applying patch build.patch
-- Applying patch build2.patch
-- Applying patch disable-install-data.patch
-- Applying patch macos_arm_fccache.patch
-- Using source at /home/dev/vcpkg/buildtrees/fontconfig/src/75c13b2421-12bdc6f9c0.clean
CMake Error at scripts/cmake/vcpkg_find_acquire_program.cmake:535 (message):
  Could not find gperf.  Please install it via your package manager.
Call Stack (most recent call first):
  ports/fontconfig/portfile.cmake:22 (vcpkg_find_acquire_program)
  scripts/ports.cmake:141 (include)


Error: Building package fontconfig:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: fontconfig:x64-linux
  Vcpkg version: 2021-05-05-unknownhash

Additionally, attach any relevant sections from the log files above.
```

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by JackBoosY** [comment]
```
  Could not find gperf.  Please install it via your package manager.
```

**Comment by fldx** [comment]
./vcpkg install cairo
Computing installation plan...
The following packages will be built and installed:
    cairo[core,fontconfig,freetype]:x64-linux -> 1.17.4#1
  * fontconfig[core]:x64-linux -> 2.13.1#7
  * lzo[core]:x64-linux -> 2.10#6
  * pixman[core]:x64-linux -> 0.40.0
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-linux...
Could not locate cached archive: /home/dev/.cache/vcpkg/archives/80/80772d1a235cda1d756ed182f55f552372050026.zip
Could not locate cached archive: /home/dev/.cache/vcpkg/archives/32/3238886b407dff30ec72081629bd6211845ecd6d.zip
Could not locate cached archive: /home/dev/.cache/vcpkg/archives/07/070ed7efe76cd3ba6895e301c97320461f1c51df.zip
Could not locate cached archive: /home/dev/.cache/vcpkg/archives/75/75968dcb70dd4bc0a9a8f763f24a9f992b638ca0.zip
Starting package 1/4: fontconfig:x64-linux
Building package fontconfig[core]:x64-linux...
-- Using cached /home/dev/vcpkg/downloads/fontconfig-fontconfig-844d8709a1f3ecab45015b24b72dd775c13b2421.tar.gz
-- Cleaning sources at /home/dev/vcpkg/buildtrees/fontconfig/src/75c13b2421-12bdc6f9c0.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/dev/vcpkg/downloads/fontconfig-fontconfig-844d8709a1f3ecab45015b24b72dd775c13b2421.tar.gz
-- Applying patch remove_tests.patch
-- Applying patch build.patch
-- Applying patch build2.patch
-- Applying patch disable-install-data.patch
-- Applying patch macos_arm_fccache.patch
-- Using source at /home/dev/vcpkg/buildtrees/fontconfig/src/75c13b2421-12bdc6f9c0.clean
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Generating configure for x64-linux
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
    Command failed: /usr/bin/autoreconf -vfi
    Working Directory: /home/dev/vcpkg/buildtrees/fontconfig/src/75c13b2421-12bdc6f9c0.clean/
    Error code: 1
    See logs for more information:
      /home/dev/vcpkg/buildtrees/fontconfig/autoconf-x64-linux-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:607 (vcpkg_execute_required_process)
  ports/fontconfig/portfile.cmake:26 (vcpkg_configure_make)
  scripts/ports.cmake:141 (include)


Error: Building package fontconfig:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: fontconfig:x64-linux
  Vcpkg version: 2021-05-05-unknownhash

Additionally, attach any relevant sections from the log files above.

**Comment by fldx** [comment]
`/home/dev/vcpkg/buildtrees/fontconfig/autoconf-x64-linux-err.log` 内容:

autoreconf: Entering directory `.'
autoreconf: running: autopoint --force
Can't exec "autopoint": 没有那个文件或目录 at /usr/share/autoconf/Autom4te/FileUtils.pm line 345.
autoreconf: failed to run autopoint: No such file or directory
autoreconf: autopoint is needed because this package uses Gettext

**Comment by JackBoosY** [comment]
Please install `autotool` using apt or yum.

**Comment by fldx** [comment]
安装 autopoint 后还有报错
./vcpkg install cairo
Computing installation plan...
The following packages will be built and installed:
    cairo[core,fontconfig,freetype]:x64-linux -> 1.17.4#1
  * fontconfig[core]:x64-linux -> 2.13.1#7
  * lzo[core]:x64-linux -> 2.10#6
  * pixman[core]:x64-linux -> 0.40.0
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-linux...
Could not locate cached archive: /home/dev/.cache/vcpkg/archives/80/80772d1a235cda1d756ed182f55f552372050026.zip
Could not locate cached archive: /home/dev/.cache/vcpkg/archives/32/3238886b407dff30ec72081629bd6211845ecd6d.zip
Could not locate cached archive: /home/dev/.cache/vcpkg/archives/07/070ed7efe76cd3ba6895e301c97320461f1c51df.zip
Could not locate cached archive: /home/dev/.cache/vcpkg/archives/75/75968dcb70dd4bc0a9a8f763f24a9f992b638ca0.zip
Starting package 1/4: fontconfig:x64-linux
Building package fontconfig[core]:x64-linux...
-- Using cached /home/dev/vcpkg/downloads/fontconfig-fontconfig-844d8709a1f3ecab45015b24b72dd775c13b2421.tar.gz
-- Cleaning sources at /home/dev/vcpkg/buildtrees/fontconfig/src/75c13b2421-12bdc6f9c0.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/dev/vcpkg/downloads/fontconfig-fontconfig-844d8709a1f3ecab45015b24b72dd775c13b2421.tar.gz
-- Applying patch remove_tests.patch
-- Applying patch build.patch
-- Applying patch build2.patch
-- Applying patch disable-install-data.patch
-- Applying patch macos_arm_fccache.patch
-- Using source at /home/dev/vcpkg/buildtrees/fontconfig/src/75c13b2421-12bdc6f9c0.clean
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Generating configure for x64-linux
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
    Command failed: /usr/bin/autoreconf -vfi
    Working Directory: /home/dev/vcpkg/buildtrees/fontconfig/src/75c13b2421-12bdc6f9c0.clean/
    Error code: 1
    See logs for more information:
      /home/dev/vcpkg/buildtrees/fontconfig/autoconf-x64-linux-out.log
      /home/dev/vcpkg/buildtrees/fontconfig/autoconf-x64-linux-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:607 (vcpkg_execute_required_process)
  ports/fontconfig/portfile.cmake:26 (vcpkg_configure_make)
  scripts/ports.cmake:141 (include)


Error: Building package fontconfig:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: fontconfig:x64-linux
  Vcpkg version: 2021-05-05-unknownhash

Additionally, attach any relevant sections from the log files above.

**Comment by dg0yt** [comment]
> autoreconf: failed to run autopoint: No such file or directory

Install the package which contains autopoint. On Ubuntu, autopoint is in package ... `autopoint`.

**Comment by fldx** [comment]
dev@debian:~/vcpkg$ ./vcpkg install cairo
Computing installation plan...
The following packages will be built and installed:
    cairo[core,fontconfig,freetype]:x64-linux -> 1.17.4#1
  * fontconfig[core]:x64-linux -> 2.13.1#7
  * lzo[core]:x64-linux -> 2.10#6
  * pixman[core]:x64-linux -> 0.40.0
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-linux...
Could not locate cached archive: /home/dev/.cache/vcpkg/archives/80/80772d1a235cda1d756ed182f55f552372050026.zip
Could not locate cached archive: /home/dev/.cache/vcpkg/archives/32/3238886b407dff30ec72081629bd6211845ecd6d.zip
Could not locate cached archive: /home/dev/.cache/vcpkg/archives/07/070ed7efe76cd3ba6895e301c97320461f1c51df.zip
Could not locate cached archive: /home/dev/.cache/vcpkg/archives/75/75968dcb70dd4bc0a9a8f763f24a9f992b638ca0.zip
Starting package 1/4: fontconfig:x64-linux
Building package fontconfig[core]:x64-linux...
-- Using cached /home/dev/vcpkg/downloads/fontconfig-fontconfig-844d8709a1f3ecab45015b24b72dd775c13b2421.tar.gz
-- Cleaning sources at /home/dev/vcpkg/buildtrees/fontconfig/src/75c13b2421-12bdc6f9c0.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/dev/vcpkg/downloads/fontconfig-fontconfig-844d8709a1f3ecab45015b24b72dd775c13b2421.tar.gz
-- Applying patch remove_tests.patch
-- Applying patch build.patch
-- Applying patch build2.patch
-- Applying patch disable-install-data.patch
-- Applying patch macos_arm_fccache.patch
-- Using source at /home/dev/vcpkg/buildtrees/fontconfig/src/75c13b2421-12bdc6f9c0.clean
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Generating configure for x64-linux
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
    Command failed: /usr/bin/autoreconf -vfi
    Working Directory: /home/dev/vcpkg/buildtrees/fontconfig/src/75c13b2421-12bdc6f9c0.clean/
    Error code: 1
    See logs for more information:
      /home/dev/vcpkg/buildtrees/fontconfig/autoconf-x64-linux-out.log
      /home/dev/vcpkg/buildtrees/fontconfig/autoconf-x64-linux-err.log
[autoconf-x64-linux-err.log](https://github.com/microsoft/vcpkg/files/6543169/autoconf-x64-linux-err.log)
[autoconf-x64-linux-out.log](https://github.com/microsoft/vcpkg/files/6543170/autoconf-x64-linux-out.log)

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:607 (vcpkg_execute_required_process)
  ports/fontconfig/portfile.cmake:26 (vcpkg_configure_make)
  scripts/ports.cmake:141 (include)


Error: Building package fontconfig:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: fontconfig:x64-linux
  Vcpkg version: 2021-05-05-unknownhash

**Comment by fldx** [comment]
我在这里`https://wiki.debian.org/AutoTools`找的`autotool`
root@debian:/# apt install autoconf autoheader automake autoproject autoreconf autoscan autotoolset autoupdate libtool
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
E: 无法定位软件包 autoheader
E: 无法定位软件包 autoreconf
E: 无法定位软件包 autoscan
E: 无法定位软件包 autotoolset
E: 无法定位软件包 autoupdate
root@debian:/# 
依然没解决我的问题

**Comment by fldx** [comment]
我在这里`https://packages.debian.org/source/sid/dh-autoreconf`把`autoreconf`安装上了,能编译下去了

**Comment by fldx** [comment]
> Please install `autotool` using apt or yum.
谢谢大佬的帮助.
