### ISSUE TITLE
[New Port Request] cglm

### ISSUE THREAD

**Issue by galaxysailing** [microsoft/vcpkg#18121]
Library name: cglm

Library description: OpenGL Mathematics (glm) for C

Source repository URL:
https://github.com/recp/cglm

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by eRuaro** [comment]
Hey! I'd like to contribute to this.

**Comment by PhoebeHui** [comment]
Thanks @eRuaro! We're happy to accept a PR that support this!

**Comment by PhoebeHui** [comment]
REF for a stable tag/commit to use, and SHA512 with the checksum of the downloaded zipfile (you can get this easily by setting it to 1, trying to install the package, and copying the checksum).

See https://github.com/microsoft/vcpkg/blob/master/docs/examples/packaging-github-repos.md for details.

**Comment by eRuaro** [comment]
Hey, @PhoebeHui, the package now appears when I use the `search` command. Installing the package brings out this error.
 ```
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:184 (message):

      Failed to download file.
      If you use a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.

      3. You proxy's remote server is out of service.

      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)

      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:147 (vcpkg_download_distfile)
  ports/cglm/portfile.cmake:1 (vcpkg_from_github)
  scripts/ports.cmake:141 (include)
```

I don't get the instructions on how to check the proxy settings on windows. I tried doing the instructions on number `2` but my proxy setup is on `auto`. I'm not sure on what to input on the `address` and `port` on the manual proxy setup.

**Comment by PhoebeHui** [comment]
@eRuaro, see https://stackoverflow.com/questions/48473330/set-http-proxy-environment-variable-with-domain-user-and-pass-in-windows

**Comment by eRuaro** [comment]
Hey, @PhoebeHui I'm now able to download other libraries, but I still can't download cglm. I'm pretty new to CMake so I don't know if what I'm doing is right, I based the `portfile.cmake` file on the `rapidjson` library. I was able to install `rapidjson`, but not `cglm`. Any help would be really appreciated.

```
vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO recp/cglm
    REF 486f9b92b2be6d9dc3a5cf237a892cf0b5cad33e
    SHA512 1
    HEAD_REF master
)

vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA
    OPTIONS
        -CGLM_SHARED=ON
        -CGLM_STATIC=OFF
        -CGLM_USE_C99=OFF
        -CGLM_USE_TEST=OFF
)

vcpkg_install_cmake()

vcpkg_fixup_cmake_targets(CONFIG_PATH cmake)

file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug ${CURRENT_PACKAGES_DIR}/lib)

vcpkg_copy_pdbs()

file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)
file(INSTALL ${CMAKE_CURRENT_LIST_DIR}/usage DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT})
```

**Comment by PhoebeHui** [comment]
@eRuaro, sorry for late response, do you figure out this? You need replace the SHA512 with 'Acutual hash' which given in command line.

**Comment by eRuaro** [comment]
Sadly no. I'm still having the proxy error even if I have set it.

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
