### ISSUE TITLE
Idle on configuring

### ISSUE THREAD

**Issue by ghost** [Microsoft/vcpkg#1812]
Hello,

i have an issue that the configuring process takes forever and when i check task manger, PC is actually idling and doing nothing. What can be the problem?

**Comment by jasjuang** [comment]
This happened to me on some machine too. Pressing "Enter" to force it to go to the next step solves it for me.

**Comment by brano543** [comment]
I think this is the problem https://github.com/Microsoft/vcpkg/issues/1802. Why it is spawning processes with low priority lol. On my corporate machine i am trying to compile that curl for 2 hours now because it is always IDLE and doing nothing...

**Comment by OlafvdSpek** [comment]
If the system is literally idle then priorities aren't the issue are they?

**Comment by ras0219-msft** [comment]
Hi @brano543, could you give us more information about what library you're specifically trying to configure and what version of vcpkg this reproduces under?

**Comment by jasjuang** [comment]
It happens to me when I am using vcpkg on a Amazon EC2 windows instance. My local computer doesn't seem to have this problem.

**Comment by JackBoosY** [comment]
Hi @jasjuang , thanks for reporting this issue!
Please open a new issue if this is still a problem for you.
Thx.
