### ISSUE TITLE
Error: Building package zlib:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by hedmon84** [Microsoft/vcpkg#1814]

**Comment by hedmon84** [comment]
Error: Building package zlib:x86-windows failed with: BUILD_FAILED

**Comment by OlafvdSpek** [comment]
Could you attach the log files?

**Comment by hedmon84** [comment]
How I do   that ?

**Comment by alexkaratarakis** [comment]
@hedmon84 
You can find the logs in `buildtrees\zlib\`. `vcpkg` will print out the exact paths on your machine.
Attach files by dragging & dropping, or pasting them from the clipboard or click the button at the bottom of your reply box.

**Comment by inetdog** [comment]
Error: Building package zlib:x64

[install-x64-windows-rel-out.log](https://github.com/Microsoft/vcpkg/files/1487334/install-x64-windows-rel-out.log)

-windows failed with: BUILD_FAILED

**Comment by Cheney-W** [comment]
@hedmon84 & @inetdog 
I can install this port successfully with the latest vcpkg and VS2017 15.9.7. So close this issue.
