### ISSUE TITLE
[z3] Binary with dependency to source

### ISSUE THREAD

**Issue by PhilippGrulich** [microsoft/vcpkg#18153]
****
Hi,

for my usecase, I prebuilt binaries of Z3 and distribute them among my team members using `vspkg export`.
We now noticed that these binaries include references the actual source directory, which is not included in the export.
Consequently, some components of Z3 do not work as expected.

For instance, we are getting the following error because the `buildtree` is not present at this machine.
```
ASSERTION VIOLATION
File: /home/pgrulich-ldap/dependencies/vcpkg/buildtrees/z3/src/50ecd99ceb-ccf6d18521.clean/src/ast/bv_decl_plugin.cpp
Line: 863
m.has_plugin(symbol("bv"))
```

**Proposed solution**
I tried to investigate the problem and noticed that the CMAKE of Z3 is setting the `Z3_COMPONENT_EXTRA_INCLUDE_DIRS` variable.
In my case its set to:
`Z3_COMPONENT_EXTRA_INCLUDE_DIRS:  /home/pgrulich-ldap/dependencies/vcpkg/buildtrees/z3/x64-linux-dbg/src; /home/pgrulich-ldap/dependencies/vcpkg/buildtrees/z3/src/50ecd99ceb-ccf6d18521.clean/src
`

We could maybe solve the problem by including the source dir in the final `vcpk` package and passing setting `Z3_COMPONENT_EXTRA_INCLUDE_DIRS` correctly. However, I'm not sure how to do these changes to the `z3` port as I just tried `vcpkg` for the first time.

I hope the issue description is clear enough.
Thanks a lot for your help,
Philipp

**Comment by JackBoosY** [comment]
Hi @PhilippGrulich, can you please test PR https://github.com/microsoft/vcpkg/pull/18104, and if this issue still exist, please provide a sample project to reproduce it.

Thanks.

**Comment by JackBoosY** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
