### ISSUE TITLE
[boost-integer] build failure and download failure

### ISSUE THREAD

**Issue by wanlizhu** [microsoft/vcpkg#18152]
**Host Environment**
- OS: Windows and macOS
- Compiler: MSVC, Clang
- Location: China mainland (`git://` works, `https://` failes)

**To Reproduce**
`./vcpkg install cgal`

**Failure logs** 
Building package boost-integer[core]:x64-windows-static...
-- Downloading https://github.com/boostorg/integer/archive/boost-1.75.0.tar.gz -> boostorg-integer-boost-1.75.0.tar.gz...
-- Downloading https://github.com/boostorg/integer/archive/boost-1.75.0.tar.gz... Failed. Status: 28;"Timeout was reached"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:184 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".

      If error with status 4 (Issue #15434),
      try setting "http://user:password@your-proxy-ip-address:port/".

      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:147 (vcpkg_download_distfile)
  ports/boost-integer/portfile.cmake:3 (vcpkg_from_github)
  scripts/ports.cmake:142 (include)

Error: Building package boost-integer:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-integer:x64-windows-static
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

**Additional context**
- I tried all the possible solutions I could find online: disable ssl verify, change hosts file for github.com, and use proxy. None of them works.
- It's succeed to clone using `git://github.com/...`, so can we let vcpkg to download package using `git://` protocol instead of `https`?

**Comment by wanlizhu** [comment]
I tried http proxy and vpn, doesn't work. But it is ok to download using git protocol, so can i mannually specific the protocol as git instead of https?

**Comment by JackBoosY** [comment]
@wanlizhu Curently not.

**Comment by JackBoosY** [comment]
Now, I have an unofficial mirror in China, please see https://gitee.com/jackboosy/vcpkg/issues/I44496.
