### ISSUE TITLE
cannot completely remove vcpkg once installed

### ISSUE THREAD

**Issue by stephanecharette** [microsoft/vcpkg#18157]
I had vcpkg installed in a certain directory.  I've made attempts to remove it from that location (such as running "vcpkg integrate remove").

I then git cloned vcpkg to a new location.  But somehow it still references the old location, which causes problems.  How should vcpkg be completely purged from a Win10 system?

The old directory was `c:\src\darknet\`.

The new directory is `c:\src\vcpkg\`.  When I run commands such as this one:

    .\vcpkg.exe install opencv[contrib,core,dnn,ffmpeg,jpeg,png,quirc,tiff,webp]:x64-windows darknet[opencv-base]:x64-windows

The error that I get mention the old vcpkg directory:

```
Starting package 28/28: darknet:x64-windows
Building package darknet[core,opencv-base]:x64-windows...
-- Downloading https://github.com/AlexeyAB/darknet/archive/91efb7c7f6c00a4616ed58735f7c670908d0a849.tar.gz -> AlexeyAB-darknet-91efb7c7f6c00a4616ed58735f7c670908d0a849.tar.gz...
-- Extracting source C:/src/darknet/vcpkg/downloads/AlexeyAB-darknet-91efb7c7f6c00a4616ed58735f7c670908d0a849.tar.gz
-- Using source at C:/src/darknet/vcpkg/buildtrees/darknet/src/0908d0a849-27adeee8f8.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: C:/src/darknet/vcpkg/packages/darknet_x64-windows/tools/darknet/scripts/download_weights.ps1
-- To download weight files, please go to C:/src/darknet/vcpkg/installed/x64-windows/tools/darknet/scripts and run ./download_weights.ps1
-- Installing: C:/src/darknet/vcpkg/packages/darknet_x64-windows/share/darknet/copyright
-- Performing post-build validation
The following EXEs were found in /bin or /debug/bin. EXEs are not valid distribution targets.

    C:/src/darknet/vcpkg/packages/darknet_x64-windows/bin/uselib_track.exe

The following EXEs were found in /bin or /debug/bin. EXEs are not valid distribution targets.

    C:/src/darknet/vcpkg/packages/darknet_x64-windows/debug/bin/uselib_track.exe

Found 2 error(s). Please correct the portfile:
    C:\src\darknet\vcpkg\ports\darknet\portfile.cmake
```

Is there a command we can run to completely reset vcpkg?  Or files we need to manually delete so it doesn't use the old location anymore?

**Comment by cjwijtmans** [comment]
did you run bootstrap in new directory.

**Comment by stephanecharette** [comment]
Yes I did.  @cenit tells me it is because I didn't exit from the powershell and start a new one.  Additionally, I think he's also made a change to the darknet package so this won't be an issue anymore.  I plan on going back to this project this weekend, will test things then.
