### ISSUE TITLE
integrate install doesn't work on static

### ISSUE THREAD

**Issue by Neurochrom** [microsoft/vcpkg#18161]
Visual Studio 2019 (16.9.4)
```
git clone https://github.com/microsoft/vcpkg.git
cd vcpkg
bootstrap-vcpkg.bat
vcpkg.exe integrate install
```
 
Accept the changes to the system.

 The console states:

 _All MSBuild C++ projects can now #include any installed libraries.
 Linking will be handled automatically.
 Installing new libraries will make them instantly available._

A  _vcpkg.system.props_ file is created in _C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\v140\ImportBefore\Default_

```
vcpkg.exe install openssl:x64-windows-static
```
The library builds as expected.

Create a new empty Windows Console C++ project in Visual Studio.
Add a hi.cpp file

```C++
#include <iostream>
#include <openssl/ssl.h>

int main()
{
	std::cout << "hi" << std::endl;
	return 0;
}
```

Switch solution platform to x64.
Try building.

Result:
_**hiosl.cpp(2,10): fatal error C1083: Cannot open include file: 'openssl/ssl.h': No such file or directory**_

Most probably related to issue [#10534](https://github.com/microsoft/vcpkg/issues/10534) and [#13503](https://github.com/microsoft/vcpkg/issues/13503), possibly a regression.
Also related to https://stackoverflow.com/questions/59865669/how-to-use-vcpkg-installed-packages-in-visual-studio-in-reality

Also the vcpkg screen in Configuration Properties does not appear in old projects (might need a separate bug report)

**Comment by JackBoosY** [comment]
Can you please also run `./vcpkg integrate project`?

**Comment by Neurochrom** [comment]
@JackBoosY
`./vcpkg integrate project`
```
Created nupkg: C:\.........\vcpkg\scripts\buildsystems\vcpkg.C.thunderpants.libs.vcpkg.1.0.0.nupkg

With a project open, go to Tools->NuGet Package Manager->Package Manager Console and paste:
    Install-Package vcpkg.C.thunderpants.libs.vcpkg -Source "C:\.........\vcpkg\scripts\buildsystems"
```
Followed the instructions
```
...
Successfully installed 'vcpkg.C.thunderpants.libs.vcpkg 1.0.0' to vcpkgNewProjTest
```
Project builds fine afterwards.

**Comment by Neurochrom** [comment]
@JackBoosY 
another workaround I used before is adding a vcpkg.props to the projects property sheets containing:
```XML
<?xml version="1.0" encoding="utf-8"?> 
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros" />
  <PropertyGroup />
  <PropertyGroup Label="Globals">
    <VcpkgTriplet Condition="'$(VcpkgOSTarget)|$(Platform)'=='linux|x64'">x64-linux</VcpkgTriplet>
    <VcpkgTriplet Condition="'$(VcpkgOSTarget)|$(Platform)'=='windows|x64'">x64-windows-static</VcpkgTriplet>
  </PropertyGroup>
  <ItemDefinitionGroup />
  <ItemGroup />
</Project>
```
still it would be lovely if it could just work as documented

**Comment by JackBoosY** [comment]
Also, we can set it here:

![image](https://user-images.githubusercontent.com/47264268/120130778-9a057b00-c1f9-11eb-8abc-52003d84962a.png)
