### ISSUE TITLE
[Folly] Add support for arm triplet

### ISSUE THREAD

**Issue by PhilippGrulich** [microsoft/vcpkg#18160]
Folly is in general supported on Linux (x86-32, x86-64, and ARM).
However, the port is currently restricted to x86 thus we should enable also ARM support.

**Comment by JackBoosY** [comment]
Folly only support x64 triplets and it should support arm now.
Can you double confirm this?

**Comment by PhilippGrulich** [comment]
Yes.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
