### ISSUE TITLE
How do I modify the port file to make is build in release only (skip debug)

### ISSUE THREAD

**Issue by HaoxuanGuo** [microsoft/vcpkg#18167]
I tried to build [geant4](https://geant4.web.cern.ch/) in vcpkg.

But due to it is not in the port registry, I have to [add a new package from a zip file](https://github.com/microsoft/vcpkg/blob/master/docs/examples/packaging-zipfiles.md). This library is too large to compile in DEBUG (it has more than 65535 symbols). vcpkg build both in default that cause an error.

To fix this error, I tried modifying the port file to disable DEBUG compiling. Thus, I add `set(VCPKG_BUILD_TYPE release)` into the port file. It works but another problem occurred.

Although the DEBUG is disabled, vcpkg also checks the number of debug and release binaries. Obviously, there is no debug binary and the number mismatch. Another error which I am unable to fix throwed.

In a nutshell, I wonder how can I modify the port file generated to build only release (no debug) in default triplets.

**Comment by JackBoosY** [comment]
Add `set(VCPKG_BUILD_TYPE "release")` to the triplet file in _VCPKG_ROOT/triplets_.

**Comment by HaoxuanGuo** [comment]
@JackBoosY Thank you for your help.
