### ISSUE TITLE
vcpkg_install_gn is NOT working

### ISSUE THREAD

**Issue by Kwizatz** [microsoft/vcpkg#18164]
**Describe the bug**

Ports calling vcpkg_install_gn are missing the target requested to be installed

**Environment**
- OS: Windows 
- Compiler: 19.28.29915

**To Reproduce**
1. vcpkg --triplet x64-windows install crashpad
2. installed/x64-windows/lib or installed/x64-windows/debug/lib are missing all .lib files

**Expected behavior**
*.lib files are installed under installed/&lt;triplet&gt;/lib

**Failure logs** 
No failure is reported, only the files are never installed

**Additional context**
This was found doing a v8 build 'vcpkg --triplet x64-windows install v8', however the v8 build takes significantly more time
and the issue is reproducible with any port using GN, if the crashpad installation is 100% correct, try with v8.

**Comment by JackBoosY** [comment]
Yeah...I saw the library was generated in `x64-windows-dbg` and `x64-windows-rel` but not install.

**Comment by JackBoosY** [comment]
cc @vejmartin.

**Comment by vejmartin** [comment]
@JackBoosY, thank you for the cc, I'll look into it.
