### ISSUE TITLE
oatpp update to 1.2.5

### ISSUE THREAD

**Issue by xilutian** [microsoft/vcpkg#18165]
Library name:

New version number:

Other information that may be useful (release notes, etc...)

**Comment by JonLiu1993** [comment]
@xilutian ,Thanks for posting this issue,
currently the highest version of oatpp is 1.2.5.
Duplicate of #17599

**Comment by xilutian** [comment]
![image](https://user-images.githubusercontent.com/14370659/119960693-cf328300-bfd7-11eb-9826-7b911e96612c.png)
Why am I still searching for 1.2.0, and what should I do  ，Thanks

**Comment by JonLiu1993** [comment]
@xilutian ,Please use the latest vcpkg

**Comment by xilutian** [comment]
Can I just update Ports? Is there any command support

**Comment by JonLiu1993** [comment]
Use the "git pull" command to update vcpkg to the latest version, if it is still not the latest version, please clone vcpkg again

**Comment by xilutian** [comment]
ok
