### ISSUE TITLE
How to force vcpkg to install dependencies with --head parameter, when using in manifest mode?

### ISSUE THREAD

**Issue by lukcz** [microsoft/vcpkg#18174]
According to documentation of vcpkg_from_github:
```
At least one of REF and HEAD_REF must be specified, however it is preferable for both to be present.
```

I do not want to specify REF and SHA512 in my portfile.cmake. Instead I would like to build my library based on HEAD_REF  by adding --head when installing my dependency:
```
vcpkg install mypackage --head
```

This works in user-wide mode, however when using vcpkg in manifest mode it is assumed that REF parameter is specified which results in package installation error:
```
vcpkg.targets(104,5): error MSB3073: The command ""vcpkg.exe" install  --x-wait-for-lock --triplet "x64-windows" --vcpkg-root "<some_path>" "--x-manifest-root=<som_other_path>" "--x-install-root=<other_path>\vcpkg_installed\\" " exited with code 1.
```

**Comment by PhoebeHui** [comment]
@lukcz, could you try the the solution provided by https://github.com/microsoft/vcpkg/pull/16613#issuecomment-799801106 and see if it works for you?

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/16624.
