### ISSUE TITLE
Does Vcpkg binary caching support reusing binaries with ABI compatible compilers?

### ISSUE THREAD

**Issue by obsgolem** [microsoft/vcpkg#18177]
My project is looking to switch from a bespoke dependency management solution to Vcpkg.  We need to distribute a set of precompiled dependencies to our customers so that customers without internet access can build the project and also so that they don't have to rebuild the dependencies if necessary. Previously, it looks like `vcpkg export` could have fulfilled this need, but this isn't currently supported in manifest mode, which would likely be our preferred mode of operation (see https://github.com/microsoft/vcpkg/issues/16124).

Would binary caching suffice for this use case? According to [this](https://github.com/microsoft/vcpkg/blob/master/docs/users/binarycaching.md#implementation-notes-internal-details-subject-to-change-without-notice), binary caching hashes a decent amount of the build environment, leading me to think it won't work with packages compiled in VS2017 being used in VS2019 (or even two different versions of 2019). If not, then what is the recommended method for making our use case work?

**Comment by JackBoosY** [comment]
I'd like @vicroms to answer this question.

**Comment by PhoebeHui** [comment]
Closing in favor of https://github.com/microsoft/vcpkg/issues/16631.
