### ISSUE TITLE
[fontconfig] Build failure on arm64-osx-dynamic

### ISSUE THREAD

**Issue by limarev** [microsoft/vcpkg#18170]
Build qt5 via vcpkg failed, it's not clear why vcpkg can't install required libfontconfig library.

**Host Environment**
- OS: Apple m1 BigSur 11.04
- Compiler: Apple clang version 12.0.5

**To Reproduce**
```
export VCPKG_FORCE_SYSTEM_BINARIES=1 \
&& ./bootstrap-vcpkg.sh -useSystemBinaries -disableMetrics -allowAppleClang \
&& ${VCPKG_ROOT}/vcpkg install \
--clean-after-build \
--triplet=arm64-osx-dynamic \
qt5 \
qt5-charts \
qt5-location \
qt5-quickcontrols \
qt5-quickcontrols2 \
&& sudo ${VCPKG_ROOT}/vcpkg integrate instal
```

**Failure logs** 
```
Starting package 17/45: fontconfig:arm64-osx-dynamic
Building package fontconfig[core]:arm64-osx-dynamic...
-- Using community triplet arm64-osx-dynamic. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: /Users/limarev/local/vcpkg/triplets/community/arm64-osx-dynamic.cmake
-- Downloading https://gitlab.freedesktop.org/fontconfig/fontconfig/-/archive/844d8709a1f3ecab45015b24b72dd775c13b2421/fontconfig-844d8709a1f3ecab45015b24b72dd775c13b2421.tar.gz -> fontconfig-fontconfig-844d8709a1f3ecab45015b24b72dd775c13b2421.tar.gz...
-- Extracting source /Users/limarev/local/vcpkg/downloads/fontconfig-fontconfig-844d8709a1f3ecab45015b24b72dd775c13b2421.tar.gz
-- Applying patch remove_tests.patch
-- Applying patch build.patch
-- Applying patch build2.patch
-- Applying patch disable-install-data.patch
-- Applying patch macos_arm_fccache.patch
-- Using source at /Users/limarev/local/vcpkg/buildtrees/fontconfig/src/75c13b2421-12bdc6f9c0.clean
-- Configuring arm64-osx-dynamic-dbg
-- Configuring arm64-osx-dynamic-rel
-- Generating configure for arm64-osx-dynamic
-- Finished generating configure for arm64-osx-dynamic
-- Configuring arm64-osx-dynamic-dbg
-- Configuring arm64-osx-dynamic-rel
-- Building arm64-osx-dynamic-dbg
-- Installing arm64-osx-dynamic-dbg
-- Building arm64-osx-dynamic-rel
-- Installing arm64-osx-dynamic-rel
-- Fixing pkgconfig file: /Users/limarev/local/vcpkg/packages/fontconfig_arm64-osx-dynamic/lib/pkgconfig/fontconfig.pc
-- Fixing pkgconfig file: /Users/limarev/local/vcpkg/packages/fontconfig_arm64-osx-dynamic/debug/lib/pkgconfig/fontconfig.pc
-- Installing: /Users/limarev/local/vcpkg/packages/fontconfig_arm64-osx-dynamic/share/fontconfig/copyright
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
    Command failed: /Users/limarev/local/vcpkg/packages/fontconfig_arm64-osx-dynamic/tools/fontconfig/bin/fc-cache --verbose
    Working Directory: /Users/limarev/local/vcpkg/packages/fontconfig_arm64-osx-dynamic/tools/fontconfig/bin
    Error code: Subprocess aborted
    See logs for more information:
      /Users/limarev/local/vcpkg/buildtrees/fontconfig/fc-cache-arm64-osx-dynamic-err.log

Call Stack (most recent call first):
  ports/fontconfig/portfile.cmake:101 (vcpkg_execute_required_process)
  scripts/ports.cmake:139 (include)


Error: Building package fontconfig:arm64-osx-dynamic failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: fontconfig:arm64-osx-dynamic
  Vcpkg version: 2021-05-05-unknownhash

Additionally, attach any relevant sections from the log files above.
```
[fc-cache-arm64-osx-dynamic-err.log](https://github.com/microsoft/vcpkg/files/6559357/fc-cache-arm64-osx-dynamic-err.log)
fc-cache-arm64-osx-dynamic-out.log is empty

**Comment by JackBoosY** [comment]
cc @xandox @dg0yt @abique @Neumann-A

**Comment by JackBoosY** [comment]
Even `arm64-osx` is a community triplet, since Apple M1 macbook are more and more used, I will stare at this issue.

**Comment by xandox** [comment]
@limarev can I ask for other logs?

**Comment by autoantwort** [comment]
Please change `arm64-osx` to `arm64-osx-dynamic` in the title, for `arm64-osx` the build is successful

**Comment by limarev** [comment]
> @limarev can I ask for other logs?

@xandox yep, you are welcome

**Comment by limarev** [comment]
> > /Users/limarev/local/vcpkg/packages/fontconfig_arm64-osx-dynamic/tools/fontconfig/bin/fc-cache
> > ...
> > dyld: Library not loaded: /Users/limarev/local/vcpkg/installed/arm64-osx-dynamic/lib/libfontconfig.1.dylib
> 
> Wait, is it running fc-cache from the `packages` dir, but expecting to find libfontconfig.1.dylib from the same build in `installed` dir?

@dg0yt seems you are right:
```
% ls -R $VCPKG_ROOT/packages | grep libfont
libfontconfig.1.dylib
libfontconfig.dylib
libfontconfig.1.dylib
libfontconfig.dylib
%
```

```
% ls -R $VCPKG_ROOT/installed | grep libfont
%
```

**Comment by limarev** [comment]
> Please change `arm64-osx` to `arm64-osx-dynamic` in the title, for `arm64-osx` the build is successful

@autoantwort I changed the title, but for `arm64-osx` build is still unsuccessful: #17472

**Comment by dg0yt** [comment]
FTR, on my x64-linux machine, `fc-cache` runs 0.35 s and creates 1.2 MB in `packages/fontconfig_x64-linux/var/cache/fontconfig`. According to `fc-cache-x64-linux-out.log`, it processed mostly `/usr/share/fonts`.

**Comment by Neumann-A** [comment]
> What is the point of running fc-cache at build time?

If  the fontconfig version within vcpkg has problems with the fontconfig cache of the system trying to run an executable like the cmake test port will display gibberish. This was e.g. the case wenn the fontconfig version within vcpkg was not working with the fontconfig cache of Ubuntu 20.04. Setting FONTCONFIG_PATH to the path within vcpkg solves this issue.

> What is the point of running fc-cache at build time?

Maybe vcpkg should add --rpath $ORIGIN and copy .so files just like dlls into the tool directory. Additionally it could have
--rpath $ORIGIN/../../lib (for tools/port/binary) and --rpath $ORIGIN/../../../lib (for  tools/port/bin/binary)

> ATM, it doesn't work well for cross builds (#15869, #15605 (comment)).

Needs to be a host dependency theoretically but you cannot run a executable on the host for the target without emulation so it does not matter that much. Just disable it for cross builds.

**Comment by Cheney-W** [comment]
Thanks for posting this issue. arm64-osx-dynamic is a community triplet, and there are no update about this issue for a long time. If there are new process or change of this issue, please reopen this issue.
