### ISSUE TITLE
[qt5-svg] build failure, /include empty or not preset

### ISSUE THREAD

**Issue by wrobelda** [microsoft/vcpkg#18188]
**Host Environment**
- OS: Ubuntu ~~20.04~~ 18.04

**To Reproduce**
`./vcpkg install qt5-svg`

**Failure logs** 

```
Starting package 1/13: qt5-svg:x64-linux
Building package qt5-svg[core]:x64-linux...
-- Using cached /home/cromo/vcpkg/downloads/qtsvg-everywhere-src-5.15.2.tar.xz
-- Cleaning sources at /home/cromo/vcpkg/buildtrees/qt5-svg/src/5.15.2-863459677c.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/cromo/vcpkg/downloads/qtsvg-everywhere-src-5.15.2.tar.xz
-- Using source at /home/cromo/vcpkg/buildtrees/qt5-svg/src/5.15.2-863459677c.clean
-- Configuring x64-linux-rel
-- Configuring x64-linux-rel done
-- Configuring x64-linux-dbg
-- Configuring x64-linux-dbg done
-- Package build-x64-linux-dbg
-- Package build-x64-linux-rel
-- Package install-x64-linux-dbg
-- Package install-x64-linux-rel
-- Installing: /home/cromo/vcpkg/packages/qt5-svg_x64-linux/share/qt5-svg/copyright
-- Performing post-build validation
The folder /include is empty or not present. This indicates the library was not correctly installed.
Found 1 error(s). Please correct the portfile:
    /home/cromo/vcpkg/ports/qt5-svg/portfile.cmake
-- Performing post-build validation done
Error: Building package qt5-svg:x64-linux failed with: POST_BUILD_CHECKS_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: qt5-svg:x64-linux
  Vcpkg version: 2021-01-13-unknownhash
```

**Comment by Neumann-A** [comment]
That is an indicator that something is missing. Configure err and out log requiered for further debugging.

**Comment by JackBoosY** [comment]
Please provide the logs in _/home/cromo/vcpkg/buildtrees/qt5-svg_.

Thanks.

**Comment by wrobelda** [comment]
Only config-err is non-empty, and reads:

```
/mnt/qt5-svg/src/5.15.2-863459677c.clean/.qmake.conf:1: Cannot find feature qt_build_config
Could not find qmake spec 'linux-g++'.
Error processing project file: /home/cromo/vcpkg/buildtrees/qt5-svg/src/5.15.2-863459677c.clean/qtsvg.pro
```

**Comment by Neumann-A** [comment]
> EDIT: I had run out of the disk space at some point when building the qtbase package. I removed /installed and am reinstalling everything from scratch to see if it helps.

that will probably help since the error :
> Could not find qmake spec 'linux-g++'.

means it is missing mkspec files which normally get installed ;)

**Comment by wrobelda** [comment]
> > Could not find qmake spec 'linux-g++'.
> 
> means it is missing mkspec files which normally get installed ;)

Yeah, that's what I figured. I had a similar issue before and there's definitely some deficiency somewhere in vcpkg that yields a false-positive port installation status in such scenario.

**Comment by wrobelda** [comment]
Yep, reinstalling everything helped. There's definitely a problem with vcpkg, such that it marks incomplete packages as installed successfully.
