### ISSUE TITLE
[popsift] build failure on x64-windows

### ISSUE THREAD

**Issue by edwin-tn** [microsoft/vcpkg#18180]
**Host Environment**
- OS: [Windows 10]
- Compiler: Visual Studio 2017 Developer Command Prompt v15.9.36

**To Reproduce**
`./vcpkg install popsift[apps] --triplet x64-windows`

**Failure logs** 
Starting package 1/1: popsift:x64-windows
Building package popsift[apps,core]:x64-windows...
-- Using cached C:/vcpkg/downloads/alicevision-popsift-v0.9.tar.gz
-- Extracting source C:/vcpkg/downloads/alicevision-popsift-v0.9.tar.gz
-- Using source at C:/vcpkg/buildtrees/popsift/src/v0.9-88e8571dbf.clean
CMake Error at ports/popsift/portfile.cmake:9 (include):
  include could not find requested file:

    C:/vcpkg/installed/x64-windows/share/cuda/vcpkg_find_cuda.cmake
Call Stack (most recent call first):
  scripts/ports.cmake:139 (include)

Error: Building package popsift:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: popsift:x64-windows
  Vcpkg version: 2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9

**Comment by JackBoosY** [comment]
Please make sure your vcpkg is latest.

Thanks.

**Comment by JackBoosY** [comment]
Related: https://github.com/microsoft/vcpkg/issues/17940.

**Comment by JackBoosY** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.
