### ISSUE TITLE
LLVM lld-link : error : could not open ...\*.lib: invalid argument

### ISSUE THREAD

**Issue by Ou7law007** [microsoft/vcpkg#18189]
**Describe the bug**
could not open 'C:\Users\User\vcpkg\scripts\buildsystems\msbuild\..\..\..\installed\x64-windows-static\debug\lib\*.lib': invalid argument when "C++ Clang Compiler for Windows (11.0.0)" is installed and "LLVM (clang-cl)" is set.

After some digging I found out that the lld linker is unable to interpret vcpkg's output of libs.

Setting Use AutoLink to false DOES NOT fully fix the issue for me, it causes all my dependencies to be ignored (all .libs and includes)

**Environment**
- OS: Windows
- Compiler: VS 2019

**To Reproduce**
1. Install clang 11.0.0 from the VS Installer
2. In VS 2019, set General -> Platform Toolset to "LLVM (clang-cl)"
3. Compile
4. Error...

**Comment by NancyLi1013** [comment]
Hi @Ou7law007 

Thanks for posting this issue. Since it's duplicated to #15623, let's track this issue there.
