### ISSUE TITLE
[libtorrent] update version from 1.2.13 to  2.0.3

### ISSUE THREAD

**Issue by pythagoras9** [microsoft/vcpkg#18192]
Library name: libtorrent

New version number: 2.0.3

-> BitTorrent v2 support

**Comment by JackBoosY** [comment]
We should add a new port named `libtorrent2`.

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by pythagoras9** [comment]
https://github.com/microsoft/vcpkg/pull/22697 @PhoebeHui
