### ISSUE TITLE
[catch2] build failure

### ISSUE THREAD

**Issue by acgetchell** [microsoft/vcpkg#18195]
**Host Environment**
- OS: Windows 10
- Compiler: Visual Studio 2019 with clang-cl 11.0.0

**To Reproduce**
`./vcpkg install--feature-flags=manifests`

**Failure logs** 
```
vcpkg install --feature-flags=manifests
Found both manifest and CONTROL file in port C:\Tools\vcpkg\ports\catch2; please rename one or the other
Command exited with code 1
```
**Additional context**
Manifest file:

https://github.com/acgetchell/CDT-plusplus/blob/develop/vcpkg.json

Build log:

https://ci.appveyor.com/project/acgetchell/cdt-plusplus/builds/39388016

**Comment by acgetchell** [comment]
If I don't cache VCPKG_ROOT, then this problem doesn't happen.

https://github.com/acgetchell/CDT-plusplus/commit/1abbc1368f60d583420ae4c0413ef6739f24df32

**Comment by autoantwort** [comment]
It this still a problem?

**Comment by acgetchell** [comment]
No.
