### ISSUE TITLE
boost-type-traits build failure

### ISSUE THREAD

**Issue by huolingfei** [microsoft/vcpkg#18190]
**Host Environment**
- OS: Windows
- Compiler: revision

**To Reproduce**
`.\vcpkg\vcpkg.exe install boost-math:x86-windows boost-math:x64-windows`

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.
Computing installation plan...
The following packages will be built and installed:
  * boost-algorithm[core]:x64-windows -> 1.75.0
  * boost-algorithm[core]:x86-windows -> 1.75.0
  * boost-align[core]:x86-windows -> 1.75.0
  * boost-align[core]:x64-windows -> 1.75.0
  * boost-array[core]:x64-windows -> 1.75.0
  * boost-array[core]:x86-windows -> 1.75.0
  * boost-assert[core]:x86-windows -> 1.75.0
  * boost-atomic[core]:x86-windows -> 1.75.0
  * boost-atomic[core]:x64-windows -> 1.75.0
  * boost-bind[core]:x64-windows -> 1.75.0
  * boost-bind[core]:x86-windows -> 1.75.0
  * boost-build[core]:x64-windows -> 1.75.0.beta1#1
  * boost-build[core]:x86-windows -> 1.75.0.beta1#1
  * boost-compatibility[core]:x86-windows -> 1.75.0
  * boost-concept-check[core]:x64-windows -> 1.75.0#1
  * boost-concept-check[core]:x86-windows -> 1.75.0#1
  * boost-config[core]:x86-windows -> 1.75.0
  * boost-container[core]:x86-windows -> 1.75.0
  * boost-container[core]:x64-windows -> 1.75.0
  * boost-container-hash[core]:x86-windows -> 1.75.0
  * boost-container-hash[core]:x64-windows -> 1.75.0
  * boost-conversion[core]:x64-windows -> 1.75.0
  * boost-conversion[core]:x86-windows -> 1.75.0
  * boost-core[core]:x86-windows -> 1.75.0
  * boost-detail[core]:x86-windows -> 1.75.0
  * boost-exception[core]:x64-windows -> 1.75.0
  * boost-exception[core]:x86-windows -> 1.75.0
  * boost-function[core]:x64-windows -> 1.75.0
  * boost-function[core]:x86-windows -> 1.75.0
  * boost-function-types[core]:x86-windows -> 1.75.0
  * boost-function-types[core]:x64-windows -> 1.75.0
  * boost-functional[core]:x86-windows -> 1.75.0
  * boost-functional[core]:x64-windows -> 1.75.0
  * boost-fusion[core]:x64-windows -> 1.75.0
  * boost-fusion[core]:x86-windows -> 1.75.0
  * boost-integer[core]:x64-windows -> 1.75.0
  * boost-integer[core]:x86-windows -> 1.75.0
  * boost-intrusive[core]:x64-windows -> 1.75.0
  * boost-intrusive[core]:x86-windows -> 1.75.0
  * boost-io[core]:x64-windows -> 1.75.0
  * boost-io[core]:x86-windows -> 1.75.0
  * boost-iterator[core]:x86-windows -> 1.75.0
  * boost-iterator[core]:x64-windows -> 1.75.0
  * boost-lambda[core]:x64-windows -> 1.75.0
  * boost-lambda[core]:x86-windows -> 1.75.0
  * boost-lexical-cast[core]:x86-windows -> 1.75.0
  * boost-lexical-cast[core]:x64-windows -> 1.75.0
    boost-math[core]:x64-windows -> 1.75.0
    boost-math[core]:x86-windows -> 1.75.0
  * boost-modular-build-helper[core]:x64-windows -> 1.75.0#6
  * boost-modular-build-helper[core]:x86-windows -> 1.75.0#6
  * boost-move[core]:x64-windows -> 1.75.0
  * boost-move[core]:x86-windows -> 1.75.0
  * boost-mp11[core]:x86-windows -> 1.75.0
  * boost-mp11[core]:x64-windows -> 1.75.0
  * boost-mpl[core]:x86-windows -> 1.75.0
  * boost-mpl[core]:x64-windows -> 1.75.0
  * boost-numeric-conversion[core]:x64-windows -> 1.75.0
  * boost-numeric-conversion[core]:x86-windows -> 1.75.0
  * boost-optional[core]:x64-windows -> 1.75.0
  * boost-optional[core]:x86-windows -> 1.75.0
  * boost-predef[core]:x64-windows -> 1.75.0
  * boost-predef[core]:x86-windows -> 1.75.0
  * boost-preprocessor[core]:x86-windows -> 1.75.0
  * boost-range[core]:x64-windows -> 1.75.0
  * boost-range[core]:x86-windows -> 1.75.0
  * boost-regex[core]:x86-windows -> 1.75.0
  * boost-regex[core]:x64-windows -> 1.75.0
  * boost-smart-ptr[core]:x64-windows -> 1.75.0
  * boost-smart-ptr[core]:x86-windows -> 1.75.0
  * boost-static-assert[core]:x86-windows -> 1.75.0
  * boost-throw-exception[core]:x86-windows -> 1.75.0
  * boost-throw-exception[core]:x64-windows -> 1.75.0
  * boost-tuple[core]:x64-windows -> 1.75.0
  * boost-tuple[core]:x86-windows -> 1.75.0
  * boost-type-index[core]:x64-windows -> 1.75.0
  * boost-type-index[core]:x86-windows -> 1.75.0
  * boost-type-traits[core]:x86-windows -> 1.75.0
  * boost-type-traits[core]:x64-windows -> 1.75.0
  * boost-typeof[core]:x64-windows -> 1.75.0
  * boost-typeof[core]:x86-windows -> 1.75.0
  * boost-uninstall[core]:x86-windows -> 1.75.0
  * boost-unordered[core]:x86-windows -> 1.75.0
  * boost-unordered[core]:x64-windows -> 1.75.0
  * boost-utility[core]:x86-windows -> 1.75.0
  * boost-utility[core]:x64-windows -> 1.75.0
  * boost-vcpkg-helpers[core]:x86-windows -> 7#2
  * boost-winapi[core]:x64-windows -> 1.75.0
  * boost-winapi[core]:x86-windows -> 1.75.0
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Detecting compiler hash for triplet x86-windows...
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\6a\6a623885356576ec30c8e39bc9479930d30f9d8f.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\bc\bcb4e3ee77163bd4f133c9a582398d9b1151a54d.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\da\da218ea5c4aea35bb54acbbac8cf34e0445adf7f.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\09\0953e0dfe3d0b45f14a92e91ea5892a71cecb669.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\c9\c9b146517ec53e1e0bb77c5b13d49ef6a6b7177c.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\0e\0e699ce53afe5f305a4a875b319e57a7afb26168.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\73\734cc3da4404542d08b1831497e38fb65e8399f7.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\42\42dc73c17d505a6df8fa8a1ae6f9be0a7dad5cf5.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\a8\a8748199b8039dcc59203592ff66a9e56bdfc03d.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\1c\1cb07ad5d691bc850a5fc191ed4cc60ac7742283.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\38\388e5f3692d01f746a2584fc011457925460b616.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\4f\4ff17bcc37cd6e9478259d150bd48c4141b48e6c.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\57\570e0caf47e8aa5787e3a52f556023867a014da5.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\d5\d5f09e21b6916c1edae44d68f9a0010383661b07.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\45\45c42a839994a0d4ff4075f57b9c65c6cf998eff.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\93\9350f3ad031a70cec8bdbd28b14366d2724172f7.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\7f\7fc21a60df81e011e594d9d69ea607d70cd9c9f1.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\aa\aa4b1f3911f4f9ea8891ff8068dea47e0b912483.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\ca\cac886bb6da0c1040cf8a292f9e70aef5168c2ba.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\c2\c291d6d7399f77414d852cb68312069400c7cae7.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\df\dfffb401ebabc8557d5fa6ff1c3fa7a847b669b5.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\5e\5e8d7387eb003f5eca246cfc93f5e8506be8b114.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\d7\d73672c6fa92911f708d1ad325dee1da6be5b088.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\98\98e3f00f61b884fb8c45ea60c6b570cfb1a551cc.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\d0\d03363c36e7c2e17bb7ed15ca3ed3febb50a8232.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\80\8033751da57f4d9b623f9d51887012ce415312b9.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\ca\ca43cd58804e7aee8eacb6ab2f830282690affd6.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\53\53024d8217fa3c933a55d976e1c8e4f072b30ea1.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\d8\d8eeab99d90584be23137ff73ae63071a737eb12.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\b9\b941f0e03fd5f6b16a69fc34b65e634f64398389.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\34\347146794545eb1435575b4562d8634f9301170c.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\26\260cf1349a69810781795d7c1680999417381b29.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\fb\fbf8ec214fa9547437d6625a45006672e007aa5e.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\32\32ba7139fd82884dc43a2f715d0b177372bb63c6.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\9a\9a94b0735d1715ed77f4c8e6c83ddf0a1ea4bf5a.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\82\82720337815e78952ada3064e75e03be066912d6.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\3d\3d7ecceb5bf26813ef47d80f4c85706f1f3b988f.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\17\17ade9c66611a58c575e792e9cb33f802d78e228.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\c1\c1e962e9d5c4cf5c881633643b77bcc5ba01e4ac.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\80\8088c1c0182a201e55ee4f5ffa27caf08d932eaa.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\4a\4a54b8931a7583ad3952bfe6555b2dcc5946b821.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\bd\bdb6d014cdd7dfdc87bdbd492f3c51f240d3ac4a.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\4a\4af6920b22ec93179f863ca00eaf0911838447ea.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\cd\cdc806a6c806b77b0edc02b826a2ecd74bedeeb5.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\47\47b660084b3c6a7adc0cc3c60ac8d8c758613ff3.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\1b\1bd11b20a96e2fbf967f909ca92dd9b318b63ab3.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\be\be2b2d92125c86ac83ba5eab0bd00fe78f378b70.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\ff\ffaa2cc65b74d0eb3f2396a2f9e0d34db8565d04.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\74\74b3b894dbbb2d90d243d3a7aae9645b8cb0e73e.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\cb\cb73bb410d4565af5bf8d0d7b8a20620dbc883e8.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\95\958b053c253264f9a5ecc8a2a5622c32337e9b96.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\da\daedbbce2489c2ce0549cef1679c3f386a2098ad.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\63\6352df0866370f67620c67fdab5856952cb598a4.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\93\934f859bf6b6d9531dac7d8cef62c00197f9039e.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\c1\c1bf7de67a021f4451f89e905ebdb33733150bb7.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\b2\b2ddea76978a9e4e3d6a3a44eef5bd7d6441b56d.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\88\88619c1c033917383a84f0fb733c7bea1a4105ab.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\4e\4e62cb0e2159999ea418c619cf7da69204ec7aa3.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\53\537eb57641ac8dcdf46fef98bd74687d79a9a661.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\48\48781cdd856b497b3456b55101847a239c97d8de.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\85\8541af7acd00f9f0f8ec79b7474070e8a92668c7.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\8d\8d5579ff309393088b38559469fb0649c733e766.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\bd\bd97ea3ff80e0819984644ec397d026a331f9110.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\ac\ac49c87a8d12ac8c06256a430341ee5e50c7258b.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\af\af67f2b31ac39236be2ab8be93e21ee56992149d.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\ef\ef80328fc1a9b1bfbaa97814b4ac997358532928.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\06\062c6aba0a6f30c767845ed8c6b68e1601c5155a.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\5c\5c9f378902ed0cb099baa376d905bd3a00465424.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\48\4869d0ea22f2bf416f7492da15664909b32b740a.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\c2\c2e1b171dc82844e34b3813509647e2e72ba5db2.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\3e\3e178a0ef02ae485c0d054462f91e075e0e1537d.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\6b\6bd079b4863d0c0cb78e514b6fd029c4005c79bb.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\5a\5ac80e300fe209bf121a5375ea1a331915cbf3ba.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\cf\cf245840b68b83f714d4379383b709bd8f8003a6.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\43\435e78bd44930fed7caf59daf6fb0128e6d9e5d8.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\00\00b7683363dcb6d6c3beb6f239544f0a5b858a6d.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\21\21baa5abf7e1ad0dc92c26af57bd7db73a9ef88c.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\bd\bdf25313579f13a72d9a78ad66c26c9ff332ec0f.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\e5\e564ebc5c1bdaf42f1d828661a14680eb5a72b3a.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\f1\f1bee11744577da9013ebad842acc48b8fa29c1b.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\6a\6a1a10593c45833b28ec3f09763372f45f15389c.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\9f\9f7abaff0701430d0dfe2827724c3a6cc88a41a9.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\d0\d0e8763b7a6f53b9c4afb9cdacc11a9aec8d7f39.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\4b\4b92732d97156b0f4f0f6f9552c440331430c19c.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\78\78ac16f6b5bc709fc50e63e48a2fed52c614d75d.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\b5\b54701432d558d2caab57ba3b6cc374a9f8a35e1.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\c3\c389400d98e053b5dbd5cab0ddb4a711e26ee1a0.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\2a\2acf529146778b815c16d7346a9eb6faf12080de.zip
Could not locate cached archive: C:\Users\31966\AppData\Local\vcpkg\archives\3e\3e566c1ef7f5da06eae8bf955b17f937dca2d06c.zip
Starting package 1/89: boost-throw-exception:x64-windows
Building package boost-throw-exception[core]:x64-windows...
-- Downloading https://github.com/boostorg/throw_exception/archive/boost-1.75.0.tar.gz -> boostorg-throw_exception-boost-1.75.0.tar.gz...
-- Extracting source D:/Project/VS2019/GITHUB/STL/vcpkg/downloads/boostorg-throw_exception-boost-1.75.0.tar.gz
-- Using source at D:/Project/VS2019/GITHUB/STL/vcpkg/buildtrees/boost-throw-exception/src/ost-1.75.0-3caab931aa.clean
-- Packaging headers
-- Packaging headers done
-- Using cached D:/Project/VS2019/GITHUB/STL/vcpkg/downloads/boost_LICENSE_1_0.txt
-- Installing: D:/Project/VS2019/GITHUB/STL/vcpkg/packages/boost-throw-exception_x64-windows/share/boost-throw-exception/usage
-- Installing: D:/Project/VS2019/GITHUB/STL/vcpkg/packages/boost-throw-exception_x64-windows/share/boost-throw-exception/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\31966\AppData\Local\vcpkg\archives\6a\6a623885356576ec30c8e39bc9479930d30f9d8f.zip
Building package boost-throw-exception[core]:x64-windows... done
Installing package boost-throw-exception[core]:x64-windows...
Installing package boost-throw-exception[core]:x64-windows... done
Elapsed time for package boost-throw-exception:x64-windows: 1.875 s
Starting package 2/89: boost-array:x64-windows
Building package boost-array[core]:x64-windows...
-- Downloading https://github.com/boostorg/array/archive/boost-1.75.0.tar.gz -> boostorg-array-boost-1.75.0.tar.gz...
-- Extracting source D:/Project/VS2019/GITHUB/STL/vcpkg/downloads/boostorg-array-boost-1.75.0.tar.gz
-- Using source at D:/Project/VS2019/GITHUB/STL/vcpkg/buildtrees/boost-array/src/ost-1.75.0-c1b398d8e9.clean
-- Packaging headers
-- Packaging headers done
-- Using cached D:/Project/VS2019/GITHUB/STL/vcpkg/downloads/boost_LICENSE_1_0.txt
-- Installing: D:/Project/VS2019/GITHUB/STL/vcpkg/packages/boost-array_x64-windows/share/boost-array/usage
-- Installing: D:/Project/VS2019/GITHUB/STL/vcpkg/packages/boost-array_x64-windows/share/boost-array/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\31966\AppData\Local\vcpkg\archives\bc\bcb4e3ee77163bd4f133c9a582398d9b1151a54d.zip
Building package boost-array[core]:x64-windows... done
Installing package boost-array[core]:x64-windows...
Installing package boost-array[core]:x64-windows... done
Elapsed time for package boost-array:x64-windows: 1.971 s
Starting package 3/89: boost-bind:x64-windows
Building package boost-bind[core]:x64-windows...
-- Downloading https://github.com/boostorg/bind/archive/boost-1.75.0.tar.gz -> boostorg-bind-boost-1.75.0.tar.gz...
-- Extracting source D:/Project/VS2019/GITHUB/STL/vcpkg/downloads/boostorg-bind-boost-1.75.0.tar.gz
-- Using source at D:/Project/VS2019/GITHUB/STL/vcpkg/buildtrees/boost-bind/src/ost-1.75.0-62a4d45ec4.clean
-- Packaging headers
-- Packaging headers done
-- Using cached D:/Project/VS2019/GITHUB/STL/vcpkg/downloads/boost_LICENSE_1_0.txt
-- Installing: D:/Project/VS2019/GITHUB/STL/vcpkg/packages/boost-bind_x64-windows/share/boost-bind/usage
-- Installing: D:/Project/VS2019/GITHUB/STL/vcpkg/packages/boost-bind_x64-windows/share/boost-bind/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\31966\AppData\Local\vcpkg\archives\da\da218ea5c4aea35bb54acbbac8cf34e0445adf7f.zip
Building package boost-bind[core]:x64-windows... done
Installing package boost-bind[core]:x64-windows...
Installing package boost-bind[core]:x64-windows... done
Elapsed time for package boost-bind:x64-windows: 2.062 s
Starting package 4/89: boost-type-traits:x64-windows
Building package boost-type-traits[core]:x64-windows...
-- Downloading https://github.com/boostorg/type_traits/archive/boost-1.75.0.tar.gz -> boostorg-type_traits-boost-1.75.0.tar.gz...
-- Downloading https://github.com/boostorg/type_traits/archive/boost-1.75.0.tar.gz... Failed. Status: 28;"Timeout was reached"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:184 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".

      If error with status 4 (Issue #15434),
      try setting "http://user:password@your-proxy-ip-address:port/".

      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:147 (vcpkg_download_distfile)
  ports/boost-type-traits/portfile.cmake:3 (vcpkg_from_github)
  scripts/ports.cmake:139 (include)

Error: Building package boost-type-traits:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-type-traits:x64-windows
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

Additionally, attach any relevant sections from the log files above.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by PhoebeHui** [comment]
@huolingfei, could you try the solution provided by https://github.com/microsoft/vcpkg/issues/13348#issue-692784879 and see if it works for you?

**Comment by PhoebeHui** [comment]
@huolingfei, please reopen this if it still be a problem for you.
