### ISSUE TITLE
bootstrap-vcpkg.bat failed - why doesn't it find winhttp.lib?

### ISSUE THREAD

**Issue by macsinus** [Microsoft/vcpkg#1819]
I have Windows 7 and Visual Studio Professional 2017.
I downloaded vcpkg-master.zip, expanded it and ran bootstrap-vcpkg.bat in a command window (with Administrator rights) and got the following:

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Alle Rechte vorbehalten.

C:\Windows\system32>cd C:\Users\mac.SINUS\Downloads\vcpkg-master\vcpkg-master

C:\Users\mac.SINUS\Downloads\vcpkg-master\vcpkg-master>bootstrap-vcpkg.bat
Microsoft (R)-Buildmodul, Version 15.3.409.57025 für .NET Framework
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

Der Buildvorgang wurde am 13.09.2017 10:52:40 gestartet.
     1>Projekt "C:\Users\mac.SINUS\Downloads\vcpkg-master\vcpkg-master\toolsrc\dirs.proj" auf Knoten "1" (Standardziele).
     1>Das Projekt "C:\Users\mac.SINUS\Downloads\vcpkg-master\vcpkg-master\toolsrc\dirs.proj" (1) erstellt "C:\Users\mac.SINUS\Downloads\vcpkg-m
       aster\vcpkg-master\toolsrc\vcpkg\vcpkg.vcxproj" (2) auf Knoten "1", Clean Ziel(e).
     2>CoreClean:
         Das Verzeichnis "Release\" wird erstellt.
     2>Das Projekt "C:\Users\mac.SINUS\Downloads\vcpkg-master\vcpkg-master\toolsrc\vcpkg\vcpkg.vcxproj" (2) erstellt "C:\Users\mac.SINUS\Downloa
       ds\vcpkg-master\vcpkg-master\toolsrc\vcpkglib\vcpkglib.vcxproj" (3) auf Knoten "1", Clean Ziel(e).
     3>CoreClean:
         Das Verzeichnis "Release\" wird erstellt.
     3>Die Erstellung von Projekt "C:\Users\mac.SINUS\Downloads\vcpkg-master\vcpkg-master\toolsrc\vcpkglib\vcpkglib.vcxproj" ist abgeschlossen (
       Clean Ziel(e)).
     2>Die Erstellung von Projekt "C:\Users\mac.SINUS\Downloads\vcpkg-master\vcpkg-master\toolsrc\vcpkg\vcpkg.vcxproj" ist abgeschlossen (Clean
       Ziel(e)).
     1>Das Projekt "C:\Users\mac.SINUS\Downloads\vcpkg-master\vcpkg-master\toolsrc\dirs.proj" (1) erstellt "C:\Users\mac.SINUS\Downloads\vcpkg-m
       aster\vcpkg-master\toolsrc\vcpkgmetricsuploader\vcpkgmetricsuploader.vcxproj" (4) auf Knoten "1", Clean Ziel(e).
     4>CoreClean:
         Das Verzeichnis "Release\" wird erstellt.
     4>Die Erstellung von Projekt "C:\Users\mac.SINUS\Downloads\vcpkg-master\vcpkg-master\toolsrc\vcpkgmetricsuploader\vcpkgmetricsuploader.vcxp
       roj" ist abgeschlossen (Clean Ziel(e)).
     1>Das Projekt "C:\Users\mac.SINUS\Downloads\vcpkg-master\vcpkg-master\toolsrc\dirs.proj" (1) erstellt "C:\Users\mac.SINUS\Downloads\vcpkg-m
       aster\vcpkg-master\toolsrc\vcpkg\vcpkg.vcxproj" (2:2) auf Knoten "1", Build Ziel(e).
   2:2>Das Projekt "C:\Users\mac.SINUS\Downloads\vcpkg-master\vcpkg-master\toolsrc\vcpkg\vcpkg.vcxproj" (2:2) erstellt "C:\Users\mac.SINUS\Downl
       oads\vcpkg-master\vcpkg-master\toolsrc\vcpkglib\vcpkglib.vcxproj" (3:4) auf Knoten "1" (Standardziele).
     3>PrepareForBuild:
         Das Verzeichnis "C:\Users\mac.SINUS\Downloads\vcpkg-master\vcpkg-master\toolsrc\Release\" wird erstellt.
         Das Verzeichnis "Release\vcpkglib.tlog\" wird erstellt.
       InitializeBuildStatus:
         "Release\vcpkglib.tlog\unsuccessfulbuild" wird erstellt, da "AlwaysCreate" angegeben wurde.
       ClCompile:
         C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.11.25503\bin\HostX86\x86\CL.exe /c /I..\include /Zi /
         nologo /W3 /WX- /diagnostics:classic /sdl /MP /O2 /Oi /Oy- /GL /D DISABLE_METRICS=0 /D "VCPKG_VERSION=-unknownhash" /D _MBCS /D NDEBUG
         /D _MBCS /Gm- /EHsc /MD /GS /Gy /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Yc"pch.h" /Fp"Release\vcpkglib.pch" /Fo"Release\\" /Fd
         "Release\vcpkglib.pdb" /Gd /TP /analyze- /errorReport:queue /std:c++latest ..\src\pch.cpp
         pch.cpp
         C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.11.25503\bin\HostX86\x86\CL.exe /c /I..\include /Zi /
         nologo /W3 /WX- /diagnostics:classic /sdl /MP /O2 /Oi /Oy- /GL /D DISABLE_METRICS=0 /D "VCPKG_VERSION=-unknownhash" /D _MBCS /D NDEBUG
         /D _MBCS /Gm- /EHsc /MD /GS /Gy /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Yu"pch.h" /Fp"Release\vcpkglib.pch" /Fo"Release\\" /Fd
         "Release\vcpkglib.pdb" /Gd /TP /analyze- /errorReport:queue /std:c++latest ..\src\BinaryParagraph.cpp ..\src\commands_ci.cpp ..\src\com
         mands_depends.cpp ..\src\commands_env.cpp ..\src\commands_export.cpp ..\src\LineInfo.cpp ..\src\ParagraphParseResult.cpp ..\src\vcpkg_B
         uild.cpp ..\src\vcpkg_Build_BuildPolicy.cpp ..\src\coff_file_reader.cpp ..\src\commands_available_commands.cpp ..\src\commands_build.cp
         p ..\src\commands_build_external.cpp ..\src\commands_cache.cpp ..\src\commands_contact.cpp ..\src\commands_create.cpp ..\src\commands_e
         dit.cpp ..\src\commands_hash.cpp ..\src\commands_help.cpp ..\src\commands_import.cpp ..\src\commands_install.cpp ..\src\commands_integr
         ate.cpp ..\src\commands_list.cpp ..\src\commands_owns.cpp ..\src\commands_portsdiff.cpp ..\src\commands_remove.cpp ..\src\commands_sear
         ch.cpp ..\src\commands_update.cpp ..\src\commands_version.cpp ..\src\MachineType.cpp ..\src\metrics.cpp ..\src\PostBuildLint.cpp ..\src
         \PostBuildLint_BuildType.cpp ..\src\vcpkg_Chrono.cpp ..\src\vcpkglib.cpp ..\src\PackageSpec.cpp ..\src\PackageSpecParseResult.cpp ..\sr
         c\Paragraphs.cpp ..\src\SourceParagraph.cpp ..\src\StatusParagraph.cpp ..\src\StatusParagraphs.cpp ..\src\triplet.cpp ..\src\vcpkg_Glob
         alState.cpp ..\src\vcpkg_Parse.cpp ..\src\vcpkg_Checks.cpp ..\src\VcpkgCmdArguments.cpp ..\src\vcpkg_Dependencies.cpp ..\src\vcpkg_Enum
         s.cpp ..\src\vcpkg_Files.cpp ..\src\vcpkg_Input.cpp ..\src\VcpkgPaths.cpp ..\src\vcpkg_Strings.cpp ..\src\vcpkg_System.cpp ..\src\Versi
         onT.cpp
         BinaryParagraph.cpp
         commands_ci.cpp
         commands_depends.cpp
         commands_env.cpp
         commands_export.cpp
         LineInfo.cpp
         ParagraphParseResult.cpp
         vcpkg_Build.cpp
         vcpkg_Build_BuildPolicy.cpp
         coff_file_reader.cpp
         commands_available_commands.cpp
         commands_build.cpp
         commands_build_external.cpp
         commands_cache.cpp
         commands_contact.cpp
         commands_create.cpp
         commands_edit.cpp
         commands_hash.cpp
         commands_help.cpp
         commands_import.cpp
         commands_install.cpp
         commands_integrate.cpp
         commands_list.cpp
         commands_owns.cpp
         commands_portsdiff.cpp
         commands_remove.cpp
         commands_search.cpp
         commands_update.cpp
         commands_version.cpp
         MachineType.cpp
         metrics.cpp
         PostBuildLint.cpp
         PostBuildLint_BuildType.cpp
         vcpkg_Chrono.cpp
         vcpkglib.cpp
         PackageSpec.cpp
         PackageSpecParseResult.cpp
         Paragraphs.cpp
         SourceParagraph.cpp
         StatusParagraph.cpp
         StatusParagraphs.cpp
         triplet.cpp
         vcpkg_GlobalState.cpp
         vcpkg_Parse.cpp
         vcpkg_Checks.cpp
         VcpkgCmdArguments.cpp
         vcpkg_Dependencies.cpp
         vcpkg_Enums.cpp
         vcpkg_Files.cpp
         vcpkg_Input.cpp
         VcpkgPaths.cpp
         vcpkg_Strings.cpp
         vcpkg_System.cpp
         VersionT.cpp
       Lib:
         C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.11.25503\bin\HostX86\x86\Lib.exe /OUT:"C:\Users\mac.S
         INUS\Downloads\vcpkg-master\vcpkg-master\toolsrc\Release\vcpkglib.lib" /NOLOGO /LTCG Release\BinaryParagraph.obj
         Release\commands_ci.obj
         Release\commands_depends.obj
         Release\commands_env.obj
         Release\commands_export.obj
         Release\LineInfo.obj
         Release\ParagraphParseResult.obj
         Release\vcpkg_Build.obj
         Release\vcpkg_Build_BuildPolicy.obj
         Release\coff_file_reader.obj
         Release\commands_available_commands.obj
         Release\commands_build.obj
         Release\commands_build_external.obj
         Release\commands_cache.obj
         Release\commands_contact.obj
         Release\commands_create.obj
         Release\commands_edit.obj
         Release\commands_hash.obj
         Release\commands_help.obj
         Release\commands_import.obj
         Release\commands_install.obj
         Release\commands_integrate.obj
         Release\commands_list.obj
         Release\commands_owns.obj
         Release\commands_portsdiff.obj
         Release\commands_remove.obj
         Release\commands_search.obj
         Release\commands_update.obj
         Release\commands_version.obj
         Release\MachineType.obj
         Release\metrics.obj
         Release\pch.obj
         Release\PostBuildLint.obj
         Release\PostBuildLint_BuildType.obj
         Release\vcpkg_Chrono.obj
         Release\vcpkglib.obj
         Release\PackageSpec.obj
         Release\PackageSpecParseResult.obj
         Release\Paragraphs.obj
         Release\SourceParagraph.obj
         Release\StatusParagraph.obj
         Release\StatusParagraphs.obj
         Release\triplet.obj
         Release\vcpkg_GlobalState.obj
         Release\vcpkg_Parse.obj
         Release\vcpkg_Checks.obj
         Release\VcpkgCmdArguments.obj
         Release\vcpkg_Dependencies.obj
         Release\vcpkg_Enums.obj
         Release\vcpkg_Files.obj
         Release\vcpkg_Input.obj
         Release\VcpkgPaths.obj
         Release\vcpkg_Strings.obj
         Release\vcpkg_System.obj
         Release\VersionT.obj
         vcpkglib.vcxproj -> C:\Users\mac.SINUS\Downloads\vcpkg-master\vcpkg-master\toolsrc\Release\vcpkglib.lib
       FinalizeBuildStatus:
         Die Datei "Release\vcpkglib.tlog\unsuccessfulbuild" wird gelöscht.
         Aktualisieren des Timestamps von "Release\vcpkglib.tlog\vcpkglib.lastbuildstate".
     3>Die Erstellung von Projekt "C:\Users\mac.SINUS\Downloads\vcpkg-master\vcpkg-master\toolsrc\vcpkglib\vcpkglib.vcxproj" ist abgeschlossen (
       Standardziele).
     2>PrepareForBuild:
         Das Verzeichnis "Release\vcpkg.tlog\" wird erstellt.
       InitializeBuildStatus:
         "Release\vcpkg.tlog\unsuccessfulbuild" wird erstellt, da "AlwaysCreate" angegeben wurde.
       ClCompile:
         C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.11.25503\bin\HostX86\x86\CL.exe /c /I..\include /Zi /
         nologo /W3 /WX- /diagnostics:classic /sdl /MP /O2 /Oi /Oy- /GL /D _MBCS /D NDEBUG /D _MBCS /Gm- /EHsc /MD /GS /Gy /fp:precise /Zc:wchar
         _t /Zc:forScope /Zc:inline /Fo"Release\\" /Fd"Release\vc141.pdb" /Gd /TP /analyze- /errorReport:queue /std:c++latest ..\src\vcpkg.cpp
         vcpkg.cpp
       Link:
         C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.11.25503\bin\HostX86\x86\link.exe /ERRORREPORT:QUEUE
         /OUT:"C:\Users\mac.SINUS\Downloads\vcpkg-master\vcpkg-master\toolsrc\Release\vcpkg.exe" /NOLOGO winhttp.lib version.lib kernel32.lib us
         er32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib kernel32.
         lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MA
         NIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG:FULL /PDB:"C:\Users\mac.SINUS\Downloads\vcpkg-master\vc
         pkg-master\toolsrc\Release\vcpkg.pdb" /OPT:REF /OPT:ICF /LTCG:incremental /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:\Users\mac.SINUS\D
         ownloads\vcpkg-master\vcpkg-master\toolsrc\Release\vcpkg.lib" /MACHINE:X86 /SAFESEH Release\vcpkg.obj
         "C:\Users\mac.SINUS\Downloads\vcpkg-master\vcpkg-master\toolsrc\Release\vcpkglib.lib"
     2>LINK : fatal error LNK1181: Eingabedatei "winhttp.lib" kann nicht ge÷ffnet werden. [C:\Users\mac.SINUS\Downloads\vcpkg-master\vcpkg-maste
       r\toolsrc\vcpkg\vcpkg.vcxproj]
     2>Die Erstellung des Projekts "C:\Users\mac.SINUS\Downloads\vcpkg-master\vcpkg-master\toolsrc\vcpkg\vcpkg.vcxproj" ist abgeschlossen, Build
        Ziel(e) -- FEHLER.
     1>Das Projekt "C:\Users\mac.SINUS\Downloads\vcpkg-master\vcpkg-master\toolsrc\dirs.proj" (1) erstellt "C:\Users\mac.SINUS\Downloads\vcpkg-m
       aster\vcpkg-master\toolsrc\vcpkgmetricsuploader\vcpkgmetricsuploader.vcxproj" (4:2) auf Knoten "1", Build Ziel(e).
     4>PrepareForBuild:
         Das Verzeichnis "Release\vcpkgmet.7D6FDEEB.tlog\" wird erstellt.
       InitializeBuildStatus:
         "Release\vcpkgmet.7D6FDEEB.tlog\unsuccessfulbuild" wird erstellt, da "AlwaysCreate" angegeben wurde.
       ClCompile:
         C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.11.25503\bin\HostX86\x86\CL.exe /c /I..\include /Zi /
         nologo /W3 /WX- /diagnostics:classic /sdl /MP /O2 /Oi /Oy- /GL /D _MBCS /D NDEBUG /D _MBCS /Gm- /EHsc /MD /GS /Gy /fp:precise /Zc:wchar
         _t /Zc:forScope /Zc:inline /Fo"Release\\" /Fd"Release\vc141.pdb" /Gd /TP /analyze- /errorReport:queue /std:c++latest ..\src\vcpkg_metri
         cs_uploader.cpp
         vcpkg_metrics_uploader.cpp
       Link:
         C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.11.25503\bin\HostX86\x86\link.exe /ERRORREPORT:QUEUE
         /OUT:"C:\Users\mac.SINUS\Downloads\vcpkg-master\vcpkg-master\toolsrc\Release\vcpkgmetricsuploader.exe" /NOLOGO winhttp.lib version.lib
         kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp3
         2.lib kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib o
         dbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG:FULL /PDB:"C:\Users\mac.SINUS\Downloads\
         vcpkg-master\vcpkg-master\toolsrc\Release\vcpkgmetricsuploader.pdb" /OPT:REF /OPT:ICF /LTCG:incremental /TLBID:1 /DYNAMICBASE /NXCOMPAT
          /IMPLIB:"C:\Users\mac.SINUS\Downloads\vcpkg-master\vcpkg-master\toolsrc\Release\vcpkgmetricsuploader.lib" /MACHINE:X86 /SAFESEH Releas
         e\vcpkg_metrics_uploader.obj
         "C:\Users\mac.SINUS\Downloads\vcpkg-master\vcpkg-master\toolsrc\Release\vcpkglib.lib"
     4>LINK : fatal error LNK1181: Eingabedatei "winhttp.lib" kann nicht ge÷ffnet werden. [C:\Users\mac.SINUS\Downloads\vcpkg-master\vcpkg-maste
       r\toolsrc\vcpkgmetricsuploader\vcpkgmetricsuploader.vcxproj]
     4>Die Erstellung des Projekts "C:\Users\mac.SINUS\Downloads\vcpkg-master\vcpkg-master\toolsrc\vcpkgmetricsuploader\vcpkgmetricsuploader.vcx
       proj" ist abgeschlossen, Build Ziel(e) -- FEHLER.
     1>Die Erstellung des Projekts "C:\Users\mac.SINUS\Downloads\vcpkg-master\vcpkg-master\toolsrc\dirs.proj" ist abgeschlossen (Standardziele)
       -- FEHLER.

Fehler beim Buildvorgang.

       "C:\Users\mac.SINUS\Downloads\vcpkg-master\vcpkg-master\toolsrc\dirs.proj" (Standardziel) (1) ->
       "C:\Users\mac.SINUS\Downloads\vcpkg-master\vcpkg-master\toolsrc\vcpkg\vcpkg.vcxproj" (Build Ziel) (2:2) ->
       (Link Ziel) ->
         LINK : fatal error LNK1181: Eingabedatei "winhttp.lib" kann nicht ge÷ffnet werden. [C:\Users\mac.SINUS\Downloads\vcpkg-master\vcpkg-mas
       ter\toolsrc\vcpkg\vcpkg.vcxproj]

       "C:\Users\mac.SINUS\Downloads\vcpkg-master\vcpkg-master\toolsrc\dirs.proj" (Standardziel) (1) ->
       "C:\Users\mac.SINUS\Downloads\vcpkg-master\vcpkg-master\toolsrc\vcpkgmetricsuploader\vcpkgmetricsuploader.vcxproj" (Build Ziel) (4:2) ->
         LINK : fatal error LNK1181: Eingabedatei "winhttp.lib" kann nicht ge÷ffnet werden. [C:\Users\mac.SINUS\Downloads\vcpkg-master\vcpkg-mas
       ter\toolsrc\vcpkgmetricsuploader\vcpkgmetricsuploader.vcxproj]

    0 Warnung(en)
    2 Fehler

Verstrichene Zeit 00:00:31.09
Copy-Item : Der Pfad "C:\Users\mac.SINUS\Downloads\vcpkg-master\vcpkg-master\toolsrc\Release\vcpkg.exe" kann nicht gefunden werden, da er nicht
vorhanden ist.
Bei C:\Users\mac.SINUS\Downloads\vcpkg-master\vcpkg-master\scripts\bootstrap.ps1:49 Zeichen:14
+     Copy-Item <<<<  $vcpkgSourcesPath\Release\vcpkg.exe $vcpkgRootDir\vcpkg.exe | Out-Null
    + CategoryInfo          : ObjectNotFound: (C:\Users\mac.SI...lease\vcpkg.exe:String) [Copy-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand

Copy-Item : Der Pfad "C:\Users\mac.SINUS\Downloads\vcpkg-master\vcpkg-master\toolsrc\Release\vcpkgmetricsuploader.exe" kann nicht gefunden werde
n, da er nicht vorhanden ist.
Bei C:\Users\mac.SINUS\Downloads\vcpkg-master\vcpkg-master\scripts\bootstrap.ps1:50 Zeichen:14
+     Copy-Item <<<<  $vcpkgSourcesPath\Release\vcpkgmetricsuploader.exe $vcpkgRootDir\scripts\vcpkgmetricsuploader.exe | Out-Null
    + CategoryInfo          : ObjectNotFound: (C:\Users\mac.SI...icsuploader.exe:String) [Copy-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand

C:\Users\mac.SINUS\Downloads\vcpkg-master\vcpkg-master>

**Comment by macsinus** [comment]
Although the batch compilation above didn't work, there is a vcpkg.sln in vcpkg-master\toolsrc which does compile (and which I will soon try out). It might be better to mention this on the website rather than the batch compilation.

**Comment by alexkaratarakis** [comment]
Reopening this because there seems to be an issue with bootstrap. I will take a look.

**Comment by NancyLi1013** [comment]
Please open a new issue if this is still a problem for you.
