### ISSUE TITLE
CCfits not working

### ISSUE THREAD

**Issue by antoinech13** [microsoft/vcpkg#18193]
**Host Environment**
- OS: Windows/
- Compiler: Visual Studio 16 2019

**To Reproduce**
- i created c:\src\vcpkg
- open a cmd and execute cd c:\src\vcpkg
- git clone https://github.com/microsoft/vcpkg
- .\vcpkg\bootstrap-vcpkg.bat
- .\vcpkg\vcpkg install ccfits
- .\vcpkg\vcpkg integrate install
- last point, open a visual studio project and just #include "CCfits.h"

- VS will say that it don't arrive to find ccfits so in project properties -> C/C++ add include C:\src\vcpkg\vcpkg\packages\ccfits_x86-windows\include\CCfits
- in the linker->general add path C:\src\vcpkg\vcpkg\packages\ccfits_x86-windows\lib
- in linker->input add CCfits.lib

**Failure logs** 
Just with include in the open file, VS return: 

LNK2019	unresolved external symbol _main referenced in function "int __cdecl invoke_main(void)" (?invoke_main@@YAHXZ)
C:\...\MSVCRTD.lib(exe_main.obj)	1	

can someone help me with this pls?

**Comment by JackBoosY** [comment]
First, you should include `CCfits/CCfits.h` instead of `CCfits.h`.
Second, the library doesn't need to be added.
Last, it does have a bug with usage, but I didn't repro the link error on my machine.
