### ISSUE TITLE
DOC: Unclear command line format in README

### ISSUE THREAD

**Issue by souris-dev** [microsoft/vcpkg#18191]
*Issue:*

The Quick Start section for Windows in the README has a command format for installing x64 libraries, which goes like this in the README:

```cmd
> .\vcpkg\vcpkg install package:x64-windows
```

The part `package:x64-windows` might seem a little unclear to people using the tool for the first time as it is not explicit/clear that in this, `package` is to be substituted with the appropriate package name. The command formats before this one denote this by using square brackets to make the substitution clear:

```cmd
> .\vcpkg\vcpkg install [packages to install]
```

*Fix:*

Adding square brackets around the word `package` (for uniformity) to clarify the substitution could make things clearer to the reader, for example:

```cmd
> .\vcpkg\vcpkg install [package name]:x64-windows
```

**Comment by Ascor8522** [comment]
Just got this exact issue moments ago.
Tho I have some experience with C and C++ on other platforms I'm pretty new to vcpkg.

I initially though one had to install a package named `package:x64-windows` to add x64 compilation support for Windows.


This issue saved me quite a bit of time 👍
