### ISSUE TITLE
VCPKG reads through `subst`, but recommends `subst`.

### ISSUE THREAD

**Issue by Faaux** [microsoft/vcpkg#18208]
**Bug**
vcpkg reads through `subst` due to `canonical` calls.

**Environment**
- OS: Windows

**To Reproduce**
1. Have a repo with a manifest and vcpkg as a submodule
2. `subst W: %PATH_TO_REPO%`
3. `W:`
4. `vcpkg\vcpkg.exe install`

VCPKG will read through subst and return a path to e.g. `C:\my\project\path\vcpkg`

**Expected behavior**
VCPKG does not read through `subst` or long filepaths are supported and maintained (#11119)

**Additional context**
Taken from a discussion in Discord (IncludeCPP):

Using vcpkg as a submodule in a CI scenario with CMake and manifests. Path to the repo and submodule are non-changeable and rather long. Some packages (in this case qt5-core and qt5-webengine) need to have very short `VCPKG_ROOT` paths. VCPKG recommends using subst (see `vcpkg_buildpath_length_warning.cmake`).

** Code Culprit **
https://github.com/microsoft/vcpkg-tool/blob/d37abb3e83a3a639931886b1e6c6bb56d180e756/src/vcpkg/base/files.cpp#L1291

/cc @strega-nil-ms See our discussion in Discord

**Comment by BillyONeal** [comment]
Should have been fixed a long time ago.
