### ISSUE TITLE
[boost] update to 1.76

### ISSUE THREAD

**Issue by TheCelebrimbor** [microsoft/vcpkg#18204]
Library name: Boost

New version number: 1.76.0

Seems there are lots of breaking changes in 1.76.0. Need to retain the old port (1.75.0) maybe ?

**Comment by PhoebeHui** [comment]
Closing in favor of https://github.com/microsoft/vcpkg/issues/17330, which we already have a PR https://github.com/microsoft/vcpkg/pull/17335 for this.
