### ISSUE TITLE
How do I manually update my poco portfile.cmake?

### ISSUE THREAD

**Issue by sundarsabapathi** [microsoft/vcpkg#18205]
I want to enable netssl and crypto components in poco portfile.cmake. I enabled vcpkg version feature in my project.

**Comment by mathisloge** [comment]
for netssl you will need to install it with the feature flag. 
`vcpkg install poco[netssl]`

**Comment by sundarsabapathi** [comment]
I am using vcpkg in manifest mode. We cannot use "vcpkg install" is manifest mode is it right ?

**Comment by sundarsabapathi** [comment]
I manually update my poco portfil.cmake in /ports/poco/portfile.cmake  with the below lines
                      - -DENABLE_NETSSL=ON
                      - -DENABLE_CRYPTO=ON
I am using vcpkg in manifest mode while vcpkg installing POCO in manifest mode it always referring the portfile in the GitHub (https://github.com/Microsoft/vcpkg/blob/master/ports/poco/portfile.cmake) it won't consider my changes in the /ports/poco/portfile.cmake.

**Comment by dg0yt** [comment]
> I am using vcpkg in manifest mode. We cannot use "vcpkg install" in manifest mode is it right ?

In manifest mode, you need to request the feature for the dependency in the manifest file. 
https://github.com/microsoft/vcpkg/blob/master/docs/users/manifests.md

**Comment by sundarsabapathi** [comment]
vcpkg.json
`{
    "name": "cosmos-versions",
    "version": "1.0.0",
    "builtin-baseline": "9d7244f2f6a4f6a34c4e0b3ecbf391323e379a43",
	"dependencies": 
	[ 
	    {
            "name": "poco",
            "features": [ "netssl"]
        }
    ]
}`

I request the feature for the dependency in the manifest file. The following error are thrown while building poco using cmake

`Building package poco[core,netssl]:x86-windows...
-- Installing port from location: C:\Users\User\projects\mcruncher\nectar\nectar-cpp\cosmos\libs\vcpkg\buildtrees\versioning\versions\poco\e9c709300900158cdfcad75965e85b04413c8d5b
-- Downloading https://github.com/pocoproject/poco/archive/3fc3e5f5b8462f7666952b43381383a79b8b5d92.tar.gz -> pocoproject-poco-3fc3e5f5b8462f7666952b43381383a79b8b5d92.tar.gz...
-- Extracting source C:/Users/User/projects/mcruncher/nectar/nectar-cpp/cosmos/libs/vcpkg/downloads/pocoproject-poco-3fc3e5f5b8462f7666952b43381383a79b8b5d92.tar.gz
-- Applying patch static_pcre.patch
-- Applying patch arm64_pcre.patch
-- Applying patch fix_dependency.patch
-- Applying patch fix-feature-sqlite3.patch
-- Using source at C:/Users/User/projects/mcruncher/nectar/nectar-cpp/cosmos/libs/vcpkg/buildtrees/poco/src/a79b8b5d92-4a21266219.clean
CMake Deprecation Warning at scripts/cmake/vcpkg_check_features.cmake:182 (message):
  calling `vcpkg_check_features` without the `FEATURES` keyword has been
  deprecated.

      Please add the `FEATURES` keyword to the call.
Call Stack (most recent call first):
  buildtrees/versioning/versions/poco/e9c709300900158cdfcad75965e85b04413c8d5b/portfile.cmake:28 (vcpkg_check_features)
  scripts/ports.cmake:139 (include)


-- Found external ninja('1.10.2').
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
    Command failed: ninja -v
    Working Directory: C:/Users/User/cosmos/libs/vcpkg/buildtrees/poco/x86-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\Users\User\cosmos\libs\vcpkg\buildtrees\poco\config-x86-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:323 (vcpkg_execute_required_process)
  buildtrees/versioning/versions/poco/e9c709300900158cdfcad75965e85b04413c8d5b/portfile.cmake:43 (vcpkg_configure_cmake)
  scripts/ports.cmake:139 (include)


Error: Building package poco:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: poco:x86-windows
  Vcpkg version: 2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9`

**Comment by PhoebeHui** [comment]
@sundarsabapathi, could you attach C:\Users\User\cosmos\libs\vcpkg\buildtrees\poco\config-x86-windows-out.log?

**Comment by sundarsabapathi** [comment]
Hi @PhoebeHui  I attached the output log 
[config-x86-windows-out.log](https://github.com/microsoft/vcpkg/files/6574283/config-x86-windows-out.log)

**Comment by PhoebeHui** [comment]
@sundarsabapathi, could you unset '-DENABLE_NETSSL=ON -DENABLE_CRYPTO=ON' in your portfile.cmake, and see if the issue still repro? I tried  ./vcpkg install poco[netssl], and it install successfully for me.

**Comment by sundarsabapathi** [comment]
Sorry @PhoebeHui, This time I am not make any change in poco portfile.cmake . I defined through the manifest file only 

```
{
    "name": "cosmos-versions",
    "version": "1.0.0",
    "builtin-baseline": "9d7244f2f6a4f6a34c4e0b3ecbf391323e379a43",
	"dependencies": 
	[ 
	    {
                  "name": "poco",
                  "features": [ "netssl"]
           }
    ]
}
```


Hi @PhoebeHui , What I actually try to do in my project is I want to enable netssl and crypto components in poco portfile.cmake. Because my projects needs netssl and crytpo components. So I manually update my poco portfile.cmake in /ports/poco/portfile.cmake with the below lines

```
set(OPENSSL_DIR  ..\\..\\installed\\x86-windows\\include\\openssl)
set(OPENSSL_INCLUDE %OPENSSL_DIR%)
set(OPENSSL_LIB  ..\\..\\installed\\x86-windows\\lib)
set(INCLUDE  %INCLUDE%;%OPENSSL_INCLUDE%)
set(LIB %LIB%;%OPENSSL_LIB%)

-DENABLE_NETSSL=ON
-DENABLE_CRYPTO=ON

```

I am using vcpkg in manifest mode while vcpkg installing POCO in manifest mode it always referring the portfile in the GitHub (https://github.com/Microsoft/vcpkg/blob/master/ports/poco/portfile.cmake) it won't consider my changes in the /ports/poco/portfile.cmake.


[portfile.zip](https://github.com/microsoft/vcpkg/files/6574556/portfile.zip)

**Comment by PhoebeHui** [comment]
@sundarsabapathi, you don't need to set them on since when you install the netssl feature, it will enable netssl and crypto, see https://github.com/microsoft/vcpkg/blob/master/ports/poco/portfile.cmake#L30

**Comment by PhoebeHui** [comment]
I see,  the problem is openssl requried on non-windows platform, see https://github.com/microsoft/vcpkg/blob/master/ports/poco/vcpkg.json#L31

Failures:
```
CMake Error at C:/Users/User/cosmos/libs/vcpkg/downloads/tools/cmake-3.20.2-windows/cmake-3.20.2-windows-i386/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY
  OPENSSL_INCLUDE_DIR)
Call Stack (most recent call first):
```

**Comment by PhoebeHui** [comment]
Openssl removed from poco dependency via PR https://github.com/microsoft/vcpkg/pull/16526

**Comment by sundarsabapathi** [comment]
> @sundarsabapathi, you don't need to set them on since when you install the netssl feature, it will enable netssl and crypto, see https://github.com/microsoft/vcpkg/blob/master/ports/poco/portfile.cmake#L30

Sorry @PhonbeHui, I no need to enable netssl anywhere like this "-DENABLE_NETSSL=ON" is it right ?

**Comment by sundarsabapathi** [comment]
Sorry @PhoebeHui , In manifest mode if I execute this command "./vcpkg install poco[netssl]". It print the following error messages

**Error: 'install' requires 0 arguments, but 1 were provided.**. So only enable netssl  components through manifest file 

If I run with the below manifests file 
        ```
   {
                  "name": "poco",
                  "features": [ "netssl"]
           }
```

It enable the components while building using cmake '-DENABLE_NETSSL=ON -DENABLE_CRYPTO=ON' . 

If I run the manifest without "features" attribute like this

```
{
    "name": "cosmos-versions",
    "version": "1.0.0",
    "builtin-baseline": "9d7244f2f6a4f6a34c4e0b3ecbf391323e379a43",
    "dependencies":  [  "poco"  ]
}

```
I noticed the components are not turned on while building using cmake  '-DENABLE_NETSSL=OFF -DENABLE_CRYPTO=OFF'

**Comment by PhoebeHui** [comment]
Right, installing the feature would enable it, so you need to depend on poco[netssl]. The first one is correct, and you don't need to pass '-DENABLE_NETSSL=ON -DENABLE_CRYPTO=ON' to cmake. The 2 options are in control of the feaure.

As a workaround, you can remove the platform from your port/poco/vcpkg.json, then it will install openssl and this issue should be sloved.

**Comment by sundarsabapathi** [comment]
Thanks @PhoebeHui

**Comment by PhoebeHui** [comment]
Glad to help!
