### ISSUE TITLE
Building package msmpi:x86-windows-static failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by macsinus** [Microsoft/vcpkg#1820]
C:\Users\mac.SINUS\Downloads\vcpkg-master\vcpkg-master>vcpkg install hdf5 --triplet x86-windows-static
The following packages will be built and installed:
    hdf5:x86-windows-static
  * msmpi:x86-windows-static
Additional packages (*) will be installed to complete this operation.
Building package msmpi:x86-windows-static...
-- CURRENT_INSTALLED_DIR=C:/Users/mac.SINUS/Downloads/vcpkg-master/vcpkg-master/installed/x86-windows-static
-- DOWNLOADS=C:/Users/mac.SINUS/Downloads/vcpkg-master/vcpkg-master/downloads
-- CURRENT_PACKAGES_DIR=C:/Users/mac.SINUS/Downloads/vcpkg-master/vcpkg-master/packages/msmpi_x86-windows-static
-- CURRENT_BUILDTREES_DIR=C:/Users/mac.SINUS/Downloads/vcpkg-master/vcpkg-master/buildtrees/msmpi
-- CURRENT_PORT_DIR=C:/Users/mac.SINUS/Downloads/vcpkg-master/vcpkg-master/ports/msmpi/.
-- Downloading https://download.microsoft.com/download/D/B/B/DBB64BA1-7B51-43DB-8BF1-D1FB45EACF7A/msmpisdk.msi...
-- Downloading https://download.microsoft.com/download/D/B/B/DBB64BA1-7B51-43DB-8BF1-D1FB45EACF7A/msmpisdk.msi... Failed. Status: 7;"Couldn't con
nect to server"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:82 (message):

      Failed to download file.
      Add mirrors or submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  ports/msmpi/portfile.cmake:4 (vcpkg_download_distfile)
  scripts/ports.cmake:72 (include)

Error: Building package msmpi:x86-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: msmpi:x86-windows-static
  Vcpkg version: 0.0.88

Additionally, attach any relevant sections from the log files above.

C:\Users\mac.SINUS\Downloads\vcpkg-master\vcpkg-master>vcpkg update
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.

**Comment by macsinus** [comment]
The directory packages\msmpi_x86-windows-static is empty (no log files).

**Comment by alexkaratarakis** [comment]
```
-- Downloading https://download.microsoft.com/download/D/B/B/DBB64BA1-7B51-43DB-8BF1-D1FB45EACF7A/msmpisdk.msi...
-- Downloading https://download.microsoft.com/download/D/B/B/DBB64BA1-7B51-43DB-8BF1-D1FB45EACF7A/msmpisdk.msi... Failed. Status: 7;"Couldn't con
nect to server"
```

It looks like downloading msmpi failed. It currently works for me, so maybe it was a temporary connection issue.
Does it still not work for you?

**Comment by macsinus** [comment]
Thank you for your response.
Unfortunately it still doesn't work for me.
The other dependent packages for hdf5 were downloaded and installed OK.
I just tried removing one of them (zlib) and installing again (see below) - zlib was installed OK but there seems to be a problem with the msmpi link.
I notice that the download link for zlib is http but that for msmpi is https - could that be a cause?

`C:\vcpkg-master>vcpkg remove zlib
The following packages will be removed:
    zlib:x86-windows-static
Removing package zlib:x86-windows-static...
Removing package zlib:x86-windows-static... done
Purging package zlib:x86-windows-static...
Purging package zlib:x86-windows-static... done

C:\vcpkg-master>vcpkg install hdf5
The following packages will be built and installed:
    hdf5:x86-windows-static
  * msmpi:x86-windows-static
  * zlib:x86-windows-static
Additional packages (*) will be installed to complete this operation.
Building package zlib:x86-windows-static...
-- CURRENT_INSTALLED_DIR=C:/vcpkg-master/installed/x86-windows-static
-- DOWNLOADS=C:/vcpkg-master/downloads
-- CURRENT_PACKAGES_DIR=C:/vcpkg-master/packages/zlib_x86-windows-static
-- CURRENT_BUILDTREES_DIR=C:/vcpkg-master/buildtrees/zlib
-- CURRENT_PORT_DIR=C:/vcpkg-master/ports/zlib/.
-- Using cached C:/vcpkg-master/downloads/zlib1211.tar.gz
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Configuring x86-windows-static-rel
-- Configuring x86-windows-static-rel done
-- Configuring x86-windows-static-dbg
-- Configuring x86-windows-static-dbg done
-- Package x86-windows-static-rel
-- Package x86-windows-static-rel done
-- Package x86-windows-static-dbg
-- Package x86-windows-static-dbg done
-- Installing: C:/vcpkg-master/packages/zlib_x86-windows-static/share/zlib/copyr
ight
-- Performing post-build validation
-- Performing post-build validation done
Building package zlib:x86-windows-static... done
Installing package zlib:x86-windows-static...
Installing package zlib:x86-windows-static... done
Building package msmpi:x86-windows-static...
-- CURRENT_INSTALLED_DIR=C:/vcpkg-master/installed/x86-windows-static
-- DOWNLOADS=C:/vcpkg-master/downloads
-- CURRENT_PACKAGES_DIR=C:/vcpkg-master/packages/msmpi_x86-windows-static
-- CURRENT_BUILDTREES_DIR=C:/vcpkg-master/buildtrees/msmpi
-- CURRENT_PORT_DIR=C:/vcpkg-master/ports/msmpi/.
-- Downloading https://download.microsoft.com/download/D/B/B/DBB64BA1-7B51-43DB-
8BF1-D1FB45EACF7A/msmpisdk.msi...
-- Downloading https://download.microsoft.com/download/D/B/B/DBB64BA1-7B51-43DB-
8BF1-D1FB45EACF7A/msmpisdk.msi... Failed. Status: 7;"Couldn't connect to server"

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:82 (message):


      Failed to download file.
      Add mirrors or submit an issue at https://github.com/Microsoft/vcpkg/issue
s

Call Stack (most recent call first):
  ports/msmpi/portfile.cmake:4 (vcpkg_download_distfile)
  scripts/ports.cmake:72 (include)


Error: Building package msmpi:x86-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: msmpi:x86-windows-static
  Vcpkg version: 0.0.88

Additionally, attach any relevant sections from the log files above.`

**Comment by macsinus** [comment]
Solved by setting environment variable HTTPS_PROXY.

**Comment by alexkaratarakis** [comment]
@macsinus 
Thanks for reporting this! There have been a couple of issues around proxies and we are investigating a solution that won't cause such headache in the future.

**Comment by sommmyyyy** [comment]
@macsinus how to set variable value for https_proxy?
