### ISSUE TITLE
[protobuf[core]:x64-windows] build failure

### ISSUE THREAD

**Issue by payentan** [microsoft/vcpkg#18216]
**Host Environment**
- OS: Windows 10
- Compiler: MSVC 14.11.25503

**To Reproduce**
`./vcpkg install grpc:x64-windows`

**Failure logs** 
Computing installation plan...
The following packages will be built and installed:
    grpc[codegen,core]:x64-windows -> 1.37.0#2
  * protobuf[core]:x64-windows -> 3.15.8#1
  * re2[core]:x64-windows -> 2020-10-01
  * upb[core]:x64-windows -> 2020-12-19#1
  * zlib[core]:x64-windows -> 1.2.11#10
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\tanpeien\AppData\Local\vcpkg\archives\e4\e49421d377a0d52977051b8a38dfabfd608e6262.zip
Could not locate cached archive: C:\Users\tanpeien\AppData\Local\vcpkg\archives\36\36d365bc8a8dd6087c2a8da75a858d54ec5ef0ae.zip
Could not locate cached archive: C:\Users\tanpeien\AppData\Local\vcpkg\archives\9e\9ec30fb7d8df30e3f0051fdadd0eec9b0436f110.zip
Could not locate cached archive: C:\Users\tanpeien\AppData\Local\vcpkg\archives\39\392c08205227fce5fea856f01c8e7116ec6c5b76.zip
Could not locate cached archive: C:\Users\tanpeien\AppData\Local\vcpkg\archives\b4\b49f4206dfc25226445856a0f51b26a3778fee0d.zip
Starting package 1/5: protobuf:x64-windows
Building package protobuf[core]:x64-windows...
-- Using cached D:/tpe/task/vcpkg/downloads/protocolbuffers-protobuf-436bd7880e458532901c58f4d9d1ea23fa7edd52.tar.gz
-- Cleaning sources at D:/tpe/task/vcpkg/buildtrees/protobuf/src/23fa7edd52-3ba2225d30.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/tpe/task/vcpkg/downloads/protocolbuffers-protobuf-436bd7880e458532901c58f4d9d1ea23fa7edd52.tar.gz
-- Applying patch fix-static-build.patch
-- Applying patch fix-default-proto-file-path.patch
-- Using source at D:/tpe/task/vcpkg/buildtrees/protobuf/src/23fa7edd52-3ba2225d30.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:146 (message):
    Command failed: D:/tpe/task/vcpkg/downloads/tools/cmake-3.20.2-windows/cmake-3.20.2-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j9
    Working Directory: D:/tpe/task/vcpkg/buildtrees/protobuf/x64-windows-dbg
    See logs for more information:
      D:\tpe\task\vcpkg\buildtrees\protobuf\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:104 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:44 (vcpkg_build_cmake)
  ports/protobuf/portfile.cmake:46 (vcpkg_install_cmake)
  scripts/ports.cmake:139 (include)

Error: Building package protobuf:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: protobuf:x64-windows
  Vcpkg version: 2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9

Additionally, attach any relevant sections from the log files above.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/6572565/config-x64-windows-out.log)
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/6572566/install-x64-windows-dbg-out.log)
[stdout-x64-windows.log](https://github.com/microsoft/vcpkg/files/6572567/stdout-x64-windows.log)
[x64-windows.vcpkg_abi_info.txt](https://github.com/microsoft/vcpkg/files/6572568/x64-windows.vcpkg_abi_info.txt)

**Comment by NancyLi1013** [comment]
Hi @payentan 
Thanks for posting this issue.
Can you help provide which version of Visual Studio you used?

`D:\tpe\task\vcpkg\buildtrees\protobuf\src\23fa7edd52-3ba2225d30.clean\src\google\protobuf\repeated_field.cc : fatal error C1126: automatic allocation exceeds 2G`

I cannot reproduce this issue with Visual Studio 2017 on my machine.

**Comment by payentan** [comment]
Hi,

The version of Visual Studio is as follows. Thanks for your help.

Microsoft Visual Studio Community 2017 
版本 15.3.5
VisualStudio.15.Release/15.3.5+26730.16
Microsoft .NET Framework
版本 4.8.03752

已安装的版本: Community

Visual Basic 2017   00369-60000-00001-AA905
Microsoft Visual Basic 2017

Visual C# 2017   00369-60000-00001-AA905
Microsoft Visual C# 2017

Visual C++ 2017   00369-60000-00001-AA905
Microsoft Visual C++ 2017

**Comment by NancyLi1013** [comment]
Can you try to update Visual Studio 2017 to the latest version or install the latest version of Visual Studio 2019 to rebuild this?

Can you please also confirm if you used 32 bit or 64 bit computer?

**Comment by payentan** [comment]
Hi,
With Visual Studio 2019, I can build and install grpc now. Thanks.
