### ISSUE TITLE
Negative elapsed time

### ISSUE THREAD

**Issue by gvanem** [microsoft/vcpkg#18217]
When after doing a very lengthy `vcpkg install qwt:x86-windows --debug` job,
which involves building Qt5 itself, vcpkg exits with this message:
```
Installing package qwt[core]:x86-windows...
Installing package qwt[core]:x86-windows... done
Elapsed time for package qwt:x86-windows: 2.188 min

Total elapsed time: 1.478 h

[DEBUG] vcpkg/install.cpp(1104)
[DEBUG] Exiting after -2147483648 us (-2147483648 us)
```

1 hour 30 minutes is approx. `5 400 000 000 us`. I assume some signed overflow 
is going on here to show      `-2 147 483 648 us`.

**Comment by JackBoosY** [comment]
Known bug.

**Comment by gvanem** [comment]
> Known bug.

I forgot to say I built `vcpkg` for 32-bit. That is probably related (the `sizeof(int)`)?

**Comment by JackBoosY** [comment]
@gvanem 
```cpp
        auto elapsed_us = GlobalState::timer.lock()->microseconds();
```
```cpp
double microseconds() const { return elapsed().as<std::chrono::duration<double, std::micro>>().count(); }
```
