### ISSUE TITLE
FFmpeg can not be built as static library

### ISSUE THREAD

**Issue by madebr** [Microsoft/vcpkg#1821]
The current ffmpeg portfile will [automatically switch](https://github.com/Microsoft/vcpkg/blob/32a01e68516d51b998ec80878eb20c000f6c95ba/ports/ffmpeg/portfile.cmake#L1-L4) the build to a dynamic version.
Disabling these 4 lines and adding `--enable-static --disable-shared` to `OPTIONS` will make the build generate `.a` static libraries instead of `.lib` libraries.
CMake's `find_library` will not detect these `.a` files on Windows.

How can I generate `.lib` files instead of `.a` files?

**Comment by jasjuang** [comment]
`.a` files are linux static libraries extensions. Are you able to build ffmpeg from source to get the correct static libraries?

**Comment by madebr** [comment]
I opened this issue because the dynamic version generates Microsoft '.lib' libraries and my 'hacked' static version generates GNU '.a' libraries.

**Comment by JackBoosY** [comment]
Hi @madebr , ffmpeg can be build as static library now.
You need to update vcpkg and use command "vcpkg install ffmpeg:x86-windows-static" or "vcpkg install ffmpeg:x64-windows-static".
Thx.

**Comment by madebr** [comment]
Yeah I know. I submitted the [patch](https://github.com/Microsoft/vcpkg/commit/317b2ea082d1b48c9f107a1dc1ba882d278b2f84) :smile:
