### ISSUE TITLE
关于CMakeCache.txt的问题

### ISSUE THREAD

**Issue by yzw88** [microsoft/vcpkg#18218]
When asking a question please also include where you looked for an answer (so we can update the documentation if needed).
你好，请教一个问题，这边的项目使用了vcpkg来构建第三方依赖
win10 的clion远程编译 linux的项目。目前希望 自己在linux平台 手动去执行 cmake，make 去编译项目时，出现了一些错误。
  我的执行命令是：
  cmake -B ./build -S . -DCMAKE_TOOLCHAIN_FILE=/home/yezi/vcpkg/scripts/buildsystems/vcpkg.cmake

CMake Error at /home/devuser1/vcpkg/downloads/tools/cmake-3.20.2-linux/cmake-3.20.2-linux-x86_64/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Boost (missing: Boost_INCLUDE_DIR)
Call Stack (most recent call first):
  /home/yezi/vcpkg/downloads/tools/cmake-3.20.2-linux/cmake-3.20.2-linux-x86_64/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /home/yezi/vcpkg/downloads/tools/cmake-3.20.2-linux/cmake-3.20.2-linux-x86_64/share/cmake-3.20/Modules/FindBoost.cmake:2346 (find_package_handle_standard_args)
  CMakeLists.txt:10 (find_package)
  
 虽然这样能解决这个问题，但是项目中有很多的lib是有这个错误的。
 set(Boost_INCLUDE_DIR /home/devuser1/vcpkg/installed/x64-linux/include)
set(BOOST_LIB /home/devuser1/vcpkg/installed/x64-linux/lib)

please help me ，thanks。

**Comment by PhoebeHui** [comment]
@yzw88, what's components of boost do you use? you need link boost in your project.

See https://github.com/microsoft/vcpkg/blob/master/ports/boost/usage

**Comment by yzw88** [comment]
我这边问题已经解决了。a li ga tou

**Comment by PhoebeHui** [comment]
Glad you got the issue solved, thanks for your response!
