### ISSUE TITLE
[llvm[libunwind]:x86-windows-static / llvm[libunwind]:x64-windows-static] build failure

### ISSUE THREAD

**Issue by gdiObjects** [microsoft/vcpkg#18210]
**Host Environment**
- OS: [Windows 10]
- Compiler: Visual C++ 2019   00435-60000-00000-AA633, Microsoft Visual C++ 2019

**To Reproduce**
'.\vcpkg install llvm[libunwind]:x86-windows-static' / .\vcpkg install llvm[libunwind]:x64-windows-static

**Failure logs** 
The following packages will be built and installed:
    llvm[clang,compiler-rt,core,default-options,default-targets,disable-abi-breaking-checks,disable-assertions,disable-clang-static-analyzer,enable-bindings,enable-rtti,enable-terminfo,enable-threads,libunwind,lld,target-x86,tools]:x86-windows-static -> 11.1.0
Detecting compiler hash for triplet x86-windows-static...
Could not locate cached archive: C:\Users\Rio\AppData\Local\vcpkg\archives\51\515cd325c0ae96f017cf6d64729796191b0587a7.zip
Starting package 1/1: llvm:x86-windows-static
Building package llvm[clang,compiler-rt,core,default-options,default-targets,disable-abi-breaking-checks,disable-assertions,disable-clang-static-analyzer,enable-bindings,enable-rtti,enable-terminfo,enable-threads,libunwind,lld,target-x86,tools]:x86-windows-static...
-- Using community triplet x86-windows-static. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: D:\Development\Projects\vcpkg\triplets\community\x86-windows-static.cmake
-- Using cached D:/Development/Projects/vcpkg/downloads/llvm-llvm-project-llvmorg-11.1.0.tar.gz
-- Cleaning sources at D:/Development/Projects/vcpkg/buildtrees/llvm/src/org-11.1.0-a960fe6a14.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/Development/Projects/vcpkg/downloads/llvm-llvm-project-llvmorg-11.1.0.tar.gz
-- Applying patch 0001-add-msvc-options.patch
-- Applying patch 0002-fix-install-paths.patch
-- Applying patch 0003-fix-openmp-debug.patch
-- Applying patch 0004-fix-dr-1734.patch
-- Applying patch 0005-fix-tools-path.patch
-- Applying patch 0006-workaround-msvc-bug.patch
-- Applying patch 0007-fix-compiler-rt-install-path.patch
-- Applying patch 0008-fix-libcxx-install.patch
-- Applying patch 0009-fix-tools-install-path.patch
-- Using source at D:/Development/Projects/vcpkg/buildtrees/llvm/src/org-11.1.0-a960fe6a14.clean
CMake Error at ports/llvm/portfile.cmake:123 (message):
  Building libunwind with MSVC is not supported.  Disable it until issues are
  fixed.
Call Stack (most recent call first):
  scripts/ports.cmake:139 (include)

Error: Building package llvm:x86-windows-static failed with: BUILD_FAILED
Error: Building package llvm:x64-windows-static failed with: BUILD_FAILED

-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by PhoebeHui** [comment]
@gdiObjects, see the error message, building libunwind with MSVC is not supported.
