### ISSUE TITLE
[aws-sdk-cpp] update to 1.9.x

### ISSUE THREAD

**Issue by shanepowell** [microsoft/vcpkg#18214]
Library name: aws-sdk-cpp

New version number: 1.9.x

Other information that may be useful (release notes, etc...)

**Comment by camarois** [comment]
Is this issue still ongoing? I believe some features are linked in the vcpkg.json (like s3-crt), but aren't available with the current 1.8.126 version. Should be at least 1.9.1

**Comment by JonLiu1993** [comment]
> Is this issue still ongoing? I believe some features are linked in the vcpkg.json (like s3-crt), but aren't available with the current 1.8.126 version. Should be at least 1.9.1

I will submit a pr update to latest version

**Comment by shanepowell** [comment]
It is for me, I like to try to get all my libraries from vcpkg but this one I can't as I am using stuff not in the 1.8 branch compiled with vcpkg.  Currently I'm compiling / setting up this library manually.
