### ISSUE TITLE
vtk build failure

### ISSUE THREAD

**Issue by sekcheong** [microsoft/vcpkg#18229]
**Host Environment**
- OS: Windows
- Compiler: VS2019

**To Reproduce**
`./vcpkg install vtk --triplet=x64-windows --recurse`

**Failure logs** 
c:\src\vcpkg>vcpkg install vtk --triplet=x64-windows --recurse
Computing installation plan...
The following packages will be built and installed:
    vtk[core]:x64-windows -> 9.0.1#6
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\sek.cheong\AppData\Local\vcpkg\archives\b4\b471b09aaa53490b298e18ac169d6fb37b8d3173.zip
Starting package 1/1: vtk:x64-windows
Building package vtk[core]:x64-windows...
CMake Deprecation Warning at scripts/cmake/vcpkg_check_features.cmake:182 (message):
  calling `vcpkg_check_features` without the `FEATURES` keyword has been
  deprecated.

      Please add the `FEATURES` keyword to the call.
Call Stack (most recent call first):
  ports/vtk/portfile.cmake:116 (vcpkg_check_features)
  scripts/ports.cmake:139 (include)

-- Using cached C:/src/vcpkg/downloads/64265c5fd1a8e26a6a81241284dea6b3272f6db6.diff
-- Using cached C:/src/vcpkg/downloads/Kitware-VTK-96e6fa9b3ff245e4d51d49f23d40e9ad8774e85e.tar.gz
-- Cleaning sources at C:/src/vcpkg/buildtrees/vtk/src/ad8774e85e-b4218d18df.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/src/vcpkg/downloads/Kitware-VTK-96e6fa9b3ff245e4d51d49f23d40e9ad8774e85e.tar.gz
-- Applying patch 6811.patch
-- Applying patch FindLZMA.patch
-- Applying patch FindLZ4.patch
-- Applying patch Findproj.patch
-- Applying patch vtkm.patch
-- Applying patch pegtl.patch
-- Applying patch pythonwrapper.patch
-- Applying patch NoUndefDebug.patch
-- Applying patch python_debug.patch
-- Applying patch fix-using-hdf5.patch
-- Applying patch module-name-mangling.patch
-- Applying patch FindExpat.patch
-- Applying patch fix-freetype.patch
-- Applying patch C:/src/vcpkg/downloads/64265c5fd1a8e26a6a81241284dea6b3272f6db6.diff
-- Applying patch 0002-Qt-enforce-QT_NO_KEYWORDS-builds-by-VTK-itself.patch
-- Using source at C:/src/vcpkg/buildtrees/vtk/src/ad8774e85e-b4218d18df.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:146 (message):
    Command failed: C:/src/vcpkg/downloads/tools/cmake-3.20.2-windows/cmake-3.20.2-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j13
    Working Directory: C:/src/vcpkg/buildtrees/vtk/x64-windows-dbg
    See logs for more information:
      C:\src\vcpkg\buildtrees\vtk\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:104 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:44 (vcpkg_build_cmake)
  ports/vtk/portfile.cmake:194 (vcpkg_install_cmake)
  scripts/ports.cmake:139 (include)

Error: Building package vtk:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: vtk:x64-windows
  Vcpkg version: 2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9

Additionally, attach any relevant sections from the log files above.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by NancyLi1013** [comment]
Hi @sekcheong 

Thanks for posting this issue. Could you please help provide the error log from _C:\src\vcpkg\buildtrees\vtk\install-x64-windows-dbg-out.log_?

**Comment by timmeh87** [comment]
It seems you have filled up your drive, this is not a problem with VTK persay, other than VTK is very large

 fatal error C1085: Cannot write compiler generated file: 'C:\src\vcpkg\buildtrees\vtk\x64-windows-dbg\Common\ExecutionModel\CMakeFiles\CommonExecutionModel.dir\vtkSphereTree.cxx.obj': No space left on device

**Comment by NancyLi1013** [comment]
@sekcheong Please free up some space on your machine and then rebuild this port. 
@timmeh87 thanks for your help to post the error.

**Comment by sekcheong** [comment]
@NancyLi1013 Thank you for looking into this.
