### ISSUE TITLE
Docs at readthedocs.io seem broken?

### ISSUE THREAD

**Issue by aggieNick02** [microsoft/vcpkg#18231]
Going to the docs at https://vcpkg.readthedocs.io/ linked to from the github page goes to an unformatted table of contents with lots of broken links. I'm guessing this is known but couldn't find an issue for it recently.

Also, it gets a bit confusing when the docs are in two different places - both on github and readthedocs. Which one is authoritative?

**Comment by PhoebeHui** [comment]
@aggieNick02, we would migrate documentation from readthedocs to vcpkg new website https://vcpkg.io/en/index.html which is available to view as a draft! We really appreciate any and all feedback. You can report new issues in https://github.com/vcpkg/vcpkg.github.io/issues.

**Comment by aggieNick02** [comment]
Thanks for the info. The vcpkg.io page looks really nice!

Should the link from the main github page to https://vcpkg.readthedocs.io/ be removed since the readthedocs page seems broken? Should the readthedocs page be removed?

**Comment by PhoebeHui** [comment]
Thanks for pointing out this! I have submitted a PR to update it.

**Comment by dg0yt** [comment]
But docs at vcpkg.io are outdated as well.

**Comment by PhoebeHui** [comment]
@dg0yt, we already have issue https://github.com/vcpkg/vcpkg.github.io/issues/48 to track the issue.

**Comment by dg0yt** [comment]
@PhoebeHui Sure. What is missing is some indication when this will be dealt with.

**Comment by aggieNick02** [comment]
> Thanks for pointing out this! I have submitted a PR to update it.

Great, thanks so much!
