### ISSUE TITLE
[ompl] Cannot find lib files when using CMake

### ISSUE THREAD

**Issue by Ace314159** [microsoft/vcpkg#18237]
**Describe the bug**
After doing `find_package` and successfully finding ompl, linking fails because it can't find `/lib/boost_serialization-vc140-mt.lib`

**Environment**
- OS: Windows 10
- Compiler: MSVC 2019

**To Reproduce**
1. `./vcpkg install ompl --triplet=x64-windows`
2. `find_package(ompl REQUIRED)`

**Expected behavior**
I expect to be able to link the library after successfully using `find_package`

**Failure logs** 
`LINK : fatal error LNK1181: cannot open input file '\lib\boost_serialization-vc140-mt.lib'`

**Additional context**
This appears to occur because both `${OMPL_LIBRARY_DIRS}` and `${OMPL_LIBRARIES}` use `${_IMPORT_PREFIX}` in omplConfig.cmake which seems to be empty, leading to paths like `/lib` and `/debug/lib` being in `${OMPL_LIBRARY_DIRS}` and `/lib/boost_serialization-vc140-mt.lib` in `${OMPL_LIBRARIES}`. During port installation, all the paths were correct absolute paths at one point, and parts of the paths were replaced by `${_IMPORT_PREFIX}` when `vcpkg_fixup_cmake_targets` was called.

**Comment by PhoebeHui** [comment]
See https://github.com/microsoft/vcpkg/pull/18908#issuecomment-878693222
