### ISSUE TITLE
Combine static and dynamic libraries in a project

### ISSUE THREAD

**Issue by madebr** [Microsoft/vcpkg#1823]
Hey,

VcPkg currently uses `/MDx` compiler flags for dynamic libraries and `/MTx` flags for the static libraries.
Since the static and dynamic runtime libraries are incompatible, how can I combine static and dynamic libraries?
I would like to use the static version of library A and use the dynamic version of library B.

It would be useful if static libraries would link to the dynamic c runtime too. (or configurable)

**Comment by alexkaratarakis** [comment]
This is a scenario where the flexibility of triplets comes in useful. 

You can modify an existing triplet or create a new one and do something like this:

```cmake
set(VCPKG_TARGET_ARCHITECTURE x86)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)

if (PORT STREQUAL zlib)
	set(VCPKG_CRT_LINKAGE static)
	set(VCPKG_LIBRARY_LINKAGE static)
endif()
```

In this example, I set a default and then I specify exceptions. So, everything will be built dynamically except zlib which is specifically set to static. 

Also, as you can see, there is a different setting for CRT and Library linkage, so it is configurable as well.

**Comment by madebr** [comment]
Thanks, that might solve it.
I guess I'll have to set `VCPKG_LIBRARY_LINKAGE` of zlib to dynamic?
In order to get the libraries to link.

**Comment by alexkaratarakis** [comment]
@madebr 
`VCPKG_LIBRARY_LINKAGE` refers to the build type of zlib itself.
So, in the example, you will get static libs and not dlls.
`VCPKG_LIBRARY_LINKAGE` should be set to static.

Furthermore, I made a mistake in the previous post (which I have now edited). You should not specify different CRT in a per port basis. 

More information and further triplet customization can be found in the [documentation](https://vcpkg.readthedocs.io/en/latest/users/triplets/).
