### ISSUE TITLE
[Question]Boost RuntimeLibrary missmatch

### ISSUE THREAD

**Issue by qqblack** [microsoft/vcpkg#18255]
But when I use `vcpkg install boost:x64-windows-static-md` (or `vcpkg install boost  --triplet=x64-windows-static-md`), it only changes the output directory. The `.lib` file still is `*-mt.lib`. Why?how to solve it?

<img width="561" alt="question1" src="https://user-images.githubusercontent.com/25791058/120581437-662a8f80-c45d-11eb-8d10-dabfaf9ce8ea.png">

_Originally posted by @qqblack in https://github.com/microsoft/vcpkg/issues/10221#issuecomment-853531395_

**Comment by qqblack** [comment]
The problem is same with [issue#10221](https://github.com/microsoft/vcpkg/issues/10221), which has been closed

But I cannot solve it as the instruction

**Comment by PhoebeHui** [comment]
@qqblack, could you attach your failure logs?

**Comment by qqblack** [comment]
The output of command `vcpkg install boost-filesystem:x86-windows-static-md`

> Computing installation plan...
> The following packages will be built and installed:
>     boost-filesystem[core]:x86-windows-static-md -> 1.75.0#1
>   * boost-system[core]:x86-windows-static-md -> 1.75.0#1
> Additional packages (*) will be modified to complete this operation.
> Detecting compiler hash for triplet x86-windows-static-md...
> Using cached binary package: C:\Users\tanzi_WTG\AppData\Local\vcpkg\archives\f0\f08e6cf199a51fa1e7e44b359aea386c40be9f94.zip
> Using cached binary package: C:\Users\tanzi_WTG\AppData\Local\vcpkg\archives\ab\ab73eb256732c94bea826391ca147291cdd0fa67.zip
> Starting package 1/2: boost-system:x86-windows-static-md
> Building package boost-system[core]:x86-windows-static-md...
> Building package boost-system[core]:x86-windows-static-md... done
> Installing package boost-system[core]:x86-windows-static-md...
> Installing package boost-system[core]:x86-windows-static-md... done
> Elapsed time for package boost-system:x86-windows-static-md: 140.9 ms
> Starting package 2/2: boost-filesystem:x86-windows-static-md
> Building package boost-filesystem[core]:x86-windows-static-md...
> Building package boost-filesystem[core]:x86-windows-static-md... done
> Installing package boost-filesystem[core]:x86-windows-static-md...
> Installing package boost-filesystem[core]:x86-windows-static-md... done
> Elapsed time for package boost-filesystem:x86-windows-static-md: 54.9 ms
> 
> Total elapsed time: 3.78 s
> 
> The package boost is compatible with built-in CMake targets:
> 
> 
> 
>     find_package(Boost REQUIRED [COMPONENTS <libs>...])
> 
>     target_link_libraries(main PRIVATE Boost::boost Boost::<lib1> Boost::<lib2> ...)


The contents of `vcpkg_root\triplets\community\x86-windows-static-md.cmake` is
> set(VCPKG_TARGET_ARCHITECTURE x86)
> set(VCPKG_CRT_LINKAGE dynamic)
> set(VCPKG_LIBRARY_LINKAGE static)

The `vcpkg_root\installed\x86-windows-static-md\lib“ directory is like below
![image](https://user-images.githubusercontent.com/25791058/120727677-bb25de80-c50d-11eb-80cd-08a08039e707.png)

I hope that it can be installed in `vcpkg_root\installed\x86-windows-static\`, and the lib file is `boost_container-vc140-md.lib` rather than `boost_container-vc140-mt.lib`

**Comment by qqblack** [comment]
I don't want to change `triplet` or `library runtime` configure of my current project, which can influence some other libaries that used in this project.

I just want to change the libraries installed with vcpkg.

**Comment by qqblack** [comment]
Here is a demo to reproduce the problem

`VS project`, `C++ console`, the C++ code is as below
```C++
#include <iostream>
#include <boost/filesystem.hpp>

int main()
{
	char path[] = "C:/mylog/";
	if (!boost::filesystem::is_directory(path))
	{
		if (!boost::filesystem::create_directory(path))
		{
			std::cout << "create_directories failed: " << path << std::endl;
			return -1;
		}
	}
}
```

When the `triplet` of the project is `x86-windows`, everything is fine. But when you set `triplet` as `x86-windows-static`

![image](https://user-images.githubusercontent.com/25791058/120729127-f249bf00-c510-11eb-8068-d26a811ec3ed.png)

There would be many errors like below:

> 严重性	代码	说明	项目	文件	行	禁止显示状态	禁止显示状态
> 错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MTd_StaticDebug”不匹配值“MDd_DynamicDebug”(ConsoleApplication1.obj 中)	ConsoleApplication1	F:\3D_Graphic\GPU_programming\gpgpu\tutorials\ConsoleApplication1\boost_filesystem-vc140-mt-gd.lib(path_traits.obj)	1
		
I don't want to change `triplet` setting or `library runtime` configure of this project.

**Comment by PhoebeHui** [comment]
@qqblack, no matter x64-windows or x64-windows-static or x64-windows-static-md used, the libs names always changed with '-vc140-mt.lib'. See https://github.com/microsoft/vcpkg/blob/master/ports/boost-modular-build-helper/boost-modular-build.cmake#L38

So the thing here is the library runtime in vcpkg installed ports and your project. You need set the host triplet to x86-windows-static

![image](https://user-images.githubusercontent.com/20694052/120774615-06afab00-c555-11eb-9bc7-557735e89fc0.png)

**Comment by qqblack** [comment]
I changed the `Use static Libraries`, but it doesn't help.

![image](https://user-images.githubusercontent.com/25791058/120810825-f3fd9c00-c57d-11eb-9972-54c0941de67f.png)

I also changed the file `vcpkg_root/ports/boost-modular-build-helper/boost-modular-build.cmake` as below, it doesn't change anything neither.

![image](https://user-images.githubusercontent.com/25791058/120811096-345d1a00-c57e-11eb-86b6-2f69cb3e09ec.png)

**Comment by PhoebeHui** [comment]
@qqblack, you need to set the 'Host Triplet' to x86-windows-static, not the 'Triplet'.

**Comment by PhoebeHui** [comment]
@qqblack, does this still be a problem for you? have you try above suggestion?

**Comment by PhoebeHui** [comment]
Please reopen this issue if it still be a problem for you.
