### ISSUE TITLE
How do I disable NETSSL_WIN in poco portfile?

### ISSUE THREAD

**Issue by sundarsabapathi** [microsoft/vcpkg#18256]
Hi @JackBoosY, I followed your below suggestion 

You should modify ports/poco/portfile.cmake line 28-35 from:

```
vcpkg_check_features(OUT_FEATURE_OPTIONS FEATURE_OPTIONS
    pdf         ENABLE_PDF
    netssl      ENABLE_NETSSL
    netssl      ENABLE_NETSSL_WIN
    netssl      ENABLE_CRYPTO
    sqlite3     ENABLE_DATA_SQLITE
    postgresql  ENABLE_DATA_POSTGRESQL
)
```
to:

```
vcpkg_check_features(OUT_FEATURE_OPTIONS FEATURE_OPTIONS
    pdf         ENABLE_PDF
    netssl      ENABLE_NETSSL
    netssl      ENABLE_CRYPTO
    sqlite3     ENABLE_DATA_SQLITE
    postgresql  ENABLE_DATA_POSTGRESQL
)
```
To solve this issue.
And since overlay-port doesn't support custom version, I think you should fork vcpkg and commit this to your branch, set the builtin-baseline to your commit.

I fork vcpkg and commit the changes to my branch and after merge those changes in to master and use my commit ID to set it as builtin-baseline.

My changes are present in the file ports/poco/portfile.cmake. But while it building poco using cmake it refers the portfile in this location "vcpkg\buildtrees\versioning\versions\poco\e9c709300900158cdfcad75965e85b04413c8d5b\portfile.cmake". My changes are not present in this portfile. My problem not yet resolved. Can you please help me to resolve this issue?

**Comment by sundarsabapathi** [comment]
Hi @JackBoosY, I suggest turning off the option of ENABLE_NETSSL_WIN，in poco\portfile.cmake by default. Because like my case any of the user can use both openssl and netssl from poco then they also face my problem.

**Comment by JackBoosY** [comment]
> Hi @JackBoosY, I suggest turning off the option of ENABLE_NETSSL_WIN，in poco\portfile.cmake by default. Because like my case any of the user can use both openssl and netssl from poco then they also face my problem.

This also cancels the user's permission to use winssl.

**Comment by sundarsabapathi** [comment]
Hi @JackBoosY, Any other alternative way to disable NETSSL_WIN.

**Comment by JackBoosY** [comment]
You should remove line 30 too:
```
    netssl      ENABLE_NETSSL_WIN
```

**Comment by sundarsabapathi** [comment]
Sorry @JackBoosY still same problem. I fork vcpkg and commit the changes to my branch and after merge those changes in to master and use my latest commit ID as builtin-baseline.

My changes are present in the file ports/poco/portfile.cmake. But while it building poco using cmake it refers the portfile in this location "vcpkg\buildtrees\versioning\versions\poco\e9c709300900158cdfcad75965e85b04413c8d5b\portfile.cmake". My changes are not present in this portfile.

**Comment by JackBoosY** [comment]
@sundarsabapathi  Did you update the port-version in `CONTROL` or `vcpkg.json` them use `./vcpkg x-add-version poco` and commit changes first?

**Comment by sundarsabapathi** [comment]
Sorry @JackBoosY , I forgot to update port-version . Now this portfile "vcpkg\buildtrees\versioning\versions\poco\e9c709300900158cdfcad75965e85b04413c8d5b\portfile.cmake" also updated. I have one doubt now I followed your suggestion to fork  vcpkg and commit the changes  and use my latest commit ID as builtin-baseline. The repository microsoft/vcpkg is updating every day then how I  update my local vcpkg repository all the time ?

**Comment by JackBoosY** [comment]
@sundarsabapathi  There is currently no good solution, I think the only way is to reset the changes, merge to master and re-make the changes.

**Comment by sundarsabapathi** [comment]
Thanks @JackBoosY , After updated the port-version it works as expected.
