### ISSUE TITLE
[New Port Request] aegis.cpp

### ISSUE THREAD

**Issue by nlogozzo** [microsoft/vcpkg#18250]
Library name: aegis.cpp

Library description: Discord C++ library for interfacing with the API. 

Source repository URL: https://github.com/zeroxs/aegis.cpp

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
```
Libraries used (all are header-only with the exception of zlib and openssl):

Asio
Websocketpp (unofficial fork)
JSON for Modern C++
spdlog (by extension, fmtlib)
OpenSSL 1.0.2
zlib
zstr
```

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by pythagoras9** [comment]
Hey @PhoebeHui  
I tried creating it myself. But this particular repo (https://github.com/arvidn/libtorrent) uses submodules. The current vcpkg_from_github function does not download the submodules in a repo. Is there any plans to have a vcpkg_from_git_submod function which downloads submodules as well?

**Comment by PhoebeHui** [comment]
@pythagoras9, for submodules, generally, you can check if vcpkg has an exist port, if so, you can set it as dependency directly, if not, you can create a new port for the repo firstly. If the submodules are not required to build the library, sometimes, it's only used to test the library, we can diable it simpily.
