### ISSUE TITLE
[grpc] no grpc++_reflection lib x64-windows-static

### ISSUE THREAD

**Issue by andrusenko-ag** [microsoft/vcpkg#18266]
**Describe the bug**
Building grpc for x64-windows-static triplet I found that there is no grpc++_reflection library, it only exists in grpc_x64-windows.
You can find gRPC with find_package() but can not link grpc++_reflection

**Environment**
- OS: Windows 10
- Compiler: MSVC 2019

**To Reproduce**
find_package(gRPC CONFIG REQUIRED)message(STATUS "Using gRPC ${gRPC_VERSION}")target_link_libraries(MyTarget gRPC::grpc++_reflection)

**Expected behavior**
Library should present in x64-windows-static also

**Comment by NancyLi1013** [comment]
Hi @andrusenko-ag 

Thanks for posting this issue.

Seems `grpc++_reflection` will be built when building the feature `codegen`. Please see these codes in CMakeLists.txt.
So could you please try to build `grpc[codegen]:x64-windows-static`?
```
if(gRPC_BUILD_CODEGEN)
add_library(grpc++_reflection
  ${_gRPC_PROTO_GENS_DIR}/src/proto/grpc/reflection/v1alpha/reflection.pb.cc
  ${_gRPC_PROTO_GENS_DIR}/src/proto/grpc/reflection/v1alpha/reflection.grpc.pb.cc
  ${_gRPC_PROTO_GENS_DIR}/src/proto/grpc/reflection/v1alpha/reflection.pb.h
  ${_gRPC_PROTO_GENS_DIR}/src/proto/grpc/reflection/v1alpha/reflection.grpc.pb.h
  src/cpp/ext/proto_server_reflection.cc
  src/cpp/ext/proto_server_reflection_plugin.cc
)
```

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
