### ISSUE TITLE
nuget export - consider creating .NET Core friendly nuget packages

### ISSUE THREAD

**Issue by mkosieradzki** [microsoft/vcpkg#1826]
It would be nice to integrate somehow with .NET Core style nuget packages:

- Multi flavor package with: 
```
runtimes/<rid>/*.dll
```
inside.

This would be difficult because it requires ability to build for multiple platforms.

or
- Multiple packages:

```
runtime.<rid>.<package name>
```
For a good example see: `Microsoft.NETCore.Jit` package with its `runtime.json` and accompanying `runtime.<rid>.Microsoft.NETCore.Jit`

**Comment by NancyLi1013** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen.
