### ISSUE TITLE
[glad] Installing glad[gl-api-46] gives header for OpenGL version1.0

### ISSUE THREAD

**Issue by le-michael** [microsoft/vcpkg#18261]
**Describe the bug**
I tried installing glad through vcpkg and was targeting `gl-api-46` on the features list. When I imported it into my project the header was only providing functions for OpenGL version 1.0. Looking at the header file that was installed by vcpkg I saw that it was version 1.0 when I was expecting to see version 4.6.

**Environment**
- OS: Windows
- Compiler: Visual Studio Community 2019 Release - amd64_x86

**To Reproduce**
1. .\vcpkg install glad[gl-api-46]
2. Navigate to `C:\dev\vcpkg\packages\glad_x86-windows\include\glad`
3. Comments at the top of `glad.h` shows `APIs: gl=1.0`
4. Importing the header into a c++ file only provide only OpenGL API specification version 1.0 .

**Expected behavior**
Installing glad[gl-api-46] should provide a header file containing OpenGL  API specifications version 4.6.

**Additional context**
Running `.\vcpkg install glad[core]` will generate a header file containing OpenGL API specifications. version 4.6. Looking at the comments in the header file we can see `APIs: gl=4.6`.

**Comment by NancyLi1013** [comment]
Hi @le-michael 

Thanks for posting this issue.

I checked `include\glad\glad.h` on my local and found `APIs: gl=4.6`. 

```
/*

    OpenGL loader generated by glad 0.1.34 on -.

    Language/Generator: C/C++
    Specification: gl
    APIs: gl=4.6
    Profile: compatibility
    Extensions:
        
    Loader: True
    Local files: False
    Omit khrplatform: False
    Reproducible: True

    Commandline:
        --profile="compatibility" --api="gl=4.6" --generator="c" --spec="gl" --extensions=""
    Online:
        https://glad.dav1d.de/#profile=compatibility&language=c&specification=gl&loader=on&api=gl%3D4.6
*/
```
Have you used the latest vcpkg to build this?

**Comment by le-michael** [comment]
Running `.\vcpkg.exe  version` I get
`Vcpkg package management program version 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e`

**Comment by NancyLi1013** [comment]
Thanks for your feedback. I'm closing this issue for now since this issue has been solved now.
