### ISSUE TITLE
[gettext] build failure

### ISSUE THREAD

**Issue by BenKey** [microsoft/vcpkg#18270]
[gettext] build failure

# Host Environment

- **OS:** Windows 10 Pro Version 21H1 build 19043.1023 with Windows Feature Experience Pack 120.2212.2020.0
- **Compiler:** Microsoft Visual Studio Community 2019 Version 16.10.0

# To Reproduce

```
./vcpkg install "gettext[tools]" --triplet x64-windows
```

# Failure logs

```
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:146 (message):
Command failed: D:/vcpkg/downloads/tools/msys2/6c2b03e147d6bf87/usr/bin/make.exe -j 9 --trace -f Makefile all
Working Directory: D:/vcpkg/buildtrees/gettext/x64-windows-dbg
See logs for more information:
D:\vcpkg\buildtrees\gettext\build-x64-windows-dbg-out.log
D:\vcpkg\buildtrees\gettext\build-x64-windows-dbg-err.log
```

- [build-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/6600408/build-x64-windows-dbg-out.log)
- [build-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/6600410/build-x64-windows-dbg-err.log)

# Additional context

Apparently building msginit failed with the following error.

```
msginit-msginit.obj : error LNK2019: unresolved external symbol __imp_optarg_a referenced in function main
.libs\msginit.exe : fatal error LNK1120: 1 unresolved externals
```

**Comment by JackBoosY** [comment]
Seems needs to link to glibc.
cc @Neumann-A @375gnu @past-due

**Comment by dg0yt** [comment]
I think it is confusion between embedded getopt and port getopt-win32:
~~~
Importing getopt library
D:/vcpkg/installed/x64-windows/include\getopt.h(130): warning C4005: 'getopt': macro redefinition
D:\vcpkg\buildtrees\gettext\src\0.21-508c311661.clean\gettext-tools\gnulib-lib\getopt-pfx-core.h(45): note: see previous definition of 'getopt'
D:/vcpkg/installed/x64-windows/include\getopt.h(134): warning C4005: 'optarg': macro redefinition
D:\vcpkg\buildtrees\gettext\src\0.21-508c311661.clean\gettext-tools\gnulib-lib\getopt-pfx-core.h(46): note: see previous definition of 'optarg'
~~~

**Comment by JackBoosY** [comment]
After install `getopt-win32:x64-windows` first, I can completely reproduce this issue.

**Comment by JackBoosY** [comment]
> I think it is confusion between embedded getopt and port getopt-win32:
> 
> ```
> Importing getopt library
> D:/vcpkg/installed/x64-windows/include\getopt.h(130): warning C4005: 'getopt': macro redefinition
> D:\vcpkg\buildtrees\gettext\src\0.21-508c311661.clean\gettext-tools\gnulib-lib\getopt-pfx-core.h(45): note: see previous definition of 'getopt'
> D:/vcpkg/installed/x64-windows/include\getopt.h(134): warning C4005: 'optarg': macro redefinition
> D:\vcpkg\buildtrees\gettext\src\0.21-508c311661.clean\gettext-tools\gnulib-lib\getopt-pfx-core.h(46): note: see previous definition of 'optarg'
> ```

```
compile cl.exe -DLOCALEDIR=\"/F/vcpkg/installed/x64-windows/debug/share/gettext/locale\" -DBISON_LOCALEDIR=\"\" -DLOCALE_ALIAS_PATH=\"/F/vcpkg/installed/x64-windows/debug/share/gettext/locale\" -DUSEJAVA=0 -DGETTEXTJAR=\"/F/vcpkg/installed/x64-windows/debug/share/gettext/gettext/gettext.jar\" -DLIBDIR=\"/F/vcpkg/installed/x64-windows/debug/lib\" -DGETTEXTDATADIR=\"/F/vcpkg/installed/x64-windows/debug/share/gettext/gettext\" -DPROJECTSDIR=\"/F/vcpkg/installed/x64-windows/debug/share/gettext/gettext/projects\" -DEXEEXT=\".exe\" -DHAVE_CONFIG_H -I. -I../.././../src/0.21-d3cbdc875d/gettext-tools/src -I..  -I. -I../.././../src/0.21-d3cbdc875d/gettext-tools/src -I.. -I../.././../src/0.21-d3cbdc875d/gettext-tools -I../.././../src/0.21-d3cbdc875d/gettext-tools/libgrep -I../gnulib-lib -I../.././../src/0.21-d3cbdc875d/gettext-tools/gnulib-lib -I../intl -I../.././../src/0.21-d3cbdc875d/gettext-tools/../gettext-runtime/intl -DINSTALLDIR=\"/F/vcpkg/installed/x64-windows/debug/../tools/gettext/debug/bin\" -DWIN32 -D_WINDOWS -D_DEBUG  -nologo -W3 -utf-8 -MP -MDd -Z7 -Ob0 -Od -Xcompiler -RTC1 -c -o msginit-msginit.obj `if test -f 'msginit.c'; then cygpath -w 'msginit.c'; else cygpath -w '../.././../src/0.21-d3cbdc875d/gettext-tools/src/msginit.c'; fi`
```
Should add the generated file `getopt.h` path to this command line.

**Comment by JackBoosY** [comment]
@dg0yt I met this issue again when using my changes in https://github.com/microsoft/vcpkg/pull/19325, and I didn't find any code use `optarg_a`, also, I didn't install `getopt-win32`.

**Comment by dg0yt** [comment]
@JackBoosY This issue was: there is a "installed/x64-windows/include/getopt.h" while building gettext.

**Comment by JackBoosY** [comment]
@dg0yt  Sorry, I forgot suffix `-win32`.

**Comment by sfhacker** [comment]
Just built gettext from source on Windows. No issues at all.

![image](https://user-images.githubusercontent.com/25817529/128175908-644ca1d1-b84f-4d28-90f0-aaeef5217c34.png)

[1] https://english-for-chinese.blogspot.com/2008/06/and-meet-problem.html

**Comment by Brooklyn2001** [comment]
Have same error, when compile gettext with [tools}:
-- Configuring x64-windows-rel
-- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:155 (message):                                               Command failed: D:/dev/vcpkg/downloads/tools/msys2/803521c5733336c9/usr/bin/make.exe -j 7 --trace -f D:/dev/vcpkg/ports/gettext/Makefile all                                                                                                    Working Directory: D:/dev/vcpkg/buildtrees/gettext/x64-windows-rel/                                                     See logs for more information:                                                                                            D:\dev\vcpkg\buildtrees\gettext\build-x64-windows-rel-out.log                                                           D:\dev\vcpkg\buildtrees\gettext\build-x64-windows-rel-err.log                                                                                                                                                                             Call Stack (most recent call first):                                                                                      scripts/cmake/vcpkg_build_make.cmake:187 (vcpkg_execute_build_process)                                                  scripts/cmake/vcpkg_install_make.cmake:26 (vcpkg_build_make)                                                     15:23  ports/gettext/portfile.cmake:76 (vcpkg_install_make)                                                                    ports/gettext/portfile.cmake:105 (build_libintl_and_tools)                                                              scripts/ports.cmake:142 (include)                                                                                                                                                                                                                                                                                                                                     Error: Building package gettext:x64-windows failed with: BUILD_FAILED                                                   Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.                                   Then check for known issues at:                                                                                           https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+gettext                                   You can submit a new issue at:                                                                                            https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[gettext]+Build+error    including:                                                                                                                package: gettext[core,tools]:x64-windows -> 0.21#7                                
[build-x64-windows-rel-err.log](https://github.com/microsoft/vcpkg/files/7703690/build-x64-windows-rel-err.log)
[build-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/7703691/build-x64-windows-rel-out.log)

**Comment by mkhon** [comment]
I will re-submit #22202 - it was accidentally closed
