### ISSUE TITLE
libiconv:x64-windows build failure

### ISSUE THREAD

**Issue by AaronVanCuren** [microsoft/vcpkg#18276]
**Host Environment**
- OS: Windows
- Compiler: MINGW64 CMake

**To Reproduce**
`./vcpkg install cairo --triplet x64-windows`

**Failure logs** 
Error: Building package libiconv:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libiconv:x64-windows
  Vcpkg version: 2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9

**Additional context**
I'm following instructions from here: https://github.com/cpp-io2d/P0267_RefImpl/blob/master/BUILDING.md

**Comment by autoantwort** [comment]
Please attach the failure logs :)

**Comment by NancyLi1013** [comment]
@AaronVanCuren 

Can you provide the error info here?

**Comment by NancyLi1013** [comment]
Closing this issue for now since inactive thread. Please feel free to reopen this issue if it is sill a problem for you.

Note: Please update to the latest vcpkg to rebuild. If still failed, please provide the error log.
