### ISSUE TITLE
Fail to link CoolProp

### ISSUE THREAD

**Issue by LiuZhexuan** [microsoft/vcpkg#18281]
**Describe the bug**
I have successfully downloaded and built CoolProp using vcpkg install coolprop. But when I tried to use this pkg, MSVC reported a LINK error saying that function PropsSI not found. It was built as dynamic lib.
Besides, I want to know how to static build this pkg using vcpkg?

**Environment**
- OS: WIN10
- Compiler: MSVS 2019

**To Reproduce**
1. ./vcpkg install coolprop
2. Add following code in main.cpp
#include "CoolPropLib.h"
#include <iostream>

int main()
{
    std::cout << PropsSI("T", "P", 101325, "Q", 0, "Water") << std::endl;
    return 1;
}

**Expected behavior**
Should return 1.

**Failure logs** 
Build started...
1>------ Build started: Project: TestProj, Configuration: Debug x64 ------
1>Main.obj : error LNK2019: unresolved external symbol "double __cdecl PropsSI(char const *,char const *,double,char const *,double,char const *)" (?PropsSI@@YANPEBD0N0N0@Z) referenced in function main
1>D:\Desktop\TestProj\x64\Debug\TestProj.exe : fatal error LNK1120: 1 unresolved externals
1>Done building project "TestProj.vcxproj" -- FAILED.

**Additional context**

**Comment by JackBoosY** [comment]
Confirmed.
