### ISSUE TITLE
https for github is unavailable most of the time, can ssh be supported?

### ISSUE THREAD

**Issue by playgithub** [microsoft/vcpkg#18286]
**Problem**
In my country, `git clone` from github in `https` fails most of the time because of dns problems, it leads to `vcpkg install` failures.

**Proposed solution**
support for `ssh` for github, e.g. `git clone git@github.com:some-lib.git` works.

**Comment by NancyLi1013** [comment]
Hi @strega-nil-ms, @ras0219-msft 

Do we have a plan to support this?
