### ISSUE TITLE
arrow build failure

### ISSUE THREAD

**Issue by ghamarian** [microsoft/vcpkg#18282]
**Host Environment**
- OS:  osx
- Compiler: clang 12

**To Reproduce**
`./vcpkg install arrow`

**Failure logs** 
Port installs fine but when I make a project against it I get the following error.
make[2]: *** No rule to make target `/Users/amir/projects/github-code/vcpkg/installed/x64 osx/debug/lib/libarrow_bundled_dependencies.a'
```
find_package(arrow CONFIG REQUIRED)
target_link_libraries(database PRIVATE arrow_static parquet_static arrow_bundled_dependencies)
target_link_libraries(database PRIVATE LZ4::lz4 re2::re2 arrow_static Snappy::snappy)
```

**Additional context**
I tried both versions but gives the same error message. The older versions of the port generate arrow_bundled_dependencies.

**Comment by autoantwort** [comment]
There is no `libarrow_bundled_dependencies.a`, there is only a `libarrow.a`

**Comment by ghamarian** [comment]
Thanks for responding. I get the same error with or without it. I looked into `ArrowConfig.cmake` in `<path to vcpkg>/packages/arrow_x64-osx/share/arrow`
there is a code like this:
```
    add_library(arrow_bundled_dependencies STATIC IMPORTED)
    set_target_properties(
      arrow_bundled_dependencies
      PROPERTIES
        IMPORTED_LOCATION
        "${arrow_lib_dir}/${CMAKE_STATIC_LIBRARY_PREFIX}arrow_bundled_dependencies${CMAKE_STATIC_LIBRARY_SUFFIX}"
      )

    get_property(arrow_static_interface_link_libraries
                 TARGET arrow_static
                 PROPERTY INTERFACE_LINK_LIBRARIES)
    set_target_properties(
      arrow_static PROPERTIES INTERFACE_LINK_LIBRARIES
      "${arrow_static_interface_link_libraries};arrow_bundled_dependencies")
```

**Comment by autoantwort** [comment]
It seems that here:
 https://github.com/apache/arrow/blob/master/cpp/src/arrow/ArrowConfig.cmake.in#L75

`ARROW_BUNDLED_STATIC_LIBS` is True, but I can't find the code that sets it to true

**Comment by autoantwort** [comment]
Seems that it was already reported and fixed: https://github.com/apache/arrow/pull/9622  
I will update the lib

**Comment by ghamarian** [comment]
Oh! Thanks I missed it, so the vcpkg port does not work. I see there is a pull request for arrow version 4.0.0.

**Comment by JackBoosY** [comment]
We need to update arrow to fix this issue.

**Comment by JonLiu1993** [comment]
@ghamarian ,pr #17975 Update arrow to 4.0.0. I tested arrow:x64-osx locally and it can be used successfully. You can update vcpkg and try again.This issue is temporarily closed. If you have any problems, you can reopen it.
