### ISSUE TITLE
[zstd:x64-windows-static] build failure

### ISSUE THREAD

**Issue by caseyuhrig** [microsoft/vcpkg#18288]
**Host Environment**
- OS: Windows 10
- Compiler: revision
Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

**To Reproduce**
`./vcpkg install zstd:x64-windows-static`

**Failure logs** 
PS C:\Users\casey\Dropbox\source\vcpkg> .\vcpkg.exe install zstd:x64-windows-static
Computing installation plan...
The following packages will be built and installed:
    zstd[core]:x64-windows-static -> 1.4.9
Detecting compiler hash for triplet x64-windows-static...
Could not locate cached archive: C:\Users\casey\AppData\Local\vcpkg\archives\0f\0f3d423d91496358b7b096978af25eebc09043b9.zip
Starting package 1/1: zstd:x64-windows-static
Building package zstd[core]:x64-windows-static...
-- Downloading https://github.com/facebook/zstd/archive/v1.4.9.tar.gz -> facebook-zstd-v1.4.9.tar.gz...
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' = off
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] BuiltinRegistry initialized with: ""
[DEBUG] Using vcpkg-root: C:\Users\casey\Dropbox\source\vcpkg
[DEBUG] Using installed-root: C:\Users\casey\Dropbox\source\vcpkg\installed
[DEBUG] BuiltinRegistry initialized with: ""
[DEBUG] Using buildtrees-root: C:\Users\casey\Dropbox\source\vcpkg\buildtrees
[DEBUG] Using downloads-root: C:\Users\casey\Dropbox\source\vcpkg\downloads
[DEBUG] Using packages-root: C:\Users\casey\Dropbox\source\vcpkg\packages
[DEBUG] Using scripts-root: C:\Users\casey\Dropbox\source\vcpkg\scripts
[DEBUG] Using ports-root: C:\Users\casey\Dropbox\source\vcpkg\ports
[DEBUG] Using versions-root: C:\Users\casey\Dropbox\source\vcpkg\versions
invalid command: x-download
Commands:
  vcpkg search [pat]              Search for packages available to be built
  vcpkg install <pkg>...          Install a package
  vcpkg remove <pkg>...           Uninstall a package
  vcpkg remove --outdated         Uninstall all out-of-date packages
  vcpkg list                      List installed packages
  vcpkg update                    Display list of packages for updating
  vcpkg upgrade                   Rebuild all outdated packages
  vcpkg x-history <pkg>           (Experimental) Shows the history of CONTROL versions of a package
  vcpkg hash <file> [alg]         Hash a file by specific algorithm, default SHA512
  vcpkg help topics               Display the list of help topics
  vcpkg help <topic>              Display help for a specific topic

  vcpkg integrate install         Make installed packages available user-wide. Requires admin
                                  privileges on first use
  vcpkg integrate remove          Remove user-wide integration
  vcpkg integrate project         Generate a referencing nuget package for individual VS project use
  vcpkg integrate powershell      Enable PowerShell tab-completion

  vcpkg export <pkg>... [opt]...  Exports a package
  vcpkg edit <pkg>                Open up a port for editing (uses %EDITOR%, default 'code')
  vcpkg create <pkg> <url> [archivename]
                                  Create a new package
  vcpkg owns <pat>                Search for files in installed packages
  vcpkg depend-info <pkg>...      Display a list of dependencies for packages
  vcpkg env                       Creates a clean shell environment for development or compiling
  vcpkg version                   Display version information
  vcpkg contact                   Display contact information to send feedback

Options:
  --triplet=<t>                   Specify the target architecture triplet. See 'vcpkg help triplet'
                                  (default: %VCPKG_DEFAULT_TRIPLET%)
  --host-triplet=<t>              Specify the host architecture triplet. See 'vcpkg help triplet'
                                  (default: %VCPKG_DEFAULT_HOST_TRIPLET%)
  --overlay-ports=<path>          Specify directories to be used when searching for ports
                                  (also: %VCPKG_OVERLAY_PORTS%)
  --overlay-triplets=<path>       Specify directories containing triplets files
                                  (also: %VCPKG_OVERLAY_TRIPLETS%)
  --binarysource=<path>           Add sources for binary caching. See 'vcpkg help binarycaching'
  --downloads-root=<path>         Specify the downloads root directory
                                  (default: %VCPKG_DOWNLOADS%)
  --vcpkg-root=<path>             Specify the vcpkg root directory
                                  (default: %VCPKG_ROOT%)
  --x-buildtrees-root=<path>      (Experimental) Specify the buildtrees root directory
  --x-install-root=<path>         (Experimental) Specify the install root directory
  --x-packages-root=<path>        (Experimental) Specify the packages root directory
  --x-scripts-root=<path>         (Experimental) Specify the scripts root directory
  --x-builtin-ports-root=<path>   (Experimental) Specify the packages root directory
  --x-builtin-registry-versions-dir=<path>
                                  (Experimental) Specify the versions root directory
  --x-json                        (Experimental) Request JSON output

  @response_file                  Specify a response file to provide additional parameters

For more help (including examples) see the accompanying README.md and docs folder.
[DEBUG] C:\A\1\70\s\src\vcpkg.cpp(46)
[DEBUG] Exiting after 17690 us (3292 us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:226 (message):

      If you use a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.

      3. You proxy's remote server is out of service.

      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)

      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:147 (vcpkg_download_distfile)
  ports/zstd/portfile.cmake:1 (vcpkg_from_github)
  scripts/ports.cmake:139 (include)

Error: Building package zstd:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zstd:x64-windows-static
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

Additionally, attach any relevant sections from the log files above.

**Additional context**
I was installing boost-iostreams and zstd was required and failed. Tried installing zstd interdependently after the fact and got the same error. I also updated everything using the latest profiles.

**Comment by caseyuhrig** [comment]
Spoke too soon, this is something on my and vcpkg got corrupted somehow.

**Comment by aitchpea** [comment]
I have just had the same issue as above but when running:

vcpkg install llvm:x64-windows

I have the same version of vcpkg (and also running Windows 10). I can see you have closed this issue and you seem to indicate it was an issue on your side - but I thought it worth mentioning that it has affected me too.

The thing I find strange is the message I got (and I see it in yours too) partway down saying 

"invalid command: x-download"

**Comment by caseyuhrig** [comment]
I "believe" that I had corrupted my vcpkg configuration by accidentally breaking out of a package install (oops). After the fact I went back through and did a complete re-setup of my vcpkg packages.  Kinda a pain, but didn't take too long. All was good after that!
