### ISSUE TITLE
[New Port Request] wxwidgets 3.15

### ISSUE THREAD

**Issue by PJMonty** [microsoft/vcpkg#18280]
Library name: wxwidgets 3.15

Library description: Cross-Platform GUI Library

Source repository URL: https://github.com/wxWidgets/wxWidgets

Project homepage (if different from the source repository): https://www.wxwidgets.org/

Anything else that is useful to know when adding (such as optional features the library may have that should be included): Current version in vcpkg is 3.14, but latest release is 3.15.

**Comment by autoantwort** [comment]
It is already there?

**Comment by PJMonty** [comment]
No.  The latest in vcpkg is 3.14:
![image](https://user-images.githubusercontent.com/20196069/120907552-5787d800-c617-11eb-9eff-d8ffaefc4cdb.png)
The latest release from the wxwidgets project is 3.15.

**Comment by autoantwort** [comment]
Yeah already included: https://github.com/microsoft/vcpkg/blob/master/ports/wxwidgets/vcpkg.json  
Maybe you should update your vcpkg version (git pull)

**Comment by JonLiu1993** [comment]
@PJMonty ,Thanks posting this issue,
the latest version of wxwidgets is [3.1.5](https://github.com/microsoft/vcpkg/blob/eed75c0ad57c9e41537f4006debca6cdd7021f25/ports/wxwidgets/vcpkg.json), please update your vcpkg version, if not, please clone vcpkg again.
