### ISSUE TITLE
Trying out versioning Getting Started page. How do I find right argument for find_package for manifest dependencies

### ISSUE THREAD

**Issue by tonygould** [microsoft/vcpkg#18297]
Starting at https://github.com/microsoft/vcpkg/blob/master/docs/examples/versioning.getting-started.md, we have "zlib" in manifest but "find_package(ZLIB)" in CMake. Similarly if I have "nlohmann-json" in manifest, it's "find_package(nlohmann_json)" in CMake. Is the algorithm capitalisation or adding underscores or is there some metadata somewhere, or something else? Only way I could see to find this out seems to be to run CMake, have it fail, then "find build -name '*.cmake'", and look at the filenames.

Related, it's pretty opaque to me why in your example, we don't have "CONFIG" in "find_package(ZLIB REQUIRED)" but do have it in "find_package(fmt CONFIG REQUIRED)". I'd prefer you didn't assume that people who want to get going with vcpkg are CMake experts.

Almost finally, if I go with the example on this page and use "version>=": "7.1.3", I get error "Error: Version conflict on fmt:x64-linux: baseline required 7.1.3#4 but vcpkg could not compare it to 7.1.3". This isn't very intuitive, and nor does the subsequent explanation help! As a new user, I'd like the "starter" example to work out the box. I found out after a lot of hacking I could change the text to "7.1.3#4" and it would work.

Finally, really finally, if I use the given baseline, I get: Couldn't find explicitly specified baseline `"b60f003ccf5fe8613d029f49f835c8929a66eb61"` in the baseline file, and there was no baseline at that commit or the commit didn't exist. It works fine if I delete this line, or use a recent vcpkg commit, e.g. "751fc199af8d33eb300af5edbd9e3b77c48f0bca". Again, the error message is very obscure -- the commit exists in my repo, and git pull doesn't help -- and it would be good for a starter example to just work.

**Comment by PhoebeHui** [comment]
@tonygould, thanks for your feedbacks!
I think the following 2 docs could help to solve the first 2questions.
https://cmake.org/cmake/help/latest/manual/cmake-packages.7.html
https://cmake.org/cmake/help/latest/command/find_package.html

For the latest 2 questions, sorry for the confuse, may be we can given a message about the baseline in the example?
https://github.com/microsoft/vcpkg/blob/master/docs/examples/versioning.getting-started.md#builtin-baseline

**Comment by tonygould** [comment]
Thanks Phoebe! Apologies btw for putting all these issues in a single github issue; I probably should have split some of them out. Anyway in reply

q1 I don't see how the cmake documentation answers the specific question of how to know what to type into find_package. I go to https://vcpkg.io/en/packages.html, find "zlib", and put it in my vcpkg.json. How do I know that it should be "ZLIB" not "zlib" as the argument to find_package?

q2 Thanks for the document links. I still think it would be good for your page to explain why you use "CONFIG" in one case and not in the other. Are you able to do that?

q3, q4 Sorry I don't understand your reply. On my machine, using the (rather out of date) baseline, I get some very confusing error messages, e.g. instructing me to "git pull" my vcpkg repo when I just cloned it. If you try to run your example, I expect you might see same.

**Comment by tonygould** [comment]
Re q3, q4, the problems I had yesterday were on linux. I just tried again with windows, to see if I could repro. This is what I got using the vcpkg.json file from https://github.com/microsoft/vcpkg/blob/master/docs/examples/versioning.getting-started.md. I.e.

    {
        "name": "versions-test",
        "version": "1.0.0",
        "dependencies": [
            {
                "name": "fmt",
                "version>=": "7.1.3"
            },
            "zlib"
        ],
        "builtin-baseline": "b60f003ccf5fe8613d029f49f835c8929a66eb61"
    }

output


    [proc] Executing command: "c:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.EXE" --no-warn-unused-cli -DCMAKE_TOOLCHAIN_FILE:STRING=../vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -Hc:/Users/anton/dev/versiontest -Bc:/Users/anton/dev/versiontest/build -G "Visual Studio 16 2019" -T host=x86 -A x64
    [cmake] Not searching for unused variables given on the command line.
    [cmake] -- Running vcpkg install
    [cmake] Error: Couldn't find explicitly specified baseline `"b60f003ccf5fe8613d029f49f835c8929a66eb61"` in the baseline file, and there was no baseline at that commit or the commit didn't exist.
    [cmake] Error: while checking out baseline 'b60f003ccf5fe8613d029f49f835c8929a66eb61:versions/baseline.json':
    [cmake] fatal: path 'versions/baseline.json' exists on disk, but not in 'b60f003ccf5fe8613d029f49f835c8929a66eb61'
    [cmake] 
    [cmake] This may be fixed by updating vcpkg to the latest master via `git pull`.
    [cmake] The current commit is "b2544fd780b2e9a05d903314cbbd37268ba43d81"
    
If I delete the `baseline` line and/or replace with a more recent commit,

    {
        "name": "versions-test",
        "version": "1.0.0",
        "dependencies": [
            {
                "name": "fmt",
                "version>=": "7.1.3"
            },
            "zlib"
        ],
        "builtin-baseline": "b2544fd780b2e9a05d903314cbbd37268ba43d81"
    }

I get:

    [proc] Executing command: "c:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.EXE" --no-warn-unused-cli -DCMAKE_TOOLCHAIN_FILE:STRING=../vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -Hc:/Users/anton/dev/versiontest -Bc:/Users/anton/dev/versiontest/build -G "Visual Studio 16 2019" -T host=x86 -A x64
    [cmake] Not searching for unused variables given on the command line.
    [cmake] -- Running vcpkg install
    [cmake] Error: Version conflict on fmt:x64-windows: baseline required 7.1.3#4 but vcpkg could not compare it to 7.1.3
    [cmake] 
    [cmake] The two versions used incomparable schemes:
    [cmake]     "7.1.3" was of scheme string
    [cmake]     "7.1.3#4" was of scheme relaxed
    [cmake] 
    [cmake] This can be resolved by adding an explicit override to the preferred version, for example:
    [cmake] 
    [cmake]     "overrides": [
    [cmake]         { "name": "fmt", "version": "7.1.3" }
    [cmake]     ]
    
The first issue looks like a bug to me. Both are, at least, an issue with the page, in that the example given simply doesn't work in two respects.

I can report this as a separate issue on github if that helps?

**Comment by dg0yt** [comment]
> q1 I don't see how the cmake documentation answers the specific question of how to know what to type into find_package. I go to https://vcpkg.io/en/packages.html, find "zlib", and put it in my vcpkg.json. How do I know that it should be "ZLIB" not "zlib" as the argument to find_package?

`vcpkg install xy` may print usage information when port xy is installed successfully. 

Basically, what to use is the domain of CMake, not of vcpkg. ZLIB is one of the many "Find modules" which come with CMake itself. Cf. 
https://cmake.org/cmake/help/latest/manual/cmake-modules.7.html#find-modules

> q2 Thanks for the document links. I still think it would be good for your page to explain why you use "CONFIG" in one case and not in the other. Are you able to do that?

Traditionally CMake itself provides some "Find modules" (`find_package` Module Mode), In the past, many projects used to invent own "Find modules" for their dependencies. This was hard to work with when dealing with many transitive dependencies.
"Modern CMake" usage is built around software packages bringing their own "CMake Config" files, i.e. each project taking care of its own stuff and quality. The `CONFIG` keyword explicitly requests `find_package` Config Mode. 
https://cmake.org/cmake/help/latest/command/find_package.html

**Comment by Osyotr** [comment]
@dg0yt `vcpkg install xy` will work, but it doesn't look like good solution. We need something like `vcpkg port-usage zlib` which will just `cat vcpkg_installed/share/zlib/USAGE`

**Comment by tonygould** [comment]
> @dg0yt `vcpkg install xy` will work, but it doesn't look like good solution. We need something like `vcpkg port-usage zlib` which will just `cat vcpkg_installed/share/zlib/USAGE`

Yes, that helps a lot!

    $ cat build/vcpkg_installed/x64-linux/share/zlib/usage 
    The package zlib is compatible with built-in CMake targets:

    find_package(ZLIB REQUIRED)
    target_link_libraries(main PRIVATE ZLIB::ZLIB)

I imagine similar would work on Windows (it was trivial to get my linux test repos working on Windows earlier today). From a dumb user's point of view, if you included that output in your catalog https://vcpkg.io/en/packages.html that would help. At the moment if I click on detail for zlib, say, I get `.\vcpkg install zlib`, which doesn't help me at all -- so far I've never used the `install` command, presumably because I'm working on manifest rather than in "classic" mode. (Apologies if I have this wrong but I'm a new user, trying to evaluate vcpkg for use at work after viewing the Pure Virtual C++ video https://channel9.msdn.com/Events/CPP/Pure-Virtual-Cpp-2021/Manage-code-dependencies-at-work-with-new-vcpkg-features)

**Comment by dg0yt** [comment]
> so far I've never used the install command, presumably because I'm working on manifest rather than in "classic" mode. 

I see, and I read your questions from a different perspective now.

> `vcpkg install xy` will work, but it doesn't look like good solution. We need something like `vcpkg port-usage zlib` which will just `cat vcpkg_installed/share/zlib/USAGE`

I was pointing to what is available now. (You can call this command also for installed packages.) 
For what is discussed, see https://github.com/microsoft/vcpkg-tool/pull/82. There are many packages which don't even have a usage file.

**Comment by tonygould** [comment]
> There are many packages which don't even have a usage file.

As I realized when I tried to `cat`  a usage file at work. But your top of `vcpkg install xy ` worked, thanks.

**Comment by nmoreaud** [comment]
> 
> 
> Re q3, q4, the problems I had yesterday were on linux. I just tried again with windows, to see if I could repro. This is what I got using the vcpkg.json file from https://github.com/microsoft/vcpkg/blob/master/docs/examples/versioning.getting-started.md. I.e.
> 
> ```
> {
>     "name": "versions-test",
>     "version": "1.0.0",
>     "dependencies": [
>         {
>             "name": "fmt",
>             "version>=": "7.1.3"
>         },
>         "zlib"
>     ],
>     "builtin-baseline": "b60f003ccf5fe8613d029f49f835c8929a66eb61"
> }
> ```
> 
> output
> 
> ```
> [proc] Executing command: "c:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.EXE" --no-warn-unused-cli -DCMAKE_TOOLCHAIN_FILE:STRING=../vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -Hc:/Users/anton/dev/versiontest -Bc:/Users/anton/dev/versiontest/build -G "Visual Studio 16 2019" -T host=x86 -A x64
> [cmake] Not searching for unused variables given on the command line.
> [cmake] -- Running vcpkg install
> [cmake] Error: Couldn't find explicitly specified baseline `"b60f003ccf5fe8613d029f49f835c8929a66eb61"` in the baseline file, and there was no baseline at that commit or the commit didn't exist.
> [cmake] Error: while checking out baseline 'b60f003ccf5fe8613d029f49f835c8929a66eb61:versions/baseline.json':
> [cmake] fatal: path 'versions/baseline.json' exists on disk, but not in 'b60f003ccf5fe8613d029f49f835c8929a66eb61'
> [cmake] 
> [cmake] This may be fixed by updating vcpkg to the latest master via `git pull`.
> [cmake] The current commit is "b2544fd780b2e9a05d903314cbbd37268ba43d81"
> ```
> 
> If I delete the `baseline` line and/or replace with a more recent commit,
> 
> ```
> {
>     "name": "versions-test",
>     "version": "1.0.0",
>     "dependencies": [
>         {
>             "name": "fmt",
>             "version>=": "7.1.3"
>         },
>         "zlib"
>     ],
>     "builtin-baseline": "b2544fd780b2e9a05d903314cbbd37268ba43d81"
> }
> ```
> 
> I get:
> 
> ```
> [proc] Executing command: "c:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.EXE" --no-warn-unused-cli -DCMAKE_TOOLCHAIN_FILE:STRING=../vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -Hc:/Users/anton/dev/versiontest -Bc:/Users/anton/dev/versiontest/build -G "Visual Studio 16 2019" -T host=x86 -A x64
> [cmake] Not searching for unused variables given on the command line.
> [cmake] -- Running vcpkg install
> [cmake] Error: Version conflict on fmt:x64-windows: baseline required 7.1.3#4 but vcpkg could not compare it to 7.1.3
> [cmake] 
> [cmake] The two versions used incomparable schemes:
> [cmake]     "7.1.3" was of scheme string
> [cmake]     "7.1.3#4" was of scheme relaxed
> [cmake] 
> [cmake] This can be resolved by adding an explicit override to the preferred version, for example:
> [cmake] 
> [cmake]     "overrides": [
> [cmake]         { "name": "fmt", "version": "7.1.3" }
> [cmake]     ]
> ```
> 
> The first issue looks like a bug to me. Both are, at least, an issue with the page, in that the example given simply doesn't work in two respects.
> 
> I can report this as a separate issue on github if that helps?

Did you find a solution?

**Comment by tonygould** [comment]
> Did you find a solution?

No. There is a bug in the documentation and/or vcpkg itself, in my opinion. A workaround is not to use the version / baseline, or to use a version that works (e.g. `"version>=": "7.1.3#4"`) or a more recent baseline (e.g. `"builtin-baseline": "b2544fd780b2e9a05d903314cbbd37268ba43d81"`). But this is missing the point -- the idea of versioning is to specify a minimum version and have the system figure everything out, not reverse engineer the system implementation to come up with a specification.

Are you seeing similar? I'm intending to create another issue for this when I get time. I really shouldn't have put all these in one issue, and the first half of my question here have been addressed.

**Comment by tonygould** [comment]
q3, q4 resolved, thanks. q1, q2 unresolved and have been reported separately at https://github.com/microsoft/vcpkg/issues/18533.

**Comment by nmoreaud** [comment]
> 
> 
> > Did you find a solution?
> 
> No. There is a bug in the documentation and/or vcpkg itself, in my opinion. A workaround is not to use the version / baseline, or to use a version that works (e.g. `"version>=": "7.1.3#4"`) or a more recent baseline (e.g. `"builtin-baseline": "b2544fd780b2e9a05d903314cbbd37268ba43d81"`). But this is missing the point -- the idea of versioning is to specify a minimum version and have the system figure everything out, not reverse engineer the system implementation to come up with a specification.
> 
> Are you seeing similar? I'm intending to create another issue for this when I get time. I really shouldn't have put all these in one issue, and the first half of my question here have been addressed.

Yes, having to specify a commit ID as the baseline is very strange.
In my opinion, they are trying to mimic Linux distributions which have periodic releases. We could refer VCPKG repository version as: `"baseline": "2019-06"`. But in most package manager, the versions are not centralized this way, you can just pick the library version you want and have to deal with incompatibilities. I also saw that I cannot list easily which versions are available.

This syntax seems very strange to me:
```{
    "name": "versions-test",
    "version": "1.0.0",
    "dependencies": [
        {
            "name": "fmt",
            "version>=": "7.1.3"
        },
        {
            "name": "zlib",
            "version>=": "1.2.11#7"
        }
    ],
    "builtin-baseline": "b60f003ccf5fe8613d029f49f835c8929a66eb61",
    "overrides": [
        {
            "name": "fmt",
            "version": "6.0.0"
        }
    ]
}
```

What's the point: do you want fmt 6.0.0 or fmt 7.1.3?
Why not just put it in the dependencies list, or add a "force" tag if the baseline concept is realy important?

Just installing VCPKG seems like reverse engineering to me. it seems to be very fresh piece of software, it doesn't provide end to end examples for common use cases. Ex: I want to add 3 binaries libs with specified version in my project and make them easily available for anyone who works on the project.
If you have knowledge about it usage, mind you answer to my questions here? https://devblogs.microsoft.com/cppblog/all-vcpkg-enterprise-features-now-generally-available-versioning-binary-caching-manifests-and-registries/#comment-1795

**Comment by tonygould** [comment]
> Just installing VCPKG seems like reverse engineering to me. it seems to be very fresh piece of software, it doesn't provide end to end examples for common use cases. Ex: I want to add 3 binaries libs with specified version in my project and make them easily available for anyone who works on the project.
> If you have knowledge about it usage, mind you answer to my questions here? https://devblogs.microsoft.com/cppblog/all-vcpkg-enterprise-features-now-generally-available-versioning-binary-caching-manifests-and-registries/#comment-1795

Those are some good questions on the cppblog page. To answer the first one, what happens is that for every build configuration of every project, vcpkg copies the binaries from its cache into the build folder for that configuration. So if you build n configurations across m projects, n >= m, you will have (n+1) copies of each binary, including the cache. I believe that conan references binaries directly rather than copying them into your project build folders; I am hoping that vcpkg will make that optimization in due course. Conan is the obvious alternative to vcpkg, and much more mature, but it isn't without its own problems. The reality is that C++ package management still has a long way to go to get close to Python's, say.

**Comment by tonygould** [comment]
@nmoreaud 

> it seems to be very fresh piece of software, it doesn't provide end to end examples for common use cases.

I agree on this. Again, conan is the alternative, and is kind of the opposite in that it's very mature, and does _everything_. In fact I think it does too much, conflates too many things, is over-complex, and despite seeming comprehensive, doesn't handle some basic scenarios (e.g. try getting google test with clang 11 on windows, or even clang 10 on linux). I think the vcpkg architecture is more elegant, but as you say it's newer and lacks documentation, especially documentation oriented towards using it in an enterprise scenario.

**Comment by waruqi** [comment]
> > > Did you find a solution?
> > 
> > 
> > No. There is a bug in the documentation and/or vcpkg itself, in my opinion. A workaround is not to use the version / baseline, or to use a version that works (e.g. `"version>=": "7.1.3#4"`) or a more recent baseline (e.g. `"builtin-baseline": "b2544fd780b2e9a05d903314cbbd37268ba43d81"`). But this is missing the point -- the idea of versioning is to specify a minimum version and have the system figure everything out, not reverse engineer the system implementation to come up with a specification.
> > Are you seeing similar? I'm intending to create another issue for this when I get time. I really shouldn't have put all these in one issue, and the first half of my question here have been addressed.
> 
> Yes, having to specify a commit ID as the baseline is very strange. In my opinion, they are trying to mimic Linux distributions which have periodic releases. We could refer VCPKG repository version as: `"baseline": "2019-06"`. But in most package manager, the versions are not centralized this way, you can just pick the library version you want and have to deal with incompatibilities. I also saw that I cannot list easily which versions are available.
> 
> This syntax seems very strange to me:
> 
> ```
>     "name": "versions-test",
>     "version": "1.0.0",
>     "dependencies": [
>         {
>             "name": "fmt",
>             "version>=": "7.1.3"
>         },
>         {
>             "name": "zlib",
>             "version>=": "1.2.11#7"
>         }
>     ],
>     "builtin-baseline": "b60f003ccf5fe8613d029f49f835c8929a66eb61",
>     "overrides": [
>         {
>             "name": "fmt",
>             "version": "6.0.0"
>         }
>     ]
> }
> ```
> 
> What's the point: do you want fmt 6.0.0 or fmt 7.1.3? Why not just put it in the dependencies list, or add a "force" tag if the baseline concept is realy important?
> 
> There is also something dangerous: with Visual Studio and MSBuild, if I write build the master branch fo my project which depends on fmt v6, then switch to the dev branch which uses fmt v7; Visual Studio doesn't call VCPKG again: I'm stuck with fmt6.
> 
> Just installing VCPKG seems like reverse engineering to me. it seems to be very fresh piece of software, it doesn't provide end to end examples for common use cases. Ex: I want to add 3 binaries libs with specified version in my project and make them easily available for anyone who works on the project. If you have knowledge about it usage, mind you answer to my questions here? https://devblogs.microsoft.com/cppblog/all-vcpkg-enterprise-features-now-generally-available-versioning-binary-caching-manifests-and-registries/#comment-1795

We can also try xmake, it has better package management.

Recently I am also making xmake support the vcpkg manifest mode, but I have encountered many problems. For example, the vcpkg installed by homebrew cannot find any specified baselines. Similar to this issue, I don't know how to solve it.
