### ISSUE TITLE
[rapidjson] port usage reports wrong variable

### ISSUE THREAD

**Issue by upsj** [microsoft/vcpkg#18292]
****

**Is your feature request related to a problem? Please describe.**
RapidJSON provides its install path as `RapidJSON_INCLUDE_DIR(S)`, the port adds `RAPIDJSON_INCLUDE_DIRS` for backwards-compatibility with older versions. It seems like the usage output catches only the last variable being set:
```
The package rapidjson provides CMake integration:

    find_package(RapidJSON CONFIG REQUIRED)
    target_include_directories(main PRIVATE ${RAPIDJSON_INCLUDE_DIRS})
```

**Proposed solution**
I am not certain what is the correct way to fix the usage message - if it's possible to set the include variable explicitly, that would probably be ideal. I would be happy to do it if somebody can point me to the correct knob to turn :)

**Describe alternatives you've considered**
Alternatively, trick the usage message generation heuristic? But that does sound a bit hacky.

**Comment by JackBoosY** [comment]
Yeah, we need to add macro `RapidJSON_INCLUDE_DIRS` to the usage file.
