### ISSUE TITLE
[jxrlib] build failure

### ISSUE THREAD

**Issue by jamecc** [microsoft/vcpkg#18294]
**Host Environment**
- OS: Windows 10
- Compiler: Mingw 8

**To Reproduce**
`./vcpkg install ogre-next  --triplet=x86-mingw-static`

**Failure logs** 
D:/source/vcpkg/buildtrees/jxrlib/src/0dd9dbbdb4-4d68cbd583.clean/image/sys/windowsmediaphoto.h:249:43: error: size of array '__CT_ASSERT__strcodec1' is negative
 #define CT_ASSERT(exp, uniq) typedef char __CT_ASSERT__##uniq[(exp) ? 1 : -1] // Caller must provide a unique tag, or this fails to compile under GCC
                                           ^~~~~~~~~~~~~
D:/source/vcpkg/buildtrees/jxrlib/src/0dd9dbbdb4-4d68cbd583.clean/image/sys/strcodec.h:92:1: note: in expansion of macro 'CT_ASSERT'
 CT_ASSERT(sizeof(UINTPTR_T) == sizeof(void*), strcodec1);
 ^~~~~~~~~
D:/source/vcpkg/buildtrees/jxrlib/src/0dd9dbbdb4-4d68cbd583.clean/image/sys/windowsmediaphoto.h:249:43: error: size of array '__CT_ASSERT__strcodec2' is negative
 #define CT_ASSERT(exp, uniq) typedef char __CT_ASSERT__##uniq[(exp) ? 1 : -1] // Caller must provide a unique tag, or this fails to compile under GCC
                                           ^~~~~~~~~~~~~
D:/source/vcpkg/buildtrees/jxrlib/src/0dd9dbbdb4-4d68cbd583.clean/image/sys/strcodec.h:93:1: note: in expansion of macro 'CT_ASSERT'
 CT_ASSERT(sizeof(INTPTR_T) == sizeof(void*), strcodec2);
[install-x86-mingw-static-dbg-out.log](https://github.com/microsoft/vcpkg/files/6604222/install-x86-mingw-static-dbg-out.log)

**Comment by FrankXie05** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
