### ISSUE TITLE
vcpkg_from_git fails when downloads folder does not exist

### ISSUE THREAD

**Issue by alberthdev** [microsoft/vcpkg#18291]
**Describe the bug**
vcpkg_from_git fails to run its `git init` test when the vcpkg\downloads folder does not exist. 

**Environment**
- OS: Windows
- Compiler: MSVC 2019

**To Reproduce**
1. Setup an environment where all of the required tools needed for vcpkg are up to date and the latest. (GitHub Actions' environment is where I was able to have this kind of environment.)
2. Run `./vcpkg install [--debug] <pkg>`, where `<pkg>` is a package that engages vcpkg_from_git.
3. Error will occur that looks like this (log snip with --debug):

```
-- Fetching https://android.googlesource.com/platform/external/fdlibm...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:109 (message):
    Command failed: "C:/Program Files/Git/bin/git.exe" init git-tmp
    Working Directory: D:/a/github-actions-test/github-actions-test/vcpkg/downloads
    Error code: The system cannot find the file specified
    See logs for more information:

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_git.cmake:85 (vcpkg_execute_required_process)
  ports/fdlibm/portfile.cmake:1 (vcpkg_from_git)
  scripts/ports.cmake:139 (include)


[DEBUG] cmd_execute_and_stream_data() returned 1 after    45703 us
Error: Building package fdlibm:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: fdlibm:x86-windows
  Vcpkg version: 2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9

Additionally, attach any relevant sections from the log files above.
```

**Expected behavior**
The git checkout succeeds (or in this case, the git init test succeeds). Success in this function would result in the port being downloaded, built, and installed.

**Failure logs** 
- Raw log files:
   - [Vcpkg_AllDepsSatisfied_GitHubActions.log](https://github.com/microsoft/vcpkg/files/6603758/Vcpkg_AllDepsSatisfied_GitHubActions.log) - this is a from GitHub Actions run with all of the dependencies satisfied, triggering this bug.
  - [Vcpkg_ReqDownloadDeps_GitHubActions.log](https://github.com/microsoft/vcpkg/files/6603759/Vcpkg_ReqDownloadDeps_GitHubActions.log) - this is from a local run where dependencies needed to be downloaded for vcpkg to begin.

**Additional context**
Workaround for this problem was to create the vcpkg\downloads directory prior to starting `vcpkg install`. This allowed the build to complete successfully.

I've attached the GitHub Actions YAML that can be used to reproduce the problem:
- [vcpkg.github_actions.failure.yml.txt](https://github.com/microsoft/vcpkg/files/6603771/vcpkg.github_actions.failure.yml.txt)
- [vcpkg.github_actions.success.yml.txt](https://github.com/microsoft/vcpkg/files/6603772/vcpkg.github_actions.success.yml.txt)

The repo that I tested on for this problem can be found [here](https://github.com/alberthdev/github-actions-test/tree/f10db3ab5792955742e683c3a1db3c6f27d8705b) - recommended to clone this as it has the required fix needed to debug, as seen in the next blurb.

Noting that in order to trace this problem, I needed to add additional checks to vcpkg_execute_required_process.cmake, as it was prematurely failing due to the stdout log not existing. A log snip with the failure in question:

```
Starting package 1/1: fdlibm:x86-windows
Building package fdlibm[core]:x86-windows...
-- Fetching https://android.googlesource.com/platform/external/fdlibm...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:91 (file):
  file failed to open for reading (No such file or directory):

    D:/a/github-actions-test/github-actions-test/vcpkg/buildtrees/fdlibm/git-init-x86-windows-out.log
Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_git.cmake:85 (vcpkg_execute_required_process)
  ports/fdlibm/portfile.cmake:1 (vcpkg_from_git)
  scripts/ports.cmake:139 (include)


Error: Building package fdlibm:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: fdlibm:x86-windows
  Vcpkg version: 2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9

Additionally, attach any relevant sections from the log files above.
```

The updated cmake file that address the above problem can be found [here](https://github.com/alberthdev/github-actions-test/blob/f10db3ab5792955742e683c3a1db3c6f27d8705b/.github/workflows/vcpkg-patches/vcpkg_execute_required_process.cmake) and in the draft PR #18290.

**Comment by JackBoosY** [comment]
@strega-nil-ms Can you please take a look?

Thanks.

**Comment by PhoebeHui** [comment]
@alberthdev, what's the git revison in your machine? could you use the git that downloaded by vcpkg and see if this issue still repro?

**Comment by JackBoosY** [comment]
Can you please test whether https://github.com/microsoft/vcpkg/pull/18340 fixed this issue?

Thanks.

**Comment by alberthdev** [comment]
That PR seems to be merged, so I tried with the latest (14418e1e48ff563382fbe970637425c52d109b16) and no dice there. I tested by jumping to that commit, and then attempting to install bzip2. Same error as earlier:

```
Could not locate cached archive: C:\Users\runneradmin\AppData\Local\vcpkg\archives\6c\6cd4c7e87c24b1955353546c2a41b6f20aa6d8dd.zip
Starting package 1/1: bzip2:x86-windows
Building package bzip2[core]:x86-windows...
[DEBUG] CreateProcessW("C:\Program Files\CMake\bin\cmake.exe" -DALL_FEATURES= -DCURRENT_PORT_DIR=D:/a/github-actions-test/github-actions-test/vcpkg/ports/bzip2 -D_HOST_TRIPLET=x64-windows -DFEATURES=core -DPORT=bzip2 -DVCPKG_USE_HEAD_VERSION=0 -D_VCPKG_DOWNLOAD_TOOL=BUILT_IN -D_VCPKG_EDITABLE=0 -D_VCPKG_NO_DOWNLOADS=0 -DCMD=BUILD -DDOWNLOADS=D:/a/github-actions-test/github-actions-test/vcpkg/downloads -DTARGET_TRIPLET=x86-windows "-DTARGET_TRIPLET_FILE=D:\a\github-actions-test\github-actions-test\vcpkg\triplets\x86-windows.cmake" -DVCPKG_BASE_VERSION=2021-05-05 -DVCPKG_CONCURRENCY=3 -DVCPKG_PLATFORM_TOOLSET=v142 "-DGIT=C:/Program Files/Git/bin/git.exe" -DVCPKG_ROOT_DIR=D:/a/github-actions-test/github-actions-test/vcpkg -DPACKAGES_DIR=D:/a/github-actions-test/github-actions-test/vcpkg/packages -DBUILDTREES_DIR=D:/a/github-actions-test/github-actions-test/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=D:/a/github-actions-test/github-actions-test/vcpkg/installed -DDOWNLOADS=D:/a/github-actions-test/github-actions-test/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "D:\a\github-actions-test\github-actions-test\vcpkg\scripts\ports.cmake")
-- Fetching https://sourceware.org/git/bzip2.git...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:109 (message):
    Command failed: "C:/Program Files/Git/bin/git.exe" init git-tmp
    Working Directory: D:/a/github-actions-test/github-actions-test/vcpkg/downloads
    Error code: The system cannot find the file specified
    See logs for more information:

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_git.cmake:85 (vcpkg_execute_required_process)
  ports/bzip2/portfile.cmake:1 (vcpkg_from_git)
  scripts/ports.cmake:139 (include)


[DEBUG] cmd_execute_and_stream_data() returned 1 after    46132 us
Error: Building package bzip2:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: bzip2:x86-windows
  Vcpkg version: 2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9

Additionally, attach any relevant sections from the log files above.
[DEBUG] C:\A\1\121\s\src\vcpkg\install.cpp(511)
[DEBUG] Exiting after 14186783 us (14170984 us)
FAILED
```

Attached the GitHub Actions YAML used to test: [vcpkg.github_actions.failure.20210614.yml.txt](https://github.com/microsoft/vcpkg/files/6659595/vcpkg.github_actions.failure.20210614.yml.txt). Uncommenting the directory creation fixes the error.

I was also able to reproduce this issue using Docker on Windows (HyperV). With the Docker setup, I was able to confirm that satisfying all of the prerequisites for vcpkg prevents the `downloads` directory from being created, and causes this to fail.

Failure log with mitigation by creating downloads directory: [vcpkg.docker.failure.20210615.log.txt](https://github.com/microsoft/vcpkg/files/6659594/vcpkg.docker.failure.20210615.log.txt)

Dockerfile for reproducing this issue: https://github.com/alberthdev/docker-win10-dev/blob/master/Dockerfile

Hope this helps!

**Comment by JackBoosY** [comment]
Should be a vcpkg bug with permission or path.

**Comment by PhoebeHui** [comment]
I noticed that it point to new directory via VCPKG_DOWNLOADS in our pipeline run, see  https://github.com/microsoft/vcpkg/blob/master/scripts/azure-pipelines/azure-pipelines.yml#L18, may be you can try this as a workaround.

For further investigation, could you pass '--debug' option to './vcpkg install', it seems that failed to create downloads folder by some reason?

```
2021-06-06T06:27:25.4375126Z Start Env Check
2021-06-06T06:27:25.4377180Z == Print version
2021-06-06T06:27:25.4538787Z git version 2.31.1.windows.1
2021-06-06T06:27:25.4575057Z == Run tree
2021-06-06T06:27:25.4640572Z Folder PATH listing for volume Temporary Storage
2021-06-06T06:27:25.4641500Z Volume serial number is F021-C7E5
2021-06-06T06:27:25.4643249Z D:\A\GITHUB-ACTIONS-TEST\GITHUB-ACTIONS-TEST\VCPKG\DOWNLOADS
2021-06-06T06:27:25.4644537Z Invalid path - \A\GITHUB-ACTIONS-TEST\GITHUB-ACTIONS-TEST\VCPKG\DOWNLOADS
2021-06-06T06:27:25.4645299Z No subfolders exist 
2021-06-06T06:27:25.4645661Z 
2021-06-06T06:27:25.4652415Z == cd into dir
2021-06-06T06:27:25.4658931Z The system cannot find the path specified.
2021-06-06T06:27:25.4659586Z cd failed
2021-06-06T06:27:25.4661386Z == Attempt to git init
2021-06-06T06:27:25.4889402Z Initialized empty Git repository in D:/a/github-actions-test/github-actions-test/git-tmp/.git/
2021-06-06T06:27:25.4928490Z End GitHub Actions Environment Check
```

**Comment by alberthdev** [comment]
Reran in a fresh Docker environment, with the --debug option:

[vcpkg.docker.failure.20210616.debug.log.txt](https://github.com/microsoft/vcpkg/files/6662807/vcpkg.docker.failure.20210616.debug.log.txt)

I believe we're hitting a corner case where all of the required tools are already installed, so it never gets to the case where it would need to create the downloads directory.

**Comment by mcmtroffaes** [comment]
I've seen this also with libssh. Job without vcpkg/downloads (broken):

https://ci.appveyor.com/project/mcmtroffaes/ffmpeg-msvc-build/builds/39604214/job/bdsfn4vx34f58d26#L95

Job with vcpkg/downloads (fixed):

https://ci.appveyor.com/project/mcmtroffaes/ffmpeg-msvc-build/builds/39629978/job/2e28ivhaekgq8r1x?fullLog=true#L96

**Comment by PhoebeHui** [comment]
It looks a vcpkg bug, @ras0219 @ras0219-msft, could you please help have a look?

**Comment by PhoebeHui** [comment]
@alberthdev, the fix has been merged, please get latest source and try again.
