### ISSUE TITLE
Picking up dependencies

### ISSUE THREAD

**Issue by ZeroCrunch** [Microsoft/vcpkg#183]
I'm trying to build OpenImageIO (https://github.com/OpenImageIO/oiio).

It has many dependencies, some of which are already included in vcpkg, such as tiff.

How can I point this dependency to the portfile.cmake for OpenImageIO.

I did search the Issues already but didn't see anything, so apologies if its' already been covered.

Thanks.

**Comment by barcharcraz** [comment]
You should use find_package. And the portfile should run with the cmake prefix set correctly.

**Comment by ras0219-msft** [comment]
Since they use CMake, it should be as easy as building the project while following our CMake instructions here:
https://github.com/Microsoft/vcpkg/blob/master/docs/EXAMPLES.md#example-1-2-b.

Let us know if you have any issues!
