### ISSUE TITLE
VSCode no longer found

### ISSUE THREAD

**Issue by ShinNoNoir** [Microsoft/vcpkg#1830]
`vcpkg` can no longer find VSCode. I suspect the following commit broke this functionality: https://github.com/Microsoft/vcpkg/commit/6363910319a082512179269fb6329ecbc367b3bc (see line 36 and 37).

**Comment by alexkaratarakis** [comment]
Sorry about that!
Fixed with b08f2a02e73721cc63acecccc2c25f2c0f488d45.
