### ISSUE TITLE
VCPKG update failure on windows

### ISSUE THREAD

**Issue by aPSopt** [microsoft/vcpkg#18307]
**Host Environment**
- OS: Win10 latest
- Compiler: msvs latest

Today I update vcpkg repo from github and do:
`vcpkg update`

And see the followed error:

> Error: while loading forest:
> The port directory (D:\vcpkg\ports\forest) does not exist
> Error: failed to load port from D:\vcpkg\ports\forest
> Note: Updating vcpkg by rerunning bootstrap-vcpkg may resolve this failure.

**Comment by JackBoosY** [comment]
`forest` was deleted by PR https://github.com/microsoft/vcpkg/pull/16836.
I think you should run `git pull` first then `bootstrap-vcpkg` second.

**Comment by aPSopt** [comment]
> `forest` was deleted by PR #16836.
> I think you should run `git pull` first then `bootstrap-vcpkg` second.

I exactly did this. or... are you mean I should pull clean vcpkg? I trying to avoid it because to much time will need for recompilation

**Comment by autoantwort** [comment]
The problem is that you are trying to install a package that does not exists

**Comment by aPSopt** [comment]
No, if you look at the initial message - I dont install package, I just do 
`vcpkg update`

**Comment by autoantwort** [comment]
Sorry, to fix the problem you can properly do a `vcpkg remove forest`, because it seems to be currently installed and updating is not possible because it is gone. But yeah, a bug

**Comment by aPSopt** [comment]
Yes, your solution (delete forest) is fix the problem, thx!
