### ISSUE TITLE
[New Port Request] cucumber-cpp

### ISSUE THREAD

**Issue by andrusenko-ag** [microsoft/vcpkg#18304]
Please add this one to vcpkg

Library name:
cucumber-cpp

Source repository URL:
https://github.com/cucumber/cucumber-cpp

**Comment by andrusenko-ag** [comment]
Hi there. Just wondering, how long does it usually take to add new a port into vcpkg. I see that some requests are hanging for years. Is it feasible to add cucumber to vcpkg, in the nearest future or I should not wait for that?)

**Comment by PhoebeHui** [comment]
We're happy to answer any questions we can to support this effort, but for now we'd prefer to support you or other contributors than to take ownership ourselves. None of our core team is very familiar with cucumber-cpp, so we feel you'll do a much better job than we could! please considering to make a PR for this.
