### ISSUE TITLE
vcpkg and c++ modules

### ISSUE THREAD

**Issue by mateka** [microsoft/vcpkg#1832]
Is there a recomended way of using experimental c++ modules in Visual Studo 2017 and vcpkg? When I had turned on user wide integration, example program with modules from https://blogs.msdn.microsoft.com/vcblog/2017/05/05/cpp-modules-in-visual-studio-2017/ will not compile because of linker errors.

**Comment by NancyLi1013** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen.

**Comment by NickStrupat** [comment]
https://github.com/microsoft/vcpkg/issues/13696
