### ISSUE TITLE
How do I use Gtkmm4.0

### ISSUE THREAD

**Issue by nlogozzo** [microsoft/vcpkg#18328]
I installed Gtkmm4.0 via vcpkg using `vcpkg install gtkmm`. My triplet is `x86-windows` btw.
Now I'm following the documentation for gtkmm to create a simple application.

```cpp
#include <gtkmm-4.0/gtkmm.h>

int main(int argc, char* argv[])
{
	auto app = Gtk::Application::create("org.nickvision.application");
	//app->make_window_and_run<MainWindow>(argc, argv);
}
```
I get an error saying Gtk is not a namespace.

So then I try to include application.h instead: `#include <gtkmm-4.0/gtkmm/application.h>`
However, then I get the error saying Application is not a class name. I don't know what's going on and why it won't work. It sees all the headers...

**Comment by nlogozzo** [comment]
When including `#include <gtkmm-4.0/gtkmm/application.h>` I get the build error
`1>D:\src\vcpkg\installed\x86-windows\include\gtkmm-4.0\gtkmm\application.h(5,10): fatal error C1083: Cannot open include file: 'gtkmmconfig.h': No such file or directory`

**Comment by nlogozzo** [comment]
When including `#include <gtkmm-4.0/gtkmm.h>` I get the build error
`1>D:\src\vcpkg\installed\x86-windows\include\gtkmm-4.0\gtkmm.h(100,10): fatal error C1083: Cannot open include file: 'glibmm.h': No such file or directory`

**Comment by nlogozzo** [comment]
@NancyLi1013 any idea?

**Comment by dg0yt** [comment]
What is the usage information printed by `vcpkg install gtkmm` (if any)?

**Comment by nlogozzo** [comment]
I don't remember. But it seemed to have installed fine, like I said all the files are there just the names don't match what it expects. Should I try to uninstall it and reinstall it?

**Comment by nlogozzo** [comment]
I removed the package and reinstalled it. This was the output
```
Computing installation plan...
The following packages will be built and installed:
    gtkmm[core]:x86-windows -> 4.0.1
Detecting compiler hash for triplet x86-windows...
Could not locate cached archive: C:\Users\nlogo\AppData\Local\vcpkg\archives\d1\d1d3abec1aa5632b5ef98683dde406635c8968d3.zip
Starting package 1/1: gtkmm:x86-windows
Building package gtkmm[core]:x86-windows...
-- Downloading https://ftp.gnome.org/pub/GNOME/sources/gtkmm/4.0/gtkmm-4.0.1.tar.xz -> gtkmm-4.0.1.tar.xz...
-- Extracting source D:/src/vcpkg/downloads/gtkmm-4.0.1.tar.xz
-- Using source at D:/src/vcpkg/buildtrees/gtkmm/src/gtkmm-4-33024a6c22.clean
-- Found external ninja('1.10.2').
-- Configuring x86-windows
-- Downloading https://www.python.org/ftp/python/3.9.5/python-3.9.5-embed-win32.zip -> python-3.9.5-embed-win32.zip...
-- Downloading https://github.com/mesonbuild/meson/archive/753954be868ed78b3e339e8811fd1d29eb2af237.tar.gz -> meson-753954be868ed78b3e339e8811fd1d29eb2af237.tar.gz...
-- Using msys root at D:/src/vcpkg/downloads/tools/msys2/aa5af7b2aa7e90e8
-- Configuring x86-windows-dbg
-- Configuring x86-windows-dbg done
-- Configuring x86-windows-rel
-- Configuring x86-windows-rel done
-- Package x86-windows-dbg
-- Package x86-windows-rel
-- Using msys root at D:/src/vcpkg/downloads/tools/msys2/aa5af7b2aa7e90e8
-- Fixing pkgconfig file: D:/src/vcpkg/packages/gtkmm_x86-windows/lib/pkgconfig/gtkmm-4.0.pc
-- Fixing pkgconfig file: D:/src/vcpkg/packages/gtkmm_x86-windows/debug/lib/pkgconfig/gtkmm-4.0.pc
-- Installing: D:/src/vcpkg/packages/gtkmm_x86-windows/share/gtkmm/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\nlogo\AppData\Local\vcpkg\archives\d1\d1d3abec1aa5632b5ef98683dde406635c8968d3.zip
Building package gtkmm[core]:x86-windows... done
Installing package gtkmm[core]:x86-windows...
Installing package gtkmm[core]:x86-windows... done
Elapsed time for package gtkmm:x86-windows: 2.637 min
```

**Comment by dg0yt** [comment]
I didn't expect that the issue would go away. I just tried to understand where you take the include directory from. I suppose you should add something like `include\gtkmm-4.0\gtkmm` to your include path, and then use `include <gtkmm.h>`.

**Comment by nlogozzo** [comment]
I did that. However, gtkmm.h requires gdkmm.h so I have to include that folder, and then a bunch of other dependencies that gtkmm requires and I'm trying to find them all but it's not working out.

**Comment by dg0yt** [comment]
In general, these transitive dependencies can be resolved via pkg-config (pc files) or CMake config files. 
I see `lib/pkgconfig/gtkmm-4.0.pc` in the log above.  From CMake, you can access this information via the functions provided by [FindPkgConfig](https://cmake.org/cmake/help/latest/module/FindPkgConfig.html), but it needs a `pkg-config` executable. (vcpkg downloads one for some maintainer functions, but it doesn't yet offer a proper port.)

**Comment by nlogozzo** [comment]
I'm confused...so what do I have to do to get it working in VS2019? @dg0yt Like do i have to edit a file or something?

**Comment by Neumann-A** [comment]
The pure MSBuild integration is broken in this case since it is too simple and cannot reflect the correct usage of gtkmm. This also applies to other ports like Qt. As soon as include dirs other than `/include` come into play you are basically lost. My advice is to use CMake (or Meson if you don't like CMake).

**Comment by nlogozzo** [comment]
@Neumann-A Is there a way I can get CMake with vcpkg setup on VS2019

**Comment by nlogozzo** [comment]
I'm also getting this error
```
CMake Error at D:/src/vcpkg/scripts/buildsystems/vcpkg.cmake:772 (_find_package):
  By not providing "Findgtkmm-4.0.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "gtkmm-4.0", but CMake did not find one.

  Could not find a package configuration file provided by "gtkmm-4.0" with
  any of the following names:

    gtkmm-4.0Config.cmake
    gtkmm-4.0-config.cmake

  Add the installation prefix of "gtkmm-4.0" to CMAKE_PREFIX_PATH or set
  "gtkmm-4.0_DIR" to a directory containing one of the above files.  If
  "gtkmm-4.0" provides a separate development package or SDK, be sure it has
  been installed.        D:/src/vcpkg/scripts/buildsystems/vcpkg.cmake    772  
  ```
  @Neumann-A @dg0yt

**Comment by Neumann-A** [comment]
```
find_package(PkgConfig)
pkg_check_modules(GTKMM_VARS REQUIRED IMPORTED_TARGET gtkmm-4.0)

target_link_libraries(<your_target> PRIVATE PkgConfig::GTKMM_VARS)
```

If `PKG_CONFIG_EXECUTABLE` is missing install the port pkgconf and set `PKG_CONFIG_EXECUTABLE` to the absolute path of `pkgconf.exe`  or use the pkg-config executable vcpkg internally uses

**Comment by nlogozzo** [comment]
Where do i put these lines of code? In my main.cpp?
Like i said i don't have a CMake file in my project cause its just a blank solution and VS handles the magic. @Neumann-A

**Comment by Neumann-A** [comment]
> Where do i put these lines of code? In my main.cpp?

No in your `CMakeLists.txt` which you obviously have since you wouldn't have the error in https://github.com/microsoft/vcpkg/issues/18328#issuecomment-857176389 otherwise

**Comment by nlogozzo** [comment]
@Neumann-A there no cmakelist.txt file in my project. I'd have to add it to the overall vcpkg cmakelist that's provided by the tool chain, which will then import gtkmm in every project no?

**Comment by Pr0curo** [comment]
if you decide to go the cmake route, I made a minimal working example for your information (and my forgetful brain), please take a look at [the example](https://github.com/Pr0curo/gtkmm-4.0-simple-example) -- maybe this helps you.

**Comment by nlogozzo** [comment]
@Pr0curo Thank you for the example! That's definitely what I needed to get started. However, I decided to go with WinUI 3 instead. But thank you again. I feel good enough closing the issue having your example to give people as a reference!

**Comment by MidwestB** [comment]
Hello, I was having the exact same issues as nlogozzo but am still trying to work with gtkmm.  Following Neumann-A's suggestions, I set PKG_CONFIG_EXECUTABLE to the absolute path of pkgconf.exe (I used the pkgconf port of vcpkg) as a variable in my project's CMakeSettings.json.  I have copied the CMakeLists.txt of Pr0curo's example and my project actually compiles now!  However, I now get linker errors and I'm not sure how to fix them.

The error I am getting is:
```
>------ Build All started: Project: HelloGTK, Configuration: x64-Debug ------
  Microsoft (R) Build Engine version 16.11.0+0538acc04 for .NET Framework
  Copyright (C) Microsoft Corporation. All rights reserved.
  
D:\DDesktop\Programming\HelloGTK\HelloGTK\out\build\x64-Debug\LINK : fatal error LNK1104: cannot open file 'ffi.lib' 

Build All failed.
```

Being a continuation of the same problem, I thought I should post here.  If I should instead open a new issue, please let me know.  Any help is appreciated!

**Comment by Neumann-A** [comment]
>  cannot open file 'ffi.lib' 

that is because libffi's pc file is wrong. It links -lffi on windows which is wrong (it needs to be -llibffi).
You can manually adjust libffi.pc or provide a fix for it which replaces `VCPKG_TARGET_IS_MINGW` with `VCPKG_TARGET_IS_WINDOWS`

**Comment by MidwestB** [comment]
It worked!  Thank you so much for the help!

I manually changed -lffi to -llibffi in the libffi.pc files at `C:\dev\vcpkg\installed\x64-windows\lib\pkgconfig` and `C:\dev\vcpkg\installed\x64-windows\debug\lib\pkgconfig` and that got it to work.  

I then found that `VCPKG_TARGET_IS_MINGW` was specified in the libffi portfile in `C:\dev\vcpkg\ports\libffi` and changed it to `VCPKG_TARGET_IS_WINDOWS`.  I reinstalled libffi and it seemed to work, so I submitted the change as a pull request.  Hopefully that's alright.

Now I can work with gtkmm, thanks again!
