### ISSUE TITLE
[New Port Request]  discordpp

### ISSUE THREAD

**Issue by nlogozzo** [microsoft/vcpkg#18321]
Library name: discordpp

Library description: A Modularized C++ Library for the Discord API

Source repository URL: https://github.com/DiscordPP/discordpp

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
Required dependencies are on source repository readme page. Optional plugins on page would be welcomed as well.

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
