### ISSUE TITLE
[New Port Request] sleepy-discord

### ISSUE THREAD

**Issue by nlogozzo** [microsoft/vcpkg#18322]
Library name: sleepy-discord

Library description: C++ library for the Discord chat client

Source repository URL: https://github.com/yourWaifu/sleepy-discord

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
- OpenSSL
- cpr
- Websocket++ or uWebSockets
(Also offers a development branch if you would like to include a sleepy-discord-dev package)

**Comment by autoantwort** [comment]
See #17604

**Comment by autoantwort** [comment]
duplicate of #14065

**Comment by JonLiu1993** [comment]
duplicate of #14065
