### ISSUE TITLE
[vcpkg-tool] Canonicalization Question

### ISSUE THREAD

**Issue by strega-nil-ms** [microsoft/vcpkg#18326]
We have had problems in the past with our "canonicalize everything" choice. We need to have a discussion about whether it works to do simple case-canonicalization, in order to keep substs, junctions, and soft links in all of the paths we use; this allows people to build packages with long paths, for example. Additionally, we've had issues with `canonical` not working in Docker, which this would fix.

**Comment by BillyONeal** [comment]
Proposed changes:

* Change canonical in vcpkg-tool to fixup path case + absolute + lexically_normal instead
* Change windows test fleet to run in a subst environment
* Check macos for unicode normalization edge cases

**Comment by BillyONeal** [comment]
We stopped canonicalizing everything a while ago because it made working around long path issues more difficult.
