### ISSUE TITLE
--disable-metrics causes bootstrap-vcpkg to throw

### ISSUE THREAD

**Issue by DrDevinRX** [microsoft/vcpkg#18324]
**Describe the bug**

Using the bootstrap-vcpkg.bat with --disable-metrics causes the powershell script to throw.

```
C:\vcpkg>bootstrap-vcpkg.bat --disable-metrics
Only named parameters are allowed.
At C:\vcpkg\scripts\bootstrap.ps1:19 char:9
+         throw "Only named parameters are allowed."
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Only named parameters are allowed.:String) [], RuntimeException
    + FullyQualifiedErrorId : Only named parameters are allowed.
```

**Environment**
- OS: Windows 10 Version 10.0.19042.985

**To Reproduce**
1. Run bootstrap-vcpkg.bat --disable-metrics

**Expected behavior**
bootstrap-vcpkg runs successfully and disables metrics

**Comment by DrDevinRX** [comment]
I should note running `bootstrap-vcpkg.bat` without any parameters works correctly

**Comment by strega-nil-ms** [comment]
The correct flag is `-disableMetrics` :)

**Comment by codeling** [comment]
That there are two different ways of specifying the parameter, one for vcpkg and one for boostrap-vcpkg, definitely has the potential to confuse!
