### ISSUE TITLE
win10 install curl failed

### ISSUE THREAD

**Issue by zieckey** [Microsoft/vcpkg#1833]
ENV：

1. vcpkg version eb0591597e4cb93ddc94f5b738dd5f519bffc529
2. Windows 10 professional, simplified Chinese locale, 10.0.14393
3. cmake: 3.9.2 c:/Program Files/CMake/
4. git version 2.14.1.windows.1
5. Microsoft Visual Studio Community 2017 15.3.4 VisualStudio.15.Release/15.3.4+26730.15

I have successfully installed :

```shell
D:\git\vcpkg>vcpkg.exe list
gflags[core]:x86-windows       2.2.0-5          A C++ library that implements commandline flags processing
glog[core]:x86-windows         0.3.5-1          C++ implementation of the Google logging module
libevent[core]:x86-windows     2.1.8-3          An event notification library
libssh2[core]:x86-windows      1.8.0-2          The SSH library
openssl[core]:x86-windows      1.0.2l-2         OpenSSL is an open source project that provides a robust, commercial...
zlib[core]:x86-windows         1.2.11-1         A compression library
```

But I try to install curl failed:

```shell
D:\git\vcpkg>vcpkg.exe install curl
The following packages will be built and installed:
    curl:x86-windows
Starting package 1/1: curl:x86-windows
Building package curl:x86-windows...
-- CURRENT_INSTALLED_DIR=D:/git/vcpkg/installed/x86-windows
-- DOWNLOADS=D:/git/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=D:/git/vcpkg/packages/curl_x86-windows
-- CURRENT_BUILDTREES_DIR=D:/git/vcpkg/buildtrees/curl
-- CURRENT_PORT_DIR=D:/git/vcpkg/ports/curl/.
-- Using cached D:/git/vcpkg/downloads/curl-curl-curl-7_55_1.tar.gz
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Applying patch D:/git/vcpkg/ports/curl/0001_cmake.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch D:/git/vcpkg/ports/curl/0001_cmake.patch done
-- Applying patch D:/git/vcpkg/ports/curl/0002_fix_uwp.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch D:/git/vcpkg/ports/curl/0002_fix_uwp.patch done
-- Configuring x86-windows-rel
-- Configuring x86-windows-rel done
-- Configuring x86-windows-dbg
-- Configuring x86-windows-dbg done
-- Package x86-windows-rel
CMake Error at D:/git/vcpkg/scripts/cmake/vcpkg_execute_required_process.cmake:43 (message):
    Command failed: C:/Program Files/CMake/bin/cmake.exe;--build;.;--config;Release;--target;install;--;-v
    Working Directory: D:/git/vcpkg/buildtrees/curl/x86-windows-rel
    See logs for more information:
      D:\git\vcpkg\buildtrees\curl\package-x86-windows-rel-out.log
      D:\git\vcpkg\buildtrees\curl\package-x86-windows-rel-err.log

Call Stack (most recent call first):
  D:/git/vcpkg/scripts/cmake/vcpkg_install_cmake.cmake:49 (vcpkg_execute_required_process)
  D:/git/vcpkg/ports/curl/portfile.cmake:51 (vcpkg_install_cmake)
  D:/git/vcpkg/scripts/ports.cmake:72 (include)


Error: Building package curl:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: curl:x86-windows
  Vcpkg version: 0.0.89-2017-09-14-eb0591597e4cb93ddc94f5b738dd5f519bffc529

Additionally, attach any relevant sections from the log files above.
```

The content of the log file `D:\git\vcpkg\buildtrees\curl\config-x86-windows-rel-err.log` is :

```
CMake Warning at CMakeLists.txt:49 (message):
  the curl cmake build system is poorly maintained.  Be aware


CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_CXX_FLAGS
    CMAKE_CXX_FLAGS_RELEASE
```

Thanks.

**Comment by wfeii1980** [comment]
`[34/38] "D:/Program Files/CMake/bin/cmcldeps.exe" RC D:\vcpkg-master\buildtrees\zlib\src\zlib-1.2.11\win32\zlib1.rc "CMakeFiles\zlib.dir\win32\zlib1.res.d" CMakeFiles\zlib.dir\win32\zlib1.res "עӢ: Ѽڬτݾ:  " "D:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_x86/cl.exe" C:\PROGRA~2\WI3CF2~1\8.1\bin\x64\rc.exe -DNO_FSEEKO -DZLIB_DLL -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_SECURE_NO_DEPRECATE -ID:\vcpkg-master\buildtrees\zlib\src\zlib-1.2.11 -ID:\vcpkg-master\buildtrees\zlib\x86-windows-static-rel /DWIN32 /foCMakeFiles\zlib.dir\win32\zlib1.res D:\vcpkg-master\buildtrees\zlib\src\zlib-1.2.11\win32\zlib1.rc
FAILED: CMakeFiles/zlib.dir/win32/zlib1.res 
"D:/Program Files/CMake/bin/cmcldeps.exe" RC D:\vcpkg-master\buildtrees\zlib\src\zlib-1.2.11\win32\zlib1.rc "CMakeFiles\zlib.dir\win32\zlib1.res.d" CMakeFiles\zlib.dir\win32\zlib1.res "עӢ: Ѽڬτݾ:  " "D:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_x86/cl.exe" C:\PROGRA~2\WI3CF2~1\8.1\bin\x64\rc.exe -DNO_FSEEKO -DZLIB_DLL -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_SECURE_NO_DEPRECATE -ID:\vcpkg-master\buildtrees\zlib\src\zlib-1.2.11 -ID:\vcpkg-master\buildtrees\zlib\x86-windows-static-rel /DWIN32 /foCMakeFiles\zlib.dir\win32\zlib1.res D:\vcpkg-master\buildtrees\zlib\src\zlib-1.2.11\win32\zlib1.rc
cl: 命令行 warning D9035 :cl: 命令行 error D8000 :cl: 命令行 error D8000 :cl: 命令行 error D8000 :cl: 命令行 error D8000 :cl: 命令行 error D8000 :cl: 命令行 error D8000 :cl: 命令行 error D8000 :cl: 命令行 error D8000 :cl: 命令行 error D8000 :cl: 命令行 error D8000 :cl: 命令行 error D8000 :cl: 命令行 error D8000 :cl: 命令行 error D8000 :cl: 命令行 error D8000 :cl: 命令行 error D8000 :cl: 命令行 error D8000 :cl: 命令行 error D8000 :cl: 命令行 error D8000 :cl: 命令行 error D8000 :cl: 命令行 error D8000 :cl: 命令行 error D8000 :cl: 命令行 error D8000 :cl: 命令行 error D8000 :cl: 命令行 error D8000 :cl: 命令行 error D8000 :cl: 命令行 error D8000 :cl: 命令行 error D8000 :cl: 命令行 error D8000 :cl: 命令行 error D8000 :D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64_x86\cl.exe 中有内部编译器错误。系统将会提示你稍后向 Microsoft 发送错误报告。`

"עӢ: Ѽڬτݾ:  " = ANSI"注意: 包含文件: " = en"Note: include files: "

zlib curl ... "similar issue"

**Comment by JonnyPtn** [comment]
@zieckey You've uploaded the wrong output file:     

```
See logs for more information:
      D:\git\vcpkg\buildtrees\curl\package-x86-windows-rel-out.log
      D:\git\vcpkg\buildtrees\curl\package-x86-windows-rel-err.log
```

> The content of the log file D:\git\vcpkg\buildtrees\curl\config-x86-windows-rel-err.log is :

**Comment by prudens** [comment]
@wfeii1980 I have a similar error log file when intalled zlib or curl ,my solution is modify the vs language from Chinese to English. Maybe it would help you.

**Comment by zieckey** [comment]
@prudens 'my solution is modify the vs language from Chinese to English' it works. Thanks.

**Comment by hellowilman** [comment]
I encounter similar 
`$ ./vcpkg install curl
The following packages will be built and installed:
    curl[core,ssl,winssl]:x86-windows
  * zlib[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/2: zlib:x86-windows
Building package zlib[core]:x86-windows...
A suitable version of cmake was not found (required v3.12.4). Downloading portable cmake v3.12.4...
Downloading cmake...
  https://github.com/Kitware/CMake/releases/download/v3.12.4/cmake-3.12.4-win32-x86.zip -> E:\WilmanWork\dev\vcpkg\downloads\cmake-3.12.4-win32-x86.zip
Extracting cmake...
A suitable version of 7zip was not found (required v18.1.0). Downloading portable 7zip v18.1.0...
Downloading 7zip...
  https://www.nuget.org/api/v2/package/7-Zip.CommandLine/18.1.0 -> E:\WilmanWork\dev\vcpkg\downloads\7-zip.commandline.18.1.0.nupkg
Extracting 7zip...
A suitable version of nuget was not found (required v4.6.2). Downloading portable nuget v4.6.2...
Downloading nuget...
  https://dist.nuget.org/win-x86-commandline/v4.6.2/nuget.exe -> E:\WilmanWork\dev\vcpkg\downloads\nuget.exe
A suitable version of git was not found (required v2.20.0). Downloading portable git v2.20.0...
Downloading git...
  https://github.com/git-for-windows/git/releases/download/v2.20.0.windows.1/PortableGit-2.20.0-32-bit.7z.exe -> E:\WilmanWork\dev\vcpkg\downloads\PortableGit-2.20.0-32-bit.7z.exe
Extracting git...
-- Downloading http://www.zlib.net/zlib-1.2.11.tar.gz...
-- Extracting source E:/WilmanWork/dev/vcpkg/downloads/zlib1211.tar.gz
-- Applying patch E:/WilmanWork/dev/vcpkg/ports/zlib/cmake_dont_build_more_than_needed.patch
-- Downloading https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip...
-- Downloading https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip... Failed. Status: 7;"Couldn't connect to server"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:156 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_find_acquire_program.cmake:248 (vcpkg_download_distfile)
  scripts/cmake/vcpkg_configure_cmake.cmake:121 (vcpkg_find_acquire_program)
  ports/zlib/portfile.cmake:19 (vcpkg_configure_cmake)
  scripts/ports.cmake:71 (include)


Error: Building package zlib:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zlib:x86-windows
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.
`

**Comment by JackBoosY** [comment]
Hi @zieckey , thanks for reporting this issue!
The latest version of curl was built successfully on my machine. Plz update vcpkg and try again.
Please open a new issue if this is still a problem for you.
Thx.

**Comment by whidbey** [comment]
same error.. also with boost
I guess it's chinese system problem?

**Comment by JackBoosY** [comment]
@whidbey noop, I've test boost with win10_zh-CN, built success. Could you open a new issue?
