### ISSUE TITLE
[mpfr] build failure if mpir is previously installed

### ISSUE THREAD

**Issue by melhashash** [microsoft/vcpkg#18339]
I can't install mpir and mpfr together in Windows due to conflict with gmp

**Host Environment**
- OS: Windows
- Compiler: VS2017

**To Reproduce**
`./vcpkg install mpfr:x64-windows`

**Failure logs** 
Starting package 1/2: gmp:x64-windows
Building package gmp[core]:x64-windows...
Building package gmp[core]:x64-windows... done
Installing package gmp[core]:x64-windows...
The following files are already installed in /vcpkg/installed/x64-windows and are in conflict with gmp:x64-windows

Installed by mpir:x64-windows
    include/gmp.h
    include/gmpxx.h

Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: gmp:x64-windows
  Vcpkg version: 2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9

**Comment by JackBoosY** [comment]
`mpir` conflict with `gmp`, so you need to remove mpir first.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

**Comment by kuandeng** [comment]
> `mpir` conflict with `gmp`, so you need to remove mpir first.

Is there any way to install both mpir and mpfr？

**Comment by JackBoosY** [comment]
> > `mpir` conflict with `gmp`, so you need to remove mpir first.
> 
> Is there any way to install both mpir and mpfr？

Currently, no.
