### ISSUE TITLE
Vcpkg Configuration option in IDE doesn't work in VS2015 u3 (works in VS 2019)

### ISSUE THREAD

**Issue by ocornut** [microsoft/vcpkg#18337]
**Describe the bug**

In Visual Studio 2015 if I alter the "vcpkg configuration" setting to have Debug build use Release libraries:

![image](https://user-images.githubusercontent.com/8225057/121201689-ff4e1180-c874-11eb-8464-1aac48fd8361.png)

vcpkg still uses the Debug libraries.
One way to visualize that is that even though the $(VcpkgConfiguration) variable has been changed to "Release", the $(VcPkgConfigSubDir) and $(VcpkgNormalizedConfiguration) variables stills says "Debug".

![image](https://user-images.githubusercontent.com/8225057/121201948-358b9100-c875-11eb-8434-45961007373c.png)

Whereas in Visual Studio 2019 that settings works.

![image](https://user-images.githubusercontent.com/8225057/121202251-71265b00-c875-11eb-8883-d1230f082062.png)

(doesn't seem to have a $(VcPkgConfigSubDir) variable, and paths are not visible in properties I guess auto-link works differently between VS 2015 and VS 2019, but the bottom line is that it works and pulls the release versions of the librairies even though the project is in "debug" mode).

![image](https://user-images.githubusercontent.com/8225057/121202919-f90c6500-c875-11eb-816a-3d25f5b8f4bf.png)

**Environment**
- OS: Windows
- Compiler: 
Microsoft Visual Studio Community 2015 / Version 14.0.25431.01 Update 3
and
Microsoft Visual Studio Community 2019 / Version 16.9.4 / VisualStudio.16.Release/16.9.4+31205.134

**To Reproduce**
1. ./vcpkg install integrate
2. Create a VS2015 project
3. Confirm that vcpkg integration works
4. In a Debug target, try to alter $(VcpkgConfiguration) and select Release.
5. Confirm that Debug librairies are still used and linked.

**Comment by NancyLi1013** [comment]
Hi @ocornut 

Thanks for posting this issue.

Have you tried with the latest vcpkg? Does this still exist?

**Comment by NancyLi1013** [comment]
Confirmed, this issue also exists on Visual Studio 2015.

@strega-nil-ms could you please help take a look?

**Comment by ocornut** [comment]
> Have you tried with the latest vcpkg? Does this still exist?

Apologies @NancyLi1013 for my late answer. 
When I made the report my .exe said `2021-01-13-unknownhash` and git repo was January 29. I have now updated, .exe says `2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9` and git repo is June 18 08214e18eeb146542944067c35d77faca8962be5. I confirmed the same issue with that version now.

Thank you!

**Comment by autoantwort** [comment]
You can workaround this issue by adding the `vcpkg.targets` file as a property sheet.

**Comment by autoantwort** [comment]
This can be closed. It will never work because VS 2015 is kind of broken.
