### ISSUE TITLE
Help with problem: install custom port seems to hang at end of build step, no apparent reason

### ISSUE THREAD

**Issue by bt-ncarroll** [microsoft/vcpkg#18341]
**Describe the bug**
I have a custom port for a third-party library, the version of which I am trying to update. The previous version built correctly with the port. The new version _appears_ to build correctly (ie: output is correct, is built when manually built from the files under buildtrees, .log file shows build completion, no excess build processes outstanding, etc.), but vcpkg is not proceeding to copying files to their destination locations, or complete the install process.

**Environment**
- OS: Windows 10 build 19041
- Compiler: 19.10.1

**To Reproduce**
1. ./vcpkg install [custom port]
2. Build appears to succeed, but vcpkg.exe seems to hang after build and before file organization step(s).

**Expected behavior**
For it to work? Really, just any clue why this would be happening, or advice for how to proceed, where to look, etc.

**Failure logs** 
No failures in logs; builds appear to succeed from logs.

**Additional context**
- Using vcpkg_install_msbuild as the build command
- At the point of hang, vcpkg.exe has no child processes; that is, everything related to the build has finished.
- I can manually build the project in the buildtree without issue
- For whatever it might be worth, Process Explorer seems to show vcpkg.exe in the hung state having a handle to a non-existent process, and is still holding the build log open.

Please help with whatever info/advice possible.

**Comment by JackBoosY** [comment]
Please run command `./vcpkg install port --debug` then provide the ouput.

Thanks.

**Comment by bt-ncarroll** [comment]
[install_debug.txt](https://github.com/microsoft/vcpkg/files/6625858/install_debug.txt)

I cannot see anything indicative; this is the entire file generated until manually terminating the seemingly hung process (after letting it sit for ~20 minutes).

**Comment by bt-ncarroll** [comment]
FWIW, I have also confirmed that the build of the previous version of the library, using the same port file and local setup (ie: same OS, vcpkg.exe, etc.) still works, so it's something specific to this build. Also, the build-x86-windows-rel-out.log and build-x86-windows-dbg-out.log files in the build tree look effectively identical between versions (specific build output notwithstanding). The only difference I can observe is that in the successful install, stdout-x86-windows.log has content, whereas in the hang scenario, it is blank (although Process Explorer shows an open handle to that file when vcpkg.exe is in the hung state).

Let me know what else I can look at.

**Comment by JackBoosY** [comment]
Stuck on cmake.exe, maybe related to https://github.com/microsoft/vcpkg/issues/10884.

**Comment by bt-ncarroll** [comment]
There are a number of agents running on the system (which I cannot disable), but I can confirm that:
- The system is not going to sleep
- Other libraries build correctly, including the previous version of the same library with the same port file (this is the only time I have observed this issue)

Also note that, in all the cases I have tried to look at, vcpkg.exe has an open handle to a process (and thread within that process) which are terminated. I don't know how it works internally, but that seems like the most potentially actionable clue to me...

**Comment by bt-ncarroll** [comment]
Another interesting data point, from further experimentation:

If I do a `vcpkg.exe build [port]`, followed by `vcpkg.exe install [port]`, that succeeds. It's strange, but maybe that helps diagnose? It should be sufficient for a workaround for now, but still a bizarre issue...

**Comment by bt-ncarroll** [comment]
Although now I get `Value was null` running `vcpkg.exe build [anything]`, so perhaps that's not a good workaround in general.

**Comment by bt-ncarroll** [comment]
No, spoke too soon; just got the hang with `vcpkg.exe build [port]`, same symptoms. So it seems to be somewhat intermittent and/or timing based, perhaps?

**Comment by bt-ncarroll** [comment]
Also, fwiw, it appears the orphaned process/thread handles within the vcpkg.exe is to cmake.exe (which has terminated). Don't know if that helps diagnose at all, but that appears to be the case.

**Comment by bt-ncarroll** [comment]
I've been debugging a little; vcpkg.exe appears to be hanging in ReadFile (system.process.cpp, around 512).

I do not have any idea why this would be the case, especially for this specific project/build, and/or what's causing it, but that's the line which is apparently causing the process to hang.

**Comment by JackBoosY** [comment]
@bt-ncarroll Looks like a permission issue.
@strega-nil-ms Do you have any ideas?

**Comment by bt-ncarroll** [comment]
I have a bit more info, from debugging and experimental code in vcpkg.exe:

It appears that the issue is happening within cmake.exe, and is causing ReadFile on the pipe to fail. Also, cmake.exe is returning an error code after it's operation: 0xc0000409

This is the test code I wrote to try to identify the issue, within system.process.cpp:
```c++
    struct ProcessInfoAndPipes
    {
        ProcessInfo proc_info;
        HANDLE child_stdin = 0;
        HANDLE child_stdout = 0;

        template<class Function>
        int wait_and_stream_output(Function&& f)
        {
            CloseHandle(child_stdin);

            unsigned long bytes_read = 0;
            static constexpr int buffer_size = 1024 * 32;
            auto buf = std::make_unique<char[]>(buffer_size);

            do
            {
                const auto nProcessExitWaitResult = WaitForSingleObject(proc_info.proc_info.hProcess, 0);
                bool bProcessTerminated = (nProcessExitWaitResult == WAIT_OBJECT_0);

                DWORD nBytesAvailable{};
                /*auto bPeekSuccess =*/ PeekNamedPipe(child_stdout, nullptr, 0, nullptr, &nBytesAvailable, nullptr);
                if (nBytesAvailable == 0)
                {
                    if (bProcessTerminated)
                    {
                        break;
                    }

                    Sleep(1000);
                    continue;
                }
                if (ReadFile(child_stdout, (void*)buf.get(), buffer_size, &bytes_read, nullptr) && bytes_read > 0)
                {
                    f(StringView{buf.get(), static_cast<size_t>(bytes_read)});
                }
            } while (true);

            CloseHandle(child_stdout);

            return proc_info.wait();
        }
    };
```

The observed behavior in my test case with the test code version of vcpkg.exe:
- (cmake.exe) Process terminates, and shows as terminated via the wait on handle call
- PeekNamedPipe returns no data, breaks out of the loop
- proc_info.wait() is called
  - GetExitCodeProcess returns 0xc0000409

From google, it appears the error might be related to a std::ifstream bug? https://stackoverflow.com/questions/53421495/stdifstream-crashes-in-release-build-on-windows-with-exit-code-0xc0000409-unk

Anyway, hope that helps debug...

**Comment by JackBoosY** [comment]
cc @ras0219-msft @ras0219

**Comment by bt-ncarroll** [comment]
Another update:

I tried to hack the exit code checking to bypass the failure code, but something else is failing in the cmake.exe process. If I override the exit code, I get `Invalid BUILD_INFO file for package: no such file or directory`

This appears to be due to the cmake.exe process not writing the BUILD_INFO file to the packages directory (failure is build.cpp, ~1466)?

I'm a bit out of my depth here; I can keep hacking, but really hoping someone more knowledgeable can shed some light on what's going on, and/or how to work around.

**Comment by bt-ncarroll** [comment]
Checking in; any update? I am about to start re-writing this part of our build process to work around this presumable bug. What should my expectation be here? That is, is this a type of bug which I could expect the team to fix, or should I expect to have to work outside of vcpkg for some of my libraries?

Thanks for whatever info you can provide...

**Comment by JackBoosY** [comment]
@bt-ncarroll  Can you please `git pull` and retry?

Thanks.

**Comment by bt-ncarroll** [comment]
Don't know what was done, but this appears to have resolved the issue. :)

Going to do more validation testing today, but initial impression is that it now works.

**Comment by JackBoosY** [comment]
Okay, please reopen this issue if you meet it again.
