### ISSUE TITLE
Error: Building package openssl:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by lyxr** [microsoft/vcpkg#18349]
I want to install Point Cloud Library. So I run the comand in the terminal : .\vcpkg install pcl:x64-windows. But it always exits a error as my title show. There is what the terminal show： 
```
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
 Command failed: D:/Download/vcpkg-master/downloads/tools/perl/5.30.0.1/perl/bin/perl.exe  Configure enable-static-engine enable-capieng no-ssl2 no-tests -utf-8 shared VC-WIN64A  --prefix=D:/Download/vcpkg-master/packages/openssl_x64-windows --openssldir=D:/Download/vcpkgmaster/packages/openssl_x64-windows -FS
Working Directory: D:/Download/vcpkg-master/buildtrees/openssl/x64-windows-rel
    Error code: 255
    See logs for more information:
      D:\Download\vcpkg-master\buildtrees\openssl\configure-perl-x64-windows-rel-err.log
Call Stack (most recent call first):
  ports/openssl/windows/portfile.cmake:65 (vcpkg_execute_required_process)
  ports/openssl/portfile.cmake:19 (include)
  scripts/ports.cmake:139 (include)

Error: Building package openssl:x64-windows failed with: BUILD_FAILED
```
what can I do to deal with it? can somebody help me? Thanks very much! 
The error log:
Failure! build file wasnt produced.
Please read INSTALL and associated NOTES files. You may also hava to look over
your available compier tool chain or change your configuration.

erroneous version infomation in opensslv.h:,,,

**Comment by lyxr** [comment]
i try to install the other package.There exits another error. 

- 

> CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
    Command failed: D:/vcpkg/downloads/tools/cmake-3.20.2-windows/cmake-3.20.2-windows-i386/bin/cmake.exe D:/vcpkg/buildtrees/flann/src/638c8c7d9d-fc62c919a5.clean -DWITH_HDF5=OFF -DWITH_CUDA=OFF -DBUILD_DYNAMIC=1 -DBUILD_STATIC=0 -DBUILD_CUDA_LIB=OFF -DBUILD_EXAMPLES=OFF -DBUILD_TESTS=OFF -DBUILD_DOC=OFF -DBUILD_PYTHON_BINDINGS=OFF -DBUILD_MATLAB_BINDINGS=OFF -DCMAKE_DEBUG_POSTFIX=d -DHDF5_NO_FIND_PACKAGE_CONFIG_FILE=ON "-DCMAKE_MAKE_PROGRAM=D:/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -DBUILD_SHARED_LIBS=ON -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=D:/vcpkg/scripts/toolchains/windows.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=v142 -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=D:/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_LINKER_FLAGS_RELEASE= -DVCPKG_LINKER_FLAGS_DEBUG= -DVCPKG_TARGET_ARCHITECTURE=x64 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -D_VCPKG_ROOT_DIR=D:/vcpkg -D_VCPKG_INSTALLED_DIR=D:/vcpkg/installed -DVCPKG_MANIFEST_INSTALL=OFF -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=D:/vcpkg/packages/flann_x64-windows/debug
    Working Directory: D:/vcpkg/buildtrees/flann/x64-windows-dbg
    Error code: 1
    See logs for more information:
      D:\vcpkg\buildtrees\flann\config-x64-windows-dbg-out.log
      D:\vcpkg\buildtrees\flann\config-x64-windows-dbg-err.log

**Comment by NancyLi1013** [comment]
Hi @lyxr 

Thanks for posting this issue.
For `openssl`, there is also a related issue from upstream https://github.com/openssl/openssl/issues/9676.

For `flann`, please provide the error log from _D:\vcpkg\buildtrees\flann\config-x64-windows-dbg-out.log_ and `D:\vcpkg\buildtrees\flann\config-x64-windows-dbg-err.log`.

**Comment by JackBoosY** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
