### ISSUE TITLE
[fontconfig:x64-linux] build failure

### ISSUE THREAD

**Issue by Conan42** [microsoft/vcpkg#18342]
**Host Environment**
- OS: Ubuntu 20.04.2 or 21.04
- Compiler: gcc 9.3.0

**To Reproduce**
./vcpkg install osg

**Failure logs** 
mich@mich-desktop:~/vcpkg$ ./vcpkg install osg
Computing installation plan...
The following packages will be built and installed:
  * fontconfig[core]:x64-linux -> 2.13.1#7
    osg[core]:x64-linux -> 3.6.5#7
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-linux...
Could not locate cached archive: /home/mich/.cache/vcpkg/archives/06/065eeeac15d2934c6404aafb684e4d3273dc59de.zip
Could not locate cached archive: /home/mich/.cache/vcpkg/archives/e6/e6ad0498947f0c096d5556c8f5fe4ec0f43d5331.zip
Starting package 1/2: fontconfig:x64-linux
Building package fontconfig[core]:x64-linux...
-- Using /home/mich/vcpkg/downloads/fontconfig-fontconfig-844d8709a1f3ecab45015b24b72dd775c13b2421.tar.gz
-- Cleaning sources at /home/mich/vcpkg/buildtrees/fontconfig/src/75c13b2421-12bdc6f9c0.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/mich/vcpkg/downloads/fontconfig-fontconfig-844d8709a1f3ecab45015b24b72dd775c13b2421.tar.gz
-- Applying patch remove_tests.patch
-- Applying patch build.patch
-- Applying patch build2.patch
-- Applying patch disable-install-data.patch
-- Applying patch macos_arm_fccache.patch
-- Using source at /home/mich/vcpkg/buildtrees/fontconfig/src/75c13b2421-12bdc6f9c0.clean
CMake Error at scripts/cmake/vcpkg_find_acquire_program.cmake:535 (message):
  Could not find gperf.  Please install it via your package manager.
Call Stack (most recent call first):
  ports/fontconfig/portfile.cmake:22 (vcpkg_find_acquire_program)
  scripts/ports.cmake:139 (include)

Error: Building package fontconfig:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: fontconfig:x64-linux
  Vcpkg version: 2021-05-05-unknownhash

**Additional context**
Hello,
As I often say. To develop in C ++ it has to be earned. I have read your excellent utility vcpkg to install the OpenSceneGraph and osgEarth libraries. But I got an error message installing a fontconfig: x64-linux dependency. If anyone can fix this I would be very grateful. Thank you in advance.

Regards, 

Michel Guenin

**Comment by PhoebeHui** [comment]
> Could not find gperf. Please install it via your package manager.

@Conan42, could you install gperf via 'sudo apt -y install gperf' and try again?

**Comment by Conan42** [comment]
No other ideas? Why do I have the impression that this utility does nothing? just wasting time. After C ++ programmers can criticize Java. But the Java eco system manages dependencies much better.

**Comment by dg0yt** [comment]
> I did gperf, but still the same problem.

So vcpkg still reports "Could not find gperf" but you verified that `gperf --version` works?

**Comment by Conan42** [comment]
mich@Ticonderoga:~$ gperf --version
GNU gperf 3.1
Copyright (C) 1989-2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Written by Douglas C. Schmidt and Bruno Haible.

**Comment by Conan42** [comment]
I repeat a test :

mich@Ticonderoga:~$ cd vcpkg-master/
mich@Ticonderoga:~/vcpkg-master$ ./vcpkg install osg
Computing installation plan...
The following packages will be built and installed:
  * fontconfig[core]:x64-linux -> 2.13.1#7
    osg[core]:x64-linux -> 3.6.5#7
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-linux...
Could not locate cached archive: /home/mich/.cache/vcpkg/archives/64/641731e662d5519bf3082836210c745e9569b78e.zip
Could not locate cached archive: /home/mich/.cache/vcpkg/archives/42/42296d3c29f79a68b0b2737b15adcaed466903c7.zip
Starting package 1/2: fontconfig:x64-linux
Building package fontconfig[core]:x64-linux...
-- Using /home/mich/vcpkg-master/downloads/fontconfig-fontconfig-844d8709a1f3ecab45015b24b72dd775c13b2421.tar.gz
-- Cleaning sources at /home/mich/vcpkg-master/buildtrees/fontconfig/src/75c13b2421-12bdc6f9c0.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/mich/vcpkg-master/downloads/fontconfig-fontconfig-844d8709a1f3ecab45015b24b72dd775c13b2421.tar.gz
-- Applying patch remove_tests.patch
-- Applying patch build.patch
-- Applying patch build2.patch
-- Applying patch disable-install-data.patch
-- Applying patch macos_arm_fccache.patch
-- Using source at /home/mich/vcpkg-master/buildtrees/fontconfig/src/75c13b2421-12bdc6f9c0.clean
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Generating configure for x64-linux
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
    Command failed: /usr/bin/autoreconf -vfi
    Working Directory: /home/mich/vcpkg-master/buildtrees/fontconfig/src/75c13b2421-12bdc6f9c0.clean/
    Error code: 1
    See logs for more information:
      /home/mich/vcpkg-master/buildtrees/fontconfig/autoconf-x64-linux-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:636 (vcpkg_execute_required_process)
  ports/fontconfig/portfile.cmake:26 (vcpkg_configure_make)
  scripts/ports.cmake:139 (include)


Error: Building package fontconfig:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: fontconfig:x64-linux
  Vcpkg version: 2021-05-05-unknownhash

Additionally, attach any relevant sections from the log files above.


we can see that there are no more messages on gperf

**Comment by dg0yt** [comment]
> we can see that there are no more messages on gperf

Indeed, so "still the same problem" isn't the case.

>       CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
>       Command failed: /usr/bin/autoreconf -vfi
>       Working Directory: /home/mich/vcpkg-master/buildtrees/fontconfig/src/75c13b2421-12bdc6f9c0.clean/
>       Error code: 1
>       See logs for more information:
>       /home/mich/vcpkg-master/buildtrees/fontconfig/autoconf-x64-linux-err.log

From this error message, I would suggest to install the [package which provides `/usr/bin/autoreconf`](https://packages.ubuntu.com/search?searchon=contents&keywords=autoreconf&mode=exactfilename&suite=hirsute&arch=any).

But it may be more convenient to shortcut the installing of individual packages by simply installing `packaging-dev`.

**Comment by Conan42** [comment]
in the file autoconf-x64-linux-err.log:

autoreconf: Entering directory `.'
autoreconf: running: autopoint --force
Can't exec "autopoint": No such file or folder at /usr/share/autoconf/Autom4te/FileUtils.pm line 345.
autoreconf: failed to run autopoint: No such file or directory
autoreconf: autopoint is needed because this package uses Gettext

**Comment by dg0yt** [comment]
>  "autopoint": No such file or folder

Install `autopoint`. Or... 

>  it may be more convenient to shortcut the installing of individual packages by simply installing `packaging-dev`.

(FTR I have two PRs which would add autopoint to vcpkg's gettext port for Linux: #18159, #17317.)

**Comment by PhoebeHui** [comment]
@Conan42, could you try above suggestion?

**Comment by Conan42** [comment]
Well, I know nothing. I am exceeding. I installed Fontconfig on a 21.04 ubuntu and it will walk, and I do not know how, but I have other problem. I thought a utility like VCPKG could help me. To want to program in C ++ that this merit ...

**Comment by Conan42** [comment]
My goal is to install OpenSceneGraph and Osgearth and I do not come there. I risk falling. I wanted to adapt my "Harpoon for Android" project in C ++ for all systems.

**Comment by PhoebeHui** [comment]
@Conan42, sorry for the confuse, I think you can reference https://github.com/microsoft/vcpkg/blob/master/scripts/azure-pipelines/linux/provision-image.sh#L9 to install the required package on linux platform directly, these also applied to our ci testing, so it should work when you install the project again.

**Comment by PhoebeHui** [comment]
@Conan42, do you try above suggestions?

**Comment by Conan42** [comment]
No other suggestion. Thanks for your help. But it's expenses how to install Ubuntu. I have abandoned VCPKG for manual installations or facilities with APT-Get. The learning curve is very long in C ++. As I say before, C ++ this merit. For the moment it's a failure. I would stay there once. I'm going on something else with Javafx and Worldwind.

**Comment by PhoebeHui** [comment]
@Conan42, thanks for your response.
