### ISSUE TITLE
building package failed (versioning) build failure

### ISSUE THREAD

**Issue by ErnestoQuispe** [microsoft/vcpkg#18351]
**Host Environment**
- Windows 10
- Compiler: Visual Studio 2019  version 16.10.0

**To Reproduce**
- Hi I am new and I am trying to work with a old version of gtkmm ( for this objective I am using versioning)
- I created a vcpkg.json with the next code:
{
  "name": "versions-test",
  "version": "1.0.0",
  "dependencies": [
    {
      "name": "gtkmm",
      "version>=": "4.0.1"
    }
  ],
  "builtin-baseline": "546813ae7b9e2873dd3d38e78b27ac5582feae10",
  "overrides": [
    {
      "name": "gtkmm",
      "version-string": "3.22.2"
    }
  ]
}
(I tried without overrides and the program didnt downloaded anything)
- After downloading a lot of packages (dependencies of gtkmm) it appears the next log. 

**Failure logs** 
I have 3 errors in the List
1.- Severity	Code	Description	Project	File	Line	Suppression State
Error	code	1	vpk5	C:\Users\34675\source\repos\vpk5\vpk5\EXEC	1	

2.- Severity	Code	Description	Project	File	Line	Suppression State
Error		Building package gdk-pixbuf:x64-windows failed with: BUILD_FAILED	vpk5	C:\Users\34675\source\repos\vpk5\vpk5\EXEC	1	
3.- Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command ""C:\vcpkg\scripts\buildsystems\msbuild\..\..\..\vcpkg.exe" install  --x-wait-for-lock --triplet "x64-windows" --vcpkg-root "C:\vcpkg\scripts\buildsystems\msbuild\..\..\..\\" "--x-manifest-root=C:\Users\34675\source\repos\vpk5\\" "--x-install-root=C:\Users\34675\source\repos\vpk5\vcpkg_installed\\" " exited with code 1.	vpk5	C:\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets	104	

**Additional context**
- I dont understand where is the issue, I tryed with sqlite3 library and everything worked fine. 
- Finally I tryed with others commit and I have the 1 and 3 error same. But error 2 cant build the package  of pangomm.

**Comment by PhoebeHui** [comment]
@ErnestoQuispe, could you attach full failure logs?

**Comment by ErnestoQuispe** [comment]
this is my output?
Build started...
1>------ Build started: Project: vpk5, Configuration: Debug x64 ------
1>Installing vcpkg dependencies to C:\Users\34675\source\repos\vpk5\vcpkg_installed\
1>"C:\vcpkg\scripts\buildsystems\msbuild\..\..\..\vcpkg.exe" install  --x-wait-for-lock --triplet "x64-windows" --vcpkg-root "C:\vcpkg\scripts\buildsystems\msbuild\..\..\..\\" "--x-manifest-root=C:\Users\34675\source\repos\vpk5\\" "--x-install-root=C:\Users\34675\source\repos\vpk5\vcpkg_installed\\"
1>Detecting compiler hash for triplet x64-windows...
1>The following packages will be built and installed:
1>    atk[core]:x64-windows -> 2.36.0 -- C:\vcpkg\buildtrees\versioning\versions\atk\b8ace143cf9715262f419c85a5840fa15a4cf0ce
1>    atkmm[core]:x64-windows -> 2.36.0 -- C:\vcpkg\buildtrees\versioning\versions\atkmm\1feae8dc89c99e89b47bb8a028cca2e77d9d4352
1>    gdk-pixbuf[core]:x64-windows -> 2.42.2 -- C:\vcpkg\buildtrees\versioning\versions\gdk-pixbuf\609b77f244ec0d76aac5616cd8654dfcbc608297
1>    gtk[core]:x64-windows -> 4.0.1 -- C:\vcpkg\buildtrees\versioning\versions\gtk\5df8abca385bd61477f2da4217d0a88c3659db82
1>    gtkmm[core]:x64-windows -> 3.22.2 -- C:\vcpkg\buildtrees\versioning\versions\gtkmm\4ceb1e90e6f6f9a6ea0fcc1491ff35e92f0ca6c9
1>Could not locate cached archive: C:\Users\34675\AppData\Local\vcpkg\archives\cf\cfbee17f414ed8ac0f0a1a6a49a9fc967a08d131.zip
1>Could not locate cached archive: C:\Users\34675\AppData\Local\vcpkg\archives\98\9835d24ebe7625eee0b1a07fcd3f1a016c216b90.zip
1>Could not locate cached archive: C:\Users\34675\AppData\Local\vcpkg\archives\5c\5cb0a9e66b2e7e2f0436d3f2c8fc598938ec5e13.zip
1>Could not locate cached archive: C:\Users\34675\AppData\Local\vcpkg\archives\e4\e455e2a02f3371f933e17bcc507dd90f7b46c486.zip
1>Could not locate cached archive: C:\Users\34675\AppData\Local\vcpkg\archives\b6\b68b5445f584944b8047a3de9ac50a03bd67ed8c.zip
1>Starting package 1/5: gdk-pixbuf:x64-windows
1>Building package gdk-pixbuf[core]:x64-windows...
1>-- Installing port from location: C:\vcpkg\buildtrees\versioning\versions\gdk-pixbuf\609b77f244ec0d76aac5616cd8654dfcbc608297
1>-- Using C:/vcpkg/downloads/gdk-pixbuf-2.42.2.tar.xz
1>-- Cleaning sources at C:/vcpkg/buildtrees/gdk-pixbuf/src/k-pixbuf-2-c86079bed6.clean. Use --editable to skip cleaning for the packages you specify.
1>-- Extracting source C:/vcpkg/downloads/gdk-pixbuf-2.42.2.tar.xz
1>-- Applying patch fix_build.patch
1>-- Using source at C:/vcpkg/buildtrees/gdk-pixbuf/src/k-pixbuf-2-c86079bed6.clean
1>-- Found external ninja('1.10.2').
1>-- Configuring x64-windows
1>-- Using msys root at C:/vcpkg/downloads/tools/msys2/aa5af7b2aa7e90e8
1>-- Configuring x64-windows-dbg
1>-- Configuring x64-windows-dbg done
1>-- Configuring x64-windows-rel
1>-- Configuring x64-windows-rel done
1>-- Package x64-windows-dbg
1>-- Package x64-windows-rel
1>CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
1>    Command failed: C:/VS2019/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe install -v
1>    Working Directory: C:/vcpkg/buildtrees/gdk-pixbuf/x64-windows-rel
1>EXEC : error code: 1
1>    See logs for more information:
1>      C:\vcpkg\buildtrees\gdk-pixbuf\package-x64-windows-rel-out.log
1>
1>Call Stack (most recent call first):
1>  scripts/cmake/vcpkg_install_meson.cmake:58 (vcpkg_execute_required_process)
1>  buildtrees/versioning/versions/gdk-pixbuf/609b77f244ec0d76aac5616cd8654dfcbc608297/portfile.cmake:38 (vcpkg_install_meson)
1>  scripts/ports.cmake:139 (include)
1>
1>
1>EXEC : error : Building package gdk-pixbuf:x64-windows failed with: BUILD_FAILED
1>Please ensure you're using the latest portfiles with `.\vcpkg update`, then
1>submit an issue at https://github.com/Microsoft/vcpkg/issues including:
1>  Package: gdk-pixbuf:x64-windows
1>  Vcpkg version: 2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9
1>
1>Additionally, attach any relevant sections from the log files above.
1>C:\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(104,5): error MSB3073: The command ""C:\vcpkg\scripts\buildsystems\msbuild\..\..\..\vcpkg.exe" install  --x-wait-for-lock --triplet "x64-windows" --vcpkg-root "C:\vcpkg\scripts\buildsystems\msbuild\..\..\..\\" "--x-manifest-root=C:\Users\34675\source\repos\vpk5\\" "--x-install-root=C:\Users\34675\source\repos\vpk5\vcpkg_installed\\" " exited with code 1.
1>Done building project "vpk5.vcxproj" -- FAILED.



[package-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/6630886/package-x64-windows-rel-out.log)

**Comment by PhoebeHui** [comment]
@ErnestoQuispe, this is a Upstream issue, and it has been fixed by adding patch in vcpkg, see related PR https://github.com/microsoft/vcpkg/pull/17528, so you may need to use version '2.42.2#1' via overriding below code in your vcpkg.json file.

```
{
"name": "gdk-pixbuf",
"version": "2.42.2",
"port-version": 1
}
```

**Comment by ErnestoQuispe** [comment]
Thank you. 
I added the line and the package was installed correctly. 
However now I have this error message:
I am not sure if the commit that I am using is correct or the port of gtkmm 3.22.2. 


![image](https://user-images.githubusercontent.com/84517625/121667827-f777b280-caaa-11eb-87d3-0f299fae0a5f.png)



Build started...
1>------ Build started: Project: vpk5, Configuration: Debug x64 ------
1>Installing vcpkg dependencies to C:\Users\34675\source\repos\vpk5\vcpkg_installed\
1>"C:\vcpkg\scripts\buildsystems\msbuild\..\..\..\vcpkg.exe" install  --x-wait-for-lock --triplet "x64-windows" --vcpkg-root "C:\vcpkg\scripts\buildsystems\msbuild\..\..\..\\" "--x-manifest-root=C:\Users\34675\source\repos\vpk5\\" "--x-install-root=C:\Users\34675\source\repos\vpk5\vcpkg_installed\\"
1>Detecting compiler hash for triplet x64-windows...
1>The following packages will be built and installed:
1>    gtkmm[core]:x64-windows -> 3.22.2 -- C:\vcpkg\buildtrees\versioning\versions\gtkmm\4ceb1e90e6f6f9a6ea0fcc1491ff35e92f0ca6c9
1>Could not locate cached archive: C:\Users\34675\AppData\Local\vcpkg\archives\63\636b94ae2c60cfdcd5052dcca70244cd2f480aa4.zip
1>Starting package 1/1: gtkmm:x64-windows
1>Building package gtkmm[core]:x64-windows...
1>-- Installing port from location: C:\vcpkg\buildtrees\versioning\versions\gtkmm\4ceb1e90e6f6f9a6ea0fcc1491ff35e92f0ca6c9
1>CMake Warning at scripts/cmake/vcpkg_common_functions.cmake:3 (message):
1>  vcpkg_common_functions has been removed and all values are automatically
1>  provided in all portfile.cmake invocations.  Please remove
1>  `include(vcpkg_common_functions)`.
1>Call Stack (most recent call first):
1>  buildtrees/versioning/versions/gtkmm/4ceb1e90e6f6f9a6ea0fcc1491ff35e92f0ca6c9/portfile.cmake:13 (include)
1>  scripts/ports.cmake:139 (include)
1>
1>
1>-- Using C:/vcpkg/downloads/gtkmm-3.22.2.tar.xz
1>CMake Deprecation Warning at scripts/ports.cmake:17 (message):
1>  vcpkg_apply_patches has been deprecated in favor of the `PATCHES` argument
1>  to `vcpkg_from_*`.
1>Call Stack (most recent call first):
1>  scripts/cmake/vcpkg_apply_patches.cmake:18 (z_vcpkg_deprecation_message)
1>  buildtrees/versioning/versions/gtkmm/4ceb1e90e6f6f9a6ea0fcc1491ff35e92f0ca6c9/portfile.cmake:22 (vcpkg_apply_patches)
1>  scripts/ports.cmake:139 (include)
1>
1>
1>-- Applying patch C:/vcpkg/buildtrees/versioning/versions/gtkmm/4ceb1e90e6f6f9a6ea0fcc1491ff35e92f0ca6c9/fix_properties.patch
1>CMake Error at scripts/cmake/z_vcpkg_apply_patches.cmake:61 (message):
1>  Applying patch failed: Checking patch MSVC_Net2013/gdkmm.vcxproj...
1>
1>EXEC : error : while searching for:
1>
1>        <Command>$(OutDir)\gendef.exe $(DefDir)\$(ProjectName).def $(TargetFileName) $(IntDir)*.obj</Command>
1>      </PreLinkEvent>
1>      <Link>
1>        <AdditionalDependencies>$(CPPDepLibsDebug);%(AdditionalDependencies)</AdditionalDependencies>
1>        <OutputFile>$(OutDir)$(ProjectName)$(DebugDllSuffix).dll</OutputFile>
1>        <ModuleDefinitionFile>$(IntDir)\$(ProjectName).def</ModuleDefinitionFile>
1>        <GenerateDebugInformation>true</GenerateDebugInformation>
1>
1>
1>
1>EXEC : error : patch failed: MSVC_Net2013/gdkmm.vcxproj:93
1>
1>EXEC : error : MSVC_Net2013/gdkmm.vcxproj: patch does not apply
1>
1>  Checking patch MSVC_Net2013/gdkmm.vcxproj.filters...
1>
1>EXEC : error : while searching for:
1>
1>      </Filter>
1>    </ItemGroup>
1>    <ItemGroup>
1>      <ClCompile Include="..\gdk\gdkmm\applaunchcontext.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gdk\gdkmm\color.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gdk\gdkmm\colormap.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gdk\gdkmm\cursor.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gdk\gdkmm\device.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gdk\gdkmm\devicemanager.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gdk\gdkmm\display.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gdk\gdkmm\displaymanager.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gdk\gdkmm\dragcontext.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gdk\gdkmm\drawingcontext.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gdk\gdkmm\event.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gdk\gdkmm\general.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gdk\gdkmm\glcontext.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gdk\gdkmm\monitor.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gdk\gdkmm\pixbuf.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gdk\gdkmm\pixbufanimation.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gdk\gdkmm\pixbufanimationiter.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gdk\gdkmm\pixbufformat.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gdk\gdkmm\pixbufloader.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gdk\gdkmm\rectangle.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gdk\gdkmm\rgba.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gdk\gdkmm\seat.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gdk\gdkmm\screen.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gdk\gdkmm\timecoord.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gdk\gdkmm\types.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gdk\gdkmm\visual.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gdk\gdkmm\window.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gdk\gdkmm\wrap_init.cc"><Filter>Source Files</Filter></ClCompile>
1>    </ItemGroup>
1>    <ItemGroup>
1>      <ClInclude Include="..\gdk\gdkmm\applaunchcontext.h"><Filter>Header Files</Filter></ClInclude>
1>      <ClInclude Include="..\gdk\gdkmm\color.h"><Filter>Header Files</Filter></ClInclude>
1>      <ClInclude Include="..\gdk\gdkmm\colormap.h"><Filter>Header Files</Filter></ClInclude>
1>      <ClInclude Include="..\gdk\gdkmm\cursor.h"><Filter>Header Files</Filter></ClInclude>
1>      <ClInclude Include="..\gdk\gdkmm\device.h"><Filter>Header Files</Filter></ClInclude>
1>      <ClInclude Include="..\gdk\gdkmm\devicemanager.h"><Filter>Header Files</Filter></ClInclude>
1>      <ClInclude Include="..\gdk\gdkmm\display.h"><Filter>Header Files</Filter></ClInclude>
1>      <ClInclude Include="..\gdk\gdkmm\displaymanager.h"><Filter>Header Files</Filter></ClInclude>
1>      <ClInclude Include="..\gdk\gdkmm\dragcontext.h"><Filter>Header Files</Filter></ClInclude>
1>      <ClInclude Include="..\gdk\gdkmm\drawingcontext.h"><Filter>Header Files</Filter></ClInclude>
1>      <ClInclude Include="..\gdk\gdkmm\event.h"><Filter>Header Files</Filter></ClInclude>
1>      <ClInclude Include="..\gdk\gdkmm\gc.h"><Filter>Header Files</Filter></ClInclude>
1>      <ClInclude Include="..\gdk\gdkmm\general.h"><Filter>Header Files</Filter></ClInclude>
1>      <ClInclude Include="..\gdk\gdkmm\glcontext.h"><Filter>Header Files</Filter></ClInclude>
1>      <ClInclude Include="..\gdk\gdkmm\list.h"><Filter>Header Files</Filter></ClInclude>
1>      <ClInclude Includ
1>
1>EXEC : error : patch failed: MSVC_Net2013/gdkmm.vcxproj.filters:15
1>
1>EXEC : error : MSVC_Net2013/gdkmm.vcxproj.filters: patch does not apply
1>
1>  Checking patch MSVC_Net2013/gtkmm-build-defines.props...
1>
1>EXEC : error : while searching for:
1>
1>      <Import Project="gtkmm-version-paths.props" />
1>    </ImportGroup>
1>    <PropertyGroup Label="UserMacros">
1>      <GdkMMBuildDefs>GDKMM_BUILD</GdkMMBuildDefs>
1>      <GtkMMBuildDefs>GTKMM_BUILD</GtkMMBuildDefs>
1>      <CPPDepLibsRelease>pangomm-vc$(VSVer)0-1_4.lib;giomm-vc$(VSVer)0-2_4.lib;glibmm-vc$(VSVer)0-2_4.lib;cairomm-vc$(VSVer)0-1_0.lib;sigc-vc$(VSVer)0-2_0.lib</CPPDepLibsRelease>
1>      <CPPDepLibsDebug>pangomm-vc$(VSVer)0-d-1_4.lib;giomm-vc$(VSVer)0-d-2_4.lib;glibmm-vc$(VSVer)0-d-2_4.lib;cairomm-vc$(VSVer)0-d-1_0.lib;sigc-vc$(VSVer)0-d-2_0.lib</CPPDepLibsDebug>
1>    </PropertyGroup>
1>    <PropertyGroup>
1>      <_PropertySheetDisplayName>glibmmbuilddefinesprops</_PropertySheetDisplayName>
1>
1>
1>
1>EXEC : error : patch failed: MSVC_Net2013/gtkmm-build-defines.props:4
1>
1>EXEC : error : MSVC_Net2013/gtkmm-build-defines.props: patch does not apply
1>
1>  Checking patch MSVC_Net2013/gtkmm-version-paths.props...
1>
1>EXEC : error : while searching for:
1>
1>  <Project DefaultTargets="Build" ToolsVersion="4.0"
1>  xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
1>
1>    <PropertyGroup Label="UserMacros">
1>      <VSVer>12</VSVer>
1>      <GlibEtcInstallRoot>$(SolutionDir)\..\..\vs$(VSVer)\$(Platform)</GlibEtcInstallRoot>
1>      <CopyDir>$(GlibEtcInstallRoot)</CopyDir>
1>      <DefDir>$(SolutionDir)$(Configuration)\$(Platform)\obj\$(ProjectName)\</DefDir>
1>      <ApiMajorVersion>3</ApiMajorVersion>
1>      <ApiMinorVersion>0</ApiMinorVersion>
1>      <ReleaseDllSuffix>-vc$(VSVer)0-$(ApiMajorVersion)_$(ApiMinorVersion)</ReleaseDllSuffix>
1>      <DebugDllSuffix>-vc$(VSVer)0-d-$(ApiMajorVersion)_$(ApiMinorVersion)</DebugDllSuffix>
1>    </PropertyGroup>
1>    <PropertyGroup>
1>      <_PropertySheetDisplayName>glibmmversionpathsprops</_PropertySheetDisplayName>
1>
1>
1>
1>EXEC : error : patch failed: MSVC_Net2013/gtkmm-version-paths.props:2
1>
1>EXEC : error : MSVC_Net2013/gtkmm-version-paths.props: patch does not apply
1>
1>  Checking patch MSVC_Net2013/gtkmm.vcxproj...
1>
1>EXEC : error : while searching for:
1>
1>        <AdditionalOptions>%(AdditionalOptions)</AdditionalOptions>
1>        <Optimization>Disabled</Optimization>
1>        <AdditionalIncludeDirectories>.\gtkmm;..\gtk;$(GlibEtcInstallRoot)\include\atkmm-1.6;$(GlibEtcInstallRoot)\lib\atkmm-1.6\include;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
1>        <PreprocessorDefinitions>_DEBUG;$(GtkMMBuildDefs);%(PreprocessorDefinitions)</PreprocessorDefinitions>
1>        <MinimalRebuild>true</MinimalRebuild>
1>        <BasicRuntimeChecks>EnableFastChecks</BasicRuntimeChecks>
1>        <RuntimeLibrary>MultiThreadedDebugDLL</RuntimeLibrary>
1>
1>
1>
1>EXEC : error : patch failed: MSVC_Net2013/gtkmm.vcxproj:80
1>
1>EXEC : error : MSVC_Net2013/gtkmm.vcxproj: patch does not apply
1>
1>  Checking patch MSVC_Net2013/gtkmm.vcxproj.filters...
1>
1>EXEC : error : while searching for:
1>
1>      </Filter>
1>    </ItemGroup>
1>    <ItemGroup>
1>      <ClCompile Include="..\gtk\gtkmm\aboutdialog.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gtk\gtkmm\accelgroup.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gtk\gtkmm\accelkey.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gtk\gtkmm\accellabel.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gtk\gtkmm\accelmap.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gtk\gtkmm\action.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gtk\gtkmm\actionable.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gtk\gtkmm\actionbar.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gtk\gtkmm\actiongroup.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gtk\gtkmm\activatable.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gtk\gtkmm\adjustment.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gtk\gtkmm\alignment.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gtk\gtkmm\appchooser.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gtk\gtkmm\appchooserbutton.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gtk\gtkmm\appchooserdialog.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gtk\gtkmm\appchooserwidget.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gtk\gtkmm\application.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gtk\gtkmm\applicationwindow.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gtk\gtkmm\arrow.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gtk\gtkmm\aspectframe.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gtk\gtkmm\assistant.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gtk\gtkmm\bin.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gtk\gtkmm\border.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gtk\gtkmm\box.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gtk\gtkmm\buildable.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gtk\gtkmm\builder.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gtk\gtkmm\button.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gtk\gtkmm\buttonbox.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gtk\gtkmm\calendar.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gtk\gtkmm\cellarea.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gtk\gtkmm\cellareabox.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gtk\gtkmm\cellareacontext.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gtk\gtkmm\celleditable.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gtk\gtkmm\celllayout.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gtk\gtkmm\cellrenderer.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gtk\gtkmm\cellrenderer_generation.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gtk\gtkmm\cellrendereraccel.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gtk\gtkmm\cellrenderercombo.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gtk\gtkmm\cellrendererpixbuf.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gtk\gtkmm\cellrendererprogress.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gtk\gtkmm\cellrendererspin.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include="..\gtk\gtkmm\cellrendererspinner.cc"><Filter>Source Files</Filter></ClCompile>
1>      <ClCompile Include=
1>
1>EXEC : error : patch failed: MSVC_Net2013/gtkmm.vcxproj.filters:14
1>
1>EXEC : error : MSVC_Net2013/gtkmm.vcxproj.filters: patch does not apply
1>
1>Call Stack (most recent call first):
1>  scripts/cmake/vcpkg_apply_patches.cmake:28 (z_vcpkg_apply_patches)
1>  buildtrees/versioning/versions/gtkmm/4ceb1e90e6f6f9a6ea0fcc1491ff35e92f0ca6c9/portfile.cmake:22 (vcpkg_apply_patches)
1>  scripts/ports.cmake:139 (include)
1>
1>
1>EXEC : error : Building package gtkmm:x64-windows failed with: BUILD_FAILED
1>Please ensure you're using the latest portfiles with `.\vcpkg update`, then
1>submit an issue at https://github.com/Microsoft/vcpkg/issues including:
1>  Package: gtkmm:x64-windows
1>  Vcpkg version: 2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9
1>
1>Additionally, attach any relevant sections from the log files above.
1>C:\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(104,5): error MSB3073: The command ""C:\vcpkg\scripts\buildsystems\msbuild\..\..\..\vcpkg.exe" install  --x-wait-for-lock --triplet "x64-windows" --vcpkg-root "C:\vcpkg\scripts\buildsystems\msbuild\..\..\..\\" "--x-manifest-root=C:\Users\34675\source\repos\vpk5\\" "--x-install-root=C:\Users\34675\source\repos\vpk5\vcpkg_installed\\" " exited with code 1.
1>Done building project "vpk5.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by PhoebeHui** [comment]
It looks same issue with https://github.com/microsoft/vcpkg/issues/16955.
