### ISSUE TITLE
How do I set vcpkg cli to use Visual Studio generator to avoid ninja build errors?

### ISSUE THREAD

**Issue by zcream** [microsoft/vcpkg#18352]
In the Visual Studio docs - https://docs.microsoft.com/en-us/cpp/build/customize-cmake-settings?view=msvc-160 setting Visual Studio generator is described.
However, its not so clear what I need to do from vcpkg cli. vcpkg_configure_cmake.cmake and vcpkg_build_cmake.cmake have entries related to the generator. How do I use the latest Visual Studio as generator ?

**Comment by PhoebeHui** [comment]
@zcream, AFAIK, this is no way to pass the option in cli, however, you can remove 'PREFER_NINJA' from portfile.cmake, it will msbuild to build the project..
