### ISSUE TITLE
[New Port Request] CorrelationVector

### ISSUE THREAD

**Issue by JeanPhilippeKernel** [microsoft/vcpkg#18354]
Library name: Correlation Vector

Library description: CorrelationVector-Cpp provides the C++ implementation of the CorrelationVector protocol for tracing and correlation of events through a distributed system.

Source repository URL: https://github.com/microsoft/CorrelationVector-Cpp/commit/cf38d2b44baaf352509ad9980786bc49554c32e4

Project homepage (if different from the source repository): 

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
