### ISSUE TITLE
icu package does not build

### ISSUE THREAD

**Issue by jellnicy** [microsoft/vcpkg#1835]
on win10, Chinese locale, vcpkg is using matser  eb05915

error in installing icu, here is output

>PS C:\vcpkg> .\vcpkg.exe install icu:x64-windows
The following packages will be built and installed:
    icu:x64-windows
Starting package 1/1: icu:x64-windows
Building package icu:x64-windows...
-- CURRENT_INSTALLED_DIR=C:/vcpkg/installed/x64-windows
-- DOWNLOADS=C:/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/vcpkg/packages/icu_x64-windows
-- CURRENT_BUILDTREES_DIR=C:/vcpkg/buildtrees/icu
-- CURRENT_PORT_DIR=C:/vcpkg/ports/icu/.
-- Using cached C:/vcpkg/downloads/icu4c-59_1-src.zip
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting source C:/vcpkg/downloads/icu4c-59_1-src.zip
-- Extracting done
-- Applying patch C:/vcpkg/ports/icu/disable-escapestr-tool.patch
-- Applying patch C:/vcpkg/ports/icu/disable-escapestr-tool.patch done
-- Configuring x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:43 (message):
    Command failed: C:/vcpkg/downloads/tools/msys2/msys64/usr/bin/bash.exe;--noprofile;--norc;-c;C:/vcpkg/buildtrees/icu/src/icu-59.1/icu/source/runConfigureI
CU MSYS/MSVC --host=i686-pc-mingw32 --disable-samples --disable-tests --disable-static --enable-shared --disable-debug --enable-release --prefix=C:/vcpkg/pack
ages/icu_x64-windows
    Working Directory: C:/vcpkg/buildtrees/icu/x64-windows-rel
    See logs for more information:
      C:\vcpkg\buildtrees\icu\configure-x64-windows-rel-out.log
      C:\vcpkg\buildtrees\icu\configure-x64-windows-rel-err.log

>Call Stack (most recent call first):
  ports/icu/portfile.cmake:58 (vcpkg_execute_required_process)
  scripts/ports.cmake:72 (include)

>Error: Building package icu:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: icu:x64-windows
  Vcpkg version: 0.0.89-unknownhash

>Additionally, attach any relevant sections from the log files above.
PS C:\vcpkg>

here is configure-x64-windows-rel-err.log

>configure: error: in `/c/vcpkg/buildtrees/icu/x64-windows-rel':
configure: error: C compiler cannot create executables
See `config.log' for more details

here is config.log

>This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

>It was created by ICU configure 59.1, which was
generated by GNU Autoconf 2.69.  Invocation command line was

>  $ C:/vcpkg/buildtrees/icu/src/icu-59.1/icu/source//configure --host=i686-pc-mingw32 --disable-samples --disable-tests --disable-static --enable-shared --disable-debug --enable-release --prefix=C:/vcpkg/packages/icu_x64-windows

 >'---------' 
 >'Platform.'
 >'---------'

>hostname = DESKTOP
uname -m = x86_64
uname -r = 2.9.0(0.318/5/3)
uname -s = MSYS_NT-10.0
uname -v = 2017-09-13 23:16

>/usr/bin/uname -p = unknown
/bin/uname -X     = unknown

>/bin/arch              = x86_64
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = unknown
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

>PATH: /c/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.11.25503/bin/HostX64/x64
PATH: /c/Program Files (x86)/Microsoft Visual Studio/2017/Professional/Common7/IDE/VC/VCPackages
PATH: /c/Program Files (x86)/Microsoft Visual Studio/2017/Professional/Common7/IDE/CommonExtensions/Microsoft/TestWindow
PATH: /c/Program Files (x86)/Microsoft Visual Studio/2017/Professional/Common7/IDE/CommonExtensions/Microsoft/TeamFoundation/Team Explorer
PATH: /c/Program Files (x86)/Microsoft Visual Studio/2017/Professional/MSBuild/15.0/bin/Roslyn
PATH: /c/Program Files (x86)/Microsoft Visual Studio/2017/Professional/Team Tools/Performance Tools
PATH: /c/Program Files (x86)/Microsoft Visual Studio/Shared/Common/VSPerfCollectionTools
PATH: /c/Program Files (x86)/Microsoft SDKs/Windows/v10.0A/bin/NETFX 4.6.1 Tools/x64
PATH: /c/Program Files (x86)/Windows Kits/10/bin/x64
PATH: /c/Program Files (x86)/Windows Kits/10/bin/10.0.15063.0/x64
PATH: /c/Program Files (x86)/Microsoft Visual Studio/2017/Professional/MSBuild/15.0/bin
PATH: /c/Windows/Microsoft.NET/Framework64/v4.0.30319
PATH: /c/Program Files (x86)/Microsoft Visual Studio/2017/Professional/Common7/IDE
PATH: /c/Program Files (x86)/Microsoft Visual Studio/2017/Professional/Common7/Tools
PATH: /usr/bin
PATH: /c/Windows/system32
PATH: /c/Windows
PATH: /c/Windows/system32/Wbem
PATH: /c/Windows/system32/WindowsPowerShell/v1.0

> `-----------` 
> Core tests. 
>` ----------- `

>configure:2627: checking for ICU version numbers
configure:2660: result: release 59.1, library 59.1, unicode version 9.0
configure:2699: checking build system type
configure:2713: result: x86_64-pc-msys
configure:2733: checking host system type
configure:2746: result: i686-pc-mingw32
configure:2789: checking whether to build debug libraries
configure:2801: result: no
configure:2806: checking whether to build release libraries
configure:2818: result: yes
configure:2837: checking for i686-pc-mingw32-clang
configure:2864: result: cl
configure:2939: checking for C compiler version
configure:2948: cl --version >&5
用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.11.25508.2 版
版权所有(C) Microsoft Corporation。保留所有权利。

>cl: 命令行 warning D9002 :忽略未知选项“--version”
cl: Command-Line error D8003 :cl: Command-Line error D8000 :cl: Command-Line error D8000 :cl: Command-Line error D8000 :cl: Command-Line error D8000 :

after this, there is lots of "cl: Command-Line error D8000 :"

If you need more info in log or something else, please let me know.

**Comment by lineCode** [comment]
I have the same problem, have you solved it?

**Comment by jellnicy** [comment]
Sorry but no, maybe we can manually build icu for now.

**Comment by ras0219-msft** [comment]
Could you try running `chcp 65001` in your console before invoking vcpkg?

**Comment by jellnicy** [comment]
I tried and checked all the error message, nothing change.

**Comment by YunHsiao** [comment]
try `chcp 936` instead, not pretty, but works for me.

**Comment by NancyLi1013** [comment]
This should be fixed now. Please try to update vcpkg and rebuild this port.
