### ISSUE TITLE
关于uwebsocket的lib的问题。

### ISSUE THREAD

**Issue by yzw88** [microsoft/vcpkg#18369]
When asking a question please also include where you looked for an answer (so we can update the documentation if needed).
你好。请教下。

root@localhost vcpkg]# ./vcpkg install uwebsockets
Computing installation plan...
The following packages are already installed:
    uwebsockets[core]:x64-linux -> 19.0.0.5
Package uwebsockets:x64-linux is already installed

Total elapsed time: 20.73 us

The package uwebsockets:x64-linux is header only and can be used from CMake via:

    find_path(UWEBSOCKETS_INCLUDE_DIRS "uwebsockets/App.h")
    target_include_directories(main PRIVATE ${UWEBSOCKETS_INCLUDE_DIRS})

问题：
貌似这里没法引入 lib 哦？仅仅引入了头文件？

  find_path(UWEBSOCKETS_INCLUDE_DIRS "uwebsockets/App.h")
    target_include_directories(main PRIVATE ${UWEBSOCKETS_INCLUDE_DIRS})

**Comment by NancyLi1013** [comment]
Hi @yzw88 

Thanks for posting this issue.
Since `uwebsockets `is a header-only library. There are no any libs or dlls generated in this port. The current behavior is intended.

**Comment by NancyLi1013** [comment]
Please let me know if still have other concerns about this issue.

**Comment by yzw88** [comment]
thanks
