### ISSUE TITLE
[devil] build failure

### ISSUE THREAD

**Issue by chaquator** [microsoft/vcpkg#18363]
**Host Environment**
- OS: Windows 10 x64
- Compiler: gcc 10.2.0 mingw64

**To Reproduce**
1. `./vcpkg install devil`
2. Try to build a project with ILUT
Somewhere in the C file:
```
#include <IL/il.h>
#include <IL/ilut.h>
```
Somewhere in the CMake file:
```
find_package(DevIL REQUIRED)
target_link_libraries(main PRIVATE ${IL_LIBRARIES} PRIVATE ${ILUT_LIBRARIES})
```
3. 

**Failure logs** 
```
PS S:\c\C\compute_test\build> make
[ 50%] Building C object CMakeFiles/compute_test.dir/main.c.obj
In file included from S:\c\C\compute_test\main.c:11:
C:/src/vcpkg/installed/x64-windows/include/IL/ilut.h:100:11: fatal error: IL/ilut_config.h: No such file or directory
  100 |  #include <IL/ilut_config.h>
      |           ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles\compute_test.dir\build.make:76: CMakeFiles/compute_test.dir/main.c.obj] Error 1
make[1]: *** [CMakeFiles\Makefile2:82: CMakeFiles/compute_test.dir/all] Error 2
make: *** [Makefile:90: all] Error 2
```

**Additional context**
This issue goes away when I copy `ilut_config.h` from `DevIL/include/IL` into `vcpkg/installed/x64-windows/include/IL`.
It seems like upon installing DevIL, this file fails to be copied.

**Comment by PhoebeHui** [comment]
@chaquator, thanks for reporting this issue!

It looks the headers hasn't been installed, see https://github.com/DentonW/DevIL/blob/master/DevIL/src-ILUT/CMakeLists.txt#L102, could you also report an issue to Upstream?

**Comment by PhoebeHui** [comment]
@chaquator, I have submitted a PR to fix this, btw, I have already report this issue to Upstream https://github.com/DentonW/DevIL/issues/96

**Comment by chaquator** [comment]
Awesome, thank you so much!
