### ISSUE TITLE
vcpkg CI infrastructure is running out of disk space

### ISSUE THREAD

**Issue by BillyONeal** [microsoft/vcpkg#18379]
Consider this recent build: https://dev.azure.com/vcpkg/public/_build/results?buildId=54682&view=logs&j=821e2c31-c252-5a5c-eeb9-89df78f2f610&t=a92823a3-8612-55a7-0645-af99349e0762

x64-windows-static ends with:

> Could not copy D:\buildtrees\vectorclass\x64-windows-static.vcpkg_abi_info.txt -> D:\packages\vectorclass_x64-windows-static\share\vectorclass\vcpkg_abi_info.txt: There is not enough space on the disk. (112)

and

> ```
> Starting: Report on Disk Space After Build
> ==============================================================================
> Task         : PowerShell
> Description  : Run a PowerShell script on Linux, macOS, or Windows
> Version      : 2.186.0
> Author       : Microsoft Corporation
> Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell
> ==============================================================================
> Generating script.
> Formatted command: . 'C:\a\2\s\scripts\azure-pipelines\windows\disk-space.ps1'
> ========================== Starting Command Output ===========================
> "C:\Program Files\PowerShell\7\pwsh.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'C:\a\_temp\b3111741-d7ec-4dfb-a4a9-64387e888b79.ps1'"
> 
> Disk Label             Size    Free Space
> ---- -----             ----    ----------
> C:   Windows           127 GiB 82 GiB
> D:   Temporary Storage 400 GiB 0 B
> E:                     0 B     0 B
> 
> Finishing: Report on Disk Space After Build
>  ```

**Comment by BillyONeal** [comment]
(Note D: has no space left in that output)

**Comment by JackBoosY** [comment]
Hmm.. which label should I choose.
