### ISSUE TITLE
How do I ... Build a release version of my binary

### ISSUE THREAD

**Issue by JamesBewley** [microsoft/vcpkg#18376]
This seems like a silly question but I have tried passing options to vcpkg and cmake but my binary always comes out as x64-linux with debug.

How do I get my project to compile with CMAKE_CXX_FLAGS_RELEASE?

This is my process
`cd vcpkg
./bootstrap-vcpkg.bat
./vcpkg install --triplet x64-linux cpprestsdk libmysql paho-mqtt openssl
cd ..
cmake -B build -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=RELEASE
cmake --build build`

An example of the output is:

`james@vm:~/dev$ file build/CMakeFiles/proj.dir/src/PROJ.cpp.o
build/CMakeFiles/proj.dir/src/PROJ.cpp.o: ELF 64-bit LSB relocatable, x86-64, version 1 (SYSV), not stripped
`

**Comment by dg0yt** [comment]
a) Did you try `-DCMAKE_BUILD_TYPE=Release`?  `RELEASE` will use `CMAKE_CXX_FLAGS_RELEASE`, but for cmake commands that compare the type literally, the case may matter - for example for selecting library variants.
b) What do you expect to see `PROJ.cpp.o` with regard to the build type? It is not an installed executable.
c) You may set environment variable `VERBOSE=1` when you want to see verbose output from `cmake --build build`.

This seems to be mostly CMake aspects, not vcpkg aspects.

**Comment by JamesBewley** [comment]
Apologies for spamming this project, it is all to do with CMake (a port from msbuild).  The verbose build prints the build command and -DCMAKE_BUILD_TYPE=Release does seem to be working but there are some default options that are conflicting with my own.

Thanks for pointing me in the right direction
