### ISSUE TITLE
[New Port Request] Emscripten

### ISSUE THREAD

**Issue by DougRogers** [microsoft/vcpkg#18372]
Library name: Emscripten 

Library description: Emscripten compiles C and C++ to WebAssembly using LLVM and Binaryen. Emscripten output can run on the Web, in Node.js, and in wasm runtimes.

Source repository URL:https://github.com/emscripten-core/emscripten

Project homepage (if different from the source repository):

This is required by Qt to run apps in a browser.
 https://doc.qt.io/qtcreator/creator-setup-webassembly.html

It is supported by other package installers.

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
