### ISSUE TITLE
[protobuf] update to v3.17.3

### ISSUE THREAD

**Issue by kokulshan** [microsoft/vcpkg#18382]
Library name: protobuf [repo](https://github.com/protocolbuffers/protobuf)

New version number: v3.17.3

Other information that may be useful (release notes, etc...)

See https://github.com/protocolbuffers/protobuf/releases/tag/v3.17.3

The version on vcpkg is a few versions behind at the 3.15.x series.

**Comment by PhoebeHui** [comment]
Please update to v3.18.0 https://github.com/protocolbuffers/protobuf/releases/tag/v3.18.0.
