### ISSUE TITLE
install cpprestsdk occurs an error with ninja-win1.7.2

### ISSUE THREAD

**Issue by lazycoding** [Microsoft/vcpkg#1838]
download ninja-win 1.7.2  occurs an error

**Comment by ras0219-msft** [comment]
Hi @lazycoding, can you please post the full error message along with the version of vcpkg you're using? (run `vcpkg version`)

**Comment by lazycoding** [comment]
Vcpkg package management program version 0.0.88-2017-09-13-263466642face5485d50bccb60b45e774fe31fd9

I had tried it out， the download url of ninja-win 1.7.2 became invalid

**Comment by wangli28** [comment]
Please open a new issue if this is still a problem for you.
