### ISSUE TITLE
[otl] Wrong SHA512

### ISSUE THREAD

**Issue by powel-jeh** [microsoft/vcpkg#18396]
**Host Environment**
- OS: whichever

**To Reproduce**
```
curl -sL http://otl.sourceforge.net/otlv4_40455.zip | sha512sum 
2d5c52af3eafdd93bf7c651de218607b8985acc1fce279d48d9bf58ecf8a012332c8d0b9a33223a6449f343134211e2d7c5412b71efb36ba484bda754e1afc45  -
```
Compare vs `
d1f777dea53f4451616ef628680d070db1fe53683571bd509f58dba9c1e64fe6caa8a81d2f47876c2128af701ba19dc2e9c5612a57232efca3ad084843f272b6` in portfile.

**Comment by PhoebeHui** [comment]
@powel-jeh, thanks for reporting this issue!

otl has been updated to 40463 with correct hash in vcpkg, please get latest source and try again.
