### ISSUE TITLE
Error: Building package opencv4:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by steelONIONknight** [microsoft/vcpkg#18391]
Error: Building package opencv4:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: opencv4:x64-windows
  Vcpkg version: 2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9

here is my log: [config-x64-windows-out.log](https://gist.github.com/steelONIONknight/d0e0bed940639ddedf9fe3c5957e3f4b)
thanks.

**Comment by walbourn** [comment]
I don't see any error in the config log. Is there additional error output here missing from your issue description?

FWIW, using VS 2019 16.10 I'm able to successfully run ``vcpkg install opencv4:x64-windows``.

**Comment by NancyLi1013** [comment]
Hi @steelONIONknight 

Thanks for posting this issue. Could you please describe what problem you encountered in `opecv4`?

As @walbourn said above, we cannot found any error in the attachment. Thanks for your help to focus on this issue. @walbourn

**Comment by NancyLi1013** [comment]
Closing this issue for now since there is no response for a long time. Please provide output information on the command windows and the related log if this is still a problem for you.
