### ISSUE TITLE
Port of gtkmm

### ISSUE THREAD

**Issue by mateka** [Microsoft/vcpkg#1839]
There is gtk port in vcpkg, so maybe someone could also port [gtkmm](https://www.gtkmm.org/en/)?

**Comment by mateka** [comment]
I would try to do port myself, but I have one problem. Some sources for *mm libraries are generated. For stable releases, there are some source packages with source files already generated. For unstable snapshots of repository, somebody have to generate missing sources (with unix tools). For me, expecting unix tools on vcpkg user's machine is not a good solution.

Now, in vcpkg there are stable versions of gtk+ libraries, but libsig++ is in unstable version. There are three choices:
1. Vcpkg sould support ports of one library in many versions.
2. Libsig++ is reverted to stable release.
3. All gtk+ libraries are upgraded to unstable versions and maintainers of gtk+ and gtkmm libraries maintain libraries and generated sources.

In my opinion, most sensible one is to revert libsig++ to stable release. Will it be ok?

**Comment by ras0219-msft** [comment]
I agree with your logic, with the possible exception that if libsigpp will work in its current version then we keep it prerelease.

In the future, I definitely agree we should strive to keep everything at a stable release; however since we've already "paid" for the instability of the current libsigpp version it seems reasonable to keep it as-is if possible.

**Comment by arthur-tacca** [comment]
Actually, several vcpkg ports already install the MSYS2 build of Unix tools, and there's a shared CMake command to do it: [`vcpkg_acquire_msys`](https://vcpkg.readthedocs.io/en/latest/maintainers/vcpkg_acquire_msys/). Do it would be possible to have the head version of gtkmm and gtk+ (like option 3) without the maintainers of those libraries having to generate the sources.

**Comment by mateka** [comment]
My gtkmm port was merged, so I am closing this issue.

**Comment by sourceskyboxer** [comment]
And it failed if I use x64-windows-static glib failed build. :/
How do I fix it? If I want embed gtk libs in executable without error messages if dll could not found.

**Comment by mateka** [comment]
When I have been creating gtkmm port, I have used solution created by gtkmm project. This solution had only dll build. If You want static build, You have to update ports of *mm libs.
