### ISSUE TITLE
list of packages

### ISSUE THREAD

**Issue by VikingExplorer** [Microsoft/vcpkg#1840]
Is there any way to get a live list of packages, other than CLI vcpkg search?

Not only is CLI inconvenient, the description is cut off.

This shouldn't be that hard since presumably, these packages are in the database somewhere. Name of package should be a link to the project.

**Comment by ras0219-msft** [comment]
Thanks for pointing this out!

There are two ways that might improve the situation for you immediately. One is to pass `--x-full-desc` to search, which stop cutting off the description (but they can be _very_ long, so this will ruin the table formatting). The other is to simply do a findstr or grep inside the `ports\` directory; all the information for package X is gathered via `ports\X\CONTROL`.

**Comment by VikingExplorer** [comment]
This is now available from: https://repology.org/metapackages/

**Comment by pkeir** [comment]
I think the redirection on that repology URL might have changed. Try here: https://repology.org/repository/vcpkg

**Comment by dg0yt** [comment]
> I think the redirection on that repology URL might have changed. Try here: https://repology.org/repository/vcpkg

Now the packages are listed on https://vcpkg.io/en/packages.html.
