### ISSUE TITLE
Upgraded packages and then having a failed build leaves all packages uninstalled

### ISSUE THREAD

**Issue by twindan** [microsoft/vcpkg#18402]
****

Steps to reproduce:

1. Have out of date packages
2. Do a "vcpkg upgrade --no-dry-run"
3. Watch vcpkg uninstall all of the packages for some reason
3. Have the build fail for some reason
4. Watch all of the installed packages disappear and there is no way to know what packages were previously installed

**Proposed solution**
Since rolling back would be difficult (and some of the upgrades might have already been applied), it would be nice if VCPkg could generate a list of packages that were being installed as part of the upgrade, so if a failure happens, we could run a command to retry/continue the upgrade.

**Describe alternatives you've considered**

**Additional context**
Build failures can happen for various reasons (my specific one in this case was I was using an alternative shell, but I have seen it before where a bug got introduced into a package.)

**Comment by JackBoosY** [comment]
Can you provide the details?
We know there are some bugs in `upgrade`, but I must know which it is.

**Comment by twindan** [comment]
In this specific case, the build failure was my fault (I use TCC instead of CMD for my primary shell and it occasionally has compatibility problems with some build scripts due to esoteric differences in edge case handling).  Hence, the upgrade could have succeeded if I ran CMD first. The problem I had is that the upgrade process seems to uninstall all of the existing builds and then install the latest versions. If something happens between the uninstall and the re-install, the list of installed packages is lost. 

The same thing would presumably happen if some background upgrader decided it was a good time to install something and reboot the machine in the middle of an package upgrade. The upgrade process would abort and there does not seem to be any way to restart it without manually trying to remember which packages I had installed and re-installing them.

**Comment by JackBoosY** [comment]
Please track https://github.com/microsoft/vcpkg/issues/18402.

**Comment by twindan** [comment]
#18402 is this issue. Did you mean to include a different issue?

**Comment by JackBoosY** [comment]
Sorry, please track #4360 or https://github.com/microsoft/vcpkg/discussions/17922.
