### ISSUE TITLE
[New Port Request] <pmp-library>

### ISSUE THREAD

**Issue by XuRongYan** [microsoft/vcpkg#18401]
Library name: pmp-library

Library description: The Polygon Mesh Processing Library is a modern C++ open-source library for processing and visualizing polygon surface meshes. 

Source repository URL: https://github.com/pmp-library/pmp-library/

Project homepage (if different from the source repository): http://www.pmp-library.org/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
