### ISSUE TITLE
Dependency error when porting (minizip[bzip2])

### ISSUE THREAD

**Issue by playgithub** [microsoft/vcpkg#18416]
When porting `xlsxio`, link error as below, but minizip[bzip2] as a dependency has been installed with the same triplet
```
minizip.lib(unzip.c.obj) : error LNK2019: unresolved external symbol __imp_BZ2_bzDecompressInit referenced in function unzOpenCurrentFile3
minizip.lib(unzip.c.obj) : error LNK2019: unresolved external symbol __imp_BZ2_bzDecompress referenced in function unzReadCurrentFile
minizip.lib(unzip.c.obj) : error LNK2019: unresolved external symbol __imp_BZ2_bzDecompressEnd referenced in function unzCloseCurrentFile
xlsxio_read.dll : fatal error LNK1120: 3 unresolved externals
```

`vcpkg.json` for port `xlsxio`
```json
{
  "name": "xlsxio",
  "version-string": "commit-e3acace39e5fb153f5ce3500a4952c2bf93175bd",
  "port-version": 1,
  "description": "Cross-platform C library for reading values from and writing values to .xlsx files",
  "homepage": "https://github.com/brechtsanders/xlsxio",
  "dependencies": [
    "expat",
    {
      "name": "minizip",
      "features": [
        "bzip2"
      ]
    }
  ],
  "features": {
    "libzip": {
      "description": "use libzip instead of minizip",
      "dependencies": [
        {
          "name": "libzip",
          "features": [
            "bzip2"
          ]
        }
      ]
    },
    "wide": {
      "description": "also build utf-16 library"
    }
  }
}
```

**Comment by playgithub** [comment]
Problem located
https://github.com/microsoft/vcpkg/issues/18448

**Comment by Neumann-A** [comment]
> Problem located

not really. Reopen this and close #18448

**Comment by playgithub** [comment]
> > Problem located
> 
> not really. Reopen this and close #18448

I think it's a bug of minizip port on Windows.
I've checked the files in folder `installed`, they are not patched according to bzip2, though files in folder `packages` are patched.

**Comment by playgithub** [comment]
> > Problem located
> 
> not really. Reopen this and close #18448

Alright, compiling succeeds, but linking fails.

**Comment by Neumann-A** [comment]
> Alright, compiling succeeds, but linking fails.

Two reasons:
a) no `find_dependency(BZip2)` in the `minizipConfig.cmake`
a) no linkage against the `BZip2` target in the `minizipTargets.cmake`

**Comment by playgithub** [comment]
> > Alright, compiling succeeds, but linking fails.
> 
> Two reasons:
> a) no `find_dependency(BZip2)` in the `minizipConfig.cmake`
> a) no linkage against the `BZip2` target in the `minizipTargets.cmake`

I'm not so familiar with `cmake` and `vcpkg`. Hope someone to fix it.
I'm learning CMake now.
Thanks

**Comment by JackBoosY** [comment]
Please test my changes in https://github.com/microsoft/vcpkg/pull/18472.

Thanks.

**Comment by playgithub** [comment]
> Please test my changes in #18472.
> 
> Thanks.

It has passed all the checks, I'll test it.
Thanks

**Comment by playgithub** [comment]
@JackBoosY
I've tested, still the same probem.

**Comment by JackBoosY** [comment]
@playgithub It passed on my machine.

**Comment by playgithub** [comment]
> @playgithub It passed on my machine.
> Can you please also provide the related logs?

The logs are exactly the same.
https://dev.azure.com/vcpkg/public/_build/results?buildId=55036&view=logs&jobId=c7e67a25-2047-5d01-7913-57de0573f534&j=c7e67a25-2047-5d01-7913-57de0573f534

**Comment by JackBoosY** [comment]
I can confirm this issue was fixed.

**Comment by playgithub** [comment]
> I can confirm this issue was fixed.

The PR (https://github.com/microsoft/vcpkg/pull/18438) doesn't pass the tests in CI.
```
minizip.lib(unzip.c.obj) : error LNK2019: unresolved external symbol __imp_BZ2_bzDecompressInit referenced in function unzOpenCurrentFile3
minizip.lib(unzip.c.obj) : error LNK2019: unresolved external symbol __imp_BZ2_bzDecompress referenced in function unzReadCurrentFile
minizip.lib(unzip.c.obj) : error LNK2019: unresolved external symbol __imp_BZ2_bzDecompressEnd referenced in function unzCloseCurrentFile
xlsxio_read.dll : fatal error LNK1120: 3 unresolved externals
```
