### ISSUE TITLE
Install cpprestsdk failed with Visual Studio 2017

### ISSUE THREAD

**Issue by AlexanderSerashov** [Microsoft/vcpkg#1841]
Hi,
I've tried to do as guys said [here](https://github.com/Microsoft/cpprestsdk/issues/424) 
the command 'vcpkg install cpprestsdk --head' doesn't work as expected.

Logs:
[config-x86-windows-rel-err.txt](https://github.com/Microsoft/vcpkg/files/1310989/config-x86-windows-rel-err.txt)
[config-x86-windows-rel-out.txt](https://github.com/Microsoft/vcpkg/files/1310990/config-x86-windows-rel-out.txt)

I have VS2015 and VS2017 installed side-by-side.

Could someone help me?

**Comment by ras0219-msft** [comment]
I've checked in a fix to the cpprestsdk master branch, could you try once again?

**Comment by AlexanderSerashov** [comment]
Thanks a lot! It works!
