### ISSUE TITLE
One project detects vcpkg libraries others donot

### ISSUE THREAD

**Issue by Umair-khalidkhan** [microsoft/vcpkg#18426]
**Describe the bug**
the first ever dll I complied on VS 2017 after downloaded external dependancies from vcpkg, recognised and found the vcpkg libaries after applying the integrate install command, however no other file or project detects vcpkg libaries e.g: curl. Which is more annoying since once place is completely finds it the other fails to, I even recompiled the first dll with exactly same code and files, even that does not seem to find vcpkg files. 

**Environment**
- OS: windows 10
- IDE: MS VS 2017 community
- Compiler: do not know sorry

**To Reproduce**
1. ./vcpkg install library
2. ./vcpkg integrate install
3.  create project that uses said libary and check if VS finds it.
4. create another project same or different, and whether this time VS finds library
Repro code when

**Expected behavior**
library to be found and included in every project and file

**Failure logs** 
attached SS of error
-(please attached failure logs)

**Additional context**
I am already using a 3rd party library called binacpp, it has external dependancies which i downloaded via vcpkg
<img width="906" alt="error" src="https://user-images.githubusercontent.com/42065308/121815985-7713a600-cc92-11eb-99b8-70fd53f25319.PNG">

**Comment by JackBoosY** [comment]
Which triplet did you install? And please also run `./vcpkg integrate project`.

**Comment by JackBoosY** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
