### ISSUE TITLE
Virus in package!!?? (or compiler??)

### ISSUE THREAD

**Issue by DanL1234** [microsoft/vcpkg#18429]
**Describe the bug**
ran: 
.\vcpkg install mlpack:x86-windows
Build was interrupted at the same time as the powershell window reported an in issue:

********************************************************************
Powershell text (abbreviated):
...
Installing package vcpkg-gfortran[core]:x86-windows... done
Elapsed time for package vcpkg-gfortran:x86-windows: 1.353 min
Starting package 4/81: lapack-reference:x86-windows
Building package lapack-reference[blas-select,core,noblas]:x86-windows...
-- Downloading https://github.com/Reference-LAPACK/lapack/archive/v3.8.0.tar.gz -> Reference-LAPACK-lapack-v3.8.0.tar.gz...
-- Extracting source C:/src/vcpkg32/downloads/Reference-LAPACK-lapack-v3.8.0.tar.gz
-- Using source at C:/src/vcpkg32/buildtrees/lapack-reference/src/v3.8.0-954f10683f.clean
-- The Fortran compiler identification is unknown
-- No Fortran compiler found on the PATH. Using MinGW gfortran!
-- Using msys root at C:/src/vcpkg32/downloads/tools/msys2/51cfb821b1485bc1
-- Found external ninja('1.10.2').
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
    Command failed: ninja -v
    Working Directory: C:/src/vcpkg32/buildtrees/lapack-reference/x86-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\src\vcpkg32\buildtrees\lapack-reference\config-x86-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:323 (vcpkg_execute_required_process)
  ports/lapack-reference/portfile.cmake:63 (vcpkg_configure_cmake)
  scripts/ports.cmake:139 (include)

Error: Building package lapack-reference:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: lapack-reference:x86-windows
  Vcpkg version: 2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9

Additionally, attach any relevant sections from the log files above.

********************************************************************
Bitdefender: "Successfully blocked infected file"

"
Feature:
Antivirus

The file C:\src\vcpkg32\buildtrees\lapack-reference\x86-windows-rel\CMakeFiles\3.20.1\CompilerIdC\a.exe is infected with Gen:Variant.Fugrafa.140594. The threat has been successfully blocked, your device is safe.
"

**Environment**
- OS: Windows 10
- Compiler: ?

**To Reproduce**
1. ./vcpkg install mlpack:x86-windows (with bitdefender running)

**Expected behavior**
All packages compiled & installed / available for integration.

**Failure logs** 
Logs in text above

**Additional context**
May be misdetected?  Need a confirmation from the gods of IT.

**Comment by timmeh87** [comment]
possibly relevant due to a similar detection:

https://github.com/microsoft/vcpkg/issues/8118

**Comment by NancyLi1013** [comment]
Hi @DanL1234 

Thanks for posting this issue. Could you please try to disable virus on your machine and rebuild this port?

**Comment by DanL1234** [comment]
Hi Nancy,

I gave my src folder an exception within Bitdefender and rebuilt okay.
I also then had access to the files "a.exe" in both release and debug builds (they both were being flagged), so used https://www.fortiguard.com/faq/onlinescanner to test each individually. As expected, the files were shown as clean.
Finally, I reported both files to BitDefender as false-positives.

Cheers,
Dan

**Comment by NancyLi1013** [comment]
Glad to hear that. Please let me know if you still have other problems about this.

**Comment by NancyLi1013** [comment]
Closing this issue for now. Please feel free to reopen this issue if it is still a problem for you.
