### ISSUE TITLE
Tried everything, vcpkg works with CMake but paths fail in Visual Studio 2019 on correct config

### ISSUE THREAD

**Issue by Schala** [microsoft/vcpkg#18428]
Sorry to file another consecutive issue, but as the title says, vcpkg works with CMake but in VS2019, even with x64 and Debug correctly set, no include or lib paths are found.

Tell me if I slipped up on the steps:
- vcpkg dir is C:\vcpkg
- VCPKG_DEFAULT_TRIPLET set to x64-windows (VS2019 reflects this, too)
- vcpkg install boost
- vcpkg integrate install
- CMake GUI, I have 'CMAKE_TOOLCHAIN_FILE' set to the vcpkg.cmake file path and yes, it does import the config options from it. Again, Boost's include dir is detected
- Open in VS2019, config is set to Debug x64, tried to build, but it fails to find the Boost headers I used.

**Comment by PhoebeHui** [comment]
@Schala, I want to confirm the last step, do you open the project that generate by CMake in above steps via VS2019? How do you use boost in your project?

If use it with cmake, you need to add the following code in your CMakLists.txt file:
```
   find_package(Boost REQUIRED [COMPONENTS <libs>...])
   target_link_libraries(main PRIVATE ${Boost_LIBRARIES})
   target_include_directories(main PRIVATE ${Boost_INCLUDE_DIRS})
```
if use it with msbuild:
You only need to set configuration to Debug x64 by default.

**Comment by Schala** [comment]
I do. I open the .sln file, check that the config is x64 and Debug on "ALL_BUILD", and hit build. I currently only use Boost.Asio, a header-only component.

**Comment by Schala** [comment]
Alright, figured it out. I was missing the `target_include_directories` bit. I assumed since they were in my vcpkg include path that it was unnecessary.
