### ISSUE TITLE
[yasm-tool] build failure ( all ports failing )

### ISSUE THREAD

**Issue by YoungBlood01** [microsoft/vcpkg#18433]
**Host Environment**
- OS: Windows 10
- Compiler: visual studio 2019 16.10.1

**To Reproduce**
.\vcpkg --triplet x86-windows install yasm-tool

**Failure logs** 
Detecting compiler hash for triplet x64-windows...
Detecting compiler hash for triplet x86-windows...
Could not locate cached archive: C:\Users\brody\AppData\Local\vcpkg\archives\c6\c6e03165c846e61635df4879070ed42c0344d0aa.zip
Could not locate cached archive: C:\Users\brody\AppData\Local\vcpkg\archives\7c\7cc6964bbf071bad29ab38b4433b787121457832.zip
Could not locate cached archive: C:\Users\brody\AppData\Local\vcpkg\archives\e5\e523010c0e48b0cc7cc11345625d3e820a90a125.zip
Starting package 1/3: yasm-tool:x64-windows
Building package yasm-tool[core]:x64-windows...
-- Using C:/Development/vcpkg/downloads/yasm-yasm-009450c7ad4d425fa5a10ac4bd6efbd25248d823.tar.gz
-- Cleaning sources at C:/Development/vcpkg/buildtrees/yasm-tool/src/d25248d823-818ed1bbf4.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Development/vcpkg/downloads/yasm-yasm-009450c7ad4d425fa5a10ac4bd6efbd25248d823.tar.gz
-- Using source at C:/Development/vcpkg/buildtrees/yasm-tool/src/d25248d823-818ed1bbf4.clean
-- Installing: C:/Development/vcpkg/packages/yasm-tool_x64-windows/share/yasm-tool/copyright
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
    Command failed: ninja -v
    Working Directory: C:/Development/vcpkg/buildtrees/yasm-tool/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\Development\vcpkg\buildtrees\yasm-tool\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:323 (vcpkg_execute_required_process)
  ports/yasm-tool/portfile.cmake:26 (vcpkg_configure_cmake)
  scripts/ports.cmake:139 (include)

Error: Building package yasm-tool:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: yasm-tool:x64-windows
  Vcpkg version: 2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/6644850/config-x64-windows-out.log)
[CMakeOutput.log](https://github.com/microsoft/vcpkg/files/6644854/CMakeOutput.log)
[CMakeError.log](https://github.com/microsoft/vcpkg/files/6644856/CMakeError.log)

**Additional context**
This error is happening with every port I try and install, I'm sure it is something wrong on my side but I have no idea how to fix this. I have tried updating and reinstalling vcpkg and visual studio but no luck yet. Any help would be appreciated.

**Comment by PhoebeHui** [comment]
@YoungBlood01, it looks something wrong in windows sdk, it could not find the mt, could you reinstall/repair windows sdk and try again?

```
 cmd.exe /C "cd . && C:\Development\vcpkg\downloads\tools\cmake-3.20.2-windows\cmake-3.20.2-windows-i386\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_ba187.dir --rc=rc --mt=CMAKE_MT-NOTFOUND --manifests  -- C:\PROGRA~2\MIB055~1\2019\COMMUN~1\VC\Tools\MSVC\1429~1.300\bin\Hostx64\x64\link.exe /nologo CMakeFiles\cmTC_ba187.dir\testCCompiler.c.obj  /out:cmTC_ba187.exe /implib:cmTC_ba187.lib /pdb:cmTC_ba187.pdb /version:0.0 /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    RC Pass 1: command "rc /fo CMakeFiles\cmTC_ba187.dir/manifest.res CMakeFiles\cmTC_ba187.dir/manifest.rc" failed (exit code 0) with the following output:
    The system cannot find the file specified
    ninja: build stopped: subcommand failed.
```

**Comment by PhoebeHui** [comment]
@YoungBlood01, does this still be a problem for you?

**Comment by PhoebeHui** [comment]
@YoungBlood01, please reopen this issue if it still be a problem for you.
