### ISSUE TITLE
What's the best solution for private libs, and be ready to do a PR for some private lib one day?

### ISSUE THREAD

**Issue by playgithub** [microsoft/vcpkg#18437]
e.g. I have a lib that encapsulating small functionalities (e.g. format text in a human friendly way, http downlader by encapsulating libcurl), which are not suitable for a PR to the official vcpkg repository.

Now I fork vcpkg, treat local master branch as the main branch, i.e. merge my private libs to the local master branch and pull microsoft/vcpkg to the local master branch. The problem is that when I want to do a PR, the PR might be polluted by the privacte libs.

Questions
1. A clean branch (i.e. mirror of microsoft/vcpkg master) is needs for PR, right?
2. If I want to do a PR for a private lib, I can't merge it from the branch with private libs, instead I have to use something like copy/paste/git add/git commit to the clean branch for PR, right? Is there a better solution?

**Comment by autoantwort** [comment]
1. Yes. 
2. I always have a clean master branch that is in sync with vcpkg/master and always create new branches when I want to create a PR. Additionally I have a branch with local changes that I use in a project (or with private ports) and regularly merge master into this branch. But now you can create a own registry and use this feature instead: https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/registries.md and https://github.com/microsoft/vcpkg/blob/master/docs/users/registries.md

**Comment by playgithub** [comment]
> 2. I always have a clean master branch that is in sync with vcpkg/master and always create new branches when I want to create a PR. Additionally I have a branch with local changes that I use in a project (or with private ports) and regularly merge master into this branch. But now you can create a own registry and use this feature instead: https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/registries.md and https://github.com/microsoft/vcpkg/blob/master/docs/users/registries.md

I've tried to read it, the concepts are not intuitive for the simple functions.
I'll try `conan`.
Thanks all the same.

**Comment by playgithub** [comment]
> 2. I always have a clean master branch that is in sync with vcpkg/master and always create new branches when I want to create a PR. Additionally I have a branch with local changes that I use in a project (or with private ports) and regularly merge master into this branch. But now you can create a own registry and use this feature instead: https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/registries.md and https://github.com/microsoft/vcpkg/blob/master/docs/users/registries.md

I've tried to read it, the concepts are not intuitive for the simple functions.
I'll try `conan`.
Thanks
