### ISSUE TITLE
unable to use wxWidgets

### ISSUE THREAD

**Issue by wvvvvvv** [Microsoft/vcpkg#1843]
Hi@all,

I'm using vcpkg the first time and it's really great. Most of the frameworks I need are working. However, I have some troubles using wxWidgets at Windows 7, Visual Studio 2017, x64.

I have installed wxwidgets:x64-windows and a user-wide integration 

Then I would like to build my Projectfile using cmake3.9.2 Gui

For that I have insert FIND_PACKAGE(wxWidgets REQUIRED) in my CMakeLists.txt

Before cmake configuration I specify the toolchain for cross-compiling (vcpkg-master/scripts/buildsystems/vcpkg.cmake). Afterwards, during configuration I'm getting the error "Could NOT find wxWidgets (missing: wxWidgets_LIBRARIES  wxWidgets_INCLUDE_DIRS)"

CMake Error at C:/Program Files/CMake/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find wxWidgets (missing: wxWidgets_LIBRARIES  wxWidgets_INCLUDE_DIRS)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.9/Modules/FindwxWidgets.cmake:954 (find_package_handle_standard_args)
  D:/libs/lpmip/vcpkg-master/scripts/buildsystems/vcpkg.cmake:145 (_find_package)
  CMakeLists.txt:139 (FIND_PACKAGE)

Please, can someone help me!

Thanks

**Comment by IronPark** [comment]
I think `FIND_PACKAGE (wxWidgets)` does not seem to work properly for vcpkg.
I have experienced similar problems, and this is the solution I present.

```cmake
###wxWidgets
if(VCPKG_TOOLCHAIN)
    add_definitions(-D_UNICODE -DUNICODE -DWXUSINGDLL -DwxUSE_GUI=1 -D__WXMSW__ -DWINVER=0x0500)
    find_path(wxWidgets_INCLUDE_DIR msvc)
    include_directories(${wxWidgets_INCLUDE_DIR})
    set(vcpkg_lib_path ${_VCPKG_INSTALLED_DIR}/_target_/_mode_/lib)
    string(REGEX REPLACE "_target_" "${VCPKG_TARGET_TRIPLET}" vcpkg_lib_path ${vcpkg_lib_path})

    if("${CMAKE_BUILD_TYPE}" MATCHES "Debug")
        #debug lib
        string(REGEX REPLACE "_mode_" "debug" vcpkg_lib_path ${vcpkg_lib_path})
        link_libraries(
                ${vcpkg_lib_path}/wxmsw31ud_core.lib
                ${vcpkg_lib_path}/wxbase31ud.lib)
    else()
        #release lib
        string(REGEX REPLACE "_mode_/" "" vcpkg_lib_path ${vcpkg_lib_path})
        link_libraries(
                ${vcpkg_lib_path}/wxmsw31u_core.lib
                ${vcpkg_lib_path}/wxbase31u.lib)
    endif()
endif()

add_executable(wxIDKManager WIN32 main.cpp)
```

This code does not copy the dll file. Please copy it directly from "vcpkg/buildtrees/wxwidgets/src/wxWidgets-3.1.0/lib"

I hope this helps you.

**Comment by Type1J** [comment]
Why are the .dll files not installed in (for x86-windows for example) `C:\vcpkg\installed\x86-windows\bin`?

**Comment by Sereglaith** [comment]
@IronPark I had trouble getting this to work as well, and your comment was very helpful in getting this sorted out.  I thought I would post my solution as well since it differed a little.

```add_definitions(-D_UNICODE -DUNICODE -DWXUSINGDLL -DwxUSE_GUI=1 -D__WXMSW__)
if("${CMAKE_BUILD_TYPE}" MATCHES "Debug")
	add_definitions(-D_DEBUG)
	include_directories(${_VCPKG_INSTALLED_DIR}/x64-windows/debug/lib/mswud)
	set(wxWidgets_LIB_DIR ${_VCPKG_INSTALLED_DIR}/x64-windows/debug/lib)
	set(wxWidgets_LIBRARIES
		${wxWidgets_LIB_DIR}/wxbase31ud_net.lib
		${wxWidgets_LIB_DIR}/wxmsw31ud_core.lib
		${wxWidgets_LIB_DIR}/wxbase31ud.lib
		winmm comctl32 oleacc rpcrt4 shlwapi version wsock32
	)
elseif("${CMAKE_BUILD_TYPE}" MATCHES "Release")
	include_directories(${_VCPKG_INSTALLED_DIR}/x64-windows/lib/mswu)
	set(wxWidgets_LIB_DIR ${_VCPKG_INSTALLED_DIR}/x64-windows/lib)
	set(wxWidgets_LIBRARIES
		${wxWidgets_LIB_DIR}/wxbase31u_net.lib
		${wxWidgets_LIB_DIR}/wxmsw31u_core.lib
		${wxWidgets_LIB_DIR}/wxbase31u.lib
		winmm comctl32 oleacc rpcrt4 shlwapi version wsock32
	)
endif()

add_executable(${PROJECT_NAME} ${EXE_FLAG} ${SOURCES})
target_link_libraries(${PROJECT_NAME} ${wxWidgets_LIBRARIES})
```

**Comment by Clocktown** [comment]
Even after the fix by @Sereglaith I still had problems. I added more include directories:
```cmake
  add_definitions(-D_UNICODE -DUNICODE -DWXUSINGDLL -DwxUSE_GUI=1 -D__WXMSW__)
  if("${CMAKE_BUILD_TYPE}" MATCHES "Debug")
    add_definitions(-D_DEBUG)
    include_directories(${_VCPKG_INSTALLED_DIR}/x64-windows/debug/lib/mswud)
    include_directories(${_VCPKG_INSTALLED_DIR}/x64-windows/include)
    set(wxWidgets_LIB_DIR ${_VCPKG_INSTALLED_DIR}/x64-windows/debug/lib)
    set(wxWidgets_LIBRARIES
      ${wxWidgets_LIB_DIR}/wxbase31ud_net.lib
      ${wxWidgets_LIB_DIR}/wxmsw31ud_core.lib
      ${wxWidgets_LIB_DIR}/wxbase31ud.lib
      winmm comctl32 oleacc rpcrt4 shlwapi version wsock32
    )
  elseif("${CMAKE_BUILD_TYPE}" MATCHES "Release")
    include_directories(${_VCPKG_INSTALLED_DIR}/x64-windows/lib/mswu)
    include_directories(${_VCPKG_INSTALLED_DIR}/x64-windows/include)
    set(wxWidgets_LIB_DIR ${_VCPKG_INSTALLED_DIR}/x64-windows/lib)
    set(wxWidgets_LIBRARIES
      ${wxWidgets_LIB_DIR}/wxbase31u_net.lib
      ${wxWidgets_LIB_DIR}/wxmsw31u_core.lib
      ${wxWidgets_LIB_DIR}/wxbase31u.lib
      winmm comctl32 oleacc rpcrt4 shlwapi version wsock32
    )
  endif()
```
Anyhow, the package needs quite a bit of fixing.

PS.: You will also need something like this:
```cmake
if(WIN32)
  set_property(TARGET wxtest APPEND PROPERTY LINK_FLAGS "/ENTRY:WinMainCRTStartup")
endif()
```
If you are using `wxIMPLEMENT_APP` instead of `wxIMPLEMENT_APP_CONSOLE`. But this is unrelated to VCPKG, just wanted to add this here in case someone has problems.

**Comment by JackBoosY** [comment]
Hi @wvvvvvv , thanks for reporting this issue!
Please open a new issue if this is still a problem for you.
Thx.

**Comment by rkitover** [comment]
This is still broken.

**Comment by Type1J** [comment]
@rkitover Yes, it's still broken. I've been using workarounds presented in this thread, but they break every time that I update vcpkg. I may just remove wxWidgets and use my own abstractions.

**Comment by rkitover** [comment]
@Type1J I was commenting on the premature closure. I am using these workarounds as well, and I've expanded on them, if you want to take a look at my stuff it's here:

https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/src/wx/CMakeLists.txt#L92

This has been generally working for me, more or less.

**Comment by JackBoosY** [comment]
Maybe fixed by https://github.com/microsoft/vcpkg/pull/17111
