### ISSUE TITLE
[mp3lame:x64-osx] build failure

### ISSUE THREAD

**Issue by Greisby** [microsoft/vcpkg#18441]
**Host Environment**
- OS: Mac OS Big Sur
- Compiler: Xcode 12.5
- vcpkg repository on a mounted samba share
- Macports installed

**To Reproduce**
`./vcpkg install mp3lame`

**Failure logs** 
-- Building x64-osx-dbg
… then waiting forever (I interrupted after the week-end).

**Additional context**
Waits forever for the deletion of a (non-existing!) file. 
Last logs in build-x64-osx-dbg-out.log:
> /bin/sh ../libtool  --tag=CC   --mode=link gcc  -O3 -Wall -fPIC -g -fno-common -version-info 0:0 -export-symbols .././../src/0844b9eadb-a14cfeb202.clean/include/libmp3lame.sym -no-undefined -L/Volumes/Development/Releases/Mac/vcpkg/installed/x64-osx/debug/lib  -o libmp3lame.la -rpath /Volumes/Development/Releases/Mac/vcpkg/installed/x64-osx/debug/lib VbrTag.lo bitstream.lo encoder.lo fft.lo gain_analysis.lo id3tag.lo lame.lo newmdct.lo presets.lo psymodel.lo quantize.lo quantize_pvt.lo reservoir.lo set_get.lo tables.lo takehiro.lo util.lo vbrquantize.lo version.lo mpglib_interface.lo  ../libmp3lame/vector/liblamevectorroutines.la ../mpglib/libmpgdecoder.la -lm 
> libtool: link: Waiting for /Volumes/Development/Releases/Mac/vcpkg/buildtrees/mp3lame/x64-osx-dbg/libmp3lame/../libmp3lame/vector/.libs/liblamevectorroutines.a.lock to be removed
> libtool: link: Waiting for /Volumes/Development/Releases/Mac/vcpkg/buildtrees/mp3lame/x64-osx-dbg/libmp3lame/../libmp3lame/vector/.libs/liblamevectorroutines.a.lock to be removed
*(repeating ad infinitum)*

The problem is that libtool tries to create a hard lock across filesystems, with a wrong logic:
> **while** create hardlink(lock file) failed **do** print "waiting for lock file to be deleted" ; sleep ; **done**

I found a [post](https://lists.gnu.org/archive/html/bug-libtool/2013-06/msg00001.html) describing this problem, but no solution.

I'm new with vcpkg, but I tried to find a workaround to either fix or disable locking for libtool:
- force using Macports' libtool instead of the one of Xcode.
- adding the option **--disable-libtool-lock** to configure in *portfile.cmake*
- patching *configure* to force need_locks=false
- patching *ltmain.sh* to replace *ln* with *cp -n*  
btw, it does not seems to be used.

None of these attempts had any effect.

If anyone has a better understanding of vcpkg build system, libtool's mechanism or on how to build mp3lame on another filesystem than libtool, a workaround would be welcomed!

**Comment by Greisby** [comment]
I succeeded to install it the following way:
- Edit *buildtrees/mp3lame/x64-osx-dbg/libtool* while vcpkg is still configuring x64-osx-rel, and replace **lock_old_archive_extraction=yes** with **lock_old_archive_extraction=no**
- Do the same in *buildtrees/mp3lame/x64-osx-rel/libtool* while x64-osx-deb is building

So the solution is to find the way how to set this variable to no in the vcpkg package.

**Comment by JackBoosY** [comment]
@Neumann-A Should we also add an option `DISABLE_LOCK` to `vcpkg_*_make` to use `--disable-libtool-lock`? Or add an option `DISABLE_PARALLEL`?

**Comment by Neumann-A** [comment]
> Should we also add an option DISABLE_LOCK to vcpkg_*_make to use --disable-libtool-lock? Or add an option DISABLE_PARALLEL?

If it is need. But since the option can simply be passed be the OPTIONS parameter in `vcpkg_configure_make` why add another one? Furthermore the is the new triplet variable which can add those options to all ports if needed.

**Comment by JackBoosY** [comment]
@Neumann-A If this is a common issue, I think we have enough reasons to add it as an option.

**Comment by JackBoosY** [comment]
The function `vcpkg_build_make` already have option `DISABLE_PARALLEL`.

@Greisby  Can you please modify _ports/mp3lame/portfile.cmake_ line 109
from
```cmake
vcpkg_install_make()
```
to
```
vcpkg_install_make(DISABLE_PARALLEL)
```

And try again? thanks.

**Comment by Greisby** [comment]
Hi, it did not change anything.

**Comment by JackBoosY** [comment]
> Hi, it did not change anything.
> I checked _buildtrees/mp3lame/x64-osx-dbg/libtool_, it's still **lock_old_archive_extraction=yes**

Due to parallel construction, there may be a problem that some files are used by multiple build threads or processes at the same time.
If it is disabled, this issue should not occur.
Not sure why.

**Comment by LilyWangLL** [comment]
This issue hasn’t been updated in one month. If someone has new idea, please reopen this issue.
