### ISSUE TITLE
tiff:x86-uwp | BUILD_FAILED

### ISSUE THREAD

**Issue by josbla89** [microsoft/vcpkg#18449]
**Host Environment**
- OS: Windows 10 Home 2004
- Compiler: 2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9

**To Reproduce**
vcpkg install opencv[contrib]:x86-uwp --recurse

**Failure logs** 

Computing installation plan...
The following packages will be built and installed:
    opencv[contrib,core,dnn,jpeg,png,quirc,tiff,webp]:x86-uwp -> 4.5.1
  * opencv4[contrib,core,dnn,jpeg,png,quirc,tiff,webp]:x86-uwp -> 4.5.1#1
  * tiff[core,jpeg,lzma,zip]:x86-uwp -> 4.3.0
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x86-uwp...
Could not locate cached archive: C:\Users\josez\AppData\Local\vcpkg\archives\f1\f1076c274c660bc9c87064715e1570eeb3b76eda.zip
Could not locate cached archive: C:\Users\josez\AppData\Local\vcpkg\archives\a0\a061408a569e00fb86f586fef45f923ca2b02e7b.zip
Could not locate cached archive: C:\Users\josez\AppData\Local\vcpkg\archives\b4\b4ddcc499954c59b41d797f9f3eb03e9e002ebfd.zip
Starting package 1/3: tiff:x86-uwp
Building package tiff[core,jpeg,lzma,zip]:x86-uwp...
-- Using community triplet x86-uwp. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: C:\Users\josez\Documents\Datco\vcpkg\triplets\community\x86-uwp.cmake
-- Using C:/Users/josez/Documents/Datco/vcpkg/downloads/tiff-4.3.0.tar.gz
-- Cleaning sources at C:/Users/josez/Documents/Datco/vcpkg/buildtrees/tiff/src/4.3.0-a2c25e37d6.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/josez/Documents/Datco/vcpkg/downloads/tiff-4.3.0.tar.gz
-- Applying patch cmakelists.patch
-- Applying patch fix-pkgconfig.patch
-- Using source at C:/Users/josez/Documents/Datco/vcpkg/buildtrees/tiff/src/4.3.0-a2c25e37d6.clean
-- Configuring x86-uwp
-- Building x86-uwp-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:146 (message):
    Command failed: C:/Users/josez/Documents/Datco/vcpkg/downloads/tools/cmake-3.20.2-windows/cmake-3.20.2-windows-i386/bin/cmake.exe --build . --config Debug --target install -- /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /m
    Working Directory: C:/Users/josez/Documents/Datco/vcpkg/buildtrees/tiff/x86-uwp-dbg
    See logs for more information:
      C:\Users\josez\Documents\Datco\vcpkg\buildtrees\tiff\install-x86-uwp-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:102 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
  ports/tiff/portfile.cmake:58 (vcpkg_cmake_install)
  scripts/ports.cmake:139 (include)

Error: Building package tiff:x86-uwp failed with: BUILD_FAILED

Aditional Info:

some errors logged in install-x86-uwp-dbg-out.log file:

4>tif_win32.obj : error LNK2019: unresolved external symbol _CreateFileA referenced in function _TIFFOpen [C:\Users\josez\Documents\Datco\vcpkg\buildtrees\tiff\x86-uwp-dbg\libtiff\tiff.vcxproj]
     4>tif_win32.obj : error LNK2019: unresolved external symbol _CreateFileW referenced in function _TIFFOpenW [C:\Users\josez\Documents\Datco\vcpkg\buildtrees\tiff\x86-uwp-dbg\libtiff\tiff.vcxproj]

ERROR al compilar.

       "C:\Users\josez\Documents\Datco\vcpkg\buildtrees\tiff\x86-uwp-dbg\install.vcxproj" (destino predeterminado) (1) ->
       "C:\Users\josez\Documents\Datco\vcpkg\buildtrees\tiff\x86-uwp-dbg\ALL_BUILD.vcxproj" (destino predeterminado) (3) ->
       "C:\Users\josez\Documents\Datco\vcpkg\buildtrees\tiff\x86-uwp-dbg\libtiff\tiff.vcxproj" (destino predeterminado) (4) ->
       (ClCompile destino) -> 
         C:\Users\josez\Documents\Datco\vcpkg\buildtrees\tiff\src\4.3.0-a2c25e37d6.clean\libtiff\tif_win32.c(281,29): warning C4013: 'CreateFileA' undefined; assuming extern returning int [C:\Users\josez\Documents\Datco\vcpkg\buildtrees\tiff\x86-uwp-dbg\libtiff\tiff.vcxproj]
         C:\Users\josez\Documents\Datco\vcpkg\buildtrees\tiff\src\4.3.0-a2c25e37d6.clean\libtiff\tif_win32.c(322,29): warning C4013: 'CreateFileW' undefined; assuming extern returning int [C:\Users\josez\Documents\Datco\vcpkg\buildtrees\tiff\x86-uwp-dbg\libtiff\tiff.vcxproj]

**Comment by walbourn** [comment]
This is a bug for the upstream TIFF repo. They don't support building for the Universal Windows Platform. ``CreateFileA`` and ``CreateFileW`` are not supported for UWP. They need to use ``CreateFile2``.

Something like:

```cpp
#if (_WIN32_WINNT >= _WIN32_WINNT_WIN8)
     HANDLE hFile = CreateFile2(fileName,
                               GENERIC_READ,
                               FILE_SHARE_READ,
                               OPEN_EXISTING,
                               nullptr);
#else
    HANDLE hFile = CreateFileW(fileName,
                               GENERIC_READ,
                               FILE_SHARE_READ,
                               nullptr,
                               OPEN_EXISTING,
                               FILE_ATTRIBUTE_NORMAL,
                               nullptr);
#endif
```

```cpp
#if (_WIN32_WINNT >= _WIN32_WINNT_WIN8)
   HANDLE hFile = CreateFile2(fileName,
        GENERIC_WRITE | DELETE, 0, CREATE_ALWAYS, nullptr);
#else
   HANDLE hFile = safe_handle(CreateFileW(fileName,
        GENERIC_WRITE | DELETE, 0, nullptr, CREATE_ALWAYS, FILE_ATTRIBUTE_NORMAL, nullptr);
#endif
```

See [Microsoft Docs](https://docs.microsoft.com/en-us/uwp/win32-and-com/win32-and-com-for-uwp-apps)

**Comment by josbla89** [comment]
thanks i sussefully patched tiff

**Comment by marcfischer123467** [comment]
I still have this issue.  https://github.com/microsoft/MixedReality-SpectatorView/issues/455
Could someone give me advice on how I would go about patching it?

**Comment by chwazy** [comment]
Hi @marcfischer123467 I've been facing the same issues you've described when trying to build the SpectatorView Unity package. Did you find any solutions ?
Thanks :)

**Comment by friederwC** [comment]
Here is what worked for me 

open vcpkg\ports\opencv3\vcpkg.json

and delete all entries with tiff. The resulting file should look like this:
https://pastebin.com/xrB9xgvN

**Comment by chwazy** [comment]
Thanks, I managed to make it work.

**Comment by arvinkx** [comment]
@friederwC @chwazy Would you happen to know how to get past this issue? Trying to remove the entries with tiff doesn't work anymore due to opencv4 requiring it. I get the message `Package opencv4 does not have a tiff feature`. I've included the resulting log below when the tiff library is included:
```
Building OpenCV
Updaing vcpkg submodule to master branch
From https://github.com/microsoft/vcpkg
 * branch                master     -> FETCH_HEAD
Already up to date.
Preparing vcpkg
Downloading https://github.com/microsoft/vcpkg-tool/releases/download/2021-12-09/vcpkg.exe -> D:\ContrastP4V\MSSpectatorView\MixedReality-SpectatorView\external\vcpkg\vcpkg.exe... done.
Validating signature... done.

Telemetry
---------
vcpkg collects usage data in order to help us improve your experience.
The data collected by Microsoft is anonymous.
You can opt-out of telemetry by re-running the bootstrap-vcpkg script with -disableMetrics,
passing --disable-metrics to vcpkg on the command line,
or by setting the VCPKG_DISABLE_METRICS environment variable.

Read more about vcpkg telemetry at docs/about/privacy.md
Setting vcpkg installs to be available to MSBuild
Applied user-wide integration for this vcpkg root.

All MSBuild C++ projects can now #include any installed libraries.
Linking will be handled automatically.
Installing new libraries will make them instantly available.

CMake projects should use: "-DCMAKE_TOOLCHAIN_FILE=D:/ContrastP4V/MSSpectatorView/MixedReality-SpectatorView/external/vcpkg/scripts/buildsystems/vcpkg.cmake"
Updating vcpkg
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.
Upgrading vcpkg
All installed packages are up-to-date with the local portfiles.
Found install directory for x86 protobuf windows, skipping build
Building OpenCV x86 UWP
Computing installation plan...
The following packages will be built and installed:
    opencv[contrib,core,default-features]:x86-uwp -> 4.5.4#1
  * opencv4[contrib,core,default-features,dnn,jpeg,png,quirc,tiff,webp]:x86-uwp -> 4.5.4#2
  * tiff[core,jpeg,lzma,zip]:x86-uwp -> 4.3.0#3
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x86-uwp...
Restored 0 packages from C:\Users\cml-worker-01\AppData\Local\vcpkg\archives in 247.4 us. Use --debug to see more details.
Starting package 1/3: tiff:x86-uwp
Building package tiff[core,jpeg,lzma,zip]:x86-uwp...
-- Using community triplet x86-uwp. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: D:\ContrastP4V\MSSpectatorView\MixedReality-SpectatorView\external\vcpkg\triplets\community\x86-uwp.cmake
-- Using cached libtiff-libtiff-v4.3.0.tar.gz.
-- Extracting source D:/ContrastP4V/MSSpectatorView/MixedReality-SpectatorView/external/vcpkg/downloads/libtiff-libtiff-v4.3.0.tar.gz
-- Applying patch cmakelists.patch
-- Applying patch fix-pkgconfig.patch
-- Applying patch FindCMath.patch
-- Using source at D:/ContrastP4V/MSSpectatorView/MixedReality-SpectatorView/external/vcpkg/buildtrees/tiff/src/v4.3.0-f4a22a2fc5.clean
-- Found external ninja('1.10.2').
-- Configuring x86-uwp
-- Building x86-uwp-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:155 (message):
    Command failed: D:/ContrastP4V/MSSpectatorView/MixedReality-SpectatorView/external/vcpkg/downloads/tools/cmake-3.21.1-windows/cmake-3.21.1-windows-i386/bin/cmake.exe --build . --config Debug --target install -- /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /m
    Working Directory: D:/ContrastP4V/MSSpectatorView/MixedReality-SpectatorView/external/vcpkg/buildtrees/tiff/x86-uwp-dbg
    See logs for more information:
      D:\ContrastP4V\MSSpectatorView\MixedReality-SpectatorView\external\vcpkg\buildtrees\tiff\install-x86-uwp-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:102 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
  ports/tiff/portfile.cmake:55 (vcpkg_cmake_install)
  scripts/ports.cmake:142 (include)


Error: Building package tiff:x86-uwp failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+tiff
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[tiff]+Build+error
including:
  package: tiff[core,jpeg,lzma,zip]:x86-uwp -> 4.3.0#3
    vcpkg-tool version: 2021-12-09-724cea8b33cbf06c645f5095fa29773697da9761
    vcpkg-scripts version: 1085a57da 2021-12-30 (2 days ago)

Additionally, attach any relevant sections from the log files above.
Building OpenCV x64 Windows
Computing installation plan...
The following packages will be built and installed:
    opencv[contrib,core,default-features]:x64-windows -> 4.5.4#1
  * opencv4[contrib,core,default-features,dnn,jpeg,png,quirc,tiff,webp]:x64-windows -> 4.5.4#2
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Restored 0 packages from C:\Users\cml-worker-01\AppData\Local\vcpkg\archives in 370.3 us. Use --debug to see more details.
Starting package 1/2: opencv4:x64-windows
Building package opencv4[contrib,core,default-features,dnn,jpeg,png,quirc,tiff,webp]:x64-windows...
-- Using cached opencv-opencv-4.5.4.tar.gz.
CMake Error at scripts/cmake/vcpkg_extract_source_archive.cmake:177 (message):
  Could not find patch: '0003-force-package-requirements.patch'
Call Stack (most recent call first):
  scripts/cmake/vcpkg_extract_source_archive_ex.cmake:32 (vcpkg_extract_source_archive)
  scripts/cmake/vcpkg_from_github.cmake:182 (vcpkg_extract_source_archive_ex)
  ports/opencv4/portfile.cmake:12 (vcpkg_from_github)
  scripts/ports.cmake:142 (include)


Error: Building package opencv4:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+opencv4
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[opencv4]+Build+error
including:
  package: opencv4[contrib,core,default-features,dnn,jpeg,png,quirc,tiff,webp]:x64-windows -> 4.5.4#2
    vcpkg-tool version: 2021-12-09-724cea8b33cbf06c645f5095fa29773697da9761
    vcpkg-scripts version: 1085a57da 2021-12-30 (2 days ago)

Additionally, attach any relevant sections from the log files above.
```

**Comment by chwazy** [comment]
@arvinkx in my case I had to use an older version of vcpkg to match the other resources needed to build the Spector View package.
The script building the package was pulling the latest version of vcpkg.
I chose a version of vcpkg by date to match the other resources release date, but I can't remember with version it was.

**Comment by arvinkx** [comment]
@chwazy Thanks for the help, I tried some older versions of vcpkg by commenting out the links in the powershell scripts and pulled in various versions from 2019 - 2020 and wasn't able to build successfully. I get different errors depending on what version pulled in but mostly when trying to update after running `bootstrap-vcpkg.bat` I get the error: 

```
Using local portfile versions. To update the local portfiles, use `git pull`.
Error: while parsing the Binary Paragraph for protobuf:x64-windows
Error: There are invalid fields in the control file of protobuf:x64-windows
The following fields were not expected:

    Type

This is the list of valid fields (case-sensitive):

    Source
    Version
    Description
    Maintainer
    Build-Depends
    Homepage
    Type

Different source may be available for vcpkg. Use .\bootstrap-vcpkg.bat to update.
```

**Comment by jmschrack** [comment]
For anyone else that runs into this, you need to create patch that fixes the compile errors.  Check out the tutorial: https://github.com/microsoft/vcpkg/blob/master/docs/examples/patching.md  

Walbourn's fix is pretty easy to implement and worked for me.

When you edit the portfile.cmake for tiff, it's a different format than what is in that tutorial.  just search for _PATCHES_ and you'll find the list of patch files in that folder. Just insert your patchfile and you should be good to go!
