### ISSUE TITLE
[minizip] unresolved external symbols when linking `bzip2` functions

### ISSUE THREAD

**Issue by playgithub** [microsoft/vcpkg#18448]
**Describe the bug**
In `ports\minizip\portfile.cmake`:
```
if ("bzip2" IN_LIST FEATURES)
    file(GLOB HEADERS "${CURRENT_PACKAGES_DIR}/include/minizip/*.h")
    foreach(HEADER ${HEADERS})
        file(READ "${HEADER}" _contents)
        string(REPLACE "#ifdef HAVE_BZIP2" "#if 1" _contents "${_contents}")
        file(WRITE "${HEADER}" "${_contents}")
    endforeach()
endif()
```
For x64-windows, It patches files in `vcpkg/packages/minizip_x64-windows/include/minizip/`, the files in `installed` are not patched.

Results in link error
```
minizip.lib(unzip.c.obj) : error LNK2019: unresolved external symbol __imp_BZ2_bzDecompressInit referenced in function unzOpenCurrentFile3
minizip.lib(unzip.c.obj) : error LNK2019: unresolved external symbol __imp_BZ2_bzDecompress referenced in function unzReadCurrentFile
minizip.lib(unzip.c.obj) : error LNK2019: unresolved external symbol __imp_BZ2_bzDecompressEnd referenced in function unzCloseCurrentFile
```

**Environment**
- OS: Windows
- Compiler: msvc

**Comment by Neumann-A** [comment]
> For x64-windows, It patches files in vcpkg/packages/minizip_x64-windows/include/minizip/, the files in installed are not patched 

that is intentional and correct as explained in #18456

**Comment by playgithub** [comment]
> > For x64-windows, It patches files in vcpkg/packages/minizip_x64-windows/include/minizip/, the files in installed are not patched
> 
> that is intentional and correct as explained in #18456

But the installed files are not patched

**Comment by Neumann-A** [comment]
> But the installed files are not patched

They don't need to. They will be copied. (and they are patched....according to thsi screenshot)
![image](https://user-images.githubusercontent.com/30894796/122005424-e6ce8180-cdb5-11eb-9cac-482837af7c26.png)

**Comment by playgithub** [comment]
> > But the installed files are not patched
> 
> They don't need to. They will be copied. (and they are patched....according to thsi screenshot)
> ![image](https://user-images.githubusercontent.com/30894796/122005424-e6ce8180-cdb5-11eb-9cac-482837af7c26.png)

Sorry, you are right.
