### ISSUE TITLE
downloads/tools/ninja/1.10.1-linux/ninja: /lib64/libc.so.6: version `GLIBC_2.15' not found

### ISSUE THREAD

**Issue by mulderp** [microsoft/vcpkg#18446]
I am trying a fresh install on old machines of vcpkg with the bootstrap script.
There comes an error that latest Ninja version is unable to run ( see downloads/tools/ninja/1.10.1-linux/ninja: /lib64/libc.so.6: version `GLIBC_2.15' not found )

I then tried to bootstrap vcpkg with system binaries. This works fine and I get vcpkg binary.

However, when I then try to run vcpkg install sqlite3 I get the same error for downloading ninja .

I would expect that subsequent install commands could use the system binaries also.

**Environment**
- OS: Linux
- Compiler: g++ 8.0.0

**Comment by NancyLi1013** [comment]
Hi @mulderp 

Thanks for posting this issue. Seems `glibc `version is too low on your machine. Could you please try to upgrade `glibc`?

**Comment by mulderp** [comment]
it is an old machine in a cluster - don't have a way to upgrade the machine.
However, there are system tools available, cmake, ninja etc on that
machine. I raise the issue, because it seems systembuild tool option is
incosistent between building vcpkg itself and using vcpkg install. Bulding
vcpkg itself works fine (e.g. Ninja v1.10.1 was initially required, but I
can skip that dependency). However with vcpkg install i dont see a way to
skip the build tool download depedency. I worked around manually for now
copying the working ninja over to the expected download location.

**Comment by NancyLi1013** [comment]
Thanks for your details. vcpkg will download tools if the version of the tools installed on your machine are lower than the ones required on vcpkg.

**Comment by NancyLi1013** [comment]
@mulderp 

Is this still a problem for you?
