### ISSUE TITLE
What the role of folder `packages`?

### ISSUE THREAD

**Issue by playgithub** [microsoft/vcpkg#18456]
Found a bug related to it
https://github.com/microsoft/vcpkg/issues/18448

**Comment by Neumann-A** [comment]
staging area. after post build checks the files from there will be moved from `packages/` to `installed/`. As such only files in the `CURRENT_PACKAGES_DIR` are allowed to be modified. Never modify in `CURRENT_INSTALLED_DIR` because it breaks everything (i.e. binary caching)
