### ISSUE TITLE
vcpkg ui?

### ISSUE THREAD

**Issue by nholthaus** [microsoft/vcpkg#1845]
I'm curious if you guys know whether there's any effort in Microsoft or the open source community to make a UI for vcpkg. It seems like it would make a great VS extension, but if no one is working on anything I'd be interested in putting a stand-alone Qt interface together, something like cmake-gui.

**Comment by atkawa7** [comment]
@nholthaus  Just wondering if that would be similar to #1734

**Comment by nholthaus** [comment]
thanks yeah that looks great, any plans for it?

**Comment by cmpute** [comment]
Planning to do so.

**Comment by cmpute** [comment]
Working on this recently. You could check https://github.com/cmpute/vcpkg-gui to try and feedback please~

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/pull/1734.
