### ISSUE TITLE
Error: Building package libusb:x64-linux failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by lijuncan** [microsoft/vcpkg#18450]
**Host Environment**
OS: Ubuntu 20.04
Compiler: gcc 9.3.0

**To Reproduce**
I'm trying to install the realsense software following these steps (https://github.com/IntelRealSense/librealsense). When I run ./vcpkg install realsense2 this error appears:

**Failure logs** 
```
Computing installation plan...
The following packages will be built and installed:
  * libusb[core]:x64-linux -> 1.0.24#4
    realsense2[core]:x64-linux -> 2.42.0#1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-linux...
Could not locate cached archive: /home/vd3/.cache/vcpkg/archives/54/540c71c8cd23f25bdfe393580a39ba78d2081d86.zip
Could not locate cached archive: /home/vd3/.cache/vcpkg/archives/a1/a109c5d37a025a64d55882d759570d62ac903b0c.zip
Starting package 1/2: libusb:x64-linux
Building package libusb[core]:x64-linux...
libusb currently requires the following tools and libraries from the system package manager:
    autoreconf
    libudev

These can be installed on Ubuntu systems via apt-get install autoreconf libudev-dev
-- Downloading https://github.com/libusb/libusb/archive/c6a35c56016ea2ab2f19115d2ea1e85e0edae155.tar.gz -> libusb-libusb-c6a35c56016ea2ab2f19115d2ea1e85e0edae155.tar.gz...
-- Extracting source /home/vd3/vcpkg/downloads/libusb-libusb-c6a35c56016ea2ab2f19115d2ea1e85e0edae155.tar.gz
-- Using source at /home/vd3/vcpkg/buildtrees/libusb/src/5e0edae155-faf13d1dff.clean
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
CMake Error at scripts/cmake/vcpkg_configure_make.cmake:626 (message):
  libusb requires autoconf from the system package manager (example: "sudo
  apt-get install autoconf")
Call Stack (most recent call first):
  ports/libusb/portfile.cmake:53 (vcpkg_configure_make)
  scripts/ports.cmake:139 (include)


Error: Building package libusb:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libusb:x64-linux
  Vcpkg version: 2021-05-05-unknownhash
```

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by dg0yt** [comment]
Install Ubuntu's `packaging-dev`.

**Comment by lijuncan** [comment]
I am trying to install $ "sudo apt-get update -y", then I got the error 404 below:

vd3@vd3-virtual-machine:~/vcpkg$ sudo apt-get update -y
Hit:1 http://dl.google.com/linux/chrome/deb stable InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu focal InRelease                                     
Get:3 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]                    
Get:4 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]                                                  
Get:5 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease [101 kB]                                               
Ign:6 http://ppa.launchpad.net/gnome-terminator/ppa/ubuntu focal InRelease                                                 
Err:7 http://ppa.launchpad.net/gnome-terminator/ppa/ubuntu focal Release                                                   
  404  Not Found [IP: 91.189.95.85 80]
Hit:8 https://librealsense.intel.com/Debian/apt-repo focal InRelease
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/gnome-terminator/ppa/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by JackBoosY** [comment]
```
libusb currently requires the following tools and libraries from the system package manager:
autoreconf
libudev
These can be installed on Ubuntu systems via apt-get install autoreconf libudev-dev
```

**Comment by lijuncan** [comment]
I got this error after running sudo apt-get install autoreconf libudev-dev:
.....
vd3@vd3-virtual-machine:~/vcpkg$ **sudo apt-get install autoreconf libudev-dev**
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package autoreconf
....
Do you think it's something to do with virtual machine environment? I used VMWare on Windows 10 to create a VM and install Ubuntu20.04.

**Comment by JackBoosY** [comment]
`E: Unable to locate package autoreconf`
I think you should use `apt-get update` first.

**Comment by dg0yt** [comment]
There is no Ubuntu package `autoreconf`. The tool is in package `autoconf`. Cf. https://packages.ubuntu.com/search?searchon=contents&keywords=autoreconf&mode=exactfilename&suite=hirsute&arch=any

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
