### ISSUE TITLE
Cygwin-based CMake on PATH breaks building packages

### ISSUE THREAD

**Issue by borjacano97** [microsoft/vcpkg#18468]
**Describe the bug**
`/vcpkg/scripts/detect_compiler` doesn't exists and always fails to install any library.   

**Environment**
- OS: Windows
- Shell: CMD (although I have also used PowerShell and Git for Windows Shell with the same result)
- Compiler: Microsoft Visual Studio Community 2019 Version 16.10.1
- CMake version 3.20.0

**To Reproduce**
```
C:\>git clone https://github.com/microsoft/vcpkg
Cloning into 'vcpkg'...
remote: Enumerating objects: 112876, done.
remote: Counting objects: 100% (253/253), done.
remote: Compressing objects: 100% (205/205), done.
remote: Total 112876 (delta 154), reused 95 (delta 48), pack-reused 112623Receiving objects: 100% (112876/112876), 34.54Receiving objects: 100% (112876/112876), 34.89 MiB | 4.46 MiB/s, done.

Resolving deltas: 100% (71210/71210), done.
Updating files: 100% (7791/7791), done.

C:\>vcpkg\bootstrap-vcpkg.bat
Downloading https://github.com/microsoft/vcpkg-tool/releases/download/2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/vcpkg.exe -> C:\vcpkg\vcpkg.exe
Done.

Telemetry
---------
vcpkg collects usage data in order to help us improve your experience.
The data collected by Microsoft is anonymous.
You can opt-out of telemetry by re-running the bootstrap-vcpkg script with -disableMetrics,
passing --disable-metrics to vcpkg on the command line,
or by setting the VCPKG_DISABLE_METRICS environment variable.

Read more about vcpkg telemetry at docs/about/privacy.md

C:\>vcpkg\vcpkg.exe install glm
Computing installation plan...
The following packages will be built and installed:
    glm[core]:x86-windows -> 0.9.9.8#1
Detecting compiler hash for triplet x86-windows...
A suitable version of powershell-core was not found (required v7.1.0). Downloading portable powershell-core v7.1.0...
Downloading powershell-core...
  https://github.com/PowerShell/PowerShell/releases/download/v7.1.3/PowerShell-7.1.3-win-x86.zip -> C:\vcpkg\downloads\PowerShell-7.1.3-win-x86.zip
Extracting powershell-core...
A suitable version of 7zip was not found (required v18.1.0). Downloading portable 7zip v18.1.0...
Downloading 7zip...
  https://www.nuget.org/api/v2/package/7-Zip.CommandLine/18.1.0 -> C:\vcpkg\downloads\7-zip.commandline.18.1.0.nupkg
Extracting 7zip...
A suitable version of nuget was not found (required v5.9.0). Downloading portable nuget v5.9.0...
Downloading nuget...
  https://dist.nuget.org/win-x86-commandline/v5.9.1/nuget.exe -> C:\vcpkg\downloads\d7acca2b-nuget.exe
Error: while detecting compiler information:
The log content at C:\vcpkg\buildtrees\detect_compiler\stdout-x86-windows.log is:
CMake Error at C:/vcpkg/scripts/ports.cmake:52 (message):
  Cannot find port:

    Directory does not exist: C;/vcpkg/scripts/detect_compiler



Error: vcpkg was unable to detect the active compiler's information. See above for the CMake failure output.
```

**Additional context**
My guess is that the CMAKE macro defines the path with ';' instead of ':' for the volume.  
I've tried to reinstall CMake, Visual Studio and vcpkg and the error persist.
I don't really know how to fix this

**Comment by autoantwort** [comment]
Duplicate of #16448, there a solution is provided :)

**Comment by JonLiu1993** [comment]
@borjacano97 ,Thanks for posting this issue,
As @autoantwort  said, issue #16448 is the same as your issue, you can refer to the solution to try, if you have any problems, you can ping me at any time

**Comment by borjacano97** [comment]
Solved! I had CMake installed with cygwin and `cygwin64/bin` in the PATH. I just unistalled cmake from cygwin and runned the vcpkg install [anylib], which installed a portable version of cmake and the installed the library successfuly.
Thank you.
Closing the issue.

**Comment by ras0219-msft** [comment]
I'm reopening this issue because I think it's the most "direct" issue we have to capture the fundamental issue:

vcpkg needs to detect and skip over cygwin-derived cmake since it will not work.

**Comment by dg0yt** [comment]
As far as the native MSYS2 build of CMake is concerned, it can be detected by 
- querying generators: It lacks Visual Studio generators.
- checking the runtime librairies: it will request msys-2.0.dll or similar.

**Comment by ras0219-msft** [comment]
Does `cmake --version` report anything? We already call that to ensure it's recent enough.

**Comment by dg0yt** [comment]
I don't know about `--version`  output, but I guess I checked this in the past.

The msys2 and cygwin DLLs are the key providers of the POSIX-style environments. And `vcpkg` should already have the code to read it, for app-local deployment.

**Comment by dg0yt** [comment]
Msys cmake:
~~~
$ /usr/bin/cmake.exe --version
cmake version 3.22.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).
~~~
... but it seems that you can run `cmake --help --version` to get both the list of generators and the version.
