### ISSUE TITLE
"vcpkg integrate install"  failed

### ISSUE THREAD

**Issue by baimafeitu** [microsoft/vcpkg#18462]
My environment is Win10 Home Edition(version number:19042.1052), 64bit and Visual Studio version is 2019 community

I run bootstrap-vcpkg.bat successfully and got a vcpkg.exe file.
Then run vcpkg integrate install failedly in admin cmd. The error log shows:

Failed to copy targets file to C:\Program Files <x86>\MSBuild\Microsoft.Cpp\v4.0\V140\ImportBefore\Default\vcpkg.system.props

How to fix it?

Thanks for any advice!
![vcpkgError](https://user-images.githubusercontent.com/85609765/122022610-56199500-cdf9-11eb-886d-80718c4b2d22.jpg)

**Comment by PhoebeHui** [comment]
@baimafeitu, do you install English language pack via vs installer? if not, could you install it and try again? BTW, could you also try to execute the command via powershell?

**Comment by baimafeitu** [comment]
This problem is already sloved. I changed the directory of vcpkg. The previous path includes Chinese character. Thank you for your attention.
