### ISSUE TITLE
How do I change the triplet using manifest (with CMakePresets.json)

### ISSUE THREAD

**Issue by tonygould** [microsoft/vcpkg#18478]
I'm evaluating vcpkg, manifest mode, for use in a corporate environment. Also in the last few days I've started using CMakePresets.json, which is working great across Windows and lnux.

I have a number of acceptance tests. One of them is to see how making a fundamental change to compiler options will cause dependent packages to rebuild from source. It seems the way to do this in vcpkg is to use a different triplet. A recent example we had in our organisation was changing between static and dynamic crt linkage on windows. In vcpkg there is already a triplet for this. So I thought I would try changing to use the x64-windows-static triplet in one of my configurations. But I can't see where to specify this. I've tried "VCPKG_TARGET_TRIPLET" : "x64-windows-static" in both environment and cacheVariables dictionary in CMakePresets.json, and both are ignored (with an unused variable warning for the latter case). As well as some other variables.

A general comment -- manifest mode (and CMakePresets.json) are new features, and are also what is persuading me that vcpkg is worth adopting in our firm. But because these features are new, most of the vcpkg documentatation is still oriented towards classic mode (and towards invoking directly without CMakePresets.json). Is there any effort underway or planned to add to or re-orient the documentation towards the new features?

**Comment by Neumann-A** [comment]
Show your preset.
This one works for me:
```
        {
            "name": "vs-llvm",
            "displayName": "VS LLVM",
            "description": "VS Generator with llvm toolset",
            "generator": "Visual Studio 16 2019",
            "toolset": "LLVM,host=x64",
            "binaryDir": "${sourceDir}/build/vs-llvm",
            "cacheVariables": {
                "CMAKE_GENERATOR_INSTANCE": "$env{VS2019INSTALLDIR}",
                "VCPKG_OVERLAY_TRIPLETS": "${sourceDir}/my-vcpkg-triplets",
                "VCPKG_TARGET_TRIPLET": "x64-windows-llvm",
                "VCPKG_HOST_TRIPLET": "x64-windows-llvm",
                "VCPKG_MANIFEST_FEATURES": "qt",
                "StoPhys_ARCH_LIST": "AVX2",
                "CMakeJSON_DEBUG": "FALSE",
                "CMakeJSON_DEBUG_RETURN_PARENT": "FALSE",
                "CMakeJSON_DEBUG_HELPERS": "FALSE",
                "CMakeJSON_DEBUG_RANGE_LOOP": "FALSE",
                "CMakeJSON_DEBUG_PARSE": "FALSE",
                "CMakeJSON_DEBUG_PROJECT": "FALSE",
                "CMakeJSON_DEBUG_PROJECT_OPTIONS": "FALSE",
                "CMakeJSON_DEBUG_TARGET": "FALSE",
                "CMakeJSON_DEBUG_FIND_MODULE": "FALSE",
                "SERAR_WITH_HDF5": "TRUE"
            }
        }   
```

**Comment by tonygould** [comment]
Apologies, after reading your post, I tried again with a bunch of different options, I just got this to work with simply `"cacheVariables": { "VCPKG_TARGET_TRIPLET": "x64-windows-static" }`. I was sure that this was what I tried yesterday. After trying to replicate the problem for 1-2 hours this afternoon, I have to say the most likely explanation is user error on my part. If something like this happens again, I'll stick the config on a branch so I know exactly what I had if I don't post here.

 

My problem now is that with x64-windows-static working correctly (and looking at the packages it's bringing in now they have "Architecture: x64-windows-static" in the CONTROL file), I'm not convinced that my current project is compiling as I expect. E.g. I see

 

`[build] [11/125] "C:\PROGRA~2\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30037\bin\Hostx86\x64\cl.exe"  /nologo /TP   /DWIN32 /D_WINDOWS /EHsc /bigobj /Zi /Ob0 /Od /RTC1 -MDd -std:c++17 /showIncludes /Foxxxx.obj /Fdxxxx.cpp

`

 

when I expected `-MT` not `-MD`. Consistent with this, later in the build process, linking fails because there is a mismatch between my object files and those in the dependent libraries (which truly have been built with static per the CONTROL file I looked at).

 

This is with preset

`

    "configurePresets": [

        {

            "name": "base",

            "description": "Sets generator, build and install directory, vcpkg",

            "hidden": true,

            "generator": "Ninja",

            "binaryDir": "${sourceDir}/out/build/${presetName}",

            "cacheVariables": {

                "CMAKE_INSTALL_PREFIX": "${sourceDir}/out/install/${presetName}",

                "CMAKE_TOOLCHAIN_FILE": {

                    "type": "FILEPATH",

                    "value": "../vcpkg/scripts/buildsystems/vcpkg.cmake"

                }

            },

            "environment": {

                "VCPKG_FEATURE_FLAGS": "manifests,versions"

            }

        },

        {

            "name": "base-windows",

            "inherits": [

                "base"

            ],

            "hidden": true,

            "vendor": {

                "microsoft.com/VisualStudioSettings/CMake/1.0": {

                    "hostOS": [

                        "Windows"

                    ]

                }

            }

        },

        {

            "name": "msvc-debug",

            "inherits": [

                "base-windows"

            ],

            "description": "Visual Studio debug",

            "cacheVariables": {

               "CMAKE_BUILD_TYPE": "Debug",

                "CMAKE_C_COMPILER": "cl",

                "CMAKE_CXX_COMPILER": "cl",

                "VCPKG_TARGET_TRIPLET": "x64-windows-static",

                "VCPKG_HOST_TRIPLET": "x64-windows-static",

            }

        },
`

(I tried vs2019 generator but didn't make any difference)

**Comment by JackBoosY** [comment]
Maybe you should use the community triplet `x64-windows-static-md` instead.

**Comment by tonygould** [comment]
hi Jack, I'm not sure why a community triplet would help when the official one doesn't work? Also the community triplet specifies md when I want mt. In any case I'm closing this issue because the original question I had was addressed by Alexander, and I now have a new issue, which I'll raise separately.

**Comment by daiybh** [comment]
https://cmake.org/cmake/help/latest/prop_tgt/MSVC_RUNTIME_LIBRARY.html

set_property(TARGET Foxxxx PROPERTY  MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
can try this.
