### ISSUE TITLE
[boost-system] build failure

### ISSUE THREAD

**Issue by playgithub** [microsoft/vcpkg#18470]
**Host Environment**
- OS: Windows
- Compiler: msvc

**To Reproduce**
```shell
vcpkg install --triplet=x64-windows-cpp17 boost-system
```

**Failure logs** 
```shell
λ vcpkg install --triplet=x64-windows-cpp17 boost-system
...
CMake Error at ports/boost-system/portfile.cmake:17 (include):
  include could not find requested file:

    /path/to/vcpkg/installed/x64-windows/share/boost-build/boost-modular-build.cmake
...
```

**Additional context**
triple file `x64-windows-cpp17.cmake`
```cmake
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_CXX_FLAGS "/std:c++17")
set(VCPKG_C_FLAGS "/std:c17")
```

BTW, many boost libs before this are installed successfully

**Comment by PhoebeHui** [comment]
@playgithub, could you use './vcpkg install --host-triplet=x64-windows-cpp17 boost-system' instead?

See https://github.com/microsoft/vcpkg/blob/master/docs/users/host-dependencies.md#specifying-the-host-triplet

**Comment by playgithub** [comment]
> @playgithub, could you use './vcpkg install --host-triplet=x64-windows-cpp17 boost-system' instead?
> 
> See https://github.com/microsoft/vcpkg/blob/master/docs/users/host-dependencies.md#specifying-the-host-triplet

I can't try blindly.
What's the different of `triplet` and `host triplet`, the concepts are confused, aren't they?

**Comment by PhoebeHui** [comment]
@playgithub, sorry for the confuse, let me clarify this. eg: boost-system, looking at https://github.com/microsoft/vcpkg/blob/master/ports/boost-system/vcpkg.json#L10, you will noticed that the host set to 'true' for port boost-build and boost-modular-build-helper, since we consume the port as a tool, so they set them to true. then we has 'host triplet' and 'target triplet' concept, the target triplet' is the name of the current triplet to build for. The 'host triplet' is the name of the triplet corresponding to the host, by default, host triplets are chosen based on the host architecture and operating system, eg: x64-windows. It affect these ports that set the host to true.
 ['triplet'](https://github.com/microsoft/vcpkg/blob/master/docs/users/triplets.md#triplet-files) used to capture the target environment (cpu, os, compiler, runtime) we used usually. they located in triplets\directory.

**Comment by playgithub** [comment]
> @playgithub, sorry for the confuse, let me clarify this. eg: boost-system, looking at https://github.com/microsoft/vcpkg/blob/master/ports/boost-system/vcpkg.json#L10, you will noticed that the host set to 'true' for port boost-build and boost-modular-build-helper, since we consume the port as a tool, so they set them to true. then we has 'host triplet' and 'target triplet' concept, the target triplet' is the name of the current triplet to build for. The 'host triplet' is the name of the triplet corresponding to the host, by default, host triplets are chosen based on the host architecture and operating system, eg: x64-windows. It affect these ports that set the host to true.
> ['triplet'](https://github.com/microsoft/vcpkg/blob/master/docs/users/triplets.md#triplet-files) used to capture the target environment (cpu, os, compiler, runtime) we used usually. they located in triplets\directory.

Got it, thanks.
But why doesn't `x64-windows` as host triplet  for `boost-system` in this case  work, it should be independet of target triplet, right?

**Comment by playgithub** [comment]
@PhoebeHui 
By set host triplet to `x64-windows-cpp17`, it is installed successfully.
But why as a tool, it failed with triplet `x64-windows`.

For example, when doing cross compile for Linux on Windows, target triplet is `x64-linux`, then what host triplet should be for `boost-system`? Will `x64-windows` as  still host triplet failed?

**Comment by ras0219-msft** [comment]
You're right that the command line in the original issue should have worked; the host triplet and target triplets should be independent.

To diagnose further, could you let us know:
1. The SHA of vcpkg you're using
2. The versions of the relevant boost libraries you have installed for each architecture (`vcpkg list`). Especially important is `boost-modular-build-helper:x64-windows`
3. The install plan printed before vcpkg started installing libraries.

**Comment by playgithub** [comment]
> To diagnose further, could you let us know:
> 
> 1. The commit id of vcpkg you're using
> 2. The versions of the relevant boost libraries you have installed for each architecture (`vcpkg list`). Especially important is `boost-modular-build-helper:x64-windows`
> 3. The install plan printed before vcpkg started installing libraries.
> 4. Does it reproduce from completely clean (delete the `installed` directory and then run the command from the original post)

Now, I use commit id `183a12585`, delete directory `installed`, and try to reprocude the problem by `vcpkg install boost-system`, but it succeeds. Maybe it has been fixed. Anyway I'll close the issue and create one with details if it appears again.

Thanks
