### ISSUE TITLE
How to determine whether vtk[atlmfc] uses unicode or multi-character set？

### ISSUE THREAD

**Issue by WangZP10969** [microsoft/vcpkg#18482]
I am using vtk combined with mfc to display, when I use cmake to compile vtk, I need to set the character set to unicode, but when I use vcpkg, I did not find such a setting.
How can I confirm the type of character set currently in use?

Thank you very much.

**Comment by NancyLi1013** [comment]
Hi @WangZP10969 

Thanks for posting this issue

Seems `vtk `only sets `unicode `here:
https://github.com/Kitware/VTK/blob/master/Utilities/KWSys/vtksys/CMakeLists.txt#L915-L918

In vcpkg, I noticed that only msbuild and make set `unicode `

https://github.com/microsoft/vcpkg/blob/183a12585a95b36bfdda342eb6d302d3ab3ad466/scripts/buildsystems/msbuild/vcpkg.targets#L108

https://github.com/microsoft/vcpkg/blob/183a12585a95b36bfdda342eb6d302d3ab3ad466/scripts/cmake/vcpkg_configure_make.cmake#L567

**Comment by WangZP10969** [comment]
Thank you very much, it seems that VTK supports Unicode, so there is no need to set Unicode separately
https://gitlab.kitware.com/vtk/vtk/-/issues/18115
