### ISSUE TITLE
How do I integrate vcpkg for different toolsets?

### ISSUE THREAD

**Issue by Pilipets** [microsoft/vcpkg#18496]
I installed all the necessary libs for x64-windows and x64-windows-v140(custom triplet with `set(VCPKG_PLATFORM_TOOLSET v140)`.

Now I want to use them in Visual Studio with both toolsets, but I wasn't able to integrate vcpkg with the v140 toolset.
The compilation, linking, includes works flawlessly for the v142(aka latest toolset) in the Visual Studio after `vcpkg integrate install`, but as soon as I change the toolset for the project to v140, it's not integrated.

Any suggestions here?

**Comment by PhoebeHui** [comment]
Closing in favor of https://github.com/microsoft/vcpkg/issues/18336.
