### ISSUE TITLE
[Request] Add WiX Toolset to Vcpkg

### ISSUE THREAD

**Issue by UnaNancyOwen** [Microsoft/vcpkg#1849]
I want to extract WiX installer using dark.exe that included in [WiX Toolset](https://github.com/wixtoolset/wix3/releases/tag/wix311rtm).
Can you make dark.exe available in Vcpkg?

```cmake
# e.g.
vcpkg_execute_required_process(
    COMMAND "dark.exe -x <output> <installer>"
    WORKING_DIRECTORY ${CURRENT_BUILDTREES_DIR}
    LOGNAME extract_installer
)
```

Example of installer created by WiX:
* Kinect for Windows SDK 1.8 (KinectSDK-v1.8-Setup.exe)
* Kinect for Windows SDK 2.0 (KinectSDK-v2.0_1409-Setup.exe)

How do you want to use it? Please see https://github.com/Microsoft/vcpkg/pull/1414#issuecomment-330921112.
Thanks,

**Comment by UnaNancyOwen** [comment]
I sent a pull request https://github.com/Microsoft/vcpkg/pull/1904.
Please review it. Thanks,

**Comment by SeanFarrow** [comment]
I don't know qwhether this was fully added, but it would make sense to add the C++ libs to vcpkg.

I'm happy to create a PR if it would be accepted.
