### ISSUE TITLE
[New Port Request] voro++

### ISSUE THREAD

**Issue by xarthurx** [microsoft/vcpkg#18494]
**Library name:** Voro++

**Library description:**
Voro++ is a software library for carrying out three-dimensional computations of the Voronoi tessellation. A distinguishing feature of the Voro++ library is that it carries out cell-based calculations, computing the Voronoi cell for each particle individually. It is particularly well-suited for applications that rely on cell-based statistics, where features of Voronoi cells (eg. volume, centroid, number of faces) can be used to analyze a system of particles.

**Source repository URL:**
https://github.com/chr1shr/voro

**Project homepage (if different from the source repository):**
http://math.lbl.gov/voro++/

**Anything else that is useful to know when adding (such as optional features the library may have that should be included):**

`voro++` is the only other library I can find doing 3D voronoi computation beyond `qHull` (which has an inefficient c++ interface and is very hard to use as a cpp lib). 

The author is also planning to update the lib soon and it has been used as a base component of many scientific computation software: https://github.com/chr1shr/voro/issues/13

**Comment by xarthurx** [comment]
Is there a queue for new package request?
How long will it roughly take for adding the libs?

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead, we're happy to answer any questions we can to support this effort, but for now we'd prefer to support your role as a maintainer than to take ownership ourselves. None of our core team is very familiar with voro++, so I feel you'll do a much better job than we could!
