### ISSUE TITLE
[grpc] update to 1.35 or latest

### ISSUE THREAD

**Issue by kisan68** [microsoft/vcpkg#18503]
Library name: gRPC

New version number: 1.35

Other information that may be useful (release notes, etc...)

**Comment by PhoebeHui** [comment]
@kisan68, grpc has been upgrade to 1.37 in vcpkg, could you please get latest source and try again?

**Comment by kisan68** [comment]
When I try  ".\vcpkg.exe search grpc", I can see that grpc is at version 1.33.1#3
Do I need to wait a while after the GitHub sync?

**Comment by JonLiu1993** [comment]
> When I try ".\vcpkg.exe search grpc", I can see that grpc is at version 1.33.1#3
> Do I need to wait a while after the GitHub sync?

You can run the command "git pull" to update vcpkg, if it still fails, please clone vcpkg again

**Comment by kisan68** [comment]
Thank you. I tried a simple client-server example and it works.
