### ISSUE TITLE
tiff:arm64-linux build failure

### ISSUE THREAD

**Issue by fh-igd-mueller-roemer** [microsoft/vcpkg#18504]
**Host Environment**
- OS: Ubuntu 18.04 (inside a Docker container)
- Compiler: aarch64-linux-gnu-gcc (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04) 7.5.0

**To Reproduce**
`./vcpkg install tiff:arm64-linux`

**Failure logs** 
- [console.log](https://github.com/microsoft/vcpkg/files/6670041/console.log)
- [config-arm64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/6670043/config-arm64-linux-dbg-out.log)
- [config-arm64-linux-dbg-err.log](https://github.com/microsoft/vcpkg/files/6670045/config-arm64-linux-dbg-err.log)

**Additional context**
I noticed this in the context of installing opencv and other requirements (jpeg, lzma, png16, protobuf, webp, zlib) built without issues.

**Comment by dg0yt** [comment]
I can reproduce this issue.
tiff now uses `find_library(CMath_LIBRARY NAMES m)` to find libm. This happens to work on x64, but fails for (Ubuntu) arm64.

The error is fixed by adding `PATHS ${CMAKE_C_IMPLICIT_LINK_DIRECTORIES}` to `find_library`.
