### ISSUE TITLE
Glslang build failed

### ISSUE THREAD

**Issue by shrinktofit** [Microsoft/vcpkg#1850]
PS X:\Source\OtherRepos\vcpkg> .\vcpkg.exe install glslang glslang:x64-windows
The following packages will be built and installed:
    glslang:x86-windows
    glslang:x64-windows
Building package glslang:x86-windows...
-- CURRENT_INSTALLED_DIR=X:/Source/OtherRepos/vcpkg/installed/x86-windows
-- DOWNLOADS=X:/Source/OtherRepos/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=X:/Source/OtherRepos/vcpkg/packages/glslang_x86-windows
-- CURRENT_BUILDTREES_DIR=X:/Source/OtherRepos/vcpkg/buildtrees/glslang
-- CURRENT_PORT_DIR=X:/Source/OtherRepos/vcpkg/ports/glslang/.
CMake Warning at X:/Source/OtherRepos/vcpkg/ports/glslang/portfile.cmake:3 (message):
  Dynamic not supported.  Building static
Call Stack (most recent call first):
  X:/Source/OtherRepos/vcpkg/scripts/ports.cmake:72 (include)

-- Using cached X:/Source/OtherRepos/vcpkg/downloads/KhronosGroup-glslang-3a21c880500eac21cdf79bef5b80f970a55ac6af.tar.gz
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
CMake Error at X:/Source/OtherRepos/vcpkg/scripts/cmake/vcpkg_find_acquire_program.cmake:171 (file):
  file DOWNLOAD HASH mismatch

    for file: [X:/Source/OtherRepos/vcpkg/downloads/ninja-win.zip]
      expected hash: [cccab9281b274c564f9ad77a2115be1f19be67d7b2ee14a55d1db1b27f3b68db8e76076e4f804b61eb8e573e26a8ecc9985675a8dcf03fd7a77b7f57234f1393]
        actual hash: [cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e]
             status: [7;"Couldn't connect to server"]

Call Stack (most recent call first):
  X:/Source/OtherRepos/vcpkg/scripts/cmake/vcpkg_configure_cmake.cmake:93 (vcpkg_find_acquire_program)
  X:/Source/OtherRepos/vcpkg/ports/glslang/portfile.cmake:15 (vcpkg_configure_cmake)
  X:/Source/OtherRepos/vcpkg/scripts/ports.cmake:72 (include)

Error: Building package glslang:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: glslang:x86-windows
  Vcpkg version: 0.0.81-22848e4b7e29a3a74c28afafe4d177e541ec8638

Additionally, attach any relevant sections from the log files above.

**Comment by wfeii1980** [comment]
ninja-win.zip Download failed
re .\vcpkg.exe install glslang glslang:x64-windows
or download ninja-win.zip cp to vcpkg\downloads\ninja-win.zip
