### ISSUE TITLE
SDL2 for IOS fails

### ISSUE THREAD

**Issue by RagnarDa** [microsoft/vcpkg#18515]
Package: sdl2:x64-ios
Vcpkg version: 2021-05-05-unknownhash

Log: https://drive.google.com/file/d/1hVIUXo_nX5puH3AIR3j8EoSLGq45XXVa/view?usp=sharing

**Comment by FrankXie05** [comment]
@RagnarDaThis problem is because `Cocoa/Cocoa.h` is the library file for OSX, and not an IOS library file. Maybe sdl2 does not support ios.

**Comment by RagnarDa** [comment]
Since I got a notification for this now I checked and the error is gone. I haven't been able to check everything all the way through to a working iOS-app but I am still closing this issue.
