### ISSUE TITLE
[New Port Request] <clipper>

### ISSUE THREAD

**Issue by timmeh87** [microsoft/vcpkg#18513]
**Library name:**
"clipper" aka "Angus' C++ Polygon Clipping Library" aka "libpolyclipping"

**Library description:**
"An open source freeware library for clipping and offsetting lines and polygons."

**Source repository URL:**
http://sourceforge.net/projects/polyclipping/files/
https://github.com/brandon-kohn/clipper-lib (mirror)

**Project homepage (if different from the source repository):**
http://www.angusj.com/delphi/clipper.php

**Anything else that is useful to know when adding (such as optional features the library may have that should be included):**
I will make a PR of this port myself

**Comment by dg0yt** [comment]
This library is available under its other popular name, `polyclipping`.

**Comment by timmeh87** [comment]
Oh cool, thank you
