### ISSUE TITLE
[New Port Request] <simplesockets>

### ISSUE THREAD

**Issue by timmeh87** [microsoft/vcpkg#18514]
**Library name:**
"SimpleSockets" aka "clsocket"

**Library description:**
"SimpleSockets is a lightweight set of classes that allow developers to implement IP based network programs."

**Source repository URL:**
https://github.com/nyhnpya/ClSockets
https://github.com/DFHack/clsocket (SEE COMMENTS)

**Project homepage (if different from the source repository):**
http://sockets.carrierlabs.com/ (??? SEE COMMENTS)

**Anything else that is useful to know when adding (such as optional features the library may have that should be included):**
This library is required by my job and we have had a naked copy of the source code kicking around for years..
This library is attributed to "Mark Carrier" aka "nyhnpya" and the "DFHack" github links to a site called "carrier labs" that seems to make oil rig technology.. But the site you get to seems to contain the doxygen output of a completely unrelated project. Perplexingly, this github presents itself as official, and yet it is hosted as part of "dwarf fortress hack", part a popular videogame. The "DF" version of the source code is many commits ahead of the original "nyhnpya" repository, which has only seen a single commit, ever. So as far as I can tell the "DF" version is actually unofficial, but it is more up to date including a working cmake system.

I will make this port and submit a PR

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
