### ISSUE TITLE
Feature request: support xmake packages (xrepo).

### ISSUE THREAD

**Issue by idealvin** [microsoft/vcpkg#18518]
### Discussed in https://github.com/microsoft/vcpkg/discussions/18498

<div type='discussions-op-text'>

<sup>Originally posted by **idealvin** June 17, 2021</sup>
As far as I know, [xmake](https://github.com/xmake-io/xmake) is much simpler than cmake, it just lacks the support of big companies. Does Microsoft consider cooperating with the author of xmake to build a package manager based on xmake? </div>

**Comment by idealvin** [comment]
Google has bazel, and perhaps Microsoft may have a similar build tool.

xmake is a lightweight, powerful build tool, and the most important, it is really easy to learn. If Microsoft acquires xmake or something like that, and develops its own build tool based on xmake, lots of programmers will benefit from it.

**Comment by PhoebeHui** [comment]
@idealvin, thanks, I change the catagory and label in the discussion https://github.com/microsoft/vcpkg/discussions/18498, we will use it to track the suggestion.
