### ISSUE TITLE
win10 + boost + vs2015 build error

### ISSUE THREAD

**Issue by yaoyu** [Microsoft/vcpkg#1851]
win10 + boost + vs2015 

Building Boost.Build engine

Failed to build Boost.Build engine.
Please consult bootstrap.log for further diagnostics.

You can try to obtain a prebuilt binary from

   http://sf.net/project/showfiles.php?group_id=7586&package_id=72941

Also, you can file an issue at http://svn.boost.org 
Please attach bootstrap.log in that case.

**Comment by ras0219-msft** [comment]
Thanks for reporting this issue.

Could you attach bootstrap.log and let us know your precise vcpkg version (`vcpkg version`)?

**Comment by yaoyu** [comment]
Vcpkg version: 0.0.89-2017-09-21-a1d7e95dc5068c3cb21e4abcaab1279a280e7fd8

[bootstrap-err.zip](https://github.com/Microsoft/vcpkg/files/1320922/bootstrap-err.zip)

**Comment by bigdimboom** [comment]
error
![image](https://user-images.githubusercontent.com/6119906/30879225-d0a129c0-a2cc-11e7-9662-1f58954fecdc.png)

**Comment by atkawa7** [comment]
@bigdimboom Sourceforge is down

**Comment by kwach** [comment]
Duplicate imho https://github.com/Microsoft/vcpkg/issues/1881

**Comment by JackBoosY** [comment]
Hi @yaoyu , thanks for post this issue!
This bug seems to have been fixed. Plz help us to repro it. If build success, plz close this issue.
Thx.

**Comment by JackBoosY** [comment]
Please open a new issue if this is still a problem for you.
Thx.
