### ISSUE TITLE
[New Port Request] TUIO 1.1 and 2.0

### ISSUE THREAD

**Issue by traumedy** [microsoft/vcpkg#18519]
Library name: 
TUIO 1.1 and TUIO 2.0

Library description: 
TUIO is an open framework that defines a common protocol and API for tangible multitouch surfaces. The TUIO protocol allows the transmission of an abstract description of interactive surfaces, including touch events and tangible object states. This protocol encodes control data from a tracker application (e.g. based on computer vision) and sends it to any client application that is capable of decoding the protocol.

Source repository URL:
TUIO 1.1:  https://github.com/mkalten/TUIO11_CPP
TUIO 2.0: https://github.com/mkalten/TUIO20_CPP

Project homepage (if different from the source repository):
https://www.tuio.org/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
TUIO 1.1 and 2.0 are distinct and incompatible protocols and should be available as two separate ports.  
TUIO11_CPP contains sample programs `SimpleSimulator`, `TuioDemo`, and `TuioDump` which are useful tools for testing servers and clients and would be great to have available as a 'tools' feature.  
TUIO20_CPP contains demo programs `Tuio2Demo`, `Tuio2Dump`, `Tuio2Simulator`  and `Tuio2Test` which are useful tools for testing servers and clients and would be great to have available as a 'tools' feature.  

Both of these repositories have been unchanged for > 4 years.

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
