### ISSUE TITLE
Automatically set environment variables

### ISSUE THREAD

**Issue by luizfernandonb** [microsoft/vcpkg#18520]
The vcpkg could automatically set some environment variables, such as `VCPKG_ROOT`, among others

This would help to avoid errors in CMake builds that use the `VCPKG_ROOT` variable to find the root folder of vcpkg to use libraries among others, as I or other people don't always remember to set this environment variable to the entire system

**Comment by dg0yt** [comment]
What is the use case for setting this environment variable? 
Vcpkg tool always passes `-DVCPKG_ROOT_DIR=...` when invoking the portfile scripts. So this is the canonical source for that information.

**Comment by JackBoosY** [comment]
We have received such issues, and the answer is no.

vcpkg will never actively modify system configuration or environment variables.

**Comment by luizfernandonb** [comment]
> We have received such issues, and the answer is no.
> 
> vcpkg will never actively modify system configuration or environment variables.

But I could at least ask the user if he would like vcpkg to add as to environment variables or if that can't either, there could be an option the user would add during installation that would allow vcpkg to add to environment variables automatically

**Comment by luizfernandonb** [comment]
> What is the use case for setting this environment variable?
> Vcpkg tool always passes `-DVCPKG_ROOT_DIR=...` when invoking the portfile scripts. So this is the canonical source for that information.

I was compiling a project using CMake in Visual Studio and the IDE was not finding the VCPKG_ROOT environment variable to replace it in CMakeLists.txt because it was not defined in the system environment variables

**Comment by dg0yt** [comment]
> I was compiling a project using CMake in Visual Studio and the IDE was not finding the VCPKG_ROOT environment variable to replace it in CMakeLists.txt because it was not defined in the system environment variables

This was in "Manifest mode"? The VCPKG_ROOT *cmake* variable is pass from vcpkg tool to the portfile scripts. It is not passed magically to the the project mode (CMakeLists.txt).
In project mode

**Comment by dg0yt** [comment]
(cont.) In project mode (vcpkg manifest mode), there is `VCPKG_INSTALLED_DIR` - which has a different meaning though.

**Comment by luizfernandonb** [comment]
> > I was compiling a project using CMake in Visual Studio and the IDE was not finding the VCPKG_ROOT environment variable to replace it in CMakeLists.txt because it was not defined in the system environment variables
> 
> This was in "Manifest mode"? The VCPKG_ROOT _cmake_ variable is passed from vcpkg tool to the portfile scripts. It is not passed magically to the project mode (CMakeLists.txt).
> In project mode

I didn't understand the "manifest mode", the project I have is not a solution in itself, it's a folder that only has CMakeLists.txt and the source code, pretty much that's all

**Comment by dg0yt** [comment]
> I didn't understand the "manifest mode", the project I have is not a solution in itself, it's a folder that only has CMakeLists.txt and the source code, pretty much that's all

What did you do make vcpkg available to this project (or all your projects)?
There are different way to use vcpkg, even on Windows.

**Comment by luizfernandonb** [comment]
> > I didn't understand the "manifest mode", the project I have is not a solution in itself, it's a folder that only has CMakeLists.txt and the source code, pretty much that's all
> 
> What did you do make vcpkg available to this project (or all your projects)?
> There are different way to use vcpkg, even on Windows.

I only ran the vcpkg integrate install command the first time I used vcpkg and installed the packages I was going to use, the only thing I've done so far is this and it works perfectly in any Visual Studio project, but the environment variables are not defined

**Comment by dg0yt** [comment]
I see, you are using the [user-wide integration for msbuild](https://github.com/microsoft/vcpkg/blob/master/docs/users/integration.md#user-wide-for-msbuild-recommended-for-open-source-msbuild-projects). I can't say anything about msbuild. 

> it's a folder that only has CMakeLists.txt and the source code, pretty much that's all

For this project, you would probably need the [integration by cmake toolchain file](https://github.com/microsoft/vcpkg/blob/master/docs/users/integration.md#cmake-toolchain-file-recommended-for-open-source-cmake-projects).

**Comment by luizfernandonb** [comment]
> I see, you are using the [user-wide integration for msbuild](https://github.com/microsoft/vcpkg/blob/master/docs/users/integration.md?rgh-link-date=2021-06-19T05%3A00%3A43Z#user-wide-for-msbuild-recommended-for-open-source-msbuild-projects). I can't say anything about msbuild.
> 
> > it's a folder that only has CMakeLists.txt and the source code, pretty much that's all
> 
> For this project, you would probably need the [integration by cmake toolchain file](https://github.com/microsoft/vcpkg/blob/master/docs/users/integration.md?rgh-link-date=2021-06-19T05%3A00%3A43Z#cmake-toolchain-file-recommended-for-open-source-cmake-projects).

This integration I have already done, but the environment variable `VCPKG_ROOT` was not available for the system, so I created this issue

**Comment by dg0yt** [comment]
Again, the `VCPKG_ROOT` environment variable is a *user input*  to the vcpkg system. It is consumed, not produced by vcpkg. 
Once you are using the vcpkg toolchain in cmake projects, use the *cmake variable* `VCPKG_INSTALLED_DIR` to find the root of the installed packages. (This works in classic mode as well as in manifest mode.)
Again, what is the use case for having to know the root in the user project?

**Comment by luizfernandonb** [comment]
> Again, what is the use case for having to know the root in the user project?

Because the project in question accesses vcpkg's `lib` folder and takes some libraries from there, and it accesses it by calling `VCPKG_ROOT`, and when I did a PR to modify `CMakeLists.txt` I left it as it was so as not to confuse anyone

**Comment by dg0yt** [comment]
> Because the project in question accesses vcpkg's lib folder and takes some libraries from there, and it accesses it by calling `VCPKG_ROOT`.

IIUC this means the project should use `${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/<debug?>/lib` (which must be correct) instead of `$ENV{VCPKG_ROOT}/installed/${VCPKG_TARGET_TRIPLET}/<debug?>/lib` (which happened to work for some people). 
This still leaves room for trouble with handling debug vs. release. This can probably be avoided by relying on the vcpkg cmake toolchain's adjustment of `CMAKE_..._PATH` variables and using cmake's `find_...` accordingly.

**Comment by JackBoosY** [comment]
You can add environment variables by setting them manually, but we will not consider this feature so far.
Sorry.
