### ISSUE TITLE
[arrow] CMake Linker Usage?

### ISSUE THREAD

**Issue by xanderdunn** [microsoft/vcpkg#18538]
@ianmcook Thanks a lot for upgrading arrow to 4.0.0 in #17975.

I'm installing arrow 4.0.0 with `vcpkg install arrow[dataset,s3,parquet]`.

vcpkg prints this usage text after installation:
```
The package arrow:x64-linux provides CMake targets:

    find_package(arrow CONFIG REQUIRED)
    # Note: 9 target(s) were omitted.
    target_link_libraries(main PRIVATE LZ4::lz4 re2::re2 arrow_static zstd::libzstd)
```

When I add `find_package(Arrow CONFIG REQUIRED)` to my CMakeLists.txt, the linker doesn't find the library at all:
```
target_link_libraries(main PRIVATE arrow_static)
```
Linker error:
```
/usr/bin/ld: cannot find -larrow_static
```

I see the libs are at:
```
$ l vcpkg/installed/x64-linux/lib/ | grep arrow
-rw-r--r-- 1 xander xander   32M Jun 18 07:24 libarrow.a
-rw-r--r-- 1 xander xander  3.2M Jun 18 07:24 libarrow_dataset.a
```

What is the expected usage of linking against arrow using vcpkg? The given `arrow_static` isn't working for me.

**Comment by ianmcook** [comment]
Hi @xanderdunn, sorry I didn't see this earlier.

The CMake examples I have seen use `find_package(Arrow REQUIRED)`. Does that work? There's more info at https://arrow.apache.org/docs/cpp/build_system.html.

PS I just opened https://github.com/microsoft/vcpkg/pull/19229 to update the arrow port to 5.0.0.
