### ISSUE TITLE
Installed Tesseract does not work, unresolved external symbols

### ISSUE THREAD

**Issue by AdamMiltonBarker** [Microsoft/vcpkg#1853]
Hi guys back again :) 

I have issues with Tesseract now, it installed correctly:

```
Installing package tesseract:x64-windows... done

D:\Installations\vcpkg>vcpkg integrate install
Applied user-wide integration for this vcpkg root.
```
But I get the following:

```
1>d:\installations\vcpkg\installed\x64-windows\include\leptonica\pix.h(241): warning C4305: 'initializing': truncation from 'double' to 'l_float32'
1>d:\installations\vcpkg\installed\x64-windows\include\leptonica\pix.h(243): warning C4305: 'initializing': truncation from 'double' to 'l_float32'
1>LINK : warning LNK4098: defaultlib 'LIBCMTD' conflicts with use of other libs; use /NODEFAULTLIB:library
1>tesseract305.lib(svutil.cpp.obj) : error LNK2001: unresolved external symbol closesocket
1>tesseract305.lib(svutil.cpp.obj) : error LNK2001: unresolved external symbol connect
1>tesseract305.lib(svutil.cpp.obj) : error LNK2001: unresolved external symbol htons
1>tesseract305.lib(svutil.cpp.obj) : error LNK2001: unresolved external symbol recv
1>tesseract305.lib(svutil.cpp.obj) : error LNK2001: unresolved external symbol select
1>tesseract305.lib(svutil.cpp.obj) : error LNK2001: unresolved external symbol send
1>tesseract305.lib(svutil.cpp.obj) : error LNK2001: unresolved external symbol socket
1>tesseract305.lib(svutil.cpp.obj) : error LNK2001: unresolved external symbol gethostbyname
1>tesseract305.lib(svutil.cpp.obj) : error LNK2001: unresolved external symbol WSAStartup
fatal error LNK1120: 9 unresolved externals
```

Using code:

```
	char *outText;

	tesseract::TessBaseAPI *api = new tesseract::TessBaseAPI();
	// Initialize tesseract-ocr with English, without specifying tessdata path
	if (api->Init(NULL, "eng")) {
		fprintf(stderr, "Could not initialize tesseract.\n");
		exit(1);
	}
	PIX *image = pixCreate(imgGray.size().width, imgGray.size().height, 8);

	for (int i = 0; i<imgGray.rows; i++)
		for (int j = 0; j<imgGray.cols; j++)
			pixSetPixel(image, j, i, (l_uint32)imgGray.at<uchar>(i, j));

	api->SetImage(image);
	// Get OCR result
	outText = api->GetUTF8Text();
	printf("OCR output:\n%s", outText);
```

Any suggestions guys ?

**Comment by KindDragon** [comment]
Link also Ws2_32.lib

**Comment by AdamMiltonBarker** [comment]
OK thanks, thought VCPKG was suppose to handle all of the links ?

**Comment by AdamMiltonBarker** [comment]
I cannot find that, which package is it that needs installing, it does not exist in my installed folder.

**Comment by atkawa7** [comment]
@AdamMiltonBarker It comes with VS

**Comment by KindDragon** [comment]
> LINK : warning LNK4098: defaultlib 'LIBCMTD' conflicts with use of other libs; use /NODEFAULTLIB:library

BTW you should use dynamic linking CRT with `x64-windows` triplet

**Comment by AdamMiltonBarker** [comment]
OK thanks, this all pretty new to me, so how do I link that file? And do I use dynamic linking CRT triplet ? :D

**Comment by AdamMiltonBarker** [comment]
I found this: 

```
#define _WINSOCK_DEPRECATED_NO_WARNINGS
#include <WinSock2.h>
#pragma comment(lib, "WS2_32.lib")
```

This does not work the app just opens and closes when run.

**Comment by AdamMiltonBarker** [comment]
Hi guys I am not able to locate it:

C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise has no results for WS2_32.lib

**Comment by AdamMiltonBarker** [comment]
If I link the file in linker, the project just opens and shuts as before it will not work.

**Comment by KindDragon** [comment]
> And do I use dynamic linking CRT triplet ?

Yes tesseract:**x64-windows**

> This does not work the app just opens and closes when run.

So, it helped with your link error. But now you have a different error with your program.

**Comment by AdamMiltonBarker** [comment]
Have already done as shown by the output I posted in the first post:

```
Installing package tesseract:x64-windows... done

D:\Installations\vcpkg>vcpkg integrate install
Applied user-wide integration for this vcpkg root.
```

There is no link error it just crashed, I removed the exit() from the code and I see it is not finding the languages file, it is looking in the release folder.

**Comment by KindDragon** [comment]
> I see it is not finding the language file, it is looking in the release folder.

They available in different repository https://github.com/tesseract-ocr/tessdata/tree/3.04.00
I don't know much about Tesseract. I think better use tesseract mailing list for such questions https://github.com/tesseract-ocr/tesseract#support

**Comment by AdamMiltonBarker** [comment]
It is ok I know how to fix that, I have it setup and working in Python already, the last question remaining is about dynamic linking CRT triplet

**Comment by JackBoosY** [comment]
Hi @AdamMiltonBarker , thanks for reporting this issue!
I found nothing wrong with use tesseract by using your code.
Please open a new issue if this is still a problem for you.
Thx.
