### ISSUE TITLE
[arrow] Deprecated CMake Usage

### ISSUE THREAD

**Issue by xanderdunn** [microsoft/vcpkg#18537]
**Describe the bug**
`./vcpkg install arrow` with arrow 4.0.0 prints this usage text at the end:
```
The package arrow:x64-linux provides CMake targets:

    find_package(arrow CONFIG REQUIRED)
    # Note: 9 target(s) were omitted.
    target_link_libraries(main PRIVATE LZ4::lz4 re2::re2 arrow_static zstd::libzstd)
```

When using that in CMakeLists.txt, cmake 3.20.1 prints this message and exits:
```
CMake Warning at /home/xander/dev/vcpkg/installed/x64-linux/share/arrow/arrow-config.cmake:18 (message):
  find_package(arrow) is deprecated.  Use find_package(Arrow) instead.
Call Stack (most recent call first):
  /home/xander/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:764 (_find_package)
  CMakeLists.txt:13 (find_package)


CMake Error at /usr/local/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find arrow (missing: ARROW_INCLUDE_DIR) (found version "4.0.0")
Call Stack (most recent call first):
  /usr/local/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /home/xander/dev/vcpkg/installed/x64-linux/share/arrow/arrow-config.cmake:22 (find_package_handle_standard_args)
  /home/xander/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:764 (_find_package)
  CMakeLists.txt:13 (find_package)


-- Configuring incomplete, errors occurred!
```

**Environment**
- OS: Ubuntu 18.04
- Compiler: GCC 10.3.0

**To Reproduce**
1. `./vcpkg install arrow`
2. Add ` find_package(arrow CONFIG REQUIRED)` to CMakeLists.txt
3. Attempt to build

**Expected behavior**
vcpkg shouldn't recommend CMake usage that is deprecated or causes an error.

**Comment by ianmcook** [comment]
I suspect that this was resolved by https://github.com/microsoft/vcpkg/pull/19014 and the fix was preserved in the update to arrow 5.0.0 (https://github.com/microsoft/vcpkg/pull/19229). @xanderdunn please let us know if the problem persists for you.

**Comment by PhoebeHui** [comment]
@ianmcook, thanks for fixing this issue!

Currently, it looks provide correct cmake targets: 
```
The package arrow:x64-windows provides CMake targets:

    find_package(arrow CONFIG REQUIRED)
    target_link_libraries(main PRIVATE re2::re2 arrow_shared parquet_shared arrow_bundled_dependencies)
```

**Comment by dg0yt** [comment]
> `target_link_libraries(main PRIVATE LZ4::lz4 re2::re2 arrow_static zstd::libzstd)`

> `target_link_libraries(main PRIVATE re2::re2 arrow_shared parquet_shared arrow_bundled_dependencies)`

TBH neither looks like a proper cmake configuration. There should be a single target, not transitive usage requirements. 

But port arrow doesn't come with a usage file, so the output is auto-detected by vcpkg. This doesn't work reliably. In particular, it is unable to detect the right spelling (arrow vs. Arrow). I would recommend to look at upstream's documentation for cmake usage, verify with vcpkg, and add a proper usage file.

**Comment by PhoebeHui** [comment]
This issue has been fixed, please get latest source and try again.
