### ISSUE TITLE
[matplotplusplus] .cmake file not found by CMake

### ISSUE THREAD

**Issue by xanderdunn** [microsoft/vcpkg#18541]
**Describe the bug**
CMake can't find matplotplusplus' .cmake file during configuration after installation with vcpkg.

**Environment**
- OS: Ubuntu 18.04
- Compiler: GCC 10.3.0
- cmake 3.20.1

**To Reproduce**
1. ./vcpkg install matplotplusplus
2. Add to CMakeLists.txt: `find_package(Matplot++ CONFIG REQUIRED)`
3. Building with `cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=/home/xander/dev/vcpkg/scripts/buildsystems/vcpkg.cmake .` produces this error:
```
CMake Error at /home/xander/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:764 (_find_package):
  Could not find a package configuration file provided by "Matplot++" with
  any of the following names:

    Matplot++Config.cmake
    matplot++-config.cmake

  Add the installation prefix of "Matplot++" to CMAKE_PREFIX_PATH or set
  "Matplot++_DIR" to a directory containing one of the above files.  If
  "Matplot++" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:38 (find_package)


-- Configuring incomplete, errors occurred!
```

**Expected behavior**
Like other vcpkg installed libraries, I would expect this to be found without additional configuration.

**Additional context**
All of my other vcpkg-installed libraries are successfully found by cmake, I'm not sure what's different about this one.

I see one of the two named .cmake files exists on the system:
```
$ find / -name matplot++-config.cmake -print 2>/dev/null
/home/xander/dev/vcpkg/buildtrees/matplotplusplus/x64-linux-dbg/matplot++-config.cmake
/home/xander/dev/vcpkg/buildtrees/matplotplusplus/x64-linux-rel/matplot++-config.cmake
$ find / -name Matplot++Config.cmake -print 2>/dev/null
```
Any thoughts on why it exists only in the build tree and is not found by cmake? I would expect the .cmake file to end up in `vcpkg/installed/x64-linux/`, right?

**Comment by xanderdunn** [comment]
@myd7349

**Comment by xanderdunn** [comment]
Maybe it's a case sensitivity issue? cmake is looking for:
```
Matplot++Config.cmake
matplot++-config.cmake
```

But I'm finding these files:
```
$ l /home/xander/dev/vcpkg/installed/x64-linux/share/Matplot++/
total 24K
-rw-r--r-- 1 xander xander 8.0K Jun 18 11:47 FindFilesystem.cmake
-rw-r--r-- 1 xander xander 3.8K Jun 18 11:47 Matplot++Targets.cmake
-rw-rw-r-- 1 xander xander 1.4K Jun 18 11:47 Matplot++Targets-debug.cmake
-rw-r--r-- 1 xander xander 1.4K Jun 18 11:47 Matplot++Targets-release.cmake
-rw-r--r-- 1 xander xander 1.3K Jun 18 11:47 Matplot++-config.cmake
```
Notice `Matplot++-config.cmake != matplot++-config.cmake`

**Comment by xanderdunn** [comment]
I can confirm that Cmake finds the library and builds as expected when I rename the file:
```
cp ../vcpkg/installed/x64-linux/share/Matplot++/Matplot++-config.cmake ../vcpkg/installed/x64-linux/share/Matplot++/matplot++-config.cmake
```

**Comment by ajcressman** [comment]
Seconding this (and its solution).  Was just going to add an issue about it myself!

**Comment by JackBoosY** [comment]
Hi guys, can you please test my PR https://github.com/microsoft/vcpkg/pull/18583?

Thanks.

**Comment by myd7349** [comment]
Hi! @xanderdunn Is this work for you?
> cp ../vcpkg/installed/x64-linux/share/Matplot++/Matplot++-config.cmake ../vcpkg/installed/x64-linux/share/Matplot++/Matplot++-Config.cmake

**Comment by myd7349** [comment]
I guess it will also fix this issue by remove these lines:
https://github.com/microsoft/vcpkg/blob/c5ac711fefa6cacbd6bb6335349e36a765babf87/ports/matplotplusplus/portfile.cmake#L51-L54
