### ISSUE TITLE
[<sowin>] creat a new port and build failure

### ISSUE THREAD

**Issue by zhthree3** [microsoft/vcpkg#18548]
**Host Environment**
- OS: [Windows 10]
- Compiler: cmake version 3.20.4；vcpkg version 2021-05-05

**To Reproduce**
`./vcpkg install sowin:x64-windows`

**Failure logs** 
`-- Check size of LONG_PTR
-- Check size of LONG_PTR - done
CMake Error at CMakeLists.txt:279 (add_subdirectory):
  add_subdirectory given source "data" which is not an existing directory.

CMake Error at src/CMakeLists.txt:5 (add_subdirectory):
  add_subdirectory given source "Inventor/Win/common" which is not an
  existing directory.

CMake Error at CMakeLists.txt:286 (add_subdirectory):
  add_subdirectory given source "cpack.d" which is not an existing directory.

-- Configuring incomplete, errors occurred!
See also "D:/WorkSpace/vcpkg/buildtrees/sowin/x64-windows-dbg/CMakeFiles/CMakeOutput.log".
See also "D:/WorkSpace/vcpkg/buildtrees/sowin/x64-windows-dbg/CMakeFiles/CMakeError.log".
ninja: build stopped: subcommand failed.`

**Additional context**
Here is my vcpkg.json and portfile.cmake file：
1、vcpkg.json
`{
  "name": "sowin",
  "version-string": "1.6.0",
  "description": "Coin GUI binding for Win32.",
  "homepage": "https://github.com/coin3d/sowin"
}`

2、portfile.cmake
`vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO Coin3D/sowin
    REF SoWin-1.6.0
    SHA512 dbf680f71a26257ba970bd37df63b257602e1d2fc2594d7bf0e16ee0cfa72293a785620fa03e801e3fefe8cf8c44375893677590334235bcb2a58ab066337717
    HEAD_REF master
)

vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA	
)

vcpkg_install_cmake()
vcpkg_copy_pdbs()

file(INSTALL ${SOURCE_PATH}/COPYING DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)

file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/include)
file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/share)`

**Comment by JonLiu1993** [comment]
@zhthree3 ,Thanks for posting this issue,Please provide the error log :
````
See also "D:/WorkSpace/vcpkg/buildtrees/sowin/x64-windows-dbg/CMakeFiles/CMakeOutput.log".
See also "D:/WorkSpace/vcpkg/buildtrees/sowin/x64-windows-dbg/CMakeFiles/CMakeError.log".
````

**Comment by zhthree3** [comment]
> @zhthree3 ,Thanks for posting this issue,Please provide the error log :
> 
> ```
> See also "D:/WorkSpace/vcpkg/buildtrees/sowin/x64-windows-dbg/CMakeFiles/CMakeOutput.log".
> See also "D:/WorkSpace/vcpkg/buildtrees/sowin/x64-windows-dbg/CMakeFiles/CMakeError.log".
> ```
CMakeOutput.log：
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/6683867/config-x64-windows-out.log)
CMakeError.log is empty.

**Comment by NancyLi1013** [comment]
`sowin `is not in vcpkg now. Do you hope to add it in vcpkg or you just need help to solve the problems you encountered?

**Comment by NancyLi1013** [comment]
```
CMake Error at CMakeLists.txt:279 (add_subdirectory):
add_subdirectory given source "data" which is not an existing directory.

CMake Error at src/CMakeLists.txt:5 (add_subdirectory):
add_subdirectory given source "Inventor/Win/common" which is not an
existing directory.

CMake Error at CMakeLists.txt:286 (add_subdirectory):
add_subdirectory given source "cpack.d" which is not an existing directory.
```
These errors are caused by the same reason. Since the directories are pointed to the hyperlinks instead of being embedded to the `sowin `source codes. Namely, all these modules are third-party.

**Comment by zhthree3** [comment]
> `sowin `is not in vcpkg now. Do you hope to add it in vcpkg or you just need help to solve the problems you encountered?

The reason why I need help is that I hope to be able to upload sowin to vcpkg. In fact, it's not just sowin. I hope to upload all the packages of coin3d to vcpkg. Sowin is my first attempt.

**Comment by NancyLi1013** [comment]
Thanks for your reply. Currently, you can comment these modules out to rebuild if they are not required. Otherwise, you need to add these ports first. Since they are also not in vcpkg.

**Comment by PhoebeHui** [comment]
@zhthree3, please submit a PR for the port, and we can help reopen this issue, we're happy to answer any questions we can to support this effort, but for now we'd prefer to support your role as a maintainer than to take ownership ourselves. None of our core team is very familiar with sowin, so I feel you'll do a much better job than we could! consider making a pull request.
