### ISSUE TITLE
[OpenCV] unable to build for x86-windows

### ISSUE THREAD

**Issue by cenit** [Microsoft/vcpkg#1854]
After the very recent (desired and important) PR #1619 unfortunately OpenCV is impossible to build for x86-windows (which was a configuration available before, it is not nice to loose a build option), due to a second level dependency on openblas, which can be built only for x64 architectures
```
CMake Error at ports/openblas/portfile.cmake:16 (message):
  openblas can only be built for x64 currently
```
Was it intended? Or maybe before merging the PR was not tested? I already noticed the problem with that PR in issue #1744 but it went unnoticed (maybe I should have put it also on the PR thread?)

**Comment by jasjuang** [comment]
I only tested on x64. Openblas is a dependency opencv_contrib. Temporarily disable opencv_contrib in the portfile and it should build.

**Comment by ras0219-msft** [comment]
Should be fixed in the latest master. Thanks again for reporting, @cenit!
