### ISSUE TITLE
[opencv4] update to 4.5.2

### ISSUE THREAD

**Issue by Cazadorro** [microsoft/vcpkg#18540]
Library name: opencv4

New version number: upgrade from 4.5.1 -> 4.5.2

Other information that may be useful (release notes, etc...).  Opencv introduced a breaking change in 4.5.1 that ended up resulting in a bug that basically stopped the entire tracking module from working (literally doesn't build) if you used the "legacy API" (which also happened to be introduced in that version, and was a breaking change on its own, though solvable from the user side).  See https://github.com/opencv/opencv/issues/19260.  This was fixed in [4.5.2. ](https://github.com/opencv/opencv/pull/19817).

Here's another project whose had to deal with similar issues: https://github.com/OpenShot/libopenshot/pull/639, essentially this issue makes OpenCV 4.5.1 poison. 

With out this fix I literally cannot use VCPKG with OpenCV and will have to completely remove OpenCV from all team-member VCPKG distributions.

**Comment by cenit** [comment]
I can try to do it asap. Would you have time to help me, just in case?
