### ISSUE TITLE
[glib:x64-windows-static] build failure

### ISSUE THREAD

**Issue by lab313ru** [microsoft/vcpkg#18557]
**Host Environment**
- OS: Windows 10 x64

**To Reproduce**
`./vcpkg install gtk:x64-windows-static`

**Failure logs** 
```
Building package glib[core]:x64-windows-static...
-- Note: glib only supports dynamic library linkage. Building dynamic library.
CMake Error at scripts/cmake/vcpkg_check_linkage.cmake:47 (message):
  Refusing to build unexpected dynamic library against the static CRT.  If
  this is desired, please configure your triplet to directly request this
  configuration.
Call Stack (most recent call first):
  ports/glib/portfile.cmake:6 (vcpkg_check_linkage)
  scripts/ports.cmake:139 (include)


Error: Building package glib:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: glib:x64-windows-static
  Vcpkg version: 2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9
```

**Comment by JonLiu1993** [comment]
@lab313ru ,Thanks for posting this issue, 
gilb currentlly only suppurts DYNAMIC build:
````
# Glib relies on DllMain on Windows
if (VCPKG_TARGET_IS_WINDOWS)
    vcpkg_check_linkage(ONLY_DYNAMIC_LIBRARY)
    #remove if merged: https://gitlab.gnome.org/GNOME/glib/-/merge_requests/1655
endif()
````

**Comment by lab313ru** [comment]
Is it possible to make it build static too?

**Comment by JonLiu1993** [comment]
Someone mentioned the issue of Enable static builds on Windows using TLS callbacks in Upstream before, but it still hasn’t been successful for a long time.

> Is it possible to make it build static too?

Someone mentioned the [issue ](https://gitlab.gnome.org/GNOME/glib/-/merge_requests/1655)of _enable static builds on Windows using TLS callbacks_ in Upstream before, but it still hasn’t been successful for a long time.

**Comment by JackBoosY** [comment]
See related PR: https://github.com/microsoft/vcpkg/pull/16980.
The upstream doesn't support static build.

**Comment by JonLiu1993** [comment]
Because the three upstream PRs supporting static have been closed, this issue is temporarily closed, and I will reopen it if there is a new status upstream.
https://gitlab.gnome.org/GNOME/glib/-/merge_requests/1399
https://gitlab.gnome.org/GNOME/glib/-/merge_requests/1454
https://gitlab.gnome.org/GNOME/glib/-/merge_requests/1655
