### ISSUE TITLE
[New Port Request] telegram-bot-api

### ISSUE THREAD

**Issue by ffoxi** [microsoft/vcpkg#18559]
Library name:

Library description:The Telegram Bot API provides an HTTP API for creating Telegram Bots.

Source repository URL:https://github.com/tdlib/telegram-bot-api

Project homepage (if different from the source repository):https://core.telegram.org/bots/api

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

The Bot API is an HTTP-based interface created for developers keen on building bots for Telegram.

**Comment by TawalMc** [comment]
Hi. If I understand you want to port the telegram API to VCPKG ?

**Comment by ffoxi** [comment]
> Hi. If I understand you want to port the telegram API to VCPKG ?
yes

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by TawalMc** [comment]
Ok

**Comment by PhoebeHui** [comment]
We can’t reopen this issue until a PR is opened, we're happy to answer any questions we can to support this effort, but for now we'd prefer to support your role as a maintainer than to take ownership ourselves. None of our core team is very familiar with telegram-bot-api , so I feel you'll do a much better job than we could! consider making a pull request.

**Comment by TawalMc** [comment]
Thanks I understand.  I don't think I'll reopen again the issue will read
more about the port of mysql c++ connector
