### ISSUE TITLE
[New Port Request] enum-set

### ISSUE THREAD

**Issue by cdeln** [microsoft/vcpkg#18566]
Library name: enum-set

Library description: A library of type safe sets over fixed size collections of types or values, including methods for accessing, modifying, visiting and iterating over those.

Source repository URL: https://github.com/cdeln/cpp_enum_set

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
The library have en optional feature to use "magic-enum" library.

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
