### ISSUE TITLE
Trying to Build OpenCV 4.5.2 for GPU - Get Filename  Has Invalid Characters Error in vcpkg

### ISSUE THREAD

**Issue by RMLNZ** [microsoft/vcpkg#18561]
**Describe the bug**
Trying to Build OpenCV 4.5.2 for GPU on Windows. Getting Filename Has Invalid Characters Error in vcpkg

**Environment**
- OS:Windows 2019 Server (fully patched)

**To Reproduce**

USING CMD PROMPT:

C:\vcpkg\vcpkg>.\vcpkg create opencvgpu https:\\github.com/opencv/opencv/archive/4.5.2.zip https:\\github.com/opencv/opencv-contrib/archive/refs/tags/4.5.2.zip
Filename cannot contain invalid chars \/:*?"<>|, but was https:\\github.com/opencv/opencv-contrib/archive/refs/tags/4.5.2.zip

C:\vcpkg\vcpkg>.\vcpkg create opencvgpu https://github.com/opencv/opencv/archive/4.5.2.zip https://github.com/opencv/opencv-contrib/archive/refs/tags/4.5.2.zip
Filename cannot contain invalid chars \/:*?"<>|, but was https://github.com/opencv/opencv-contrib/archive/refs/tags/4.5.2.zip

USING POWERSHELL:

PS C:\vcpkg\vcpkg> .\vcpkg create opencvgpu https:\\github.com/opencv/opencv/archive/4.5.2.zip https:\\github.com/opencv/opencv-contrib/archive/refs/tags/4.5.2.zip
Filename cannot contain invalid chars \/:*?"<>|, but was https:\\github.com/opencv/opencv-contrib/archive/refs/tags/4.5.2.zip
PS C:\vcpkg\vcpkg>
PS C:\vcpkg\vcpkg> .\vcpkg create opencvgpu https://github.com/opencv/opencv/archive/4.5.2.zip https://github.com/opencv/opencv-contrib/archive/refs/tags/4.5.2.zip
Filename cannot contain invalid chars \/:*?"<>|, but was https://github.com/opencv/opencv-contrib/archive/refs/tags/4.5.2.zip
PS C:\vcpkg\vcpkg>

**Expected behavior**
vcpkg is meant to download the packages.

**Comment by NancyLi1013** [comment]
Hi @RMLNZ 

Thanks for posting this issue.

Seems you use an incorrect command to build. There are two URLs contained in your command. Please run `.\vcpkg create --help` to see the usage of `create `command.

**Comment by RMLNZ** [comment]
Hi @NancyLi1013 

I am following this advice:

https://vcpkg.io/en/docs/examples/packaging-zipfiles.html#create-the-manifest-file

and the command: .\vcpkg create zlib2 http://zlib.net/zlib-1.2.11.tar.gz zlib1211.tar.gz

There's a need to combine files from 2 sources for the opencv gpu enabled build - hence the attempt to use two URLs.

Please note that I logged another request for a GPU enabled version of opencv to be available on vcpkg.io site.

Your colleagues say that it's already there under opencv4 - that's not made clear in the package descriptions on the web site.

Sounds like we can close this.

Thanks so much.

**Comment by NancyLi1013** [comment]
Thanks for your above detailed information.

For `vcpkg create` command, currently it doesn't support the arguments like you used above.

For the description of opencv4, mostly we use the description from homepage, such as for opencv4, it is from [here](https://github.com/opencv/opencv/tree/4.5.2#opencv-open-source-computer-vision-library).  if you have other concerns, please open a new issue.
