### ISSUE TITLE
[opencv4] update to 4.5.2 to support feature GPU

### ISSUE THREAD

**Issue by RMLNZ** [microsoft/vcpkg#18562]
Library name: opencv

Library description: OpenCV computer vision library

Source repository URL: (including version)
https:\\github.com/opencv/opencv/archive/4.5.2.zip 
https:\\github.com/opencv/opencv-contrib/archive/refs/tags/4.5.2.zip

Project homepage (if different from the source repository): opencv.org

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

opencv will very commonly be used with GPU support.

**Comment by JackBoosY** [comment]
Does opencv4 in vcpkg not support GPU now?
cc @cenit

**Comment by cenit** [comment]
opencv[cuda] is well and alive. But the 4.5.2 update is still to-do (we are on 4.5.1 as of now)

**Comment by JackBoosY** [comment]
So I think we should wait for the official release then update opencv4 to 4.5.2.

**Comment by RMLNZ** [comment]
Thanks so much @JackBoosY 

Perhaps the descriptions could be clarified on vcpkg.io :)

<img width="658" alt="Capture" src="https://user-images.githubusercontent.com/8750005/122740777-6be6f880-d2d8-11eb-9380-b2fb6b882817.PNG">

**Comment by dg0yt** [comment]
FTR there is a "Feature List" link in the details for each port. However, some names and descriptions ask for improvement.

**Comment by JackBoosY** [comment]
Please keep this issue open untill opencv4 update to 4.5.2.

**Comment by cenit** [comment]
open cv is already at version 4.5.2

**Comment by JackBoosY** [comment]
Fixed by #18572.
