### ISSUE TITLE
CMake Unable to open .lib file

### ISSUE THREAD

**Issue by nlogozzo** [microsoft/vcpkg#18560]
Hi all,
I'm trying to compile my program using cmake. However, I'm getting an issue: `Error LNK1104: cannot open file 'jsoncpp.lib'`. If I remove the jsoncpp line, I get the error with curl and then curlpp. So I think I'm doing something wrong with my cmake file. All of the packages are installed via vcpkg. Here is my cmake file:
```
# CMakeList.txt : CMake project for NickvisionApplication5, include source and define
# project specific logic here.
#
cmake_minimum_required (VERSION 3.8)
set(CMAKE_CXX_STANDARD 17)

if(MSVC)
    add_definitions(-D_CRT_SECURE_NO_WARNINGS)
endif()

find_package(PkgConfig)
find_package(jsoncpp)
find_package(curl)
find_package(unofficial-curlpp CONFIG REQUIRED)

add_executable (NickvisionApplication5 "main.cpp" "Models/Update/Version.h" "Models/Update/Version.cpp" "Models/Update/UpdateConfig.h" "Models/Update/UpdateConfig.cpp" "Models/Update/Updater.h" "Models/Update/Updater.cpp" "Views/MainWindow.h" "Views/MainWindow.cpp")

pkg_check_modules(GTKMM_VARS REQUIRED IMPORTED_TARGET gtkmm-4.0)
target_link_libraries(NickvisionApplication5 PRIVATE PkgConfig::GTKMM_VARS)
target_link_libraries(NickvisionApplication5 PRIVATE jsoncpp)
target_link_libraries(NickvisionApplication5 PRIVATE curl)
target_link_libraries(NickvisionApplication5 PRIVATE curlpp)
```

**Comment by Neumann-A** [comment]
> `target_link_libraries(NickvisionApplication5 PRIVATE jsoncpp)`

needs either to be one of those:
`target_link_libraries(NickvisionApplication5 PRIVATE jsoncpp_lib)` (only for triplets with VCPKG_LIBRARY_LINKAGE = dynmaic)
`target_link_libraries(NickvisionApplication5 PRIVATE jsoncpp_static)` (only for triplets with VCPKG_LIBRARY_LINKAGE = static)
`target_link_libraries(NickvisionApplication5 PRIVATE jsoncpp_object)`
depending on your triplet


> Error LNK1104: cannot open file 'jsoncpp.lib'.

Note: Such an error always indicates your are not linking a target.

**Comment by JackBoosY** [comment]
Please use the following cmake code instead:
For dynamic jsoncpp (triplet doesn't contains `static`):
```cmake
    find_package(jsoncpp CONFIG REQUIRED)
    target_link_libraries(main PRIVATE jsoncpp_lib jsoncpp_object)
```
For static jsoncpp:
```cmake
    find_package(jsoncpp CONFIG REQUIRED)
    target_link_libraries(main PRIVATE jsoncpp_object jsoncpp_static)
```

**Comment by nlogozzo** [comment]
@JackBoosY The jsoncpp is now fixed using 
```
find_package(jsoncpp CONFIG REQUIRED)
target_link_libraries(NickvisionApplication5 PRIVATE jsoncpp_lib jsoncpp_object)
```
However curl and curlpp have the same issue unable to open the .lib file. I tried using the same example that you provided for jsoncpp for curl and curlpp, but it's not working.
Heres what I have currently:
```
find_package(curl CONFIG REQUIRED)
find_package(unofficial-curlpp CONFIG REQUIRED)
target_link_libraries(NickvisionApplication5 PRIVATE libcurl)
target_link_libraries(NickvisionApplication5 PRIVATE curlpp)
```

**Comment by nlogozzo** [comment]
Fixed all issues 
This is my final cmake file:
```cpp
# CMakeList.txt : CMake project for NickvisionApplication5, include source and define
# project specific logic here.
#
cmake_minimum_required (VERSION 3.8)
set(CMAKE_CXX_STANDARD 17)

if(MSVC)
    add_definitions(-D_CRT_SECURE_NO_WARNINGS)
endif()

find_package(PkgConfig)
find_package(jsoncpp CONFIG REQUIRED)
find_package(curl CONFIG REQUIRED)
find_package(unofficial-curlpp CONFIG REQUIRED)

add_executable (NickvisionApplication5 "main.cpp" "Models/Update/Version.h" "Models/Update/Version.cpp" "Models/Update/UpdateConfig.h" "Models/Update/UpdateConfig.cpp" "Models/Update/Updater.h" "Models/Update/Updater.cpp" "Views/MainWindow.h" "Views/MainWindow.cpp")

pkg_check_modules(GTKMM_VARS REQUIRED IMPORTED_TARGET gtkmm-4.0)
target_link_libraries(NickvisionApplication5 PRIVATE PkgConfig::GTKMM_VARS)
target_link_libraries(NickvisionApplication5 PRIVATE jsoncpp_lib jsoncpp_object)
target_link_libraries(NickvisionApplication5 PRIVATE CURL::libcurl)
target_link_libraries(NickvisionApplication5 PRIVATE unofficial::curlpp::curlpp)
```

**Comment by dg0yt** [comment]
Note that: 

> `find_package(jsoncpp CONFIG REQUIRED)`

finds a named *package* (via a cmake config file or cmake find module). You need to look into the documentation for that software or find module to see what it provides, because:

> `target_link_libraries(NickvisionApplication5 PRIVATE jsoncpp_lib jsoncpp_object)`

will try to link to the named *libraries*. Packages provide the libraries in different ways:
- as (imported) targets
- as variable containing the actual library name or target name.

Example: https://cmake.org/cmake/help/v3.19/module/FindCURL.html
