### ISSUE TITLE
[New Port Request] ImGUI 1.83

### ISSUE THREAD

**Issue by mises-games** [microsoft/vcpkg#18576]
Library name: ImGUI 1.83

Library description: Immediate Interfaces

Source repository URL:  https://github.com/ocornut/imgui

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by mises-games** [comment]
The port for the most recent stable ImGUI

**Comment by autoantwort** [comment]
Is is already there?

https://github.com/microsoft/vcpkg/blob/master/ports/imgui/vcpkg.json

**Comment by mises-games** [comment]
Sorry
