### ISSUE TITLE
[sdl2] update to 2.0.15

### ISSUE THREAD

**Issue by mises-games** [microsoft/vcpkg#18578]
Library name: sdl2

New version number: 2.0.15

Other information that may be useful (release notes, etc...)

**Comment by JonLiu1993** [comment]
@mises-games ,Thanks posting this issue,the latest version of sdl2 is [2.0.14](https://www.libsdl.org/release/?C=M;O=A), and 2.0.15 has not been released yet, so I will upgrade to version 2.0.14

**Comment by mises-games** [comment]
I made a mistake, sorry

**Comment by JonLiu1993** [comment]
@mises-games ,I will close this issue for now, please reopen this issue after the 2.0.15 certificate version is released
