### ISSUE TITLE
[Matplotplusplus] CMake can't find the package configuration file

### ISSUE THREAD

**Issue by remz1337** [microsoft/vcpkg#18573]
**Describe the bug**
Building my program with CMake throws this error: 
```
Could not find a package configuration file provided by "Matplot++" with  any of the following names:
    Matplot++Config.cmake
    matplot++-config.cmake
```

**Environment**
- OS: Ubuntu 20.04 on WSL2 (Windows 10 x64)
- Compiler: gcc 9.3

**To Reproduce**
1. install matplotplusplus
2. call find_package in CMakeLists.txt
3. build project with CMake

**Expected behavior**
Build the program successfully

**Additional context**
I also have vcpkg installed in Windows 10. I am able to build with CMake successfully in Windows and program runs fine. I deployed Ubuntu through WSL and cloned vcpkg inside my home directory. The package installs successfully but when I tried to build, I get that error.

I digged in the installation folder (.../vcpkg/installed/x64-linux/shared/Matplot++/) and found out that the config file isn't named like specified in the error. I found `Matplot++-config.cmake` (with capital M) instead of `matplot++-config.cmake`. I renamed the file and it fixed the error

**Comment by JackBoosY** [comment]
Confirmed.

**Comment by dg0yt** [comment]
Duplicate of #18541?

**Comment by JackBoosY** [comment]
@dg0yt  Yes, thanks.

Please track #18541.
