### ISSUE TITLE
[fltk] build failure

### ISSUE THREAD

**Issue by zcream** [microsoft/vcpkg#18586]
**Host Environment**
- OS: High Sierra 10.13.6 mac
- Compiler: 

**To Reproduce**
`./vcpkg install fltk`

**Failure logs** 
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:146 (message):
    Command failed: /usr/local/Cellar/cmake/3.20.5/bin/cmake --build . --config Debug --target install -- -v -j5
    Working Directory: /usr/local/Cellar/vcpkg/2021.05.12/libexec/buildtrees/fltk/x64-osx-dbg
    See logs for more information:
      /usr/local/Cellar/vcpkg/2021.05.12/libexec/buildtrees/fltk/install-x64-osx-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:104 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:44 (vcpkg_build_cmake)
  ports/fltk/portfile.cmake:42 (vcpkg_install_cmake)
  scripts/ports.cmake:142 (include)

Error: Building package fltk:x64-osx failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: fltk:x64-osx
  Vcpkg version: 2021-05-05-unknownhash

Additionally, attach any relevant sections from the log files above.
[install-x64-osx-dbg-out.log](https://github.com/microsoft/vcpkg/files/6693262/install-x64-osx-dbg-out.log)

**Additional context**
fresh install of homebrew and vcpkg.

**Comment by zcream** [comment]
There are a couple of possibly related issues https://github.com/microsoft/vcpkg/issues/8627 https://github.com/microsoft/vcpkg/pull/11205 https://github.com/microsoft/vcpkg/issues/9321

**Comment by zcream** [comment]
One suggested solution is the usage of ninja 1.9 - how would I use that ?
Currently vcpkg is using an external ninja version - possibly from XCode.
`-- Found external ninja('1.10.2').`

**Comment by NancyLi1013** [comment]
Hi @zcream 

Thanks for posting this issue.

```
/usr/local/Cellar/vcpkg/2021.05.12/libexec/buildtrees/fltk/src/fltk-1-7591e64af8.clean/src/Fl_cocoa.mm:716:3: error: cannot find protocol declaration for 'CALayerDelegate'; did you mean 'NSDrawerDelegate'?
< CALayerDelegate >
  ^~~~~~~~~~~~~~~
  NSDrawerDelegate
```

```
/usr/local/Cellar/vcpkg/2021.05.12/libexec/buildtrees/fltk/src/fltk-1-7591e64af8.clean/src/Fl_cocoa.mm:4879:30: error: use of undeclared identifier 'version'; did you mean 'Fl::version'?
    NSOperatingSystemVersion version = [[NSProcessInfo processInfo] operatingSystemVersion];
                             ^~~~~~~
                             Fl::version
```
 
Seems there is no `CALayerDelegate` found on your machine. `CALayerDelegate` is available on these 

```
Availability

iOS 10.0+
macOS 10.12+
Mac Catalyst 13.0+
tvOS 10.0+
```
Please see https://developer.apple.com/documentation/quartzcore/calayerdelegate

**Comment by zcream** [comment]
I updated to Catalina 10.15 due to the warning of an older OS. I still get a build error - though for something different.
```
-- Generating configure for x64-osx
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
    Command failed: /usr/local/bin/autoreconf -vfi
    Working Directory: /usr/local/Cellar/vcpkg/2021.05.12/libexec/buildtrees/fontconfig/src/75c13b2421-12bdc6f9c0.clean/
    Error code: 2
    See logs for more information:
      /usr/local/Cellar/vcpkg/2021.05.12/libexec/buildtrees/fontconfig/autoconf-x64-osx-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:600 (vcpkg_execute_required_process)
  ports/fontconfig/portfile.cmake:26 (vcpkg_configure_make)
  scripts/ports.cmake:142 (include)


Error: Building package fontconfig:x64-osx failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: fontconfig:x64-osx
  Vcpkg version: 2021-05-05-unknownhash

Additionally, attach any relevant sections from the log files above.

```

**Comment by NancyLi1013** [comment]
Could you please provide the error log from _/usr/local/Cellar/vcpkg/2021.05.12/libexec/buildtrees/fontconfig/autoconf-x64-osx-err.log_?

**Comment by zcream** [comment]
Hi. I gave up on Vcpkg in macOS and just used home-brew. Thanks.
