### ISSUE TITLE
How to add the lib to my project afterwards

### ISSUE THREAD

**Issue by Manfred-O** [microsoft/vcpkg#18588]
Hi, 
i am quit new in vcpkg so i have some basic questions. I have already started my project and could include the json-c and paho-mqtt libraries with help of the vcpkg manager. But now i like to add the sqlite library. I was able to download and install it and when starting a new project i could successfully build. But it is not recognized in my project i already set up. I think it can not find the library because there are plenty red underlining function declerations inside the header files. But when starting a new projects it seems to work well. What is the correct process to add libraries afterwards?

**Comment by JackBoosY** [comment]
Tha's depends on your custom build system.
1. For cmake, use vcpkg toolchain.
2. For msbuild, you only need to intergrate with msbuild.

 For more details please see [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/users/integration.md#buildsystem-integration).

**Comment by NancyLi1013** [comment]
Please feel free to reopen this issue if it is still a problem for you.
