### ISSUE TITLE
[opencv4:x64-windows] build failure

### ISSUE THREAD

**Issue by freprec** [microsoft/vcpkg#18587]
**Host Environment**
- OS: Windows10
- Compiler: VS2017

**To Reproduce**
`.\vcpkg.exe install OpenCV:x64-windows`

**Failure logs** 

```
Computing installation plan...
The following packages will be built and installed:
    opencv[core,dnn,jpeg,png,quirc,tiff,webp]:x64-windows -> 4.5.2
  * opencv4[core,dnn,jpeg,png,quirc,tiff,webp]:x64-windows -> 4.5.2
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\xyz\AppData\Local\vcpkg\archives\d1\d1967d73138de6cf7e6bf32b3c56573f6db9617a.zip
Could not locate cached archive: C:\Users\xyz\AppData\Local\vcpkg\archives\e4\e43f209b1002be9716f806691de05ecd61c07660.zip
Starting package 1/2: opencv4:x64-windows
Building package opencv4[core,dnn,jpeg,png,quirc,tiff,webp]:x64-windows...
-- Using C:/Lib/vcpkg/downloads/opencv-opencv-4.5.2.tar.gz
-- Cleaning sources at C:/Lib/vcpkg/buildtrees/opencv4/src/4.5.2-755f235ba0.clean. Use --editable to skip cleaning for the packages you specify.
-- Using source at C:/Lib/vcpkg/buildtrees/opencv4/src/4.5.2-755f235ba0.clean
-- Using C:/Lib/vcpkg/downloads/opencv-cache/tiny_dnn/adb1c512e09ca2c7a6faef36f9c53e59-v1.0.0a3.tar.gz
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
    Command failed: ninja -v
    Working Directory: C:/Lib/vcpkg/buildtrees/opencv4/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\Lib\vcpkg\buildtrees\opencv4\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:323 (vcpkg_execute_required_process)
  ports/opencv4/portfile.cmake:312 (vcpkg_configure_cmake)
  scripts/ports.cmake:139 (include)


Error: Building package opencv4:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: opencv4:x64-windows
  Vcpkg version: 2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9
```

[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/6694162/config-x64-windows-out.log)

**Additional context**
The x86 package installs fine.

**Comment by treigilbert** [comment]
Getting the same errors:

Host Environment
OS: Windows 10
Compiler: VS2019

.\vcpkg.exe install opencv[dnn,sfm,contrib,cuda,ffmpeg,openexr,tiff,png,jpeg,jasper,eigen,webp]

CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
    Command failed: ninja -v
    Working Directory: E:/Code/penelope/vcpkg/buildtrees/opencv4/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      E:\Code\penelope\vcpkg\buildtrees\opencv4\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:323 (vcpkg_execute_required_process)
  ports/opencv4/portfile.cmake:312 (vcpkg_configure_cmake)
  scripts/ports.cmake:139 (include)


Error: Building package opencv4:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: opencv4:x64-windows
  Vcpkg version: 2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9

**Comment by bgtwoigu** [comment]
Seems I met  the same error, related logs below:

-- NVIDIA_OPTICAL_FLOW: Download: edb50da3cf849840d680249aa6dbef248ebce2ca.zip
CMake Error at D:/vcpkg/buildtrees/opencv4/src/4.5.2-755f235ba0.clean/cmake/OpenCVDownload.cmake:161 (message):
      Downloads are not permitted during configure. Please pre-download the file "D:/vcpkg/downloads/opencv-cache/nvidia_optical_flow/a73cd48b18dcc0cc8933b30796074191-edb50da3cf849840d680249aa6dbef248ebce2ca.zip":
      
      vcpkg_download_distfile(OCV_DOWNLOAD
          URLS "https://github.com/NVIDIA/NVIDIAOpticalFlowSDK/archive/edb50da3cf849840d680249aa6dbef248ebce2ca.zip"
          FILENAME "opencv-cache/nvidia_optical_flow/a73cd48b18dcc0cc8933b30796074191-edb50da3cf849840d680249aa6dbef248ebce2ca.zip"
          SHA512 0
      )
Call Stack (most recent call first):
  D:/vcpkg/buildtrees/opencv4/src/4.5.2-58c4f07550.clean/modules/cudaoptflow/CMakeLists.txt:15 (ocv_download)


-- Configuring incomplete, errors occurred!
See also "D:/vcpkg/buildtrees/opencv4/x64-windows-dbg/CMakeFiles/CMakeOutput.log".
See also "D:/vcpkg/buildtrees/opencv4/x64-windows-dbg/CMakeFiles/CMakeError.log".
ninja: build stopped: subcommand failed.

Manually downloading and renaming files seems to work temporarily.

**Comment by JonLiu1993** [comment]
@freprec, thanks for posting this question, I can successfully install opencv4:x64-windows on my local machine.
Please delete cached file then try install again.

**Comment by freprec** [comment]
I deleted all contents of `C:\Users\xyz\AppData\Local\vcpkg\archives\` which seems to have fixed the problem.
Thank you!

**Comment by bgtwoigu** [comment]
download https://github.com/NVIDIA/NVIDIAOpticalFlowSDK/archive/edb50da3cf849840d680249aa6dbef248ebce2ca.zip and place it to opencv-cache/nvidia_optical_flow/a73cd48b18dcc0cc8933b30796074191-edb50da3cf849840d680249aa6dbef248ebce2ca.zip may help.

It seems the URL in portfile.cmake (“https://github.com/NVIDIA/NVIDIAOpticalFlowSDK/archive/79c6cee80a2df9a196f20afd6b598a9810964c32.zip”) should be “https://github.com/NVIDIA/NVIDIAOpticalFlowSDK/archive/edb50da3cf849840d680249aa6dbef248ebce2ca.zip”
