### ISSUE TITLE
How do I build the apriltag library in the ARM64 version?

### ISSUE THREAD

**Issue by FilippoCinotti** [microsoft/vcpkg#18589]
I was only able to obtain the x64 and x86 version of the library.

**Comment by autoantwort** [comment]
Same as for x64 or x86 but you say arm64

**Comment by FilippoCinotti** [comment]
Where di you write it @autoantwortaa?

**Comment by FilippoCinotti** [comment]
Where do you write it @autoantwort?

**Comment by autoantwort** [comment]
If you are using [manifest mode](https://github.com/microsoft/vcpkg/blob/master/docs/users/manifests.md) `./vcpkg install --triplet=arm64-windows`

**Comment by FilippoCinotti** [comment]
![image](https://user-images.githubusercontent.com/63125253/122989557-3ce98900-d3a3-11eb-91a3-c8fb8997ee4d.png)

I got this error :(

**Comment by autoantwort** [comment]
And what does the error log say?

**Comment by JonLiu1993** [comment]
@FilippoCinotti ,Thanks for posting this issue.
could you please provide error log:

**Comment by FilippoCinotti** [comment]
I am trying to export the apriltag library in arm64-uwp. The error I got is this:
![image](https://user-images.githubusercontent.com/63125253/123593037-526d1180-d7ee-11eb-926f-e0bb03d07413.png)
When looking at the error log:
[install-arm64-uwp-dbg-out.log](https://github.com/microsoft/vcpkg/files/6724063/install-arm64-uwp-dbg-out.log)

**Comment by dg0yt** [comment]
~~~
C:\dev\vcpkg\buildtrees\opencv4\src\4.5.2-755f235ba0.clean\modules\imgcodecs\src\grfmt_tiff.cpp(573,33): error C4996: 'tiff_dummy_namespace::uint32': libtiff type deprecated; please use corresponding C99 stdint.h type
~~~

libtiff uses a standard types now. There was one port where CI reported error C4996, and it was resolved by adding the `/wd4996` compiler option: 
https://github.com/microsoft/vcpkg/blob/master/ports/selene/tiff-deprecated-typedefs.patch

**Comment by FilippoCinotti** [comment]
![image](https://user-images.githubusercontent.com/63125253/123600645-286c1d00-d7f7-11eb-9d65-c16557496dcf.png)

I just have it!

**Comment by JonLiu1993** [comment]
@FilippoCinotti ,Is this issue solved?

**Comment by FilippoCinotti** [comment]
No no it is not

**Comment by FilippoCinotti** [comment]
@dg0yt @JonLiu1993 I still got the same error

**Comment by FilippoCinotti** [comment]
And why apriltag has been removed from ports?

**Comment by dg0yt** [comment]
Removed? Did it exist? https://github.com/microsoft/vcpkg/search?q=apriltag

**Comment by FilippoCinotti** [comment]
Yeah it was on the list but I could not find it anymore now

**Comment by dg0yt** [comment]
@FilippoCinotti I did read my search results. #12171 is a "New Port Request" (i.e. wish), not even a pull request (i.e. code). 

So no, there was no port apriltag in the vcpkg repository. This issue is not valid.

**Comment by FilippoCinotti** [comment]
I am sure it did exist, I have it in my ports

**Comment by dg0yt** [comment]
> I am sure it did exist, I have it in my ports
> 
> https://github.com/ooeygui/vcpkg/tree/master/ports/apriltag

https://github.com/ooeygui/vcpkg/commits/master/ports/apriltag

Nothing from https://github.com/microsoft/vcpkg.

**Comment by FilippoCinotti** [comment]
So, you mean I could not use that?

**Comment by dg0yt** [comment]
> So, you mean I could not use that?

I mean that it is not true that "apriltag has been removed from ports". You can use it as an overlay port with the original vcpkg repository. 
Here, opencv4 with tiff builds successfully for x64-uwp, arm64-windows, and arm-uwp in CI. But https://github.com/ooeygui/vcpkg/ has older versions.

**Comment by FrankXie05** [comment]
@FilippoCinotti We are sorry for the addition and use of port `apriltag`, you can use the suggestion given by `dg0yt`, we will add this port as soon as possible and notify you as soon as possible. If you have any problems during use, please reopen and reply to me . :)

**Comment by N0RAIR** [comment]
Anything new? its still not added
