### ISSUE TITLE
Automatically add pkg-config path to PKG_CONFIG_PATH environment variable

### ISSUE THREAD

**Issue by octowaddle** [microsoft/vcpkg#18585]
****

**Is your feature request related to a problem? Please describe.**
After installing a library with Vcpkg, you have to add the pkg-config directory manually to the PKG_CONFIG_PATH environment variable, so that pkg-config can find it.

**Proposed solution**
Vcpkg should create and automatically add the pkg-config path to the PKG_CONFIG_PATH environment variable.

**Additional context**
This makes usage with other build systems like Meson or Make easier.

**Comment by JackBoosY** [comment]
cc @Neumann-A

**Comment by Neumann-A** [comment]
No because vcpkg should not modify the users environment. For meson at least vcpkg might provide an integration via a native/cross file with the required setting. For pure make there is no such thing.

**Comment by NancyLi1013** [comment]
Closing this issue for now based on the above comments. Please feel free to reopen this issue if it is still a problem for you.
