### ISSUE TITLE
Why are packages being removed in manifest mode when switching between static vs dynamic?

### ISSUE THREAD

**Issue by thxkiwi** [microsoft/vcpkg#18599]
I've recently read almost all of the vcpkg documentation (because I've just setup vcpkg to use internally for my organization and also externally with a private registry to distribute binary only versions of our client libraries to our customers) and I have yet to find anything that covers why this happens.

I have a Visual Studio solution that builds a library and a googletest executable for unit tests of that library. The VS solution has build configurations for both statically and dynamically linking the runtime. 

I build, say, static release and vcpkg in manifest mode places all of the dependencies in vcpkg_installed/x64-windows-static as expected. 
However, I now switch from static release to dynamic release, and rebuild. vcpkg in manifest mode removes all of the dependencies and rebuilds them for static... however it leaves behind one dependency still in the x64-windows-static directory.

As I switch back and forth vcpkg deletes and rebuilds (although it is using binary caching) the packages for static vs. dynamic every time.

My question is whether this is expected behavior? Why does vcpkg rebuild between static versus dynamic every time when it stores the triple under vcpkg_installed anyway?

Any and all help and guidance is appreciated.

>1>------ Rebuild All started: Project: libEvents, Configuration: DynamicRelease x64 ------
1>Installing vcpkg dependencies to F:\src\repo\vcpkg_installed\
1>"F:\src\vcpkg\scripts\buildsystems\msbuild\..\..\..\vcpkg.exe" install  --x-wait-for-lock --triplet "x64-windows" --vcpkg-root "F:\src\vcpkg\scripts\buildsystems\msbuild\..\..\..\\" "--x-manifest-root=F:\src\repo\\" "--x-install-root=F:\src\repo\vcpkg_installed\\"
1>Detecting compiler hash for triplet x64-windows...
1>The following packages will be removed:
1>    cppzmq:x64-windows-static
1>    czmq:x64-windows-static
1>    gtest:x64-windows-static
1>    protobuf:x64-windows-static
1>    zeromq:x64-windows-static
1>    zyre:x64-windows-static
1>The following packages will be built and installed:
1>    cppzmq[core]:x64-windows -> 4.7.1#1
1>    czmq[core]:x64-windows -> 2019-06-10-4
1>    gtest[core]:x64-windows -> 1.11.0
1>    zeromq[core]:x64-windows -> 4.3.4
1>    zyre[core]:x64-windows -> 2019-07-07-1

And then when I switch back to static

>1>------ Rebuild All started: Project: libEvents, Configuration: Release x64 ------
1>Installing vcpkg dependencies to F:\src\repo\vcpkg_installed\
1>"F:\src\vcpkg\scripts\buildsystems\msbuild\..\..\..\vcpkg.exe" install  --x-wait-for-lock --triplet "x64-windows-static" --vcpkg-root "F:\src\vcpkg\scripts\buildsystems\msbuild\..\..\..\\" "--x-manifest-root=F:\src\repo\\" "--x-install-root=F:\src\repo\vcpkg_installed\\"
1>Detecting compiler hash for triplet x64-windows-static...
1>Detecting compiler hash for triplet x64-windows...
1>The following packages will be removed:
1>    cppzmq:x64-windows
1>    czmq:x64-windows
1>    gtest:x64-windows
1>    zeromq:x64-windows
1>    zyre:x64-windows
1>The following packages will be built and installed:
1>    cppzmq[core]:x64-windows-static -> 4.7.1#1
1>    czmq[core]:x64-windows-static -> 2019-06-10-4
1>    gtest[core]:x64-windows-static -> 1.11.0
1>    protobuf[core]:x64-windows-static -> 3.15.8#2
1>    zeromq[core]:x64-windows-static -> 4.3.4
1>    zyre[core]:x64-windows-static -> 2019-07-07-1

Manifest is as follows;

>{
  "$schema": "https://raw.githubusercontent.com/microsoft/vcpkg/master/scripts/vcpkg.schema.json",
  "name": "my-project",
  "version": "1.0.0",
  "description": "Names have been changed to protect the innocent.",
  "supports": "windows",
  "dependencies": [
    {
      "name": "czmq"
    },
    {
      "name": "zeromq"
    },
    {
      "name": "cppzmq"
    },
    {
      "name": "zyre"
    },
    {
      "name": "protobuf"
    },
    {
      "name": "gtest"
    }
  ]
}

**Comment by Neumann-A** [comment]
Because you are switching triplets from `x64-windows` to `x64-windows-static` (or vice versa) using the same vcpkg_installed directory. If you don't want to have that behavior you need to set different vcpkg_installed dirs for the different triplets.

**Comment by thxkiwi** [comment]
@Neumann-A that would make sense to me. What's confusing here is that google protobuf is leaving behind artifacts in _the same vcp_installed_ when switching triples. I observe this when switching dynamic/static and also when switching x86/x64. I realize Google's protobuf may not be a port you maintain and I'm wondering if you can think of any reason why that would happen? Could it be something that I have configured incorrectly?

**Comment by Neumann-A** [comment]
> . What's confusing here is that google protobuf is leaving behind artifacts in the same vcp_installed when switching triples. I observe this when switching dynamic/static and also when switching x86/x64. 

You probably have a host dependency on `protobuf` and the default host-triplet is `x64-windows`

**Comment by thxkiwi** [comment]
> > . What's confusing here is that google protobuf is leaving behind artifacts in the same vcp_installed when switching triples. I observe this when switching dynamic/static and also when switching x86/x64.
> 
> You probably have a host dependency on `protobuf` and the default host-triplet is `x64-windows`

Thank you; I'll look into it.

**Comment by thxkiwi** [comment]
> > . What's confusing here is that google protobuf is leaving behind artifacts in the same vcp_installed when switching triples. I observe this when switching dynamic/static and also when switching x86/x64.
> 
> You probably have a host dependency on `protobuf` and the default host-triplet is `x64-windows`

Turns out protobuf itself has the host dependency. Makes sense since protobuf has to be able to generate C++ code from the proto source. So, what was confusing me was that protobuf builds its "proto" to C++ compiler for the host and the host triplet is indeed x64-windows.
