### ISSUE TITLE
[uwebsockets] support feature ssl

### ISSUE THREAD

**Issue by vp00** [microsoft/vcpkg#18598]
Hi,

uwebsockets exposes two server builders - `uWS::App` and `uWS::SSLApp`. From inspecting the source, if I'm not mistaken, the difference is the value passed to the underlying socket library, usockets.

This touches my second issue. Installing this port does not automatically install usockets, you have to do so manually. No problem, I installed usockets[ssl] to also get ssl support. This could perhaps be fixed by adding usockets a dependency?

However, when I try to start a server from SSLApp, it acts like a normal unsecured server. During troubleshooting, I read somewhere that when SSL support wasn't available, SSLApp acted as a regular app. This seems to be further confirmed by websocket debugging tools failing to connect when the protocol is specified as wss:// ("ssl handshake timed out", or similar), but work without issue when changing to ws://

It seems I am not the only vcpkg user with this issue:

https://github.com/uNetworking/uWebSockets/issues/1161

I suspect usockets[ssl] to be troublesome part, but that is mere speculation. Maybe someone else has an idea.

Thanks!

**Comment by JonLiu1993** [comment]
@vp00, Currently, there is a problem with the SSL feature upstream. I have investigated and found that it has not been resolved yet, so I will temporarily close this issue. If there is any new progress, please ping me and I will open it again.
