### ISSUE TITLE
zlib build failure

### ISSUE THREAD

**Issue by johnmichaloski** [microsoft/vcpkg#18606]
**Host Environment**
- OS: Windows 10
- Compiler: msvc 2019 community

**To Reproduce**
`vcpkg install zlib`

**Failure logs** 
`Error: Building package zlib:x64-windows failed with: BUILD_FAILED`

c:\opt\ros\noetic\ariac_ws>`more C:\opt\ros\noetic\x64\tools\vcpkg\buildtrees\zlib\msys-pacman-x64-windows-err.log`
`error: pkg-config: signature from "David Macek <david.macek.0@gmail.com>" is unknown trust
error: failed to commit transaction (invalid or corrupted package (PGP signature))`

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.
`Was trying to install libxml2 and it requires zlib, and it stops on this error. Using vcpkg from ROS1 noetic on Windows found in C:\opt\ros\noetic\x64\tools\vcpkg\ports.`

TIA.

**Comment by JonLiu1993** [comment]
@johnmichaloski ,Thanks for posting this issue.
````
msys-pacman-x64-windows-err.log
````
It seems that your error is related to MSYS2-packages. According to the official [comments](https://github.com/msys2/msys2.github.io/pull/104#issuecomment-782710642), it may be related to the old version. You can try to update the version.
The following issue is the same as your error and has been successfully resolved, you can refer to it
[#2058](https://github.com/msys2/MSYS2-packages/issues/2058)

**Comment by johnmichaloski** [comment]
Ok thanks. I played around but couldn't get it to work  - there was no windows compatible pacman-key  and I'm really a newbie to a lot of this stuff. Wasn't looking promising. Plus vcpkg,msys2, and pacman are embedded deeply in the MS deployment of ROS and since there is no pacman-key, so I will ask the MS ROS for windows git issues for help.

**Comment by JonLiu1993** [comment]
> Ok thanks. I played around but couldn't get it to work - there was no windows compatible pacman-key and I'm really a newbie to a lot of this stuff. Wasn't looking promising. Plus vcpkg,msys2, and pacman are embedded deeply in the MS deployment of ROS and since there is no pacman-key, so I will ask the MS ROS for windows git issues for help.

Okay, I will continue to track and investigate the solution

**Comment by JonLiu1993** [comment]
@johnmichaloski ，You can update vcpkg and try again. If it doesn’t work, you can try to clone vcpkg again, which may solve your problem.

**Comment by JonLiu1993** [comment]
@johnmichaloski ,Is this still a problem for you？

**Comment by johnmichaloski** [comment]
So, reinstalling vcpkg did install libxml2.

#  Steps to Install libxml2
Problem: ROS1 used old open source packages in the bundled vcpkg. So had to download and clone vcpkg that had the latest packagers for zlib (David Macek with signing key 0x9078f532) required by libxml2, which is the package used in a ROS1 workspace.
## Step 1: Clone the vcpkg repo (From vcpkg windows install instructions)
```
cd C:\opt
git clone https://github.com/Microsoft/vcpkg.git
```
Make sure you are in the directory you want the tool installed to before doing this.
## Step 2: Run the bootstrap script to build vcpkg
.\vcpkg\bootstrap-vcpkg.bat
## Step 3: Setup use of VC 2019 community
Previously had downloaded VC 2019 community to be used aa command line build tool for ROS1. Note: had bundled ROS1 and VC 2019 in PATH environment variable.  So created separate command terminal: and then 
`C:\Windows\System32\cmd.exe /k "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\VsDevCmd.bat" -arch=amd64 -host_arch=amd64`
Just assumed it was needed. 
## Step 4: Install libxml2
`C:\opt\vcpkg>.\vcpkg install libxml2`
This worked with the new packager download hash credentials.
## Packages installed in C:\opt\vcpkg\installed\x86-windows  Have not tested.
