### ISSUE TITLE
How do I install ImGui with docking?

### ISSUE THREAD

**Issue by mises-games** [microsoft/vcpkg#18609]

**Comment by NancyLi1013** [comment]
Hi @mises-games 

Thanks for posting this issue.

Currently, docking branch is still in testing. https://github.com/ocornut/imgui/issues/2109

We add a feature `docking-experimental` in vcpkg. So you can install it via `vcpkg install imgui[docking-experimental]`.

**Comment by NancyLi1013** [comment]
Closing this issue for now since there is no active thread for a long time. Please feel free to reopen this issue if it is still a problem for you.

**Comment by Jehudme** [comment]
How can I do it from vcpk.json file?

**Comment by ylvgn** [comment]
> How can I do it from vcpk.json file?
**vcpk.json**
```json
{
  "dependencies": [
	{
		"name": "imgui",
		"features": ["docking-experimental"]
	}
  ]
}
```

**Comment by sfhacker** [comment]
This issue is from 2021!
