### ISSUE TITLE
Trying to update socket-io-client but got `Cannot open include file`

### ISSUE THREAD

**Issue by ysc3839** [microsoft/vcpkg#18603]
I'm working on updating socket-io-client to version 3.0.0.
After update source version, it failed with `fatal error C1083: Cannot open include file: 'websocketpp/client.hpp': No such file or directory`.
But `websocketpp/client.hpp` is exist in `C:\vcpkg\installed\x64-windows-static\include`. How to solve this issue?

Commit with issue: https://github.com/ysc3839/vcpkg/commit/0f1c3c6c79abe6207aac7ff06c3135432e03b61b
Error log: [install-x64-windows-static-dbg-out.log](https://github.com/microsoft/vcpkg/files/6701033/install-x64-windows-static-dbg-out.log)

**Comment by JonLiu1993** [comment]
@ysc3839 ,Thanks for posting this issue.
I reproduced your issue locally and it has been successfully resolved. You can close this issue and reopen a port update issue, I will submit pr for update, you can view the solution in the pr I submitted

**Comment by ysc3839** [comment]
@JonLiu1993 So do you mean I should open a update request issue and wait for your PR?

**Comment by JonLiu1993** [comment]
> @JonLiu1993 So do you mean I should open a update request issue and wait for your PR?

@ysc3839 ,Yes, you close this issue and reopen a socket-io-client update issue. I will submit pr to upgrade socket-io-client to the latest version. You can check my changes in pr.
