### ISSUE TITLE
[OpenCV] unable to build

### ISSUE THREAD

**Issue by slyshykO** [Microsoft/vcpkg#1860]
CMake Error at ports/opencv/portfile.cmake:110 (file):
  file failed to open for reading (No such file or directory):

    D:/projects/vcpkg-master/packages/opencv_x64-windows/share/opencv/lib/OpenCVConfig.cmake
Call Stack (most recent call first):
  scripts/ports.cmake:72 (include)

Error: Building package opencv:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: opencv:x64-windows
  Vcpkg version: 0.0.89-2017-09-19-3697bd0290100667a090e1699c94eb4c5200d9c1

**Comment by ras0219-msft** [comment]
Hi @slyshykO , there were some regressions in the last PR that we're currently ironing out. We hope to either fix the issues soon or revert the changes!

**Comment by ras0219-msft** [comment]
It should be fixed in the latest master (opencv port version 3.3.0-4).

**Comment by slyshykO** [comment]
Thank you for such fast response & fix
