### ISSUE TITLE
vcpkg integrate install fails with Warning: integration was not applied 

### ISSUE THREAD

**Issue by catscribbles** [microsoft/vcpkg#18619]
**Describe the bug**
I'm trying to integrate some builds into visual studio 2019
vcpkg integrate install fails with a pop up window saying - this file does not have an app associated with it for performing this action - screenshot included.

**Environment**
windows 10 latest update 
- Compiler: Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30038.1 for x64

**To Reproduce**
1. ./vcpkg inteegrate 
![vcpkg-integrate-install-error](https://user-images.githubusercontent.com/86246681/123211015-c63faf00-d4ba-11eb-9bc1-1c09a53ed796.png)
 install
2. See error
Repro code when

**Expected behavior**

**Failure logs** 
-(please attached failure logs)

**Additional context**
I've tried using the powershell, x64 developer command prompt, both as normal and admin user.
I tried 
vcpkg integrate project
and this gave me a command to run in the nuget tools prompt in visual studio but it only included one library, the last library built with vcpkg.
Is there a way to get vcpkg integrate install to work, or as a way round, to get vcpkg integrate project to include all the libraries I need in the build - the command it gave to copy and paste was:
Install-Package vcpkg.C.Users.richard.source.repos.vcpkgmaster -Source "C:\Users\xxxxxxx\source\repos\vcpkg-master\scripts\buildsystems"
I've built 4 libraries with vcpkg, I can manually include and link them but they're not all being integrated by vcpkg integrate project
Any help or advice would be great

**Comment by JackBoosY** [comment]
I think the reason why `cmd` wasn't recognized is your system environment `PATH` was broken.
It should contains `${SYSTEM_DISK}/Windows/system32` which the executable `cmd.exe` exists.

Please check the system environment `PATH` first.

Thanks.

**Comment by catscribbles** [comment]
Hi,
I've checked the PATH, it contains C:\WINDOWS\system32
I've tried to export a single package :
C:\Users\xxxxxxx\source\repos\vcpkg-master>vcpkg.exe export zeromq:x64-windows --nuget
The following packages are already built and will be exported:
    zeromq:x64-windows
Exporting package zeromq:x64-windows...
Packing nuget package...
NuGet package exported at: C:\Users\xxxxxxx\source\repos\vcpkg-master\vcpkg-export-20210629-091202.1.0.0.nupkg

With a project open, go to Tools->NuGet Package Manager->Package Manager Console and paste:
    Install-Package vcpkg-export-20210629-091202 -Source "C:\Users\xxxxxxx\source\repos\vcpkg-master"

C:\Users\xxxxxxx\source\repos\vcpkg-master>

It seems to work doing it this way, it'd be great if the integration worked though

**Comment by JackBoosY** [comment]
Can you please add `--debug` to the integration command, try again and provide the output?

Thanks.

**Comment by catscribbles** [comment]
Hi,
Here's the output:
C:\Users\richard\source\repos\vcpkg-master>vcpkg integrate install --debug
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] BuiltinRegistry initialized with: ""
[DEBUG] Using vcpkg-root: C:\Users\richard\source\repos\vcpkg-master
[DEBUG] Using installed-root: C:\Users\richard\source\repos\vcpkg-master\installed
[DEBUG] BuiltinRegistry initialized with: ""
[DEBUG] Using buildtrees-root: C:\Users\richard\source\repos\vcpkg-master\buildtrees
[DEBUG] Using downloads-root: C:\Users\richard\source\repos\vcpkg-master\downloads
[DEBUG] Using packages-root: C:\Users\richard\source\repos\vcpkg-master\packages
[DEBUG] Using scripts-root: C:\Users\richard\source\repos\vcpkg-master\scripts
[DEBUG] Using ports-root: C:\Users\richard\source\repos\vcpkg-master\ports
[DEBUG] Using versions-root: C:\Users\richard\source\repos\vcpkg-master\versions
[DEBUG] Failed to open: C:\Program Files (x86)\MSBuild/Microsoft.Cpp/v4.0/V140/ImportBefore/Default/vcpkg.system.props
Warning: integration was not applied
[DEBUG] C:\A\1\121\s\src\vcpkg\commands.integrate.cpp(231)
[DEBUG] Exiting after 32366696 us (32356481 us)
it popped up the error message box mentioned before at the line 'Warning: integration was not applied', when I clicked OK I got the last two debug lines.
I looked for the file it can't find, I've got a path up to C:\Program Files (x86)\MSBuild/Microsoft.Cpp/v4.0/, there is a BuildCustomizations folder in the v4.0 folder but no ImportBefore folder. The BuildCustomizations folder has 'CUDA 11.0.props', 'CUDA 11.0.targets' and a few others. I've got the CUDA sdk installed.
Hope that helps

**Comment by JackBoosY** [comment]
Anyone meet this issue again please ping me to reopen it.

Thanks.
