### ISSUE TITLE
[libdatachannel] It can find dependent libraries on its own.

### ISSUE THREAD

**Issue by KangLin** [microsoft/vcpkg#18616]
My program depends on libdatachannel. Then libdatachannel depends on Threads::Threads and LibJuice::juice.
In my program CMakeLists.txt use:

find_package(libdatachannel)

The error message:
Target "RabbitProxy" links to target "Threads::Threads" but the target was not found.  Perhaps a find_package() call is missing for an IMPORTED target, or an ALIAS target is missing?

Of cause. can to add find_package(Threads).
But my expectation is that it can find dependent libraries on its own.
Is there a way to solve?

**Comment by KangLin** [comment]
Solution:
See: https://gitlab.kitware.com/cmake/cmake/-/issues/22336

**Comment by NancyLi1013** [comment]
Thanks for your information @KangLin. I have submitted a PR #18621 to fix this problem.
