### ISSUE TITLE
spirv-tools explicitly deletes DLLs, then aborts when consumed via find_package due to missing DLLs

### ISSUE THREAD

**Issue by chrisdjali-wrld3d** [microsoft/vcpkg#18612]
**Describe the bug**
The `spirv-tools` package explicitly deletes the output of the `SPIRV-Tools-shared` target here: https://github.com/barcharcraz/vcpkg/blob/master/ports/spirv-tools/portfile.cmake#L46-L51

The `SPIRV-Tools-shared` target is still created even with `-DSPIRV_TOOLS_BUILD_STATIC=ON` (which is set explicitly in the portfile) so the upstream CMake still installs it, and creates a check for its presence in the module importing script.

That means if the package is consumed via `find_package`, the check will fail, and a `FATAL_ERROR` message is logged. This aborts the build.

**Environment**
- OS: Windows 10
- Compiler: MSVC 2019 16.9.5

**To Reproduce**
1. `./vcpkg install spirv-tools`
2. Create a new CMake project including `find_package(SPIRV-Tools REQUIRED)`. A `CMakeLists.txt` containing this single line should be enough.
3. Configure the CMake project using the normal Vcpkg toolchain.
4. Observe that a fatal error is printed stating that:
   ```
    The imported target "SPIRV-Tools-shared" references the file

       "C:/Clones/vcpkg/installed/x64-windows/debug/bin/SPIRV-Tools-shared.dll"

    but this file does not exist.  Possible reasons include:

    * The file was deleted, renamed, or moved to another location.

    * An install or uninstall procedure did not complete successfully.

    * The installation package was faulty and contained

       "C:/Clones/vcpkg/installed/x64-windows/share/SPIRV-Tools/SPIRV-ToolsTarget.cmake"

    but not all the files it references.

   Call Stack (most recent call first):
     C:/Clones/vcpkg/installed/x64-windows/share/SPIRV-Tools/SPIRV-ToolsConfig.cmake:1 (include)
     C:/Clones/vcpkg/scripts/buildsystems/vcpkg.cmake:772 (_find_package)
     CMakeLists.txt:119 (find_package)
   ```

**Expected behavior**
Once `find_package(SPIRV-Tools REQUIRED)` has been called, the configure proceeds and the `SPIRV-Tools-static` library is available (also as `SPIRV-Tools` with no suffix).

**Failure logs** 
- The relevant parts of the log are above.
- This is a log from a dummy CMake project with literally just the `find_package` call, so it's got some other warnings about not being a real CMake project: [log.log](https://github.com/microsoft/vcpkg/files/6705076/log.log)

**Additional context**
N/A

**Comment by NancyLi1013** [comment]
Hi @chrisdjali-wrld3d 

Thanks for posting this issue.

@barcharcraz 

Could you please help take a look why removing SPIRV-Tools-shared.dll?
https://github.com/microsoft/vcpkg/blob/876e67c26e42c0c7d2daa41c6871af117ae6bec5/ports/spirv-tools/portfile.cmake#L49

Is there any reason why this port only supports static build?

**Comment by barcharcraz** [comment]
I don't think they actually correctly export symbols on windows. I forget the exact reason, however. I think one of vcpkgs lint checks fires if a static library build installs shared libraries, requiring the deletion. If I recall patching the shared build out of the cmakelists was pretty involved as well due to how their cmake is structured.

I'll take another look when I have time, maybe things have improved upstream.

There's some upstream work in SPIRV-Tools to fix their build options.

**Comment by FrankXie05** [comment]
@chrisdjali-wrld3d This issue has been fixed upstream, please update to the latest vcpkg and try building again. :)

Successful example： 
**CMakeLists.txt:**
````
cmake_minimum_required(VERSION 3.9)
set(CMAKE_CXX_STANDARD 20)

project(Bug_test)

add_executable(main main.cpp)

find_package(SPIRV-Tools CONFIG REQUIRED)
target_link_libraries(main PRIVATE SPIRV-Tools-shared SPIRV-Tools-static)
````
**log:**
````
test@test002:~/bug/build$ cmake .. -DCMAKE_TOOLCHAIN_FILE=/home/test/vcpkg/scripts/buildsystems/vcpkg.cmake
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/test/bug/build
````

**Comment by dg0yt** [comment]
> target_link_libraries(main PRIVATE SPIRV-Tools-shared SPIRV-Tools-static)

Find the error!
