### ISSUE TITLE
[versioning] Versioning turned in the wrong scene

### ISSUE THREAD

**Issue by JackBoosY** [microsoft/vcpkg#18623]
When other dependent ports use versioning, the custom port will automatically enable versioning.
For example, I have a `vcpkg.json`:
```json
{
	"name": "sample",
	"version-string": "0.0.1",
	"dependencies": [{
			"name": "brynet",
			"version>=": "1.10.0"
		},
		{
			"name": "protobuf",
			"version>=": "3.15.8"
		},
		{
			"name": "folly-custom"
		}
	],
	"overrides": [
        { "name": "protobuf", "version": "3.14.0" }
    ],
	"builtin-baseline": "2b1f2ca96a0e4483f50ba605c4c6cc0243633c8d"
}
```
The port `folly-custom` is a copy of `folly` and already put the folder _folly-custom_ into _VCPKG_ROOT/ports_ and  commit the it by `git commit`.

The configure shows:
```
Error: Cannot resolve a minimum constraint for dependency folly-custom from gayrpc:x64-windows.
The dependency was not found in the baseline, indicating that the package did not exist at that time. This may be fixed by providing an explicit override version via the "overrides" field or by updating the baseline.
See `vcpkg help versioning` for more information.
```

Our documentation does not state that if versioning is turned on for a dependency, all dependencies will use versioning.
So it is a bug or incomplete documentation.

**Comment by JackBoosY** [comment]
cc @vicroms @ras0219 @ras0219-msft

**Comment by IronsDu** [comment]
@vicroms @ras0219 @ras0219-msft can you help me? thanks.

**Comment by vicroms** [comment]
The right thing to do is use an [overlay port](https://github.com/microsoft/vcpkg/blob/master/docs/specifications/ports-overlay.md) for `folly-custom` (if you use an overlay you can even keep the `folly` name).

Take your port out of `${VCPKG_ROOT}/ports` and put it somewhere else. Then set the [`VCPKG_OVERLAY_PORTS`](https://github.com/microsoft/vcpkg/blob/master/docs/users/manifests.md#vcpkg_overlay_ports) variable to point to your overlays location.  As specified in the versioning documentation, port overlays circumvent versioning completely.

**Comment by JackBoosY** [comment]
Related doc: https://github.com/microsoft/vcpkg/blob/master/docs/examples/versioning.getting-started.md#versions-and-custom-ports.

**Comment by ras0219-msft** [comment]
Let us know if this doesn't resolve your issue!

**Comment by IronsDu** [comment]
@ras0219-msft :  I don't know whether this resolve my issue. But @JackBoosY Help me resolve my issue.

Thank you.
