### ISSUE TITLE
Tutorial in the documentation for adding packages has a bug

### ISSUE THREAD

**Issue by XsongyangX** [microsoft/vcpkg#18638]
**Describe the bug**
On the help page for adding new [ports](https://github.com/microsoft/vcpkg/blob/master/docs/examples/packaging-zipfiles.md), doing `vcpkg install zlib2` yields an error.
```
Computing installation plan...
Errors occurred while parsing C:\src\vcpkg\ports\zlib2\vcpkg.json
    $.features[0].name (an identifier): must be lowercase alphanumeric+hy
phens and not reserved (see https://github.com/Microsoft/vcpkg/tree/maste
r/docs/specifications/manifests.md for more information)
Error: failed to load port from C:\src\vcpkg\ports\zlib2
Note: Updating vcpkg by rerunning bootstrap-vcpkg may resolve this failur
e.
```

**Environment**
- OS: Windows

**To Reproduce**
Follow the tutorial until section "Tweak the generated portfile". Then perform the command in the tutorial.

**Comment by PhoebeHui** [comment]
@XsongyangX, could you attach  C:\src\vcpkg\ports\zlib2\vcpkg.json file? I suspect the features part hasn't to be removed from vcpkg.json file, that results the errors, please replace vcpkg.json file with following content. I test it locally, and it installed as expect.

vcpkg.json
```
{
  "name": "zlib2",
  "version-string": "1.2.11",
  "description": "A Massively Spiffy Yet Delicately Unobtrusive Compression Library"
}
```

**Comment by XsongyangX** [comment]
This is what I have right after using vcpkg's create. I thought we just add the json fields in the tutorial, not replace all of the file.
```
{
  "name": "zlib2",
  "version-string": "",
  "homepage": "",
  "description": "",
  "dependencies": [],

  "default-features": [],
  "features": [
    {
      "name": "",
      "description": "",
      "dependencies": []
    }
  ]
}
```

**Comment by PhoebeHui** [comment]
@XsongyangX, this is a template for a new port, since it doesn't has any dependency and features, so they need to be removed, Just replace them with the example code. Let me know if you have any others question.

**Comment by XsongyangX** [comment]
Ok. It works now

**Comment by PhoebeHui** [comment]
Great!
