### ISSUE TITLE
[wxpython:x64-windows] build failure when applying patch

### ISSUE THREAD

**Issue by Nicolas8989** [microsoft/vcpkg#18640]
Package: zlib:x64-windows
  Vcpkg version: 2021-05-05-b110959e13f562c2a17d7bd9e352e2dd8d6dc603

error: while searching for:

  option(ASM686 "Enable building i686 assembly implementation")

  option(AMD64 "Enable building amd64 assembly implementation")

  set(INSTALL_BIN_DIR "${CMAKE_INSTALL_PREFIX}/bin" CACHE PATH "Installation
  directory for executables")

  set(INSTALL_LIB_DIR "${CMAKE_INSTALL_PREFIX}/lib" CACHE PATH "Installation
  directory for libraries")

  error: patch failed: CMakeLists.txt:7

  error: CMakeLists.txt: patch does not apply

Call Stack (most recent call first):
  scripts/cmake/vcpkg_extract_source_archive_ex.cmake:144 (z_vcpkg_apply_patches)
  ports/zlib/portfile.cmake:9 (vcpkg_extract_source_archive_ex)
  scripts/ports.cmake:139 (include)

Error: Building package zlib:x64-windows failed with: BUILD_FAILED

**Comment by Nicolas8989** [comment]
I don't know where is this CMAKE.

**Comment by JackBoosY** [comment]
Needs to update the patch.

**Comment by Nicolas8989** [comment]
> 需要更新补丁。

thank you, Where can I download it？

**Comment by JackBoosY** [comment]
@Nicolas8989 Please wait for us to fix this.

**Comment by Nicolas8989** [comment]
> @Nicolas8989请等待我们解决此问题。

Ok,thanks.

**Comment by JonLiu1993** [comment]
@Nicolas8989 ,Thanks for posting this issue.
We don't have a port named wxpython,according to your error log, you need to remake the patch.
Here are the steps to make a patch:

- Direct to the libs path src: such as :C:\fixDate\vcpkg\buildtrees\date\src\date-2.4
- Git init .    (#Retrieve all source files in the current path)
- git add .   (Mirror all retrieved files to a temporary warehouse)
- git commit -m "test amp" (Create a temporary commit on the current branch)
- Modify source   (Modify file)
- git diff | out-file -enc ascii fix-xxx.patch  (Generate the patch file in the current folder (note: this is a powershell command, so it must be run under the powershell window))

**Comment by Nicolas8989** [comment]
> @Nicolas8989，感谢您发布此问题。
> 我们没有名为wxpython的端口，根据你的错误日志，你需要重新打补丁。
> 以下是制作补丁的步骤：
> 
> * 直接到libs路径src：如:C:\fixDate\vcpkg\buildtrees\date\src\date-2.4
> * git初始化。(#检索当前路径下的所有源文件)
> * git 添加。（将所有检索到的文件镜像到临时仓库）
> * git commit -m "test amp"（在当前分支上创建一个临时提交）
> * 修改源（修改文件）
> * 混帐差异| out-file -enc ascii fix-xxx.patch（在当前文件夹生成补丁文件（注意：这是powershell命令，所以必须在powershell窗口下运行））

ok,i got it, thanks

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
