### ISSUE TITLE
Package is not installed, just output the text "Computing installation plan...". And, nothing happened.

### ISSUE THREAD

**Issue by hansputera** [microsoft/vcpkg#18647]
**Describe the bug**
The bug that occurs is when I want to install an openssl package and zlib using VCPKG. At one point I ran `./vcpkg.exe install openssl:x86-windows zlib:x86-windows`. And shows the text "Computing installation plan...", and does not issue any more text in the console. I thought that the installation was complete, but when I ran the `./vcpkg list`. No package installed

**Environment**
- OS: Windows
- Compiler: MSVC 

**To Reproduce**
1. ./vcpkg install openssl:x86-windows zlib:x86-windows
2. Nothing to see, only 1 text is "Computing installation plan..."

**Expected behavior**
I want the package installed.

**Failure logs** 
https://pastebin.com/rHsCumZt

**Comment by Hoikas** [comment]
Potentially a dupe of #18636

**Comment by hansputera** [comment]
Fixed, thanks
