### ISSUE TITLE
How do I reintegrate vcpkg with an existing VS2019 solution?

### ISSUE THREAD

**Issue by lalilulelost** [microsoft/vcpkg#18657]
I am using Visual Studio 2019 on Windows 10 21H1.

I had to delete my local copy of a repository for a C++ project I'm working on that uses `glfw3`, `imgui`, `glad`, `glm`, among some other libraries, which were downloaded, configured and linked using vcpkg. I still have vcpkg integrated and all libraries are currently installed user-wide. Since I deleted the local copy, I cloned the repo again and opened the solution with Visual Studio.

However, all `#include`s for headers from these libraries are giving me errors like `cannot open source file "glm/glm.hpp"`, which suggests vcpkg isn't working on this project. If I run `vcpkg install glm`, for example, I get a message like `Package glm:x86-windows is already installed`. 

How do I trigger vcpkg to find and link the libraries into the project, given that they're already installed and should be ready to go, as they were before I deleted the previous local repository? The documentation (from the vcpkg repository's `README.md`) seems to suggest that the way to do it would be to run `vcpkg integrate install` in the repository's root folder. But I've done it with and without administrator privileges, and have tried restarting VS2019 and rebooting my PC after running that command, unfortunately without satisfactory results.

I hope I was able to clearly describe the issue, but please ask for further details if needed.

**Comment by lalilulelost** [comment]
Particularly, I guess, in [this documentation page](https://vcpkg.readthedocs.io/en/latest/examples/installing-and-using-packages/), in `Step 2: Use`, it says (after instructing the user to run `vcpkg integrate install`):

>You can now simply use File -> New Project in Visual Studio and the library will be automatically available.

But how do I activate vcpkg integration for a project that _already exists_? I suppose my issue boils down to this.

**Comment by lalilulelost** [comment]
Oh, yes, I am using an MSBuild project, not a CMake one.

**Comment by lalilulelost** [comment]
Aha! So I figured out what to do from [this](https://github.com/Microsoft/vcpkg/issues/4402#issuecomment-426987631) answer to another issue.

![image](https://user-images.githubusercontent.com/1574303/123503721-1178cf80-d62b-11eb-8db6-28675993d17d.png)

I simply had to switch the project's platform in the configuration manager to Win32. I welcome anyone to detail _why_ this works, but it did work for me, lol.

I'll leave the issue open for others to comment, but let me know if I should close it.

**Comment by PhoebeHui** [comment]
@lalilulelost, the answer from https://github.com/Microsoft/vcpkg/issues/4402#issuecomment-426987631 is a right solution for this issue, you need to keep same bit for installed port and your project, eg, x86-windows -> x86|win32 configuration, x64-windows ->x64 configuration. Since the issue has been resolved, closing it now.
