### ISSUE TITLE
[qtbase] build failure

### ISSUE THREAD

**Issue by BenKey** [microsoft/vcpkg#18660]
# Host Environment

* **OS:** Windows 10 Pro Version 21H1 build 19043.1081 with Windows Feature Experience Pack 120.2212.3530.0
* **Compiler:** Microsoft Visual Studio Community 2019 Version 16.10.2

# To Reproduce

```
./vcpkg install "qt[core,default-features]" --triplet x64-windows
```

# Failure logs

```
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:146 (message):
  Command failed: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j9
  Working Directory: D:/vcpkg/buildtrees/qtbase/x64-windows-dbg
  See logs for more information:
  D:\vcpkg\buildtrees\qtbase\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:104 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:44 (vcpkg_build_cmake)
  ports/qtbase/cmake/qt_install_submodule.cmake:112 (vcpkg_install_cmake)
  ports/qtbase/portfile.cmake:211 (qt_install_submodule)
  scripts/ports.cmake:139 (include)
```

[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/6719968/install-x64-windows-dbg-out.log)

**Comment by autoantwort** [comment]
The error `FAILED: src/testlib/Test_autogen/timestamp` looks random, can you simply try it again? :)

**Comment by BenKey** [comment]
I have tried four times already.
*-- *

*Ciao,*
*Benilda Key*
*Email: ***@***.*** ***@***.***>*
*Website: https://sullivanandkey.com/ <https://sullivanandkey.com/>*

*There is a fork in the path ahead of you. There are also two signs,
telling you where each fork goes. The sign for the right fork reads
“Regnad.” The sign for the left fork reads “Shortcut to Regnad.” What
should you do?*
*-- *

**Comment by JackBoosY** [comment]
cc @Neumann-A

**Comment by Neumann-A** [comment]
Which version of cmake is VS shipping right now? Maybe it is the CMake bug which was fixed?

**Comment by BenKey** [comment]
The output of 'cmake --version' is as follows.

````````
cmake version 3.20.21032501-MSVC_2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
````````

**Comment by BenKey** [comment]
I just tried to build this again last night. It worked. Who knows what went wrong before.
