### ISSUE TITLE
GLEW build failure on Ubuntu

### ISSUE THREAD

**Issue by Journeyman-dev** [microsoft/vcpkg#18662]
**Host Environment**
- OS: Linux (Ubuntu 20.04 via Github Actions)
- Compiler: GCC and Clang

**To Reproduce**
(in Github Actions)
' git submodule add https://github.com/microsoft/vcpkg vcpkg/'
'pushd vcpkg'
'./bootstrap-vcpkg.sh -disableMetrics'
'./vcpkg install catch2 glew glfw3 --triplet x64-linux'
(permalink to yaml file https://github.com/Journeyman-dev/TUIC/blob/b97438671742a044c69f11a2814b5ef60fd37982/.github/workflows/Tests.yml)
(actions report https://github.com/Journeyman-dev/TUIC/actions/runs/974265097)

**Failure logs** 
(logs extracted from Github Actions using actions/archive)
```
CMake Error at /home/runner/work/TUIC/TUIC/vcpkg/downloads/tools/cmake-3.20.2-linux/cmake-3.20.2-linux-x86_64/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find OpenGL (missing: OPENGL_opengl_LIBRARY OPENGL_glx_LIBRARY
  OPENGL_INCLUDE_DIR)
Call Stack (most recent call first):
  /home/runner/work/TUIC/TUIC/vcpkg/downloads/tools/cmake-3.20.2-linux/cmake-3.20.2-linux-x86_64/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /home/runner/work/TUIC/TUIC/vcpkg/downloads/tools/cmake-3.20.2-linux/cmake-3.20.2-linux-x86_64/share/cmake-3.20/Modules/FindOpenGL.cmake:443 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  /home/runner/work/TUIC/TUIC/vcpkg/scripts/buildsystems/vcpkg.cmake:771 (_find_package)
  CMakeLists.txt:40 (find_package)
```

**Additional context**
it is apparent that vcpkg recognizes that opengl[core] is needed for glew to work and downloads it as a dependency:
```
Run ./vcpkg install catch2 glew glfw3 --triplet x64-linux
Computing installation plan...
The following packages will be built and installed:
    catch2[core]:x64-linux -> 2.13.6
    glew[core]:x64-linux -> 2.1.0#10
    glfw3[core]:x64-linux -> 3.3.4
  * opengl[core]:x64-linux -> 0.0#8
  ```
 It should be noted that  opengl[core] is not needed for glfw3 or catch2, so it must be installing it for glew unless there is a mistake in one of those two packages. 
 
 Despite the fact that vcpkg successfully installs opengl[core], it fails to link it with glew correctly. Also note that instead of using the built in vcpkg install that ships with GitHub Actions server, I cloned it as a submodule to ensure that I am using the latest version of vcpkg. As you can see from the Actions report, this error does not occur on Windows and Mac operating systems.

**Comment by PhoebeHui** [comment]
@Journeyman-dev, thanks for reporting this issue!

**Comment by PhoebeHui** [comment]
@Journeyman-dev, glew requires libxmu-dev libxi-dev libgl-dev on linux, could you install them via apt-get install libxmu-dev libxi-dev libgl-dev, and see if this issue still repro?

**Comment by PhoebeHui** [comment]
@Journeyman-dev, do you have a chance to test it?
