### ISSUE TITLE
How do I install other library into vcpkg

### ISSUE THREAD

**Issue by XuRongYan** [microsoft/vcpkg#18669]
For example, I want to install alglib, a header-only c++ library, into vcpkg. But I don't know how to do it

**Comment by NancyLi1013** [comment]
Hi @XuRongYan

Thanks for posting this issue.

Do you mean how to install libraries that are not in vcpkg now or do you want to know how to add a new port to vcpkg?

**Comment by XuRongYan** [comment]
Hi, 
I mean how to install libraries that are not in vcpkg now.

**Comment by NancyLi1013** [comment]
If you only want to use the port on your local, you can use `vcpkg create` to generate a portfile.cmake.

Please refer to this doc https://github.com/microsoft/vcpkg/blob/master/docs/examples/packaging-zipfiles.md.

**Comment by NancyLi1013** [comment]
Closing this issue for now since there is no active thread in a long time. Please feel free to reopen this issue if it is still a problem for you.
