### ISSUE TITLE
Can we use classic mode  and  manifest mode together？

### ISSUE THREAD

**Issue by daiybh** [microsoft/vcpkg#18666]
1. we installed [fmt] in classic mode , so  it will be in $VCPKG_ROOT/installed
2. if we use manifest in our project , this project depends [fmt].
3. then vcpkg will download fmt ,build and install it into  $PROJECT_ROOT/installed.
4.  my question is can we  have a option, if in $VCPKG_ROOT/installed have we need library,directly use it ,or copy them to $PROJECT_ROOT/installed.   Don't download , build them ?

**Comment by autoantwort** [comment]
Normally the binary cache is used to copy the lib. So no rebuild

**Comment by daiybh** [comment]
> Normally the binary cache is used to copy the lib. So no rebuild

it need use  export?

**Comment by JackBoosY** [comment]
No, currently we have to choose one of them. And the build directory between them is different.

**Comment by daiybh** [comment]
Thanks. should we  support it later?

**Comment by PhoebeHui** [comment]
@daiybh, if you enable binary cache, you will found it doesn't rebuild in manifest mode if you installed in classic mode with same revision. So please enable the binarycache feature and try again, the feature enabled by default.

**Comment by PhoebeHui** [comment]
BTW, It's a intent behavior, see https://github.com/microsoft/vcpkg/blob/master/docs/users/manifests.md#manifest-mode.

**Comment by daiybh** [comment]
@PhoebeHui  Thanks. It is works.
