### ISSUE TITLE
[New Port Request] libtcc

### ISSUE THREAD

**Issue by Tanishq-Banyal** [microsoft/vcpkg#18665]
***Library name :*** libtcc

***Library description :*** The libtcc library enables you to use TCC as a backend for dynamic code generation. The idea consists in giving a C string containing the program you want to compile directly to libtcc. Then you can access to any global symbol (function or variable) defined.

***Source URL :*** http://download.savannah.gnu.org/releases/tinycc/

**Source GIT Repository URL :-**
https://repo.or.cz/tinycc.git

***Project homepage :*** https://bellard.org/tcc/

***Anything else that is useful to know when adding :*** latest version is 0.9.27 & it is also the last version.

**Comment by mathisloge** [comment]
is it still developed? 

> [Note: I am no longer working on TCC. Check the mailing list to get up to date information.]
~cite https://bellard.org/tcc/

I think that this would be appropiate for a custom registry since we had the discussion in the past:
https://github.com/microsoft/vcpkg/pull/17540#issuecomment-829462086 
https://github.com/microsoft/vcpkg/pull/17540#issuecomment-829608222

**Comment by Tanishq-Banyal** [comment]
But libTCC is not experimental, it's been there for long time and last update was in 2020, and it works fine, it mostly supports c99 and is stable enough to be a vcpkg port.

It's open source so chances are that someone may decide to maintain it in future.

**Comment by mathisloge** [comment]
@Tanishq-Banyal yeah thats true. 

Just discovered the git repository https://repo.or.cz/tinycc.git which indicates an active maintenance from the community.

**Comment by Tanishq-Banyal** [comment]
> Just discovered the git repository https://repo.or.cz/tinycc.git which indicates an active maintenance from the community.

Yeah I didn't knew about it either since he didn't mentioned the repository on his website.

Seems like only "the owner bellard" has stopped maintaining, Community commits are still coming everyday.

**Comment by Tanishq-Banyal** [comment]
Any progress ?

**Comment by mathisloge** [comment]
So I don't have time for that right now. Either someone else will do it, or you try to create the port yourself. 
Some good starting points: 

https://github.com/microsoft/vcpkg/blob/master/docs/examples/packaging-github-repos.md

Since tinycc's git repo isn't on github, you need this one instead of `vcpkg_from_github` [vcpkg_from_git](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_from_git.md) with the tag (https://repo.or.cz/tinycc.git/refs  => tags/release_0_9_27)

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
