### ISSUE TITLE
CLAPACK_FOUND used before initialized?

### ISSUE THREAD

**Issue by bucurb** [microsoft/vcpkg#18679]
I don't think there's anything setting CLAPACK_FOUND in the file below, so I don't believe it's setting-up the proper targets. I'm actually getting a build error when trying to use the lapack target after a successful call to find_package(LAPACK REQUIRED) on a Windows build.

Additionally, the targets are only correctly set-up the first time you call find_package(LAPACK). Subsequent calls will have all the oF2C_LIBRARY_RELEASE etc. variables not set and hence the targets will typically be -NOTFOUND.

https://github.com/microsoft/vcpkg/blob/bb002cdd1a2c9eacbe60d8383fb5d437752b1e4e/ports/clapack/FindLAPACK.cmake#L171

**Comment by PhoebeHui** [comment]
cc @cenit

**Comment by PhoebeHui** [comment]
@bucurb, could you provide us the repro code?

```
The package clapack:x64-windows provides CMake targets:

    find_package(clapack CONFIG REQUIRED)
    target_link_libraries(main PRIVATE f2c lapack)

    find_package(lapack CONFIG REQUIRED)
    target_link_libraries(main PRIVATE lapack clapack::clapack)
```

**Comment by bucurb** [comment]
Adding find_package(clapack CONFIG REQUIRED) fixes the issue for sure, but that is not the 'proper' fix, as lapack is supposed to be the 'pure virtual' package that dispatches to either clapack or lapack-reference depending on the platform. As for the repro, you only need 2 dummy sibling cmake files, both calling only find_package(LAPACK REQUIRED). Initially none will succeed, but if you do indeed set CLAPACK_FOUND as the script claims it does, then the first call will succeed, but the second will not, as the variables used to set-up the lapack targets are not set and the target will end-up invalid.

**Comment by PhoebeHui** [comment]
@bucurb, It looks a port bug, I have submitted a PR https://github.com/microsoft/vcpkg/pull/18707 to fix it, could you help test it?

**Comment by bucurb** [comment]
@PhoebeHui I just created a PR with what worked for me. I saw your PR just now, sorry about that.
