### ISSUE TITLE
X_VCPKG_APPLOCAL_DEPS_INSTALL bug for install-command with multiple targets.

### ISSUE THREAD

**Issue by powel-jeh** [microsoft/vcpkg#18670]
**Describe the bug**
`x_vcpkg_install_local_dependencies` breaks down for install-command with multiple targets, as PARSED_TARGETS is passed as string https://github.com/microsoft/vcpkg/blob/master/scripts/buildsystems/vcpkg.cmake#L681, not list.

**Additional context**
Fixed here: https://github.com/strega-nil/vcpkg/tree/vcpkg-cmake-install_local_deps_bug by @strega-nil.

**Comment by NancyLi1013** [comment]
Fixed by PR #18607

**Comment by powel-jeh** [comment]
Thanks!

**Comment by NancyLi1013** [comment]
Please keep this issue open until the PR is merged. 

Thanks.

**Comment by JackBoosY** [comment]
Related: https://github.com/microsoft/vcpkg/issues/19123

**Comment by JackBoosY** [comment]
Hi @powel-jeh, since #19157 was merged. can you please try again?

**Comment by powel-jeh** [comment]
ya, works.
