### ISSUE TITLE
[arrayfire] build failure on MacOS

### ISSUE THREAD

**Issue by alexunsworthfb** [microsoft/vcpkg#18685]
**Host Environment**
- OS: [Mac OS  11.4]
- Compiler: revision

Trying to install flashlight-cpu but coming across this error, MLK is installed.

All in same terminal :

. /opt/intel/oneapi/setvars.sh

./vcpkg/bootstrap-vcpkg.sh

./vcpkg/vcpkg install flashlight-cpu

**Error in terminal **
```
-- Building x64-osx-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:146 (message):
    Command failed: /Users/alexunsworth/vcpkg/downloads/tools/cmake-3.20.2-osx/cmake-3.20.2-macos-universal/CMake.app/Contents/bin/cmake --build . --config Debug --target install -- -v -j13
    Working Directory: /Users/alexunsworth/vcpkg/buildtrees/arrayfire/x64-osx-dbg
    See logs for more information:
      /Users/alexunsworth/vcpkg/buildtrees/arrayfire/install-x64-osx-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:104 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:44 (vcpkg_build_cmake)
  ports/arrayfire/portfile.cmake:76 (vcpkg_install_cmake)
  scripts/ports.cmake:139 (include)


Error: Building package arrayfire:x64-osx failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: arrayfire:x64-osx
  Vcpkg version: 2021-05-05-unknownhash
```
**Failure logs** 
Found in '/Users/alex/vcpkg/buildtrees/arrayfire/config-x64-osx-dbg-err.log'
```
CMake Warning (dev) at /Users/alexunsworth/vcpkg/downloads/tools/cmake-3.20.2-osx/cmake-3.20.2-macos-universal/CMake.app/Contents/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (OpenMP_CXX)
  does not match the name of the calling package (OpenMP).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  CMakeModules/FindOpenMP.cmake:402 (find_package_handle_standard_args)
  /Users/alexunsworth/vcpkg/scripts/buildsystems/vcpkg.cmake:771 (_find_package)
  CMakeModules/FindMKL.cmake:67 (find_package)
  /Users/alexunsworth/vcpkg/scripts/buildsystems/vcpkg.cmake:771 (_find_package)
  CMakeLists.txt:47 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning:
  Manually-specified variables were not used by the project:

    VCPKG_CRT_LINKAGE
    VCPKG_PLATFORM_TOOLSET
    VCPKG_SET_CHARSET_FLAG
    _VCPKG_ROOT_DIR

```

**Comment by JackBoosY** [comment]
Please provide failure log _/Users/alexunsworth/vcpkg/buildtrees/arrayfire/install-x64-osx-dbg-err.log_.

Thanks.

**Comment by alexunsworthfb** [comment]
[config-x64-osx-dbg-err.log](https://github.com/microsoft/vcpkg/files/6731634/config-x64-osx-dbg-err.log)


Debug information is not split on OSX
CUDA_TOOLKIT_ROOT_DIR not found or specified
CMake Warning (dev) at /Users/alexunsworth/vcpkg/downloads/tools/cmake-3.20.2-osx/cmake-3.20.2-macos-universal/CMake.app/Contents/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (LAPACK)
  does not match the name of the calling package (LAPACKE).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  CMakeModules/FindLAPACKE.cmake:153 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  /Users/alexunsworth/vcpkg/scripts/buildsystems/vcpkg.cmake:771 (_find_package)
  CMakeLists.txt:45 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /Users/alexunsworth/vcpkg/downloads/tools/cmake-3.20.2-osx/cmake-3.20.2-macos-universal/CMake.app/Contents/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (OpenMP_C)
  does not match the name of the calling package (OpenMP).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  CMakeModules/FindOpenMP.cmake:402 (find_package_handle_standard_args)
  /Users/alexunsworth/vcpkg/scripts/buildsystems/vcpkg.cmake:771 (_find_package)
  CMakeModules/FindMKL.cmake:67 (find_package)
  /Users/alexunsworth/vcpkg/scripts/buildsystems/vcpkg.cmake:771 (_find_package)
  CMakeLists.txt:47 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /Users/alexunsworth/vcpkg/downloads/tools/cmake-3.20.2-osx/cmake-3.20.2-macos-universal/CMake.app/Contents/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (OpenMP_CXX)
  does not match the name of the calling package (OpenMP).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  CMakeModules/FindOpenMP.cmake:402 (find_package_handle_standard_args)
  /Users/alexunsworth/vcpkg/scripts/buildsystems/vcpkg.cmake:771 (_find_package)
  CMakeModules/FindMKL.cmake:67 (find_package)
  /Users/alexunsworth/vcpkg/scripts/buildsystems/vcpkg.cmake:771 (_find_package)
  CMakeLists.txt:47 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning:
  Manually-specified variables were not used by the project:

    VCPKG_CRT_LINKAGE
    VCPKG_PLATFORM_TOOLSET
    VCPKG_SET_CHARSET_FLAG
    _VCPKG_ROOT_DIR

**Comment by JackBoosY** [comment]
No, not the config log, please provide the install log.

**Comment by alexunsworthfb** [comment]
Apologies, 

ninja: error: 'MKL_ThreadingLibrary_LINK_LIBRARY-NOTFOUND', needed by 'src/backend/cpu/libafcpu.3.7.3.dylib', missing and no known rule to make it


[install-x64-osx-dbg-err.log](https://github.com/microsoft/vcpkg/files/6732008/install-x64-osx-dbg-err.log)

**Comment by JackBoosY** [comment]
Duplicated to #18222, please track that issue.
