### ISSUE TITLE
How to build `vcpkg.exe` instead of downloading?

### ISSUE THREAD

**Issue by playgithub** [microsoft/vcpkg#18686]
Previously `bootstrap-vcpkg.bat` builds`vcpkg.exe` from source.
Now it downloads `vcpkg.exe` in binary.

I prefer the open source way, is it supported?

**Comment by JackBoosY** [comment]
See the [tool repo](https://github.com/microsoft/vcpkg-tool).
We recommend against building it manually because the executable file you build does not contain certification.

**Comment by playgithub** [comment]
> We recommend against building it manually because the executable file you build does not contain certification.

It can not be built in an open source way with a certification?
What is the certification for?
What is no certification?

**Comment by JackBoosY** [comment]
![image](https://user-images.githubusercontent.com/47264268/123743754-45c8e600-d8e0-11eb-9ae6-9d307b20016c.png)
The generated binary must be signed before it will not be blocked by anti-virus.

**Comment by playgithub** [comment]
> The generated binary must be signed before it will not be blocked by anti-virus.

I think a common pkg manager should not be blocked as a virus by nature.
So what causes it to need a certificate?

**Comment by JackBoosY** [comment]
See the history in https://github.com/microsoft/vcpkg/issues/3345.

**Comment by dg0yt** [comment]
> The generated binary must be signed before it will not be blocked by anti-virus.

None of the installed tools generated by `vcpkg install` are signed, and still they can be used by consuming ports.

**Comment by JackBoosY** [comment]
> > The generated binary must be signed before it will not be blocked by anti-virus.
> 
> None of the installed tools generated by `vcpkg install` are signed, and still they can be used by consuming ports.

And some executables like `b2.exe` have this issues too.

**Comment by dg0yt** [comment]
With regard to #3345 "vcpkgmetricsuploaded-0.0.110.exe is detected as a virus": 
Maybe disabling all network features in individual builds would make anti-virus tools more relaxed. Integrating telemetry upload and the `x-download` command into the tool was the opposite move.

**Comment by playgithub** [comment]
Now `vcpkg.exe` has the ability of metrics, the ability can be disabled by a file named `vcpkg.disable-metrics`, but anyway it has the ability, so a backdoor is possible.
Like `live share` of Visual Studio, if it has the ability of live share, some way underground might be there.
