### ISSUE TITLE
protoc target not available in cross-compile builds

### ISSUE THREAD

**Issue by bucurb** [microsoft/vcpkg#18689]
It looks like the protobuf port file is trying to add a protoc target even for the case where the host is different from the target triplet. That's all great, but I don't understand what is supposed to call the protobuf-targets-vcpkg-protoc.cmake file. The toolchain does not, and neither do any of the config or targets .cmake files.

https://github.com/microsoft/vcpkg/blob/6cdc26c884ac1c7c4cf2d480b364b773765622a3/ports/protobuf/portfile.cmake#L123

**Comment by PhoebeHui** [comment]
@bucurb, thanks for reporting this issue! it looks a port bug in protobuf. 

The changes involved by PR https://github.com/microsoft/vcpkg/pull/16479, I will take a look.

**Comment by bucurb** [comment]
Actually protobuf-targets-vcpkg-protoc.cmake is called. But the executable is not found as it looks like the path in find_program(Protobuf_PROTOC_EXECUTABLE NAMES protoc PATHS "${CMAKE_CURRENT_LIST_DIR}/../../../@HOST_TRIPLET@/tools/protobuf" NO_DEFAULT_PATH) is wrong. The executable seems to be copied in the PLATFORM_TRIPLET instead of the HOST_TRIPLET.
