### ISSUE TITLE
[CGAL] build failure

### ISSUE THREAD

**Issue by marianaiv** [microsoft/vcpkg#18688]
**Host Environment**
- OS: Microsoft Windows 10 Home
Version	10.0.19041 Build 19041
- Compiler: not sure. I have vs2019

**To Reproduce**
<code>.\vcpkg install yasm-tool:x86-windows</code>

**Failure logs** 
```
Computing installation plan...
The following packages will be built and installed:
    yasm-tool[core]:x86-windows -> 1.3.0
Detecting compiler hash for triplet x86-windows...
Could not locate cached archive: C:\Users\maria\AppData\Local\vcpkg\archives\51\5109c76138dc5f0bfd6d96917b1da69e673365bb1f7414cb7a5b06d964328740.zip
Starting package 1/1: yasm-tool:x86-windows
Building package yasm-tool[core]:x86-windows...
-- Using C:/Users/maria/vcpkg/downloads/yasm-yasm-009450c7ad4d425fa5a10ac4bd6efbd25248d823.tar.gz
-- Cleaning sources at C:/Users/maria/vcpkg/buildtrees/yasm-tool/src/d25248d823-818ed1bbf4.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/maria/vcpkg/downloads/yasm-yasm-009450c7ad4d425fa5a10ac4bd6efbd25248d823.tar.gz
-- Using source at C:/Users/maria/vcpkg/buildtrees/yasm-tool/src/d25248d823-818ed1bbf4.clean
-- Installing: C:/Users/maria/vcpkg/packages/yasm-tool_x86-windows/share/yasm-tool/copyright
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
    Command failed: ninja -v
    Working Directory: C:/Users/maria/vcpkg/buildtrees/yasm-tool/x86-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\Users\maria\vcpkg\buildtrees\yasm-tool\config-x86-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:323 (vcpkg_execute_required_process)
  ports/yasm-tool/portfile.cmake:26 (vcpkg_configure_cmake)
  scripts/ports.cmake:139 (include)


Error: Building package yasm-tool:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: yasm-tool:x86-windows
  Vcpkg version: 2021-05-05-b110959e13f562c2a17d7bd9e352e2dd8d6dc603

Additionally, attach any relevant sections from the log files above.
```

**Additional context**

I'm trying to install Vcpkg to install CGAL following the instructions [here](https://doc.cgal.org/latest/Manual/windows.html#title0). 

I'm on 1.2 trying to run <code>.\vcpkg install yasm-tool:x86-windows</code>. 
I tried skipping this step and running <code>.\vcpkg.exe install cgal</code> but it also gave me an error 
```
Error: Building package boost-build:x64-windows failed with: BUILD_FAILED
```

I also tried <code>.\vcpkg update </code> but <code> No packages need updating. </code>

**Comment by NancyLi1013** [comment]
Hi @marianaiv 

Thanks for posting this issue.

Could you please help provide the error log from `C:\Users\maria\vcpkg\buildtrees\yasm-tool\config-x86-windows-out.log`?

I also noticed that you didn't use the latest vcpkg to build. So Could you please try to update vcpkg via `git pull` to rebuild?

**Comment by marianaiv** [comment]
> Hi @marianaiv
> 
> Thanks for posting this issue.
> 
> Could you please help provide the error log from `C:\Users\maria\vcpkg\buildtrees\yasm-tool\config-x86-windows-out.log`?
> 
> I also noticed that you didn't use the latest vcpkg to build. So Could you please try to update vcpkg via `git pull` to rebuild?

I tried <code>git pull</code> and <code>.\vcpkg install yasm-tool:x86-windows</code> and still:


    Error: Building package yasm-tool:x86-windows failed with: BUILD_FAILED
    Please ensure you're using the latest portfiles with `.\vcpkg update`, then
    submit an issue at https://github.com/Microsoft/vcpkg/issues including:
       Package: yasm-tool:x86-windows
       Vcpkg version: 2021-05-05-b110959e13f562c2a17d7bd9e352e2dd8d6dc603

This is **the log** (I think there are two there but I leave it like this because I don't actually know):

[1/2] cmd /c "cd .. && "C:/Users/maria/vcpkg/downloads/tools/cmake-3.20.2-windows/cmake-3.20.2-windows-i386/bin/cmake.exe" "C:/Users/maria/vcpkg/buildtrees/yasm-tool/src/d25248d823-818ed1bbf4.clean" "-DENABLE_NLS=OFF" "-DYASM_BUILD_TESTS=OFF" "-DCMAKE_MAKE_PROGRAM=C:/Users/maria/vcpkg/downloads/tools/ninja/1.10.2-windows/ninja.exe" "-DBUILD_SHARED_LIBS=OFF" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/Users/maria/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x86-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v142" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/Users/maria/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_LINKER_FLAGS_RELEASE=" "-DVCPKG_LINKER_FLAGS_DEBUG=" "-DVCPKG_TARGET_ARCHITECTURE=x86" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=C:/Users/maria/vcpkg" "-D_VCPKG_INSTALLED_DIR=C:/Users/maria/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=C:/Users/maria/vcpkg/packages/yasm-tool_x86-windows""
FAILED: ../CMakeCache.txt 
cmd /c "cd .. && "C:/Users/maria/vcpkg/downloads/tools/cmake-3.20.2-windows/cmake-3.20.2-windows-i386/bin/cmake.exe" "C:/Users/maria/vcpkg/buildtrees/yasm-tool/src/d25248d823-818ed1bbf4.clean" "-DENABLE_NLS=OFF" "-DYASM_BUILD_TESTS=OFF" "-DCMAKE_MAKE_PROGRAM=C:/Users/maria/vcpkg/downloads/tools/ninja/1.10.2-windows/ninja.exe" "-DBUILD_SHARED_LIBS=OFF" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/Users/maria/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x86-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v142" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/Users/maria/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_LINKER_FLAGS_RELEASE=" "-DVCPKG_LINKER_FLAGS_DEBUG=" "-DVCPKG_TARGET_ARCHITECTURE=x86" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=C:/Users/maria/vcpkg" "-D_VCPKG_INSTALLED_DIR=C:/Users/maria/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=C:/Users/maria/vcpkg/packages/yasm-tool_x86-windows""
-- The C compiler identification is MSVC 19.29.30037.0
-- The CXX compiler identification is MSVC 19.29.30037.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30037/bin/Hostx64/x86/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30037/bin/Hostx64/x86/cl.exe - broken
CMake Error at C:/Users/maria/vcpkg/downloads/tools/cmake-3.20.2-windows/cmake-3.20.2-windows-i386/share/cmake-3.20/Modules/CMakeTestCCompiler.cmake:66 (message):
  The C compiler

    "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30037/bin/Hostx64/x86/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/Users/maria/vcpkg/buildtrees/yasm-tool/x86-windows-rel/CMakeFiles/CMakeTmp
    
    Run Build Command(s):C:/Users/maria/vcpkg/downloads/tools/ninja/1.10.2-windows/ninja.exe cmTC_00fb6 && [1/2] Building C object CMakeFiles\cmTC_00fb6.dir\testCCompiler.c.obj
    [2/2] Linking C executable cmTC_00fb6.exe
    FAILED: cmTC_00fb6.exe 
    cmd.exe /C "cd . && C:\Users\maria\vcpkg\downloads\tools\cmake-3.20.2-windows\cmake-3.20.2-windows-i386\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_00fb6.dir --rc=rc --mt=CMAKE_MT-NOTFOUND --manifests  -- C:\PROGRA~2\MIB055~1\2019\COMMUN~1\VC\Tools\MSVC\1429~1.300\bin\Hostx64\x86\link.exe /nologo CMakeFiles\cmTC_00fb6.dir\testCCompiler.c.obj  /out:cmTC_00fb6.exe /implib:cmTC_00fb6.lib /pdb:cmTC_00fb6.pdb /version:0.0 /machine:X86  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    RC Pass 1: command "rc /fo CMakeFiles\cmTC_00fb6.dir/manifest.res CMakeFiles\cmTC_00fb6.dir/manifest.rc" failed (exit code 0) with the following output:
    The system cannot find the file specified
    ninja: build stopped: subcommand failed.
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:1 (PROJECT)


-- Configuring incomplete, errors occurred!
See also "C:/Users/maria/vcpkg/buildtrees/yasm-tool/x86-windows-rel/CMakeFiles/CMakeOutput.log".
See also "C:/Users/maria/vcpkg/buildtrees/yasm-tool/x86-windows-rel/CMakeFiles/CMakeError.log".
[2/2] cmd /c "cd ../../x86-windows-dbg && "C:/Users/maria/vcpkg/downloads/tools/cmake-3.20.2-windows/cmake-3.20.2-windows-i386/bin/cmake.exe" "C:/Users/maria/vcpkg/buildtrees/yasm-tool/src/d25248d823-818ed1bbf4.clean" "-DENABLE_NLS=OFF" "-DYASM_BUILD_TESTS=OFF" "-DCMAKE_MAKE_PROGRAM=C:/Users/maria/vcpkg/downloads/tools/ninja/1.10.2-windows/ninja.exe" "-DBUILD_SHARED_LIBS=OFF" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/Users/maria/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x86-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v142" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/Users/maria/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_LINKER_FLAGS_RELEASE=" "-DVCPKG_LINKER_FLAGS_DEBUG=" "-DVCPKG_TARGET_ARCHITECTURE=x86" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=C:/Users/maria/vcpkg" "-D_VCPKG_INSTALLED_DIR=C:/Users/maria/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_INSTALL_PREFIX=C:/Users/maria/vcpkg/packages/yasm-tool_x86-windows/debug""
FAILED: ../../x86-windows-dbg/CMakeCache.txt 
cmd /c "cd ../../x86-windows-dbg && "C:/Users/maria/vcpkg/downloads/tools/cmake-3.20.2-windows/cmake-3.20.2-windows-i386/bin/cmake.exe" "C:/Users/maria/vcpkg/buildtrees/yasm-tool/src/d25248d823-818ed1bbf4.clean" "-DENABLE_NLS=OFF" "-DYASM_BUILD_TESTS=OFF" "-DCMAKE_MAKE_PROGRAM=C:/Users/maria/vcpkg/downloads/tools/ninja/1.10.2-windows/ninja.exe" "-DBUILD_SHARED_LIBS=OFF" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/Users/maria/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x86-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v142" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/Users/maria/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_LINKER_FLAGS_RELEASE=" "-DVCPKG_LINKER_FLAGS_DEBUG=" "-DVCPKG_TARGET_ARCHITECTURE=x86" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=C:/Users/maria/vcpkg" "-D_VCPKG_INSTALLED_DIR=C:/Users/maria/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_INSTALL_PREFIX=C:/Users/maria/vcpkg/packages/yasm-tool_x86-windows/debug""
-- The C compiler identification is MSVC 19.29.30037.0
-- The CXX compiler identification is MSVC 19.29.30037.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30037/bin/Hostx64/x86/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30037/bin/Hostx64/x86/cl.exe - broken
CMake Error at C:/Users/maria/vcpkg/downloads/tools/cmake-3.20.2-windows/cmake-3.20.2-windows-i386/share/cmake-3.20/Modules/CMakeTestCCompiler.cmake:66 (message):
  The C compiler

    "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30037/bin/Hostx64/x86/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/Users/maria/vcpkg/buildtrees/yasm-tool/x86-windows-dbg/CMakeFiles/CMakeTmp
    
    Run Build Command(s):C:/Users/maria/vcpkg/downloads/tools/ninja/1.10.2-windows/ninja.exe cmTC_9ac56 && [1/2] Building C object CMakeFiles\cmTC_9ac56.dir\testCCompiler.c.obj
    [2/2] Linking C executable cmTC_9ac56.exe
    FAILED: cmTC_9ac56.exe 
    cmd.exe /C "cd . && C:\Users\maria\vcpkg\downloads\tools\cmake-3.20.2-windows\cmake-3.20.2-windows-i386\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_9ac56.dir --rc=rc --mt=CMAKE_MT-NOTFOUND --manifests  -- C:\PROGRA~2\MIB055~1\2019\COMMUN~1\VC\Tools\MSVC\1429~1.300\bin\Hostx64\x86\link.exe /nologo CMakeFiles\cmTC_9ac56.dir\testCCompiler.c.obj  /out:cmTC_9ac56.exe /implib:cmTC_9ac56.lib /pdb:cmTC_9ac56.pdb /version:0.0 /machine:X86  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    RC Pass 1: command "rc /fo CMakeFiles\cmTC_9ac56.dir/manifest.res CMakeFiles\cmTC_9ac56.dir/manifest.rc" failed (exit code 0) with the following output:
    The system cannot find the file specified
    ninja: build stopped: subcommand failed.
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:1 (PROJECT)


-- Configuring incomplete, errors occurred!
See also "C:/Users/maria/vcpkg/buildtrees/yasm-tool/x86-windows-dbg/CMakeFiles/CMakeOutput.log".
See also "C:/Users/maria/vcpkg/buildtrees/yasm-tool/x86-windows-dbg/CMakeFiles/CMakeError.log".
ninja: build stopped: subcommand failed.

**Comment by NancyLi1013** [comment]
Sorry for the long delay. 

`--mt=CMAKE_MT-NOTFOUND`

Could you please reinstall Windows SDK and then try to rebuild this? @marianaiv

**Comment by allaboutfuture** [comment]
hi! Maria ,Do you solve your problem？I got the same error like you got。Can you tell me how to install yasm -tool，thx!

**Comment by sfhacker** [comment]
Are we STILL having issues with yasm?

**Comment by NancyLi1013** [comment]
@allaboutfuture 

This is not related with `yasm-tool`. You need to solve the environment problem. Have you tried to reinstall Windows SDK and then rebuild this?

**Comment by JackBoosY** [comment]
Please see https://github.com/microsoft/vcpkg/pull/22214.
