### ISSUE TITLE
Add GNU Triangulated Surface (GTS) Library

### ISSUE THREAD

**Issue by traversaro** [Microsoft/vcpkg#1869]
It would be great to have a port of the GNU Triangulated Surface (GTS) library ( http://gts.sourceforge.net/ ).

Debian package : https://packages.debian.org/source/sid/gts .
Homebrew formula : https://github.com/Homebrew/homebrew-core/blob/master/Formula/gts.rb .

Fork with CMake support: https://github.com/finetjul/gts

**Comment by alexkaratarakis** [comment]
Merged : )
