### ISSUE TITLE
[icu] build failure

### ISSUE THREAD

**Issue by AndreMeyerRMC** [microsoft/vcpkg#18708]
**Host Environment**
- OS: Windows 10
- Compiler: VS2017 (I guess... VS2015 is also installed)

**To Reproduce**
-new vcpkg installation 
`./vcpkg install icu`

**Failure logs** 
...
cl : Command line warning D9025 : overriding '/W3' with '/W4'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
...
Der Befehl "bash" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
-- return status = 1
Failed to compile oma.c
Der Befehl "link.exe" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
-- return status = 1
Error creating Windows DLL library. Failed command: link.exe /nologo /release /out:"../lib/icudtd69.dll"  /NXCOMPAT /DYNAMICBASE /DLL /NOENTRY /MANIFEST:NO /implib:"../lib/icudtd.lib" "./out/tmp/icudt69l_dat.obj" "./out/tmp/icudata.res"
Error generating package data.
make[1]: *** [Makefile:176: packagedata] Error 1
make: *** [Makefile:153: all-recursive] Error 2 

**Console output**
```
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:146 (message):
    Command failed: C:/dev/vcpkg/downloads/tools/msys2/703e5aa15d402568/usr/bin/make.exe -j 17 --trace -f Makefile all
    Working Directory: C:/dev/vcpkg/buildtrees/icu/x86-windows-dbg
    See logs for more information:
      C:\dev\vcpkg\buildtrees\icu\build-x86-windows-dbg-out.log
      C:\dev\vcpkg\buildtrees\icu\build-x86-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_make.cmake:194 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_make.cmake:26 (vcpkg_build_make)
  ports/icu/portfile.cmake:136 (vcpkg_install_make)
  scripts/ports.cmake:139 (include)


Error: Building package icu:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: icu:x86-windows
  Vcpkg version: 2021-05-05-b110959e13f562c2a17d7bd9e352e2dd8d6dc603
```

Error: Building package icu:x86-windows failed with: BUILD_FAILED

[build-x86-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/6732651/build-x86-windows-dbg-err.log)

**Comment by AndreMeyerRMC** [comment]
The path 'c:\dev\vcpkg\downloads\tools\msys2\703e5aa15d402568\usr\bin\' also contains bash.exe and link.exe

**Comment by PhoebeHui** [comment]
@AndreMeyerRMC, could you install the English language pack and try again?

**Comment by AndreMeyerRMC** [comment]
@PhoebeHui that did not help


**Failure log (english)**
'bash' is not recognized as an internal or external command,
operable program or batch file.
-- return status = 1
Failed to compile oma.c
'link.exe' is not recognized as an internal or external command,
operable program or batch file.
-- return status = 1
Error creating Windows DLL library. Failed command: link.exe /nologo /release /out:"../lib/icudtd69.dll"  /NXCOMPAT /DYNAMICBASE /DLL /NOENTRY /MANIFEST:NO /implib:"../lib/icudtd.lib" "./out/tmp/icudt69l_dat.obj" "./out/tmp/icudata.res"
Error generating package data.
make[1]: *** [Makefile:176: packagedata] Error 1
make: *** [Makefile:153: all-recursive] Error 2 

**Console out**
```
c:\dev\vcpkg>.\vcpkg install icu
Computing installation plan...
The following packages will be built and installed:
    icu[core]:x86-windows -> 69.1#10
Detecting compiler hash for triplet x86-windows...
-- Automatically setting HTTP(S)_PROXY environment variables to 10.32.15.50:8080
Could not locate cached archive: C:\Users\meye01\AppData\Local\vcpkg\archives\e3\e30547d67daf4b546e6f3383edd87ac0e3d7b94115871753315a9bdc2c211238.zip
Starting package 1/1: icu:x86-windows
Building package icu[core]:x86-windows...
-- Using C:/dev/vcpkg/downloads/icu4c-69_1-src.tgz
-- Cleaning sources at C:/dev/vcpkg/buildtrees/icu/src/c-69_1-src-78c1b28057.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/dev/vcpkg/downloads/icu4c-69_1-src.tgz
-- Applying patch C:/dev/vcpkg/ports/icu/disable-escapestr-tool.patch
-- Applying patch C:/dev/vcpkg/ports/icu/remove-MD-from-configure.patch
-- Applying patch C:/dev/vcpkg/ports/icu/fix_parallel_build_on_windows.patch
-- Applying patch C:/dev/vcpkg/ports/icu/fix-extra.patch
-- Using source at C:/dev/vcpkg/buildtrees/icu/src/c-69_1-src-78c1b28057.clean
-- Configuring x86-windows
-- Using msys root at C:/dev/vcpkg/downloads/tools/msys2/703e5aa15d402568
-- Using msys root at C:/dev/vcpkg/downloads/tools/msys2/aa5af7b2aa7e90e8
-- Configuring x86-windows-dbg
-- Configuring x86-windows-rel
-- Using msys root at C:/dev/vcpkg/downloads/tools/msys2/aaafe87dcead272e
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:146 (message):
    Command failed: C:/dev/vcpkg/downloads/tools/msys2/703e5aa15d402568/usr/bin/make.exe -j 17 --trace -f Makefile all
    Working Directory: C:/dev/vcpkg/buildtrees/icu/x86-windows-dbg
    See logs for more information:
      C:\dev\vcpkg\buildtrees\icu\build-x86-windows-dbg-out.log
      C:\dev\vcpkg\buildtrees\icu\build-x86-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_make.cmake:194 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_make.cmake:26 (vcpkg_build_make)
  ports/icu/portfile.cmake:136 (vcpkg_install_make)
  scripts/ports.cmake:139 (include)


Error: Building package icu:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: icu:x86-windows
  Vcpkg version: 2021-05-05-b110959e13f562c2a17d7bd9e352e2dd8d6dc603

Additionally, attach any relevant sections from the log files above.

c:\dev\vcpkg>
```

[build-x86-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/6738334/build-x86-windows-dbg-err.log)

**Comment by AndreMeyerRMC** [comment]
I'm sorry, maybe I misunderstood you... I installed the English language pack via the windows system settings. My Visual Studio installation already only has the English language pack activated, and it seems to me that none of it has been executed until the skript aborts.

I encountered this issue while trying to install the package "skia", and icu was when the installation progress stopped, so I ran a clean install of just icu to reproduce this error. zlib, bzip2, libpng and otherse were build successfully.

**Comment by PhoebeHui** [comment]
Could you execute '.\vcpkg install icu --debug', and provide us the output?

**Comment by AndreMeyerRMC** [comment]
error log is the same as before.
Console out:

[console_out_debug.txt](https://github.com/microsoft/vcpkg/files/6738493/console_out_debug.txt)

**Comment by PhoebeHui** [comment]
@AndreMeyerRMC, thanks for the information, it looks a same issue with https://github.com/microsoft/vcpkg/issues/18086.
We will use that issue to track.
