### ISSUE TITLE
[New Port Request] <cppzmq>

### ISSUE THREAD

**Issue by yzw88** [microsoft/vcpkg#18701]
Library name: cppzmq

Library description:  cppzmq is a C++ binding for libzmq.

Source repository URL: https://github.com/zeromq/cppzmq

**Comment by NancyLi1013** [comment]
Hi @yzw88 
Thanks for posting this request.

`cppzmq `has been added to vcpkg here https://github.com/microsoft/vcpkg/tree/master/ports/cppzmq. Please try to use it.

**Comment by NancyLi1013** [comment]
Please feel free to reopen this issue it you still have other concerns.

**Comment by yzw88** [comment]
thanks
