### ISSUE TITLE
'sndfile' port not cleanup when remove

### ISSUE THREAD

**Issue by heretic13** [microsoft/vcpkg#18713]
**Describe the bug**
Sndfile port does not remove headers and libraries when removed.

**Environment**
- OS: Windows 10 x64 21H1 19043.1081. 
- Compiler: Microsoft Visual Studio Enterprise 2019 Version 16.10.2

**To Reproduce**
1. vcpkg.exe install sndfile:x86-windows-static
2. vcpkg.exe remove sndfile:x86-windows-static
2. I can see the sndfile header and lib files in my file system.

**Expected behavior**

**Failure logs** 
-(please attached failure logs)

**Additional context**

**Comment by FrankXie05** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
