### ISSUE TITLE
[sqlite3] build failure

### ISSUE THREAD

**Issue by arunabh42** [microsoft/vcpkg#18716]
Not able to install the package it's showing 

The following packages will be built and installed:
    sqlite3[core]:x86-windows -> 3.35.5
No suitable Visual Studio instances were found

**Comment by JonLiu1993** [comment]
@arunabh42 ,Thanks for posting this issue,
have you installed Visual Studio?

**Comment by arunabh42** [comment]
Yes installed.

**Comment by JonLiu1993** [comment]
@arunabh42 ,Can you provide your specific visual Studio version?

**Comment by arunabh42** [comment]
It's Visual Studio 2019

**Comment by JonLiu1993** [comment]
Please download the English language pack and try to install again

**Comment by PhoebeHui** [comment]
@arunabh42, does this still be a problem for you? have you try above suggestion?

**Comment by arunabh42** [comment]
Yes, it works.

**Comment by SenkoLS** [comment]
It dsnt work! Windows 10 + Visual Studio 2022
