### ISSUE TITLE
Visual Studio with vcpkg doesn't recognize custom triplet installed libraries.

### ISSUE THREAD

**Issue by Pilipets** [microsoft/vcpkg#18717]
**Details:**
I'm using VS2019, and it works as expected with vcpkg install *:x64-windows.
All includes are recognized and linkage works as well.

**Problem:**
I created custom triplet `x64-windows-v140` for building on C++14 with MSVC v140.
```
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)

set(VCPKG_PLATFORM_TOOLSET v140)
```

Now after installing the respective libraries with vcpkg `install boost:x64-windows-v140` and `boost-asio:x64-windows-v140` and integrating it to the project via NuGet packages, the includes aren't recognized.
The built files, sources, headers for sure exist and project config is correct - see the attached snapshots.

**Question:**
How to fix this? Any help is highly appreciated...

![1](https://user-images.githubusercontent.com/22419519/123817183-9b14ef80-d900-11eb-829a-9295e5188193.jpg)
![2](https://user-images.githubusercontent.com/22419519/123817186-9c461c80-d900-11eb-9e64-a7b9538a3ab4.jpg)
![3](https://user-images.githubusercontent.com/22419519/123818110-62c1e100-d901-11eb-85ed-ec33f0b28ebc.png)
![4](https://user-images.githubusercontent.com/22419519/123819140-39558500-d902-11eb-9c38-d6b614760bda.png)

**Comment by PhoebeHui** [comment]
@Pilipets, I'm not sure what I missed, I tried with below steps, and I can't repro this issue, could you please have a try?

1. PS F:\vcpkg\src> ./vcpkg install boost-asio:x64-windows-v140
2. PS F:\vcpkg\src> ./vcpkg integrate install
3. Create C++ console project with VS and change the configuration to x64
4. Set the triplet to x64-windows-v140 in vcpkg section in project property.
5. include the asio headers, it looks everything is correct.

![image](https://user-images.githubusercontent.com/20694052/123913772-2f3e8f80-d9b1-11eb-8bd0-a0502390a02d.png)

**Comment by Pilipets** [comment]
As I mentioned in the description, please try using vcpkg integrate project and add the respective package with NuGet package manager to the project in order to reproduce the issue.
What Visual Studio version did you use?

**Comment by PhoebeHui** [comment]
I'm using msvc v140  with vs2019 16.7.16, thanks for the information, I will try to repro this issue.

**Comment by PhoebeHui** [comment]
@Pilipets, I using msvc140 with vs2019 16.10.3, and I still can't repro this issue

1. PS E:\vcpkg\clean\vcpkg> ./vcpkg install boost-asio:x64-windows-v140
2. PS E:\vcpkg\clean\vcpkg> ./vcpkg integrate project
3. Create C++ console project with VS and change the configuration to x64
4. Tools->NuGet Package Manager->Package Manager Console and paste " Install-Package vcpkg.E.vcpkg.clean.vcpkg -Source "E:\vcpkg\clean\vcpkg\scripts\buildsystems"
5. Project property -> vcpkg, and setting:
![image](https://user-images.githubusercontent.com/20694052/124735429-9e375d80-df48-11eb-9da9-68500ed7317a.png)

6. Include the asio headers, it looks everything is correct.


![image](https://user-images.githubusercontent.com/20694052/124735679-d8a0fa80-df48-11eb-9914-0c7f31f83bb2.png)

**Comment by PhoebeHui** [comment]
@Pilipets, could you try above steps?

**Comment by Pilipets** [comment]
Alright, I updated vcpkg, tried on the clean project, and it worked. Let me see where the problem comes from on another project.

**Comment by Pilipets** [comment]
Yes, it worked after git pull + .\bootstrap-vcpkg.bat.

However, another concern I have relates to moving the project with installed packages to another PC machine for building.
I can't delete the packages.config if the packages folder in the project is missing - is it expected behaviour?

![image](https://user-images.githubusercontent.com/22419519/125442387-40d274a9-c0b1-4118-a898-871b27ffc4f4.png)

If this folder is missing, I can't simply remove the package in order to install it again with another path.

**Comment by PhoebeHui** [comment]
I can't repro this issue, I removed the packages folder and delete the packages.config successfully, were you able to repro this issue stably?

**Comment by Pilipets** [comment]
You need to move the project to another machine - where the path to the extension becomes invalid.
Anyway, thanks - I will create another issue in case of stable reproductions.
