### ISSUE TITLE
[szip] build failure

### ISSUE THREAD

**Issue by Hanqer** [microsoft/vcpkg#18734]
**Host Environment**
- OS: Windows

**To Reproduce**
`./vcpkg install szip`

**Failure logs** 
Package: szip:x86-windows
Vcpkg version: 2021-05-05-e8977e69d9a3fb462d9ad42013d83a7682706659

Error: Failed to download from mirror set:
https://support.hdfgroup.org/ftp/lib-external/szip/2.1.1/src/szip-2.1.1.tar.gz: WinHttpSendRequest() failed: 12002

I think this FTP server is broken.

**Comment by JackBoosY** [comment]
No, it's not down. Please use proxy to download it. Or use mirror in China.

**Comment by PhoebeHui** [comment]
@Hanqer, we have increased the timeouts for downloads in vcpkg tool, the next release should include the improvements. 
Please also see a workaround in https://github.com/microsoft/vcpkg/issues/19289#issuecomment-890792856.
