### ISSUE TITLE
[New Port Request] <wintun>

### ISSUE THREAD

**Issue by ChanthMiao** [microsoft/vcpkg#18735]
Library name: wintun

Library description: Wintun is a very simple and minimal TUN driver for the Windows kernel, which provides userspace programs with a simple network adapter for reading and writing packets.

Source repository URL: <https://git.zx2c4.com/wintun/tree/>

Project homepage <https://www.wintun.net/>:

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

Due to Microsoft's driver ***signing*** requirements, wintun is distributed as a simple ZIP archive containing ***signed and precompiled DLLs*** for AMD64, X86, ARM64, and ARM32, along with the wintun.h header file for applications.

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
