### ISSUE TITLE
[libmariadb] Missing caching_sha2_password.so for Linux/MacOs build

### ISSUE THREAD

**Issue by ludekvodicka** [microsoft/vcpkg#18749]
****

There are missing dynamic files for libMariaDB in the case of build on Linux and MacOS.

MariaDB connector needs for example caching_sha2_password when connecting to MySQL 8.0. Without this file, MariaDB library returns error `"Plugin caching_sha2_password could not be loaded: dlopen(PATH/caching_sha2_password.so.2) image not found`

- Windows: This file (together with others) is correctly built and installed for windows to "plugin" directory.
- Linux: some of these files are built but not installed. Files can be found at `vcpkg/buildtrees/libmariadb/x64-linux-dbg/caching_sha2_password.so 
- MacOS: these files are completely missing and not build

I'm installing it via `vcpkg install libmariadb`

**Comment by JackBoosY** [comment]
```
buildtrees/libmariadb/x64-osx-dbg/mysql_clear_password.so
buildtrees/libmariadb/x64-osx-dbg/caching_sha2_password.so
buildtrees/libmariadb/x64-osx-dbg/dialog.so
buildtrees/libmariadb/x64-osx-dbg/client_ed25519.so
buildtrees/libmariadb/x64-osx-dbg/sha256_password.so
```
The issues is not install them.

**Comment by JackBoosY** [comment]
@ludekvodicka  Can you please provide me the reproduce steps? I think we also need to patch the load plugin path.

Thanks.

**Comment by JackBoosY** [comment]
@ludekvodicka Ping for response.

**Comment by ludekvodicka** [comment]
I believe it's already fixed.  I already worked on this with someone else.

**Comment by JackBoosY** [comment]
Okay, please reopen this PR when it happened again.
