### ISSUE TITLE
[yasm] Dependent library of yasm binary is missing

### ISSUE THREAD

**Issue by Christsnatcher** [microsoft/vcpkg#18746]
**Host Environment**
- OS: Windows 8.1 x64, up-to-date
- Compiler: MSVC 19.29.30038.1

**To Reproduce**
vcpkg install mpg123:x86-windows --> fails
vcpkg install mpg123:x64-windows --> fails
vcpkg install mpg123:x86-windows-static --> succeeds
vcpkg install mpg123:x64-windows-static --> succeeds

**Failure logs** 
**x86**
```
The following packages will be built and installed:
    mpg123[core]:x86-windows -> 1.28.0
Detecting compiler hash for triplet x86-windows...
Could not locate cached archive: C:\Users\Daniel\AppData\Local\vcpkg\archives\7f\7ff2d3bab8cfe01abcb3de9fd52e93f808c52c7bc03a32808457f3d82d7cc346.zip
Starting package 1/1: mpg123:x86-windows
Building package mpg123[core]:x86-windows...
-- Downloading https://sourceforge.net/projects/mpg123/files/mpg123/1.28.0/mpg123-1.28.0.tar.bz2/download;https://sourceforge.net/projects/mpg123/files/mpg123
et;https://sourceforge.net/projects/mpg123/files/mpg123/1.28.0/mpg123-1.28.0.tar.bz2/download?use_mirror=freefr;https://sourceforge.net/projects/mpg123/files/
s://sourceforge.net/projects/mpg123/files/mpg123/1.28.0/mpg123-1.28.0.tar.bz2/download?use_mirror=netix;https://sourceforge.net/projects/mpg123/files/mpg123/1
-- Extracting source D:/Code/Repos/vcpkg/downloads/mpg123-1.28.0.tar.bz2
-- Applying patch 0001-fix-checkcpuarch-path.patch
-- Using source at D:/Code/Repos/vcpkg/buildtrees/mpg123/src/4e333ee4f3-f9ae7d9a6e.clean
-- Found external ninja('1.10.2').
-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:146 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /m
    Working Directory: D:/Code/Repos/vcpkg/buildtrees/mpg123/x86-windows-dbg
    See logs for more information:
      D:\Code\Repos\vcpkg\buildtrees\mpg123\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:104 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:44 (vcpkg_build_cmake)
  ports/mpg123/portfile.cmake:33 (vcpkg_install_cmake)
  scripts/ports.cmake:139 (include)


Error: Building package mpg123:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: mpg123:x86-windows
  Vcpkg version: 2021-05-05-e8977e69d9a3fb462d9ad42013d83a7682706659
```
**x64**
```
D:\Code\Repos\vcpkg>vcpkg install mpg123:x64-windows
Computing installation plan...
The following packages will be built and installed:
    mpg123[core]:x64-windows -> 1.28.0
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\Daniel\AppData\Local\vcpkg\archives\7e\7ef4e1a094c74c70480583abe8b85b6aabc42d923dc1a5d95c544d2fe4667652.zip
Starting package 1/1: mpg123:x64-windows
Building package mpg123[core]:x64-windows...
-- Using D:/Code/Repos/vcpkg/downloads/mpg123-1.28.0.tar.bz2
-- Cleaning sources at D:/Code/Repos/vcpkg/buildtrees/mpg123/src/4e333ee4f3-f9ae7d9a6e.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/Code/Repos/vcpkg/downloads/mpg123-1.28.0.tar.bz2
-- Applying patch 0001-fix-checkcpuarch-path.patch
-- Using source at D:/Code/Repos/vcpkg/buildtrees/mpg123/src/4e333ee4f3-f9ae7d9a6e.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:146 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /m
    Working Directory: D:/Code/Repos/vcpkg/buildtrees/mpg123/x64-windows-dbg
    See logs for more information:
      D:\Code\Repos\vcpkg\buildtrees\mpg123\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:104 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:44 (vcpkg_build_cmake)
  ports/mpg123/portfile.cmake:33 (vcpkg_install_cmake)
  scripts/ports.cmake:139 (include)


Error: Building package mpg123:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: mpg123:x64-windows
  Vcpkg version: 2021-05-05-e8977e69d9a3fb462d9ad42013d83a7682706659
```

**Additional context**
The issue was introduced in commit 5edbbf1a70a0a502e6362f51bf875b96469ed807, which updated the mpg123 version from 1.26.5  to 1.28.0. This obviously means that both the mpg123 source code and multiple port-related vcpkg files got changed, and I am not 100% if we have an actual vcpkg port bug here or if the src itself is the culprit. I mention this as I tried to manually compile the src using latest VS 2019, and the process terminated with exactly the same - long - error message you'll find in one of the logs attached. 

Very interesting is the fact that building static libs works perfectly fine, so I the issue has to be connected to the building of _dynamic_ libraries somehow.

Ah, before you ask, yes, I tested with my "external" Ninja and CMake installations removed from %PATH% and Program Files as well, with exactly the same results.

Attached you'll find all logs generated during the operations mentioned above.

[mpg123_vcpkg_logs.zip](https://github.com/microsoft/vcpkg/files/6745472/mpg123_vcpkg_logs.zip)

**Comment by NancyLi1013** [comment]
Hi @Christsnatcher 
Thanks for posting this issue.

`yasm: FATAL: could not load standard modules`

Can you install `yasm-tool` successfully on your machine? Seems there are something wrong with `yasm`. Could you please help check this?

But I cannot reproduce this on my machine on Windows 10 with VS2019 16.10.

**Comment by Christsnatcher** [comment]
Hello,

I found the culprit: Searching for the error message led me to this part of yasm source code:
```
#ifdef CMAKE_BUILD
    /* Load standard modules */
#ifdef BUILD_SHARED_LIBS
    if (!load_plugin("yasmstd")) {
        print_error(_("%s: could not load standard modules"), _("FATAL"));
        return EXIT_FAILURE;
```
referenced e.g. on these sites:

opensource.dell.com/releases/ThinClient/WTOS/thinos_9.0/patched-yasm/frontends/yasm/yasm.c
https://chromium.googlesource.com/chromium/deps/yasm/patched-yasm/+/4671120cd8558ce62ee8672ebf3eb6f5216f909b/frontends/yasm/yasm.c

So I searched my system for "yasmstd.dll", with these results:

https://i.gyazo.com/6550b14415c8c6034dbe5b715f9fe2d9.png

Apparently the yasm.exe used fails to find the resp. yasmstd.dll in their vcpkg standard path(s), so I followed the build process in SysInternals Process Monitor with "yasm.exe" set as filter to find out where it ACTUALLY searches for it, the result was interesting:

https://i.gyazo.com/bacd187addc2cb80be06304fbfb14ad7.png

The tool first looks in its own folder for the yasmstd.dll, which for some reason isn't there, while yasm.dll actually IS present, then it iterates through all %PATH% entries, but obviously with File Not Found error.

To verify my "theory" I simply copied yasmstd.dll from "..\vcpkg\installed\x86-windows\bin\" to "vcpkg\installed\x86-windows\tools\yasm\", and was actually able to build mpg123:x86-windows without any issues, the same works for the x64 port.

So, maybe you could implement a line into the code of the yasm-tool port which makes yasmstd.dll get copied from its standard folder to the resp. "tools\yasm\" directory, this would resolve all similar problems, thank you very much!

**Comment by JackBoosY** [comment]
```
D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: Custom build for 'D:\Code\Repos\vcpkg\buildtrees\mpg123\x64-windows-dbg\CMakeFiles\b32fd62167209f98bb76427b287f7783\dct36_x86_64.S.asm.rule;D:\Code\Repos\vcpkg\buildtrees\mpg123\x64-windows-dbg\CMakeFiles\b32fd62167209f98bb76427b287f7783\dct36_x86_64.S.obj.rule;D:\Code\Repos\vcpkg\buildtrees\mpg123\x64-windows-dbg\CMakeFiles\b32fd62167209f98bb76427b287f7783\dct64_x86_64_float.S.asm.rule;D:\Code\Repos\vcpkg\buildtrees\mpg123\x64-windows-dbg\CMakeFiles\b32fd62167209f98bb76427b287f7783\dct64_x86_64_float.S.obj.rule;D:\Code\Repos\vcpkg\buildtrees\mpg123\x64-windows-dbg\CMakeFiles\b32fd62167209f98bb76427b287f7783\synth_x86_64_float.S.asm.rule;D:\Code\Repos\vcpkg\buildtrees\mpg123\x64-windows-dbg\CMakeFiles\b32fd62167209f98bb76427b287f7783\synth_x86_64_float.S.obj.rule;D:\Code\Repos\vcpkg\buildtrees\mpg123\x64-windows-dbg\CMakeFiles\b32fd62167209f98bb76427b287f7783\synth_x86_64_s32.S.asm.rule;D:\Code\Repos\vcpkg\buildtrees\mpg123\x64-windows-dbg\CMakeFiles\b32fd62167209f98bb76427b287f7783\synth_x86_64_s32.S.obj.rule;D:\Code\Repos\vcpkg\buildtrees\mpg123\x64-windows-dbg\CMakeFiles\b32fd62167209f98bb76427b287f7783\synth_stereo_x86_64_float.S.asm.rule;D:\Code\Repos\vcpkg\buildtrees\mpg123\x64-windows-dbg\CMakeFiles\b32fd62167209f98bb76427b287f7783\synth_stereo_x86_64_float.S.obj.rule;D:\Code\Repos\vcpkg\buildtrees\mpg123\x64-windows-dbg\CMakeFiles\b32fd62167209f98bb76427b287f7783\synth_stereo_x86_64_s32.S.asm.rule;D:\Code\Repos\vcpkg\buildtrees\mpg123\x64-windows-dbg\CMakeFiles\b32fd62167209f98bb76427b287f7783\synth_stereo_x86_64_s32.S.obj.rule;D:\Code\Repos\vcpkg\buildtrees\mpg123\x64-windows-dbg\CMakeFiles\b32fd62167209f98bb76427b287f7783\dct36_avx.S.asm.rule;D:\Code\Repos\vcpkg\buildtrees\mpg123\x64-windows-dbg\CMakeFiles\b32fd62167209f98bb76427b287f7783\dct36_avx.S.obj.rule;D:\Code\Repos\vcpkg\buildtrees\mpg123\x64-windows-dbg\CMakeFiles\b32fd62167209f98bb76427b287f7783\dct64_avx_float.S.asm.rule;D:\Code\Repos\vcpkg\buildtrees\mpg123\x64-windows-dbg\CMakeFiles\b32fd62167209f98bb76427b287f7783\dct64_avx_float.S.obj.rule;D:\Code\Repos\vcpkg\buildtrees\mpg123\x64-windows-dbg\CMakeFiles\b32fd62167209f98bb76427b287f7783\synth_stereo_avx_float.S.asm.rule;D:\Code\Repos\vcpkg\buildtrees\mpg123\x64-windows-dbg\CMakeFiles\b32fd62167209f98bb76427b287f7783\synth_stereo_avx_float.S.obj.rule;D:\Code\Repos\vcpkg\buildtrees\mpg123\x64-windows-dbg\CMakeFiles\b32fd62167209f98bb76427b287f7783\synth_stereo_avx_s32.S.asm.rule;D:\Code\Repos\vcpkg\buildtrees\mpg123\x64-windows-dbg\CMakeFiles\b32fd62167209f98bb76427b287f7783\synth_stereo_avx_s32.S.obj.rule;D:\Code\Repos\vcpkg\buildtrees\mpg123\x64-windows-dbg\CMakeFiles\b32fd62167209f98bb76427b287f7783\getcpuflags_x86_64.S.asm.rule;D:\Code\Repos\vcpkg\buildtrees\mpg123\x64-windows-dbg\CMakeFiles\b32fd62167209f98bb76427b287f7783\getcpuflags_x86_64.S.obj.rule;D:\Code\Repos\vcpkg\buildtrees\mpg123\x64-windows-dbg\CMakeFiles\b32fd62167209f98bb76427b287f7783\synth_x86_64_accurate.S.asm.rule;D:\Code\Repos\vcpkg\buildtrees\mpg123\x64-windows-dbg\CMakeFiles\b32fd62167209f98bb76427b287f7783\synth_x86_64_accurate.S.obj.rule;D:\Code\Repos\vcpkg\buildtrees\mpg123\x64-windows-dbg\CMakeFiles\b32fd62167209f98bb76427b287f7783\synth_stereo_x86_64_accurate.S.asm.rule;D:\Code\Repos\vcpkg\buildtrees\mpg123\x64-windows-dbg\CMakeFiles\b32fd62167209f98bb76427b287f7783\synth_stereo_x86_64_accurate.S.obj.rule;D:\Code\Repos\vcpkg\buildtrees\mpg123\x64-windows-dbg\CMakeFiles\b32fd62167209f98bb76427b287f7783\synth_stereo_avx_accurate.S.asm.rule;D:\Code\Repos\vcpkg\buildtrees\mpg123\x64-windows-dbg\CMakeFiles\b32fd62167209f98bb76427b287f7783\synth_stereo_avx_accurate.S.obj.rule' exited with code 1. [D:\Code\Repos\vcpkg\buildtrees\mpg123\x64-windows-dbg\src\libmpg123\libmpg123.vcxproj]
```

**Comment by evpobr** [comment]
I don't see how I can help. In fact, all these yasm, yasm-tool, yasm-tool-helper and friends are driving me crazy.

**Comment by Christsnatcher** [comment]
> ```
> D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: Custom build for 'D:\Code\Repos\vcpkg\buildtrees\mpg123\x64-windows-dbg\CMakeFiles\b32fd62167209f98bb76427b287f7783\dct36_x86_64.S.asm.rule;D:\Code\Repos\vcpkg\buildtrees\mpg123\x64-windows-dbg\CMakeFiles\b32fd62167209f98bb76427b287f7783\dct36_x86_64.S.obj.rule;D:\Code\Repos\vcpkg\buildtrees\mpg123\x64-windows-dbg\CMakeFiles\b32fd62167209f98bb76427b287f7783\dct64_x86_64_float.S.asm.rule;D:\Code\Repos\vcpkg\buildtrees\mpg123\x64-windows-dbg\CMakeFiles\b32fd62167209f98bb76427b287f7783\dct64_x86_64_float.S.obj.rule;D:\Code\Repos\vcpkg\buildtrees\mpg123\x64-windows-dbg\CMakeFiles\b32fd62167209f98bb76427b287f7783\synth_x86_64_float.S.asm.rule;D:\Code\Repos\vcpkg\buildtrees\mpg123\x64-windows-dbg\CMakeFiles\b32fd62167209f98bb76427b287f7783\synth_x86_64_float.S.obj.rule;D:\Code\Repos\vcpkg\buildtrees\mpg123\x64-windows-dbg\CMakeFiles\b32fd62167209f98bb76427b287f7783\synth_x86_64_s32.S.asm.rule;D:\Code\Repos\vcpkg\buildtrees\mpg123\x64-windows-dbg\CMakeFiles\b32fd62167209f98bb76427b287f7783\synth_x86_64_s32.S.obj.rule;D:\Code\Repos\vcpkg\buildtrees\mpg123\x64-windows-dbg\CMakeFiles\b32fd62167209f98bb76427b287f7783\synth_stereo_x86_64_float.S.asm.rule;D:\Code\Repos\vcpkg\buildtrees\mpg123\x64-windows-dbg\CMakeFiles\b32fd62167209f98bb76427b287f7783\synth_stereo_x86_64_float.S.obj.rule;D:\Code\Repos\vcpkg\buildtrees\mpg123\x64-windows-dbg\CMakeFiles\b32fd62167209f98bb76427b287f7783\synth_stereo_x86_64_s32.S.asm.rule;D:\Code\Repos\vcpkg\buildtrees\mpg123\x64-windows-dbg\CMakeFiles\b32fd62167209f98bb76427b287f7783\synth_stereo_x86_64_s32.S.obj.rule;D:\Code\Repos\vcpkg\buildtrees\mpg123\x64-windows-dbg\CMakeFiles\b32fd62167209f98bb76427b287f7783\dct36_avx.S.asm.rule;D:\Code\Repos\vcpkg\buildtrees\mpg123\x64-windows-dbg\CMakeFiles\b32fd62167209f98bb76427b287f7783\dct36_avx.S.obj.rule;D:\Code\Repos\vcpkg\buildtrees\mpg123\x64-windows-dbg\CMakeFiles\b32fd62167209f98bb76427b287f7783\dct64_avx_float.S.asm.rule;D:\Code\Repos\vcpkg\buildtrees\mpg123\x64-windows-dbg\CMakeFiles\b32fd62167209f98bb76427b287f7783\dct64_avx_float.S.obj.rule;D:\Code\Repos\vcpkg\buildtrees\mpg123\x64-windows-dbg\CMakeFiles\b32fd62167209f98bb76427b287f7783\synth_stereo_avx_float.S.asm.rule;D:\Code\Repos\vcpkg\buildtrees\mpg123\x64-windows-dbg\CMakeFiles\b32fd62167209f98bb76427b287f7783\synth_stereo_avx_float.S.obj.rule;D:\Code\Repos\vcpkg\buildtrees\mpg123\x64-windows-dbg\CMakeFiles\b32fd62167209f98bb76427b287f7783\synth_stereo_avx_s32.S.asm.rule;D:\Code\Repos\vcpkg\buildtrees\mpg123\x64-windows-dbg\CMakeFiles\b32fd62167209f98bb76427b287f7783\synth_stereo_avx_s32.S.obj.rule;D:\Code\Repos\vcpkg\buildtrees\mpg123\x64-windows-dbg\CMakeFiles\b32fd62167209f98bb76427b287f7783\getcpuflags_x86_64.S.asm.rule;D:\Code\Repos\vcpkg\buildtrees\mpg123\x64-windows-dbg\CMakeFiles\b32fd62167209f98bb76427b287f7783\getcpuflags_x86_64.S.obj.rule;D:\Code\Repos\vcpkg\buildtrees\mpg123\x64-windows-dbg\CMakeFiles\b32fd62167209f98bb76427b287f7783\synth_x86_64_accurate.S.asm.rule;D:\Code\Repos\vcpkg\buildtrees\mpg123\x64-windows-dbg\CMakeFiles\b32fd62167209f98bb76427b287f7783\synth_x86_64_accurate.S.obj.rule;D:\Code\Repos\vcpkg\buildtrees\mpg123\x64-windows-dbg\CMakeFiles\b32fd62167209f98bb76427b287f7783\synth_stereo_x86_64_accurate.S.asm.rule;D:\Code\Repos\vcpkg\buildtrees\mpg123\x64-windows-dbg\CMakeFiles\b32fd62167209f98bb76427b287f7783\synth_stereo_x86_64_accurate.S.obj.rule;D:\Code\Repos\vcpkg\buildtrees\mpg123\x64-windows-dbg\CMakeFiles\b32fd62167209f98bb76427b287f7783\synth_stereo_avx_accurate.S.asm.rule;D:\Code\Repos\vcpkg\buildtrees\mpg123\x64-windows-dbg\CMakeFiles\b32fd62167209f98bb76427b287f7783\synth_stereo_avx_accurate.S.obj.rule' exited with code 1. [D:\Code\Repos\vcpkg\buildtrees\mpg123\x64-windows-dbg\src\libmpg123\libmpg123.vcxproj]
> ```
> 
> cc @evpobr

It exit with code 1 because the assembler - yasm - fails, obviously. If you want to reprodruce, install yasm and yasm-tool and yasm-tool-helper in x86-windows, x64-windows, x86-windows-static and x64-windows-static, then try to build mpg123. It will work for the static builds and fail for the dynamic ones. Afterwards you can change the issue category again. ;)

**Comment by JackBoosY** [comment]
In _SOURCE_PATH/ports/cmake/src/libmpg123/CMakeLists.txt_:
```cmake
        add_custom_command(
            OUTPUT ${FILENAME}.obj
            COMMAND ${YASM_ASSEMBLER} -a x86 -m ${MACHINE} -p gas -r raw -f win32 -g null -o ${FILENAME}.obj ${FILENAME}.asm
            DEPENDS ${FILENAME}.asm
            WORKING_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}")
```

details:
```
YASM_ASSEMBLER: F:/vcpkg/installed/x86-windows/tools/yasm/yasm.exe
command: F:/vcpkg/installed/x86-windows/tools/yasm/yasm.exe -a x86 -m x86 -p gas -r raw -f win32 -g null -o tabinit_mmx.S.obj tabinit_mmx.S.asm
command: F:/vcpkg/installed/x86-windows/tools/yasm/yasm.exe -a x86 -m x86 -p gas -r raw -f win32 -g null -o dct36_sse.S.obj dct36_sse.S.asm
command: F:/vcpkg/installed/x86-windows/tools/yasm/yasm.exe -a x86 -m x86 -p gas -r raw -f win32 -g null -o dct64_sse_float.S.obj dct64_sse_float.S.asm
command: F:/vcpkg/installed/x86-windows/tools/yasm/yasm.exe -a x86 -m x86 -p gas -r raw -f win32 -g null -o synth_sse_float.S.obj synth_sse_float.S.asm
command: F:/vcpkg/installed/x86-windows/tools/yasm/yasm.exe -a x86 -m x86 -p gas -r raw -f win32 -g null -o synth_stereo_sse_float.S.obj synth_stereo_sse_float.S.asm
command: F:/vcpkg/installed/x86-windows/tools/yasm/yasm.exe -a x86 -m x86 -p gas -r raw -f win32 -g null -o synth_sse_s32.S.obj synth_sse_s32.S.asm
command: F:/vcpkg/installed/x86-windows/tools/yasm/yasm.exe -a x86 -m x86 -p gas -r raw -f win32 -g null -o synth_stereo_sse_s32.S.obj synth_stereo_sse_s32.S.asm
command: F:/vcpkg/installed/x86-windows/tools/yasm/yasm.exe -a x86 -m x86 -p gas -r raw -f win32 -g null -o synth_sse_accurate.S.obj synth_sse_accurate.S.asm
command: F:/vcpkg/installed/x86-windows/tools/yasm/yasm.exe -a x86 -m x86 -p gas -r raw -f win32 -g null -o synth_stereo_sse_accurate.S.obj synth_stereo_sse_accurate.S.asm
```
Results:
```
     8>CustomBuild:
         Building Custom Rule F:/vcpkg/buildtrees/mpg123/src/4e333ee4f3-f9ae7d9a6e/ports/cmake/src/libmpg123/CMakeLists.txt
         Generating tabinit_mmx.S.obj
         yasm: FATAL: could not load standard modules
```

**Comment by JackBoosY** [comment]
In favor of #23218.
