### ISSUE TITLE
Build failing libgnutls:x64-windows

### ISSUE THREAD

**Issue by UniversalBinary** [microsoft/vcpkg#18743]
[config-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/6744425/config-x64-windows-dbg-out.log)
[config-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/6744427/config-x64-windows-dbg-err.log)

Below is the command output prior to the failure:

Starting package 11/11: libgnutls:x64-windows
Building package libgnutls[core]:x64-windows...
-- Downloading https://www.gnupg.org/ftp/gcrypt/gnutls/v3.6/gnutls-3.6.15.tar.xz -> gnutls-3.6.15.tar.xz...
-- Extracting source C:/vcpkg/downloads/gnutls-3.6.15.tar.xz
-- Using source at C:/vcpkg/buildtrees/libgnutls/src/3.6.15-4050d06d46.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
-- Using msys root at C:/vcpkg/downloads/tools/msys2/703e5aa15d402568
-- Using msys root at C:/vcpkg/downloads/tools/msys2/aa5af7b2aa7e90e8
-- Configuring x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
    Command failed: C:/vcpkg/downloads/tools/msys2/703e5aa15d402568/usr/bin/bash.exe --noprofile --norc --debug -c "V=1 CPP='cl.exe -E' CC='cl.exe' CC_FOR_BUILD='cl.exe' CXX='cl.exe' AR='lib.exe' LD='link.exe -verbose' RANLIB=':' STRIP=':' NM='dumpbin.exe -symbols -headers' DLLTOOL='link.exe -verbose -dll' CCAS=':' AS=':' ./../src/3.6.15-4050d06d46.clean/configure  --disable-doc --disable-silent-rules --disable-tests --disable-maintainer-mode --disable-rpath --disable-libdane --with-included-unistring --without-p11-kit --without-tpm LDFLAGS= ac_cv_prog_ac_ct_STRIP=: gl_cv_double_slash_root=yes ac_cv_func_memmove=yes --disable-silent-rules --verbose --enable-shared --disable-static --prefix=/C/vcpkg/installed/x64-windows/debug --bindir='${prefix}'/../tools/libgnutls/debug/bin --sbindir='${prefix}'/../tools/libgnutls/debug/sbin --includedir='${prefix}'/../include --datarootdir='${prefix}'/share/libgnutls"
    Working Directory: C:/vcpkg/buildtrees/libgnutls/x64-windows-dbg
    Error code: 1
    See logs for more information:
      C:\vcpkg\buildtrees\libgnutls\config-x64-windows-dbg-out.log
      C:\vcpkg\buildtrees\libgnutls\config-x64-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:807 (vcpkg_execute_required_process)
  ports/libgnutls/portfile.cmake:27 (vcpkg_configure_make)
  scripts/ports.cmake:139 (include)

Error: Building package libgnutls:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libgnutls:x64-windows
  Vcpkg version: 2021-05-05-e8977e69d9a3fb462d9ad42013d83a7682706659

Additionally, attach any relevant sections from the log files above.

**Comment by JackBoosY** [comment]
```
configure: WARNING: Compiler does not support C99. It may not be able to compile the project.
configure: error: 
  ***
  *** Libhogweed (nettle's companion library) 3.4.1 was not found. Note that you must compile nettle with gmp support.
```

**Comment by JackBoosY** [comment]
cc @dg0yt  @jgehw @emptyVoid

**Comment by JackBoosY** [comment]
That's due to nettle doesn't install hogweed library.

**Comment by JackBoosY** [comment]
Duplicated to #18395.
