### ISSUE TITLE
[pe-parse] update to 1.3.0

### ISSUE THREAD

**Issue by liubin3071** [microsoft/vcpkg#18756]
Library name: pe-parse

New version number: 1.3.0

Other information that may be useful (release notes, etc...)

https://github.com/trailofbits/pe-parse

**Comment by PhoebeHui** [comment]
We have an exist PR https://github.com/microsoft/vcpkg/pull/17575 to update it.

**Comment by JonLiu1993** [comment]
Fix by #20918
