### ISSUE TITLE
How do I find libgit2 with CMake?

### ISSUE THREAD

**Issue by rayferric** [microsoft/vcpkg#18753]
vcpkg does not provide libgit2-config.cmake and configuring fails. Am I missing something? Should I write my own find script and submit a PR? It's my first contact with vcpkg.

**Comment by PhoebeHui** [comment]
@rayferric, the upstream doesn't export the cmake config and targets files, so you can create a PR to export an unofficial cmake config and targts files in vcpkg, and you can also submit an issue or request in Upstream.

**Comment by rayferric** [comment]
Alright! Thanks for clarification, PhoebeHui.
