### ISSUE TITLE
[vcpkg upgrade] overlay triplet on osx does not work when running vcpkg upgrade.

### ISSUE THREAD

**Issue by daschuer** [microsoft/vcpkg#18764]
**Describe the bug**

I am trying to us a overlay triplet for x64-osx 
I have created overlay/triplets/x64-osx.cmake and set the environment variable VCPKG_OVERLAY_TRIPLETS to overlay/triplets 

When building a port, I receive these lines: 
```
[OVERLAY] Loading triplet configuration from: /Users/runner/mixxx-vcpkg/overlay/triplets/x64-osx.cmake
...
...
Error getting canonicalization of overlay/triplets: No such file or directory
```
Is it correct that the first line confirms that the file is there but it forgets it later on? 

**Environment**
- OS: osx
- Compiler: GNU 11.1.0

**To Reproduce**
Use this workflow on github:
https://github.com/mixxxdj/vcpkg/blob/871675591e3fcc2b876d7a6f59cbe3518a142580/.github/workflows/build.yml

I am not able to provide a minimum failing receipt, because I have no access to an osx device.  

**Expected behavior**
The overlay triplet should be used without failing 

**Failure logs** 
https://github.com/mixxxdj/vcpkg/runs/2960968025?check_suite_focus=true

**Additional context**
We need the overlay to set the VCPKG_OSX_DEPLOYMENT_TARGET to 10.12 for compatibility with old devices.

**Comment by JackBoosY** [comment]
This issue cannot be reproduced by setting `VCPKG_OVERLAY_TRIPLETS` to an absolute path or a relative path.
But just in case, please make sure your vcpkg is up to date (and run bootstrap again) and set it as an absolute path and try again.

Thanks.

**Comment by JackBoosY** [comment]
@daschuer  On OSX.

**Comment by daschuer** [comment]
The issue is fixed when using an absolute path. 
See: https://github.com/daschuer/vcpkg/runs/2989211009?check_suite_focus=true

**Comment by JackBoosY** [comment]
> The issue is fixed when using an absolute path.
> See: https://github.com/daschuer/vcpkg/runs/2989211009?check_suite_focus=true

I also test the relative path and it also works. No idea why it failed on your machine.
Any way, I will update the doc.

**Comment by JackBoosY** [comment]
@vicroms Can you please take a look?

Thanks.

**Comment by daschuer** [comment]
It does not fail on my machine because I have no access to a osx device. It fails during a the GitHub workflow. 

I have the suspicion that it relates to you other overlays since you cannot confirm it locally.  
It fails when building /Users/runner/mixxx-vcpkg/overlay/osx/portmidi a osx enabled version. 
See the [portmidi] commits here: https://github.com/mixxxdj/vcpkg/pull/18/commits
Can you spot an issue? 
Do you have an idea to debug it?

**Comment by JackBoosY** [comment]
Ping @vicroms

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. This issue hasn’t been updated in four months. Please reopen this issue if this is still a problem for you.

**Comment by daschuer** [comment]
I can confirm that the issue is solved now.
