### ISSUE TITLE
openssl build failure

### ISSUE THREAD

**Issue by alejandropuig** [microsoft/vcpkg#18762]
**Host Environment**
- OS: Windows 10 64bits
- Compiler: Visual Studio 2015

**To Reproduce**
`./vcpkg install openssl`

**Failure logs** 
C:\Temp\vcpkg>.\vcpkg.exe install openssl
Computing installation plan...
The following packages will be built and installed:
    openssl[core]:x86-windows -> 1.1.1k#6
Detecting compiler hash for triplet x86-windows...
Could not locate cached archive: C:\Users\alejandrop\AppData\Local\vcpkg\archives\e5\e57d9bc9e711ae4eeea989c04c7590b40f611b955cde3e6ca0dc6204b5639dd9.zip
Starting package 1/1: openssl:x86-windows
Building package openssl[core]:x86-windows...
-- Using C:/Temp/vcpkg/downloads/openssl-1.1.1k.tar.gz
-- Cleaning sources at C:/Temp/vcpkg/buildtrees/openssl/src/openssl-1-a1ae8b796e.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Temp/vcpkg/downloads/openssl-1.1.1k.tar.gz
-- Using source at C:/Temp/vcpkg/buildtrees/openssl/src/openssl-1-a1ae8b796e.clean
-- Copying openssl release source files...
-- Copying openssl release source files... done
-- Configure x86-windows-rel
-- Configure x86-windows-rel done
-- Build x86-windows-rel
-- Build x86-windows-rel done
-- Copying openssl debug source files...
-- Copying openssl debug source files... done
-- Configure x86-windows-dbg
-- Configure x86-windows-dbg done
-- Build x86-windows-dbg
-- Build x86-windows-dbg done
CMake Error at scripts/cmake/vcpkg_copy_tool_dependencies.cmake:29 (message):
  Could not find PowerShell Core; please open an issue to report this.
Call Stack (most recent call first):
  ports/openssl/windows/portfile.cmake:154 (vcpkg_copy_tool_dependencies)
  ports/openssl/portfile.cmake:19 (include)
  scripts/ports.cmake:139 (include)

Error: Building package openssl:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openssl:x86-windows
  Vcpkg version: 2021-05-05-e8977e69d9a3fb462d9ad42013d83a7682706659

Additionally, attach any relevant sections from the log files above.

**Additional context**
Clean install of vcpkg

**Comment by NancyLi1013** [comment]
Hi @alejandropuig 

Thanks for posting this issue.

Seems duplicated of https://github.com/microsoft/vcpkg/issues/15681, let's track this issue there.
