### ISSUE TITLE
[libiconv] build failure

### ISSUE THREAD

**Issue by jfm535** [microsoft/vcpkg#18778]
**Host Environment**
- OS: Windows
- Compiler: Visual studio 2019

**To Reproduce**
`./vcpkg install libiconv:x64-windows`

**Failure logs** 
the lines seen in `build-x64-windows-dbg-out.log`
```
.././../src/1.16-de9101a181.clean/lib/relocatable.c(483): error C2065: 'D': undeclared identifier
.././../src/1.16-de9101a181.clean/lib/relocatable.c(483): error C2143: syntax error: missing ';' before ':'
```
**Additional context**
heres the offending lines in `relocatable.c`

```
      const char *orig_installprefix = INSTALLPREFIX;
      const char *orig_installdir = INSTALLDIR;
```
it seems that it doesnt like windows paths. 

I am currently trying to figure out how to apply a patch to replace `INSTALLPREFIX` and `INSTALLDIR` with an empty string in hopes of fixing it.

**Comment by jfm535** [comment]
adding these lines to the port file bypass that error
```
vcpkg_replace_string(${SOURCE_PATH}/lib/relocatable.c "= INSTALLPREFIX" "= \"\"")
vcpkg_replace_string(${SOURCE_PATH}/lib/relocatable.c "= INSTALLDIR" "= \"\"")
vcpkg_replace_string(${SOURCE_PATH}/srclib/relocatable.c "= INSTALLPREFIX" "= \"\"")
vcpkg_replace_string(${SOURCE_PATH}/srclib/relocatable.c "= INSTALLDIR" "= \"\"")
```
however it still seems to throw errors

**Comment by jfm535** [comment]
latest update it seems port version `1.16#4` works

**Comment by dg0yt** [comment]
> ~~~
> mingw32-make: *** [Makefile:34: all] Error 2
> ~~~

`mingw32-make` doesn't look right. Dou you have another installation of Cygwin or MSYS in `PATH`? 
This would also explain the trouble with INSTALLPREFIX etc. (Windows paths vs Unix paths).
(Attaching log files would provide more information.)

**Comment by jfm535** [comment]
I dont have an installation of msys or cygwin on my path as far as i know but i am attaching the log files here 
[libiconv.zip](https://github.com/microsoft/vcpkg/files/6758163/libiconv.zip)

**Comment by sfhacker** [comment]
@jfm535 Are we mixing toolchains here? If so, you are looking for trouble.
We have faced no issues at all building this port from source on Windows.

**Comment by dg0yt** [comment]
> I dont have an installation of msys or cygwin on my path as far as i know but i am attaching the log files here
> [libiconv.zip](https://github.com/microsoft/vcpkg/files/6758163/libiconv.zip)

The build log confirms that `mingw32-make` is found in the `PATH`, taken from your environment. See line 2:

>    builddir="`pwd`"; cd libcharset && C:/Users/peter/scoop/apps/gcc/current/bin/mingw32-make.exe all && C:/Users/peter/scoop/apps/gcc/current/bin/mingw32-make.exe install-lib libdir="$builddir/lib" includedir="$builddir/lib"

This indicates a mixing of toolchains which is discouraged. So you will need to somehow adjust your `PATH` now. 
However, you would certainly benefit from hardening vcpkg against picking up `mingw32-make`.

**Comment by jfm535** [comment]
I am surprised I never would have expected scoop gcc to impact the script thanks for helping me solve the issue. as for fixing my path i can just do `scoop uninstall gcc`. And yes hardening the script agenst such issues would be a good idea. Maybe compare the contents of the vcpkg bin directory agenst ones path and if the path already contains one strip it out during the build session.

**Comment by JonLiu1993** [comment]
@jfm535 ,Has this issue been solved?

**Comment by jfm535** [comment]
yes it has
