### ISSUE TITLE
What does "The file may be corrupted" error means?

### ISSUE THREAD

**Issue by brupelo** [Microsoft/vcpkg#1878]
What does it mean the below errors?

    KneDa@KNEDA-PC d:\software\vcpkg
    > vcpkg install libpng
    The following packages will be built and installed:
        libpng:x86-windows
    Starting package 1/1: libpng:x86-windows
    Building package libpng:x86-windows...
    -- CURRENT_INSTALLED_DIR=D:/software/vcpkg/installed/x86-windows
    -- DOWNLOADS=D:/software/vcpkg/downloads
    -- CURRENT_PACKAGES_DIR=D:/software/vcpkg/packages/libpng_x86-windows
    -- CURRENT_BUILDTREES_DIR=D:/software/vcpkg/buildtrees/libpng
    -- CURRENT_PORT_DIR=d:/software/vcpkg/ports/libpng/.
    -- Using cached D:/software/vcpkg/downloads/libpng-1.6.32.tar.xz
    -- Testing integrity of cached file...
    CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:47 (message):

      File does not have expected hash:

              File path: [ D:/software/vcpkg/downloads/libpng-1.6.32.tar.xz ]
          Expected hash: [ 24cf4d38dc08d1db7721fc580d8bf6cee9a105afcea32f1245b7bb3727c8a8645ad733a24534782ef5dfb0d4315a5fd6b0eee9e7f0704e0c635350f80c19a708 ]
            Actual hash: [ 3b53ccf0243cd4a6a731a898bfdba95c3d22342e7e64f9e9a4a2bce5f74ac809943f570ed92c9077101a178f82f49ece1d1c4bfee1f288ea61d99fb36f6a243e ]

      Please delete the file and retry if this file should be downloaded again.

    Call Stack (most recent call first):
      scripts/cmake/vcpkg_download_distfile.cmake:59 (test_hash)
      ports/libpng/portfile.cmake:5 (vcpkg_download_distfile)
      scripts/ports.cmake:72 (include)

    Error: Building package libpng:x86-windows failed with: BUILD_FAILED
    Please ensure you're using the latest portfiles with `.\vcpkg update`, then
    submit an issue at https://github.com/Microsoft/vcpkg/issues including:
      Package: libpng:x86-windows
      Vcpkg version: 0.0.90-2017-09-25-084b1afe9af1690916fab95bbb80c6891109f0fc

    Additionally, attach any relevant sections from the log files above.

    KneDa@KNEDA-PC d:\software\vcpkg
    > vcpkg install freetype
    The following packages will be built and installed:
        freetype:x86-windows
      * libpng:x86-windows
    Additional packages (*) will be installed to complete this operation.
    Starting package 1/2: libpng:x86-windows
    Building package libpng:x86-windows...
    -- CURRENT_INSTALLED_DIR=D:/software/vcpkg/installed/x86-windows
    -- DOWNLOADS=D:/software/vcpkg/downloads
    -- CURRENT_PACKAGES_DIR=D:/software/vcpkg/packages/libpng_x86-windows
    -- CURRENT_BUILDTREES_DIR=D:/software/vcpkg/buildtrees/libpng
    -- CURRENT_PORT_DIR=d:/software/vcpkg/ports/libpng/.
    -- Using cached D:/software/vcpkg/downloads/libpng-1.6.32.tar.xz
    -- Testing integrity of cached file...
    CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:47 (message):

      File does not have expected hash:

              File path: [ D:/software/vcpkg/downloads/libpng-1.6.32.tar.xz ]
          Expected hash: [ 24cf4d38dc08d1db7721fc580d8bf6cee9a105afcea32f1245b7bb3727c8a8645ad733a24534782ef5dfb0d4315a5fd6b0eee9e7f0704e0c635350f80c19a708 ]
            Actual hash: [ 3b53ccf0243cd4a6a731a898bfdba95c3d22342e7e64f9e9a4a2bce5f74ac809943f570ed92c9077101a178f82f49ece1d1c4bfee1f288ea61d99fb36f6a243e ]

      Please delete the file and retry if this file should be downloaded again.

    Call Stack (most recent call first):
      scripts/cmake/vcpkg_download_distfile.cmake:59 (test_hash)
      ports/libpng/portfile.cmake:5 (vcpkg_download_distfile)
      scripts/ports.cmake:72 (include)

    Error: Building package libpng:x86-windows failed with: BUILD_FAILED
    Please ensure you're using the latest portfiles with `.\vcpkg update`, then
    submit an issue at https://github.com/Microsoft/vcpkg/issues including:
      Package: libpng:x86-windows
      Vcpkg version: 0.0.90-2017-09-25-084b1afe9af1690916fab95bbb80c6891109f0fc

    Additionally, attach any relevant sections from the log files above.

    KneDa@KNEDA-PC d:\software\vcpkg
    > vcpkg install freeimage
    The following packages will be built and installed:
        freeimage:x86-windows
      * ilmbase:x86-windows
      * jasper:x86-windows
      * jxrlib:x86-windows
      * lcms:x86-windows
      * liblzma:x86-windows
      * libpng:x86-windows
      * libraw:x86-windows
      * libwebp:x86-windows
      * openexr:x86-windows
      * openjpeg:x86-windows
      * tiff:x86-windows
    Additional packages (*) will be installed to complete this operation.
    Starting package 1/12: libpng:x86-windows
    Building package libpng:x86-windows...
    -- CURRENT_INSTALLED_DIR=D:/software/vcpkg/installed/x86-windows
    -- DOWNLOADS=D:/software/vcpkg/downloads
    -- CURRENT_PACKAGES_DIR=D:/software/vcpkg/packages/libpng_x86-windows
    -- CURRENT_BUILDTREES_DIR=D:/software/vcpkg/buildtrees/libpng
    -- CURRENT_PORT_DIR=d:/software/vcpkg/ports/libpng/.
    -- Using cached D:/software/vcpkg/downloads/libpng-1.6.32.tar.xz
    -- Testing integrity of cached file...
    CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:47 (message):

      File does not have expected hash:

              File path: [ D:/software/vcpkg/downloads/libpng-1.6.32.tar.xz ]
          Expected hash: [ 24cf4d38dc08d1db7721fc580d8bf6cee9a105afcea32f1245b7bb3727c8a8645ad733a24534782ef5dfb0d4315a5fd6b0eee9e7f0704e0c635350f80c19a708 ]
            Actual hash: [ 3b53ccf0243cd4a6a731a898bfdba95c3d22342e7e64f9e9a4a2bce5f74ac809943f570ed92c9077101a178f82f49ece1d1c4bfee1f288ea61d99fb36f6a243e ]

      Please delete the file and retry if this file should be downloaded again.

    Call Stack (most recent call first):
      scripts/cmake/vcpkg_download_distfile.cmake:59 (test_hash)
      ports/libpng/portfile.cmake:5 (vcpkg_download_distfile)
      scripts/ports.cmake:72 (include)

    Error: Building package libpng:x86-windows failed with: BUILD_FAILED
    Please ensure you're using the latest portfiles with `.\vcpkg update`, then
    submit an issue at https://github.com/Microsoft/vcpkg/issues including:
      Package: libpng:x86-windows
      Vcpkg version: 0.0.90-2017-09-25-084b1afe9af1690916fab95bbb80c6891109f0fc

    Additionally, attach any relevant sections from the log files above.
                                       
    Additionally, attach any relevant sections from the log files above.
    KneDa@KNEDA-PC d:\software\vcpkg
    > vcpkg install rapidxml
    The following packages will be built and installed:
        rapidxml:x86-windows
    Starting package 1/1: rapidxml:x86-windows
    Building package rapidxml:x86-windows...
    -- CURRENT_INSTALLED_DIR=D:/software/vcpkg/installed/x86-windows
    -- DOWNLOADS=D:/software/vcpkg/downloads
    -- CURRENT_PACKAGES_DIR=D:/software/vcpkg/packages/rapidxml_x86-windows
    -- CURRENT_BUILDTREES_DIR=D:/software/vcpkg/buildtrees/rapidxml
    -- CURRENT_PORT_DIR=d:/software/vcpkg/ports/rapidxml/.
    -- Downloading https://sourceforge.net/projects/rapidxml/files/rapidxml/rapidxml%201.13/rapidxml-1.13.zip/download...
    -- Downloading https://sourceforge.net/projects/rapidxml/files/rapidxml/rapidxml%201.13/rapidxml-1.13.zip/download... OK
    -- Testing integrity of downloaded file...
    CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:47 (message):

      File does not have expected hash:

              File path: [ D:/software/vcpkg/downloads/rapidxml-1.13.zip ]
          Expected hash: [ 6c10583e6631ccdb0217d0a5381172cb4c1046226de6ef1acf398d85e81d145228e14c3016aefcd7b70a1db8631505b048d8b4f5d4b0dbf1811d2482eefdd265 ]
            Actual hash: [ 3b53ccf0243cd4a6a731a898bfdba95c3d22342e7e64f9e9a4a2bce5f74ac809943f570ed92c9077101a178f82f49ece1d1c4bfee1f288ea61d99fb36f6a243e ]

      The file may be corrupted.

    Call Stack (most recent call first):
      scripts/cmake/vcpkg_download_distfile.cmake:87 (test_hash)
      ports/rapidxml/portfile.cmake:4 (vcpkg_download_distfile)
      scripts/ports.cmake:72 (include)

    Error: Building package rapidxml:x86-windows failed with: BUILD_FAILED
    Please ensure you're using the latest portfiles with `.\vcpkg update`, then
    submit an issue at https://github.com/Microsoft/vcpkg/issues including:
      Package: rapidxml:x86-windows
      Vcpkg version: 0.0.90-2017-09-25-084b1afe9af1690916fab95bbb80c6891109f0fc

    Additionally, attach any relevant sections from the log files above.
                                                                                   
This is happening after upgraded from 0.0.81 to 0.0.9:

    git pull
    .\bootstrap-vcpkg.bat
    vcpkg update

And then just trying to upgrade all my packages.

As you can see, the above commands are trying unsuccesfully to install libpng, freetype, freeimage, glew and rapidxml

In any case, what does it mean these type of errors? I've tried cleaning the downloads folder and running vcpkg again but it didn't make any difference.

Hope you can advice.
Thanks in advance

**Comment by brupelo** [comment]
Oh, I've checked manually what vcpkg has tried to download and it seems Sourceforge is in "static offline mode", that's why the downloaded package `https://sourceforge.net/projects/glew/files/glew/2.1.0/glew-2.1.0.tgz` was 1kb out of wget request. Alright, I think I understand the logic here, no black magic involved :)

Btw, do you know any command line to calculate the hash used by vcpkg? I've tried cygwin's md5sum but it's not reporting that type of hashes. It'd be helpful to have these type of tools in case I try to download manually the src package files of the libraries.

**Comment by treigilbert** [comment]
To get the hash, I just run vcpkg install and let it fail. In the error message it lists the "Actual hash:" that vcpkg calculated. Plug that hash into the portfile.cmake SHA512 and it should pass the hash check. All the standard warnings about you are now bypassing the hash security check on your download and assuming the download has not been altered from the original.

**Comment by KindDragon** [comment]
Sourceforge is down. You can get 2.1.0 from https://github.com/nigels-com/glew/releases

**Comment by JackBoosY** [comment]
Hi @brupelo , thanks for reporting this issue!
Please open a new issue if this is still a problem for you.
Thx.
