### ISSUE TITLE
[New Port Request] ifcOpenShell

### ISSUE THREAD

**Issue by kipodon** [microsoft/vcpkg#18797]
Library name:
ifcOpenShell
Library description:
software library that helps users and software developers to work with the IFC file format.  The IFC file format can be used to describe building and construction data. The format is commonly used for Building Information Modelling.
Source repository URL:
https://github.com/IfcOpenShell/IfcOpenShell
Project homepage (if different from the source repository):
http://ifcopenshell.org/
Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
