### ISSUE TITLE
[mongo-c-driver:x64-windows-static-md] build failure

### ISSUE THREAD

**Issue by jsnhsu** [microsoft/vcpkg#18798]
**Host Environment**
- OS: Windows 10
- Compiler: VC 16.4

**To Reproduce**
`./vcpkg upgrade --no-dry-run`

**Failure logs** 
Starting package 40/44: mongo-c-driver:x64-windows-static-md
Building package mongo-c-driver[core]:x64-windows-static-md...
-- Using community triplet x64-windows-static-md. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: D:\CppTool\vcpkg\triplets\community\x64-windows-static-md.cmake
-- Using D:/CppTool/vcpkg/downloads/mongodb-mongo-c-driver-99d422877c5b5ea52006c13ee3b48297251b2b2d.tar.gz
-- Extracting source D:/CppTool/vcpkg/downloads/mongodb-mongo-c-driver-99d422877c5b5ea52006c13ee3b48297251b2b2d.tar.gz
-- Applying patch fix-dependency-libbson.patch
-- Applying patch disable-static-when-dynamic-build.patch
-- Applying patch fix-arm-build.patch
-- Using source at D:/CppTool/vcpkg/buildtrees/mongo-c-driver/src/97251b2b2d-f5c6ef32ce.clean
CMake Deprecation Warning at scripts/cmake/vcpkg_check_features.cmake:182 (message):
  calling `vcpkg_check_features` without the `FEATURES` keyword has been
  deprecated.

      Please add the `FEATURES` keyword to the call.
Call Stack (most recent call first):
  ports/mongo-c-driver/portfile.cmake:14 (vcpkg_check_features)
  scripts/ports.cmake:139 (include)

-- Found external ninja('1.10.2').
-- Configuring x64-windows-static-md
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
    Command failed: ninja -v
    Working Directory: D:/CppTool/vcpkg/buildtrees/mongo-c-driver/x64-windows-static-md-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\CppTool\vcpkg\buildtrees\mongo-c-driver\config-x64-windows-static-md-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:324 (vcpkg_execute_required_process)
  ports/mongo-c-driver/portfile.cmake:45 (vcpkg_configure_cmake)
  scripts/ports.cmake:139 (include)

Error: Building package mongo-c-driver:x64-windows-static-md failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: mongo-c-driver:x64-windows-static-md
  Vcpkg version: 2021-05-05-e8977e69d9a3fb462d9ad42013d83a7682706659

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by FrankXie05** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
