### ISSUE TITLE
TripletCMakeVarProvider::launch_and_split crash due to incorrect iterator usage

### ISSUE THREAD

**Issue by JustasMasiulis** [microsoft/vcpkg#18806]
**Describe the bug**
Crash.

**Environment**
- OS: Windows 11

**To Reproduce**
1. Have whole OS messed up and nothing working
2. ./vcpkg install any_library

**Expected behavior**
Doesn't crash.

**Additional context**
https://github.com/microsoft/vcpkg-tool/blob/f9a044cb139423024cd7c667222d3561a45767eb/src/vcpkg/cmakevars.cpp#L196

When `block_start` is equal to `port_end` because no new start was found, it will be incremented and cause a crash.

**Comment by JustasMasiulis** [comment]
Seems to be duplicate of https://github.com/microsoft/vcpkg/issues/18636 - downgrading cmake worked as a fix.

Tried it with a quick fix applied, which stops it from crashing:

```cpp
if (block_start != port_end) ++block_start;
auto block_end = std::find(block_start, port_end, BLOCK_END_GUID);
```
However it just errors out with `Invalid architecture string: ` where the string is empty.

**Comment by NancyLi1013** [comment]
@BillyONeal 

Could you please help take a look? 

Thanks.

**Comment by LilyWangLL** [comment]
Ping @BillyONeal, could you please take a look this issue? Thanks in advance.

**Comment by LilyWangLL** [comment]
This issue has been fixed in PR https://github.com/microsoft/vcpkg-tool/pull/107, so I am closing this issue for now.
