### ISSUE TITLE
[libsigcpp-3] build failure

### ISSUE THREAD

**Issue by MrAviator93** [microsoft/vcpkg#18808]
**Host Environment**
- OS: Windows
- Compiler: Visual Studio 2019

**To Reproduce**
```
1. .\vcpkg.exe install libsigcpp-3:x64-windows-static
2. mkdir build
3. cd build
4. cmake ..\
5. Run Test.sln generated using Visual Studio 2019
6. Choose either Debug x64 or Release x64 mode, both of them will generate the same result.
```

CMakeLists.txt file used
```
cmake_minimum_required( VERSION "3.20.0" )

project( Test VERSION 1.0 LANGUAGES CXX )

if ( WIN32 )
    add_compile_definitions( _WIN32_WINNT=0x0A00 )
    set( VCPKG_TARGET_TRIPLET "x64-windows-static" CACHE STRING "We are building for x64 platform static libraries." )
    include( "C:/VCPCKG/vcpkg/scripts/buildsystems/vcpkg.cmake" )
endif()

set( CMAKE_CXX_STANDARD 17 )
set( CMAKE_CXX_STANDARD_REQUIRED TRUE )

if( MSVC )
    add_compile_options(
        $<$<CONFIG:>:/MT> #---------|
        $<$<CONFIG:Debug>:/MTd> #---|-- Statically link the runtime libraries
        $<$<CONFIG:Release>:/MT> #--|
    )
endif()

find_package( sigc++-3 CONFIG REQUIRED )
message( STATUS "libsigc++ is in ${sigc++-3_INCLUDE_DIRS}")
include_directories( ${sigc++-3_INCLUDE_DIRS} )


set( EXECUTABLE_NAME test )

add_executable( ${EXECUTABLE_NAME}
    main.cpp
)

target_include_directories( ${EXECUTABLE_NAME}
    PRIVATE
    $<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/Code/Source>
    # ${libsigc++_INCLUDE_DIRS}
)

target_link_libraries( ${EXECUTABLE_NAME}
    sigc-3.0
)

```

main.cpp
```
#include <sigc++/signal.h>

#include <iostream>


int main()
{
    sigc::signal< void() > test;
    test.connect( [] { std::cout << "Test Signal Called" << std::endl; } );
    test();
    return 0;
}

```

**Failure logs** 
1>------ Build started: Project: test, Configuration: Release x64 ------
1>main.cpp
1>LINK : warning LNK4217: symbol '??1slot_rep@internal@sigc@@UEAA@XZ (public: virtual __cdecl sigc::internal::slot_rep::~slot_rep(void))' defined in 'sigc-3.0.lib(slot_base.obj)' is imported by 'main.obj' in function '"public: virtual __cdecl sigc::internal::typed_slot_rep<class <lambda_a7602b47bb1fd6537891f809b4745f1b> >::~typed_slot_rep<class <lambda_a7602b47bb1fd6537891f809b4745f1b> >(void)" (??1?$typed_slot_rep@V<lambda_a7602b47bb1fd6537891f809b4745f1b>@@@internal@sigc@@UEAA@XZ)'
1>LINK : warning LNK4217: symbol '??0slot_base@sigc@@QEAA@XZ (public: __cdecl sigc::slot_base::slot_base(void))' defined in 'sigc-3.0.lib(slot_base.obj)' is imported by 'main.obj' in function 'main'
1>LINK : warning LNK4217: symbol '??0slot_base@sigc@@QEAA@PEAUslot_rep@internal@1@@Z (public: __cdecl sigc::slot_base::slot_base(struct sigc::internal::slot_rep *))' defined in 'sigc-3.0.lib(slot_base.obj)' is imported by 'main.obj' in function 'main'
1>LINK : warning LNK4217: symbol '??0slot_base@sigc@@QEAA@$$QEAV01@@Z (public: __cdecl sigc::slot_base::slot_base(class sigc::slot_base &&))' defined in 'sigc-3.0.lib(slot_base.obj)' is imported by 'main.obj' in function 'main'
1>LINK : warning LNK4217: symbol '??1slot_base@sigc@@QEAA@XZ (public: __cdecl sigc::slot_base::~slot_base(void))' defined in 'sigc-3.0.lib(slot_base.obj)' is imported by 'main.obj' in function '"public: __cdecl sigc::slot<void __cdecl(void)>::~slot<void __cdecl(void)>(void)" (??1?$slot@$$A6AXXZ$$V@sigc@@QEAA@XZ)'
1>main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl sigc::internal::slot_rep::slot_rep(void * (__cdecl*)(void *))" (__imp_??0slot_rep@internal@sigc@@QEAA@P6APEAXPEAX@Z@Z) referenced in function "private: virtual struct sigc::internal::slot_rep * __cdecl sigc::internal::typed_slot_rep<class <lambda_a7602b47bb1fd6537891f809b4745f1b> >::clone(void)const " (?clone@?$typed_slot_rep@V<lambda_a7602b47bb1fd6537891f809b4745f1b>@@@internal@sigc@@EEBAPEAUslot_rep@23@XZ)
1>main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl sigc::internal::slot_do_bind::slot_do_bind(struct sigc::internal::slot_rep *)" (__imp_??0slot_do_bind@internal@sigc@@QEAA@PEAUslot_rep@12@@Z) referenced in function "private: virtual struct sigc::internal::slot_rep * __cdecl sigc::internal::typed_slot_rep<class <lambda_a7602b47bb1fd6537891f809b4745f1b> >::clone(void)const " (?clone@?$typed_slot_rep@V<lambda_a7602b47bb1fd6537891f809b4745f1b>@@@internal@sigc@@EEBAPEAUslot_rep@23@XZ)
1>main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl sigc::internal::slot_do_unbind::slot_do_unbind(struct sigc::internal::slot_rep *)" (__imp_??0slot_do_unbind@internal@sigc@@QEAA@PEAUslot_rep@12@@Z) referenced in function "public: virtual __cdecl sigc::internal::typed_slot_rep<class <lambda_a7602b47bb1fd6537891f809b4745f1b> >::~typed_slot_rep<class <lambda_a7602b47bb1fd6537891f809b4745f1b> >(void)" (??1?$typed_slot_rep@V<lambda_a7602b47bb1fd6537891f809b4745f1b>@@@internal@sigc@@UEAA@XZ)
1>main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: bool __cdecl sigc::slot_base::empty(void)const " (__imp_?empty@slot_base@sigc@@QEBA_NXZ) referenced in function main
1>main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: bool __cdecl sigc::slot_base::blocked(void)const " (__imp_?blocked@slot_base@sigc@@QEBA_NXZ) referenced in function main
1>main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl sigc::connection::connection(class sigc::slot_base &)" (__imp_??0connection@sigc@@QEAA@AEAVslot_base@1@@Z) referenced in function main
1>main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl sigc::connection::~connection(void)" (__imp_??1connection@sigc@@QEAA@XZ) referenced in function main
1>main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl sigc::internal::signal_impl_holder::signal_impl_holder(class std::shared_ptr<struct sigc::internal::signal_impl> const &)" (__imp_??0signal_impl_holder@internal@sigc@@QEAA@AEBV?$shared_ptr@Usignal_impl@internal@sigc@@@std@@@Z) referenced in function main
1>main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl sigc::internal::signal_impl_holder::~signal_impl_holder(void)" (__imp_??1signal_impl_holder@internal@sigc@@QEAA@XZ) referenced in function main
1>main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl sigc::signal_base::signal_base(void)" (__imp_??0signal_base@sigc@@QEAA@XZ) referenced in function main
1>main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl sigc::signal_base::~signal_base(void)" (__imp_??1signal_base@sigc@@QEAA@XZ) referenced in function "public: __cdecl sigc::signal<void __cdecl(void)>::~signal<void __cdecl(void)>(void)" (??1?$signal@$$A6AXXZ$$V@sigc@@QEAA@XZ)
1>main.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) protected: class std::_List_iterator<class std::_List_val<struct std::_List_simple_types<class sigc::slot_base> > > __cdecl sigc::signal_base::connect(class sigc::slot_base &&)" (__imp_?connect@signal_base@sigc@@IEAA?AV?$_List_iterator@V?$_List_val@U?$_List_simple_types@Vslot_base@sigc@@@std@@@std@@@std@@$$QEAVslot_base@2@@Z) referenced in function main
1>main.obj : error LNK2001: unresolved external symbol "public: __cdecl sigc::internal::signal_impl_holder::~signal_impl_holder(void)" (??1signal_impl_holder@internal@sigc@@QEAA@XZ)
1>C:\Users\Artur\Desktop\va_dynamics\Repos\test\build\Release\test.exe : fatal error LNK1120: 13 unresolved externals
1>Done building project "test.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========

**Additional context**
I believe it's something to do with the configuration of sigc, it seems that it doesn't even exist.

**Comment by MrAviator93** [comment]
Was just curious to ask, if you have looked at it in more detail, maybe could provide some tips?

**Comment by NancyLi1013** [comment]
I will look into this issue soon.

**Comment by NancyLi1013** [comment]
@MrAviator93 
I submitted a PR #18944 to fix this issue. Could you please help test if this PR can work fine for you?

**Comment by MrAviator93** [comment]
You are right, if I remove #define SIGC_DLL 1 then for static build it builds and works just fine.
So as I understand the fix will be merged now in master and it will be possible to pull the fixed one?
