### ISSUE TITLE
MSBuild integration broken

### ISSUE THREAD

**Issue by autoantwort** [microsoft/vcpkg#18805]
I am using the msbuild integration and have updated to the latest master, but now I am getting the following error when I try to build the project:
```
Error MSB3371
The file "F:\src2\vcpkg\scripts\buildsystems\msbuild\..\..\..\installed\.msbuildstamp-x86-windows..stamp" cannot be created. Could not find a part of the path 'F:\src2\vcpkg\installed\.msbuildstamp-x86-windows..stamp'.
From
F:\src2\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets:110
```

PS: I am using your workaround for different installed dirs from #16083

**Comment by JackBoosY** [comment]
@vicroms Can you please take a look?

Thanks.

**Comment by JackBoosY** [comment]
https://github.com/microsoft/vcpkg/blob/b361c2eefa3966cb7cec45275aff32e90430aaa6/scripts/buildsystems/msbuild/vcpkg.targets#L110

https://github.com/microsoft/vcpkg/blob/b361c2eefa3966cb7cec45275aff32e90430aaa6/scripts/buildsystems/msbuild/vcpkg.targets#L81

`VcpkgInstalledDir` and (`VcpkgTriplet` or `VcpkgHostTriplet`) is empty.

**Comment by JackBoosY** [comment]
Can you please provide your Visual Studio version and install location?

Thanks.

**Comment by autoantwort** [comment]
I am using Visual Studio 2015 installed at `C:\Program Files (x86)\Microsoft Visual Studio 14.0` (should be the default location)

**Comment by PhoebeHui** [comment]
@autoantwort, could you provide us the repro steps, I didn't repro this issue with VS2015 update3 with latest vcpkg, do you have custom settings?

**Comment by autoantwort** [comment]
I have updated my bug report repo: https://github.com/autoantwort/VcpkgBug/tree/vcpkg_bug_18805 :D 
1. `git clone --recurse-submodules https://github.com/autoantwort/VcpkgBug.git`
2. `git checkout vcpkg_bug_18805`
3. bootstrap stuff + integrate install
4. build the project

It maybe worked for you because you have an existing folder at `$(VcpkgRoot)/installed`. Delete that folder and try again, then it should fail

**Comment by strega-nil-ms** [comment]
@autoantwort does my branch solve your problem? <https://github.com/strega-nil/vcpkg/tree/vcpkg-msbuild-no-installed-dir>

**Comment by autoantwort** [comment]
I still getting the same error

**Comment by autoantwort** [comment]
Fixed
