### ISSUE TITLE
[vcpkg tool] udpate to latest release

### ISSUE THREAD

**Issue by PhoebeHui** [microsoft/vcpkg#18815]
See https://github.com/microsoft/vcpkg/issues/14766#issuecomment-873311876

> @PhoebeHui VCPKG uses strawberry-perl 5.30.0.1, why wasn't it updated to strawberry-perl 5.32.1.1?
> Few others behind in revisions too like nuget 5.5.1 VS 5.10.0 etc.

**Comment by xavier2k6** [comment]
@PhoebeHui see also https://github.com/microsoft/vcpkg/issues/14766#issuecomment-874239368
