### ISSUE TITLE
boost 1_65_1.7z hash error building cpprestsdk

### ISSUE THREAD

**Issue by bc1275** [Microsoft/vcpkg#1881]
Building the latest CPPRest fails on the boost 1.65.1 downloaded file.

PS C:\Dev\vcpkg> .\vcpkg install cpprestsdk cpprestsdk:x64-windows
The following packages will be built and installed:
  * boost:x86-windows
  * boost:x64-windows
  * bzip2:x64-windows
    cpprestsdk:x86-windows
    cpprestsdk:x64-windows
  * openssl:x64-windows
  * websocketpp:x86-windows
  * websocketpp:x64-windows
  * zlib:x64-windows
Additional packages (*) will be installed to complete this operation.
Starting package 1/9: boost:x86-windows
Building package boost:x86-windows...
-- CURRENT_INSTALLED_DIR=C:/Dev/vcpkg/installed/x86-windows
-- DOWNLOADS=C:/Dev/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/Dev/vcpkg/packages/boost_x86-windows
-- CURRENT_BUILDTREES_DIR=C:/Dev/vcpkg/buildtrees/boost
-- CURRENT_PORT_DIR=C:/Dev/vcpkg/ports/boost/.
-- Downloading https://sourceforge.net/projects/boost/files/boost/1.65.1/boost_1_65_1.7z...
-- Downloading https://sourceforge.net/projects/boost/files/boost/1.65.1/boost_1_65_1.7z... OK
-- Testing integrity of downloaded file...
CMake Error at C:/Dev/vcpkg/scripts/cmake/vcpkg_download_distfile.cmake:47 (message):

  File does not have expected hash:

          File path: [ C:/Dev/vcpkg/downloads/boost_1_65_1.7z ]
      Expected hash: [ b1d9264ec74dd75c68176f5a2d2da33a2c1e3162842cc61a07ac8ed1ebb953855cece4faf72ce99b490b665e813b839e35c7fc8026f2f9cb31b106fb8bab2a9c ]
        Actual hash: [ 3b53ccf0243cd4a6a731a898bfdba95c3d22342e7e64f9e9a4a2bce5f74ac809943f570ed92c9077101a178f82f49ece1d1c4bfee1f288ea61d99fb36f6a243e ]

  The file may be corrupted.

Call Stack (most recent call first):
  C:/Dev/vcpkg/scripts/cmake/vcpkg_download_distfile.cmake:87 (test_hash)
  C:/Dev/vcpkg/ports/boost/portfile.cmake:10 (vcpkg_download_distfile)
  C:/Dev/vcpkg/scripts/ports.cmake:72 (include)

Error: Building package boost:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost:x86-windows
  Vcpkg version: 0.0.90-2017-09-25-084b1afe9af1690916fab95bbb80c6891109f0fc

Additionally, attach any relevant sections from the log files above.

**Comment by atkawa7** [comment]
@bc1275 sourceforge not working

**Comment by kwach** [comment]
```
-- Downloading https://sourceforge.net/projects/boost/files/boost/1.65.1/boost_1_65_1.7z...
-- Downloading https://sourceforge.net/projects/boost/files/boost/1.65.1/boost_1_65_1.7z... OK
```

It doesen't compile but file id downloaded Ok.

```
-- Building x86-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process_repeat.cmake:21 (message):
    Command failed: C:/workspace/vcpkg/buildtrees/boost/src/boost_1_65_1/b2.exe;--stagedir=C:/workspace/vcpkg/buildtrees
/boost/x86-windows-rel/stage;--build-dir=C:/workspace/vcpkg/buildtrees/boost/x86-windows-rel;-sZLIB_INCLUDE="C:/workspac
e/vcpkg/installed/x86-windows\include";-sBZIP2_INCLUDE="C:/workspace/vcpkg/installed/x86-windows\include";-sICU_PATH="C:
/workspace/vcpkg/installed/x86-windows";-j4;--debug-configuration;--hash;-q;threading=multi;runtime-link=shared;link=sha
red;--without-python;boost.locale.icu=off;--disable-icu;toolset=msvc-14.1;-sZLIB_BINARY=zlib;-sZLIB_LIBPATH="C:/workspac
e/vcpkg/installed/x86-windows\lib";-sBZIP2_BINARY=bz2;-sBZIP2_LIBPATH="C:/workspace/vcpkg/installed/x86-windows\lib";var
iant=release;debug-symbols=on
```

**Comment by JackBoosY** [comment]
Hi @bc1275 , thanks for reporting this issue!
Please open a new issue if this is still a problem for you.
Thx.
