### ISSUE TITLE
How do I integrate vcpkg to my project in github actions

### ISSUE THREAD

**Issue by xarthurx** [microsoft/vcpkg#18821]
Please see the detailed scenario here:
https://github.com/actions/virtual-environments/issues/3689

Simply put, I'm trying to use `vcpkg` in a github action to compile my library.
However, whatever works locally does not work on the github virtual machine.

It seems that using `msbuild` to build my lib on the virtual machine does not recognize `vcpkg` library location even I run 

`vcpkg integrate install`

Any clue what is the problem?
May it be that my `.sln` file is generated on my local machine and only point to a `vcpkg` location defined locally?
Is it that the `vcpkg` library location is not defined by global environmental variable?

Thanks.

**Comment by JackBoosY** [comment]
I suggest @BillyONeal to have a reply for this issue.

**Comment by BillyONeal** [comment]
`integrate install` relies on a feature in the public msbuild targets that go through `%APPDATA%` which might not work from a service account (as Actions is likely to be using). I think we might need a feature that works without such global integration to enable this scenario....
