### ISSUE TITLE
[glibmm]glibmmconfig.h missing

### ISSUE THREAD

**Issue by yonaka** [microsoft/vcpkg#18824]
**Describe the bug**
glibmmconfig.h is missing.

**Environment**
- OS: Windows 10 20H2
- Compiler: Visual Studio 2019 16.10.3

**To Reproduce**

1. ./vcpkg install cairo cairomm pango pangomm

1. Set External Include Directory project setting to `$(VCPkgRoot)\installed\$(LibrariesArchitecture)-windows\include\sigc++-3.0;$(VCPkgRoot)\installed\$(LibrariesArchitecture)-windows\include\giomm-2.68;$(VCPkgRoot)\installed\$(LibrariesArchitecture)-windows\include\glibmm-2.68;$(VCPkgRoot)\installed\$(LibrariesArchitecture)-windows\include\cairomm-1.16;$(VCPkgRoot)\installed\$(LibrariesArchitecture)-windows\include\pangomm-2.48;$(ExternalIncludePath)`

1. Compile the code below.
`#include <glibmm.h>`

**Expected behavior**
No error.

**Failure logs** 
`C:\work\Project\vcpkg\installed\x64-windows\include\glibmm-2.68\glibmm.h(96,10): fatal error C1083: include ファイルを開けません。'glibmmconfig.h':No such file or directory`

**Additional context**
`#include <pangomm.h>` emits the same error.
See #18760 for the External Include Directory project setting above.

**Comment by NancyLi1013** [comment]
Hi @yonaka 

Thanks for posting this issue.

Currently, `glibmmconfig.h` was installed in _../lib/glibmm-2.68/include_ directory. It should be in _include_ directory.

**Comment by Neumann-A** [comment]
> Currently, glibmmconfig.h was installed in ../lib/glibmm-2.68/include directory. It should be in include directory.

Upstream installs it there since it is an architecture (and maybe build type) dependent configuration file. This is simply a problem using the MSBuild integration. CMake and Meson don't have that issue since they will add the necessary include via the pc file.

**Comment by NancyLi1013** [comment]
Thanks for your information. @Neumann-A 

Do you have any suggestions to MSBuild project? This should also exist in other ports, such as `glib`, `graphene`. As you said, it is upstream behavior. But how should we solve the problem using MSBuild?
