### ISSUE TITLE
[New Port Request] Imguizmo

### ISSUE THREAD

**Issue by enricogolfieri** [microsoft/vcpkg#18823]
Library name:
Imguizmo

Library description:
ImGizmo is a small (.h and .cpp) library built ontop of Dear ImGui that allow you to manipulate(Rotate & translate at the moment) 4x4 float matrices. No other dependancies. Coded with Immediate Mode (IM) philosophy in mind.

Source repository URL:
https://github.com/CedricGuillemet/ImGuizmo

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by mathisloge** [comment]
@JonLiu1993 this could be closed https://github.com/microsoft/vcpkg/pull/18991

**Comment by JonLiu1993** [comment]
> @JonLiu1993 this could be closed #18991

Thanks for your reminder.
