### ISSUE TITLE
Urho3D SDL Problem

### ISSUE THREAD

**Issue by tijon1** [microsoft/vcpkg#18833]
**Describe the bug**
This issue doesn't allow me to use Urho3D. 

**Environment**
- OS: Windows 10 
- Compiler: VS 2022 

**To Reproduce**
Download Visual Studio (2022, haven't tried using Urho3D on other versions of VS)
2.Install the Urho3D package via Vcpkg via "vcpkg install urho3d"
3.Create a empty project in VS
4.Use the application framework in the link below (no modifications)
https://urho3d.io/documentation/1.7.1/_main_loop.html
5.Build the solution/project

**Expected behavior**
I expected the project to compile and work without any errors

**Failure logs** 
`
E1696	cannot open source file "SDL/SDL_joystick.h"
E1696	cannot open source file "SDL/SDL_gamecontroller.h"
E1696	cannot open source file "SDL/SDL_keycode.h"	
E1696	cannot open source file "SDL/SDL_mouse.h"
C1083	Cannot open include file: 'SDL/SDL_joystick.h'
`

``
Build started...

1>------ Build started: Project: GeometryTest, Configuration: Debug Win32 ------

1>MyApp.cpp

1>C:\Users\??????\vcpkg\installed\x86-windows\include\Urho3D\Input\InputConstants.h(30,10): fatal error C1083: Cannot open include file: 'SDL/SDL_joystick.h': No such file or directory

1>Done building project "GeometryTest.vcxproj" -- FAILED.

========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
``

**Additional context**
I tried....
- reinstalling urho3D
- installing sdl1 and sdl2

**Comment by tijon1** [comment]
Turns out Urho3D use their own fork of SDL. It's located at [https://github.com/urho3d/SDL-mirror](https://github.com/urho3d/SDL-mirror). 
I also tried adding the changes from the #18880 pull request to my Vcpkg and it didn't help at all. 
Same errors when compiling the same project.

**Comment by NancyLi1013** [comment]
Thanks for your feedback. Yes, `Urho3D` use the embedded `SDL`. For me the changes can work on my machine. But it seems to be not reasonable. I will try to fix it in another way.

**Comment by koprok** [comment]
Hi all,
I am the creator of the Urho3D package in Vcpkg and I am currently happily using it. I have described how to use it here:
https://github.com/urho3d/Urho3D/issues/2810#issuecomment-881356375
I hope this helps.

**Comment by JackBoosY** [comment]
Please don't close this issue until I fixed it.
