### ISSUE TITLE
Port request: Abseil (Google's common library)

### ISSUE THREAD

**Issue by arthur-tacca** [Microsoft/vcpkg#1883]
Google has just released a library with some of their low-level code such as time, string handling, and their mutex class. There are plans to add logging and command-line flag infrastructure.

* Announcement: https://opensource.googleblog.com/2017/09/introducing-abseil-new-common-libraries.html
* Library docs: https://abseil.io/
* Library code: https://github.com/abseil/abseil-cpp

This is a pre-emptive request, because the library has just been released so it is not a dependency of any public project (or probably of any private project). But the announcement mentions that this library already existed privately inside Google, and bits of it are currently copy-and-pasted into protobuf and gRPC (already in vcpkg) and TensorFlow (#466), and this will change to a proper dependency over time. So sooner or later it will need to be included if these other packages are (still) to be.

**Comment by KindDragon** [comment]
Bazel doesn't work for me on Windows

**Comment by KindDragon** [comment]
> But the announcement mentions that this library already existed privately inside Google

They will add for them CMake

**Comment by arthur-tacca** [comment]
I wasn't sure what that comment meant at first, but I think you're saying that Google is going to have to add CMake support to Abseil so that it can be used by these other projects. The implication being that there's no point vcpkg adding it now when official support will come anyway before it's really needed here. If that is what you meant, I agree.

**Comment by KindDragon** [comment]
Yes, you said it right

**Comment by ras0219-msft** [comment]
Totally experimental; don't take a dependency; etc etc:

I've written a replacement buildsystem for abseil in CMake available in master (9f9b4bc5). It also installs targets (subject to change in the future according to what Google does for their official cmake buildsystem):
```cmake
  find_package(unofficial-abseil REQUIRED)
  link_libraries(unofficial::abseil::strings unofficial::abseil::base)
```

**Comment by atkawa7** [comment]
@ras0219-msft **out of topic** Are you guys at cppcon?

**Comment by ras0219-msft** [comment]
Yep, I gave a talk on vcpkg on Tuesday and I'll be at the Microsoft booth all week if anyone wants to drop by!

**Comment by atkawa7** [comment]
@ras0219-msft  I am not. But would love to hear about the talks. Hopeful they are going to release some videos soon

**Comment by KindDragon** [comment]
https://github.com/abseil/abseil-cpp/pull/8

**Comment by gennadiycivil** [comment]
Bazel is a build sytstem for [Abseil](github.com/abseil/abseil-cpp). 
If anyone experiences Bazel problems on any platform (windows should work by the way ) please open issues and we shall see what we can do to address. 
NOTE: Abseil team will still primarily support bazel, but we'll do our best to keep CMake working too once [CMake support ](https://github.com/abseil/abseil-cpp/pull/8) lands.

**Comment by KindDragon** [comment]
I can't even run `bazel` on Windows https://github.com/bazelbuild/bazel/issues/3821

**Comment by atkawa7** [comment]
@KindDragon Bazel fails on windows most of the time. I don't think it is  as stable as they assume it to be

**Comment by atkawa7** [comment]
@ras0219-msft Please close
