### ISSUE TITLE
[bzip2[core]] build failure

### ISSUE THREAD

**Issue by rkcarroll** [microsoft/vcpkg#18834]
**Host Environment**
- OS: Windows 10
- Compiler: VS2019, v16.10.3

**To Reproduce**
`./vcpkg upgrade --no-dry-run` (bzip2, or some package dependent on bzip2, previously installed)

**Failure logs** 
-Starting package 11/14: bzip2:x64-windows
Building package bzip2[core]:x64-windows...
-- Downloading https://sourceware.org/pub/bzip2/bzip2-1.0.8.tar.gz -> bzip2-1.0.8.tar.gz...
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' = off
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] BuiltinRegistry initialized with: ""
[DEBUG] Using vcpkg-root: E:\Libs\vcpkg
[DEBUG] Using installed-root: E:\Libs\vcpkg\installed
[DEBUG] BuiltinRegistry initialized with: ""
[DEBUG] Using buildtrees-root: E:\Libs\vcpkg\buildtrees
[DEBUG] Using downloads-root: E:\Libs\vcpkg\downloads
[DEBUG] Using packages-root: E:\Libs\vcpkg\packages
[DEBUG] Using scripts-root: E:\Libs\vcpkg\scripts
[DEBUG] Using ports-root: E:\Libs\vcpkg\ports
[DEBUG] Using versions-root: E:\Libs\vcpkg\versions
**invalid command: x-download**
_<removed irrelevant commands list, etc.>_
[DEBUG] C:\A\1\70\s\src\vcpkg.cpp(46)
[DEBUG] Exiting after 36617 us (3739 us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:240 (message):

      Failed to download file.
      If you use a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.

      3. You proxy's remote server is out of service.

      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)

      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  ports/bzip2/portfile.cmake:2 (vcpkg_download_distfile)
  scripts/ports.cmake:139 (include)

Error: Building package bzip2:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: bzip2:x64-windows
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

Additionally, attach any relevant sections from the log files above.
-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by rkcarroll** [comment]
BTW, This appears to be a dependency of boost-iostreams

**Comment by autoantwort** [comment]
Do `git pull` and run `bootstrap-vcpkg.bat`

**Comment by rkcarroll** [comment]
Great! all good now.  Thanks!
