### ISSUE TITLE
xalan-c 1.12 Linux build failure

### ISSUE THREAD

**Issue by tedyyu** [microsoft/vcpkg#18830]
**Host Environment**
- OS: Linux / Ubuntu
- Compiler: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

**To Reproduce**
`./vcpkg install xerces-c[icu]`
`./vcpkg install xalan-c`

*Update: This problem can only be reproduced on my side when you install xalan-c after xerces-c[icu]

**Failure logs** 
# ./vcpkg install xalan-c
Computing installation plan...
The following packages will be built and installed:
    xalan-c[core]:x64-linux -> 1.12
Detecting compiler hash for triplet x64-linux...
Could not locate cached archive: /root/.cache/vcpkg/archives/c8/c880ddbc3f9b1a2289b90c4fb0f7c6242dea5dea69c9249161853f43bcf30db7.zip
Starting package 1/1: xalan-c:x64-linux
Building package xalan-c[core]:x64-linux...
-- Note: xalan-c only supports dynamic library linkage. Building dynamic library.
-- Using /root/vcpkg/downloads/apache-xalan-c-4055bb0c58e3053b04fcd0c68fdcda8f84411213.tar.gz
-- Cleaning sources at /root/vcpkg/buildtrees/xalan-c/src/8f84411213-46f0020fde.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /root/vcpkg/downloads/apache-xalan-c-4055bb0c58e3053b04fcd0c68fdcda8f84411213.tar.gz
-- Applying patch fix-win-deprecated-err.patch
-- Applying patch fix-missing-dll-error.patch
-- Applying patch fix-linux-no-bin.patch
-- Using source at /root/vcpkg/buildtrees/xalan-c/src/8f84411213-46f0020fde.clean
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:146 (message):
    Command failed: /root/vcpkg/downloads/tools/cmake-3.20.2-linux/cmake-3.20.2-linux-x86_64/bin/cmake --build . --config Debug --target install -- -v -j9
    Working Directory: /root/vcpkg/buildtrees/xalan-c/x64-linux-dbg
    See logs for more information:
      /root/vcpkg/buildtrees/xalan-c/install-x64-linux-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:104 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:44 (vcpkg_build_cmake)
  ports/xalan-c/portfile.cmake:20 (vcpkg_install_cmake)
  scripts/ports.cmake:139 (include)

Error: Building package xalan-c:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: xalan-c:x64-linux
  Vcpkg version: 2021-05-05-unknownhash

Additionally, attach any relevant sections from the log files above.

**Additional context**
I'm using a fresh new git clone of vcpkg on this Linux machine, so nothing to do for ”./vcpkg update".

**Comment by NancyLi1013** [comment]
Hi @tedyyu 

Thanks for posting this issue.
Could you please help provide the error log from _/root/vcpkg/buildtrees/xalan-c/install-x64-linux-dbg-out.log_?

**Comment by tedyyu** [comment]
Sure. 

# cat  /root/vcpkg/buildtrees/xalan-c/install-x64-linux-dbg-out.log
[1/445] /usr/bin/c++ -D_FILE_OFFSET_BITS=64 -D_THREAD_SAFE=1 -I/root/vcpkg/buildtrees/xalan-c/src/8f84411213-46f0020fde.clean/src -Isrc -isystem /root/vcpkg/installed/x64-linux/include -fPIC -Wall -Wcast-align -Wcast-qual -Wctor-dtor-privacy -Wextra -Wformat=2 -Wmissing-declarations -Wno-long-long -Woverlength-strings -Woverloaded-virtual -Wredundant-decls -Wreorder -Wswitch-default -Wunused-variable -Wwrite-strings -Wno-variadic-macros -fstrict-aliasing -g -std=gnu++14 -MD -MT src/xalanc/Utils/MsgCreator/CMakeFiles/MsgCreator.dir/MsgFileOutputStream.cpp.o -MF src/xalanc/Utils/MsgCreator/CMakeFiles/MsgCreator.dir/MsgFileOutputStream.cpp.o.d -o src/xalanc/Utils/MsgCreator/CMakeFiles/MsgCreator.dir/MsgFileOutputStream.cpp.o -c /root/vcpkg/buildtrees/xalan-c/src/8f84411213-46f0020fde.clean/src/xalanc/Utils/MsgCreator/MsgFileOutputStream.cpp
/root/vcpkg/buildtrees/xalan-c/src/8f84411213-46f0020fde.clean/src/xalanc/Utils/MsgCreator/MsgFileOutputStream.cpp: In function ‘void xalanc_1_12::FormatMessageLocal(const char*, const char*, int, char*)’:
/root/vcpkg/buildtrees/xalan-c/src/8f84411213-46f0020fde.clean/src/xalanc/Utils/MsgCreator/MsgFileOutputStream.cpp:116:1: warning: no previous declaration for ‘void xalanc_1_12::FormatMessageLocal(const char*, const char*, int, char*)’ [-Wmissing-declarations]
 FormatMessageLocal(
 ^~~~~~~~~~~~~~~~~~
[2/445] /usr/bin/c++ -D_FILE_OFFSET_BITS=64 -D_THREAD_SAFE=1 -I/root/vcpkg/buildtrees/xalan-c/src/8f84411213-46f0020fde.clean/src -Isrc -isystem /root/vcpkg/installed/x64-linux/include -fPIC -Wall -Wcast-align -Wcast-qual -Wctor-dtor-privacy -Wextra -Wformat=2 -Wmissing-declarations -Wno-long-long -Woverlength-strings -Woverloaded-virtual -Wredundant-decls -Wreorder -Wswitch-default -Wunused-variable -Wwrite-strings -Wno-variadic-macros -fstrict-aliasing -g -std=gnu++14 -MD -MT src/xalanc/Utils/MsgCreator/CMakeFiles/MsgCreator.dir/ICUResHandler.cpp.o -MF src/xalanc/Utils/MsgCreator/CMakeFiles/MsgCreator.dir/ICUResHandler.cpp.o.d -o src/xalanc/Utils/MsgCreator/CMakeFiles/MsgCreator.dir/ICUResHandler.cpp.o -c /root/vcpkg/buildtrees/xalan-c/src/8f84411213-46f0020fde.clean/src/xalanc/Utils/MsgCreator/ICUResHandler.cpp
[3/445] /usr/bin/c++ -D_FILE_OFFSET_BITS=64 -D_THREAD_SAFE=1 -I/root/vcpkg/buildtrees/xalan-c/src/8f84411213-46f0020fde.clean/src -Isrc -isystem /root/vcpkg/installed/x64-linux/include -fPIC -Wall -Wcast-align -Wcast-qual -Wctor-dtor-privacy -Wextra -Wformat=2 -Wmissing-declarations -Wno-long-long -Woverlength-strings -Woverloaded-virtual -Wredundant-decls -Wreorder -Wswitch-default -Wunused-variable -Wwrite-strings -Wno-variadic-macros -fstrict-aliasing -g -std=gnu++14 -MD -MT src/xalanc/Utils/MsgCreator/CMakeFiles/MsgCreator.dir/NLSHandler.cpp.o -MF src/xalanc/Utils/MsgCreator/CMakeFiles/MsgCreator.dir/NLSHandler.cpp.o.d -o src/xalanc/Utils/MsgCreator/CMakeFiles/MsgCreator.dir/NLSHandler.cpp.o -c /root/vcpkg/buildtrees/xalan-c/src/8f84411213-46f0020fde.clean/src/xalanc/Utils/MsgCreator/NLSHandler.cpp
[4/445] /usr/bin/c++ -D_FILE_OFFSET_BITS=64 -D_THREAD_SAFE=1 -I/root/vcpkg/buildtrees/xalan-c/src/8f84411213-46f0020fde.clean/src -Isrc -isystem /root/vcpkg/installed/x64-linux/include -fPIC -Wall -Wcast-align -Wcast-qual -Wctor-dtor-privacy -Wextra -Wformat=2 -Wmissing-declarations -Wno-long-long -Woverlength-strings -Woverloaded-virtual -Wredundant-decls -Wreorder -Wswitch-default -Wunused-variable -Wwrite-strings -Wno-variadic-macros -fstrict-aliasing -g -std=gnu++14 -MD -MT src/xalanc/Utils/MsgCreator/CMakeFiles/MsgCreator.dir/InMemHandler.cpp.o -MF src/xalanc/Utils/MsgCreator/CMakeFiles/MsgCreator.dir/InMemHandler.cpp.o.d -o src/xalanc/Utils/MsgCreator/CMakeFiles/MsgCreator.dir/InMemHandler.cpp.o -c /root/vcpkg/buildtrees/xalan-c/src/8f84411213-46f0020fde.clean/src/xalanc/Utils/MsgCreator/InMemHandler.cpp
[5/445] /usr/bin/c++ -D_FILE_OFFSET_BITS=64 -D_THREAD_SAFE=1 -I/root/vcpkg/buildtrees/xalan-c/src/8f84411213-46f0020fde.clean/src -Isrc -isystem /root/vcpkg/installed/x64-linux/include -fPIC -Wall -Wcast-align -Wcast-qual -Wctor-dtor-privacy -Wextra -Wformat=2 -Wmissing-declarations -Wno-long-long -Woverlength-strings -Woverloaded-virtual -Wredundant-decls -Wreorder -Wswitch-default -Wunused-variable -Wwrite-strings -Wno-variadic-macros -fstrict-aliasing -g -std=gnu++14 -MD -MT src/xalanc/Utils/MsgCreator/CMakeFiles/MsgCreator.dir/SAX2Handler.cpp.o -MF src/xalanc/Utils/MsgCreator/CMakeFiles/MsgCreator.dir/SAX2Handler.cpp.o.d -o src/xalanc/Utils/MsgCreator/CMakeFiles/MsgCreator.dir/SAX2Handler.cpp.o -c /root/vcpkg/buildtrees/xalan-c/src/8f84411213-46f0020fde.clean/src/xalanc/Utils/MsgCreator/SAX2Handler.cpp
[6/445] /usr/bin/c++ -D_FILE_OFFSET_BITS=64 -D_THREAD_SAFE=1 -I/root/vcpkg/buildtrees/xalan-c/src/8f84411213-46f0020fde.clean/src -Isrc -isystem /root/vcpkg/installed/x64-linux/include -fPIC -Wall -Wcast-align -Wcast-qual -Wctor-dtor-privacy -Wextra -Wformat=2 -Wmissing-declarations -Wno-long-long -Woverlength-strings -Woverloaded-virtual -Wredundant-decls -Wreorder -Wswitch-default -Wunused-variable -Wwrite-strings -Wno-variadic-macros -fstrict-aliasing -g -std=gnu++14 -MD -MT src/xalanc/Utils/MsgCreator/CMakeFiles/MsgCreator.dir/MsgCreator.cpp.o -MF src/xalanc/Utils/MsgCreator/CMakeFiles/MsgCreator.dir/MsgCreator.cpp.o.d -o src/xalanc/Utils/MsgCreator/CMakeFiles/MsgCreator.dir/MsgCreator.cpp.o -c /root/vcpkg/buildtrees/xalan-c/src/8f84411213-46f0020fde.clean/src/xalanc/Utils/MsgCreator/MsgCreator.cpp
/root/vcpkg/buildtrees/xalan-c/src/8f84411213-46f0020fde.clean/src/xalanc/Utils/MsgCreator/MsgCreator.cpp: In function ‘bool getArgs(int, char**, CmdLineParams&, const char**)’:
/root/vcpkg/buildtrees/xalan-c/src/8f84411213-46f0020fde.clean/src/xalanc/Utils/MsgCreator/MsgCreator.cpp:122:1: warning: no previous declaration for ‘bool getArgs(int, char**, CmdLineParams&, const char**)’ [-Wmissing-declarations]
 getArgs(
 ^~~~~~~
[7/445] : && /usr/bin/c++ -fPIC -Wall -Wcast-align -Wcast-qual -Wctor-dtor-privacy -Wextra -Wformat=2 -Wmissing-declarations -Wno-long-long -Woverlength-strings -Woverloaded-virtual -Wredundant-decls -Wreorder -Wswitch-default -Wunused-variable -Wwrite-strings -Wno-variadic-macros -fstrict-aliasing -g -rdynamic src/xalanc/Utils/MsgCreator/CMakeFiles/MsgCreator.dir/ICUResHandler.cpp.o src/xalanc/Utils/MsgCreator/CMakeFiles/MsgCreator.dir/InMemHandler.cpp.o src/xalanc/Utils/MsgCreator/CMakeFiles/MsgCreator.dir/MsgCreator.cpp.o src/xalanc/Utils/MsgCreator/CMakeFiles/MsgCreator.dir/MsgFileOutputStream.cpp.o src/xalanc/Utils/MsgCreator/CMakeFiles/MsgCreator.dir/NLSHandler.cpp.o src/xalanc/Utils/MsgCreator/CMakeFiles/MsgCreator.dir/SAX2Handler.cpp.o -o src/xalanc/Utils/MsgCreator/MsgCreator  /root/vcpkg/installed/x64-linux/debug/lib/libxerces-c.a && :
FAILED: src/xalanc/Utils/MsgCreator/MsgCreator
: && /usr/bin/c++ -fPIC -Wall -Wcast-align -Wcast-qual -Wctor-dtor-privacy -Wextra -Wformat=2 -Wmissing-declarations -Wno-long-long -Woverlength-strings -Woverloaded-virtual -Wredundant-decls -Wreorder -Wswitch-default -Wunused-variable -Wwrite-strings -Wno-variadic-macros -fstrict-aliasing -g -rdynamic src/xalanc/Utils/MsgCreator/CMakeFiles/MsgCreator.dir/ICUResHandler.cpp.o src/xalanc/Utils/MsgCreator/CMakeFiles/MsgCreator.dir/InMemHandler.cpp.o src/xalanc/Utils/MsgCreator/CMakeFiles/MsgCreator.dir/MsgCreator.cpp.o src/xalanc/Utils/MsgCreator/CMakeFiles/MsgCreator.dir/MsgFileOutputStream.cpp.o src/xalanc/Utils/MsgCreator/CMakeFiles/MsgCreator.dir/NLSHandler.cpp.o src/xalanc/Utils/MsgCreator/CMakeFiles/MsgCreator.dir/SAX2Handler.cpp.o -o src/xalanc/Utils/MsgCreator/MsgCreator  /root/vcpkg/installed/x64-linux/debug/lib/libxerces-c.a && :
/root/vcpkg/installed/x64-linux/debug/lib/libxerces-c.a(ICUTransService.cpp.o): In function `xercesc_3_2::convertToXMLCh(char16_t const*, xercesc_3_2::MemoryManager*)':
/root/vcpkg/buildtrees/xerces-c/src/v3.2.3-991a51b227.clean/src/xercesc/util/Transcoders/ICU/ICUTransService.cpp:122: undefined reference to `u_strlen_69'
/root/vcpkg/installed/x64-linux/debug/lib/libxerces-c.a(ICUTransService.cpp.o): In function `xercesc_3_2::ICUTransService::compareIString(char16_t const*, char16_t const*)':
/root/vcpkg/buildtrees/xerces-c/src/v3.2.3-991a51b227.clean/src/xercesc/util/Transcoders/ICU/ICUTransService.cpp:211: undefined reference to `u_foldCase_69'
/root/vcpkg/buildtrees/xerces-c/src/v3.2.3-991a51b227.clean/src/xercesc/util/Transcoders/ICU/ICUTransService.cpp:214: undefined reference to `u_foldCase_69'
/root/vcpkg/installed/x64-linux/debug/lib/libxerces-c.a(ICUTransService.cpp.o): In function `xercesc_3_2::ICUTransService::compareNIString(char16_t const*, char16_t const*, unsigned long)':
/root/vcpkg/buildtrees/xerces-c/src/v3.2.3-991a51b227.clean/src/xercesc/util/Transcoders/ICU/ICUTransService.cpp:256: undefined reference to `u_foldCase_69'
/root/vcpkg/buildtrees/xerces-c/src/v3.2.3-991a51b227.clean/src/xercesc/util/Transcoders/ICU/ICUTransService.cpp:259: undefined reference to `u_foldCase_69'
/root/vcpkg/installed/x64-linux/debug/lib/libxerces-c.a(ICUTransService.cpp.o): In function `xercesc_3_2::ICUTransService::makeNewLCPTranscoder(xercesc_3_2::MemoryManager*)':
/root/vcpkg/buildtrees/xerces-c/src/v3.2.3-991a51b227.clean/src/xercesc/util/Transcoders/ICU/ICUTransService.cpp:298: undefined reference to `ucnv_open_69'
/root/vcpkg/installed/x64-linux/debug/lib/libxerces-c.a(ICUTransService.cpp.o): In function `xercesc_3_2::ICUTransService::upperCase(char16_t*)':
/root/vcpkg/buildtrees/xerces-c/src/v3.2.3-991a51b227.clean/src/xercesc/util/Transcoders/ICU/ICUTransService.cpp:358: undefined reference to `u_toupper_69'
/root/vcpkg/installed/x64-linux/debug/lib/libxerces-c.a(ICUTransService.cpp.o): In function `xercesc_3_2::ICUTransService::lowerCase(char16_t*)':
/root/vcpkg/buildtrees/xerces-c/src/v3.2.3-991a51b227.clean/src/xercesc/util/Transcoders/ICU/ICUTransService.cpp:363: undefined reference to `u_tolower_69'
/root/vcpkg/installed/x64-linux/debug/lib/libxerces-c.a(ICUTransService.cpp.o): In function `xercesc_3_2::ICUTransService::makeNewXMLTranscoder(char16_t const*, xercesc_3_2::XMLTransService::Codes&, unsigned long, xercesc_3_2::MemoryManager*)':
/root/vcpkg/buildtrees/xerces-c/src/v3.2.3-991a51b227.clean/src/xercesc/util/Transcoders/ICU/ICUTransService.cpp:416: undefined reference to `ucnv_openU_69'
/root/vcpkg/installed/x64-linux/debug/lib/libxerces-c.a(ICUTransService.cpp.o): In function `xercesc_3_2::ICUTranscoder::ICUTranscoder(char16_t const*, UConverter*, unsigned long, xercesc_3_2::MemoryManager*)':
/root/vcpkg/buildtrees/xerces-c/src/v3.2.3-991a51b227.clean/src/xercesc/util/Transcoders/ICU/ICUTransService.cpp:450: undefined reference to `ucnv_getMaxCharSize_69'
/root/vcpkg/buildtrees/xerces-c/src/v3.2.3-991a51b227.clean/src/xercesc/util/Transcoders/ICU/ICUTransService.cpp:450: undefined reference to `ucnv_getMinCharSize_69'
/root/vcpkg/installed/x64-linux/debug/lib/libxerces-c.a(ICUTransService.cpp.o): In function `xercesc_3_2::ICUTranscoder::~ICUTranscoder()':
/root/vcpkg/buildtrees/xerces-c/src/v3.2.3-991a51b227.clean/src/xercesc/util/Transcoders/ICU/ICUTransService.cpp:461: undefined reference to `ucnv_close_69'
/root/vcpkg/installed/x64-linux/debug/lib/libxerces-c.a(ICUTransService.cpp.o): In function `xercesc_3_2::ICUTranscoder::transcodeFrom(unsigned char const*, unsigned long, char16_t*, unsigned long, unsigned long&, unsigned char*)':
/root/vcpkg/buildtrees/xerces-c/src/v3.2.3-991a51b227.clean/src/xercesc/util/Transcoders/ICU/ICUTransService.cpp:503: undefined reference to `ucnv_toUnicode_69'
/root/vcpkg/buildtrees/xerces-c/src/v3.2.3-991a51b227.clean/src/xercesc/util/Transcoders/ICU/ICUTransService.cpp:551: undefined reference to `ucnv_getMaxCharSize_69'
/root/vcpkg/installed/x64-linux/debug/lib/libxerces-c.a(ICUTransService.cpp.o): In function `xercesc_3_2::ICUTranscoder::transcodeTo(char16_t const*, unsigned long, unsigned char*, unsigned long, unsigned long&, xercesc_3_2::XMLTranscoder::UnRepOpts)':
/root/vcpkg/buildtrees/xerces-c/src/v3.2.3-991a51b227.clean/src/xercesc/util/Transcoders/ICU/ICUTransService.cpp:642: undefined reference to `UCNV_FROM_U_CALLBACK_STOP_69'
/root/vcpkg/buildtrees/xerces-c/src/v3.2.3-991a51b227.clean/src/xercesc/util/Transcoders/ICU/ICUTransService.cpp:642: undefined reference to `UCNV_FROM_U_CALLBACK_SUBSTITUTE_69'
/root/vcpkg/buildtrees/xerces-c/src/v3.2.3-991a51b227.clean/src/xercesc/util/Transcoders/ICU/ICUTransService.cpp:642: undefined reference to `ucnv_setFromUCallBack_69'
/root/vcpkg/buildtrees/xerces-c/src/v3.2.3-991a51b227.clean/src/xercesc/util/Transcoders/ICU/ICUTransService.cpp:660: undefined reference to `ucnv_fromUnicode_69'
/root/vcpkg/buildtrees/xerces-c/src/v3.2.3-991a51b227.clean/src/xercesc/util/Transcoders/ICU/ICUTransService.cpp:678: undefined reference to `ucnv_setFromUCallBack_69'
/root/vcpkg/installed/x64-linux/debug/lib/libxerces-c.a(ICUTransService.cpp.o): In function `xercesc_3_2::ICUTranscoder::canTranscodeTo(unsigned int)':
/root/vcpkg/buildtrees/xerces-c/src/v3.2.3-991a51b227.clean/src/xercesc/util/Transcoders/ICU/ICUTransService.cpp:735: undefined reference to `UCNV_FROM_U_CALLBACK_STOP_69'
/root/vcpkg/buildtrees/xerces-c/src/v3.2.3-991a51b227.clean/src/xercesc/util/Transcoders/ICU/ICUTransService.cpp:735: undefined reference to `ucnv_setFromUCallBack_69'
/root/vcpkg/buildtrees/xerces-c/src/v3.2.3-991a51b227.clean/src/xercesc/util/Transcoders/ICU/ICUTransService.cpp:751: undefined reference to `ucnv_fromUnicode_69'
/root/vcpkg/buildtrees/xerces-c/src/v3.2.3-991a51b227.clean/src/xercesc/util/Transcoders/ICU/ICUTransService.cpp:769: undefined reference to `ucnv_setFromUCallBack_69'
/root/vcpkg/installed/x64-linux/debug/lib/libxerces-c.a(ICUTransService.cpp.o): In function `xercesc_3_2::ICULCPTranscoder::~ICULCPTranscoder()':
/root/vcpkg/buildtrees/xerces-c/src/v3.2.3-991a51b227.clean/src/xercesc/util/Transcoders/ICU/ICUTransService.cpp:791: undefined reference to `ucnv_close_69'
/root/vcpkg/installed/x64-linux/debug/lib/libxerces-c.a(ICUTransService.cpp.o): In function `xercesc_3_2::ICULCPTranscoder::calcRequiredSize(char16_t const*, xercesc_3_2::MemoryManager*)':
/root/vcpkg/buildtrees/xerces-c/src/v3.2.3-991a51b227.clean/src/xercesc/util/Transcoders/ICU/ICUTransService.cpp:818: undefined reference to `ucnv_fromUChars_69'
/root/vcpkg/installed/x64-linux/debug/lib/libxerces-c.a(ICUTransService.cpp.o): In function `xercesc_3_2::ICULCPTranscoder::calcRequiredSize(char const*, xercesc_3_2::MemoryManager*)':
/root/vcpkg/buildtrees/xerces-c/src/v3.2.3-991a51b227.clean/src/xercesc/util/Transcoders/ICU/ICUTransService.cpp:870: undefined reference to `ucnv_toUChars_69'
/root/vcpkg/installed/x64-linux/debug/lib/libxerces-c.a(ICUTransService.cpp.o): In function `xercesc_3_2::ICULCPTranscoder::transcode(char16_t const*, xercesc_3_2::MemoryManager*)':
/root/vcpkg/buildtrees/xerces-c/src/v3.2.3-991a51b227.clean/src/xercesc/util/Transcoders/ICU/ICUTransService.cpp:951: undefined reference to `ucnv_fromUChars_69'
/root/vcpkg/buildtrees/xerces-c/src/v3.2.3-991a51b227.clean/src/xercesc/util/Transcoders/ICU/ICUTransService.cpp:975: undefined reference to `ucnv_fromUChars_69'
/root/vcpkg/installed/x64-linux/debug/lib/libxerces-c.a(ICUTransService.cpp.o): In function `xercesc_3_2::ICULCPTranscoder::transcode(char const*, xercesc_3_2::MemoryManager*)':
/root/vcpkg/buildtrees/xerces-c/src/v3.2.3-991a51b227.clean/src/xercesc/util/Transcoders/ICU/ICUTransService.cpp:1030: undefined reference to `ucnv_toUChars_69'
/root/vcpkg/buildtrees/xerces-c/src/v3.2.3-991a51b227.clean/src/xercesc/util/Transcoders/ICU/ICUTransService.cpp:1046: undefined reference to `ucnv_toUChars_69'
/root/vcpkg/installed/x64-linux/debug/lib/libxerces-c.a(ICUTransService.cpp.o): In function `xercesc_3_2::ICULCPTranscoder::transcode(char const*, char16_t*, unsigned long, xercesc_3_2::MemoryManager*)':
/root/vcpkg/buildtrees/xerces-c/src/v3.2.3-991a51b227.clean/src/xercesc/util/Transcoders/ICU/ICUTransService.cpp:1127: undefined reference to `ucnv_toUChars_69'
/root/vcpkg/installed/x64-linux/debug/lib/libxerces-c.a(ICUTransService.cpp.o): In function `xercesc_3_2::ICULCPTranscoder::transcode(char16_t const*, char*, unsigned long, xercesc_3_2::MemoryManager*)':
/root/vcpkg/buildtrees/xerces-c/src/v3.2.3-991a51b227.clean/src/xercesc/util/Transcoders/ICU/ICUTransService.cpp:1207: undefined reference to `ucnv_fromUChars_69'
/root/vcpkg/installed/x64-linux/debug/lib/libxerces-c.a(XMLUniCharacter.cpp.o): In function `xercesc_3_2::XMLUniCharacter::getType(char16_t)':
/root/vcpkg/buildtrees/xerces-c/src/v3.2.3-991a51b227.clean/src/xercesc/util/regx/XMLUniCharacter.cpp:46: undefined reference to `u_charType_69'
/root/vcpkg/installed/x64-linux/debug/lib/libxerces-c.a(RangeToken.cpp.o): In function `xercesc_3_2::RangeToken::getCaseInsensitiveToken(xercesc_3_2::TokenFactory*)':
/root/vcpkg/buildtrees/xerces-c/src/v3.2.3-991a51b227.clean/src/xercesc/util/regx/RangeToken.cpp:199: undefined reference to `uset_openPatternOptions_69'
/root/vcpkg/buildtrees/xerces-c/src/v3.2.3-991a51b227.clean/src/xercesc/util/regx/RangeToken.cpp:203: undefined reference to `uset_serialize_69'
/root/vcpkg/buildtrees/xerces-c/src/v3.2.3-991a51b227.clean/src/xercesc/util/regx/RangeToken.cpp:207: undefined reference to `uset_serialize_69'
/root/vcpkg/buildtrees/xerces-c/src/v3.2.3-991a51b227.clean/src/xercesc/util/regx/RangeToken.cpp:209: undefined reference to `uset_getSerializedSet_69'
/root/vcpkg/buildtrees/xerces-c/src/v3.2.3-991a51b227.clean/src/xercesc/util/regx/RangeToken.cpp:210: undefined reference to `uset_getSerializedRangeCount_69'
/root/vcpkg/buildtrees/xerces-c/src/v3.2.3-991a51b227.clean/src/xercesc/util/regx/RangeToken.cpp:214: undefined reference to `uset_getSerializedRange_69'
/root/vcpkg/buildtrees/xerces-c/src/v3.2.3-991a51b227.clean/src/xercesc/util/regx/RangeToken.cpp:218: undefined reference to `uset_setSerializedToOne_69'
/root/vcpkg/buildtrees/xerces-c/src/v3.2.3-991a51b227.clean/src/xercesc/util/regx/RangeToken.cpp:219: undefined reference to `uset_close_69'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

**Comment by tedyyu** [comment]
Hi, @NancyLi1013 

The problem is gone after running `sudo apt install build-essential` on the Linux machine.
I think we can close this issue. Thanks.

**Comment by tedyyu** [comment]
BTW, I'll add a pr to add [icu] feature to xalan-c package, just like xerces-c[icu].

**Comment by NancyLi1013** [comment]
Glad to hear the good news. Sorry for my late response.

But the problem you encountered seems to be related with `icu`.
`991a51b227.clean/src/xercesc/util/Transcoders/ICU/ICUTransService.cpp:122: undefined reference to u_strlen_69'`

So we still need to figure this out.

Currently, vcpkg has disabled `icu` in `xalan-c`, I'm not clear why this is still happening.

https://github.com/microsoft/vcpkg/blob/b761301f77a68bbe443034f1ed6ccebbd52614e8/ports/xalan-c/portfile.cmake#L17

**Comment by dg0yt** [comment]
> Currently, vcpkg has disabled `icu` in `xalan-c`, I'm not clear why this is still happening.

xalan-c depends on xerces-c. And that's where the linking errors come from: 

>     /root/vcpkg/buildtrees/xerces-c/src/v3.2.3-991a51b227.clean/src/xercesc/util/regx/RangeToken.cpp:218: undefined reference to uset_setSerializedToOne_69' /root/vcpkg/buildtrees/xerces-c/src/v3.2.3-991a51b227.clean/src/xercesc/util/regx/RangeToken.cpp:219: undefined reference to uset_close_69'

xerces-c can use icu if enabled as a feature. Now you have to check
- if xerces-c forwards the transitive dependency, and
- if xalan-c checks makes use of this dependency. 

`CMAKE_DISABLE_FIND_PACKAGE_ICU=ON` might interfer with handling of transitive dependencies (lesson learnt from tiff wrapper).

**Comment by NancyLi1013** [comment]
Thanks for your investigation @dg0yt. It's my mistake. I forgot the dependency `xerces-c` and got a wrong information for the error log.

**Comment by tedyyu** [comment]
Some updates:

This problem can only be reproduced on my side when you install `xalan-c` after `xerces-c[icu]`. I think it's reasonable behavior, as libxerces-c.so with ICU has some ICU related symbols, but xalan-c has no means to know that without extra inputs, usually in cmake it's `cmake -Dtranscoder=icu`, see also [build instructions](https://apache.github.io/xalan-c/build.html) from apache.

ICU should be consistently used in xerces-c and xalan-c, and the developers using them should know about that.

**Comment by dg0yt** [comment]
xalan-c was delisted with #27401.
This issue must be closed without fix.
