### ISSUE TITLE
Exiv2 update to 0.27.4

### ISSUE THREAD

**Issue by ndurner** [microsoft/vcpkg#18840]
Library name:Exiv2 

New version number: 0.27.4

**Comment by EvanAW** [comment]
Exiv2 was updated to 0.27.4 an hour ago. 
See: https://github.com/microsoft/vcpkg/commit/75a90ccfb1f8d1206f1fb5900c27bf14d0a9aeb7

**Comment by JonLiu1993** [comment]
@ndurner ,Thanks for posting this issue,this issue duplicate of #18690,so this issue will be closed
