### ISSUE TITLE
Failed to build boost-compability

### ISSUE THREAD

**Issue by Chessom** [microsoft/vcpkg#18845]
OS:Windows 10
vcpkg-version:latest
Error Log:

Starting package 1/153: boost-compatibility:x64-windows
Building package boost-compatibility[core]:x64-windows...
-- Using cached E:/vcpkg-2021.05.12/downloads/boostorg-compatibility-boost-1.75.0.tar.gz
-- Cleaning sources at E:/vcpkg-2021.05.12/buildtrees/boost-compatibility/src/ost-1.75.0-b473de8f4d.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/vcpkg-2021.05.12/downloads/boostorg-compatibility-boost-1.75.0.tar.gz
-- Using source at E:/vcpkg-2021.05.12/buildtrees/boost-compatibility/src/ost-1.75.0-b473de8f4d.clean
-- Packaging headers
-- Packaging headers done
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.74.0/LICENSE_1_0.txt -> boost_LICENSE_1_0.txt...
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.74.0/LICENSE_1_0.txt... Failed. Status: 4;"A requested feature, protocol or option was not found built-in in this libcurl due to a build-time decision."
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:184 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".

      If error with status 4 (Issue #15434),
      try setting "http://user:password@your-proxy-ip-address:port/".

      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  installed/x64-windows/share/boost-vcpkg-helpers/boost-modular-headers.cmake:17 (vcpkg_download_distfile)
  ports/boost-compatibility/portfile.cmake:12 (boost_modular_headers)
  scripts/ports.cmake:142 (include)

Error: Building package boost-compatibility:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-compatibility:x64-windows
  Vcpkg version: 2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9

Additionally, attach any relevant sections from the log files above.

I have never used a proxy service.I tried to find solution in #15434,however it didn't work.

**Comment by PhoebeHui** [comment]
@Chessom, could you try the solution in https://github.com/microsoft/vcpkg/issues/13348#issue-692784879

**Comment by Chessom** [comment]
> @Chessom，你能试试[#13348（评论）中](https://github.com/microsoft/vcpkg/issues/13348#issue-692784879)的解决方案吗？如果它对您不起作用，请告诉我。

**Comment by Chessom** [comment]
OK.I solved it by installing boost_LICENSE_1_0.txt by hand.Thanks for your help!
