### ISSUE TITLE
[qhull] qset.c functions are not built

### ISSUE THREAD

**Issue by furkanxdgs4** [microsoft/vcpkg#18854]
Hi. I installed PCL with vcpkg and so qhull is installed too. I'm using PCL already but I want to access qhull functionality too. When I try to use qhull's runQhull function (in orgQhull:Qhull), linker fails as "unresolved external symbol qh_memcheck" and some other qset.c related functions. I tried to build qhull myself and when I did that, it fails because my build is a different version against vcpkg's. How can I solve this issue? I'm using latest version of both vcpkg and all other libraries.

**Comment by NancyLi1013** [comment]
Hi @furkanxdgs4 

Thanks for posting this issue.

Could you please help provide your project sample here?

**Comment by furkanxdgs4** [comment]
The project is a little bit big, so I can't provide much here now but I found a workaround by including all of libqhull_r and libqhullcpp files except some .c that's causing linker issues. But also this workaround is causing errors on some functions, so it's better solved properly. I'm a little bit busy these days, I'll probably get back to help on the issue in a week or so.

**Comment by NancyLi1013** [comment]
You can provide a simple sample, just includes the functions that have problems.

**Comment by furkanxdgs4** [comment]
I don't know how much it can help because it's a unresolved external function issue but here's the very basic example.
'''
#include <libqhullcpp/Qhull.h>
void CalculateVoronoi(){
	orgQhull::Qhull x;
	x.runQhull("", 0, 0, nullptr, "");
}
'''
When you include and call the function, linker will give the unresolved external function.

**Comment by NancyLi1013** [comment]
```
1>qhullcpp_d.lib(QhullQh.cpp.obj) : error LNK2019: unresolved external symbol qh_memcheck referenced in function "public: void __cdecl orgQhull::QhullQh::checkAndFreeQhullMemory(void)" (?checkAndFreeQhullMemory@QhullQh@orgQhull@@QEAAXXZ)
1>qhullcpp_d.lib(QhullFacetSet.cpp.obj) : error LNK2001: unresolved external symbol qh_setendpointer
1>qhullcpp_d.lib(QhullVertex.cpp.obj) : error LNK2001: unresolved external symbol qh_setendpointer
1>qhullcpp_d.lib(QhullFacet.cpp.obj) : error LNK2001: unresolved external symbol qh_setendpointer
1>qhullcpp_d.lib(QhullPointSet.cpp.obj) : error LNK2001: unresolved external symbol qh_setendpointer
1>qhullcpp_d.lib(QhullVertexSet.cpp.obj) : error LNK2001: unresolved external symbol qh_setendpointer
1>C:\Users\Nancy\source\repos\ConsoleApplication10\x64\Debug\ConsoleApplication10.exe : fatal error LNK1120: 2 unresolved externals
1>Done building project "ConsoleApplication10.vcxproj" -- FAILED.
```

**Comment by JackBoosY** [comment]
Because the function `qh_memcheck` isn't exported in the source (.h / .def). 
I think it's a upstream bug.

**Comment by NancyLi1013** [comment]
Hi @furkanxdgs4 

This issue should be solved now. Please update to the latest vcpkg to rebuild this.
