### ISSUE TITLE
[vswhere] update to 2.8.4

### ISSUE THREAD

**Issue by xavier2k6** [microsoft/vcpkg#18853]
Library name: `vswhere` -> `scripts/vcpkgTools.xml`

New version number: 2.8.4 (Latest Release)

Other information that may be useful (release notes, etc...)

ref:
https://github.com/microsoft/vcpkg/blob/master/scripts/vcpkgTools.xml#L84:L88

https://github.com/Microsoft/vswhere/releases

**Comment by PhoebeHui** [comment]
Closing in favor of https://github.com/microsoft/vcpkg/issues/18815
