### ISSUE TITLE
Library purge leaves build tree on the disk.

### ISSUE THREAD

**Issue by lazyhamster** [microsoft/vcpkg#1885]
I've noticed that currently if I try to remove the library it's sources and build files from 'buildtrees' folder are left untouched. Supplying --purge flag doesn't change anything.
Isn't it would be logical to remove everything from the library with --purge flag? Maybe downloaded archive could be left for future use but build tree should be removed IMO.

**Comment by jasjuang** [comment]
I also think the build files from older sources should be deleted too. My current vcpkg folder currently is exceeding 250gb.

**Comment by jasjuang** [comment]
I also realized the buildtree folder is taking 200gb out of 250gb of my vcpkg folder. I would even like to see an option to purge the buildtree after installation. It looks to me that the buildtree is only useful for debugging purposes.

**Comment by MikeGitb** [comment]
I also think that some tools to cleanup the vcpkg folder would be very usefull.

**Comment by genbtc** [comment]
Oh wow this doesnt exist? OK Hmmm. Interesting to know. I Came here also to find out the proper way how to do this.

**Comment by patrikhuber** [comment]
> It looks to me that the buildtree is only useful for debugging purposes.

This is very important though. I'd hate to be left with the choice to either A) download the source files (and the correct version) manually after vcpkg installation, or B) have to keep both the source files in vcpkg as well as all these gigabytes of build artefacts.

vcpkg should:
* Leave the source files intact
* Have the ability to purge **intermediate** build files, like the `.pch` files, which are actually the files taking most of the space.

**Comment by arthur-tacca** [comment]
@patrikhuber I think a first approximation of this would be pretty easy. Within the `buildtrees/<portname>` directory, there is a subdirectory `src` and a subdirectory for each build (with name `<triplet>-<dbg or rel>`). So a vcpkg option to purge build files could just delete these subdirectories while leaving `src`.

This would have some problems. Generated source files, e.g. as created by protoc or moc, would be deleted. But I think that, to since problems like that, you would need help from individual ports rather than a heuristic algorithm.

**Comment by NancyLi1013** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen.

**Comment by MikeGitb** [comment]
Still a problem. Please reopen

**Comment by PhoebeHui** [comment]
Currently this is supported, you can pass '--clean-after-build' to clean buildtrees, packages after building each package,  eg: './vcpkg install xxx  --clean-after-build'. BTW, the --purge flag has been removed now.

**Comment by MikeGitb** [comment]
Thanks. Is there a way to lean up the build tree after the fact?
