### ISSUE TITLE
Unsupported toolchain combination x64 on appveyor

### ISSUE THREAD

**Issue by mcgoo** [Microsoft/vcpkg#1886]
I had breakage before this so I'm not positive that this is a vcpkg issue but I am seeing the message "Unsupported toolchain combination x64" on my x64 appveyor builds where I was not previously.

[example](https://ci.appveyor.com/project/mcgoo/vcpkg-rs/build/1.0.164/job/6jdjda3d800seu8o)

Latest commit is 0ccea4f3677d92a2 [Toolset selection] Use VS2017 vcvarsall for v140 if available
Build machine is using tools from C:\Program Files (x86)\Microsoft Visual Studio 14.0

**Comment by mcgoo** [comment]
Looks like eca068e4c5673b888d6470b42d6b5b44b21c4007 is the bad commit.

I think the appveyor instance I am using is VS2015 only. I can't reproduce this locally, probably because I have VS2017 installed also.

**Comment by jasjuang** [comment]
Side question, do you think you can submit a PR to add appveyor CI into vcpkg?

**Comment by atkawa7** [comment]
@jasjuang see https://github.com/mcgoo/vcpkg-rs/blob/master/.appveyor.yml

**Comment by alexkaratarakis** [comment]
Fixed by reverting eca068e.

**Comment by mcgoo** [comment]
Works for me, thanks!
