### ISSUE TITLE
[New Port Request] DaisySP 

### ISSUE THREAD

**Issue by andywang0607** [microsoft/vcpkg#18864]
Library name: DaisySP 

Library description: A Powerful, Open Source DSP Library in C++

Source repository URL: https://github.com/electro-smith/DaisySP

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
