### ISSUE TITLE
Use vcpkg in a Visual Studio project without running vcpkg integrate install

### ISSUE THREAD

**Issue by davidhunter22** [microsoft/vcpkg#18868]
We tried running  "vcpkg integrate install" and found it to be extremely toxic, basically it broke lots of existing working builds as it messes around with include and link paths. Also getting all users to run  vcpkg integrate install is very hard in a big organization.

So is there any documentation on how to use vcpkg from Visual Studio without running vcpkg integrate install. Ideally we add stuff to a vcxproj file and/or import a .props file it imports and things just work after checking out the code. Note ideally this would use caching. I have looked in lots of places and they all say run "vcpkg integrate install". It would be great if https://vcpkg.io/en/docs/users/integration.html had a section on how to do this.

**Comment by davidhunter22** [comment]
As an extra question. Is there any documentation anywhere of script we could look at that shows what "vcpkg integrate install" actualy does?

**Comment by soumyamahunt** [comment]
> So is there any documentation on how to use vcpkg from Visual Studio without running vcpkg integrate install. Ideally we add stuff to a vcxproj file and/or import a .props file it imports and things just work after checking out the code. Note ideally this would use caching. I have looked in lots of places and they all say run "vcpkg integrate install". It would be great if https://vcpkg.io/en/docs/users/integration.html had a section on how to do this.

The article you linked also describes `vcpkg export` which seems exactly what you want. Have you looked into it if this is viable for your organization? Or is there any issue using export too?

**Comment by JackBoosY** [comment]
> We tried running "vcpkg integrate install" and found it to be extremely toxic, basically it broke lots of existing working builds as it messes around with include and link paths. Also getting all users to run vcpkg integrate install is very hard in a big organization.

Can you provide more information such as a example?

vcpkg only do the following steps when integrating msbuild:
1. Add _VCPKG_ROOT/installed/TRIPLET/include_ to the `Additional Include Directories`,
2. Add _VCPKG_ROOT/installed/TRIPLET/debug/lib_ or _VCPKG_ROOT/installed/TRIPLET/lib_ to `Additional Dependencies` (depending on different configurations)
3. Priority to build dependencies in manifest mode (automatically disabled if there is no manifest file).
4. Install the dependencies after the private project is built.

**Comment by JackBoosY** [comment]
@davidhunter22  Ping for response.

**Comment by davidhunter22** [comment]
After some digging I discovered that  "vcpkg integrate install" works as follows
1) Microsoft.Cpp.Common.props does an <Import> of $(LOCALAPPDATA)\vcpkg\vcpkg.user if it exists
2) $(LOCALAPPDATA)\vcpkg\vcpkg.user.props imports C:\vcpkg\scripts\buildsystems\msbuild\vcpkg.props if it exists ( I believe this file is created when you run vcpkg integrate install and points the generated file will contain the path of where you have vcpkg installed )
3)  vcpkg\scripts\buildsystems\msbuild\vcpkg.props dows all sorts of stuff like adding things to paths

Note a similar sequence happens for targets.

So to solve my issues I can do one of two things
1) Not run vcpkg integrate install and import C:\vcpkg\scripts\buildsystems\msbuild\vcpkg.props and vcpkg.targets in my project files
2) The import in $(LOCALAPPDATA)\vcpkg\vcpkg.user.props  is conditional on a poperty called VCPkgLocalAppDataDisabled. So I can set that to true for a given project and the imports won't happen.

It would be nice if the above was document somewhere.

My view is that using a combination of centralized packages and what vcpkg integrate install dows to MSBuild is extremely problematic. It may make it easier for first time users but it not scable and is brittle.

**Comment by JackBoosY** [comment]
@davidhunter22  Can you provide a scenario to prove that the integration of msbuild destroys the compilation environment?

**Comment by JackBoosY** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
