### ISSUE TITLE
Using --overlay-triplets seems to overwrite where built ports go?

### ISSUE THREAD

**Issue by jdx-john** [microsoft/vcpkg#18869]
I have custom manifest and triplet file so am testing building like this.
`vcpkg install --overlay-triplets=.\CFG --x-manifest-root=.\CFG --triplet=x86-windows-custom`
Everything built fine but after `integrate install` my projects are failing due to missing headers. They were building before and the triplet name hasn't changed.
It appears the ports are now built into .\CFG - I have a **.\CFG\vcpgk_installed** folder which appears to be identical to the expected .\installed directory.  It seems like this is a bug and I don't want it building into my custom directory!

I tried to fix this:
`vcpkg install --overlay-triplets=.\CFG --x-manifest-root=.\CFG --triplet=x86-windows-custom --vcpkg-root=".\"`

But then I got errors:

> The port directory (C:\github\microsoft\vcpkg\vcpkg\ports\gtest) does not exist
> Error: failed to load port from C:\github\microsoft\vcpkg\vcpkg\ports\gtest

Then I tried:

> C:\github\microsoft\vcpkg>vcpkg install --overlay-triplets=.\CFG --x-manifest-root=.\CFG --triplet=x86-windows-custom --vcpkg-root="./.."
> Error: invalid triplet: x64-windows
> 

Which made NO sense as an error.

Why is it trying to build into vcpkg\vcpkg? What is the correct way to workaround this?

**Comment by jdx-john** [comment]
So as a workaround I basically did:

copy vcpkg\CFG\vcpkg_installed vcpkg\installed

And things are working. But clearly this isn't ideal, given CFG will ultimately be on a totally different folder to vcpkg (it's part of our git repo)

**Comment by NancyLi1013** [comment]
Hi @jdx-john 

Thanks for posting this issue.

In manifest mode, the installed directory will be changed to `<manifest-root>/vcpkg_installed` by default. If want to change the install path, you can pass `--x-install-root=<path>
` .

Please see https://github.com/microsoft/vcpkg/blob/master/docs/users/manifests.md#--x-install-rootpath

**Comment by jdx-john** [comment]
@NancyLi1013 thanks I actually found this workaround last night but you posted before I could update :) 
Is this behaviour a bug, or intended functionality?

**Comment by NancyLi1013** [comment]
This is intended behavior. If you don't pass the argument, it will be installed to the default directory `<manifest-root>/vcpkg_installed `. This is optional, which depends on your requirement.

**Comment by jdx-john** [comment]
Thanks @NancyLi1013 I'll close this then. I will remind that `--x-manifest-root` is not documented on the command-line, in case anyone thinks it is worth addressing.

**Comment by NancyLi1013** [comment]
Thanks for your kindly reminder. Yes, there are many options that are not documented on the command-line. we might need to improve this in the future.
