### ISSUE TITLE
[New Port Request] gpmf-parser

### ISSUE THREAD

**Issue by ndurner** [microsoft/vcpkg#18871]
Library name: gpmf-parser

Library description: The GPMF structured storage format implementation for high-frequency periodic sensor data stored within a video file like an MP4

Source repository URL: https://github.com/gopro/gpmf-parser

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
