### ISSUE TITLE
[gsutil] update to 4.65

### ISSUE THREAD

**Issue by xavier2k6** [microsoft/vcpkg#18878]
Library name: gsutil

New version number: 4.65

Other information that may be useful (release notes, etc...)

`scripts/vcpkgTools.xml`

ref.:
https://storage.googleapis.com/pub/gsutil_4.65.ReleaseNotes.txt

**Comment by PhoebeHui** [comment]
Closing in favor of https://github.com/microsoft/vcpkg/issues/18815
