### ISSUE TITLE
[CMake] update to 3.20.5

### ISSUE THREAD

**Issue by xavier2k6** [microsoft/vcpkg#18879]
Library name: CMake (Kitware)

New version number: 3.20.5

Other information that may be useful (release notes, etc...)

ref.:
`scripts/vcpkgTools.xml`

**Comment by JackBoosY** [comment]
I think we should wait for 3.21 release.

**Comment by xavier2k6** [comment]
> I think we should wait for 3.21 release.

I thought alright with the small update & that 3.21 isn't that far away was a bit trivial.

Will I close?

**Comment by Neumann-A** [comment]
Also vote for 3.21 release. Otherwise all binary caches get invalidated.

**Comment by xavier2k6** [comment]
>I think we should wait for 3.21 release.

>Also vote for 3.21 release. Otherwise all binary caches get invalidated.

👍 

I will close/await CMake 3.21 Release.
