### ISSUE TITLE
[CI] Update Linux CI to Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#18882]
Reason: 
Qt6.2 cannot be build with gcc 7.5 used as a default within 18.04 due to constexpr constrains (Officially requires 9 but 8 also seems to work.)

Alternative:
 Add another Linux CI with 20.04.

**Comment by dg0yt** [comment]
FTR, gcc-8 is available for 18.04. (https://packages.ubuntu.com/source/bionic/gcc-8)

**Comment by Neumann-A** [comment]
Yeah but it needs to be setup as the default compiler.

**Comment by BillyONeal** [comment]
Closing as a  duplicate of https://github.com/microsoft/vcpkg/issues/13624
