### ISSUE TITLE
unable to execute any vcpkg commands

### ISSUE THREAD

**Issue by fawdlstty** [microsoft/vcpkg#18885]
**Describe the bug**
I was unable to execute any VCPKG commands

**Environment**
- OS: win10 20h2 (19042.1052)
- Compiler: vs2019 16.10.2

**To Reproduce**
1. any vcpkg command such as `vcpkg list`
2. See error
```
Database is corrupted: package cpprestsdk:x64-windows-static has features but no core paragraph.
Note: Updating vcpkg by rerunning bootstrap-vcpkg may resolve this failure.
```

**Expected behavior**
run

**Failure logs** 
no more logs

**Additional context**
no more

**Comment by fawdlstty** [comment]
I cleaned the buildtrees folder due to lack of disk space. Is that the reason?

**Comment by autoantwort** [comment]
maybe delete and clone vcpkg again. But probably you will run into disk space issues again

**Comment by dg0yt** [comment]
You can clean the `buildtrees` before starting to build a large package if disk storage is limited.
On "Database is corrupted" you need to clean `packages` and `installed`. They must stay in sync. The caching of binary artifacts should restore the directories quickly on next install.

**Comment by JonLiu1993** [comment]
@fawdlstty ,Have you tried the suggestions provided by the two above? Is this issue still a hindrance to you?

**Comment by fawdlstty** [comment]
I successfully solved the problem through the advice of dg0yt, but I am not sure whether this issue needs to be closed.  Because this problem seems to affect usage.

**Comment by JonLiu1993** [comment]
If this issue has been resolved, I will close this issue. If you have other issues, please reopen an issue. Thank you
