### ISSUE TITLE
[boost:x64-windows] build failure

### ISSUE THREAD

**Issue by Erxl** [microsoft/vcpkg#18888]
**Host Environment**
- OS: Windows
- Compiler: Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30130.2 for x64

**To Reproduce**
`./vcpkg install boost:x64-windows`

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

> PS C:\Users\Erxl> vcpkg install boost:x64-windows
> Computing installation plan...
> The following packages will be built and installed:
>     boost[core]:x64-windows -> 1.76.0
>   * boost-accumulators[core]:x64-windows -> 1.76.0
>   * boost-any[core]:x64-windows -> 1.76.0
>   * boost-asio[core]:x64-windows -> 1.76.0
>   * boost-assign[core]:x64-windows -> 1.76.0
>   * boost-beast[core]:x64-windows -> 1.76.0
>   * boost-bimap[core]:x64-windows -> 1.76.0
>   * boost-callable-traits[core]:x64-windows -> 1.76.0
>   * boost-compatibility[core]:x64-windows -> 1.76.0
>   * boost-compute[core]:x64-windows -> 1.76.0
>   * boost-context[core]:x64-windows -> 1.76.0
>   * boost-contract[core]:x64-windows -> 1.76.0
>   * boost-convert[core]:x64-windows -> 1.76.0
>   * boost-coroutine[core]:x64-windows -> 1.76.0
>   * boost-coroutine2[core]:x64-windows -> 1.76.0
>   * boost-crc[core]:x64-windows -> 1.76.0
>   * boost-date-time[core]:x64-windows -> 1.76.0
>   * boost-dll[core]:x64-windows -> 1.76.0
>   * boost-dynamic-bitset[core]:x64-windows -> 1.76.0
>   * boost-endian[core]:x64-windows -> 1.76.0
>   * boost-fiber[core]:x64-windows -> 1.76.0
>   * boost-flyweight[core]:x64-windows -> 1.76.0
>   * boost-foreach[core]:x64-windows -> 1.76.0
>   * boost-format[core]:x64-windows -> 1.76.0
>   * boost-geometry[core]:x64-windows -> 1.76.0
>   * boost-gil[core]:x64-windows -> 1.76.0
>   * boost-graph[core]:x64-windows -> 1.76.0
>   * boost-graph-parallel[core]:x64-windows -> 1.76.0
>   * boost-hana[core]:x64-windows -> 1.76.0
>   * boost-heap[core]:x64-windows -> 1.76.0
>   * boost-histogram[core]:x64-windows -> 1.76.0
>   * boost-hof[core]:x64-windows -> 1.76.0
>   * boost-icl[core]:x64-windows -> 1.76.0
>   * boost-interprocess[core]:x64-windows -> 1.76.0
>   * boost-iostreams[core]:x64-windows -> 1.76.0
>   * boost-json[core]:x64-windows -> 1.76.0
>   * boost-leaf[core]:x64-windows -> 1.76.0
>   * boost-local-function[core]:x64-windows -> 1.76.0
>   * boost-locale[core]:x64-windows -> 1.76.0
>   * boost-lockfree[core]:x64-windows -> 1.76.0
>   * boost-log[core]:x64-windows -> 1.76.0
>   * boost-math[core]:x64-windows -> 1.76.0
>   * boost-metaparse[core]:x64-windows -> 1.76.0
>   * boost-mp11[core]:x64-windows -> 1.76.0
>   * boost-msm[core]:x64-windows -> 1.76.0
>   * boost-multi-array[core]:x64-windows -> 1.76.0
>   * boost-multi-index[core]:x64-windows -> 1.76.0
>   * boost-multiprecision[core]:x64-windows -> 1.76.0
>   * boost-nowide[core]:x64-windows -> 1.76.0
>   * boost-odeint[core]:x64-windows -> 1.76.0
>   * boost-outcome[core]:x64-windows -> 1.76.0
>   * boost-parameter[core]:x64-windows -> 1.76.0
>   * boost-parameter-python[core]:x64-windows -> 1.76.0
>   * boost-pfr[core]:x64-windows -> 1.76.0
>   * boost-phoenix[core]:x64-windows -> 1.76.0
>   * boost-poly-collection[core]:x64-windows -> 1.76.0
>   * boost-polygon[core]:x64-windows -> 1.76.0
>   * boost-process[core]:x64-windows -> 1.76.0
>   * boost-program-options[core]:x64-windows -> 1.76.0
>   * boost-property-map[core]:x64-windows -> 1.76.0
>   * boost-property-tree[core]:x64-windows -> 1.76.0
>   * boost-proto[core]:x64-windows -> 1.76.0
>   * boost-ptr-container[core]:x64-windows -> 1.76.0
>   * boost-python[core]:x64-windows -> 1.76.0
>   * boost-qvm[core]:x64-windows -> 1.76.0
>   * boost-random[core]:x64-windows -> 1.76.0
>   * boost-safe-numerics[core]:x64-windows -> 1.76.0
>   * boost-scope-exit[core]:x64-windows -> 1.76.0
>   * boost-serialization[core]:x64-windows -> 1.76.0
>   * boost-signals2[core]:x64-windows -> 1.76.0
>   * boost-sort[core]:x64-windows -> 1.76.0
>   * boost-spirit[core]:x64-windows -> 1.76.0
>   * boost-stacktrace[core]:x64-windows -> 1.76.0
>   * boost-statechart[core]:x64-windows -> 1.76.0
>   * boost-static-string[core]:x64-windows -> 1.76.0
>   * boost-stl-interfaces[core]:x64-windows -> 1.76.0
>   * boost-test[core]:x64-windows -> 1.76.0
>   * boost-thread[core]:x64-windows -> 1.76.0
>   * boost-timer[core]:x64-windows -> 1.76.0
>   * boost-tokenizer[core]:x64-windows -> 1.76.0
>   * boost-tti[core]:x64-windows -> 1.76.0
>   * boost-type-erasure[core]:x64-windows -> 1.76.0
>   * boost-ublas[core]:x64-windows -> 1.76.0
>   * boost-units[core]:x64-windows -> 1.76.0
>   * boost-uuid[core]:x64-windows -> 1.76.0
>   * boost-variant[core]:x64-windows -> 1.76.0
>   * boost-variant2[core]:x64-windows -> 1.76.0
>   * boost-vmd[core]:x64-windows -> 1.76.0
>   * boost-wave[core]:x64-windows -> 1.76.0
>   * boost-xpressive[core]:x64-windows -> 1.76.0
>   * boost-yap[core]:x64-windows -> 1.76.0
>   * bzip2[core]:x64-windows -> 1.0.8#2
>   * expat[core]:x64-windows -> 2.4.1
>   * libffi[core]:x64-windows -> 3.3#9
>   * liblzma[core]:x64-windows -> 5.2.5#2
>   * openssl[core]:x64-windows -> 1.1.1k#6
>   * python3[core]:x64-windows -> 3.9.5#1
>   * sqlite3[core]:x64-windows -> 3.35.5
>   * zstd[core]:x64-windows -> 1.4.9
> Additional packages (*) will be modified to complete this operation.
> Warning: The following VS instances are excluded because the English language pack is unavailable.
>     C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
> Please install the English language pack.
> Detecting compiler hash for triplet x64-windows...
> -- Using HTTP(S)_PROXY in environment variables.
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\38\3894e50d2effa3be5c3dfed3a0673e37e0e11458892f486708557054f9032456.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\ff\ffc4affe2ac4038011b77983c1644ec7897ba90b624ca29d83b2caa1792fc199.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\8b\8bec77f35dbb9ac673a2984ca725e2de73ebc387789129d55b888eb241ee091d.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\23\2316dbf470cdae3adee29b2205c13675c704fde687c45203ee16e397d4da8505.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\2a\2a0802a3509e6a160f73cd20b18e00d012399e8713a0affe3cad86107062646b.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\77\7742ee50e842cd3e66d444a42d6a3ecd65fbc510892a917e9962ee5f132971de.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\90\90df0dc80138522133a925c65c1da3a48abb53ba9bda332f63d9064c398b6842.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\e1\e12ae45f0af8e5bdf17f4c3683ea6dfb7179e5bd6209addacee2682ae6e86af4.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\c2\c24366b88c32f086f1c194311bc5253cefbc0d8e55bd3cf0e84e7346b902edf3.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\43\434b33b2a0db5d4184638775c00491a2da3f471741ca429a92e8eac5f6af8669.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\7e\7e2e1c5bffc3f12a714e92ec741027e021e4951261600852562ff32c6bfe7029.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\26\26ebaa396498c475a868671a7585aa113e3c1300e8ed259e5fa4d272d08b2b74.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\62\62765e6041c71cf1f3e72f6b55e20e0302c1bc0a66298db8db064a76023110e9.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\10\10dc7b9e00f4542503dced7348e4d98ebf4ae5911ea1eeeb965e087c6ae983fa.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\47\473e5deaf7775ad8d3454eca5c90b42be51010d5a56dfb48e0e2d6b2af12a029.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\97\97f6bf90bb97594ac625ab7dcddd309301d51062c41a4ca4f4c57427ff8ad860.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\bf\bf16019c0e50adfcbc07ebbe5e97cf18a95077a28030bad7913de1439a23710b.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\53\53980832cdb457a98e8b22211e51db4cf91c1bf4b8be5cd87b62deac1304b783.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\b8\b8ad5afa27cc4fbfc1295eb54a41a5469e357c4acf6fafd351f726cd1ecfd9fd.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\d8\d8cbda073168fbcc8548d9cf8af60a866a46e5c293efb8435ab314a8aba1de25.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\36\3639fc34f19a03bba0f1c139a7b44bc5d5e5d90a45530ae84992b309b0a8e164.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\de\de8c7e2d3d20ca70a99bdea7c44e190138bb3a846d1e58d8a5de3f3f423040af.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\03\03f90b59605355145d81e22cb67b6066fc894ac9c17bb27f8f3f71f6a24bf08d.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\86\86c32934326ad71a41a666c7b644a76fc3e3bfab95f35ee128a477b1d1959e80.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\fc\fc8ed045438e742a078c981730d0110795ab8c0b9589e17ff9cb002040e41814.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\49\49ddb1e53838ebf71c7e224b6aa9e20773876481d3dbd983f34f46a015810d7e.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\9c\9c8cdbad79272e283f6293481e0b4609e7adfb25a342f480800bf716f064b991.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\df\df9b3274cbfc5dbedec20972a5682aa918e40ca742337e019cf8aa0daeb2575f.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\7f\7f6e74ec39e0ce77b268ca1085514bfb541ba9a4366da8498f53dd644d76dff6.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\2f\2ff7d1e08d02083a976ada098eed6d4ed7f091a0a563a2c17969016c3e7a9b36.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\9a\9aff635e49cf002f87b5a00aad2a65b093781f60c1792280561d98a0aa98e750.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\16\169dc17cbe80c5e67ffdbcb7397181e0cd52b67347d30aff6e48ac711e1437a3.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\ce\ce13e56c15d5a2bff4c8a27d53e6002c9853b310df2a92796b530f47609c46ff.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\0f\0f0f2a76fc7aff164c8a66004b4b3e2f7e55674ca5501d0b67828bc42258098a.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\86\8639214aeb970e42b213b3c8c97bc4c4e29fa822f7f3010a5d71247300697cf3.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\31\31dbc7f728cd48089a2a81b6c631296881f376c08de4db521d63387661801a48.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\a2\a2d64b3e19e26cc99e00d4d64cbba5b4344fb65e3d8cd77a240e71e1529ea28d.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\63\63ecbdedd90708d71bb57b0d0d5999a60bdcfe4be9bc881cfb386e676aa32749.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\55\557527de3c9ef905d9617770fa686ebe8384e86b677237a8dbc4c3b999840274.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\ff\ffa0dfb0a9edeb62b6ad8fdd6b615c908741ac5a203e351cf0f0b8bf91adc24c.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\6a\6a09b5bef1ebb42a1499cd1ba7a064dc387c322597748cf6e1dabda185500666.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\c2\c237005eb475def54a7520527be50fec9b55c4b96a22808455acd6ea6b18d3ec.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\28\2803a34bbb1bfacc11e0ed1495fe4e00276f834243fb8bbfbe26aaa796523ea3.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\3a\3a54483d6d377fe341d9165de78e9a031e3f3f52206005c8e2010b33aa80a75f.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\ce\ce00599fa91b7ed41b9a63aed1a14229d929e93e451addd998b09cd406ff15ac.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\c8\c8f70e469767c2e5bcd909c3c5e4f3086d6c44b5d3d42118d7a182406b48fa17.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\a5\a52979a2b8579c96650ed1f42b14d18e34f6b4782641a889c327ab44fa5ef1b5.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\6c\6cb1791eeb539c64438d3067cd2c6bcd36f90b34693af1d8b43795f936217f5b.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\31\3196fe0afef7ac6e2ef9d659abb8e876470c0c07454edd8acf0a22b521a635b2.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\1c\1cf8150b37f49eb48dec9b6c0f15e2d9b46da818804dc5dbc420c1ccd631b717.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\80\8085bc2994f8bf4e3cc1a10d45aed19524052e20e3ed4a1d8cd6fae546f1bae0.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\dc\dc470ca2a5e3711498bd8fc052db8efacfaee862d1f6f2583db7e7be1b633f0d.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\9e\9ebe5292f48f0d89b9a52be18ad9b9c9d863716aa83b074cee608f36971b50ec.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\df\dfbe341ffe66c454a5b9dbd5f0c5f866f54df0e55dd9b5d6be811ec21f9ae1df.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\76\76c2f71f15120bfccf5f11d9eec11f0d56aa01c6fb261f04fea9538b23bb1833.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\03\035684de68ed71fcb625a4b873adf6feebdb9e98a2259c173eb440f10dd3ccdb.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\c5\c576e2593b99d46febcc4822275f82fabea53203733a17c94cf126fdaa2fa646.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\99\99cfa38c404770d53a3fa12d60d137f98cdcb47b833f27428a617a5af3f11640.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\45\4516e6a51a358049d9571b8a0b12ff53b40b3f45ecd60c1b30b42b973736c69f.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\c4\c435d6ed09196a2a13896ab4c83b5093768748c66de486910a7073d157bd214a.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\12\12766f87e3b8f07c97fdc02717266a1afd95e2bf0f218d1a31eb62daec808bd9.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\0a\0aaa223c94ff96fcf011b30c419d46f328abcfd6f37b21209dcf917543d307ad.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\c2\c26fcd74166442a1f9c545107e1f5804500415c99771eaf446cc65d78f9811bf.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\6e\6e86bbfb9c303c26b04e264a9801278fa622533432f20972d91ad32baae95b53.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\7c\7c915d6ea97dcf3440c02d516667bca0489dc2cf70bcebaf1fc83db0e6e74c94.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\8b\8bee1526971b72fca89522749d1ad739df48808219967d0204d717ddc66c0937.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\b3\b3d0ae74df65ce80b608c8a75fd18904c9010b5c7fe561dc0d931ce705c026f2.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\23\236d044718d29dc0b9d299e876e4062d22cab77dfe4eae521ef8467a51856045.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\2a\2a3fd3317a72c1db6c5648770e4144cda36aa994bc78db623e620dfb4a152b5e.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\6f\6f52a7c75911c67284f2421c5a0952b37349a0ad10d2910201f55d269e380624.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\73\73b8a562b34ce77161cff6695890e8fb7a7f38a20dc105ed35d095cca040ff7c.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\e6\e659dee37f5bdeb437e3a9e4719013527347bf3c5486399858a1efb6cc2726c3.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\54\546388d9381212c438b4efa314b1be887ed7049b126cf726b5159386e86fd95e.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\c1\c1b97d30378705624705c31ddd920177cc92d681446bb23babafa364e4cefd69.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\91\917b4a3c7374d5aed4da60d2dd576cad27818ef2350349924c0065ee448e41ab.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\0b\0bfbedbec6d02215814f582acdcc070a4536170640b296ca88f9d96115947378.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\1e\1ea6489786d1de758bdf19b02a1030947219eb824b81a09b4ae76e3623594958.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\8b\8b549bebfeeed1ec9d834bd7303d79b718ddb5818fcb0d78577dc9c69d33b8b0.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\bd\bdfcb01e9a2695bf5cf43b1b86dcb28b2dd03ee1abe0869b0551dc9e1957be44.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\66\66d9cbe7723471ed5bbdddf8748cd7392960b9dff433e727f3e3392fd304bec7.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\29\2995176e72e64506d64534dd66c9e5f044e54568fe98213006036ee5ffed6bd7.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\33\335ac54aa3ac839ab58f9897db68e4ba635f912c20332fe2b7f8f362ce96ea55.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\71\71c2bc9437da86a7e0f6ad0d689f10803b06e4780edb7918808801a2d70c3803.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\10\10dd2121b3315c3120362815747983af80b76827a44ef38d82c4346af1206c25.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\9c\9c2563cd1916d0742d1f6cca42510443369eed521a77bcdf289dec28a783085c.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\c7\c7818cd461b04205de1410d4748ca12fb54f38e0ceb2dee470d005ffcdf32906.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\4f\4fddf053ed10f180d8caf22fe9b3403f099d1389bb01426ed8d20907a538c1f8.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\35\35ff34b485ac73f6079430145595ce2d95a131befd4fb982a6b68ac1cd712447.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\04\04b59605bbd9fa05b370bd4714979c6c92201c4257e3428deba6602f9cf39b9e.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\f6\f633dbc67435091af794ac43193b46bce6166e0d3d152e32c974b3af877b8a2f.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\a8\a8e250a0308e7f44b8c2475fd4ca0c5b10ec293ff9667f7ffc7d240874ba6d0c.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\ba\bac95762ab1d2a95f9c1fc87cabbdd9be2e8e84fcb4bbea86a83d3b443d6852b.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\c6\c6ad584cd645af9af128f6a393eefd20ba044195c396f8a53c32361d53732410.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\da\da7068a36c55b9b9c71b5255b26d50d462804a065cce37ff088bd49108897700.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\5f\5fca2ea73f06b4ceac130ecff86b1262b32d5983ddeb1076c047f78acb03a4f6.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\13\1367e3bad1dcd9d72121b2c0d7a296619029fb6a2f8b09de2b409dbde17ad867.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\5c\5c5d8f7a0960987ebd5f64338957230763eb14b492e27eccc53713ff75ed4a5b.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\22\2232d5592214dc7b97f3754808ce5d970b8694d0910661b638a31a2461faab82.zip
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\fd\fd6ab625cd36119c6bb09af33cf804fa5644d014e426f91a0bcf4a59bdc958b8.zip
> Starting package 1/99: boost-math:x64-windows
> Building package boost-math[core]:x64-windows...
> -- Downloading https://github.com/boostorg/math/archive/boost-1.76.0.tar.gz -> boostorg-math-boost-1.76.0.tar.gz...
> [DEBUG] Feature flag 'binarycaching' unset
> [DEBUG] Feature flag 'manifests' = off
> [DEBUG] Feature flag 'compilertracking' unset
> [DEBUG] Feature flag 'registries' unset
> [DEBUG] Feature flag 'versions' unset
> [DEBUG] Downloading https://github.com/boostorg/math/archive/boost-1.76.0.tar.gz
> Error: Failed to download from mirror set:
> https://github.com/boostorg/math/archive/boost-1.76.0.tar.gz: WinHttpQueryDataAvailable() failed: 12152
> 
> [DEBUG] C:\A\1\60\s\src\vcpkg\base\downloads.cpp(628)
> [DEBUG] Exiting after 31669051 us (31661177 us)
> 
> CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:240 (message):
> 
>       Failed to download file.
>       If you use a proxy, please check your proxy setting. Possible causes are:
> 
>       1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
>          to `https://address:port`. This is not correct, because `https://` prefix
>          claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
>          , etc..) is an HTTP proxy. Try setting `http://address:port` to both
>          HTTP_PROXY and HTTPS_PROXY instead.
> 
>       2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
>          will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
>          Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
>          Change `http=address:port;https=address:port` to `address`, and fill the port number.
> 
>       3. You proxy's remote server is out of service.
> 
>       In future vcpkg releases, if you are using Windows, you no longer need to set
>       HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
>       Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
>       and (https://github.com/microsoft/vcpkg-tool/pull/77)
> 
>       Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues
> 
> Call Stack (most recent call first):
>   scripts/cmake/vcpkg_from_github.cmake:147 (vcpkg_download_distfile)
>   ports/boost-math/portfile.cmake:3 (vcpkg_from_github)
>   scripts/ports.cmake:139 (include)
> 
> 
> Error: Building package boost-math:x64-windows failed with: BUILD_FAILED
> Please ensure you're using the latest portfiles with `.\vcpkg update`, then
> submit an issue at https://github.com/Microsoft/vcpkg/issues including:
>   Package: boost-math:x64-windows
>   Vcpkg version: 2021-05-05-e8977e69d9a3fb462d9ad42013d83a7682706659
> 
> Additionally, attach any relevant sections from the log files above.
> PS C:\Users\Erxl>

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by mathisloge** [comment]
Are you behind a proxy? 
If yes, have you followed the error message? 
```
  Failed to download file.
  If you use a proxy, please check your proxy setting. Possible causes are:

  1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
     to `https://address:port`. This is not correct, because `https://` prefix
     claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
     , etc..) is an HTTP proxy. Try setting `http://address:port` to both
     HTTP_PROXY and HTTPS_PROXY instead.

  2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
     will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
     Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
     Change `http=address:port;https=address:port` to `address`, and fill the port number.

  3. You proxy's remote server is out of service.

  In future vcpkg releases, if you are using Windows, you no longer need to set
  HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
  Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
  and (https://github.com/microsoft/vcpkg-tool/pull/77)

  Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues


```

**Comment by drink-crow** [comment]
I have same problem. i use proxy clash with tun mode but i can install other package example freetype. also can download package in firefox with proxy

**Comment by drink-crow** [comment]
> 
> 
> I have same problem. i use proxy clash with tun mode but i can install other package example freetype. also can download package in firefox with proxy

I repair this problem. It seem that update vcpkg by `git pull` but not run `.\bootstrap-vcpkg.bat` again cause this problem. I run  `.\bootstrap-vcpkg.bat` and install go ahead

**Comment by PhoebeHui** [comment]
@Erxl, could you try above suggestions and see if it works for you?

**Comment by Erxl** [comment]
> @Erxl, could you try above suggestions and see if it works for you?

I have compiled successfully, but I don't know why

**Comment by PhoebeHui** [comment]
@Erxl, glad it works for you now, it may due to the changes https://github.com/microsoft/vcpkg-tool/pull/49 in latest source.
