### ISSUE TITLE
[llvm] build failure

### ISSUE THREAD

**Issue by Erxl** [microsoft/vcpkg#18884]
**Host Environment**
- OS: Windows
- Compiler: Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30130.2 for x64

**To Reproduce**
`./vcpkg install llvm:x64-windows`

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

> C:\Users\Erxl>vcpkg install llvm:x64-windows
> Computing installation plan...
> The following packages will be built and installed:
>     llvm[clang,compiler-rt,core,default-options,default-targets,disable-abi-breaking-checks,disable-assertions,disable-clang-static-analyzer,enable-bindings,enable-terminfo,enable-threads,enable-zlib,lld,target-x86,tools]:x64-windows -> 12.0.0
> Warning: The following VS instances are excluded because the English language pack is unavailable.
>     C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
> Please install the English language pack.
> Detecting compiler hash for triplet x64-windows...
> Could not locate cached archive: C:\Users\Erxl\AppData\Local\vcpkg\archives\3b\3b1d9c380c72c1ed67240a06d7ad10afe3916b70581a6cb9ded56714ecfaba3a.zip
> Starting package 1/1: llvm:x64-windows
> Building package llvm[clang,compiler-rt,core,default-options,default-targets,disable-abi-breaking-checks,disable-assertions,disable-clang-static-analyzer,enable-bindings,enable-terminfo,enable-threads,enable-zlib,lld,target-x86,tools]:x64-windows...
> -- Note: llvm only supports static library linkage. Building static library.
> -- Downloading https://github.com/llvm/llvm-project/archive/llvmorg-12.0.0.tar.gz -> llvm-llvm-project-llvmorg-12.0.0.tar.gz...
> -- Extracting source C:/Program Files/vcpkg/downloads/llvm-llvm-project-llvmorg-12.0.0.tar.gz
> -- Applying patch 0002-fix-install-paths.patch
> -- Applying patch 0003-fix-openmp-debug.patch
> -- Applying patch 0004-fix-dr-1734.patch
> -- Applying patch 0005-fix-tools-path.patch
> -- Applying patch 0007-fix-compiler-rt-install-path.patch
> -- Applying patch 0008-fix-libcxx-install.patch
> -- Applying patch 0009-fix-tools-install-path.patch
> -- Applying patch 0010-fix-libffi.patch
> -- Applying patch 0011-fix-libxml2.patch
> -- Using source at C:/Program Files/vcpkg/buildtrees/llvm/src/org-12.0.0-511e760473.clean
> -- Downloading https://www.python.org/ftp/python/3.9.5/python-3.9.5-embed-amd64.zip -> python-3.9.5-embed-amd64.zip...
> -- Found external ninja('1.10.2').
> -- Configuring x64-windows
> -- Building x64-windows-dbg
> CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:146 (message):
>     Command failed: "C:/Program Files/vcpkg/downloads/tools/cmake-3.20.2-windows/cmake-3.20.2-windows-i386/bin/cmake.exe" --build . --config Debug --target install -- -v -j9
>     Working Directory: C:/Program Files/vcpkg/buildtrees/llvm/x64-windows-dbg
>     See logs for more information:
>       C:\Program Files\vcpkg\buildtrees\llvm\install-x64-windows-dbg-out.log
> 
> Call Stack (most recent call first):
>   scripts/cmake/vcpkg_build_cmake.cmake:104 (vcpkg_execute_build_process)
>   scripts/cmake/vcpkg_install_cmake.cmake:44 (vcpkg_build_cmake)
>   ports/llvm/portfile.cmake:238 (vcpkg_install_cmake)
>   scripts/ports.cmake:139 (include)
> 
> 
> Error: Building package llvm:x64-windows failed with: BUILD_FAILED
> Please ensure you're using the latest portfiles with `.\vcpkg update`, then
> submit an issue at https://github.com/Microsoft/vcpkg/issues including:
>   Package: llvm:x64-windows
>   Vcpkg version: 2021-05-05-e8977e69d9a3fb462d9ad42013d83a7682706659
> 
> Additionally, attach any relevant sections from the log files above.

[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/6790816/install-x64-windows-dbg-out.log)

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by NancyLi1013** [comment]
Hi @Erxl 

Thanks for posting this issue.

`C:\Program Files\vcpkg\buildtrees\llvm\src\org-12.0.0-511e760473.clean\llvm\include\llvm\DebugInfo\PDB\DIA\DIASupport.h(25): fatal error C1083: Cannot open include file: 'atlbase.h': No such file or directory`

Since `atlbase.h` is listed in this directory.
`C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.23.28105\atlmfc\include\atlbase.h`

Could you please try to install the ATL components corresponding to your build tools version via Visual Studio Installer?
Please see https://github.com/microsoft/vcpkg/issues/15987#issuecomment-771409245.

**Comment by NancyLi1013** [comment]
Please feel free to reopen this issue if it is still a problem for you after you installed ATL components.
