### ISSUE TITLE
Why is `search` so slow?

### ISSUE THREAD

**Issue by jdx-john** [microsoft/vcpkg#18886]
I am routinely finding `vcpkg search` to take >10s, sometimes nearer 30s. Is this normal and is there a reason why it is so slow?
I was under the impression search only looked at the local ports list, though that may be totally wrong.

**Comment by autoantwort** [comment]
Are you using a custom registry or only the default one?

**Comment by jdx-john** [comment]
I'm not sure I understand the question so I assume the default, it's basically a stock installation

**Comment by autoantwort** [comment]
Ok hm, yeah maybe your file system is slow, because it reads 1500 files every time you search. How fast is for example `grep -r zlib ports`

**Comment by JonLiu1993** [comment]
@jdx-john ,This issue has nothing to do with vcpkg. I use vcpkg search locally, the default search is less than 5S, and the specified port search is less than 2s. This may be related to your local equipment. I will close this issue and reopen it if you have new information

**Comment by jdx-john** [comment]
If you are expecting it to take several seconds, it's maybe not that bad on my PC - I had expected it would be virtually instant, iterating a list of ports?
Thanks for the input.

**Comment by JonLiu1993** [comment]
> If you are expecting it to take several seconds, it's maybe not that bad on my PC - I had expected it would be virtually instant, iterating a list of ports?
> Thanks for the input.

Yes,So don’t worry too much about this
