### ISSUE TITLE
How can I add a package such as `imgui[glfw-binding]` as a dependency to my project's `vcpkg.json` manifest?

### ISSUE THREAD

**Issue by lalilulelost** [microsoft/vcpkg#18893]
I know manifest mode is currently in beta, but I've been trying it out for my Visual Studio 2019 MSBuild project (on Windows 10 21H1). The latest `git tag` in my vcpkg install folder is `2021.05.12`.

The `vcpkg.json` manifest file with all the dependencies for my project looks like this:

```
{
  "name": "gl-engine",
  "version": "0.0.1",
  "dependencies": [
    "glfw3",
    "glad",
    "imgui",
    "imgui[glfw-binding]",
    "glm",
    "entt",
    "assimp"
  ]
}
```

Upon running `vcpkg install` inside the project folder, I get this error: 
```
Errors occurred while parsing C:\code\vcpkg-manifest-test\vcpkg.json
    $.dependencies[3] (a dependency): must be lowercase alphanumeric+hyphens, split with periods, and not reserved
See https://github.com/Microsoft/vcpkg/tree/master/docs/users/manifests.md for more information.
```
The name `imgui[glfw-binding]` seems to break the constraints for dependency [`<package-name>`](https://github.com/microsoft/vcpkg/blob/master/docs/specifications/manifests.md#definitions)s , so I can't quite build the project in manifest mode. Using classic mode, the dependency does install correctly with `vcpkg install imgui[glfw-binding]`, and indeed the whole project builds without using manifest mode. 

Is there currently some way to use this kind of package name in a manifest file, or is support for such names simply not available yet in any way?

**Comment by mathisloge** [comment]
Manifest dependency features are listed as followed: 
see https://github.com/microsoft/vcpkg/blob/master/docs/users/manifests.md for more information

```json

{
  ...
  "dependencies": [
    ...
    {
            "name": "imgui",
            "features": [
                "glfw-binding"
            ]
     },
    ...
  ]
}

```

**Comment by lalilulelost** [comment]
> Manifest dependency features are listed as followed:
> see [https://github.com/microsoft/vcpkg/blob/master/docs/users/manifests.md](https://github.com/microsoft/vcpkg/blob/master/docs/users/manifests.md?rgh-link-date=2021-07-10T12%3A40%3A20Z) for more information

Thank you very much! I wasn't aware that names listed with square brackets were _features_, will read the documentation more carefully next time, hahah. I'm still having trouble getting the project to build, but as far as adding `<name>[<feature>]` dependencies, the issue is solved, I can run `vcpkg install` successfully.
