### ISSUE TITLE
vcpkg does not consider supported architectures when selecting a Visual Studio instance

### ISSUE THREAD

**Issue by thespivey** [microsoft/vcpkg#18890]
On machines that have multiple versions of Visual Studio installed (Community + Enterprise), with x86/x64 tools in both but ARM tools only installed in the Enterprise instance, vcpkg will select the Community edition for an arm build and then fail.

```
-- Running vcpkg install
Detecting compiler hash for triplet x64-windows...
Detecting compiler hash for triplet arm-uwp...
Error: Unsupported toolchain combination.
Target was arm but the chosen Visual Studio instance supports:
    x86, amd64, x86_amd64, amd64_x86
Vcpkg selected C:\Program Files (x86)\Microsoft Visual Studio\2019\Community as the Visual Studio instance.
Detected instances:
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
```    

Removing the x86/x64 tools from the Community install will cause vcpkg to select the Enterprise edition instead and build successfully.

**Comment by JackBoosY** [comment]
@vicroms what do you think about?

**Comment by vicroms** [comment]
@JackBoosY 
I'll take a look at the issue this week
