### ISSUE TITLE
[New Port Request] <Mediapipe c++>

### ISSUE THREAD

**Issue by bobluoluo** [microsoft/vcpkg#18894]
Library name: mediapipe

Library description: Cross-platform, customizable ML solutions for live and streaming media

Source repository URL: https://github.com/google/mediapipe

Project homepage (if different from the source repository): https://google.github.io/mediapipe/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.

**Comment by ilongshan** [comment]
Hope it can be added to vcpkg

**Comment by sfhacker** [comment]
This issue is from 2021!
