### ISSUE TITLE
[intel-mkl] build failure using GitHub Actions (MSBuild based project)

### ISSUE THREAD

**Issue by rogerfraser** [microsoft/vcpkg#18896]
**Host Environment**
- OS: Windows via GitHub Action ([msvc_build.yml](https://github.com/rogerfraser/DynAdjust/blob/master/.github/workflows/msvc_build.yml))
  ```yaml
  env:
    BUILD_CONFIGURATION: Release
    ARCH: x64

  jobs:
    build:
      runs-on: windows-latest
  ...
  
  ```
  
- Compiler: MSBuild (supplied by GitHub Actions virtual environments)
  ```yaml
  steps:
  ...

  - name: Add MSBuild to PATH
    uses: microsoft/setup-msbuild@v1.0.2  
    
  ...
  
  ```

**To Reproduce**
```yaml
- name: Install vcpkg prerequisites
  shell: cmd
  if: steps.cache.outputs.cache-hit != 'true'
  run: |
    vcpkg update
    vcpkg install intel-mkl --triplet=${{env.ARCH}}-windows
    vcpkg ...
    vcpkg integrate install
    vcpkg list
    
  ...
  
  ```

**Failure logs** 
- See full log [here](https://github.com/rogerfraser/DynAdjust/runs/3034571347?check_suite_focus=true).

```txt
Run vcpkg update
  vcpkg update
  vcpkg install intel-mkl --triplet=x64-windows
  shell: C:\Windows\system32\cmd.EXE /D /E:ON /V:OFF /S /C "CALL "{0}""
  env:
    SOLUTION_FILE_PATH: ./dynadjust/dynadjust_1_01_00.sln
    BUILD_CONFIGURATION: Release
    ARCH: x64
    VCPKG_INSTALL_FOLDER: c:/vcpkg/installed
    CS_XSD_INSTALL_FOLDER: xsd/xsd-4.0.0-i686-windows/libxsd
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.
Computing installation plan...
The following packages will be built and installed:
    intel-mkl[core]:x64-windows -> 2020.0.0
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\runneradmin\AppData\Local\vcpkg\archives\f8\f8e99c4db6108860ec37bb79c9bbdbbc05a34887cc655ec8fcd3a7400f38d72b.zip
Starting package 1/1: intel-mkl:x64-windows
Building package intel-mkl[core]:x64-windows...
CMake Error at ports/intel-mkl/portfile.cmake:15 (message):
  Could not find MKL.  Before continuing, please download and install MKL
  (20200000 or higher) from:

      https://registrationcenter.intel.com/en/products/download/3178/

  

  Also ensure vcpkg has been rebuilt with the latest version (v0.0.104 or
  later)
Call Stack (most recent call first):
  scripts/ports.cmake:139 (include)


Error: Building package intel-mkl:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: intel-mkl:x64-windows
  Vcpkg version: 2021-05-05-b110959e13f562c2a17d7bd9e352e2dd8d6dc603

Additionally, attach any relevant sections from the log files above.
Error: Process completed with exit code 1.
```

**Additional context**
- Successful build of the repo requires other packages (e.g. boost-*, 7zip, xerces-c, etc.).   Installation of these packages (e.g. `vcpkg install boost-process ... --triplet=${{env.ARCH}}-windows`) is successful. 
- Caching was originally applied, then removed, but neither cases were successful.
- Full yaml [here](https://github.com/rogerfraser/DynAdjust/blob/master/.github/workflows/msvc_build.yml).

**Comment by autoantwort** [comment]
What is the question? 
```
CMake Error at ports/intel-mkl/portfile.cmake:15 (message):
  Could not find MKL.  Before continuing, please download and install MKL
  (20200000 or higher) from:

      https://registrationcenter.intel.com/en/products/download/3178/

```

**Comment by Neumann-A** [comment]
https://github.com/oneapi-src/oneapi-ci

**Comment by rogerfraser** [comment]
Thanks @autoantwort. 

As this yaml is for a Windows-based workflow using MSBuild, the expected behaviour (as per [docs](https://github.com/microsoft/vcpkg/blob/master/docs/examples/installing-and-using-packages.md)) is:
- vcpkg automatically downloads and builds intel-mkl using VC20xx (via `vcpkg install intel-mkl ...`)
- vcpkg automatically adds intel-mkl include directories, link directories and libraries to VC20xx  (via `vcpkg integrate install`)

Looking at the vcpkg error message, the issue seems to be that vcpkg cannot find/build/install intel-mkl, yet it is a supported port.  For example, the following yaml:
``` yaml
run: |
  vcpkg update
  vcpkg search intel-mkl
```
gives:

``` txt
No packages need updating.
intel-mkl                2020.0.0         Intel® Math Kernel Library (Intel® MKL) accelerates math processing rout...
```

As this is a GitHub Action, there is no previous installation of intel-mkl (as per #3322 and #13050).

The question is - Why is vcpkg unable to automatically download, build and install intel-mkl using MSBuild on a Windows-based workflow?

Thanks again.

**Comment by autoantwort** [comment]
The first line of the file `ports/intel-mkl/portfile.cmake` says:
```
# Due to the complexity involved, this package doesn't install MKL. It instead verifies that MKL is installed.
```

But the descriptions should definitely mention that.

**Comment by rogerfraser** [comment]
Thanks @autoantwort. If there is no future plan for this package to install MKL, I'm happy for this issue to be closed.

Yes, a description that notifyies users of vcpkg ports that aren't automatically installed would be very beneficial for future users.

Thanks again.

**Comment by NancyLi1013** [comment]
Hi @rogerfraser 

Thanks for posting this issue.

For `interl-mkl`, vcpkg just detects if `MKL `is installed. So you need to install `MKL `manually, then rebuild this.

**Comment by NancyLi1013** [comment]
Since there are also other ports have the same cases with `intel-mkl`. And there is also the information described in portfile.cmake:
 `# Due to the complexity involved, this package doesn't install MKL. It instead verifies that MKL is installed.`

So I think it's unnecessary to mention this in description field.

**Comment by autoantwort** [comment]
> And there is also the information described in portfile.cmake:
> `# Due to the complexity involved, this package doesn't install MKL. It instead verifies that MKL is installed.`
> 
> So I think it's unnecessary to mention this in description field.


But nobody reads the portfile.cmake. And why should you as normal user?

**Comment by PhoebeHui** [comment]
I think adding the information to description field is fine. @NancyLi1013, could you please submit a PR to add that information?
