### ISSUE TITLE
etcd-cpp-apiv3:x64-windows build failure

### ISSUE THREAD

**Issue by zjmnssy** [microsoft/vcpkg#18901]
**Host Environment**
- OS: windows 10
- Compiler: Vcpkg version: 2021-05-05-e8977e69d9a3fb462d9ad42013d83a7682706659

**To Reproduce**
vcpkg install etcd-cpp-apiv3:x64-windows

**Failure logs** 
D:\third_party\vcpkg>vcpkg install etcd-cpp-apiv3:x64-windows
Computing installation plan...
The following packages will be built and installed:
    etcd-cpp-apiv3[core]:x64-windows -> 0.2.1
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\z\AppData\Local\vcpkg\archives\1d\1d4690500cc8cc25f53c954091805479fe2290c0d7f2edfa855fa73eca80b0e8.zip
Starting package 1/1: etcd-cpp-apiv3:x64-windows
Building package etcd-cpp-apiv3[core]:x64-windows...
-- Using D:/third_party/vcpkg/downloads/etcd-cpp-apiv3-etcd-cpp-apiv3-v0.2.1.tar.gz
-- Cleaning sources at D:/third_party/vcpkg/buildtrees/etcd-cpp-apiv3/src/v0.2.1-85b6180791.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/third_party/vcpkg/downloads/etcd-cpp-apiv3-etcd-cpp-apiv3-v0.2.1.tar.gz
-- Using source at D:/third_party/vcpkg/buildtrees/etcd-cpp-apiv3/src/v0.2.1-85b6180791.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:146 (message):
    Command failed: D:/third_party/vcpkg/downloads/tools/cmake-3.20.2-windows/cmake-3.20.2-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j17
    Working Directory: D:/third_party/vcpkg/buildtrees/etcd-cpp-apiv3/x64-windows-dbg
    See logs for more information:
      D:\third_party\vcpkg\buildtrees\etcd-cpp-apiv3\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:104 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:44 (vcpkg_build_cmake)
  ports/etcd-cpp-apiv3/portfile.cmake:18 (vcpkg_install_cmake)
  scripts/ports.cmake:139 (include)

Error: Building package etcd-cpp-apiv3:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: etcd-cpp-apiv3:x64-windows
  Vcpkg version: 2021-05-05-e8977e69d9a3fb462d9ad42013d83a7682706659

Additionally, attach any relevant sections from the log files above.

**Additional context**
nothing i can find to do

**Comment by dg0yt** [comment]
There is no `etcd-cpp-apiv3` in https://github.com/microsoft/vcpkg. But you can check the build log as suggested in the output:
~~~
See logs for more information:
D:\third_party\vcpkg\buildtrees\etcd-cpp-apiv3\install-x64-windows-dbg-out.log
~~~

**Comment by zjmnssy** [comment]
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/6795233/install-x64-windows-dbg-out.log)

**Comment by mathisloge** [comment]
`Cannot open include file: 'boost/asio/io_context.hpp' ` 
have you installed `boost-asio``?

**Comment by zjmnssy** [comment]
i will check later, but i use vcpkg to build, i think it will aotu download and install the dependence

**Comment by PhoebeHui** [comment]
@zjmnssy, it seems boost-asio has been installed but the version is too old, you need execute './vcpkg remove boost-uninstall --recurse', and install boost-asio again.

**Comment by zjmnssy** [comment]
when i use 'vcpkg install etcd-cpp-apiv3:x64-windows' it will auto install boost, but i found it will not install boost-asio, does boost-asio need i manual to install?
![2021-07-12_101547](https://user-images.githubusercontent.com/21244667/125221322-a43b8e80-e2fa-11eb-9bc6-296b82d73c43.jpg)

**Comment by zjmnssy** [comment]
i clean vcpkg , then install etcd-cpp-apiv3:x64-windows, but it out a new error that not appeared, the buildtrees\etcd-cpp-apiv3\config-x64-windows-out.log like blow:

[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/6798237/config-x64-windows-out.log)

it look like pthread.h - not found, but i have install pthread module in VS install path.

**Comment by zjmnssy** [comment]
ok, it build success,  i first install boost manual, then install etcd-cpp-apiv3:x64-windows. but at the build result output, i only find DLL and include files , not found lib files.

**Comment by PhoebeHui** [comment]
@zjmnssy, I didn't find a etcd-cpp-apiv3 port in vcpkg, I'm not sure what's happning, glad it build successfully for you now.
Do you consider to submit a PR for the port?

**Comment by zjmnssy** [comment]
@PhoebeHui 
you can copy 
https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/tree/master/vcpkg/etcd-cpp-apiv3
into your vcpkg/ports
then, you can begin build

**Comment by sighingnow** [comment]
The original error has been fixed after adding `boost-asio` to the dependency list.

**Comment by zjmnssy** [comment]
i found a other problem, after build success, i use the output DLL files, but exe always load dll failed, it said not found the module, so does the build dll is not available？

**Comment by zjmnssy** [comment]
i let the dll and exe at the same directory, but also load failed, then i use dll analyse exe to see what in the dll files, the dll file can't be open , said it a invalid dll file. @sighingnow

**Comment by qugang** [comment]
> 我让dll和exe在同一个目录下，但也加载失败，然后我用dll分析exe查看dll文件中的内容，dll文件无法打开，说是一个输入的dll文件。@sighingnow

Solve it? I also encountered the same problem!

**Comment by sighingnow** [comment]
Hi @qugang and @zjmnssy,

I don't have a test environment with QT to verify the problem, but I believe the following code works, where the `etcd-cpp-api.dll`, as well as its dependencies are all in `PATH`.

Maybe you folks could use this alternative for your purpose?

```cpp
// A simple program that uses LoadLibrary and 
// GetProcAddress to access myPuts from Myputs.dll. 
 
#include <windows.h> 
#include <stdio.h> 
 
typedef int (__cdecl *MYPROC)(LPWSTR); 
 
int main(int argc, char **argv) 
{ 
    HINSTANCE hinstLib; 
    MYPROC ProcAdd; 
    BOOL fFreeResult, fRunTimeLinkSuccess = FALSE; 
 
    if (argc == 1) {
        printf("Usage: win-dll-load.exe <library path>\n");
        return EXIT_FAILURE;
    }

    // Get a handle to the DLL module.
    hinstLib = LoadLibrary(TEXT(argv[1])); 
 
    // If the handle is valid, try to get the function address.
 
    if (hinstLib != NULL) { 
        printf("load the library successfully\n");
        // Free the DLL module.
        fFreeResult = FreeLibrary(hinstLib);
        return EXIT_FAILURE;
    } else {
        printf("failed to load the library\n");
        return EXIT_SUCCESS;
    }
}
```

**Comment by qugang** [comment]
changge CMakeLists.txt 29 lines option(BUILD_SHARED_LIBS "Build shared libraries" OFF)
copy etcd-cpp-api.lib to vcpkg\installed\x64-windows\debug\lib
After recompiling, solve the problem!

windows need lib and dll or use LoadLibrary and GetProcAddress load dll

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue and continue the PR, but we're closing it for now, consider making a pull request instead.
