### ISSUE TITLE
[New Port Request] GTSAM

### ISSUE THREAD

**Issue by mans0987** [microsoft/vcpkg#18904]
Library name: GTSAM

Library description: 
GTSAM 4.0 is a BSD-licensed C++ library that implements sensor fusion for robotics and computer vision applications, including SLAM (Simultaneous Localization and Mapping), VO (Visual Odometry), and SFM (Structure from Motion). It uses factor graphs and Bayes networks as the underlying computing paradigm rather than sparse matrices to optimize for the most probable configuration or an optimal plan. Coupled with a capable sensor front-end (not provided here), GTSAM powers many impressive autonomous systems, in both academia and industry.

Source repository URL:  https://github.com/borglab/gtsam

Project homepage (if different from the source repository):
https://gtsam.org/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
