### ISSUE TITLE
[boost-regex]error including 

### ISSUE THREAD

**Issue by cocaocla** [microsoft/vcpkg#18900]
Error: Building package boost-regex:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-regex:x86-windows
  Vcpkg version: 2021-05-05-e8977e69d9a3fb462d9ad42013d83a7682706659

Additionally, attach any relevant sections from the log files above.

update comand not work

C:\Users\domin\vcpkg>vcpkg update
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.

**Comment by mathisloge** [comment]
could you attach the build err log file?

**Comment by JonLiu1993** [comment]
@cocaocla ,Thanks for posting this issue, could you please attach the build err log file?

**Comment by PhoebeHui** [comment]
@cocaocla, please reopen this issue and attach full failure logs if it still be a problem for you.
