### ISSUE TITLE
Failed to take the filesystem lock on /opt/src/vcpkg/.vcpkg-root after vcpkg install --feature-flags=manifests

### ISSUE THREAD

**Issue by acgetchell** [microsoft/vcpkg#18903]
**Describe the bug**
`vcpkg install --feature-flags=manifests` fails to work due to a lock

**Environment**
- OS:Linux
- Compiler: gcc 9.2.1

**To Reproduce**
1. ./vcpkg install feature-flags=manifests
2. Failed to take the filesystem lock on /opt/src/vcpkg/.vcpkg-root

**Expected behavior**
Expect vcpkg to build and install packages

**Failure logs** 
https://lgtm.com/projects/g/acgetchell/CDT-plusplus/logs/languages/lang:cpp

**Additional context**
https://github.com/acgetchell/CDT-plusplus/blob/develop/.lgtm.yml

**Comment by autoantwort** [comment]
Then another vcpkg process is running that is holding the lock

**Comment by JackBoosY** [comment]
Can you please provide the output with command `ps aux | grep vcpkg`?

**Comment by JackBoosY** [comment]
Ping @acgetchell for response.

**Comment by acgetchell** [comment]
I just got to this and It started working again 2 days ago, so thanks for your attention!

https://lgtm.com/projects/g/acgetchell/CDT-plusplus/logs/languages/lang:cpp
