### ISSUE TITLE
[New Port Request] <EventBus>

### ISSUE THREAD

**Issue by liubin3071** [microsoft/vcpkg#18913]
Library name:EventBus

Library description:

Source repository URL:https://github.com/gelldur/EventBus

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.

**Comment by ilongshan** [comment]
Hope it canbe add this port
