### ISSUE TITLE
CMake fails to find vcpkg.json file

### ISSUE THREAD

**Issue by fishnet37222** [microsoft/vcpkg#18928]
**Describe the bug**
When using vcpkg with CMake, CMake fails to find the "vcpkg.json" file.

**Environment**
- OS: Windows
- Compiler: Visual Studio 2019
- CMake: 3.19.2

**To Reproduce**
1. Create a CMake project
2. Place a vcpkg.json file in the project's root directory
3. Build the project

**Expected behavior**
Any dependencies defined in the manifest will be downloaded and installed into the project.

**Failure logs** 
```
C:\Users\Dave\AppData\Local\JetBrains\Toolbox\apps\CLion\ch-0\211.7628.27\bin\cmake\win\bin\cmake.exe -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=c:/vcpkg/scripts/buildsystems/vcpkg.cmake -G "CodeBlocks - NMake Makefiles" C:\Users\Dave\CLionProjects\Minesweeper
CMake Error at C:/vcpkg/scripts/buildsystems/vcpkg.cmake:814 (message):
  vcpkg manifest mode was enabled, but we couldn't find a manifest file
  (vcpkg.json)

  in the current source directory (C:/Users/Dave/CLionProjects/Minesweeper).

  Please add a manifest, or disable manifests by turning off
  VCPKG_MANIFEST_MODE.
Call Stack (most recent call first):
  cmake-build-debug/CMakeFiles/3.19.2/CMakeSystem.cmake:6 (include)
  CMakeLists.txt:3 (project)


-- Configuring incomplete, errors occurred!
See also "C:/Users/Dave/CLionProjects/Minesweeper/cmake-build-debug/CMakeFiles/CMakeOutput.log".

[Failed to reload]
```
[CMakeOutput.log](https://github.com/microsoft/vcpkg/files/6808681/CMakeOutput.log)

**Additional context**
The attached log was generated by including "set(VCPKG_MANIFEST_MODE ON)" in the CMakeLists.txt file.  If that line is not included, then the build fails with the log included below.

```
C:\Users\Dave\AppData\Local\JetBrains\Toolbox\apps\CLion\ch-0\211.7628.27\bin\cmake\win\bin\cmake.exe -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=c:/vcpkg/scripts/buildsystems/vcpkg.cmake -G "CodeBlocks - NMake Makefiles" C:\Users\Dave\CLionProjects\Minesweeper
CMake Error at C:/Users/Dave/AppData/Local/JetBrains/Toolbox/apps/CLion/ch-0/211.7628.27/bin/cmake/win/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
  Could NOT find wxWidgets (missing: wxWidgets_LIBRARIES
  wxWidgets_INCLUDE_DIRS net gl core base webview)
Call Stack (most recent call first):
  C:/Users/Dave/AppData/Local/JetBrains/Toolbox/apps/CLion/ch-0/211.7628.27/bin/cmake/win/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:582 (_FPHSA_FAILURE_MESSAGE)
  C:/Users/Dave/AppData/Local/JetBrains/Toolbox/apps/CLion/ch-0/211.7628.27/bin/cmake/win/share/cmake-3.19/Modules/FindwxWidgets.cmake:1016 (find_package_handle_standard_args)
  C:/vcpkg/scripts/buildsystems/vcpkg.cmake:771 (_find_package)
  CMakeLists.txt:8 (find_package)


-- Configuring incomplete, errors occurred!
See also "C:/Users/Dave/CLionProjects/Minesweeper/cmake-build-release/CMakeFiles/CMakeOutput.log".

[Failed to reload]

```

Here is a screenshot showing the contents of the project's root directory.  As you can see, the "vcpkg.json" file exists.
![image](https://user-images.githubusercontent.com/1977106/125450159-eb84e836-2dab-4d30-b487-afa33d19d95e.png)

I get the same behavior when I use VSCode and Visual Studio.

**Comment by JackBoosY** [comment]
Please note that the manifest file must be placed in the same level directory as the top-level `CMakeLists.txt`.
Once vcpkg detects its existence, it will automatically turn on manifest mode.
And also, please make sure your vcpkg is latest and rerun bootstrap again.

**Comment by fishnet37222** [comment]
The manifest file is at the same level directory as the top-level `CMakeLists.txt`.  I made sure I have the latest vcpkg and ran the bootstrap batch file again.  The issue still remains.

I've attached a sample project that reproduces the issue.
[Minesweeper.zip](https://github.com/microsoft/vcpkg/files/6813131/Minesweeper.zip)

**Comment by JackBoosY** [comment]
I can't repro this issue on the same directory locally, can you provide the Visual Studio version?

**Comment by JackBoosY** [comment]
cc @strega-nil-ms

**Comment by fishnet37222** [comment]
Microsoft Visual Studio Professional 2019
Version 16.10.3
VisualStudio.16.Release/16.10.3+31424.327
Microsoft .NET Framework
Version 4.8.04161

Installed Version: Professional

Visual C++ 2019   00435-60000-00000-AA402
Microsoft Visual C++ 2019

I created the project using JetBrains CLion, but the issue occurs with VSCode and Visual Studio itself.  The issue does not occur when I use vcpkg with an MSBuild project.

**Comment by JackBoosY** [comment]
@fishnet37222  Can you also please provide the cmake version?

**Comment by fishnet37222** [comment]
The version of CMake that CLion uses is 3.19.2.  When I try with VSCode, the version of CMake being used is 3.20.5.

**Comment by PhoebeHui** [comment]
@fishnet37222, as a workaround, could you pass -DVCPKG_MANIFEST_DIR="C:/Users/Dave/CLionProjects/Minesweeper" and see if it works for you?

See https://github.com/microsoft/vcpkg/blob/master/scripts/buildsystems/vcpkg.cmake#L53, I suspect it doesn't get CMAKE_SOURCE_DIR correctly.

**Comment by fishnet37222** [comment]
Passing that variable to CMake gets rid of the error and allows the dependencies to be downloaded and installed.

**Comment by strega-nil-ms** [comment]
@fishnet37222 could you `message(STATUS "${CMAKE_SOURCE_DIR}")` in your CMake file, above the project() line? I wanna see what's going on.

**Comment by fishnet37222** [comment]
I get the following output when I add that line.  I did modify the line slightly to make it more obvious.

```
[main] Configuring folder: Minesweeper 
[driver] Removing c:/Users/Dave/source/repos/Minesweeper/build/CMakeCache.txt
[driver] Removing c:\Users\Dave\source\repos\Minesweeper\build\CMakeFiles
[proc] Executing command: "C:\Program Files\CMake\bin\cmake.EXE" --no-warn-unused-cli -DCMAKE_TOOLCHAIN_FILE:STRING= -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -Hc:/Users/Dave/source/repos/Minesweeper -Bc:/Users/Dave/source/repos/Minesweeper/build -G "Visual Studio 16 2019" -T host=x64 -A x64
[cmake] Not searching for unused variables given on the command line.
[cmake] -- CMAKE_SOURCE_DIR = C:/Users/Dave/source/repos/Minesweeper
[cmake] -- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.22000.
[cmake] -- The C compiler identification is MSVC 19.29.30038.1
[cmake] -- The CXX compiler identification is MSVC 19.29.30038.1
[cmake] -- Detecting C compiler ABI info
[cmake] -- Detecting C compiler ABI info - done
[cmake] -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.29.30037/bin/Hostx64/x64/cl.exe - skipped
[cmake] -- Detecting C compile features
[cmake] -- Detecting C compile features - done
[cmake] -- Detecting CXX compiler ABI info
[cmake] -- Detecting CXX compiler ABI info - done
[cmake] -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.29.30037/bin/Hostx64/x64/cl.exe - skipped
[cmake] -- Detecting CXX compile features
[cmake] -- Detecting CXX compile features - done
[cmake] CMake Error at C:/Program Files/CMake/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
[cmake]   Could NOT find wxWidgets (missing: wxWidgets_LIBRARIES
[cmake]   wxWidgets_INCLUDE_DIRS net gl core base webview)
[cmake] Call Stack (most recent call first):
[cmake]   C:/Program Files/CMake/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
[cmake]   C:/Program Files/CMake/share/cmake-3.20/Modules/FindwxWidgets.cmake:1025 (find_package_handle_standard_args)
[cmake]   CMakeLists.txt:9 (find_package)
[cmake] 
[cmake] 
[cmake] -- Configuring incomplete, errors occurred!
[cmake] See also "C:/Users/Dave/source/repos/Minesweeper/build/CMakeFiles/CMakeOutput.log".

```

**Comment by strega-nil-ms** [comment]
@fishnet37222 are you listing the right source directory? The screenshot you attached is not of the directory that that CMake is showing.

**Comment by PhoebeHui** [comment]
@fishnet37222, could you add 'message(STATUS "${CMAKE_SOURCE_DIR}")' in your cmake file, and execute the cmake commands without passing  '-DVCPKG_MANIFEST_DIR', I think Nicole wants to confirm if CMAKE_SOURCE_DIR gets correctly when it failed at the beginning.

The above looks like another instance and is different source diretory from original problem.

**Comment by fishnet37222** [comment]
I guess you can close this issue now.  I just did another `git pull` in the vcpkg folder and ran the bootstrap file again.  I then deleted the CMake cache and reconfigured the project.  All the dependencies started building and installing as expected.  I don't know what changed, but something must have because clearing the cache wasn't resolving the issue earlier.

**Comment by moliqingwa** [comment]
I have the same issue on Mac using Clion. Here's the variable printed:

VCPKG_MANIFEST_DIR=/Users/xxxxx/code/git/robotics/easySim
Z_VCPKG_HAS_MANIFEST_DIR=ON
VCPKG_MANIFEST_MODE=OFF
