### ISSUE TITLE
vcpkg keeps keeps trying different package of different name than indicated

### ISSUE THREAD

**Issue by marekyggdrasil** [microsoft/vcpkg#18929]
**Describe the bug**

I have tried to install `secp256k1-zkp` but there is no such port (which is ok, not subject of this issue). Later I tried to install `mio` and it keeps trying to install `secp256k1-zkp`.

```
$ ./vcpkg install mio
Computing installation plan...
Error: while loading secp256k1-zkp:
The port directory (/home/marek/open-source/vcpkg/ports/secp256k1-zkp) does not exist
Error: failed to load port from /home/marek/open-source/vcpkg/ports/secp256k1-zkp
Note: Updating vcpkg by rerunning bootstrap-vcpkg may resolve this failure.
```

however, it let's me `search` for `mio`

```
$ ./vcpkg search mio
mio                      2019-02-10       Cross-platform header-only C++11 library for memory mapped file IO.

If your library is not listed, please open an issue at and/or consider making a pull request:
    https://github.com/Microsoft/vcpkg/issues
```

**Environment**
- OS: Linux, Debian 10
- Compiler: CMake-3.21.0-rc3

**To Reproduce**

1. `./vcpkg install secp256k1-zkp` and expect to fail
2. `./vcpkg search mio` should give info about `mio` port
3. `./vcpkg install mio` keeps trying to install `secp256k1-zkp`

**Expected behavior**

The `install` command should be installing `mio` and not `secp256k1-zkp`.

**Failure logs** 

I only have console output, but if someone requests content of some log file I am not aware of I will attach.

**Additional context**

N/A

**Comment by autoantwort** [comment]
I don't know if it was fixed, but normally vcpkg crashes with cmake 21. Maybe it triggers undefined behavior and wants to install random packages. Can you maybe try it with cmake 20?

**Comment by marekyggdrasil** [comment]
@autoantwort thank you for your suggestion! To be honest I don't really want to mess with my environment on that machine as I am still learning to setup those things and I am worried I might break it. Just out of curiosity, does `vcpkg` store some sort of state somewhere? While I run `./vcpkg install mio` it has to somehow remember that previously I attempted to install `secp256k1-zkp`.

Actually my problem has been resolved https://github.com/GrinPlusPlus/GrinPlusPlus/issues/173#issuecomment-879191978 as I found different way to install all the dependencies.

If the problem is not relevant for the community and development feel free to close the issue.

**Comment by NancyLi1013** [comment]
@marekyggdrasil 
`secp256k1-zkp` is not in vcpkg.  You might have installed it on your machine before. But you removed the files on `ports/secp256k1-zkp`. So it will fail to find the port when you install other ports in vcpkg lists. You can run `./vcpkg remove secp256k1-zkp`, then try to rebuild other ports.

**Comment by NancyLi1013** [comment]
@marekyggdrasil 

Is this still a problem for you?

**Comment by marekyggdrasil** [comment]
For me no problem, I have linked my solution comment above. I'll take the liberty to close this issue and worst-case-scenario someone might re-open it. Thanks again for help!
