### ISSUE TITLE
[colmap] build failure

### ISSUE THREAD

**Issue by pik314** [microsoft/vcpkg#18925]
**Host Environment**
- OS: Windows Server 2019 standard
- Compiler:  Compiler Version 19.00.24215.1 for x86 

**To Reproduce**
`./vcpkg install colmap[cuda-redist]:x64-windows`

**Failure logs** 
-- Using HTTP(S)_PROXY in environment variables.
Could not locate cached archive: C:\Users\XXXX28\AppData\Local\vcpkg\archives\7f\7f3224a2d3ff4d5db2056d7a1255ed9949fbe31bfb0ea462bffb3d6442735df2.zip
Could not locate cached archive: C:\Users\XXXX28\AppData\Local\vcpkg\archives\df\df5fe40c7abd208b2c4004aed9d17efcf85b81d0154cb3c908485bd61b68eeee.zip
Could not locate cached archive: C:\Users\XXXX28\AppData\Local\vcpkg\archives\35\35603a7415cb58d4ad59d1d81ab7f962dfd1fbcf4522321a2d2d7e8880b5b563.zip
Could not locate cached archive: C:\Users\XXXX28\AppData\Local\vcpkg\archives\c7\c74bae7c2cfce0e0390a3eebee26e8baf4519b32bbd9bfe581bc7e8f4f40593f.zip
Could not locate cached archive: C:\Users\XXXX28\AppData\Local\vcpkg\archives\38\38a64b0979e5822269f2a763525df23e5514a6cdd0fd43681c2c77a596583c2e.zip
Could not locate cached archive: C:\Users\XXXX28\AppData\Local\vcpkg\archives\15\156c95ea182551db9b4b69d9b50f1d0479f2834329b14f2c60f2d93a93932e62.zip
Could not locate cached archive: C:\Users\XXXX28\AppData\Local\vcpkg\archives\db\dbf2ed143b83f37b40e463ba1fa96be92ef1aab18a37f054c734d7e5ece3a825.zip
.....

**Additional context**
Proxy settings are correct. Not using Fiddler. Remote server is working.

**Comment by NancyLi1013** [comment]
Hi @pik314 

Thanks for posting this issue.

Could you please help provide the full log on your machine when you run `./vcpkg install colmap[cuda-redist]:x64-windows`?

```
PS F:\latest\vcpkg> ./vcpkg install colmap[cuda-redist]:x64-windows --editable
Computing installation plan...
The following packages will be built and installed:
    colmap[core,cuda-redist]:x64-windows -> 3.6#1
Starting package 1/1: colmap:x64-windows
Building package colmap[core,cuda-redist]:x64-windows...
-- Downloading https://github.com/colmap/colmap/archive/3.6.tar.gz -> colmap-colmap-3.6.tar.gz...
-- Extracting source F:/latest/vcpkg/downloads/colmap-colmap-3.6.tar.gz
-- Applying patch fix-dependency-freeimage.patch
-- Using source at F:/latest/vcpkg/buildtrees/colmap/src/3.6-f2a7f88123
-- Found external ninja('1.10.2').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: F:/latest/vcpkg/packages/colmap_x64-windows/share/colmap/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package colmap[core,cuda-redist]:x64-windows... done
Installing package colmap[core,cuda-redist]:x64-windows...
Installing package colmap[core,cuda-redist]:x64-windows... done
Elapsed time for package colmap:x64-windows: 1.872 h

Total elapsed time: 1.872 h
```

**Comment by pik314** [comment]
Hi, Thank you for responding. Below is the full log of the command 

.\vcpkg install colmap [cuda,tests]:x64-windows 

in Windows server 2019 . I have replaced my user name on the machine with XXXXXX. Proxy settings are correctand I am not using Fiddler.

Thank you for looking into this.

========================================
[vcpkg_install_colmap_error.txt](https://github.com/microsoft/vcpkg/files/6824366/vcpkg_install_colmap_error.txt)

**Comment by pik314** [comment]
Closed by mistake. Sorry.

**Comment by pik314** [comment]
It seems the issue is with libjpeg-turbo. Below is the log of the install command for jpeg-turbo
[vcpkg_install_jpeg-turbo.txt](https://github.com/microsoft/vcpkg/files/6824538/vcpkg_install_jpeg-turbo.txt)

**Comment by NancyLi1013** [comment]
```
[DEBUG] Downloading https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win32/nasm-2.15.05-win32.zip
[DEBUG] Downloading https://fossies.org/windows/misc/nasm-2.15.05-win32.zip
Error: Failed to download from mirror set:
https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win32/nasm-2.15.05-win32.zip: failed: status code 403
https://fossies.org/windows/misc/nasm-2.15.05-win32.zip: failed: status code 403

[DEBUG] C:\A\1\60\s\src\vcpkg\base\downloads.cpp(628)
[DEBUG] Exiting after 211836 us (166903 us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:251 (message):
```
Could you please help confirm if you have access to `https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win32/nasm-2.15.05-win32.zip` or `https://fossies.org/windows/misc/nasm-2.15.05-win32.zip`?

If yes, please download it manually, and put this archive to _C:/Projects/colmap/vcpkg/downloads_ folder. Then try to rebuild this.

**Comment by pik314** [comment]
This fixed this particular problem. Thank you! The first URL was blocked by the company firewall, but the second one wasn't and I was able to download the zip file. Atfer that the installation proceeded without problems.
