### ISSUE TITLE
[fmt] build failure

### ISSUE THREAD

**Issue by JosipNizetic** [microsoft/vcpkg#18934]
**Host Environment**
- OS: MacOs Big Surr 11.4
- Compiler:  The CXX compiler identification is AppleClang 11.0.0.11000033

**To Reproduce**
./vcpkg install fmt:x64-osx

**Failure logs** 
Josi-4266:vcpkg Josip$ ./vcpkg install fmt:x64-osx
Computing installation plan...
The following packages will be built and installed:
    fmt[core]:x64-osx -> 7.1.3#5
Detecting compiler hash for triplet x64-osx...
Could not locate cached archive: /Users/Josip/.cache/vcpkg/archives/e9/e961ec543058668bb550a99b1cf0db5303608ffe1edd9bb39f3474b9eea4f28d.zip
Starting package 1/1: fmt:x64-osx
Building package fmt[core]:x64-osx...
-- Using /Users/Josip/vcpkg/downloads/fmtlib-fmt-7bdf0628b1276379886c7f6dda2cef2b3b374f0b.tar.gz
-- Cleaning sources at /Users/Josip/vcpkg/buildtrees/fmt/src/2b3b374f0b-01bcd63221.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /Users/Josip/vcpkg/downloads/fmtlib-fmt-7bdf0628b1276379886c7f6dda2cef2b3b374f0b.tar.gz
-- Applying patch fix-warning4189.patch
-- Applying patch fix-write-batch.patch
-- Using source at /Users/Josip/vcpkg/buildtrees/fmt/src/2b3b374f0b-01bcd63221.clean
-- Configuring x64-osx-dbg
-- Configuring x64-osx-rel
-- Building x64-osx-dbg
-- Building x64-osx-rel
-- Installing: /Users/Josip/vcpkg/packages/fmt_x64-osx/share/fmt/copyright
CMake Error at scripts/cmake/vcpkg_find_acquire_program.cmake:535 (message):
  Could not find pkg-config.  Please install it via your package manager:

      brew install pkg-config
Call Stack (most recent call first):
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:116 (vcpkg_find_acquire_program)
  ports/fmt/portfile.cmake:46 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:139 (include)

Error: Building package fmt:x64-osx failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: fmt:x64-osx
  Vcpkg version: 2021-05-05-unknownhash

Additionally, attach any relevant sections from the log files above.

**Additional context**

**Comment by autoantwort** [comment]
You have to install `pkg-config` via brew with `brew install pkg-config` as suggested in the error message ;)

**Comment by JosipNizetic** [comment]
Yes that  was right direction. I gave up too easy:-) 

I needed to used following three lines 

```
cd /usr/local/Homebrew/Library/Taps/homebrew/
rm -rf homebrew-core
git clone https://github.com/Homebrew/homebrew-core.git
```
to be able o use

`  brew install pkg-config`

Now it works..

Thank you very much
