### ISSUE TITLE
installing any build failure windows 11 and windows 10

### ISSUE THREAD

**Issue by jaysonpowers** [microsoft/vcpkg#18935]
On OS Windows 11 dev build, and Windows 10 latest
Compiler: VS 2019 latest community
CMake: latest

tested on fltk and glm, glew, glad

git clone https://github.com/microsoft/vcpkg
.\vcpkg\bootstrap-vcpkg.bat
`C:\dev>.\vcpkg\vcpkg install fltk

Computing installation plan...
NOTHING
C:\dev>`

Nothing happens.

Checked using Windows Terminal - Powershell
and Vanilla command prompt.

A search shows the packages and it says nothing is installed.

**Comment by autoantwort** [comment]
Duplicate of #18636: Don't use cmake 21, use cmake 20.x :)

**Comment by NancyLi1013** [comment]
Hi @jaysonpowers 

Thanks for posting this issue. Could you please help confirm if you used cmake 3.21?

**Comment by jaysonpowers** [comment]
Yes, I was using CMake 3.21, I'll go ahead and install 3.20, thanks!

**Comment by jaysonpowers** [comment]
It's working fine now, thank you very much!
