### ISSUE TITLE
[icu:arm-android] build failure

### ISSUE THREAD

**Issue by mathisloge** [microsoft/vcpkg#18941]
**Host Environment**
- OS: Windows 10 -> Android
- cmake: 3.18.1
- Android Studio:
```
Bumblebee | 2021.1.1 Canary 3
Build #AI-211.7442.40.2111.7518594, built on July 2, 2021
Runtime version: 11.0.10+0-b96-7249189 amd64
VM: OpenJDK 64-Bit Server VM by Oracle Corporation
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 24
Registry: external.system.auto.import.disabled=true
```

**To Reproduce**

It's my first time building something for android. 
I've used the vcpkg-android.cmake example from the docs and modified it to work with android studio. 
https://github.com/mathisloge/tangram-es/blob/vcpkg-example/cmake/vcpkg_android.cmake

Root cmake project: https://github.com/mathisloge/tangram-es/tree/vcpkg-example

The easiest way to reproduce would be to clone  https://github.com/mathisloge/tangram-es/tree/vcpkg-example and open `platforms/android` with android studio and build.

**Failure logs** 

Execution line: 

`C:\Users\mathi\AppData\Local\Android\Sdk\cmake\3.18.1\bin\cmake.exe with arguments {-HD:\dev\tangram-es -DCMAKE_CXX_FLAGS=-std=c++14 -fvisibility=hidden -pedantic -fPIC -fexceptions -frtti -Wl,--exclude-libs,ALL -Wall -Wignored-qualifiers -Wtype-limits -Wno-missing-field-initializers -Wno-format-pedantic -Wno-gnu-statement-expression -Wno-gnu-anonymous-struct -Wno-nested-anon-types -Wno-unused-command-line-argument -Wno-unknown-warning-option -g -DCMAKE_FIND_ROOT_PATH=D:\dev\tangram-es\platforms\android\tangram\.cxx\cmake\debug\prefab\armeabi-v7a\prefab -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=C:\Users\mathi\AppData\Local\Android\Sdk\ndk\21.4.7075529\build\cmake\android.toolchain.cmake -DANDROID_ABI=armeabi-v7a -DANDROID_NDK=C:\Users\mathi\AppData\Local\Android\Sdk\ndk\21.4.7075529 -DANDROID_PLATFORM=android-16 -DCMAKE_ANDROID_ARCH_ABI=armeabi-v7a -DCMAKE_ANDROID_NDK=C:\Users\mathi\AppData\Local\Android\Sdk\ndk\21.4.7075529 -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=D:\dev\tangram-es\platforms\android\tangram\build\intermediates\cmake\debug\obj\armeabi-v7a -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=D:\dev\tangram-es\platforms\android\tangram\build\intermediates\cmake\debug\obj\armeabi-v7a -DCMAKE_MAKE_PROGRAM=C:\Users\mathi\AppData\Local\Android\Sdk\cmake\3.18.1\bin\ninja.exe -DCMAKE_SYSTEM_NAME=Android -DCMAKE_SYSTEM_VERSION=16 -DTANGRAM_PLATFORM=android -DANDROID_STL=c++_shared -DVCPKG_TARGET_ANDROID=ON -BD:\dev\tangram-es\platforms\android\tangram\.cxx\cmake\debug\armeabi-v7a -GNinja}
`

```
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
    Command failed: --noprofile --norc --debug -c " ./../src/c-69_1-src-78c1b28057.clean/source/configure  --disable-samples" --disable-tests --disable-layoutex --with-cross-build=D:/dev/tangram-es/platforms/android/tangram/.cxx/cmake/debug/armeabi-v7a/vcpkg_installed/x64-windows/tools/icu --disable-silent-rules --verbose --disable-shared "--enable-static --enable-debug" --disable-release --prefix=/D/dev/tangram-es/platforms/android/tangram/.cxx/cmake/debug/armeabi-v7a/vcpkg_installed/arm-android/debug --bindir='${prefix}'/../tools/icu/debug/bin --sbindir='${prefix}'/../tools/icu/debug/sbin --includedir='${prefix}'/../include --datarootdir='${prefix}'/share/icu
    Working Directory: D:/dev/tangram-es/vcpkg/buildtrees/icu/arm-android-dbg
    Error code: Das System kann die angegebene Datei nicht finden
    See logs for more information:

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:811 (vcpkg_execute_required_process)
  buildtrees/versioning/versions/icu/07e8fca3896a13ac7b4196e104015174429a6c74/portfile.cmake:49 (vcpkg_configure_make)
  scripts/ports.cmake:139 (include)


Error: Building package icu:arm-android failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: icu:arm-android
  Vcpkg version: 2021-05-05-e8977e69d9a3fb462d9ad42013d83a7682706659

Additionally, attach any relevant sections from the log files above.
-- Running vcpkg install - failed
-- Configuring incomplete, errors occurred!

vcpkg_android.cmake: VCPKG_TARGET_TRIPLET was set to arm-android
vcpkg_android.cmake: ANDROID_NDK_HOME was set to C:/Users/mathi/AppData/Local/Android/Sdk/ndk/21.4.7075529
vcpkg_android.cmake: CMAKE_TOOLCHAIN_FILE was set to D:/dev/tangram-es/vcpkg/scripts/buildsystems/vcpkg.cmake
vcpkg_android.cmake: VCPKG_CHAINLOAD_TOOLCHAIN_FILE was set to C:\Users\mathi\AppData\Local\Android\Sdk\ndk\21.4.7075529\build\cmake\android.toolchain.cmake
CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:835 (message):
  vcpkg install failed.  See logs for more information:
  D:\dev\tangram-es\platforms\android\tangram\.cxx\cmake\debug\armeabi-v7a\vcpkg-manifest-install.log
Call Stack (most recent call first):
  C:/Users/mathi/AppData/Local/Android/Sdk/cmake/3.18.1/share/cmake-3.18/Modules/CMakeDetermineSystem.cmake:93 (include)
  CMakeLists.txt:19 (project)
```

unfortunately there aren't more error locks. 

@autoantwort pointed on discord out, that there might be a missing executable in `Command failed: --noprofile` that should be something like `Command failed: bash.exe --noprofile`

**Comment by mathisloge** [comment]
This might be related to 
https://github.com/microsoft/vcpkg/pull/15605 and https://github.com/microsoft/vcpkg/issues/15255

**Comment by holmescn** [comment]
When the PR #21847 merged, this issue could be closed.

**Comment by m-kuhn** [comment]
> When the PR #21847 merged, this issue could be closed.

Tested, confirmed

**Comment by FrankXie05** [comment]
Duplicated to PR #21847

**Comment by mathisloge** [comment]
@FrankXie05 I don't feel like closing a issue before a PR is merged is the right decision. Because this issue is only *resolved*  when the PR is *merged*. And since it is open since december 2021 it might be better to not close it.

**Comment by mathisloge** [comment]
It will be autoclosed since it is linked :) 
Thanks for reopening 💯

**Comment by LilyWangLL** [comment]
This issue hasn’t been updated in 3 months, if someone could fix this issue, please reopen it.
