### ISSUE TITLE
"Error: invalid triplet: x64-windows" when using custom triplet and --overlay-triplet

### ISSUE THREAD

**Issue by jdx-john** [microsoft/vcpkg#18948]
I have created a custom triplet in a separate directory:

`C:\github\microsoft>vcpkg\vcpkg install magic-enum --overlay-triplets=c:\triplets --triplet=x64-windows-vs2019
`
```
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_PLATFORM_TOOLSET "v142")
set(VCPKG_DEP_INFO_OVERRIDE_VARS "v142")
set(VCPKG_BUILD_TYPE release)
```

I get the error in the title:

> Error: invalid triplet: x64-windows
> Available architecture triplets
> VCPKG built-in triplets:
> 
> VCPKG community triplets:
> 
> Overlay triplets from C:\triplets:
>   vcpkg
>   x64-windows-vs2019-static
>   x64-windows-vs2019
>   x86-windows-vs2019-static
>   x86-windows-vs2019

 This seems to suggest that it is for some reason using default x64 triplet in part. If I run from inside vcpkg directory it builds but I do see installed\x64-windows directory created.

Is this a bug? I can copy my custom triplets into the triplet dir I suppose but that masks the problem only.

**Comment by autoantwort** [comment]
That's strange, are there files in vcpkg/triplets?

**Comment by jdx-john** [comment]
Yes all the normal ones. OK If I forget my custom triplet:

> 
> C:\github\microsoft>vcpkg\vcpkg install magic-enum --triplet=x64-windows
> Error: invalid triplet: x64-windows
> Available architecture triplets
> VCPKG built-in triplets:
> 
> VCPKG community triplets:

I am guessing you have to run vcpkg in it's own directory for it to find the default triplets, whereas --overlay-triplets explicitly sets them. This might be intended functionality, but my bigger concern is why x64-windows is being built at all. It _seems_ that in installed\x64-windows I only have some tools and helper files, so possibly a false alarm.

**Comment by autoantwort** [comment]
Yeah `x64-windows` is the "host" triplet. If you for example build boost, you need the b2 executable, but not for your target platform, but for your host platform

**Comment by dg0yt** [comment]
The host triplet is also used for some pure cmake helper scripts such as the one providing `vcpkg_cmake_configure`.

**Comment by jdx-john** [comment]
I've set my custom triplet to be release-only, but it's building x64-windows-dbg as well as x64-windows-rel for these required parts. But this clears up one part of my question.

So then how can I use overlay-triplets as I wish? Can I separately specify host and target triplet overlay-paths or whatever? I want my custom triplets to be in my own repository but I don't want to copy vcpkg's own triplets into my repo. Am I missing a setting or is this not quite possible?

**Comment by NancyLi1013** [comment]
@jdx-john
Is this custom triplet listed in _C:\triplets\x64-windows-vs2019.cmake_? Do you use overlay-triplets on your own repo? If possible, could you please help tell us what special for your repo?

I can build successfully on my machine with` .\vcpkg.exe install magic-enum --overlay-triplets=F:\custom-triplets --triplet=x64-windows-vs2019`.

`x64-windows-vs2019.cmake` is in _F:\custom-triplets\x64-windows-vs2019.cmake_.

```
PS F:\new\vcpkg> .\vcpkg.exe install magic-enum --overlay-triplets=F:\custom-triplets --triplet=x64-windows-vs2019
Computing installation plan...
The following packages will be built and installed:
    magic-enum[core]:x64-windows-vs2019 -> 0.7.3
Detecting compiler hash for triplet x64-windows-vs2019...
Could not locate cached archive: C:\Users\Nancy\AppData\Local\vcpkg\archives\b5\b5872723e2d1e2e00d64141d96af74f87a3832bddc11b35a905c89521c17d0d6.zip
Starting package 1/1: magic-enum:x64-windows-vs2019
Building package magic-enum[core]:x64-windows-vs2019...
-- [OVERLAY] Loading triplet configuration from: F:\custom-triplets\x64-windows-vs2019.cmake
-- Using F:/new/vcpkg/downloads/Neargye-magic_enum-v0.7.3.tar.gz
-- Extracting source F:/new/vcpkg/downloads/Neargye-magic_enum-v0.7.3.tar.gz
-- Using source at F:/new/vcpkg/buildtrees/magic-enum/src/v0.7.3-f7a403c6d5.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows-vs2019
-- Building x64-windows-vs2019-rel
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\Nancy\AppData\Local\vcpkg\archives\b5\b5872723e2d1e2e00d64141d96af74f87a3832bddc11b35a905c89521c17d0d6.zip
Building package magic-enum[core]:x64-windows-vs2019... done
Installing package magic-enum[core]:x64-windows-vs2019...
Installing package magic-enum[core]:x64-windows-vs2019... done
Elapsed time for package magic-enum:x64-windows-vs2019: 3.523 s

Total elapsed time: 8.754 s

The package magic-enum:x64-windows-vs2019 provides CMake targets:

    find_package(magic_enum CONFIG REQUIRED)
    target_link_libraries(main PRIVATE magic_enum::magic_enum)
```

**Comment by NancyLi1013** [comment]
@jdx-john 

Is this still a problem for you now?
