### ISSUE TITLE
How do I build DLLs from vcpkg into `CPack`ed installer?

### ISSUE THREAD

**Issue by SamuelMarks** [microsoft/vcpkg#18943]
> The [`cpack`](https://cmake.org/cmake/help/latest/manual/cpack.1.html) executable is the CMake packaging program. It generates installers and source packages in a variety of formats.

I'm using `cpack -G WIX -C Debug` on my [SamuelMarks/cmake-example-with-vcpkg](https://github.com/SamuelMarks/cmake-example-with-vcpkg). Which produces a nice installer, but it doesn't copy/install `zlibd1.dll` (from `vcpkg`).

How is this meant to work?

**Comment by jakoch** [comment]
Hey! 
Copying the dependencies automatically is still experimental, but you can try setting `X_VCPKG_APPLOCAL_DEPS_INSTALL` to ON.
That should copy dependencies into the install target directory for executables. 

Add to `CMakeLists.txt`:
```
    # X_VCPKG_APPLOCAL_DEPS_INSTALL depends on CMake policy CMP0087 and requires CMake 3.14
    if(POLICY CMP0087)
        cmake_policy(SET CMP0087 NEW)
    endif()

    set(X_VCPKG_APPLOCAL_DEPS_INSTALL ON)
```

Referencing: https://github.com/Microsoft/vcpkg/issues/1653 + https://github.com/microsoft/vcpkg/issues/16557

**Comment by SamuelMarks** [comment]
Thanks I added that but it didn't copy the DLLs over. Is it CPack compatible?

**Comment by dg0yt** [comment]
CPack relies on CMake install comands and additional staging directories. I have no ideas if this works with vcpkg's staging, install, and applocal install. For cross-platform deployment of DLLs without vcpkg, I normally use CMake's BundleUtilities. IIUC parts of these functions now even became part of the `file` command (https://cmake.org/cmake/help/latest/command/file.html#get-runtime-dependencies).

**Comment by SamuelMarks** [comment]
@dg0yt Yes I tried that approach https://gitlab.kitware.com/cmake/cmake/-/issues/22431 https://gitlab.kitware.com/cmake/cmake/-/issues/22006

**Comment by JackBoosY** [comment]
> Thanks I added that but it didn't copy the DLLs over. Is it CPack compatible?

Did you run cmake install command?

**Comment by dg0yt** [comment]
> > Thanks I added that but it didn't copy the DLLs over. Is it CPack compatible?
> 
> Did you run cmake install command?

CPack *is* running cmake install.

> it doesn't copy/install `zlibd1.dll` (from `vcpkg`).

- Note that the wrapper for zlib is missing, https://github.com/microsoft/vcpkg/pull/18914, which may cause some strange effects.
- If not using a multi-config generator, don't let `CMAKE_BUILD_TYPE` be unset, or there will be strange effects.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
