### ISSUE TITLE
[qtbase] build failure

### ISSUE THREAD

**Issue by Kicer86** [microsoft/vcpkg#18950]
**Host Environment**
- OS: Windows
- Compiler: gcc.exe (Rev5, Built by MSYS2 project) 10.3.0

**To Reproduce**
`./vcpkg install qtbase:x64-mingw-dynamic`

**Additional context**
qtbase depends on `libb2` on !windows platoforms.
Yet with x64-mingw-dynamic triplet `vcpkg` tries to install `libb2` which fails (`libb2` builds on windows are disabled with `vcpkg_fail_port_install(ON_TARGET "WINDOWS")`).

**Comment by FrankXie05** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.

**Comment by Kicer86** [comment]
Works now.
