### ISSUE TITLE
[CMake] update to 3.21.0

### ISSUE THREAD

**Issue by xavier2k6** [microsoft/vcpkg#18952]
Library name: CMake from Kitware

New version number: 3.21.0

Other information that may be useful (release notes, etc...)

ref.:
`scripts/vcpkgTools.xml`
https://cmake.org/download/#:~:text=Latest%20Release
https://cmake.org/cmake/help/v3.21/release/3.21.html#cmake-3-21-release-notes

**Comment by cenit** [comment]
https://github.com/microsoft/vcpkg-tool/pull/107

a new vcpkg-tool is also mandatory for cmake 3.21
fixes already landed there, I hope it can be released soon to unblock pipelines that are already using cmake 3.21

**Comment by davidhunter22** [comment]
Can I second the request for a new vcpkg-tool release. Not having the commit https://github.com/microsoft/vcpkg-tool/commit/8b1c04b3b8e50db93d0245e761f3d8ebeb400309 means anyone using vcpkg migrating to CMake 3.21 will face doom and gloom. See https://gitlab.kitware.com/cmake/cmake/-/issues/22371 and https://gitlab.kitware.com/cmake/cmake/-/issues/22422 for at least two reports of the problem

**Comment by JackBoosY** [comment]
@davidhunter22 We will release the next version in a few days.

**Comment by snnn** [comment]
It will affect a lot of github users. The latest Windows 2019 image provided by github actions works fine, because it uses cmake 3.20.5. (see https://github.com/actions/virtual-environments/blob/releases/win19/20210711/images/win/Windows2019-Readme.md).

But once they regenerate the image, vcpkg will crash. Usually they update the image weekly.

**Comment by 9prady9** [comment]
> It will affect a lot of github users. The latest Windows 2019 image provided by github actions works fine, because it uses cmake 3.20.5. (see https://github.com/actions/virtual-environments/blob/releases/win19/20210711/images/win/Windows2019-Readme.md).
> 
> But once they regenerate the image, vcpkg will crash. Usually they update the image weekly.

This kind of eventually happened and our CI job fails running vcpkg command because Windows image now has CMake 3.21

@JackBoosY Any hints on the ETA for next vcpkg release ?

**Comment by JackBoosY** [comment]
@9prady9 The update for cmake 3.21.0 is ready for merge now.
