### ISSUE TITLE
Installing mpg123 creates an mpg123-config.cmake file for x64-windows but not x64-linux. Should it?

### ISSUE THREAD

**Issue by CodedByATool** [microsoft/vcpkg#18968]
I'm making a simple cmake project that uses mpg123. I'd like this stub to work the same on both linux (ubuntu) and windows (10):

```cmake_minimum_required(VERSION 3.17)
message(STATUS "Tool Chain ${CMAKE_TOOLCHAIN_FILE}")
project(testproject VERSION 0.0.1 LANGUAGES CXX)	
find_package(mpg123 CONFIG REQUIRED)
get_target_property(MPG123_INCLUDE_DIRECTORIES MPG123::libmpg123 INTERFACE_INCLUDE_DIRECTORIES)
message(STATUS "mpg123 includes ${MPG123_INCLUDE_DIRECTORIES}")
```

The toolchain file is set correctly for vcpkg, _other_ vcpkg installed packages are being found fine and are setting variables for both linux and windows builds.

When this is run on windows10 after installing the mpg123 x64-windows triplet with vcpkg it picks up the INTERFACE_INCLUDE_DIRECTORIES set by `vcpkg\installed\x64-windows\share\mpg123\targets.cmake` (included from mpg123-config.cmake).

On ubuntu, when I install the mpg123 x64-linux triplet with vcpkg the path `vcpkg/installed/x64-linux/share/mpg123` does not contain any cmake files to configure the interface.

Is this a bug with the mpg123 port, or am I using it incorrectly?
I have been able to work around the issue with a MPG123Find.cmake module, but I'd rather not do that for vcpkg installed packages if I don't have to.

Thanks.

**Comment by evpobr** [comment]
CMake buildsystem is new for mpg123 and tested (more or less) on Windows platform only. On other platfroms it uses Autotools.

**Comment by JackBoosY** [comment]
Yes, maybe we should support cmake to build mpg123 on Linux.
@evpobr What do you think about this?

**Comment by evpobr** [comment]
Sorry, i'm buzy now.

**Comment by LilyWangLL** [comment]
This issue has been solved, now user could use usage of CMake and pkg-config on Linux.
```
mpg123 provides CMake targets:

  # this is heuristically generated, and may not be correct
  find_package(mpg123 CONFIG REQUIRED)
  target_link_libraries(main PRIVATE MPG123::libmpg123 MPG123::libout123 MPG123::libsyn123)

mpg123 provides pkg-config modules:

    # An optimised MPEG Audio decoder
    libmpg123

    # A streaming audio output API derived from mpg123
    libout123

    # A signal synthesis library accompanying mpg123
    libsyn123
```
