### ISSUE TITLE
VCPkg does not support the v143 MSVC toolset

### ISSUE THREAD

**Issue by Ryan-rsm-McKenzie** [microsoft/vcpkg#18987]
**Describe the bug**
VCPkg does not support the v143 MSVC toolset. It seems to stem from a missing entry in this hard-coded list:
https://github.com/microsoft/vcpkg-tool/blob/3be6b75f6972aa72ca34afce39168094432ea300/src/vcpkg/visualstudio.cpp#L15-L18
And subsequently a missing case here:
https://github.com/microsoft/vcpkg-tool/blob/main/src/vcpkg/visualstudio.cpp#L252-L266

**Environment**
- OS: Windows
- Compiler: VS 2022 17.0 Preview 2.0

**To Reproduce**
Given some valid cmake project:
1. `cmake -B build -S . -G "Visual Studio 17 2022" -T v143 -DCMAKE_TOOLCHAIN_FILE="path/to/vcpkg/scripts/buildsystems/vcpkg.cmake"`
2. See error
```
-- Running vcpkg install
No suitable Visual Studio instances were found
-- Running vcpkg install - failed
CMake Error at E:/Repos/vcpkg/scripts/buildsystems/vcpkg.cmake:837 (message):
  vcpkg install failed.  See logs for more information:
  E:\Repos\bsa\build\vcpkg-manifest-install.log
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.21/Modules/CMakeDetermineSystem.cmake:124 (include)
  CMakeLists.txt:3 (project)
```

**Expected behavior**
I would expect vcpkg to recognize the v143 toolset.

**Failure logs** 
`vcpkg-manifest-install.log`
```
No suitable Visual Studio instances were found
```

**Comment by SmartPolarBear** [comment]
Same issue.

**Comment by PhoebeHui** [comment]
@Ryan-rsm-McKenzie, thanks for bringing this up! 

This is not supported yet, we would work for it recently.

**Comment by rouisibra** [comment]
Doesn't VS 2022 supports VS 2019 projects? I think that the script just needs to allow VS 2022 preview and that's it.

**Comment by BillyONeal** [comment]
Reopening until we do a binary release to pick up the fix.
