### ISSUE TITLE
vcpkg install  [package] error

### ISSUE THREAD

**Issue by branchesgit** [microsoft/vcpkg#18988]
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:155 (message):
    Command failed: "D:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j17
    Working Directory: D:/vc_tools/vcpkg/buildtrees/zlib/x86-windows-dbg
    See logs for more information:
      D:\vc_tools\vcpkg\buildtrees\zlib\install-x86-windows-dbg-out.log
      D:\vc_tools\vcpkg\buildtrees\zlib\install-x86-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:104 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:44 (vcpkg_build_cmake)
  ports/zlib/portfile.cmake:33 (vcpkg_install_cmake)
  scripts/ports.cmake:140 (include)

Error: Building package zlib:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zlib:x86-windows
  Vcpkg version: 2021-05-05-e8977e69d9a3fb462d9ad42013d83a7682706659

**Comment by autoantwort** [comment]
When reporting an issue please always provide the log files :
> See logs for more information:
D:\vc_tools\vcpkg\buildtrees\zlib\install-x86-windows-dbg-out.log
D:\vc_tools\vcpkg\buildtrees\zlib\install-x86-windows-dbg-err.log

Thanks :)

**Comment by branchesgit** [comment]
try it some times, and pass
