### ISSUE TITLE
How do I enable spectre mitigation

### ISSUE THREAD

**Issue by henriblMSFT** [microsoft/vcpkg#18986]
We are using BinSkim to scan our assembly for any issues, one of the issue is flagged is that our assembly does not have spectre mitigation.

Our assembly depends on the yara port which we build this way:
```
vcpkg install yara:x86-windows-static yara:x64-windows-static
```

Ultimately we depend on the following lib packages:
- jansson.lib
- libcrypto.lib
- libssl.lib
- libyara.lib

Is it possible to enable spectre mitigation when building those static libraries flag without changing the port file?

When building with msbuild this is done by either by specifying the /p:SpectreMitigation=Spectre or by adding the /QSpectre

**Comment by JackBoosY** [comment]
Please replace _VCPKG_ROOT/ports/yara/CMakeLists.txt_ line 5 from:
```cmake
  add_compile_options(/W3 /wd4005 /wd4996 /wd4018 -D_CRT_SECURE_NO_WARNINGS)
```
to
```cmake
  add_compile_options(/W3 /wd4005 /wd4996 /wd4018 -D_CRT_SECURE_NO_WARNINGS /Qspectre)
```

Then rebuild yara.

**Comment by henriblMSFT** [comment]
Should I submit a PR to update the port file or is there a mechanism to make this optional?

**Comment by JackBoosY** [comment]
@henriblMSFT  Yes please, you need to add a feature named `spectre`, and I will give you help.

**Comment by henriblMSFT** [comment]
Could you point me to documentation on how to add features or a sample pull request that added a feature?

**Comment by JackBoosY** [comment]
@henriblMSFT Please see [doc](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md) and [example](https://github.com/microsoft/vcpkg/pull/18964/files).

**Comment by henriblMSFT** [comment]
@JackBoosY create a draft PR and tested locally. Do features trickle down? If I was to implement the same feature in jansson would calling `vcpkg install yara[spectre]:x64-windows-static` also enable that feature on jansson or would I need to first install jansson with spectre feature
```
vcpkg install jansson[spectre]:x64-windows-static
vcpkg install yara[spectre]:x64-windows-static
```

**Comment by Adela0814** [comment]
Fixed by https://github.com/microsoft/vcpkg/pull/28713.
