### ISSUE TITLE
Could not find toolset 'v140_xp'

### ISSUE THREAD

**Issue by Ghabry** [microsoft/vcpkg#1898]
I created a new triplet file with
```
set(VCPKG_PLATFORM_TOOLSET "v140_xp")
```
but this results in the error "Could not find toolset 'v140_xp'".

Is the "_xp" stuff not supported by vcpkg? The toolset is correctly installed, I can use it in Visual Studio.

**Comment by Mixaill** [comment]
**_xp** stuff currently WIP #1732

**Comment by Ghabry** [comment]
Great. Thanks. Missed that Pull request. Only searched for "v140_xp", not for Windows XP >.>

**Comment by VikingExplorer** [comment]
@Mixaill  Isn't this ready by now?  

I'm getting: Could not find Visual Studio instance with v141_xp toolset

**Comment by NancyLi1013** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen.
