### ISSUE TITLE
[glib:x64-mingw-static] build failure

### ISSUE THREAD

**Issue by talregev** [microsoft/vcpkg#18996]
**Host Environment**
- OS: ubuntu
- Compiler: gcc 9.3, x86_64-w64-mingw32-gcc 9.3-win32

**To Reproduce**

> Steps to reproduce the behavior:

`./vcpkg install glib --triplet=x64-mingw-static`

**Failure logs** 

> -Cut and past the appropriate build messages from the console output.
> -Please attach any additional failure logs mentioned in the console output.

```
../src/glib-2-b84205c786.clean/meson.build:1:0: ERROR: Unsupported linker, only bfd, gold, and lld are supported, not /usr/bin/x86_64-w64-mingw32-ld.

A full log can be found at /home/tal/libgsf/vcpkg/buildtrees/glib/x64-mingw-static-dbg/meson-logs/meson-log.txt
```
[glib.zip](https://github.com/microsoft/vcpkg/files/6836046/glib.zip)

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by talregev** [comment]
[meson-log.txt](https://github.com/microsoft/vcpkg/files/6836052/meson-log.txt)

**Comment by longnguyen2004** [comment]
I'm not familiar with meson, so maybe someone else can have a look at this.

**Comment by talregev** [comment]
ok. Thank you for your time that you take a look!

**Comment by autoantwort** [comment]
Would be fixed by https://github.com/microsoft/vcpkg/pull/18927

**Comment by talregev** [comment]
I will check it now.

**Comment by talregev** [comment]
I checkout your PR https://github.com/microsoft/vcpkg/pull/18927
```
./bootstrap-vcpkg.sh
./vcpkg install glib --triplet=x64-mingw-static
```
I got the same error:
[glib.zip](https://github.com/microsoft/vcpkg/files/6836178/glib.zip)

**Comment by talregev** [comment]
@autoantwort Can you verify on your end:

```bash
git clone https://github.com/autoantwort/vcpkg -b fix-meson-linux-windows-cross-build
vcpkg/bootstrap-vcpkg.sh
git -C vcpkg remote add longnguyen https://github.com/longnguyen2004/vcpkg
git -C vcpkg pull --all
git -C vcpkg checkout libffi-v3.4.2
vcpkg/vcpkg install glib --triplet=x64-mingw-static
```

**Comment by autoantwort** [comment]
In your code you are not using my patch. You have to merge my patch into `libffi-v3.4.2`

**Comment by talregev** [comment]
This is not my branch. Maybe if we can create a test branch that will merge both the changes.
I am also try opposite:
I clone https://github.com/longnguyen2004/vcpkg first. then install all the dependencies of glib.
then switch to your branch build from scratch vcpkg, then `vcpkg install glib`. I got the same error.

**Comment by longnguyen2004** [comment]
You can do
```
git clone https://github.com/Microsoft/vcpkg && cd vcpkg
git remote add fork1 https://github.com/longnguyen2004/vcpkg
git remote add fork2 https://github.com/autoantwort/vcpkg
git fetch fork1 && git fetch fork2
git checkout -b test-patch
git merge fork1/libffi-v3.4.2 && git merge fork2/fix-meson-linux-windows-cross-build
```

**Comment by talregev** [comment]
ok. I will try it. Can you try it also on yours end?

**Comment by talregev** [comment]
I merge both branches, I am still getting the same errors:
[artifacts.zip](https://github.com/microsoft/vcpkg/files/6836483/artifacts.zip)

**Comment by autoantwort** [comment]
I can test it one our university gitlab is up again

**Comment by talregev** [comment]
ok.

**Comment by talregev** [comment]
Thank you for the fix. Now I got another error:
`../src/glib-2-b84205c786.clean/meson.build:1697:2: ERROR: Entry _WIN32_WINNT not in configuration data.`
[artifacts.zip](https://github.com/microsoft/vcpkg/files/6842435/artifacts.zip)

**Comment by talregev** [comment]
@JackBoosY @Neumann-A @dg0yt @autoantwort 
Can you help? What should I do? 
https://stackoverflow.com/questions/12871513/how-to-get-rid-of-win32-winnt-not-defined-warning/12871547

**Comment by autoantwort** [comment]
https://discourse.gnome.org/t/build-gtk3-with-meson-using-msys2-on-windows-fails/4015

**Comment by dg0yt** [comment]
Is static glib supported for mingw? It isn't for windows, according to #18557.

**Comment by talregev** [comment]
Can we solve it? I prefer to use static.

**Comment by talregev** [comment]
The same happen with dynamic: 
`../src/glib-2-b84205c786.clean/meson.build:1697:2: ERROR: Entry _WIN32_WINNT not in configuration data.`
[glib.zip](https://github.com/microsoft/vcpkg/files/6895596/glib.zip)

**Comment by talregev** [comment]
I guess we should define it somewhere `_WIN32_WINNT`

**Comment by dg0yt** [comment]
Oh, meson. AFAIU vcpkg doesn't set the right system for mingw. I created https://github.com/autoantwort/vcpkg/pull/1 to extend 
 #18927. Waiting for @autoantwort.

**Comment by talregev** [comment]
I already use the fix of @autoantwort it after I merge it PR.

**Comment by talregev** [comment]
@dg0yt Seems that all test pass in #18927. What else is needed to do there?

**Comment by autoantwort** [comment]
> Oh, meson. AFAIU vcpkg doesn't set the right system for mingw. I created [autoantwort#1](https://github.com/autoantwort/vcpkg/pull/1) to extend
> #18927. Waiting for @autoantwort.

Sorry, I didn't got an email about it. Good that you ping me and thank you for the real fix!

**Comment by talregev** [comment]
I will test it again with @autoantwort PR #18927.

**Comment by talregev** [comment]
Now we get some progress. 
I have another error:
`../src/glib-2-b84205c786.clean/glib/meson.build:326:2: ERROR: Could not find Windows resource compiler`

[glib.zip](https://github.com/microsoft/vcpkg/files/6895748/glib.zip)

**Comment by talregev** [comment]
https://stackoverflow.com/questions/57436089/meson-can-not-find-windows-resource-compiler-on-linux

I have `x86_64-w64-mingw32-windres`

![image](https://user-images.githubusercontent.com/7043539/127378918-9357412c-bad2-4835-b0d3-d597c5434c89.png)

**Comment by talregev** [comment]
How I can define to meson that I have windows resource compiler?

**Comment by autoantwort** [comment]
Like in the stackoverflow question you probably have to set 
```
ar = 'i686-w64-mingw32-ar'
strip = 'i686-w64-mingw32-strip'
exe_wrapper = 'WINEPREFIX=~/.wine64 wine'
windres = 'i686-w64-mingw32-windres'
```
in the `meson-cross-x64-mingw-*.log` file. That must be done by `vcpkg_configure_meson`. Instead of `windres` `rc` is currently set

**Comment by talregev** [comment]
> in the `meson-cross-x64-mingw-*.log` file. That must be done by `vcpkg_configure_meson`. Instead of `windres` `rc` is currently set

Can you do it?

**Comment by talregev** [comment]
I think for `x64-mingw-*` triplet it should `x86_64-w64-mingw32-*`
For triplet `x86-mingw-*` triplet is should like you write: `i686-w64-mingw32-*`

**Comment by talregev** [comment]
@autoantwort thanks that help! 
https://mesonbuild.com/Windows-module.html
I define:
`export WINDRES=x86_64-w64-mingw32-windres`
like it written in the link.
I get some progress.
Now it missing
`fatal error: libintl.h: No such file or directory `
I will try to install this lib with vcpkg manually. it should add as a dependency.

**Comment by talregev** [comment]
https://stackoverflow.com/questions/11370684/what-is-libintl-h-and-where-can-i-get-it

**Comment by talregev** [comment]
I already have it:
![image](https://user-images.githubusercontent.com/7043539/127381938-d8015e4f-a476-4264-a019-9a7b7f14ebb4.png)

**Comment by talregev** [comment]
What should I do?

**Comment by talregev** [comment]
[glib.zip](https://github.com/microsoft/vcpkg/files/6895913/glib.zip)

```
Building package glib[core]:x64-mingw-dynamic...
-- Using community triplet x64-mingw-dynamic. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: /home/tal/vcpkg/triplets/community/x64-mingw-dynamic.cmake
-- Using /home/tal/vcpkg/downloads/glib-2.66.4.tar.xz
-- Cleaning sources at /home/tal/vcpkg/buildtrees/glib/src/glib-2-b84205c786.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/tal/vcpkg/downloads/glib-2.66.4.tar.xz
-- Applying patch use-libiconv-on-windows.patch
-- Applying patch fix-libintl-detection.patch
-- Using source at /home/tal/vcpkg/buildtrees/glib/src/glib-2-b84205c786.clean
-- Configuring x64-mingw-dynamic-dbg
-- Configuring x64-mingw-dynamic-rel
-- Configuring x64-mingw-dynamic-dbg
-- Configuring x64-mingw-dynamic-dbg done
-- Configuring x64-mingw-dynamic-rel
-- Configuring x64-mingw-dynamic-rel done
-- Package x64-mingw-dynamic-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: /home/tal/vcpkg/downloads/tools/ninja-1.10.2-linux/ninja install -v
    Working Directory: /home/tal/vcpkg/buildtrees/glib/x64-mingw-dynamic-dbg
    Error code: 1
    See logs for more information:
      /home/tal/vcpkg/buildtrees/glib/package-x64-mingw-dynamic-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_meson.cmake:58 (vcpkg_execute_required_process)
  ports/glib/portfile.cmake:55 (vcpkg_install_meson)
  scripts/ports.cmake:141 (include)


Error: Building package glib:x64-mingw-dynamic failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: glib:x64-mingw-dynamic
  Vcpkg version: 2021-07-26-unknownhash
```

**Comment by autoantwort** [comment]
Hm the path is added via `'-I"/home/tal/vcpkg/installed/x64-mingw-dynamic/include"'`.

**Comment by autoantwort** [comment]
Maybe the `"` are a problem

**Comment by talregev** [comment]
This is my path `/home/tal/vcpkg/installed/x64-mingw-dynamic/include`
![image](https://user-images.githubusercontent.com/7043539/127382893-89198527-3331-45f2-95b5-63c8005113d9.png)

Maybe it the problem. How I can remove it?

**Comment by autoantwort** [comment]
https://github.com/microsoft/vcpkg/blob/master/scripts/cmake/vcpkg_configure_meson.cmake#L124 Remove them there

**Comment by autoantwort** [comment]
And here:https://github.com/microsoft/vcpkg/blob/master/scripts/cmake/vcpkg_configure_meson.cmake#L128
Remove the `\"` at the beginning and at the end

**Comment by talregev** [comment]
ok. Should I bootstrap (compile vcpkg) after that?

**Comment by autoantwort** [comment]
No you don't have to

**Comment by talregev** [comment]
I only found the L128. I didn't find the L124. Did i Miss something?

**Comment by autoantwort** [comment]
Yeah it is a link to master, with my patch the line numbers are different, but you should find the right line

**Comment by talregev** [comment]
For me it on 128 and 132 lines

**Comment by talregev** [comment]
I remove and I testing now.

**Comment by talregev** [comment]
It help!
Can you remove it from your PR?
We also need to solve the `export WINDRES=x86_64-w64-mingw32-windres` in another PR.
it succussed on dynamic and fail on static.

**Comment by talregev** [comment]
```
Starting package 1/5: glib:x64-mingw-static
Building package glib[core]:x64-mingw-static...
-- Using community triplet x64-mingw-static. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: /home/tal/vcpkg/triplets/community/x64-mingw-static.cmake
-- Note: glib only supports dynamic library linkage. Building dynamic library.
-- Using /home/tal/vcpkg/downloads/glib-2.66.4.tar.xz
-- Cleaning sources at /home/tal/vcpkg/buildtrees/glib/src/glib-2-b84205c786.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/tal/vcpkg/downloads/glib-2.66.4.tar.xz
-- Applying patch use-libiconv-on-windows.patch
-- Applying patch fix-libintl-detection.patch
-- Using source at /home/tal/vcpkg/buildtrees/glib/src/glib-2-b84205c786.clean
-- Configuring x64-mingw-static-dbg
-- Configuring x64-mingw-static-rel
-- Configuring x64-mingw-static-dbg
-- Configuring x64-mingw-static-dbg done
-- Configuring x64-mingw-static-rel
-- Configuring x64-mingw-static-rel done
-- Package x64-mingw-static-dbg
-- Package x64-mingw-static-rel
-- Fixing pkgconfig file: /home/tal/vcpkg/packages/glib_x64-mingw-static/lib/pkgconfig/gio-2.0.pc
-- Fixing pkgconfig file: /home/tal/vcpkg/packages/glib_x64-mingw-static/lib/pkgconfig/gio-windows-2.0.pc
-- Fixing pkgconfig file: /home/tal/vcpkg/packages/glib_x64-mingw-static/lib/pkgconfig/glib-2.0.pc
-- Fixing pkgconfig file: /home/tal/vcpkg/packages/glib_x64-mingw-static/lib/pkgconfig/gmodule-2.0.pc
-- Fixing pkgconfig file: /home/tal/vcpkg/packages/glib_x64-mingw-static/lib/pkgconfig/gmodule-export-2.0.pc
-- Fixing pkgconfig file: /home/tal/vcpkg/packages/glib_x64-mingw-static/lib/pkgconfig/gmodule-no-export-2.0.pc
-- Fixing pkgconfig file: /home/tal/vcpkg/packages/glib_x64-mingw-static/lib/pkgconfig/gobject-2.0.pc
-- Fixing pkgconfig file: /home/tal/vcpkg/packages/glib_x64-mingw-static/lib/pkgconfig/gthread-2.0.pc
-- Fixing pkgconfig file: /home/tal/vcpkg/packages/glib_x64-mingw-static/debug/lib/pkgconfig/gio-2.0.pc
-- Fixing pkgconfig file: /home/tal/vcpkg/packages/glib_x64-mingw-static/debug/lib/pkgconfig/gio-windows-2.0.pc
-- Fixing pkgconfig file: /home/tal/vcpkg/packages/glib_x64-mingw-static/debug/lib/pkgconfig/glib-2.0.pc
-- Fixing pkgconfig file: /home/tal/vcpkg/packages/glib_x64-mingw-static/debug/lib/pkgconfig/gmodule-2.0.pc
-- Fixing pkgconfig file: /home/tal/vcpkg/packages/glib_x64-mingw-static/debug/lib/pkgconfig/gmodule-export-2.0.pc
-- Fixing pkgconfig file: /home/tal/vcpkg/packages/glib_x64-mingw-static/debug/lib/pkgconfig/gmodule-no-export-2.0.pc
-- Fixing pkgconfig file: /home/tal/vcpkg/packages/glib_x64-mingw-static/debug/lib/pkgconfig/gobject-2.0.pc
-- Fixing pkgconfig file: /home/tal/vcpkg/packages/glib_x64-mingw-static/debug/lib/pkgconfig/gthread-2.0.pc
-- Installing: /home/tal/vcpkg/packages/glib_x64-mingw-static/share/glib/copyright
-- Performing post-build validation
Import libs were not present in /home/tal/vcpkg/packages/glib_x64-mingw-static/debug/lib
If this is intended, add the following line in the portfile:
    SET(VCPKG_POLICY_DLLS_WITHOUT_LIBS enabled)
Import libs were not present in /home/tal/vcpkg/packages/glib_x64-mingw-static/lib
If this is intended, add the following line in the portfile:
    SET(VCPKG_POLICY_DLLS_WITHOUT_LIBS enabled)
Found 2 error(s). Please correct the portfile:
    /home/tal/vcpkg/ports/glib/portfile.cmake
-- Performing post-build validation done
Error: Building package glib:x64-mingw-static failed with: POST_BUILD_CHECKS_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: glib:x64-mingw-static
  Vcpkg version: 2021-07-26-unknownhash

Additionally, attach any relevant sections from the log files above.
```

**Comment by autoantwort** [comment]
> It help!
> Can you remove it from your PR?
> We also need to solve the `export WINDRES=x86_64-w64-mingw32-windres` in another PR.
> it succussed on dynamic and fail on static.
> @autoantwort and @dg0yt Thank you for your help!

Yes I will fix it

**Comment by talregev** [comment]
@autoantwort Thank you!

**Comment by autoantwort** [comment]
Can use unset WINDRES and undo the changes and test the updated PR? 
Btw thank you for testing :)

**Comment by talregev** [comment]
I will! I will test it on CI.

**Comment by talregev** [comment]
It should with capital letter
I test it earlier and it didn't work: `export windres=x86_64-w64-mingw32-windres`
Can you change to capital letter? `WINDRES`
https://github.com/microsoft/vcpkg/pull/18927/commits/975674d7b02b4b1e162e8f7e63c12f4b9d52a826#diff-06c96eebcc929e5c160ad5c08c55ca09520a1b419eabb3841ac77e44991a6a35R282

**Comment by talregev** [comment]
it fail on the CI

```
Starting package 9/13: glib:x64-mingw-dynamic
Building package glib[core]:x64-mingw-dynamic...
-- Using community triplet x64-mingw-dynamic. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: /builds/tal.regev/libgsf/vcpkg/triplets/community/x64-mingw-dynamic.cmake
-- Downloading https://ftp.gnome.org/pub/gnome/sources/glib/2.66/glib-2.66.4.tar.xz -> glib-2.66.4.tar.xz...
-- Extracting source /builds/tal.regev/libgsf/vcpkg/downloads/glib-2.66.4.tar.xz
-- Applying patch use-libiconv-on-windows.patch
-- Applying patch fix-libintl-detection.patch
-- Using source at /builds/tal.regev/libgsf/vcpkg/buildtrees/glib/src/glib-2-b84205c786.clean
-- Configuring x64-mingw-dynamic-dbg
-- Configuring x64-mingw-dynamic-rel
-- Configuring x64-mingw-dynamic-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: /usr/bin/python3 /builds/tal.regev/libgsf/vcpkg/downloads/tools/meson/meson-aeda7f249c4a5dbbecc52e44f382246a2377b5b0/meson.py -Dbuild_tests=false -Dinstalled_tests=false -Dselinux=disabled -Diconv=external -Dinternal_pcre=false --buildtype plain --backend ninja --wrap-mode nodownload --cross /builds/tal.regev/libgsf/vcpkg/buildtrees/glib/meson-cross-x64-mingw-dynamic.log --native /builds/tal.regev/libgsf/vcpkg/scripts/buildsystems/meson/none.txt --default-library shared --libdir lib --cross /builds/tal.regev/libgsf/vcpkg/buildtrees/glib/meson-cross-x64-mingw-dynamic-debug.log -Ddebug=true --prefix /builds/tal.regev/libgsf/vcpkg/packages/glib_x64-mingw-dynamic/debug --includedir ../include -Dcmake_prefix_path=['/builds/tal.regev/libgsf/vcpkg/installed/x64-mingw-dynamic/debug','/builds/tal.regev/libgsf/vcpkg/installed/x64-mingw-dynamic','/builds/tal.regev/libgsf/vcpkg/installed/x64-mingw-dynamic/share'] /builds/tal.regev/libgsf/vcpkg/buildtrees/glib/src/glib-2-b84205c786.clean
    Working Directory: /builds/tal.regev/libgsf/vcpkg/buildtrees/glib/x64-mingw-dynamic-dbg
    Error code: 1
    See logs for more information:
      /builds/tal.regev/libgsf/vcpkg/buildtrees/glib/config-x64-mingw-dynamic-dbg-out.log
Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_meson.cmake:496 (vcpkg_execute_required_process)
  ports/glib/portfile.cmake:42 (vcpkg_configure_meson)
  scripts/ports.cmake:141 (include)
Error: Building package glib:x64-mingw-dynamic failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: glib:x64-mingw-dynamic
  Vcpkg version: 2021-07-26-unknownhash
Additionally, attach any relevant sections from the log files above.
```

[artifacts.zip](https://github.com/microsoft/vcpkg/files/6896283/artifacts.zip)

**Comment by talregev** [comment]
`../src/glib-2-b84205c786.clean/glib/meson.build:326:2: ERROR: Could not find Windows resource compiler`

**Comment by talregev** [comment]
@autoantwort 
I found a typo:
you write "winres" should be `windres`
https://github.com/microsoft/vcpkg/commit/975674d7b02b4b1e162e8f7e63c12f4b9d52a826#diff-06c96eebcc929e5c160ad5c08c55ca09520a1b419eabb3841ac77e44991a6a35R282

**Comment by FrankXie05** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.

**Comment by JackBoosY** [comment]
> @autoantwort I found a typo: you write "winres" should be `windres` [975674d#diff-06c96eebcc929e5c160ad5c08c55ca09520a1b419eabb3841ac77e44991a6a35R282](https://github.com/microsoft/vcpkg/commit/975674d7b02b4b1e162e8f7e63c12f4b9d52a826#diff-06c96eebcc929e5c160ad5c08c55ca09520a1b419eabb3841ac77e44991a6a35R282)

This was fixed.
