### ISSUE TITLE
x-add-version check in ci

### ISSUE THREAD

**Issue by m-kuhn** [microsoft/vcpkg#18993]
When creating a pull request for a port update it is required to run the x-add-version command.
Failing to run and commit this (or doing it at the wrong point in time) blocks a pull request. This is prone to happen for newcomers (it happened to me more than once).

At the moment, this check is mostly done manually by repository maintainers. The good thing of that is, that there is a social aspect by having someone reply, suggest, guide and explain (appreciated!).
The other side is that it usually adds a couple of hours of waiting time and an extra round of work to be done when the author of said pull request is busy with other things already.

It would be fairly straightforward to add a check for this into the ci (talking about github ci here ...) and even have a bot adding the code suggestion.

The resulting UX would be:

 - Author opens a pull request or pushes a new commit to a pull request
 - After a couple of seconds (or minutes) the "x-add-version" check would be green or red
 - If it's red, the author receives a notification that something is wrong
   - Option A: with a description how to fix things manually
   - Option B: to apply the suggestion on the github pull request page through the github suggestion mechanism
   - Option C: with a comment from a bot offering to do things, something like: Please respond with a comment "apply x-add-version" to fix it up for you.

Here is an example of B / C https://github.com/opengisch/QField/blob/master/.github/workflows/astyle.yml#L68-L74

**Comment by dg0yt** [comment]
Note that there is a basic check, at the end of the x86-windows job. However on Github, the message just says "PowerShell exited with code '1'." (e.g. current state at https://github.com/microsoft/vcpkg/pull/18971/checks?check_run_id=3084308351).

**Comment by autoantwort** [comment]
If you click on "View on azure" you get
```
Found the following errors:
Error: While reading versions for port curl from file: C:\a\1\s\versions\c-\curl.json
       Version `7.77.0` was not found in versions file.
       Run:
           vcpkg x-add-version curl
       to add the new port version.
To attempt to resolve all errors at once, run:
    vcpkg x-add-version --all
```
But yeah this can be approved. 

Normally the pull request template already states that you have to run `x-add-version` and commit the result, but nobody seems to read it.

**Comment by dg0yt** [comment]
> If you click on "View on azure" you get

You still need to click on the failed job.

> Normally the pull request template already states that you have to run x-add-version and commit the result, but nobody seems to read it.

The template is hard to understand for outsiders, and the particularities of the the git-tree reference are hard to understand, too. So a newcomer choose between submitting without fully understanding, and not submitting at all. 

IMO, handling the `versions` directory, and perhaps even incrementing the port-version, is more a task for the actual merge instead of the initial submission - or, as proposed by @m-kuhn, something for an automated suggestion.

**Comment by m-kuhn** [comment]
Even for those who know how it works it's easy to forget or do wrong.
Contributor time should be treated with care. For creating more pull requests, doing other work or enjoy leisure time.
The less clicks and typing required for a pull request to get merged and the shorter the number of times it needs to be revisited, the happier the contributor is and the more likely he'll contribute again.

**Comment by autoantwort** [comment]
Maybe we should create a page with instructions how to update(/create) a port. The current maintainer guide is imho currently very user unfriendly. Also maybe change the current Pull Request Template to a Checklist.  
An yeah a auto suggestion for that would be cool (when there is some way to turn it off).

**Comment by BillyONeal** [comment]
>   * Option B: to apply the suggestion on the github pull request page through the github suggestion mechanism
>   * Option C: with a comment from a bot offering to do things, something like: Please respond with a comment "apply x-add-version" to fix it up for you.
> 
> Here is an example of B / C https://github.com/opengisch/QField/blob/master/.github/workflows/astyle.yml#L68-L74

This would require the CI infrasatructure to be able to write back to GitHub; a capability it does not currently have. The example you quote uses GitHub Actions, rather than Azure Pipelines, but VMs of sufficient size to build the vcpkg catalog in a reasonable amount of time are not available in Actions, so I think we either need Actions to gain the virtual machine scale set management feature we need from Pipelines, or Pipelines needs to gain the 'write to github' capability.

>Maybe we should create a page with instructions how to update(/create) a port. The current maintainer guide is imho currently very user unfriendly. Also maybe change the current Pull Request Template to a Checklist.

I agree our docs could be a lot better.

**Comment by m-kuhn** [comment]
or you could have both cis involved for different tasks, but I can understand if this is not an option.

**Comment by BillyONeal** [comment]
> or you could have both cis involved for different tasks, but I can understand if this is not an option.

Yeah, we're really wary of increasing the number of things that need to be up/working in order to make progress.

**Comment by m-kuhn** [comment]
One option would be to add a bot user on github and use that for interaction through the github api [1].

Improving the documentation would be valuable, but I think some tooling and automation could help even more to increase contributor satisfaction and reduce maintenance effort.
An alternative would be to remove the check from the development process itself and push a new commit from the CI after each merge (I think @dg0yt also hinted in this direction)

[1]:
I don't know if azure ci allows to keep the login token secure (i.e. not make it available to code that can be modified in a PR).

**Comment by BillyONeal** [comment]
> Improving the documentation would be valuable, but I think some tooling and automation could help even more to increase contributor satisfaction and reduce maintenance effort. 

I'm not saying that wouldn't be nice, I'm saying I don't know of a way to do that that doesn't cause the 'more things need to be working for us to make any progress' problem.

> An alternative would be to remove the check from the development process itself and push a new commit from the CI after each merge (I think @dg0yt also hinted in this direction)

This is unacceptable because half the commits in the history would be broken. (And also, the version database edits aren't completely automatable)

**Comment by autoantwort** [comment]
I think it is was kind of done in #19115

**Comment by BillyONeal** [comment]
I agree this is done by 19115
