### ISSUE TITLE
How to get documentation in Qt Assistant?

### ISSUE THREAD

**Issue by mknigh23** [microsoft/vcpkg#19004]
When building qt5, Qt Assistant builds, but the documentation is empty and the qt.qch file is unavailable.  Am I meant to use an undocumented command-line argument to build the documents or is it simply missing?

![qt5_assistant](https://user-images.githubusercontent.com/8951806/126153117-f06a5a58-f72d-4055-93c1-8c44fea20a6d.png)

If the file is a separate download, could you please advise where?

I note a previous assistant.patch has been removed from the $(vcpkg_base)\ports\qt5-tools\qt5-tools folder, which was for a similar issue.

**Comment by Neumann-A** [comment]
> How do I build Qt Assistant?

The title is wrong. 
The question should be: How to get documentation in Qt Assistant?
According to the maintainer guidelines documentation is disabled by default. (see https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#do-not-build-testsdocsexamples-by-default)
Please feel free to add it as a feature if you need it.

**Comment by mknigh23** [comment]
I stand corrected.
I would have thought the help documentation - as opposed to examples - a necessity, as it is unavailable online, making it extremely difficult to identify new concepts, classes and function parameters.
You mention adding it, should I need it, but as this is my first contact with vcpkg, I have absolutely no idea how to do so.  I used the command-line "./vcpkg install cgal[qt5]:x64-windows" to build CGAL, QT5 and their dependencies (nice), but have no idea to add individual components. Any help on how to build the qt5\docs\*.qch files would be appreciated.

**Comment by MonicaLiu0311** [comment]
This feature has been added, for details, see: [vcpkg.json#L125-L133](https://github.com/microsoft/vcpkg/blob/master/ports/qt5/vcpkg.json#L125-L133)
The path after installation is: `${VCPKG_ROOT}\installed\x64-windows\share\qt5\doc`

**Comment by dg0yt** [comment]
> This feature has been added, for details, see: [vcpkg.json#L125-L133](https://github.com/microsoft/vcpkg/blob/master/ports/qt5/vcpkg.json#L125-L133) The path after installation is: `${VCPKG_ROOT}\installed\x64-windows\share\qt5\doc`
>
> Fixed by https://github.com/microsoft/vcpkg/pull/10644.

No. Just check CI file lists.
qt5 is just a meta port. 
~~~
qt5:x64-windows:/share/qt5/vcpkg.spdx.json
qt5:x64-windows:/share/qt5/vcpkg_abi_info.txt
~~~
For `!windows`, it pulls in `qt5-doc`, but it also doesn't install useful artifacts:
~~~
qt5-doc:x64-linux:/share/qt5-doc/copyright
qt5-doc:x64-linux:/share/qt5-doc/vcpkg.spdx.json
qt5-doc:x64-linux:/share/qt5-doc/vcpkg_abi_info.txt
~~~

**Comment by dg0yt** [comment]
And please change the issue title to match the question. https://github.com/microsoft/vcpkg/issues/19004#issuecomment-882487199

**Comment by mknigh23** [comment]
I have upgraded to Qt6 (version 6.5.3), having installed qtbase, as well as qttools for the Assistant and Designer. But if I try to open Assistant from here - C:\dev\vcpkg\installed\x64-windows\tools\Qt6\bin - I get the following message...

![image](https://github.com/microsoft/vcpkg/assets/8951806/1312601b-7c5c-4a46-b252-009ccb3de047)

I note that the C:\Users\KnightM\AppData\Local\QtProject\Assistant folder contains the QHC file from an old install of Qt, qthelpcollection_5.5.1.qhc. 

The previous Qt5 version allowed me to open Assistant, even though it was empty, but with Qt6, I cannot get past this error.
