### ISSUE TITLE
[qwt] update to 6.2.0

### ISSUE THREAD

**Issue by MehdiChinoune** [microsoft/vcpkg#19003]
Library name: Qt Widgets for Technical Applications (Qwt)

New version number: 6.2.0

Other information that may be useful (release notes, etc...)

https://sourceforge.net/p/qwt/news/2021/07/qwt-620/

**Comment by Neumann-A** [comment]
This update would allow switching qwt to Qt6 instead of Qt5.

**Comment by MehdiChinoune** [comment]
> This update would allow switching qwt to Qt6 instead of Qt5.

That would force some to use Qt6!
Maybe It should be splitted to qwt-qt5 and qwt-qt6.
