### ISSUE TITLE
[New Port Request] sdbus-c++

### ISSUE THREAD

**Issue by AnticliMaxtic** [microsoft/vcpkg#19025]
Library name:
sdbus-c++

Library description:
(From README.md)
sdbus-c++ is a high-level C++ D-Bus library for Linux designed to provide expressive, easy-to-use API in modern C++. It adds another layer of abstraction on top of sd-bus, a nice, fresh C D-Bus implementation by systemd.

Source repository URL:
https://github.com/Kistler-Group/sdbus-cpp/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
