### ISSUE TITLE
Access violation in manifest mode when updating CMake to version 3.21

### ISSUE THREAD

**Issue by upupming** [microsoft/vcpkg#19021]
**Describe the bug**

I use vcpkg in my repo for a long time: https://github.com/upupming/volume-rendering, everything works well but it fails in the last commit. I didn't change anything related to vcpkg, but the vcpkg install is reporting the error. It recommends I look into the `vcpkg-manifest-install.log` file, but the `vcpkg-manifest-install.log` file is empty, which is quite confusing. Could you please help me out with the error, thanks?

**Environment**
- OS: Windows
- Compiler: msvc2019

**To Reproduce**

See the CI build error log: https://github.com/upupming/volume-rendering/runs/3114427732?check_suite_focus=true#step:11:120 

I ran `cat` on the CI, but it seems the log file is empty:

![image](https://user-images.githubusercontent.com/24741764/126333772-88cde55e-6b1c-4ff3-9f14-6df375292f2b.png)
![image](https://user-images.githubusercontent.com/24741764/126333896-4852ab4b-1adf-45f3-a68e-a4444597bbd1.png)

**Comment by NancyLi1013** [comment]
Hi @upupming 
Thanks for posting this issue.

Seems ninja wasn't found. What's the last commit you used?
```
-- Running vcpkg install
-- Running vcpkg install - failed
CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:837 (message):
  vcpkg install failed.  See logs for more information:
  C:\volume-rendering\build\vcpkg-manifest-install.log
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.21/Modules/CMakeDetermineSystem.cmake:124 (include)
  CMakeLists.txt:16 (project)


CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
The parameter is incorrect
CMake Error: Generator: execution of make failed. Make command was:  -j 2 all && 
".\volume-rendering.exe" does not exist.
```

**Comment by upupming** [comment]
@NancyLi1013 Thanks for the help!

Actually, I have installed Ninja and the `ninia --version` outputs this:

![image](https://user-images.githubusercontent.com/24741764/126424341-1cfd3e71-4f3e-4f9e-8184-5b2b4432c8a1.png)
![image](https://user-images.githubusercontent.com/24741764/126424313-922db46c-d526-440f-992b-be64712e3bf8.png)

I believe this is not a Ninja problem, because I have some experience that when CMake with vcpkg fails, it will always complain about Ninja, but the actual problem comes from another where.

The last commit I use is https://github.com/upupming/volume-rendering/commit/7f0194992de2fd5b563e2f09d212751a6cfb320b , I didn't change anything related to vcpkg, but I don't know how to fix this.

**Comment by upupming** [comment]
I have reproduced this error on my PC, it seems to be caused by the **CMake 3.21 update**. Seems GitHub updated their built-in CMake recently, which is not compatible with the lastest Vcpkg. I have to downgrade the CMake manually.

**Comment by NancyLi1013** [comment]
cc @BillyONeal, @strega-nil Could you please help take a look?

**Comment by autoantwort** [comment]
Please do `git pull` and run the `bootstrap-vcpkg.sh` script again and test again, that was a bug in the vcpkg tool.

**Comment by upupming** [comment]
@autoantwort Thanks for your info. After the update, the CI still failed. So could you please help how can I fix this?

**Comment by autoantwort** [comment]
Failed with the same error? Can you try cmake 3.20?

**Comment by upupming** [comment]
> Failed with the same error? Can you try cmake 3.20?

Yes, failed with the same error. And if I use CMake 3.20, everything is okay.

Please see the following CI logs:

- CMake 3.20, passed： https://github.com/upupming/vscode-qt-vcpkg-template/runs/3121053880
- CMake 3.21, errored： https://github.com/upupming/vscode-qt-vcpkg-template/runs/3123835487

**Comment by autoantwort** [comment]
It is still downloading an old release: https://github.com/upupming/vscode-qt-vcpkg-template/runs/3123835487#step:7:115

**Comment by upupming** [comment]
@autoantwort Thanks for point out this! Now after update the vcpkg tool, the CI passes on using CMake 3.21: https://github.com/upupming/vscode-qt-vcpkg-template/runs/3124743234?check_suite_focus=true
