### ISSUE TITLE
vcpkg upgrade is a dangerous command

### ISSUE THREAD

**Issue by cnSchwarzer** [microsoft/vcpkg#19024]
****

**Is your feature request related to a problem? Please describe.**
When we use `vcpkg upgrade` to do a global dependencies upgrade, we can only pray for everything download smoothly. Otherwise, we lost everything.

**Proposed solution**
Before upgrade or do anything manipulating installed list, save it, backup it to prevent lossing. Or write better upgrading code like `apt upgrade` won't lead to information loss if you `Ctrl+C`

**Comment by PhoebeHui** [comment]
Duplicated to issue https://github.com/microsoft/vcpkg/issues/4360, https://github.com/microsoft/vcpkg/discussions/17922
