### ISSUE TITLE
[host triplet]: Always insists on building/installing dependencies for x64-windows even if not using x64-windows triplet

### ISSUE THREAD

**Issue by jumpinjackie** [microsoft/vcpkg#19027]
**Describe the bug**

When wanting to `vcpkg install grpc` for any windows triplet that is not `x64-windows`. The installation plan still insists on installing certain dependencies of `grpc` for `x64-windows`

This also manifests when doing a `vcpkg export` for said triplet as well, with dependencies for `x64-windows` coming along for the ride

**Environment**
- OS: Windows
- Compiler: MSVC 2019
- Vcpkg: Current `master` (as of: 2021-07-21)

**To Reproduce**

1. Install `grpc` with any windows triplet that is not `x64-windows`. eg: `vcpkg.exe install grpc:x64-windows-static`
2. It will produce the following installation plan:

```
Computing installation plan...
The following packages will be built and installed:
  * abseil[core]:x64-windows -> 2021-03-24#1
  * abseil[core]:x64-windows-static -> 2021-03-24#1
  * c-ares[core]:x64-windows -> 1.17.1#1
  * c-ares[core]:x64-windows-static -> 1.17.1#1
  * grpc[codegen,core]:x64-windows -> 1.37.0#2
    grpc[core]:x64-windows-static -> 1.37.0#2
  * openssl[core]:x64-windows -> 1.1.1k#7
  * openssl[core]:x64-windows-static -> 1.1.1k#7
  * protobuf[core]:x64-windows -> 3.15.8#3
  * protobuf[core]:x64-windows-static -> 3.15.8#3
  * re2[core]:x64-windows -> 2020-10-01
  * re2[core]:x64-windows-static -> 2020-10-01
  * upb[core]:x64-windows -> 2020-12-19#1
  * upb[core]:x64-windows-static -> 2020-12-19#1
  * zlib[core]:x64-windows -> 1.2.11#10
  * zlib[core]:x64-windows-static -> 1.2.11#10
Additional packages (*) will be modified to complete this operation.
```

Notice how the following dependencies always build for `x64-windows` in addition to whatever triplet I specified:
 * `abseil[core]`
 * `c-ares[core]`
 * `grpc[codegen,core]`
 * `openssl[core]`
 * `protobuf[core]`
 * `re2[core]`
 * `upb[core]`
 * `zlib[core]`

**Expected behavior**

I would've expected the installation plan to list dependencies to be built/installed for `x64-windows-static` or any other triplet (built-in or custom) that I specified.

**Failure logs** 

N/A

**Additional context**

N/A

**Comment by longnguyen2004** [comment]
This is due to `grpc` having a host dependency on itself, and the default host triplet is `x64-windows`
Add `--host-triplet=x64-windows-static` to the vcpkg command

**Comment by jumpinjackie** [comment]
Thanks for the explanation @longnguyen2004  

I guess my main concern is when using `vcpkg export` where libs for the host triplet (`x64-windows`) are also included and I am very conscious about the final size of the vcpkg export archive being bloated up with libs for a triplet I'm not targeting/consuming. Is this intended behaviour as well?

**Comment by alexsmn** [comment]
Seems to be the same as https://github.com/microsoft/vcpkg/issues/17555

**Comment by Edord99** [comment]
- [ ] 1888

**Comment by vicroms** [comment]
There are cases where ports require tools from other ports in order to build (sometimes even from themselves). So, we built the tools for the host and reuse them for other ports that need them.

It is unfortunate but right now you can't uninstall the host package without having to remove the target package. But we would gladly accept a PR that changes the tool to allow that.
