### ISSUE TITLE
Freetype does not have harfbuzz support (circular dependency)

### ISSUE THREAD

**Issue by Ghabry** [microsoft/vcpkg#1903]
Freetype supports textshaping through Harfbuzz but to compile harfbuzz you need freetype first.

Which means to get a freetype that supports harfbuzz the compile order is:
 - Freetype without Harfbuzz <- in vcpkg
 - Harfbuzz <- in vcpkg
 - Freetype with Harfbuzz <- not in vcpkg

Any idea how to solve this? This would need a "freetype-with-harfbuzz" package that provides "freetype". Can this be expressed with vcpkg?

**Comment by muemart** [comment]
How do other package managers do this?
MSVC apparently supports [mutual imports](https://docs.microsoft.com/en-us/cpp/build/mutual-imports), so technically it's possible to do. But I think that would need to be a single port that builds both libraries itself, and presumably needs a lot of patching for both build systems.

**Comment by ebraminio** [comment]
have a look at https://gist.github.com/roxlu/0108d45308a0434e27d4320396399153#file-cmakelists-txt which support circular dependency of harfbuzz and freetype

**Comment by NancyLi1013** [comment]
Hi @Ghabry thanks for posting this issue.
Currently `freetype`(v2.10.1)  has been one of `harfbuzz`(v2.5.3) dependencies and `harfbuzz ` need to depend on `freetype `to build in vcpkg.

Please try to update vcpkg and use them.

@ebraminio thanks for your all work on this issue.

**Comment by zcream** [comment]
Hi. I can confirm this is still an issue. Is there a patch for the circular dependency?

**Comment by NancyLi1013** [comment]
Hi @zcream 
Thanks for posting this issue again.
Could you please describe the specific issue you met? As for the current status, we cannot fix it that caused by circular dependency in near future.
