### ISSUE TITLE
[binary caching] Failed to push some of the ports to NuGet on Ubuntu

### ISSUE THREAD

**Issue by Pospelove** [microsoft/vcpkg#19038]
## UPDATE: Easy way to reproduce is here https://github.com/Pospelove/vcpkg-nuget-issue

**Describe the bug**
Failed to push some of the ports to NuGet after building (binary caching).

Failed ports:
* boost-regex
* boost-math
* boost-serialization
* mongo-cxx-driver
* sqlite3
* chakracore (overlay port copied from https://github.com/microsoft/vcpkg/pull/18476)

```
Pushing boost-regex_x64-linux.1.75.0-vcpkg2150fdca76f992a7b944e55522732509d47ede13.nupkg to 'https://nuget.pkg.github.com/skyrim-multiplayer'...
  PUT https://nuget.pkg.github.com/skyrim-multiplayer/
An error was encountered when fetching 'PUT https://nuget.pkg.github.com/skyrim-multiplayer/'. The request will now be retried.
Error while copying content to a stream.
  Unable to read data from the transport connection: The socket has been shut down.
  The socket has been shut down
  PUT https://nuget.pkg.github.com/skyrim-multiplayer/
An error was encountered when fetching 'PUT https://nuget.pkg.github.com/skyrim-multiplayer/'. The request will now be retried.
Error while copying content to a stream.
  Unable to read data from the transport connection: The socket has been shut down.
  The socket has been shut down
  PUT https://nuget.pkg.github.com/skyrim-multiplayer/
An error occurred while sending the request.
  The server returned an invalid or unrecognized response.
Pushing NuGet to GitHub failed. Use --debug for more information.
```

**Environment**
- OS: Ubuntu latest (GitHub Actions)
- Compiler: Clang 11
- vcpkg 3c82e1931ea375fd48fcfb42af09990798ee6489

**To Reproduce**
Trigger `.github/workflows/cmake.yml` for https://github.com/skyrim-multiplayer/skymp/pull/85 (last commit hash - 58812850911e8e1488b73be033a0a5d61a7bf551)

**Expected behavior**
Everything should be pushed to NuGet successfully.

**Failure logs** 
https://github.com/skyrim-multiplayer/skymp/runs/3121332869?check_suite_focus=true

See also
https://github.com/NuGet/Home/issues/8580

**Comment by Neumann-A** [comment]
Do you have more than one NuGet binary cache for vcpkg on Github?

**Comment by Pospelove** [comment]
> Do you have more than one NuGet binary cache for vcpkg on Github?

No.

**Comment by JackBoosY** [comment]
Maybe related to https://github.com/microsoft/vcpkg/issues/15289.

**Comment by Pospelove** [comment]
> Maybe related to #15289.

@JackBoosY I could create a sample repo with a minimal reproducible example if it helps.

**Comment by JackBoosY** [comment]
@Pospelove  Yes please.

**Comment by Hoikas** [comment]
This is the same issue I mentioned to @ras0219-msft in discord a few months ago. I saw it with the physx and python3 ports on macOS and Linux.

**Comment by Pospelove** [comment]
@JackBoosY 

It's finally out:
https://github.com/Pospelove/vcpkg-nuget-issue

This is a very minimal repo. The only things it contains are vcpkg submodule, manifest, and a workflow file.

It's based on GitHub Actions because of the [original example](https://github.com/microsoft/vcpkg/blob/f7c83acf486c572d7b1ebe5894dc83bca4f5faef/docs/users/binarycaching.md#github-packages). Please let me know if you need to reproduce this bug locally instead of using GitHub Actions.

**Comment by m-kuhn** [comment]
gdal is also affected

**Comment by PhoebeHui** [comment]
Related to https://github.com/NuGet/Home/issues/8580 and https://github.com/NuGet/Home/issues/10045.

It seems nuget issue on ubuntu, I'm not sure what should vcpkg do here, update the docs? @ras0219-msft @ras0219, could you please take a look?

**Comment by Pospelove** [comment]
Any progress on this?

**Comment by Pospelove** [comment]
![image](https://user-images.githubusercontent.com/37947786/183463821-a5645459-748d-47a5-9c18-99332f316649.png)
![image](https://user-images.githubusercontent.com/37947786/183463840-bdbc5557-2dd8-4ece-8db3-066cb4049ffd.png)
![image](https://user-images.githubusercontent.com/37947786/183463869-d3588bbc-7295-4e78-9b3a-eff974611ded.png)

**Comment by JackBoosY** [comment]
@BillyONeal Any ideas?

**Comment by BillyONeal** [comment]
Nope. We're invoking NuGet and NuGet is failing. Not much we can do I think

**Comment by Pospelove** [comment]
Anyway thanks for taking a look, let's keep this issue open for now

**Comment by SchaichAlonso** [comment]
You need to setup an api key explicitly by running something like

      nuget setapikey "${{ secrets.GITHUB_TOKEN }}" -source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

The [example provided in the documentation on nuget binary caching](https://learn.microsoft.com/en-us/vcpkg/users/binarycaching#quickstart-github) has already been updated.

**Comment by Pospelove** [comment]
> You need to setup an api key explicitly by running something like
> 
> ```
>   nuget setapikey "${{ secrets.GITHUB_TOKEN }}" -source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
> ```
> 
> The [example provided in the documentation on nuget binary caching](https://learn.microsoft.com/en-us/vcpkg/users/binarycaching#quickstart-github) has already been updated.

Thank you for your tip. I'm not working on binary caching in any of my projects atm, so I'll close this issue. I'll reopen this in case of being able to reproduce the original bug.
