### ISSUE TITLE
[New Port Request] Mini-XML

### ISSUE THREAD

**Issue by Dom1n1cB** [microsoft/vcpkg#19042]
Library name: Mini-XML

Library description: Mini-XML is a tiny XML library that you can use to read and write XML and XML-like data files in your application without requiring large non-standard libraries.

Source repository URL: https://github.com/michaelrsweet/mxml

Project homepage (if different from the source repository): https://www.msweet.org/mxml/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.

**Comment by Rossmaxx** [comment]
I have made a pull request here, but I don't really know what I'm doing here.

**Comment by Rossmaxx** [comment]
can anyone reopen this pls?

**Comment by sfhacker** [comment]
This is from 2021!

**Comment by Rossmaxx** [comment]
I am working on adding MSVC support to zynaddsubfx, which uses mxml as a dependency. So i need this port

**Comment by JohannesLorenz** [comment]
@Rossmaxx I also need this port for setting up a Zyn CI. Your mentioned PR still has open checkpoints and an open review comment. Maybe you could finish those and continue asking maintainers for help?
