### ISSUE TITLE
[cctag] Building package cctag failes with: BUILD_FAILED

### ISSUE THREAD

**Issue by sondretordal** [microsoft/vcpkg#19041]
**Host Environment**
- OS: Windows 10
- Compiler: Visual Studio 2019

**To Reproduce**
`./vcpkg install cctag[apps] --triplet x64-windows` or
`./vcpkg install cctag[apps] --triplet x86-windows`

Both fails

**Failure logs** 

**CMD output: x86-windows:**
c:\vcpkg>vcpkg install cctag[apps] --triplet x86-windows
Computing installation plan...
The following packages will be built and installed:
    cctag[apps,core]:x86-windows -> 1.0.0
Detecting compiler hash for triplet x86-windows...
Could not locate cached archive: C:\Users\sondr\AppData\Local\vcpkg\archives\42\428c8b13990f5f36bbbf90f4819af7bd22bea1ff345ea261d635a80debc59f57.zip
Starting package 1/1: cctag:x86-windows
Building package cctag[apps,core]:x86-windows...
-- Using C:/vcpkg/downloads/alicevision-cctag-v1.0.0.tar.gz
-- Cleaning sources at C:/vcpkg/buildtrees/cctag/src/v1.0.0-67692c294b.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg/downloads/alicevision-cctag-v1.0.0.tar.gz
-- Using source at C:/vcpkg/buildtrees/cctag/src/v1.0.0-67692c294b.clean
-- Found external ninja('1.10.2').
-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:155 (message):
    Command failed: C:/vcpkg/downloads/tools/cmake-3.20.2-windows/cmake-3.20.2-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j17
    Working Directory: C:/vcpkg/buildtrees/cctag/x86-windows-dbg
    See logs for more information:
      C:\vcpkg\buildtrees\cctag\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:104 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:44 (vcpkg_build_cmake)
  ports/cctag/portfile.cmake:28 (vcpkg_install_cmake)
  scripts/ports.cmake:141 (include)

Error: Building package cctag:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: cctag:x86-windows
  Vcpkg version: 2021-07-16-3be6b75f6972aa72ca34afce39168094432ea300

Additionally, attach any relevant sections from the log files above.

**CMD output: x64-windows:**
c:\vcpkg>vcpkg install cctag[apps] --triplet x64-windows
Computing installation plan...
The following packages will be built and installed:
    cctag[apps,core]:x64-windows -> 1.0.0
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\sondr\AppData\Local\vcpkg\archives\1e\1e9f75dfbc22d9f60525ad137cd973a56ecff78e8ebe1701b8aaab0e2bf224d4.zip
Starting package 1/1: cctag:x64-windows
Building package cctag[apps,core]:x64-windows...
-- Using C:/vcpkg/downloads/alicevision-cctag-v1.0.0.tar.gz
-- Cleaning sources at C:/vcpkg/buildtrees/cctag/src/v1.0.0-67692c294b.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg/downloads/alicevision-cctag-v1.0.0.tar.gz
-- Using source at C:/vcpkg/buildtrees/cctag/src/v1.0.0-67692c294b.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:155 (message):
    Command failed: C:/vcpkg/downloads/tools/cmake-3.20.2-windows/cmake-3.20.2-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j17
    Working Directory: C:/vcpkg/buildtrees/cctag/x64-windows-dbg
    See logs for more information:
      C:\vcpkg\buildtrees\cctag\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:104 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:44 (vcpkg_build_cmake)
  ports/cctag/portfile.cmake:28 (vcpkg_install_cmake)
  scripts/ports.cmake:141 (include)

Error: Building package cctag:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: cctag:x64-windows
  Vcpkg version: 2021-07-16-3be6b75f6972aa72ca34afce39168094432ea300

Additionally, attach any relevant sections from the log files above.

** Log output from compilation og CCtag library **
Bresenham.cpp.obj : error LNK2019: unresolved external symbol "int __cdecl boost::math::sign<int>(int const &)" (??$sign@H@math@boost@@YAHAEBH@Z) referenced in function "void __cdecl cctag::updateXY(float const &,float const &,int &,int &,float &,int &,int &)" (?updateXY@cctag@@YAXAEBM0AEAH1AEAM11@Z)
Windows-AMD64\CCTagd.dll : fatal error LNK1120: 1 unresolved externals

Seems to me like the above Boost library is not linked properly.

**Additional context**
Have successfully been using CCTag before from [AliceVision fork of VCPKG](https://github.com/alicevision/vcpkg) using the branch `ports/cctag`. This branch is now gone after that CCTag port was recently included in the official VCPKG repository. Unfortunately, the build fails using the official VCPKG.

**Comment by SamyGr** [comment]
Hi @sondretordal,
I have found a way to fix this issue in two steps. It seems to work for the x86 version, not tested with the x64 version.

### Modify CMakeLists
- After one build fails, open the file ```.\vcpkg\buildtrees\cctag\src\v1.0.0-67692c294b\CMakeLists.txt```
- Add **math_c99** to **BOOST_REQUIRED_COMPONENTS** (L113) like this:
```
# FIND BOOST
set(BOOST_REQUIRED_COMPONENTS "atomic;chrono;date_time;filesystem;program_options;serialization;system;thread;timer;math_c99")
```
### Modify Bresenham.cpp
- Open the file ```.\vcpkg\buildtrees\cctag\src\v1.0.0-67692c294b\src\cctag\Bresenham.cpp```
- Add ```#include <boost/math/special_functions/sign.hpp>``` to the beginning of the file

### Re-build the package
- ```.\vcpkg\vcpkg install cctag --editable``` ( --editable is mandatory to avoid deleting files when unzipping the CCTag repo)

Let me know if this works.

**Comment by sondretordal** [comment]
Hi Samy,

Thanks for the fix, Tried it now and it works perfectly when building x86
and x64. So I guess this will be included in the official VCPKG package of
CCTag soon.

**Comment by simogasp** [comment]
FYI the fix has been merged recently in the develop branch of the main repository.
https://github.com/alicevision/CCTag/pull/166

we are preparing a new patch release for cctag and the vcpkg port to include this and other fixes.
