### ISSUE TITLE
[spdlog] update to 1.9.0

### ISSUE THREAD

**Issue by aizuon** [microsoft/vcpkg#19044]
Library name: spdlog

New version number: 1.9.0

Other information that may be useful (release notes, etc...)

https://github.com/gabime/spdlog/releases/tag/v1.9.0

**Comment by NancyLi1013** [comment]
Related PR https://github.com/microsoft/vcpkg/pull/18512

**Comment by NancyLi1013** [comment]
Hi @aizuon 

`Spdlog `has been updated to 1.9.0 in vcpkg now. Please try to update to the latest vcpkg and rebuild this port.
