### ISSUE TITLE
vcpkg tool crashes for `format-manifest` on directory path

### ISSUE THREAD

**Issue by dg0yt** [microsoft/vcpkg#19057]
**Describe the bug**
When calling `vcpkg format-manifest` with a path to a directory, it crashes.

**Environment**
- OS: Linux (Ubuntu 18.04).

**To Reproduce**
1. `./vcpkg format-manifest ports` 
Result:
~~~
vcpkg.exe has crashed.
Please send an email to:
    vcpkg@microsoft.com
containing a brief summary of what you were trying to do and the following data blob:

Version=2021-05-05-unknownhash
EXCEPTION='std::bad_alloc'
CMD=
./vcpkg|
format-manifest|
ports|
~~~

**Expected behavior**
Either report a proper error message, or apply the operation to `vcpkg.json` / `CONTROL` in that directory.

**Comment by JackBoosY** [comment]
`std::bad_alloc`
Can you provide the complete input path?
How many bytes does this path have? Are there spaces? If there is a space, do you enclose it in double quotes?
And can you provide dmp files?

**Comment by dg0yt** [comment]
It is really just `./vcpkg format-manifest ports`.

I thought I had seen this also on Windows, but I can reproduce it only on my Ubuntu 18.04 now. I will update the initial post.

**Comment by dg0yt** [comment]
The vcpkg root / working directory is `/home/dg0yt/Projekte/vcpkg/vcpkg`.

**Comment by PhoebeHui** [comment]
I tried below commands, both works.
```
PS E:\vcpkg\clean\vcpkg> ./vcpkg format-manifest .\ports\3fd\vcpkg.json
Succeeded in formatting the manifest files.
PS E:\vcpkg\clean\vcpkg> ./vcpkg format-manifest --all
Succeeded in formatting the manifest files.
```

**Comment by JackBoosY** [comment]
```
root@usr:/home/usr/work/vcpkg# ./vcpkg  format-manifest /home/usr/work/vcpkg/ports/arrow/vcpkg.json
Succeeded in formatting the manifest files.
```

Please make sure your vcpkg is latest, and check whether your memory is enough.

**Comment by dg0yt** [comment]
You didn't test what I reported: a directory argument, such as `/home/usr/work/vcpkg/ports/arrow` or `ports/arrow`. I know it is not a valid argument ATM, but still the tool shouldn't crash. After all, this is how I stumbled over the bug.

**Comment by PhoebeHui** [comment]
Sorry, I missed that information. It doesn't crash on windows 10.

```
PS E:\vcpkg\clean\vcpkg> ./vcpkg format-manifest 3fd
error reading file: E:\vcpkg\clean\vcpkg\3fd: no such file or directory
PS E:\vcpkg\clean\vcpkg> ./vcpkg format-manifest .\ports\3fd\
error reading file: E:\vcpkg\clean\vcpkg\.\ports\3fd\: no such file or directory
PS E:\vcpkg\clean\vcpkg> ./vcpkg version
Vcpkg package management program version 2021-07-21-244f69e78da4f97034328b4d290db262d748d4c7
See LICENSE.txt for license information.
```

**Comment by JackBoosY** [comment]
```
root@usr:/home/usr/work/vcpkg# ./vcpkg  format-manifest /home/usr/work/vcpkg/ports/arrow
Failed to parse /home/usr/work/vcpkg/ports/arrow: /home/usr/work/vcpkg/ports/arrow:1:1: error: Unexpected EOF; expected value
   on expression:
                  ^

root@usr:/home/usr/work/vcpkg#
```

vcpkg didn't crash, it just reported this error message.

**Comment by autoantwort** [comment]
`std::bad_alloc` is normally only called when you are out of memory. Are you running a low memory system? Maybe restart the computer helps to reduce the memory usage.

**Comment by dg0yt** [comment]
>  Are you running a low memory system? Maybe restart the computer helps to reduce the memory usage.

No, the machine is healthy and strong. (Only that vcpkg builds eat disk space quickly.)

I cannot reproduce it with a build of the current HEAD of vcpkg-tool. I guess it was fixed with https://github.com/microsoft/vcpkg-tool/pull/109 which significantly changed the file reading code.
