### ISSUE TITLE
vcpkg tool fails for `native` platform condition on dependency

### ISSUE THREAD

**Issue by dg0yt** [microsoft/vcpkg#19055]
**Describe the bug**
When the keyword `native` is used in platform expressions of a port or feature dependency, calling vcpkg install fails with 
~~~
Error: Unreachable code was reached
/.../vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-06-29/src/vcpkg/platform-expression.cpp(411)
~~~

Note that according to `git grep "native"`, no current port uses `native`. But it is documented: https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/manifest-files.md#supports

**Environment**
- OS: Linux, Windows

**To Reproduce**
1. Add `  "platform": "native"` to some dependency of port xxxx.
1. ./vcpkg install xxxx
2. See error

**Expected behavior**
Do not fail, but adjust to nativeness.

**Comment by PhoebeHui** [comment]
@dg0yt, thanks for reporting this issue!

This issue can be reproed locally, @strega-nil @strega-nil-ms, could you please take a look?

**Comment by PhoebeHui** [comment]
@dg0yt, the 'native' is used to 'supports' filed, not the 'platform' field.

See [supports](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/manifest-files.md#supports) and [platform](https://github.com/microsoft/vcpkg/blob/master/docs/users/manifests.md#platform-field).

**Comment by dg0yt** [comment]
@PhoebeHui AFAIU `native` *is* a "platform expression".

I see (and saw before) that documentation of `platform` is quite thin, and that documentation of `supports` is explicitly referring to "platform expressions".

In addition, [the user documentation of `supports`](https://github.com/microsoft/vcpkg/blob/master/docs/users/manifests.md#supports) explicitly states that it
  "uses the same platform expressions as "platform", from dependencies, as well as the "supports" field of features."

So please clarify if `native` is a platform expression or not. If yes, it means that the `platforms` field is *not* using (all) platform expressions. If no, then the grammar for `supports` is incomplete.

In any case, `Unreachable code was reached` is unsuitable as a user-facing message. Proposal:
~~~
'native' is not a supported expression for 'platform'.
~~~

**Comment by strega-nil-ms** [comment]
Hmm, this looks like a bug in vcpkg; lemme take a look.

**Comment by strega-nil-ms** [comment]
Mmh, I see it; fixed in https://github.com/microsoft/vcpkg-tool/pull/147

**Comment by PhoebeHui** [comment]
@strega-nil-ms, thanks for fix this issue!

**Comment by dg0yt** [comment]
Fixed in bootstrapped version of vcpkg tool.
