### ISSUE TITLE
[New Port Request] <hackrf>

### ISSUE THREAD

**Issue by ZR233** [microsoft/vcpkg#19063]
Library name:libhackrf

Library description:This repository contains host software (Linux/Windows) for HackRF, a project to produce a low cost, open source software radio platform.

Source repository URL: https://github.com/mossmann/hackrf/tree/master/host

Project homepage (if different from the source repository):https://hackrf.readthedocs.io/en/latest/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
