### ISSUE TITLE
[qt5] No mysqlplugin feature, qt5[all] cannot build

### ISSUE THREAD

**Issue by ZgblKylin** [microsoft/vcpkg#19093]
**Describe the bug**
Port `qt5[all]` depends on a feature called `mysqlplugin`, but there's not such feature in port `qt5`

**Environment**
- OS: Windows 11
- Compiler: 14.29.30037

**To Reproduce**
1. ./vcpkg install qt5[all]
2. See error

**Expected behavior**
`./vcpkg install qt5[all]` should work properly.

**Failure logs** 
```powershell
PS C:\Users\zgblc> vcpkg install qt5[all] --recurse --clean-after-build
Computing installation plan...
Error: could not find feature 'mysqlplugin' in port 'qt5'
```

**Additional context**
Threre's a `mysqlplugin` feature in underlying port `qt5-base`, but no corresponding feature in bundle port `qt5`.

**Comment by JackBoosY** [comment]
cc @Neumann-A

**Comment by JackBoosY** [comment]
Please install `qt5-base[mysqlplugin]`.
