### ISSUE TITLE
ffmpeg build failure

### ISSUE THREAD

**Issue by kelteseth** [microsoft/vcpkg#19096]
**Host Environment**
- OS: Windows
- Compiler: MSVC 2019 16.10

**To Reproduce**
`./vcpkg install ffmpeg ` 32 bit

**Failure logs** 
```
[DEBUG] Feature flag 'versions' unset
[DEBUG] Downloading https://www.tortall.net/projects/yasm/snapshots/v1.3.0.6.g1962/yasm-1.3.0.6.g1962.exe
Error: Failed to download from mirror set:
https://www.tortall.net/projects/yasm/snapshots/v1.3.0.6.g1962/yasm-1.3.0.6.g1962.exe: WinHttpSendRequest() failed: 12175

[DEBUG] C:\a\1\s\src\vcpkg\base\downloads.cpp(626)
[DEBUG] Exiting after 668743 us (665403 us)

 CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:251 (message):

```

**Additional context**

When I click on the link, I get a certificate error. HTTP works fine but is insecure...
![image](https://user-images.githubusercontent.com/1071536/126746579-8a058a38-76e0-4129-b9e4-a3f3c12b059b.png)

**Comment by kelteseth** [comment]
I contacted the webmaster to update the certificate.

**Comment by JackBoosY** [comment]
It's not a vcpkg bug, the upstream should update their certificate.
