### ISSUE TITLE
opencv4 error: The following files are already installed

### ISSUE THREAD

**Issue by Lishen1** [microsoft/vcpkg#19106]
**Describe the bug**
Starting package 1/1: opencv4:arm64-android
Building package opencv4[core,dnn,jpeg,png,quirc,tiff,webp]:arm64-android...
Building package opencv4[core,dnn,jpeg,png,quirc,tiff,webp]:arm64-android... done
Installing package opencv4[core,dnn,jpeg,png,quirc,tiff,webp]:arm64-android...
The following files are already installed in D:/dev/iot/vcpkg/installed/arm64-android and are in conflict with opencv4:arm64-android

Installed by libwebp:arm64-android
    debug/lib/libcpufeaturesd.a
    lib/libcpufeatures.a

 Package: opencv4:arm64-android
 Vcpkg version: 2021-07-21-244f69e78da4f97034328b4d290db262d748d4c7

**Environment**
- OS: Windows
- Compiler: ndk 22.17

**To Reproduce**
1. ./vcpkg install opencv4::arm64-android
2. See error
Repro code when

**Expected behavior**

**Failure logs** 
-(please attached failure logs)

**Additional context**

**Comment by JackBoosY** [comment]
Fine, that's the third same issue I met, I will try to fix that.

**Comment by JackBoosY** [comment]
This issue is a upstream issue: https://github.com/opencv/opencv/issues/9155

But the upstream doesn't fix it completely.
