### ISSUE TITLE
curl no longer loads a root certificate for TLS validation

### ISSUE THREAD

**Issue by henriquegemignani** [Microsoft/vcpkg#1910]
Machine: Windows 10 x64 1703
Locale: en-US
Visual Studio 2017 Professional
Example Code: https://gist.github.com/henriquegemignani/ca8266a5c6def4ec4fc03e689646bfb8

Installed packages:
`vcpkg install curl:x64-windows zlib:x64-windows`

Instructions:
```
mkdir build
cd build
cmake -G "Visual Studio 15 2017 Win64" -T host=x64 -DCMAKE_TOOLCHAIN_FILE=..\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET:STRING=x64-windows ..
cmake --build . --target curltest --config Debug
Debug\curltest.exe
```

Expcted:
The contents of `https://example.com/` being printed on the console.

Actual:
`Request failed: SSL certificate problem: unable to get local issuer certificate`

Context:
This same code previously loaded HTTPS addresess successfully.
This appears to be some kind of bug with OpenSSL not loading some kind of default root CA, or not shipping with one automatically.

**Comment by IntelOrca** [comment]
cURL has been configured to use OpenSSL instead of Windows' certificate store. `CMAKE_USE_WINSSL` should be set when building cURL so that it doesn't require OpenSSL.
