### ISSUE TITLE
[szip,libaec] Replace szip with new port libaec

### ISSUE THREAD

**Issue by dg0yt** [microsoft/vcpkg#19125]
Library name: libaec - Adaptive Entropy Coding library

Library description: Libaec provides fast lossless compression of 1 up to 32 bit wide
signed or unsigned integers (samples). The library achieves best
results for low entropy data as often encountered in space imaging
instrument data or numerical model output from weather or climate
simulations. While floating point representations are not directly
supported, they can also be efficiently coded by grouping exponents
and mantissa.

Source repository URL: https://gitlab.dkrz.de/k202009/libaec/-/tree/master

Additional information:

"Libaec includes a free drop-in replacement for the SZIP library", cf.
https://gitlab.dkrz.de/k202009/libaec/-/blob/master/README.SZIP 
and even in HDF5, "SZIP compression has been replaced by AEC compression as of HDF5-1.10.7", cf. 
https://portal.hdfgroup.org/display/HDF5/Szip+Compression+in+HDF+Products

In contrast, SZIP has special terms for commercial use of encoding, cf.
https://portal.hdfgroup.org/display/HDF5/Szip+Copyright+and+License+Statement%2C+as+Distributed+in+the+HDF+Source+Code

**Comment by Neumann-A** [comment]
> "Libaec includes a free drop-in replacement for the SZIP library"

Needs XOR features so that a metaport for `szip-api` can be created

**Comment by dg0yt** [comment]
AFAIU libaec uses different binary names. Most uses of szip are via HDF5, so the XOR could be implemented there.
(I want to remove szip from default features anyway, given it is special usage terms.)

**Comment by Neumann-A** [comment]
> (I want to remove szip from default features anyway, given it is special usage terms.)

If I remember correctly if you configure HDF5 without any flags yourself it will always include ZLIB and SZIP. 
As such removing it from the defaults is unexpected for users.

**Comment by dg0yt** [comment]
> If I remember correctly if you configure HDF5 without any flags yourself it will always include ZLIB and SZIP.
As such removing it from the defaults is unexpected for users.

SZIP is on, but usage of the encoder defaults to off in HDF5's CMakeLists.txt. This the legally safe default.
But vcpkg activates the encoder together with the (default!) szip feature. This is worrying.

With this background alone, there would three options:
1. szip off,
2. szip decode-only,
3. szip encoding-enabled.

With libaec as a full replacement for szip, it maybe used to
- either drop szip entirely,
- or offer libaec as an alternative implementation to "szip encoding-enabled" with relaxed licensing terms.

Indeed libaec seems to provide binaries with identical names as szip, so libaec and szip cannot be installed at the same time.

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.

**Comment by dg0yt** [comment]
FTR msys2 and brew already did the switch.
