### ISSUE TITLE
Error: Building package llvm:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by AbstractSoft** [Microsoft/vcpkg#1912]
Package: llvm:x86-windows
Vcpkg version: 0.0.90-unknownhash

**Comment by JackBoosY** [comment]
Hi @AbstractSoft , have you forgotten to install mfc component?
If you forgot, the error shows:
> CMake Error at ports/atlmfc/portfile.cmake:7 (message):
  Unable to locate 'afxres.h'.  Ensure you have installed the ATL/MFC
  component of Visual Studio.

And after you install mfc component, it will build successful.

ps: Build llvm need huge disk space(at least 62 GB).

**Comment by JackBoosY** [comment]
Please open a new issue if this is still a problem for you.
Thx.
