### ISSUE TITLE
X_VCPKG_APPLOCAL_DEPS_INSTALL Regression

### ISSUE THREAD

**Issue by Hoikas** [microsoft/vcpkg#19123]
X_VCPKG_APPLOCAL_DEPS_INSTALL does not function as intended if the project CMake includes a `DESTINATION`. Meaning that dependencies are properly deployed in the case of `install(TARGETS foo)` but not in the case of `install(TARGETS foo DESTINATION bar)`.

**Environment**
- OS: Windows 10
- Compiler: Visual Studio 2017, 2019

**To Reproduce**
- [Correct behavior](https://github.com/Hoikas/vcpkg-python3-test/actions/runs/1065788974) in GHA.
- [Incorrect behavior](https://github.com/Hoikas/vcpkg-python3-test/actions/runs/1065794877) in GHA.

**Comment by JackBoosY** [comment]
@Hoikas  Can you explain more?
I can't see any different from you provided CI results.

**Comment by Hoikas** [comment]
The dependency DLLs are not installed in the [incorrect behavior](https://github.com/Hoikas/vcpkg-python3-test/actions/runs/1065794877) result.

**Comment by JackBoosY** [comment]
Confirmed.

**Comment by JackBoosY** [comment]
cc @strega-nil-ms

**Comment by Hoikas** [comment]
[Fixed run](https://github.com/Hoikas/vcpkg-python3-test/actions/runs/1068915902) with #19158

**Comment by Hoikas** [comment]
Closed by #19157
