### ISSUE TITLE
[New Port Request] - CamOdoCal

### ISSUE THREAD

**Issue by abaghiyan** [microsoft/vcpkg#19134]
Library name: CamOdoCal

Library description: CamOdoCal is a C++ library supports the following tasks:

- Intrinsic calibration of a generic camera.
- Extrinsic self-calibration of a multi-camera rig for which odometry data is provided.
- Extrinsic infrastructure-based calibration of a multi-camera rig for which a map generated from task 2 is provided.

Source repository URL: https://github.com/hengli/camodocal

**Comment by abaghiyan** [comment]
Maybe the `devel` branch of this [repo](https://github.com/abaghiyan/camodocal/tree/devel) can help to port CamOdoCal.

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
