### ISSUE TITLE
How do I use a private registry hosted in Azure

### ISSUE THREAD

**Issue by simon-winter** [microsoft/vcpkg#19140]
Hello,
i am trying to setup a private registry for our private company libs. These lay in Azure repos.
After setting up the registry there aswell and trying to build with cmake, the process hangs at:
```
[CMake] -- Running vcpkg install
[CMake] Fetching baseline information from https://dev.azure.com/myCompany/vcpkg-registry...
```
and never continues.

I guess its because vcpkg has no authentication and i couldn't find on how to provide a token/login credentials to vcpkg.

I'm Cross-compiling from VS 2019 to a WSL2 distri with Ubuntu. I can access our azure container registry via cmd line, after using the `az login` commands, but these won't help vcpkg manager as it seems.

For completion i will post the registry setup:
![image](https://user-images.githubusercontent.com/34577718/126960143-400e1561-e809-49c3-b772-16ae12087c94.png)

// versions dir
```
baseline.json

{
  "default": {
    "myLib": {
      "baseline": "1.0.0",
      "port-version": 0
    }
  }
}
```
```
myLib.json
{
  "versions": [
    {
      "version": "1.0.0",
      "port-version":  0,
      "git-tree": "xxxxxxx git sha to ports tree of myLib"
    }
  ]
}
```
// port dir

```
{
  "name": "myLib",
  "version": "1.0.0",
  "description": "A library",
  "homepage": "https://dev.azure.com/pathTo/MyLib"
}
```

```
vcpkg_from_github(
  OUT_SOURCE_PATH SOURCE_PATH
  URL https://dev.azure.com/pathTo/MyLib
  REF 7ceab4684e8c19fxxxxxxxxxxxxxxxxxxxxxxxxxx
  HEAD_REF main
)

vcpkg_configure_cmake(
  SOURCE_PATH "${SOURCE_PATH}"
  PREFER_NINJA
)
vcpkg_install_cmake()
vcpkg_cmake_config_fixup()

file(
  INSTALL "${SOURCE_PATH}/LICENSE"
  DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}"
  RENAME copyright)
```

**Comment by simon-winter** [comment]
Update:
i tried using vcpkg_from_git() instead and also set the "port-version" to 0 in the 3rd codesnipped above.
Additionally i used the git config credentials with a pat like:
`config --global http.https://dev.azure.com/myCompany/xx/_git/*.extraheader "AUTHORIZATION: bearer xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"`

it still hangs on fetching baseline

**Comment by PhoebeHui** [comment]
@simon-winter, can you try the method provided in https://github.com/microsoft/vcpkg/discussions/17272 and see if it works for you? BTW, you should use vcpkg_from_git() instead. vcpkg_from_github used for these ports from github.

**Comment by simon-winter** [comment]
the `git config --global` i tried without success

**Comment by simon-winter** [comment]
Sorry msistake with the closing.

i tried the github config --global solution without success and now try the environment variable one, but the later requreis me to make atleast the registry public. is it not possible with a private registry at all?

**Comment by simon-winter** [comment]
i tried the bottom solution of your link by adding a valid PAT to my permanent env variables in the WSL distri and then passing it to vcpkg upon resolving the lib location :

```
if(DEFINED ENV{MY_TOKEN})
    set(ENV{MY_TOKEN} "$ENV{MY_TOKEN}@")
endif()

vcpkg_from_git(
  OUT_SOURCE_PATH SOURCE_PATH
  URL https://$ENV{MY_TOKEN}dev.azure.com/xxxxx/_git/xxxx
  REF 7ceab4684exxxxxxxxxxxxxxxxxxxxxx
  HEAD_REF main
)

vcpkg_configure_cmake(
  SOURCE_PATH "${SOURCE_PATH}"
  PREFER_NINJA
)


vcpkg_install_cmake()
vcpkg_cmake_config_fixup()

file(
  INSTALL "${SOURCE_PATH}/LICENSE"
  DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}"
  RENAME copyright)
```

The registry i made public for now. VCPKG now successfully fetches the custom registry, but crashes upon installation:

```
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
    Command failed: /mnt/c/vcpkg/downloads/tools/cmake-3.20.2-linux/cmake-3.20.2-linux-x86_64/bin/cmake /mnt/c/vcpkg/buildtrees/xxx/src/c69f1703f7-04638364ae.clean -DCMAKE_MAKE_PROGRAM=/mnt/c/vcpkg/downloads/tools/ninja/1.10.2-linux/ninja -DCMAKE_SYSTEM_NAME=Linux -DBUILD_SHARED_LIBS=OFF -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/mnt/c/vcpkg/scripts/toolchains/linux.cmake -DVCPKG_TARGET_TRIPLET=x64-linux -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=external -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=/mnt/c/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_LINKER_FLAGS_RELEASE= -DVCPKG_LINKER_FLAGS_DEBUG= -DVCPKG_TARGET_ARCHITECTURE=x64 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -D_VCPKG_ROOT_DIR=/mnt/c/vcpkg -D_VCPKG_INSTALLED_DIR=/mnt/c/Users/xxxx/source/repos/xxxxx/out/build/WSL-GCC-Debug/vcpkg_installed -DVCPKG_MANIFEST_INSTALL=OFF -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/mnt/c/vcpkg/packages/xxxxxx64-linux/debug
    Working Directory: /mnt/c/vcpkg/buildtrees/xxxxx/x64-linux-dbg
    Error code: 1
    See logs for more information:
      /mnt/c/vcpkg/buildtrees/xxxxxxx/config-x64-linux-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:332 (vcpkg_execute_required_process)
  /home/hmi/.cache/vcpkg/registries/git-trees/e9848c7c278d6d3f4264f692ca39f17881a7ad0f/portfile.cmake:12 (vcpkg_configure_cmake)
  scripts/ports.cmake:139 (include)


Error: Building package xxxxx:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: plchandler:x64-linux
  Vcpkg version: 2021-05-05-unknownhash

```

**Comment by simon-winter** [comment]
ok this seems to be my fault , because our lib was not ready for a complete cmake install.
But i still ahve to use a public registry. Is there no waya of pasing argumets in the vcpkg-configuration to reach a registry with a set of credentials?

**Comment by PhoebeHui** [comment]
@simon-winter, could you ask above question in https://github.com/microsoft/vcpkg/discussions/17272?

Closing in favor of https://github.com/microsoft/vcpkg/discussions/17272.
