### ISSUE TITLE
Older solution doesn't work with vcpkg, no host-triplet option

### ISSUE THREAD

**Issue by jdx-john** [microsoft/vcpkg#19152]
I've recently rebuilt vcpkg and new VS2019 projects work fine with vcpkg, and give me options like this:
![image](https://user-images.githubusercontent.com/1654627/127012944-c022e414-5a05-4505-b784-2c5fbc1b7850.png)

However when I opened an older VS2019 project I used to use for vcpkg testing, none of my includes to vcpkg headers were found. In the project settings, I noticed the "host triplet" option is missing, is this a clue? Could project settings be screwed up somehow?

![image](https://user-images.githubusercontent.com/1654627/127013578-4cb7eb8d-fd42-4729-9d52-3c409ab06d0a.png)

**Comment by NancyLi1013** [comment]
Hi @jdx-john 

Thanks for posting this issue.
Could you please try to integrate your project again? Please also check if the libraries required for old project are listed in the same repo with the libraries required for new project.

**Comment by jdx-john** [comment]
@NancyLi1013 reintegrating was what I tried first (and re-starting VS). The libraries used are ones we are already using in other projects against the same triplet.

**Comment by NancyLi1013** [comment]
So you used the same integration with these two projects, right? 

Could you please try to run `bootstrap-vcpkg.bat` and reintegrate the project?

If still the same problem, please try to remove integrate and reintegrate. Then restart VS.

**Comment by autoantwort** [comment]
Maybe the same as #18337, there is also a workaround you could try

**Comment by jdx-john** [comment]
@NancyLi1013 yeah everything is the same - and other old projects work just fine. Reintegration etc don't help. It's only a throwaway test project so it's not really a problem but I am curious. I might look at the vcxproj file to see if something has got messed up. If I find anything I'll report back.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. This issue hasn’t been updated in three months. Please reopen this issue if this is still a problem for you.
