### ISSUE TITLE
Boost regex compile error

### ISSUE THREAD

**Issue by jdx-john** [microsoft/vcpkg#19153]
I am getting this problem, initially in an existing code-base so I created a brand-new Console project to test:

```
#include <boost/regex/v4/regex.hpp>
#include <iostream>

int main()
{
    std::cout << "Hello World!\n";
}
```
> Error | C2027 | use of undefined type 'boost::mpl::bool_<true>' | vcpkgTest | C:\github\microsoft\vcpkg\installed\x86-windows\include\boost\regex\v4\basic_regex_parser.hpp | 59 |  

I'm building on VS2019, using default v142 libraries and C++17. Many other ports work fine, including using boost. It seems specific to regex could there be an issue? Using boost 1.76 (latest).

**Comment by PhoebeHui** [comment]
@jdx-john, thanks for reporting this issue, I can repro this issue locally. However, It looks a source issue, I reported an issue to Upstream https://github.com/boostorg/regex/issues/145.

**Comment by jdx-john** [comment]
I'm happy with the response upstream @PhoebeHui so I'll close this.
