### ISSUE TITLE
Integrate per project - how to choose static library version?

### ISSUE THREAD

**Issue by aPSopt** [Microsoft/vcpkg#1916]
I create simple application, add vcpkg per project integration, use boost filesystem.
After compilation I go to the build directory and see the boost filesystem .dll near my .exe.
But I want to use static version of boost library!
How to choose static verion in this case?

**Comment by ras0219-msft** [comment]
The per-project integration acts _exactly_ the same as the user-wide integration from your project's perspective, so you can use the same mechanism to switch triplets:
```xml
<PropertyGroup Label="Globals">
    ....
    <VcpkgTriplet>x86-windows-static</VcpkgTriplet>
    <VcpkgEnabled>true</VcpkgEnabled>
</PropertyGroup>
```

https://blogs.msdn.microsoft.com/vcblog/2016/11/01/vcpkg-updates-static-linking-is-now-available/

**Comment by aPSopt** [comment]
I create porperty sheet as writed on your link wuth content:

```
<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<PropertyGroup Label="Globals">
        <VcpkgTriplet>x64-windows-static</VcpkgTriplet>
        <VcpkgEnabled>true</VcpkgEnabled>
    </PropertyGroup>
</Project>
```

I aad it to the project but I received linkage error:

> 1>------ Build started: Project: AKnowledgeBase, Configuration: Debug x64 ------
> 1>boost_system-vc140-mt-gd-1_65_1.lib(error_code.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in moc_AKnowledgeBase.obj
> 1>LINK : warning LNK4098: defaultlib 'LIBCMTD' conflicts with use of other libs; use /NODEFAULTLIB:library

Why it happens and how it could be fixed?

**Comment by ras0219-msft** [comment]
By default, our `x-y-static` triplets build using the _static_ CRT (aka the `/MT` switch). You could either modify the triplet / make a new triplet with dynamic CRT but static libraries or you could switch your project to static link the CRT [1].

[1] https://stackoverflow.com/questions/37398/how-do-i-make-a-fully-statically-linked-exe-with-visual-studio-express-2005
