### ISSUE TITLE
[libarchive] segmentation fault inside Windows GitHub Actions runner

### ISSUE THREAD

**Issue by otavio** [microsoft/vcpkg#19169]
**Host Environment**
- OS: Windows
- Compiler: vcpkg commit 5568f110b509a9fd90711978a7cb76bae75bb092 # 2021.05.12

**To Reproduce**
`./vcpkg install libarchive:x86-windows`

**Failure logs** 
https://github.com/OSSystems/compress-tools-rs/runs/3161186196#step:3:186

**Additional context**
It is very weird as vcpkg stars to comput its execution plan and dies. I tried to go to newer release and it fails same way.

**Comment by autoantwort** [comment]
Duplicate of #18636, please update vcpkg or use cmake 3.20 :)

**Comment by otavio** [comment]
In this case, it'd be nice to have a new release so we could use it. I updated to the latest stable release, and it failed. So now I am using master, but this is not very user-friendly...

Using master does fix it. Thanks for letting me know.

**Comment by autoantwort** [comment]
Yeah there are no real releases because you could tag every commit on the master branch as release

**Comment by JonLiu1993** [comment]
@otavio ,Thanks for posting this issue,
good solutions and suggestions have been given above.

**Comment by otavio** [comment]
Yes, using master did the trick, but it'd be good to make a release with this fix. Unfortunately, it is tough to figure out what is happening.

**Comment by JonLiu1993** [comment]
Please wait for a stable version to be released
