### ISSUE TITLE
[openmpi] build failure

### ISSUE THREAD

**Issue by Henderz** [microsoft/vcpkg#19178]
[build-x64-linux-dbg-err.log](https://github.com/microsoft/vcpkg/files/6889593/build-x64-linux-dbg-err.log)
[build-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/6889594/build-x64-linux-dbg-out.log)
**Host Environment**
- OS: Ubuntu 20.04.2.0
- Compiler: gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

**To Reproduce**
`./vcpkg install openmpi`

**Failure logs** 
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:155 (message):
    Command failed: /usr/bin/make V=1 -j 1 -f Makefile all
    Working Directory: /home/rin/Documents/Workspace/vcpkg/buildtrees/openmpi/x64-linux-dbg
    See logs for more information:
      /home/rin/Documents/Workspace/vcpkg/buildtrees/openmpi/build-x64-linux-dbg-out.log
      /home/rin/Documents/Workspace/vcpkg/buildtrees/openmpi/build-x64-linux-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_make.cmake:188 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_make.cmake:26 (vcpkg_build_make)
  ports/openmpi/portfile.cmake:35 (vcpkg_install_make)
  scripts/ports.cmake:141 (include)

Error: Building package openmpi:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openmpi:x64-linux
  Vcpkg version: 2021-07-26-unknownhash

**Comment by autoantwort** [comment]
https://stackoverflow.com/questions/9066080/what-is-lnuma-and-what-program-uses-it-for-compilation

Seems that you have to install numa from your package manager

**Comment by Henderz** [comment]
> https://stackoverflow.com/questions/9066080/what-is-lnuma-and-what-program-uses-it-for-compilation
> 
> Seems that you have to install numa from your package manager

Thank you @autoantwort! That did it. 
I ran "apt-get install libnuma-dev"
