### ISSUE TITLE
SUFFIX setups are not working

### ISSUE THREAD

**Issue by jackzenko** [microsoft/vcpkg#19186]
I wanted to add suffix to the DLLs for x64 build, so it can be differentiated from x86 version under same folder.
However following definitions are not working, no suffix was added to build target

VCPKG_TARGET_STATIC_LIBRARY_SUFFIX       static library suffix for target (same as CMAKE_STATIC_LIBRARY_SUFFIX)
VCPKG_TARGET_SHARED_LIBRARY_SUFFIX       shared library suffix for target (same as CMAKE_SHARED_LIBRARY_SUFFIX)
VCPKG_TARGET_IMPORT_LIBRARY_SUFFIX       import library suffix for target (same as CMAKE_IMPORT_LIBRARY_SUFFIX)

**Environment**
- OS: Windows 10 64bit
- Compiler: VS2015

**To Reproduce**
1. add following 3 lines to VCPKG_PATH\triplets\x64-windows.cmake
set(VCPKG_TARGET_STATIC_LIBRARY_SUFFIX "_x64")
set(VCPKG_TARGET_SHARED_LIBRARY_SUFFIX "_x64")
set(VCPKG_TARGET_IMPORT_LIBRARY_SUFFIX "_x64")

2. execute "vcpkg install icu:x64-windows" to compile and install icu libraries

3. find DLL files under VCPKG_PATH\packages\icu_x64-windows, all files are in original names such as "icudt69.dll"

**Expected behavior**
all files should be with _x64 suffix such as "icudt69_x64.dll"

**Additional Information**

I also tried to add these 3 lines to VCPKG_PATH\ports\icu\portfile.cmake
same result, no suffix was added.

For debugging purposes, entire content in x64-windows.cmake file is pasted below:
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_PLATFORM_TOOLSET v140)
set(VCPKG_BUILD_TYPE release)
set(VCPKG_TARGET_STATIC_LIBRARY_SUFFIX "_x64")
set(VCPKG_TARGET_SHARED_LIBRARY_SUFFIX "_x64")
set(VCPKG_TARGET_IMPORT_LIBRARY_SUFFIX "_x64")

**Comment by JackBoosY** [comment]
`VCPKG_TARGET_STATIC_LIBRARY_SUFFIX`, `VCPKG_TARGET_SHARED_LIBRARY_SUFFIX` and `VCPKG_TARGET_IMPORT_LIBRARY_SUFFIX` are only used in `portfile.cmake` to get the specific file name, not to set it to change the build process. See
https://github.com/microsoft/vcpkg/blob/1257354a3ab0bebd8abe95281ca561537853578c/scripts/cmake/vcpkg_common_definitions.cmake#L7-L25

We respect the library name specified by the upstream without changing it.

**Comment by jackzenko** [comment]
is there a way to add prefix/suffix to generated libs so we can differentiate x86/x64 files?
for example:
icudt69.dll for 32 bit version
icudt69_x64.dll for 64 bit version

in addition, changing name isnt an issue, which can even done by hand. but setting libs to call correct dlls is a problem, after building icu 64 bits version by vcpkg, all files are generated with exact same name as 32 bits, even i manually change file name to icudt69_x64.dll, the 64 bits version icuuc.lib still calls icudt69.dll which is 32 bits version, and it caused app failure eventually.

**Comment by JackBoosY** [comment]
@jackzenko  You can add a patch to modify the configure.ac / makefile in icu's source then use overlay-port feature to install the custom icu.

**Comment by Neumann-A** [comment]
Only CMake projects can be easily suffixed (via a custom toolchain). Everything else needs a lot more work.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
