### ISSUE TITLE
rocksdb: unresolved external symbol

### ISSUE THREAD

**Issue by planninghippo** [microsoft/vcpkg#1918]
Hi,

I ran the following to install rocksdb:
vcpkg install rocksdb:x64-windows

Now, when I build my small program:

    #include "rocksdb\db.h"
    int main()
    {
        rocksdb::DB* db;
        rocksdb::Options options;
        options.create_if_missing = true;
        rocksdb::Status status = rocksdb::DB::Open(options, "testdb", &db);
    }

I get the following link errors:
1>ConsoleApplication2.obj : error LNK2001: unresolved external symbol "public: __cdecl rocksdb::DBOptions::DBOptions(void)" (??0DBOptions@rocksdb@@QEAA@XZ)
1>ConsoleApplication2.obj : error LNK2001: unresolved external symbol "public: __cdecl rocksdb::ColumnFamilyOptions::ColumnFamilyOptions(void)" (??0ColumnFamilyOptions@rocksdb@@QEAA@XZ)

Do you know what I missed? Note that I ran 'vcpkg integrate install' as well.

Thanks,

**Comment by ras0219-msft** [comment]
Thanks for posting this issue!

It looks like they didn't export those symbols, oddly enough. I'll look at upgrading the port to 5.8 -- in the meantime, you might try a static build by adding
```cmake
set(VCPKG_LIBRARY_LINKAGE static)
```
to the top of `ports\rocksdb\portfile.cmake` and then running `remove`/`install`.

**Comment by sauravyad500** [comment]
Tell me how and where to build/run this program Please include the links I can solve the problem.

**Comment by JackBoosY** [comment]
Hi @planninghippo, thanks for reporting this issue.
I've fixed this issue, please update vcpkg and rebuild rocksdb.

Thanks.
