### ISSUE TITLE
A linking error LNK2001

### ISSUE THREAD

**Issue by NeoxyCN** [microsoft/vcpkg#19198]
I'm using Windows 10 Pro 2004. I successfully ran "vcpkg install glew" and "vcpkg install glfw3".
Then I ran "vcpkg integrate install"
I coding in Visual Studio 2017 Verison 15.9.36.
When I clicked "Local Windows Debugger", an error happened.

> error LNK2001: unresolved external symbol _glewExperimental

```
#include <stdio.h>
#define GLEW_STATIC
#include <gl/glew.h>
#include "GLFW/glfw3.h"

void keyCallback(GLFWwindow* window, int key, int scancode, int action, int mode);

int main() {

	// initialize GLFW
	glfwInit();
	glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
	glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);
	glfwWindowHint(GLFW_RESIZABLE, GL_FALSE);
	GLFWwindow* window = glfwCreateWindow(800, 600, "Main Window", NULL, NULL);
	if (window == NULL) {
		printf("Failed to create window\n");
		glfwTerminate();
		return -1;
	}
	glfwMakeContextCurrent(window);
	glewExperimental = GL_TRUE;
	if (glewInit() != GLEW_OK) {
		printf("Failed to initialize GLEW\n");
		return -1;
	}
	
	glfwSetKeyCallback(window, keyCallback);
	int width, height;
	glfwGetFramebufferSize(window, &width, &height);
	glViewport(0, 0, width, height);

	while (!glfwWindowShouldClose(window))
	{
		glfwPollEvents();
		glfwSwapBuffers(window);
	}
	glfwTerminate();
	return 0;
}

void keyCallback(GLFWwindow* window, int key, int scancode, int action, int mode) {
	if (key == GLFW_KEY_ESCAPE && action == GLFW_PRESS) {
		glfwSetWindowShouldClose(window, GL_TRUE);
	}
}
```
thx

**Comment by NeoxyCN** [comment]
I also ran "vcpkg integrate project".

**Comment by autoantwort** [comment]
When I google for your error I found https://stackoverflow.com/questions/49391509/unresolved-external-symbol-glewexperimental

Seems like you installed 32 bit apps but build 64 bit?
Then you need to install `vcpkg install glew glfw3 --triplet=x64-windows`

**Comment by NeoxyCN** [comment]
> 
> 
> When I google for your error I found https://stackoverflow.com/questions/49391509/unresolved-external-symbol-glewexperimental
> 
> Seems like you installed 32 bit apps but build 64 bit?
> Then you need to install `vcpkg install glew glfw3 --triplet=x64-windows`

Thank you.
When I saw that answer, I realized that GLEW_STATIC should not be defined when target platform is dynamic.
If anyone who need static compilation, he shoud add glews.lib into additional library dictionary.
