### ISSUE TITLE
How do I add a compile parameter to support ssl when I compile the libevent?

### ISSUE THREAD

**Issue by shelman-zl** [microsoft/vcpkg#19215]
When asking a question please also include where you looked for an answer (so we can update the documentation if needed).
I wanna to compile the libevent, and it must support ssl, how can I add the compile the parameter?
I use: ./vcpkg install libevent, so I wanna compile to support ssl, I use ./vcpkg install libevent[ssl] does not work...

**Comment by shelman-zl** [comment]
@JonLiu1993 Hello, How can I add the "category:port-feature"? please give me the detail example, thank you.

**Comment by JonLiu1993** [comment]
> @JonLiu1993 Hello, How can I add the "category:port-feature"? please give me the detail example, thank you.

You can refer to it after I submit pr

**Comment by shelman-zl** [comment]
@JonLiu1993 thank you, I think I have solved this issue, I just modify the /ports/libevent/portfile.cmake file, as:
vcpkg_check_features(OUT_FEATURE_OPTIONS FEATURE_OPTIONS
    INVERTED_FEATURES
**_#    openssl EVENT__DISABLE_OPENSSL
#    thread  EVENT__DISABLE_THREAD_SUPPORT_**
)

I commented the openssl EVENT__DISABLE_OPENSSL and thread  EVENT__DISABLE_THREAD_SUPPORT, and add a define as: \
vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA
    OPTIONS ${FEATURE_OPTIONS}
        -DEVENT__LIBRARY_TYPE=${LIBEVENT_LIB_TYPE}
        -DEVENT__MSVC_STATIC_RUNTIME=${LIBEVENT_STATIC_RUNTIME}
        -DEVENT__DISABLE_BENCHMARK=ON
        -DEVENT__DISABLE_TESTS=ON
        -DEVENT__DISABLE_REGRESS=ON
        -DEVENT__DISABLE_SAMPLES=ON
	_**-DEVENT__HAVE_OPENSSL=TRUE**_
)

-DEVENT__HAVE_OPENSSL=TRUE, it works.
