### ISSUE TITLE
[cfitsio] build failure

### ISSUE THREAD

**Issue by KalgogSmash** [microsoft/vcpkg#19212]
**Host Environment**
- OS: [Windows 10 Pro]
- Compiler: 19.29.30037

**To Reproduce**

'vcpkg install cfitsio --triplet=x64-windows'

**Failure logs** 
Computing installation plan...
The following packages will be built and installed:
    cfitsio[core]:x64-windows -> 3.49#1
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\c110282\AppData\Local\vcpkg\archives\34\3425fac40a540df2bf0800257558b556ab8eb4f1029c36c6cdb28aa454e3ec88.zip
Starting package 1/1: cfitsio:x64-windows
Building package cfitsio[core]:x64-windows...
-- Using C:/GDAL/vcpkg/downloads/cfitsio-3.49.tar.gz
-- Cleaning sources at C:/GDAL/vcpkg/buildtrees/cfitsio/src/cfitsio-3-e0a21ee3a7.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/GDAL/vcpkg/downloads/cfitsio-3.49.tar.gz
-- Applying patch 0001-fix-dependencies.patch
-- Applying patch 0002-export-cmake-targets.patch
-- Applying patch 0003-add-Wno-error-implicit-funciton-declaration-to-cmake.patch
-- Applying patch 0004-pkg-config.patch
-- Using source at C:/GDAL/vcpkg/buildtrees/cfitsio/src/cfitsio-3-e0a21ee3a7.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: ninja -v
    Working Directory: C:/GDAL/vcpkg/buildtrees/cfitsio/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\GDAL\vcpkg\buildtrees\cfitsio\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:340 (vcpkg_execute_required_process)
  ports/cfitsio/portfile.cmake:39 (vcpkg_configure_cmake)
  scripts/ports.cmake:141 (include)

Error: Building package cfitsio:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: cfitsio:x64-windows
  Vcpkg version: 2021-07-21-244f69e78da4f97034328b4d290db262d748d4c7

[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/6896667/config-x64-windows-out.log)

**Additional context**
This happened in the context of trying to install gdal. I ran the cfitsio installation standalone with the same result.

**Comment by NancyLi1013** [comment]
Hi @KalgogSmash 

Thanks for posting this issue.

Could you please help check if you have installed `zlib:x64-windows `on your machine?
```
CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.20/Modules/FindZLIB.cmake:120 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  C:/GDAL/vcpkg/scripts/buildsystems/vcpkg.cmake:797 (_find_package)
  CMakeLists.txt:141 (FIND_PACKAGE)
```

**Comment by KalgogSmash** [comment]
@NancyLi1013 yes, I confirmed ZLIB is installed:

C:\GDAL\vcpkg>vcpkg install zlib:x64-windows
Computing installation plan...
The following packages are already installed:
    zlib[core]:x64-windows -> 1.2.11#11
Package zlib:x64-windows is already installed

Total elapsed time: 831.2 us

**Comment by NancyLi1013** [comment]
Closing this issue for now, please feel free to reopen this issue if this is still a problem for you.
