### ISSUE TITLE
[VTK] How can I use QVTKWidget in QT Disigner?

### ISSUE THREAD

**Issue by jjjkkyz** [microsoft/vcpkg#19217]
IN origin VTK installed, I will have QVTKWidget.dll in bin folder.
And I can put It into Qt designer plugins folder to import it.

But in vcpkg-builded vtk[core, qt], I can't find QVTKWidget.dll.
Although I still can use QVTKXXXXWidget, but it's not very convience.

So I am wonder is there any way to import QVTKWidget into Qt desinger？

**Comment by JackBoosY** [comment]
cc @cenit @Neumann-A

**Comment by LilyWangLL** [comment]
Ping @cenit @Neumann-A, could you help take a look this issue? Thanks in advance.

**Comment by Neumann-A** [comment]
> Ping @cenit @Neumann-A, could you help take a look this issue? Thanks in advance.

This is not a vcpkg issues. There needs to be a designer plugin to directly use it. Otherwise promoting the normal widgets is probably the way to go but I am not an expert in Qt Designer.

**Comment by JackBoosY** [comment]
> > Ping @cenit @Neumann-A, could you help take a look this issue? Thanks in advance.
> 
> This is not a vcpkg issues. There needs to be a designer plugin to directly use it. Otherwise promoting the normal widgets is probably the way to go but I am not an expert in Qt Designer.

Thanks!
@jjjkkyz  So please report this to the upstream qt side.

**Comment by Neumann-A** [comment]
> @jjjkkyz So please report this to the upstream qt side.

More like asking on the VTK discourse probably
