### ISSUE TITLE
[<libxmlpp>] libxml3 support

### ISSUE THREAD

**Issue by Baklap4** [microsoft/vcpkg#19211]
****

**Is your feature request related to a problem? Please describe.**
Are there any plans in supporting libxml++3?

**Proposed solution**
Build it when wanted

**Comment by PhoebeHui** [comment]
@Baklap4, vcpkg has update libxmlpp to lastest version https://download.gnome.org/sources/libxml++/5.0/, does that match your requirements?

**Comment by Baklap4** [comment]
Sadly i can't quite port to libxmlpp 5 as of yet :( I've tried to add it yesterday, but got into a dependency hell with glibmm

**Comment by PhoebeHui** [comment]
@Baklap4, we recommend to use [overlay ports](https://github.com/microsoft/vcpkg/blob/master/docs/specifications/ports-overlay.md#3-proposed-solution) instead, you can change the libxmlpp to the version you want in your own ports.
