### ISSUE TITLE
[New Port Request] <pbrt-v4>

### ISSUE THREAD

**Issue by abaghiyan** [microsoft/vcpkg#19222]
Library name: pbrt, Version 4

Library description: Physically Based Rendering library contains many useful and efficient methods for 3D Geometry and Image Reconstruction for photorealistic computer graphics.

Source repository URL: https://github.com/mmp/pbrt-v4

Project homepage: https://pbrt.org/

Anything else that is useful to know when adding: Library has GPU support, so it would be great if CPU and GPU separately supported versions were available.

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
