### ISSUE TITLE
Windows build issue

### ISSUE THREAD

**Issue by qraz** [Microsoft/vcpkg#1922]
I just started with vcpkg to build rocksdb and its dependencies on Windows 7, VS 2015.

I used "x64-windows-static" option to build them. Though the libraries were created successfully, I noticed that for zlib build, the lib size of "release" version (414 KB) was actually bigger than "debug" (353 KB).

I'm not sure if this is anything to do with my system.

**Comment by ras0219-msft** [comment]
Thanks for posting!

This is quite reasonable if some loops got unrolled for performance reasons. I wouldn't be concerned unless you experience other issues.
