### ISSUE TITLE
[tensorflow-cc] build failure

### ISSUE THREAD

**Issue by ianmcook** [microsoft/vcpkg#19235]
**Host Environment**
`x64-windows`

**To Reproduce**
`./vcpkg install tensorflow-cc:x64-windows-static`

**Failure logs** 
Install log shows this error:
```
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: C:/vcpkg/downloads/tools/msys2/b3b3d399e80e310e/mingw64/bin/python3.exe C:/vcpkg/buildtrees/tensorflow-cc/x64-windows-static-dbg/configure.py --workspace C:/vcpkg/buildtrees/tensorflow-cc/x64-windows-static-dbg
    Working Directory: C:/vcpkg/buildtrees/tensorflow-cc/x64-windows-static-dbg
    Error code: 1
    See logs for more information:
      C:\vcpkg\buildtrees\tensorflow-cc\config-x64-windows-static-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows-static/share/tensorflow-common/tensorflow-common.cmake:151 (vcpkg_execute_required_process)
  ports/tensorflow-cc/portfile.cmake:7 (include)
  scripts/ports.cmake:141 (include)
```

`config-x64-windows-static-dbg-out.log` shows this:
```
You have bazel 4.1.0 installed.
Please downgrade your bazel installation to version 3.99.0 or lower to build TensorFlow! To downgrade: download the installer for the old version (from https://github.com/bazelbuild/bazel/releases) then run the installer.
```

**Additional context**
This seems to have been caused by this change to `scripts/cmake/vcpkg_find_acquire_program.cmake` on 2021-07-22 which updated Bazel to 4.1.0:
https://github.com/microsoft/vcpkg/commit/16aeda9c214e7eaac314e5977f4204c1ba5a645f#diff-151d9ba93b4be2dfa98ec4f962bd066169262d77d1ae72b256db570329f7d898R399

**Comment by PhoebeHui** [comment]
PR https://github.com/microsoft/vcpkg/pull/19165 would fix this issue.

**Comment by NancyLi1013** [comment]
Hi @ianmcook 

Since PR #19165 has been merged, this issue should be fixed now. Please update to the latest vcpkg via `git pull` to rebuild this.
