### ISSUE TITLE
[bullet3] find_package failure

### ISSUE THREAD

**Issue by skaarj1989** [microsoft/vcpkg#19234]
**Host Environment**
- OS: `Windows10` and `Ubuntu 20.04.1 LTS`
- Compiler: `Microsoft Visual C++ 2019`
- CMake: `3.16.3` and `3.21.1`

**To Reproduce**
`./vcpkg install bullet3`

```cmake
find_package(Bullet CONFIG REQUIRED)
```

**Failure logs** 
```
CMake Error at D:/dev/vcpkg/installed/x64-windows/share/bullet3/BulletConfig.cmake:18 (set_and_check):
  Unknown CMake command "set_and_check".
Call Stack (most recent call first):
  D:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:782 (_find_package)
  CMakeLists.txt:23 (find_package)
```

**Additional context**
Previous version (2.89-1) worked just fine.

**Comment by JackBoosY** [comment]
This issue is related to the cmake version.
