### ISSUE TITLE
[grpc] build failure

### ISSUE THREAD

**Issue by ivanshilo** [microsoft/vcpkg#19232]
**Host Environment**
- OS: Windows 10
- Compiler: MS VS 2017

**To Reproduce**
`./vcpkg install grpc:x64-windows`

**Failure logs** 
Building package grpc[codegen,core]:x64-windows...
-- Note: grpc only supports static library linkage. Building static library.
-- Using C:/grpc/vcpkg/downloads/grpc-grpc-44c40ac23023b7b3dd82744372c06817cc203898.tar.gz
-- Cleaning sources at C:/grpc/vcpkg/buildtrees/grpc/src/17cc203898-d61717d122.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/grpc/vcpkg/downloads/grpc-grpc-44c40ac23023b7b3dd82744372c06817cc203898.tar.gz
-- Applying patch 00001-fix-uwp.patch
-- Applying patch 00002-static-linking-in-linux.patch
-- Applying patch 00003-undef-base64-macro.patch
-- Applying patch 00004-link-gdi32-on-windows.patch
-- Applying patch 00005-fix-uwp-error.patch
-- Applying patch 00009-use-system-upb.patch
-- Applying patch 00010-add-feature-absl-sync.patch
-- Applying patch 00011-fix-csharp_plugin.patch
-- Applying patch snprintf.patch
-- Applying patch 00012-fix-use-cxx17.patch
-- Applying patch 00013-build-upbdefs.patch
-- Applying patch 00014-pkgconfig-upbdefs.patch
-- Using source at C:/grpc/vcpkg/buildtrees/grpc/src/17cc203898-d61717d122.clean
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: ninja -v
    Working Directory: C:/grpc/vcpkg/buildtrees/grpc/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\grpc\vcpkg\buildtrees\grpc\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:340 (vcpkg_execute_required_process)
  ports/grpc/portfile.cmake:46 (vcpkg_configure_cmake)
  scripts/ports.cmake:141 (include)

Error: Building package grpc:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: grpc:x64-windows
  Vcpkg version: 2021-07-26-9425cf5f512f242c0bcbabac31f08832825aee81

**Additional context**
**I have found the issue** - it is upb library version **2020-08-19**. It MUST be updated to **2020-12-19** first (upb::all_libs not found error, whatever it means)

Why grpc package contains wrong version dependency? Even more, nothing is mentioned regarding found UPB lib version in `/buildtrees/grpc/config-x64-windows-out.log` file although it is clearly a dependency.

**Comment by PhoebeHui** [comment]
@ivanshilo, thanks for reporting this issue! I can repro this issue locally.

```
CMake Error at E:/vcpkg/clean/vcpkg/scripts/buildsystems/vcpkg.cmake:534 (_add_executable):
  Target "check_epollexclusive" links to target "upb::all_libs" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:3889 (add_executable)

CMake Error at E:/vcpkg/clean/vcpkg/scripts/buildsystems/vcpkg.cmake:572 (_add_library):
  Target "upb" links to target "upb::all_libs" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?
Call Stack (most recent call first):
  cmake/upb.cmake:30 (add_library)
  CMakeLists.txt:270 (include)
...
```

**Comment by PhoebeHui** [comment]
@ivanshilo, could you remove upb:x64-windows and reinstall grpc again? I can't repro this issue with latest clean vcpkg source, and previous reproed with installed an old upb version.

**Comment by PhoebeHui** [comment]
@ivanshilo, the problem should be resolved by above solution, Please reopen if it doesn't works for you.
