### ISSUE TITLE
[SDL] enable hidapi

### ISSUE THREAD

**Issue by Yamakaky** [microsoft/vcpkg#19252]
****

**Is your feature request related to a problem? Please describe.**
Since a few versions, SDL uses HIDAPI for some game controller features, most notably access to the gyroscope and accelerometer data. This isn't included currently in vcpkg, so only the buttons and joysticks work.

**Proposed solution**
From [what I can see](https://github.com/libsdl-org/SDL/blob/main/cmake/sdlchecks.cmake#L1146-L1180), SDL uses its own bundled hidapi version, so we should just need to enable the  HIDAPI=ON cmake flag?

I can do the change, but I'm not familiar with vcpkg so some guidance would be welcomed, including testing it works on all platforms.

**Describe alternatives you've considered**

**Additional context**

**Comment by NancyLi1013** [comment]
Hi @Yamakaky
 
Thanks for posting this issue.

You can submit a PR for this issue if you are interested in this. Please let me know what guidance you need from us.

**Comment by Yamakaky** [comment]
PR opened.This was easier than thought since SDL use a bundled hidapi version.
