### ISSUE TITLE
[New Port Request] VTIL-Core

### ISSUE THREAD

**Issue by xxkat** [microsoft/vcpkg#19253]
Library name:
`VTIL-Core
`
Library description:

> VTIL Project, standing for Virtual-machine Translation Intermediate Language, is a set of tools designed around an optimizing compiler to be used for binary de-obfuscation and de-virtualization.
> 
> The main difference between VTIL and other optimizing compilers such as LLVM is that it has an extremely versatile IL that makes it trivial to lift from any architecture including stack machines. Since it is built for translation, VTIL does not abstract away the native ISA and keeps the concept of the stack, physical registers, and the non-SSA architecture of a general-purpose CPU as is. Native instructions can be emitted in the middle of the IL stream and the physical registers can be addressed from VTIL instructions freely.
> 
> VTIL also makes it trivial to emit code back into the native format at any virtual address requested without being constrained to a specific file format.
> 

Source repository URL:
_https://github.com/vtil-project/VTIL-Core_

Project homepage (if different from the source repository):
_https://vtil.org/_

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
