### ISSUE TITLE
Failure with vcpkg.json manifest file and azure-

### ISSUE THREAD

**Issue by MarkVabulas** [microsoft/vcpkg#19267]
**Describe the bug**
When trying to use a vcpkg.json manifest file, it works with every library except the azure-* ones.  The vcpkg install works correctly from the command line.  It does NOT work when using the manifest file.  Adding "version>=" entry for each one does not solve the issue.  This issue was found by using the vcpkg integration with Visual Studio Manifest file.  The Manifest file works for other libraries such as rapidjson, protobuf, openssl, boost, etc.  The Manifest file only starts to fail when the azure- libraries are included.  Installing them manually using the command line works correctly, so it is only a problem when using the manifest file.  I've trimmed down the MSBuild command line which is displayed to show minimum required commands to reproduce.  I tried uninstalling, then deleting, then rechecking out, then re-bootstrapping, then re-integrating vcpkg and get the same results.  

**Environment**
- OS: Windows 10 21H1 compiling for arm64-windows
- Compiler: Microsoft Visual Studio Professional 2019 Version 16.10.4

**To Reproduce**
1. Run command "git clone https://github.com/microsoft/vcpkg"
2. Run command ".\vcpkg\bootstrap-vcpkg.bat"
3. Drop the attached vcpkg.json [vcpkg.json.txt](https://github.com/microsoft/vcpkg/files/6911457/vcpkg.json.txt) file inside the .\vcpkg folder
4. Run command ".\vcpkg\vcpkg install --triplet=arm64-windows --x-manifest-root=.\vcpkg\"
5. Error results in:
Error: no version entry for azure-storage-common-cpp at version 12.0.0.
We are currently using the version in the ports tree (12.0.1).
Error: no version entry for azure-core-cpp at version 1.0.0.
We are currently using the version in the ports tree (1.1.0).
Error: no version entry for azure-storage-blobs-cpp at version 12.0.0.
We are currently using the version in the ports tree (12.0.1).
Error: no version entry for azure-storage-common-cpp at version 12.0.0.
We are currently using the version in the ports tree (12.0.1).

**Expected behavior**
I expect it to function the same when using the normal command line command:
vcpkg install --triplet=arm64-windows azure-core-cpp azure-identity-cpp azure-storage-blobs-cpp azure-storage-common-cpp azure-storage-files-datalake-cpp azure-storage-files-shares-cpp
Without it working through the manifest file, it breaks CI/CD toolchains.

**Failure logs** 
1>------ Build started: Project: Sample, Configuration: Debug ARM64 ------
1>Installing vcpkg dependencies to D:\Sample\vcpkg_installed\
1>"D:\vcpkg\scripts\buildsystems\msbuild\..\..\..\vcpkg.exe" install  --x-wait-for-lock --triplet "arm64-windows" --vcpkg-root "D:\vcpkg\scripts\buildsystems\msbuild\..\..\..\\" "--x-manifest-root=D:\Sample\\" "--x-install-root=D:\Sample\vcpkg_installed\\"
1>EXEC : error : no version entry for azure-storage-common-cpp at version 12.0.0.
1>We are currently using the version in the ports tree (12.0.1).
1>EXEC : error : no version entry for azure-core-cpp at version 1.0.0.
1>We are currently using the version in the ports tree (1.1.0).
1>EXEC : error : no version entry for azure-storage-blobs-cpp at version 12.0.0.
1>We are currently using the version in the ports tree (12.0.1).
1>EXEC : error : no version entry for azure-storage-common-cpp at version 12.0.0.
1>We are currently using the version in the ports tree (12.0.1).
1>D:\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(104,5): error MSB3073: The command ""D:\vcpkg\scripts\buildsystems\msbuild\..\..\..\vcpkg.exe" install  --x-wait-for-lock --triplet "arm64-windows" --vcpkg-root "D:\vcpkg\scripts\buildsystems\msbuild\..\..\..\\" "--x-manifest-root=D:\Sample\\" "--x-install-root=D:\Sample\vcpkg_installed\\" " exited with code 1.
1>C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\XamlCompiler\Microsoft.Windows.UI.Xaml.Common.targets(486,5): error MSB4181: The "CompileXaml" task returned false but did not log an error.
1>Done building project "Sample.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Additional context**
It says "We are currently using the version in the ports tree" which is newer than a version entry for the file, so what seems to be the problem?

**Comment by MarkVabulas** [comment]
Everything installs correctly when I run:
"D:\vcpkg\scripts\buildsystems\msbuild\..\..\..\vcpkg.exe" install  --x-wait-for-lock --triplet "arm64-windows" --vcpkg-root "D:\vcpkg\scripts\buildsystems\msbuild\..\..\..\\" "--x-install-root=D:\Sample\vcpkg_installed\\" azure-core-cpp azure-identity-cpp azure-storage-blobs-cpp azure-storage-common-cpp azure-storage-files-datalake-cpp azure-storage-files-shares-cpp

But the problem is that the output from MSBuild immediately after, or using the manifest as specified in the original description, gives the same results.  It's correctly installed in the vcpkg_installed folder as shown through "vcpkg list", and even then it still fails when specified with the manifest file.

**Comment by PhoebeHui** [comment]
@MarkVabulas, thanks for reporting this issue! I have submitted a PR to fix this issue.
