### ISSUE TITLE
Got an error when installing boost-regex

### ISSUE THREAD

**Issue by vega0** [microsoft/vcpkg#19263]
compile-c-c++ D:\workspace\cpp.licenses\src\cpprestsdk\vcpkg\buildtrees\boost-regex\x86-windows-rel\boost\build\64c60debac8240633333a6301148bbec\posix_api.obj
posix_api.cpp
compile-c-c++ D:\workspace\cpp.licenses\src\cpprestsdk\vcpkg\buildtrees\boost-regex\x86-windows-rel\boost\build\64c60debac8240633333a6301148bbec\cregex.obj
cregex.cpp
compile-c-c++ D:\workspace\cpp.licenses\src\cpprestsdk\vcpkg\buildtrees\boost-regex\x86-windows-rel\boost\build\64c60debac8240633333a6301148bbec\wide_posix_api.obj
wide_posix_api.cpp
compile-c-c++ D:\workspace\cpp.licenses\src\cpprestsdk\vcpkg\buildtrees\boost-regex\x86-windows-rel\boost\build\64c60debac8240633333a6301148bbec\instances.obj
instances.cpp
compile-c-c++ D:\workspace\cpp.licenses\src\cpprestsdk\vcpkg\buildtrees\boost-regex\x86-windows-rel\boost\build\64c60debac8240633333a6301148bbec\winstances.obj
winstances.cpp
compile-c-c++ D:\workspace\cpp.licenses\src\cpprestsdk\vcpkg\buildtrees\boost-regex\x86-windows-rel\boost\build\64c60debac8240633333a6301148bbec\usinstances.obj
usinstances.cpp
msvc.link.dll D:\workspace\cpp.licenses\src\cpprestsdk\vcpkg\buildtrees\boost-regex\x86-windows-rel\boost\build\64c60debac8240633333a6301148bbec\boost_regex-vc140-mt-x32-1_75.dll
   Создается библиотека D:\workspace\cpp.licenses\src\cpprestsdk\vcpkg\buildtrees\boost-regex\x86-windows-rel\boost\build\64c60debac8240633333a6301148bbec\boost_regex-vc140-mt-x32-1_75.lib и объект D:\workspace\cpp.licenses\src\cpprestsdk\vcpkg\buildtrees\boost-regex\x86-windows-rel\boost\build\64c60debac8240633333a6301148bbec\boost_regex-vc140-mt-x32-1_75.exp
LINK : fatal error LNK1158: не удается запустить "rc.exe"

        call "D:\workspace\cpp.licenses\src\cpprestsdk\vcpkg\buildtrees\boost-regex\x86-windows-rel\boost\standalone\msvc\6303f0eb78aa64dc89c3f04044858d46\msvc-setup.bat" x86 >nul
 link /NOLOGO /INCREMENTAL:NO /DLL /DEBUG /MACHINE:X86 /MANIFEST:EMBED /OPT:REF,ICF /subsystem:console /out:"D:\workspace\cpp.licenses\src\cpprestsdk\vcpkg\buildtrees\boost-regex\x86-windows-rel\boost\build\64c60debac8240633333a6301148bbec\boost_regex-vc140-mt-x32-1_75.dll" /IMPLIB:"D:\workspace\cpp.licenses\src\cpprestsdk\vcpkg\buildtrees\boost-regex\x86-windows-rel\boost\build\64c60debac8240633333a6301148bbec\boost_regex-vc140-mt-x32-1_75.lib"     @"D:\workspace\cpp.licenses\src\cpprestsdk\vcpkg\buildtrees\boost-regex\x86-windows-rel\boost\build\64c60debac8240633333a6301148bbec\boost_regex-vc140-mt-x32-1_75.dll.rsp"
    
...failed msvc.link.dll D:\workspace\cpp.licenses\src\cpprestsdk\vcpkg\buildtrees\boost-regex\x86-windows-rel\boost\build\64c60debac8240633333a6301148bbec\boost_regex-vc140-mt-x32-1_75.dll D:\workspace\cpp.licenses\src\cpprestsdk\vcpkg\buildtrees\boost-regex\x86-windows-rel\boost\build\64c60debac8240633333a6301148bbec\boost_regex-vc140-mt-x32-1_75.lib D:\workspace\cpp.licenses\src\cpprestsdk\vcpkg\buildtrees\boost-regex\x86-windows-rel\boost\build\64c60debac8240633333a6301148bbec\boost_regex-vc140-mt-x32-1_75.pdb D:\workspace\cpp.licenses\src\cpprestsdk\vcpkg\buildtrees\boost-regex\x86-windows-rel\boost\build\64c60debac8240633333a6301148bbec\boost_regex-vc140-mt-x32-1_75.pdb...
...removing D:\workspace\cpp.licenses\src\cpprestsdk\vcpkg\buildtrees\boost-regex\x86-windows-rel\boost\build\64c60debac8240633333a6301148bbec\boost_regex-vc140-mt-x32-1_75.lib
...removing D:\workspace\cpp.licenses\src\cpprestsdk\vcpkg\buildtrees\boost-regex\x86-windows-rel\boost\build\64c60debac8240633333a6301148bbec\boost_regex-vc140-mt-x32-1_75.pdb
...failed updating 1 target...
...updated 20 targets...

How to fix this? 
![image](https://user-images.githubusercontent.com/6493857/127732837-a726457d-b9a0-409a-8717-8170e0a82be2.png)

rc.exe in different windows has different find path?

**Comment by PhoebeHui** [comment]
@vega0, do you install windows sdk? if not, please install it via installer and try again, please also install the English language pack via installer.

**Comment by PhoebeHui** [comment]
@vega0, has the problem been solved?

**Comment by PhoebeHui** [comment]
@vega0, please reopen this issue if it still be a problem for you.
