### ISSUE TITLE
Error: Building package cairo:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by axelriet** [microsoft/vcpkg#19277]
Error: Building package cairo:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: cairo:x86-windows
  Vcpkg version: 2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9

That is all I know.

**Comment by autoantwort** [comment]
Hi, please provide the logs :)

**Comment by NancyLi1013** [comment]
Hi @axelriet 

Thanks for posting this issue.

Please provide the detailed error info. Also, please update to the latest vcpkg via `git pull `to rebuild this.

**Comment by NancyLi1013** [comment]
Closing this issue for now since there is no active thread for a long time. Please feel free to reopen this issue if you can provide above information.
