### ISSUE TITLE
[New Port Request] <ShaderConductor>

### ISSUE THREAD

**Issue by alvarogalloc** [microsoft/vcpkg#19275]
Library name:
**Shader Conductor**

Library description:
**ShaderConductor is a tool designed for cross-compiling HLSL to other shading languages.**

Source repository URL:
https://github.com/microsoft/ShaderConductor

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
