### ISSUE TITLE
[boost] build failure

### ISSUE THREAD

**Issue by joker-charles** [microsoft/vcpkg#19289]
**Host Environment**
- OS: Windows
- Compiler: 用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.29.30040 版
版权所有(C) Microsoft Corporation。保留所有权利。

**To Reproduce**
`./vcpkg install boost opencv`

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.
Building package boost-pool[core]:x64-windows...
-- Downloading https://github.com/boostorg/pool/archive/boost-1.75.0.tar.gz -> boostorg-pool-boost-1.75.0.tar.gz...
-- Downloading https://github.com/boostorg/pool/archive/boost-1.75.0.tar.gz... Failed. Status: 35;"SSL connect error"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:184 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".

      If error with status 4 (Issue #15434),
      try setting "http://user:password@your-proxy-ip-address:port/".

      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:147 (vcpkg_download_distfile)
  ports/boost-pool/portfile.cmake:3 (vcpkg_from_github)
  scripts/ports.cmake:142 (include)

Error: Building package boost-pool:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-pool:x64-windows
  Vcpkg version: 2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9

Additionally, attach any relevant sections from the log files above.

**Comment by PhoebeHui** [comment]
@joker-charles, could you get vcpkg latest source via 'git pull' and 'bootstrap-vcpkg.bat' and try again?

**Comment by joker-charles** [comment]
This package(Python3) must use MSVC v141 -VS 2017 C++ to build .and if use MSVC v142 -VS2019 It will be build failure。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: ***@***.***>
发送时间: 2021年8月2日 14:29
收件人: ***@***.***>
抄送: Joker ***@***.***>; ***@***.***>
主题: Re: [microsoft/vcpkg] [<port name>] build failure (#19289)


@joker-charles<https://github.com/joker-charles>, could you get vcpkg latest source via 'git pull' and 'bootstrap-vcpkg.bat' and try again?

―

**Comment by joker-charles** [comment]
It seem to I am in China, soI have difficulty downloading files on github，so boost-pool was build failed。And I found another reson to build boost-python failure。because python3 can only be built by vs2017(MSVC v141 VS2017 C++tooset)。So when I only have VS2019, it failed to build。

**Comment by PhoebeHui** [comment]
@joker-charles, could you report a seperate issue with full failure logs for boost-python?

>It seem to I am in China, so I have difficulty downloading files on github

That's true, it happens occasionally, it works when you retry sometimes, here is a workaround for solving the download issue in China: https://zhuanlan.zhihu.com/p/383683670, you can have a try. 
BTW, we have blogs https://www.cnblogs.com/vcpkg/ to introduce some features in vcpkg, Hope it helps.

**Comment by joker-charles** [comment]
I can't reproduce this build failed.It's weird.

@joker-charles<https://github.com/joker-charles>, could you report a seperate issue with full failure logs for boost-python?

It seem to I am in China, so I have difficulty downloading files on github

That's true, it happens occasionally, it works when you retry sometimes, here is a workaround for solving the download issue in China: https://zhuanlan.zhihu.com/p/383683670, you can have a try.
BTW, we have blogs https://www.cnblogs.com/vcpkg/ to introduce some features in vcpkg, Hope it helps.

**Comment by PhoebeHui** [comment]
@joker-charles, so can we close this issue now? you can create a new issue if the issue reproduce.

**Comment by joker-charles** [comment]
okay ,just close this issue.

**Comment by PhoebeHui** [comment]
Thanks!
