### ISSUE TITLE
[New Port Request] wjwwood/serial (Serial Communication Library)

### ISSUE THREAD

**Issue by IshaanKarnik** [microsoft/vcpkg#19293]
Library name: wjwwood/serial (Serial Communication Library)

Library description: This is a cross-platform library for interfacing with RS-232 serial like ports written in C++. It provides a modern C++ interface with a workflow designed to look and feel like PySerial, but with the speed and control provided by C++.

Source repository URL: https://github.com/wjwwood/serial.git

Project homepage : http://wjwwood.io/serial/

**Comment by IshaanKarnik** [comment]
Last time I manually installed wjwwood/serial I installed catkin referring the bellow link.

https://catkin-tools.readthedocs.io/en/latest/installing.html

**Comment by ericfont** [comment]
Catkin should be easily installable via `pip install catkin_tools`

And searching vcpkg repo shows that at least one other project uses pip install inside of its port (https://github.com/microsoft/vcpkg/blob/8ad33ead9075cd8d6d357e0b870ba8d501efe35c/ports/tensorflow-common/tensorflow-common.cmake#L54-L56)

I would like this serial package added to vcpkg too...

**Comment by ericfont** [comment]
well I started an attempt to create a port file, but couldn't seem to get catkin discoverabe by cmake after using pip install:

https://github.com/ericfont/vcpkg/commit/881a173a39629c6f027082e753535a963af65c67

Also it seems vcpkg wants the license to be in its own separate file, so I made a PR on the original library to move the license text to a LICENSE file: https://github.com/wjwwood/serial/pull/261

**Comment by ericfont** [comment]
I spent time trying to edit the cmake file and figure out how to get the python catkin thing working with vcpkg, but I gave up.  I wonder if removing the catkin dependency is eaiser, cause it is only used for the build configuration I think.

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
