### ISSUE TITLE
Error: Building package boost-build:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by sycamore27** [microsoft/vcpkg#19295]
C:\src\vcpkg\vcpkg>vcpkg install pcl --triplet=x64-windows
Computing installation plan...
The following packages will be built and installed:
  * boost-algorithm[core]:x64-windows -> 1.76.0
  * boost-align[core]:x64-windows -> 1.76.0
  * boost-any[core]:x64-windows -> 1.76.0
  * boost-asio[core]:x64-windows -> 1.76.0
  * boost-atomic[core]:x64-windows -> 1.76.0
  * boost-bimap[core]:x64-windows -> 1.76.0
  * boost-build[core]:x64-windows -> 1.75.0
  * boost-chrono[core]:x64-windows -> 1.76.0
  * boost-circular-buffer[core]:x64-windows -> 1.76.0
  * boost-container[core]:x64-windows -> 1.76.0
  * boost-container-hash[core]:x64-windows -> 1.76.0
  * boost-context[core]:x64-windows -> 1.76.0
  * boost-conversion[core]:x64-windows -> 1.76.0
  * boost-coroutine[core]:x64-windows -> 1.76.0
  * boost-date-time[core]:x64-windows -> 1.76.0
  * boost-dynamic-bitset[core]:x64-windows -> 1.76.0
  * boost-endian[core]:x64-windows -> 1.76.0
  * boost-exception[core]:x64-windows -> 1.76.0
  * boost-filesystem[core]:x64-windows -> 1.76.0
  * boost-foreach[core]:x64-windows -> 1.76.0
  * boost-format[core]:x64-windows -> 1.76.0
  * boost-function[core]:x64-windows -> 1.76.0
  * boost-function-types[core]:x64-windows -> 1.76.0
  * boost-functional[core]:x64-windows -> 1.76.0
  * boost-fusion[core]:x64-windows -> 1.76.0
  * boost-graph[core]:x64-windows -> 1.76.0
  * boost-integer[core]:x64-windows -> 1.76.0
  * boost-interprocess[core]:x64-windows -> 1.76.0
  * boost-intrusive[core]:x64-windows -> 1.76.0
  * boost-io[core]:x64-windows -> 1.76.0
  * boost-iostreams[core]:x64-windows -> 1.76.0
  * boost-iterator[core]:x64-windows -> 1.76.0
  * boost-lambda[core]:x64-windows -> 1.76.0
  * boost-lexical-cast[core]:x64-windows -> 1.76.0
  * boost-math[core]:x64-windows -> 1.76.0
  * boost-modular-build-helper[core]:x64-windows -> 1.76.0#1
  * boost-move[core]:x64-windows -> 1.76.0
  * boost-mp11[core]:x64-windows -> 1.76.0
  * boost-mpl[core]:x64-windows -> 1.76.0
  * boost-multi-array[core]:x64-windows -> 1.76.0
  * boost-multi-index[core]:x64-windows -> 1.76.0
  * boost-numeric-conversion[core]:x64-windows -> 1.76.0
  * boost-optional[core]:x64-windows -> 1.76.0
  * boost-parameter[core]:x64-windows -> 1.76.0
  * boost-phoenix[core]:x64-windows -> 1.76.0
  * boost-pool[core]:x64-windows -> 1.76.0
  * boost-predef[core]:x64-windows -> 1.76.0
  * boost-property-map[core]:x64-windows -> 1.76.0
  * boost-property-tree[core]:x64-windows -> 1.76.0
  * boost-proto[core]:x64-windows -> 1.76.0
  * boost-ptr-container[core]:x64-windows -> 1.76.0
  * boost-random[core]:x64-windows -> 1.76.0
  * boost-range[core]:x64-windows -> 1.76.0
  * boost-ratio[core]:x64-windows -> 1.76.0
  * boost-rational[core]:x64-windows -> 1.76.0
  * boost-regex[core]:x64-windows -> 1.76.0
  * boost-serialization[core]:x64-windows -> 1.76.0
  * boost-signals2[core]:x64-windows -> 1.76.0
  * boost-smart-ptr[core]:x64-windows -> 1.76.0
  * boost-sort[core]:x64-windows -> 1.76.0
  * boost-spirit[core]:x64-windows -> 1.76.0
  * boost-system[core]:x64-windows -> 1.76.0
  * boost-test[core]:x64-windows -> 1.76.0
  * boost-thread[core]:x64-windows -> 1.76.0
  * boost-tokenizer[core]:x64-windows -> 1.76.0
  * boost-tti[core]:x64-windows -> 1.76.0
  * boost-tuple[core]:x64-windows -> 1.76.0
  * boost-type-index[core]:x64-windows -> 1.76.0
  * boost-typeof[core]:x64-windows -> 1.76.0
  * boost-unordered[core]:x64-windows -> 1.76.0
  * boost-utility[core]:x64-windows -> 1.76.0
  * boost-uuid[core]:x64-windows -> 1.76.0
  * boost-variant[core]:x64-windows -> 1.76.0
  * boost-winapi[core]:x64-windows -> 1.76.0
  * boost-xpressive[core]:x64-windows -> 1.76.0
  * bzip2[core]:x64-windows -> 1.0.8#2
  * eigen3[core]:x64-windows -> 3.3.9
  * flann[core]:x64-windows -> 2019-04-07#2
  * liblzma[core]:x64-windows -> 5.2.5#3
  * libpng[core]:x64-windows -> 1.6.37#15
  * lz4[core]:x64-windows -> 1.9.3
  * openssl[core]:x64-windows -> 1.1.1k#8
    pcl[core]:x64-windows -> 1.11.1#4
  * qhull[core]:x64-windows -> 8.0.2
  * vcpkg-cmake[core]:x64-windows -> 2021-07-26
  * vcpkg-cmake-config[core]:x64-windows -> 2021-05-22#1
  * xxhash[core]:x64-windows -> 0.8.0#1
  * zlib[core]:x64-windows -> 1.2.11#11
  * zstd[core]:x64-windows -> 1.4.9
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\3a\3ab62d5f5e46d3ba9ad7ab4dcb0f7b00645b941603d778fa33ce17f72283678b.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\ab\ab8229e18298b8e6a0cf7290688acadf32d284a41cfafac6321972ebc045b28d.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\df\df418aa006806b10949d1f6e0c81e5e45b0de0af09146e8cb7e25838cf0f7146.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\99\990d680f94f24c03385d363f867092abc6881a6deab3bdbf37219fea6ad2c3a4.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\b0\b087f08c408baaa6c37b109a95b3b93576507a551c4c27934241c4304def0ee2.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\23\2346793435a19834821d0214d3945a04ce683a08062b8e8f3a5bc39fa02529db.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\a4\a458cd5ba568d6980264080f64038d620303b65d519f44d668eb303f146d00a8.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\4e\4ee2eebe4e4ed442a50af0fe5b04fd43ffb5cb9a89ca0a565df02476798ff381.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\62\625a57ac992ddc39fe08ac31fef1497a707989cc7a3476e7f36f16cb18f1739a.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\10\10ebdce5e4cdc85f136f56a853b87f74989ce886e7fbd596820a8eb35986fd45.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\68\68acbfb2555baeeb8ac33ff1be556275732c41de7b6a75eabfdcfec185c452bb.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\b0\b032694882293317f4a0c580304a7721b2e0ea096d8f60f2706b6c1eab44eb04.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\5a\5ad4640a84506db6f9873f63ec063c93dc4a2223c74bee8303dde9cded573698.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\f6\f6f671b1e88bdefc2cb1932ad733ac66ccb6e68c5dacb602758668e3fed34703.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\21\21055a5ee6ab0bdbee33c57012351bc77e0bffc0462f9949935a1c8af12f88fe.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\af\afba9b7455695cb2755d7fd882c4e68e88fe00c7569fcb6cdd238b42fd1aeb46.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\a7\a757309080d514da0d086ecbd9e21b81be9849850344b777a654c9e67a86d850.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\23\23fbc8dfc2e1910d136f0306cba5920fd41845c33998bce1d4dc2e78393a369a.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\12\12b6aafc665379635eb7f368617d3aacd47d2562d24f19cc72c9a5c14c8a4458.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\35\357caf17849bf3d0052b0a618c01afc71f43b208cbaed0b118a6d2b586c3d3cf.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\eb\eb0f5af57642f7e725b54237f849f6ce6eaf137c1c5152d8235b8468e9a67a8d.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\53\53923be20e30fb27d3cf19447dc7a48fcc76ad933be2bc3ac2bc3e54264fc14e.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\cf\cf76dc64ac231a3e296e2d8387f694ea542e89616df1250da3494d0b731f17cb.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\ab\ab5220602670315a9c2e351e5c1c12d3b990c1e0e420228a5879e8ff9c25a0f6.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\f3\f31cbc85de4d2e81870754fba780ade6ae639274179331f3d15f7a837ec2aba9.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\97\97556a5589f4d411104b625719b706264ec5bff472354423253672dbee208f45.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\61\613d2778891c6668d3dda1f210b3789f9a21b5adfb0a08a2276951c731fab9f3.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\19\1937e4f87b6506ae901dda7cc66cee7f49cd57fb41e52501f970d8399c9d7a5c.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\7a\7af845420cd480468de618ce989f68c52340dc57714685ccb1d0395b21aaa50f.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\7e\7ed6f4a9dc66246f532a806a900a09a0825dd19f3cbcb1e550b5b5fbbea30b2a.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\cc\cc689cf23ac0e63f36f45f1ab59a6a0f59014907f3c61191822067af83806cb1.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\0b\0befa3533c82c35960994076ab58aa31c87e5d1fc1ea63b339b89224ccc99cf2.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\bf\bf29a9761fba4c02c83f4b2760bcf138f4c81a774d3fff529a80545e0be57c97.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\27\2781d01b1e8b448f4affc2baaadecec8d402157c688500db7ef840ba91272602.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\3f\3f24334bb98c46745a6a281892918e83bce7e32abed1c0b91390b7c2f4fbe18c.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\e0\e031e092424a30a27e3b92aa152e16588a6ca14b519b471670680edb28113597.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\4c\4c523c73860f480bc7199c5629c09e6eeec4959f9cbcb4e399f0d8275ebc2760.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\18\18f6361350cc1f1a9a2df8fcffbe077ada086f1bb9f20a837bc70dc6f4b3e7cc.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\83\83eb0a9c0d1237d36ccbf686a8c36115f35e3e7c01f238ab5f3931a9110bda52.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\fb\fba629b33240c0fed0abb183d2dc84ed0a177c977c818f3a2bf9473b81bc144b.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\bf\bf0ed3d89e45394574a51937384864957cebc3de6e71fb7ff2ff6da5de694bfa.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\14\140e6269684e0c6560749e5ce97624421b7227207044ab878149d915583ab258.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\ab\ab82b4293d4a1bdaeb7dc57bf6930619e01b74e84a3fda95c019f5f9eebd0661.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\6d\6d7c5ccdc4e86c1b50aedefe47546a1fae7688cd53aaced9ced4678c30be525a.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\44\448fe539c8c97170b4a3b1f8ad2711e4be5448f33d60e50f91a9f19ee6f380ce.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\dd\dd2b1c21279406c7c339f1f5accd1fecb36da0c40b014b74ccf2af9c80592be9.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\10\10048ec237d1ffef06b0317353f44724d6e2f6a88b848a821acd2836e90c15df.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\d1\d1e512ec19cd77c2eaf9c7ca8cb36164e0f95c99ee29821c692b5fb44fae1f8c.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\75\75fee3fb32636c342f43f9240434df1f1ae6e4696bc7f2c0fa325458bb4976d8.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\b5\b55a1377773e8f2c3dd9d91936ec262856a1730dd40204a4797870c8434fa62c.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\af\aff20f704fcaf0ddfde61dc6ca2b555fd83cf0a2fcb753c8e14f32416745470b.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\42\423af0dd9646452115a07e4995a0d79a2a615832df4bb0a1785de81400458347.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\b2\b239ea7c7b24930ea522572cec93470c1dfc92bc0e8de879f21426421a041777.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\90\90a5afca2fdd7be6d5652f2163f6efe91f8395f2f18aeb25435c6d86cbda8998.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\45\456f3d464d93cdf81c29f06303f6fef1f6746e7a22033a529c0a228a585f8cbc.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\49\49d66dfeee2719f43215403f031009dddc6c21a4c4a3f09c7f361158da256ab0.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\0a\0af168cde66d71bbfeed4982936574e7c848147b64a12e787fe2d6643de0753a.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\64\647f879dae7f22df50f610f00b3780aa8e1629023fab48921a1f35df5ccdaff8.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\f0\f04cd8c15b2ec19f3b9f22a030eaa15b28fe81459976c01e906f5ed7ab29946a.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\8f\8f2f32a933c40ecc54e5b7f2a207e714fee13a03b4fab30a003c1ccc1e1d3d44.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\70\70171b31e09b2ab53b4cdb8e90183bdce0d0fa6690131d3a096856508ce2c9aa.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\a3\a371e519b94e8ec5010f73647ccf8538aa19385742221ea96898e469958d7ebc.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\1c\1c178c9efd175425f0b122a63a14fcf75eef459a97fbc5c3d40def57039e9a23.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\b7\b76c1d66164fa185d57b83c35948f2bb46daa861f2ce61200f66681ed25f10cb.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\b2\b25ca2a4bbbd8a1e92e7e9bd1eb1d6be68c3f526bf7ae1c3bff235adffca56ce.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\e4\e4a445785529226f1c3cbd87e143c5f4b192e097461679679dcb9faec40eebcd.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\45\4520de3bffa2a4d3b5f57ac94b2e2bb6ab3b2cf65a9beacef86448f5c9b65e54.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\96\96ef443d684ce8bf5b82a27787140ce2f55c051c52ef7dd99cb33710285b819f.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\e3\e39f58ef7011b36562229ad4eb4be816289197892e8e1da9e1196e37e11c7ec8.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\15\15d2b11892bf5c6fe24d668866f5a18084295effb04712baef8549e085d6c12b.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\fb\fb53c8da20b5f696bf5a89ab19f4dc42d76d90af4d97fdc913ad17148e983947.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\5b\5b5b5ba27b3160d1503318adb7e069d778f402664c57663c74c5950725ff3a8a.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\1c\1cd4816ac77d9bbfb6d60879aeadfedca6b72c5faa15c52a19ade7f1d4ec744e.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\e1\e1be24533d28f04b1b83fac264dac8ed6cde1ec2b46657cfbd454485ac23926a.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\a3\a3c959b04c2d26052178673fbdd1a9c7766a133bbb13339a84c5599a141db110.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\72\721242c45c4e2c788e80ce72b7936aabd976fd16c3199aa3ad2778e890f0d40e.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\e1\e129db7cb8dc5a855bdc61bfb2b07ca044a04478b6f98a3ba2ee94307b4922e4.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\8c\8ce95b6758b96ee4afaff44650ebcdd0aa66b681f1f4f9928e6a4d2175816ac0.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\84\84ff5d4b425174d0fd620971b5cccfbed2318d62c389bcec131abccf85b8ae26.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\91\91b09ba9b2da6a9022b7983ac2b7997c23796a12fbd175f7db7846b3734f9577.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\be\bee01203611e3284dc7413b889a119da9dd23b62a8363617378563bd28b70121.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\34\349e005fed5845c1eaf51263e2bbd42597ce8444bf2cc1915f1587d121941d85.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\aa\aa76b57a605f1f498408d4b7fc47db08a646cb253854129ab40cc08561f63fe0.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\fd\fdd98098b4a94d74c4706f7121c2f543610b9d9442236d23afb0e04883203e77.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\c5\c51d305123e31f71e33207319147f06cd93b3e3c6e700db726790dc97483b67a.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\72\728d15e048af02d2b4a605a0263ce413e41b2617b0552703b04226bc61435ef3.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\5d\5d0af80b18b4cbcf93fbbc7b1272cd225a053d5379795549b8d8b0bca7a53072.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\60\603c177880c8a1037ac2fe01fa8855429ca1ea682935cdee3a2a0a5835c7ad28.zip
Could not locate cached archive: C:\Users\fdft\AppData\Local\vcpkg\archives\11\11edfbd06283b1f2ff19980ef4bdecd9cccfbc50db8d10fb9c47b3d806218d4c.zip
Starting package 1/89: boost-build:x64-windows
Building package boost-build[core]:x64-windows...
-- Using C:/src/vcpkg/vcpkg/downloads/boostorg-build-boost-1.75.0.tar.gz
-- Cleaning sources at C:/src/vcpkg/vcpkg/buildtrees/boost-build/src/ost-1.75.0-a06f9834b9.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/src/vcpkg/vcpkg/downloads/boostorg-build-boost-1.75.0.tar.gz
-- Applying patch fix_options.patch
-- Using source at C:/src/vcpkg/vcpkg/buildtrees/boost-build/src/ost-1.75.0-a06f9834b9.clean
-- Using C:/src/vcpkg/vcpkg/downloads/boost_LICENSE_1_0.txt
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.75.0/boostcpp.jam -> boost-1.75.0-boostcpp.jam...
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' = off
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.75.0/boostcpp.jam
Error: Failed to download from mirror set:
https://raw.githubusercontent.com/boostorg/boost/boost-1.75.0/boostcpp.jam: WinHttpSendRequest() failed: 12007

[DEBUG] C:\a\1\s\src\vcpkg\base\downloads.cpp(626)
[DEBUG] Exiting after 62142 us (43670 us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:251 (message):

      Failed to download file.
      If you use a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.

      3. You proxy's remote server is out of service.

      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)

      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  ports/boost-build/portfile.cmake:25 (vcpkg_download_distfile)
  scripts/ports.cmake:141 (include)

Error: Building package boost-build:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-build:x64-windows
  Vcpkg version: 2021-07-26-9425cf5f512f242c0bcbabac31f08832825aee81

Additionally, attach any relevant sections from the log files above.

**Comment by sycamore27** [comment]
I'm on windows 10 and Visual Studio 2019, and I have updated the vcpkg to the latest. Sincerely ask for help, thanks!

**Comment by srgbtl** [comment]
The same issue on GitHub actions environment with random ports:

```
-- Downloading https://github.com/boostorg/type_traits/archive/boost-1.76.0.tar.gz -> boostorg-type_traits-boost-1.76.0.tar.gz...
[DEBUG] Feature flag 'binarycaching' unset

[DEBUG] Feature flag 'manifests' = off

[DEBUG] Feature flag 'compilertracking' unset

[DEBUG] Feature flag 'registries' unset

[DEBUG] Feature flag 'versions' unset

[DEBUG] Downloading https://github.com/boostorg/type_traits/archive/boost-1.76.0.tar.gz

Error: Failed to download from mirror set:

https://github.com/boostorg/type_traits/archive/boost-1.76.0.tar.gz: WinHttpReceiveResponse() failed: 12002



[DEBUG] C:\a\1\s\src\vcpkg\base\downloads.cpp(626)

[DEBUG] Exiting after 21189447 us (21183025 us)
```

```
-- Downloading https://github.com/nlohmann/json/raw/v3.9.1/CMakeLists.txt -> nlohmann-json-v3.9.1/CMakeLists.txt...
-- Downloading https://github.com/nlohmann/json/raw/v3.9.1/LICENSE.MIT -> nlohmann-json-v3.9.1/LICENSE.MIT...
-- Downloading https://github.com/nlohmann/json/raw/v3.9.1/nlohmann_json.natvis -> nlohmann-json-v3.9.1/nlohmann_json.natvis...
[DEBUG] Feature flag 'binarycaching' unset

[DEBUG] Feature flag 'manifests' = off

[DEBUG] Feature flag 'compilertracking' unset

[DEBUG] Feature flag 'registries' unset

[DEBUG] Feature flag 'versions' unset

[DEBUG] Downloading https://github.com/nlohmann/json/raw/v3.9.1/nlohmann_json.natvis

Error: Failed to download from mirror set:

https://github.com/nlohmann/json/raw/v3.9.1/nlohmann_json.natvis: WinHttpSendRequest() failed: 12002



[DEBUG] C:\a\1\s\src\vcpkg\base\downloads.cpp(626)

[DEBUG] Exiting after 21021174 us (21014727 us)
```

Vcpkg version: 2021-07-21-244f69e78da4f97034328b4d290db262d748d4c7

**Comment by srgbtl** [comment]
Seems like the issue is not related to vcpkg but to GitHub. Had a few failures with setting up of GitHub Actions Jobs and the same problem reported (TIMEOUT):
```
Download action repository '***'
Warning: Failed to download action 'https://api.github.com/repos/***'. Error: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
Warning: Back off 17.747 seconds before retry.
Warning: Failed to download action 'https://api.github.com/repos/***'. Error: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
Warning: Back off 26.557 seconds before retry.
Error: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
```

**Comment by autoantwort** [comment]
@sycamore27, could you try the solution in [#13348 (comment)](https://github.com/microsoft/vcpkg/issues/13348#issue-692784879)?

**Comment by sycamore27** [comment]
Thank you very much for your reply! It does seem to be an issue related to the process of downloading on the GitHub. Because I am in China, the download error is caused by the network. After switching the network, I can download normally. Thank you again for your help.

**Comment by PhoebeHui** [comment]
> Seems like the issue is not related to vcpkg but to GitHub

@srgbtl, yes, we have increased the timeouts for downloads in vcpkg tool, the next release should include the improvements.

@sycamore27, see https://github.com/microsoft/vcpkg/issues/19289#issuecomment-890792856 as well.
