### ISSUE TITLE
When updating package, please download first and then removing

### ISSUE THREAD

**Issue by liupeiqiHN** [microsoft/vcpkg#19292]
Due to the China Great Firewall affect internet speed, Github download speed is slow ( <50k/s is very common ), and downloads failure often happens. So this cause a problem, when I want to update all outdated packages `vcpkg upgrade --no-dry-run`, vcpkg will remove all outdated packages first and then download the newest packages from GitHub, but if the download failure, this upgrade process will be terminated, and I must install all removed packages one by one.

**Comment by JackBoosY** [comment]
Well, I have a personal mirror, please see https://zhuanlan.zhihu.com/p/383683670.

**Comment by gvanem** [comment]
>  and then download the newest packages from GitHub, but if the download failure, this upgrade process will be terminated, 

The `upgrade` command is broken for me too (I have a 100 MBit/s line in Norway). Before a `vcpkg upgrade --no-dry-run`, I had
63 packages. After that broken upgrade a `vcpkg list` shows only 49 packages installed.

**PS**.  Why do we have to specify `--no-dry-run`? This hints on a `--dry-run` option was specified somehow. I did not.

**Comment by JackBoosY** [comment]
> > and then download the newest packages from GitHub, but if the download failure, this upgrade process will be terminated,
> 
> The `upgrade` command is broken for me too (I have a 100 MBit/s line in Norway). Before a `vcpkg upgrade --no-dry-run`, I had
> 63 packages. After that broken upgrade a `vcpkg list` shows only 49 packages installed.
> 
> **PS**. Why do we have to specify `--no-dry-run`? This hints on a `--dry-run` option was specified somehow. I did not.

For this part issue, we already have the same one.

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/4360 https://github.com/microsoft/vcpkg/discussions/17922
