### ISSUE TITLE
[New Port Request] pytorch

### ISSUE THREAD

**Issue by debapritam22** [microsoft/vcpkg#19303]
Library name: pytorch

Library description:
PyTorch is a Python package that provides two high-level features:

> Tensor computation (like NumPy) with strong GPU acceleration

> Deep neural networks built on a tape-based autograd system

Source repository URL: https://github.com/pytorch/pytorch

Project homepage (if different from the source repository): https://pytorch.org/

Anything else that is useful to know when adding (such as optional features the library may have that should be included): NA

**Comment by aizuon** [comment]
Related PR: https://github.com/microsoft/vcpkg/pull/17199

**Comment by JackBoosY** [comment]
Please track #16319 instaed.
