### ISSUE TITLE
[New Port Request] Shark

### ISSUE THREAD

**Issue by debapritam22** [microsoft/vcpkg#19301]
Library name: Shark 
Library description: Shark is a fast, modular, general open-source C++ machine learning library. 

Source repository URL: https://github.com/Shark-ML/Shark

Project homepage (if different from the source repository): http://www.shark-ml.org/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
