### ISSUE TITLE
[New Port Request]  reactphysics3d

### ISSUE THREAD

**Issue by orosmatthew** [microsoft/vcpkg#19309]
Library name: ReactPhysics3D

Library description: ReactPhysics3D is an open source C++ physics engine library that can be used in 3D simulations and games.

Source repository URL: https://github.com/DanielChappuis/reactphysics3d

Project homepage: https://www.reactphysics3d.com/

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
