### ISSUE TITLE
[enet, libsodium, miniupnpc] Lack .pc files

### ISSUE THREAD

**Issue by s0600204** [microsoft/vcpkg#19317]
**Problem, described**
These projects all support pkg-config upstream (in that they have the ability to generate a .pc file), but `vcpkg`'s port of them does not export the .pc files

* [enet](https://github.com/microsoft/vcpkg/tree/master/ports/enet)
* [libsodium](https://github.com/microsoft/vcpkg/tree/master/ports/libsodium)
* [miniupnpc](https://github.com/microsoft/vcpkg/tree/master/ports/miniupnpc)

**Solution, proposed**
Have the above project ports export the generated .pc files to where such things typically go when `vcpkg` exports .pc files.

**Comment by Neumann-A** [comment]
If the ports are switched to their native buildsystem they most likely will automatically generate the .pc files so this should be the task.
