### ISSUE TITLE
[openal-soft] Incorrect prefix in .pc file

### ISSUE THREAD

**Issue by s0600204** [microsoft/vcpkg#19316]
**Current problem**
The `prefix` line written to the `openal.pc` file is incorrect. It currently looks something like:
```
prefix=D:/a/0ad/0ad/libraries/win32-build/vcpkg/vc/packages/openal-soft_x86-windows
```
(Exact text will differ depending on triplet, and the location of where vcpkg is building things.)

**Proposed solution**
Based on other .pc files exported by vcpkg, it should read:
```
prefix=${pcfiledir}/../..
```

**Describe alternatives you've considered**
I'm currently employing a workaround (search-replace of text) in a project that relies on .pc files. Would like to remove that workaround if possible.

**Comment by NancyLi1013** [comment]
Hi @s0600204 

Thanks for posting this issue.

Needs to add `vcpkg_fixup_pkgconfig()` to fix the paths in .pc files. I will submit a PR to fix this later.
