### ISSUE TITLE
opencv4:arm-uwp build failure

### ISSUE THREAD

**Issue by artificial-jamesirei** [microsoft/vcpkg#19313]
**Host Environment**
- OS: Windows 10

**To Reproduce**
`./vcpkg install opencv4:arm-uwp`

**Failure logs** 
`-- Using C:/dev/vcpkg/downloads/opencv-cache/tiny_dnn/adb1c512e09ca2c7a6faef36f9c53e59-v1.0.0a3.tar.gz
-- Found external ninja('1.10.2').
-- Configuring arm-uwp
-- Building arm-uwp-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:155 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /m
    Working Directory: C:/dev/vcpkg/buildtrees/opencv4/arm-uwp-dbg
    See logs for more information:
      C:\dev\vcpkg\buildtrees\opencv4\install-arm-uwp-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:104 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:44 (vcpkg_build_cmake)
  ports/opencv4/portfile.cmake:407 (vcpkg_install_cmake)
  scripts/ports.cmake:141 (include)

Error: Building package opencv4:arm-uwp failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: opencv4:arm-uwp
  Vcpkg version: 2021-07-26-9425cf5f512f242c0bcbabac31f08832825aee81

Additionally, attach any relevant sections from the log files above.`

Attached is the output log file listed from above
[install-arm-uwp-dbg-out.log](https://github.com/microsoft/vcpkg/files/6919882/install-arm-uwp-dbg-out.log)

**Comment by PhoebeHui** [comment]
@artificial-jamesirei, thanks for reporting this issue! It should be a port bug, I will take a look.

**Comment by Adela0814** [comment]
@artificial-jamesirei PR#19358 may solve this issue, could you test with latest version and report the result?

**Comment by PhoebeHui** [comment]
@artificial-jamesirei, this issue has been fixed, please get latest source and try again.
