### ISSUE TITLE
bootstrap-vcpkg fails when multiple Win10 SDK's are installed, but the newest one is incomplete

### ISSUE THREAD

**Issue by nerdile** [Microsoft/vcpkg#1932]
On a machine that has Visual Studio 2017 and the Windows 10 SDK installed, but not the Windows 8.1 SDK, bootstrap-vcpkg fails with the error:
Could not detect a Windows SDK / TargetPlatformVersion
At D:\path\to\vcpkg\scripts\getWindowsSDK.ps1:109 char:1
+ throw "Could not detect a Windows SDK / TargetPlatformVersion"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not detec...PlatformVersion:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not detect a Windows SDK / TargetPlatformVersion

**Comment by nerdile** [comment]
In scripts\getWindowsSDK.ps1 - the issue is that CheckWindows10SDK is supposed to be finding the newest full SDK, is returning instead of continuing in the foreach loop

**Comment by nerdile** [comment]
I think this is gonna be my first public pull request to github, you guys ready for this?

**Comment by nerdile** [comment]
Issued PR #1934

**Comment by NancyLi1013** [comment]
The PR has been merged. So close it.
