### ISSUE TITLE
Older VCPKG fails to install packages

### ISSUE THREAD

**Issue by larshg** [microsoft/vcpkg#19333]
**Describe the bug**
VCPKG failes to install packages and exits with code 1.

**Environment**
- OS: [e.g. Windows/Linux etc...] Windows x64
- Compiler: VS2019

**To Reproduce**
1. Checkout older version, ie. 2021.05.12.
2. .\vcpkg install boost flann eigen3 qhull vtk[qt,opengl] gtest benchmark --triplet x86-windows-rel --clean-after-build;

**Expected behavior**
Packages installed successfully as it did some weeks ago.

**Failure logs** 
-(please attached failure logs)
See here: https://dev.azure.com/PointCloudLibrary/pcl/_build/results?buildId=19728&view=logs&j=1d0d1847-c9f6-5bed-a0b6-1256ce54b612&t=3a44332a-b52e-58ca-3fc0-f33f70a901bb&l=335

Last successful (11. July) can be seen here: https://dev.azure.com/PointCloudLibrary/pcl/_build?definitionId=11&_a=summary

**Additional context**
Looking at latest build it was tested with master of VCPKG, which is successful.

**Comment by autoantwort** [comment]
Duplicate of #18636. Update your vcpkg version or use cmake 3.20.x

**Comment by larshg** [comment]
Thanks @autoantwort. I dont know why didnt find those issues. Anyway, I'll try it out.

**Comment by larshg** [comment]
Thanks for the help. It indeed solved the issue using cmake 3.20.5.
