### ISSUE TITLE
Generating a PDF from docs/*.md

### ISSUE THREAD

**Issue by gvanem** [microsoft/vcpkg#19331]
I've been struggling creating a single `VCPKG.PDF` from all `docs/*.md` files with little success. 
First trying with Pandoc (latest v2.14.1), but it does not follow and convert internal links like:
```
  - [FAQ](about/faq.md)
```
to a sensible link and content. This was my command:
```
pandoc  --output VCPKG.pdf --pdf-engine xelatex --metadata title="VCPKG documentation" ^
  --table-of-contents --listings --self-contained --reference-links --to=pdf --from=gfm README.md 
```
I assume some Pandoc filter is required for this. But I'm not so into this. Anybody?

Then a tip in https://github.com/microsoft/vcpkg/pull/1111/files hinted on trying:
```
pwsh docs\regenerate.ps1 -VcpkgRoot . -WarningAction Stop
```

which did absolutely nothing.

So how should I create a single offline `VCPKG.pdf` file?

**Comment by PhoebeHui** [comment]
@gvanem, I haven't used pandoc before, I have no idea why it doesn't work here.

I know a simple way to same the .md file to .pdf, however, I'm not sure if it matches your requirements:
Open the .md file with Chrome -> Print -> Destination: Save as PDF -> Save
