### ISSUE TITLE
Problem with installing kinectsdk1

### ISSUE THREAD

**Issue by jasjuang** [Microsoft/vcpkg#1933]
I am on VS2015 and trying to install the x64-windows version. I am trying to install kinectsdk1 with `vcpkg install kinectsdk1` and here is the error message 

``````
C:\vcpkg>vcpkg install kinectsdk1
The following packages will be built and installed:
    kinectsdk1:x64-windows
Starting package 1/1: kinectsdk1:x64-windows
Building package kinectsdk1:x64-windows...
Expected major version 14 or 15 but got: 12

C:\vcpkg>
``````

The weird thing is this error only happens to my windows server on AWS, but it compiles fine on my local computer. Does anyone also experience this error?

**Comment by ras0219-msft** [comment]
Thanks for reporting this! This is a regression on master.

I've pushed 540046b5 to fix it; could you please try that version and let me know if it resolves the issue?

**Comment by jasjuang** [comment]
Thanks for the quick response. The new commit fixes it.
