### ISSUE TITLE
[libvpx] Missing vcpkg_fixup_pkgconfing

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#19346]
libvpx install invalid pc files.

Found due to:
```
CMake Error in /mnt/vcpkg-ci/buildtrees/qtwebengine/x64-linux-dbg/CMakeFiles/CMakeTmp/CMakeLists.txt:
  Imported target "PkgConfig::VPX" includes non-existent path

    "/mnt/vcpkg-ci/packages/libvpx_x64-linux/debug/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```

**Comment by dg0yt** [comment]
I wonder if there shouldn't be general checks for absolute paths (`packages`, `installed`) in any installed .pc and .cmake files.

**Comment by NancyLi1013** [comment]
> I wonder if there shouldn't be general checks for absolute paths (`packages`, `installed`) in any installed .pc and .cmake files.

Why do you think it doesn't need to check the absolute paths?

**Comment by dg0yt** [comment]
> Why do you think it doesn't need to check the absolute paths?

Maybe I am misunderstood. To make it clear: All installed pc and cmake files should be checked for absolute paths (containing "packages" or "installed", and error shall be thrown if a match is found.

**Comment by NancyLi1013** [comment]
Currently, there is no way to checked automatically. So we need to add vcpkg_fixup_pkgconfig() or 
`vcpkg_fixup_cmake_targets()` to fix the path in .pc files and .cmake files.

**Comment by Neumann-A** [comment]
The point is there should be a check either in the vcpkg binary or in `ports.cmake` which checks for pc and/or cmake files and checks if `vcpkg_fixup_cmake_targets` or `vcpkg_fixup_pkgconfig` was called or reads the pc files itself for absolute paths. In general nearly all files need to be checkd for absolute paths not only pc and cmake files.
