### ISSUE TITLE
I cant isntall anything with vcpkg allways returns  failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by Nokimochi1** [microsoft/vcpkg#19340]
**Host Environment**
- OS: Windows
- Compiler: I have whole visual studio installed

**To Reproduce**
`./vcpkg install anything`

**Failure logs** 
Building package sqlite3[core]:x86-windows...
-- Downloading https://sqlite.org/2021/sqlite-amalgamation-3350500.zip -> sqlite-amalgamation-3350500.zip...
-- Extracting source C:/important/vcpkg/downloads/sqlite-amalgamation-3350500.zip
-- Applying patch fix-arm-uwp.patch
-- Using source at C:/important/vcpkg/buildtrees/sqlite3/src/3350500-adf155e1e1.clean
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: ninja -v
    Working Directory: C:/important/vcpkg/buildtrees/sqlite3/x86-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\important\vcpkg\buildtrees\sqlite3\config-x86-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:345 (vcpkg_execute_required_process)
  ports/sqlite3/portfile.cmake:27 (vcpkg_configure_cmake)
  scripts/ports.cmake:141 (include)

Error: Building package sqlite3:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: sqlite3:x86-windows
  Vcpkg version: 2021-07-26-9425cf5f512f242c0bcbabac31f08832825aee81

Additionally, attach any relevant sections from the log files above.

**Additional context**
I tried a lot of things but nothing seemed to work hope you can help me

**Comment by autoantwort** [comment]
> C:\important\vcpkg\buildtrees\sqlite3\config-x86-windows-out.log
Please provide the logs :)

**Comment by JonLiu1993** [comment]
@Nokimochi1 ,Thanks for posting this issue,Could you please provide the logs:
````
C:\important\vcpkg\buildtrees\sqlite3\config-x86-windows-out.log
````

**Comment by Nokimochi1** [comment]
nevermind my issue was with Visual Studio wrong language and it didnt want to install my bad guys sorry!
