### ISSUE TITLE
Not sure if static builds are using static libs

### ISSUE THREAD

**Issue by jdx-john** [microsoft/vcpkg#19341]
We use a .props file in our vcpkg-enabled builds:

```
  <PropertyGroup>
	<WindowsTargetPlatformVersion>10.0.18362.0</WindowsTargetPlatformVersion>
	<PlatformToolset>v142</PlatformToolset>
    <VcpkgEnabled>true</VcpkgEnabled>
	<VcpkgUseStatic>true</VcpkgUseStatic> 

```
We were building without `VcpkgUseStatic` but I added this and re-ran our build. I can see seemingly as many DLLs are being copied as previously in the `AppLocalFromInstalled` step in the msbuild logs. And I see this:

> VcpkgTripletSelection:
>          Using triplet "x64-windows-vs2019" from "C:\vcpkg\scripts\buildsystems\msbuild\..\..\..\installed\x64-windows-vs2019\"

I am not sure if it should explicitly mention static building or not, I not it should append `-static` to the triplet name but not whether it should display this. The raw path above does _not_ include the static suffix.

I am aware some ports only support dynamic linking but it seems like it's doing it for everything. 
Is there some way to tell for certain if it is using the static version or not? Could I bodge something into one of the scripts maybe?

**Comment by autoantwort** [comment]
Afaik this only works if you not use a custom triplet name. If you use a custom triplet name you have to add `-static` yourself

**Comment by jdx-john** [comment]
Can anyone confirm @autoantwort is correct? I can't really see how vcpkg even knows it's a custom triplet and I figured it was a simple shortcut `if(VcPckUseStatic)triplet = triplet+"-static"` but it's an easy workaround. I could try building with my explicit static triplet by name tomorrow, but it takes a while to build :)

**Comment by autoantwort** [comment]
https://github.com/microsoft/vcpkg/blob/b7f99c3c4b32c0b31b73701e92bb42fbea0c83cb/scripts/buildsystems/msbuild/vcpkg.targets#L15-L16

**Comment by jdx-john** [comment]
> https://github.com/microsoft/vcpkg/blob/b7f99c3c4b32c0b31b73701e92bb42fbea0c83cb/scripts/buildsystems/msbuild/vcpkg.targets#L15-L16

Oh, hang on my msbuild script is very minimal but is that saying in L16 to _only_ use the result of L15 _if_ the triplet is empty, e.g. default? I missed that!

**Comment by autoantwort** [comment]
> is that saying in L16 to only use the result of L15 if the triplet is empty, e.g. default?

Yeah. So instead of doing `<VcpkgUseStatic>true</VcpkgUseStatic>` in your property sheet do ` <VcpkgTriplet>$(VcpkgPlatformTarget)-$(VcpkgOSTarget)-vs2019-static</VcpkgTriplet> ` or something like that.

**Comment by jdx-john** [comment]
Many thanks. Yeah we just need to explicitly set our triplet name. 

I'll close as it seems to be pretty clear. I do wonder if this functionality is ideal (or if the documentation in VS could be improved). I quite like the idea of specifying triplet but still being able to toggle -static personally.
