### ISSUE TITLE
Error: Building package boost-config:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by Nameisedith** [microsoft/vcpkg#19352]
I want to use vcptk to intall pcl,but  I have some trouble during installation.Please help me solve these.

C:\vcptk\vcpkg-master>.\vcpkg install pcl
Computing installation plan...
The following packages will be built and installed:
  * boost-algorithm[core]:x86-windows -> 1.76.0
  * boost-align[core]:x86-windows -> 1.76.0
  * boost-any[core]:x86-windows -> 1.76.0
  * boost-array[core]:x86-windows -> 1.76.0
  * boost-asio[core]:x86-windows -> 1.76.0
  * boost-assert[core]:x86-windows -> 1.76.0
  * boost-atomic[core]:x86-windows -> 1.76.0
  * boost-bimap[core]:x86-windows -> 1.76.0
  * boost-bind[core]:x86-windows -> 1.76.0
  * boost-build[core]:x64-windows -> 1.75.0
  * boost-chrono[core]:x86-windows -> 1.76.0
  * boost-circular-buffer[core]:x86-windows -> 1.76.0
  * boost-concept-check[core]:x86-windows -> 1.76.0
  * boost-config[core]:x86-windows -> 1.76.0
  * boost-container[core]:x86-windows -> 1.76.0
  * boost-container-hash[core]:x86-windows -> 1.76.0
  * boost-context[core]:x86-windows -> 1.76.0
  * boost-conversion[core]:x86-windows -> 1.76.0
  * boost-core[core]:x86-windows -> 1.76.0
  * boost-coroutine[core]:x86-windows -> 1.76.0
  * boost-date-time[core]:x86-windows -> 1.76.0
  * boost-detail[core]:x86-windows -> 1.76.0
  * boost-dynamic-bitset[core]:x86-windows -> 1.76.0
  * boost-endian[core]:x86-windows -> 1.76.0
  * boost-exception[core]:x86-windows -> 1.76.0
  * boost-filesystem[core]:x86-windows -> 1.76.0
  * boost-foreach[core]:x86-windows -> 1.76.0
  * boost-format[core]:x86-windows -> 1.76.0
  * boost-function[core]:x86-windows -> 1.76.0
  * boost-function-types[core]:x86-windows -> 1.76.0
  * boost-functional[core]:x86-windows -> 1.76.0
  * boost-fusion[core]:x86-windows -> 1.76.0
  * boost-graph[core]:x86-windows -> 1.76.0
  * boost-integer[core]:x86-windows -> 1.76.0
  * boost-interprocess[core]:x86-windows -> 1.76.0
  * boost-intrusive[core]:x86-windows -> 1.76.0
  * boost-io[core]:x86-windows -> 1.76.0
  * boost-iostreams[core]:x86-windows -> 1.76.0
  * boost-iterator[core]:x86-windows -> 1.76.0
  * boost-lambda[core]:x86-windows -> 1.76.0
  * boost-lexical-cast[core]:x86-windows -> 1.76.0
  * boost-math[core]:x86-windows -> 1.76.0
  * boost-modular-build-helper[core]:x64-windows -> 1.76.0#1
  * boost-move[core]:x86-windows -> 1.76.0
  * boost-mp11[core]:x86-windows -> 1.76.0
  * boost-mpl[core]:x86-windows -> 1.76.0
  * boost-multi-array[core]:x86-windows -> 1.76.0
  * boost-multi-index[core]:x86-windows -> 1.76.0
  * boost-numeric-conversion[core]:x86-windows -> 1.76.0
  * boost-optional[core]:x86-windows -> 1.76.0
  * boost-parameter[core]:x86-windows -> 1.76.0
  * boost-phoenix[core]:x86-windows -> 1.76.0
  * boost-pool[core]:x86-windows -> 1.76.0
  * boost-predef[core]:x86-windows -> 1.76.0
  * boost-preprocessor[core]:x86-windows -> 1.76.0
  * boost-property-map[core]:x86-windows -> 1.76.0
  * boost-property-tree[core]:x86-windows -> 1.76.0
  * boost-proto[core]:x86-windows -> 1.76.0
  * boost-ptr-container[core]:x86-windows -> 1.76.0
  * boost-random[core]:x86-windows -> 1.76.0
  * boost-range[core]:x86-windows -> 1.76.0
  * boost-ratio[core]:x86-windows -> 1.76.0
  * boost-rational[core]:x86-windows -> 1.76.0
  * boost-regex[core]:x86-windows -> 1.76.0
  * boost-serialization[core]:x86-windows -> 1.76.0
  * boost-signals2[core]:x86-windows -> 1.76.0
  * boost-smart-ptr[core]:x86-windows -> 1.76.0
  * boost-sort[core]:x86-windows -> 1.76.0
  * boost-spirit[core]:x86-windows -> 1.76.0
  * boost-static-assert[core]:x86-windows -> 1.76.0
  * boost-system[core]:x86-windows -> 1.76.0
  * boost-test[core]:x86-windows -> 1.76.0
  * boost-thread[core]:x86-windows -> 1.76.0
  * boost-throw-exception[core]:x86-windows -> 1.76.0
  * boost-tokenizer[core]:x86-windows -> 1.76.0
  * boost-tti[core]:x86-windows -> 1.76.0
  * boost-tuple[core]:x86-windows -> 1.76.0
  * boost-type-index[core]:x86-windows -> 1.76.0
  * boost-type-traits[core]:x86-windows -> 1.76.0
  * boost-typeof[core]:x86-windows -> 1.76.0
  * boost-uninstall[core]:x64-windows -> 1.75.0#1
  * boost-unordered[core]:x86-windows -> 1.76.0
  * boost-utility[core]:x86-windows -> 1.76.0
  * boost-uuid[core]:x86-windows -> 1.76.0
  * boost-variant[core]:x86-windows -> 1.76.0
  * boost-winapi[core]:x86-windows -> 1.76.0
  * boost-xpressive[core]:x86-windows -> 1.76.0
  * bzip2[core]:x86-windows -> 1.0.8#2
  * eigen3[core]:x86-windows -> 3.3.9
  * flann[core]:x86-windows -> 2019-04-07#2
  * liblzma[core]:x86-windows -> 5.2.5#3
  * libpng[core]:x86-windows -> 1.6.37#15
  * lz4[core]:x86-windows -> 1.9.3
  * openssl[core]:x86-windows -> 1.1.1k#8
    pcl[core]:x86-windows -> 1.11.1#4
  * qhull[core]:x86-windows -> 8.0.2
  * vcpkg-cmake[core]:x64-windows -> 2021-07-26
  * vcpkg-cmake-config[core]:x64-windows -> 2021-05-22#1
  * xxhash[core]:x86-windows -> 0.8.0#1
  * zlib[core]:x86-windows -> 1.2.11#11
  * zstd[core]:x86-windows -> 1.4.9
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x86-windows...
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\b2\b2ecf60fc1e3d5458dd44f1ee6e218202a19dca21bf96ac264882205546fcf46.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\ad\adfb83e00f201de3bdb91a72123314c5cada9623c54f509ec2227a3fcb6c3979.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\f9\f93ebe231928982a4781d9d7a19a6fc8d221a9022de68e087d94e9e1819da534.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\63\6395313d479d84a65d71fa70afc29d9efb1932ce8a689c14eafd80008da94c32.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\89\89b6a2e5720ba3ca9b102a2a67e174b437897da281cde3db4fe9019d5181f502.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\58\580081bcc61606164688205b07db4c70df917b45ca87365ea04c35159b7e010d.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\9c\9ce93d56c1aae0d02014a9458945365958cb030c3a2a5e2c5fc933f59b183c03.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\48\487b961271714382831ec14352ab28c2bb3d8cc992bdb39ba99841cd5ad95bdd.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\0d\0d38b0f8e23f431c88b4b3097857ddb5e64f918fb521da405fc88250bc69b349.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\ca\cafea7f7460540eb94acdac124fb1c250829631dfbc52436800b7538bbe353ac.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\aa\aa0547af52fc669ea886857a05d058039a15296f0a033e05c6f678b7cb77d4c8.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\0f\0f45881792d6aeb5e3debbef8b84903af0b580bd3a773484e4e221404dcec9dc.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\e9\e9b7a13d5ff9fe374022c51e23376e9262db5575fdbf11a0d7aec827b25640d8.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\41\414631306cbefe586678e20d11241cb9ea655554e6108cfa53dd13fcfa45372d.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\35\35f528789c51ee78d1ff2a6c1d8da3421f0996258054210ca15427bc7afc66f9.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\ab\ab275670f06fef8b69603cee9fb31e0bc1468358e8f6905e42c4ec46b86a4488.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\24\2484804db753d217ba5d3e6474062e524c90e2fdb46b64b5bc12463f8d68d245.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\e0\e06b4a69139b330b4c6051d4ba201f52ff065cb7c78122c149506d5c6367dc5a.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\ba\ba6149d83a016aedddc7318786633bc5d90565cd1a4b07a14f660b7708e5a7a9.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\f4\f433a4fda95c6b5873a4c4fe9459c7f98a2d5ff8cba2755d5aa9621f22aa8b7c.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\95\9563a7e53e72fbe46246d366294b06d7685a3c5cc22351a4e144f2fbd459de37.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\13\13b3e16db86105a5d224bfc918883d54bbea1e198a7405d24d6e4a5aca52e4da.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\c7\c7215b2ff57751cd693c48b6f31bcc2f10a8362794e6f582a94a1adf3f82da02.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\e8\e889bd872d572697a7ab548ce1a7666155837d00706c34123acec417ee68cee0.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\81\811059c37262b9dee8775cca991c4f0a5cf2f32a38fb2ec96bd01e014469557f.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\d2\d201dafe6578e1aa9f837a5d56e0404d2f89c1742a141f94a225a969a19a3710.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\03\03fd3ed29926965bbcd67de22010159e31743c14a432a802f2e916eda190dffd.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\79\7971e631abf4cf35b89ebb6695bad743ef5610d059505b6ff56a8037086e997c.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\33\33a87f1ea3f1f8f4cbe2ab2f643bd54f09b56d6c7b313dca09e87ed0275116a5.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\5b\5bd9c14c822f07ac615ba75f863d7943374d3d27c714aa8bca328a79839a6abd.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\71\71760dd0601a661861ee8de9233e998fe539a42544ac31c7c53aae9eb229ba85.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\10\10f0ac240614bd7d1e8df786f0e2ac52692e8b1348227de52e0a85be381cf69e.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\2a\2a7b5ec911e81ed61e5ef0efbfcdac40b940ccf39476e31d58de1e70a427ab11.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\d1\d191df452378ae5acb3ea73579b38c9eaa96de7cb5d41908cad3acf1a8c4ba63.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\20\204bb8e0206acea87cd83597b9917046d992142299415713c5212ca8a8792d5c.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\5e\5e9c898249df441b3129b4966692c69b6c832e7f23c10b7f3c6c8ebcc19c0d7f.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\8d\8de800829590729da5d6f8d9f03ec581fc9d55fbfb0113839d9173ca83934c9d.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\f2\f296bcca00dee922262b4959c8cc8beec534d6522ce759ab9b24dfefaa15d1a6.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\9b\9bdf7842a9263836e8296366da1a533a40e20215c6aaf399e3f4428141994ecd.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\a9\a92aafe52a1d18cfc0a0140f3ec2b3583349797216b2abaffe2f708a9b9e3e60.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\49\49e849d9998b110f6fe0910d049f25b276e0dc64682beedd8576affa1b80f96d.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\69\6944ef0cf27ab285a7d44e88fd4766ce75465bed10ff1162cbf44c4f29bbcfcb.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\48\485261d7a46354db5c52adc0af08571af65db5fcb5d6f045714d0f588f1d9895.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\3c\3c1f09bd607496b29c3cce3fccc70e8fd026c157440aa1f0610ff4c0f4758d6a.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\9d\9decfa01889663eba59763c6bae86c7a5f88cdd650858e6a7acd299d9e2e9d46.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\26\264c2c898b858bde7942a6609952f585dee4c278bbd3ff2991f72dd5a89e88b7.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\de\de4f1653bf1b6d1c3074bf56723ba29a6948447d9f835e91e5427259d6bd9829.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\16\1666b783929102052d429ef60ed63959f026fba5b3c9b47fefe1eaa5935882b1.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\59\5915fd863079cdc213a7f5db2e4a6c0f0bb5157c630710ed7fa817a62e0eda4c.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\8c\8cee4756069bed1cc9aa822e682a074dd1e3b8f1d4aca73071dc45e701e5643d.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\3b\3b28d7a6deea813bf97d19591b76dcde1dc0e209b216a907c89091afbc77804f.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\c6\c6133f7ff7baff08d66f59e0572a31931ff29221510393c5a49059e5993dbb4e.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\9e\9ef3d2c531ec03cee7268a0f2d1143e04f48db58c86c8907c4e33636c21b425e.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\8c\8c08364127c24f8d70de78cd08aebf28553efbc6605cc0bd11ae2e02af9e4699.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\8f\8f388826c3d6697cd9c90c34ad16f1270382f2b27cf2dcead30704bf06800162.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\5e\5e11af2b638681e7169a1f7ce63d5c28d42004f4ab2b257801ad7ed969418ff7.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\aa\aafc7207372d8e294a75dec8ec264430721f069653509f26d2b797f204bb197f.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\2e\2e5f855577a0a17919aa2145a8f6c1cc2004ef9e4d91799a90e472d3480dd487.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\c3\c33bd3b03a63aec7f16373cde7917e8cb434cb416689435e7c225bdfa227ca2b.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\63\63996b9e8612783b99fb50324d478501b0a00cd724a3793a7ab31e0e9cf0f93b.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\1a\1a021b6ebbb977198f09ee80182dd9d1f9f8211f98c00134a7d4af8a959293ad.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\60\60ef3ff7462ff4cf2a098030c0f690957732b603d9b9dff4ae1ebfab4b51db35.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\84\84cb59a84f06ee8205838bf58611f8e8c81b2f1e70e7349466170057c355aa36.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\a4\a4dfa129ac2778b85a4925e730f3ecc69d6e82c0e3d45dcefdfad1a1cb26db7f.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\66\66182e06dc0c0d2b369a43e4ad9b88f2e2c7f89a2c41ebafd80bf7aa2eb342be.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\ba\ba7c9a0d30fcd9a03932f26c9785d5bc79c5ee7598b26774dd7aadfd2c067998.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\55\55750bb2e33b10c91620af4f9b444618bd662c3fd0d9e9f852c7b17c86b038d4.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\64\646812e3c7e947ab2781237498693d066af9005865724b9d1b7e637f130088da.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\cb\cb4fa186e6f2a3afae67011bde767bf835b15d0a9a1a70649a2c073fa4f00f18.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\e4\e4ab2ff43d8832760a74073a75de07ae1afad59680fa849df12605cd682f14a9.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\2f\2fecb60c3e8ff41756e36a4fc8bbdb1c9fe2dcbef5fe883066a5fe59b0b297af.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\0a\0a34561a721fe099d36208d1c62d985015801a75c6b8084989412d4bc73d42bd.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\17\17b323bdba8ae03e202c368b279fe28834d7f767fe99aa0df6a555a8006640d8.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\80\802329f7228096c4e6bb42c6273897ca3418650a8b86b40b29dd51648c902572.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\c6\c62629998efe9e511767ea0c92d11f99d787d8779207bb05e83fb6a7116b6932.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\e4\e476af205257d9b5eebec51adfcbc27bfb3ca7266ce619dbe9783a0aa4bf0b03.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\12\122c4707a37f866323772ed63d7751f6ee78c6438c59a0bb41512881596c3bf7.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\b4\b471422af0dc223982d77b8e9c71e75c1c1824ae32015824e619f879a08b9ec8.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\f2\f29896ef22759275c84823cf6b9e1d551690f5b9dc72e64ad54998f38c46a95a.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\85\855ca893fcd67e39a358764ed8f6bebd3e6ba82fcaef226089312a988d206c6b.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\eb\ebceb49ab02b3bbd8224fb31ca34c0dab2b422cafa6c65d9e2cbd70255274230.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\73\73b0907d9416c588e1ae8c3328fac92cfb2f91fb791594eb46461a6a1528e47c.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\f9\f90cbbec0a026e0a5b33121b503521b1be37178e5b3420b1e14fc4ff4c969ce3.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\e8\e808ed2a8aa11033fa8f97691c92eb5ab399635f88f5fe088414dc398a899209.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\3b\3b7711f9fad45ef5e50393523e2ad3b15acc4b1c2f5e3c7ff2c81e47d99e718f.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\49\493feec063576eb46a815af3eedf0dd4bbaef64a909d6dc6583a9d1f9300725a.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\21\211d0b7990b88b9000716e607e1866a7afeb98bd526a6c8b95665c7bfacff452.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\6b\6b802757734344872518d9a285a3932c17a3ea483d8151c092b15355a62f9a92.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\27\27e0a937167ed645bb9e180b4369f96852cc63f013d8b4586151bd5c12a0bb6d.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\86\86370a8ec9d381e4c94885cbcaa5f3024749db703c35bcd9a8c4549377896f29.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\63\637c2831701b4ec4b91e451dc5636808177dc1a1c6302f4e7295c5347c19d1f1.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\58\584d2801fcad250a4837eef7b14989253fdebce945ddfdd3f85fd49d8beab64e.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\cc\ccfb42cea15624a82eb15ad79518d58bb3737cdf702bb81870e53ce4522c2a4f.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\78\78be5ce35c60aac2fc9e592ad9d5faa9464a8412d8e12362c7e0e910bf05ba59.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\bf\bf8ce9ab18fc61ae2401c4dd8736bec9ffa57665dc9415242e0b03ae7c3ecef1.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\00\0004deac175a6a13860c18d7b7dd450ef42c90fdffd2e2d12dac14ba753594f4.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\17\173df8a9d535a2674c97466fa4df8734106ea2d3641ea6ade22465f7febf1206.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\99\999f72fc45b4f38260ace6411e006a81ad98de79d559316153d9f0fbf6be62c8.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\80\80a2ee769bf2ec1876298bb14f509727a66bad1f01802bb972e052662b0cba4e.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\30\300465158d235b6515454e3ccff098f8cb034f6a6dba20fa128bda4bfca305d6.zip
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\d6\d672cabb5c7d556dcee9e7fa7cd3a7478df5014c3e79dbb3793dfa6d401c51ca.zip
Starting package 1/101: boost-config:x86-windows
Building package boost-config[core]:x86-windows...
-- Using C:/vcptk/vcpkg-master/downloads/boostorg-config-boost-1.76.0.tar.gz
-- Cleaning sources at C:/vcptk/vcpkg-master/buildtrees/boost-config/src/ost-1.76.0-c5d6f64586.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcptk/vcpkg-master/downloads/boostorg-config-boost-1.76.0.tar.gz
-- Using source at C:/vcptk/vcpkg-master/buildtrees/boost-config/src/ost-1.76.0-c5d6f64586.clean
-- Packaging headers
-- Packaging headers done
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.74.0/LICENSE_1_0.txt -> boost_LICENSE_1_0.txt...
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' = off
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.74.0/LICENSE_1_0.txt
Error: Failed to download from mirror set:
https://raw.githubusercontent.com/boostorg/boost/boost-1.74.0/LICENSE_1_0.txt: WinHttpSendRequest() failed: 12007

[DEBUG] C:\a\1\s\src\vcpkg\base\downloads.cpp(626)
[DEBUG] Exiting after 97160 us (76994 us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:251 (message):

      Failed to download file.
      If you use a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.

      3. You proxy's remote server is out of service.

      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)

      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  installed/x86-windows/share/boost-vcpkg-helpers/boost-modular-headers.cmake:17 (vcpkg_download_distfile)
  ports/boost-config/portfile.cmake:12 (boost_modular_headers)
  scripts/ports.cmake:141 (include)

Error: Building package boost-config:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-config:x86-windows
  Vcpkg version: 2021-07-26-9425cf5f512f242c0bcbabac31f08832825aee81

Additionally, attach any relevant sections from the log files above.

**Comment by Nameisedith** [comment]
My system is Win10 x64.I try to install pclx64，but  failed.

C:\vcptk\vcpkg-master>.\vcpkg isntall pcl:x64-windows
invalid command: isntall
Commands:
  vcpkg search [pat]              Search for packages available to be built
  vcpkg install <pkg>...          Install a package
  vcpkg remove <pkg>...           Uninstall a package
  vcpkg remove --outdated         Uninstall all out-of-date packages
  vcpkg list                      List installed packages
  vcpkg update                    Display list of packages for updating
  vcpkg upgrade                   Rebuild all outdated packages
  vcpkg x-history <pkg>           (Experimental) Shows the history of CONTROL versions of a package
  vcpkg hash <file> [alg]         Hash a file by specific algorithm, default SHA512
  vcpkg help topics               Display the list of help topics
  vcpkg help <topic>              Display help for a specific topic

  vcpkg integrate install         Make installed packages available user-wide. Requires admin
                                  privileges on first use
  vcpkg integrate remove          Remove user-wide integration
  vcpkg integrate project         Generate a referencing nuget package for individual VS project use
  vcpkg integrate powershell      Enable PowerShell tab-completion

  vcpkg export <pkg>... [opt]...  Exports a package
  vcpkg edit <pkg>                Open up a port for editing (uses %EDITOR%, default 'code')
  vcpkg create <pkg> <url> [archivename]
                                  Create a new package
  vcpkg x-init-registry <path>    Initializes a registry in the directory <path>
  vcpkg owns <pat>                Search for files in installed packages
  vcpkg depend-info <pkg>...      Display a list of dependencies for packages
  vcpkg env                       Creates a clean shell environment for development or compiling
  vcpkg version                   Display version information
  vcpkg contact                   Display contact information to send feedback

Options:
  --triplet=<t>                   Specify the target architecture triplet. See 'vcpkg help triplet'
                                  (default: %VCPKG_DEFAULT_TRIPLET%)
  --host-triplet=<t>              Specify the host architecture triplet. See 'vcpkg help triplet'
                                  (default: %VCPKG_DEFAULT_HOST_TRIPLET%)
  --overlay-ports=<path>          Specify directories to be used when searching for ports
                                  (also: %VCPKG_OVERLAY_PORTS%)
  --overlay-triplets=<path>       Specify directories containing triplets files
                                  (also: %VCPKG_OVERLAY_TRIPLETS%)
  --binarysource=<path>           Add sources for binary caching. See 'vcpkg help binarycaching'
  --downloads-root=<path>         Specify the downloads root directory
                                  (default: %VCPKG_DOWNLOADS%)
  --vcpkg-root=<path>             Specify the vcpkg root directory
                                  (default: %VCPKG_ROOT%)
  --x-buildtrees-root=<path>      (Experimental) Specify the buildtrees root directory
  --x-install-root=<path>         (Experimental) Specify the install root directory
  --x-packages-root=<path>        (Experimental) Specify the packages root directory
  --x-scripts-root=<path>         (Experimental) Specify the scripts root directory
  --x-builtin-ports-root=<path>   (Experimental) Specify the packages root directory
  --x-builtin-registry-versions-dir=<path>
                                  (Experimental) Specify the versions root directory
  --x-json                        (Experimental) Request JSON output

  @response_file                  Specify a response file to provide additional parameters

For more help (including examples) see the accompanying README.md and docs folder.

Thus,the command I'm using now is  C:\vcptk\vcpkg-master>.\vcpkg install pcl

**Comment by PhoebeHui** [comment]
@Nameisedith, could you try if the solution provided in https://github.com/microsoft/vcpkg/issues/13348#issue-692784879 works for you?
We have increased the timeouts for downloads in vcpkg tool, the next release should include the improvements.

> C:\vcptk\vcpkg-master>.\vcpkg isntall pcl:x64-windows
   invalid command: isntall

It should be .\vcpkg install pcl:x64-windows

**Comment by PhoebeHui** [comment]
@Nameisedith, has the problem been solved?

**Comment by Nameisedith** [comment]
Thanks for your advice.Your advice helped me&nbsp; solve this problem sucessfully.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/vcpkg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月4日(星期三) 下午4:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/vcpkg] Error: Building package boost-config:x86-windows failed with: BUILD_FAILED (#19352)





 
@Nameisedith, has the problem been solved?
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
