### ISSUE TITLE
[curl] build failure or rather configuration problem

### ISSUE THREAD

**Issue by ulfllorenz** [microsoft/vcpkg#19359]
**Describe the bug**
It is surprisingly difficult to build curl on Windows _without_ the default non-http feature.

* "vcpkg.exe install curl" installs curl[core,non-http,schannel,ssl,sspi,winssl], due to "non-http" being default. Fine so far.
* "vcpkg.exe install curl[core,ssl]" also installs the non-http feature, which is a bit surprising, because I explicitly want to disable it.
* "vcpkg.exe install curl[core,schannel]" installs curl[core,schannel,sspi], which is what I want.

I think the problem comes from the feature mapping ssl -> winssl -> schannel -> sspi, where only the latter two actually enter the CMake build. The feature winssl does not reference curl[core,schannel], but curl[schannel] (or, in the latest version, does not set default-features to false).

Since this behavior is different from Linux, I guess it counts as a bug.

**Comment by dg0yt** [comment]
Thanks for reporting! Feature `winssl` seems to miss `"default-dependencies": false`. I can pick this up for #18971.

**Comment by ulfllorenz** [comment]
Another question: It may not fit here perfectly, but this is the fundamental reason I am playing around with curl: What is the status of issue https://github.com/microsoft/vcpkg/issues/17919?

**Comment by dg0yt** [comment]
> What is the status of issue #17919?

It is better to ask there, assuming that relevant people are subscribed there.

**Comment by NancyLi1013** [comment]
> I think the problem comes from the feature mapping ssl -> winssl -> schannel -> sspi, where only the latter two actually enter the CMake build. The feature winssl does not reference curl[core,schannel], but curl[schannel] (or, in the latest version, does not set default-features to false).

Could you please provide what the detailed error you encountered for `curl[core,ssl]`?

**Comment by NancyLi1013** [comment]
> Another question: It may not fit here perfectly, but this is the fundamental reason I am playing around with curl: What is the status of issue #17919?

For #17919, it's duplicated to #14030, so you can focus on the status of #14030.

**Comment by ulfllorenz** [comment]
Thanks for the reply regarding the issue status. Regarding the detailed error, there is no error per se. I want to install curl

*  with ssl 
*  http only (i.e., without "non-http")

Normally, you would install "curl[core,ssl]", but that expands to "curl[...,non-http,...]", which is not what I want. And the reason is that the intermediate feature winssl erroneously enables the default features (one of which is non-http).

**Comment by dg0yt** [comment]
@NancyLi1013 Look:

~~~
$ ./vcpkg depend-info curl[core,ssl]:x64-linux
openssl:
zlib:
curl[openssl, ssl]: openssl, zlib
$ ./vcpkg depend-info curl[core,ssl]:x64-windows
zlib:
curl[non-http, ssl, schannel, sspi, winssl]: zlib
~~~

**Comment by dg0yt** [comment]
> For #17919, it's duplicated to #14030, so you can focus on the status of #14030.

@NancyLi1013 No, these issue are different: #14030 is missing LDAPS with WinLDAP. #17919 is uncontrolled system dependencies with OpenLDAP.

**Comment by NancyLi1013** [comment]
@ulfllorenz 

Since #18971 has been merged, could you please try to update to the latest vcpkg to rebuild this?

**Comment by ulfllorenz** [comment]
Looks good, produces good output, I think this issue can be closed.
