### ISSUE TITLE
Naming confusion for boost libs?

### ISSUE THREAD

**Issue by jdx-john** [microsoft/vcpkg#19362]
When we built boost manually against VS2017 (v141) using CMake we got libraries named such as:

> boost_atomic-vc141-mt-gd-x32-1_68.lib

However now we build using vcpkg with VS2019 (v142) we get the library named like:

> boost_atomic-vc140-mt.lib

It seems strange that it is named "v140" and odd that it misses all the extra information from the library like the version number (1.76 IIRC). Is it just the way whoever build the port set it up? Maybe it's considered better the library file keeps the same name across versions?

**Comment by jdx-john** [comment]
Thanks @mathisloge I can confirm the *DLL* seems to have the full name (boost_atomic-vc142-mt-x32-1_76.dll for me) but the .lib does not. 
So I suspect a very minor issue in CMake scripts perhaps?

**Comment by Osyotr** [comment]
See https://github.com/microsoft/vcpkg/commit/b2b2c9136918ed3ef85961c5c2885b9562d07d1d
@ras0219-msft would you kindly elaborate?

**Comment by PhoebeHui** [comment]
See https://github.com/microsoft/vcpkg/issues/601#issuecomment-276220946.
