### ISSUE TITLE
folly fails to build - Histogram.cpp 

### ISSUE THREAD

**Issue by sfinktah** [Microsoft/vcpkg#1936]
Apologies for yet another folly issue.

TLDR:
```
E:\git\vcpkg\buildtrees\folly\src\folly-2017.07.17.01\folly\stats\Histogram.cpp(42): error C5037: 'folly::detail::HistogramBuckets<__int64,folly::detail::Bucket<T>>::getPercentileBucketIdx': an out-of-line definition of a member of a class template cannot have default arguments
        with
        [
            T=int64_t
        ]
```

```

Call Stack (most recent call first):
  E:/git/vcpkg/scripts/cmake/vcpkg_install_cmake.cmake:49 (vcpkg_execute_required_process)
  E:/git/vcpkg/ports/folly/portfile.cmake:41 (vcpkg_install_cmake)
  E:/git/vcpkg/scripts/ports.cmake:72 (include)


Error: Building package folly:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: folly:x64-windows
  Vcpkg version: 0.0.90-2017-10-04-d8507cd159f8de6ae174cae9894c926f75fe50d7
```

To actually obtain an error, it was necessary to run cmake manually, as no errors appeared in the log files.

```
E:\git\vcpkg\buildtrees\folly>cd E:/git/vcpkg/buildtrees/folly/x64-windows-rel

E:\git\vcpkg\buildtrees\folly\x64-windows-rel>E:\git\vcpkg\downloads\cmake-3.9.3-win32-x86\bin\cmake.exe --build . --config Release --target install -- -v

...

FAILED: CMakeFiles/folly_base.dir/folly/stats/Histogram.cpp.obj
C:\PROGRA~2\MIB055~1\2017\ENTERP~1\VC\Tools\MSVC\1411~1.255\bin\HostX64\x64\cl.exe   /TP -DWIN32_LEAN_AND_MEAN -D_CRT_NONSTDC_NO_WARNINGS -D_CRT_SECURE_NO_WARNINGS -D_HAS_AUTO_PTR_ETC=1 -D_SCL_SECURE_NO_WARNINGS -D_STL_EXTRA_DISABLED_WARNINGS="4774 4987" -IE:\git\vcpkg\buildtrees\folly\src\folly-2017.07.17.01 -I. -IE:\git\vcpkg\installed\x64-windows\include /DWIN32 /D_WINDOWS /W3 /utf-8 /GR  /MP /MD /O2 /Oi /Gy /DNDEBUG /Z7   /EHa /GF /Zc:referenceBinding /Zc:rvalueCast /Zc:implicitNoexcept /Zc:strictStrings /Zc:threadSafeInit /Zc:throwingNew /std:c++latest /permissive- /bigobj /favor:blend /Zc:inline /Wall /MP /Gw /Gy /Qpar /Oi /Ot /wd4191 /wd4291 /wd4309 /wd4310 /wd4366 /wd4587 /wd4592 /wd4723 /wd4724 /wd4868 /wd4996 /wd4068 /wd4091 /wd4146 /wd4800 /wd4018 /wd4365 /wd4388 /wd4389 /wd4100 /wd4459 /wd4505 /wd4701 /wd4702 /wd4061 /wd4127 /wd4200 /wd4201 /wd4296 /wd4316 /wd4324 /wd4355 /wd4371 /wd4435 /wd4514 /wd4548 /wd4574 /wd4582 /wd4583 /wd4619 /wd4623 /wd4625 /wd4626 /wd4647 /wd4668 /wd4706 /wd4710 /wd4711 /wd4714 /wd4820 /wd5026 /wd5027 /wd5031 /we4099 /we4129 /we4566 /showIncludes /FoCMakeFiles\folly_base.dir\folly\stats\Histogram.cpp.obj /FdCMakeFiles\folly_base.dir\ /FS -c E:\git\vcpkg\buildtrees\folly\src\folly-2017.07.17.01\folly\stats\Histogram.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.11.25507.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

E:\git\vcpkg\buildtrees\folly\src\folly-2017.07.17.01\folly\stats\Histogram.cpp(42): error C5037: 'folly::detail::HistogramBuckets<__int64,folly::detail::Bucket<T>>::getPercentileBucketIdx': an out-of-line definition of a member of a class template cannot have default arguments
        with
        [
            T=int64_t
        ]
```

**Comment by sfinktah** [comment]
note: building with 2017 (chosen by cmake), it's possible it may compile with 2015, but I don't know how to force it to use 2015.

**Comment by sssnakesss** [comment]
Same issue, although I did find stuff in logs. Prior to the histogram related error are these:

> C:\src\vcpkg\buildtrees\folly\src\folly-2017.07.17.01\folly\io\async\AsyncSocket.cpp(1589): error C2039: 'Control': is not a member of 'msghdr'
C:\src\vcpkg\buildtrees\folly\src\folly-2017.07.17.01\folly/portability/Sockets.h(42): note: see declaration of 'msghdr'
C:\src\vcpkg\buildtrees\folly\src\folly-2017.07.17.01\folly\io\async\AsyncSocket.cpp(1589): error C2228: left of '.len' must have class/struct/union
C:\src\vcpkg\buildtrees\folly\src\folly-2017.07.17.01\folly\io\async\AsyncSocket.cpp(1589): error C2228: left of '.buf' must have class/struct/union
C:\src\vcpkg\buildtrees\folly\src\folly-2017.07.17.01\folly\io\async\AsyncSocket.cpp(1593): error C2039: 'Control': is not a member of 'msghdr'
C:\src\vcpkg\buildtrees\folly\src\folly-2017.07.17.01\folly/portability/Sockets.h(42): note: see declaration of 'msghdr'
C:\src\vcpkg\buildtrees\folly\src\folly-2017.07.17.01\folly\io\async\AsyncSocket.cpp(1593): error C2228: left of '.len' must have class/struct/union
C:\src\vcpkg\buildtrees\folly\src\folly-2017.07.17.01\folly\io\async\AsyncSocket.cpp(1593): error C2228: left of '.buf' must have class/struct/union

Much further down in the log is

> C:\src\vcpkg\buildtrees\folly\src\folly-2017.07.17.01\folly\stats\Histogram.cpp(42): error C5037: 'folly::detail::HistogramBuckets<__int64,folly::detail::Bucket<T>>::getPercentileBucketIdx': an out-of-line definition of a member of a class template cannot have default arguments
        with
        [
            T=int64_t
        ]

**Comment by KindDragon** [comment]
AsyncSocket.cpp error should only be with latest Win10 SDK, because it define `MSG_ERRQUEUE` https://naughter.wordpress.com/2017/07/16/changes-in-the-windows-v10-0-16232-sdk-compared-to-windows-v10-0-15063-sdk-part-one/
