### ISSUE TITLE
[openimageio] update to 2.2.17

### ISSUE THREAD

**Issue by EvanAW** [microsoft/vcpkg#19367]
Library name: OpenImageIO

New version number: 2.2.17

Other information that may be useful (release notes, etc...)

https://github.com/OpenImageIO/oiio/releases/tag/v2.2.17.0

This update has fixes for building against fmt 8.0.0 which might be necessary once https://github.com/microsoft/vcpkg/issues/18577 lands.

**Comment by autoantwort** [comment]
I can do it in #19272

**Comment by JonLiu1993** [comment]
We have an exist PR #19272  to update it.

**Comment by JonLiu1993** [comment]
@EvanAW, openimageio has been updated to 2.2.17, please update vcpkg to use it
