### ISSUE TITLE
Convert all CONTROL to vcpkg.json

### ISSUE THREAD

**Issue by SamuelMarks** [microsoft/vcpkg#19378]
****

**Is your feature request related to a problem? Please describe.**
@JackBoosY was telling me in https://github.com/microsoft/vcpkg/pull/18895#discussion_r683305599 that `vcpkg.json` is preferred over `CONTROL` files for all new ports.

**Proposed solution**
I can write a script to automatically convert `CONTROL` files to `vcpkg.json` files. I'll write + open-source it in any language—do you have a preferred?—and apply it to every port in the vcpkg tree. Additionally any ports with an open PR will be blacklisted… so as not to conflict.

**Describe alternatives you've considered**
Wait for each port to slowly change, after the `CONTROL` has been officially deprecated and starts spitting out warnings.

**Additional context**
EDIT: The [GitHub API](https://docs.github.com/en/rest/reference/repos#get-all-repository-topics) can be used to acquire the tags for `vcpkg.json`. The platform details can be acquired through a simple—though not always 100% accurate—analysis of the CMake file (not UWP is easy; can always use [CMakeJSON](https://github.com/Neumann-A/CMakeJSON)… but that might be too hardcore for this to still be considered a simple script)

**Comment by PhoebeHui** [comment]
> I can write a script to automatically convert CONTROL files to vcpkg.json files.

I like the idea, I think we prefer vcpkg.json for all new ports, and for all exist ports, we prefer to wait for each port to slowly change. It would be help if there is a script to do this. 

@dan-shaw @ras0219-msft, what do you think?

**Comment by autoantwort** [comment]
In general there is `vcpkg format-manifest --all --convert-control` to convert all CONTROL files to vcpkg.json

**Comment by autoantwort** [comment]
947 ports still uses CONTROL files.

**Comment by SamuelMarks** [comment]
#12471 gotcha

Want this extended with those added features I mentioned above?

Also would you accept a PR that applied just the command as is—to the entire tree—but with all the open PR port names blacklisted?

**Comment by Osyotr** [comment]
Please have mercy on reviewers.

**Comment by Neumann-A** [comment]
I think the idea is to convert on port update. Simply because it otherwise invalidates users binary caches only due to a change from `CONTROL` to `vcpkg.json`.

**Comment by SamuelMarks** [comment]
Hey it's the guy from the JSON project! - Cool

RE: Updating just on port update. Can't the binary cache invalidation become conditional on a functional change to the CONTROL/vcpkg.json file rather than a mere change? - Fixing a typo or adding tags shouldn't invalidate the cache… right?

**Comment by mathisloge** [comment]
@PhoebeHui I think this can be closed since all `CONTROL` files were converted to `vcpkg.json` in https://github.com/microsoft/vcpkg/pull/19986

**Comment by SamuelMarks** [comment]
@mathisloge I'm only annoyed that @BillyONeal beat me to the punch!

(notably over a month before his PR I opened https://github.com/microsoft/vcpkg/issues/19436 which proceeded to get no feedback… the idea here as to run through the whole process without dropping to PowerShell; including filtering through GitHub Pull Requests to only upgrade the `CONTROL` files of ports lacking open PRs against them)

**Comment by BillyONeal** [comment]
> the idea here as to run through the whole process without dropping to PowerShell; including filtering through GitHub Pull Requests to only upgrade the `CONTROL` files of ports lacking open PRs against them)

The difficulty is that reviewing thousands of tiny changes is difficult, the trick was to make people review the script that did the conversion instead.

>> @mathisloge I'm only annoyed that @BillyONeal beat me to the punch!
> 
> (notably over a month before his PR I opened #19436 which proceeded to get no feedback… 

The associated PR is still marked "draft" so people probably think you're still working on it. The volume of incoming PRs is high enough that we don't generally look at ones marked that way.

**Comment by SamuelMarks** [comment]
> the trick was to make people review the script that did the conversion instead.

Yes but this was the script to do the conversion https://github.com/microsoft/vcpkg-tool/pull/149

---

Maybe next time I try to do something like this I can tag a few of you by name? - I didn't want to be impolite and do that to start with…

**Comment by JackBoosY** [comment]
> > the trick was to make people review the script that did the conversion instead.
> 
> Yes but this was the script to do the conversion [microsoft/vcpkg-tool#149](https://github.com/microsoft/vcpkg-tool/pull/149)
> 
> Maybe next time I try to do something like this I can tag a few of you by name? - I didn't want to be impolite and do that to start with…

Yeah, you can do that.
