### ISSUE TITLE
opencv3[ffmpeg] build failure

### ISSUE THREAD

**Issue by seccpur** [microsoft/vcpkg#19372]
**Host Environment**
- OS: Windows 10
- Compiler: VC++ 2019

**To Reproduce**
`./vcpkg install opencv3[ffmpeg]:x64-windows`

**Failure logs** 
`PS D:\repos\vcpkg> .\vcpkg install opencv3[ffmpeg]:x64-windows
Computing installation plan...
The following packages will be built and installed:
    opencv3[core,dnn,ffmpeg,flann,jpeg,png,quirc,tiff,webp]:x64-windows -> 3.4.13
  * quirc[core]:x64-windows -> 1.1#2
Additional packages (*) will be modified to complete this operation.
Warning: The following VS instances are excluded because the English language pack is unavailable.
    C:\Program Files (x86)\Microsoft Visual Studio 14.0
Please install the English language pack.
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\Encoded\AppData\Local\vcpkg\archives\d0\d066d7bdccd40e9c4123f49850a1748703445a08.zip
Could not locate cached archive: C:\Users\Encoded\AppData\Local\vcpkg\archives\68\683102019646b39d88f1e720165b8159c6be41f3.zip
Starting package 1/2: quirc:x64-windows
Building package quirc[core]:x64-windows...
-- Note: quirc only supports static library linkage. Building static library.
-- Downloading https://github.com/dlbeer/quirc/archive/7e7ab596e4d0988faf1c12ae89c354b114181c40.tar.gz -> dlbeer-quirc-7e7ab596e4d0988faf1c12ae89c354b114181c40.tar.gz...
-- Extracting source D:/Repos/vcpkg/downloads/dlbeer-quirc-7e7ab596e4d0988faf1c12ae89c354b114181c40.tar.gz
-- Using source at D:/Repos/vcpkg/buildtrees/quirc/src/b114181c40-f1e71e0d5b.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: D:/Repos/vcpkg/packages/quirc_x64-windows/share/quirc/copyright/LICENSE
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\Encoded\AppData\Local\vcpkg\archives\d0\d066d7bdccd40e9c4123f49850a1748703445a08.zip
Building package quirc[core]:x64-windows... done
Installing package quirc[core]:x64-windows...
Installing package quirc[core]:x64-windows... done
Elapsed time for package quirc:x64-windows: 4.34 s
Starting package 2/2: opencv3:x64-windows
Building package opencv3[core,dnn,ffmpeg,flann,jpeg,png,quirc,tiff,webp]:x64-windows...
-- Downloading https://github.com/opencv/opencv/archive/3.4.13.tar.gz -> opencv-opencv-3.4.13.tar.gz...
-- Extracting source D:/Repos/vcpkg/downloads/opencv-opencv-3.4.13.tar.gz
-- Applying patch 0001-disable-downloading.patch
-- Applying patch 0002-install-options.patch
-- Applying patch 0003-force-package-requirements.patch
-- Applying patch 0004-fix-eigen.patch
-- Applying patch 0005-fix-vtk9.patch
-- Applying patch 0006-fix-uwp.patch
-- Applying patch 0008-devendor-quirc.patch
-- Using source at D:/Repos/vcpkg/buildtrees/opencv3/src/3.4.13-1d83403e4f.clean
CMake Deprecation Warning at scripts/cmake/vcpkg_check_features.cmake:182 (message):
  calling `vcpkg_check_features` without the `FEATURES` keyword has been
  deprecated.

      Please add the `FEATURES` keyword to the call.
Call Stack (most recent call first):
  ports/opencv3/portfile.cmake:41 (vcpkg_check_features)
  scripts/ports.cmake:139 (include)

-- Downloading https://github.com/tiny-dnn/tiny-dnn/archive/v1.0.0a3.tar.gz -> opencv-cache/tiny_dnn/adb1c512e09ca2c7a6faef36f9c53e59-v1.0.0a3.tar.gz...
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- mt.exe has failed. This may be the result of anti-virus. Disabling anti-virus on the buildtree folder may improve build speed
-- Restarting Build x64-windows-rel because of mt.exe file locking issue. Iteration: 1
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:122 (file):
  file failed to open for reading (No such file or directory):

    D:/Repos/vcpkg/-out-1.log
Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:104 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:44 (vcpkg_build_cmake)
  ports/opencv3/portfile.cmake:346 (vcpkg_install_cmake)
  scripts/ports.cmake:139 (include)

Error: Building package opencv3:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: opencv3:x64-windows
  Vcpkg version: 2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9`

**Comment by JonLiu1993** [comment]
@seccpur ,Thanks for posting this issue,please provide the error log:
```
D:/Repos/vcpkg/-out-1.log

```

**Comment by seccpur** [comment]
Somehow the log was missing. I tried a second installation in the hope of generating the error and the log, but the installation completed without error this time.

`PS D:\repos\vcpkg> ./vcpkg install opencv3[ffmpeg]:x64-windows
Computing installation plan...
The following packages will be built and installed:
    opencv3[core,dnn,ffmpeg,flann,jpeg,png,quirc,tiff,webp]:x64-windows -> 3.4.13
Warning: The following VS instances are excluded because the English language pack is unavailable.
    C:\Program Files (x86)\Microsoft Visual Studio 14.0
Please install the English language pack.
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\Encoded\AppData\Local\vcpkg\archives\68\683102019646b39d88f1e720165b8159c6be41f3.zip
Starting package 1/1: opencv3:x64-windows
Building package opencv3[core,dnn,ffmpeg,flann,jpeg,png,quirc,tiff,webp]:x64-windows...
-- Using D:/Repos/vcpkg/downloads/opencv-opencv-3.4.13.tar.gz
-- Cleaning sources at D:/Repos/vcpkg/buildtrees/opencv3/src/3.4.13-1d83403e4f.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/Repos/vcpkg/downloads/opencv-opencv-3.4.13.tar.gz
-- Applying patch 0001-disable-downloading.patch
-- Applying patch 0002-install-options.patch
-- Applying patch 0003-force-package-requirements.patch
-- Applying patch 0004-fix-eigen.patch
-- Applying patch 0005-fix-vtk9.patch
-- Applying patch 0006-fix-uwp.patch
-- Applying patch 0008-devendor-quirc.patch
-- Using source at D:/Repos/vcpkg/buildtrees/opencv3/src/3.4.13-1d83403e4f.clean
CMake Deprecation Warning at scripts/cmake/vcpkg_check_features.cmake:182 (message):
  calling `vcpkg_check_features` without the `FEATURES` keyword has been
  deprecated.

      Please add the `FEATURES` keyword to the call.
Call Stack (most recent call first):
  ports/opencv3/portfile.cmake:41 (vcpkg_check_features)
  scripts/ports.cmake:139 (include)


-- Using D:/Repos/vcpkg/downloads/opencv-cache/tiny_dnn/adb1c512e09ca2c7a6faef36f9c53e59-v1.0.0a3.tar.gz
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: D:/Repos/vcpkg/packages/opencv3_x64-windows/share/opencv3/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\Encoded\AppData\Local\vcpkg\archives\68\683102019646b39d88f1e720165b8159c6be41f3.zip
Building package opencv3[core,dnn,ffmpeg,flann,jpeg,png,quirc,tiff,webp]:x64-windows... done
Installing package opencv3[core,dnn,ffmpeg,flann,jpeg,png,quirc,tiff,webp]:x64-windows...
Installing package opencv3[core,dnn,ffmpeg,flann,jpeg,png,quirc,tiff,webp]:x64-windows... done
Elapsed time for package opencv3:x64-windows: 6.989 min

Total elapsed time: 7.102 min

The package opencv3:x64-windows provides CMake targets:

    find_package(OpenCV CONFIG REQUIRED)
    # Note: 13 target(s) were omitted.
    target_link_libraries(main PRIVATE opencv_ml opencv_dnn opencv_core opencv_flann)`

**Comment by JonLiu1993** [comment]
@seccpur ,Thanks for posting this issue,I will close this issue for now, if you have new issue, you can reopen it
