### ISSUE TITLE
vcpkg stuck in manifest mode, refuses to install packages manually

### ISSUE THREAD

**Issue by Be-ing** [microsoft/vcpkg#19387]
**Describe the bug**
I used manifest mode locally as a test for one project. Then I switched back to a branch I was working on for packaging a new port. However when I tried to use `vcpkg install`, I got an error:
```
vcpkg on  libsbsms 
❯ ./vcpkg install libsbsms
Error: 'install' requires 0 arguments, but 1 were provided.
```

I tried re-bootstrapping, deleting the whole vcpkg Git repository and recloning it, `rm -rf ~/.vcpkg ~/.cache/vcpkg`, but none of those worked. I don't know where the broken state is stored or how I can fix it.

**Environment**
- OS: Linux (Fedora 34)
- Compiler: GCC

**To Reproduce**
1. Build a CMake project in manifest mode
2. ./vcpkg install xxxx
2. See error

**Expected behavior**
`vcpkg install` would work.

**Comment by PhoebeHui** [comment]
@Be-ing, since you are in manifest mode, so could you try './vcpkg install' instead? it would install the ports configured in your vcpkg.json file.

**Comment by cenit** [comment]
is there any vcpkg.json file anywhere? that tricks vcpkg into manifest mode..,
