### ISSUE TITLE
[cairo ] build failure

### ISSUE THREAD

**Issue by JohannYellow** [microsoft/vcpkg#19383]
**Host Environment**
- Windows 10 x64
- Compiler: gcc (i686-posix-dwarf-rev0, Built by MinGW-W64 project) 8.1.0

**To Reproduce**
.\vcpkg.exe install cairo --triplet x64-windows

**Failure logs** 
Error: Building package brotli:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: brotli:x64-windows
  Vcpkg version: 2021-08-03-1a6d67b8150e94b7f473c6ab1c0cfdd794316a64

**Additional context**

**Comment by JonLiu1993** [comment]
@JohannYellow ,Thanks for posting this issue,Could you please provide the error log?

**Comment by JohannYellow** [comment]
Hi Jon,
thank you for getting back to me.  I'm relatively new to this so forgive me
for any stupid questions.

If by "error log" you mean the output in Powershell - here is it below:

PS C:\programs\vcpkg>
PS C:\programs\vcpkg> .\vcpkg.exe install cairo --triplet x64-windows
Computing installation plan...
The following packages will be built and installed:
  * brotli[core]:x64-windows -> 1.0.9#1
  * bzip2[core]:x64-windows -> 1.0.8#2
    cairo[core,fontconfig,freetype]:x64-windows -> 1.17.4#2
  * dirent[core]:x64-windows -> 1.23.2
  * expat[core]:x64-windows -> 2.4.1
  * fontconfig[core]:x64-windows -> 2.13.1#7
  * freetype[brotli,bzip2,core,png,zlib]:x64-windows -> 2.10.4
  * gettext[core]:x64-windows -> 0.21#4
  * json-c[core]:x64-windows -> 2019-09-10#1
  * libiconv[core]:x64-windows -> 1.16#9
  * libpng[core]:x64-windows -> 1.6.37#15
  * lzo[core]:x64-windows -> 2.10#6
  * pixman[core]:x64-windows -> 0.40.0
  * pthread[core]:x64-windows -> 3.0.0
  * pthreads[core]:x64-windows -> 3.0.0#10
  * tool-meson[core]:x64-windows -> 0.58.1
  * vcpkg-cmake[core]:x64-windows -> 2021-07-30
  * vcpkg-cmake-config[core]:x64-windows -> 2021-05-22#1
  * zlib[core]:x64-windows -> 1.2.11#11
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
A suitable version of git was not found (required v2.32.0). Downloading
portable git v2.32.0...
Downloading git...

https://github.com/git-for-windows/git/releases/download/v2.32.0.windows.2/PortableGit-2.32.0.2-32-bit.7z.exe
-> C:\programs\vcpkg\downloads\PortableGit-2.32.0.2-32-bit.7z.exe
Extracting git...
A suitable version of 7zip was not found (required v18.1.0). Downloading
portable 7zip v18.1.0...
Downloading 7zip...
  https://www.nuget.org/api/v2/package/7-Zip.CommandLine/18.1.0 ->
C:\programs\vcpkg\downloads\7-zip.commandline.18.1.0.nupkg
Extracting 7zip...
A suitable version of nuget was not found (required v5.10.0). Downloading
portable nuget v5.10.0...
Downloading nuget...
  https://dist.nuget.org/win-x86-commandline/v5.10.0/nuget.exe ->
C:\programs\vcpkg\downloads\c4b7375e-nuget.exe
Could not locate cached archive:
C:\Users\jpk\AppData\Local\vcpkg\archives\72\720dd3a028243458c242d1dd84604de5388452d079e10ae6499761d28d0faf43.zip
Could not locate cached archive:
C:\Users\jpk\AppData\Local\vcpkg\archives\db\db9b9b717979402dc1192e0ecbc6dce8c5cf0636e4cbb91bb1e8d8dab3f77e6b.zip
Could not locate cached archive:
C:\Users\jpk\AppData\Local\vcpkg\archives\12\12f60bc6f5c8fd94321d5ff55324684d14770d468e9bd9c8e460a175f9944ea0.zip
Could not locate cached archive:
C:\Users\jpk\AppData\Local\vcpkg\archives\a6\a61d7514474172a42e942bcbfe51552ac39f93b3e9fd87cbf366d9f4445472e0.zip
Could not locate cached archive:
C:\Users\jpk\AppData\Local\vcpkg\archives\e7\e7a8c2031dafde7f9364a857a1b3480617deabbadcfac1c730888030c0ce391a.zip
Could not locate cached archive:
C:\Users\jpk\AppData\Local\vcpkg\archives\96\968d6612d19a57bb4c6a02c4a290ebbbdb88ea1317f4b768c8494afcb819cd99.zip
Could not locate cached archive:
C:\Users\jpk\AppData\Local\vcpkg\archives\3b\3b134f57f8d94b923a9726dc51a65b79665e83a3bcbf36f82046e7d40290caa1.zip
Could not locate cached archive:
C:\Users\jpk\AppData\Local\vcpkg\archives\d4\d416a35d6b72baedfe5fed0fe7c178d6a869fdce8972fe60beb4283f0cf15592.zip
Could not locate cached archive:
C:\Users\jpk\AppData\Local\vcpkg\archives\db\db533c7f88de93ac474b898d296438f9baef76a4f12ab02769e258aa4ce439b7.zip
Could not locate cached archive:
C:\Users\jpk\AppData\Local\vcpkg\archives\49\49454a6911cc846bcd6a81cfe830e3a12da03156f6a2c132172e9c4b466b3e0f.zip
Could not locate cached archive:
C:\Users\jpk\AppData\Local\vcpkg\archives\26\2689f7283772ff8ffb7ce64f3730aa71681704de6884eba719cc2f10813f9e6c.zip
Could not locate cached archive:
C:\Users\jpk\AppData\Local\vcpkg\archives\c3\c35f77e892e8594207859f45b16da1fe69ee0c8f7f95dcdd2146ed1e8941186c.zip
Could not locate cached archive:
C:\Users\jpk\AppData\Local\vcpkg\archives\b0\b0817d35dfba6413c9dbd62d837e6f92b3ca9dea4a7d4dc451ffeace0c09c9ea.zip
Could not locate cached archive:
C:\Users\jpk\AppData\Local\vcpkg\archives\3a\3a38c2e7c5b6c16e8ba421639420482aff8745252e5fb232303dbcfba7fc1e35.zip
Could not locate cached archive:
C:\Users\jpk\AppData\Local\vcpkg\archives\f7\f74786026d8d5d7561b677b9dec8e33ecdc7b5258d321797fa333a697fcf0695.zip
Could not locate cached archive:
C:\Users\jpk\AppData\Local\vcpkg\archives\85\853782459eecdd10a5af9cbea85369f56daf59d60c2d12d29b9e106640908ed1.zip
Could not locate cached archive:
C:\Users\jpk\AppData\Local\vcpkg\archives\ec\ecf599f044889dfcaf2371a117d2b38455a2e75f96605266c63efce7d69c96c6.zip
Could not locate cached archive:
C:\Users\jpk\AppData\Local\vcpkg\archives\30\308d0c6ae68b4a6c985fd97085c2eeb9bf5b7662dddc8f6e76059f0a1c83af5e.zip
Could not locate cached archive:
C:\Users\jpk\AppData\Local\vcpkg\archives\da\dab99a4729d1a5f245d3d13bb8c545067340cf828e78d684cbeabd7da1c54acb.zip
Starting package 1/19: brotli:x64-windows
Building package brotli[core]:x64-windows...
-- Downloading
https://github.com/google/brotli/archive/e61745a6b7add50d380cfd7d3883dd6c62fc2c71.tar.gz
-> google-brotli-e61745a6b7add50d380cfd7d3883dd6c62fc2c71.tar.gz...
-- Extracting source
C:/programs/vcpkg/downloads/google-brotli-e61745a6b7add50d380cfd7d3883dd6c62fc2c71.tar.gz
-- Applying patch install.patch
-- Applying patch fix-arm-uwp.patch
-- Applying patch pkgconfig.patch
-- Applying patch fix-ios.patch
-- Using source at
C:/programs/vcpkg/buildtrees/brotli/src/6c62fc2c71-7c6c2710e9.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
CMake Warning at scripts/cmake/vcpkg_copy_pdbs.cmake:70 (message):
  Could not find a matching pdb file for:

Call Stack (most recent call first):
  ports/brotli/portfile.cmake:22 (vcpkg_copy_pdbs)
  scripts/ports.cmake:141 (include)

CMake Error at scripts/cmake/vcpkg_copy_tool_dependencies.cmake:44
(message):
  Could not find PowerShell Core; please open an issue to report this.
Call Stack (most recent call first):
  ports/brotli/portfile.cmake:24 (vcpkg_copy_tool_dependencies)
  scripts/ports.cmake:141 (include)

Error: Building package brotli:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: brotli:x64-windows
  Vcpkg version: 2021-08-03-1a6d67b8150e94b7f473c6ab1c0cfdd794316a64

Additionally, attach any relevant sections from the log files above.
PS C:\programs\vcpkg>
PS C:\programs\vcpkg>
PS C:\programs\vcpkg>
PS C:\programs\vcpkg>

regards
Johann Kok

**Comment by JonLiu1993** [comment]
Hi @JohannYellow .

Seems duplicated of #15681, let's track this issue there.
