### ISSUE TITLE
[boost-exception]msvc.write-setup-script C:\Program Files\CMake\vcpkg\buildtrees\boost-exception\x86-windows-rel\boost\standalone\msvc\4c43e23ab5ea979f4503513265cfdf27\msvc-setup.bat The system cannot find the path specified.

### ISSUE THREAD

**Issue by NekoooooOoi** [microsoft/vcpkg#19382]
**Host Environment**
- OS: Windows
- Compiler: Visual Studio 2019

**To Reproduce**
`./vcpkg install boost`

**Failure logs** 
Could not locate cached archive: C:\Users\王峥宇\AppData\Local\vcpkg\archives\32\32369fe7853f9a1cd2d89b75a6daeabf91e40231ea379bb4e8d2f2deea89af5d.zip
Could not locate cached archive: C:\Users\王峥宇\AppData\Local\vcpkg\archives\03\036c991f79315d3fbcb90856c81b2fc9c95cd3b407e70c104923ad1201612667.zip
Could not locate cached archive: C:\Users\王峥宇\AppData\Local\vcpkg\archives\53\5342f375fbb1eff7a1753936910bef4832a375b8db3ea20516670f9918d4816e.zip
Could not locate cached archive: C:\Users\王峥宇\AppData\Local\vcpkg\archives\8e\8e03fe90945347105b375b1263e0d1895f95bb9cb8c4939303fc8d0c6a873898.zip
Could not locate cached archive: C:\Users\王峥宇\AppData\Local\vcpkg\archives\e7\e77a486b8db0c1e21cf961b1c9d63e58e953036d9ca9d9b8420a4de8998ba8e0.zip
Could not locate cached archive: C:\Users\王峥宇\AppData\Local\vcpkg\archives\03\03f790810bfe74ff9e22ca1435d631b92fefbf6d5612cc2a83de0f1e12532175.zip
Starting package 1/69: boost-exception:x86-windows
Building package boost-exception[core]:x86-windows...
-- Using C:/Program Files/CMake/vcpkg/downloads/boostorg-exception-boost-1.76.0.tar.gz
-- Cleaning sources at C:/Program Files/CMake/vcpkg/buildtrees/boost-exception/src/ost-1.76.0-5e68eb1a52.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Program Files/CMake/vcpkg/downloads/boostorg-exception-boost-1.76.0.tar.gz
-- Using source at C:/Program Files/CMake/vcpkg/buildtrees/boost-exception/src/ost-1.76.0-5e68eb1a52.clean
-- Building x86-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: "C:/Program Files/CMake/vcpkg/installed/x64-windows/tools/boost-build/b2.exe" "--stagedir=C:/Program Files/CMake/vcpkg/buildtrees/boost-exception/x86-windows-rel/stage" "--build-dir=C:/Program Files/CMake/vcpkg/buildtrees/boost-exception/x86-windows-rel" "--user-config=C:/Program Files/CMake/vcpkg/buildtrees/boost-exception/x86-windows-rel/user-config.jam" -j16 --debug-configuration --debug-building --debug-generators --disable-icu --ignore-site-config --hash -q "-sZLIB_INCLUDE=C:/Program Files/CMake/vcpkg/installed/x86-windows/include" "-sBZIP2_INCLUDE=C:/Program Files/CMake/vcpkg/installed/x86-windows/include" "-sLZMA_INCLUDE=C:/Program Files/CMake/vcpkg/installed/x86-windows/include" "-sZSTD_INCLUDE=C:/Program Files/CMake/vcpkg/installed/x86-windows/include" threading=multi threadapi=win32 runtime-link=shared link=shared address-model=32 architecture=x86 asmflags=/safeseh -sZLIB_BINARY=zlib "-sZLIB_LIBPATH=C:/Program Files/CMake/vcpkg/installed/x86-windows/lib" -sBZIP2_BINARY=bz2 "-sBZIP2_LIBPATH=C:/Program Files/CMake/vcpkg/installed/x86-windows/lib" -sLZMA_BINARY=lzma "-sLZMA_LIBPATH=C:/Program Files/CMake/vcpkg/installed/x86-windows/lib" -sZSTD_BINARY=zstd "-sZSTD_LIBPATH=C:/Program Files/CMake/vcpkg/installed/x86-windows/lib" variant=release debug-symbols=on
    Working Directory: C:/Program Files/CMake/vcpkg/buildtrees/boost-exception/src/ost-1.76.0-5e68eb1a52.clean/build
    Error code: 1
    See logs for more information:
      C:\Program Files\CMake\vcpkg\buildtrees\boost-exception\build-x86-windows-rel-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/boost-build/boost-modular-build.cmake:336 (vcpkg_execute_required_process)
  ports/boost-exception/portfile.cmake:15 (boost_modular_build)
  scripts/ports.cmake:141 (include)

Error: Building package boost-exception:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-exception:x86-windows
  Vcpkg version: 2021-08-03-1a6d67b8150e94b7f473c6ab1c0cfdd794316a64

Additionally, attach any relevant sections from the log files above.

**Additional context**
         returned [ <relevant>address-model <relevant>architecture <relevant>archiveflags <relevant>asynch-exceptions <relevant>cflags <relevant>cxxflags <relevant>cxxstd <relevant>debug-store <relevant>debug-symbols <relevant>define <relevant>exception-handling <relevant>extern-c-nothrow <relevant>force-include <relevant>include <relevant>inlining <relevant>instruction-set <relevant>link <relevant>lto <relevant>mc-input-encoding <relevant>mc-output-encoding <relevant>mc-set-customer-bit <relevant>optimization <relevant>pch <relevant>pch-file <relevant>pch-header <relevant>pch-source <relevant>rtti <relevant>runtime-debugging <relevant>runtime-link <relevant>threading <relevant>toolset <relevant>toolset-msvc:version <relevant>undef <relevant>user-interface <relevant>warnings <relevant>warnings-as-errors <relevant>windows-api ] { msvc%msvc.archive-libboost_exception-vc142-mt-x32-1_76.lib.STATIC_LIB { msvc%msvc.compile.c++-clone_current_exception_non_intrusive.obj.OBJ { clone_current_exception_non_intrusive.cpp.CPP } } }
           generator msvc.archive  spawned 
           { msvc%msvc.archive-libboost_exception-vc142-mt-x32-1_76.lib.STATIC_LIB { msvc%msvc.compile.c++-clone_current_exception_non_intrusive.obj.OBJ { clone_current_exception_non_intrusive.cpp.CPP } } }
           with usage requirements: [ <relevant>address-model <relevant>architecture <relevant>archiveflags <relevant>asynch-exceptions <relevant>cflags <relevant>cxxflags <relevant>cxxstd <relevant>debug-store <relevant>debug-symbols <relevant>define <relevant>exception-handling <relevant>extern-c-nothrow <relevant>force-include <relevant>include <relevant>inlining <relevant>instruction-set <relevant>link <relevant>lto <relevant>mc-input-encoding <relevant>mc-output-encoding <relevant>mc-set-customer-bit <relevant>optimization <relevant>pch <relevant>pch-file <relevant>pch-header <relevant>pch-source <relevant>rtti <relevant>runtime-debugging <relevant>runtime-link <relevant>threading <relevant>toolset <relevant>toolset-msvc:version <relevant>undef <relevant>user-interface <relevant>warnings <relevant>warnings-as-errors <relevant>windows-api ]
     returned [ <relevant>address-model <relevant>architecture <relevant>archiveflags <relevant>asynch-exceptions <relevant>cflags <relevant>cxxflags <relevant>cxxstd <relevant>debug-store <relevant>debug-symbols <relevant>define <relevant>exception-handling <relevant>extern-c-nothrow <relevant>force-include <relevant>include <relevant>inlining <relevant>instruction-set <relevant>link <relevant>lto <relevant>mc-input-encoding <relevant>mc-output-encoding <relevant>mc-set-customer-bit <relevant>optimization <relevant>pch <relevant>pch-file <relevant>pch-header <relevant>pch-source <relevant>rtti <relevant>runtime-debugging <relevant>runtime-link <relevant>threading <relevant>toolset <relevant>toolset-msvc:version <relevant>undef <relevant>user-interface <relevant>warnings <relevant>warnings-as-errors <relevant>windows-api ] { msvc%msvc.archive-libboost_exception-vc142-mt-x32-1_76.lib.STATIC_LIB { msvc%msvc.compile.c++-clone_current_exception_non_intrusive.obj.OBJ { clone_current_exception_non_intrusive.cpp.CPP } } }
       generator builtin.lib-generator  spawned 
       { msvc%msvc.archive-libboost_exception-vc142-mt-x32-1_76.lib.STATIC_LIB { msvc%msvc.compile.c++-clone_current_exception_non_intrusive.obj.OBJ { clone_current_exception_non_intrusive.cpp.CPP } } }
       with usage requirements: [ <relevant>address-model <relevant>architecture <relevant>archiveflags <relevant>asynch-exceptions <relevant>cflags <relevant>cxxflags <relevant>cxxstd <relevant>debug-store <relevant>debug-symbols <relevant>define <relevant>exception-handling <relevant>extern-c-nothrow <relevant>force-include <relevant>include <relevant>inlining <relevant>instruction-set <relevant>link <relevant>lto <relevant>mc-input-encoding <relevant>mc-output-encoding <relevant>mc-set-customer-bit <relevant>optimization <relevant>pch <relevant>pch-file <relevant>pch-header <relevant>pch-source <relevant>rtti <relevant>runtime-debugging <relevant>runtime-link <relevant>threading <relevant>toolset <relevant>toolset-msvc:version <relevant>undef <relevant>user-interface <relevant>warnings <relevant>warnings-as-errors <relevant>windows-api ]
             Usage requirements from boost_exception:  <relevant>address-model <relevant>architecture <relevant>asynch-exceptions <relevant>cxxstd <relevant>cxxstd-dialect <relevant>debug-store <relevant>debug-symbols <relevant>deduced-address-model <relevant>deduced-architecture <relevant>exception-handling <relevant>extern-c-nothrow <relevant>inlining <relevant>instruction-set <relevant>link <relevant>lto <relevant>lto-mode <relevant>optimization <relevant>pch <relevant>rtti <relevant>runtime-debugging <relevant>runtime-link <relevant>segmented-stacks <relevant>threading <relevant>toolset <relevant>toolset-msvc:vendor <relevant>toolset-msvc:version <relevant>variant <relevant>warnings <relevant>warnings-as-errors <relevant>windows-api

         Usage requirements for stage:  <relevant>address-model <relevant>architecture <relevant>asynch-exceptions <relevant>cxxstd <relevant>cxxstd-dialect <relevant>debug-store <relevant>debug-symbols <relevant>deduced-address-model <relevant>deduced-architecture <relevant>exception-handling <relevant>extern-c-nothrow <relevant>inlining <relevant>instruction-set <relevant>link <relevant>lto <relevant>lto-mode <relevant>optimization <relevant>pch <relevant>rtti <relevant>runtime-debugging <relevant>runtime-link <relevant>segmented-stacks <relevant>threading <relevant>toolset <relevant>toolset-msvc:vendor <relevant>toolset-msvc:version <relevant>variant <relevant>warnings <relevant>warnings-as-errors <relevant>windows-api
         Build properties:  <address-model>32 <architecture>x86 <asmflags>/safeseh <asynch-exceptions>off <coverage>off <debug-store>object <debug-symbols>on <define>BOOST_ALL_NO_LIB=1 <define>NDEBUG <embed-manifest-via>linker <embed-manifest>on <exception-handling>on <extern-c-nothrow>off <hardcode-dll-paths>false <host-os>windows <include>../include&&/C:/Program Files/CMake/vcpkg/installed/x86-windows/include <inlining>full <install-dependencies>off <link>static <location>/C:/Program Files/CMake/vcpkg/buildtrees/boost-exception/x86-windows-rel/stage/lib <midl-robust>yes <midl-stubless-proxy>yes <optimization>speed <os>NT <pch>on <profiling>off <relevant>address-model <relevant>architecture <relevant>asynch-exceptions <relevant>cxxstd <relevant>cxxstd-dialect <relevant>debug-store <relevant>debug-symbols <relevant>deduced-address-model <relevant>deduced-architecture <relevant>exception-handling <relevant>extern-c-nothrow <relevant>inlining <relevant>instruction-set <relevant>link <relevant>lto <relevant>lto-mode <relevant>optimization <relevant>pch <relevant>rtti <relevant>runtime-debugging <relevant>runtime-link <relevant>segmented-stacks <relevant>threading <relevant>threading:<relevant>runtime-link <relevant>threading:<relevant>toolset <relevant>toolset <relevant>toolset-msvc:vendor <relevant>toolset-msvc:version <relevant>variant <relevant>warnings <relevant>warnings-as-errors <relevant>windows-api <rtti>on <runtime-debugging>off <runtime-link>shared <stdlib>native <strip>off <suppress-import-lib>false <symlink-location>project-relative <tag>@Jamfile<C:\Program Files\CMake\vcpkg\buildtrees\boost-exception\src\ost-1.76.0-5e68eb1a52.clean>%Jamfile<C:\Program Files\CMake\vcpkg\buildtrees\boost-exception\src\ost-1.76.0-5e68eb1a52.clean>.tag <target-os>windows <threadapi>win32 <threading>multi <toolset-msvc:version>14.2 <toolset>msvc <translate-path>@Jamfile<C:\Program Files\CMake\vcpkg\buildtrees\boost-exception\src\ost-1.76.0-5e68eb1a52.clean\build>%Jamfile<C:\Program Files\CMake\vcpkg\buildtrees\boost-exception\src\ost-1.76.0-5e68eb1a52.clean\build>.stage-translate-path <user-interface>console <variant>release <vectorize>off <warnings-as-errors>off <warnings>on <windows-api>desktop
         Usage requirements from stage:  <relevant>address-model <relevant>architecture <relevant>asynch-exceptions <relevant>cxxstd <relevant>cxxstd-dialect <relevant>debug-store <relevant>debug-symbols <relevant>deduced-address-model <relevant>deduced-architecture <relevant>exception-handling <relevant>extern-c-nothrow <relevant>inlining <relevant>instruction-set <relevant>link <relevant>lto <relevant>lto-mode <relevant>optimization <relevant>pch <relevant>rtti <relevant>runtime-debugging <relevant>runtime-link <relevant>segmented-stacks <relevant>threading <relevant>toolset <relevant>toolset-msvc:vendor <relevant>toolset-msvc:version <relevant>variant <relevant>warnings <relevant>warnings-as-errors <relevant>windows-api
...patience...
...found 263 targets...
...updating 12 targets...
msvc.write-setup-script C:\Program Files\CMake\vcpkg\buildtrees\boost-exception\x86-windows-rel\boost\standalone\msvc\4c43e23ab5ea979f4503513265cfdf27\msvc-setup.bat
The system cannot find the path specified.

    type "C:\Users\王峥宇\AppData\Local\Temp\jam22f0d537.000" > "C:\Program Files\CMake\vcpkg\buildtrees\boost-exception\x86-windows-rel\boost\standalone\msvc\4c43e23ab5ea979f4503513265cfdf27\msvc-setup.bat"

...failed msvc.write-setup-script C:\Program Files\CMake\vcpkg\buildtrees\boost-exception\x86-windows-rel\boost\standalone\msvc\4c43e23ab5ea979f4503513265cfdf27\msvc-setup.bat...
...removing C:\Program Files\CMake\vcpkg\buildtrees\boost-exception\x86-windows-rel\boost\standalone\msvc\4c43e23ab5ea979f4503513265cfdf27\msvc-setup.bat
...skipped <pC:\Program Files\CMake\vcpkg\buildtrees\boost-exception\x86-windows-rel\boost\build\a27be6bd2649072a1cc0b6aeca86b2f1>clone_current_exception_non_intrusive.obj for lack of <pC:\Program Files\CMake\vcpkg\buildtrees\boost-exception\x86-windows-rel\boost\standalone\msvc\4c43e23ab5ea979f4503513265cfdf27>msvc-setup.nup...
...failed updating 1 target...
...skipped 1 target...
...updated 9 targets...

**Comment by NekoooooOoi** [comment]
I've already read the issue at 'https://github.com/microsoft/vcpkg/issues/14154', and I've tried some of the solutions suggested by @PhoebeHui  like installing the boost-build by 'vcpkg install boost-build' and install English language package. However, they didn't work.

**Comment by NekoooooOoi** [comment]
Also, I've tried to  exit my anti-virus software, it didn't work either....

**Comment by PhoebeHui** [comment]
@NekoooooOoi, the Chinese characters cause this issue, see https://github.com/microsoft/vcpkg/issues/15201#issuecomment-750804866.


Duplicated to https://github.com/microsoft/vcpkg/issues/15201.

**Comment by NekoooooOoi** [comment]
@PhoebeHui It works! Thanks for your help.
