### ISSUE TITLE
How do I use Catch::Catch2WithMain ?

### ISSUE THREAD

**Issue by InfRandomness** [microsoft/vcpkg#19388]
I was checking the catch2's documentation about their cmake integration (https://github.com/catchorg/Catch2/blob/devel/docs/cmake-integration.md#cmake-targets);

They seem to advise people who don't need a custom main() function to use Catch2::Catch2WithMain, so that's what I went with. 
Only, I seem to have troubles with trying to do so when using catch2 through vcpkg,
my configuration is : 
```
# Tests
find_package(Catch2 CONFIG REQUIRED)
add_executable(tests "src/Test.cxx")
target_link_libraries(tests PRIVATE Catch2::Catch2WithMain)
```

and cmake tells me 
```
CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:534 (_add_executable):
  Target "tests" links to target "Catch2::Catch2WithMain" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
```

However, using Catch2::Catch2 works fine.

Is there a way to use Catch2::Catch2WithMain ?

**Comment by NancyLi1013** [comment]
Hi @InfRandomness 

Thanks for posting this issue.

Currently, there is no `Catch2WithMain` provided in vcpkg. As you can see here:
https://github.com/catchorg/Catch2/blob/v2.13.6/CMakeLists.txt#L109

`Catch2WithMain `is generated only in static build. We need to support this.

**Comment by InfRandomness** [comment]
This still doesn't appear to work, not sure why

I have the same code as before, I tried to remove both my out dir and my vcpkg dir

**Comment by NancyLi1013** [comment]
@InfRandomness 

Have you installed `catch2:x64-windows-static`? And please also set `CMAKE_TOOLCHAIN_FILE `and `VCPKG_TARGET_TRIPLET` when you build your project.

Please post the error info if you still cannot build successfully.

**Comment by NancyLi1013** [comment]
Yes, you can do that with manifest.

**Comment by NancyLi1013** [comment]
Please refer to this [doc](https://github.com/microsoft/vcpkg/blob/master/docs/specifications/manifests.md#example---cmake-integration) to get the information how to use manifest.

**Comment by InfRandomness** [comment]
I've tried 
```
  "dependencies": [
    {
      "name": "catch2",
      "platform": "(windows & static)"
    }

```
and
```
  "dependencies": [
    {
      "name": "catch2",
      "platform": "static"
    }
```
both didn't work, I'm not sure how to do it if this doesn't work

**Comment by NancyLi1013** [comment]
Thanks for your feedback. I will try this on my machine.

**Comment by NancyLi1013** [comment]
Hi @InfRandomness 

I use the following project to build, it work fine for me.

vcpkg.josn:

```
{
  "name": "test",
  "version-string": "0.0.1",
  "dependencies": [
  {
    "name": "catch2",
    "platform": "windows & static"
  }
  ]
}

```
CMakeLists.txt:
```

cmake_minimum_required (VERSION 3.8)

project(test)

# Add source to this project's executable.
add_executable (test "main.cpp")

find_package(Catch2 CONFIG REQUIRED)

target_link_libraries(test PRIVATE Catch2::Catch2WithMain)

```
main.cpp
```
#include <catch.hpp>
#include <catch2/catch.hpp>

int main()
{
    return 0;
}
```

**Comment by NancyLi1013** [comment]
The command I used to build:

`cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_TOOLCHAIN_FILE=vcpkg_root\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static`

Please help confirm if you pass `-DVCPKG_TARGET_TRIPLET=x64-windows-static`. 

Please post the details if you still have the problem.
