### ISSUE TITLE
[New Port Request] libserialport

### ISSUE THREAD

**Issue by jayvdb** [microsoft/vcpkg#19390]
Library name: libserialport

Library description: libserialport is a minimal, cross-platform shared library written in C that is intended to take care of the OS-specific details when writing software that uses serial ports.

It is widely available in *nux distros; c.f https://repology.org/project/libserialport/versions 

Source repository URL: git://sigrok.org/libserialport

Project homepage (if different from the source repository): https://sigrok.org/wiki/Libserialport

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
