### ISSUE TITLE
add command to download sources without installing

### ISSUE THREAD

**Issue by Be-ing** [microsoft/vcpkg#19391]
****

**Is your feature request related to a problem? Please describe.**
Many other package managers such as Flatpak and Linux distribution package managers do not provide build machines with network access to prevent tampering with source code. vcpkg could be used in such settings if the sources could be downloaded separately from building them.

This would be nice for packaging Flatpaks for applications which use vcpkg for their own builds upstream. This way packagers could build exactly the same way as upstream does.

**Proposed solution**
A command `vcpkg download [package names]` that would download the source code for packages or the packages specified in a vcpkg.json manifest. Running `vcpkg install` for those packages could then be done without network access.

**Describe alternatives you've considered**
:shrug: not using vcpkg?

**Additional context**
https://github.com/flathub/flathub/pull/2444#issuecomment-890655236

**Comment by autoantwort** [comment]
There is `vcpkg install --only-downloads`

**Comment by Be-ing** [comment]
Oh, hah, I didn't know about that.
