### ISSUE TITLE
tensorflow-cc:x64-windows

### ISSUE THREAD

**Issue by HoLue** [microsoft/vcpkg#19395]
[msys-pacman-x64-windows-err.log](https://github.com/microsoft/vcpkg/files/6944024/msys-pacman-x64-windows-err.log)
[msys-pacman-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/6944025/msys-pacman-x64-windows-out.log)
**Host Environment**
- Windows 10
- Compiler: ?
Microsoft Visual Studio Community 2019
Version 16.10.1
VisualStudio.16.Release/16.10.1+31402.337
Microsoft .NET Framework
Version 4.8.04084
Visual C++ 2019   00435-60000-00000-AA952
Microsoft Visual C++ 2019

**To Reproduce**
.\vcpkg install tensorflow-cc:x64-windows

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
Computing installation plan...
The following packages will be built and installed:
    tensorflow-cc[core]:x64-windows
Starting package 1/1: tensorflow-cc:x64-windows
Building package tensorflow-cc[core]:x64-windows...
CMake Warning at ports/tensorflow-cc/portfile.cmake:3 (message):
  This tensorflow port currently is experimental on Windows and Linux
  platforms.
Call Stack (most recent call first):
  scripts/ports.cmake:90 (include)

-- Using cached D:/Di/Libraries/VS/vcpkg/downloads/tensorflow-tensorflow-v1.14.0.tar.gz
-- Using source at D:/Di/Libraries/VS/vcpkg/buildtrees/tensorflow-cc/src/v1.14.0-62c7aa4bd8
-- Acquiring MSYS Packages...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: D:/Di/Libraries/VS/vcpkg/downloads/tools/msys2/msys64/usr/bin/bash.exe --noprofile --norc -c "pacman -Sy --noconfirm --needed unzip patch diffutils git"
    Working Directory: D:/Di/Libraries/VS/vcpkg/downloads/tools/msys2
    Error code: 1
    See logs for more information:
      D:\Di\Libraries\VS\vcpkg\buildtrees\tensorflow-cc\msys-pacman-x64-windows-out.log
      D:\Di\Libraries\VS\vcpkg\buildtrees\tensorflow-cc\msys-pacman-x64-windows-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_acquire_msys.cmake:106 (vcpkg_execute_required_process)
  ports/tensorflow-cc/portfile.cmake:46 (vcpkg_acquire_msys)
  scripts/ports.cmake:90 (include)

-> Then nothing happens anymore! No cursor comes...

-Please attach any additional failure logs mentioned in the console output.
msys-pacman-x64-windows-out.log:
:: Synchronizing package databases...
downloading mingw32.db...
downloading mingw32.db.sig...
downloading mingw64.db...
downloading mingw64.db.sig...
downloading msys.db...
downloading msys.db.sig... 

error: mingw32: key "5F944B027F7FE2091985AA2EFA11531AA0AA7F57" is unknown
error: key "5F944B027F7FE2091985AA2EFA11531AA0AA7F57" could not be looked up remotely
error: mingw64: key "5F944B027F7FE2091985AA2EFA11531AA0AA7F57" is unknown
error: key "5F944B027F7FE2091985AA2EFA11531AA0AA7F57" could not be looked up remotely
error: msys: key "5F944B027F7FE2091985AA2EFA11531AA0AA7F57" is unknown
error: key "5F944B027F7FE2091985AA2EFA11531AA0AA7F57" could not be looked up remotely
error: mingw32: key "5F944B027F7FE2091985AA2EFA11531AA0AA7F57" is unknown
error: key "5F944B027F7FE2091985AA2EFA11531AA0AA7F57" could not be looked up remotely
error: failed to update mingw32 (invalid or corrupted database (PGP signature))
error: mingw64: key "5F944B027F7FE2091985AA2EFA11531AA0AA7F57" is unknown
error: key "5F944B027F7FE2091985AA2EFA11531AA0AA7F57" could not be looked up remotely
error: failed to update mingw64 (invalid or corrupted database (PGP signature))
error: msys: key "5F944B027F7FE2091985AA2EFA11531AA0AA7F57" is unknown
error: key "5F944B027F7FE2091985AA2EFA11531AA0AA7F57" could not be looked up remotely
error: failed to update msys (invalid or corrupted database (PGP signature))
error: failed to synchronize all databases 

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by jgehw** [comment]
> -- Using cached D:/Di/Libraries/VS/vcpkg/downloads/tensorflow-tensorflow-v1.14.0.tar.gz

You're using **very** outdated vcpkg (must be older than Nov 2020 because tensorflow was upgraded to 2.x via #13028). Apparently third party dependencies aren't available for download any longer for this ancient tensorflow port version.  Current tensorflow port version is 2.4.1. Please update vcpkg.

**Comment by HoLue** [comment]
Thanks! But how can I upgrade vcpkg?

**Comment by JonLiu1993** [comment]
@HoLue ,Please recreate a folder and clone vcpkg and try again.thanks

**Comment by HoLue** [comment]
Thanks, this worked!
