### ISSUE TITLE
Error when running bootstrap-vcpkg.bat: Exception calling "Join" with "2" argument(s) (Value cannot be null)

### ISSUE THREAD

**Issue by JesseTG** [Microsoft/vcpkg#1940]
When I run `bootstrap-vcpkg.bat` (on either CMD or Powershell), I get this error.

```
PS C:\Users\Administrator\code\vcpkg> .\bootstrap-vcpkg.bat
C:\Users\Administrator\Code\vcpkg\scripts\findAnyMSBuildWithCppPlatformToolset.ps1 : Exception calling "Join" with "2"
argument(s): "Value cannot be null.
Parameter name: values"
At C:\Users\Administrator\Code\vcpkg\scripts\bootstrap.ps1:41 char:38
+ ... tformToolset = & $scriptsDir\findAnyMSBuildWithCppPlatformToolset.ps1
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [findAnyMSBuildWithCppPlatformToolset.ps1], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentNullException,findAnyMSBuildWithCppPlatformToolset.ps1

PS C:\Users\Administrator\code\vcpkg>
```
This happens on [the latest commit](https://github.com/Microsoft/vcpkg/commit/1fb5313a881fe0fcfd90dff5255045c8367ee00b) as of this moment, on Windows Server 2016.

**Comment by JesseTG** [comment]
Ah, one possibility; as I was running this, I was (and still am, in fact) in the middle of upgrading the Visual Studio build tools.

**Comment by JesseTG** [comment]
No, no luck.  I have no idea what's going on.

**Comment by JesseTG** [comment]
Ah!  It looks like [this](https://github.com/Microsoft/vcpkg/commit/f0c23aeb6b238ee0ba2dc272ee4c193f2f777460) is the offending commit.  Ideas, @alexkaratarakis ?

**Comment by alexkaratarakis** [comment]
Can you try running `.\scripts\findVisualStudioInstallationInstances.ps1` and paste the output?
Also, do you have only the Visual C++ Build Tools installed without Visual Studio? If so, I suspect that's where the bug lies.

**Comment by JesseTG** [comment]
> Can you try running `.\scripts\findVisualStudioInstallationInstances.ps1` and paste the output?

Sure, gimme a few minutes.

> Also, do you have only the Visual C++ Build Tools installed without Visual Studio? If so, I suspect that's where the bug lies.

I only have the build tools, not the IDE.  I'll try installing it after running that script.

**Comment by alexkaratarakis** [comment]
@JesseTG 
If you haven't installed it yet: don't, the intention is that you shouldn't have to so I will make the changes necessary to make it work in your case.

Also, the script is run as part of bootstrap, so it did not modify your system in any way.

Investigating the BuildTools issue..

**Comment by JesseTG** [comment]
Thank you very much.

> Also, the script is run as part of bootstrap, so it did not modify your system in any way.
Never thought that it would, but thanks for letting me know.

**Comment by alexkaratarakis** [comment]
Should work in latest master! (after ab7a1abc93473dc1b7fcb341a4d104e3a77afd87)
Please try and let me know : )

**Comment by JesseTG** [comment]
Okay, we're in business!  Thank you very much!
