### ISSUE TITLE
librsvg - cmake module debug mode appends a suffix

### ISSUE THREAD

**Issue by Baklap4** [microsoft/vcpkg#19416]
I'm trying to get a native Windows build working in which we depend on `librsvg-2`. It's correctly installed through [vcpkg](https://github.com/microsoft/vcpkg). We usually build with cmake and have made a custom module to find this library. This works great in the unix world, but not within Windows and targeting either a Debug build or a Release build (from visual studio). This is due to the fact the actual lib file gets suffixed with a `d` on Windows.

This is our `FindLibRSVG.cmake`
```
include(LibFindMacros)
libfind_package(LibRSVG Cairo)
libfind_package(LibRSVG GDK-PixBuf)
libfind_pkg_detect(LibRSVG librsvg-2.0
  FIND_PATH librsvg/rsvg.h PATH_SUFFIXES librsvg-2 librsvg-2.0
  FIND_LIBRARY rsvg-2
)
libfind_process(LibRSVG)
```

To get the build working on Windows i have to specify a flag to our cmake command like this: 

```
cmake .. -DLibRSVG_LIBRARY=./vcpkg_installed/x64-windows/debug/lib/rsvg-2.40d.lib
```
Do note the `d` at the end of the library.

I know there is a cmake module [`SelectLibraryConfigurations`](https://github.com/Kitware/CMake/blob/master/Modules/SelectLibraryConfigurations.cmake) available but i'm not quite sure how to use this properly.

What i'd like to achieve is to be able to build in debug mode without having to provide this flag.

Note: The [`LibFindMacros` implementation can be found here](https://github.com/Tronic/cmake-modules/blob/master/LibFindMacros.cmake)

**Comment by PhoebeHui** [comment]
@Baklap4, thanks reporting this issue! I have submitted a PR to fix this issue.

**Comment by Baklap4** [comment]
@PhoebeHui PR is looking good and it seems to resolve my problem after changing my FindLibRSVG cmake to
```
include(LibFindMacros)
libfind_package(LibRSVG Cairo)
libfind_package(LibRSVG GDK-PixBuf)
libfind_pkg_detect(LibRSVG librsvg-2.0
  FIND_PATH librsvg/rsvg.h PATH_SUFFIXES librsvg-2 librsvg-2.0 librsvg-2.40
  FIND_LIBRARY rsvg-2 rsvg-2.0 rsvg-2.40
)
libfind_process(LibRSVG)
```
