### ISSUE TITLE
ARM/x64 macOS universal binary triplet

### ISSUE THREAD

**Issue by Be-ing** [microsoft/vcpkg#19431]
****

**Is your feature request related to a problem? Please describe.**
Apple has switched CPU architectures again, this time to ARM.

**Proposed solution**
Add a new triplet arm64-x64-osx (or some similar name) for ARM/x64 universal binaries

**Describe alternatives you've considered**
Make separate builds for x64-osx and arm64-osx

**Additional context**
https://cmake.org/cmake/help/latest/variable/CMAKE_OSX_ARCHITECTURES.html

**Comment by JackBoosY** [comment]
Yes, we are planing to do that.
