### ISSUE TITLE
[New Port Request] jerryscript

### ISSUE THREAD

**Issue by heretic13** [microsoft/vcpkg#19432]
Library name:
jerryscript

Library description:
JerryScript is a lightweight JavaScript engine for resource-constrained devices such as microcontrollers.

Source repository URL:
https://github.com/jerryscript-project/jerryscript
Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
The JERRY_MATH option must be disabled. This option includes its own implementation of sin / cos / abs and others. This is useful for microcontrollers, but not meaningful for a PC platform.

Reasons why this library should be added:
Currently vcpkg supports the following javascript engines: chakracore, duktape, v8.

chakracore - Full support for Esmascript specifications. acceptable size of binaries. But internally it uses wide-strings.

duktape - Esmacript 5 support (6 not supported). Small size of binary files.

v8 - full support for Esmascript specifications, but large binaries.

Jerryscript, in contrast to these libraries, is small in size and supports most of the features of Esmascript 6.

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
