### ISSUE TITLE
option to reduce reproducibility constraints for binary caching

### ISSUE THREAD

**Issue by Be-ing** [microsoft/vcpkg#19442]
**Is your feature request related to a problem? Please describe.**
vcpkg's binary caching features aims for reproducible builds, which is good in general. However it limits the usefulness of the feature. According to https://vcpkg.readthedocs.io/en/latest/users/binarycaching/#implementation-notes-internal-details-subject-to-change-without-notice vcpkg considers all these when calculating a cache key:
```
    Every file in the port directory
    The triplet file and name
    The C++ compiler executable
    The C compiler executable
    The set of features selected
    Every dependency's package hash (note: this is that package's input hash, not contents)
    All helper scripts referenced by portfile.cmake (heuristic)
    The version of CMake used
    The contents of any environment variables listed in VCPKG_ENV_PASSTHROUGH
    The hash of the toolchain file (builtin or VCPKG_CHAINLOAD_TOOLCHAIN_FILE)
```

If the cache is written from CI and a developer tries to read from the cache for local builds, the cache would only hit if the developer's local environment was *exactly* the same as CI. This is not practical in many cases.

**Proposed solution**
An environment variable to exclude the compiler and CMake versions from the cache key hash inputs.

**Describe alternatives you've considered**
Using `vcpkg archive` does not have this issue which is why it is currently being used for Mixxx. That [does not currently work in manifest mode though](https://github.com/microsoft/vcpkg/discussions/17873).

**Additional context**
I tried writing to an Azure Artifacts cache from GitHub Actions and reading from it for local development but vcpkg rebuilt every package.

**Comment by Hoikas** [comment]
microsoft/vcpkg-tool#110

**Comment by Be-ing** [comment]
Closing as duplicate of https://github.com/microsoft/vcpkg/issues/16631
