### ISSUE TITLE
lua[cpp]:x64-uwp build failure

### ISSUE THREAD

**Issue by trojanfoe** [microsoft/vcpkg#19449]
**Host Environment**
- OS: Windows 10 20H2
- Compiler: 19.29.30040

**To Reproduce**
`./vcpkg install lua[cpp]:x64-uwp`

**Failure logs** 
```
    lparser.c
     4>C:\dev\vcpkg\buildtrees\lua\src\lua-5-60afff5bd1.clean\src\lgc.c(720,19): warning C4334: '<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?) [C:\dev\vcpkg\buildtrees\lua\x64-uwp-dbg\lua.vcxproj]
     4>C:\dev\vcpkg\buildtrees\lua\src\lua-5-60afff5bd1.clean\src\lgc.c(739,23): warning C4334: '<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?) [C:\dev\vcpkg\buildtrees\lua\x64-uwp-dbg\lua.vcxproj]
     4>C:\dev\vcpkg\buildtrees\lua\src\lua-5-60afff5bd1.clean\src\liolib.c(286,29): error C3861: '_pclose': identifier not found [C:\dev\vcpkg\buildtrees\lua\x64-uwp-dbg\lua.vcxproj]
         lstate.c
         lstring.c
     4>C:\dev\vcpkg\buildtrees\lua\src\lua-5-60afff5bd1.clean\src\liolib.c(295,10): error C3861: '_popen': identifier not found [C:\dev\vcpkg\buildtrees\lua\x64-uwp-dbg\lua.vcxproj]
```

**Comment by JackBoosY** [comment]
According to [msdn docs](https://docs.microsoft.com/en-us/cpp/cppcx/crt-functions-not-supported-in-universal-windows-platform-apps?view=msvc-160), `_popen` and `_pclose` does not support uwp application, so it's by design.

**Comment by trojanfoe** [comment]
Shouldn't the the lack of support for UWP be flagged at a higher level though, rather than generating a build error?

**Comment by JackBoosY** [comment]
@trojanfoe No, since the upstream uses some uwp-unsupported functions, we can only report error message here.
If you need to use this feature on UWP build, please report this to the upstream.

Thanks.

**Comment by JackBoosY** [comment]
Please keep this issue open until #19510 merge.
