### ISSUE TITLE
[value-ptr-lite] Package config naming differs from package name

### ISSUE THREAD

**Issue by redpandamonium** [microsoft/vcpkg#19448]
**Describe the bug**
When installing the value-ptr-lite package vcpkg suggests the following usage:
```
find_package(value-ptr-lite CONFIG REQUIRED)
target_link_libraries(main PRIVATE nonstd::value_ptr-lite)
```

This results in CMake not being able to find the config, because of a naming conflict. The config is found at `vcpkg_installed/<arch-os>/share/value-ptr-lite/value_ptr-lite-config.cmake` which conflicts with the name of its parent directory (which has the package name). So whichever version you use in find_package, it will not be found.

```
Could not find a package configuration file provided by "value-ptr-lite"
  with any of the following names:

    value-ptr-liteConfig.cmake
    value-ptr-lite-config.cmake
```

```
Could not find a package configuration file provided by "value_ptr-lite"
  with any of the following names:

    value_ptr-liteConfig.cmake
    value_ptr-lite-config.cmake
```

**Environment**
- OS: MacOS 11.5
- Compiler: Apple Clang 12.0.5

**To Reproduce**
1. ./vcpkg install value-ptr-lite
2. Use find_package(value-ptr-lite CONFIG REQUIRED)

**Expected behavior**
There are two possible expected behaviours. The first one is to adjust the usage suggestion. This works, because this is a header-only library.
```
find_path(VALUE_PTR_LITE_INCLUDE_DIRS "nonstd/value_ptr.hpp")
target_include_directories(main PRIVATE ${VALUE_PTR_LITE_INCLUDE_DIRS})
```

Alternatively if the naming conflict between the package name (value-ptr-lite) and the cmake config name (value_ptr-lite-config.cmake) is fixed and the config is found, the original suggestion is true. The config does define the target from the usage suggestion.

**Failure logs** 
none

**Additional context**
none

**Comment by NancyLi1013** [comment]
Hi @redpandamonium 

Thanks for posting this issue. I have submitted a PR #19457 to fix this issue. It should be fine.

**Comment by redpandamonium** [comment]
Thanks! Looks good.
