### ISSUE TITLE
[libgd] update to 2.3.x and later

### ISSUE THREAD

**Issue by pierrejoye** [microsoft/vcpkg#19451]
Library name: libgd

New version number: 2.3.x

Good morning :)

Thanks for the great work here!

We are the libGd teams and finally cleaning up the building scripts to only rely on CMake and autoconf. 

I see that libgd is already in the list of available packages but it seems stuck to 2.2.x. 

What would be the process to add our own registry, anything else than https://devblogs.microsoft.com/cppblog/registries-bring-your-own-libraries-to-vcpkg/ ? Given it is in there already.

We have a task for it https://github.com/libgd/libgd/issues/724

Mainly about missing deps. To see where it fits best (libxpm and libimagequant are not yet on vcpkg).

Thanks,
Pierre

**Comment by JonLiu1993** [comment]
@pierrejoye ,Thanks for posting this issue,you can refer [[New port]](https://github.com/microsoft/vcpkg/pulls?q=is%3Apr+label%3Acategory%3Anew-port+is%3Aclosed) label submit a pr add your registry to vcpkg.

**Comment by PhoebeHui** [comment]
@pierrejoye, we have a PR#20068 to update libgd in vcpkg now. 

> What would be the process to add our own registry, anything else than https://devblogs.microsoft.com/cppblog/registries-bring-your-own-libraries-to-vcpkg/ ? Given it is in there already.

Does this still be a question for you now?

**Comment by pierrejoye** [comment]
Hi

On Thu, Sep 9, 2021, 5:27 PM Phoebe ***@***.***> wrote:

> @pierrejoye <https://github.com/pierrejoye>, we have a PR#20068 to update
> libgd in vcpkg now.
>
> What would be the process to add our own registry, anything else than
> https://devblogs.microsoft.com/cppblog/registries-bring-your-own-libraries-to-vcpkg/
> ? Given it is in there already.
>
> Does this still be a question for you now?
>
if I can help with the PR, please let me know.
I looked at the current patch in the vcpkg libgd:
 - I added the intrinsics header fix on windows already (from current
version)

- I am however not sure what are the use od the cmake changes in the
current patch in vcpkg libgd

I am about to release 2.3.3. I will then look at the process to get libgd
in vcpkg from libgd/libgd directly, if possible, hopefully next release
could be live on both libgd/libgd and vcpkg at the same time :)

**Comment by pierrejoye** [comment]
@PhoebeHui good morning :)

Do I understand correctly that using a registry, users will have to add our registry to use it?

What I am looking for is a way to have the default libgd in vcpkg to use our releases, is it possible?  Or does it have to be done by providing a new PR here on each new release?

**Comment by PhoebeHui** [comment]
@pierrejoye, Registry feature provide a solution for managing your project and dependency conveniently. vcpkg itself is a registry. You can create a registry for using the dependency ports(freetype,tiff, webp..) provided by vcpkg.

Currently we need create new PR in vcpkg for each new release.

Eg: Git registry: users only need create 'vcpkg-configuration.json' and configure it in their projects simply.
Eg: vcpkg-configuration.json:
{
   "registries": [
    {
      "kind": "git",
      "baseline": "94a566bc8ea2706dafe1457cdd0682e09fd00416",
      "repository": "https://github.com/PhoebeHui/vcpkg-registry",
      "packages": [ "beicode"]
    }
  ]
}
