### ISSUE TITLE
How do I need to setup custom registry from private repo

### ISSUE THREAD

**Issue by srgbtl** [microsoft/vcpkg#19467]
I set up a custom registry in a private repo.
In the repo with sources, I added vcpkg-configuration.json to enable using ports from the custom registry.

On local environment it works great: during cmake configure I am prompted to select a credential source and then ports building is proceeded as with public ports.

But in the CI environment configuration fails with the following error:
```
-- Running vcpkg install
Fetching baseline information from https://github.com/private-repo/private-vcpkg-registry...
Error: Couldn't find baseline `"4e1a753b8265dc92e7e4f1de871bfe8c7b773a93"` for repo https://github.com/private-repo/private-vcpkg-registry:
fatal: not a git repository: 'C:\Users\runneradmin\AppData\Local\vcpkg\registries\git\.git'

Error: Failed to fetch https://github.com/private-repo/private-vcpkg-registry:
Error: Failed to fetch ref 4e1a753b8265dc92e7e4f1de871bfe8c7b773a93 from repository https://github.com/private-repo/private-vcpkg-registry.
fatal: Cannot prompt because user interactivity has been disabled.
bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com': No such file or directory


-- Running vcpkg install - failed
```

From what I found in [vcpkg-tool](https://github.com/microsoft/vcpkg-tool/blob/cb1e40d6fe1a97ec4e29b79c3a0b4bcb02acc532/src/vcpkg/vcpkgpaths.cpp#L884) - it simply generates and executes git fetch cmd.

Is there a way to provide a token for git cmd? Or any different way to use a custom registry located in a private repo?

**Comment by srgbtl** [comment]
Same error if repo is cloned in a separate step and X_VCPKG_REGISTRIES_CACHE is used to provide vcpkg path to it.

**Comment by srgbtl** [comment]
A workaround is to configure git credential helper before running vcpkg.
`git config --global credential.helper '!f() { echo username=${GIT_USER}; echo password=${GIT_TOKEN}; }; f'`

**Comment by PhoebeHui** [comment]
@srgbtl, see https://github.com/microsoft/vcpkg/discussions/17720 and https://github.com/microsoft/vcpkg/discussions/17272.

**Comment by srgbtl** [comment]
The solution with using `git credential approve` (#17272) works for me.
