### ISSUE TITLE
[SDL2] Debug not copied over as dll

### ISSUE THREAD

**Issue by Baklap4** [microsoft/vcpkg#19463]
Within windows-x64 and building + running our application in debug a lot of dll's are copied over from their install location to the build root. Except that this doesn't happen for `SDL2d.dll`. Is this a bug on my side or on vcpkg's side? I also have to rename the `SDL2d.dll` to `SDL2.dll` for it to be able to work. Upstream they do use the d suffix as shown here: https://github.com/libsdl-org/SDL/blob/main/CMakeLists.txt#L63

**Comment by Baklap4** [comment]
I took a look into the `vcpkg.cmake` and found the script: `applocal.ps1` which is registered as a `POST_BUILD` process. 
```
add_custom_command(TARGET "${target_name}" POST_BUILD
                    COMMAND "${Z_VCPKG_POWERSHELL_PATH}" -noprofile -executionpolicy Bypass -file "${Z_VCPKG_TOOLCHAIN_DIR}/msbuild/applocal.ps1"
                        -targetBinary "$<TARGET_FILE:${target_name}>"
                        -installedDir "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}$<$<CONFIG:Debug>:/debug>/bin"
                        -OutVariable out
                    ${EXTRA_OPTIONS}
                )
```
It basicly copies the `*.dll` from the install dir to the build dir (where the exe lives). However it doesn't do so for SDL2 it seems. It does for non-debug builds though.

This is our `FindSDL2.cmake` module

```
include(LibFindMacros)
libfind_pkg_detect(SDL2 sdl2 FIND_PATH SDL.h PATH_SUFFIXES SDL2 FIND_LIBRARY SDL2)

# Process others than OSX with native SDL normally
if(NOT "${SDL2_SDL_LIBRARY}" MATCHES "framework")
  if(MINGW)
    set(MINGW32_LIBRARY mingw32)
    set(SDL2_PROCESS_LIBS ${SDL2_PROCESS_LIBS} MINGW32_LIBRARY)
  endif()
  find_library(SDL2_SDLmain_LIBRARY
    NAMES libSDL2main.a SDL2main
    HINTS ${SDL2_PKGCONF_LIBRARY_DIRS}
  )
  if (SDL2_SDLmain_LIBRARY)
    set(SDL2_PROCESS_LIBS ${SDL2_PROCESS_LIBS} SDL2_SDLmain_LIBRARY)
  endif()
  set(SDL2_PROCESS_LIBS ${SDL2_PROCESS_LIBS} SDL2_SDL_LIBRARY)
endif()

libfind_process(SDL2)

# Special processing for OSX native SDL
if("${SDL2_SDL_LIBRARY}" MATCHES "SDL.framework")
  set(SDL2_SOURCES "osx/SDLmain.m")
  set(SDL2_LIBRARIES "-framework SDL2")
endif()

# All OSX versions need Cocoa
if(APPLE)
  set(SDL2_LIBRARIES ${SDL2_LIBRARIES} "-framework Cocoa")
endif(APPLE)
```

**Comment by dg0yt** [comment]
Does your project really link to `SDL2d.dll`? I don't see a `find_library` call for this name, but I also don't know the import library name. The shown cmake code will find `SDL2main.lib` (MSVC) or `SDL2main.dll.a` (mingw). If this is not found in the debug path, it will be taken from the release path.

**Comment by Baklap4** [comment]
Yea this seemed an issue on my side. I wasn't linking to `SDL2d.lib` but to `SDL2.lib`
