### ISSUE TITLE
libgnutls build failure

### ISSUE THREAD

**Issue by xbotuk** [microsoft/vcpkg#19479]
**Host Environment**
- Windows 10.21H1
- Compiler: Visual Studio 2019 latest update 16.10.4 (latest, at the time of build)

**To Reproduce**
vcpkg install libgnutls

**Failure logs** 
E:\LIBS\vcpkg>vcpkg install libgnutls
Computing installation plan...
The following packages will be built and installed:
    libgnutls[core]:x64-windows -> 3.6.15#2
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\user\AppData\Local\vcpkg\archives\23\233696e545a29811b75d6bc3872d7654f6dedd726156783ed27e9e7a574d0f58.zip
Starting package 1/1: libgnutls:x64-windows
Building package libgnutls[core]:x64-windows...
-- Using E:/LIBS/vcpkg/downloads/gnutls-3.6.15.tar.xz
-- Cleaning sources at E:/LIBS/vcpkg/buildtrees/libgnutls/src/3.6.15-4050d06d46.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/LIBS/vcpkg/downloads/gnutls-3.6.15.tar.xz
-- Using source at E:/LIBS/vcpkg/buildtrees/libgnutls/src/3.6.15-4050d06d46.clean
-- Found external ninja('1.10.2').
-- Getting CMake variables for x64-windows
-- Using msys root at E:/LIBS/vcpkg/downloads/tools/msys2/703e5aa15d402568
-- Using msys root at E:/LIBS/vcpkg/downloads/tools/msys2/aa5af7b2aa7e90e8
-- Configuring x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: E:/LIBS/vcpkg/downloads/tools/msys2/703e5aa15d402568/usr/bin/bash.exe --noprofile --norc --debug -c "V=1 CPP='cl.exe -E' CC='cl.exe' CC_FOR_BUILD='cl.exe' CXX='cl.exe' RC='rc.exe' WINDRES='rc.exe' AR='lib.exe' LD='link.exe -verbose' RANLIB=':' STRIP=':' NM='dumpbin.exe -symbols -headers' DLLTOOL='link.exe -verbose -dll' CCAS=':' AS=':' ./../src/3.6.15-4050d06d46.clean/configure  --disable-doc --disable-silent-rules --disable-tests --disable-maintainer-mode --disable-rpath --disable-libdane --with-included-unistring --without-p11-kit --without-tpm LDFLAGS= ac_cv_prog_ac_ct_STRIP=: gl_cv_double_slash_root=yes ac_cv_func_memmove=yes --disable-silent-rules --verbose --enable-shared --disable-static --prefix=/E/LIBS/vcpkg/installed/x64-windows/debug --bindir='${prefix}'/../tools/libgnutls/debug/bin --sbindir='${prefix}'/../tools/libgnutls/debug/sbin --includedir='${prefix}'/../include --datarootdir='${prefix}'/share/libgnutls"
    Working Directory: E:/LIBS/vcpkg/buildtrees/libgnutls/x64-windows-dbg
    Error code: 1
    See logs for more information:
      E:\LIBS\vcpkg\buildtrees\libgnutls\config-x64-windows-dbg-out.log
      E:\LIBS\vcpkg\buildtrees\libgnutls\config-x64-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:820 (vcpkg_execute_required_process)
  ports/libgnutls/portfile.cmake:27 (vcpkg_configure_make)
  scripts/ports.cmake:141 (include)

Error: Building package libgnutls:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libgnutls:x64-windows
  Vcpkg version: 2021-08-03-1a6d67b8150e94b7f473c6ab1c0cfdd794316a64

Additionally, attach any relevant sections from the log files above.

**Additional context**
I tried with both x86-windows and x64-windows but same issue.

**Comment by xbotuk** [comment]
==== config-x64-windows-dbg-out.log ====

checking build system type... x86_64-pc-msys
checking host system type... x86_64-pc-msys
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
***
*** Checking for compilation programs...

checking pkg-config is at least version 0.9.0... yes
checking for gcc... cl.exe
checking whether the C compiler works... yes
checking for C compiler default output file name... conftest.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... no
checking for suffix of object files... obj
checking whether we are using the GNU C compiler... no
checking whether cl.exe accepts -g... yes
checking for cl.exe option to enable C11 features... unsupported
checking for cl.exe option to enable C99 features... unsupported
checking for cl.exe option to enable C89 features... none needed
checking whether the compiler is clang... no
checking for compiler option needed when checking for declarations... none
checking whether make supports the include directive... yes (GNU style)
checking dependency style of cl.exe... msvc7
checking how to run the C preprocessor... cl.exe -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... no
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... no
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking whether _XOPEN_SOURCE should be defined... no
checking for Minix Amsterdam compiler... no
checking the archiver (lib.exe) interface... lib
checking for ar... /e/LIBS/vcpkg/buildtrees/libgnutls/src/3.6.15-4050d06d46.clean/build-aux/ar-lib lib.exe
checking for _LARGEFILE_SOURCE value needed for large files... unknown
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... unknown
checking for _LARGE_FILES value needed for large files... unknown
checking dependency style of :... none
checking the archiver (/e/LIBS/vcpkg/buildtrees/libgnutls/src/3.6.15-4050d06d46.clean/build-aux/ar-lib lib.exe) interface... (cached) lib
checking whether we are using the GNU C++ compiler... no
checking whether cl.exe accepts -g... yes
checking for cl.exe option to enable C++11 features... none needed
checking dependency style of cl.exe... msvc7
checking for bison... no
checking for byacc... no
checking for a sed that does not truncate output... /usr/bin/sed
checking whether to build with code coverage support... no
checking whether to enable maintainer-specific portions of Makefiles... no
checking for inline... inline
checking for ANSI C header files... (cached) yes
checking cpuid.h usability... no
checking cpuid.h presence... no
checking for cpuid.h... no
checking for __get_cpuid_count... no
checking for struct iovec.iov_base... no
checking netinet/tcp.h usability... no
checking netinet/tcp.h presence... no
checking for netinet/tcp.h... no
checking stdatomic.h usability... no
checking stdatomic.h presence... no
checking for stdatomic.h... no
checking for library containing __atomic_load_4... no
configure: Could not detect libatomic
checking threads.h usability... no
checking threads.h presence... no
checking for threads.h... no
checking valgrind/memcheck.h usability... no
checking valgrind/memcheck.h presence... no
checking for valgrind/memcheck.h... no
checking for getrandom... no
checking for KERN_ARND... no
checking for getentropy... no
checking for NETTLE... yes
checking for HOGWEED... no

**Comment by xbotuk** [comment]
==== config-x64-windows-dbg-err.log ====

configure: WARNING: Compiler does not support C99. It may not be able to compile the project.
configure: error: 
  ***
  *** Libhogweed (nettle's companion library) 3.4.1 was not found. Note that you must compile nettle with gmp support.

**Comment by dg0yt** [comment]
Did you do a git pull before reporting? Just in case it is the mingw make issue fixed a commits ago.

**Comment by PhoebeHui** [comment]
Closing in favor of https://github.com/microsoft/vcpkg/issues/18395.
