### ISSUE TITLE
[osgEarth] update to <3.2>

### ISSUE THREAD

**Issue by chuyanjuncn** [microsoft/vcpkg#19475]
Library name: osgEarth

New version number: 3.2 

Other information that may be useful (release notes, etc...)
http://osgearth.org/
https://github.com/gwaldron/osgearth/tarball/osgearth-3.2
https://github.com/gwaldron/osgearth
https://github.com/gwaldron/osgearth/archive/refs/tags/osgearth-3.2.zip
https://github.com/gwaldron/osgearth/archive/refs/tags/osgearth-3.2.tar.gz

**Comment by chuyanjuncn** [comment]
any advances?

**Comment by JonLiu1993** [comment]
> any advances?

@chuyanjuncn ,Sorry reply you so late,I will submit a pr update osgearth recently.

**Comment by ankurverma85** [comment]
Any updates on this ?

**Comment by chuyanjuncn** [comment]
Version 3.2 (August 2021)
This is primarily a release and bug-fix release.

Release Highlights:

New ImGui integration, including the new osgearth_imgui command line tool.

ObjectIDPicker, a more reliable replacement for RTTPicker

ContourMap has new for custom color stops in the earth file

Build system now uses Git Submodules for some inline dependencies.

**Comment by JonLiu1993** [comment]
Fix by #20160
