### ISSUE TITLE
Install error: Microsof C/C++ Compiler Driver Stop Working

### ISSUE THREAD

**Issue by tzbo** [Microsoft/vcpkg#1947]
Install openssl or boost error, as following:

![toy5djy8cz z4sl 9i5n6t2](https://user-images.githubusercontent.com/19189826/31329818-6996e4ee-ad0e-11e7-866b-f48c5394609b.png)

![k ao48gj1onmnwm m75o1gw](https://user-images.githubusercontent.com/19189826/31329420-9fbb1114-ad0c-11e7-8980-1c74c674abaa.png)

**Comment by wangli28** [comment]
Thanks for posting this issue. Please open a new issue if this is still a problem for you.
