### ISSUE TITLE
[c-ares] build failure cross compile

### ISSUE THREAD

**Issue by agokjr** [microsoft/vcpkg#19489]
**Host Environment**
- OS: Ubuntu/Linux
- Compiler: x86_64-w64-mingw32-gcc 9.3.0
- Triplet: mingw-static

**To Reproduce**
`./vcpkg install --triplet mingw-static c-aries`

**Failure logs** 
```
This seems to be issue with generation of `ares_config.h` not really sure how to pass any variables in.
# vcpkg install c-ares
Computing installation plan...
The following packages will be built and installed:
    c-ares[core]:x64-mingw-static -> 1.17.1#2
Detecting compiler hash for triplet x64-mingw-static...
Could not locate cached archive: /root/.cache/vcpkg/archives/d8/d85b98e9a8c24305b5174ec64e76f3f71df2a3a15b407df27541a6a4342e5f77.zip
Starting package 1/1: c-ares:x64-mingw-static
Building package c-ares[core]:x64-mingw-static...
-- Using community triplet x64-mingw-static. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: /vcpkg/triplets/community/x64-mingw-static.cmake
-- Using /vcpkg/downloads/c-ares-c-ares-cares-1_17_1.tar.gz
-- Cleaning sources at /vcpkg/buildtrees/c-ares/src/res-1_17_1-7723edf4cb.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /vcpkg/downloads/c-ares-c-ares-cares-1_17_1.tar.gz
-- Using source at /vcpkg/buildtrees/c-ares/src/res-1_17_1-7723edf4cb.clean
-- Configuring x64-mingw-static-dbg
-- Configuring x64-mingw-static-rel
-- Building x64-mingw-static-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:155 (message):
    Command failed: /vcpkg/downloads/tools/cmake-3.20.2-linux/cmake-3.20.2-linux-x86_64/bin/cmake --build . --config Debug --target install -- -v -j33
    Working Directory: /vcpkg/buildtrees/c-ares/x64-mingw-static-dbg
    See logs for more information:
      /vcpkg/buildtrees/c-ares/install-x64-mingw-static-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:104 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:44 (vcpkg_build_cmake)
  ports/c-ares/portfile.cmake:25 (vcpkg_install_cmake)
  scripts/ports.cmake:141 (include)


Error: Building package c-ares:x64-mingw-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: c-ares:x64-mingw-static
  Vcpkg version: 2021-08-03-unknownhash

Additionally, attach any relevant sections from the log files above.
```
[install-x64-mingw-static-dbg-out.log](https://github.com/microsoft/vcpkg/files/6965279/install-x64-mingw-static-dbg-out.log)

**Additional context**
- was trying to install grpc which this is a dependency.
- cross compiling from in linux docker container.
- `ares_config.h` is generated via `src/lib/ares_config.h.cmake` called from `src/lib/CMakeList.txt:7`
- however not sure how to override the cmake variables within vcpkg

**Comment by agokjr** [comment]
figured workaround that to get c-ares on the copy of vcpkg on Linux for mingw.
1) build on windows computer using `msys2` and `x64-mingw-static`
2) transfer `$VCPKG_ROOT/installed/vcpkg/info/c-ares_1.17.2_x64-mingw-static.list` and files listed to Linux box.
3) copy entry for c-ares install from `$VCPKG_ROOT/installed/vcpkg/status` or `$VCPKG_ROOT/installed/vcpkg/updates/${SOME_NUMBER}` to Linux box's `$VCPKG_ROOT/installed/vcpkg/status`

Still have to test and use the library but I have installed grpc:x64-mingw-static that depends on successfully.

problem issue seems to be with c-ares build and not necessary vcpkg.

**Comment by JackBoosY** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
