### ISSUE TITLE
How do I ensure that package will go to binary cache after build is done

### ISSUE THREAD

**Issue by bialasjaroslaw** [microsoft/vcpkg#19486]
I looked into documentation/github repository SO/reddit but I am not able to find out if there is a way to force a package to go to binary cache (I am talking about simplest way of caching - local directory).

I just finished a quite long build process of the package `pcl`, but after that it is not present in the binary cache directory. I tried with other (smaller) packages and they are going there each time. With `--debug` switch there is even an info if there is a hit in the binary cache or not, but not in case of the `pcl`. I am wondering if there is a limit due to the fact that this package is quite big, or I have to specify this operation explicitly?

**Comment by JackBoosY** [comment]
I need to take a look.

**Comment by JackBoosY** [comment]
If you need to ensure that binarycaching feature is enabled, please set `binarycaching` to `VCPKG_FEATURE_FLAGS`, or pass `--binarysouce=<source>` to the install command. See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/specifications/binarycaching.md#configuration).

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

**Comment by stellarpower** [comment]
I have enabled binary caching using that option, however, following the initial build, the package did not successfully submit to the package repository. If I then run the command again, with the debug flag (i.e. `vcpkg install --debug package-name`), vcpkg doesn't try to submit it to the cache, as the build already completed, so I can't see what went wrong. 

I presume this is reasonably close to what the OP was trying to achieve.

**Comment by dg0yt** [comment]
> If I then run the command again, with the debug flag (i.e. `vcpkg install --debug package-name`), vcpkg doesn't try to submit it to the cache, as the build already completed, so I can't see what went wrong.

You would have to uninstall the package first.

> I am wondering if there is a limit due to the fact that this package is quite big, or I have to specify this operation explicitly?

There are problems with uploading big artifacts. It is known from some configurations of llvm. Typically, this happens with static triplets, in particular when installing tools for the debug variant.
