### ISSUE TITLE
missing static libraries in tbb

### ISSUE THREAD

**Issue by mehranmehr** [microsoft/vcpkg#19481]
**Describe the bug**
When I install tbb (normally or using a manifest) everything seems to be good, but the static libraries, i.e. libtbb.a libtbb_debug.a libtbbmalloc.a libtbbmalloc_debug.a are all missing.  Hence the `find_package(TBB CONFIG REQUIRED)` command in my CMakeLists.txt gives me the `Missed required Intel TBB component: tbb` error.

**Environment**
- OS: MacOS version 10.15.7
- Compiler: Clang 12.0

**To Reproduce**
1. ./vcpkg install tbb
2. find_package(TBB CONFIG REQUIRED) fails.

**Expected behavior**
libtbb.a libtbb_debug.a libtbbmalloc.a libtbbmalloc_debug.a should be made and installed.

**Failure logs** 
- find_package(TBB CONFIG REQUIRED) fails in my CMakeLists.txt.

**Additional context**
It works on my colleagues' laptops. Our systems are all similar.

**Comment by NancyLi1013** [comment]
Hi @mehranmehr 

Thanks for posting this issue.

Could you please remove `tbb `first and reinstall it, then post the build info?

- vcpkg remove tbb
- vcpkg install tbb --debug
- post the build info here

**Comment by mehranmehr** [comment]
Hi @NancyLi1013 

Thanks for taking the time to check this issue.
I did the above steps and here is the output:

`[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] BuiltinRegistry initialized with: ""
[DEBUG] Using vcpkg-root: /Users/mehranmehr/projects/vcpkg
[DEBUG] Using installed-root: /Users/mehranmehr/projects/vcpkg/installed
[DEBUG] BuiltinRegistry initialized with: ""
[DEBUG] Using buildtrees-root: /Users/mehranmehr/projects/vcpkg/buildtrees
[DEBUG] Using downloads-root: /Users/mehranmehr/projects/vcpkg/downloads
[DEBUG] Using packages-root: /Users/mehranmehr/projects/vcpkg/packages
[DEBUG] Using scripts-root: /Users/mehranmehr/projects/vcpkg/scripts
[DEBUG] Using ports-root: /Users/mehranmehr/projects/vcpkg/ports
[DEBUG] Using versions-root: /Users/mehranmehr/projects/vcpkg/versions
[DEBUG] Default binary cache path is: /Users/mehranmehr/.cache/vcpkg/archives
Computing installation plan...
[DEBUG] Found path: /usr/local/bin/cmake
[DEBUG] popen(/Users/mehranmehr/projects/vcpkg/downloads/tools/cmake-3.20.2-osx/cmake-3.20.2-macos-universal/CMake.app/Contents/bin/cmake --version 2>&1)
[DEBUG] cmd_execute_and_stream_data() returned 0 after    50791 us
[DEBUG] popen(/Users/mehranmehr/projects/vcpkg/downloads/tools/cmake-3.20.2-osx/cmake-3.20.2-macos-universal/CMake.app/Contents/bin/cmake -DVCPKG_ROOT_DIR=/Users/mehranmehr/projects/vcpkg -DPACKAGES_DIR=/Users/mehranmehr/projects/vcpkg/packages -DBUILDTREES_DIR=/Users/mehranmehr/projects/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=/Users/mehranmehr/projects/vcpkg/installed -DDOWNLOADS=/Users/mehranmehr/projects/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P /Users/mehranmehr/projects/vcpkg/buildtrees/0.vcpkg_tags.cmake 2>&1)
[DEBUG] cmd_execute_and_stream_data() returned 0 after    11611 us
The following packages will be built and installed:
    tbb[core]:x64-osx -> 2020_U3#5
Detecting compiler hash for triplet x64-osx...
[DEBUG] popen(/Users/mehranmehr/projects/vcpkg/downloads/tools/ninja-1.10.2-osx/ninja --version 2>&1)
[DEBUG] cmd_execute_and_stream_data() returned 0 after     6842 us
[DEBUG] Found path: /usr/local/bin/git
[DEBUG] Found path: /usr/bin/git
[DEBUG] popen(/usr/local/bin/git --version 2>&1)
[DEBUG] cmd_execute_and_stream_data() returned 0 after    23546 us
[DEBUG] popen(/Users/mehranmehr/projects/vcpkg/downloads/tools/cmake-3.20.2-osx/cmake-3.20.2-macos-universal/CMake.app/Contents/bin/cmake -DCURRENT_PORT_DIR=/Users/mehranmehr/projects/vcpkg/scripts/detect_compiler -DCURRENT_BUILDTREES_DIR=/Users/mehranmehr/projects/vcpkg/buildtrees/detect_compiler -DCURRENT_PACKAGES_DIR=/Users/mehranmehr/projects/vcpkg/packages/detect_compiler_x64-osx -D_HOST_TRIPLET=x64-osx -DCMD=BUILD -DDOWNLOADS=/Users/mehranmehr/projects/vcpkg/downloads -DTARGET_TRIPLET=x64-osx -DTARGET_TRIPLET_FILE=/Users/mehranmehr/projects/vcpkg/triplets/x64-osx.cmake -DVCPKG_BASE_VERSION=2021-08-03 -DVCPKG_CONCURRENCY=13 -DVCPKG_PLATFORM_TOOLSET=external -DGIT=/usr/local/bin/git -DVCPKG_ROOT_DIR=/Users/mehranmehr/projects/vcpkg -DPACKAGES_DIR=/Users/mehranmehr/projects/vcpkg/packages -DBUILDTREES_DIR=/Users/mehranmehr/projects/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=/Users/mehranmehr/projects/vcpkg/installed -DDOWNLOADS=/Users/mehranmehr/projects/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P /Users/mehranmehr/projects/vcpkg/scripts/ports.cmake 2>&1)
[DEBUG] -- Configuring x64-osx-rel
[DEBUG] -- The C compiler identification is AppleClang 12.0.0.12000032
[DEBUG] -- Detecting C compiler ABI info
[DEBUG] -- Detecting C compiler ABI info - done
[DEBUG] -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
[DEBUG] -- Detecting C compile features
[DEBUG] -- Detecting C compile features - done
[DEBUG] -- The CXX compiler identification is AppleClang 12.0.0.12000032
[DEBUG] -- Detecting CXX compiler ABI info
[DEBUG] -- Detecting CXX compiler ABI info - done
[DEBUG] -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
[DEBUG] -- Detecting CXX compile features
[DEBUG] -- Detecting CXX compile features - done
[DEBUG] -- Configuring done
[DEBUG] -- Generating done
[DEBUG] -- Build files have been written to: /Users/mehranmehr/projects/vcpkg/buildtrees/detect_compiler/x64-osx-rel
[DEBUG]
[DEBUG] #COMPILER_HASH#e189ed6203a70f0b5c0bda99725cce063c1e8003
[DEBUG] #COMPILER_C_HASH#c1fe47cfc79ed8b417053e8a94f813b4f75ba6ec
[DEBUG] #COMPILER_C_VERSION#12.0.0.12000032
[DEBUG] #COMPILER_C_ID#AppleClang
[DEBUG] #COMPILER_CXX_HASH#c1fe47cfc79ed8b417053e8a94f813b4f75ba6ec
[DEBUG] #COMPILER_CXX_VERSION#12.0.0.12000032
[DEBUG] #COMPILER_CXX_ID#AppleClang
[DEBUG] CMake Warning:
[DEBUG]   Manually-specified variables were not used by the project:
[DEBUG]
[DEBUG]     BUILD_SHARED_LIBS
[DEBUG]     CMAKE_INSTALL_BINDIR
[DEBUG]     CMAKE_INSTALL_LIBDIR
[DEBUG]     VCPKG_CRT_LINKAGE
[DEBUG]     VCPKG_PLATFORM_TOOLSET
[DEBUG]     VCPKG_SET_CHARSET_FLAG
[DEBUG]     _VCPKG_ROOT_DIR
[DEBUG]
[DEBUG]
[DEBUG]
[DEBUG] cmd_execute_and_stream_data() returned 0 after  2749351 us
[DEBUG]
[DEBUG] Detected compiler hash for triplet x64-osx: e189ed6203a70f0b5c0bda99725cce063c1e8003
[DEBUG] <abientries for tbb:x64-osx>
[DEBUG]   CMakeLists.txt|62f4dbe381e8c15d1ca304640448b3a17356b3b0a4e06eccb17548eb97882903
[DEBUG]   CONTROL|e65919a5bd37caea9a04d9f96e742513e95c2681c88790fd2dcd52502d6486ab
[DEBUG]   cmake|3.20.2
[DEBUG]   features|core
[DEBUG]   fix-static-build.patch|c01a7ad1743f76da6df5ddef11d5aed134e50f6144723cc51f02fa88c3d6b03e
[DEBUG]   portfile.cmake|e1277c6bb68f6f109e1cc9fa765dd4b4ca63f4ed479b2d1d4cd24a84896e761f
[DEBUG]   ports.cmake|c0512f9b1ab58726dcf19e52a9c6e3bd4198eae07083b506dec408dfc53b704a
[DEBUG]   post_build_checks|2
[DEBUG]   terminate-when-buildtool-notfound.patch|b29e09d42edb456933634c8727f4bb31bbe11ca19373fe2bd68e61c6a50ea97f
[DEBUG]   triplet|x64-osx
[DEBUG]   triplet_abi|0cc97ac39ed2fe40688d8bafad0ada7770ba2f0c628308eb0f31f13101beb338-d577d02c3d1128236b1160974d8f5593d83eac2ba7d39b254a2841f4f4659f2f-e189ed6203a70f0b5c0bda99725cce063c1e8003
[DEBUG]   usage|22036fe4dc9eb80873c077a815a76a6ac568ab04fce86ceb3824e001d36d4e62
[DEBUG]   vcpkg_configure_cmake|7ef59fb404a8ff25d9fe36e8a1a081de7f6b5aa9b52628207e1a955365f30a1f
[DEBUG]   vcpkg_fail_port_install|01b43acb1a7a8903f82a0a6fe9c005bef12e7f2189f78db317c60628fa457384
[DEBUG]   vcpkg_from_git|5a1a6937291b670fa030244fe1b2d08cff60da4ef8997c33447260fecbffce6e
[DEBUG]   vcpkg_from_github|2f5640e66a80bd2dced292099108f6b8a5ca4f5a27efc230e622424627c8fa72
[DEBUG]   vcpkg_install_cmake|a04ca69ec49d413d16091484556ec2c9429a4e1e002cbfd2fc20bb24644aa88c
[DEBUG]   vcpkg_install_msbuild|999b85d0e19c04143e255be8000843cbb0c6786ab5114babf268d367b695259d
[DEBUG] </abientries>
Could not locate cached archive: /Users/mehranmehr/.cache/vcpkg/archives/7e/7e0cee5e848e932ed842889ce31e35aedc67c5273039f952d768ec3726c55476.zip
Starting package 1/1: tbb:x64-osx
Building package tbb[core]:x64-osx...
[DEBUG] popen(/Users/mehranmehr/projects/vcpkg/downloads/tools/cmake-3.20.2-osx/cmake-3.20.2-macos-universal/CMake.app/Contents/bin/cmake -DALL_FEATURES= -DCURRENT_PORT_DIR=/Users/mehranmehr/projects/vcpkg/ports/tbb -D_HOST_TRIPLET=x64-osx -DFEATURES=core -DPORT=tbb -DVCPKG_USE_HEAD_VERSION=0 -D_VCPKG_DOWNLOAD_TOOL=BUILT_IN -D_VCPKG_EDITABLE=0 -D_VCPKG_NO_DOWNLOADS=0 -DCMD=BUILD -DDOWNLOADS=/Users/mehranmehr/projects/vcpkg/downloads -DTARGET_TRIPLET=x64-osx -DTARGET_TRIPLET_FILE=/Users/mehranmehr/projects/vcpkg/triplets/x64-osx.cmake -DVCPKG_BASE_VERSION=2021-08-03 -DVCPKG_CONCURRENCY=13 -DVCPKG_PLATFORM_TOOLSET=external -DGIT=/usr/local/bin/git -DVCPKG_ROOT_DIR=/Users/mehranmehr/projects/vcpkg -DPACKAGES_DIR=/Users/mehranmehr/projects/vcpkg/packages -DBUILDTREES_DIR=/Users/mehranmehr/projects/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=/Users/mehranmehr/projects/vcpkg/installed -DDOWNLOADS=/Users/mehranmehr/projects/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P /Users/mehranmehr/projects/vcpkg/scripts/ports.cmake 2>&1)
-- Using /Users/mehranmehr/projects/vcpkg/downloads/oneapi-src-oneTBB-eca91f16d7490a8abfdee652dadf457ec820cc37.tar.gz
-- Cleaning sources at /Users/mehranmehr/projects/vcpkg/buildtrees/tbb/src/7ec820cc37-30e75ff0be.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /Users/mehranmehr/projects/vcpkg/downloads/oneapi-src-oneTBB-eca91f16d7490a8abfdee652dadf457ec820cc37.tar.gz
-- Applying patch fix-static-build.patch
-- Applying patch terminate-when-buildtool-notfound.patch
-- Using source at /Users/mehranmehr/projects/vcpkg/buildtrees/tbb/src/7ec820cc37-30e75ff0be.clean
-- Configuring x64-osx-dbg
-- Configuring x64-osx-rel
-- Building x64-osx-dbg
-- Building x64-osx-rel
-- Installing: /Users/mehranmehr/projects/vcpkg/packages/tbb_x64-osx/share/tbb/copyright
[DEBUG] cmd_execute_and_stream_data() returned 0 after  9896922 us
-- Performing post-build validation
-- Performing post-build validation done
[DEBUG] system(cd /Users/mehranmehr/projects/vcpkg/packages/tbb_x64-osx && zip --quiet -y -r /Users/mehranmehr/projects/vcpkg/buildtrees/tbb/x64-osx.zip *)
[DEBUG] system() returned 0 after 63721 us
Stored binary cache: /Users/mehranmehr/.cache/vcpkg/archives/7e/7e0cee5e848e932ed842889ce31e35aedc67c5273039f952d768ec3726c55476.zip
Building package tbb[core]:x64-osx... done
Installing package tbb[core]:x64-osx...
Installing package tbb[core]:x64-osx... done
Elapsed time for package tbb:x64-osx: 10 s

Total elapsed time: 12.8 s

The package tbb provides CMake targets:

    find_package(TBB CONFIG REQUIRED)
    target_link_libraries(main PRIVATE TBB::tbb)

[DEBUG] /Users/mehranmehr/projects/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-08-03/src/vcpkg/install.cpp(1089)
[DEBUG] Exiting after 12872567 us (12868777 us)
`

**Comment by NancyLi1013** [comment]
```
-- Building is unsuccessful (2): /Users/mehranmehr/projects/vcpkg/buildtrees/tbb/x64-osx-dbg/src/./build/Makefile.tbb:28: CONFIG: cfg=release arch=intel64 compiler=clang target=macos runtime=cc12.0.0_os10.15.7
ar: -L/usr/local/opt/openssl@1.1/lib: No such file or directory
make[1]: *** [libtbb.a] Error 1
make[1]: *** Deleting file `libtbb.a'
make: *** [tbb] Error 2
```
The problem maybe here `ar: -L/usr/local/opt/openssl@1.1/lib: No such file or directory`

**Comment by mehranmehr** [comment]
Actually, that folder is there (is a symlink) and it contains the static and dynamic libraries for openssl. 

`(mlpiot) ~/p/vcpkg ❯❯❯ ls -al /usr/local/opt/openssl@1.1/lib                                                    ✘ 1
total 15144
drwxr-xr-x  10 mehranmehr  staff      320 Mar 25 13:28 .
drwxr-xr-x  14 mehranmehr  staff      448 Aug 12 13:45 ..
drwxr-xr-x   4 mehranmehr  staff      128 Mar 25 13:28 engines-1.1
-r--r--r--   1 mehranmehr  staff  2437024 Jun  9 12:18 libcrypto.1.1.dylib
-r--r--r--   1 mehranmehr  staff  4087072 Mar 25 13:28 libcrypto.a
lrwxr-xr-x   1 mehranmehr  staff       19 Mar 25 13:28 libcrypto.dylib -> libcrypto.1.1.dylib
-r--r--r--   1 mehranmehr  staff   502872 Jun  9 12:18 libssl.1.1.dylib
-r--r--r--   1 mehranmehr  staff   723992 Mar 25 13:28 libssl.a
lrwxr-xr-x   1 mehranmehr  staff       16 Mar 25 13:28 libssl.dylib -> libssl.1.1.dylib
drwxr-xr-x   5 mehranmehr  staff      160 Jun  9 12:18 pkgconfig`

I am not sure if vcpkg should use its own openssl or not. However, the whole thing is strange to me. The fact that the configuration is done using make and not cmake is also strange. I will try to debug the makefiles to find something. Thank you.

**Comment by NancyLi1013** [comment]
Generally, we prefer to use the library that is  provided by vcpkg. But for this issue, `openssl `seems not to be required here. Since there is no `openssl` in `tbb `source codes.

**Comment by NancyLi1013** [comment]
Please feel free to reopen this issue if it is still a problem for you.
