### ISSUE TITLE
vcpkg fails to msiexec 7zip extraction under jenkins ci with failed stdout capture

### ISSUE THREAD

**Issue by marekr** [microsoft/vcpkg#19490]
**Describe the bug**
This is two bugs, after updating to the latest vcpkg which introduced msi package for 7zip. I can no longer have CI setup vcpkg. It will fail with bad stdout capture.

It could be an environment issue I am not aware of BUT the first annoying part of this bug, it fails to capture stdout of msiexec properly.

```
14:59:23  A suitable version of 7zip was not found (required v19.0.0). Downloading portable 7zip v19.0.0...
14:59:23  Extracting 7zip...
14:59:23  msiexec failed while extracting 'J:\workspace\windows-kicad-ps-pipeline\vcpkg\downloads\7z1900-x64.msi' with message:
14:59:23  T
```

It only captures "T" and prints it. It appears that it might be capturing the "T" of the TARGET_DIR arg.
This appears to be performed by vcpkg-tool rather than find_acquire_program.

**Environment**
- OS: Windows Server 2019

**To Reproduce**
Not entirely sure

**Expected behavior**
msiexec extracts without error OR prints the full error

**Comment by JackBoosY** [comment]
@BillyONeal Can you please take a look?

Thanks.

**Comment by dg0yt** [comment]
After updating my local `master` (including 0fd101a2c), I just had a 7zip installation problem, too (Windows 10). The output, **after successful build and validation**, is confusing in a different way:
~~~
...
A suitable version of 7zip was not found (required v19.0.0). Downloading portable 7zip v19.0.0...
Downloading 7zip...
  https://www.7-zip.org/a/7z1900-x64.msi -> D:\msys64\home\pastor\vcpkg\downloads\7z1900-x64.msi
Extracting 7zip...
A suitable version of 7zip was not found (required v19.0.0). Downloading portable 7zip v19.0.0...
Extracting 7zip...
~~~
Note that some message appear twice. 
After this message, there is a `downloads/tools/7zip-19.00-windows.partial.6724/` folder which indicates an interruption. The SHA512 sum of the msi matches, and repeated attempts fail in the same way, only omitting the unique download lines.

Now I tried a `vcpkg-bootstrap.bat` which acquired a new version of the tool. After this, the next install **successfully** acquired new versions of cmake and 7zip **before the build**, just after `Computing installation plan...`

So there is a workaround, but there is also a fundamental issue.

**Comment by marekr** [comment]
> After updating my local `master` (including [0fd101a](https://github.com/microsoft/vcpkg/commit/0fd101a2c5c6a5b47cef35e172be0ae32dd241d4)), I just had a 7zip installation problem, too (Windows 10). The output, **after successful build and validation**, is confusing in a different way:
> 
> ```
> ...
> A suitable version of 7zip was not found (required v19.0.0). Downloading portable 7zip v19.0.0...
> Downloading 7zip...
>   https://www.7-zip.org/a/7z1900-x64.msi -> D:\msys64\home\pastor\vcpkg\downloads\7z1900-x64.msi
> Extracting 7zip...
> A suitable version of 7zip was not found (required v19.0.0). Downloading portable 7zip v19.0.0...
> Extracting 7zip...
> ```
> 
> Note that some message appear twice.
> After this message, there is a `downloads/tools/7zip-19.00-windows.partial.6724/` folder which indicates an interruption. The SHA512 sum of the msi matches, and repeated attempts fail in the same way, only omitting the unique download lines.
> 
> Now I tried a `vcpkg-bootstrap.bat` which acquired a new version of the tool. After this, the next install **successfully** acquired new versions of cmake and 7zip **before the build**, just after `Computing installation plan...`
> 
> So there is a workaround, but there is also a fundamental issue.

Nope, no workaround on my side. We already execute bootstrap-vcpkg.bat in this full build CI job.

```
02:59:08  Downloading https://github.com/microsoft/vcpkg-tool/releases/download/2021-08-03/vcpkg.exe -> J:\workspace\windows-kicad-ps-pipeline\vcpkg\vcpkg.exe... done.
02:59:09  Validating signature... done.
```

**Comment by dg0yt** [comment]
@marekr Do you the face the issue before the build or after the build?

**Comment by marekr** [comment]
> @marekr Do you the face the issue before the build or after the build?

It happens during `Computing installation plan...` when given a long list of dependencies to install

**Comment by dg0yt** [comment]
Okay, that's the step that succeed for me. Maybe it was just a lucky race...
And of course I'm using an unprivileged user, on desktop. This may be different for your CI.

**Comment by dg0yt** [comment]
In particular, the 7zip download changed from nuget to msi with 0fd101a2c.

**Comment by marekr** [comment]
> In particular, the 7zip download changed from nuget to msi with [0fd101a](https://github.com/microsoft/vcpkg/commit/0fd101a2c5c6a5b47cef35e172be0ae32dd241d4).

I am quite aware. The issue lies in the new implementation where the msiexec is performed by vcpkg.exe itself and the changes in vcpkg-tools repo. But that repo has issues disabled so here we are.

I think somewhere the TARGET_DIR arg isn't being escaped properly, maybe? Otherwise it should even be responding with a "T" for whatever broken error output

**Comment by GyrosGeier** [comment]
One important point: the build normally runs as an unprivileged user with no desktop access. Running as Administrator from an ssh session works, so it seems the MSI is expecting Administrator privileges for some reason, but not having desktop access is fine.

**Comment by GyrosGeier** [comment]
FWIW, last run (after deleting workspace to start from a clean slate) is [here](https://jenkins.simonrichter.eu/job/windows-kicad-ps-pipeline/526/).

**Comment by BillyONeal** [comment]
Can you try rerunning with `--debug`?

**Comment by ras0219-msft** [comment]
We've observed an issue similar to this on another system internally (though the single character of output is `A` instead of `T`). Upon running with `--debug`, the error code was 1618, which is msi's code for `ERROR_INSTALL_ALREADY_RUNNING`. Essentially, `msiexec`, even when running as an unprivileged user, still needs some amount of global locking.

I've submitted and merged https://github.com/microsoft/vcpkg-tool/pull/153 which adds a retry loop around this operation which we will publish very soon. In the meantime you can always work around the issue by explicitly checking out the vcpkg commit before the new 7zip update (https://github.com/microsoft/vcpkg/commit/0fd101a2c5c6a5b47cef35e172be0ae32dd241d4) instead of `master`.

**Comment by dg0yt** [comment]
> `ERROR_INSTALL_ALREADY_RUNNING`

Is it possible that vcpkg runs `msiexec` twice, or perhaps doesn't wait properly for one installation to finish before starting another? As noted above, I did have duplicated output.

**Comment by marekr** [comment]
> We've observed an issue similar to this on another system internally (though the single character of output is `A` instead of `T`). Upon running with `--debug`, the error code was 1618, which is msi's code for `ERROR_INSTALL_ALREADY_RUNNING`. Essentially, `msiexec`, even when running as an unprivileged user, still needs some amount of global locking.
> 
> I've submitted and merged [microsoft/vcpkg-tool#153](https://github.com/microsoft/vcpkg-tool/pull/153) which adds a retry loop around this operation which we will publish very soon. In the meantime you can always work around the issue by explicitly checking out the vcpkg commit before the new 7zip update ([0fd101a](https://github.com/microsoft/vcpkg/commit/0fd101a2c5c6a5b47cef35e172be0ae32dd241d4)) instead of `master`.


I am getting error code 1601 after recreating a local windows server VM mirroring our CI process
```
[DEBUG] CreateProcessW(cmd /c msiexec /a "C:\jenkins\kicad-win-builder\vcpkg\downloads\7z1900-x64.msi" /qn TARGETDIR
="C:\jenkins\kicad-win-builder\vcpkg\downloads\tools\7zip-19.00-windows.partial.1884")
[DEBUG] cmd_execute_and_stream_data() returned 1601 after   170090 us
msiexec failed while extracting 'C:\jenkins\kicad-win-builder\vcpkg\downloads\7z1900-x64.msi' with message:
T
[DEBUG] C:\a\1\s\src\vcpkg\archives.cpp(85)
```

**Comment by BillyONeal** [comment]
> I am getting error code 1601 after recreating a local windows server VM mirroring our CI process

Consulting decoder ring for that: https://james.darpinian.com/decoder/?q=1601

looks like ERROR_INSTALL_SERVICE_FAILURE: The Windows Installer Service could not be accessed. This can occur if the Windows Installer is not correctly installed. Contact your support personnel for assistance.

**Comment by marekr** [comment]
> > I am getting error code 1601 after recreating a local windows server VM mirroring our CI process
> 
> Consulting decoder ring for that: https://james.darpinian.com/decoder/?q=1601
> 
> looks like ERROR_INSTALL_SERVICE_FAILURE: The Windows Installer Service could not be accessed. This can occur if the Windows Installer is not correctly installed. Contact your support personnel for assistance.

Yes, but this is a 100% fresh windows server install. msiexec works just fine logged over remote desktop. This seems like some sort security restriction over openssh being placed by Windows but I cannot find any documentation for it.

MSI packages are very...unfriendly :(

**Comment by marekr** [comment]
Reading further, this is a long running Windows restriction that the Windows Installer Service simply does not operate on non-admin and non-interactive logins

https://sourceforge.net/p/wix/mailman/message/24361610/   (one random thread on the wix mailing list)

RIP, I guess we have to make CI insecure by giving it administrator permissions

**Comment by paulcleggSIG** [comment]
We're seeing this same issue running vcpkg in a TeamCity job. Would it be reasonable to rollback the 7-zip distribution mechanism to before 0fd101a ?

Granting interactive admin to a CI process that downloads binaries from the internet is not a solution for us.

**Comment by ConceptualWempa** [comment]
alternately, could a command-line option be provided to direct vcpkg to use an already-installed 7z as a workaround?

**Comment by paulcleggSIG** [comment]
Allowing us to pass in the location of an existing 7z v19 exe would work for us as well.

**Comment by BillyONeal** [comment]
If it's ok the PATH I think we use that one? Not positive...

**Comment by ConceptualWempa** [comment]
does not appear to "use the one on the PATH"; at least, not for a simplistic interpretation of what that means:
- installed 7z v19 (literally by interactively running the same .msi vcpkg has been downloading but failing to unpack)
- put "C:\Program Files\7-Zip" first on PATH
- "7z" prints the 7z usage summary, including version showing 19
- vcpkg immediately afterwards in same shell session still downloads and attempts/fails to unpack 7z1900-x64.msi

is there some other form it needs to be in PATH?  or some other clue/queue vcpkg needs?

**Comment by gotocoffee1** [comment]
I think the lookup is broken too. Vcpkg search for "[7zip](https://github.com/microsoft/vcpkg-tool/blob/cb1e40d6fe1a97ec4e29b79c3a0b4bcb02acc532/include/vcpkg/tools.h#L14)" it seems.

**Comment by antoinebj** [comment]
This is marked as requiring repro. Did anyone manage to make vcpkg work with a CI runner running under user privileges (not admin) from a recent fresh install? If not, then that gives us the repro.

**Comment by hajokirchhoff** [comment]
Same thing here. Azure Devops Pipeline fails because 7zip cannot be extracted: msiexec failed...

**Comment by dg0yt** [comment]
I digged into the vcpkg tool code and found [this spot in a retry-loop](https://github.com/microsoft/vcpkg-tool/blob/d13ece3a9fe60f5159a8ff6cfa37c2676d50ff3c/src/vcpkg/archives.cpp#L60-L72):

~~~C++
            // msiexec is a WIN32/GUI application, not a console application and so needs special attention to wait
            // until it finishes (wrap in cmd /c).
            const auto code_and_output = cmd_execute_and_capture_output(
                Command{"cmd"}
                    .string_arg("/c")
                    .string_arg("msiexec")
                    // "/a" is administrative mode, which unpacks without modifying the system
                    .string_arg("/a")
                    .path_arg(archive)
                    .string_arg("/qn")
                    // msiexec requires quotes to be after "TARGETDIR=":
                    //      TARGETDIR="C:\full\path\to\dest"
                    .raw_arg(Strings::concat("TARGETDIR=", Command{to_path}.extract())));
~~~

IIRC from my software deployment scripts, `cmd /C` *is not* suffficient to wait for a WIN32/GUI application to finish. You need 
~~~
cmd /C start /wait "" <Cmd>
~~~
where `""` is needed to let `start` not mistake another quoted argument for the window title. Cf. https://ss64.com/nt/start.html

**Comment by dg0yt** [comment]
More on `msiexec` and `start /wait`, from 2005:
https://devblogs.microsoft.com/setup/waiting-for-msiexec-exe-to-finish/

**Comment by marekr** [comment]
> I digged into the vcpkg tool code and found [this spot in a retry-loop](https://github.com/microsoft/vcpkg-tool/blob/d13ece3a9fe60f5159a8ff6cfa37c2676d50ff3c/src/vcpkg/archives.cpp#L60-L72):
> 
> ```c++
>             // msiexec is a WIN32/GUI application, not a console application and so needs special attention to wait
>             // until it finishes (wrap in cmd /c).
>             const auto code_and_output = cmd_execute_and_capture_output(
>                 Command{"cmd"}
>                     .string_arg("/c")
>                     .string_arg("msiexec")
>                     // "/a" is administrative mode, which unpacks without modifying the system
>                     .string_arg("/a")
>                     .path_arg(archive)
>                     .string_arg("/qn")
>                     // msiexec requires quotes to be after "TARGETDIR=":
>                     //      TARGETDIR="C:\full\path\to\dest"
>                     .raw_arg(Strings::concat("TARGETDIR=", Command{to_path}.extract())));
> ```
> 
> IIRC from my software deployment scripts, `cmd /C` _is not_ suffficient to wait for a WIN32/GUI application to finish. You need
> 
> ```
> cmd /C start /wait "" <Cmd>
> ```
> 
> where `""` is needed to let `start` not mistake another quoted argument for the window title. Cf. https://ss64.com/nt/start.html

No, the problem is deeper. 

msiexec does not run as administrator under non-interactive (no windows GUI) session. This is a limitation imposed by microsoft since even XP and it's why this is failing in the numerous CI users in this thread

**Comment by hajokirchhoff** [comment]
> msiexec does not escalate to administrator under non-interactive (no windows GUI) session. 
...
> The dumbest part, which is also a msiexec issue is, even if you are just extracting the installer without targeting an administrator required path, it stops at the check for admin escalation without extracting.

I agree, this is exactly what I found. I think this does not happen with the 7zip .exe based installer, which is why older versions of vcpkg work okay and why switching back to 7zip-.exe installer would probably solve the issue. (This one at least...)

**Comment by JackBoosY** [comment]
Should be the same issue with https://github.com/microsoft/vcpkg/issues/23284.

**Comment by BillyONeal** [comment]
https://github.com/microsoft/vcpkg-tool/pull/404

**Comment by JackBoosY** [comment]
Resolved by updating vcpkg-tool. Please git pull vcpkg and run bootstrap script again.
