### ISSUE TITLE
[New Port Request] xgboost

### ISSUE THREAD

**Issue by draveness** [microsoft/vcpkg#19498]
Library name: xgboost

Library description: Scalable, Portable and Distributed Gradient Boosting (GBDT, GBRT or GBM) Library, for Python, R, Java, Scala, C++ and more. Runs on single machine, Hadoop, Spark, Dask, Flink and DataFlow

Source repository URL: https://github.com/dmlc/xgboost

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
