### ISSUE TITLE
Package: opencv4:x64-windows   Vcpkg version: 2021-08-03-1a6d67b8150e94b7f473c6ab1c0cfdd794316a64

### ISSUE THREAD

**Issue by avre10** [microsoft/vcpkg#19497]
**Host Environment**
- OS: [Windows]

**Failure logs** 
CMake Error at D:/vcpkg/buildtrees/opencv4/src/4.5.2-755f235ba0.clean/cmake/OpenCVDownload.cmake:161 (message):
      Downloads are not permitted during configure. Please pre-download the file "D:/vcpkg/downloads/opencv-cache/nvidia_optical_flow/a73cd48b18dcc0cc8933b30796074191-edb50da3cf849840d680249aa6dbef248ebce2ca.zip":
      
      vcpkg_download_distfile(OCV_DOWNLOAD
          URLS "https://github.com/NVIDIA/NVIDIAOpticalFlowSDK/archive/edb50da3cf849840d680249aa6dbef248ebce2ca.zip"
          FILENAME "opencv-cache/nvidia_optical_flow/a73cd48b18dcc0cc8933b30796074191-edb50da3cf849840d680249aa6dbef248ebce2ca.zip"
          SHA512 0
      )
Call Stack (most recent call first):
  D:/vcpkg/buildtrees/opencv4/src/4.5.2-58c4f07550.clean/modules/cudaoptflow/CMakeLists.txt:15 (ocv_download)

**Additional context**
Building Package: opencv4:x64-windows
Vcpkg version: 2021-08-03-1a6d67b8150e94b7f473c6ab1c0cfdd794316a64

**Comment by King-Otaku** [comment]
I hava same problem. It's not a fundamental solution, but I heard that build repeatably may work. So I tried it , but it didn't work. And I also rebuild vcpkg from first step but still it didn't work. Somebody help me!!!

**Comment by NancyLi1013** [comment]
@cenit 

Could you please help take a look what's wrong here? Thanks.

**Comment by cenit** [comment]
it is already fixed in #18827, but that PR is waiting for another pr to be merged.
time is passing fast and opencv will soon have another release, and here on vcpkg we are still stuck on the older one and with download errors

**Comment by NancyLi1013** [comment]
Thanks for your information. @cenit 

Yes, there are always something blocks the progress of PR.

**Comment by avre10** [comment]
Any solution now apart of waiting?

**Comment by NancyLi1013** [comment]
Please keep this issue open until it is fixed.

**Comment by PhoebeHui** [comment]
@avre10, this issue has been fixed, please get latest source and try again.
