### ISSUE TITLE
Error: Building package rttr:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by FireFlyForLife** [Microsoft/vcpkg#1949]
running on Windows 10 Home
 - version 1703 
 - OS build: 15063.608
 - language is: Dutch with english keyboard addon

I succesfully installed vcpkg with:
`powershell -exec bypass scripts/bootstrap.ps1`
`.\vcpkg integrate install`

After that I tried to install rttr with:
`.\vcpkg install rttr curl`

I expected the rttr library to be downloaded, build. 

But the build failt with the following error:

> CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:43 (message):
>     Command failed: C:/Projects/vcpkg/downloads/cmake-3.9.3-win32-x86/bin/cmake.exe;C:/Projects/vcpkg/buildtrees/rttr/src/rttr-0.9.5-src;-DBUILD_SHARED_LIBS=ON;-DVCPKG_TARGET_TRIPLET=x86-windows;-DCMAKE_CXX_FLAGS= /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP ;-DCMAKE_C_FLAGS= /DWIN32 /D_WINDOWS /W3 /utf-8 /MP ;-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON;-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE;-DCMAKE_VERBOSE_MAKEFILE=ON;-DVCPKG_APPLOCAL_DEPS=OFF;-DCMAKE_TOOLCHAIN_FILE=C:/Projects/vcpkg/scripts/buildsystems/vcpkg.cmake;-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON;-DCMAKE_CXX_FLAGS_RELEASE=/MD /O2 /Oi /Gy /DNDEBUG /Z7 ;-DCMAKE_C_FLAGS_RELEASE=/MD /O2 /Oi /Gy /DNDEBUG /Z7 ;-DCMAKE_SHARED_LINKER_FLAGS_RELEASE=/DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF ;-DCMAKE_EXE_LINKER_FLAGS_RELEASE=/DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF ;-G;Ninja;-DCMAKE_BUILD_TYPE=Release;-DCMAKE_INSTALL_PREFIX=C:/Projects/vcpkg/packages/rttr_x86-windows
>     Working Directory: C:/Projects/vcpkg/buildtrees/rttr/x86-windows-rel
>     See logs for more information:
>       C:\Projects\vcpkg\buildtrees\rttr\config-x86-windows-rel-out.log
>       C:\Projects\vcpkg\buildtrees\rttr\config-x86-windows-rel-err.log
> 
> Call Stack (most recent call first):
>   scripts/cmake/vcpkg_configure_cmake.cmake:170 (vcpkg_execute_required_process)
>   ports/rttr/portfile.cmake:20 (vcpkg_configure_cmake)
>   scripts/ports.cmake:72 (include)
> 
> 
> Error: Building package rttr:x86-windows failed with: BUILD_FAILED
> Please ensure you're using the latest portfiles with `.\vcpkg update`, then
> submit an issue at https://github.com/Microsoft/vcpkg/issues including:
>   Package: rttr:x86-windows
>   Vcpkg version: 0.0.91-2017-10-08-d7c60c2048d8d71915478de871caae2767bd80e6

The full log can be found in this pastebin: https://pastebin.com/WFygaYpJ

According to the version on the github CONTROL file the version of rttr is:
 `Version: 0.9.5-1`

**Comment by ras0219-msft** [comment]
Thanks for the pastebin! Could you attach the log files listed in the error message?

>C:\Projects\vcpkg\buildtrees\rttr\config-x86-windows-rel-out.log
C:\Projects\vcpkg\buildtrees\rttr\config-x86-windows-rel-err.log

**Comment by obfuscate** [comment]
I have got the same problem:

>  .\vcpkg install rttr
The following packages will be built and installed:
    rttr[core]:x86-windows
Starting package 1/1: rttr:x86-windows
Building package rttr[core]:x86-windows...
-- Using cached D:/Sources/vcpkg/downloads/rttrorg-rttr-v0.9.5.tar.gz
-- Using source at D:/Sources/vcpkg/buildtrees/rttr/src/v0.9.5-dc133aa853
-- Applying patch D:/Sources/vcpkg/ports/rttr/fix-directory-output.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch D:/Sources/vcpkg/ports/rttr/disable-unit-tests.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch D:/Sources/vcpkg/ports/rttr/remove-owner-read-perms.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
CMake Error at ports/rttr/portfile.cmake:41 (file):
  file must be called with at least two arguments.
Call Stack (most recent call first):
  scripts/ports.cmake:71 (include)

>Package: rttr:x86-windows
  Vcpkg version: 0.0.113-nohash

**Comment by wangli28** [comment]
Thanks for posting this issue. Please open a new issue if this is still a problem for you.
