### ISSUE TITLE
[boost-multiprecision] missing dependency

### ISSUE THREAD

**Issue by remz1337** [microsoft/vcpkg#19506]
**Describe the bug**
Tried to compile simple program with boost-multiprecision and compiler complains about missing boost/math/tools/complex.hpp file

**Environment**
- OS: Windows 10
- Compiler: MSVC 19

**To Reproduce**
1. `vcpkg install boost-multiprecision:x64-windows`
2. Add boost to CMakeLists: find_package(Boost REQUIRED); target_link_libraries(Test PRIVATE Boost::boost)
3. include boost multiprecision header in a simple hello world program
4. Compile: fatal error C1083: Cannot open include file: 'boost/math/tools/complex.hpp' 

**Expected behavior**
compile successfully

**Additional context**
Everything works after manually installing boost-math
`vcpkg install boost-math:x64-windows`

**Comment by PhoebeHui** [comment]
@remz1337, thanks for reporting this issue! I have submitted a PR to fix it.
