### ISSUE TITLE
[raylib:wasm32-emscripten] build failure

### ISSUE THREAD

**Issue by Rdna123** [microsoft/vcpkg#19515]
**Host Environment**
- OS: Windows 
- Compiler: Latest EMSDK, Visual Studio 2019, Ninja 1.10.2.git.kitware.jobserver-1

Package: raylib:wasm32-emscripten
 Vcpkg version: 2021-08-03-1a6d67b8150e94b7f473c6ab1c0cfdd794316a64

**To Reproduce**
`./vcpkg install raylib:wasm32-emscripten`

**Failure logs** 
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: ninja -v
    Working Directory: C:/Users/chknm/TestingGrounds/vcpkg/buildtrees/raylib/wasm32-emscripten-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\Users\chknm\TestingGrounds\vcpkg\buildtrees\raylib\config-wasm32-emscripten-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:356 (vcpkg_execute_required_process)
  ports/raylib/portfile.cmake:39 (vcpkg_configure_cmake)
  scripts/ports.cmake:141 (include)
[config-wasm32-emscripten-out.log](https://github.com/microsoft/vcpkg/files/6973416/config-wasm32-emscripten-out.log)

**Comment by JackBoosY** [comment]
![Uploading image.png…]()

**Comment by Rdna123** [comment]
What is the image it just says uploading image

**Comment by JackBoosY** [comment]
> What is the image it just says uploading image

Ah sorry, that's a wrong operation, is this issue still exist?

**Comment by Rdna123** [comment]
I do not know I have changed projects and computers since then.

**Comment by JackBoosY** [comment]
Okay, please reopen this issue if it still bother you.

**Comment by hbirler** [comment]
I have checked and the error still persists. The issue should be reopened.

**Comment by JackBoosY** [comment]
```
Could NOT find X11 (missing: X11_X11_LIB)
```
X11 is not supported on Windows in vcpkg now.

**Comment by JackBoosY** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
