### ISSUE TITLE
SDL2 extension packages try to use release dll in debug configuration

### ISSUE THREAD

**Issue by MerickOWA** [Microsoft/vcpkg#1951]
Steps to reproduce:

1. vcpkg install sdl2
2. vcpkg install sdl2-net
3. create a new c++ windows console application
4. paste in simple main 
```
// SDL2Test.cpp : Defines the entry point for the console application.
//

#include "stdafx.h"
#include <SDL2\SDL.h>
#include <SDL2\SDL_net.h>

int main(int argc, char *argv[]) {
  SDL_Init(SDL_INIT_EVERYTHING);
  SDLNet_Init();
  return 0;
}

```
I expect that running the application would launch successfully.

I actually get an error "The program can't start because SDL2.dll is missing from your computer.  Try reinstalling the program to fix this problem"

This appears to be due to the fact that the built \vcpkg\installed\x86-windows\debug\bin\SDL2_net.dll imports "SDL2.dll" instead of "SDL2d.dll"

This same problem seems to exist with other SDL2 extension libraries such as sdl2-gfx, sdl2-image, sdl2-mixer, sdl2-net, and sdl2-ttf.

Its possible this problem is with the libraries themselves.  I don't understand cmake and/or vcpkg's magic to understand where the problem lies.

**Comment by ras0219-msft** [comment]
Thanks for reporting this! It should be fixed in deee8c17.

**Comment by TheCycoONE** [comment]
smpeg2 is still affected

**Comment by MerickOWA** [comment]
@TheCycoONE I've submitted #2030 to fix smpeg2

**Comment by TheCycoONE** [comment]
Opps, I just submitted #2031, I'll close mine!
