### ISSUE TITLE
[sqlcipher] build failure

### ISSUE THREAD

**Issue by felfelche** [microsoft/vcpkg#19526]
**Host Environment**
- OS: Windows
- Compiler: Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27027.1

**To Reproduce**
`vcpkg.exe install sqlcipher:x64-windows-static`

**Failure logs** 
vcpkg.exe install sqlcipher:x64-windows-static
Computing installation plan...
The following packages will be built and installed:
    sqlcipher[core]:x64-windows-static -> 4.4.3
Detecting compiler hash for triplet x64-windows-static...
Starting package 1/1: sqlcipher:x64-windows-static
Building package sqlcipher[core]:x64-windows-static...
-- Note: sqlcipher only supports dynamic library linkage. Building dynamic library.
CMake Error at scripts/cmake/vcpkg_check_linkage.cmake:61 (message):
  Refusing to build unexpected dynamic library against the static CRT.

      If this is desired, please configure your triplet to directly request this configuration.
Call Stack (most recent call first):
  ports/sqlcipher/portfile.cmake:1 (vcpkg_check_linkage)
  scripts/ports.cmake:141 (include)

**Additional context**
I founded in https://vcpkg.io/en/packages.html that sqlcipher is compatible with x64-windows-static

  Package: sqlcipher:x64-windows-static
  Vcpkg version: 2021-08-03-1a6d67b8150e94b7f473c6ab1c0cfdd794316a64

**Comment by JackBoosY** [comment]
```
CMake Error at scripts/cmake/vcpkg_check_linkage.cmake:61 (message):
Refusing to build unexpected dynamic library against the static CRT.
```
sqlcipher only support dynamic build, please build `sqlcipher:x64-windows` instead.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
