### ISSUE TITLE
Libxml2 (and other ports?) spuriously detects external iconv library

### ISSUE THREAD

**Issue by davidchisnall** [microsoft/vcpkg#19546]
**Describe the bug**

The iconv port checks the `Iconv_IS_BUILT_IN`.  This, according to the CMake documentation, can spuriously return true if iconv is installed separately, even in cases where libc provides the iconv functionality.  As a result, things using the iconv port will link a version of GNU libiconv if it happens to be in one of the default CMake search paths.

I am not sure if this bug is in the iconv or libxml2 port, no work-around that I've tried has worked.

**Environment**
- OS: x86-FreeBSD
- Compiler: clang 10.0.1

This is probably reproduceable on any system where libc provides iconv and you have libiconv installed separately.

**To Reproduce**
1. Install libiconv from a source other than vcpkg somewhere in the default search path (e.g. /usr/local/lib or /usr/lib)
2. ./vcpkg install libxml2
3. See that libxml2 dynamically links to libiconv.so, rather than using the system version.  You can inspect the .pc file to see -liconv.

**Expected behavior**

No additional include or library paths should be exposed when libc provides iconv functionality or, if the libc iconv is not sufficient for a given port then GNU libiconv should be installed by vcpkg.

**Comment by NancyLi1013** [comment]
Hi @davidchisnall 

Thanks for posting this issue.

Since `libiconv `doesn't support non Windows platform in vcpkg. Currently, `libiconv `is only built on Windows platform. For non Windows, there is only vcpk-cmake-wrapper.cmake without any libs.

https://github.com/microsoft/vcpkg/blob/6bc4362fb49e53f1fff7f51e4e27e1946755ecc6/ports/libiconv/portfile.cmake#L1-L6


There is also another issue to track the issue supported on non windows platform. https://github.com/microsoft/vcpkg/issues/11071

**Comment by davidchisnall** [comment]
The problem appears to be the interaction between that wrapper and CMake's iconv detection.  The portfile that you reference installs [`vcpkg-cmake-wrapper.cmake'](https://github.com/microsoft/vcpkg/blob/6bc4362fb49e53f1fff7f51e4e27e1946755ecc6/ports/libiconv/vcpkg-cmake-wrapper.cmake).  This uses CMake's built-in iconv detection.  This sets `Iconv_IS_BUILT_IN` if libc contains iconv support *and* libiconv is not found in any of the normal search locations.  If libiconv is installed system-wide as a dependency of something else, then this detects it and adds `-liconv` to the linker flags.  

It might be possible to work around this by wrapping the `_find_packace` call in something that removes everything except the libc path from the search path.

Note that my build logs for libxml2 (built by vcpkg) contain:

```
-- Performing Test Iconv_IS_BUILT_IN
-- Performing Test Iconv_IS_BUILT_IN - Success
-- Found Iconv: built in to C library
```

Yes -liconv is still added to the linker flags for this port.

**Comment by davidchisnall** [comment]
It looks as if this was fixed on Friday.
