### ISSUE TITLE
`vcpkg env --tools` command broken

### ISSUE THREAD

**Issue by lukka** [microsoft/vcpkg#19552]
**Describe the bug**
`vcpkg env` command is broken when using `--tools` flag.

**Environment**
- OS: Windows

**To Reproduce**
1. Get `vcpkg` sources at commit id eb9cb291669f24b315d6001065e3b1e53e3701b4, and bootstrap.
1. Launch the following:
```powershell
.\vcpkg.exe env --bin --tools --python set
get_directories_non_recursive(D:\repos\vcpkg\installed\x86-windows\tools): The system cannot find the path specified.
```
It repro when the **--tools** is being passed.

**Expected behavior**
It should execute properly the provided command, i.e. `set`

**Additional context**
The error is happening since commit id [dee2b65c7c565697d38b74f26534e62d1f502a89](https://github.com/microsoft/vcpkg-tool/commit/dee2b65c7c565697d38b74f26534e62d1f502a89), where the call to `get_directories_non_recursive` were introduced.

Note that it looks that API triggers the error when a non existing directory is provided. If such direcotry reported in the error is created (e.g., mkdir `installed\x86-windows\tools`), then invoking  `vcpkg env --tools set` just works.

@ras0219-msft @BillyONeal  FYI

**Comment by BillyONeal** [comment]
instances_of_if_it_doesnt_have_tests_it_doesnt_exist.push_back( #19552 );
