### ISSUE TITLE
EXCEPTION='invalid vector<T> subscript'

### ISSUE THREAD

**Issue by stephendeng-888** [Microsoft/vcpkg#1955]
c:\vcpkg>vcpkg install libpng
The following packages will be built and installed:
    libpng:x86-windows
  * zlib:x86-windows
Additional packages (*) will be installed to complete this operation.
Starting package 1/2: zlib:x86-windows
Building package zlib:x86-windows...
A suitable version of cmake was not found (required v3.9.3). Downloading portabl
e cmake v3.9.3...
vcpkg.exe has crashed.
Please send an email to:
    vcpkg@microsoft.com
containing a brief summary of what you were trying to do and the following data
blob:

Version=0.0.91-2017-10-09-d3c45b0668e00703facc86aee998cbfb40fde2ff
EXCEPTION='invalid vector<T> subscript'
CMD=
vcpkg|
install|
libpng|

**Comment by JackBoosY** [comment]
Please open a new issue if this is still a problem for you.
Thx.
