### ISSUE TITLE
failed build of aws-sdk-cpp

### ISSUE THREAD

**Issue by elmendorf** [microsoft/vcpkg#19550]
**Describe the bug**

**Environment**
- OS: Linux Kubuntu 20.04
- Compiler: gcc 9.3.0

**To Reproduce**
1. ./vcpkg install "aws-sdk-cpp[*]"
2. See error
Repro code when

**Expected behavior**
A clean build of the sdk.

**Failure logs** 
config-x64-linux-dbg-err.log

CMake Error at cmake/sdks.cmake:147 (message):
  applicationcostprofiler is required for build, but
  aws-cpp-sdk-applicationcostprofiler directory is missing!
Call Stack (most recent call first):
  CMakeLists.txt:253 (include)

CMakeError.log

Performing C++ SOURCE FILE Test CMAKE_HAVE_LIBC_PTHREAD failed with the following output:
Change Dir: /home/scott/Development/vcpkg/buildtrees/aws-sdk-cpp/x64-linux-dbg/CMakeFiles/CMakeTmp

Run Build Command(s):/home/scott/Development/vcpkg/downloads/tools/ninja-1.10.2-linux/ninja cmTC_4c340 && [1/2] Building CXX object CMakeFiles/cmTC_4c340.dir/src.cxx.o
[2/2] Linking CXX executable cmTC_4c340
FAILED: cmTC_4c340 
: && /usr/bin/c++ -fPIC  CMakeFiles/cmTC_4c340.dir/src.cxx.o -o cmTC_4c340   && :
/usr/bin/ld: CMakeFiles/cmTC_4c340.dir/src.cxx.o: in function `main':
src.cxx:(.text+0x46): undefined reference to `pthread_create'
/usr/bin/ld: src.cxx:(.text+0x52): undefined reference to `pthread_detach'
/usr/bin/ld: src.cxx:(.text+0x5e): undefined reference to `pthread_cancel'
/usr/bin/ld: src.cxx:(.text+0x6f): undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

Source file was:
#include <pthread.h>

static void* test_func(void* data)
{
  return data;
}

int main(void)
{
  pthread_t thread;
  pthread_create(&thread, NULL, test_func, NULL);
  pthread_detach(thread);
  pthread_cancel(thread);
  pthread_join(thread, NULL);
  pthread_atfork(NULL, NULL, NULL);
  pthread_exit(NULL);

  return 0;
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/scott/Development/vcpkg/buildtrees/aws-sdk-cpp/x64-linux-dbg/CMakeFiles/CMakeTmp

Run Build Command(s):/home/scott/Development/vcpkg/downloads/tools/ninja-1.10.2-linux/ninja cmTC_a52f4 && [1/2] Building CXX object CMakeFiles/cmTC_a52f4.dir/CheckFunctionExists.cxx.o
[2/2] Linking CXX executable cmTC_a52f4
FAILED: cmTC_a52f4 
: && /usr/bin/c++ -fPIC -DCHECK_FUNCTION_EXISTS=pthread_create  CMakeFiles/cmTC_a52f4.dir/CheckFunctionExists.cxx.o -o cmTC_a52f4  -lpthreads && :
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

**Additional context**

**Comment by NancyLi1013** [comment]
Hi @elmendorf 

Thanks for posting this issue. Seems like a port bug in current version now. I will try to update `aws-sdk-cpp` to the latest version to confirm if this still exists.

Related issue from upstream: https://github.com/aws/aws-sdk-cpp/issues/1717

**Comment by dg0yt** [comment]
> CMake Error at cmake/sdks.cmake:147 (message):
> applicationcostprofiler is required for build, but
> aws-cpp-sdk-applicationcostprofiler directory is missing!

`aws-sdk-cpp[applicationcostprofiler]` builds successfully on Ubuntu 18.04. I guess this was fixed by the port update to 1.9.96 (#20033) on Sep 15.

**Comment by Adela0814** [comment]
@elmendorf Have you tried PR #20033, does it solve your problem?

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
