### ISSUE TITLE
Better VS triplet integration / consistent compilation

### ISSUE THREAD

**Issue by Fleischner** [Microsoft/vcpkg#1956]
- How is it possible to fine tune visual studio compiler options in the triplet (and inspect the resulting options)?
- What is correct way to compile in vs with the same options as in the (fine tuned) triplet.

I have a solution with multiple projects that use several libraries from vcpkg (using integrate).
Currently I'm setting up shared project property sheets for out solution (e.g. https://manski.net/2012/01/sharing-project-properties-in-visual-c/ ). But how can we ensure consistent compilation?

We would like to be able to easily fine tune compiler options in the vcpkg triplet (optimization flags, debug format, etc) and then just use the exact same options to build out solution in vs. At best integrate command should just make the correct property sheets (.props) available automatically. Is this possible?

The easiest way would be, either to allow the triplet configuration being created from a property sheet.
Or otherwise generate a property sheet from the triplet that can be used in vs.

**Comment by qis** [comment]
Example from what I use at work for static libraries with dynamic CRT (`vcpkg\triplets\x64-windows-native.cmake`):

```cmake
set(VCPKG_TARGET_ARCHITECTURE x64) 
set(VCPKG_CRT_LINKAGE dynamic) 
set(VCPKG_LIBRARY_LINKAGE static) 
```

Projects are configured with the following command:

```cmd
cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_CONFIGURATION_TYPES="Debug;Release" ^
  -DCMAKE_TOOLCHAIN_FILE=C:/Libraries/vcpkg/scripts/buildsystems/vcpkg.cmake ^
  -DVCPKG_TARGET_TRIPLET=x64-windows-native
```

On a side note: Is there a reason, why this triplet is not included by default in vcpkg?

**Comment by kklouzal** [comment]
I use a standard set of compiler options across all my projects and all libraries I build to use in my projects.
```General:
Whole Program Optimization - Use Link Time Code Generation

C/C++:
Optimization - Maximize Speed - /O2
Inline Function Expansion - Any Suitable - /Ob2
Enable Intrinsic Functions - Yes - /Oi
Favor Size Or Speed - Favor fast code - /Ot
Enable String Pooling - Yes - /GF
Enable Function-Level Linking - Yes - /Gy
Security Check - Disable Security Check - /GS-

Linker:
Link Time Code Generation - Use Link Time Code Generation - /LTCG
```

It seems as though I cannot ensure libraries being built with VCPKG are using these options. Is there a way to set these as the default and even override them if the library specifies something else?

**Comment by Fleischner** [comment]
I close this issue, as build options can be set in the tool chain file now. Also vcpkg promotes libraries not to hard-code those options.
