### ISSUE TITLE
[vcpkg-tools] update scons to 4.2.0

### ISSUE THREAD

**Issue by xavier2k6** [microsoft/vcpkg#19564]
Library name: **scons**

New version number: **4.2.0**

Other information that may be useful (release notes, etc...)

https://github.com/SCons/scons/releases/latest

**Comment by JonLiu1993** [comment]
@xavier2k6 ,I duplicated this issue to issue #19568,let's update vcpkg-tools together in issue #19568,I temporarily close this issue
