### ISSUE TITLE
[PowerShell] update to 7.1.4

### ISSUE THREAD

**Issue by xavier2k6** [microsoft/vcpkg#19569]
Library name: **PowerShell**

New version number: **7.1.4**

Other information that may be useful (release notes, etc...)
https://github.com/PowerShell/PowerShell/releases/latest

**Comment by JonLiu1993** [comment]
@xavier2k6 ,I duplicated this issue to issue #19568,let's update vcpkg-tools together in issue #19568,I temporarily close this issue

**Comment by xavier2k6** [comment]
Updated in PR https://github.com/microsoft/vcpkg/pull/20064
