### ISSUE TITLE
[vcpkg-tools] update many vcpkg tools

### ISSUE THREAD

**Issue by xavier2k6** [microsoft/vcpkg#19568]
Reference:

```
/scripts/cmake/vcpkg_find_acquire_program.cmake
/scripts/vcpkgTools.xml
```

(In case ports should be updated in conjunction with their respective tools, small example of reference)
```
/ports/vcpkg-tool-nodejs/vcpkg.json
/ports/vcpkg-tool-meson/vcpkg.json
/ports/tool-meson/vcpkg.json
/versions/baseline.json
/versions/v-/vcpkg-tool-nodejs.json
/versions/v-/vcpkg-tool-meson.json
/versions/t-/tool-meson.json
```
____

Tool name: **WiX Toolset** (DARK Decompiler)

New version number: **4.0.4**
Other information that may be useful (release notes, etc...)
https://wixtoolset.org/releases/
https://github.com/wixtoolset/wix4/releases
https://wixtoolset.org/docs/releasenotes/#v4
____

Tool name: **NuGet**

New version number: **6.9.1**
Other information that may be useful (release notes, etc...)
https://www.nuget.org/downloads
____

Tool name: **meson**

New version number: **1.3.2**
Other information that may be useful (release notes, etc...)
https://github.com/mesonbuild/meson/tags
____

Tool name: **Go**

New version number: **1.22.0**
Other information that may be useful (release notes, etc...)
https://github.com/golang/go/tags
https://golang.org/doc/go1.22
https://go.dev/blog/
https://go.dev/blog/go1.22
https://golang.org/
____

Tool name: **scons**

New version number: **4.6.0**
Other information that may be useful (release notes, etc...)
https://github.com/SCons/scons/releases/latest
____

Tool name: **LLVM**

New version number: **17.0.6**
Other information that may be useful (release notes, etc...)
https://github.com/llvm/llvm-project/releases/latest
____

Tool name: **Git for Windows**

New version number: **2.43.0**
Other information that may be useful (release notes, etc...)
https://github.com/git-for-windows/git/releases/latest
____

Tool name: **aria2**

New version number: **1.37.0**
Other information that may be useful (release notes, etc...)
https://github.com/aria2/aria2/releases/latest
____

Tool name: **coscli**

New version number: **0.19.0**
Other information that may be useful (release notes, etc...)
https://github.com/tencentyun/coscli/releases/latest
____

Tool name: **installerbase**

New version number: **4.6.1**
Other information that may be useful (release notes, etc...)
https://download.qt.io/official_releases/qt-installer-framework/4.6.1/
____

Tool name: **gsutil**

New version number: **5.27**
Other information that may be useful (release notes, etc...)
https://github.com/GoogleCloudPlatform/gsutil/tags
https://storage.googleapis.com/pub/gsutil_5.27.ReleaseNotes.txt
____

Tool name: **bazel**

New version number: **7.0.2**
Other information that may be useful (release notes, etc...)
https://github.com/bazelbuild/bazel/releases/latest
____

Tool name: **doxygen**

New version number: **1.10.0**
Other information that may be useful (release notes, etc...)
https://github.com/doxygen/doxygen/tags
https://www.doxygen.nl/manual/changelog.html
____

Tool name: **CMake** from Kitware

New version number: **3.28.3**
Other information that may be useful (release notes, etc...)
https://github.com/Kitware/CMake/tags
https://cmake.org/download/#:~:text=Latest%20Release
https://cmake.org/cmake/help/v3.28/release/3.28.html#cmake-3-28-release-notes
____

Tool name: **Rubyinstaller**

New version number: **3.2.3-1**
Other information that may be useful (release notes, etc...)
https://www.ruby-lang.org/en/downloads/
https://github.com/oneclick/rubyinstaller2/tags
____

Tool name: **PowerShell**

New version number: **7.4.1**
Other information that may be useful (release notes, etc...)
https://github.com/PowerShell/PowerShell/releases/latest
____

Tool name: **ninja**

New version number: **1.11.1**
Other information that may be useful (release notes, etc...)
https://github.com/ninja-build/ninja/releases
https://ninja-build.org/
https://groups.google.com/g/ninja-build/c/R2oCyDctDf8/m/-U94Y5I8AgAJ
____

Tool name: **7-zip**

New version number: **23.01**
Other information that may be useful (release notes, etc...)
https://7-zip.org/
https://www.7-zip.org/download.html
https://sourceforge.net/p/sevenzip/discussion/45797/thread/3f550826d8/
____

Tool name: **Python3**

New version number: **3.12.2**
Other information that may be useful (release notes, etc...)
https://www.python.org/
https://www.python.org/ftp/python/3.12.2/
https://www.python.org/downloads/release/python-3122/
https://docs.python.org/release/3.12.2/whatsnew/changelog.html#python-3-12-2-final
____

Tool name: **node**

New version number: **20.11.1**
Other information that may be useful (release notes, etc...)
https://nodejs.org/dist/v20.11.1/
https://nodejs.org/en/download/
https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V20.md#20.11.1
____

Tool name: **vswhere**

New version number: **3.1.7**
Other information that may be useful (release notes, etc...)
https://github.com/Microsoft/vswhere/releases
____

Tool name: **NASM**

New version number: **2.16.01**
Other information that may be useful (release notes, etc...)
https://www.nasm.us/
https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/
https://nasm.us/doc/nasmdocc.html
____

Tool name: **jom**

New version number: **1.1.4**
Other information that may be useful (release notes, etc...)
https://download.qt.io/official_releases/jom/
https://mirrors.ukfast.co.uk/sites/qt.io/official_releases/jom/changelog.txt
https://mirrors.ocf.berkeley.edu/qt/official_releases/jom/
https://mirrors.ocf.berkeley.edu/qt/official_releases/jom/changelog.txt
____

Tool name: **Strawberry Perl**

New version number: **5.38.2.2**
Other information that may be useful (release notes, etc...)
https://github.com/StrawberryPerl/Perl-Dist-Strawberry/releases

**Comment by xavier2k6** [comment]
@JonLiu1993 Are these tools going to be updated/acted on anytime soon? I appreciate, that you may be busy.

**Comment by JonLiu1993** [comment]
> 

Thanks for your understanding, we will update these tools together at the right time

**Comment by xavier2k6** [comment]
@JackBoosY @JonLiu1993 Ping.

**Comment by JackBoosY** [comment]
We'll be updating the tools, but it's a huge undertaking as some ports will always fail.

**Comment by xavier2k6** [comment]
@JonLiu1993 Can any of these be updated now?, I understand `Powershell` probably can't in order to maintain Windows 7 Support.

**Comment by dg0yt** [comment]
Some isolated updates should be facilitated by #30780.
But the center of activity moved to #31748.

**Comment by xavier2k6** [comment]
added jom to list

**Comment by xavier2k6** [comment]
added strawberry perl to list
