### ISSUE TITLE
[vcpkg-tools] update meson to 0.58.2

### ISSUE THREAD

**Issue by xavier2k6** [microsoft/vcpkg#19565]
Library name: **meson**

New version number: **0.58.2**

Other information that may be useful (release notes, etc...)

https://github.com/mesonbuild/meson/releases/latest

**Comment by JonLiu1993** [comment]
@xavier2k6 ,I duplicated this issue to issue #19568,let's update vcpkg-tools together in issue #19568,I temporarily close this issue
