### ISSUE TITLE
why i fail to run vcpkg on userland

### ISSUE THREAD

**Issue by A91K3C1l** [microsoft/vcpkg#19562]
I want to ask why I can't execute the command 
./vcpkg integrate install
Returns error 
Environment variable VCPKG_FORCE_SYSTEM_BINARIES must be set on arm, s390x, and ppc64le platforms.

Saya menggunakan aarch64 android 6.0
Thank
![Screenshot_2021-08-14-18-03-16-98](https://user-images.githubusercontent.com/59974186/129444375-8370aaee-de3d-4972-89f3-753a5f126c53.png)

**Comment by NancyLi1013** [comment]
Hi @A91K3C1l 

Thanks for posting this issue.

Could you please help confirm which platform you build on your machine?

`Environment variable VCPKG_FORCE_SYSTEM_BINARIES must be set on arm, s390x, and ppc64le platforms.`

Please set `VCPKG_FORCE_SYSTEM_BINARIES `as Environment variable if your platform is one of them.

**Comment by NancyLi1013** [comment]
Closing this issue for now since there is no active thread for a long time. Please feel free to reopen this issue if you can provide above information.
