### ISSUE TITLE
[LLVM] update to 12.0.1

### ISSUE THREAD

**Issue by xavier2k6** [microsoft/vcpkg#19570]
Library name: **LLVM**

New version number: **12.0.1**

Other information that may be useful (release notes, etc...)
https://github.com/llvm/llvm-project/releases/latest

**Comment by JonLiu1993** [comment]
@xavier2k6 ,Is this issue a port update or a tool update for LLVM?

**Comment by xavier2k6** [comment]
tool update

FYI - There is no option/category for tool updates when creating an issue.

**Comment by JonLiu1993** [comment]
@xavier2k6 ,I duplicated this issue to issue #19568,let's update vcpkg-tools together in issue #19568,I temporarily close this issue
