### ISSUE TITLE
[blas:x86-windows] build failure

### ISSUE THREAD

**Issue by ign4si** [microsoft/vcpkg#19586]
**Host Environment**
- OS: Windows
- Compiler: revision

**To Reproduce**
`./vcpkg install armadillo`

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

C:\WINDOWS\system32>vcpkg install armadillo
Computing installation plan...
The following packages will be built and installed:
    armadillo[core]:x86-windows -> 10.4.0
  * blas[core]:x86-windows -> 1
  * lapack[core]:x86-windows -> 3#1
  * lapack-reference[blas-select,core,noblas]:x86-windows -> 3.8.0#5
  * vcpkg-gfortran[core]:x86-windows -> 3
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x86-windows...
Could not locate cached archive: C:\Users\NachLobat\AppData\Local\vcpkg\archives\aa\aab6ef918965c1a862ae711457aaa6de69d9453dea27b145271b8dde32d1f091.zip
Could not locate cached archive: C:\Users\NachLobat\AppData\Local\vcpkg\archives\71\712b9c03c737a5ff0b4d629e62a22279cf14620c99528059f6e1abb6ab9db9d4.zip
Could not locate cached archive: C:\Users\NachLobat\AppData\Local\vcpkg\archives\dc\dcf6e143b7818ed8ca2a53023240f766bc28c6b58efc591778f3b800a29261bd.zip
Could not locate cached archive: C:\Users\NachLobat\AppData\Local\vcpkg\archives\f4\f40049609748b72e35056b481caa461d70c87b93f95068d243b4147707337a09.zip
Could not locate cached archive: C:\Users\NachLobat\AppData\Local\vcpkg\archives\86\86d442bb9940f7530b4f0aeb82736d3d620ce706e26df477d10481b676377c0e.zip
Starting package 1/5: blas:x86-windows
Building package blas[core]:x86-windows...
-- Found external ninja('1.10.2').
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: ninja -v
    Working Directory: C:/Users/Nach Lobat/vcpkg/buildtrees/blas/x86-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\Users\Nach Lobat\vcpkg\buildtrees\blas\config-x86-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:356 (vcpkg_execute_required_process)
  ports/blas/portfile.cmake:4 (vcpkg_configure_cmake)
  scripts/ports.cmake:141 (include)

Error: Building package blas:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: blas:x86-windows
  Vcpkg version: 2021-08-12-85ab112d5ee102bc6eac8cdbbfdd173a71374e04

Additionally, attach any relevant sections from the log files above.

**Additional context**
I'm trying to install Armadillo in order to work with matrices. It needs LAPACK and BLAS. I was struggling 7 hours but failed. If someone wants to help me we can make join a discord channel or something and do voice chat. 
[config-x86-windows-out.log](https://github.com/microsoft/vcpkg/files/6988845/config-x86-windows-out.log)

**Comment by Neumann-A** [comment]
Remove the space in the path (within the user name).

**Comment by ign4si** [comment]
> Remove the space in the path (within the user name).

Mmm I really don't know how to do that. Should I change my user name?

**Comment by ign4si** [comment]
> Remove the space in the path (within the user name).

Maybe you meant in the ticket.

**Comment by Neumann-A** [comment]
> Mmm I really don't know how to do that. Should I change my user name?

Just move vcpkg somewhere without a space in the path?

**Comment by ign4si** [comment]
> > Mmm I really don't know how to do that. Should I change my user name?
> 
> Just move vcpkg somewhere without a space in the path?

Apparently I just delete the complete vcpkg folder and re installed in C:\\. It worked for BLAS which is good.! Now it is LAPACK turn.
![image](https://user-images.githubusercontent.com/66034070/129492670-463f062a-19c3-42e7-aebf-57eb7bd779b1.png)
Hope it works

**Comment by ign4si** [comment]
> > Mmm I really don't know how to do that. Should I change my user name?
> 
> Just move vcpkg somewhere without a space in the path?

ALEXANDER I LOVE YOU I'M SO GRATEFUL FOR YOUR HELP. THANK YOU VERY MUCH. HOPE I MEET YOU SOMEDAY BECAUSE YOU ARE AMAZING.
