### ISSUE TITLE
build failed with ffmpeg-uwp arm package

### ISSUE THREAD

**Issue by touseefbsb** [Microsoft/vcpkg#1958]
**Steps To Reproduce**

git clone https://github.com/khouzam/vcpkg -b ffmpeg-uwp

cd vcpkg
bootstrap-vcpkg.bat

vcpkg install ffmpeg:x86-uwp ffmpeg:x64-uwp ffmpeg:arm-uwp

x86 and x64 packages build successfully, error occurred with arm package.

**error**

CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:43 (message):
    Command failed: C:/vcpkg/downloads/tools/msys2/msys64/usr/bin/bash.exe;--noprofile;--norc;C:/vcpkg/ports/ffmpeg\build.sh;C:/vcpkg/buildtrees/ffmpeg/arm-uwp-rel;C:/vcpkg/buildtrees/ffmpeg/src/ffmpeg-3.2.4;C:/vcpkg/packages/ffmpeg_arm-uwp;--disable-ffmpeg --disable-ffprobe --disable-doc --enable-debug --enable-runtime-cpudetect --disable-programs --enable-cross-compile --target-os=win32 --arch=arm --extra-cflags=-DWINAPI_FAMILY=WINAPI_FAMILY_APP --extra-cflags=-D_WIN32_WINNT=0x0A00 --disable-static --enable-shared --extra-ldflags=-APPCONTAINER --extra-ldflags=WindowsApp.lib  --extra-cflags=-MD --extra-cxxflags=-MD
    Working Directory: C:/vcpkg/buildtrees/ffmpeg/arm-uwp-rel
    See logs for more information:
      C:\vcpkg\buildtrees\ffmpeg\build-arm-uwp-rel-out.log
      C:\vcpkg\buildtrees\ffmpeg\build-arm-uwp-rel-err.log

Call Stack (most recent call first):
  ports/ffmpeg/portfile.cmake:74 (vcpkg_execute_required_process)
  scripts/ports.cmake:73 (include)

Error: Building package ffmpeg:arm-uwp failed with: BUILD_FAILED

  **Package: ffmpeg:arm-uwp
  Vcpkg version: 0.0.81-9fe35b0d4d0cf4622f56013f9ba9a8a061912548**

**Note**
I have attached the log files as well.

[build-arm-uwp-rel-err.log](https://github.com/Microsoft/vcpkg/files/1377149/build-arm-uwp-rel-err.log)
[build-arm-uwp-rel-out.log](https://github.com/Microsoft/vcpkg/files/1377150/build-arm-uwp-rel-out.log)

**Comment by JackBoosY** [comment]
Hi @touseefbsb , thanks for reporting this issue!
ffmpeg-uwp works good in latest version(4.1-1), plz update vcpkg and rebuild it.
Thx.
