### ISSUE TITLE
gsl library build failure

### ISSUE THREAD

**Issue by cbtang01** [microsoft/vcpkg#19594]
**Host Environment**
- OS: Windows 10
- Compiler: Visual Studio 2019

**To Reproduce**
1. git clone https://github.com/microsoft/vcpkg.git
2. cd vcpkg
3. .\bootstrap-vcpkg.bat
4. .\vcpkg integrate install
5. .\vcpkg install gsl gsl:x64-windows

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
Computing installation plan...
A suitable version of cmake was not found (required v3.21.1). Downloading portable cmake v3.21.1...
Downloading cmake...
  https://github.com/Kitware/CMake/releases/download/v3.21.1/cmake-3.21.1-windows-i386.zip -> C:\Users\Charlie\OneDrive\QIjob\QIQA\Lambda Calculus & semantics\Haskell\HaskellWikibook\vcpkg\downloads\cmake-3.21.1-windows-i386.zip
Extracting cmake...
A suitable version of 7zip was not found (required v19.0.0). Downloading portable 7zip v19.0.0...
Downloading 7zip...
  https://www.7-zip.org/a/7z1900-x64.msi -> C:\Users\Charlie\OneDrive\QIjob\QIQA\Lambda Calculus & semantics\Haskell\HaskellWikibook\vcpkg\downloads\7z1900-x64.msi
Extracting 7zip...
The following packages will be built and installed:
    gsl[core]:x64-windows -> 2.6#1
    gsl[core]:x86-windows -> 2.6#1
Warning: The following VS instances are excluded because the English language pack is unavailable.
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
Please install the English language pack.
Detecting compiler hash for triplet x64-windows...
A suitable version of git was not found (required v2.32.0). Downloading portable git v2.32.0...
Downloading git...
  https://github.com/git-for-windows/git/releases/download/v2.32.0.windows.2/PortableGit-2.32.0.2-32-bit.7z.exe -> C:\Users\Charlie\OneDrive\QIjob\QIQA\Lambda Calculus & semantics\Haskell\HaskellWikibook\vcpkg\downloads\PortableGit-2.32.0.2-32-bit.7z.exe       
Extracting git...
A suitable version of powershell-core was not found (required v7.1.3). Downloading portable powershell-core v7.1.3...
Downloading powershell-core...
  https://github.com/PowerShell/PowerShell/releases/download/v7.1.3/PowerShell-7.1.3-win-x86.zip -> C:\Users\Charlie\OneDrive\QIjob\QIQA\Lambda Calculus & semantics\Haskell\HaskellWikibook\vcpkg\downloads\PowerShell-7.1.3-win-x86.zip
Extracting powershell-core...
Detecting compiler hash for triplet x86-windows...
Could not locate cached archive: C:\Users\Charlie\AppData\Local\vcpkg\archives\7c\7cd588fa8d5ed04b734747033dbe52f14f034c595a823d5110060af37ec35f84.zip
Could not locate cached archive: C:\Users\Charlie\AppData\Local\vcpkg\archives\b9\b967dd41ca29fc9c849dea991970952920e1923290c171079a24a2d9bc425e92.zip
Starting package 1/2: gsl:x64-windows
Building package gsl[core]:x64-windows...
-- Downloading https://ftp.gnu.org/gnu/gsl/gsl-2.6.tar.gz;https://www.mirrorservice.org/sites/ftp.gnu.org/gnu/gsl/gsl-2.6.tar.gz -> gsl-2.6.tar.gz...
-- Extracting source C:/Users/Charlie/OneDrive/QIjob/QIQA/Lambda Calculus & semantics/Haskell/HaskellWikibook/vcpkg/downloads/gsl-2.6.tar.gz
-- Applying patch 0001-configure.patch
-- Applying patch 0002-add-fp-control.patch
-- Using source at C:/Users/Charlie/OneDrive/QIjob/QIQA/Lambda Calculus & semantics/Haskell/HaskellWikibook/vcpkg/buildtrees/gsl/src/gsl-2-fb511965d5.clean
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: ninja -v
    Working Directory: C:/Users/Charlie/OneDrive/QIjob/QIQA/Lambda Calculus & semantics/Haskell/HaskellWikibook/vcpkg/buildtrees/gsl/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\Users\Charlie\OneDrive\QIjob\QIQA\Lambda Calculus & semantics\Haskell\HaskellWikibook\vcpkg\buildtrees\gsl\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:356 (vcpkg_execute_required_process)
  scripts/ports.cmake:141 (include)

Error: Building package gsl:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: gsl:x64-windows
  Vcpkg version: 2021-08-12-85ab112d5ee102bc6eac8cdbbfdd173a71374e04

Additionally, attach any relevant sections from the log files above.

-Please attach any additional failure logs mentioned in the console output. (see below)
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/6991444/config-x64-windows-out.log)

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.
PS C:\Users\Charlie\OneDrive\QIjob\QIQA\Lambda Calculus & semantics\Haskell\HaskellWikibook\vcpkg> .\vcpkg update
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.
PS C:\Users\Charlie\OneDrive\QIjob\QIQA\Lambda Calculus & semantics\Haskell\HaskellWikibook\vcpkg> git pull
Already up to date.

**Comment by dg0yt** [comment]
> `C:\Users\Charlie\OneDrive\QIjob\QIQA\Lambda Calculus & semantics\Haskell\HaskellWikibook\vcpkg\...` 

Please use a path without space, and also without `&`, for vcpkg. Some tools can't handle it correctly.

**Comment by cbtang01** [comment]
Thanks.  I used a pathname without space and & sign, but it still didn't work.  Then I noticed a yellow-colored warning in the build message from console output: I did not have English community package of Visual Studio 2019.  So, I fixed this from Visual Studio Installer and it worked.
