### ISSUE TITLE
[icu] build failure - resolved - Antivirus blocking gentest.exe

### ISSUE THREAD

**Issue by Qbort** [microsoft/vcpkg#19596]
**Host Environment**
- OS: Windows 10
- Compiler: unsure (assume gcc?)

**To Reproduce**
`.\vcpkg install icu:x64-windows`

**Failure logs** 

```
PS C:\src\vcpkg_microsoft> .\vcpkg install icu:x64-windows
Computing installation plan...
The following packages will be built and installed:
    icu[core]:x64-windows -> 69.1#11
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\Roberto\AppData\Local\vcpkg\archives\95\95c2f1f57e70cc253b430b0505d6634e8ebc27579efdf1cb72ab723925bffa62.zip
Starting package 1/1: icu:x64-windows
Building package icu[core]:x64-windows...
-- Using C:/src/vcpkg_microsoft/downloads/icu4c-69_1-src.tgz
-- Extracting source C:/src/vcpkg_microsoft/downloads/icu4c-69_1-src.tgz
-- Applying patch C:/src/vcpkg_microsoft/ports/icu/disable-escapestr-tool.patch
-- Applying patch C:/src/vcpkg_microsoft/ports/icu/remove-MD-from-configure.patch
-- Applying patch C:/src/vcpkg_microsoft/ports/icu/fix_parallel_build_on_windows.patch
-- Applying patch C:/src/vcpkg_microsoft/ports/icu/fix-extra.patch
-- Using source at C:/src/vcpkg_microsoft/buildtrees/icu/src/c-69_1-src-78c1b28057.clean
-- Downloading https://www.python.org/ftp/python/3.9.6/python-3.9.6-embed-amd64.zip -> python-3.9.6-embed-amd64.zip...
-- Found external ninja('1.10.2').
-- Getting CMake variables for x64-windows
-- Using msys root at C:/src/vcpkg_microsoft/downloads/tools/msys2/703e5aa15d402568
-- Using msys root at C:/src/vcpkg_microsoft/downloads/tools/msys2/aa5af7b2aa7e90e8
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
-- Installing x64-windows-dbg
-- Restarting Build without parallelism because memory exceeded
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:155 (message):
    Command failed: C:/src/vcpkg_microsoft/downloads/tools/msys2/703e5aa15d402568/usr/bin/make.exe -j 5 --trace -f Makefile install DESTDIR=/C/src/vcpkg_microsoft/packages/icu_x64-windows
    Working Directory: C:/src/vcpkg_microsoft/buildtrees/icu/x64-windows-dbg
    See logs for more information:
      C:\src\vcpkg_microsoft\buildtrees\icu\install-x64-windows-dbg-out.log
      C:\src\vcpkg_microsoft\buildtrees\icu\install-x64-windows-dbg-err.log
      C:\src\vcpkg_microsoft\buildtrees\icu\install-x64-windows-dbg-out-1.log
      C:\src\vcpkg_microsoft\buildtrees\icu\install-x64-windows-dbg-err-1.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_make.cmake:210 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_make.cmake:26 (vcpkg_build_make)
  ports/icu/portfile.cmake:137 (vcpkg_install_make)
  scripts/ports.cmake:141 (include)


Error: Building package icu:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: icu:x64-windows
  Vcpkg version: 2021-08-12-85ab112d5ee102bc6eac8cdbbfdd173a71374e04
  ```
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/6992068/install-x64-windows-dbg-out.log)
[install-x64-windows-dbg-out-1.log](https://github.com/microsoft/vcpkg/files/6992069/install-x64-windows-dbg-out-1.log)
[install-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/6992070/install-x64-windows-dbg-err.log)
[install-x64-windows-dbg-err-1.log](https://github.com/microsoft/vcpkg/files/6992067/install-x64-windows-dbg-err-1.log)

**Additional context**
Already tried `.\vcpkg update` and also cloning the repository again into an empty folder.

**Comment by NancyLi1013** [comment]
Hi @Qbort 

Thanks for posting this issue.

From install-x64-windows-dbg-out.log, I found the errors like this:
```
Makefile:69: update target 'gentest.exe' due to: genres32.o gentest.o
LINK.EXE -subsystem:console -LC:/src/vcpkg_microsoft/installed/x64-windows/debug/lib -LC:/src/vcpkg_microsoft/installed/x64-windows/debug/lib/manual-link  -nologo -out:gentest.exe genres32.o gentest.o ../../tools/ctestfw/icutestd.lib ../../lib/icutud.lib ../../lib/icuind.lib ../../lib/icuucd.lib ../../lib/icudtd.lib advapi32.lib  
Microsoft (R) Incremental Linker Version 14.28.29914.0
Copyright (C) Microsoft Corporation.  All rights reserved.

LINK : warning LNK4044: unrecognized option '/LC:/src/vcpkg_microsoft/installed/x64-windows/debug/lib'; ignored
LINK : warning LNK4044: unrecognized option '/LC:/src/vcpkg_microsoft/installed/x64-windows/debug/lib/manual-link'; ignored
LINK : fatal error LNK1104: cannot open file 'gentest.exe'
```
Is `gentest.exe` in _C:/src/vcpkg_microsoft/installed/x64-windows/tools/icu/bin/_ or _C:/src/vcpkg_microsoft/buildtress/icu/x64-windows-dbg/tools/gentest_ on your machine?

**Comment by Qbort** [comment]
@NancyLi1013 The folder `C:/src/vcpkg_microsoft/installed/x64-windows/tools/icu/bin/` does not exist (assume because the package has not yet succeeded to build). 

In contrast, in the `C:\src\vcpkg_microsoft\buildtrees\icu\x64-windows-dbg\tools\gentest` folder, i have the following files (no `gentest.exe`):
![image](https://user-images.githubusercontent.com/16581353/129709767-9c24fc5f-afc5-4cef-aca3-3dff20dc41dc.png)

**Comment by sfhacker** [comment]
Are we STILL having issues with icu? I thought all the 'recurring' issues were fixed!
We haven't had any issues so far.
@Qbort Wonder how we can reproduce this issue locally?

**Comment by Qbort** [comment]
I'm not sure what to suggest. I have tried even just cloning vcpkg into an empty folder, bootstrapping and then trying to install. The only thing I have in my environment is `VCPKG_DEFAULT_TRIPLET=x64-windows` as a user environment variable. I can't think what else I might have that prevents me from installing.

The below would be steps to reproduce:
```
 git clone https://github.com/microsoft/vcpkg
.\vcpkg\bootstrap-vcpkg.bat
.\vcpkg\vcpkg install icu
```

**Comment by Qbort** [comment]
@sfhacker @NancyLi1013 I've done some additional investigation because I know that I previously was able to install icu without issues (somewhere around the begining of this year). My computer is quite slow so it will take me several days to fully investigate the commit that caused the problem, but for now I can say that icu is building fine as of commit 7944ed328a10833c4a6b3ab3ff947b2a0b9f8d9b (15 Dec 2020).

Something between there and now has broken the build for x64-windows. I'll keep investigating and report which commits within the icu package succeed and which ones fail. Hopefully that helps somehow.

**Comment by sfhacker** [comment]
@Qbort Have you tried some of the official binaries? [1]


[1] https://github.com/unicode-org/icu/releases/tag/release-69-1

**Comment by NancyLi1013** [comment]
@Qbort 

Could you please help check if there is any Antivirus software on your machine?

If you installed, please disable it and try to rebuild this.

**Comment by Qbort** [comment]
@NancyLi1013 apologies for the delay. Thank you for the suggestion. Indeed it appears my antivirus was moving `gentest.exe` to quarantine:

![image](https://user-images.githubusercontent.com/16581353/130477874-2fbf8f0c-b805-4dd4-ae49-9b2cc05eb071.png)

I also had to delete the contents of download and build-trees folders and restart the computer (as it was still failing due to lack of memory - similar to#17576)

**Comment by NancyLi1013** [comment]
Thanks for your feedback. Please free up some space to rebuild if it is due to lack of memory.
