### ISSUE TITLE
[New Port Request] ecal

### ISSUE THREAD

**Issue by niclar** [microsoft/vcpkg#19597]
Library name:
ecal

Library description:
The enhanced communication abstraction layer (eCAL) is a middleware that enables scalable, high performance interprocess communication on a single computer node or between different nodes in a computer network. eCAL is designed for typical cloud computing scenarios where different processes exchange there I/O’s using a publish/subscribe pattern.

Source repository URL:
https://github.com/continental/ecal

Project homepage (if different from the source repository):
https://continental.github.io/ecal/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
-The build is a find_package recursion nightmare

**Comment by niclar** [comment]
The windows version now work, linux remaining...  then I'll file a PR

**Comment by PhoebeHui** [comment]
Please reopen this issue and continue PR https://github.com/microsoft/vcpkg/pull/19802 If you wish to add this port in the future.
