### ISSUE TITLE
[freeimage] FreeImage.dll missing version information

### ISSUE THREAD

**Issue by the-nerbs** [microsoft/vcpkg#19605]
While integrating with FreeImage as built from `vcpkg install freeimage`, I noticed that the DLL is not built with version information. This information does exist in the binaries available from the FreeImage homepage, and the .rc file that supplies this information exists in the source zip that the port downloads to build, so I suspect its omission here was a mistake.

**Proposed solution**
I believe the fix is as simple as adding the .rc file to the DLL's sources in the port's CMakeLists.txt as such:
```cmake
# change this line: 
add_library(FreeImage ${SRCS} ${PRIVATE_HEADERS} ${PUBLIC_HEADERS})

# to this:
add_library(FreeImage ${SRCS} ${PRIVATE_HEADERS} ${PUBLIC_HEADERS}
                      ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage.rc)
```

This mirrors what is currently done for FreeImagePlus.dll ([link](https://github.com/microsoft/vcpkg/blob/99e06a64eca28a9af2b9e5544459e60fa40d19fd/ports/freeimage/CMakeLists.txt#L117-L120)).

**Additional context**
The use-case that led me to find this is that I am trying to include this DLL in an MSI-based installer. In upgrade scenarios, the unversioned DLL fails to install correctly due to the [file versioning rules](https://docs.microsoft.com/en-us/windows/win32/msi/file-versioning-rules).

If this is not an intended use case, or if the omission of this information was intentional, then I can almost certainly find a different solution for my needs.

**Comment by NancyLi1013** [comment]
Hi @the-nerbs 

Thanks for posting this issue. I will submit a PR to fix it later.

**Comment by the-nerbs** [comment]
Thanks for the fast response @NancyLi1013 !

I pulled the changes from your PR and confirmed that they resolve the issue I was seeing. If there's anything else I need to do, please let me know. Thanks!

**Comment by NancyLi1013** [comment]
Thanks for your help @the-nerbs. Currently, there is nothing needs to be done now. Let's wait for the PR merged.
