### ISSUE TITLE
[suggestion] Separate Download (Source) Step

### ISSUE THREAD

**Issue by podsvirov** [microsoft/vcpkg#1960]
The project actively uses caching results at each stage of building a binary package.

What about separating the step of getting the source code?

For example:
- Download the source codes of the required packages.
- Go to drink tea or change the computer to a more powerful one.
- Build and install packages.
- Export the results and continue to work in the team.

**Comment by cmpute** [comment]
Vote for this! Downloading can be quite long using cmake. I hope that using alternative downloading tools will be possible.

**Comment by NancyLi1013** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen.
