### ISSUE TITLE
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):     Command failed: ninja -v                                                                                                

### ISSUE THREAD

**Issue by mukeshhope** [microsoft/vcpkg#19609]
**Host Environment**
- OS: Windows 10 enterprise

**To Reproduce**
vcpkg.exe install azure-iot-sdk-c:x64-windows

**Failure logs** 
```
Computing installation plan...                                                                                          
The following packages will be built and installed:
  * azure-c-shared-utility[core]:x64-windows -> 2020-12-09#1
    azure-iot-sdk-c[core]:x64-windows -> 2020-12-09#2
  * azure-macro-utils-c[core]:x64-windows -> 2020-06-17#2
  * azure-uamqp-c[core]:x64-windows -> 2020-12-09                                                                        
  * azure-uhttp-c[core]:x64-windows -> 2020-12-09
  * azure-umqtt-c[core]:x64-windows -> 2020-12-09
  * parson[core]:x64-windows -> 2020-09-14
  * umock-c[core]:x64-windows -> 2020-06-17-1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\muct\AppData\Local\vcpkg\archives\7b\7bac0664f0e9df9f61fac88be02428313d51beed192af5c0e39fbd9c87e849ce.zip
Could not locate cached archive: C:\Users\muct\AppData\Local\vcpkg\archives\82\8209cbb0a2fd9cb220dceea999ec55dc19dc1e1a010e7855ec5ae5b52f7d786d.zip
Could not locate cached archive: C:\Users\muct\AppData\Local\vcpkg\archives\a9\a993f2fcddddd9771ce34281b3b1e0f6650a966a82e26399075df7da7aa62f6e.zip
Could not locate cached archive: C:\Users\muct\AppData\Local\vcpkg\archives\db\db8f54c3217020a14566723741e3b799826d69503ea266bbc67cff342b023fbe.zip                                                                                             
Could not locate cached archive: C:\Users\muct\AppData\Local\vcpkg\archives\d5\d557b25766af0c89fa9102f9d313c4b852d27ff485277dcd37330ba005eb26fd.zip
Could not locate cached archive: C:\Users\muct\AppData\Local\vcpkg\archives\53\53ee7d13c30909e5b25589473008bce1e4f4cbac6ee5332ee97013f6e6f40b27.zip
Could not locate cached archive: C:\Users\muct\AppData\Local\vcpkg\archives\ef\efc5c597a049427bd09a1b76a1086d4565ff09fbe3cfef0f94d5fd69440ce419.zip
Could not locate cached archive: C:\Users\muct\AppData\Local\vcpkg\archives\5f\5f7f0dae07ea17ea58d2396d462e04daf46849c21f3f7580f2ab718e92349bea.zip
Starting package 1/8: azure-macro-utils-c:x64-windows
Building package azure-macro-utils-c[core]:x64-windows...
-- Note: azure-macro-utils-c only supports static library linkage. Building static library.
-- Downloading https://github.com/Azure/azure-macro-utils-c/archive/5926caf4e42e98e730e6d03395788205649a3ada.tar.gz -> Azure-azure-macro-utils-c-5926caf4e42e98e730e6d03395788205649a3ada-1.tar.gz...
-- Extracting source C:/Mukesh/IOTedge/vcpkg/downloads/Azure-azure-macro-utils-c-5926caf4e42e98e730e6d03395788205649a3ada-1.tar.gz
-- Using source at C:/Mukesh/IOTedge/vcpkg/buildtrees/azure-macro-utils-c/src/05649a3ada-59e162c9fa.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows                                                                                              
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: ninja -v                                                                                                
Working Directory: C:/Mukesh/IOTedge/vcpkg/buildtrees/azure-macro-utils-c/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1                                                                                                           
See logs for more information:
      C:\Mukesh\IOTedge\vcpkg\buildtrees\azure-macro-utils-c\config-x64-windows-out.log
Call Stack (most recent call first):                                                                                      scripts/cmake/vcpkg_configure_cmake.cmake:356 (vcpkg_execute_required_process)
  ports/azure-macro-utils-c/portfile.cmake:23 (vcpkg_configure_cmake)
```
**Additional context**
log file attached
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/6997976/config-x64-windows-out.log)

**Comment by JonLiu1993** [comment]
@mukeshhope ,Thanks for posting this issue,try removing your current build files and starting over. From the Pangolin root directory

**Comment by mukeshhope** [comment]
Hi @JonLiu1993 ,

I tried by removing whole vcpkg folder and then git clone again but it did not work.
What do you mean my Pangolin root directory, I could not understand this.
Thankyou for quick response

**Comment by JackBoosY** [comment]
```
FAILED: ../../x64-windows-dbg/CMakeCache.txt 
cmd /c "cd ../../x64-windows-dbg && "C:/Mukesh/IOTedge/vcpkg/downloads/tools/cmake-3.21.1-windows/cmake-3.21.1-windows-i386/bin/cmake.exe" "C:/Mukesh/IOTedge/vcpkg/buildtrees/azure-macro-utils-c/src/05649a3ada-59e162c9fa.clean" "-Drun_int_tests=OFF" "-DCMAKE_MAKE_PROGRAM=C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" "-DBUILD_SHARED_LIBS=OFF" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/Mukesh/IOTedge/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v142" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/Mukesh/IOTedge/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_LINKER_FLAGS_RELEASE=" "-DVCPKG_LINKER_FLAGS_DEBUG=" "-DVCPKG_TARGET_ARCHITECTURE=x64" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=C:/Mukesh/IOTedge/vcpkg" "-D_VCPKG_INSTALLED_DIR=C:/Mukesh/IOTedge/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_INSTALL_PREFIX=C:/Mukesh/IOTedge/vcpkg/packages/azure-macro-utils-c_x64-windows/debug""
The system cannot find the path specified.
```
Maybe a permission issue. Can you please retry on non-system disk?

Thanks.

**Comment by mukeshhope** [comment]
Hi Jack..
I started command prompt as administrator.
I do not have a non-system disk right now on my computer.
Thankyou for your response

**Comment by JonLiu1993** [comment]
@mukeshhope ,I can't produce the error in system disk ,please use powershell as administrator to try again
````
-- Using source at C:/test1/vcpkg/buildtrees/azure-iot-sdk-c/src/eff40b92ec-46a358aeca
-- Found external ninja('1.10.2').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package azure-iot-sdk-c[core]:x64-windows... done
Installing package azure-iot-sdk-c[core]:x64-windows...
Installing package azure-iot-sdk-c[core]:x64-windows... done
Elapsed time for package azure-iot-sdk-c:x64-windows: 22.23 s

Total elapsed time: 46.53 s

The package azure-iot-sdk-c:x64-windows provides CMake targets:

    find_package(azure_iot_sdks CONFIG REQUIRED)
    # Note: 6 target(s) were omitted.
    target_link_libraries(main PRIVATE serializer iothub_client prov_auth_client hsm_security_client)
````

**Comment by mukeshhope** [comment]
Hello Jon,

Today once again I performed a git pull and then run the command as an administrator but again I faced same error 
![error](https://user-images.githubusercontent.com/18657453/130056843-450406ce-271a-4ed2-b800-94e8c31f0704.png)

**Comment by JackBoosY** [comment]
I think the reason is one of the following:
1. run "cd ../../x64-windows-dbg" failed since _../../x64-windows-dbg_ doesn't exist or we don't have permission to access it,
2. run "C:/Mukesh/IOTedge/vcpkg/downloads/tools/cmake-3.21.1-windows/cmake-3.21.1-windows-i386/bin/cmake.exe" failed since it doesn't exist or we don't have permission to access it.

Sadly, we can't reproduce it locally, can you please confirm the above 2 items?

Thanks.

**Comment by mukeshhope** [comment]
Hi Jack,

yes it looks like so as it says, System can not find path specified.
Please have a look on attached log
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/7047459/config-x64-windows-out.log)

**Comment by JackBoosY** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!

**Comment by MichalDulski** [comment]
Hi! I've stumbled upon the same problem as above when I was trying to run command 
`F:\Dev\vcpkg\vcpkg.exe --triplet x64-windows install sfml`

I've run powershell as administrator. 

Here I'm posting whole console output
`PS F:\Dev\OpenCL-SDK> F:\Dev\vcpkg\vcpkg.exe --triplet x64-windows install sfml
Computing installation plan...
The following packages will be built and installed:
  * openal-soft[core]:x64-windows -> 1.21.1#4
    sfml[core]:x64-windows -> 2.5.1#12
  * stb[core]:x64-windows -> 2020-09-14#2
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Restored 0 packages from C:\Users\dulsk\AppData\Local\vcpkg\archives in 227 us. Use --debug to see more details.
Starting package 1/3: openal-soft:x64-windows
Building package openal-soft[core]:x64-windows...
-- Using cached kcat-openal-soft-ae4eacf147e2c2340cc4e02a790df04c793ed0a9.tar.gz.
-- Cleaning sources at F:/Dev/vcpkg/buildtrees/openal-soft/src/4c793ed0a9-63c417bd2b.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source F:/Dev/vcpkg/downloads/kcat-openal-soft-ae4eacf147e2c2340cc4e02a790df04c793ed0a9.tar.gz
-- Applying patch dont-export-symbols-in-static-build.patch
-- Using source at F:/Dev/vcpkg/buildtrees/openal-soft/src/4c793ed0a9-63c417bd2b.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:128 (message):
    Command failed: ninja -v
    Working Directory: F:/Dev/vcpkg/buildtrees/openal-soft/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      F:\Dev\vcpkg\buildtrees\openal-soft\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:367 (vcpkg_execute_required_process)
  ports/openal-soft/portfile.cmake:31 (vcpkg_configure_cmake)
  scripts/ports.cmake:145 (include)


error: building openal-soft:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+openal-soft
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[openal-soft]+Build+error
including:
  package: openal-soft[core]:x64-windows -> 1.21.1#4
    vcpkg-tool version: 2022-03-30-692785ac944e81417840c6de244fb3e18a4b35eb
    vcpkg-scripts version: 0051a1879 2022-04-29 (9 days ago)

Additionally, attach any relevant sections from the log files above.`

I don't know if this might help, but running `F:\Dev\vcpkg\vcpkg.exe --triplet x64-windows install tclap` worked just fine.

**Comment by JackBoosY** [comment]
@MichalDulski That's a different issue, please open a new issue and provide the logs.
