### ISSUE TITLE
Application with Opencv library fails on release mode builds. 

### ISSUE THREAD

**Issue by seccpur** [microsoft/vcpkg#19604]
**Describe the bug**
Installed opencv library using vcpkg. Installation and integration was successful and a test application builds successfully on debug mode. During release build, it fails with the message 'opencv_aruco340.dll was not found'. The project configuration is same for both modes, hence it is not related to the IDE project settings. 

**Environment**
- OS: Windows
- Compiler: Visual C++ 2019

**To Reproduce**
1) vcpkg install opencv3[ffmpeg]:x64-windows

2) Build a test application release mode.

**Comment by cenit** [comment]
are you up to date with vcpkg? the 340 dll extension looks very suspicious on that end

**Comment by seccpur** [comment]
vcpkg   version: 2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9`

**Comment by JonLiu1993** [comment]
@seccpur ,Thanks for posting this issue, please use git pull update vcpkg to the latest and try again.

**Comment by cenit** [comment]
and can you share cmake cache and logs of the build of your application? i fear it is finding another opencv installation

**Comment by seccpur** [comment]
Here's some relevant files related to debug built:
[CMakeError.log](https://github.com/microsoft/vcpkg/files/7000204/CMakeError.log)
[cmake_check_cache.zip](https://github.com/microsoft/vcpkg/files/7000219/cmake_check_cache.zip)

**Comment by cenit** [comment]
don't you have a file called CMakeCache.txt?

**Comment by seccpur** [comment]
This the CMakeCache.txt file. [CMakeCache.txt](https://github.com/microsoft/vcpkg/files/7000474/CMakeCache.txt)

**Comment by cenit** [comment]
not of opencv, but of your application. 
also, since it’s opencv3, the line you called in vcpkg is ./vcpkg install opencv3[ffmpeg]

without the 3, it would install opencv4, or either you are overlaying opencv

**Comment by seccpur** [comment]
My bad, its typos in this thread, as you can clearly see opencv3 is definitely in the  CMakeCache.txt file.

**Comment by cenit** [comment]
so? is it working now?

**Comment by seccpur** [comment]
Same.  It's not working in debug mode.

**Comment by seccpur** [comment]
I am not sure how. Both are free from any run time error. Thanks for the support.

![buildok debug](https://user-images.githubusercontent.com/5178443/129825210-da315ce2-879e-46c4-80ce-eaf2876e9777.PNG)
![buildok release](https://user-images.githubusercontent.com/5178443/129825211-aa9c6a02-86ed-4eaf-8838-2013f585ec89.PNG)
