### ISSUE TITLE
Private  built package  impossible to use using  python versioning

### ISSUE THREAD

**Issue by XWarin** [microsoft/vcpkg#19611]
Os : windows 10

**What is working** 👍  
-  build the stopt library package using vcpkg
-  build a second projet using stopt library without versioning

**Bug** 👎 
using python versioning to  compile the second project : the stopt package fail  to compile not finding zlib library (present in the baseline)

To reproduce:
 **vcpkg.json** file  in second project at level of CMakeList.txt

```json
{
  "name": "goestov2",
  "version": "1.0.0",
    "dependencies": [
{
   "name": "python3",
   "version>=": "3.8.3#2"
},
"boost-multi-array",
"boost-log",
"boost-chrono",
"boost-timer",
"boost-system",
"boost-random",
"boost-test",
"stopt"
  ],
  "overrides": [
    {
      "name": "python3",
      "version": "3.8.3#2"
    }
  ]
}
```
**The vcpk-configuration.json :**
```json
{
   "default-registry": {
    "kind": "git",
    "repository": "C:/dev/vcpkg",
    "baseline": "69478c5caafcde4c490bb1fccb960296801dbb5f"
  }, 
  "registries": [
    {
      "kind": "git",
      "repository": "C:/Users/c97830/VCPKG-REGISTRY/vcpkg-registry",
      "baseline": "6af5becc286a3cc4f7a56fe9316c1e6b44f63cd8",
      "packages": [ "stopt" ]
    }
  ]
}
```
The following package not compiling with versioning

[stochastic-control-StOpt-v4.1.tar.gz](https://github.com/microsoft/vcpkg/files/6998356/stochastic-control-StOpt-v4.1.tar.gz)

Message error

Error: Building package stopt:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: stopt:x64-windows
  Vcpkg version: 2021-08-03-1a6d67b8150e94b7f473c6ab1c0cfdd794316a64

Log

[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/6998420/config-x64-windows-out.log)

Regards

**Comment by NancyLi1013** [comment]
Hi @XWarin 

Thanks for posting this issue.

From config-x64-windows-out.log, found this:
```
CMake Error at C:/Program Files/CMake/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.21/Modules/FindZLIB.cmake:120 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:782 (_find_package)
  CMakeLists.txt:86 (FIND_PACKAGE)
```
Seems like `stopt ` needs to depend on `zlib`, but you didn't add it as the dependency. Could you please help check this? Or share `stopt` port in your registry repo if possible.

From CMakeLists.txt in StOpt-v4.1 folder, I found the following codes:
```
IF (WIN32)
  #zlib
  FIND_PACKAGE(ZLIB REQUIRED)
 
  #bzip2
  FIND_PACKAGE(BZip2 REQUIRED)
ENDIF(WIN32)
```

**Comment by XWarin** [comment]
Hi

Yes StOpt needs zlib and many boost libs.
The package works correctly without versioning. Meaning that using  the
library

https://gitlab.com/stochastic-control/StOpt

and the configuration i made

https://gitlab.com/stochastic-control/vcpkg-registry

I was able to build the package.

Using the package in a second one with jason file

{  "name": "goestov2",  "version": "1.0.0",    "dependencies":
[	"boost-multi-array",	"boost-log",	"boost-chrono",	"boost-timer",	"boost-system",	"boost-random",	"boost-test",	"pybind11",	"stopt"
 ]}

and configuration

{   "default-registry": {    "kind": "git",    "repository":
"C:/dev/vcpkg",    "baseline":
"69478c5caafcde4c490bb1fccb960296801dbb5f"  },   "registries": [    {
    "kind": "git",      "repository":
"C:/Users/c97830/VCPKG-REGISTRY/vcpkg-registry",      "baseline":
"6af5becc286a3cc4f7a56fe9316c1e6b44f63cd8",      "packages": [ "stopt"
]    }  ]}

it works perfectly well  (so it compiles with python 3.9, and the
project is able to see zlib depence occuring in StOpt) but using

{
"name": "goestov2",
"version": "1.0.0",
"dependencies": [
{
"name": "python3",
"version>=": "3.8.3#2"
},
"boost-multi-array",
"boost-log",
"boost-chrono",
"boost-timer",
"boost-system",
"boost-random",
"boost-test",
"stopt"
],

"overrides": [

{
"name": "python3",
"version": "3.8.3#2"
}
]
}

it fails not finding the libraries ZLIB.

Notice that the StOpt package can be build  (without generating the
package) but with some python binding using the  jason file in the StOpt
repo:

{    "name": "stopt",    "version": "4.1",    "dependencies": [
{            "name": "python3",            "version>=": "3.8.3#2"
  },      "pybind11",       "boost",        "boost-mpi",       "osi",
     "clp",	"coinutils",	"eigen3"    ],    "builtin-baseline":
"69478c5caafcde4c490bb1fccb960296801dbb5f",     "overrides": [
{ "name": "python3", "version": "3.8.3#2" }    ]
}

meaning that i was able to choose some python directly building the library.

As for GoestoV2 it is a private repo i cannot share.

It is sufficient for you ?

Best regards




Le mer. 18 août 2021 à 11:01, NancyLi1013 ***@***.***> a
écrit :

**Comment by NancyLi1013** [comment]
Hi @XWarin 

As I said above, you need to add `zlib `and `bzip2 ` to the dependency lists of `stopt` in your registries. 

I can reproduce this issue on my local with the following files:
vcpkg-configuration.json:
```
{
   "default-registry": {
    "kind": "git",
    "repository": "F:/new/vcpkg",
    "baseline": "69478c5caafcde4c490bb1fccb960296801dbb5f"
  },
  "registries": [
    {
      "kind": "git",
      "repository": "https://gitlab.com/stochastic-control/vcpkg-registry",
      "baseline": "6af5becc286a3cc4f7a56fe9316c1e6b44f63cd8",
      "packages": [ "stopt" ]
    }
  ]
}
```
vcpkg.json is the same as your above.

The reason why you encountered this issue only on versioning in manifest mode instead of the classic mode is that in manifest mode, there will a new folder `vcpkg_installed` generated. All binaries are installed to `vcpkg_installed `folder instead of `installed `folder. So if you didn't add `zlib `as a dependency of stopt, it will not be installed. In this case, stopt failed to build due to zlib cannot be found.

So, please add `zlib `and `bzip2 `to the dependency lists of `stopt `first.

https://gitlab.com/stochastic-control/vcpkg-registry/-/blob/main/ports/stopt/vcpkg.json

**Comment by XWarin** [comment]
Done. Adding all the dependencies solves the problem.
Thank you very much.
Regards

Xavier

Le ven. 20 août 2021 à 08:49, NancyLi1013 ***@***.***> a
écrit :

**Comment by NancyLi1013** [comment]
Please let me know if you still have other concerns about this issue.

**Comment by XWarin** [comment]
No everything works.
You can close it.
Thank you once again.


Le ven. 20 août 2021 à 11:19, NancyLi1013 ***@***.***> a
écrit :
