### ISSUE TITLE
[glib[core]:x64-linux] dynamic build failure

### ISSUE THREAD

**Issue by cgurps** [microsoft/vcpkg#19616]
**Host Environment**
- OS: archlinux
- Compiler: gcc (GCC) 11.1.0

**Context**
I'm trying to build `glib` as a dynamic library in Linux. I created the dynamic triplets 
```
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)

set(VCPKG_CMAKE_SYSTEM_NAME Linux)
```
And then run `./vcpkg install glib `. `vcpkg` complains about non empty directories
```
There should be no empty directories in vcpkg/packages/glib_x64-linux
The following empty directories were found:

    vcpkg/packages/glib_x64-linux/debug/bin
    packages/glib_x64-linux/bin

If a directory should be populated but is not, this might indicate an error in the portfile.
If the directories are not needed and their creation cannot be disabled, use something like this in the portfile to remove them:

    file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/a/dir" "${CURRENT_PACKAGES_DIR}/some/other/dir")
   ```
If I add the ` file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/a/dir" "${CURRENT_PACKAGES_DIR}/some/other/dir")` to the port cmake, everything runs fine. Those two directory are empty after building.

Should I make a PR to fix that?

**Comment by PhoebeHui** [comment]
@cgurps, we're happy to accept a PR to fix this issue! please submit a PR for it, thank you!

**Comment by Adela0814** [comment]
Fixed by PR https://github.com/microsoft/vcpkg/pull/17117
