### ISSUE TITLE
[yasm-tool:x64-windows] [Windows7] build failure

### ISSUE THREAD

**Issue by zichuan0320** [microsoft/vcpkg#19617]
**Host Environment**
- OS: [Windows7]
- Compiler: Visual Studio 2017

**To Reproduce**
$ vcpkg.exe install yasm-tool:x64-windows
Computing installation plan...
The following packages will be built and installed:
    yasm-tool[core]:x64-windows -> 1.3.0
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\libai\AppData\Local\vcpkg\archives\47\47be71aed1d96e48da358df052fc1d70536656b998c165122680d5ec9bf1b1d0.zip
Starting package 1/1: yasm-tool:x64-windows
Building package yasm-tool[core]:x64-windows...
-- Downloading https://github.com/yasm/yasm/archive/009450c7ad4d425fa5a10ac4bd6efbd25248d823.tar.gz -> yasm-yasm-009450c7ad4d425fa5a10ac4bd6efbd25248d823.tar.gz...
-- Cleaning sources at E:/vcpkg/buildtrees/yasm-tool/src/d25248d823-818ed1bbf4.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/vcpkg/downloads/yasm-yasm-009450c7ad4d425fa5a10ac4bd6efbd25248d823.tar.gz
-- Using source at E:/vcpkg/buildtrees/yasm-tool/src/d25248d823-818ed1bbf4.clean
-- Installing: E:/vcpkg/packages/yasm-tool_x64-windows/share/yasm-tool/copyright
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:155 (message):
    Command failed: E:/vcpkg/downloads/tools/cmake-3.21.1-windows/cmake-3.21.1-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j5
    Working Directory: E:/vcpkg/buildtrees/yasm-tool/x64-windows-dbg
    See logs for more information:
      E:\vcpkg\buildtrees\yasm-tool\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:104 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:44 (vcpkg_build_cmake)
  ports/yasm-tool/portfile.cmake:33 (vcpkg_install_cmake)
  scripts/ports.cmake:140 (include)

Error: Building package yasm-tool:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: yasm-tool:x64-windows
  Vcpkg version: 2021-08-12-85ab112d5ee102bc6eac8cdbbfdd173a71374e04

Additionally, attach any relevant sections from the log files above.

**Comment by PhoebeHui** [comment]
@zichuan0320, could you attach failure log E:\vcpkg\buildtrees\yasm-tool\install-x64-windows-dbg-out.log?

**Comment by zichuan0320** [comment]
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/7004158/install-x64-windows-dbg-out.log)

**Comment by PhoebeHui** [comment]
@zichuan0320, it's due to  Python 3.9 has dropped support for Windows 7. See a possible workaround for this in https://github.com/microsoft/vcpkg/issues/17924#issuecomment-841861494.

**Comment by zichuan0320** [comment]
@PhoebeHui，Hello, the above problems have been solved! Sincerely thank you for your help! I wish you success in your work and a happy life! thank you！
