### ISSUE TITLE
Issues found when building VCPKG with MSVC + /permissive-

### ISSUE THREAD

**Issue by PhoebeHui** [Microsoft/vcpkg#1963]
Building VCPKG with MSVC + /permissive- failed with error C4596, the issue is in https://github.com/Microsoft/vcpkg/blob/master/toolsrc/include/VcpkgPaths.h#L70, and involved by commit https://github.com/Microsoft/vcpkg/commit/9a963f7eff1981d4e894ea8b297d092cda60b764
 
Using full-qualified name to declare members inside class is ill-formed and incorrectly allowed by MSVC. MSVC now gives error when /permissive- is used. The fix is remove  ‘VcpkgPaths::’.

Failures like:
d:\vcpkg\src\toolsrc\include\VcpkgPaths.h(70): error C4596: 'get_toolset': illegal qualified name in member declaration (compiling source file ..\src\vcpkg_Input.cpp) [D:\VCPKG\src\toolsrc\vcpkglib\vcpkglib.vcxproj]

**Comment by alexkaratarakis** [comment]
Thanks!
