### ISSUE TITLE
[colmap] Build failure

### ISSUE THREAD

**Issue by wedadsallam2020** [microsoft/vcpkg#19663]
**Describe the bug**
Error: Building package colmap:x64-windows failed with: BUILD_FAILED

- OS: Windows
- Compiler: revision
colmap:x64-windows
- Vcpkg version: 2021-08-12-85ab112d5ee102bc6eac8cdbbfdd173a71374e04 

![Screenshot (9)](https://user-images.githubusercontent.com/72740859/130180902-1c6c39bf-ee63-425a-8e50-86059eec3e08.png)

**Comment by JonLiu1993** [comment]
@wedadsallam2020 ,Could you please provide the error log?

**Comment by JackBoosY** [comment]
Will be fixed by https://github.com/microsoft/vcpkg/pull/19628.
