### ISSUE TITLE
Could not parse version for tool 7zip. Version string was: 19.00

### ISSUE THREAD

**Issue by BenXu86** [microsoft/vcpkg#19664]
**Describe the bug**

**Environment**
- OS: Windows 10
- Compiler: vs2019

**To Reproduce**
1. ./vcpkg install zlib:x64-windows
2. See error
Repro code when

**Expected behavior**

**Failure logs** 
Warning: Different source is available for vcpkg (2020.6.15 -> 9999.99.99). Use .\bootstrap-vcpkg.bat to update.
Computing installation plan...
The following packages will be built and installed:
    zlib[core]:x64-windows
Warning: The following VS instances are excluded because the English language pack is unavailable.
    D:\Applications\VisualStudio2017
    C:\Program Files (x86)\Microsoft Visual Studio 12.0\
Please install the English language pack.
Detecting compiler hash for triplet x64-windows...
A suitable version of powershell-core was not found (required v7.1.3). Downloading portable powershell-core v7.1.3...
Downloading powershell-core...
  https://github.com/PowerShell/PowerShell/releases/download/v7.1.3/PowerShell-7.1.3-win-x86.zip -> D:\Code\vcpkg\downloads\PowerShell-7.1.3-win-x86.zip
Extracting powershell-core...
Could not parse version for tool 7zip. Version string was: 19.00

**Additional context**
I have installed VS2019 so I ignore the warning about VS2017

**Comment by PhoebeHui** [comment]
@BenXu86, could you get vcpkg latest source via 'git pull' and '.\bootstrap-vcpkg.bat', then try again?

**Comment by BenXu86** [comment]
> @BenXu86, could you get vcpkg latest source via 'git pull' and '.\bootstrap-vcpkg.bat', then try again?

I try again. But I still get the same error.

**Comment by PhoebeHui** [comment]
@BenXu86, could you install English language pack via VS installer and try again? You can also reference https://www.cnblogs.com/vcpkg/p/14550099.html. BTW, we have many blogs posted about VCPKG in https://www.cnblogs.com/vcpkg/ for Chinese users, you can reference them if you needed.

```
Warning: The following VS instances are excluded because the English language pack is unavailable.
```

**Comment by gnaggnoyil** [comment]
@BenXu86 I can confirm that both current master (e201002) and commit at 2021-08-21 (ab60f27) will not cause the problem you described. In fact, the only possible way I can come up with is that you updated your local vcpkg branch to track the remote branch yet forgot to run `booststrap.bat` and left your `vcpkg.exe` with a version released before 6 months ago. Do you still have this issue after syncing your local vcpkg branch to current master and rerunning `booststrap.bat` to update your `vcpkg.exe`?

**Comment by PhoebeHui** [comment]
@BenXu86, please reopen this issue if it still be a problem for you.
