### ISSUE TITLE
application build features in manifest mode

### ISSUE THREAD

**Issue by Be-ing** [microsoft/vcpkg#19662]
****

**Is your feature request related to a problem? Please describe.**
vcpkg port manifests can specify various features to toggle build options, which can also selectively pull in dependencies. However, there is no way to use different features of a vcpkg.json manifest file when building an application which uses vcpkg for its dependencies.

**Proposed solution**
Add parameters to `vcpkg install` and CMake build options for specifying features to use from a vcpkg.json manifest file.

**Describe alternatives you've considered**
Use different versions of vcpkg.json in different Git branches instead of different features. However, this is harder to maintain. I want to be able to set up CI jobs for the same Git branch to test different sets of dependencies with the same application code.

**Additional context**
Mixxx is starting to work towards migrating from Qt5 to Qt6. For a while we will need CI builds for both Qt5 and Qt6. To use vcpkg in manifest mode for this, it would be helpful to select whether to use Qt5 or Qt6 as a dependency. Alternatively, the vcpkg.json manifest file could specify both Qt5 and Qt6 as dependencies and leave it to the application's build system to select between them. The downside to that would be downloading large unnecessary dependencies.

**Comment by JackBoosY** [comment]
Can you please provide an example?
The manifest mode already provides port feature selection.

**Comment by autoantwort** [comment]
I think you want to use the `--x-feature=` option. E.g. if you have a feature `foo` in your `vcpkg.json` file you have to do `vcpkg install --x-feature=foo`

**Comment by Be-ing** [comment]
How would I use a command line argument to the vcpkg executable with the CMake toolchain?

**Comment by autoantwort** [comment]
See [here](https://github.com/microsoft/vcpkg/blob/master/docs/users/manifests.md#vcpkg_manifest_features)

**Comment by Be-ing** [comment]
Ah, thanks. That would satisfy my use case. Sorry for the noise.
