### ISSUE TITLE
[llvm] update to version 12.0.1

### ISSUE THREAD

**Issue by InfRandomness** [microsoft/vcpkg#19676]
Library name: LLVM

New version number: 12.0.1

Other information that may be useful (release notes, etc...)
https://llvm.org/docs/ReleaseNotes.html

**Comment by xavier2k6** [comment]
@InfRandomness see https://github.com/microsoft/vcpkg/issues/19568

**Comment by InfRandomness** [comment]
Closed as duplicate of #19568

**Comment by InfRandomness** [comment]
@xavier2k6

Just to make sure, I meant the LLVM package, are we on the same page ?

**Comment by xavier2k6** [comment]
> @xavier2k6
> 
> Just to make sure, I meant the LLVM package/port, are we on the same page ?

I was only referring to the tool being updated too, see below - onwards.

https://github.com/microsoft/vcpkg/issues/19570#issuecomment-900011501

Your port update is still valid as far as I can see.

**Comment by xavier2k6** [comment]
@InfRandomness You should re-open this.
