### ISSUE TITLE
[tinyfiledialogs] build failure, /debug/lib/tinyfiledialogs.lib does not exist

### ISSUE THREAD

**Issue by SamuelMarks** [microsoft/vcpkg#19678]
**Host Environment**
- OS: Windows
- Compiler: 19.29.30040 (MSVC)

**To Reproduce**
`./vcpkg install tinyfiledialogs:x86-windows tinyfiledialogs:x64-windows`

**Failure logs** 
Error on on `target_link_libraries`:
The imported target "tinyfiledialogs::tinyfiledialogs" references the file

     "vcpkg/packages/tinyfiledialogs_x86-windows/debug/lib/tinyfiledialogs.lib"

  but this file does not exist.

**Additional context**
I think this broke it https://github.com/microsoft/vcpkg/pull/19338

**Comment by NancyLi1013** [comment]
Hi @SamuelMarks 

Thanks for posting this issue.

`"vcpkg/packages/tinyfiledialogs_x86-windows/debug/lib/tinyfiledialogs.lib"` should not exist in tinyfiledialogsConfig.cmake file.

I think we should fix this problem.

But it seems that the usage can work fine.

```
    find_package(tinyfiledialogs CONFIG REQUIRED)
    target_link_libraries(main PRIVATE tinyfiledialogs::tinyfiledialogs)
```
Please let me know if you have other concerns about this issue.
