### ISSUE TITLE
cmake can't configure glfw3 after vcpkg install && integrate install.

### ISSUE THREAD

**Issue by shash29-dev** [microsoft/vcpkg#19682]
My CmakeLists.txt
`cmake_minimum_required(VERSION 3.0.0)
project(alpha VERSION 0.1.0)

include(CTest)
find_package(glfw3 CONFIG REQUIRED)
find_package(hdf5 CONFIG REQUIRED)
enable_testing()

add_executable(alpha main.cpp)
target_link_libraries(alpha PRIVATE glfw)
target_link_libraries(alpha PRIVATE hdf5::hdf5-shared hdf5::hdf5_hl-shared)
set(CPACK_PROJECT_NAME ${PROJECT_NAME})
set(CPACK_PROJECT_VERSION ${PROJECT_VERSION})
include(CPack)`

Error stack:
`[proc] Executing command: C:\msys64\mingw64\bin\cmake.exe --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_C_COMPILER:FILEPATH=C:\msys64\mingw64\bin\x86_64-w64-mingw32-gcc.exe -DCMAKE_CXX_COMPILER:FILEPATH=C:\msys64\mingw64\bin\x86_64-w64-mingw32-g++.exe -Hd:/PhD/Research/ProjectCpp/TutOpenGL/one -Bd:/PhD/Research/ProjectCpp/TutOpenGL/one/build -G "MinGW Makefiles"
[cmake] Not searching for unused variables given on the command line.
[cmake] -- The C compiler identification is GNU 10.3.0
[cmake] -- The CXX compiler identification is GNU 10.3.0
[cmake] -- Detecting C compiler ABI info
[cmake] -- Detecting C compiler ABI info - done
[cmake] -- Check for working C compiler: C:/msys64/mingw64/bin/x86_64-w64-mingw32-gcc.exe - skipped
[cmake] -- Detecting C compile features
[cmake] -- Detecting C compile features - done
[cmake] -- Detecting CXX compiler ABI info
[cmake] -- Detecting CXX compiler ABI info - done
[cmake] -- Check for working CXX compiler: C:/msys64/mingw64/bin/x86_64-w64-mingw32-g++.exe - skipped
[cmake] -- Detecting CXX compile features
[cmake] -- Detecting CXX compile features - done
[cmake] CMake Error at CMakeLists.txt:5 (find_package):
[cmake]   Could not find a package configuration file provided by "glfw3" with any of
[cmake]   the following names:
[cmake] 
[cmake]     glfw3Config.cmake
[cmake]     glfw3-config.cmake
[cmake] 
[cmake]   Add the installation prefix of "glfw3" to CMAKE_PREFIX_PATH or set
[cmake]   "glfw3_DIR" to a directory containing one of the above files.  If "glfw3"
[cmake]   provides a separate development package or SDK, be sure it has been
[cmake]   installed.
[cmake] 
[cmake] -- Configuring incomplete, errors occurred!`

If I remove glfw3 from the CMakeLists.txt, other installed packages are successfully configured.  For example hdf5 here is successfully configured.

CMakeLists.txt
`cmake_minimum_required(VERSION 3.0.0)
project(alpha VERSION 0.1.0)

include(CTest)
find_package(hdf5 CONFIG REQUIRED)
enable_testing()

add_executable(alpha main.cpp)
target_link_libraries(alpha PRIVATE hdf5::hdf5-shared hdf5::hdf5_hl-shared)
set(CPACK_PROJECT_NAME ${PROJECT_NAME})
set(CPACK_PROJECT_VERSION ${PROJECT_VERSION})
include(CPack)`

My Cmakesettings.json:
`{
    "configurations": [{
      "name": "x86-Debug",
      "generator": "MinGW Makefiles",
      "configurationType" : "Debug",
      "cmakeCommandArgs": "",
      "variables": [{
        "name": "CMAKE_TOOLCHAIN_FILE",
        "value": "C:\\src\\vcpkg\\scripts\\buildsystems\\vcpkg.cmake"
      }]
    }]
  }`

My cmake-tools-kits.json. (I am using "Mingw64 GCC 10.3.0" )
`[
  {
    "name": "GCC 10.3.0 x86_64-w64-mingw32",
    "compilers": {
      "C": "C:\\msys64\\mingw64\\bin\\x86_64-w64-mingw32-gcc.exe",
      "CXX": "C:\\msys64\\mingw64\\bin\\x86_64-w64-mingw32-g++.exe"
    }
  },
  {
    "name": "Visual Studio Community 2019 Release - amd64",
    "visualStudio": "95f37377",
    "visualStudioArchitecture": "x64",
    "preferredGenerator": {
      "name": "Visual Studio 16 2019",
      "platform": "x64",
      "toolset": "host=x64"
    }
  },
  {
    "name": "Visual Studio Community 2019 Release - amd64_x86",
    "visualStudio": "95f37377",
    "visualStudioArchitecture": "x64",
    "preferredGenerator": {
      "name": "Visual Studio 16 2019",
      "platform": "win32",
      "toolset": "host=x64"
    }
  },
  {
    "name": "Visual Studio Community 2019 Release - x86",
    "visualStudio": "95f37377",
    "visualStudioArchitecture": "x86",
    "preferredGenerator": {
      "name": "Visual Studio 16 2019",
      "platform": "win32",
      "toolset": "host=x86"
    }
  },
  {
    "name": "Visual Studio Community 2019 Release - x86_amd64",
    "visualStudio": "95f37377",
    "visualStudioArchitecture": "x86",
    "preferredGenerator": {
      "name": "Visual Studio 16 2019",
      "platform": "x64",
      "toolset": "host=x86"
    }
  },
  {
    "name": "Mingw64 GCC 10.3.0",
    
    "compilers": {
      "C": "C:\\msys64\\mingw64\\bin\\x86_64-w64-mingw32-gcc.exe",
      "CXX": "C:\\msys64\\mingw64\\bin\\x86_64-w64-mingw32-g++.exe"
    },
    "preferredGenerator": {
      "name": "MinGW Makefiles",
      "platform": "x64",
      "toolset": "host=x64"
    },
    "environmentVariables": {
      "CMT_MINGW_PATH": "C:\\msys64\\mingw64\\bin\\"
    },
    "cmakeSettings": {
      "CMAKE_MAKE_PROGRAM": "C:\\msys64\\usr\\bin\\",
      "cmake.cmakePath": "C:\\msys64\\mingw64\\bin\\cmake.exe"
   }
  }
]`

What can be the problem? Please share possible causes.

**Comment by autoantwort** [comment]
Can you please properly format your issue with code blocks: https://www.markdownguide.org/extended-syntax#fenced-code-blocks
