### ISSUE TITLE
vcpkg unable to determine architecture

### ISSUE THREAD

**Issue by vadi2** [microsoft/vcpkg#19683]
vcpkg stopped working without an obvious reason to cause it:

```
[variant] Loaded new set of variants
[main] Configuring folder: mudlet 
[cmake] CMake Warning at 3rdparty/vcpkg/scripts/buildsystems/vcpkg.cmake:191 (message):
[cmake]   Unable to determine target architecture, continuing without vcpkg.
```

Using vcpkg 4b222f8 on an Intel chromebook:

```
Linux penguin 5.4.119-14945-gafc97d54f809 #1 SMP PREEMPT Tue Aug 10 21:49:04 PDT 2021 x86_64 GNU/Linux
```

What could be wrong?

**Comment by autoantwort** [comment]
https://github.com/microsoft/vcpkg/blob/025e564979cc01d0fbc5c920aa8a36635efb01bb/scripts/buildsystems/vcpkg.cmake#L239-L337

Maybe check the values of the variables that are checked in the code. Maybe they are empty?

**Comment by PhoebeHui** [comment]
@vadi2, does this still be a problem with vcpkg latest source?

**Comment by vadi2** [comment]
This somehow fixed itself. Maybe the VS Code C++ or CMake extension was being dodgy.

**Comment by PhoebeHui** [comment]
Good to know, thanks for your reply!
