### ISSUE TITLE
vcpkg ports\Binn directories recursion

### ISSUE THREAD

**Issue by perrog** [microsoft/vcpkg#19688]
I got an error stating that vcpkg search failed because it it could not find the CONTROL file inside ports\Binn directory.
After closer inspection I found out that the ports\Binn directory contained subdirectories repeating itself indefinitely (...at least 10'000 subfolders.)
Does anybody have any clue why this happened?

I noticed that I still got the old capital letter folder name format, whereas master branch switched to lowercase letter. My local git repo is old. But can't see why this should be the problem.

```
>tree C:\path\to\vcpkg\ports\Binn
Folder PATH listing
Volume serial number is ...
C:\PATH\TO\VCPKG\PORTS\BINN
└───Binn
    └───Binn
        └───Binn
            └───Binn
                └───Binn
                    └───Binn
                        └───Binn
                          .
                          .  ...thousands of levels later:
                          .
                          │   0001_fix_uwp.patch
                          │
                          └───Binn
                              │   CMakeLists.txt
                              │   portfile.cmake
                              │
                              └───Binn
                                      CONTROL```

**Comment by autoantwort** [comment]
Do you still have the problem after a `git pull` in the vcpkg repo?

**Comment by dg0yt** [comment]
There is no `ports\Binn` in the current HEAD of the master branch.

**Comment by dg0yt** [comment]
... but on a case-insensitive file system, the local presence of `ports/Binn` could be a challenge for handling `ports/binn`.

**Comment by lviolette** [comment]
I too have found that I have what appears to be a very deeply recursive vcpkg folder.
Explorer crashes when I attempt to delete it.
The path looks like this recursively...
C:\dev\vcpkg\ports\tbb\out\build\x64-Debug\src\out\build\x64-Debug\src\out\build\x64-Debug\src\out

**Comment by dg0yt** [comment]
> Explorer crashes when I attempt to delete it.
> The path looks like this recursively...
> C:\dev\vcpkg\ports\tbb\out\build\x64-Debug\src\out\build\x64-Debug\src\out\build\x64-Debug\src\out

Can you perhaps rename `out` in `C:\dev\vcpkg\ports\tbb\` before trying to remove it?

**Comment by JackBoosY** [comment]
Can you describe how this problem happened? Or provide a repro step. 

Thanks.

**Comment by perrog** [comment]
> Do you still have the problem after a `git pull` in the vcpkg repo?

No, git pull solved the issue. 
For the subdirectories removal I had to write a Powershell script since  Explorer crashed when trying to delete the folder with so many subfolders.

**Comment by perrog** [comment]
> Can you describe how this problem happened? Or provide a repro step.
> 
> Thanks.

I will start to look closely at this from now on, and if it happens again be prepare to give a repo instruction.
Recently I've started to use vcpkg.json manifests in Linux devcontainers, so I don't have a complete command-history what I've typed so far.

**Comment by JackBoosY** [comment]
This should be a vcpkg bug and was fixed by other PR.
Please reopen this issue if you have other concern.
