### ISSUE TITLE
[ffmpeg] ld: warning: could not create compact unwind 

### ISSUE THREAD

**Issue by daschuer** [microsoft/vcpkg#19699]
When I try to link to the ffmpeg libraries I get the following linker warnings: 
```
2021-08-18T22:06:41.3473950Z ld: warning: could not create compact unwind for _ff_cfhd_init_vlcs: stack subq instruction is too different from dwarf stack size
2021-08-18T22:06:41.3475230Z ld: warning: could not create compact unwind for _ff_rl_init_vlc: stack subq instruction is too different from dwarf stack size
```
The linking itself succeeds and so far it works as well. 
How can I get rid of the warnings? 

ffmpeg is build with these options
```
-- Building Options: --enable-pic --disable-doc --enable-debug --enable-runtime-cpudetect --enable-asm --enable-x86asm --enable-gpl --disable-ffmpeg --disable-ffplay --disable-ffprobe --enable-avcodec --enable-avdevice --enable-avformat --enable-avfilter --enable-postproc --enable-swresample --enable-swscale --disable-libass --disable-avisynth --disable-bzlib --disable-libdav1d --disable-libfdk-aac --disable-libfontconfig --disable-libfreetype --disable-libfribidi --disable-iconv --disable-libilbc --disable-lzma --disable-libmp3lame --disable-libmodplug --disable-cuda --disable-nvenc --disable-nvdec  --disable-cuvid --disable-ffnvcodec --disable-opencl --disable-opengl --disable-libopenh264 --disable-libopenjpeg --disable-openssl --disable-libopus --disable-sdl2 --disable-libsnappy --disable-libsoxr --disable-libspeex --disable-libssh --disable-libtensorflow --disable-libtesseract --disable-libtheora --disable-libvorbis --disable-libvpx --disable-libwebp --disable-libx264 --disable-libx265 --disable-libxml2 --disable-zlib --disable-vdpau --extra-cflags="-isysroot /Applications/Xcode_12.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk" --extra-ldflags="-isysroot /Applications/Xcode_12.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk"  --enable-cross-compile --target-os=darwin --arch=x86_64 --extra-ldflags=-arch --extra-ldflags=x86_64 --extra-cflags=-arch --extra-cflags=x86_64 --extra-cxxflags=-arch --extra-cxxflags=x86_64 --pkg-config-flags=--static
```

**Environment**
- OS: osx
- Compiler: AppleClang 12.0.0.12000032

**To Reproduce**
1. ./vcpkg install ffmpeg
2. link mixxx application 

Here is the workflow run building Mixxx
https://github.com/mixxxdj/mixxx/pull/4225/checks?check_run_id=3365982171

And here the Run building vcpkg
https://github.com/mixxxdj/vcpkg/runs/3332915409

**Expected behavior**
No warning should be logged 

I would be great if someone has an idea how to fix the issue or debug it more. 
Thank you.

**Comment by Be-ing** [comment]
Are you sure ffmpeg was built as 64 bit? https://stackoverflow.com/questions/39598302/ld-warning-stack-subl-instruction-is-too-different-from-dwarf-stack-size-on-os

**Comment by daschuer** [comment]
At least the --arch=x86_64 option is set. See above.

**Comment by Be-ing** [comment]
I am not sure it actually does get set:
```
--arch=x86_64 --extra-ldflags=-arch --extra-ldflags=x86_64 --extra-cflags=-arch --extra-cflags=x86_64 --extra-cxxflags=-arch --extra-cxxflags=x86_64
```
`--extra-ldflags` is set twice, first to `-arch` then to `x86_64`. The same happens for `--extra-cflags` and `--extra-cxxflags`. Perhaps only the first one has an effect.

**Comment by NancyLi1013** [comment]
Hi @daschuer 

Thanks for posting this issue.

Do you encounter this issue on your local machine or on the CI https://github.com/mixxxdj/mixxx/pull/4225?

Could you please try to pass the compiler option to rebuild?

`LDFLAGS="-Wl,-no_compact_unwind"`

**Comment by daschuer** [comment]
This linker flag removes the warning. See https://github.com/daschuer/mixxx/runs/3399675678

I encounter the issue on the GitHub CI. I have unfortunately no access to a local macOS machine. 

Can you give some insights? 
* Why the linker only complains about these two ffmpeg functions? Are other warnings suppressed or are only these two affected? 
* For my feeling the linker flag is a workaround since it affect all functions, right?
* It seems to cause issues with the exception stack  see: https://developer.apple.com/documentation/xcode/addressing-language-exception-crashes
* Crawling in GitHub I have found other solutions where the warning is silenced with LDFLAGS="-Wl,-w"
* What is the recommended Fix in case of this warning by the supplier? 
* Is there something official where the  "no_compact_unwind" flag is explained?

**Comment by daschuer** [comment]
By the way, when I do not link to ffmpeg the warning disappears. What could be the cause? It there something special with it?

**Comment by JackBoosY** [comment]
@daschuer Sorry but I didn'f found the error messages you mentioned in https://github.com/daschuer/mixxx/runs/3399675678, can you please extract it and provide me a log file?

Also, can you get the config logs and install logs in your ci system?

Thanks.

**Comment by daschuer** [comment]
https://github.com/daschuer/mixxx/runs/3399675678 is the run with LDFLAGS="-Wl,-no_compact_unwind"

The original error can be found here:
https://github.com/mixxxdj/mixxx/pull/4225/checks?check_run_id=3403021507

The logs from the vcpkg build run can be downloaded as artifact here:
https://github.com/mixxxdj/vcpkg/runs/3332915409

Thank you for having a look.

**Comment by daschuer** [comment]
By default ffmpeg is build  with gcc. I have patched the build.sh.in to use clang but the warning remains, so it is not a compiler bug. 
If I disable the dfhd encoder and decoder, one warning disappears. So it seems to be an issue with the function itself. 
Both function have in common that they allocate big arrays on the stack. I guess that this causes the linker to fail applying compact unwind. 

I will report the issue upstream, maybe they can suggest a workaround.

**Comment by daschuer** [comment]
https://trac.ffmpeg.org/ticket/9399

**Comment by JackBoosY** [comment]
Close this PR until upstream fixes this.

**Comment by ValZapod** [comment]
Should be fixed with https://github.com/FFmpeg/FFmpeg/commit/e6d89d0efd9194198d9964e47bf428be222594ea
