### ISSUE TITLE
vcpkg.json optional dependencies and devdependencies

### ISSUE THREAD

**Issue by Baklap4** [microsoft/vcpkg#19696]
I have two questions:
1. Is it possible within the `vcpkg.json` manifest file to make a dependency optional?
2. Can we define a dependency such as `gettext` a development dependency?

The first question comes from the fact that i ran into a library (portmidi #19694 ) which didn't have linux support. In our case portmidi is just optional and thus not needed to be installed. In normal cmake we check if it's available. If it's not just  don't build anything related to portmidi. This is a common practice i believe so i was wondering if we can somehow define those optional dependencies.

As for the second question, we only use gettext (and the other binaries) if we have to compile our `*.po` translation files. Like portmidi this is an optional component but a special sort of 'optional' component as it works just fine without it but you don't have the translation feature. Endusers running our application also don't need gettext if our installer supplies all the files so therefore i thought it'd be nice to define development dependencies. This is a pretty common practice within javascript world. See a real world [package.json](https://github.com/angular/angular/blob/master/package.json#L163-L208) as an example for this. Some more documentation of [devDependencies](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#devdependencies)

**Comment by autoantwort** [comment]
You can use features for that: https://github.com/microsoft/vcpkg/blob/master/docs/users/manifests.md#features-and-default-features

**Comment by Baklap4** [comment]
@autoantwort Hmm so if i understand correctly to declare a library as optional you'll have to use the `features` part like this?:
```
{
  "name": "program",
  "version": "1.0.0",
  "dependencies": [
    "ffmpeg"
  ],
  "features": {
    "portmidi": {
      "description": "Optional dependency for program"
    },
    "libxmlpp": {
      "description":"Optional dependency for program"
    }
  },
  "builtin-baseline": "025e564979cc01d0fbc5c920aa8a36635efb01bb"
}
```

cause if i do that i don't see that libxmlpp is being downloaded/build and installed

**Comment by autoantwort** [comment]
You also have to add the dependency to the feature like in the linked example

**Comment by Baklap4** [comment]
After some trial and error i think i've managed it:

```
{
  "name": "program",
  "version": "1.0.0",
  "dependencies": [
    "ffmpeg"
  ],
  "default-features": [],
  "features": {
    "portmidi": {
      "description": "Optional dependency for program",
      "dependencies": [ "portmidi" ]
    },
    "libxmlpp": {
      "description": "Optional dependency for program",
      "dependencies": [ "libxmlpp" ]
    }
  },
  "builtin-baseline": "025e564979cc01d0fbc5c920aa8a36635efb01bb"
}
```

Without that `default-features` i didn't get it to work.

So correct me if i'm wrong, but the above does this:
It requires vcpkg to install `ffmpeg`. And if it's available for the platform installs `portmidi` (which doesn't work on linux and thus doesn't get installed) and `libxmlpp` (which does work on linux and gets installed).

**Comment by autoantwort** [comment]
The `default-features` line shouldn't be necessary.

> So correct me if i'm wrong, but the above does this:

It only installs ffmpeg. If you also want to install the features, you have to pass that as an option to vcpkg by `--x-feature=...` (e.g. `vcpkg install --x-feature=libxmlpp`). You can add the features to the default features list, then they are installed by default (`"default-features": ["portmidi", "libxmlpp"]`). If an dependency only works on one platform, you should use the `platform` field. For example
```json
    "portmidi": {
      "description": "Optional dependency for program",
      "supports": "linux",
      "dependencies": [ {
           "name": "portmidi",
           "platform": "linux"
       }]
    },
```

**Comment by dg0yt** [comment]
>  2. Can we define a dependency such as `gettext` a development dependency?
> 
> ...
> 
> As for the second question, we only use gettext (and the other binaries) if we have to compile our `*.po` translation files.

Note that gettext[core] only provides libintl (for the platforms which need it). The tools are in a non-default feature.

**Comment by Baklap4** [comment]
@autoantwort alright i think i've got it thanks! It's basicly really focused on libraries, not persé enduser applications. Portmidi for instance already has defined it doesn't work on Linux so why should i need to redefine it?

> Note that gettext[core] only provides libintl (for the platforms which need it). The tools are in a non-default feature.

@dg0yt i'm aware of that. Ran into that issue yesterday ghehe ;) 

I think this issue can be closed as my questions are answered thanks!
