### ISSUE TITLE
How do I install Arrayfire (getting errors).

### ISSUE THREAD

**Issue by TheUnrealDragon** [microsoft/vcpkg#19708]
I am trying to install arrayfire for Windows 10 x64 for flashlight.
(Neither of arrayfire[cpu] / arrayfire[cuda] are being installed as they both depend on intel-mkl)

However Arrayfire cannot find the oneapi-mkl install.I have set oneapi_root environment variable. And I have installed intel-mkl from vcpkg.

The log says that it can't find intel-mkl.

arrayfire install error output:
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/7030320/config-x64-windows-out.log)

vcpkg list output:
[vcpkg-list.txt](https://github.com/microsoft/vcpkg/files/7030383/vcpkg-list.txt)

**Comment by JackBoosY** [comment]
Can you please provide Intel MKL version and the installed path?

Thanks.

**Comment by TheUnrealDragon** [comment]
Intel-MKL installed version installed from the Intel oneAPI version is "2021.3.0."
Installed path is on "E:\IntelLibs\mkl\"
Environment variable ONEAPI_ROOT is "E:\IntelLibs\"

I also tried creating a new Environment Variable for MKLROOT to E:\IntelLibs\mkl\2021.3.0 ( this didn't work.).

**Comment by JackBoosY** [comment]
Will be fixed by #15233.

**Comment by TheUnrealDragon** [comment]
Hey, total beginner to github and cmake here. (so this may be a stupid question.)

> Will be fixed by #15233.

But when I checked the that link in the files changed tab the cmake file the find_path command was searching for intel-mkl 
Line 35: `find_path(MKL_ROOT include/mkl.h PATHS $ENV{MKLROOT} ${INTEL_ROOT}/mkl DOC "Folder contains MKL")`
But oneAPI sets only the environment variable ONEAPI_ROOT which in my case points to E:\IntelLibs\
So shouldn't "${ENV${ONEAPI_ROOT}}/mkl/latest" be also searched for the include dir?
latest folder is a shortcut to the 2021.3.0 dir in "E:\IntelLibs\mkl\"
The mkl include directory comes under the  "E:\IntelLibs\mkl\latest\" subdirectory. So mkl.h is found in "E:\IntelLibs\mkl\latest\include" dir.

Also is there any workaround I can use for the time being?
Thanks!

**Comment by FrankXie05** [comment]
The port `intel-mkl` has been integrated on `Linux` by PR https://github.com/microsoft/vcpkg/pull/29437.
