### ISSUE TITLE
[Building SMP/libgmp.sln for Release CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127] build failure

### ISSUE THREAD

**Issue by xulincai** [microsoft/vcpkg#19709]
**Host Environment**
- OS: Windows
- Compiler: vs2019

**To Reproduce**
.\vcpkg.exe install cgal

**Failure logs** 
2>hamdist.obj : warning LNK4078: multiple '.rdata' sections found with different attributes (C0500040) [C:\dev\vcpkg\buildtrees\gmp\x64-windows-rel\19f0b65fd0-9b395bc164.clean\SMP\libgmp.vcxproj]
            Creating library C:\dev\vcpkg\buildtrees\gmp\x64-windows-rel\19f0b65fd0-9b395bc164.clean\SMP\..\msvc\\lib\x64\gmp.lib and object C:\dev\vcpkg\buildtrees\gmp\x64-windows-rel\19f0b65fd0-9b395bc164.clean\SMP\..\msvc\\lib\x64\gmp.exp
         Generating code
         Previous IPDB not found, fall back to full compilation.
         All 868 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
         Finished generating code
     2>LINK : fatal error LNK1158: cannot run 'rc.exe' [C:\dev\vcpkg\buildtrees\gmp\x64-windows-rel\19f0b65fd0-9b395bc164.clean\SMP\libgmp.vcxproj]
     2>已完成生成项目“C:\dev\vcpkg\buildtrees\gmp\x64-windows-rel\19f0b65fd0-9b395bc164.clean\SMP\libgmp.vcxproj”(Rebuild 个目标)的操作 - 失败。
     1>已完成生成项目“C:\dev\vcpkg\buildtrees\gmp\x64-windows-rel\19f0b65fd0-9b395bc164.clean\SMP\libgmp.sln”(Rebuild 个目标)的操作 - 失败。
生成失败。

       “C:\dev\vcpkg\buildtrees\gmp\x64-windows-rel\19f0b65fd0-9b395bc164.clean\SMP\libgmp.sln”(Rebuild 目标) (1) ->
       “C:\dev\vcpkg\buildtrees\gmp\x64-windows-rel\19f0b65fd0-9b395bc164.clean\SMP\libgmp.vcxproj”(Rebuild 目标) (2) ->
       (ClCompile 目标) -> 
         C:\dev\vcpkg\buildtrees\gmp\x64-windows-rel\19f0b65fd0-9b395bc164.clean\mpn\generic\gcdext_1.c(1,1): warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss [C:\dev\vcpkg\buildtrees\gmp\x64-windows-rel\19f0b65fd0-9b395bc164.clean\SMP\libgmp.vcxproj]

       “C:\dev\vcpkg\buildtrees\gmp\x64-windows-rel\19f0b65fd0-9b395bc164.clean\SMP\libgmp.sln”(Rebuild 目标) (1) ->
       “C:\dev\vcpkg\buildtrees\gmp\x64-windows-rel\19f0b65fd0-9b395bc164.clean\SMP\libgmp.vcxproj”(Rebuild 目标) (2) ->
         cl : command line warning D9025: overriding '/Dinline=__inline' with '/Uinline' [C:\dev\vcpkg\buildtrees\gmp\x64-windows-rel\19f0b65fd0-9b395bc164.clean\SMP\libgmp.vcxproj]
         cl : command line warning D9025: overriding '/Dinline=__inline' with '/Uinline' [C:\dev\vcpkg\buildtrees\gmp\x64-windows-rel\19f0b65fd0-9b395bc164.clean\SMP\libgmp.vcxproj]
         cl : command line warning D9025: overriding '/Dinline=__inline' with '/Uinline' [C:\dev\vcpkg\buildtrees\gmp\x64-windows-rel\19f0b65fd0-9b395bc164.clean\SMP\libgmp.vcxproj]
         cl : command line warning D9025: overriding '/Dinline=__inline' with '/Uinline' [C:\dev\vcpkg\buildtrees\gmp\x64-windows-rel\19f0b65fd0-9b395bc164.clean\SMP\libgmp.vcxproj]
         cl : command line warning D9025: overriding '/Dinline=__inline' with '/Uinline' [C:\dev\vcpkg\buildtrees\gmp\x64-windows-rel\19f0b65fd0-9b395bc164.clean\SMP\libgmp.vcxproj]

       “C:\dev\vcpkg\buildtrees\gmp\x64-windows-rel\19f0b65fd0-9b395bc164.clean\SMP\libgmp.sln”(Rebuild 目标) (1) ->
       “C:\dev\vcpkg\buildtrees\gmp\x64-windows-rel\19f0b65fd0-9b395bc164.clean\SMP\libgmp.vcxproj”(Rebuild 目标) (2) ->
       (Link 目标) -> 
         hamdist.obj : warning LNK4078: multiple '.rdata' sections found with different attributes (C0500040) [C:\dev\vcpkg\buildtrees\gmp\x64-windows-rel\19f0b65fd0-9b395bc164.clean\SMP\libgmp.vcxproj]

       “C:\dev\vcpkg\buildtrees\gmp\x64-windows-rel\19f0b65fd0-9b395bc164.clean\SMP\libgmp.sln”(Rebuild 目标) (1) ->
       “C:\dev\vcpkg\buildtrees\gmp\x64-windows-rel\19f0b65fd0-9b395bc164.clean\SMP\libgmp.vcxproj”(Rebuild 目标) (2) ->
       (Link 目标) -> 
         LINK : fatal error LNK1158: cannot run 'rc.exe' [C:\dev\vcpkg\buildtrees\gmp\x64-windows-rel\19f0b65fd0-9b395bc164.clean\SMP\libgmp.vcxproj]

**Additional context**
-- Building SMP/libgmp.sln for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: msbuild C:/dev/vcpkg/buildtrees/gmp/x64-windows-rel/19f0b65fd0-9b395bc164.clean/SMP/libgmp.sln /p:Configuration=ReleaseDLL /p:YasmPath=C:\\dev\\vcpkg\\installed\\x64-windows\\share\\yasm-tool\\..\\..\\tools\\yasm-tool\\yasm.exe /t:Rebuild /p:Platform=x64 /p:PlatformToolset=v142 /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /p:WindowsTargetPlatformVersion=10.0.19041.0 /p:VcpkgTriplet=x64-windows /p:VcpkgInstalledDir=C:/dev/vcpkg/installed /p:VcpkgManifestInstall=false /m /p:ForceImportBeforeCppTargets=C:/dev/vcpkg/scripts/buildsystems/msbuild/vcpkg.targets /p:VcpkgApplocalDeps=false
    Working Directory: C:/dev/vcpkg/buildtrees/gmp/x64-windows-rel/19f0b65fd0-9b395bc164.clean
    Error code: 1

**Comment by PhoebeHui** [comment]
@xulincai, could you reinstall windows sdk via VS installer and try again? I can't repro this issue locally.

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community>where rc.exe
C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64\rc.exe
C:\Program Files (x86)\Windows Kits\10\bin\x64\rc.exe

**Comment by PhoebeHui** [comment]
@xulincai, does this still be a problem for you?

**Comment by PhoebeHui** [comment]
@xulincai, please reopen this issue if it still be a problem for you.
