### ISSUE TITLE
[blas:x64-windows] build failure

### ISSUE THREAD

**Issue by BorjaFrade** [microsoft/vcpkg#19707]
**Host Environment**
- OS: Windows 10 64bits
- Compiler: Visual Studio 2022

**To Reproduce**
.\vcpkg.exe install suitesparse:x64-windows

**Failure logs** 
PS C:\Repository\vcpkg> .\vcpkg.exe install suitesparse:x64-windows
Computing installation plan...
The following packages will be built and installed:
  * blas[core]:x64-windows -> 1
  * lapack[core]:x64-windows -> 3#1
  * lapack-reference[blas-select,core,noblas]:x64-windows -> 3.8.0#5
  * metis[core]:x64-windows -> 5.1.0#7
    suitesparse[core]:x64-windows -> 5.8.0#1
  * vcpkg-gfortran[core]:x64-windows -> 3
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\brodf_773sidp\AppData\Local\vcpkg\archives\e2\e258752e19dec81afc502e9ff815c11753346e9d758ebc62de18698f114e6813.zip
Could not locate cached archive: C:\Users\brodf_773sidp\AppData\Local\vcpkg\archives\14\142680439940ba63c11d464fba2306eb21b69bbfcea750ab22fb5584859d300f.zip
Could not locate cached archive: C:\Users\brodf_773sidp\AppData\Local\vcpkg\archives\a0\a0c5e049901e7ae70d77d6dca2cc4439ac39a1721f5b75d88f10d8ee3dc338a6.zip
Could not locate cached archive: C:\Users\brodf_773sidp\AppData\Local\vcpkg\archives\14\1451cfb9c4a4f8d0876958618009e564fe67beec93159c1ebfc186c7d74eeba4.zip
Could not locate cached archive: C:\Users\brodf_773sidp\AppData\Local\vcpkg\archives\e4\e42946462824583cfde511be8eaddaeb9bf35627b71c383ff42c7e17709ad003.zip
Could not locate cached archive: C:\Users\brodf_773sidp\AppData\Local\vcpkg\archives\0e\0e874ed2e894ca85a9a5f2778632b5389742f715034b039f9344a1e99910e1c2.zip
Starting package 1/6: blas:x64-windows
Building package blas[core]:x64-windows...
CMake Error at scripts/cmake/vcpkg_configure_cmake.cmake:194 (message):
  Unable to determine appropriate generator for: Windows-x64-v143
Call Stack (most recent call first):
  ports/blas/portfile.cmake:4 (vcpkg_configure_cmake)
  scripts/ports.cmake:140 (include)

Error: Building package blas:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: blas:x64-windows
  Vcpkg version: 2021-08-12-85ab112d5ee102bc6eac8cdbbfdd173a71374e04

**Comment by PhoebeHui** [comment]
We have PR https://github.com/microsoft/vcpkg/pull/19088 to support this!

As a workaround, you can "set(VCPKG_PLATFORM_TOOLSET v143)' in triplet file and try again?

**Comment by PhoebeHui** [comment]
This issue should be fixed now.
