### ISSUE TITLE
[yaml-cpp] Application links always against release version

### ISSUE THREAD

**Issue by Carbenium** [microsoft/vcpkg#19701]
**Describe the bug**
Since yaml-cpp got upgraded to 0.7.0 in https://github.com/microsoft/vcpkg/pull/19272, projects built in `Debug` mode link against the release version of the library leading to ABI incompatibilities.

Below a shortened sample output during build of the application in `Debug` mode. Notice how it is correctly linking against the debug build of `boost` but uses the release version of `yaml-cpp`.

` [...]  -- C:\PROGRA~2\MICROS~4\2019\COMMUN~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\link.exe  [...]  vcpkg_installed\x64-windows\debug\lib\boost_program_options-vc140-mt-gd.lib  vcpkg_installed\x64-windows\lib\yaml-cpp.lib  [...]`

Also `yaml-cppd.dll` is not copied to the output directory.

**Environment**
- OS: Windows
- Compiler: MSVC 19.29.30133

**To Reproduce**
1. ./vcpkg install yaml-cpp
2. Build application in debug mode

**Expected behavior**
Application links against debug version of yaml-cpp and `yaml-cppd.dll` is copied to the output directory.

**Comment by autoantwort** [comment]
Do you have a custom cmake file for yaml or how do you find the lib? I think the debug lib is called `libyaml-cppd` (at least on mac)

**Comment by autoantwort** [comment]
Can you test #19703?

**Comment by Carbenium** [comment]
> 
> 
> Do you have a custom cmake file for yaml or how do you find the lib? I think the debug lib is called `libyaml-cppd` (at least on mac)

Nope, no custom find module.

> 
> 
> Can you test #19703?

Thanks for the quick fix! It resolves the issue for me. Application build tested in `Debug` and `RelWithDebInfo` configuration. It correctly links against `yaml-cppd.dll` with the former config and against `yaml-cpp.dll` with the latter. Can't test with other OSs though, since I'm using vcpkg only on Windows.
