### ISSUE TITLE
[gstreamer:arm64-windows] build failure

### ISSUE THREAD

**Issue by MarkVabulas** [microsoft/vcpkg#19717]
**Host Environment**
- OS: Windows 10 Pro 21H1
- Compiler: MSVC v142 Visual Studio 2019 16.11.1

**To Reproduce**
`./vcpkg --triplet=arm64-windows install gstreamer`

**Failure logs** 
Fails when trying to install x264, or fontconfig, depending on the order it tries to install them.

> -- Building arm64-windows-dbg
> CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:155 (message):
>     Command failed: D:/vcpkg/downloads/tools/msys2/2f5e2150b81fcd06/usr/bin/make.exe -j 13 --trace -f Makefile all
>     Working Directory: D:/vcpkg/buildtrees/fontconfig/arm64-windows-dbg
>     See logs for more information:
>       D:\vcpkg\buildtrees\fontconfig\build-arm64-windows-dbg-out.log
>       D:\vcpkg\buildtrees\fontconfig\build-arm64-windows-dbg-err.log
> 
> Call Stack (most recent call first):
>   scripts/cmake/vcpkg_build_make.cmake:190 (vcpkg_execute_build_process)
>   scripts/cmake/vcpkg_install_make.cmake:26 (vcpkg_build_make)
>   ports/fontconfig/portfile.cmake:47 (vcpkg_install_make)
>   scripts/ports.cmake:140 (include)
> 
> 
> Error: Building package fontconfig:arm64-windows failed with: BUILD_FAILED
> Please ensure you're using the latest portfiles with `.\vcpkg update`, then
> submit an issue at https://github.com/Microsoft/vcpkg/issues including:
>   Package: fontconfig:arm64-windows
>   Vcpkg version: 2021-08-12-85ab112d5ee102bc6eac8cdbbfdd173a71374e04

**Additional context**
No other context.  The arm64-windows builds should probably not try to build any of the items with mingw dependencies, because they couldn't be used anyway.  See here for more information: [https://gstreamer.freedesktop.org/download/](GStreamer prebuild libraries download page)  (Quote: "UWP apps cannot use plugins that use dependencies built with MinGW because of forbidden APIs. Hence, these plugins are omitted from the binaries.")  I realize this says UWP, but arm64-windows doesn't really exist without some level of UWP awareness on supported operating systems.
Additionally, it's reported on vcpkg.io that fontconfig is not a supported arm64-windows port, but that gstreamer **apparently** does work.

**Comment by JackBoosY** [comment]
Yeah... the mingW doesn't fit uwp now.

**Comment by JackBoosY** [comment]
We should make fontconfig to support arm.
