### ISSUE TITLE
manifest feature doesn't support "supports" field

### ISSUE THREAD

**Issue by mathisloge** [microsoft/vcpkg#19716]
**Describe the bug**
In https://github.com/microsoft/vcpkg/blob/master/docs/users/manifests.md#features-and-default-features it is stated, that the feature field have a `supports` field. However if adding this field, `vcpkg x-add-version <port>` and `vcpkg format-manifest <port>` will fail. 

Example with the port `comms`: 

vcpkg.json: 
```json
{
  "name": "comms",
  "version-semver": "3.4.0",
  "features": {
    "tools": {
      "description": "Builds CommsChampion tools",
      "supports": "!static",
      "dependencies": [
        "qt5-base"
      ]
    }
  }
}
```

Error message from `format-manifest`
```
.\vcpkg.exe format-manifest .\ports\comms\vcpkg.json
Failed to parse manifest file: D:\dev\vcpkg_mapnik\.\ports\comms\vcpkg.json
Errors occurred while parsing D:\dev\vcpkg_mapnik\.\ports\comms\vcpkg.json
    $.features.tools (a feature): unexpected field 'supports', did you mean 'description'?
```

Error message from `x-add-version`
```
 .\vcpkg.exe x-add-version comms --overwrite-version 
Error: Couldn't load port `comms`.
```

**Environment**
- OS: Windows
.\vcpkg.exe --version                               
Vcpkg package management program version 2021-08-12-85ab112d5ee102bc6eac8cdbbfdd173a71374e04

**Expected behavior**
I would expect to support the `supports` field.

Related PR https://github.com/microsoft/vcpkg/pull/19581

**Comment by dg0yt** [comment]
Basically a duplicate of #17651.

Note that `supports` has only limited practical effects IIRC:
- vcpkg.io website
- CI testing

In one case, I added a `$supports` field instead IIRC.

**Comment by mathisloge** [comment]
wouldn't (e.g. taken above example) `vcpkg install comms[tools]:x64-windows-static` fail if someone wants to install the port?

**Comment by mathisloge** [comment]
will close this in favor of #17651

**Comment by autoantwort** [comment]
> wouldn't (e.g. taken above example) `vcpkg install comms[tools]:x64-windows-static` fail if someone wants to install the port?

If it is implemented it should then fail, yes

**Comment by dg0yt** [comment]
> wouldn't (e.g. taken above example) `vcpkg install comms[tools]:x64-windows-static` fail if someone wants to install the port?

I don't see such behaviour. If you want a reliable error message, it has to be added to the portfile (`vcpkg_fail_port_install`).

 But please verify yourself.

**Comment by mathisloge** [comment]
> > wouldn't (e.g. taken above example) `vcpkg install comms[tools]:x64-windows-static` fail if someone wants to install the port?
> 
> I don't see such behaviour. If you want a reliable error message, it has to be added to the portfile (`vcpkg_fail_port_install`).
> 
> But please verify yourself.

Currently it wouldn't fail (root manifest `supports`). But from a user perspective this would be desirable. At least a warning should be printed when trying to install (classic or manifest mode) a port which is not supported.

**Comment by autoantwort** [comment]
Maybe I have time to implement that next week, but the install code is currently 2500 lines long with literally no comment. But imho it should be an error. Then `vcpkg_fail_port_install` is also not necessary anymore.
