### ISSUE TITLE
I add a LightGBM port in vcpkg, it can be complied, but it doesn't have the "abi" hash, and it won't be saved in /Appdata/local/vcpkg/achieves

### ISSUE THREAD

**Issue by wobuxie1997** [microsoft/vcpkg#19711]
here is the termminal output:

> The following packages will be rebuilt:
    lightgbm[core]:x86-windows -> 3.2.1#7 -- D:\code\windows\thirdparty_supervisor\vcpkg_overlay\ports\lightgbm
Starting package 1/2: lightgbm:x86-windows
Removing package lightgbm:x86-windows...
Removing package lightgbm:x86-windows... done
Elapsed time for package lightgbm:x86-windows: 19.44 ms
Could not locate cached archive: C:\Users\FP6P2D3\AppData\Local\vcpkg\archives\.zip
Starting package 2/2: lightgbm:x86-windows
Building package lightgbm[core]:x86-windows...
-- [OVERLAY] Loading triplet configuration from: D:\code\windows\thirdparty_supervisor\vcpkg_overlay\triplets\x86-windows.cmake
-- Installing port from location: D:\code\windows\thirdparty_supervisor\vcpkg_overlay\ports\lightgbm
-- Using cached E:/git/devtools/.cache/downloads/LightGBM-3.2.1.zip
-- Cleaning sources at D:/code/windows/thirdparty_supervisor/vcpkg/buildtrees/lightgbm/src/LightGBM-3-2ab1f16ea6.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/git/devtools/.cache/downloads/LightGBM-3.2.1.zip
-- Using source at D:/code/windows/thirdparty_supervisor/vcpkg/buildtrees/lightgbm/src/LightGBM-3-2ab1f16ea6.clean
-- Found external ninja('1.10.2').
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Restarting Build without parallelism because memory exceeded
-- Building x86-windows-rel
-- Installing: D:/code/windows/thirdparty_supervisor/vcpkg/packages/lightgbm_x86-windows/share/lightgbm/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package lightgbm[core]:x86-windows... done
Installing package lightgbm[core]:x86-windows...
Installing package lightgbm[core]:x86-windows... done
Elapsed time for package lightgbm:x86-windows: 1.177 min

i don't know why LightGBM is going to be removed every times i try to install it.
you can see that:

> Could not locate cached archive: C:\Users\FP6P2D3\AppData\Local\vcpkg\archives\.zip

the .zip don't have the abi prefix (or something else).

**Comment by wobuxie1997** [comment]
> Package: lightgbm
Version: 3.2.1
Port-Version: 7
Architecture: x86-windows
Multi-Arch: same
Description: LightGBM is a gradient boosting framework that uses tree based learning algorithms.
Type: Port
Status: install ok installed

> Package: kenlm
> Version: 20200924
> Architecture: x86-windows
> Multi-Arch: same
> Abi: 8154c8a9a3031e809325584af732c1ba350c3bc8
> Description: KenLM: Faster and Smaller Language Model Queries
> Type: Port
> Status: install ok installed

here is some message in /vcpkg/status, you can see kenlm has abi field, but lightgbm not

**Comment by wobuxie1997** [comment]
is there any way to make LightGBM not be rebuilt every times?

**Comment by PhoebeHui** [comment]
@wobuxie1997, could you share us the portfile.cmake and vcpkg.json for the port? then I can try it locally.

**Comment by wobuxie1997** [comment]
> vcpkg_download_distfile(ARCHIVE
>     URLS "https://github.com/wobuxie1997/buildtools/raw/master/source/LightGBM-3.2.1.zip"
>     FILENAME "LightGBM-3.2.1.zip"
>     SHA512 bd167956d7b0178af2743e15ae88da5cf4893b3d8353c501215dec2b57556c5a4ec855164fa9f91cd19c17357cc6f6bc8abcffa9975501a596007f4b0a50183b
> )
> 
> vcpkg_extract_source_archive_ex(
>     OUT_SOURCE_PATH SOURCE_PATH
>     ARCHIVE ${ARCHIVE}
> )
> 
> file(COPY ${CMAKE_CURRENT_LIST_DIR}/fmt DESTINATION ${SOURCE_PATH}/external_libs/fmt/include/)
> file(COPY ${CMAKE_CURRENT_LIST_DIR}/fast_double_parser.h DESTINATION ${SOURCE_PATH}/external_libs/fast_double_parser/include/)
> file(COPY ${CMAKE_CURRENT_LIST_DIR}/Eigen DESTINATION ${SOURCE_PATH}/external_libs/eigen/)
> file(COPY ${CMAKE_CURRENT_LIST_DIR}/CMakeLists.txt DESTINATION ${SOURCE_PATH}/)
> 
> vcpkg_configure_cmake(
>     SOURCE_PATH ${SOURCE_PATH}
> )
> 
> vcpkg_install_cmake()
> 
> vcpkg_copy_pdbs()
> 
> file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")
> 
> \# License
> file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)

this is my portfile.cmake, i use the CONTROL file rather the vcpkg.json

> Source: lightgbm
> Version: 3.2.1
> Port-Version: 7
> Homepage: https://github.com/microsoft/LightGBM
> Description: LightGBM is a gradient boosting framework that uses tree based learning algorithms.

**Comment by wobuxie1997** [comment]
@PhoebeHui
i also add a FastText port, the portfile.cmake and CONTROL are just like above, but it works fine, needn't rebuild every times

**Comment by PhoebeHui** [comment]
@wobuxie1997, since it's your personal project, so I can't download the source locally.

Questions for further investigation:
1. What's the vcpkg version, do you use latest vcpkg source(git pull and bootstrap-vcpkg.bat).
2. It looks you test the port via overlay ports, what's command do you execute?
3. could you add '--debug' to the install command and provide the output? eg: './vcpkg install lightgbm --debug'.

I just changed sqlite3 to sqlite4 to use the overlay, and it works correctlly.


```
Package: sqlite4
Version: 3.35.5
Architecture: x86-windows
Multi-Arch: same
Abi: e236e57dc73208df0e3f6b719f704b46ae325b4290d7ce9f42f311b3c1c55cb8
Description: SQLite is a software library that implements a self-contained, serverless, zero-configuration, transactional SQL database engine.
Type: Port
Status: purge ok not-installed
```

**Comment by wobuxie1997** [comment]
1. My vcpkg source is from commit beb56f9d6, sorry i can't pull for some reason.
2. The command i execute is "vcpkg --overlay-ports="overlay_path" install", it will install all overlay ports packages
3. I add the "--debug" in the cammand, and I find these:
> [DEBUG] <abientries for lightgbm:x86-windows>
> [DEBUG]   1CONTROL|019dcc6d9dd0f13ee0d277cbe8555f6b20593495
> [DEBUG]   ArithmeticSequence.h|4c5b9934003f3cf41f512fc56394aca0403d374b
> [DEBUG]   Array.h|6299b8fb10493693aa3a134d1fce6e1ce2bb72ed
> [DEBUG]   ArrayBase.h|2b39d97b2f9bbc80df925bf8298cd4997d6eb24d
> [DEBUG]   ArrayWrapper.h|abc01306c2c88617296c607f60da3905338b5ef3
> [DEBUG]   Assign.h|c3dc72af964abbacffdc096ff3f3c74bd616992b
> [DEBUG]   AssignEvaluator.h|4898743d107e08fd29b062fb4db4d8844767135e
> [DEBUG]   Assign_MKL.h|f8fd1b4559e967a1bb9279f6930b18a80945f45d
> [DEBUG]   BFloat16.h|2e45db5978bcf3a61afe4f58126cd3ab32e352d1
> [DEBUG]   BandMatrix.h|9febdd95e275b21464d697c67705c8aa5f275b41
> [DEBUG]   Block.h|55bd3ac0f702ec99d355457eeaf2b46e0a6e51cb
> [DEBUG]   BooleanRedux.h|d1581f36e94b954ce7a377bb9c74e8a626a318ad
> [DEBUG]   CMakeLists.txt|396b6940a0c1309074154bcb5b15bbd434e5110b
> [DEBUG]   Cholesky|e9ac2a88646971d768f4ca97e8f9317732212291
> [DEBUG]   CholmodSupport|ecaf6289f4585c2b8e7305df93956c55373264b0
> [DEBUG]   CholmodSupport.h|48aa2626e43e63484f779bab2262fd43ae296fbd
> [DEBUG]   CommaInitializer.h|e72690ea6aa13bae4c3bd157daf292437e2fe53d
> [DEBUG]   Complex.h|356e179b01b4a45be99403a45658173cda6739e4
> [DEBUG]   Complex.h|4c70a412e53e8beaf52bf52dd9ffb8459712017f
> [DEBUG]   Complex.h|5d07f83f65aa25d90b956c5401ea78cd23ffbc09
> [DEBUG]   Complex.h|6032856a5de9da4d4ee65e9f36c5290381f9cc5f
> [DEBUG]   Complex.h|9eccc220097b34ed566e1817027eaf4d936b4ac8
> [DEBUG]   Complex.h|c18745f3c5f7b4a17df942b841635ac098a32216
> [DEBUG]   Complex.h|cef8ac52ceba71927b5fb467664ce6ed96e0806b
> [DEBUG]   Complex.h|e2a5ed575e29a0c7b66b980b6a3ef31b96a8a359
> [DEBUG]   ConditionEstimator.h|ed10fa9d1d3a3b816122ee705a6c62c285cc6650
> [DEBUG]   ConjHelper.h|63891967a50ce47bed3d38cb8ae193d21ed8899f
> [DEBUG]   Core|3d2ecc630d4b15686d87bfafcacf9584dd71732b
> [DEBUG]   CoreEvaluators.h|d475c0e385257dc2e4cd90df8a95b6faebc4d865
> [DEBUG]   CoreIterators.h|99900468b6255245d76efbad126b6a1792a5a1b4
> [DEBUG]   CwiseBinaryOp.h|97ba84fb51e6410be6d58cd74cacbbae04a677c7
> [DEBUG]   CwiseNullaryOp.h|80bfdbcb0b1b2c97ae04e9f563a960cf67e4bd02
> [DEBUG]   CwiseTernaryOp.h|4aeb2a5f2bd1920eeda6d74af52aedd9fb11b62e
> [DEBUG]   CwiseUnaryOp.h|2e049ff4e8ed5ff734e39b4a5ba60817d8d4fa22
> [DEBUG]   CwiseUnaryView.h|450cbc2f558abf18e40aaefd06cdf91c82c453d1
> [DEBUG]   Dense|f1c14b122803ec853b0b153cd905e01bcc978dda
> [DEBUG]   DenseBase.h|d0e39f657381d5b00df31a4865fc5e08ded53026
> [DEBUG]   DenseCoeffsBase.h|7eeb5ffe9a7f4701c73082d6df50f7bf1cc7aba0
> [DEBUG]   DenseStorage.h|7f8c8e6598134532a4ef8bbdee770d2f206f2185
> [DEBUG]   Eigen|8c8b3412ebc995167e23f20558e6dae072b9ccb6
> [DEBUG]   Eigenvalues|79b02228b1748efe3fe6b5b4b52c8a571c677e71
> [DEBUG]   GeneralBlockPanelKernel.h|231eec17ab0a399cf2472ce94b82dc1b3c4823d2
> [DEBUG]   GenericPacketMathFunctions.h|d71441d87fa15d54f58903b84dcaffd5177ad3eb
> [DEBUG]   GenericPacketMathFunctionsFwd.h|6a2d56d32e2dc83ccc7c378668bd48bb1258f9af
> [DEBUG]   Geometry|a8f496efd59a0fe1445553369c38f19d791f4e91
> [DEBUG]   Half.h|3b26b075945788a33d0067b9b8bd882dec8dc648
> [DEBUG]   Householder|4501209f892ffaf9a1cacc1ed440e843cc4e07de
> [DEBUG]   InteropHeaders.h|679e831eb57a24bd3cdf9df0c1d7bab9750e9db0
> [DEBUG]   IterativeLinearSolvers|659ad5b170df03dae1980d653ffd628812e1d656
> [DEBUG]   Jacobi|3232d14286284a0f8a30cc97a2749eaafea99a10
> [DEBUG]   KLUSupport|30d2b9b58f373b70b59019ad11070abe82b6a02f
> [DEBUG]   LDLT.h|e6f63c9fec2f123ec2ae3f4046b9f6c775c3239a
> [DEBUG]   LLT.h|2958dc7bea6c8b080f36585aa40938087916f2dd
> [DEBUG]   LLT_LAPACKE.h|cb9cedd62623529c6a076ac329a514b1e0a8e13f
> [DEBUG]   LU|c90943e3bf69a96d0b6d7b0e85ba683fb8a3ae0d
> [DEBUG]   MathFunctions.h|0c829ad3158893a12da7c7d6cc5bfecb5205c89f
> [DEBUG]   MathFunctions.h|2a594a7dd73bab65f690d6a3ce1e7c0d96279221
> [DEBUG]   MathFunctions.h|455e92318280f2fa4de2c136a6fe05109f74a3da
> [DEBUG]   MathFunctions.h|6875adbb2be1fcd2152f2c44fcbe98644d543550
> [DEBUG]   MathFunctions.h|9f01827b10a01b7d38ec5105a5b742a454b9d047
> [DEBUG]   MathFunctions.h|a8796953e97f1fd05da07ee644438d1c67edfd47
> [DEBUG]   MathFunctions.h|ac62554021d5b8306373210a32010ea861b28d5c
> [DEBUG]   MathFunctions.h|d0af2ad17d13dc3c127a19bc37a48d283f7bb802
> [DEBUG]   MathFunctions.h|d6bbb1d3d852dbd5252c4cab5220494ba8800f0e
> [DEBUG]   MathFunctions.h|dfb0316070d2974ae6054192554f1b20cb99bec7
> [DEBUG]   MatrixProduct.h|01fc9c8673b0f3c40731d51ab57171efaad556ad
> [DEBUG]   MatrixProductCommon.h|1c3b5ba21ca39e2bc5dd4ad40f1f180e123cfbb3
> [DEBUG]   MatrixProductMMA.h|ed5835e39eca7bd5ec8ddc83511ab47974c6d346
> [DEBUG]   MetisSupport|d9320c3937023f357a56d1d0c5c31babbdd4025c
> [DEBUG]   OrderingMethods|627f8f5eb5a973fcfaa977e266ade011c7535450
> [DEBUG]   PaStiXSupport|38f5193f0ec0cea713d8e2a5d39b0e1e574e63e6
> [DEBUG]   PacketMath.h|01c9847dc4961cde0c70a35ec41e5e2169a344b1
> [DEBUG]   PacketMath.h|18cf708ca3e3602a9cdc89f00bc77a55899d77ba
> [DEBUG]   PacketMath.h|45509a6b7725d5786f4f7c9a1871e607d1deb06e
> [DEBUG]   PacketMath.h|4dfe196ad8d6968d6fca7ba9a05263e1a813c904
> [DEBUG]   PacketMath.h|80a3a9ee3c044df3b46f60bab105d1995a772f5c
> [DEBUG]   PacketMath.h|87168c1803d0c328134e3e62f6c4adeb0b3e75bf
> [DEBUG]   PacketMath.h|a85033a50c00ebea001e85e81acf66344245ab55
> [DEBUG]   PacketMath.h|c13005d2486d68eee43375e8ba52cf7b39c2c5a8
> [DEBUG]   PacketMath.h|eef59c2432bd52b96d3e07849cb3bb585698a4e1
> [DEBUG]   PacketMath.h|f1e03e77b6da2b3b496737ffab33b991e668c6cb
> [DEBUG]   PardisoSupport|d2f1e26cb5eca2cf62a460b1f6c137781f0cd9a6
> [DEBUG]   QR|95bfdd5609f89e94a972e80db7de3419a7117a24
> [DEBUG]   QtAlignedMalloc|b39855794a55da1cfccaf1fd3def08742c4b5df3
> [DEBUG]   SPQRSupport|aab816a0411d85008662d4348d0c83f7bd2a8baf
> [DEBUG]   Settings.h|eda877889beacf4c13f2d2aec04609c070be907c
> [DEBUG]   Sparse|ab3cd08c627314b21b9569c3ca83c92701676946
> [DEBUG]   SparseCholesky|f9a2890b7c70e1e21ad61679ab203ca4cc873de4
> [DEBUG]   SparseCore|15ac8349d246f2e8add5fe596604a6a04f23f888
> [DEBUG]   SparseLU|f59ac5ab83b1966f61f13ed1d89d943df7f39f5c
> [DEBUG]   SparseQR|379bc1da577d8148b9380c3a4f2494093d47d97e
> [DEBUG]   SyclMemoryModel.h|7fdc05c7e9819c7d43d499af7efd7eb86165aa8c
> [DEBUG]   TypeCasting.h|1479c67a9985ba22b793d8a18da9a8cd15e5ab60
> [DEBUG]   TypeCasting.h|3f4ec572e827f0d9a6eeb95075e2a8590ab6f131
> [DEBUG]   TypeCasting.h|6c8e9a27aa3c9e314d9d712c8a9523044b9581a3
> [DEBUG]   TypeCasting.h|72f14af6c96bc6bf922e89d858d10bad15374ab7
> [DEBUG]   TypeCasting.h|bbc31e71140d7f293fc27b929a02dbda702b07cd
> [DEBUG]   TypeCasting.h|c23ae6808d7444c1e6d8d04f6f3944e11b6ed844
> [DEBUG]   TypeCasting.h|cf766cca3af61fff011e8f27c3b763f206821388
> [DEBUG]   TypeCasting.h|e07202b6978f58b0def184e9e45ec1d8acc190c4
> [DEBUG]   cmake|3.19.2
> [DEBUG]   features|core
> [DEBUG]   math_constants.h|f778860cb2d61f09c4416219f6d428e3a636883f
> [DEBUG]   no_hash_max_portfile|
> [DEBUG]   post_build_checks|2
> [DEBUG]   powershell|7.1.0
> [DEBUG]   triplet|dd0b56725952b7ea4047a7a3bb367145a04c963f-a1c0eabb0c5177b6a8fb97a58ae398880c47b352-ac3a9e1ce50a5a4aff5ea3e8945aa7930ca6e260
> [DEBUG]   vcpkg_configure_cmake|9df1c6098c9f7f00ed45e5daa2e5c047d9e047a8
> [DEBUG]   vcpkg_copy_pdbs|77501408e9111fbc567621d90d587244ee4ccb3b
> [DEBUG]   vcpkg_download_distfile|9e59f2d7ac7193568b301812a84c7129d25c952f
> [DEBUG]   vcpkg_extract_source_archive|d800c9f9fc4df8eeeabc5acc8c8a337bafc9ab6d
> [DEBUG]   vcpkg_extract_source_archive_ex|cc8f8ace5195315de748ddf9898f6469843b8c27
> [DEBUG]   vcpkg_install_cmake|0ca42e314ef99ccbc75ace6664a7934f396ab391
> [DEBUG] </abientries>
> [DEBUG] Warning: abi keys are missing values:
>     no_hash_max_portfile

this is lightgbm's output, I can see the warning, but I don't know why this happened.

**Comment by wobuxie1997** [comment]
@PhoebeHui , Is this information helpful to you?

**Comment by wobuxie1997** [comment]
@PhoebeHui , I think I know the problem.
I read the build.cpp in vcpkg, and I find this

> // If there is an unusually large number of files in the port then
> // something suspicious is going on.  Rather than hash all of them
> // just mark the port as no-hash
> const int max_port_file_count = 100;

I have put too much files in the port, thanks for your help!

**Comment by PhoebeHui** [comment]
Glad you got the issue solved! Can I close this issue now?

**Comment by wobuxie1997** [comment]
Yes, you can close it.
Thank you again.

**Comment by PhoebeHui** [comment]
You're welcome! BTW, we have many blogs in https://www.cnblogs.com/vcpkg/ about vcpkg for Chinese users, you can reference them if you needed.
