### ISSUE TITLE
Port Request: DevIL

### ISSUE THREAD

**Issue by Lyrex** [Microsoft/vcpkg#1973]
DevIL is a cross-platform image library that in it's last version has been reworked to fully work with CMake.  
I would love to see it integrated into vcpkg.

The project URL is http://openil.sourceforge.net

Thank you

**Comment by xoviat** [comment]
@Lyrex mind sharing your port?

**Comment by Lyrex** [comment]
I coudln't get it fully working yet.
Linking statically still outputs some linking errors.

**Comment by KindDragon** [comment]
I think it's better than nothing. You can disable static linking at first

**Comment by Lyrex** [comment]
I made a PR (#2082) of my version of the port with static linking disabled.
Feel free to add or correct things.

**Comment by atkawa7** [comment]
@ras0219-msft should be closed
