### ISSUE TITLE
[yaml-cpp] build failure when compiling the `x64-windows-static` for debugging

### ISSUE THREAD

**Issue by jixingcn** [microsoft/vcpkg#19736]
**Host Environment**
- OS: Windows
- Compiler: vs2019

**To Reproduce**
`./vcpkg install yaml-cpp`

**Additional context**
The `yaml-cpp` doesn't copy `yaml-cpp-targets-debug.cmake` to `share\yaml-cpp\`.
So it is failed to compile the `x64-windows-static` for debugging.

**Comment by PhoebeHui** [comment]
@jixingcn, the PR has been merged, please get latest source and try again.
