### ISSUE TITLE
[log4cxx] failure to compile application with clang on Windows/VC2019

### ISSUE THREAD

**Issue by SergeiDelov** [microsoft/vcpkg#19730]
We have an application that uses log4cxx.
When I compile with clang on Windows VC2019 I observe the following error:
_[...]
  In file included from C:\vcpkg\installed\x64-windows\include\log4cxx/logger.h:30:
  In file included from C:\vcpkg\installed\x64-windows\include\log4cxx/helpers/appenderattachableimpl.h:27:
  In file included from C:\vcpkg\installed\x64-windows\include\log4cxx/spi/appenderattachable.h:30:
C:\vcpkg\installed\x64-windows\include\log4cxx\appender.h(140,1): error : explicit instantiation of 'allocator' not in a namespace enclosing 'std'
  LOG4CXX_LIST_DEF(AppenderList, AppenderPtr);
  ^
  C:\vcpkg\installed\x64-windows\include\log4cxx\log4cxx.h(91,45): note: expanded from macro 'LOG4CXX_LIST_DEF'
                  extern template class LOG4CXX_EXPORT std::allocator<T>; \
                                                            ^
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.27.29110\include\iosfwd(167,7): note: explicit instantiation refers here
  class allocator;
        ^_

I found this error appears because clang compiler included with Visual Studio has _MSC_VER macro defined.
(Intel icx compiler also has _MSC_VER macro defined on Windows)

The simple fix worked for me for both compilers:
(log4cxx.h, line 81)
`#elif` defined(_MSC_VER) __&& !defined(\_\_clang\_\_)__ && !defined(LOG4CXX_STATIC)

I didn't try to compile with LOG4CXX_STATIC defined, though.

Please apply this fix to github log4cxx sources.

**Comment by JackBoosY** [comment]
`__clang__` doesn't exists in log4cxx's headers, so I think the upstream doesn't consider this situation.
Please report this issue to log4cxx upstream, and we will update it when the upstream support clang.
