### ISSUE TITLE
[vs-yasm] build failure

### ISSUE THREAD

**Issue by 1144280511** [microsoft/vcpkg#19745]
**Host Environment**
- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**
`./vcpkg install xxxx`

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.
Package: vs-yasm:x64-windows
  Vcpkg version: 2021-08-12-85ab112d5ee102bc6eac8cdbbfdd173a71374e04

**Comment by autoantwort** [comment]
Please fill out the issue template, otherwise we can't help you :)

**Comment by JonLiu1993** [comment]
@1144280511,please provide us more infomation about your error, fill out the issue template
