### ISSUE TITLE
Header-only pybind11

### ISSUE THREAD

**Issue by twMr7** [microsoft/vcpkg#1974]
The current port of pybind11 is set to `Build-Depends: python3`, but I am not using python 3.6.1, and I prefer to reply on some python distributions that I used for a long time. I don't want to build python3 port in order to install pybind11.

Since pybind11 is a header-only library, I feel that it should make more sense to install pybind11 without depending on a specific version of python. Is there any use-case this dependency must be kept?

**Comment by twMr7** [comment]
Or, is there a way to tell vcpkg build system that my python3 port is already installed at a specific path?

**Comment by xoviat** [comment]
You could just use Python 3 rather than Python 2.7.

**Comment by twMr7** [comment]
@xoviat , I am not using Python 2.7. That is not what I have mentioned in my use-case.

For pybind11 to be useful in a project, the path to Python.h and pythonxx.lib must provide. I am aware of this dependency and trying to come up with a solution that won't affect other ports.

- I did a search over all CONTROL files. It turns out no any port depends on `pybind11`, and only port depends on `python3` is `pybind11`. 

- I installed pybind11 with `Build-Depends: python3` removed. From "config-x64-windows-rel-out.log", it shows that some cmake script can identify my Python installation correctly from registry.

so, I assumed it should work for vcpkg build system for user to assign an already installed Python to be used in python3 port.

**Comment by cmpute** [comment]
pybind11 needs to find PythonLibs, which is originally brought by python3 in vcpkg. If you want to use external python, then this is another issue described here #2974

**Comment by slyviacassell** [comment]
Hi, does this feature have been added to the vcpkg? I think building the addtional python just for using pybind11 is not necessay. We can use the python we have already installed if requied.

**Comment by NancyLi1013** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen.
