### ISSUE TITLE
cannot modify cairo-features.h

### ISSUE THREAD

**Issue by olilarkin** [Microsoft/vcpkg#1975]
i would like to modify cairo-features.h to include

#include <GL/glew.h>
#define CAIRO_HAS_GL_SURFACE 1

but whenever i do this the build fails, for whatever target

how can i build cairo using vcpkg with this setting?

thanks

**Comment by martin-s** [comment]
If you are talking from building cairo, then you can add a patch which adds this changes to the header file. This is port-specific and not related to vcpkg.
Do you have tried to build it yourself with these changes (without vcpkg)?

**Comment by Youlean** [comment]
Here is the commit that will enable OpenGL backend. https://github.com/Youlean/vcpkg/commit/8a28b17c6e2cb1bcc76267c6c9bf7b6745ab2509

I had some problems with glext.h so I needed to download glext.h, glcorearb.h, glxext.h, and wglext.h from http://www.opengl.org/registry/
Put the downloaded files to c:\Program Files (x86)\Windows Kits\10\Include\10.0.16299.0\um\gl\

**Comment by luzpaz** [comment]
https://github.com/Microsoft/vcpkg/issues/5284

**Comment by JackBoosY** [comment]
Hi @olilarkin , here is document:
https://github.com/Microsoft/vcpkg/blob/master/docs/examples/patching.md
If you have problem with build, it will help you make a patch to solve.

And port cairo is fixed, plz update vcpkg and rebuild it.
Thx.

**Comment by olilarkin** [comment]
well i believe that answers my question, closing
