### ISSUE TITLE
[abseil] apply patch failed

### ISSUE THREAD

**Issue by sunwangme** [Microsoft/vcpkg#1977]
-- Applying patch C:/projects/vcpkg/ports/abseil/fix-intrin.patch
-- Applying patch failed. This is expected if this patch was previously applied.

**Comment by sunwangme** [comment]
@ras0219-msft

**Comment by sunwangme** [comment]
@ras0219-msft

**Comment by ras0219-msft** [comment]
Thanks for opening an issue! This patch was upstreamed, so this was the expected behavior.
