### ISSUE TITLE
"Failed to store binary cache" warning while using cmake-gui and a user path containing a non ascii character

### ISSUE THREAD

**Issue by olafurw** [microsoft/vcpkg#19774]
**Describe the bug**
While generating a project that uses vcpkg using CMake GUI, a warning is displayed for each dependency. Here is an example.

Failed to store binary cache C:\Users\ï¿½lafur Waage\AppData\Local\vcpkg\archives\85\85e66e68e8491e807639e582790406d6bd370891f96550accdc22b020084e4fe.zip: The system cannot find the path specified.

The user path is C:\Users\Ólafur Waage but it is displayed like the log entry above.

This does not happen if I'm using git-bash and I run `cmake .. -G"Visual Studio 16 2019`

Could be a bug with cmake-gui and whatever environment they are using to run the scripts.

I tried searching for this kind of issue here and could not find any, feel free to close if you know about it and it's a cmake issue only.

**Environment**
- OS: Windows 10
- Compiler: MSVC 2019
- CMake: 3.21.2

**Failure logs** 
Log entry pasted above.

**Comment by NancyLi1013** [comment]
Hi @olafurw 

Thanks for posting this issue.

Since your path contains non-ASCII characters, please try to change your path and rebuild your project.

Seems cmake also doesn't support non-ASCII characters, please see https://gitlab.kitware.com/cmake/cmake/-/issues/21478.

**Comment by olafurw** [comment]
Hey Nancy,

I have a workaround as I said in the issue, cmake is fine with the non ascii path in the command line version, it's only happening in the GUI version.
I was only posting to check if you wanted to know about this and there was some detection you could do based on the environment vcpkg was being run in.

Cheers.

**Comment by olafurw** [comment]
Some CMake issues that are related. They say they have fixed these kinds of issues. Not sure what's going on then. I might send an issue on their end.

https://cmake.org/Bug/view.php?id=13880

https://gitlab.kitware.com/cmake/cmake/-/commit/cdc29c3

**Comment by JackBoosY** [comment]
_C:\Users\ï¿½lafur Waage\AppData\Local\vcpkg\archives_.
Currently, vcpkg doesn't support a path that contains non-ASCII char, and also, some compilers may not support it.
But it does a vcpkg bug.

**Comment by NancyLi1013** [comment]
Since it's duplicated to #5995, let's track this issue there.
