### ISSUE TITLE
[matplotlib-cpp] To display Inconsistant graph.

### ISSUE THREAD

**Issue by varshapratapchavan** [microsoft/vcpkg#19772]
In my application, I want to display run time graphs. But the graphs can have a break in between i.e. data may not be available for some duration. I want to display this gap in my graph.

I want to use MATPLOTLIB library in my application which will run under Qt.

I am trying to use NUMCPP to create an array with breaks ( gaps) in my graph readings
Is it a right solution ? Or can you suggest a better option ?

While including of NUMCPP I faced different problems like mismatch of BOOST version & C++ Standards
So finally, I am still not able to build the solution

Kindly suggest an option / solution

Regards

Varsha

**Comment by JackBoosY** [comment]
Can you compare with the results of using pre-built binaries released upstream?
If it still exists, please report it upstream.

**Comment by JackBoosY** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
