### ISSUE TITLE
Building package boost-fiber:x64-windows-v142 failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by Tim-Mckinley** [microsoft/vcpkg#19775]
**Host Environment**
- OS: Windows 10
- Compiler: revision

**To Reproduce**
C:\src\slam6d-code-r2343-trunk\windows>build2.cmd
outdir: C:\dev
sourcedir: C:\src\slam6d-code-r2343-trunk
INFO: Could not find files for the given pattern(s).
vcpkgexe: C:\dev\3rdparty\vcpkg\vcpkg.exe
vcpkgdir: C:\dev\3rdparty\vcpkg
patching vcpkg...
'git' is not recognized as an internal or external command,
operable program or batch file.
'git' is not recognized as an internal or external command,
operable program or batch file.
copy triplets...
        1 file(s) copied.
        1 file(s) copied.
building vcpkg...

Building vcpkg.exe ...

**Failure logs** 
C:\src\slam6d-code-r2343-trunk\windows>build2.cmd
outdir: C:\dev
sourcedir: C:\src\slam6d-code-r2343-trunk
INFO: Could not find files for the given pattern(s).
vcpkgexe: C:\dev\3rdparty\vcpkg\vcpkg.exe
vcpkgdir: C:\dev\3rdparty\vcpkg
patching vcpkg...
'git' is not recognized as an internal or external command,
operable program or batch file.
'git' is not recognized as an internal or external command,
operable program or batch file.
copy triplets...
        1 file(s) copied.
        1 file(s) copied.
building vcpkg...

Building vcpkg.exe ...

  pch.cpp
  archives.cpp
  checks.cpp
  chrono.cpp
  cofffilereader.cpp
  downloads.cpp
  enums.cpp
  files.cpp
  hash.cpp
  json.cpp
  machinetype.cpp
  parse.cpp
  strings.cpp
  stringview.cpp
  system.cpp
  system.print.cpp
  system.process.cpp
  unicode.cpp
  binarycaching.cpp
  binaryparagraph.cpp
  build.cpp
  cmakevars.cpp
  commands.autocomplete.cpp
  commands.buildexternal.cpp
  commands.cache.cpp
  commands.ci.cpp
  commands.ciclean.cpp
  commands.contact.cpp
  commands.cpp
  commands.create.cpp
  commands.dependinfo.cpp
  commands.edit.cpp
  commands.env.cpp
  commands.exportifw.cpp
  commands.import.cpp
  commands.integrate.cpp
  commands.list.cpp
  commands.owns.cpp
  commands.porthistory.cpp
  commands.portsdiff.cpp
  commands.search.cpp
  commands.setinstalled.cpp
  commands.upgrade.cpp
  commands.version.cpp
  commands.xvsinstances.cpp
  dependencies.cpp
  export.cpp
  export.chocolatey.cpp
  export.prefab.cpp
  globalstate.cpp
  help.cpp
  input.cpp
  install.cpp
  logicexpression.cpp
  metrics.cpp
  packagespec.cpp
  paragraphparseresult.cpp
  paragraphs.cpp
  portfileprovider.cpp
  postbuildlint.buildtype.cpp
  postbuildlint.cpp
  remove.cpp
  sourceparagraph.cpp
  statusparagraph.cpp
  statusparagraphs.cpp
  tools.cpp
  triplet.cpp
  update.cpp
  userconfig.cpp
  vcpkgcmdarguments.cpp
  vcpkglib.cpp
  vcpkgpaths.cpp
  versiont.cpp
  visualstudio.cpp
  vcpkglib.vcxproj -> C:\dev\3rdparty\vcpkg\toolsrc\msbuild.x86.release\vcpkglib.lib
  vcpkg.cpp
  Generating code
  Previous IPDB not found, fall back to full compilation.
  All 18363 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Finished generating code
  vcpkg.vcxproj -> C:\dev\3rdparty\vcpkg\toolsrc\msbuild.x86.release\vcpkg.exe

Building vcpkg.exe... done.

C:\Program Files\CMake\bin\cmake.exe
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe
cmakeexe: cmake
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.
vcpkg update succeeded
There are no outdated packages.
vcpkg remove --outdated succeeded
All installed packages are up-to-date with the local portfiles.
vcpkg upgrade succeeded
Computing installation plan...
The following packages are already installed:
    zlib[core]:x64-windows-v142
The following packages will be built and installed:
    boost[core]:x64-windows-v142
  * boost-fiber[core]:x64-windows-v142
  * boost-flyweight[core]:x64-windows-v142
  * boost-geometry[core]:x64-windows-v142
  * boost-gil[core]:x64-windows-v142
  * boost-graph[core]:x64-windows-v142
  * boost-graph-parallel[core]:x64-windows-v142
  * boost-hana[core]:x64-windows-v142
  * boost-heap[core]:x64-windows-v142
  * boost-histogram[core]:x64-windows-v142
  * boost-hof[core]:x64-windows-v142
  * boost-icl[core]:x64-windows-v142
  * boost-interprocess[core]:x64-windows-v142
  * boost-local-function[core]:x64-windows-v142
  * boost-lockfree[core]:x64-windows-v142
  * boost-log[core]:x64-windows-v142
  * boost-metaparse[core]:x64-windows-v142
  * boost-msm[core]:x64-windows-v142
  * boost-nowide[core]:x64-windows-v142
  * boost-outcome[core]:x64-windows-v142
  * boost-parameter-python[core]:x64-windows-v142
  * boost-poly-collection[core]:x64-windows-v142
  * boost-polygon[core]:x64-windows-v142
  * boost-process[core]:x64-windows-v142
  * boost-program-options[core]:x64-windows-v142
    boost-python[core]:x64-windows-v142
  * boost-qvm[core]:x64-windows-v142
  * boost-safe-numerics[core]:x64-windows-v142
  * boost-scope-exit[core]:x64-windows-v142
  * boost-signals2[core]:x64-windows-v142
  * boost-sort[core]:x64-windows-v142
  * boost-stacktrace[core]:x64-windows-v142
  * boost-statechart[core]:x64-windows-v142
  * boost-static-string[core]:x64-windows-v142
  * boost-test[core]:x64-windows-v142
  * boost-timer[core]:x64-windows-v142
  * boost-type-erasure[core]:x64-windows-v142
  * boost-variant2[core]:x64-windows-v142
  * boost-vmd[core]:x64-windows-v142
  * boost-wave[core]:x64-windows-v142
  * boost-xpressive[core]:x64-windows-v142
  * boost-yap[core]:x64-windows-v142
    cgal[core]:x64-windows-v142
  * clapack[core]:x64-windows-v142
  * double-conversion[core]:x64-windows-v142
  * egl-registry[core]:x64-windows-v142
    eigen3[core]:x64-windows-v142
  * expat[core]:x64-windows-v142
    freeglut[core]:x64-windows-v142
  * freetype[bzip2,core,png]:x64-windows-v142
    glfw3[core]:x64-windows-v142
  * harfbuzz[core]:x64-windows-v142
  * icu[core]:x64-windows-v142
  * jasper[core]:x64-windows-v142
    libconfig[core]:x64-windows-v142
  * libffi[core]:x64-windows-v142
  * libjpeg-turbo[core]:x64-windows-v142
    libpng[core]:x64-windows-v142
  * libpq[core,openssl,zlib]:x64-windows-v142
  * libwebp[core,nearlossless,simd,unicode]:x64-windows-v142
    libzip[bzip2,core,default-aes,wincrypto]:x64-windows-v142
  * mpfr[core]:x64-windows-v142
    mpir[core]:x64-windows-v142
  * openblas[core]:x64-windows-v142
    opencv[core,dnn,jpeg,opengl,png,tiff,webp]:x64-windows-v142
  * opencv4[core,dnn,jpeg,opengl,png,tiff,webp]:x64-windows-v142
    opengl[core]:x64-windows-v142
  * pcre2[core]:x64-windows-v142
  * protobuf[core]:x64-windows-v142
    pthreads[core]:x64-windows-v142
    python3[core]:x64-windows-v142
    qt5[activeqt,core,declarative,essentials,imageformats,multimedia,networkauth,quickcontrols2,svg,tools]:x64-windows-v142
  * qt5-activeqt[core]:x64-windows-v142
  * qt5-base[core]:x64-windows-v142
  * qt5-declarative[core]:x64-windows-v142
  * qt5-imageformats[core]:x64-windows-v142
  * qt5-multimedia[core]:x64-windows-v142
  * qt5-networkauth[core]:x64-windows-v142
  * qt5-quickcontrols2[core]:x64-windows-v142
  * qt5-svg[core]:x64-windows-v142
  * qt5-tools[core]:x64-windows-v142
  * ragel[core]:x64-windows-v142
  * sqlite3[core]:x64-windows-v142
    suitesparse[core]:x64-windows-v142
  * tiff[core]:x64-windows-v142
    wxwidgets[core]:x64-windows-v142
Additional packages (*) will be modified to complete this operation.
Package zlib:x64-windows-v142 is already installed
Starting package 1/86: boost-fiber:x64-windows-v142
Building package boost-fiber[core]:x64-windows-v142...
-- Using cached C:/dev/3rdparty/vcpkg/downloads/boostorg-fiber-boost-1.73.0.tar.gz
-- Using source at C:/dev/3rdparty/vcpkg/buildtrees/boost-fiber/src/ost-1.73.0-19cdf62e42
-- Building x64-windows-v142-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: C:/dev/3rdparty/vcpkg/installed/x64-windows-v142/tools/boost-build/b2.exe --stagedir=C:/dev/3rdparty/vcpkg/buildtrees/boost-fiber/x64-windows-v142-rel/stage --build-dir=C:/dev/3rdparty/vcpkg/buildtrees/boost-fiber/x64-windows-v142-rel --user-config=C:/dev/3rdparty/vcpkg/buildtrees/boost-fiber/x64-windows-v142-rel/user-config.jam -j12 --debug-configuration --debug-building --debug-generators --disable-icu --ignore-site-config --hash -q -sZLIB_INCLUDE=C:/dev/3rdparty/vcpkg/installed/x64-windows-v142/include -sBZIP2_INCLUDE=C:/dev/3rdparty/vcpkg/installed/x64-windows-v142/include -sLZMA_INCLUDE=C:/dev/3rdparty/vcpkg/installed/x64-windows-v142/include -sZSTD_INCLUDE=C:/dev/3rdparty/vcpkg/installed/x64-windows-v142/include threading=multi threadapi=win32 runtime-link=shared link=shared address-model=64 architecture=x86 toolset=msvc -sZLIB_BINARY=zlib -sZLIB_LIBPATH=C:/dev/3rdparty/vcpkg/installed/x64-windows-v142/lib -sBZIP2_BINARY=bz2 -sBZIP2_LIBPATH=C:/dev/3rdparty/vcpkg/installed/x64-windows-v142/lib -sLZMA_BINARY=lzma -sLZMA_LIBPATH=C:/dev/3rdparty/vcpkg/installed/x64-windows-v142/lib -sZSTD_BINARY=zstd -sZSTD_LIBPATH=C:/dev/3rdparty/vcpkg/installed/x64-windows-v142/lib variant=release debug-symbols=on
    Working Directory: C:/dev/3rdparty/vcpkg/buildtrees/boost-fiber/src/ost-1.73.0-19cdf62e42/build
    Error code: 1
    See logs for more information:
      C:\dev\3rdparty\vcpkg\buildtrees\boost-fiber\build-x64-windows-v142-rel-out.log

Call Stack (most recent call first):
  installed/x64-windows-v142/share/boost-build/boost-modular-build.cmake:297 (vcpkg_execute_required_process)
  ports/boost-fiber/portfile.cmake:17 (boost_modular_build)
  scripts/ports.cmake:90 (include)

Error: Building package boost-fiber:x64-windows-v142 failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-fiber:x64-windows-v142
  Vcpkg version: 2020.02.04-nohash-external

Additionally, attach any relevant sections from the log files above.
vcpkg install failed

C:\src\slam6d-code-r2343-trunk\windows>Building package boost-fiber:x64-windows-v142 failed with: BUILD_FAILED
[build-x64-windows-v142-rel-out.log](https://github.com/microsoft/vcpkg/files/7068736/build-x64-windows-v142-rel-out.log)

**Comment by PhoebeHui** [comment]
@Tim-Mckinley, could you try the following steps and see if the issue persist?

1. ./vcpkg remove boost-uninstall:x64-windows-v142
2. git pull and execute ./bootstrap-vcpkg.bat
3. ./vcpkg install boost-fiber:x64-windows-v142

**Comment by Tim-Mckinley** [comment]
@PhoebeHui Please see the following results.

**1:** The following packages are not installed, so not removed:
    boost-uninstall:x64-windows-v142
Package boost-uninstall:x64-windows-v142 is not installed

**2:** C:\dev\3rdparty\vcpkg>.\bootstrap-vcpkg.bat

Building vcpkg.exe ...

  pch.cpp
  archives.cpp
  checks.cpp
  chrono.cpp
  cofffilereader.cpp
  downloads.cpp
  enums.cpp
  files.cpp
  hash.cpp
  json.cpp
  machinetype.cpp
  parse.cpp
  strings.cpp
  stringview.cpp
  system.cpp
  system.print.cpp
  system.process.cpp
  unicode.cpp
  binarycaching.cpp
  binaryparagraph.cpp
  build.cpp
  cmakevars.cpp
  commands.autocomplete.cpp
  commands.buildexternal.cpp
  commands.cache.cpp
  commands.ci.cpp
  commands.ciclean.cpp
  commands.contact.cpp
  commands.cpp
  commands.create.cpp
  commands.dependinfo.cpp
  commands.edit.cpp
  commands.env.cpp
  commands.exportifw.cpp
  commands.import.cpp
  commands.integrate.cpp
  commands.list.cpp
  commands.owns.cpp
  commands.porthistory.cpp
  commands.portsdiff.cpp
  commands.search.cpp
  commands.setinstalled.cpp
  commands.upgrade.cpp
  commands.version.cpp
  commands.xvsinstances.cpp
  dependencies.cpp
  export.cpp
  export.chocolatey.cpp
  export.prefab.cpp
  globalstate.cpp
  help.cpp
  input.cpp
  install.cpp
  logicexpression.cpp
  metrics.cpp
  packagespec.cpp
  paragraphparseresult.cpp
  paragraphs.cpp
  portfileprovider.cpp
  postbuildlint.buildtype.cpp
  postbuildlint.cpp
  remove.cpp
  sourceparagraph.cpp
  statusparagraph.cpp
  statusparagraphs.cpp
  tools.cpp
  triplet.cpp
  update.cpp
  userconfig.cpp
  vcpkgcmdarguments.cpp
  vcpkglib.cpp
  vcpkgpaths.cpp
  versiont.cpp
  visualstudio.cpp
  vcpkglib.vcxproj -> C:\dev\3rdparty\vcpkg\toolsrc\msbuild.x86.release\vcpkglib.lib
  vcpkg.cpp
  Generating code
  Previous IPDB not found, fall back to full compilation.
  All 18363 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Finished generating code
  vcpkg.vcxproj -> C:\dev\3rdparty\vcpkg\toolsrc\msbuild.x86.release\vcpkg.exe
  vcpkgmetricsuploader.cpp
  Generating code
  Previous IPDB not found, fall back to full compilation.
  All 7944 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Finished generating code
  vcpkgmetricsuploader.vcxproj -> C:\dev\3rdparty\vcpkg\toolsrc\msbuild.x86.release\vcpkgmetricsuploader.exe

Building vcpkg.exe... done.

Telemetry
---------
vcpkg collects usage data in order to help us improve your experience. The data collected by Microsoft is anonymous. You can opt-out of telemetry by re-running bootstrap-vcpkg.bat with -disableMetrics.
Read more about vcpkg telemetry at docs/about/privacy.md


**3:** C:\dev\3rdparty\vcpkg>.\vcpkg install boost-fiber:x64-windows-v142
Computing installation plan...
The following packages will be built and installed:
    boost-fiber[core]:x64-windows-v142
Starting package 1/1: boost-fiber:x64-windows-v142
Building package boost-fiber[core]:x64-windows-v142...
-- Using cached C:/dev/3rdparty/vcpkg/downloads/boostorg-fiber-boost-1.73.0.tar.gz
-- Using source at C:/dev/3rdparty/vcpkg/buildtrees/boost-fiber/src/ost-1.73.0-19cdf62e42
-- Building x64-windows-v142-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: C:/dev/3rdparty/vcpkg/installed/x64-windows-v142/tools/boost-build/b2.exe --stagedir=C:/dev/3rdparty/vcpkg/buildtrees/boost-fiber/x64-windows-v142-rel/stage --build-dir=C:/dev/3rdparty/vcpkg/buildtrees/boost-fiber/x64-windows-v142-rel --user-config=C:/dev/3rdparty/vcpkg/buildtrees/boost-fiber/x64-windows-v142-rel/user-config.jam -j12 --debug-configuration --debug-building --debug-generators --disable-icu --ignore-site-config --hash -q -sZLIB_INCLUDE=C:/dev/3rdparty/vcpkg/installed/x64-windows-v142/include -sBZIP2_INCLUDE=C:/dev/3rdparty/vcpkg/installed/x64-windows-v142/include -sLZMA_INCLUDE=C:/dev/3rdparty/vcpkg/installed/x64-windows-v142/include -sZSTD_INCLUDE=C:/dev/3rdparty/vcpkg/installed/x64-windows-v142/include threading=multi threadapi=win32 runtime-link=shared link=shared address-model=64 architecture=x86 toolset=msvc -sZLIB_BINARY=zlib -sZLIB_LIBPATH=C:/dev/3rdparty/vcpkg/installed/x64-windows-v142/lib -sBZIP2_BINARY=bz2 -sBZIP2_LIBPATH=C:/dev/3rdparty/vcpkg/installed/x64-windows-v142/lib -sLZMA_BINARY=lzma -sLZMA_LIBPATH=C:/dev/3rdparty/vcpkg/installed/x64-windows-v142/lib -sZSTD_BINARY=zstd -sZSTD_LIBPATH=C:/dev/3rdparty/vcpkg/installed/x64-windows-v142/lib variant=release debug-symbols=on
    Working Directory: C:/dev/3rdparty/vcpkg/buildtrees/boost-fiber/src/ost-1.73.0-19cdf62e42/build
    Error code: 1
    See logs for more information:
      C:\dev\3rdparty\vcpkg\buildtrees\boost-fiber\build-x64-windows-v142-rel-out.log

Call Stack (most recent call first):
  installed/x64-windows-v142/share/boost-build/boost-modular-build.cmake:297 (vcpkg_execute_required_process)
  ports/boost-fiber/portfile.cmake:17 (boost_modular_build)
  scripts/ports.cmake:90 (include)


Error: Building package boost-fiber:x64-windows-v142 failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-fiber:x64-windows-v142
  Vcpkg version: 2020.02.04-nohash

**Comment by PhoebeHui** [comment]
@Tim-Mckinley, do you solve the problem finally? could you please try vcpkg latest source and see if the issue still repro? boost has been upgraded to 1.77.0, I still can't repro this issue locally.

**Comment by LilyWangLL** [comment]
Ping @Tim-Mckinley for response.

**Comment by Tim-Mckinley** [comment]
Yes, the problem has been resolved. Thanks for your assistance.
