### ISSUE TITLE
[abseil] build failed with msvc2015

### ISSUE THREAD

**Issue by sunwangme** [Microsoft/vcpkg#1978]
C:\projects\vcpkg\buildtrees\abseil\src\abseil-cpp-1a9ba5e2e5a14413704f0c913fac53359576d3b6\absl\numeric\int128.cc(58): error C2719: 'n': formal parameter with requested alignment of 16 won't be aligned
C:\projects\vcpkg\buildtrees\abseil\src\abseil-cpp-1a9ba5e2e5a14413704f0c913fac53359576d3b6\absl\numeric\int128.cc(69): error C2719: 'dividend': formal parameter with requested alignment of 16 won't be aligned
C:\projects\vcpkg\buildtrees\abseil\src\abseil-cpp-1a9ba5e2e5a14413704f0c913fac53359576d3b6\absl\numeric\int128.cc(69): error C2719: 'divisor': formal parameter with requested alignment of 16 won't be aligned

**Comment by sunwangme** [comment]
@ras0219-msft

**Comment by ras0219-msft** [comment]
Hi @sunwangme, could you confirm which version of VS2015 you're using?

I got this:
> [20/59] C:\PROGRA\~2\MICROS\~1.0\VC\bin\amd64\cl.exe   /TP -DNOMINMAX -DWIN32_LEAN_AND_MEAN -Dnumeric_EXPORTS -ID:\src\vcpkg\buildtrees\abseil\src\abseil-cpp-1a9ba5e2e5a14413704f0c913fac53359576d3b6 /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP /MD /O2 /Oi /Gy /DNDEBUG /Z7 /showIncludes /FoCMakeFiles\numeric.dir\absl\numeric\int128.cc.obj /FdCMakeFiles\numeric.dir\ /FS -c D:\src\vcpkg\buildtrees\abseil\src\abseil-cpp-1a9ba5e2e5a14413704f0c913fac53359576d3b6\absl\numeric\int128.cc

And in my `config-<triplet>-rel-out.log` I have:
> -- The CXX compiler identification is MSVC 19.0.24225.1
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe

**Comment by sunwangme** [comment]
1. Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24210 for x86
2. x64_windows is ok
3. x86_windows failed
4. maybe: the default alignment of msvc under x86 is 8 bytes, c++11 alignas is invalid for "formal parameter"
5. my patch:

diff --git a/absl/numeric/int128.cc b/absl/numeric/int128.cc
index 7debf56..e59ef85 100644
--- a/absl/numeric/int128.cc
+++ b/absl/numeric/int128.cc
@@ -55,7 +55,7 @@ static inline int Fls64(uint64_t n) {
 
 // Like Fls64() above, but returns the 0-based position of the last set bit
 // (i.e., most significant bit) in the given uint128. The argument may not be 0.
-static inline int Fls128(uint128 n) {
+static inline int Fls128(const uint128& n) {
   if (uint64_t hi = Uint128High64(n)) {
     return Fls64(hi) + 64;
   }
@@ -65,10 +65,13 @@ static inline int Fls128(uint128 n) {
 // Long division/modulo for uint128 implemented using the shift-subtract
 // division algorithm adapted from:
 // http://stackoverflow.com/questions/5386377/division-without-using
-void DivModImpl(uint128 dividend, uint128 divisor, uint128* quotient_ret,
+void DivModImpl(const uint128& const_dividend, const uint128& divisor, uint128* quotient_ret,
                 uint128* remainder_ret) {
   assert(divisor != 0);
 
+  //fixed for msvc-x86! error C2719: 'dividend': formal parameter with requested alignment of 16
+  uint128 dividend = const_dividend;
+  
   if (divisor > dividend) {
     *quotient_ret = 0;
     *remainder_ret = dividend;
diff --git a/absl/time/duration.cc b/absl/time/duration.cc
index f508195..e51d105 100644
--- a/absl/time/duration.cc
+++ b/absl/time/duration.cc
@@ -126,7 +126,7 @@ inline uint128 MakeU128Ticks(Duration d) {
 }
 
 // Breaks a uint128 of ticks into a Duration.
-inline Duration MakeDurationFromU128(uint128 u128, bool is_neg) {
+inline Duration MakeDurationFromU128(const uint128& u128, bool is_neg) {
   int64_t rep_hi;
   uint32_t rep_lo;
   const uint64_t h64 = Uint128High64(u128);
@@ -198,7 +198,7 @@ inline bool SafeAddRepHi(double a_hi, double b_hi, Duration* d) {
 // T value instead of overflowing. This is only defined for uint128.
 template <typename Ignored>
 struct SafeMultiply {
-  uint128 operator()(uint128 a, uint128 b) const {
+  uint128 operator()(const uint128& a, const uint128& b) const {
     // b hi is always zero because it originated as an int64_t.
     assert(Uint128High64(b) == 0);
     // Fastpath to avoid the expensive overflow check with division.

**Comment by sunwangme** [comment]
diff --git a/absl/numeric/int128.cc b/absl/numeric/int128.cc
index 7debf56..e59ef85 100644
--- a/absl/numeric/int128.cc
+++ b/absl/numeric/int128.cc
@@ -55,7 +55,7 @@ static inline int Fls64(uint64_t n) {
 
 // Like Fls64() above, but returns the 0-based position of the last set bit
 // (i.e., most significant bit) in the given uint128. The argument may not be 0.
-static inline int Fls128(uint128 n) {
+static inline int Fls128(const uint128& n) {
   if (uint64_t hi = Uint128High64(n)) {
     return Fls64(hi) + 64;
   }
@@ -65,10 +65,13 @@ static inline int Fls128(uint128 n) {
 // Long division/modulo for uint128 implemented using the shift-subtract
 // division algorithm adapted from:
 // http://stackoverflow.com/questions/5386377/division-without-using
-void DivModImpl(uint128 dividend, uint128 divisor, uint128* quotient_ret,
+void DivModImpl(const uint128& const_dividend, const uint128& divisor, uint128* quotient_ret,
                 uint128* remainder_ret) {
   assert(divisor != 0);
 
+  //fixed for msvc-x86! error C2719: 'dividend': formal parameter with requested alignment of 16
+  uint128 dividend = const_dividend;
+  
   if (divisor > dividend) {
     *quotient_ret = 0;
     *remainder_ret = dividend;
diff --git a/absl/time/duration.cc b/absl/time/duration.cc
index f508195..e51d105 100644
--- a/absl/time/duration.cc
+++ b/absl/time/duration.cc
@@ -126,7 +126,7 @@ inline uint128 MakeU128Ticks(Duration d) {
 }
 
 // Breaks a uint128 of ticks into a Duration.
-inline Duration MakeDurationFromU128(uint128 u128, bool is_neg) {
+inline Duration MakeDurationFromU128(const uint128& u128, bool is_neg) {
   int64_t rep_hi;
   uint32_t rep_lo;
   const uint64_t h64 = Uint128High64(u128);
@@ -198,7 +198,7 @@ inline bool SafeAddRepHi(double a_hi, double b_hi, Duration* d) {
 // T value instead of overflowing. This is only defined for uint128.
 template <typename Ignored>
 struct SafeMultiply {
-  uint128 operator()(uint128 a, uint128 b) const {
+  uint128 operator()(const uint128& a, const uint128& b) const {
     // b hi is always zero because it originated as an int64_t.
     assert(Uint128High64(b) == 0);
     // Fastpath to avoid the expensive overflow check with division.``

**Comment by sunwangme** [comment]
`diff --git a/absl/numeric/int128.cc b/absl/numeric/int128.cc
index 7debf56..e59ef85 100644
--- a/absl/numeric/int128.cc
+++ b/absl/numeric/int128.cc
@@ -55,7 +55,7 @@ static inline int Fls64(uint64_t n) {
 
 // Like Fls64() above, but returns the 0-based position of the last set bit
 // (i.e., most significant bit) in the given uint128. The argument may not be 0.
-static inline int Fls128(uint128 n) {
+static inline int Fls128(const uint128& n) {
   if (uint64_t hi = Uint128High64(n)) {
     return Fls64(hi) + 64;
   }
@@ -65,10 +65,13 @@ static inline int Fls128(uint128 n) {
 // Long division/modulo for uint128 implemented using the shift-subtract
 // division algorithm adapted from:
 // http://stackoverflow.com/questions/5386377/division-without-using
-void DivModImpl(uint128 dividend, uint128 divisor, uint128* quotient_ret,
+void DivModImpl(const uint128& const_dividend, const uint128& divisor, uint128* quotient_ret,
                 uint128* remainder_ret) {
   assert(divisor != 0);
 
+  //fixed for msvc-x86! error C2719: 'dividend': formal parameter with requested alignment of 16
+  uint128 dividend = const_dividend;
+  
   if (divisor > dividend) {
     *quotient_ret = 0;
     *remainder_ret = dividend;
diff --git a/absl/time/duration.cc b/absl/time/duration.cc
index f508195..e51d105 100644
--- a/absl/time/duration.cc
+++ b/absl/time/duration.cc
@@ -126,7 +126,7 @@ inline uint128 MakeU128Ticks(Duration d) {
 }
 
 // Breaks a uint128 of ticks into a Duration.
-inline Duration MakeDurationFromU128(uint128 u128, bool is_neg) {
+inline Duration MakeDurationFromU128(const uint128& u128, bool is_neg) {
   int64_t rep_hi;
   uint32_t rep_lo;
   const uint64_t h64 = Uint128High64(u128);
@@ -198,7 +198,7 @@ inline bool SafeAddRepHi(double a_hi, double b_hi, Duration* d) {
 // T value instead of overflowing. This is only defined for uint128.
 template <typename Ignored>
 struct SafeMultiply {
-  uint128 operator()(uint128 a, uint128 b) const {
+  uint128 operator()(const uint128& a, const uint128& b) const {
     // b hi is always zero because it originated as an int64_t.
     assert(Uint128High64(b) == 0);
     // Fastpath to avoid the expensive overflow check with division.`

**Comment by solvingj** [comment]
So was the fix for this to patch abseil sources? 

Did anyone happen to suggest a patch upstream?
