### ISSUE TITLE
Visual Studio: cannot open source file 'gtkmm.h' (Gtkmm-4.0)

### ISSUE THREAD

**Issue by JamesC01** [microsoft/vcpkg#19786]
**Describe the bug**
I installed Gtkmm with 'vcpkg install gtkmm:x64-windows'. When I try to include it in visual studio, it gives the error "cannot open source file "gtkmm.h". The problem is that gtkmm.h's path is gtkmm-4.0/gtkmm.h. If I include that, I get a ton of errors for the includes inside of gtkmm.h, because it's trying to access the headers without the gtkmm-4.0 folder in the include. I'm sure there's some option I have to set, but still, I thought I wouldn't have to configure anything, it should probably have the correct options by default.

**Environment**
- OS: Windows
- Compiler: VC++

**Expected behavior**
It should work without any configuration.

**Comment by PhoebeHui** [comment]
@JamesC01, the MSBuild integration is broken, could you try the solution provided by https://github.com/microsoft/vcpkg/issues/18328#issuecomment-857183263?

**Comment by Adela0814** [comment]
@JamesC01 Have you tried PR #18328, does it solve your problem?

**Comment by dewcked** [comment]
Whoever facing same problem or having hard time to setting gtkmm-4.0 can try [GTKMM-4.0VcpkgCmakeExample](https://github.com/dewcked/GTKMM-4.0VcpkgCmakeExample). If problem occurs, Try chanching `Toolset` option in **CMakeSettings.json**.

**Comment by jimwang118** [comment]
You can use the following method to find gtkmm-4.0 in the cmakelists.txt file.
```
find_package(PkgConfig REQUIRED)
pkg_check_modules(GTKMM_LIB REQUIRED IMPORTED_TARGET gtkmm-4.0)
target_link_libraries(main PRIVATE PkgConfig::GTKMM_LIB)
```
