### ISSUE TITLE
[vswhere] fail to detect "visual-cpp-build-tools 2015"

### ISSUE THREAD

**Issue by sunwangme** [Microsoft/vcpkg#1979]
0.0.90 is ok
0.0.91 is fail

C:\projects\vcpkg>vcpkg search abseil
Warning: Different source is available for vcpkg (0.0.90 -> 0.0.91). Use .\boots
trap-vcpkg.bat to update.
abseil               2017-10-14       an open-source collection designed to augm
ent the C++ standard library. Abseil...

If your library is not listed, please open an issue at and/or consider making a
pull request:
    https://github.com/Microsoft/vcpkg/issues

C:\projects\vcpkg>bootstrap-vcpkg.bat

Could not find MSBuild version with C++ support. VS2015 or VS2017 (with C++) ne
eds to be installed.
C:\projects\vcpkg\scripts\findAnyMSBuildWithCppPlatformToolset.ps1:54: 6
+ throw <<<<  "Could not find MSBuild version with C++ support. VS2015 or VS201
7 (with C++) needs to be installed."
    + CategoryInfo          : OperationStopped: (Could not find ...o be instal
   led.:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find MSBuild version with C++ support.
    VS2015 or VS2017 (with C++) needs to be installed.

@ras0219-msft

**Comment by alexkaratarakis** [comment]
It appears your Visual Studio installation cannot be detected. Which version of Visual Studio do you have installed and on what version of Windows?

**Comment by sunwangme** [comment]
i just install vc-build-tools 2015.

**Comment by alexkaratarakis** [comment]
@sunwangme 
I fixed this with 0051e7477be15c9746e9fb2babe15aaec47a7eef.
Please to a `git pull` and let me know if it fixes your issue : ).

**Comment by sunwangme** [comment]
@alexkaratarakis 
thanks, ok now, but i move the patch to findAnyMSBuildWithCppPlatformToolset.ps1

1. suggest: move the patch to the end of "findAnyMSBuildWithCppPlatformToolset.ps1", ie:

# If nothing is found, attempt to find VS2015 Build Tools (not detected by vswhere.exe)
if(1)
{
    $programFilesPath = & $scriptsDir\getProgramFiles32bit.ps1
    $installationPath = "$programFilesPath\Microsoft Visual Studio 14.0"
    $clExe = "$installationPath\VC\bin\cl.exe"
    $vcvarsallbat = "$installationPath\VC\vcvarsall.bat"

    if ((Test-Path $clExe) -And (Test-Path $vcvarsallbat))
    {
       return "$programFilesPath\MSBuild\14.0\Bin\MSBuild.exe", "v140"
    }
}

throw "Could not find MSBuild version with C++ support. VS2015 or VS2017 (with C++) needs to be installed."

2. reason: vs2013/2012 can be detected by vswhere.  my computer: vs2013 + buildtools 2015
C:\projects\vcpkg\downloads\vswhere-2.2.3>vswhere.exe -prerelease -legacy -products * -format xml
<?xml version="1.0"?>
<instances>
  <instance>
    <instanceId>VisualStudio.12.0</instanceId>
    <installationPath>C:\Program Files (x86)\Microsoft Visual Studio 12.0\</installationPath>
    <installationVersion>12.0</installationVersion>
  </instance>
</instances>
