### ISSUE TITLE
[libjpeg-turbo] build failure (failed finding 32-bit nasm)

### ISSUE THREAD

**Issue by trebla64** [microsoft/vcpkg#19800]
**Host Environment**
- OS: Windows 10 x64
- Compiler: revision

**To Reproduce**
`./vcpkg install libjpeg-turbo:x64-windows`

**Failure logs** 
$ .\vcpkg.exe install libjpeg-turbo:x64-windows
Computing installation plan...
The following packages will be built and installed:
    libjpeg-turbo[core]:x64-windows -> 2.0.6
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\Albert\AppData\Local\vcpkg\archives\66\66907990a2242f6b03dd0a5152bd078368927ad06cc9c00d0b857804d3362c20.zip
Starting package 1/1: libjpeg-turbo:x64-windows
Building package libjpeg-turbo[core]:x64-windows...
-- Downloading https://github.com/libjpeg-turbo/libjpeg-turbo/archive/10ba6ed3365615ed5c2995fe2d240cb2d5000173.tar.gz -> libjpeg-turbo-libjpeg-turbo-10ba6ed3365615ed5c2995fe2d240cb2d5000173.tar.gz...
-- Cleaning sources at C:/dev/vcpkg/buildtrees/libjpeg-turbo/src/b2d5000173-96baffe5bc.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/dev/vcpkg/downloads/libjpeg-turbo-libjpeg-turbo-10ba6ed3365615ed5c2995fe2d240cb2d5000173.tar.gz
-- Applying patch add-options-for-exes-docs-headers.patch
-- Applying patch workaround_cmake_system_processor.patch
-- Applying patch fix-incompatibility-for-c11-c17.patch
-- Using source at C:/dev/vcpkg/buildtrees/libjpeg-turbo/src/b2d5000173-96baffe5bc.clean
-- Downloading https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win32/nasm-2.15.05-win32.zip;https://fossies.org/windows/misc/nasm-2.15.05-win32.zip -> nasm-2.15.05-win32.zip...
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' = off
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Downloading https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win32/nasm-2.15.05-win32.zip
[DEBUG] Downloading https://fossies.org/windows/misc/nasm-2.15.05-win32.zip
Error: Failed to download from mirror set:
https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win32/nasm-2.15.05-win32.zip: WinHttpSendRequest() failed: 12030
https://fossies.org/windows/misc/nasm-2.15.05-win32.zip: failed: status code 410

[DEBUG] C:\a\1\s\src\vcpkg\base\downloads.cpp(626)
[DEBUG] Exiting after 35474822 us (35457456 us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:83 (message):

      Failed to download file with error: 1
      If you use a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.

      3. You proxy's remote server is out of service.

      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)

      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:274 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_find_acquire_program.cmake:552 (vcpkg_download_distfile)
  ports/libjpeg-turbo/portfile.cmake:22 (vcpkg_find_acquire_program)
  scripts/ports.cmake:140 (include)

Error: Building package libjpeg-turbo:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libjpeg-turbo:x64-windows
  Vcpkg version: 2021-08-12-85ab112d5ee102bc6eac8cdbbfdd173a71374e04

Additionally, attach any relevant sections from the log files above.

**Additional context**
It looks like the 32-bit build of nasm it is pointing to doesn't exist anymore

**Comment by NancyLi1013** [comment]
Hi @trebla64 

Thanks for posting this issue.
Could you please try to redownload https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win32/nasm-2.15.05-win32.zip?

I have checked that this archive can be accessed now. 

For https://fossies.org/windows/misc/nasm-2.15.05-win32.zip, nasm-2.15.05-win32.zip seems not exist now. there is only nasm-2.15.05-win64.zip.

**Comment by trebla64** [comment]
@NancyLi1013 Yes, it works now. Was able to get past this point. Thanks a lot

**Comment by NancyLi1013** [comment]
Closing this issue since it has been solved.
