### ISSUE TITLE
issues with installing crashrpt

### ISSUE THREAD

**Issue by tester0077** [microsoft/vcpkg#19804]
Building package dbghelp[core]:x86-windows...
LIBFILEPATH: C:\Program Files (x86)\Windows Kits\10\Debuggers\lib\x86\dbghelp.lib
DLLFILEPATH: C:\Program Files (x86)\Windows Kits\10\Debuggers\x86\dbghelp.dll
HEADERPATH: C:\Program Files (x86)\Windows Kits\10\Debuggers\inc\dbghelp.h
CMake Error at ports/dbghelp/portfile.cmake:18 (message):
  Cannot find debugging tools in Windows SDK 10.0.19041.0.  Please reinstall
  the Windows SDK and select "Debugging Tools".
Call Stack (most recent call first):
  scripts/ports.cmake:140 (include)

Error: Building package dbghelp:x86-windows failed with: BUILD_FAILED

**Comment by JonLiu1993** [comment]
@tester0077,Thanks for posting this issue,
```
Cannot find debugging tools in Windows SDK 10.0.19041.0. Please reinstall
the Windows SDK and select "Debugging Tools"
```

**Comment by JonLiu1993** [comment]
Closing this issue for no active thread for a long time. Please feel free to reopen this issue if it is still a problem for you.

**Comment by tester0077** [comment]
Sorry for my slow response.
It had been hoped to use crashrpt to find the issue, but when the project failed to build, its priority drop to the bottom and I have not had a chance to follow up.
