### ISSUE TITLE
[angle] Add CMake package with modules.

### ISSUE THREAD

**Issue by qis** [Microsoft/vcpkg#1981]
Please add an automatically generated CMake package with modules support to the ANGLE port.
Here is a fully functional example:

https://github.com/qis/angle-package/commit/d38c077495dd53b564d9fa94b5e67a127f3a0249

This allows users to include angle and link to it with only a few lines of code:

```cmake
find_package(ANGLE REQUIRED)
target_link_libraries(${PROJECT_NAME} PRIVATE ANGLE::EGL ANGLE::GLESv2)
target_compile_definitions(${PROJECT_NAME} PRIVATE EGL_EGLEXT_PROTOTYPES=1 GL_GLEXT_PROTOTYPES=1)
```

It might be a good idea to add `EGL_EGLEXT_PROTOTYPES` and `GL_GLEXT_PROTOTYPES` to the `ANGLE::EGL` and `ANGLE::GLESv2` targets as `INTERFACE_COMPILE_DEFINITIONS` entries.

Here is a repo I used to test it on `x64-windows`:

https://github.com/qis/angle-package-test

**Comment by qis** [comment]
I've made a pull request for this issue. If anybody wishes me to change something, please comment either there, or here.

https://github.com/Microsoft/vcpkg/pull/2223

**Comment by ras0219-msft** [comment]
Thanks again!
