### ISSUE TITLE
[asio] update to 1.19.2

### ISSUE THREAD

**Issue by xavier2k6** [microsoft/vcpkg#19835]
Library name: **asio**

New version number: **1.19.2**

Other information that may be useful (release notes, etc...)

FYI:
https://github.com/chriskohlhoff/asio/issues/873
https://github.com/chriskohlhoff/asio/commit/2d3a4c9fcdeeea48dc6974389b4c5167da9e34f7 (included in 1.19.2)

See also PR https://github.com/chriskohlhoff/asio/pull/892 (Open)

**Comment by mathisloge** [comment]
Thats not the latest stable release. I would prefer to not use the latest development version
