### ISSUE TITLE
[Thalhammer-jwt-cpp] checksum failure

### ISSUE THREAD

**Issue by pyrotechnics-io** [microsoft/vcpkg#19837]
**Host Environment**
- OS: Linux (all). probably Windows too. 
- Compiler: gcc

**To Reproduce**
`./vcpkg install jwt-cpp`

**Failure logs** 
`
[DEBUG] popen(curl --fail -L https://github.com/Thalhammer/jwt-cpp/archive/60122bbd8e6b9009c4633c1a33ea94c5b682034a.tar.gz --create-dirs --output /tmp/codon/tmp/cache/vcpkg/downloads/Thalhammer-jwt-cpp-60122bbd8e6b9009c4633c1a33ea94c5b682034a.tar.gz.3615.part 2>&1)
[DEBUG] cmd_execute_and_stream_data() returned 0 after   273358 us
Error: Failed to download from mirror set:
File does not have the expected hash:
             url : [ https://github.com/Thalhammer/jwt-cpp/archive/60122bbd8e6b9009c4633c1a33ea94c5b682034a.tar.gz ]
       File path : [ /tmp/codon/tmp/cache/vcpkg/downloads/Thalhammer-jwt-cpp-60122bbd8e6b9009c4633c1a33ea94c5b682034a.tar.gz.3615.part ]
   Expected hash : [ d2c6e2174cd86c27b8866f6ea50a379a321788e91f97a0548e694d11469c05d93b0713e0c38b37a8f14a0aded4fc4635599dcfb50142e4496fb3c8b9f7e5f8cd ]
     Actual hash : [ ae905e217824d21ec9f098f562d993fbae71b2223e65f3bbcc29d352af61f2aa09b5c6b12c7d94742901a1374f9683335d3b4934c25b11500b710398331f6cb4 ]`

**Additional context**
Changing the hash on the portfile fixes the issue, but I'm not sure if the problem is with vcpkg's hash, or the upstream repo.

**Comment by JackBoosY** [comment]
I checked the hash on Windows and Linux, they are all passed. Maybe your network caused this.

**Comment by pyrotechnics-io** [comment]
Could it be your vcpkg cache that has a stored tarball ? Because mine failed on 2 different linux boxes as well as on a clean heroku application build (thats where the screenshot above is from)

**Comment by pyrotechnics-io** [comment]
Just tried again right now. Different machine, different network (office), same result : 

```
Elapsed time for package picojson:x64-linux: 1.946 s
Starting package 2/2: jwt-cpp:x64-linux
Building package jwt-cpp[core]:x64-linux...
-- Downloading https://github.com/Thalhammer/jwt-cpp/archive/60122bbd8e6b9009c4633c1a33ea94c5b682034a.tar.gz -> Thalhammer-jwt-cpp-60122bbd8e6b9009c4633c1a33ea94c5b682034a.tar.gz...
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' = off
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] popen(curl --fail -L https://github.com/Thalhammer/jwt-cpp/archive/60122bbd8e6b9009c4633c1a33ea94c5b682034a.tar.gz --create-dirs --output /home/harsh/pyrotechnics/trickle/cache/vcpkg/downloads/Thalhammer-jwt-cpp-60122bbd8e6b9009c4633c1a33ea94c5b682034a.tar.gz.6019.part 2>&1)
[DEBUG] cmd_execute_and_stream_data() returned 0 after  2033171 us
Error: Failed to download from mirror set:
File does not have the expected hash:
             url : [ https://github.com/Thalhammer/jwt-cpp/archive/60122bbd8e6b9009c4633c1a33ea94c5b682034a.tar.gz ]
       File path : [ /home/harsh/pyrotechnics/trickle/cache/vcpkg/downloads/Thalhammer-jwt-cpp-60122bbd8e6b9009c4633c1a33ea94c5b682034a.tar.gz.6019.part ]
   Expected hash : [ d2c6e2174cd86c27b8866f6ea50a379a321788e91f97a0548e694d11469c05d93b0713e0c38b37a8f14a0aded4fc4635599dcfb50142e4496fb3c8b9f7e5f8cd ]
     Actual hash : [ ae905e217824d21ec9f098f562d993fbae71b2223e65f3bbcc29d352af61f2aa09b5c6b12c7d94742901a1374f9683335d3b4934c25b11500b710398331f6cb4 ]


[DEBUG] /home/harsh/pyrotechnics/trickle/cache/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-08-12/src/vcpkg/base/downloads.cpp(626)
[DEBUG] Exiting after 2035140 us (2034345 us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:83 (message):
      
      Failed to download file with error: 1
      If you use a proxy, please check your proxy setting. Possible causes are:
      
      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
      
      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.
      
      3. You proxy's remote server is out of service.
      
      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)
      
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:274 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_github.cmake:173 (vcpkg_download_distfile)
  ports/jwt-cpp/portfile.cmake:1 (vcpkg_from_github)
  scripts/ports.cmake:140 (include)

```

**Comment by pyrotechnics-io** [comment]
Ok so this is definitely a wrong hash value in vcpkg portfile. If you just take the file from the "url" in the error message above, download it normally, and take its sha512sum, you see the issue : 

burt@strava:~/$ wget https://github.com/Thalhammer/jwt-cpp/archive/60122bbd8e6b9009c4633c1a33ea94c5b682034a.tar.gz
--2021-09-01 14:27:21--  https://github.com/Thalhammer/jwt-cpp/archive/60122bbd8e6b9009c4633c1a33ea94c5b682034a.tar.gz
Resolving github.com (github.com)... 52.74.223.119
Connecting to github.com (github.com)|52.74.223.119|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/Thalhammer/jwt-cpp/tar.gz/60122bbd8e6b9009c4633c1a33ea94c5b682034a [following]
--2021-09-01 14:27:22--  https://codeload.github.com/Thalhammer/jwt-cpp/tar.gz/60122bbd8e6b9009c4633c1a33ea94c5b682034a
Resolving codeload.github.com (codeload.github.com)... 13.250.162.133
Connecting to codeload.github.com (codeload.github.com)|13.250.162.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘60122bbd8e6b9009c4633c1a33ea94c5b682034a.tar.gz’

60122bbd8e6b9009c4633c1a33ea94c5b     [ <=>                                                         ] 242.92K  1.46MB/s    in 0.2s    

2021-09-01 14:27:22 (1.46 MB/s) - ‘60122bbd8e6b9009c4633c1a33ea94c5b682034a.tar.gz’ saved [248745]

burt@strava:~/$ sha512sum 60122bbd8e6b9009c4633c1a33ea94c5b682034a.tar.gz 
**ae905e217824d21ec9f098f562d993fbae71b2223e65f3bbcc29d352af61f2aa09b5c6b12c7d94742901a1374f9683335d3b4934c25b11500b710398331f6cb4**  60122bbd8e6b9009c4633c1a33ea94c5b682034a.tar.gz

**Comment by pyrotechnics-io** [comment]
Ok so I know what checkin broke it too (#19618) : 
https://github.com/microsoft/vcpkg/pull/19618

**Comment by JackBoosY** [comment]
Oh god, I didn't pull the latest code. Sorry.

**Comment by prince-chrismc** [comment]
RIP! Can we open a PR to fix the issue?
