### ISSUE TITLE
Error: Building package cpprestsdk:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by LeCrucien** [Microsoft/vcpkg#1984]
cpprestsdk:x86-windows
Building package cpprestsdk:x86-windows...
-- CURRENT_INSTALLED_DIR=C:/D/local/vcpkg/installed/x86-windows
-- DOWNLOADS=C:/D/local/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/D/local/vcpkg/packages/cpprestsdk_x86-windows
-- CURRENT_BUILDTREES_DIR=C:/D/local/vcpkg/buildtrees/cpprestsdk
-- CURRENT_PORT_DIR=C:/D/local/vcpkg/ports/cpprestsdk/.
-- Using cached C:/D/local/vcpkg/downloads/Microsoft-cpprestsdk-v2.9.0.tar.gz
-- Testing integrity of cached file...
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:47 (message):

  File does not have expected hash:

          File path: [ C:/D/local/vcpkg/downloads/Microsoft-cpprestsdk-v2.9.0.tar.gz ]
      Expected hash: [ c75de6ad33b3e8d2c6ba7c0955ed851d557f78652fb38a565de0cfbc99e7db89cb6fa405857512e5149df80356c51ae9335abd914c3c593fa6658ac50adf4e29 ]
        Actual hash: [ 7f6af05e2aaf49fb5ba24f4fac43b7787345d46913831504925cefc60d1b62e38457e1d628d5de8b0db891b59716d2bfe63a494ca0b337d67fc9ca5447a5ba9b ]

  Please delete the file and retry if this file should be downloaded again.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:59 (test_hash)
  scripts/cmake/vcpkg_from_github.cmake:103 (vcpkg_download_distfile)
  ports/cpprestsdk/portfile.cmake:3 (vcpkg_from_github)
  scripts/ports.cmake:72 (include)

Error: Building package cpprestsdk:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: cpprestsdk:x86-windows
  Vcpkg version: 0.0.85-2017-09-01-35a9d223bc14fb4b35d6ad876d208897c8ce590a

Additionally, attach any relevant sections from the log files above.

**Comment by alexkaratarakis** [comment]
The latest version of `vcpkg` has this fixed; please do a `git pull`.

**Comment by JackBoosY** [comment]
Hi @LeCrucien , thanks for reporting this issue!
Please open a new issue if this is still a problem for you.
Thx.
