### ISSUE TITLE
openimageio cmake errors 

### ISSUE THREAD

**Issue by jmacey** [microsoft/vcpkg#19878]
When building against the latest version of openimageio in vcpkg there is an error 
```
CMake Error at /Users/jmacey/vcpkg/installed/x64-osx/share/OpenImageIO/OpenImageIOConfig.cmake:33 (elseif):
  given arguments:

    "2.5.0" "VERSION_GREATER_EQUAL" "2.4" "AND"
```
It seems the line

```elseif (2.5.0 VERSION_GREATER_EQUAL 2.4 AND )```

is the issue (I presume the dangling AND) this is an autocreated file so not sure where the error stems from.

**Environment**

Mac, Windows and Linux (RHEL 7.7 tested)

**To Reproduce**

Create a dummy project and add the following to CMakeLists.txt
```cmake
find_package(OpenImageIO CONFIG REQUIRED)
target_link_libraries(test PRIVATE OpenImageIO::OpenImageIO )
```
run cmake

**Expected behavior**
It shoudl build

**Comment by JackBoosY** [comment]
That because `FOUND_OPENEXR_WITH_CONFIG` is empty. It should always have a value, ON or OFF.
