### ISSUE TITLE
[cppwinrt] update to 2.0.210825.3

### ISSUE THREAD

**Issue by xavier2k6** [microsoft/vcpkg#19874]
Library name: cppwinrt

New version number: 2.0.210825.3

Other information that may be useful (release notes, etc...)
https://github.com/microsoft/cppwinrt/releases/latest

**Comment by Cheney-W** [comment]
Since the PR https://github.com/microsoft/vcpkg/pull/14092, this port has been changed to be empty. I'm closing this issue, as it doesn't need updating.
