### ISSUE TITLE
[nmap] update to 7.95

### ISSUE THREAD

**Issue by xavier2k6** [microsoft/vcpkg#19888]
Library name: nmap

New version number: 7.95

Other information that may be useful (release notes, etc...)
https://nmap.org/dist/
https://nmap.org/dist/nmap-7.95.tar.bz2
https://nmap.org/changelog.html

**Comment by voltagex** [comment]
The patches that are currently used for this port won't apply cleanly to 7.92 but some fixes to the vcxproj files are still needed.

**Comment by JonLiu1993** [comment]
The nmap port has been deleted by PR https://github.com/microsoft/vcpkg/pull/41458, so this PR is no longer valid and I will close this issue.
