### ISSUE TITLE
[libhsplasma] update to 2021.06.08

### ISSUE THREAD

**Issue by xavier2k6** [microsoft/vcpkg#19880]
Library name: libhsplasma

New version number: 2021.06.08

Other information that may be useful (release notes, etc...)
https://github.com/H-uru/libhsplasma/releases/latest

Edit: Fix typo in Library name.

**Comment by NancyLi1013** [comment]
Hi @xavier2k6 

Thanks for posting this issue. 

Since `libhplasma` doesn't exist in vcpkg now. Could you please submit a pull request to add this port if you are interested in this?

**Comment by NancyLi1013** [comment]
Thanks for your information. 

I will update the title and label.
