### ISSUE TITLE
[tesseract] build failure of training module

### ISSUE THREAD

**Issue by yangtx2009** [microsoft/vcpkg#19893]
**Host Environment**
- OS: Windows 10 Pro 21H1
- Compiler: VS 2019

**To Reproduce**
`./vcpkg install tesseract[core,training-tools]:x64-windows`

**Failure logs** 
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:155 (message):
    Command failed: D:/vcpkg/downloads/tools/cmake-3.21.1-windows/cmake-3.21.1-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j9
    Working Directory: D:/vcpkg/buildtrees/tesseract/x64-windows-dbg
    See logs for more information:
      D:\vcpkg\buildtrees\tesseract\install-x64-windows-dbg-out.log
      D:\vcpkg\buildtrees\tesseract\install-x64-windows-dbg-out-1.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:104 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:44 (vcpkg_build_cmake)
  ports/tesseract/portfile.cmake:37 (vcpkg_install_cmake)
  scripts/ports.cmake:140 (include)

Error: Building package tesseract:x64-windows failed with: BUILD_FAILED

Package: tesseract:x64-windows
Vcpkg version: 2021-08-12-85ab112d5ee102bc6eac8cdbbfdd173a71374e04

**Log reports:** 
FAILED: bin/common_training.dll src/training/common_training.lib 
...\training\CMakeFiles\common_training.dir/manifest.res" failed (exit code 1104) with the following output:
LINK : fatal error LNK1104: cannot open file 'src\training\tessopt.lib'

**Additional context**
The core module is compiled successfully. However, the compilation of the training module fails.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. This issue has been fixed in latest vcpkg, `tesseract[core,training-tools]:x64-windows` can install succeed in latest vcpkg.
```
Installing 3/3 tesseract:x64-windows...
Building tesseract[core,training-tools]:x64-windows...
......
Stored binaries in 1 destinations.
Elapsed time to handle tesseract:x64-windows: 4.5 min
Total install time: 8.3 min
tesseract provides CMake targets:

    # this is heuristically generated, and may not be correct
    find_package(Tesseract CONFIG REQUIRED)
    target_link_libraries(main PRIVATE Tesseract::libtesseract)
```
