### ISSUE TITLE
How can I update vcpkg from a previous version?

### ISSUE THREAD

**Issue by juandent** [Microsoft/vcpkg#1989]
Hi,
I downloaded vcpkg some time ago (version: Vcpkg package management program version 0.0.81-144d3718c4197b101c7d61ee6a258200371fb1ab) and now realize there is a newer version available (Vcpkg package management program version 0.0.91). 

What is the correct way to start using the new version? Just download the latest vcpkg and build it with vcpkg.sln and then copy the exe to the root directory of my previous vcpkg tree?

Seems reasonable but just wanted to make sure.

Regards,
Juan Dent

**Comment by ras0219-msft** [comment]
Even simpler: just run `.\bootstrap-vcpkg.bat` :) Ideally, `vcpkg update` should mention this as well.

**Comment by juandent** [comment]
I ran .\bootstrap-vcpkg.bat but it does not change the version of vcpkg!

**Comment by ras0219-msft** [comment]
Sorry for not mentioning: you do need to run `git pull` first!

**Comment by juandent** [comment]
sorry for my ignorance -- where am I to run 

> git pull
?
If I run it on the command prompt I get:

> C:\Users\Juan Dent\C++ Development\Source Components\vcpkg-master>git pull
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> master

Regards,
Juan

**Comment by juandent** [comment]
Seeing that I had no tracking information for this branch I ran this:

>git branch --set-upstream-to=origin/master

Then 
>git pull

Which got me the following:

>error: Your local changes to the following files would be overwritten by merge:
        ports/cppwinrt/CONTROL
        ports/cppwinrt/portfile.cmake
Please commit your changes or stash them before you merge.
error: The following untracked working tree files would be overwritten by merge:
        ports/date/CONTROL
        ports/date/portfile.cmake
Please move or remove them before you merge.
Aborting
Updating 144d3718..374253cb

Should I commit the changes to ports/cppwinrt/*? Should I delete ports/date/*?

Regards,
Juan

**Comment by ras0219-msft** [comment]
If you don't have any changes you'd like to keep, you can simply `git reset --hard origin/master` to reset your current branch to match the current upstream master.

Otherwise, I'd:
```
git add ports/cppwinrt
git add ports/date
git commit -m "wip"
git pull
```

Then, git will indicate what (if any) it was unable to merge on its own and you can decide what changes to keep or discard.

**Comment by juandent** [comment]
got it thanks!!
Juan
