### ISSUE TITLE
[npcap] update to 1.50

### ISSUE THREAD

**Issue by xavier2k6** [microsoft/vcpkg#19890]
Library name: npcap

New version number: 1.50

Other information that may be useful (release notes, etc...)
https://github.com/nmap/npcap/releases
https://github.com/nmap/npcap/blob/master/CHANGELOG.md
https://nmap.org/npcap/

**Comment by PhoebeHui** [comment]
@xavier2k6, we don't have this port in vcpkg, it may be your custom port, could you submit a PR for it firstly?

**Comment by xavier2k6** [comment]
It was requested previously - I misread/thought it had been implemented. (my mistake)

https://github.com/microsoft/vcpkg/issues/10873

**Comment by xavier2k6** [comment]
Closing this as it is integrated in to the "nmap" 7.92 port update!

Nmap 7.92 [2021-08-07] §
[Windows] Upgraded Npcap (our Windows raw packet capturing and transmission driver) from version 1.00 to the latest version 1.50.
