### ISSUE TITLE
[bullet3] change order of target_link_libraries printed.

### ISSUE THREAD

**Issue by jmacey** [microsoft/vcpkg#19919]
****
When bullet is installed it prints the following

```
The package bullet3:x64-linux provides CMake targets:

    find_package(Bullet CONFIG REQUIRED)
    # Note: 2 target(s) were omitted.
    target_link_libraries(main PRIVATE LinearMath Bullet3Common BulletDynamics BulletSoftBody)

```

This ordering can cause linker errors as bullet needs a specific order of library includes [see here](https://pybullet.org/Bullet/phpBB3/viewtopic.php?t=9554)

**Proposed solution**

I suggest the printed text is changed to the following order

```
target_link_libraries(main  Bullet3Common   BulletDynamics BulletCollision BulletSoftBody   LinearMath)

```

**Comment by Neumann-A** [comment]
> This ordering can cause linker errors as bullet needs a specific order of library includes see here

That is an upstream issues. Targets should be defined in a way that link order doesn't matter. If it does cause link issues the targets are not defining their `INTERFACE_LINK_LIBRARIES` correctly!

**Comment by jmacey** [comment]
> > This ordering can cause linker errors as bullet needs a specific order of library includes see here
> 
> That is an upstream issues. Targets should be defined in a way that link order doesn't matter. If it does cause link issues the targets are not defining their `INTERFACE_LINK_LIBRARIES` correctly!

It's a known issue with Bullet, my suggestion is that the order that things are printed out is usually cut and paste by my students and then things break. Hence requesting for a change to ensure the order is correct. I've already got it in my notes but most students don't read :-)

**Comment by LilyWangLL** [comment]
I submit an issue on upstream: https://github.com/bulletphysics/bullet3/issues/4380.

**Comment by dg0yt** [comment]
@LilyWangLL I don't know if the upstream issue is useful.
- vcpkg has a usage file for bullet3 since 2020. So the *displayed usage* is from vcpkg and can be recitfied here.
- upstream doesn't export targets but `${BULLET_LIBRARIES}`. Targets are from a vcpkg patch, i.e. unofficial vcpkg stuff. And the patch even deals with link libraries. If it isn't enough information to resolve transitive usage requirements, it needs more work.
- Upstream does provide a pkgconfig file. And of course it does use a different order. So either use that order for `usage`, or entirely switch usage to pkgconfig.

**Comment by LilyWangLL** [comment]
> @LilyWangLL I don't know if the upstream issue is useful.
> 
> * vcpkg has a usage file for bullet3 since 2020. So the _displayed usage_ is from vcpkg and can be recitfied here.
> * upstream doesn't export targets but `${BULLET_LIBRARIES}`. Targets are from a vcpkg patch, i.e. unofficial vcpkg stuff. And the patch even deals with link libraries. If it isn't enough information to resolve transitive usage requirements, it needs more work.
> * Upstream does provide a pkgconfig file. And of course it does use a different order. So either use that order for `usage`, or entirely switch usage to pkgconfig.

The usage of `bullet3` is not installed and used, I don't know why it not be removed, the targets are from `cmake-fix.patch`. I modify the description of my upstream issue, It should as jmacey says is a reminder. 
I will use a new usage for this port, and use the same link libraries order with pkgconfig from upstream.
```
Libs: -L${libdir} -lBulletSoftBody -lBulletDynamics -lBulletCollision -lLinearMath
```

**Comment by dg0yt** [comment]
> The usage of `bullet3` is not installed and used, 

Indeed. :disappointed: 

> I don't know why it not be removed, the targets are from `cmake-fix.patch`.

TBH I would recommend to leave the *official* cmake config unchanged, and provide the target-based cmake config in the proper *unofficial* namespace.

A usage file should still be installed because the vcpkg tool heuristics cannot tell which target out of 25 is the primary (single) one which a user should link to.

**Comment by JackBoosY** [comment]
My opinion is: if link order is required, the libraries being linked should establish explicit dependencies.

**Comment by LilyWangLL** [comment]
> My opinion is: if link order is required, the libraries being linked should establish explicit dependencies.

Building explicit dependencies should be done upstream.

**Comment by dg0yt** [comment]
> My opinion is: if link order is required, the libraries being linked should establish explicit dependencies.

I agree:
"the patch even deals with link libraries. If it isn't enough information to resolve transitive usage requirements, it needs more work."

**Comment by dg0yt** [comment]
Remember that link order matters mostly for *static libraries on non-windows targets*.
vcpkg has a MSVC bias and sometimes fails to see that what works for windows isn't good enough for non-windows.

And remember that  upstreams with a non-MSVC bias tend *to assume dynamic linkage*, i.e. simply consider static linkage unsupported.
