### ISSUE TITLE
scripts/bootstrap.sh: [[: not found

### ISSUE THREAD

**Issue by mikeharder** [microsoft/vcpkg#19915]
**Describe the bug**
Running `./vcpkg/bootstrap-vcpkg.sh` prints the following message:

```
./vcpkg/bootstrap-vcpkg.sh: 168: /vcpkg/scripts/bootstrap.sh: [[: not found
```

I believe the issue is #19640 added bash-only syntax (`[[`) but the script uses the `#!/bin/sh` shebang.

**Environment**
- OS: Linux
- Compiler: N/A

**To Reproduce**
1. `git clone https://github.com/microsoft/vcpkg`
2. `./vcpkg/bootstrap-vcpkg.sh`

**Expected behavior**
No errors or warnings

**Failure logs** 
```
./vcpkg/bootstrap-vcpkg.sh: 168: /vcpkg/scripts/bootstrap.sh: [[: not found
```

**Comment by c72578** [comment]
A solution is on the way, see #19822 and #19911

**Comment by PhoebeHui** [comment]
@mikeharder, the fix https://github.com/microsoft/vcpkg/pull/19911 has been merged to master, please get latest source and try again.
