### ISSUE TITLE
New package request- libsodium

### ISSUE THREAD

**Issue by leecbaker** [Microsoft/vcpkg#1992]
Would love to see a port of libsodium.

> Sodium is a modern, easy-to-use software library for encryption, decryption, signatures, password hashing and more.

> It is a portable, cross-compilable, installable, packageable fork of NaCl, with a compatible API, and an extended API to improve usability even further.

> Its goal is to provide all of the core operations needed to build higher-level cryptographic tools.

https://github.com/jedisct1/libsodium
https://libsodium.org

**Comment by xoviat** [comment]
Doesn't look too difficult to port.
