### ISSUE TITLE
[mDNSResponder] update to 878.270.2

### ISSUE THREAD

**Issue by xavier2k6** [microsoft/vcpkg#19966]
Library name: mDNSResponder

New version number: 1310.140.1

Other information that may be useful (release notes, etc...)
https://opensource.apple.com/tarballs/mDNSResponder/

**Comment by Cheney-W** [comment]
After checked the source of mDNSResponder, I found that from version mDNSResponder-1096.0.2 onwards, the mDNSWindows folder and the projects under it have disappeared and cannot be found from source. But checked the sln file of this port, I could see that the projects under mDNSWindows are still built.

I think these files should have been missed. Until these files have been added to source, we cannot go and update the port.

**Comment by xavier2k6** [comment]
> After checked the source of mDNSResponder, I found that from version mDNSResponder-1096.0.2 onwards, the mDNSWindows folder and the projects under it have disappeared and cannot be found from source. But checked the sln file of this port, I could see that the projects under mDNSWindows are still built.
> 
> I think these files should have been missed. Until these files have been added to source, we cannot go and update the port.

Current is `mDNSResponder-765.30.11` so could the port be updated to a newer version that does contain the mDNSWindows folder?
