### ISSUE TITLE
[leptonica:arm64-uwp] build failure

### ISSUE THREAD

**Issue by ignacio-alorre** [microsoft/vcpkg#19974]
**Host Environment**
- OS: Windows 10
- Compiler: Vcpkg version: 2021-08-12-85ab112d5ee102bc6eac8cdbbfdd173a71374e04

**To Reproduce**
`vcpkg install tesseract:arm64-uwp`

**Failure logs** 
-Error: Building package leptonica:arm64-uwp failed with: BUILD_FAILED
-Package: leptonica:arm64-uwp

-- Building arm64-uwp-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:155 (message):
    Command failed: C:/Users/xxxx/Documents/GitHub/vcpkg/downloads/tools/cmake-3.21.1-windows/cmake-3.21.1-windows-i386/bin/cmake.exe --build . --config Debug --target install -- /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /m
    Working Directory: C:/Users/xxxx/Documents/GitHub/vcpkg/buildtrees/leptonica/arm64-uwp-dbg
    See logs for more information:
      C:\Users\xxx\Documents\GitHub\vcpkg\buildtrees\leptonica\install-arm64-uwp-dbg-out.log

**Comment by PhoebeHui** [comment]
@ignacio-alorre, could you attach failure log C:\Users\xxx\Documents\GitHub\vcpkg\buildtrees\leptonica\install-arm64-uwp-dbg-out.log?

**Comment by JonLiu1993** [comment]
@ignacio-alorre ,Thanks for posting this issue. Please reopen this issue if it still be a problem for you.
