### ISSUE TITLE
[catch2] build failure with VCPKG_BUILD_TYPE set to release

### ISSUE THREAD

**Issue by dimiboi** [microsoft/vcpkg#19989]
**Host Environment**
- OS: Windows Server 2019 Datacenter ([Azure DevOps Microsoft-hosted build agent](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md))
- Package: catch2:x86-windows-static-md
- Vcpkg version: 2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9

**To Reproduce**
```
git clone https://github.com/microsoft/vcpkg.git
cd vcpkg
git checkout 2021.05.12
.\bootstrap-vcpkg.bat
Add-Content -Path .\triplets\community\x86-windows-static-md.cmake -Value "set(VCPKG_BUILD_TYPE release)"
.\vcpkg.exe install catch2 --triplet x86-windows-static-md
```

**Failure logs** 
```
CMake Error at ports/catch2/portfile.cmake:20 (file):
  file RENAME failed to rename

    D:/a/1/s/vcpkg/packages/catch2_x86-windows-static-md/debug/share/Catch2

  to

    D:/a/1/s/vcpkg/packages/catch2_x86-windows-static-md/debug/share/catch2

  because: The system cannot find the path specified.
```

**Comment by JackBoosY** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
