### ISSUE TITLE
vishnuaq1-msft:dev/roschuma/usage https://github.com/microsoft/vcpkg-tool/pull/82?

### ISSUE THREAD

**Issue by vishnuaq1** [microsoft/vcpkg#19995]
https://github.com/microsoft/vcpkg-tool/pull/82?

_Originally posted by @JackBoosY in https://github.com/microsoft/vcpkg/issues/16951#issuecomment-846793931_

**Comment by autoantwort** [comment]
There is already https://github.com/microsoft/vcpkg-tool/pull/133

**Comment by JackBoosY** [comment]
I think microsoft/vcpkg-tool#133 is different with microsoft/vcpkg-tool#82.
The #133 is print the usage on the manifest mode, and #82 is add a new vcpkg command to print the installed port's usage.

**Comment by autoantwort** [comment]
But the general goal "getting usage information in manifest mode" is the same.

**Comment by JackBoosY** [comment]
@autoantwort No, that's not the same.
Currently, vcpkg will print the usage after install ports on the command mode, but before 133 merge, we didn't do that on the manifest mode.
And 82 is adding a new vcpkg command to directly print the usage.

**Comment by autoantwort** [comment]
Yeah but the output of 82 would be nearly the same. I mean 
```
➜  vcpkg git:(master) ✗ ./vcpkg install --triplet=x64-osx --host-triplet=x64-osx

Detecting compiler hash for triplet x64-osx...
All requested packages are currently installed.

Total elapsed time: 2 us

The package boost is compatible with built-in CMake targets:

    find_package(Boost REQUIRED [COMPONENTS <libs>...])
    target_link_libraries(main PRIVATE Boost::boost Boost::<lib1> Boost::<lib2> ...)

The package concurrencpp:x64-osx provides CMake targets:

    find_package(concurrencpp CONFIG REQUIRED)
    target_link_libraries(main PRIVATE concurrencpp::concurrencpp)

The package kubazip:x64-osx provides CMake targets:

    find_package(kubazip CONFIG REQUIRED)
    target_link_libraries(main PRIVATE kubazip::kubazip)
```
outputs the nearly same as a new `./vcpkg x-usage --triplet=x64-osx --host-triplet=x64-osx` command (except the first tree lines).

**Comment by JackBoosY** [comment]
Anyway, please track the PR.
