### ISSUE TITLE
Add FFMPEG

### ISSUE THREAD

**Issue by corporateshark** [Microsoft/vcpkg#2]
https://ffmpeg.org/download.html

**Comment by traversaro** [comment]
Related: https://github.com/pyke369/sffmpeg , a superbuild for building ffmpeg and its dependencies (useful to understand all the dependencies of ffmpeg).

**Comment by ras0219-msft** [comment]
I've added an initial port of ffmpeg with only a minimum of dependencies in 2f8d8d8. Please open new issues and pull requests to add more dependencies!
