### ISSUE TITLE
Is port versioning only exposed via manifest?

### ISSUE THREAD

**Issue by jdx-john** [microsoft/vcpkg#20010]
We have looked at using manifest mode but didn't find it really suited our build flow. However the documentation for versioning (https://github.com/microsoft/vcpkg/blob/master/docs/users/versioning.md, https://github.com/microsoft/vcpkg/blob/master/docs/examples/versioning.getting-started.md) appears to all be couched in terms of manifest files.

Is it possible to control versioning using the 'classic' command-line approach? If so, can anyone point me to documentation or provide an example?

Thankyou.

**Comment by autoantwort** [comment]
No, versioning is only possible in manifest mode :)

**Comment by jdx-john** [comment]
Could this be considered a feature request then?

**Comment by autoantwort** [comment]
I don't think that it will works. Versioning and classic mode cannot be conceptually combined well.
