### ISSUE TITLE
How to configure vcpkg to enable all feature package by default

### ISSUE THREAD

**Issue by jasjuang** [Microsoft/vcpkg#2001]
Is there a way to configure vcpkg to enable all feature package by default when installing? Perhaps by a environment variable?

For example I want to type `vcpkg install boost` and it will have the effect of `vcpkg install boost[locale-icu,regex-icu,python] --featurepackages`

Just like if I set `VCPKG_DEFAULT_TRIPLET` to `x64-windows` if I type `vcpkg install ceres` is the same as `vcpkg install ceres:x64-windows`

**Comment by ras0219-msft** [comment]
We don't currently have that, though it seems like an interesting idea. I think a first step would be to add a flag to `install` that requests all features to be installed. E.g:

```
>vcpkg install boost --all-features --featurepackages
```

**Comment by OlafvdSpek** [comment]
`vcpkg install boost[*]` ?

With `--all-features --featurepackages` you can't have the flags apply to only some packages.

**Comment by jasjuang** [comment]
With pcl, vtk, opencv all starting to have feature packages I say we definitely need this. Installing them has starting to become a bit painful.

**Comment by jasjuang** [comment]
vcpkg install package[*] works well for me
