### ISSUE TITLE
[openblas] build failure

### ISSUE THREAD

**Issue by sclel016** [microsoft/vcpkg#20030]
**Host Environment**
- OS: Linux x86-64
- Compiler: GCC 11.2

**To Reproduce**
`./vcpkg install blaze`

**Failure logs** 
[log](https://gist.github.com/sclel016/e230a413233948a9bee2d202cb2b4d9a)

**Additional context**
GTest, Google Benchmark and SPDlog all successfully installed. Tried updating the portfiles but no package updates were found. Looks like an issue in openblas.

**Comment by JackBoosY** [comment]
```
  file STRINGS file
  "/home/<user>/repos/vcpkg/buildtrees/openblas/src/60ab2f2704-82fac8cc89.clean/kernel/x86_64/KERNEL.sandybridge"
  cannot be read.
```
This should be upper-case `KERNEL.SANDYBRIDGE`.
I believed that's a upstream bug, but I will to fix that.

**Comment by JackBoosY** [comment]
Can you please unzip [this file](https://github.com/microsoft/vcpkg/files/7134030/openblas.zip) and replace them into _ports/openblas_ and try again?

**Comment by sclel016** [comment]
Sorry for the delay, I was away on vacation. I'm still getting a failure during `openblas` with your modified portfiles. The error is now in the compilation stage during inlining of some AVX512 intrinsics. I've uploaded the logs [openblas/install-x64-linux-dbg-out.log](https://gist.github.com/sclel016/e230a413233948a9bee2d202cb2b4d9a#file-install-x64-linux-dbg-out-log). I built `OpenBlas` from source using GCC/cmake without issue. Could it be related to do with the arch detection upstream mentioned in https://github.com/xianyi/OpenBLAS/issues/3372 ? I am indeed running a Tiger Lake CPU.

**Comment by JackBoosY** [comment]
@sclel016  Maybe, I'm not sure.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. `blaze` and `openblas` can install succeed in latest vcpkg, please update your vcpkg and rebuild them.
```
Installing 3/3 blaze:x64-linux...
Building blaze[core]:x64-linux...
-- Downloading https://bitbucket.com/blaze-lib/blaze/get/v3.8.1.tar.gz -> blaze-lib-blaze-v3.8.1.tar.gz...
-- Extracting source /home/0417/downloads/blaze-lib-blaze-v3.8.1.tar.gz
-- Using source at /home/0417/buildtrees/blaze/src/v3.8.1-0f55422df0.clean
-- Configuring x64-linux
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Installing: /home/0417/packages/blaze_x64-linux/share/blaze/copyright
-- Performing post-build validation
Stored binaries in 1 destinations.
Elapsed time to handle blaze:x64-linux: 6.9 s
Total install time: 1 min
blaze provides CMake targets:

    # this is heuristically generated, and may not be correct
    find_package(blaze CONFIG REQUIRED)
    target_link_libraries(main PRIVATE blaze::blaze)
```
