### ISSUE TITLE
vcpkg build/install should prevent machine from sleeping

### ISSUE THREAD

**Issue by yuehuang010** [microsoft/vcpkg#2004]
Please add SetThreadExecutionState() (https://msdn.microsoft.com/en-us/library/windows/desktop/aa373208(v=vs.85).aspx )
to prevent the machine from entering sleep state during long builds and installs while the user is AFK.

**Comment by NancyLi1013** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen.
