### ISSUE TITLE
vcpkg: Tensorflow 2.4.1 intall error

### ISSUE THREAD

**Issue by tuiho0706proton** [microsoft/vcpkg#20042]
**I tried to install tensorflow by vcpkg on windows 10.**
- OS: Windows 10 Version 1903
- Compiler: Visual Studio Enterprise 2019 Version 16.10.2

**To Reproduce**
I downloaded vcpkg from https://github.com/microsoft/vcpkg/

 ./bootstrap-vcpkg.bat
`./vcpkg install tensorflow-cc:x64-windows

**Failure logs** 
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: D:/vcpkg-master/downloads/tools/msys2/b3b3d399e80e310e/mingw64/bin/python3.exe -c "import site  print(site.getsitepackages()[0])"
    Working Directory: D:/vcpkg-master/buildtrees/tensorflow-cc
    Error code: 1
    See logs for more information:
      D:\vcpkg-master\buildtrees\tensorflow-cc\prerequesits-pypath-x64-windows-err.log

Call Stack (most recent call first):
  installed/x64-windows/share/tensorflow-common/tensorflow-common.cmake:42 (vcpkg_execute_required_process)
  ports/tensorflow-cc/portfile.cmake:11 (include)
  scripts/ports.cmake:140 (include)

Error: Building package tensorflow-cc:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: tensorflow-cc:x64-windows
  Vcpkg version: 2021-08-12-85ab112d5ee102bc6eac8cdbbfdd173a71374e04

Additionally, attach any relevant sections from the log files above.

**D:\vcpkg-master\buildtrees\tensorflow-cc\prerequesits-pypath-x64-windows-err.log**
This file content is as following:
[prerequesits-pypath-x64-windows-err.log](https://github.com/microsoft/vcpkg/files/7128022/prerequesits-pypath-x64-windows-err.log)

Python path configuration:
PYTHONHOME = (not set)
PYTHONPATH = (not set)
program name = 'D:/vcpkg-master/downloads/tools/msys2/b3b3d399e80e310e/mingw64/bin/python3.exe'
isolated = 0
environment = 1
user site = 1
import site = 1
sys._base_executable = 'D:\vcpkg-master\downloads\tools\msys2\b3b3d399e80e310e\mingw64\bin\python3.exe'
sys.base_prefix = 'D:\msys64\mingw64'
sys.base_exec_prefix = 'D:\msys64\mingw64'
sys.executable = 'D:\vcpkg-master\downloads\tools\msys2\b3b3d399e80e310e\mingw64\bin\python3.exe'
sys.prefix = 'D:\msys64\mingw64'
sys.exec_prefix = 'D:\msys64\mingw64'
sys.path = [
'D:\msys64\mingw64\lib\python38.zip',
'D:\msys64\mingw64\lib\python3.8',
'D:\msys64\mingw64\lib\python3.8',
'D:\msys64\mingw64\lib\lib-dynload',
]
Could not find platform independent libraries 
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to [:<exec_prefix>]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00001264 (most recent call first):

I faced at the above issue.
What can i do?
Please help me with this issue.

**Comment by tuiho0706proton** [comment]
D:\vcpkg-master\buildtrees\tensorflow-cc\prerequesits-pypath-x64-windows-err.log
This file content is as following:

Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = 'D:/vcpkg-master/downloads/tools/msys2/b3b3d399e80e310e/mingw64/bin/python3.exe'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = 'D:\\vcpkg-master\\downloads\\tools\\msys2\\b3b3d399e80e310e\\mingw64\\bin\\python3.exe'
  sys.base_prefix = 'D:\\msys64\\mingw64'
  sys.base_exec_prefix = 'D:\\msys64\\mingw64'
  sys.executable = 'D:\\vcpkg-master\\downloads\\tools\\msys2\\b3b3d399e80e310e\\mingw64\\bin\\python3.exe'
  sys.prefix = 'D:\\msys64\\mingw64'
  sys.exec_prefix = 'D:\\msys64\\mingw64'
  sys.path = [
    'D:\\msys64\\mingw64\\lib\\python38.zip',
    'D:\\msys64\\mingw64\\lib\\python3.8',
    'D:\\msys64\\mingw64\\lib\\python3.8',
    'D:\\msys64\\mingw64\\lib\\lib-dynload',
  ]
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00001264 (most recent call first):
<no Python frame>

Please help me.

**Comment by tuiho0706proton** [comment]
This issue was solved.
I used follow command.

git clone https://github.com/microsoft/vcpkg
bootstrap-vcpkg.bat
vcpkg install tensorflow-cc:x64-windows

I modified something.
In D:\vcpkg\vcpkg\scripts\cmake\vcpkg_acquire_msys.cmake.

       

_>  - URL "https://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-bzip2-1.0.8-1-any.pkg.tar.xz"_
+URL "https://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-bzip2-1.0.8-2-any.pkg.tar.zst"
_>  - SHA512 6e01b26a2144f99ca00406dbce5b8c3e928ec8a3ff77e0b741b26aaf9c927e9bea8cb1b5f38cd59118307e10dd4523a0ea2a1ea61f798f99e6d605ef1d100503_
+SHA512 4f7ba44189d953d4d00e7bbf5a7697233f759c92847c074f0f2888d2a641c59ce4bd3c39617adac0ad7b53c5836e529f9ffd889f976444016976bb517e5c24a2

**Comment by JonLiu1993** [comment]
@tuiho0706proton, you are right, the URL: https://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-bzip2-1.0.8-1-any.pkg.tar.xz is wrong, but I am confused why I cannot reproduce your problem, I will update vcpkg-tool to replace the wrong url

**Comment by tuiho0706proton** [comment]
first I downloaded from
https://github.com/microsoft/vcpkg/archive/refs/heads/master.zip.
In this case, I faced some problem.

Next I used follow command.
git clone https://github.com/microsoft/vcpkg

It worked well.
I don't know about that.
Thanks.
