### ISSUE TITLE
Why VTK cannot be found after installing successfully?

### ISSUE THREAD

**Issue by mjjackey** [microsoft/vcpkg#20041]
### Discussed in https://github.com/microsoft/vcpkg/discussions/20040

<div type='discussions-op-text'>

<sup>Originally posted by **mjjackey** September  8, 2021</sup>
I used vcpkg to install vtk, the installation was successful.
![vtk_vcpkg](https://user-images.githubusercontent.com/14541043/132456261-7e07d688-3a1e-470f-a219-36975f199bd0.png)

After integration configuration, the project still cannot find VTK.

![image](https://user-images.githubusercontent.com/14541043/132456362-e1954a6d-78a6-4790-854b-b856545a38b8.png)

What's the reason of this problem?</div>

**Comment by PhoebeHui** [comment]
Closing in favor of https://github.com/microsoft/vcpkg/discussions/20040.
