### ISSUE TITLE
[zlib] warning: Broken installation of vcpkg port zlib (Android)

### ISSUE THREAD

**Issue by Luiz-Monad** [microsoft/vcpkg#20057]
**Describe the bug**
Is there a reason why I get "Broken installation of vcpkg port zlib" after updating my vcpkg ports.

**Environment**
- Windows + NDK targeting Android 29 on ARM64
<details>
 <summary>Full gory details</summary>

```
    -- Custom Android NDK Toolchain
    -- root:    C:/Microsoft/AndroidSDK/25
    -- ndk:     C:/Microsoft/AndroidSDK/25/ndk
    -- ndk_ver: 22.1.7171670
    -- sys_ver: 29
    -- ninja:   C:/Microsoft/AndroidSDK/25/cmake/3.10.2.4988404/bin/ninja.exe
    -- Android: Targeting API '21' with architecture 'arm64', ABI 'arm64-v8a', and processor 'aarch64'
    -- Custom Android NDK Toolchain
    -- root:    C:/Microsoft/AndroidSDK/25
    -- ndk:     C:/Microsoft/AndroidSDK/25/ndk
    -- ndk_ver: 22.1.7171670
    -- sys_ver: 29
    -- ninja:   C:/Microsoft/AndroidSDK/25/cmake/3.10.2.4988404/bin/ninja.exe
    -- Android: Selected unified Clang toolchain
    -- The C compiler identification is Clang 11.0.5
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working C compiler: C:/Microsoft/AndroidSDK/25/ndk/22.1.7171670/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe - skipped
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- The CXX compiler identification is Clang 11.0.5
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Check for working CXX compiler: C:/Microsoft/AndroidSDK/25/ndk/22.1.7171670/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe - skipped
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    #COMPILER_HASH#4cd580d23fc13bc8374d090d9f853424e245f5ad
    #COMPILER_C_HASH#363c3ee7d32c9d699f2db05451e67a8b4b09faa9
    #COMPILER_C_VERSION#11.0.5
    #COMPILER_C_ID#Clang
    #COMPILER_CXX_HASH#363c3ee7d32c9d699f2db05451e67a8b4b09faa9
    #COMPILER_CXX_VERSION#11.0.5
    #COMPILER_CXX_ID#Clang
```

</details>

**To Reproduce**
1. ./vcpkg install zlib
2. Try to build anythging statically that uses zlib on Android.

**Expected behavior**
No warnings.

**Failure logs** 

<details>
  <summary>Bloody logs!</summary>

```cmake
    -- OpenCV disables pkg-config to avoid using of host libraries. Consider using PKG_CONFIG_LIBDIR to specify target SYSROOT
    CMake Warning at C:/extern/workbench/test/build/outputs/opencv/ndk-android-aarch64-debug/vcpkg_installed/ndk-android-aarch64/share/zlib/vcpkg-cmake-wrapper.cmake:6 (message):
    ZLIB_ROOT:
    C:/extern/workbench/test/build/outputs/opencv/ndk-android-aarch64-debug/vcpkg_installed/ndk-android-aarch64
    Call Stack (most recent call first):
    C:/extern/workbench/test-app/thirdparty/vcpkg/scripts/buildsystems/vcpkg.cmake:738 (include)
    cmake/OpenCVFindLibsGrfmt.cmake:14 (find_package)
    CMakeLists.txt:710 (include)
    CMake Warning at C:/extern/workbench/test/build/outputs/opencv/ndk-android-aarch64-debug/vcpkg_installed/ndk-android-aarch64/share/zlib/vcpkg-cmake-wrapper.cmake:7 (message):
    ZLIB_INCLUDE_DIR:
    C:/extern/workbench/test/build/outputs/opencv/ndk-android-aarch64-debug/vcpkg_installed/ndk-android-aarch64/include
    Call Stack (most recent call first):
    C:/extern/workbench/test-app/thirdparty/vcpkg/scripts/buildsystems/vcpkg.cmake:738 (include)
    cmake/OpenCVFindLibsGrfmt.cmake:14 (find_package)
    CMakeLists.txt:710 (include)
    CMake Warning at C:/extern/workbench/test/build/outputs/opencv/ndk-android-aarch64-debug/vcpkg_installed/ndk-android-aarch64/share/zlib/vcpkg-cmake-wrapper.cmake:8 (message):
    ZLIB_LIBRARY_RELEASE:
    C:/Microsoft/AndroidSDK/25/ndk/22.1.7171670/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/lib/aarch64-linux-android/29/libz.so
    Call Stack (most recent call first):
    C:/extern/workbench/test-app/thirdparty/vcpkg/scripts/buildsystems/vcpkg.cmake:738 (include)
    cmake/OpenCVFindLibsGrfmt.cmake:14 (find_package)
    CMakeLists.txt:710 (include)
    CMake Warning at C:/extern/workbench/test/build/outputs/opencv/ndk-android-aarch64-debug/vcpkg_installed/ndk-android-aarch64/share/zlib/vcpkg-cmake-wrapper.cmake:9 (message):
    ZLIB_LIBRARY_DEBUG: ZLIB_LIBRARY_DEBUG-NOTFOUND
    Call Stack (most recent call first):
    C:/extern/workbench/test-app/thirdparty/vcpkg/scripts/buildsystems/vcpkg.cmake:738 (include)
    cmake/OpenCVFindLibsGrfmt.cmake:14 (find_package)
    CMakeLists.txt:710 (include)
    CMake Warning at C:/extern/workbench/test/build/outputs/opencv/ndk-android-aarch64-debug/vcpkg_installed/ndk-android-aarch64/share/zlib/vcpkg-cmake-wrapper.cmake:10 (message):
    Broken installation of vcpkg port zlib
    Call Stack (most recent call first):
    C:/extern/workbench/test-app/thirdparty/vcpkg/scripts/buildsystems/vcpkg.cmake:738 (include)
    cmake/OpenCVFindLibsGrfmt.cmake:14 (find_package)
    CMakeLists.txt:710 (include)
    -- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
    -- Consider adding OPENCV_ALLOCATOR_STATS_COUNTER_TYPE=int/int64_t according to your build configuration
    -- Excluding from source files list: modules/imgproc/src/corner.avx.cpp
    -- Excluding from source files list: modules/imgproc/src/imgwarp.avx2.cpp
    -- Excluding from source files list: modules/imgproc/src/imgwarp.sse4_1.cpp
```

</details>

**Additional context**
The bisect change that was made, I guess there's a good reason for that warning.

https://github.com/microsoft/vcpkg/blob/7dbc05515b44bf54d2a42b4da9d1e1f910868b86/ports/zlib/portfile.cmake#L34

https://github.com/microsoft/vcpkg/blob/7dbc05515b44bf54d2a42b4da9d1e1f910868b86/ports/zlib/vcpkg-cmake-wrapper.cmake#L6

**Comment by dg0yt** [comment]
You use the wrapper:
`C:/extern/workbench/test/build/outputs/opencv/ndk-android-aarch64-debug/vcpkg_installed/ndk-android-aarch64/share/zlib/vcpkg-cmake-wrapper.cmake`
so your root is:
`C:/extern/workbench/test/build/outputs/opencv/ndk-android-aarch64-debug/vcpkg_installed/ndk-android-aarch64`
ZLIB_INCLUDE_DIR is okay:
`C:/extern/workbench/test/build/outputs/opencv/ndk-android-aarch64-debug/vcpkg_installed/ndk-android-aarch64/include`
ZLIB_LIBRARY_RELEASE is not from vcpkg, so it may be a different version than the headers:
`C:/Microsoft/AndroidSDK/25/ndk/22.1.7171670/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/lib/aarch64-linux-android/29/libz.so`
ZLIB_LIBRARY_DEBUG is not found at all:
`ZLIB_LIBRARY_DEBUG: ZLIB_LIBRARY_DEBUG-NOTFOUND`

I guess there is an issue with the library search path in you project. The vcpkg path should be searched before the NDK path. Vcpkg had a change to support this.
zlib in the NDK was an old version when I needed it, so it really matters to use vcpkg's version for some ports.

**Comment by dg0yt** [comment]
> ZLIB_LIBRARY_DEBUG is not found at all:
> `ZLIB_LIBRARY_DEBUG: ZLIB_LIBRARY_DEBUG-NOTFOUND`

Actually it should be found despite the path issues. Do you really have libz in `C:/extern/workbench/test/build/outputs/opencv/ndk-android-aarch64-debug/vcpkg_installed/ndk-android-aarch64/lib` and `C:/extern/workbench/test/build/outputs/opencv/ndk-android-aarch64-debug/vcpkg_installed/ndk-android-aarch64/debug/lib` ?

**Comment by Luiz-Monad** [comment]
> 
> 
> You use the wrapper:
> `C:/extern/workbench/test/build/outputs/opencv/ndk-android-aarch64-debug/vcpkg_installed/ndk-android-aarch64/share/zlib/vcpkg-cmake-wrapper.cmake`
> so your root is:
> `C:/extern/workbench/test/build/outputs/opencv/ndk-android-aarch64-debug/vcpkg_installed/ndk-android-aarch64`
> ZLIB_INCLUDE_DIR is okay:
> `C:/extern/workbench/test/build/outputs/opencv/ndk-android-aarch64-debug/vcpkg_installed/ndk-android-aarch64/include`
> ZLIB_LIBRARY_RELEASE is not from vcpkg, so it may be a different version than the headers:
> `C:/Microsoft/AndroidSDK/25/ndk/22.1.7171670/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/lib/aarch64-linux-android/29/libz.so`
> ZLIB_LIBRARY_DEBUG is not found at all:
> `ZLIB_LIBRARY_DEBUG: ZLIB_LIBRARY_DEBUG-NOTFOUND`
> 
> I guess there is an issue with the library search path in you project. The vcpkg path should be searched before the NDK path. Vcpkg had a change to support this.
> zlib in the NDK was an old version when I needed it, so it really matters to use vcpkg's version for some ports.

I understood it, I must have done some mixup by mistake.

**Comment by Luiz-Monad** [comment]
> 
> 
> Are we STILL having issues with zlib?
> zlib is such a tiny and simple project that takes a minute to be built from source.
> So far we haven't experienced any issues on Windows 10 x64 (no idea about Android, sorry).

It does indeed work when I build against MSVC and target Windows, it builds from the source.
But when I build against Android, I prefer to use the library from the system.

My problem is that I used headers from vcpkg and the library from Android.
I got confused, but dgoyt clarified it for me.
Its not really a problem to me, to mix the headers and the binaries, they are compatible anyway, I just wanted to know why the warning, as I wasn't understanding why.

The program builds and works fine anyway, its just that I don't like to not know the reason for warning, so I had to investigate before turning it off and marking the reason why I ignored it (by copying zlib and commenting out the check)

**Comment by Luiz-Monad** [comment]
> 
> 
> Are we STILL having issues with zlib?
> zlib is such a tiny and simple project that takes a minute to be built from source.
> So far we haven't experienced any issues on Windows 10 x64 (no idea about Android, sorry).

You may be right, there's no point in saving 3kb of binary code by using the library from Android, I should force it to always use the VCPKG.

**Comment by dg0yt** [comment]
@Luiz-Monad Let me repeat my question: Do you have libz in `C:/extern/workbench/test/build/outputs/opencv/ndk-android-aarch64-debug/vcpkg_installed/ndk-android-aarch64/lib` and `C:/extern/workbench/test/build/outputs/opencv/ndk-android-aarch64-debug/vcpkg_installed/ndk-android-aarch64/debug/lib`?
Even if yes, we may need to verify it is really for aarch-64.

**Comment by Luiz-Monad** [comment]
Yes, I do have it.

**Comment by Luiz-Monad** [comment]
> 
> 
> > ZLIB_LIBRARY_DEBUG is not found at all:
> > `ZLIB_LIBRARY_DEBUG: ZLIB_LIBRARY_DEBUG-NOTFOUND`
> 
> Actually it should be found despite the path issues. Do you really have libz in `C:/extern/workbench/test/build/outputs/opencv/ndk-android-aarch64-debug/vcpkg_installed/ndk-android-aarch64/lib` and `C:/extern/workbench/test/build/outputs/opencv/ndk-android-aarch64-debug/vcpkg_installed/ndk-android-aarch64/debug/lib` ?

I do have it.

Maybe OpenCV did something stupid like this, changing the name of the library. (this has the vcpkg patch applied, I checked it)


    # --- zlib (required) ---
    if(BUILD_ZLIB)
    ocv_clear_vars(ZLIB_FOUND)
    else()
    ocv_clear_internal_cache_vars(ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
    if(ANDROID)
        set(_zlib_ORIG_CMAKE_FIND_LIBRARY_SUFFIXES ${CMAKE_FIND_LIBRARY_SUFFIXES})
        set(CMAKE_FIND_LIBRARY_SUFFIXES .so)
    endif()
    find_package(ZLIB "${MIN_VER_ZLIB}" REQUIRED)
    if(ANDROID)
        set(CMAKE_FIND_LIBRARY_SUFFIXES ${_zlib_ORIG_CMAKE_FIND_LIBRARY_SUFFIXES})
        unset(_zlib_ORIG_CMAKE_FIND_LIBRARY_SUFFIXES)
    endif()
    if(ZLIB_FOUND AND ANDROID)
        if(ZLIB_LIBRARIES MATCHES "/usr/lib.*/libz.so$")
        set(ZLIB_LIBRARIES z)
        endif()
    endif()
    endif()

    if(NOT ZLIB_FOUND)
    ocv_clear_vars(ZLIB_LIBRARY ZLIB_LIBRARIES ZLIB_INCLUDE_DIR)

    set(ZLIB_LIBRARY zlib CACHE INTERNAL "")
    add_subdirectory("${OpenCV_SOURCE_DIR}/3rdparty/zlib")
    set(ZLIB_INCLUDE_DIR "${${ZLIB_LIBRARY}_SOURCE_DIR}" "${${ZLIB_LIBRARY}_BINARY_DIR}" CACHE INTERNAL "")
    set(ZLIB_INCLUDE_DIRS ${ZLIB_INCLUDE_DIR})
    set(ZLIB_LIBRARIES ${ZLIB_LIBRARY})

    ocv_parse_header2(ZLIB "${${ZLIB_LIBRARY}_SOURCE_DIR}/zlib.h" ZLIB_VERSION)
    endif()

**Comment by Luiz-Monad** [comment]
That was it 


This makes sense now.

    if(ZLIB_FOUND AND ANDROID)
        if(ZLIB_LIBRARIES MATCHES "/usr/lib.*/libz.so$")
        set(ZLIB_LIBRARIES z)
        endif()
    endif()

OpenCV was messing with it.
Let me check if I updated the ports to the new version.

**Comment by dg0yt** [comment]
What a "hack". I added the zlib wrapper not so long ago but I didn't know about that. Now I feel even more comfortable with the extra check and message in the zlib wrapper.

**Comment by Luiz-Monad** [comment]
The ports are on the updated version, nothing changed on **OpenCVFindLibsGrfmt.cmake** .
We either add a patch to remove those lines on top of it to get rid of the warning and use the compiled version.
Or we can ignore the warning and use the android dynamic library version, either way will work.

**Comment by Luiz-Monad** [comment]
That really confused me, I wasn't suspecting it, because I have a lot of other libraries that use zlib and work fine on android, but this specific OpenCV one...

**Comment by dg0yt** [comment]
You have to stay with one version of zlib. As some ports need a more recent zlib this means you have to use vpkg's one.

(However, a no-op overlay-port for zlib could redirect the build to Android's zlib if this is desired.)

**Comment by Luiz-Monad** [comment]
This might be desired at some point by someone else.
In my case I only made it by mistake, and because I was already doing it before.
But this and _sfhacker_ convinced me that its better to use the vcpkg static one anyway.
So I opt to fix my OpenCV port meanwhile, I do customize a lot of things on my opencv, so its not a problem to hack off their "hack".

**Comment by cenit** [comment]
> The ports are on the updated version, nothing changed on **OpenCVFindLibsGrfmt.cmake** .
> We either add a patch on top of it on OpenCV to remove those lines, that will fix the problem and get rid of the warning and use the compiled version, and it makes more sense.
> Or we can ignore the warning and use the android dynamic library version, either way will work, but I'm starting to think it doesn't help much saving a few kilobytes.

we can do a patch specific for android here in vcpkg. We already "undo" some workarounds that opencv has in its toolchain that break many things for windows (ffmpeg, protobuf, image libs), we can revert also this zlib one for android and put it back in the normal flow of checks

**Comment by dg0yt** [comment]
It needs to be patched in vcpkg. However, it needs a contributor with an Android toolchain, space and time.

**Comment by JackBoosY** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.

**Comment by reynoldsbd** [comment]
I was able to get a local repro of this issue pretty easily:

```
> $Env:ANDROID_NDK_HOME = "$HOME\AppData\Local\Android\Sdk\ndk\22.1.7171670\"
> .\vcpkg.exe install opencv --triplet=x64-android

<snip>

-- Configuring x64-android
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:128 (message):
    Command failed: ninja -v
    Working Directory: D:/Source/vcpkg/buildtrees/opencv4/x64-android-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\Source\vcpkg\buildtrees\opencv4\config-x64-android-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:415 (vcpkg_execute_required_process)
  ports/opencv4/portfile.cmake:390 (vcpkg_cmake_configure)
  scripts/ports.cmake:145 (include)

<snip>
```

Relevant error message from the configure log:

```
CMake Error at D:/Source/vcpkg/installed/x64-android/share/zlib/vcpkg-cmake-wrapper.cmake:5 (message):
  Broken installation of vcpkg port zlib
Call Stack (most recent call first):
  D:/Source/vcpkg/scripts/buildsystems/vcpkg.cmake:743 (include)
  cmake/OpenCVFindLibsGrfmt.cmake:14 (find_package)
  CMakeLists.txt:724 (include)
```

I was able to successfully build by simply removing the `if(ANDROID)` hacks from _OpenCVFindLibsGrfmt.cmake_. Opening a PR now...

**Comment by mlt** [comment]
The problem with zlib and cross-compilation is that `vcpkg-cmake-wrapper.cmake` wrapper does not include `NO_CMAKE_FIND_ROOT_PATH` while `CMAKE_FIND_ROOT_PATH` is set to something like, e.g.,  `/usr/x86_64-w64-mingw32` while cross-compiling for Windows from Linux using *x64-mingw-dynamic* triplet. A workaround could be
```sh
sed -i 's/NO_DEFAULT_PATH/NO_DEFAULT_PATH NO_CMAKE_FIND_ROOT_PATH/' $VCPKG_ROOT/installed/x64-mingw-dynamic/share/zlib/vcpkg-cmake-wrapper.cmake
```

**Comment by dg0yt** [comment]
> ~~~cmake
>     set(CMAKE_FIND_LIBRARY_SUFFIXES .so)

This was breaking the deal for a static android triplet.
