### ISSUE TITLE
MIL

### ISSUE THREAD

**Issue by MilliSamz** [microsoft/vcpkg#20094]
Library name:MIL

New version number:7

Other information that may be useful (release notes, etc...)

**Comment by PhoebeHui** [comment]
@MilliSamz, we don't have a port named MIL, could you confirm the port name?

**Comment by PhoebeHui** [comment]
@MilliSamz, could you provide us more information? such as the homepage of the library?

**Comment by PhoebeHui** [comment]
@MilliSamz, please reopen this issue and provide us more information if it still be a request for you.
