### ISSUE TITLE
liblzma build failure

### ISSUE THREAD

**Issue by agnickolov** [microsoft/vcpkg#20106]
**Host Environment**
- Host OS: MacOS
- Target OS: iOS
- Compiler: AppleClang / Xcode 12.5.1

**To Reproduce**
Define a CMake project on MacOS that cross-compiles to iOS.
Add a dependency to Boost in its vcpkg manifest.
vcpkg fails to build liblzma for iOS, which is one of the dependencies for Boost.
`./vcpkg install xxxx`

**Failure logs** 
-Cut and paste the appropriate build messages from the console output.
m64-ios/debug
    Working Directory: /Users/alexander.nickolov/git/vcpkg/buildtrees/liblzma/arm64-ios-dbg
    Error code: 1
    See logs for more information:
      /Users/alexander.nickolov/git/vcpkg/buildtrees/liblzma/config-arm64-ios-dbg-out.log
      /Users/alexander.nickolov/git/vcpkg/buildtrees/liblzma/config-arm64-ios-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:369 (vcpkg_execute_required_process)
  buildtrees/versioning/versions/liblzma/5f491131f98307f42a98db7ad0b5455225481284/portfile.cmake:13 (vcpkg_configure_cmake)
  scripts/ports.cmake:140 (include)

Error: Building package liblzma:arm64-ios failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: liblzma:arm64-ios
  Vcpkg version: 2021-08-12-unknownhash

-Please attach any additional failure logs mentioned in the console output.
CMake Error at CMakeLists.txt:527 (install):
  install TARGETS given no BUNDLE DESTINATION for MACOSX_BUNDLE executable
  target "xzdec".

CMake Error at CMakeLists.txt:654 (install):
  install TARGETS given no BUNDLE DESTINATION for MACOSX_BUNDLE executable
  target "xz".

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

The problem is that liblzma tries to build its executables for iOS. These should not be built since they make no sense as they are command-line executables.

Here is an excerpt from the CMakeLists.txt file for liblzma for the first error. It should check about a desktop OS, but it doesn't. Alternatively, a BUNDLE destination can be provided in the install directive.

if(HAVE_GETOPT_LONG)
    add_executable(xzdec
        src/common/sysdefs.h
        src/common/tuklib_common.h
        src/common/tuklib_config.h
        src/common/tuklib_exit.c
        src/common/tuklib_exit.h
        src/common/tuklib_gettext.h
        src/common/tuklib_progname.c
        src/common/tuklib_progname.h
        src/xzdec/xzdec.c
    )

    target_include_directories(xzdec PRIVATE
        src/common
        src/liblzma/api
    )

    target_link_libraries(xzdec PRIVATE liblzma)

    tuklib_progname(xzdec)

    install(TARGETS xzdec
            RUNTIME DESTINATION "${CMAKE_INSTALL_BINDIR}"
                    COMPONENT xzdec)

    if(UNIX)
        install(FILES src/xzdec/xzdec.1
                DESTINATION "${CMAKE_INSTALL_MANDIR}/man1"
                COMPONENT xzdec)
    endif()
endif()

I'd submit a fix myself, but I don't know which GitHub repo to target...

**Comment by agnickolov** [comment]
I notice there already is a patch for this issue in the portfile for liblzma: add_support_ios.patch. The problem is that this patch is not getting applied. I manually checked the buildtrees folder and the patch has not been applied there, both on Mac OS for iOS builds and on Windows for my Windows builds. At a guess, the previous two patches conflict with it because they both insert a line each before the patch locations for the iOS patch. Moving it above fix_config_include.patch should hopefully resolve the issue without breaking the other two patches.

**Comment by agnickolov** [comment]
It was as I expected. I created a private registry and copied the entire port for liblzma. Then I modified the patch order to have the iOS patch as second instead of fourth in the list. I also updated the patch file itself to reduce the line numbers by 2. With these changes in place and my registry listed as the source for liblzma, the patch is properly applied and the code builds fine for iOS. The other two Windows patches to CMakeLists.txt are applied properly as well.

Hopefully this issue is resolved soon for the built-in vcpkg registry so I can remove my private registry from my builds.

**Comment by dg0yt** [comment]
> I notice there already is a patch for this issue in the portfile for liblzma: add_support_ios.patch. The problem is that this patch is not getting applied. I manually checked the buildtrees folder and the patch has not been applied there, both on Mac OS for iOS builds and on Windows for my Windows builds. At a guess, the previous two patches conflict with it because they both insert a line each before the patch locations for the iOS patch. Moving it above fix_config_include.patch should hopefully resolve the issue without breaking the other two patches.

On linux, I cannot confirm your claims. `add_support_ios.patch` applies cleanly, according to `buildtrees/liblzma/patch-x64-linux-3-err.log`, and `BUNDLE_DESTINATION` shows as expected in `CMakeLists.txt`.

With the pristine vcpkg port, what is the contents of your `buildtrees/liblzma/patch-x64-linux-3-err.log`?

**Comment by agnickolov** [comment]
I don't have a Linux machine so cannot speak about that OS. On Windows and MacOS (building for iOS) the patch is reported as applied successfully, but the BUNDLE entries are missing from CMakeLists.txt. As I mentioned above, reordering the patches so the iOS patch is applied first (and fixing up its line numbers accordingly of course) results in the patch actually being applied successfully on both Windows and MacOS with the BUNDLE entries present in the patched file.

**Comment by dg0yt** [comment]
I can't reproduce this also on Windows... `BUNDLE DESTINATION` is there. Do you look at the right src dir? Did you try to remove `buildtrees/liblzma` before build? 
(I don't dare to ask for `git pull` because otherwise the patch wouldn't be on your disk / in portfile.cmake.)

**Comment by agnickolov** [comment]
It took me some time, but I managed to reproduce it again (on Windows). I deleted the cached build and the build tree for liblzma so everything was re-downloaded. The problem is that the iOS patch is not applied at all. Here is the relevant build output (stdout-x86-windows.log):

-- Using C:/git/vcpkg/vcpkg/downloads/xz-mirror-xz-v5.2.5.tar.gz
-- Extracting source C:/git/vcpkg/vcpkg/downloads/xz-mirror-xz-v5.2.5.tar.gz
-- Applying patch enable-uwp-builds.patch
-- Applying patch fix_config_include.patch
-- Applying patch win_output_name.patch
-- Using source at C:/git/vcpkg/vcpkg/buildtrees/liblzma/src/v5.2.5-77236e0e89.clean
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
CMake Warning at scripts/cmake/vcpkg_copy_pdbs.cmake:70 (message):
  Could not find a matching pdb file for:

      

Call Stack (most recent call first):
  buildtrees/versioning/versions/liblzma/5f491131f98307f42a98db7ad0b5455225481284/portfile.cmake:20 (vcpkg_copy_pdbs)
  scripts/ports.cmake:141 (include)


-- Using msys root at C:/git/vcpkg/vcpkg/downloads/tools/msys2/aa5af7b2aa7e90e8
-- Fixing pkgconfig file: C:/git/vcpkg/vcpkg/packages/liblzma_x86-windows/lib/pkgconfig/liblzma.pc
-- Fixing pkgconfig file: C:/git/vcpkg/vcpkg/packages/liblzma_x86-windows/debug/lib/pkgconfig/liblzma.pc
-- Installing: C:/git/vcpkg/vcpkg/packages/liblzma_x86-windows/share/liblzma/copyright

And this is the beginning of its portfile.cmake where all 4 patches are specified:

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO xz-mirror/xz
    REF v5.2.5
    SHA512 686f01cfe33e2194766a856c48668c661b25eee194a443524f87ce3f866e0eb54914075b4e00185921516c5211db8cd5d2658f4b91f4a3580508656f776f468e
    HEAD_REF master
    PATCHES
        enable-uwp-builds.patch
        fix_config_include.patch
        win_output_name.patch # Fix output name on Windows. Autotool build does not generate lib prefixed libraries on windows. 
        add_support_ios.patch # add install bundle info for support ios 
)

All 4 patches are available in the port folder.

There is no output for a fourth patch, e.g. no patch-x86-windows-3-err.log file exists.

**Comment by dg0yt** [comment]
~~~
Call Stack (most recent call first):
buildtrees/versioning/versions/liblzma/5f491131f98307f42a98db7ad0b5455225481284/portfile.cmake:20 (vcpkg_copy_pdbs)
~~~

Hm, I guess this is in manifest mode, and the manifest refers to the port version before the iOS patches. 5f491131f98307f42a98db7ad0b5455225481284 is liblzma 5.2.5#2. The patch is in 2.5.2#3.

**Comment by agnickolov** [comment]
Yeah, I figured the same myself too. I updated the builtin-baseline to the commit hash for the current head as of today and the problem gets resolved.
