### ISSUE TITLE
[libjpeg-turbo] build failure

### ISSUE THREAD

**Issue by esohns** [microsoft/vcpkg#20110]
**Host Environment**
- Windows
- NASM version 2.12.01

**To Reproduce**
`.\\vcpkg install libjpeg-turbo`

**Failure logs** 
Error: Building package libjpeg-turbo:x86-windows failed with: BUILD_FAILED

**Additional context**
Vcpkg version: 2021-08-12-85ab112d5ee102bc6eac8cdbbfdd173a71374e04
[install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/7147646/install-x86-windows-dbg-out.log)

**Comment by dg0yt** [comment]
https://github.com/libjpeg-turbo/libjpeg-turbo/blob/main/BUILDING.md#build-requirements:

> If using NASM, 2.13 or later is required.

But port yasm in vcpkg should be recent enough, and the x64/x86 host/target issues should be resolved. Perhaps portlibjpeg-turbo could use host port yasm?

**Comment by esohns** [comment]
yes, that was the problem. I updated NASM and now it's working.
Thanks for pointing this out to me !

**Comment by dg0yt** [comment]
> But port yasm in vcpkg should be recent enough, and the x64/x86 host/target issues should be resolved. Perhaps portlibjpeg-turbo could use host port yasm?

Port libjpeg-turbo already acquires nasm via vcpkg. But its location is *appended* to `PATH`. I guess this is meant to allow using a newer version. It would probably be possible to actually enforce vcpkg's nasm (i.e. the CI-tested configuration) without touching `PATH` at all.
