### ISSUE TITLE
Throw error if .vcpkg-root is missing

### ISSUE THREAD

**Issue by JulianGro** [microsoft/vcpkg#20125]
****

**Is your feature request related to a problem? Please describe.**
When `.vcpkg-root` is missing, you will run into issues where cmake will eternally check for that file. This is the case even if `VCPKG_ROOT` is provided to vcpkg.

**Proposed solution**
Since this causes later steps to fail, it should throw an error or a warning that no `.vcpkg-root` file has been found and that this might cause problems.

**Describe alternatives you've considered**
Alternatively `.vcpkg-root` could be made a non-hidden file instead. E.g. `vcpkg-root`.

**Additional context**
The reason the `.vcpkg-root` file might be missing is because it is hidden. When copying, moving, or archiving vcpkg binaries, they can easily get lost.
In my case my archiver didn't add `.vcpkg-root` to the archive. It literally took me 1 1/2 years to figure out that this file was missing (because it was hidden everywhere).

**Comment by dg0yt** [comment]
> **Describe alternatives you've considered**
> Alternatively `.vcpkg-root` could be made a non-hidden file instead. E.g. `vcpkg-root`.

Or `_vcpkg-root`.

**Comment by Adela0814** [comment]
Fixed by PR #22694
