### ISSUE TITLE
[libdatachannel] LibDatachannel::datachannel rename LibDataChannel::LibDataChannel

### ISSUE THREAD

**Issue by KangLin** [microsoft/vcpkg#20126]
The libdatachannel rename LibDataChannel::LibDataChannel.
See: https://github.com/paullouisageneau/libdatachannel/pull/473

**Comment by NancyLi1013** [comment]
Hi @KangLin 

Thanks for your information. Since there is no new released version that contains the changes now. We will update to the next version to fix this.
