### ISSUE TITLE
[glslang]:arm64-linux build waits for something eternally when running in Docker

### ISSUE THREAD

**Issue by JulianGro** [microsoft/vcpkg#20120]
**Host Environment**
- OS: Linux Debian Bullseye
- Compiler: I have no idea it is using whatever got installed by the build-essential package
- vcpkg version: 2021.05.12

**To Reproduce**
`./vcpkg install glslang`

**Failure logs** 
Terminal output including strace:
```
Starting package 1/5: glslang:arm64-linux-release
Building package glslang[core]:arm64-linux-release...
read(4, "-- Extracting source /tmp/github"..., 4096) = 165
read(4, "-- Using source at /tmp/github-r"..., 4096) = 146
read(4, "-- Configuring arm64-linux-relea"..., 4096) = 39
read(4, 0x55af51c0b0, 4096)             = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGURG {si_signo=SIGURG, si_code=SI_USER, si_pid=1, si_uid=0} ---
read(4, 0x55af51c0b0, 4096)             = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGURG {si_signo=SIGURG, si_code=SI_USER, si_pid=1, si_uid=0} ---
read(4, 0x55af51c0b0, 4096)             = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGURG {si_signo=SIGURG, si_code=SI_USER, si_pid=1, si_uid=0} ---
```

**Additional context**
I am running vcpkg inside a Debian Bullseye aarch64 Docker container on a Debian Bullseye aarch64 host system.
When trying to build vcpkg, it gets stuck at `Building package glslang[core]:arm64-linux-release...` with 100% CPU usage.
I ran it with strace to find out what it is waiting on but have no idea what to make of this.

A friend of mine says:
"hm. So my best guess: signals interrupt syscalls. Eg, if you're doing a read from a socket, and a signal arrives, then read() aborts. The program then needs to detect what happened and retry to read. What I think might be going on there is that for whatever reason, there's urgent data available. So read aborts. The program doesn't handle the presence of urgent data, retries the read. Urgent data is still waiting to be handled, signal happens again, read stops. And so on. Just guessing here though."

I also have to run vcpkg with `--feature-flags=-compilertracking` because it will freeze at that stage otherwise.
Obviously I am at a loss for what is going on. Only thing I know is that vcpkg should exit with an error or at least throw a warning instead of just staying frozen forever.

If I don't run with `--feature-flags=-compilertracking` then it will freeze at `Detecting compiler hash for triplet arm64-linux-release...` without strace showing anything after that. Not sure if this is related or not.
```newfstatat(AT_FDCWD, "/tmp/github-runner-JulianGro-vircadia/vircadia-files/vcpkg/139a2bcd-release/buildtrees/detect_compiler", 0x7ff5cceb10, AT_SYMLINK_NOFOLLOW) = -1 ENOENT (No such file or directory)
mkdirat(AT_FDCWD, "/tmp/github-runner-JulianGro-vircadia/vircadia-files/vcpkg/139a2bcd-release/buildtrees/detect_compiler", 0777) = 0
openat(AT_FDCWD, "/tmp/github-runner-JulianGro-vircadia/vircadia-files/vcpkg/139a2bcd-release/buildtrees/detect_compiler/stdout-arm64-linux-release.log", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 3
write(1, "The following packages will be b"..., 502) = 502
pipe2([4, 5], O_CLOEXEC)                = 0
prlimit64(0, RLIMIT_NOFILE, NULL, {rlim_cur=1024*1024, rlim_max=1024*1024}) = 0
prlimit64(0, RLIMIT_NOFILE, NULL, {rlim_cur=1024*1024, rlim_max=1024*1024}) = 0
mmap(NULL, 36864, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7fadd98000
rt_sigprocmask(SIG_BLOCK, ~[], [], 8)   = 0
clone(child_stack=0x7fadda1000, flags=CLONE_VM|CLONE_VFORK|SIGCHLD) = 7986
munmap(0x7fadd98000, 36864)             = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
close(5)                                = 0
fcntl(4, F_SETFD, 0)                    = 0
fstat(4, {st_mode=S_IFIFO|0600, st_size=0, ...}) = 0
read(4, "-- Configuring arm64-linux-relea"..., 4096) = 39
    hifi-host-tools[core]:arm64-linux-release -> 0
  * hifi-scribe[core]:arm64-linux-release -> 1bd638a36ca771e5a68d01985b6389b71835cbd2
  * spirv-cross[core]:arm64-linux-release -> 2018-08-07-1
  * spirv-tools[core]:arm64-linux-release -> 2018.5-1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet arm64-linux-release...
```

This only seems to happen in aarch64 Docker. I tested multiple images with the same results.
These issues also don't happen in amd64 Docker on a different host.
Running on the host without Docker in between does allow vcpkg to finish normally.

**Comment by JulianGro** [comment]
Digging a little deeper, I am closer (or at) the place where the compilertracking gets stuck. I ran whatever vcpkg tried to run with 
`--trace-extended` and this is where it stops:
```
/git/vircadia-builder/vcpkg/scripts/cmake/vcpkg_execute_in_download_mode.cmake(58):  execute_process(COMMAND /git/vircadia-builder/cmake-3.21.2-linux-aarch64/bin/cmake;/git/vircadia-builder/vcpkg/scripts/detect_compiler;-DCMAKE_MAKE_PROGRAM=/usr/bin/ninja;-DCMAKE_SYSTEM_NAME=Linux;-DBUILD_SHARED_LIBS=OFF;-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/git/vircadia-builder/vcpkg/scripts/toolchains/linux.cmake;-DVCPKG_TARGET_TRIPLET=arm64-linux;-DVCPKG_SET_CHARSET_FLAG=ON;-DVCPKG_PLATFORM_TOOLSET=external;-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON;-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE;-DCMAKE_VERBOSE_MAKEFILE=ON;-DVCPKG_APPLOCAL_DEPS=OFF;-DCMAKE_TOOLCHAIN_FILE=/git/vircadia-builder/vcpkg/scripts/buildsystems/vcpkg.cmake;-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON;-DVCPKG_CXX_FLAGS=;-DVCPKG_CXX_FLAGS_RELEASE=;-DVCPKG_CXX_FLAGS_DEBUG=;-DVCPKG_C_FLAGS=;-DVCPKG_C_FLAGS_RELEASE=;-DVCPKG_C_FLAGS_DEBUG=;-DVCPKG_CRT_LINKAGE=dynamic;-DVCPKG_LINKER_FLAGS=;-DVCPKG_LINKER_FLAGS_RELEASE=;-DVCPKG_LINKER_FLAGS_DEBUG=;-DVCPKG_TARGET_ARCHITECTURE=arm64;-DCMAKE_INSTALL_LIBDIR:STRING=lib;-DCMAKE_INSTALL_BINDIR:STRING=bin;-D_VCPKG_ROOT_DIR=/git/vircadia-builder/vcpkg;-D_VCPKG_INSTALLED_DIR=/git/vircadia-builder/vcpkg/installed;-DVCPKG_MANIFEST_INSTALL=OFF;-G;Ninja;-DCMAKE_BUILD_TYPE=Release;-DCMAKE_INSTALL_PREFIX=/git/vircadia-builder/vcpkg/packages/detect_compiler_arm64-linux WORKING_DIRECTORY;/git/vircadia-builder/vcpkg/buildtrees/detect_compiler/arm64-linux-rel;RESULT_VARIABLE;error_code;OUTPUT_FILE;/git/vircadia-builder/vcpkg/buildtrees/detect_compiler/config-arm64-linux-rel-out.log;ERROR_FILE;/git/vircadia-builder/vcpkg/buildtrees/detect_compiler/config-arm64-linux-rel-err.log )
```
(don't mind the /git/vircadia-builder/ I just used a random folder)
That command runs, uses 100% cpu and never finished.
If I run the same command by hand I get:
```
root@11-slim:/git/vircadia-builder/vcpkg# /git/vircadia-builder/cmake-3.21.2-linux-aarch64/bin/cmake /git/vircadia-builder/vcpkg/scripts/detect_compiler -DCMAKE_MAKE_PROGRAM=/usr/bin/ninja -DCMAKE_SYSTEM_NAME=Linux -DBUILD_SHARED_LIBS=OFF -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/git/vircadia-builder/vcpkg/scripts/toolchains/linux.cmake -DVCPKG_TARGET_TRIPLET=arm64-linux -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=external -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=/git/vircadia-builder/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_LINKER_FLAGS_RELEASE= -DVCPKG_LINKER_FLAGS_DEBUG= -DVCPKG_TARGET_ARCHITECTURE=arm64 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -D_VCPKG_ROOT_DIR=/git/vircadia-builder/vcpkg -D_VCPKG_INSTALLED_DIR=/git/vircadia-builder/vcpkg/installed -DVCPKG_MANIFEST_INSTALL=OFF -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/git/vircadia-builder/vcpkg/packages/detect_compiler_arm64-linux
CMake Error: Error: generator : Ninja
Does not match the generator used previously: Unix Makefiles
Either remove the CMakeCache.txt file and CMakeFiles directory or choose a different binary directory.
root@11-slim:/git/vircadia-builder/vcpkg# 
```
Not sure if this is of any use. Do tell me if there is a better way to debug vcpkg by having it run `--trace-expand` on all cmake operations, etc..

**Comment by JulianGro** [comment]
Okay I think I have found the problem.
Running strace on the child process shows that it is trying to access a file that is not there:
```
[pid 13781] faccessat(AT_FDCWD, "//.vcpkg-root", R_OK) = -1 ENOENT (No such file or directory)
[pid 13781] newfstatat(AT_FDCWD, "/", {st_mode=S_IFDIR|0755, st_size=4096, ...}, 0) = 0
[pid 13781] faccessat(AT_FDCWD, "//.vcpkg-root", R_OK) = -1 ENOENT (No such file or directory)
[pid 13781] newfstatat(AT_FDCWD, "/", {st_mode=S_IFDIR|0755, st_size=4096, ...}, 0) = 0
[pid 13781] faccessat(AT_FDCWD, "//.vcpkg-root", R_OK) = -1 ENOENT (No such file or directory)
[pid 13781] newfstatat(AT_FDCWD, "/", {st_mode=S_IFDIR|0755, st_size=4096, ...}, 0) = 0
[pid 13781] faccessat(AT_FDCWD, "//.vcpkg-root", R_OK) = -1 ENOENT (No such file or directory)
[pid 13781] newfstatat(AT_FDCWD, "/", {st_mode=S_IFDIR|0755, st_size=4096, ...}, 0) = 0
[pid 13781] faccessat(AT_FDCWD, "//.vcpkg-root", R_OK) = -1 ENOENT (No such file or directory)
[pid 13781] newfstatat(AT_FDCWD, "/", {st_mode=S_IFDIR|0755, st_size=4096, ...}, 0) = 0
[pid 13781] faccessat(AT_FDCWD, "//.vcpkg-root", R_OK) = -1 ENOENT (No such file or directory)
```
 I have run into this issue on Ubuntu 18.04 aarch64 without Docker in the past as well.
 Here is the full strace if someone wants to take a look: [strace1.log.zip](https://github.com/microsoft/vcpkg/files/7151721/strace1.log.zip)

**Comment by dg0yt** [comment]
> Digging a little deeper, I am closer (or at) the place where the compilertracking gets stuck. I ran whatever vcpkg tried to run with
> `--trace-extended` and this is where it stops:
> 
> ```
> /git/vircadia-builder/vcpkg/scripts/cmake/vcpkg_execute_in_download_mode.cmake(58):  execute_process(COMMAND /git/vircadia-builder/cmake-3.21.2-linux-aarch64/bin/cmake;/git/vircadia-builder/vcpkg/scripts/detect_compiler;-DCMAKE_MAKE_PROGRAM=/usr/bin/ninja;-DCMAKE_SYSTEM_NAME=Linux;-DBUILD_SHARED_LIBS=OFF;-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/git/vircadia-builder/vcpkg/scripts/toolchains/linux.cmake;-DVCPKG_TARGET_TRIPLET=arm64-linux;-DVCPKG_SET_CHARSET_FLAG=ON;-DVCPKG_PLATFORM_TOOLSET=external;-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON;-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE;-DCMAKE_VERBOSE_MAKEFILE=ON;-DVCPKG_APPLOCAL_DEPS=OFF;-DCMAKE_TOOLCHAIN_FILE=/git/vircadia-builder/vcpkg/scripts/buildsystems/vcpkg.cmake;-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON;-DVCPKG_CXX_FLAGS=;-DVCPKG_CXX_FLAGS_RELEASE=;-DVCPKG_CXX_FLAGS_DEBUG=;-DVCPKG_C_FLAGS=;-DVCPKG_C_FLAGS_RELEASE=;-DVCPKG_C_FLAGS_DEBUG=;-DVCPKG_CRT_LINKAGE=dynamic;-DVCPKG_LINKER_FLAGS=;-DVCPKG_LINKER_FLAGS_RELEASE=;-DVCPKG_LINKER_FLAGS_DEBUG=;-DVCPKG_TARGET_ARCHITECTURE=arm64;-DCMAKE_INSTALL_LIBDIR:STRING=lib;-DCMAKE_INSTALL_BINDIR:STRING=bin;-D_VCPKG_ROOT_DIR=/git/vircadia-builder/vcpkg;-D_VCPKG_INSTALLED_DIR=/git/vircadia-builder/vcpkg/installed;-DVCPKG_MANIFEST_INSTALL=OFF;-G;Ninja;-DCMAKE_BUILD_TYPE=Release;-DCMAKE_INSTALL_PREFIX=/git/vircadia-builder/vcpkg/packages/detect_compiler_arm64-linux WORKING_DIRECTORY;/git/vircadia-builder/vcpkg/buildtrees/detect_compiler/arm64-linux-rel;RESULT_VARIABLE;error_code;OUTPUT_FILE;/git/vircadia-builder/vcpkg/buildtrees/detect_compiler/config-arm64-linux-rel-out.log;ERROR_FILE;/git/vircadia-builder/vcpkg/buildtrees/detect_compiler/config-arm64-linux-rel-err.log )
> ```

Is this the exact string? There is one strange spot:
~~~
...;-DCMAKE_INSTALL_PREFIX=/git/vircadia-builder/vcpkg/packages/detect_compiler_arm64-linux WORKING_DIRECTORY;...
~~~
Note the plain ` ` in front of `WORKING_DIRECTORY` which should be a `;` if consistent.

**Comment by JulianGro** [comment]
> Is this the exact string? There is one strange spot:
> 
> ```
> ...;-DCMAKE_INSTALL_PREFIX=/git/vircadia-builder/vcpkg/packages/detect_compiler_arm64-linux WORKING_DIRECTORY;...
> ```
> 
> Note the plain ` ` in front of `WORKING_DIRECTORY` which should be a `;` if consistent.

Yes. I just double-checked.

**Comment by JulianGro** [comment]
That might be a good clue actually. The command is cut off at that point. See:
cmake --trace-extended output:
```
execute_process(COMMAND /git/vircadia-builder/cmake-3.21.2-linux-aarch64/bin/cmake;/git/vircadia-builder/vcpkg/scripts/detect_compiler;-DCMAKE_MAKE_PROGRAM=/usr/bin/ninja;-DCMAKE_SYSTEM_NAME=Linux;-DBUILD_SHARED_LIBS=OFF;-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/git/vircadia-builder/vcpkg/scripts/toolchains/linux.cmake;-DVCPKG_TARGET_TRIPLET=arm64-linux;-DVCPKG_SET_CHARSET_FLAG=ON;-DVCPKG_PLATFORM_TOOLSET=external;-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON;-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE;-DCMAKE_VERBOSE_MAKEFILE=ON;-DVCPKG_APPLOCAL_DEPS=OFF;-DCMAKE_TOOLCHAIN_FILE=/git/vircadia-builder/vcpkg/scripts/buildsystems/vcpkg.cmake;-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON;-DVCPKG_CXX_FLAGS=;-DVCPKG_CXX_FLAGS_RELEASE=;-DVCPKG_CXX_FLAGS_DEBUG=;-DVCPKG_C_FLAGS=;-DVCPKG_C_FLAGS_RELEASE=;-DVCPKG_C_FLAGS_DEBUG=;-DVCPKG_CRT_LINKAGE=dynamic;-DVCPKG_LINKER_FLAGS=;-DVCPKG_LINKER_FLAGS_RELEASE=;-DVCPKG_LINKER_FLAGS_DEBUG=;-DVCPKG_TARGET_ARCHITECTURE=arm64;-DCMAKE_INSTALL_LIBDIR:STRING=lib;-DCMAKE_INSTALL_BINDIR:STRING=bin;-D_VCPKG_ROOT_DIR=/git/vircadia-builder/vcpkg;-D_VCPKG_INSTALLED_DIR=/git/vircadia-builder/vcpkg/installed;-DVCPKG_MANIFEST_INSTALL=OFF;-G;Ninja;-DCMAKE_BUILD_TYPE=Release;-DCMAKE_INSTALL_PREFIX=/git/vircadia-builder/vcpkg/packages/detect_compiler_arm64-linux WORKING_DIRECTORY;/git/vircadia-builder/vcpkg/buildtrees/detect_compiler/arm64-linux-rel;RESULT_VARIABLE;error_code;OUTPUT_FILE;/git/vircadia-builder/vcpkg/buildtrees/detect_compiler/config-arm64-linux-rel-out.log;ERROR_FILE;/git/vircadia-builder/vcpkg/buildtrees/detect_compiler/config-arm64-linux-rel-err.log )
```
What actually gets run:
```
/git/vircadia-builder/cmake-3.21.2-linux-aarch64/bin/cmake /git/vircadia-builder/vcpkg/scripts/detect_compiler -DCMAKE_MAKE_PROGRAM=/usr/bin/ninja -DCMAKE_SYSTEM_NAME=Linux -DBUILD_SHARED_LIBS=OFF -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/git/vircadia-builder/vcpkg/scripts/toolchains/linux.cmake -DVCPKG_TARGET_TRIPLET=arm64-linux -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=external -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=/git/vircadia-builder/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_LINKER_FLAGS_RELEASE= -DVCPKG_LINKER_FLAGS_DEBUG= -DVCPKG_TARGET_ARCHITECTURE=arm64 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -D_VCPKG_ROOT_DIR=/git/vircadia-builder/vcpkg -D_VCPKG_INSTALLED_DIR=/git/vircadia-builder/vcpkg/installed -DVCPKG_MANIFEST_INSTALL=OFF -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/git/vircadia-builder/vcpkg/packages/detect_compiler_arm64-linux
```

**Comment by dg0yt** [comment]
> Note the plain ` ` in front of `WORKING_DIRECTORY` which should be a `;` if consistent.

I misinterpreted the output. Starting at `WORKING_DIRECTORY`, there are arguments to `execute_process`, not the command. So that ` ` is fine. Sorry for that noise.

Still, it seems like the use of `<SPACE>` and `<SEMICOLON>` isn't consistent:
`COMMAND <SPACE> <ACTUAL_COMMAND_AND_ARGUMENTS> <SPACE> WORKING_DIRECTORY <SEMICOLON> /git/vircadia-builder/vcpkg/buildtrees/detect_compiler/arm64-linux-rel <SEMICOLON> RESULT_VARIABLE <SEMICOLON> error_code <SEMICOLON> OUTPUT_FILE <SEMICOLON> /git/vircadia-builder/vcpkg/buildtrees/detect_compiler/config-arm64-linux-rel-out.log <SEMICOLON> ERROR_FILE <SEMICOLON> /git/vircadia-builder/vcpkg/buildtrees/detect_compiler/config-arm64-linux-rel-err.log`
i.e. `<SPACE>` is only used around the command and arguments, but not to separate the remaining arguments. I really don't know if it is of importance. CMake lists are odd, this might just be an output issue.

**Comment by JulianGro** [comment]
I found the issue.
I was using a "package" of vcpkg and all the times where vcpkg worked fine I didn't use a package.
While the package is just an archive of a normal vcpkg build, it was missing the `.vcpkg-root` file. Since the file was hidden, I never noticed that it was missing.
I will open a feature request for a fitting error message, since this did actually take me around 1 1/2 years to notice.
