### ISSUE TITLE
[SDL2] 2.0.16 android file breaks GitHub's CI cache

### ISSUE THREAD

**Issue by kcgen** [microsoft/vcpkg#20121]
**Describe the bug**

We use GitHub's workflow cache to save and restore our vcpkg installed content, which avoids roughly 40 minutes per run of our Windows CI workflow on the GitHub VMs. 

The recent SDL2 PR included an Android manifest file, which is giving GitHub's cache action troubles.  

We'll, it can archive it but can't restore it. This mean the entire cache fails and we're stuck waiting for entire builds from from scratch. 

```text
c:/vcpkg/buildtrees/sdl2/src/ase-2.0.16-5db7014de9.clean/android-project-ant/AndroidManifest.xml: Can't create '\\\\?\\c:\\vcpkg\\buildtrees\\sdl2\\src\\ase-2.0.16-5db7014de9.clean\\android-project-ant\\AndroidManifest.xml'
c:/vcpkg/buildtrees/sdl2/src/ase-2.0.16-5db7014de9.clean/android-project-ant/src: Can't create '\\\\?\\c:\\vcpkg\\buildtrees\\sdl2\\src\\ase-2.0.16-5db7014de9.clean\\android-project-ant\\src'
tar.exe: Error exit delayed from previous errors.
Warning: Tar failed with error: The process 'C:\Windows\System32\tar.exe' failed with exit code 1
```

**Environment**
GitHub CI machines.

**To Reproduce**
Attempt to use GitHub's cache to cache and restore the vcpkg subdirectory content. 

**Expected behavior**
Cache creation and restore should work without issue.

I suspect that manifest file (or it's parent directory) has some special permissions or characters that are hosing tar's restore process.

**Failure logs** 
See above.

Here's a failing workflow.  See the cache actions.

https://github.com/dosbox-staging/dosbox-staging/runs/3581471397?check_suite_focus=

**Comment by NancyLi1013** [comment]
@BillyONeal Could you please help take a look?

**Comment by kcgen** [comment]
(Above PR in the DOSBox Staging repo is simply a work-around that deletes the offending directory prior to GitHub cache-creation; sorry for the accidental-close!)

**Comment by BillyONeal** [comment]
> @BillyONeal Could you please help take a look?

I don't think there's much we can do about tar crashing on extraction. It seems a problem with upstream?

**Comment by kcgen** [comment]
There's something sufficiently problematic with:
 - `c:\\vcpkg\\buildtrees\\sdl2\\src\\ase-2.0.16-5db7014de9.clean\\android-project-ant`
 - `c:\\vcpkg\\buildtrees\\sdl2\\src\\ase-2.0.16-5db7014de9.clean\\android-project-ant\\src`

that `tar` can't even properly extract them.

Is there something different about these versus the other directories/files inside the SDL2 tree?

> It seems a problem with upstream?

Definitely agree.

`vcpkg` is the conduit that's laying those files down, so presumably has (some?) responsibility that it doesn't leave a mess behind.  Given the breakages between Linux/Unix file-system allowances versus NTFS and FAT32 - I would hope VCPKG has some tree filtering and sanity-checking functions that could be applied in cases like this? 

 ```python
FixBadPermissions("./src/ase-*/android-project-ant")
ScanForIllegalCharacters("./src/ase-*/android-project-ant")
...
```

The gold-plated solution is definitely upstream - but it would be nice for VCPKG to have some kind protections of it's own to handle these cases.

**Comment by BillyONeal** [comment]
> I would hope VCPKG has some tree filtering and sanity-checking functions that could be applied in cases like this?

For the most part, no. We just call `tar`.

**Comment by BillyONeal** [comment]
(To clarify, the problem is that we don't crack open the tar first or anything like that. We shell out to the real tar or cmake's embedded tar, so by the time we could do such checks it's already too late)

**Comment by kcgen** [comment]
After vcpkg is done building and integrating the package, GitHub's CI cache comes along and tar's up the entire vcpkg subdirectory.  

It's this tar'ing is where the broken content is ingested into GitHub's tarball.

In a subsequent CI run, GitHub's cache find the old tarball and attempts to extract it. It's during this exaction where it chokes on the hosed files/directories. 

This all happens downstream from vcpkg's use of the shelled out tar or cmake's tar (all of those steps have already passed any.. so even if you checked their return codes they would be fine).

So I think there's an opportunity post-build, for vcpkg to scan the resulting directory tree, and check it for broken permissions / illegal characters / un-readable files, etc -- and clean them up.   These can result from any step in the build process; it's just a form a house keeping at this point.

**Comment by BillyONeal** [comment]
Oh I see, this is on restoration of binary cache, not an invocation of tar directly or indirectly from a `porfile.cmake`?

**Comment by kcgen** [comment]
> Oh I see, this is on restoration of binary cache, not an invocation of tar directly or indirectly from a `porfile.cmake`?

Correct.

**Comment by ras0219** [comment]
>on restoration of binary cache

To clarify: this is an issue with https://github.com/actions/cache's tar and restore, not vcpkg's tar and restore.

From the original linked log:

> C:\Windows\System32\tar.exe -z -xf D:/a/_temp/1003ea5c-6b8b-4296-95d0-0d693802abad/cache.tgz -P -C D:/a/dosbox-staging/dosbox-staging
c:/vcpkg/buildtrees/sdl2/src/ase-2.0.16-5db7014de9.clean/android-project-ant/AndroidManifest.xml: Can't create '\\\\?\\c:\\vcpkg\\buildtrees\\sdl2\\src\\ase-2.0.16-5db7014de9.clean\\android-project-ant\\AndroidManifest.xml'
c:/vcpkg/buildtrees/sdl2/src/ase-2.0.16-5db7014de9.clean/android-project-ant/src: Can't create '\\\\?\\c:\\vcpkg\\buildtrees\\sdl2\\src\\ase-2.0.16-5db7014de9.clean\\android-project-ant\\src'
tar.exe: Error exit delayed from previous errors.

Additionally, I note that in your vcpkg step you're performing:

> rm -R c:\vcpkg
  mv c:\vcpkg-bak c:\vcpkg
  vcpkg install --triplet x64-windows libpng sdl2 sdl2-net libmt32emu opusfile fluidsynth gtest
  if (-not $?) { throw "vcpkg failed to install library dependencies" }
  rm -R c:\vcpkg\buildtrees\fluidsynth\src\*.clean\sf2

My primary suggestion would be to delete the entire `buildtrees` and `packages` folder at the end -- nothing in that folder should be needed after vcpkg finishes executing and it should dramatically reduce your cache size.

We also recommend looking at using manifest mode, which lets you track your dependencies in a file (including version support) instead of the "imperative" style of `vcpkg install`.

**Comment by kcgen** [comment]
Thanks for these suggestions @ras0219, we will put them to use.

Indeed, it's GitHub's cache that's choking on the files - and therefore GitHub's cache team should try to include detections for problematic broken files and directories, and work around them.

Just as another other recursive file archiving or processing tool should - as they might also have problems when recusing into these problematic directories (either on read or write).

None the less, regardless of how many tools choke on these subdirectories, vcpkg is the one that wrote them (even if the ultimate source is some untrusted upstream repo), therefore, vcpkg should bear some responsibility in managing the content when it goes off the rails (as is in this case).
