### ISSUE TITLE
vcpkg is downloading the incorrect version of a package

### ISSUE THREAD

**Issue by baylf2000** [microsoft/vcpkg#20141]
vcpkg is installing an old version of the "crow" package. According to vcpkg.io the current version is `crow |
Version: 0.3.2` however the vcpkg command keeps installing `0.1-1`. I've tried clearing the cache and download directories however this does not help.

- OS: Windows 10

1. ./vcpkg install crow

vcpkg should be installing version listed on vcpkg.io, however it is pulling a much older version from somewhere.

**Comment by autoantwort** [comment]
`git pull` in your vcpkg folder

**Comment by baylf2000** [comment]
Yes I can confirm this fixed the error.

**Comment by PhoebeHui** [comment]
Good to know.

```
PS E:\vcpkg\clean\vcpkg> ./vcpkg install crow:x64-windows
Computing installation plan...
The following packages will be built and installed:
    crow[core]:x64-windows -> 0.3.2#1
Detecting compiler hash for triplet x64-windows...
