### ISSUE TITLE
package liblzma:x86-windows build failure

### ISSUE THREAD

**Issue by georgezhu68** [microsoft/vcpkg#20143]
**Host Environment**
- OS: win10
- Compiler: vs2015
- 
**To Reproduce**
`./vcpkg install pcl`

**Failure logs** 
 Package: liblzma:x86-windows
 Vcpkg version: 2021-09-10-2059ef11aa6067e6f59b0d939c5d17e3c5c47d3e

CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:155 (message):
    Command failed: D:/CMake/bin/cmake.exe --build . --config Debug --target install -- -v -j3
    Working Directory: D:/vcpkg/vcpkg/buildtrees/liblzma/x86-windows-dbg
    See logs for more information:
      D:\vcpkg\vcpkg\buildtrees\liblzma\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:102 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
  ports/liblzma/portfile.cmake:19 (vcpkg_cmake_install)
  scripts/ports.cmake:140 (include)

 
**Additional context**
No

**Comment by autoantwort** [comment]
> D:\vcpkg\vcpkg\buildtrees\liblzma\install-x86-windows-dbg-out.log

Please provide the log :)

**Comment by georgezhu68** [comment]
Thanks & Best Regards
朱志辉（George Zhu）
手机：86-13699402221
***@***.***
地址：四川省成都市武侯区科华北路65号
         四川大学国际学术交流中心2422室 610065
 
From: autoantwort
Date: 2021-09-14 11:43
To: microsoft/vcpkg
CC: georgezhu68; Author
Subject: Re: [microsoft/vcpkg] package liblzma:x86-windows build failure (#20143)
D:\vcpkg\vcpkg\buildtrees\liblzma\install-x86-windows-dbg-out.log
Please provide the log :)
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by georgezhu68** [comment]
[install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/7167756/install-x86-windows-dbg-out.log)

**Comment by PhoebeHui** [comment]
@georgezhu68, could you install 'English language pack' and try again?

**Comment by georgezhu68** [comment]
I used  visual studio 2015 English version to build the package and be successful.
