### ISSUE TITLE
Error when creating a port that doesn't produce header files and leaves /include empty. Please make the post-build validation of vcpkg flexible and configurable.

### ISSUE THREAD

**Issue by McKillroy** [microsoft/vcpkg#20149]
**Is your feature request related to a problem? Please describe.**
I would like to be able to install a custom port from a custom registry that does not install header files, just like a tool (In this case a script based templating engine) that has no headers, because it is just a tool. Just adding it as a dependency and then using CMakes "find_package" to set its directory would be nice and simple.
I tried that, but unfortunately I get post build errors, because the tool does not have any headers in any /include folder.
I'm getting errors like this:
`-- Installing: C:/vcpkg/packages/mytool_x64-windows/share/mytool/usage`
`-- Installing: C:/vcpkg/packages/mytool_x64-windows/share/mytool/copyright`
`-- Performing post-build validation`
`The folder /include is empty or not present. This indicates the library was not correctly installed.`
`Found 1 error(s). Please correct the portfile:`
`    C:\my_registry\ports/mytool/0.0.1\portfile.cmake`
`-- Performing post-build validation done`

**Proposed solution**
I would like to get rid of this check, specifically for that port. I looked into the vcpkg source code and there are build policies where one of them checks for empty /include folders. I'd like to be able to disable it just for that port with a setting or entry in the portfile or the vcpkg.json. Probably a simple helper function or variable would do it so I could tweak my portfile and have this even depend on features if ever needed. Maybe it's already there and just not documented - no idea :) .

**Describe alternatives you've considered**
Alternatives would be to code some cmake into the CMakeLists.txt of the consuming project which uses the tool, or use git submodules. Using an environment variable to set sth. like MYTOOL_HOME would also work. However I'd prefer the mentioned vcpkg based solution. 

**Additional context**
None. Error text is mentioned above

**Comment by Neumann-A** [comment]
there is a `VCPKG_POLICY_` variable for that https://github.com/microsoft/vcpkg/blob/e201002b4f4827d7b7b672f0c5c672a77fc3b77d/scripts/build_info.cmake#L26

**Comment by McKillroy** [comment]
Thank you for answering !
Is there any documention how to set this variable?
a naive attempt to 
`SET(VCPKG_POLICY_EMPTY_INCLUDE_FOLDER ON)`
or 
`SET(VCPKG_POLICY_EMPTY_INCLUDE_FOLDER 1)`
utterly failed with 
`Unknown setting for policy 'PolicyEmptyIncludeFolder': 1` or ON respectively.

**Comment by JackBoosY** [comment]
This should be written in the mantainer docs.

**Comment by Thomas1664** [comment]
@MonicaLiu0311 I think this issue can be closed because all policies and how to use them is documented at https://learn.microsoft.com/en-us/vcpkg/reference/policies

**Comment by MonicaLiu0311** [comment]
Fixed by https://github.com/microsoft/vcpkg-docs/pull/319.
