### ISSUE TITLE
Missing library ！  OpenVDB | Eigen3 | CGAL | LAPACK

### ISSUE THREAD

**Issue by pengguanjun** [microsoft/vcpkg#20159]
Please create a discussion in https://github.com/microsoft/vcpkg/discussions/new instead.
1 I followed the document: 

https://gitee.com/zenustech/zeno/blob/master/docs/dev_win10.md#https://zhuanlan.zhihu.com/p/383683670

2 I want to install the following libraries: 

git clone https://github.com/microsoft/vcpkg.git --depth=1
cd vcpkg

@rem (Optional) integrate vcpkg into your VS2019 if necessary:
vcpkg integrate install

@rem (Optional) Install OpenVDB for the extension ZenVDB & FastFLIP:
vcpkg install openvdb:x64-windows

@rem (Optional) Install Eigen3 for the extension FastFLIP:
vcpkg install eigen3:x64-windows

@rem (Optional) Install CGAL for the extension CGMesh:
vcpkg install cgal:x64-windows

@rem (Optional) Install LAPACK for the extension CGMesh:
vcpkg install lapack:x64-windows

3 According to the online method, set vs2019 to the English locale.
After installing the following contents, the required libraries are no longer installed.
If you are free, please check it out, thanks! 
![image](https://user-images.githubusercontent.com/29192658/133309041-8042f768-cac1-4831-b8e1-bb6df86ae5cd.png)

```

c:\zeno\vcpkg>@rem (Optional) integrate vcpkg into your VS2019 if necessary:

c:\zeno\vcpkg>vcpkg integrate install
Applied user-wide integration for this vcpkg root.

All MSBuild C++ projects can now #include any installed libraries.
Linking will be handled automatically.
Installing new libraries will make them instantly available.

CMake projects should use: "-DCMAKE_TOOLCHAIN_FILE=C:/zeno/vcpkg/scripts/buildsystems/vcpkg.cmake"

c:\zeno\vcpkg>
c:\zeno\vcpkg>@rem (Optional) Install OpenVDB for the extension ZenVDB & FastFLIP:

c:\zeno\vcpkg>vcpkg install openvdb:x64-windows
Computing installation plan...
A suitable version of cmake was not found (required v3.21.0). Downloading portable cmake v3.21.0...
Downloading cmake...
  https://github.com/Kitware/CMake/releases/download/v3.21.1/cmake-3.21.1-windows-i386.zip -> C:\zeno\vcpkg\downloads\cmake-3.21.1-windows-i386.zip
Extracting cmake...
A suitable version of 7zip was not found (required v19.0.0). Downloading portable 7zip v19.0.0...
Downloading 7zip...
  https://www.7-zip.org/a/7z1900-x64.msi -> C:\zeno\vcpkg\downloads\7z1900-x64.msi
Extracting 7zip...

c:\zeno\vcpkg>
c:\zeno\vcpkg>@rem (Optional) Install Eigen3 for the extension FastFLIP:

c:\zeno\vcpkg>vcpkg install eigen3:x64-windows
Computing installation plan...
A suitable version of cmake was not found (required v3.21.0). Downloading portable cmake v3.21.0...
Extracting cmake...
A suitable version of 7zip was not found (required v19.0.0). Downloading portable 7zip v19.0.0...
Extracting 7zip...

c:\zeno\vcpkg>
c:\zeno\vcpkg>@rem (Optional) Install CGAL for the extension CGMesh:

c:\zeno\vcpkg>vcpkg install cgal:x64-windows
Computing installation plan...
A suitable version of cmake was not found (required v3.21.0). Downloading portable cmake v3.21.0...
Extracting cmake...
A suitable version of 7zip was not found (required v19.0.0). Downloading portable 7zip v19.0.0...
Extracting 7zip...

c:\zeno\vcpkg>
c:\zeno\vcpkg>@rem (Optional) Install LAPACK for the extension CGMesh:

c:\zeno\vcpkg>vcpkg install lapack:x64-windows
Computing installation plan...
A suitable version of cmake was not found (required v3.21.0). Downloading portable cmake v3.21.0...
Extracting cmake...
A suitable version of 7zip was not found (required v19.0.0). Downloading portable 7zip v19.0.0...
Extracting 7zip...

c:\zeno\vcpkg>
```

**Comment by NancyLi1013** [comment]
Hi @pengguanjun 

Thanks for posting this issue. 
Seems the process is not completed. Please wait for it to continue. 

Currently, it is still in progress of downloading tools. After finishing this process, it will install the ports that you need to install.

**Comment by pengguanjun** [comment]
> 
> 
> Hi @pengguanjun
> 
> Thanks for posting this issue.
> Seems the process is not completed. Please wait for it to continue.
> 
> Currently, it is still in progress of downloading tools. After finishing this process, it will install the ports that you need to install.

Thanks for the reply, it has been resolved, the latest vckpg.exe is not used, this stuff can only be used after compiling it by yourself.

**Comment by NancyLi1013** [comment]
Since you have solved this problem, I'm closing this issue for now.
