### ISSUE TITLE
aws-sdk-cpp build failure

### ISSUE THREAD

**Issue by xanather** [microsoft/vcpkg#20167]
AWS CPP SDK no longer builds since https://github.com/microsoft/vcpkg/commit/92af1ff59a651c1cf43aca48f54369a86d40d81c

**Host Environment**
- OS: Windows
- Compiler: MSVC 19.29.30038.1

**To Reproduce**
.\vcpkg.exe update
.\vcpkg.exe install aws-sdk-cpp[core,cloudformation,ec2,monitoring,ssm,s3,cloudfront,rds,cloudtrail,sns,lambda]:x64-windows

**Failure logs** 
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/7168805/config-x64-windows-out.log)

Seems that the AWS CRT C++ does not build, which is required for all aws sdk libraries.

CMake Error at CMakeLists.txt:87 (configure_file):
  configure_file attempted to configure a file:
  C:/Users/xanat/Documents/Files/Projects/system_monitor/third-party/vcpkg/buildtrees/aws-crt-cpp/src/c763da6810-ba58d2be12.clean/include/aws/crt/Config.h
  into a source directory.

**Additional context**
I appreciate the work Microsoft does with this beautiful tool which makes C++ dependency management more bearable but is there potentially a more 'stable' release branch system I can use to avoid this breaking my continuous integration? Should I be using the tags releases found here instead: https://github.com/microsoft/vcpkg/releases ?

Thanks

**Comment by PhoebeHui** [comment]
@xanather, thanks for reporting this issue! I have submitted a PR to fix it.
