### ISSUE TITLE
[libarchive] wrapper emits warnings and uses find_dependency

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#20182]
related issue about the warning:
https://gitlab.kitware.com/vtk/vtk/-/issues/18308

also the wrapper uses `find_dependency` instead of `find_package` which only works correctly in `*config.cmake`

**Comment by dg0yt** [comment]
> also the wrapper uses `find_dependency` instead of `find_package` which only works correctly in `*config.cmake`

I noticed when looking at #16845. I might pick this up for #20146. 

For lz4, I see you are already have the details in the vtk issue. An interesting puzzle indeed.
