### ISSUE TITLE
Package pcl:x86-windows build failure

### ISSUE THREAD

**Issue by georgezhu68** [microsoft/vcpkg#20193]
**Host Environment**
- OS: Windows 10
- Compiler: Visual Studio 2015

**To Reproduce**
`./vcpkg install pcl`

**Failure logs** 
Package: pcl:x86-windows
  Vcpkg version: 2021-09-10-2059ef11aa6067e6f59b0d939c5d17e3c5c47d3e
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:155 (message):
    Command failed: D:/CMake/bin/cmake.exe --build . --config Debug --target install -- -v -j3
    Working Directory: D:/vcpkg/vcpkg/buildtrees/pcl/x86-windows-dbg
    See logs for more information:
      D:\vcpkg\vcpkg\buildtrees\pcl\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:104 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:44 (vcpkg_build_cmake)
  ports/pcl/portfile.cmake:62 (vcpkg_install_cmake)
  scripts/ports.cmake:140 (include)

**Additional context**
No
[install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/7176256/install-x86-windows-dbg-out.log)

**Comment by JonLiu1993** [comment]
@georgezhu68 ,Could you try to use vistual studio2017 or 2019 whether it can be installed normally？

**Comment by JonLiu1993** [comment]
Closing this issue for no active thread for a long time. Please feel free to reopen this issue if it is still a problem for you.
