### ISSUE TITLE
vcpkg_copy_tools() doesn't support macOS .app bundles

### ISSUE THREAD

**Issue by wrobelda** [microsoft/vcpkg#20209]
**Describe the bug**
Some of the ports I work with generate a complete .app bundle for some of their tools on macOS. `vcpkg_copy_tools()` unfortunately fails to detect it and copy to a location.

**Environment**
- OS: macOS

**To Reproduce**
1. Checkout #20207 
2. `./vcpkg install libalkimia[tools]` on macOS

```
CMake Error at scripts/cmake/vcpkg_copy_tools.cmake:62 (message):
  Couldn't find tool "onlinequoteseditor5":

      "/Users/cromo/Documents/Sourcecode/vcpkg/packages/libalkimia_arm64-osx/bin/onlinequoteseditor5" does not exist
```

**Expected behavior**
Bundle directory should be treated as an executable and copied as if it was a regular ELF or Windows .exe.

**Comment by wrobelda** [comment]
Duplicate of #15164

**Comment by JackBoosY** [comment]
Please track #15164.
