### ISSUE TITLE
Header search path is not set when installing static triplets

### ISSUE THREAD

**Issue by olilarkin** [microsoft/vcpkg#2021]
If I only install the openssl:x64-windows-static port, I cannot  #include <openssl/sha.h> in a new commandline project. 

the header search path is not set. If I also  install the openssl:x64-windows version, it is. This is true for all ports as far as i can tell

**Comment by olilarkin** [comment]
if you have both static and dll versions installed, how do you specify what get's linked?

**Comment by twMr7** [comment]
The following docs shall help:
[Triplet Files](https://github.com/Microsoft/vcpkg/blob/master/docs/users/triplets.md)
[Triplet Selection in MSBuild](https://github.com/Microsoft/vcpkg/blob/master/docs/users/integration.md#triplet-selection)

**Comment by JackBoosY** [comment]
Hi @olilarkin , as @twMr7 said, have you solved this problem?

**Comment by olilarkin** [comment]
this was an awful long time ago and i can't remember even what it was for. closing
