### ISSUE TITLE
Armadillo dependency locations not correctly specified

### ISSUE THREAD

**Issue by kjohnsen** [microsoft/vcpkg#20215]
**Describe the bug**
When I try to build my project (ldsCtrlEst) using this branch of vcpkg, I get the following error:
ninja: error: '../vcpkg/packages/armadillo_x64-windows/lib/openblas.lib', needed by 'ldsCtrlEst.lib', missing and no known rule to make it

I copied and pasted openblas.lib in there, and when building again the same thing happened, but looking for lapack.lib as well in the armadillo folder

**Environment**
- OS: Windows 10
- Compiler: Clang 11.0.0 (MSVC CLI)

**To Reproduce**
1. ./vcpkg install armadillo:x64-windows
2. Create cmake project. In CMakeLists.txt use `find_package(Armadillo CONFIG REQUIRED)
3. `add_library(...)`, `target_link_libraries(demo PUBLIC ${ARMADILLO_LIBRARIES})`
4. build a project with cmake, `cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=[path to vcpkg]/scripts/buildsystems/vcpkg.cmake`

**Expected behavior**
The build should work, find needed libraries

**Failure logs** 
```
[main] Building folder: pybind-arma-bug 
[build] Starting build
[proc] Executing command: C:\Users\johns\scoop\shims\cmake.EXE --build [project location]/build --config RelWithDebInfo --target all -v -j 18 --
[build] ninja: error: '[vcpkg location]/packages/armadillo_x64-windows/lib/openblas.lib', needed by 'dummy.lib', missing and no known rule to make it
[build] Build finished with exit code 1
```

**Additional context**

**Comment by kjohnsen** [comment]
I worked around this by creating symbolic links in the `packages/armadillo_x64-windows/lib` to the installed location of `installed/x64-windows/lib`

**Comment by JackBoosY** [comment]
Close this issue via #20439 merged.
