### ISSUE TITLE
[libdatachannel] BUG: Don't find rtc/rtc.hpp file

### ISSUE THREAD

**Issue by KangLin** [microsoft/vcpkg#20223]
**Host Environment**
- OS: Windows 10
- Compiler: cl 19.16.27045
- qt: 5.12.11

Don't find rtc/rtc.hpp file.
I look cmake configure file. There are not include directory.

**Comment by JackBoosY** [comment]
Confirmed, the include path wasn't exported to the config file.

**Comment by JackBoosY** [comment]
This is a upstream issue and was fixed by https://github.com/paullouisageneau/libdatachannel/pull/446 28 days ago.
