### ISSUE TITLE
Boost tries to link to v140 libraries despite v141 when it's build with VS2017

### ISSUE THREAD

**Issue by jasjuang** [Microsoft/vcpkg#2023]
I am on Windows 10, VS 2017. I installed boost through `vcpkg install boost`

In my minimal downstream CMakeLists.txt

``````
cmake_minimum_required(VERSION 3.5)

project(Example)

find_package( Boost COMPONENTS system REQUIRED )

set(PROJECT_SRCS ${PROJECT_SOURCE_DIR}/main.cpp)

add_executable(${PROJECT_NAME} ${PROJECT_SRCS})

target_link_libraries(${PROJECT_NAME} Boost::system)
``````

main.cpp can be anything, after cmake configuration and I go into the solution file, it shows that Example is linking to `C:\vcpkg\installed\x64-windows-dev\lib\boost_system-vc140-mt-1_65_1.lib` whereas my actual boost system library is at `C:\vcpkg\installed\x64-windows-dev\lib\boost_system-vc141-mt-1_65_1.lib` . Is there a hard coding of `v140` somewhere in the boost portfile that is causing this error? Or is it the FindBoost.cmake that comes with cmake causing the error?

**Comment by KindDragon** [comment]
It should `vc140` even for VS2017 https://github.com/Microsoft/vcpkg/blob/master/ports/boost/portfile.cmake#L276-L294

**Comment by jasjuang** [comment]
@KindDragon My boost libraries are with vc141. Is yours vc140?

**Comment by jasjuang** [comment]
@KindDragon Actually you are right. I reinstalled boost and the problem went away. Sorry for the noise.
