### ISSUE TITLE
Gdal cannot open netcdf format while netcdf-c is defined as a dependency

### ISSUE THREAD

**Issue by IfremerUnderwater** [microsoft/vcpkg#20231]
Hello,
I have updated to the last ports on windows x64 and still have an issue with gdal library for opening netcdf format. Netcdf seems to be included as a dependency but maybe compilation option is not activated as it is impossible to open netcdf format using the library. It is working with the same file using linux standard gdal installation so it seems to be related to a missing compilation flag.

**Comment by dg0yt** [comment]
In vcpkg, gdal uses an entirely different build system for Linux (and Mingw) than for Windows. AFAICT, netcdf is not used in the Windows variant : all needed Windows libraries are hard-coded in the portfile.

**Comment by IfremerUnderwater** [comment]
Thank you for your message. I would have like to add netcdf support but I'm not very familiar with nmake, do you think of a documentation that could help me to modify the port ?

**Comment by longhuan2018** [comment]
Under windows, if you want GDAL to support NetCDF, you need vcpkg install netcdf-c before vcpkg install GDAL. Only GDAL dynamic library compilation is supported.
You can check the dependency_win.cmake file in GDAL port.
If you need GDAL to support more formats under windows, you can modify the file.
```
# Setup netcdf libraries
  if(VCPKG_LIBRARY_LINKAGE STREQUAL "dynamic")
      if(EXISTS "${CURRENT_INSTALLED_DIR}/lib/netcdf.lib")
          file(TO_NATIVE_PATH "${CURRENT_INSTALLED_DIR}/include" NETCDF_INCLUDE)
          file(TO_NATIVE_PATH "${CURRENT_INSTALLED_DIR}/lib/netcdf.lib" NETCDF_LIBRARY_REL)
          file(TO_NATIVE_PATH "${CURRENT_INSTALLED_DIR}/debug/lib/netcdf.lib" NETCDF_LIBRARY_DBG)
          list(APPEND NMAKE_OPTIONS NETCDF_PLUGIN=NO)
          list(APPEND NMAKE_OPTIONS NETCDF_SETTING=yes)
          list(APPEND NMAKE_OPTIONS NETCDF_INC_DIR=${NETCDF_INCLUDE})
          list(APPEND NMAKE_OPTIONS_REL NETCDF_LIB=${NETCDF_LIBRARY_REL})
          list(APPEND NMAKE_OPTIONS_DBG NETCDF_LIB=${NETCDF_LIBRARY_DBG})
      endif()
  endif()
```

**Comment by dg0yt** [comment]
> Only GDAL dynamic library compilation is supported.

I guess this limitation is mentioned because the proposal doesn't handle netcdf's transitive usage requirements?

**Comment by longhuan2018** [comment]
It is not easy to determine all static library dependencies of NetCDF here, so the static library mode is excluded for the time being

**Comment by dg0yt** [comment]
> It is not easy to determine all static library dependencies of NetCDF here, so the static library mode is excluded for the time being

So it is all about handling transitive usage requirements with nmake. 
I raised the underlying problem in a few other spots, as I would prefer to see a sound solution instead of jumping from one limitation to another. netcdf already provides transitive usage requirements via cmake and pkgconfig. This could be leveraged in some way. (Most likely pkgconfig, but it needs some extra transformations.) When I start with that, I can verify the build via CI, but someone else has to build and test locally.

**Comment by IfremerUnderwater** [comment]
> Under windows, if you want GDAL to support NetCDF, you need vcpkg install netcdf-c before vcpkg install GDAL. Only GDAL dynamic library compilation is supported. You can check the dependency_win.cmake file in GDAL port. If you need GDAL to support more formats under windows, you can modify the file.
> 
> ```
> # Setup netcdf libraries
>   if(VCPKG_LIBRARY_LINKAGE STREQUAL "dynamic")
>       if(EXISTS "${CURRENT_INSTALLED_DIR}/lib/netcdf.lib")
>           file(TO_NATIVE_PATH "${CURRENT_INSTALLED_DIR}/include" NETCDF_INCLUDE)
>           file(TO_NATIVE_PATH "${CURRENT_INSTALLED_DIR}/lib/netcdf.lib" NETCDF_LIBRARY_REL)
>           file(TO_NATIVE_PATH "${CURRENT_INSTALLED_DIR}/debug/lib/netcdf.lib" NETCDF_LIBRARY_DBG)
>           list(APPEND NMAKE_OPTIONS NETCDF_PLUGIN=NO)
>           list(APPEND NMAKE_OPTIONS NETCDF_SETTING=yes)
>           list(APPEND NMAKE_OPTIONS NETCDF_INC_DIR=${NETCDF_INCLUDE})
>           list(APPEND NMAKE_OPTIONS_REL NETCDF_LIB=${NETCDF_LIBRARY_REL})
>           list(APPEND NMAKE_OPTIONS_DBG NETCDF_LIB=${NETCDF_LIBRARY_DBG})
>       endif()
>   endif()
> ```

Hi,
thank you for your help. I'm already building lib dynamically and have netcdf installed before. If I try opening with gdalinfo I've got  C:\vcpkg\installed\x64-windows\tools\gdal\gdalinfo.exe C:\Users\aarnaube\Desktop\BathyRenavClaire_PL394_1m_interp2.grd
ERROR 4: `C:\Users\aarnaube\Desktop\BathyRenavClaire_PL394_1m_interp2.grd' not recognized as a supported file format.
gdalinfo failed - unable to open 'C:\Users\aarnaube\Desktop\BathyRenavClaire_PL394_1m_interp2.grd'. I could provide an example file if anybody has the time to test on its side.
Thank you,
Best

**Comment by longhuan2018** [comment]
Can you provide a sample data for me to debug? @ @IfremerUnderwater

**Comment by IfremerUnderwater** [comment]
> Can you provide a sample data for me to debug? @ @IfremerUnderwater

Here is a file that works on linux -> https://filesender.renater.fr/?s=download&token=05631b6c-763a-4cb8-a9d0-e111238490b1
Thank you very much for your help @longhuan2018 .

**Comment by NancyLi1013** [comment]
@IfremerUnderwater 

Have you tried if this is still a problem for you?

**Comment by IfremerUnderwater** [comment]
Really sorry for the delay in my answer I was in long mission and couldn't test. With this mod it works perfectly, thank you very much for your help @NancyLi1013
