### ISSUE TITLE
[qt] Add ccache support

### ISSUE THREAD

**Issue by wrobelda** [microsoft/vcpkg#20232]
****

**Is your feature request related to a problem? Please describe.**
I have ccache enabled via the typical PATH symlinks substitution. However, Qt somehow ignores that and executes the compiler directly from `/Library/Developer/CommandLineTools/usr/bin/clang`, with ccache showing in configure summary as:
```
Using ccache ........................... no
```

I can enable it by hand by adding `--ccache` to `CORE_OPTIONS` in `qt5-base/portfile.cmake`, but that's obviously a dirty workaround. 

**Proposed solution**
Possibly detect if `g++`/`clang` in PATH is symlinked to `ccache` and add `--cache` to the list of options, respecting developer's choices.

**Comment by JackBoosY** [comment]
cc @Neumann-A

**Comment by dg0yt** [comment]
How about passing the compiler detected by cmake?

**Comment by Neumann-A** [comment]
> How about passing the compiler detected by cmake?

needs to be done. Currently Qt5/qmake does not even pass custom compiler flags. 

> cc @Neumann-A

I am not usign CC so somebody you wants and uses the feature should add it.

**Comment by dg0yt** [comment]
> needs to be done. Currently Qt5/qmake does not even pass custom compiler flags.

I'm just playing with that for mingw. (It basically works, only that it stumbles over broken port icu in the middle of build.)
ENV{CC} etc. for the host compiler.
QMAKE_CC configure parameter for the target compiler.

**Comment by wrobelda** [comment]
Some ports (`harfbuzz`) failed with "Unrecognized compiler: ccache" if I set ccache via env variable. Had to do a "stealth" PATH substitution via symlinks.
