### ISSUE TITLE
[libusb-1.0.25#5] libusb is a C library that provides generic access to USB devices. 

### ISSUE THREAD

**Issue by MrAviator93** [microsoft/vcpkg#20247]
****

I would like to request to create a pkg-config for this library so pkg_check_modules could be used, currently, it doesn't exist.

If a default libusb-1.0 library from Ubuntu package manager is used, it's impossible to use  find_package(libusb CONFIG REQUIRED), instead, it would be way preferable to use pkg_check_modules( libusb REQUIRED libusb-1.0 ).

**Comment by LilyWangLL** [comment]
This issue has been solved, please install `libusb` on the latest vcpkg.
```
Elapsed time to handle libusb:x64-linux: 15 s
libusb:x64-linux package ABI: fa275f543d9cba59400cc155b6eb593edbffcf3c5f6cf3055701880a751e0063
Total install time: 15 s
libusb can be imported via CMake FindPkgConfig module:
    find_package(PkgConfig REQUIRED)
    pkg_check_modules(libusb REQUIRED IMPORTED_TARGET libusb-1.0)

    target_link_libraries(main PRIVATE PkgConfig::libusb)

user@user002:/mnt/lily/vcpkg$ ./vcpkg --version
vcpkg package management program version 2023-12-12-1c9ec1978a6b0c2b39c9e9554a96e3e275f7556e
```
