### ISSUE TITLE
[qt] split out Qt Linguist as a feature of qt-tools

### ISSUE THREAD

**Issue by wrobelda** [microsoft/vcpkg#20244]
**Is your feature request related to a problem? Please describe.**
Almost all KDE ports depend on Qt Linguist for their internationalization purposes. However, `Qt Linguist` is included in `qt-tools` bundle, which is a heavy dependency. Qt6 port already split out some of the tools as separate features, but Qt Linguist  is not one of them.

This was previously discussed with @Neumann-A, so I opened this issue to track progress.

**Proposed solution**
Split out `Qt Linguist` as a separate feature, so that the KDE ports can explicitly depend on it and it only.

**Comment by Neumann-A** [comment]
Linguist depends on Assistant for some reason so you wont get a lot of improvement unless upstream changes that. (See Qt 6.2 pr)

**Comment by dg0yt** [comment]
Doesn't KDE use gettext? Or do you refer to Qt Linguist as one possible frontend for editing KDE translation files?

**Comment by wrobelda** [comment]
@dg0yt implicitly by using `ki18n` framework, but some of the frameworks use Qt translation instead.

**Comment by wrobelda** [comment]
I was told that the dependency is due to:

"`qt5_create_translation()` which depends on lupdate. That is a tool which your distro may package with linguist, but there is actual dependency on the linguist application."

So, if it makes things easier, maybe the `lupdate` and `lrelease` could be singled out, or actually included with qt5-base?

**Comment by dg0yt** [comment]
In my current superbuild (not vcpkg), the linguist solution is app.:
~~~cmake
"${CMAKE_COMMAND}" -E make_directory src/linguist
"${CMAKE_COMMAND}" -E chdir src/linguist "@qmake@" "${SOURCE_DIR}/src/linguist"
"$(MAKE)" -C src/linguist
"$(MAKE)" -C src/linguist install INSTALL_ROOT=${DESTDIR}
 ~~~

**Comment by wrobelda** [comment]
@dg0yt right, but we actually depend on `lupdate` (and possibly `lrelease`) only

**Comment by JackBoosY** [comment]
Marked this issue as `port-feature` temporary.

**Comment by wrobelda** [comment]
> @dg0yt right, but we actually depend on `lupdate` (and possibly `lrelease`) only

Correcting myself here: the fact we depend on those binaries only is in fact irrelevant, we look them up with:
```
 find_package(Qt5LinguistTools CONFIG REQUIRED)

    if(TARGET Qt5::lconvert)
        set(lconvert_executable Qt5::lconvert)
    else()
``

, so still depend on Qt5LinguistTools.

**Comment by XapaJIaMnu** [comment]
Is QT Linguist part of the qttools port? It's not detected for me from a 3rd party cmake project:
```
-- Could NOT find Qt6LinguistTools (missing: Qt6LinguistTools_DIR)
```
A bit reminiscent of: https://github.com/microsoft/vcpkg/issues/2834
At any rate, i'd also be interested in a qt linguist only package.

**Comment by Neumann-A** [comment]
> Is QT Linguist part of the qttools port? 

Yes it is

>  It's not detected for me from a 3rd party cmake project:

probably doing something wrong or somebody is manipulating `CMAKE_PREFIX_PATH`

```
[cmake] -- The following REQUIRED packages have been found:
<snip>
[cmake]  * Qt6LinguistTools
```

> At any rate, i'd also be interested in a qt linguist only package.

That will not happen unless upstream changes qttools and extracts that as a standalone module.

**Comment by XapaJIaMnu** [comment]
@Neumann-A  thanks for the explanation. I used github workflow with vcpkg 50fd3d995. My package built successfully when using qt5-base and qt5-tools as opposed to when using the qt6 counterparts where some of the QT components could not be found. I will try to experiment outside of a VM when I get the chance and file issues if necessary.
