### ISSUE TITLE
[GDAL] BUILD_FAILED during libiconv installation when attempting to install GDAL (for pydggrid)

### ISSUE THREAD

**Issue by AMDaniel** [microsoft/vcpkg#20245]
I am attempting to install GDAL (https://gdal.org/; https://github.com/OSGeo/gdal) as it is a prerequisite for the package pydggrid (https://github.com/am2222/pydggrid). 

**Machine Setup**
Windows 10, x64

**Steps to Reproduce Error**
I followed the instructions on the pydggrid page (https://github.com/am2222/pydggrid) to install vcpkg, and then attempted to use vcpkg to install GDAL (all commands executed from an Anaconda 3 PowerShell prompt):
`PS> git clone https://github.com/Microsoft/vcpkg.git`
`PS> cd vcpkg`
`PS> .\bootstrap-vcpkg.bat`
`PS> .\vcpkg integrate install`
`PS> .\vcpkg install gdal:x64-windows`

**Error**
The `install gdal` command downloads and installs 20 packages without issue before attempting to install the "libiconv" package:

> ...
Starting package 19/26: libpq:x64-windows
Installing package libpq[core,openssl,zlib]:x64-windows...
Elapsed time for package libpq:x64-windows: 2.894 s
Starting package 20/26: libwebp:x64-windows
Installing package libwebp[core,nearlossless,simd,unicode]:x64-windows...
Elapsed time for package libwebp:x64-windows: 231.5 ms
Starting package 21/26: libiconv:x64-windows
Building package libiconv[core]:x64-windows...

Unlike the previous packages, this generates a substantial amount of output in the prompt (can be provided upon request). After some time, the following error appears:

>-- Downloading http://download.osgeo.org/gdal/3.2.2/gdal322.zip -> gdal322.zip...
-- Extracting source C:/Users/User/Documents/Python/vcpkg/downloads/gdal322.zip
-- Applying patch 0001-Fix-debug-crt-flags.patch
-- Applying patch 0002-Fix-build.patch
-- Applying patch 0004-Fix-cfitsio.patch
-- Applying patch 0005-Fix-configure.patch
-- Applying patch 0007-Control-tools.patch
-- Applying patch 0006-Fix-mingw-dllexport.patch
-- Using source at C:/Users/User/Documents/Python/vcpkg/buildtrees/gdal/src/gdal322-e10db1d6e9.clean
-- Building and installing x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:155 (message):
    Command failed: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/nmake.exe" /NOLOGO /G /U -f makefile.vc devinstall install INSTALLDIR=C:/Users/User/Documents/Python/vcpkg/packages/gdal_x64-windows/debug DATADIR=C:/Users/User/Documents/Python/vcpkg/packages/gdal_x64-windows/share/gdal HTMLDIR=C:/Users/User/Documents/Python/vcpkg/packages/gdal_x64-windows/share/gdal/html GEOS_DIR=C:/Users/User/Documents/Python/vcpkg/installed/x64-windows/include "GEOS_CFLAGS=-IC:/Users/User/Documents/Python/vcpkg/installed/x64-windows/include -DHAVE_GEOS" PROJ_INCLUDE=-IC:/Users/User/Documents/Python/vcpkg/installed/x64-windows/include EXPAT_DIR=C:/Users/User/Documents/Python/vcpkg/installed/x64-windows/include EXPAT_INCLUDE=-IC:/Users/User/Documents/Python/vcpkg/installed/x64-windows/include CURL_INC=-IC:/Users/User/Documents/Python/vcpkg/installed/x64-windows/include "SQLITE_INC=-IC:/Users/User/Documents/Python/vcpkg/installed/x64-windows/include " PG_INC_DIR=C:/Users/User/Documents/Python/vcpkg/installed/x64-windows/include OPENJPEG_ENABLED=YES OPENJPEG_CFLAGS=-IC:/Users/User/Documents/Python/vcpkg/installed/x64-windows/include OPENJPEG_VERSION=20100 WEBP_ENABLED=YES WEBP_CFLAGS=-IC:/Users/User/Documents/Python/vcpkg/installed/x64-windows/include LIBXML2_INC=-IC:/Users/User/Documents/Python/vcpkg/installed/x64-windows/include PNG_EXTERNAL_LIB=1 PNGDIR=C:/Users/User/Documents/Python/vcpkg/installed/x64-windows/include ZLIB_INC=-IC:/Users/User/Documents/Python/vcpkg/installed/x64-windows/include ZLIB_EXTERNAL_LIB=1 ACCEPT_USE_OF_DEPRECATED_PROJ_API_H=1 MSVC_VER=1900 WIN64=YES WITH_PDB=1 DLLBUILD=1 GDAL_HOME=C:/Users/User/Documents/Python/vcpkg/packages/gdal_x64-windows/debug CXX_CRT_FLAGS=/MDd PROJ_LIBRARY=C:/Users/User/Documents/Python/vcpkg/installed/x64-windows/debug/lib/proj_d.lib PNG_LIB=C:/Users/User/Documents/Python/vcpkg/installed/x64-windows/debug/lib/libpng16d.lib "GEOS_LIB=C:/Users/User/Documents/Python/vcpkg/installed/x64-windows/debug/lib/geos_cd.lib C:/Users/User/Documents/Python/vcpkg/installed/x64-windows/debug/lib/geosd.lib" EXPAT_LIB=C:/Users/User/Documents/Python/vcpkg/installed/x64-windows/debug/lib/libexpatd.lib "CURL_LIB=C:/Users/User/Documents/Python/vcpkg/installed/x64-windows/debug/lib/libcurl-d.lib wsock32.lib wldap32.lib winmm.lib" "SQLITE_LIB=C:/Users/User/Documents/Python/vcpkg/installed/x64-windows/debug/lib/sqlite3.lib " OPENJPEG_LIB=C:/Users/User/Documents/Python/vcpkg/installed/x64-windows/debug/lib/openjp2.lib WEBP_LIBS=C:/Users/User/Documents/Python/vcpkg/installed/x64-windows/debug/lib/webpd.lib "LIBXML2_LIB=C:/Users/User/Documents/Python/vcpkg/installed/x64-windows/debug/lib/libxml2.lib C:/Users/User/Documents/Python/vcpkg/installed/x64-windows/debug/lib/iconv.lib C:/Users/User/Documents/Python/vcpkg/installed/x64-windows/debug/lib/charset.lib C:/Users/User/Documents/Python/vcpkg/installed/x64-windows/debug/lib/lzmad.lib" ZLIB_LIB=C:/Users/User/Documents/Python/vcpkg/installed/x64-windows/debug/lib/zlibd.lib "PG_LIB=C:/Users/User/Documents/Python/vcpkg/installed/x64-windows/debug/lib/libpq.lib C:/Users/User/Documents/Python/vcpkg/installed/x64-windows/debug/lib/libpgcommon.lib C:/Users/User/Documents/Python/vcpkg/installed/x64-windows/debug/lib/libpgport.lib Secur32.lib Shell32.lib Advapi32.lib Crypt32.lib Gdi32.lib C:/Users/User/Documents/Python/vcpkg/installed/x64-windows/debug/lib/libcrypto.lib C:/Users/User/Documents/Python/vcpkg/installed/x64-windows/debug/lib/libssl.lib" DEBUG=1 BUILD_TOOLS=0
    Working Directory: C:/Users/User/Documents/Python/vcpkg/buildtrees/gdal/x64-windows-dbg
    See logs for more information:
      C:\Users\User\Documents\Python\vcpkg\buildtrees\gdal\build-x64-windows-dbg-out.log
      C:\Users\User\Documents\Python\vcpkg\buildtrees\gdal\build-x64-windows-dbg-err.log
>
>Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_nmake.cmake:221 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_nmake.cmake:89 (vcpkg_build_nmake)
  ports/gdal/portfile.cmake:136 (vcpkg_install_nmake)
  scripts/ports.cmake:140 (include)
>
>
>Error: Building package gdal:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: gdal:x64-windows
  Vcpkg version: 2021-09-10-2059ef11aa6067e6f59b0d939c5d17e3c5c47d3e
>
>Additionally, attach any relevant sections from the log files above. 

Using `.\vcpkg update` and `git pull` indicate no portfiles need updating.

The two aforementioned log files are:
[build-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/7190599/build-x64-windows-dbg-err.log)
[build-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/7190600/build-x64-windows-dbg-out.log)

Any help in resolving this problem would be greatly appreciated!

**Comment by dg0yt** [comment]
See the end of the log file:
~~~
pdfdataset.cpp(7240): fatal error C1088: Cannot flush compiler intermediate file: 'C:\Users\User\AppData\Local\Temp\_CL_a7f8a8ebdb': No space left on device
~~~

Note that you really need many GB of free space in order to build GDAL. vcpkg adds to it because:
- it builds debug AND release variants, and
- it not just creates the target install tree (public), but also another packages tree (implementation detail).

**Comment by AMDaniel** [comment]
Thank you for the follow-up! I attempted again with 60.1 GB of free space on disk and the installation was successful (leaving 48.9 GB free after installation). (If other pydggrid/GDAL users/installers are reading this, the remaining space was sufficient to install the shapelib package using vcpkg as well).

Thanks again!
