### ISSUE TITLE
[freetype] freetype 2.11.0 dll produces crash when built with some MSVC compilers

### ISSUE THREAD

**Issue by itszn** [microsoft/vcpkg#20246]
**Host Environment**
- OS: Windows
- Compiler: Visual Studio 16 2019 (MSVC 19.29.30037.0) also github actions `windows-latest` build image

**To Reproduce**
Do this in a visual studio cmd
```
git clone https://github.com/microsoft/vcpkg.git
cd vcpkg
.\bootstrap-vcpkg.bat
.\vcpkg.exe install freetype:x64-windows
cd ..
git clone https://github.com/itszn/typetest.git
cd typetest
mkdir build
cd build
cmake -G "Visual Studio 16 2019" -DCMAKE_TOOLCHAIN_FILE=..\..\vcpkg\scripts\buildsystems\vcpkg.cmake -DCMAKE_BUILD_TYPE=Debug ..
msbuild typetest.sln
.\Debug\typetest.exe
```
Expected output is `Survived FT_Load_Glyph`

# Bug
Freetype 2.11.0 built with vcpkg will compile with an empty `af_writing_system_classes`. This causes a null pointer dereference when trying to create glyphs with autofit.

freetype uses an [include file](https://gitlab.freedesktop.org/freetype/freetype/-/blob/801cd842e27c85cb1d5000f6397f382ffe295daa/src/autofit/afwrtsys.h) with macros to initialize `af_writing_system_classes`. However when building with vcpkg, this fails to correctly populate leading to the crash.

The following patch to freetype seems to fix the issue:

```patch
diff --git a/src/autofit/afwrtsys.h b/src/autofit/afwrtsys.h
index 39aa121..81e6108 100644
--- a/src/autofit/afwrtsys.h
+++ b/src/autofit/afwrtsys.h
@@ -27,6 +27,8 @@
 #include "afcjk.h"
 #include "afindic.h"
 
+#else
+
 #endif /* AFWRTSYS_H_ */
```

The patch adds an `#else` statement to the header before the `#endif`. This theoretically should be a no-op, but vcpkg produces different objects:

Without patch:
![image](https://user-images.githubusercontent.com/1857794/133907266-64120616-3662-41ba-ba14-5de645f1768d.png)

With patch:
![image](https://user-images.githubusercontent.com/1857794/133907377-d50c5b76-bd45-4a66-8a6f-0a0e8a49cc7d.png)

**Comment by itszn** [comment]
Something else to note: Up stream freetype has [split the `afwrtsys.h` file](https://gitlab.freedesktop.org/freetype/freetype/-/commit/5bcaf51b611ce579c89c2bb423984ec89fdaadd7). This might actually resolve this issue. However they have not tagged it for release yet.

**Comment by JackBoosY** [comment]
Thanks for reporting this issue! I will take a look later.

**Comment by Masaiki** [comment]
I met the same problem, would you make a PR to add this patch before next release, @itszn ?
and also for a remind, @JackBoosY .

**Comment by JackBoosY** [comment]
@Sibras When will the upstream cmake build system be synchronized with other build systems?

**Comment by Sibras** [comment]
> 
> 
> @Sibras When will the upstream cmake build system be synchronized with other build systems?

Im probably the wrong person to ask about this as I dont know. But to quote freetype themselves:

> Meson
> Right now, support for Meson is experimental and available for the library only, without the demo programs. It is planned to fix this eventually, making Meson a first-class build system.
> 
> CMake
> FreeType can also be built with CMake. Note, however, that this is contributed code not officially supported.

**Comment by JackBoosY** [comment]
@Sibras Oh sorry, I thought you are the freetype member.

**Comment by JackBoosY** [comment]
I wish to fix this issue in https://github.com/microsoft/vcpkg/pull/21508, but since freetype is a base dependency port, this may take a few days.

**Comment by Neumann-A** [comment]
@Cheney-W Freetype is now at 2.12.1 so it is unlikely the problem still exists?
