### ISSUE TITLE
[gmp] DLLs not copied to /bin folder on Windows

### ISSUE THREAD

**Issue by wrobelda** [microsoft/vcpkg#20267]
**Describe the bug**
My project uses gmp and I can successfully build it using vcpkg. However, the `gmp.dll` is not being copied to the build folder alongside the `.exe`, so it fails to start. Works fine after manually copying the file. 

The Windows build uses msbuild project, which I am not familiar with when it comes to MSVC, so can't fix it myself.  

**Environment**
- OS: Windows
- Compiler: MSVC 2019 (current stable build)

**To Reproduce**
1. Reference gmp in a project
2. build in VS 2019 using vcpkg toolchain
3. run the .exe

**Expected behavior**
The app should execute without issues, with app necessary dependencies copied to bin folder.

**Comment by wrobelda** [comment]
cc @hellozee

**Comment by dg0yt** [comment]
To be clear, you are refering to app-local deployment into your user project build directory?
And inspecting your exe reports the gmp.dll/gmpd.dll dependency?

**Comment by hellozee** [comment]
In my experience, msbuild automatically copies all the required dlls beside the executable except the gmp dll, for some reason it skips it while including others.

**Comment by JackBoosY** [comment]
Missing `vcpkg_copy_tools`.

**Comment by dg0yt** [comment]
> Missing `vcpkg_copy_tools`.

This was asked before: This issue is *not* about build a port. This issues is about consuming port gmp DLLs.
