### ISSUE TITLE
[gdal:x64-windows] build failure

### ISSUE THREAD

**Issue by calysteau** [microsoft/vcpkg#20274]
**Host Environment**
- OS: Windows 11
- Compiler: 14.29.30133

**To Reproduce**
`./vcpkg install gdal:x64-windows`

**Failure logs** 
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:155 (message):
    Command failed: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/nmake.exe" /NOLOGO /G /U -f makefile.vc devinstall install INSTALLDIR=C:/workspace/vcpkg/packages/gdal_x64-windows/debug DATADIR=C:/workspace/vcpkg/packages/gdal_x64-windows/share/gdal HTMLDIR=C:/workspace/vcpkg/packages/gdal_x64-windows/share/gdal/html GEOS_DIR=C:/workspace/vcpkg/installed/x64-windows/include "GEOS_CFLAGS=-IC:/workspace/vcpkg/installed/x64-windows/include -DHAVE_GEOS" PROJ_INCLUDE=-IC:/workspace/vcpkg/installed/x64-windows/include EXPAT_DIR=C:/workspace/vcpkg/installed/x64-windows/include EXPAT_INCLUDE=-IC:/workspace/vcpkg/installed/x64-windows/include CURL_INC=-IC:/workspace/vcpkg/installed/x64-windows/include "SQLITE_INC=-IC:/workspace/vcpkg/installed/x64-windows/include " PG_INC_DIR=C:/workspace/vcpkg/installed/x64-windows/include OPENJPEG_ENABLED=YES OPENJPEG_CFLAGS=-IC:/workspace/vcpkg/installed/x64-windows/include OPENJPEG_VERSION=20100 WEBP_ENABLED=YES WEBP_CFLAGS=-IC:/workspace/vcpkg/installed/x64-windows/include LIBXML2_INC=-IC:/workspace/vcpkg/installed/x64-windows/include PNG_EXTERNAL_LIB=1 PNGDIR=C:/workspace/vcpkg/installed/x64-windows/include ZLIB_INC=-IC:/workspace/vcpkg/installed/x64-windows/include ZLIB_EXTERNAL_LIB=1 ACCEPT_USE_OF_DEPRECATED_PROJ_API_H=1 MSVC_VER=1900 WIN64=YES WITH_PDB=1 DLLBUILD=1 GDAL_HOME=C:/workspace/vcpkg/packages/gdal_x64-windows/debug CXX_CRT_FLAGS=/MDd PROJ_LIBRARY=C:/workspace/vcpkg/installed/x64-windows/debug/lib/proj_d.lib PNG_LIB=C:/workspace/vcpkg/installed/x64-windows/debug/lib/libpng16d.lib "GEOS_LIB=C:/workspace/vcpkg/installed/x64-windows/debug/lib/geos_cd.lib C:/workspace/vcpkg/installed/x64-windows/debug/lib/geosd.lib" EXPAT_LIB=C:/workspace/vcpkg/installed/x64-windows/debug/lib/libexpatd.lib "CURL_LIB=C:/workspace/vcpkg/installed/x64-windows/debug/lib/libcurl-d.lib wsock32.lib wldap32.lib winmm.lib" "SQLITE_LIB=C:/workspace/vcpkg/installed/x64-windows/debug/lib/sqlite3.lib " OPENJPEG_LIB=C:/workspace/vcpkg/installed/x64-windows/debug/lib/openjp2.lib WEBP_LIBS=C:/workspace/vcpkg/installed/x64-windows/debug/lib/webpd.lib "LIBXML2_LIB=C:/workspace/vcpkg/installed/x64-windows/debug/lib/libxml2.lib C:/workspace/vcpkg/installed/x64-windows/debug/lib/iconv.lib C:/workspace/vcpkg/installed/x64-windows/debug/lib/charset.lib C:/workspace/vcpkg/installed/x64-windows/debug/lib/lzmad.lib" ZLIB_LIB=C:/workspace/vcpkg/installed/x64-windows/debug/lib/zlibd.lib "PG_LIB=C:/workspace/vcpkg/installed/x64-windows/debug/lib/libpq.lib C:/workspace/vcpkg/installed/x64-windows/debug/lib/libpgcommon.lib C:/workspace/vcpkg/installed/x64-windows/debug/lib/libpgport.lib Secur32.lib Shell32.lib Advapi32.lib Crypt32.lib Gdi32.lib C:/workspace/vcpkg/installed/x64-windows/debug/lib/libcrypto.lib C:/workspace/vcpkg/installed/x64-windows/debug/lib/libssl.lib" DEBUG=1 BUILD_TOOLS=0
    Working Directory: C:/workspace/vcpkg/buildtrees/gdal/x64-windows-dbg
    See logs for more information:
      C:\workspace\vcpkg\buildtrees\gdal\build-x64-windows-dbg-out.log
      C:\workspace\vcpkg\buildtrees\gdal\build-x64-windows-dbg-err.log

**Additional context**

Error: Building package gdal:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: gdal:x64-windows
  Vcpkg version: 2021-09-10-2059ef11aa6067e6f59b0d939c5d17e3c5c47d3e
[build-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/7205150/build-x64-windows-dbg-err.log)
[build-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/7205151/build-x64-windows-dbg-out.log)

**Comment by autoantwort** [comment]
Googling your error gives me the following: https://stackoverflow.com/questions/3898287/c-include-atlbase-h-is-not-found

**Comment by PhoebeHui** [comment]
@calysteau, please install atl related components via vs installer and try again.

**Comment by calysteau** [comment]
ATL components installed on Visual Studio 2019 and build is ok.

I installed VS with Unity, and ATL components are not installed in that case.

Thanks for helping.
