### ISSUE TITLE
cppzmq ubuntu compile error

### ISSUE THREAD

**Issue by zeynepkoyun** [microsoft/vcpkg#20285]
Hi @ras0219 
After the download was completed with the vcpkg install cppzmq:x64-linux command, I ran cmake .. respectively. Then I get the error in the image below in the make -j command.

![hata1](https://user-images.githubusercontent.com/53746550/134296155-effd2eda-0729-4cb4-a16a-109582a588ca.png)

**Comment by JackBoosY** [comment]
Can you provide the config command?

**Comment by JackBoosY** [comment]
Ping @zeynepkoyun for response.

**Comment by zeynepkoyun** [comment]
> Yanıt için @zeynepkoyun'a ping atın .

@JackBoosY  Hi, 
I was able to solve this problem by installing with vcpkg.
