### ISSUE TITLE
libcpr/cpr update to 1.6.2

### ISSUE THREAD

**Issue by rossbrin** [microsoft/vcpkg#20287]
Library name: libcpr/cpr

New version number: 1.62

cpr is a C++ library which wraps cURL.  The current release is 1.6.2 and adds a number of new features especially in the area of SSL/TLS support.  CPR documentation advises to create an issue on the vcpkg repo:

https://github.com/libcpr/cpr#building-cpr---using-vcpkg

thanks!

**Comment by JonLiu1993** [comment]
@rossbrin, Thanks for posting this issue, the cpr latest version is 1.6.2,update by #18386,plesase update your vcpkg and use

**Comment by rossbrin** [comment]
My mistake - many thanks for the quick reply.
