### ISSUE TITLE
vcpkg upgrade --no-dry-run build failure

### ISSUE THREAD

**Issue by mknigh23** [microsoft/vcpkg#20280]
**Host Environment**
- OS: Windows 10
- Compiler: VS2019 x64 Native Tools Command Prompt

**To Reproduce**
`./vcpkg upgrade --no-dry-run`

**Failure logs** 
The original error log is as follows...
A suitable version of cmake was not found (required v3.21.1). Downloading portable cmake v3.21.1...
Extracting cmake...
A suitable version of 7zip was not found (required v19.0.0). Downloading portable 7zip v19.0.0...
Extracting 7zip...
Error: vcpkg has crashed; no additional details are available.
The source line is C:\A\1\14\s\src\vcpkg\archives.cpp(73)

I manually copied the contents of the downloaded cmake zip file to the appropriate folder and installed the 7zip from the 7z1900-x64.msi file, then set my PATH to find them...

D:\libs\vcpkg>set PATH=C:\Program Files\7-Zip;D:\libs\vcpkg\downloads\tools\cmake-3.20.2-windows\cmake-3.20.2-windows-i386\bin;%PATH%

I the run the upgrade...

D:\libs\vcpkg>.\vcpkg upgrade --no-dry-run
The following packages will be rebuilt:
  * assimp[core]:x64-windows -> 5.0.1#5
  * boost-accumulators[core]:x64-windows -> 1.76.0
  * boost-accumulators[core]:x64-windows-static -> 1.76.0
. . .
  * zlib[core]:x86-windows -> 1.2.11#12
  * zlib[core]:x64-windows -> 1.2.11#12
  * zlib[core]:x64-windows-static -> 1.2.11#12
  * zstd[core]:x64-windows-static -> 1.5.0
  * zstd[core]:x64-windows -> 1.5.0
  * zstd[core]:x86-windows -> 1.5.0
Additional packages (*) will be modified to complete this operation.
Starting package 1/718: cgal:x64-windows
Removing package cgal:x64-windows...
Removing package cgal:x64-windows... done
Elapsed time for package cgal:x64-windows: 15.3 s
. . .
Starting package 358/718: zstd:x64-windows-static
Removing package zstd:x64-windows-static...
Removing package zstd:x64-windows-static... done
Elapsed time for package zstd:x64-windows-static: 130.6 ms
Detecting compiler hash for triplet x64-windows...
A suitable version of git was not found (required v2.32.0). Downloading portable git v2.32.0...
Downloading git...
  https://github.com/git-for-windows/git/releases/download/v2.32.0.windows.2/PortableGit-2.32.0.2-32-bit.7z.exe -> D:\libs\vcpkg\downloads\PortableGit-2.32.0.2-32-bit.7z.exe
Extracting git...
A suitable version of 7zip was not found (required v19.0.0). Downloading portable 7zip v19.0.0...
Extracting 7zip...
Error: vcpkg has crashed; no additional details are available.
The source line is C:\A\1\14\s\src\vcpkg\archives.cpp(73)

...but the 7zip install is not being identified.

I have now lost all my libraries and cannot build them.  HELP!

**Comment by PhoebeHui** [comment]
@mknigh23, could you execute 'git pull' and 'bootstrap-vcpkg.bat' and see if this issue still repro?

**Comment by mknigh23** [comment]
Hi @PhoebeHui,
When I run those commands, I get the following...

D:\libs\vcpkg>git pull
Already up to date.

D:\libs\vcpkg>bootstrap-vcpkg.bat
Downloading https://github.com/microsoft/vcpkg-tool/releases/download/2021-09-10/vcpkg.exe -> D:\libs\vcpkg\vcpkg.exe... done.
Validating signature... done.

Telemetry
---------
vcpkg collects usage data in order to help us improve your experience.
The data collected by Microsoft is anonymous.
You can opt-out of telemetry by re-running the bootstrap-vcpkg script with -disableMetrics,
passing --disable-metrics to vcpkg on the command line,
or by setting the VCPKG_DISABLE_METRICS environment variable.

Read more about vcpkg telemetry at docs/about/privacy.md

D:\libs\vcpkg>.\vcpkg upgrade --no-dry-run
All installed packages are up-to-date with the local portfiles.

...but my installed debug, include, lib and share folders are near empty.  I'm not familiar enough with vcpkg to get a listing of installed packages, but all I see is expat and openjpeg.

**Comment by PhoebeHui** [comment]
@mknigh23, you can use './vcpkg list' to list all installed packages. And please use 'git pull' & 'bootstrap-vcpkg.bat' to update the local source.

'vcpkg upgrade' has known problems that when one of the packages fails to build the information of all removed packages is lost. See https://github.com/microsoft/vcpkg/discussions/17922.

**Comment by mknigh23** [comment]
I am reinstalling everything, from scratch... thankfully, the output from '.\vcpkg upgrade' provides a clue as to what that was.  And no, the error has disappeared.

This came about in an attempt to get the latest version of PDAL, which you have version 1.7.1#12, but the PDAL site is showing 2.3.0.  vcpkg is nice, in that we don't have to run around looking for compatible libraries and build them with all their idiosyncrasies, but it should be kept up to date.  Most of the functions I needed in PDAL are recent additions and, in these rapidly changing/evolving times, it is important to have the most up to date software... and a package manager that allows upgrades without wiping a system.  Sorry for the rant, but I've been building libraries since last night and still going... while trying to meet deadlines to boot.

**Comment by PhoebeHui** [comment]
@mknigh23, good to know it works for you, we're updating many ports recently, parts of them has been done, pdal still in the queue, sorry for the old date version! There is an old PR https://github.com/microsoft/vcpkg/pull/14055 for updating the pdal to v2.2.0, however, it was closed since no progress is being made. We're happy to accept a PR if you can submit a new PR for it.

**Comment by mknigh23** [comment]
How do I do that?  I'm fairly new to vcpkg, so I'm feeling my way.  If there's a help document, I'm happy to accept a link.

**Comment by PhoebeHui** [comment]
[Here ](https://vcpkg.io/en/docs/examples/packaging-github-repos.html) is some docs for package a new library, you can also find the same docs from https://github.com/microsoft/vcpkg/tree/master/docs/examples.

However, you don't need do to that as the examples shows when upgrade a port, the basic step:
1. Update the version in https://github.com/microsoft/vcpkg/tree/master/ports/pdal
2. Update the version and SHA512 in https://github.com/microsoft/vcpkg/blob/master/ports/pdal/portfile.cmake
3. Update the patch to match the new source changes, noted that some patches may need to be removed.
4. If everything goes well, you can commit the changes, then update the vesion database by executing './vcpkg x-add-version pdal', and submit the changes again.

**Comment by dg0yt** [comment]
Warning: Updating port PDAL is tough, in particular for new contributors. Cross-platform issues ahead.

**Comment by mknigh23** [comment]
Okay.  May leave that for the time being, as deadlines are looming.  Thanks for your help.

**Comment by mknigh23** [comment]
@dg0yt thanks for the heads-up... will definitely leave it till things cool down.
