### ISSUE TITLE
I want to install some third library,but vcpck failed to download all the time 

### ISSUE THREAD

**Issue by North2Tree** [microsoft/vcpkg#20297]
C:\Users\Administrator\Desktop\1>vcpkg install zlib boost-iostreams boost-program-options boost-system boost-serialization eigen3 cgal[core] opencv glew glfw3 --triplet=x64-windows
Computing installation plan...
The following packages will be built and installed:
  * boost-accumulators[core]:x64-windows -> 1.76.0
  * boost-algorithm[core]:x64-windows -> 1.76.0
  * boost-align[core]:x64-windows -> 1.76.0
  * boost-any[core]:x64-windows -> 1.76.0
  * boost-atomic[core]:x64-windows -> 1.76.0
  * boost-bimap[core]:x64-windows -> 1.76.0
  * boost-bind[core]:x64-windows -> 1.76.0
  * boost-build[core]:x64-windows -> 1.75.0
  * boost-callable-traits[core]:x64-windows -> 1.76.0
  * boost-chrono[core]:x64-windows -> 1.76.0
  * boost-circular-buffer[core]:x64-windows -> 1.76.0
  * boost-compute[core]:x64-windows -> 1.76.0
  * boost-concept-check[core]:x64-windows -> 1.76.0
  * boost-container[core]:x64-windows -> 1.76.0
  * boost-container-hash[core]:x64-windows -> 1.76.0
  * boost-conversion[core]:x64-windows -> 1.76.0
  * boost-date-time[core]:x64-windows -> 1.76.0
  * boost-dynamic-bitset[core]:x64-windows -> 1.76.0
  * boost-endian[core]:x64-windows -> 1.76.0
  * boost-exception[core]:x64-windows -> 1.76.0
  * boost-filesystem[core]:x64-windows -> 1.76.0
  * boost-foreach[core]:x64-windows -> 1.76.0
  * boost-format[core]:x64-windows -> 1.76.0
  * boost-function[core]:x64-windows -> 1.76.0
  * boost-function-types[core]:x64-windows -> 1.76.0
  * boost-functional[core]:x64-windows -> 1.76.0
  * boost-fusion[core]:x64-windows -> 1.76.0
  * boost-geometry[core]:x64-windows -> 1.76.0
  * boost-graph[core]:x64-windows -> 1.76.0
  * boost-heap[core]:x64-windows -> 1.76.0
  * boost-integer[core]:x64-windows -> 1.76.0
  * boost-interval[core]:x64-windows -> 1.76.0
  * boost-intrusive[core]:x64-windows -> 1.76.0
  * boost-io[core]:x64-windows -> 1.76.0
    boost-iostreams[core]:x64-windows -> 1.76.0
  * boost-iterator[core]:x64-windows -> 1.76.0
  * boost-lambda[core]:x64-windows -> 1.76.0
  * boost-lexical-cast[core]:x64-windows -> 1.76.0
  * boost-logic[core]:x64-windows -> 1.76.0
  * boost-math[core]:x64-windows -> 1.76.0
  * boost-modular-build-helper[core]:x64-windows -> 1.76.0#1
  * boost-move[core]:x64-windows -> 1.76.0
  * boost-mp11[core]:x64-windows -> 1.76.0
  * boost-mpl[core]:x64-windows -> 1.76.0
  * boost-multi-array[core]:x64-windows -> 1.76.0
  * boost-multi-index[core]:x64-windows -> 1.76.0
  * boost-multiprecision[core]:x64-windows -> 1.76.0
  * boost-numeric-conversion[core]:x64-windows -> 1.76.0
  * boost-odeint[core]:x64-windows -> 1.76.0
  * boost-optional[core]:x64-windows -> 1.76.0
  * boost-parameter[core]:x64-windows -> 1.76.0
  * boost-phoenix[core]:x64-windows -> 1.76.0
  * boost-polygon[core]:x64-windows -> 1.76.0
  * boost-pool[core]:x64-windows -> 1.76.0
  * boost-predef[core]:x64-windows -> 1.76.0
    boost-program-options[core]:x64-windows -> 1.76.0
  * boost-property-map[core]:x64-windows -> 1.76.0
  * boost-property-tree[core]:x64-windows -> 1.76.0
  * boost-proto[core]:x64-windows -> 1.76.0
  * boost-ptr-container[core]:x64-windows -> 1.76.0
  * boost-qvm[core]:x64-windows -> 1.76.0
  * boost-random[core]:x64-windows -> 1.76.0
  * boost-range[core]:x64-windows -> 1.76.0
  * boost-ratio[core]:x64-windows -> 1.76.0
  * boost-rational[core]:x64-windows -> 1.76.0
  * boost-regex[core]:x64-windows -> 1.76.0
    boost-serialization[core]:x64-windows -> 1.76.0
  * boost-smart-ptr[core]:x64-windows -> 1.76.0
  * boost-spirit[core]:x64-windows -> 1.76.0
    boost-system[core]:x64-windows -> 1.76.0
  * boost-test[core]:x64-windows -> 1.76.0
  * boost-thread[core]:x64-windows -> 1.76.0
  * boost-tokenizer[core]:x64-windows -> 1.76.0
  * boost-tti[core]:x64-windows -> 1.76.0
  * boost-tuple[core]:x64-windows -> 1.76.0
  * boost-type-index[core]:x64-windows -> 1.76.0
  * boost-type-traits[core]:x64-windows -> 1.76.0
  * boost-typeof[core]:x64-windows -> 1.76.0
  * boost-ublas[core]:x64-windows -> 1.76.0
  * boost-units[core]:x64-windows -> 1.76.0
  * boost-unordered[core]:x64-windows -> 1.76.0
  * boost-utility[core]:x64-windows -> 1.76.0
  * boost-uuid[core]:x64-windows -> 1.76.0
  * boost-variant[core]:x64-windows -> 1.76.0
  * boost-winapi[core]:x64-windows -> 1.76.0
  * boost-xpressive[core]:x64-windows -> 1.76.0
  * bzip2[core]:x64-windows -> 1.0.8#2
    cgal[core]:x64-windows -> 5.3
    eigen3[core]:x64-windows -> 3.3.9#1
    glew[core]:x64-windows -> 2.2.0
    glfw3[core]:x64-windows -> 3.3.4
  * gmp[core]:x64-windows -> 6.2.1#6
  * libjpeg-turbo[core]:x64-windows -> 2.0.6#2
  * liblzma[core]:x64-windows -> 5.2.5#3
  * libpng[core]:x64-windows -> 1.6.37#15
  * libwebp[core,nearlossless,simd,unicode]:x64-windows -> 1.1.0#4
  * mpfr[core]:x64-windows -> 4.1.0#1
    opencv[core,dnn,jpeg,png,quirc,tiff,webp]:x64-windows -> 4.5.3
  * opencv4[core,dnn,jpeg,png,quirc,tiff,webp]:x64-windows -> 4.5.3#1
  * opengl[core]:x64-windows -> 0.0#9
  * protobuf[core]:x64-windows -> 3.15.8#4
  * quirc[core]:x64-windows -> 1.1#2
  * tiff[core,jpeg,lzma,zip]:x64-windows -> 4.3.0#1
  * vcpkg-cmake[core]:x64-windows -> 2021-09-13
  * vcpkg-cmake-config[core]:x64-windows -> 2021-05-22#1
  * vs-yasm[core]:x64-windows -> 0.5.0#1
  * yasm-tool[core]:x64-windows -> 1.3.0
    zlib[core]:x64-windows -> 1.2.11#12
  * zstd[core]:x64-windows -> 1.5.0
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Restored 0 packages from C:\Users\Administrator\AppData\Local\vcpkg\archives in 6.271 ms. Use --debug to see more details.
Starting package 1/109: boost-type-traits:x64-windows
Building package boost-type-traits[core]:x64-windows...
-- Downloading https://github.com/boostorg/type_traits/archive/boost-1.76.0.tar.gz -> boostorg-type_traits-boost-1.76.0.tar.gz...
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' = off
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Downloading https://github.com/boostorg/type_traits/archive/boost-1.76.0.tar.gz
Error: Failed to download from mirror set:
https://github.com/boostorg/type_traits/archive/boost-1.76.0.tar.gz: WinHttpSendRequest() failed: 12002

[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(626)
[DEBUG] Exiting after 19.67 s us (19470304 us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:83 (message):

      Failed to download file with error: 1
      If you use a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.

      3. You proxy's remote server is out of service.

      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)

      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:274 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_github.cmake:173 (vcpkg_download_distfile)
  ports/boost-type-traits/portfile.cmake:3 (vcpkg_from_github)
  scripts/ports.cmake:140 (include)

Error: Building package boost-type-traits:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-type-traits:x64-windows
  Vcpkg version: 2021-09-10-2059ef11aa6067e6f59b0d939c5d17e3c5c47d3e

Additionally, attach any relevant sections from the log files above.

**Comment by NancyLi1013** [comment]
Hi @North2Tree 

Thanks for posting this issue.

Could you please try to download https://github.com/boostorg/type_traits/archive/boost-1.76.0.tar.gz manually?

Then copy the archive file to _vcpkg_root_path/downloads_ and rename it as `boostorg-type_traits-boost-1.76.0.tar.gz` to rebuild this.

**Comment by North2Tree** [comment]
Thank you for your response, it is very useful to me, although it is a bit troublesome to download manually.
