### ISSUE TITLE
[jasper] build failure

### ISSUE THREAD

**Issue by playgithub** [microsoft/vcpkg#20299]
**Host Environment**
- OS: Windows
- Compiler: Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30133 for x64
- CMake: 3.21.3
- git commit: 9d892ff9270f2d2fe3b8e490471f0a7dfa78981e

**To Reproduce**
`./vcpkg install jasper --triplet=x64-windows`

**Failure logs** 
```
λ vcpkg install jasper --triplet=x64-windows
Computing installation plan...
The following packages will be built and installed:
  * freeglut[core]:x64-windows -> 3.2.1#6
    jasper[core]:x64-windows -> 2.0.33
  * libjpeg-turbo[core]:x64-windows -> 2.0.6#2
  * opengl[core]:x64-windows -> 0.0#9
...
Starting package 4/4: jasper:x64-windows
Building package jasper[core]:x64-windows...
-- Downloading https://github.com/mdadams/jasper/archive/fe00207dc10db1d7cc6f2757961c5c6bdfd10973.tar.gz -> mdadams-jasper-fe00207dc10db1d7cc6f2757961c5c6bdfd10973.tar.gz...
-- Cleaning sources at D:/vcpkg/buildtrees/jasper/src/6bdfd10973-cdf68d9a44.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/vcpkg/downloads/mdadams-jasper-fe00207dc10db1d7cc6f2757961c5c6bdfd10973.tar.gz
-- Using source at D:/vcpkg/buildtrees/jasper/src/6bdfd10973-cdf68d9a44.clean
CMake Error at ports/jasper/portfile.cmake:11 (vcpkg_cmake_configure):
  Unknown CMake command "vcpkg_cmake_configure".
Call Stack (most recent call first):
  scripts/ports.cmake:140 (include)


Error: Building package jasper:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: jasper:x64-windows
  Vcpkg version: 2021-09-10-unknownhash

Additionally, attach any relevant sections from the log files above.
```

**Comment by playgithub** [comment]
I have checked some other working ports, they use `vcpkg_configure_cmake` instead of `vcpkg_cmake_configure`.

But there is doc for `vcpkg_cmake_configure`, https://vcpkg.io/en/docs/maintainers/ports/vcpkg-cmake/vcpkg_cmake_configure.html

Why: Unknown CMake command "vcpkg_cmake_configure"?

**Comment by JackBoosY** [comment]
Please remove port `vcpkg-cmake:x64-windows` and try again.

**Comment by playgithub** [comment]
> Please remove port `vcpkg-cmake:x64-windows` and try again.

```shell
λ vcpkg install jasper
Computing installation plan...
Error: while loading vcpkg-cmake:
The port directory (D:\vcpkg\ports\vcpkg-cmake) does not exist
Error: failed to load port from D:\vcpkg\ports\vcpkg-cmake
Note: Updating vcpkg by rerunning bootstrap-vcpkg may resolve this failure.
```

**Comment by JackBoosY** [comment]
Please pull the master to update vcpkg to the latest.

**Comment by playgithub** [comment]
> Please pull the master to update vcpkg to the latest.

Before I'm posting the issue, I've tried this.

**Comment by dg0yt** [comment]
> > > The port directory (D:\vcpkg\ports\vcpkg-cmake) does not exist
> >
> > Please pull the master to update vcpkg to the latest.
>
> Before I'm posting the issue, I've tried this.

But `ports\vcpkg-cmake` does exist here. Please double-check that you pull/checkout https://github.com/microsoft/vcpkg master

**Comment by playgithub** [comment]
> But `ports\vcpkg-cmake` does exist here. Please double-check that you pull/checkout https://github.com/microsoft/vcpkg master

It doesn't work when `ports\vcpkg-cmake` is there.

Follow @JackBoosY's guide, removing `ports\vcpkg-cmake` is for debugging
> Please remove port `vcpkg-cmake:x64-windows` and try again.

**Comment by dg0yt** [comment]
> Follow @JackBoosY's guide, removing `ports\vcpkg-cmake` is for debugging
> 
> > Please remove port `vcpkg-cmake:x64-windows` and try again.

Don't remove the source. Do:
~~~
vcpkg uninstall --recurse vcpkg-cmake
~~~

**Comment by playgithub** [comment]
On a fresh installed env (OS, VS2019, vcpkg, ...), both `vcpkg install jasper` and `vcpkg install jasper:x64-windows` succeed.
