### ISSUE TITLE
[giflib] update to 5.2.1

### ISSUE THREAD

**Issue by quaesitor-scientiam** [microsoft/vcpkg#20327]
Library name:
giflib
New version number:
5.2.1
Other information that may be useful (release notes, etc...)

**Comment by dg0yt** [comment]
giflib is at 5.2.1.

**Comment by PhoebeHui** [comment]
@quaesitor-scientiam, giflib has been upgrade to 5.2.1 in master, you can get latest source via executing 'git pull' and 'bootstrap-vcpkg.bat' and try again.

**Comment by quaesitor-scientiam** [comment]
Thanks
