### ISSUE TITLE
[<libuvc>] build failure

### ISSUE THREAD

**Issue by JustinWuCN** [microsoft/vcpkg#20338]
**Host Environment**
- OS: Windows
- Compiler: VC 2019
-  Package: libuvc:x86-windows
-  Vcpkg version: 2021-05-05-e8977e69d9a3fb462d9ad42013d83a7682706659

**To Reproduce**
`./vcpkg install libuvc`

**Failure logs** 
- ninja: error: build.ninja:229: multiple rules generate uvc.lib [-w dupbuild=err]

[config-x86-windows-out.log](https://github.com/microsoft/vcpkg/files/7229478/config-x86-windows-out.log)

**Additional context**
no

**Comment by JonLiu1993** [comment]
@JustinWuCN ,Could you please update your vcpkg to the latest version and try again?

**Comment by JonLiu1993** [comment]
Closing this issue for no active thread for a long time. Please feel free to reopen this issue if it is still a problem for you.
