### ISSUE TITLE
[New Port Request] libimagequant

### ISSUE THREAD

**Issue by softworkz** [microsoft/vcpkg#20335]
Library name: libimagequant

Library description: Palette quantization library that powers pngquant and other PNG optimizers

Source repository URL: https://github.com/ImageOptim/libimagequant

Project homepage (if different from the source repository): https://pngquant.org/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

None. It's small and simple.

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
