### ISSUE TITLE
Finding dependent libraries

### ISSUE THREAD

**Issue by MikeGitb** [Microsoft/vcpkg#2033]
I'd like to update [date](https://github.com/HowardHinnant/date) but this will change the include directory (from "date.h" to "date/date.h"). Is there a way to find out if there are any libraries depending on date that this would break?

**Comment by ras0219-msft** [comment]
We do have an undocumented command `depend-info` which does something similar to this search:
```
>vcpkg depend-info date
date:
>vcpkg depend-info qt5
cgal: mpfr, mpir, zlib, boost, qt5
kf5plotting: ecm, qt5
qca: qt5
qscintilla: qt5
qt5: zlib, libjpeg-turbo, libpng, freetype, pcre, harfbuzz, sqlite3, libpq, double-conversion
qwt: qt5
```

**Comment by MikeGitb** [comment]
Thanks
