### ISSUE TITLE
[azure-kinect-sensor-sdk] build failure

### ISSUE THREAD

**Issue by cgnerds** [microsoft/vcpkg#20345]
**Host Environment**
- OS: Windows 11 Pro Insider Preview, Build 22463.rs_prerelease.210917-1503
- Compiler: Visual Studio 16 2019

**To Reproduce**
`./vcpkg install azure-kinect-sensor-sdk`

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
 vcpkg.exe install azure-kinect-sensor-sdk
Computing installation plan...
The following packages will be built and installed:
  * azure-c-shared-utility[core]:x64-windows -> 2021-09-09
    azure-kinect-sensor-sdk[core]:x64-windows -> 1.4.1#3
  * cjson[core]:x64-windows -> 1.7.15
  * ebml[core]:x64-windows -> 1.4.0#1
  * fmt[core]:x64-windows -> 8.0.1
  * gtest[core]:x64-windows -> 1.11.0
  * imgui[core]:x64-windows -> 1.84.2#1
  * libsoundio[core]:x64-windows -> 2.0.0#4
  * libusb[core]:x64-windows -> 1.0.24#5
  * libyuv[core]:x64-windows -> 2021-04-15
  * matroska[core]:x64-windows -> 1.6.2#1
  * spdlog[core]:x64-windows -> 1.9.2
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Restored 0 packages from C:\Users\38325\AppData\Local\vcpkg\archives in 289.4 us. Use --debug to see more details.
Starting package 1/12: azure-c-shared-utility:x64-windows
Building package azure-c-shared-utility[core]:x64-windows...
-- Note: azure-c-shared-utility only supports static library linkage. Building static library.
-- Downloading https://github.com/Azure/azure-c-shared-utility/archive/73a2039cc0de5ececf5755ebe731a6b5b98f85da.tar.gz -> Azure-azure-c-shared-utility-73a2039cc0de5ececf5755ebe731a6b5b98f85da.tar.gz...
-- Cleaning sources at D:/Source/vcpkg/buildtrees/azure-c-shared-utility/src/b5b98f85da-3f78b77ba2.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/Source/vcpkg/downloads/Azure-azure-c-shared-utility-73a2039cc0de5ececf5755ebe731a6b5b98f85da.tar.gz
-- Applying patch fix-utilityFunctions-conditions.patch
-- Applying patch disable-error.patch
-- Using source at D:/Source/vcpkg/buildtrees/azure-c-shared-utility/src/b5b98f85da-3f78b77ba2.clean
-- Configuring x64-windows
-- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:155 (message):
    Command failed: D:/Source/vcpkg/downloads/tools/cmake-3.21.1-windows/cmake-3.21.1-windows-i386/bin/cmake.exe --build . --config Release --target install -- -v -j17
    Working Directory: D:/Source/vcpkg/buildtrees/azure-c-shared-utility/x64-windows-rel
    See logs for more information:
      D:\Source\vcpkg\buildtrees\azure-c-shared-utility\install-x64-windows-rel-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:104 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:44 (vcpkg_build_cmake)
  ports/azure-c-shared-utility/portfile.cmake:39 (vcpkg_install_cmake)
  scripts/ports.cmake:140 (include)

Error: Building package azure-c-shared-utility:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: azure-c-shared-utility:x64-windows
  Vcpkg version: 2021-09-10-2059ef11aa6067e6f59b0d939c5d17e3c5c47d3e

Additionally, attach any relevant sections from the log files above.

-Please attach any additional failure logs mentioned in the console output.

[install-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/7229746/install-x64-windows-rel-out.log)

**Comment by JonLiu1993** [comment]
@cgnerds , I can't repro this issue locally, you may need get latest source and rebuild azure-kinect-sensor-sdk?

**Comment by JonLiu1993** [comment]
Closing this issue for no active thread for a long time. Please feel free to reopen this issue if it is still a problem for you.
