### ISSUE TITLE
[ pthreads:x64-windows] build failure

### ISSUE THREAD

**Issue by nhanminhnhat1998** [microsoft/vcpkg#20355]
**Host Environment**
- OS: WIN 10
- Compiler: Vcpkg version: 2021-09-10-2059ef11aa6067e6f59b0d939c5d17e3c5c47d3e

**To Reproduce**

`CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/nmake.exe" -f Makefile all install DESTROOT="C:\\Users\\DUMA\\darknet\\vcpkg\\packages\\pthreads_x64-windows"`
**Failure logs** 
`Detecting compiler hash for triplet x64-windows...
The following packages will be built and installed:
  * bzip2[core]:x64-windows -> 1.0.8#2
    cuda[core]:x64-windows -> 10.1#8
    cudnn[core]:x64-windows -> 7.6.5#4
  * ffmpeg[avcodec,avdevice,avfilter,avformat,core,swresample,swscale]:x64-windows -> 4.4#14
  * giflib[core]:x64-windows -> 5.2.1
  * hdf5[core,szip,zlib]:x64-windows -> 1.12.0#4
  * leptonica[core]:x64-windows -> 1.81.1
  * libarchive[bzip2,core,libxml2,lz4,lzma,openssl,zstd]:x64-windows -> 3.5.2#1
  * libiconv[core]:x64-windows -> 1.16#11
  * libjpeg-turbo[core]:x64-windows -> 2.0.6#2
  * liblzma[core]:x64-windows -> 5.2.5#3
  * libpng[core]:x64-windows -> 1.6.37#15
  * libwebp[core,nearlossless,simd,unicode]:x64-windows -> 1.1.0#4
  * libxml2[core]:x64-windows -> 2.9.12#4
  * lz4[core]:x64-windows -> 1.9.3#3
    opencv[contrib,core,dnn,ffmpeg,jpeg,png,quirc,tiff,webp]:x64-windows -> 4.5.3
  * opencv4[contrib,core,dnn,ffmpeg,jpeg,png,quirc,tiff,webp]:x64-windows -> 4.5.3#2
  * openjpeg[core]:x64-windows -> 2.3.1#4
  * openssl[core]:x64-windows -> 1.1.1l#1
  * protobuf[core]:x64-windows -> 3.18.0
    pthreads[core]:x64-windows -> 3.0.0#10
  * quirc[core]:x64-windows -> 1.1#2
    stb[core]:x64-windows -> 2020-09-14#1
  * szip[core]:x64-windows -> 2.1.1#7
  * tesseract[core]:x64-windows -> 4.1.1#8
  * tiff[core,jpeg,lzma,zip]:x64-windows -> 4.3.0#1
  * vcpkg-cmake[core]:x64-windows -> 2021-09-13
  * vcpkg-cmake-config[core]:x64-windows -> 2021-05-22#1
  * vcpkg-pkgconfig-get-modules[core]:x64-windows -> 2021-04-02#1
  * zlib[core]:x64-windows -> 1.2.11#12
  * zstd[core]:x64-windows -> 1.5.0
Additional packages (*) will be modified to complete this operation.
Restored 0 packages from C:\Users\DUMA\AppData\Local\vcpkg\archives in 741.3 us. Use --debug to see more details.
Starting package 1/31: pthreads:x64-windows
Building package pthreads[core]:x64-windows...
-- Downloading https://sourceforge.net/projects/pthreads4w//files/pthreads4w-code-v3.0.0.zip/download;https://sourceforge.net/projects/pthreads4w//files/pthreads4w-code-v3.0.0.zip/download?use_mirror=cfhcable;https://sourceforge.net/projects/pthreads4w//files/pthreads4w-code-v3.0.0.zip/download?use_mirror=pilotfiber;https://sourceforge.net/projects/pthreads4w//files/pthreads4w-code-v3.0.0.zip/download?use_mirror=gigenet;https://sourceforge.net/projects/pthreads4w//files/pthreads4w-code-v3.0.0.zip/download?use_mirror=versaweb;https://sourceforge.net/projects/pthreads4w//files/pthreads4w-code-v3.0.0.zip/download?use_mirror=ayera;https://sourceforge.net/projects/pthreads4w//files/pthreads4w-code-v3.0.0.zip/download?use_mirror=netactuate;https://sourceforge.net/projects/pthreads4w//files/pthreads4w-code-v3.0.0.zip/download?use_mirror=phoenixnap;https://sourceforge.net/projects/pthreads4w//files/pthreads4w-code-v3.0.0.zip/download?use_mirror=astuteinternet;https://sourceforge.net/projects/pthreads4w//files/pthreads4w-code-v3.0.0.zip/download?use_mirror=freefr;https://sourceforge.net/projects/pthreads4w//files/pthreads4w-code-v3.0.0.zip/download?use_mirror=netcologne;https://sourceforge.net/projects/pthreads4w//files/pthreads4w-code-v3.0.0.zip/download?use_mirror=deac-riga;https://sourceforge.net/projects/pthreads4w//files/pthreads4w-code-v3.0.0.zip/download?use_mirror=excellmedia;https://sourceforge.net/projects/pthreads4w//files/pthreads4w-code-v3.0.0.zip/download?use_mirror=iweb;https://sourceforge.net/projects/pthreads4w//files/pthreads4w-code-v3.0.0.zip/download?use_mirror=jaist;https://sourceforge.net/projects/pthreads4w//files/pthreads4w-code-v3.0.0.zip/download?use_mirror=jztkft;https://sourceforge.net/projects/pthreads4w//files/pthreads4w-code-v3.0.0.zip/download?use_mirror=managedway;https://sourceforge.net/projects/pthreads4w//files/pthreads4w-code-v3.0.0.zip/download?use_mirror=nchc;https://sourceforge.net/projects/pthreads4w//files/pthreads4w-code-v3.0.0.zip/download?use_mirror=netix;https://sourceforge.net/projects/pthreads4w//files/pthreads4w-code-v3.0.0.zip/download?use_mirror=ufpr;https://sourceforge.net/projects/pthreads4w//files/pthreads4w-code-v3.0.0.zip/download?use_mirror=tenet -> pthreads4w-code-v3.0.0.zip...
-- Cleaning sources at C:/Users/DUMA/darknet/vcpkg/buildtrees/pthreads/src/49e541b66c-53502e357c.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/DUMA/darknet/vcpkg/downloads/pthreads4w-code-v3.0.0.zip
-- Applying patch fix-arm-macro.patch
-- Applying patch use-md.patch
-- Using source at C:/Users/DUMA/darknet/vcpkg/buildtrees/pthreads/src/49e541b66c-53502e357c.clean
-- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/nmake.exe" -f Makefile all install DESTROOT="C:\\Users\\DUMA\\darknet\\vcpkg\\packages\\pthreads_x64-windows"
    Working Directory: C:/Users/DUMA/darknet/vcpkg/buildtrees/pthreads/src/49e541b66c-53502e357c.clean
    Error code: 2
    See logs for more information:
      C:\Users\DUMA\darknet\vcpkg\buildtrees\pthreads\nmake-build-x64-windows-release-out.log
      C:\Users\DUMA\darknet\vcpkg\buildtrees\pthreads\nmake-build-x64-windows-release-err.log

Call Stack (most recent call first):
  ports/pthreads/portfile.cmake:38 (vcpkg_execute_required_process)
  scripts/ports.cmake:140 (include)

Error: Building package pthreads:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: pthreads:x64-windows
  Vcpkg version: 2021-09-10-2059ef11aa6067e6f59b0d939c5d17e3c5c47d3e

Additionally, attach any relevant sections from the log files above.`

**Additional context**
i am trying build the darknet library https://github.com/AlexeyAB/darknet

Here are their compile  instruction
Set-ExecutionPolicy unrestricted -Scope CurrentUser -Force
git clone https://github.com/AlexeyAB/darknet
cd darknet
.\build.ps1 -UseVCPKG -EnableOPENCV -EnableCUDA -EnableCUDNN

**Comment by PhoebeHui** [comment]
@nhanminhnhat1998, could you attach the failure logs?

C:\Users\DUMA\darknet\vcpkg\buildtrees\pthreads\nmake-build-x64-windows-release-out.log
C:\Users\DUMA\darknet\vcpkg\buildtrees\pthreads\nmake-build-x64-windows-release-err.log

**Comment by nhanminhnhat1998** [comment]
my bad .


- nmake-build-x64-windows-release-out.log:
[nmake-build-x64-windows-release-out.log](https://github.com/microsoft/vcpkg/files/7231255/nmake-build-x64-windows-release-out.log)

- nmake-build-x64-windows-release-err.log 
[nmake-build-x64-windows-release-err.log](https://github.com/microsoft/vcpkg/files/7231256/nmake-build-x64-windows-release-err.log)

[vcpkg-manifest-install.log](https://github.com/microsoft/vcpkg/files/7231258/vcpkg-manifest-install.log)

**Comment by PhoebeHui** [comment]
@nhanminhnhat1998, do you install windows sdk? if not, could you install it via VS installer and try again?
For me the errno.h file locates in C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\ucrt.

```
.\_ptw32.h(143): fatal error C1083: Cannot open include file: 'errno.h': No such file or directory
```

**Comment by nhanminhnhat1998** [comment]
Hi PheobeHui,

I works thanks a lot. but i have another error, in term of downloading. I tried to turn of my firewall and anti virus. but it did not help. Not sure if I should create new issue.

Thank you for your help.

here are the files it tried to download
Error: Failed to download from mirror set:
https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win32/nasm-2.15.05-win32.zip: WinHttpSendRequest() failed: 12007
https://fossies.org/windows/misc/nasm-2.15.05-win32.zip: WinHttpSendRequest() failed: 12007

[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(626)
[DEBUG] Exiting after 84.51 ms us (84439 us)
