### ISSUE TITLE
gdal 2.* build failed

### ISSUE THREAD

**Issue by saedrna** [Microsoft/vcpkg#2036]
OS: Windows 10
Platform : VS 2017
triplet : x64-windows

With error code:
nmake-build-x64-windows-release-err.log
```
NMAKE : fatal error U1077: “"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\bin\HostX64\x64\cl.EXE"”: 返回代码“0xc0000005”
Stop.
NMAKE : fatal error U1077: “"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\bin\HostX64\x64\nmake.EXE"”: 返回代码“0x2”
Stop.
```

nmake-build-x64-windows-release-out.log
```
***
***
cpl_hash_set.cpp
cl: 命令行 error D8000 :cl: 命令行 error D8000 :cl: 命令行 error D8000 :cl: 命令行 error D8000 :cl: 命令行 error D8000 :cl: 命令行 error D8000 :cl: 命令行 error D8000 
```

Sorry for the Chinese character, I think this is a internal compiler error, I have experienced this once using  nmake myself. And a solution is to use x64_86 instead of native x64 nmake to build gdal.

My question is, is it possible to select x86-64 pipeline instead of native x64 for x64-windows pipeline?

**Comment by saedrna** [comment]
fix by `set(VCPKG_PLATFORM_TOOLSET "v140")`. It seems that this is only exist for vs 2017

**Comment by lineCode** [comment]
i have the same problem, are you resolve it?

**Comment by smplife** [comment]
Hi saedrna
With this: set(VCPKG_PLATFORM_TOOLSET "v140"), you resolve it? Where you insert this code?
Thanks
