### ISSUE TITLE
[New Port Request] CTK

### ISSUE THREAD

**Issue by Hconk** [microsoft/vcpkg#20407]
Library name:  CTK
Library description:  A set of common support code for medical imaging, surgical navigation, and related purposes.

Source repository URL: https://github.com/commontk/CTK

Project homepage (if different from the source repository): http://commontk.org

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
