### ISSUE TITLE
[boost 1.77] build failure - Unsupported value for VCPKG_PLATFORM_TOOLSET: 'v143'

### ISSUE THREAD

**Issue by niclar** [microsoft/vcpkg#20406]
Building package boost-lambda2[core]:x64-windows-static...
-- Downloading https://github.com/boostorg/lambda2/archive/boost-1.77.0.tar.gz -> boostorg-lambda2-boost-1.77.0.tar.gz...
-- Cleaning sources at C:/src/thirdparty/vcpkg/buildtrees/boost-lambda2/src/ost-1.77.0-225e739b3c.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/src/thirdparty/vcpkg/downloads/boostorg-lambda2-boost-1.77.0.tar.gz
-- Using source at C:/src/thirdparty/vcpkg/buildtrees/boost-lambda2/src/ost-1.77.0-225e739b3c.clean
-- Packaging headers
-- Packaging headers done
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.74.0/LICENSE_1_0.txt -> boost_LICENSE_1_0.txt...
-- Installing: C:/src/thirdparty/vcpkg/packages/boost-lambda2_x64-windows-static/share/boost-lambda2/usage
-- Installing: C:/src/thirdparty/vcpkg/packages/boost-lambda2_x64-windows-static/share/boost-lambda2/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\x\AppData\Local\vcpkg\archives\ad\add76b020aae5e94488b8ce2c857a4ae7a0da758012542d7b3f926977ba4fb4e.zip
Installing package boost-lambda2[core]:x64-windows-static...
Elapsed time for package boost-lambda2:x64-windows-static: 426.2 ms
Starting package 5/11: boost-log:x64-windows-static
Building package boost-log[core]:x64-windows-static...
-- Downloading https://github.com/boostorg/log/archive/boost-1.77.0.tar.gz -> boostorg-log-boost-1.77.0.tar.gz...
-- Cleaning sources at C:/src/thirdparty/vcpkg/buildtrees/boost-log/src/ost-1.77.0-b54115eac1.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/src/thirdparty/vcpkg/downloads/boostorg-log-boost-1.77.0.tar.gz
-- Using source at C:/src/thirdparty/vcpkg/buildtrees/boost-log/src/ost-1.77.0-b54115eac1.clean
CMake Error at installed/x64-windows/share/boost-build/boost-modular-build.cmake:316 (message):
  Unsupported value for VCPKG_PLATFORM_TOOLSET: 'v143'
Call Stack (most recent call first):
  ports/boost-log/portfile.cmake:28 (boost_modular_build)
  scripts/ports.cmake:141 (include)

**Comment by PhoebeHui** [comment]
@niclar, boost has been updated to 1.77.0 today, you need remove the old version by './vcpkg remove boost-uninstall:x64-windows --recurse' and try again, I can't repro this issue locally, it built successfully for me.

**Comment by niclar** [comment]
@PhoebeHui , thanks

vcpkg remove boost-uninstall-static:x64-windows --recurse

solved it...
