### ISSUE TITLE
[lapack-reference] build failure

### ISSUE THREAD

**Issue by Orig1n** [microsoft/vcpkg#20419]
**Host Environment**
- OS: [Windows10]
- Compiler: Visual Studio 2019 Community

**To Reproduce**
`./vcpkg install lapack-reference`

**Failure logs** 
```
Computing installation plan...
The following packages will be built and installed:
    lapack-reference[blas-select,core,noblas]:x64-windows -> 3.8.0#4
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\Origin\AppData\Local\vcpkg\archives\31\31a6b93579802da0af7329744224f0eba1aeab21.zip
Starting package 1/1: lapack-reference:x64-windows
Building package lapack-reference[blas-select,core,noblas]:x64-windows...
-- Using cached D:/vcpkg-master/downloads/Reference-LAPACK-lapack-v3.8.0.tar.gz
-- Cleaning sources at D:/vcpkg-master/buildtrees/lapack-reference/src/v3.8.0-954f10683f.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/vcpkg-master/downloads/Reference-LAPACK-lapack-v3.8.0.tar.gz
-- Using source at D:/vcpkg-master/buildtrees/lapack-reference/src/v3.8.0-954f10683f.clean
-- The Fortran compiler identification is unknown
-- No Fortran compiler found on the PATH. Using MinGW gfortran!
-- Using msys root at D:/vcpkg-master/downloads/tools/msys2/41f8981ddd3a5888
-- Found external ninja('1.10.2').
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
    Command failed: ninja -v
    Working Directory: D:/vcpkg-master/buildtrees/lapack-reference/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\vcpkg-master\buildtrees\lapack-reference\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:323 (vcpkg_execute_required_process)
  ports/lapack-reference/portfile.cmake:63 (vcpkg_configure_cmake)
  scripts/ports.cmake:141 (include)


Error: Building package lapack-reference:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: lapack-reference:x64-windows
  Vcpkg version: 2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9

Additionally, attach any relevant sections from the log files above.
```
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/7248573/config-x64-windows-out.log)

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by JackBoosY** [comment]
```
-- The Fortran compiler identification is unknown
-- The C compiler identification is unknown
-- Detecting Fortran compiler ABI info
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_Fortran_PREPROCESS_SOURCE
CMake Error at D:/CMake/share/cmake-3.20/Modules/CMakeDetermineCompilerABI.cmake:49 (try_compile):
  Failed to generate test project build system.
Call Stack (most recent call first):
  D:/CMake/share/cmake-3.20/Modules/CMakeTestFortranCompiler.cmake:20 (CMAKE_DETERMINE_COMPILER_ABI)
  CMakeLists.txt:3 (project)
```
The Fortran compiler should be gfortran.exe and the C compiler should be gcc.exe.
Please remove directory _VCPKG_ROOT/downloads/tools/msys2_ and try again.

Thanks.

**Comment by Orig1n** [comment]
I did so but it didn't work, and the failure logs are the same.
I searched for gfortran.exe and gcc.exe in msys2 folder and I found them.

**Comment by JackBoosY** [comment]
Can you please pass ` --x-cmake-args=--trace-expand` to vcpkg install command and provide the output?
And please ensure your vcpkg is latest first.

**Comment by sfhacker** [comment]
@Orig1n Are you mixing toolchains? If so, you are looking for trouble.
There is a lapack newer version you could try.

-- The Fortran compiler identification is GNU 11.1.0
-- The C compiler identification is GNU 11.1.0
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Check for working Fortran compiler: C:/MinGW/bin/gfortran.exe - skipped
-- Checking whether C:/MinGW/bin/gfortran.exe supports Fortran 90
-- Checking whether C:/MinGW/bin/gfortran.exe supports Fortran 90 - yes
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/MinGW/bin/gcc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
...
...

Perhaps your environment is broken and/or polluted somehow.

**Comment by sfhacker** [comment]
Just built lapack 3.8.0 from source on Windows 10 x64. All the tests passed!

![image](https://user-images.githubusercontent.com/25817529/135278792-94ca92f4-0347-40e0-a588-7a9add9d2646.png)

**Comment by JackBoosY** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.
