### ISSUE TITLE
Missing include on algorithm - boost.process 1.77

### ISSUE THREAD

**Issue by Stardusstt** [microsoft/vcpkg#20413]
[https://github.com/boostorg/process/issues/213](https://github.com/boostorg/process/issues/213)

Error: boost/process/detail/traits/wchar_t.hpp(150,14): error : no member named 'transform' in namespace 'std'
Fix: include <algorithm> in wchar_t.hpp

fix in [https://github.com/boostorg/process/pull/215](https://github.com/boostorg/process/pull/215)

**Comment by cjwijtmans** [comment]
are you building with C++17. std::transform was introduced since then.

**Comment by PhoebeHui** [comment]
@Stardusstt, thanks for bringing up this! I have already submitted a PR to fix it.
