### ISSUE TITLE
Adding Directx SDK to vcpkg

### ISSUE THREAD

**Issue by brupelo** [microsoft/vcpkg#2042]
Any plan to include the Directx SDK on vcpkg?

Asking cos some of my old apps are using DX Sdk aug2007 and others even older SDK ones. But all in all, it'd be awesome if vcpkg would allow me to install the Directx SDK (include headers + libs), that way I could update properly my DX apps without having these SDKs in other places different than vcpkg.

Thanks in advance.

**Comment by ras0219-msft** [comment]
Note for someone interested in tackling this: It looks like the directx SDK installer is unpackable via 7zip.

**Comment by brupelo** [comment]
In the meantime, I just unpack myself manually the DX headers+libs+binaries on vcpkg installed directory which is far from being optimal. To be honest, this would be a really interesting feature, being able to install/uninstall the different SDK DX versions by using vcpkg instead the typical dx SDK installers.

If I was familiar with vcpkg I'd give it a try, unfortunately I don't :) . How hard would be to achieve btw? Without knowing at all the vcpkg mechanisms feels like it's a trivial feature, is it not?

**Comment by ras0219-msft** [comment]
Yeah, it shouldn't be too terribly hard. I think it would make a fine first PR for someone new to vcpkg!

Some references that might be useful:
https://github.com/Microsoft/vcpkg/tree/master/ports/msmpi
https://github.com/Microsoft/vcpkg/tree/master/ports/redshell

**Comment by JackBoosY** [comment]
We can’t reopen this issue until a PR is opened, unfortunately, consider making a pull request!
