### ISSUE TITLE
How to do with absolute path in installed files?

### ISSUE THREAD

**Issue by playgithub** [microsoft/vcpkg#20425]
LibA has a accompanying data file for it to work.

For a lib, a relative path makes no sense,
the lib must know the absolute path of the data file,
so the path is saved somewhere in the installed folders,
and the value of the path is the path of installed data file, it is fixed.

With traditional cmake install, no problem.
But for vcpkg, it is initially installed in `vcpkg\packages`, then regularized and copied to `vcpkg\installed`.

After some debugging, I can see include directories will be modified to be in `vcpkg\installed`,
but paths that are genereated by `configure_file` are still in `vcpkg\packages`.
It means the installed pkg in `vcpkg\packages` depend on the data file in `vcpkg\packages`, is it expected?

**Comment by playgithub** [comment]
> Since vcpkg can package and export the generated files, we cannot use absolute paths in binary/configuration files but must use relative paths.

But a relative path only makes sense for applications, for a lib a relative path makes no sense, right?

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
