### ISSUE TITLE
[FontConfig] build failure

### ISSUE THREAD

**Issue by kossiLeBeau** [microsoft/vcpkg#20438]
**Host Environment**
- OS: Window\s 7
-Compiler VS 2019 command line prompt (I applied the latest update)

**To Reproduce**
`.vcpkg install fontconfig

**Failure logs** 
I manually downloaded fontconfig from gitlab.freedesktop.org/fontconfig/fontconfig/-/tags/2.13.94/fontconfig-2.13.94.tar.gz manually, because vcpkg was looking at a wrong  downloading URL. 
I placed the down;loaded file in /vcpkg/download and renamed the file to fontconfig-fontconfig-2.13.94.tar.gz.
I restarted "vcpkg install fontconfig" again and get the following message.
It stopped when vcpkg tried to execute python .exe from vcpkg/downloads/tools/python/python-3.9.7-x86/

I tried to run python.exe from the above directory, and I had an error message stating: **"The program can't start because api-ms-win-core-path-l1-1-0.dll is missing from your computer"**

I downloaded the above dll and vcpkg is giving me **access violation error.**

**Additional context**

E:\vcpkg>vcpkg install fontconfig
[stdout-x86-windows.log](https://github.com/microsoft/vcpkg/files/7255631/stdout-x86-windows.log)

Computing installation plan...
The following packages will be built and installed:
    fontconfig[core]:x86-windows -> 2.13.94
Detecting compiler hash for triplet x86-windows...
Restored 0 packages from C:\Users\Blaise\AppData\Local\vcpkg\archives in 492.2 u
s. Use --debug to see more details.
Starting package 1/1: fontconfig:x86-windows
Building package fontconfig[core]:x86-windows...
-- Downloading https://gitlab.freedesktop.org/fontconfig/fontconfig/-/archive/2.
13.94/fontconfig-2.13.94.tar.gz -> fontconfig-fontconfig-2.13.94.tar.gz...
-- Cleaning sources at E:/vcpkg/buildtrees/fontconfig/src/2.13.94-6fd83e1cbe.cle
an. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/vcpkg/downloads/fontconfig-fontconfig-2.13.94.tar.gz
-- Using source at E:/vcpkg/buildtrees/fontconfig/src/2.13.94-6fd83e1cbe.clean
-- Found external ninja('1.10.2').
-- Getting CMake variables for x86-windows
-- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.
2-2-any.pkg.tar.zst;https://www2.futureware.at/~nickoe/msys2-mirror/mingw/i686/m
ingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst;https://mirror.yandex.ru/mirro
rs/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst;https://m
irrors.tuna.tsinghua.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-
any.pkg.tar.zst;https://mirrors.ustc.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-
config-0.29.2-2-any.pkg.tar.zst;https://mirror.bit.edu.cn/msys2/mingw/i686/mingw
-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst;https://mirror.selfnet.de/msys2/mi
ngw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst;https://mirrors.sjtu
g.sjtu.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zs
t -> msys-mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst...
-- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-gi
t-8.0.0.5906.c9a21571-1-any.pkg.tar.zst;https://www2.futureware.at/~nickoe/msys2
-mirror/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pk
g.tar.zst;https://mirror.yandex.ru/mirrors/msys2/mingw/i686/mingw-w64-i686-libwi
npthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst;https://mirrors.tuna.tsinghua
.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-
any.pkg.tar.zst;https://mirrors.ustc.edu.cn/msys2/mingw/i686/mingw-w64-i686-libw
inpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst;https://mirror.bit.edu.cn/ms
ys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.ta
r.zst;https://mirror.selfnet.de/msys2/mingw/i686/mingw-w64-i686-libwinpthread-gi
t-8.0.0.5906.c9a21571-1-any.pkg.tar.zst;https://mirrors.sjtug.sjtu.edu.cn/msys2/
mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zs
t -> msys-mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst
...
-- Using msys root at E:/vcpkg/downloads/tools/msys2/aa5af7b2aa7e90e8
-- Configuring x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):

    Command failed: E:/vcpkg/downloads/tools/python/python-3.9.7-x86/python.exe
E:/vcpkg/downloads/tools/meson/meson-aeda7f249c4a5dbbecc52e44f382246a2377b5b0/me
son.py --buildtype plain --backend ninja --wrap-mode nodownload --native E:/vcpk
g/buildtrees/fontconfig/meson-nativ-x86-windows.log --default-library shared --l
ibdir lib --native E:/vcpkg/buildtrees/fontconfig/meson-nativ-x86-windows-debug.
log -Ddebug=true --prefix E:/vcpkg/packages/fontconfig_x86-windows/debug --inclu
dedir ../include -Dcmake_prefix_path=['E:/vcpkg/installed/x86-windows/debug','E:
/vcpkg/installed/x86-windows','E:/vcpkg/installed/x86-windows/share'] E:/vcpkg/b
uildtrees/fontconfig/src/2.13.94-6fd83e1cbe.clean
    Working Directory: E:/vcpkg/buildtrees/fontconfig/x86-windows-dbg
    Error code: Exit code 0xc0000135

    See logs for more information:

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_meson.cmake:512 (vcpkg_execute_required_process)

  ports/fontconfig/portfile.cmake:16 (vcpkg_configure_meson)
  scripts/ports.cmake:141 (include)

Error: Building package fontconfig:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: fontconfig:x86-windows
  Vcpkg version: 2021-09-10-2059ef11aa6067e6f59b0d939c5d17e3c5c47d3e

Additionally, attach any relevant sections from the log files above.

E:\vcpkg>

**Comment by PhoebeHui** [comment]
Closing in favor of https://github.com/microsoft/vcpkg/issues/16986.
