### ISSUE TITLE
Port Request: minhook

### ISSUE THREAD

**Issue by iskiselev** [microsoft/vcpkg#2043]
[Minhook](https://github.com/TsudaKageyu/minhook) - The Minimalistic x86/x64 API Hooking Library for Windows.
It would be great to have a port for it.

**Comment by Mixaill** [comment]
trying to support it with the upstream in the first.
https://github.com/TsudaKageyu/minhook/pull/58

**Comment by iskiselev** [comment]
Looks like maintainer of minhook project do not merge it there. Can CMake be added as patch from VCPKG side?

**Comment by NancyLi1013** [comment]
Hi @iskiselev, thanks for posting this issue. The port has been merged to the master. Please try to use it.
