### ISSUE TITLE
[New Port Request] mysql-connector-cpp

### ISSUE THREAD

**Issue by wxilas21** [microsoft/vcpkg#20453]
Library name: 
mysql-connector-cpp

Library description:
MySQL Connector/C++ is a MySQL database connector for C++. It lets you develop C++ and C applications that connect to MySQL Server.

Source repository URL:
https://github.com/mysql/mysql-connector-cpp

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
I need the latest version and version 1.1
(https://github.com/mysql/mysql-connector-cpp/tree/1.1)

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
