### ISSUE TITLE
Is mixed _UNICODE and _MBCS a problem?

### ISSUE THREAD

**Issue by twMr7** [microsoft/vcpkg#2045]
I can see from logs that some ports are built with _UNICODE defined, and some with _MBCS.
Should I care about this for linking these mix-linked libraries in my project?
How to explicitly specify _UNICODE definition to build system if the port is built with _MBCS by default?

**Comment by woodmeister123** [comment]
I've noticed this as well, is there a way of selecting?

**Comment by NancyLi1013** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen.
