### ISSUE TITLE
Allow the user to specify NuGet package version number on NuGet export

### ISSUE THREAD

**Issue by adv12** [microsoft/vcpkg#20467]
**Is your feature request related to a problem? Please describe.**
I'm using vcpkg to build a suite of libraries consumed by a VC++ application that uses MSBuild.  I have a CMake project for building all the required libraries via vcpkg and exporting a NuGet package via vcpkg export --nuget.  I then install this NuGet package in a local NuGet repository and consume it in my app's MSBuild project.  Right now I'm using the NuGet filename to contain the version information, but that means that every time I create a new NuGet package, my app must be updated to point to a totally different NuGet package.  I would prefer to be able to simply upgrade my project to the latest version of a NuGet package with a consistent name.

**Proposed solution**
I would like to be able to pass a NuGet package version number to vcpkg export via an argument like --nuget-version=1.0.0.1234 so I can represent continuity between exported NuGet packages.

**Describe alternatives you've considered**
The only alternative I've considered is what I'm already doing--using the NuGet package name for version number information.

**Comment by JonLiu1993** [comment]
Vcpkg export supports specifying the name and version of the package through --nuget-id and --nuget-version.
