### ISSUE TITLE
[ffmpeg] build failure | build causes computer to crash

### ISSUE THREAD

**Issue by ThomasWilshaw** [microsoft/vcpkg#20476]
**Host Environment**
- OS: Windows 10
- Compiler: cl.exe

**To Reproduce**
`./vcpkg install ffmpeg[core]:x64-windows`

Computer blue screens with the error message: `KERNEL MODE HEAP CORRUPTION`

**Failure logs** 
[build-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/7271618/build-x64-windows-rel-out.log)
None, see below

**Additional context**
Everytime I try to build ffmpeg my laptop crashes with a blue screen. I've built plenty of other packages via vcpkg with no issues at all. I do have various log files in `buildtress/ffmpeg` but I don't know which would be most useful, please advise. The only slight error message I can see in any is the follwoing:

```
Checking patch configure...
warning: configure has type 100644, expected 100755
Hunk #1 succeeded at 6549 (offset 52 lines).
Applied patch configure cleanly.
```

**Comment by JackBoosY** [comment]
cc @dg0yt @cenit

**Comment by dg0yt** [comment]
Sorry, no x64-windows toolchain locally. But a blue screen is more likely to be hardware issue than a software nowadays. No user-space software is allowed to tear down the whole system with "Kernel mode heap corruption".

**Comment by JackBoosY** [comment]
GPU is not required to build ffmpeg.

**Comment by cenit** [comment]
can you please remove gpu drivers?
heap corruption looks like a driver is using memory it should not, and building the program overwrites it (because it's not system protected since it does not belong to the driver from the beginning)

**Comment by JackBoosY** [comment]
Yes, that's seems like a gpu driver bug.

**Comment by JackBoosY** [comment]
Anyway, I think this is not related to vcpkg.

**Comment by ThomasWilshaw** [comment]
Okay, well thanks everyone for all your help :) I'll post back here if I fond a solution or have any meaningful updates in case anyone else has the same issue.

**Comment by ThomasWilshaw** [comment]
To follow up on this, as og the latest master (ba383ed) `ffmpeg` now compiles fine for me. There have been a few `ffmpeg` related commits since I last tried so one of them may have fixed it. Equally whilst I haven't deliberately tried to fix this on my end something may have changed in my setup, I don't know.
