### ISSUE TITLE
curl: (6) Could not resolve host: github.com

### ISSUE THREAD

**Issue by dodoaska** [microsoft/vcpkg#20482]
└─$ sudo bash bootstrap-vcpkg.sh                                                                                     1 ⨯
Downloading cmake...
curl: (6) Could not resolve host: github.com
curl: (6) Could not resolve host: github.com
curl: (6) Could not resolve host: github.com
curl: (6) Could not resolve host: github.com
                                                                                                                         
?>????

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
