### ISSUE TITLE
[tensorflow:x86-windows] build failure

### ISSUE THREAD

**Issue by etolgad** [microsoft/vcpkg#20507]
**Host Environment**
- OS:  Windows 10 64bit 

**To Reproduce**
./vcpkg install tensorflow

**Failure logs** 
CMake Error at scripts/cmake/vcpkg_fail_port_install.cmake:96 (message):
  Architecture 'x86' not supported by tensorflow!

Call Stack (most recent call first):
  ports/tensorflow/portfile.cmake:1 (vcpkg_fail_port_install)
  scripts/ports.cmake:141 (include)

Error: Building package tensorflow:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: tensorflow:x86-windows
  Vcpkg version: 2021-09-10-2059ef11aa6067e6f59b0d939c5d17e3c5c47d3e

**Comment by FabianLorenzo** [comment]
./vcpkg install tensorflow --triplet x64-windows
for x64 architecture windows

**Comment by etolgad** [comment]
It failed again.

 Command failed: C:/dev/vcpkg/vcpkg/downloads/tools/msys2/5ac3933426d8437e/usr/bin/bash.exe --noprofile --norc -c "'C:/dev/vcpkg/vcpkg/downloads/tools/bazel/4.1.0-windows/bazel.exe' --output_user_root='C:/dev/vcpkg/vcpkg/buildtrees/tensorflow/.bzl' --max_idle_secs=1 build --verbose_failures --compilation_mode=dbg --features=fastbuild    --python_path='C:/dev/vcpkg/vcpkg/downloads/tools/msys2/5ac3933426d8437e/mingw64/bin/python3.exe' --define=no_tensorflow_py_deps=true ///tensorflow:tensorflow.dll ///tensorflow:install_headers"
    Working Directory: C:/dev/vcpkg/vcpkg/buildtrees/tensorflow/x64-windows-dbg
    See logs for more information:
      C:\dev\vcpkg\vcpkg\buildtrees\tensorflow\build-x64-windows-dbg-err.log

Call Stack (most recent call first):
  installed/x64-windows/share/tensorflow-common/tensorflow-common.cmake:237 (vcpkg_execute_build_process)
  ports/tensorflow/portfile.cmake:7 (include)
  scripts/ports.cmake:141 (include)


Error: Building package tensorflow:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: tensorflow:x64-windows
  Vcpkg version: 2021-09-10-2059ef11aa6067e6f59b0d939c5d17e3c5c47d3e

Additionally, attach any relevant sections from the log files above.

**Comment by etolgad** [comment]
It failed again.

 Command failed: C:/dev/vcpkg/vcpkg/downloads/tools/msys2/5ac3933426d8437e/usr/bin/bash.exe --noprofile --norc -c "'C:/dev/vcpkg/vcpkg/downloads/tools/bazel/4.1.0-windows/bazel.exe' --output_user_root='C:/dev/vcpkg/vcpkg/buildtrees/tensorflow/.bzl' --max_idle_secs=1 build --verbose_failures --compilation_mode=dbg --features=fastbuild    --python_path='C:/dev/vcpkg/vcpkg/downloads/tools/msys2/5ac3933426d8437e/mingw64/bin/python3.exe' --define=no_tensorflow_py_deps=true ///tensorflow:tensorflow.dll ///tensorflow:install_headers"
    Working Directory: C:/dev/vcpkg/vcpkg/buildtrees/tensorflow/x64-windows-dbg
    See logs for more information:
      C:\dev\vcpkg\vcpkg\buildtrees\tensorflow\build-x64-windows-dbg-err.log

Call Stack (most recent call first):
  installed/x64-windows/share/tensorflow-common/tensorflow-common.cmake:237 (vcpkg_execute_build_process)
  ports/tensorflow/portfile.cmake:7 (include)
  scripts/ports.cmake:141 (include)


Error: Building package tensorflow:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: tensorflow:x64-windows
  Vcpkg version: 2021-09-10-2059ef11aa6067e6f59b0d939c5d17e3c5c47d3e

Additionally, attach any relevant sections from the log files above.

**Comment by FabianLorenzo** [comment]
Please provide the log in C:\dev\vcpkg\vcpkg\buildtrees\tensorflow\build-x64-windows-dbg-err.log

**Comment by etolgad** [comment]
[build-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/7284050/build-x64-windows-dbg-err.log)

**Comment by FabianLorenzo** [comment]
```
ERROR: Analysis of target '//tensorflow:tensorflow.dll' failed; build aborted: error loading package '@bazel_tools//tools/jdk': Package 'tools/jdk' contains errors
```

jdk seems to be the culprit, would need someone from the package to inform what is happening

**Comment by JackBoosY** [comment]
```
ERROR: C:/dev/vcpkg/vcpkg/buildtrees/tensorflow/x64-windows-dbg/tensorflow/c/BUILD:503:11: In rule 'tf_status_helper_test', size 'medium' is not a valid size.
ERROR: C:/dev/vcpkg/vcpkg/buildtrees/tensorflow/x64-windows-dbg/tensorflow/c/BUILD:503:11: In rule 'tf_status_helper_test', timeout 'illegal' is not a valid timeout.
ERROR: C:/dev/vcpkg/vcpkg/buildtrees/tensorflow/x64-windows-dbg/tensorflow/c/BUILD:686:11: In rule 'c_test', size 'medium' is not a valid size.
ERROR: C:/dev/vcpkg/vcpkg/buildtrees/tensorflow/x64-windows-dbg/tensorflow/c/BUILD:686:11: In rule 'c_test', timeout 'illegal' is not a valid timeout.
ERROR: C:/dev/vcpkg/vcpkg/buildtrees/tensorflow/x64-windows-dbg/tensorflow/c/BUILD:753:11: In rule 'c_api_experimental_test', size 'medium' is not a valid size.
ERROR: C:/dev/vcpkg/vcpkg/buildtrees/tensorflow/x64-windows-dbg/tensorflow/c/BUILD:753:11: In rule 'c_api_experimental_test', timeout 'illegal' is not a valid timeout.
ERROR: C:/dev/vcpkg/vcpkg/buildtrees/tensorflow/.bzl/xpz6vyzm/external/bazel_tools/tools/jdk/BUILD:465:8: In rule 'proguard_whitelister_test', size 'medium' is not a valid size.
ERROR: C:/dev/vcpkg/vcpkg/buildtrees/tensorflow/.bzl/xpz6vyzm/external/bazel_tools/tools/jdk/BUILD:465:8: In rule 'proguard_whitelister_test', timeout 'illegal' is not a valid timeout.
```

**Comment by LilyWangLL** [comment]
@etolgad Does this issue still exist? If this issue still exist, according to Joachim's suggestion, you need check a conflicting Java (or Bazel) installation in the PATH but outside vcpkg.

**Comment by etolgad** [comment]
No, it doesn't exist anymore. I am not using vcpkg at the moment. Thank you all for helping.

**Comment by LilyWangLL** [comment]
Thanks for your reply. This issue doesn't exist, so I am closing this issue for now.
