### ISSUE TITLE
[kcp] update to 20210610

### ISSUE THREAD

**Issue by Aoi-hosizora** [microsoft/vcpkg#20510]
Library name: skywind3000/kcp

New version number: 20210610 (current version is 20190920)

Current newest version: https://github.com/skywind3000/kcp/tree/58139efbbaa6fc82a451b780b05d37fb41f21d15

**Comment by JonLiu1993** [comment]
@Aoi-hosizora ,Thanks for posting this issue, The stable release version of kcp is v1.7. We usually update version to the latest stable version. Unless the user has specific needs, we will use the latest commit update.
