### ISSUE TITLE
opencv4:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by acamporeale** [microsoft/vcpkg#20543]
**Host Environment**
- OS: Windows 10 64bit
- Compiler: Visual Studio 2019 environment with C++ workload

**To Reproduce**
.\vcpkg\vcpkg install opencv:x64-windows

**Failure logs** 
Error: Building package opencv4:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: opencv4:x64-windows
  Vcpkg version: 2021-09-10-2059ef11aa6067e6f59b0d939c5d17e3c5c47d3e

Additionally, attach any relevant sections from the log files above.

C:\Users\Mixdas>.\vcpkg\vcpkg update
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.

**Additional context**

I attach the full log:

[full_log.txt](https://github.com/microsoft/vcpkg/files/7291523/full_log.txt)

**Comment by dg0yt** [comment]
According to the log, please provide `C:\Users\Mixdas\vcpkg\buildtrees\opencv4\install-x64-windows-dbg-out.log`

**Comment by Stevenliu520** [comment]
I have same problem

**Comment by JackBoosY** [comment]
@Stevenliu520 Please provide the failure log first.

**Comment by JackBoosY** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
