### ISSUE TITLE
Make PCL's Qt and VTK dependencies optional

### ISSUE THREAD

**Issue by bjornpiltz** [Microsoft/vcpkg#2054]
I stumbled upon the `Feature:` specification in the boost CONTROL file.

```
Source: boost
Version: 1.65.1-1
Description: Peer-reviewed portable C++ source libraries
Build-Depends: zlib, bzip2

Feature: locale-icu
Description: ICU backend for Boost.Locale
Build-Depends: icu

Feature: regex-icu
Description: ICU support for Boost.Regex
Build-Depends: icu

Feature: python
Description: a C++ library which enables seamless interoperability between C++ and the Python programming language.
Build-Depends: python3
```

Could this be used for a feature called gui/visualization/apps or something similar. This would save a lot of time and space for people only interested in using PCL as a library.

**Comment by UnaNancyOwen** [comment]
The visualization module should be enabled by default, because most developers need visualization features.
In order to implement option to disable visualization module, I think that it is necessary to add a "without feature option" to vcpkg install command.

If you want to disable visualization module now, Please rewrite [CONTROL#L3](https://github.com/Microsoft/vcpkg/blob/master/ports/pcl/CONTROL#L3) and [portfile.cmake#L38-58](https://github.com/Microsoft/vcpkg/blob/master/ports/pcl/portfile.cmake#L38-L58).

```patch
- Build-Depends: boost, eigen3, flann, qhull, vtk, openni2, qt5, winpcap
+ Build-Depends: boost, eigen3, flann, qhull, openni2, winpcap
```
```patch
vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA
    OPTIONS
        # BUILD
        -DBUILD_surface_on_nurbs=ON
        -DBUILD_tools=OFF
+       -DBUILD_visualization=OFF
        # PCL
        -DPCL_BUILD_WITH_BOOST_DYNAMIC_LINKING_WIN32=${LIBRARY_LINKAGE}
        -DPCL_BUILD_WITH_FLANN_DYNAMIC_LINKING_WIN32=${LIBRARY_LINKAGE}
        -DPCL_SHARED_LIBS=${LIBRARY_LINKAGE}
        # WITH
        -DWITH_CUDA=OFF
        -DWITH_LIBUSB=OFF
        -DWITH_OPENNI2=ON
        -DWITH_PCAP=ON
        -DWITH_PNG=OFF
        -DWITH_QHULL=ON
-       -DWITH_QT=ON
-       -DWITH_VTK=ON
+       -DWITH_QT=OFF
+       -DWITH_VTK=OFF
)
```

**Comment by bjornpiltz** [comment]
I'm fine with visualization being enabled by default. I just want to be able to turn it off since the costs of Qt/VTK are not trivial:
```
vcpkg
├── [    66,4 GB]  buildtrees
│   ├── [    22,6 GB]  qt5
│   ├── [    14,7 GB]  pcl
│   ├── [    11,5 GB]  vtk
│   ├── [     4,2 GB]  boost
...
├── [    10,4 GB]  packages
│   ├── [     5,7 GB]  vtk
│   ├── [     1,7 GB]  qt5
│   ├── [     1,3 GB]  boost
│   ├── [     390 MB]  pcl
```
 I just realized that the "Feature"-feature is still at [the proposal stage](https://github.com/Microsoft/vcpkg/pull/1205), but they are suggesting the keyword `[core]` for deselecting all default packages.

**Comment by UnaNancyOwen** [comment]
@bjornpiltz PCL port and VTK port implemented the install options.
You can install PCL without Qt (and WinPCAP) by default.
It will be able to reduce capacity considerably than before.
```
vcpkg install pcl
```
If you want to build PCL with these options, Please add features with install commands.
```
vcpkg install pcl[qt,pcap] --featurepackages
```
