### ISSUE TITLE
Installing cpprestsdk:x86-windows | Building package brotli:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by vibhug** [microsoft/vcpkg#20547]
C:\src\vcpkg>vcpkg install cpprestsdk:x86-windows
Computing installation plan...
The following packages will be built and installed:
  * brotli[core]:x86-windows -> 1.0.9#2
    cpprestsdk[brotli,compression,core,default-features]:x86-windows -> 2.10.18
  * zlib[core]:x86-windows -> 1.2.11#12
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x86-windows...
Restored 0 packages from C:\Users\vibhu.gupta\AppData\Local\vcpkg\archives in 245.4 us. Use --debug to see more details.
Starting package 1/3: brotli:x86-windows
Building package brotli[core]:x86-windows...
-- Downloading https://github.com/google/brotli/archive/e61745a6b7add50d380cfd7d3883dd6c62fc2c71.tar.gz -> google-brotli-e61745a6b7add50d380cfd7d3883dd6c62fc2c71.tar.gz...
-- Cleaning sources at C:/src/vcpkg/buildtrees/brotli/src/6c62fc2c71-7c6c2710e9.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/src/vcpkg/downloads/google-brotli-e61745a6b7add50d380cfd7d3883dd6c62fc2c71.tar.gz
-- Applying patch install.patch
-- Applying patch fix-arm-uwp.patch
-- Applying patch pkgconfig.patch
-- Applying patch fix-ios.patch
-- Using source at C:/src/vcpkg/buildtrees/brotli/src/6c62fc2c71-7c6c2710e9.clean
-- Found external ninja('1.10.2').
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: ninja -v
    Working Directory: C:/src/vcpkg/buildtrees/brotli/x86-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\src\vcpkg\buildtrees\brotli\config-x86-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:368 (vcpkg_execute_required_process)
  ports/brotli/portfile.cmake:14 (vcpkg_configure_cmake)
  scripts/ports.cmake:141 (include)

Error: Building package brotli:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: brotli:x86-windows
[config-x86-windows-out.log](https://github.com/microsoft/vcpkg/files/7292675/config-x86-windows-out.log)
  Vcpkg version: 2021-09-10-2059ef11aa6067e6f59b0d939c5d17e3c5c47d3e

Additionally, attach any relevant sections from the log files above.

[CMakeCache.txt](https://github.com/microsoft/vcpkg/files/7292689/CMakeCache.txt)
[CMakeError.log](https://github.com/microsoft/vcpkg/files/7292693/CMakeError.log)
[CMakeOutput.log](https://github.com/microsoft/vcpkg/files/7292695/CMakeOutput.log)
[config-x86-windows-out.log](https://github.com/microsoft/vcpkg/files/7292683/config-x86-windows-out.log)

**Comment by vibhug** [comment]
Relevant section of C:\src\vcpkg\buildtrees\brotli\config-x86-windows-out.log

CMake Error at C:/src/vcpkg/downloads/tools/cmake-3.21.1-windows/cmake-3.21.1-windows-i386/share/cmake-3.21/Modules/CMakeTestCXXCompiler.cmake:62 (message):
  The C++ compiler
    "C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe"
  is not able to compile a simple test program.
  It fails with the following output:

    Change Dir: C:/src/vcpkg/buildtrees/gflags/x64-windows-rel/	
    
    Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe cmTC_34bb9 && [1/2] Building CXX object CMakeFiles\cmTC_34bb9.dir\testCXXCompiler.cxx.obj
    [2/2] Linking CXX executable cmTC_34bb9.exe
    FAILED: cmTC_34bb9.exe 
    cmd.exe /C "cd . && C:\src\vcpkg\downloads\tools\cmake-3.21.1-windows\cmake-3.21.1-windows-i386\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_34bb9.dir --rc=rc --mt=CMAKE_MT-NOTFOUND --manifests  -- C:\PROGRA~2\MICROS~2\2019\PROFES~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\link.exe /nologo CMakeFiles\cmTC_34bb9.dir\testCXXCompiler.cxx.obj  /out:cmTC_34bb9.exe /implib:cmTC_34bb9.lib /pdb:cmTC_34bb9.pdb /version:0.0 /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    RC Pass 1: command "rc /fo CMakeFiles\cmTC_34bb9.dir/manifest.res CMakeFiles\cmTC_34bb9.dir/manifest.rc" failed (exit code 0) with the following output:
    The system cannot find the file specified
    ninja: build stopped: subcommand failed.

It does not mention which file it can not find.

**Comment by vibhug** [comment]
Above log suggest to:

See also "C:/src/vcpkg/buildtrees/gflags/x64-windows-rel/CMakeFiles/CMakeOutput.log".
See also "C:/src/vcpkg/buildtrees/gflags/x64-windows-rel/CMakeFiles/CMakeError.log".

CMakeOutput.log shows success:

The system is: Windows - 10.0.19042 - AMD64
Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.

---------
CMakeError.log says compilation of same file failed. ( Self contradicting)

Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x86/cl.exe 
Build flags: ;/nologo;/DWIN32;/D_WINDOWS;/W3;/utf-8;/MP;
Id flags:  

The output was:
2
CMakeCCompilerId.c
LINK : fatal error LNK1104: cannot open file 'kernel32.lib'


Detecting C compiler ABI info failed to compile with the following output:
Change Dir: C:/src/vcpkg/buildtrees/brotli/x86-windows-rel/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe cmTC_9458f && [1/2] Building C object CMakeFiles\cmTC_9458f.dir\CMakeCCompilerABI.c.obj

[2/2] Linking C executable cmTC_9458f.exe

FAILED: cmTC_9458f.exe 

cmd.exe /C "cd . && C:\src\vcpkg\downloads\tools\cmake-3.21.1-windows\cmake-3.21.1-windows-i386\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_9458f.dir --rc=rc --mt=CMAKE_MT-NOTFOUND --manifests  -- C:\PROGRA~2\MICROS~2\2019\PROFES~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x86\link.exe /nologo CMakeFiles\cmTC_9458f.dir\CMakeCCompilerABI.c.obj  /out:cmTC_9458f.exe /implib:cmTC_9458f.lib /pdb:cmTC_9458f.pdb /version:0.0 /machine:X86  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."

RC Pass 1: command "rc /fo CMakeFiles\cmTC_9458f.dir/manifest.res CMakeFiles\cmTC_9458f.dir/manifest.rc" failed (exit code 0) with the following output:
The system cannot find the file specified

ninja: build stopped: subcommand failed.

**Comment by vibhug** [comment]
kernel32.lib is very much present.
I even reinstalled Windows SDK 10 as well as 11 and rebooted, still same error.
I installed via Visual Studio Installer, same error.
Uninstalled and then reinstalled WindowsSDK , with rebooting, still same error.
Disabled Anti Virus, still same error.
Interestingly, same cpprestsdk was able to compile on another windows10 laptop, but i need to do it on this office laptop.

Please advise if i need to attach more information.

**Comment by dg0yt** [comment]
> ```
> RC Pass 1: command "rc /fo CMakeFiles\cmTC_34bb9.dir/manifest.res CMakeFiles\cmTC_34bb9.dir/manifest.rc" failed (exit code 0) with the following output:
> The system cannot find the file specified
> ninja: build stopped: subcommand failed.
> ```
> 
> 
>     
>   
> 
> It does not mention which file it can not find.

Looks like `rc` is not on the PATH.  Does this help: https://gitlab.kitware.com/cmake/cmake/-/issues/19054 ?

**Comment by vibhug** [comment]
> > RC Pass 1: command "rc /fo CMakeFiles\cmTC_34bb9.dir/manifest.res CMakeFiles\cmTC_34bb9.dir/manifest.rc" failed (exit code 0) with the following output:
> > The system cannot find the file specified
> > ninja: build stopped: subcommand failed.
   
> > It does not mention which file it can not find.
> 
> Looks like `rc` is not on the PATH. Does this help: https://gitlab.kitware.com/cmake/cmake/-/issues/19054 ?
----------------------
With thanks for responding, I tried following.

- Added path of rc.exe in PATH variable.   (same error persist)

>where rc
C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x86\rc.exe

>which rc
/c/Program Files (x86)/Windows Kits/10/bin/10.0.19041.0/x86/rc
---------
-  Above the error of file not found of "rc" there is another suspect "LINK : fatal error LNK1104: cannot open file 'kernel32.lib'"
- As per the defect 19054 shared, i added path of kernel32.lib in a "LIB" environment variable. 
>where $LIB:kernel32.lib
C:\Program Files (x86)\Windows Kits\10\Lib\10.0.19041.0\um\x86\kernel32.Lib
- Same error persist.
----------
Removed al WindowsSDK, Removed Visual Studio, and Reinstalled VS 2019 Professional.
Enabled Desktop C++ feature, and enabled almost all the optional individual tick marks.
Same error persist.
----------
- Also ran 	Call “C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Auxiliary\Build\vcvars.32.bat”
- Same error persist.
----------

**Comment by NancyLi1013** [comment]
Sorry for the late response. I noticed you have tried to reinstalled SDK 10 and Visual Studio, but it still failed with the same error.

Sorry, I also have no idea about this. So you cannot install any ports on your machine, right?

May be you can try another suggestion like this. Uninstall Windows SDK 10 and Visual Studio at the same time and then install them again. please try to clone vcpkg to a new repo.

**Comment by vibhug** [comment]
@NancyLi1013 
I have reinstalled both VS and SDK, nothing works.
It wasted several days of project, and put me under immense timeline pressures.
Finally i tried the NuGet package, and that helped me move ahead in project.
Suprisingly, i read somewhere that NuGet is deprecated in favor of vcpkg.  Whereas its NuGet that became my lifeline.
This VCPKG is still unsolved after ONE MONTH :-)

**Comment by NancyLi1013** [comment]
Sorry that I didn't help you solve the problem.

For NuGet, it is not deprecated in vcpkg, you can still use it.

https://github.com/microsoft/vcpkg/blob/master/docs/users/integration.md

https://devblogs.microsoft.com/cppblog/vcpkg-introducing-export-command/

**Comment by JackBoosY** [comment]
See https://github.com/microsoft/vcpkg/pull/22214.
