### ISSUE TITLE
[folly] update to v2021.10.04.00

### ISSUE THREAD

**Issue by qinix** [microsoft/vcpkg#20558]
Library name: folly

New version number: v2021.10.04.00

Other information that may be useful (release notes, etc...)

https://github.com/facebook/folly/releases/tag/v2021.10.04.00

**Comment by cmachaca** [comment]
Hello, there are facebook libraries that were not updated. Please also update them.

**Comment by JonLiu1993** [comment]
> Hello, there are facebook libraries that were not updated. Please also update them.

@cmachaca, Could you please open a issue about update facebook? we will commit a pr fix it.
