### ISSUE TITLE
Boost.Test libs not moved to manual link

### ISSUE THREAD

**Issue by iskiselev** [Microsoft/vcpkg#2057]
Boost.Test libs are not moved to manual link.
Created lib files are: boost_test_exec_monitor-vc140-mt-1_65_1.lib, boost_prg_exec_monitor-vc140-mt-1_65_1.lib, so they include ${VERSION_FULL}, but portfile looks for lib with just ${VERSION} at the end.

**Comment by iskiselev** [comment]
BTW, shouldn't boost_prg_exec_monitor be also placed in manual-link?
When I try to compile Boost Test (static linking) with boost_prg_exec_monitor in lib folder, it results in:
```
 boost_prg_exec_monitor-vc140-mt-1_65_1.lib(cpp_main.obj) : error LNK2001: unresolved external symbol "int __cdecl cpp_main(int,char * * const)" (?cpp_main@@YAHHQEAPEAD@Z)
```
It works if I move it to manual link folder.

**Comment by ras0219-msft** [comment]
Thanks! I've pushed e3dcfcb4 to master.
