### ISSUE TITLE
proj/ proj4 update to 8.1.1

### ISSUE THREAD

**Issue by Cazadorro** [microsoft/vcpkg#20578]
Library name: PROJ [listed as proj4]

New version number: 8.1.1

Other information that may be useful (release notes, etc...)

8.1.1 is the latest stable release, PROJ 8.0 included the release of an important feature for topocentric coordinate transforms, current version in vcpkg is PROJ 7.2.1.  Topocentric coordinate transforms is a required feature for our codebase, thus prevents us from using VCPKG to manage this dependency until PROJ gets updated.

**Comment by Cazadorro** [comment]
I'm not sure why that means a "proj8" can't exist, or proj, or proj8.1.1 or what ever.

**Comment by PhoebeHui** [comment]
Closing in favor of https://github.com/microsoft/vcpkg/issues/19910.

**Comment by dg0yt** [comment]
> I'm not sure why that means a "proj8" can't exist, or proj, or proj8.1.1 or what ever.
 
Look at the existing issues and PRs. I repeatedly proposed to have a modern "proj" separate from legacy "proj4" . But it isn't easy with vcpkg providing a "single integrated universe" where alternatives are usually not feasible:
With vtk[all] depending on gdal, this port needs to use the legacy proj, too. This chain continues with libgeotiff. And with libgeotiff and gdal, the legacy proj dependent would get into most other ports which use proj.

Note the draft at https://github.com/microsoft/vcpkg/pull/16494.

**Comment by Cazadorro** [comment]
Should proj even be able to be used as a standalone library then with all these issues?  I just realized that this is a thing: https://github.com/microsoft/vcpkg/pull/16169, meaning the utility of proj is cut at the knees with both versioning and the ability to even perform transforms.
