### ISSUE TITLE
[arrayfire] build failure

### ISSUE THREAD

**Issue by felixt56** [microsoft/vcpkg#20595]
**Host Environment**
- OS: Linux Mint
- Compiler: gcc version 9.3.0

**To Reproduce**
`./vcpkg install arrayfire[cpu]

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: /home/ft/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/bin/cmake /home/ft/vcpkg/buildtrees/arrayfire/src/86c948954d-c996b9f837.clean -DBUILD_TESTING=OFF -DAF_BUILD_DOCS=OFF -DAF_BUILD_EXAMPLES=OFF -DUSE_CPU_MKL=ON -DUSE_OPENCL_MKL=ON -DAF_CPU_THREAD_PATH=/home/ft/vcpkg/buildtrees/arrayfire/src/7005e85d9a-64aebcce4b.clean -DAF_FORGE_PATH=/home/ft/vcpkg/buildtrees/arrayfire/src/9c95132389-511398ace8.clean -DAF_BUILD_FORGE=OFF -DAF_INSTALL_CMAKE_DIR=/home/ft/vcpkg/packages/arrayfire_x64-linux/share/arrayfire -DAF_BUILD_UNIFIED=ON -DAF_BUILD_CPU=ON -DAF_BUILD_CUDA=OFF -DAF_BUILD_OPENCL=OFF -DCMAKE_MAKE_PROGRAM=/home/ft/vcpkg/downloads/tools/ninja-1.10.2-linux/ninja -DCMAKE_SYSTEM_NAME=Linux -DBUILD_SHARED_LIBS=OFF -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/home/ft/vcpkg/scripts/toolchains/linux.cmake -DVCPKG_TARGET_TRIPLET=x64-linux -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=external -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=/home/ft/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_LINKER_FLAGS_RELEASE= -DVCPKG_LINKER_FLAGS_DEBUG= -DVCPKG_TARGET_ARCHITECTURE=x64 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -D_VCPKG_ROOT_DIR=/home/ft/vcpkg -D_VCPKG_INSTALLED_DIR=/home/ft/vcpkg/installed -DVCPKG_MANIFEST_INSTALL=OFF -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/home/ft/vcpkg/packages/arrayfire_x64-linux/debug
    Working Directory: /home/ft/vcpkg/buildtrees/arrayfire/x64-linux-dbg
    Error code: 1
    See logs for more information:
      /home/ft/vcpkg/buildtrees/arrayfire/config-x64-linux-dbg-out.log
      /home/ft/vcpkg/buildtrees/arrayfire/config-x64-linux-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:381 (vcpkg_execute_required_process)
  ports/arrayfire/portfile.cmake:69 (vcpkg_configure_cmake)
  scripts/ports.cmake:141 (include)
Error: Building package arrayfire:x64-linux failed with: BUILD_FAILED

-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue
[config-x64-linux-dbg-err.log](https://github.com/microsoft/vcpkg/files/7310601/config-x64-linux-dbg-err.log)
[config-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/7310602/config-x64-linux-dbg-out.log)

**Comment by JonLiu1993** [comment]
@felixt56, Have you install MKL？
````
CMake Error at CMakeModules/InternalUtils.cmake:10 (message):
  MKL not found
Call Stack (most recent call first):
  src/backend/cpu/CMakeLists.txt:300 (dependency_check)
````

**Comment by JonLiu1993** [comment]
@felixt56 ,Could you test whether this pr #15233 can solve your problem?

**Comment by JonLiu1993** [comment]
Fixed by PR https://github.com/microsoft/vcpkg/pull/29437.
