### ISSUE TITLE
Subdirectories in lib and debug/lib now errors

### ISSUE THREAD

**Issue by adam4813** [Microsoft/vcpkg#206]
The commit 16ecddf is now causing certain packages to install with errors such as GLFW3, openal-soft and spdlog which copy their pkgconfig folder to share, but to remove it from lib and debug/lib folders.

**Comment by ras0219-msft** [comment]
Thanks for reporting this, we should come up with a good solution for pkgconfig files (which may be removing them) and apply this to all the existing ports before reenabling these checks.
