### ISSUE TITLE
Boost partial libs

### ISSUE THREAD

**Issue by SergeyVSB** [Microsoft/vcpkg#2060]
It's more question, than issue.

What should I do, if I need
(first part)
static lib with static release CRT
static lib with shared release CRT
shared lib with shared debug CRT

(second part)
Only iostreams, system and filesystem libs?

**Comment by ras0219-msft** [comment]
For the first part, you can build these with separate triplets:
```
vcpkg install boost:x64-windows boost:x64-windows-static boost:x64-windows-static-md
```

`x64-windows` is shared/shared, `x64-windows-static` is static/static, and you'll need to create the third on your own if you want it. See https://github.com/Microsoft/vcpkg/blob/master/docs/users/triplets.md for more information.

For the second part, we currently don't have a way to (from the command line) disable components of boost. However, you could modify `ports\boost\portfile.cmake` and add more `--without-x` options if you really want to trim it down.
