### ISSUE TITLE
[boost-compute] build failuPackage: boost-compute:x86-windows   Vcpkg version: 2021-09-10-2059ef11aa6067e6f59b0d939c5d17e3c5c47d3ere

### ISSUE THREAD

**Issue by TaiQiX** [microsoft/vcpkg#20601]
Package: boost-compute:x86-windows
  Vcpkg version: 2021-09-10-2059ef11aa6067e6f59b0d939c5d17e3c5c47d3e

Additionally, attach any relevant sections from the log files above.

**Comment by PhoebeHui** [comment]
@TaiQiX, please reopen this issue and provide us the failure logs if it still be a problems for you.
