### ISSUE TITLE
[boost] Make #define BOOST_ALL_NO_LIB conditional

### ISSUE THREAD

**Issue by d-komarov** [Microsoft/vcpkg#2061]
If I have a project with ```add_definitions(-DBOOST_ALL_NO_LIB)``` then [portfile.cmake:261](https://github.com/Microsoft/vcpkg/blob/133099fa2c46152474cfab052d0d1bcbc83749f2/ports/boost/portfile.cmake#L261) will result in a ```warning C4005: 'BOOST_ALL_NO_LIB': macro redefinition```

I believe that BOOST_ALL_NO_LIB should be defined like:

```C++
#ifndef BOOST_ALL_NO_LIB
#define BOOST_ALL_NO_LIB
#endif
```

**Comment by ras0219-msft** [comment]
Thanks for posting this issue! It should be fixed in master.
