### ISSUE TITLE
[pixman] build failure for android

### ISSUE THREAD

**Issue by KangLin** [microsoft/vcpkg#20613]
**Host Environment**
- OS: Windows10
- Compiler: ndk-21.3.6528147

**To Reproduce**
`./vcpkg install  --triplet arm-android pixman`

**Failure logs** 
d:\Source\vcpkg>vcpkg install --triplet arm-android pixman
Computing installation plan...
The following packages will be built and installed:
    pixman[core]:arm-android -> 0.40.0
Detecting compiler hash for triplet arm-android...
Warning: The following VS instances are excluded because the English language pack is unavailable.
    C:\Program Files (x86)\Microsoft Visual Studio 12.0\
Please install the English language pack.
Could not locate cached archive: C:\Users\k\AppData\Local\vcpkg\archives\ed\eda48a734f125fe8542e1b107027cf5efe5cedb075a011bb2c199454da79a7fb.zip
Starting package 1/1: pixman:arm-android
Building package pixman[core]:arm-android...
-- Using community triplet arm-android. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: D:\Source\vcpkg\triplets\community\arm-android.cmake
-- Downloading https://www.cairographics.org/releases/pixman-0.40.0.tar.gz -> pixman-0.40.0.tar.gz...
-- Cleaning sources at D:/Source/vcpkg/buildtrees/pixman/src/0.40.0-9a8e17d6df.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/Source/vcpkg/downloads/pixman-0.40.0.tar.gz
-- Applying patch remove_test_demos.patch
-- Using source at D:/Source/vcpkg/buildtrees/pixman/src/0.40.0-9a8e17d6df.clean
-- Getting CMake variables for arm-android
-- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst;https://www2.futureware.at/~nickoe/msys2-mirror/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst;https://mirror.yandex.ru/mirrors/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst;https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst;https://mirrors.ustc.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst;https://mirror.bit.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst;https://mirror.selfnet.de/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst;https://mirrors.sjtug.sjtu.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst -> msys-mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst...
-- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst;https://www2.futureware.at/~nickoe/msys2-mirror/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst;https://mirror.yandex.ru/mirrors/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst;https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst;https://mirrors.ustc.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst;https://mirror.bit.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst;https://mirror.selfnet.de/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst;https://mirrors.sjtug.sjtu.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst -> msys-mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst...
-- Using msys root at D:/Source/vcpkg/downloads/tools/msys2/aa5af7b2aa7e90e8
-- Configuring arm-android-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: D:/Source/vcpkg/downloads/tools/python/python-3.10.0-x64/python.exe D:/Source/vcpkg/downloads/tools/meson/meson-aeda7f249c4a5dbbecc52e44f382246a2377b5b0/meson.py -Dmmx=disabled -Dsse2=disabled -Dssse3=disabled -Dlibpng=enabled --buildtype plain --backend ninja --wrap-mode nodownload --cross D:/Source/vcpkg/buildtrees/pixman/meson-cross-arm-android.log --native D:/Source/vcpkg/scripts/buildsystems/meson/none.txt --default-library static --libdir lib --cross D:/Source/vcpkg/buildtrees/pixman/meson-cross-arm-android-debug.log -Ddebug=true --prefix D:/Source/vcpkg/packages/pixman_arm-android/debug --includedir ../include -Dcmake_prefix_path=['D:/Source/vcpkg/installed/arm-android/debug','D:/Source/vcpkg/installed/arm-android'] D:/Source/vcpkg/buildtrees/pixman/src/0.40.0-9a8e17d6df.clean
    Working Directory: D:/Source/vcpkg/buildtrees/pixman/arm-android-dbg
    Error code: 1
    See logs for more information:
      D:\Source\vcpkg\buildtrees\pixman\config-arm-android-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_meson.cmake:512 (vcpkg_execute_required_process)
  ports/pixman/portfile.cmake:45 (vcpkg_configure_meson)
  scripts/ports.cmake:141 (include)

Error: Building package pixman:arm-android failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: pixman:arm-android
  Vcpkg version: 2021-08-03-1a6d67b8150e94b7f473c6ab1c0cfdd794316a64

Additionally, attach any relevant sections from the log files above.

**Additional context**

The error in D:\Source\vcpkg\buildtrees\pixman\arm-android-dbg\meson-logs\meson-log.txt

```
Sanity check compile stderr:
clang: error: unsupported option '-fPIC' for target 'x86_64-w64-windows-gnu'

```

[config-arm-android-dbg-out.log](https://github.com/microsoft/vcpkg/files/7315291/config-arm-android-dbg-out.log)
[meson-log.txt](https://github.com/microsoft/vcpkg/files/7315290/meson-log.txt)
[CMakeOutput.log](https://github.com/microsoft/vcpkg/files/7315292/CMakeOutput.log)

**Comment by JackBoosY** [comment]
This issue should be fixed, please update vcpkg and try again.

Thanks.
