### ISSUE TITLE
[libraw] Install `raw_r.lib`

### ISSUE THREAD

**Issue by HappySeaFox** [microsoft/vcpkg#20614]
****

**Is your feature request related to a problem? Please describe.**

The port installs two variants of libraw: `raw.dll` and `raw_r.dll` (which is multi-threaded version). However, only one lib variant `raw.lib` is installed.

**Proposed solution**
Install `raw_r.lib` as well.

**Describe alternatives you've considered**
No alternative solutions.

**Additional context**
\-

**Comment by JackBoosY** [comment]
Confirmed.

**Comment by JackBoosY** [comment]
Will be fixed by https://github.com/microsoft/vcpkg/pull/19593.
