### ISSUE TITLE
[New Port Request] <libremidi>

### ISSUE THREAD

**Issue by ericfont** [microsoft/vcpkg#20623]
Library name: libremidi

Library description: A modern C++ MIDI real-time & file I/O library. Supports Windows, macOS, Linux and WebMIDI.

Source repository URL: https://github.com/jcelerier/libremidi

Anything else that is useful to know when adding (such as optional features the library may have that should be included): this is a fork of RtMidi, and since RtMidi is already in vcpkg, I imagine the starting point to port would be just copy and paste the config files from https://github.com/microsoft/vcpkg/tree/master/ports/rtmidi and tweak them.

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.

**Comment by splisp** [comment]
I see that libremidi is now available. It's the first component that I'm trying after installing vcpkg and I have linker issues that may be related to the port or to my inexperience with vcpkg.

I want to use the x64-static version in VS2022 Community. I have set the "Use static libraries" option in my project's vcpkg properties page, and set the RT to static in the Code Generation properties page. In order to link correctly, I still have to

• add the path to the vcpkg binaries in VC++ Directories | Library Directories
• add libremidi.lib to Linker | Input
• also, add winmm.lib to Linker | Input

Now everything builds and runs fine. I think that I should not have to manually add the vcpkg binaries path and the library... should I??? The fact is that I don't see the vcpkg binaries path in the evaluated library path:

![image](https://github.com/microsoft/vcpkg/assets/2437263/284b8393-9c9a-47a4-b656-18bfe2bfe67f)

I have run vcpkg integrate install (as administrator just to be sure); in fact, headers are resolved with no need to manually adjust the include path, and intellisense works for libremidi.

Any help appreciated... thanks!

**Comment by JackBoosY** [comment]
@LilyWangLL Marked port-resolved.

**Comment by JackBoosY** [comment]
Did you try `./vcpkg integrate install` first?

**Comment by splisp** [comment]
> Did you try `./vcpkg integrate install` first?

@JackBoosY yes, I did. I have run vcpkg integrate install (as administrator just to be sure); in fact, headers are resolved with no need to manually adjust the include path, and intellisense works for libremidi.

**Comment by JackBoosY** [comment]
So can you please provide the results of `./vcpkg list libremidi` and which arch do your project use?
Also please provide the build log.

**Comment by splisp** [comment]
> ~So can you please provide the results of `./vcpkg list libremidi` and which arch do your project use? Also please provide the build log.~
> 
> Fine, that's a good news.

Well, I still have the issue of having to manually tweak the project. As I wrote in my first comment, I had already run `./vcpkg integrate install` ahead, before commenting.

**Comment by splisp** [comment]
Here's the result of running `.\vcpkg list libremidi`:

```
libremidi:x64-windows                             4.2.3#1             A modern C++ MIDI real-time & file I/O library
libremidi:x64-windows-static                      4.2.3#1             A modern C++ MIDI real-time & file I/O library
```

This is the build log when I remove both the path from vcpkgs binaries to Library path, and not the name of libremidi.lib from Linker Input:

```
1>------ Build started: Project: libremidi_test_2, Configuration: Debug x64 ------
1>libremidi_test_2.obj : error LNK2019: unresolved external symbol "public: __cdecl libremidi::observer::observer(struct libremidi::observer_configuration)" (??0observer@libremidi@@QEAA@Uobserver_configuration@1@@Z) referenced in function main
1>libremidi_test_2.obj : error LNK2019: unresolved external symbol "public: __cdecl libremidi::observer::~observer(void)" (??1observer@libremidi@@QEAA@XZ) referenced in function main
1>libremidi_test_2.obj : error LNK2019: unresolved external symbol "public: class std::vector<struct libremidi::input_port,class std::allocator<struct libremidi::input_port> > __cdecl libremidi::observer::get_input_ports(void)const " (?get_input_ports@observer@libremidi@@QEBA?AV?$vector@Uinput_port@libremidi@@V?$allocator@Uinput_port@libremidi@@@std@@@std@@XZ) referenced in function main
1>D:\SWDev\MISSILI\libremidi_test_2\x64\Debug\libremidi_test_2.exe : fatal error LNK1120: 3 unresolved externals
1>Done building project "libremidi_test_2.vcxproj" -- FAILED.
```

The path I added to Library directories is `$(VcpkgRoot)\installed\x64-windows-static\debug\lib\static`

**Comment by JackBoosY** [comment]
`__cdecl` is correct in static build. But why the libs are in _lib/static_?
@LilyWangLL Needs to check the build output paths.

**Comment by LilyWangLL** [comment]
> `__cdecl` is correct in static build. But why the libs are in _lib/static_? @LilyWangLL Needs to check the build output paths.

I will confirm it.

**Comment by splisp** [comment]
Looks like the dll is written to the correct path _x64-windows/bin_, but both the import library for the dll and the static library are in a _/static_ subdir (_x64-windows\lib\static_ and _x64-windows-static\lib\static_, and both only contain just _libremidi.lib_). 

I tried and move the static .lib and then I could get rid of my project tweaks. I just have to manually add _winmm.lib_ to _Linker | Input_.

**Comment by jcelerier** [comment]
> but both the import library for the dll

hmm, the install rule in cmake is

```cmake
  install(TARGETS libremidi
          EXPORT libremidi-targets
          ARCHIVE DESTINATION lib/static
          RUNTIME DESTINATION bin
          LIBRARY DESTINATION lib
  )
```

which should install: 
- libremidi.dll in bin/
- libremidi.lib (import library) in lib/static
- libremidi.lib (static library) in lib/static

Would it be better to change: 

```cmake
ARCHIVE DESTINATION lib/static
```

into

```cmake
 ARCHIVE DESTINATION lib
```
?

**Comment by dg0yt** [comment]
`ARCHIVE DESTINATION lib` is the right thing for a tiny patch in vcpkg.
Upstream should use input variables for destinations, ideally those from `GNUInstallDirs`.

**Comment by LilyWangLL** [comment]
PR #34718 will fix the wrong lib path.

**Comment by JackBoosY** [comment]
Anyone encountered this issue can test https://github.com/microsoft/vcpkg/pull/34718 ?

**Comment by splisp** [comment]
> Anyone encountered this issue can test #34718 ?

@JackBoosY I would but I'm not sure how can I test the patch before it's merged. Anyway, I had manually altered my `installed` directory, should I revert the changes I made? Would the patch be able to remove the files in the previous wrong `/static` directory?

**Comment by splisp** [comment]
Ok, I managed to fetch @LilyWangLL 's commits from the PR into my local repository. This is what I have done:

• Reverted the manual adjustments I had made
• `vcpgk remove libremidi`
• the previous command only removed _x64-windows_, so I also ran `vcpgk remove libremidi:x64-windows-static`
• verified that the _lib/static_ folder was gone, and _libremidi.lib_ with it
• cherry-picked the commits
• vcpkg install libremidi:x64-windows-static

_libremidi.lib_ was then found in _lib_ folder and my test project compiles and links, both for debug and release configurations (and with no manual tweaks of the project options).

This workflow didn't allow me to check whether the updated script would be able to remove the _static_ directory. I should have not removed libremidi before merging the PR... I only thought about it later.

**Comment by splisp** [comment]
I was feeling bold, so I removed libremidi after installing it using the patched scripts, reverted the scripts to HEAD, reinstalled libremidi (it went to the wrong _static_ directory), then re-applied the PR, and run `vcpkg upgrade --no-dry-run`. The _static_ directory created by the previous installation was removed, and _libremidi.lib_ was created in the right place in _lib_ alongside other libraries.

```
D:\SWDev\SDKs\vcpkg>vcpkg list libremidi
libremidi:x64-windows-static                      4.2.3#2             A modern C++ MIDI real-time & file I/O library
```

**Comment by jcelerier** [comment]
note that I changed to use gnuinstalldirs in the latest libremidi HEAD commits: https://github.com/jcelerier/libremidi/blob/master/cmake/libremidi.install.cmake

**Comment by totalgee** [comment]
It looks like the `libremidi` port needs to add a dependency for `readerwriterqueue`, at least when the pipewire backend is being used on Linux. I'm not very familiar with vcpkg, so am not sure if it would be enough to just add this to the port file:

```
  "dependencies": [
    {
      "name": "readerwriterqueue",
      "platform": "linux"
    },
    ...
```
