### ISSUE TITLE
[New Port Request] djarek / certify

### ISSUE THREAD

**Issue by mobileFX** [microsoft/vcpkg#20630]
Library name: djarek / certify

Library description: Platform-specific TLS keystore abstraction for use with Boost.ASIO and OpenSSL

Source repository URL: https://github.com/djarek/certify

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

Installing boost beast with vcpkg reports missing includes

#include <boost/certify/extensions.hpp>
#include <boost/certify/https_verification.hpp>

**Comment by autoantwort** [comment]
See #16783

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
