### ISSUE TITLE
OpenCV doesn't install protobuf with custom triplet

### ISSUE THREAD

**Issue by bjornpiltz** [microsoft/vcpkg#2065]
It appears the OpenCV dependency `protobuf (windows)` [here](https://github.com/Microsoft/vcpkg/blob/master/ports/opencv/CONTROL#L4) doesn't trigger when using a custom triplet.
### Error:
```
CMake Error at cmake/OpenCVFindLibProtobuf.cmake:16 (message):
  The protocol buffer compiler is not found
  (Protobuf_PROTOC_EXECUTABLE='Protobuf_PROTOC_EXECUTABLE-NOTFOUND')
Call Stack (most recent call first):
  modules/dnn/CMakeLists.txt:9 (include)
```
### Workaround:
`vcpkg install protobuf`

**Comment by ras0219-msft** [comment]
This is unfortunately a limitation of the current qualifiers system -- they are simply a substring match against the triplet name.

In the short term, another workaround would be to always add suffixes or prefixes to the builtin triplet names.
