### ISSUE TITLE
[PowerShell] version prerequisite

### ISSUE THREAD

**Issue by darke1891** [Microsoft/vcpkg#2067]
Starting from commit 9ddc98988fb8d7c886963fa7568395ecd5785eaa, proxy authorization in [fetchDependency.ps1](https://github.com/Microsoft/vcpkg/blob/master/scripts/fetchDependency.ps1) runs without exception handling.

A problem is, line 54 of this file is as follows:
```powershell
    $ProxyCred = Get-Credential -Message "Enter credentials for Proxy Authentication"
```

As it's said in [document of Powershell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/get-credential?view=powershell-5.1), `-Message` was introduced in PowerShell 3.0. However, default version of PowerShell in Windows 7 is 2.0. So the script can't run in some Windows 7 environments.

This is just a Windows 7 issue, but if the users don't install an update, such as [Windows Management Framework 3.0](https://www.microsoft.com/en-us/download/details.aspx?id=34595), they can't run `bootstrap-vcpkg.bat` successfully.

This should be mentioned somewhere, for example, prerequisites part in readme.md

**Comment by alexkaratarakis** [comment]
I just pushed 83c29df043ce91d37a0c463ed854e78caba53984 that should make it work in Powershell 2.0 (it did work on my VM). 
Please give it a spin and let me know. : )

**Comment by darke1891** [comment]
Hi, I test the newest version on a Win 7 PC with PowerShell 2.0, but it doesn't work.

The error message is `You cannot call a method on a null-valued expression.` on `$PSDefaultParameterValues.Add("Start-BitsTransfer:ProxyAuthentication","Basic")`

Maybe the problem is that `PSDefaultParameterValues` doesn't exist in PowerShell 2.0, as [this doc](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_parameters_default_values?view=powershell-5.1) says.

**Comment by alexkaratarakis** [comment]
Missed that, sorry. It was indeed `PSDefaultParameterValues` and it should be fixed in the latest version. 
Please try once more. :)

(relevant commit: eb7e1e481bbebc13d277d6a89f0a270767962286 )

**Comment by darke1891** [comment]
Hi, I download the newest version `fae64c5` I can find.
Then I try to use it on a PC with Windows 7 and PowerShell 2.0. When I run `bootstrap-vcpkg.bat`, I get error message as follows:
```powershell
Enter credentials for Proxy Authentication

cmdlet Get-Credential at command pipeline position 1
Supply values for the following parameters:
Credential
Enter credentials for Proxy Authentication

cmdlet Get-Credential at command pipeline position 1
Supply values for the following parameters:
Credential
Exception calling "Substring" with "2" argument(s): "Index and length must refer to a location within the string.
Parameter name: length"
At D:\Hao\dev\vcpkg\scripts\findAnyMSBuildWithCppPlatformToolset.ps1:28 char:39
+     $majorVersion = $version.Substring <<<< (0,2);
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DotNetMethodException
```

**Comment by alexkaratarakis** [comment]
That does not seem to be a Win7/Powershell2.0 issue, but something else.
Do you have Visual Studio installed? Which version? Try running:
```
.\scripts\findVisualStudioInstallationInstances.ps1 -Verbose
```
and
```
.\scripts\findAnyMSBuildWithCppPlatformToolset.ps1 -Verbose
```

Paste the output here.

**Comment by darke1891** [comment]
Well, you are right.
I'm sorry that I try to run `vcpkg` on a remote machine, which don't have Visual Studio. I have installed PowerShell 3.0 on my PC, so I can't test it on my environment.
So, maybe this issue can be closed.
