### ISSUE TITLE
[boost-regex:x64-windows] build failure

### ISSUE THREAD

**Issue by zachsucking** [microsoft/vcpkg#20707]
**Host Environment**
- OS: Windows 10 20H2
- Compiler: MSVC v142 VS2019 C++ x64/x86 Build Tools

**To Reproduce**
`./vcpkg install --triplet x64-windows gtest eigen3 benchmark boost`

**Failure logs** 
-- Downloading https://github.com/boostorg/regex/archive/boost-1.77.0.tar.gz -> boostorg-regex-boost-1.77.0.tar.gz...
-- Cleaning sources at D:/dev/vcpkg/buildtrees/boost-regex/src/ost-1.77.0-3dc3b8cc79.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/dev/vcpkg/downloads/boostorg-regex-boost-1.77.0.tar.gz
-- Using source at D:/dev/vcpkg/buildtrees/boost-regex/src/ost-1.77.0-3dc3b8cc79.clean
-- Including D:/dev/vcpkg/ports/boost-regex/b2-options.cmake
-- Found external ninja('1.10.2').
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:155 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j5
    Working Directory: D:/dev/vcpkg/buildtrees/boost-regex/x64-windows-dbg
    See logs for more information:
      D:\dev\vcpkg\buildtrees\boost-regex\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:102 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
  installed/x64-windows/share/boost-build/boost-modular-build.cmake:96 (vcpkg_cmake_install)
  ports/boost-regex/portfile.cmake:15 (boost_modular_build)
  scripts/ports.cmake:141 (include)

**Additional context**
Attach log:
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/7335465/install-x64-windows-dbg-out.log)
Besides,`install-x64-windows-dbg-err.log` is empty.
Could anybody help me?

**Comment by dg0yt** [comment]
Parallel builds are controlled by `VCPKG_MAX_CONCURRENCY`.
https://github.com/microsoft/vcpkg/blob/master/docs/users/config-environment.md#vcpkg_max_concurrency

**Comment by zachsucking** [comment]
@PhoebeHui Well,I've installed the pack.
@FaFoYX Not yet  :(

That's the jam file.
```
import toolset ;

if "v142" != "external"
{
    using msvc : 142 : cl.exe
        :
        <setup>"D:/dev/vcpkg/installed/x64-windows/share/boost-build/nothing.bat"
        <cxxflags>/nologo <cxxflags>/DWIN32 <cxxflags>/D_WINDOWS <cxxflags>/W3 <cxxflags>/utf-8 <cxxflags>/GR <cxxflags>/EHsc <cxxflags>/MP <cxxflags> <cxxflags>/D_DEBUG <cxxflags>/MDd <cxxflags>/Z7 <cxxflags>/Ob0 <cxxflags>/Od <cxxflags>/RTC1
        <cflags>/nologo <cflags>/DWIN32 <cflags>/D_WINDOWS <cflags>/W3 <cflags>/utf-8 <cflags>/MP <cflags> <cflags>/D_DEBUG <cflags>/MDd <cflags>/Z7 <cflags>/Ob0 <cflags>/Od <cflags>/RTC1
        <linkflags>/machine:x64 <linkflags>/nologo <linkflags> <linkflags> <linkflags> <linkflags>/debug <linkflags>/INCREMENTAL
        ;
}
else
{
    using msvc : : D:/VisualStudio2019/VisualStudio2019BuildTool/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe
        :
        <ranlib>:
        <archiver>D:/VisualStudio2019/VisualStudio2019BuildTool/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/lib.exe
        <cxxflags>/nologo <cxxflags>/DWIN32 <cxxflags>/D_WINDOWS <cxxflags>/W3 <cxxflags>/utf-8 <cxxflags>/GR <cxxflags>/EHsc <cxxflags>/MP <cxxflags> <cxxflags>/D_DEBUG <cxxflags>/MDd <cxxflags>/Z7 <cxxflags>/Ob0 <cxxflags>/Od <cxxflags>/RTC1
        <cflags>/nologo <cflags>/DWIN32 <cflags>/D_WINDOWS <cflags>/W3 <cflags>/utf-8 <cflags>/MP <cflags> <cflags>/D_DEBUG <cflags>/MDd <cflags>/Z7 <cflags>/Ob0 <cflags>/Od <cflags>/RTC1
        <linkflags>/machine:x64 <linkflags>/nologo <linkflags> <linkflags> <linkflags> <linkflags>/debug <linkflags>/INCREMENTAL
        # MINGW here causes b2 to not run cygpath
        <flavor>mingw
        ;
}

if "boost-regex" = "boost-python"
{
    using python :  : : "" : "" ;
    using python :  : : "" : "" : <python-debugging>on ;
    using python :  : : "" : "" ;
    using python :  : : "" : "" : <python-debugging>on ;
}

if "boost-regex" = "boost-mpi" || "boost-regex" = "boost-graph-parallel"
{
    using mpi : :
        <library-path>"D:/dev/vcpkg/installed/x64-windows/lib"
        <include>"D:/dev/vcpkg/installed/x64-windows/include"
        <find-shared-library>msmpi ;
}

project user-config : ;

if "v142" != "external"
{
    lib advapi32 ;

    lib icuuc : : <file>"D:/dev/vcpkg/installed/x64-windows/lib/icuuc.lib" <variant>release : : <library>advapi32 ;
    lib icuuc : : <file>"D:/dev/vcpkg/installed/x64-windows/debug/lib/icuucd.lib" <variant>debug : : <library>advapi32 ;

    lib icuin : : <file>"D:/dev/vcpkg/installed/x64-windows/lib/icuin.lib" <variant>release : : ;
    lib icuin : : <file>"D:/dev/vcpkg/installed/x64-windows/debug/lib/icuind.lib" <variant>debug : : ;

    lib icudt : : <file>"D:/dev/vcpkg/installed/x64-windows/lib/icudt.lib" <variant>release : : ;
    lib icudt : : <file>"D:/dev/vcpkg/installed/x64-windows/debug/lib/icudtd.lib" <variant>debug : : ;
}
else
{
    if "Windows" = "Windows" # We are hopelessly stuck inside boost-modular-build-helper, only this works
    {
        lib icuuc : : <name>icuuc <search>"D:/dev/vcpkg/installed/x64-windows/lib" <variant>release : : ;
        lib icuuc : : <name>icuucd <search>"D:/dev/vcpkg/installed/x64-windows/debug/lib" <variant>debug : : ;

        lib icuin : : <name>icuin <search>"D:/dev/vcpkg/installed/x64-windows/lib" <variant>release : : ;
        lib icuin : : <name>icuind <search>"D:/dev/vcpkg/installed/x64-windows/debug/lib" <variant>debug : : ;

        lib icudt : : <name>icudt <search>"D:/dev/vcpkg/installed/x64-windows/lib" <variant>release : : ;
        lib icudt : : <name>icudtd <search>"D:/dev/vcpkg/installed/x64-windows/debug/lib" <variant>debug : : ;
    }
    else
    {
        lib dl ;
        lib icuuc : : <name>icuuc <search>"D:/dev/vcpkg/installed/x64-windows/lib" <variant>release : : <library>dl ;
        lib icuuc : : <name>icuuc <search>"D:/dev/vcpkg/installed/x64-windows/debug/lib" <variant>debug : : <library>dl ;

        lib icuin : : <name>icui18n <search>"D:/dev/vcpkg/installed/x64-windows/lib" <variant>release : : ;
        lib icuin : : <name>icui18n <search>"D:/dev/vcpkg/installed/x64-windows/debug/lib" <variant>debug : : ;

        lib icudt : : <name>icudata <search>"D:/dev/vcpkg/installed/x64-windows/lib" <variant>release : : ;
        lib icudt : : <name>icudata <search>"D:/dev/vcpkg/installed/x64-windows/debug/lib" <variant>debug : : ;
    }
}

lib iconv : : <file>"" <link>shared <runtime-link>shared <variant>release : : ;
lib iconv : : <file>"" <link>shared <runtime-link>shared <variant>debug : : ;
```

**Comment by PhoebeHui** [comment]
@zachsucking, thanks for providing the jam file! we should fix the 'Unescaped special character' issue in user-config.jam

However I don't think it cause this failure. could you check the file under D:/dev/vcpkg/buildtrees/boost-regex/x64-windows-dbg/CMakeFiles/boost? I checked my local files, I don't have that directory, it may contains some special logs or files which may help us to diagnose the problem. Please also attach CMakeOutput.log file.
 
D:/dev/vcpkg/buildtrees/boost-regex/x64-windows-dbg/CMakeFiles/boost 
D:/dev/vcpkg/buildtrees/boost-regex/x64-windows-dbg/CMakeFiles/CMakeOutput.log

```
FAILED: CMakeFiles/boost D:/dev/vcpkg/buildtrees/boost-regex/x64-windows-dbg/CMakeFiles/boost 
```

**Comment by PhoebeHui** [comment]
@coolMissile @FaFoYX, could you help provide above information?

**Comment by PhoebeHui** [comment]
@zachsucking, could you please try latest clean source with following steps?

git clone https://github.com/microsoft/vcpkg
cd vcpkg
./bootstrap-vcpkg.bat
./vcpkg install boost-regex:x64-windows

**Comment by PhoebeHui** [comment]
@zachsucking, have you tried above steps?

**Comment by daoshiming** [comment]
I have the same problem.
Attach log:
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/7619590/install-x64-windows-dbg-out.log)

**Comment by PhoebeHui** [comment]
@daoshiming, it's a different issue, please report a new issue with failures logs and compiler version instead. 

@zachsucking, please reopen this issue if the issue persist.
