### ISSUE TITLE
CMake build failed with wangle:64-linux, because facebook libraries are out of date.

### ISSUE THREAD

**Issue by nusus** [microsoft/vcpkg#20711]
@nusus ,Could you please commit a pr fix this issue? and you can open a issue of facebook update,I will update it

_Originally posted by @JonLiu1993 in https://github.com/microsoft/vcpkg/issues/20586#issuecomment-939207808_

**Comment by JonLiu1993** [comment]
@nusus ,I will fix this bug in pr #20586, reopen issue #20586 and cloesed this issue
