### ISSUE TITLE
IFW-related export options missing from vcpkg help export

### ISSUE THREAD

**Issue by traversaro** [Microsoft/vcpkg#2073]
The IFW-related options of the export command are not displayed on the help of the export command:
~~~
pegua@LAPTOP-TO4SAKLB MINGW64 /c/vcpkg (master)
$ ./vcpkg.exe help export
Summary:
  vcpkg export [options] <pkgs>...

Options:
  --7zip                          Export to a 7zip (.7z) file
  --dry-run                       Do not actually export
  --nuget                         Export a NuGet package
  --nuget-id=<id>                 Specify the id for the exported NuGet package
  --nuget-version=<ver>           Specify the version for the exported NuGet package
  --raw                           Export to an uncompressed directory
  --zip                           Export to a zip file
~~~

The IFW options are instead correctly displayed when a wrong option is passed to the export command:
~~~
pegua@LAPTOP-TO4SAKLB MINGW64 /c/vcpkg (master)
$ ./vcpkg.exe export --wrongopt zlib:x64-windows
Unknown option(s) for command 'export':
    --wrongopt

Valid options are:
    --dry-run
    --raw
    --nuget
    --ifw
    --zip
    --7zip
    --nuget-id=...
    --nuget-version=...
    --ifw-repository-url=...
    --ifw-packages-directory-path=...
    --ifw-repository-directory-path=...
    --ifw-configuration-file-path=...
    --ifw-installer-file-path=...
    --triplet <t>
    --vcpkg-root <path>
~~~

**Comment by traversaro** [comment]
cc @podsvirov

**Comment by podsvirov** [comment]
Hello Silvio, you're right.
Export is already working, but I would say that it is in beta testing.
The documentation was not yet worked out, but I tried to give the options an intuitive name.
Now, the official release of tools for creating installers is not used. You can track the relevant problem [QTIFW-948](https://bugreports.qt.io/browse/QTIFW-948).
When the functionality is stabilized, I will try to pay attention to the documentation.

**Comment by traversaro** [comment]
I just noticed that also the non-ifw related options `triplet` and `vcpkg-root` are not in the help command.

**Comment by traversaro** [comment]
I just realized that `triplet` and `vcpkg-root` are options valid for all commands, and so they are correctly documented in the `./vcpkg help` command.
