### ISSUE TITLE
Signalrclient's portfile.cmake is outdated. Now cpprestsdk's version information is 2.10.0

### ISSUE THREAD

**Issue by wurui1994** [Microsoft/vcpkg#2074]
The cpprest_2_9.lib should be updated to cpprest_2_10.lib:
vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
	OPTIONS_DEBUG
		-DCPPREST_SO=${CURRENT_INSTALLED_DIR}/debug/lib/cpprest_2_9.lib
	OPTIONS_RELEASE
		-DCPPREST_SO=${CURRENT_INSTALLED_DIR}/lib/cpprest_2_9.lib
    OPTIONS
		-DCPPREST_INCLUDE_DIR=${CURRENT_INSTALLED_DIR}/include
        -DDISABLE_TESTS=ON
)

**Comment by ras0219-msft** [comment]
Fixed in master. Thanks for reporting this issue!
