### ISSUE TITLE
[sfml:x64-windows-static] link failure

### ISSUE THREAD

**Issue by Trider12** [microsoft/vcpkg#20744]
**Host Environment**
- OS: Windows 10
- Compiler: v142

**To Reproduce**
`./vcpkg install sfml --triplet=x64-windows-static-md`
New empty project
Add [SFML demo](https://www.sfml-dev.org/tutorials/2.5/start-vc.php) code
Set vcpkg project settings
![image](https://user-images.githubusercontent.com/47952308/137297815-d3f8d1aa-81c2-4c7c-9f58-b7d16ec12cf9.png)
Enable /MD (/MDd)
![image](https://user-images.githubusercontent.com/47952308/137297921-d718f6d9-5335-4dab-a863-bb0dddbfb2f4.png)
Inherited linker input:
`kernel32.lib
user32.lib
gdi32.lib
winspool.lib
comdlg32.lib
advapi32.lib
shell32.lib
ole32.lib
oleaut32.lib
uuid.lib
odbc32.lib
odbccp32.lib`

**Failure logs** 
```
Target VcpkgTripletSelection:
Using triplet "x64-windows-static-md" from "...\vcpkg\installed\\x64-windows-static-md\"

...

Target Link:
SfmlDemo.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl sf::String::String(char const *,class std::locale const &)" (__imp_??0String@sf@@QEAA@PEBDAEBVlocale@std@@@Z) referenced in function main

...

...\SfmlDemo\x64\Debug\SfmlDemo.exe : fatal error LNK1120: 17 unresolved externals
```

**Comment by JackBoosY** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.

**Comment by milen-prg** [comment]
The problem is still unsolved - see here https://github.com/microsoft/vcpkg/issues/31402.
Seems that vcpkg cant link static libraries.
