### ISSUE TITLE
[< gtk:x86-windows>] build failure

### ISSUE THREAD

**Issue by Ramvan1954** [microsoft/vcpkg#20750]
Visual Studio 2019 Community Edition - Windows 10 Home

- Using msys root at F:/Users/GAARY/Documents/GitHub/vcpkg/downloads/tools/msys2/aa5af7b2aa7e90e8
-- Getting CMake variables for x86-windows
-- Configuring x86-windows-dbg
-- Configuring x86-windows-dbg done
-- Configuring x86-windows-rel
-- Configuring x86-windows-rel done
-- Package x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: F:/Users/GAARY/Documents/GitHub/vcpkg/downloads/tools/ninja/1.10.2-windows/ninja.exe install -v
    Working Directory: F:/Users/GAARY/Documents/GitHub/vcpkg/buildtrees/gtk/x86-windows-dbg
    Error code: 1
    See logs for more information:
      F:\Users\GAARY\Documents\GitHub\vcpkg\buildtrees\gtk\package-x86-windows-dbg-out.log
      F:\Users\GAARY\Documents\GitHub\vcpkg\buildtrees\gtk\package-x86-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_meson.cmake:58 (vcpkg_execute_required_process)
  ports/gtk/portfile.cmake:73 (vcpkg_install_meson)
  scripts/ports.cmake:141 (include)

Error: Building package gtk:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: gtk:x86-windows
  Vcpkg version: 2021-09-10-2059ef11aa6067e6f59b0d939c5d17e3c5c47d3e

Additionally, attach any relevant sections from the log files above.

**Comment by Ramvan1954** [comment]
[](url)
[package-x86-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/7353573/package-x86-windows-dbg-err.log)
[](url)
[package-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/7353580/package-x86-windows-dbg-out.log)

**Comment by JonLiu1993** [comment]
@Ramvan1954 ，According to my investigation, this is not a problem with vcpkg. This issue is probably because the parameters you pass to CreateProcess are too long. Here are some suggestions for you to refer to. If you still can’t solve it, please ping me
https://github.com/ninja-build/ninja/issues/1402#issuecomment-376006824

**Comment by JonLiu1993** [comment]
@Ramvan1954 ,Does this problem still exist?

**Comment by JonLiu1993** [comment]
Closing this issue for now since there is no active thread for a long time. Please feel free to reopen this issue if it is still a problem for you.
