### ISSUE TITLE
[<realsense2:x64-windows>] build failure

### ISSUE THREAD

**Issue by nadaM00** [microsoft/vcpkg#20752]
**Host Environment**
- OS: [Windows 10]

**To Reproduce**
`./vcpkg/vcpkg install realsense2:x64-windows

**Failure logs** 
Error: Building package realsense2:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: realsense2:x64-windows
  Vcpkg version: 2021-09-10-2059ef11aa6067e6f59b0d939c5d17e3c5c47d3e

**Additional context**
I have also tried this, but it didn't work:
`./vcpkg/vcpkg install realsense2 --triplet=x64-windows

**Comment by JonLiu1993** [comment]
@nadaM00 ,Thanks for posting this issue, I can't repo your issue locally:
````
Building package realsense2[core]:x64-windows... done
Installing package realsense2[core]:x64-windows...
Installing package realsense2[core]:x64-windows... done
Elapsed time for package realsense2:x64-windows: 4.515 min

Total elapsed time: 4.516 min

The package realsense2:x64-windows provides CMake targets:

    find_package(realsense2 CONFIG REQUIRED)
    target_link_libraries(main PRIVATE realsense2::fw realsense2::realsense2 realsense2::realsense-file)
````
could you please update vcpkg and run command " ./vcpkg install realsense2:x64-windows " again, and provide the error log, thanks

**Comment by JonLiu1993** [comment]
@nadaM00 ，Does this problem still exist?

**Comment by xaedes** [comment]
Can confirm the problem still exists.
I did git pull and vcpkg upgrade, problem still remains.

The error from the log file [install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/7548217/install-x64-windows-dbg-out.log) is:

`src\win\win-helpers.cpp(15): fatal error C1083: Cannot open include file: 'atlstr.h': No such file or directory`

**Comment by xaedes** [comment]
Installing ATL in Visual Studio seems to fix it!

**Comment by JonLiu1993** [comment]
@nadaM00, Could please you try @xaedes' suggestion?

**Comment by JonLiu1993** [comment]
Closing this issue for now since there is no active thread for a long time. Please feel free to reopen this issue if it is still a problem for you.
