### ISSUE TITLE
Error building vcpkg

### ISSUE THREAD

**Issue by Ahnassef** [microsoft/vcpkg#2075]
when running .\bootstrap-vcpkg.bat I get this error 

> C:\vcpkg\scripts\findVisualStudioInstallationInstances.ps1 : Cannot convert value "System.Object[]" to type
"System.Xml.XmlDocument". Error: "An error occurred while parsing EntityName. Line 17, position 55."
At C:\vcpkg\scripts\findAnyMSBuildWithCppPlatformToolset.ps1:10 char:38
> onInstances = & $scriptsDir\findVisualStudioInstallationInstances.ps1
>                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [findVisualStudi...onInstances.ps1], RuntimeException
    + FullyQualifiedErrorId : InvalidCastToXmlDocument,findVisualStudioInstallationInstances.ps1

I've visual studio 2017 community edition version 15.2 with visual c++ and C# installed running on windows 10 machine.

Please help.

**Comment by ras0219-msft** [comment]
Hi @Ahnassif, could you try updating VS 2017 to the latest 15.4 release and try again?

**Comment by NancyLi1013** [comment]
@Ahnassif , is there the problem on your machine when you update VS 2017 to the latest version?
Note: the latest version of VS 2017 is 15.9.7.

**Comment by vstep0** [comment]
Hello. I have the same issue. Could it happen because vswhere.exe doesn't escape '&' symbols in xml output?

**Comment by kaushik-d** [comment]
I have the same problem too.

**Comment by luojia65** [comment]
After installation a reboot may be required. If you install VS and install vcpkg immediately before reboot, it may rise this error. Reboot and try again solved my problem.

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/7903
