### ISSUE TITLE
[osg] When debugging, the PDB file for osgViewer.dll cannot be loaded.

### ISSUE THREAD

**Issue by stronger1234** [microsoft/vcpkg#20762]
****

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when the PDB file for osgViewer.dll cannot be loaded during debugging.
I use the command `vcpkg.exe install osg[tools]` and the PDB for osgViewer.dll is overridden by that for osgviewer.exe because their PDB file names are the same. The modified date time of osgViewer.pdb is the same as osgviewer.exe, differing from osgViewer.dll.

**Proposed solution**
Configuring the output directory for libraries and applications to different destination path may solved this problem.

**Describe alternatives you've considered**
I also found that there's a `vcpkg/ports/osg/remove-prefix.patch` which remove the version string from the traditional style of the osg library names. Maybe not applying this patch could also fix this problem.

**Additional context**
None.

**Comment by JackBoosY** [comment]
Yeah... that's a common issue.
