### ISSUE TITLE
[osg] Debug build of tools not installed properly, and PDBs for Release build missing in the installed directory.

### ISSUE THREAD

**Issue by stronger1234** [microsoft/vcpkg#20763]
****

**Is your feature request related to a problem? Please describe.**
I use `vcpkg.exe install osg[tools]` to install osg application tools, but the resulting executables are missing in the `vcpkg/installed/<triplet>/debug/tools/osg`. Only osgPlugins are presented there.
Another problem is that PDBs for Release build of tools and plugins are also not copied to the installed directory.

**Proposed solution**
It would be nice to deploy all PDBs and tools(exe) into the installed directory.

**Comment by JackBoosY** [comment]
The fact is: some tools with the same name as the library were installed in the same directory by default, causing pdb to be overwritten.
If it's true, I believe it's a upstream bug: they doesn't consider that.

**Comment by stronger1234** [comment]
I finally found that the Release configuration of osg plugins' linker flags are affected by `CMAKE_MODULE_LINKER_FLAGS_RELEASE`. But in `vcpkg/scripts/toolchains/windows.cmake`, only `CMAKE_SHARED_LINKER_FLAGS_RELEASE` and `CMAKE_EXE_LINKER_FLAGS_RELEASE` are set with `/DEBUG` linker option, missing the `MODULE` one. No wonder why PDBs for release build of osg plugins were even not generated at all.
