### ISSUE TITLE
[glog] Static build of glog dynamically links libunwind

### ISSUE THREAD

**Issue by tusharb86** [microsoft/vcpkg#20771]
****

**Is your feature request related to a problem? Please describe.**
glog pulls in libunwind automatically if it is detected on the system. By default, this linkage is dynamic even though the triplet has `VCPKG_LIBRARY_LINKAGE` set to `static`. This means that when we deploy the resulting binary to a target system/container, the machine requires libunwind.so to be installed. See the tangentially related issue here: https://github.com/google/glog/issues/629

**Proposed solution**
In glog version 0.5.0, [a new CMake option `WITH_UNWIND`](https://github.com/google/glog/blob/8f9ccfe770add9e4c64e9b25c102658e3c763b73/CMakeLists.txt#L30) was introduced. This allows consumers to build without libunwind being pulled in at all and glog uses alternative methods to unwind the stack when needed. It is unclear to me whether this fits the pattern of "features" for a port and could be implemented that way?

**Describe alternatives you've considered**
Our team has implemented a custom port to upgrade glog to version 0.5.0 and adds `-DWITH_UNWIND=OFF` to the OPTIONS in vcpkg_configure_cmake.

**Comment by JonLiu1993** [comment]
Fixed by #22135
