### ISSUE TITLE
some packages not respecting VCPKG_TARGET_TRIPLET on macOS

### ISSUE THREAD

**Issue by Be-ing** [microsoft/vcpkg#20779]
**Describe the bug**
I am using a custom triplet to set the minimum macOS deployment target. In CMakeLists.txt, I have:
```
set(VCPKG_TARGET_TRIPLET "x64-osx-min10.14")
```
However some packages [ignore this](https://github.com/mixxxdj/mixxx/runs/3912521801?check_suite_focus=true#step:17:921) and revert to the default x64-osx triplet.

**Environment**
- OS: macOS 10.15
- Compiler: Apple Clang

**To Reproduce**
1. Create custom triplet
2. Set VCPKG_OVERLAY_TRIPLETS and VCPKG_TARGET_TRIPLET from CMakeLists.txt
3. Add zstd or qtbase to manifest

**Expected behavior**
VCPKG_TARGET_TRIPLET is used for all packages.

**Failure logs** 
https://github.com/mixxxdj/mixxx/runs/3912521801?check_suite_focus=true#step:17:921

**Comment by dg0yt** [comment]
> So any port with a host dependency will ignore VCPKG_TARGET_TRIPLET

No. The port will use the target triplet as expected.
The host dependency will use the host triplet.

In the zstd case, it is cheap. (Only some cmake files.)
In the qtbase case, it pulls in a lot of binary stuff. Some port will be builld both for host and target.

**Comment by JackBoosY** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
