### ISSUE TITLE
[sdl2:x64-windows-static/cmake] Could not find a package configuration file provided by "SDL2"

### ISSUE THREAD

**Issue by cjwijtmans** [microsoft/vcpkg#20788]
* Installed sdl2 static
```bash
.\vcpkg install sdl2:x64-windows-static
```

> Package sdl2:x64-windows-static is already installed
> Restored 0 packages from C:\Users\cjwij\AppData\Local\vcpkg\archives in 202 us. Use --debug to see more details.
> 
> Total elapsed time: 514 us
> 
> The package sdl2 provides CMake targets:
> 
>     find_package(SDL2 CONFIG REQUIRED)
>     target_link_libraries(main PRIVATE SDL2::SDL2 SDL2::SDL2main SDL2::SDL2-static)

* setup CMakeLists.txt
```cmake
set(VCPKG_TARGET_TRIPLET x64-windows-static)
find_package(SDL2 CONFIG REQUIRED)
```

* vscode invokes cmake 
```
Executing command: "C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" --no-warn-unused-cli -DCMAKE_TOOLCHAIN_FILE:STRING=C:/usr/src/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -Hblah -Bblah/build -G "Visual Studio 17 2022" -T host=x64 -A x64
```

> [cmake] CMake Error at C:/usr/src/vcpkg/scripts/buildsystems/vcpkg.cmake:788 (_find_package):
> [cmake]   Could not find a package configuration file provided by "SDL2" with any of
> [cmake]   the following names:
> [cmake] 
> [cmake]     SDL2Config.cmake
> [cmake]     sdl2-config.cmake
> [cmake] 
> [cmake]   Add the installation prefix of "SDL2" to CMAKE_PREFIX_PATH or set
> [cmake]   "SDL2_DIR" to a directory containing one of the above files.  If "SDL2"
> [cmake]   provides a separate development package or SDK, be sure it has been
> [cmake]   installed.

* Works when `sdl2:x64-windows` is installed.

**Comment by sonygod** [comment]
got the same issue.

**Comment by JackBoosY** [comment]
Please pass -DVCPKG_TARGET_TRIPLET="x64-windows-static" and try again.

**Comment by JackBoosY** [comment]
@cjwijtmans In the `CMakeSettings.json`, click your configuration name first then click `Manage Configurations...`:
![image](https://user-images.githubusercontent.com/47264268/137831119-54b282b5-7731-46e4-9393-37a78e971295.png)
![image](https://user-images.githubusercontent.com/47264268/137831150-5a562621-ce96-4874-89d5-25974a1162f5.png)

**Comment by cjwijtmans** [comment]
I do not have this file. I created one but inside this file I do not get any JSON suggestions neither do I get a `Manage Configurations...` drop down. Is there a documentation on this somewhere?

**Comment by cjwijtmans** [comment]
This seemed to work for me.

```json
{
    "version": 3,
    "cmakeMinimumRequired": {
        "major": 3,
        "minor": 21,
        "patch": 0
    },
    "configurePresets": [
        { "name": "default",
            "hidden": true,
            "generator": "Ninja",
            "binaryDir": "${sourceDir}/build/${presetName}",
            "cacheVariables": {
              "CMAKE_BUILD_TYPE": "Debug",
              "CMAKE_INSTALL_PREFIX": "${sourceDir}/build/install"
            }
        },
        { "name": "windows-default",
            "inherits": "default",
            "condition": {
                "type": "equals",
                "lhs": "${hostSystemName}",
                "rhs": "Windows"
             },
            "generator": "Visual Studio 17 2022",
            "environment": {
                "VCPKG_ROOT": "C:/usr/src/vcpkg"
             },
            "cacheVariables": {
                "CMAKE_TOOLCHAIN_FILE": {
                    "value": "C:/usr/src/vcpkg/scripts/buildsystems/vcpkg.cmake",
                    "type": "FILEPATH"
                 },
                "VCPKG_TARGET_TRIPLET": "x64-windows-static"
             },
            "vendor": {
                "microsoft.com/VisualStudioSettings/CMake/1.0": {
                    "hostOS": [ "Windows" ]
                 }
            }
        }
    ]
}
```

but still has issues.

```bash
[cpptools] The build configurations generated do not contain the active build configuration. Using 'Debug' for CMAKE_BUILD_TYPE instead of 'null' to ensure that IntelliSense configurations can be found
```

**Comment by cjwijtmans** [comment]
I have tried this in `settings.json`, it does not work.

```json
{
    "cmake.buildEnvironment": {
        "VCPKG_TARGET_TRIPLET": "x64-windows-static"
    },
    "cmake.configureEnvironment": {
        "VCPKG_TARGET_TRIPLET": "x64-windows-static"
    },
    "cmake.environment": {
        "VCPKG_TARGET_TRIPLET": "x64-windows-static"
    }
}
```

**Comment by JackBoosY** [comment]
Close this issue as solved.
