### ISSUE TITLE
_add_library cannot create ALIAS target because another target "CURL::libcurl" with the same name already exists

### ISSUE THREAD

**Issue by SpriteOvO** [microsoft/vcpkg#20789]
**Host Environment**
- OS: Windows
- Compiler: MSVC

**To Reproduce**
- CMakeLists.txt:
  ```
  cmake_minimum_required(VERSION 3.20)
  
  include(FetchContent)
  
  project(cmake_test)
  
  set(CPR_BUILD_TESTS OFF)
  set(CPR_BUILD_TESTS_SSL OFF)
  set(CURL_ZLIB OFF CACHE STRING "" FORCE)
  FetchContent_Declare(
      cpr
      GIT_REPOSITORY "https://github.com/whoshuu/cpr.git"
      GIT_TAG "1.6.2"
  )
  FetchContent_MakeAvailable(cpr)
  ```
- `cmake -G "Visual Studio 16 2019" -A Win32 -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="path/to/vcpkg/scripts/buildsystems/vcpkg.cmake"`

**Failure logs** 
```
CMake Error at path/to/vcpkg/scripts/buildsystems/vcpkg.cmake:576 (_add_library):
  _add_library cannot create ALIAS target "CURL::libcurl" because another
  target with the same name already exists.
Call Stack (most recent call first):
  _deps/cpr-src/CMakeLists.txt:217 (add_library)
```

**Additional context**
This error occurs if `cmake_minimum_required(VERSION 3.20)`, but `VERSION 3.10` not.
The reason for using `FetchContent` is that I use the unreleased code of that library. Some other libraries are installed by vcpkg.

**Comment by dg0yt** [comment]
FTR this is not about *port cpr*, but using the vcpkg toolchain to build cpr.

Which curl do you want to use with cpr: curl from vcpkg (needs `-DCPR_FORCE_USE_SYSTEM_CURL=ON`), or curl fetched/added by cpr?

**Comment by SpriteOvO** [comment]
> Which curl do you want to use with cpr: curl from vcpkg (needs `-DCPR_FORCE_USE_SYSTEM_CURL=ON`), or curl fetched/added by cpr?

curl fetched/added by cpr I think.

**Comment by JonLiu1993** [comment]
Confirmed
cmake_minimum_required(VERSION 3.20)
````
CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:578 (_add_library):
  _add_library cannot create ALIAS target "CURL::libcurl" because another
  target with the same name already exists.
Call Stack (most recent call first):
  _deps/cpr-src/CMakeLists.txt:191 (add_library)


-- Configuring incomplete, errors occurred!
See also "F:/test6/CMakeFiles/CMakeOutput.log".
See also "F:/test6/CMakeFiles/CMakeError.log".
````
cmake_minimum_required(VERSION 3.10)
````
-- curl version=[7.75.0]
-- Could NOT find Perl (missing: PERL_EXECUTABLE)
-- Could NOT find LibSSH2 (missing: LIBSSH2_LIBRARY LIBSSH2_INCLUDE_DIR)
-- Enabled features: SSL IPv6 AsynchDNS SSPI alt-svc SPNEGO Kerberos NTLM
-- Enabled protocols: HTTP HTTPS
-- Enabled SSL backends: Schannel
-- Configuring done
-- Generating done
-- Build files have been written to: F:/test6
````

**Comment by dg0yt** [comment]
See also https://github.com/microsoft/vcpkg/issues/20756#issuecomment-944252561: 
You basically don't want to let cpr build curl while another curl is installed and used in vcpkg.

It is still strange that `CURL::libcurl` already exists when cpr tries to create the alias. I suspect some `find_package(CURL)` in one of the other packages searched by cpr.

**Comment by SpriteOvO** [comment]
@PhoebeHui You are right, it may be a bug in `cpr`.

I copied some code from `cpr` to made the following smaller reproducible code.
It can reproduce the error message when `CMAKE_TOOLCHAIN_FILE` is not specified. (but the previous can't, which is a bit strange)
Anyway, I'll open an issue in the `cpr` repo and let them take a look.
Thank you for your help.

```cmake
cmake_minimum_required(VERSION 3.20)

include(FetchContent)

project(cmake_test)

FetchContent_Declare(curl
                     URL                    https://github.com/curl/curl/releases/download/curl-7_79_1/curl-7.79.1.tar.xz
                     URL_HASH               SHA256=0606f74b1182ab732a17c11613cbbaf7084f2e6cca432642d0e3ad7c224c3689 # the file hash for curl-7.79.1.tar.xz
                     USES_TERMINAL_DOWNLOAD TRUE)   # <---- This is needed only for Ninja to show download progress
FetchContent_MakeAvailable(curl)

add_library(curl_int INTERFACE)
target_link_libraries(curl_int INTERFACE libcurl)
target_include_directories(curl_int INTERFACE ${curl_SOURCE_DIR}/include ${curl_BINARY_DIR}/include/curl)
add_library(CURL::libcurl ALIAS curl_int)
```
