### ISSUE TITLE
Make `usage` file mandatory

### ISSUE THREAD

**Issue by HappySeaFox** [microsoft/vcpkg#20786]
****

**Is your feature request related to a problem? Please describe.**

Some ports have no usage, and it's not clear how to link against them.

**Proposed solution**
Make `usage` mandatory.

**Describe alternatives you've considered**
Search for cmake configs and use `find_package` if they exist. Use `find_library` otherwise.

**Additional context**
\-

**Comment by dg0yt** [comment]
In most cases, upstreams should provide usage instructions which work also when using vcpkg.

> **Describe alternatives you've considered** 
> Search for cmake configs and use `find_package` if they exist.

FTR the vcpkg tools has a similar feature. However, I tend to consider it a misfeature, in its current form:
#20190 

>  Use `find_library` otherwise.

Not sufficient for static linkage with transitive usage requirements.

But pkgconfig could be considered in addition to cmake.

**Comment by PhoebeHui** [comment]
Closing in favor of https://github.com/microsoft/vcpkg/discussions/18224.
