### ISSUE TITLE
How to know whether dependent packages has been built with specified features?

### ISSUE THREAD

**Issue by UnaNancyOwen** [Microsoft/vcpkg#2079]
Currently, @xoviat are implementing features in VTK port (#2071 <code>vcpkg install vtk[qt] --featurepackage</code>).
I want to implement a feature to specify whether to build with enable Qt option to [PCL](https://github.com/Microsoft/vcpkg/tree/master/ports/pcl) port (<code>vcpkg install pcl[qt] --featurepackage</code>).
However, It is necessary to know whether VTK port has been built with Qt option.
How to know whether dependent packages has been built with specified features?
```
Source: pcl
Version: 1.8.1
Description: Point Cloud Library (PCL) is open source library for 2D/3D image and point cloud processing.
Build-Depends: boost, eigen3, flann, qhull, vtk, openni2, winpcap

Feature: qt
Description: Qt support for PCL
Build-Depends: qt5
```

Can I specify depends in CONTROL?
```
Build-Depends: vtk[qt5]
```
Or, Is it necessary to conditional branch in portfile.cmake?
```cmake
set(WITH_QT OFF)
if("qt" IN_LIST FEATURES)
  if(NOT EXIST "${VCPKG_ROOT_DIR}\installed\${TARGET_TRIPLET}\lib\<QVTK Library File>")
    message(FATAL_ERROR "VTK port is not built with Qt option enabled.")
  endif()
  set(WITH_QT ON)
endif()
```

**Comment by xoviat** [comment]
What's funny is that homebrew started out with the functionality to depend on packages with features, but then they disabled that so that they could switch to binaries.

**Comment by xoviat** [comment]
Can you submit your port as a PR? I can test it on appveyor (https://github.com/xoviat/test-vcpkg).

**Comment by ras0219-msft** [comment]
The objective is to simply depend on `vtk[qt]` in the feature -- if that doesn't work, please let us know, because it's a bug!

@xoviat yeah, that is pretty funny! Though, I think it is an expression of different goals (application deployment vs developer libraries).

**Comment by xoviat** [comment]
> that is pretty funny! 

It's not funny at all. There are a variety of CI projects that depend on c libraries to build. On OSX and linux, its a simple `apt-get install` or `brew install`, but on Windows, before vcpkg, you had to put in a few hours to get the library built on the CI system. Now, you can just do `vcpkg install` and set up the cache locations, and everything just works.

Further, even if you had managed to build the libraries on the CI system, the scripts were likely not applicable to local development. With vcpkg, it's possible to run the same commands on appveyor and your local system to install the C libraries.

**Comment by UnaNancyOwen** [comment]
@xoviat @ras0219-msft Thank you for your advice.
I sent a pull request #2083. Please review it.

**Comment by ras0219-msft** [comment]
Merged!
