### ISSUE TITLE
[sol2] Handle dependencies using features

### ISSUE THREAD

**Issue by michaelkroener** [microsoft/vcpkg#20794]
****

**Is your feature request related to a problem? Please describe.**
It is currently not possible to use sol2 with the package luajit as dependency as on the windows platform it always tries to use lua and if you have luajit in your vcpkg.json this is a conflict.

**Proposed solution**
```json
{
  "name": "sol2",
  "version-string": "3.2.2",
  "port-version": 2,
  "description": "Sol v2.0 - a C++ <-> Lua API wrapper with advanced features and top notch performance - is here, and it's great",
  "homepage": "https://github.com/ThePhD/sol2",
  "default-features": [
    "lua"
  ],
  "features": {
    "lua": {
      "description": "Use lua",
      "dependencies": [
        "lua"
      ]
    },
    "luajit": {
      "description": "Use luajit",
      "dependencies": [
        "luajit"
      ]
    }
  }
}
```

I propose using features to determine which lua implementation the user wants to use. Also having the default Lua implementation as the default doesnt change the old behavior but allows the new behavior.

**Describe alternatives you've considered**
I tried looking for a possibility for overwriting the dependencies of a package I include in my vcpkg.json

**Additional context**

**Comment by JackBoosY** [comment]
We should select the detected dependencies based on the feature name, rather than automatically detect them.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Now lua and luajit don't conflict on windows, you can install sol2 when luajit has been installed vcpkg.
