### ISSUE TITLE
[effolkronium-random] Properly handle package_name

### ISSUE THREAD

**Issue by michaelkroener** [microsoft/vcpkg#20795]
****

**Is your feature request related to a problem? Please describe.**
Since version 1.3.1 the port suggested find_package(effolkronium-random CONFIG REQUIRED) this did not work you had to use 
ind_package(effolkronium-random CONFIG REQUIRED) after the last update to the port 1.4.0 neither of both options work as it can't properly find the cmake config files anymore.

**Proposed solution**
I already answered in the pull request https://github.com/microsoft/vcpkg/pull/20496 after it stopped working

```
vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO effolkronium/random
    REF v1.4.0
    SHA512 B3DDEC048BBFB48877FD12295D4E0492E25976E1C4FE66F13E9E6E611DAAF654BD8D4AE75EA75125CB5AB420B82472C1CC1AB0BED3AEF632911B0934B45B23AF
    HEAD_REF master
)

vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS
		-DRandom_BuildTests=OFF
)
vcpkg_cmake_install()
vcpkg_cmake_config_fixup(PACKAGE_NAME "effolkronium_random" CONFIG_PATH "cmake")
vcpkg_fixup_pkgconfig()

file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug" "${CURRENT_PACKAGES_DIR}/lib")
file(INSTALL "${SOURCE_PATH}/LICENSE.MIT" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
```

**Describe alternatives you've considered**
I renamed the config files to both variatons of the name thats not really a alternative but it worked.

**Additional context**

**Comment by NancyLi1013** [comment]
Hi @michaelkroener 

Thanks for posting this issue.

Since package name `effolkronium-random` is different from `${PROJECT_NAME} `https://github.com/effolkronium/random/blob/master/CMakeLists.txt#L4.

Your proposal is correct. Thanks for figuring this out.
