### ISSUE TITLE
[wangle, folly, fizz, proxygen] Update and repair of facebook libraries.

### ISSUE THREAD

**Issue by cmachaca** [microsoft/vcpkg#20805]
****

**Is your feature request related to a problem?**
Problems with the facebook repositories.

**Proposed solution**
Update facebook repositories (wangle, fizz, folly, proxygen) and repair windows compatibility (wangle, fizz, folly).

**Additional context**
Wangle cannot compile on windows. The solution is in a fork of mine.

**Comment by Thomas1664** [comment]
(Partially) fixed by #22967

**Comment by JonLiu1993** [comment]
Fixed by https://github.com/microsoft/vcpkg/pull/22967
