### ISSUE TITLE
[qwt:x64-windows-static] qwt gets built as dynamic library even though it's a static triplet.

### ISSUE THREAD

**Issue by oyvindln** [microsoft/vcpkg#20811]
**Describe the bug**
When installing qwt with the x64-windows-static tripled, it is built as a dynamic library rather than a static one. There is a config setting in qwtconfig.pri that makes it build as a dll that is enabled by default. There used to be a patch to selectively set it, but it seems to have been removed when updating to version 6.1.5 of the library in #12459. It may have been an oversight as there was another patch there that was no longer needed. I suspect the same issue will occur on other static triplets but haven't tested. (No problems on non-static triplets as it's supposed to be dynamically linked there, and it is.)

**Environment**
- OS: Windows 10
- Compiler: MSVC 2019

**To Reproduce**
1. ./vcpkg install qwt:x64-windows-static
2. Build a project that uses qwt, and it depends on qwt.dll (and it again depends on other Qt dlls)

**Expected behavior**
The library should be statically linked.

**Comment by JonLiu1993** [comment]
@oyvindln ,Could you please provide your CMakeLists? I will repo locally

**Comment by JonLiu1993** [comment]
Do you mean that this patch shouldn't be deleted when the qwt version was upgraded last time?
````
diff --git a/qwtconfig.pri b/qwtconfig.pri
index 1fe6055..441c69b 100644
--- a/qwtconfig.pri
+++ b/qwtconfig.pri
@@ -72,7 +72,10 @@ QWT_INSTALL_FEATURES  = $${QWT_INSTALL_PREFIX}/features
 # it will be a static library.
 ######################################################################

+CONFIG(dynamic, dynamic|static) {
+
 QWT_CONFIG           += QwtDll
+}

 ######################################################################
 # QwtPlot enables all classes, that are needed to use the QwtPlot
````

**Comment by oyvindln** [comment]
I will see if I can sort something

**Comment by JackBoosY** [comment]
Can any one confirm this issue was fixed by #21832? I need to double confirm that.

Thanks.

**Comment by oyvindln** [comment]
Seems to solve it for me at least.

**Comment by BillyONeal** [comment]
Thanks!
