### ISSUE TITLE
[msmpi] build failure

### ISSUE THREAD

**Issue by UnknownObject000** [microsoft/vcpkg#20823]
**Host Environment**
- OS: Windows 11 Professional Workstation Insider Preview (Build 22478.1012)
- Compiler: MSVC 14.2 (Visual Studio 2019)

**To Reproduce**
`./vcpkg install msmpi`

**Failure logs** 
PS F:\vcpkg> vcpkg install msmpi
Computing installation plan...
The following packages will be built and installed:
    msmpi[core]:x86-windows -> 10.1.12498#2
Detecting compiler hash for triplet x86-windows...
-- Using HTTP(S)_PROXY in environment variables.
Restored 0 packages from C:\Users\15819\AppData\Local\vcpkg\archives in 120.7 us. Use --debug to see more details.
Starting package 1/1: msmpi:x86-windows
Building package msmpi[core]:x86-windows...
-- Downloading https://download.microsoft.com/download/a/5/2/a5207ca5-1203-491a-8fb8-906fd68ae623/msmpisdk.msi -> msmpisdk-10.1.12498-b0087dfd.msi...
-- Downloading https://download.microsoft.com/download/a/5/2/a5207ca5-1203-491a-8fb8-906fd68ae623/msmpisetup.exe -> msmpisetup-10.1.12498.exe...
CMake Error at ports/msmpi/portfile.cmake:59 (message):
    Could not find:
      C:\Program Files/Microsoft MPI/Bin/mpiexec.exe
    Please install the MSMPI redistributable package before trying to install this port.
    The appropriate installer has been downloaded to:
      F:/vcpkg/downloads/msmpisetup-10.1.12498.exe

Call Stack (most recent call first):
  scripts/ports.cmake:141 (include)

Error: Building package msmpi:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: msmpi:x86-windows
  Vcpkg version: 2021-09-10-2059ef11aa6067e6f59b0d939c5d17e3c5c47d3e

Additionally, attach any relevant sections from the log files above.

**Additional context**
Package: msmpi:x86-windows
 Vcpkg version: 2021-09-10-2059ef11aa6067e6f59b0d939c5d17e3c5c47d3e

**Comment by NancyLi1013** [comment]
Closing this issue for now, please feel free if it is still a problem for you.

**Comment by sodmlx2** [comment]
hi!

this error persist:

error: building msmpi:x64-windows failed with: BUILD_FAILED
Elapsed time to handle msmpi:x64-windows: 203 ms
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+msmpi
You can submit a new issue at:
https://github.com/microsoft/vcpkg/issues/new?title=[msmpi]+Build+error&body=Copy+issue+body+from+C%3A%2Fdev%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

Is there any way to handle this error, without installing msmpi.exe ? manually..
