### ISSUE TITLE
[qwt] provides qt6 version

### ISSUE THREAD

**Issue by MehdiChinoune** [microsoft/vcpkg#20836]
****

**Is your feature request related to a problem? Please describe.**
Qwt is built against Qt5 on vcpkg.

**Proposed solution**
Rename the qwt to qwt-qt5 and build qwt against Qt6

**Describe alternatives you've considered**
Maybe make qt5 and qt6 as features (even they conflict)

**Additional context**
@Neumann-A any suggestions?

**Comment by JackBoosY** [comment]
We should move `qwt` to `qwt-qt5` and suitable `qwt` with `qt6`.
