### ISSUE TITLE
[android] Android NDK r23 and clang support

### ISSUE THREAD

**Issue by holmescn** [microsoft/vcpkg#20844]
I was trying to embed python into my Android App. So I need to build a bunch of C/C++ libraries besides the `libpython3.x.a`. Since Android NDK r21, the GCC toolchain is dropped and only clang as the default compiler. I have written some scripts to build some libraries and a little of patches. But in order to finish the project, I need more C/C++ libraries. So I switch to vcpkg. After some tests, I found that most libraries that are built with CMake seem to work well with the `*-android` triplets contributed by the community, but others that are based on autotools (e.g. configure + make) does not work well. For example, the `libiconv` failed during the config stage due to it is trying to compile with gcc.

There are several problems:

1. the `VCPKG_DETECTED_CMAKE_CXX_STANDARD_LIBRARIES` contains `-static-libc++` which will be convert to `-l-static-libc++` since it is not the standard library reference style.
2. `CC` and `CXX` should be set in the environment to help the `configure` script find the right compiler
3. `AR`, `RANLIB` and `STRIP`, perhaps `READELF` should also be set in the environment for library generate.

For `python3:*-android`, patches should be apply to the `setup.py` for cross-compiling the standard libraries.

So I have made a draft PR in http://github.com/holmescn/vcpkg on branch fix-android-ndk-r23. But there are some problem that I don't know how to resolve, so I cannot make a PR right now:

1. There is an option of ANDROID_API which needed to be appended to the cross-compiling compiler like `armv7a-linux-androideabi${ANDROID_API}-clang`. I don't know where to add it.
2. The `CMAKE_HOST_SYSTEM_VERSION` is empty on macOS which is needed in the `--build` option like `--build=x86_64-apple-darwin${CMAKE_HOST_SYSTEM_VERSION}`. Though this could be solved by execute_process of `uname -r`.
3. The `_vcpkg_determine_autotools_host_cpu` and `_vcpkg_determine_autotools_target_cpu` seem not handle Android host and target well. I implement them using MATCHES on `VCPKG_DETECTED_CMAKE_SYSTEM_PROCESSOR` but it takes more code.

The python patches is another story. I would like to keep track with the problem until the PR is ready to push.

**Comment by m-kuhn** [comment]
See also https://github.com/microsoft/vcpkg/pull/15605

**Comment by m-kuhn** [comment]
@holmescn are you working on a PR?
Would it make sense to rename this issue and remove the version r23 it seems to be generic for any ndk

**Comment by holmescn** [comment]
@m-kuhn yes, I am working on this draft PR. It seems to be a generic patch for Android NDKs that are using clang as their main compiler. I have added as few as possible changes to make it work. But I could not test most ports.

**Comment by m-kuhn** [comment]
@holmescn happy to give your branch a try if you can send me a link to it

**Comment by holmescn** [comment]
@m-kuhn https://github.com/holmescn/vcpkg, branch fix-android-ndk-r23. Only Linux platform is tested, I am working on macOS. Windows is the last.

**Comment by holmescn** [comment]
today upgrade to latest master branch:

1. VCPKG_DETECTED_CMAKE_HOST_SYSTEM_VERSION is added
2. changed to arg_BUILD_TRIPLET
3. changed to configure_env style
4. use string append instead of list append

**Comment by dg0yt** [comment]
Don't you want to open a *draft* PR?

**Comment by m-kuhn** [comment]
> Don't you want to open a _draft_ PR?

Great idea.
I failed to build libiconv for x64-android (works on the [branch listed above](https://github.com/opengisch/vcpkg/tree/configure_make)), a discussion related to this implementation would be much better located in the context of a PR.

**Comment by holmescn** [comment]
@dg0yt Yes, but, I cannot find how to make a draft PR. I remember that it was mentioned in the issue template but cannot find it. (shame)

**Comment by holmescn** [comment]
> > Don't you want to open a _draft_ PR?
> 
> Great idea. I failed to build libiconv for x64-android (works on the [branch listed above](https://github.com/opengisch/vcpkg/tree/configure_make)), a discussion related to this implementation would be much better located in the context of a PR.

If you check the `config-x64-android-dbg-out.log` under `<VCPKG_ROOT>/buildtrees/libiconv`, and it said gcc not works, please set:

    export PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH

since I did not configure the PATH inside `vcpkg_configure_make.cmake`. If is shown other errors, please post your config-* files here. libiconv is fine here.

**Comment by dg0yt** [comment]
One way to start a PR is the "Create new PR" button on the PR list, and then "Compare across forks". Note that there is also a help button. I can even give you the links for the two forks:

https://github.com/microsoft/vcpkg/compare/master...holmescn:fix-android-ndk-r23

https://github.com/microsoft/vcpkg/compare/master...opengisch:configure-make

Just remember to change the button state to "Create draft PR" before finally pushing the button.

The PR submission, and any new push (regular or force-push), will trigger CI. CI does not test android, but some changes may impact other targets. For example, @m-kuhn's branch has an important patch fixing cross builds with `vcpkg_configure_make` which is not specific to android. It will rebuild a lot of ports. I would like to make this a separate PR, with a slighty different implementation. But it is a candidate for idle CI on Sunday.

Whatever branch is chose to form a PR, it can be contributed to by comments or by PRs against that branch on the owner's GH repository.

**Comment by holmescn** [comment]
@dg0yt Ok, the draft PR is published at #21222.
I even don't know GitHub has this kind of feature, shame.

**Comment by holmescn** [comment]
The PR is dropped, but the branch will be maintained until someone finds an elegant method to support Android NDK r21+ that are based on the clang compiler. I will keep the branch upgrade to the latest branch from microsoft/vcpkg. It could be a reference for any successor. Thanks to anyone who reviewed the PR.

**Comment by holmescn** [comment]
This issue will be closed since a more generic topic is opened at #21345 .
