### ISSUE TITLE
Packages from vcpkg are not visible in the cmake project 

### ISSUE THREAD

**Issue by Step245** [microsoft/vcpkg#20843]
Several packages (including uwebsockets) are installed for my Visual Studio 19 using VCPKG. When working in the WINDOWS console project, everything is fine, everything "#Include" sees, everything works. But I create a CMAKE C ++ project (I need a program for Linux and windows) and enter #include <uwebsockets / App.h> and others that were installed using VCPKG, the compiler does not see (cannot open source file "uwebsockets/App.h"). According to the guide from README.md, I added the path to the vcpkg.cmake file, changed SETTINGS.JSON, nothing worked. I did not find information on the Internet, please help with this.

**Comment by autoantwort** [comment]
So you have set `CMAKE_TOOLCHAIN_FILE`, but do you also have done `find_package` for the packages you are using in CMake?

**Comment by adrubesh** [comment]
Same issue here. I cannot get this to work with CMake. `CMAKE_TOOLCHAIN_FILE` is set, I've ran `vcpkg integrate install` half a dozen times already thinking it would fix things. `find_package` just shows 'error cannot find package XYZ'
