### ISSUE TITLE
Error when trying to bootstrap vcpkg after new install

### ISSUE THREAD

**Issue by DragonOsman** [Microsoft/vcpkg#2086]
I tried to reinstall vcpkg just now.  When I tried to run the bootstrap .bat file, I got the following error:

> PS C:\Windows\System32\vcpkg> .\bootstrap-vcpkg.bat
> Microsoft (R) Build Engine version 15.4.8.50001 for .NET Framework
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
> MSBUILD : error MSB1009: Project file does not exist.
> Switch: dirs.proj
> Copy-Item : Cannot find path 'C:\Windows\System32\vcpkg\toolsrc\Release\vcpkg.exe' because it does not exist.
> At C:\Windows\System32\vcpkg\scripts\bootstrap.ps1:49 char:5
> +     Copy-Item $vcpkgSourcesPath\Release\vcpkg.exe $vcpkgRootDir\vcpkg ...
> +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : ObjectNotFound: (C:\Windows\Syst...lease\vcpkg.exe:String) [Copy-Item], ItemNotFoundExce
>    ption
>     + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand
> 
> Copy-Item : Cannot find path 'C:\Windows\System32\vcpkg\toolsrc\Release\vcpkgmetricsuploader.exe' because it does not
> exist.
> At C:\Windows\System32\vcpkg\scripts\bootstrap.ps1:50 char:5
> +     Copy-Item $vcpkgSourcesPath\Release\vcpkgmetricsuploader.exe $vcp ...
> +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : ObjectNotFound: (C:\Windows\Syst...icsuploader.exe:String) [Copy-Item], ItemNotFoundExce
>    ption
>     + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand

Would someone please help me out?  Thanks in advance.

**Comment by ras0219-msft** [comment]
Hi @DragonOsman, thanks for reporting this issue!

It looks like the clone process was incomplete; this error log indicates that `toolsrc\dirs.proj` doesn't exist.

Could you remove `C:\Windows\System32\vcpkg` and re-clone it into a directory like `C:\src\vcpkg`, then try again?

**Comment by jeanga** [comment]
Hi!

I just got this same error on two separate machine (with one "fresh" git clone) since yesterday commits.

Consistently reproes on Windows 10, VS2017 (latest).

Here is what I got:
Microsoft (R) Build Engine version 15.5.180.51428 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: dirs.proj

Thanks for any help!
Jean

**Comment by jeanga** [comment]
After more testing, my profile.ps1 is changing current directory and that did not please the setup.
Once that part is commented. All is fine!

**Comment by DragonOsman** [comment]
The issue is resolved for me as well.  It was a while ago, though, and I don't remember what I did exactly.  I'm sorry about that.

**Comment by ras0219-msft** [comment]
We've also been steadily improving bootstrap in the meantime, so it's quite possible we fixed your issue accidentally :)
