### ISSUE TITLE
[gdal] does not build for arm (32bit android versions arm-android and x86-android)

### ISSUE THREAD

**Issue by m-kuhn** [microsoft/vcpkg#20875]
**Host Environment**
- OS: Linux
- Compiler: r21e

**To Reproduce**
`./vcpkg install gdal`

**Failure logs** 
Does not build on arm

First line of the portfile disables support for arm (32bit)
https://github.com/microsoft/vcpkg/blob/master/ports/gdal/portfile.cmake#L1

Same happens for x86 (32bit), where the failure happens in cfitsio with

>     static_assert( sizeof(OFF_T) == 8, "OFF_T should be 64 bits !" );

https://github.com/OSGeo/gdal/blob/aeef8c81dfb7017bb6fb9277e375277f555a2d9a/gdal/frmts/fits/fitsdataset.cpp

---------------

The simplest approach would be to disable the `cfitsio` dependency on these two platforms. Is there a possibility to filter by these triplets (`arm-android` and `x86-android`) in `vcpkg.json`? I only found examples of complete platforms (e.g. `windows`) and not triplets, architectures or bits.

**Comment by JackBoosY** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
