### ISSUE TITLE
support clang-cl optionally

### ISSUE THREAD

**Issue by ghost** [microsoft/vcpkg#2087]
Specifically, OpenBLAS requires clang to build the assembly. It would be nice if vcpkg would optionally allow OpenBLAS to be built with clang-cl.

**Comment by liuzijing97** [comment]
Clang has better support for modern cpp,  and more powerful optmization.
Clang matures enough to compile productive code on windows and it even has binary compatibility with msvc.
vcpkg use cmake to generate ninja file. supporting clang-cl optionally and experimentally may be fine.

**Comment by donny-dont** [comment]
Has anyone gotten this to work? I prefer using cl considering the major improvements that have been made with it. However I think I found a bug with cl when building in Docker that doesn't appear to be a problem with clang so it would be nice to check.

**Comment by Neumann-A** [comment]
you could try #4609 but you need to install the llvm toolset in visual studio

**Comment by Neumann-A** [comment]
https://github.com/Neumann-A/my-vcpkg-triplets

has triplets for clang-cl (llvm) although not all ports are supporting clang-cl currently. For MSBuild ports you need to have the llvm extension installed.

**Comment by PhoebeHui** [comment]
We recommend to create a custome triplet instead. 
Related to https://github.com/microsoft/vcpkg/issues/12292.
