### ISSUE TITLE
[boost-thread] vcpkg causes __pRawDllMain regression by auto-linking library in static builds

### ISSUE THREAD

**Issue by jdx-john** [microsoft/vcpkg#20898]
I've been searching for ages to find out why MFC calls like `AfxGetResourceHandle` were suddenly failing in our DLLs, after we switched to vcpkg... the DLL uses no 3rd-party libs but with vpkg enabled the DLL size grew about 40Kb and these calls failed. We link to vcpkg ports statically, but to MFC as a shared DLL (Static-MD triplet.)

After some low-level digging, it turns out __pRawDllMain is being linked from boost-thread:

> Searching C:\vcpkg\installed\\x86-windows-vs2019-static-md\lib\boost_thread-vc140-mt.lib:
>       Found __pRawDllMain
>         Referenced in msvcrt.lib(dll_dllmain.obj)
>         Loaded boost_thread-vc140-mt.lib(tss_pe.obj)

I tested by temporarily removing this .lib file and rebuilding, that the problem went away. 

It's a known issue and there are two workarounds I have seen: https://stackoverflow.com/questions/3466944/upgrade-of-boost-1-35-to-1-43-causes-linker-error-with-prawdllmain-mfc-relate

1. change the link-order so boost_thread-vc140-mt.lib is linked after mfcs140u.lib
2. explicitly `#include <boost/thread/win32/mfc_thread_init.hpp>`

Since vcpkg uses auto-link, option 1. seems a very ugly kludge. And considering our project doesn't _use_ boost, explicitly adding an #include seems pretty awful too. Since we only see regressions at run-time, we'd have to go adding this into many projects.

Is there any way to resolve this from a vcpkg angle? For instance, why are vcpkg port libs not linked _after_ everything else... is there a way to do this?

Also see issue I raised on boost: https://github.com/boostorg/thread/issues/360

**Comment by JackBoosY** [comment]
As @Neumann-A said, all libraries containing function definitions in the system library should be placed in the _manual-link_ folder.

**Comment by MonicaLiu0311** [comment]
Will close issue because #32309.
