### ISSUE TITLE
hwloc update to 2.6 (it has native CMake support)

### ISSUE THREAD

**Issue by bgoglin** [microsoft/vcpkg#20899]
Library name: hwloc
New version number: 2.6

Hello
I am the upstream maintainer of hwloc. I was told about this project and we had some users requesting native CMake support for building hwloc on Windows. So I took your CMakeLists.txt as a base, updated it to hwloc 2.6 and added some additional features. See https://github.com/open-mpi/hwloc/pull/484

Differences between your CMakeLists.txt and mine:
* I commented-out your snprintf/strtoull reenabling because we had some issues with them in the past, and I don't know how to make sure we're not running on such old/broken build environment. It shoudn't hurt much anyway.
* I didn't apply any change that is currently in portfile.cmake because I am not why they are needed and why they are not in CMakeLists.txt
* all tools and lstopo are now built but may be disabled with HWLOC_SKIP_LSTOPO and HWLOC_SKIP_TOOLS
* I install these tools in bin/ instead tools/hwloc/ (if you need a way to customize that, let me know).
* dolib.c isn't needed *inside* the library, it's an external tool that helps linking the library on MinGW

If you have some feedback before I release hwloc 2.6 officially next week, I'll be happy to update the CMakeLists. Otherwise we'll update it in future releases.

In the future, I'd like to be able to rename libhwloc.dll into libhwloc-15.dll to match other builds. If there's a need to disable that, let me know.

**Comment by Neumann-A** [comment]
Is the CMakeLists.txt limited to windows or can it be used on all platforms? If it is limited to windows: Why is it limited?

**Comment by bgoglin** [comment]
It's only for Windows. For other platforms, autoconf works fine, duplicating everything in cmake would require a lot of work, and nobody requested it.

**Comment by Neumann-A** [comment]
So i get hwloc 2.5 to build nativ on windows for x64-windows-static. The x64-windows build fails with: `LINK : fatal error LNK1104: cannot open file '.libs/libhwloc.def'`. The reason for that is that somewhere hwloc is passing `--output-def` for that. Have to check how fontconfig solved shared libraries in the past.

**Comment by FunMiles** [comment]
@bgoglin I would like to know if a more complete CMake system could be made? I use CMake exclusively for my code development and previously integrated hwloc via Conan. Unfortunately, conan is in transition from v1 to v2 and they temporarily stopped maintaining the plugin from my IDE (CLion). To avoid some pain, I decided to use the `FetchContent` feature of CMake to bring hwloc in my latest project. I failed at doing it with the autotools system and had to create a fork with a CMakeLists.txt for Mac OS. My fork is at https://github.com/FunMiles/hwloc
Compared to the version you made for Windows, created a MacOS CMakeLists.txt with a few things updated to more modern/flexible CMake. It would be great if that same file could handle at least Windows and Linux as well. I can easily test/tune for Mac and Linux but am not well versed with Windows to do much good.

Having a correct CMakeLists.txt allows to consume hwloc in CMake projects (with CMake >= 3.24) very easily:

```
    include(FetchContent)

    FetchContent_Declare(
            hwloc
            GIT_REPOSITORY https://github.com/FunMiles/hwloc.git
            GIT_TAG 251864c1795cf07146981842d2aa4de270f907f5 # based on release-2.8.0
            OVERRIDE_FIND_PACKAGE
    )
    find_package(hwloc)
    target_link_library(my_executable PRIVATE hwloc)
```

**Comment by bgoglin** [comment]
@FunMiles yes that's possible, but I am not good at CMake, hence it'll be good to keep it simple (so that I can maintain it without too much trouble)

**Comment by FunMiles** [comment]
@bgoglin I can help a lot with CMake. I have not dug into much of how hwloc works however, so when things break I will probably need help. My new code using the approach outlined above compiles and link but crashes on an assert, which is of course frustrating...
````cpp
assert(hwloc_filter_check_keep_object(topology, obj));
```

**Comment by FunMiles** [comment]
@bgoglin I am making a new post as I know you won't get notified if I edit the above.
It seems that the MacOS version of hwloc will crash in the above assert if compiled with HWLOC_DEBUG set to 1.
It happens with the autotools compiled version. Should I make a new issue about it? I am turning that flag off for my fork.

**Comment by bgoglin** [comment]
@FunMiles I cannot reproduce the failed assert on our old mac that runs the CI, neither on a M1. Can you open a proper issue at https://github.com/open-mpi/hwloc/issues ? One thing to try first: rebuild without debug, check that lstopo works, then export HWLOC_DEBUG_CHECK=1 in the environment and check that lstopo fails the assert. If so, do "lstopo foo.xml" without the export and attach foo.xml to the issue.

We may also want to move the reminder of the issue to another issue at https://github.com/open-mpi/hwloc/issues to avoid discussion no-vcpkg-related things here.

Regarding the configuration file, you may want to ignore a lot of autotools tests because those are related to operating systems that are old or likely won't care about CMake anytime soon. I can try to build a list of things you really want to detect for MacOS.

**Comment by Neumann-A** [comment]
Please move the discussion. This is really not a vcpkg topic ;)

**Comment by FunMiles** [comment]
@bgoglin I opened an issue on hwloc repository demonstrating how to trigger the issue. What is the proper way to start a discussion on the CMakeLists.txt over there? @JackBoosY 's help would be welcome.
@Neumann-A  Agreed 😄 . We'll work on this on the hwloc side.

**Comment by bgoglin** [comment]
@funmiles the cmake discussion should just be another issue on hwloc's github, thanks.

**Comment by JackBoosY** [comment]
@FunMiles Can you please cc me on that issue or provide the issue link here?

**Comment by FrankXie05** [comment]
https://github.com/open-mpi/hwloc/issues/565 @JackBoosY
