### ISSUE TITLE
[New Port Request] MIT Kerberos (krb5)

### ISSUE THREAD

**Issue by geraldcombs** [microsoft/vcpkg#20903]
Library name: krb5

Library description: MIT Kerberos Version 5, a network authentication system

Source repository URL: https://github.com/krb5/krb5

Project homepage (if different from the source repository): https://web.mit.edu/kerberos/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

Windows build instructions can be found at https://github.com/krb5/krb5/tree/master/src/windows

**Comment by PhoebeHui** [comment]
@anonymousr007, sorry for late response, I assigned this issue to you, we're happy to accept a PR for this！

**Comment by JackBoosY** [comment]
@anonymousr007 Can you please open a PR to add this port?

Thanks.

**Comment by JackBoosY** [comment]
@anonymousr007 Any updates?

**Comment by Cheney-W** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
