### ISSUE TITLE
[libsquish] build failure in ARM (Apple M1)

### ISSUE THREAD

**Issue by david-antiteum** [microsoft/vcpkg#20930]
**Host Environment**
- OS: macOS ARM
- Compiler: Xcode 13.0

**To Reproduce**
`./vcpkg install libsquish`

**Additional context**

libsquish uses by default SSE2 instructions by default. The portfile requires this for ARM builds:

```make
vcpkg_configure_cmake(
    ...
    OPTIONS
        -DBUILD_SQUISH_WITH_SSE2=OFF
    ...
```

Thanks,

**Comment by treellama** [comment]
I don't think upstream is going to fix this--the library hasn't been updated in years. Will vcpkg not accept patches to fix builds on community triplets?

**Comment by JackBoosY** [comment]
@treellama  For the source code changes, we should have the upstream approval.

**Comment by treellama** [comment]
Is there a policy for how to handle libraries which don't have upstream maintainers? Out of all the vcpkg ports this can't be the only one

**Comment by david-antiteum** [comment]
@JackBoosY The problem is still there and the solution (-DBUILD_SQUISH_WITH_SSE2=OFF) works without changing the lib code at all. I this an aceptable solution (in portfile.cmake) ?

```
if( VCPKG_TARGET_ARCHITECTURE MATCHES "aarch64|arm64|arm64v8" )
    set( EXTRA_OPTIONS "-DBUILD_SQUISH_WITH_SSE2=OFF" )
endif()

vcpkg_cmake_configure(
    SOURCE_PATH ${SOURCE_PATH}
    DISABLE_PARALLEL_CONFIGURE
    OPTIONS
        ${EXTRA_OPTIONS}
)
```

**Comment by JackBoosY** [comment]
@david-antiteum This can be considered.

**Comment by JackBoosY** [comment]
Okay, please use command `./vcpkg install libsquish[core]` to build this port on arm-osx.
