### ISSUE TITLE
[libevent] install failure empty bin/ folder

### ISSUE THREAD

**Issue by silverqx** [microsoft/vcpkg#20945]
**Host Environment**
- OS: Linux

**To Reproduce**
It is only reproducible with `x64-linux-dynamic` triplet:
`./vcpkg install libevent:x64-linux-dynamic`

**Failure logs** 
```
-- Performing post-build validation
There should be no empty directories in /home/silverqx/Code/c/vcpkg_test/packages/libevent_x64-linux-dynamic
The following empty directories were found:

/home/silverqx/Code/c/vcpkg_test/packages/libevent_x64-linux-dynamic/bin

If a directory should be populated but is not, this might indicate an error in the portfile.
If the directories are not needed and their creation cannot be disabled, use something like this in the portfile to remove them:

file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/a/dir" "${CURRENT_PACKAGES_DIR}/some/other/dir")


Found 1 error(s). Please correct the portfile:
```

**Additional context**
I have temporary added to `libevent/portfile.cmake`:
```
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/bin")
```

This problem is specific to Linux only, on Windows and MSYS2 `bin/` folder contains `.dll` libs.
What would be the best solution to run this command on UNIX systems only ? I'm thinking about `if(UNIX)`, `if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")` or do you have any better solution for this?

**Comment by JonLiu1993** [comment]
@silverqx ,I used the latest vcpkg to try to reproduce this error again. I was surprised to find that this problem seems to no longer exist in the latest vcpkg. Can you try it with the latest vcpkg locally?

**Comment by silverqx** [comment]
For me still reproducible `./vcpkg install libevent:x64-linux-dynamic`:
[install.log.zip](https://github.com/microsoft/vcpkg/files/7466917/install.log.zip)

**Comment by silverqx** [comment]
Did you try dynamic linkage on linux? @JonLiu1993

**Comment by JonLiu1993** [comment]
> Did you try dynamic linkage on linux? @JonLiu1993

of course

**Comment by silverqx** [comment]
For me it even fails with `libevent[thread]` or with `libevent[thread,openssl]`, so all possible cases fail because of that empty /bin dir, of course tried on master, but we have a good PR so it will be ok after merge.

**Comment by dg0yt** [comment]
From install.log.zip:
~~~
The following packages will be built and installed:
libevent[core,thread]:x64-linux-dynamic -> 2.1.12#2
~~~

This is not the fixed port version.

**Comment by silverqx** [comment]
> This is not the fixed port version.

And that is correct, it is still reproducible on the vcpkg master and the proposing PR will fix it. 😂
