### ISSUE TITLE
Lua port does not publish all required headers to use the published header lua.h

### ISSUE THREAD

**Issue by SethBe** [microsoft/vcpkg#20942]
The current package publishes lua.h, but does not include the full chain of headers required to include lua.h successfully.

Lua.h has a dependency on lua_State defined in lstate.h.
lstate.h requires lobject.h, ltm.h, lzio.h.
lobject.h requires  llimts.h 
and finally lzio.h requires lmem.h.

Also lapi.h is a fairly commonly used header so I would love to have that added as well.

In short my ask is that we include Lapi.h, llimits.h, lmem.h, lobject.h, lstate.h, ltm.h, lzio.h in all revsions. So that this package can be consumed.

**Comment by michaelkroener** [comment]
Usually only 3 headers are public headers lua can be fully used without the other headers used to build lua only if you want to do more advanced stuff for example using the lua lexer manually do you actually need the other headers but in that case its usually enough to use something like minilua a single c file implementation of lua and including that in your tool or well building lua your self and having it as add_subdirectory in your CMake structure. 
Functions not in the 3 public headers are as far as I know implementation details / internals and should not be used by the end user.

**Comment by PhoebeHui** [comment]
@SethBe, please reopen this issue if it still be a question for you.
