### ISSUE TITLE
Error: Building package openblas:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by husseinalihazime** [Microsoft/vcpkg#2095]
Building suitesparse error

**Comment by xoviat** [comment]
Yes, openblas does not support 32 bit builds. If you want, then submit a PR to fix that.

**Comment by husseinalihazime** [comment]
Hello, I have a 64bit machine. How to install the openblas for 64bits on the vcpkg?

Best Regards,
Hussein Hazime

________________________________

**Comment by xoviat** [comment]
`vcpkg install suitesparse:x64-windows`.
