### ISSUE TITLE
Install fails when vcpkg is built with gcc-6

### ISSUE THREAD

**Issue by isaactorz** [microsoft/vcpkg#20982]
**Describe the bug**
When attempting to install an arbitrary package, using an instance of vcpkg built with gcc-6.3, the install will fail after post-built validation. The error is `No such file or directory` while trying to remove the x64-linux.zip artifact.

This bug has been observed in Ubuntu 20.04 LTS, and in CI using the debian-stretch-slim image.

**Environment**
- OS: Ubuntu 20.04 LTS, and in CI using the debian-stretch-slim image
- Compiler: GCC 6.3

**To Reproduce**
(install and set gcc-6)
1. echo "deb http://old-releases.ubuntu.com/ubuntu zesty main" | sudo tee /etc/apt/sources.list.d/zesty.list
2. sudo apt update
3. sudo apt install g++-6
4. export CC=gcc-6 CXX=g++-6
5. ./vcpkg/bootstrap-vcpkg.sh
6. ./vcpkg/vcpkg install gtest

**Expected behavior**
Expected packages to install successfully.

**Failure logs** 
The following is the content of a vcpkg-manifest-install.log, but the bug and output is the same when running any install.

Detecting compiler hash for triplet x64-linux...
The following packages will be built and installed:
    fmt[core]:x64-linux -> 8.0.1
    gtest[core]:x64-linux -> 1.11.0
  \* vcpkg-cmake[core]:x64-linux -> 2021-09-13
  \* vcpkg-cmake-config[core]:x64-linux -> 2021-09-27
Additional packages (*) will be modified to complete this operation.
Restored 1 packages from /home/parallels/.cache/vcpkg/archives in 64.69 ms. Use --debug to see more details.
Starting package 1/4: vcpkg-cmake-config:x64-linux
Building package vcpkg-cmake-config[core]:x64-linux...
\-- Installing: /home/parallels/sandbox/vcpkg-gcc6/source/vcpkg/packages/vcpkg-cmake-config_x64-linux/share/vcpkg-cmake-config/vcpkg_cmake_config_fixup.cmake
\-- Installing: /home/parallels/sandbox/vcpkg-gcc6/source/vcpkg/packages/vcpkg-cmake-config_x64-linux/share/vcpkg-cmake-config/vcpkg-port-config.cmake
\-- Installing: /home/parallels/sandbox/vcpkg-gcc6/source/vcpkg/packages/vcpkg-cmake-config_x64-linux/share/vcpkg-cmake-config/copyright
\-- Performing post-build validation
\-- Performing post-build validation done
remove(/home/parallels/sandbox/vcpkg-gcc6/source/vcpkg/buildtrees/vcpkg-cmake-config/x64-linux.zip): No such file or directory

**Comment by isaactorz** [comment]
Confirm update has fixed this issue.

**Comment by BillyONeal** [comment]
Thanks!
