### ISSUE TITLE
[wxwidgets] build issue

### ISSUE THREAD

**Issue by fishnet37222** [microsoft/vcpkg#20983]
**Host Environment**
- OS: [Linux]
- Compiler: gcc 9.3.0

**To Reproduce**
`./vcpkg install wxwidgets`

**Failure logs** 
There are no failure logs.

**Additional context**
This is not technically a build failure since issuing the command above succeeds without any noticeable errors.  However, use it with CMake, the configure step fails with the message below:

```
[cmake] CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
[cmake] Please set them or make sure they are set and tested correctly in the CMake files:
[cmake] -ldep_name
[cmake]     linked by target "minesweeper" in directory /home/dave/Projects/minesweeper
```
I noticed that the line of output starting with `Found wxWidgets` contains the offending bit of text:
```
[cmake] -- Found wxWidgets:...-ldep_name-NOTFOUND;... (found version "3.1.5") 
```
That line of output is generated by the `wx-config` utility, which uses the script located at `[vcpkg root]/installed/x64-linux/debug/lib/wx/config/gtk3-unicode-static-3.1`.  If you open that script up in a text editor and look at line 1032, you'll see that same "NOTFOUND" text.

When I downloaded the source directly from the wxWidgets web-site and compiled it myself, the corresponding script did not have that "NOTFOUND" text which leads me to believe that something in the wxWidgets port is failing to report a missing dependency.

**Comment by dg0yt** [comment]
I assume I resolved this issue already.

**Comment by Cheney-W** [comment]
@fishnet37222 Does this issue still exist?

**Comment by fishnet37222** [comment]
I just checked, and it appears that this specific issue is no longer occurring.
