### ISSUE TITLE
vcpkg can't install opencv2 

### ISSUE THREAD

**Issue by yungteng** [microsoft/vcpkg#20998]
Hello, World,  Ｉcna't install opencv2 by vcpkg, the error log as the below, anyidea?

---------------------------------------------------------------------------------------------------
C:\src\vcpkg>vcpkg install opencv2 --triplet=x64-windows
Computing installation plan...
The following packages will be built and installed:
  * eigen3[core]:x64-windows -> 3.3.9#1
  * libjpeg-turbo[core]:x64-windows -> 2.0.6#2
  * liblzma[core]:x64-windows -> 5.2.5#3
  * libpng[core]:x64-windows -> 1.6.37#15
    opencv2[core,eigen,jpeg,png,tiff]:x64-windows -> 2.4.13.7#6
  * tiff[core,jpeg,lzma,zip]:x64-windows -> 4.3.0#2
  * vcpkg-cmake[core]:x64-windows -> 2021-09-13
  * vcpkg-cmake-config[core]:x64-windows -> 2021-09-27
  * zlib[core]:x64-windows -> 1.2.11#13
Additional packages (*) will be modified to complete this operation.
Warning: The following VS instances are excluded because the English language pack is unavailable.
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
Please install the English language pack.
Detecting compiler hash for triplet x64-windows...
A suitable version of git was not found (required v2.32.0). Downloading portable git v2.32.0...
Downloading git...
  https://github.com/git-for-windows/git/releases/download/v2.32.0.windows.2/PortableGit-2.32.0.2-32-bit.7z.exe -> C:\src\vcpkg\downloads\PortableGit-2.32.0.2-32-bit.7z.exe
Extracting git...
A suitable version of 7zip was not found (required v19.0.0). Downloading portable 7zip v19.0.0...
Downloading 7zip...
  https://www.7-zip.org/a/7z1900-x64.msi -> C:\src\vcpkg\downloads\7z1900-x64.msi
Extracting 7zip...
A suitable version of powershell-core was not found (required v7.1.4). Downloading portable powershell-core v7.1.4...
Downloading powershell-core...
  https://github.com/PowerShell/PowerShell/releases/download/v7.1.4/PowerShell-7.1.4-win-x86.zip -> C:\src\vcpkg\downloads\PowerShell-7.1.4-win-x86.zip
Extracting powershell-core...
Restored 0 packages from C:\Users\BEN\AppData\Local\vcpkg\archives in 1.319 ms. Use --debug to see more details.
Starting package 1/9: eigen3:x64-windows
Building package eigen3[core]:x64-windows...
-- Downloading https://gitlab.com/libeigen/eigen/-/archive/3.3.9/eigen-3.3.9.tar.gz -> libeigen-eigen-3.3.9.tar.gz...
-- Extracting source C:/src/vcpkg/downloads/libeigen-eigen-3.3.9.tar.gz
-- Applying patch disable_pkgconfig_absolute_path_check.patch
-- Applying patch fix-cuda-error.patch
-- Using source at C:/src/vcpkg/buildtrees/eigen3/src/3.3.9-c395fd9e7c.clean
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: ninja -v
    Working Directory: C:/src/vcpkg/buildtrees/eigen3/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\src\vcpkg\buildtrees\eigen3\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:368 (vcpkg_execute_required_process)
  ports/eigen3/portfile.cmake:15 (vcpkg_configure_cmake)
  scripts/ports.cmake:142 (include)

Error: Building package eigen3:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: eigen3:x64-windows
  Vcpkg version: 2021-09-10-2059ef11aa6067e6f59b0d939c5d17e3c5c47d3e

Additionally, attach any relevant sections from the log files above.

----------------------------------------------------------------------------------------------------------

Please create a discussion in https://github.com/microsoft/vcpkg/discussions/new instead.

**Comment by yungteng** [comment]
Please check below, Thanks.
----------------------------------------------------------------
[1/2] cmd /c "cd ../../x64-windows-dbg && "C:/Program
Files/CMake/bin/cmake.exe"
"C:/src/vcpkg/buildtrees/eigen3/src/3.3.9-c395fd9e7c.clean"
"-DBUILD_TESTING=OFF" "-DEIGEN_BUILD_PKGCONFIG=ON"
"-DCMAKE_MAKE_PROGRAM=C:/src/vcpkg/downloads/tools/ninja/1.10.2-windows/ninja.exe"
"-DBUILD_SHARED_LIBS=ON"
"-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/src/vcpkg/scripts/toolchains/windows.cmake"
"-DVCPKG_TARGET_TRIPLET=x64-windows" "-DVCPKG_SET_CHARSET_FLAG=ON"
"-DVCPKG_PLATFORM_TOOLSET=v140" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON"
"-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON"
"-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON"
"-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE"
"-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF"
"-DCMAKE_TOOLCHAIN_FILE=C:/src/vcpkg/scripts/buildsystems/vcpkg.cmake"
"-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS="
"-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS="
"-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG="
"-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS="
"-DVCPKG_LINKER_FLAGS_RELEASE=" "-DVCPKG_LINKER_FLAGS_DEBUG="
"-DVCPKG_TARGET_ARCHITECTURE=x64" "-DCMAKE_INSTALL_LIBDIR:STRING=lib"
"-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=C:/src/vcpkg"
"-D_VCPKG_INSTALLED_DIR=C:/src/vcpkg/installed"
"-DVCPKG_MANIFEST_INSTALL=OFF"
"-DCMAKEPACKAGE_INSTALL_DIR=C:/src/vcpkg/packages/eigen3_x64-windows/debug/share/eigen3"
"-DPKGCONFIG_INSTALL_DIR=C:/src/vcpkg/packages/eigen3_x64-windows/debug/lib/pkgconfig"
"-G" "Ninja" "-DCMAKE_BUILD_TYPE=Debug"
"-DCMAKE_INSTALL_PREFIX=C:/src/vcpkg/packages/eigen3_x64-windows/debug""
FAILED: ../../x64-windows-dbg/CMakeCache.txt
cmd /c "cd ../../x64-windows-dbg && "C:/Program Files/CMake/bin/cmake.exe"
"C:/src/vcpkg/buildtrees/eigen3/src/3.3.9-c395fd9e7c.clean"
"-DBUILD_TESTING=OFF" "-DEIGEN_BUILD_PKGCONFIG=ON"
"-DCMAKE_MAKE_PROGRAM=C:/src/vcpkg/downloads/tools/ninja/1.10.2-windows/ninja.exe"
"-DBUILD_SHARED_LIBS=ON"
"-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/src/vcpkg/scripts/toolchains/windows.cmake"
"-DVCPKG_TARGET_TRIPLET=x64-windows" "-DVCPKG_SET_CHARSET_FLAG=ON"
"-DVCPKG_PLATFORM_TOOLSET=v140" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON"
"-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON"
"-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON"
"-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE"
"-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF"
"-DCMAKE_TOOLCHAIN_FILE=C:/src/vcpkg/scripts/buildsystems/vcpkg.cmake"
"-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS="
"-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS="
"-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG="
"-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS="
"-DVCPKG_LINKER_FLAGS_RELEASE=" "-DVCPKG_LINKER_FLAGS_DEBUG="
"-DVCPKG_TARGET_ARCHITECTURE=x64" "-DCMAKE_INSTALL_LIBDIR:STRING=lib"
"-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=C:/src/vcpkg"
"-D_VCPKG_INSTALLED_DIR=C:/src/vcpkg/installed"
"-DVCPKG_MANIFEST_INSTALL=OFF"
"-DCMAKEPACKAGE_INSTALL_DIR=C:/src/vcpkg/packages/eigen3_x64-windows/debug/share/eigen3"
"-DPKGCONFIG_INSTALL_DIR=C:/src/vcpkg/packages/eigen3_x64-windows/debug/lib/pkgconfig"
"-G" "Ninja" "-DCMAKE_BUILD_TYPE=Debug"
"-DCMAKE_INSTALL_PREFIX=C:/src/vcpkg/packages/eigen3_x64-windows/debug""
-- The C compiler identification is MSVC 19.0.24245.0
-- The CXX compiler identification is MSVC 19.0.24245.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual
Studio 14.0/VC/bin/amd64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual
Studio 14.0/VC/bin/amd64/cl.exe - broken
CMake Error at C:/Program
Files/CMake/share/cmake-3.21/Modules/CMakeTestCCompiler.cmake:69 (message):
  The C compiler

    "C:/Program Files (x86)/Microsoft Visual Studio
14.0/VC/bin/amd64/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir:
C:/src/vcpkg/buildtrees/eigen3/x64-windows-dbg/CMakeFiles/CMakeTmp

    Run Build
Command(s):C:/src/vcpkg/downloads/tools/ninja/1.10.2-windows/ninja.exe
cmTC_bf7a4 && [1/2] Building C object
CMakeFiles\cmTC_bf7a4.dir\testCCompiler.c.obj
    [2/2] Linking C executable cmTC_bf7a4.exe
    FAILED: cmTC_bf7a4.exe
    cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E
vs_link_exe --intdir=CMakeFiles\cmTC_bf7a4.dir --rc=rc
--mt=CMAKE_MT-NOTFOUND --manifests  --
C:\PROGRA~2\MICROS~1.0\VC\bin\amd64\link.exe /nologo
CMakeFiles\cmTC_bf7a4.dir\testCCompiler.c.obj  /out:cmTC_bf7a4.exe
/implib:cmTC_bf7a4.lib /pdb:cmTC_bf7a4.pdb /version:0.0 /machine:x64
 /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib
winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib
advapi32.lib && cd ."
    RC Pass 1: command "rc /fo CMakeFiles\cmTC_bf7a4.dir/manifest.res
CMakeFiles\cmTC_bf7a4.dir/manifest.rc" failed (exit code 0) with the
following output:
    系统找不到指定的文件。
    ninja: build stopped: subcommand failed.





  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:1 (project)


-- Configuring incomplete, errors occurred!
See also
"C:/src/vcpkg/buildtrees/eigen3/x64-windows-dbg/CMakeFiles/CMakeOutput.log".
See also
"C:/src/vcpkg/buildtrees/eigen3/x64-windows-dbg/CMakeFiles/CMakeError.log".
[2/2] cmd /c "cd .. && "C:/Program Files/CMake/bin/cmake.exe"
"C:/src/vcpkg/buildtrees/eigen3/src/3.3.9-c395fd9e7c.clean"
"-DBUILD_TESTING=OFF" "-DEIGEN_BUILD_PKGCONFIG=ON"
"-DCMAKE_MAKE_PROGRAM=C:/src/vcpkg/downloads/tools/ninja/1.10.2-windows/ninja.exe"
"-DBUILD_SHARED_LIBS=ON"
"-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/src/vcpkg/scripts/toolchains/windows.cmake"
"-DVCPKG_TARGET_TRIPLET=x64-windows" "-DVCPKG_SET_CHARSET_FLAG=ON"
"-DVCPKG_PLATFORM_TOOLSET=v140" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON"
"-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON"
"-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON"
"-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE"
"-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF"
"-DCMAKE_TOOLCHAIN_FILE=C:/src/vcpkg/scripts/buildsystems/vcpkg.cmake"
"-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS="
"-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS="
"-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG="
"-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS="
"-DVCPKG_LINKER_FLAGS_RELEASE=" "-DVCPKG_LINKER_FLAGS_DEBUG="
"-DVCPKG_TARGET_ARCHITECTURE=x64" "-DCMAKE_INSTALL_LIBDIR:STRING=lib"
"-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=C:/src/vcpkg"
"-D_VCPKG_INSTALLED_DIR=C:/src/vcpkg/installed"
"-DVCPKG_MANIFEST_INSTALL=OFF"
"-DCMAKEPACKAGE_INSTALL_DIR=C:/src/vcpkg/packages/eigen3_x64-windows/share/eigen3"
"-DPKGCONFIG_INSTALL_DIR=C:/src/vcpkg/packages/eigen3_x64-windows/lib/pkgconfig"
"-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release"
"-DCMAKE_INSTALL_PREFIX=C:/src/vcpkg/packages/eigen3_x64-windows""
FAILED: ../CMakeCache.txt
cmd /c "cd .. && "C:/Program Files/CMake/bin/cmake.exe"
"C:/src/vcpkg/buildtrees/eigen3/src/3.3.9-c395fd9e7c.clean"
"-DBUILD_TESTING=OFF" "-DEIGEN_BUILD_PKGCONFIG=ON"
"-DCMAKE_MAKE_PROGRAM=C:/src/vcpkg/downloads/tools/ninja/1.10.2-windows/ninja.exe"
"-DBUILD_SHARED_LIBS=ON"
"-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/src/vcpkg/scripts/toolchains/windows.cmake"
"-DVCPKG_TARGET_TRIPLET=x64-windows" "-DVCPKG_SET_CHARSET_FLAG=ON"
"-DVCPKG_PLATFORM_TOOLSET=v140" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON"
"-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON"
"-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON"
"-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE"
"-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF"
"-DCMAKE_TOOLCHAIN_FILE=C:/src/vcpkg/scripts/buildsystems/vcpkg.cmake"
"-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS="
"-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS="
"-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG="
"-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS="
"-DVCPKG_LINKER_FLAGS_RELEASE=" "-DVCPKG_LINKER_FLAGS_DEBUG="
"-DVCPKG_TARGET_ARCHITECTURE=x64" "-DCMAKE_INSTALL_LIBDIR:STRING=lib"
"-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=C:/src/vcpkg"
"-D_VCPKG_INSTALLED_DIR=C:/src/vcpkg/installed"
"-DVCPKG_MANIFEST_INSTALL=OFF"
"-DCMAKEPACKAGE_INSTALL_DIR=C:/src/vcpkg/packages/eigen3_x64-windows/share/eigen3"
"-DPKGCONFIG_INSTALL_DIR=C:/src/vcpkg/packages/eigen3_x64-windows/lib/pkgconfig"
"-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release"
"-DCMAKE_INSTALL_PREFIX=C:/src/vcpkg/packages/eigen3_x64-windows""
-- The C compiler identification is MSVC 19.0.24245.0
-- The CXX compiler identification is MSVC 19.0.24245.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual
Studio 14.0/VC/bin/amd64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual
Studio 14.0/VC/bin/amd64/cl.exe - broken
CMake Error at C:/Program
Files/CMake/share/cmake-3.21/Modules/CMakeTestCCompiler.cmake:69 (message):
  The C compiler

    "C:/Program Files (x86)/Microsoft Visual Studio
14.0/VC/bin/amd64/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir:
C:/src/vcpkg/buildtrees/eigen3/x64-windows-rel/CMakeFiles/CMakeTmp

    Run Build
Command(s):C:/src/vcpkg/downloads/tools/ninja/1.10.2-windows/ninja.exe
cmTC_c9956 && [1/2] Building C object
CMakeFiles\cmTC_c9956.dir\testCCompiler.c.obj
    [2/2] Linking C executable cmTC_c9956.exe
    FAILED: cmTC_c9956.exe
    cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E
vs_link_exe --intdir=CMakeFiles\cmTC_c9956.dir --rc=rc
--mt=CMAKE_MT-NOTFOUND --manifests  --
C:\PROGRA~2\MICROS~1.0\VC\bin\amd64\link.exe /nologo
CMakeFiles\cmTC_c9956.dir\testCCompiler.c.obj  /out:cmTC_c9956.exe
/implib:cmTC_c9956.lib /pdb:cmTC_c9956.pdb /version:0.0 /machine:x64
 /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib
winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib
advapi32.lib && cd ."
    RC Pass 1: command "rc /fo CMakeFiles\cmTC_c9956.dir/manifest.res
CMakeFiles\cmTC_c9956.dir/manifest.rc" failed (exit code 0) with the
following output:
    系统找不到指定的文件。
    ninja: build stopped: subcommand failed.





  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:1 (project)


-- Configuring incomplete, errors occurred!
See also
"C:/src/vcpkg/buildtrees/eigen3/x64-windows-rel/CMakeFiles/CMakeOutput.log".
See also
"C:/src/vcpkg/buildtrees/eigen3/x64-windows-rel/CMakeFiles/CMakeError.log".
ninja: build stopped: subcommand failed.

**Comment by JonLiu1993** [comment]
@yungteng ,Thanks for posting this issue,
Make sure Visual Studio has the following installed:

Desktop Development with C++
One of the Windows SDKs, preferably the latest
English Language Pack

**Comment by JonLiu1993** [comment]
@yungteng, have you tested the suggestion?

**Comment by JonLiu1993** [comment]
Closing this issue for now since there is no active thread for a long time. Please feel free to reopen this issue if it is still a problem for you.

**Comment by yungteng** [comment]
dear sender,
 sorry, it's a busy time for not yet trying the suggestion, will try
as soon as possible, thanks for your help

1. Desktop Development with C++
2. One of the Windows SDKs, preferably the latest
3. English Language Pack
