### ISSUE TITLE
Add libzmq (ZeroMQ)

### ISSUE THREAD

**Issue by roalz** [Microsoft/vcpkg#21]
http://zeromq.org/intro:get-the-software
https://github.com/zeromq/libzmq

**Comment by adam4813** [comment]
Just so no one else starts this, I have to just commit this when I get home however it will only work nicely with the master branch which has no release tags to use specifically.

**Comment by traversaro** [comment]
@adam4813 If you are interested in it, I had a version that almost worked with the latest release in https://github.com/traversaro/vcpkg_playground/tree/master/zeromq . Furthermore I had also a working port of `cppzmq` in https://github.com/traversaro/vcpkg_playground/tree/master/cppzmq , feel free to use/modify them, I do not plan to work on them at the moment.

**Comment by adam4813** [comment]
I went a simpler route and just used the provided build files. It works I
just didn't have time to commit my code and submit a PR.
