### ISSUE TITLE
[zlib:x64-windows-static] build failure

### ISSUE THREAD

**Issue by Sariaki** [microsoft/vcpkg#21006]
**Host Environment**
- OS: [Windows]
- Compiler: revision

**To Reproduce**
`vcpkg install cpr`

**Failure logs** 
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: ninja -v
    Working Directory: D:/dev/vcpkg/buildtrees/zlib/x64-windows-static-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\dev\vcpkg\buildtrees\zlib\config-x64-windows-static-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:368 (vcpkg_execute_required_process)
  ports/zlib/portfile.cmake:23 (vcpkg_configure_cmake)
  scripts/ports.cmake:142 (include)

**Additional context**
Error: Building package zlib:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zlib:x64-windows-static
  Vcpkg version: 2021-09-10-2059ef11aa6067e6f59b0d939c5d17e3c5c47d3

[config-x64-windows-static-out.log](https://github.com/microsoft/vcpkg/files/7420747/config-x64-windows-static-out.log)

**Comment by Sariaki** [comment]
> Looks same issue with [#7067 (comment)](https://github.com/microsoft/vcpkg/issues/7067#issuecomment-506728267), could you try the solution provided in the issue and see if it works?
I looked into my system path variable and couldn't find any paths to anything visual studio related, so i added `C:\Program Files (x86)\Windows Kits\10\Lib\10.0.19041.0\ucrt\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community;
`, rebooted and tried running vcpkg install zlib:x64-windows-static --debug with no success and the same error.
[error.txt](https://github.com/microsoft/vcpkg/files/7446723/error.txt)

**Comment by Sariaki** [comment]
reinstalling the windows sdk 10.0.19041.0 has also not changed anything

**Comment by sfhacker** [comment]
Are we STILL having issues with zlib? We haven't been able to reproduce this issue locally.
@Sariaki Most probably your environment is broken somehow!

**Comment by PhoebeHui** [comment]
@Sariaki, sorry for the late response, from your failure log, it looks the latest windows sdk version is 10.0.20348.0 in your machine, so reinstalling windows sdk 10.0.19041.0 doesn't work.

Could you install 10.0.20348.0 VS installer and try again? I double confirmed, zlib built successfully with it. Just for curious, why do you install multi windows sdks?

```
WindowsLibPath=C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.20348.0;C:\Program Files (x86)\Windows Kits\10\References\10.0.20348.0
WindowsSdkBinPath=C:\Program Files (x86)\Windows Kits\10\bin\
WindowsSdkDir=C:\Program Files (x86)\Windows Kits\10\
WindowsSDKLibVersion=10.0.20348.0\
WindowsSdkVerBinPath=C:\Program Files (x86)\Windows Kits\10\bin\10.0.20348.0\
WindowsSDKVersion=10.0.20348.0\
```

**Comment by Sariaki** [comment]
> @Sariaki, sorry for the late response, from your failure log, it looks the latest windows sdk version is 10.0.20348.0 in your machine, so reinstalling windows sdk 10.0.19041.0 doesn't work.
> 
> Could you install 10.0.20348.0 VS installer and try again? I double confirmed, zlib built successfully with it. Just for curious, why do you install multi windows sdks?
> 
> ```
> WindowsLibPath=C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.20348.0;C:\Program Files (x86)\Windows Kits\10\References\10.0.20348.0
> WindowsSdkBinPath=C:\Program Files (x86)\Windows Kits\10\bin\
> WindowsSdkDir=C:\Program Files (x86)\Windows Kits\10\
> WindowsSDKLibVersion=10.0.20348.0\
> WindowsSdkVerBinPath=C:\Program Files (x86)\Windows Kits\10\bin\10.0.20348.0\
> WindowsSDKVersion=10.0.20348.0\
> ```
I tried looked into my visual studio installer and it said i only have the windows sdk 10.0.19041.0 installed, installing 10.0.20348.0 didn't change anything.
I'm beginning to suspect that this issue is somehow being caused by me installing and uninstalling visual studio 2022 a while back, since i remember using vcpkg at one point before.

**Comment by PhoebeHui** [comment]
It looks your environment is broken, I suggest you uninstall all windows sdks, and only install the latest windows sdk that provided by VS installer and try again.

**Comment by Sariaki** [comment]
this fixed it, thank you!
