### ISSUE TITLE
[EasyHook] allow static triplet

### ISSUE THREAD

**Issue by lanyizi** [microsoft/vcpkg#21011]
EasyHook is a library that support function hooking (even from managed code, although it's not related with current issue which only deals with unmanaged case) and DLL injection, and it's available on vcpkg.

Currently vcpkg will refuse to install EasyHook under `static` triplets, it's explicitly disabled on the first line of port file (see below) and `vcpkg.json`:
https://github.com/microsoft/vcpkg/blob/d8b9fa9a535de1d3b4effe8fca5c18f573af88e8/ports/easyhook/portfile.cmake#L1
That sounds reasonable. as EasyHook has to be a dynamic library in order to work.

However, for example I wish to build my "injector" and "injected dll" as "self-contained" targets, which try to not require any external dependencies. So I would link everything statically, including 3rd-party library from vcpkg, and I would use a static triplet. Of course, with the exception of EasyHook, as itself has to remain to be a dynamic library. Unfortunately vcpkg currently refuses to install it in the static triplet.

By removing `ON_LIBRARY_LINKAGE "static"`  and adding `set(VCPKG_POLICY_DLLS_IN_STATIC_LIBRARY enabled)` in the port file, EasyHook can be installed in the static triplet. It will still build as a dynamic library just like the non-static triplet.
EasyHook is also a self-contained library, it only references system DLLs, it does not reference the CRT dll (even in the "dynamic" triplets), so it will be safe to use under static triplets.

Previously I achieved that by using locally-modified port files, but that will making future upgrades more difficult (I still have my `CONTROL` file instead of the new `vcpkg.json`), and it will also cause issues when other people are trying to build my project.

So, could I make a pull request to allow static triplets for EasyHook?

PS: Besides the question above, currently EasyHook on vcpkg seems to require MFC, as it has a `#include "afxres.h"` (which seems to be a MFC header) in its resource file. It can actually be safely substituted with `windows.h`. EasyHook has already fixed this issue (https://github.com/EasyHook/EasyHook/issues/210), but the author haven't made a new release yet. 
In the meantime, could we mitigate that by using `fix-build.patch`?

**Comment by JackBoosY** [comment]
So can this issue be closed by "fixed"?

**Comment by lanyizi** [comment]
I think yes, closing it now
