### ISSUE TITLE
[eastl] update to 3.18.00

### ISSUE THREAD

**Issue by tusharb86** [microsoft/vcpkg#21010]
Library name: eastl

New version number: 3.18.00

Other information that may be useful (release notes, etc...)
https://github.com/electronicarts/EASTL/releases/tag/3.18.00

Thanks!

**Comment by tusharb86** [comment]
@JonLiu1993 @NancyLi1013 @BillyONeal - I was just using the eastl port as an example to teach a colleague about vcpkg and noticed that the commit hash of eastl was not updated in the `portfile.cmake` in #21014. The commit ref should be `e8bdd5531ed79c30ccef2fd71e070f5ab9f1222a`.

Here is what I see on the current 'master' branch:
https://github.com/microsoft/vcpkg/blob/master/ports/eastl/portfile.cmake#L6
```
    REF 41bd2e4466e33b979d2afc37f9b98dacf1eab50b #v 3.17.03
    SHA512 3011a0a08701b683e22cc624167b4f65fce8b16d0f7a03675f6a1d5b02313c5b763bcc6c8091f65728ed60ceee8d585cbdb1968a35fb24954f4f66afabb23865
```

Can we re-open the issue, please? Thanks!

**Comment by BillyONeal** [comment]
> the commit hash of eastl was not updated in the `portfile.cmake` in #21014.

Yikes! Sorry for missing that!

**Comment by JonLiu1993** [comment]
> @JonLiu1993 @NancyLi1013 @BillyONeal - I was just using the eastl port as an example to teach a colleague about vcpkg and noticed that the commit hash of eastl was not updated in the `portfile.cmake` in #21014. The commit ref should be `e8bdd5531ed79c30ccef2fd71e070f5ab9f1222a`.
> 
> Here is what I see on the current 'master' branch: https://github.com/microsoft/vcpkg/blob/master/ports/eastl/portfile.cmake#L6
> 
> ```
>     REF 41bd2e4466e33b979d2afc37f9b98dacf1eab50b #v 3.17.03
>     SHA512 3011a0a08701b683e22cc624167b4f65fce8b16d0f7a03675f6a1d5b02313c5b763bcc6c8091f65728ed60ceee8d585cbdb1968a35fb24954f4f66afabb23865
> ```
> 
> Can we re-open the issue, please? Thanks!

I am sorry to make this low-level mistake, I have submitted a new pr #21315  to fix it, thank you very much for your correction

**Comment by tusharb86** [comment]
> I am sorry to make this low-level mistake, I have submitted a new pr #21315 to fix it, thank you very much for your correction

@JonLiu1993 - No worries! It happens. Thanks for the quick fix!
