### ISSUE TITLE
fontconfig:x64-windows build failure

### ISSUE THREAD

**Issue by Darkshadows9** [microsoft/vcpkg#21038]
**Host Environment**
- OS: Windows 10 Pro 19042.1288
- Compiler: Unsure, I believe vcpkg is picking up Visual Studio 2019's default, but I do have GCC installed and on path.

**To Reproduce**
```vcpkg install gtk:x64-windows``` though ```vcpkg install fontconfig:x64-windows``` does the exact same thing.

**Failure logs** 
```
C:\vcpkg>vcpkg install gtk:x64-windows
Computing installation plan...
The following packages will be built and installed:
  * cairo[core,fontconfig,freetype,gobject]:x64-windows -> 1.17.4#2
  * fontconfig[core]:x64-windows -> 2.13.94
  * gdk-pixbuf[core]:x64-windows -> 2.42.2#1
    gtk[core]:x64-windows -> 4.3.0
  * libsass[core]:x64-windows -> 3.6.5
  * pango[core]:x64-windows -> 1.48.4#1
  * sassc[core]:x64-windows -> 3.6.2
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Restored 0 packages from C:\Users\Darkshadows\AppData\Local\vcpkg\archives in 398.6 us. Use --debug to see more details.
Starting package 1/7: fontconfig:x64-windows
Building package fontconfig[core]:x64-windows...
-- Using cached fontconfig-fontconfig-2.13.94.tar.gz.
-- Cleaning sources at C:/vcpkg/buildtrees/fontconfig/src/2.13.94-6fd83e1cbe.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg/downloads/fontconfig-fontconfig-2.13.94.tar.gz
-- Using source at C:/vcpkg/buildtrees/fontconfig/src/2.13.94-6fd83e1cbe.clean
-- Found external ninja('1.10.2').
-- Getting CMake variables for x64-windows
-- Using cached msys-mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst.
-- Using msys root at C:/vcpkg/downloads/tools/msys2/aa5af7b2aa7e90e8
-- Configuring x64-windows-dbg
-- Configuring x64-windows-dbg done
-- Configuring x64-windows-rel
-- Configuring x64-windows-rel done
-- Package x64-windows-dbg
-- Package x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" install -v
    Working Directory: C:/vcpkg/buildtrees/fontconfig/x64-windows-rel
    Error code: 1
    See logs for more information:
      C:\vcpkg\buildtrees\fontconfig\package-x64-windows-rel-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_meson.cmake:58 (vcpkg_execute_required_process)
  ports/fontconfig/portfile.cmake:17 (vcpkg_install_meson)
  scripts/ports.cmake:142 (include)


Error: Building package fontconfig:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: fontconfig:x64-windows
  Vcpkg version: 2021-09-10-2059ef11aa6067e6f59b0d939c5d17e3c5c47d3e

Additionally, attach any relevant sections from the log files above.
```
[package-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/7434489/package-x64-windows-rel-out.log)

**Additional context**
Had previously done ```vcpkg install gtk``` to install the x86 version, which seemed to succeed, but when trying the x64 version, fontconfig seems to be the thing that causes the cascade failure. I've tried deleting the cached tar.gz for fontconfig, with no change. I updated myself as of an hour ago with bootstrap-vcpkg.bat and ```vcpkg update``` (which keeps telling me it's using local ports. I did manually download the ports.) I only first downloaded the vcpkg repository about 2(?) days ago.  I've pasted the command prompt output and the mentioned log file above.

**Comment by JackBoosY** [comment]
@Darkshadows9  I'm pretty sure your Windows 10 SDK has some problems.
Please re-install it.

**Comment by Darkshadows9** [comment]
Went ahead and uninstalled all of the SDK's before reinstalling only 10.0.19041.0 using the Visual Studio Installer. Same exact results trying to rebuild.

**Comment by JackBoosY** [comment]
Can you please run the following command and provide the output?
1. Using cmd:
```cmd
cd C:\vcpkg\buildtrees\fontconfig\x64-windows-rel\fc-cache\
fc-cache.exe
```

2. Using Visual Studio Developer Command Prompt:
```cmd
cd C:\vcpkg\buildtrees\fontconfig\x64-windows-rel\fc-cache\
dumpbin /DEPENDENTS fc-cache.exe
```

**Comment by JackBoosY** [comment]
I don’t know why your generated fc-cache depends on fontconfig-1.dll, we need more in-depth investigation.

**Comment by JackBoosY** [comment]
@Neumann-A Can you please take a look?
I confirmed `fc-cache.exe` requires `fontconfig-1.dll` and this dll not exist in the executable path.
The meson config is in _fc-cache/meson.build_ line 10:
```
# Do not try to execute target's fc-cache on host when cross compiling
if not meson.is_cross_build()
  meson.add_install_script(fccache, '-s', '-f', '-v')
endif
```
But I can't repro this issue.

**Comment by Darkshadows9** [comment]
> 
> 
> I don’t know why your generated fc-cache depends on fontconfig-1.dll, we need more in-depth investigation.

If there's anything I can do to help the investigation, just let me know. 🙂

**Comment by Neumann-A** [comment]
the dep on fontconfig-1.dll is normal. The question is rather why it cannot find the dll. Normally meson should setup the path variable accordingly

```
E:\vcpkg_folders\master\installed\x64-windows\tools\fontconfig>dumpbin fc-cache.exe /DEPENDENTS
Microsoft (R) COFF/PE Dumper Version 14.29.30136.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file fc-cache.exe

File Type: EXECUTABLE IMAGE

  Image has the following dependencies:

    fontconfig-1.dll
    KERNEL32.dll
    VCRUNTIME140.dll
    api-ms-win-crt-filesystem-l1-1-0.dll
    api-ms-win-crt-stdio-l1-1-0.dll
    api-ms-win-crt-runtime-l1-1-0.dll
    api-ms-win-crt-math-l1-1-0.dll
    api-ms-win-crt-locale-l1-1-0.dll
    api-ms-win-crt-heap-l1-1-0.dll

  Summary

        1000 .data
        1000 .pdata
        2000 .rdata
        1000 .reloc
        2000 .text

```

**Comment by Neumann-A** [comment]
Check if `C:\vcpkg\buildtrees\fontconfig\x64-windows-rel\src` contains `fontconfig-1.dll`

**Comment by Darkshadows9** [comment]
That directory does contain fontconfig-1.dll.

**Comment by Darkshadows9** [comment]
Just curious if there's any updates or anything I could do to help either reset my installation or the investigation.

**Comment by JackBoosY** [comment]
In my log:
```
(if false; then \
    echo "fc-cache.exe -s -f -v"; \
    fc-cache/fc-cache.exe -s -f -v; \
else \
    echo "***"; \
    echo "*** Warning: fonts.cache not built"; \
    echo "***"; \
    echo "*** Generate this file manually on host system using fc-cache"; \
    echo "***"; \
fi)
```

**Comment by Darkshadows9** [comment]
Here's the first two files:
[cmake-vars-x64-windows-dbg.cmake.log](https://github.com/microsoft/vcpkg/files/7573198/cmake-vars-x64-windows-dbg.cmake.log)
[config-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/7573202/config-x64-windows-dbg-out.log)

And here are the two files in the specified folder:
[install-log.txt](https://github.com/microsoft/vcpkg/files/7573204/install-log.txt)
[meson-log.txt](https://github.com/microsoft/vcpkg/files/7573205/meson-log.txt)

**Comment by JackBoosY** [comment]
The only differences are Visual Studio path and ninja path.

**Comment by JackBoosY** [comment]
@BillyONeal @ras0219-msft Can you please figure this out?

Thanks.

**Comment by LilyWangLL** [comment]
Ping @BillyONeal @ras0219-msft, could you please take a look this issue? Thanks in advance.

**Comment by BillyONeal** [comment]
> Ping @BillyONeal @ras0219-msft, could you please take a look this issue? Thanks in advance.

I don't think either of us are going to have much insight here.

**Comment by JackBoosY** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.

**Comment by openFDEM-project** [comment]
Hi Jack @JackBoosY ,
I think I meet the same problem with @Darkshadows9 when I installed fontconfig on Windows. I tried to x86 version or static, the same problme raise.

-- Cleaning sources at D:/vcpkg/buildtrees/fontconfig/src/2.14.2-7f52ee670b.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/vcpkg/downloads/fontconfig-fontconfig-2.14.2.tar.gz
-- Applying patch no-etc-symlinks.patch
-- Applying patch libgetopt.patch
-- Applying patch fix-preprocessor-clang-cl.patch
-- Using source at D:/vcpkg/buildtrees/fontconfig/src/2.14.2-7f52ee670b.clean
-- Found external ninja('1.10.2').
-- Getting CMake variables for x64-windows-static-md
-- Configuring x64-windows-static-md-dbg
-- Using cached mingw-w64-x86_64-pkgconf-1~2.1.0-1-any.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.4.9-3-x86_64.pkg.tar.zst.
-- Using msys root at D:/vcpkg/downloads/tools/msys2/023cdb3ca06f77f2
-- Configuring x64-windows-static-md-dbg done
-- Configuring x64-windows-static-md-rel
-- Configuring x64-windows-static-md-rel done
-- Package x64-windows-static-md-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: "D:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" install -v
    Working Directory: D:/vcpkg/buildtrees/fontconfig/x64-windows-static-md-dbg
    Error code: 1
    See logs for more information:
      D:\vcpkg\buildtrees\fontconfig\package-x64-windows-static-md-dbg-out.log


[error-logs-x64-windows.txt](https://github.com/microsoft/vcpkg/files/13698936/error-logs-x64-windows.txt)
[package-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/13698942/package-x64-windows-dbg-err.log)

Many thanks.

**Comment by JackBoosY** [comment]
@openFDEM-project Please provide _D:\vcpkg\buildtrees\fontconfig\package-x64-windows-static-md-dbg-out.log_ instead.

**Comment by openFDEM-project** [comment]
Hi, @JackBoosY ,
Please find below 
[config-x64-windows-static-md-dbg-out.log](https://github.com/microsoft/vcpkg/files/13703757/config-x64-windows-static-md-dbg-out.log)
Many thanks.

**Comment by JackBoosY** [comment]
@openFDEM-project I need **package**-x64-windows-static-md-dbg-out.log.

**Comment by openFDEM-project** [comment]
@JackBoosY 
[package-x64-windows-static-md-dbg-out.log](https://github.com/microsoft/vcpkg/files/13712316/package-x64-windows-static-md-dbg-out.log)

**Comment by jackgoodman2** [comment]
It is a little weird, because the failure installation of fontconfig package, I almost can not install any qt-like packages, such as qt, cairo, osg, freecascade and so on on windows platform. I tried all the solutions I can get from google but it doesnot work. I also unistalled vcpkg and reinstall, it still no work.

**Comment by openFDEM-project** [comment]
It is a little weird, because the failure installation of fontconfig package, I almost can not install any qt-like packages, such as qt, cairo, osg, freecascade and so on on windows platform. I tried all the solutions I can get from google but it doesnot work. I also unistalled vcpkg and reinstall, it still no work.

**Comment by JackBoosY** [comment]
```
../src/2.14.2-7f52ee670b.clean/src/fccompat.c(134): error C2065: 'mode_t': undeclared identifier
```
@LilyWangLL can you please take a look at this?

**Comment by LilyWangLL** [comment]
> @LilyWangLL can you please take a look at this?

I will take a look.
