### ISSUE TITLE
[gtk] Allow selection of GTK3 in addition to GTK4

### ISSUE THREAD

**Issue by Darkshadows9** [microsoft/vcpkg#21039]
****

**Is your feature request related to a problem? Please describe.**
As GTK3 is still actively supported and is the latest version the Glade editor supports, it would be nice if there was some way to select the latest version of it, as GTK4 does break compatibility majorly.

**Proposed solution**
I found what appears to me to be a good solution proposal described [here](https://github.com/microsoft/vcpkg/issues/20471#issuecomment-934119328), which I gather is being able to select a version of the port. The current workaround is to replace the port folder for gtk, which I have yet to verify if it works or not.

**Describe alternatives you've considered**
My first gut instinct wasn't the above, it was simply to specify the extra install name as "gtk3" instead, as both versions could need to be accessed globally for separate projects.

**Additional context**
I got nothin'. I'm new to this project and just looking around for solutions.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

**Comment by nlogozzo** [comment]
@Darkshadows9  Hopefully it gets added as a new port soon #22201

**Comment by Febbe** [comment]
Yep, rolling back is not an option. Please reopen this.

**Comment by JonLiu1993** [comment]
Fixed by PR #27026

**Comment by vserdyuk** [comment]
Would love to see gtkmm3 too: https://github.com/microsoft/vcpkg/issues/28085
