### ISSUE TITLE
having trouble pinning versions of tbb

### ISSUE THREAD

**Issue by ViksitAgarwal** [microsoft/vcpkg#21034]
Here is my vcpkg.json

{
    "$schema": "https://raw.githubusercontent.com/microsoft/vcpkg/master/scripts/vcpkg.schema.json",
    "name": "main",
    "version": "0.1.0",
    "dependencies": [
      "gtest",
      "cpprestsdk",
      "tbb",
      "librabbitmq",
      "hiredis"
    ],
    "builtin-baseline":"9d892ff9270f2d2fe3b8e490471f0a7dfa78981e",
    "overrides": [
      { "name": "cpprestsdk", "version": "2.10.14" },
      { "name": "tbb", "version-string": "2019_U8" },
      { "name": "librabbitmq", "version": "0.9.0" }
    ]
}

Below is the console output with error. Tried with many different version formats and values that look valid, also tried cleaning up and starting all over again, nothing helped.

-- Downloading https://github.com/intel/tbb/archive/4bdba61bafc6ba2d636f31564f1de5702d365cf7.tar.gz -> intel-tbb-4bdba61bafc6ba2d636f31564f1de5702d365cf7.tar.gz...
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' = off
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Downloading https://github.com/intel/tbb/archive/4bdba61bafc6ba2d636f31564f1de5702d365cf7.tar.gz
Error: Failed to download from mirror set:
File does not have the expected hash:
             url : [ https://github.com/intel/tbb/archive/4bdba61bafc6ba2d636f31564f1de5702d365cf7.tar.gz ]
       File path : [ D:\GIT\vcpkg\downloads\intel-tbb-4bdba61bafc6ba2d636f31564f1de5702d365cf7.tar.gz.44620.part ]
   Expected hash : [ 0b00c9deefdac5dc1f4fbae314e91eb3513b54b47ff6dec08ed2460486fc7d211ab36d6130e5787bfd50523cb613c65f03f9217d967292ca9056e2d3f5010bf8 ]
     Actual hash : [ f2a8d7e0476f846039390f4a79af3fe13770e23b01bf4741e738136f7ddb401357a0e50f35212e8d0fa5fc4cf1563418337309227d7243fc3676edd406ae652d ]

[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(626)
[DEBUG] Exiting after 10.47 s us (10323353 us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:83 (message):

      Failed to download file with error: 1
      If you use a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.

      3. You proxy's remote server is out of service.
[vcpkg-manifest-install.log](https://github.com/microsoft/vcpkg/files/7433076/vcpkg-manifest-install.log)

      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)

      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:274 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_github.cmake:173 (vcpkg_download_distfile)
  buildtrees/versioning/versions/tbb/3be5c111cb01595f1b786724e6d53fd0d8df7e92/portfile.cmake:7 (vcpkg_from_github)
  scripts/ports.cmake:142 (include)

Error: Building package tbb:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: tbb:x64-windows
  Vcpkg version: 2021-09-10-2059ef11aa6067e6f59b0d939c5d17e3c5c47d3e

Additionally, attach any relevant sections from the log files above.
-- Running vcpkg install - failed
CMake Error at D:/GIT/vcpkg/scripts/buildsystems/vcpkg.cmake:831 (message):
  vcpkg install failed.  See logs for more information:
  D:\GIT\MyProject\build\windows-vs2019\vcpkg-manifest-install.log
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.21/Modules/CMakeDetermineSystem.cmake:124 (include)
  CMakeLists.txt:7 (project
[vcpkg-manifest-install.log](https://github.com/microsoft/vcpkg/files/7433085/vcpkg-manifest-install.log)
)

**Comment by PhoebeHui** [comment]
@ViksitAgarwal, sorry for my late response, I take a look at the history off tbb, the tbb repo changed, so it causes hash changed  for older version, related to https://github.com/microsoft/vcpkg/pull/10456. I suggest you use more newer version instead, or you use an [overlay port](https://github.com/microsoft/vcpkg/blob/master/docs/specifications/ports-overlay.md) instead.

**Comment by PhoebeHui** [comment]
Please reopen this issue if it still be a question for you.
