### ISSUE TITLE
Error: Building package zlib:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by GeorgeBohw** [Microsoft/vcpkg#2105]
I execute the following cmd:
./vcpkg install folly:x64-windows,
then it automatically install dependies zlib:x64-windows which occur errors:
-- Build x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:43 (message):
    Command failed: E:/vcpkg/downloads/cmake-3.9.4-win32-x86/bin/cmake.exe;--build;.;--config;Release;--target;install;--;-v
    Working Directory: E:/vcpkg/buildtrees/zlib/x64-windows-rel
    See logs for more information:
      E:\vcpkg\buildtrees\zlib\install-x64-windows-rel-out.log
      E:\vcpkg\buildtrees\zlib\install-x64-windows-rel-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:62 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/zlib/portfile.cmake:26 (vcpkg_install_cmake)
  scripts/ports.cmake:72 (include)

Error: Building package zlib:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zlib:x64-windows
  Vcpkg version: 0.0.95-2017-11-01-fae64c544e86bfe327404b341b50d9e01dedea68

Additionally, attach any relevant sections from the log files above.

how do i need to do?

**Comment by GeorgeBohw** [comment]
the platform:win10   vs2015
install-x64-windows-rel-out.log:
FAILED: CMakeFiles/zlib.dir/win32/zlib1.res 
"E:/vcpkg/downloads/cmake-3.9.4-win32-x86/bin/cmcldeps.exe" RC E:\vcpkg\buildtrees\zlib\src\zlib-1.2.11\win32\zlib1.rc "CMakeFiles\zlib.dir\win32\zlib1.res.d" CMakeFiles\zlib.dir\win32\zlib1.res "עӢ: °��"C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe" C:\PROGRA~2\WI3CF2~1\10\bin\x64\rc.exe -DNO_FSEEKO -DZLIB_DLL -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_SECURE_NO_DEPRECATE -IE:\vcpkg\buildtrees\zlib\src\zlib-1.2.11 -IE:\vcpkg\buildtrees\zlib\x64-windows-rel /DWIN32 /foCMakeFiles\zlib.dir\win32\zlib1.res E:\vcpkg\buildtrees\zlib\src\zlib-1.2.11\win32\zlib1.rc
cl: 命令行 warning D9035 :cl: 命令行 error D8000 :cl: 命令行 error D8000 :cl: 命令行 error D8000

**Comment by FishOrBear** [comment]
I have the same problem

**Comment by GeorgeBohw** [comment]
i reinstall cmake-3.9 x64 version,but the problem still exist,can you give some details?
i run ./vcpkg install folly:x64-windows through powershell windows,
thanks

**Comment by GeorgeBohw** [comment]
i retry run :  ./vcpkg install folly,it runs successfully,under this condition,it install x86 version,
so does it mean i only can instll x86 version? if i want to install x64,how to do?

**Comment by GeorgeBohw** [comment]
it can't support x86 version folly,i have to install folly:x64-windows,but still error:

_Error: Building package zlib:x64-windows failed with: BUILD_FAILED_

?i have no idea ,any body give me a light!

**Comment by FishOrBear** [comment]
I think I can not explain this problem, because I can not install another computer

**Comment by FishOrBear** [comment]
I opened the vs installation and installed some of the C + + library, and then the problem is solved.

**Comment by GeorgeBohw** [comment]
thansk much

**Comment by ijesonchen** [comment]
@GeorgeBohw 
Will you check if there is a possibility that an Englished version of VS installed then resolved the problem?
