### ISSUE TITLE
nuget 5.10.0 does not respect the no_proxy env variable

### ISSUE THREAD

**Issue by cenit** [microsoft/vcpkg#21057]
this nuget version is broken for servers not behind proxy (listed in no_proxy env variable), when a proxy is set (with http_proxy env variable)

https://github.com/NuGet/Home/issues/10902

https://github.com/NuGet/NuGet.Client/pull/4079

Upgrading to 5.11 fixes the issue, will be opening a PR soon with this *urgent* fix

**Comment by jbogard** [comment]
I don't know where to raise this, but I also encountered this bug in the `dotnet nuget` tool (and related, `dotnet tool`). Updating to 5.11 for `nuget` fixed the plain `nuget install Foo` CLI way, but not `dotnet nuget`.

`dotnet nuget` shows `NuGet Command Line 6.0.0.278`. I'm .NET SDK version 6.0.100.

**Comment by jbogard** [comment]
And confirmed it's still broken on SDKs `6.0.200-preview.21607.2` and `6.0.101`.
