### ISSUE TITLE
[New Port Request] qthttpserver

### ISSUE THREAD

**Issue by bouffa** [microsoft/vcpkg#21053]
Library name: qthttpserver

Library description: Simple Qt based Http server library with several essential features 

Source repository URL: https://github.com/qt-labs/qthttpserver

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
