### ISSUE TITLE
[lapack-reference] build failure

### ISSUE THREAD

**Issue by cenit** [microsoft/vcpkg#21060]
due to tool update (i assume) there is an error with gfortran-built libraries validation (tool checks for .lib but lapack-reference creates a .dll.a)

```
Starting package 93/159: lapack-reference:x64-windows
Building package lapack-reference[blas-select,core,noblas]:x64-windows...
-- Using cached Reference-LAPACK-lapack-v3.8.0.tar.gz.
-- Extracting source F:/vcpkg/downloads/Reference-LAPACK-lapack-v3.8.0.tar.gz
-- Using source at F:/vcpkg/buildtrees/lapack-reference/src/v3.8.0-954f10683f.clean
-- The Fortran compiler identification is unknown
-- No Fortran compiler found on the PATH. Using MinGW gfortran!
-- Using cached msys-mingw-w64-x86_64-gcc-fortran-10.2.0-1-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-x86_64-gcc-libgfortran-10.2.0-1-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-x86_64-gcc-libs-10.2.0-1-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-x86_64-gmp-6.2.0-1-any.pkg.tar.xz.
-- Using cached msys-mingw-w64-x86_64-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-x86_64-winpthreads-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-x86_64-mpc-1.1.0-1-any.pkg.tar.xz.
-- Using cached msys-mingw-w64-x86_64-mpfr-4.1.0-2-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-x86_64-gcc-10.2.0-1-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-x86_64-binutils-2.34-3-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-x86_64-crt-git-8.0.0.5966.f5da805f-1-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-x86_64-headers-git-8.0.0.5966.f5da805f-1-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-x86_64-libiconv-1.16-2-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-x86_64-windows-default-manifest-6.4-3-any.pkg.tar.xz.
-- Using cached msys-mingw-w64-x86_64-zlib-1.2.11-8-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-x86_64-zstd-1.4.5-1-any.pkg.tar.zst.
-- Using cached msys-gzip-1.10-1-x86_64.pkg.tar.xz.
-- Using cached msys-bash-4.4.023-2-x86_64.pkg.tar.xz.
-- Using cached msys-diffutils-3.7-1-x86_64.pkg.tar.xz.
-- Using cached msys-coreutils-8.32-1-x86_64.pkg.tar.xz.
-- Using cached msys-grep-3.0-2-x86_64.pkg.tar.xz.
-- Using cached msys-sed-4.8-1-x86_64.pkg.tar.xz.
-- Using cached msys-libpcre-8.44-1-x86_64.pkg.tar.xz.
-- Using cached msys-gawk-5.1.0-1-x86_64.pkg.tar.xz.
-- Using cached msys-mpfr-4.1.0-1-x86_64.pkg.tar.zst.
-- Using cached msys-gmp-6.2.0-1-x86_64.pkg.tar.xz.
-- Using cached msys-libreadline-8.0.004-1-x86_64.pkg.tar.xz.
-- Using cached msys-ncurses-6.2-1-x86_64.pkg.tar.xz.
-- Using cached msys-pkg-config-0.29.2-4-x86_64.pkg.tar.zst.
-- Using cached msys-make-4.3-1-x86_64.pkg.tar.xz.
-- Using cached msys-libintl-0.19.8.1-1-x86_64.pkg.tar.xz.
-- Using cached msys-libiconv-1.16-2-x86_64.pkg.tar.zst.
-- Using cached msys-gcc-libs-9.3.0-1-x86_64.pkg.tar.xz.
-- Using cached msys-msys2-runtime-3.2.0-8-x86_64.pkg.tar.zst.
-- Using msys root at F:/vcpkg/downloads/tools/msys2/456f7716e2893cfb
-- Found external ninja('1.10.2').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Fixing pkgconfig file: F:/vcpkg/packages/lapack-reference_x64-windows/lib/pkgconfig/blas.pc
-- Fixing pkgconfig file: F:/vcpkg/packages/lapack-reference_x64-windows/lib/pkgconfig/lapack.pc
-- Using cached msys-mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst.
-- Using msys root at F:/vcpkg/downloads/tools/msys2/aa5af7b2aa7e90e8
-- Fixing pkgconfig file: F:/vcpkg/packages/lapack-reference_x64-windows/debug/lib/pkgconfig/blas.pc
-- Fixing pkgconfig file: F:/vcpkg/packages/lapack-reference_x64-windows/debug/lib/pkgconfig/lapack.pc
-- Installing: F:/vcpkg/packages/lapack-reference_x64-windows/share/lapack-reference/copyright
-- Performing post-build validation
Import libs were not present in F:\vcpkg\packages\lapack-reference_x64-windows\debug/lib
If this is intended, add the following line in the portfile:
    SET(VCPKG_POLICY_DLLS_WITHOUT_LIBS enabled)
Import libs were not present in F:\vcpkg\packages\lapack-reference_x64-windows\lib
If this is intended, add the following line in the portfile:
    SET(VCPKG_POLICY_DLLS_WITHOUT_LIBS enabled)
Found 2 error(s). Please correct the portfile:
    F:\vcpkg\ports\lapack-reference\portfile.cmake
-- Performing post-build validation done
Error: Building package lapack-reference:x64-windows failed with: POST_BUILD_CHECKS_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: lapack-reference:x64-windows
  Vcpkg version: 2021-09-10-2059ef11aa6067e6f59b0d939c5d17e3c5c47d3e

Additionally, attach any relevant sections from the log files above.
```

**Comment by JackBoosY** [comment]
This needs to add the ELF check functions in `cofffilereader.cpp`.

**Comment by dg0yt** [comment]
> This needs to add the ELF check functions in `cofffilereader.cpp`. I think this is a good start for Linux post check.

I don't understand this point. How does the issue relate to linux?

What I see is using mingw naming conventions (`.dll.a`) instead of MSVC naming conventions (`.lib`) for import libs. Possibly due to:
~~~
-- The Fortran compiler identification is unknown
-- No Fortran compiler found on the PATH. Using MinGW gfortran!
~~~

**Comment by JackBoosY** [comment]
@dg0yt In the post check step, vcpkg will check the suffix of the library and the library file format. At this time, the code for checking the `.a` file format needs to be added.

**Comment by dg0yt** [comment]
@JackBoosY AFAIK `.dll.a` import libs (and `.a` static libs) are *not usable by MSVC*, so they are not valid for windows triplets and don't need to be checked in detail. 
The build happened to detect the error because no other `.lib` is present. But in fact there should be a check that no `.a` is present in (MSVC) windows triplet builds.

**Comment by JackBoosY** [comment]
@dg0yt Can `.dll.a` and `.a` be used in mingW? If yes, I think we still need to check.

**Comment by dg0yt** [comment]
> Can `.dll.a` and `.a` be used in mingW? 

Yes.

> If yes, I think we still need to check.

But then you are not dealing with COFF format or ELF format but with ar format.

~~~
$ file packages/curl_x64-mingw-dynamic/bin/libcurl.dll 
packages/curl_x64-mingw-dynamic/bin/libcurl.dll: PE32+ executable (DLL) (console) x86-64, for MS Windows
$ file packages/curl_x64-mingw-dynamic/lib/libcurl.dll.a 
packages/curl_x64-mingw-dynamic/lib/libcurl.dll.a: current ar archive
$ file packages/curl_x64-mingw-static/lib/libcurl.a 
packages/curl_x64-mingw-static/lib/libcurl.a: current ar archive
~~~

And this check is not needed for (non-mingw) windows triplets. You don't want `.a` files there.

**Comment by dg0yt** [comment]
> dll.a ... (fully compatible with MSVC)

@cenit Where do you take this from? 
- See above: .dll.a is an ar archive.
- We had some mingw builds (e.g. hdf5) naming mingw import libraries `.lib`, triggering "missing second linker"  member in vcpkg's policy check.

**Comment by dg0yt** [comment]
> we have many ports built by MSVC which depend on this library built by mingw, so I assume somehow it was working before!

I don't dispute that. But was it building with MinGW gfortran before?

**Comment by cenit** [comment]
> I don't dispute that. But was it building with MinGW gfortran before?

yes

**Comment by cenit** [comment]
> > dll.a ... (fully compatible with MSVC)
> 
> @cenit Where do you take this from?
> 
> * See above: .dll.a is an ar archive.
> * We had some mingw builds (e.g. hdf5) naming mingw import libraries `.lib`, triggering "missing second linker member" errors in vcpkg's policy check.

https://stackoverflow.com/questions/55610732/cmake-dll-vs-dll-a-vs-a-what-library-should-i-specify-in-the-cmake-configur
https://stackoverflow.com/questions/2096519/from-mingw-static-library-a-to-visual-studio-static-library-lib/2139061#2139061
https://stackoverflow.com/questions/6422478/linking-a-lib-and-def-files/6480464#6480464

just trying to recover things from my mind.
I remember having problems with static libraries/import libraries made by the "bare" MSYS2, but not from the MinGW layer on top of it

**Comment by dg0yt** [comment]
Okay. Accepting that .dll.a is compatible with MSVC.

~~~
-- Performing post-build validation
Import libs were not present in F:\vcpkg\packages\lapack-reference_x64-windows\debug/lib
...
Import libs were not present in F:\vcpkg\packages\lapack-reference_x64-windows\lib
~~~

Now in CI for lapack-reference[blas-select,core,noblas]:x64-windows, .lib and .dll.a exist side by side:
~~~
lapack-reference:/bin/liblapack.dll
lapack-reference:/debug/bin/liblapack.dll
lapack-reference:/debug/lib/lapack.lib
lapack-reference:/debug/lib/liblapack.dll.a
...
lapack-reference:/bin/liblapack.dll
lapack-reference:/lib/lapack.lib
lapack-reference:/lib/liblapack.dll.a
~~~

So your build with latest repo and tool doesn't create the .lib files?

**Comment by sfhacker** [comment]
We don't follow this open issue very well, but ... are we mixing toolchains here? Please, elaborate. Cheers,

**Comment by dg0yt** [comment]
I found one less common item in the fortran setup:
https://github.com/microsoft/vcpkg/blob/5bdb9d60123df20c247a1654e6a1def51d6c5140/scripts/cmake/vcpkg_find_fortran.cmake#L123-L124
`CMAKE_GNUtoMS` means 

> Convert GNU import libraries (.dll.a) to MS format (.lib).
> 
> When linking a shared library or executable that exports symbols using GNU tools on Windows (MinGW/MSYS) with Visual Studio installed convert the import library (.dll.a) from GNU to MS format (.lib). Both import libraries will be installed by install(TARGETS) and exported by install(EXPORT) and export() to be linked by applications with either GNU- or MS-compatible tools.

(https://cmake.org/cmake/help/v3.22/prop_tgt/GNUtoMS.html#prop_tgt:GNUtoMS)

This is what is passed on to mingw fortran in lapack-reference. 

This CMake feature relies on `lib.exe` from VS. Do you see such a step in verbose build?

Cf. https://github.com/Kitware/CMake/blob/master/Modules/Platform/Windows-GNU.cmake

**Comment by cenit** [comment]
ah yes that's the trick that was applied. Not that .dll.a were compatible, but that using the def file and a lib call (wrapped inside the CMAKE_GNUtoMS option) the lib appeared automagically.
Yes, somehow that's not working anymore. Something might have changed in CMake maybe? I was running with the latest update in that pipeline that failed.
Let me investigate it more.

**Comment by cenit** [comment]
@dg0yt thanks for helping me out diagnosing the issue

**Comment by cenit** [comment]
something very suspicious is going on
I cannot reproduce the issue anymore, not even on the "faulty" machine.
I don't know what happened during that run, unfortunately purging actions are very aggressive on that pipeline and so I cannot diagnose it more without reproducing the issue.

Closing the issue for now.
Thanks again @dg0yt for your time

**Comment by cenit** [comment]
Reopening: I found the culprit
Visual Studio 2022 Preview.

Using that compiler revision, CMakeGNUtoMS is broken. Probably because here https://github.com/Kitware/CMake/blob/master/Modules/Platform/Windows-GNU.cmake VS 17 is still not considered at all...

**Comment by cenit** [comment]
Merge request on upstream cmake already finished:
https://gitlab.kitware.com/cmake/cmake/-/merge_requests/6695

will be merged soon!

**Comment by JackBoosY** [comment]
This issue will be fixed by updating cmake version.
