### ISSUE TITLE
[libharu] syntax error: identifier 'HPDF_Boolean'

### ISSUE THREAD

**Issue by darke1891** [Microsoft/vcpkg#2106]
Hi, I use commit `fae64c5` of `vpkg` to try to install `VTK:x64-windows`, and I failed.
My OS is Windows 7. I use PowerShell 3.0 and VS 2015 Update 3.
In terminal, I get error message as follows.
``` powershell
-- Build x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:43 (messag
    Command failed: C:/Program Files/CMake/bin/cmake.exe;--build;.;--config;
    Working Directory: D:/dev/vcpkg/buildtrees/vtk/x64-windows-rel
    See logs for more information:
      D:\dev\vcpkg\buildtrees\vtk\install-x64-windows-rel-out.log
      D:\dev\vcpkg\buildtrees\vtk\install-x64-windows-rel-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:62 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/vtk/portfile.cmake:169 (vcpkg_install_cmake)
  scripts/ports.cmake:72 (include)


Error: Building package vtk:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: vtk:x64-windows
  Vcpkg version: 0.0.95-2017-11-01-fae64c544e86bfe327404b341b50d9e01dedea68
```

In `install-x64-windows-rel-out.log`, I find error message as follows:
``` powershell
D:\dev\vcpkg\installed\x64-windows\include\hpdf.h(464): error C2061: syntax error: identifier 'HPDF_Boolean'
```

In [portfile of libharu](https://github.com/Microsoft/vcpkg/blob/master/ports/libharu/portfile.cmake), I find that the commit it uses is `d84867ebf9f3de6afd661d2cdaff102457fbc371`. Actually, there is [an issue of this commit](https://github.com/libharu/libharu/issues/104) which covers this. Some guys suggested to change `HPDF_Boolean` to `HPDF_BOOL`, but this fix has not been accepted by authors. What's worse, it seems that there are no more updates of `libharu`, so maybe they have stopped development of libharu.

You can find another guy who got the same problem in the end of [this issue](2077)

**Comment by xoviat** [comment]
Can someone test #2128?
