### ISSUE TITLE
[bzip2:x64-windows] build failure

### ISSUE THREAD

**Issue by javibo590** [microsoft/vcpkg#21075]
**Host Environment**

    OS: Windows 10
    Compiler: Microsoft Visual Studio Community 2019 Version 16.6.5

**To Reproduce**
    vcpkg install bzip2:x64-windows

**Failure logs**
D:\Proyectos\ROS\catkin_ws>vcpkg install bzip2:x64-windows
Computing installation plan...
The following packages will be built and installed:
    bzip2[core]:x64-windows
Detecting compiler hash for triplet x64-windows...
Starting package 1/1: bzip2:x64-windows
Building package bzip2[core]:x64-windows...
Could not locate cached archive: C:\Users\T800\AppData\Local\vcpkg\archives\3c\3c0652163ae0ac78f85bf1acf87509bff06c8dcf.zip
-- Using cached C:/opt/ros/melodic/x64/tools/vcpkg/downloads/bzip2-1.0.6.tar.gz
-- Cleaning sources at C:/opt/ros/melodic/x64/tools/vcpkg/buildtrees/bzip2/src/1.0.6-8838f21f8e.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/opt/ros/melodic/x64/tools/vcpkg/downloads/bzip2-1.0.6.tar.gz
-- Applying patch fix-import-export-macros.patch
-- Applying patch fix-windows-include.patch
-- Using source at C:/opt/ros/melodic/x64/tools/vcpkg/buildtrees/bzip2/src/1.0.6-8838f21f8e.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Fixing pkgconfig
-- Acquiring MSYS Packages...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: C:/opt/ros/melodic/x64/tools/vcpkg/downloads/tools/msys2/msys64/usr/bin/bash.exe --noprofile --norc -c "pacman -S --noconfirm --needed pkg-config"
    Working Directory: C:/opt/ros/melodic/x64/tools/vcpkg/downloads/tools/msys2
    Error code: 1
    See logs for more information:
      C:\opt\ros\melodic\x64\tools\vcpkg\buildtrees\bzip2\msys-pacman-x64-windows-out.log
      C:\opt\ros\melodic\x64\tools\vcpkg\buildtrees\bzip2\msys-pacman-x64-windows-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_acquire_msys.cmake:153 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:281 (vcpkg_acquire_msys)
  ports/bzip2/portfile.cmake:51 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:79 (include)

Error: Building package bzip2:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: bzip2:x64-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.

D:\Proyectos\ROS\catkin_ws>

**logs files:**
**msys-pacman-x64-windows-err.log**
error: pkg-config: signature from "David Macek <david.macek.0@gmail.com>" is unknown trust
error: failed to commit transaction (invalid or corrupted package (PGP signature))

**msys-pacman-x64-windows-out.log**
resolving dependencies...
looking for conflicting packages...

Packages (1) pkg-config-0.29.2-4

Total Download Size:   0.20 MiB
Total Installed Size:  0.55 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
downloading pkg-config-0.29.2-4-x86_64.pkg.tar.zst...
checking keyring...
checking package integrity...
:: File /var/cache/pacman/pkg/pkg-config-0.29.2-4-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] 
Errors occurred, no packages were upgraded.

**Thanks¡**

**Comment by PhoebeHui** [comment]
@javibo590, could you get latest source via 'git pull' & 'bootstrap-vcpkg.bat' and try again? it looks your local is too old.

**Comment by javibo590** [comment]
Thank you very much for the quick answer. unfortunately the error continues to occur.
The problem is not in the Zlib2 library. the problem occurs when trying - Acquiring MSYS Packages ... You cannot reproduce the problem because you already have the MSYS Packages installed. Thanks

**Comment by javibo590** [comment]
I have checked Similar issue # 19204 and deleted msys2 directory from vcpkg / downloads / tools and rebuild again. the msys2 directory is generated correctly but later fails again at the same point. - Acquiring MSYS Packages ... 

D:\Proyectos\ROS\catkin_ws>vcpkg install bzip2:x64-windows
Computing installation plan...
The following packages will be built and installed:
    bzip2[core]:x64-windows
Detecting compiler hash for triplet x64-windows...
Starting package 1/1: bzip2:x64-windows
Building package bzip2[core]:x64-windows...
Could not locate cached archive: C:\Users\T800\AppData\Local\vcpkg\archives\63\634c5fa966c910424a62aa7ef78abc6afa545ad6.zip
-- Using cached C:/opt/ros/melodic/x64/tools/vcpkg/downloads/bzip2-1.0.6.tar.gz
-- Cleaning sources at C:/opt/ros/melodic/x64/tools/vcpkg/buildtrees/bzip2/src/1.0.6-8838f21f8e.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/opt/ros/melodic/x64/tools/vcpkg/downloads/bzip2-1.0.6.tar.gz
-- Applying patch fix-import-export-macros.patch
-- Applying patch fix-windows-include.patch
-- Using source at C:/opt/ros/melodic/x64/tools/vcpkg/buildtrees/bzip2/src/1.0.6-8838f21f8e.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Fixing pkgconfig
-- Acquiring MSYS2...
-- Using cached C:/opt/ros/melodic/x64/tools/vcpkg/downloads/msys2-base-x86_64-20190524.tar.xz
-- Using cached C:/opt/ros/melodic/x64/tools/vcpkg/downloads/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz
-- Using cached C:/opt/ros/melodic/x64/tools/vcpkg/downloads/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig
gpg: /etc/pacman.d/gnupg/trustdb.gpg: trustdb created
gpg: no ultimately trusted keys found
gpg: starting migration from earlier GnuPG versions
gpg: porting secret keys from '/etc/pacman.d/gnupg/secring.gpg' to gpg-agent
gpg: migration succeeded
gpg: Generating pacman keyring master key...
gpg: key 877F5A5A14D71959 marked as ultimately trusted
gpg: directory '/etc/pacman.d/gnupg/openpgp-revocs.d' created
gpg: revocation certificate stored as '/etc/pacman.d/gnupg/openpgp-revocs.d/7347C7AD614D6AB344865254877F5A5A14D71959.rev'
gpg: Done
==> Updating trust database...
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
==> Appending keys from msys2.gpg...
==> Locally signing trusted keys in keyring...
  -> Locally signing key D55E7A6D7CE9BA1587C0ACACF40D263ECA25678A...
  -> Locally signing key 123D4D51A1793859C2BE916BBBE514E53E0D0813...
  -> Locally signing key B91BCF3303284BF90CC043CA9F418C233E652008...
  -> Locally signing key 9DD0D4217D75A33B896159E6DA7EF2ABAEEA755C...
==> Importing owner trust values...
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: inserting ownertrust of 4
==> Updating trust database...
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   4  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: depth: 1  valid:   4  signed:   3  trust: 0-, 0q, 0n, 4m, 0f, 0u
gpg: depth: 2  valid:   3  signed:   0  trust: 3-, 0q, 0n, 0m, 0f, 0u
==> Checking C:/opt/ros/melodic/x64/tools/vcpkg/downloads/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig...
gpg: assuming signed data in 'C:/opt/ros/melodic/x64/tools/vcpkg/downloads/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz'
gpg: Signature made Mon Jun 29 07:36:14 2020
gpg:                using DSA key AD351C50AE085775EB59333B5F92EFC1A47D45A1
gpg: Good signature from "Alexey Pavlov (Alexpux) <alexpux@gmail.com>" [full]
loading packages...
resolving dependencies...
looking for conflicting packages...

Packages (1) msys2-keyring-r21.b39fb11-1

Total Installed Size:  0.05 MiB
Net Upgrade Size:      0.03 MiB

:: Proceed with installation? [Y/n]
checking keyring...
checking package integrity...
loading package files...
checking for file conflicts...
checking available disk space...
:: Processing package changes...
upgrading msys2-keyring...
==> Appending keys from msys2.gpg...
==> Locally signing trusted keys in keyring...
  -> Locally signing key 6E8FEAFF9644F54EED90EEA0790AE56A1D3CFDDC...
  -> Locally signing key D55E7A6D7CE9BA1587C0ACACF40D263ECA25678A...
  -> Locally signing key 123D4D51A1793859C2BE916BBBE514E53E0D0813...
  -> Locally signing key B91BCF3303284BF90CC043CA9F418C233E652008...
  -> Locally signing key 9DD0D4217D75A33B896159E6DA7EF2ABAEEA755C...
  -> Locally signing key 69985C5EB351011C78DF7F6D755B8182ACD22879...
==> Importing owner trust values...
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
==> Disabling revoked keys in keyring...
  -> Disabling key B19514FB53EB3668471B296E794DCF97F93FC717...
==> Updating trust database...
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   6  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: depth: 1  valid:   6  signed:   5  trust: 0-, 0q, 0n, 6m, 0f, 0u
gpg: depth: 2  valid:   5  signed:   0  trust: 5-, 0q, 0n, 0m, 0f, 0u
:: Synchronizing package databases...
downloading mingw32.db...
downloading mingw32.db.sig...
downloading mingw64.db...
downloading mingw64.db.sig...
downloading msys.db...
downloading msys.db.sig...
resolving dependencies...
looking for conflicting packages...

Packages (3) libzstd-1.5.0-1  zstd-1.5.0-1  pacman-6.0.1-3

Total Download Size:    6.11 MiB
Total Installed Size:  36.79 MiB
Net Upgrade Size:      -9.81 MiB

:: Proceed with installation? [Y/n]
:: Retrieving packages...
downloading libzstd-1.5.0-1-x86_64.pkg.tar.zst...
downloading zstd-1.5.0-1-x86_64.pkg.tar.zst...
downloading pacman-6.0.1-3-x86_64.pkg.tar.zst...
checking keyring...
checking package integrity...
loading package files...
error: could not open file /var/cache/pacman/pkg/libzstd-1.5.0-1-x86_64.pkg.tar.zst: Child process exited with status 127
error: could not open file /var/cache/pacman/pkg/zstd-1.5.0-1-x86_64.pkg.tar.zst: Child process exited with status 127
error: could not open file /var/cache/pacman/pkg/pacman-6.0.1-3-x86_64.pkg.tar.zst: Child process exited with status 127
error: failed to commit transaction (cannot open package file)
Errors occurred, no packages were upgraded.
checking dependencies...

Packages (2) rebase-4.4.4-1  dash-0.5.10.2-1

Total Removed Size:  1.12 MiB

:: Do you want to remove these packages? [Y/n]
:: Processing package changes...
removing rebase...
removing dash...
:: Synchronizing package databases...
 mingw32 is up to date
 mingw64 is up to date
 msys is up to date
:: Starting core system upgrade...
warning: resolving dependencies...
terminate other MSYS2 programs before proceeding
looking for conflicting packages...

Packages (8) bash-5.1.008-1  filesystem-2021.06-2  libzstd-1.5.0-1  mintty-1~3.5.1-1  msys2-runtime-3.2.0-15  pacman-6.0.1-3  pacman-mirrors-20210902-1  zstd-1.5.0-1

Total Download Size:    6.21 MiB
Total Installed Size:  61.21 MiB
Net Upgrade Size:      -8.51 MiB

:: Proceed with installation? [Y/n]
:: Retrieving packages...
downloading bash-5.1.008-1-x86_64.pkg.tar.zst...
downloading filesystem-2021.06-2-x86_64.pkg.tar.zst...
downloading mintty-1~3.5.1-1-x86_64.pkg.tar.zst...
downloading msys2-runtime-3.2.0-15-x86_64.pkg.tar.zst...
downloading pacman-mirrors-20210902-1-any.pkg.tar.zst...
checking keyring...
checking package integrity...
loading package files...
error: could not open file /var/cache/pacman/pkg/bash-5.1.008-1-x86_64.pkg.tar.zst: Child process exited with status 127
error: could not open file /var/cache/pacman/pkg/filesystem-2021.06-2-x86_64.pkg.tar.zst: Child process exited with status 127
error: could not open file /var/cache/pacman/pkg/mintty-1~3.5.1-1-x86_64.pkg.tar.zst: Child process exited with status 127
error: could not open file /var/cache/pacman/pkg/msys2-runtime-3.2.0-15-x86_64.pkg.tar.zst: Child process exited with status 127
error: could not open file /var/cache/pacman/pkg/pacman-mirrors-20210902-1-any.pkg.tar.zst: Child process exited with status 127
error: could not open file /var/cache/pacman/pkg/libzstd-1.5.0-1-x86_64.pkg.tar.zst: Child process exited with status 127
error: could not open file /var/cache/pacman/pkg/zstd-1.5.0-1-x86_64.pkg.tar.zst: Child process exited with status 127
error: could not open file /var/cache/pacman/pkg/pacman-6.0.1-3-x86_64.pkg.tar.zst: Child process exited with status 127
error: failed to commit transaction (cannot open package file)
Errors occurred, no packages were upgraded.
-- Acquiring MSYS2... OK
-- Acquiring MSYS Packages...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: C:/opt/ros/melodic/x64/tools/vcpkg/downloads/tools/msys2/msys64/usr/bin/bash.exe --noprofile --norc -c "pacman -S --noconfirm --needed pkg-config"
    Working Directory: C:/opt/ros/melodic/x64/tools/vcpkg/downloads/tools/msys2
    Error code: 1
    See logs for more information:
      C:\opt\ros\melodic\x64\tools\vcpkg\buildtrees\bzip2\msys-pacman-x64-windows-out.log
      C:\opt\ros\melodic\x64\tools\vcpkg\buildtrees\bzip2\msys-pacman-x64-windows-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_acquire_msys.cmake:153 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:281 (vcpkg_acquire_msys)
  ports/bzip2/portfile.cmake:51 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:79 (include)


Error: Building package bzip2:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: bzip2:x64-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.

D:\Proyectos\ROS\catkin_ws>

**Comment by sfhacker** [comment]
@javibo590 Where can I download 'Zlib2 library'?
Are you mixing toolchains? If so, you are looking for trouble!
Try to stick to only one toolchain and see if that works fine.

**Comment by PhoebeHui** [comment]
@javibo590, could you execute 'git pull' & './bootstrap-vcpkg.bat' and see if this issue still repro?

**Comment by javibo590** [comment]
Hello again.
I have carried out the actions that you have commented but unfortunately the problem continues to occur.
The problem is in the download of - Acquiring MSYS Packages ...
Any other idea? 

D:\Descargas\vcpkg>git pull
Already up to date.

D:\Descargas\vcpkg>bootstrap-vcpkg.bat
Downloading https://github.com/microsoft/vcpkg-tool/releases/download/2021-11-15/vcpkg.exe -> D:\Descargas\vcpkg\vcpkg.exe... done.
Validating signature... done.

Telemetry
---------
vcpkg collects usage data in order to help us improve your experience.
The data collected by Microsoft is anonymous.
You can opt-out of telemetry by re-running the bootstrap-vcpkg script with -disableMetrics,
passing --disable-metrics to vcpkg on the command line,
or by setting the VCPKG_DISABLE_METRICS environment variable.

Read more about vcpkg telemetry at docs/about/privacy.md

D:\Descargas\vcpkg>vcpkg install bzip2:x64-windows
Computing installation plan...
The following packages will be built and installed:
    bzip2[core]:x64-windows -> 1.0.6-6
Detecting compiler hash for triplet x64-windows...
Restored 0 packages from C:\Users\T800\AppData\Local\vcpkg\archives in 881 us. Use --debug to see more details.
Starting package 1/1: bzip2:x64-windows
Building package bzip2[core]:x64-windows...
-- Using cached C:/opt/ros/melodic/x64/tools/vcpkg/downloads/bzip2-1.0.6.tar.gz
-- Cleaning sources at C:/opt/ros/melodic/x64/tools/vcpkg/buildtrees/bzip2/src/1.0.6-8838f21f8e.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/opt/ros/melodic/x64/tools/vcpkg/downloads/bzip2-1.0.6.tar.gz
-- Applying patch fix-import-export-macros.patch
-- Applying patch fix-windows-include.patch
-- Using source at C:/opt/ros/melodic/x64/tools/vcpkg/buildtrees/bzip2/src/1.0.6-8838f21f8e.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Fixing pkgconfig
-- Acquiring MSYS Packages...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: C:/opt/ros/melodic/x64/tools/vcpkg/downloads/tools/msys2/msys64/usr/bin/bash.exe --noprofile --norc -c "pacman -S --noconfirm --needed pkg-config"
    Working Directory: C:/opt/ros/melodic/x64/tools/vcpkg/downloads/tools/msys2
    Error code: 1
    See logs for more information:
      C:\opt\ros\melodic\x64\tools\vcpkg\buildtrees\bzip2\msys-pacman-x64-windows-out.log
      C:\opt\ros\melodic\x64\tools\vcpkg\buildtrees\bzip2\msys-pacman-x64-windows-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_acquire_msys.cmake:153 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:281 (vcpkg_acquire_msys)
  ports/bzip2/portfile.cmake:51 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:79 (include)


Error: Building package bzip2:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  package: bzip2[core]:x64-windows -> 1.0.6-6
  vcpkg version: Failed to get HEAD: fatal: not a git repository: 'C:\opt\ros\melodic\x64\tools\vcpkg\.git'

  vcpkg-tool version: 2021-11-15-ec76affcc987efbf172b7da0b05df711b48fa535

Additionally, attach any relevant sections from the log files above.

D:\Descargas\vcpkg>

**Comment by dg0yt** [comment]
> `package: bzip2[core]:x64-windows -> 1.0.6-6`

The current version in vcpkg is 1.0.8#2.

> `vcpkg version: Failed to get HEAD: fatal: not a git repository: 'C:\opt\ros\melodic\x64\tools\vcpkg.git'`

Which vcpkg revision are you trying to build?

> ~~~
> D:\Descargas\vcpkg>vcpkg install bzip2:x64-windows
> ...
> Command failed: C:/opt/ros/melodic/x64/tools/vcpkg/downloads/tools/msys2/msys64/usr/bin/bash.exe --noprofile --norc -c "pacman -S --noconfirm --needed pkg-config"

I can't see where vcpkg would execute `pacman` today.

**Comment by javibo590** [comment]
Hello again.
I have already solved¡¡¡
You just have to change a value in the configuration file \ msys2 \ msys64 \ etc \ pacman.conf

SigLevel = Never
#SigLevel = Required DatabaseOptional

as they comment here:
https://bbs.archlinux.org/viewtopic.php?id=142798 

-- Cleaning sources at C:/opt/ros/melodic/x64/tools/vcpkg/buildtrees/bzip2/src/1.0.6-8838f21f8e.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/opt/ros/melodic/x64/tools/vcpkg/downloads/bzip2-1.0.6.tar.gz
-- Applying patch fix-import-export-macros.patch
-- Applying patch fix-windows-include.patch
-- Using source at C:/opt/ros/melodic/x64/tools/vcpkg/buildtrees/bzip2/src/1.0.6-8838f21f8e.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Fixing pkgconfig
-- Acquiring MSYS Packages...
-- Acquiring MSYS Packages... OK
-- Fixing pkgconfig - release
-- Checking file: C:/opt/ros/melodic/x64/tools/vcpkg/packages/bzip2_x64-windows/lib/pkgconfig/bzip2.pc
-- Fixing pkgconfig - debug
-- Checking file: C:/opt/ros/melodic/x64/tools/vcpkg/packages/bzip2_x64-windows/debug/lib/pkgconfig/bzip2.pc
-- Fixing pkgconfig --- finished
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\T800\AppData\Local\vcpkg\archives\63\634c5fa966c910424a62aa7ef78abc6afa545ad6.zip
Building package bzip2[core]:x64-windows... done
Installing package bzip2[core]:x64-windows...
Installing package bzip2[core]:x64-windows... done
Elapsed time for package bzip2:x64-windows: 40.01 s

Total elapsed time: 52.52 s

The package bzip2 is compatible with built-in CMake targets:

    find_package(BZip2 REQUIRED)
    target_link_libraries(main PRIVATE BZip2::BZip2)


Thank you all very much for your time and effort!!
