### ISSUE TITLE
[New Port Request] libvips

### ISSUE THREAD

**Issue by Kuranes** [microsoft/vcpkg#21070]
Library name: libvips

Library description:
libvips is a demand-driven, horizontally threaded image processing library. Compared to similar libraries, libvips runs quickly and uses little memory.

Source repository URL:
https://github.com/libvips/libvips

Project homepage (if different from the source repository):
https://www.libvips.org/
Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
