### ISSUE TITLE
bzip2[core]:x64-windows - error en la instalacion

### ISSUE THREAD

**Issue by javibo590** [microsoft/vcpkg#21074]
Hola, estoy intentando instalar  rtabmap:x64-windows con VCPKG pero por mas que lo intento siempre obtengo el mismo error
Por favor, a ver si me pueden ayudar. Muchas gracias¡

D:\Proyectos\ROS\catkin_ws>vcpkg install rtabmap:x64-windows
Computing installation plan...
The following packages will be built and installed:
  * boost-bimap[core]:x64-windows
  * boost-circular-buffer[core]:x64-windows
  * boost-dynamic-bitset[core]:x64-windows
  * boost-format[core]:x64-windows
  * boost-graph[core]:x64-windows
  * boost-interprocess[core]:x64-windows
  * boost-iostreams[core]:x64-windows
  * boost-locale[core]:x64-windows
  * boost-multi-array[core]:x64-windows
  * boost-multi-index[core]:x64-windows
  * boost-multiprecision[core]:x64-windows
  * boost-parameter[core]:x64-windows
  * boost-phoenix[core]:x64-windows
  * boost-property-map[core]:x64-windows
  * boost-property-tree[core]:x64-windows
  * boost-proto[core]:x64-windows
  * boost-ptr-container[core]:x64-windows
  * boost-random[core]:x64-windows
  * boost-serialization[core]:x64-windows
  * boost-signals2[core]:x64-windows
  * boost-spirit[core]:x64-windows
  * boost-test[core]:x64-windows
  * boost-tti[core]:x64-windows
  * boost-uuid[core]:x64-windows
  * boost-variant[core]:x64-windows
  * boost-xpressive[core]:x64-windows
  * bzip2[core]:x64-windows
  * curl[core,non-http,ssl,sspi,winssl]:x64-windows
  * double-conversion[core]:x64-windows
  * eigen3[core]:x64-windows
  * expat[core]:x64-windows
  * flann[core]:x64-windows
  * freetype[bzip2,core,png]:x64-windows
  * glew[core]:x64-windows
  * hdf5[core,szip,zlib]:x64-windows
  * jsoncpp[core]:x64-windows
  * libharu[core,notiffsymbols]:x64-windows
  * libiconv[core]:x64-windows
  * libjpeg-turbo[core]:x64-windows
  * liblzma[core]:x64-windows
  * libogg[core]:x64-windows
  * libpng[core]:x64-windows
  * libtheora[core]:x64-windows
  * libwebp[core,nearlossless,simd,unicode]:x64-windows
  * libxml2[core]:x64-windows
  * lz4[core]:x64-windows
  * netcdf-c[core]:x64-windows
  * opencv[core,dnn,jpeg,opengl,png,tiff,webp]:x64-windows
  * opencv4[core,dnn,jpeg,opengl,png,tiff,webp]:x64-windows
  * opengl[core]:x64-windows
  * pcl[core]:x64-windows
  * pegtl-2[core]:x64-windows
  * proj4[core,database]:x64-windows
  * protobuf[core]:x64-windows
  * pugixml[core]:x64-windows
  * qhull[core]:x64-windows
    rtabmap[core]:x64-windows
  * sqlite3[core,tool]:x64-windows
  * szip[core]:x64-windows
  * tiff[core]:x64-windows
  * utfcpp[core]:x64-windows
  * vtk[core]:x64-windows
  * xxhash[core]:x64-windows
  * zlib[core]:x64-windows
  * zstd[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Starting package 1/65: bzip2:x64-windows
Building package bzip2[core]:x64-windows...
Could not locate cached archive: C:\Users\T800\AppData\Local\vcpkg\archives\3c\3c0652163ae0ac78f85bf1acf87509bff06c8dcf.zip
-- Using cached C:/opt/ros/melodic/x64/tools/vcpkg/downloads/bzip2-1.0.6.tar.gz
-- Cleaning sources at C:/opt/ros/melodic/x64/tools/vcpkg/buildtrees/bzip2/src/1.0.6-8838f21f8e.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/opt/ros/melodic/x64/tools/vcpkg/downloads/bzip2-1.0.6.tar.gz
-- Applying patch fix-import-export-macros.patch
-- Applying patch fix-windows-include.patch
-- Using source at C:/opt/ros/melodic/x64/tools/vcpkg/buildtrees/bzip2/src/1.0.6-8838f21f8e.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Fixing pkgconfig
-- Acquiring MSYS Packages...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: C:/opt/ros/melodic/x64/tools/vcpkg/downloads/tools/msys2/msys64/usr/bin/bash.exe --noprofile --norc -c "pacman -S --noconfirm --needed pkg-config"
    Working Directory: C:/opt/ros/melodic/x64/tools/vcpkg/downloads/tools/msys2
    Error code: 1
    See logs for more information:
      C:\opt\ros\melodic\x64\tools\vcpkg\buildtrees\bzip2\msys-pacman-x64-windows-out.log
      C:\opt\ros\melodic\x64\tools\vcpkg\buildtrees\bzip2\msys-pacman-x64-windows-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_acquire_msys.cmake:153 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:281 (vcpkg_acquire_msys)
  ports/bzip2/portfile.cmake:51 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:79 (include)

Error: Building package bzip2:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: bzip2:x64-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.

D:\Proyectos\ROS\catkin_ws>

-Ficheros de los logs:

-msys-pacman-x64-windows-err.log

error: pkg-config: signature from "David Macek <david.macek.0@gmail.com>" is unknown trust
error: failed to commit transaction (invalid or corrupted package (PGP signature))

-msys-pacman-x64-windows-out.log

resolving dependencies...
looking for conflicting packages...

Packages (1) pkg-config-0.29.2-4

Total Download Size:   0.20 MiB
Total Installed Size:  0.55 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
downloading pkg-config-0.29.2-4-x86_64.pkg.tar.zst...
checking keyring...
checking package integrity...
:: File /var/cache/pacman/pkg/pkg-config-0.29.2-4-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] 
Errors occurred, no packages were upgraded.

**Comment by PhoebeHui** [comment]
Closing in favor of https://github.com/microsoft/vcpkg/issues/21075
