### ISSUE TITLE
[abseil] build failure

### ISSUE THREAD

**Issue by giles45** [microsoft/vcpkg#21077]
**Host Environment**
- OS: Windows Server 2019
- Compiler: MSVC 2019

**To Reproduce**
`./vcpkg install abseil:x86-windows`

**Failure logs** 
Error: abseil[core] is only supported on '(x64 | arm64) & (linux | osx | windows)'

**Additional context**
This is a bug because Abseil is supported on 32-bit Windows. (See here https://abseil.io/docs/cpp/platforms/platforms). Moreover, we have been using Abseil via vcpkg targeting 32-bit Windows for several years now. We have a Jenkins job that runs monthly to upgrade our vcpkg packages - and it only failed today after I needed to do a full git clean. So even though it looks like the change went in 12 months ago (75e24fa12478581919b7e65cddaffb87ead2a5a7) - we've only just now been affected by it.

**Comment by NancyLi1013** [comment]
Hi @giles45

Thanks for posting this issue.

Sorry for my confusion. The message is intended, since we add `supports `filed in vcpkg.json.

But it should support x86-windows. I will fix this soon.

**Comment by jeffkohn-swi** [comment]
Please merge linked PR, I'm dead in the water until this is fixed since I need to use some libraries that depend on abseil.

**Comment by Jedi18** [comment]
Hi! I still get this error if I install using `vcpkg install --x-manifest-root cpp --feature-flags=versions --clean-after-build` in the apache arrow directory (it contains vcpkg.json file containing "abseil" in the dependencies).

I was following the apache arrow installation steps. I tried installing abseil through `vcpkg install abseil:x86-windows` which worked, but when I run the above command it still shows this error

`Error: abseil:x86-windows@20210324.2 is only supported on '(x64 | arm64) & (linux | osx | windows)'`

**Comment by dg0yt** [comment]
> Error: abseil:x86-windows@20210324.2 is only supported on '(x64 | arm64) & (linux | osx | windows)'

Did you update you manifest and/or vcpkg in order to find the updated version? `vcpkg install` doesn't do a `git pull` on the vcpkg repo.

**Comment by Jedi18** [comment]
Thanks! I updated the manifest and it worked.

**Comment by Aidan979** [comment]
> 
Adding  `{ "name": "abseil", "version": "20211102.1" }` to the overrides section seems to have worked.
