### ISSUE TITLE
[docopt] docopt targets are not called doctop::docopt for all platforms <2018-11-01#1>

### ISSUE THREAD

**Issue by aminya** [microsoft/vcpkg#21071]
Library name: docopt

New version number: 2018-11-01#1

Other information that may be useful (release notes, etc...)

docopt uses target name `docopt` under Windows, and uses `docopt_s` under Linux. This make it hard to use as we have to do something like this:
```cmake
find_package(docopt CONFIG REQUIRED)
if(WIN32)
  target_link_libraries(main PRIVATE docopt)
else()
  target_link_libraries(main PRIVATE docopt_s)
endif()
```
This is not also consistent with most of the other libraries that follow a `::` naming convention

**Comment by dg0yt** [comment]
Is `docopt` also used for static Windows triplets, and `docopt_s` also for dynamic Linux triplets`?  It sounds like suffix for static linkage.

**Comment by aminya** [comment]
> Is `docopt` also used for static Windows triplets, and `docopt_s` also for dynamic Linux triplets`?  It sounds like suffix for static linkage.

I don't think so. I just used what the CLI recommend as the cmake target. Anyways, these two should follow similar convention like other packages.

**Comment by NancyLi1013** [comment]
Hi @aminya 

Thanks for posting this issue.
`docopt` is for dynamic build, `docopt_s `is for static build, which is not related with platforms.

https://github.com/docopt/docopt.cpp/blob/6f5de76970be94a6f1e4556d1716593100e285d2/CMakeLists.txt#L37-L58

For the targets name, this is upstream behavior. If you have any doubts or requests, please report an issue to upstream.

**Comment by aminya** [comment]
Conan somehow manages to use doctop::doctop for all platforms. That's what I also expected for vcpkg.
https://conan.io/center/docopt.cpp?tab=recipe

**Comment by NancyLi1013** [comment]
Considering this is an upstream behavior. We prefer to expect the behavior designed by upstream. So please report this to upstream.
