### ISSUE TITLE
Broken usage of aws-cpp-sdk v2

### ISSUE THREAD

**Issue by xanather** [microsoft/vcpkg#21081]
Continuation of https://github.com/microsoft/vcpkg/issues/20252

On windows try:
.\vcpkg.exe install aws-sdk-cpp[cloudformation,ssm,s3,ec2]:x64-windows

The result:
```
Error: aws-checksums[core] is only supported on '!arm & !windows'
```

https://github.com/microsoft/vcpkg/blob/master/ports/aws-checksums/vcpkg.json#L6

Why is windows not supported?

**Comment by xanather** [comment]
I just tried it by allowing aws-checksums on windows (manually edited the vcpkg.json file) and seems to have built fine.

**Comment by xanather** [comment]
https://github.com/microsoft/vcpkg/pull/21082 should fix this issue.

**Comment by dg0yt** [comment]
Looks like a bad conversion from `!(arm & windows)` in #20033.
