### ISSUE TITLE
[New Port Request] DPP

### ISSUE THREAD

**Issue by InfRandomness** [microsoft/vcpkg#21084]
Library name: DPP

Library description: Extremely lightweight C++ Discord library

Source repository URL: https://github.com/brainboxdotcc/DPP

Project homepage (if different from the source repository): https://dpp.dev/

**Comment by InfRandomness** [comment]
I am stuck up to that part where I am having this issue : 

```
CMake Error in CMakeLists.txt:
  Found relative path while evaluating include directories of "dpp":

    "OPUS_INCLUDE_DIRS-NOTFOUND"



CMake Error in CMakeLists.txt:
  Found relative path while evaluating include directories of "test":

    "OPUS_INCLUDE_DIRS-NOTFOUND"
```
Can anyone enlighten me on this one?

**Comment by dg0yt** [comment]
Ask upstream. The `CMakeLists.txt` does not look very clean, building for windows "with precompiled packaged dependencies" including opus and sodium. Yes, precompiled... I wouldn't want to be the maintainer of such a port ;-)

**Comment by InfRandomness** [comment]
So, actually, what was happening that we either can not use neither opus or sodium, but if we use one, we have to use the other, and since I want voice support, I have to include both..

And.. uh.. I just want to be able to use a discord library via vcpkg but didn't find anything
