### ISSUE TITLE
[OpenVDB] Update to V9.0 (from 7.x)

### ISSUE THREAD

**Issue by cgolchert** [microsoft/vcpkg#21095]
****

**Is your feature request related to a problem? Please describe.**
The openVDB port is now two full versions behind the current release.   NanoVDB has also been officially released as part of V9.0 to allow for GPU support.

**Proposed solution**
Update the vcpkg version would...well...make the library up-to-date.

**Describe alternatives you've considered**
Waiting so far hasn't gotten it updated so I am putting this request in.

**Additional context**
V9.0:
-------------------------------------------
NanoVDB, which offers GPU support
Improved compilation times
Support for OpenEXR version 3

**Comment by cgolchert** [comment]
Can anyone that understands how version number work explain why this shouldn't have been closed?

Updating it to 8.2 doesn't cover the request for a 9.0 update.

**Comment by JonLiu1993** [comment]
@cgolchert ,The latest version of openvdb currently released is the rolled back version 8.2.0, but in fact its latest version is the last released version 9.0. We are going to submit a new pr to upgrade the version to 9.0.

**Comment by cgolchert** [comment]
I'm not following what you mean...  It IS v9.0 with the incorrect versioning number in vcpkg?

The fact that a request for v9 being closed BECAUSE of 8.2.0 was how the closure was worded.

**Comment by JonLiu1993** [comment]
> 

Sorry to make you confused, I mean we will submit a new pr to upgrade openvdb to version 9.0 soon

**Comment by BillyONeal** [comment]
> Can anyone that understands how version numbers work explain why this shouldn't have been closed?

It got closed because in the PR https://github.com/microsoft/vcpkg/pull/22184 the author said "fix #21095" which caused GitHub to automatically close it when that PR was merged.

**Comment by cgolchert** [comment]
Cool.  I meant "explain why it got closed."  That is what happens when you are tired and edit only have the sentence. :)

**Comment by cgolchert** [comment]
Did interest in this port die?
