### ISSUE TITLE
[bullet3] build failure Mac M1 / arm64

### ISSUE THREAD

**Issue by jmacey** [microsoft/vcpkg#21091]
**Host Environment**
Mac M1 / arm64
Apple clang version 13.0.0 (clang-1300.0.29.3)
Target: arm64-apple-darwin21.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**To Reproduce**
`./vcpkg install bullet3`

**Failure logs** 
  package: bullet3[core]:arm64-osx -> 3.17#2
  vcpkg version: 2021-10-25-b4bff9afacafb0a234a8f20fd6451b2362c0f9a0
  vcpkg-tool version: 5bdb9d601 2021-10-29 (28 hours ago)

Starting package 1/1: bullet3:arm64-osx
Building package bullet3[core]:arm64-osx...
-- Using community triplet arm64-osx. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: /Users/jmacey/vcpkg/triplets/community/arm64-osx.cmake
CMake Error at scripts/cmake/vcpkg_fail_port_install.cmake:96 (message):
  Architecture 'arm64' not supported by bullet3!

If I remove the following 

#vcpkg_fail_port_install(ON_ARCH "arm" "arm64" ON_TARGET "UWP")

from ports/bullet3/portfile.cmake

It works so I guess the check on arm64 and UWP is causing the issue. (I guess UWP is Universal Windows Platform?).

**Comment by JackBoosY** [comment]
```
Architecture 'arm64' not supported by bullet3!
```
https://github.com/microsoft/vcpkg/blob/5bdb9d60123df20c247a1654e6a1def51d6c5140/ports/bullet3/portfile.cmake#L1

Bullet3 doesn't support arm and uwp currently.

**Comment by jmacey** [comment]
It will build fine under arm64 under Mac M1 this check fails under mac which it should not.  I guess either the vcpkg_fail_port_install function is reporting the wrong target or the function is using or instead of and for the checks.

**Comment by JackBoosY** [comment]
@jmacey On arm64-windows build:
```
[1/182] "C:\PROGRA~2\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\Hostx64\arm64\cl.exe"   /TP -DNO_OPENGL3 -DUSE_GRAPHICAL_BENCHMARK -D_CRT_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -D_SCL_SECURE_NO_WARNINGS -D_WIN64 -IF:\vcpkg\buildtrees\bullet3\src\3.17-e90f5ef08b.clean\src /GR- /Gy /GF  /nologo /DWIN32  /W3 /utf-8  /EHsc /MP  /fp:fast /wd4244 /wd4267 /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -D_DEBUG /showIncludes /Fosrc\BulletInverseDynamics\CMakeFiles\BulletInverseDynamics.dir\IDMath.cpp.obj /Fdsrc\BulletInverseDynamics\CMakeFiles\BulletInverseDynamics.dir\BulletInverseDynamics.pdb /FS -c F:\vcpkg\buildtrees\bullet3\src\3.17-e90f5ef08b.clean\src\BulletInverseDynamics\IDMath.cpp
FAILED: src/BulletInverseDynamics/CMakeFiles/BulletInverseDynamics.dir/IDMath.cpp.obj 
"C:\PROGRA~2\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\Hostx64\arm64\cl.exe"   /TP -DNO_OPENGL3 -DUSE_GRAPHICAL_BENCHMARK -D_CRT_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -D_SCL_SECURE_NO_WARNINGS -D_WIN64 -IF:\vcpkg\buildtrees\bullet3\src\3.17-e90f5ef08b.clean\src /GR- /Gy /GF  /nologo /DWIN32  /W3 /utf-8  /EHsc /MP  /fp:fast /wd4244 /wd4267 /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -D_DEBUG /showIncludes /Fosrc\BulletInverseDynamics\CMakeFiles\BulletInverseDynamics.dir\IDMath.cpp.obj /Fdsrc\BulletInverseDynamics\CMakeFiles\BulletInverseDynamics.dir\BulletInverseDynamics.pdb /FS -c F:\vcpkg\buildtrees\bullet3\src\3.17-e90f5ef08b.clean\src\BulletInverseDynamics\IDMath.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\emmintrin.h(24): fatal error C1189: #error:  This header is specific to X86 and X64 targe
```

**Comment by jmacey** [comment]
Works fine on mac (I guess there is an issue with UWP trying to include the intrinsics, however on mac this doesn't happen).  It all works fine (and I have several demos against it installed via vcpkg, I have also built it from source via the official github repo and all of the Demos work fine). The check is the issue it should check for UWP and fail not arm on mac.

➜  vcpkg git:(master) ✗ ./vcpkg install bullet3
Computing installation plan...
The following packages are already installed:
    bullet3[core]:arm64-osx -> 3.17#2
Package bullet3:arm64-osx is already installed
Res

**Comment by jmacey** [comment]
Obviously the above install is with my edited port file.

**Comment by JackBoosY** [comment]
Yes I confirmed.
