### ISSUE TITLE
Installing OpenSSL not working [Hash Issue]

### ISSUE THREAD

**Issue by xtreameprogram** [Microsoft/vcpkg#2109]
I was trying to install OpenSSL on my device, however, I got an issue as shown below. I don't know where any logs are, but I tried looking. 

    /Downloads/vcpkg/scripts/cmake/vcpkg_find_acquire_program.cmake:167 (file):
    file DOWNLOAD HASH mismatch

    for file: [C:/Users/Ford/Downloads/vcpkg/downloads/strawberry-perl-5.24.1.1-32bit-portable.zip]
      expected hash: [a6e685ea24376f50db5f06c5b46075f1d3be25168fa1f27fa9b02e2ac017826cee62a2b43562f9b6c989337a231ba914416c110075457764de2d11f99d5e0f26]
        actual hash: [f3355d2b16232e34d28713216e7f49fae02c6b8e957548fd0eda19a3894e43c4ad613acc0685c86f450de36338cf9681d8619c47bd11c147a9079f300d83e40f]
             status: [0;"No error"]

    Call Stack (most recent call first):    
    C:/Users/Ford/Downloads/vcpkg/ports/openssl/portfile.cmake:10 (vcpkg_find_acquire_program)
    C:/Users/Ford/Downloads/vcpkg/scripts/ports.cmake:72 (include)

**Comment by alexkaratarakis** [comment]
Seems like the file was partially downloaded. 
Please delete `C:/Users/Ford/Downloads/vcpkg/downloads/strawberry-perl-5.24.1.1-32bit-portable.zip` and try again.

**Comment by xtreameprogram** [comment]
Worker perfectly. Thanks!

**Comment by alexkaratarakis** [comment]
@xtreameprogram 
"Incomplete downloads" is an issue that has occurred a number of times. In response, the downloading functionality in `vcpkg` has been improved in 66ad158be46e09b2db4fe8be90841fc01d271c68...0fb0191f3cb9ba4ea0f0e0675f929e1e599e1461. 
The downloads are now performed in a temp file; if the download is complete successfully, the file is moved to its actual target destination.

This avoids issues with incomplete downloads.
Thanks for reporting. :)

**Comment by corymickelson** [comment]
Also having this issue, but removing and re-trying just results in the same error message.
λ .\vcpkg.exe install openssl
The following packages will be built and installed:
    openssl:x86-windows
Starting package 1/1: openssl:x86-windows
Building package openssl:x86-windows...
-- CURRENT_INSTALLED_DIR=C:/Users/SkySlope/Prototypes/vcpkg/installed/x86-windows
-- DOWNLOADS=C:/Users/SkySlope/Prototypes/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/Users/SkySlope/Prototypes/vcpkg/packages/openssl_x86-windows
-- CURRENT_BUILDTREES_DIR=C:/Users/SkySlope/Prototypes/vcpkg/buildtrees/openssl
-- CURRENT_PORT_DIR=C:/Users/SkySlope/Prototypes/vcpkg/ports/openssl/.
-- Downloading http://strawberryperl.com/download/5.24.1.1/strawberry-perl-5.24.1.1-32bit-portable.zip...
-- Downloading http://strawberryperl.com/download/5.24.1.1/strawberry-perl-5.24.1.1-32bit-portable.zip... OK
-- Testing integrity of downloaded file...
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:56 (message):


  File does not have expected hash:

          File path: [ C:/Users/SkySlope/Prototypes/vcpkg/downloads/strawberry-perl-5.24.1.1-32bit-portable.zip ]
      Expected hash: [ a6e685ea24376f50db5f06c5b46075f1d3be25168fa1f27fa9b02e2ac017826cee62a2b43562f9b6c989337a231ba914416c110075457764de2d11f99d5e0f26 ]
        Actual hash: [ f3355d2b16232e34d28713216e7f49fae02c6b8e957548fd0eda19a3894e43c4ad613acc0685c86f450de36338cf9681d8619c47bd11c147a9079f300d83e40f ]

  The file may be corrupted.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:96 (test_hash)
  scripts/cmake/vcpkg_find_acquire_program.cmake:167 (vcpkg_download_distfile)
  ports/openssl/portfile.cmake:10 (vcpkg_find_acquire_program)
  scripts/ports.cmake:72 (include)


Error: Building package openssl:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openssl:x86-windows
  Vcpkg version: 0.0.97-2017-11-20-4415ff5c16d96928a80fa17d6f7028bc9023ebd8

Additionally, attach any relevant sections from the log files above.
