### ISSUE TITLE
[vcpkg] Running vcpkg where vcpkg-root must be detected by looking for .vcpkg-root fails with find_file_recursively_up(..., .vcpkg-root): Not a directory

### ISSUE THREAD

**Issue by al-cheb** [microsoft/vcpkg#21107]
**Describe the bug**
After the PR https://github.com/microsoft/vcpkg/pull/20838 was merged installation, vcpkg is broken on macOS 10.15/11.

**Environment**
- OS: 11.6(20G165)

**To Reproduce**
https://github.com/actions/virtual-environments/blob/main/images/macos/provision/core/vcpkg.sh

```
VCPKG_INSTALLATION_ROOT=/usr/local/share/vcpkg
git clone --depth=1 https://github.com/Microsoft/vcpkg $VCPKG_INSTALLATION_ROOT
$VCPKG_INSTALLATION_ROOT/bootstrap-vcpkg.sh
$VCPKG_INSTALLATION_ROOT/vcpkg integrate install
```

**Expected behavior**
```
$VCPKG_INSTALLATION_ROOT/bootstrap-vcpkg.sh
$VCPKG_INSTALLATION_ROOT/vcpkg integrate install
```

**Failure logs** 
```
$ $VCPKG_INSTALLATION_ROOT/vcpkg integrate install
find_file_recursively_up(/usr/local/share/vcpkg/vcpkg, .vcpkg-root): Not a directory
```

**Comment by al-cheb** [comment]
cc @BillyONeal

**Comment by miketimofeev** [comment]
@BillyONeal @NancyLi1013 same for Ubuntu 
```
==> azure-arm: Provisioning with shell script: C:\agent\_work\6\s\images\linux/scripts/installers/vcpkg.sh
    azure-arm: VCPKG_INSTALLATION_ROOT=/usr/local/share/vcpkg
==> azure-arm: Cloning into '/usr/local/share/vcpkg'...
    azure-arm: Downloading vcpkg-glibc...
    azure-arm: Telemetry
    azure-arm: ---------
    azure-arm: vcpkg collects usage data in order to help us improve your experience.
    azure-arm: The data collected by Microsoft is anonymous.
    azure-arm: You can opt-out of telemetry by re-running the bootstrap-vcpkg script with -disableMetrics,
    azure-arm: passing --disable-metrics to vcpkg on the command line,
    azure-arm: or by setting the VCPKG_DISABLE_METRICS environment variable.
    azure-arm:
    azure-arm: Read more about vcpkg telemetry at docs/about/privacy.md
    azure-arm: find_file_recursively_up(/usr/local/share/vcpkg/vcpkg, .vcpkg-root): Not a directory
```
https://github.visualstudio.com/virtual-environments/_build/results?buildId=118536&view=logs&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=5431112d-2b61-5a5f-7042-ef698f761043

**Comment by BillyONeal** [comment]
What does `uname` say on your system?

https://github.com/microsoft/vcpkg/blob/5bdb9d60123df20c247a1654e6a1def51d6c5140/scripts/bootstrap.sh#L128

**Comment by BillyONeal** [comment]
Oh I see this isn't that it downloaded the linux binary on macos, it's that `find_file_recursively_up` no longer accepts a regular file as the starting path.

As a workaround for now you can manually set `VCPKG_ROOT`

**Comment by al-cheb** [comment]
> Oh I see this isn't that it downloaded the linux binary on macos, it's that `find_file_recursively_up` no longer accepts a regular file as the starting path.
> 
> As a workaround for now you can manually set `VCPKG_ROOT`

Should it point to the `/usr/local/share/vcpkg`?

**Comment by shilewenuw** [comment]
seems it's broken on Ubuntu:Hirsute as well. Temporary fix: 
```
cd to vcpkg/scripts
rm bootstrap.sh
wget https://raw.githubusercontent.com/microsoft/vcpkg/a241dd2859f92f09f801cda2255a94e7bf8336db/scripts/bootstrap.sh
cd ..
./bootstrap-vcpkg.sh
```

**Comment by soulmachine** [comment]
I'm having the same issue on Ubuntu and Debian,

```bash
find_file_recursively_up(/usr/local/share/vcpkg/vcpkg, .vcpkg-root): Not a directory
```

For now I cd to the `$VCPKG_ROOT` and execute `bootstrap-vcpkg.sh` manually to work around it.

**Comment by BillyONeal** [comment]
> > Oh I see this isn't that it downloaded the linux binary on macos, it's that `find_file_recursively_up` no longer accepts a regular file as the starting path.
> > As a workaround for now you can manually set `VCPKG_ROOT`
> 
> Should it point to the `/usr/local/share/vcpkg`?

If that's where your `ports` are, yes.

> seems it's broken on Ubuntu:Hirsute as well. Temporary fix:
> 
> ```
> cd to vcpkg/scripts
> rm bootstrap.sh
> wget https://raw.githubusercontent.com/microsoft/vcpkg/a241dd2859f92f09f801cda2255a94e7bf8336db/scripts/bootstrap.sh
> cd ..
> ./bootstrap-vcpkg.sh
> ```

That fix is suboptimal because it causes a build (it effectively downgrades the tool). Ideally you would use the manually setting `VCPKG_ROOT` temporary workaround.

**Comment by BillyONeal** [comment]
> For now I cd to the `$VCPKG_ROOT` and execute `bootstrap-vcpkg.sh` manually to work around it.

That should also work (and is why we didn't notice this before shipping the update)

**Comment by PhoebeHui** [comment]
Related to https://github.com/microsoft/vcpkg/issues/20125

**Comment by al-cheb** [comment]
@BillyONeal, Thank you for the fix. The issue with Ubuntu&macOS has been resolved for us.
