### ISSUE TITLE
Dlib - find_package(dlib REQUIRED) doesn't work

### ISSUE THREAD

**Issue by lp55** [Microsoft/vcpkg#2111]
Hi,

    I'm using win 10 x64 (version 1607) with Visual Studio 2017 Community Edition. I'm trying to use the dlib package on my project, but the command find_package(dlib REQUIRED) on my CMakeLists.txt fails to work. I have other find_packages (OpenCV, Boost, sqlite3, Qt5Core, etc) that work fine with my vcpkg packages. I get the following error:

CMake Error at D:/vcpkg/scripts/buildsystems/vcpkg.cmake:159 (_find_package):
  By not providing "Finddlib.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "dlib", but
  CMake did not find one.

  Could not find a package configuration file provided by "dlib" with any of
  the following names:

    dlibConfig.cmake
    dlib-config.cmake

  Add the installation prefix of "dlib" to CMAKE_PREFIX_PATH or set
  "dlib_DIR" to a directory containing one of the above files.  If "dlib"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:24 (find_package)

    I updated the dlib port package on my machine to the lastest version of dlib (https://pastebin.com/37c6z97W), but I also tried the original port and the result was the same. I installed with the command vcpkg install dlib:x64-windows. Everything compiled fine and I got not installation errors (some cmake config warnings on the cuda part, but if I compiled without it CUDA support, no errors appeared but the find_package still did't work).
    Any ideas?

**Comment by jasjuang** [comment]
See PR #2124, this should solve it for you.

**Comment by alexkaratarakis** [comment]
PR has been merged now, so you can try latest master.

**Comment by lp55** [comment]
Thanks! It works just fine now. I made a small change to use features to enable/disable CUDA. Here's the patch:

 ports/dlib/CONTROL        | 4 ++++
 ports/dlib/portfile.cmake | 8 ++++++--
 2 files changed, 10 insertions(+), 2 deletions(-)

diff --git a/ports/dlib/CONTROL b/ports/dlib/CONTROL
index 87d8187..78eb29c 100644
--- a/ports/dlib/CONTROL
+++ b/ports/dlib/CONTROL
@@ -2,3 +2,7 @@ Source: dlib
 Version: 19.7
 Build-Depends: libjpeg-turbo, libpng, sqlite3, fftw3
 Description: Modern C++ toolkit containing machine learning algorithms and tools for creating complex software in C++
+
+Feature: cuda
+Build-Depends: cuda
+Description: CUDA support for dlib
diff --git a/ports/dlib/portfile.cmake b/ports/dlib/portfile.cmake
index 4234e3e..6047a0d 100644
--- a/ports/dlib/portfile.cmake
+++ b/ports/dlib/portfile.cmake
@@ -17,6 +17,11 @@ file(READ "${SOURCE_PATH}/dlib/CMakeLists.txt" DLIB_CMAKE)
 string(REPLACE "PNG_LIBRARY" "PNG_LIBRARIES" DLIB_CMAKE "${DLIB_CMAKE}")
 file(WRITE "${SOURCE_PATH}/dlib/CMakeLists.txt" "${DLIB_CMAKE}")
 
+set(WITH_CUDA OFF)
+if("cuda" IN_LIST FEATURES)
+  set(WITH_CUDA ON)
+endif()
+
 vcpkg_configure_cmake(
     SOURCE_PATH ${SOURCE_PATH}
     PREFER_NINJA 
@@ -27,10 +32,9 @@ vcpkg_configure_cmake(
         -DDLIB_JPEG_SUPPORT=ON
         -DDLIB_USE_BLAS=OFF
         -DDLIB_USE_LAPACK=OFF
-        -DDLIB_USE_CUDA=OFF
+        -DDLIB_USE_CUDA=${WITH_CUDA}
         -DDLIB_GIF_SUPPORT=OFF
         -DDLIB_USE_MKL_FFT=OFF
-        #-DDLIB_USE_CUDA=ON
     OPTIONS_DEBUG
         -DDLIB_ENABLE_ASSERTS=ON
         #-DDLIB_ENABLE_STACK_TRACE=ON

You can add this to the main tree on the same license vcpkg uses (don't really care for such a small patch :) )

**Comment by jasjuang** [comment]
It will be great if you can submit a PR!

**Comment by lp55** [comment]
Just did that! (https://github.com/Microsoft/vcpkg/pull/2173)
