### ISSUE TITLE
 [vcpkg upgrade] vcpkg has crashed (update on not installed packages)

### ISSUE THREAD

**Issue by GitMensch** [microsoft/vcpkg#21117]
**To Reproduce**

```sh
$ git pull
$ ./bootstrap-vcpkg`
$ ./vcpkg upgrade json-c
The following packages are not installed:
    json-c:x86-windows

Error: vcpkg has crashed; no additional details are available.
The source line is D:\a\_work\1\s\src\vcpkg\commands.upgrade.cpp(170)
```

**Comment by PhoebeHui** [comment]
@GitMensch, confirmed, this issue could repro with latest vcpkg source, thanks for reporting this issue!

**Comment by Ou7law007** [comment]
I'm getting this error when trying to install any package

`A suitable version of 7zip was not found (required v21.7.0). Downloading portable 7zip v21.7.0...
Extracting 7zip...
A suitable version of 7zip was not found (required v21.7.0). Downloading portable 7zip v21.7.0...
Extracting 7zip...
Error: vcpkg has crashed; no additional details are available.
The source line is D:\a\_work\1\s\src\vcpkg\archives.cpp(100)
`

**Comment by GitMensch** [comment]
@Ou7law007

That's a different issue from a different source file (commands.upgrade.cpp vs. archives.cpp) in a different case (upgrade of non-existing package vs. vcpgk update and 7zip download/use not working). I suggest to move it to a separate one.

**Comment by Ou7law007** [comment]
> @Ou7law007
> 
> That's a different issue from a different source file (commands.upgrade.cpp vs. archives.cpp) in a different case (upgrade of non-existing package vs. vcpgk update and 7zip download/use not working). I suggest to move it to a separate one.

Thank you for replying.
I completely deleted vcpkg and  re cloned/installed it from scratch and it's now working. Should I still create an issue?

**Comment by HydrogenC** [comment]
This seems to be triggered when git pull is performed, but you didn't execute bootstrap-vcpkg.bat to update the executive file.

**Comment by GitMensch** [comment]
The issue starter was still true when tested two weeks ago - and it includes calling the bootstrap script (via msys calling the bootstrap batch file)

**Comment by dg0yt** [comment]
> it includes calling the bootstrap script (via msys calling the bootstrap batch file)

Do you mean running `./bootstrap-vcpkg` from MSYS2 bash?
a) Make sure to bootstrap with the `.bat` version of the script, even on MSYS2
b) Make sure to have only one MSYS2/MinGW runtime in your `PATH`.

https://github.com/microsoft/vcpkg/blob/master/docs/users/mingw.md#using-mingw-w64-natively-on-windows

**Comment by DethRaid** [comment]
I ran into this issue this morning. I had `git pull`ed to update my local `vcpkg` right before I hit this error

I got rid of the error by running `./bootstrap-vcpkg.bat`

Maybe this will help unblock other people

**Comment by PhoebeHui** [comment]
This bug still appears with latest version of vcpkg-tool.

```
PS F:\vcpkg\vcpkg> ./vcpkg upgrade json-c
warning: Starting with the September 2023 release, the default triplet for vcpkg libraries will change from x86-windows to the detected host triplet (x64-windows). To resolve this message, add --triplet x86-windows to keep the same behavior.
error: The following packages are not installed:
    json-c:x86-windows
internal error: D:\a\_work\1\s\src\vcpkg\commands.upgrade.cpp(172): vcpkg has crashed; no additional details are available.
Please open an issue at https://github.com/microsoft/vcpkg/issues/new?template=other-type-of-bug-report.md&labels=category:vcpkg-bug with detailed steps to reproduce the problem.
```

**Comment by CookiePLMonster** [comment]
A PR fixing this seems to be open now so commenting to keep this issue open in case this PR needs some questions answered.
