### ISSUE TITLE
[zipper] build failure

### ISSUE THREAD

**Issue by calvinho-ms** [microsoft/vcpkg#21138]
**Host Environment**
- OS: Ubuntu 20.04
- Compiler: GNU 9.3.0

**To Reproduce**
./vcpkg --triplet x64-linux install zipper

**Failure logs** 
Computing installation plan...
The following packages will be built and installed:
    zipper[core]:x64-linux -> 1.0.3
Detecting compiler hash for triplet x64-linux...
Could not locate cached archive: /home/user/.cache/vcpkg/archives/43/432f4cbbcbe99ec355208bfa340cdbb919467c71.zip
Starting package 1/1: zipper:x64-linux
Building package zipper[core]:x64-linux...
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:146 (message):
    Command failed: /home/user/XXX/vcpkg/downloads/tools/cmake-3.20.2-linux/cmake-3.20.2-linux-x86_64/bin/cmake --build . --config Debug --target install -- -v -j5
    Working Directory: /home/user/XXX/vcpkg/buildtrees/zipper/x64-linux-dbg
    See logs for more information:
      /home/user/XXX/vcpkg/buildtrees/zipper/install-x64-linux-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:104 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:44 (vcpkg_build_cmake)
  ports/zipper/portfile.cmake:40 (vcpkg_install_cmake)
  scripts/ports.cmake:142 (include)

Error: Building package zipper:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zipper:x64-linux
  Vcpkg version: 2021-05-05-unknownhash

Additionally, attach any relevant sections from the log files above.

**install-x64-linux-dbg-err.log**
ninja: error: '/home/calvinho/AEP-Fun-FleetDiagnostics/vcpkg/packages/zlib_x64-linux/lib/zlib.lib', needed by 'Zipper-test', missing and no known rule to make it

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by dg0yt** [comment]
There is no port zipper here.

**Comment by calvinho-ms** [comment]
Sorry the port is not here.
