### ISSUE TITLE
bootstrap compilation failure on RPi OS

### ISSUE THREAD

**Issue by mprather** [microsoft/vcpkg#21142]
**Describe the bug**
As of 5bdb9d60123df20c247a1654e6a1def51d6c5140, the bootstrap compilation process fails on RPi OS.

**Environment**
- OS: Raspberry OS (Linux ci 5.10.17-v7+ #1414 SMP Fri Apr 30 13:18:35 BST 2021 armv7l GNU/Linux)
- Compiler: gcc 8.3.1

**To Reproduce**
1. clone vcpkg
2. run ./bootstrap-vcpkg.sh

Result:
the bootstrap is unable to complete compilation due to failure with messages.cpp

**Expected behavior**
bootstrap should complete successfully. It was working until commit 5bdb9d601 was introduced

**Failure logs** 
[31/122] Building CXX object CMakeFiles/vcpkglib.dir/src/vcpkg/base/messages.cpp.o
FAILED: CMakeFiles/vcpkglib.dir/src/vcpkg/base/messages.cpp.o
/usr/bin/c++  -DFMT_LOCALE -DVCPKG_BASE_VERSION=2021-10-25 -DVCPKG_VERSION=unknownhash -I/home/c/src/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-10-25/include -I_deps/fmt-src/include -O3 -DNDEBUG   -include /home/c/src/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-10-25/include/pch.h -pthread -std=c++17 -MD -MT CMakeFiles/vcpkglib.dir/src/vcpkg/base/messages.cpp.o -MF CMakeFiles/vcpkglib.dir/src/vcpkg/base/messages.cpp.o.d -o CMakeFiles/vcpkglib.dir/src/vcpkg/base/messages.cpp.o -c /home/c/src/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-10-25/src/vcpkg/base/messages.cpp
/usr/include/c++/8/ext/new_allocator.h:136:4: error: call of overloaded ‘StringView(vcpkg::StringLiteral&)’ is ambiguous
  { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }

**Additional context**

**Comment by PhoebeHui** [comment]
@BillyONeal, could you please take a look? I looks a vcpkg bug, however, I don't have that environment to double confirm this issue locally.

**Comment by BillyONeal** [comment]
Yeah now that we are doing binary releases on all the main platforms building from source is going to get progressively more annoying.... which is half the point of wanting to do those binary releases (so that we can use real dependencies).

**Comment by mprather** [comment]
This has been addressed with the tool update on 3/28/22, commit 671db8ae9. Closing.
