### ISSUE TITLE
[openblas:arm64-uwp\openblas:arm-uwp] build failure

### ISSUE THREAD

**Issue by bo-wu** [microsoft/vcpkg#21146]
**Host Environment**
- OS: Windows 10
- Compiler: MSVC 2019

**To Reproduce**
` .\vcpkg\vcpkg.exe install openblas:arm64-uwp`

**Failure logs** 

Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  package: openblas[core]:arm64-uwp -> 0.3.15
  vcpkg version: 2021-10-25-b4bff9afacafb0a234a8f20fd6451b2362c0f9a0
  vcpkg-tool version: 85b31152d 2021-11-02 (6 hours ago)

**Additional context**

CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: ninja -v
    Working Directory: D:/vcpkg/buildtrees/openblas/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\vcpkg\buildtrees\openblas\config-x64-windows-out.log

[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/7464752/config-x64-windows-out.log)

**Comment by bo-wu** [comment]
Hello @Cheney-W ,

One more thing, the failure is not only on community-triplet arm64-uwp, but also same on the built-in triplet arm-uwp.

Thanks advance for solving the problem.

**Comment by JackBoosY** [comment]
Should be fixed by https://github.com/microsoft/vcpkg/pull/20986.
