### ISSUE TITLE
WIL-config.cmake should be named wil-config.cmake

### ISSUE THREAD

**Issue by calvinho-ms** [microsoft/vcpkg#21141]
**Describe the bug**
According to [https://cmake.org/cmake/help/latest/command/find_package.html#search-procedure](https://cmake.org/cmake/help/latest/command/find_package.html#search-procedure), _"CMake searches for a file called \<lowercasePackageName\>-config.cmake or \<PackageName\>Config.cmake."_

Instead of naming the file WIL-config.cmake, I think it should be wil-config.cmake.

**Environment**
- OS: Linux
- Compiler: GNU 9.3.0

**To Reproduce**
cmake -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DVCPKG_TARGET_TRIPLET=x64-linux ..

**Expected behavior**
CMake is able to find wil-config.cmake

**Failure logs** 
CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:861 (_find_package):
  Could not find a package configuration file provided by "WIL" with any of
  the following names:

    WILConfig.cmake
    wil-config.cmake

**Additional context**

**Comment by calvinho-ms** [comment]
Sorry the port is not here.

**Comment by JackBoosY** [comment]
Yes I confirmed.
According to the `https://cmake.org/cmake/help/latest/command/find_package.html#id6`:
```
The command searches for a file called <PackageName>Config.cmake or <lowercasePackageName>-config.cmake for each name specified. 
```
