### ISSUE TITLE
[CGAL] build failure

### ISSUE THREAD

**Issue by cczls1991** [microsoft/vcpkg#21158]
**Describe the bug**

**Environment**
- OS: Windows

**To Reproduce**
1. ./vcpkg install CGAL

  package: boost-config[core]:x86-windows -> 1.77.0#2
  vcpkg version: 2021-11-02-af04ebf6274fd6f7a941bff4662b3955c64f6f42
  vcpkg-tool version: 7375bb408 2021-11-03 (3 hours ago)

**Comment by JonLiu1993** [comment]
@cczls1991 ,Thanks for your issue, could you explain your problem or provide a specific error log?

**Comment by JonLiu1993** [comment]
@cczls1991 ,please reopen this issue if it still be a problem for you.
