### ISSUE TITLE
[New Port Request] libgda

### ISSUE THREAD

**Issue by moshilgc** [microsoft/vcpkg#21150]
Library name:   libgda
Library description:
     GNU Data Access (GDA) is an attempt to provide uniform access to different kinds of data sources (databases, information
servers, mail spools, etc). It is a complete architecture that provides all you need to access your data.
Source repository URL:
     https://github.com/GNOME/libgda/tree/LIBGDA_6.0 
Project homepage (if different from the source repository):
      https://github.com/GNOME/libgda
Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
