### ISSUE TITLE
For the file download should have more reminders

### ISSUE THREAD

**Issue by FishOrBear** [microsoft/vcpkg#2116]
When I download openssl, always download failed, then found that the download speed of the library is too slow.
` strawberry-perl-5.24.1.1-32bit-portable.zip `
After reviewing other issues, I manually downloaded this file and successfully installed it.
If the download prompts the current download file name. I think it will be better.

There are more error tips to help us find the cause of the problem

Or, like npm, provide server downloads to prevent downloads from failing.

C + + compiler build always frustrating.

**Comment by NancyLi1013** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen.
