### ISSUE TITLE
[<colmap>] build failure

### ISSUE THREAD

**Issue by beardbox** [microsoft/vcpkg#21169]
**Host Environment**
- OS: windows 10
- Compiler: visual studio 2019

**To Reproduce**
.\vcpkg install colmap[cuda,tests]:x64-windows

**Failure logs** 
Error: Building package openblas:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  package: openblas[core]:x64-windows -> 0.3.15
  vcpkg version: 2021-11-02-af04ebf6274fd6f7a941bff4662b3955c64f6f42
  vcpkg-tool version: 7375bb408 2021-11-03 (9 hours ago)

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by NancyLi1013** [comment]
Hi @beardbox

Thanks for posting this issue.

Could you please help provide the detailed error info or the error log here?

**Comment by PhoebeHui** [comment]
@beardbox, please reopen this issue and provide us failure logs if it still be a problem for you.
