### ISSUE TITLE
[sentencepiece]build failure

### ISSUE THREAD

**Issue by lewulewu** [microsoft/vcpkg#21185]
Computing installation plan...
The following packages will be built and installed:
    sentencepiece[core]:x64-osx -> 0.1.95#1
Detecting compiler hash for triplet x64-osx...
Restored 0 packages from /Users/***/.cache/vcpkg/archives in 46.46 us. Use --debug to see more details.
Starting package 1/1: sentencepiece:x64-osx
Building package sentencepiece[core]:x64-osx...
-- Using cached google-sentencepiece-v0.1.95.tar.gz.
-- Cleaning sources at /Users/***/vcpkg/buildtrees/sentencepiece/src/v0.1.95-e88ac94423.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /Users/***/vcpkg/downloads/google-sentencepiece-v0.1.95.tar.gz
-- Using source at /Users/***/vcpkg/buildtrees/sentencepiece/src/v0.1.95-e88ac94423.clean
-- Configuring x64-osx-dbg
-- Configuring x64-osx-rel
-- Building x64-osx-dbg
-- Building x64-osx-rel
-- Fixing pkgconfig file: /Users/***/vcpkg/packages/sentencepiece_x64-osx/lib/pkgconfig/sentencepiece.pc
CMake Error at scripts/cmake/vcpkg_find_acquire_program.cmake:543 (message):
  Could not find pkg-config.  Please install it via your package manager:

      brew install pkg-config
Call Stack (most recent call first):
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:198 (vcpkg_find_acquire_program)
  ports/sentencepiece/portfile.cmake:34 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:142 (include)

Error: Building package sentencepiece:x64-osx failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  package: sentencepiece[core]:x64-osx -> 0.1.95#1
  vcpkg version: 2021-11-02-af04ebf6274fd6f7a941bff4662b3955c64f6f42
  vcpkg-tool version: 40a0fb232 2021-11-03 (2 hours ago)

Additionally, attach any relevant sections from the log files above.

**Comment by JonLiu1993** [comment]
@lewulewu ,Thanks for posting this issue,you have to install pkg-config via brew with brew install pkg-config as suggested in the error message ;)

**Comment by JonLiu1993** [comment]
@lewulewu , have you tested the suggestion?

**Comment by JonLiu1993** [comment]
@lewulewu ，Does this problem still exist?

**Comment by JonLiu1993** [comment]
Thanks for posting this issue. Please reopen this issue if it still be a problem for you
