### ISSUE TITLE
7zip - [tool] feature build missing?

### ISSUE THREAD

**Issue by mirostauder** [microsoft/vcpkg#21187]
default 7zip build is [core] and builds only the 7zip.dll

I don't see a way to build the 7zip.exe - no [tool] feature is present

**Comment by JonLiu1993** [comment]
The `7zip` under ports is only provided for binary `.dll` files, and vcpkg itself provides tools through `vcpkg_find_acquire_program(7Z).cmake` https://github.com/microsoft/vcpkg/blob/70992f64912b9ab0e60e915ab7421faa197524b7/scripts/cmake/vcpkg_find_acquire_program(7Z).cmake
