### ISSUE TITLE
VCPKG fails to install on linux/Arm/V7 due Value too large for defined data type.

### ISSUE THREAD

**Issue by vishnucool220** [microsoft/vcpkg#21189]
When i tried build my c++ program inside my docker. VCPKG fails to install. because of  `get_regular_files_recursive(/root/.cache/vcpkg/registries/git-trees/b79091461891cef2671af33c4ef236d517b12d55): Value too large for defined data type
`

**Environment**
- OS: Linux
- Compiler: GCC 10/G++ 10
-CMake: 3.21

**To Reproduce**
Run cmake project on arm/v7.

RUN cmake -G "Unix Makefiles" -DCMAKE_CXX_COMPILER:STRING=/usr/bin/g++-10 -DCMAKE_C_COMPILER:STRING=/usr/bin/gcc-10 -DCMAKE_TOOLCHAIN_FILE=/opt/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo CMakeLists.txt

**Expected behavior**
VCPKG package should install the packages without any issues.

**Failure logs** 
```
[linux/arm/v7 builder  5/10] RUN cmake -G "Unix Makefiles" -DCMAKE_CXX_COMPILER:STRING=/usr/bin/g++-10 -DCMAKE_C_COMPILER:STRING=/usr/bin/gcc-10 -DCMAKE_TOOLCHAIN_FILE=/opt/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo CMakeLists.txt
#32 21.81 get_regular_files_recursive(/root/.cache/vcpkg/registries/git-trees/b79091461891cef2671af33c4ef236d517b12d55): Value too large for defined data type
#32 23.17 -- Running vcpkg install - failed
#32 23.19 CMake Error at /opt/vcpkg/scripts/buildsystems/vcpkg.cmake:831 (message):
#32 23.19   vcpkg install failed.  See logs for more information:
#32 23.19   /source/vcpkg-manifest-install.log
#32 23.19 Call Stack (most recent call first):
#32 23.19   /usr/local/share/cmake-3.21/Modules/CMakeDetermineSystem.cmake:124 (include)
#32 23.19   CMakeLists.txt:3 (project)
#32 23.19 
#32 23.20 
#32 23.20 CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
#32 23.22 -- Configuring incomplete, errors occurred!
#32 ERROR: process "/bin/sh -c cmake -G \"Unix Makefiles\" -DCMAKE_CXX_COMPILER:STRING=/usr/bin/g++-10 -DCMAKE_C_COMPILER:STRING=/usr/bin/gcc-10 -DCMAKE_TOOLCHAIN_FILE=/opt/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE:STRING=$configuration CMakeLists.txt" did not complete successfully: exit code: 1
```

**Additional context**
The same code is working fine on amd64 and arm64 Architectures. If failes only on 32bit arm/v7.

**Comment by heretic13** [comment]
I got a similar error when compiling vcpkg for arm processor from qemu chroot.

It looks like the returned inode value is too big for a 32-bit machine.

https://stackoverflow.com/questions/2438890/cc1plus-error-include-value-too-large-for-defined-data-type-when-compiling-wi

**Comment by TheAifam5** [comment]
I have the same issue while building an application in docker using buildx on macOS (colima). Currently due to this bug I am blocked since the arm32 is a hard requirement (for now).

**Comment by heretic13** [comment]
Quick fix: run compilation on a smaller tmpfs partition. This helped me.

**Comment by Thomas1664** [comment]
@MonicaLiu0311 Fixed by https://github.com/microsoft/vcpkg-tool/pull/834
This PR added `_FILE_OFFSET_BITS=64`.
