### ISSUE TITLE
`vcpkg_cmake_configure` does not change the cwd on windows

### ISSUE THREAD

**Issue by autoantwort** [microsoft/vcpkg#21198]
While working on #21168 the following was detected:
It seems that `vcpkg_cmake_configure` does not change the cwd in contrast to `vcpkg_configure_cmake` on windows. 
The line `file(MAKE_DIRECTORY generated)` generates the following error on windows but not on other platforms:
```
CMake Error at CMakeLists.txt:13 (file):
  file attempted to create a directory:
  C:/Users/LeanderSchulten/git_projects/vcpkg/buildtrees/offscale-libetcd-cpp/src/fdb87cf638-60a9ea69fd.clean/generated
  into a source directory.
```

**Comment by JackBoosY** [comment]
@strega-nil-ms can you please take a look?

I met this error again.

**Comment by sfhacker** [comment]
@JackBoosY Which (online) translator have you been using so far? We would like to try it out! [1]
Cheers.

[1] https://english-for-chinese.blogspot.com/2008/06/and-meet-problem.html

**Comment by JackBoosY** [comment]
According to cmake issue https://gitlab.kitware.com/cmake/cmake/-/issues/18811,
The reason why we got this error is `CMAKE_DISABLE_SOURCE_CHANGES` is enabled.
I will check the maintain history later.

**Comment by JackBoosY** [comment]
Additional. we can use option `DISABLE_PARALLEL_CONFIGURE` to `vcpkg_configure_cmake` / `vcpkg_cmake_configure` to avoid this.

**Comment by JackBoosY** [comment]
This option was introduced by PR https://github.com/microsoft/vcpkg/pull/12846.

**Comment by dg0yt** [comment]
This analysis went in the wrong direction again. The problem is entirely in `vcpkg_cmake_configure` (and `vcpkg_configure_cmake`) which invokes cmake differently (from ninja) with parallel configure. It is more evident with the port version because it uses parallel by default.

**Comment by dg0yt** [comment]
> While working on #21168 the following was detected: It seems that `vcpkg_cmake_configure` does not change the cwd in contrast to `vcpkg_configure_cmake` on windows. The line `file(MAKE_DIRECTORY generated)` generates the following error on windows but not on other platforms:
> 
> ```
> CMake Error at CMakeLists.txt:13 (file):
>   file attempted to create a directory:
>   C:/Users/LeanderSchulten/git_projects/vcpkg/buildtrees/offscale-libetcd-cpp/src/fdb87cf638-60a9ea69fd.clean/generated
>   into a source directory.
> ```

What can be fixed is:
Change the cwd for uniform behaviour between parallel and non-parallel configure.

What can't be fixed is:
Enable (parallel!) safe writes to the source directory during parallel configure.

**Comment by dg0yt** [comment]
For parallel configure to work, offscale-libetcd-cpp must be patched. Cf. https://github.com/microsoft/vcpkg/pull/22124#issuecomment-998507322.

**Comment by strega-nil-ms** [comment]
Yeah, this is not a bug (as @dg0yt points out) - offscale-libetcd-cpp cannot use parallel configure.

**Comment by dg0yt** [comment]
It is a bug because it affects the working directory of `execute_process`, and a patch is pending in #22124.

**Comment by strega-nil-ms** [comment]
mmh, okay, thanks! reopening
