### ISSUE TITLE
[nanodbc] I want build it for win7, need pass a cmake param " -DNANODBC_DISABLE_ASYNC=1"

### ISSUE THREAD

**Issue by daiybh** [microsoft/vcpkg#21190]
****

**Is your feature request related to a problem? Please describe.**

if use lastVersion builded , and can not run it on win7.
there is a  solution [link](https://github.com/nanodbc/nanodbc/issues/89#issuecomment-748075493)

**Proposed solution**
as the [link]() say ,just need pass  -DNANODBC_DISABLE_ASYNC=1 to CMake ,will be fixed it.

so I want to know:

1 when use `vcpkg install nanodbc:x86-windows`   ,how to pass  the ` -DNANODBC_DISABLE_ASYNC=1`

2 if I use manifests "vcpkg.json"   ,how to pass  the ` -DNANODBC_DISABLE_ASYNC=1`
   ```{
    "$schema": "https://raw.githubusercontent.com/microsoft/vcpkg/master/scripts/vcpkg.schema.json",
    "name": "sdktools",
    "version": "0.0.1",
  "dependencies": [
    {
      "name": "nanodbc",
      "default-features": false,
      "features": [ "NANODBC_DISABLE_ASYNC??????" ]
    }
  ]
}
```

**Comment by JackBoosY** [comment]
@daiybh Please download and uzip [this file](https://github.com/microsoft/vcpkg/files/7480117/nanodbc-custom.zip), put it to a custom folder, then use feature overlay-port.
See [document ](https://github.com/microsoft/vcpkg/blob/master/docs/specifications/ports-overlay.md)([chinese doc](https://www.cnblogs.com/vcpkg/p/15019942.html)).

**Comment by daiybh** [comment]
Thanks. so need  custom a new port ,but can not pass it from  vcpkg.json.
