### ISSUE TITLE
[vtk[core]:x64-linux] build failure

### ISSUE THREAD

**Issue by AlexLeungZ** [microsoft/vcpkg#21195]
**Host Environment**
- OS: Ubuntu 20.04.3 LTS on Windows 10 x86_64 (WSL)
- Compiler: g++ (Ubuntu 11.1.0-1ubuntu1~20.04) 11.1.0
- CMake version: cmake version 3.21.2

**To Reproduce**
`git clone https://github.com/microsoft/vcpkg`
`sudo ./vcpkg/bootstrap-vcpkg.sh`
`sudo vcpkg/vcpkg integrate install`
then hit build with vscode's cmake extension

**vcpkg.json**
```
{
    "name": "vtk-test",
    "version": "1.0",
    "description": "--",
    "dependencies": [
        {
            "name": "vtk",
            "features": [ ]
        }
    ]
}
```

**Expected Behavior**
Installs without error

**Failure logs** 
```
[build] -- Building x64-linux-dbg
[build] CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:155 (message):
[build]     Command failed: /home/alex/.local/lib/pypy3.6/site-packages/cmake/data/bin/cmake --build . --config Debug --target install -- -v -j33
[build]     Working Directory: /mnt/d/Git/GitHub/vtk-test/vcpkg/buildtrees/vtk/x64-linux-dbg
[build]     See logs for more information:
[build]       /mnt/d/Git/GitHub/vtk-test/vcpkg/buildtrees/vtk/install-x64-linux-dbg-out.log
[build] 
[build] Call Stack (most recent call first):
[build]   /mnt/d/Git/GitHub/vtk-test/build/vcpkg_installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_build.cmake:102 (vcpkg_execute_build_process)
[build]   /mnt/d/Git/GitHub/vtk-test/build/vcpkg_installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
[build]   ports/vtk/portfile.cmake:171 (vcpkg_cmake_install)
[build]   scripts/ports.cmake:142 (include)
[build] 
[build] 
[build] Error: Building package vtk:x64-linux failed with: BUILD_FAILED
[build] Please ensure you're using the latest portfiles with `git pull` and `./vcpkg update`, then
[build] submit an issue at https://github.com/Microsoft/vcpkg/issues including:
[build]   package: vtk[core]:x64-linux -> 9.0.3-pv5.9.1#3
[build]   vcpkg version: 2021-11-02-af04ebf6274fd6f7a941bff4662b3955c64f6f42
[build]   vcpkg-tool version: 603748b5d 2021-11-04 (33 minutes ago)
[build] 
[build] Additionally, attach any relevant sections from the log files above.
[build] -- Running vcpkg install - failed
[build] CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:831 (message):
[build]   vcpkg install failed.  See logs for more information:
[build]   /mnt/d/Git/GitHub/vtk-test/build/vcpkg-manifest-install.log
[build] Call Stack (most recent call first):
[build]   build/CMakeFiles/3.21.2/CMakeSystem.cmake:6 (include)
[build]   CMakeLists.txt:2 (project)
[build] 
[build] 
[build] -- Configuring incomplete, errors occurred!
[build] See also "/mnt/d/Git/GitHub/vtk-test/build/CMakeFiles/CMakeOutput.log".
[build] See also "/mnt/d/Git/GitHub/vtk-test/build/CMakeFiles/CMakeError.log".
[build] make: *** [Makefile:604: cmake_check_build_system] Error 1
[build] Build finished with exit code 2
```
Full log is attached here:
[LOG.txt](https://github.com/microsoft/vcpkg/files/7477411/LOG.txt)

**Additional context**
/mnt/d/Git/GitHub/vtk-test/build/vcpkg-manifest-install.log
[vcpkg-manifest-install.log](https://github.com/microsoft/vcpkg/files/7477424/vcpkg-manifest-install.log)

/mnt/d/Git/GitHub/vtk-test/vcpkg/buildtrees/vtk/install-x64-linux-dbg-out.log
[install-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/7477435/install-x64-linux-dbg-out.log)

/mnt/d/Git/GitHub/vtk-test/vcpkg/buildtrees/vtk/config-x64-linux-dbg-out.log
[config-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/7477481/config-x64-linux-dbg-out.log)

/mnt/d/Git/GitHub/vtk-test/build/CMakeFiles/CMakeError.log
[CMakeError.log](https://github.com/microsoft/vcpkg/files/7477441/CMakeError.log)

/mnt/d/Git/GitHub/vtk-test/build/CMakeFiles/CMakeOutput.log
[CMakeOutput.log](https://github.com/microsoft/vcpkg/files/7477444/CMakeOutput.log)

./vcpkg list
```
No packages are installed. Did you mean `search`?
```

**Comment by NancyLi1013** [comment]
Hi @AlexLeungZ 

Thanks for posting this issue.

From install-x64-linux-dbg-out.log, we found this:

```
/mnt/d/Git/GitHub/vtk-test/vcpkg/buildtrees/vtk/src/edd2e5233f-f32830fbf2.clean/Common/Core/vtkGenericDataArrayLookupHelper.h: In function ‘bool detail::isnan(T)’:
/mnt/d/Git/GitHub/vtk-test/vcpkg/buildtrees/vtk/src/edd2e5233f-f32830fbf2.clean/Common/Core/vtkGenericDataArrayLookupHelper.h:52:26: error: ‘numeric_limits’ is not a member of ‘std’
   52 |   return has_NaN<T, std::numeric_limits<T>::has_quiet_NaN>::isnan(x);
```

Seems  like a bug in `vtk`, <limits.h> is required.

please see https://discourse.vtk.org/t/compilation-error-include-limits-required-in-several-files/6496.

https://gitlab.kitware.com/vtk/vtk/-/merge_requests/7611

**Comment by AlexLeungZ** [comment]
@NancyLi1013 
where should I add those headers,
as every time I added the `#include <limits>` at those files, such as 
/mnt/d/Git/GitHub/vtk-test/vcpkg/buildtrees/vtk/src/edd2e5233f-f32830fbf2.clean/Common/Core/vtkGenericDataArrayLookupHelper.h
It will just undo all my changes and gives out the same error

**Comment by AlexLeungZ** [comment]
```
/mnt/d/Git/GitHub/vtk-test/vcpkg/buildtrees/vtk/src/edd2e5233f-f32830fbf2.clean/Common/Core/vtkGenericDataArrayLookupHelper.h: In function ‘bool detail::isnan(T)’:
/mnt/d/Git/GitHub/vtk-test/vcpkg/buildtrees/vtk/src/edd2e5233f-f32830fbf2.clean/Common/Core/vtkGenericDataArrayLookupHelper.h:52:26: error: ‘numeric_limits’ is not a member of ‘std’
   52 |   return has_NaN<T, std::numeric_limits<T>::has_quiet_NaN>::isnan(x);
```

I successfully installed vtk with this method:

1. After the first failed build with VCPKG, you should have a file called `Kitware-VTK-xxx.tar.gz` in path `.../vcpkg/downloads`, in my case it is `.../vcpkg/downloads/Kitware-VTK-2959413ff190bc6e3ff40f5b6c1342edd2e5233f.tar.gz`
2. `cd` into that directory
3. Unzip the .tar.gz file, `unpigz xvf Kitware-VTK-xxx.tar.gz` then `tar xvf Kitware-VTK-xxx.tar`
4. Right now, you should have a directory called `VTK-xxx`
5. Edit the following files: `Common/Core/vtkGenericDataArray.h`, `Common/Core/vtkGenericDataArrayLookupHelper.h`, `Common/DataModel/vtkPiecewiseFunction.cxx`, `Filters/HyperTree/vtkHyperTreeGridThreshold.cxx`, `Rendering/Core/vtkColorTransferFunction.cxx`
6. Add these two header to those files` #include <stdexcept>`, `#include <limits>`
7. Save everything
8. zip the directory `VTK-xxx`, `tar cvf VTK-xxx.tar VTK-xxx`, then `pigz VTK-xxx.tar`
9. Rename the file as `Kitware-VTK-xxx.tar.gz`, which should be the same as what it is named in the downloaded path of vcpkg
10. Replace the old `Kitware-VTK-xxx.tar.gz` with your new one
11. Run build again, this time you should have a error something similar to this `expert hash: ...` `actual hash: ....`, and a message like this `Installing port from location: /mnt/d/Git/GitHub/vtk-test/vcpkg/buildtrees/versioning/versions/vtk/1b201a8e060b6c2688ccc2e96cae175f2d8af205`
12. Goto that directory, edit the `portfile.cmake` file, 
13. Change the `SHA512` value with the `actual hash` value
14. Now build the whole thing again, you should be good to go

Thx NancyLi for helping

**Comment by NancyLi1013** [comment]
I will create a PR to patch this to fix this problem later.
