### ISSUE TITLE
MSBuild integration should select static triplets when linking against the static CRT

### ISSUE THREAD

**Issue by ras0219-msft** [Microsoft/vcpkg#212]
See title.

While today you can override this by specifying some poorly documented msbuild variables, we should give the user an "It Just Works" experience out of the box by selecting static libraries when statically linking the CRT and DLLs when dynamically linking the CRT.

**Comment by alexkaratarakis** [comment]
Resolved by 789855546ca26ae30398235d0b3ee2f9eb92c40a.
