### ISSUE TITLE
Error: Building package libconfig:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by ycj1124** [microsoft/vcpkg#21205]
**Host Environment**
- OS: e.g. Windows
- Compiler: revision

**To Reproduce**
`./vcpkg install libconfig:x64-windows`

**Failure logs** 
Error: Building package libconfig:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  package: libconfig[core]:x64-windows -> 1.7.3#1
  vcpkg version: 2021-11-02-af04ebf6274fd6f7a941bff4662b3955c64f6f42
  vcpkg-tool version: 8acb35e27 2021-11-05 (6 hours ago)

Additionally, attach any relevant sections from the log files above.
when I try to install libconfig(x64) by vcpkg,it orrurs the problem.and when I use the "vcpkg install libconfig:x64-windows`" to install ,it occurs the warning like this .Is this the problem of the failure of my install?noticed that the warning said the VS2013 lacking English package,but I am using VS2015 actually.
![error3](https://user-images.githubusercontent.com/55937464/140521893-012ee359-d6bd-4565-a8f3-d53c1aad9520.png)

**Comment by ycj1124** [comment]
![error](https://user-images.githubusercontent.com/55937464/140522085-0081c38a-c5d0-4452-a722-cdda2a01d52f.png)
the whole process is like this

**Comment by autoantwort** [comment]
Please attach the mentioned log files

**Comment by ycj1124** [comment]
> Please attach the mentioned log files
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/7489613/config-x64-windows-out.log)
[stdout-x64-windows.log](https://github.com/microsoft/vcpkg/files/7489614/stdout-x64-windows.log)
[stdout-x64-windows.log](https://github.com/microsoft/vcpkg/files/7489615/stdout-x64-windows.log)
[x64-windows.vcpkg_abi_info.txt](https://github.com/microsoft/vcpkg/files/7489616/x64-windows.vcpkg_abi_info.txt)
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/7489617/config-x64-windows-out.log)

**Comment by autoantwort** [comment]
> config-x64-windows-out.log

Look strange. Seems that it produces a internal compiler error.

**Comment by ycj1124** [comment]
> > config-x64-windows-out.log
> 
> Looks strange. Seems that it produces a internal compiler error.

Sir,is there any possible method to fix the problem?I just want to download the libconfig library and I have been stuck by the problem for days.thank you very much!

**Comment by JackBoosY** [comment]
```
       #include <dlfcn.h>

       void *dlsym(void *restrict handle, const char *restrict symbol);

       #define _GNU_SOURCE
       #include <dlfcn.h>

       void *dlvsym(void *restrict handle, const char *restrict symbol,
                    const char *restrict version);

       Link with -ldl.
```
Missing `-ldl`

```
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe - broken
CMake Error at C:/Program Files/CMake/share/cmake-3.21/Modules/CMakeTestCCompiler.cmake:69 (message):
  The C compiler

    "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe"
```
Does you install both Visual Studio 2015 and Visual Studio 2019?

**Comment by ycj1124** [comment]
> ```
>        #include <dlfcn.h>
> 
>        void *dlsym(void *restrict handle, const char *restrict symbol);
> 
>        #define _GNU_SOURCE
>        #include <dlfcn.h>
> 
>        void *dlvsym(void *restrict handle, const char *restrict symbol,
>                     const char *restrict version);
> 
>        Link with -ldl.
> ```
> 
> Missing `-ldl`
> 
> ```
> -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe
> -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe - broken
> CMake Error at C:/Program Files/CMake/share/cmake-3.21/Modules/CMakeTestCCompiler.cmake:69 (message):
>   The C compiler
> 
>     "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe"
> ```
> 
> Does you install both Visual Studio 2015 and Visual Studio 2019?

at first ，I only installed vs2015 and vs2013 .but the vcpkg seemed to search vs2013 directly and ignore the vs2015.after that,I install vs2017 now and I have successfully install the libconfig library.is there any problem if I install multi version of visual studio? when I use the library,must I use the vs2017 rather than 2015? should I must install vs2019？

**Comment by JackBoosY** [comment]
@ycj1124 vcpkg requires Visual Studio version 2015 or higher, but we prefer to use at lest Visual Studio 2017. So you don't need to install Visual Studio 2019.

**Comment by ycj1124** [comment]
> @ycj1124 vcpkg requires Visual Studio version 2015 or higher, but we prefer to use at lest Visual Studio 2017. So you don't need to install Visual Studio 2019.

alright，thank you sir.
