### ISSUE TITLE
feature request: disable debug builds

### ISSUE THREAD

**Issue by xoviat** [Microsoft/vcpkg#2120]
Sometimes we don't need the debug builds and they can take 40+ minutes to compile. I would appreciate a command-line flag to disable them.

**Comment by ismail** [comment]
This is especially important for CI builds where you might only need -rel but you have to spend time & resources waiting for -debug too.

**Comment by KindDragon** [comment]
You can use `vcpkg export` and then use it for CI

**Comment by alexkaratarakis** [comment]
Latest `vcpkg` version has `VCPKG_BUILD_TYPE`.
See also: https://github.com/Microsoft/vcpkg/issues/143
