### ISSUE TITLE
[New Port Request] Open Shading Language

### ISSUE THREAD

**Issue by romainaugier** [microsoft/vcpkg#21211]
Library name: Open Shading Language

Library description: Open Shading Language (OSL) is a small but rich language for programmable shading in advanced renderers and other applications, ideal for describing materials, lights, displacement, and pattern generation.

Source repository URL: https://github.com/AcademySoftwareFoundation/OpenShadingLanguage

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
