### ISSUE TITLE
[New Port Request] Luau (Lua with types)

### ISSUE THREAD

**Issue by Spejik** [microsoft/vcpkg#21210]
Library name: Luau

Library description: 
An extension to Lua, that adds types, and many more features that are listed on the Luau website.

Source repository URL: 
https://github.com/Roblox/luau

Project homepage (if different from the source repository): 
https://luau-lang.org/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
