### ISSUE TITLE
[<pcl[cuda]:x64-windows-static>] build failure

### ISSUE THREAD

**Issue by weibingrong** [microsoft/vcpkg#21223]
**Host Environment**
- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**
`./vcpkg install xxxx`

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by weibingrong** [comment]
Host Environment

OS: [Win10]
Compiler: VS2019
To Reproduce
Steps to reproduce the behavior:
./vcpkg install pcl[cuda]:x64-windows-static

Failure logs
CMake Error at scripts/cmake/vcpkg_fixup_pkgconfig.cmake:78 (message):

  D:/0temp/vcpkg/downloads/tools/msys2/aa5af7b2aa7e90e8/mingw32/bin/pkg-config.exe
  --exists pcl_cuda_features-1.12 failed with error code: 1

      ENV{PKG_CONFIG_PATH}: "D:/0temp/vcpkg/packages/pcl_x64-windows-static/lib/pkgconfig;D:/0temp/vcpkg/packages/pcl_x64-windows-static/share/pkgconfig;D:/0temp/vcpkg/installed/x64-windows-static/lib/pkgconfig;D:/0temp/vcpkg/installed/x64-windows-static/share/pkgconfig"
      output: Package pcl_cuda_common-1.12 was not found in the pkg-config search path.

  Perhaps you should add the directory containing `pcl_cuda_common-1.12.pc'

  to the PKG_CONFIG_PATH environment variable

  Package 'pcl_cuda_common-1.12', required by 'pcl_cuda_features-1.12', not
  found
Call Stack (most recent call first):
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:201 (z_vcpkg_fixup_pkgconfig_check_files)
  ports/pcl/portfile.cmake:77 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:142 (include)


Error: Building package pcl:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  package: pcl[core,cuda]:x64-windows-static -> 1.12.0
  vcpkg version: 2021-11-02-af04ebf6274fd6f7a941bff4662b3955c64f6f42
  vcpkg-tool version: 8acb35e27 2021-11-05 (16 hours ago)

**Comment by JackBoos** [comment]
Does `pcl_cuda_common-1.12.pc` exists in _D:/0temp/vcpkg/installed/x64-windows-static/lib/pkgconfig_ ?
cc @raahilsha-z

**Comment by weibingrong** [comment]
> Does `pcl_cuda_common-1.12.pc` exists in _D:/0temp/vcpkg/installed/x64-windows-static/lib/pkgconfig_ ? cc @raahilsha-z

No, there is no pcl_cuda_common-1.12.pc in the whole vcpkg directory

**Comment by JackBoos** [comment]
Please keep this issue open.

**Comment by JackBoosY** [comment]
```'

    Directory: F:\vcpkg\packages\pcl_x64-windows-static\debug\lib\pkgconfig


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         11/8/2021  12:00 AM            371 pcl_2d-1.12.pc
-a----         11/8/2021  12:00 AM            387 pcl_common-1.12.pc
-a----         11/8/2021  12:00 AM            474 pcl_cuda_features-1.12.pc
-a----         11/8/2021  12:00 AM            496 pcl_cuda_sample_consensus-1.12.pc
-a----         11/8/2021  12:00 AM            480 pcl_cuda_segmentation-1.12.pc
-a----         11/8/2021  12:00 AM            488 pcl_features-1.12.pc
-a----         11/8/2021  12:00 AM            481 pcl_filters-1.12.pc
-a----         11/8/2021  12:00 AM            380 pcl_geometry-1.12.pc
-a----         11/8/2021  12:00 AM            501 pcl_gpu_containers-1.12.pc
-a----         11/8/2021  12:00 AM            623 pcl_gpu_features-1.12.pc
-a----         11/8/2021  12:00 AM            442 pcl_gpu_octree-1.12.pc
-a----         11/8/2021  12:00 AM            506 pcl_gpu_segmentation-1.12.pc
-a----         11/8/2021  12:00 AM            433 pcl_gpu_utils-1.12.pc
-a----         11/8/2021  12:00 AM            410 pcl_io-1.12.pc
-a----         11/8/2021  12:00 AM            410 pcl_kdtree-1.12.pc
-a----         11/8/2021  12:00 AM            498 pcl_keypoints-1.12.pc
-a----         11/8/2021  12:00 AM            401 pcl_ml-1.12.pc
-a----         11/8/2021  12:00 AM            403 pcl_octree-1.12.pc
-a----         11/8/2021  12:00 AM            578 pcl_recognition-1.12.pc
-a----         11/8/2021  12:00 AM            536 pcl_registration-1.12.pc
-a----         11/8/2021  12:00 AM            459 pcl_sample_consensus-1.12.pc
-a----         11/8/2021  12:00 AM            443 pcl_search-1.12.pc
-a----         11/8/2021  12:00 AM            566 pcl_segmentation-1.12.pc
-a----         11/8/2021  12:00 AM            415 pcl_stereo-1.12.pc
-a----         11/8/2021  12:00 AM            455 pcl_surface-1.12.pc
-a----         11/8/2021  12:00 AM            476 pcl_tracking-1.12.pc


PS F:\vcpkg\packages\pcl_x64-windows-static\debug\lib\pkgconfig>
```

**Comment by LOVELESSYI** [comment]
> ```
> 
>     Directory: F:\vcpkg\packages\pcl_x64-windows-static\debug\lib\pkgconfig
> 
> 
> Mode                 LastWriteTime         Length Name
> ----                 -------------         ------ ----
> -a----         11/8/2021  12:00 AM            371 pcl_2d-1.12.pc
> -a----         11/8/2021  12:00 AM            387 pcl_common-1.12.pc
> -a----         11/8/2021  12:00 AM            474 pcl_cuda_features-1.12.pc
> -a----         11/8/2021  12:00 AM            496 pcl_cuda_sample_consensus-1.12.pc
> -a----         11/8/2021  12:00 AM            480 pcl_cuda_segmentation-1.12.pc
> -a----         11/8/2021  12:00 AM            488 pcl_features-1.12.pc
> -a----         11/8/2021  12:00 AM            481 pcl_filters-1.12.pc
> -a----         11/8/2021  12:00 AM            380 pcl_geometry-1.12.pc
> -a----         11/8/2021  12:00 AM            501 pcl_gpu_containers-1.12.pc
> -a----         11/8/2021  12:00 AM            623 pcl_gpu_features-1.12.pc
> -a----         11/8/2021  12:00 AM            442 pcl_gpu_octree-1.12.pc
> -a----         11/8/2021  12:00 AM            506 pcl_gpu_segmentation-1.12.pc
> -a----         11/8/2021  12:00 AM            433 pcl_gpu_utils-1.12.pc
> -a----         11/8/2021  12:00 AM            410 pcl_io-1.12.pc
> -a----         11/8/2021  12:00 AM            410 pcl_kdtree-1.12.pc
> -a----         11/8/2021  12:00 AM            498 pcl_keypoints-1.12.pc
> -a----         11/8/2021  12:00 AM            401 pcl_ml-1.12.pc
> -a----         11/8/2021  12:00 AM            403 pcl_octree-1.12.pc
> -a----         11/8/2021  12:00 AM            578 pcl_recognition-1.12.pc
> -a----         11/8/2021  12:00 AM            536 pcl_registration-1.12.pc
> -a----         11/8/2021  12:00 AM            459 pcl_sample_consensus-1.12.pc
> -a----         11/8/2021  12:00 AM            443 pcl_search-1.12.pc
> -a----         11/8/2021  12:00 AM            566 pcl_segmentation-1.12.pc
> -a----         11/8/2021  12:00 AM            415 pcl_stereo-1.12.pc
> -a----         11/8/2021  12:00 AM            455 pcl_surface-1.12.pc
> -a----         11/8/2021  12:00 AM            476 pcl_tracking-1.12.pc
> 
> 
> PS F:\vcpkg\packages\pcl_x64-windows-static\debug\lib\pkgconfig>
> ```

I also meet this problem. But there is only "pcl_common-1.12.pc", not "pcl_cuda_common-1.12", in the folder you show.

**Comment by sfhacker** [comment]
[1] https://english-for-chinese.blogspot.com/2008/06/and-meet-problem.html

**Comment by LOVELESSYI** [comment]
> [1] https://english-for-chinese.blogspot.com/2008/06/and-meet-problem.html

Thank you for pointing out my problems in English expression！

**Comment by raahilsha-z** [comment]
I don't have a pcl_cuda_common in my installed pkgconfig directory (only cuda_features, cuda_sample_consensus, and cuda_segmentation). There's also no pcl_cuda_common.lib file, anyways.

Looking at the source code for PCL, however, pcl/cuda/common doesn't have any source files (headers only - https://github.com/PointCloudLibrary/pcl/tree/master/cuda/common). I don't think there's supposed to pcl_cuda_common to begin with.

**Comment by raahilsha-z** [comment]
I just tried building static with cuda and get the same error as @weibingrong (Package 'pcl_cuda_common-1.12'... not found). As I mentioned above, though, this package shouldn't exist in the first place anyways.
