### ISSUE TITLE
[libnoise] is missing its config.cmake

### ISSUE THREAD

**Issue by dannypike** [microsoft/vcpkg#21228]
**Describe the bug**
There is no `libnoise-config.cmake` file for this port, so `find_package()` cannot find it.

**Environment**
- OS: Windows
- Compiler: Visual Studio 2019

**To Reproduce**
Add `find_package(libnoise CONFIG REQUIRED)` to your CMakeLists.txt file.

**Failure logs** 
```
1> [CMake]   Could not find a package configuration file provided by "libnoise" with any
1> [CMake]   of the following names:
1> [CMake] 
1> [CMake]     libnoiseConfig.cmake
1> [CMake]     libnoise-config.cmake
1> [CMake] 
1> [CMake]   Add the installation prefix of "libnoise" to CMAKE_PREFIX_PATH or set
1> [CMake]   "libnoise_DIR" to a directory containing one of the above files.  If
1> [CMake]   "libnoise" provides a separate development package or SDK, be sure it has
1> [CMake]   been installed.
```

**Additional context**
The same syntax works for other ports, e.g. `libpng`

**Comment by dg0yt** [comment]
> find_package(noise CONFIG REQUIRED)

For this to work, upstream (libnoise) must provide config files. vcpkg can't do that. (At best, vcpkg can add "unofficial" configs for convenience with complex dependencies.)

**Comment by dannypike** [comment]
Yes but I thought that the appropriate action is post problems for each port here, with the name of the package in brackets.

Is that wrong?

**Comment by dg0yt** [comment]
> Yes but I thought that the appropriate action is post problems for each port here, with the name of the package in brackets.
> 
> Is that wrong?

It is not wrong in general, and I didn't want to give that impression. 

However, some issues are upstream issues (or design decisions).
I don't think that vcpkg promises that for *every* port in vcpkg, `find_package(port CONFIG REQUIRED)` should just work.

**Comment by dannypike** [comment]
Ah, OK. Thank you for the clarification. As you gave me an [alternative solution](https://github.com/microsoft/vcpkg/discussions/21227#discussioncomment-1598828) this isn't important, so I'll close it.
