### ISSUE TITLE
libpq build failed

### ISSUE THREAD

**Issue by Matrix-Zhang** [Microsoft/vcpkg#2122]
Package: libpq:x64-windows
  Vcpkg version: 0.0.96-2017-11-03-aec7d6d60628602fa153633f7e7e92fe66af0655

**Comment by Mixaill** [comment]
Didn't reproduce

Can you please update `vcpkg` to latest master, re-run `vcpkg-bootstrap.bat` and try `vcpkg install libpq:x64-windows` again?

**Comment by Matrix-Zhang** [comment]
after reinstall windows, it's ok....

**Comment by flow-specter** [comment]
I met the same problem now...
