### ISSUE TITLE
Please give at least one example in the vcpkg toolchain script for CMake

### ISSUE THREAD

**Issue by dannypike** [microsoft/vcpkg#21226]
This comment:
```
## Notes
This command supplies many common arguments to configure. To see the full list, examine the source.
```
isn't very helpful to those of us who aren't fluent in how to "examine the source".

I've tried to understand the script but it's pretty obscure and convoluted and none of the things that I believe should have been exported by appropriate `set()` commands appear are defined when I try to use them in my CMakeLists.txt.

So, please would you expand this comment, perhaps with an example of how I might "examine the source" and determine the name of those variables that I might want to use but that you haven't added to the list at the top of the file?

**Comment by dg0yt** [comment]
> ```
> ## Notes
> This command supplies many common arguments to configure. To see the full list, examine the source.
> ```

This sentence appears in the documentation of `vcpkg_configure_make`, a function to be used in portfiles (CMake script mode) for building packages based on autotools or similar. It has no effect on user projects (CMake project mode), or on portfiles for building packages based on CMake.

But maybe you can name the variables you are expecting to be set from vcpkg's cmake toolchain file, `vcpkg.cmake`?

**Comment by dannypike** [comment]
I don't know the names, that's why I'm looking through the file. It just seems to be a strange thing for a comment to say, along the lines of:

```
Please do not read this sentence.
```

:)

**Comment by dg0yt** [comment]
Again, you are commenting the documentation of a maintainer function for dealing with autotools. Either you are happy to have a package which just works as expected, or you already know the common options (`--prefix`, `--target`), or you will dive into a much stranger world of autotools options, build scripts, and patches. So it is more along the lines of 
~~~
This is not what you are looking for you unless you 
- want to use `configure` and 
- are familiar, or want to get familiar, with autotools.
~~~

At least it would help to mark `configure` as a program name by proper backticks.

**Comment by dannypike** [comment]
OK, thanks.

I was only looking at the file, because I'm trying to find a way to get Visual Studio + CMake to be able to locate the `libnoise` _vcpkg_ package, as per [this ticket](https://github.com/microsoft/vcpkg/discussions/21227).
