### ISSUE TITLE
[lapack-reference] Cannot disable blas-select on Linux

### ISSUE THREAD

**Issue by cgmb** [microsoft/vcpkg#21224]
**Describe the bug**
On Linux, `USE_OPTIMIZED_BLAS=ON` [appears to always be set](https://github.com/microsoft/vcpkg/blob/66c39e113a348a6ae80419fae5a629b951b00f1a/ports/lapack-reference/portfile.cmake#L61) when using an external Fortran compiler, but it should only be true when using the blas-select or noblas features.

**Environment**
- OS: Linux (Ubuntu 18.04)
- Compiler: gfortran

**To Reproduce**
I created a project to illustrate the problem. It sets `"default-features": false` to disable blas-select.

1. Download the example project: https://gist.github.com/cgmb/371a8279ee5bc8f63285d0b96d920a41
2. Configure the project.
```
cmake -S. -Bbuild -DCMAKE_TOOLCHAIN_FILE=$VCPKG_PATH/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-linux
```
3. Examine the lapack-reference build parameters:
```
grep USE_OPTIMIZED_BLAS $VCPKG_PATH/buildtrees/lapack-reference/x64-linux-rel/CMakeCache.txt
```
Actual Output:
```
USE_OPTIMIZED_BLAS:BOOL=ON
```
Expected Output:
```
USE_OPTIMIZED_BLAS:BOOL=OFF
```

**Comment by PhoebeHui** [comment]
@cgmb,t thanks for reporting this issue! Could you help test linked PR and see if it works for you?
