### ISSUE TITLE
vcpkg tool fails to build on FreeBSD

### ISSUE THREAD

**Issue by kuriboshi** [microsoft/vcpkg#21229]
**Describe the bug**
Compilation of the `vcpkg` tool fails.

**Environment**
- OS: FreeBSD 13.0
- Compiler: FreeBSD clang version 11.0.1

**To Reproduce**
1. `git clone https://github.com/microsoft/vcpkg-tool`
2. `cd vcpkg-tool`
2. `mkdir build`
3. `cd build`
4. `cmake ..`
5. `make`

**Expected behavior**
I expect the compilation to be successful.

**Failure logs** 
```
[  0%] Building CXX object _deps/fmt-build/CMakeFiles/fmt.dir/src/format.cc.o
[  1%] Building CXX object _deps/fmt-build/CMakeFiles/fmt.dir/src/os.cc.o
[  2%] Linking CXX static library libfmt.a
[  2%] Built target fmt
[  2%] Building CXX object CMakeFiles/vcpkglib.dir/src/vcpkg/base/checks.cpp.o
[  3%] Building CXX object CMakeFiles/vcpkglib.dir/src/vcpkg/base/chrono.cpp.o
[  4%] Building CXX object CMakeFiles/vcpkglib.dir/src/vcpkg/base/cofffilereader.cpp.o
[  5%] Building CXX object CMakeFiles/vcpkglib.dir/src/vcpkg/base/downloads.cpp.o[  6%] Building CXX object CMakeFiles/vcpkglib.dir/src/vcpkg/base/files.cpp.o
/home/krister/Projects/vcpkg-tool/src/vcpkg/base/files.cpp:2733:38: error: use of undeclared identifier 'i_fd'
            while (auto read_bytes = i_fd.read(buffer, buffer_length))
                                     ^
1 error generated.
*** Error code 1
```

**Additional context**
The following patch fixes the problem and all tests complete successfully.
```
diff --git a/src/vcpkg/base/files.cpp b/src/vcpkg/base/files.cpp
index c80aa2d6..6d4d334c 100644
--- a/src/vcpkg/base/files.cpp
+++ b/src/vcpkg/base/files.cpp
@@ -2730,7 +2730,7 @@ namespace vcpkg
 #else  // ^^^ defined(__APPLE__) // !(defined(__APPLE__) || defined(__linux__)) vvv
             constexpr std::size_t buffer_length = 4096;
             unsigned char buffer[buffer_length];
-            while (auto read_bytes = i_fd.read(buffer, buffer_length))
+            while (auto read_bytes = source_fd.read(buffer, buffer_length))
             {
                 if (read_bytes == -1)
                 {
```

**Comment by JackBoosY** [comment]
You can directly use vcpkg pre-build binary instead of build it.

**Comment by kuriboshi** [comment]
As far as I know there are no pre-built executables for FreeBSD and compilation errors prevents anyone from providing one since commit d4a0cec3d3ad5eb0f41154bd0b0e9eafd86aff00.

**Comment by BillyONeal** [comment]
Can you make a PR with that patch against https://github.com/microsoft/vcpkg-tool ? You should get credit for fixing it!

**Comment by PhoebeHui** [comment]
This issue should be fixed in latest release.

**Comment by nunotexbsd** [comment]
Hi @kuriboshi,

What's the status of vcpkg on FreeBSD? Are thinking porting it?

Cheers,

Nuno Teixeira

**Comment by BillyONeal** [comment]
I believe we at least build on FreeBSD but not netbsd. See also https://github.com/microsoft/vcpkg-tool/pull/359
