### ISSUE TITLE
[libwebsockets] fails with triplet x64-mingw (static/dynamic)

### ISSUE THREAD

**Issue by facontidavide** [microsoft/vcpkg#21233]
Building package libwebsockets[core]:x64-mingw-static...
-- Using community triplet x64-mingw-static. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: C:\dev\vcpkg\triplets\community\x64-mingw-static.cmake
-- Using cached warmcat-libwebsockets-8d605f0649ed1ab6d27a443c7688598ea21fdb75.tar.gz.
-- Cleaning sources at C:/dev/vcpkg/buildtrees/libwebsockets/src/8ea21fdb75-57eb5491c5.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/dev/vcpkg/downloads/warmcat-libwebsockets-8d605f0649ed1ab6d27a443c7688598ea21fdb75.tar.gz
-- Applying patch fix-dependency-libuv.patch
-- Applying patch fix-build-error.patch
-- Applying patch export-include-path.patch
-- Using source at C:/dev/vcpkg/buildtrees/libwebsockets/src/8ea21fdb75-57eb5491c5.clean
-- Configuring x64-mingw-static
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: ninja -v
    Working Directory: C:/dev/vcpkg/buildtrees/libwebsockets/x64-mingw-static-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\dev\vcpkg\buildtrees\libwebsockets\config-x64-mingw-static-out.log

Call Stack (most recent call first):
  installed/x64-mingw-static/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:411 (vcpkg_execute_required_process)
  ports/libwebsockets/portfile.cmake:135 (vcpkg_cmake_configure)
  scripts/ports.cmake:142 (include)

Error: Building package libwebsockets:x64-mingw-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  package: libwebsockets[core]:x64-mingw-static -> 4.2.2#3
  vcpkg version: 2021-11-02-af04ebf6274fd6f7a941bff4662b3955c64f6f42
  vcpkg-tool version: 66c39e113 2021-11-05 (14 hours ago)

**Comment by JackBoosY** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
