### ISSUE TITLE
[libnoise] the FindLibNoise.cmake script did not find noiseutils.lib

### ISSUE THREAD

**Issue by dannypike** [microsoft/vcpkg#21235]
**Describe the bug**
The `FindLibNoise.cmake` script only finds `noise.lib`. It does not find `noiseutils.lib`.

**Environment**
- OS: Windows
- Compiler: Visual Studio 2019

**To Reproduce**
Use a CMakeLists.txt file something like this:
```
include(${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/share/libnoise/FindLibNoise.cmake)
message("LIBNOISE_LIBRARIES = '${LIBNOISE_LIBRARIES}'")
```
and it will show that it has only found noise.lib:

```
1> [CMake] LIBNOISE_LIBRARIES = 'D:/work/github/vcpkg/installed/x64-windows/debug/lib/noise.lib'
```

This appears to be because the person who ported this library assumed that the CMake `find_library` script will find and add all of matching .lib files for the names that are specified. In fact, CMake only matches the first one it can find, i.e. the names are alternatives for a single file, not names of multiple files. Presumably that's why the name of the command is `find_library` and not `find_libraries`. :)

A bug like this leads me to wonder if this is even a working implementation of libnoise? Should I be using something else instead?

**Comment by NancyLi1013** [comment]
The current usage is broken. As you can see, if `noise `is found. `noiseutils` will not be searched again.

https://github.com/qknight/libnoise/blob/032caf6572707e3e3acd5e6a899a315d9ad78d8c/cmake/Modules/FindLibNoise.cmake#L48

This is a bug in upstream.
