### ISSUE TITLE
[pcl[vtk]:x64-linux] build failure

### ISSUE THREAD

**Issue by AlexLeungZ** [microsoft/vcpkg#21241]
Host Environment

x64-linux:
OS: Ubuntu 20.04.3 LTS on Windows 10 x86_64 (WSL)
Compiler: g++ (Ubuntu 11.1.0-1ubuntu1~20.04) 11.1.0
CMake version: cmake version 3.21.2

arm64-linux:
OS: Ubuntu 20.04.3 LTS
Compiler: g++ (Ubuntu 11.1.0-1ubuntu1~20.04) 11.1.0
CMake version: cmake version 3.22.0-rc2

**To Reproduce**
`git clone https://github.com/microsoft/vcpkg`
`sudo ./vcpkg/bootstrap-vcpkg.sh`
`sudo vcpkg/vcpkg integrate install`
then hit build with vscode's cmake extension

**vcpkg.json**
```
{
    "name": "robocon-test-code",
    "version": "1.0",
    "dependencies": [
        {
            "name": "vtk",
            "features": [ ]            
        },
        {
            "name": "pcl",
            "features": [ "vtk" ]
        }
    ],
    
    "builtin-baseline": "66c39e113a348a6ae80419fae5a629b951b00f1a",
    "overrides": [
        {
            "name": "vtk",
            "version-semver": "9.0.3-pv5.9.1#3"
        }
    ]
}
```

**Expected Behavior**
Installs without error

**Failure logs** 
```
[cmake] -- Building x64-linux-dbg
[cmake] CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:155 (message):
[cmake]     Command failed: /home/alex/.local/lib/pypy3.6/site-packages/cmake/data/bin/cmake --build . --config Debug --target install -- -v -j33
[cmake]     Working Directory: /mnt/d/Git/GitHub/robocon-test-code/vcpkg/buildtrees/pcl/x64-linux-dbg
[cmake]     See logs for more information:
[cmake]       /mnt/d/Git/GitHub/robocon-test-code/vcpkg/buildtrees/pcl/install-x64-linux-dbg-out.log
[cmake] 
[cmake] Call Stack (most recent call first):
[cmake]   /mnt/d/Git/GitHub/robocon-test-code/build/vcpkg_installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_build.cmake:102 (vcpkg_execute_build_process)
[cmake]   /mnt/d/Git/GitHub/robocon-test-code/build/vcpkg_installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
[cmake]   buildtrees/versioning/versions/pcl/6a65773e049bbdfef835781a6a61ee6a3a94dd27/portfile.cmake:60 (vcpkg_cmake_install)
[cmake]   scripts/ports.cmake:142 (include)
[cmake] 
[cmake] 
[cmake] Error: Building package pcl:x64-linux failed with: BUILD_FAILED
[cmake] Please ensure you're using the latest portfiles with `git pull` and `./vcpkg update`, then
[cmake] submit an issue at https://github.com/Microsoft/vcpkg/issues including:
[cmake]   package: pcl[core,vtk]:x64-linux -> 1.12.0
[cmake]   vcpkg version: 2021-10-25-b4bff9afacafb0a234a8f20fd6451b2362c0f9a0
[cmake]   vcpkg-tool version: 66c39e113 2021-11-05 (2 days ago)
[cmake] 
[cmake] Additionally, attach any relevant sections from the log files above.
[cmake] -- Running vcpkg install - failed
[cmake] CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:831 (message):
[cmake]   vcpkg install failed.  See logs for more information:
[cmake]   /mnt/d/Git/GitHub/robocon-test-code/build/vcpkg-manifest-install.log
[cmake] Call Stack (most recent call first):
[cmake]   build/CMakeFiles/3.21.2/CMakeSystem.cmake:6 (include)
[cmake]   CMakeLists.txt:2 (project)
[cmake] 
[cmake] 
[cmake] -- Configuring incomplete, errors occurred!
[cmake] See also "/mnt/d/Git/GitHub/robocon-test-code/build/CMakeFiles/CMakeOutput.log".
[cmake] See also "/mnt/d/Git/GitHub/robocon-test-code/build/CMakeFiles/CMakeError.log".
```

Full log is attached here:
[20211107_pcl_vtk_log.txt](https://github.com/microsoft/vcpkg/files/7492454/20211107_pcl_vtk_log.txt)

**Additional context**
/mnt/d/Git/GitHub/robocon-test-code/build/vcpkg-manifest-install.log
[vcpkg-manifest-install.log](https://github.com/microsoft/vcpkg/files/7492457/vcpkg-manifest-install.log)

/mnt/d/Git/GitHub/robocon-test-code/vcpkg/buildtrees/pcl/config-x64-linux-dbg-out.log
[config-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/7492463/config-x64-linux-dbg-out.log)

/mnt/d/Git/GitHub/robocon-test-code/vcpkg/buildtrees/pcl/install-x64-linux-dbg-out.log
[install-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/7492458/install-x64-linux-dbg-out.log)

/mnt/d/Git/GitHub/robocon-test-code/build/CMakeFiles/CMakeOutput.log
[CMakeOutput.log](https://github.com/microsoft/vcpkg/files/7492461/CMakeOutput.log)

/mnt/d/Git/GitHub/robocon-test-code/build/CMakeFiles/CMakeError.log
[CMakeError.log](https://github.com/microsoft/vcpkg/files/7492462/CMakeError.log)

**Comment by dg0yt** [comment]
FTR it fails here (install-x64-linux-dbg-out.log):
~~~
/usr/bin/ld: lib/libpcl_io.a(openni_driver.cpp.o): undefined reference to symbol 'libusb_get_device_descriptor'
/usr/bin/ld: /lib/x86_64-linux-gnu/libusb-1.0.so.0: error adding symbols: DSO missing from command line
~~~

**Comment by AlexLeungZ** [comment]
How can I fix this, as this also happened on my arm64-linux

**Comment by AlexLeungZ** [comment]
Here is the workaround to build it, only tested on x64-linux, arm64-linux is not yet been tested.
The method here is similar what I've done for the [vtk[core] fix](https://apt.kitware.com/ "vtk[core] fix")

1. After the first failed build with `VCPKG`, you should have a file called `PointCloudLibrary-pcl-xxx.tar.gz` in path `.../vcpkg/downloads`, in my case it is `.../vcpkg/downloads/PointCloudLibrary-pcl-f36a69a5e89953708990c4669317f989d532cf08.tar.gz`
2. `cd` into that directory
3. Unzip the `.tar.gz` file, with `unpigz xvf PointCloudLibrary-pcl-xxx.tar.gz` then `tar xvf PointCloudLibrary-pcl-xxx.tar`
4. Right now, you should have a directory called `pcl-xxx`
5. Edit the following file: `/io/CMakeLists.txt`
6. In line 358, replace
```
if(LIBUSB_FOUND)
  target_link_libraries("${LIB_NAME}" libusb::libusb)
endif()
```
with 
```
find_package(libusb CONFIG REQUIRED)

if(LIBUSB_FOUND)
  target_include_directories("${LIB_NAME}" PUBLIC ${LIBUSB_INCLUDE_DIRS})
  target_link_libraries("${LIB_NAME}" ${LIBUSB_LIBRARIES})
endif()
```
7. Save everything
8. zip the directory `pcl-xxx`, with `tar cvf pcl-xxx.tar pcl-xxx`, then `pigz pcl-xxx.tar`
9. Rename the file as `PointCloudLibrary-pcl-xxx.tar.gz`, which should be the same as what it is named in the downloaded path of vcpkg
10. Replace the old `PointCloudLibrary-pcl-xxx.tar.gz` with your new one
Step 11 - 14 are same as [vtk[core] fix](https://apt.kitware.com/ "vtk[core] fix")

**Comment by JackBoosY** [comment]
Sadly, I can't repro this issue on my local machine.

**Comment by AlexLeungZ** [comment]
I tried to build them on both my wsl and the Xavier NX, which is arm64-linux machine, and they both fail on the same issue

**Comment by dg0yt** [comment]
> /usr/bin/ld: /lib/x86_64-linux-gnu/libusb-1.0.so.0...

To reproduce it, you probably
- must not  have installed port libusb, 
- must have installed system package libusb-dev (or similar)

**Comment by AlexLeungZ** [comment]
```
-- Performing post-build validation
There should be no bin\ directory in a static build, but /mnt/d/Git/GitHub/robocon-test-code/vcpkg/packages/pcl_x64-linux/bin is present.
There should be no debug\bin\ directory in a static build, but /mnt/d/Git/GitHub/robocon-test-code/vcpkg/packages/pcl_x64-linux/debug/bin is present.
If the creation of bin\ and/or debug\bin\ cannot be disabled, use this in the portfile to remove them

    if(VCPKG_LIBRARY_LINKAGE STREQUAL "static")
        file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/bin" "${CURRENT_PACKAGES_DIR}/debug/bin")
    endif()

Found 1 error(s). Please correct the portfile:
    /mnt/d/Git/GitHub/robocon-test-code/vcpkg/buildtrees/versioning/versions/pcl/6a65773e049bbdfef835781a6a61ee6a3a94dd27/portfile.cmake
-- Performing post-build validation done
Error: Building package pcl:x64-linux failed with: POST_BUILD_CHECKS_FAILED
Please ensure you're using the latest portfiles with `git pull` and `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  package: pcl[core,cuda,vtk]:x64-linux -> 1.12.0
  vcpkg version: 2021-10-25-b4bff9afacafb0a234a8f20fd6451b2362c0f9a0
  vcpkg-tool version: 66c39e113 2021-11-05 (2 days ago)

Additionally, attach any relevant sections from the log files above.
```

vcpkg complains about bin in the folder, so `portfile.cmake` needs to be adjust

**Comment by JackBoosY** [comment]
In _source/CMakeLists.txt_ line 319:
```cmake
option(WITH_LIBUSB "Build USB RGBD-Camera drivers" TRUE)
if(WITH_LIBUSB)
  find_package(libusb)
endif()
```
In _source/cmake/Modules/FindOpenNI2.cmake_ line 36:
```cmake
if(OPENNI2_INCLUDE_DIR AND OPENNI2_LIBRARY)
...
  # Libraries
  if(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
    find_package(libusb REQUIRED)
    set(OPENNI2_LIBRARIES ${OPENNI2_LIBRARY} libusb::libusb)
  else()
    set(OPENNI2_LIBRARIES ${OPENNI2_LIBRARY})
  endif()
```

In _source/cmake/Modules/FindOpenNI.cmake_ line 46:
```cmake
if(OPENNI_INCLUDE_DIR AND OPENNI_LIBRARY)
...
  # Libraries
  if(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
    find_package(libusb REQUIRED)
    set(OPENNI_LIBRARIES ${OPENNI_LIBRARY} libusb::libusb)
  else()
    set(OPENNI_LIBRARIES ${OPENNI_LIBRARY})
  endif()
```

Option `WITH_LIBUSB` always be `OFF` since pcl was added in vcpkg 5 years ago (https://github.com/microsoft/vcpkg/pull/1283), and the system is not MacOS, so I'm confused why pcl need link to libusb and use libusb functions.

**Comment by dg0yt** [comment]
> Option `WITH_LIBUSB` always be `OFF` since pcl was added in vcpkg 5 years ago (#1283), and the system is not MacOS, so I'm confused why pcl need link to libusb and use libusb functions.

`WITH_LIBUSB` only controls direct calls to `find_package(libusb)` in pcl. But there might be unguarded calls from cmake packages used by pcl.

**Comment by JackBoosY** [comment]
> `WITH_LIBUSB` only controls direct calls to `find_package(libusb)` in pcl. But there might be unguarded calls from cmake packages used by pcl.

Not likely, `libusb` doesn't in the dependency chain.

And I found other stuff interesting:
In _source/io/CMakeLists,txt_ line 78:
```cmake
if(WITH_OPENNI)
...
  set(OPENNI_GRABBER_SOURCES
...
    src/openni_camera/openni_driver.cpp
...
  )
```
In _io/src/opennni_camera/openni_driver.cpp_ 
line 58:
```cpp
#ifndef _WIN32
#include <libusb-1.0/libusb.h>
#endif
```
line 362:
```cpp
#ifndef _WIN32
...
void
openni_wrapper::OpenNIDriver::getDeviceInfos () noexcept
{
...
    result = libusb_get_device_descriptor (devices[devIdx], &descriptor);
...
)
```

This proves that if `WITH_OPENNI` is enabled, libusb will become a mandatory dependency in non-Windows, which does not match the setting in `FindOpenNI[2].cmake`.

**Comment by dg0yt** [comment]
> Not likely, `libusb` doesn't in the dependency chain.

This is not a contradiction: If port `libusb` was in the dependency chain, pcl probably wouldn't pick up the system's libusb.

**Comment by dg0yt** [comment]
> So I can confirm this is a upstream bug.

Even if upstream doesn't sufficiently express the dependencies, it can be solved on the vcpkg packaging side with features and dependencies.

**Comment by JackBoosY** [comment]
> > So I can confirm this is a upstream bug.
> 
> Even if upstream doesn't sufficiently express the dependencies, it can be solved on the vcpkg packaging side with features and dependencies.

Yes, but let me report this to the upstream first.
