### ISSUE TITLE
Porting request: CoolProp

### ISSUE THREAD

**Issue by nitrogene** [Microsoft/vcpkg#2125]
https://github.com/CoolProp/CoolProp

From github page:

> CoolProp is a thermophysical property database and wrappers for a selection of programming environments. It offers similar functionality to REFPROP, but CoolProp is open-source and free. It was originally developed by Ian Bell, currently a post-doc at the University of Liege, in Liege, Belgium.

Please let me thank you for your job. VCPKG makes it soooo easy to work with open source projects !

**Comment by xoviat** [comment]
This one is fairly easy.

**Comment by xoviat** [comment]
Actually not. I'll need to work up the dependency chain.
