### ISSUE TITLE
[VTK] Build failed

### ISSUE THREAD

**Issue by nitrogene** [Microsoft/vcpkg#2126]
This is the same issue than #2106.

I am unable to install VTK (Laptop, Windows 10, VS2017). Here are the relevant parts - I guess the issue is with the semicolon.

-- Build x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:43 (message):
    Command failed: D:/Dev/vcpkg/downloads/cmake-3.9.5-win32-x86/bin/cmake.exe;--build;.;--config;Release;--target;install;--;-v
    Working Directory: D:/Dev/vcpkg/buildtrees/vtk/x64-windows-rel
    See logs for more information:
      D:\Dev\vcpkg\buildtrees\vtk\install-x64-windows-rel-out.log
      D:\Dev\vcpkg\buildtrees\vtk\install-x64-windows-rel-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:62 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/vtk/portfile.cmake:169 (vcpkg_install_cmake)
  scripts/ports.cmake:72 (include)

Error: Building package vtk:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: vtk:x64-windows
  Vcpkg version: 0.0.96-2017-11-03-aec7d6d60628602fa153633f7e7e92fe66af0655
Additionally, attach any relevant sections from the log files above.

Here's a link to install log:
[install-x64-windows-rel-out.log](https://github.com/Microsoft/vcpkg/files/1443236/install-x64-windows-rel-out.log)

**Comment by xoviat** [comment]
You would think a C/C++ developer could at least post the error:


```
D:\Dev\vcpkg\installed\x64-windows\include\hpdf.h(464): error C2061: syntax error: identifier 'HPDF_Boolean'
```

**Comment by xoviat** [comment]
Can you update your libharu portfile to #2128, purge your packages, and rebuild?

**Comment by nitrogene** [comment]
I was away but I tried early this morning and #2140 solve this issue. 

Thx.
