### ISSUE TITLE
package: qtwebengine[core,default-features,geolocation,spellchecker,webchannel]:x64-windows -> 6.2.1

### ISSUE THREAD

**Issue by RomanTruhanov** [microsoft/vcpkg#21260]
Выпуск	Windows 11 Pro Insider Preview
Версия	Dev
Дата установки	‎04.‎11.‎2021
Сборка ОС	22494.1000
Взаимодействие	Windows Feature Experience Pack 1000.22494.1000.0

Visual Studio 2022 Dev Preview 7 (compiller version 17.0.0)

vcpkg-tool version: 66c39e113 2021-11-05 (3 days ago)

qt[core,default-features]:x64-windows -> 6.2.1

.\vcpkg.exe install qt

[install-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/7499238/install-x64-windows-dbg-err.log)

[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/7499237/install-x64-windows-dbg-out.log)

**Comment by NancyLi1013** [comment]
Hi @RomanTruhanov Thanks for posting this issue. 
Duplicated to #20702. Let's track this issue there.

**Comment by RomanTruhanov** [comment]
nope i am tested 3 version visual studio: 2019 (compiller version 16.11.6)  2022 current (compiller version 17.0.0) and 2022 Preview (compiller version 17.1.0 preview 1) debug building work fine but in release build failed.  Maybe it's build bug...

![image](https://user-images.githubusercontent.com/13104248/141421111-694c1493-b190-4ded-86c1-89a7bbd91b93.png)

full logs my qtwebengine buildtree

[qtwebengine.zip](https://github.com/microsoft/vcpkg/files/7525333/qtwebengine.zip)

**Comment by NancyLi1013** [comment]
@RomanTruhanov

Please move attention to #20702.

**Comment by RomanTruhanov** [comment]
yes im frist to use set(VCPKG_VISUAL_STUDIO_PATH "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise") and clean rebuilding... but not working
