### ISSUE TITLE
portable cmake error

### ISSUE THREAD

**Issue by cenit** [Microsoft/vcpkg#2127]
After today's update of required cmake to 3.9.5 (why do you do it so quickly after every release?) I have a problem: usually vcpkg does NOT need to download a portable cmake because I keep it up to date with chocolatey. But since choco is not as quick as you to update packages, vcpkg just informed me that it had to download a suitable version of cmake (I still had 3.9.4 installed system-wide)
This is what happened (and it is reproducible on some other machines of mine)
```
A suitable version of cmake was not found (required v3.9.5). Downloading portable cmake v3.9.5...
Launching powershell failed or was denied when trying to fetch cmake version 3.9.5.
(No sufficient installed version was found)
```
I cannot understand what is the problem

**Comment by alexkaratarakis** [comment]
Firstly, sorry for the eager updates; that is on me.
However, not being able to download through PowerShell is unexpected.
Can you give me some more info?:

- In latest master, I improved the error message. Please do:
```
>git pull
>.\bootstrap-vcpkg.bat
```
and try again.

- What is your Windows version? To find it, you can do this on PowerShell:
```
PS D:\workspace\vcpkg$ [System.Environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      17029  0
```
- Where is powershell.exe located? To find it, you can do:
```
PS D:\workspace\vcpkg$ where.exe powershell.exe
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
```
- What is the PowerShell version? To find it, you can do:
```
PS D:\workspace\vcpkg$ $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      17029  1000
```
- Can you run: `.\scripts\fetchDependency.ps1 cmake`? 

If the last one works, then you will have `cmake` so this can be used as a workaround while I am working on the issue.

**Comment by cenit** [comment]
I updated to the latest master and relaunched my install
```
Vcpkg package management program version 0.0.96-2017-11-04-330b8d8bab6a3d07165bf7c05fea09a8e0d56348
```
Now the error message is much longer, maybe you can find better the problem
This is what I got:
```
Building package boost:x64-windows-static...
A suitable version of cmake was not found (required v3.9.5). Downloading portable cmake v3.9.5...
Fetching %s version %s (No sufficient installed version was found)
Could not run:
    'C:/Users/....../vcpkg/scripts/fetchDependency.ps1'
Error message was:
    Expand-Archive : Impossibile trovare un parametro corrispondente al nome 'destinationpath'.
In C:\Users\......\vcpkg\scripts\fetchDependency.ps1:147 car:40
+             Expand-Archive -path $file -destinationpath $destination
+                                        ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Expand-Archive], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Pscx.Commands.IO.Compression.ExpandArchiveCommand

Could not detect or download cmake
In C:\Users\stefano\Codice\vcpkg\scripts\fetchDependency.ps1:278 car:9
+         throw ("Could not detect or download " + $Dependency)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not detect or download cmake:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not detect or download cmake
```
the italian phrase `Impossibile trovare un parametro corrispondente al nome` means "it's impossible to find a parameter that corresponds to name..."
I just changed my username and path to my code with six lower dots

I run on Windows 10 FCU
```
Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      16299  0
```
and Powershell is this:
```
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      16299  19
```
My Visual Studio is 2017 (15.4.2)

Just running `.\scripts\fetchDependency.ps1 cmake` gives the same error:
```
Expand-Archive : Impossibile trovare un parametro corrispondente al nome 'destinationpath'.
In C:\Users\stefano\Codice\vcpkg\scripts\fetchDependency.ps1:147 car:40
+             Expand-Archive -path $file -destinationpath $destination
+                                        ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Expand-Archive], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Pscx.Commands.IO.Compression.ExpandArchiveCommand

Could not detect or download cmake
In C:\Users\stefano\Codice\vcpkg\scripts\fetchDependency.ps1:278 car:9
+         throw ("Could not detect or download " + $Dependency)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not detect or download cmake:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not detect or download cmake
```

**Comment by cenit** [comment]
i think I found the problem!
You use `-destinationpath` which somehow was unknown to my cmdlet... So I tried to investigate.
If I do `get-help expand-archive` what I see is this:
```
PS C:\Users\sinigard\Downloads> get-help Expand-Archive

NOME
    Expand-Archive

RIEPILOGO
    PSCX Cmdlet: Expands a compressed archive file, or ArchiveEntry object, to its constituent file(s).


SINTASSI
    Expand-Archive [-LiteralPath] <String[]> [[-OutputPath] <String>] [-EntryPath <String[]>] [-FlattenPaths] [-Force]
    [-Index <Int32[]>] [-PassThru] [-Password <SecureString>] [-ShowProgress] [<CommonParameters>]
.....
```

as you can see, my `Expand-Archive` comes from `PSCX`! I have removed PSCX and now the problem should be solved.
As described here https://github.com/Pscx/Pscx/issues/23, since maybe I am not the only one with PSCX installed, maybe a good idea would be to module name qualify the command, so to write `Microsoft.PowerShell.Archive\Expand-Archive`. Is it too verbose?

**Comment by alexkaratarakis** [comment]
>As described here https://github.com/Pscx/Pscx/issues/23, since maybe I am not the only one with PSCX installed, maybe a good idea would be to module name qualify the command, so to write `Microsoft.PowerShell.Archive\Expand-Archive`. Is it too verbose?

If it solves the problem, then verbosity is not an issue :). 
Installing `PSCX` to investigate!

**Comment by xoviat** [comment]
BTW please do not drop the eager updates.

**Comment by alexkaratarakis** [comment]
Should be fixed in latest master, please try it!

**Comment by cenit** [comment]
it works also with PSCX installed now! Thanks a lot!
(I also reworked some scripts in the meantime to avoid in future to have PSCX installed whenever is possible, it seems that they're lagging behind a little bit)

**Comment by alexkaratarakis** [comment]
@cenit 
Sweet! Thanks for taking the time to investigate!
