### ISSUE TITLE
[New Port Request] firebase-cpp-sdk

### ISSUE THREAD

**Issue by IshaanKarnik** [microsoft/vcpkg#21279]
Library name: firebase-cpp-sdk

Library description: The repository contains the Firebase C++ SDK source, with support for Android, iOS, and desktop platforms. It includes the following Firebase libraries:

1. AdMob
2. Google Analytics for Firebase
3. Firebase Authentication
4. Firebase Realtime Database
5. Firebase Dynamic Links
6. Cloud Firestore
7. Cloud Functions for Firebase
8. Firebase Invites
9. Firebase Cloud Messaging
10. Firebase Remote Config
11. Cloud Storage for Firebase

Firebase is an app development platform with tools to help you build, grow and monetize your app. More information about Firebase can be found at https://firebase.google.com.

More information about the Firebase C++ SDK can be found at https://firebase.google.com/docs/cpp/setup. Samples on how to use the Firebase C++ SDK can be found at https://github.com/firebase/quickstart-cpp.

Source repository URL: https://github.com/firebase/firebase-cpp-sdk.git

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
