### ISSUE TITLE
[ pcl[cuda,opengl,openni2,pcap,qt,tools,vtk]:x64-windows ] build failure

### ISSUE THREAD

**Issue by LOVELESSYI** [microsoft/vcpkg#21282]
Thanks @JackBoosY  for fixing bug with "Package pcl_cuda_common-1.12 was not found" in https://github.com/PointCloudLibrary/pcl/issues/5025. But I got some new errors. I think the code to generate "libopenni2.pc" is probably missing as https://github.com/PointCloudLibrary/pcl/issues/5025, but I don't know where to modify it. Can anyone help me? Thanks a lot!

**Host Environment**
- OS: Windows

**To Reproduce**
`.\vcpkg.exe install pcl[cuda,opengl,openni2,pcap,qt,tools,vtk]:x64-windows --editable`

**Failure logs** 
```
.\vcpkg.exe install pcl[cuda,opengl,openni2,pcap,qt,tools,vtk]:x64-windows --editable
Computing installation plan...
The following packages will be built and installed:
    pcl[core,cuda,opengl,openni2,pcap,qt,tools,vtk]:x64-windows -> 1.12.0
Restored 0 packages from C:\Users\89785\AppData\Local\vcpkg\archives in 93.9 us. Use --debug to see more details.
Starting package 1/1: pcl:x64-windows
Building package pcl[core,cuda,opengl,openni2,pcap,qt,tools,vtk]:x64-windows...
-- Using cached PointCloudLibrary-pcl-f36a69a5e89953708990c4669317f989d532cf08.tar.gz.
-- Using source at C:/vcpkg/buildtrees/pcl/src/89d532cf08-fd49a85837
-- Found external ninja('1.10.2').
-- Configuring x64-windows
CMake Warning at installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:485 (message):
  The following variables are not used in CMakeLists.txt:

      PCL_BUILD_WITH_FLANN_DYNAMIC_LINKING_WIN32

  Please recheck them and remove the unnecessary options from the
  `vcpkg_cmake_configure` call.

  If these options should still be passed for whatever reason, please use the
  `MAYBE_UNUSED_VARIABLES` argument.
Call Stack (most recent call first):
  ports/pcl/portfile.cmake:42 (vcpkg_cmake_configure)
  scripts/ports.cmake:142 (include)


-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: C:/vcpkg/packages/pcl_x64-windows/share/pcl/copyright
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_2d-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_common-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_cuda_common-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_cuda_features-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_cuda_sample_consensus-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_cuda_segmentation-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_features-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_filters-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_geometry-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_gpu_containers-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_gpu_features-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_gpu_octree-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_gpu_segmentation-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_gpu_utils-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_io-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_kdtree-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_keypoints-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_ml-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_octree-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_outofcore-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_people-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_recognition-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_registration-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_sample_consensus-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_search-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_segmentation-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_stereo-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_surface-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_tracking-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_visualization-1.12.pc
-- Using cached msys-mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst.
-- Using msys root at C:/vcpkg/downloads/tools/msys2/aa5af7b2aa7e90e8
CMake Error at scripts/cmake/vcpkg_fixup_pkgconfig.cmake:78 (message):
  C:/vcpkg/downloads/tools/msys2/aa5af7b2aa7e90e8/mingw32/bin/pkg-config.exe
  --exists pcl_cuda_features-1.12 failed with error code: 1

      ENV{PKG_CONFIG_PATH}: "C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig;C:/vcpkg/packages/pcl_x64-windows/share/pkgconfig;C:/vcpkg/installed/x64-windows/lib/pkgconfig;C:/vcpkg/installed/x64-windows/share/pkgconfig"
      output: Package libopenni2 was not found in the pkg-config search path.

  Perhaps you should add the directory containing `libopenni2.pc'

  to the PKG_CONFIG_PATH environment variable

  Package 'libopenni2', required by 'pcl_io-1.12', not found
Call Stack (most recent call first):
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:201 (z_vcpkg_fixup_pkgconfig_check_files)
  ports/pcl/portfile.cmake:77 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:142 (include)


Error: Building package pcl:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  package: pcl[core,cuda,opengl,openni2,pcap,qt,tools,vtk]:x64-windows -> 1.12.0
  vcpkg version: 2021-11-02-af04ebf6274fd6f7a941bff4662b3955c64f6f42
  vcpkg-tool version: 4df8c6d7f 2021-11-08 (11 hours ago)

Additionally, attach any relevant sections from the log files above.
```

**Comment by JackBoosY** [comment]
Will be fixed by #21276.

**Comment by JackBoosY** [comment]
Please test #21276 again.

Thanks.

**Comment by LOVELESSYI** [comment]
> Please test #21276 again.
> 
> Thanks.

After updating the latest vcpkg,  deleting the comment in the https://github.com/PointCloudLibrary/pcl/issues/5025 and changing if(CMAKE_SYSTEM_NAME STREQUAL "Darwin") to if(NOT WIN32) in https://github.com/PointCloudLibrary/pcl/issues/5027, I still got  "Package libopenni2 was not found in the pkg-config search path".

Here is whole output:

`Computing installation plan...
The following packages will be built and installed:
    pcl[core,cuda,opengl,openni2,pcap,qt,tools,vtk]:x64-windows -> 1.12.0
Restored 0 packages from C:\Users\89785\AppData\Local\vcpkg\archives in 130.5 us. Use --debug to see more details.
Starting package 1/1: pcl:x64-windows
Building package pcl[core,cuda,opengl,openni2,pcap,qt,tools,vtk]:x64-windows...
-- Using cached PointCloudLibrary-pcl-f36a69a5e89953708990c4669317f989d532cf08.tar.gz.
-- Using source at C:/vcpkg/buildtrees/pcl/src/89d532cf08-fd49a85837
-- Found external ninja('1.10.2').
-- Configuring x64-windows
CMake Warning at installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:485 (message):
  The following variables are not used in CMakeLists.txt:

      PCL_BUILD_WITH_FLANN_DYNAMIC_LINKING_WIN32

  Please recheck them and remove the unnecessary options from the
  `vcpkg_cmake_configure` call.

  If these options should still be passed for whatever reason, please use the
  `MAYBE_UNUSED_VARIABLES` argument.
Call Stack (most recent call first):
  ports/pcl/portfile.cmake:42 (vcpkg_cmake_configure)
  scripts/ports.cmake:142 (include)


-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: C:/vcpkg/packages/pcl_x64-windows/share/pcl/copyright
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_2d-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_common-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_cuda_common-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_cuda_features-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_cuda_sample_consensus-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_cuda_segmentation-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_features-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_filters-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_geometry-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_gpu_containers-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_gpu_features-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_gpu_octree-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_gpu_segmentation-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_gpu_utils-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_io-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_kdtree-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_keypoints-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_ml-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_octree-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_outofcore-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_people-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_recognition-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_registration-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_sample_consensus-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_search-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_segmentation-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_stereo-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_surface-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_tracking-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_visualization-1.12.pc
-- Using cached msys-mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst.
-- Using msys root at C:/vcpkg/downloads/tools/msys2/aa5af7b2aa7e90e8
CMake Error at scripts/cmake/vcpkg_fixup_pkgconfig.cmake:78 (message):
  C:/vcpkg/downloads/tools/msys2/aa5af7b2aa7e90e8/mingw32/bin/pkg-config.exe
  --exists pcl_cuda_features-1.12 failed with error code: 1

      ENV{PKG_CONFIG_PATH}: "C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig;C:/vcpkg/packages/pcl_x64-windows/share/pkgconfig;C:/vcpkg/installed/x64-windows/lib/pkgconfig;C:/vcpkg/installed/x64-windows/share/pkgconfig"
      output: Package libopenni2 was not found in the pkg-config search path.

  Perhaps you should add the directory containing `libopenni2.pc'

  to the PKG_CONFIG_PATH environment variable

  Package 'libopenni2', required by 'pcl_io-1.12', not found
Call Stack (most recent call first):
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:201 (z_vcpkg_fixup_pkgconfig_check_files)
  ports/pcl/portfile.cmake:77 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:142 (include)


Error: Building package pcl:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  package: pcl[core,cuda,opengl,openni2,pcap,qt,tools,vtk]:x64-windows -> 1.12.0
  vcpkg version: 2021-11-02-af04ebf6274fd6f7a941bff4662b3955c64f6f42
  vcpkg-tool version: c32ccbb34 2021-11-10 (4 hours ago)

Additionally, attach any relevant sections from the log files above.`

**Comment by JackBoosY** [comment]
@LOVELESSYI  Please pull #21276 changes and try again.

**Comment by LOVELESSYI** [comment]
> @LOVELESSYI Please pull #21276 changes and try again.

I'm not familiar with Github, and I'm not sure if you want me to do  like this. I first run
 `gh pr checkout 21276`
then
`.\vcpkg.exe install pcl[cuda,opengl,openni2,pcap,qt,tools,vtk]:x64-windows`
But I get the same error as above. 

> output: Package libopenni2 was not found in the pkg-config search path.

**Comment by JackBoosY** [comment]
@LOVELESSYI Can you please provide file _C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_io-1.12.pc_ ?

**Comment by LOVELESSYI** [comment]
> @LOVELESSYI Can you please provide file _C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_io-1.12.pc_ ?

```
prefix=${pcfiledir}/../..
# This file was generated by CMake for PCL library pcl_io
exec_prefix=${prefix}
libdir=${prefix}/lib
#includedir=${prefix}/include/pcl
includedir=${prefix}/include/pcl-1.12
Name: pcl_io
Description: Point cloud IO library
Version: 1.12.0
Requires:  eigen3  pcl_common-1.12 pcl_octree-1.12
Libs: -lKinect10 -lOpenNI2-L${libdir} -lpcl_io  
Cflags: -I"${includedir}" 
```

**Comment by JackBoosY** [comment]
Ah missing a space.

**Comment by JackBoosY** [comment]
Please pull my latest changes and try again.

**Comment by LOVELESSYI** [comment]
> Please pull my latest changes and try again.

Hello. After rebuilding, I still got the same error. Here's the new "pcl_io-1.12.pc". I can see a space has been added behind  "-lOpenNI2"
```
prefix=${pcfiledir}/../..
# This file was generated by CMake for PCL library pcl_io
exec_prefix=${prefix}
libdir=${prefix}/lib
#includedir=${prefix}/include/pcl
includedir=${prefix}/include/pcl-1.12
Name: pcl_io
Description: Point cloud IO library
Version: 1.12.0
Requires:  eigen3  pcl_common-1.12 pcl_octree-1.12
Libs: -lKinect10 -lOpenNI2 -L"${libdir}" -lpcl_io  
Cflags: -I"${includedir}" 
```

**Comment by LOVELESSYI** [comment]
And there is no file named "libopenni2.pc" in "C:\vcpkg"

**Comment by JackBoosY** [comment]
@LOVELESSYI Please provide the output.

**Comment by LOVELESSYI** [comment]
> @LOVELESSYI Please provide the output.

`.\vcpkg.exe install pcl[cuda,opengl,openni2,pcap,qt,tools,vtk]:x64-windows`
```
Computing installation plan...
The following packages will be built and installed:
    pcl[core,cuda,opengl,openni2,pcap,qt,tools,vtk]:x64-windows -> 1.12.0#1
Detecting compiler hash for triplet x64-windows...
Restored 0 packages from C:\Users\89785\AppData\Local\vcpkg\archives in 1.718 ms. Use --debug to see more details.
Starting package 1/1: pcl:x64-windows
Building package pcl[core,cuda,opengl,openni2,pcap,qt,tools,vtk]:x64-windows...
-- Using cached PointCloudLibrary-pcl-f36a69a5e89953708990c4669317f989d532cf08.tar.gz.
-- Cleaning sources at C:/vcpkg/buildtrees/pcl/src/89d532cf08-56497bbdf2.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg/downloads/PointCloudLibrary-pcl-f36a69a5e89953708990c4669317f989d532cf08.tar.gz
-- Applying patch add-gcc-version-check.patch
-- Applying patch fix-check-sse.patch
-- Applying patch fix-find-qhull.patch
-- Applying patch fix-numeric-literals-flag.patch
-- Applying patch pcl_config.patch
-- Applying patch pcl_utils.patch
-- Applying patch remove-broken-targets.patch
-- Applying patch fix-cmake_find_library_suffixes.patch
-- Applying patch fix-pkgconfig.patch
-- Applying patch fix-find-libusb.patch
-- Using source at C:/vcpkg/buildtrees/pcl/src/89d532cf08-56497bbdf2.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_2d-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_common-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_cuda_common-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_cuda_features-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_cuda_sample_consensus-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_cuda_segmentation-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_features-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_filters-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_geometry-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_gpu_containers-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_gpu_features-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_gpu_octree-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_gpu_segmentation-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_gpu_utils-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_io-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_kdtree-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_keypoints-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_ml-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_octree-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_outofcore-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_people-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_recognition-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_registration-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_sample_consensus-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_search-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_segmentation-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_stereo-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_surface-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_tracking-1.12.pc
-- Fixing pkgconfig file: C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig/pcl_visualization-1.12.pc
-- Using cached msys-mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst.
-- Using msys root at C:/vcpkg/downloads/tools/msys2/aa5af7b2aa7e90e8
CMake Error at scripts/cmake/vcpkg_fixup_pkgconfig.cmake:78 (message):
  C:/vcpkg/downloads/tools/msys2/aa5af7b2aa7e90e8/mingw32/bin/pkg-config.exe
  --exists pcl_outofcore-1.12 failed with error code: 1

      ENV{PKG_CONFIG_PATH}: "C:/vcpkg/packages/pcl_x64-windows/lib/pkgconfig;C:/vcpkg/packages/pcl_x64-windows/share/pkgconfig;C:/vcpkg/installed/x64-windows/lib/pkgconfig;C:/vcpkg/installed/x64-windows/share/pkgconfig"
      output: Package libopenni2 was not found in the pkg-config search path.

  Perhaps you should add the directory containing `libopenni2.pc'

  to the PKG_CONFIG_PATH environment variable

  Package 'libopenni2', required by 'pcl_visualization-1.12', not found
Call Stack (most recent call first):
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:201 (z_vcpkg_fixup_pkgconfig_check_files)
  ports/pcl/portfile.cmake:84 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:142 (include)


Error: Building package pcl:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  package: pcl[core,cuda,opengl,openni2,pcap,qt,tools,vtk]:x64-windows -> 1.12.0#1
  vcpkg version: 2021-11-02-af04ebf6274fd6f7a941bff4662b3955c64f6f42
  vcpkg-tool version: e1a5fb9f0 2021-11-11 (47 minutes ago)

Additionally, attach any relevant sections from the log files above.
```

**Comment by JackBoosY** [comment]
@LOVELESSYI  Please test again.

**Comment by LOVELESSYI** [comment]
> @LOVELESSYI Please test again.

Thank you very much!
With branch `dev/jack/21223-21241`, I successfully install PCL and show pcd file by using `pcl/visualization/cloud_viewer.h` which was lost in previous vcpkg. But I got some small mistakes, I fixed them by myself and I think mayebe you need to know about this.
While using `pcl/visualization/cloud_viewer.h` in VS2019, I got many errors like `can't open file vtkxxxx.h`. I looked for the include file and found that the correct way is `#include <vtk-9.0/vtkxxxx.h>`. After I change all `#include <vtkxxxx.h>` to `#include <vtk-9.0/vtkxxxx.h>` in files in `C:\vcpkg\installed\x64-windows\include\pcl`, I successfully run my code.
