### ISSUE TITLE
Why I need to install Python

### ISSUE THREAD

**Issue by kylinholmes** [microsoft/vcpkg#21295]
I have already installed Python3.8,
![image](https://user-images.githubusercontent.com/45586871/141051280-073cecb0-ec9e-4751-9f61-6ea672ece140.png)

Why it need to download another python3.10 while I trying to install `glad`

![image](https://user-images.githubusercontent.com/45586871/141051074-b95948e8-1143-4e49-a9da-ae452d2e7192.png)

And if there is another way to install it without python3.10?

**Comment by JackBoosY** [comment]
@kylinholmes  Maybe your python path is not added to the system environment `PATH`, so vcpkg can't find it from your system.

**Comment by kylinholmes** [comment]
@JackBoosY I looked my path, and python.exe just in it

**Comment by kylinholmes** [comment]
@JackBoosY It worked somehow.
