### ISSUE TITLE
libjpeg-turbo:x64-osx

### ISSUE THREAD

**Issue by NSLahore** [microsoft/vcpkg#21300]
Error: Building package libjpeg-turbo:x64-osx failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libjpeg-turbo:x64-osx
  Vcpkg version: 2021-05-05-unknownhash

**Comment by NSLahore** [comment]
@JonLiu1993 Can you figure this out I am getting error on this build while installing vcpkg in IntelliJ IDEA.

**Comment by JonLiu1993** [comment]
@NSLahore ,Could you please provide your error log?

**Comment by NSLahore** [comment]
@JonLiu1993
  CMake Error at scripts/cmake/vcpkg_find_acquire_program.cmake:535 (message):
  Could not find pkg-config.  Please install it via your package manager:

      brew install pkg-config
Call Stack (most recent call first):
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:112 (vcpkg_find_acquire_program)
  ports/libjpeg-turbo/portfile.cmake:80 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:142 (include)


Error: Building package libjpeg-turbo:x64-osx failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libjpeg-turbo:x64-osx
  Vcpkg version: 2021-05-05-unknownhash

**Comment by JonLiu1993** [comment]
@NSLahore ,Please use "brew install pkg-config" install  pkg-config first
