### ISSUE TITLE
SDL2-mixer [x64-windows] with ["dynamic-load", "libvorbis", "mpg123"] not copying DLLs into build folder

### ISSUE THREAD

**Issue by obscurelyme** [microsoft/vcpkg#21313]
SDL2-mixer, I just cleaned out my configuration and reran cmake configure only to find that on windows SDL2-mixer isn't copying over the dependency DLLs into the build folder like it used to. If you remove the "dynamic-load" feature then both "libvorbis" and "mpg123" are copied over. Idk if that's intended or not, but it's seems unintuitive considering how Windows builds everything to be linked dynamically rather than statically as opposed to OSX and Linux. 

**Environment**
- OS: Windows 10

**To Reproduce**
1. Clone basic sample [repo](https://github.com/obscurelyme/sdl-mixer)
2.  cmake configure from cmake tools in VS Code
3. cmake build from VS Code

**Expected behavior**
ogg.dll, mpg123.dll, vorbis.dll, vorbisfile.dll should be copied into the executable's directory

**Additional context**
Only by removing "dynamic-load" as a feature from sdl-mixer in vcpkg.json do the DLLs get copied over.

**Comment by JackBoosY** [comment]
That's expected.
vcpkg analyzes dependencies by calling `dumpbin`, but if dynamic-load is enabled, dumpbin will not be able to get them.

**Comment by obscurelyme** [comment]
So if "dynamic-load" is specified, would that mean the user is meant to manually include any additional dependencies in their CMakeLists.txt?

**Comment by JackBoosY** [comment]
@obscurelyme Yes, vcpkg will build the dependencies but won't install them into the same dir.

**Comment by obscurelyme** [comment]
Sounds good. I'll go ahead and close.
