### ISSUE TITLE
[GTK ] build failure

### ISSUE THREAD

**Issue by affonsoelias** [microsoft/vcpkg#21312]
**Host Environment**
- OS: Windows 7
- Compiler:  19.27.29117  x86
- vcpkg version: 2021-11-02-af04ebf6274fd6f7a941bff4662b3955c64f6f42
- vcpkg-tool version: 66c39e113 2021-11-05 (5 days ago)

**To Reproduce**
`./vcpkg install gtk`

**Failure logs** 
```
.\vcpkg install gtk
Computing installation plan...
The following packages will be built and installed:
  * atk[core]:x86-windows -> 2.36.0#1
  * brotli[core]:x86-windows -> 1.0.9#2
  * bzip2[core]:x86-windows -> 1.0.8#2
  * cairo[core,fontconfig,freetype,gobject]:x86-windows -> 1.17.4#2
  * dirent[core]:x86-windows -> 1.23.2#1
  * fontconfig[core]:x86-windows -> 2.13.94
  * freetype[brotli,bzip2,core,png,zlib]:x86-windows -> 2.11.0#2
  * fribidi[core]:x86-windows -> 1.0.11
  * gdk-pixbuf[core]:x86-windows -> 2.42.2#1
  * getopt[core]:x86-windows -> 0#1
  * getopt-win32[core]:x86-windows -> 0.1#1
  * glib[core]:x64-windows -> 2.66.4
  * glib[core]:x86-windows -> 2.66.4
  * graphene[core]:x86-windows -> 1.10.2#1
    gtk[core]:x86-windows -> 4.3.0
  * harfbuzz[core]:x86-windows -> 3.0.0
  * json-c[core]:x86-windows -> 2019-09-10#2
  * libepoxy[core]:x86-windows -> 1.5.5#1
  * libffi[core]:x86-windows -> 3.4.2#2
  * libjpeg-turbo[core]:x86-windows -> 2.0.6#2
  * liblzma[core]:x86-windows -> 5.2.5#4
  * libpng[core]:x86-windows -> 1.6.37#15
  * libsass[core]:x86-windows -> 3.6.5
  * lzo[core]:x86-windows -> 2.10#7
  * pango[core]:x86-windows -> 1.48.4#1
  * pcre[core]:x86-windows -> 8.45
  * pcre[core]:x64-windows -> 8.45
  * pixman[core]:x86-windows -> 0.40.0
  * pthread[core]:x86-windows -> 3.0.0#1
  * pthreads[core]:x86-windows -> 3.0.0#10
  * sassc[core]:x86-windows -> 3.6.2
  * tiff[core,jpeg,lzma,zip]:x86-windows -> 4.3.0#2
  * tool-meson[core]:x64-windows -> 0.58.1
  * tool-meson[core]:x86-windows -> 0.58.1
  * zlib[core]:x64-windows -> 1.2.11#13
  * zlib[core]:x86-windows -> 1.2.11#13
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Detecting compiler hash for triplet x86-windows...
Restored 0 packages from C:\Users\affonso\AppData\Local\vcpkg\archives in 792.8 ms. Use --debug to see more details.
Starting package 1/36: pcre:x64-windows
Building package pcre[core]:x64-windows...
CMake Warning at scripts/cmake/vcpkg_download_distfile.cmake:170 (message):
  SILENT_EXIT has been deprecated as an argument to vcpkg_download_distfile
  -- remove the argument to resolve this warning
Call Stack (most recent call first):
  ports/pcre/portfile.cmake:12 (vcpkg_download_distfile)
  scripts/ports.cmake:142 (include)


-- Downloading https://ftp.pcre.org/pub/pcre/pcre-8.45.zip -> pcre-8.45.zip...
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' = off
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Downloading https://ftp.pcre.org/pub/pcre/pcre-8.45.zip
[DEBUG] Download failed -- retrying after 1000 ms.
[DEBUG] Download failed -- retrying after 2000 ms.
[DEBUG] Download failed -- retrying after 4000 ms.
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(656)
Error: Failed to download from mirror set:
https://ftp.pcre.org/pub/pcre/pcre-8.45.zip: WinHttpSendRequest() failed: 12002
https://ftp.pcre.org/pub/pcre/pcre-8.45.zip: WinHttpSendRequest() failed: 12002
https://ftp.pcre.org/pub/pcre/pcre-8.45.zip: WinHttpSendRequest() failed: 12002
https://ftp.pcre.org/pub/pcre/pcre-8.45.zip: WinHttpSendRequest() failed: 12002

[DEBUG] Exiting after %s (%d us)


CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:84 (message):

      Failed to download file with error: 1
      If you use a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.

      3. You proxy's remote server is out of service.

      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)

      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:292 (z_vcpkg_download_distfile_show_proxy_and_fail)
  ports/pcre/portfile.cmake:12 (vcpkg_download_distfile)
  scripts/ports.cmake:142 (include)

Error: Building package pcre:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  package: pcre[core]:x64-windows -> 8.45
  vcpkg version: 2021-11-02-af04ebf6274fd6f7a941bff4662b3955c64f6f42
  vcpkg-tool version: 66c39e113 2021-11-05 (5 days ago)

Additionally, attach any relevant sections from the log files above.
```
**Additional context**

the website https://pcre.org/ says the following:

You can check out the PCRE2 source code via Git or Subversion: git clone https://github.com/PhilipHazel/pcre2.git

Note that the former ftp.pcre.org FTP site is no longer available. You will need to update any scripts that download PCRE source code to download via HTTPS, Git, or Subversion from the new home on GitHub instead.

**Comment by JackBoosY** [comment]
It seems the ftp server is down. We'd prefer to wait for some days.
For workaround, please download [this file](https://github.com/microsoft/vcpkg/files/7518187/pcre-8.45.zip) and put it into _VCPKG_ROOT/downloads_ then try again.

> You can check out the PCRE2 source code via Git or Subversion: git clone https://github.com/PhilipHazel/pcre2.git

No, that's pcre2 repo and we already have it named `pcre2`.

**Comment by Neumann-A** [comment]
Has PCRE2 the same API as PCRE? Maybe we can just replace the dependencies.

Also the pcre2 github says:

> As well as downloading from the GitHub site, you can download PCRE2 or the older, unmaintained PCRE1 library from an unofficial mirror at SourceForge.

note the word "unofficial" here

**Comment by affonsoelias** [comment]
I put the PCRE2 package as @JackBoosY directed. In C:\vcpkg\downloads. it worked but I got another error

.\vcpkg install gtk
Computing installation plan...
The following packages will be built and installed:
  * atk[core]:x86-windows -> 2.36.0#1
  * brotli[core]:x86-windows -> 1.0.9#2
  * bzip2[core]:x86-windows -> 1.0.8#2
  * cairo[core,fontconfig,freetype,gobject]:x86-windows -> 1.17.4#2
  * dirent[core]:x86-windows -> 1.23.2#1
  * fontconfig[core]:x86-windows -> 2.13.94
  * freetype[brotli,bzip2,core,png,zlib]:x86-windows -> 2.11.0#2
  * fribidi[core]:x86-windows -> 1.0.11
  * gdk-pixbuf[core]:x86-windows -> 2.42.2#1
  * getopt[core]:x86-windows -> 0#1
  * getopt-win32[core]:x86-windows -> 0.1#1
  * glib[core]:x64-windows -> 2.66.4
  * glib[core]:x86-windows -> 2.66.4
  * graphene[core]:x86-windows -> 1.10.2#1
    gtk[core]:x86-windows -> 4.3.0
  * harfbuzz[core]:x86-windows -> 3.0.0
  * json-c[core]:x86-windows -> 2019-09-10#2
  * libepoxy[core]:x86-windows -> 1.5.5#1
  * libffi[core]:x86-windows -> 3.4.2#2
  * libjpeg-turbo[core]:x86-windows -> 2.0.6#2
  * liblzma[core]:x86-windows -> 5.2.5#4
  * libpng[core]:x86-windows -> 1.6.37#15
  * libsass[core]:x86-windows -> 3.6.5
  * lzo[core]:x86-windows -> 2.10#7
  * pango[core]:x86-windows -> 1.48.4#1
  * pcre[core]:x86-windows -> 8.45
  * pixman[core]:x86-windows -> 0.40.0
  * pthread[core]:x86-windows -> 3.0.0#1
  * pthreads[core]:x86-windows -> 3.0.0#10
  * sassc[core]:x86-windows -> 3.6.2
  * tiff[core,jpeg,lzma,zip]:x86-windows -> 4.3.0#2
  * tool-meson[core]:x86-windows -> 0.58.1
  * zlib[core]:x86-windows -> 1.2.11#13
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Detecting compiler hash for triplet x86-windows...
Restored 0 packages from C:\Users\affonso\AppData\Local\vcpkg\archives in 1.635 ms. Use --debug to see more details.
Starting package 1/33: glib:x64-windows
Building package glib[core]:x64-windows...
-- Using cached glib-2.66.4.tar.xz.
-- Cleaning sources at C:/vcpkg/buildtrees/glib/src/glib-2-b84205c786.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg/downloads/glib-2.66.4.tar.xz
-- Applying patch use-libiconv-on-windows.patch
-- Applying patch fix-libintl-detection.patch
-- Using source at C:/vcpkg/buildtrees/glib/src/glib-2-b84205c786.clean
-- Found external ninja('1.10.2').
-- Getting CMake variables for x64-windows
-- Using cached msys-mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst.
-- Using msys root at C:/vcpkg/downloads/tools/msys2/aa5af7b2aa7e90e8
-- Configuring x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: C:/vcpkg/downloads/tools/python/python-3.10.0-x64/python.exe C:/vcpkg/downloads/tools/meson/meson-aeda7f249c4a5dbbecc52e44f382246a2377b5b0/meson.py -Dbuild_tests=false -Dinstalled_tests=false -Dselinux=disabled -Diconv=external -Dinternal_pcre=false --buildtype plain --backend ninja --wrap-mode nodownload --native C:/vcpkg/buildtrees/glib/meson-nativ-x64-windows.log --default-library shared --libdir lib --native C:/vcpkg/buildtrees/glib/meson-nativ-x64-windows-debug.log -Ddebug=true --prefix C:/vcpkg/packages/glib_x64-windows/debug --includedir ../include -Dcmake_prefix_path=['C:/vcpkg/installed/x64-windows/debug','C:/vcpkg/installed/x64-windows','C:/vcpkg/installed/x64-windows/share'] C:/vcpkg/buildtrees/glib/src/glib-2-b84205c786.clean
    Working Directory: C:/vcpkg/buildtrees/glib/x64-windows-dbg
    Error code: Exit code 0xc0000135



    See logs for more information:

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_meson.cmake:512 (vcpkg_execute_required_process)
  ports/glib/portfile.cmake:42 (vcpkg_configure_meson)
  scripts/ports.cmake:142 (include)


[GTK.zip](https://github.com/microsoft/vcpkg/files/7524051/GTK.zip)

**Comment by JackBoosY** [comment]
```
    Command failed: C:/vcpkg/downloads/tools/python/python-3.10.0-x64/python.exe C:/vcpkg/downloads/tools/meson/meson-aeda7f249c4a5dbbecc52e44f382246a2377b5b0/meson.py -Dbuild_tests=false -Dinstalled_tests=false -Dselinux=disabled -Diconv=external -Dinternal_pcre=false --buildtype plain --backend ninja --wrap-mode nodownload --native C:/vcpkg/buildtrees/glib/meson-nativ-x64-windows.log --default-library shared --libdir lib --native C:/vcpkg/buildtrees/glib/meson-nativ-x64-windows-debug.log -Ddebug=true --prefix C:/vcpkg/packages/glib_x64-windows/debug --includedir ../include -Dcmake_prefix_path=['C:/vcpkg/installed/x64-windows/debug','C:/vcpkg/installed/x64-windows','C:/vcpkg/installed/x64-windows/share'] C:/vcpkg/buildtrees/glib/src/glib-2-b84205c786.clean
    Working Directory: C:/vcpkg/buildtrees/glib/x64-windows-dbg
    Error code: Exit code 0xc0000135
```
Please delete folder _C:/vcpkg/downloads/tools/python_ and try again.
That because python.exe dependencies are missing.

**Comment by affonsoelias** [comment]
**Delete the folder C:/vcpkg/downloads/tools/python and tried again**

.\vcpkg install gtk
Computing installation plan...
The following packages will be built and installed:
  * atk[core]:x86-windows -> 2.36.0#1
  * brotli[core]:x86-windows -> 1.0.9#2
  * bzip2[core]:x86-windows -> 1.0.8#2
  * cairo[core,fontconfig,freetype,gobject]:x86-windows -> 1.17.4#2
  * fontconfig[core]:x86-windows -> 2.13.94
  * freetype[brotli,bzip2,core,png,zlib]:x86-windows -> 2.11.0#2
  * fribidi[core]:x86-windows -> 1.0.11
  * gdk-pixbuf[core]:x86-windows -> 2.42.2#1
  * getopt[core]:x86-windows -> 0#1
  * getopt-win32[core]:x86-windows -> 0.1#1
  * glib[core]:x64-windows -> 2.66.4
  * glib[core]:x86-windows -> 2.66.4
  * graphene[core]:x86-windows -> 1.10.2#1
    gtk[core]:x86-windows -> 4.3.0
  * harfbuzz[core]:x86-windows -> 3.0.0
  * json-c[core]:x86-windows -> 2019-09-10#2
  * libepoxy[core]:x86-windows -> 1.5.5#1
  * libjpeg-turbo[core]:x86-windows -> 2.0.6#2
  * liblzma[core]:x86-windows -> 5.2.5#4
  * libpng[core]:x86-windows -> 1.6.37#15
  * libsass[core]:x86-windows -> 3.6.5
  * lzo[core]:x86-windows -> 2.10#7
  * pango[core]:x86-windows -> 1.48.4#1
  * pixman[core]:x86-windows -> 0.40.0
  * pthread[core]:x86-windows -> 3.0.0#1
  * pthreads[core]:x86-windows -> 3.0.0#10
  * sassc[core]:x86-windows -> 3.6.2
  * tiff[core,jpeg,lzma,zip]:x86-windows -> 4.3.0#2
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Detecting compiler hash for triplet x86-windows...
Restored 0 packages from C:\Users\affonso\AppData\Local\vcpkg\archives in 77.12 ms. Use --debug to see more details.
Starting package 1/28: glib:x64-windows
Building package glib[core]:x64-windows...
-- Using cached glib-2.66.4.tar.xz.
-- Cleaning sources at C:/vcpkg/buildtrees/glib/src/glib-2-b84205c786.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg/downloads/glib-2.66.4.tar.xz
-- Applying patch use-libiconv-on-windows.patch
-- Applying patch fix-libintl-detection.patch
-- Using source at C:/vcpkg/buildtrees/glib/src/glib-2-b84205c786.clean
-- Found external ninja('1.10.2').
-- Getting CMake variables for x64-windows
-- Using cached python-3.10.0-embed-amd64.zip.
-- Using cached msys-mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst.
-- Using msys root at C:/vcpkg/downloads/tools/msys2/aa5af7b2aa7e90e8
-- Configuring x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: C:/vcpkg/downloads/tools/python/python-3.10.0-x64/python.exe C:/vcpkg/downloads/tools/meson/meson-aeda7f249c4a5dbbecc52e44f382246a2377b5b0/meson.py -Dbuild_tests=false -Dinstalled_tests=false -Dselinux=disabled -Diconv=external -Dinternal_pcre=false --buildtype plain --backend ninja --wrap-mode nodownload --native C:/vcpkg/buildtrees/glib/meson-nativ-x64-windows.log --default-library shared --libdir lib --native C:/vcpkg/buildtrees/glib/meson-nativ-x64-windows-debug.log -Ddebug=true --prefix C:/vcpkg/packages/glib_x64-windows/debug --includedir ../include -Dcmake_prefix_path=['C:/vcpkg/installed/x64-windows/debug','C:/vcpkg/installed/x64-windows','C:/vcpkg/installed/x64-windows/share'] C:/vcpkg/buildtrees/glib/src/glib-2-b84205c786.clean
    Working Directory: C:/vcpkg/buildtrees/glib/x64-windows-dbg
    Error code: Exit code 0xc0000135



    See logs for more information:

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_meson.cmake:512 (vcpkg_execute_required_process)
  ports/glib/portfile.cmake:42 (vcpkg_configure_meson)
  scripts/ports.cmake:142 (include)


Error: Building package glib:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  package: glib[core]:x64-windows -> 2.66.4
  vcpkg version: 2021-11-02-af04ebf6274fd6f7a941bff4662b3955c64f6f42
  vcpkg-tool version: 66c39e113 2021-11-05 (7 days ago)

Additionally, attach any relevant sections from the log files above.

**But the error continues. 

I'm using windows 7. I can only install python up to version 3.8. And vcpkg is using version 3.10. I don't know if this has a problem. or relevance**

**Comment by JackBoosY** [comment]
The pcre part was resolved, and for the python part, please track https://github.com/microsoft/vcpkg/issues/21312.
