### ISSUE TITLE
[GDAL] Build failure: "not a git repository"

### ISSUE THREAD

**Issue by gvanem** [microsoft/vcpkg#21325]
**Host Environment**
- OS: Windows-10
- Compiler: MSVC-2019. 19.29.30136 for x86

**To Reproduce**

`vcpkg.exe install gdal:x86-windows --debug`

**Failure logs** 
```
[DEBUG] Using vcpkg-root: F:\gv\VC_project\VCPKG
...
Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_nmake.cmake:187 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_nmake.cmake:115 (vcpkg_build_nmake)
  ports/gdal/portfile.cmake:131 (vcpkg_install_nmake)
  scripts/ports.cmake:142 (include)

[DEBUG] cmd_execute_and_stream_data() returned 1 after 106744394 us
Error: Building package gdal:x86-windows failed with: BUILD_FAILED
[DEBUG] CreateProcessW("F:\gv\VC_project\VCPKG\downloads\tools\git-2.32.0.2-windows\mingw32\bin\git.exe" 
"--git-dir=F:\gv\VC_project\VCPKG\.git" "--work-tree=F:\gv\VC_project\VCPKG\.git" -c core.autocrlf=false show 
"--pretty=format:%h %cd (%cr)" -s --date=short HEAD)
[DEBUG] cmd_execute_and_stream_data() returned 128 after    91482 us
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  package: gdal[core]:x86-windows -> 3.3.2#4
  vcpkg version: Failed to get HEAD: fatal: not a git repository: 'F:\gv\VC_project\VCPKG\.git'
  vcpkg-tool version: 2021-11-11-2021-11-02-14-g8ad39733

Additionally, attach any relevant sections from the log files above.
[DEBUG] vcpkg/install.cpp(498)
[DEBUG] Exiting after %s (%d us)
```

**Additional context**

The gist of the error is `Failed to get HEAD: fatal: not a git repository: 'F:\gv\VC_project\VCPKG\.git'`. 
True, my `VCPKG_ROOT` != the *Git-checkout root*. I fails to see why a `git show HEAD` (?) is important to build Gdal.
I've built *many* packages with `vcpkg install ..`, but I've never seen such an error.

Seems to come from `vcpkg-tool/src/vcpkg/vcpkgpaths.cpp` and `Command VcpkgPaths::git_cmd_builder()`.
But why?

**Comment by dg0yt** [comment]
> I fails to see why a `git show HEAD` (?) is important to build Gdal.

It isn't. The git call is an attempt to provide the repo version for the error reporting hint:

> ~~~
> Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`, then
> submit an issue at https://github.com/Microsoft/vcpkg/issues including:
>   package: gdal[core]:x86-windows -> 3.3.2#4
>   vcpkg version: Failed to get HEAD: fatal: not a git repository: 'F:\gv\VC_project\VCPKG\.git'
>   vcpkg-tool version: 2021-11-11-2021-11-02-14-g8ad39733

Now please provide the revision in another way, provide the actual error message, and attach the log files mentioned in the error message.

**Comment by gvanem** [comment]
> Now please provide the revision in another way, provide the actual error message, and attach the log files mentioned in 
> the error message.

A `vcpkg version` gives:
`Vcpkg package management program version 2021-11-11-g8ad39733`.

The error log-file `buildtrees\gdal\install-x86-windows-dbg-err.log` simply says:
```
NMAKE : fatal error U1081: 'C:\Windows\sysnative\cmd.exe' : program not found
Stop.
NMAKE : fatal error U1077: 'f:\gv\vc_2019\VC\Tools\MSVC\14.29.30133\bin\HostX64\x86\nmake.EXE' : return code '0x2'
Stop.
```

Strange since `C:\Windows\sysnative\cmd.exe` does exist. But since the above `nmake.EXE` is for `x64`, maybe that's the cause.

**Comment by dg0yt** [comment]
> Strange since `C:\Windows\sysnative\cmd.exe` does exist.

It does exist when you run in the x86 subsystem of an x64 host. `sysnative` points back into the x64 environment ("native"). Illustration from an x64 command prompt:
~~~
dir C:\Windows\sysnative\xcopy.exe | find "xcopy"
dir C:\Windows\System32\xcopy.exe | find "xcopy"
dir C:\Windows\SysWOW64\xcopy.exe | find "xcopy"
C:\Windows\SysWOW64\cmd.exe /C "dir C:\windows\sysnative\xcopy.exe" | find "xcopy"
~~~

**Comment by dg0yt** [comment]
> A `vcpkg version` gives:
> `Vcpkg package management program version 2021-11-11-g8ad39733`.

The vcpkg tool version was reported by the tool. I was asking for the revision of the vcpkg data. You didn't use a vcpkg git checkout. But you should know where you got your reposititory from.

**Comment by gvanem** [comment]
> You didn't use a vcpkg git checkout.

I sure did. But you're saying we cannot build `vcpkg.exe` from a downloaded .ZIP?

Anyway, in the git checkout of `vcpkg-tool`:  `git show -s --date=short HEAD`:
```
commit 8ad3973372b37a7a54bff71a4a09985e0bd15d92 (HEAD -> main, origin/main, origin/HEAD)
Author: Przemyslaw Ciezkowski <pc.pc3t@gmail.com>
Date:   2021-11-10
```

And in the git checkout of `vcpkg-root`:  `git show -s --date=short HEAD`:
```
commit 86b23850c376428633e8690b6983028da0c93683 (HEAD -> master, origin/master, origin/HEAD)
Author: nicole mazzuca <83086508+strega-nil-ms@users.noreply.github.com>
Date:   2021-11-10
```

**Comment by dg0yt** [comment]
> > You didn't use a vcpkg git checkout.
> 
> I sure did.

Thanks for the clarification. So in the initial report, `git` failed despite running  on a git checkout.

> But you're saying we cannot build `vcpkg.exe` from a downloaded .ZIP?

I'm not saying that anywhere.

> Anyway, in the git checkout of `vcpkg-tool`: `git show -s --date=short HEAD`:
> 
> ```
> commit 8ad3973372b37a7a54bff71a4a09985e0bd15d92 (HEAD -> main, origin/main, origin/HEAD)
> Author: Przemyslaw Ciezkowski <pc.pc3t@gmail.com>
> Date:   2021-11-10
> ```

The tool's revision was in the initial post, and repeated in another post.

> And in the git checkout of `vcpkg-root`: `git show -s --date=short HEAD`:
> 
> ```
> commit 86b23850c376428633e8690b6983028da0c93683 (HEAD -> master, origin/master, origin/HEAD)
> Author: nicole mazzuca <83086508+strega-nil-ms@users.noreply.github.com>
> Date:   2021-11-10
> ```

*This* is what I was asking for. But probably the actual revision doesn't matter, given the context.

I can't remember having seen a `sysnative` problem before. Do you build from an x86 command prompt on x64? I wonder if both the gdal build *and* `git` might stumble over that. I can't help with VS particularities.

**Comment by gvanem** [comment]
> Do you build from an x86 command prompt on x64? 

Yes.

**Comment by gvanem** [comment]
I ended up creating this `vcpkg.bat` (on my `%PATH` ahead of `vcpkg.exe`):

```bat
@setlocal
@set COMSPEC=c:\Windows\System32\cmd.exe
@%COMSPEC% /C %~dp0vcpkg.exe %$
```

This builds GDAL okay for both architectures:
 * `vcpkg.exe install gdal:x86-windows`
 * `vcpkg.exe install gdal:x64-windows`

**Comment by dg0yt** [comment]
Why don't you simply start from a native command prompt?

And maybe there is indeed some bug in when running x86 vcpkg on x64...

**Comment by gvanem** [comment]
> Why don't you simply start from a native command prompt?

Implying CMD? Yuk! Pile of shit program. Never use it unless situations like the above.
