### ISSUE TITLE
[New Port Request]  AMGCL

### ISSUE THREAD

**Issue by xarthurx** [microsoft/vcpkg#21332]
**Library name:**
AMGCL

**Library description:**
AMGCL is a header-only C++ library for solving large sparse linear systems with algebraic multigrid (AMG) method. AMG is one of the most effective iterative methods for solution of equation systems arising, for example, from discretizing PDEs on unstructured grids. The method can be used as a black-box solver for various computational problems, since it does not require any information about the underlying geometry. AMG is often used not as a standalone solver but as a preconditioner within an iterative solver (e.g. Conjugate Gradients, BiCGStab, or GMRES).

AMGCL builds the AMG hierarchy on a CPU and then transfers it to one of the provided backends. This allows for transparent acceleration of the solution phase with help of OpenCL, CUDA, or OpenMP technologies. Users may provide their own backends which enables tight integration between AMGCL and the user code.

**Source repository URL:**
https://github.com/ddemidov/amgcl

**Project homepage (if different from the source repository):**
https://amgcl.readthedocs.io/en/latest/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
No.

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
