### ISSUE TITLE
Deal with Emscripten SDK older version (Example :  Version sdk-fastcomp-1.38.11-64bit)

### ISSUE THREAD

**Issue by JeanPhilippeKernel** [microsoft/vcpkg#21338]
****
 VCPKG fails to install Emscripten SDK older version (older than 2.0.32).
it does the right thing when is about to consume a newer version as it fetches CMake module from the `upstream/cmake/Module/Platform` directory.

but older versions use differents directories, for an example `sdk-fastcomp-1.38.11-64bit` uses `emscripten/1.38.11 ` .
That ones cause VCKPG to find and install CMake module...

**Is your feature request related to a problem? Please describe.**

**Proposed solution**

**Describe alternatives you've considered**

**Additional context**

**Comment by JackBoosY** [comment]
Can you provide a reproduce step?

Thanks.

**Comment by JackBoosY** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
