### ISSUE TITLE
[New Port Request] Cinder

### ISSUE THREAD

**Issue by maziarmzh** [microsoft/vcpkg#21333]
Library name: Cinder

Library description: Cinder is a peer-reviewed, free, open source C++ library for creative coding.

Source repository URL: https://github.com/cinder/Cinder

Project homepage (if different from the source repository): https://libcinder.org/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
