### ISSUE TITLE
[sdl2-image]  JPEG and WEBP features do not work on Linux

### ISSUE THREAD

**Issue by kogiokka** [microsoft/vcpkg#21331]
**Describe the bug**
SDL reports error when loading .jpg and .webp images. Both `sdl2-image[libjpeg-turbo]` and `sdl2-image[libwebp]` are installed.

**Environment**
- OS: Linux (Fedora 33)
- Compiler: GCC version 10.3.1 20210422

**To Reproduce**
1. `./vcpkg install sdl2 'sdl2-image[core,libjpeg-turbo,libwebp]'`
2. Compile and run the attached project: [SDL_image_vcpkg_bug_report.zip](https://github.com/microsoft/vcpkg/files/7521000/SDL_image_vcpkg_bug_report.zip)
3. SDL reports "`JPEG loading error`" when loading a JPEG image, and "`Failed loading libwebp-4.dll: libwebp-4.dll: cannot open shared object file: No such file or directory`" when loading a WEBP image.

**Expected behavior**

SDL should be able to load JPEG and WEBP images on Linux after `libjpeg-turbo` and `libwebp` features are installed. The same project has been tested on Windows without any issue occurring.

**Failure logs** 
N/A

**Additional context**
N/A

**Comment by JackBoosY** [comment]
`Failed loading libwebp-4.dll: libwebp-4.dll: cannot open shared object file: No such file or directory`
In Linux triplet, weird.

**Comment by JackBoosY** [comment]
Caused by https://github.com/microsoft/vcpkg/blob/897ff9372f15c032f1e6cd1b97a59b57d66ee5b2/ports/sdl2-image/CMakeLists.txt#L22-L26

**Comment by kogiokka** [comment]
> Caused by
> 
> https://github.com/microsoft/vcpkg/blob/897ff9372f15c032f1e6cd1b97a59b57d66ee5b2/ports/sdl2-image/CMakeLists.txt#L22-L26

I can confirm TIFF images have the same issue. PNG has no issues on Linux, however.

It seems that these features won't work on macOS, either.
