### ISSUE TITLE
[qt] build failure

### ISSUE THREAD

**Issue by jparr721** [microsoft/vcpkg#21340]
**Host Environment**
- OS: Windows
- Compiler: MSVC 2019 (Latest)

**To Reproduce**
`./vcpkg install qt:x64-windows`

**Failure logs** 
```
$ ./vcpkg install qt:x64-windows
Computing installation plan...
Error: while loading qt:
The port directory (C:\Users\jparr\Documents\vcpkg\ports\qt) does not exist
Error: failed to load port from C:\Users\jparr\Documents\vcpkg\ports\qt
Note: Updating vcpkg by rerunning bootstrap-vcpkg may resolve this failure.
```

**Additional context**
I updated vcpkg by re-runnng the bootstrap script and saw no change. I tried manually adding the port folder and the items from the ports directory in this repository, this led to other errors.

I can install other packages fine, even qt5 was able to work, so I'm not sure what I'm doing wrong here. I have tried looking around for this error message but haven't seen anyone with this problem before, if there's a solution somewhere, please let me know. Thanks!

**Comment by jparr721** [comment]
Out of frustration I deleted and re-added vcpkg to my computer and the error went away. I suspect this is due to vcpkg getting to a new version and getting the port folder. However, I am curious as to why when manually adding it, as well as its requisite files, from the repository didn't work? Is there more involved than simply adding the folder to `${VCPKG_ROOT}/ports/`? I'd like to avoid this in the future, would a simple `git pull` have sufficed?

**Comment by dg0yt** [comment]
It is unclear what was wrong with your repository or environment. And now it is probably no longer possible to ask.

> ~~~
> $ ./vcpkg install qt:x64-windows
> Computing installation plan...
> Error: while loading qt:
> The port directory (C:\Users\jparr\Documents\vcpkg\ports\qt) does not exist
> Error: failed to load port from C:\Users\jparr\Documents\vcpkg\ports\qt
> Note: Updating vcpkg by rerunning bootstrap-vcpkg may resolve this failure.

I think that a `git pull` might have been useful. Bootstrapping updates the tool, but it doesn't change repository state.

**Comment by jparr721** [comment]
That makes sense, is this perhaps documented? It was very confusing at first.

**Comment by dg0yt** [comment]
Not sure about the documentation. I wish the error message wouldn't point in the wrong direction.

**Comment by jparr721** [comment]
Sure thing, I'll close this for now then.
