### ISSUE TITLE
[libpq:x64-windows] build failure

### ISSUE THREAD

**Issue by vilisch** [microsoft/vcpkg#21351]
**Host Environment**
- OS: [Windows 10]
- Vcpkg version: 2020.01.17-nohash

**To Reproduce**
`./vcpkg.exe install poco:x64-windows poco:x86-windows`

**Failure logs** 
MSBUILD : error MSB1008: Only one project can be specified.
Switch: Documents/Coverage/OpenCppCoverage-master/Build/ThirdParty/vcpkg/scripts/buildsystems/msbuild/vcpkg.targets

[build-libpq-x64-windows-RELEASE-out.log](https://github.com/microsoft/vcpkg/files/7527739/build-libpq-x64-windows-RELEASE-out.log)
[build-libpq-x86-windows-RELEASE-out.log](https://github.com/microsoft/vcpkg/files/7527740/build-libpq-x86-windows-RELEASE-out.log)

**Comment by JackBoosY** [comment]
Please clone vcpkg in a non-space path and try again.

Thanks.

**Comment by dg0yt** [comment]
Given the log file name: Do you use a custom release-only triplet? (Looking also at #21351.)

**Comment by JackBoosY** [comment]
_Documents/Coverage/OpenCppCoverage-master/Build/ThirdParty/vcpkg/scripts/buildsystems/msbuild/vcpkg.targets_.
The default Windows Document path should be _SYS_PARTITION/Users/USER_NAME/Documents_.
So I assume there is a space at the end of your username.

**Comment by vilisch** [comment]
Thank you! It worked.
