### ISSUE TITLE
Package build failure with versioning when building multiple times

### ISSUE THREAD

**Issue by autoantwort** [microsoft/vcpkg#21350]
**Describe the bug**
Create a file `vcpkg.json` with the following content:
```json
{
    "name": "dependencies",
    "version-string": "1.0.1",
    "dependencies": [
        "openssl"
    ],
    "builtin-baseline":"897ff9372f15c032f1e6cd1b97a59b57d66ee5b2",
    "overrides": [
        {
            "name": "openssl",
            "version-string": "1.0.2o-3"
        }
    ]
}

```
Then run `vcpkg install`  
Delete the `vcpkg_installed` folder  
Run `vcpkg install --binarysource=clear`  
You get an error that a patch could not be applied:
```
-- Applying patch /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/buildtrees/versioning/versions/openssl/39d1773390a9817dd776d1d90e809d873437daa7/ConfigureIncludeQuotesFix.patch
CMake Error at scripts/cmake/z_vcpkg_apply_patches.cmake:61 (message):
  Applying patch failed: Checking patch Configure...

  warning: Configure has type 100755, expected 100644

  error: while searching for:

                                }

                        elsif (/^--with-zlib-include=(.*)$/)

                                {

                                $withargs{"zlib-include"}="-I$1";

                                }

                        elsif (/^--with-fipsdir=(.*)$/)

                                {

  

  error: patch failed: Configure:972

  error: Configure: patch does not apply

Call Stack (most recent call first):
  scripts/cmake/vcpkg_apply_patches.cmake:28 (z_vcpkg_apply_patches)
  buildtrees/versioning/versions/openssl/39d1773390a9817dd776d1d90e809d873437daa7/portfile.cmake:22 (vcpkg_apply_patches)
  scripts/ports.cmake:142 (include)
```

If you now run `rm -rf buildtrees` and then run `vcpkg install` the build is successful again. 

**Environment**
- OS: On every os
- Compiler: not important

**Expected behavior**
No error when applying patch.

**Comment by Neumann-A** [comment]
That is strange since vcpkg should clear the source dir on every build unless you explicitly pass `--editable`. It could be that your rebuild happend too fast and something still had a file lock into the source dir maybe?

**Comment by autoantwort** [comment]
vcpkg existed normally before I ran it again, so I don't thing that there was a file lock somewhere. And I get this error very reproducible and deleting the buildtrees folder manually is not a problem

**Comment by BillyONeal** [comment]
The right behavior here is probably to move the temp directories into the "installed" location in manifest mode.

**Comment by ras0219-msft** [comment]
Since it hasn't been said: this is an issue with using extremely old port versions that use helpers designed long before manifest mode existed. Any port developed since manifest mode was introduced should work.

Additionally, the version requested in the OP (`1.0.2o-3`) is no longer supported by OpenSSL: https://www.openssl.org/policies/releasestrat.html and we strongly recommend against its use for any reason without an extended support contract from OpenSSL (and therefore without developing a private port to use the updated, supported sources).

**Comment by JackBoosY** [comment]
> Since it hasn't been said: this is an issue with using extremely old port versions that use helpers designed long before manifest mode existed. Any port developed since manifest mode was introduced should work.

This is the drawback of the files in scripts/cmake without version control.

**Comment by BillyONeal** [comment]
> > Since it hasn't been said: this is an issue with using extremely old port versions that use helpers designed long before manifest mode existed. Any port developed since manifest mode was introduced should work.
> 
> This is the drawback of the files in scripts/cmake without version control.

In this case the problem comes from `portfile.cmake`, not anything in `scripts/cmake`.

**Comment by autoantwort** [comment]
Ok I will close that as _won't fix_
