### ISSUE TITLE
[assimp] update to 5.1

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#21361]
Library name: assimp
https://github.com/assimp/assimp/releases/tag/v5.1.0

New version number: 5.1

Other information that may be useful (release notes, etc...)
fix qtquick3d assimp feature.

**Comment by LilyWangLL** [comment]
Installing assimp 5.1.0 failed with build error as below. I submitted a bug on upstream: https://github.com/assimp/assimp/issues/4183
```
E:\vcpkg\buildtrees\assimp\src\29ac8f2cb6-00bd3a7e8d\code\AssetLib\glTF\glTFAssetWriter.inl(112): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'rapidjson::Value'
E:\vcpkg\buildtrees\assimp\src\29ac8f2cb6-00bd3a7e8d\code\AssetLib\glTF\glTFAssetWriter.inl(112): note: No constructor could take the source type, or constructor overload resolution was ambiguous
E:\vcpkg\buildtrees\assimp\src\29ac8f2cb6-00bd3a7e8d\code\AssetLib\glTF\glTFAssetWriter.inl(112): error C2661: 'rapidjson::GenericValue<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>>::AddMember': no overloaded function takes 2 arguments
E:\vcpkg\buildtrees\assimp\src\29ac8f2cb6-00bd3a7e8d\code\AssetLib\glTF\glTFAssetWriter.inl(146): error C2672: 'StringRef': no matching overloaded function found
E:\vcpkg\buildtrees\assimp\src\29ac8f2cb6-00bd3a7e8d\code\AssetLib\glTF\glTFAssetWriter.inl(146): error C2780: 'rapidjson::GenericStringRef<CharType> rapidjson::StringRef(const CharType *,size_t)': expects 2 arguments - 1 provided
E:\vcpkg\installed\x86-windows\include\rapidjson/document.h(463): note: see declaration of 'rapidjson::StringRef'
E:\vcpkg\buildtrees\assimp\src\29ac8f2cb6-00bd3a7e8d\code\AssetLib\glTF\glTFAssetWriter.inl(146): error C2784: 'rapidjson::GenericStringRef<CharType> rapidjson::StringRef(const CharType *)': could not deduce template argument for 'const CharType *' from 'std::string'
E:\vcpkg\installed\x86-windows\include\rapidjson/document.h(443): note: see declaration of 'rapidjson::StringRef'
```

**Comment by Neumann-A** [comment]
@LilyWangLL : a bit quick to regard this as an upstream issue....

a) have you actually checked the version of rapidjson bundled with assimp?
b) have you tried to also update rapidjson to a newer commit id?

**Comment by LilyWangLL** [comment]
> @LilyWangLL : a bit quick to regard this as an upstream issue....
> 
> a) have you actually checked the version of rapidjson bundled with assimp? b) have you tried to also update rapidjson to a newer commit id?

Thanks, I will test with new version of rapidjson.

**Comment by Osyotr** [comment]
Yeah, assimp does not build neither with current nor with latest version of rapidjson.

**Comment by rundheim** [comment]
Latest release of assimp is now  v5.1.3

**Comment by JackBoosY** [comment]
@rundheim Does 5.1.3 also include this bug fix?

**Comment by Osyotr** [comment]
@JackBoosY doesn't seem like it. Nothing relevant in changelog.
