### ISSUE TITLE
How do I compile only release version?

### ISSUE THREAD

**Issue by humfrey28whu** [microsoft/vcpkg#21360]
Because I usually only use the Release version, but vcpkg will compile Debug and Release by default when installing, which consumes more installation time and harddisk space. Is there a command to compile only the Release version library? Thanks!

**Comment by NancyLi1013** [comment]
Hi @humfrey28whu

Thanks for posting this issue. 

If you want to build only release version, you can add `set(VCPKG_BUILD_TYPE release)` to the triplet that you want to build.

Or you can use overlay-ports or overlay-triplet to build. 

https://github.com/microsoft/vcpkg/blob/master/docs/specifications/ports-overlay.md
https://github.com/microsoft/vcpkg/blob/master/docs/examples/overlay-triplets-linux-dynamic.md

**Comment by humfrey28whu** [comment]
It does work! Thanks! The following is a step-by-step description for novices:
1. Copy the `${VCPKG_ROOT}\triplets\x64-windows.cmake` and name it `x64-windows-rel.cmake`
2. Add `set(VCPKG_BUILD_TYPE release)` in the last line of `x64-windows-rel.cmake`
3. Modify the value of the environment variable `VCPKG_DEFAULT_TRIPLET` to x64-windows-rel

**Comment by humfrey28whu** [comment]
> It does work! Thanks! The following is a step-by-step description for novices:
> 
> 1. Copy the `${VCPKG_ROOT}\triplets\x64-windows.cmake` and name it `x64-windows-rel.cmake`
> 2. Add `set(VCPKG_BUILD_TYPE release)` in the last line of `x64-windows-rel.cmake`
> 3. Modify the value of the environment variable `VCPKG_DEFAULT_TRIPLET` to `x64-windows-rel`

@NancyLi1013 However, the libraries will be installed at `${VCPKG_ROOT}\installed\x64-windows-rel`. And my visual studio can't automatically find them. Is there any way to solve this problem? Thanks!

**Comment by NancyLi1013** [comment]
One way, you can `set(VCPKG_BUILD_TYPE release)` in ${VCPKG_ROOT}\triplets\x64-windows.cmake directly. This is simple, but it may affect other ports to build.

Another way, please try to use overlay-ports or overlay-triplets in manifest mode.

**Comment by humfrey28whu** [comment]
Yeah, thanks! And this method ([Changing the triplet](https://github.com/microsoft/vcpkg/blob/master/docs/users/integration.md#changing-the-triplet)) can also help!

**Comment by HppZ** [comment]
pls support this feature.
