### ISSUE TITLE
PowerShell-7.1.4-win-x86.zip dwonload timeout - address error

### ISSUE THREAD

**Issue by TimelifeCzy** [microsoft/vcpkg#21362]
-- Setting SOCKS_PROXY environment variables to 127.0.0.1:1081
A suitable version of powershell-core was not found (required v7.1.4). Downloading portable powershell-core v7.1.4...
Downloading powershell-core...
  https://github.com/PowerShell/PowerShell/releases/download/v7.1.4/PowerShell-7.1.4-win-x86.zip -> D:\vcpkg\downloads\PowerShell-7.1.4-win-x86.zip
Error: Failed to download from mirror set:
https://github.com/PowerShell/PowerShell/releases/download/v7.1.4/PowerShell-7.1.4-win-x86.zip: WinHttpSendRequest() failed: 12002
https://github.com/PowerShell/PowerShell/releases/download/v7.1.4/PowerShell-7.1.4-win-x86.zip: WinHttpSendRequest() failed: 12002
https://github.com/PowerShell/PowerShell/releases/download/v7.1.4/PowerShell-7.1.4-win-x86.zip: WinHttpSendRequest() failed: 12002
https://github.com/PowerShell/PowerShell/releases/download/v7.1.4/PowerShell-7.1.4-win-x86.zip: WinHttpSendRequest() failed: 12002

https://github.com/PowerShell/PowerShell/releases/download/v7.1.4/PowerShell-7.1.4-win-x86.zip  Address Error ，How to correct.

**Comment by TimelifeCzy** [comment]
A suitable version of powershell-core was not found (required v7.1.4). Downloading portable powershell-core v7.1.4...
File does not have the expected hash:
             url : [ https://github.com/PowerShell/PowerShell/releases/download/v7.1.4/PowerShell-7.1.4-win-x86.zip ]
       File path : [ D:\vcpkg\downloads\PowerShell-7.1.4-win-x86.zip ]
   Expected hash : [ cf30f80edb57f37501c4a380a8ddd8adf016a51a988a315e15ef517fdae42313ddf5260d8374db65ef12808ec980118bc8b543256df0c1d641a5b8355a80ba7b ]
     Actual hash : [ cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e ]

**Comment by TimelifeCzy** [comment]
Завантаження вручну перейти до каталогу

**Comment by robustjack** [comment]
Hello, I met this problem, too. I solved it by copy the link to thunder (a p2p downloader ) and download it.
Then put the file to the /download in vcpkg dir
