### ISSUE TITLE
[protobuf] update to 3.19.1

### ISSUE THREAD

**Issue by Spejik** [microsoft/vcpkg#21365]
Library name: protobuf

New version number: 3.19.1

Other information that may be useful (release notes, etc...)
https://github.com/protocolbuffers/protobuf/releases/tag/v3.19.1

**Comment by Spejik** [comment]
Just a note, the latest version is 3.19.4, but it doesn't seem to have any C++ related changes.
https://github.com/protocolbuffers/protobuf/releases/tag/v3.19.4

**Comment by LilyWangLL** [comment]
Fixed in PR #23474.
