### ISSUE TITLE
bootstrap-vcpkg.bat does not download the correct arch on Windows on ARM

### ISSUE THREAD

**Issue by jonshipman** [microsoft/vcpkg#21403]
Running .\bootstrap-vcpkg.bat on an ARM64 machine does not fire true for $env:PROCESSOR_ARCHITECTURE -eq 'ARM64' on line 49 of scripts\bootstrap.ps1. This is due to powershell.exe being an x86 compatible binary and returns AMD64 for $env:PROCESSOR_ARCHITECTURE

**Environment**
Windows 11  22000.318
Surface Pro X SQ1

**To Reproduce**
Run .\bootstrap-vcpkg.bat with 
```
Write-Host $env:PROCESSOR_ARCHITECTURE
exit
```
@ line 10 of scripts\bootstrap.ps1

CMD prints the proper variable for %PROCESSOR_ARCHITECTURE% so that should be passed to the ps1 script.

**Comment by JackBoosY** [comment]
cc @BillyONeal

**Comment by BillyONeal** [comment]
> CMD prints the proper variable for %PROCESSOR_ARCHITECTURE% so that should be passed to the ps1 script.

The ps script isn't invoked by `CMD` so I'm not sure what can be done there.

I don't have an arm64 device to test this with unfortunately.

Also note that even if the vcpkg binary is arm64, we don't have arm64 copies of cmake et al., or compilers, yet so the story isn't complete no matter what at this time.

**Comment by jonshipman** [comment]
Sorry, the bat is run by cmd.exe. The user documentation specifies to run ``.\bootstrap-vcpkg.bat``, which can solve the issue with a passthrough. It won't fix the script itself, but those following the README.md won't have this issue.

**Comment by BillyONeal** [comment]
Resolved by https://github.com/microsoft/vcpkg/pull/22605
