### ISSUE TITLE
[libxslt] Build failure

### ISSUE THREAD

**Issue by qornflex** [microsoft/vcpkg#21417]
**Host Environment**
- OS: Windows 10
- Compiler: latest (pulled from master on 11/14/2021)

package: libxslt[core]:x64-windows -> 1.1.34#1
  vcpkg version: 2021-11-02-af04ebf6274fd6f7a941bff4662b3955c64f6f42
  vcpkg-tool version: 7dff5e821 2021-11-14 (7 hours ago)

**To Reproduce**
./vcpkg install libxslt:x64-windows

**Failure logs** 
```
D:\vcpkg>vcpkg install libxslt:x64-windows
Computing installation plan...
The following packages will be built and installed:
    libxslt[core]:x64-windows -> 1.1.34#1
Detecting compiler hash for triplet x64-windows...
Restored 0 packages from C:\Users\root\AppData\Local\vcpkg\archives in 246.5 us. Use --debug to see more details.
Starting package 1/1: libxslt:x64-windows
Building package libxslt[core]:x64-windows...
-- Using cached e2584eed1c84c18f16e42188c30d2c3d8e3e8853.patch.
-- Using cached GNOME-libxslt-v1.1.34.tar.gz.
-- Cleaning sources at D:/vcpkg/buildtrees/libxslt/src/v1.1.34-9fbf4c76fa.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/vcpkg/downloads/GNOME-libxslt-v1.1.34.tar.gz
-- Applying patch D:/vcpkg/downloads/e2584eed1c84c18f16e42188c30d2c3d8e3e8853.patch
-- Applying patch 0001-Fix-makefile.patch
-- Applying patch 0002-Fix-lzma.patch
-- Applying patch 0003-Fix-configure.patch
-- Applying patch only_build_one_lib_type.patch
-- Using source at D:/vcpkg/buildtrees/libxslt/src/v1.1.34-9fbf4c76fa.clean
-- Prerunning x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: cscript configure.js cruntime=/MDd static=no debug=yes prefix=D:\\vcpkg\\packages\\libxslt_x64-windows\\debug include=D:\\vcpkg\\installed\\x64-windows\\include lib=D:\\vcpkg\\installed\\x64-windows\\debug\\lib bindir=$(PREFIX)\\bin sodir=$(PREFIX)\\bin zlib=yes lzma=yes
    Working Directory: D:/vcpkg/buildtrees/libxslt/x64-windows-dbg/win32
    Error code: 1
    See logs for more information:
      D:\vcpkg\buildtrees\libxslt\prerun-specific-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_nmake.cmake:174 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_install_nmake.cmake:115 (vcpkg_build_nmake)
  ports/libxslt/portfile.cmake:73 (vcpkg_install_nmake)
  scripts/ports.cmake:142 (include)


Error: Building package libxslt:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  package: libxslt[core]:x64-windows -> 1.1.34#1
  vcpkg version: 2021-11-02-af04ebf6274fd6f7a941bff4662b3955c64f6f42
  vcpkg-tool version: 7dff5e821 2021-11-14 (4 hours ago)

Additionally, attach any relevant sections from the log files above.
```

**Additional context**

Nothing particular today except that it seems cscript isn't able to deal with configure.js correctly... but I may be wrong.
But there is no way to install this package anymore without having this issue :/ 
It was still fine in April of this year, as I was compiling libxslt without any prob.

[prerun-specific-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/7534692/prerun-specific-x64-windows-dbg-out.log)
[stdout-x64-windows.log](https://github.com/microsoft/vcpkg/files/7534693/stdout-x64-windows.log)

**Comment by JackBoosY** [comment]
```
Input Error: There is no script engine for file extension ".js".
```

**Comment by JackBoosY** [comment]
Can you please run `cscript` in cmd and provide the output?
If it fails, please use suggestion in the `[official doc](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/cscript)`:

> if you double-click a script file with an extension that has no association, the Open With dialog box appears. Select wscript or cscript, and then select Always use this program to open this file type. This registers wscript.exe or cscript as the default script host for files of this file type.

**Comment by qornflex** [comment]
@JackBoosY Thanks for the proposal Jack.
I finally fixed it by using this fix:
https://www.winhelponline.com/blog/error-there-is-no-script-engine-for-file-extension-when-running-js-files
