### ISSUE TITLE
[clapack]:hash error & cmake error

### ISSUE THREAD

**Issue by leohawke** [Microsoft/vcpkg#2142]
**./vcpkg install ceres:x64-windows**
   =>dependend clapack 
vcpkg failed because of the **file hash != expect hash**

**expect hash**:cf19c710291ddff3f6ead7d86bdfdeaebca21291d9df094bf0a8ef599546b007757fb2dbb19b56511bb53ef7456eac0c73973b9627bf4d02982c856124428b49
**file hash**:c85a01c87ef3e39dfc1a2470555e1139b6074a0a2be7aa7011b34ffeb9cd5f822337a3f5163cff3f58d7df082364f59f15d32aca858f11334d63d9875aa40fee

**I modify this  vcpkg/ports/clapack/protfile.cmake**
Then:
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:43 (message):
    Command failed: G:/vcpkg/downloads/cmake-3.9.5-win32-x86/bin/cmake.exe;--build;.;--config;Release;--target;install;--;/p:VCPkgLocalAppDataDisabled=true;/p:UseIntelMKL=No;/m
    Working Directory: G:/vcpkg/buildtrees/clapack/x64-windows-rel
    See logs for more information:
      G:\vcpkg\buildtrees\clapack\install-x64-windows-rel-out.log
      G:\vcpkg\buildtrees\clapack\install-x64-windows-rel-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:62 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/clapack/portfile.cmake:44 (vcpkg_install_cmake)
  scripts/ports.cmake:72 (include)

cat  vcpkg\buildtrees\clapack\install-x64-windows-rel-out.log
=>CMake Warning (dev) at TESTING/CMakeLists.txt:13 (get_target_property):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The LOCATION property should not be read from target "xeigtstz".  Use the
  target name directly with add_custom_command, or use the generator
  expression $<TARGET_FILE>, as appropriate.

Call Stack (most recent call first):
  TESTING/CMakeLists.txt:293 (add_lapack_test)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_CXX_FLAGS
    CMAKE_CXX_FLAGS_RELEASE

**Comment by alexkaratarakis** [comment]
The hash seems to be correct, so I suspect the downloaded file is corrupted; you can try removing it. However, I noticed that the name in the portfile didn't include the file extension, so I fixed that in the latest version.

Therefore, you can simply do a `git pull` and try again.

**Comment by leohawke** [comment]
@alexkaratarakis  Thank you so muck I will try it again

**Comment by Cheney-W** [comment]
@leohawke , Thanks for reporting this issue. I can't reproduce it in the latest VCPKG.
Please open a new issue if this is still a problem for you.
