### ISSUE TITLE
autotools configure config.log not preserved 

### ISSUE THREAD

**Issue by daschuer** [microsoft/vcpkg#21422]
In case the ./configure step fails, the config.log file containing the details is not preserved. 
This happens because a FATAL_ERROR is issue before the copy of the file is done here.  
https://github.com/microsoft/vcpkg/blob/d369df7ecf194005eaca46f07368779cd486badd/scripts/cmake/vcpkg_execute_required_process.cmake#L127
The move statement lives here:
https://github.com/microsoft/vcpkg/blob/c973b499f2ec648d9e7ae6c784f94d0ebc41f788/scripts/cmake/vcpkg_configure_make.cmake#L811

It works in the good case, where the info is not needed, but it fails in the failure case where this info is interesting the most. 

**Proposed solution**
As a workaround I have made the error non fatal. 

**Describe alternatives you've considered**
Not sure how is the best way around the issue. Maybe we can tell vcpkg_execute_required_process to save the config.log file on failure.

**Comment by dg0yt** [comment]
Related: https://github.com/microsoft/vcpkg-tool/pull/226
