### ISSUE TITLE
 vcpkg was unable to detect the active compiler's information

### ISSUE THREAD

**Issue by zhangbowei** [microsoft/vcpkg#21427]
question:    ERROR    .\vcpkg.exe install eigen3:arm-linux 

plafform: win7
target: armv7
gcc: arm-linux-gnueabihf-gcc
![image](https://user-images.githubusercontent.com/14348480/141749333-fffd4ac2-6da5-443a-9057-5acf372263fe.png)

console log: 
```pwsh
D:\vcpkg (master -> origin)
λ .\vcpkg.exe install eigen3:arm-linux
Computing installation plan...
The following packages will be built and installed:
    eigen3[core]:arm-linux -> 3.3.9#1
Detecting compiler hash for triplet arm-linux...
Error: while detecting compiler information:
The log content at D:\vcpkg\buildtrees\detect_compiler\stdout-arm-linux.log is:
-- Configuring arm-linux
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: ninja -v
    Working Directory: D:/vcpkg/buildtrees/detect_compiler/arm-linux-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\vcpkg\buildtrees\detect_compiler\config-arm-linux-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:345 (vcpkg_execute_required_process)
  scripts/detect_compiler/portfile.cmake:18 (vcpkg_configure_cmake)
  scripts/ports.cmake:142 (include)



Error: vcpkg was unable to detect the active compiler's information. See above for the CMake failure output.
```

**Comment by NancyLi1013** [comment]
Hi @zhangbowei 

Thanks for posting this issue.

Could you please provide the information from _D:\vcpkg\buildtrees\detect_compiler\config-arm-linux-out.log_?

**Comment by zhangbowei** [comment]
[1/1] cmd /c "cd .. && "D:/vcpkg/downloads/tools/cmake-3.21.1-windows/cmake-3.21.1-windows-i386/bin/cmake.exe" "D:/vcpkg/scripts/detect_compiler" "-DCMAKE_MAKE_PROGRAM=D:/vcpkg/downloads/tools/ninja/1.10.2-windows/ninja.exe" "-DCMAKE_SYSTEM_NAME=Linux" "-DBUILD_SHARED_LIBS=OFF" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=D:/vcpkg/scripts/toolchains/linux.cmake" "-DVCPKG_TARGET_TRIPLET=arm-linux" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=external" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=D:/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_LINKER_FLAGS_RELEASE=" "-DVCPKG_LINKER_FLAGS_DEBUG=" "-DVCPKG_TARGET_ARCHITECTURE=arm" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=D:/vcpkg" "-DZ_VCPKG_ROOT_DIR=D:/vcpkg" "-D_VCPKG_INSTALLED_DIR=D:/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=D:/vcpkg/packages/detect_compiler_arm-linux""
FAILED: ../CMakeCache.txt 
cmd /c "cd .. && "D:/vcpkg/downloads/tools/cmake-3.21.1-windows/cmake-3.21.1-windows-i386/bin/cmake.exe" "D:/vcpkg/scripts/detect_compiler" "-DCMAKE_MAKE_PROGRAM=D:/vcpkg/downloads/tools/ninja/1.10.2-windows/ninja.exe" "-DCMAKE_SYSTEM_NAME=Linux" "-DBUILD_SHARED_LIBS=OFF" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=D:/vcpkg/scripts/toolchains/linux.cmake" "-DVCPKG_TARGET_TRIPLET=arm-linux" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=external" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=D:/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_LINKER_FLAGS_RELEASE=" "-DVCPKG_LINKER_FLAGS_DEBUG=" "-DVCPKG_TARGET_ARCHITECTURE=arm" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=D:/vcpkg" "-DZ_VCPKG_ROOT_DIR=D:/vcpkg" "-D_VCPKG_INSTALLED_DIR=D:/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=D:/vcpkg/packages/detect_compiler_arm-linux""
-- The C compiler identification is unknown
CMake Error at CMakeLists.txt:11 (enable_language):
  The CMAKE_C_COMPILER:

    arm-linux-gnueabihf-gcc

  is not a full path and was not found in the PATH.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "D:/vcpkg/buildtrees/detect_compiler/arm-linux-rel/CMakeFiles/CMakeOutput.log".
See also "D:/vcpkg/buildtrees/detect_compiler/arm-linux-rel/CMakeFiles/CMakeError.log".
ninja: build stopped: subcommand failed.

**Comment by JackBoosY** [comment]
You are trying to build linux library in Windows, so you should use the crossbuild triplet instead of the official Linux triplet.

**Comment by dg0yt** [comment]
> You are trying to build linux library in Windows, so you should use the crossbuild triplet instead of the official Linux triplet.

What is a "cross-build triplet"? AFAIK there are target triplets and host triplets, and a mismatch of target and host means cross compiling.

**Comment by JackBoosY** [comment]
> > You are trying to build linux library in Windows, so you should use the crossbuild triplet instead of the official Linux triplet.
> 
> What is a "cross-build triplet"? AFAIK there are target triplets and host triplets, and a mismatch of target and host means cross compiling.

The host machine is win7, and the compiler selected to gcc, so he should use an unofficial triplet that uses gcc to set the compiler.

**Comment by zhangbowei** [comment]
How do I use an unofficial triplet？

**Comment by JackBoosY** [comment]
> How do I use an unofficial triplet？

I think this question is off topic. 
You can found the official in folder _VCPKG_ROOT/triplets_, and the community triplets are in _VCPKG_ROOT/triplets/community_ which may have some issues and we can't guarantee that.
To use triplet, you shoud add `:TRIPLET_NAME` after ports or add extra options `--triplet=TRIPLET_NAME` to the install command line.
Such as:
```pwsh
.\vcpkg install eigen3:arm64-windows
```
or
```pwsh
.\vcpkg install eigen3 --triplet=arm64-windows
```

**Comment by zhangbowei** [comment]
D:\vcpkg (master -> origin)
λ .\vcpkg install eigen3 --triplet=arm64-windows
Computing installation plan...
The following packages will be built and installed:
    eigen3[core]:arm64-windows -> 3.3.9#1
Detecting compiler hash for triplet arm64-windows...
Error: Unsupported toolchain combination.
Target was arm64 but the chosen Visual Studio instance supports:
    x86, amd64, x86_amd64, amd64_x86
Vcpkg selected D:\vsstudio as the Visual Studio instance.
Detected instances:
    D:\vsstudio

See https://github.com/microsoft/vcpkg/blob/master/docs/users/triplets.md#VCPKG_VISUAL_STUDIO_PATH for more information.
Note: Updating vcpkg by rerunning bootstrap-vcpkg may resolve this failure.

**Comment by zhangbowei** [comment]
![image](https://user-images.githubusercontent.com/14348480/143820814-3c0f236e-042d-4156-89b4-7134bf25d956.png)

**Comment by JackBoosY** [comment]
Yeah I know what this issue is, the fact is:
1. we need a new toolchain to handle this.
2. we need a new triplet to use gcc in Windows.

So far, triplet for arm-linux is only available in Linux, which means we can only use community triplet `arm64-linux` and `arm-linux` **in Linux**.

**Comment by zhangbowei** [comment]
So，what All I need to do is to patiently wait for u， Right？

**Comment by JackBoosY** [comment]
Unfortunately, we only guarantee the stability of the official triplets.
But I'm glad to see that other contributors can do this.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. This issue hasn’t been updated in three months, if it is still an issue, please reopen.
