### ISSUE TITLE
[tensorflow-cc]error LNK2019: unresolved external symbol "tensorflow::io::RecordWriter::WriteRecord"

### ISSUE THREAD

**Issue by shelllet** [microsoft/vcpkg#21423]
**Describe the bug**
```
error LNK2019: unresolved external symbol "public: class tensorflow::Status __cdecl tensorflow::io::RecordWriter::WriteRecord(class std::basic_string_view<char,struct std::char_traits<char> >)" (?WriteRecord@RecordWriter@io@tensorflow@@QEAA?AVStatus@3@V?$basic_string_view@DU?$char_traits@D@std@@@std@@@Z) referenced in function "public: static struct winrt::Windows::Foundation::IAsyncAction __cdecl winrt::Tensorflow::implementation::TfRecord::Write$_ResumeCoro$1(struct winrt::hstring,struct winrt::Windows::Foundation::Collections::IMap<struct winrt::hstring,int>)" (?Write$_ResumeCoro$1@TfRecord@implementation@Tensorflow@winrt@@SA?AUIAsyncAction@Foundation@Windows@4@Uhstring@4@U?$IMap@Uhstring@winrt@@H@Collections@674@@Z)
```
**Environment**
- OS: Windows
- Compiler: msvc142

**To Reproduce**
1. ./vcpkg install tensorflow-cc:x64-widows
2. Enable std:c++17
3. See error
call `tensorflow::io::RecordWriter::WriteRecord` method.

**Expected behavior**
build successful!

**Failure logs** 

?WriteRecord@RecordWriter@io@tensorflow@@QEAA?AVStatus@3@V?$basic_string_view@DU?$char_traits@D@std@@@std@@@Z

**Additional context**

```
namespace absl {
ABSL_NAMESPACE_BEGIN
using string_view = std::string_view;
ABSL_NAMESPACE_END
}  // namespace absl
```
```
namespace tensorflow {

using StringPiece = absl::string_view;

}  // namespace tensorflow
```

`Status WriteRecord(StringPiece data);` 

i dumpbin  symbols tensorflow-cc.lib and found abi signature: 
```
4B0 00000540 SECT6  notype ()    External     | ?WriteRecord@RecordWriter@io@tensorflow@@QEAA?AVStatus@3@Vstring_view@lts_20210324@absl@@@Z (public: class tensorflow::Status __cdecl tensorflow::io::RecordWriter::WriteRecord(class absl::lts_20210324::string_view))
4B1 00000820 SECT6  notype ()    External     | ?WriteRecord@RecordWriter@io@tensorflow@@QEAA?AVStatus@3@AEBVCord@lts_20210324@absl@@@Z (public: class tensorflow::Status __cdecl tensorflow::io::RecordWriter::WriteRecord(class absl::lts_20210324::Cord const &))

```
vcpkg does't compile tensoflow dependency lib absl with `ABSL_OPTION_USE_STD_STRING_VIEW =2` or `ABSL_OPTION_USE_STD_STRING_VIEW =1`  see [https://github.com/abseil/abseil-cpp/blob/master/absl/base/options.h"](https://github.com/abseil/abseil-cpp/blob/master/absl/base/options.h)

**Comment by JackBoosY** [comment]
The not found one is `basic_string_view`, and the exist are `Vstring_view` and `AEBVCord`, so I assue that's a macro issue.

**Comment by JackBoosY** [comment]
> vcpkg does't compile tensoflow dependency lib absl with ABSL_OPTION_USE_STD_STRING_VIEW =2 or ABSL_OPTION_USE_STD_STRING_VIEW =1 see https://github.com/abseil/abseil-cpp/blob/master/absl/base/options.h"

Yes, that's it. You need to use the corresponding macro to use tf-cc.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
