### ISSUE TITLE
Error while installing libpq library

### ISSUE THREAD

**Issue by K0tBegemot** [microsoft/vcpkg#21437]
**Host Environment**
- OS: Windows 10 Pro 21H1 19043.1348
- Compiler: MSVC

**To Reproduce**
./vcpkg install libpq:x64-windows

**Failure logs** 
Computing installation plan...
The following packages will be built and installed:
    libpq[core,openssl,zlib]:x64-windows -> 12.2#20
Detecting compiler hash for triplet x64-windows...
Restored 0 packages from C:\Users\Bakel\AppData\Local\vcpkg\archives in 535.2 us. Use --debug to see more details.
Starting package 1/1: libpq:x64-windows
Building package libpq[core,openssl,zlib]:x64-windows...
-- Using cached postgresql-12.2.tar.bz2.
-- Cleaning sources at C:/vcpkg/vcpkg/buildtrees/libpq/src/tgresql-12-ef0b4889ed.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg/vcpkg/downloads/postgresql-12.2.tar.bz2
-- Applying patch patches/windows/install.patch
-- Applying patch patches/windows/win_bison_flex.patch
-- Applying patch patches/windows/openssl_exe_path.patch
-- Applying patch patches/windows/Solution.patch
-- Applying patch patches/windows/MSBuildProject_fix_gendef_perl.patch
-- Applying patch patches/windows/msgfmt.patch
-- Applying patch patches/windows/python_lib.patch
-- Applying patch patches/windows/fix-compile-flag-Zi.patch
-- Applying patch patches/windows/minimize_install.patch
-- Using source at C:/vcpkg/vcpkg/buildtrees/libpq/src/tgresql-12-ef0b4889ed.clean
-- Copying libpq source files to C:/vcpkg/vcpkg/buildtrees/libpq/x64-windows-rel...
-- Copying libpq source files... done
CMake Deprecation Warning at scripts/ports.cmake:75 (message):
  vcpkg_apply_patches has been deprecated in favor of the `PATCHES` argument
  to `vcpkg_from_*`.
Call Stack (most recent call first):
  scripts/cmake/vcpkg_apply_patches.cmake:18 (z_vcpkg_deprecation_message)
  ports/libpq/portfile.cmake:127 (vcpkg_apply_patches)
  scripts/ports.cmake:142 (include)

-- Applying patch patches/windows/Solution_RELEASE.patch
-- Applying patch patches/windows/python3_build_RELEASE.patch
-- Patches applied!
-- Building libpq x64-windows-RELEASE...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: C:/vcpkg/vcpkg/downloads/tools/perl/5.32.1.1/perl/bin/perl.exe build.pl RELEASE libpq
    Working Directory: C:/vcpkg/vcpkg/buildtrees/libpq/x64-windows-rel/src/tools/msvc
    Error code: 1
    See logs for more information:
      C:\vcpkg\vcpkg\buildtrees\libpq\build-libpq-x64-windows-RELEASE-out.log

Call Stack (most recent call first):
  ports/libpq/portfile.cmake:223 (vcpkg_execute_required_process)
  scripts/ports.cmake:142 (include)

Error: Building package libpq:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libpq:x64-windows
  Vcpkg version: 2021-09-10-2059ef11aa6067e6f59b0d939c5d17e3c5c47d3e
**Additional context**
This library was installed with a more general command .\vcpkg install qt:x64-windows

**Comment by dg0yt** [comment]
Please do a `git pull`.

**Comment by K0tBegemot** [comment]
All wors fine now. Thanks for the correction
