### ISSUE TITLE
Could not copy the file "targetBinaryFilePath" because it was not found.

### ISSUE THREAD

**Issue by aronbardsley** [microsoft/vcpkg#21431]
https://github.com/microsoft/vcpkg/commit/7dff5e821e4a0b7fe43e8a28c51357217bb4bef6

Can someone please fix line 61 of that file

`if ($copiedFilesLog) { Add-Content $copiedFilesLog targetBinaryFilePath -Encoding UTF8 } `
should be:
`if ($copiedFilesLog) { Add-Content $copiedFilesLog $targetBinaryFilePath -Encoding UTF8 }`

Note the dollar sign is needed on the variable targetBinaryFilePath

The commit was done 20 hours ago and it just nuked my build
This is the error it gives in case you see other people report the same problem: 
![image](https://user-images.githubusercontent.com/16513722/141784194-933d3bef-5996-4e9b-913b-aee431a12c89.png)

also - thank you for the awesome work you do on a wonderful tool :)

**Comment by ras0219-msft** [comment]
Thanks for the kind words! https://github.com/microsoft/vcpkg/pull/21429 has been merged and should fix this issue. Sorry for the trouble!
