### ISSUE TITLE
[qt] build failure

### ISSUE THREAD

**Issue by ilongshan** [microsoft/vcpkg#21435]
**Host Environment**
- OS: Ubuntu 20.04
- Compiler: gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04) 

**To Reproduce**
`./vcpkg install qt`

**Failure logs** 
> Error: qtwebengine[core] is only supported on '!static & !((arm | x86) & windows)'

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by JonLiu1993** [comment]
@Neumann-A ,Could you please take a look?

**Comment by Neumann-A** [comment]
> @Neumann-A ,Could you please take a look?

No since the error obviously is telling what is wrong (especially since it is an error emitted by vcpkg itself and not the build)

@ilongshan

only install the qtstuff you actually need. If you need qtwebengine on linux you need to make a custom triplet with dynamic library linkage.

**Comment by ilongshan** [comment]
OK, I will install qt without qtwebengine.
Thanks

**Comment by ilongshan** [comment]
There seems no option to exclude qtwebengine when installing qt?

Is there any way to install qt without qtwebengine?

**Comment by JackBoosY** [comment]
> There seems no option to exclude qtwebengine when installing qt?
> 
> Is there any way to install qt without qtwebengine?

You can pick single qt component port to build instead a "full" qt.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

**Comment by lukesdm** [comment]
> only install the qtstuff you actually need. If you need qtwebengine on linux you need to make a custom triplet with dynamic library linkage.

Hi @Neumann-A , as someone new to vcpkg in an unfamiliar project using qt and cmake, coming to this thread via google... would you mind elaborating on what this means please - which docs should I look at?

**Comment by Neumann-A** [comment]
https://github.com/microsoft/vcpkg/blob/master/docs/users/triplets.md#per-port-customization

**Comment by lukesdm** [comment]
> https://github.com/microsoft/vcpkg/blob/master/docs/users/triplets.md#per-port-customization

Many thanks!
