### ISSUE TITLE
[s2n] build failure on macOS

### ISSUE THREAD

**Issue by Mike4Online** [microsoft/vcpkg#21443]
**Host Environment**
- OS: macOS 10.14 Mojave
- Compiler: AppleClang 11.0.0.11000033

**To Reproduce**
`./vcpkg install aws-sdk-cpp[s3]:x64-osx --no-binary-caching`

**Failure logs** 
Build fails while building the s2n library, claiming LibCrypo cannot be found

**Additional context**
A work-around is to manually build OpenSSL 1.1.1 first, as follows:
`./vcpkg install openssl[core]:x64-osx --no-binary-caching`
`./vcpkg install aws-sdk-cpp[s3]:x64-osx --no-binary-caching`

I also found that curl was rejecting the SSL certificate of the server providing the OpenSSL source.  I had to create a text file `~/.curlrc` and add the following line to the file:

    --insecure

in order for curl to successfully download the OpenSSL source.  I am not sure why this was necessary.  I tried installing macOS security updates for macOS Mojave, and also tried updating curl with HomeBrew, but I still needed to set `--insecure` in `~/.curlrc` for vcpkg to build OpenSSL.

**Comment by JackBoosY** [comment]
Can you please provide the failure logs first?

**Comment by JackBoosY** [comment]
What's the difference between this and https://github.com/microsoft/vcpkg/issues/21445?

**Comment by Mike4Online** [comment]
> What's the difference between this and #21445?

This issue is primarily about OpenSSL failing to automatically build as a dependency for aws-sdk-cpp.

Issue #21445 is about the aws-sdk-cpp package failing to fully honor the MACOSX_DEPLOYMENT_TARGET environment variable, specifically MACOSX_DEPLOYMENT_TARGET=10.9 (but could be any value less that 10.13).

It is possible both issues are related to building this package on macOS 10.14 Mojave, rather than a newer macOS version such as Big Sur or Monterey.  But I assume vcpkg is still supported on macOS Mojave.

I will upload a failure log for this issue tomorrow.

**Comment by dg0yt** [comment]
> This issue is primarily about OpenSSL failing to automatically build as a dependency for aws-sdk-cpp.

What do you mean by that? Port aws-sdk-cpp is to use port openssl from vcpkg.

aws-sdk-cpp in vcpkg is not up-to-date, unfortunately. The version used here has a number of cmake issues. For example, it calls `include(FindOpenSSL)` instead of `find_package(OpenSSL)`. This prevents vcpkg cmake wrapper taking effect.

So the first step needed is updating the port to a more recent version.

**Comment by dg0yt** [comment]
> A work-around is to manually build OpenSSL 1.1.1 first, as follows:
> `./vcpkg install openssl[core]:x64-osx --no-binary-caching`
> `./vcpkg install aws-sdk-cpp[s3]:x64-osx --no-binary-caching`

What is suggested to do manually is already enforced by dependencies:
~~~
$ ./vcpkg depend-info aws-sdk-cpp[core,s3]:x64-osx --max-recurse=0
aws-sdk-cpp[s3]: aws-crt-cpp, curl, openssl, vcpkg-cmake, vcpkg-cmake-config, zlib
~~~

**Comment by Mike4Online** [comment]
What I mean is that building
`./vcpkg install aws-sdk-cpp[s3]:x64-osx`
will fail, but when i build
`./vcpkg install openssl[core]:x64-osx`
and _then_ building
`./vcpkg install aws-sdk-cpp[s3]:x64-osx`
then they both succeed.  

It should not be necessary to build OpenSSL first, because OpenSSL is one of the dependencies of aws-sdk-cpp, as you mentioned, but for me it is necessary to build OpenSSL first.  So I assume something must be wrong with the aws-sdk-cpp port.  The s2n library (another aws-sdk-cpp dependency) builds before OpenSSL, but s2n needs LibCrypto from OpenSSL, so s2n fails.  So perhaps the build order of the dependencies is wrong.

I am doing these builds on macOS Mojave, in a vcpkg folder that is freshly prepared (git clone followed by running the bootstrap.sh script).

**Comment by dg0yt** [comment]
> What I mean is that building `./vcpkg install aws-sdk-cpp[s3]:x64-osx` will fail, but when i build `./vcpkg install openssl[core]:x64-osx` and _then_ build `./vcpkg install aws-sdk-cpp[s3]:x64-osx` then they both succeed.
> 
> It should not be necessary to build OpenSSL first, because OpenSSL is one of the dependencies of aws-sdk-cpp, as you mentioned, but for me it is necessary to build OpenSSL first. So I assume something must be wrong with the aws-sdk-cpp port. The s2n library (another aws-sdk-cpp dependency) builds before OpenSSL, but s2n needs LibCrypto from OpenSSL, so s2n fails. So perhaps the build order of the dependencies is wrong.

Well:
~~~
$ ./vcpkg depend-info s2n:x64-osx --max-recurse=1vcpkg-cmake: 
vcpkg-cmake-config: 
s2n: vcpkg-cmake, vcpkg-cmake-config
~~~

So s2n doesn't declare an openssl dependency. 

> **Failure logs**
> Build fails while building the s2n library, claiming LibCrypo cannot be found

In that case, you should have chosen a different title for the issue, even if aws-sdk-cpp is the ultimate goal. (And I assume that this was written in the instruction in the console output when the s2n port failed.)
Would you mind updating the title now?

**Comment by Mike4Online** [comment]
> s2n doesn't declare an openssl dependency.

Perhaps s2n should declare a dependency on openssl.  I am uploading vcpkg console output and an error log to this comment.  These logs were generated by attempting to build aws-sdk-cpp.  The logs show that the build of s2n that is triggered by building aws-sdk-cpp fails due to LibCrypto being missing.  So s2n does depend on LibCrypto (which is one of two OpenSSL libraries).

I do not understand updating the Title of this issue, because building s2n is not my goal.  The error happens for me on a clean vcpkg folder trying to build aws-sdk-cpp, so changing the title would not represent the issue I am having.

I do not know why the s2n portion of the aws-sdk-cpp build fails to find LibCrypto.  All I know is that manually building OpenSSL with vcpkg prior to building aws-sdk-cpp is an effective work-around, but I should not have to do that.  Perhaps there is something wrong with the port for aws-sdk-cpp or one of its dependencies.  Perhaps it is a build order issue.  Perhaps the port doesn't work properly when I have installed CMake via HomeBrew.  As an end user of vcpkg, it is my job to say what is broken from my perspective, and leave the diagnostics to you.

[aws-sdk-cpp_console_output.txt](https://github.com/microsoft/vcpkg/files/7549428/aws-sdk-cpp_console_output.txt)
[s2n_config-x64-osx-dbg-err.log](https://github.com/microsoft/vcpkg/files/7549429/s2n_config-x64-osx-dbg-err.log)

.

**Comment by JackBoosY** [comment]
```
Could NOT find LibCrypto (missing: LibCrypto_LIBRARY LibCrypto_INCLUDE_DIR)
```

Can you pleae remove openssl and retry again?

**Comment by Mike4Online** [comment]
I deleted my entire vcpkg root folder, then grabbed it fresh with git clone, and tried installing with

`./vcpkg install aws-sdk-cpp[s3]:x64-osx`

I did this two minutes after receiving an email with your latest comment.  I got the same error when it got to building s2n:
```

MACBUILD2:vcpkg michael$ cat /Users/michael/vcpkg/buildtrees/s2n/config-x64-osx-dbg-err.log
CMake Error at /usr/local/Cellar/cmake/3.21.3_1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find LibCrypto (missing: LibCrypto_LIBRARY LibCrypto_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.21.3_1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindLibCrypto.cmake:71 (find_package_handle_standard_args)
  /Users/michael/vcpkg/scripts/buildsystems/vcpkg.cmake:788 (_find_package)
  CMakeLists.txt:389 (find_package)

```

**Comment by Mike4Online** [comment]
Note in my previous comment, in the error text, that the path

`/usr/local/Cellar/cmake`

is where HomeBrew installed its copy of CMake.

**Comment by JackBoosY** [comment]
It seems that aws-sdk-cpp[s3] finds the openssl in system side.

**Comment by Mike4Online** [comment]
Perhaps the `aws-sdk-cpp` port behaves improperly only when CMake has been installed via HomeBrew.

Let me know if you'd like me to rename this issue back to referencing the [aws-sdk-cpp] port, rather than the s2n port.

As for the other issue, [#21445](https://github.com/microsoft/vcpkg/issues/21445), it is also an issue with the `aws-sdk-cpp` port, but it is unrelated to this issue.

**Comment by dg0yt** [comment]
I can reproduce the `s2n` issue on osx:

~~~
    See logs for more information:
      /Users/dg0yt/dev/vcpkg/buildtrees/s2n/config-x64-osx-dbg-out.log
      /Users/dg0yt/dev/vcpkg/buildtrees/s2n/config-x64-osx-dbg-err.log
...
Error: Building package s2n:x64-osx failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  package: s2n[core]:x64-osx -> 1.1.1
  vcpkg version: 2021-11-02-af04ebf6274fd6f7a941bff4662b3955c64f6f42
  vcpkg-tool version: 03f3d5262 2021-11-16 (10 hours ago)

Additionally, attach any relevant sections from the log files above.
~~~

@Mike4Online This is the output of vcpkg tool. Having the title right helps to focus attention - and it is also helpful for other users which may have a different ultimate goal but also stumble over s2n.

**Comment by Mike4Online** [comment]
Glad you can reproduce the issue.  Looking forward to a corrected s2n port.  Meanwhile,  can do the work-around I have documented, above.

I'll leave the Title of this issue as it currently is.  If you need me to edit it, let me know and I'll do so.
