### ISSUE TITLE
[libiconv] build failure

### ISSUE THREAD

**Issue by taviso** [microsoft/vcpkg#21442]
**Host Environment**
- OS: Windows 10
- Compiler: msvc 19.29.30040

**To Reproduce**

```
> md "c:\test path"
> cd "c:\test path"
> git clone https://github.com/Microsoft/vcpkg.git
> .\vcpkg\bootstrap-vcpkg.bat
> .\vcpkg\vcpkg install libiconv
```

The installation fails if the buildroot is in a path with a space in it.

**Comment by JonLiu1993** [comment]
@taviso ,Thanks for posting this issue, 
- I created a file named test path with spaces on my local
- Then open powershell and run the command git clone https://github.com/Microsoft/vcpkg.git
- Then run .\bootstrap-vcpkg.bat
- Finally run ./vcpkg install libiconv install success

````
https://github.com/PowerShell/PowerShell/releases/download/v7.1.4/PowerShell-7.1.4-win-x86.zip -> F:\test-pr\test path\vcpkg\downloads\PowerShell-7.1.4-win-x86.zip
Extracting powershell-core...
Restored 1 packages from C:\Users\AppData\Local\vcpkg\archives in 124 ms. Use --debug to see more details.
Starting package 1/1: libiconv:x86-windows
Installing package libiconv[core]:x86-windows...
Elapsed time for package libiconv:x86-windows: 200.6 ms

Total elapsed time: 35.37 s

The package libiconv provides CMake targets:

    find_package(iconv CONFIG REQUIRED)
    target_link_libraries(main PRIVATE Iconv::Charset)
````

**Comment by dg0yt** [comment]
> Elapsed time for package libiconv:x86-windows: 200.6 ms

You installed from cache. `--no-binarycaching`...

**Comment by JonLiu1993** [comment]
Confirmed

**Comment by JackBoosY** [comment]
This is a upstream issue. The upstream doesn't consider this situation in `Makefile.in`.
I recommend cloning vcpkg in a non-spatial path to avoid such issues.

**Comment by dg0yt** [comment]
And the console should also have this line:
~~~
Detected whitespace in root directory. Please move the path to one without whitespaces! The required tools do not handle whitespaces correctly and the build will most likely fail
~~~
But unfortunately, vcpkg tool still prints the instruction to open an issue.

**Comment by JackBoosY** [comment]
In fact, autotools supports paths with spaces, but users must manually process them in Makefile.in.

**Comment by taviso** [comment]
I guess a workaround would be to use the short path, which will not contain any spaces. I.e. `C:\testpa~1`? As far as I know, it should work identically?

**Comment by JackBoosY** [comment]
> I guess a workaround would be to use the short path, which will not contain any spaces. I.e. `C:\testpa~1`? As far as I know, it should work identically?

This type of path generally needs to be processed into abbreviated paths using functions, but obviously this is not done in libiconv.

**Comment by JackBoosY** [comment]
Close this PR until upstream fixes this.

**Comment by taviso** [comment]
I guess, but why not just use the shortpath? I don't really know what you mean by "abbreviated paths using functions", I mean if the PWD has a space, `SetCurrentDirectory()` into the short path, then run the build?

That way upstream doesn't have to do anything, and it will just work, no?

**Comment by JackBoosY** [comment]
> I'm saying, that exact directory can legally be referred to as C:\foobar~1\build (try it!). That path has no spaces, and short names never have spaces. You can now build libiconv in a path with a space, and it will work (I tried).

But what about non-Windows?

**Comment by dg0yt** [comment]
> Edit: nmake is just for Windows so there is no issue in non-Windows.

There is no `nmake` involved here. But autotools and MSYS2.

**Comment by JackBoosY** [comment]
> > Edit: nmake is just for Windows so there is no issue in non-Windows.
> 
> There is no `nmake` involved here. But autotools and MSYS2.

So we can only use this workaround for Windows, right?

**Comment by dg0yt** [comment]
If workaround means: 

> if the PWD has a space, SetCurrentDirectory() into the short path, then run the build?

then you can use it only for Windows. AFAICT short paths are a relict of the mid-90ies FAT (8.3 file names) to VFAT transition. 

And you have to test this thoroughly, in CI. You might easily end up with an impenetrable mix of short paths and canonical paths.
- When building with MSYS2, paths in environment variables and parameters are converted between Windows format and Unix format when changing between Windows runtime and MSYS2 runtime. It is not clear to me if this cooperates nicely with short paths.
- vcpkg does a lot substitutions on literal paths, to establish relocatable binary packages. It is not clear to me if this cooperates nicely with short paths.
- In the end it is not enough to know that port libiconv builds. You must be sure that it can be used for downstream ports, even if installed from cache in a different location. E.g. is the pc file fixup correct? It may be more difficult for other ports.

I'm really not sure if it is worth the hassle.

(IMO the only good reason is: Non-privileged users with space in account name.)

**Comment by taviso** [comment]
The current solution is to just accept build failures if your `%PROFILEDIR%` has a space. Is that really better? :)

Each path has only one long name and a short name, it seems really hard to get confused.

Sure, this only helps Windows users, but they're also the ones most likely to have a space in a build path!
