### ISSUE TITLE
vcpkg remove --recurse should also remove dependencies build with feature packages

### ISSUE THREAD

**Issue by jasjuang** [Microsoft/vcpkg#2145]
For example, lets say I have vtk core installed and opencv[vtk] installed. Currently if I want to remove expat something like this will show

``````
C:\vcpkg>vcpkg remove expat
The following packages will be removed:
    expat:x64-windows
  * vtk:x64-windows
Additional packages (*) need to be removed to complete this operation.
If you are sure you want to remove them, run the command with the --recurse option
``````

However, I am expecting something like

``````
C:\vcpkg>vcpkg remove expat
The following packages will be removed:
    expat:x64-windows
  * vtk:x64-windows
  * opencv:x64-windows
Additional packages (*) need to be removed to complete this operation.
If you are sure you want to remove them, run the command with the --recurse option
``````

**Comment by ras0219-msft** [comment]
Thanks for reporting this! It looks like a serious bug.

However, I'm having a bit of trouble reproducing it. I added a test case, but it passes for me:
https://github.com/Microsoft/vcpkg/blob/e2575e8c961e90b5dd35ef37c0b241b6cdb2914a/toolsrc/src/tests.plan.cpp#L547-L559

Could you try running the tests (open `toolsrc\vcpkg.sln`, build all, then Test -> Run -> All Tests) and adding a case that fails?

(Also, just to confirm, `vcpkg list opencv --featurepackages` _does_ list `opencv[vtk]:x64-windows`?)

**Comment by jasjuang** [comment]
I am sorry, when I do `vcpkg list opencv --featurepackages` there is no `opencv[vtk]:x64-windows`. Apparently there is an error in the script I created as suggested in #2101.
