### ISSUE TITLE
botan2 build static botan-2.a with enable -fPIC

### ISSUE THREAD

**Issue by CAMOBAP** [microsoft/vcpkg#21461]
****

**Is your feature request related to a problem? Please describe.**

```
/usr/bin/ld: /usr/local/share/vcpkg/installed/x64-linux/debug/lib/libbotan-2.a(src_lib_ffi.o): relocation R_X86_64_PC32 against symbol `stderr@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
```

Full log: https://github.com/rnpgp/rnp/runs/4222343272?check_suite_focus=true#step:7:724

**Proposed solution**

Always compile with `--extra-cxxflags=-fPIC`

**Describe alternatives you've considered**

IDK about possible alternatives

**Additional context**

More logs https://github.com/rnpgp/rnp/runs/4222343068

**Comment by CAMOBAP** [comment]
https://github.com/microsoft/vcpkg/issues/21461 - ready for review

**Comment by JackBoosY** [comment]
Why cloes this?

**Comment by CAMOBAP** [comment]
@JackBoosY based on this comment and other suggestions https://github.com/microsoft/vcpkg/pull/21522#issuecomment-974633261

**Comment by dg0yt** [comment]
While I'm still opposed to applying `-fPIC` to static toolchains, the reality is that vcpkg already has `-fPIC` in it its default linux and osx toolchains. This is also passed to builds based on autotools. So the question is if and why botan2 isn't building with the expected flags.
