### ISSUE TITLE
[jsoncpp] Missing usage file

### ISSUE THREAD

**Issue by cglong** [microsoft/vcpkg#21476]
****

**Is your feature request related to a problem? Please describe.**
We're trying to use the **jsoncpp** port and don't see a `usage` file, so I'm not really sure how to consume it in my project.

**Proposed solution**
Add a `usage` file for this port.

**Describe alternatives you've considered**
We're just now starting this work, so we might be able to figure it out on our own; the `usage` files are really helpful for decreasing time spent in investigation though.

**Additional context**
N/A

**Comment by dg0yt** [comment]
Usage info is auto-generated on `vcpkg install jsoncpp`.
~~~
The package jsoncpp provides CMake targets:

    find_package(jsoncpp CONFIG REQUIRED)
    target_link_libraries(main PRIVATE jsoncpp_object jsoncpp_static)
~~~

However, autogenerated usage instructions may be wrong. (Here, the `json_object` item seems strange. And it is unfortunate that they don't use a namespace.) 
Ideally, you find the usage in upstream's documentation.

**Comment by cglong** [comment]
Thank you @dg0yt; we're pretty new to vcpkg, so sorry I didn't know they get autogenerated. We'll try these usage instructions and I'll update here on our findings 🙂

**Comment by JonLiu1993** [comment]
@cglong ,Have you find the usage in upstream?

**Comment by cglong** [comment]
Hi @JonLiu1993, thank you for following up! After installing the package, we did get these instructions as @dg0yt mentioned:

    find_package(jsoncpp CONFIG REQUIRED)
    target_link_libraries(${library_name} jsoncpp_lib jsoncpp_object)

However, we're now receiving these errors. Do you happen to know what could be causing this?

     error LNK2019: unresolved external symbol "public: class Json::Value & __cdecl Json::Value::operator=(class Json::Value)" (??4Value@Json@@QEAAAEAV01@V01@@Z) referenced in function "[snip]"
     error LNK2001: unresolved external symbol "public: class Json::Value & __cdecl Json::Value::operator=(class Json::Value)" (??4Value@Json@@QEAAAEAV01@V01@@Z)
     error LNK2001: unresolved external symbol "public: class Json::Value & __cdecl Json::Value::operator=(class Json::Value)" (??4Value@Json@@QEAAAEAV01@V01@@Z)
     error LNK2001: unresolved external symbol "public: class Json::Value & __cdecl Json::Value::operator=(class Json::Value)" (??4Value@Json@@QEAAAEAV01@V01@@Z)

**Comment by JonLiu1993** [comment]
@cglong ,Thanks for your feedback, could you please provide your CMakeLists.txt and main.cpp to repo this issue? I created a cmake project using jsoncpp locally,  and it use  successfully.

The repro steps:

1. ./vcpkg install jsoncpp:x64-windows 
2. ./vcpkg integrate install
3. create cmake project:

CMakeLists.txt:
````
cmake_minimum_required(VERSION 3.0)
project(test)

find_package(jsoncpp CONFIG 1.9.5 REQUIRED)

add_executable(main main.cpp)

target_link_libraries(main PRIVATE jsoncpp_lib jsoncpp_object JsonCpp::JsonCpp)
````

main.cpp:
````
#include "json/json.h"

using namespace std;

int main()
{
	return 0;
}
````
4.F:\test8\test\build> F:\test8\vcpkg\downloads\tools\cmake-3.21.1-windows\cmake-3.21.1-windows-i386\bin\cmake.exe -DCMAKE_TOOLCHAIN_FILE="F://test8//vcpkg//scripts//buildsystems//vcpkg.cmake" ..
````
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
-- The C compiler identification is MSVC 19.29.30137.0
-- The CXX compiler identification is MSVC 19.29.30137.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: F:/test8/test/build
````
5.F:\test8\test\build> F:\test8\vcpkg\downloads\tools\cmake-3.21.1-windows\cmake-3.21.1-windows-i386\bin\cmake.exe --build .
````
Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  Building Custom Rule F:/test8/test/CMakeLists.txt
  main.cpp
     Creating library F:/test8/test/build/Debug/main.lib and object F:/test8/test/build/Debug/main.exp
  main.vcxproj -> F:\test8\test\build\Debug\main.exe
  Building Custom Rule F:/test8/test/CMakeLists.txt
````

**Comment by JonLiu1993** [comment]
@cglong ,Is this problem solved?

**Comment by JonLiu1993** [comment]
Thanks for posting this issue. Please reopen this issue if it still be a problem for you.
