### ISSUE TITLE
[Building package boost-build:x64-windows failed] build failure

### ISSUE THREAD

**Issue by tesszts** [microsoft/vcpkg#21487]
**Host Environment**
- OS: Windows 11
- Compiler: Visual Studio Community 2022

**To Reproduce**
`./vcpkg install cgal`

**Failure logs** 
PS C:\dev\vcpkg> ./vcpkg.exe install cgal
Computing installation plan...
The following packages will be built and installed:
  * boost-accumulators[core]:x86-windows -> 1.77.0
  * boost-algorithm[core]:x86-windows -> 1.77.0
  * boost-align[core]:x86-windows -> 1.77.0
  * boost-any[core]:x86-windows -> 1.77.0
  * boost-atomic[core]:x86-windows -> 1.77.0
  * boost-bimap[core]:x86-windows -> 1.77.0
  * boost-build[core]:x64-windows -> 1.77.0
  * boost-callable-traits[core]:x86-windows -> 1.77.0
  * boost-chrono[core]:x86-windows -> 1.77.0
  * boost-compute[core]:x86-windows -> 1.77.0
  * boost-container[core]:x86-windows -> 1.77.0
  * boost-date-time[core]:x86-windows -> 1.77.0
  * boost-dynamic-bitset[core]:x86-windows -> 1.77.0
  * boost-endian[core]:x86-windows -> 1.77.0
  * boost-exception[core]:x86-windows -> 1.77.0
  * boost-filesystem[core]:x86-windows -> 1.77.0
  * boost-foreach[core]:x86-windows -> 1.77.0
  * boost-format[core]:x86-windows -> 1.77.0
  * boost-functional[core]:x86-windows -> 1.77.0
  * boost-geometry[core]:x86-windows -> 1.77.0
  * boost-graph[core]:x86-windows -> 1.77.0
  * boost-heap[core]:x86-windows -> 1.77.0
  * boost-interval[core]:x86-windows -> 1.77.0
  * boost-intrusive[core]:x86-windows -> 1.77.0
  * boost-iostreams[bzip2,core,lzma,zlib,zstd]:x86-windows -> 1.77.0#1
  * boost-lambda[core]:x86-windows -> 1.77.0
  * boost-lexical-cast[core]:x86-windows -> 1.77.0
  * boost-logic[core]:x86-windows -> 1.77.0
  * boost-math[core]:x86-windows -> 1.77.0
  * boost-modular-build-helper[core]:x64-windows -> 1.77.0#4
  * boost-multi-index[core]:x86-windows -> 1.77.0
  * boost-multiprecision[core]:x86-windows -> 1.77.0
  * boost-phoenix[core]:x86-windows -> 1.77.0
  * boost-polygon[core]:x86-windows -> 1.77.0
  * boost-pool[core]:x86-windows -> 1.77.0
  * boost-property-map[core]:x86-windows -> 1.77.0
  * boost-property-tree[core]:x86-windows -> 1.77.0
  * boost-proto[core]:x86-windows -> 1.77.0
  * boost-ptr-container[core]:x86-windows -> 1.77.0
  * boost-qvm[core]:x86-windows -> 1.77.0
  * boost-random[core]:x86-windows -> 1.77.0
  * boost-range[core]:x86-windows -> 1.77.0
  * boost-ratio[core]:x86-windows -> 1.77.0
  * boost-rational[core]:x86-windows -> 1.77.0
  * boost-regex[core]:x86-windows -> 1.77.0
  * boost-serialization[core]:x86-windows -> 1.77.0
  * boost-spirit[core]:x86-windows -> 1.77.0
  * boost-system[core]:x86-windows -> 1.77.0
  * boost-thread[core]:x86-windows -> 1.77.0
  * boost-tokenizer[core]:x86-windows -> 1.77.0
  * boost-tti[core]:x86-windows -> 1.77.0
  * boost-ublas[core]:x86-windows -> 1.77.0
  * boost-uninstall[core]:x64-windows -> 1.77.0
  * boost-units[core]:x86-windows -> 1.77.0
  * boost-unordered[core]:x86-windows -> 1.77.0
  * boost-uuid[core]:x86-windows -> 1.77.0
  * boost-variant[core]:x86-windows -> 1.77.0
  * boost-variant2[core]:x86-windows -> 1.77.0
  * boost-xpressive[core]:x86-windows -> 1.77.0
  * bzip2[core]:x86-windows -> 1.0.8#2
    cgal[core]:x86-windows -> 5.3
  * gmp[core]:x86-windows -> 6.2.1#7
  * liblzma[core]:x86-windows -> 5.2.5#4
  * mpfr[core]:x86-windows -> 4.1.0#1
  * vcpkg-cmake[core]:x64-windows -> 2021-09-13
  * vcpkg-cmake-config[core]:x64-windows -> 2021-11-01
  * vs-yasm[core]:x64-windows -> 0.5.0#1
  * yasm-tool[core]:x64-windows -> 1.3.0
  * zlib[core]:x86-windows -> 1.2.11#13
  * zstd[core]:x86-windows -> 1.5.0#1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Detecting compiler hash for triplet x86-windows...
Restored 1 packages from C:\Users\Tess Zheng\AppData\Local\vcpkg\archives in 31.84 ms. Use --debug to see more details.
Starting package 1/70: boost-uninstall:x64-windows
Installing package boost-uninstall[core]:x64-windows...
Elapsed time for package boost-uninstall:x64-windows: 10.37 ms
Starting package 2/70: boost-build:x64-windows
Building package boost-build[core]:x64-windows...
-- Using cached boostorg-build-boost-1.77.0.tar.gz.
-- Cleaning sources at C:/dev/vcpkg/buildtrees/boost-build/src/ost-1.77.0-b7eff2b3a0.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/dev/vcpkg/downloads/boostorg-build-boost-1.77.0.tar.gz
-- Using source at C:/dev/vcpkg/buildtrees/boost-build/src/ost-1.77.0-b7eff2b3a0.clean
-- Using cached boost_LICENSE_1_0.txt.
-- Using cached boost-1.77.0-boostcpp.jam.
-- Installing: C:/dev/vcpkg/packages/boost-build_x64-windows/share/boost-build/copyright
-- Bootstrapping...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: C:/dev/vcpkg/packages/boost-build_x64-windows/tools/boost-build/bootstrap.bat msvc
    Working Directory: C:/dev/vcpkg/packages/boost-build_x64-windows/tools/boost-build
    Error code: 1
    See logs for more information:
      C:\dev\vcpkg\buildtrees\boost-build\bootstrap-x64-windows-out.log
      C:\dev\vcpkg\buildtrees\boost-build\bootstrap-x64-windows-err.log

Call Stack (most recent call first):
  ports/boost-build/portfile.cmake:61 (vcpkg_execute_required_process)
  scripts/ports.cmake:142 (include)

Error: Building package boost-build:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  package: boost-build[core]:x64-windows -> 1.77.0
  vcpkg version: a4b5cde7f 2021-11-16 (5 hours ago)
  vcpkg-tool version: 2021-11-15-ec76affcc987efbf172b7da0b05df711b48fa535

Additionally, attach any relevant sections from the log files above.

**Comment by PhoebeHui** [comment]
@tesszts, could you attach the following failure logs?

C:\dev\vcpkg\buildtrees\boost-build\bootstrap-x64-windows-out.log
C:\dev\vcpkg\buildtrees\boost-build\bootstrap-x64-windows-err.log

**Comment by tesszts** [comment]
##below is output log


Building the B2 engine..
Call_If_Exists "bin\VCVARS32.BAT"
###
### Using 'msvc' toolset.
###

C:\dev\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine>"cl" /nologo /MP /MT /TP /Feb2 /wd4996 /O2 /GL /EHsc   -DNDEBUG  builtins.cpp class.cpp command.cpp compile.cpp constants.cpp cwd.cpp debug.cpp debugger.cpp execcmd.cpp execnt.cpp execunix.cpp filent.cpp filesys.cpp fileunix.cpp frames.cpp function.cpp glob.cpp hash.cpp hcache.cpp hdrmacro.cpp headers.cpp jam.cpp jamgram.cpp lists.cpp make.cpp make1.cpp md5.cpp mem.cpp modules.cpp native.cpp object.cpp option.cpp output.cpp parse.cpp pathnt.cpp pathsys.cpp pathunix.cpp regexp.cpp rules.cpp scan.cpp search.cpp jam_strings.cpp startup.cpp subst.cpp sysinfo.cpp timestamp.cpp variable.cpp w32_getreg.cpp modules/order.cpp modules/path.cpp modules/property-set.cpp modules/regex.cpp modules/sequence.cpp modules/set.cpp /link kernel32.lib advapi32.lib user32.lib 
builtins.cpp
class.cpp
command.cpp
compile.cpp
constants.cpp
cwd.cpp
debug.cpp
debugger.cpp
C:\dev\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file builtins.cpp)
C:\dev\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file compile.cpp)
C:\dev\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file command.cpp)
execcmd.cpp
execnt.cpp
execunix.cpp
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\include\yvals.h(12): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory (compiling source file constants.cpp)
C:\dev\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file debug.cpp)
filent.cpp
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\include\yvals.h(12): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory (compiling source file class.cpp)
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\include\yvals.h(12): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory (compiling source file cwd.cpp)
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\include\yvals.h(12): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory (compiling source file debugger.cpp)
filesys.cpp
fileunix.cpp
frames.cpp
function.cpp
C:\dev\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file execunix.cpp)
C:\dev\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file execcmd.cpp)
C:\dev\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file execnt.cpp)
C:\dev\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file filent.cpp)
glob.cpp
hash.cpp
C:\dev\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file filesys.cpp)
hcache.cpp
hdrmacro.cpp
headers.cpp
C:\dev\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file fileunix.cpp)
C:\dev\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file frames.cpp)
C:\dev\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file function.cpp)
jam.cpp
jamgram.cpp
lists.cpp
C:\dev\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file hdrmacro.cpp)
make.cpp
C:\dev\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file jam.cpp)
make1.cpp
C:\dev\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file hcache.cpp)
md5.cpp
C:\dev\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file glob.cpp)
C:\dev\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file hash.cpp)
C:\dev\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file jamgram.cpp)
mem.cpp
C:\dev\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file headers.cpp)
modules.cpp
native.cpp
C:\dev\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file lists.cpp)
object.cpp
option.cpp
C:\dev\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\md5.h(53): fatal error C1083: Cannot open include file: 'stddef.h': No such file or directory (compiling source file md5.cpp)
C:\dev\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file make.cpp)
output.cpp
parse.cpp
C:\dev\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file make1.cpp)
pathnt.cpp
C:\dev\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file mem.cpp)
C:\dev\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file modules.cpp)
C:\dev\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file option.cpp)
pathsys.cpp
pathunix.cpp
C:\dev\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file object.cpp)
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\include\yvals.h(12): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory (compiling source file native.cpp)
regexp.cpp
rules.cpp
scan.cpp
C:\dev\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file output.cpp)
search.cpp
C:\dev\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file parse.cpp)
C:\dev\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file pathnt.cpp)
jam_strings.cpp
startup.cpp
C:\dev\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file pathunix.cpp)
C:\dev\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file pathsys.cpp)
subst.cpp
C:\dev\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file rules.cpp)
sysinfo.cpp
C:\dev\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file regexp.cpp)
C:\dev\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file scan.cpp)
timestamp.cpp
variable.cpp
w32_getreg.cpp
C:\dev\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file search.cpp)
order.cpp
C:\dev\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file jam_strings.cpp)
path.cpp
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\include\yvals.h(12): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory (compiling source file startup.cpp)
C:\dev\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file subst.cpp)
property-set.cpp
C:\dev\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file sysinfo.cpp)
C:\dev\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file variable.cpp)
C:\dev\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file w32_getreg.cpp)
C:\dev\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file timestamp.cpp)
regex.cpp
sequence.cpp
set.cpp
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\include\yvals.h(12): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory (compiling source file modules/order.cpp)
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\include\yvals.h(12): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory (compiling source file modules/path.cpp)
C:\dev\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\modules\../mem.h(14): fatal error C1083: Cannot open include file: 'stdlib.h': No such file or directory (compiling source file modules/regex.cpp)
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\include\yvals.h(12): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory (compiling source file modules/property-set.cpp)
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\include\yvals.h(12): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory (compiling source file modules/sequence.cpp)
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\include\yvals.h(12): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory (compiling source file modules/set.cpp)

C:\dev\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine>dir *.exe 
 Volume in drive C is Windows
 Volume Serial Number is CA68-06FE

 Directory of C:\dev\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine


C:\dev\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine>copy /b .\b2.exe .\bjam.exe 
The system cannot find the file specified.

Failed to build the B2 engine.

**Comment by tesszts** [comment]
## error log

File Not Found

**Comment by PhoebeHui** [comment]
@tesszts, could you install window sdk via VS installer and try again?

Similar issue https://github.com/microsoft/vcpkg/issues/19544.

**Comment by tesszts** [comment]
YES,It works. Thankyou!
