### ISSUE TITLE
python3 in ARM cannot be build due to too restrictive support entry

### ISSUE THREAD

**Issue by david-antiteum** [microsoft/vcpkg#21497]
**Describe the bug**

Too restrictive support entry in python3 port (and other ports) prevents to build this package/s in ARM system (macOS M1, Linux ARM64). 

The entry says:

  "supports": "!(arm | uwp)",

But, if arm is removed, it compiles and works just fine.

This problem affects other packages too.

Maybe related: #21474

**Environment**
- OS: Ubuntu 20 ARM64 (Linux 5.4.0-90-generic # 101-Ubuntu SMP Fri Oct 15 20:02:26 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux)
- Compiler: gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

**To Reproduce**
1. ./vcpkg install python3
2. See error
Error: python3[core] is only supported on '!(arm | uwp)'

**Expected behavior**

A compilation :)

**Comment by NancyLi1013** [comment]
Hi @david-antiteum

Thanks for posting this issue.

Currently, vcpkg only supports `arm `on Windows. So generally, we only consider the value of the `supports `for the official triplets.

Could you please help test if `"supports": "!uwp & !(windows & arm)",` can work fine for you?

**Comment by david-antiteum** [comment]
Hi @NancyLi1013 

Yes, your change works for me.

Thanks
