### ISSUE TITLE
[qt5-base] find_qt_mkspec.cmake in qt5-base will use g++ without detecting compiler

### ISSUE THREAD

**Issue by 0x8A63F77D** [microsoft/vcpkg#21492]
**Describe the bug**

https://github.com/microsoft/vcpkg/blob/a4b5cde7f504c1bbbbc455f4a6ee60efd9034772/ports/qt5-base/cmake/find_qt_mkspec.cmake#L25-L26

**Comment by Neumann-A** [comment]
set `VCPKG_QT_TARGET_MKSPEC` in the triplet to the mkspec you want to use. 
The stuff was written well before there was a function to extra compiler ids and flags from cmake.,

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
