### ISSUE TITLE
[luacom] add C++ library

### ISSUE THREAD

**Issue by Eunsolfs** [microsoft/vcpkg#21495]
I‘m using a extra component of lua ,it's name is (["luacom"](https://github.com/davidm/luacom))，but I can't get this component  from vcpkg.It would be great if this component can be added to vcpkg!
***
LuaCOM is an additional library for Lua language <(http://www.lua.org)>
Allow Lua programs to use and implement the following objects Microsoft’s Component Object Model (COM) specification and ActiveX technology for attribute access and method invocation.

LuaCOM is implemented as a C++ library and can be statically linked to Application or load at runtime. LuaCOM provides its source code And the makefile needed to build it.

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
