### ISSUE TITLE
[libsigcpp] include failure

### ISSUE THREAD

**Issue by jhndnnqsc** [microsoft/vcpkg#21496]
**Describe the bug**
Installation of libsigcpp puts include files in sigc++-3.0/sigc++/ so to include
`#include <sigc++-3.0/sigc++/connection.h>` is required. The issue is that internally in the library things are included with `<sigc++config.h>` and ` <sigc++/functors/slot_base.h>`. ` sigc++config.h` is not included in the port and even if it was the next include would fail since it doesn't have sigc++3.0 in the path.

**Environment**
- OS: Win10
- Compiler: VS 2019

**To Reproduce**
1. ./vcpkg install libsigcpp
2. Compile code
3. Compile fails

Code is 
```
#include <iostream>
#include <sigc++-3.0/sigc++/connection.h>
int main()
{
    std::cout << "Hello World!\n";
}
```

connection.h includes look like
```
#ifndef SIGC_CONNECTION_HPP
#define SIGC_CONNECTION_HPP
#include <sigc++config.h>
#include <sigc++/functors/slot_base.h>
#include <sigc++/weak_raw_ptr.h>
```

**Expected behavior**
Code should compile without errors

**Failure logs** 
```
Rebuild started...
1>------ Rebuild All started: Project: ConsoleApplication1, Configuration: Debug Win32 ------
1>ConsoleApplication1.cpp
1>C:\code\vcpkg\installed\x86-windows\include\sigc++-3.0\sigc++\connection.h(21,10): fatal error C1083: Cannot open include file: 'sigc++config.h': No such file or directory
1>Done building project "ConsoleApplication1.vcxproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
```

Note failure occurs with both x64 and x86 builds.

**Comment by IshaanKarnik** [comment]
I am facing the same issue.

**Comment by JackBoosY** [comment]
I will handle this issue today.

**Comment by JackBoosY** [comment]
In the test code:
```cpp
#include <sigc++/sigc++.h>
```
So the include path should be _include/sigc++_.
In _SOURCE/CMakeLists.txt_ line 105:
```cmake
set (LIBSIGCXX_INCLUDE_DIR	"${CMAKE_INSTALL_PREFIX}/lib/${PROJECT_NAME}-${SIGCXX_API_VERSION}/include")
```
Therefore, I think this is a upstream bug.


And for the config header `sigc++config.h`, it should be installed in _include_ directly since some other header directly include it without any path.

**Comment by JackBoosY** [comment]
Let's wait for the upstream reply first.

**Comment by JackBoosY** [comment]
The upstream rejected my suggestion. I think we should fix this on the vcpkg side.

**Comment by jhndnnqsc** [comment]
Is there any plan to address this? I just retried with the latest and got the same result.

**Comment by sfhacker** [comment]
This open issue is nearly one year old!
Can we afford such a long time?
@jhndnnqsc How can we better assist you?

**Comment by xiaozhuai** [comment]
No, this not a bug, you should use it with pkg-config.
```cmake
find_package(PkgConfig REQUIRED)
pkg_search_module(LIBSIGCPP REQUIRED sigc++ sigc++-3.0)
target_include_directories(main PRIVATE "${LIBSIGCPP_INCLUDE_DIRS}")
target_link_libraries(main PRIVATE "${LIBSIGCPP_LINK_LIBRARIES}")
```
