### ISSUE TITLE
[sdl2] CMake linker error with libX11 and SDL2 on x64-linux

### ISSUE THREAD

**Issue by Cleptomania** [microsoft/vcpkg#21526]
**Host Environment**
- OS: Arch Linux (Linux 5.15.2-arch1-1)
- Compiler: GCC 11.1.0
- vcpkg HEAD: cbc22a396c88d098247fe7f79f0913a952e1f77d

**To Reproduce**
I'm using vcpkg in manifest mode with the following files:

vcpkg.json:

```json
{
    "name": "test-project",
    "version": "0.0.1",
    "dependencies": [
        "sdl2"
    ]
}
```

CMakeLists.txt:

```
cmake_minimum_required(VERSION 3.0.0)

project(MyTestProject VERSION 0.0.1)

find_package(SDL2 REQUIRED)

add_executable(MyTestProject src/main.cpp)

TARGET_LINK_LIBRARIES(MyTestProject SDL2::SDL2 SDL2::SDL2main)
```

src/main.cpp:

```c++
#include <SDL2/SDL.h>
#include <stdio.h>

#define SCREEN_WIDTH 640
#define SCREEN_HEIGHT 480

int main(int argc, char *args[])
{
    SDL_Window *window = NULL;
    SDL_Surface *screenSurface = NULL;
    if (SDL_Init(SDL_INIT_VIDEO) < 0)
    {
        fprintf(stderr, "could not initialize sdl2: %s\n", SDL_GetError());
        return 1;
    }
    window = SDL_CreateWindow(
        "hello_sdl2",
        SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED,
        SCREEN_WIDTH, SCREEN_HEIGHT,
        SDL_WINDOW_SHOWN);
    if (window == NULL)
    {
        fprintf(stderr, "could not create window: %s\n", SDL_GetError());
        return 1;
    }
    screenSurface = SDL_GetWindowSurface(window);
    SDL_FillRect(screenSurface, NULL, SDL_MapRGB(screenSurface->format, 0xFF, 0xFF, 0xFF));
    SDL_UpdateWindowSurface(window);
    SDL_Delay(2000);
    SDL_DestroyWindow(window);
    SDL_Quit();
    return 0;
}
```

**Failure logs** 

This results in a linker error like below:

```
[build] Consolidate compiler generated dependencies of target MyTestProject
[build] [ 50%] Building CXX object CMakeFiles/MyTestProject.dir/src/main.cpp.o
[build] [100%] Linking CXX executable MyTestProject
[build] /usr/bin/ld: vcpkg_installed/x64-linux/debug/lib/libSDL2d.a(SDL_x11dyn.c.o): undefined reference to symbol 'XPending'
[build] /usr/bin/ld: /usr/lib/libX11.so.6: error adding symbols: DSO missing from command line
[build] collect2: error: ld returned 1 exit status
[build] make[2]: *** [CMakeFiles/MyTestProject.dir/build.make:105: MyTestProject] Error 1
[build] make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/MyTestProject.dir/all] Error 2
[build] make: *** [Makefile:91: all] Error 2
[build] Build finished with exit code 2
```

**Additional context**
I've verified that my system has libX11, any research on this particular linker error is just telling me to add `-lX11` to the GCC compile command, but with CMake I'm not quite sure how that translates, and the linker error appears to come from SDL's cmake config, so I'm not too sure where to go from there.

I've tested this exact same build on Windows with VS Enterprise 2019 compiler and it works without issue, the problem is isolated to building on Linux with X11.

**Comment by Cleptomania** [comment]
I have solved my own problems. Though hopefully this will help someone else as I couldn't find a super clear explanation of how this worked anywhere.

SDL2 in vcpkg has the x11 feature available by installing `sdl2[x11]`, however you can only install this feature on a Linux host, so it's not suitable to use as a dependency for a cross platform application.

I ended up solving this, and keeping full cross platform support by modifying my `vcpkg.json` to the following to force x11 installation on Linux but just use core on Windows:

```json
{
    "name": "test-project",
    "version": "0.0.1",
    "dependencies": [
        {
            "name": "sdl2",
            "features": [ "x11" ],
            "platform": "linux"
        },
        {
            "name": "sdl2",
            "platform": "!linux"
        }
    ]
}
```

**Comment by dg0yt** [comment]
IIUC, you are not using just core but the default features on Windows. To use default feaures everywhere, plus x11 on linux, it should look app. like this:
~~~
{
    "name": "test-project",
    "version": "0.0.1",
    "dependencies": [
        "sdl2",
        {
            "name": "sdl2",
            "default-features": false,
            "features": [ "x11" ],
            "platform": "linux"
        }
    ]
}
~~~

**Comment by Raffaello** [comment]
Besides isn't it an error? 
shouldn't run "out of the box" just the "sdl2" core for linux without explicitly installing sdl[x11] package?

**Comment by NekkoDroid** [comment]
Is there any info/update on a fix to this issue (other than the workaround)?
It seems to still be a problem when I tested on my linux system.
