### ISSUE TITLE
vcpkg dlls only copied in release profile CMAKE builds, debug profile builds unable to run

### ISSUE THREAD

**Issue by 7Redacted** [microsoft/vcpkg#21523]
I've just started using vcpkg -- it seems like a well designed, super useful tool!

I've noticed a peculiar issue. I put together a simple project using Visual Studio 2022, vcpkg and cmake to illustrate it. First I installed libgit2 to my project:

`vcpkg install libgit2:x64-windows`

Next, wrote the following into my CMake file:

```
cmake_minimum_required (VERSION 3.8)

project ("vcpkg-cmake-x64-dbg-release-issue")

find_path(LIBGIT2_INCLUDE_DIR git2.h REQUIRED)
find_library(LIBGIT2_LIBRARY git2 REQUIRED)

# Add source to this project's executable.
add_executable (vcpkg-cmake-x64-dbg-release-issue "vcpkg-cmake-x64-dbg-release-issue.cpp")

target_include_directories(vcpkg-cmake-x64-dbg-release-issue PRIVATE ${LIBGIT2_INCLUDE_DIR})
target_link_libraries(vcpkg-cmake-x64-dbg-release-issue ${LIBGIT2_LIBRARY})
```

And finally, the following cpp file:

```
#include <iostream>
#include <git2.h>

using namespace std;

int main()
{
	cout << "Hello CMake." << endl;
	git_libgit2_init();
	git_libgit2_shutdown();
	return 0;
}
```

This compiles and runs when using an x64-Release profile, copying the DLLS needed for execution into the build directory: git2.dll, pcre.dll, zlib1.dll

However, when using an x64-Debug profile, the pcre.dll is not copied to the build directory. This causes any attempt to run or debug the generated .exe to fail.

My CMakeSettings.json file appears to show these two configurations are identical (aside from the configurationType):

```
{
  "configurations": [
    {
      "name": "x64-Debug",
      "generator": "Ninja",
      "configurationType": "Debug",
      "inheritEnvironments": [ "msvc_x64_x64" ],
      "buildRoot": "${projectDir}\\out\\build\\${name}",
      "installRoot": "${projectDir}\\out\\install\\${name}",
      "cmakeCommandArgs": "",
      "buildCommandArgs": "",
      "ctestCommandArgs": "",
      "cmakeToolchain": "C:/Users/Steph/source/vcpkg/scripts/buildsystems/vcpkg.cmake"
    },
    {
      "name": "x64-Release",
      "generator": "Ninja",
      "configurationType": "RelWithDebInfo",
      "buildRoot": "${projectDir}\\out\\build\\${name}",
      "installRoot": "${projectDir}\\out\\install\\${name}",
      "cmakeCommandArgs": "",
      "buildCommandArgs": "",
      "ctestCommandArgs": "",
      "inheritEnvironments": [ "msvc_x64_x64" ],
      "cmakeToolchain": "C:/Users/Steph/source/vcpkg/scripts/buildsystems/vcpkg.cmake"
    }
  ]
}
```

I've also seen similar problems to this when using other vcpkg libraries: certain dlls are only copied over in the release profile. Has anyone seen any issues like this or have an idea of what could be causing it?

**Comment by 7Redacted** [comment]
@LilyWangLL -- I see the issue was tagged with the label "the issue is not currently repro-able".

Is there anything I can do to help reproduce the problem? I can provide project files or reproduce the issue in an environment that more closely matches yours.

**Comment by LilyWangLL** [comment]
Sorry I am late, I can reproduce this issue locally. I will confirm this issue and resolve it soon.
