### ISSUE TITLE
[<influxdb-cxx>] build failure

### ISSUE THREAD

**Issue by MlovehebeE** [microsoft/vcpkg#21532]
PS D:\vcpkgmanage\vcpkg> .\vcpkg.exe install influxdb-cxx:x64-windows
Computing installation plan...
The following packages will be built and installed:
    influxdb-cxx[core]:x64-windows -> 0.6.7
Detecting compiler hash for triplet x64-windows...
Restored 0 packages from C:\Users\q8718tiny\AppData\Local\vcpkg\archives in 251.1 us. Use --debug to see more details.
Starting package 1/1: influxdb-cxx:x64-windows
Building package influxdb-cxx[core]:x64-windows...
-- Using cached offa-influxdb-cxx-v0.6.7.tar.gz.
-- Cleaning sources at D:/vcpkgmanage/vcpkg/buildtrees/influxdb-cxx/src/v0.6.7-1d6a39a436.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/vcpkgmanage/vcpkg/downloads/offa-influxdb-cxx-v0.6.7.tar.gz
-- Using source at D:/vcpkgmanage/vcpkg/buildtrees/influxdb-cxx/src/v0.6.7-1d6a39a436.clean
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: ninja -v
    Working Directory: D:/vcpkgmanage/vcpkg/buildtrees/influxdb-cxx/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\vcpkgmanage\vcpkg\buildtrees\influxdb-cxx\config-x64-windows-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:411 (vcpkg_execute_required_process)
  ports/influxdb-cxx/portfile.cmake:14 (vcpkg_cmake_configure)
  scripts/ports.cmake:142 (include)

Error: Building package influxdb-cxx:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  package: influxdb-cxx[core]:x64-windows -> 0.6.7
  vcpkg version: cbc22a396 2021-11-17 (30 hours ago)
  vcpkg-tool version: 2021-11-15-ec76affcc987efbf172b7da0b05df711b48fa535

Additionally, attach any relevant sections from the log files above.

**Comment by JonLiu1993** [comment]
@MlovehebeE ,Thanks for posting this issue, could you please provide the error log:
````
D:\vcpkgmanage\vcpkg\buildtrees\influxdb-cxx\config-x64-windows-out.log
````

**Comment by JonLiu1993** [comment]
@MlovehebeE ,Can you install this port successfully?

**Comment by JonLiu1993** [comment]
@MlovehebeE ,Has this problem been sloved?

**Comment by JonLiu1993** [comment]
Thanks for posting this issue. Please reopen this issue if it still be a problem for you.
