### ISSUE TITLE
vcpkg_install_qmake doesn't install pkgconfig files

### ISSUE THREAD

**Issue by MehdiChinoune** [microsoft/vcpkg#21533]
****

**Is your feature request related to a problem? Please describe.**
Some qmake-buildsystem projects generate pkgconfig files *.pc to be installed and then used by other projects. Those files are not installed by vcpkg_install_qmake

**Proposed solution**
Install *.pc files to the right destination.

**Describe alternatives you've considered**
Nothing

**Additional context**
I have encountered that issue with qwt which generates and installs a pkgconfig file that help cmake finding it easier.

**Comment by JackBoosY** [comment]
cc @Neumann-A

**Comment by JackBoosY** [comment]
Why close this?

**Comment by MehdiChinoune** [comment]
Because I don't like to have open issues won't be fixed sooner.

**Comment by JackBoosY** [comment]
I think we should consider this issue. Please keep this issue open until we fix it.

**Comment by MehdiChinoune** [comment]
> I think we should consider this issue. Please keep this issue open until we fix it.

When?

**Comment by Neumann-A** [comment]
personally i think this is a setting the port itself needs to provide. 
In qwt for example there is:
`CONFIG     += create_pc create_prl no_install_prl`
but only if 
`contains(QWT_CONFIG, QwtPkgConfig)`
so for me it seems not like something `vcpkg_install_qmake` needs to support 
(also Qt5 install pc files and is using vcpkg_install_qmake internally)
