### ISSUE TITLE
How can my colleagues import  libraries into their own vcpkg

### ISSUE THREAD

**Issue by zzandyc** [microsoft/vcpkg#21551]
I have exported some libraries with extension 7z using export function. How can my colleagues import these libraries into their own vcpkg and view them using vcpkg list

**Comment by JackBoosY** [comment]
We recommend that you use export to export nuget packages and use nuget to import them in Visual Studio.
To use the exported 7z packages, you may need to manually decompress them and set the corresponding include path and link path.
For better, you can use feature binarycaching to manage these binaries. See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/specifications/binarycaching.md).

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
