### ISSUE TITLE
[boost] Wrong library names (not following boost's naming convention)

### ISSUE THREAD

**Issue by edo9300** [microsoft/vcpkg#21562]
****

**Is your feature request related to a problem? Please describe.**
Currently the names of the generated boost libraries for windows aren't following [boost's library naming convention](https://www.boost.org/doc/libs/1_77_0/more/getting_started/windows.html#library-naming). When the libraries are statically linked to the runtime, their filename should have the ``-s`` ABI tag, something which is currently not done. Also [the naming convention](https://www.boost.org/doc/libs/1_77_0/more/getting_started/windows.html#distinct) states that on Windows to differentiate import libraries and static libraries both with ``.lib`` extension, the import libraries should named ``boost_xxx.lib`` and the static libraries ``libboost_xxx.lib``, which also is not being done currently.
For example, a statically built ``boost filesystem`` library currently is being generated as ``boost_filesystem-vc140-mt.lib``, when it should be ``libboost_filesystem-vc140-mt-s.lib``

**Proposed solution**
Add a prefix tag for the boost libraries so that it expands to ``lib`` when the library is built statically under Windows, also add the proper ``-s`` tag in https://github.com/microsoft/vcpkg/blob/709e9ec32e27319636c047a38744e1ce0e229ae4/ports/boost-modular-build-helper/boost-modular-build.cmake#L38-L46
when the libraries are linked to the static runtime.

**Comment by PhoebeHui** [comment]
This is intended behavior, see https://github.com/microsoft/vcpkg/issues/1338#issuecomment-313243813.
