### ISSUE TITLE
folly on Windows CMake Error BUILD_FAILED

### ISSUE THREAD

**Issue by danielTechn** [Microsoft/vcpkg#2156]
I execute the following cmd: ( Windows  8.1 vs 15 with Update 3 ) 
C:\vcpkg>./vcpkg install folly:x64-windows
'.' is not recognized as an internal or external command,
operable program or batch file.

C:\vcpkg>.\vcpkg install folly:x64-windows
The following packages will be built and installed:
    folly:x64-windows
Starting package 1/1: folly:x64-windows
Building package folly:x64-windows...
-- CURRENT_INSTALLED_DIR=C:/vcpkg/installed/x64-windows
-- DOWNLOADS=C:/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/vcpkg/packages/folly_x64-windows
-- CURRENT_BUILDTREES_DIR=C:/vcpkg/buildtrees/folly
-- CURRENT_PORT_DIR=C:/vcpkg/ports/folly/.
-- Warning: Dynamic building not supported yet. Building static.
-- Using cached C:/vcpkg/downloads/facebook-folly-v2017.10.02.00.tar.gz
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Applying patch C:/vcpkg/ports/folly/fix-static-linking.diff
-- Applying patch failed. This is expected if this patch was previously applied.

-- Applying patch C:/vcpkg/ports/folly/fix-static-linking.diff done
-- Applying patch C:/vcpkg/ports/folly/fix-malloc.diff
-- Applying patch failed. This is expected if this patch was previously applied.

-- Applying patch C:/vcpkg/ports/folly/fix-malloc.diff done
-- Applying patch C:/vcpkg/ports/folly/fix-MSG_ERRQUEUE.diff
-- Applying patch failed. This is expected if this patch was previously applied.

-- Applying patch C:/vcpkg/ports/folly/fix-MSG_ERRQUEUE.diff done
-- Applying patch C:/vcpkg/ports/folly/fix-histogram.diff
-- Applying patch failed. This is expected if this patch was previously applied.

-- Applying patch C:/vcpkg/ports/folly/fix-histogram.diff done
-- Configuring x64-windows-rel
-- Configuring x64-windows-rel done
-- Configuring x64-windows-dbg
-- Configuring x64-windows-dbg done
-- Build x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:43 (message):
    Command failed: C:/vcpkg/downloads/cmake-3.9.5-win32-x86/bin/cmake.exe;--bui
ld;.;--config;Release;--target;install;--;-v
    Working Directory: C:/vcpkg/buildtrees/folly/x64-windows-rel
    See logs for more information:
      C:\vcpkg\buildtrees\folly\install-x64-windows-rel-out.log
      C:\vcpkg\buildtrees\folly\install-x64-windows-rel-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:62 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/folly/portfile.cmake:51 (vcpkg_install_cmake)
  scripts/ports.cmake:72 (include)

Error: Building package folly:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: folly:x64-windows
  Vcpkg version: 0.0.96-2017-11-07-387c5477e5a3c89a560c0c642123aeb9f48dfea3

Additionally, attach any relevant sections from the log files above.

**Comment by ras0219-msft** [comment]
Hi, could you please attach the following logs?
> C:\vcpkg\buildtrees\folly\install-x64-windows-rel-out.log
C:\vcpkg\buildtrees\folly\install-x64-windows-rel-err.log

**Comment by danielTechn** [comment]
yep , thanks
the rel err is empty ...


[install-x64-windows-rel-out.log](https://github.com/Microsoft/vcpkg/files/1463641/install-x64-windows-rel-out.log)

**Comment by BuzaL** [comment]
I've got the same error (except, the callstack, but seems similar).

>   Package: folly:x64-windows
  Vcpkg version: 0.0.99-unknownhash

`Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:63 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/folly/portfile.cmake:51 (vcpkg_install_cmake)
  scripts/ports.cmake:72 (include)`
As I see, Folly has an error:
`C:\project\vcpkg-master\buildtrees\folly\src\head\folly-master\folly\IPAddressV6.cpp(441): error C2666: 'inet_ntop': 2 overloads have similar conversions`

This is the only error in my install/x64/windows/rel/out.log file.

**Comment by JackBoosY** [comment]
Hi @danielTechn @BuzaL  , thanks for post this issue, that's makes vcpkg better!
This issue should be fixed in nearly PR. Can you update and rebuild it?
Thx.

**Comment by BuzaL** [comment]
> Hi @danielTechn @BuzaL , thanks for post this issue, that's makes vcpkg better!
> This issue should be fixed in nearly PR. Can you update and rebuild it?
> Thx.

Sorry, I havn't got that buildsystem and currently not planning to reconstruct it. Thanks the fix anyway.
