### ISSUE TITLE
Error: Building package bzip2:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by JamesBremner** [microsoft/vcpkg#21580]
**Host Environment**
- OS: windows
- Compiler: ???

**To Reproduce**
`vcpkg install tesseract:x64-windows`

**Failure logs** 
-Cut and paste the appropriate build messages from the console output.

```
Starting package 1/19: bzip2:x64-windows
Building package bzip2[core]:x64-windows...
-- Downloading https://sourceware.org/pub/bzip2/bzip2-1.0.8.tar.gz -> bzip2-1.0.8.tar.gz...
-- Extracting source C:/Users/James/code/ext/vcpkg/downloads/bzip2-1.0.8.tar.gz
-- Applying patch fix-import-export-macros.patch
-- Using source at C:/Users/James/code/ext/vcpkg/buildtrees/bzip2/src/bzip2-1-336d4794a3.clean
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: ninja -v
    Working Directory: C:/Users/James/code/ext/vcpkg/buildtrees/bzip2/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\Users\James\code\ext\vcpkg\buildtrees\bzip2\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:345 (vcpkg_execute_required_process)
  ports/bzip2/portfile.cmake:16 (vcpkg_configure_cmake)
  scripts/ports.cmake:142 (include)


Error: Building package bzip2:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  package: bzip2[core]:x64-windows -> 1.0.8#2
  vcpkg version: 709e9ec32 2021-11-19 (2 days ago)
  vcpkg-tool version: 2021-11-15-ec76affcc987efbf172b7da0b05df711b48fa535
```

-Please attach any additional failure logs mentioned in the console output.
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/7576945/config-x64-windows-out.log)

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by JamesBremner** [comment]
Did a git pull abd vcpkg update.

Same problem

E```
rror: Building package bzip2:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  package: bzip2[core]:x64-windows -> 1.0.8#2
  vcpkg version: 653912591 2021-11-21 (58 minutes ago)
  vcpkg-tool version: 2021-11-15-ec76affcc987efbf172b7da0b05df711b48fa535

```

**Comment by LilyWangLL** [comment]
Hi @JamesBremner, thanks for your issue. I found this error `--mt=CMAKE_MT-NOTFOUND` in your error log. This should be you Visual Studio miss some components. Could you check your Visual Studio installer? Like this.
![image](https://user-images.githubusercontent.com/94091114/142831925-7024678d-798e-48fe-89ed-111f6b380e84.png)

**Comment by JamesBremner** [comment]
Thank you for your response.

I have installed Desktop C++.  Your response indicates that I should add "Universal Windows" and ".NET"

Do you realise how much disk space these monsters demand?  The installer indicates a disk space requirement of over 10 GB.

Surely there is a more efficient way to provide vcpkg with access to CMAKE?

**Comment by JamesBremner** [comment]
I took a closer look at the installation details on my machine

![image](https://user-images.githubusercontent.com/2046227/142936911-a1b79654-6b31-45dd-8e6f-532a464d659d.png)

It looks like I should already have CMAKE installed?

**Comment by JamesBremner** [comment]
I installed more supposedly optional parts of the =desktop C++  Specifically

![image](https://user-images.githubusercontent.com/2046227/142942056-93cef108-4f3a-4b97-802f-c3f572fd46b0.png)

The installation is now running and looking good..

I suggest that the vcpkg docs should specify exactly what is needed from visual studio = all I found was a vague mention that visual studio should be installed first.

Other than the documentation improvement, I think this issue can be closed.

**Comment by running-az** [comment]
I also encountered this problem, but it was not resolved using the same method

**Comment by running-az** [comment]
I have also encountered this problem, but it has not been solved by the same method. Is there any other solution?

**Comment by sfhacker** [comment]
This issue … from 2021!

**Comment by JamesBremner** [comment]
I closed this issue in 2021.  Don't know why it is getting so much action.

@running-az This issue is closed.  You should open a new issue for your problem, describing it in detail.
