### ISSUE TITLE
[pcl] error: can't open file 'vtk::hdf5::hdf5.lib'

### ISSUE THREAD

**Issue by darke1891** [Microsoft/vcpkg#2158]
Hi,

I'm using commit `4b5d452` on Windows 7 with VS 2015. In commit `087dc94`, vtk is updated.
Then it failed when I re-install pcl;x64-windows.

The error message in `install-x64-windows-rel-out.log` is as follows:
```
LINK : fatal error LNK1104: cannot open file 'vtk::hdf5::hdf5.lib'
```

Best

**Comment by darke1891** [comment]
commit `318613d` can install pcl correctly.

**Comment by ras0219-msft** [comment]
@UnaNancyOwen

**Comment by UnaNancyOwen** [comment]
@ras0219-msft I confirmed that it works correctly. Thanks,
