### ISSUE TITLE
[zlib] Build error

### ISSUE THREAD

**Issue by NeedCf** [microsoft/vcpkg#21589]
**Host Environment**
- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**
`./vcpkg install xxxx`

**Failure logs** 
-Cut and paste the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by JonLiu1993** [comment]
@NeedCf ,Thanks for posting this issue, please provide your recurring information, OS, Compiler ,recurring steps and error log.

**Comment by NeedCf** [comment]
OS : Win10 20H1
installed vs2022 (C++ developer), vcpkg
error : Error: Building package zlib:x64-windows failed with: BUILD_FAILED
by run : vcpkg install zlib:x64-windows

**Comment by JonLiu1993** [comment]
> OS : Win10 20H1 installed vs2022 (C++ developer), vcpkg error : Error: Building package zlib:x64-windows failed with: BUILD_FAILED by run : vcpkg install zlib:x64-windows

Please provide detail error log

**Comment by NeedCf** [comment]
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/7594457/config-x64-windows-out.log)

**Comment by JonLiu1993** [comment]
@NeedCf  ,Thanks for posting this issue,
Make sure Visual Studio has the following installed:

Desktop Development with C++
One of the Windows SDKs, preferably the latest
English Language Pack
````
CMake Error at D:/BlockChain/vcpkg/downloads/tools/cmake-3.21.1-windows/cmake-3.21.1-windows-i386/share/cmake-3.21/Modules/CMakeTestCCompiler.cmake:69 (message):
  The C compiler

    "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.30.30705/bin/Hostx64/x64/cl.exe"

  is not able to compile a simple test program.
````

**Comment by NeedCf** [comment]
Thanks for helping me. Your guide is really necessary and helpful. Wishing you all the best

**Comment by JonLiu1993** [comment]
@NeedCf , Is this issue solved?

**Comment by PhoebeHui** [comment]
@NeedCf, please reopen this issue if it still be a problem for you.
