### ISSUE TITLE
Error: yasm-tool[core] is only supported on 'native & !uwp'

### ISSUE THREAD

**Issue by szhllyyl** [microsoft/vcpkg#21592]
host:
win10 x64; vs 2019 （MSVC140,  141）

Because of a bug with gmp in vcpkg for windows, i need to install yasm-tool in 32 bits to be able to correctly build gmp 64bits
but it shows the error logs as the title says.

**Comment by PhoebeHui** [comment]
@szhllyyl, what triplets do you install?

**Comment by szhllyyl** [comment]
> @szhllyyl, what triplets do you install?
yasm-tool:x86-windows

**Comment by PhoebeHui** [comment]
@szhllyyl, you can use [overlay ports]( https://github.com/microsoft/vcpkg/blob/master/docs/specifications/ports-overlay.md) and remove 'native&' from https://github.com/microsoft/vcpkg/blob/master/ports/yasm-tool/vcpkg.json#L6, then try again and see if it works for you.

**Comment by szhllyyl** [comment]
I removed ’native&‘ and it works! thanks for your reply!

**Comment by dg0yt** [comment]
Note that you can build "yasm-tool:x86-windows" when the host triplet is x86-windows. Native means target == host. 
However the default vcpkg triplets on x64 machines are host x64-windows, target x86-windows...
