### ISSUE TITLE
[vcpkg-tool] Race condition on accessing .vcpkg-root

### ISSUE THREAD

**Issue by Carbenium** [microsoft/vcpkg#21604]
**Describe the bug**
`vcpkg install` races on the access of `.vcpkg-root` when multiple instances of `vcpkg` are started simultaneously in manifest mode.

**Environment**
- OS: Windows
- Compiler: VS2019 16.11.7
- vcpkg: `2021-11-15-ec76affcc987efbf172b7da0b05df711b48fa535`

**To Reproduce**
1. Create a `vcpkg.json` with contents similar to
```
{
  "$schema": "https://raw.githubusercontent.com/microsoft/vcpkg/master/scripts/vcpkg.schema.json",
  "name": "test",
  "version": "0.1",
  "dependencies": [],
  "builtin-baseline": "1a5075baf8e5a1a10fab6282c18587741dcc155e"
}
```
2. Run two instances of `vcpkg install` simultaneously from the folder containing the `vcpkg.json` file (manifest mode)
3. Sometimes one of the two instances errors out with
```
read_contents(C:\Users\pk19i077\DEV\vcpkg\.vcpkg-root): permission denied
```

**Expected behavior**
The second instance should wait until the first one has quit instead of quitting with an error.

**Failure logs** 
Log with `--debug` from instance 1 (finished processing):
```
C:\Users\pk19i077\DEV\test_proj>C:\Users\pk19i077\DEV\vcpkg\vcpkg.exe install --debug
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] BuiltinRegistry initialized with: ""
[DEBUG] Using vcpkg-root: C:\Users\pk19i077\DEV\vcpkg
[DEBUG] Using manifest-root: C:\Users\pk19i077\DEV\test_proj
[DEBUG] BuiltinRegistry initialized with: ""
[DEBUG] Using scripts-root: C:\Users\pk19i077\DEV\vcpkg\scripts
[DEBUG] Using downloads-root: C:\Users\pk19i077\DEV\vcpkg\downloads
[DEBUG] Using scripts-root: C:\Users\pk19i077\DEV\vcpkg\scripts
[DEBUG] Using builtin-ports: C:\Users\pk19i077\DEV\vcpkg\ports
[DEBUG] Using builtin-registry: C:\Users\pk19i077\DEV\vcpkg\versions
[DEBUG] Using installed-root: C:\Users\pk19i077\DEV\test_proj\vcpkg_installed
[DEBUG] Using packages-root: C:\Users\pk19i077\DEV\vcpkg\packages
[DEBUG] Using buildtrees-root: C:\Users\pk19i077\DEV\vcpkg\buildtrees
[DEBUG] Default binary cache path is: C:\Users\pk19i077\AppData\Local\vcpkg\archives
[DEBUG] Using overlay: C:\Users\pk19i077\DEV\test_proj
[DEBUG] Found path: C:\Program Files\CMake\bin\cmake.exe
[DEBUG] CreateProcessW("C:\Program Files\CMake\bin\cmake.exe" --version)
[DEBUG] cmd_execute_and_stream_data() returned 0 after    27591 us
[DEBUG] CreateProcessW("C:\Program Files\CMake\bin\cmake.exe" -DVCPKG_ROOT_DIR=C:/Users/pk19i077/DEV/vcpkg -DPACKAGES_DIR=C:/Users/pk19i077/DEV/vcpkg/packages -DBUILDTREES_DIR=C:/Users/pk19i077/DEV/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=C:/Users/pk19i077/DEV/test_proj/vcpkg_installed -DDOWNLOADS=C:/Users/pk19i077/DEV/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "C:\Users\pk19i077\DEV\vcpkg\buildtrees\0.vcpkg_dep_info.cmake")
[DEBUG] cmd_execute_and_stream_data() returned 0 after    18071 us
[DEBUG] Using overlay: C:\Users\pk19i077\DEV\test_proj
All requested packages are currently installed.
Restored 0 packages from C:\Users\pk19i077\AppData\Local\vcpkg\archives in 128.3 us. Use --debug to see more details.

Total elapsed time: 58.97 ms

[DEBUG] D:\a\_work\1\s\src\vcpkg\commands.setinstalled.cpp(138)
[DEBUG] Exiting after 59.92 ms (59621 us)
```

Log with `--debug` from instance 2 (errored out):
```
C:\Users\pk19i077\DEV\test_proj>C:\Users\pk19i077\DEV\vcpkg\vcpkg.exe install --debug
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] BuiltinRegistry initialized with: ""
[DEBUG] Using vcpkg-root: C:\Users\pk19i077\DEV\vcpkg
[DEBUG] Failed to open: C:\Users\pk19i077\DEV\vcpkg\.vcpkg-root
read_contents(C:\Users\pk19i077\DEV\vcpkg\.vcpkg-root): permission denied
[DEBUG] D:\a\_work\1\s\src\vcpkg\vcpkgpaths.cpp(384)
[DEBUG] Exiting after 1.989 ms (1917 us)
```

**Additional context**
This bug was introduced in the last couple of months (didn't bisect). One can hit it quite often with CLion having multiple configurations set-up for a project (Debug, Release, ...), since a CMake reload triggers the execution of vcpkg simultaneously for the different configurations.

**Comment by autoantwort** [comment]
This also broke the msbuild integration because msbuild builds projects in parallel, which then start vcpkg in parallel which is now broken.

**Comment by autoantwort** [comment]
I think the following code broke it: https://github.com/microsoft/vcpkg-tool/pull/246/files#diff-a7dc1f432d5bfbd00785a5742acaa7861bf9279fabbcb1131612ee56f89bf8eaR379

**Comment by ras0219-msft** [comment]
We've reverted the 2021-11-19 update to address this issue -- thank you very much for reporting!

I'll leave this open until we successfully publish a new tool that does not have the problem.

**Comment by autoantwort** [comment]
@ras0219-msft I think you have to revert to a version previous to 2021-11-15. It was introduced in the release before the last release (not in the latest release)

**Comment by ras0219-msft** [comment]
Yes, you're right. We decided to go ahead and push for a hotfix release instead, which occurred on 2021-11-24. See https://github.com/microsoft/vcpkg/commit/b3cfaaf1bba70febd07c2f672ae590dc5d914180 and https://github.com/microsoft/vcpkg-tool/releases/tag/2021-11-24
