### ISSUE TITLE
How do I build on PowerPC arch?

### ISSUE THREAD

**Issue by TDL3** [microsoft/vcpkg#21603]
Please create a discussion in https://github.com/microsoft/vcpkg/discussions/new instead.

**Comment by TDL3** [comment]
Yo

**Comment by TDL3** [comment]
Is it possible to build vcpkg from source on PowerPC64 arch?

**Comment by FrankXie05** [comment]
@TDL3 Thanks for posting this issue. Sorry, we currently do not officially support building on the PowerPC64 arch.

**Comment by TDL3** [comment]
Thanks for the info
