### ISSUE TITLE
[assimp] dependency on irrlicht

### ISSUE THREAD

**Issue by markridgewell** [microsoft/vcpkg#21605]
****

**Is your feature request related to a problem? Please describe.**
When I try to install Assimp on Linux, it fails when building Irrlicht because of dependencies that must be manually installed (see related issue: https://github.com/microsoft/vcpkg/pull/21511). But Assimp doesn't need any of these dependencies, it only cares about IrrXML, which is part of Irrlicht but also available as a stand-alone. I notice there is a port for IrrXML, but its just an alias for Irrlicht. Irrlicht is a large project with many dependencies, and it doesn't make sense for Assimp to depend on the whole thing just to support .irr files.

Also, I'm not even sure if Assimp still depends on IrrXML, as there is another XML parser in the repo: https://github.com/assimp/assimp/tree/master/contrib/pugixml). If this is the case, the dependency can simply be removed.

**Proposed solution**
Remove Irrlicht dependency. If IrrXML is still required, add a proper port for it.

**Describe alternatives you've considered**
If this isn't possible or easy, an alternative might be to add a feature to make irr support optional. 

**Additional context**
SourceForge page for IrrXML: https://sourceforge.net/projects/irrlicht/files/irrXML%20SDK/1.2/

**Comment by Neumann-A** [comment]
If you look at the history of IrrXML you can see that it has been a proper port and not just a redirection. There was probably a good reason to change it to the way it is now.

**Comment by Osyotr** [comment]
AFAIK irrlicht is not unsed anymore in latest version of assimp (5.1.1), so we can drop the dependency.

**Comment by markridgewell** [comment]
That's what I thought. If the dependency can be removed that would be great 🙂

**Comment by JackBoosY** [comment]
If it's not required, we can convert that to a feature instead.

**Comment by Osyotr** [comment]
I've tried to build assimp 5.1.1, but it requires patching: https://github.com/microsoft/vcpkg/issues/21361
