### ISSUE TITLE
update restclient-cpp to 0.5.2

### ISSUE THREAD

**Issue by albintho** [microsoft/vcpkg#21614]
Library name: restclient-cpp

current version: 0.5.1
New version: 0.5.2

The current version of restclient-cpp is old, requesting to update the version.
Looking forward for new feature like verifyPeer etc. to be updated in vcpkg.

**Comment by FrankXie05** [comment]
@albintho ,Thanks for posting this issue, pr #9717 have updated restclient-cpp to latest version 0.5.2
please git pull vcpkg and use, we temporarily cloes this issue

**Comment by albintho** [comment]
@FrankXie05  this still doesnt have verifyPeer functionality.

**Comment by FrankXie05** [comment]
The latest release version didn't merge this PR's changes, see https://github.com/mrtazz/restclient-cpp/blob/c4683b21af188f3f78146ea6f841db16a56e5ff4/include/restclient-cpp/connection.h.

We will wait for the next release and update this port to fix this issue.

**Comment by FrankXie05** [comment]
@albintho We merged to master Fix PR #23005 , you can use `git pull` to use the latest restclient-cpp. And upstream has been merged into master.
see https://github.com/mrtazz/restclient-cpp/blob/master/include/restclient-cpp/connection.h
If there is still a problem, please reply me and I will reopen it
