### ISSUE TITLE
Error: Building package python3:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by nextquanta** [microsoft/vcpkg#21615]
**Host Environment**
- OS: Windows 10

**To Reproduce**
`./vcpkg install boost:x64-windows`

**Failure logs** 
Error: Building package python3:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+python3
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[python3]+Build+error
including:
  package: python3[core]:x64-windows -> 3.10.0#2
    vcpkg-tool version: 2021-11-19-dd4f5f501990cc475022b1677675c344a91b8192
    vcpkg-scripts version: 653912591 2021-11-21 (33 hours ago)

Additionally, attach any relevant sections from the log files above.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by PhoebeHui** [comment]
@nextquanta, could you attach the failure logs?

**Comment by PhoebeHui** [comment]
@nextquanta, please reopen this issue and provide us failure logs if it still be a problem for you.

**Comment by yudaichen** [comment]
**OS: Windows 10

./vcpkg install boost:x64-windows**

Starting package 1/23: python3:x64-windows
Building package python3[core]:x64-windows...
-- Using cached python-cpython-v3.10.1.tar.gz.
-- Cleaning sources at E:/development/zz/vcpkg/vcpkg/buildtrees/python3/src/v3.10.1-157716e946.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/development/zz/vcpkg/vcpkg/downloads/python-cpython-v3.10.1.tar.gz
-- Applying patch 0002-use-vcpkg-zlib.patch
-- Applying patch 0003-devendor-external-dependencies.patch
-- Applying patch 0004-dont-copy-vcruntime.patch
-- Applying patch 0005-only-build-required-projects.patch
-- Applying patch 0008-fix-parallel-install.patch
-- Using source at E:/development/zz/vcpkg/vcpkg/buildtrees/python3/src/v3.10.1-157716e946.clean
-- Building PCbuild/pcbuild.proj for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: msbuild E:/development/zz/vcpkg/vcpkg/buildtrees/python3/x64-windows-rel/v3.10.1-157716e946.clean/PCbuild/pcbuild.proj /p:Configuration=Release /p:IncludeExtensions=true /p:IncludeExternals=true /p:IncludeCTypes=true /p:IncludeSSL=true /p:IncludeTkinter=false /p:IncludeTests=false /p:ForceImportBeforeCppTargets=E:/development/zz/vcpkg/vcpkg/buildtrees/python3/src/v3.10.1-157716e946.clean/PCbuild/python_vcpkg.props /p:IncludeUwp=false /p:_VcpkgPythonLinkage=DynamicLibrary /t:Rebuild /p:Platform=x64 /p:PlatformToolset=v142 /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /p:WindowsTargetPlatformVersion=10.0.19041.0 /p:VcpkgTriplet=x64-windows /p:VcpkgInstalledDir=E:/development/zz/vcpkg/vcpkg/installed /p:VcpkgManifestInstall=false /p:UseMultiToolTask=true /p:MultiProcMaxCount=9 /p:EnforceProcessCountAcrossBuilds=true /m:9
    Working Directory: E:/development/zz/vcpkg/vcpkg/buildtrees/python3/x64-windows-rel/v3.10.1-157716e946.clean
    Error code: 1
    See logs for more information:
      E:\development\zz\vcpkg\vcpkg\buildtrees\python3\build-x64-windows-rel-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_msbuild.cmake:172 (vcpkg_execute_required_process)
  ports/python3/portfile.cmake:118 (vcpkg_install_msbuild)
  scripts/ports.cmake:142 (include)


Error: Building package python3:x64-windows failed with: BUILD_FAILED

**Comment by PhoebeHui** [comment]
@yudaichen, please create a new issue with full failure logs instead.
