### ISSUE TITLE
[coolprop] if97 build failed

### ISSUE THREAD

**Issue by nitrogene** [Microsoft/vcpkg#2162]
I failed to install coolprop due to if97package:

PS D:\Dev\vcpkg> .\vcpkg.exe install coolprop:x64-windows
The following packages will be built and installed:
    coolprop:x64-windows
  * fmt:x64-windows
  * if97:x64-windows
  * msgpack:x64-windows
  * rapidjson:x64-windows
  * refprop-headers:x64-windows
Additional packages (*) will be installed to complete this operation.
Starting package 1/6: if97:x64-windows
Building package if97:x64-windows...
-- CURRENT_INSTALLED_DIR=D:/Dev/vcpkg/installed/x64-windows
-- DOWNLOADS=D:/Dev/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=D:/Dev/vcpkg/packages/if97_x64-windows
-- CURRENT_BUILDTREES_DIR=D:/Dev/vcpkg/buildtrees/if97
-- CURRENT_PORT_DIR=D:/Dev/vcpkg/ports/if97/.
CMake Error at scripts/cmake/vcpkg_from_github.cmake:58 (message):
  OUT_SOURCE_PATH must be specified.
Call Stack (most recent call first):
  ports/if97/portfile.cmake:4 (vcpkg_from_github)
  scripts/ports.cmake:72 (include)

Error: Building package if97:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: if97:x64-windows
  Vcpkg version: 0.0.96-2017-11-09-615f7e112f38cf82dd1cec9d519501938f755324

Additionally, attach any relevant sections from the log files above.

**Comment by xoviat** [comment]
What's the log output?

**Comment by xoviat** [comment]
Sorry, just submit a PR to fix OUT_SOURCE_PATH
