### ISSUE TITLE
[unixodbc:x64-linux] build failure

### ISSUE THREAD

**Issue by ViksitAgarwal** [microsoft/vcpkg#21621]
**Host Environment**
- OS: Linux - UBuntu 20.04 WSL2 on Windows10
- Compiler: revision

**To Reproduce**
`sudo vcpkg install unixodbc`

**Failure logs** 
-Cut and paste the appropriate build messages from the console output.
sudo vcpkg install unixodbc
Computing installation plan...
The following packages will be built and installed:
    unixodbc[core]:x64-linux -> 2.3.9
Detecting compiler hash for triplet x64-linux...
Restored 0 packages from /root/.cache/vcpkg/archives in 5.4 us. Use --debug to see more details.
Starting package 1/1: unixodbc:x64-linux
Building package unixodbc[core]:x64-linux...
-- Using cached lurcher-unixODBC-v2.3.9.tar.gz.
-- Cleaning sources at /home/vagarwal/installs/vcpkg/buildtrees/unixodbc/src/v2.3.9-8382bc5611.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/vagarwal/installs/vcpkg/downloads/lurcher-unixODBC-v2.3.9.tar.gz
-- Using source at /home/vagarwal/installs/vcpkg/buildtrees/unixodbc/src/v2.3.9-8382bc5611.clean
-- Getting CMake variables for x64-linux-dbg
-- Getting CMake variables for x64-linux-rel
-- Generating configure for x64-linux
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: /usr/bin/autoreconf -vfi
    Working Directory: /home/vagarwal/installs/vcpkg/buildtrees/unixodbc/src/v2.3.9-8382bc5611.clean/
    Error code: 1
    See logs for more information:
      /home/vagarwal/installs/vcpkg/buildtrees/unixodbc/autoconf-x64-linux-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:610 (vcpkg_execute_required_process)
  ports/unixodbc/portfile.cmake:16 (vcpkg_configure_make)
  scripts/ports.cmake:142 (include)

Error: Building package unixodbc:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  package: unixodbc[core]:x64-linux -> 2.3.9
  vcpkg version: 30465138e 2021-11-22 (6 hours ago)
  vcpkg-tool version: 2021-11-15-ec76affcc987efbf172b7da0b05df711b48fa535
===============
-Please attach any additional failure logs mentioned in the console output.
err.log
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: adding subdirectory libltdl to autoreconf
autoreconf: Entering directory `libltdl'
autoreconf: running: aclocal --force -I ../m4
autoreconf: running: libtoolize --copy --force --ltdl
Can't exec "libtoolize": No such file or directory at /usr/share/autoconf/Autom4te/FileUtils.pm line 345, <GEN7> line 6.
autoreconf: failed to run libtoolize: No such file or directory
autoreconf: libtoolize is needed because this package uses Libtool

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by ViksitAgarwal** [comment]
After installing these packages - automake autoconf libtool, mentioned in http://www.unixodbc.org/, the installation was successful.  Not sure if by design vcpkg should install these pre-requisites or not.

**Comment by JonLiu1993** [comment]
@ViksitAgarwal ,Yes, the first time you install unixodbc:x64-linux, you need to install the above packages in advance. If you install it, you won’t be prompted again.

**Comment by JonLiu1993** [comment]
@ViksitAgarwal ,This issue has been resolved, temporarily close this issue, please feel free to reopen this issue if it is still a problem for you.
