### ISSUE TITLE
How to apply a patch from a fork in the portfile

### ISSUE THREAD

**Issue by jasjuang** [Microsoft/vcpkg#2163]
Currently libfreenect2 depends on libusb, however even though libfreenect2 currently builds it's still not able to launch the kinect correctly, because libfreenect2 requires libusb to be built with a custom patch from xlz/libusb applied. It is shown in https://github.com/OpenKinect/libfreenect2/blob/master/depends/install_libusb_vs2015.cmd.

I inquired the authors of libfreenect2 in https://github.com/OpenKinect/libfreenect2/issues/931 asking why not submit a PR to the main libusb branch and it appears that libusb is moving really slow.

Now I want to update the libusb portfile to apply the patch from xlz/libusb, but I am stuck. Can someone give me some hints on how to change the portfile to make this happen?

**Comment by xoviat** [comment]
Look at Flint.

**Comment by xoviat** [comment]
```
vcpkg_apply_patches(
    SOURCE_PATH ${SOURCE_PATH}
    PATCHES "${CMAKE_CURRENT_LIST_DIR}/lib_flint.patch"
            "${CMAKE_CURRENT_LIST_DIR}/dll_flint.patch"
)

set(MSVC_VERSION 14)

file(REMOVE_RECURSE ${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET})
file(MAKE_DIRECTORY ${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET})
file(COPY ${SOURCE_PATH} DESTINATION ${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET})
get_filename_component(SOURCE_DIR_NAME "${SOURCE_PATH}" NAME)

# Use fresh copy of sources for building and modification
set(SOURCE_PATH "${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}/${SOURCE_DIR_NAME}")

file(TO_NATIVE_PATH ${CURRENT_INSTALLED_DIR} NATIVE_INSTALLED_DIR)
```

**Comment by jasjuang** [comment]
@xoviat @ras0219-msft @alexkaratarakis I still need some help. How is the index in the patch file determined? Currently how I am doing is 

1. git clone a new copy of libusb
2. Apply the change of the fork on libusb
3. Do a git diff
4. Copy paste what is in the terminal and save it into libfreenect2.patch and put it into the port folder on libusb.
5. Add `vcpkg_apply_patches` on the portfile of libusb.
6. `vcpkg install libusb` but it shows the libfreenect2.patch failed to apply.

What am I doing wrong? I suspect it's the index that is not matching but can't figure it out yet.

**Comment by xoviat** [comment]
Make sure to clone the exact revision of libusb that vcpkg clones.

**Comment by jasjuang** [comment]
@xoviat I figured out why it's failing. It's because when I copy the diff from the terminal for some reason there is a Carriage Return (CR) in the end of the line. If I run a dos2unix on the patch file then everything starts working again...
