### ISSUE TITLE
make libzip for mingw have error

### ISSUE THREAD

**Issue by Moodsky** [microsoft/vcpkg#21643]
make libzip for win is OK,bug make libzip for mingw is Error!

D:\vcpkg-master>vcpkg install libzip[bzip2]:x64-mingw-static
Computing installation plan...
The following packages will be built and installed:
    libzip[bzip2,core,default-aes,wincrypto]:x64-mingw-static -> 1.8.0
Detecting compiler hash for triplet x64-mingw-static...
Restored 0 packages from C:\Users\Administrator\AppData\Local\vcpkg\archives in 246 us. Use --debug to see more details.
Starting package 1/1: libzip:x64-mingw-static
Building package libzip[bzip2,core,default-aes,wincrypto]:x64-mingw-static...
**-- Using community triplet x64-mingw-static. This triplet configuration is not guaranteed to succeed.**
-- [COMMUNITY] Loading triplet configuration from: D:\vcpkg-master\triplets\community\x64-mingw-static.cmake
-- Using cached nih-at-libzip-v1.8.0.tar.gz.
-- Cleaning sources at D:/vcpkg-master/buildtrees/libzip/src/v1.8.0-57e7193039.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/vcpkg-master/downloads/nih-at-libzip-v1.8.0.tar.gz
-- Applying patch fix-dependency.patch
-- Using source at D:/vcpkg-master/buildtrees/libzip/src/v1.8.0-57e7193039.clean
-- Configuring x64-mingw-static
-- Building x64-mingw-static-dbg
-- Building x64-mingw-static-rel
-- Fixing pkgconfig file: D:/vcpkg-master/packages/libzip_x64-mingw-static/lib/pkgconfig/libzip.pc
-- Using cached msys-mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst.
-- Using msys root at D:/vcpkg-master/downloads/tools/msys2/aa5af7b2aa7e90e8
-- Fixing pkgconfig file: D:/vcpkg-master/packages/libzip_x64-mingw-static/debug/lib/pkgconfig/libzip.pc
-- Installing: D:/vcpkg-master/packages/libzip_x64-mingw-static/share/libzip/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\Administrator\AppData\Local\vcpkg\archives\e7\e7367733ed889d42cc52d811dee7f40c1cb877ba7a817972ba201a41ad55e553.zip
Installing package libzip[bzip2,core,default-aes,wincrypto]:x64-mingw-static...
Elapsed time for package libzip:x64-mingw-static: 32.74 s

Total elapsed time: 35.13 s

The package libzip provides CMake targets:

    find_package(libzip CONFIG REQUIRED)
    target_link_libraries(main PRIVATE libzip::zip)

make libzip for mingw-x64-static file size is 277kb
error code win64/libzip.a(zip_crypto_win.c.obj):zip_crypto_win.c:(.text+0xeb5): undefined reference to `BCryptCloseAlgorithmProvider'

**Comment by JackBoosY** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
