### ISSUE TITLE
OpenEXR update to 3.1.3

### ISSUE THREAD

**Issue by meshula** [microsoft/vcpkg#21652]
Library name: OpenEXR

New version number:

3.1.3

https://github.com/AcademySoftwareFoundation/openexr/releases/tag/v3.1.3

Other information that may be useful (release notes, etc...)

Many projects, such as OpenVdb and OpenImageIO have migrated to OpenEXR 3 already, and vcpkg only supply OpenEXR version 2 is starting to impact users.

https://github.com/AcademySoftwareFoundation/openexr/issues/1207

**Comment by JonLiu1993** [comment]
Fix by #20957

**Comment by EvanAW** [comment]
This can be closed since https://github.com/microsoft/vcpkg/commit/94b089b7c130b6aa6e49bbf923985176a888b9e3 landed.

**Comment by meshula** [comment]
3.1.5 is deployed to vcpkg :)
