### ISSUE TITLE
Using --x-buildtrees does not overwrite the value in SOURCE_PATH

### ISSUE THREAD

**Issue by JackBoosY** [microsoft/vcpkg#21656]
In case https://github.com/microsoft/vcpkg/issues/21343, the user used the extra option `--x-buildtrees` when building qt5, which resulted in the failure of clearing `EffectiveSourcePaths` in the script `configure_qt.cmake`:
https://github.com/microsoft/vcpkg/blob/a2fcb03749ff5897b5985092934dc6057680c789/ports/qt5-base/cmake/configure_qt.cmake#L145

Our expectation is that `SOURCE_PATH` is always the currently used source path of the library.
Obviously, this does not meet the expected results.

**Comment by Neumann-A** [comment]
just replace it with:
`string(REPLACE "[EffectiveSourcePaths]\nPrefix=[^\n]+\n" "" _contents ${_contents}) `

**Comment by JackBoosY** [comment]
> just replace it with: `string(REPLACE "[EffectiveSourcePaths]\nPrefix=[^\n]+\n" "" _contents ${_contents}) `

Yeah, that will definitely solve the qt issues, but this issue still exists.

**Comment by BillyONeal** [comment]
To my understanding the vcpkg tool does not set any variable named `SOURCE_PATH`; that's just a common convention we happen to use a lot as the name for `vcpkg_from_xxx`.

https://github.com/microsoft/vcpkg-tool/blob/45c773ee248f664b96dda6f41502cca8c380cede/src/vcpkg/buildenvironment.cpp#L15

It appears the name the vcpkg binary sets is `BUILDTREES_DIR`.

**Comment by JackBoosY** [comment]
> To my understanding the vcpkg tool does not set any variable named SOURCE_PATH; that's just a common convention we happen to use a lot as the name for vcpkg_from_xxx.

Yeah but this will obviously mislead maintainers.

**Comment by BillyONeal** [comment]
> Yeah but this will obviously mislead maintainers.

I'm not sure I understand; whatever `portfile.cmake` set `SOURCE_PATH` to a funny value needs to be fixed here; vcpkg can't fix setting a variable it never set in the first place.

**Comment by JackBoosY** [comment]
> I'm not sure I understand; whatever `portfile.cmake` set `SOURCE_PATH` to a funny value needs to be fixed here; vcpkg can't fix setting a variable it never set in the first place.

`SOURCE_PATH` is provided by `vcpkg_from_*` and `vcpkg_download_dstfile`. Obviously, this value has become well-known, and our maintainers expects to pass it into the configuration script to call the files in the path.
However `--x-buildtrees` clearly broke the maintainer's expectations.

**Comment by JackBoosY** [comment]
Consider this:
`vcpkg_configure_make` adds the option `COPY_SOURCE` because some ports do not support building outside the source, but the source path used by the user who uses the `--x-buildtrees` option is not the expected value (_VCPKG_ROOT/buildtrees/PORT/src/HASH_), This will cause the failure to copy all files in the source path to _VCPKG_ROOT/buildtrees/PORT/TRIPLET_dbg_ when using `COPY_SOURCE`.

**Comment by BillyONeal** [comment]
> `SOURCE_PATH` is provided by `vcpkg_from_*`

No, those set whatever variable name the user wants. Rather than:

```
vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO cpp-io2d/P0267_RefImpl
    REF caa0ba0cb5a421a38bc26afaf3505bee206c44dd # accessed on 2020-09-14
    SHA512 f8e5a708f6cbda913a0492a843e1502b8d3cc615a6abda50e850be944e1484ec9087b787c54cc25d513172a7d5ab789be41a761c97df94266df4d1bcf14db17c
    HEAD_REF master
    PATCHES
        cmake.dep.patch
)
```

the user can do

```
vcpkg_from_github(
    OUT_SOURCE_PATH ANYTHING_YOU_WANT
    REPO cpp-io2d/P0267_RefImpl
    REF caa0ba0cb5a421a38bc26afaf3505bee206c44dd # accessed on 2020-09-14
    SHA512 f8e5a708f6cbda913a0492a843e1502b8d3cc615a6abda50e850be944e1484ec9087b787c54cc25d513172a7d5ab789be41a761c97df94266df4d1bcf14db17c
    HEAD_REF master
    PATCHES
        cmake.dep.patch
)
```

and there will be no `SOURCE_PATH`.

In the linked `ports/qt5-base/cmake/configure_qt.cmake#L145` example, `SOURCE_PATH` is a parameter, so where the bad parameter value came from needs to be investigated.

**Comment by BillyONeal** [comment]
> `vcpkg_configure_make` adds the option `COPY_SOURCE` because some ports do not support building outside the source, but the source path used by the user who uses the `--x-buildtrees` option is not the expected value

In this case too it is a parameter, not a well known value set by vcpkg: 
https://github.com/microsoft/vcpkg/blob/d0ce2aa08b1b3b1e740eeaec5d724bbe2099ea1f/scripts/cmake/vcpkg_configure_make.cmake#L230-L234

**Comment by dg0yt** [comment]
AFAICT *the source path* is passed out of download functions and into configure functions explicitly.
Build functions operate only on *build paths* which are more based on convention, not passed out of configure functions explicitly. They don't know about source paths.

**Comment by Neumann-A** [comment]
> In the linked ports/qt5-base/cmake/configure_qt.cmake#L145 example, SOURCE_PATH is a parameter, so where the bad parameter value came from needs to be investigated.

just run vcpkg with `--x-cmake-args=--trace-expand` ;)
So `SOURCE_PATH` is set by one of the download functions. The problem with it is that it seems to see through system indirection which is a problem if `subst` is used and the buildsystem does not see through it. As far as I can tell `vcpkg_extract_source_archive_ex` is setting `SOURCE_PATH` which is using the new `cmake_path` API. So this could be the issue.
