### ISSUE TITLE
Linux: static compilation （linux系统如何静态编译？）

### ISSUE THREAD

**Issue by zhangbowei** [microsoft/vcpkg#21658]
platform: linux
**question:** How do I get ompl's  *.a files?(static compile)
command: (photos form installed/vcpkg/info
vcpkg install protobuf:x64-linux   => *.a
![image](https://user-images.githubusercontent.com/14348480/143415623-b16ac00c-3a49-4340-913d-3733ac38bbff.png)

vcpkg install ompl:x64-linux => *.so
![image](https://user-images.githubusercontent.com/14348480/143415462-3dfe87f3-54f1-4820-9e97-eb0e50c3829d.png)

vcpkg install protobuf:arm-linux  => *.a
![image](https://user-images.githubusercontent.com/14348480/143415809-68abd540-745a-4f62-88c7-946016a978e8.png)

vcpkg install ompl:arm-linux => *.so
![image](https://user-images.githubusercontent.com/14348480/143415526-97a46c3f-62f4-44de-8a9d-6bc33c4982f6.png)

**Comment by JackBoosY** [comment]
ompl should respect the selected triplet in Linux.

**Comment by JackBoosY** [comment]
According to the [upstream configuration](https://github.com/ompl/ompl/blob/main/src/ompl/CMakeLists.txt#L49-L54):
```cmake
# build the library
if(MSVC)
    add_library(ompl STATIC ${OMPL_SOURCE_CODE})
else(MSVC)
    add_library(ompl SHARED ${OMPL_SOURCE_CODE})
endif(MSVC)
```
I think that's by design.

**Comment by zhangbowei** [comment]
If I want static compile OMPL in ubuntu18.04，what should I do ？
If I change the code which you change in the portfile.cmake, Could It run？

**Comment by JackBoosY** [comment]
@zhangbowei  Create a new triplet file `x64-linux-dynamic` in _VCPKG_ROOT/triplets/community_ and add the following code:
```cmake
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)

set(VCPKG_CMAKE_SYSTEM_NAME Linux)
```
Build those port with extra option `--triplet=x64-linux-dynamic`.

**Comment by zhangbowei** [comment]
According to you，I add a  new triplet，Running `vcpkg install ompl  --triplet=x64-linux-dynamic`， And I got this error.


Starting package 1/70: boost-exception:x64-linux-dynamic
Building package boost-exception[core]:x64-linux-dynamic...
-- Using community triplet x64-linux-dynamic. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: /home/test/package/vcpkg/triplets/community/x64-linux-dynamic.cmake
-- Using cached boostorg-exception-boost-1.77.0.tar.gz.
-- Cleaning sources at /home/test/package/vcpkg/buildtrees/boost-exception/src/ost-1.77.0-6531b39968.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/test/package/vcpkg/downloads/boostorg-exception-boost-1.77.0.tar.gz
-- Using source at /home/test/package/vcpkg/buildtrees/boost-exception/src/ost-1.77.0-6531b39968.clean
CMake Error at ports/boost-exception/portfile.cmake:14 (include):
  include could not find requested file:

    /home/test/package/vcpkg/installed/x64-linux/share/boost-build/boost-modular-build.cmake
Call Stack (most recent call first):
  scripts/ports.cmake:142 (include)


Error: Building package boost-exception:x64-linux-dynamic failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  package: boost-exception[core]:x64-linux-dynamic -> 1.77.0
  vcpkg version: 203daf9 2021-11-19 (10 days ago)
  vcpkg-tool version: 2021-11-15-ec76affcc987efbf172b7da0b05df711b48fa535

Additionally, attach any relevant sections from the log files above.

**Comment by JackBoosY** [comment]
_/home/test/package/vcpkg/installed/x64-linux/share/boost-build/boost-modular-build.cmake_
This path is incorrect, and I can't reproduce this on my local machine.

Please remove `boost-uninstall:x64-linux` first and try again.

**Comment by dg0yt** [comment]
> @zhangbowei Create a new triplet file `x64-linux-dynamic` in _VCPKG_ROOT/triplets/community_ and add the following code:
> 
> ```cmake
> set(VCPKG_TARGET_ARCHITECTURE x64)
> set(VCPKG_CRT_LINKAGE dynamic)
> set(VCPKG_LIBRARY_LINKAGE dynamic)
> 
> set(VCPKG_CMAKE_SYSTEM_NAME Linux)
> ```
> 
> Build those port with extra option `--triplet=x64-linux-dynamic`.

@JackBoosY This doesn't help to "static compile OMPL".

In order to build static ompl, the ompl source code needs to be patched.

**Comment by JackBoosY** [comment]
@dg0yt According to the [upstream code](https://github.com/ompl/ompl/blob/main/src/ompl/CMakeLists.txt#L49-L54) and we do not change the build type in [portfile.cmake](https://github.com/microsoft/vcpkg/blob/master/ports/ompl/portfile.cmake), ompl can only be built as a dynamic library on Linux.
