### ISSUE TITLE
 Build port failure when using symbolic link

### ISSUE THREAD

**Issue by n4z4m3** [microsoft/vcpkg#21669]
**Host Environment**
- OS: Windows 10
- Compiler: Visual Studio 2019

**To Reproduce**
`./vcpkg install icu:x64-windows`

**Failure logs** 
`-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
-- Installing x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:155 (message):
    Command failed: C:/Code/External/CppLib/vcpkg/downloads/tools/msys2/803521c5733336c9/usr/bin/make.exe -j 9 --trace -f Makefile install DESTDIR=/C/Code/External/CppLib/vcpkg/packages/icu_x64-windows
    Working Directory: C:/Code/External/CppLib/vcpkg/buildtrees/icu/x64-windows-dbg
    See logs for more information:
      C:\Code\External\CppLib\vcpkg\buildtrees\icu\install-x64-windows-dbg-out.log
      C:\Code\External\CppLib\vcpkg\buildtrees\icu\install-x64-windows-dbg-err.log`

install-x64-windows-dbg-err.log
`make[1]: ./../src/c-69_1-src-86e71a956d.clean/source/install-sh: No such file or directory
make[1]: *** [Makefile:87: install-library] Error 127
make: *** [Makefile:153: install-recursive] Error 2
make: *** Waiting for unfinished jobs....`

**Additional context**
There is a src/c-69_1-src-86e71a956d.clean/source/install-sh file, but maybe the reference path of ./../ is wrong?
It was working at some point, but is not working now. It may have been because I installed Visual Studio 2022, but I have since uninstalled it. But possibly there is some environment setting that was not reverted?

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Please provide files `install-x64-windows-dbg-out.log` and `install-x64-windows-dbg-err.log`.

**Comment by lijgame** [comment]
I had this error as well.
OS: Windows 11
[install-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/7609361/install-x64-windows-dbg-err.log)
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/7609362/install-x64-windows-dbg-out.log)

Compiler: Visual Studio 2019 and 2022

**Comment by n4z4m3** [comment]
> Thanks for posting this issue. Please provide files `install-x64-windows-dbg-out.log` and `install-x64-windows-dbg-err.log`.

[install-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/7619158/install-x64-windows-dbg-err.log)
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/7619160/install-x64-windows-dbg-out.log)

**Comment by LilyWangLL** [comment]
There is message in install-x64-windows-dbg-out.log
`./../src/c-69_1-src-86e71a956d.clean/source/install-sh -c icudtd69.dll`
This is correct message: `/usr/bin/install -c icudt69.dll /E/Code/External/CppLib/vcpkg/packages/icu_x64-windows/E/Code/External/CppLib/vcpkg/installed/x64-windows/lib`
It looks like use incorrect install.sh or executable. Did you clone new vcpkg after uninstalling Visual Studio 2022?

**Comment by n4z4m3** [comment]
@LilyWangLL I just tried to clone a new vcpkg and the only commands I did were the bootstrap and the install icu

I still get the same error.

New logs are attache
[install-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/7626779/install-x64-windows-dbg-err.log)
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/7626780/install-x64-windows-dbg-out.log)
d.

**Comment by LilyWangLL** [comment]
@n4z4m3 Could you please use the attached file to install icu again? I did some fix in **portfile.cmake**
[icu.zip](https://github.com/microsoft/vcpkg/files/7630447/icu.zip)
.

**Comment by n4z4m3** [comment]
@LilyWangLL  Thank you, but that did not work. I tried crossing my fingers and everything.

New log files attached
[install-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/7630666/install-x64-windows-dbg-err.log)
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/7630668/install-x64-windows-dbg-out.log)
.

**Comment by LilyWangLL** [comment]
@n4z4m3 Due to I can't reproduce this issue locally, could you remove folder [VCPKG_ROOT]/downloads/tools/msys2 and install again? Before installing icu, please use command `git pull` and `.\bootstrap-vcpkg.bat` to update vcpkg to latest version.

**Comment by n4z4m3** [comment]
@LilyWangLL 
Unfortunately your suggestion did not work. 
However, I was able to get it to build by moving my VCPKG_ROOT to C:\vcpkg
Prior to that, it was in a subdirectory structure which I guess you can see in the log files. So somehow it does not like the subdirectory structure or maybe something at this directory structure is cached or stored in the environment. I did look at my PATH environment variable and it doesn't appear there. 
I do have msys2 installed already on my computer and that is in my PATH. But I would not expect this to be an issue.

**Comment by lijgame** [comment]
Hey guys,

I ran into the same error earlier.
After spending hours on trying to figure out the issue, I finally found my issue caused by directory symbolic link.
In my case, my `vcpkg` folder is `d:\codes\vcpkg`, I created a symbolic link in C drive `c:\codes\vcpkg`.
The error happens when I try to install the package from c:\codes\vcpkg location.
Problem solved after I switched to native location( `d:\codes\vcpkg`).

As I noticed, most packages won't have any issue with symbolic links, but ICU and QT5 will complain.

-Jiang

**Comment by JackBoosY** [comment]
Please note that vcpkg may have bugs on symbolic link.

**Comment by n4z4m3** [comment]
@lijgame and @LilyWangLL It looks like the symbolic links are my problem as well. And it also explains why it just started recently for me. My C drive was getting full so I needed to move vcpkg to my D drive, but I really wanted to keep it so that it appeared like it was in the C drive so I used a symbolic link. I guess I need to find a new way to do this.

Any thoughts on the next steps? Do I close this issue and that is that? Do I rename the issue to say that icu breaks when vcpkg root is a symbolic link? Or close this issue and open a new one?

**Comment by lijgame** [comment]
I'm glad it works for you.
You can still use symbolic link, you just need to install packages from d drive.
I have no issues linking vcpkg libraries from c drive in my projects. 

-Jiang

**Comment by n4z4m3** [comment]
@lijgame 
Thanks. That is exactly how I am now using it. I do the package install from my D drive, but then point to the symbolic link location on the C drive in my software that utilizes the libraries.

**Comment by LilyWangLL** [comment]
Hi @BillyONeal, could you help take a look this issue? Thanks.

**Comment by JackBoosY** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/19087.
