### ISSUE TITLE
[glog] build failure

### ISSUE THREAD

**Issue by hei-zy** [microsoft/vcpkg#21665]
**Host Environment**
- OS: [ x64-Windows]
- Compiler: revision

**To Reproduce**
`./vcpkg install glog:x64-windows`

**Failure logs** 
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:155 (message):
    Command failed: D:/develop/vcpkg/downloads/tools/cmake-3.21.1-windows/cmake-3.21.1-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j5
    Working Directory: D:/develop/vcpkg/buildtrees/glog/x64-windows-dbg
    See logs for more information:
      D:\develop\vcpkg\buildtrees\glog\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:106 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:44 (vcpkg_build_cmake)
  ports/glog/portfile.cmake:18 (vcpkg_install_cmake)
  scripts/ports.cmake:142 (include)

Error: Building package glog:x64-windows failed with: BUILD_FAILED

**Additional context**
FAILED: CMakeFiles/glog.dir/src/logging.cc.obj 
ninja: build stopped: subcommand failed.

**Comment by JackBoosY** [comment]
Please provide failure log _D:\develop\vcpkg\buildtrees\glog\install-x64-windows-dbg-out.log_ first.

**Comment by hei-zy** [comment]
Thanks for replying! Here is the file.
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/7605989/install-x64-windows-dbg-out.log)

**Comment by JackBoosY** [comment]
```
D:\develop\vcpkg\buildtrees\glog\src\v0.4.0-46ccbc49a4.clean\src\logging.cc(1957): error C3861: 'truncate': identifier not found
D:\develop\vcpkg\buildtrees\glog\src\v0.4.0-46ccbc49a4.clean\src\logging.cc(1975): error C3861: 'S_ISREG': identifier not found
D:\develop\vcpkg\buildtrees\glog\src\v0.4.0-46ccbc49a4.clean\src\logging.cc(2002): error C3861: 'ftruncate': identifier not found
```

It looks like the cmake choose the Linux codes in Windows.
Can you also please provide config log _D:\develop\vcpkg\buildtrees\glog\config-x64-windows-dbg-out.log_ ?

**Comment by hei-zy** [comment]
I only find the [config-x64-windows-out.log].
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/7606026/config-x64-windows-out.log)

**Comment by hei-zy** [comment]
So how do I switch to Windows codes ?

**Comment by JackBoosY** [comment]
I cannot find the header file `unistd.h` in the Visual Studio path and Visual Studio has never provided this file.
Please provide the version of Visual Studio you are using and the location of the file.

**Comment by hei-zy** [comment]
I added this file `unistd.h` in the Visual Studio myself Previously.   
And I removed the `unistd.h`  just now, the glog was built successfully !
Thanks !
