### ISSUE TITLE
[New Port Request] fatal

### ISSUE THREAD

**Issue by jiayuehua** [microsoft/vcpkg#21678]
Library name:
fatal
Library description:
Fatal (Facebook Template Library) is a library for fast prototyping software in modern C++.
Source repository URL:
https://github.com/facebook/fatal
Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
