### ISSUE TITLE
ITK：Could not determine source path

### ISSUE THREAD

**Issue by wurui1994** [microsoft/vcpkg#2167]
-- Extracting done
CMake Error at D:/vcpkg/scripts/cmake/vcpkg_from_github.cmake:88 (message):
  Could not determine source path:
  'D:/vcpkg/buildtrees/itk/src/ITK-fc374c8431a8aec740e4db3a398c6e95294f34a2'
  does not exist
Call Stack (most recent call first):
  D:/vcpkg/scripts/cmake/vcpkg_from_github.cmake:112 (set_SOURCE_PATH)
  D:/vcpkg/ports/itk/portfile.cmake:3 (vcpkg_from_github)
  D:/vcpkg/scripts/ports.cmake:72 (include)

Error: Building package itk:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: itk:x86-windows
  Vcpkg version: 0.0.96-2017-11-03-aec7d6d60628602fa153633f7e7e92fe66af0655

Additionally, attach any relevant sections from the log files above.

**Comment by PhoebeHui** [comment]
This issue should fix, please get latest vcpkg version and try again, reopen this if it still be an issue for you.
