### ISSUE TITLE
Building package sdl2:x64-mingw-static failed

### ISSUE THREAD

**Issue by EiEddie** [microsoft/vcpkg#21686]
**Host Environment**
- OS: Windows
- Compiler: gcc version 8.1.0 (x86_64-posix-sjlj-rev0, Built by MinGW-W64 project)

**To Reproduce**
`./vcpkg install sdl2:x64-mingw-static`

**Failure logs** 
- Building package sdl2:x64-mingw-static failed with: BUILD_FAILED

[log.txt](https://github.com/microsoft/vcpkg/files/7611240/log.txt)

**Comment by dg0yt** [comment]
Maybe you need #21683.
