### ISSUE TITLE
[New Port Request] mvfst

### ISSUE THREAD

**Issue by jiayuehua** [microsoft/vcpkg#21685]
Library name:
mvfst
Library description:
mvfst (Pronounced move fast) is a client and server implementation of IETF QUIC protocol in C++ by Facebook. QUIC is a UDP based reliable, multiplexed transport protocol that will become an internet standard. 
Source repository URL:
https://github.com/facebookincubator/mvfst
Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
