### ISSUE TITLE
[openssl:x64-windows-static] build failure

### ISSUE THREAD

**Issue by RedstoneMedia** [microsoft/vcpkg#21688]
**Host Environment**
- OS: Windows 10

**To Reproduce**
`./vcpkg install openssl:x64-windows-static`

**Failure logs** 
When it tires to build x64-windows-static-re :
```
Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

Der Befehl "rc" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
NMAKE : fatal error U1077: 'rc' : return code '0x1'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.exe"' : return code '0x2'
Stop.
```

**Additional context**
I do have `rc.exe` installed and in path, but NMAKE still does not find the command : 
```
Get-Command rc

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     rc.exe                                             10.0.19... C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64\rc.exe
```

**Comment by JackBoosY** [comment]
Can you please also provide the _build-x64-windows-static-rel-*-out.log_ ?

Thanks.

**Comment by RedstoneMedia** [comment]
Ok theses are the output logs :
[build-x64-windows-static-rel-0-out.log](https://github.com/microsoft/vcpkg/files/7627656/build-x64-windows-static-rel-0-out.log)
[build-x64-windows-static-rel-1-out.log](https://github.com/microsoft/vcpkg/files/7627653/build-x64-windows-static-rel-1-out.log)

**Comment by JackBoosY** [comment]
```
Der Befehl "rc" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
```
I think your Visual Studio is incomplete.
Can you please provide your Visual Studio version and the installed components?
Also please make sure you've installed the English Language Package using Visual Studio Installer.

Thanks.

**Comment by RedstoneMedia** [comment]
I have Visual Studio 2019 16.11.7 Installed.
The Installed Components are (apart from .net stuff): 
![image](https://user-images.githubusercontent.com/34373974/144310619-fa3b488a-06d3-4342-be90-f965023d0485.png)

**Comment by RedstoneMedia** [comment]
Bruh I just tried to build again, after I installed the English language package (without chaining anything) and it worked. Why does the installed language package have anything to do with the build failing though, that is really confusing ?

**Comment by JackBoosY** [comment]
@RedstoneMedia  Because we do some "magic“ 😆.
