### ISSUE TITLE
[casclib] Unicode regression

### ISSUE THREAD

**Issue by stijnherfst** [microsoft/vcpkg#21682]
The latest merged PR for the casclib port breaks unicode support for the library on Windows. A fix for this would be to add `-DCASC_UNICODE=TRUE` to the portfile.cmake OPTIONS section.

I tried crafting a pull request to fix this issue but I keep running into errors while trying to do the steps the PR guide requires.

**Comment by stijn-ucrowds** [comment]
Thank you for the changes, I appreciate it.

**Comment by stijnherfst** [comment]
Thank you for fixing it, I appreciate it.
