### ISSUE TITLE
[jsoncpp] Build error

### ISSUE THREAD

**Issue by wbaq** [microsoft/vcpkg#21739]
**Host Environment**
- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**
`./vcpkg install xxxx`

**Failure logs** 
-Cut and paste the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by JonLiu1993** [comment]
@wbaq ,Thanks for posting this issue, could you please provide your Compiler, OS, Visual Studio version and detail error log?

**Comment by JonLiu1993** [comment]
@wbaq ,Could you provide the above recurring information?

**Comment by JonLiu1993** [comment]
Thanks for posting this issue. Please reopen this issue if it still be a problem for you.
