### ISSUE TITLE
[flatbuffers] Compiler detection inconsistent with other ports?

### ISSUE THREAD

**Issue by sketch34** [microsoft/vcpkg#21743]
**Is your feature request related to a problem? Please describe.**

Note: I'm using vcpkg in **manifest mode**.

When building on a CentOS box, the flatbuffers port is selecting an old GCC compiler. All other ports select the newer compiler. This is resulting in linker errors for the flatbuffers port. It appears that the compiler selection / detection logic in flatbuffers is inconsistent with how other ports are doing it?

flatbuffers `/vcpkg/buildtrees/flatbuffers/x64-linux-dbg/CMakeCache.txt`:
```
CMAKE_CXX_COMPILER:FILEPATH=/usr/bin/c++
```

```
[jarrod@mozart table-ws-ng]$ /usr/bin/c++ --version
c++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
```

All other ports:
```
CMAKE_CXX_COMPILER:FILEPATH=/opt/gcc/gcc-10.2/bin/c++
```
```
[jarrod@mozart table-ws-ng]$ /opt/gcc/gcc-10.2/bin/c++ --version
c++ (GCC) 10.2.0
```

**Proposed solution**

I'm not sure what the "correct" fix for this is. What I would like is to be able to specify the compiler used for all vcpkg ports and tell the flatbuffers port not to use the old version of GCC. I'm guessing some changes may be required to:
`./vcpkg/buildtrees/flatbuffers/src/v2.0.0-0dfbae4aaf.clean/CMakeLists.txt`

**Describe alternatives you've considered**

I've tried updating to latest vcpkg.

**Additional context**

![image](https://user-images.githubusercontent.com/1082293/143828841-1f77d7a2-818c-4226-ad9b-fcba56d7cd7d.png)

**Comment by JackBoosY** [comment]
Marked as port bug temporary.

**Comment by sketch34** [comment]
@JackBoosY any workaround I can use for now?

**Comment by sketch34** [comment]
I found a temporary workaround, passing `-DCMAKE_CXX_COMPILER:FILEPATH` in the OPTIONS of `vcpkg_configure_cmake()` inside the portfile.cmake:
```
cpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA
    OPTIONS
        -DCMAKE_CXX_COMPILER:FILEPATH=/opt/gcc/gcc-10.2/bin/c++  # TEMP: Workaround. Specify compiler.
        -DFLATBUFFERS_BUILD_TESTS=OFF
        -DFLATBUFFERS_BUILD_GRPCTEST=OFF
        ${OPTIONS}
)
```

**Comment by sketch34** [comment]
Alternative workaround, just for reference in case it helps track down a proper fix:

1. Put a comment in submodules/vcpkg/ports/flatbuffers/portfile.cmake so vcpkg recomputes the hash and will trigger a flatbuffers rebuild.
1. Run:
    ```
    export CXX=g++
    <cmake configure of your main project>
    ```
1. Then you can use cmake normally, export CXX=g++ only needs to be present for the initial build of flatbuffers.

**Comment by JackBoosY** [comment]
I will look into it tomorrow.

**Comment by JackBoosY** [comment]
Comfirmed, but don't know why.

**Comment by sketch34** [comment]
Any further thoughts on this?

**Comment by JackBoosY** [comment]
Can you please unzip [this file](https://github.com/microsoft/vcpkg/files/8067593/flatbuffers.zip) and replace it to _VCPKG_ROOT/ports/flatbuffers_ and try again?

Thanks.

**Comment by JackBoosY** [comment]
Ping for response.

**Comment by sketch34** [comment]
@JackBoosY Thank you, apologies for the delay. I copied the files in the zip and it appears to be consistent now.

<img width="462" alt="image" src="https://user-images.githubusercontent.com/1082293/191433426-f024df91-7caa-4676-bf11-c986c44dfc33.png">

Also note that I get the same result with vcpkg [f93ba15](vscode-file://vscode-app/c:/Users/Jarrod/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)  (tag `2022.07.25`).

**Comment by MonicaLiu0311** [comment]
Currently flatbuffers has been updated to [`23.3.3`](https://github.com/microsoft/vcpkg/pull/30083), does your issue still exist?

**Comment by MonicaLiu0311** [comment]
Test on the `x64-linux` machine, check `/vcpkg/buildtrees/flatbuffers/x64-linux-dbg/CMakeCache.txt`, and find that the detected gcc version is consistent with other ports, so close this issue.


```
root@monica003:/home/monica/vcpkg# ./vcpkg version
vcpkg package management program version 2023-04-07-bedcba5172f5e4b91caac660ab7afe92c27a9895

See LICENSE.txt for license information.
```
