### ISSUE TITLE
alembic Could not find a package configuration file provided by "Alembic" with any   of the following names:

### ISSUE THREAD

**Issue by zhouhang95** [microsoft/vcpkg#21749]
**Describe the bug**
I also use vcpkg install other libs, likes: openvdb, cgmesh, openblas, boost. They work right.
but this lib, can not work.

**Environment**
- OS: Windows
- Compiler: vs2019

**To Reproduce**
1. ./vcpkg install alembic:x64-windows
2. cmake -Bbuild
3. Boom!!!!

**Expected behavior**

**Failure logs** 

I also use vcpkg install other libs, likes: openvdb, cgmesh, openblas, boost. They work right.
but this lib, can not work.
```
D:\zeno>cmake -Bbuild -DCMAKE_TOOLCHAIN_FILE=D:/vcpkg/scripts/buildsystems/vcpkg.cmake
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19043.
-- pybind11 v2.6.3 dev1
-- Build spdlog: 1.4.1
-- Build type: Release
-- Could NOT find libdw (missing: LIBDW_LIBRARY LIBDW_INCLUDE_DIR)
-- Could NOT find libbfd (missing: LIBBFD_LIBRARY LIBBFD_INCLUDE_DIR LIBDL_LIBRARY LIBDL_INCLUDE_DIR)
-- Could NOT find libdwarf (missing: LIBDWARF_LIBRARY LIBDWARF_INCLUDE_DIR LIBELF_LIBRARY LIBELF_INCLUDE_DIR LIBDL_LIBRARY LIBDL_INCLUDE_DIR)
found package: OpenMP::OpenMP_CXX
*** Building ZENO with extension: ZenoFX
found package: OpenMP::OpenMP_CXX
*** Building ZENO with extension: oldzenbase
found package: OpenMP::OpenMP_CXX
*** Building ZENO with extension: Alembic
CMake Error at projects/Alembic/CMakeLists.txt:11 (find_package):
  Could not find a package configuration file provided by "Alembic" with any
  of the following names:

    AlembicConfig.cmake
    alembic-config.cmake

  Add the installation prefix of "Alembic" to CMAKE_PREFIX_PATH or set
  "Alembic_DIR" to a directory containing one of the above files.  If
  "Alembic" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
See also "D:/zeno/build/CMakeFiles/CMakeOutput.log".
See also "D:/zeno/build/CMakeFiles/CMakeError.log".
```

**Comment by JonLiu1993** [comment]
@zhouhang95 ,Thanks for posting this issue, could you please provide your main.cpp and CMakeLists.txt? I can't reproduce your issue locally
````
LCHAIN_FILE=/home/Jon/vcpkg/scripts/buildsystems/vcpkg.cmake ..
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: //home/Jon/test2/build

````

**Comment by zhouhang95** [comment]
i use windows

**Comment by JonLiu1993** [comment]
> Thanks, but i use windows

@zhouhang95 ,Currently alembic dosent't support window
````
alembic[core] is only supported on '!(windows & x86) & !uwp'
````
I am curious why you can successfully install alembic on the windows platform?

**Comment by dg0yt** [comment]
> @zhouhang95 ,Currently alembic dosent't support window
> 
> ```
> alembic[core] is only supported on '!(windows & x86) & !uwp'
> ```

x64-windows seems to be supported.

**Comment by zhouhang95** [comment]
D:\vcpkg>vcpkg install alembic:x64-windows
Computing installation plan...
The following packages are already installed:
    alembic[core]:x64-windows -> 1.8.3
Package alembic:x64-windows is already installed
Restored 0 packages from C:\Users\zenus\AppData\Local\vcpkg\archives in 129.8 us. Use --debug to see more details.

Total elapsed time: 485.2 ms

The package alembic provides CMake targets:

    find_package(Alembic CONFIG REQUIRED)
    target_link_libraries(main PRIVATE Alembic::Alembic)

**Comment by JonLiu1993** [comment]
I try again x64-windows seems to be supported. I will reproduce again your issue,

**Comment by PhoebeHui** [comment]
@zhouhang95, could you provide us your CMakeLists.txt and main.cpp file to repro this issue? I create a minimal test code, everything works as expected. Could you get latest source via 'git pull' & 'bootstrap-vcpkg.bat' and try again?

The repro steps:
1. ./vcpkg install alembic:x64-windows
2. ./vcpkg integrate install
3. Create test code as following:

CMakeLists.txt
```
cmake_minimum_required(VERSION 3.0)
project(test)
add_executable(test main.cpp)

find_package(Alembic CONFIG REQUIRED)
target_link_libraries(test PRIVATE Alembic::Alembic)
```

main.cpp
```
#include "Alembic/Abc/All.h"

int main()
{
    return 0;
}
```

4. E:\vcpkg\vcpkgtest\alembic>cmake -Bbuild -DCMAKE_TOOLCHAIN_FILE=E:/vcpkg/src/vcpkg/scripts/buildsystems/vcpkg.cmake

```
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19044.
-- The C compiler identification is MSVC 19.29.30137.0
-- The CXX compiler identification is MSVC 19.29.30137.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: E:/vcpkg/vcpkgtest/alembic/build
```

**Comment by zhouhang95** [comment]
@PhoebeHui 
It's my problem.
I delete all vcpkg, reisntall it. It works.
But now new problem.

https://github.com/alembic/alembic
```
    -DUSE_HDF5=ON
    Specify this if you want to include optional HDF5 support.
    -DHDF_ROOT=HDF5Path may need to be specified if HDF5 is not installed in
    a standard location.
```
I need this flag is ON, but default is OFF.
How i turn this flag on?

**Comment by PhoebeHui** [comment]
@zhouhang95, you can enable it via './vcpkg install alembic[hdf5]:x64-windows'.
