### ISSUE TITLE
[x64-windows-static] SDL2-static not found

### ISSUE THREAD

**Issue by Raffaello** [microsoft/vcpkg#21746]
**Describe the bug**
When generating CMAKE using SDL2-static as a target link library, is reported to be not found.

**Environment**
- OS: windows
- Compiler: CMAKE generation

**To Reproduce**
1. ./vcpkg install sdl2 --triplet x64-windows
2. ./vcpkg install sdl2 --triplet x64-windows-static
```
The package sdl2 provides CMake targets:

    find_package(SDL2 CONFIG REQUIRED)
    target_link_libraries(main PRIVATE SDL2::SDL2 SDL2::SDL2main SDL2::SDL2-static)

```
2. Error when CMAKE is generating:
```
1> [CMake] CMake Error at [...]/vcpkg/scripts/buildsystems/vcpkg.cmake:540 (_add_executable):
1> [CMake]   Target "sdl2-static-example" links to target "SDL2::SDL2-static" but the
1> [CMake]   target was not found.  Perhaps a find_package() call is missing for an
1> [CMake]   IMPORTED target, or an ALIAS target is missing?
1> [CMake] Call Stack (most recent call first):
1> [CMake]   sdl2-static-example/CMakeLists.txt:9 (add_executable)
1> [CMake] -- Generating done
```

CMAKE settings just a default VS CMAKE file with:
```
find_package(SDL2 CONFIG REQUIRED)

# Add source to this project's executable.
add_executable (sdl2-static-example "sdl2-static-example.cpp" "sdl2-static-example.h")
target_link_libraries(sdl2-static-example SDL2::SDL2-static)
```

**Expected behavior**
I was expecting that `SDL2::SDL2-static` was available to be linked. 

**Failure logs** 
-(please attached failure logs)
```
1> [CMake] CMake Error at [...]/vcpkg/scripts/buildsystems/vcpkg.cmake:540 (_add_executable):
1> [CMake]   Target "sdl2-static-example" links to target "SDL2::SDL2-static" but the
1> [CMake]   target was not found.  Perhaps a find_package() call is missing for an
1> [CMake]   IMPORTED target, or an ALIAS target is missing?
1> [CMake] Call Stack (most recent call first):
1> [CMake]   sdl2-static-example/CMakeLists.txt:9 (add_executable)
1> [CMake] -- Generating done
```

**Additional context**
It is just enough to try a simple cmake project using sdl2-static in windows.
I know before adding the triplet x64-windows-static that it was working. 
Now it seems or either broken or the CMAKE config might required a slightly different setting to link to static library?

**Comment by Raffaello** [comment]
OK i found the "issue" here, In CMAKE settings now, when using the {{lib}}-static (SDL2-static), it is required to change also the CMAKE `VCPKG_TARGET_TRIPLET` to `x64-windows-static` ... 
This is a little bit annoying as it requires to have a "meta configuration" when using a static library too instead of just switches in cmake. 
But anyway definitely not a bug as it works.

**Comment by Raffaello** [comment]
I am just wondering if using a mix of `x64-windows-static` and `x64-windows` triplets would be possible now... It looks it won't.

**Comment by JackBoosY** [comment]
I don't know why you need to use the sdl dynamic library and static library at the same time, which will obviously cause symbol conflict errors.

**Comment by Raffaello** [comment]
> I don't know why you need to use the sdl dynamic library and static library at the same time, which will obviously cause symbol conflict errors.

No I don't. At the same time just wanting an option to let the user decide one or another and requires to regenerate CMAKE with a different triplet, didn't check it yet, but if  the `x64-windows-static` SDL2::SDL2 would be an alias for ``SDL2::SDL2-static` would be ok, no need to have a CMAKE option for SDL2-static eventually....

My other thought was on a general basis, mixing different library some with dynamic linking and other with static linking. It is arguable someone can just go fully static or dynamic anyway it was just a thought as compiler can allow this kind of mix, but with this new vcpkg triplet it is a discouraged approach.

**Comment by JackBoosY** [comment]
@Raffaello The upstream does add the opposite target `SDL2::SDL2` / `SDL2::SDL2-static`. It's the upstream behavior so I think we shouldn't touch it.

In vcpkg, you can only build and use one triple at a time in one configuration.

**Comment by JackBoosY** [comment]
> At the same time just wanting an option to let the user decide one or another and requires to regenerate CMAKE with a different triplet

So I think you should use overlay ports to achieve dynamic/static switching when using existing triplet.

**Comment by Raffaello** [comment]
> > At the same time just wanting an option to let the user decide one or another and requires to regenerate CMAKE with a different triplet
> 
> So I think you should use overlay ports to achieve dynamic/static switching when using the current triplet.

i see.

Not a problem, it looks like is not an helper using `vcpkg`,  I was using as a optional dependency manager to help CMAKE generating the "make files" as it shouldn't be strictly required to use with Cmake, but just as an helper eventually.

Basically, with the new static triplet, there is a lot of more work to accommodate the usage of vcpkg if wanting a switch among a static or dynamic 3rd party library linking as it has a completely mutual exclusive set of dynamic or static triplet. 
Doing a port is a workaround due this mutual exclusive set of triplets.

My starting point is like: doing the CMake config without vcpkg, if you want to use vcpkg then use it without too many hassles, just enough to give the right target compilation. But spitting further static/dynamic, it would conflict using cmake without using vcpkg as it will require also cmake option for the static dynamic switch apart a different "triplet". 

In this case it is not a triplet anymore but rather has become a **quartet**: it has arch (x86/x64), configuration type (debug/release), OS (windows/linux/etc..) and the 4th value is a (dynamic( implicit default) / static).

Anyway, thanks at the moment I found simpler to remove the static option and force to use just dynamic.

**Comment by JackBoosY** [comment]
If you have any other questions, please leave them here.
