### ISSUE TITLE
[Documentation] Triplet docs should mention that none or all of VCPKG_lang_FLAGS have to be defined

### ISSUE THREAD

**Issue by horenmar** [microsoft/vcpkg#21752]
**Describe the bug**
Exactly what it says in the title. I am doing bunch of work with custom triplets, and my build failed about an hour in with error message that if either of `VCPKG_CXX_FLAGS` or `VCPKG_C_FLAGS` are defined, then the other flags have to be defined as well.

I would prefer to find this out from the documentation :smiley:

**Comment by sfhacker** [comment]
This issue is from 2021!
