### ISSUE TITLE
[x64-linux] SDL2 doesn't work, linking issues

### ISSUE THREAD

**Issue by Raffaello** [microsoft/vcpkg#21750]
**Describe the bug**
if installing SDL2 for linux, the application won't compile.
It is forced to install sdl2[x11] along side SDL2 package and it is only a specific package for linux.

**Environment**
- OS: Linux
- Compiler: GCC

**To Reproduce**
1. ./vcpkg install SDL2
2. See error
```
[ 25%] Linking CXX shared library libvga-terminald.so
../../vcpkg/installed/x64-linux/debug/lib/libSDL2d.a(SDL_x11dyn.c.o): In function `SDL_X11_LoadSymbols':
/home/vsts/work/1/s/vcpkg/buildtrees/sdl2/src/ase-2.0.16-139ee71275.clean/src/video/x11/SDL_x11sym.h:33: undefined reference to `XAllocSizeHints'
```

**Expected behavior**
when installing SDL2 package for linux should be implicit to install also SDL2[x11] as otherwise won't work.
It is silly to install 2 packages just to make work 1. 
The logical split can be ok, but should be defaulted to install SDL2[x11] as dependency otherwise won't work.
At least for my actual understading.

**Failure logs** 
-(please attached failure logs)
```
[ 25%] Linking CXX shared library libvga-terminald.so
../../vcpkg/installed/x64-linux/debug/lib/libSDL2d.a(SDL_x11dyn.c.o): In function `SDL_X11_LoadSymbols':
/home/vsts/work/1/s/vcpkg/buildtrees/sdl2/src/ase-2.0.16-139ee71275.clean/src/video/x11/SDL_x11sym.h:33: undefined reference to `XAllocSizeHints'
```
**Additional context**
It also makes more complicated to have cross-os dependency managed by `vcpkg` as just for linux there is an extra packge to install.
Just imagine doing a CI with that, can't really be too much generalized..
It would just be simpler to have it as it was before:
when installing SDL2 pacakge through vcpkg, should be default to install SDL2 and SDL2[x11], unless specified otherwise.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Did you install sdl2 failed on Linux or use `find_package(SDL2 CONFIG REQUIRED)` to link sdl2 error? I can install sdl2 succeed on Linux and use `find_package(SDL2 CONFIG REQUIRED)` in sample repro project. Please provide detail steps and error log.

**Comment by LilyWangLL** [comment]
@Raffaello Thanks for you detail reply. For this issue:
1. Since x11 can only be installed on UNIX, and the keyword `default feature` in manifest file doesn't support triplet expression. so it can't be add to default feature. And I think you should declare feature `x11` in the install command manually.
2. We confirmed this issue is a port bug and I will fix this issue soon.

**Comment by Thomas1664** [comment]
@LilyWangLL #28148 enabled X11 on Linux by default. I think this issue can be closed now?
