### ISSUE TITLE
szip failed to download

### ISSUE THREAD

**Issue by jasjuang** [Microsoft/vcpkg#2175]
`vcpkg install szip` shows

```
-- Downloading http://hdf4.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.0-patch1/src/CMake-hdf5-1.10.0-patch1.zip...
-- Downloading http://hdf4.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.0-patch1/src/CMake-hdf5-1.10.0-patch1.zip... Failed. Status: 22;"HTTP response code said error"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:91 (message):


      Failed to download file.
      Add mirrors or submit an issue at https://github.com/Microsoft/vcpkg/issues
```

I couldn't find an official github repo for szip to update it with `vcpkg_from_github`. How do we solve this?

**Comment by ras0219-msft** [comment]
It looks like the hdf group reformatted their website, but I can't find the old patch on it. I think the best long term option is to engage with them over email and figure out what url we should be using.

However, that doesn't solve the short-term problem for libs that depend on hdf5. Perhaps we try building without the patch and see if there is a more minimal fix we can check in to unblock things?

**Comment by jasjuang** [comment]
I just sent them an email to ask them the same question. Currently the
workaround I am doing is copying the hdf5 zip file from another computer of
mine to the current one.

**Comment by jasjuang** [comment]
The ftp is fixed now
