### ISSUE TITLE
[triplets] Handle VCPKG_lang_FLAGS being a list, not a string

### ISSUE THREAD

**Issue by horenmar** [microsoft/vcpkg#21753]
**Is your feature request related to a problem? Please describe.**

I am using custom triplet to, among other things, build our dependencies with hidden visibility for symbols. This works well enough if that is the only customization I want to make, but breaks if I have multiple ones (e.g. disabling RTTI).

This triplet file seems correct but will break during configuration:
```cmake
if (NOT ${PORT} MATCHES "opencv")
  set(VCPKG_C_FLAGS "-fno-rtti")
  set(VCPKG_CXX_FLAGS "-fno-rtti")
endif ()

if (NOT ${PORT} MATCHES "ffmpeg")
  list(APPEND VCPKG_C_FLAGS "-fvisibility=hidden" "-fvisibility-inlines-hidden")
  list(APPEND VCPKG_CXX_FLAGS "-fvisibility=hidden" "-fvisibility-inlines-hidden")
endif()
```

As far as I can tell, the workaround is to change the later changes to `VCPKG_CXX_FLAGS` to `set(VCPKG_CXX_FLAGS "${VCPKG_CXX_FLAGS} -fvisibility=hidden -fvisibility-inlines-hidden")` to keep the value as a single string.

**Proposed solution**
I would want this behaviour to be at least documented in the triplet documentation, or for vcpkg to handle the case where `VCPKG_CXX_FLAGS` is a list of strings specially.

**Comment by JackBoosY** [comment]
Using cmake list to deal with CFLAGS or CXXFLAGS is a disaster.
Cmake will automatically splice the contents of the list or completely with semicolons according to the usage scenario, and this will cause the compiler to fail to recognize these flags.

**Comment by dg0yt** [comment]
Note that these variables just mirror cmake flags which are also implemented as string, not list. 

> vcpkg to handle the case where VCPKG_CXX_FLAGS is a list of strings specially.

This is not possible. There is no way to know if a cmake variable is list, or a string which contains `;`.

**Comment by horenmar** [comment]
> This is not possible. There is no way to know if a cmake variable is list, or a string which contains ;.

CMake strikes again I guess.

--------

Well, I would still like the documentation for triplets to be better.
