### ISSUE TITLE
xxhash update to 0.81

### ISSUE THREAD

**Issue by hros** [microsoft/vcpkg#21769]
please update xxhash (https://github.com/Cyan4973/xxHash) to version 0.81 

additionally, please let me know how can choose a specific version when installing a port.  for example, if I want to build version 0.8 what would be the command parameters?

**Comment by JonLiu1993** [comment]
Fix by #21761

**Comment by hros** [comment]
Thanks

Please let me know the syntax for:
1. Installing a specific (older) version of a library
2. Creating a shared library (.so)

**Comment by JonLiu1993** [comment]
@hros ,
1.How to install specific version?  you can refer this issue:#21357
2.Creating a shared library (.so)

I don't quite understand the meaning of your second question, Could you please describe your question in detail.

**Comment by hros** [comment]
When building xxhash with vcpkg I only get static libraries (.a), whereas the default makefile in the xxhash project builds a shared library (.so)

**Comment by JonLiu1993** [comment]
@hros ,If you want build builds a shared library (.so), you can create a cmake file named x64-linux-dynamic.cmake:
````
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)

set(VCPKG_CMAKE_SYSTEM_NAME Linux)
````
Then use ./vcpkg install x64-linux --dynamic to compile under linux
