### ISSUE TITLE
[cpprestsdk] build failure

### ISSUE THREAD

**Issue by xuhancn** [microsoft/vcpkg#21766]
**Host Environment**
- OS: Win11
- Compiler: VS2017

**To Reproduce**
`./vcpkg install cpprestsdk:x64-windows-static`

**Failure logs** 
Error: Building package cpprestsdk:x64-windows-static failed with: BUILD_FAILED
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
Package: cpprestsdk:x64-windows-static
Vcpkg version: 2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9

**Additional context**
Still not solved, it works in another PC 4 months ago.

**Comment by JonLiu1993** [comment]
@xuhancn ,Thanks for posting this issue, could you please provide the detail error log?

**Comment by xuhancn** [comment]
> @xuhancn ,Thanks for posting this issue, could you please provide the detail error log?

[1/25] C:\PROGRA~2\MICROS~1.0\VC\bin\amd64\cl.exe   /TP -DCPPREST_EXCLUDE_WEBSOCKETS=1 -DUNICODE -DWIN32 -D_NO_ASYNCRTIMP -D_NO_PPLXIMP -D_SCL_SECURE_NO_WARNINGS -D_UNICODE -D_WIN32_WINNT=0x0600 -D_WINSOCK_DEPRECATED_NO_WARNINGS -ID:\xu_git\vcpkg\buildtrees\cpprestsdk\src\ecb9e168c5-96a8d6ba89.clean\Release\include -ID:\xu_git\vcpkg\buildtrees\cpprestsdk\src\ecb9e168c5-96a8d6ba89.clean\Release\src\pch -ID:\xu_git\vcpkg\installed\x64-windows-static\include /nologo /DWIN32 /D_WINDOWS /W3  /GR /EHsc /MP  /D_DEBUG /MTd /Z7 /Ob0 /Od /RTC1  /MP /bigobj /Yustdafx.h /FpD:/xu_git/vcpkg/buildtrees/cpprestsdk/x64-windows-static-dbg/src/cpprest.pch /Zm120 /Ycstdafx.h /showIncludes /Fosrc\CMakeFiles\cpprest.dir\pch\stdafx.cpp.obj /Fdsrc\CMakeFiles\cpprest.dir\cpprest.pdb /FS -c D:\xu_git\vcpkg\buildtrees\cpprestsdk\src\ecb9e168c5-96a8d6ba89.clean\Release\src\pch\stdafx.cpp
FAILED: src/CMakeFiles/cpprest.dir/pch/stdafx.cpp.obj 
C:\PROGRA~2\MICROS~1.0\VC\bin\amd64\cl.exe   /TP -DCPPREST_EXCLUDE_WEBSOCKETS=1 -DUNICODE -DWIN32 -D_NO_ASYNCRTIMP -D_NO_PPLXIMP -D_SCL_SECURE_NO_WARNINGS -D_UNICODE -D_WIN32_WINNT=0x0600 -D_WINSOCK_DEPRECATED_NO_WARNINGS -ID:\xu_git\vcpkg\buildtrees\cpprestsdk\src\ecb9e168c5-96a8d6ba89.clean\Release\include -ID:\xu_git\vcpkg\buildtrees\cpprestsdk\src\ecb9e168c5-96a8d6ba89.clean\Release\src\pch -ID:\xu_git\vcpkg\installed\x64-windows-static\include /nologo /DWIN32 /D_WINDOWS /W3  /GR /EHsc /MP  /D_DEBUG /MTd /Z7 /Ob0 /Od /RTC1  /MP /bigobj /Yustdafx.h /FpD:/xu_git/vcpkg/buildtrees/cpprestsdk/x64-windows-static-dbg/src/cpprest.pch /Zm120 /Ycstdafx.h /showIncludes /Fosrc\CMakeFiles\cpprest.dir\pch\stdafx.cpp.obj /Fdsrc\CMakeFiles\cpprest.dir\cpprest.pdb /FS -c D:\xu_git\vcpkg\buildtrees\cpprestsdk\src\ecb9e168c5-96a8d6ba89.clean\Release\src\pch\stdafx.cpp
D:\xu_git\vcpkg\buildtrees\cpprestsdk\src\ecb9e168c5-96a8d6ba89.clean\Release\include\cpprest/details/SafeInt3.hpp(6025) : error C2146: syntax error : missing ';' before identifier 'SafeInt'
        D:\xu_git\vcpkg\buildtrees\cpprestsdk\src\ecb9e168c5-96a8d6ba89.clean\Release\include\cpprest/details/SafeInt3.hpp(6834) : see reference to class template instantiation 'msl::safeint3::SafeInt<T,E>' being compiled
D:\xu_git\vcpkg\buildtrees\cpprestsdk\src\ecb9e168c5-96a8d6ba89.clean\Release\include\cpprest/details/SafeInt3.hpp(6025) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
ninja: build stopped: subcommand failed.
------------------------------------------------------------
If you need more log, pls list to me. Thanks.

**Comment by JackBoosY** [comment]
```
D:\xu_git\vcpkg\buildtrees\cpprestsdk\src\ecb9e168c5-96a8d6ba89.clean\Release\include\cpprest/details/SafeInt3.hpp(6025) : error C2146: syntax error : missing ';' before identifier 'SafeInt'
```

**Comment by FrankXie05** [comment]
@xuhancn 
url: [set-C++11.zip](https://github.com/microsoft/vcpkg/files/7640561/set-C%2B%2B11.zip)
I think it's possible that VC2017 did not use C++11, so I appiled a patch to use it. 
And I Successfully build it. Cna you try it? 
If  fails, connect me in time. :)

**Comment by xuhancn** [comment]
> 

Still build failed：
--------------------------------------------------------
PS D:\xu_git\vcpkg> ./vcpkg install cpprestsdk:x64-windows-static
Computing installation plan...
The following packages will be built and installed:
    cpprestsdk[brotli,compression,core,default-features]:x64-windows-static -> 2.10.18
Detecting compiler hash for triplet x64-windows-static...
Restored 0 packages from C:\Users\xu\AppData\Local\vcpkg\archives in 119.4 us. Use --debug to see more details.
Starting package 1/1: cpprestsdk:x64-windows-static
Building package cpprestsdk[brotli,compression,core,default-features]:x64-windows-static...
-- Using cached Microsoft-cpprestsdk-122d09549201da5383321d870bed45ecb9e168c5.tar.gz.
-- Cleaning sources at D:/xu_git/vcpkg/buildtrees/cpprestsdk/src/ecb9e168c5-3ce7c4f9f6.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/xu_git/vcpkg/downloads/Microsoft-cpprestsdk-122d09549201da5383321d870bed45ecb9e168c5.tar.gz
-- Applying patch fix-find-openssl.patch
-- Applying patch set-C++11.patch
-- Using source at D:/xu_git/vcpkg/buildtrees/cpprestsdk/src/ecb9e168c5-3ce7c4f9f6.clean
-- Configuring x64-windows-static
CMake Warning at scripts/cmake/vcpkg_configure_cmake.cmake:410 (message):
  The following variables are not used in CMakeLists.txt:

      WEBSOCKETPP_CONFIG
      WEBSOCKETPP_CONFIG_VERSION

  Please recheck them and remove the unnecessary options from the
  `vcpkg_configure_cmake` call.

  If these options should still be passed for whatever reason, please use the
  `MAYBE_UNUSED_VARIABLES` argument.
Call Stack (most recent call first):
  ports/cpprestsdk/portfile.cmake:28 (vcpkg_configure_cmake)
  scripts/ports.cmake:142 (include)


-- Building x64-windows-static-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:155 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j17
    Working Directory: D:/xu_git/vcpkg/buildtrees/cpprestsdk/x64-windows-static-dbg
    See logs for more information:
      D:\xu_git\vcpkg\buildtrees\cpprestsdk\install-x64-windows-static-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:106 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:44 (vcpkg_build_cmake)
  ports/cpprestsdk/portfile.cmake:43 (vcpkg_install_cmake)
  scripts/ports.cmake:142 (include)


Error: Building package cpprestsdk:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+cpprestsdk
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[cpprestsdk]+Build+error
including:
  package: cpprestsdk[brotli,compression,core,default-features]:x64-windows-static -> 2.10.18
    vcpkg-tool version: 2021-11-24-48b94a6946b8a70abd21529218927fd478d02b6c
    vcpkg-scripts version: 5ddd7f026 2021-12-01 (9 hours ago)

Additionally, attach any relevant sections from the log files above.
PS D:\xu_git\vcpkg>

**Comment by FrankXie05** [comment]
@xuhancn could you please provide the detail error log?

**Comment by xuhancn** [comment]
> @xuhancn could you please provide the detail error log?
> 
> ```
> D:\xu_git\vcpkg\buildtrees\cpprestsdk\install-x64-windows-static-dbg-out.log
> ```

I tried to repo issue and find it only build failed in Chinese language Visual Studio.
---------------------------------------------------------------------------
Microsoft Visual Studio Community 2017 
版本 15.9.38
VisualStudio.15.Release/15.9.38+28307.1622
Microsoft .NET Framework
版本 4.8.04161

已安装的版本: Community

Visual C++ 2017   00369-60000-00001-AA144
Microsoft Visual C++ 2017

ASP.NET and Web Tools 2017   15.9.04012.0
ASP.NET and Web Tools 2017

C# 工具   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
在 IDE 中使用的 C# 组件。根据项目类型和设置，可能会使用不同版本的编译器。

JavaScript 语言服务   2.0
JavaScript 语言服务

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ 向导   1.0
Microsoft Visual C++ 向导

Microsoft Visual Studio VC 软件包   1.0
Microsoft Visual Studio VC 软件包

MLGen Package Extension   1.0
MLGen Package Visual Studio Extension Detailed Info

NuGet 包管理器   4.6.0
Visual Studio 中的 NuGet 包管理器。有关 NuGet 的详细信息，请访问 http://docs.nuget.org/。

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Visual Basic 工具   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
在 IDE 中使用 Visual Basic 组件。根据项目类型和设置，可能会使用不同版本的编译器。

Visual Studio Code 调试适配器主机包   1.0
用于在 Visual Studio 中托管 Visual Studio Code 调试适配器的互操作层

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

适用于 Google Test 的测试适配器   1.0
启用带有针对 Google Test 编写的单元测试的 Visual Studio 测试工具。扩展安装目录中提供了使用条款和第三方通知。

**Comment by JackBoosY** [comment]
Please make sure you've installed the English Language Package using Visual Studio Installer first.

**Comment by xuhancn** [comment]
> Please make sure you've installed the English Language Package using Visual Studio Installer first.

You means try to install English Language Package to narrow down issue?

**Comment by JackBoosY** [comment]
@xuhancn  No, it may fix this issue.

**Comment by xuhancn** [comment]
@JackBoosY it works when change to English language package. 
So, if I can understand that, vcpkg is not support Chinese language package offically?

**Comment by JackBoosY** [comment]
@xuhancn vcpkg requires the English Lanugage package to do some magic things.
