### ISSUE TITLE
vcpkg installed libraries do not auto-link from command line

### ISSUE THREAD

**Issue by Meneleus** [microsoft/vcpkg#21760]
I could have sworn this used to work, I re-staged my machine and reinstalled my packages. In particular I'm using https://github.com/grpc/grpc/tree/master/src/cpp instructions for Packaging systems. Projects run in the Visual Studio IDE 2019 work fine. However, using nmake to build the project fails to link. Is there any workaround? Do I need to manually link? I tried adding every single .lib but it still would not work...

**Comment by JackBoosY** [comment]
Which triplet do you use?
Can you please provide a failure logs?

**Comment by autoantwort** [comment]
The auto-link functionality is only implemented for msbuild and not for nmake.

**Comment by Meneleus** [comment]
> The auto-link functionality is only implemented for msbuild and not for nmake.

We’ll that explains it then. I guess I’m just not remembering correctly. Thank you.
