### ISSUE TITLE
[qt5-base] build failure: arm64-linux with dynamic linkage

### ISSUE THREAD

**Issue by charles-sun0v0** [microsoft/vcpkg#21778]
**Host Environment**
- OS:Ubuntu 18.04, arm64-linux
- Compiler:gcc 7.5

**To Reproduce**
1. Modify triplets so that qt5-base will be built as a dynamic linkage library:
   ```
    set(VCPKG_TARGET_ARCHITECTURE arm64)
    set(VCPKG_CRT_LINKAGE dynamic)
    set(VCPKG_LIBRARY_LINKAGE static)

    set(VCPKG_CMAKE_SYSTEM_NAME Linux)

    if(PORT MATCHES "qt5-")
         set(VCPKG_LIBRARY_LINKAGE dynamic)
    endif()

   if(NOT CMAKE_HOST_SYSTEM_PROCESSOR)
         execute_process(COMMAND "uname" "-m" OUTPUT_VARIABLE 
    CMAKE_HOST_SYSTEM_PROCESSOR OUTPUT_STRIP_TRAILING_WHITESPACE)
    endif()
   ```
2. install
`./vcpkg install qt5-base`

**Failure logs**
[build-arm64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/7630541/build-arm64-linux-dbg-out.log)
 [build-arm64-linux-dbg-err.log](https://github.com/microsoft/vcpkg/files/7630543/build-arm64-linux-dbg-err.log)

It reads 
```
vcpkg/installed/arm64-linux/debug/lib/libfreetyped.a(sfnt.c.o): In function `woff2_decompress':
vcpkg/buildtrees/freetype/src/bf1991f3c3-78ecfbc293.clean/src/sfnt/sfwoff2.c:327: undefined reference to `BrotliDecoderDecompress'
```

**Comment by JackBoosY** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.

**Comment by ikulagin** [comment]
The issue is still there. Please, reopen this issue.

**Comment by ikulagin** [comment]
The temporary solution of this issue:
```
if((PORT MATCHES "qt5-")
  OR (PORT MATCHES "freetype")
  OR (PORT MATCHES "jasper"))
    set(VCPKG_LIBRARY_LINKAGE dynamic)
endif()
```

**Comment by JonLiu1993** [comment]
@ikulagin ,Thanks for the suggestion, could you submit a pr to fix this issue?

**Comment by dg0yt** [comment]
> @ikulagin ,Thanks for the suggestion, could you submit a pr to fix this issue?

@JonLiu1993 This was a workaround with a massive side effect, not something acceptable as a PR.

**Comment by JonLiu1993** [comment]
> > @ikulagin ,Thanks for the suggestion, could you submit a pr to fix this issue?
> 
> @JonLiu1993 This was a workaround with a massive side effect, not something acceptable as a PR.

OK, it seems that we still need a new solution for this issue

**Comment by JonLiu1993** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.

**Comment by KOConchobhair** [comment]
Qt5 dynamic with freetype static needs all of freetype's dependencies in Qt5's portfile.cmake.
latest versions of freetype depends on brotli so Qt5 has to too. 
building freetype as dynamic is not a terrible workaround but the issue is fixed in current vcpkg baseline as of this writing but using overrides you can easily find yourself back in this position. 
so just leaving this note here for future google searches, no need to reopen the issue.

**Comment by dg0yt** [comment]
@KOConchobhair This is what the qt5-base portfile does:
https://github.com/microsoft/vcpkg/blob/4a3c366f2d0d0eaf034bfa649124768df7cfe813/ports/qt5-base/portfile.cmake#L201-L202
I assume it works correctly for the standard triplets (all libs static or all libs dynamic, not mixed).

**Comment by KOConchobhair** [comment]
> I assume it works correctly for the standard triplets (all libs static or all libs dynamic, not mixed).
> 
@dg0yt is there a reason why it won't work for mixed too?
with qt5 dynamic and freetype(bzip,png,zlib,brotli,etc.) static, don't these lines in qt5-base portfile pick it up?

https://github.com/microsoft/vcpkg/blob/4a3c366f2d0d0eaf034bfa649124768df7cfe813/ports/qt5-base/portfile.cmake#L161-L164
