### ISSUE TITLE
[qt]: qt build failure on Mac M1

### ISSUE THREAD

**Issue by ilongshan** [microsoft/vcpkg#21779]
**Describe the bug**
qt doesn't support Mac M1

**Environment**
- OS: Mac
- Compiler: Apple clang version 13.0.0 (clang-1300.0.29.3)

**To Reproduce**
1. ./vcpkg install qt
2. See error
Computing installation plan...
Error: x264[core] is only supported on '!arm'

**Expected behavior**
Hope it supports Mac M1

**Comment by JackBoosY** [comment]
Duplicated to #21767.
