### ISSUE TITLE
[rocksDB] update to <6.26.1>

### ISSUE THREAD

**Issue by luyenbuuhuy** [microsoft/vcpkg#21785]
Library name: RocksDB

New version number: 6.26.1

Source: https://github.com/facebook/rocksdb/releases/tag/v6.26.1

**Comment by FrankXie05** [comment]
@luyenbuuhuy ,Thanks for posting this issue, this version has been update and merged, see  #21661

**Comment by FrankXie05** [comment]
@luyenbuuhuy  Use the command: git pull to update, then you can use this version :)

**Comment by luyenbuuhuy** [comment]
@FrankXie05: Thank you! :)
