### ISSUE TITLE
[refprop-headers] Build failed

### ISSUE THREAD

**Issue by nitrogene** [Microsoft/vcpkg#2178]
Following resolution of #2166, I tried to install coolprop, but failed. There is an error in the portfile:

D:\Dev\vcpkg\ports\refprop-headers\portfile.cmake, on line 5 ${SOURCE_PATH} should be replaced by SOURCE_PATH (this is the same issue than for #2166).

**Comment by ras0219-msft** [comment]
Thanks for reporting this! I've corrected it in `refprop-headers` as well as a full sweep of all other portfiles :)
