### ISSUE TITLE
vcpkg install with triplet take too much time.

### ISSUE THREAD

**Issue by xiaoyifang** [microsoft/vcpkg#21792]
**Describe the bug**
  `vcpkg.exe install lzo --triplet=x64-mingw-static`
vcpkg install takes too much time ,>14 mins.

**Environment**
- OS: Windows
- Compiler: revision

**To Reproduce**
1. vcpkg.exe install lzo  --triplet=x64-mingw-static
2. See error
no error,but takes too much time.

**Expected behavior**
take less time to install
**Failure logs** 
-(please attached failure logs)

[log.txt](https://github.com/microsoft/vcpkg/files/7632720/log.txt)
**Additional context**

**Comment by dg0yt** [comment]
Only 90 s here.

**Comment by xiaoyifang** [comment]
install ffmpeg will cost 2 hours in my computer.
any solution to reduce the time.
would it better to offer some precompiled library as an option.

**Comment by JackBoosY** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
