### ISSUE TITLE
[New Port Request] libao

### ISSUE THREAD

**Issue by xiaoyifang** [microsoft/vcpkg#21791]
Library name: libao

Library description:
Libao is a cross-platform audio library that allows programs to output audio using a simple API on a wide variety of platforms. It currently supports:

Null output (handy for testing without a sound device)
WAV files
AU files
RAW files
OSS (Open Sound System, used on Linux and FreeBSD)
ALSA (Advanced Linux Sound Architecture)
aRts (Analog RealTime Synth, used by KDE)
PulseAudio (next generation GNOME sound server)
esd (EsounD or Enlightened Sound Daemon)
Mac OS X
Windows (98 and later)
AIX
Sun/NetBSD/OpenBSD
IRIX
NAS (Network Audio Server)
RoarAudio (Modern, multi-OS, networked Sound System)
OpenBSD's sndio
Source repository URL:
https://gitlab.xiph.org/xiph/libao
Project homepage (if different from the source repository):
https://www.xiph.org/ao/
Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
