### ISSUE TITLE
[curl] update to <7.80.0>

### ISSUE THREAD

**Issue by ensiform** [microsoft/vcpkg#21794]
Library name: curl / libcurl

New version number: 7.80.0

https://github.com/curl/curl/releases/tag/curl-7_80_0

Released November 10, 2021

Changelog: https://curl.se/changes.html#7_80_0

**Comment by dg0yt** [comment]
Already done, #21554.

**Comment by ensiform** [comment]
Whoops, I still noticed 7.79 in port list on https://vcpkg.io/en/packages.html
