### ISSUE TITLE
Upgrading OpenSSL from 1.0.2h to 1.1.0

### ISSUE THREAD

**Issue by alexkaratarakis** [microsoft/vcpkg#218]
We are considering updating OpenSSL to 1.1.0.
However, there are some breaking changes in OpenSSL 1.1.0, as outlined here: 
https://wiki.openssl.org/index.php/1.1_API_Changes

If you have tried upgrading to OpenSSL, please post your experience here.
Were you able/unable to update? If you did manage to upgrade, what was the extent of changes that were required?

**Comment by KindDragon** [comment]
I tried to compile grpc and folly with [OpenSSL 1.1.0](https://github.com/KindDragon/vcpkg/tree/openssl-1.1.0) and... grpc doesn't compile
https://github.com/grpc/grpc/issues/8801

**Comment by KindDragon** [comment]
CppRestSDK 2.9.0 too, but you probably already know about it :)

**Comment by KindDragon** [comment]
websocketpp https://github.com/zaphoyd/websocketpp/issues/599

**Comment by thierryba** [comment]
May I suggest that openssl1.1 be a different port from 1.0.2. Not every 3rdparty is compatible yet. And if you look at brew on Mac you have both 1.0.2 and 1.1.0.
Doing so would allow other libs to be upgraded carefully and willingly choose to switch to the new openssl.

**Comment by strega-nil** [comment]
Fixed!
