### ISSUE TITLE
[Qt] update Qt6 to <6.2.2>

### ISSUE THREAD

**Issue by xavier2k6** [microsoft/vcpkg#21804]
Library name: **Qt**

New version number: **6.2.2**

Other information that may be useful (release notes, etc...)
https://www.qt.io/blog/qt-6.2.2-released
https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/6.2.2/release-note.md
https://download.qt.io/official_releases/qt/6.2/
https://wiki.qt.io/Qt_6.2_Release#Qt_6.2_release_plan

**Comment by Neumann-A** [comment]
And I thought I would be finished with adding additional qt ports.
