### ISSUE TITLE
[gdal] build failure

### ISSUE THREAD

**Issue by meghanrjones** [microsoft/vcpkg#21806]
**Host Environment**
- OS: Windows Server 2019
- Compiler: Visual Studio Enterprise 2019

**To Reproduce**
`./vcpkg install gdal[core,tools]`

**Failure logs** 
```
 CMake Error at scripts/cmake/vcpkg_copy_tools.cmake:70 (message):
  Couldn't find tool "testepsg":

      "C:/vcpkg/packages/gdal_x64-windows/bin/testepsg.exe" does not exist
Call Stack (most recent call first):
  ports/gdal/portfile.cmake:172 (vcpkg_copy_tools)
  scripts/ports.cmake:142 (include)


Error: Building package gdal:x64-windows failed with: BUILD_FAILED
```
**Additional context**

The [gdal portfile](https://github.com/microsoft/vcpkg/blob/master/ports/gdal/portfile.cmake) includes `testepsg`, but that was removed from the default build for gdal in https://github.com/OSGeo/gdal/commit/0272378cc7b16975e3a85585e175ec8b8fffcaa1. I expect that needs to be removed from the portfile.

**Comment by JonLiu1993** [comment]
Confirmed

**Comment by JackBoosY** [comment]
I saw testepsg still exists in the `makefile.vc`, no ideas why it wasn't build.
