### ISSUE TITLE
Diagnostics about vcpkg calling into other binaries don't differentiate between WinAPI Errors and application exit codes

### ISSUE THREAD

**Issue by autoantwort** [microsoft/vcpkg#21800]
**Describe the bug**
While running vcpkg we got the following error message:
```
error : curl failed to put file to file:///G:/Entwicklung/vcpkg/assetcache/abc123 with exit code '2' and http code '0'
```
But the problem was not, that curl exited with code 2, but the `CreateProcessA` function failed and `GetLastError` returned `2` aka `ERROR_FILE_NOT_FOUND`. So the problem was that there was no curl on the path. 

**Environment**
- OS: Windows

**To Reproduce**
1. Use a system without curl on the path or remove it from the path. 
2. Use vcpkg with some assetcache 

**Expected behavior**
The function should differentiate between failed WinAPI calls and the return code of the application. If you currently get a code `x` you don't know if the API call failed with code `x` or if the application existed with code `x`.   

**Additional context**
Happened on a windows server 2008 (Yeah I know that it is not supported anymore, there are plans to replace it)

**Comment by BillyONeal** [comment]
I renamed the bug to capture that the issue is really bad diagnostics rather than about the specific internal organization of the tool. (In case that function is ever renamed or similar if the bug is still valid it should survive)

**Comment by autoantwort** [comment]
@BillyONeal What do you think about wrapping the `int` return/exit code into an `ExpectedS` that can hold the failure message of the winapi

**Comment by BillyONeal** [comment]
That seems a reasonable interim solution to me

**Comment by autoantwort** [comment]
> That seems a reasonable interim solution to me

I started with this in https://github.com/microsoft/vcpkg-tool/pull/482, but it doesn't seems to be a good fit, because the caller only wants to know if the command was executed successfully or not, but with ExpectedS you always have to check twice `res.hasValue() && res.get()->exit_code == 0`

**Comment by autoantwort** [comment]
I now have created https://github.com/microsoft/vcpkg/issues/21800, imho the api is a lot better. And it was faster to code.

**Comment by BillyONeal** [comment]
Thanks for the submission, I just looked at it.
