### ISSUE TITLE
[coolprop] Installation failed - Python exe not detected

### ISSUE THREAD

**Issue by nitrogene** [Microsoft/vcpkg#2180]
As you can see in [config-x64-windows-rel-err.log](https://github.com/Microsoft/vcpkg/files/1464540/config-x64-windows-rel-err.log) the python executable is not detected. I then installed version 3.6.3, modified the PATH to make it available from everywhere. Same result.

To be noted that I am able to build coolprop from its github repository and CMake (Gui) version 3.9.6.

PS D:\Dev\vcpkg> .\vcpkg.exe install coolprop:x64-windows
The following packages will be built and installed:
    coolprop:x64-windows
Starting package 1/1: coolprop:x64-windows
Building package coolprop:x64-windows...
-- CURRENT_INSTALLED_DIR=D:/Dev/vcpkg/installed/x64-windows
-- DOWNLOADS=D:/Dev/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=D:/Dev/vcpkg/packages/coolprop_x64-windows
-- CURRENT_BUILDTREES_DIR=D:/Dev/vcpkg/buildtrees/coolprop
-- CURRENT_PORT_DIR=D:/Dev/vcpkg/ports/coolprop/.
-- Using cached D:/Dev/vcpkg/downloads/CoolProp-CoolProp-0e934e842e9ce83eea64fda1d4ab8e59adf9d8cd.tar.gz
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Configuring x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:43 (message):
    Command failed: D:/Dev/vcpkg/downloads/cmake-3.9.5-win32-x86/bin/cmake.exe;D:/Dev/vcpkg/buildtrees/coolprop/src/CoolProp-0e934e842e9ce83eea64fda1d4ab8e59adf9d8cd;-DCOOLPROP_SHARED_LIBRARY=1;-DCOOLPROP_STATIC_LIBRARY=0;-DCOOLPROP_MSVC_DYNAMIC=1;-DCOOLPROP_MSVC_STATIC=0;-DBUILD_SHARED_LIBS=ON;-DCMAKE_CXX_FLAGS= /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP ;-DCMAKE_C_FLAGS= /DWIN32 /D_WINDOWS /W3 /utf-8 /MP ;-DVCPKG_TARGET_TRIPLET=x64-windows;-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON;-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE;-DCMAKE_VERBOSE_MAKEFILE=ON;-DVCPKG_APPLOCAL_DEPS=OFF;-DCMAKE_TOOLCHAIN_FILE=D:/Dev/vcpkg/scripts/buildsystems/vcpkg.cmake;-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON;-DCOOLPROP_RELEASE=ON;-DCMAKE_CXX_FLAGS_RELEASE=/MD /O2 /Oi /Gy /DNDEBUG /Z7 ;-DCMAKE_C_FLAGS_RELEASE=/MD /O2 /Oi /Gy /DNDEBUG /Z7 ;-DCMAKE_SHARED_LINKER_FLAGS_RELEASE=/DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF ;-DCMAKE_EXE_LINKER_FLAGS_RELEASE=/DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF ;-G;Ninja;-DCMAKE_BUILD_TYPE=Release;-DCMAKE_INSTALL_PREFIX=D:/Dev/vcpkg/packages/coolprop_x64-windows
    Working Directory: D:/Dev/vcpkg/buildtrees/coolprop/x64-windows-rel
    See logs for more information:
      D:\Dev\vcpkg\buildtrees\coolprop\config-x64-windows-rel-out.log
      D:\Dev\vcpkg\buildtrees\coolprop\config-x64-windows-rel-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:196 (vcpkg_execute_required_process)
  ports/coolprop/portfile.cmake:49 (vcpkg_configure_cmake)
  scripts/ports.cmake:72 (include)

Error: Building package coolprop:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: coolprop:x64-windows
  Vcpkg version: 0.0.96-2017-11-11-49e82f5db2ad2283c08216a7d940e78320372e12

**Comment by ras0219-msft** [comment]
Thanks for reporting this issue! This should be fixed in 5c9f0ff4, which will internally acquire python 2.7.
