### ISSUE TITLE
APR missing unicode functions

### ISSUE THREAD

**Issue by chhenning** [Microsoft/vcpkg#2181]
Is there a reason why the header "apr_arch_utf8.h" is not copied into the installed folder? It resides in VCPGK\buildtrees\apr\src\apr-1.6.3\misc\win32

**Comment by chhenning** [comment]
When I copy the header manually, it gives me access to "apr_conv_utf8_to_ucs2(...)" and "apr_conv_ucs2_to_utf8(...)". That means that "apr-1.6.3\misc\win32\utf8.c" is compiled.

**Comment by JackBoosY** [comment]
Hi @chhenning , thanks for reporting this issue!
This issue has been fixed. Plz update vcpkg and rebuild apr.
Thanks.
