### ISSUE TITLE
How to use BOOST Library in ARM

### ISSUE THREAD

**Issue by zhangbowei** [microsoft/vcpkg#21814]
As title，which command should I use to install boost in ARM architecture？

**Comment by PhoebeHui** [comment]
On windows you can try below commands:
./vcpkg install boost:arm-windows: this is community supported triplet which not tested in CI pipeline.
./vcpkg install boost:arm64-windows:  this is official supported triplet.

**Comment by PhoebeHui** [comment]
@zhangbowei, please reopen this issue if it still be a question for you.
