### ISSUE TITLE
[New Port Request] <Cachelot>

### ISSUE THREAD

**Issue by hudengjunai** [microsoft/vcpkg#21810]
Library name:Cachelot

Library description:a fast c++ cache library

Source repository URL:https://github.com/cachelot/cachelot

Project homepage (if different from the source repository):https://cachelot.io/index.html

Anything else that is useful to know when adding (such as optional features the library may have that should be included):https://cachelot.io/index.html

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
