### ISSUE TITLE
[arrow] Use vendored Thrift

### ISSUE THREAD

**Issue by ianmcook** [microsoft/vcpkg#21821]
The `arrow` port depends on the `thrift` port. This introduces possible version incompatibilities and requires applying patches to the Arrow CMake scripts. Investigate whether we should instead use Arrow's vendored Thrift in the `arrow` port.

**Comment by JonLiu1993** [comment]
I will submit pr to let arrow port use Thrift of vcpkg

**Comment by JackBoosY** [comment]
arrow should use `thrift` in vcpkg.

**Comment by Osyotr** [comment]
I believe the issue is not relevant anymore.

**Comment by JonLiu1993** [comment]
@Osyotr, Could you explain why this issue is no longer relevant? Thanks

**Comment by Osyotr** [comment]
@JonLiu1993 because a) vcpkg should not use vendored libraries and b) the original patch for thrift support has been replaced long ago
