### ISSUE TITLE
[nvtt] Build error

### ISSUE THREAD

**Issue by supersickle** [microsoft/vcpkg#21823]
**Host Environment**
- VirtualBox VM 
- OS: Ubuntu 22.04 linux
- Compiler: gcc 11.2
- ~/vcpkg$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/11/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 11.2.0-12ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-11/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-11 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-11-VB3iS9/gcc-11-11.2.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-11-VB3iS9/gcc-11-11.2.0/debian/tmp-gcn/usr --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-serialization=2
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.2.0 (Ubuntu 11.2.0-12ubuntu1) 

**To Reproduce**
`./vcpkg install osgearth`

**Failure logs** 
-Console Output:
```
./vcpkg install osgearth
Computing installation plan...
The following packages will be built and installed:
  * nvtt[core]:x64-linux -> 2.1.2#2
  * osg[core,plugins]:x64-linux -> 3.6.5#11
    osgearth[core,tools]:x64-linux -> 3.2#1
  * protobuf[core]:x64-linux -> 3.18.0
  * sdl1[core]:x64-linux -> 1.2.15#14
  * tinyxml[core]:x64-linux -> 2.6.2#8
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-linux...
Restored 0 packages from /home/vagrant/.cache/vcpkg/archives in 43.78 us. Use --debug to see more details.
Starting package 1/6: nvtt:x64-linux
Building package nvtt[core]:x64-linux...
-- Using cached castano-nvidia-texture-tools-b1a90f36013522b9e5a3a2197859b72188752e3f.tar.gz.
-- Cleaning sources at /home/vagrant/vcpkg/buildtrees/nvtt/src/2188752e3f-f52a2f5d6f.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/vagrant/vcpkg/downloads/castano-nvidia-texture-tools-b1a90f36013522b9e5a3a2197859b72188752e3f.tar.gz
-- Applying patch 001-define-value-for-HAVE_UNISTD_H-in-mac-os.patch
-- Applying patch bc6h.patch
-- Applying patch bc7.patch
-- Applying patch squish.patch
-- Applying patch fix-build-error.patch
-- Applying patch add-compile-options-for-osx.patch
-- Applying patch skip-building-libsquish.patch
-- Using source at /home/vagrant/vcpkg/buildtrees/nvtt/src/2188752e3f-f52a2f5d6f.clean
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
CMake Warning at scripts/cmake/vcpkg_configure_cmake.cmake:410 (message):
  The following variables are not used in CMakeLists.txt:

      CMAKE_DEBUG_POSTFIX

  Please recheck them and remove the unnecessary options from the
  `vcpkg_configure_cmake` call.

  If these options should still be passed for whatever reason, please use the
  `MAYBE_UNUSED_VARIABLES` argument.
Call Stack (most recent call first):
  ports/nvtt/portfile.cmake:21 (vcpkg_configure_cmake)
  scripts/ports.cmake:142 (include)


-- Building x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:155 (message):
    Command failed: /usr/bin/cmake --build . --config Debug --target install -- -v -j5
    Working Directory: /home/vagrant/vcpkg/buildtrees/nvtt/x64-linux-dbg
    See logs for more information:
      /home/vagrant/vcpkg/buildtrees/nvtt/install-x64-linux-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:106 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:44 (vcpkg_build_cmake)
  ports/nvtt/portfile.cmake:29 (vcpkg_install_cmake)
  scripts/ports.cmake:142 (include)


Error: Building package nvtt:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `./vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+nvtt
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[nvtt]+Build+error
including:
  package: nvtt[core]:x64-linux -> 2.1.2#2
    vcpkg-tool version: 2021-11-24-48b94a6946b8a70abd21529218927fd478d02b6c
    vcpkg-scripts version: 5ddd7f026 2021-12-01 (18 hours ago)

Additionally, attach any relevant sections from the log files above.
```
- install-x64-linux-dbg-out.log info:
```
[72/106] /usr/bin/c++ -DNVTT_EXPORTS -I/home/vagrant/vcpkg/buildtrees/nvtt/src/2188752e3f-f52a2f5d6f.clean/src -I/home/vagrant/vcpkg/buildtrees/nvtt/x64-linux-dbg/src -I/home/vagrant/vcpkg/buildtrees/nvtt/src/2188752e3f-f52a2f5d6f.clean/extern/poshlib -I/home/vagrant/vcpkg/buildtrees/nvtt/src/2188752e3f-f52a2f5d6f.clean/extern/stb -I/home/vagrant/vcpkg/buildtrees/nvtt/src/2188752e3f-f52a2f5d6f.clean/src/nvtt -I/home/vagrant/vcpkg/buildtrees/nvtt/src/2188752e3f-f52a2f5d6f.clean/extern/rg_etc1_v104 -fPIC -march=native -fPIC -g -std=c++11 -MD -MT src/nvtt/CMakeFiles/nvtt.dir/icbc.cpp.o -MF src/nvtt/CMakeFiles/nvtt.dir/icbc.cpp.o.d -o src/nvtt/CMakeFiles/nvtt.dir/icbc.cpp.o -c /home/vagrant/vcpkg/buildtrees/nvtt/src/2188752e3f-f52a2f5d6f.clean/src/nvtt/icbc.cpp

FAILED: src/nvtt/CMakeFiles/nvtt.dir/icbc.cpp.o 

/usr/bin/c++ -DNVTT_EXPORTS -I/home/vagrant/vcpkg/buildtrees/nvtt/src/2188752e3f-f52a2f5d6f.clean/src -I/home/vagrant/vcpkg/buildtrees/nvtt/x64-linux-dbg/src -I/home/vagrant/vcpkg/buildtrees/nvtt/src/2188752e3f-f52a2f5d6f.clean/extern/poshlib -I/home/vagrant/vcpkg/buildtrees/nvtt/src/2188752e3f-f52a2f5d6f.clean/extern/stb -I/home/vagrant/vcpkg/buildtrees/nvtt/src/2188752e3f-f52a2f5d6f.clean/src/nvtt -I/home/vagrant/vcpkg/buildtrees/nvtt/src/2188752e3f-f52a2f5d6f.clean/extern/rg_etc1_v104 -fPIC -march=native -fPIC -g -std=c++11 -MD -MT src/nvtt/CMakeFiles/nvtt.dir/icbc.cpp.o -MF src/nvtt/CMakeFiles/nvtt.dir/icbc.cpp.o.d -o src/nvtt/CMakeFiles/nvtt.dir/icbc.cpp.o -c /home/vagrant/vcpkg/buildtrees/nvtt/src/2188752e3f-f52a2f5d6f.clean/src/nvtt/icbc.cpp

In file included from /usr/lib/gcc/x86_64-linux-gnu/11/include/immintrin.h:99,

                 from /home/vagrant/vcpkg/buildtrees/nvtt/src/2188752e3f-f52a2f5d6f.clean/src/nvtt/icbc.h:138,

                 from /home/vagrant/vcpkg/buildtrees/nvtt/src/2188752e3f-f52a2f5d6f.clean/src/nvtt/icbc.cpp:3:

/usr/lib/gcc/x86_64-linux-gnu/11/include/fmaintrin.h: In function ‘icbc::VFloat icbc::vmadd(icbc::VFloat, icbc::VFloat, icbc::VFloat)’:

/usr/lib/gcc/x86_64-linux-gnu/11/include/fmaintrin.h:63:1: error: inlining failed in call to ‘always_inline’ ‘__m256 _mm256_fmadd_ps(__m256, __m256, __m256)’: target specific option mismatch

   63 | _mm256_fmadd_ps (__m256 __A, __m256 __B, __m256 __C)

      | ^~~~~~~~~~~~~~~

In file included from /home/vagrant/vcpkg/buildtrees/nvtt/src/2188752e3f-f52a2f5d6f.clean/src/nvtt/icbc.cpp:3:

/home/vagrant/vcpkg/buildtrees/nvtt/src/2188752e3f-f52a2f5d6f.clean/src/nvtt/icbc.h:656:35: note: called from here

  656 |     return _mm256_fmadd_ps(a, b, c);

      |                                   ^
```

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by supersickle** [comment]
I also duplicated this failure on my 20.04 install on my laptop.  Similar error in nvtt.
System76 
Pop_OS with Ubuntu 20.04 base
Intel x64 i7
intel graphics
nvidia tegra dev toolchain is installed on this system, but no nvidia hardware/graphics card

lspci
00:00.0 Host bridge: Intel Corporation Coffee Lake HOST and DRAM Controller (rev 0b)
00:02.0 VGA compatible controller: Intel Corporation UHD Graphics 620 (Whiskey Lake)
00:12.0 Signal processing controller: Intel Corporation Cannon Point-LP Thermal Controller (rev 30)
00:14.0 USB controller: Intel Corporation Cannon Point-LP USB 3.1 xHCI Controller (rev 30)
00:14.2 RAM memory: Intel Corporation Cannon Point-LP Shared SRAM (rev 30)
00:14.3 Network controller: Intel Corporation Cannon Point-LP CNVi [Wireless-AC] (rev 30)
00:16.0 Communication controller: Intel Corporation Cannon Point-LP MEI Controller #1 (rev 30)
00:17.0 SATA controller: Intel Corporation Cannon Point-LP SATA Controller [AHCI Mode] (rev 30)
00:1c.0 PCI bridge: Intel Corporation Cannon Point-LP PCI Express Root Port #5 (rev f0)
00:1d.0 PCI bridge: Intel Corporation Cannon Point-LP PCI Express Root Port #9 (rev f0)
00:1d.4 PCI bridge: Intel Corporation Cannon Point-LP PCI Express Root Port #13 (rev f0)
00:1f.0 ISA bridge: Intel Corporation Cannon Point-LP LPC Controller (rev 30)
00:1f.3 Audio device: Intel Corporation Cannon Point-LP High Definition Audio Controller (rev 30)
00:1f.4 SMBus: Intel Corporation Cannon Point-LP SMBus Controller (rev 30)
00:1f.5 Serial bus controller [0c80]: Intel Corporation Cannon Point-LP SPI Controller (rev 30)
01:00.0 PCI bridge: Intel Corporation JHL7540 Thunderbolt 3 Bridge [Titan Ridge 2C 2018] (rev 06)
02:00.0 PCI bridge: Intel Corporation JHL7540 Thunderbolt 3 Bridge [Titan Ridge 2C 2018] (rev 06)
02:01.0 PCI bridge: Intel Corporation JHL7540 Thunderbolt 3 Bridge [Titan Ridge 2C 2018] (rev 06)
02:02.0 PCI bridge: Intel Corporation JHL7540 Thunderbolt 3 Bridge [Titan Ridge 2C 2018] (rev 06)
03:00.0 System peripheral: Intel Corporation JHL7540 Thunderbolt 3 NHI [Titan Ridge 2C 2018] (rev 06)
38:00.0 USB controller: Intel Corporation JHL7540 Thunderbolt 3 USB Controller [Titan Ridge 2C 2018] (rev 06)
39:00.0 Unassigned class [ff00]: Realtek Semiconductor Co., Ltd. RTL8411B PCI Express Card Reader (rev 01)
39:00.1 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 12)
3a:00.0 Non-Volatile memory controller: Samsung Electronics Co Ltd NVMe SSD Controller SM981/PM981/PM983


Log message:
FAILED: src/nvtt/CMakeFiles/cuda_compile_1.dir/cuda/cuda_compile_1_generated_CompressKernel.cu.o /home/ryan/bin/vcpkg/buildtrees/nvtt/x64-linux-dbg/src/nvtt/CMakeFiles/cuda_compile_1.dir/cuda/cuda_compile_1_generated_CompressKernel.cu.o 
cd /home/ryan/bin/vcpkg/buildtrees/nvtt/x64-linux-dbg/src/nvtt/CMakeFiles/cuda_compile_1.dir/cuda && /home/ryan/bin/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/bin/cmake -E make_directory /home/ryan/bin/vcpkg/buildtrees/nvtt/x64-linux-dbg/src/nvtt/CMakeFiles/cuda_compile_1.dir/cuda/. && /home/ryan/bin/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/bin/cmake -D verbose:BOOL=OFF -D build_configuration:STRING=Debug -D generated_file:STRING=/home/ryan/bin/vcpkg/buildtrees/nvtt/x64-linux-dbg/src/nvtt/CMakeFiles/cuda_compile_1.dir/cuda/./cuda_compile_1_generated_CompressKernel.cu.o -D generated_cubin_file:STRING=/home/ryan/bin/vcpkg/buildtrees/nvtt/x64-linux-dbg/src/nvtt/CMakeFiles/cuda_compile_1.dir/cuda/./cuda_compile_1_generated_CompressKernel.cu.o.cubin.txt -P /home/ryan/bin/vcpkg/buildtrees/nvtt/x64-linux-dbg/src/nvtt/CMakeFiles/cuda_compile_1.dir/cuda/cuda_compile_1_generated_CompressKernel.cu.o.Debug.cmake
In file included from /usr/local/cuda/include/cuda_runtime.h:83,
                 from <command-line>:
/usr/local/cuda/include/crt/host_config.h:138:2: error: #error -- unsupported GNU version! gcc versions later than 8 are not supported!
  138 | #error -- unsupported GNU version! gcc versions later than 8 are not supported!
      |  ^~~~~
CMake Error at cuda_compile_1_generated_CompressKernel.cu.o.Debug.cmake:220 (message):
  Error generating
  /home/ryan/bin/vcpkg/buildtrees/nvtt/x64-linux-dbg/src/nvtt/CMakeFiles/cuda_compile_1.dir/cuda/./cuda_compile_1_generated_CompressKernel.cu.o

**Comment by JackBoosY** [comment]
@supersickle It's a cuda bug, see https://stackoverflow.com/questions/65605972/cmake-unsupported-gnu-version-gcc-versions-later-than-8-are-not-supported.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
