### ISSUE TITLE
libusb canot be installed

### ISSUE THREAD

**Issue by KnifeEdge** [microsoft/vcpkg#21837]
The download URL may be changed  !!!

Package: libusb:x64-windows
Vcpkg version: 2020.06.15-nohash

**Comment by cenit** [comment]
git pull
./bootstrap-vcpkg.sh

then retry

**Comment by JonLiu1993** [comment]
@KnifeEdge ,Thanks for posting this issue, please use command _git pull_ use the latest verision vcpkg and run _./bootstrap-vcpkg.sh_ then try again

**Comment by JackBoosY** [comment]
I checked the file and its hash is corrrect.

**Comment by KnifeEdge** [comment]
The problem has been solved,

> I checked the file and its hash is corrrect.

yes,it has been solved. Thanks for your concern !

**Comment by KnifeEdge** [comment]
> git pull ./bootstrap-vcpkg.sh
> 
> then retry

thanks,it has been solved.
