### ISSUE TITLE
[mpfr] Build error

### ISSUE THREAD

**Issue by lmdiazangulo** [microsoft/vcpkg#21833]
**Host Environment**
- OS: x64 Ubuntu 20.04 (as WSL)
- Compiler: gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04) 

**To Reproduce**
`./vcpkg install mpfr`

**Failure logs** 

 - Console output: 
> Building package mpfr[core]:x64-linux...
> -- Using cached mpfr-4.1.0.tar.xz.
> -- Extracting source /home/luis/workspace/vcpkg/downloads/mpfr-4.1.0.tar.xz
> -- Applying patch gmpd.patch
> -- Applying patch dll.patch
> -- Using source at /home/luis/workspace/vcpkg/buildtrees/mpfr/src/mpfr-4-8955d4bc66.clean
> -- Getting CMake variables for x64-linux-dbg
> -- Getting CMake variables for x64-linux-rel
> -- Generating configure for x64-linux
> -- Finished generating configure for x64-linux
> -- Configuring x64-linux-dbg
> -- Configuring x64-linux-rel
> -- Building x64-linux-dbg
> CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:155 (message):
>     Command failed: /usr/bin/make V=1 -j 9 -f Makefile all
>     Working Directory: /home/luis/workspace/vcpkg/buildtrees/mpfr/x64-linux-dbg/
>     See logs for more information:
>       /home/luis/workspace/vcpkg/buildtrees/mpfr/build-x64-linux-dbg-out.log
>       /home/luis/workspace/vcpkg/buildtrees/mpfr/build-x64-linux-dbg-err.log
> 
> Call Stack (most recent call first):
>   scripts/cmake/vcpkg_build_make.cmake:187 (vcpkg_execute_build_process)
>   scripts/cmake/vcpkg_install_make.cmake:26 (vcpkg_build_make)
>   ports/mpfr/portfile.cmake:23 (vcpkg_install_make)
>   scripts/ports.cmake:142 (include)
> 
> 
> Error: Building package mpfr:x64-linux failed with: BUILD_FAILED
> 

buildtrees/mpfr/autoconf-x64-linux-err.log 
> autoreconf: Entering directory `.'
> autoreconf: configure.ac: not using Gettext
> autoreconf: running: aclocal --force -I m4
> aclocal: warning: couldn't open directory 'm4': No such file or directory
> autoreconf: configure.ac: tracing
> autoreconf: running: libtoolize --copy --force
> autoreconf: running: /usr/bin/autoconf --force
> autoreconf: configure.ac: not using Autoheader
> autoreconf: running: automake --add-missing --copy --force-missing
> configure.ac:411: installing './compile'
> configure.ac:37: installing './missing'
> src/Makefile.am: installing './depcomp'
> autoreconf: Leaving directory 

**Additional context**
Previously had an error that required to install the autoconf-archive package

**Comment by LilyWangLL** [comment]
@lmdiazangulo Thanks for posting this issue. `autoconf-archive` and `texinfo` are missing which is why the error is there. You can see comment: https://github.com/microsoft/vcpkg/pull/13081#issuecomment-678739081
You can install `autoconf-archive` and `texinfo` to make mpfr build succeed, I will add message to mpfr'portfile.cmake in future.
Install `autoconf-archive`:
```
sudo apt-get update -y
sudo apt-get install -y autoconf-archive
```
Install `texinfo`:
```
sudo apt-get update -y
sudo apt-get install -y texinfo
```

**Comment by lmdiazangulo** [comment]
Thank you, this solved the problem for me.

**Comment by LilyWangLL** [comment]
There should be message in portfile.cmake to remind user to install `autoconf-archive` and `texinfo`, I will submit a PR to fix it.
