### ISSUE TITLE
Unnecessary proxy authentication prompts

### ISSUE THREAD

**Issue by chrullrich** [Microsoft/vcpkg#2183]
When running bootstrap.ps1, I get two popups asking me for HTTP proxy credentials. These prompts are not necessary because the proxy does not require authentication.

Upgrading CMake causes one proxy auth prompt to appear.

**Comment by alexkaratarakis** [comment]
Should be fixed as part of the rework in 2abdcc1eec62fa7bd6af7abe0d7884966bd65b59.

**Comment by LYP951018** [comment]
@alexkaratarakis  No, this is still not fixed ...

**Comment by Cheney-W** [comment]
@chrullrich , thanks for reporting this issue.
I can't reproduce it in the latest VCPKG now, please open a new issue if this is still a problem for you.
