### ISSUE TITLE
Port Request: OpenVDB 

### ISSUE THREAD

**Issue by Remotion** [Microsoft/vcpkg#2184]
https://github.com/dreamworksanimation/openvdb

OpenVDB is an open source C++ library comprising a novel hierarchical data structure and a large suite of tools for the efficient storage and manipulation of sparse volumetric data discretized on three-dimensional grids. It is developed and maintained by DreamWorks Animation for use in volumetric applications typically encountered in feature film production.

Thank you !

**Comment by kypp** [comment]
Port was added with PR #2237
