### ISSUE TITLE
As there is no import command, why does the export command exist?

### ISSUE THREAD

**Issue by xiaoxstz** [microsoft/vcpkg#21865]
As there is no import command, why does the export command exist?

How to use the files exported?

**Comment by JackBoosY** [comment]
Yeah, since vcpkg cannot get the exported file's abi, so we can't determine whether the file is correct.
You can also use feature binarycaching instead of `import`.
See https://github.com/microsoft/vcpkg/blob/master/docs/specifications/binarycaching.md.

**Comment by dg0yt** [comment]
There is a blog post on the export feature:
https://devblogs.microsoft.com/cppblog/vcpkg-introducing-export-command/

So the export commands exist for being the binary artifacts to be used in a different environment, even without vcpkg. 
However, not using the vcpkg toolchain also cuts away important features like the wrappers for cmake modules.

**Comment by xiaoxstz** [comment]
## For Visual Studio
import `\scripts\buildsystems\msbuild\vcpkg.targets` to the project

For example, add `<Import Project="$(CpplibPath)\scripts\buildsystems\msbuild\vcpkg.targets" />` to the project file (`.vcxproj`)
  ![image](https://user-images.githubusercontent.com/81862747/145762255-bc16972e-5650-4842-9b5b-7a097648a6fc.png)

## For Cmake
specify the CMAKE_TOOLCHAIN_FILE variable when calling CMake

For example
```bash
cmake .. "-DCMAKE_TOOLCHAIN_FILE=C:\dev\CppLib\scripts\buildsystems\vcpkg.cmake"
```
