### ISSUE TITLE
[New Port Request]  licensecc

### ISSUE THREAD

**Issue by IshaanKarnik** [microsoft/vcpkg#21868]
Library name : licensecc

Library description : Copy protection, licensing library and license generator for Windows and Linux.

Source repository URL:
https://github.com/open-license-manager/licensecc
https://github.com/open-license-manager/lcc-license-generator

http://open-license-manager.github.io/licensecc/index.html

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
