### ISSUE TITLE
[ompl] Can't find_package ompl

### ISSUE THREAD

**Issue by Ace314159** [microsoft/vcpkg#21863]
**Describe the bug**
Doing `find_package(ompl CONFIG REQUIRED)` results in an error

**Environment**
- OS: Windows 10.0.19042
- Compiler: MSVC 19.29.30040

**To Reproduce**
1. `./vcpkg install ompl:x64-windows`
2. Create CMakeLists.txt with only `find_package(ompl CONFIG REQUIRED)`
3. Run CMake
4. Error occurs

**Expected behavior**
No error should occur

**Failure logs** 
```
CMake Error at C:/vcpkg/installed/x64-windows/share/ompl/omplConfig.cmake:35 (find_dependency):
  Unknown CMake command "find_dependency".
Call Stack (most recent call first):
  C:/vcpkg/scripts/buildsystems/vcpkg.cmake:788 (_find_package)
  CMakeLists.txt:3 (find_package)
```

**Additional context**

**Comment by JackBoosY** [comment]
Confirmed, missing include `CMakeFindDependencyMacro`.
Also, this is a upstream bug.
