### ISSUE TITLE
[boost-exception] Build error

### ISSUE THREAD

**Issue by gregorijk** [microsoft/vcpkg#21862]
Trying to build pcl library which requires boost. Build process break with one of the boost modules with the following error:

```
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: ninja -v
    Working Directory: C:/dev/vcpkg/buildtrees/boost-exception/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\dev\vcpkg\buildtrees\boost-exception\config-x64-windows-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:364 (vcpkg_execute_required_process)
  installed/x64-windows/share/boost-build/boost-modular-build.cmake:89 (vcpkg_cmake_configure)
  ports/boost-exception/portfile.cmake:15 (boost_modular_build)
  scripts/ports.cmake:142 (include)


Error: Building package boost-exception:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-exception
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[boost-exception]+Build+error
including:
  package: boost-exception[core]:x64-windows -> 1.77.0
    vcpkg-tool version: 2021-11-24-48b94a6946b8a70abd21529218927fd478d02b6c
    vcpkg-scripts version: 63e935d96 2021-12-02 (2 days ago)

Additionally, attach any relevant sections from the log files above.
```

**Host Environment**
- OS: Windows
- Compiler: VS2022
- Vcpkg package management program version 2021-11-24-48b94a6946b8a70abd21529218927fd478d02b6c

**To Reproduce**
`./vcpkg install boost`

[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/7654809/config-x64-windows-out.log)

**Comment by dg0yt** [comment]
Can you verify that you build with latest version of vcpkg-cmake? This implies a `vckg remove vpckg-cmake` (NB: for the host triplet), which in turn implies rebuilding all ports which use it.
(The config log indicates that you use an older version which doesn't understand the `MAYBE_UNUSED_VARIABLES` parameter.)

**Comment by gregorijk** [comment]
I did a clean pull to a new folder and the boost library compiled. As you suggested, it looks like there was some stale configuration left.
