### ISSUE TITLE
[New Port Request] autodiff

### ISSUE THREAD

**Issue by cityadmirer** [microsoft/vcpkg#21874]
Library name: 
autodiff
Library description: 
A C++17 library that uses modern and advanced programming techniques to enable automatic computation of derivatives in an efficient, easy, and intuitive way.
Source repository URL: 
https://github.com/autodiff/autodiff
Project homepage (if different from the source repository):
https://autodiff.github.io/
Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
