### ISSUE TITLE
[ensmallen] update to 2.18.1

### ISSUE THREAD

**Issue by cityadmirer** [microsoft/vcpkg#21876]
Library name:
ensmallen
New version number:
2.18.1
Other information that may be useful (release notes, etc...)
version 2.18.0 removed redundant template argument for C++20 compatibility

**Comment by JonLiu1993** [comment]
@cityadmirer ,Currently the version of armadillo in vcpkg is 10.6.2, the latest version of armadillo is http://sourceforge.net/projects/arma/files/armadillo-10.7.4.tar.xz, could you provide a link to version 2.18.1?

**Comment by cityadmirer** [comment]
sorry,I confuesd <ensmallen> with <armadillo>

**Comment by cityadmirer** [comment]
sorry, i confused ensmallen with armadillo
