### ISSUE TITLE
Provide a way to get the debug/release library path for Nina Multi-Config builds when using CMake

### ISSUE THREAD

**Issue by michaelkroener** [microsoft/vcpkg#21870]
****

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I'm trying to use Ninja Multi-Config builds that do not set an build type in the configuration step. Currently the method I know is to write a custom find module that extracts the debug and release binary directories based either on the include path or the release / debug library path.

**Proposed solution**
VCPKG knows the library path for both debug and release libs so why not just provide a way to query this path to atleast make it a bit easier to write a find module. ${VCPKG_LIBRARY_PATH_DEBUG} ${VCPKG_LIBRARY_PATH} for example would be really helpful.  

**Describe alternatives you've considered**
In my humble opinion vcpkg should actually provide find modules for packages that do currently not support find_package or atleast some kind of script to make it easier for most ports creating an imported target and mapping the IMPORTED_LOCATION for different build types automatically https://cmake.org/cmake/help/v3.19/prop_tgt/MAP_IMPORTED_CONFIG_CONFIG.html 

**Additional context**
(https://github.com/microsoft/vcpkg/issues/1626#issuecomment-324185781) For example this works because the debug version is actually called zlibd but it wont work for libraries where debug and optimized versions are called the same.
(https://github.com/Microsoft/vcpkg/issues/2979) This was also discussed here and thats where I took my current approach mentioned above from.

**Comment by dg0yt** [comment]
This sounds like a variant of `z_vcpkg_find_configurations` which I am proposing for (find module) wrappers in #21783. You would still need to do a `select_library_configurations`.

**Comment by JackBoosY** [comment]
Currently, vcpkg only supports single configuration.
Since the user project will only generate one configuration at a time, and the configuration provided by the port is multi-configuration, adding multi-configuration is not that important to me.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. This issue hasn’t been updated in one month. Please reopen this issue if this is still a problem for you.

**Comment by redbaron** [comment]
This is still very real issue. Multi-Ninja is a thing and current approach with CMAKE_BUILD_TYPE [check](https://github.com/microsoft/vcpkg/blob/master/scripts/buildsystems/vcpkg.cmake#L421-L427) in vcpkg toolchain nothing. I suspect any port which has same lib name for release and debug build can't be pulled as dependency when app is build with Debug config in Multi-Ninja on windows

**Comment by sfhacker** [comment]
This issue is from 2021!

**Comment by redbaron** [comment]
even more sad that it remains unfixed

**Comment by dg0yt** [comment]
You can contribute by helping upstreams and CMake to correctly implement multi-config, at least for the packages you are interested in.

In addition, we need a good wrapping, reimplementation, or upstream modification of `FindPkgConfig.cmake` to handle multi-config.

#27408 indicates that it is a long way to go, even with official CMake modules.
