### ISSUE TITLE
[fontconfig] Build error

### ISSUE THREAD

**Issue by xingkong010** [microsoft/vcpkg#21880]
Computing installation plan...
The following packages will be built and installed:
    fontconfig[core]:arm64-linux -> 2.13.94#4
Detecting compiler hash for triplet arm64-linux...
Restored 0 packages from /home/abab/.cache/vcpkg/archives in 5.37 us. Use --debug to see more details.
Starting package 1/1: fontconfig:arm64-linux
Building package fontconfig[core]:arm64-linux...
-- Using community triplet arm64-linux. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: /home/abab/new_vcpkg/vcpkg/triplets/community/arm64-linux.cmake
-- Using cached fontconfig-fontconfig-2.13.94.tar.gz.
-- Cleaning sources at /home/abab/new_vcpkg/vcpkg/buildtrees/fontconfig/src/2.13.94-6fd83e1cbe.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/abab/new_vcpkg/vcpkg/downloads/fontconfig-fontconfig-2.13.94.tar.gz
-- Using source at /home/abab/new_vcpkg/vcpkg/buildtrees/fontconfig/src/2.13.94-6fd83e1cbe.clean
CMake Error at scripts/cmake/vcpkg_find_acquire_program.cmake:613 (message):
  Could not find gperf.  Please install it via your package manager.
Call Stack (most recent call first):
  ports/fontconfig/portfile.cmake:12 (vcpkg_find_acquire_program)
  scripts/ports.cmake:142 (include)

Error: Building package fontconfig:arm64-linux failed with: BUILD_FAILED

**Comment by autoantwort** [comment]
> Could not find gperf. Please install it via your package manager.

**Comment by xingkong010** [comment]
> > Could not find gperf. Please install it via your package manager.

caiji@caiji-virtual-machine:~/crossCompile/vcpkg$ ./vcpkg install gperf:arm64-linux
Computing installation plan...
The following packages are already installed:
    gperf[core]:arm64-linux -> 3.1#2
Package gperf:arm64-linux is already installed
Restored 0 packages from /home/caiji/.cache/vcpkg/archives in 957 ns. Use --debug to see more details.

Total elapsed time: 29.73 ms

caiji@caiji-virtual-machine:~/crossCompile/vcpkg$ ./vcpkg install gperf
Computing installation plan...
The following packages are already installed:
    gperf[core]:x64-linux -> 3.1#2
Package gperf:x64-linux is already installed
Restored 0 packages from /home/caiji/.cache/vcpkg/archives in 1.736 us. Use --debug to see more details.

Total elapsed time: 3.175 ms
 
我安装了gperf但还是出现这个错误

**Comment by LilyWangLL** [comment]
@xingkong010 You need install gperf by command `sudo apt-get install gperf` on Linux

**Comment by LilyWangLL** [comment]
There should add a message to fontconfig's portfile.cmake, I will fix it soon.

**Comment by dg0yt** [comment]
> There should add a message to fontconfig's portfile.cmake, I will fix it soon.

The message won't be more visible than the current one:
~~~
CMake Error at scripts/cmake/vcpkg_find_acquire_program.cmake:613 (message):
Could not find gperf. Please install it via your package manager.
Call Stack (most recent call first):
ports/fontconfig/portfile.cmake:12 (vcpkg_find_acquire_program)
scripts/ports.cmake:142 (include)

<countless lines of output>
~~~

To really improve the situation, vcpkg tool would need to recognize the situation, and print the message more prominently (no call stack, no instruction to open an issue.

**Comment by LilyWangLL** [comment]
Duplicate to issue #15931.
