### ISSUE TITLE
[kf5i18n] build failure

### ISSUE THREAD

**Issue by zhangjp0405** [microsoft/vcpkg#21886]
**Host Environment**
- OS: [e.g. Windows]
- Compiler: 5.88.0

**To Reproduce**
`./vcpkg install kf5i18n:x64-windows`

**Failure logs** 
-buildtrees\kf5i18n\src\v5.88.0-658d066571.clean\src\localedata\data/spatial_index_data.cpp(10): error C2131: expression did not evaluate to a constant

**Comment by FrankXie05** [comment]
@zhangjp0405 Thanks for posting this issue, 
````
 spatial_index_data.cpp(10): static constexpr const SpatialIndexProperty spatial_index_properties[] = {
 `````
I think it is a port bug, you can go to upstream to submit a issue to deal with it :)

**Comment by zhangjp0405** [comment]
Thank you
