### ISSUE TITLE
[mongo-cxx-driver] Not working after last pull

### ISSUE THREAD

**Issue by renis1235** [microsoft/vcpkg#21898]
**Host Environment**
- OS: Windows

**To Reproduce**
`./vcpkg install mongo-cxx-driver`

**Failure logs** 
![image](https://user-images.githubusercontent.com/11201041/145088232-df9d5812-380a-44ab-8260-7e3eddf2461f.png)

I wanted to use the latest MongoDB driver on one of my applications and I am using vcpkg as a package manager. After pulling the latest and  installing mongo-cxx-driver 3.6.5 I cannot run the app at all. It builds and the above error comes every time. I suspect that the building is not correct.

Any help is appreciated. Thank you!

**Comment by JackBoosY** [comment]
Did you use cmake project or msvc project?

**Comment by renis1235** [comment]
I used a msvc project.

**Comment by JackBoosY** [comment]
Can you please also provide a sample code?

Thanks.

**Comment by renis1235** [comment]
Wherever I import it, it happens.
e.g
```
        mongocxx::instance instance{}; 

	string uriStr = "mongodb://127.0.0.1:27017/?directConnection=true&tls=true";
	mongocxx::uri uri(uriStr);
	mongocxx::client client(uri,);
```

Thank you for taking a look at this.

**Comment by JackBoosY** [comment]
Confirmed.
