### ISSUE TITLE
When installing grpc for x64-windows-static-md we get x64-windows too.

### ISSUE THREAD

**Issue by BengtGustafsson** [microsoft/vcpkg#21895]
**Describe the bug**
When installing grpc for x64-windows-static-md we get x64-windows too, including all dependencies. This doubles compile time and resulting size. In addition, the tools/grpc directory only exists in x64-windows, not in x64-windows-static-md.

If we install x86-windows-static-md we also get the same (64 bit) extra directory.

We also install leveldb and fmt which don't have this behaviour.

This worked in 2020-06 version, but not in 2021-05-12 version. Same problem in master ans in 2021-05-12.

**Environment**
- OS: [e.g. Windows/Linux etc...]
Windows 10, 64 bit.

- Compiler: revision
VS 16.9.5

**To Reproduce**
1. ./vcpkg install grpc:x64-windows-static-md

**Expected behavior**
Only the x64-install-static-md directory exists, and it is complete with tools/gprc subdirectory.

**Failure logs** 
- no error messages or anything like that from vcpkg.

**Comment by autoantwort** [comment]
It is called host dependency. Tools for the host system are compiled for the host system, which is `x64-windows` by default. Pass `--host-triplet=x86-windows-static-md` to change the host triplet

**Comment by dg0yt** [comment]
On the positive side, a host dependency means that it is really build (and cached) only once, even if you use it for 5 different target triplets. 
Do you really need grpc:x64-windows-static-md, or is grpc:x64-windows good enough? In that case, you can `vcpkg install grpc:x64-windows` will install only that (changing the target triplet, not the host triplet).
