### ISSUE TITLE
[fontconfig] Build error

### ISSUE THREAD

**Issue by xingkong010** [microsoft/vcpkg#21892]
The following packages will be built and installed:
  * fontconfig[core]:arm64-linux -> 2.13.94#4
    osg[core]:arm64-linux -> 3.6.5#11
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet arm64-linux...
Restored 0 packages from /home/caiji/.cache/vcpkg/archives in 50.17 us. Use --debug to see more details.
Starting package 1/2: fontconfig:arm64-linux
Building package fontconfig[core]:arm64-linux...
-- Using community triplet arm64-linux. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: /home/caiji/crossCompile/vcpkg/triplets/community/arm64-linux.cmake
-- Using cached fontconfig-fontconfig-2.13.94.tar.gz.
-- Cleaning sources at /home/caiji/crossCompile/vcpkg/buildtrees/fontconfig/src/2.13.94-6fd83e1cbe.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/caiji/crossCompile/vcpkg/downloads/fontconfig-fontconfig-2.13.94.tar.gz
-- Using source at /home/caiji/crossCompile/vcpkg/buildtrees/fontconfig/src/2.13.94-6fd83e1cbe.clean
-- Getting CMake variables for arm64-linux-dbg
-- Getting CMake variables for arm64-linux-rel
-- Configuring arm64-linux-dbg
-- Configuring arm64-linux-dbg done
-- Configuring arm64-linux-rel
-- Configuring arm64-linux-rel done
-- Package arm64-linux-dbg
-- Package arm64-linux-rel
-- Fixing pkgconfig file: /home/caiji/crossCompile/vcpkg/packages/fontconfig_arm64-linux/lib/pkgconfig/fontconfig.pc
-- Fixing pkgconfig file: /home/caiji/crossCompile/vcpkg/packages/fontconfig_arm64-linux/debug/lib/pkgconfig/fontconfig.pc
-- Installing: /home/caiji/crossCompile/vcpkg/packages/fontconfig_arm64-linux/share/fontconfig/copyright
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: /home/caiji/crossCompile/vcpkg/packages/fontconfig_arm64-linux/bin/fc-cache --verbose
    Working Directory: /home/caiji/crossCompile/vcpkg/packages/fontconfig_arm64-linux/bin
    Error code: 2
    See logs for more information:
      /home/caiji/crossCompile/vcpkg/buildtrees/fontconfig/fc-cache-arm64-linux-err.log

Call Stack (most recent call first):
  ports/fontconfig/portfile.cmake:73 (vcpkg_execute_required_process)
  scripts/ports.cmake:142 (include)

Error: Building package fontconfig:arm64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `./vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+fontconfig
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[fontconfig]+Build+error
including:
  package: fontconfig[core]:arm64-linux -> 2.13.94#4
    vcpkg-tool version: 2021-11-24-48b94a6946b8a70abd21529218927fd478d02b6c
    vcpkg-scripts version: 63e935d96 2021-12-02 (4 天前)
我已经单独编译通过了fontconfig:arm64-linux 但在编译osg时还是提示fontconfig失败

**Comment by Apivan** [comment]
I can reproduce the problem on ubuntu 20.04 arm64 with today pulled vcpkg.

Here is my workaround solution

1.	Ensure that you have  meson >= 0.56.0  [[meson.build](https://github.com/freedesktop/fontconfig/blob/master/meson.build)] install by


`pip3 install meson==0.61.1
`


2.	After tring  vcpkg install fontconfig, I found the Exec format error in the log vcpkg/downloads/tools/ninja/1.10.2-linux/ninja. So I replaced the wrong ninja (x86?) with the system bin.

under vcpkg folder
`cd downloads/tools/ninja/1.10.2-linux/ninja`
`./ninja`
You will see exec format error indicated that it downloaded the wrong binary. So replace it.
`mv  ninja ninja-bk`
`cp /usr/bin/ninja ninja`

then `vcpkg install fontconfig `pass.

**Comment by LilyWangLL** [comment]
Thanks for Apivan's solution, @xingkong010 could you please try install `fontconfig` again as Apivan's reply.

**Comment by apivan2** [comment]
I think it's because https://github.com/microsoft/vcpkg/blob/master/scripts/cmake/vcpkg_find_acquire_program.cmake 
download the x86 ninja.

Here is the issue that discussing this matter. 
https://github.com/microsoft/vcpkg/issues/21482

**Comment by JackBoosY** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
