### ISSUE TITLE
[libiconv] Build error

### ISSUE THREAD

**Issue by micking** [microsoft/vcpkg#21901]
**Host Environment**
- OS: Windows 10
- Compiler: 19.29.30137 for x64

**To Reproduce**
`./vcpkg install libiconv:x64-windows`

**Failure logs** 
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: D:/dev/vcpkg/downloads/tools/msys2/803521c5733336c9/usr/bin/bash.exe --noprofile --norc --debug -c "V=1 CPP='compile cl.exe -E' CC='compile cl.exe' CC_FOR_BUILD='compile cl.exe' CXX='compile cl.exe' RC='windres-rc rc.exe' WINDRES='windres-rc rc.exe' AR='ar-lib lib.exe' LD='link.exe -verbose' RANLIB=':' STRIP=':' NM='dumpbin.exe -symbols -headers' DLLTOOL='link.exe -verbose -dll' CCAS=':' AS=':' ./../src/1.16-b0c41d3469.clean/configure --build=x86_64-pc-mingw32 \"--enable-extra-encodings\" \"--without-libiconv-prefix\" \"--without-libintl-prefix\" \"--enable-relocatable\" \"ac_cv_prog_ac_ct_STRIP=:\" \"gl_cv_double_slash_root=yes\" \"ac_cv_func_memmove=yes\" \"--disable-silent-rules\" \"--verbose\" \"--enable-shared\" \"--disable-static\" \"--prefix=/D/dev/vcpkg/installed/x64-windows/debug\" \"--bindir=\\${prefix}/../tools/libiconv/debug/bin\" \"--sbindir=\\${prefix}/../tools/libiconv/debug/sbin\" \"--libdir=\\${prefix}/lib\" \"--includedir=\\${prefix}/../include\" \"--datarootdir=\\${prefix}/share/libiconv\""
    Working Directory: D:/dev/vcpkg/buildtrees/libiconv/x64-windows-dbg
    Error code: 1
    See logs for more information:
      D:\dev\vcpkg\buildtrees\libiconv\config-x64-windows-dbg-out.log
      D:\dev\vcpkg\buildtrees\libiconv\config-x64-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:796 (vcpkg_execute_required_process)
  ports/libiconv/portfile.cmake:29 (vcpkg_configure_make)
  scripts/ports.cmake:142 (include)

Error: Building package libiconv:x64-windows failed with: BUILD_FAILED

**Additional context**
Here the config.log file
[config.log](https://github.com/microsoft/vcpkg/files/7671741/config.log)

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Please also provide files:
```
D:\dev\vcpkg\buildtrees\libiconv\config-x64-windows-dbg-out.log
D:\dev\vcpkg\buildtrees\libiconv\config-x64-windows-dbg-err.log
```

**Comment by LilyWangLL** [comment]
Ping @micking

**Comment by dg0yt** [comment]
config.log should be more useful.
~~~
configure:4377: ./conftest.exe
D:/dev/vcpkg/buildtrees/libiconv/x64-windows-dbg/conftest.exe: error while loading shared libraries: ucrtbased.dll: cannot open shared object file: No such file or directory
configure:4381: $? = 127
configure:4388: error: in `/d/dev/vcpkg/buildtrees/libiconv/x64-windows-dbg':
configure:4390: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
~~~

**Comment by LilyWangLL** [comment]
Thanks for the help of dg0yt. The error message: `ucrtbased.dll: cannot open shared object file: No such file or directory`, did you install **Windows 10 SDK 10.0.19041.0** in Visual Studio Installer?
![image](https://user-images.githubusercontent.com/94091114/147661233-0877eb82-f159-455d-8939-84603345cf7f.png)

**Comment by LilyWangLL** [comment]
@micking Does this issue resolved?

**Comment by micking** [comment]
the thing is that none of the SDK's install the ucrtbased.dll into a folder that is included in the computer's PATH. 
So as a workaround I copied manually ucrtbased.dll to C:\WINDOWS\System32, now the build works

**Comment by LilyWangLL** [comment]
This issue has been resolved, I am closing this issue for now.

**Comment by pattyl11** [comment]
What is causing this error?

configure:5232: ./conftest.exe
./../src/v1.17-84a471678e.clean/configure: line 5234: ./conftest.exe: Permission denied
configure:5236: $? = 126
configure:5243: error: in `/c/src/vcpkg/buildtrees/libiconv/x64-windows-dbg':
configure:5245: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
[config-x64-windows-dbg-config.log](https://github.com/microsoft/vcpkg/files/13943379/config-x64-windows-dbg-config.log)
[config.log](https://github.com/microsoft/vcpkg/files/13943380/config.log)

[config-x64-windows-dbg-config.log](https://github.com/microsoft/vcpkg/files/13943373/config-x64-windows-dbg-config.log)
[config-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/13943374/config-x64-windows-dbg-err.log)
[config-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/13943375/config-x64-windows-dbg-out.log)

**Comment by pattyl11** [comment]
It looks like Windows Security is blocking my build so I used this article to exempt my source code path using this link:
https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/attack-surface-reduction-rules-deployment-implement?view=o365-worldwide#customize-attack-surface-reduction-rules

**Comment by pattyl11** [comment]
It looks like Windows Security is blocking my build so I used this article to exempt my source code path using this link:
https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/attack-surface-reduction-rules-deployment-implement?view=o365-worldwide#customize-attack-surface-reduction-rules
