### ISSUE TITLE
[rapidjson] update to current master (last update 2020-9-14)

### ISSUE THREAD

**Issue by connorjak** [microsoft/vcpkg#21904]
Library name: rapidjson

Many pull requests have been merged without a tagged release. Looks like it's already on rolling releases; it's time for another. There have been ~20 pull requests merged since the last vcpkg update: https://github.com/Tencent/rapidjson/pulls?q=is%3Apr+is%3Aclosed.

Issue thread for lack of version numbering: https://github.com/Tencent/rapidjson/issues/1919

**Comment by connorjak** [comment]
My specific need for this is the inclusion of https://github.com/Tencent/rapidjson/pull/1877

**Comment by FrankXie05** [comment]
Will  be fixed by #21112

**Comment by FrankXie05** [comment]
This issue has been fixed #21112
