### ISSUE TITLE
Can TRIPLET be used with vcpkg.json

### ISSUE THREAD

**Issue by errcodex** [microsoft/vcpkg#21917]
Please create a discussion in https://github.com/microsoft/vcpkg/discussions/new instead.

`$.dependencies[0] (a dependency): must be lowercase alphanumeric+hyphens, split with periods, and not reserved`

I can fin'd a way to set TRIPLET in vcpkg.json, and I need to depend a static link static runtime(/MT) library, I may need to use dynamic/static libraries for different libraries, so I cannot set the environment variables uniformly. Is there any way to solve this problem?

**Comment by Neumann-A** [comment]
you don't set/use the triplet in vcpkg.json. If you need specific combinations of VCPKG_LIBRARY_LINKAGE you have to define a custom triplet for it.

**Comment by errcodex** [comment]
> you don't set/use the triplet in vcpkg.json. If you need specific combinations of VCPKG_LIBRARY_LINKAGE you have to define a custom triplet for it.

I can't find the option to set TRIPLET for each dependency in the [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/users/manifests.md), I want to implement the following idea, how should I write?
`{
  "name": "LoganCore",
  "version-string": "0.1.0",
  "dependencies": [
    "openssl:x86-windows-static",
    "zlib:x86-windows"
  ]
}
`

**Comment by Osyotr** [comment]
https://github.com/microsoft/vcpkg/blob/master/docs/users/triplets.md#per-port-customization

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

**Comment by 0blu** [comment]
This should be a feature request.
I know technically every repository should use a fork / submodule of vcpkg where adding a custom triplet is not a problem,
but I think adding triplet support to `vcpkg.json` sounds very logical.

**Comment by Osyotr** [comment]
@0blu it sounds logical if you target only one platform, configuration and build tools version.

**Comment by TheMaverickProgrammer** [comment]
Hi I agree with 0blu. I'm having vcpkg issues because the triplet for one of my packages is only available as `-static` on ubuntu whereas on windows it can be `dynamic` (which is defaulted on windows). 

This means my current CI/CD scripts are busted if I depend on `vcpkg,json` to do the installation for me. We should really have this feature.

**Comment by dg0yt** [comment]
vcpkg has some ports which must be built with either static or dynamic linkage regardless of triplet.
And you can add per-port customization to your triplet file for ports which support both types.
In any case, there is a *single* triplet which defines your target universe.

**Comment by dg0yt** [comment]
@TheMaverickProgrammer Probably it is best to ask for help with what you want to achieve in a new discussion.

**Comment by abdelmaged** [comment]
One of the disadvantages of using per port customization, is when you change the triplet file to customize one port, all other ports will recompile, this is why I don't find this feature very practical, I think it would be better, if one can specify the triplet per dependency in the vcpkg.json instead.

**Comment by Neumann-A** [comment]
There is a way to avoid it. Simply include a file with the specialization but be aware it has implications.

**Comment by TheMaverickProgrammer** [comment]
> There is a way to avoid it. Simply include a file with the specialization but be aware it has implications.

Avoiding is not a solution. And you even imply it has undesirable outcomes. Not good.

**Comment by errcodex** [comment]
I haven't paid attention to this discussion for a long time. My initial thought is very simple:
`foobar.exe` requires two libraries, `foo.lib` and `bar.dll`.
`foo.lib` is a `x86-windows-static-md` static library,
`bar.dll` is an `x86-windows` dynamic library,
Both libraries are dynamic runtime (/MD)
What is finally provided to the user is `foobar.exe` and `bar.dll`, which is very common in traditional engineering projects.

The issue is:
If I specify the same TRIPLET, two dynamic libraries need to be provided under `x86-windows`, or both libraries will be used as static library dependencies under `x86-windows-static-md`.

Am I missing something, or is there a way I can achieve what I'm thinking above?

**Comment by yhyu13** [comment]
The easiest thing is simply modifying the port/port***.cmake file for specific libaray and adjust `VCPKG_LIBRARY_LINKAGE` to `dynamic` temporaly, like I did here for luajit in linux-x64. Now linux-x64 build liblujit.so by default. No need to inflict custom dynamic triplet https://github.com/yhyu13/vcpkg/blob/84bc6197cf22f9cdc777090d6715988f6aea16ed/ports/luajit/portfile.cmake#L21

**Comment by dg0yt** [comment]
>A Simply modifying the port/port***.cmake file for specific libaray

Don't do that. It is not a customization point.

The triplet controls the linkage. And it is a valid customization point in particular for non-standard linkage. Take one of the two triplets as a base, and use per-port customization. 
https://learn.microsoft.com/en-us/vcpkg/users/triplets#per-port-customization

Instead of 

> `foo.lib` is a `x86-windows-static-md` static library,
> `bar.dll` is an `x86-windows` dynamic library,

this would better be presented as:
`foo.lib` is as static lib (/MD) in `x86-windows-custom`
`bar.dll` is as DLL (/MD) in `x86-windows-custom`
