### ISSUE TITLE
[getdns] Build error

### ISSUE THREAD

**Issue by xgcssch** [microsoft/vcpkg#21910]
**Host Environment**
- OS: Windows
- Compiler: Version 19.29.30137 for x86

**To Reproduce**
- fresh vcpkg repo clone
- `vcpkg install getdns`

**Failure logs** 
Tail of `C:\work\vcpkg>type C:\work\vcpkg\buildtrees\getdns\install-x86-windows-dbg-out.log`:
```
...
-- Installing: C:/work/vcpkg/packages/getdns_x86-windows/debug/share/doc/getdns/ChangeLog
FAILED: CMakeFiles/install.util
cmd.exe /C "cd /D C:\work\vcpkg\buildtrees\getdns\x86-windows-dbg && C:\work\vcpkg\downloads\tools\cmake-3.21.1-windows\cmake-3.21.1-windows-i386\bin\cmake.exe -P cmake_install.cmake"
ninja: build stopped: subcommand failed.
```
`C:\work\vcpkg>type C:\work\vcpkg\buildtrees\getdns\install-x86-windows-dbg-err.log`:
```
CMake Error at cmake_install.cmake:52 (file):
  file INSTALL cannot find
  "C:/work/vcpkg/buildtrees/getdns/src/1.7.0-0577a67b18.clean/COPYING": File
  exists.

```
**Workaround**
Create the `COPYING` file and use the `--editable` Flag of vcpkg to build the port:
1. `./vcpkg install getdns` then wait for error to occur
2. `./vcpkg install --editable getdns` then wait again for error to occur
3. create the file mentioned in `C:\work\vcpkg>type C:\work\vcpkg\buildtrees\getdns\install-x86-windows-dbg-err.log`. E. g. `C:/work/vcpkg/buildtrees/getdns/src/1.7.0-0577a67b18.clean/COPYING`
4. `./vcpkg install --editable getdns` succeeds now

**Comment by Cheney-W** [comment]
I tried to install the getdns port with the latest `vcpkg version 2021-12-09-724cea8b33cbf06c645f5095fa29773697da9761` and VS2019, and I could install it successfully. Does this issue still occur in your side?

**Comment by xgcssch** [comment]
Issue is still there.

Digging a little bit deeper, i discovered that `COPYING` in not present in the the `src` directory. 
Examining the zipped tar archive in the `download` folder shows the file is there, but it is stored as a link to the `LICENSE` file in the same directory. 
Extracting the file with a local 7Zip Version leads to an error "Cannot create symbolic link - a required right is missing".
Monitoring the unzip process with `procmon` leads to:
```
15:32:55,3653093	7zG.exe	9932	FileSystemControl	C:\work\vcpkg-getdns\downloads\getdns-1.7.0.tar\getdns\getdns-1.7.0\COPYING	PRIVILEGE NOT HELD	Control: FSCTL_SET_REPARSE_POINT
```

Doing a bit of googeling gives  https://social.msdn.microsoft.com/Forums/en-US/c107c3a9-025a-48f8-816f-5191f93d5da1/deviceiocontrol-failing-with-acess-denied-for-fsctlsetreparsepoint

And an old 7Zip bug: https://sourceforge.net/p/sevenzip/bugs/1016/

So it comes down to an `7Zip` Windows problem.
I suggest a Cmake patch for should remove `COPYING` from `CmakeLists.txt` line 1105:
```
install(FILES AUTHORS ChangeLog COPYING LICENSE NEWS README.md DESTINATION ${docdir})
```

**Comment by Cheney-W** [comment]
Does this issue occur when you clone vcpkg in a new disk, such as E:\ of F:\?
It is possible that the problem is with the file access rights of the system disk.

**Comment by xgcssch** [comment]
I attached a new USB drive, did a fresh format with NTFS and tested it:
same result as before.

It must have to do with my account, as running elevated with admin privileges let the compile coplete without errors.
But this is no option on our company systems.

User at home is a standard windows local user account created with the Windows UI. At work it's a domain user with restricted rights.
Here are my user rights for the local user account. Output is in german, but the rights are unique among languages:
```
D:\vcpkg>whoami /priv

BERECHTIGUNGSINFORMATIONEN
--------------------------

Berechtigungsname             Beschreibung                                    Status
============================= =============================================== ===========
SeShutdownPrivilege           Herunterfahren des Systems                      Deaktiviert
SeChangeNotifyPrivilege       Auslassen der durchsuchenden Überprüfung        Aktiviert
SeUndockPrivilege             Entfernen des Computers von der Docking-Station Deaktiviert
SeIncreaseWorkingSetPrivilege Arbeitssatz eines Prozesses vergrößern          Deaktiviert
SeTimeZonePrivilege           Ändern der Zeitzone                             Deaktiviert
```
and these are the ones running as administrator:
```
D:\vcpkg>whoami /priv

BERECHTIGUNGSINFORMATIONEN
--------------------------

Berechtigungsname                         Beschreibung                                                            Status
========================================= ======================================================================= ===========
SeIncreaseQuotaPrivilege                  Anpassen von Speicherkontingenten für einen Prozess                     Deaktiviert
SeSecurityPrivilege                       Verwalten von Überwachungs- und Sicherheitsprotokollen                  Deaktiviert
SeTakeOwnershipPrivilege                  Übernehmen des Besitzes von Dateien und Objekten                        Deaktiviert
SeLoadDriverPrivilege                     Laden und Entfernen von Gerätetreibern                                  Deaktiviert
SeSystemProfilePrivilege                  Erstellen eines Profils der Systemleistung                              Deaktiviert
SeSystemtimePrivilege                     Ändern der Systemzeit                                                   Deaktiviert
SeProfileSingleProcessPrivilege           Erstellen eines Profils für einen Einzelprozess                         Deaktiviert
SeIncreaseBasePriorityPrivilege           Anheben der Zeitplanungspriorität                                       Deaktiviert
SeCreatePagefilePrivilege                 Erstellen einer Auslagerungsdatei                                       Deaktiviert
SeBackupPrivilege                         Sichern von Dateien und Verzeichnissen                                  Deaktiviert
SeRestorePrivilege                        Wiederherstellen von Dateien und Verzeichnissen                         Deaktiviert
SeShutdownPrivilege                       Herunterfahren des Systems                                              Deaktiviert
SeDebugPrivilege                          Debuggen von Programmen                                                 Deaktiviert
SeSystemEnvironmentPrivilege              Verändern der Firmwareumgebungsvariablen                                Deaktiviert
SeChangeNotifyPrivilege                   Auslassen der durchsuchenden Überprüfung                                Aktiviert
SeRemoteShutdownPrivilege                 Erzwingen des Herunterfahrens von einem Remotesystem aus                Deaktiviert
SeUndockPrivilege                         Entfernen des Computers von der Docking-Station                         Deaktiviert
SeManageVolumePrivilege                   Durchführen von Volumewartungsaufgaben                                  Deaktiviert
SeImpersonatePrivilege                    Annehmen der Clientidentität nach Authentifizierung                     Aktiviert
SeCreateGlobalPrivilege                   Erstellen globaler Objekte                                              Aktiviert
SeIncreaseWorkingSetPrivilege             Arbeitssatz eines Prozesses vergrößern                                  Deaktiviert
SeTimeZonePrivilege                       Ändern der Zeitzone                                                     Deaktiviert
SeCreateSymbolicLinkPrivilege             Erstellen symbolischer Verknüpfungen                                    Deaktiviert
SeDelegateSessionUserImpersonatePrivilege Identitätstoken für einen anderen Benutzer in derselben Sitzung abrufen Deaktiviert
```
Maybe it's the missing `SeCreateSymbolicLinkPrivilege` right.

Standard and recommended setting seems to be, that normal users do not have this right. See: https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/create-symbolic-links

**Comment by JackBoosY** [comment]
vcpkg will never use permissions beyond ordinary users, which means that this problem cannot be solved from the root cause.

**Comment by xgcssch** [comment]
Hm. If that is true, then the requirement of `SeCreateSymbolicLinkPrivilege` violates this assumption and it is a port bug.

**Comment by xgcssch** [comment]
Confirmed. Works now!
Thanks much!
