### ISSUE TITLE
Bulid fail  when install zlib 

### ISSUE THREAD

**Issue by evildiamond** [Microsoft/vcpkg#2192]
i am trying to install folly, and my machine has installed vs2017.
The following is my log.

PS F:\Vcpkg> .\vcpkg.exe --keep-going install zlib
The following packages will be built and installed:
    zlib:x86-windows
Starting package 1/1: zlib:x86-windows
Building package zlib:x86-windows...
-- CURRENT_INSTALLED_DIR=F:/Vcpkg/installed/x86-windows
-- DOWNLOADS=F:/Vcpkg/downloads
-- CURRENT_PACKAGES_DIR=F:/Vcpkg/packages/zlib_x86-windows
-- CURRENT_BUILDTREES_DIR=F:/Vcpkg/buildtrees/zlib
-- CURRENT_PORT_DIR=F:/Vcpkg/ports/zlib/.
-- Using cached F:/Vcpkg/downloads/zlib1211.tar.gz
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Applying patch F:/Vcpkg/ports/zlib/cmake_dont_build_more_than_needed.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch F:/Vcpkg/ports/zlib/cmake_dont_build_more_than_needed.patch done
-- Configuring x86-windows-rel
-- Configuring x86-windows-rel done
-- Configuring x86-windows-dbg
-- Configuring x86-windows-dbg done
-- Build x86-windows-rel
CMake Error at F:/Vcpkg/scripts/cmake/vcpkg_execute_required_process.cmake:43 (message):
    Command failed: F:/Vcpkg/downloads/cmake-3.9.5-win32-x86/bin/cmake.exe;--build;.;--config;Release;--target;install;--;-v
    Working Directory: F:/Vcpkg/buildtrees/zlib/x86-windows-rel
    See logs for more information:
      F:\Vcpkg\buildtrees\zlib\install-x86-windows-rel-out.log
      F:\Vcpkg\buildtrees\zlib\install-x86-windows-rel-err.log

Call Stack (most recent call first):
  F:/Vcpkg/scripts/cmake/vcpkg_build_cmake.cmake:62 (vcpkg_execute_required_process)
  F:/Vcpkg/scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  F:/Vcpkg/ports/zlib/portfile.cmake:26 (vcpkg_install_cmake)
  F:/Vcpkg/scripts/ports.cmake:72 (include)

Error: Building package zlib:x86-windows failed with: BUILD_FAILED
Elapsed time for package zlib:x86-windows: 22.21 s

Total elapsed time: 22.22 s
RESULTS
    zlib:x86-windows: BUILD_FAILED: 22.21 s

SUMMARY
    SUCCEEDED: 0
    BUILD_FAILED: 1
    POST_BUILD_CHECKS_FAILED: 0
    FILE_CONFLICTS: 0
    CASCADED_DUE_TO_MISSING_DEPENDENCIES: 0
    EXCLUDED: 0

And the log file [**config-x86-windows-dbg-err.log**]:
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_CXX_FLAGS
    CMAKE_CXX_FLAGS_DEBUG

log file [**patch-x86-windows-0-err.log]**
Checking patch CMakeLists.txt...
error: while searching for:

option(ASM686 "Enable building i686 assembly implementation")
option(AMD64 "Enable building amd64 assembly implementation")

set(INSTALL_BIN_DIR "${CMAKE_INSTALL_PREFIX}/bin" CACHE PATH "Installation directory for executables")
set(INSTALL_LIB_DIR "${CMAKE_INSTALL_PREFIX}/lib" CACHE PATH "Installation directory for libraries")

error: patch failed: CMakeLists.txt:7
error: CMakeLists.txt: patch does not apply

**Comment by ras0219-msft** [comment]
Thanks for reporting this issue!

Could you attach the logs mentioned in the error message?
>See logs for more information:
F:\Vcpkg\buildtrees\zlib\install-x86-windows-rel-out.log
F:\Vcpkg\buildtrees\zlib\install-x86-windows-rel-err.log

**Comment by evildiamond** [comment]
***F:\Vcpkg\buildtrees\zlib\install-x86-windows-rel-out.log***

The C compiler identification is MSVC 19.11.25547.0
-- Check for working C compiler: @ras0219-msft D:/EnglishPath/VS2017/VC/Tools/MSVC/14.11.25503/bin/Hostx64/x86/cl.exe
-- Check for working C compiler: D:/EnglishPath/VS2017/VC/Tools/MSVC/14.11.25503/bin/Hostx64/x86/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of off64_t
-- Check size of off64_t - failed
-- Looking for fseeko
-- Looking for fseeko - not found
-- Looking for unistd.h
-- Looking for unistd.h - not found
-- Configuring done
-- Generating done
-- Build files have been written to: F:/Vcpkg/buildtrees/zlib/x86-windows-rel

***config-x86-windows-rel-err.log***
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_CXX_FLAGS
    CMAKE_CXX_FLAGS_RELEASE

thanks.

**Comment by ras0219-msft** [comment]
Thanks, but the first file you attached is most probably the `config-x86-windows-rel-out.log`, not `install-...`.

Could you double-check and attach the install logs?

**Comment by ufolr** [comment]
Maybe you need  install "CMake & Linux support For Visual C++ "  form “Visual Studio 2017 Installer” in StarMenu.

**Comment by NancyLi1013** [comment]
Please open a new issue if this is still a problem for you.
