### ISSUE TITLE
[boost] update to 1.78.0

### ISSUE THREAD

**Issue by niclar** [microsoft/vcpkg#21921]
Library name: boost

New version number: 1.78

Other information that may be useful: https://www.boost.org/users/history/version_1_78_0.html

**Comment by SeanFarrow** [comment]
I'd be happy to do this if I can work out how to call the generate-ports script. How do I pass in an empty array of libraries? Or should we look to rewrite the script to make the parameter optional?

**Comment by PhoebeHui** [comment]
@SeanFarrow, you can execute the scripts with following command, it will update boost components automatically.
```
"E:\vcpkg\downloads\tools\powershell-core-7.1.4-windows\pwsh.exe" -NoProfile -ExecutionPolicy Bypass "E:\vcpkg\scripts\boost\generate-ports.ps1"
```
