### ISSUE TITLE
uninstall feature

### ISSUE THREAD

**Issue by percin** [microsoft/vcpkg#21934]
I installed vcpkg  and later figured out that I don't need it. How does one completely remove vcpkg and all installations/system changes made by it?

I recall seeing  about vcpkg where it said that you could just delete the vcpkg folder. Also "just delete the folder" being the solution seems implausible to me, since I would assume vcpkg changes some environment variables or other settings, as well as the integration with Visual Studio that I was trying to use. Online search on this topic only yielded people discussing how to remove multiple installed libraries at once, with no clear solution even to that problem (I would be interested in this as well).

As far as I understand, you did not add UNinstall support to the this software with a full bloatware logic.

**Comment by JackBoosY** [comment]
Hi, sorry to hear that.
You can use the following steps:
1. `.\vcpkg integrate remove`
2. Remove folder `%localappdata%/vcpkg`
3. Remove vcpkg folder

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
