### ISSUE TITLE
cannot use qt6 qmake to build project

### ISSUE THREAD

**Issue by Canvis-Me** [microsoft/vcpkg#21936]
When I try to use qt6 qmake to build, it shows:
Could not find qmake spec 'win32-msvc'.

Then adding `-spec D:\vcpkg\installed\x64-windows-static\share\Qt6\mkspecs\win32-msvc` to qmake, it shows:
Project ERROR: Could not find feature thread.

For `qmake -query`, it puts out:
QT_SYSROOT:
QT_INSTALL_PREFIX:D:/vcpkg/installed/x64-windows-static
QT_INSTALL_ARCHDATA:D:/vcpkg/installed/x64-windows-static/share/Qt6
QT_INSTALL_DATA:D:/vcpkg/installed/x64-windows-static/share/Qt6
QT_INSTALL_DOCS:D:/vcpkg/installed/x64-windows-static/doc/Qt6
QT_INSTALL_HEADERS:D:/vcpkg/installed/x64-windows-static/include/Qt6
QT_INSTALL_LIBS:D:/vcpkg/installed/x64-windows-static/lib
QT_INSTALL_LIBEXECS:D:/vcpkg/installed/x64-windows-static/tools/Qt6/bin
QT_INSTALL_BINS:D:/vcpkg/installed/x64-windows-static/bin
QT_INSTALL_TESTS:D:/vcpkg/installed/x64-windows-static/tests
QT_INSTALL_PLUGINS:D:/vcpkg/installed/x64-windows-static/Qt6/plugins
QT_INSTALL_QML:D:/vcpkg/installed/x64-windows-static/Qt6/qml
QT_INSTALL_TRANSLATIONS:D:/vcpkg/installed/x64-windows-static/translations/Qt6
QT_INSTALL_CONFIGURATION:
QT_INSTALL_EXAMPLES:D:/vcpkg/installed/x64-windows-static/share/examples/Qt6
QT_INSTALL_DEMOS:D:/vcpkg/installed/x64-windows-static/share/examples/Qt6
QT_HOST_PREFIX:D:/vcpkg/installed/x64-windows-static
QT_HOST_DATA:D:/share/Qt6
QT_HOST_BINS:D:/vcpkg/installed/x64-windows-static/bin
QT_HOST_LIBEXECS:D:/vcpkg/installed/x64-windows-static/tools/Qt6/bin
QT_HOST_LIBS:D:/vcpkg/installed/x64-windows-static/lib
QMAKE_SPEC:win32-msvc
QMAKE_XSPEC:win32-msvc
QMAKE_VERSION:3.1
QT_VERSION:6.2.2

- OS: Windows 10 19044.1387
- Compiler: Visual Studio Community 2022

But for qt5, qmake works well as usual, and for cmake build project, building poppler-qt6 is fine.
So is there any bug with qt6 qmake?

**Comment by JackBoosY** [comment]
cc @Neumann-A

**Comment by Neumann-A** [comment]
a) which feature set of qtbase the is the featuren concurrent which enables threads
b) which host triplet? QT_HOST_DATA looks wrong. Maybe qt.conf in the folder of qmake wasn't configured correctly.
c) by default -static triplets are not the native host triplets.

**Comment by Canvis-Me** [comment]
> a) which feature set of qtbase the is the featuren concurrent which enables threads b) which host triplet? QT_HOST_DATA looks wrong. Maybe qt.conf in the folder of qmake wasn't configured correctly. c) by default -static triplets are not the native host triplets.

a) I found QThread in 'x64-windows-static\include\Qt6\QtCore', maybe it's qt6 core function?
b) x64-windows-static? I install both x64-windows and x64-windows-static for qt6. Here's the content of `x64-windows-static\tools\Qt6\bin\qt.conf`:
[DevicePaths]
Prefix=./../../../
Headers=include/Qt6/
Libraries=lib
Plugins=Qt6/plugins
Qml2Imports=Qt6/qml
Documentation=doc/Qt6/
Binaries=bin
LibraryExecutables=tools/Qt6/bin
ArchData=share/Qt6
Data=share/Qt6
Translations=translations/Qt6/
Examples=share/examples/Qt6/
[Paths]
Prefix=./../../../
Headers=include/Qt6/
Libraries=lib
Plugins=Qt6/plugins
Qml2Imports=Qt6/qml
Documentation=doc/Qt6/
Binaries=bin
LibraryExecutables=tools/Qt6/bin
ArchData=share/Qt6
Data=share/Qt6
Translations=translations/Qt6/
Examples=share/examples/Qt6/
HostPrefix=./../../../
HostData=./../../..//share/Qt6
HostBinaries=bin
HostLibraries=lib
HostLibraryExecutables=tools/Qt6/bin

It does exist some different paths from qt5, there're no qt5 in my vcpkg now, and I built qt6 from fresh today.

**Comment by Neumann-A** [comment]
Could you manually remove the additional `/` in `HostData=./../../..//share/Qt6` and see if it resolves the issue. If not try to set it to `HostData=share/Qt6`

The reason this is an issue is probably because you didn't do `vcpkg install qtbase --triplet=x64-windows-static --host-triplet=x64-windows-static` As such the qt.conf in x64-windows-static is invalid since the valid one is in x64-windows

**Comment by Canvis-Me** [comment]
Ok, it works fine when set it to `HostData=share/Qt6`.
Yeah, I installed qt6 as `vcpkg install qtbase:x64-windows`. I didn't consider host-triplet before.

**Comment by JackBoosY** [comment]
Please keep this issue open until #21944 merge.
