### ISSUE TITLE
build failed ffmpeg

### ISSUE THREAD

**Issue by JoviNoob** [Microsoft/vcpkg#2194]
https://imgur.com/a/atFkC 
I tried to run the command ".\vcpkg update" and showed one message saying that the build was failed for the library ffmpeg.

**Comment by NancyLi1013** [comment]
Hi @JoviNoob , could you please help confirm whether this issue still exists on your machine?
I try it on my machine and  I can install ffmpeg  successfully. Then I run the command ".\vcpkg update" and  there is no any problem. I cannot reproduce it now.

**Comment by NancyLi1013** [comment]
Please open a new issue if this is still a problem for you.
