### ISSUE TITLE
[New Port Request] libpg_query

### ISSUE THREAD

**Issue by nobyArdor** [microsoft/vcpkg#21945]
Library name: libpg_query

Library description: 
   C library for accessing the PostgreSQL parser outside of the server.

   This library uses the actual PostgreSQL server source to parse SQL queries and return the internal PostgreSQL parse tree.

Source repository URL: https://github.com/pganalyze/libpg_query

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

Because library pg_query does not support c# helpfully to have port of this core lib to make own dotnet lib over

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
