### ISSUE TITLE
[exiv2] Build error

### ISSUE THREAD

**Issue by leashi** [microsoft/vcpkg#21943]
**Host Environment**
- OS: [Windows 7 x64.]
- Compiler: vs2017

**To Reproduce**
`.\vcpkg.exe install exiv2[nls,png,unicode,video,xmp] --triplet x64-windows`

**Failure logs** 
The following packages will be built and installed:
    exiv2[core,nls,png,unicode,video,xmp]:x64-windows -> 0.27.4#2
Detecting compiler hash for triplet x64-windows...
Restored 0 packages from C:\Users\UPUP\AppData\Local\vcpkg\archives in 30.56 ms. Use --debug to see more details.
Starting package 1/1: exiv2:x64-windows
Building package exiv2[core,nls,png,unicode,video,xmp]:x64-windows...
-- Using cached Exiv2-exiv2-15098f4ef50cc721ad0018218acab2ff06e60beb.tar.gz.
-- Cleaning sources at E:/vcpkg/buildtrees/exiv2/src/ff06e60beb-4354818a55.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/vcpkg/downloads/Exiv2-exiv2-15098f4ef50cc721ad0018218acab2ff06e60beb.tar.gz
-- Applying patch fix-ninja-error.patch
-- Using source at E:/vcpkg/buildtrees/exiv2/src/ff06e60beb-4354818a55.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:155 (message):
    Command failed: E:/vcpkg/downloads/tools/cmake-3.21.1-windows/cmake-3.21.1-windows-i386/bin/cmake.exe --build . --config Debug --target install --
 -v -j3
    Working Directory: E:/vcpkg/buildtrees/exiv2/x64-windows-dbg
    See logs for more information:
      E:\vcpkg\buildtrees\exiv2\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:106 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:44 (vcpkg_build_cmake)
  ports/exiv2/portfile.cmake:52 (vcpkg_install_cmake)
  scripts/ports.cmake:142 (include)

Error: Building package exiv2:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+exiv2
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[exiv2]+Build+error
including:
  package: exiv2[core,nls,png,unicode,video,xmp]:x64-windows -> 0.27.4#2
    vcpkg-tool version: 2021-11-24-48b94a6946b8a70abd21529218927fd478d02b6c
    vcpkg-scripts version: 14543ba18 2021-12-08 (11 hours ago)

Additionally, attach any relevant sections from the log files above.

**  **
remove nls is ok.
steps: .\vcpkg.exe install exiv2[png,unicode,video,xmp] --triplet x64-windows

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. This build error will be fix in PR #21941.
