### ISSUE TITLE
[New Port Request] timercpp

### ISSUE THREAD

**Issue by IshaanKarnik** [microsoft/vcpkg#21956]
Library name: timercpp

Library description:

Javascript like timer for c++ developers
This header only library has js equivalent setTimeout() and setInterval() for c++.

Source repository URL: https://github.com/99x/timercpp.git

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
