### ISSUE TITLE
[tmxparser] Build error

### ISSUE THREAD

**Issue by matildelucchesi** [microsoft/vcpkg#21962]
**Host Environment**
- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**
`./vcpkg install xxxx`

**Failure logs** 
Error: Building package tmxparser:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+tmxparser
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[tmxparser]+Build+error
including:
  package: tmxparser[core]:x64-windows -> 2.1.0#6
    vcpkg-tool version: 2021-12-09-724cea8b33cbf06c645f5095fa29773697da9761
    vcpkg-scripts version: 77967a622 2021-12-09 (11 hours ago)

Additionally, attach any relevant sections from the log files above.

**Additional context**
I already tried to use 'git pull' and '.\vcpkg update'

**Comment by JackBoosY** [comment]
Please provide the failure log mentioned in the output message first.

Thanks.
