### ISSUE TITLE
[lodepng] cannot open include file "lodepng.h"

### ISSUE THREAD

**Issue by BTOdell** [microsoft/vcpkg#21961]
**Host Environment**
- OS: Windows 10 21H1
- Compiler: VS2019 MSVC 16.11

**To Reproduce**
https://github.com/BTOdell/maze-bench-cpp/tree/5ca7cd97d897a5a693663f63ca64e7d75d238c9b

- vscode
- cmake
- manifest mode

**Failure logs** 
```
[proc] Executing command: "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" --build d:/Programming/maze-bench-cpp/build --config Debug --target ALL_BUILD -j 34 --
[build] Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework
[build] Copyright (C) Microsoft Corporation. All rights reserved.
[build] 
[build]   main.cpp
[build] D:\Programming\maze-bench-cpp\src\main.cpp(3,10): fatal error C1083: Cannot open include file: 'lodepng.h': No such file or directory [D:\Programming\maze-bench-cpp\build\maze-bench.vcxproj]
[build] Build finished with exit code 1
```

**Additional context**
If I hardcode the include path at the end of the CMakeLists.txt file:
```
target_include_directories(maze-bench PRIVATE "D:/Programming/maze-bench-cpp/build/vcpkg_installed/x64-windows/include")
```
then it builds successfully.

I would expect the usage instructions to include the complete list of CMake commands to use the port, but the current usage instructions are:
```
[cmake] The package lodepng provides CMake targets:
[cmake] 
[cmake]     # C API
[cmake]     find_package(lodepng-c CONFIG REQUIRED)
[cmake]     target_link_libraries(main PRIVATE lodepng-c)
[cmake] 
[cmake]     # C++ API
[cmake]     find_package(lodepng CONFIG REQUIRED)
[cmake]     target_link_libraries(main PRIVATE lodepng)
```

**Comment by JackBoosY** [comment]
Please use `#include <lodepng.h>` instead.

**Comment by dg0yt** [comment]
> Please use #include <lodepng.h> instead.

It is present and failing.

The targets (lodepng, lodepng-c) should carry all what is needed but maybe they lack the include directories. Did you use it in the past? I think it must have been broken before the recent update. The update made the usage explicit based on what was auto-generated.

**Comment by JackBoosY** [comment]
> > Please use #include <lodepng.h> instead.
> 
> It is present and failing.
> 
> The targets (lodepng, lodepng-c) should carry all what is needed but maybe they lack the include directories. Did you use it in the past? I think it must have been broken before the recent update. The update made the usage explicit based on what was auto-generated.

Yes, the `INTERFACE_INCLUDE_DIRECTORIES` should exists in lodepng*-targets.cmake.

It's a port bug.
