### ISSUE TITLE
[vcpkg] appdeploy.ps1 "Join-Path" InvalidArgument error when trying to install plugin dependencies

### ISSUE THREAD

**Issue by Squareys** [microsoft/vcpkg#21968]
**Describe the bug**
Powershell error when compiling projects using e.g. `magnum-plugins` port:
```
Join-Path : A positional parameter cannot be found that accepts argument 'magnum'.
At C:\Repos\vcpkg\scripts\buildsystems\msbuild\applocal.ps1:124 char:61
+ ... um $targetBinaryDir (Join-Path "$g_install_root" 'bin' 'magnum') "$_"
+                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Join-Path], ParameterBindingExcepti
   on
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands
   .JoinPathCommand
```

**Environment**
- OS: Windows
- Compiler: MSVC 19.29.30136.0

**To Reproduce**
1. ./vcpkg install magnum-plugins
2. Set up basic cmake or VS project that uses Magnum::Trade from the `magnum` port (this triggers installation of plugins into a magnum/importers directory)
2. See error during build

**Expected behavior**
No error, plugin dependencies are copied directly.

**Failure logs** 
-(please attached failure logs)

**Additional context**
Commit https://github.com/microsoft/vcpkg/commit/7dff5e821e4a0b7fe43e8a28c51357217bb4bef6 by @dg0yt uses `Join-Path` which joins two paths, but tries to join three.

**Comment by dg0yt** [comment]
IIUC `Join-Path` should join an indefinite numer of paths, cf. example 7 of https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/join-path?view=powershell-7.2

**Comment by dg0yt** [comment]
This `Join-Path` feature may need PowerShell >=6.
