### ISSUE TITLE
[coolprop] Does not build in static

### ISSUE THREAD

**Issue by nitrogene** [Microsoft/vcpkg#2196]
I can not install coolprop in static with x64-windows-static. As you can see below, vcpkg search for lib in:

/install_root/static_library/Windows/**_64bit_**/ 

but it is generated in 

/install_root/static_library/Windows/_**64bit_MSVC_19.11.25547.0**_/

Building package coolprop:x64-windows-static...
-- CURRENT_INSTALLED_DIR=D:/Dev/vcpkg/installed/x64-windows-static
-- DOWNLOADS=D:/Dev/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=D:/Dev/vcpkg/packages/coolprop_x64-windows-static
-- CURRENT_BUILDTREES_DIR=D:/Dev/vcpkg/buildtrees/coolprop
-- CURRENT_PORT_DIR=D:/Dev/vcpkg/ports/coolprop/.
-- Using cached D:/Dev/vcpkg/downloads/CoolProp-CoolProp-0e934e842e9ce83eea64fda1d4ab8e59adf9d8cd.tar.gz
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Configuring x64-windows-static-rel
-- Configuring x64-windows-static-rel done
-- Configuring x64-windows-static-dbg
-- Configuring x64-windows-static-dbg done
-- Build x64-windows-static-rel
-- Build x64-windows-static-rel done
-- Build x64-windows-static-dbg
-- Build x64-windows-static-dbg done
-- Installing: D:/Dev/vcpkg/packages/coolprop_x64-windows-static/include/CoolPropLib.h
CMake Error at ports/coolprop/portfile.cmake:98 (file):
  file INSTALL cannot find
  "D:/Dev/vcpkg/buildtrees/coolprop/src/CoolProp-0e934e842e9ce83eea64fda1d4ab8e59adf9d8cd/install_root/static_library/Windows/64bit/CoolProp.lib".
Call Stack (most recent call first):
  scripts/ports.cmake:72 (include)

**Comment by NancyLi1013** [comment]
Please open a new issue if this is still a problem for you.
