### ISSUE TITLE
[python3] Build error

### ISSUE THREAD

**Issue by sbrosgol** [microsoft/vcpkg#21974]
**Host Environment**
- OS: MacOS 12
- Compiler: revision

**To Reproduce**
`./vcpkg install boost`

-- Downloading https://github.com/python/cpython/archive/v3.10.1.tar.gz -> python-cpython-v3.10.1.tar.gz...
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' = off
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] popen(curl --fail -L https://github.com/python/cpython/archive/v3.10.1.tar.gz --create-dirs --output /Users/slava_brosgol/dev/vcpkg/downloads/python-cpython-v3.10.1.tar.gz.76167.part 2>&1)
[DEBUG] cmd_execute_and_stream_data() returned 0 after  4873283 us
Error: Failed to download from mirror set:
File does not have the expected hash:
             url : [ https://github.com/python/cpython/archive/v3.10.1.tar.gz ]
       File path : [ /Users/slava_brosgol/dev/vcpkg/downloads/python-cpython-v3.10.1.tar.gz.76167.part ]
   Expected hash : [ d83e0685c274be09da7833a3c24b7379ae0e43b43c131f11bfaccd5902f6a1c510a3ae67c42471a4281922ead3bd34856608ec47be7dd76ddd734e59906ba03b ]
     Actual hash : [ 23f99b77c7978282d43a6e442811de1d6e8cc9597c6d1143ec65ae986f64805c36a0a033632a4d1a89053a55854904bcf11415d91e2a3b4a5308c4a21de80098 ]

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by dfederm** [comment]
This is due to my recent change. I missed this hash update and it wasn't caught in the PR gate.

I'll fix it in a few hours when I'm at a computer unless someone beats me to it
