### ISSUE TITLE
[fontconfig] Build error

### ISSUE THREAD

**Issue by leashi** [microsoft/vcpkg#21976]
**Host Environment**
- OS: Windows 7 sp1 x64
- Compiler: VS2017  15.9.41

**To Reproduce**
`.\vcpkg.exe install fontconfig --triplet x64-windows`

**Failure logs** 
PS E:\vcpkg> .\vcpkg.exe install fontconfig --triplet x64-windows
Computing installation plan...
The following packages will be built and installed:
    fontconfig[core]:x64-windows -> 2.13.94#4
Detecting compiler hash for triplet x64-windows...
Restored 0 packages from C:\Users\UPUP\AppData\Local\vcpkg\archives in 27.63 ms. Use --debug to see more details.
Starting package 1/1: fontconfig:x64-windows
Building package fontconfig[core]:x64-windows...
-- Using cached fontconfig-fontconfig-2.13.94.tar.gz.
-- Cleaning sources at E:/vcpkg/buildtrees/fontconfig/src/2.13.94-6fd83e1cbe.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/vcpkg/downloads/fontconfig-fontconfig-2.13.94.tar.gz
-- Using source at E:/vcpkg/buildtrees/fontconfig/src/2.13.94-6fd83e1cbe.clean
-- Getting CMake variables for x64-windows
-- Downloading https://www.python.org/ftp/python/3.10.1/python-3.10.1-embed-amd64.zip -> python-3.10.1-embed-amd64.zip...
-- Using cached msys-mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst.
-- Using msys root at E:/vcpkg/downloads/tools/msys2/aa5af7b2aa7e90e8
-- Configuring x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: E:/vcpkg/downloads/tools/python/python-3.10.1-x64/python.exe E:/vcpkg/installed/x64-windows/tools/meson/meson.py -Ddoc=disabled --
buildtype plain --backend ninja --wrap-mode nodownload --native E:/vcpkg/buildtrees/fontconfig/meson-native-x64-windows.log --default-library shared -
-libdir lib --native E:/vcpkg/buildtrees/fontconfig/meson-native-x64-windows-debug.log -Ddebug=true --prefix E:/vcpkg/packages/fontconfig_x64-windows/
debug --includedir ../include -Dcmake_prefix_path=['E:/vcpkg/installed/x64-windows/debug','E:/vcpkg/installed/x64-windows','E:/vcpkg/installed/x64-win
dows/share'] E:/vcpkg/buildtrees/fontconfig/src/2.13.94-6fd83e1cbe.clean
    Working Directory: E:/vcpkg/buildtrees/fontconfig/x64-windows-dbg
    Error code: Exit code 0xc0000135

    See logs for more information:

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_meson.cmake:512 (vcpkg_execute_required_process)
  ports/fontconfig/portfile.cmake:16 (vcpkg_configure_meson)
  scripts/ports.cmake:142 (include)

Error: Building package fontconfig:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+fontconfig
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[fontconfig]+Build+error
including:
  package: fontconfig[core]:x64-windows -> 2.13.94#4
    vcpkg-tool version: 2021-11-24-48b94a6946b8a70abd21529218927fd478d02b6c
    vcpkg-scripts version: a8204d987 2021-12-10 (3 hours ago)

Additionally, attach any relevant sections from the log files above.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Could you please provide the fail log file?

**Comment by leashi** [comment]
[fontconfig-log.zip](https://github.com/microsoft/vcpkg/files/7701744/fontconfig-log.zip)

**Comment by leashi** [comment]
> Thanks for posting this issue. Could you please provide the fail log file?

[fontconfig-log.zip](https://github.com/microsoft/vcpkg/files/7701752/fontconfig-log.zip)

**Comment by LilyWangLL** [comment]
Thanks for your reply. Did you try installing the Proper Version of the .NET Framework? I found this messsage in your log: Error `code: Exit code 0xc0000135`. `0xc0000135` error can happens when you run a program that requires the .NET framework, but your computer doesn’t have the .NET framework or doesn’t install the .NET framework properly.

You can check if there is the .NET framework on your PC. Type “control panel” in the search bar to open the Control Panel. Click Programs in the Control Panel, then find Programs and Features and click it. All the programs installed on your computer are listed. Check if there is any form of the .NET framework.

If there is the .NET framework, just uninstall it and then have it reinstalled. If not, you can download the proper version of .NET framework from Microsoft official website and install it. After the .NET framework installed, remember to reboot your computer

**Comment by leashi** [comment]
> Thanks for your reply. Did you try installing the Proper Version of the .NET Framework? I found this messsage in your log: Error `code: Exit code 0xc0000135`. `0xc0000135` error can happens when you run a program that requires the .NET framework, but your computer doesn’t have the .NET framework or doesn’t install the .NET framework properly.
> 
> You can check if there is the .NET framework on your PC. Type “control panel” in the search bar to open the Control Panel. Click Programs in the Control Panel, then find Programs and Features and click it. All the programs installed on your computer are listed. Check if there is any form of the .NET framework.
> 
> If there is the .NET framework, just uninstall it and then have it reinstalled. If not, you can download the proper version of .NET framework from Microsoft official website and install it. After the .NET framework installed, remember to reboot your computer

I found, has nothing to do with .Net framework. Python 3.9 and above do not support Windows 7, and python 3.10 is used in vcpkg.

**Comment by leashi** [comment]
hi,!
Thanks for your reply.
I found, has nothing to do with .Net framework. Python 3.9 and above do not support Windows 7, and python 3.10 is used in vcpkg.




***@***.***
 
From: LilyWangLL
Date: 2021-12-14 10:15
To: microsoft/vcpkg
CC: leashi; Author
Subject: Re: [microsoft/vcpkg] [fontconfig] Build error (Issue #21976)
Thanks for your reply. Did you try installing the Proper Version of the .NET Framework? I found this messsage in your log: Error code: Exit code 0xc0000135. 0xc0000135 error can happens when you run a program that requires the .NET framework, but your computer doesn’t have the .NET framework or doesn’t install the .NET framework properly.
You can check if there is the .NET framework on your PC. Type “control panel” in the search bar to open the Control Panel. Click Programs in the Control Panel, then find Programs and Features and click it. All the programs installed on your computer are listed Check if there is any form of the .NET framework.
If there is the .NET framework, just uninstall it and then have it reinstalled. If not, you can download the proper version of .NET framework from Microsoft official website and install it. After the .NET framework installed, remember to reboot your computer
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by JackBoosY** [comment]
@leashi Yes, python 3.9 has dropped support with Windows 7, and we should add feature `depreciate-win7` to fontconfig to avoid this.

**Comment by JackBoosY** [comment]
After some discussion, I think this new feature shouldn't be added since it conflicts with non-win7.
Please use overlay port to change the fontconfig dependency python3 to `python3[deprecated-win7-support]`.

Thanks.

**Comment by LilyWangLL** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
