### ISSUE TITLE
[tiff] Build error

### ISSUE THREAD

**Issue by PortalRising** [microsoft/vcpkg#21986]
**Host Environment**
- OS: Windows
- Compiler: CMake with Visual Studio 2022

**To Reproduce**
`./vcpkg install tiff`

**Additional context**
I have installed this before but when I updated vcpkg, i get this error (in log file attached)
"
Error: Failed to download from mirror set:
https://download.osgeo.org/libtiff/tiff-4.3.0.tar.gz: WinHttpSendRequest() failed: 12007
...
Error: Building package tiff:x86-windows failed with: BUILD_FAILED
"
I have tried pinging download.osgeo.org but I get the error "Ping request could not find host download.osgeo.org. Please check the name and try again."
[logFile.txt](https://github.com/microsoft/vcpkg/files/7697407/logFile.txt)

**Comment by dg0yt** [comment]
Check your network. https://download.osgeo.org/libtiff/ is online.

**Comment by PortalRising** [comment]
Thanks, must of had been shutdown or smth.
