### ISSUE TITLE
[SDL2] Could not find a package configuration file

### ISSUE THREAD

**Issue by EiEddie** [microsoft/vcpkg#21983]
**Describe the bug**
Could not find a package configuration file provided by "SDL2" with any of the following names:

>  SDL2Config.cmake
>  sdl2-config.cmake

I sure that I install the package SDL2, because:

```cmd
> vcpkg install sdl2:x64-mingw-static
Computing installation plan...
The following packages are already installed:
    sdl2[core]:x64-mingw-static -> 2.0.16#3
Package sdl2:x64-mingw-static is already installed
Restored 0 packages from C:\Users\EiEddie\AppData\Local\vcpkg\archives in 309.3 us. Use --debug to see more details.

Total elapsed time: 10.34 ms

The package sdl2 provides CMake targets:

    find_package(SDL2 CONFIG REQUIRED)
    target_link_libraries(main PRIVATE SDL2::SDL2 SDL2::SDL2main SDL2::SDL2-static)
```

**Environment**
- OS: Windows 10
- Compiler: gcc/g++ 8.1.0 (x86_64-posix-sjlj-rev0, Built by MinGW-W64 project)
- Builder: cmake 3.21.1

**To Reproduce**
- `cmake .. -G "MinGW Makefiles" -D CMAKE_TOOLCHAIN_FILE=E:/vcpkg/scripts/buildsystems/vcpkg.cmake`

- CMakeLists.txt:
```cmake
cmake_minimum_required(VERSION 3.21)

project(main)

find_package(SDL2 REQUIRED)

add_executable(main main.cpp)

target_link_libraries(main PRIVATE SDL2::SDL2 SDL2::SDL2main SDL2::SDL2-static)
```

**Failure logs** 
``` CMake Error at CMakeLists.txt:19 (find_package):
  By not providing "FindSDL2.cmake" in CMAKE_MODULE_PATH this project has   
  asked CMake to find a package configuration file provided by "SDL2", but  
  CMake did not find one.

 Could not find a package configuration file provided by "SDL2" with any of
  the following names:

    SDL2Config.cmake
    sdl2-config.cmake

  Add the installation prefix of "SDL2" to CMAKE_PREFIX_PATH or set
  "SDL2_DIR" to a directory containing one of the above files.  If "SDL2"
  provides a separate development package or SDK, be sure it has been
  installed.
-- Configuring incomplete, errors occurred!
See also "D:/Temp/jsoncppLearn/build/CMakeFiles/CMakeOutput.log".
```
[CMakeOutput.log](https://github.com/microsoft/vcpkg/files/7696803/CMakeOutput.log)

**Comment by m-decoster** [comment]
Have you tried setting `SDL2_DIR` to `vcpkg/installed/x64-windows/share/sdl2`?

**Comment by EiEddie** [comment]
> Have you tried setting `SDL2_DIR` to `vcpkg/installed/x64-windows/share/sdl2`?

No, but I tried to add `-DCMAKE_PREFIX_PATH=E:\vcpkg\installed\x64-mingw-static` when build. It also works.

**Comment by dg0yt** [comment]
> > Have you tried setting `SDL2_DIR` to `vcpkg/installed/x64-windows/share/sdl2`?

This is not the right path for mingw.

> No, but I tried to add `-DCMAKE_PREFIX_PATH=E:\vcpkg\installed\x64-mingw-static` when build. It also works.

This is strange. The cmake toolchain already sets `CMAKE_PREFIX_PATH`.

If you want to debug `find_package(SDL2 REQUIRED)`, you can add `set(CMAKE_FIND_DEBUG_MODE 1)` before that line.

Do you explicitly set host and target triplet to mingw, e.g. using environment variables?
