### ISSUE TITLE
[

### ISSUE THREAD

**Issue by hex55** [microsoft/vcpkg#21985]
**Host Environment**
- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**
`./vcpkg install xxxx`

**Failure logs** 
-Cut and paste the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by JonLiu1993** [comment]
@hex55 ,Please follow the template prompts to resubmit the issue. You need to provide your Visual Studio version, OS type, related ports, detailed error logs, steps to reproduce, etc. This issue is temporarily closed. thanks
