### ISSUE TITLE
[qtwebengine] build failure

### ISSUE THREAD

**Issue by Canvis-Me** [microsoft/vcpkg#21981]
- OS: Windows 10
- Compiler: visual studio community 2022

`.\vcpkg install qtwebengine[proprietary-codecs]:x64-windows`

**Failure logs** 

My terminal emulator swallowed my error messages. Here are attached files.
[install-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/7696638/install-x64-windows-rel-out.log)
[install-x64-windows-rel-err.log](https://github.com/microsoft/vcpkg/files/7696639/install-x64-windows-rel-err.log)

I tried some times to build it, still failed.

**Comment by Neumann-A** [comment]
`D:\vcpkg\buildtrees\qtwebengine\x64-windows-rel\` the path is too long 

use `.\vcpkg install qtwebengine[proprietary-codecs]:x64-windows --x-buildtrees-root=D:\b\`

**Comment by Canvis-Me** [comment]
I got only 16G memory on my computer, it seemed not enough to build qtwebengine, for another error occur:

-- Building x64-windows-dbg
-- Restarting Build without parallelism because memory exceeded
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:155 (message):
    Command failed: D:/vcpkg/downloads/tools/cmake-3.21.1-windows/cmake-3.21.1-windows-i
386/bin/cmake.exe --build . --config Debug --target install -- -v -j25
    Working Directory: U://qtwebengine/x64-windows-dbg
    See logs for more information:
      U:\qtwebengine\install-x64-windows-dbg-out.log
      U:\qtwebengine\install-x64-windows-dbg-err.log
      U:\qtwebengine\install-x64-windows-dbg-out-1.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:106 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:44 (vcpkg_build_cmake)
  ports/qtwebengine/portfile.cmake:104 (vcpkg_install_cmake)
  scripts/ports.cmake:142 (include)

Error: Building package qtwebengine:x64-windows failed with: BUILD_FAILED
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/7708431/install-x64-windows-dbg-out.log)
[install-x64-windows-dbg-out-1.log](https://github.com/microsoft/vcpkg/files/7708432/install-x64-windows-dbg-out-1.log)
[install-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/7708433/install-x64-windows-dbg-err.log)

So is there anyway to build it?

**Comment by JackBoosY** [comment]
`fatal error C1060: compiler is out of heap space`
Maybe qt doesn't support VS2022 officially.

**Comment by Canvis-Me** [comment]
Finally built it with vs2019.

**Comment by Neumann-A** [comment]
> fatal error C1060: compiler is out of heap space

cannot do anything but setting VCPKG_CONCURRENCY to 1 and wait a week for it to build. If it runs out while linking there is probably no solution to that problem except upgrading the hardware.
