### ISSUE TITLE
[documentation] add integration hint about `cmake kits` with vscode cmake-tools extension

### ISSUE THREAD

**Issue by Locietta** [microsoft/vcpkg#21988]
**Is your feature request related to a problem? Please describe.**

Hi, I'm currently using vcpkg with vscode and cmake to build some cross-platfrom cmake projects. 

So I'm trying to change the triplet according to toolchains. (e.g. need to change triplet to `x64-linux` for linux, or to `arm64-android` for android), and I don't find any convenient way to switch them in docs.

And since vcpkg currently integrate itself into cmake with a toolchain file, so a simple if-else in CMakeLists.txt doesn't work.

```cmake
# this don't work because it have to be placed before project() call

if (MSVC) # some if-else to detect different toolchain
set(VCPKG_TARGET_TRIPLET x64-windows 
  CACHE STRING "Vcpkg triplet")
endif(MSVC)
```

**Proposed solution**

After some research, I found something about [CMake Kits](https://github.com/microsoft/vscode-cmake-tools/blob/main/docs/kits.md) in vscode-cmake-tools docs. It's said that the extension support user-defined kits, which allows to define named toolchains with a toolchain file and several cache variables.

Here's an example to define named toolchain with vcpkg integration and a specific triplet in `.vscode/cmake-kits.json`. 

```json
[
  {
    "name": "Visual Studio Community 2022 Release - amd64_arm64",
    "visualStudio": "8a215db0",
    "visualStudioArchitecture": "x64",
    "toolchainFile": "D:\\vcpkg\\scripts\\buildsystems\\vcpkg.cmake",
    "preferredGenerator": {
      "name": "Visual Studio 17 2022",
      "platform": "arm64",
      "toolset": "host=x64"
    },
    "cmakeSettings": {
      "VCPKG_TARGET_TRIPLET": "arm64-windows",
      "VCPKG_CHAINLOAD_TOOLCHAIN_FILE": "path/to/additional-toolchain-file.cmake"
    }
  }
]
```

I think this deserves to be documented somewhere here, and may be preferred compared to the current method described in `README.md` as it allows more flexibility. It seems to make more sense to bind different triplets to different toolchains after all 😀

**Comment by Neumann-A** [comment]
Personally I don't think this is on the vcpkg side. vcpkg already documents how to use the cmake toolchain file. How vs code implements setting cmake variables is also already documented so this is just info on how to put both together. That being said the consumption via presets in vs code is also different from the above way. 
Also:
`"visualStudio": "8a215db0",` is as far as I remember dependent on the installation and unique for each machine.
```
    "preferredGenerator": {
      "name": "Visual Studio 17 2022",
```
if you use the VS generator cmake presets seem to be a better solution to the old CMake kits. (Presets are only problematic for none vs generators since they don't automatically run vcvars.)

**Comment by JackBoosY** [comment]
Yeah, we should provide the VS Code plugin and it's on the road.

**Comment by Locietta** [comment]
Thanks for the information about cmake presets, I will try that out sometime. Sounds like I missed something about cmake configs.

> "visualStudio": "8a215db0", is as far as I remember dependent on the installation and unique for each machine.

I actually copy the configuration auto-generated by vscode, and add some options on it. It just worked, but as Neumann suggests, it's not portable when sharing configs. 

Sorry for the noise here, I'm going to close this issue.
