### ISSUE TITLE
[mlpack] Build error

### ISSUE THREAD

**Issue by Blakjak88** [microsoft/vcpkg#21984]
**Host Environment**
- OS: Windows 10 
- Compiler: Visual Studio C++ 2022

**To Reproduce**
[config-x64-windows-static-out.log](https://github.com/microsoft/vcpkg/files/7696998/config-x64-windows-static-out.log)

`./vcpkg install mlpack`

**Failure logs** 
  package: mlpack[core]:x64-windows-static -> 3.4.1#2
    vcpkg-tool version: 2021-11-24-48b94a6946b8a70abd21529218927fd478d02b6c
    vcpkg-scripts version: 1b664707c 2021-11-30 (10 days ago)

**Additional context**
I submitted this before and was told it was linked to #20439 but I see that issue is closed and I still have this error after doing a fresh updated of VCPKG.
[config-x64-windows-static-out.log](https://github.com/microsoft/vcpkg/files/7696999/config-x64-windows-static-out.log)

**Comment by JackBoosY** [comment]
This issue should be fixed before, can you please git pull, remove port `Armadillo` and try again?

Thanks.

**Comment by JonLiu1993** [comment]
@Blakjak88 ,Thanks for posting this issue, please git pull and try again, I can install mlpack[core]:x64-windows-static successfully in my local machine:
````
Building package mlpack[core]:x64-windows-static...
-- Using cached mlpack-mlpack-7ae9ddda86c1751b6509ceb48b27d182feaae439.tar.gz.
-- Using source at F:/test-pr/mlpack/vcpkg/buildtrees/mlpack/src/82feaae439-787f7149b5
-- Found external ninja('1.10.2').
-- Configuring x64-windows-static-dbg
-- Configuring x64-windows-static-rel
-- Building x64-windows-static-dbg
-- Building x64-windows-static-rel
-- Using cached msys-mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst.
-- Using msys root at F:/test-pr/mlpack/vcpkg/downloads/tools/msys2/aa5af7b2aa7e90e8
-- Installing: F:/test-pr/mlpack/vcpkg/packages/mlpack_x64-windows-static/share/mlpack/copyright
-- Performing post-build validation
-- Performing post-build validation done
Installing package mlpack[core]:x64-windows-static...
Elapsed time for package mlpack:x64-windows-static: 2.066 min

Total elapsed time: 11.46 min

The package mlpack provides CMake targets:

    find_package(mlpack CONFIG REQUIRED)
    target_link_libraries(main PRIVATE mlpack::mlpack)
````
Please reopen this issue if it still be a problem for you.
