### ISSUE TITLE
How do I force building a package

### ISSUE THREAD

**Issue by acceleratxr** [microsoft/vcpkg#21990]
In my project I have multiple triplet overlays as I need to specify custom build parameters. In the most recent version of vcpkg I am finding that when installing my packages it appears to be skipping the build process and instead downloading a pre-built binary package of the dependency instead. This is causing linker issues later on in my build since the downloaded binaries aren't compatible.

I install the packages using a command like so...
```
.\vcpkg.exe install <packages> --recurse --overlay-triplets=..\triplets\v142 --triplet x64-windows-static
```

The triplet I am attempting to override looks like the following:
```
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_PLATFORM_TOOLSET v142)
set(VCPKG_C_FLAGS_DEBUG "/D_ITERATOR_DEBUG_LEVEL=0")
set(VCPKG_CXX_FLAGS_DEBUG "/D_ITERATOR_DEBUG_LEVEL=0")
```

Predictably since my triplet isn't being respected I am getting the following errors in my build process.

```
error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug'
error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0'
```

How do I force vcpkg to build the packages instead of using a pre-built binary?

**Comment by dg0yt** [comment]
> How do I force vcpkg to build the packages instead of using a pre-built binary?

As an immediate workaround, use `--no-binarycaching`.

**Comment by acceleratxr** [comment]
> > How do I force vcpkg to build the packages instead of using a pre-built binary?
> 
> As an immediate workaround, use `--no-binarycaching`.

That does appear to be building the packages now but i'm still getting the same linker errors as if it's still not respecting my triplet overlay.

FYI that flag doesn't appear to be documented anywhere.

**Comment by acceleratxr** [comment]
Oops, I figured out it was an issue on my end. The pathing was wrong (I had moved some things around in my cmake file and it was broken afterward). It's now respecting my triplet overlay.

It'd probably be helpful for vcpkg to exit with an error if an invalid triplet-overlay path is specified.

**Comment by autoantwort** [comment]
> FYI that flag doesn't appear to be documented anywhere.

Because disabling binary caching does not help in cases like this, like in your case. I suggest using a new unique name to detect wrong overlay triplet paths, then the error would have been recognized earlier.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
