### ISSUE TITLE
[caf] Build error

### ISSUE THREAD

**Issue by MoeSzyslak98** [microsoft/vcpkg#21994]
**Host Environment**
- OS: Manjaro 2021.1
- Compiler: c++ 11.1.0

**To Reproduce**
`./vcpkg install caf`

**Failure logs** 
form vcpkg/buildtrees/caf/src/5c3cea9cb5-e41d5b113c.clean/libcaf_io/caf/io/network/receive_buffer.hpp:90:17: error: ‘numeric_limits’ is not a member of ‘std’
   90 |     return std::numeric_limits<size_t>::max();
      |                 ^~~~~~~~~~~~~~
vcpkg/buildtrees/caf/src/5c3cea9cb5-e41d5b113c.clean/libcaf_io/caf/io/network/receive_buffer.hpp:90:38: error: expected primary-expression before ‘>’ token
   90 |     return std::numeric_limits<size_t>::max();
      |                                      ^
vcpkg/buildtrees/caf/src/5c3cea9cb5-e41d5b113c.clean/libcaf_io/caf/io/network/receive_buffer.hpp:90:41: error: ‘::max’ has not been declared; did you mean ‘std::max’?
   90 |     return std::numeric_limits<size_t>::max();
      |                                         ^~~
      |                                         std::max
In file included from /usr/include/c++/11.1.0/algorithm:62,
                 from vcpkg/buildtrees/caf/src/5c3cea9cb5-e41d5b113c.clean/libcaf_io/src/io/network/receive_buffer.cpp:19:
/usr/include/c++/11.1.0/bits/stl_algo.h:3467:5: note: ‘std::max’ declared here
 3467 |     max(initializer_list<_Tp> __l, _Compare __comp)
      |     ^~~

**Additional context**
====================|  Build Summary  |====================

CAF version:           0.17.6

Build type:            Debug
Build static:          ON
Build static only:     ON
Build static runtime:  no
Runtime checks:        no
Log level:             QUIET
With mem. mgmt.:       yes
With exceptions:       yes

Build I/O module:      yes
Build tools:           no
Build examples:        no
Build unit tests:      no
Build OpenCL:          no
Build OpenSSL:         yes
Build Python:          yes

CXX:                   /usr/bin/c++
CXXFLAGS:              -std=c++11 -fPIC -ftemplate-depth=512 -ftemplate-backtrace-limit=0 -Wno-missing-field-initializers -pthread -g
LINKER_FLAGS (shared)  Threads::Threads

Source directory:      vcpkg/buildtrees/caf/src/5c3cea9cb5-e41d5b113c.clean
Build directory:       vcpkg/buildtrees/caf/x64-linux-dbg
Executable path:       vcpkg/buildtrees/caf/x64-linux-dbg/bin
Library path:          vcpkg/buildtrees/caf/x64-linux-dbg/lib
Install prefix:        vcpkg/packages/caf_x64-linux/debug
Generator:             Ninja

===========================================================

-- Configuring done
-- Generating done
-- Build files have been written to:  vcpkg/buildtrees/caf/x64-linux-dbg
 
I cloned, build and installed CAF manually. and it's working, i don't know why this error came up when i tried vcpkg.

**Comment by Osyotr** [comment]
It's a common issue when compiling code that was written prior to GCC11 release. You can either create a patch for current version or update version of the library.
Similar: https://github.com/microsoft/vcpkg/commit/e14842c4462c5d3542b58dcc3de742139da06979

**Comment by PhoebeHui** [comment]
@MoeSzyslak98, it looks an upstream issue with gcc11, could you report an issue to Upstream instead? it builts successfully with gcc 9.4.0 for me.

**Comment by MoeSzyslak98** [comment]
> It's a common issue when compiling code that was written prior to GCC11 release. You can either create a patch for current version or update version of the library.
> Similar: https://github.com/microsoft/vcpkg/commit/e14842c4462c5d3542b58dcc3de742139da06979

thanks for the comment, I try to do so.[Im a little bit noob tho].

**Comment by PhoebeHui** [comment]
@MoeSzyslak98, we're happy to accept a PR for this issue.

**Comment by PhoebeHui** [comment]
@MoeSzyslak98, could you help confirm if PR #22046 works for you?
