### ISSUE TITLE
open62541 build failure on both x86 and x64

### ISSUE THREAD

**Issue by JamMika** [microsoft/vcpkg#21997]
**Host Environment**
- OS: Windows 10
- Compiler: Microsoft Visual C++ 2019

**To Reproduce**
`./vcpkg install open62541:x86-windows`
or
`./vcpkg install open62541:x64-windows`

**Failure logs** 
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: ninja -v
    Working Directory: D:/dev/C++/_vcpkg/vcpkg/buildtrees/open62541/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\dev\C++\_vcpkg\vcpkg\buildtrees\open62541\config-x64-windows-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:407 (vcpkg_execute_required_process)
  ports/open62541/portfile.cmake:23 (vcpkg_cmake_configure)
  scripts/ports.cmake:142 (include)

AND

CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: ninja -v
    Working Directory: D:/dev/C++/_vcpkg/vcpkg/buildtrees/open62541/x86-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\dev\C++\_vcpkg\vcpkg\buildtrees\open62541\config-x86-windows-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:407 (vcpkg_execute_required_process)
  ports/open62541/portfile.cmake:23 (vcpkg_cmake_configure)
  scripts/ports.cmake:142 (include)
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/7699810/config-x64-windows-out.log)
[config-x86-windows-out.log](https://github.com/microsoft/vcpkg/files/7699811/config-x86-windows-out.log)
[stdout-x64-windows.log](https://github.com/microsoft/vcpkg/files/7699812/stdout-x64-windows.log)
[stdout-x86-windows.log](https://github.com/microsoft/vcpkg/files/7699813/stdout-x86-windows.log)

**Comment by Neumann-A** [comment]
rename the folder to `cpp` instead of `C++`. Also that is an upstream issues not strictly a vcpkg issue.

**Comment by PhoebeHui** [comment]
@JamMika, could you try the suggestion provided by Neumann-A?

Falilures:
```
CMake Error at CMakeLists.txt:1534 (if):
  if given arguments:

    "D:/dev/C++/_vcpkg/vcpkg/buildtrees/open62541/x64-windows-rel/src_generated/open62541/config.h" "MATCHES" "D:/dev/C++/_vcpkg/vcpkg/buildtrees/open62541/src/v1.2.2-bb014958a9.clean/deps"

  Regular expression
  "D:/dev/C++/_vcpkg/vcpkg/buildtrees/open62541/src/v1.2.2-bb014958a9.clean/deps"
  cannot compile

-- Configuring incomplete, errors occurred!
See also "D:/dev/C++/_vcpkg/vcpkg/buildtrees/open62541/x64-windows-rel/CMakeFiles/CMakeOutput.log".
RegularExpression::compile(): Nested *?+.
RegularExpression::compile(): Error in compile.
```

**Comment by JamMika** [comment]
Thank you. The suggestion from Neumann worked well.
For your information I have sent the ticket to open62541 project as well, they can fix CMakeLists issue with ++.
