### ISSUE TITLE
在中文环境下的严重问题：如果vs没有安装英文语言包，有些库编译无法通过。如果系统没有英文语言包，vs默认不安装英文包

### ISSUE THREAD

**Issue by how0723** [Microsoft/vcpkg#2199]
在中文环境下的严重问题：如果vs没有安装英文语言包，有些库编译无法通过。如果系统没有英文语言包，vs默认不安装英文包

**Comment by jasjuang** [comment]
I happen to know Chinese so I can translate this issue. Basically it is saying in a Chinese version Windows, if the English language pack is not installed, vcpkg compilation will fail

**Comment by lethe555** [comment]
look this [CMake 3.9 Generates build.ninja failed on Non-Engish Windows](https://gitlab.kitware.com/cmake/cmake/issues/17191)

**Comment by how0723** [comment]
i have solve this problem

**Comment by jasjuang** [comment]
@how0723 Please let us know how you solve the problem so if people run into the same problem in the future they will know how to solve it.

**Comment by how0723** [comment]
ok. install English language pack for your windows system. then install English language pack for your vs2017 or vs2015.
