### ISSUE TITLE
Port showing in vcpkg.info but not available in search/install

### ISSUE THREAD

**Issue by skizzay** [microsoft/vcpkg#22010]
**Describe the bug**
I can search vcpkg.info for package stduuid.  I see the package listing properly returned.  It even has a link to its vcpkg folder.  However, the link brings you to GitHub's 404 page.  Further, when I run vcpkg install stduuid or even vcpkg search stduuid, nothing comes back.  I've looked in my ports directory and don't see it.  When I searched the vcpkg github repo, I see two commits with the second reverting the installation provided in the first. 

**Environment**
- OS: Link
- Compiler: GCC

**To Reproduce**
1. Go to vcpkg.info
2. Search for "stduuid"
3. See listing
4. ./vcpkg install stduuid
5. See error
6. ./vcpkg search stduuid
7. See error

**Expected behavior**
Consistency between vcpkg.info and actual package availability.  In this particular scenario, I'd prefer for the package to be made available.  However, I understand that there may be circumstances that this isn't possible.  Regardless, it shouldn't be returned in the vcpkg.info search listing.

**Failure logs** 
- none

**Additional context**
noe

**Comment by autoantwort** [comment]
>  Regardless, it shouldn't be returned in the vcpkg.info search listing.

vcpkg.info is not maintained by the vcpkg team, you can contact the maintainer [here](https://vcpkg.info/contact)

**Comment by PhoebeHui** [comment]
@skizzay, the official webiste is https://vcpkg.io/en/index.html, you can check the availlable packages in https://vcpkg.io/en/packages.html. 

The new port was added by https://github.com/microsoft/vcpkg/pull/16382. however it cause CI regressions, so it has been reverted by https://github.com/microsoft/vcpkg/pull/20161. you can create a [overlay ports](https://github.com/microsoft/vcpkg/blob/master/docs/specifications/ports-overlay.md) with changes in https://github.com/microsoft/vcpkg/pull/16382, or you can open a new PR and resolve the issue mentioned in https://github.com/microsoft/vcpkg/pull/16382#issuecomment-919500382. we're happy to accept a PR for this.

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue and continue the PR, but we're closing it for now, consider making a pull request instead.
