### ISSUE TITLE
[cudnn] Build error

### ISSUE THREAD

**Issue by Anassatti** [microsoft/vcpkg#22019]
**Host Environment**
- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**
`./vcpkg install xxxx`

**Failure logs** 
-Cut and paste the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by Anassatti** [comment]
Host Environment

OS: [Windows 11 Pro]
Compiler: revision
To Reproduce
Steps to reproduce the behavior:
.\vcpkg install darknet[opencv-base,cuda,cudnn]:x64-windows

Failure logs
Building package cudnn[core]:x64-windows...
-- Found CUDA V11.5.119
-- CUDNN_INCLUDE_DIR: CUDNN_INCLUDE_DIR-NOTFOUND
-- CUDNN_LIBRARY: CUDNN_LIBRARY-NOTFOUND
CMake Error at ports/cudnn/portfile.cmake:69 (message):
  Please download CUDNN from official sources (such as
  https://developer.nvidia.com/rdp/cudnn-download ) and extract the zip into
  your CUDA_TOOLKIT_ROOT (C:/Program Files/NVIDIA GPU Computing
  Toolkit/CUDA/v11.5).  (For example: tar.exe -xvf
  cudnn-11.2-windows-x64-v8.1.1.33.zip --strip 1 --directory "C:/Program
  Files/NVIDIA GPU Computing Toolkit/CUDA/v11.5"
Call Stack (most recent call first):
  scripts/ports.cmake:142 (include)
Error: Building package cudnn:x64-windows failed with: BUILD_FAILED.

Additional context
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by dg0yt** [comment]
> Please download CUDNN from official sources (such as
https://developer.nvidia.com/rdp/cudnn-download ) and extract the zip into
your CUDA_TOOLKIT_ROOT (C:/Program Files/NVIDIA GPU Computing
Toolkit/CUDA/v11.5). (For example: tar.exe -xvf
cudnn-11.2-windows-x64-v8.1.1.33.zip --strip 1 --directory "C:/Program
Files/NVIDIA GPU Computing Toolkit/CUDA/v11.5"

**Comment by LilyWangLL** [comment]
@Anassatti Does this issue resolve?

**Comment by Anassatti** [comment]
Yes, thank you.

**Comment by LilyWangLL** [comment]
This issue has been resolved, I am closing this issue for now.

**Comment by Sakethgupta-aqua** [comment]
can u plz help me @LilyWangLL i am also facing the same issue as mentioned above but i have installed CUDNN also form nividia official site

**Comment by LilyWangLL** [comment]
> can u plz help me @LilyWangLL i am also facing the same issue as mentioned above but i have installed CUDNN also form nividia official site

Please provide the error log.

**Comment by Sakethgupta-aqua** [comment]
hello thanks for your reply but i have rectified my issue
But i am facing some other issue

ERROR: CUDA Error: no kernel image is available for execution on the device
