### ISSUE TITLE
[vcpkg_install_qmake] broken.

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#22011]
The script is simply broken with the current design. 
`vcpkg_build_qmake` should call the `install` target.
The problem: the current installation points into `/installed/` instead of `/packages/` after makefile generation (qmake_all or `vcpkg_configure_qmake`). 
Solution: do the same as qt5-base does for all its submodules.

**Comment by Neumann-A** [comment]
The problem reason why this is implemented in this way is because install rules in qmake are kind of funky. 
Projects needs to setup:
```
# Install directives
win32 {
    dlltarget.path = $$[QT_INSTALL_BINS]
    INSTALLS += dlltarget
}
target.path    = $$[QT_INSTALL_LIBS]
!static: target.CONFIG = no_dll
INSTALLS     += target 
```
in addition to fixing the makefiles to not directly install into `/installed/`

**Comment by JackBoosY** [comment]
Can you make a PR to fix that?
If all the qmake configuration need to be patched, we can do that in `vcpkg_configure_qmake` internally.

**Comment by Neumann-A** [comment]
I don't really care about qt5 so I won't fix it. You can copy most (all?) of the stuff from vcpkg-qmake. 

> qmake configuration need to be patched

That is not so easy since not all *.pro files need patching. It is basically the same error as if in cmake the proper `install()` command is missing.
