### ISSUE TITLE
Build tesseract:x86-windows-static failed

### ISSUE THREAD

**Issue by gzf** [Microsoft/vcpkg#2201]
The build process was blocked by one of its dependency, leptonica. Here are the error messages:

Error: Building package leptonica:x86-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: leptonica:x86-windows-static
  Vcpkg version: 0.0.97-2017-11-14-2b7cd655c8d52ce40453497ecc06c81dc2977aab

install-x86-windows-static-rel-out.log:

   Creating library src\leptonica-1.74.4.lib and object src\leptonica-1.74.4.exp
tiff.lib(tif_lzma.c.obj) : error LNK2019: unresolved external symbol _lzma_code referenced in function _LZMADecode
tiff.lib(tif_lzma.c.obj) : error LNK2019: unresolved external symbol _lzma_end referenced in function _LZMACleanup
tiff.lib(tif_lzma.c.obj) : error LNK2019: unresolved external symbol _lzma_memusage referenced in function _LZMADecode
tiff.lib(tif_lzma.c.obj) : error LNK2019: unresolved external symbol _lzma_lzma_preset referenced in function _LZMAVSetField
tiff.lib(tif_lzma.c.obj) : error LNK2019: unresolved external symbol _lzma_stream_encoder referenced in function _LZMAPreEncode
tiff.lib(tif_lzma.c.obj) : error LNK2019: unresolved external symbol _lzma_stream_decoder referenced in function _LZMADecode
bin\leptonica-1.74.4.dll : fatal error LNK1120: 6 unresolved externals
LINK failed. with 1120
ninja: build stopped: subcommand failed.

**Comment by ras0219-msft** [comment]
This should be fixed in the latest master; thank you for reporting this issue!
