### ISSUE TITLE
Error: Building package eigen3:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by Birght-lab** [microsoft/vcpkg#22030]
**Host Environment**
- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**
`./vcpkg install xxxx`

**Failure logs** 
-Cut and paste the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by JackBoosY** [comment]
Please provide the output in your console and the failure log in the contents first.

Thanks.

**Comment by JonLiu1993** [comment]
Thanks for posting this issue. Please reopen this issue if it still be a problem for you.
