### ISSUE TITLE
vcpkg does not ignore $-prefixed keys in features object

### ISSUE THREAD

**Issue by horenmar** [microsoft/vcpkg#22037]
**Describe the bug**
I tried to introduce comment inside of the "features" field of package's `vcpkg.json`. This causes error:

```
Errors occurred while parsing C:\ubuntu\vcpkg\../vcpkg-registry/overlay-ports\repro\vcpkg.json
    $.features (a set of features): unexpected field '$possible-features': must be lowercase alphanumeric+hyphens and not reserved
Error: Failed to load port repro from C:\ubuntu\vcpkg\../vcpkg-registry/overlay-ports
```

**Environment**
- vcpkg: Vcpkg package management program version 2021-12-09-724cea8b33cbf06c645f5095fa29773697da9761

**To Reproduce**
Create package `repro` with this `vcpkg.json`:
```json
{
  "$schema": "https://raw.githubusercontent.com/microsoft/vcpkg/master/scripts/vcpkg.schema.json",
  "name": "repro",
  "version": "0.0.0",
  "features": {
    "$possible-features": "Some comment or something",
    "fake": {
      "description": "fake feature"
    }
  }
}
```

2. ```vcpkg install repro --overlay-ports={path to port repro}```

**Expected behavior**
$-prefixed field is ignored as it would be elsewhere.

**Comment by JackBoosY** [comment]
cc @strega-nil-ms

**Comment by strega-nil-ms** [comment]
Needs a release.
