### ISSUE TITLE
[New Port Request] gnugraph

### ISSUE THREAD

**Issue by christospliakos** [microsoft/vcpkg#22033]
Library name: gnugraph

Library description: A header only interface to gnuplot.exe, to plot 2D and 3D graphs from C++ code.

Source repository URL: https://github.com/AnyarInc/gnugraph

Project homepage (if different from the source repository): N/A

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
