### ISSUE TITLE
New mirrors for QT5

### ISSUE THREAD

**Issue by gb96** [microsoft/vcpkg#2203]
Thanks to a limitation of my corporate web proxy, I can generally only download binaries via https (binary download requests via http are mostly blocked).

Consequently I would like to suggest https URLS as "mirrors" for any existing vcpkg packages that only have http URLS.

For example, add:
https://ftp.yz.yamagata-u.ac.jp/pub/qtproject/archive/qt/5.8/5.8.0/single/qt-everywhere-opensource-src-5.8.0.7z

as a mirror for:
http://download.qt.io/official_releases/qt/5.8/5.8.0/single/qt-everywhere-opensource-src-5.8.0.7z

If you think this is acceptable I can locate a number of such mirrors, add these URLS to the ends of the URLS  lists in the appropriate cmake scripts, and create a single PR.

Or if you prefer I can create a separate PR for each case.

Note I do not intend to find mirrors for all http URLS in the vcpkg ecosystem, only the ones I encounter on my current project.

**Comment by ras0219-msft** [comment]
This sounds very reasonable and we would be happy to accept such PRs! Since every file is hash checked, there is no risk of getting the wrong sources 😊.

**Comment by gb96** [comment]
My employer has poured cold water on me signing the MFST CLA in the near future, however I hope I might be able to do so from home and contribute to this project in my free time.  Unfortunately I don't have much free time until xmas break.

**Comment by JackBoosY** [comment]
Related: #8696.

**Comment by heydojo** [comment]
Here is something relevant that NixOs does in this area:
https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/fetchurl/mirrors.nix
They use a mirror list as part of a function (which they use liberally in their package files, similar to vcpkg's ports) and fall back onto a mirror, a release archive or a git pull if the source is unavailable from the address which has the highest priority.

Some of the first tries are **https** addresses and then the first fall back option is commonly a **http** address.

**Comment by JackBoosY** [comment]
@heydojo That's very useful.

**Comment by MonicaLiu0311** [comment]
Fixed by #19843.
