### ISSUE TITLE
[portfile helpers] Undeprecate vcpkg_apply_patches

### ISSUE THREAD

**Issue by horenmar** [microsoft/vcpkg#22042]
I understand that using `vcpkg_from_git(hub)` is preferred, but I have at least two private packages for which I cannot use it for different reasons*, and instead I have to call into `git` manually like this

```cmake
if (NOT EXISTS "${SOURCE_PATH}")
  vcpkg_execute_required_process(
    COMMAND ${GIT} clone https://github.com/Pexeso/pexlib.git ${CHECKOUT_DIR}
    WORKING_DIRECTORY ${CURRENT_BUILDTREES_DIR}
    LOGNAME git-1-clone-${TARGET_TRIPLET}
  )
endif()
``` 

This then means that if I also need to patch the checkout, I am forced to use `vcpkg_apply_patches`, and this adds a multiline deprecation warning to the build output.

\* For the record, the reason is that for one port I need submodules and for the other one using `vcpkg_from_git` fails at dealing with git_lfs, while calling into `git` successfully checks out the repo.

**Proposed solution**
Remove deprecation warning from the actual helper. Reword the documentation to strongly suggest use of `PATCHES` argument where possible. Have the quick check PR bot also check against `vcpkg_apply_patches` and make it a warning/error there.

Alternative solution would be to add a "YES_I_NEED_TO_USE_THIS` argument to `vcpkg_apply_patches` to silence the warning 😃

**Comment by JackBoosY** [comment]
I think we should add new features to vcpkg_from_git(hub) to support the features you need instead of re-enable `vcpkg_apply_patches`.
Can you please provide a repro step?

Thanks.

**Comment by JonLiu1993** [comment]
@horenmar ,Could you please provide a repro step?

**Comment by JackBoosY** [comment]
@horenmar For submodules, it should also be pre-downloaded in vcpkg using `vcpkg_from_git*` and rename the folder to _SOURCE_PATH_. If the patch is for a submodule, the patch should be added to the submodule's `vcpkg_from_git*` or `vcpkg_extract_source_archive_ex`.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
