### ISSUE TITLE
[gmp] Build error

### ISSUE THREAD

**Issue by Emmetv15** [microsoft/vcpkg#22044]
**Host Environment**
- OS: Windows
- Compiler: revision

**To Reproduce**
`vcpkg install gmp`

**Failure logs** 

Starting package 3/3: gmp:x86-windows
Building package gmp[core]:x86-windows...
-- Downloading https://github.com/ShiftMediaProject/gmp/archive/0018c44e8dfcc3b64b43e0aea4b3f419f0b65fd0.tar.gz -> ShiftMediaProject-gmp-0018c44e8dfcc3b64b43e0aea4b3f419f0b65fd0.tar.gz...
-- Extracting source C:/vcpkg/downloads/ShiftMediaProject-gmp-0018c44e8dfcc3b64b43e0aea4b3f419f0b65fd0.tar.gz
-- Applying patch vs.build.patch
-- Applying patch runtime.patch
-- Applying patch adddef.patch
-- Using source at C:/vcpkg/buildtrees/gmp/src/19f0b65fd0-9b395bc164.clean
-- Building SMP/libgmp.sln for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: msbuild C:/vcpkg/buildtrees/gmp/x86-windows-rel/19f0b65fd0-9b395bc164.clean/SMP/libgmp.sln /p:Configuration=ReleaseDLL /p:YasmPath=C:\\vcpkg\\installed\\x64-windows\\share\\yasm-tool\\..\\..\\tools\\yasm-tool\\yasm.exe /t:Rebuild /p:Platform=x86 /p:PlatformToolset=v143 /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /p:WindowsTargetPlatformVersion=10.0.19041.0 /p:VcpkgTriplet=x86-windows /p:VcpkgInstalledDir=C:/vcpkg/installed /p:VcpkgManifestInstall=false /p:UseMultiToolTask=true /p:MultiProcMaxCount=5 /p:EnforceProcessCountAcrossBuilds=true /m:5 /p:ForceImportBeforeCppTargets=C:/vcpkg/scripts/buildsystems/msbuild/vcpkg.targets /p:VcpkgApplocalDeps=false
    Working Directory: C:/vcpkg/buildtrees/gmp/x86-windows-rel/19f0b65fd0-9b395bc164.clean
    Error code: 1
    See logs for more information:
      C:\vcpkg\buildtrees\gmp\build-x86-windows-rel-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_msbuild.cmake:172 (vcpkg_execute_required_process)
  ports/gmp/portfile.cmake:51 (vcpkg_install_msbuild)
  scripts/ports.cmake:142 (include)

**Additional context**
I'm new

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Please provide the error log file: `C:\vcpkg\buildtrees\gmp\build-x86-windows-rel-out.log`

**Comment by Emmetv15** [comment]
[build-x86-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/7728951/build-x86-windows-rel-out.log)

**Comment by Emmetv15** [comment]
[build-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/7728971/build-x64-windows-rel-out.log)
for x64 aswell, same thing

**Comment by Emmetv15** [comment]
![image](https://user-images.githubusercontent.com/36600912/146413411-3ec260b2-1f62-453d-b480-fa435a79ecaa.png)
![image](https://user-images.githubusercontent.com/36600912/146414773-17ff3527-cbb3-4e0d-a89f-699a91b5efd6.png)

**Comment by Emmetv15** [comment]
![image](https://user-images.githubusercontent.com/36600912/146414897-06ecc877-cfc4-4785-98ba-13db98c3ac19.png)

**Comment by Emmetv15** [comment]
i fixed it by installing the windows 10 SDK from vs2022 and uninstalling from vs build tools 2019

**Comment by LilyWangLL** [comment]
This issue has been resolved, so I am closing this issue for now.
