### ISSUE TITLE
How do I use vcpkg with GNU Makefiles

### ISSUE THREAD

**Issue by Hawk2811** [microsoft/vcpkg#22043]
There is no guide to using vcpkg with Makefiles only with CMake and Visual Studio but I wanted to use vcpkg with VSCode and GNU Makefile or NMake

**Comment by autoantwort** [comment]
I think you add the include folder to the include path and link the libs manually. I think nearly is using plain makefiles so that it is unlikely that there will be a guide, but you can create a PR that

**Comment by Hawk2811** [comment]
> I think you add the include folder to the include path and link the libs manually. I think nearly is using plain makefiles so that it is unlikely that there will be a guide, but you can create a PR that

How?

**Comment by autoantwort** [comment]
How do you normally add include paths? If you don't know that, I really suggest using cmake.

**Comment by Hawk2811** [comment]
> How do you normally add include paths? If you don't know that, I really suggest using cmake. 
> 

I fumble all over using cmake because when I put the default compiler like LLVM-mingw it uses MSVC anyway

**Comment by autoantwort** [comment]
Normally you simply pass the compiler to cmake in the configure step `-DCMAKE_C_COMPILER=C:/.../clang -DCMAKE_CXX_COMPILER=C:/.../clang++`

**Comment by Hawk2811** [comment]
> Normally you simply pass the compiler to cmake in the configure step `-DCMAKE_C_COMPILER=C:/.../clang -DCMAKE_CXX_COMPILER=C:/.../clang++`

ok I'll try here if there's any problem I'll send it here

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
