### ISSUE TITLE
VS2017 CMake Boost Problems

### ISSUE THREAD

**Issue by Pantau123** [microsoft/vcpkg#2205]
Hi,
I want to build a CMake Solution which links to cpprestsdk in VS2017.
When I want to Compile I receive the following message: 
Warning		CMake Warning at C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.9/Modules/FindBoost.cmake:769 (message):
  Imported targets not available for Boost version 106501		C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.9/Modules/FindBoost.cmake	769	

Can anybody help me?

Best regards

**Comment by ras0219-msft** [comment]
Hi @Pantau123,

This message is unfortunately normal; when Boost updates, CMake is no longer able to generate the targets (Boost::boost). However, the boost library variables will continue to function correctly: `${Boost_LIBRARIES}`!

This is just a warning, so it can be safely ignored in this case.

**Comment by Pantau123** [comment]
But Visual Studio doesn't ignore it. It prohibite to Compile.

**Comment by PhoebeHui** [comment]
@Pantau123, does this still be a problem for you?

**Comment by PhoebeHui** [comment]
Verified this issue with VS2017 + cmake 3.12, it's not a problem now, it compiles successfully.
