### ISSUE TITLE
[boost-build] Error: Building package boost-build:x86-windows-static-xp failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by bertox94** [microsoft/vcpkg#22052]
**Host Environment**
- OS: Windows 10
- Compiler: 
       clang version 12.0.0
       Target: i686-pc-windows-msvc
       Thread model: posix
       InstalledDir: C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\Llvm\bin

**To Reproduce**
`.\vcpkg.exe install boost-build:x86-windows-static-xp`

**Failure logs** 
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
    Command failed: C:/Users/alt/vcpkg/packages/boost-build_x86-windows-static-xp/tools/boost-build/bootstrap.bat msvc
    Working Directory: C:/Users/alt/vcpkg/packages/boost-build_x86-windows-static-xp/tools/boost-build
    Error code: 1
    See logs for more information:
      C:\Users\alt\vcpkg\buildtrees\boost-build\bootstrap-x86-windows-static-xp-out.log
      C:\Users\alt\vcpkg\buildtrees\boost-build\bootstrap-x86-windows-static-xp-err.log

Call Stack (most recent call first):
  ports/boost-build/portfile.cmake:58 (vcpkg_execute_required_process)
  scripts/ports.cmake:144 (include)

Error: Building package boost-build:x86-windows-static-xp failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-build:x86-windows-static-xp
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

-Please attach any additional failure logs mentioned in the console output.
[bootstrap-x86-windows-static-xp-out.log](https://github.com/microsoft/vcpkg/files/7728661/bootstrap-x86-windows-static-xp-out.log)
[bootstrap-x86-windows-static-xp-err.log](https://github.com/microsoft/vcpkg/files/7728662/bootstrap-x86-windows-static-xp-err.log)

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.
When I try to run the command ([bootstrap-x86-windows-static-xp-out.log](https://github.com/microsoft/vcpkg/files/7728661/bootstrap-x86-windows-static-xp-out.log) at line 7) from the cmd prompt it executes successfully and it builds the b2.exe.
Here the triplet file I'm using: [x86-windows-static-xp.txt](https://github.com/microsoft/vcpkg/files/7728695/x86-windows-static-xp.txt)
(toolchain file unchanged)

**Comment by PhoebeHui** [comment]
Failures;
```
C:\Users\alt\vcpkg\packages\boost-build_x86-windows-static-xp\tools\boost-build\src\engine>clang-cl /nologo /MP /MT /TP /Feb2 /wd4996 /O2 /GL   -DNDEBUG  builtins.cpp class.cpp command.cpp compile.cpp constants.cpp cwd.cpp debug.cpp debugger.cpp execcmd.cpp execnt.cpp filent.cpp filesys.cpp frames.cpp function.cpp glob.cpp hash.cpp hcache.cpp hdrmacro.cpp headers.cpp jam.cpp jamgram.cpp lists.cpp make.cpp make1.cpp md5.cpp mem.cpp modules.cpp native.cpp object.cpp option.cpp output.cpp parse.cpp pathnt.cpp pathsys.cpp regexp.cpp rules.cpp scan.cpp search.cpp jam_strings.cpp startup.cpp subst.cpp sysinfo.cpp timestamp.cpp variable.cpp w32_getreg.cpp modules/order.cpp modules/path.cpp modules/property-set.cpp modules/regex.cpp modules/sequence.cpp modules/set.cpp /link kernel32.lib advapi32.lib user32.lib 
libcmt.lib(chkstk.obj) : fatal error LNK1112: module machine type 'x86' conflicts with target machine type 'x64'
```

**Comment by bertox94** [comment]
Hello, anybody here?

**Comment by bertox94** [comment]
Hi,
I solved this by adding the following triplets and toolchain files:
[triplets.zip](https://github.com/microsoft/vcpkg/files/7750715/triplets.zip)
But I have a new issue on boost-exception.
Opening new issue...
