### ISSUE TITLE
[poco：mysql] Build error

### ISSUE THREAD

**Issue by cloudsnake** [microsoft/vcpkg#22057]
**Host Environment**
- OS: Windows
- Compiler: VS 2022

**To Reproduce**
./vcpkg install poco[mysql]:x64-windows-static

**Failure logs** 
-Cut and paste the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

**Additional context**
-- Using source at D:/dev/vcpkg/buildtrees/poco/src/f788bc88ea-d4759b3a2b.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows-static
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: ninja -v
    Working Directory: D:/dev/vcpkg/buildtrees/poco/x64-windows-static-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\dev\vcpkg\buildtrees\poco\config-x64-windows-static-out.log
[Uploading config-x64-windows-static-out.log…]()

**Comment by cloudsnake** [comment]
thanks!
libmysql is ok!
but
./vcpkg install poco[mysql]:x64-windows-static
no error,no build PocoDataMysqlmt.lib file!

**Comment by LilyWangLL** [comment]
Waitting for PR #22062 merged, this issue will be closed.
