### ISSUE TITLE
[7-Zip] update to 21.06

### ISSUE THREAD

**Issue by Tarek-Hasan** [microsoft/vcpkg#22063]
Library name: 7-Zip

New version number: 21.06

Other information that may be useful (release notes, etc...)
Released on 24 Nov 2021
https://www.7-zip.org/download.html
mirror: https://sourceforge.net/projects/sevenzip/files/7-Zip/21.06/

**Comment by xavier2k6** [comment]
Duplicate of #21567

**Comment by Tarek-Hasan** [comment]
Feel free to delete this issue.

**Comment by PhoebeHui** [comment]
Closing in favor of https://github.com/microsoft/vcpkg/issues/21567.
