### ISSUE TITLE
[sqlite3] Build error

### ISSUE THREAD

**Issue by prizrak56** [microsoft/vcpkg#22066]
**Host Environment**
- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**
`./vcpkg install xxxx`

**Failure logs** 
-Cut and paste the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by prizrak56** [comment]
Error: Building package sqlite3:x64-windows failed with: BUILD_FAILED

**Comment by prizrak56** [comment]
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+sqlite3
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[sqlite3]+Build+error
including:
  package: sqlite3[core]:x64-windows -> 3.37.0
    vcpkg-tool version: 2021-12-09-724cea8b33cbf06c645f5095fa29773697da9761
    vcpkg-scripts version: unknown

**Comment by JonLiu1993** [comment]
@prizrak56 ,Thanks for posting this issue,Cou you please provide the detail error log?

**Comment by JonLiu1993** [comment]
@prizrak56 ,Cou you please provide the detail error log?

**Comment by JonLiu1993** [comment]
Thanks for posting this issue. Please reopen this issue if it still be a problem for you.
