### ISSUE TITLE
Is it possible to generate a Visual Studio solution for a package ?

### ISSUE THREAD

**Issue by aybe** [Microsoft/vcpkg#2207]
I would like to be able to browse the sources of ```aubio``` package from within Visual Studio but I can't find any `.sln` file like there is on ```libflac``` for instance.

Is this something that vcpkg can do ? If yes, then could you provide some guidance on how to do that ?

Thank you !

**Comment by ras0219-msft** [comment]
While we don't support directly generating a VS solution from a package, you can definitely use VS2017's "Open Folder" mode and browse the sources directly!

The sources will be available in `buildtrees\aubio\src\<version>`.

**Comment by aybe** [comment]
Alright, thank you.
