### ISSUE TITLE
[tensorflow] build failure

### ISSUE THREAD

**Issue by gemsofgem** [microsoft/vcpkg#22083]
**Host Environment**
- OS: [e.g. Windows/Linux etc...] Windows 11 Pro 64 bit
- Compiler: revision MS VS2022 C++

**To Reproduce**
./vcpkg install tensorflow:x64-windows

**Failure logs** 
Error: Building package tensorflow:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  package: tensorflow[core]:x64-windows -> 2.6.0
  vcpkg version: a2fcb0374 2021-11-23 (3 weeks ago)
  vcpkg-tool version: 2021-11-15-ec76affcc987efbf172b7da0b05df711b48fa535

Additionally, attach any relevant sections from the log files above.

**Additional context**
When I try to install tensorflow for x64-windows using MS VS2022 C++ complier, It halts  and exits with the failure given above.

**Comment by JackBoosY** [comment]
Can you please provide all logs in _VCPKG_ROOT/buildtrees/tensorflow_ first?

Thanks.

**Comment by gemsofgem** [comment]
Thanks for your interest in the issue. Sorry, but I don't know how to attach a file in this text box. I had to add the long text below in the "build-x64-windows-dbg-err.log" file.

Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=0 --terminal_columns=80
INFO: Reading rc options for 'build' from z:\swlibrary\vcpkg\buildtrees\tensorflow\x64-windows-dbg\.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Options provided by the client:
  'build' options: --python_path=Z:/SWLibrary/vcpkg/downloads/tools/msys2/5ac3933426d8437e/mingw64/bin/python.exe
INFO: Reading rc options for 'build' from z:\swlibrary\vcpkg\buildtrees\tensorflow\x64-windows-dbg\.bazelrc:
  'build' options: --define framework_shared_object=true --java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --host_java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true
INFO: Reading rc options for 'build' from z:\swlibrary\vcpkg\buildtrees\tensorflow\x64-windows-dbg\.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=Z:/SWLibrary/vcpkg/downloads/tools/msys2/5ac3933426d8437e/mingw64/bin/python3.exe --action_env PYTHON_LIB_PATH=Z:/SWLibrary/vcpkg/downloads/tools/msys2/5ac3933426d8437e/mingw64/lib/python3.8/site-packages --python_path=Z:/SWLibrary/vcpkg/downloads/tools/msys2/5ac3933426d8437e/mingw64/bin/python3.exe --define=with_xla_support=false --copt=/d2ReducedOptimizeHugeFunctions --host_copt=/d2ReducedOptimizeHugeFunctions --define=override_eigen_strong_inline=true
INFO: Found applicable config definition build:short_logs in file z:\swlibrary\vcpkg\buildtrees\tensorflow\x64-windows-dbg\.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file z:\swlibrary\vcpkg\buildtrees\tensorflow\x64-windows-dbg\.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:windows in file z:\swlibrary\vcpkg\buildtrees\tensorflow\x64-windows-dbg\.bazelrc: --copt=/W0 --copt=/D_USE_MATH_DEFINES --host_copt=/D_USE_MATH_DEFINES --cxxopt=/std:c++14 --host_cxxopt=/std:c++14 --config=monolithic --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --copt=/experimental:preprocessor --host_copt=/experimental:preprocessor --linkopt=/DEBUG --host_linkopt=/DEBUG --linkopt=/OPT:REF --host_linkopt=/OPT:REF --linkopt=/OPT:ICF --host_linkopt=/OPT:ICF --verbose_failures --distinct_host_configuration=false
INFO: Found applicable config definition build:monolithic in file z:\swlibrary\vcpkg\buildtrees\tensorflow\x64-windows-dbg\.bazelrc: --define framework_shared_object=false
Loading: 
Loading: 0 packages loaded
DEBUG: Z:/swlibrary/vcpkg/buildtrees/tensorflow/.bzl/3bqwlsea/external/tf_runtime/third_party/cuda/dependencies.bzl:51:10: The following command will download NVIDIA proprietary software. By using the software you agree to comply with the terms of the license agreement that accompanies the software. If you do not agree to the terms of the license agreement, do not use the software.
Loading: 0 packages loaded
Analyzing: 2 targets (1 packages loaded, 0 targets configured)
Analyzing: 2 targets (24 packages loaded, 32 targets configured)
INFO: Repository local_config_def_file_filter instantiated at:
  Z:/swlibrary/vcpkg/buildtrees/tensorflow/x64-windows-dbg/WORKSPACE:15:14: in <toplevel>
  Z:/swlibrary/vcpkg/buildtrees/tensorflow/x64-windows-dbg/tensorflow/workspace2.bzl:1088:19: in workspace
  Z:/swlibrary/vcpkg/buildtrees/tensorflow/x64-windows-dbg/tensorflow/workspace2.bzl:101:30: in _tf_toolchains
Repository rule def_file_filter_configure defined at:
  Z:/swlibrary/vcpkg/buildtrees/tensorflow/x64-windows-dbg/tensorflow/tools/def_file_filter/def_file_filter_configure.bzl:55:44: in <toplevel>
Analyzing: 2 targets (81 packages loaded, 1879 targets configured)
ERROR: An error occurred during the fetch of repository 'local_config_def_file_filter':
   Traceback (most recent call last):
	File "Z:/swlibrary/vcpkg/buildtrees/tensorflow/x64-windows-dbg/tensorflow/tools/def_file_filter/def_file_filter_configure.bzl", line 37, column 28, in _def_file_filter_configure_impl
		auto_configure_fail("Couldn't find undname.exe under %s, please check your VC installation and set BAZEL_VC environment variable correctly." % vc_path)
	File "Z:/swlibrary/vcpkg/buildtrees/tensorflow/.bzl/3bqwlsea/external/bazel_tools/tools/cpp/lib_cc_configure.bzl", line 112, column 9, in auto_configure_fail
		fail("\n%sAuto-Configuration Error:%s %s\n" % (red, no_color, msg))
Error in fail: 
Auto-Configuration Error: Couldn't find undname.exe under C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC, please check your VC installation and set BAZEL_VC environment variable correctly.
ERROR: Error fetching repository: Traceback (most recent call last):
	File "Z:/swlibrary/vcpkg/buildtrees/tensorflow/x64-windows-dbg/tensorflow/tools/def_file_filter/def_file_filter_configure.bzl", line 37, column 28, in _def_file_filter_configure_impl
		auto_configure_fail("Couldn't find undname.exe under %s, please check your VC installation and set BAZEL_VC environment variable correctly." % vc_path)
	File "Z:/swlibrary/vcpkg/buildtrees/tensorflow/.bzl/3bqwlsea/external/bazel_tools/tools/cpp/lib_cc_configure.bzl", line 112, column 9, in auto_configure_fail
		fail("\n%sAuto-Configuration Error:%s %s\n" % (red, no_color, msg))
Error in fail: 
Auto-Configuration Error: Couldn't find undname.exe under C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC, please check your VC installation and set BAZEL_VC environment variable correctly.
INFO: Repository com_googlesource_code_re2 instantiated at:
  Z:/swlibrary/vcpkg/buildtrees/tensorflow/x64-windows-dbg/WORKSPACE:15:14: in <toplevel>
  Z:/swlibrary/vcpkg/buildtrees/tensorflow/x64-windows-dbg/tensorflow/workspace2.bzl:1098:21: in workspace
  Z:/swlibrary/vcpkg/buildtrees/tensorflow/x64-windows-dbg/tensorflow/workspace2.bzl:273:20: in _tf_repositories
  Z:/swlibrary/vcpkg/buildtrees/tensorflow/x64-windows-dbg/third_party/repo.bzl:113:21: in tf_http_archive
Repository rule _tf_http_archive defined at:
  Z:/swlibrary/vcpkg/buildtrees/tensorflow/x64-windows-dbg/third_party/repo.bzl:66:35: in <toplevel>
INFO: Repository eigen_archive instantiated at:
  Z:/swlibrary/vcpkg/buildtrees/tensorflow/x64-windows-dbg/WORKSPACE:15:14: in <toplevel>
  Z:/swlibrary/vcpkg/buildtrees/tensorflow/x64-windows-dbg/tensorflow/workspace2.bzl:1091:28: in workspace
  Z:/swlibrary/vcpkg/buildtrees/tensorflow/x64-windows-dbg/tensorflow/workspace2.bzl:61:11: in _initialize_third_party
  Z:/swlibrary/vcpkg/buildtrees/tensorflow/x64-windows-dbg/third_party/eigen3/workspace.bzl:12:20: in repo
  Z:/swlibrary/vcpkg/buildtrees/tensorflow/x64-windows-dbg/third_party/repo.bzl:113:21: in tf_http_archive
Repository rule _tf_http_archive defined at:
  Z:/swlibrary/vcpkg/buildtrees/tensorflow/x64-windows-dbg/third_party/repo.bzl:66:35: in <toplevel>
INFO: Repository rules_proto instantiated at:
  Z:/swlibrary/vcpkg/buildtrees/tensorflow/x64-windows-dbg/WORKSPACE:23:14: in <toplevel>
  Z:/swlibrary/vcpkg/buildtrees/tensorflow/x64-windows-dbg/tensorflow/workspace0.bzl:120:20: in workspace
  Z:/swlibrary/vcpkg/buildtrees/tensorflow/.bzl/3bqwlsea/external/com_github_grpc_grpc/bazel/grpc_extra_deps.bzl:29:18: in grpc_extra_deps
  Z:/swlibrary/vcpkg/buildtrees/tensorflow/.bzl/3bqwlsea/external/com_google_protobuf/protobuf_deps.bzl:42:21: in protobuf_deps
Repository rule http_archive defined at:
  Z:/swlibrary/vcpkg/buildtrees/tensorflow/.bzl/3bqwlsea/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: Z:/swlibrary/vcpkg/buildtrees/tensorflow/x64-windows-dbg/tensorflow/BUILD:1091:8: //tensorflow:tensorflow_filtered_def_file depends on @local_config_def_file_filter//:def_file_filter in repository @local_config_def_file_filter which failed to fetch. no such package '@local_config_def_file_filter//': 
Auto-Configuration Error: Couldn't find undname.exe under C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC, please check your VC installation and set BAZEL_VC environment variable correctly.
ERROR: Analysis of target '//tensorflow:tensorflow.dll' failed; build aborted: Analysis failed
INFO: Elapsed time: 9.430s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (83 packages loaded, 1880 targets configured)
FAILED: Build did NOT complete successfully (83 packages loaded, 1880 targets configured)

**Comment by JackBoosY** [comment]
```
uto-Configuration Error: Couldn't find undname.exe under C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC, please check your VC installation and set BAZEL_VC environment variable correctly.
```
Plesa track https://github.com/microsoft/vcpkg/issues/21246 instead.

**Comment by gemsofgem** [comment]
Thanks for your reply.
However, I cannot figure out what the solution is proposed to fix the issue. Is it as below?

Update TensorFlow to 2.7.

Update Bazel to 4.2.2 (latest 4.x), hopefully fixing Windows 11 issues like #21246.

If this is the solution proposed, I don't know how to upgrade tensorflow in vcpkg.  As far s I am aware, it is done automatically done by the command

vcpkg install tensorflow:x64-windows

**Comment by JackBoosY** [comment]
I'm not sure whether tf and bazel supports Visual Studio 2022 now.

**Comment by OgreTransporter** [comment]
I have tried many different things to build TF directly (without vcpkg) with VS2022, but have had no success so far. VS2019 is working well.
