### ISSUE TITLE
vcpkg tool syntax for `,` operator

### ISSUE THREAD

**Issue by dg0yt** [microsoft/vcpkg#22080]
The `supports` field in manifests has a `,` operator. I would expect to put this operator directly after the preceeding expression, e.g.
~~~
!windows, mingw
~~~

However, vcpkg tool 2021-12-09-724cea8b33cbf06c645f5095fa29773697da9761 expects a space before (and after) the comma:
~~~
!windows , mingw
~~~

I would prefer if the tool accepted (`x-add-version`) and write (`format-manifest`) the variant *without* leading space.

**Comment by JackBoosY** [comment]
Although the inclusion of spaces before the comma does not affect the parsing results, it is obvious that this approach is not a strict standard.

**Comment by strega-nil-ms** [comment]
Needs a merge to close.

**Comment by BillyONeal** [comment]
Fixed by https://github.com/microsoft/vcpkg/pull/22629
