### ISSUE TITLE
Port Request: Visual Leak Detector (VLD)

### ISSUE THREAD

**Issue by ijesonchen** [microsoft/vcpkg#2209]
https://github.com/KindDragon/vld
https://kinddragon.github.io/vld/
Visual C++ provides built-in memory leak detection, but its capabilities are minimal at best. This memory leak detector was created as a free alternative to the built-in memory leak detector provided with Visual C++. Here are some of Visual Leak Detector’s features, none of which exist in the built-in detector:

Provides a complete stack trace for each leaked block, including source file and line number information when available.
Detects most, if not all, types of in-process memory leaks including COM-based leaks, and pure Win32 heap-based leaks.
Selected modules (DLLs or even the main EXE) can be excluded from leak detection.
Provides complete data dumps (in hex and ASCII) of leaked blocks.
Customizable memory leak report: can be saved to a file or sent to the debugger and can include a variable level of detail.

Thanks.

**Comment by KindDragon** [comment]
I will think about it

**Comment by JackBoosY** [comment]
We can’t reopen this issue until a PR is opened, unfortunately, consider making a pull request!
