### ISSUE TITLE
[LuaBridge] update to 3.x

### ISSUE THREAD

**Issue by qisumi** [microsoft/vcpkg#22097]
Library name: LuaBridge

New version number: 3.x

LuaBridge 3.x is also a header-only library, which can be easily introduced into vcpkg.
https://github.com/kunitoki/LuaBridge3

**Comment by JonLiu1993** [comment]
@qisumi , 'https://github.com/kunitoki/LuaBridge3' This is not the official repo and we shouldn't accept this. 
Vcpkg use the official  repo https://github.com/vinniefalco/LuaBridge. which doesn't provide 3.0 version
