### ISSUE TITLE
[New Port Request] <coz>

### ISSUE THREAD

**Issue by hudengjunai** [microsoft/vcpkg#22094]
Library name:coz

Library description:causual profiler

Source repository URL: https://github.com/plasma-umass/coz

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
