### ISSUE TITLE
Got error [find_file_recursively_up(E:\TOOLS\vcpkg\vcpkg.exe, .vcpkg-root): �������� ]while running vcpkg.exe -search

### ISSUE THREAD

**Issue by DeanXi** [microsoft/vcpkg#22102]
First time to use vcpkg,  after executing vcpkg.exe search --debug I got the output：

[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
find_file_recursively_up(E:\TOOLS\vcpkg\vcpkg.exe, .vcpkg-root): ��������
[DEBUG] D:\a_work\1\s\src\vcpkg\vcpkgpaths.cpp(400)
[DEBUG] Time in subprocesses: 0 us
[DEBUG] Time in parsing JSON: 0 us
[DEBUG] Time in JSON reader: 0 us
[DEBUG] Time in filesystem: 11851 us
[DEBUG] Time in loading ports: 0 us
[DEBUG] Exiting after 49.58 ms (9761 us)

And got the same out running vcpkg list or vcpkg install.
It looks like a env problem but I can't fix it on my own.
Thanke for any help.

**Comment by JackBoosY** [comment]
How did you get vcpkg? Clone or directly download the zip package?
Please confirm `.vcpkg-root` exists in the vcpkg root dir, also please clone vcpkg in non-system path to avoid the permission issues.

**Comment by DeanXi** [comment]
> How did you get vcpkg? Clone or directly download the zip package? Please confirm `.vcpkg-root` exists in the vcpkg root dir, also please clone vcpkg in non-system path to avoid the permission issues.
Thank you for your reply.
I downloaded the ZIP package and ran bootstrap.bat, the script program downloaded vcpkg.exe. 
I checked the vcpkg root, .vcpkg-root exists but empty. 
The path that vcpkg unziped in is non-system path, which is output in the error log

> ` #find_file_recursively_up(E:\TOOLS\vcpkg\vcpkg.exe, .vcpkg-root): ��������`



p.s : My OS is windows10 installed in macbook.

**Comment by JackBoosY** [comment]
@DeanXi Please clone vcpkg instead of downloading vcpkg because the downloaded version cannot enable version control.

**Comment by ShiverZm** [comment]
i met the same problem, i clone twice but the same result.

**Comment by JackBoosY** [comment]
I think this isuse is same with https://github.com/microsoft/vcpkg/issues/19524.

Did you clone or download vcpkg in an external disk?

**Comment by ShiverZm** [comment]
i just use it by putting the vcpkg to C dist like "C:/vcpkg"   ,which can solved this problem.

**Comment by DeanXi** [comment]
> I think this isuse is same with #19524.
> 
> Did you clone or download vcpkg in an external disk or symbol link path?

no，just ran bootstrap.bat

**Comment by DeanXi** [comment]
> i just use it by putting the vcpkg to C dist like "C:/vcpkg" ,which can solved this problem.
Thank you so much, it works!!

**Comment by JackBoosY** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/19524.
