### ISSUE TITLE
header files not found

### ISSUE THREAD

**Issue by Cook21** [microsoft/vcpkg#22128]
**Describe the bug**
I was able to build my projects on Fedora with the DNF, but after I switch to MacOS and vcpkg, one of my projects failed: https://github.com/Cook21/GAMES101-Assignments/tree/main/Assignment0, it told me 

> fatal error: 'eigen3/Eigen/Core' file not found 

when I run the `make` command.
**Environment**
- OS: MacOS 12.1
- Compiler: Apple clang version 13.0.0

**To Reproduce**
Add these lines to `CMakeLists.txt`:
```
include(FetchContent)
FetchContent_Declare(vcpkg
    vcpkg
    URL "https://github.com/microsoft/vcpkg/archive/master.zip")
FetchContent_MakeAvailable(vcpkg)
set(CMAKE_TOOLCHAIN_FILE ${vcpkg_SOURCE_DIR}/scripts/buildsystems/vcpkg.cmake)
```
Create `vcpkg.json` on source folder:
```
{
    "name": "transformation",
    "version-string": "0",
    "dependencies": [
      "eigen3"
    ]
}
```
```
mkdir build
cd build
cmake ..
make
```
**Expected behavior**
Successfully build.

**Failure logs** 
fatal error: 'eigen3/Eigen/Core' file not found

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. The include path of `eigen3` is _VCPKG_ROOT/installed/TRIPLET/include/eigen3_, so this should be `#include <Eigen/Core>` in **main.cpp**. You can use the following codes in **CMakeLists.txt**, and needn't set `include_directories`
```
find_package(Eigen3 CONFIG REQUIRED)
target_link_libraries(main PRIVATE Eigen3::Eigen)
```

**Comment by Cook21** [comment]
It works, thanks!

**Comment by Cook21** [comment]
@LilyWangLL This raises a concern for me, what if I have to include header files with the same name from two different libraries?

**Comment by Cook21** [comment]
OK, I think I know how to deal with this, just add:
`include_directories(${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include)`
and I can use `#include <eigen3/Eigen/Core>` as a uniform format with other scenarios
