### ISSUE TITLE
AWS storage support for binary caching 

### ISSUE THREAD

**Issue by qdin** [microsoft/vcpkg#22139]
****

**Is your feature request related to a problem? Please describe.**
Binary caching is wonderful (thank you!), and the ability to use external storage is great, but I build my software using vcpkg on AWS instances, so it would be great to have an AWS-based storage solution.
Currently binary caching supports NuGet and Google Cloud storage, while there is zero mention of using AWS S3 or CodeArtifact.

**Proposed solution**
To add the ability to store binary artifacts on S3 / CodeArtifact.

**Describe alternatives you've considered**
There is a solution to use AWS CodeArtifact via NuGet but that means supporting (and paying for) another 2 tools/services. 

**Additional context**
N/A

**Comment by PhoebeHui** [comment]
Related to https://github.com/microsoft/vcpkg-tool/pull/293

**Comment by BillyONeal** [comment]
Fixed by https://github.com/microsoft/vcpkg/pull/22629

**Comment by qdin** [comment]
Amazing, thank you!
