### ISSUE TITLE
[boost-exception] build failure

### ISSUE THREAD

**Issue by bertox94** [microsoft/vcpkg#22132]
**Host Environment**
- OS: Windows 10
- Compiler: clang -v
       clang version 12.0.0
       Target: i686-pc-windows-msvc
       Thread model: posix
       InstalledDir: C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\Llvm\bin

**To Reproduce**
`.\vcpkg.exe install boost-exception:x86-windows-xp-llvm`

**Failure logs** 
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: ninja -v
    Working Directory: C:/Users/alt/vcpkg-master/buildtrees/boost-exception/x86-windows-xp-llvm-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\Users\alt\vcpkg-master\buildtrees\boost-exception\config-x86-windows-xp-llvm-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:407 (vcpkg_execute_required_process)
  installed/x64-windows/share/boost-build/boost-modular-build.cmake:89 (vcpkg_cmake_configure)
  ports/boost-exception/portfile.cmake:15 (boost_modular_build)
  scripts/ports.cmake:142 (include)

Error: Building package boost-exception:x86-windows-xp-llvm failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-exception
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[boost-exception]+Build+error
including:
  package: boost-exception[core]:x86-windows-xp-llvm -> 1.77.0
    vcpkg-tool version: 2021-12-09-724cea8b33cbf06c645f5095fa29773697da9761
    vcpkg-scripts version: unknown

Triplet and toolchain: [triplets.zip](https://github.com/microsoft/vcpkg/files/7750756/triplets.zip)

**Comment by yurybura** [comment]
Please upload log file `C:\Users\alt\vcpkg-master\buildtrees\boost-exception\config-x86-windows-xp-llvm-out.log`.

**Comment by bertox94** [comment]
Had to do some changes, because other libraries were failing. So my intention is, **use clang-cl and link with libc++**.
Starting from the master version I only created this triplet file: [x86-windows-static.zip](https://github.com/microsoft/vcpkg/files/7761330/x86-windows-static.zip)

**The command failing now is**: .\vcpkg install boost-exception:x86-windows-static
**with this error**:
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: ninja -v
    Working Directory: C:/Users/alt/vcpkg/buildtrees/boost-exception/x86-windows-static-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\Users\alt\vcpkg\buildtrees\boost-exception\config-x86-windows-static-out.log: [config-x86-windows-static-out.log](https://github.com/microsoft/vcpkg/files/7761348/config-x86-windows-static-out.log)


Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:407 (vcpkg_execute_required_process)
  installed/x64-windows/share/boost-build/boost-modular-build.cmake:89 (vcpkg_cmake_configure)
  ports/boost-exception/portfile.cmake:15 (boost_modular_build)
  scripts/ports.cmake:142 (include)


Error: Building package boost-exception:x86-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-exception
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[boost-exception]+Build+error
including:
  package: boost-exception[core]:x86-windows-static -> 1.77.0
    vcpkg-tool version: 2021-12-09-724cea8b33cbf06c645f5095fa29773697da9761
    vcpkg-scripts version: 67e427212 2021-12-22 (4 hours ago)

**Comment by Nemirtingas** [comment]
I don't know about you, but I installed Clang+LLVM and had to do this to make it compile:
```
rm -rf trash && cmake \
  "-DCMAKE_EXE_LINKER_FLAGS=/manifest:no -libpath:\"C:/Program Files (x86)/Windows Kits/10/Lib/10.0.18362.0/um/x64\" -libpath:\"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\lib\x64\" -libpath:\"C:/Program Files (x86)/Windows Kits/10/Lib/10.0.18362.0/ucrt/x64\"" \
  -DCMAKE_RC_COMPILER=D:/Programs/LLVM/bin/llvm-rc.exe \
  -DCMAKE_MAKE_PROGRAM=D:/Programs/ninja/ninja.exe \
  -DCMAKE_CXX_COMPILER:PATH=D:/Programs/LLVM/bin/clang-cl.exe \
  -DCMAKE_C_COMPILER:PATH=D:/Programs/LLVM/bin/clang-cl.exe \
  -G"Ninja" .  -B trash
```
