### ISSUE TITLE
Boost portfile.cmake fails to rename static debug .lib filenames when enabling Python feature

### ISSUE THREAD

**Issue by hlmodi** [Microsoft/vcpkg#2213]
I've lost two days wondering why linking to static libs kept failing.

Problem:
When boost is compiled with Python, static debug .lib filenames are named with "-sgyd-".
Boost portfile.cmake only renames files (to match release .lib filenames) when they have "-sgd-".

Solution:
It should replace "-sg" to "-g" (so as to maintain after any other additional combination)

Bests

**Comment by JackBoosY** [comment]
Hi @hlmodi, thanks for reporting this issue!
In the latest version, boost-python build static library renamed to boost_python36-vcXXX-mt-gd.lib. Is this correct?

**Comment by hlmodi** [comment]
Correct!
Thanks


-------- Mensaje original --------
De: JackBoosY <notifications@github.com>
Fecha: 19/3/19 23:26 (GMT-03:00)
A: Microsoft/vcpkg <vcpkg@noreply.github.com>
CC: hlmodi <hlmodi@hotmail.com>, Mention <mention@noreply.github.com>
Asunto: Re: [Microsoft/vcpkg] Boost portfile.cmake fails to rename static debug .lib filenames when enabling Python feature (#2213)


Hi @hlmodi<https://github.com/hlmodi>, thanks for reporting this issue!
In the latest version, boost-python build static library renamed to boost_python36-vcXXX-mt-gd.lib. Is this correct?
