### ISSUE TITLE
Error compiling gmp under ubuntu 18.04: Host path separator (:) in path; this is unsupported.

### ISSUE THREAD

**Issue by lmdiazangulo** [microsoft/vcpkg#22148]
**Host Environment**
- OS: Ubuntu 18.04.6 LTS
- Compiler: gcc (Ubuntu 10.3.0-1ubuntu1-18.04-1) 10.3.0

**To Reproduce**
`./vcpkg install gmp`

**Failure logs** 

> Building package gmp[core]:x64-linux...
> -- Using cached gmp-6.2.1.tar.xz.
> -- Extracting source /home/luis/workspace/vcpkg/downloads/gmp-6.2.1.tar.xz
> -- Applying patch tools.patch
> -- Using source at /home/luis/workspace/vcpkg/buildtrees/gmp/src/gmp-6.2.1-f412680bba.clean
> -- Getting CMake variables for x64-linux-dbg
> -- Getting CMake variables for x64-linux-rel
> CMake Error at scripts/cmake/vcpkg_host_path_list.cmake:43 (message):
>   Host path separator (:) in path; this is unsupported.
> Call Stack (most recent call first):
>   scripts/cmake/vcpkg_host_path_list.cmake:72 (z_vcpkg_translate_to_host_path_list)
>   scripts/cmake/vcpkg_configure_make.cmake:218 (vcpkg_host_path_list)
>   scripts/cmake/vcpkg_configure_make.cmake:527 (z_prepend_include_path)
>   ports/gmp/portfile.cmake:103 (vcpkg_configure_make)
>   scripts/ports.cmake:142 (include)
> 
> 
> Error: Building package gmp:x64-linux failed with: BUILD_FAILED

**Comment by autoantwort** [comment]
What is your current PATH?

**Comment by lmdiazangulo** [comment]
I had this: 

> /home/luis/.local/bin:/opt/intel/compilers_and_libraries_2019.1.144/linux/bin/intel64:/opt/intel//compilers_and_libraries_2019.1.144/linux/mpi/intel64/libfabric/bin:/opt/intel//compilers_and_libraries_2019.1.144/linux/mpi/intel64/bin:/opt/intel/debugger_2019/gdb/intel64/bin:/opt/intel/impi/4.1.3.049/intel64/bin:/opt/intel/composer_xe_2013_sp1.2.144/bin/intel64:/opt/intel/composer_xe_2013_sp1.2.144/mpirt/bin/intel64:/opt/intel/composer_xe_2013_sp1.2.144/bin/intel64:/opt/intel/composer_xe_2013_sp1.2.144/bin/intel64_mic:/opt/intel/composer_xe_2013_sp1.2.144/debugger/gui/intel64:/opt/intel/impi/4.1.3.049/intel64/bin:/opt/intel/composer_xe_2013_sp1.2.144/bin/intel64:/opt/intel/composer_xe_2013_sp1.2.144/mpirt/bin/intel64:/opt/intel/composer_xe_2013_sp1.2.144/bin/intel64:/opt/intel/composer_xe_2013_sp1.2.144/bin/intel64_mic:/opt/intel/composer_xe_2013_sp1.2.144/debugger/gui/intel64:/opt/intel/impi/4.1.3.049/intel64/bin:/opt/intel/composer_xe_2013_sp1.2.144/bin/intel64:/opt/intel/composer_xe_2013_sp1.2.144/mpirt/bin/intel64:/opt/intel/composer_xe_2013_sp1.2.144/bin/intel64:/opt/intel/composer_xe_2013_sp1.2.144/bin/intel64_mic:/opt/intel/composer_xe_2013_sp1.2.144/debugger/gui/intel64:/opt/intel/impi/4.1.3.049/intel64/bin:/opt/intel/composer_xe_2013_sp1.3.174/bin/intel64:/opt/intel/composer_xe_2013_sp1.3.174/mpirt/bin/intel64:/opt/intel/composer_xe_2013_sp1.3.174/bin/intel64:/opt/intel/composer_xe_2013_sp1.3.174/bin/intel64_mic:/opt/intel/composer_xe_2013_sp1.3.174/debugger/gui/intel64:/home/luis/intel/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/luis/intel/bin:/home/luis/intel/impi/4.1.3.049/bin64

I have removed the intel compiler sources and now it seems to be working. Thanks!
