### ISSUE TITLE
Upgrade option

### ISSUE THREAD

**Issue by vkaytsanov** [microsoft/vcpkg#22145]
****
I just decided to upgrade my packages with `./vcpkg.exe upgrade --no-dry-run` and I lost all my ports, just because of a some dependency that can't build of `assimp`.

**Proposed solution**
Make the upgrade iterative, a.k.a remove port -> upgrade -> next port

**Comment by autoantwort** [comment]
Use `--keep-going`, duplicate of #17922 and possible fix in https://github.com/microsoft/vcpkg-tool/pull/308
