### ISSUE TITLE
tls12-download.exe failed with error 0x00002EFE

### ISSUE THREAD

**Issue by huangqinjin** [microsoft/vcpkg#22143]
```shell
> tls12-download.exe github.com /microsoft/vcpkg-tool/releases/download/2021-12-09/vcpkg.exe vcpkg.exe
Downloading https://github.com/microsoft/vcpkg-tool/releases/download/2021-12-09/vcpkg.exe -> vcpkg.exe...While calling Windows API function WinHttpReceiveResponse got error 0x00002EFE:
The connection with this server was terminated abnormally.
```

`tls12-download.exe` failed to download `vcpkg.exe`. But using following powershell command it is successful.
```powershell
Invoke-WebRequest https://github.com/microsoft/vcpkg-tool/releases/download/2021-12-09/vcpkg.exe -OutFile vcpkg.exe
```

I don't understand how my company IT department configure the network. They are quite conservative, as not long ago, I could not even `git clone` repo from github. Any suggestions to troubleshoot?

**Comment by JackBoosY** [comment]
Please track https://github.com/microsoft/vcpkg/issues/21163 instead.

**Comment by huangqinjin** [comment]
@JackBoosY not the same case as #21163 I think. The problem there is about http headers and curl, but here is tls12-download.exe and nothing about headers.

**Comment by JackBoosY** [comment]
According to the [msdn doc](https://docs.microsoft.com/en-us/windows/win32/winhttp/error-messages):
```
ERROR_WINHTTP_CONNECTION_ERROR

12030

The connection with the server has been reset or terminated, or an incompatible SSL protocol was encountered. For example, WinHTTP version 5.1 does not support SSL2 unless the client specifically enables it.
```

**Comment by JackBoosY** [comment]
I can't repro this issue using [2021-12-09 release](https://github.com/microsoft/vcpkg-tool/releases/download/2021-12-09/tls12-download.exe).
Can you please try the latest executable again?

Thanks.

**Comment by huangqinjin** [comment]
I tried the latest tls12-download.exe and got same error. I think this problem is specific to my company environment. But I don't understand why `Invoke-WebRequest` is working.

**Comment by JackBoosY** [comment]
You can directly download vcpkg binary using [the Chinese mirror](https://gitee.com/jackboosy/vcpkg-tool/releases).

**Comment by huangqinjin** [comment]
In fact my company is in Singapore. And the problem is not only `tls12-download.exe`, `vcpkg x-download` that download all packages has same error.

**Comment by JackBoosY** [comment]
@huangqinjin So you can use the bootstrap scripts to download vcpkg.

**Comment by huangqinjin** [comment]
Done more tests in my environment.

| URL |  pwsh |  vcpkg |  aria2 | curl | cmake |
|----|--------|---------|--------|------|--------|
| 1 |  :heavy_check_mark: | :x: | :x: | :x: | :x: |
| 2 |  :heavy_check_mark: | :x: | :x: | :x: | :x: |
| 3 |  :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |

1. https://www.7-zip.org/a/7z1900-src.7z
2. https://github.com/microsoft/vcpkg-tool/releases/download/2021-12-09/vcpkg.exe
3. https://github.com/microsoft/vcpkg-tool/archive/refs/tags/2021-12-09.zip


Since no valuable information in this thread, let's close it now.
