### ISSUE TITLE
PCL installation - Error: Building package pcl:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by Robomate** [microsoft/vcpkg#22144]
OS: Win11

-- Building x86-windows-dbg
-- Building x86-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:155 (message):
    Command failed: C:/Users/rfg/vcpkg/downloads/tools/cmake-3.21.1-windows/cmake-3.21.1-windows-i386/bin/cmake.exe --build . --config Release --target install -- -v -j17
    Working Directory: C:/Users/rfg/vcpkg/buildtrees/pcl/x86-windows-rel
    See logs for more information:
      C:\Users\rfg\vcpkg\buildtrees\pcl\install-x86-windows-rel-out.log

Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+pcl
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[pcl]+Build+error
including:
  package: pcl[core]:x86-windows -> 1.12.0#2
    vcpkg-tool version: 2021-12-09-724cea8b33cbf06c645f5095fa29773697da9761
    vcpkg-scripts version: 0fd31b9db 2021-12-20 (10 hours ago)

Additionally, attach any relevant sections from the log files above.
[install-x86-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/7757319/install-x86-windows-rel-out.log)

**Comment by autoantwort** [comment]
> C:\Users\rfg\vcpkg\buildtrees\pcl\src\89d532cf08-d57dbcb12e.clean\surface\src\3rdparty\opennurbs\opennurbs_lookup.cpp(670) : fatal error C1001: Internal compiler error.
(compiler file 'd:\a01\_work\3\s\src\vctools\Compiler\Utc\src\p2\main.c', line 217)
 To work around this problem, try simplifying or changing the program near the locations listed above.
If possible please provide a repro here: https://developercommunity.visualstudio.com 
Please choose the Technical Support command on the Visual C++ 
 Help menu, or open the Technical Support help file for more information
  cl!RaiseException()+0x6c
  cl!RaiseException()+0x6c
  cl!CloseTypeServerPDB()+0x1c030f
  cl!CloseTypeServerPDB()+0xdae19

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. This is a bug of Visual Studio.
Closed this due to duplicate with #19561, please pay attention of #19561.
