### ISSUE TITLE
MPI executes only one process 

### ISSUE THREAD

**Issue by booka24** [microsoft/vcpkg#22155]
Hello 

Just started to work with MPI 
everything is installed and works fine 
And my first code was Hello World 
But in console were executed only one process and shows size = 1 only !
What's wrong?

**Comment by JackBoosY** [comment]
Which triplet did you use?

**Comment by booka24** [comment]
> Which triplet did you use?

64x-windows

**Comment by JackBoosY** [comment]
In x64-windows, port `mpi` is `msmpi`. vcpkg only unzip the official package and get the include path.
So I think it's a usage issue.
Please report it to https://github.com/microsoft/Microsoft-MPI/issues instead.

Thanks.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
