### ISSUE TITLE
[GLFW3] build failure

### ISSUE THREAD

**Issue by Legonois** [microsoft/vcpkg#22164]
**Host Environment**
- OS: Windows 11 Professional 
- Compiler: Not sure what to put here

**To Reproduce**
 .\vcpkg install GLFW3

**Failure logs** 

> PS C:\Users\\#####\source\weird stuff for VS\vcpkg-2021.05.12> .\vcpkg install GLFW3
> Computing installation plan...
> The following packages will be built and installed:
>     glfw3[core]:x86-windows -> 3.3.3
> _**No suitable Visual Studio instances were found**_

**Additional context**
I have repaired my Visual Studio 2022 Community Edition instance and made sure I had the English Language Pack

I have also added a system variable called "VCPKG_VISUAL_STUDIO_PATH" that contains "C:\Program Files\Microsoft Visual Studio\2022" to help troubleshoot it. It did not work.

**Comment by Legonois** [comment]
This might help. I found the debug command and I hope this helps understand the problem

 ".\vcpkg install GLFW3 --debug" is the command that I ran

PS C:\Users\#####\source\weird stuff for VS\vcpkg-2021.05.12> .\vcpkg install GLFW3 --debug
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] BuiltinRegistry initialized with: ""
[DEBUG] Using vcpkg-root: C:\Users\#####\source\weird stuff for VS\vcpkg-2021.05.12
[DEBUG] Using installed-root: C:\Users\#####\source\weird stuff for VS\vcpkg-2021.05.12\installed
[DEBUG] BuiltinRegistry initialized with: ""
[DEBUG] Using buildtrees-root: C:\Users\#####\source\weird stuff for VS\vcpkg-2021.05.12\buildtrees
[DEBUG] Using downloads-root: C:\Users\#####\source\weird stuff for VS\vcpkg-2021.05.12\downloads
[DEBUG] Using packages-root: C:\Users\#####\source\weird stuff for VS\vcpkg-2021.05.12\packages
[DEBUG] Using scripts-root: C:\Users\#####\source\weird stuff for VS\vcpkg-2021.05.12\scripts
[DEBUG] Using ports-root: C:\Users\#####\source\weird stuff for VS\vcpkg-2021.05.12\ports
[DEBUG] Using versions-root: C:\Users\#####\source\weird stuff for VS\vcpkg-2021.05.12\versions
[DEBUG] Default binary cache path is: C:\Users\#####\AppData\Local\vcpkg\archives
Computing installation plan...
[DEBUG] CreateProcessW("C:\Users\#####\source\weird stuff for VS\vcpkg-2021.05.12\downloads\tools\cmake-3.20.2-windows\cmake-3.20.2-windows-i386\bin\cmake.exe" --version)
[DEBUG] cmd_execute_and_stream_data() returned 0 after    37688 us
[DEBUG] CreateProcessW("C:\Users\#####\source\weird stuff for VS\vcpkg-2021.05.12\downloads\tools\cmake-3.20.2-windows\cmake-3.20.2-windows-i386\bin\cmake.exe" "-DVCPKG_ROOT_DIR=C:/Users/#####/source/weird stuff for VS/vcpkg-2021.05.12" "-DPACKAGES_DIR=C:/Users/#####/source/weird stuff for VS/vcpkg-2021.05.12/packages" "-DBUILDTREES_DIR=C:/Users/#####/source/weird stuff for VS/vcpkg-2021.05.12/buildtrees" "-D_VCPKG_INSTALLED_DIR=C:/Users/#####/source/weird stuff for VS/vcpkg-2021.05.12/installed" "-DDOWNLOADS=C:/Users/#####/source/weird stuff for VS/vcpkg-2021.05.12/downloads" -DVCPKG_MANIFEST_INSTALL=OFF -P "C:\Users\#####\source\weird stuff for VS\vcpkg-2021.05.12\buildtrees\0.vcpkg_tags.cmake")
[DEBUG] cmd_execute_and_stream_data() returned 0 after    26258 us
The following packages will be built and installed:
    glfw3[core]:x86-windows -> 3.3.3
[DEBUG] CreateProcessW("C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -all -prerelease -legacy -products * -format xml)
[DEBUG] cmd_execute_and_stream_data() returned 0 after    23209 us
[DEBUG] Could not locate a complete Visual Studio instance
[DEBUG] The following paths were examined:
[DEBUG]     C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat
No suitable Visual Studio instances were found
[DEBUG] C:\A\1\121\s\src\vcpkg\vcpkgpaths.cpp(1128)
[DEBUG] Exiting after 127586 us (120977 us)

**Comment by Legonois** [comment]
I have uninstalled everything with Visual Studio 2022, and reinstalled it with the C++ Desktop Development package, along with the Windows 10 and Windows 11 SDK. I saw somewhere that installing that fixed it, but I am still getting the same error

**Comment by Cheney-W** [comment]
Could you please run `.\bootstrap-vcpkg.bat` in the vcpkg folder and try to install this port again?

**Comment by Legonois** [comment]
It did not work

PS C:\Users\wesle\source\weird stuff for VS\vcpkg-2021.05.12> .\bootstrap-vcpkg.bat
Downloading https://github.com/microsoft/vcpkg-tool/releases/download/2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/vcpkg.exe -> C:\Users\wesle\source\weird stuff for VS\vcpkg-2021.05.12\vcpkg.exe
Done.

Telemetry

vcpkg collects usage data in order to help us improve your experience.
The data collected by Microsoft is anonymous.
You can opt-out of telemetry by re-running the bootstrap-vcpkg script with -disableMetrics,
passing --disable-metrics to vcpkg on the command line,
or by setting the VCPKG_DISABLE_METRICS environment variable.

Read more about vcpkg telemetry at docs/about/privacy.md
PS C:\Users\wesle\source\weird stuff for VS\vcpkg-2021.05.12>  .\vcpkg install GLFW3 --debug
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] BuiltinRegistry initialized with: ""
[DEBUG] Using vcpkg-root: C:\Users\wesle\source\weird stuff for VS\vcpkg-2021.05.12
[DEBUG] Using installed-root: C:\Users\wesle\source\weird stuff for VS\vcpkg-2021.05.12\installed
[DEBUG] BuiltinRegistry initialized with: ""
[DEBUG] Using buildtrees-root: C:\Users\wesle\source\weird stuff for VS\vcpkg-2021.05.12\buildtrees
[DEBUG] Using downloads-root: C:\Users\wesle\source\weird stuff for VS\vcpkg-2021.05.12\downloads
[DEBUG] Using packages-root: C:\Users\wesle\source\weird stuff for VS\vcpkg-2021.05.12\packages
[DEBUG] Using scripts-root: C:\Users\wesle\source\weird stuff for VS\vcpkg-2021.05.12\scripts
[DEBUG] Using ports-root: C:\Users\wesle\source\weird stuff for VS\vcpkg-2021.05.12\ports
[DEBUG] Using versions-root: C:\Users\wesle\source\weird stuff for VS\vcpkg-2021.05.12\versions
[DEBUG] Default binary cache path is: C:\Users\wesle\AppData\Local\vcpkg\archives
Computing installation plan...
[DEBUG] CreateProcessW("C:\Users\wesle\source\weird stuff for VS\vcpkg-2021.05.12\downloads\tools\cmake-3.20.2-windows\cmake-3.20.2-windows-i386\bin\cmake.exe" --version)
[DEBUG] cmd_execute_and_stream_data() returned 0 after    49633 us
[DEBUG] CreateProcessW("C:\Users\wesle\source\weird stuff for VS\vcpkg-2021.05.12\downloads\tools\cmake-3.20.2-windows\cmake-3.20.2-windows-i386\bin\cmake.exe" "-DVCPKG_ROOT_DIR=C:/Users/wesle/source/weird stuff for VS/vcpkg-2021.05.12" "-DPACKAGES_DIR=C:/Users/wesle/source/weird stuff for VS/vcpkg-2021.05.12/packages" "-DBUILDTREES_DIR=C:/Users/wesle/source/weird stuff for VS/vcpkg-2021.05.12/buildtrees" "-D_VCPKG_INSTALLED_DIR=C:/Users/wesle/source/weird stuff for VS/vcpkg-2021.05.12/installed" "-DDOWNLOADS=C:/Users/wesle/source/weird stuff for VS/vcpkg-2021.05.12/downloads" -DVCPKG_MANIFEST_INSTALL=OFF -P "C:\Users\wesle\source\weird stuff for VS\vcpkg-2021.05.12\buildtrees\0.vcpkg_tags.cmake")
[DEBUG] cmd_execute_and_stream_data() returned 0 after    28248 us
The following packages will be built and installed:
    glfw3[core]:x86-windows -> 3.3.3
[DEBUG] CreateProcessW("C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -all -prerelease -legacy -products * -format xml)
[DEBUG] cmd_execute_and_stream_data() returned 0 after    28129 us
[DEBUG] Could not locate a complete Visual Studio instance
[DEBUG] The following paths were examined:
[DEBUG]     C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat
No suitable Visual Studio instances were found
[DEBUG] C:\A\1\121\s\src\vcpkg\vcpkgpaths.cpp(1128)
[DEBUG] Exiting after 130263 us (123233 us)

**Comment by Cheney-W** [comment]
Sorry, it's my mistake. You should git pull the latest vcpkg and run this script for getting the latest vcpkg.exe 2021-12-09-724cea8b33cbf06c645f5095fa29773697da9761.
Also, could you find the vcvarsall.bat file in your computer?

**Comment by Legonois** [comment]
I pulled the latest version and it works!! Thanks!
