### ISSUE TITLE
vcpkg with CLion

### ISSUE THREAD

**Issue by kreuzerkrieg** [microsoft/vcpkg#22178]
Documentation problem

it is stated here https://github.com/microsoft/vcpkg#vcpkg-with-clion
```
Vcpkg with CLion
Open the Toolchains settings (File > Settings on Windows and Linux, CLion > Preferences on macOS), and go to the CMake settings (Build, Execution, Deployment > CMake). Finally, in CMake options, add the following line:

-DCMAKE_TOOLCHAIN_FILE=[vcpkg root]/scripts/buildsystems/vcpkg.cmake
Unfortunately, you'll have to add this to each profile.
```
This part, `Unfortunately, you'll have to add this to each profile.` is not true, you have a way to solve it using standar cmake approach by adding PreLoad.cmake file and adding the following line to it
`set(CMAKE_TOOLCHAIN_FILE ~/Development/vcpkg/scripts/buildsystems/vcpkg.cmake CACHE INTERNAL "" FORCE)`

Dont remember if restarting the CLion is enough or you have to delete the cmake folder and restart CLion but it is less important

**Comment by JackBoosY** [comment]
Can you please correct our document?

Thanks.

**Comment by kreuzerkrieg** [comment]
> Can you please correct our document?
> 
> Thanks.

https://github.com/microsoft/vcpkg/pull/22275

**Comment by LilyWangLL** [comment]
Fixed by #24737.

**Comment by Chealer** [comment]
The relevant line is now on [vcpkg in CMake projects](https://learn.microsoft.com/en-us/vcpkg/users/buildsystems/cmake-integration#clion).

**Comment by kreuzerkrieg** [comment]
> The relevant line is now on [vcpkg in CMake projects](https://learn.microsoft.com/en-us/vcpkg/users/buildsystems/cmake-integration#clion).

not sure it is relevant in 2026, vcpkg has native integration in clion now

**Comment by Chealer** [comment]
I hit 2 errors in CLion 2026.1, including "This Vcpkg instance is not used in any Cmake profile" and then a persistent:
> error: in triplet x64-windows: Unable to find a valid Visual Studio instance
> Could not locate a complete Visual Studio instance

But the next day, installing with Vcpkg worked from the first attempt, indeed without having to add that line.
