### ISSUE TITLE
[mp3Lame] : x86 build Failing certification test in UWP, because ImageHasSafeExceptionHandlers is set to false 

### ISSUE THREAD

**Issue by AbhishekSharma-SEG** [microsoft/vcpkg#22186]
in x86, mp3Lame Failing certification test in UWP version because of ImageHasSafeExceptionHandlers Flag set to false 

need to update  patch  00001-msvc-upgrade-solution-up-to-vc11, and set ImageHasSafeExceptionHandlers to true

**Comment by AbhishekSharma-SEG** [comment]
I have an open pr,u can check, with the same fix  #22188

**Comment by JackBoosY** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
