### ISSUE TITLE
[bzip2] Build error

### ISSUE THREAD

**Issue by jing-yao** [microsoft/vcpkg#22193]
**Host Environment**
- OS: [win10]
- Compiler:  vs2022

**To Reproduce**
.\vcpkg install colmap[cuda,tests]:x64-windows

**Failure logs** 
Error: Building package bzip2:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+bzip2
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[bzip2]+Build+error
including:
  package: bzip2[core]:x64-windows -> 1.0.8#2
    vcpkg-tool version: 2021-12-09-724cea8b33cbf06c645f5095fa29773697da9761
    vcpkg-scripts version: 772fe6cbc 2021-12-22 (2 days ago)

**Additional context**
and i tried to use '.\vcpkg update' , there is 'No packages need updating'.
I tried to use 'git pull ' ,there is 'Already up to date'.

**Comment by JackBoosY** [comment]
Please provide the full output and the log mentioned in the output.

Thanks.

**Comment by jing-yao** [comment]
i tried to bulid COLMAP using `.\vcpkg install colmap[cuda,tests]:x64-windows`, my output is:

> Computing installation plan...
The following packages will be built and installed:
  * assimp[core]:x64-windows -> 5.0.1#5
  * blas[core]:x64-windows -> 1#1
  * boost-accumulators[core]:x64-windows -> 1.77.0
  * boost-algorithm[core]:x64-windows -> 1.77.0
  * boost-align[core]:x64-windows -> 1.77.0
  * boost-any[core]:x64-windows -> 1.77.0
  * boost-array[core]:x64-windows -> 1.77.0
  * boost-assert[core]:x64-windows -> 1.77.0
  * boost-atomic[core]:x64-windows -> 1.77.0
  * boost-bimap[core]:x64-windows -> 1.77.0
  * boost-bind[core]:x64-windows -> 1.77.0
  * boost-build[core]:x64-windows -> 1.77.0
  * boost-callable-traits[core]:x64-windows -> 1.77.0
  * boost-chrono[core]:x64-windows -> 1.77.0
  * boost-circular-buffer[core]:x64-windows -> 1.77.0
  * boost-compute[core]:x64-windows -> 1.77.0
  * boost-concept-check[core]:x64-windows -> 1.77.0
  * boost-config[core]:x64-windows -> 1.77.0#2
  * boost-container[core]:x64-windows -> 1.77.0
  * boost-container-hash[core]:x64-windows -> 1.77.0
  * boost-conversion[core]:x64-windows -> 1.77.0
  * boost-core[core]:x64-windows -> 1.77.0
  * boost-date-time[core]:x64-windows -> 1.77.0
  * boost-detail[core]:x64-windows -> 1.77.0
  * boost-dynamic-bitset[core]:x64-windows -> 1.77.0
  * boost-endian[core]:x64-windows -> 1.77.0
  * boost-exception[core]:x64-windows -> 1.77.0
  * boost-filesystem[core]:x64-windows -> 1.77.0
  * boost-foreach[core]:x64-windows -> 1.77.0
  * boost-format[core]:x64-windows -> 1.77.0
  * boost-function[core]:x64-windows -> 1.77.0
  * boost-function-types[core]:x64-windows -> 1.77.0
  * boost-functional[core]:x64-windows -> 1.77.0
  * boost-fusion[core]:x64-windows -> 1.77.0
  * boost-geometry[core]:x64-windows -> 1.77.0
  * boost-graph[core]:x64-windows -> 1.77.0
  * boost-heap[core]:x64-windows -> 1.77.0
  * boost-integer[core]:x64-windows -> 1.77.0
  * boost-interval[core]:x64-windows -> 1.77.0
  * boost-intrusive[core]:x64-windows -> 1.77.0
  * boost-io[core]:x64-windows -> 1.77.0
  * boost-iostreams[bzip2,core,lzma,zlib,zstd]:x64-windows -> 1.77.0#1
  * boost-iterator[core]:x64-windows -> 1.77.0
  * boost-lambda[core]:x64-windows -> 1.77.0
  * boost-lexical-cast[core]:x64-windows -> 1.77.0
  * boost-logic[core]:x64-windows -> 1.77.0
  * boost-math[core]:x64-windows -> 1.77.0
  * boost-modular-build-helper[core]:x64-windows -> 1.77.0#4
  * boost-move[core]:x64-windows -> 1.77.0
  * boost-mp11[core]:x64-windows -> 1.77.0
  * boost-mpl[core]:x64-windows -> 1.77.0
  * boost-multi-index[core]:x64-windows -> 1.77.0
  * boost-multiprecision[core]:x64-windows -> 1.77.0
  * boost-numeric-conversion[core]:x64-windows -> 1.77.0
  * boost-optional[core]:x64-windows -> 1.77.0
  * boost-parameter[core]:x64-windows -> 1.77.0
  * boost-phoenix[core]:x64-windows -> 1.77.0
  * boost-polygon[core]:x64-windows -> 1.77.0
  * boost-pool[core]:x64-windows -> 1.77.0
  * boost-predef[core]:x64-windows -> 1.77.0
  * boost-preprocessor[core]:x64-windows -> 1.77.0
  * boost-program-options[core]:x64-windows -> 1.77.0
  * boost-property-map[core]:x64-windows -> 1.77.0
  * boost-property-tree[core]:x64-windows -> 1.77.0
  * boost-proto[core]:x64-windows -> 1.77.0
  * boost-ptr-container[core]:x64-windows -> 1.77.0
  * boost-qvm[core]:x64-windows -> 1.77.0
  * boost-random[core]:x64-windows -> 1.77.0
  * boost-range[core]:x64-windows -> 1.77.0
  * boost-ratio[core]:x64-windows -> 1.77.0
  * boost-rational[core]:x64-windows -> 1.77.0
  * boost-regex[core]:x64-windows -> 1.77.0
  * boost-serialization[core]:x64-windows -> 1.77.0
  * boost-smart-ptr[core]:x64-windows -> 1.77.0
  * boost-spirit[core]:x64-windows -> 1.77.0
  * boost-static-assert[core]:x64-windows -> 1.77.0
  * boost-system[core]:x64-windows -> 1.77.0
  * boost-test[core]:x64-windows -> 1.77.0
  * boost-thread[core]:x64-windows -> 1.77.0
  * boost-throw-exception[core]:x64-windows -> 1.77.0
  * boost-tokenizer[core]:x64-windows -> 1.77.0
  * boost-tti[core]:x64-windows -> 1.77.0
  * boost-tuple[core]:x64-windows -> 1.77.0
  * boost-type-index[core]:x64-windows -> 1.77.0
  * boost-type-traits[core]:x64-windows -> 1.77.0
  * boost-typeof[core]:x64-windows -> 1.77.0
  * boost-ublas[core]:x64-windows -> 1.77.0
  * boost-uninstall[core]:x64-windows -> 1.77.0
  * boost-units[core]:x64-windows -> 1.77.0
  * boost-unordered[core]:x64-windows -> 1.77.0
  * boost-utility[core]:x64-windows -> 1.77.0
  * boost-uuid[core]:x64-windows -> 1.77.0
  * boost-variant[core]:x64-windows -> 1.77.0
  * boost-variant2[core]:x64-windows -> 1.77.0
  * boost-vcpkg-helpers[core]:x64-windows -> 1.77.0
  * boost-winapi[core]:x64-windows -> 1.77.0
  * boost-xpressive[core]:x64-windows -> 1.77.0
  * brotli[core]:x64-windows -> 1.0.9#2
  * bzip2[core]:x64-windows -> 1.0.8#2
  * ceres[core,lapack,suitesparse]:x64-windows -> 2.0.0#5
  * cgal[core,qt]:x64-windows -> 5.3
    colmap[core,cuda,tests]:x64-windows -> 3.6#1
  * cuda[core]:x64-windows -> 10.1#8
  * double-conversion[core]:x64-windows -> 3.1.5#1
  * egl-registry[core]:x64-windows -> 2021-11-23
  * eigen3[core]:x64-windows -> 3.3.9#1
  * freeglut[core]:x64-windows -> 3.2.1#7
  * freeimage[core]:x64-windows -> 3.18.0#21
  * freetype[brotli,bzip2,core,png,zlib]:x64-windows -> 2.11.0#2
  * gflags[core]:x64-windows -> 2.2.2#5
  * glew[core]:x64-windows -> 2.2.0
  * glog[core]:x64-windows -> 0.4.0#4
  * gmp[core]:x64-windows -> 6.2.1#7
  * harfbuzz[core]:x64-windows -> 3.0.0#1
  * icu[core]:x64-windows -> 69.1#16
  * irrlicht[core]:x64-windows -> 1.8.4#12
  * jasper[core]:x64-windows -> 2.0.33
  * jxrlib[core]:x64-windows -> 2019.10.9#3
  * kubazip[core]:x64-windows -> 0.1.19#1
  * lapack[core]:x64-windows -> 3#2
  * lapack-reference[blas-select,core,noblas]:x64-windows -> 3.8.0#6
  * lcms[core]:x64-windows -> 2.12#2
  * libjpeg-turbo[core]:x64-windows -> 2.0.6#3
  * liblzma[core]:x64-windows -> 5.2.5#4
  * libpng[core]:x64-windows -> 1.6.37#16
  * libraw[core]:x64-windows -> 201903#5
  * libwebp[core,nearlossless,simd,unicode]:x64-windows -> 1.2.1
  * metis[core]:x64-windows -> 5.1.0#8
  * minizip[core]:x64-windows -> 1.2.11#9
  * mpfr[core]:x64-windows -> 4.1.0#2
  * openblas[core]:x64-windows -> 0.3.15#1
  * openexr[core]:x64-windows -> 2.5.0#3
  * opengl[core]:x64-windows -> 0.0#9
  * openjpeg[core]:x64-windows -> 2.4.0
  * openssl[core]:x64-windows -> 1.1.1l#4
  * pcre2[core]:x64-windows -> 10.39#2
  * poly2tri[core]:x64-windows -> 2020-07-21#2
  * polyclipping[core]:x64-windows -> 6.4.2#10
  * qt5-3d[core]:x64-windows -> 5.15.2#2
  * qt5-activeqt[core]:x64-windows -> 5.15.2#1
  * qt5-base[core]:x64-windows -> 5.15.2#19
  * qt5-declarative[core]:x64-windows -> 5.15.2#3
  * qt5-gamepad[core]:x64-windows -> 5.15.2#1
  * qt5-imageformats[core]:x64-windows -> 5.15.2#1
  * qt5-script[core]:x64-windows -> 5.15.2#1
  * qt5-svg[core]:x64-windows -> 5.15.2#2
  * qt5-tools[core]:x64-windows -> 5.15.2#1
  * qt5-xmlpatterns[core]:x64-windows -> 5.15.2#1
  * rapidjson[core]:x64-windows -> 2020-09-14#2
  * sqlite3[core]:x64-windows -> 3.37.0#1
  * stb[core]:x64-windows -> 2020-09-14#1
  * suitesparse[core]:x64-windows -> 5.8.0#1
  * tiff[core,jpeg,lzma,zip]:x64-windows -> 4.3.0#2
  * utfcpp[core]:x64-windows -> 3.2.1
  * vcpkg-cmake[core]:x64-windows -> 2021-12-05
  * vcpkg-cmake-config[core]:x64-windows -> 2021-12-01
  * vcpkg-gfortran[core]:x64-windows -> 3#1
  * vcpkg-pkgconfig-get-modules[core]:x64-windows -> 2021-04-02#1
  * vcpkg-tool-meson[core]:x64-windows -> 0.60.2#1
  * vs-yasm[core]:x64-windows -> 0.5.0#1
  * yasm-tool[core]:x64-windows -> 1.3.0
  * zlib[core]:x64-windows -> 1.2.11#13
  * zstd[core]:x64-windows -> 1.5.0#1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
-- Automatically setting HTTP(S)_PROXY environment variables to 127.0.0.1:20081
Restored 0 packages from C:\Users\49091\AppData\Local\vcpkg\archives in 6.301 ms. Use --debug to see more details.
Starting package 1/163: bzip2:x64-windows
Building package bzip2[core]:x64-windows...
-- Using cached bzip2-1.0.8.tar.gz.
-- Cleaning sources at C:/Users/49091/vcpkg/buildtrees/bzip2/src/bzip2-1-336d4794a3.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/49091/vcpkg/downloads/bzip2-1.0.8.tar.gz
-- Applying patch fix-import-export-macros.patch
-- Using source at C:/Users/49091/vcpkg/buildtrees/bzip2/src/bzip2-1-336d4794a3.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: ninja -v
    Working Directory: C:/Users/49091/vcpkg/buildtrees/bzip2/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\Users\49091\vcpkg\buildtrees\bzip2\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:345 (vcpkg_execute_required_process)
  ports/bzip2/portfile.cmake:16 (vcpkg_configure_cmake)
  scripts/ports.cmake:142 (include)


Error: Building package bzip2:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+bzip2
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[bzip2]+Build+error
including:
  package: bzip2[core]:x64-windows -> 1.0.8#2
    vcpkg-tool version: 2021-12-09-724cea8b33cbf06c645f5095fa29773697da9761
    vcpkg-scripts version: 772fe6cbc 2021-12-22 (3 days ago)

Additionally, attach any relevant sections from the log files above.

**Comment by JackBoosY** [comment]
Can you please provide _C:\Users\49091\vcpkg\buildtrees\bzip2\config-x64-windows-out.log_?

Thanks.

**Comment by jing-yao** [comment]
[1/2] cmd /c "cd .. && "C:/Users/49091/vcpkg/downloads/tools/cmake-3.21.1-windows/cmake-3.21.1-windows-i386/bin/cmake.exe" "C:/Users/49091/vcpkg/buildtrees/bzip2/src/bzip2-1-336d4794a3.clean" "-DCMAKE_MAKE_PROGRAM=C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/Users/49091/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v143" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/Users/49091/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_LINKER_FLAGS_RELEASE=" "-DVCPKG_LINKER_FLAGS_DEBUG=" "-DVCPKG_TARGET_ARCHITECTURE=x64" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=C:/Users/49091/vcpkg" "-DZ_VCPKG_ROOT_DIR=C:/Users/49091/vcpkg" "-D_VCPKG_INSTALLED_DIR=C:/Users/49091/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=C:/Users/49091/vcpkg/packages/bzip2_x64-windows""
FAILED: ../CMakeCache.txt 
cmd /c "cd .. && "C:/Users/49091/vcpkg/downloads/tools/cmake-3.21.1-windows/cmake-3.21.1-windows-i386/bin/cmake.exe" "C:/Users/49091/vcpkg/buildtrees/bzip2/src/bzip2-1-336d4794a3.clean" "-DCMAKE_MAKE_PROGRAM=C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/Users/49091/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v143" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/Users/49091/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_LINKER_FLAGS_RELEASE=" "-DVCPKG_LINKER_FLAGS_DEBUG=" "-DVCPKG_TARGET_ARCHITECTURE=x64" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=C:/Users/49091/vcpkg" "-DZ_VCPKG_ROOT_DIR=C:/Users/49091/vcpkg" "-D_VCPKG_INSTALLED_DIR=C:/Users/49091/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=C:/Users/49091/vcpkg/packages/bzip2_x64-windows""
-- The C compiler identification is MSVC 19.30.30706.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.30.30705/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.30.30705/bin/Hostx64/x64/cl.exe - broken
CMake Error at C:/Users/49091/vcpkg/downloads/tools/cmake-3.21.1-windows/cmake-3.21.1-windows-i386/share/cmake-3.21/Modules/CMakeTestCCompiler.cmake:69 (message):
  The C compiler

    "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.30.30705/bin/Hostx64/x64/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/Users/49091/vcpkg/buildtrees/bzip2/x64-windows-rel/CMakeFiles/CMakeTmp
    
    Run Build Command(s):C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe cmTC_cf4ec && [1/2] Building C object CMakeFiles\cmTC_cf4ec.dir\testCCompiler.c.obj
    [2/2] Linking C executable cmTC_cf4ec.exe
    FAILED: cmTC_cf4ec.exe 
    cmd.exe /C "cd . && C:\Users\49091\vcpkg\downloads\tools\cmake-3.21.1-windows\cmake-3.21.1-windows-i386\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_cf4ec.dir --rc=rc --mt=CMAKE_MT-NOTFOUND --manifests  -- C:\PROGRA~1\MICROS~2\2022\COMMUN~1\VC\Tools\MSVC\1430~1.307\bin\Hostx64\x64\link.exe /nologo CMakeFiles\cmTC_cf4ec.dir\testCCompiler.c.obj  /out:cmTC_cf4ec.exe /implib:cmTC_cf4ec.lib /pdb:cmTC_cf4ec.pdb /version:0.0 /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    RC Pass 1: command "rc /fo CMakeFiles\cmTC_cf4ec.dir/manifest.res CMakeFiles\cmTC_cf4ec.dir/manifest.rc" failed (exit code 0) with the following output:
    系统找不到指定的文件。
    ninja: build stopped: subcommand failed.
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)


-- Configuring incomplete, errors occurred!
See also "C:/Users/49091/vcpkg/buildtrees/bzip2/x64-windows-rel/CMakeFiles/CMakeOutput.log".
See also "C:/Users/49091/vcpkg/buildtrees/bzip2/x64-windows-rel/CMakeFiles/CMakeError.log".
[2/2] cmd /c "cd ../../x64-windows-dbg && "C:/Users/49091/vcpkg/downloads/tools/cmake-3.21.1-windows/cmake-3.21.1-windows-i386/bin/cmake.exe" "C:/Users/49091/vcpkg/buildtrees/bzip2/src/bzip2-1-336d4794a3.clean" "-DCMAKE_MAKE_PROGRAM=C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/Users/49091/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v143" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/Users/49091/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_LINKER_FLAGS_RELEASE=" "-DVCPKG_LINKER_FLAGS_DEBUG=" "-DVCPKG_TARGET_ARCHITECTURE=x64" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=C:/Users/49091/vcpkg" "-DZ_VCPKG_ROOT_DIR=C:/Users/49091/vcpkg" "-D_VCPKG_INSTALLED_DIR=C:/Users/49091/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF" "-DBZIP2_SKIP_HEADERS=ON" "-DBZIP2_SKIP_TOOLS=ON" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_INSTALL_PREFIX=C:/Users/49091/vcpkg/packages/bzip2_x64-windows/debug""
FAILED: ../../x64-windows-dbg/CMakeCache.txt 
cmd /c "cd ../../x64-windows-dbg && "C:/Users/49091/vcpkg/downloads/tools/cmake-3.21.1-windows/cmake-3.21.1-windows-i386/bin/cmake.exe" "C:/Users/49091/vcpkg/buildtrees/bzip2/src/bzip2-1-336d4794a3.clean" "-DCMAKE_MAKE_PROGRAM=C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/Users/49091/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v143" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/Users/49091/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_LINKER_FLAGS_RELEASE=" "-DVCPKG_LINKER_FLAGS_DEBUG=" "-DVCPKG_TARGET_ARCHITECTURE=x64" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=C:/Users/49091/vcpkg" "-DZ_VCPKG_ROOT_DIR=C:/Users/49091/vcpkg" "-D_VCPKG_INSTALLED_DIR=C:/Users/49091/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF" "-DBZIP2_SKIP_HEADERS=ON" "-DBZIP2_SKIP_TOOLS=ON" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_INSTALL_PREFIX=C:/Users/49091/vcpkg/packages/bzip2_x64-windows/debug""
-- The C compiler identification is MSVC 19.30.30706.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.30.30705/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.30.30705/bin/Hostx64/x64/cl.exe - broken
CMake Error at C:/Users/49091/vcpkg/downloads/tools/cmake-3.21.1-windows/cmake-3.21.1-windows-i386/share/cmake-3.21/Modules/CMakeTestCCompiler.cmake:69 (message):
  The C compiler

    "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.30.30705/bin/Hostx64/x64/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/Users/49091/vcpkg/buildtrees/bzip2/x64-windows-dbg/CMakeFiles/CMakeTmp
    
    Run Build Command(s):C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe cmTC_bcd52 && [1/2] Building C object CMakeFiles\cmTC_bcd52.dir\testCCompiler.c.obj
    [2/2] Linking C executable cmTC_bcd52.exe
    FAILED: cmTC_bcd52.exe 
    cmd.exe /C "cd . && C:\Users\49091\vcpkg\downloads\tools\cmake-3.21.1-windows\cmake-3.21.1-windows-i386\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_bcd52.dir --rc=rc --mt=CMAKE_MT-NOTFOUND --manifests  -- C:\PROGRA~1\MICROS~2\2022\COMMUN~1\VC\Tools\MSVC\1430~1.307\bin\Hostx64\x64\link.exe /nologo CMakeFiles\cmTC_bcd52.dir\testCCompiler.c.obj  /out:cmTC_bcd52.exe /implib:cmTC_bcd52.lib /pdb:cmTC_bcd52.pdb /version:0.0 /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    RC Pass 1: command "rc /fo CMakeFiles\cmTC_bcd52.dir/manifest.res CMakeFiles\cmTC_bcd52.dir/manifest.rc" failed (exit code 0) with the following output:
    系统找不到指定的文件。
    ninja: build stopped: subcommand failed.
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)


-- Configuring incomplete, errors occurred!
See also "C:/Users/49091/vcpkg/buildtrees/bzip2/x64-windows-dbg/CMakeFiles/CMakeOutput.log".
See also "C:/Users/49091/vcpkg/buildtrees/bzip2/x64-windows-dbg/CMakeFiles/CMakeError.log".
ninja: build stopped: subcommand failed.

**Comment by jing-yao** [comment]
`系统找不到指定的文件`  means `The system cannot find the specified file‘

**Comment by JackBoosY** [comment]
```
--mt=CMAKE_MT-NOTFOUND
```
Please make sure you've installed the English Language Package using Visual Studio Installer, and installed the required c++ Visual Studio Components.

**Comment by jing-yao** [comment]
Thank you very much！！The problem has been solved
