### ISSUE TITLE
[mlpack] Build error

### ISSUE THREAD

**Issue by GreatV** [microsoft/vcpkg#22208]
**Host Environment**
- OS: Windows10
- Compiler: MSVC 2022

**To Reproduce**
`./vcpkg install  mlpack[core,tools]:x64-windows`

**Failure logs** 
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/7776498/install-x64-windows-dbg-out.log)

**Additional context**
 - package: mlpack[core,tools]:x64-windows -> 3.4.1#4
 - vcpkg-tool version: 2021-12-09-724cea8b33cbf06c645f5095fa29773697da9761
 - vcpkg-scripts version: 772fe6cbc 2021-12-22 (3 days ago)

**Comment by JackBoosY** [comment]
```
D:\local\vcpkg\buildtrees\mlpack\src\82feaae439-787f7149b5.clean\src\mlpack\methods\preprocess\preprocess_describe_main.cpp(16): fatal error C1083: Cannot open include file: 'boost/format.hpp': No such file or directory
```
Please remove `boost-uninstall` then try again.

Thanks.

**Comment by GreatV** [comment]
I solved this problem by using

```
vcpkg install boost-format:x64-windows
```

**Comment by JackBoosY** [comment]
Please keep this issue open untill we fix it totally.
