### ISSUE TITLE
[New Port Request] Zeb

### ISSUE THREAD

**Issue by mjmucha** [microsoft/vcpkg#22203]
Library name: zep

Library description: Zep is a simple embeddable editor, with a rendering agnostic design and optional Vim mode. Out of the box Zep can draw to a Qt Widget or an an ImGui window - useful for embedding in a game engine.

Source repository URL: https://github.com/Rezonality/zep

Project homepage (if different from the source repository): N/A

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
