### ISSUE TITLE
How do I use getopt-win32 package

### ISSUE THREAD

**Issue by sergei-zykov** [microsoft/vcpkg#22215]
Hello.

Suppose, I've got getopt-win32 installed. There are other packages installed and worked, so it isn't an issue of integration.

> vcpkg install getopt-win32:x64-windows
> Computing installation plan...
> The following packages are already installed:
>     getopt-win32[core]:x64-windows -> 0.1#1
> Package getopt-win32:x64-windows is already installed
> 

Then I've added it to cmake

```
if(CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
    find_package(getopt-win32 REQUIRED)
    # .... irrelevant ......
endif()

```
It doesn't work:

```
1> [CMake] CMake Error at C:/Users/serge/repos/vcpkg/scripts/buildsystems/vcpkg.cmake:788 (_find_package):
1> [CMake]   By not providing "Findgetopt-win32.cmake" in CMAKE_MODULE_PATH this project
1> [CMake]   has asked CMake to find a package configuration file provided by
1> [CMake]   "getopt-win32", but CMake did not find one.
1> [CMake] 
1> [CMake]   Could not find a package configuration file provided by "getopt-win32" with
1> [CMake]   any of the following names:
1> [CMake] 
1> [CMake]     getopt-win32Config.cmake
1> [CMake]     getopt-win32-config.cmake
1> [CMake] 

```

**Comment by Osyotr** [comment]
For packages that don't provide cmake config you should manually search for includes and libraries.
https://github.com/microsoft/vcpkg/blob/master/docs/examples/installing-and-using-packages.md#handling-libraries-without-native-cmake-support

**Comment by sergei-zykov** [comment]
Still don't understand. There's no readme file with exact lines to add in cmake.
Post install message of getopt package doesn't clarify how to modify existing cmake project as well.
