### ISSUE TITLE
How do I install “Qt5 PrintSupport”?

### ISSUE THREAD

**Issue by nil-is-lin** [microsoft/vcpkg#22222]
I have installed qt5 with the command,  `./vcpkg.exe install qt5:x64-windows`, it runs well. 
However, it thow

> CMake Error at F:/workspace/vcpkg/scripts/buildsystems/vcpkg.cmake:540 (_add_executable):
 Target "XXX" links to target "Qt5::PrintSupport" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?		F:/workspace/vcpkg/scripts/buildsystems/vcpkg.cmake	540	

If `target_link_libraries(${PROJECT_NAME} PRIVATE Qt5::Widgets Qt5::Core Qt5::Gui )# Qt5::PrintSupport`, the cmakelists file configured well.  What's wrong? 

Win 10, cmake version 3.22.1, git pull with 'Already up to date'.

**Comment by JackBoosY** [comment]
cc @Neumann-A

**Comment by Neumann-A** [comment]
@JackBoosY Check the file list and see if you can figure it out?

@nil-is-lin You are probably missing the correct `find_package` call as the error says. (It should already be installed... but if you are not explicitly importing it it will not be found since you never searched for it.)

**Comment by nil-is-lin** [comment]
@Neumann-A  Thank you for your answer. Sure, I believe it already be installed. 
Maybe the keyword “PRIVATE” made this error?

**Comment by dg0yt** [comment]
Installing in vcpkg is not the same importing in your CMake project. In your CMake project, you need a proper `find_package` call to create a `Qt5::PrintSupport` target before you can use this target with `target_link_libraries`. See Qt5 and CMake documentation.

**Comment by Neumann-A** [comment]
`find_package(Qt5 COMPONENTS Core Widgets Gui PrintSupport)`.... really not an issue related to vcpkg

**Comment by nil-is-lin** [comment]
```
# find_package(Qt5 COMPONENTS Core Widgets Gui Concurrent PrintSupport CONFIG REQUIRED)
find_package(Qt5Core CONFIG REQUIRED)
find_package(Qt5Gui CONFIG REQUIRED)
find_package(Qt5OpenGL CONFIG REQUIRED)
find_package(Qt5Widgets CONFIG REQUIRED)
find_package(Qt5PrintSupport CONFIG REQUIRED)
```
I missed the last line of the code. I'm sorry for wasting everyone's time.
