### ISSUE TITLE
Print depend-info also if a package is not available for the target triplet

### ISSUE THREAD

**Issue by m-kuhn** [microsoft/vcpkg#22220]
****

**Is your feature request related to a problem? Please describe.**
I am trying to find out why a port fails to build when one of the dependencies is not available for the target triplet.

E.g; since updating vcpkg, the build fails with "libgcrypt[core] is only supported on 'linux | osx'"

To debug, I'd like to know how my build depends on this package:

```
$ .\vcpkg.exe depend-info qtkeychain:arm-android
Error: libgcrypt[core] is only supported on 'linux | osx'
```

Result:
Instead of the dependency tree, the error is shown again.

**Proposed solution**
It would be helpful if the dependency tree would still be shown, ideally with the affected packages visually flagged (e.g. shown in red).

```
...
libgcrypt: !Error: libgcrypt[core] is only supported on 'linux | osx'!
libsecret: glib, glib, libgcrypt, vcpkg-tool-meson
qtkeychain[translations]: libsecret, qt5-tools, vcpkg-cmake, vcpkg-cmake-config
```

**Comment by JackBoosY** [comment]
This was fixed in the latest vcpkg release, but not published.

**Comment by BillyONeal** [comment]
Fixed by https://github.com/microsoft/vcpkg/pull/22629
