### ISSUE TITLE
[boost-exception] cross-compilation build failure

### ISSUE THREAD

**Issue by Nemirtingas** [microsoft/vcpkg#22232]
**Host Environment**
- OS: Linux, Ubuntu 18
- Compiler: Clang-cl/LLVM 9

**To Reproduce**
Docker image build steps are described here: https://github.com/Nemirtingas/windowscross_vcpkg/tree/msvc2019_win10.0.18362.0

```
docker run --name windows -it nemirtingas/windowscross_vcpkg:msvc2019_win10.0.18362.0 bash

cd /
git clone https://github.com/microsoft/vcpkg --branch=master vcpkg_microsoft
cd vcpkg_microsoft
cat >triplets/community/x86-windows-clangcl.cmake <<EOF
set(VCPKG_TARGET_ARCHITECTURE x86)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE static)
if(PORT STREQUAL "portaudio")
    set(VCPKG_LIBRARY_LINKAGE dynamic)
endif()

set(VCPKG_BUILD_TYPE release)

set(ENV{HOST_ARCH} \${VCPKG_TARGET_ARCHITECTURE})

set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE /clang_windows_sdk/clang-cl-msvc.cmake)

set(ENV{VCPKG_TOOLCHAIN} "/vcpkg/scripts/toolchains/windows.cmake")
EOF
./bootstrap-vcpkg.sh
./vcpkg install boost-exception:x86-windows-clangcl
```

**Failure logs** 
```
Starting package 18/18: boost-exception:x86-windows-clangcl
Building package boost-exception[core]:x86-windows-clangcl...
-- Using community triplet x86-windows-clangcl. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: /vcpkg_microsoft/triplets/community/x86-windows-clangcl.cmake
-- Using cached boostorg-exception-boost-1.77.0.tar.gz.
-- Extracting source /vcpkg_microsoft/downloads/boostorg-exception-boost-1.77.0.tar.gz
-- Using source at /vcpkg_microsoft/buildtrees/boost-exception/src/ost-1.77.0-6531b39968.clean
-- Configuring x86-windows-clangcl-rel
-- Building x86-windows-clangcl-rel
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:155 (message):
    Command failed: /vcpkg_microsoft/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/bin/cmake --build . --config Release --target install -- -v -j3
    Working Directory: /vcpkg_microsoft/buildtrees/boost-exception/x86-windows-clangcl-rel
    See logs for more information:
      /vcpkg_microsoft/buildtrees/boost-exception/install-x86-windows-clangcl-rel-out.log

Call Stack (most recent call first):
  installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_build.cmake:102 (vcpkg_execute_build_process)
  installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
  installed/x64-linux/share/boost-build/boost-modular-build.cmake:105 (vcpkg_cmake_install)
  ports/boost-exception/portfile.cmake:15 (boost_modular_build)
  scripts/ports.cmake:142 (include)


Error: Building package boost-exception:x86-windows-clangcl failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `./vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-exception
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[boost-exception]+Build+error
including:
  package: boost-exception[core]:x86-windows-clangcl -> 1.77.0
    vcpkg-tool version: 2021-12-09-724cea8b33cbf06c645f5095fa29773697da9761
    vcpkg-scripts version: ae91542c8 2021-12-27 (21 hours ago)

```

**Additional context**
Boost is wrongly configured when building with something else than MSVC. I fixed the build with the following changes:

** Correctly setup boost configuration file **
https://github.com/Nemirtingas/vcpkg/commit/32043f59ba1be4b0830615bdac3fe95f767f8862#diff-6114a1d0526c9e9e3477ac321abfe1c9005f46441b01c5b1f5821f64f231721e

** Configure boost as MSVC when using Clang **
https://github.com/Nemirtingas/vcpkg/commit/32043f59ba1be4b0830615bdac3fe95f767f8862#diff-c077edde0f3fffc35a652c0f9c4e775256730d564700af914284ef6a5e90ecb3

**Comment by JackBoosY** [comment]
Can you please provide the logs in _VCPKG_ROOT/buildtrees/boost-exception_?

Thanks.

**Comment by Nemirtingas** [comment]
Hi,

I've filled the base issue infos like how to reproduce and errors, here are the build logs:
[boost-exception.tar.gz](https://github.com/microsoft/vcpkg/files/7785842/boost-exception.tar.gz)

**Comment by Nemirtingas** [comment]
Will you take a look even if its a "community-triplet" ? Its really only 2 lines to modify to handle clang-cl compilation.

**Comment by JackBoosY** [comment]
```
cmd.exe: not found
```
The toolchain should be fixed.

**Comment by Nemirtingas** [comment]
The toolchain does not ship cmd.exe because its on Ubuntu, not Windows. And cmd.exe is called only because the wrong b2 configuration is loaded because of https://github.com/Nemirtingas/vcpkg/commit/32043f59ba1be4b0830615bdac3fe95f767f8862#diff-6114a1d0526c9e9e3477ac321abfe1c9005f46441b01c5b1f5821f64f231721e
If its clang-win, cmd.exe is not called and everything compiles fine.

**Comment by Nemirtingas** [comment]
So, I guess you won't take any further look at it ?

**Comment by JackBoosY** [comment]
> The toolchain does not ship cmd.exe because its on Ubuntu, not Windows

But the triplet you used is `x86-windows-clangcl`?

**Comment by Nemirtingas** [comment]
Yes, its my custom triplet to cross-compile a Windows library/executable on Ubuntu.

**Comment by JackBoosY** [comment]
Now we only have a tool chain from Windows to Linux, but no tool chain from Linux to Windows.

**Comment by Nemirtingas** [comment]
Yes. Still I think boost's B2 should be configured to use clang-win when using clang instead of always configure boost for MSVC, no matter the OS.

**Comment by JackBoosY** [comment]
It is in the judgment `if(MSVC)`, so I think it does not matter, we should change the code in another condition.

**Comment by Nemirtingas** [comment]
MSVC is also set when using clang as a compiler.

**Comment by Nemirtingas** [comment]
MSVC is still set when using clang-cl: https://cmake.org/cmake/help/latest/variable/MSVC.html
It seems to me that is the expected behavior. But when using clang, you have some differences:
When using MSVC
```
CMAKE_C_COMPILER_ID=MSVC
```

When using Clang-cl:
```
CMAKE_C_COMPILER_ID=Clang 
CMAKE_C_COMPILER_FRONTEND_VARIANT=MSVC
CMAKE_CXX_COMPILER_ID=Clang
CMAKE_CXX_COMPILER_FRONTEND_VARIANT=MSVC
```

I dumped all CMake variables using the following CMakeLists.txt:
```
cmake_minimum_required(VERSION 3.19)

project(cmake_variables)

get_cmake_property(_variableNames VARIABLES)
list (SORT _variableNames)
foreach (_variableName ${_variableNames})
    message(STATUS "${_variableName}=${${_variableName}}")
endforeach()
```

**Comment by JackBoosY** [comment]
I'm not familiar with clang-cl, but we can't use Visual Studio in Linux anyway, can we?

**Comment by Nemirtingas** [comment]
There is Visual Studio Code that should work on Linux. It depends on what you want to achieve.

**Comment by JackBoosY** [comment]
Visual Studio Code is different with Visual Studio since it doesn't contain the compiler.
If we use `clang-cl`, it is assumed that `cl` must exist, right?

**Comment by Nemirtingas** [comment]
No, cl is not mandatory, clang-cl is the frontend that accepts the same parameters as cl so users don't have to change their compilation options. Like lld-link that accept the same parameters as link.exe, llvm-rc, and so one.

**Comment by JackBoosY** [comment]
I'm very confused. `MSVC` means that cl.exe was selected using clang-cl, but this is not necessarily the case here?
`WIN32` should include `MSVC`, not the other way around.

**Comment by Nemirtingas** [comment]
MSVC means the compiler is cl.exe or another compiler that emulates cl.exe's behavior. WIN32 can be defined but not MSVC when you build with MinGW for example. Clang-cl is the clang compiler but its can handle cl.exe's options format (like /H- and such) while clang.exe can also build for Windows but can't handle cl.exe's options.

**Comment by JackBoosY** [comment]
So https://github.com/microsoft/vcpkg/blob/1085a57da0725c19e19586025438e8c16f34c890/ports/boost-modular-build-helper/CMakeLists.txt#L54-L74
Should be:
```cmake
if(WIN32)
    if(MSVC)
        set(USER_CONFIG_TOOLSET msvc)
        if(MSVC_VERSION LESS 1900)
            math(EXPR USER_CONFIG_TOOLSET_VERSION "${MSVC_VERSION} / 10 - 60")
        else()
            math(EXPR USER_CONFIG_TOOLSET_VERSION "${MSVC_VERSION} / 10 - 50")
        endif()
    else()
        set(USER_CONFIG_TOOLSET gcc)
    endif()
    list(APPEND B2_OPTIONS target-os=windows)
elseif(APPLE)
    set(USER_CONFIG_TOOLSET clang)
    list(APPEND B2_OPTIONS target-os=darwin)
elseif(ANDROID)
    set(USER_CONFIG_TOOLSET gcc)
    list(APPEND B2_OPTIONS target-os=android)
else()
    if(MSVC)
        set(USER_CONFIG_TOOLSET clang)
    else()
        set(USER_CONFIG_TOOLSET gcc)
    endif()
    list(APPEND B2_OPTIONS target-os=linux)
endif()
```
right?

**Comment by Nemirtingas** [comment]
No, because when you cross-compile for Windows, CMake sets WIN32 too, because its not the host arch that is checked, its the target arch.
https://cmake.org/cmake/help/latest/variable/WIN32.html

You can't target clang for Windows according to clang.jam:
```
# This is a generic 'clang' toolset. Depending on the current system, it
# forwards either to 'clang-linux' or 'clang-darwin' modules.
```
So you will have to explicitly use clang-win.jam.

```
if(WIN32)
    if(MSVC)
        if (CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
            if(CMAKE_CXX_COMPILER_FRONTEND_VARIANT STREQUAL "MSVC")
                set(USER_CONFIG_TOOLSET clang-win)
            else(CMAKE_CXX_COMPILER_FRONTEND_VARIANT STREQUAL "GCC")
                set(USER_CONFIG_TOOLSET gcc)
            else()
                message(FATAL_ERROR "Unknown clang frontend")
            endif()
        else(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
            set(USER_CONFIG_TOOLSET msvc)
        endif()
        if(MSVC_VERSION LESS 1900)
            math(EXPR USER_CONFIG_TOOLSET_VERSION "${MSVC_VERSION} / 10 - 60")
        else()
            math(EXPR USER_CONFIG_TOOLSET_VERSION "${MSVC_VERSION} / 10 - 50")
        endif()
    else()
        set(USER_CONFIG_TOOLSET gcc)
    endif()
    list(APPEND B2_OPTIONS target-os=windows)
elseif(APPLE)
    set(USER_CONFIG_TOOLSET clang)
    list(APPEND B2_OPTIONS target-os=darwin)
elseif(ANDROID)
    set(USER_CONFIG_TOOLSET gcc)
    list(APPEND B2_OPTIONS target-os=android)
else()
    if (CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
        set(USER_CONFIG_TOOLSET clang)
    else()
        set(USER_CONFIG_TOOLSET gcc)
    endif()
    list(APPEND B2_OPTIONS target-os=linux)
endif()
```

**Comment by dg0yt** [comment]
Is there a `MSVC` with `CMAKE_CXX_COMPILER_FRONTEND_VARIANT STREQUAL "GNU"`?

**Comment by JackBoosY** [comment]
@Nemirtingas Can you please make a PR to commit that?

Thanks.

**Comment by Nemirtingas** [comment]
> Is there a `MSVC` with `CMAKE_CXX_COMPILER_FRONTEND_VARIANT STREQUAL "GNU"`?

I just tested that, it doesn't seem to have MSVC set when using Clang on Windows with GNU frontend (clang.exe and clang++.exe as compilers):
```
-- CMAKE_CXX_COMPILER_FRONTEND_VARIANT=GNU
-- CMAKE_CXX_COMPILER_ID=Clang
-- CMAKE_C_COMPILER_FRONTEND_VARIANT=GNU
-- CMAKE_C_COMPILER_ID=Clang
-- WIN32=1
```

With clang-cl.exe as C and CXX compilers:
```
-- CMAKE_CXX_COMPILER_FRONTEND_VARIANT=MSVC
-- CMAKE_CXX_COMPILER_ID=Clang
-- CMAKE_C_COMPILER_FRONTEND_VARIANT=MSVC
-- CMAKE_C_COMPILER_ID=Clang
-- MSVC=1
-- WIN32=1
```

So I believe it should be:
```
if(WIN32)
    if(MSVC)
        if (CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
            if(CMAKE_CXX_COMPILER_FRONTEND_VARIANT STREQUAL "MSVC")
                set(USER_CONFIG_TOOLSET clang-win)
            else()
                message(FATAL_ERROR "Unknown Clang frontend: ${CMAKE_CXX_COMPILER_FRONTEND_VARIANT}")
            endif()
        else(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
            set(USER_CONFIG_TOOLSET msvc)
        endif()
        if(MSVC_VERSION LESS 1900)
            math(EXPR USER_CONFIG_TOOLSET_VERSION "${MSVC_VERSION} / 10 - 60")
        else()
            math(EXPR USER_CONFIG_TOOLSET_VERSION "${MSVC_VERSION} / 10 - 50")
        endif()
    else()
        if(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
            if(CMAKE_CXX_COMPILER_FRONTEND_VARIANT STREQUAL "GNU")
                # I'm not sure if the toolset is gcc or clang here
                set(USER_CONFIG_TOOLSET clang)
            else()
                message(FATAL_ERROR "Unknown Clang frontend: ${CMAKE_CXX_COMPILER_FRONTEND_VARIANT}")
            endif()
        else()
            set(USER_CONFIG_TOOLSET gcc)
        endif()
    endif()
    list(APPEND B2_OPTIONS target-os=windows)
elseif(APPLE)
    set(USER_CONFIG_TOOLSET clang)
    list(APPEND B2_OPTIONS target-os=darwin)
elseif(ANDROID)
    set(USER_CONFIG_TOOLSET gcc)
    list(APPEND B2_OPTIONS target-os=android)
else()
    if (CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
        set(USER_CONFIG_TOOLSET clang)
    else()
        set(USER_CONFIG_TOOLSET gcc)
    endif()
    list(APPEND B2_OPTIONS target-os=linux)
endif()
```

??

**Comment by Nemirtingas** [comment]
> @Nemirtingas Can you please make a PR to commit that?
> 
> Thanks.

Ok, I made a Draft PR for now: https://github.com/microsoft/vcpkg/pull/22274. So we can check its content before trying to merge it.

**Comment by PhoebeHui** [comment]
>Since CMake 3.15 we support both the `clang++` and `clang-cl` tools that target the MSVC ABI. The `CMAKE_<LANG>_COMPILER_FRONTEND_VARIANT` variable is used to distinguish them internally,

Reference https://gitlab.kitware.com/cmake/cmake/-/issues/19724
