### ISSUE TITLE
[fontconfig] Build fail on x86-windows

### ISSUE THREAD

**Issue by flyingyizi** [microsoft/vcpkg#22239]
**Host Environment**
- OS: Windows 10   fontconfig[core]:x86-windows
- Compiler: Microsoft Visual Studio 2022 Community
- vcpkg port:  latest
- 
**To Reproduce**
`.\vcpkg install fontconfig`

**Failure logs** 
...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: C:/tools/vcpkg/downloads/tools/ninja/1.10.2-windows/ninja.exe install -v
    Working Directory: C:/tools/vcpkg/buildtrees/fontconfig/x86-windows-rel
    Error code: 1
    See logs for more information:
      C:\tools\vcpkg\buildtrees\fontconfig\package-x86-windows-rel-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_meson.cmake:53 (vcpkg_execute_required_process)
  ports/fontconfig/portfile.cmake:21 (vcpkg_install_meson)
  scripts/ports.cmake:142 (include)
...

**Additional context**

[package-x86-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/7786222/package-x86-windows-rel-out.log)

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. I can't reproduce this issue locally with Visual Studio 2022. I found this eror message in your log:
```
FAILED: install script 'C:\tools\vcpkg\buildtrees\fontconfig\x86-windows-rel\fc-cache\fc-cache.exe -s -f -v' exit code 3221225785, stopped
FAILED: meson-install 
```
According to comment https://github.com/microsoft/vcpkg/pull/21026#issuecomment-954613467, that's a pixman bug, you can try the workaround: https://github.com/microsoft/vcpkg/issues/17956#issuecomment-841861734.

**Comment by LilyWangLL** [comment]
@flyingyizi Does this issue still exist?

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
