### ISSUE TITLE
[libmariadb] Build error

### ISSUE THREAD

**Issue by lsqtzj** [microsoft/vcpkg#22249]
**Host Environment**
- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**
vcpkg install libmysql:x64-windows
vcpkg install libmariadb[core]:x64-windows
![image](https://user-images.githubusercontent.com/4635861/147688956-c5b7dba3-0f48-4e9f-939b-02f18bba905c.png)

**Failure logs** 
-Cut and paste the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by dg0yt** [comment]
Your sceenshot doesn't show the error message. And probably it has information for you.

**Comment by LilyWangLL** [comment]
@lsqtzj Thanks for posting this issue. Could you please provide the error log?

**Comment by lolo32** [comment]
Hi @lsqtzj,

I just have the same error, and the solution is in the error message.
I got it after some upgrade, maybe another options in the past.

Here is my error:
```
Building package libmariadb[core,openssl,schannel,ssl,zlib]:x64-windows-static...
CMake Error at ports/libmariadb/portfile.cmake:6 (message):
  Only one SSL backend must be selected.
Call Stack (most recent call first):
  scripts/ports.cmake:142 (include)


Error: Building package libmariadb:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libmariadb
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[libmariadb]+Build+error
including:
  package: libmariadb[core,openssl,schannel,ssl,zlib]:x64-windows-static -> 3.1.15
    vcpkg-tool version: 2021-12-09-724cea8b33cbf06c645f5095fa29773697da9761
    vcpkg-scripts version: e2a231775 2022-01-04 (2 hours ago)

Additionally, attach any relevant sections from the log files above.
```
The error came from `Only one SSL backend must be selected.`, and after checked, it tried to compile it with these 3 backend: `openssl,schannel,ssl`.

After left only one (either openssl or schannel or ssl), it compiled like a charm and worked.

**Comment by JonLiu1993** [comment]
@lsqtzj ,Thanks for posting this issue, please use @lolo32's suggestion to try if it can be solved, if you still have problems, please reopen the issue

**Comment by JackBoosY** [comment]
```
Only one SSL backend must be selected.
```
As the error message said: you should only pick one of the ssl features.
