### ISSUE TITLE
[embree3] wrong fatal error

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#22240]
https://github.com/microsoft/vcpkg/blob/2689f785c9dbc02d714e2c3824a42c80ac58a8f8/ports/embree3/portfile.cmake#L21

seems wrong. There is an `/ARCH:AVX512` flag in VS. The question is rather if embree3 supports it with VS. In my opinion it should be at least reduced to a warning.

**Comment by JackBoosY** [comment]
Confirmed, Visual Studio 2017 or later supports `/ARCH:AVX512`.
But this is written in the [upstream configure](https://github.com/embree/embree/blob/master/CMakeLists.txt#L201-L203):
```cmake
    IF (EMBREE_ISA_AVX512)
      MESSAGE(FATAL_ERROR "Microsoft Visual C++ Compiler does not support AVX512. Please use Intel Compiler or Clang.")
    ENDIF()
```
I will report this to the upstream laster.

**Comment by JackBoosY** [comment]
Close this PR until upstream fixes this.

**Comment by JackBoosY** [comment]
Looks like the upstream already support AVX512 in the latest version.
