### ISSUE TITLE
[New Port Request] libomp[OpenMP]

### ISSUE THREAD

**Issue by Cook21** [microsoft/vcpkg#22241]
Library name: 
libomp

Library description: 
OpenMP subproject of LLVM

Source repository URL: 
https://github.com/llvm/llvm-project/tree/main/openmp

Project homepage: 
https://openmp.llvm.org

Anything else that is useful to know when adding:
The toolchain that shipped with MacOS doesn't contain the OpenMP library, In order to use it, I have to run `brew install libomp`. Wish I can add it into `vcpkg.json` instead of  manually install it using system level package manager.

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
