### ISSUE TITLE
[boost-regex] build failure

### ISSUE THREAD

**Issue by kzq0717** [microsoft/vcpkg#22243]
install boost:x64-windows  appear quesion
![2021-12-29_110935](https://user-images.githubusercontent.com/51390506/147623775-2b87e70f-3b51-4e2f-9fc1-8d375184e9f6.png)

**Comment by PhoebeHui** [comment]
@kzq0717, could you execute './vcpkg remove boost-uninstall:x64-windows --recurse' and try again?

**Comment by PhoebeHui** [comment]
@kzq0717, does this still be a problem for you? boost-modular-build should exist after boost-modular-build-helper port installed, So in your case, the file can't be found by some reason, the quick solution is remove the old version and reinstall it.

**Comment by JackBoosY** [comment]
Ping for response.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
