### ISSUE TITLE
OpenVDB update to 9.0

### ISSUE THREAD

**Issue by cgolchert** [microsoft/vcpkg#22255]
Library name: OpenVDB

New version number:  -----> **9.0** <-----

Other information that may be useful (release notes, etc...)

#21095

For some reason the previous request was closed because a keyword in the 8.2.0 notes triggered a closure.

> Is your feature request related to a problem? Please describe.
> The openVDB port is now two full versions behind the current release. NanoVDB has also been officially released as part of V9.0 to allow for GPU support.
> 
> Proposed solution
> Update the vcpkg version would...well...make the library up-to-date.
> 
> Describe alternatives you've considered
> Waiting so far hasn't gotten it updated so I am putting this request in.
> 
> Additional context
> V9.0:
> NanoVDB, which offers GPU support
> Improved compilation times
> Support for OpenEXR version 3

**Comment by JonLiu1993** [comment]
@cgolchert ,The issue #21095 has been reopened, this issue is repeated, so I will close it
