### ISSUE TITLE
vcpkg windows XP

### ISSUE THREAD

**Issue by alroyso** [microsoft/vcpkg#2225]
CMake Error at CMakeLists.txt:47 (project):
  Generator

    Ninja

  does not support toolset specification, but toolset

    v141_xp

  was specified.

CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage

**Comment by how0723** [comment]
change to win10 version

**Comment by alroyso** [comment]
CMAKE?

**Comment by how0723** [comment]
change your operating system to win7 or win10 version

**Comment by alroyso** [comment]
I am a win10 system

**Comment by how0723** [comment]
if the English language pack is not installed, vcpkg compilation will fail

**Comment by alroyso** [comment]
Is a system language package

**Comment by how0723** [comment]
right

**Comment by alroyso** [comment]
I have a language pack

**Comment by alroyso** [comment]
I downloaded VCPKG support WINDOWS XP version of the official version of the compiler is normal But the translation of the things do not support XP

**Comment by alroyso** [comment]
How to support xp

**Comment by how0723** [comment]
using vc6.0

**Comment by alroyso** [comment]
vs2017 compiler support XP

**Comment by how0723** [comment]
maybe you did not installed correctly

**Comment by gggin** [comment]
Ninja Generator is not support x64 or v140_xp or 141_xp.
So anyone find a way to support ?

**Comment by JackBoosY** [comment]
Related: #2580.

**Comment by NancyLi1013** [comment]
It's duplicated to #1015.
