### ISSUE TITLE
vcpkg install libmysql:x64-windows  fail!

### ISSUE THREAD

**Issue by 1647606255** [microsoft/vcpkg#22261]
```
C:\Users\ssit>vcpkg install libmysql:x64-windows
Computing installation plan...
The following packages will be built and installed:
    libmysql[core]:x64-windows -> 8.0.20#2
Warning: The following VS instances are excluded because the English language pack is unavailable.
    C:\Program Files (x86)\Microsoft Visual Studio 12.0\
Please install the English language pack.
Detecting compiler hash for triplet x64-windows...
-- Automatically setting HTTP(S)_PROXY environment variables to 127.0.0.1:7890
Could not locate cached archive: C:\Users\ssit\AppData\Local\vcpkg\archives\15\157bdc5bc61531bd2ee32c40405680050f3eedfe.zip
Starting package 1/1: libmysql:x64-windows
Building package libmysql[core]:x64-windows...
-- Using D:/DevelopmentTool/vcpkg-master/downloads/mysql-mysql-server-7d10c82196c8e45554f27c00681474a9fb86d137.tar.gz
-- Cleaning sources at D:/DevelopmentTool/vcpkg-master/buildtrees/libmysql/src/a9fb86d137-9c03d2b524.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/DevelopmentTool/vcpkg-master/downloads/mysql-mysql-server-7d10c82196c8e45554f27c00681474a9fb86d137.tar.gz
-- Applying patch ignore-boost-version.patch
-- Applying patch system-libs.patch
-- Applying patch rename-version.patch
-- Applying patch export-cmake-targets.patch
-- Using source at D:/DevelopmentTool/vcpkg-master/buildtrees/libmysql/src/a9fb86d137-9c03d2b524.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Restarting Build without parallelism because memory exceeded
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:146 (message):
    Command failed: D:/DevelopmentTool/vcpkg-master/downloads/tools/cmake-3.20.2-windows/cmake-3.20.2-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j5
    Working Directory: D:/DevelopmentTool/vcpkg-master/buildtrees/libmysql/x64-windows-dbg
    See logs for more information:
      D:\DevelopmentTool\vcpkg-master\buildtrees\libmysql\install-x64-windows-dbg-out.log
      D:\DevelopmentTool\vcpkg-master\buildtrees\libmysql\install-x64-windows-dbg-out-1.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:104 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:44 (vcpkg_build_cmake)
  ports/libmysql/portfile.cmake:70 (vcpkg_install_cmake)
  scripts/ports.cmake:139 (include)


Error: Building package libmysql:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libmysql:x64-windows
  Vcpkg version: 2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9

Additionally, attach any relevant sections from the log files above
```

**Comment by PhoebeHui** [comment]
@1647606255, could you please provide the failure logs?
D:\DevelopmentTool\vcpkg-master\buildtrees\libmysql\install-x64-windows-dbg-out.log
D:\DevelopmentTool\vcpkg-master\buildtrees\libmysql\install-x64-windows-dbg-out-1.log

**Comment by 1647606255** [comment]
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/7792651/install-x64-windows-dbg-out.log)
[install-x64-windows-dbg-out-1.log](https://github.com/microsoft/vcpkg/files/7792652/install-x64-windows-dbg-out-1.log)

**Comment by Cheney-W** [comment]
`LINK : fatal error LNK1104: cannot open file 'runtime_output_directory\conf_to_src.exe'`
I can't reproduce this issue in my side, I used VS2019 16.11.8 and vcpkg: 2021-12-09-724cea8b33cbf06c645f5095fa29773697da9761. 
Also, the latest version of libmysql is 8.0.20#5, could you please update your vcpkg and re-install this port with following command:
`.\vcpkg.exe install libmysql:x64-windows --debug --binarysource=clear`
Thank you!

**Comment by PhoebeHui** [comment]
I noticed the failure in your machine. Could you add DISABLE_PARALLEL to https://github.com/microsoft/vcpkg/blob/master/ports/libmysql/portfile.cmake#L68 and try again?

Failure:
```
-- Restarting Build without parallelism because memory exceeded
```

**Comment by 1647606255** [comment]
> I noticed the failure in your machine. Could you add DISABLE_PARALLEL to https://github.com/microsoft/vcpkg/blob/master/ports/libmysql/portfile.cmake#L68 and try again?
> 
> Failure:
> 
> ```
> -- Restarting Build without parallelism because memory exceeded
> ```


Add  -DISABLE_PARALLEL=OFF
it is ok now ! Thanks!

**Comment by dg0yt** [comment]
> > I noticed the failure in your machine. Could you add DISABLE_PARALLEL to https://github.com/microsoft/vcpkg/blob/master/ports/libmysql/portfile.cmake#L68 and try again?
> > Failure:
> > ```
> > -- Restarting Build without parallelism because memory exceeded
> > ```

Note that this means that vcpkg already retried building without parallelism.

> Add -DISABLE_PARALLEL=OFF it is ok now ! Thanks!

`DISABLE_PARALLEL` was meant to be used literally as an option to `vcpkg_cmake_install`. (But all it would change is that vcpkg would build that port immediately without parallelism - but it already tried that before.)

**Comment by JackBoosY** [comment]
The reserved memory is too small that even vcpkg use no parallel build command, your spare memory still down to zero.

**Comment by PhoebeHui** [comment]
>Note that this means that vcpkg already retried building without parallelism.

Yes, https://github.com/microsoft/vcpkg/blob/master/scripts/cmake/vcpkg_execute_build_process.cmake#L86-L108.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
