### ISSUE TITLE
installed directory is not created when multiple projects have the same path

### ISSUE THREAD

**Issue by elad8a** [microsoft/vcpkg#22265]
I use manifest files (vcpkg.json) with Visual Studio 2022 solution that contains multiple projects.

I would like all the libraries that are installed automatically to be located in the same directory **for all projects in the solution**.
So I changed the "Installed Directory" property to point to the desired location:

![image](https://user-images.githubusercontent.com/17446835/147788829-3a78132f-85d6-4f13-bf53-be2796c3ab0f.png)

The first project I build seems to install its libraries and build just fine. But other projects fail to invoke the libraries installation and the build fails.
If I give each project a unique "Installed Directory" path for its dependencies, it works just fine.

**Comment by autoantwort** [comment]
> I would like all the libraries that are installed automatically to be located in the same directory for all projects in the solution.

That is the default, so resetting the value to the default should work (Only works if you only have one manifest file, multiple manifest files can not share the installation dir).

**Comment by JackBoosY** [comment]
> > I would like all the libraries that are installed automatically to be located in the same directory for all projects in the solution.
> 
> That is the default, so resetting the value to the default should work (Only works if you only have one manifest file, multiple manifest files can not share the installation dir).

Maybe set an absolute path?

**Comment by elad8a** [comment]
@autoantwort @JackBoosY  why multiple manifest files can not share the installation dir? What is the proper way to reduce the space overhead of the installation dir? I have multiple copies of the same solution, and within each solution each project has its own installation dir. The amount of space it takes is enormous compared to what it used to be before using manifest files.

**Comment by autoantwort** [comment]
> why multiple manifest files can not share the installation dir?

Because the manifest file describes what should be in the installation dir. If you have different manifest files and a shared installation dir, each install would remove the stuff from the previous install. 

> What is the proper way to reduce the space overhead of the installation dir? 

Use only one manifest file at the root of the solution.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
