### ISSUE TITLE
[pffft] Support building for non-static triplets

### ISSUE THREAD

**Issue by oracleoftroy** [microsoft/vcpkg#22277]
I typically build with x64-windows. Many ports don't support dynamic linking and will issue a warning in that case. Pffft accomplishes this with `vcpkg_check_linkage(ONLY_STATIC_LIBRARY)` at the top of portfile.cmake.

But the pffft port also adds `"supports": "static"` to its vcpkg.json file, which had the effect of completely preventing building on any non-static triplets. Removing this line seemed to work on my machine, but I don't know what other consequences removing that may have.

As there is no obvious reason to prevent linking to static only libraries even when dynamic linking is ok, pffft should do as other ports do and allow that use case.

**Comment by LilyWangLL** [comment]
Fixed by PR #25403.
