### ISSUE TITLE
How do I specify an alternative to vcpkg_installed directory via CMakePresets.json?

### ISSUE THREAD

**Issue by eladmaimoni** [microsoft/vcpkg#22279]
I tried to use VCPKG_INSTALL_OPTIONS in the following manner but it fails:

```
        "cacheVariables": {
            "CMAKE_C_COMPILER": "cl.exe",
            "CMAKE_CXX_COMPILER": "cl.exe",
            "CMAKE_BUILD_TYPE": "Debug",
            "CMAKE_INSTALL_PREFIX": "${sourceDir}/out/install/${presetName}",
            "CMAKE_TOOLCHAIN_FILE": {
                "value": "$env{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake",
                "type": "FILEPATH"
            },
            "VCPKG_INSTALL_OPTIONS": "--x-install-root=${sourceDir}/packages",
            "VCPKG_TARGET_TRIPLET": "x64-windows-static-md"
        },

```

I get the following error message:

`[CMake] Error: --x-install-root specified multiple times`

So how do I specify an alternative to vcpkg_installed directory via CMakePresets.json?

**Comment by elad8a** [comment]
I found an undocumented (?) option:

"VCPKG_INSTALLED_DIR" : "${sourceDir}/packages"

**Comment by JackBoosY** [comment]
> I found an undocumented (?) option:
> 
> "VCPKG_INSTALLED_DIR" : "${sourceDir}/packages"

You can only set the installed path using `--x-install-root`, not `VCPKG_INSTALLED_DIR`.

**Comment by elad8a** [comment]
@JackBoosY can you provide us with a working example of **how** to use` --x-install-root`?

**Comment by dg0yt** [comment]
> I get the following error message:
> 
> `[CMake] Error: --x-install-root specified multiple times`

The vcpkg CMake toolchain file already passes the `--x-install-root` parameter to the vcpkg tool when dealing with the manifest:

https://github.com/microsoft/vcpkg/blob/abf52dd1adb482e21fb89d1125d4fed6b79dfc07/scripts/buildsystems/vcpkg.cmake#L492-L506

> > I found an undocumented (?) option:
> > "VCPKG_INSTALLED_DIR" : "${sourceDir}/packages"

This does indeed change the value of `_VCPKG_INSTALLED_DIR` which is used as value for  `--x-install-root`.

But I assume it is not intented to be modified. The default choice, a subdirectory of your CMake build directory is a reasonable choice for manifest mode IMO. If you want to share one install directory for multiple installations, you can/must do this in classic mode.

**Comment by Osyotr** [comment]
I'm using `"VCPKG_INSTALLED_DIR": "${sourceParentDir}/vcpkg_installed"` to make sure the folder won't be removed by rsync.
@dg0yt build dir is OK only for multiconfig generators. Otherwise you end up with two copies of vcpkg_installed folder.

**Comment by dg0yt** [comment]
> I'm using `"VCPKG_INSTALLED_DIR": "${sourceParentDir}/vcpkg_installed"` to make sure the folder is not removed by rsync.

AFAICT rsync is not used in vcpkg.

> @dg0yt build dir is OK only for multiconfig generators. Otherwise you end up with two copies of vcpkg_installed folder.

AFAICT it is not related to the generator. The two copies come from `vcpkg install` being used manually in the source directory, in addition to the automated call at CMake runtime.

**Comment by Osyotr** [comment]
There are two configure presets in our `CMakePresets.json`: x64-windows-debug and x64-windows-release. But use Ninja generator (_not_ multiconfig, as Visual Studio doesn't support it yet). The respective output folders are:
`_project_folder_/out/build/x64-windows-debug`
`_project_folder_/out/build/x64-windows-release`
By default, each of these folders will contain a copy of `vcpkg_installed` which is a waste of space.
Possible solution is to set `"VCPKG_INSTALLED_DIR": "${sourceDir}/out/vcpkg_installed"`.
Now, imagine you use Visual Studio to build an app on remote host (WSL or Linux via ssh). VS uses rsync to synchronize sources between local host and remote host. I don't really know why, but sometimes VS just removes `out/` folder on remote host before running cmake cache generation. `vcpkg_installed` folder, of course, is also removed and you end up in situation where small change in `CMakeLists.txt` would require waiting for `vcpkg install` and subsequently full rebuild of the project.
My workaround is to set `VCPKG_INSTALLED_DIR` somewhere outside the project so it is kept even after removing cmake cache.

**Comment by jimwang118** [comment]
Thanks for the user's reply, this issue has been resolved in the reply, I will close this issue.

**Comment by justusranvier** [comment]
> The default choice, a subdirectory of your CMake build directory is a reasonable choice for manifest mode IMO.

This would be fine if Windows wasn't such a cursed operating system with its 260 character MAX_PATH limitation inherited from MS-DOS.

Troubleshooting build issues with qtdeclarative related to this is hell because so many seemingly minor differences between the environments of one developer and another developer determine whether or not that limit is exceeded and thus who gets a successful build and who gets an incomprehensible error message.
