### ISSUE TITLE
[vcpkg upgrade][vcpkg-tool-meson[core]] build failure "vcpkg-tool-meson[core] is only supported on 'native'"

### ISSUE THREAD

**Issue by MarkCallow** [microsoft/vcpkg#22278]
**Host Environment**
- OS: macOS 12.1 (Monterey)
- Compiler: Xcode 13.2.1 / Apple clang version 13.0.0 (clang-1300.0.29.30)

**To Reproduce**
`git pull` # to update to tip of tree `master`. I'm at commit 1085a57da0725c19e19586025438e8c16f34c890
`./bootstrap-vcpkg.sh`
`./vcpkg upgrade`

I did the bootstrap-vcpkg because on my first attempt at `./vcpkg-upgrade` I got

```
Errors occurred while parsing /Users/mark/Projects/github/vcpkg/ports/glib/vcpkg.json
    $.features.libmount (a feature): unexpected field 'supports', did you mean 'description'?
Error: failed to load port from /Users/mark/Projects/github/vcpkg/ports/glib
Note: Updating vcpkg by rerunning bootstrap-vcpkg may resolve this failure.
```

**Failure logs** 
```
Error: vcpkg-tool-meson[core] is only supported on 'native'
```

**Additional context**

I have various triplets of only OpenImageIO and its dependencies installed including x64-osx which is native for my hardware. (I do not recall meson being one of those dependencies.) I then tried explicitly specifying the triplet

```
./vcpkg upgrade --triplet x64-osx
```

but I get the same error.

I'm not sure if this is a package build failure or an issue with vcpkg itself.

**Comment by JackBoosY** [comment]
cc @Neumann-A

**Comment by MFRSiam** [comment]
+1 this , i was just trying to update my installed packages using vcpkg upgrade then 
```Error: vcpkg-tool-meson[core] is only supported on 'native'``` 
showed
![image](https://user-images.githubusercontent.com/12758535/147875306-5cf9a3fa-a951-4aac-b37e-17fbaec4cf4b.png)

**Comment by Neumann-A** [comment]
Vcpkg-tool-meson is a host tool only so native is correct. Either a port is missing a host: true for the dependency or there is a bug in vcpkg upgrade

**Comment by JackBoosY** [comment]
Ah...yes that's a vcpkg bug.

**Comment by MarkCallow** [comment]
Please get this fixed quickly.

I've been unable to use vcpkg for almost 3 months. First due to a bug in the rewriting of the cmake files in the package I want to use, that caused configured builds to fail, and now because I can't run `vcpkg --upgrade` to get the fix for that. I'm ready to give up and find an alternate solution.

**Comment by Neumann-A** [comment]
How about not using `vcpkg upgrade`?  Use `vcpkg list` to get a list of installed ports -> a bit of regex action to only get a list of installed ports -> create a new vcpkg dir -> use response file to install everything `vcpkg install @list-of-ports`.  

 `vcpkg upgrade` is not really a supported command due to the issues it has.

**Comment by AlexanderTaeschner** [comment]
> `vcpkg upgrade` is not really a supported command due to the issues it has.

Is this the offical stance now? If yes, the command should be obsoleted.

**Comment by MarkCallow** [comment]
> The official stance is to use manifest mode instead of classic mode.

What is the equivalent command in "manifest mode"?

`vcpkg --help` needs to be updated to warn about the issues and describe the recommended alternative.

**Comment by MFRSiam** [comment]
i did a new vcpkg install, seems like it fixed it.

**Comment by MarkCallow** [comment]
> i did a new vcpkg install, seems like it fixed it.

@MFRSiam what exactly did you do? As I noted in the bug description I did a `git pull; ./bootstrap-vcpkg.sh` before encountering this bug. That should have installed the latest version of vcpkg.

**Comment by MFRSiam** [comment]
@MarkCallow after that bug i did a fresh install which fixed it, i dont know why it happened in the 1st place.  But i do remember git pulling and running bootstrap-vcpkg didnt fix it. as i use vcpkg i didnt bother fixing it instead removed the whole folder and reinstalling it again. Sorry for not being to elaborate more.

**Comment by FrankXie05** [comment]
@MarkCallow I'm not able to repro this issue with the latest vcpkg version.
     Maybe you can try to clone a new vcpkg again, if it is still an issue, please reopen it.

**Comment by MarkCallow** [comment]
I had followed @MFRSiam's suggestion deleting and recreating my clone of vcpkg and done an upgrade. That was many months ago. I have just done

```bash
git pull
./bootstrap-vcpkg.sh
./vcpkg upgrade
```

and it worked. But given my previous re-clone I don't think this proves the bug is fixed.

**Comment by Neumann-A** [comment]
`tools-meson` was missing the dependency of `vcpkg-tool-meson` as a host dependency instead of a normal dependency. This was fixed.
