### ISSUE TITLE
[libwebsockets] Build error: fails with triplet x64-mingw

### ISSUE THREAD

**Issue by patzf** [microsoft/vcpkg#22288]
**Host Environment**
- OS: WIN10
- Compiler: Target: MinGw64 (gcc version 11.2.0 (Rev5, Built by MSYS2 project))
-  Target: x86_64-w64-mingw32
- Vcpkg package management program version 2021-12-09-724cea8b33cbf06c645f5095fa29773697da9761

**To Reproduce**
`./vcpkg install libwebsockets`

**Failure logs** 
CMake Error at C:/install/msys64/home/myusr/vcpkg/scripts/buildsystems/vcpkg.cmake:788 (_find_package):
  By not providing "Findpthreads_windows.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "pthreads_windows", but CMake did not find one.

  Could not find a package configuration file provided by "pthreads_windows"
  with any of the following names:

    pthreads_windowsConfig.cmake
    pthreads_windows-config.cmake

  Add the installation prefix of "pthreads_windows" to CMAKE_PREFIX_PATH or
  set "pthreads_windows_DIR" to a directory containing one of the above
  files.  If "pthreads_windows" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:491 (find_package)

**Additional context**
Call Stack (most recent call first):
  installed/x64-mingw-dynamic/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:415 (vcpkg_execute_required_process)
  ports/libwebsockets/portfile.cmake:135 (vcpkg_cmake_configure)
  scripts/ports.cmake:142 (include)

---

  package: libwebsockets[core]:x64-mingw-dynamic -> 4.3.0
    vcpkg-tool version: 2021-12-09-724cea8b33cbf06c645f5095fa29773697da9761
    vcpkg-scripts version: 1085a57da 2021-12-30 (2 days ago)

**Comment by dg0yt** [comment]
AFAICT port libwebsockets is not ready for building with mingw. There are more showstoppers in the portfile.

**Comment by patzf** [comment]
@dg0yt : Thanks for your input! So it seems that on Windows OS, I have to go with MS VisualStudio / MS Build tools / Windows SDK to build libwebsockets, right?
I checked this (https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.build-windows.md) on the web, but it´s more a rant against the Win OS than the attempt getting the lib compilable with FOSS on Windows...

**Comment by dg0yt** [comment]
> So it seems that on Windows OS, I have to go with MS VisualStudio / MS Build tools / Windows SDK to build libwebsockets, right?

You might also try to fix the vcpkg port yourself if you need that port and prefer mingw.
The error you reported is introduced by a patch from vcpkg (should use `MSVC` instead of `WIN32`).

**Comment by sfhacker** [comment]
Just built libwebsockets from source on Windows 10 x64. No issues at all.

![image](https://user-images.githubusercontent.com/25817529/148388572-e8045caf-80a7-4011-83b6-fd1fd1206e12.png)

How can we reproduce this issue locally?

Cheers.

**Comment by patzf** [comment]
@sfhacker 
Thanks for the effort.
I started off with a nearly "clean" Win 10 machine (64bit OS), and followed this guidr to bootstrap vcpkg:
https://nicedoc.io/Microsoft/vcpkg/docs/users/mingw.md#How-to-avoid-mixing-different-installations

In essence, the steps i did were:

- install Msys2
- in msys2 terminal run "pacman -S mingw-w64-x86_64-toolchain" and "pacman -S --needed git base-devel"
- open the Msys Terminal and switch to MinGW64 console by typing "source shell mingw64"
- git clone https://github.com/microsoft/vcpkg.git
- cd vcpkg
- ./bootstrap-vcpkg.bat
- export VCPKG_DEFAULT_TRIPLET=x64-mingw-dynamic
- export VCPKG_DEFAULT_HOST_TRIPLET=x64-mingw-dynamic
- cd vcpkg
- ./vcpkg install libwebsockets
- This immedialtely FAILS because libuv package installation fails. I found a pullrequest on a already fixed bug on that and found that installing libuv with "./vcpkg install --head libuv" is successful.
- Another call of "./vcpkg install libwebsockets" then fails with the logs I already mentioned in the ticket. 

The output of the console is 

Computing installation plan...
The following packages will be built and installed:
    libwebsockets[core]:x64-mingw-dynamic -> 4.3.0
Restored 0 packages from C:\Users\franz\AppData\Local\vcpkg\archives in 341.6 us. Use --debug to see more details.
Starting package 1/1: libwebsockets:x64-mingw-dynamic
Building package libwebsockets[core]:x64-mingw-dynamic...
-- Using community triplet x64-mingw-dynamic. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: C:\install\msys64\home\franz\vcpkg\triplets\community\x64-mingw-dynamic.cmake
-- Using cached warmcat-libwebsockets-a5aae049b2a386712e1be3b417915c0d44c7e675.tar.gz.
-- Extracting source C:/install/msys64/home/franz/vcpkg/downloads/warmcat-libwebsockets-a5aae049b2a386712e1be3b417915c0d44c7e675.tar.gz
-- Applying patch fix-dependency-libuv.patch
-- Applying patch fix-build-error.patch
-- Applying patch export-include-path.patch
-- Using source at C:/install/msys64/home/franz/vcpkg/buildtrees/libwebsockets/src/0d44c7e675-123a54d3a2.clean
-- Configuring x64-mingw-dynamic
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: ninja -v
    Working Directory: C:/install/msys64/home/franz/vcpkg/buildtrees/libwebsockets/x64-mingw-dynamic-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\install\msys64\home\franz\vcpkg\buildtrees\libwebsockets\config-x64-mingw-dynamic-out.log

Call Stack (most recent call first):
  installed/x64-mingw-dynamic/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:415 (vcpkg_execute_required_process)
  ports/libwebsockets/portfile.cmake:135 (vcpkg_cmake_configure)
  scripts/ports.cmake:142 (include)


Error: Building package libwebsockets:x64-mingw-dynamic failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libwebsockets
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[libwebsockets]+Build+error
including:
  package: libwebsockets[core]:x64-mingw-dynamic -> 4.3.0
    vcpkg-tool version: 2021-12-09-724cea8b33cbf06c645f5095fa29773697da9761
    vcpkg-scripts version: 408ffb232 2022-01-05 (10 hours ago)

Additionally, attach any relevant sections from the log files above.

**Comment by dg0yt** [comment]
> Just built libwebsockets from source on Windows 10 x64. No issues at all.

That's easy with windows triplets which are CI tested and with a screenshot which hides the details. But it doesn't help the user.

**Comment by dg0yt** [comment]
> Just built libwebsockets from source on Windows 10 x64. No issues at all.

And it is also manually with upstream sources.

**Comment by sfhacker** [comment]
@patzf Are you new to building projects from source on Windows?

Have you tried using/following this online guide? [1]

![image](https://user-images.githubusercontent.com/25817529/148407628-1693a57c-0049-426b-b946-8c2a2973019d.png)


[1] https://libwebsockets.org/lws-api-doc-master/html/md_README_8build.html

**Comment by patzf** [comment]
@sfhacker Yes, I am new to building libs from source - I will definitely check the link you refer to.

Anyhow, isn´t it THE purpose of a system like vckpg (and the libs provided by that system) to perfom the build process without manually tweaking sources / configs to "manually" build some single lib from source? Because even If I find a way to build that specific lib, I still have to figure out how that fits into the "big" picture (because in this case, I actually want to install a tool that does not only depend on lws but a bunch of other packages too and it is unlikely to get a working and reproducable result in the end?)

**Comment by JackBoosY** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
