### ISSUE TITLE
[New Port Request] <msdf-atlas-gen>

### ISSUE THREAD

**Issue by bmarques1995** [microsoft/vcpkg#22284]
Library name: msdf-atlas-gen

Library description: This is a utility for generating compact font atlases using MSDFgen.

The atlas generator loads a subset of glyphs from a TTF or OTF font file, generates a distance field for each of them, and tightly packs them into an atlas bitmap (example below). The finished atlas and/or its layout metadata can be exported as an Artery Font file, a plain image file, a CSV sheet or a structured JSON file.

Source repository URL: https://github.com/Chlumsky/msdf-atlas-gen

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
