### ISSUE TITLE
No suitable Visual Studio instances were found

### ISSUE THREAD

**Issue by LedLoaf** [microsoft/vcpkg#22287]
Hello,

I recently deleted Visual Studio 2019 and installed Visual Studio 2022.

When I use vcpkg I get this error message "No suitable Visual Studio instances were found". I'm assuming it is looking for 2019, how can I redirect where it is looking? I did a quick search for similar problems and I found nothing of use.

Any help would be appreciated!

**Comment by LedLoaf** [comment]
One of the searched threads said installing 142.29 fixed it for him. It doesn't work for me.

**Comment by JackBoosY** [comment]
See https://github.com/microsoft/vcpkg-tool/pull/314.

**Comment by FrankXie05** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
