### ISSUE TITLE
Port Request : Zipper

### ISSUE THREAD

**Issue by herpiko** [microsoft/vcpkg#2229]
https://github.com/sebastiandev/zipper

Zipper's goal is to bring the power and simplicity of minizip to a more object oriented/c++ user friendly library.

**Comment by gb96** [comment]
Related to this, I would like to suggest adding a port of gzip.  I am not currently permitted to sign the MSFT CLA in my day-job capacity, however will make a PR on my own time if/when I get a chance.

https://downloads.sourceforge.net/project/gnuwin32/gzip/1.3.12-1/gzip-1.3.12-1-src.zip

### URLs and Hash:
`    
        URLS "https://jaist.dl.sourceforge.net/project/gnuwin32/gzip/1.3.12-1/gzip-1.3.12-1-src.zip" "https://sourceforge.mirrorservice.org/g/gn/gnuwin32/gzip/1.3.12-1/gzip-1.3.12-1-src.zip" "https://fossies.org/windows/misc/gow-utilities-src-0.8.0.tar/gow-utilities-src-0.8.0/gzip-1.3.12-1-src.zip" "http://download2.nust.na/pub4/sourceforge/g/gn/gnuwin32/gzip/1.3.12-1/gzip-1.3.12-1-src.zip"
        FILENAME "gzip-1.3.12-1-src"
        SHA512 8ea9ad3e937a3de54fe9e1810996eaa599cc3dc13be75a51c4e62f05f733f1731ecb4098fd62f56311790380cecbd353a9b5e61e035bfa39bd8d79ceeb4a3cff
`

### CMakeLists
This source archive has some Makefiles, no CMakeLists so one will need to be written,

**Comment by AlvinZhangH** [comment]
Solved

**Comment by JackBoosY** [comment]
We can’t reopen this issue until a PR is opened, unfortunately, consider making a pull request!

**Comment by BullyWiiPlaza** [comment]
It looks like `Zipper` is still not available in `vcpkg`, can someone give it another try with a port implementation? Thank you.

Related: https://github.com/microsoft/vcpkg/pull/4581

**Comment by NancyLi1013** [comment]
You can try to add this port if possible @BullyWiiPlaza.
