### ISSUE TITLE
[sqlcipher] Linux/macOS support

### ISSUE THREAD

**Issue by kotori2** [microsoft/vcpkg#22296]
**Is your feature request related to a problem? Please describe.**
It seems that Linux and macOS support was dropped. Maybe it's related to static linking. 
https://github.com/microsoft/vcpkg/blob/1085a57da0725c19e19586025438e8c16f34c890/ports/sqlcipher/portfile.cmake#L3

**Proposed solution**
Add macOS and Linux support. 

**Describe alternatives you've considered**
Simply removing it won't work. 
```
Starting package 2/2: sqlcipher:x64-osx
Building package sqlcipher[core]:x64-osx...
-- Note: sqlcipher only supports dynamic library linkage. Building dynamic library.
-- Downloading https://github.com/sqlcipher/sqlcipher/archive/v4.4.3.tar.gz -> sqlcipher-sqlcipher-v4.4.3.tar.gz...
-- Extracting source /Users/kotori0/vcpkg/downloads/sqlcipher-sqlcipher-v4.4.3.tar.gz
-- Using source at /Users/kotori0/vcpkg/buildtrees/sqlcipher/src/v4.4.3-6db972b75c.clean
CMake Error at ports/sqlcipher/portfile.cmake:14 (find_program):
  Could not find NMAKE using the following names: nmake
Call Stack (most recent call first):
  scripts/ports.cmake:140 (include)
```

**Additional context**
/

**Comment by shiena** [comment]
Conan's sqlcipher recipe supports macOS/Linux, so I think it can be supported by vcpkg if you refer to it.
https://github.com/conan-io/conan-center-index/tree/master/recipes/sqlcipher

**Comment by nlogozzo** [comment]
any updates on Linux support?

It's the only thing keeping me back from switching from conan...
