### ISSUE TITLE
[New Port Request] libpsl

### ISSUE THREAD

**Issue by equeim** [microsoft/vcpkg#22294]
Library name: libpsl

Library description: C library to handle the Public Suffix List

Source repository URL: https://github.com/rockdaboot/libpsl

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
It can use either libicu, libidn2 or libidn as dependency, although it seems that most Linux distributuions build is with libidn2.

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.

**Comment by equeim** [comment]
@JackBoosY Does [this](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md#do-not-use-features-to-implement-alternatives) section of maintainer guide mean that I will have to choose one of backend libraries for libpsl (either icu or libidn2), and users won't able to choose another via feature? If so then I think it will stay in my personal vcpkg registry. I actually need to build both variants of it, and I don't think I'm qualified to make this choice for others.

**Comment by JackBoosY** [comment]
> @JackBoosY Does [this](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md#do-not-use-features-to-implement-alternatives) section of maintainer guide mean that I will have to choose one of backend libraries for libpsl (either icu or libidn2), and users won't able to choose another via feature?


Yes. That will cause the diamond issue if you use both 2 features.
