### ISSUE TITLE
[SDL2] update to <2.0.18>

### ISSUE THREAD

**Issue by jz315** [microsoft/vcpkg#22290]
Library name: SDL2

New version number: 2.0.18

Other information that may be useful (release notes, etc...)
https://www.libsdl.org/download-2.0.php

**Comment by JonLiu1993** [comment]
@jz315 , This issue will be fixed by #21848

**Comment by JonLiu1993** [comment]
This issue will be fixed by https://github.com/microsoft/vcpkg/pull/22586
