### ISSUE TITLE
[hunspell] build failure autopoint: archive.dir.tar.xz: No such file or directory

### ISSUE THREAD

**Issue by vadi2** [microsoft/vcpkg#22301]
**Host Environment**
- OS: Windows
- Compiler: MinGW

**To Reproduce**
`./vcpkg install hunspell`

**Failure logs** 
```
-- Using msys root at D:/a/Mudlet/Mudlet/3rdparty/vcpkg/downloads/tools/msys2/aa5af7b2aa7e90e8
  -- Generating configure for x64-mingw-dynamic
  [LogCollection][Start]File:'D:\a\Mudlet\Mudlet\3rdparty\vcpkg\buildtrees\hunspell\autoconf-x64-mingw-dynamic-err.log':
  autoreconf: export WARNINGS=
  autoreconf: Entering directory '.'
  autoreconf: running: autopoint --force
  /c/Program Files/Git/usr/bin/autopoint: line 485: /usr/share/gettext/archive.dir.tar.xz: No such file or directory
  tar.exe: gettext-0.19.8: Not found in archive
  tar.exe: Error exit delayed from previous errors.
  autopoint: *** infrastructure files for version 0.19.8 not found; this is autopoint from GNU gettext-tools 0.19.8.1
  autopoint: *** Stop.
  autoreconf: error: autopoint failed with exit status: 1
  
  [LogCollection][End]File:'D:\a\Mudlet\Mudlet\3rdparty\vcpkg\buildtrees\hunspell\autoconf-x64-mingw-dynamic-err.log'.
  CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
      Command failed: D:/a/Mudlet/Mudlet/3rdparty/vcpkg/downloads/tools/msys2/803521c5733336c9/usr/bin/bash.exe --noprofile --norc --debug -c "autoreconf -vfi"
      Working Directory: D:/a/Mudlet/Mudlet/3rdparty/vcpkg/buildtrees/hunspell/src/v1.7.0-9251c91a4b.clean/
      Error code: 1
      See logs for more information:
        D:\a\Mudlet\Mudlet\3rdparty\vcpkg\buildtrees\hunspell\autoconf-x64-mingw-dynamic-err.log
  
  Call Stack (most recent call first):
    scripts/cmake/vcpkg_configure_make.cmake:604 (vcpkg_execute_required_process)
    ports/hunspell/portfile.cmake:64 (vcpkg_configure_make)
    scripts/ports.cmake:142 (include)
```

**Comment by dg0yt** [comment]
> /c/Program Files/Git/usr/bin/autopoint

Does git for Windows come with (an incomplete) `autopoint` 0.19.8.1? :eyes:

**Comment by vadi2** [comment]
I'm building in GitHub actions, if it helps - here's the list of software: https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md

**Comment by SlySven** [comment]
Is https://www.gnu.org/software/gnulib/manual/html_node/gettextize-and-autopoint.html relevant?

**Comment by dg0yt** [comment]
> Is https://www.gnu.org/software/gnulib/manual/html_node/gettextize-and-autopoint.html relevant?

At least it indicates that env `AUTOPOINT` might be used to enforce vcpkg's installation of `autopoint`.

**Comment by vadi2** [comment]
@dg0yt would you have an idea on how to fix this?

**Comment by JonLiu1993** [comment]
@dg0yt, would you have an idea?

**Comment by dg0yt** [comment]
I think the hints were already given. It may be necessary to work with the AUTOPOINT variable when building hunspell.

**Comment by JonLiu1993** [comment]
> I think the hints were already given. It may be necessary to work with the AUTOPOINT variable when building hunspell.

@vadi2 , Can you try it locally? We don't have the environment to reproduce your problem

**Comment by vadi2** [comment]
Confirmed fixed, thank you!
