### ISSUE TITLE
Log4cplus version

### ISSUE THREAD

**Issue by LazyWolfLin** [Microsoft/vcpkg#2230]
Why the version of log4cplus is 1.2.1 rc2, but not 2.0.0 rc2?

**Comment by ras0219-msft** [comment]
Thanks for pointing out that there's an update available!

This was probably the latest version when the original submitter added the port -- We'd be happy to accept a PR that updates it! Simply edit the `ports\log4cplus\CONTROL` and `ports\log4cplus\portfile.cmake` to use the new version.
