### ISSUE TITLE
Vcpkg forces "ninja" without having ninja installed

### ISSUE THREAD

**Issue by co-dev10** [microsoft/vcpkg#22300]
Hello, 
I trief to use vcpkg, but it always tries to use "ninja -v", without even having ninja installed. 

**Host Environment**
- OS: Windows
- Compiler: MSVC

**To Reproduce**
`git clone https://github.com/Microsoft/vcpkg.git`
`cd vcpkg`
`./vcpkg install libmariadb`

**Failure logs** 
```D:\vcpkg\vcpkg>vcpkg install libmariadb
Computing installation plan...
The following packages will be built and installed:
    libmariadb[core,schannel,ssl]:x86-windows -> 3.1.15
  * vcpkg-cmake[core]:x64-windows -> 2021-12-20
  * vcpkg-cmake-config[core]:x64-windows -> 2021-12-28
  * zlib[core]:x86-windows -> 1.2.11#13
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
A suitable version of powershell-core was not found (required v7.2.0). Downloading portable powershell-core v7.2.0...
Downloading powershell-core...
  https://github.com/PowerShell/PowerShell/releases/download/v7.2.0/PowerShell-7.2.0-win-x86.zip -> D:\vcpkg\vcpkg\downloads\PowerShell-7.2.0-win-x86.zip
Extracting powershell-core...
A suitable version of 7zip was not found (required v19.0.0). Downloading portable 7zip v19.0.0...
Downloading 7zip...
  https://www.7-zip.org/a/7z1900-x64.msi -> D:\vcpkg\vcpkg\downloads\7z1900-x64.msi
Extracting 7zip...
Detecting compiler hash for triplet x86-windows...
Restored 2 packages from C:\Users\Cian\AppData\Local\vcpkg\archives in 35.16 ms. Use --debug to see more details.
Starting package 1/4: vcpkg-cmake:x64-windows
Installing package vcpkg-cmake[core]:x64-windows...
Elapsed time for package vcpkg-cmake:x64-windows: 19.8 ms
Starting package 2/4: vcpkg-cmake-config:x64-windows
Installing package vcpkg-cmake-config[core]:x64-windows...
Elapsed time for package vcpkg-cmake-config:x64-windows: 59.08 ms
Starting package 3/4: zlib:x86-windows
Building package zlib[core]:x86-windows...
-- Downloading https://www.zlib.net/zlib-1.2.11.tar.gz;https://downloads.sourceforge.net/project/libpng/zlib/1.2.11/zlib-1.2.11.tar.gz -> zlib1211.tar.gz...
-- Extracting source D:/vcpkg/vcpkg/downloads/zlib1211.tar.gz
-- Applying patch cmake_dont_build_more_than_needed.patch
-- Applying patch 0001-Prevent-invalid-inclusions-when-HAVE_-is-set-to-0.patch
-- Applying patch add_debug_postfix_on_mingw.patch
-- Applying patch 0002-android-build-mingw.patch
-- Using source at D:/vcpkg/vcpkg/buildtrees/zlib/src/1.2.11-e9a093319e.clean
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: ninja -v
    Working Directory: D:/vcpkg/vcpkg/buildtrees/zlib/x86-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\vcpkg\vcpkg\buildtrees\zlib\config-x86-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:345 (vcpkg_execute_required_process)
  ports/zlib/portfile.cmake:23 (vcpkg_configure_cmake)
  scripts/ports.cmake:142 (include)


Error: Building package zlib:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+zlib
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[zlib]+Build+error
including:
  package: zlib[core]:x86-windows -> 1.2.11#13
    vcpkg-tool version: 2021-12-09-724cea8b33cbf06c645f5095fa29773697da9761
    vcpkg-scripts version: 1085a57da 2021-12-30 (3 days ago)
```

`Additionally, attach any relevant sections from the log files above.`

**Additional context**
I dont found any application with the name "ninja"... used the following commands:
```where ninja```
```which ninja```

**Comment by HyeonJunKimAny** [comment]
> Hello, I trief to use vcpkg, but it always tries to use "ninja -v", without even having ninja installed.
> 
> **Host Environment**
> 
> * OS: Windows
> * Compiler: MSVC
> 
> **To Reproduce** `git clone https://github.com/Microsoft/vcpkg.git` `cd vcpkg` `./vcpkg install libmariadb`
> 
> **Failure logs**
> 
> ```
> Computing installation plan...
> The following packages will be built and installed:
>     libmariadb[core,schannel,ssl]:x86-windows -> 3.1.15
>   * vcpkg-cmake[core]:x64-windows -> 2021-12-20
>   * vcpkg-cmake-config[core]:x64-windows -> 2021-12-28
>   * zlib[core]:x86-windows -> 1.2.11#13
> Additional packages (*) will be modified to complete this operation.
> Detecting compiler hash for triplet x64-windows...
> A suitable version of powershell-core was not found (required v7.2.0). Downloading portable powershell-core v7.2.0...
> Downloading powershell-core...
>   https://github.com/PowerShell/PowerShell/releases/download/v7.2.0/PowerShell-7.2.0-win-x86.zip -> D:\vcpkg\vcpkg\downloads\PowerShell-7.2.0-win-x86.zip
> Extracting powershell-core...
> A suitable version of 7zip was not found (required v19.0.0). Downloading portable 7zip v19.0.0...
> Downloading 7zip...
>   https://www.7-zip.org/a/7z1900-x64.msi -> D:\vcpkg\vcpkg\downloads\7z1900-x64.msi
> Extracting 7zip...
> Detecting compiler hash for triplet x86-windows...
> Restored 2 packages from C:\Users\Cian\AppData\Local\vcpkg\archives in 35.16 ms. Use --debug to see more details.
> Starting package 1/4: vcpkg-cmake:x64-windows
> Installing package vcpkg-cmake[core]:x64-windows...
> Elapsed time for package vcpkg-cmake:x64-windows: 19.8 ms
> Starting package 2/4: vcpkg-cmake-config:x64-windows
> Installing package vcpkg-cmake-config[core]:x64-windows...
> Elapsed time for package vcpkg-cmake-config:x64-windows: 59.08 ms
> Starting package 3/4: zlib:x86-windows
> Building package zlib[core]:x86-windows...
> -- Downloading https://www.zlib.net/zlib-1.2.11.tar.gz;https://downloads.sourceforge.net/project/libpng/zlib/1.2.11/zlib-1.2.11.tar.gz -> zlib1211.tar.gz...
> -- Extracting source D:/vcpkg/vcpkg/downloads/zlib1211.tar.gz
> -- Applying patch cmake_dont_build_more_than_needed.patch
> -- Applying patch 0001-Prevent-invalid-inclusions-when-HAVE_-is-set-to-0.patch
> -- Applying patch add_debug_postfix_on_mingw.patch
> -- Applying patch 0002-android-build-mingw.patch
> -- Using source at D:/vcpkg/vcpkg/buildtrees/zlib/src/1.2.11-e9a093319e.clean
> -- Configuring x86-windows
> CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
>     Command failed: ninja -v
>     Working Directory: D:/vcpkg/vcpkg/buildtrees/zlib/x86-windows-rel/vcpkg-parallel-configure
>     Error code: 1
>     See logs for more information:
>       D:\vcpkg\vcpkg\buildtrees\zlib\config-x86-windows-out.log
> 
> Call Stack (most recent call first):
>   scripts/cmake/vcpkg_configure_cmake.cmake:345 (vcpkg_execute_required_process)
>   ports/zlib/portfile.cmake:23 (vcpkg_configure_cmake)
>   scripts/ports.cmake:142 (include)
> 
> 
> Error: Building package zlib:x86-windows failed with: BUILD_FAILED
> Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
> Then check for known issues at:
>   https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+zlib
> You can submit a new issue at:
>   https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[zlib]+Build+error
> including:
>   package: zlib[core]:x86-windows -> 1.2.11#13
>     vcpkg-tool version: 2021-12-09-724cea8b33cbf06c645f5095fa29773697da9761
>     vcpkg-scripts version: 1085a57da 2021-12-30 (3 days ago)
> ```
> 
> `Additionally, attach any relevant sections from the log files above.`
> 
> **Additional context** I dont found any application with the name "ninja"... used the following commands: `where ninja` `which ninja`

how did you solve this?
