### ISSUE TITLE
[New Port Request] licensecc

### ISSUE THREAD

**Issue by IshaanKarnik** [microsoft/vcpkg#22302]
Library name: Licensecc

Library description: Copy protection, licensing library and license generator for Windows and Linux.

Source repository URL: https://github.com/open-license-manager/licensecc

Project homepage (if different from the source repository): http://open-license-manager.github.io/licensecc/index.html

**Comment by PhoebeHui** [comment]
Duplicated of https://github.com/microsoft/vcpkg/issues/22302
