### ISSUE TITLE
[vcpkg-tool] duplicated export plan when doing export with prefab for protobuf

### ISSUE THREAD

**Issue by holmescn** [microsoft/vcpkg#22318]
This is a bug of [vcpkg-tool](https://github.com/microsoft/vcpkg-tool). When doing:
```
$ vcpkg export protobuf --triplet arm-android --prefab --prefab-debug
```
it found the compiled protobuf versions but do export twice. And since the first time is done, the second time caused an error:
```
copy_regular_recursive(/home/vcpkg/packages/protobuf_x86-android23/include, /home/vcpkg/prefab/protobuf/aar/prefab/modules/protobuf-lite/libs/android.x86/include): File exists
```

**Environment**
- OS: Ubuntu 20.04
- Compiler: clang 12 in Android NDK r23

**To Reproduce**
1. ./vcpkg install protobuf:arm-android protobuf:arm64-android protobuf:x86-android protobuf:x64-android
2. ./vcpkg export protobuf --triplet arm-android --prefab --prefab-debug
3. See error: `copy_regular_recursive(...) File exists`

**Expected behavior**
Successfully exported protobuf, and only once.

**Additional context**
I tried to remove the directory if it exists but I think it isn't a good solution. But I cannot find where the export plans are generated.

**Comment by JonLiu1993** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
