### ISSUE TITLE
[cunit] Build error

### ISSUE THREAD

**Issue by caleberi** [microsoft/vcpkg#22323]
**Host Environment**
- OS: Windows
- Compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x86/cl.exe

**To Reproduce**
`./vcpkg install cunit`

**Failure logs** 
-Cut and paste the appropriate build messages from the console output.
```
-- Extracting source C:/vcpkg/downloads/CUnit-2.1-3.tar.bz2
-- Using source at C:/vcpkg/buildtrees/cunit/src/547b417109-1efb971e0d.clean
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: ninja -v
    Working Directory: C:/vcpkg/buildtrees/cunit/x86-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\vcpkg\buildtrees\cunit\config-x86-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:345 (vcpkg_execute_required_process)
  ports/cunit/portfile.cmake:11 (vcpkg_configure_cmake)
  scripts/ports.cmake:142 (include)


Error: Building package cunit:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+cunit
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[cunit]+Build+error
including:
  package: cunit[core]:x86-windows -> 2.1.3#7
    vcpkg-tool version: 2021-12-09-724cea8b33cbf06c645f5095fa29773697da9761
    vcpkg-scripts version: abf52dd1a 2022-01-03 (12 hours ago)'
```

-Please attach any additional failure logs mentioned in the console output.
[config-x86-windows-out.log](https://github.com/microsoft/vcpkg/files/7807059/config-x86-windows-out.log)

**Additional context**
I tried deleting my old vcpkg  and reinstalling but it still didn't work

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Did you install CMake tools in Visual Studio Installer? If not, please install `cunit` again after installing this.
![image](https://user-images.githubusercontent.com/94091114/148192117-b44af445-4d18-46c5-bb1d-31bfcf430778.png)

**Comment by JackBoosY** [comment]
Ping for response

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
