### ISSUE TITLE
Vcpkg cannot find libssh2

### ISSUE THREAD

**Issue by simon-p-r** [Microsoft/vcpkg#2233]
Hi

I am trying to find libssh2 static library which has been built and installed by vcpkg however I cannot find it unless I hardcode the path.  Here is CMake file and it is called with vcpkg toolchain

     cmake_minimum_required (VERSION 3.10.0)
     project(curl-test C)

     find_package(CURL REQUIRED)
     find_package(OPENSSL REQUIRED)
     find_package(LIBSSH2 REQUIRED)
     find_package(ZLIB REQUIRED)

     add_executable(curl-test main.c)
     target_link_libraries(curl-test PRIVATE ${CURL_LIBRARIES} ${OPENSSL_LIBRARIES} ${LIBSSH2_LIBRARIES}  ${ZLIB_LIBRARIES} Ws2_32.lib wldap32.lib crypt32.lib)
     target_include_directories(curl-test PRIVATE ${CURL_INCLUDE_DIRS})

However if I change find_package to hardcoded path it works

      find_package(LIBSSH2)
      if (NOT DEFINED LIBSSH2_FOUND)
          set(LIBSSH2_LIBRARIES "D:/vcpkg/installed/x64-windows-static/lib/libssh2.lib")
      endif()

Thanks

**Comment by ras0219-msft** [comment]
Thanks for reporting this! It looks like our libssh2 port wasn't installing the cmake targets.

I've fixed them up in the latest master, so you should now see:
```
D:\src\vcpkg> vcpkg install libssh2
The following packages will be built and installed:
    libssh2:x86-windows
Starting package 1/1: libssh2:x86-windows
Building package libssh2:x86-windows...
...
Building package libssh2:x86-windows... done
Installing package libssh2:x86-windows...
Installing package libssh2:x86-windows... done
Elapsed time for package libssh2:x86-windows: 2.616 min

Total elapsed time: 2.616 min

The package libssh2:x86-windows provides CMake targets:

    find_package(libssh2 REQUIRED)
    target_link_libraries(main PRIVATE Libssh2::libssh2)
```

**Comment by simon-p-r** [comment]
@ras0219-msft thanks for the quick fix, much appreciated!
