### ISSUE TITLE
vcpkg msys install requires admin (privileged) mode to copy files to non privileged folders

### ISSUE THREAD

**Issue by sekcheong** [microsoft/vcpkg#22341]
**Describe the bug**
When build libiconv vcpkg 

**Environment**
- OS: Windows
- Compiler: VC2019

**To Reproduce**
0. Make sure the user doesn't have admin access in Windows 10
1. ./vcpkg install libiconv:x64-windows
2. See error, vckpg -> cmake -> bash ->sh 
Repro code when

**Expected behavior**
vcpkg should not require privileged access to install non privileged files. 

**Failure logs** 
cmake invokes 
C:\devel\vcpkg\downloads\tools\msys2\803521c5733336c9\usr\bin\sh.exe ./../src/1.16-b0c41d3469.clean/configure --build=x86_64-pc-mingw32 --enable-extra-encodings --without-libiconv-prefix --without-libintl-prefix --enable-relocatable ac_cv_prog_ac_ct_STRIP=: gl_cv_double_slash_root=yes ac_cv_func_memmove=yes --disable-silent-rules --verbose --enable-shared --disable-static --prefix=/C/devel/vcpkg/installed/x64-windows --bindir=${prefix}/tools/libiconv/bin --sbindir=${prefix}/tools/libiconv/sbin --libdir=${prefix}/lib --mandir=${prefix}/share/libiconv --docdir=${prefix}/share/libiconv --datarootdir=${prefix}/share/libiconv

Here is another command that the windows Elevated Privileges dialog box. Note, the destination directory is a user directory which should not need privileged access. 

C:\devel\vcpkg\downloads\tools\msys2\803521c5733336c9\usr\bin\install.exe -c .libs/charset.lib /c/devel/vcpkg/buildtrees/libiconv/x64-windows-dbg/lib/charset.lib

**Additional context**

**Comment by Cheney-W** [comment]
Dose this issue occur when the vcpkg saved in a Non-c drive?

**Comment by sekcheong** [comment]
It's on C drive

**Comment by dg0yt** [comment]
Make sure that there is no second set of MSYS2 tools, e.g. from git, in the PATH.
Attach `config.log` which is within the ...-rel or -dbg directory after a failed configure step.

**Comment by Cheney-W** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
