### ISSUE TITLE
Integrating vcpkg into VS2017 results in 'project out of date' permanently

### ISSUE THREAD

**Issue by digidream** [Microsoft/vcpkg#2234]
When the vcpkg is integrated into VS2017, and the projects is linked to some vcpkg installed library, the project is always built again. Prior to run, the message 'This project is out of date' appears. When 'Build' is selected, no (re)build is done. 

For example, trying to run this code:
```
#include <boost/log/trivial.hpp>
int main()
{
    BOOST_LOG_TRIVIAL(info) << "Running example";
    return 0;
}
```
will always report 'project out of date'.

I use VS2017 on two different PCs - this issue shows only on Windows 7 installation, the same version of VS2017 on Windows 10 works fine.

**Comment by NancyLi1013** [comment]
Please open a new issue if this is still a problem for you.
