### ISSUE TITLE
Port Request: Flang compiler

### ISSUE THREAD

**Issue by MathiasMagnus** [microsoft/vcpkg#2235]
https://github.com/flang-compiler/flang

First open-source, Windows capable Fortran compiler based on LLVM.

**Comment by xoviat** [comment]
Can you help with 32 bit support?

**Comment by MathiasMagnus** [comment]
I have never tried building a 32-bit version of flang. Can give it a shot, though I have never authored a vcpkg as well.

**Comment by cenit** [comment]
here https://github.com/Microsoft/vcpkg/pull/1098 it is discussed with a PR ready to merge. I think that the author is still waiting for a reply

**Comment by xoviat** [comment]
Please pick up isuruf/flang#54. I don't have time to finish it.

**Comment by JackBoosY** [comment]
We can’t reopen this issue until a PR is opened, unfortunately, consider making a pull request!
