### ISSUE TITLE
VCPKG forcing Ninja

### ISSUE THREAD

**Issue by diehard2** [microsoft/vcpkg#22368]
No matter how I structure my portfile.cmake Ninja is being chose by  vcpkg_configure_cmake.

**Environment**
- OS: Linux
- Compiler: gcc 11.2
- Latest VCPKG latest revision

` 
	 
	 find_program(GIT git)
	 set(GIT_URL "xxxxxxxxxxx")
	 set(GIT_REV "2a8e132e85a527603a3d6d4503ded117d5066eaf")
	 message(STATUS "port: ${PORT}")
	 make_directory( ${CURRENT_BUILDTREES_DIR}/src/${PORT})
	 set(SOURCE_PATH ${CURRENT_BUILDTREES_DIR}/src/${PORT})
	
     if(NOT EXISTS "${SOURCE_PATH}/.git")
		  message(STATUS "Cloning and fetching submodules")
		  vcpkg_execute_required_process(
		    COMMAND ${GIT} clone --recurse-submodules ${GIT_URL} ${SOURCE_PATH}
		    WORKING_DIRECTORY ${SOURCE_PATH}
		    LOGNAME clone
		  )
		  message(STATUS "Checkout revision ${GIT_REV}")
		  vcpkg_execute_required_process(
		    COMMAND ${GIT} checkout ${GIT_REV}
		    WORKING_DIRECTORY ${SOURCE_PATH}
		    LOGNAME checkout
		  )
	  endif()
	  
	  vcpkg_configure_cmake(
	    SOURCE_PATH ${SOURCE_PATH}
	     OPTIONS -DBUILD_SERVER=OFF -G "Unix Makefiles"
	  )
	  
	  
	  vcpkg_install_cmake()
	  vcpkg_fixup_cmake_targets()
`

If I run cmake from the command line with -G Unix Makefiles, everything works. However, vcpkg is inserting a second -G option for Ninja  that's taking precedence 

resulting output that fails
```
  Command failed: /usr/local/bin/cmake /home/simple_dds/vcpkg/buildtrees/nebula/src/nebula -DBUILD_NEBULA_SERVER=OFF -G "Unix Makefiles" -DCMAKE_MAKE_PROGRAM=/home/simple_dds/vcpkg/downloads/tools/ninja-1.10.2-linux/ninja -DCMAKE_SYSTEM_NAME=Linux -DBUILD_SHARED_LIBS=OFF -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/home/simple_dds/vcpkg/scripts/toolchains/linux.cmake -DVCPKG_TARGET_TRIPLET=x64-linux -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=external -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=/home/simple_dds/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_LINKER_FLAGS_RELEASE= -DVCPKG_LINKER_FLAGS_DEBUG= -DVCPKG_TARGET_ARCHITECTURE=x64 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -D_VCPKG_ROOT_DIR=/home/simple_dds/vcpkg -DZ_VCPKG_ROOT_DIR=/home/simple_dds/vcpkg -D_VCPKG_INSTALLED_DIR=/home/simple_dds/vcpkg/installed -DVCPKG_MANIFEST_INSTALL=OFF -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/home/simple_dds/vcpkg/packages/nebula_x64-linux/debug
 ```
note the -G Ninja in the second to last line. I tried adding GENERATOR "Unix Makefile" I get 
```
  Unrecognized GENERATOR setting from vcpkg_configure_cmake().  Valid
  generators are: Ninja, Visual Studio, and NMake Makefiles
```

I can't change the portion that's causing an issue with Ninja since I don't own that code and it's for an older release anyway. Is there any way to run it with "Unix Makefiles" and still use vcpkg_configure_cmake?

**Comment by JackBoosY** [comment]
If your repo has makefiles, you may use `vcpkg_*_make` instead.

**Comment by diehard2** [comment]
Thanks for the suggestion @JackBoosY , but it only has makefiles

**Comment by Neumann-A** [comment]
Why do you want to use the Makefile generator? Using Ninja is preferred inside vcpkg. You are not supposed to work with the files in the buildtree.

**Comment by JackBoosY** [comment]
Ping @diehard2 for response.

**Comment by diehard2** [comment]
@Neumann-A , I don't particularly want to use the Makefile generator, but that option works and the Ninja option doesn't. I don't particularly want to spend time figuring out why, so I was hoping to just use the option that gets me a build.

Regardless of if this is the correct approach, its clearly incorrect behavior based on both the vcpkg documentation and the cmake allowable options. "Unix Makefiles" is allowed by the cmake command line (and works) and PREFER_NINJA does nothing. Ninja is forced regardless.

Not allowing "Unix Makefiles" in Generator seems like an oversight since it's a valid option for CMake

**Comment by Neumann-A** [comment]
> Ninja option doesn't.

show the log.... If ninja doesn't work there is probably a bug in the CMakeLists.txt which is just hidden by the Makefile generator.

**Comment by diehard2** [comment]
Sorry for the delay. The CMakeLists.txt calls 

find_package(zstd MODULE REQUIRED)

and this in turn generates 

#############################################
# Custom command for thirdparty/zstd/src/zstdBuild-stamp/zstdBuild-build

build thirdparty/zstd/src/zstdBuild-stamp/zstdBuild-build | ${cmake_ninja_workdir}thirdparty/zstd/src/zstdBuild-stamp/zstdBuild-build: CUSTOM_COMMAND thirdparty/zstd/src/zstdBuild-stamp/zstdBuild-configure
  COMMAND = cd /home/simple_dds/vcpkg/buildtrees/nebula/thirdparty/zstd/src/zstdBuild && $(MAKE) -j1 -C lib PREFIX=/home/simple_dds/vcpkg/buildtrees/nebula/thirdparty/zstd LIBDIR=/home/simple_dds/vcpkg/buildtrees/nebula/thirdparty/zstd/lib && /usr/local/bin/cmake -E touch /home/simple_dds/vcpkg/buildtrees/nebula/thirdparty/zstd/src/zstdBuild-stamp/zstdBuild-build
  DESC = Performing build step for 'zstdBuild'
  restat = 1

The error being generated is

ninja: error: build.ninja:7741: bad $-escape (literal $ must be written as $$)

But since this is all autogenerated I don't have a ton of options here for making this work (as far as I can tell) other than being able to use "Unix Makefiles" as a Generator

**Comment by JackBoosY** [comment]
Ah I saw this issue before.

**Comment by JackBoosY** [comment]
Can you please provide file `build.ninja` in your cmake binary dir?

**Comment by diehard2** [comment]
attached
[build.ninja.txt](https://github.com/microsoft/vcpkg/files/7878486/build.ninja.txt)

**Comment by JackBoosY** [comment]
`${cmake_ninja_workdir}`

**Comment by JackBoosY** [comment]
Did you install ninja manullay? Can you confirm whether _VCPKG_ROOT/downloads/tools/ninja-1.10.2-linux/_ exists?

**Comment by diehard2** [comment]
I did not install it manually and that directory exists

**Comment by JackBoosY** [comment]
> I did not install it manually and that directory exists

I'll take a look.

**Comment by dg0yt** [comment]
~~~
 Command failed: /usr/local/bin/cmake /home/simple_dds/vcpkg/buildtrees/nebula/src/nebula -DBUILD_NEBULA_SERVER=OFF -G "Unix Makefiles" -DCMAKE_MAKE_PROGRAM=/home/simple_dds/vcpkg/downloads/tools/ninja-1.10.2-linux/ninja -DCMAKE_SYSTEM_NAME=Linux -DBUILD_SHARED_LIBS=OFF -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/home/simple_dds/vcpkg/scripts/toolchains/linux.cmake -DVCPKG_TARGET_TRIPLET=x64-linux -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=external -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=/home/simple_dds/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_LINKER_FLAGS_RELEASE= -DVCPKG_LINKER_FLAGS_DEBUG= -DVCPKG_TARGET_ARCHITECTURE=x64 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -D_VCPKG_ROOT_DIR=/home/simple_dds/vcpkg -DZ_VCPKG_ROOT_DIR=/home/simple_dds/vcpkg -D_VCPKG_INSTALLED_DIR=/home/simple_dds/vcpkg/installed -DVCPKG_MANIFEST_INSTALL=OFF -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/home/simple_dds/vcpkg/packages/nebula_x64-linux/debug
~~~
...
~~~
build CMakeFiles/rebuild_cache.util: CUSTOM_COMMAND
  COMMAND = cd /home/simple_dds/vcpkg/buildtrees/nebula/x64-linux-dbg && /usr/local/bin/cmake --regenerate-during-build -S/home/simple_dds/vcpkg/buildtrees/nebula/src/nebula -B/home/simple_dds/vcpkg/buildtrees/nebula/x64-linux-dbg
~~~~

FTR:
 - There is no port "nebula" in vcpkg.
 - The custom port builds zstd as a vendored dependency.
 - The nebula build seems to build the vendored zstd via explicit commands for Makefiles (`$(MAKE)`). This assumes that nebula itseld is build with `make`.

**Comment by diehard2** [comment]
@dg0yt I'm attempting to build it as an internal package for vcpkg. It builds fine with cmake outside of vcpkg. Its being pulled in with the find_package command from cmake

**Comment by dg0yt** [comment]
It is a vcpkg problem. It needs to support cmake (the configuration system) with make (the build tool) for ports that assume this combination. Maybe #22597 is just the same issue, but with a port that already is part of vcpkg. But in generally, ports avoid vendored dependencies, and for other part, you don't use `$(MAKE)` very often. 

(My old superbuild uses cmake+`$(MAKE)` to parallelize everything across packages and target systems.)

**Comment by Neumann-A** [comment]
> It is a vcpkg problem.

Not really. Just means the buildsystem is not really cmake..... CMake build scripts should be agnostic to the generator otherwise using cmake is in itself absurd. 

> $(MAKE)

change to `${MAKE}` and do a `find_program` call ?

**Comment by diehard2** [comment]
@Neumann-A  thanks, I'll try to do a patch that fixes those up. I suppose another alternative is calling cmake directly with the arguments for "Unix Makefiles"

**Comment by dg0yt** [comment]
> > It is a vcpkg problem.
> 
> Not really. Just means the buildsystem is not really cmake..... CMake build scripts should be agnostic to the generator otherwise using cmake is in itself absurd.

This is overstretched. cmake doesn't only specific rules from generic rules. It also deals with configuration prior to deciding which generic rules to feed into the generation.

CMake does allow to choose different systems. vpckg limits this choice in two ways:
 - It always sets a generator.
 - It doesn't allow some common generators such as "Unix Makefiles".

There is no reason for these limitation, given that the build system is run via `cmake --build`.

**Comment by dg0yt** [comment]
> Such issues are generally caused by some macros in the cmake code that are not defined and are not escaped in build.ninja.

No. It is not about *cmake* variables.

Here, it is intentionally using literal `$(MAKE)`, a *make* variable. `$(MAKE)` passes makeflags, in particular parallelism, to sub-makes. This ties the cmake build system to the "Unix Makefiles" generator.

What @Neumann-A proposes is to patch the package to call `make` directly instead of relying on `$(MAKE)` variable. This will work to some extent (no parallelism, maybe additional assumptions about the build environment).

But when there is a widely-used cmake generator (`Unix Makefiles`) that is compatible with a package, and a widely used build tool (`make`) which is compatible with the package, how can `vcpkg_configure_cmake` not support that combination?

**Comment by diehard2** [comment]
I agree with @dg0yt that if CMake has an option/generator that allows this to be used, vcpkg should let me use it. It would also make this much easier on me :D

**Comment by dg0yt** [comment]
@diehard2 You may try the changes from #22626. Note that I updated the `vcpkg_cmake` port, not the legacy maintainer functions.

**Comment by diehard2** [comment]
thanks @dg0yt. I'll try it this afternoon

**Comment by diehard2** [comment]
@dg0yt sorry, I'm still new to vcpkg. I'm on your branch and can see the changes, but I'm not seeing how to hit the new functionality. This is my portfile.cmake (I'm not using the git functions because they don't work with submodules). I'm assuming I'm missing something easy.

find_program(GIT git)
set(GIT_URL "******")
set(GIT_REV "2a8e132e85a527603a3d6d4503ded117d5066eaf")
message(STATUS "port: ${PORT}")


make_directory( ${CURRENT_BUILDTREES_DIR}/src/${PORT})
set(SOURCE_PATH ${CURRENT_BUILDTREES_DIR}/src/${PORT})

message(STATUS "path: ${SOURCE_PATH}")

if(NOT EXISTS "${SOURCE_PATH}/.git")
	message(STATUS "Cloning and fetching submodules")
	vcpkg_execute_required_process(
	  COMMAND ${GIT} clone --recurse-submodules ${GIT_URL} ${SOURCE_PATH}
	  WORKING_DIRECTORY ${SOURCE_PATH}
	  LOGNAME clone
	)

	message(STATUS "Checkout revision ${GIT_REV}")
	vcpkg_execute_required_process(
	  COMMAND ${GIT} checkout ${GIT_REV}
	  WORKING_DIRECTORY ${SOURCE_PATH}
	  LOGNAME checkout
	)
endif()

vcpkg_configure_cmake(
  SOURCE_PATH ${SOURCE_PATH}
  MAYBE_UNUSED_VARIABLES BUILD_NEBULA_SERVER
  GENERATOR "Unix Makefiles"
  OPTIONS -DBUILD_NEBULA_SERVER=OFF
)


vcpkg_install_cmake()
vcpkg_fixup_cmake_targets()

#file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")

**Comment by dg0yt** [comment]
The changes are not in the legacy function `vcpkg_configure_cmake`.
You need to install port `vcpkg-cmake` for your host triplet (in manifests, add a host dependency).
And then call the function prefixed with `vcpkg_cmake`, i.e. `vcpkg_cmake_configure` etc.

**Comment by diehard2** [comment]
Its getting closer. Currently cmake is telling me that I have an argument that is unused in the CMakeLists.txt, but it definitely is used and if I call cmake directly I don't et the warning, and everything builds without issue. The bigger issue is 

gmake: *** No rule to make target 'install'.  Stop. 

from 

 Command failed: /usr/local/bin/cmake --build . --config Debug --target install -- VERBOSE=1 -j13

Thanks for the help on all of this

**Comment by diehard2** [comment]
okay, figured out to add vcpkg_cmake_build(). Not sure what's going on with not being able to find that argument yet

**Comment by JackBoosY** [comment]
> Its getting closer. Currently cmake is telling me that I have an argument that is unused in the CMakeLists.txt, but it definitely is used and if I call cmake directly I don't et the warning, and everything builds without issue. The bigger issue is
> 
> gmake: *** No rule to make target 'install'. Stop.
> 
> from
> 
> Command failed: /usr/local/bin/cmake --build . --config Debug --target install -- VERBOSE=1 -j13
> 
> Thanks for the help on all of this

Does the CMakeLists.txt have `install` content?

**Comment by dg0yt** [comment]
> Currently cmake is telling me that I have an argument that is unused in the CMakeLists.txt

Maybe you have an argument in `OPTIONS` which is only used in a particular configuration. We see this with `CMAKE_DEBUG_POSTFIX` which needs to be placed in `OPTIONS_DEBUG`.
