### ISSUE TITLE
[zlib] <Botan>

### ISSUE THREAD

**Issue by balahv** [microsoft/vcpkg#22372]
Hello.
Botan have compressing support disabled in default configuration.
To enable it need put option --with-zlib. 
I tried make patch. Its working. But may be u will do it better.
Thank you
[botan[zlib].patch.txt](https://github.com/microsoft/vcpkg/files/7813018/botan.zlib.patch.txt)
.

**Comment by FrankXie05** [comment]
@balahv Sorry for the late reply, I think you should open an issue upstream(url: https://github.com/randombit/botan/issues) and we'll update it as soon as they think it works. :)
