### ISSUE TITLE
[gdal] Build error using latest port 3.4.0#6

### ISSUE THREAD

**Issue by sphoto** [microsoft/vcpkg#22381]
**Host Environment**
- OS: Windows 10 21H1
- Compiler: VS2019

**To Reproduce**
`./vcpkg install gdal[core,hdf5,netcdf,postgresql,mysql-libmariadb,libspatialite,supported-default-features]:x64-windows-static-md`

**Failure logs** 
Error: Building package gdal:x64-windows-static-md failed with: BUILD_FAILED

`link /nologo /dll /INCLUDE:OSRValidate  /INCLUDE:OGR_G_GetPointCount  /INCLUDE:OGRRegisterAll /INCLUDE:GDALSimpleImageWarp  /INCLUDE:GDALReprojectImage  /INCLUDE:GDALComputeMedianCutPCT  /INCLUDE:GDALDitherRGB2PCT  /INCLUDE:OCTNewCoordinateTransformation port\*.obj gcore\*.obj alg\*.obj frmts\o\*.obj ogr\ogrsf_frmts\ogrsf_frmts.lib ogr\ogr.lib gnm\*.obj gnm\gnm_frmts\o\*.obj third_party\o\*.obj apps\commonutils.obj apps\gdalinfo_lib.obj apps\gdal_translate_lib.obj apps\gdalwarp_lib.obj apps\ogr2ogr_lib.obj  apps\gdaldem_lib.obj apps\nearblack_lib.obj apps\gdal_grid_lib.obj apps\gdal_rasterize_lib.obj apps\gdalbuildvrt_lib.obj  apps\gdalmdiminfo_lib.obj apps\gdalmdimtranslate_lib.obj    D:/projects/_latest/vcpkg/installed/x64-windows-static-md/debug/lib/libexpatdMD.lib  D:/projects/_latest/vcpkg/installed/x64-windows-static-md/debug/lib/libpq.lib D:/projects/_latest/vcpkg/installed/x64-windows-static-md/debug/lib/libpgcommon.lib D:/projects/_latest/vcpkg/installed/x64-windows-static-md/debug/lib/libpgport.lib Secur32.lib Shell32.lib Advapi32.lib Crypt32.lib Gdi32.lib D:/projects/_latest/vcpkg/installed/x64-windows-static-md/debug/lib/libcrypto.lib D:/projects/_latest/vcpkg/installed/x64-windows-static-md/debug/lib/libssl.lib          D:\projects\_latest\vcpkg\installed\x64-windows-static-md\debug\lib\jpeg.lib /libpath:D:/projects/_latest/vcpkg/installed/x64-windows-static-md/debug/lib netcdf.lib libhdf5_hl_D.lib libhdf5_D.lib libszip_D.lib zlibd.lib libcurl-d.lib winmm.lib ws2_32.lib zlibd.lib advapi32.lib crypt32.lib    D:\projects\_latest\vcpkg\installed\x64-windows-static-md\debug\lib\tiffd.lib /libpath:D:/projects/_latest/vcpkg/installed/x64-windows-static-md/debug/lib proj_d.lib ole32.lib shell32.lib sqlite3.lib tiffd.lib zlibd.lib jpeg.lib lzmad.lib zstd_staticd.lib libcurl-d.lib winmm.lib ws2_32.lib zlibd.lib advapi32.lib crypt32.lib D:/projects/_latest/vcpkg/installed/x64-windows-static-md/debug/lib/sqlite3.lib D:/projects/_latest/vcpkg/installed/x64-windows-static-md/debug/lib/librttopo.lib  D:/projects/_latest/vcpkg/installed/x64-windows-static-md/debug/lib/libmariadb.lib D:/projects/_latest/vcpkg/installed/x64-windows-static-md/debug/lib/geos_cd.lib D:/projects/_latest/vcpkg/installed/x64-windows-static-md/debug/lib/geosd.lib /libpath:D:/projects/_latest/vcpkg/installed/x64-windows-static-md/debug/lib libhdf5_D.lib libszip_D.lib zlibd.lib      D:/projects/_latest/vcpkg/installed/x64-windows-static-md/debug/lib/libcurl-d.lib wsock32.lib wldap32.lib winmm.lib    legacy_stdio_definitions.lib odbc32.lib odbccp32.lib user32.lib  D:/projects/_latest/vcpkg/installed/x64-windows-static-md/debug/lib/libpng16d.lib D:/projects/_latest/vcpkg/installed/x64-windows-static-md/debug/lib/zlibd.lib   D:/projects/_latest/vcpkg/installed/x64-windows-static-md/debug/lib/openjp2.lib            D:/projects/_latest/vcpkg/installed/x64-windows-static-md/debug/lib/webpd.lib   D:\projects\_latest\vcpkg\installed\x64-windows-static-md\debug\lib\freexl.lib    D:/projects/_latest/vcpkg/installed/x64-windows-static-md/debug/lib/libxml2.lib D:/projects/_latest/vcpkg/installed/x64-windows-static-md/debug/lib/iconv.lib D:/projects/_latest/vcpkg/installed/x64-windows-static-md/debug/lib/charset.lib D:/projects/_latest/vcpkg/installed/x64-windows-static-md/debug/lib/lzmad.lib       ws2_32.lib          kernel32.lib psapi.lib wbemuuid.lib gcore\Version.res  /out:gdal_d.dll /implib:gdal_i_d.lib   /debug`

`LINK : fatal error LNK1104: cannot open file 'D:\projects\_latest\vcpkg\installed\x64-windows-static-md\debug\lib\librttopo.lib'`

**Additional context**

Static build failed, due to a bug in `dependency_win.cmake` (wrong double quotes in line 235, 236).

**Comment by dg0yt** [comment]
@sphoto Did it work for you in the past?

libspatialite should come with a pkg-config file now, so we might import libspatialite dependencies like implemented for hdf5 and netcdf-c.

**Comment by sphoto** [comment]
No, I did never use vcpkg to build gdal.

**Comment by dg0yt** [comment]
For static linkage, we must use the rttopo libs when they are used by spatialite. I test a fix in #22370 now. I cannot build windows triplets locally.

**Comment by sphoto** [comment]
I'll try your latest fix and let you if it works.

**Comment by sphoto** [comment]
[#9566c](https://github.com/microsoft/vcpkg/commit/9566c29a795317f27d9889147b283f4ed2a7eddc) works perfectly well. I could build gdal statically with spatialite support. Thank you.

**Comment by LilyWangLL** [comment]
This issue will be closed in PR #22370.
