### ISSUE TITLE
no cmake toochain file(vcpkg.cmake) in vcpkg_installed dir when using Manifest Mode ?

### ISSUE THREAD

**Issue by changnet** [microsoft/vcpkg#22400]
I used to use vcpkg in this way
```bat
.\vcpkg.exe install lua:x64-windows mongo-c-driver:x64-windows openssl:x64-windows libmariadb:x64-windows flatbuffers:x64-windows
.\vcpkg.exe export --raw --output-dir=./pack_and_go_lib/ --output=vcpkg_win_x64 lua:x64-windows mongo-c-driver:x64-windows openssl:x64-windows libmariadb:x64-windows flatbuffers:x64-windows
```
a cmake toolchain file will be placed in `vcpkg_win_x64/scripts/buildsystems/vcpkg.cmake`.  If I copy `vcpkg_win_x64` to someone, he can still use a relative path to build my project(no need to install vcpkg at all).

Lately I try manifest mode, after install, only two dir in vcpkg_installed(vcpkg、x64-windows)，no `scripts\buildsystems\vcpkg.cmake`. Did I use it the wrong way ?
```bat
E:\dev\MServer\project\vcpkg_installed>dir
 E:\dev\MServer\project\vcpkg_installed

2022/01/07  12:04    <DIR>          .
2022/01/07  12:04    <DIR>          ..
2022/01/07  12:04    <DIR>          vcpkg
2022/01/07  12:04    <DIR>          x64-windows
```

I had read some example, they all use the `${VCPKG_ROOT}\scripts\buildsystems\vcpkg.cmake`

my vcpkg.json
```json
{
    "name": "mserver",
    "version": "0.0.1",
    "description": "Mini Distributed Game Server, a lightweight game engine",
    "homepage": "https://github.com/changnet/MServer",
    "supports": "x64",
    "builtin-baseline": "ae91542c8e71634cb937d467f05920653084cc0b",
    "dependencies": [
        {
            "name": "lua",
            "version>=": "5.4.3#3"
        },
        "mongo-c-driver",
        "openssl",
        "libmariadb",
        "flatbuffers"
    ]
}
```
and install cmd
```bat
vcpkg install --triplet=x64-windows
```

**Comment by JackBoosY** [comment]
Yes, because the list mode supports features such as version control, you need to use vcpkg_root, which means you need to use the toolchain file in vcpkg.

**Comment by changnet** [comment]
Is it possible to "install dependency libraries into separated directory like vcpkg export using vcpkg.json" ?
I use vcpkg to build dependency libraries and upload them to svn server.
It is much easier if a project's member use the same binary dependency libraries instead of compile their own.

If not, any plan to add this feature in the future ?

**Comment by JackBoosY** [comment]
Not too possible.
1. In the future, all functions in vcpkg will be migrated to _ports_.
2. All port records are stored in _versions_.

**Comment by dg0yt** [comment]
But you can try "asset caching".

**Comment by dg0yt** [comment]
> But you can try "asset caching".

Sorry, I meant to say "artifact caching"/"Binary caching". ("Asset caching" is for sources.)
Here is the link: https://github.com/microsoft/vcpkg/blob/master/docs/users/binarycaching.md

**Comment by changnet** [comment]
Thanks

But Binary caching still need to install vcpkg.
I may consider using `vcpkg export` or manually write cmake script at a off internet enviroment
