### ISSUE TITLE
Unable to install any package due to 7zip installation fails.

### ISSUE THREAD

**Issue by vishalvaza** [microsoft/vcpkg#22405]
### Discussed in https://github.com/microsoft/vcpkg/discussions/22404

<div type='discussions-op-text'>

<sup>Originally posted by **vishalvaza** January  7, 2022</sup>
Here I tried to install any library i got following error message.

vcpkg install zyre
Computing installation plan...
The following packages will be built and installed:
  * czmq[core]:x86-windows -> 4.2.1
  * vcpkg-cmake[core]:x64-windows -> 2021-12-20
  * vcpkg-cmake-config[core]:x64-windows -> 2021-12-28
  * zeromq[core]:x86-windows -> 4.3.4#2
    zyre[core]:x86-windows -> 2019-07-07#3
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
A suitable version of powershell-core was not found (required v7.2.0). Downloading portable powershell-core v7.2.0...
Extracting powershell-core...
**A suitable version of 7zip was not found (required v19.0.0). Downloading portable 7zip v19.0.0...
Downloading 7zip...
  https://www.7-zip.org/a/7z1900-x64.msi -> C:\TestDev\vcpkg\downloads\7z1900-x64.msi
Error: Failed to download from mirror set:
https://www.7-zip.org/a/7z1900-x64.msi: WinHttpSendRequest() failed: 12030
https://www.7-zip.org/a/7z1900-x64.msi: WinHttpSendRequest() failed: 12030
https://www.7-zip.org/a/7z1900-x64.msi: WinHttpSendRequest() failed: 12030
https://www.7-zip.org/a/7z1900-x64.msi: WinHttpSendRequest() failed: 12030**</div>

**Comment by vishalvaza** [comment]
Tried with different libraries but the error remains the same.

**Comment by JackBoosY** [comment]
Please unzip [this file](https://github.com/microsoft/vcpkg/files/7828185/7z1900-x64.zip), put it to _VCPKG_ROOT/downloads_ and try again.

Thanks.

**Comment by wheezy1749** [comment]
Found this thread and thought I'd share. This was due to a permission problem under windows for me. I had downloaded it to C:/ initially and that messed everything up I guess. A fresh clone in my user directory and this issue went away.
