### ISSUE TITLE
Build boost-parameter:x64-windows failed

### ISSUE THREAD

**Issue by barenet97** [microsoft/vcpkg#22406]
Please create a discussion in https://github.com/microsoft/vcpkg/discussions/new instead.

Error: Building package boost-parameter:x64-windows failed with: BUILD_FAILED

how to solve this

**Comment by JackBoosY** [comment]
Please provide the output and the logs mentioned in the output.

Thanks.

**Comment by JonLiu1993** [comment]
@barenet97 ,Thanks for posting this issue, could you please provide the detail error log?

**Comment by barenet97** [comment]
Problem has been solved,I used vcpkg to install the package.

Thank you guys trying to help me
