### ISSUE TITLE
vcpkg integrate install: wrong path separator

### ISSUE THREAD

**Issue by Snoop05** [microsoft/vcpkg#22413]
`C:\src\vcpkg>vcpkg integrate install`
`Error: Failed to copy file: C:\src\vcpkg\scripts\buildsystems\tmp\vcpkg.user.targets -> C:\Users\Administrator\AppData\Local\vcpkg/vcpkg.user.targets`

- OS: Windows 10 x64 build 19044.1415
- Compiler: VS 2022 v17.0.4 / MSVC v143
- Vcpkg package management program version 2021-12-09-724cea8b33cbf06c645f5095fa29773697da9761

1. vcpkg integrate install
2. See error

Expected behavior:
Use backslash for paths on Windows, provide instuctions of everyhing this thing wants to do when its inadept to do so instead of bailing out on first failure

**Comment by FusionCarcass** [comment]
I was just about to submit this issue as I'm having the same problem.

```
PS C:\dev\vcpkg\> vcpkg.exe integrate install
Error: Failed to copy file: C:\dev\vcpkg\vcpkg\scripts\buildsystems\tmp\vcpkg.user.targets -> C:\Users\helpdesk\AppData\Local\vcpkg/vcpkg.user.targets
```

**Comment by blueneogeo** [comment]
Same problem here, I cannot install vcpkg

**Comment by blueneogeo** [comment]
Workaround:
`./vcpkg.exe integrate install` also does not work. However, adding the git repo directory to the Windows path does make `vcpkg.exe integrate install `work.

**Comment by modtrek** [comment]
Same issue.  Fresh Win 11 dev VM from MS with VS2022 and latest MSVC143.
`C:\vcpkg>.\vcpkg.exe integrate install
Error: Failed to copy file: C:\vcpkg\scripts\buildsystems\tmp\vcpkg.user.targets -> C:\Users\User\AppData\Local\vcpkg/vcpkg.user.targets`

**Comment by PhoebeHui** [comment]
I get vcpkg clean source and couldn't repro this issue locally.

```
C:\vcpkg>vcpkg integrate install
Applied user-wide integration for this vcpkg root.

All MSBuild C++ projects can now #include any installed libraries.
Linking will be handled automatically.
Installing new libraries will make them instantly available.

CMake projects should use: "-DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake"
```

**Comment by JackBoosY** [comment]
Related [code](https://github.com/microsoft/vcpkg-tool/blob/5d329016ab5109460301441304298ed4938e4110/src/vcpkg/commands.integrate.cpp#L254-L264):
```cpp
            const auto appdata_src_path = tmp_dir / "vcpkg.user.targets";
            fs.write_contents(
                appdata_src_path, create_appdata_shortcut(paths.buildsystems_msbuild_targets), VCPKG_LINE_INFO);
            auto appdata_dst_path = get_appdata_targets_path();


            fs.copy_file(appdata_src_path, appdata_dst_path, CopyOptions::overwrite_existing, ec);
            if (ec)
            {
                print2(Color::error, "Error: Failed to copy file: ", appdata_src_path, " -> ", appdata_dst_path, "\n");
                Checks::exit_fail(VCPKG_LINE_INFO);
            }
```

**Comment by JackBoosY** [comment]
Can any one confirm that whether _C:\Users\User\AppData\Local\vcpkg_ exist?

Thanks.

**Comment by modtrek** [comment]
> Can any one confirm that whether _C:\Users\User\AppData\Local\vcpkg_ exist?
> 
> Thanks.

C:\Users\%USERNAME%\AppData\Local\vcpkg did not exist for me.  Manually created the directory and was able to run **vcpkg integrate install** successfully:

```
C:\vcpkg>mkdir C:\Users\%USERNAME%\AppData\Local\vcpkg
C:\vcpkg>vcpkg integrate install
Applied user-wide integration for this vcpkg root.

All MSBuild C++ projects can now #include any installed libraries.
Linking will be handled automatically.
Installing new libraries will make them instantly available.

CMake projects should use: "-DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake"
```

**Comment by JackBoosY** [comment]
Okay, thanks @modtrek !

**Comment by Snoop05** [comment]
@JackBoosY thank you for linking source, i must have overlooked it before
i tried your change but unfortunately it didn't fix it as this wasn't the issue (but now the error at least doesn't attract attention on the inconsistency, preventing false suspicion like mine)

creating the directory indeed fixed it 👍 
wonder why it failed at that task, should have no issues permission wise (or has it never attempted to do so?)

**Comment by JackBoosY** [comment]
> wonder why it failed at that task, should have no issues permission wise (or has it never attempted to do so?)

Any way, I will add code to check whether this folder was created.

**Comment by BillyONeal** [comment]
Fixed by https://github.com/microsoft/vcpkg/pull/22629
