### ISSUE TITLE
[New Port Request] lightstep-tracer-cpp [LightStep Tracer Library]

### ISSUE THREAD

**Issue by h-barthwal** [microsoft/vcpkg#22429]
Library name:
lightstep-tracer-cpp

Library description:
The Lightstep distributed tracing library for C++

Source repository URL:
https://github.com/lightstep/lightstep-tracer-cpp

Project homepage:
https://lightstep.com

Anything else that is useful to know when adding:
Supports grpc and http streaming which can be added as features.

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
