### ISSUE TITLE
bootstrap-vcpkg.sh gets stuck when building on Ubuntu 21.10 on Raspberry Pi 4B

### ISSUE THREAD

**Issue by gary-desroches** [microsoft/vcpkg#22424]
**Describe the bug**
The bootstrap script gets stuck when attempting to build vcpkg from source on Ubuntu 21 ARM64 Raspberry Pi 4B.

I let it run overnight, so I gave it enough time.

**Environment**
- OS: Ubuntu 21.10 ARM64 on a Raspberry Pi 4 Model B with 8GB of RAM
- Compiler: GCC 11.2.0

**To Reproduce**
1. wget -O vcpkg.tar.gz https://github.com/microsoft/vcpkg/archive/master.tar.gz
2. sudo mkdir /opt/vcpkg
3. sudo tar xf vcpkg.tar.gz --strip-components=1 -C /opt/vcpkg
4. sudo /opt/vcpkg/bootstrap-vcpkg.sh
5. It gets stuck on "[0/133] Building CXX object CMakeFiles/vcpkg-test.dir/src/vcpkg-test/configmetadata.cpp.o"

**Expected behavior**
I expected the bootstrap script to successfully build vcpkg from source.

**Failure logs** 
Unable to determine a binary release of vcpkg; attempting to build from source.
Building vcpkg-tool...
-- The CXX compiler identification is GNU 11.2.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting the C++ compiler in use
-- Detecting the C++ compiler in use - gcc
-- Module support is disabled.
-- Version: 8.0.1
-- Build type: Release
-- CXX_STANDARD: 17
-- Performing Test has_std_17_flag
-- Performing Test has_std_17_flag - Success
-- Performing Test has_std_1z_flag
-- Performing Test has_std_1z_flag - Success
-- Performing Test SUPPORTS_USER_DEFINED_LITERALS
-- Performing Test SUPPORTS_USER_DEFINED_LITERALS - Success
-- Performing Test FMT_HAS_VARIANT
-- Performing Test FMT_HAS_VARIANT - Success
-- Required features: cxx_variadic_templates
-- Looking for strtod_l
-- Looking for strtod_l - found
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/vcpkg/buildtrees/_vcpkg/build
[0/2] Re-checking globbed directories...
[0/133] Building CXX object CMakeFiles/vcpkg-test.dir/src/vcpkg-test/configmetadata.cpp.o

**Additional context**
I just installed Ubuntu 21.10 fresh on this Raspberry Pi, and I did a "sudo apt update" followed by a "sudo apt upgrade" to make sure I had the latest versions of all packages.

**Comment by autoantwort** [comment]
And if you rerun it sill stucks? PS: Use git clone for vcpkg or you will get errors later when you try to use versioning.

**Comment by gary-desroches** [comment]
When I tried it again, it sat there for several minutes, then output this error.

FAILED: CMakeFiles/vcpkg-test.dir/src/vcpkg-test/commands.cpp.o
/usr/bin/c++ -DFMT_LOCALE -DVCPKG_BASE_VERSION=2999-12-31 -DVCPKG_VERSION=unknownhash -I/opt/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-12-09/include -I_deps/fmt-src/include -O3 -DNDEBUG -std=c++17 -MD -MT CMakeFiles/vcpkg-test.dir/src/vcpkg-test/commands.cpp.o -MF CMakeFiles/vcpkg-test.dir/src/vcpkg-test/commands.cpp.o.d -o CMakeFiles/vcpkg-test.dir/src/vcpkg-test/commands.cpp.o -c /opt/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-12-09/src/vcpkg-test/commands.cpp
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.

**Comment by dg0yt** [comment]
> c++: fatal error: Killed signal terminated program cc1plus

Out-of-memory? Overheated?

**Comment by JackBoosY** [comment]
> > c++: fatal error: Killed signal terminated program cc1plus
> 
> Out-of-memory? Overheated?

I think so.

**Comment by mark-whitelaw** [comment]
I had this problem, overcame it by adding a 1Gb swap file for the duration of the build

**Comment by JackBoosY** [comment]
So I confirmed that's a memory issue.

**Comment by gary-desroches** [comment]
Thanks.  I can't believe I picked up the wrong Pi board from my shelf.  It had 1 GB of RAM and no swapfile.  The actual Pi 4 Model B builds vcpkg just fine.
