### ISSUE TITLE
[New Port Request] wxSQLite3

### ISSUE THREAD

**Issue by jsnhsu** [microsoft/vcpkg#22430]
Library name: wxSQLite3

Library description: SQLite3 wrapper based on wxWidgets

Source repository URL: https://github.com/utelle/wxsqlite3

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
