### ISSUE TITLE
[readline-(osx|win32|unix)] remove platform dependent ports. 

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#22436]
there should only be one readline port. (see how openssl does it.....)

**Comment by dg0yt** [comment]
Only 27 days ago: https://github.com/microsoft/vcpkg/pull/22000#issuecomment-992223797

**Comment by JackBoosY** [comment]
@dg0yt Now readline uses makefile in non-Windows.

**Comment by dg0yt** [comment]
> @dg0yt Now readline uses makefile in non-Windows.

I know. Still, it would have been less work to just implement it in port `readline`, right from my first comment, before adding new names to the catalog.
And it seems we need a `vcpkg-pkgconfig-validate` as much as the submitted `vcpkg-cmake-validate`.

**Comment by Neumann-A** [comment]
> vcpkg-pkgconfig-validate

In the past vcpkg_fixup_pkgconfig had validation but it was removed since a lot of pc files contain system libs in Libs:. and vcpkg cannot guess all those for all cases.

**Comment by dg0yt** [comment]
> In the past vcpkg_fixup_pkgconfig had validation but it was removed since a lot of pc files contain system libs in Libs:. and vcpkg cannot guess all those for all cases.

No guessing needed. Builds a test project which consumes the pc file. It must break when there is `-lm` for x64-windows.

**Comment by Neumann-A** [comment]
> No guessing needed. 

#13126 was the pr removing the library checks.

**Comment by dg0yt** [comment]
> #13126 was the pr removing the library checks.

However, these were pure script mode checks. I mean building a test project. Takes more CI build time, but should catch such errors quite reliably.

**Comment by Neumann-A** [comment]
> I mean building a test project.

requires symbol usage to detect stuff. And even that is not reliable. If you have already ports depending on the upstream pkgconfig stuff that is better than any arbitrary test. 
In generally the only test needed is to see if the stuff in `Libs:` is existing.

**Comment by dg0yt** [comment]
> If you have already ports depending on the upstream pkgconfig stuff that is better than any arbitrary test.

The problem is that we sometimes/often don't have the ports (yet), or the feature combination isn't tested (yet), or the dependency is not used (yet) due to some cascaded skip, or whatever. When a problem appears in some consuming configuration, it is hard to track down the origin of the problem.
