### ISSUE TITLE
Curl port file

### ISSUE THREAD

**Issue by simon-p-r** [microsoft/vcpkg#2243]
Hi

The curl port file doesn't appear to build with SSPI support, I have tried manually setting CURL_WINDOWS_SSPI define in function vcpkg_configure_cmake but no joy.  Also curl portfile support  for nghttp2  https://github.com/Microsoft/vcpkg/issues/1122 and c-ares would be good.

Thanks

**Comment by NancyLi1013** [comment]
Hi @simon-p-r, thanks for posting this issue. These features have been added. Please update this port and try to use them.
