### ISSUE TITLE
[severe bug] vcpkg can't find Visual Studio 2022 english instance, can't install any packages

### ISSUE THREAD

**Issue by ZMathias** [microsoft/vcpkg#22431]
Fresh build of vcpkg and using Visual Studio 2022. vcpkg can't install any packages, because it fails to find a valid instance of Visual Studio, even though there is one at the exact path it says it couldn't find it.

- OS: [Windows 11 build 22000.376]
- Compiler: latest msvc toolchain v143
 
**Failure logs**
```
Error: in triplet x64-windows: Unable to find a valid Visual Studio instance
     at "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE"
The following Visual Studio instances were considered:
    C:\Program Files\Microsoft Visual Studio\2022\Community
The following paths were examined for Visual Studio instances:
    C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary/Build\vcvarsall.bat
    C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools/MSVC\14.30.30705\bin/HostX86/x86\dumpbin.exe
```

The IDE is at the exact location it tries to find it, and the devenv.exe is also there.

**Comment by Cheney-W** [comment]
Do you have the English package for VS installed? If not, please install the english package first. Thank you!

**Comment by ProgGrey** [comment]
I had the same problem. Solution: download the latest vcpkg.exe from https://github.com/microsoft/vcpkg-tool/releases. Version 2021-12-09 seems to work fine.

**Comment by ZMathias** [comment]
> Do you have the English package for VS installed? If not, please install the english package first. Thank you!

Yes, I specified that in the title of the issue.

**Comment by ZMathias** [comment]
> I had the same problem. Solution: download the latest vcpkg.exe from https://github.com/microsoft/vcpkg-tool/releases. Version 2021-12-09 seems to work fine.

Tried it just now, it doesn't work sadly. The insanely weird thing is that it works on my laptop, that had the exact same Windows version installed.

**Comment by Cheney-W** [comment]
Could you please run the following command in the latest vcpkg and send the output of the Powershell to me? Thank you!
`.\vcpkg install zlib:x64-windows --debug`

**Comment by ZMathias** [comment]
This is the output.
Note that I freshly installed vcpkg before this.
`PS C:\Users\zagon> vcpkg install zlib:x64-windows --debug
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Using vcpkg-root: C:\Users\zagon\vcpkg
[DEBUG] Failed to open: C:\Users\zagon\vcpkg\vcpkg-bundle.json
[DEBUG] Bundle config: readonly=0, usegitregistry=0, embeddedsha=nullopt
[DEBUG] Using scripts-root: C:\Users\zagon\vcpkg\scripts
[DEBUG] Using downloads-root: C:\Users\zagon\vcpkg\downloads
[DEBUG] Using scripts-root: C:\Users\zagon\vcpkg\scripts
[DEBUG] Using builtin-ports: C:\Users\zagon\vcpkg\ports
[DEBUG] Using builtin-registry: C:\Users\zagon\vcpkg\versions
[DEBUG] Using installed-root: C:\Users\zagon\vcpkg\installed
[DEBUG] Using packages-root: C:\Users\zagon\vcpkg\packages
[DEBUG] Using buildtrees-root: C:\Users\zagon\vcpkg\buildtrees
[DEBUG] Default binary cache path is: C:\Users\zagon\AppData\Local\vcpkg\archives
Computing installation plan...
[DEBUG] Found path: C:\Program Files\CMake\bin\cmake.exe
[DEBUG] CreateProcessW("C:\Program Files\CMake\bin\cmake.exe" --version)
[DEBUG] cmd_execute_and_stream_data() returned 0 after    85855 us
[DEBUG] CreateProcessW("C:\Program Files\CMake\bin\cmake.exe" -DVCPKG_ROOT_DIR=C:/Users/zagon/vcpkg -DPACKAGES_DIR=C:/Users/zagon/vcpkg/packages -DBUILDTREES_DIR=C:/Users/zagon/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=C:/Users/zagon/vcpkg/installed -DDOWNLOADS=C:/Users/zagon/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "C:\Users\zagon\vcpkg\buildtrees\0.vcpkg_tags.cmake")
[DEBUG] cmd_execute_and_stream_data() returned 0 after    19632 us
The following packages will be built and installed:
    zlib[core]:x64-windows -> 1.2.11#13
[DEBUG] CreateProcessW("C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -all -prerelease -legacy -products * -format xml)
[DEBUG] cmd_execute_and_stream_data() returned 0 after    87427 us
Error: in triplet x64-windows: Unable to find a valid Visual Studio instance
     at "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE"
The following Visual Studio instances were considered:
    C:\Program Files\Microsoft Visual Studio\2022\Community
The following paths were examined for Visual Studio instances:
    C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary/Build\vcvarsall.bat
    C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools/MSVC\14.30.30705\bin/HostX86/x86\dumpbin.exe
[DEBUG] D:\a\_work\1\s\src\vcpkg\vcpkgpaths.cpp(1347)
[DEBUG] Time in subprocesses: 192914 us
[DEBUG] Time in parsing JSON: 29 us
[DEBUG] Time in JSON reader: 45 us
[DEBUG] Time in filesystem: 19163 us
[DEBUG] Time in loading ports: 1716 us
[DEBUG] Exiting after 229.6 ms (224525 us)`

**Comment by Cheney-W** [comment]
Thanks for your reply!
Could you please send me the screenshot from your VS installer about the components and languages installed in VS2022 Community?

**Comment by sfhacker** [comment]
You can easily find out your VS instances by running a command line script:

![image](https://user-images.githubusercontent.com/25817529/150149231-b20934e1-b266-41d5-b90b-bd31fe286e73.png)


![image](https://user-images.githubusercontent.com/25817529/150149287-b1191451-285f-4bca-9b40-31f39be1effe.png)

**Comment by ZMathias** [comment]
> Thanks for your reply! Could you please send me the screenshot from your VS installer about the components and languages installed in VS2022 Community?

![image](https://user-images.githubusercontent.com/78689074/150175414-7c3c017d-2833-454e-bed3-a312bb8613fa.png)

And for sfhackers' response, I searched system wide with "Everything" and couldn't find a single executable named "pkg-mgr.exe". Should this be included with a VS install? Or should this be something standalone?

**Comment by sfhacker** [comment]
zlib is such a tiny and simple project. It takes one minute to be built from source!
There are DOZENS of reported issues about zlib. It is indeed embarrassing!

Perhaps there is a confusion between x86 & x64?
(C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools/MSVC\14.30.30705\bin/HostX86/x86\dumpbin.exe)

There is no need for English language pack to build and install zlib!
 I'll ask my workmates how they installed zlib on Windows.

**Comment by sfhacker** [comment]
My infrastructure team tell me the use this command line to install zlib on their CI environment.

 `pkg-mgr.exe --msvc-version=2022 install zlib`


![image](https://user-images.githubusercontent.com/25817529/150237229-46e4feda-195a-45b6-9a05-560617431eaf.png)

Can you have a go at it? You may need to update **_pkg-mgr_** tool.

I'll try to sort out this issue and report back.

**Comment by Cheney-W** [comment]
@ZMathias Thanks for your reply! I can confirm that you do have all VS related components installed.
To solve this problem, I want to confirm with you, after you execute `bootstrap-vcpkg.bat`, is vcpkg.exe generated by build or downloaded directly?

**Comment by faysal247** [comment]
The bug packages

**Comment by ZMathias** [comment]
> My infrastructure team tell me the use this command line to install zlib on their CI environment.
> 
> `pkg-mgr.exe --msvc-version=2022 install zlib`
> 
> ![image](https://user-images.githubusercontent.com/25817529/150237229-46e4feda-195a-45b6-9a05-560617431eaf.png)
> 
> Can you have a go at it? You may need to update **_pkg-mgr_** tool.
> 
> I'll try to sort out this issue and report back.



> 

![image](https://user-images.githubusercontent.com/78689074/150411720-81b5b1f4-0a9d-4ec8-8716-28ad18452657.png)
I have the exact same output as you do.

**Comment by ZMathias** [comment]
> @ZMathias Thanks for your reply! I can confirm that you do have all VS related components installed. To solve this problem, I want to confirm with you, after you execute `bootstrap-vcpkg.bat`, is vcpkg.exe generated by build or downloaded directly?

![image](https://user-images.githubusercontent.com/78689074/150412040-16d4811a-8857-4856-9c5d-34b55b678374.png)

Well, I unplugged my ethernet cable while running the bootstrap. It seems it downloads the vcpkg.exe from the github repo.

**Comment by Cheney-W** [comment]
The latest vcpkg.exe is now separate from vcpkg for ease of version control, so it will only be downloaded from the git repository instead of being a separate local build.

**Comment by ZMathias** [comment]
> The latest vcpkg.exe is now separate from vcpkg for ease of version control, so it will only be downloaded from the git repository instead of being a separate local build.

One thing I am sure of is that it has something to do with the environment, sincr vcpkg works on my laptop with the same VS2022 instance and extensions installed. Any ideas?

**Comment by Cheney-W** [comment]
Does this issue still occur when you clone a new vcpkg from the github?

**Comment by ZMathias** [comment]
No, I have no idea what fixed it, since upgrading vcokg from the old version kept the issue alive, but after a clean install and some messing around in the Visual Studio installer, it works.

**Comment by luodaoyi** [comment]
> > 我的基础架构团队告诉我使用此命令行在他们的 CI 环境中安装 zlib。
> > `pkg-mgr.exe --msvc-version=2022 install zlib`
> > ![图像](https://user-images.githubusercontent.com/25817529/150237229-46e4feda-195a-45b6-9a05-560617431eaf.png)
> > 你能试一试吗？您可能需要更新**_pkg-mgr_**工具。
> > 我会尝试解决这个问题并报告回来。
> 
> > 
> 
> ![图像](https://user-images.githubusercontent.com/78689074/150411720-81b5b1f4-0a9d-4ec8-8716-28ad18452657.png) 我的输出与您完全相同。

Hi!  Where can i get 'pkg-mgr.exe' ?
