### ISSUE TITLE
[libogg] Build error

### ISSUE THREAD

**Issue by BAZI-Ilyess** [microsoft/vcpkg#22449]
**Host Environment**
- Windows
I get this error message, any instructions plz.
Error: Building package libogg:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg upd
ate`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+li
bogg
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-fa
ilure.md&title=[libogg]+Build+error
including:
  package: libogg[core]:x64-windows -> 1.3.5
    vcpkg-tool version: 2021-12-09-724cea8b33cbf06c645f5095fa29773697da9761
    vcpkg-scripts version: 03ca9b59a 2022-01-07 (2 days ago)

Additionally, attach any relevant sections from the log files above.

**Comment by FrankXie05** [comment]
@BAZI-Ilyess Thanks for posting this issue, Could you please provide the detail error log?

**Comment by JonLiu1993** [comment]
@BAZI-Ilyess , Could you please provide the detail error log?

**Comment by JonLiu1993** [comment]
Thanks for posting this issue. Please reopen this issue if it still be a problem for you.

**Comment by TokyoSU** [comment]
there is the log:
[x86-windows.vcpkg_abi_info.txt](https://github.com/microsoft/vcpkg/files/8871354/x86-windows.vcpkg_abi_info.txt)
[stdout-x64-windows.log](https://github.com/microsoft/vcpkg/files/8871355/stdout-x64-windows.log)
[stdout-x86-windows.log](https://github.com/microsoft/vcpkg/files/8871356/stdout-x86-windows.log)
[x64-windows.vcpkg_abi_info.txt](https://github.com/microsoft/vcpkg/files/8871357/x64-windows.vcpkg_abi_info.txt)

**Comment by FrankXie05** [comment]
@TokyoSU 
````
https://gitlab.xiph.org/xiph/ogg/-/archive/v1.3.5/ogg-v1.3.5.tar.gz: WinHttpSendRequest() failed: 12175
https://gitlab.xiph.org/xiph/ogg/-/archive/v1.3.5/ogg-v1.3.5.tar.gz: WinHttpSendRequest() failed: 12175
https://gitlab.xiph.org/xiph/ogg/-/archive/v1.3.5/ogg-v1.3.5.tar.gz: WinHttpSendRequest() failed: 12175
https://gitlab.xiph.org/xiph/ogg/-/archive/v1.3.5/ogg-v1.3.5.tar.gz: WinHttpSendRequest() failed: 12175
````
Obviously, this is a TLS issue, and there are 2 ways to resolve this:

-   1. Check your network, it may be that your network filter is filtering the connection.
-   2. Enable TLS 1.2 on your Windows. Please see https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/security/enable-tls-1-2-client.

**Comment by TokyoSU** [comment]
after reinstalling windows 8.1 and doing all install required (visual studio, vcpkg etc..) the error are still there, i think the download for libogg fail because the link is not secure anymore or is only available in windows 10 :'(

**Comment by FrankXie05** [comment]
@TokyoSU I have confirmed that there is no problem with downloading the port from the link of `libogg`. Are you able to download and access manually https://gitlab.xiph.org/xiph/ogg/-/archive/v1.3.5/ogg-v1.3.5.tar.gz OR https://gitlab.xiph.org/xiph/ogg/-/tree/v1.3.5

**Comment by TokyoSU** [comment]
@FrankXie05 Yes, i've said it in my first message :)

**Comment by FrankXie05** [comment]
@TokyoSU Sorry, I can't reproduce your problem. But for error `12175`, this means your Windows operating system has not been configured for TLS 1.2. So although your desktop applications, like browsers, work with TLS 1.2, that doesn't mean that your WinHTTP stack is configured to work with TLS 1.2. 
Solution: 

1.  keep your windows up to date
2.  Configure by following link： https://support.microsoft.com/en-us/topic/update-to-enable-tls-1-1-and-tls-1-2-as-default-secure-protocols-in-winhttp-in-windows-c4bd73d2-31d7-761e-0178-11268bb10392#easy

**Comment by FrankXie05** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.

**Comment by ChthonVII** [comment]
Same issue on a Win8.1 machine (which should have TLS 1.2 by default).

I suspect there's something in the TLS configuration at xiph.org that's just incompatible with some versions of winhttp, despite supposed tls 1.2 support.

Anyway, I'm going to post the workaround for the benefit of anyone else running into this bug:
1. Manually download https://gitlab.xiph.org/xiph/ogg/-/archive/v1.3.5/ogg-v1.3.5.tar.gz using a web browser
2. Paste into [vcpkg install path]\downloads\
3. Rename file to xiph-ogg-v1.3.5.tar.gz 

Also, Microsoft dropped the ball here. Either vcpkg shouldn't be using winhttp, or it shouldn't be treating xiph.org as the canonical download.

**Comment by FrankXie05** [comment]
@ChthonVII Sorry for the confusion, for the port repo, we only provide the official website link to download.

**Comment by AlvinKimata** [comment]
> Manually download https://gitlab.xiph.org/xiph/ogg/-/archive/v1.3.5/ogg-v1.3.5.tar.gz using a web browser
Paste into [vcpkg install path]\downloads\
Rename file to xiph-ogg-v1.3.5.tar.gz


The link provided below seems unavailable. I managed to download the same package through the `xiph.org` website under the downloads section. Here's the link to the package. `https://downloads.xiph.org/releases/ogg/libogg-1.3.5.tar.gz`
