### ISSUE TITLE
Port Request: LLVM

### ISSUE THREAD

**Issue by jsrduck** [Microsoft/vcpkg#2246]
Suite can be downloaded from http://llvm.org/releases/download.html and documentation at http://llvm.org/docs/

Hugely popular suite, but obviously a lot to chew off

**Comment by janisozaur** [comment]
https://github.com/Microsoft/vcpkg/tree/master/ports/llvm

**Comment by jsrduck** [comment]
Thanks, why doesn't it show up yet in vcpkg search?

**Comment by Mixaill** [comment]
```
> .\vcpkg.exe search llvm
llvm                 5.0.0-2          The LLVM Compiler Infrastructure
````

**Comment by ras0219-msft** [comment]
You probably just need to run `git pull` to get the latest bits :) Make sure to re-run bootstrap after!
