### ISSUE TITLE
vcpkg assumes cross-compiling when building for the same OS and ARCH

### ISSUE THREAD

**Issue by mkhon** [microsoft/vcpkg#22476]
****

**Is your feature request related to a problem? Please describe.**
vcpkg assumes cross-compiling when host triplet is not equal to target triplet

However, vcpkg triplet definitions are ARCH-OS-FLAVOR where FLAVOR is "release" (for release-only builds) or static/dynamic and their variations (static-md).

This leads to cross-compilation when for example -release flavor is built on host.

Example: python3 port makes some decisions based on VCPKG_CROSSCOMPILING (ensurepip is executed only when NOT VCPKG_CROSSCOMPILING). So x64-windows-release build does not execute ensurepip

Additionally, "host" dependencies (especially, self-dependencies) do not seem to be needed when target triplet is for the same ARCH and OS as host triplet.

For example, python3 port has a "host" self-dependency (depends on host "python3") so that -release or -static build depends on host python3 package.

**Proposed solution**

(this is just a proposal, there may be side-effects I haven't noticed)

I think the definition of cross-compilation should be changed so that we check only ARCH and OS. This should be safe given that host dependencies are needed to build host tools that are expected to be executed on host triplet during the build: -release, -static or -dynamic flavors can be executed on host so this is not a actually a cross-compilation

1) define VCPKG_CROSSCOMPILING based only on ARCH and OS

```
diff --git a/scripts/cmake/vcpkg_common_definitions.cmake b/scripts/cmake/vcpkg_common_definitions.cmake
index 40c8183f1..670d80c80 100644
--- a/scripts/cmake/vcpkg_common_definitions.cmake
+++ b/scripts/cmake/vcpkg_common_definitions.cmake
@@ -32,7 +32,11 @@ Furthermore the variables CMAKE_FIND_LIBRARY_(PREFIXES|SUFFIXES) are also define
 portfiles are able to use find_library calls to discover dependent libraries within the current triplet for ports.
 #]===]
 
-string(COMPARE NOTEQUAL "${TARGET_TRIPLET}" "${HOST_TRIPLET}" VCPKG_CROSSCOMPILING)
+if(NOT TARGET_TRIPLET STREQUAL HOST_TRIPLET AND NOT TARGET_TRIPLET MATCHES "^${HOST_TRIPLET}-")
+    set(VCPKG_CROSSCOMPILING TRUE)
+else()
+    set(VCPKG_CROSSCOMPILING FALSE)
+endif()
 #Helper variable to identify the Target system. VCPKG_TARGET_IS_<targetname>
 if (NOT DEFINED VCPKG_CMAKE_SYSTEM_NAME OR VCPKG_CMAKE_SYSTEM_NAME STREQUAL "")
     set(VCPKG_TARGET_IS_WINDOWS ON)
```

2) "host" dependencies in vcpkg-tool should map to target triplet if ARCH and OS match host ARCH and OS

I can provide a patch if this change is conceptually acceptable

**Describe alternatives you've considered**

**Additional context**

**Comment by Neumann-A** [comment]
> vcpkg assumes cross-compiling when host triplet is not equal to target triplet

this is by design. If you don't want to have this behavior explicitly pass `--host-triplet` and set it to the same value aus `--triplet`.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
