### ISSUE TITLE
My project has an error when i make it

### ISSUE THREAD

**Issue by alliancebbbb** [microsoft/vcpkg#22474]
Please create a discussion in https://github.com/microsoft/vcpkg/discussions/new instead.
Thanks for help!im green in libigl.so my question is also easy.
this is my question:
  When i configure and generate my project,it successed.but when i make it ,i got an error:its can  not find"tutorial_shared_path.h".how can i get it?and whats it function?

**Comment by Cheney-W** [comment]
1. What's the command you use when installing libigl via vcpkg?
2. Could you describe in detail what you did in this part(When i configure and generate my project,it successed.but when i make it )?

**Comment by alliancebbbb** [comment]
sorry,its my fault and i got the solution.thanks for help
