### ISSUE TITLE
How do I install library on windows with mingw

### ISSUE THREAD

**Issue by KitCarson03** [microsoft/vcpkg#22478]
**Host Environment**
- OS: Windows 10
- Compiler: mingw-w64 gcc 11.2

**To Reproduce**
`./vcpkg install sdl2 --triplet=x64-mingw-dynamic (or static)`

**Failure logs** 

`The following packages will be built and installed:
    sqlite3[core]:x64-mingw-static -> 3.37.0#1
  * vcpkg-cmake[core]:x64-windows -> 2021-12-20
  * vcpkg-cmake-config[core]:x64-windows -> 2021-12-28
Additional packages (*) will be modified to complete this operation.
Error: in triplet x64-windows: Unable to find a valid Visual Studio instance
The following VS instances were excluded because the English language pack is unavailable:
    C:\Program Files\Microsoft Visual Studio\2022\Community
Could not locate a complete Visual Studio instance
The following paths were examined for Visual Studio instances:
    C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary/Build\vcvarsall.bat
    C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools/MSVC\14.30.30705\bin/HostX86/x86\dumpbin.exe`

**Comment by dg0yt** [comment]
You must also set the host triplet to mingw.

**Comment by dg0yt** [comment]
https://github.com/microsoft/vcpkg/blob/master/docs/users/mingw.md#using-mingw-w64-natively-on-windows

**Comment by KitCarson03** [comment]
Solved. thanks. the problem was that i missed to set the environment variables

```
export VCPKG_DEFAULT_TRIPLET=x64-mingw-dynamic
export VCPKG_DEFAULT_HOST_TRIPLET=x64-mingw-dynamic
```

**Comment by PhoebeHui** [comment]
Great to hear!
