### ISSUE TITLE
build failure: qtbase[core,gui,doubleconversion]:x64-windows-static

### ISSUE THREAD

**Issue by sorokin** [microsoft/vcpkg#22482]
**Host Environment**
- OS: Windows 10 2004
- Compiler: MSVC

**To Reproduce**
`./vcpkg install qtbase[core,gui,doubleconversion]:x64-windows-static`

**Failure logs** 
```
-- The following packages have been found:

...

-- The following REQUIRED packages have not been found:

 * WrapPCRE2

-- The following OPTIONAL packages have not been found:

...

CMake Error at C:/Program Files/CMake/share/cmake-3.22/Modules/FeatureSummary.cmake:464 (message):
  feature_summary() Error: REQUIRED package(s) are missing, aborting CMake
  run.
```

**Additional context**

Adding `pcre2` feature fixes the problem: `qtbase[core,gui,doubleconversion,pcre2]:x64-windows-static`.

I think it would be great if pcre2 is added automatically when needed.

**Comment by CuriousUser** [comment]
I have the same issue, help is needed, thank you.
