### ISSUE TITLE
How do I select my registry when using manifest mode?

### ISSUE THREAD

**Issue by keith6014** [microsoft/vcpkg#22486]
In my project I have a vcpkg.json file which states my deps.
```json
{
"name":"foo",
"version":"1.0.0",
"dependencies":["fmt"]
}
```

Lets assume "fmt" port is outated and I would like to use a newest port I create just now in ../vcpkg-registry.

How can I do that in manifest mode?

**Comment by JackBoosY** [comment]
1. Use versioning, see https://github.com/microsoft/vcpkg/blob/master/docs/users/versioning.md#version-constraints
2. Use overlay port, see https://github.com/microsoft/vcpkg/blob/master/docs/specifications/ports-overlay.md

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
