### ISSUE TITLE
[fontconfig] Build error on cross-compile from x64-osx host to arm64-osx target

### ISSUE THREAD

**Issue by kafeg** [microsoft/vcpkg#22498]
**Host Environment**
- OS: macOS Catalina x64-osx
- Compiler: clang / XCode 12.4

**To Reproduce**
`./vcpkg install fontconfig:arm64-osx`

It generates binaries for wrong architecture.

**Comment by PhoebeHui** [comment]
PR https://github.com/microsoft/vcpkg/pull/21772 would solve this issue.

**Comment by kafeg** [comment]
Solved by changes in PR above.
