### ISSUE TITLE
[New Port Request] CLD2

### ISSUE THREAD

**Issue by Cecil-Huang** [microsoft/vcpkg#22499]
Library name:
Compact Language Detector 2

Library description:
CLD2 probabilistically detects over 80 languages in Unicode UTF-8 text, either plain text or HTML/XML. 

Source repository URL:
https://github.com/CLD2Owners/cld2

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
