### ISSUE TITLE
[cuda] Build error

### ISSUE THREAD

**Issue by naveenmarni8** [microsoft/vcpkg#22508]
**Host Environment**
- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**
`./vcpkg install xxxx`

**Failure logs** 
-Cut and paste the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

![image](https://user-images.githubusercontent.com/48897553/149201798-51dd24a7-4502-41ca-8f29-bb5d75dfc57a.png)

**Comment by FrankXie05** [comment]
@naveenmarni8 Thanks for posting this issue, In the following path file, we provide the download method of cuda。And can you download it and try again? :)

- scripts/azure-pipelines/linux/provision-image.sh
https://github.com/microsoft/vcpkg/blob/a9ff505c5b8677af4c09a6e60860b1dde932fccc/scripts/azure-pipelines/linux/provision-image.sh

**Comment by naveenmarni8** [comment]
I am using windows os, can you suggest me other link? By the way, I already downloaded two different versions of cuda from nvidia but no use.

**Comment by FrankXie05** [comment]
@naveenmarni8 Can you explain which port you installed? Because the re-step download you provided is ‘xxxx ’

**Comment by FrankXie05** [comment]
@naveenmarni8 Is still work for this issue? Is the problem still there?

**Comment by FrankXie05** [comment]
@naveenmarni8 Is still work for this issue? Please reply me if the problem still exist and I will reopen it.

**Comment by FrankXie05** [comment]
Confirm

**Comment by naveenmarni8** [comment]
Yes you can close it.
