### ISSUE TITLE
[freeglut] arm64-android build failure

### ISSUE THREAD

**Issue by foobra** [microsoft/vcpkg#22515]
**Host Environment**
- OS: Mac
- Compiler: revision

**To Reproduce**
`./vcpkg install freeglut:arm64-android`

**Failure logs** 

Computing installation plan...
The following packages will be built and installed:
    freeglut[core]:arm64-android -> 3.2.1#7
Detecting compiler hash for triplet arm64-android...
Restored 0 packages from /Users//.cache/vcpkg/archives in 18.56 us. Use --debug to see more details.
Starting package 1/1: freeglut:arm64-android
Building package freeglut[core]:arm64-android...
-- Using community triplet arm64-android. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: /vcpkg/triplets/community/arm64-android.cmake
-- Using cached freeglut-3.2.1.tar.gz.
-- Cleaning sources at /vcpkg/buildtrees/freeglut/src/aced4bbcd3-ea0f90c226.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /Users//Documents/Projects/Migu/MGYX/vcpkg/downloads/freeglut-3.2.1.tar.gz
-- Applying patch use_targets_to_export_x11_dependency.patch
-- Applying patch macOS_Xquartz.patch
-- Applying patch gcc10.patch
-- Applying patch fix-debug-macro.patch
-- Applying patch no_x64_enforcement.patch
-- Using source at /vcpkg/buildtrees/freeglut/src/aced4bbcd3-ea0f90c226.clean
Freeglut currently requires the following libraries from the system package manager:
    opengl
    glu
    libx11
    xrandr
    xi
    xxf86vm

These can be installed on Ubuntu systems via apt-get install libxi-dev libgl1-mesa-dev libglu1-mesa-dev mesa-common-dev libxrandr-dev libxxf86vm-dev
On macOS Xquartz is required.

**Comment by JackBoosY** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
