### ISSUE TITLE
[sqlpp11]update to 0.61

### ISSUE THREAD

**Issue by uuiid** [microsoft/vcpkg#22513]
Library name: sqlpp11

New version number: 0.61

Other information that may be useful (release notes, etc...)
Massive refactor and cleanup release
      The changes below require git/build rules to be changed.
I am expecting the result to be considerably simpler, though.
It will also be much simpler to make changes to the library or
individual connectors now (most of the misc changes below would
have been much harder to do with the former multiple repos).

Some of the misc changes below might break existing code in very
rare cases (I am aware of exactly one).
Happy to help fixing those :-)

**Comment by JonLiu1993** [comment]
Fixed by #25458
