### ISSUE TITLE
"vcpkg remove" regularly fails with "error: directory not empty"

### ISSUE THREAD

**Issue by Tizznt** [microsoft/vcpkg#22520]
The bug: "vcpkg remove" regularly fails with "error: directory not empty"

Environment: Windows 7
Powershell 7.2.1
Visual Studio 2017

To Reproduce:
1. ./vcpkg remove xxbigpackage (e,g, Boost all)
2. See error:
Removal fails with error "directory not empty"

Expected behavior:
ALL of Boost is removed and reinstalled when doing for example  ./vcpkg upgrade

Solution:

See this link : https://stackoverflow.com/questions/1752677/how-to-recursively-delete-an-entire-directory-with-powershell-2-0

Extra context:  (from StackExchange)
When deleting files recursively using a simple Remove-Item "folder" -Recurse I sometimes see an intermittent error : [folder] cannot be removed because it is not empty.

This answer attempts to prevent that error by individually deleting the files.

function Get-Tree($Path,$Include='*') { 
    @(Get-Item $Path -Include $Include -Force) + 
        (Get-ChildItem $Path -Recurse -Include $Include -Force) | 
        sort pspath -Descending -unique
} 

function Remove-Tree($Path,$Include='*') { 
    Get-Tree $Path $Include | Remove-Item -force -recurse
} 

Remove-Tree some_dir

I can confirm this solution ALWAYS works ;-)), but i dont know what file i have to change in vcpkg tree.

**Comment by BillyONeal** [comment]
I think you just got lucky here or are getting "saved" by powershell being slower to do the delete than vcpkg. On Win10 we can engage POSIX delete support which fixes the issue another way but any kind of recursive delete on NT is hindered by NT being a delete-on-close universe, so if anything is held open in the directory by anyone deletion is likely to fail.

**Comment by Cheney-W** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
