### ISSUE TITLE
imgui[core,sdl2-renderer-binding] build failure

### ISSUE THREAD

**Issue by sorokin** [microsoft/vcpkg#22536]
**Host Environment**
- OS: Windows 10 2004
- Compiler: MSVC

**To Reproduce**
`./vcpkg install imgui[core,sdl2-renderer-binding]`

**Failure logs** 

```
C:\w\vcpkg\buildtrees\imgui\src\v1.86-7944920afc.clean\backends\imgui_impl_sdlrenderer.cpp(37): fatal error C1189: #error:  This backend requires SDL 2.0.17+ because of SDL_RenderGeometry() function
```

**Additional context**

The current version of SDL2 in vcpkg is 2.0.16, but imgui requires SDL 2.0.17+. Perhaps this will be fixed by #22290.

**Comment by Cheney-W** [comment]
Fixed by PR: https://github.com/microsoft/vcpkg/pull/22586
