### ISSUE TITLE
vcpkg_configure_make should warn/error on unparsed arguments

### ISSUE THREAD

**Issue by autoantwort** [microsoft/vcpkg#22535]
```
vcpkg_configure_make(
   SOURCE_PATH "${SOURCE_PATH}"
   OPTIOS
      --test=34
)
```
Works without a warning or error. It should print a warning or stops with an error because `OPTIOS` is an unknown argument.  
Discovered in https://github.com/microsoft/vcpkg/pull/22421#issuecomment-1012959754

**Comment by JackBoosY** [comment]
Yes, I'm starting to add this feature.
