### ISSUE TITLE
[gmime] build failure

### ISSUE THREAD

**Issue by refaim** [microsoft/vcpkg#22544]
**Host Environment**
- OS: Windows 10
- Compiler: Microsoft Visual Studio 2017
- vcpkg: master (bba8794b82a0f44b8709f294850a2c8e96b61415)

**To Reproduce**
- Clone https://github.com/refaim/VcpkgGmimeBuildFailure
- Run `msbuild /p:VcpkgEnableManifest=true test.vcxproj`

**Failure logs** 
```
c:\<...>\vcpkg_installed\x64-windows\x64-windows\include\gmime\gmime.h(25): fatal error C1083: Cannot open include file: 'glib.h': No such file or directory [C:\<...>\test.vcxproj]
```
[build.log](https://github.com/microsoft/vcpkg/files/7875192/build.log)

**Additional context**
This failure is most likely not compiler-dependent. According to list of packages in the description of port [gmime 3.2.6#2](https://vcpkg.info/port/gmime) it depends on [glib 2.66.4](https://vcpkg.info/port/glib), however `<glib.h>` is present in 2.52.3 port but was moved to `<glib-2.0\glib.h>` in 2.66.4 port (and later versions).

Also I have no idea why vcpkg installs glib 2.70.1 instead of 2.66.4 (see build.log).

**Comment by Adela0814** [comment]
@refaim please refer to #20483
there are two reasonable fixes here:

**Option 1.** We remove the `glib-2.0` subdirectory: `/include/glib-2.0/glib.h` should become `/include/glib.h`.

Consequence: All users must `#include <glib.h>`.

**Option 2.** We patch every glib include to say` #include <glib-2.0/glib/blah.h>` and change the `.pc` file to include both `/include and /include/glib-2.0` (and similar for CMake).

Consequence: `.pc` and `CMake` users can use `#include <glib.h>` or `#include <glib-2.0/glib.h>`. MSBuild users must use `#include <glib-2.0/glib.h>`.

**Comment by PhoebeHui** [comment]
Duplicated of https://github.com/microsoft/vcpkg/issues/20483.
