### ISSUE TITLE
"Error: in triplet x64-windows: Unable to find a valid Visual Studio instance" even with a valid visual studio instance

### ISSUE THREAD

**Issue by OishikGuha** [microsoft/vcpkg#22548]
I am watching [this video](https://www.youtube.com/watch?v=IfRMV2MY9n0) about machine learning with a Yolo algorithm and in this video it says to install `vcpkg` (by the way, this is the [github repo](https://github.com/AlexeyAB/darknet#how-to-compile-on-windows-using-vcpkg) with those instructions)

and this is the error I got while using the ```.\vcpkg install darknet[opencv-base,cuda,cudnn]:x64-windows``` command:
```
Error: in triplet x64-windows: Unable to find a valid Visual Studio instance
Could not locate a complete Visual Studio instance
The following paths were examined for Visual Studio instances:
    D:\Visual Studio\VC\Auxiliary/Build\vcvarsall.bat
```

**Environment**
- OS: Windows
- Installed Dependency: Visual Studio 2017 (with the english language pack)

**To Reproduce**
1. Have the above environment
2. Execute this sequence of code in your console (I used windows Powershell for this case):
```
>mkdir vcpkg
>cd .\vcpkg\
>git clone https://github.com/microsoft/vcpkg
>cd vcpkg
>$env:VCPKG_ROOT=$PWD
>.\bootstrap-vcpkg.bat
>.\vcpkg install darknet[opencv-base,cuda,cudnn]:x64-windows
```

**Expected behavior**
I expected the process to finish but it gave me this error instead (with full process included):
```
.\vcpkg install darknet[opencv-base,cuda,cudnn]:x64-windows
Computing installation plan...
A suitable version of cmake was not found (required v3.21.1). Downloading portable cmake v3.21.1...
Extracting cmake...
A suitable version of 7zip was not found (required v19.0.0). Downloading portable 7zip v19.0.0...
Downloading 7zip...
  https://www.7-zip.org/a/7z1900-x64.msi -> D:\vcpkg\vcpkg\downloads\7z1900-x64.msi
Extracting 7zip...
The following packages will be built and installed:
  * bzip2[core]:x64-windows -> 1.0.8#2
  * cuda[core]:x64-windows -> 10.1#8
  * cudnn[core]:x64-windows -> 7.6.5#4
    darknet[core,cuda,cudnn,opencv-base]:x64-windows -> 2021-04-16#1
  * ffmpeg[avcodec,avdevice,avfilter,avformat,core,swresample,swscale]:x64-windows -> 4.4.1#5
  * giflib[core]:x64-windows -> 5.2.1#1
  * hdf5[core,szip,zlib]:x64-windows -> 1.12.1#3
  * leptonica[core]:x64-windows -> 1.81.1
  * libarchive[bzip2,core,libxml2,lz4,lzma,openssl,zstd]:x64-windows -> 3.5.2#2
  * libiconv[core]:x64-windows -> 1.16#11
  * libjpeg-turbo[core]:x64-windows -> 2.1.2
  * liblzma[core]:x64-windows -> 5.2.5#4
  * libpng[core]:x64-windows -> 1.6.37#16
  * libwebp[core,nearlossless,simd,unicode]:x64-windows -> 1.2.1
  * libxml2[core]:x64-windows -> 2.9.12#4
  * lz4[core]:x64-windows -> 1.9.3#3
  * opencv[contrib,core,default-features,dnn,ffmpeg]:x64-windows -> 4.5.4#1
  * opencv4[contrib,core,default-features,dnn,ffmpeg,jpeg,png,quirc,tiff,webp]:x64-windows -> 4.5.4#2
  * openjpeg[core]:x64-windows -> 2.4.0
  * openssl[core]:x64-windows -> 1.1.1m
  * protobuf[core]:x64-windows -> 3.18.0#1
  * pthreads[core]:x64-windows -> 3.0.0#10
  * quirc[core]:x64-windows -> 1.1#2
  * stb[core]:x64-windows -> 2020-09-14#1
  * szip[core]:x64-windows -> 2.1.1#7
  * tesseract[core]:x64-windows -> 4.1.1#9
  * tiff[core,jpeg,lzma,zip]:x64-windows -> 4.3.0#4
  * vcpkg-cmake[core]:x64-windows -> 2021-12-20
  * vcpkg-cmake-config[core]:x64-windows -> 2021-12-28
  * vcpkg-pkgconfig-get-modules[core]:x64-windows -> 2021-04-02#1
  * zlib[core]:x64-windows -> 1.2.11#13
  * zstd[core]:x64-windows -> 1.5.0#1
Additional packages (*) will be modified to complete this operation.
Error: in triplet x64-windows: Unable to find a valid Visual Studio instance
Could not locate a complete Visual Studio instance
The following paths were examined for Visual Studio instances:
    D:\Visual Studio\VC\Auxiliary/Build\vcvarsall.bat
```

**Comment by JackBoosY** [comment]
Please check the  required Visual Studio components in https://github.com/microsoft/vcpkg-tool/pull/314.

Thanks.

**Comment by OishikGuha** [comment]
@JackBoosY I will try it out, thanks for giving your time!

**Comment by archika08** [comment]
@OishikGuha Did you find a solution. I am facing the same issue.

**Comment by sfhacker** [comment]
You can easily find out all Visual Studio instances by using this small tool: pkg-mgr

![image](https://user-images.githubusercontent.com/25817529/152683448-02c919e8-b928-4871-9c35-70380aff45c9.png)

**Comment by JackBoosY** [comment]
@archika08 See https://github.com/microsoft/vcpkg-tool/pull/314.

**Comment by the-overdriven** [comment]
> Please check the required Visual Studio components in https://github.com/microsoft/vcpkg-tool/pull/314.
@JackBoosY I don't understand, how to check required components exactly? This is just a link to some pull request.

**Comment by JackBoosY** [comment]
@the-overdriven You can open the Visual Studio Installer to select the components.

**Comment by DeveloperPaul123** [comment]
I'm facing this issue as well but I believe I have all the necessary components installed in Visual Studio 2022

```
Error: in triplet x64-windows: Unable to find a valid Visual Studio instance
     at "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional"
The following Visual Studio instances were considered:
    C:\Program Files\Microsoft Visual Studio\2022\Professional
    C:\Program Files\Microsoft Visual Studio\2022\Professional
    C:\Program Files\Microsoft Visual Studio\2022\Professional
    C:\Program Files\Microsoft Visual Studio\2022\Professional
    C:\Program Files\Microsoft Visual Studio\2022\Professional
    C:\Program Files\Microsoft Visual Studio\2022\Professional
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\
    C:\Program Files (x86)\Microsoft Visual Studio 14.0
    C:\Program Files (x86)\Microsoft Visual Studio 14.0
The following paths were examined for Visual Studio instances:
    C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Auxiliary/Build\vcvarsall.bat
    C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools/MSVC\14.31.31103\bin/HostX86/x86\dumpbin.exe
    C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools/MSVC\14.29.30133\bin/HostX86/x86\dumpbin.exe
    C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools/MSVC\14.16.27023\bin/HostX86/x86\dumpbin.exe
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC/vcvarsall.bat
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC/bin\dumpbin.exe
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC/vcvarsall.bat
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC/bin\dumpbin.exe
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC/vcvarsall.bat
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC/bin\dumpbin.exe
```

Not sure where to go from here

**Comment by chcgjc** [comment]
HELLO
os:window 7 x64
can somebody tell me how to fix this Error: in triplet x64-windows: Unable to find a valid Visual Studio instance
Could not locate a complete Visual Studio instance in visual studio CODE?
this is the .\vcpkg\vcpkg install cpprestsdk cpprestsdk:x64-windows

PS> vcpkg install cpprestsdk cpprestsdk:x64-windows and what is the PS> in this ?

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

**Comment by eeyu** [comment]
installing cmaketools for windows and linux worked for me:
https://stackoverflow.com/questions/72134097/error-installing-openssl-using-vcpkg-on-visual-studio-code-error-in-triplet-x6

**Comment by lattice0** [comment]
Does it really need to be Visual Studio or can it be Visual Studio Build Tools?

**Comment by javeriaashraf111** [comment]
Solved this issue by installing just the Visual Studio Build Tools, which gives MSVC without installing the entire IDE.

**Comment by lattice0** [comment]
Do you have the script for such installation or did you do manually?

-------- Mensagem Original --------
Em 23 de nov. de 2022 16:53, javeriaashraf111 escreveu:

**Comment by drizzle042** [comment]
> Visual Studio Build Tools

There is actually a place to download on Microsoft Website
https://devblogs.microsoft.com/cppblog/introducing-the-visual-studio-build-tools/

**Comment by Draaakos** [comment]
Windows: in my case for fix it:

step1: open  visual studio installer
step2: select modify button
step3: select checbox for desktop development with c++
step4: click in modify button

and try again 😄

**Comment by Perdixky** [comment]
**这是vcpkg的bug**，解决方法：下载最新的vcpkg并覆盖原来的即可。
具体步骤：
1、随便找一个目录执行

 `git clone https://github.com/microsoft/vcpkg`

，然后运行bootstrap-vcpkg.bat进行安装。
2、将安装好的内容覆盖到你原先的vcpkg目录中。
这然的话就实现了vcpkg的重新安装并且不会影响之前安装好的库。
希望这对你有用！
