### ISSUE TITLE
[LIBTOMMATH] The static build library can not be included in a shared library in LINUX

### ISSUE THREAD

**Issue by atopavirgil** [microsoft/vcpkg#22549]
https://github.com/libtom/libtommath

The library build with VCPKG in Linux x64 can be included and works in another static library (as static library).
However if we try to create a shared library (which includes libtommath) we get this message:

libtommath.a(bn_mp_mul.o): relocation R_X86_64_PC32 against symbol `KARATSUBA_MUL_CUTOFF' can not be used when making a shared object; **recompile with -fPIC**

I suppose somwhere in the port the option must be included. 

Triplet used:

set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_CMAKE_SYSTEM_NAME Linux)

During the build using this triplet both static and dynamic libraries are created for libtommath but the program links with the static one.

**Comment by atopavirgil** [comment]
This is not a community-triplet issue (it may be for Android for which I added a sepparate issue). The main problem described here is that Building in Linux x64 which is an official supported configuration (not community) require changes in the PORT file ( adding -fPIC parameter). The sister library libtomcrypt has this parameter in port, libtommath it does not.
The Android problem may be different.

**Comment by LilyWangLL** [comment]
> This is not a community-triplet issue (it may be for Android for which I added a sepparate issue). The main problem described here is that Building in Linux x64 which is an official supported configuration (not community) require changes in the PORT file ( adding -fPIC parameter). The sister library libtomcrypt has this parameter in port, libtommath it does not. The Android problem may be different.

I will repro this issue locally and confirm it soon.

**Comment by LilyWangLL** [comment]
See the comment https://github.com/libtom/libtommath/issues/523#issuecomment-1633755551, this issue still exists when recompile with `-fPIC`.
