### ISSUE TITLE
[icu] build failure

### ISSUE THREAD

**Issue by Eric-JH** [microsoft/vcpkg#22547]
**Host Environment**
- OS: Windows 10
- Compiler: MSVC 2022

**To Reproduce**
`./vcpkg install ITK`

**Failure logs** 
D:\Visual Studio\vcpkg>vcpkg install ITK
Computing installation plan...
The following packages will be built and installed:
  * icu[core]:x64-windows -> 69.1#16
  * icu[core]:x86-windows -> 69.1#16
    itk[core]:x86-windows -> 5.1.0#7
  * libjpeg-turbo[core]:x86-windows -> 2.1.2
  * liblzma[core]:x86-windows -> 5.2.5#4
  * libpng[core]:x86-windows -> 1.6.37#16
  * minc[core]:x86-windows -> 2.4.03#2
  * nifticlib[core,nifti2,nifticdf]:x86-windows -> 2020-04-30#1
  * tiff[core,jpeg,lzma,zip]:x86-windows -> 4.3.0#3
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
-- Automatically setting HTTP(S)_PROXY environment variables to 127.0.0.1:1080
Detecting compiler hash for triplet x86-windows...
Restored 0 packages from C:\Users\26327\AppData\Local\vcpkg\archives in 579.1 us. Use --debug to see more details.
Starting package 1/9: icu:x64-windows
Building package icu[core]:x64-windows...
-- Using cached icu4c-69_1-src.tgz.
-- Cleaning sources at D:/Visual Studio/vcpkg/buildtrees/icu/src/c-69_1-src-86e71a956d.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/Visual Studio/vcpkg/downloads/icu4c-69_1-src.tgz
-- Applying patch disable-escapestr-tool.patch
-- Applying patch remove-MD-from-configure.patch
-- Applying patch fix_parallel_build_on_windows.patch
-- Applying patch fix-extra.patch
-- Applying patch mingw-dll-install.patch
-- Applying patch disable-static-prefix.patch
-- Using source at D:/Visual Studio/vcpkg/buildtrees/icu/src/c-69_1-src-86e71a956d.clean
-- Found external ninja('1.10.2').
-- Getting CMake variables for x64-windows
CMake Warning at scripts/cmake/vcpkg_configure_make.cmake:298 (message):
  Detected whitespace in root directory.  Please move the path to one without
  whitespaces! The required tools do not handle whitespaces correctly and the
  build will most likely fail
Call Stack (most recent call first):
  ports/icu/portfile.cmake:48 (vcpkg_configure_make)
  scripts/ports.cmake:142 (include)

-- Using cached msys-gzip-1.10-1-x86_64.pkg.tar.xz.
-- Using cached msys-bash-4.4.023-2-x86_64.pkg.tar.xz.
-- Using cached msys-autoconf-2.71-1-any.pkg.tar.zst.
-- Using cached msys-diffutils-3.7-1-x86_64.pkg.tar.xz.
-- Using cached msys-binutils-2.34-4-x86_64.pkg.tar.zst.
-- Using cached msys-libtool-2.4.6-9-x86_64.pkg.tar.xz.
-- Using cached msys-file-5.39-1-x86_64.pkg.tar.zst.
-- Using cached msys-zlib-1.2.11-1-x86_64.pkg.tar.xz.
-- Using cached msys-libbz2-1.0.8-2-x86_64.pkg.tar.xz.
-- Using cached msys-coreutils-8.32-1-x86_64.pkg.tar.xz.
-- Using cached msys-grep-3.0-2-x86_64.pkg.tar.xz.
-- Using cached msys-sed-4.8-1-x86_64.pkg.tar.xz.
-- Using cached msys-libpcre-8.44-1-x86_64.pkg.tar.xz.
-- Using cached msys-m4-1.4.19-1-x86_64.pkg.tar.zst.
-- Using cached msys-automake-wrapper-11-1-any.pkg.tar.xz.
-- Using cached msys-gawk-5.1.0-1-x86_64.pkg.tar.xz.
-- Using cached msys-mpfr-4.1.0-1-x86_64.pkg.tar.zst.
-- Using cached msys-gmp-6.2.0-1-x86_64.pkg.tar.xz.
-- Using cached msys-libreadline-8.0.004-1-x86_64.pkg.tar.xz.
-- Using cached msys-ncurses-6.2-1-x86_64.pkg.tar.xz.
-- Using cached msys-automake1.16-1.16.3-1-any.pkg.tar.zst.
-- Using cached msys-perl-5.32.1-1-x86_64.pkg.tar.zst.
-- Using cached msys-libcrypt-2.1-3-x86_64.pkg.tar.zst.
-- Using cached msys-pkg-config-0.29.2-4-x86_64.pkg.tar.zst.
-- Using cached msys-make-4.3-1-x86_64.pkg.tar.xz.
-- Using cached msys-findutils-4.7.0-1-x86_64.pkg.tar.xz.
-- Using cached msys-libintl-0.19.8.1-1-x86_64.pkg.tar.xz.
-- Using cached msys-libiconv-1.16-2-x86_64.pkg.tar.zst.
-- Using cached msys-gcc-libs-9.3.0-1-x86_64.pkg.tar.xz.
-- Using cached msys-msys2-runtime-3.2.0-8-x86_64.pkg.tar.zst.
-- Using msys root at D:/Visual Studio/vcpkg/downloads/tools/msys2/803521c5733336c9
-- Using cached msys-mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst.
-- Using msys root at D:/Visual Studio/vcpkg/downloads/tools/msys2/aa5af7b2aa7e90e8
-- Configuring x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: "D:/Visual Studio/vcpkg/downloads/tools/msys2/803521c5733336c9/usr/bin/bash.exe" --noprofile --norc --debug -c "V=1 CPP='cl.exe -E' CC='cl.exe' CC_FOR_BUILD='cl.exe' CXX='cl.exe' RC='rc.exe' WINDRES='rc.exe' AR='lib.exe' LD='link.exe -verbose' RANLIB=':' STRIP=':' NM='dumpbin.exe -symbols -headers' DLLTOOL='link.exe -verbose -dll' CCAS=':' AS=':' ./../src/c-69_1-src-86e71a956d.clean/source/configure --build=x86_64-pc-mingw32 \"--disable-samples\" \"--disable-tests\" \"--disable-layoutex\" \"ac_cv_prog_ac_ct_STRIP=:\" \"gl_cv_double_slash_root=yes\" \"ac_cv_func_memmove=yes\" \"--disable-silent-rules\" \"--verbose\" \"--enable-shared\" \"--disable-static\" \"--enable-debug\" \"--disable-release\" \"--prefix=/D/Visual Studio/vcpkg/installed/x64-windows/debug\" \"--bindir=\\${prefix}/../tools/icu/debug/bin\" \"--sbindir=\\${prefix}/../tools/icu/debug/sbin\" \"--libdir=\\${prefix}/lib\" \"--includedir=\\${prefix}/../include\" \"--datarootdir=\\${prefix}/share/icu\""
    Working Directory: D:/Visual Studio/vcpkg/buildtrees/icu/x64-windows-dbg
    Error code: 1
    See logs for more information:
      D:\Visual Studio\vcpkg\buildtrees\icu\config-x64-windows-dbg-out.log
      D:\Visual Studio\vcpkg\buildtrees\icu\config-x64-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:796 (vcpkg_execute_required_process)
  ports/icu/portfile.cmake:48 (vcpkg_configure_make)
  scripts/ports.cmake:142 (include)

**Additional context**
[config-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/7876481/config-x64-windows-dbg-err.log)
[config-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/7876482/config-x64-windows-dbg-out.log)

I read the log file and installed python via Visual studio Installer. It didn't worked.

**Comment by dg0yt** [comment]
~~~
./../src/c-69_1-src-86e71a956d.clean/source/configure: line 3878: D:/Visual: No such file or directory
~~~

Move vcpkg to a directory without spaces. Some packages don't handle spaces well.

**Comment by Eric-JH** [comment]
Yeah, your advice is quite useful. Thanks~
