### ISSUE TITLE
[glib] Build error

### ISSUE THREAD

**Issue by lunkyguy** [microsoft/vcpkg#22541]
**Host Environment**
- OS: ubuntu20.04
- Compiler: revision

**To Reproduce**
`./vcpkg install opencv:x64-linux`

**Failure logs** 
Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_meson.cmake:491 (vcpkg_execute_required_process)
  ports/glib/portfile.cmake:46 (vcpkg_configure_meson)
  scripts/ports.cmake:142 (include)

**Comment by JackBoosY** [comment]
Please provide the output and the failure logs mentioned in the output first.

Thanks.

**Comment by lunkyguy** [comment]
I know the issue,I should read the errorlog and sudo apt-get install * what I need
