### ISSUE TITLE
[LIBTOMMATH] The static build library can not be included in a shared library in ANDROID

### ISSUE THREAD

**Issue by atopavirgil** [microsoft/vcpkg#22550]
https://github.com/libtom/libtommath

The static build libtommath can not be used in another shared Android library or linked in an executable (can be included in a static library, however ). Getting the error (for every function):

ld: error: (extra path)/vcpkg/installed/arm64-android/lib/libtommath.a(bn_mp_abs.o) is incompatible with aarch64linux
...

If the library is build as dynamic , the same message is received when the library is linked in the shared library.

It may require some specific flags in the PORT file , as the library builds properly under ARM64, it may be related with specific compiler flags needed.

As a note (may provide help in investigating the issue) the library builds and works in Linux x64 (linked as STATIC) but even there can not be included in another  Dynamic build library.In that case the message is: "libtommath.a(bn_mp_mul.o): relocation R_X86_64_PC32 against symbol `KARATSUBA_MUL_CUTOFF' can not be used when making a shared object; recompile with -fPIC"

Using triplet:

set(VCPKG_TARGET_ARCHITECTURE arm64)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_CMAKE_SYSTEM_NAME Android)

With the latest NDK  (23)

same for 32 bit.

**Comment by atopavirgil** [comment]
Any help with this ? It was confirmed on tommath forum that ARM64 is supported for the lib, and probably needs some flags probably LDFLAGS to build properly. I suppose the port file can do this. Any help apreciated.

**Comment by JackBoosY** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
