### ISSUE TITLE
[mesa] build/acquisition failure

### ISSUE THREAD

**Issue by s0600204** [microsoft/vcpkg#22564]
**Host Environment**
- *OS*: Windows (specifically GitHub Actions' `windows-2016` and `windows-2019` images)
- *Compiler*: Not relevant, as the failure occurs before the compiler comes into play.

**To Reproduce**
```
git clone --depth=1 https://github.com/Microsoft/vcpkg.git --branch=2022.01.01 .
.\bootstrap-vcpkg.bat -disableMetrics
.\vcpkg install mesa[core, opengl]
```

**Failure logs** 
```
Building package mesa[core,opengl]:x86-windows...
-- Downloading https://gitlab.freedesktop.org/mesa/mesa/-/archive/mesa-21.2.5/mesa-mesa-21.2.5.tar.gz -> mesa-mesa-mesa-21.2.5.tar.gz...
Error: Failed to download from mirror set:
File does not have the expected hash:
             url : [ https://gitlab.freedesktop.org/mesa/mesa/-/archive/mesa-21.2.5/mesa-mesa-21.2.5.tar.gz ]
       File path : [ D:\a\0ad\0ad\vc\downloads\mesa-mesa-mesa-21.2.5.tar.gz.2920.part ]
   Expected hash : [ 24387ce5ea0f200b39f930a842fc56fa120dd5cc6a94d175374ce788356dc7ac73e6390a7ffa6a1f2b0eb212cc00f556c7204548118ececb69d3555f0a259bc0 ]
     Actual hash : [ a9ead27f08e862738938cf728928b7937ff37e4c26967f2e46e40a3c8419159397f75b2f4ce43f9b453b35bb3716df581087fb7ba8434fafdfab9488c3db6f92 ]
```

**Additional context**
Downloading the `mesa-mesa-21.2.5.tar.gz` file manually to my own personal machine (which runs ArchLinux) and deriving a hash (`sha512sum ./mesa-mesa-21.2.5.tar.gz`) results in the same `a9ead27...` hash above.

This would imply to me that the hash stated in the port file is incorrect. Why this would be I am unsure.

It may be worth noting that the `portfile.cmake` for the previous version of the `mesa` port (providing `mesa 21.2.0`) stated a hash beginning `4837e4`. Downloading and running `sha512sum` on the `mesa-mesa-21.2.0.tar.gz` file results in a different hash - one beginning `0e92c5`. So either the hashes have been wrong (for at least) two port-versions in a row... or the downloadable `.tar.gz` files have somehow changed/are being auto-generated differently.

**Comment by JackBoosY** [comment]
Confirmed, thanks for reporting this!
