### ISSUE TITLE
Error: Building package openssl:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by acse-mp3014** [microsoft/vcpkg#22580]
### Host environment

- OS: Windows 7 Professional (64-bit version)
- Powershell version: 7.2.1
- C++ compiler: MinGW-w64

### Command used to reproduce

PS C:\vcpkg> `.\vcpkg.exe install boost:x64-windows`

### Logs from running command .\vpckg.exe install boost:x64-windows

**1.  Logs from Command launched & list of packages for installation**

![image](https://user-images.githubusercontent.com/72515880/149733161-fb5d3816-cf73-4a1b-b667-eb62f8058323.png)

**2. Logs from building process**

![image](https://user-images.githubusercontent.com/72515880/149733365-03116602-7e3f-475b-8fdf-a5c538752993.png)

**3.  Logs from first error message**

![image](https://user-images.githubusercontent.com/72515880/149733432-c1caa2fc-2f5d-448f-9031-3d6491d100f5.png)

**4. Logs from second (final) error message**

![image](https://user-images.githubusercontent.com/72515880/149733465-965e870e-b302-4be8-8f87-9005525117dd.png)

**Comment by PhoebeHui** [comment]
@acse-mp3014, could you try below workaround?

1. Download https://www.openssl.org/source/openssl-1.1.1m.tar.gz manually.
2. Rename it to openssl-1.1.1m.tar.gz and put it to vcpkg\downloads folder
3. ./vcpkg install openssl:x64-windows

**Comment by PhoebeHui** [comment]
@acse-mp3014, please reopen this issue if it still be a problem for you.
