### ISSUE TITLE
How do I use the versioning function

### ISSUE THREAD

**Issue by Eric-JH** [microsoft/vcpkg#22582]
According to the versioning part of vcpkg documentation, and I tried to reproduce the example given by [Getting started with versioning](https://github.com/microsoft/vcpkg/blob/master/docs/examples/versioning.getting-started.md). But I failed and I thought the error was caused by the wrong "builtin-baseline". Because it went well if I don't specify the version. 
Here is the log.
[vcpkg-manifest-install.log](https://github.com/microsoft/vcpkg/files/7880369/vcpkg-manifest-install.log)

**Comment by Eric-JH** [comment]
[CmakeVersionTest.zip](https://github.com/microsoft/vcpkg/files/7880391/CmakeVersionTest.zip)
This is the whole code which is same with [Getting started with versioning](https://github.com/microsoft/vcpkg/blob/master/docs/examples/versioning.getting-started.md)

**Comment by JackBoosY** [comment]
```
fatal: not a git repository: 'D:\software\vcpkg\.git'

This may be fixed by updating vcpkg to the latest master via `git pull` or fetching commits via `git fetch`.

Failed to determine the current commit:
fatal: not a git repository: 'D:\software\vcpkg\.git'
```
Please clone vcpkg instead of downloading vcpkg as a zip package.
vcplg needs the git records to implement the versioning feature.

**Comment by Eric-JH** [comment]
> ```
> fatal: not a git repository: 'D:\software\vcpkg\.git'
> 
> This may be fixed by updating vcpkg to the latest master via `git pull` or fetching commits via `git fetch`.
> 
> Failed to determine the current commit:
> fatal: not a git repository: 'D:\software\vcpkg\.git'
> ```
> 
> Please clone vcpkg instead of downloading vcpkg as a zip package. vcplg needs the git records to implement the versioning feature.

Yeah. I cloned vcpkg and the problem was solved. And I still have a question about the builtin-baseline. I read the docs and didn't figure out the meaning. In my point of view, the builtin-baseline is the commited id. But I don't know how to set the proper builtin-baseline. For example, if I want to include the fmt with version >= 7.1.0, what's the builtin-baseline? Is that the commit id of fmt with version of 7.0.3?

**Comment by JackBoosY** [comment]
The content corresponding to the commit id of `builtin-baseline` must be greater than or equal to the version number you need.
