### ISSUE TITLE
[<libmariadb>] build failure please don't change the link lib name

### ISSUE THREAD

**Issue by williamxin** [microsoft/vcpkg#22614]
in vcpkg's old version, libmariadb works perfectly on windows,mac and linux, we can link libmariadb like this:
`find_package(unofficial-libmariadb CONFIG REQUIRED)
    target_link_libraries(main PRIVATE libmariadb mariadbclient)`

but now in the latest version, we have to do it on linux,mac like this:
`find_package(unofficial-libmariadb CONFIG REQUIRED)
    target_link_libraries(main PRIVATE unofficial::libmariadb)`

This caused my program to be incompatible

can you change the link name back to old version, like this:
`find_package(unofficial-libmariadb CONFIG REQUIRED)
    target_link_libraries(main PRIVATE libmariadb mariadbclient)`

**Host Environment**
- OS: [e.g. Linux etc...]
- Compiler: revision

**To Reproduce**
`./vcpkg install libmariadb`

**Comment by williamxin** [comment]
but why the windows version keep unchanged?

`PS C:\secure\Scoop\apps\windows-terminal\current> vcpkg install libmariadb
Computing installation plan...
The following packages are already installed:
    libmariadb[core,openssl,zlib]:x64-windows -> 3.1.12#2
Package libmariadb:x64-windows is already installed
Restored 0 packages from C:\Users\xinyong\AppData\Local\vcpkg\archives in 134 us. Use --debug to see more details.

Total elapsed time: 103.9 ms

The package libmariadb provides CMake targets:

    find_package(unofficial-libmariadb CONFIG REQUIRED)
    target_link_libraries(main PRIVATE libmariadb mariadbclient)`

**Comment by dg0yt** [comment]
> libmariadb[core,openssl,zlib]:x64-windows -> 3.1.12#2

This is the old version, not the rectified version (3.1.15).

**Comment by williamxin** [comment]
ok, I see, thank you

I have another question, can you release a offline version? Many developers are in intranet, they cannot access internet, so it's very difficult to use vcpkg.

also, more developers in china cannot access github freely, we have to use proxy, but the proxy is not stable,  we often use decades of minutes to update vcpkg, can you solve this problem?

thank you!

**Comment by JackBoosY** [comment]
@williamxin We are recommand you to use the assetcaching feature, see https://github.com/microsoft/vcpkg/blob/master/docs/users/assetcaching.md

**Comment by williamxin** [comment]
@JackBoosY I have read your post on zhihu about vcpkg mirror, and I have solved my problem, thank you very much!

Now the download speed is VERY VERY VERY VERY fast!

vcpkg is great!

but still I have one more issue:

`vcpkg install jemalloc                            ✔  10053  15:14:30
Computing installation plan...
The following packages will be built and installed:
    jemalloc[core]:x64-linux -> 4.3.1#5
Detecting compiler hash for triplet x64-linux...
Restored 0 packages from /home/xinyong/.cache/vcpkg/archives in 7.208 us. Use --debug to see more details.
Starting package 1/1: jemalloc:x64-linux
Building package jemalloc[core]:x64-linux...
-- Note: jemalloc only supports dynamic library linkage. Building dynamic library.
-- Downloading https://github.com/jemalloc/jemalloc-cmake/archive/jemalloc-cmake.4.3.1.tar.gz -> jemalloc-jemalloc-cmake-jemalloc-cmake.4.3.1.tar.gz...
-- Extracting source /home/xinyong/github/vcpkg/downloads/jemalloc-jemalloc-cmake-jemalloc-cmake.4.3.1.tar.gz
-- Applying patch fix-cmakelists.patch
-- Applying patch fix-utilities.patch
-- Applying patch fix-static-build.patch
-- Using source at /home/xinyong/github/vcpkg/buildtrees/jemalloc/src/make.4.3.1-c0500eb0e6.clean
-- Configuring x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: /home/xinyong/github/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/bin/cmake /home/xinyong/github/vcpkg/buildtrees/jemalloc/src/make.4.3.1-c0500eb0e6.clean -DGIT_FOUND=OFF -DCMAKE_DISABLE_FIND_PACKAGE_Git=ON -Dwithout-export=OFF -DCMAKE_MAKE_PROGRAM=/home/xinyong/.vcpkg/downloads/tools/ninja-1.10.2-linux/ninja -DCMAKE_SYSTEM_NAME=Linux -DBUILD_SHARED_LIBS=ON -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/home/xinyong/.vcpkg/scripts/toolchains/linux.cmake -DVCPKG_TARGET_TRIPLET=x64-linux -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=external -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=/home/xinyong/.vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_LINKER_FLAGS_RELEASE= -DVCPKG_LINKER_FLAGS_DEBUG= -DVCPKG_TARGET_ARCHITECTURE=x64 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -D_VCPKG_ROOT_DIR=/home/xinyong/github/vcpkg -DZ_VCPKG_ROOT_DIR=/home/xinyong/github/vcpkg -D_VCPKG_INSTALLED_DIR=/home/xinyong/github/vcpkg/installed -DVCPKG_MANIFEST_INSTALL=OFF -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/home/xinyong/github/vcpkg/packages/jemalloc_x64-linux/debug
    Working Directory: /home/xinyong/github/vcpkg/buildtrees/jemalloc/x64-linux-dbg
    Error code: 1
    See logs for more information:
      /home/xinyong/github/vcpkg/buildtrees/jemalloc/config-x64-linux-dbg-out.log
      /home/xinyong/github/vcpkg/buildtrees/jemalloc/config-x64-linux-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:358 (vcpkg_execute_required_process)
  ports/jemalloc/portfile.cmake:20 (vcpkg_configure_cmake)
  scripts/ports.cmake:142 (include)


Error: Building package jemalloc:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `./vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+jemalloc
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[jemalloc]+Build+error
including:
  package: jemalloc[core]:x64-linux -> 4.3.1#5
    vcpkg-tool version: 2021-12-09-724cea8b33cbf06c645f5095fa29773697da9761
    vcpkg-scripts version: 4184491f0 2022-01-17 (24 hours ago)

Additionally, attach any relevant sections from the log files above.
`

**Comment by dg0yt** [comment]
@williamxin This is no longer related to the original issue. Please create separate issues or discussions.
