### ISSUE TITLE
[azure-kinect-sensor-sdk] supports field should be "linux | windows"

### ISSUE THREAD

**Issue by yuanchen-zhu** [microsoft/vcpkg#22623]
The commit 66dc12b3fa1863bf60afe75f2cfdd41298e52ee5 changed the support field in vcpkg.json from "!oxs" to "linux & windows", but it won't work on any system since the correct field should be "linux | windows".

**Comment by PhoebeHui** [comment]
@yuanchen-zhu, thanks for reporting this issue!
