### ISSUE TITLE
could you please disable  debug option of the package librdkafka[ENABLE_REFCNT_DEBUG]

### ISSUE THREAD

**Issue by chris-shenzhen-china** [microsoft/vcpkg#22622]
OS: linux
Issue:  so many debug info below.
could you please disable build option: ENABLE_REFCNT_DEBUG

REFCNT DEBUG: &(rkbuf->rkbuf_rkb)->rkb_refcnt 10 -1: 0x7ffff00114d8: rd_kafka_buf_destroy_final:73
REFCNT DEBUG: &(response)->rkbuf_refcnt 1 -1: 0x7fffd0001158: rd_kafka_buf_callback:497
REFCNT DEBUG: &(rkbuf->rkbuf_rkb)->rkb_refcnt 9 -1: 0x7ffff00114d8: rd_kafka_buf_destroy_final:73
REFCNT DEBUG: (&(rkb)->rkb_refcnt) 8 +1: 0x7ffff00114d8: rd_kafka_buf_new_request0:141
REFCNT DEBUG: &rktp->rktp_refcnt 5 +1: 0x7fffd80022f0: rd_kafka_broker_fetch_toppars:4900
REFCNT DEBUG: &rktp->rktp_refcnt 5 +1: 0x7fffd80033a0: rd_kafka_broker_fetch_toppars:4900
REFCNT DEBUG: &rktp->rktp_refcnt 1 +1: 0x7fffe802af80: rd_kafka_topic_scan_all:1493
REFCNT DEBUG: &_RKTP->rktp_refcnt 2 -1: 0x7fffe802af80: rd_kafka_topic_scan_all:1530
REFCNT DEBUG: &rktp->rktp_refcnt 2 +1: 0x7fffd4001120: rd_kafka_topic_scan_all:1493
REFCNT DEBUG: &_RKTP->rktp_refcnt 3 -1: 0x7fffd4001120: rd_kafka_topic_scan_all:1530
REFCNT DEBUG: &rktp->rktp_refcnt 6 +1: 0x7fffd80022f0: rd_kafka_topic_partition_list_add_copy:2905
REFCNT DEBUG: &rktp->rktp_refcnt 6 +1: 0x7fffd80033a0: rd_kafka_topic_partition_list_add_copy:2905
REFCNT DEBUG: &_RKTP->rktp_refcnt 7 -1: 0x7fffd80022f0: rd_kafka_topic_partition_destroy0:2748
REFCNT DEBUG: &_RKTP->rktp_refcnt 7 -1: 0x7fffd80033a0: rd_kafka_topic_partition_destroy0:2748
REFCNT DEBUG: &(request)->rkbuf_refcnt 1 -1: 0x7fffd80016c8: rd_kafka_buf_callback:495
REFCNT DEBUG: &rktp->rktp_refcnt 1 +1: 0x7fffd8001e10: rd_kafka_topic_scan_all:1493
REFCNT DEBUG: &_RKTP->rktp_refcnt 2 -1: 0x7fffd8001e10: rd_kafka_topic_scan_all:1530
REFCNT DEBUG: &rktp->rktp_refcnt 6 +1: 0x7fffd80022f0: rd_kafka_topic_scan_all:1493
REFCNT DEBUG: &_RKTP->rktp_refcnt 7 -1: 0x7fffd80022f0: rd_kafka_topic_scan_all:1530
REFCNT DEBUG: &rktp->rktp_refcnt 1 +1: 0x7fffd8002dd0: rd_kafka_topic_scan_all:1493

**Comment by Adela0814** [comment]
Can you provide the steps of reproduction? and gcc/cmake version.
You can try to change `-DENABLE_REFCNT_DEBUG=ON` to `OFF` in `vcpkg\ports\librdkafka\portfile.cmake`. then re-install librdkafka via vcpkg. I wonder if this can reduce your unnecessary log.

**Comment by Adela0814** [comment]
@chris-shenzhen-china  any update?

**Comment by Adela0814** [comment]
Thanks for posting this issue. Please reopen this issue if it still be a problem for you.

**Comment by Lilolbet** [comment]
This should probably be reopened as it is not fixed. @chris-shenzhen-china failed to link to another issue he opened, where the maintainer asserts that this property is for the development of the library itself. Therefore it should not be switched on if the library is 'just' a dependency.

Link to issue/maintainer comment https://github.com/edenhill/librdkafka/issues/3654#issuecomment-1015447105
