### ISSUE TITLE
[<jemalloc>] build failure jemalloc cannot be installed on ubuntu

### ISSUE THREAD

**Issue by williamxin** [microsoft/vcpkg#22627]
**Host Environment**
- OS: Ubuntu20
- Compiler: revision

**To Reproduce**
`./vcpkg install jemalloc`

**Failure logs** 
`vcpkg install jemalloc                            ✔  10053  15:14:30
Computing installation plan...
The following packages will be built and installed:
    jemalloc[core]:x64-linux -> 4.3.1#5
Detecting compiler hash for triplet x64-linux...
Restored 0 packages from /home/xinyong/.cache/vcpkg/archives in 7.208 us. Use --debug to see more details.
Starting package 1/1: jemalloc:x64-linux
Building package jemalloc[core]:x64-linux...
-- Note: jemalloc only supports dynamic library linkage. Building dynamic library.
-- Downloading https://github.com/jemalloc/jemalloc-cmake/archive/jemalloc-cmake.4.3.1.tar.gz -> jemalloc-jemalloc-cmake-jemalloc-cmake.4.3.1.tar.gz...
-- Extracting source /home/xinyong/github/vcpkg/downloads/jemalloc-jemalloc-cmake-jemalloc-cmake.4.3.1.tar.gz
-- Applying patch fix-cmakelists.patch
-- Applying patch fix-utilities.patch
-- Applying patch fix-static-build.patch
-- Using source at /home/xinyong/github/vcpkg/buildtrees/jemalloc/src/make.4.3.1-c0500eb0e6.clean
-- Configuring x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: /home/xinyong/github/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/bin/cmake /home/xinyong/github/vcpkg/buildtrees/jemalloc/src/make.4.3.1-c0500eb0e6.clean -DGIT_FOUND=OFF -DCMAKE_DISABLE_FIND_PACKAGE_Git=ON -Dwithout-export=OFF -DCMAKE_MAKE_PROGRAM=/home/xinyong/.vcpkg/downloads/tools/ninja-1.10.2-linux/ninja -DCMAKE_SYSTEM_NAME=Linux -DBUILD_SHARED_LIBS=ON -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/home/xinyong/.vcpkg/scripts/toolchains/linux.cmake -DVCPKG_TARGET_TRIPLET=x64-linux -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=external -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=/home/xinyong/.vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_LINKER_FLAGS_RELEASE= -DVCPKG_LINKER_FLAGS_DEBUG= -DVCPKG_TARGET_ARCHITECTURE=x64 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -D_VCPKG_ROOT_DIR=/home/xinyong/github/vcpkg -DZ_VCPKG_ROOT_DIR=/home/xinyong/github/vcpkg -D_VCPKG_INSTALLED_DIR=/home/xinyong/github/vcpkg/installed -DVCPKG_MANIFEST_INSTALL=OFF -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/home/xinyong/github/vcpkg/packages/jemalloc_x64-linux/debug
    Working Directory: /home/xinyong/github/vcpkg/buildtrees/jemalloc/x64-linux-dbg
    Error code: 1
    See logs for more information:
      /home/xinyong/github/vcpkg/buildtrees/jemalloc/config-x64-linux-dbg-out.log
      /home/xinyong/github/vcpkg/buildtrees/jemalloc/config-x64-linux-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:358 (vcpkg_execute_required_process)
  ports/jemalloc/portfile.cmake:20 (vcpkg_configure_cmake)
  scripts/ports.cmake:142 (include)

Error: Building package jemalloc:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `./vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+jemalloc
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[jemalloc]+Build+error
including:
  package: jemalloc[core]:x64-linux -> 4.3.1#5
    vcpkg-tool version: 2021-12-09-724cea8b33cbf06c645f5095fa29773697da9761
    vcpkg-scripts version: 4184491f0 2022-01-17 (24 hours ago)

Additionally, attach any relevant sections from the log files above.
`

**Comment by JackBoosY** [comment]
Please provide the following logs first:
/home/xinyong/github/vcpkg/buildtrees/jemalloc/config-x64-linux-dbg-out.log
/home/xinyong/github/vcpkg/buildtrees/jemalloc/config-x64-linux-dbg-err.log

Thanks.

**Comment by williamxin** [comment]
config-x64-linux-dbg-out.log

`-- The C compiler identification is GNU 9.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- CMAKE_C_COMPILER_ID: GNU
-- Configuring incomplete, errors occurred!
See also "/home/xinyong/github/vcpkg/buildtrees/jemalloc/x64-linux-dbg/CMakeFiles/CMakeOutput.log".`


config-x64-linux-dbg-err.log

`CMake Error at Utilities.cmake:779 (CHECK_C_COMPILER_FLAG):
  Unknown CMake command "CHECK_C_COMPILER_FLAG".
Call Stack (most recent call first):
  CMakeLists.txt:150 (JeCflagsAppend)
`

**Comment by JackBoosY** [comment]
I think your manually installed cmake version is too low, please update or remove it then try again.

**Comment by williamxin** [comment]
on my centos7
`cmake version 3.21.0-rc2

CMake suite maintained and supported by Kitware (kitware.com/cmake).`


on my ubuntu20
`cmake version 3.16.3

CMake suite maintained and supported by Kitware (kitware.com/cmake).`

I think the version is quite high

**Comment by williamxin** [comment]
on my mac, the cmake version is 3.22
jemalloc can not be installed either

`cmake version 3.22.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).`


`Will@MacBook-Pro  ~/.vcpkg   master  vcpkg install jemalloc
Computing installation plan...
The following packages will be built and installed:
    jemalloc[core]:x64-osx -> 4.3.1#5
Detecting compiler hash for triplet x64-osx...
Restored 0 packages from /Users/Will/.cache/vcpkg/archives in 67.75 us. Use --debug to see more details.
Starting package 1/1: jemalloc:x64-osx
Building package jemalloc[core]:x64-osx...
-- Note: jemalloc only supports dynamic library linkage. Building dynamic library.
-- Using cached jemalloc-jemalloc-cmake-jemalloc-cmake.4.3.1.tar.gz.
-- Cleaning sources at /Users/Will/github/vcpkg/buildtrees/jemalloc/src/make.4.3.1-c0500eb0e6.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /Users/Will/github/vcpkg/downloads/jemalloc-jemalloc-cmake-jemalloc-cmake.4.3.1.tar.gz
-- Applying patch fix-cmakelists.patch
-- Applying patch fix-utilities.patch
-- Applying patch fix-static-build.patch
-- Using source at /Users/Will/github/vcpkg/buildtrees/jemalloc/src/make.4.3.1-c0500eb0e6.clean
-- Found external ninja('1.10.2').
-- Configuring x64-osx-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: /usr/local/Cellar/cmake/3.22.1/bin/cmake /Users/Will/github/vcpkg/buildtrees/jemalloc/src/make.4.3.1-c0500eb0e6.clean -DGIT_FOUND=OFF -DCMAKE_DISABLE_FIND_PACKAGE_Git=ON -Dwithout-export=OFF -DCMAKE_MAKE_PROGRAM=/usr/local/bin/ninja -DCMAKE_SYSTEM_NAME=Darwin -DBUILD_SHARED_LIBS=ON -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/Users/Will/.vcpkg/scripts/toolchains/osx.cmake -DVCPKG_TARGET_TRIPLET=x64-osx -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=external -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=/Users/Will/.vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_LINKER_FLAGS_RELEASE= -DVCPKG_LINKER_FLAGS_DEBUG= -DVCPKG_TARGET_ARCHITECTURE=x64 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -D_VCPKG_ROOT_DIR=/Users/Will/github/vcpkg -DZ_VCPKG_ROOT_DIR=/Users/Will/github/vcpkg -D_VCPKG_INSTALLED_DIR=/Users/Will/github/vcpkg/installed -DVCPKG_MANIFEST_INSTALL=OFF -DCMAKE_OSX_ARCHITECTURES=x86_64 -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/Users/Will/github/vcpkg/packages/jemalloc_x64-osx/debug
    Working Directory: /Users/Will/github/vcpkg/buildtrees/jemalloc/x64-osx-dbg
    Error code: 1
    See logs for more information:
      /Users/Will/github/vcpkg/buildtrees/jemalloc/config-x64-osx-dbg-out.log
      /Users/Will/github/vcpkg/buildtrees/jemalloc/config-x64-osx-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:358 (vcpkg_execute_required_process)
  ports/jemalloc/portfile.cmake:20 (vcpkg_configure_cmake)
  scripts/ports.cmake:142 (include)


Error: Building package jemalloc:x64-osx failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `./vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+jemalloc
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[jemalloc]+Build+error
including:
  package: jemalloc[core]:x64-osx -> 4.3.1#5
    vcpkg-tool version: 2021-12-09-724cea8b33cbf06c645f5095fa29773697da9761
    vcpkg-scripts version: 5ef52b5b7 2022-01-19 (16 hours ago)

Additionally, attach any relevant sections from the log files above.`

**Comment by dg0yt** [comment]
> I think your manually installed cmake version is too low, please update or remove it then try again.

Pointless.
When port jemalloc is build by vcpkg, vcpkg normally takes its own copy of CMake. It does so in daily CI, and fails:
https://dev.azure.com/vcpkg/public/_build/results?buildId=66017&view=logs&j=f79cfdd7-47a8-597f-8f57-dc3e21a8f2ad&t=da63cf11-1f12-503b-6d64-3b2fb713c172

In PR CI it is skipped:
~~~
jemalloc:arm64-windows=fail
jemalloc:arm-uwp=fail
jemalloc:x64-linux=fail
jemalloc:x64-osx=fail
jemalloc:x64-uwp=fail
jemalloc:x64-windows-static=fail
~~~

**Comment by sfhacker** [comment]
Some people and/or organisations publish releases without testing! That goes against best practices.

Avoid jemalloc cmake version. It is completely broken and it is old.

We do not use Linux or Mac but on Windows it works fine.

Just built jemalloc 5.2.1 from source. No issues at all.

![image](https://user-images.githubusercontent.com/25817529/150347910-5d891047-152a-4821-b23c-612af32eaf79.png)

**Comment by Neumann-A** [comment]
@JackBoosY close?
