### ISSUE TITLE
Display message shows it's downloading from github not from mirror when i am using vcpkg mirror

### ISSUE THREAD

**Issue by williamxin** [microsoft/vcpkg#22628]
****

**Is your feature request related to a problem? Please describe.**
I am using vcpkg mirror http://106.15.181.5/, when I install ports, it still displays downloading from github, not from your mirror

`Computing installation plan...
The following packages will be built and installed:
    protobuf[core]:x64-linux -> 3.18.0#1
Detecting compiler hash for triplet x64-linux...
Restored 0 packages from /home/xinyong/.cache/vcpkg/archives in 15.58 us. Use --debug to see more details.
Starting package 1/1: protobuf:x64-linux
Building package protobuf[core]:x64-linux...
-- Downloading https://github.com/protocolbuffers/protobuf/archive/v3.18.0.tar.gz -> protocolbuffers-protobuf-v3.18.0.tar.gz...
-- Extracting source /home/xinyong/github/vcpkg/downloads/protocolbuffers-protobuf-v3.18.0.tar.gz
-- Applying patch fix-static-build.patch
-- Applying patch fix-default-proto-file-path.patch
-- Applying patch fix-uwp-build.patch
-- Applying patch fix-mingw-build.patch
-- Using source at /home/xinyong/github/vcpkg/buildtrees/protobuf/src/v3.18.0-296107ec8b.clean
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Fixing pkgconfig file: /home/xinyong/github/vcpkg/packages/protobuf_x64-linux/lib/pkgconfig/protobuf-lite.pc
-- Fixing pkgconfig file: /home/xinyong/github/vcpkg/packages/protobuf_x64-linux/lib/pkgconfig/protobuf.pc
-- Fixing pkgconfig file: /home/xinyong/github/vcpkg/packages/protobuf_x64-linux/debug/lib/pkgconfig/protobuf-lite.pc
-- Fixing pkgconfig file: /home/xinyong/github/vcpkg/packages/protobuf_x64-linux/debug/lib/pkgconfig/protobuf.pc
-- Installing: /home/xinyong/github/vcpkg/packages/protobuf_x64-linux/share/protobuf/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: /home/xinyong/.cache/vcpkg/archives/b3/b389ce8e8cbb0126760d89395c350e31e1979d61f81e608a658da96e8f329878.zip
Installing package protobuf[core]:x64-linux...
Elapsed time for package protobuf:x64-linux: 4.357 min

Total elapsed time: 4.367 min

The package protobuf provides CMake targets:

    find_package(protobuf CONFIG REQUIRED)
    target_link_libraries(main PRIVATE protobuf::libprotoc protobuf::libprotobuf protobuf::libprotobuf-lite)
`

**Proposed solution**
vcpkg can tell me downloading from mirror

**Describe alternatives you've considered**

**Additional context**

**Comment by JackBoosY** [comment]
My mirror may not update the port in time, please file an issue at [gitee](https://gitee.com/jackboosy/vcpkg/issues) instead of here.

Thanks.

**Comment by williamxin** [comment]
ok
