### ISSUE TITLE
Build failure: qtbase:x64-windows

### ISSUE THREAD

**Issue by CuriousUser** [microsoft/vcpkg#22632]
**Host Environment**
- OS: Windows 10
- Compiler: MSVC

**To Reproduce**
`.\vcpkg install qtbase`

**Failure logs** 

```
Computing installation plan...
The following packages will be built and installed:
  * qtbase[brotli,concurrent,core,dbus,default-features,doubleconversion,freetype,gui,harfbuzz,icu,jpeg,network,openssl,pcre2,png,sql,sql-psql,sql-sqlite,testlib,widgets,zstd]:x64-windows -> 6.2.2#2
    qtbase[brotli,concurrent,core,dbus,default-features,doubleconversion,freetype,gui,harfbuzz,icu,jpeg,network,openssl,pcre2,png,sql,sql-psql,sql-sqlite,testlib,widgets,zstd]:x86-windows -> 6.2.2#2
  * sqlite3[core]:x86-windows -> 3.37.0#1
  * zstd[core]:x86-windows -> 1.5.2
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Detecting compiler hash for triplet x86-windows...
Restored 0 packages from C:\Users\Redouane\AppData\Local\vcpkg\archives in 539.9 us. Use --debug to see more details.
Starting package 1/4: qtbase:x64-windows
Building package qtbase[brotli,concurrent,core,dbus,default-features,doubleconversion,freetype,gui,harfbuzz,icu,jpeg,network,openssl,pcre2,png,sql,sql-psql,sql-sqlite,testlib,widgets,zstd]:x64-windows...
-- Using cached F:/Software/DEV/vcpkg/downloads/qtbase-61fbf7596beda0178e213a7ba945bc0314153366.tar.gz
-- Cleaning sources at F:/Software/DEV/vcpkg/buildtrees/qtbase/src/0314153366-104b8f293d.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source F:/Software/DEV/vcpkg/downloads/qtbase-61fbf7596beda0178e213a7ba945bc0314153366.tar.gz
-- Applying patch allow_outside_prefix.patch
-- Applying patch clang-cl_source_location.patch
-- Applying patch config_install.patch
-- Applying patch dont_force_cmakecache.patch
-- Applying patch fix_cmake_build.patch
-- Applying patch harfbuzz.patch
-- Applying patch fix_egl.patch
-- Using source at F:/Software/DEV/vcpkg/buildtrees/qtbase/src/0314153366-104b8f293d.clean
-- Configuring x64-windows
CMake Warning at scripts/cmake/vcpkg_configure_cmake.cmake:410 (message):
  The following variables are not used in CMakeLists.txt:

      CMAKE_DISABLE_FIND_PACKAGE_CUPS
      CMAKE_DISABLE_FIND_PACKAGE_PPS
      CMAKE_DISABLE_FIND_PACKAGE_X11
      CMAKE_DISABLE_FIND_PACKAGE_XCB
      CMAKE_DISABLE_FIND_PACKAGE_XKB
      CMAKE_DISABLE_FIND_PACKAGE_XKB_COMMON_X11
      CMAKE_DISABLE_FIND_PACKAGE_XRender
      FEATURE_appstore-compliant
      INPUT_sqlite
      QT_NO_MAKE_EXAMPLES
      QT_NO_MAKE_TESTS

  Please recheck them and remove the unnecessary options from the
  `vcpkg_configure_cmake` call.

  If these options should still be passed for whatever reason, please use the
  `MAYBE_UNUSED_VARIABLES` argument.
Call Stack (most recent call first):
  ports/qtbase/cmake/qt_install_submodule.cmake:88 (vcpkg_configure_cmake)
  ports/qtbase/cmake/qt_install_submodule.cmake:257 (qt_cmake_configure)
  ports/qtbase/portfile.cmake:216 (qt_install_submodule)
  scripts/ports.cmake:142 (include)


-- Building x64-windows-dbg
-- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:156 (message):
    Command failed: F:/Software/DEV/vcpkg/downloads/tools/cmake-3.21.1-windows/cmake-3.21.1-windows-i386/bin/cmake.exe --build . --config Release --target install -- -v -j9
    Working Directory: F:/Software/DEV/vcpkg/buildtrees/qtbase/x64-windows-rel
    See logs for more information:
      F:\Software\DEV\vcpkg\buildtrees\qtbase\install-x64-windows-rel-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:106 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:44 (vcpkg_build_cmake)
  ports/qtbase/cmake/qt_install_submodule.cmake:262 (vcpkg_install_cmake)
  ports/qtbase/portfile.cmake:216 (qt_install_submodule)
  scripts/ports.cmake:142 (include)


Error: Building package qtbase:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+qtbase
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[qtbase]+Build+error
including:
  package: qtbase[brotli,concurrent,core,dbus,default-features,doubleconversion,freetype,gui,harfbuzz,icu,jpeg,network,openssl,pcre2,png,sql,sql-psql,sql-sqlite,testlib,widgets,zstd]:x64-windows -> 6.2.2#2
    vcpkg-tool version: 2021-12-09-724cea8b33cbf06c645f5095fa29773697da9761
    vcpkg-scripts version: 291b84e65 2022-01-18 (10 hours ago)

Additionally, attach any relevant sections from the log files above.
```

**Additional context**
I tried the following commands:

As suggested in the error report:
-> "git pull" and ".\vcpkg update"

As suggested in #22584:
.\vcpkg install qtbase[core,gui,doubleconversion]:x64-windows-static
.\vcpkg install qtbase[core,gui,doubleconversion,pcre2]:x64-windows-static

**Comment by Neumann-A** [comment]
Please provide:    `F:\Software\DEV\vcpkg\buildtrees\qtbase\install-x64-windows-rel-out.log`

It is a bit suspicious that only the release build fails.

**Comment by CuriousUser** [comment]
[install-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/7896084/install-x64-windows-rel-out.log)

**Comment by Neumann-A** [comment]
`C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt\wrl\module.h(1427): error C2039: 'CheckForDuplicateEntries': is not a member of 'Microsoft::WRL::Details'`

**Comment by Neumann-A** [comment]
https://help.appveyor.com/discussions/problems/26088-checkforduplicateentries-is-not-a-member-of-microsoftwrldetails

Probably an issue with the Windows SDK. Not related with the port itself, so not my issues ;P

**Comment by CuriousUser** [comment]
And what is this Windows SDK?

**Comment by Neumann-A** [comment]
> And what is this Windows SDK?

Search engine (e.g. google)?
https://en.wikipedia.org/wiki/Microsoft_Windows_SDK

`C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\` <- That is the Windows SDK installation . 
It gets installed alongside Visual Studio unless you manually untick it. Remove that version and replace it with something newer (at least 10.0.18362.0 as indicated by the linked discussion in https://github.com/microsoft/vcpkg/issues/22632#issuecomment-1016292420)

**Comment by CuriousUser** [comment]
Thank you, I'll try it and report back with the results

**Comment by CuriousUser** [comment]
The installation now has completed without any errors, now all is left is to verify the code that I wrote if it works properly.
Thank you so much for your help!



`Computing installation plan...
The following packages will be built and installed:
  * qtbase[brotli,concurrent,core,dbus,default-features,doubleconversion,freetype,gui,harfbuzz,icu,jpeg,network,openssl,pcre2,png,sql,sql-psql,sql-sqlite,testlib,widgets,zstd]:x64-windows -> 6.2.2#2
    qtbase[brotli,concurrent,core,dbus,default-features,doubleconversion,freetype,gui,harfbuzz,icu,jpeg,network,openssl,pcre2,png,sql,sql-psql,sql-sqlite,testlib,widgets,zstd]:x86-windows -> 6.2.2#2
  * sqlite3[core]:x86-windows -> 3.37.0#1
  * zstd[core]:x86-windows -> 1.5.2
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Detecting compiler hash for triplet x86-windows...
Restored 0 packages from C:\Users\Redouane\AppData\Local\vcpkg\archives in 542.5 us. Use --debug to see more details.
Starting package 1/4: qtbase:x64-windows
Building package qtbase[brotli,concurrent,core,dbus,default-features,doubleconversion,freetype,gui,harfbuzz,icu,jpeg,network,openssl,pcre2,png,sql,sql-psql,sql-sqlite,testlib,widgets,zstd]:x64-windows...
-- Using cached F:/Software/DEV/vcpkg/downloads/qtbase-61fbf7596beda0178e213a7ba945bc0314153366.tar.gz
-- Cleaning sources at F:/Software/DEV/vcpkg/buildtrees/qtbase/src/0314153366-104b8f293d.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source F:/Software/DEV/vcpkg/downloads/qtbase-61fbf7596beda0178e213a7ba945bc0314153366.tar.gz
-- Applying patch allow_outside_prefix.patch
-- Applying patch clang-cl_source_location.patch
-- Applying patch config_install.patch
-- Applying patch dont_force_cmakecache.patch
-- Applying patch fix_cmake_build.patch
-- Applying patch harfbuzz.patch
-- Applying patch fix_egl.patch
-- Using source at F:/Software/DEV/vcpkg/buildtrees/qtbase/src/0314153366-104b8f293d.clean
-- Configuring x64-windows
CMake Warning at scripts/cmake/vcpkg_configure_cmake.cmake:410 (message):
  The following variables are not used in CMakeLists.txt:

      CMAKE_DISABLE_FIND_PACKAGE_CUPS
      CMAKE_DISABLE_FIND_PACKAGE_PPS
      CMAKE_DISABLE_FIND_PACKAGE_X11
      CMAKE_DISABLE_FIND_PACKAGE_XCB
      CMAKE_DISABLE_FIND_PACKAGE_XKB
      CMAKE_DISABLE_FIND_PACKAGE_XKB_COMMON_X11
      CMAKE_DISABLE_FIND_PACKAGE_XRender
      FEATURE_appstore-compliant
      INPUT_sqlite
      QT_NO_MAKE_EXAMPLES
      QT_NO_MAKE_TESTS

  Please recheck them and remove the unnecessary options from the
  `vcpkg_configure_cmake` call.

  If these options should still be passed for whatever reason, please use the
  `MAYBE_UNUSED_VARIABLES` argument.
Call Stack (most recent call first):
  ports/qtbase/cmake/qt_install_submodule.cmake:88 (vcpkg_configure_cmake)
  ports/qtbase/cmake/qt_install_submodule.cmake:257 (qt_cmake_configure)
  ports/qtbase/portfile.cmake:216 (qt_install_submodule)
  scripts/ports.cmake:142 (include)


-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: F:/Software/DEV/vcpkg/packages/qtbase_x64-windows/share/qtbase/copyright
-- Installing: F:/Software/DEV/vcpkg/packages/qtbase_x64-windows/share/qtbase/qt_port_details.cmake
-- Installing: F:/Software/DEV/vcpkg/packages/qtbase_x64-windows/tools/Qt6/bin/qmake.debug.bat
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\Redouane\AppData\Local\vcpkg\archives\29\29bc6fe2914537f5377d71208b8d33f7754cd5375b731d825226606e145e24e1.zip
Installing package qtbase[brotli,concurrent,core,dbus,default-features,doubleconversion,freetype,gui,harfbuzz,icu,jpeg,network,openssl,pcre2,png,sql,sql-psql,sql-sqlite,testlib,widgets,zstd]:x64-windows...
Elapsed time for package qtbase:x64-windows: 23.79 min
Starting package 2/4: sqlite3:x86-windows
Building package sqlite3[core]:x86-windows...
-- Using cached sqlite-amalgamation-3370000.zip.
-- Cleaning sources at F:/Software/DEV/vcpkg/buildtrees/sqlite3/src/3370000-2bb42c52da.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source F:/Software/DEV/vcpkg/downloads/sqlite-amalgamation-3370000.zip
-- Applying patch fix-arm-uwp.patch
-- Using source at F:/Software/DEV/vcpkg/buildtrees/sqlite3/src/3370000-2bb42c52da.clean
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Fixing pkgconfig file: F:/Software/DEV/vcpkg/packages/sqlite3_x86-windows/lib/pkgconfig/sqlite3.pc
-- Using cached msys-mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst.
-- Using msys root at F:/Software/DEV/vcpkg/downloads/tools/msys2/aa5af7b2aa7e90e8
-- Fixing pkgconfig file: F:/Software/DEV/vcpkg/packages/sqlite3_x86-windows/debug/lib/pkgconfig/sqlite3.pc
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\Redouane\AppData\Local\vcpkg\archives\07\077809c9b7649f8e9bb274369c961eb00891b1515b0d1451f20dc8cf2246ea35.zip
Installing package sqlite3[core]:x86-windows...
Elapsed time for package sqlite3:x86-windows: 21.29 s
Starting package 3/4: zstd:x86-windows
Building package zstd[core]:x86-windows...
-- Using cached facebook-zstd-f4a552a3fa24d9078f84157bd40e4f1bad49c488.tar.gz.
-- Extracting source F:/Software/DEV/vcpkg/downloads/facebook-zstd-f4a552a3fa24d9078f84157bd40e4f1bad49c488.tar.gz
-- Applying patch install_pkgpc.patch
-- Using source at F:/Software/DEV/vcpkg/buildtrees/zstd/src/1bad49c488-399422de62.clean
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Fixing pkgconfig file: F:/Software/DEV/vcpkg/packages/zstd_x86-windows/lib/pkgconfig/libzstd.pc
-- Using cached msys-mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst.
-- Using msys root at F:/Software/DEV/vcpkg/downloads/tools/msys2/aa5af7b2aa7e90e8
-- Fixing pkgconfig file: F:/Software/DEV/vcpkg/packages/zstd_x86-windows/debug/lib/pkgconfig/libzstd.pc
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\Redouane\AppData\Local\vcpkg\archives\08\0894f4480ff4d49a35478ac9535881b8a066c0d007028f484cd3d75ac7e7b459.zip
Installing package zstd[core]:x86-windows...
Elapsed time for package zstd:x86-windows: 16.62 s
Starting package 4/4: qtbase:x86-windows
Building package qtbase[brotli,concurrent,core,dbus,default-features,doubleconversion,freetype,gui,harfbuzz,icu,jpeg,network,openssl,pcre2,png,sql,sql-psql,sql-sqlite,testlib,widgets,zstd]:x86-windows...
-- Using cached F:/Software/DEV/vcpkg/downloads/qtbase-61fbf7596beda0178e213a7ba945bc0314153366.tar.gz
-- Cleaning sources at F:/Software/DEV/vcpkg/buildtrees/qtbase/src/0314153366-104b8f293d.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source F:/Software/DEV/vcpkg/downloads/qtbase-61fbf7596beda0178e213a7ba945bc0314153366.tar.gz
-- Applying patch allow_outside_prefix.patch
-- Applying patch clang-cl_source_location.patch
-- Applying patch config_install.patch
-- Applying patch dont_force_cmakecache.patch
-- Applying patch fix_cmake_build.patch
-- Applying patch harfbuzz.patch
-- Applying patch fix_egl.patch
-- Using source at F:/Software/DEV/vcpkg/buildtrees/qtbase/src/0314153366-104b8f293d.clean
-- Configuring x86-windows
CMake Warning at scripts/cmake/vcpkg_configure_cmake.cmake:410 (message):
  The following variables are not used in CMakeLists.txt:

      CMAKE_DISABLE_FIND_PACKAGE_CUPS
      CMAKE_DISABLE_FIND_PACKAGE_PPS
      CMAKE_DISABLE_FIND_PACKAGE_X11
      CMAKE_DISABLE_FIND_PACKAGE_XCB
      CMAKE_DISABLE_FIND_PACKAGE_XKB
      CMAKE_DISABLE_FIND_PACKAGE_XKB_COMMON_X11
      CMAKE_DISABLE_FIND_PACKAGE_XRender
      FEATURE_appstore-compliant
      INPUT_sqlite
      QT_NO_MAKE_EXAMPLES
      QT_NO_MAKE_TESTS

  Please recheck them and remove the unnecessary options from the
  `vcpkg_configure_cmake` call.

  If these options should still be passed for whatever reason, please use the
  `MAYBE_UNUSED_VARIABLES` argument.
Call Stack (most recent call first):
  ports/qtbase/cmake/qt_install_submodule.cmake:88 (vcpkg_configure_cmake)
  ports/qtbase/cmake/qt_install_submodule.cmake:257 (qt_cmake_configure)
  ports/qtbase/portfile.cmake:216 (qt_install_submodule)
  scripts/ports.cmake:142 (include)


-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Installing: F:/Software/DEV/vcpkg/packages/qtbase_x86-windows/share/qtbase/copyright
-- Installing: F:/Software/DEV/vcpkg/packages/qtbase_x86-windows/share/qtbase/qt_port_details.cmake
-- Installing: F:/Software/DEV/vcpkg/packages/qtbase_x86-windows/tools/Qt6/bin/qmake.debug.bat
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\Redouane\AppData\Local\vcpkg\archives\d3\d35dec4f10605158943b2b7967c62dbd08940cc443a1a4947a14708c71e8a474.zip
Installing package qtbase[brotli,concurrent,core,dbus,default-features,doubleconversion,freetype,gui,harfbuzz,icu,jpeg,network,openssl,pcre2,png,sql,sql-psql,sql-sqlite,testlib,widgets,zstd]:x86-windows...
Elapsed time for package qtbase:x86-windows: 23.16 min

Total elapsed time: 47.7 min

The package qtbase provides CMake targets:

    find_package(Qt6 CONFIG REQUIRED)
    # Note: 46 target(s) were omitted.
    target_link_libraries(main PRIVATE __PPS DB2::DB2 PPS::PPS Platform)

    find_package(Qt6Concurrent CONFIG REQUIRED)
    target_link_libraries(main PRIVATE Qt::Concurrent Qt6::Concurrent Qt::ConcurrentPrivate Qt6::ConcurrentPrivate)

    find_package(Qt6Core CONFIG REQUIRED)
    target_link_libraries(main PRIVATE Qt::Core Qt6::Core Qt::CorePrivate Qt6::CorePrivate)

    find_package(Qt6DBus CONFIG REQUIRED)
    target_link_libraries(main PRIVATE Qt::DBus Qt6::DBus Qt::DBusPrivate Qt6::DBusPrivate)

    find_package(Qt6DeviceDiscoverySupportPrivate CONFIG REQUIRED)
    target_link_libraries(main PRIVATE Qt::DeviceDiscoverySupportPrivate Qt6::DeviceDiscoverySupportPrivate)

    find_package(Qt6EntryPointPrivate CONFIG REQUIRED)
    target_link_libraries(main PRIVATE Qt::EntryPointPrivate Qt6::EntryPointPrivate Qt6::EntryPointImplementation)

    find_package(Qt6FbSupportPrivate CONFIG REQUIRED)
    target_link_libraries(main PRIVATE Qt::FbSupportPrivate Qt6::FbSupportPrivate)

    find_package(Qt6Gui CONFIG REQUIRED)
    # Note: 8 target(s) were omitted.
    target_link_libraries(main PRIVATE Qt::Gui Qt6::Gui Qt::GuiPrivate Qt6::GuiPrivate)

    find_package(Qt6Network CONFIG REQUIRED)
    # Note: 4 target(s) were omitted.
    target_link_libraries(main PRIVATE Qt::Network Qt6::Network Qt6::QNLMNIPlugin Qt::NetworkPrivate)

    find_package(Qt6OpenGL CONFIG REQUIRED)
    target_link_libraries(main PRIVATE Qt::OpenGL Qt6::OpenGL Qt::OpenGLPrivate Qt6::OpenGLPrivate)

    find_package(Qt6OpenGLWidgets CONFIG REQUIRED)
    target_link_libraries(main PRIVATE Qt::OpenGLWidgets Qt6::OpenGLWidgets Qt::OpenGLWidgetsPrivate Qt6::OpenGLWidgetsPrivate)

    find_package(Qt6PrintSupport CONFIG REQUIRED)
    target_link_libraries(main PRIVATE Qt::PrintSupport Qt6::PrintSupport Qt::PrintSupportPrivate Qt6::PrintSupportPrivate)

    find_package(Qt6Sql CONFIG REQUIRED)
    # Note: 2 target(s) were omitted.
    target_link_libraries(main PRIVATE Qt::Sql Qt6::Sql Qt::SqlPrivate Qt6::SqlPrivate)

    find_package(Qt6Test CONFIG REQUIRED)
    target_link_libraries(main PRIVATE Qt::Test Qt6::Test Qt::TestPrivate Qt6::TestPrivate)

    find_package(Qt6Widgets CONFIG REQUIRED)
    # Note: 1 target(s) were omitted.
    target_link_libraries(main PRIVATE Qt::Widgets Qt6::Widgets Qt::WidgetsPrivate Qt6::WidgetsPrivate)

    find_package(Qt6Xml CONFIG REQUIRED)
    target_link_libraries(main PRIVATE Qt::Xml Qt6::Xml Qt::XmlPrivate Qt6::XmlPrivate)

    find_package(find-modules CONFIG REQUIRED)
    target_link_libraries(main PRIVATE EGL::EGL X11::XCB GLIB2::GLIB2)

    find_package(kwin CONFIG REQUIRED)
    target_link_libraries(main PRIVATE XKB::XKB gbm::gbm Libdrm::Libdrm Libinput::Libinput)`

**Comment by JackBoosY** [comment]
We will discover whether this issue is about Windows SDK.

**Comment by CuriousUser** [comment]
I guess it is because Windows SDK was the only variable, still, further investigation is always good. Thank you again.

**Comment by Neumann-A** [comment]
@JackBoosY  It is an SDK issues. It has been fixed in a newer version. It is not a vcpkg issue. Case closed, nothing to see here from a vcpkg perspective. General advice: Don't use old WinSDKs since you can select the WinAPI by a macro independent of the SDK version. (https://docs.microsoft.com/en-us/cpp/porting/modifying-winver-and-win32-winnt?view=msvc-170)
