### ISSUE TITLE
[zlib] Restclient Build error

### ISSUE THREAD

**Issue by Calvin-LLC** [microsoft/vcpkg#22644]
**Host Environment**
- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**
`./vcpkg install restclient-cpp`

**Failure logs** 
The following packages will be built and installed:
  * curl[core,non-http,schannel,ssl,sspi]:x86-windows -> 7.81.0
    restclient-cpp[core]:x86-windows -> 0.5.2#1
  * zlib[core]:x86-windows -> 1.2.11#13
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x86-windows...
Restored 0 packages from C:\Users\sospo\AppData\Local\vcpkg\archives in 558.6 us. Use --debug to see more details.
Starting package 1/3: zlib:x86-windows
Building package zlib[core]:x86-windows...
-- Using cached zlib1211.tar.gz.
-- Cleaning sources at C:/libs/vcpkg/buildtrees/zlib/src/1.2.11-e9a093319e.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/libs/vcpkg/downloads/zlib1211.tar.gz
-- Applying patch cmake_dont_build_more_than_needed.patch
-- Applying patch 0001-Prevent-invalid-inclusions-when-HAVE_-is-set-to-0.patch
-- Applying patch add_debug_postfix_on_mingw.patch
-- Applying patch 0002-android-build-mingw.patch
-- Using source at C:/libs/vcpkg/buildtrees/zlib/src/1.2.11-e9a093319e.clean
-- Found external ninja('1.10.2').
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: ninja -v
    Working Directory: C:/libs/vcpkg/buildtrees/zlib/x86-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\libs\vcpkg\buildtrees\zlib\config-x86-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:345 (vcpkg_execute_required_process)
  ports/zlib/portfile.cmake:23 (vcpkg_configure_cmake)
  scripts/ports.cmake:142 (include)

Error: Building package zlib:x86-windows failed with: BUILD_FAILED

including:
  package: zlib[core]:x86-windows -> 1.2.11#13
    vcpkg-tool version: 2021-12-09-724cea8b33cbf06c645f5095fa29773697da9761
    vcpkg-scripts version: 5ef52b5b7 2022-01-19 (9 hours ago)

**Additional context**
Attempted to download things listed here:
https://github.com/microsoft/vcpkg-tool/pull/314
through visual studio community's installer.

[config-x86-windows-out.log](https://github.com/microsoft/vcpkg/files/7902078/config-x86-windows-out.log)

**Comment by JackBoosY** [comment]
```
    LINK : fatal error LNK1104: cannot open file 'ucrtd.lib'
    ninja: build stopped: subcommand failed.
```
Please ensure you've installed the Windows SDK first.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
