### ISSUE TITLE
[New Port Request] <webrtc>

### ISSUE THREAD

**Issue by chris-shenzhen-china** [microsoft/vcpkg#22646]
Library name: webrtc

Library description: Build Custom Video Experiences

Source repository URL:   https://webrtc.googlesource.com/src/

Project homepage (if different from the source repository):  https://webrtc.org/?hl=en

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by Nemirtingas** [comment]
Duplicate with #6205 and #12134 ?

**Comment by JackBoosY** [comment]
Duplicate of #6205.
