### ISSUE TITLE
include ITK

### ISSUE THREAD

**Issue by Eric-JH** [microsoft/vcpkg#22641]
**Describe the bug**
I used vcpkg to manage the inclusion. In the CMakeLists.txt of my project, I included ITK. But the error occured. The content of CMakeLists is same as the example given by ITK docs. 

**Environment**
- OS: Windows 10
- Compiler: msvc 2022

**Failure logs** 
The log was given by MSVC
CMake Error at F:/Github/vcpkg/scripts/buildsystems/vcpkg.cmake:540 (_add_executable): Target "TestDll" links to target "GTest::Main" but the target was not found.  Perhaps a find_package() call is missing for an IMPORTED target, or an ALIAS target is missing?

**Additional context**
[CMakeLists.txt](https://github.com/microsoft/vcpkg/files/7900872/CMakeLists.txt)

**Comment by Cheney-W** [comment]
If you use the itk from vcpkg, please ensure that your project contains the following:
CMakeSettings.json:
```
"variables": [
   {
     "name": "CMAKE_TOOLCHAIN_FILE",
     "value": "{vcpkg_path}/scripts/buildsystems/vcpkg.cmake"
   }
 ]
```
CMakeLists.txt:
```
find_package(ITK CONFIG REQUIRED)
target_link_libraries(TestDll PRIVATE ITKFFT ITKVTK ITKznz itksys)
```

**Comment by Eric-JH** [comment]
> If you use the itk from vcpkg, please ensure that your project contains the following: CMakeSettings.json:
> 
> ```
> "variables": [
>    {
>      "name": "CMAKE_TOOLCHAIN_FILE",
>      "value": "{vcpkg_path}/scripts/buildsystems/vcpkg.cmake"
>    }
>  ]
> ```
> 
> CMakeLists.txt:
> 
> ```
> find_package(ITK CONFIG REQUIRED)
> target_link_libraries(TestDll PRIVATE ITKFFT ITKVTK ITKznz itksys)
> ```

I'm sure of my cmake-toolchain is right. And the main problem is why i can't use the example in [ITK docs](https://itk.org/ItkSoftwareGuide.pdf). I proposed the issue in [ITK issues](https://github.com/InsightSoftwareConsortium/ITK/issues/3111). And they thought the error was caused by vcpkg. 
I understand the usage of `target_link_libraries(TestDll PRIVATE ITKFFT ITKVTK ITKznz itksys)`. But I want a more convenient way to include, like `${g2o_LIBS} ${ceres_LIBRARIES} ${OpenCV_LIBS}`  so that I don't need to specify the module in CMakeLists. Now the problem is there is a similar way to include ITK according to ITK docs, but it's not feasible maybe due to vcpkg.
