### ISSUE TITLE
[zlib] build failure, Failed to download file

### ISSUE THREAD

**Issue by olejniczak** [microsoft/vcpkg#22656]
vcpkg is trying to download a file:

**mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz**

that does not exist on any mirror server.

There are:

_mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst 01-Oct-2020 11:12              281245
mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar...> 01-Oct-2020 11:15                 438
mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst 29-Nov-2020 10:15              281274
mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar...> 29-Nov-2020 10:28                 438_

Build log:

Starting package 1/8: zlib:x86-windows
Building package zlib[core]:x86-windows...
Could not locate cached archive: C:\Users\oley\AppData\Local\vcpkg\archives\d5\d53a55ba543da4693230bedbc6e560f558d47240.zip
-- Using cached D:/src/projects/VcPkgNuGetGenerator/src/vcpkg/downloads/zlib1211.tar.gz
-- Cleaning sources at D:/src/projects/VcPkgNuGetGenerator/src/vcpkg/buildtrees/zlib/src/1.2.11-63309e48e5.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/src/projects/VcPkgNuGetGenerator/src/vcpkg/downloads/zlib1211.tar.gz
-- Applying patch cmake_dont_build_more_than_needed.patch
-- Applying patch 0001-Prevent-invalid-inclusions-when-HAVE_-is-set-to-0.patch
-- Applying patch add_debug_postfix_on_mingw.patch
-- Using source at D:/src/projects/VcPkgNuGetGenerator/src/vcpkg/buildtrees/zlib/src/1.2.11-63309e48e5.clean
-- Found external ninja('1.10.2').
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz...
-- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz... Failed. Status: 22;"HTTP response code said error"
-- Downloading https://www2.futureware.at/~nickoe/msys2-mirror/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz...
-- Downloading https://www2.futureware.at/~nickoe/msys2-mirror/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz... Failed. Status: 22;"HTTP response code said error"
-- Downloading https://mirror.yandex.ru/mirrors/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz...
-- Downloading https://mirror.yandex.ru/mirrors/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz... Failed. Status: 22;"HTTP response code said error"
-- Downloading https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz...
-- Downloading https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz... Failed. Status: 22;"HTTP response code said error"
-- Downloading https://mirrors.ustc.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz...
-- Downloading https://mirrors.ustc.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz... Failed. Status: 22;"HTTP response code said error"
-- Downloading https://mirror.bit.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz...
-- Downloading https://mirror.bit.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz... Failed. Status: 22;"HTTP response code said error"
-- Downloading https://mirror.selfnet.de/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz...
-- Downloading https://mirror.selfnet.de/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz... Failed. Status: 35;"SSL connect error"
-- Downloading https://mirrors.sjtug.sjtu.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz...
-- Downloading https://mirrors.sjtug.sjtu.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz... Failed. Status: 22;"HTTP response code said error"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:181 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_acquire_msys.cmake:87 (vcpkg_download_distfile)
  scripts/cmake/vcpkg_acquire_msys.cmake:135 (msys_package_download)
  scripts/cmake/vcpkg_find_acquire_program.cmake:427 (vcpkg_acquire_msys)
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:270 (vcpkg_find_acquire_program)
  ports/zlib/portfile.cmake:48 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:79 (include)

Error: Building package zlib:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zlib:x86-windows
  Vcpkg version: 2020.06.15-nohash

**Comment by FrankXie05** [comment]
@olejniczak Sorry for the late reply, Looks like you can't download `[mingw ](https://mirrors.ustc.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz)`
Suggested solution：
1. Make sure you are using the latest vcpkg, you can use the command` git pull` or re-clone a vcpkg 
2. Please unzip this [file ](https://github.com/microsoft/vcpkg/files/7141535/mingw-w64-x86_64-libiconv-1.16-1-any.pkg.tar.xz.zip)and put it into VCPKG_ROOT/downloads then try again.

**Comment by JackBoosY** [comment]
Both 0.29.2-1 or 0.29.2-2(in latest vcpkg) are not found, this should be updated to https://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst

**Comment by dalboris** [comment]
Unfortunately, one of my test machines is on Windows 7, and on this machine I'm using vcpkg version 2020.11-1, because it's basically the latest version that (used to) work out of the box with Windows 7 (due to Python 3.9 not working on Windows 7). So I can't update vcpkg here, and I'm hit with this download failure. It's a shame that mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz seems to have been removed from msys2 and all the mirrors.

**Comment by JackBoosY** [comment]
@dalboris You can use overlay-port to overwrite the port python.

**Comment by dalboris** [comment]
@JackBoosY Thanks for the help. In this case, I need to modify both the port, but also `scripts\cmake\vcpkg_find_acquire_program.cmake`. Is this possible with port overlay?

Anyway, I managed to get my config working by using the latest vcpkg and manually modifying those files as described here:

https://github.com/microsoft/vcpkg/issues/20113#issuecomment-977463518

**Comment by dalboris** [comment]
Ideally, it would be nice if vcpkg detects when the system is Windows 7, and automatically use Python 3.8.x in this case. As is, Windows 7 is not supported by vcpkg, despite what's written in the README.

**Comment by JackBoosY** [comment]
@dalboris 
You should not modify the contents of `vcpkg_find_acquire_program` because the old package may not exist upstream.
my suggestion is:
1. Roll back the vcpkg version to the previously available version.
2. Backup the port name folder in _VCPKG_ROOT/ports_ that affects your build.
3. Use overlay-port to specify the configuration path used by these builds. See https://github.com/microsoft/vcpkg/blob/master/docs/specifications/ports-overlay.md.
4. Update vcpkg to the latest using git pull.

**Comment by dalboris** [comment]
@JackBoosY I cannot roll back to a previous version of vcpkg, because the latest version of vcpkg with Python 3.8.x request to download mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz (as per this issue), which isn't available anymore.

Of course I'm going to change vcpkg_find_acquire_program if it works! The situation is: I've already spent two days getting a working configuration and now it works, so I'm not going to spend any more minute on it :)

**Comment by dalboris** [comment]
Oh wait, are you suggesting to use an old version of vcpkg, but write an overlay-port to get a newer version of pkg-config? Well, I suppose that could work too, but again, other issues might occur when using an older vcpkg, I'm not touching anything now that the config works. Windows 7 is end of life anyway, I'm only spending a few days per year on this system it's just for testing.
