### ISSUE TITLE
[rhash] fails to be found with `find_package` or explicit `find_library`

### ISSUE THREAD

**Issue by SamuelMarks** [microsoft/vcpkg#22660]
Library name: rhash

New version number: 9d2f4a59b30a8b0730096ad3b63eff859437d6db

Other information that may be useful (release notes, etc...)

Tried this and all the name variations in `find_package`:
```cmake
find_library(LibRHash_LIBRARY RHash LibRHash librhash rhash REQUIRED)
```

Do I need to `include` this https://gitlab.kitware.com/traversaro/cmake/-/blob/add_cmake_install_cmakebasedir/Source/Modules/FindLibRHash.cmake?

**Comment by JackBoosY** [comment]
We should export the unofficial targets in CMakeLists.txt

**Comment by dg0yt** [comment]
> We should export the unofficial targets in CMakeLists.txt

...or just document the usage with standard cmake commands, compatible with usage without vcpkg.

What is the error message with `find_library(LibRHash_LIBRARY RHash LibRHash librhash rhash REQUIRED)`?
Which triplet failed?
There is no reaons why this command shouldn't find `rhash:x64-windows:/debug/lib/rhash.lib`.

**Comment by SamuelMarks** [comment]
@dg0yt / @JackBoosY 
With `find_library(LibRHash_LIBRARY NAMES RHash LibRHash librhash rhash REQUIRED)`:
```
  Could not find LibRHash_LIBRARY using the following names: RHash, LibRHash,
  librhash, rhash
```

I've installed both x86 and x64 variants


With `find_package`:
```
vcpkg/scripts/buildsystems/vcpkg.cmake:788 (_find_package):
  Could not find a package configuration file provided by "rhash" with any of
  the following names:

    rhashConfig.cmake
    rhash-config.cmake

  Add the installation prefix of "rhash" to CMAKE_PREFIX_PATH or set
  "rhash_DIR" to a directory containing one of the above files.  If "rhash"
  provides a separate development package or SDK, be sure it has been
  installed.
```

**Comment by SamuelMarks** [comment]
@dg0yt / @JackBoosY the old https://gitlab.kitware.com/traversaro/cmake/-/blob/add_cmake_install_cmakebasedir/Source/Modules/FindLibRHash.cmake didn't work. Should I be trying with pkg-config next?

**Comment by dg0yt** [comment]
It is a simple library without dependencies or fancy names. 

- `find_package(rhash CONFIG)` needs exported config. Which rhash doesn't provide. It won't use the Find module you linked.
- The Find module you linked is called `FindLibRHash.cmake`. If you place it in a location which is in `CMAKE_MODULE_PATH`, you can try to use it with`find_package(LibRHash)` .[!]

You can `set(CMAKE_FIND_DEBUG_MODE 1)` to have more output.

**Comment by SamuelMarks** [comment]
Thanks it's working now. Weird that the explicit include didn't set the `_FOUND` var but after fixing my `CMAKE_MODULE_PATH` to the dir where I have that one (and other `Find*.cmake`) it worked.

I'll keep this issue open in case someone wants to expose targets for it to vcpkg

**Comment by dg0yt** [comment]
The `include` does just that. `find_package` sets interface variables which are used by Find modules and helper functions, in particular by  `FIND_PACKAGE_HANDLE_STANDARD_ARGS`. 

The linked module also has a fragile hard-coded path to `FindPackageHandleStandardArgs.cmake`. Apart from that it has the most primitive form of `find_path` and ` find_library`.
