### ISSUE TITLE
vcpkg's VMSS might no longer need the unencrypted Git protocol

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/vcpkg#22670]
vcpkg's Virtual Machine Scale Set scripts allow the unencrypted Git protocol through the firewall:

https://github.com/microsoft/vcpkg/blob/5fcea86177e7c81fa90e721bba2822649dd4b982/scripts/azure-pipelines/create-vmss-helpers.psm1#L274-L284

GitHub is disabling support for this: https://github.blog/2021-09-01-improving-git-protocol-security-github/

Unless some of vcpkg's ports are manually connecting to other hosting services through this legacy protocol, I suspect that vcpkg can and should remove this firewall exception.

**Comment by JackBoosY** [comment]
cc @BillyONeal

**Comment by BillyONeal** [comment]
Still might be used:

* https://github.com/microsoft/vcpkg/blob/02745e0f4749d1f51d2025824209408f5a6c3614/ports/qtbase/cmake/qt_install_submodule.cmake#L29
* https://github.com/microsoft/vcpkg/blob/02745e0f4749d1f51d2025824209408f5a6c3614/ports/qtbase/cmake/qt_install_submodule.cmake#L45

@Neumann-A Do you know if `https://` would work for these?

**Comment by BillyONeal** [comment]
![Image](https://github.com/user-attachments/assets/ce3b5b57-e887-4195-81a0-030cc1369811)
