### ISSUE TITLE
[mpfr] Build error

### ISSUE THREAD

**Issue by EulerSheep** [microsoft/vcpkg#22671]
**Host Environment**
- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**
`./vcpkg install xxxx`

**Failure logs** 
-Cut and paste the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by JackBoosY** [comment]
-Cut and paste the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

**Comment by Llcoolsouder** [comment]
I have also had a build error for this package (although I can't say if it's the _same_).
Here's the output of my error log.

```
/home/ghost/dev/third-party/vcpkg/buildtrees/mpfr/src/mpfr-4-8955d4bc66.clean/missing: line 81: makeinfo: command not found
WARNING: 'makeinfo' is missing on your system.
         You should only need it if you modified a '.texi' file, or
         any other file indirectly affecting the aspect of the manual.
         You might want to install the Texinfo package:
         <http://www.gnu.org/software/texinfo/>
         The spurious makeinfo call might also be the consequence of
         using a buggy 'make' (AIX, DU, IRIX), in which case you might
         want to install GNU make:
         <http://www.gnu.org/software/make/>
make[1]: *** [.././../src/mpfr-4-8955d4bc66.clean/doc/mpfr.info] Error 127
make: *** [all-recursive] Error 1
```

**Comment by JackBoosY** [comment]
```
makeinfo: command not found
```
Please see https://stackoverflow.com/questions/338317/what-is-makeinfo-and-how-do-i-get-it

**Comment by JackBoosY** [comment]
Confirmed, mpfr doesn't support non-Windows in vcpkg currently.
