### ISSUE TITLE
[harfbuzz] link dependency incorrectly set when VCPKG=release and CMAKE=debug

### ISSUE THREAD

**Issue by abique** [microsoft/vcpkg#22680]
**Describe the bug**
When building statically Qt6Widgets, `target_link_libraries(app Qt6::Widgets)` will fail.
```
vcpkg_installed/x64-linux/lib/libQt6Gui.a(qfontengine.cpp.o):qfontengine.cpp:function QFontEngine::supportsScript(QChar::Script) const: error: undefined reference to 'hb_ot_tags_from_script_and_language'
vcpkg_installed/x64-linux/lib/libQt6Gui.a(qfontengine.cpp.o):qfontengine.cpp:function QFontEngine::supportsScript(QChar::Script) const: error: undefined reference to 'hb_ot_layout_table_select_script'
vcpkg_installed/x64-linux/lib/libQt6Gui.a(qtextengine.cpp.o):qtextengine.cpp:function QTextEngine::shapeTextWithHarfbuzzNG(QScriptItem const&, unsigned short const*, int, QFontEngine*, QList<unsigned int> const&, bool, bool) const: error: undefined reference to 'hb_buffer_create'
vcpkg_installed/x64-linux/lib/libQt6Gui.a(qtextengine.cpp.o):qtextengine.cpp:function QTextEngine::shapeTextWithHarfbuzzNG(QScriptItem const&, unsigned short const*, int, QFontEngine*, QList<unsigned int> const&, bool, bool) const: error: undefined reference to 'hb_buffer_set_unicode_funcs'
vcpkg_installed/x64-linux/lib/libQt6Gui.a(qtextengine.cpp.o):qtextengine.cpp:function QTextEngine::shapeTextWithHarfbuzzNG(QScriptItem const&, unsigned short const*, int, QFontEngine*, QList<unsigned int> const&, bool, bool) const: error: undefined reference to 'hb_buffer_pre_allocate'
vcpkg_installed/x64-linux/lib/libQt6Gui.a(qtextengine.cpp.o):qtextengine.cpp:function QTextEngine::shapeTextWithHarfbuzzNG(QScriptItem const&, unsigned short const*, int, QFontEngine*, QList<unsigned int> const&, bool, bool) const: error: undefined reference to 'hb_buffer_allocation_successful'
vcpkg_installed/x64-linux/lib/libQt6Gui.a(qtextengine.cpp.o):qtextengine.cpp:function QTextEngine::shapeTextWithHarfbuzzNG(QScriptItem const&, unsigned short const*, int, QFontEngine*, QList<unsigned int> const&, bool, bool) const: error: undefined reference to 'hb_language_get_default'
vcpkg_installed/x64-linux/lib/libQt6Gui.a(qtextengine.cpp.o):qtextengine.cpp:function QTextEngine::shapeTextWithHarfbuzzNG(QScriptItem const&, unsigned short const*, int, QFontEngine*, QList<unsigned int> const&, bool, bool) const: error: undefined reference to 'hb_buffer_clear_contents'
vcpkg_installed/x64-linux/lib/libQt6Gui.a(qtextengine.cpp.o):qtextengine.cpp:function QTextEngine::shapeTextWithHarfbuzzNG(QScriptItem const&, unsigned short const*, int, QFontEngine*, QList<unsigned int> const&, bool, bool) const: error: undefined reference to 'hb_buffer_add_utf16'
...
```

Adding `vcpkg_installed/x64-linux/lib/libharfbuzz.a` to the link command fixes it.

**Environment**
- OS: Linux, x86_64, static build
- Compiler: gcc (GCC) 11.1.0

**To Reproduce**
```bash
git clone git@github.com:free-audio/clap-examples.git
cd clap-examples
git checkout 7aa26b2474fd329fab3560a2cae8aa18c9d1b252
git submodules init
git submodules update
cmake --preset ninja-vcpkg
cmake  --build --preset ninja-vcpkg-release --target clap-host
```

**Comment by abique** [comment]
It seems to also happen on macos.

**Comment by abique** [comment]
I've tried to add:
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 0e25b22..a0d4811 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -14,6 +14,7 @@ set(CMAKE_AUTOMOC ON)
 
 find_package(Boost REQUIRED COMPONENTS serialization iostreams)
 
+find_package(harfbuzz CONFIG REQUIRED)
 find_package(Qt6Core CONFIG REQUIRED)
 find_package(Qt6Widgets CONFIG REQUIRED)
 find_package(Qt6Qml CONFIG REQUIRED)
diff --git a/host/CMakeLists.txt b/host/CMakeLists.txt
index c8abe64..30647ab 100644
--- a/host/CMakeLists.txt
+++ b/host/CMakeLists.txt
@@ -44,16 +44,16 @@ set_target_properties(clap-host PROPERTIES
   WIN32_EXECUTABLE true
   VS_DEBUGGER_COMMAND_ARGUMENTS "-p $<TARGET_FILE:clap-plugins> -i 0")
 
-target_link_libraries(clap-host Qt6::Widgets clap-helpers)
+target_link_libraries(clap-host PRIVATE Qt6::Widgets harfbuzz clap-helpers)
 
 if(UsePkgConfig)
```

And it did not fix it so I now wonder if the problem lies in harbuzz instead.

**Comment by JackBoosY** [comment]
cc @Neumann-A

**Comment by Neumann-A** [comment]
try chaniging:
```
 find_package(Qt6Core CONFIG REQUIRED)
 find_package(Qt6Widgets CONFIG REQUIRED)
 find_package(Qt6Qml CONFIG REQUIRED)
```
to
`find_package(Qt6 COMPONENTS Core Gui Widgets Qml REQUIRED)`

Also please specify which features of qtbase you selected/build.

**Comment by abique** [comment]
This is how I select the features: https://github.com/free-audio/clap-examples/blob/main/vcpkg.json
I've tried what you've suggested, but the problem remains.

**Comment by Neumann-A** [comment]
This is the installation:
```
      qtbase[brotli,concurrent,core,dbus,default-features,doubleconversion,freetype,gui,harfbuzz,icu,jpeg,network,openssl,pcre2,png,sql,sql-psql,sql-sqlite,testlib,widgets,zstd]:x64-windows -> 6.2.2#2
      qtdeclarative[core]:x64-windows -> 6.2.2#1
      qtquickcontrols2[core]:x64-windows -> 6.2.0
    * qtshadertools[core]:x64-windows -> 6.2.2
``` 
(you can remove the dependency on quickcontrols2)

Try linking `Qt6::Gui` and `Qt6::Widgets`... Never seen that error in Qt6 yet and the cmake test port which also uses Gui and Widgets works. 

Maybe a log with --trace-expand can shed some light on what is happening here.

**Comment by abique** [comment]
I've done the suggested changes but the problem is still there.
How to use `--trace-expand` cmake does not seem to take it as an argument.

**Comment by Neumann-A** [comment]
> cmake does not seem to take it as an argument.

https://cmake.org/cmake/help/latest/manual/cmake.1.html (search for it; cannot link it directly)

**Comment by abique** [comment]
[trace-err.log](https://github.com/microsoft/vcpkg/files/7912862/trace-err.log)
[trace-out.log](https://github.com/microsoft/vcpkg/files/7912869/trace-out.log)

OK it works when configuring but not when building, understood.

**Comment by abique** [comment]
I've found the issue.
If I run: `cmake --build --preset ninja-vcpkg-release --target clap-host` then it works.
The thing is that in my triplet overlay, I've forced release build, so I don't build everything in debug, but it seems that harfbuzz resolution looks at the current build type.

**Comment by abique** [comment]
I think the important bits are here:
```
/home/abique/develop/clap-examples/builds/ninja-vcpkg/vcpkg_installed/x64-linux/share/harfbuzz/harfbuzzConfig.cmake(11):  find_library(HARFBUZZ_LIBRARY_DEBUG NAMES harfbuzz PATHS /home/abique/develop/clap-examples/builds/ninja-vcpkg/vcpkg_installed/x64-linux/debug PATH_SUFFIXES lib NO_DEFAULT_PATH )
/home/abique/develop/clap-examples/builds/ninja-vcpkg/vcpkg_installed/x64-linux/share/harfbuzz/harfbuzzConfig.cmake(12):  if(HARFBUZZ_LIBRARY_DEBUG )
/home/abique/develop/clap-examples/builds/ninja-vcpkg/vcpkg_installed/x64-linux/share/harfbuzz/harfbuzzConfig.cmake(16):  find_library(HARFBUZZ_LIBRARY_RELEASE NAMES harfbuzz PATHS /home/abique/develop/clap-examples/builds/ninja-vcpkg/vcpkg_installed/x64-linux PATH_SUFFIXES lib NO_DEFAULT_PATH )
/home/abique/develop/clap-examples/builds/ninja-vcpkg/vcpkg_installed/x64-linux/share/harfbuzz/harfbuzzConfig.cmake(17):  if(HARFBUZZ_LIBRARY_RELEASE )
/home/abique/develop/clap-examples/builds/ninja-vcpkg/vcpkg_installed/x64-linux/share/harfbuzz/harfbuzzConfig.cmake(18):  target_link_libraries(harfbuzz INTERFACE $<$<NOT:$<CONFIG:DEBUG>>:/home/abique/develop/clap-examples/builds/ninja-vcpkg/vcpkg_installed/x64-linux/lib/libharfbuzz.a> )
/home/abique/develop/clap-examples/builds/ninja-vcpkg/vcpkg_installed/x64-linux/share/harfbuzz/harfbuzzConfig.cmake(21):  set(HARFBUZZ_FEATURES core )
```

**Comment by Neumann-A** [comment]
> , I've forced release build

have you defined the CMAKE_BUILD_TYPE=Release ?

**Comment by abique** [comment]
Here for the overlay: https://github.com/free-audio/clap-examples/blob/main/vcpkg-overlay/triplets/x64-linux.cmake
Then I've use `Ninja Multi-Config` for the generator, so it does both Debug and Release right?

**Comment by abique** [comment]
From `builds/ninja-vcpkg/vcpkg_installed/x64-linux/share/harfbuzz/harfbuzzConfig.cmake`:

```cmake
find_library(HARFBUZZ_LIBRARY_DEBUG NAMES harfbuzz PATHS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/debug" PATH_SUFFIXES lib NO_DEFAULT_PATH)
if(HARFBUZZ_LIBRARY_DEBUG)
    target_link_libraries(harfbuzz INTERFACE $<$<CONFIG:DEBUG>:${HARFBUZZ_LIBRARY_DEBUG}>)
endif()

find_library(HARFBUZZ_LIBRARY_RELEASE NAMES harfbuzz PATHS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}" PATH_SUFFIXES lib NO_DEFAULT_PATH)
if(HARFBUZZ_LIBRARY_RELEASE)
    target_link_libraries(harfbuzz INTERFACE $<$<NOT:$<CONFIG:DEBUG>>:${HARFBUZZ_LIBRARY_RELEASE}>)
endif()
```

Do you think it is correct?

**Comment by Neumann-A** [comment]
> hen I've use Ninja Multi-Config for the generator, so it does both Debug and Release right?

........... the default configuration for Multi-config is always Debug...... either specify release or don't use multi config.

**Comment by abique** [comment]
I've tried to pass the build type to release when configuring, but it did not fix building the debug configuration.

**Comment by abique** [comment]
It is only harfbuzz which has this issue, the other libraries seems to be fine.

**Comment by Neumann-A** [comment]
not a qt issue. It is an issue in the harfbuzz wrapper. The wrapper needs to use/set `IMPORTED_LOCATION_<CONFIG>` to support your case. In general multi config support in vcpkg is not really good.

**Comment by abique** [comment]
Should I use ninja with single config, and for debug build, use the config type release but set the actual cxxflags to debug?

**Comment by abique** [comment]
> not a qt issue. It is an issue in the harfbuzz wrapper. The wrapper needs to use/set `IMPORTED_LOCATION_<CONFIG>` to support your case. In general multi config support in vcpkg is not really good.

If you know the solution, will you fix the wrapper?

**Comment by Neumann-A** [comment]
> If you know the solution, will you fix the wrapper?

Knowing the solution and having time to fix it are two different shoes. So currently no. 

You can have a look at https://gitlab.kitware.com/cmake/cmake/-/blob/master/Modules/FindJPEG.cmake#L110-L140 to see how it needs to be setup.

**Comment by abique** [comment]
By looking at the file history: https://github.com/microsoft/vcpkg/commits/master/ports/harfbuzz/harfbuzzConfig.cmake.in
Maybe one of its author would have the time to look into it?
@vejmartin @ebraminio @BillyONeal @JackBoosY
