### ISSUE TITLE
Directory named 'control' is mistaken as a 'CONTROL' file failing manifest mode of vcpkg

### ISSUE THREAD

**Issue by mabu4ch** [microsoft/vcpkg#22686]
**Describe the bug**
We wanted to add vcpkg to manage libraries in an existing project using the manifest mode with vcpkg.json.
We have added vcpkg.json to the root directory and use the -DCMAKE_TOOLCHAIN_FILE=vcpkginstall/.../vcpkg.cmake.
Running CMake results in following error message:

-- Running vcpkg install
Found both manifest and CONTROL file in port /Users/markus/Programming/vcpkgbug; please rename one or the other
-- Running vcpkg install - failed

Part of our code is in a directory named "control". Renaming it makes the bug disappear. 
Also adding a folder "control" to another project that works well with vcpkg will trigger this bug.

**Environment**
- OS: MacOs 11.6.2
- Compiler: Xcode_12_4 Clang

**To Reproduce**
1. take any project using a manifest: vcpkg.json
2. add a folder named 'control' at the same level as the manifest
3. Run configure

**Expected behavior**
I would have expected that a folder 'control' will not be interpreted as a CONTROL file.

**Comment by pmeems** [comment]
I have the same issue with https://github.com/MapWindow/MapWinGIS/tree/develop/src making it very hard to use vcpkg together with vcpkg.json and Github Actions
