### ISSUE TITLE
[New Port Request] Cuba

### ISSUE THREAD

**Issue by tueda** [microsoft/vcpkg#22699]
Library name: Cuba

Library description: a library for multidimensional numerical integration

Source repository URL: none; tarballs available on the project homepage

Project homepage (if different from the source repository): http://www.feynarts.de/cuba/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

This library implements multidimensional numerical integration by using both randomized and deterministic algorithms. The latter is good for a moderate number of dimensions and is not available in, e.g., the GNU Scientific Library (GSL).

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
