### ISSUE TITLE
vcpkg goes into an infinite loop on setup

### ISSUE THREAD

**Issue by vadi2** [microsoft/vcpkg#22690]
Gist for the `cmake --trace-expand` output: https://gist.github.com/vadi2/e2d362c3dd45bbad3eb1a83ffe511222

Using the latest `vcpkg.cmake` downloaded today.

**Comment by vadi2** [comment]
This is while running within Github Codespaces.

**Comment by dg0yt** [comment]
It starts searching for the vpkg root dir on `/workspaces/Housemaker/`, works its way up and live-locks on `/`...

Is there a file `/workspaces/Housemaker/.vcpkg-root`?

**Comment by vadi2** [comment]
That is empty -

```
$ file /workspaces/Housemaker/.vcpkg-root
/workspaces/Housemaker/.vcpkg-root: cannot open `/workspaces/Housemaker/.vcpkg-root' (No such file or directory)
```

**Comment by dg0yt** [comment]
> `$ cmake -DCMAKE_TOOLCHAIN_FILE:STRING=/workspaces/Housemaker/vcpkg.cmake -DVCPKG_VERBOSE=ON --trace-expand ..`
>
> Using the latest `vcpkg.cmake` downloaded today.

In particular, do not just use `vcpkg.cmake`. It interacts with other parts of the vcpkg tree.

**Comment by vadi2** [comment]
Thanks for the tip - I started out with the [modern-cpp-template](https://github.com/filipdutescu/modern-cpp-template) which [does this](https://github.com/filipdutescu/modern-cpp-template/blob/master/cmake/Vcpkg.cmake) ootb.

**Comment by dg0yt** [comment]
Duplicate of #20125.

**Comment by JackBoosY** [comment]
Please track #20125 instead.
