### ISSUE TITLE
[New Port Request] stduuid

### ISSUE THREAD

**Issue by ankurvdev** [microsoft/vcpkg#22700]
Library name: stduuid

Library description:
Cross platform UUID 

Source repository URL:
https://github.com/mariusbancila/stduuid

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

There was an earlier attempt 
https://github.com/microsoft/vcpkg/pull/16382

That was reverted back 
https://github.com/microsoft/vcpkg/pull/20161

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.

**Comment by BurningEnlightenment** [comment]
@JackBoosY this can be marked as resolved now.
