### ISSUE TITLE
[Qt] Support for `-DQT_NAMESPACE=XXX`

### ISSUE THREAD

**Issue by abique** [microsoft/vcpkg#22712]
Hi,

Qt offers the option to put all the classes in a namespace.
For that we'd need to pass `-DQT_NAMESPACE=XXX`.

I haven't seen a way to parametrize a feature with a string. Did I miss something?

Two options:
1. Generate a random namespace based upon user+host+date
2. pick the namespace name from `QT_NAMESPACE` which would be defined in the triplet

What do you think is the right approach?

**Comment by abique** [comment]
@Neumann-A I ping you as you contributed to qtbase.

**Comment by Neumann-A** [comment]
Only option here is to use an overlay port and pass that option manually.

**Comment by abique** [comment]
@Neumann-A Thank you very much.
Pull request incoming.
