### ISSUE TITLE
rocksdb

### ISSUE THREAD

**Issue by pete-johnson** [microsoft/vcpkg#2273]
Env: Win10, VS2017, x64 builds
When using vcpkg to build rocksdb, (x64-windows), so a dll build, it appears that only the C API is exported from the dll - i.e. functions such as "rocksdb_*". While I can successfully build programs that use the C API, none of the C++ calls are exported, and so result in unresolved external symbol errors.

**Comment by JackBoosY** [comment]
Same with #2411.

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/2411.
