### ISSUE TITLE
Error: Building package zlib:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by zengzuoqi** [Microsoft/vcpkg#2274]
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:44 (message):
    Command failed: D:/Lib/vcpkg/downloads/cmake-3.10.0-win32-x86/bin/cmake.exe;--build;.;--config;Release;--target;install;--;-v
    Working Directory: D:/Lib/vcpkg/buildtrees/zlib/x64-windows-rel
    See logs for more information:
      D:\Lib\vcpkg\buildtrees\zlib\install-x64-windows-rel-out.log
      D:\Lib\vcpkg\buildtrees\zlib\install-x64-windows-rel-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:63 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/zlib/portfile.cmake:26 (vcpkg_install_cmake)
  scripts/ports.cmake:72 (include)

Error: Building package zlib:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zlib:x64-windows
  Vcpkg version: 0.0.99-2017-11-28-6c5f52daf3cf1c3d7c0f8430f62436bf1d298b1b

**Comment by zengzuoqi** [comment]
[install-x64-windows-rel-out.log](https://github.com/Microsoft/vcpkg/files/1516408/install-x64-windows-rel-out.log)

**Comment by bahaki386** [comment]
A similar error occurred in my environment as well. I attach a link to the log.
[https://gist.github.com/bahaki386/f1322b6967d9ca2b4e323f0ce599b0bd](Gist)

**Comment by bahaki386** [comment]
Maybe,In the standard library,missing type definition of std::off64_t occurs this error.

**Comment by bahaki386** [comment]
In my case,I tried
1.update to recent version of VS
2.exectue `git pull`
3.execute `bootstrap-vcpkg.bat`
4.execute `vcpkg integrate install`
and this errror is gone.

**Comment by NancyLi1013** [comment]
Please open a new issue if this is still a problem for you.
