### ISSUE TITLE
[python3] vcpkg cmake wrappers must not used `find_dependency`

### ISSUE THREAD

**Issue by dg0yt** [microsoft/vcpkg#22743]
**Describe the bug**
`find_dependency` must only be used in cmake package config files. The wrappers neither provides the interface variables nor the call stack for `return()`.

Affected ports:
~~~
$ git grep "find_dependency"  ports/*/vcpkg-cmake-wrapper*
ports/curlpp/vcpkg-cmake-wrapper.cmake:find_dependency(CURL)
ports/libuv/vcpkg-cmake-wrapper.cmake:find_dependency(Threads)
ports/python3/vcpkg-cmake-wrapper.cmake:            find_dependency(ZLIB)
ports/python3/vcpkg-cmake-wrapper.cmake:            find_dependency(Iconv)
ports/python3/vcpkg-cmake-wrapper.cmake:            find_dependency(Intl)
~~~

Alternatives:
- plain `find_package`
- a future `vcpkg_find_dependency`

**Comment by dg0yt** [comment]
The issue is still present in curlpp and python3.

**Comment by LilyWangLL** [comment]
The issue is still present in `python3`.
