### ISSUE TITLE
harfbuzz build failed because of commit 26f12d20

### ISSUE THREAD

**Issue by jasjuang** [Microsoft/vcpkg#2276]
I am on VS2017, in config-x64-windows-rel-err.log

```
CMake Error at CMakeLists.txt:149 (message):
  ragel not found, get it here -- http://www.complang.org/ragel/ or, use
  harfbuzz releases https://github.com/behdad/harfbuzz/releases
```

This is a huge blocker because a lot of huge libraries depends on this.

**Comment by ras0219-msft** [comment]
Thanks for catching that; I don't know why it didn't appear when I was testing the upgrade!

I've reverted the change for now until we can investigate further.

**Comment by ebraminio** [comment]
> I don't know why it didn't appear when I was testing the upgrade!

No problem but I guess because you had installed the unmentioned dependency for not releases, `ragel`, while testing. So the solution is either use releases from https://github.com/harfbuzz/harfbuzz/releases or add ragel to be able to compile the source.
