### ISSUE TITLE
User name contains a space

### ISSUE THREAD

**Issue by maobaoqi** [microsoft/vcpkg#2277]
I have a computer account user name with a space, for example "Benjy Mao", after I run vcpkg, it will pop the message that cannot find the "C:\Users\Benjy".However, the "Benjy" folder is not in computer and it is should be "Benjy Mao" folder.

**Comment by alexkaratarakis** [comment]
I tried reproducing this in an account with space and it seems to work. 
Which command is failing for you? I tried `install`, `remove`, `integrate install`.
Also, where is your `vcpkg` folder located?

**Comment by maobaoqi** [comment]
@alexkaratarakis ok, i will try it again.

**Comment by pagict** [comment]
i met this problem too. 
The command is `vcpkg install boost:x64-linux`.
and the error is
```
Expected output of the form [hash filename] (3 tokens), but got [some_hash_string /mnt/c/Users/My Name/vcpkg/triplets/x64-linux.cmake](4 tokens)
```
while I'm using it on Windows WSL

**Comment by NancyLi1013** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen.
