### ISSUE TITLE
[<libmariadb[openssl]>] build failure

### ISSUE THREAD

**Issue by xengine-qyt** [microsoft/vcpkg#22780]
**Host Environment**
- OS:Windows
- Compiler: 3.1.15

**To Reproduce**
`./vcpkg install libmariadb[openssl]`

**Failure logs** 
Computing installation plan...
The following packages will be built and installed:
    libmariadb[core,openssl,schannel,ssl]:x64-windows -> 3.1.15
Detecting compiler hash for triplet x64-windows...
-- Automatically setting HTTP(S)_PROXY environment variables to 127.0.0.1:7890
Restored 0 packages from C:\Users\qyt\AppData\Local\vcpkg\archives in 153.6 us. Use --debug to see more details.
Starting package 1/1: libmariadb:x64-windows
Building package libmariadb[core,openssl,schannel,ssl]:x64-windows...
CMake Error at ports/libmariadb/portfile.cmake:6 (message):
  Only one SSL backend must be selected.
Call Stack (most recent call first):
  scripts/ports.cmake:142 (include)

Error: Building package libmariadb:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libmariadb
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[libmariadb]+Build+error
including:
  package: libmariadb[core,openssl,schannel,ssl]:x64-windows -> 3.1.15
    vcpkg-tool version: 2021-12-09-724cea8b33cbf06c645f5095fa29773697da9761
    vcpkg-scripts version: b18b17865 2022-01-24 (6 hours ago)

Additionally, attach any relevant sections from the log files above.

**Additional context**

**Comment by JackBoosY** [comment]
```
CMake Error at ports/libmariadb/portfile.cmake:6 (message):
Only one SSL backend must be selected.
```
You should only pick one ssl backend feature.
Please use `./vcpkg install libmariadb[core, openssl]` instead.

**Comment by xengine-qyt** [comment]
o thanks...
