### ISSUE TITLE
Error: Building package botan:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by skthrowaway** [microsoft/vcpkg#2278]
The portfile needs to be updated to not use `--with-pkcs11` as it has been removed in Botan 2.1.0

Also the patch for configure.py needs to be updated

```
@@ -1168,6 +1168,21 @@
             if flag != None and flag != '' and flag not in abi_link:
                 abi_link.append(flag)
 
+        if options.build_shared_lib:
+            if options.with_debug_info:
+                if 'dynamic-debug' in self.mach_abi_linking:
+                    abi_link.append(self.mach_abi_linking['dynamic-debug'])
+            else:
+                if 'dynamic' in self.mach_abi_linking:
+                    abi_link.append(self.mach_abi_linking['dynamic'])
+        else:
+            if options.with_debug_info:
+                if 'static-debug' in self.mach_abi_linking:
+                    abi_link.append(self.mach_abi_linking['static-debug'])
+            else:
+                if 'static' in self.mach_abi_linking:
+                    abi_link.append(self.mach_abi_linking['static'])
+                    
         if options.with_stack_protector and self.stack_protector_flags != '':
             abi_link.append(self.stack_protector_flags)
```

It also fails on the installation of the compiled lib:

> Usage: install.py [options]
> 
> install.py: error: no such option: --destdir

as it was removed in 2.2.0, from the release notes:

> The --destdir flag to configure.py has been removed. Instead use the DESTDIR environment variable at install time. This change was done to more closely match how autoconf handles this case.

Wish I could make a pull request myself but I don't understand a jackshit to Git and there is a lack of instruction on how to make a proper .patch file on this repo, so ...

**Comment by In3xess** [comment]
It also fails on installation of the lib.

> Usage: install.py [options]
> 
> install.py: error: no such option: --destdir

**Comment by wangli28** [comment]
Hi @skthrowaway, thank you for posting this issue! I installed `botan:x64-windows` successfully with Visual Studio 2017 and VCPKG latest source. This document mentioned how to make a patch. See here: https://github.com/microsoft/vcpkg/blob/master/docs/examples/patching.md.
