### ISSUE TITLE
How do I use cmake port scripts in my project?

### ISSUE THREAD

**Issue by fromasmtodisasm** [microsoft/vcpkg#22785]
I want to write a cmake utility and form a port from it, I barely managed to understand how cmake-port does it, for some reason there is no documentation about such files as "vcpkg-port-config.cmake" anywhere, there is no information available in the documentation. But having this file, my cmake library can only be used in other portfile.cmake! And I want to specify this library in vcpkg.json as dependencies and use cmake functions from it. How can I achieve this?

**Comment by fromasmtodisasm** [comment]
I have an engine from which I made a port. It worked out well, I can install it via vcpkg. But it turned out that the dependent project requires cmake scripts that the engine itself uses. I need to somehow distribute these setup scripts along with the engine or as a separate package so that the consumer (my game) can be configured correctly

**Comment by fromasmtodisasm** [comment]
The problem is that earlier both the engine and the game lived in the same repository, after trying to move the engine to a separate repository, everything broke

**Comment by dg0yt** [comment]
Keep it a discussion? #22784

**Comment by fromasmtodisasm** [comment]
> Keep it a discussion? #22784

I did not know where to write better, I wrote in two places at once, if it is more appropriate to resolve this issue here, then you can not leave that #22784

**Comment by autoantwort** [comment]
> I did not know where to write better, I wrote in two places at once

That is a bad idea. It only splits the discussion to multiple places. I have answered your discussion. Imho a discussion is better because it is a question and not a bug.

**Comment by fromasmtodisasm** [comment]
> > I did not know where to write better, I wrote in two places at once
> 
> That is a bad idea. It only splits the discussion to multiple places. I have answered your discussion. Imho a discussion is better because it is a question and not a bug.

This is not a bug, right, most likely a missing feature, because I used conan a little, and there it was easy to form a tool "library" from cmake scripts, which could be easily used via include , perhaps you need to create a feature request in which to discuss this aspect. Perhaps this thread needs to be frozen or renamed in order to split the thread

**Comment by JackBoosY** [comment]
Please track #22784.
