### ISSUE TITLE
No Fortran compiler found on the PATH. But there is.

### ISSUE THREAD

**Issue by TobiasWallner** [microsoft/vcpkg#22799]
I would like to install a package (armadillo) that needs a fortran compiler to build. And I have one installed and added to the path. I can call the gfortran.exe from anywhere in the command line however vcpkg cannot find it and outputs:

-- No Fortran compiler found on the PATH.

It occurs every time I try to install armadillo.
vcpkg install armadillo.

Additionally the build fails because it tries to build/download fortran and fails in the process. However, this is another different issue that I believe is described in #22789.

In the attatched files are screenshots of the fortran compiler on my system and the vcpkg output.

![console vcpkg not finding fortran compiler](https://user-images.githubusercontent.com/70602844/151151413-cf9ec36b-9add-4d8f-b352-6c03c060a83d.PNG)
![fortran compiler as part of the mingw in the path system environment variables](https://user-images.githubusercontent.com/70602844/151151416-1cca6d6a-1544-4a95-94b8-1bacebecf170.PNG)
![fortran compiler called from anywhere on my system](https://user-images.githubusercontent.com/70602844/151151419-bde67376-587f-4fd9-acc5-df636aaa2010.PNG)
![Fortran compiler on my system](https://user-images.githubusercontent.com/70602844/151151420-5fe79254-03b0-4efe-87bf-ea765cc73b16.PNG)

**Comment by Neumann-A** [comment]
Run `vcpkg env --triplet=x64-windows` and you will get the environment vcpkg uses. On windows vcpkg uses a clean vscmd shell environment so whatever the user externally sets up doesn't matter. (except some exceptions like CUDA and INTEL vars. )

**Comment by TobiasWallner** [comment]
Ok, I opend the shell as asked

> Run vcpkg env --triplet=x64-windows and you will get the environment vcpkg uses

and added the path manually, however vcpkg still cannot find the gfortran.exe compiler. And the build fails.

Attatched is a screenshot with markers at the relevant parts as well as the whole shell output.

![Explizitly added the path still fortran compiler not found](https://user-images.githubusercontent.com/70602844/151545573-12849414-2b1f-409a-bdec-d354adb635f4.PNG)

[Shell output.txt](https://github.com/microsoft/vcpkg/files/7958547/Shell.output.txt)

**Comment by Neumann-A** [comment]
> and added the path manually

That does nothing. Each vcpkg call has its own clean shell env on windows. If you want to change that you need to look into custom triplets and https://github.com/microsoft/vcpkg/blob/master/docs/users/triplets.md#vcpkg_env_passthrough

**Comment by sfhacker** [comment]
This is indeed embarrassing!
@TobiasWallner Most probably your environment is broken. Try reinstalling it.

No issues here.

![image](https://user-images.githubusercontent.com/25817529/151575427-9db85cd0-0169-4591-9d9a-6437d9a3d894.png)

**Comment by sfhacker** [comment]
Just built armadillo 10.8.1 from source on Windows 10 x64. No issues at all!

![image](https://user-images.githubusercontent.com/25817529/151592931-06d1cbec-6bae-45e1-b5d4-fd1ef7021fbc.png)

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
