### ISSUE TITLE
 vcpkg.exe has crashed. windows 10 x64 

### ISSUE THREAD

**Issue by urbanekpj** [Microsoft/vcpkg#2279]
after clean install from git Latest commit c8c332c  4 hours ago
and running "vcpkg install grpc"
i recived
Process creation failed with error code: 87
and also  "vcpkg.exe has crashed" 

C:\vcpkg\vcpkg-master>vcpkg install grpc:x86-windows-static
The following packages will be built and installed:
    grpc:x86-windows-static
Starting package 1/1: grpc:x86-windows-static
Building package grpc:x86-windows-static...
-- CURRENT_INSTALLED_DIR=C:/vcpkg/vcpkg-master/installed/x86-windows-static
-- DOWNLOADS=C:/vcpkg/vcpkg-master/downloads
-- CURRENT_PACKAGES_DIR=C:/vcpkg/vcpkg-master/packages/grpc_x86-windows-static
-- CURRENT_BUILDTREES_DIR=C:/vcpkg/vcpkg-master/buildtrees/grpc
-- CURRENT_PORT_DIR=C:/vcpkg/vcpkg-master/ports/grpc/.
-- Downloading https://github.com/grpc/grpc/archive/v1.7.2.tar.gz...
-- Downloading https://github.com/grpc/grpc/archive/v1.7.2.tar.gz... OK
-- Testing integrity of downloaded file...
-- Testing integrity of downloaded file... OK
-- Extracting source C:/vcpkg/vcpkg-master/downloads/grpc-grpc-v1.7.2.tar.gz
-- Extracting done
-- Applying patch C:/vcpkg/vcpkg-master/ports/grpc/disable-csharp-ext.patch
-- Applying patch C:/vcpkg/vcpkg-master/ports/grpc/disable-csharp-ext.patch done
-- Configuring x86-windows-static-rel
-- Configuring x86-windows-static-rel done
-- Configuring x86-windows-static-dbg
-- Configuring x86-windows-static-dbg done
-- Build x86-windows-static-rel
-- Build x86-windows-static-rel done
-- Build x86-windows-static-dbg
-- Build x86-windows-static-dbg done
-- Installing: C:/vcpkg/vcpkg-master/packages/grpc_x86-windows-static/share/grpc/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package grpc:x86-windows-static... done
Installing package grpc:x86-windows-static...
Installing package grpc:x86-windows-static... done
Elapsed time for package grpc:x86-windows-static: 7.364 min

Total elapsed time: 7.364 min

The package grpc:x86-windows-static provides CMake targets:

    find_package(grpc REQUIRED)
    # Note: 6 targets were omitted
    target_link_libraries(main PRIVATE gRPC::gpr gRPC::grpc gRPC::grpc_cronet gRPC::grpc_unsecure)

Process creation failed with error code: 87
vcpkg.exe has crashed.
Please send an email to:
    vcpkg@microsoft.com
containing a brief summary of what you were trying to do and the following data blob:

Version=0.0.99-unknownhash
EXCEPTION='device or resource busy: device or resource busy'
CMD=
vcpkg|
install|
grpc:x86-windows-static|

Microsoft Visual Studio Professional 2017
Version 15.4.1
VisualStudio.15.Release/15.4.1+27004.2005
Microsoft .NET Framework
Version 4.7.02556

Installed Version: Professional

Visual Basic 2017   00370-10001-02349-AA565
Microsoft Visual Basic 2017

Visual C# 2017   00370-10001-02349-AA565
Microsoft Visual C# 2017

Visual C++ 2017   00370-10001-02349-AA565
Microsoft Visual C++ 2017

ASP.NET and Web Tools 2017   15.0.30925.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   1.0
Provides languages services for ASP.NET Core Razor.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   4.4.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio tools for CMake   1.0
Visual Studio tools for CMake

WiX Toolset Visual Studio Extension   0.9.21.62588
WiX Toolset Visual Studio Extension version 0.9.21.62588
Copyright (c) .NET Foundation and contributors. All rights reserved.

**Comment by Jeinhaus** [comment]
I got the same error here trying to install the pcl-library:

Additional packages (*) will be installed to complete this operation.
Starting package 1/24: bzip2:x86-windows
Building package bzip2:x86-windows...
Process creation failed with error code: 87
Process creation failed with error code: 87
vcpkg.exe has crashed.
Please send an email to:
    vcpkg@microsoft.com
containing a brief summary of what you were trying to do and the following data blob:

Version=0.0.99-2017-11-30-c8c332c8935e0141f4fcb074b511e77e649f0bd9
EXCEPTION='device or resource busy: device or resource busy'
CMD=
D:\repos\vcpkg\vcpkg.exe|
install|
pcl|

**Comment by alexkaratarakis** [comment]
Thanks for reporting and identifying the offending commit.
Hotfixed with 88d953a88d7061c4c49a5cb3d6323bb8f4442521 until we figure out the problem.
