### ISSUE TITLE
Package: opencv4:x64-windows    ...

### ISSUE THREAD

**Issue by nurozhikun** [microsoft/vcpkg#22797]
.\vcpkg.exe install opencv4[contrib]:x64-windows

-- Extracting source D:/dev/vcpkg/downloads/opencv-opencv_contrib-4.5.1.tar.gz
-- Applying patch 0007-fix-hdf5.patch
-- Using source at D:/dev/vcpkg/buildtrees/opencv4/src/4.5.1-0a6ce0443d.clean
-- Downloading https://raw.githubusercontent.com/opencv/opencv_3rdparty/34e4206aef44d50e6bbcd0ab06354b52e7466d26/boostdesc_bgm.i -> opencv-cache/xfeatures2d/boostdesc/0ea90e7a8f3f7876d450e4149c97c74f-boostdesc_bgm.i...
-- Downloading https://raw.githubusercontent.com/opencv/opencv_3rdparty/34e4206aef44d50e6bbcd0ab06354b52e7466d26/boostdesc_bgm.i... Failed. Status: 6;"Couldn't resolve host name"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:184 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".

      If error with status 4 (Issue #15434),
      try setting "http://user:password@your-proxy-ip-address:port/".

      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  ports/opencv4/portfile.cmake:148 (vcpkg_download_distfile)
  scripts/ports.cmake:142 (include)

Error: Building package opencv4:x64-windows failed with: BUILD_FAILED

Package: opencv4:x64-windows
 Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

**Comment by LilyWangLL** [comment]
Ping @nurozhikun for response. Does this issue still exist?
