### ISSUE TITLE
[icu] File does not have expected hash 

### ISSUE THREAD

**Issue by dehilsterlexis** [microsoft/vcpkg#22806]
$ ./vcpkg install icu:x64-windows
The following packages will be built and installed:
    icu[core]:x64-windows
Starting package 1/1: icu:x64-windows
Building package icu[core]:x64-windows...
-- Downloading http://download.icu-project.org/files/icu4c/69.1/icu4c-69_1-src.tgz...
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:91 (message):

  File does not have expected hash:

          File path: [ C:/git/nlp-engine/vcpkg/downloads/temp/icu4c-69_1-src.tgz ]
      Expected hash: [ 4c37691246db802e4bae0c8c5f6ac1dac64c5753b607e539c5c1c36e361fcd9dd81bd1d3b5416c2960153b83700ccdb356412847d0506ab7782ae626ac0ffb94 ]
        Actual hash: [ 5e650ae3edbc3d467a59915c301d583f35d615e04282830b8c7f3b6c49df1728270dad58f359d466174e84c85ae26f97e50acc9dc01ffcd901daa949d5b92f24 ]

  The file may have been corrupted in transit.  This can be caused by
  proxies.  If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY
  environment variables to
  "https://user:password@your-proxy-ip-address:port/".

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:163 (test_hash)
  ports/icu/portfile.cmake:12 (vcpkg_download_distfile)
  scripts/ports.cmake:71 (include)

Error: Building package icu:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: icu:x64-windows
  Vcpkg version: 2018.10.20-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by autoantwort** [comment]
Try updating vcpkg (`git pull`)

**Comment by JonLiu1993** [comment]
@dehilsterlexis ,Thanks for posting this issue, please use command "git pull" updating vcpkg and try again

**Comment by dehilsterlexis** [comment]
Ok.

**Comment by JonLiu1993** [comment]
@dehilsterlexis ,Is this problem solved?

**Comment by dehilsterlexis** [comment]
Yes.
