### ISSUE TITLE
[gdal] Build error

### ISSUE THREAD

**Issue by ferretnt** [microsoft/vcpkg#22802]
**Host Environment**
- OS: [e.g. Windows/Linux etc...]
- Windows 11 X64 Home
- Compiler: revision
VS 2019

**To Reproduce**
`./vcpkg install gdal`

**Failure logs** 
-Cut and paste the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

including:
  package: gdal[core,hdf5,netcdf,postgresql,supported-default-features]:x64-windows -> 3.4.1#1
    vcpkg-tool version: 2021-12-09-724cea8b33cbf06c645f5095fa29773697da9761
    vcpkg-scripts version: 2e34a79a8 2022-01-25 (9 hours ago)

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by Adela0814** [comment]
@ferretnt I don't have a machine with win11 system and I can't repro this issue in my win10 machine, can you please provide failure logs

**Comment by ferretnt** [comment]
Resolved in discord. My fault, Please close this issue.
