### ISSUE TITLE
Can we install the natvis file when installing package?

### ISSUE THREAD

**Issue by sdcb** [microsoft/vcpkg#2281]
natvis file can greatly improve debug experience. 
If port manager create its own natvis file, can vcpkg install it in proper position so that user can easily make use of it?

**Comment by KindDragon** [comment]
You can embed natvis file to .pdb (doesn’t work with ninja)

**Comment by ZeeWanderer** [comment]
This functionality would be very appreciated. I found [a cmake issue about natvis and ninja](https://gitlab.kitware.com/cmake/cmake/issues/16874) but it is there for 2 years now.
If there is no way to embed natvis to pdb via ninja then is it feasible to add functionality to install provided natvis file to `%USERPROFILE%\Documents\%Visual_Studio_YEAR%\Visualizers`?
