### ISSUE TITLE
vcpkg.exe install qt5-translations:x86-windows-static  bug (file is exist,but tell us not exist)

### ISSUE THREAD

**Issue by introspection3** [microsoft/vcpkg#22815]
**Describe the bug**

G:\src\vcpkg>vcpkg.exe --version
Vcpkg package management program version 2021-12-09-724cea8b33cbf06c645f5095fa29773697da9761

 
![image](https://user-images.githubusercontent.com/12368358/151324736-b9ff905b-1158-4f62-a8b6-f80731ecdfab.png)

jom 1.1.3 - empower your cores

WARNING: Failure to find: qt5qml_metatypes.json
WARNING: Failure to find: G:/src/vcpkg/buildtrees/qt5-declarative/src/5.15.2-30e50540ea.clean/src/3rdparty/masm/assembler/*.h
WARNING: Failure to find: G:/src/vcpkg/buildtrees/qt5-declarative/src/5.15.2-30e50540ea.clean/src/3rdparty/masm/wtf/*.h
WARNING: Failure to find: G:/src/vcpkg/buildtrees/qt5-declarative/x86-windows-static-rel/src/qml/qt5qml_metatypes.json
WARNING: Failure to find: qt5qmld_metatypes.json
WARNING: Failure to find: G:/src/vcpkg/buildtrees/qt5-declarative/src/5.15.2-30e50540ea.clean/src/3rdparty/masm/assembler/*.h
WARNING: Failure to find: G:/src/vcpkg/buildtrees/qt5-declarative/src/5.15.2-30e50540ea.clean/src/3rdparty/masm/wtf/*.h
WARNING: Failure to find: G:/src/vcpkg/buildtrees/qt5-declarative/x86-windows-static-rel/src/qml/qt5qmld_metatypes.json
Cannot open foreign types file G:/src/vcpkg/installed/x86-windows-static/lib/metatypes/qt5network_metatypes.json
WARNING: Failure to find: qt5qmlmodels_metatypes.json
WARNING: Failure to find: G:/src/vcpkg/buildtrees/qt5-declarative/x86-windows-static-rel/src/qmlmodels/qt5qmlmodels_metatypes.json
WARNING: Failure to find: qt5qmlmodelsd_metatypes.json
WARNING: Failure to find: G:/src/vcpkg/buildtrees/qt5-declarative/x86-windows-static-rel/src/qmlmodels/qt5qmlmodelsd_metatypes.json
Cannot open foreign types file G:/src/vcpkg/installed/x86-windows-static/lib/metatypes/qt5network_metatypes.json
WARNING: Failure to find: qt5qmlworkerscript_metatypes.json
WARNING: Failure to find: G:/src/vcpkg/buildtrees/qt5-declarative/x86-windows-static-rel/src/qmlworkerscript/qt5qmlworkerscript_metatypes.json
WARNING: Failure to find: qt5qmlworkerscriptd_metatypes.json
WARNING: Failure to find: G:/src/vcpkg/buildtrees/qt5-declarative/x86-windows-static-rel/src/qmlworkerscript/qt5qmlworkerscriptd_metatypes.json
Cannot open foreign types file G:/src/vcpkg/installed/x86-windows-static/lib/metatypes/qt5network_metatypes.json
WARNING: Failure to find: qt5quick_metatypes.json
WARNING: Failure to find: G:/src/vcpkg/buildtrees/qt5-declarative/x86-windows-static-rel/src/quick/qt5quick_metatypes.json
WARNING: Failure to find: qt5quickd_metatypes.json
WARNING: Failure to find: G:/src/vcpkg/buildtrees/qt5-declarative/x86-windows-static-rel/src/quick/qt5quickd_metatypes.json
G:\src\vcpkg\buildtrees\qt5-declarative\src\5.15.2-30e50540ea.clean\src\quick\scenegraph\qsgrenderloop.cpp(0): Note: No relevant classes found. No output generated.
Cannot open foreign types file G:/src/vcpkg/installed/x86-windows-static/lib/metatypes/qt5network_metatypes.json
WARNING: Failure to find: qt5quickshapes_metatypes.json
WARNING: Failure to find: G:/src/vcpkg/buildtrees/qt5-declarative/x86-windows-static-rel/src/quickshapes/qt5quickshapes_metatypes.json
WARNING: Failure to find: qt5quickshapesd_metatypes.json
WARNING: Failure to find: G:/src/vcpkg/buildtrees/qt5-declarative/x86-windows-static-rel/src/quickshapes/qt5quickshapesd_metatypes.json
Cannot open foreign types file G:/src/vcpkg/installed/x86-windows-static/lib/metatypes/qt5network_metatypes.json
WARNING: Failure to find: qt5quicktest_metatypes.json
WARNING: Failure to find: G:/src/vcpkg/buildtrees/qt5-declarative/x86-windows-static-rel/src/qmltest/qt5quicktest_metatypes.json
WARNING: Failure to find: qt5quicktestd_metatypes.json
WARNING: Failure to find: G:/src/vcpkg/buildtrees/qt5-declarative/x86-windows-static-rel/src/qmltest/qt5quicktestd_metatypes.json
Cannot open foreign types file G:/src/vcpkg/installed/x86-windows-static/lib/metatypes/qt5test_metatypes.json
Cannot open foreign types file G:/src/vcpkg/installed/x86-windows-static/lib/metatypes/qt5network_metatypes.json
WARNING: Failure to find: labsmodelsplugin_metatypes.json
WARNING: Failure to find: qmlfolderlistmodelplugin_metatypes.json
WARNING: Failure to find: qmllocalstorageplugin_metatypes.json
WARNING: Failure to find: qmlsettingsplugin_metatypes.json
WARNING: Failure to find: qtqmlstatemachine_metatypes.json
WARNING: Failure to find: qmlsettingsplugind_metatypes.json
WARNING: Failure to find: qmlfolderlistmodelplugind_metatypes.json
WARNING: Failure to find: labsmodelsplugind_metatypes.json
WARNING: Failure to find: qmllocalstorageplugind_metatypes.json
WARNING: Failure to find: qtqmlstatemachined_metatypes.json
WARNING: Failure to find: labsanimationplugin_metatypes.json
WARNING: Failure to find: labsanimationplugind_metatypes.json
Cannot open foreign types file G:/src/vcpkg/installed/x86-windows-static/lib/metatypes/qt5network_metatypes.json
WARNING: Failure to find: qquicklayoutsplugin_metatypes.json
WARNING: Failure to find: qquicklayoutsplugind_metatypes.json
Cannot open foreign types file G:/src/vcpkg/installed/x86-windows-static/lib/metatypes/qt5network_metatypes.json
Cannot open foreign types file G:/src/vcpkg/installed/x86-windows-static/lib/metatypes/qt5sql_metatypes.json
Cannot open foreign types file G:/src/vcpkg/installed/x86-windows-static/lib/metatypes/qt5network_metatypes.json
Cannot open foreign types file G:/src/vcpkg/installed/x86-windows-static/lib/metatypes/qt5network_metatypes.json
WARNING: Failure to find: windowplugin_metatypes.json
WARNING: Failure to find: windowplugind_metatypes.json
WARNING: Failure to find: qmlwavefrontmeshplugin_metatypes.json
WARNING: Failure to find: qmlwavefrontmeshplugind_metatypes.json
WARNING: Failure to find: qmltestplugin_metatypes.json
WARNING: Failure to find: qmltestplugind_metatypes.json
Cannot open foreign types file G:/src/vcpkg/installed/x86-windows-static/lib/metatypes/qt5network_metatypes.json
WARNING: Failure to find: sharedimageplugin_metatypes.json
WARNING: Failure to find: sharedimageplugind_metatypes.json
Cannot open foreign types file G:/src/vcpkg/installed/x86-windows-static/lib/metatypes/qt5network_metatypes.json
Cannot open foreign types file G:/src/vcpkg/installed/x86-windows-static/lib/metatypes/qt5network_metatypes.json
Cannot open foreign types file G:/src/vcpkg/installed/x86-windows-static/lib/metatypes/qt5network_metatypes.json
Cannot open foreign types file G:/src/vcpkg/installed/x86-windows-static/lib/metatypes/qt5network_metatypes.json
Cannot open foreign types file G:/src/vcpkg/installed/x86-windows-static/lib/metatypes/qt5network_metatypes.json
Cannot open foreign types file G:/src/vcpkg/installed/x86-windows-static/lib/metatypes/qt5network_metatypes.json
Cannot open foreign types file G:/src/vcpkg/installed/x86-windows-static/lib/metatypes/qt5test_metatypes.json
jom: G:\src\vcpkg\buildtrees\qt5-declarative\x86-windows-static-rel\tools\qmlpreview\Makefile.Release [.obj\release\moc_qmlpreviewapplication.obj] Error 1
jom: G:\src\vcpkg\buildtrees\qt5-declarative\x86-windows-static-rel\tools\qmlpreview\Makefile.Release [.obj\release\moc_qmlpreviewfilesystemwatcher.obj] Error 1
jom: G:\src\vcpkg\buildtrees\qt5-declarative\x86-windows-static-rel\tools\qmlpreview\Makefile [release] Error 2
jom: G:\src\vcpkg\buildtrees\qt5-declarative\x86-windows-static-rel\tools\qmlmin\Makefile.Release [..\..\bin\qmlmin.exe] Error 1180
jom: G:\src\vcpkg\buildtrees\qt5-declarative\x86-windows-static-rel\tools\qmlmin\Makefile [release] Error 2
jom: G:\src\vcpkg\buildtrees\qt5-declarative\x86-windows-static-rel\tools\qmlprofiler\Makefile.Release [.obj\release\commandlistener.obj] Error 1
jom: G:\src\vcpkg\buildtrees\qt5-declarative\x86-windows-static-rel\tools\qmlprofiler\Makefile.Release [.obj\release\qmlprofilerdata.obj] Error 1
jom: G:\src\vcpkg\buildtrees\qt5-declarative\x86-windows-static-rel\tools\qmlprofiler\Makefile.Release [.obj\release\qmlprofilerclient.obj] Error 1
jom: G:\src\vcpkg\buildtrees\qt5-declarative\x86-windows-static-rel\tools\qmlprofiler\Makefile [release] Error 2
jom: G:\src\vcpkg\buildtrees\qt5-declarative\x86-windows-static-rel\tools\qmllint\Makefile.Release [..\..\bin\qmllint.exe] Error 1180
jom: G:\src\vcpkg\buildtrees\qt5-declarative\x86-windows-static-rel\tools\qmllint\Makefile [release] Error 2
jom: G:\src\vcpkg\buildtrees\qt5-declarative\x86-windows-static-rel\tools\Makefile [sub-qmllint-make_first] Error 2
jom: G:\src\vcpkg\buildtrees\qt5-declarative\x86-windows-static-rel\tools\qmlcachegen\Makefile.Release [..\..\bin\qmlcachegen.exe] Error 1106
jom: G:\src\vcpkg\buildtrees\qt5-declarative\x86-windows-static-rel\tools\qmlcachegen\Makefile [release] Error 2
jom: G:\src\vcpkg\buildtrees\qt5-declarative\x86-windows-static-rel\tools\Makefile [sub-qmlcachegen-make_first] Error 2
jom: G:\src\vcpkg\buildtrees\qt5-declarative\x86-windows-static-rel\tools\qmltestrunner\Makefile.Release [..\..\bin\qmltestrunner.exe] Error 1180
jom: G:\src\vcpkg\buildtrees\qt5-declarative\x86-windows-static-rel\tools\qmltestrunner\Makefile [release] Error 2
jom: G:\src\vcpkg\buildtrees\qt5-declarative\x86-windows-static-rel\tools\Makefile [sub-qmltestrunner-make_first] Error 2
jom: G:\src\vcpkg\buildtrees\qt5-declarative\x86-windows-static-rel\tools\Makefile [sub-qmlmin-make_first] Error 2
jom: G:\src\vcpkg\buildtrees\qt5-declarative\x86-windows-static-rel\tools\Makefile [sub-qmlprofiler-make_first] Error 2
jom: G:\src\vcpkg\buildtrees\qt5-declarative\x86-windows-static-rel\tools\Makefile [sub-qmlpreview-make_first] Error 2
jom: G:\src\vcpkg\buildtrees\qt5-declarative\x86-windows-static-rel\Makefile [sub-tools-make_first] Error 2

**Environment**
- OS: windows
- Compiler: revision

**To Reproduce**
1. ./vcpkg install xxxx
2. See error
Repro code when

**Expected behavior**

**Failure logs** 
-(please attached failure logs)

**Additional context**

**Comment by JackBoosY** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
