### ISSUE TITLE
[fftw] fftw3 port broken - lack of single and long-double version

### ISSUE THREAD

**Issue by jstankowski** [Microsoft/vcpkg#2283]
fftw3 port is broken since [d476d8fe8d7704e62c70036352293c690e2d310e](https://github.com/Microsoft/vcpkg/commit/d476d8fe8d7704e62c70036352293c690e2d310e). Does not build single and long-double precision libs (fftw3f.lib + fftw3f.dll and fftw3l.lib + fftw3l.dll), but only double precision version (fftw3.lib + fftw3.dll).

**Comment by xoviat** [comment]
I think we need these options?


```
option (ENABLE_FLOAT "single-precision" OFF)
option (ENABLE_LONG_DOUBLE "long-double precision" OFF)
option (ENABLE_QUAD_PRECISION "quadruple-precision" OFF)
```

**Comment by jstankowski** [comment]
> I think we need these options?

1. Not only. It looks like fftw3 changed parameter names (BUILD_SINGLE --> ENABLE_FLOAT, BUILD_LONG_DOUBLE --> ENABLE_LONG_DOUBLE). 

2. The functionality of building all 3 versions of lib is still broken. After 1. changes only fftw3l is built.

Diff for point 1.
```diff
 ports/fftw3/portfile.cmake | 6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)

diff --git a/ports/fftw3/portfile.cmake b/ports/fftw3/portfile.cmake
index d5fc1bf0..c16631ba 100644
--- a/ports/fftw3/portfile.cmake
+++ b/ports/fftw3/portfile.cmake
@@ -17,13 +17,13 @@ vcpkg_download_distfile(ARCHIVE
 
 vcpkg_extract_source_archive(${ARCHIVE})
 
-option(BUILD_SINGLE "Additionally build single precision library" ON)
-option(BUILD_LONG_DOUBLE "Additionally build long-double precision library" ON)
+option(ENABLE_FLOAT "Additionally build single precision library" ON)
+option(ENABLE_LONG_DOUBLE "Additionally build long-double precision library" ON)
 
 vcpkg_configure_cmake(
     SOURCE_PATH ${SOURCE_PATH}
     PREFER_NINJA
-    OPTIONS -DBUILD_SINGLE=${BUILD_SINGLE} -DBUILD_LONG_DOUBLE=${BUILD_LONG_DOUBLE}
+    OPTIONS -DENABLE_FLOAT=${ENABLE_FLOAT} -DENABLE_LONG_DOUBLE=${ENABLE_LONG_DOUBLE}
 )
 
 vcpkg_install_cmake()
```

**Comment by bagong** [comment]
Looks like the build must be triggered 3 times with different settings. That is how it was done in the previous cmake build with the custom build-script. I doubt, btw., that quadruple works on Windows, should be verified.

**Comment by jstankowski** [comment]
> Looks like the build must be triggered 3 times with different settings. That is how it was done in the previous cmake build with the custom 

So maybe just revert the build script to previous version?

>  I doubt, btw., that quadruple works on Windows, should be verified.

IIRC only POWER uArch has native quads and is not supported by MSVC. Probably long double also doesn't make sense, in MSVC long double is an alias for double.

Probably version for single (memory efficiency and performance) and double (precision) is enough.

**Comment by bagong** [comment]
>> Looks like the build must be triggered 3 times with different settings. That is how it was done in the previous cmake build with the custom

> So maybe just revert the build script to previous version?

No, the previous version was a fully independent, 3rd party cmake script to build fftw, it had nothing to do with the very recently commited cmake support that *comes with* fftw, which should now be considered the "original" build system for Windows. I only referred to the old script because it contained the logic "the build must be retriggered with different settings as often as differing precision versions are required" (this used to be three, single, double, long double, but maybe long double was redundant). I haven't inspected the new build scripts, but it seems possible that this logic still prevails. In that case a little cmake script would have to be added in vcpkg that triggers each build with the correct settings.
