### ISSUE TITLE
[boost] build script cannot handle compiler flags with spaces

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#22840]
errors observed in #22831
`/FU\C:/Program <cxxflags>Files <cxxflags>(x86)/Microsoft <cxxflags>Visual <cxxflags>Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/lib/x86/store/references/platform.winmd\`

**Comment by yurybura** [comment]
Related to #22371
