### ISSUE TITLE
How do i add MNN to my cmake project ?

### ISSUE THREAD

**Issue by ishanshLal-tRED** [microsoft/vcpkg#22847]
cannot find MNNConfig.cmake in vcpkg directory (it dosen't exist), previously when project was in visual studio so it was picking up every installed package, now moving my project to cmake and vcpkg **(manifest-mode)**, i found there's no config file for mnn in vcpkg, since i'm concerned regarding portability how would it be possible get mnn includes and mnn lib directory to link with target
![image](https://user-images.githubusercontent.com/61790879/151613788-56ce73b8-8271-4220-a480-dbbee3f2a31b.png)
 
like to do in my project [an example]
![image](https://user-images.githubusercontent.com/61790879/151614092-bf347f4b-052a-4587-b204-07e69d2ae315.png)

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Due to `MNN` doesn't provide ***config.cmake** and ***target.cmake** files, so we can't use `find_package` to find `MNN` in CMake Project. You can use `find_path` and `find_library` to use `MNN`.

**Comment by LilyWangLL** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
