### ISSUE TITLE
[plplot] Build error

### ISSUE THREAD

**Issue by Meghana-Chava** [microsoft/vcpkg#22868]
**Host Environment**
- OS: Windows 10
- Compiler: revision

**To Reproduce**
vcpkg.exe install plplot

**Failure logs** 

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:111 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
  ports/plplot/portfile.cmake:42 (vcpkg_cmake_install)
  scripts/ports.cmake:145 (include)

Error: Building package plplot:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.

  package: plplot[core]:x64-windows -> 5.13.0#15
    vcpkg-tool version: 2021-12-09-724cea8b33cbf06c645f5095fa29773697da9761
    vcpkg-scripts version: 6ba505cf2 2022-01-28 (2 days ago)

**Comment by JackBoosY** [comment]
Please provide the full output.

Thanks.

**Comment by JackBoosY** [comment]
Ping for response.

**Comment by JackBoosY** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
