### ISSUE TITLE
[qtbase,qtdeclarative] It is compiling twice when using a custom triplet

### ISSUE THREAD

**Issue by abique** [microsoft/vcpkg#22865]
Hi,

Currently qtbase is compiling twice when using a custom triplet, and same for qtdeclarative.

I suspect that this is due to:
```JSON
    {
      "name": "qtbase",
      "host": true,
      "default-features": false
    },
```

Is it because of qmake, moc or other tools?
Do you think we could extract those tools into a dedicated package like `qt-moc`, etc...?

Also, in my case my custom triplet is actually targeting the current host, so maybe vcpkg could find out that it is not necessary to rebuild? 

Compiling a second time qt has a major impact, especially when using github actions which are limited in space.

@Neumann-A sorry to ping you again, do you have an insight on this issue?

**Comment by Neumann-A** [comment]
> sorry to ping you again, do you have an insight on this issue?

this is not an issues that is by design..... if you have a custom triplet and you are not cross-compiling you need to pass `--host-triplet=<custom-triplet>` or set `VCPKG_HOST_TRIPLET` to the same value as `VCPKG_TARGET_TRIPLET`.

**Comment by abique** [comment]
Ah thank you very much!
I guess we can close this ticket then.
