### ISSUE TITLE
Copy dependent libraries for a library (DLL) project?

### ISSUE THREAD

**Issue by stefando** [microsoft/vcpkg#2287]
Is it possible to inject an applocal.ps1 post build action into library project (as it is done for executables)? 

Thanks.

**Comment by jasjuang** [comment]
dll produced by vcpkg will be automatically copied to downstream applications and/or libraries

**Comment by stefando** [comment]
Hello @jasjuang. 
That is what I expected.
How ever I see that the vcpkg libraries are copied only for the exe projects.

In the sample application ("Using Sqlite"):
- when using the the original CMakeLists.txt the sqlite3.dll is copied as expected
- if you change add_executable(main main.cpp) to **add_library**(main main.cpp) the sqlite3.dll **is not copied**

**Comment by ras0219-msft** [comment]
Thanks for the request! We do need something for these scenarios (it has been brought up before as well).

Some questions:
- Should it not always occur? If so, on by default or off by default?
- Should it be explicitly requested by the CMakeLists? Would this be ideal:
```cmake
add_library(main main.cpp)
if(FUNCTION vcpkg_applocal_deps)
  vcpkg_applocal_deps(main)
endif()
```

**Comment by stefando** [comment]
My expectations have been based on the C#/nuget behavior where if you add a nuget package the appropriate assemblies/dlls will copied to the right place.

However, I have very limited experience with cmake so I cannot comment what would be idiomatically the right default.

For my current scenario it would be OK to explicitly request to copy dependencies (and the the proposed syntax looks feasible as well).

**Comment by NancyLi1013** [comment]
This feature should be implemented now. Since `vcpkg_applocal_deps()` has been added to vcpkg.
Please try to update vcpkg and rebuild.
