### ISSUE TITLE
[snappy] build failure

### ISSUE THREAD

**Issue by bertox94** [microsoft/vcpkg#22874]
**Host Environment**
- OS: Windows 10
- Compiler: clang-cl 12.0.0

**To Reproduce**
`./vcpkg install snappy:x86-windows`

**Failure logs** 
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
    Command failed: ninja -v
    Working Directory: C:/Users/alt/vcpkg/buildtrees/snappy/x86-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
    [config-x86-windows-out.log](https://github.com/microsoft/vcpkg/files/7970286/config-x86-windows-out.log)

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:338 (vcpkg_execute_required_process)
  ports/snappy/portfile.cmake:12 (vcpkg_configure_cmake)
  scripts/ports.cmake:144 (include)

**Additional context**
The compiler is set in a toolchain file, which is referenced by the VCPKG_CHAINLOAD_TOOLCHAIN_FILE in the community triplet file

**Comment by bertox94** [comment]
Tried also with the official triplet [x86-windows.txt](https://github.com/microsoft/vcpkg/files/7993105/x86-windows.txt) and toolchain [windows2.txt](https://github.com/microsoft/vcpkg/files/7993111/windows2.txt).

**Comment by JackBoosY** [comment]
```
C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/Llvm/bin/clang-cl.exe
```
Did you install the C++ core features with Visual Studio Installer?

**Comment by JackBoosY** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
