### ISSUE TITLE
Request: Add re2 pattern matching library

### ISSUE THREAD

**Issue by rapoth** [Microsoft/vcpkg#2288]
Thank you for the amazing work on vcpkg! We are working towards moving completely to vcpkg for dependency management and so far, the only library missing is [re2](https://github.com/google/re2) (a popular pattern matching library). 

Do you have any plans for supporting re2?

**Comment by ras0219-msft** [comment]
We don't currently have re2 on the backlog to package, but we would _love_ to accept a PR for it!

Here's our walkthrough for packaging zlib if you'd like to give it a shot: https://github.com/Microsoft/vcpkg/blob/master/docs/examples/packaging-zlib.md

**Comment by rapoth** [comment]
Thank you for your response. I've submitted a PR here: https://github.com/Microsoft/vcpkg/pull/2298 and verified that everything works on my machine.

**Comment by alexkaratarakis** [comment]
#2298 merged, thanks!
