### ISSUE TITLE
[crashpad] Support Linux/Android targets and arm64 architecture

### ISSUE THREAD

**Issue by jason-ortiz** [microsoft/vcpkg#22891]
****

**Is your feature request related to a problem? Please describe.**
Can only build Crashpad for Windows/Mac currently, although Crashpad supports building for more triplets than allowed by this port currently.

**Proposed solution**
Would like to use this port to build Crashpad for Android arm64 at least. Would also like to build it cross-platform (e.g. on Windows via Android NDK). The latter would require updating mini_chromium's BUILD.gn file accordingly.

**Describe alternatives you've considered**
Removing the vcpkg_fail_port_install call and building on Linux.

**Additional context**
I've created a private version of this port that builds for Android on Windows and applies patches to mini_chromium accordingly. Will consider publishing PR with suggested changes, if possible, but that will require more thorough testing of more triplets.

**Comment by Cheney-W** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
