### ISSUE TITLE
[x264] arm64 cross-compile settings are ignored.

### ISSUE THREAD

**Issue by sylvain-prevost** [microsoft/vcpkg#22899]
**Describe the bug**
[x264] port does **not** propagate cross-compile settings to the 'configure' script. The package is built using host settings leading to output executable format mismatch (if expected output is aarch64 and host is x86_64, for ex).

**Host Environment**
- OS: Linux
- Arch: x86_64
- Compiler: gcc 10.3.0
- Cross-Compiler: linaro arm64 cross-compiler v7.5.0

**Target Environment**
- OS: Linux
- Arch: arm64
- Compiler: gcc linaro v7.5.0

**To Reproduce**

1. Use triplet with any cross-compile toolchain (via VCPKG_CHAINLOAD_TOOLCHAIN_FILE)
2. Add vcpkg-cmake to vcpkg.json
3. Add following lines to portfile
```
vcpkg_cmake_get_vars(cmake_vars_file)
include("${cmake_vars_file}")
```
4. Build
5. Verify that VCPKG_DETECTED_CMAKE_CROSSCOMPILING is set to TRUE in cmake-vars log file.
6. Verify in build log that cross-compile toolchain compiler was **NOT** used.

**Expected behavior**
Build should work, but use the appropriate cross-compile compiler as set per the toolchain.

**Failure logs** 
n.a

**Additional context**
The x264 'configure' options '--host' and '--cross-prefix' are not propagated, hence the build does not use the appropriate tools.

**Comment by LilyWangLL** [comment]
Hi @sylvain-prevost, PR #22331 has been merged, do you have plan to cerate a new PR to continue fix this issue?
