### ISSUE TITLE
[sqlite3] Build error

### ISSUE THREAD

**Issue by Ashkel** [microsoft/vcpkg#22893]
**Host Environment**
- OS: Windows 10 Home x64 21H1 19043.1466
- Compiler: CMAKE

**To Reproduce**
`./vcpkg install openssl[core]:x64-windows` and `./vcpkg install openssl[core]:x64-windows-static`

**Failure logs** 
Installing package openssl[core]:x64-windows...
Elapsed time for package openssl:x64-windows: 11.53 min
Starting package 137/160: sqlite3:x64-windows
Building package sqlite3[core]:x64-windows...
-- Downloading https://sqlite.org/2021/sqlite-amalgamation-3370000.zip -> sqlite-amalgamation-3370000.zip...
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' = off
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Downloading https://sqlite.org/2021/sqlite-amalgamation-3370000.zip
Error: Failed to download from mirror set:
File does not have the expected hash:
             url : [ https://sqlite.org/2021/sqlite-amalgamation-3370000.zip ]
       File path : [ C:\vcpkg\downloads\sqlite-amalgamation-3370000.zip.6916.part ]
   Expected hash : [ e33935e513e52c825ebdef8eab92a4a839731a3b8fffcd5910a5dbd305ffd4cb627bf10c3d191dd934d1d6707e4a199dd098073953322768d5210fc726eb22fd ]
     Actual hash : [ f969b823a7d342c823854e21938023ff28bcda3e7b1460e49ecc1da418352b314c250e70f785691685ad70009a4b2b4f6a656a565f236b4b1d6b732377c15da3 ]

[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(705)
[DEBUG] Time in subprocesses: 0 us
[DEBUG] Time in parsing JSON: 4 us
[DEBUG] Time in JSON reader: 0 us
[DEBUG] Time in filesystem: 2545 us
[DEBUG] Time in loading ports: 0 us
[DEBUG] Exiting after 15.44 s (15127479 us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:84 (message):

      Failed to download file with error: 1
      If you use a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.

      3. You proxy's remote server is out of service.

      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)

      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:309 (z_vcpkg_download_distfile_show_proxy_and_fail)
  ports/sqlite3/portfile.cmake:6 (vcpkg_download_distfile)
  scripts/ports.cmake:145 (include)

Error: Building package sqlite3:x64-windows failed with: BUILD_FAILED

**Additional context**
Tried to update vcpkg with `git pull` and `.\vcpkg update`.
I completely removed vcpkg and installed it again.

**Comment by JackBoosY** [comment]
Please download [this file](https://github.com/microsoft/vcpkg/files/7992021/sqlite-amalgamation-3370000.zip) and put it into _VCPKG_ROOT/downloads_ and try again.

Thanks.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
