### ISSUE TITLE
Binarycaching + VCPKG_APPLOCAL_DEPS does not replace libraries properly

### ISSUE THREAD

**Issue by cbrammere3d** [microsoft/vcpkg#22896]
**Describe the bug**
I have 2 Versions (A, B) of vcpkg dependencies cached in Nuget using binarycaching. When checking out a branch which swaps from Version A to B, the DLLs copied by `VCPKG_APPLOCAL_DEPS` are replaced properly. When swapping from B to A they are not.

**Environment**
- OS: Windows

**Expected behavior**
The current DLLs in the `vcpkg_installed` folder are always correctly deployed even when changing binary-cached versions.

**Analysis**
The script resposible for copying the DLLs on Windows is `applocal.ps1`. The Bug lies within the used timestamp:
```powershell
# applocal.ps1
$sourceModTime = (Get-Item $sourceBinaryFilePath).LastWriteTime
            $destModTime = (Get-Item $targetBinaryFilePath).LastWriteTime
            if ($destModTime -lt $sourceModTime) {
                Write-Verbose "  ${targetBinaryName}: Updating from $sourceBinaryFilePath"
                Copy-Item $sourceBinaryFilePath $targetBinaryDir
            } else {
                Write-Verbose "  ${targetBinaryName}: already present"
            }
```
As we can see it uses `LastWriteTime` of the file to determine if the file is already present. Since the files are built and then stored in Nuget the `LastWriteTime` field does not change once stored in Nuget. In other words it describes the build time of the dependency and does not change when downloaded and unpacked from Nuget. This leads to the older build versions to never be copied if a newer version was present.

To fix this one could take `CreationTime` into account since it will be set to the date where the files was copied from Nuget to the `vcpkg_installed` folder, which would resolve this use-case. There are probably other use-cases that need to be considered.

**Additional Information**
Posted now as a bug since I figured out why it happens. https://github.com/microsoft/vcpkg/discussions/22886

Thanks for an awesome C++ dependency tool :)

**Comment by JackBoosY** [comment]
@ras0219-msft Can you please take a look?

**Comment by MonicaLiu0311** [comment]
Ping @JavierMatosD
