### ISSUE TITLE
cuda build failure

### ISSUE THREAD

**Issue by timluther** [microsoft/vcpkg#22903]
**Host Environment**
- OS: Windows
- Compiler:  

**To Reproduce**
`./vcpkg install cuda`

**Failure logs** 
vcpkg install cuda
Computing installation plan...
The following packages will be built and installed:
    cuda[core]:x64-windows -> 10.1#8
Detecting compiler hash for triplet x64-windows...
Restored 1 packages from C:\Users\luthe\AppData\Local\vcpkg\archives in 162.2 ms. Use --debug to see more details.
Starting package 1/1: cuda:x64-windows
Installing package cuda[core]:x64-windows...
Elapsed time for package cuda:x64-windows: 1.112 s

Total elapsed time: 10.86 s

**Additional context**
Appears to install Cuda but does not. No error message given but it spends no time installing and no cuda headers or libraries are present.

**Comment by JackBoosY** [comment]
Port `CUDA` in vcpkg will only check cuda headers and libs, then install `vcpkg_find_cuda.cmake`.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
