### ISSUE TITLE
[New Port Request] Lua-Cjson

### ISSUE THREAD

**Issue by SethBe** [microsoft/vcpkg#22901]
Library name: lua-cjson
Source repository URL:  https://github.com/mpx/lua-cjson/

Project homepage (if different from the source repository):  https://www.kyne.com.au/~mark/software/lua-cjson.php

Anything else that is useful to know when adding: Depends on lua51 but will work with newer.

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
