### ISSUE TITLE
run vcpkg.exe install sqlite3 get error

### ISSUE THREAD

**Issue by z2665** [Microsoft/vcpkg#2290]
system os : Windows 10 Fall Creators Update
compiler & ide :  Visual Studio 2017 Community
When I run the command  vcpkg.exe install sqlite3 It return a error
like this:
PS D:\vcpkg\vcpkg> .\vcpkg.exe install sqlite3
The following packages will be built and installed:
    sqlite3:x86-windows
Starting package 1/1: sqlite3:x86-windows
Building package sqlite3:x86-windows...
Warning: The following VS instances are exluded because the English language pack is unavailable.
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community
Please install the English language pack.
Could not locate a complete toolset.
The following paths were examined:
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\bin\HostX86\x86\dumpbin.exe

**Comment by alexkaratarakis** [comment]
You need to install the English language pack on Visual Studio. You can do thing by starting the Visual Studio Installer, going to language pack; make sure English is checked, and even if it is already checked, click Modify. See also: https://github.com/Microsoft/vcpkg/issues/2295

**Comment by z2665** [comment]
I modify the language pack unclick the English and click it. 
after that it will install about 157MB size language packs.
Then run the vcpkg.exe install sqlite3. It can work well.
@alexkaratarakis  Thank you very much
