### ISSUE TITLE
vcpkg export with feature does not work anymore

### ISSUE THREAD

**Issue by gix** [microsoft/vcpkg#22913]
**Describe the bug**

`vcpkg export` fails when using features. This recently broke (probably <https://github.com/microsoft/vcpkg-tool/pull/298>?).

**Environment**
- OS: Windows
- Compiler: N/A

**To Reproduce**
1. `.\vcpkg.exe install 'abseil[cxx17]'`
2. `.\vcpkg export abseil[cxx17] --nuget`

    ```
    Error: List of features is not allowed in this contectExample:
      vcpkg export zlib zlib:x64-windows boost --nuget
    ```
3. `.\vcpkg export abseil --nuget`

    ```
    The following packages need to be built:
        abseil:x86-windows
    There are packages that have not been built.
    To build them, run:
        vcpkg install abseil:x86-windows
    ```

**Expected behavior**
Exporting a port with feature works as before.

**Comment by JackBoosY** [comment]
Yeah, but we may end up deprecating including features because the body of the export is a port instead of a feature.

**Comment by JackBoosY** [comment]
@ras0219-msft Is this changes by design?

**Comment by ras0219-msft** [comment]
Because export does not install or remove packages, the set of features has always had no substantial effect except perhaps failing if the features were not currently installed. Therefore, if you had a configuration before that worked, the workaround is simply to remove the feature list from the packages list. All features of the selected packages will be exported.

However, we'll still need to look into this as a scripting regression and perhaps issue a warning instead that features on the cli have no effect for the export command.

**Comment by daschuer** [comment]
If you consider a scripting environment where the same string is used to install and export the ports, it makes perfectly sens to have the list of features also during export. The alternative would be some magic string handling to remove the features, or using --x-all-installed. The later might be export deprecated packages that have been installed earlier.

**Comment by FrankHeimes** [comment]
This situation is unsatisfying. The latest version of `vcpkg` can not do what previous calls `.\vcpkg.exe install 'opencv4[contrib]'` did for me, i. e. downloading and installing a few header files for the `Aruco` extension of OpenCV

For OpenCV, a workaround is to patch `vcproj.json` to include `"contrib"` into the list of `"default-features"`.

But that defies the whole point of `vcpkg` to automagically install all required packages.

**Comment by invy** [comment]
> Therefore, if you had a configuration before that worked, the workaround is simply to remove the feature list from the packages list. All currently installed features of the selected packages will be exported.
Not very nice workaround, it either requires editing a bunch of build configuration, or doing some not really needed scripting.

> However, we'll still need to look into this as a scripting regression and perhaps issue a warning instead that features on the cli have no effect for the export command.

The problem appears in scripting environment. It is also related to the package dependencies. So I think the logic here could look like:
1. Export accepts packages with features.
2. Export verifies whether packages with corresponding features are installed, if no, there should be either warning or error. I.e. User has installed curl, but wants to export curl[ssh] which requires also libssh to be present, so it's a nice check.
3. Existing scripting environments should not break.

**Comment by pkeir** [comment]
Any update on this? I rely on `vcpkg export opencv[contrib]`, but now I get the message "error: list of features is not allowed in this context". Is there a workaround?

**Comment by dg0yt** [comment]
AFAIU the answer was that features don't make sense for the export command: https://github.com/microsoft/vcpkg/issues/22913#issuecomment-1031850921

There was the idea of adding a more tolerant behaviour, but maybe this tolerance is no longer relevant after almost two years.

**Comment by pkeir** [comment]
Thanks. I had misread that comment. The advice in my case would be to use `vcpkg export opencv`. I'll give that a try.

(I had been thinking of `opencv[contrib]` as adding a component (`contrib`) rather than specifying a feature.)
