### ISSUE TITLE
Errror: Build Openblas:x64-windows failed

### ISSUE THREAD

**Issue by cherichy** [Microsoft/vcpkg#2291]
when install Openblas-v0.2.20 using vcpkg: PS: vcpkg install openblas:x64-windows, error occors as follow:

-- Configuring x64-windows-rel
-- Configuring x64-windows-rel done
-- Configuring x64-windows-dbg
-- Configuring x64-windows-dbg done
-- Build x64-windows-rel
CMake Error at F:/codes/vcpkg/scripts/cmake/vcpkg_execute_required_process.cmake:44 (message):
    Command failed: D:/CMake/bin/cmake.exe;--build;.;--config;Release;--target;install;--;/p:VCPkgLocalAppDataDisabled=true;/p:UseIntelMKL=No;/m
    Working Directory: F:/codes/vcpkg/buildtrees/openblas/x64-windows-rel
    See logs for more information:
      F:\codes\vcpkg\buildtrees\openblas\install-x64-windows-rel-out.log
      F:\codes\vcpkg\buildtrees\openblas\install-x64-windows-rel-err.log

Call Stack (most recent call first):
  F:/codes/vcpkg/scripts/cmake/vcpkg_build_cmake.cmake:63 (vcpkg_execute_required_process)
  F:/codes/vcpkg/scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  F:/codes/vcpkg/ports/openblas/portfile.cmake:93 (vcpkg_install_cmake)
  F:/codes/vcpkg/scripts/ports.cmake:72 (include)

Error: Building package openblas:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openblas:x64-windows
  Vcpkg version: 0.0.99-2017-12-01-71f8958a069208b08a4bcca207956ef8a15238ab

Additionally, attach any relevant sections from the log files above.

Configure has no problem, but build failed. I check the log file and find that openblas use awk and sed in building.
In generated files vcpkg\buildtrees\openblas\x64-windows-rel\gencblas.vcxproj (line 98 and 113) , sed is called. And file genf77blas.vcxproj (line 98 and 111), awk is called.
 Although I have install mingw64 and have awk and sed in path, the build system ignores the path environment variables. When I changed the awk to \path\to\awk.exe and the same to sed, I can successfully build openblas in Visual Studio 2017.
So, How to solve the problem or Can I just continue to install the built binarys into vcpkg's installed packages?

**Comment by wsw0108** [comment]
It is because when `vcpkg` spawn `cmd`/`cmake` as child process, it only add the compiler's path to the execute environment, so thoes tools like `awk`/`sed` in your example can not be found.

**Comment by NancyLi1013** [comment]
@cherichy , @Madokakaroto , thanks for posting this issue. The package has been updated to 0.3.5-1 and I can install it successfully on my machine now. Please open a new issue if this is still a problem for you.
PS E:\vcpkgTest\vcpkg> .\vcpkg.exe install openblas:x64-windows
The following packages will be built and installed:
    openblas[core]:x64-windows
Starting package 1/1: openblas:x64-windows
Building package openblas[core]:x64-windows...
-- Downloading https://github.com/xianyi/OpenBLAS/archive/v0.3.5.tar.gz...
-- Extracting source E:/vcpkgTest/vcpkg/downloads/xianyi-OpenBLAS-v0.3.5.tar.gz
-- Applying patch uwp.patch
-- Applying patch fix-space-path.patch
-- Using source at E:/vcpkgTest/vcpkg/buildtrees/openblas/src/v0.3.5-c59ddfa6b5
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package openblas[core]:x64-windows... done
Installing package openblas[core]:x64-windows...
Installing package openblas[core]:x64-windows... done
Elapsed time for package openblas:x64-windows: 10.8 min

Total elapsed time: 10.8 min

The package openblas:x64-windows provides CMake targets:

    find_package(OpenBLAS CONFIG REQUIRED)
    target_link_libraries(main PRIVATE OpenBLAS::OpenBLAS)
