### ISSUE TITLE
[boost-chrono] Build error

### ISSUE THREAD

**Issue by LegendOfCatBro** [microsoft/vcpkg#22916]
**Host Environment**
- OS: Windows
- Compiler: revision

**To Reproduce**
`./vcpkg install websocketpp`

**Failure logs** 
package: boost-chrono[core]:x86-windows -> 1.78.0
    vcpkg-tool version: 2021-12-09-724cea8b33cbf06c645f5095fa29773697da9761
    vcpkg-scripts version: d8d61c941 2022-02-02 (19 hours ago)

**Additional context**

**Comment by JackBoosY** [comment]
Please provide the full output first.

Thanks.

**Comment by PhoebeHui** [comment]
@LegendOfCatBro, please reopen this issue with full failure logs if it still be a problem for you.
