### ISSUE TITLE
Speex modes variables are not exported

### ISSUE THREAD

**Issue by WPMGPRoSToTeMa** [Microsoft/vcpkg#2292]
Hello, I'm using VS 2017 on Windows 7.
The problem is when I'm using `speex` port with this code:
`auto encoder = speex_encoder_init(&speex_nb_mode);`
I'm getting:
`error LNK2001: unresolved external symbol _speex_nb_mode`
As a temporary solution I'm using:
`auto encoder = speex_encoder_init(speex_lib_get_mode(SPEEX_MODEID_NB));`
And it works fine.

**Comment by ras0219-msft** [comment]
Thanks for reporting this issue! It is fixed in the latest master :)

**Comment by WPMGPRoSToTeMa** [comment]
Sorry for the late, but `speex_header_free` is not exported too.

**Comment by ras0219-msft** [comment]
Thanks again!
