### ISSUE TITLE
[ICU] build failure OSX

### ISSUE THREAD

**Issue by GordonSmith** [microsoft/vcpkg#22933]
**Host Environment**
- OS: macOS Big Sur 11
- Compiler: Clang/LLVM 13.0.0

**To Reproduce**
`./vcpkg install icu`

**Failure logs** 
```
Building package icu[core]:x64-osx...
-- Downloading https://github.com/unicode-org/icu/releases/download/release-69-1/icu4c-69_1-src.tgz -> icu4c-69_1-src.tgz...
-- Extracting source /Users/runner/work/vcpkg/vcpkg/downloads/icu4c-69_1-src.tgz
-- Applying patch disable-escapestr-tool.patch
-- Applying patch remove-MD-from-configure.patch
-- Applying patch fix_parallel_build_on_windows.patch
-- Applying patch fix-extra.patch
-- Applying patch mingw-dll-install.patch
-- Applying patch disable-static-prefix.patch
-- Applying patch fix-win-build.patch
-- Using source at /Users/runner/work/vcpkg/vcpkg/buildtrees/icu/src/c-69_1-src-b48be0c7ce.clean
-- Getting CMake variables for x64-osx-dbg
-- Getting CMake variables for x64-osx-rel
-- Generating configure for x64-osx
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:128 (message):
    Command failed: /usr/local/bin/autoreconf -vfi
    Working Directory: /Users/runner/work/vcpkg/vcpkg/buildtrees/icu/src/c-69_1-src-b48be0c7ce.clean/source
    Error code: 2
    See logs for more information:
      /Users/runner/work/vcpkg/vcpkg/buildtrees/icu/autoconf-x64-osx-err.log
Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:610 (vcpkg_execute_required_process)
  ports/icu/portfile.cmake:51 (vcpkg_configure_make)
  scripts/ports.cmake:145 (include)
Error: Building package icu:x64-osx failed with: BUILD_FAILED
Elapsed time for package icu:x64-osx: 5.831 s
```

**Additional context**
Environment is the GitHub actions host:  https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md

**Comment by JackBoosY** [comment]
Please provide _/Users/runner/work/vcpkg/vcpkg/buildtrees/icu/autoconf-x64-osx-err.log_ first.

Thanks.

**Comment by JackBoosY** [comment]
Should same with #22934.

**Comment by GordonSmith** [comment]
@JackBoosY - FYI this was resolved with a 
```
brew install automake libtool
```
(It was a bit of pain to work out as I don't have a mac and was relying on GitHub actions)

**Comment by JackBoosY** [comment]
Yeah it needs those tools.

**Comment by ylz-at** [comment]
facing the same issue when trying to install qtbase.

**Comment by mamamakesgames** [comment]
> facing the same issue when trying to install qtbase.

This also required 'brew install autoconf-archive' on my system (OSX 12.3.1 x86_64) for qtbase. HTH. :)

**Comment by JosiahBLB** [comment]
> > facing the same issue when trying to install qtbase.
> 
> This also required 'brew install autoconf-archive' on my system (OSX 12.3.1 x86_64) for qtbase. HTH. :)

Thank you! 🙏
How does one figure out this was the problem?
