### ISSUE TITLE
Current 'dirent' package limits porting a lot because 'Windows.h'

### ISSUE THREAD

**Issue by carlo-bramini** [microsoft/vcpkg#22936]
VCPKG provides an implementation of POSIX dirent:

https://github.com/microsoft/vcpkg/tree/master/ports/dirent

Although its purpuse is to increase the chances to build foreing code, it happens that this package brutally limits the porting capabilities when your project uses VCPKG and it finds `dirent.h` into the path. The reason is that this dirent package includes `Windows.h` internally and, because of that, all its stuff is also exposed to the code that included `dirent.h`. The results can be warnings and errors because name conflicts.

It would be better to use a different code for implementing the functions provided by dirent, by using C library functions, for example `_findfirst`/`_findnext`/`_findclose`, rather than Windows APIs.

**Comment by JackBoosY** [comment]
@BillyONeal what do you think about this?

**Comment by BillyONeal** [comment]
I think this is an upstream enhancement request one should report against https://github.com/tronkko/dirent and this issue should be closed, as there is nothing specific to vcpkg here.

**Comment by carlo-bramini** [comment]
> I think this is an upstream enhancement request one should report against https://github.com/tronkko/dirent and this issue should be closed, as there is nothing specific to vcpkg here.

In my opinion, at this time the solutions to this issue can be:
1) the project that provides support for dirent must allow the feature but without using the Windows API (and this can be seen as an enhancement to that upstream) or
2) vcpkg should use something different than that.

**Comment by JackBoosY** [comment]
@carlo-bramini This should be considered by the upstream, not vcpkg.
vcpkg will not change any source code of these ports.

**Comment by JackBoosY** [comment]
Close this issue/PR until upstream fixes this.
