### ISSUE TITLE
[leptonica] Build error

### ISSUE THREAD

**Issue by YuryBrodskiy** [microsoft/vcpkg#22938]
**Host Environment**
- OS: windows
- Compiler: revision

**To Reproduce**
`vcpkg install leptonica:x64-windows`

**Failure logs** 
```
- Cleaning sources at C:/workspace/vcpkg/buildtrees/leptonica/src/2f893da097-acceb02b8a.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/workspace/vcpkg/downloads/DanBloomberg-leptonica-2ff4313a85427ceb272540c570106b2f893da097.tar.gz
-- Applying patch fix-cmakelists.patch
-- Applying patch find-dependency.patch
-- Applying patch fix-find-libwebp.patch
-- Applying patch Modify-include-dir.patch
-- Using source at C:/workspace/vcpkg/buildtrees/leptonica/src/2f893da097-acceb02b8a.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
CMake Warning at installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:487 (message):
  The following variables are not used in CMakeLists.txt:

      CPPAN_BUILD

  Please recheck them and remove the unnecessary options from the
  `vcpkg_cmake_configure` call.

  If these options should still be passed for whatever reason, please use the
  `MAYBE_UNUSED_VARIABLES` argument.
Call Stack (most recent call first):
  ports/leptonica/portfile.cmake:16 (vcpkg_cmake_configure)
  scripts/ports.cmake:145 (include)


-- Building x64-windows-dbg
CMake Warning at scripts/cmake/vcpkg_execute_build_process.cmake:89 (message):
  Please ensure your system has sufficient memory.
Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:111 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
  ports/leptonica/portfile.cmake:27 (vcpkg_cmake_install)
  scripts/ports.cmake:145 (include)


-- Restarting build without parallelism
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:158 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j17
    Working Directory: C:/workspace/vcpkg/buildtrees/leptonica/x64-windows-dbg
    See logs for more information:
      C:\workspace\vcpkg\buildtrees\leptonica\install-x64-windows-dbg-out.log
      C:\workspace\vcpkg\buildtrees\leptonica\install-x64-windows-dbg-out-1.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:111 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
  ports/leptonica/portfile.cmake:27 (vcpkg_cmake_install)
  scripts/ports.cmake:145 (include)


Error: Building package leptonica:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+leptonica
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[leptonica]+Build+error
including:
  package: leptonica[core]:x64-windows -> 1.81.1
    vcpkg-tool version: 2022-02-01-c76e0def147898591d9c35113b95e0b3f2eaa4d4
    vcpkg-scripts version: c0d667ad6 2022-02-04 (5 hours ago)

Additionally, attach any relevant sections from the log files above.
```
**Additional context**
End of -db-gout.log 

```
C:\workspace\vcpkg\buildtrees\leptonica\src\2f893da097-acceb02b8a.clean\src\utils2.c(3231): warning C4267: '=': conversion from 'size_t' to 'l_int32', possible loss of data
C:\workspace\vcpkg\buildtrees\leptonica\src\2f893da097-acceb02b8a.clean\src\utils2.c(3242): warning C4267: '=': conversion from 'size_t' to 'l_int32', possible loss of data
C:\workspace\vcpkg\buildtrees\leptonica\src\2f893da097-acceb02b8a.clean\src\utils2.c(3469): warning C4267: '=': conversion from 'size_t' to 'l_int32', possible loss of data
C:\workspace\vcpkg\buildtrees\leptonica\src\2f893da097-acceb02b8a.clean\src\utils2.c(2915) : warning C4706: assignment within conditional expression
[180/181] cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_dll --intdir=src\CMakeFiles\leptonica.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MICROS~2\2019\PROFES~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\link.exe  @CMakeFiles\leptonica.rsp  /out:bin\leptonica-1.81.1d.dll /implib:src\leptonica-1.81.1d.lib /pdb:bin\leptonica-1.81.1d.pdb /dll /version:1.81 /machine:x64 /nologo    /debug /INCREMENTAL  && cd ."
FAILED: bin/leptonica-1.81.1d.dll src/leptonica-1.81.1d.lib 
cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_dll --intdir=src\CMakeFiles\leptonica.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MICROS~2\2019\PROFES~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\link.exe  @CMakeFiles\leptonica.rsp  /out:bin\leptonica-1.81.1d.dll /implib:src\leptonica-1.81.1d.lib /pdb:bin\leptonica-1.81.1d.pdb /dll /version:1.81 /machine:x64 /nologo    /debug /INCREMENTAL  && cd ."
LINK Pass 1: command "C:\PROGRA~2\MICROS~2\2019\PROFES~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\link.exe @CMakeFiles\leptonica.rsp /out:bin\leptonica-1.81.1d.dll /implib:src\leptonica-1.81.1d.lib /pdb:bin\leptonica-1.81.1d.pdb /dll /version:1.81 /machine:x64 /nologo /debug /INCREMENTAL /MANIFEST /MANIFESTFILE:src\CMakeFiles\leptonica.dir/intermediate.manifest src\CMakeFiles\leptonica.dir/manifest.res" failed (exit code 1104) with the following output:
LINK : fatal error LNK1104: cannot open file 'openjp2.lib'
ninja: build stopped: subcommand failed.
```

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. I found you use cmake which not installed by VCPKG. `"C:\Program Files\CMake\bin\cmake.exe"`
Could you remove it and install port again? And therer are error: `LINK : fatal error LNK1104: cannot open file 'openjp2.lib'`, could you please check _VCPKG_ROOT/installed/x64-windows/lib/openjp2.lib_  is correct exist?

**Comment by dweckmann** [comment]
> Thanks for posting this issue. I found you use cmake which not installed by VCPKG. `"C:\Program Files\CMake\bin\cmake.exe"` Could you remove it and install port again? And therer are error: `LINK : fatal error LNK1104: cannot open file 'openjp2.lib'`, could you please check _VCPKG_ROOT/installed/x64-windows/lib/openjp2.lib_ is correct exist?

Hello, I'm experiencing the same issue here, and the fix is to remove the "system" cmake (in my case cmake 3.22.2, installed from chocolatey). In short the problem disappeared once I used the cmake installed from VCPKG.

**Comment by LilyWangLL** [comment]
Ping @YuryBrodskiy

**Comment by YuryBrodskiy** [comment]
openjp2 is installed and present.
The problem in CMakeList  openjp2 is too complex and fails somewhere, giving openjp2.lib without full path. 
compare to all other libraries that give absolute path. 
 I have when through the build process and made a workaround by adding
find_package(OpenJPEG CONFIG REQUIRED) in CMakeList.txt on line 67 inside leptonica\src\
then build using   --editable flag

Naturally there should be a cleaner solution

**Comment by dg0yt** [comment]
The original issue here was reported with `C:\Program Files\CMake\bin\cmake.exe`.
We recently found that at least python's pip installs a broken CMake 3.22 which fails to deal correctly with file system paths  (cf. https://github.com/scikit-build/cmake-python-distributions/issues/221, including cmake test code). This can lead to all type of path-related problems.
So you can check if your CMake is affected by this problem, or you can simply use the version installed by CMake, as used in vcpkg CI.

**Comment by YuryBrodskiy** [comment]
The problem has been replicated by my colleagues 3 times on different PC with different setups, so it doesn't feel like specific setup problem. I have not used pip to install my CMake, moreover, I have used the official CMake installer just prior to the running build.
I have built a big number of dependencies(300 packages) and only leptonica has a problem with paths.

Btw my recommendation is to increase the minimum CMake version requirements (currently 3.1) inside CMakeLists.txt to least (3.13 higher is better), as many CMake commands have changed semantics. This would allow you to significantly simplify the CMakeLists file.
As have mentioned in the previous comment "find_package(OpenJPEG CONFIG REQUIRED)" will do most of the solution.

**Comment by dweckmann** [comment]
> I have not used pip to install my CMake, moreover, I have used the official CMake installer just prior to the running build. I have built a big number of dependencies(300 packages) and only leptonica has a problem with paths.

I second that. I've also installed CMake 3.22 with chocolatey, which use the default official installer. I've never used PIP to install CMake.

The strange thing is that when I call `vcpkg.exe install leptonica` first, there is no problem at all, only when leptonica is installed because being a dependency. Once the build failed, even calling `vcpkg.exe install leptonica` alone, will fail. It only works on a clean vcpkg build tree.

I also agree that the correct fix should be to add `find_package(OpenJPEG CONFIG REQUIRED)`. Otherwise, using CMake 3.21 could be a workaround.

**Comment by LilyWangLL** [comment]
@YuryBrodskiy Could you provide the log file `config-x64-windows-out.log` which you use CMake 3.22 install `leptonica`?

**Comment by YuryBrodskiy** [comment]
I don't have the original one, as I have successfully rebuilt the package using the fixes described above. Sorry, I don't want to break my current setup to replicate the problem, project pressure.  
I can give you the latest successful build version of the log if you want.

**Comment by ishanshLal-tRED** [comment]
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/8118008/install-x64-windows-dbg-out.log)
this is my build logs, just few moments ago i started facing same issue. (after cmake upgrade from 3.22.1 to 3.23.0-rc1)

**Comment by sfhacker** [comment]
Many users here are wondering what's different between this cmake [1] and the cmake provided by vcpkg? Is it a custom build? If so, why?

[1] https://github.com/Kitware/CMake/releases/
