### ISSUE TITLE
[New port request] easings/raygui/physac

### ISSUE THREAD

**Issue by yhl1219** [microsoft/vcpkg#22935]
Library name: raylib

New version number: previous it is 4.0.0#2

It seems that the current raylib package in vcpkg (version 4.0.0#2) misses something with raylib extras, like physac.h, raygui.h, etc. Those headers are included in "extras/... .h" folder and I've checked vcpkg include and there's no "extras", only raylib.h, raymath.h, rlgl.h and probably raudio.h. I think it should be also included into the include directory which is origin under the raylib / src / extras.

**Comment by JonLiu1993** [comment]
@yhl1219 ,Thanks for posting this issue, after our confirmation with raylib upstream, you can install them in vcpkg side, I have submitted pr to solve this problem.

**Comment by frankhale** [comment]
This issue is quite old and I'd love to have at least raygui along side raylib. Is there any way to move forward on this? Work arounds? I will but don't want to include raygui and extra (header only libs) in my source directly. I'd rather have them installed via vcpkg.

**Comment by ex-purple** [comment]
I made two PR for the raygui and physac. 
What is it easings? This is nowhere to be found.
