### ISSUE TITLE
Why vcpkg installs x64-windows binaries for x86-windows-static triplet?

### ISSUE THREAD

**Issue by okravets** [microsoft/vcpkg#22940]
I am trying to compile my project using latest cmake and vcpkg using manifest mode and CMakePresets.json.
I have specific configuration for x86-windows-debug-static with :
        "VCPKG_INSTALLED_DIR": "$env{VCPKG_ROOT_DIR}/baselines/c0d667",
        "CMAKE_BUILD_TYPE": "Debug",
        "VCPKG_TARGET_TRIPLET": "x86-windows-static"

So for some reason it performs installation of packages for x64-windows and for x86-windows-static.

Moreover, when I switch from x86-windows-static to x64-windows-static, it deletes installed packages from $env{VCPKG_ROOT_DIR}/baselines/c0d667.

Any advice how I could configure to install in one VCPKG_INSTALLED_DIR directory and avoid removing other triplets packages?

Thank you,
Olexandr

**Comment by okravets** [comment]
Output:
* brotli[core]:x64-windows -> 1.0.9#2 -- I:\vcpkg\c0d667\buildtrees\versioning_\versions\brotli\73d0ed2fd7816c7a4958983b0b027c85b60eac15
  * brotli[core]:x86-windows-static -> 1.0.9#2 -- I:\vcpkg\c0d667\buildtrees\versioning_\versions\brotli\73d0ed2fd7816c7a4958983b0b027c85b60eac15

**Comment by dg0yt** [comment]
Usually it means that your target triplet (x86-windows-static) is different from you host triplet (default: x64-windows). But many ports do have host dependencies.

**Comment by okravets** [comment]
Ok, I understand why we have them both, but I still do not understand why if I switch from x86-windows-static to x64-windows-static, it deletes installed packages. I would expect new to be added only ...

**Comment by dg0yt** [comment]
Manifest mode ensures that the installed packages match the configuration, including the active triplets. In that way, it avoids some conflicts and hidden dependencies. Normally, removal isn't a problem because the binary artifacts are cached separately.
If you need to work with multiple target triplets, you should use different build directories. All your binary project artifacts depend on the targe triplet.

**Comment by Osyotr** [comment]
If you think that target executables are compatible with host machine, you can override `VCPKG_HOST_TRIPLET` and don't build additional host dependencies.

**Comment by dg0yt** [comment]
> If you think that target executables are compatible with host machine, you can override `VCPKG_HOST_TRIPLET` and don't build additional host dependencies.

Yes. 
But it also means that the "host" dependencies are built and cached for every triplet. If you really want to build for different targets, it might need more space and time.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
