### ISSUE TITLE
[New Port Request] Dawn

### ISSUE THREAD

**Issue by Kuranes** [microsoft/vcpkg#22948]
Library name: Dawn

Library description: allows to compile webgpu in native (and emscripten)

Source repository URL: https://dawn.googlesource.com/dawn/

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
crucial for webgpu deployment using msvc dev environment, as for now it's really hard to do wegpu native in c++, as that dependency is a complex one

**Comment by linuxaged** [comment]
Any progress? maybe we can do the same like adding skia? https://github.com/microsoft/vcpkg/issues/835

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.

**Comment by retifrav** [comment]
> Any progress?

There is at least one attempt to make a port [here](https://github.com/microsoft/vcpkg/pull/32153).

If anything, I was able to use that PR to make [my own port](https://github.com/retifrav/vcpkg-registry/tree/master/ports/dawn) in my personal registry (*with dependencies on my custom versions of other ports*). Quite naturally, I can only vouch for it to work in my own projects (*"works-on-my-machine"*).

**Comment by sshsphere** [comment]
Would this be easier to implement now that dawn has the `DAWN_ENABLE_INSTALL` cmake option? Related docs [here](https://dawn.googlesource.com/dawn/+/HEAD/docs/quickstart-cmake.md)

**Comment by dg0yt** [comment]
Easier, yes. But it probably still takes some work to integrate well with vcpkg.

**Comment by patrikhuber** [comment]
Another interested party here...
