### ISSUE TITLE
[New Port Request] GMT

### ISSUE THREAD

**Issue by insar-dev** [microsoft/vcpkg#22954]
hi,
could somebody add GMT port, it is widely used in GIS drawing.
in ubuntun, we can install it by sudo apt install libgmt-dev.
thanks.

Library name: GMT

Library description:

GMT is an open source collection of about 90 command-line tools for manipulating geographic and Cartesian data sets (including filtering, trend fitting, gridding, projecting, etc.) and producing high-quality illustrations ranging from simple x–y plots via contour maps to artificially illuminated surfaces, 3D perspective views and animations. The GMT supplements add another 50 more specialized and discipline-specific tools. GMT supports over 30 map projections and transformations and requires support data such as [GSHHG](http://www.soest.hawaii.edu/pwessel/gshhg/) coastlines, rivers, and political boundaries and optionally [DCW](http://www.soest.hawaii.edu/pwessel/dcw) country polygons.

Source repository URL:

https://github.com/GenericMappingTools/gmt

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by dg0yt** [comment]
IIUC GMT is a set of tools for end users, not a library with a public API for developers.

**Comment by insar-dev** [comment]
@dg0yt GMT could be used as a library now.
https://docs.generic-mapping-tools.org/6.2/api.html

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
