### ISSUE TITLE
Please help with:  Building package x265 fails

### ISSUE THREAD

**Issue by chris-batty** [microsoft/vcpkg#22953]
Hello VCPKG Team!

** VCPKG is a wonderful toolset/environment, and generally works flawlessly for me.  Well Done!! **

However, I ran into a problem with installation of the x265 (HEVC Video Encoder) package.

There appears to be a problem getting the file:
       https://bitbucket.com/multicoreware/x265/get/3.2.tar.gz

The details of the failure are given below.

Thanks for your help!
Chris

====================================================================
```
S:\Sd\3p\VCPKG>vcpkg install x265
The following packages will be built and installed:
    x265[core]:x86-windows
Starting package 1/1: x265:x86-windows
Building package x265[core]:x86-windows...
-- Downloading https://bitbucket.com/multicoreware/x265/get/3.2.tar.gz...
-- Downloading **https://bitbucket.com/multicoreware/x265/get/3.2.tar.gz... Failed. Status: 22;"HTTP response code said error"**
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:175 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_bitbucket.cmake:127 (vcpkg_download_distfile)
  ports/x265/portfile.cmake:3 (vcpkg_from_bitbucket)
  scripts/ports.cmake:94 (include)


Error: Building package x265:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: x265:x86-windows
  Vcpkg version: 2019.09.12-nohash-external

Additionally, attach any relevant sections from the log files above.
```
====================================================================

**Comment by chris-batty** [comment]
My configuration:
System:  Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz   3.50 GHz, 32GB RAM
OS: Microsoft Windows [Version 10.0.19044.1469]    (Windows 10 Pro 21H2)
Country/Regional:   United States / English (US)
VCPKG bundled with:  Microsoft Visual Studio Community 2019 -- Version 16.11.9

**Comment by Thomas1664** [comment]
X265 is normally downloaded from its GitHub repo. Please make sure you are using the latest version of vcpkg:
From your vcpkg folder run `git pull` and then `bootstrap.bat`.

**Comment by Thomas1664** [comment]
> Question 2:
> Should I install (and learn) git, in order to proceed?

Definitely yes!

> Question 1:
If I understand you correctly, that means I need to obtain the x265 package myself; i.e. it is not something VCPKG will do for me?

vcpkg will download the package from GitHub. The reason why this particular port failed to download is that it changed the location from which it will be downloaded to its GitHub repo.

**Comment by chris-batty** [comment]
Thanks, @Thomas1664  !

Q2:
I kinda knew that answer to (Q2) was gonna be Yes...
Ok ... alright ... gonna git with the program.  :-)

Q1:
Right.  I see.  An updated VCPKG will "find it" on GitHub.  
So, there would be nothing else for me to do (beyond updating vcpkg, then re-trying the vcpkg install x265...)
 
- - - - 
 
Ok, I will let you know how it goes.

Thanks again for the super-quick response!

**Comment by JackBoosY** [comment]
> Question 1:
If I understand you correctly, that means I need to obtain the x265 package myself; i.e. it is not something VCPKG will do for me?
Sorry if that sounds stupid. I hope you'll forgive my limited understanding of VCPKG. Just so you know ... I am an experienced C/C++ developer [30+years], but I am new to using automated 3rd party code packaging apps, like VCPKG.
I guess I thought it would be handled automatically like all the other packages I have -- like zlib, sqlite, ffmpeg, etc.
My VCPKG list shows 188 packages installed. They all work just fine in my projects.

vcpkg will automaticly download, build and install the binaries/headers/other publish files. You don't need to manually download the packages, since vcpkg already change the repo from official webset to github, you just need to update vcpkg using `git pull`.

> Right. Since I am using the VCPKG bundled with VS 2019, I will assume it is out of date.

If your bundled vcpkg is out-dated, you should update it.

> Question 2:
Should I install (and learn) git, in order to proceed?

Just a bit: using `git pull` to update vcpkg.

**Comment by chris-batty** [comment]
Thank you @JackBoosY  and @Thomas1664  !

Success!

I have now:
   a) installed git and configured it,
   b) git clone'd the vcpkg,
   c) installed and rebuilt all my packages,
   d) confirmed my existing projects still build, and finally...
   e)  -- TADA! -- successfully installed the x265 package.

Thanks guys, for your awesome response.

From my point of view, this issue can be closed.  :-)

Chris
