### ISSUE TITLE
How do I rebuild a package？Instead of copying DLL file and LIB file from the cache.

### ISSUE THREAD

**Issue by PTA00** [microsoft/vcpkg#22968]
How do I rebuild a package？Instead of copying DLL file and LIB file from the cache.

**Comment by dg0yt** [comment]
`./vcpkg install --no-binarycaching PKG`

**Comment by PTA00** [comment]
> `./vcpkg install --no-binarycaching PKG`

Thank you very much.😊
could you please tell me where it is in the document？

**Comment by dg0yt** [comment]
I don't know. It is even missing from `vcpkg install --help`.

**Comment by PTA00** [comment]
Hope to add to the document.
analogous:
    Delete the binary cache while deleting the package.
