### ISSUE TITLE
OpenCV is bugged in vcpkg when building with Clang

### ISSUE THREAD

**Issue by rodneysnacks** [microsoft/vcpkg#22969]
**Describe the bug**
The find_contours function of OpenCV returns points which are way outside of the bounds of the input image. This happens when installing opencv4 with vcpkg and building the project with Clang-13. This does not happen when building with GCC-10. Furthermore, manually installing OpenCV from source without vcpkg does not display this bug for both Clang-13 and GCC-10. The points seem to be off by a fixed offset, however this seems to change everytime the program is executed. 

**Environment**
- OS: Ubuntu 20.04.3 LTS 64-bit 
- Compiler:  clang version 13.0.1
- vcpkg at commit 7e7dad5fe20cdc085731343e0e197a7ae655555b

**To Reproduce**
main.cpp:
```cpp
#include <iostream>
#include <opencv2/opencv.hpp>

int main(){
    cv::Mat img{200, 200, CV_8U, 0.0};
    cv::Rect rect{50, 50, 100, 100};
    cv::Scalar col{255, 255, 255};
    cv::rectangle(img, rect, col, -1);

    std::vector<std::vector<cv::Point>> contours{};
    std::vector<cv::Vec4i> hierarchy{};
    cv::findContours(img.clone(), contours, hierarchy, cv::RETR_TREE, cv::CHAIN_APPROX_SIMPLE);

    for (const auto &points: contours)
        for (const auto &point: points)
            std::cout << point << std::endl;
    return 0;
}

```

CMakeLists.txt
```
cmake_minimum_required(VERSION 3.22)
project(opencv_bug)

set(CMAKE_CXX_STANDARD 17)

find_package(OpenCV REQUIRED)
include_directories(${OpenCV_INCLUDE_DIRS})
link_directories(${OpenCV_LIB_DIR})

add_executable(opencv_bug main.cpp)
target_link_libraries(opencv_bug ${OpenCV_LIBS})
```

vcpkg.json
```json
{
  "name": "opencv-bug",
  "version-string": "1.0.0-SNAPSHOT",
  "dependencies": [{"name": "opencv4"}]
}
```

Then build with:
- -DCMAKE_BUILD_TYPE=Debug
- -DCMAKE_MAKE_PROGRAM=/usr/bin/ninja
- -DCMAKE_C_COMPILER=/usr/bin/clang-13
- -DCMAKE_CXX_COMPILER=/usr/bin/clang++-13 
- -DCMAKE_TOOLCHAIN_FILE=~/vcpkg/scripts/buildsystems/vcpkg.cmake 
- -G Ninja

**Expected behavior**
find_contours should return points which are inside of the image for both compilers. Specifically, the code snippit should print:
```
[50, 50]
[50, 149]
[149, 149]
[149, 50]
```
However, with clang it is printing points like these:
```
[41437298, 32814]
[41437298, 32913]
[41437397, 32913]
[41437397, 32814]
```

**Additional context**
 Manually passing an offset of (0, 0) does not fix it. Nor does casting the output to different int-types. Also tested with older commits of vcpkg and still present there (431d3810aa9241aed49b14367be417f225d2af5e).

**Comment by JackBoosY** [comment]
cc @cenit

**Comment by cenit** [comment]
I am building opencv using x64-windows-llvm triplet from here https://github.com/Neumann-A/my-vcpkg-triplets right now
@Neumann-A 

i will let you know if i can reproduce errors

**Comment by cenit** [comment]
Also, I'd suggest to use a triplet for x64-linux-llvm instead of manually passing parameters to cmake when building, to have better consistency.
Please write a triplet file and share it here, so that I can test it later on an ubuntu machine

**Comment by cenit** [comment]
it looks like the library built by gcc-10 is not perfectly compatible with a downstream project built with clang-13?
Might it be some missing -fPIC somewhere in a dependency?

Why not defining your own triplet in vcpkg and let it build ports with clang, too? I never mix and match compilers, that might be a problem due to this situation?

**Comment by rodneysnacks** [comment]
Our build server is running Ubuntu, but we have several macOS developers who wanted to use clang on the server as well.  So as I understand, vcpkg will just use whatever compiler the triplet specifies and it doesn't follow the DCMAKE_CXX_COMPILER flag. Which is causing the vcpkg dependencies to be built with gcc, but the rest of the project with clang, is that correct? So to have vcpkg use different compilers or compiler flags I need to define a triplet and pass it to vcpkg. I can try doing that. Still, I wouldn't expect that to change not just the behaviour, but the correctness of the find_contours function of opencv.

**Comment by sfhacker** [comment]
I have been told that vcpkg has a strong tendency to mix toolchains!
@rodneysnacks You could check (or verify) your environment(s) so vcpkg doesn't get confused.
We don't use clang but will try to repro this issue locally.

**Comment by rodneysnacks** [comment]
Was busy last week and forgot to post an update. When vcpkg is also configured to use Clang, it worked without issues.  So the mixing of compilers was the issue. This can be closed as far as I'm concerned.

Sidenote, I used `export CXX=...` to get vcpkg to use Clang. If I want to do this via triplet I should append `set(CMAKE_CXX_COMPILER ...)` to it? Is there a way that is prefered? I kinda like the export, since I don't have to edit any files and I know that each command I execute will use the same compiler.

**Comment by JackBoosY** [comment]
> If I want to do this via triplet I should append set(CMAKE_CXX_COMPILER ...) to it? Is there a way that is prefered?

Yes, you should writer a new triplet.
