### ISSUE TITLE
[Building package fmt:x86-windows] build failure

### ISSUE THREAD

**Issue by qazmx5741** [microsoft/vcpkg#22989]
[install-x64-windows-static-dbg-out.log](https://github.com/microsoft/vcpkg/files/8020249/install-x64-windows-static-dbg-out.log)
**Host Environment**
- OS: Windows
- Compiler: abreast of the times

**To Reproduce**
`./vcpkg install spdlog`

**Failure logs** 
Computing installation plan...
The following packages will be built and installed:
  * fmt[core]:x86-windows -> 8.1.1
    spdlog[core]:x86-windows -> 1.9.2
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x86-windows...
Restored 0 packages from C:\Users\HP\AppData\Local\vcpkg\archives in 154.7 us. Use --debug to see more details.
Starting package 1/2: fmt:x86-windows
Building package fmt[core]:x86-windows...
-- Using cached fmtlib-fmt-8.1.1.tar.gz.
-- Cleaning sources at D:/dev/vcpkg/buildtrees/fmt/src/8.1.1-75ee4647fd.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/dev/vcpkg/downloads/fmtlib-fmt-8.1.1.tar.gz
-- Applying patch fix-write-batch.patch
-- Using source at D:/dev/vcpkg/buildtrees/fmt/src/8.1.1-75ee4647fd.clean
-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:158 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j17
    Working Directory: D:/dev/vcpkg/buildtrees/fmt/x86-windows-dbg
    See logs for more information:
      D:\dev\vcpkg\buildtrees\fmt\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:111 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
  ports/fmt/portfile.cmake:19 (vcpkg_cmake_install)
  scripts/ports.cmake:145 (include)

Error: Building package fmt:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+fmt
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[fmt]+Build+error
including:
  package: fmt[core]:x86-windows -> 8.1.1
    vcpkg-tool version: 2022-02-03-457b0309cefb58fae0dcb2e4c06de9bd7582967f
    vcpkg-scripts version: c7ab9d311 2020-04-20 (1 year, 10 months ago)

Additionally, attach any relevant sections from the log files above.

**Additional context**
I have confirmed that git pull is the latest, and vspkg update also indicates that there is no update available。
Prompt that the file you want to view has been added to the attachment.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Which version of Visual Studio you use?

**Comment by qazmx5741** [comment]
> Thanks for posting this issue. Which version of Visual Studio you use?

VS2019

**Comment by LilyWangLL** [comment]
There are error in your log:
```
[1/4] C:\LLongwillDevelopProducts\VS2013\VC\bin\amd64\cl.exe   /TP -DFMT_LOCALE -ID:\dev\vcpkg\buildtrees\fmt\src\8.1.1-75ee4647fd.clean\include /nologo /DWIN32 /D_WINDOWS /W3  /GR /EHsc /MP  /D_DEBUG /MTd /Z7 /Ob0 /Od /RTC1  -MTd /showIncludes /FoCMakeFiles\fmt.dir\src\os.cc.obj /FdCMakeFiles\fmt.dir\fmt.pdb /FS -c D:\dev\vcpkg\buildtrees\fmt\src\8.1.1-75ee4647fd.clean\src\os.cc
FAILED: CMakeFiles/fmt.dir/src/os.cc.obj 
C:\LLongwillDevelopProducts\VS2013\VC\bin\amd64\cl.exe   /TP -DFMT_LOCALE -ID:\dev\vcpkg\buildtrees\fmt\src\8.1.1-75ee4647fd.clean\include /nologo /DWIN32 /D_WINDOWS /W3  /GR /EHsc /MP  /D_DEBUG /MTd /Z7 /Ob0 /Od /RTC1  -MTd /showIncludes /FoCMakeFiles\fmt.dir\src\os.cc.obj /FdCMakeFiles\fmt.dir\fmt.pdb /FS -c D:\dev\vcpkg\buildtrees\fmt\src\8.1.1-75ee4647fd.cle
```
I saw the vcpkg use `cl.exe` of Visual Studio 2013.

**Comment by qazmx5741** [comment]
> There are error in your log:
> 
> ```
> [1/4] C:\LLongwillDevelopProducts\VS2013\VC\bin\amd64\cl.exe   /TP -DFMT_LOCALE -ID:\dev\vcpkg\buildtrees\fmt\src\8.1.1-75ee4647fd.clean\include /nologo /DWIN32 /D_WINDOWS /W3  /GR /EHsc /MP  /D_DEBUG /MTd /Z7 /Ob0 /Od /RTC1  -MTd /showIncludes /FoCMakeFiles\fmt.dir\src\os.cc.obj /FdCMakeFiles\fmt.dir\fmt.pdb /FS -c D:\dev\vcpkg\buildtrees\fmt\src\8.1.1-75ee4647fd.clean\src\os.cc
> FAILED: CMakeFiles/fmt.dir/src/os.cc.obj 
> C:\LLongwillDevelopProducts\VS2013\VC\bin\amd64\cl.exe   /TP -DFMT_LOCALE -ID:\dev\vcpkg\buildtrees\fmt\src\8.1.1-75ee4647fd.clean\include /nologo /DWIN32 /D_WINDOWS /W3  /GR /EHsc /MP  /D_DEBUG /MTd /Z7 /Ob0 /Od /RTC1  -MTd /showIncludes /FoCMakeFiles\fmt.dir\src\os.cc.obj /FdCMakeFiles\fmt.dir\fmt.pdb /FS -c D:\dev\vcpkg\buildtrees\fmt\src\8.1.1-75ee4647fd.cle
> ```
> 
> I saw the vcpkg use `cl.exe` of Visual Studio 2013.

Do I need to modify the cl.exe program of vcpkg to 2019? I now use both vs2013 and vs2019

**Comment by qazmx5741** [comment]
> > There are error in your log:
> > ```
> > [1/4] C:\LLongwillDevelopProducts\VS2013\VC\bin\amd64\cl.exe   /TP -DFMT_LOCALE -ID:\dev\vcpkg\buildtrees\fmt\src\8.1.1-75ee4647fd.clean\include /nologo /DWIN32 /D_WINDOWS /W3  /GR /EHsc /MP  /D_DEBUG /MTd /Z7 /Ob0 /Od /RTC1  -MTd /showIncludes /FoCMakeFiles\fmt.dir\src\os.cc.obj /FdCMakeFiles\fmt.dir\fmt.pdb /FS -c D:\dev\vcpkg\buildtrees\fmt\src\8.1.1-75ee4647fd.clean\src\os.cc
> > FAILED: CMakeFiles/fmt.dir/src/os.cc.obj 
> > C:\LLongwillDevelopProducts\VS2013\VC\bin\amd64\cl.exe   /TP -DFMT_LOCALE -ID:\dev\vcpkg\buildtrees\fmt\src\8.1.1-75ee4647fd.clean\include /nologo /DWIN32 /D_WINDOWS /W3  /GR /EHsc /MP  /D_DEBUG /MTd /Z7 /Ob0 /Od /RTC1  -MTd /showIncludes /FoCMakeFiles\fmt.dir\src\os.cc.obj /FdCMakeFiles\fmt.dir\fmt.pdb /FS -c D:\dev\vcpkg\buildtrees\fmt\src\8.1.1-75ee4647fd.cle
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I saw the vcpkg use `cl.exe` of Visual Studio 2013.
> 
> Do I need to modify the cl.exe program of vcpkg to 2019? I now use both vs2013 and vs2019

What should I do?

**Comment by LilyWangLL** [comment]
You can set `VCPKG_PLATFORM_TOOLSET` in _VCPKG_ROOT/triplets/Use_triplet.cmake_ like below. V141 is VIsual Studio 2017, V142 is VIsual Studio 2019, V143 is VIsual Studio 2022.
**x64-windows.cmake**
```
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_PLATFORM_TOOLSET v142)
```

**Comment by LilyWangLL** [comment]
Ping @qazmx5741 for response. Does this issue still exist?

**Comment by LilyWangLL** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

**Comment by Ponyets** [comment]
This solves my problem, though I don't know if it works for [qazmx5741](https://github.com/qazmx5741). Thanks.
