### ISSUE TITLE
vcpkg cannot find 'powershell.exe' (MSB3073)

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [microsoft/vcpkg#2299]
[Here](https://ci.appveyor.com/project/dotnetfoundation/openlivewriter/build/0.6.2.301#L258) is during build on AppVeyor.

Note that there is no problem with executing `powershell.exe` right before build (checked [here](https://ci.appveyor.com/project/dotnetfoundation/openlivewriter/build/0.6.2.301#L242), after [this](https://github.com/OpenLiveWriter/OpenLiveWriter/commit/9ee603db1bf69716486dfd095943f87206d482d5) change.

Also note that project does not use vcpkg and last success build was before we (AppVeyor) [added vcpkg](https://github.com/appveyor/ci/issues/1076).

For now problem fixed with [deletion of vcpkg folder](https://github.com/OpenLiveWriter/OpenLiveWriter/commit/636feec6b9cd06611c09717b4c5e0ee31dd17068). But maybe it should be better fix.

cc @jongalloway

**Comment by ras0219-msft** [comment]
Hi @IlyaFinkelshteyn,

Could you try out the branch `appveyor-issue-2299` and see if it fixes the issue?

**Comment by IlyaFinkelshteyn** [comment]
@ras0219-msft  that did not work as is. I was needed to add `System32` to the path. See https://github.com/Microsoft/vcpkg/pull/2309. 

However root cause is that path variable is broken at the point of calling that script. Here is what I see when replacing that command (directly in RDP session) with `echo %path%`. It [looks very short](https://ci.appveyor.com/project/IlyaFinkelshteyn/openlivewriter/build/0.6.2.10#L489):
```
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin;C:\Program Files (x86)\Windows Kits\8.1\bin\x86;;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\tools;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\ide;C:\Program Files (x86)\HTML Help Workshop;;C:\Program Files (x86)\MSBuild\14.0\bin\;C:\Windows\Microsoft.NET\Framework\v4.0.30319\;C:\windows\SysWow64;;;;;
```

I am not sure if **vcpkg** or something within **OpenLiveWriter** changing the `path` variablle. I cannot absolutely exclude that AppVeyor is changing something but this is not probable as we tested `path` before build command started. Also commands like [this](https://github.com/OpenLiveWriter/OpenLiveWriter/blob/master/src/unmanaged/OpenLiveWriter.Ribbon/OpenLiveWriter.Ribbon.vcxproj#L67) would not work if `path` broken before...

@ras0219-msft if it works OK for you with another solution, then maybe this is not vcpkg issue.

CC @jongalloway @willduff

**Comment by NancyLi1013** [comment]
@IlyaFinkelshteyn 
This issue should have been fixed now. Please update vcpkg and try it again.
Please reopen this if it is still a problem for you.
