### ISSUE TITLE
[boost-vcpkg-helpers] Build error

### ISSUE THREAD

**Issue by westshellX** [microsoft/vcpkg#22992]
**Host Environment**
- OS: [Windows/Linux]
- Compiler: VS2019

**To Reproduce**
`./vcpkg install boost-convert`

**Failure logs** 
  package: boost-vcpkg-helpers[core]:x86-windows -> 1.78.0#1
    vcpkg-tool version: 2022-02-03-457b0309cefb58fae0dcb2e4c06de9bd7582967f
    vcpkg-scripts version: a709191a6 2022-02-07 (5 minutes ago)

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by Adela0814** [comment]
@westshellX I can't repro this issue, could you please provide the failure logs?

**Comment by westshellX** [comment]
I solved, and it was my internet problem. Sorry.
















At 2022-02-08 16:34:30, "Mengna Li" ***@***.***> wrote:

@westshellX I can't repro this issue, could you please provide the failure logs?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
