### ISSUE TITLE
Portable Bash not installed

### ISSUE THREAD

**Issue by jdx-john** [microsoft/vcpkg#22996]
On a brand new machine I set up vcpkg and it seemed everything was running smoothly, until package _libiconv_ failed:

> -- Using msys root at F:/git/vcpkg/downloads/tools/msys2/aa5af7b2aa7e90e8
> CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
>     Command failed: F:/git/vcpkg/downloads/tools/msys2/703e5aa15d402568/usr/bin/bash.exe

Checking, many things are missing from this folder:
![image](https://user-images.githubusercontent.com/1654627/152968085-c3108f13-0983-4d21-b128-43e2ae237fa0.png)

However in the download root dir I see all sorts of things which look right:
![image](https://user-images.githubusercontent.com/1654627/152965851-350d97c4-c87e-4c5a-8339-bf7a33dfa647.png)

vcpkg did correctly install other portable things like CMake and PWSH when run for the first time but it seems it didn't do the same for bash, though it knows where it is supposed to be. Is this a glitch in the installer? It's a non-internet machine so I copied across the \downloads dir from our working machine... which is what we normally do and has never caused this problem before. We have a slightly newer version of VS2019 on this box (16.11) 

I have build 200 of the 250 packages as well which is a bit perplexing - I'd expect it to crash and burn right away if there was some problem in the vcpkg install.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Did you check there is bash.exe in _VCPKG_ROOT/downloads/tools/msys2/703e5aa15d402568/usr/bin_? And could you provide the all error log?
![image](https://user-images.githubusercontent.com/94091114/153143295-97c05e42-1356-40f9-9b12-280f387f3c68.png)

**Comment by dg0yt** [comment]
Please also check if you have any other MSYS/MinGW installations in your PATH, e.g. from git. Mixing different MSYS/MinGW runtimes can lead to problems - at runtime, not when extracting the packages. (There is no formal "install" step.)

**Comment by jdx-john** [comment]
@LilyWangLL thanks for the reply. See my screenshot above, the only things in _VCPKG_ROOT/downloads/tools/msys2/703e5aa15d402568/usr/bin_ are 3 folders core_perl, site_perl & vendor_perl. So it's like vcpkg either never tried to install other msys components.
The first time I ran vcpkg it installed cmake, PWSH, ninja and all the rest from installers in \downloads and reported no issues until libiconv (package 300/350!) wanted to use bash... presumably none of my other ports have this dependency.

I've run vcpkg since so I'm not sure I would have logs but the test to reproduce would be, I think:
- disconnect machine from internet
- delete VCPKGROOT\downloads\tools sub-folder
- try to build... 
 
my understanding is everything should re-appear in downloads\tools but I wondered if a port misses specifying it _needs_ bash/MSYS.

I'll do this but it's a machine we're actively using so I'll have to find a quiet time, you are welcome to test or wait for my reply.
As a workaround I could copy that whole VCPKG_ROOT/downloads/tools/msys2/703e5aa15d402568/usr/bin subfolder from another machine but the whole point is I want to avoid that.

**Comment by LilyWangLL** [comment]
@jdx-john Thanks for your reply. Could you provide the log file: _VCPKG_ROOT/buildtrees/libiconv/stdout-x64-windows.log_?

**Comment by jdx-john** [comment]
I'd subsequently got a workaround so I could use the machine but what I tested today was to delete VCPKG_ROOT\downloads\tools and then explicitly build libiconv using default triplet. This PC had no internet access.

I was expecting it to fail but actually, it _did_ install MSYS e.g.:

```
F:\git\vcpkg>vcpkg install libiconv
Computing installation plan...
A suitable version of cmake was not found (required v3.21.1). Downloading portable cmake v3.21.1...
Extracting cmake...
A suitable version of 7zip was not found (required v19.0.0). Downloading portable 7zip v19.0.0...
Extracting 7zip...
The following packages will be built and installed:
    libiconv[core]:x86-windows -> 1.16#11
Detecting compiler hash for triplet x86-windows...
A suitable version of powershell-core was not found (required v7.1.3). Downloading portable powershell-core v7.1.3...
Extracting powershell-core...
Could not locate cached archive: C:\Users\Administrator\AppData\Local\vcpkg\archives\74\7413e45a7903444a3867a1d99e0c84c3cb5f6956700c6041e205365f5c831508.zip
Starting package 1/1: libiconv:x86-windows
Building package libiconv[core]:x86-windows...
-- Downloading https://ftp.gnu.org/gnu/libiconv/libiconv-1.16.tar.gz;https://www.mirrorservice.org/sites/ftp.gnu.org/gnu/libiconv/libiconv-1.16.tar.gz -> libiconv-1.16.tar.gz...
-- Cleaning sources at F:/git/vcpkg/buildtrees/libiconv/src/1.16-b0c41d3469.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source F:/git/vcpkg/downloads/libiconv-1.16.tar.gz
-- Applying patch 0002-Config-for-MSVC.patch
-- Applying patch 0003-Add-export.patch
-- Applying patch 0004-ModuleFileName.patch
-- Using source at F:/git/vcpkg/buildtrees/libiconv/src/1.16-b0c41d3469.clean
-- Found external ninja('1.10.2').
-- Getting CMake variables for x86-windows
-- Downloading https://repo.msys2.org/msys/x86_64/bash-4.4.023-2-x86_64.pkg.tar.xz;https://www2.futureware.at/~nickoe/msys2-mirror/msys/x86_64/bash-4.4.023-2-x86_64.pkg.tar.xz;https://mirror.yandex.ru/mirrors/msys2/msys/x86_64/bash-4.4.023-2-x86_64.pkg.tar.xz;https://mirrors.tuna.tsinghua.edu.cn/msys2/msys/x86_64/bash-4.4.023-2-x86_64.pkg.tar.xz;https://mirrors.ustc.edu.cn/msys2/msys/x86_64/bash-4.4.023-2-x86_64.pkg.tar.xz;https://mirror.bit.edu.cn/msys2/msys/x86_64/bash-4.4.023-2-x86_64.pkg.tar.xz;https://mirror.selfnet.de/msys2/msys/x86_64/bash-4.4.023-2-x86_64.pkg.tar.xz;https://mirrors.sjtug.sjtu.edu.cn/msys2/msys/x86_64/bash-4.4.023-2-x86_64.pkg.tar.xz -> msys-bash-4.4.023-2-x86_64.pkg.tar.xz...
```

So now I'm confused what went wrong the first time! The main difference is I don't explicitly build _libiconv_, it's a dependency of a package we do use... any idea how I can find which ports have a dependency on _libiconv_ to test that scenario?

I also don't want to delete my entire build (it takes a long time!) - can you remind me how to get a specific port to rebuild? I can never recall if it's somewhere in _buildtree_ or _installed_ I can remove a specific port so vcpkg will rebuild it?

It's possible this was a one-off but it seems more likely there's a cause so I want to try and reproduce.

**Comment by sfhacker** [comment]
A dumb question: is bash a dependency and/or requirement to build libiconv?

**Comment by LilyWangLL** [comment]
@jdx-john Thanks for your reply. Did you use latest VCPKG? Or did you run command `git pull` before you install port? I saw your tools folder is _VCPKG_ROOT/downloads/tools/msys2/703e5aa15d402568_, but latest folder is _VCPKG_ROOT/downloads/tools/msys2/803521c5733336c9_
![image](https://user-images.githubusercontent.com/94091114/153531612-f627b31f-3017-44cd-8f42-885d5e47d7ee.png)

**Comment by jdx-john** [comment]
I finally got round to re-testing this on another clean Windows install, similarly on an offline PC. I can report that this time it worked perfectly, _msys2_ was fully installed as expected. I'm not sure if it was because I ran my command prompt as administrator this time, or it was a one-time glitch the first time round, but it seems there is no bug.

Phew ;)
