### ISSUE TITLE
[eigen3] Eigen is not found by a CMake find_package(Eigen3)

### ISSUE THREAD

**Issue by traversaro** [Microsoft/vcpkg#230]
The Eigen library installed by vcpkg is not found by a CMake `find_package(Eigen3)`.

Before version 3.3 (vcpkg is currently installing 3.2.10) Eigen was installing a file named `signature_of_eigen3_matrix_library` in the `include` directory, and this file was then used by the official [`FindEigen3.cmake`](https://bitbucket.org/eigen/eigen/src/24abf9a98b5342d5e07701ee2da69741ed7949f1/cmake/FindEigen3.cmake?at=default&fileviewer=file-view-default) to find the right location in which the Eigen header were installed. 

The `signature_of_eigen3_matrix_library` file is not installed because the installation procedure provided by the official build system are ignored by the port introduced in https://github.com/Microsoft/vcpkg/pull/26 . However this may be a good thing, as having a random non-include file in `${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include` may be brittle. 

The best solution could be to wait for Eigen 3.3 that should be released shortly and switch to use the official build solution that installs a `Eigen3Config.cmake` file following CMake standards. In that case we need to check if the file is actually [relocatable](https://cmake.org/cmake/help/v3.3/manual/cmake-packages.7.html#id19), and eventually patch it.

**Comment by traversaro** [comment]
Thinking more about this, it still make sense to install `signature_of_eigen3_matrix_library` in `${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include`, as many projects copy pasted the `FindEigen3.cmake` file before this PR : https://bitbucket.org/eigen/eigen/pull-requests/213 , and so they will ignore any existing `Eigen3Config.cmake` .

**Comment by ras0219-msft** [comment]
I completely agree, fundamentally we do need a working solution at the end of the day. Thanks for the detailed write-up yet again; I fixed the `eigen3` port to deploy the `signature_of_eigen3_matrix_library` file and tested it using the old official `FindEigen3.cmake` you linked above.

**Comment by traversaro** [comment]
Thanks a lot for the quick fix. 👍
