### ISSUE TITLE
[openssl] Build error

### ISSUE THREAD

**Issue by pettengillb** [microsoft/vcpkg#23008]
**Host Environment**
- OS: Windows 10 (remote debugging to the raspberry pi)
- Compiler: gcc version 10.3.1 

**To Reproduce**
`./vcpkg vcpkg install curlpp:arm-linux`

**Failure logs** 
Error: Building package openssl:arm-linux failed with: BUILD_FAILED

**Additional context**
I'm trying to install curlpp (on the host windows 10 machine) for remote debugging on the raspberry pi (from VS on Windows 10).   

I seem to have gotten vcpkg past the curl portion after some errors by adding the following to CMAKELISTS.txt:
set(CMAKE_C_COMPILER "C:/gcc-arm-toolchain/bin/arm-none-linux-gnueabihf-gcc.exe")
set(CMAKE_CXX_COMPILER "C:/gcc-arm-toolchain/bin/arm-none-linux-gnueabihf-gcc.exe")
)

However when it gets to the openssl portion of the install the openssl\config-arm-linux-out.log is giving the error: "No CMAKE_C_COMPILER could be found."

I've tried adding the following CC variable to the windows system environment variables:
CC=C:/gcc-arm-toolchain/bin/arm-none-linux-gnueabihf-gcc.exe

(also tried CC=C:\MinGW\bin\gcc.exe incase it's looking for a host compiler)
But I get the same error.

Thanks in advance.
  
[config-arm-linux-out.log](https://github.com/microsoft/vcpkg/files/8030461/config-arm-linux-out.log)

**Comment by JackBoosY** [comment]
You should use mingW triplet instead of arm-linux.
