### ISSUE TITLE
CI: Just run doc related jobs if only docs have changed

### ISSUE THREAD

**Issue by Thomas1664** [microsoft/vcpkg#23019]
**Is your feature request related to a problem? Please describe.**
I filed a PR that touches only docs. However, CI jobs for all platforms have started. 1 hour later, only one of them finished - the others are still queued. 

**Proposed solution**
Only start CI jobs if code files were updated and not for doc files.

**Comment by dg0yt** [comment]
The CI also checks docs. The finished job took 33 second, and so should the others. There is just no free agent.

**Comment by Thomas1664** [comment]
> The CI also checks docs. The finished job took 33 second, and so should the others. There is just no free agent.

Are all these jobs on different OSs really necessary? Would it be possible to run only doc related checks in this case? Do docs checks depend on a certain OS? I don't want to wait hours until an agent is available just for changes in the docs. 
I don't have a problem that jobs take 30 seconds each. I have a problem with waiting until checks finally run.

**Comment by Thomas1664** [comment]
Now that I had to edit the script files CI builds 922 ports. This is kind of ridiculous because again, I only touched the docs!

**Comment by LilyWangLL** [comment]
Thanks for posting this issue, This can't be controled by VCPKG, this controled by CI pipeline.

**Comment by LilyWangLL** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
