### ISSUE TITLE
[curl] Could not find a configuration file for package "CURL" that is compatible with requested version "".

### ISSUE THREAD

**Issue by SamuelMarks** [microsoft/vcpkg#23016]
**Is your feature request related to a problem? Please describe.**
MSVC

Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30139 for x64
vcpkg @ d15470bb6464a3bb0ce3d98d118190cfd5189080

```
find_package(CURL CONFIG REQUIRED)
```

**Proposed solution**
Install to work without version specification required

**Describe alternatives you've considered**
[`FindCurlCustom.cmake`](https://github.com/offscale/libacquire/blob/master/cmake/FindCurlCustom.cmake)

**Additional context**
```
The package curl provides CMake targets:

    find_package(CURL CONFIG REQUIRED)
    target_link_libraries(main PRIVATE CURL::libcurl)

-- Running vcpkg install - done
CMake Error at cmake-build-debug/vcpkg_installed/x64-windows/share/curl/vcpkg-cmake-wrapper.cmake:11 (_find_package):
  Could not find a configuration file for package "CURL" that is compatible
  with requested version "".
```

**Comment by FrankXie05** [comment]
@SamuelMarks  Thanks for posting this issue, The problem may be because MSVC is arch x64 arch vcpkg is arch x86 by default,
you can call cmake with `-DVCPKG_TARGET_TRIPLET=x64-windows`, see #9290. :)

**Comment by FrankXie05** [comment]
@SamuelMarks Is still work for this issue? Please reply me if the problem still exist and I will reopen it.
