### ISSUE TITLE
[jasper] Build error

### ISSUE THREAD

**Issue by BanKeTang** [microsoft/vcpkg#23026]
**Host Environment**
- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**
`./vcpkg install xxxx`

**Failure logs** 
-Cut and paste the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by BanKeTang** [comment]
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/8038479/install-x64-windows-dbg-out.log)

**Comment by BanKeTang** [comment]
package: jasper[core,opengl]:x64-windows -> 2.0.33#3
    vcpkg-tool version: 2022-02-03-457b0309cefb58fae0dcb2e4c06de9bd7582967f
    vcpkg-scripts version: 47c570174 2022-02-09 (8 hours ago)

**Comment by JonLiu1993** [comment]
@BanKeTang ,Thanks for posting this issue, Could you please provide your Visual Studio version and windows SDK version?

**Comment by BanKeTang** [comment]
Visual Studio 2019, Windows SDK 10.0

**Comment by JonLiu1993** [comment]
@BanKeTang ,What language pack are you using? is it english?

**Comment by BanKeTang** [comment]
English

**Comment by JonLiu1993** [comment]
@BanKeTang ,What is the specific version of your Windows SDK? If it is lower, I suggest you upgrade it and reinstall it.

![Capture](https://user-images.githubusercontent.com/63675417/153349324-bbd7eb94-6c15-4481-980b-c2b574006013.PNG)

**Comment by BanKeTang** [comment]
After updating to10.0.18362.0, it works, thank you for your reply!
