### ISSUE TITLE
How can I get the boost libraries (for example) to compile with certain compiler options?

### ISSUE THREAD

**Issue by juandent** [microsoft/vcpkg#2302]
Hi,
I need my boost libraries built with /std:c++17. How I can get that specific compilation done using vcpkg since only triplets are allowed to be specified (no compiler options are)?

Regards
Juan Dent

**Comment by MikeGitb** [comment]
Does any of the boost libraries generate abi-incompatible code under the c++17 switch or why is this necessary?
I think the only thing you can do is to either hack  the build files and or create a custom triplet.

**Comment by JackBoosY** [comment]
Like @MikeGitb said. You need to:
1. create a custom triplet in _vcpkg/triplets/_.
2. copy the code from the file you want to the triplet.
3. add custom macro with cmake.
