### ISSUE TITLE
vcpkg does not accept "null" as license in the manifest

### ISSUE THREAD

**Issue by chausner** [microsoft/vcpkg#23038]
**Describe the bug**
https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/manifest-files.md#license claims that `null` is a valid option for the `license` metadata field:
> The license of the port. This is an [SPDX license expression](https://spdx.dev/ids/#how), or null for proprietary licenses and other licenses for which one should "just read the copyright file" (e.g., Qt).

However, when I set the license field to `null` for port `osg`, vcpkg fails with the error message
> Error: Couldn't load port `osg`.

**Environment**
- OS: Windows
- Compiler: revision

**To Reproduce**
1. Add the attribute `"license": null,` to `ports\osg\vcpkg.json`.
2. Run `.\vcpkg x-add-version osg --overwrite-version`

**Expected behavior**
vcpkg should correctly parse the port manifest.

**Failure logs** 

**Additional context**

**Comment by autoantwort** [comment]
1. `git pull`
2. `./bootstrap-vcpkg.bat`

**Comment by chausner** [comment]
@autoantwort Thanks for the hint, I was using a fairly recent version of vcpkg but apparently one that was not recent enough. ;)
