### ISSUE TITLE
bzip2 fails to compile

### ISSUE THREAD

**Issue by henrikse55** [Microsoft/vcpkg#2304]
bzip2 fails to compile even when running PowerShell as admin.
CMake aren't being detected either.

`
PS D:\vcpkg> .\vcpkg.exe install boost
The following packages will be built and installed:
    boost:x86-windows
  * bzip2:x86-windows
  * zlib:x86-windows
Additional packages (*) will be installed to complete this operation.
Starting package 1/3: zlib:x86-windows
Building package zlib:x86-windows...
A suitable version of cmake was not found (required v3.10.0). Downloading portable cmake v3.10.0...
A suitable version of git was not found (required v2.15.0). Downloading portable git v2.15.0...
-- CURRENT_INSTALLED_DIR=D:/vcpkg/installed/x86-windows
-- DOWNLOADS=D:/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=D:/vcpkg/packages/zlib_x86-windows
-- CURRENT_BUILDTREES_DIR=D:/vcpkg/buildtrees/zlib
-- CURRENT_PORT_DIR=D:/vcpkg/ports/zlib/.
-- Downloading http://www.zlib.net/zlib-1.2.11.tar.gz...
-- Downloading http://www.zlib.net/zlib-1.2.11.tar.gz... OK
-- Testing integrity of downloaded file...
-- Testing integrity of downloaded file... OK
-- Extracting done
-- Applying patch D:/vcpkg/ports/zlib/cmake_dont_build_more_than_needed.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch D:/vcpkg/ports/zlib/cmake_dont_build_more_than_needed.patch done
-- Downloading https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip...
-- Downloading https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip... OK
-- Testing integrity of downloaded file...
-- Testing integrity of downloaded file... OK
-- Configuring x86-windows-rel
-- Configuring x86-windows-rel done
-- Configuring x86-windows-dbg
-- Configuring x86-windows-dbg done
-- Build x86-windows-rel
-- Build x86-windows-rel done
-- Build x86-windows-dbg
-- Build x86-windows-dbg done
-- Installing: D:/vcpkg/packages/zlib_x86-windows/share/zlib/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package zlib:x86-windows... done
Installing package zlib:x86-windows...
Installing package zlib:x86-windows... done
Elapsed time for package zlib:x86-windows: 2.351 min
Starting package 2/3: bzip2:x86-windows
Building package bzip2:x86-windows...
-- CURRENT_INSTALLED_DIR=D:/vcpkg/installed/x86-windows
-- DOWNLOADS=D:/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=D:/vcpkg/packages/bzip2_x86-windows
-- CURRENT_BUILDTREES_DIR=D:/vcpkg/buildtrees/bzip2
-- CURRENT_PORT_DIR=D:/vcpkg/ports/bzip2/.
-- Downloading http://www.bzip.org/1.0.6/bzip2-1.0.6.tar.gz...
-- Downloading http://www.bzip.org/1.0.6/bzip2-1.0.6.tar.gz... OK
-- Testing integrity of downloaded file...
-- Testing integrity of downloaded file... OK
-- Extracting source D:/vcpkg/downloads/bzip2-1.0.6.tar.gz
-- Extracting done
-- Applying patch D:/vcpkg/ports/bzip2/fix-import-export-macros.patch
-- Applying patch D:/vcpkg/ports/bzip2/fix-import-export-macros.patch done
-- Configuring x86-windows-rel
CMake Error at D:/vcpkg/scripts/cmake/vcpkg_execute_required_process.cmake:44 (message):
    Command failed: D:/vcpkg/downloads/cmake-3.10.0-win32-x86/bin/cmake.exe;D:/vcpkg/buildtrees/bzip2/src/bzip2-1.0.6;-DBUILD_SHARED_LIBS=ON;-DCMAKE_CXX_FLAGS= /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP ;-DCMAKE_C_FLAGS= /DWIN32 /D_WINDOWS /W3 /utf-8 /MP ;-DVCPKG_TARGET_TRIPLET=x86-windows;-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON;-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE;-DCMAKE_VERBOSE_MAKEFILE=ON;-DVCPKG_APPLOCAL_DEPS=OFF;-DCMAKE_TOOLCHAIN_FILE=D:/vcpkg/scripts/buildsystems/vcpkg.cmake;-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON;-DCMAKE_CXX_FLAGS_RELEASE=/MD /O2 /Oi /Gy /DNDEBUG /Z7 ;-DCMAKE_C_FLAGS_RELEASE=/MD /O2 /Oi /Gy /DNDEBUG /Z7 ;-DCMAKE_SHARED_LINKER_FLAGS_RELEASE=/DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF ;-DCMAKE_EXE_LINKER_FLAGS_RELEASE=/DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF ;-G;Ninja;-DCMAKE_BUILD_TYPE=Release;-DCMAKE_INSTALL_PREFIX=D:/vcpkg/packages/bzip2_x86-windows
    Working Directory: D:/vcpkg/buildtrees/bzip2/x86-windows-rel
    See logs for more information:
      D:\vcpkg\buildtrees\bzip2\config-x86-windows-rel-out.log
      D:\vcpkg\buildtrees\bzip2\config-x86-windows-rel-err.log

Call Stack (most recent call first):
  D:/vcpkg/scripts/cmake/vcpkg_configure_cmake.cmake:205 (vcpkg_execute_required_process)
  D:/vcpkg/ports/bzip2/portfile.cmake:18 (vcpkg_configure_cmake)
  D:/vcpkg/scripts/ports.cmake:72 (include)

Error: Building package bzip2:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: bzip2:x86-windows
  Vcpkg version: 0.0.100-2017-12-04-216f7137b9736d68e698f32154966ea68c7b98db

Additionally, attach any relevant sections from the log files above.
[config-x86-windows-rel-err.log](https://github.com/Microsoft/vcpkg/files/1532398/config-x86-windows-rel-err.log)
`

**Comment by ZhilkinSerg** [comment]
#### C:\Projects\vcpkg\buildtrees\bzip2\x86-windows-test\CMakeFiles\CMakeError.log

```
The output was:
1
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 08.01.2019 2:02:57.
Project "C:\Projects\vcpkg\buildtrees\bzip2\x86-windows-test\CMakeFiles\3.12.4\CompilerIdCXX\CompilerIdCXX.vcxproj" on node 1 (default targets).
PrepareForBuild:
  Creating directory "Debug\".
  Creating directory "Debug\CompilerIdCXX.tlog\".
InitializeBuildStatus:
  Creating "Debug\CompilerIdCXX.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
VcpkgTripletSelection:
  Using triplet "x86-windows" from "c:\Projects\vcpkg\installed\x86-windows\"
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x86\CL.exe /c /I"c:\Projects\vcpkg\installed\x86-windows\include" /nologo /W0 /WX- /diagnostics:classic /Od /Oy- /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\" /Fd"Debug\vc141.pdb" /Gd /TP /analyze- /FC /errorReport:queue CMakeCXXCompilerId.cpp
  CMakeCXXCompilerId.cpp
Link:
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x86\link.exe /ERRORREPORT:QUEUE /OUT:".\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO /LIBPATH:"c:\Projects\vcpkg\installed\x86-windows\debug\lib" /LIBPATH:"c:\Projects\vcpkg\installed\x86-windows\debug\lib\manual-link" kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib "c:\Projects\vcpkg\installed\x86-windows\debug\lib\*.lib" /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\CompilerIdCXX.lib" /MACHINE:X86 /SAFESEH Debug\CMakeCXXCompilerId.obj
LINK : fatal error LNK1181: cannot open input file 'uuid.lib' [C:\Projects\vcpkg\buildtrees\bzip2\x86-windows-test\CMakeFiles\3.12.4\CompilerIdCXX\CompilerIdCXX.vcxproj]
Done Building Project "C:\Projects\vcpkg\buildtrees\bzip2\x86-windows-test\CMakeFiles\3.12.4\CompilerIdCXX\CompilerIdCXX.vcxproj" (default targets) -- FAILED.

Build FAILED.

"C:\Projects\vcpkg\buildtrees\bzip2\x86-windows-test\CMakeFiles\3.12.4\CompilerIdCXX\CompilerIdCXX.vcxproj" (default target) (1) ->
(Link target) -> 
  LINK : fatal error LNK1181: cannot open input file 'uuid.lib' [C:\Projects\vcpkg\buildtrees\bzip2\x86-windows-test\CMakeFiles\3.12.4\CompilerIdCXX\CompilerIdCXX.vcxproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.49
```

I guess something is missing from my VS install - I've made some changes to what was installed recently and removed `v140 toolset`, so that could be the case.

![image](https://user-images.githubusercontent.com/16213433/50798641-1fff8f00-12ea-11e9-8645-180da3a8d0cc.png)

**Comment by LarryIII** [comment]
@henrikse55 @ZhilkinSerg Thanks for your feedback. I installed bzip2:x86-windows successfully. Please open a new issue if this is still a problem for you.
