### ISSUE TITLE
[New Port Request] Anti Grain Geometry - Highest quality 2D rasterizer

### ISSUE THREAD

**Issue by jakerdy** [microsoft/vcpkg#23054]
##  agg: Anti Grain Geometry 

This is great and very high quality 2d library, which rises antialiasing level up to 256 samples per pixel. Probably this is the highest possible quality in 2d rasterization which could be achieved with open source libraries right now.  Also it pretty portable, and could be easily built with modern compilers (i tried vc2019, vc2022, gcc 9, clang 11). 

**Source repository URL:** https://github.com/ghaerr/agg-2.6

It would be nice if sources will be spitted into separate packages each for specific feature like:
- `agg-core` (the core lib itself)
- `agg-platform-support` (various tools for opening system windows on different platforms)
- `agg-gui` (AGG GUI features)
- `agg-examples` (examples. It may depends on all AGG packages, because they are cover most of the lib apis)
- `agg-freetype` (freetype support, should depends on already existing freetype port)
- `agg-2d` (2d canvas which makes using AGG pretty simple and convenient)
- `gpc` (not really part of AGG, but still it's pretty useful and robust polygon clipper, btw, there is version 2.33 which is published under MIT, and probably it would be better to use this version and not that one from original AGG repo. https://github.com/rickbrew/GeneralPolygonClipper)

**Comment by jakerdy** [comment]
Well, maybe there is no need in `gpc` package, because:
- there is package `polyclipping`, which has better performance and quality
- it's not clear about gpc license, It states as MIT, but author him self didn't say any word about is it legit or not...

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
