### ISSUE TITLE
[New Port Request] libadwaita

### ISSUE THREAD

**Issue by nlogozzo** [microsoft/vcpkg#23050]
Library name: libadwaita

Library description: Building blocks for modern adaptive GNOME applications

Source repository URL: https://gitlab.gnome.org/GNOME/libadwaita/

Project homepage (if different from the source repository): https://gnome.pages.gitlab.gnome.org/libadwaita/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
- Requires GTK4 (which already exists in this repo)

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
