### ISSUE TITLE
Unable to install any lib 

### ISSUE THREAD

**Issue by mayankgaur019** [Microsoft/vcpkg#2305]
I am trying to install any lib using vcpkg but it fails.
for example: installing zlib giving this error 

Error: Building package zlib:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zlib:x86-windows
  Vcpkg version: 0.0.99-2017-12-01-34d8c77d35089484f66d80299dc6f8303a994a84

on  running \vcpkg update getting this 

C:\Users\Desktop\vcpkg>.\vcpkg update
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating..

**Comment by ras0219-msft** [comment]
Thanks for posting this issue! Could you attach the log files listed slightly above that error message?

**Comment by mayankgaur019** [comment]
CMake Error at CMakeLists.txt:4 (project):
  Failed to run MSBuild command:

    C:/Program Files/Microsoft Visual Studio/2017/Community/MSBuild/15.0/Bin/MSBuild.exe

  to get the value of VCTargetsPath:

    Microsoft (R) Build Engine version 15.3.409.57025 for .NET Framework
    Copyright (C) Microsoft Corporation. All rights reserved.
    
    Build started 12/7/2017 11:28:47 PM.
    Project "C:\Users\gaur\Desktop\microsoft-vcpkg\vcpkg\buildtrees\zlib\x86-windows-rel\CMakeFiles\3.10.0\VCTargetsPath.vcxproj" on node 1 (default targets).
    PrepareForBuild:
      Creating directory "Debug\".
      Creating directory "Debug\VCTargetsPath.tlog\".
    InitializeBuildStatus:
      Creating "Debug\VCTargetsPath.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
    FinalizeBuildStatus:
      Deleting file "Debug\VCTargetsPath.tlog\unsuccessfulbuild".
      Touching "Debug\VCTargetsPath.tlog\VCTargetsPath.lastbuildstate".
    Done Building Project "C:\Users\gaur\Desktop\microsoft-vcpkg\vcpkg\buildtrees\zlib\x86-windows-rel\CMakeFiles\3.10.0\VCTargetsPath.vcxproj" (default targets).
    
    Build succeeded.
        0 Warning(s)
        0 Error(s)
    
    Time Elapsed 00:00:03.98

**Comment by mayankgaur019** [comment]
this is the error log

**Comment by wangli28** [comment]
Thanks for posting this issue. Please open a new issue if this is still a problem for you.
