### ISSUE TITLE
pybind11 links against wrong Python library when PYBIND11_FINDPYTHON is present

### ISSUE THREAD

**Issue by SunBlack** [microsoft/vcpkg#23052]
**Describe the bug**

In case you are using `pybind11` with `PYBIND11_FINDPYTHON`, the debug build is failing with `LINK : fatal error LNK1104: cannot open file 'python310.lib'`.

**Environment**
- OS: Windows
- Compiler: MSVC 2022

**To Reproduce**
1. `./vcpkg install pybind11`
2. Using following code:

`CMakeLists.txt`
```CMake
cmake_minimum_required(VERSION 3.14...3.22)
project(test)

set(PYBIND11_FINDPYTHON ON)
find_package(pybind11 2.6 CONFIG REQUIRED)

add_executable(${PROJECT_NAME}
	main.cpp
)

target_link_libraries(${PROJECT_NAME}
	PRIVATE
		pybind11::embed
)
```

`main.cpp`
```cpp
#include <pybind11/embed.h>

int main(int argc, char** argv)
{
	pybind11::scoped_interpreter guard{};
	return 0;
}
```

**Expected behavior**

Linker should succeed.

**Additional context**

  | Without vcpkg | With vcpkg
-- | -- | --
With `PYBIND11_FINDPYTHON` | Build succeeded | `cannot open file 'python310.lib'`
Without `PYBIND11_FINDPYTHON` | Build succeeded | Build succeeded

As the debug build works when not using vcpkg even when `PYBIND11_FINDPYTHON` is `ON` it looks like an vcpkg issue for me

**Comment by Hoikas** [comment]
This issue will occur if you consume pybind11 outside of vcpkg, IME. I think this should be reported to upstream.

**Comment by SunBlack** [comment]
> This issue will occur if you consume pybind11 outside of vcpkg, IME.

I don't think it used an version from outside. See CMake log:
```
Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19044.
The C compiler identification is MSVC 19.30.30709.0
The CXX compiler identification is MSVC 19.30.30709.0
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.30.30705/bin/Hostx64/x64/cl.exe - skipped
Detecting C compile features
Detecting C compile features - done
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.30.30705/bin/Hostx64/x64/cl.exe - skipped
Detecting CXX compile features
Detecting CXX compile features - done
Found Python: D:/vcpkg/installed/x64-windows-msvc2022/tools/python3/python.exe (found version "3.10.1") found components: Interpreter Development Development.Module Development.Embed 
Performing Test HAS_MSVC_GL_LTCG
Performing Test HAS_MSVC_GL_LTCG - Success
Found pybind11: D:/vcpkg/installed/x64-windows-msvc2022/include (found version "2.9.0")
Configuring done
Generating done
```

**Comment by reder2000** [comment]
The problem is pybind11 somewhere does
#undef _DEBUG
and python autolinks (pyconfig.h) wrongly.
There's a comment here https://github.com/python/cpython/pull/19740 to request for non autoliking
Line 264 could be patched to 
#       if !defined(Py_BUILD_CORE) && !defined(Py_BUILD_CORE_BUILTIN) && !!defined(PY_NO_LINK_LIB)
and with
add_compile_definitions(PY_NO_LINK_LIB)
in your CMakeLists.txt everything builds ok

**Comment by FrankXie05** [comment]
Related upstream issue https://github.com/pybind/pybind11/issues/3403.
At present, we can temporarily disable autolinks of python to prevent conflicts with upstream specified links. 😔

**Comment by SunBlack** [comment]
@reder2000 If you want to debug this problem, you can also call cmake with `--trace` or `--trace-expand` to understand, what happens there (the issues has to low priority for me to spend much time into this).

**Comment by reder2000** [comment]
> @reder2000 If you want to debug this problem, you can also call cmake with `--trace` or `--trace-expand` to understand, what happens there (the issues has to low priority for me to spend much time into this).

There's no problem with cmake, thanks. I have memories of python being unusable in debug mode anyways, because even if you build a debug python, you'd need to build pandas, numpy or whatever else you use that way.
In any case, a successful debug build is better than a failed one, even if modules can't be used.

**Comment by Dariusz1989** [comment]
+1 from me too. Massive pain. Will try to build pybind11 myself from the source. But otherwise, it looks like booth pybind11 and Boost are linking against wrong libs while using vcpkg.

**Comment by reder2000** [comment]
I ended up overriding settings for RelWithDebInfo so that msvc does not inline or optimize anything, and Debug ignores python projects. 
Things like :
```
set_property(TARGET my_python_module
             PROPERTY EXCLUDE_FROM_DEFAULT_BUILD_DEBUG TRUE)

```
and
```
add_compile_options("$<$<AND:$<CXX_COMPILER_ID:MSVC>,$<CONFIG:RELWITHDEBINFO>>:/Od>")
add_compile_options("$<$<AND:$<CXX_COMPILER_ID:MSVC>,$<CONFIG:RELWITHDEBINFO>>:/Ob0>")
```
Does the job.

**Comment by Dariusz1989** [comment]
> I ended up overriding settings for RelWithDebInfo so that msvc does not inline or optimize anything, and Debug ignores python projects. Things like :
> 
> ```
> set_property(TARGET my_python_module
>              PROPERTY EXCLUDE_FROM_DEFAULT_BUILD_DEBUG TRUE)
> ```
> 
> and
> 
> ```
> add_compile_options("$<$<AND:$<CXX_COMPILER_ID:MSVC>,$<CONFIG:RELWITHDEBINFO>>:/Od>")
> add_compile_options("$<$<AND:$<CXX_COMPILER_ID:MSVC>,$<CONFIG:RELWITHDEBINFO>>:/Ob0>")
> ```
> 
> Does the job.

That add_compile_options looks a bit... "ODD"... is that c orrect? I've never seen that before...
Also, so you are able to debug your python/pyd module with this? Or even import it? I cant even import my pyd modules. They just give me crazy error.

**Comment by reder2000** [comment]
"generator expressions" are a bit surprising.

Obviously you're still on debug, which is a dead end. Select (add config in cmake settings) RelWithDebInfo.

**Comment by Dariusz1989** [comment]
> "generator expressions" are a bit surprising.
> 
> Obviously you're still on debug, which is a dead end. Select (add config in cmake settings) RelWithDebInfo.

Wait so debug is not working? That sounds odd... 
Yesterday I realized that Clion does not support debugging python/pyds! 
And that vs apparently can... > https://learn.microsoft.com/en-us/visualstudio/python/debugging-mixed-mode-c-cpp-python-in-visual-studio?view=vs-2022

So far I was "almost" able to break point in to. I just had source code miss match which I have to figure out how to fix.

**Comment by reder2000** [comment]
Debug is not working (not directly, certainly tiring workarounds). Even though, you'd need to compile anything you use (pandas, and so on) in debug as well.
Simplest thing in VS is to fill debug session properties 
```
if (MSVC)
    find_program (my_python python NO_CACHE)
        if ("${my_python}" STREQUAL "my_python-NOTFOUND")
        MESSAGE("python found on command line. Using ${Python_EXECUTABLE} instead")
        set(my_python ${Python_EXECUTABLE})
        endif()
    message("${PROJECT_NAME}")
    set_target_properties(${PROJECT_NAME} PROPERTIES VS_DEBUGGER_COMMAND "${my_python}")
    set_target_properties(${PROJECT_NAME} PROPERTIES VS_DEBUGGER_COMMAND_ARGUMENTS "${CMAKE_CURRENT_SOURCE_DIR}/demo_trend.py")
    set_target_properties(${PROJECT_NAME} PROPERTIES VS_DEBUGGER_WORKING_DIRECTORY "$<TARGET_FILE_DIR:${PROJECT_NAME}>")
    set_target_properties(${PROJECT_NAME} PROPERTIES VS_DEBUGGER_ENVIRONMENT "PYTHONPATH=$<TARGET_FILE_DIR:${PROJECT_NAME}>")
endif(MSVC)
```
For Clion one can attach itself to a python process (that's all I found).

**Comment by Dariusz1989** [comment]
> Debug is not working (not directly, certainly tiring workarounds). Even though, you'd need to compile anything you use (pandas, and so on) in debug as well. Simplest thing in VS is to fill debug session properties
> 
> ```
> if (MSVC)
>     find_program (my_python python NO_CACHE)
>         if ("${my_python}" STREQUAL "my_python-NOTFOUND")
>         MESSAGE("python found on command line. Using ${Python_EXECUTABLE} instead")
>         set(my_python ${Python_EXECUTABLE})
>         endif()
>     message("${PROJECT_NAME}")
>     set_target_properties(${PROJECT_NAME} PROPERTIES VS_DEBUGGER_COMMAND "${my_python}")
>     set_target_properties(${PROJECT_NAME} PROPERTIES VS_DEBUGGER_COMMAND_ARGUMENTS "${CMAKE_CURRENT_SOURCE_DIR}/demo_trend.py")
>     set_target_properties(${PROJECT_NAME} PROPERTIES VS_DEBUGGER_WORKING_DIRECTORY "$<TARGET_FILE_DIR:${PROJECT_NAME}>")
>     set_target_properties(${PROJECT_NAME} PROPERTIES VS_DEBUGGER_ENVIRONMENT "PYTHONPATH=$<TARGET_FILE_DIR:${PROJECT_NAME}>")
> endif(MSVC)
> ```
> 
> For Clion one can attach itself to a python process (that's all I found).

Hey
Thanks for ping!
I got some exciting news !!!!
I got debug working!!!!! WOHOOOO!!!

Ok so
cmake_examples for pybind11> https://github.com/pybind/cmake_example
cmakelist.txt tweak >
```
cmake_minimum_required(VERSION 3.4...3.18)
project(cmake_example)

add_compile_options(/Zi /MDd /Od)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /Zi /Od")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} /DEBUG")

add_subdirectory(pybind11)
pybind11_add_module(cmake_example src/main.cpp)

# EXAMPLE_VERSION_INFO is defined by setup.py and passed into the C++ code as a
# define (VERSION_INFO) here.
add_definitions(-DVERSION_INFO=3.10)

target_compile_definitions(cmake_example
                           PRIVATE VERSION_INFO=${EXAMPLE_VERSION_INFO})

```
build as debug in vs code 2022
Run my application
run python
import sys
sys.path.append("/path/to/folder/dll/"
import module

the module will break point after you attach to process ! WOHOOOOO!!!! I got debug vars/etc/etc!!! :DDD

**Comment by jeanga** [comment]
FWIW, I was able to "manually" fix this issue for my module with these steps: https://github.com/pybind/pybind11/issues/3403#issuecomment-1515786458
HTH
