### ISSUE TITLE
vcpkg install drogon fail!

### ISSUE THREAD

**Issue by 1647606255** [microsoft/vcpkg#23051]
vcpkg install drogon[ctl,mysql]  fail. I can not find the error log, detail as screenshot.
 I install drogon sucess in other pc,but fail in my notebook. I can  not find the reason,so  need your help.

![(O3T@WB_G@(175)$SX3FJKW](https://user-images.githubusercontent.com/49872873/153594671-c930ee25-ec94-4ef3-8e10-0ba3fd5eef03.png)
.

**Comment by 1647606255** [comment]
[install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/8049777/install-x86-windows-dbg-out.log)

install-x86-windows-dbg-err.log file is empty

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. You need add `set(VCPKG_PLATFORM_TOOLSET v142)` to triplet file _VCPKG_ROOT/triplets/Install_triplet.file_ which you need.

**Comment by 1647606255** [comment]
> Thanks for posting this issue. You need add `set(VCPKG_PLATFORM_TOOLSET v142)` to triplet file _VCPKG_ROOT/triplets/Install_triplet.file_ which you need.

I do it your way, than it it show this  error:The following VS instances were excluded because the English language pack is unavailable
![XD3@AFFUBS5E2 3@E)6CD10](https://user-images.githubusercontent.com/49872873/154021565-ffcaf669-7803-439c-8fa2-101800ce4b12.png).

installing the English language pack  can solve all of my proplem.

thanks  a lot.

**Comment by LilyWangLL** [comment]
This issue has been resolved, so I am closing this issue for now.
