### ISSUE TITLE
vcpkg crashes if invoked inside `vcpkg edit`

### ISSUE THREAD

**Issue by ras0219-msft** [microsoft/vcpkg#23065]
**Describe the bug**
If using the terminal inside a vscode instance launched via `vcpkg edit <port>`, `vcpkg install` runs but any attempt to download a file crashes. This is due to nesting limits in vcpkg (`vcpkg install` sees itself as a recursive invocation and so sets `$X_VCPKG_RECURSIVE_DATA` to `poison`).

**Comment by MonicaLiu0311** [comment]
It still reproduces in the latest vcpkg:
![VSCodeTerminal](https://github.com/microsoft/vcpkg/assets/110024546/dd850289-f71b-4ff4-bfb9-fa24fcc859f4)

```
PS E:\vcpkg02> ./vcpkg version
vcpkg package management program version 2023-04-07-bedcba5172f5e4b91caac660ab7afe92c27a9895

See LICENSE.txt for license information.
```

**Comment by jimwang118** [comment]
This issue has been fixed in the latest version of vcpkg.
![Image](https://github.com/user-attachments/assets/cef351ed-5fad-4936-8c60-f93b7bac4be7)
