### ISSUE TITLE
[openssl] Build error

### ISSUE THREAD

**Issue by xengine-qyt** [microsoft/vcpkg#23078]
**Host Environment**
- OS:Windows
- Compiler: revision

**To Reproduce**
`vcpkg.exe upgrade --no-dry-run`

**
Building package openssl[core]:x64-windows...
-- Using cached openssl-1.1.1m.tar.gz.
-- Cleaning sources at D:/vcpkg/buildtrees/openssl/src/openssl-1-8c9323690c.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/vcpkg/downloads/openssl-1.1.1m.tar.gz
-- Using source at D:/vcpkg/buildtrees/openssl/src/openssl-1-8c9323690c.clean
-- Copying openssl release source files...
-- Copying openssl release source files... done
-- Configure x64-windows-rel
-- Configure x64-windows-rel done
-- Build x64-windows-rel
-- Build x64-windows-rel done
-- Copying openssl debug source files...
-- Copying openssl debug source files... done
-- Configure x64-windows-dbg
-- Configure x64-windows-dbg done
-- Build x64-windows-dbg
-- Build x64-windows-dbg done
-- Installing: D:/vcpkg/packages/openssl_x64-windows/share/openssl/copyright
-- Fixing pkgconfig file: D:/vcpkg/packages/openssl_x64-windows/lib/pkgconfig/libcrypto.pc
-- Fixing pkgconfig file: D:/vcpkg/packages/openssl_x64-windows/lib/pkgconfig/libssl.pc
-- Fixing pkgconfig file: D:/vcpkg/packages/openssl_x64-windows/lib/pkgconfig/openssl.pc
-- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst;https://www2.futureware.at/~nickoe/msys2-mirror/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst;https://mirror.yandex.ru/mirrors/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst;https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst;https://mirrors.ustc.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst;https://mirror.bit.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst;https://mirror.selfnet.de/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst;https://mirrors.sjtug.sjtu.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst -> msys-mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst...
-- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst;https://www2.futureware.at/~nickoe/msys2-mirror/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst;https://mirror.yandex.ru/mirrors/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst;https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst;https://mirrors.ustc.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst;https://mirror.bit.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst;https://mirror.selfnet.de/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst;https://mirrors.sjtug.sjtu.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst -> msys-mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:128 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" -E tar xzf D:/vcpkg/downloads/msys-mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst
    Working Directory: D:/vcpkg/downloads/tools/msys2/9a1ec3f33446b195.tmp
    Error code: 系统找不到指定的文件。
    See logs for more information:

Call Stack (most recent call first):
  scripts/cmake/vcpkg_acquire_msys.cmake:551 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_find_acquire_program.cmake:551 (vcpkg_acquire_msys)
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:198 (vcpkg_find_acquire_program)
  ports/openssl/install-pc-files.cmake:32 (vcpkg_fixup_pkgconfig)
  ports/openssl/portfile.cmake:22 (include)
  scripts/ports.cmake:145 (include)

Error: Building package openssl:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+openssl
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[openssl]+Build+error
including:
  package: openssl[core]:x64-windows -> 1.1.1m#2
    vcpkg-tool version: 2021-12-09-724cea8b33cbf06c645f5095fa29773697da9761
    vcpkg-scripts version: 8dbd66f5a 2022-02-11 (2 days ago)

Additionally, attach any relevant sections from the log files above.
**

**Comment by xengine-qyt** [comment]
git pull 
open console running commands
vcpkg update 
vcpkt upgrade

The upgrade command has no effect after the upgrade fails?

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Could you please remove cmake which installed by yourself and try again?
`"C:/Program Files/CMake/bin/cmake.exe"`

**Comment by xengine-qyt** [comment]
i am reinstall vcpkg that's ok now ...thanks
