### ISSUE TITLE
Invalid characters in control file -> Better error message needed

### ISSUE THREAD

**Issue by Neumann-A** [Microsoft/vcpkg#2307]
So I am currently playing with the modular qt branch and got and error message like this:
`vcpkg install qt5:x64-windows`
`Contains invalid characters. Only alphanumeric lowercase ASCII characters and dashes are allowed`

What I know that it has most likely to do with invalid characters in a control file. My Problem is I would like to know which file has the invalid characters as my control file für qt5 has the following dependencies:

`Build-Depends: qt5base,qt5modularscripts, qt5charts, qt5datavis3d, qt5declarative, qt5gamepad, qt5imageformats, qt5multimedia, qt5scxml, qt5serialport, qt5speech, qt5svg, qt5tools, qt5virtualkeyboard, qt5websockets, qt53d, qt5winextras, qt5xmlpatterns, qt5serialbus, qt5quickcontrols, qt5quickcontrols2, qt5remoteobjects, qt5script, qt5sensor`

so going through them all will take some time and a better error message would save time.

**Comment by alexkaratarakis** [comment]
Yes, good suggestion!
I added more info to the error message, try with latest master.

**Comment by Neumann-A** [comment]
Thanks it is better but still not good enough:

Error now:
`C:\Sources\Extern\vcpkg2>vcpkg install qt5:x64-windows`
`Invalid package: qt5declarative`
`Contains invalid characters. Only alphanumeric lowercase ASCII characters and dashes are allowed`

Control file:
`Source: qt5declarative`
`Version: 5.9.3-1`
`Description: Qt5 Declarative (Quick 2) Module. Includes QtQuick, QtQuickParticles, QtQuickWidgets, QtQml, and QtPacketProtocol.` (no line break in file)
`Build-Depends: qt5modularscripts, qt5base`

I can't see an error so I am still in need of a better error message (line number / position would be nice)
(Although I dont understand the error at all. According to its git history I just changed the version number)

If you want to test the error message I am working on this [branch](https://github.com/Neumann-A/vcpkg/tree/qt5_modular)

**Comment by Neumann-A** [comment]
forgot to mention that 
`vcpkg install qt5declarative`
works fine 

Yeah so it seems like not the CONTROL file of qt5declarative has the error but another file which uses it as a build dependency. 

Found it: qt3d had an extra white space behind qt5declarative. 
-> Yeah, current error message is a bit misleading ;). Please improve it.

**Comment by alexkaratarakis** [comment]
Right, there is a distinction between invalid package names and invalid dependencies. They were passing through the same check but I changed them to be separate now. The new error message would be:
```
Invalid dependency [qt5declarative] in package [qt3d]
Contains invalid characters. Only alphanumeric lowercase ASCII characters and dashes are allowed
```

Thanks!
