### ISSUE TITLE
Split NuGet packaging into "primary" & "redist" packages

### ISSUE THREAD

**Issue by forderud** [microsoft/vcpkg#2308]
I really like the `export --nuget` feature. However, the feature would be even better if it could package header/lib files and dll/pdb files into separate NuGet packages.

Desired packaging:
* `PackageName.nupkg`: Primary nuget package containing headers, lib-files & other resources needed for _building_. This package depends on PackageName.redist.nupkg.
* `PackageName.redist.nupkg`: Secondary nuget package containing DLL & PDBs (if present) required to _run_ the SW.

Example package that depends on a "redist" counterpart: https://www.nuget.org/packages/sdl2. It's also possible to move PDBs into a separate "symbols" package, as done by coapp (http://coapp.org/tutorials/autopackage-guide.html). However, that is not important to me.

One advantage with this division is that only "redist" packages are needed for SW deployment. It's also sufficient to distribute "redist" packages for "internal" transitive nuget dependencies.

**Comment by ras0219-msft** [comment]
Thanks for the feature suggestion!

Could you go into more detail about what you mean by "SW deployment"? How would you distribute software using these "redist" packages in a way that's reasonably installable?

**Comment by forderud** [comment]
My organization uses a series of Wix projects for creating MSI installers for our SW. These projects pull in relevant NuGet "redist" packages and use them as input for creating the installers.

Makes sense?

**Comment by forderud** [comment]
Concrete proposal for new command-line arguments to be used in conjunction with `export --nuget`:
* `--redist` - package run-time binaries (DLLs) in a separate "redist" package.
* `--symbols` - package debugging symbols (PDBs) in a separate "symbols" package.

Symbol files will be packaged in the "redist" package if `--symbols` is not specified.

**Comment by OfekShilon** [comment]
Split or not - collecting PDBs and distributing to developers is essential.  It is also a very typical form of distributing Nuget packages.
@ras0219-msft  Can you please update if it's anywhere on the roadmap?   Thanks.

**Comment by NancyLi1013** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen.
