### ISSUE TITLE
[wxwidgets] Build error

### ISSUE THREAD

**Issue by fishnet37222** [microsoft/vcpkg#23094]
**Host Environment**
- OS: Windows 10
- Compiler: Visual Studio 2022

**To Reproduce**

1. Clone the repository located at [https://github.com/fishnet37222/FNDice.git](https://github.com/fishnet37222/FNDice.git).
2. Open the solution in the cloned repository in Visual Studio 2022.
3. Build the solution.

**Failure logs** 
```
1>-- Building x64-windows-rel
1>CMake Error at scripts/cmake/vcpkg_copy_tool_dependencies.cmake:52 (message):
1>  Could not find PowerShell Core; please open an issue to report this.
1>Call Stack (most recent call first):
1>  scripts/cmake/vcpkg_copy_tools.cmake:82 (vcpkg_copy_tool_dependencies)
1>  ports/wxwidgets/portfile.cmake:70 (vcpkg_copy_tools)
1>  scripts/ports.cmake:145 (include)
1>
1>
1>EXEC : error : Building package wxwidgets:x64-windows failed with: BUILD_FAILED

```
**Additional context**
After getting the above error the first time, I issued a `git pull` command in the vcpkg root folder followed by a `vcpkg update` command.  The error did not go away after those commands were issued.

The package builds without any errors when I issue a `vcpkg install wxwidgets` command outside of Visual Studio.

I have another computer with Windows 11 installed and the error does not occur on that computer.

**Comment by FrankXie05** [comment]
Duplicated of https://github.com/microsoft/vcpkg/issues/15681.

**Comment by fishnet37222** [comment]
I was taking a closer look at the issue this was linked to, and I noticed that #15681 only occurs when PowerShell Core is installed from the Microsoft Store.  I did not install PowerShell Core from the Microsoft Store.  I downloaded the MSI from the PowerShell GitHub releases page and installed it that way.  So, is this really a duplicate of 15681?

**Comment by fishnet37222** [comment]
It turns out this is a duplicate after all.  I don't remember installing it, but when I was looking at the profiles available in Windows Terminal, I saw "Powershell Preview (msix)" listed.  After uninstalling that version of Powershell Preview, the issue no longer occurs.  I am closing this issue.
