### ISSUE TITLE
[cgal] Fix CGAL_DATA_DIR CMake warning

### ISSUE THREAD

**Issue by acgetchell** [microsoft/vcpkg#23098]
****

**Is your feature request related to a problem? Please describe.**
Using CGAL produces the CMake warning:

```
CMake Warning at vcpkg_installed/arm64-osx/share/cgal/CGALConfig.cmake:92 (message):
  CGAL_DATA_DIR cannot be deduced, set the variable CGAL_DATA_DIR to set the
  default value of CGAL::data_file_path()
Call Stack (most recent call first):
  /Users/adam/projects/vcpkg/scripts/buildsystems/vcpkg.cmake:793 (_find_package)
  CMakeLists.txt:72 (find_package)
```

**Proposed solution**
Fix the port so that this works:

https://github.com/CGAL/cgal/blob/master/Installation/lib/cmake/CGAL/CGALConfig.cmake#L75

**Describe alternatives you've considered**
Setting this manually, however, that doesn't fit well within the vcpkg port philosophy heretofore, which is that installing a package should not usually require environment variables to be set.

**Additional context**
In CLion, this causes error messages in CMake builds
![Screen Shot 2022-02-14 at 9 52 03 PM](https://user-images.githubusercontent.com/434849/154000749-1a30eedf-60f7-47bd-a5fe-7741cfcf2558.png)
.

**Comment by dg0yt** [comment]
> Setting this manually, however, that doesn't fit well within the vcpkg port philosophy heretofore, which is that installing a package should not usually require environment variables to be set.

This idea usually doesn't work well for data directories, because there are two layers of relocation:
-  After building a package like GDAL, before it is used in another package.
- After building another package and deploing it to the user.

With exported config, vcpkg could (somewhat) cover the first relocation, but not the second.

**Comment by JackBoosY** [comment]
I think `CGAL_DATA_DIR` should be defined in the user side.

**Comment by paulonasc7** [comment]
I'm not quite sure if I understood what's the fix for this. I'm trying to build a project in VS code with CMake, but I keep getting the following warning.

```
CMake Warning at /opt/homebrew/lib/cmake/CGAL/CGALConfig.cmake:92 (message):CGAL_DATA_DIR cannot be 
deduced, set the variable CGAL_DATA_DIR to set the default value of CGAL::data_file_path()
```

**Comment by JackBoosY** [comment]
@paulonasc7 I think you should pass `-DCGAL_DATA_DIR=...` to the cmake command line since it may contains other path outside vcpkg.

**Comment by jwbullard** [comment]
Sorry for the dumb question, but what is the meaning of CGAL_DATA_DIR?  I'm happy to set it, but what is it?  The path to the CGAL working directory, the location of the installed include files, or something else?

**Comment by aji-geo** [comment]
> 

same question

**Comment by aji-geo** [comment]
The same question.... @jwbullard

**Comment by dg0yt** [comment]
> what is the meaning of CGAL_DATA_DIR?

As a CMake variable, definition or environment variable, its value is used by `CGAL::data_file_path`. Maybe this is normally used only for demos, examples, tests and benchmarks. In any case, it is not a path which vcpkg could burn into binary files.
https://github.com/CGAL/cgal/blob/master/Documentation/doc/Documentation/CGAL/config.h 
https://github.com/CGAL/cgal/wiki/Directory-Structure-for-Packages#shared-data-directory
https://stackoverflow.com/questions/71713439/what-is-cgaldata-file-path

**Comment by JackBoosY** [comment]
I'm not familiar with cgal, but in CGALConfig.cmake:
```cmake
#set CGAL_DATA_DIR
if (NOT CGAL_DATA_DIR)
  if(DEFINED ENV{CGAL_DATA_DIR})
    set(CGAL_DATA_DIR $ENV{CGAL_DATA_DIR})
  else()
    if (EXISTS "${CGAL_ROOT}/Data/data")
      set(CGAL_DATA_DIR "${CGAL_ROOT}/Data/data")
    else()
      if (EXISTS "${CGAL_ROOT}/data")
        set(CGAL_DATA_DIR "${CGAL_ROOT}/data")
      else()
        if (EXISTS "${CMAKE_SOURCE_DIR}/../data")
          set(CGAL_DATA_DIR "${CMAKE_SOURCE_DIR}/../data")
        else()
          if (EXISTS "${CMAKE_SOURCE_DIR}/../../data")
              set(CGAL_DATA_DIR "${CMAKE_SOURCE_DIR}/../../data")
          else()
            message(WARNING "CGAL_DATA_DIR cannot be deduced, set the variable CGAL_DATA_DIR to set the default value of CGAL::data_file_path()")
          endif()
        endif()
      endif()
    endif()
  endif()
endif()

if(NOT TARGET CGAL::Data)
  add_library(CGAL::Data INTERFACE IMPORTED GLOBAL)
  if ( NOT "${CGAL_DATA_DIR}" STREQUAL "" )
    set_target_properties(CGAL::Data PROPERTIES
      INTERFACE_COMPILE_DEFINITIONS "CGAL_DATA_DIR=\"${CGAL_DATA_DIR}\"")
  endif()
endif()
```


And I found the _Data/data_ folder will only be installed in cmake file `cgal_create_release_with_cmake.cmake`, which isn't used in the main cmake frame.

**Comment by JackBoosY** [comment]
Can anyone test my PR https://github.com/microsoft/vcpkg/pull/24112?

Thanks.
