### ISSUE TITLE
[pcl] Build error

### ISSUE THREAD

**Issue by imindude** [microsoft/vcpkg#23097]
**Host Environment**
- OS: Windows 11
- Compiler: VS Community 2022

**To Reproduce**
./vcpkg install pcl:x64-windows

**Failure logs** 
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:158 (message):
    Command failed: C:/vcpkg/downloads/tools/cmake-3.21.1-windows/cmake-3.21.1-windows-i386/bin/cmake.exe --build . --config Release --target install -- -v -j13
    Working Directory: C:/vcpkg/buildtrees/pcl/x64-windows-rel
    See logs for more information:
      C:\vcpkg\buildtrees\pcl\install-x64-windows-rel-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:111 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
  ports/pcl/portfile.cmake:82 (vcpkg_cmake_install)
  scripts/ports.cmake:145 (include)

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.
[install-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/8065426/install-x64-windows-rel-out.log)

**Comment by Cheney-W** [comment]
Thanks for posting this issue. This is a bug of Visual Studio.
Closed this due to duplicate with https://github.com/microsoft/vcpkg/issues/19561, please pay attention of https://github.com/microsoft/vcpkg/issues/19561.
