### ISSUE TITLE
[vtk] build failure

### ISSUE THREAD

**Issue by Eric-JH** [microsoft/vcpkg#23103]
**Host Environment**
- OS: Windows10
- Compiler: MSVC2022

**To Reproduce**
`./vcpkg install vtk:x64-windows`

**Failure logs** 
D:\vcpkg>vcpkg install vtk:x64-windows
Computing installation plan...
The following packages will be built and installed:
    vtk[core]:x64-windows -> 9.0.3-pv5.9.1#6
Detecting compiler hash for triplet x64-windows...
-- Automatically setting HTTP(S)_PROXY environment variables to 127.0.0.1:1080
Restored 0 packages from C:\Users\26327\AppData\Local\vcpkg\archives in 179.2 us. Use --debug to see more details.
Starting package 1/1: vtk:x64-windows
Building package vtk[core]:x64-windows...
-- Using cached Kitware-VTK-2959413ff190bc6e3ff40f5b6c1342edd2e5233f.tar.gz.
-- Cleaning sources at D:/vcpkg/buildtrees/vtk/src/edd2e5233f-d2586c767d.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/vcpkg/downloads/Kitware-VTK-2959413ff190bc6e3ff40f5b6c1342edd2e5233f.tar.gz
-- Applying patch FindLZMA.patch
-- Applying patch FindLZ4.patch
-- Applying patch Findproj.patch
-- Applying patch pegtl.patch
-- Applying patch pythonwrapper.patch
-- Applying patch NoUndefDebug.patch
-- Applying patch python_debug.patch
-- Applying patch fix-using-hdf5.patch
-- Applying patch FindExpat.patch
-- Applying patch vtkm.patch
-- Applying patch 1f00a0c9.patch
-- Applying patch 156fb524.patch
-- Applying patch d107698a.patch
-- Applying patch fix-gdal.patch
-- Applying patch missing-limits.patch
-- Applying patch UseProj5Api.patch
-- Using source at D:/vcpkg/buildtrees/vtk/src/edd2e5233f-d2586c767d.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
CMake Warning at installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:487 (message):
  The following variables are not used in CMakeLists.txt:

      VTK_MODULE_ENABLE_VTK_PythonContext2D

  Please recheck them and remove the unnecessary options from the
  `vcpkg_cmake_configure` call.

  If these options should still be passed for whatever reason, please use the
  `MAYBE_UNUSED_VARIABLES` argument.
Call Stack (most recent call first):
  ports/vtk/portfile.cmake:150 (vcpkg_cmake_configure)
  scripts/ports.cmake:142 (include)

-- Building x64-windows-dbg

**Additional context**
The install process was stucked during Building x64-windows-dbg. No other error was reported.

**Comment by FrankXie05** [comment]
@Eric-JH Thanks for posting this issue, Is there an error log?

**Comment by Eric-JH** [comment]
Sry. Maybe the issue attributes to my device. It took 34mins to build and I interrupted the process.  Now it is built successfully.
