### ISSUE TITLE
cmake can not find package installed by vcpkg

### ISSUE THREAD

**Issue by insar-dev** [microsoft/vcpkg#23107]
**Describe the bug**

I have installed boost by vckpg.

when I develop linux app by visual studio + cmake + vcpkg, cmake can not find boost package.
![image](https://user-images.githubusercontent.com/1676595/154065592-99ebb7c8-dba2-4c18-8364-6d9a2191504c.png)

if i use vscode  + cmake + vcpkg in linux, cmake can find it. 

**Environment**
- OS: [e.g. Windows/Linux etc...] windows
- Compiler: vs2022 + cmake3.22.2 + vcpkg

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Do you install which component of boost? And could you please remove CMake which not installed by VCPKG and try again? CMake 3.22.0 will be fixed in PR https://github.com/microsoft/vcpkg/pull/22985.

**Comment by insar-dev** [comment]
boost version is 1.78.
why vscode cmake can find it ?

**Comment by LilyWangLL** [comment]
Sorry I am late. Now cmake in VCPKG has been updated to version 3.22.2. Does this issue still exist?

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
