### ISSUE TITLE
Version specirfied in ports/package/vcpkg.json not used

### ISSUE THREAD

**Issue by Scotty1701** [microsoft/vcpkg#23117]
**Describe the bug**
When a version for a dependency is specified in the vcpkg/ports/package/vcpkg.json file, this version is not used when using vcpkg to install that package. 
For example, the `azure-security-keyvault-certificates-cpp` package has the following lines in its vcpkg.json file:
```
"dependencies": [
    {
      "name": "azure-core-cpp",
      "default-features": false,
      "version>=": "1.2.0"
    },
```
thus, I would expect that vcpkg would install version 1.2.0 of `azure=core-cpp`, however, when installing vcpkg will build and install the most recent version, in this case 1.3.1:
```
PS C:\dev\vcpkg> vcpkg --feature-flags=versions --triplet=x64-windows install azure-security-keyvault-certificates-cpp
Computing installation plan...
The following packages will be built and installed:
  * azure-core-cpp[core,curl,http,winhttp]:x64-windows -> 1.3.1
```
**Environment**
- OS: Windows x64
- Compiler: MSVC2019
- Vcpkg version: 2021-12-09-724cea8b33cbf06c645f5095fa29773697da9761

**To Reproduce**
1. `vcpkg --feature-flags=versions --triplet=x64-windows install azure-security-keyvault-certificates-cpp`

**Expected behavior**
Vcpkg install the version of the dependency specified in vcpkg.json

**Additional context**
The motivation for this is trying to build cartographer and cartographer_ros version 1.0.0 on windows. Using protobuf 3.18.0 (the most recent version in vcpkg) leads to linking errors due to changes in the protobuf compiler. If there is a way to specify/change how the vcpkg port of cartographer compiles the .proto files then that could be a workaround.

**Comment by Thomas1664** [comment]
> thus, I would expect that vcpkg would install version 1.2.0 of `azure=core-cpp`, however, when installing vcpkg will build and install the most recent version, in this case 1.3.1:

I don't see the problem here. `"version>=": "1.2.0"` means version `1.2.0` or higher and `1.3.1` is in fact higher. 

However, we can update `cartographer` to 2.0.0 and/ or update `protobuf` to 3.19.4. 
Additionally, can you provide the logs when you try to install `cartographer`?

**Comment by Scotty1701** [comment]
Hi Thomas, thanks for the quick reply. 
> I don't see the problem here. `"version>=": "1.2.0"` means version `1.2.0` or higher and `1.3.1` is in fact higher.  

From [vcpkg/versioning.md](https://github.com/microsoft/vcpkg/blob/master/docs/users/versioning.md):
>Note: Vcpkg selects the lowest version that matches all constraints, so a less-than constraint is not required.

I read this as meaning that in my example, version `1.2.0` would be used as the lowest version. Are constraints for dependency versions specified in other locations?  Furthermore, trying to force it to use a different version with the `overrides` field in the `vcpkg.json` still results in the newest version being used. Returning to `cartographer` with the following `vcpkg/ports/cartographer/vcpkg.json`:
```
{
  "name": "cartographer",
  "version": "1.0.0",
  "port-version": 5,
  "description": "Google 2D & 3D SLAM package",
  "homepage": "https://github.com/googlecartographer/cartographer",
  "dependencies": [
    "boost-iostreams",
    "cairo",
    {
      "name": "ceres",
      "features": [
        "suitesparse"
      ]
    },
    "gflags",
    "glog",
    "gtest",
    "lua",
    {
      "name": "protobuf",
      "version>=": "3.4.0"
    },
    {
      "name": "vcpkg-cmake",
      "host": true
    },
    {
      "name": "vcpkg-cmake-config",
      "host": true
    }
  ],
  "builtin-baseline": "d40f2a4a5d51e28b322c5c63771af3e8de302c45",
  "overrides": [
    { "name": "protobuf", "version": "3.4.0" }
  ]
}
```
console output:
```
C:\dev\vcpkg>vcpkg install cartographer:x64-windows
Computing installation plan...
The following packages will be built and installed:
    cartographer[core]:x64-windows -> 1.0.0#5
  * protobuf[core]:x64-windows -> 3.18.0#1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Restored 0 packages from C:\Users\isaac.poplin.adm\AppData\Local\vcpkg\archives in 857.2 us. Use --debug to see more details.
Starting package 1/2: protobuf:x64-windows
Building package protobuf[core]:x64-windows...
-- Using cached protocolbuffers-protobuf-v3.18.0.tar.gz.
-- Extracting source C:/dev/vcpkg/downloads/protocolbuffers-protobuf-v3.18.0.tar.gz
-- Applying patch fix-static-build.patch
-- Applying patch fix-default-proto-file-path.patch
-- Applying patch fix-uwp-build.patch
-- Applying patch fix-mingw-build.patch
-- Using source at C:/dev/vcpkg/buildtrees/protobuf/src/v3.18.0-296107ec8b.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Fixing pkgconfig file: C:/dev/vcpkg/packages/protobuf_x64-windows/lib/pkgconfig/protobuf-lite.pc
-- Fixing pkgconfig file: C:/dev/vcpkg/packages/protobuf_x64-windows/lib/pkgconfig/protobuf.pc
-- Using cached msys-mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst.
-- Using msys root at C:/dev/vcpkg/downloads/tools/msys2/9a1ec3f33446b195
-- Fixing pkgconfig file: C:/dev/vcpkg/packages/protobuf_x64-windows/debug/lib/pkgconfig/protobuf-lite.pc
-- Fixing pkgconfig file: C:/dev/vcpkg/packages/protobuf_x64-windows/debug/lib/pkgconfig/protobuf.pc
-- Installing: C:/dev/vcpkg/packages/protobuf_x64-windows/share/protobuf/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\isaac.poplin.adm\AppData\Local\vcpkg\archives\3d\3df2258e7af4a4311899f19166575ca7273535016f6ec00af20669b09d1e3212.zip
Installing package protobuf[core]:x64-windows...
Elapsed time for package protobuf:x64-windows: 1.187 min
Starting package 2/2: cartographer:x64-windows
Building package cartographer[core]:x64-windows...
-- Note: cartographer only supports static library linkage. Building static library.
-- Using cached googlecartographer-cartographer-1.0.0.tar.gz.
-- Extracting source C:/dev/vcpkg/downloads/googlecartographer-cartographer-1.0.0.tar.gz
-- Applying patch fix-find-packages.patch
-- Applying patch fix-build-error.patch
-- Applying patch fix-cmake-location.patch
-- Using source at C:/dev/vcpkg/buildtrees/cartographer/src/1.0.0-fedf76091e.clean
-- Configuring x64-windows
CMake Warning at installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:487 (message):
  The following variables are not used in CMakeLists.txt:

      GFLAGS_PREFER_EXPORTED_GFLAGS_CMAKE_CONFIGURATION
      GLOG_PREFER_EXPORTED_GLOG_CMAKE_CONFIGURATION
      gtest_disable_pthreads

  Please recheck them and remove the unnecessary options from the
  `vcpkg_cmake_configure` call.

  If these options should still be passed for whatever reason, please use the
  `MAYBE_UNUSED_VARIABLES` argument.
Call Stack (most recent call first):
  ports/cartographer/portfile.cmake:15 (vcpkg_cmake_configure)
  scripts/ports.cmake:145 (include)


-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: C:/dev/vcpkg/packages/cartographer_x64-windows/share/cartographer/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\isaac.poplin.adm\AppData\Local\vcpkg\archives\fe\fe3ab36c10b2ebb70107faa93b82e1cfa904201ca5d8aa9ea2d5d36e03376593.zip
Installing package cartographer[core]:x64-windows...
Elapsed time for package cartographer:x64-windows: 2.305 min

Total elapsed time: 3.523 min

The package cartographer provides CMake targets:

    find_package(cartographer CONFIG REQUIRED)
    target_link_libraries(main PRIVATE cartographer)
```
Note how `protobuf 3.18.0#0` is used despite specifying version `3.4.0`. 


> However, we can update `cartographer` to 2.0.0 and/ or update `protobuf` to 3.19.4. Additionally, can you provide the logs when you try to install `cartographer`?

Which logs would you like? I see 16 log files in `vcpkg/buildtrees/cartographer`, with 8 of them being empty. Are these the logs you're referring to?

Cartographer by itself installs fine, it's when I try to use it to build `cartographer-ros` on the `ros2-dashing-1.0.0` branch that I get linking errors due to different definitions of symbols created by `protobuf`. 

My problem doesn't stem from them being too old, it stems from the version of protobuf used by vcpkg to build cartographer being too new. Is there any way to set the versions of dependencies for packages that exist as vcpkg ports? I just want to install `cartographer` the way vcpkg does, *except* I want to use `protobuf 3.4.0`.

**Comment by Thomas1664** [comment]
First of all, you can't overwrite the version directly in a ports' `vcpkg.json` file. To use a specific version you need to...

1. Uninstall protobuf: `vcpkg remove protobuf:x64-windows`
2. Remove protobuf from cache: Delete `C:/dev/vcpkg/downloads/protocolbuffers-protobuf-v3.18.0.tar.gz`
3. Refer to this issue to install a specific version of a port: https://github.com/microsoft/vcpkg/issues/21357#issuecomment-968325176

**Comment by Thomas1664** [comment]
Seems like that version of the port had an error. Please try the fixed version by replacing `"version": "3.4.0"` with `"version-string": "3.4.0-2"` in your `overrides`.

**Comment by Scotty1701** [comment]
Initially, `3.4.0-2` failed with the same error, as did `3.4.0-1`.
However, after deleting `C:\dev\vcpkg\buildtrees\protobuf`, I get a different error:
```
D:\Documents\protobuf>vcpkg --feature-flags=versions --triplet=x64-windows install
Detecting compiler hash for triplet x64-windows...
The following packages will be built and installed:
    protobuf[core]:x64-windows -> 3.4.0-2 -- C:\dev\vcpkg\buildtrees\versioning_\versions\protobuf\b6fd0beef65a76c6efc90b702e61d150f25b62d3
  * zlib[core]:x64-windows -> 1.2.11#13 -- C:\dev\vcpkg\buildtrees\versioning_\versions\zlib\92cfe30c807d343c6359d272242f0765ad906740
Additional packages (*) will be modified to complete this operation.
Restored 0 packages from C:\Users\isaac.poplin.adm\AppData\Local\vcpkg\archives in 204.1 us. Use --debug to see more details.
Starting package 1/2: zlib:x64-windows
Building package zlib[core]:x64-windows...
-- Installing port from location: C:\dev\vcpkg\buildtrees\versioning_\versions\zlib\92cfe30c807d343c6359d272242f0765ad906740
-- Using cached zlib1211.tar.gz.
-- Cleaning sources at C:/dev/vcpkg/buildtrees/zlib/src/1.2.11-e9a093319e.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/dev/vcpkg/downloads/zlib1211.tar.gz
-- Applying patch cmake_dont_build_more_than_needed.patch
-- Applying patch 0001-Prevent-invalid-inclusions-when-HAVE_-is-set-to-0.patch
-- Applying patch add_debug_postfix_on_mingw.patch
-- Applying patch 0002-android-build-mingw.patch
-- Using source at C:/dev/vcpkg/buildtrees/zlib/src/1.2.11-e9a093319e.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: C:/dev/vcpkg/packages/zlib_x64-windows/share/zlib/vcpkg-cmake-wrapper.cmake
-- Fixing pkgconfig file: C:/dev/vcpkg/packages/zlib_x64-windows/lib/pkgconfig/zlib.pc
-- Using cached msys-mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst.
-- Using msys root at C:/dev/vcpkg/downloads/tools/msys2/9a1ec3f33446b195
-- Fixing pkgconfig file: C:/dev/vcpkg/packages/zlib_x64-windows/debug/lib/pkgconfig/zlib.pc
-- Installing: C:/dev/vcpkg/packages/zlib_x64-windows/share/zlib/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\isaac.poplin.adm\AppData\Local\vcpkg\archives\21\214d502bb629fc19246b5ad5df0a630ffa9c487644359a550f1c265a8e4777d0.zip
Installing package zlib[core]:x64-windows...
Elapsed time for package zlib:x64-windows: 3.808 s
Starting package 2/2: protobuf:x64-windows
Building package protobuf[core]:x64-windows...
-- Installing port from location: C:\dev\vcpkg\buildtrees\versioning_\versions\protobuf\b6fd0beef65a76c6efc90b702e61d150f25b62d3
CMake Warning at scripts/cmake/vcpkg_common_functions.cmake:3 (message):
  vcpkg_common_functions has been removed and all values are automatically
  provided in all portfile.cmake invocations.  Please remove
  `include(vcpkg_common_functions)`.
Call Stack (most recent call first):
  buildtrees/versioning_/versions/protobuf/b6fd0beef65a76c6efc90b702e61d150f25b62d3/portfile.cmake:1 (include)
  scripts/ports.cmake:145 (include)


-- Using cached protobuf-cpp-3.4.0.tar.gz.
-- Using cached protoc-3.4.0-win32.zip.
CMake Deprecation Warning at scripts/ports.cmake:75 (message):
  Deprecated form of vcpkg_extract_source_archive used:

      Please use the `vcpkg_extract_source_archive(<out-var> ARCHIVE <archive>)` form.
Call Stack (most recent call first):
  scripts/cmake/vcpkg_extract_source_archive.cmake:97 (z_vcpkg_deprecation_message)
  buildtrees/versioning_/versions/protobuf/b6fd0beef65a76c6efc90b702e61d150f25b62d3/portfile.cmake:19 (vcpkg_extract_source_archive)
  scripts/ports.cmake:145 (include)


-- Extracting source C:/dev/vcpkg/downloads/protobuf-cpp-3.4.0.tar.gz
CMake Deprecation Warning at scripts/ports.cmake:75 (message):
  vcpkg_apply_patches has been deprecated in favor of the `PATCHES` argument
  to `vcpkg_from_*`.
Call Stack (most recent call first):
  scripts/cmake/vcpkg_apply_patches.cmake:18 (z_vcpkg_deprecation_message)
  buildtrees/versioning_/versions/protobuf/b6fd0beef65a76c6efc90b702e61d150f25b62d3/portfile.cmake:22 (vcpkg_apply_patches)
  scripts/ports.cmake:145 (include)


-- Applying patch C:/dev/vcpkg/buildtrees/versioning_/versions/protobuf/b6fd0beef65a76c6efc90b702e61d150f25b62d3/001-add-compiler-flag.patch
CMake Deprecation Warning at scripts/ports.cmake:75 (message):
  Deprecated form of vcpkg_extract_source_archive used:

      Please use the `vcpkg_extract_source_archive(<out-var> ARCHIVE <archive>)` form.
Call Stack (most recent call first):
  scripts/cmake/vcpkg_extract_source_archive.cmake:97 (z_vcpkg_deprecation_message)
  buildtrees/versioning_/versions/protobuf/b6fd0beef65a76c6efc90b702e61d150f25b62d3/portfile.cmake:28 (vcpkg_extract_source_archive)
  scripts/ports.cmake:145 (include)


-- Extracting source C:/dev/vcpkg/downloads/protoc-3.4.0-win32.zip
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_install_cmake.cmake:34 (message):
  vcpkg_cmake_install was passed extra arguments: MSVC_64_TOOLSET
Call Stack (most recent call first):
  buildtrees/versioning_/versions/protobuf/b6fd0beef65a76c6efc90b702e61d150f25b62d3/portfile.cmake:61 (vcpkg_install_cmake)
  scripts/ports.cmake:145 (include)


Error: Building package protobuf:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+protobuf
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[protobuf]+Build+error
including:
  package: protobuf[core]:x64-windows -> 3.4.0-2
    vcpkg-tool version: 2022-02-11-dac008bf9b55ef48e10bcc81e273b97a82bbf72d
    vcpkg-scripts version: 18e6e8855 2022-02-15 (10 hours ago)

Additionally, attach any relevant sections from the log files above.
```
`3.4.1-2` seems to install fine, however it looks like it may actually be grabbing version `3.5.0`:
```
-- Downloading https://github.com/google/protobuf/releases/download/v3.5.0/protobuf-cpp-3.5.0.tar.gz -> protobuf-cpp-3.5.0.tar.gz...
-- Downloading https://github.com/google/protobuf/releases/download/v3.5.0/protoc-3.5.0-win32.zip -> protoc-3.5.0-win32.zip...
```
Using `3.4.1-1` appears to use the expected version of `protobuf` and install without error.

**Comment by Thomas1664** [comment]
> Using `3.4.1-1` appears to use the expected version of `protobuf` and install without error.

I think you must use `3.4.1-1` or try to fix the cmake error by yourself because we can't fix previous versions of a port. 

> ```
> -- Extracting source C:/dev/vcpkg/downloads/protoc-3.4.0-win32.zip
> -- Configuring x64-windows
> CMake Error at scripts/cmake/vcpkg_install_cmake.cmake:34 (message):
>   vcpkg_cmake_install was passed extra arguments: MSVC_64_TOOLSET
> Call Stack (most recent call first):
>   buildtrees/versioning_/versions/protobuf/b6fd0beef65a76c6efc90b702e61d150f25b62d3/portfile.cmake:61 (vcpkg_install_cmake)
>   scripts/ports.cmake:145 (include)
> ```

The problem is that `vcpkg_install_cmake` has an extra argument `MSVC_64_TOOLSET` that isn't used anymore.
Maybe @FrankXie05 knows more

**Comment by FrankXie05** [comment]
@Scotty1701 Sorry for the late reply，Thanks for your reply @Thomas1664 👍 And https://github.com/microsoft/vcpkg/issues/23117#issuecomment-1041563992  It does work as a workaround, but the version of the port it depends on changes in the latest vcpkg, like patching dependency errors, I think the most efficient way is 
1. Rollback the vcpkg library version and 
2. Overwrite the port you want to build on file,
3. Update the vcpkg library

For using a port specifying an older version, `--overlay-port` can be used. see https://github.com/microsoft/vcpkg/issues/22656#issuecomment-1036024997 and related file: https://github.com/microsoft/vcpkg/blob/master/docs/specifications/ports-overlay.md

**Comment by Scotty1701** [comment]
Thanks for the help guys, I actually ended up using a slightly different workaround to get things to build. I installed `protobuf` separately using the manifest method, then copied the files into the main `vcpkg` directory locations, then was able to build `cartographer` using the version of `protobuf` I wanted. `Protobuf` version `3.13.0#2` ended up being the version I needed to work with the `cartographer_ros` `ros2-dashing-1.0.0` branch. 

Is versioning support planned for classic mode/command line interface? I don't see it explicitly mentioned in the [roadmap ](https://github.com/microsoft/vcpkg/wiki/Roadmap) however the second paragraph of the More Details section seems to suggest such functionality. I personally would fine this very useful.

**Comment by JackBoosY** [comment]
vcpkg will use the latest dependency port version by default, but you can still specify it:
-  overlay port: after backing up(use `./vcpkg x-history` then `git reset HASH`) the port folder (_VCPKG_ROOT/ports/PORT_NAME_) of the specified version, manually specify the path used by the installation port.
See https://github.com/microsoft/vcpkg/blob/master/docs/specifications/ports-overlay.md#3-proposed-solution
-  registry. See https://github.com/microsoft/vcpkg/blob/master/docs/specifications/registries-2.md

**Comment by FrankXie05** [comment]
@Scotty1701 Could you please try to test the jack method?

**Comment by FrankXie05** [comment]
@Scotty1701 Is still work for this issue? Please reply me if the problem still exist and I will reopen it.
