### ISSUE TITLE
blaze run error

### ISSUE THREAD

**Issue by TongTianDaXia** [microsoft/vcpkg#23115]
**Describe the bug**
blaze run error when using Platform Toolset vs2022(v143). But it's ok if change it to Platform Toolset vs2019(v142)

**Environment**
- OS: windows11
- Compiler: VS2022 17.0.6

**To Reproduce**
installation of blaze is ok, but when compiling the src with #include<blaze/Math.h>
then error report:
1>C:\src\vcpkg\installed\x64-windows\include\blaze\math\dense\StaticVector.h(3642,1): error C2593: 'operator !=' is ambiguous
1>C:\src\vcpkg\installed\x64-windows\include\blaze\math\dense\StaticVector.h(3642,1): message : could be 'built-in C++ operator!=(size_t, int)'
1>C:\src\vcpkg\installed\x64-windows\include\blaze\math\dense\StaticVector.h(3642,1): message : or       'built-in C++ operator!=(size_t, unsigned int)'
1>C:\src\vcpkg\installed\x64-windows\include\blaze\math\dense\StaticVector.h(3642,1): message : or       'built-in C++ operator!=(size_t, unsigned long)'
1>C:\src\vcpkg\installed\x64-windows\include\blaze\math\dense\StaticVector.h(3642,1): message : or       'built-in C++ operator!=(size_t, long)'
1>C:\src\vcpkg\installed\x64-windows\include\blaze\math\dense\StaticVector.h(3642,1): message : or       'built-in C++ operator!=(size_t, size_t)'
1>C:\src\vcpkg\installed\x64-windows\include\blaze\math\dense\StaticVector.h(3642,1): message : or       'built-in C++ operator!=(size_t, ptrdiff_t)'
1>C:\src\vcpkg\installed\x64-windows\include\blaze\math\dense\StaticVector.h(3642,1): message : or       'built-in C++ operator!=(size_t, float)'
1>C:\src\vcpkg\installed\x64-windows\include\blaze\math\dense\StaticVector.h(3642,1): message : or       'built-in C++ operator!=(size_t, double)'
1>C:\src\vcpkg\installed\x64-windows\include\blaze\math\dense\StaticVector.h(3642,1): message : or       'built-in C++ operator!=(size_t, long double)'
1>C:\src\vcpkg\installed\x64-windows\include\blaze\math\dense\StaticVector.h(3642,1): message : while trying to match the argument list '(size_t, const blaze::Infinity)'

...

**Comment by Cheney-W** [comment]
Could you please provide your repro codes to me?

**Comment by TongTianDaXia** [comment]
![image](https://user-images.githubusercontent.com/16608419/154671575-38413ce4-9a9d-447d-a5e9-9a455991ef53.png)


do you mean this?

can you reproduce the problem?

**Comment by TongTianDaXia** [comment]
@Cheney-W
