### ISSUE TITLE
[orc] update to 1.7.2 or higher

### ISSUE THREAD

**Issue by ianmcook** [microsoft/vcpkg#23118]
Library name: **orc**

New version number: **1.7.2 or higher**

This is required to enable the **orc** feature of the **arrow** port in version 7.0.0 or higher (https://github.com/apache/arrow/pull/12006, https://github.com/microsoft/vcpkg/pull/23032).

**Comment by LouisClt** [comment]
Hello, is there a reason why this is still active ? I needed this to compile last version of Arrow (8.0.0) with ORC support.
I did this "by hand" by applying the pull request proposed by Thomas1664 on my local files. It then compiled successfully.

**Comment by LouisClt** [comment]
Any news on this matter ?

**Comment by JonLiu1993** [comment]
> 

@LouisClt, I have committed pr update orc to latest version 1.7.6 and ci test is successful, please wait for this [pr ](https://github.com/microsoft/vcpkg/pull/26603)merge
