### ISSUE TITLE
__GSHandlerCheck_EH4 Error

### ISSUE THREAD

**Issue by killghost** [microsoft/vcpkg#23121]
I was able to compile jsoncpp (x64-windows-static) with the latest vcpkg. cpkg will automatically compile jsoncpp version 1.9.5.

I copied the Lib file and Header file to my project. v There will be an error GSHandlerCheck Error here:

1>json2_jsoncpp_x64.lib(json_writer.cpp.obj) : error LNK2001: __GSHandlerCheck_EH4
1>json2_jsoncpp_x64.lib(json_value.cpp.obj) : error LNK2001: __GSHandlerCheck_EH4

If I use vcpkg release (2021.05.12) version. He will compile jsoncpp 1.9.4. And it can be used normally in my project.

The latest vcpkg compiled jsoncpp 64-bit, his Lib size is 5.1M

The jsoncpp 64-bit compiled by vcpkg release (2021.05.12) version has a Lib size of 5.9M

I Can anyone help me to solve this problem. Thanks

**Comment by JackBoosY** [comment]
Did you installed more than one Visual Studio?
Can you please provide their versions?

Thanks.

**Comment by killghost** [comment]
I Have Installed VS 2017 And VS 2019

**Comment by killghost** [comment]
C:\vcpkg-2021.05.12>vcpkg install jsoncpp:x64-windows-static
Computing installation plan...
The following packages will be built and installed:
    jsoncpp[core]:x64-windows-static -> 1.9.4
Warning: The following VS instances are excluded because the English language pack is unavailable.
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional
Please install the English language pack.
Detecting compiler hash for triplet x64-windows-static...
Using cached binary package: C:\Users\GamePP10900K\AppData\Local\vcpkg\archives\f7\f7afd0b481a66c10c3a7d5535131ac3448a08791.zip
Starting package 1/1: jsoncpp:x64-windows-static
Building package jsoncpp[core]:x64-windows-static...
Building package jsoncpp[core]:x64-windows-static... done
Installing package jsoncpp[core]:x64-windows-static...
Installing package jsoncpp[core]:x64-windows-static... done
Elapsed time for package jsoncpp:x64-windows-static: 109.8 ms

Total elapsed time: 1.55 s

The package jsoncpp:x64-windows-static provides CMake targets:

    find_package(jsoncpp CONFIG REQUIRED)
    target_link_libraries(main PRIVATE jsoncpp_object jsoncpp_static)

**Comment by JackBoosY** [comment]
Therefore, the reason for this issue should be that vcpkg uses Visual Studio 2019 to build jsoncpp, and you use the generated binary in Visual Studio 2017. Right?

**Comment by killghost** [comment]
Yes,then How to specify to use vs 2017 to compile the library?

**Comment by JackBoosY** [comment]
Add the following code to the toolchain file(.cmake) in _VCPKG_ROOT/triplets_:
```cmake
set(VCPKG_PLATFORM_TOOLSET v141)
```

**Comment by killghost** [comment]
Thanks a lot, my problem is solved
