### ISSUE TITLE
Visual Studio 2022 don't find installed packages

### ISSUE THREAD

**Issue by 6a6f6a6f** [microsoft/vcpkg#23123]
**Describe the bug**
After installing any pkg via `vcpkg`, VS stills do not find the respective source file.

**Environment**
- OS: Windows 11 21H2
- Compiler: MSVC 14.30.30705

**To Reproduce**
1. `vcpkg install fmt`;
2. Try to include `fmt/core.h` inside a C++ project.

**Expected behavior**
Just works I think.

**Failure logs** 
There is not.

**Additional context**
My installation steps of `vcpkg`:

```powershell
$ New-Item -Path "C:\" -Name "src" -ItemType "directory"
$ cd "C:\src"
$ git clone https://github.com/Microsoft/vcpkg.git
$ cd vcpkg
$ .\bootstrap-vcpkg.bat
$ vcpkg.exe integrate install
$ New-Item -Path "C:\" -Name "tools" -ItemType "directory"
$ Copy-Item "C:\src\vcpkg.exe" -Destination "C:\tools"
$ [Environment]::SetEnvironmentVariable("Path", [Environment]::GetEnvironmentVariable("Path", [EnvironmentVariableTarget]::Machine) + ";C:\tools", [EnvironmentVariableTarget]::User)
$ [Environment]::SetEnvironmentVariable("VCPKG_ROOT", "C:\src\vcpkg", [System.EnvironmentVariableTarget]::User)
```

**Comment by FrankXie05** [comment]
@6a6f6a6f  Thanks for posting this issue. Could you provide the file CMakeSettings.json in your VS?

**Comment by gounnoticed** [comment]
Here is the only CMakeSettings.json which is in vcpkg 
{
  "configurations": [
    {
      "name": "x64-Debug",
      "generator": "Ninja",
      "configurationType": "Debug",
      "inheritEnvironments": [
        "msvc_x64_x64"
      ],
      "buildRoot": "${env.USERPROFILE}\\CMakeBuilds\\${workspaceHash}\\build\\${name}",
      "installRoot": "${env.USERPROFILE}\\CMakeBuilds\\${workspaceHash}\\install\\${name}",
      "cmakeCommandArgs": "-DGSL_CXX_STANDARD=17",
      "buildCommandArgs": "-v",
      "ctestCommandArgs": "",
      "codeAnalysisRuleset": "CppCoreCheckRules.ruleset"
    }
  ]
}

**Comment by FrankXie05** [comment]
@gounnoticed Sorry for the late reply.
Please note:
1. Make sure the CMakeLists file is added
find_package(fmt CONFIG REQUIRED) 
target_link_libraries(main PRIVATE fmt::fmt)
 Or
find_package(fmt CONFIG REQUIRED) 
target_link_libraries(main PRIVATE fmt::fmt-header-only)
2. If CMake is modified, you need to delete and regenerate the CMake cache

You can try the following modifications
```
{
"configurations": [
{
"name": "x64-Debug",
"generator": "Visual Studio 16 2019 Win64",
"configurationType": "Debug",
"inheritEnvironments": [
"msvc_x64_x64"
],
"buildRoot": "${env.USERPROFILE}\CMakeBuilds\${workspaceHash}\build\${name}",
"installRoot": "${env.USERPROFILE}\CMakeBuilds\${workspaceHash}\install\${name}",
"cmakeCommandArgs": "-DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake",
"buildCommandArgs": "-v",
"ctestCommandArgs": "",
"codeAnalysisRuleset": "CppCoreCheckRules.ruleset"
}
]
}
```

**Comment by JackBoosY** [comment]
Did you use `integrate` command before?

**Comment by FrankXie05** [comment]
@6a6f6a6f @gounnoticed Is still work for this issue?

**Comment by FrankXie05** [comment]
Close this issue due to no reply for a long time

**Comment by hugle** [comment]
I am also using VS2022, based on the [vcpkg documentation](https://vcpkg.readthedocs.io/en/latest/examples/installing-and-using-packages/). There requires to add the following config for variable `CMAKE_BUILD_TYPE` in `CMakePresets.json` file:

```json
"cacheVariables": {
    "CMAKE_BUILD_TYPE": "Release",
    "CMAKE_TOOLCHAIN_FILE": "D:\\src\\vcpkg\\scripts\\buildsystems\\vcpkg.cmake"
}
```
