### ISSUE TITLE
SQLiteCpp not in search list

### ISSUE THREAD

**Issue by ha0x7c7** [Microsoft/vcpkg#2312]
Please add this library to search list

**Comment by ha0x7c7** [comment]
by the way how can I make a PR for this issue?

**Comment by ras0219-msft** [comment]
Take a look at our [packaging zlib](https://github.com/Microsoft/vcpkg/blob/master/docs/examples/packaging-zlib.md) example, then submit a PR here with your new port 😄!

**Comment by ha0x7c7** [comment]
> First, locate a globally accessible archive of the library's sources. Zip, gzip, and bzip are all supported. Strongly prefer official sources or mirrors over unofficial mirrors.

What if it doesn't have a globally accessible source, I mean the project is hosted on github, where is the link to source in github projects?

**Comment by ras0219-msft** [comment]
For GitHub projects you can use the "download as zip" link, however it's even better to use `vcpkg_from_github()`[1]. If you'd like to use that, then simply put a dummy link into the `create` command and then replace the download command in the generated portfile.

[1] https://vcpkg.readthedocs.io/en/latest/maintainers/vcpkg_from_github/
