### ISSUE TITLE
[New Port Request] subhook

### ISSUE THREAD

**Issue by ori-d** [microsoft/vcpkg#23131]
Library name: subhook

Library description: SubHook is a super-simple hooking library for C and C++ that works on Windows, Linux and macOS. It supports x86 only (32-bit and 64-bit).

Source repository URL: https://github.com/Zeex/subhook

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
