### ISSUE TITLE
magic_enum does not seem to get installed at all

### ISSUE THREAD

**Issue by tester0077** [microsoft/vcpkg#23137]
**Describe the bug**
magic_enum is a header-only package but the header file does not show anywhere in the install tree
**Environment**
- OS: Win 10 64
- Compiler: MSVC 2019 community edition

**To Reproduce**
1.  ./vcpkg install magic_enum
2. no error

**Expected behavior**
expect to have magic_enum.hpp installed in the install tree

**Failure logs** 
-(please attached failure logs)

**Additional context**

**Comment by Neumann-A** [comment]
since i am using magic enum i can tell you that it gets installed. And since I just did a rebuild of all of my dependencies today I can tell you that it works. 

Also it is
`./vcpkg install magic-enum`

_ is not allowed in vcpkg

**Comment by tester0077** [comment]
Thank you, that does make a difference and does install the header file.
Unsure of why I missed the error report, still,  using 'magic-enum' does
produce an error, but it also creates a directory magic-enum in
x86-windows/share

**Comment by Neumann-A** [comment]
> using 'magic-enum' does produce an error,

which says it cannot be found? probably because you want x64 and not x86: `./vcpkg install magic-enum:x64-windows`

**Comment by Adela0814** [comment]
@tester0077 I can not repro your failure, `magic_enum.hpp` can be find in my install tree. could you check `vcpkg\installed\x64-windows\include\magic_enum.hpp` in your machine.

**Comment by tester0077** [comment]
I only needed the x86 version at the time.
FWIW, I have still not decided to actually use this header permanently and
so have not worked with it since I first ran into this issue.

**Comment by Adela0814** [comment]
If you installed `magic-enum` using `./vcpkg install magic-enum`, you need to check the path vcpkg\installed\x86-windows\include\magic_enum.hpp. because the default platform is x86-windows.

**Comment by Adela0814** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
