### ISSUE TITLE
[ffmpeg] Build error

### ISSUE THREAD

**Issue by NoWhereMan1979** [microsoft/vcpkg#23130]
**Host Environment**
- OS: Linux
- Compiler: gcc 9.3.0
- CUDA 11.4

**To Reproduce**
`./vcpkg install ffmpeg[ffmpeg,ffplay,ffprobe,nvcodec,avresample]`

**Failure logs** 
/tmp/ffconf.KXWmnZm6/test.cu
nvcc -gencode arch=compute_30,code=sm_30 -O2 -m64 -ptx -c -o /tmp/ffconf.KXWmnZm6/test.o /tmp/ffconf.KXWmnZm6/test.cu
nvcc fatal   : Unsupported gpu architecture 'compute_30'
ERROR: failed checking for nvcc.

**Additional context**
I have installed CUDA 11.4 that has abandoned 'compute_30' long ago.
I know it is the FFMPEG's problem but it would be great if vcpkg consider this as an optional patch

**My solution**
Added the following code to the ‘vcpkg/ports/ffmpeg/build.sh.in’ script just before calling build_ffmpeg() function
echo "=== Editing compute_30, sm_30 to 35 to bypass nvcc fatal: Unsupported gpu architecture 'compute_30' ==="
sed -i "s/compute_30/compute_35/g" $PATH_TO_SRC_DIR/configure
sed -i "s/sm_30/sm_35/g" $PATH_TO_SRC_DIR/configure

**Say something politely**
Thanks for this great gift and all other contributions to the Open Source culture.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue, is there upstream issue or PR report this bug?

**Comment by NoWhereMan1979** [comment]
Considering what i did, was some hackish way, i think there should be a better way to do that, so still didn't issued any PR. 
Beside there is another problem of using ffmpeg with cuda that i passed through using this kind of tricks.
So do you think i should have a fork and off course do the patches in a more clear way?

**Comment by LilyWangLL** [comment]
> Considering what i did, was some hackish way, i think there should be a better way to do that, so still didn't issued any PR. Beside there is another problem of using ffmpeg with cuda that i passed through using this kind of tricks. So do you think i should have a fork and off course do the patches in a more clear way?

Sorry I am late, I think you need submit an issue or PR on upstream to report this issue. If upstream apply this way, we can add a patch to sync the change to VCPKG.

**Comment by JackBoosY** [comment]
Close this issue/PR until upstream fixes this.
