### ISSUE TITLE
[yajl] macos & linux build failure

### ISSUE THREAD

**Issue by vadi2** [microsoft/vcpkg#23147]
The port uses the https://github.com/lloyd/yajl/archive/2.1.0.tar.gz download location which worked previously, but does not work anymore since Github changed it in their backend.

```
  Building package yajl[core]:x64-linux...
  -- Downloading https://github.com/lloyd/yajl/archive/2.1.0.tar.gz -> lloyd-yajl-2.1.0.tar.gz...
  [DEBUG] Feature flag 'binarycaching' unset
  [DEBUG] Feature flag 'manifests' = off
  [DEBUG] Feature flag 'compilertracking' unset
  [DEBUG] Feature flag 'registries' unset
  [DEBUG] Feature flag 'versions' unset
  [DEBUG] popen(curl --fail -L https://github.com/lloyd/yajl/archive/2.1.0.tar.gz --create-dirs --output /home/runner/work/Mudlet/Mudlet/3rdparty/vcpkg/downloads/lloyd-yajl-2.1.0.tar.gz.15237.part 2>&1)
  [DEBUG] cmd_execute_and_stream_data() returned 0 after   164241 us
  Error: Failed to download from mirror set:
  File does not have the expected hash:
               url : [ https://github.com/lloyd/yajl/archive/2.1.0.tar.gz ]
         File path : [ /home/runner/work/Mudlet/Mudlet/3rdparty/vcpkg/downloads/lloyd-yajl-2.1.0.tar.gz.15237.part ]
     Expected hash : [ 9e786d080803df80ec03a9c2f447501e6e8e433a6baf636824bc1d50ecf4f5f80d7dfb1d47958aeb0a30fe459bd0ef033d41bc6a79e1dc6e6b5eade930b19b02 ]
       Actual hash : [ ba50b7fc9eb733e586ba48131fcdcb8e615bdb148733dd3fc729f48be390e1f3f3fc1013ad9b41584234ca1058dfc6067639ccc1cb6a32286609344b39b19fd4 ]
```

**Comment by FrankXie05** [comment]
@vadi2 Thanks for possing this issue, are you using the `vcpkg` to build? If yes, could you please provide the file `vcpkg.json`

**Comment by vadi2** [comment]
I'm not using a manifest file yet.

**Comment by FrankXie05** [comment]
You might consider replacing the hash in file
`/home/runner/work/Mudlet/Mudlet/3rdparty/vcpkg/downloads/lloyd-yajl-2.1.0.tar.gz.15237.part`
The expected hash : 
`[9e786d080803df80ec03a9c2f447501e6e8e433a6baf636824bc1d50ecf4f5f80d7dfb1d47958aeb0a30fe459bd0ef033d41bc6a79e1dc6e6b5eade930b19b02 ]`

**Comment by vadi2** [comment]
Erm, that download link is no longer valid. Changing the hash is an absolutely incorrect solution.

**Comment by FrankXie05** [comment]
The latest download url: https://github.com/lloyd/yajl/archive/refs/tags/2.1.0.tar.gz

**Comment by JackBoosY** [comment]
Upstream may republish the version or modify the published REF, causing the download to fail.
