### ISSUE TITLE
[libtommath] cross-compiling for ARM64 build failure

### ISSUE THREAD

**Issue by atopavirgil** [microsoft/vcpkg#23140]
**Host Environment**
- OS: Linux Ubuntu x86
- Compiler: Cross-compile for Android using NDK (23)

The build works, but the created library is not cross-compiled for ARM but for x86. Any other library build using the same configuration and triplet is build properly. This is the same for a static or dynamic build.

Using triplet:
```cmake
set(VCPKG_TARGET_ARCHITECTURE arm64)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_CMAKE_SYSTEM_NAME Android)
```
After build:
```
objdump -f libtommath.a
```
In archive libtommath.a:
```
mp_2expt.o:     file format elf64-x86-64
architecture: i386:x86-64, flags 0x00000011:
HAS_RELOC, HAS_SYMS
start address 0x0000000000000000


mp_abs.o:     file format elf64-x86-64
architecture: i386:x86-64, flags 0x00000011:
HAS_RELOC, HAS_SYMS
start address 0x0000000000000000


mp_add.o:     file format elf64-x86-64
architecture: i386:x86-64, flags 0x00000011:
HAS_RELOC, HAS_SYMS
start address 0x0000000000000000
```

Which is wrong. This library was build for x86 (not for ARM64).

For example another library build using same environment shows:
```
objdump -f libbenchmark.a

benchmark.cc.o:     file format elf64-little
architecture: UNKNOWN!, flags 0x00000011:
HAS_RELOC, HAS_SYMS
start address 0x0000000000000000


benchmark_api_internal.cc.o:     file format elf64-little
architecture: UNKNOWN!, flags 0x00000011:
HAS_RELOC, HAS_SYMS
start address 0x0000000000000000


benchmark_name.cc.o:     file format elf64-little
architecture: UNKNOWN!, flags 0x00000011:
HAS_RELOC, HAS_SYMS
start address 0x0000000000000000


benchmark_register.cc.o:     file format elf64-little
architecture: UNKNOWN!, flags 0x00000011:
HAS_RELOC, HAS_SYMS
start address 0x0000000000000000
```

Which is correct, this library was build for ARM64

The problem may be related to the tool used, "libtool" which is used by libtommath.

Probably will be the same problem for ANY cross-compile.

Any sugestions ?

**Comment by JackBoosY** [comment]
Can you please provide the build logs in _VCPKG_ROOT/buildtrees/libtommath_ ?

**Comment by atopavirgil** [comment]
The problem may be with any cross-compiling (did not try but may be the same for Apple M1).

**Comment by JackBoosY** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
