### ISSUE TITLE
Cannot open include file: 'glibmmconfig.h'

### ISSUE THREAD

**Issue by imindude** [microsoft/vcpkg#23159]
**Describe the bug**
[proc] Executing command: C:\msys64\mingw64\bin\cmake.EXE --build d:/workspace/testcase/GTKMM-Test/build --config Debug --target ALL_BUILD -j 14 --
[build] Microsoft (R) Build Engine version 17.0.0+c9eb9dd64 for .NET Framework
[build] Copyright (C) Microsoft Corporation. All rights reserved.
[build] 
[build]   Checking Build System
[build]   Building Custom Rule D:/workspace/testcase/GTKMM-Test/CMakeLists.txt
[build]   Main.cpp
[build] C:\vcpkg\installed\x64-windows\include\glibmm-2.68\glibmm.h(96,10): fatal error C1083: Cannot open include file: 'glibmmconfig.h': No such file or directory [D:\workspace\testcase\GTKMM-Test\build\DroneGuidance.vcxproj]
[build] Build finished with exit code 1

**Environment**
- OS: Windows 11
- Compiler: MSVC 14.3

**To Reproduce**
1. ./vcpkg install gtkmm:x64-windows : OK
2. Write a test program
2. See error
Refer to "*Describe the bug"

**Expected behavior**

**Failure logs** 
Same as above

**Additional context**
Here is my test code. When I compiled this, compiler cannot find "gtkmmconfig.h".
[GTKMM-Test.zip](https://github.com/microsoft/vcpkg/files/8093666/GTKMM-Test.zip)

**Comment by imindude** [comment]
I found that file in the "lib/glibmm-2.68/include" directory. I think it's my fault.

**Comment by JonLiu1993** [comment]
@imindude ,Thanks for posting this issue, I use the [GTKMM-Test.zip](https://github.com/microsoft/vcpkg/files/8093666/GTKMM-Test.zip) you provide reproduce your issue, but got a different error than you, Am I missing some steps?
````
PS F:\test9\test\build> F:\test9\vcpkg\downloads\tools\cmake-3.21.1-windows\cmake-3.21.1-windows-i386\bin\cmake.exe .. -G "Visual Studio 16 2019" -DCMAKE_TOOLCHAIN_FILE=F:/test9/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_BUILD_TYPE=debug
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
-- The C compiler identification is MSVC 19.29.30137.0
-- The CXX compiler identification is MSVC 19.29.30137.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - no
-- Found Threads: TRUE
CMake Error at F:/test9/vcpkg/downloads/tools/cmake-3.21.1-windows/cmake-3.21.1-windows-i386/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Boost (missing: Boost_INCLUDE_DIR thread chrono)
Call Stack (most recent call first):
  F:/test9/vcpkg/downloads/tools/cmake-3.21.1-windows/cmake-3.21.1-windows-i386/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  F:/test9/vcpkg/downloads/tools/cmake-3.21.1-windows/cmake-3.21.1-windows-i386/share/cmake-3.21/Modules/FindBoost.cmake:2345 (find_package_handle_standard_args)
  F:/test9/vcpkg/installed/x64-windows/share/boost/vcpkg-cmake-wrapper.cmake:11 (_find_package)
  F:/test9/vcpkg/scripts/buildsystems/vcpkg.cmake:743 (include)
  CMakeLists.txt:22 (find_package)


-- Configuring incomplete, errors occurred!
See also "F:/test9/test/build/CMakeFiles/CMakeOutput.log".
See also "F:/test9/test/build/CMakeFiles/CMakeError.log".
````
![image](https://user-images.githubusercontent.com/63675417/154632403-de0e74e2-faaf-4700-bfd0-a8df937e0ded.png)

**Comment by Neumann-A** [comment]
small tipp use `FindPkgConfig` your `FindGTKMM` is incorrect. 

Can be closed since it is not a vcpkg issue

**Comment by imindude** [comment]
> @imindude ,Thanks for posting this issue, I use the [GTKMM-Test.zip](https://github.com/microsoft/vcpkg/files/8093666/GTKMM-Test.zip) you provide reproduce your issue, but got a different error than you, Am I missing some steps?

I don't know why. My msys2's cmake working well, but vcpkg's cmake is not.
Anyway it just another issue. Thank you.
