### ISSUE TITLE
nuget export option to support .nuspec as an input

### ISSUE THREAD

**Issue by imback82** [microsoft/vcpkg#2315]
Currently, vcpkg.exe supports the following options for exporting as nuget packages
--nuget-id
--nuget-version

Can you add an option to accept .nuspec files to configure the nuget packages?

**Comment by ras0219-msft** [comment]
Hi @imback82, what settings are you wanting to configure?

**Comment by imback82** [comment]
Description will be good. Also, the --nuget-id value specified is lower-cased in the output. Is this an intended feature?

**Comment by NancyLi1013** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen.
