### ISSUE TITLE
No GitHub releases for latest vcpkg version

### ISSUE THREAD

**Issue by mrexodia** [microsoft/vcpkg#23155]
## Problem

It's confusing that the vcpkg releases are not the latest version available. You have to look at the tags to find out the latest vcpkg version that was actually released.

![image](https://user-images.githubusercontent.com/2458265/154577974-5b8f989a-db5b-4ec8-8e77-ca9dd8984d3f.png)

## Proposed solution

Create a release for every tag.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue? Now every tag has the related release version in vcpkg. I think this issue can be closed.
![image](https://user-images.githubusercontent.com/94091114/180393858-22731136-8dc8-4703-8494-36b6ab94cbf2.png)
![image](https://user-images.githubusercontent.com/94091114/180394786-98da57aa-d1ce-4f8f-a6ec-d07f323f332a.png)

**Comment by mrexodia** [comment]
Thanks!

**Comment by mrexodia** [comment]
Thanks!
