### ISSUE TITLE
[colmap] build failure

### ISSUE THREAD

**Issue by YUME-FF** [microsoft/vcpkg#23160]
following instruction by using .\vcpkg install colmap[cuda,tests]:x64-windows to build colmap, however,
[install-x64-windows-dbg-out-1.log](https://github.com/microsoft/vcpkg/files/8093716/install-x64-windows-dbg-out-1.log)
[install-x64-windows-dbg-err-1.log](https://github.com/microsoft/vcpkg/files/8093718/install-x64-windows-dbg-err-1.log)
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/8093721/install-x64-windows-dbg-out.log)

D:\Eng\VCPKG>.\vcpkg install colmap[cuda,tests]:x64-windows
Computing installation plan...
The following packages will be built and installed:
    colmap[core,cuda,tests]:x64-windows -> 3.7
Detecting compiler hash for triplet x64-windows...
-- Automatically setting HTTP(S)_PROXY environment variables to 127.0.0.1:7890
Restored 0 packages from C:\Users\FZ\AppData\Local\vcpkg\archives in 500.4 us. Use --debug to see more details.
Starting package 1/1: colmap:x64-windows
Building package colmap[core,cuda,tests]:x64-windows...
-- Using cached colmap-colmap-3.7.tar.gz.
-- Extracting source D:/Eng/VCPKG/downloads/colmap-colmap-3.7.tar.gz
-- Applying patch fix-dependency-freeimage.patch
-- Using source at D:/Eng/VCPKG/buildtrees/colmap/src/3.7-c5c387390d.clean
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
CMake Warning at scripts/cmake/vcpkg_execute_build_process.cmake:89 (message):
  Please ensure your system has sufficient memory.
Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:111 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
  ports/colmap/portfile.cmake:53 (vcpkg_cmake_install)
  scripts/ports.cmake:145 (include)

-- Restarting build without parallelism
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:158 (message):
    Command failed: D:/CMakeFiles/bin/cmake.exe --build . --config Debug --target install -- -v -j13
    Working Directory: D:/Eng/VCPKG/buildtrees/colmap/x64-windows-dbg
    See logs for more information:
      D:\Eng\VCPKG\buildtrees\colmap\install-x64-windows-dbg-out.log
      D:\Eng\VCPKG\buildtrees\colmap\install-x64-windows-dbg-out-1.log
      D:\Eng\VCPKG\buildtrees\colmap\install-x64-windows-dbg-err-1.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:111 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
  ports/colmap/portfile.cmake:53 (vcpkg_cmake_install)
  scripts/ports.cmake:145 (include)

Error: Building package colmap:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+colmap
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[colmap]+Build+error
including:
  package: colmap[core,cuda,tests]:x64[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/8093715/install-x64-windows-dbg-out.log)windows -> 3.7
    vcpkg-tool version: 2022-02-11-dac008bf9b55ef48e10bcc81e273b97a82bbf72d
    vcpkg-scripts version: unknown

Additionally, attach any relevant sections from the log files above.

**Comment by Cheney-W** [comment]
Thanks for posting this issue. 
I found you use cmake("D:\CMakeFiles\bin\cmake.exe") which not installed by VCPKG, could you remove it and install port again?

**Comment by JackBoosY** [comment]
```
Please ensure your system has sufficient memory.
```

D:\Eng\VCPKG\buildtrees\colmap\install-x64-windows-dbg-out.log
D:\Eng\VCPKG\buildtrees\colmap\install-x64-windows-dbg-out-1.log
D:\Eng\VCPKG\buildtrees\colmap\install-x64-windows-dbg-err-1.log

**Comment by YUME-FF** [comment]
Thanks for your comments, and I have tried to remove cmake and reinstall it by vcpkg, meanwhile, I turned off other unnecessary software to make sure I had enough memory, this, it turns out that
D:\Eng\VCPKG>.\vcpkg install colmap[cuda,tests]:x64-windows
Computing installation plan...
The following packages will be built and installed:
    colmap[core,cuda,tests]:x64-windows -> 3.7
Detecting compiler hash for triplet x64-windows...
Restored 0 packages from C:\Users\FZ\AppData\Local\vcpkg\archives in 575.7 us. Use --debug to see more details.
Starting package 1/1: colmap:x64-windows
Building package colmap[core,cuda,tests]:x64-windows...
-- Using cached colmap-colmap-3.7.tar.gz.
-- Cleaning sources at D:/Eng/VCPKG/buildtrees/colmap/src/3.7-c5c387390d.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/Eng/VCPKG/downloads/colmap-colmap-3.7.tar.gz
-- Applying patch fix-dependency-freeimage.patch
-- Using source at D:/Eng/VCPKG/buildtrees/colmap/src/3.7-c5c387390d.clean
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:158 (message):
    Command failed: D:/Eng/VCPKG/downloads/tools/cmake-3.21.1-windows/cmake-3.21.1-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j13
    Working Directory: D:/Eng/VCPKG/buildtrees/colmap/x64-windows-dbg
    See logs for more information:
      D:\Eng\VCPKG\buildtrees\colmap\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:111 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
  ports/colmap/portfile.cmake:53 (vcpkg_cmake_install)
  scripts/ports.cmake:145 (include)


Error: Building package colmap:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+colmap
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[colmap]+Build+error
including:
  package: colmap[core,cuda,tests]:x64-windows -> 3.7
    vcpkg-tool version: 2022-02-11-dac008bf9b55ef48e10bcc81e273b97a82bbf72d
    vcpkg-scripts version: unknown

Additionally, attach any relevant sections from the log files above.
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/8095099/install-x64-windows-dbg-out.log)

**Comment by JackBoosY** [comment]
```
LINK : fatal error LNK1168: cannot open src\base\triangulation_test.exe for writing
```
Please close your anti-virus and ensure you have enough disk space left.

Thanks.

**Comment by YUME-FF** [comment]
Done! Thank you!
