### ISSUE TITLE
[fribidi] build failure with x64-mingw-dynamic triplet

### ISSUE THREAD

**Issue by BMZE** [microsoft/vcpkg#23169]
**Host Environment**
- OS: Debian GNU/Linux 11 (bullseye)
- Compiler: x86_64-w64-mingw32

**To Reproduce**

1. Include fribidi as a dependency in vcpkg.json or another library that requires fribidi to build.
2. Run cmake --preset windows-release-from-linux
3. vcpkg install fails when trying to build fribidi.

This is my configure preset:
```
    {
      "name": "windows-release-from-linux",
      "displayName": "Windows x64 Release",
      "description": "Target Windows crosscompiling from linux",
      "generator": "Ninja",
      "binaryDir": "${sourceDir}/bin/build/${presetName}",
      "toolchainFile": "$env{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake",
      "environment": {
        "VCPKG_CMAKE_SYSTEM_NAME": "MinGW",
        "VCPKG_DEFAULT_TRIPLET=x64": "x64-mingw-dynamic",
        "VCPKG_DEFAULT_HOST_TRIPLET": "x64-mingw-dynamic"
      },
      "cacheVariables": {
        "CMAKE_INSTALL_PREFIX": "${sourceDir}/bin/install/${presetName}",
        "CMAKE_C_COMPILER": "x86_64-w64-mingw32-gcc",
        "CMAKE_CXX_COMPILER": "x86_64-w64-mingw32-g++",
        "CMAKE_BUILD_TYPE": "Release"
      }
    }
```

**Failure logs** 
[vcpkg-manifest-install.log](https://github.com/microsoft/vcpkg/files/8099366/vcpkg-manifest-install.log)
[config-x64-mingw-dynamic-dbg-out.log](https://github.com/microsoft/vcpkg/files/8099403/config-x64-mingw-dynamic-dbg-out.log)
[meson-log.txt](https://github.com/microsoft/vcpkg/files/8099413/meson-log.txt)

**Additional context**
I'm trying to cross compile my project for windows, but I currently can't as _vcpkg install_ fails when building fribidi. Am I doing something wrong? Any help on fixing this is very much appreciated!

**Comment by JackBoosY** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
