### ISSUE TITLE
Load vcpkg toolchain file causes msmpi cmake error

### ISSUE THREAD

**Issue by jasjuang** [Microsoft/vcpkg#2317]
In my downstream CMakeLists

```
cmake_minimum_required(VERSION 3.10)

project(Example)

set(PROJECT_SRCS ${PROJECT_SOURCE_DIR}/mycpp.cpp) 

find_package( MPI REQUIRED )

add_executable(${PROJECT_NAME} ${PROJECT_SRCS})

target_link_libraries(${PROJECT_NAME} MPI::MPI_CXX)
```

If I CMake it without including any vcpkg toolchain file, `cmake -A x64 ..` everything works. However, in my actual project I need to add the toolchain file but when I add it with `cmake -A x64 -C ..\initcmake ..` where initcmake is `set(CMAKE_TOOLCHAIN_FILE $ENV{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake CACHE STRING "")` it starts breaking. I get the error

```
-- Could NOT find MPI_C (missing: MPI_C_COMPILER) (found version "2.0")
-- Could NOT find MPI_CXX (missing: MPI_CXX_COMPILER) (found version "2.0")
```

if I run  `cmake -A x64 -C ..\initcmake ..` more than once.

When I investigate more thoroughly, I notice that if the tool chain file is not loaded

variable `MPI_msmpi_LIBRARY` is `C:/Program Files (x86)/Microsoft SDKs/MPI/Lib/x64/msmpi.lib`
variable `MPI_CXX_HEADER_DIR` is `C:/Program Files (x86)/Microsoft SDKs/MPI/Include`

when the toolchain file is loaded

variable `MPI_msmpi_LIBRARY` is `C:/dev/vcpkg/installed/x64-windows/debug/lib/msmpi.lib`
variable `MPI_CXX_HEADER_DIR` is `C:/dev/vcpkg/installed/x64-windows/include`

When I investigate the portfile of msmpi I noticed that vcpkg is building msmpi from source itself. Why is it necessary? Why is it not like the cuda port where it just simply verify whether the installation was successful since msmpi is installed through manually double clicking `msmpisdk-8.1.msi` and `MSMpiSetup-8.1.exe`?

EDIT: This might be also related to the update on FindMPI.cmake in 3.10 as shown in https://cmake.org/cmake/help/v3.10/release/3.10.html

**Comment by danieltak** [comment]
Had this issue today that was described on #2323 , however, this issue is about another problem.

Had to install MSMPI manually to continue installing PCL.

**Comment by ras0219-msft** [comment]
Thanks for reporting this!

We don't build msmpi from source, but we do repackage it; this is to provide automatic linkage and `vcpkg export` functionality.

I'm able to reproduce your issue locally, so I'll take a look at how we can fix this.

**Comment by ras0219-msft** [comment]
Can you confirm that `find_package(MPI REQUIRED)` works _without_ vcpkg's integrate install? You can use `vcpkg integrate remove` to temporarily remove it, then `vcpkg integrate install` to restore.

**Comment by jasjuang** [comment]
@ras0219-msft Without or without `vcpkg integrate install` yields the same behavior for me.

If the toolchain file is not loaded everything works (`cmake -A x64 ..`)

If the toolchain file is loaded (`cmake -A x64 -C ..\initcmake ..`) the first time will succeed, but if I have the need to run `cmake -A x64 -C ..\initcmake ..` again the error will show up

**Comment by ras0219-msft** [comment]
I've pushed a fix to master that works on my machine -- could you try it and confirm?

**Comment by jasjuang** [comment]
It works now, thanks!
