### ISSUE TITLE
[boost-build] Build error ms fix ur trash

### ISSUE THREAD

**Issue by MSFixUrTrash** [microsoft/vcpkg#23170]
**Host Environment**
- OS: Sadly windows 
- Compiler: obviously msvc

**To Reproduce**
install windows

**Failure logs** 
Make Error at scripts/cmake/vcpkg_execute_required_process.cmake
Error: Building package boost-build:x64-windows failed with: BUILD_FAILED 

**Additional context**
uninstall windows

ms fix ur trash

**Comment by PhoebeHui** [comment]
@MSFixUrTrash, could you please provide us the full failure logs?

**Comment by Neumann-A** [comment]
@PhoebeHui I wonder why you didn't directly close the issue. It is obvious that the person who made the issue has no interest in helping in any way. The person also used a throw away account. Personally I think such issues should be closed on the spot.

**Comment by Adela0814** [comment]
@MSFixUrTrash We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
