### ISSUE TITLE
[libpq] Build error

### ISSUE THREAD

**Issue by jyr19910218** [microsoft/vcpkg#23199]
Error: Building package libpq:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libpq
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[libpq]+Build+error
including:
  package: libpq[core,openssl,zlib]:x86-windows -> 12.9#1
    vcpkg-tool version: 2022-02-11-dac008bf9b55ef48e10bcc81e273b97a82bbf72d
    vcpkg-scripts version: 5cf60186a 2022-02-18 (2 days ago)

**Comment by dg0yt** [comment]
For building libpq with openssl, cf. #22516.
