### ISSUE TITLE
Building package aws-sdk-cpp:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by ryan-motive** [microsoft/vcpkg#23190]
**Describe the bug**
Following instructions step-by-step for vcpkg and aws-sdk-cpp.
.\vcpkg\vcpkg install "aws-sdk-cpp[lexv2-runtime]" fails with this error

**Environment**
- Windows 11

**To Reproduce**
1. .\vcpkg\vcpkg install "aws-sdk-cpp[lexv2-runtime]"
2. See error

**Expected behavior**
Not this

**Failure logs** 
```
CMake Error: Problem with archive_write_header(): Can't create '\\?\C:\Dev\vcpkg\vcpkg\buildtrees\aws-sdk-cpp\src\7237798297-e0c81eb359.clean.tmp\aws-sdk-cpp-26fa78673ec93dc703e80b741d8b437237798297\aws-cpp-sdk-ebs\include\aws\ebs\model\AccessDeniedException.h'
CMake Error: Current file: aws-sdk-cpp-26fa78673ec93dc703e80b741d8b437237798297/aws-cpp-sdk-ebs/include/aws/ebs/model/AccessDeniedException.h
CMake Error: Problem extracting tar: C:/Dev/vcpkg/vcpkg/downloads/aws-aws-sdk-cpp-26fa78673ec93dc703e80b741d8b437237798297.tar.gz
```
**Additional context**
Very vanilla installation and followed instructions step-by-step. Diagnostics were not helpful.

**Comment by ryan-motive** [comment]
Additional info from the console:

  package: aws-sdk-cpp[core,dynamodb,kinesis,lexv2-runtime,s3]:x86-windows -> 1.9.160
    vcpkg-tool version: 2022-02-11-dac008bf9b55ef48e10bcc81e273b97a82bbf72d
    vcpkg-scripts version: 5cf60186a 2022-02-18 (2 days ago)

**Comment by ryan-motive** [comment]
Managed to hack my way past that because the "model" folder was somehow corrupt. Tried again (also as admin), but now hitting this:

CMake Error at scripts/cmake/vcpkg_extract_source_archive.cmake:236 (file):
  file RENAME failed to rename

    C:/Dev/vcpkg/vcpkg/buildtrees/aws-sdk-cpp/src/7237798297-e0c81eb359.clean.tmp/aws-sdk-cpp-26fa78673ec93dc703e80b741d8b437237798297

  to

    C:/Dev/vcpkg/vcpkg/buildtrees/aws-sdk-cpp/src/7237798297-e0c81eb359.clean

  because: Access is denied.

**Comment by JackBoosY** [comment]
This issue was fixed by PR https://github.com/microsoft/vcpkg-tool/pull/361 and this issue will be resolved by PR https://github.com/microsoft/vcpkg/pull/23162.
