### ISSUE TITLE
To restrictive support expressions for arm64-osx 

### ISSUE THREAD

**Issue by autoantwort** [microsoft/vcpkg#23207]
The following ports have a to restrictive supports expression (list probably contains false positives) 
- [ ] PASSING, Adapt support expression: akali:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: ashes:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: asiosdk:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: asmjit:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: irrlicht:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: atk:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: aws-c-common:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: aws-c-cal:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: aws-c-compression:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: aws-c-io:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: aws-c-http:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: aws-c-auth:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: aws-checksums:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: aws-c-event-stream:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: aws-c-mqtt:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: aws-c-s3:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: aws-crt-cpp:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: aws-sdk-cpp:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: bext-wintls:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: blitz:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: boost-coroutine:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: boost-fiber:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: camport3:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: chromium-base:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: clamav:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: clblast:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: coin:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: commsdsl:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: cppad:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: cppxaml:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: cpuid:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: directx-headers:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: dav1d:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: discord-game-sdk:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: eathread:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: faiss:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: farmhash:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: fbthrift:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: ffnvcodec:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: flash-runtime-extensions:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: onednn:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: freerdp:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: g3log:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: gamedev-framework:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: gasol:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: gperftools:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: pangomm:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: ignition-msgs5:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: ignition-msgs6:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: kfr:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: knet:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: krabsetw:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: launch-darkly-server:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: libgo:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: x265:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: libhv:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: libigl:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: libmicrohttpd:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: libressl:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: libsecret:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: libssh:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: libu2f-server:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: libuvc:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: lzfse:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: mecab:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: mimalloc:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: mnn:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: munit:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: murmurhash:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: networkdirect-sdk:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: nnpack:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: ocilib:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: ois:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: onnxruntime-gpu:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: opencc:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: opensubdiv:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: pbc:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: qt5-doc:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: raylib:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: rsm-binary-io:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: rsm-mmio:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: ryu:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: soqt:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: starlink-ast:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: superlu:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: v-hacd:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: vc:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: vcpkg-gfortran:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: vs-yasm:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: vtk-m:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: wavpack:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: winlamb:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: winreg:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: x-plane:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: xbyak:arm64-osx (Support expression says unsupported, but the port builds)
- [ ] PASSING, Adapt support expression: yasm:arm64-osx (Support expression says unsupported, but the port builds)

**Comment by Neumann-A** [comment]
> PASSING, Adapt support expression: vs-yasm:arm64-osx (Support expression says unsupported, but the port builds)

probably not. Since that is MSBuild integration of yasm
