### ISSUE TITLE
boost-build_x64-windows build failure

### ISSUE THREAD

**Issue by the-overdriven** [microsoft/vcpkg#23204]
**Host Environment**
- OS: Windows 10
- Compiler: newest

**To Reproduce**
`.\vcpkg install --triplet x64-windows boost-iostreams boost-asio boost-system boost-filesystem boost-variant boost-lockfree luajit libmariadb pugixml cryptopp fmt`

**Failure logs** 
```
vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine>dir *.exe 
 Volume in drive C has no label.
 Volume Serial Number is EEFA-254A

 Directory vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine


vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine>copy /b .\b2.exe .\bjam.exe 
The system cannot find the file specified.

Failed to build the B2 engine.
```

There are no exe files in **vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine**

I guess installator commands are outdated.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Did you use latest VCPKG to install `boost-build`? Now the latest version of `boost-build` is **1.78.0#1**. There are `b2.exe` and `bjam.exe` in _VCPKG_ROOT/packages/boost-build_x64-windows/tools/boost-build/src/engine_.
![image](https://user-images.githubusercontent.com/94091114/155082151-60b95a3a-419b-488f-ac47-667030d0f8b7.png)

**Comment by LilyWangLL** [comment]
Ping @the-overdriven for response.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. If this issue has new message, please reopen this issue.
