### ISSUE TITLE
[spirv-tools] SPIRV-ToolsConfig.cmake tries to set property on non existent target when used with find_package()

### ISSUE THREAD

**Issue by wrosecrans** [microsoft/vcpkg#23209]
****

shaderc depends on spirv-tools so this originally came up for me while hacking on the issues that I filed as issue #23208 but is separate.

I vaguely speculate that this is not unrelated to issue #18612 but I am getting a different behavior, so filing it as a separate issue.  That issue is about a missing file.  This one about a missing target.

When I find_package(spirv-tools) from another project to use it after it is installed, I get this in my CMake configure output:

CMake Warning (dev) at V:/installed/x64-windows/share/SPIRV-Tools/SPIRV-ToolsConfig.cmake:3 (get_target_property):
  Policy CMP0045 is not set: Error on non-existent target in
  get_target_property.  Run "cmake --help-policy CMP0045" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  get_target_property() called with non-existent target "SPIRV-Tools".
Call Stack (most recent call first):
  V:/scripts/buildsystems/vcpkg.cmake:793 (_find_package)
  CMakeLists.txt:21 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

**Proposed solution**
Someone with a deeper understanding than me of CMake install/export/config stuff should examine it.  The "-config" files are all autogenerated, so it isn't useful for me to try and hack a diff on it directly.  It needs to be fixed indirectly at a higher level of abstraction.

Ideally, there should probably be some sort of CI/automation around attempting to consume every package to validate that it is useful/correct and not shouting warnings when consumed.  Both this and my previous issue about shaderc involve packages that appear to have 100% successful package installs, but still have issues with actually being consumed.  I'd guess that most every package that can be installed with ".\vcpkg install foo" should be possible to "find_package( foo CONFIG REQUIRED)" unless somebody specifies otherwise and provides some test example of consuming the package in another way?

**Comment by Adela0814** [comment]
There's some upstream work in SPIRV-Tools [#3781](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3781)  to fix their build options. we can wait for upstream fix first.

**Comment by Adela0814** [comment]
@wrosecrans  #23269 may fixed this issue, could you please get the latest vcpkg version and try again.

**Comment by wrosecrans** [comment]
Thanks for the update.  I should be able to make time take a closer look at this over the weekend.

**Comment by Adela0814** [comment]
@wrosecrans  any updates?

**Comment by Adela0814** [comment]
This issue hasn’t been updated in a long time; if it is still an issue, please reopen this issue.
