### ISSUE TITLE
[lz4] Build error

### ISSUE THREAD

**Issue by jackyoung003** [microsoft/vcpkg#23206]
**Host Environment**
- OS: Windows 10
- Compiler: Visual Studio

**To Reproduce**
`./vcpkg install xxxx`

**Failure logs** 
  package: lz4[core]:x64-windows -> 1.9.3#3
    vcpkg-tool version: 2022-02-11-dac008bf9b55ef48e10bcc81e273b97a82bbf72d
    vcpkg-scripts version: 5cf60186a 2022-02-18 (3 days ago)
-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by JonLiu1993** [comment]
@jackyoung003 ,Thanks for posting this issue, could you please provide the error log?

**Comment by JonLiu1993** [comment]
@jackyoung003 ,Ping for response!

**Comment by JonLiu1993** [comment]
Thanks for posting this issue. Please reopen this issue if it still be a problem for you.
