### ISSUE TITLE
[gainput] build failure

### ISSUE THREAD

**Issue by binfengxueqian** [microsoft/vcpkg#23216]
**Host Environment**
- OS: Linux
- Compiler: gcc7

**To Reproduce**
`./vcpkg install gainput`

**Failure logs** 
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
    Command failed: /home/craipy/vcpkg-2021.05.12/downloads/tools/cmake-3.20.2-linux/cmake-3.20.2-linux-x86_64/bin/cmake /home/craipy/vcpkg-2021.05.12/buildtrees/gainput/src/v1.0.0-52a00a4a7c.clean -DGAINPUT_BUILD_SHARED=OFF -DGAINPUT_BUILD_STATIC=ON -DGAINPUT_TESTS=OFF -DGAINPUT_SAMPLES=OFF -DCMAKE_MAKE_PROGRAM=/home/craipy/vcpkg-2021.05.12/downloads/tools/ninja-1.10.1-linux/ninja -DCMAKE_SYSTEM_NAME=Linux -DBUILD_SHARED_LIBS=OFF -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/home/craipy/vcpkg-2021.05.12/scripts/toolchains/linux.cmake -DVCPKG_TARGET_TRIPLET=x64-linux -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=external -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=/home/craipy/vcpkg-2021.05.12/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_LINKER_FLAGS_RELEASE= -DVCPKG_LINKER_FLAGS_DEBUG= -DVCPKG_TARGET_ARCHITECTURE=x64 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -D_VCPKG_ROOT_DIR=/home/craipy/vcpkg-2021.05.12 -D_VCPKG_INSTALLED_DIR=/home/craipy/vcpkg-2021.05.12/installed -DVCPKG_MANIFEST_INSTALL=OFF -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/home/craipy/vcpkg-2021.05.12/packages/gainput_x64-linux/debug
    Working Directory: /home/craipy/vcpkg-2021.05.12/buildtrees/gainput/x64-linux-dbg
    Error code: 1
    See logs for more information:
      /home/craipy/vcpkg-2021.05.12/buildtrees/gainput/config-x64-linux-dbg-out.log
      /home/craipy/vcpkg-2021.05.12/buildtrees/gainput/config-x64-linux-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:332 (vcpkg_execute_required_process)
  ports/gainput/portfile.cmake:22 (vcpkg_configure_cmake)
  scripts/ports.cmake:142 (include)

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by JackBoosY** [comment]
Pleae provide the following logs:
/home/craipy/vcpkg-2021.05.12/buildtrees/gainput/config-x64-linux-dbg-out.log
/home/craipy/vcpkg-2021.05.12/buildtrees/gainput/config-x64-linux-dbg-err.log

**Comment by binfengxueqian** [comment]
> Pleae provide the following logs: /home/craipy/vcpkg-2021.05.12/buildtrees/gainput/config-x64-linux-dbg-out.log /home/craipy/vcpkg-2021.05.12/buildtrees/gainput/config-x64-linux-dbg-err.log

[config-x64-linux-dbg-err.log](https://github.com/microsoft/vcpkg/files/8114162/config-x64-linux-dbg-err.log)
[config-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/8114163/config-x64-linux-dbg-out.log)

**Comment by JackBoosY** [comment]
```
CMake Error at CMakeLists.txt:16 (if):
  if given arguments:

    "LESS" "6.1"

  Unknown arguments specified
```

`CMAKE_SYSTEM_VERSION` is empty which caused this issue.

**Comment by dg0yt** [comment]
... and "6.1" would ask for `VERSION_LESS`.

**Comment by binfengxueqian** [comment]
Thank you so much!
I have installed gainput successfully.
I add the following to vcpkg/triplets/x64-linux.cmake
`set(VCPKG_CMAKE_SYSTEM_VERSION 20.2)`
