### ISSUE TITLE
[New Port Request] zlib-ng

### ISSUE THREAD

**Issue by FriskTheFallenHuman** [microsoft/vcpkg#23215]
Library name: zlib-ng

Library description: zlib data compression library for the next generation systems

Source repository URL: https://github.com/zlib-ng/zlib-ng

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
zlib-ng is ABI compatible  with zlib, just like libjpeg-turbo, it needs to be compile it with `ZLIB_COMPAT`

**Comment by JonLiu1993** [comment]
@FriskTheFallenHuman ,Thanks for posting this issue, vcpkg already have zlib-ng port, Please use "git pull" update your vcpkg and  use, Thanks!
