### ISSUE TITLE
[tesseract] update to <5.0.1>

### ISSUE THREAD

**Issue by bakashigure** [microsoft/vcpkg#23210]
Library name: `tesseract`

New version number: `5.0.1`

Other information that may be useful (release notes, etc...)
https://github.com/tesseract-ocr/tesseract/releases/tag/5.0.1

**Comment by wrosecrans** [comment]
FYI, there is a draft PR for updating Tesseract already started, PR #23101 if you want to take a look at it.

**Comment by JonLiu1993** [comment]
Duplicate of #16019
