### ISSUE TITLE
Bootstrap stuck

### ISSUE THREAD

**Issue by TooYoungTooSimp** [Microsoft/vcpkg#2321]
When I running `bootstrap-vcpkg.bat`, It doesn't even try to download anything. (No `Downloading $Dependency...` shows in the verbosity mode)
After a short examining, I tried to delete these lines:
[https://github.com/Microsoft/vcpkg/blob/master/scripts/VcpkgPowershellUtils.ps1#L131]() to [https://github.com/Microsoft/vcpkg/blob/master/scripts/VcpkgPowershellUtils.ps1#L149]()
![image](https://user-images.githubusercontent.com/6648049/33720437-e4b95328-db9e-11e7-8a2b-37090e623cac.png)
After completely bypass BITS, everything starts to work fine.

**Comment by alexkaratarakis** [comment]
@TooYoungTooSimp 
What is your OS?
Also, what is your powershell version? (type `PSVer$PSVersionTable.PSVersion` in powershell to find this).

**Comment by TooYoungTooSimp** [comment]
Windows 1709 16299.64
PSVer 
![image](https://user-images.githubusercontent.com/6648049/33750375-8e350324-dc0e-11e7-86af-e1a26fcf1074.png)

**Comment by alexkaratarakis** [comment]
In 3390007020921b41e3d4d42ad9b46c671250743a, I have removed usage of BITS Transfer.
Can you try latest master to see if your issue is resolved?

**Comment by TooYoungTooSimp** [comment]
It works well now.
Thank you.
