### ISSUE TITLE
[vcpkg-tool] Consider passing-through GIT_ASKPASS env variable by default

### ISSUE THREAD

**Issue by horenmar** [microsoft/vcpkg#23225]
**Is your feature request related to a problem? Please describe.**
We are using private repository and private packages, and this requires vcpkg to properly auth against private git repos. We use `GIT_ASKPASS` to tell git what to use for the auth, and ran into issue where vcpkg would strip away `GIT_ASKPASS` from the env that the package is being built in (and thus stopping git from being able to download the private repo).

I suggest that vcpkg automatically passes-through `GIT_ASKPASS` environment variable to avoid these issues.

Also an interesting note, adding `set(VCPKG_ENV_PASSTHROUGH_UNTRACKED "GIT_ASKPASS")` to the triplet didn't work, even though by my reading of the docs it should. We had to add `VCPKG_KEEP_ENV_VARS=GIT_ASKPASS` to the environment.

**Comment by petr-tichy** [comment]
See https://github.com/microsoft/vcpkg/pull/23226

**Comment by JackBoosY** [comment]
I think #23226 can resolve this.

**Comment by horenmar** [comment]
@JackBoosY The linked PR adds a note to docs. This issue asks for vcpkg to automatically pass-through the env variable, because it is important for a common use case to work out of the box.

**Comment by horenmar** [comment]
Note that the tool release also makes [a part of docs](https://github.com/microsoft/vcpkg/blob/master/docs/users/authentication.md#pass-jenkins-gitusernamepassword-credentials) obsolete.

**Comment by horenmar** [comment]
The new tool release was done on Friday, should this be closed now?
