### ISSUE TITLE
VS project build get stuck/slowed down by vcpkg script

### ISSUE THREAD

**Issue by skthrowaway** [microsoft/vcpkg#2322]
When a project is being built, a script is executed, from buildsystems\msbuild\vcpkg.targets:

```
<Exec Condition="$(VcpkgConfiguration.StartsWith('Release'))"
      Command="$(SystemRoot)\System32\WindowsPowerShell\v1.0\powershell.exe -ExecutionPolicy Bypass -noprofile -File %22$(MSBuildThisFileDirectory)applocal.ps1%22 %22$(TargetPath)%22 %22$(VcpkgRoot)bin%22 %22$(TLogLocation)$(ProjectName).write.1u.tlog%22 %22$(IntDir)vcpkg.applocal.log%22"
      StandardOutputImportance="Normal">
    </Exec>
```

But for me, it often gets stuck, certain programs become unresponsive (Chrome stays in a black screen, Windows Explorer can't launch any process etc...), it's not a CPU high usage and every other app works, including VS. I usually cancel the build (which takes a few seconds to take in effect) and then I can retry a build and it will generally work.

It's been occurring since a few weeks but I expected it to be known and patched before, I hope this can be fixed as it is a really annoying bug.

**Comment by NancyLi1013** [comment]
This issue hasn’t been updated in a year; please update vcpkg and try it again. if it is still an issue, please reopen.
