### ISSUE TITLE
[gmp] Build error

### ISSUE THREAD

**Issue by yhl798999** [microsoft/vcpkg#23236]
**Host Environment**
- OS: [Windows 10]
- Compiler: msvc2019

**To Reproduce**
using vcpkg versioning to build cgal, which has a dependcy on gmp.
this is the vcpkg.json:
`{
    "name": "3dreconstructiondependencies",
    "version-semver": "1.0.0",
    "dependencies": [
        "cgal"
    ],
    "builtin-baseline":"3426db05b996481ca31e95fff3734cf23e0f51bc",
    "overrides": [
    ]
}`
it works well for the first time and create a vcpkg_installed folder at my build directory. Then I try to add more libs(eigen3..) to vcpkg.json, it will rebuild the gmp, and the error occurs:
`CMake Error at E:/test/3dreconstruction/build/vcpkg_installed/x64-windows/share/yasm-tool-helper/yasm-tool-helper.cmake:16 (message):
Cross-targetting and x64 ports requiring yasm require the x86-windows
yasm-tool to be available.  Please install yasm-tool:x86-windows first.`
I fellow the advice and install yasm-tool:x86-windows using power-shell and try again, but the error still exists, so I open the cmake file mentioned above  which reports  the error, and I found this:
` 
get_filename_component(YASM "${CURRENT_INSTALLED_DIR}/../x86-windows/tools/yasm-tool/yasm.exe" ABSOLUTE)
if(NOT EXISTS "${YASM}")
message(FATAL_ERROR "Cross-targetting and x64 ports requiring yasm require the x86-windows yasm-tool to be available. Please install yasm-tool:x86-windows first.")
`
the cmake will find yasm.exe from the CURRENT_INSTALLED_DIR, it will work well when using power-shell, but vcpkg versioning will create a local vcpkg_install at my project/build, so yasm.exe cannot be found.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. `yasm-tool` has been changed after commit `3426db05b996481ca31e95fff3734cf23e0f51bc`. The attached file is `cgal version 5.2`. You can use [overlay-ports](https://github.com/microsoft/vcpkg/blob/master/docs/specifications/ports-overlay.md) way to install it in your project. 
1. If you use cmake project, you need add `"cmakeCommandArgs": "-DCPKG_OVERLAY_PORTS=H:/Lily/cgal"` to **CMakeSettings.json.** The path is your `cgal` path.
2. If you use msbuild project, you can add `Additional Options` as the picture.
![image](https://user-images.githubusercontent.com/94091114/155298310-b46474ea-0eda-4f36-9fb4-b67d6b9e7430.png)
3. Remove "builtin-baseline":"3426db05b996481ca31e95fff3734cf23e0f51bc" in vcpkg.json
build project, it will install `cgal version 5.2`.

[cgal.zip](https://github.com/microsoft/vcpkg/files/8123375/cgal.zip)

**Comment by yhl798999** [comment]
I tried the overlay-ports ways, and the cgal was installed successfully, thank you!
