### ISSUE TITLE
[loguru] Add feature to link with fmt

### ISSUE THREAD

**Issue by mrlegohead0x45** [microsoft/vcpkg#23231]
**Is your feature request related to a problem? Please describe.**
Loguru supports string formatting with fmt via `#define LOGURU_USE_FMTLIB 1`. However, when trying to use this feature with non-header-only, it fails with linker error
``undefined reference to `loguru::vlog(int, char const*, unsigned int, char const*, fmt::v8::basic_format_args<fmt::v8::basic_format_context<fmt::v8::appender, char> >)'``, which I am guessing comes from the loguru binary not being linked to the fmt library when it is built.

**Proposed solution**
I suggest adding a feature to loguru that has a dependency on fmt and that will build loguru linked to fmt. I am already working on a solution on my [fork](https://github.com/mrlegohead0x45/vcpkg) and I will create a pr if people agree.

**Describe alternatives you've considered**
Use loguru with header only.

Also slightly off topic, but why is non-header-only not supported on Windows?

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Could you submit a PR to merge your fix?
