### ISSUE TITLE
[brotli] Build error

### ISSUE THREAD

**Issue by memuratozturk** [microsoft/vcpkg#23245]
**Host Environment**
- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**
`./vcpkg install xxxx`

**Failure logs** 
-Cut and paste the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

Error: Building package brotli:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+brotli
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[brotli]+Build+error
including:
  package: brotli[core]:x64-windows -> 1.0.9#2
    vcpkg-tool version: 2022-02-11-dac008bf9b55ef48e10bcc81e273b97a82bbf72d
    vcpkg-scripts version: daa7215f3 2022-02-22 (19 hours ago)

Additionally, attach any relevant sections from the log files above.

**Comment by memuratozturk** [comment]
I tried and I get that error on my windows 10 latest update pc.

Error: Building package brotli:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+brotli
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[brotli]+Build+error
including:
  package: brotli[core]:x64-windows -> 1.0.9#2
    vcpkg-tool version: 2022-02-11-dac008bf9b55ef48e10bcc81e273b97a82bbf72d
    vcpkg-scripts version: daa7215f3 2022-02-22 (19 hours ago)

Additionally, attach any relevant sections from the log files above.

**Comment by JonLiu1993** [comment]
@memuratozturk ,Thanks for posting this issue, could you plesae provide the error log?

**Comment by JonLiu1993** [comment]
@memuratozturk ,Ping for response!

**Comment by JonLiu1993** [comment]
Thanks for posting this issue. Please reopen this issue if it still be a problem for you.
