### ISSUE TITLE
[cppwinrt] update to 2.0.220131.2

### ISSUE THREAD

**Issue by davidmatson** [microsoft/vcpkg#23249]
Library name:
cppwinrt

New version number:
2.0.220131.2

Other information that may be useful (release notes, etc...)
The current port is a no-op, saying to get the code from the Windows SDK. But the Windows SDK version is an old version - the latest is on GitHub as a source and NuGet package release:
https://github.com/microsoft/cppwinrt/releases/tag/2.0.220131.2

I'm not sure what it would take to get the actual cppwinrt tool working properly with vcpkg, and no longer pointing to the old version in the Windows SDK instead.

**Comment by FrankXie05** [comment]
@davidmatson Thanks for posting this issue, Since the PR https://github.com/microsoft/vcpkg/pull/14092, this port has been changed to be empty. I'm closing this issue, as it doesn't need updating.

**Comment by davidmatson** [comment]
@FrankXie05 - what's the right way to track requesting a non-empty port?

Thanks,

David

**Comment by JackBoosY** [comment]
This port depends on the Windows SDK, so if you have a newer Windows SDK installed and remove-reinstall this port.
It will be updated to the latest.

**Comment by davidmatson** [comment]
I believe C++/WinRT recommends not using the Windows SDK version because it's older and recommend using what's available from NuGet releases instead.

**Comment by JackBoosY** [comment]
@davidmatson Can you provide some links to prove it please?

**Comment by davidmatson** [comment]
https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/intro-to-using-cpp-with-winrt#sdk-support-for-cwinrt

    Although it is now present only for compatibility reasons, as of version 10.0.17134.0 (Windows 10, version 1803), the Windows SDK contains a header-file-based standard C++ library for consuming first-party Windows APIs (Windows Runtime APIs in Windows namespaces). Those headers are inside the folder %WindowsSdkDir%Include<WindowsTargetPlatformVersion>\cppwinrt\winrt. As of the Windows SDK version 10.0.17763.0 (Windows 10, version 1809), these headers are generated for you inside your project's $(GeneratedFilesDir) folder.

    Again for compatibility, the Windows SDK also comes with the cppwinrt.exe tool. However, we recommend that you instead install and use the most recent version of cppwinrt.exe, which is included with the Microsoft.Windows.CppWinRT NuGet package. That package, and cppwinrt.exe, are described in the sections above.

**Comment by kennykerr** [comment]
See also https://github.com/microsoft/vcpkg/pull/14092#issuecomment-1050332234

**Comment by walbourn** [comment]
https://github.com/microsoft/vcpkg/pull/24967
