### ISSUE TITLE
Differences between vcpkg_configure_cmake and vcpkg_cmake_configure

### ISSUE THREAD

**Issue by sandercox** [microsoft/vcpkg#23248]
**Describe the bug**

In PR #18156 I fixed some architecture handling in both these files. My understanding is that `vcpkg_cmake_configure` is the new method moving forward.

In PR #20885 I notice that the scrips of `vcpkg_configure_cmake` has been audited and much of our changes have been replaced by using `vcpkg_list` commands instead of regular CMake `list` commands.

Is this now just waiting for vcpkg_cmake_configure to be audited as well? Or should I just make a PR for changing this and keeping these parts of the code the same?

**Comment by JackBoosY** [comment]
Please feel free to open a PR for script audit, these two functions should be in sync.
