### ISSUE TITLE
[cudnn] Build error

### ISSUE THREAD

**Issue by MollyHoo** [microsoft/vcpkg#23251]
package: cudnn[core]:x64-windows-release -> 7.6.5#4
    vcpkg-tool version: 2022-02-11-dac008bf9b55ef48e10bcc81e273b97a82bbf72d
    vcpkg-scripts version: 7249fa4d6 2022-02-23 (7 hours ago)

**Comment by JackBoosY** [comment]
Please provide the full failure output first.

**Comment by cenit** [comment]
note that cudnn is only searching for a package that must be installed manually by the user!
we cannot redistribute cudnn anymore

**Comment by JackBoosY** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
