### ISSUE TITLE
[OpenCL] Update to version 3.0

### ISSUE THREAD

**Issue by HWiman-ICONIC** [microsoft/vcpkg#23254]
We´d like to be able to state ```target_compile_definitions(IconicGpu PUBLIC CL_TARGET_OPENCL_VERSION=300)``` (or even better not stating anything would result in PUBLIC CL_TARGET_OPENCL_VERSION=300 by default) in our builds, but that results in 

```cl_version: CL_TARGET_OPENCL_VERSION is not a valid value (100, 110, 120, 200, 210, 220). Defaulting to 220 (OpenCL 2.2)```

OpenCL 3.0 is already quite old and is additionally "making a step forward by taking a step backwards" meaning that it puts less requirements on OpenCL implementations. Thus upgrading to 3.0 will broaden the number of available platforms. 

The latest[ cl_version.h ](https://github.com/KhronosGroup/OpenCL-Headers/blob/master/CL/cl_version.h) has 300 as default.

E.g. my laptop´s both GPU:s (Intel+NVidia) and CPU (Intel) support 3.0, but using current vcpkg I can only check for versions up to 2.2:
```Platform: Intel(R) OpenCL HD Graphics
Device: Intel(R) UHD Graphics 630
Vendor: Intel(R) Corporation
Version: OpenCL 3.0 NEO
Compute units: 23
Global memory: 3356807168

Platform: NVIDIA CUDA
Device: NVIDIA GeForce GTX 1660 Ti with Max-Q Design
Vendor: NVIDIA Corporation
Version: OpenCL 3.0 CUDA
Compute units: 24
Global memory: 6442123264

Platform: Intel(R) OpenCL
Device: Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
Vendor: Intel(R) Corporation
Version: OpenCL 3.0 (Build 0)
Compute units: 8
Global memory: 8392019968 ```

**Comment by k06a** [comment]
Wen merge?
