### ISSUE TITLE
Error: aws-sdk-cpp[core] is only supported on '!arm & !uwp'

### ISSUE THREAD

**Issue by hefengliang** [microsoft/vcpkg#23257]
arm ubuntu18

./vcpkg version
Vcpkg package management program version 2999-12-31-unknownhash

./vcpkg install aws-sdk-cpp[s3]
Error: aws-sdk-cpp[core] is only supported on '!arm & !uwp'

**Comment by hefengliang** [comment]
Does aws-sdk-cpp not support ARM platform?

**Comment by FrankXie05** [comment]
@hefengliang Thanks for posting this issue, yes `aws-sdk-cpp` currently does not support arm platform builds。https://github.com/microsoft/vcpkg/blob/febf337ad89f7fe975c40f00a803015e2445ec54/ports/aws-sdk-cpp/vcpkg.json#L7

**Comment by autoantwort** [comment]
You can run the install command with `--allow-unsupported`

**Comment by autoantwort** [comment]
According to https://discord.com/channels/400588936151433218/687365466422902841/945714222388625459 the support expression is wrong

**Comment by hefengliang** [comment]
@autoantwort  Thank you very much, I compiled successfully in ubuntu18 arm according to your method.

**Comment by JackBoosY** [comment]
```json
"supports": "!(arm & windows) & !uwp"
```

We should also check whether arm-windows is supported.

**Comment by FrankXie05** [comment]
Fix by PR #23278
