### ISSUE TITLE
openssl install error

### ISSUE THREAD

**Issue by bitsrules** [Microsoft/vcpkg#2327]
openssl can't install because of the file is not saved in in unicode format.

.\ssl\bad_dtls_test.c: error C2220: warning treated as error - no 'object' file generated
.\ssl\bad_dtls_test.c: warning C4819: The file contains a character that cannot be represented in the current code page (932). Save the file in Unicode format to prevent data loss

Starting package 3/6: openssl:x86-windows
Building package openssl:x86-windows...
-- CURRENT_INSTALLED_DIR=C:/Users/lars.schouw/dev/vcpkg/installed/x86-windows
-- DOWNLOADS=C:/Users/lars.schouw/dev/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/Users/lars.schouw/dev/vcpkg/packages/openssl_x86-windows
-- CURRENT_BUILDTREES_DIR=C:/Users/lars.schouw/dev/vcpkg/buildtrees/openssl
-- CURRENT_PORT_DIR=C:/Users/lars.schouw/dev/vcpkg/ports/openssl/.
-- Using cached C:/Users/lars.schouw/dev/vcpkg/downloads/openssl-1.0.2n.tar.gz

Similar issue here : https://bz.apache.org/ooo/show_bug.cgi?id=87098

**Comment by alexkaratarakis** [comment]
Aha! Same issue as here:
https://github.com/Microsoft/vcpkg/issues/2334
Please try the workaround in that bug.
(Closing this as duplicate, please continue discussion there)
