### ISSUE TITLE
vcpkg install error:in triplet x64-windows: Unable to find a valid Visual Studio instance Could not locate a complete Visual Studio instance

### ISSUE THREAD

**Issue by chetan-2002** [microsoft/vcpkg#23275]
Basically, I was having an error while downloading a c package through vcpkg.
This was the first time I was trying to download an external c package.

The series of commands i ran :
1) cd C:
2) git clone https://github.com/microsoft/vcpkg
3) .\vcpkg\bootstrap-vcpkg.bat
4) .\vcpkg\vcpkg integrate install
5) .\vcpkg\vcpkg install curl

This is the error I am getting.

![image](https://user-images.githubusercontent.com/77783033/155708856-ad476d7b-335f-4172-8450-dba7ec76068a.png)

Can anyone help me with how can I solve this issue?

**Comment by Adela0814** [comment]
Please check the following in your machine:

1. The language pack of VS is `English`:

![image](https://user-images.githubusercontent.com/95600143/155930156-5a81c2f5-d330-4ff1-9f55-32c8351f8cd8.png)

2. Please make sure you have downloaded `c++ component`:

![image](https://user-images.githubusercontent.com/95600143/155930268-990a9d03-9ef6-4563-8d76-e55b31c6fc3f.png)

3. Do you have anti-virus software locally?

**Comment by chetan-2002** [comment]
Thanks, @Adela0814 for your help, My issue is resolved now. Once again thanks for the help.
