### ISSUE TITLE
[termcolor] update to NULL

### ISSUE THREAD

**Issue by playday3008** [microsoft/vcpkg#23287]
Library name: termcolor

New version number: The author of the repository did not create a release and therefore there is no new version, but there is a very important thing in the commits

Other information that may be useful (release notes, etc...)
https://github.com/ikalnytskyi/termcolor

**Comment by FrankXie05** [comment]
@playday3008 Thanks for posting this issue, I see your upstream contributions, we won't update to master unless upstream needs to do so, but I will make a patch on the latest version to apply your changes and remove the patch in the next version.  :)
