### ISSUE TITLE
boost regex linker error

### ISSUE THREAD

**Issue by bitsrules** [Microsoft/vcpkg#2328]
When I link with boost I get a linker error from symbols that have been added in boost 1_61_1

error LNK2019: unresolved external symbol "__declspec(dllimport) char __cdecl boost::re_detail_106501::do_global_lower(char)" (__imp_?do_global_lower@re_detail_106501@boost@@YADD@Z) referenced in function "char __cdecl boost::re_detail_106501::global_lower<char>(char)" (??$global_lower@D@re_detail_106501@boost@@YADD@Z)

error LNK2019: unresolved external symbol "__declspec(dllimport) char __cdecl boost::re_detail_106501::do_global_upper(char)" (__imp_?do_global_upper@re_detail_106501@boost@@YADD@Z) referenced in function "char __cdecl boost::re_detail_106501::global_upper<char>(char)" (??$global_upper@D@re_detail_106501@boost@@YADD@Z)

**Comment by JackBoosY** [comment]
Hi @bitsrules , thanks for post this issue!
Currently, boost-regex has been updated to version 1.69.0 and this error does not appear in the latest version.
Can you update your vcpkg and repro it?
Thx.
