### ISSUE TITLE
[python3:x86-windows-static] Linker issue when building in Release mode in Visual Studio

### ISSUE THREAD

**Issue by 1999lucnguyen** [microsoft/vcpkg#23288]
I am new to vcpkg (and C++ in general), so apologies if I get some terminology wrong.

**Host Environment**
- OS: Windows
- Compiler: Microsoft Visual Studio Community 2019 Version 16.9.2
- Package version: python3:x86-windows-static 3.10.1#6

**To Reproduce**
1. `./vcpkg install python3:x86-windows-static` (works correctly)
2. `./vcpkg integrate install` (works correctly)
3. Create a Visual Studio C++ Console app
4. In Project > Properties > vcpkg, set "Use Static Libraries" to "Yes".
5. Build the following code ***in Release x86*** (fails!):
```
#include <iostream>
#include <python3.10/Python.h>

int* main()
{
    Py_Initialize();
    PyRun_SimpleString("print('hi')");
    Py_Finalize();
    _Py_NoneStruct; // Note this seemingly random symbol!
}
```

You will get linker errors:
```
LNK2005	_Py_Finalize already defined in python.lib(python.exe)
LNK2005	_Py_Initialize already defined in python.lib(python.exe)
LNK2005	_PyRun_SimpleStringFlags already defined in python.lib(python.exe)	
```

**Failure logs** 
Relevant linker logs:
```
Searching C:\vcpkg\installed\x86-windows-static\lib\python.lib:
  Found _Py_Finalize
    Referenced in pythontest.obj
    Loaded python.lib(python.exe)
  Found _Py_Initialize
    Referenced in pythontest.obj
    Loaded python.lib(python.exe)
  [...]
[...]
Searching C:\vcpkg\installed\x86-windows-static\lib\python310.lib:
  Found __Py_NoneStruct
    Referenced in pythontest.obj
    Loaded python310.lib(object.obj)
  [...]
  python310.lib(pylifecycle.obj) : error LNK2005: _Py_Finalize already defined in python.lib(python.exe)
  python310.lib(pylifecycle.obj) : error LNK2005: _Py_Initialize already defined in python.lib(python.exe)
```

**Additional context**
In the sample code, notice the random `_Py_NoneStruct` (without it, the linker will not error). From what I understand, there are two `lib` files: `python.lib` and `python310.lib`, where `python.lib` contains only "key" functions, while `python310.lib` contains the full library (i.e., `python.lib` is a subset of `python310.lib`). When the linker searches for the symbols `Py_Initialize`, `PyRun_SimpleString`, and `Py_Finalize`, it will first search in `python.lib` (since it comes before `python310.lib` alphabetically) and find them there (since these are "key" functions). However, `_Py_NoneStruct` is not defined in `python.lib`, so the linker will search further and eventually find `python310.lib`. When searching this lib, the linker will error as it will notice that it defines many of the symbols it had already found in `python.lib` [1].

Before someone says I should not use `_Py_NoneStruct` directly: my actual program does not use it directly. Rather, it uses `Py_RETURN_NONE`, which is a macro that when expanded, refers to `_Py_NoneStruct`. In any case, this linker error should happen whenever there is a reference to a symbol that is only defined in the "complete" `python310.lib` lib file.

Further, if you build this in ***Debug x86*** mode, the linker will *not* error. I believe this is because the names of the `lib` files for the Debug mode are `python_d.lib` and `python310_d.lib` instead. With these names, the "complete" lib file `python310_d.lib` actually comes first alphabetically. So the linker will first search that `lib` file, and find all the symbols needed, and will not need to search `python_d.lib`.

Thank you so much!

[1] I actually have no idea if that is actually how the linker works, but this theory seems to correctly predict the outcomes, and I hope it can help debug this issue.

**Comment by JackBoosY** [comment]
Confirmed.

**Comment by 1999lucnguyen** [comment]
Thank you so much for fixing this! I have an additional question, please let me know if I should open another bug (or if it's not a bug at all). Since upgrading my python package, my builds have been much slower. It says:
```
Previous IPDB not found, fall back to full compilation.
```
Is there any way to generate an "IPDB" as per the warning?

**Comment by JackBoosY** [comment]
This is related to `/LTCG` in your custom project, please enable this in your project configuration, see https://docs.microsoft.com/en-us/cpp/build/reference/ltcg-link-time-code-generation?view=msvc-170.

**Comment by 1999lucnguyen** [comment]
Thank you for the reply. My project is already set to `/LTCG:incremental` by default. Changing it to `/LTCG` (or anything else) removes the warning, but the builds are still slow. The only way for me to get my previous build speed is setting it to the deafult value of `/LTCG:incremental`, and moving back the `python.lib` file from `.../lib/manual-link` to `../lib` (and obviously, building in Debug x86, as per the bug in the OP, otherwise it fails to build).
