### ISSUE TITLE
[boost-build] Build error

### ISSUE THREAD

**Issue by Nosenzor** [microsoft/vcpkg#23307]
**Host Environment**
- OS: Windows 10
- Compiler: revision
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\bin\Hostx64\x64\cl.exe
**To Reproduce**
`./vcpkg install boost

**Failure logs** 
 package: boost-build[core]:x64-windows -> 1.78.0#1
    vcpkg-tool version: 2022-02-24-7efe7f2b04912a7d674f86a406f9f2711c0221c6
    vcpkg-scripts version: 1b1ae50e1 2022-02-25 (31 hours ago)

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by JackBoosY** [comment]
Please provide the full output.

Thanks.

**Comment by JackBoosY** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
