### ISSUE TITLE
VCPKG lacks support for older, but still supported major library versions

### ISSUE THREAD

**Issue by Febbe** [microsoft/vcpkg#23303]
****

**Is your feature request related to a problem? Please describe.**
Our issue is, that our application is based on gtk+3.X. Since vcpkg only supports the latest library versions. Therefore, we can't use vcpkg (using an old vcpkg version is not feasible, because security updates of other deps are also rolled back).
Also, we want to port to gtk4 for newer versions, but still support the old gtk3 app for some time.
Switching between vcpkg configurations is problematic, too.

**Proposed solution**
It should be possible, to choose a version which can be installed in parallel to the newest version. Like
`vcpkg --install <pkg> --version <major[.minor[.patch]]>`.   
VCPKG should then follow the newest subversion. E.g. choosing 3.<latest minor> for a major version of 3.

**Describe alternatives you've considered**
 - Use conan.   
 - Compile manually (Yikes).
 - checkout old vcpkg (dangerous)

**Comment by dg0yt** [comment]
Alternative No. 1: Use vcpkg manifest mode.

**Comment by Neumann-A** [comment]
Alternative No. 2: Use an overlay port for gtk

**Comment by Cheney-W** [comment]
manifest mode: https://github.com/microsoft/vcpkg/blob/master/docs/users/manifests.md
overlay port: https://github.com/microsoft/vcpkg/blob/master/docs/specifications/ports-overlay.md
