### ISSUE TITLE
[tensorflow-cc] Build error - Memory limitations cause confusing failure, non-generalizable fix

### ISSUE THREAD

**Issue by duskvirkus** [microsoft/vcpkg#23300]
Maybe related to #20124 or #18500

**Host Environment**
- OS: Ubuntu 20.04 (x86_64 Linux 5.13.0-30-generic)
- Compiler: gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
- Important: 16gb memory

**To Reproduce**
`./vcpkg install tensorflow-cc`

**Failure logs**
Console output:
```
Computing installation plan...
The following packages will be built and installed:
    tensorflow-cc[core]:x64-linux -> 2.7.0#2
Detecting compiler hash for triplet x64-linux...
Restored 0 packages from /home/duskvirkus/.cache/vcpkg/archives in 548.6 us. Use --debug to see more details.
Starting package 1/1: tensorflow-cc:x64-linux
Building package tensorflow-cc[core]:x64-linux...
-- Using cached tensorflow-tensorflow-v2.7.0.tar.gz.
-- Extracting source /home/duskvirkus/dev/tf-vcpkg/vcpkg/downloads/tensorflow-tensorflow-v2.7.0.tar.gz
-- Applying patch /home/duskvirkus/dev/tf-vcpkg/vcpkg/installed/x64-linux/share/tensorflow-common/fix-build-error.patch
-- Applying patch /home/duskvirkus/dev/tf-vcpkg/vcpkg/installed/x64-linux/share/tensorflow-common/change-macros-for-static-lib.patch
-- Using source at /home/duskvirkus/dev/tf-vcpkg/vcpkg/buildtrees/tensorflow-cc/src/v2.7.0-8c27530f06.clean
-- Configuring TensorFlow (dbg)
-- Warning: Building TensorFlow can take an hour or more.
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:158 (message):
    Command failed: /home/duskvirkus/dev/tf-vcpkg/vcpkg/downloads/tools/bazel/4.2.2-linux/bazel --output_user_root=/home/duskvirkus/dev/tf-vcpkg/vcpkg/buildtrees/tensorflow-cc/.bzl --max_idle_secs=1 build -s --verbose_failures --compilation_mode=dbg --python_path=/home/duskvirkus/dev/tf-vcpkg/vcpkg/buildtrees/tensorflow-cc/x64-linux-venv/bin/python3 --define=no_tensorflow_py_deps=true //tensorflow:libtensorflow_cc.so //tensorflow:install_headers
    Working Directory: /home/duskvirkus/dev/tf-vcpkg/vcpkg/buildtrees/tensorflow-cc/x64-linux-dbg
    See logs for more information:
      /home/duskvirkus/dev/tf-vcpkg/vcpkg/buildtrees/tensorflow-cc/build-x64-linux-dbg-err.log

Call Stack (most recent call first):
  installed/x64-linux/share/tensorflow-common/tensorflow-common.cmake:280 (vcpkg_execute_build_process)
  ports/tensorflow-cc/portfile.cmake:9 (include)
  scripts/ports.cmake:145 (include)


Error: Building package tensorflow-cc:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `./vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+tensorflow-cc
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[tensorflow-cc]+Build+error
including:
  package: tensorflow-cc[core]:x64-linux -> 2.7.0#2
    vcpkg-tool version: 2022-02-24-7efe7f2b04912a7d674f86a406f9f2711c0221c6
    vcpkg-scripts version: 1b1ae50e1 2022-02-25 (15 hours ago)

Additionally, attach any relevant sections from the log files above.
```

Unfortunately I didn’t save any of the logs but they didn't have any useful information it just said some compile command had failed with no further information.

**Additional context**

**Inelegant fix**
I managed to get it working by adding some flags to the bazel build that limit memory and jobs. Thanks to information found here: https://github.com/tensorflow/tensorflow/issues/30047#issuecomment-565556142

I modified
https://github.com/microsoft/vcpkg/blob/1b1ae50e1a69f7c659bd7d731e80b358d21c86ad/ports/tensorflow-common/tensorflow-common.cmake#L256
to be
```cmake
				COMMAND ${BAZEL} --output_user_root=${CURRENT_BUILDTREES_DIR}/.bzl --max_idle_secs=1 --local_ram_resources=8192 --jobs=5 build --verbose_failures ${BUILD_OPTS} --python_path=${PYTHON3} ${COPTS} ${CXXOPTS} ${LINKOPTS} --define=no_tensorflow_py_deps=true //tensorflow:${BAZEL_LIB_NAME} //tensorflow:install_headers
```

And
https://github.com/microsoft/vcpkg/blob/1b1ae50e1a69f7c659bd7d731e80b358d21c86ad/ports/tensorflow-common/tensorflow-common.cmake#L281
to be
```cmake
				COMMAND ${BAZEL} --output_user_root=${CURRENT_BUILDTREES_DIR}/.bzl --max_idle_secs=1 --local_ram_resources=8192 --jobs=5 build -s --verbose_failures ${BUILD_OPTS} ${COPTS} ${CXXOPTS} ${LINKOPTS} --python_path=${PYTHON3} --define=no_tensorflow_py_deps=true //tensorflow:${BAZEL_LIB_NAME} //tensorflow:install_headers
```

The key change being `--local_ram_resources=8192 --jobs=5` to both. I think the `--jobs=5` was unnecessary but wanted to still be able to use my computer while the build was happening. These look like they only run for unix based systems so different lines would have to be changed for windows.

Then deleting `vcpkg/installed`, `vcpkg/packages`, `vcpkg/packages`, and `vcpkg/packages` (this step was important at some point in the build step `tensorflow-common.cmake` is copied and won’t be recopied if it already exists)

Then rerun `./vcpkg/vcpkg install tensorflow-cc` and it took 4.59 hours to build.

**Suggestion**

I only started using vcpkg yesterday so I don’t think I’m the one to make a pull request because I don’t know how this would best be integrated.

If possible it would be great if someone could make it so there’s automatically add the `--local_ram_resources` flag to the bazel builds with something like system ram - 8gb. Failing that I think it would be worth including a warning saying how much ram is required. Definitely would not recommend capping memory usage for everyone because if people have the memory I think the build would go much quicker.

Also would be nice if when the build doesn’t succeed there was an easy way to clean up the half built libraries (this might already exist but I didn’t see a clean flag in the install cli).

**Comment by JonLiu1993** [comment]
@duskvirkus ，Thanks for posting this issue, I notice you said you didn’t save any of the logs, Could you please provide this log?
````
 /home/duskvirkus/dev/tf-vcpkg/vcpkg/buildtrees/tensorflow-cc/build-x64-linux-dbg-err.log
````
If not ,I will reproduce this problem locally, if it is indeed a bug I will seriously consider your suggestion and submit a pr to fix the bug

**Comment by JonLiu1993** [comment]
Confirmed

**Comment by dg0yt** [comment]
Vcpkg doesn't provide RAM control. But AFAICS the tensorflow/bazel script may lack support for the `VCPKG_CONCURRENCY` cmake variable (which is controlled via the `VCPKG_MAX_CONCURRENCY` environment variable). This would offer a first mitigation for memory pressure.

**Comment by JackBoosY** [comment]
Should add `-jobs ${VCPKG_CONCURRENCY}` to the following place:
https://github.com/microsoft/vcpkg/blob/75ae1ef84437bc457fb4db54360f88af57bb158a/ports/tensorflow-common/tensorflow-common.cmake#L249-L259
https://github.com/microsoft/vcpkg/blob/75ae1ef84437bc457fb4db54360f88af57bb158a/ports/tensorflow-common/tensorflow-common.cmake#L274-L283

Related official document: https://docs.bazel.build/versions/main/user-manual.html#flag--jobs

**Comment by JonLiu1993** [comment]
The latest version has fixed this issue:
````
-- You may want to delete /mnt/vcpkg/buildtrees/tensorflow-cc to free diskspace.
-- Performing post-build validation
Stored binaries in 1 destinations in 13 min.
Elapsed time to handle tensorflow-cc:x64-linux: 1.7 h
tensorflow-cc:x64-linux package ABI: 6b15005922bac23755d7f64c99b7bc1128ec01564d18dea2f50c179909d457bc
Total install time: 1.7 h
tensorflow-cc provides CMake targets:
 
  # this is heuristically generated, and may not be correct
  find_package(tensorflow-cc CONFIG REQUIRED)
  target_link_libraries(main PRIVATE tensorflow_cc::tensorflow_cc)
````
