### ISSUE TITLE
[vcpkg|manifests] MSBuild integration uses dubious --x-install-root, which differs from plain `vcpkg install` command.

### ISSUE THREAD

**Issue by hajokirchhoff** [microsoft/vcpkg#23306]
The MSBuild integration installs files to 

`vcpkg_installed\$(triplet)\$(triplet)`,

with "triplet" occurring *twice* in the path, whereas `vcpkg install`  installs files to `vcpkg_installed\$(triplet)`, as I would expect it to.

The Visual Studio Build integration duplicates the triplet in the install directory name, which is probably unnecessary and somewhat dubious.

Example - triplet `x64-windows`:
 A Visual Studio "Build" command creates the [bin, debug, include, shared etc...] directories under `./vcpkg-installed/x64-windows/x64-windows`. Running a `vcpkg install` command in that folder creates additional [bin, bin...] directories with the same content, but under `./vcpkg-installed/x64-windows`.

This makes it more difficult to run "vcpkg install" from additional scripts and devenv at the same time.

**Environment**
- OS: Windows10
- Compiler: Visual Studio 2017, 2019, 2022 (current latest version)

1. vcpkg install integrate
2. Create and run a Visual Studio Project with manifests
3. Call "vcpkg install" from the projects directory.

**Expected behavior**
There should be a directory
`vcpkg_installed\triplet` next to the `vcpkg.json`
There should *not* be another directory
`vcpkg_installed\triplet\triplet`

**Additional context**
My guess is that the vcpkg.target.props calculate the "--x-install-root=directory" command as 
"vcpkg-manifest-root/triplet"
but fail to take into account that "vcpkg install" will add another `triplet` part to the "--x-install-root" parameter.

In the MSBuild Logs I see
> 1>Target VcpkgInstallManifestDependencies:
> 1>  Installing vcpkg dependencies to X:\agent\_work\2\s\vcpkg_installed\x64-windows\
> 1>  "C:\Users\ourbuildbot\vcpkg.izt\vcpkg.exe" install  --x-wait-for-lock --triplet "x64-windows" --vcpkg-root "C:\Users\ourbuildbot\vcpkg.izt\\" "--x-manifest-root=X:\agent\_work\2\s\\" "--x-install-root=X:\agent\_work\2\s\vcpkg_installed\x64-windows\\"

Here you can see that vcpkg gets called with "--x-install-root=dir\vcpkg_installed\x64-windows", i.e. the triplet already added. My guess is that "vcpkg install" adds another directory level "triplet" to the install-root.

This not only is confusing and makes parallel use of "vcpkg install" difficult. It also wastes another directory level.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. This is by design, you can get the detail reason from: https://github.com/microsoft/vcpkg/pull/23023#pullrequestreview-878288016

**Comment by hajokirchhoff** [comment]
Ah, I see. Thanks for the pointer.
