### ISSUE TITLE
[magnum] Build error

### ISSUE THREAD

**Issue by MachinMigueldLeon** [microsoft/vcpkg#23304]
**Host Environment**
- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**
`./vcpkg install xxxx`

**Failure logs** 
-Cut and paste the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by FrankXie05** [comment]
@MachinMigueldLeon Thanks for posting this issue, could you please provide detailed error log?

**Comment by FrankXie05** [comment]
@MachinMigueldLeon  Is still work for this issue?

**Comment by FrankXie05** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
