### ISSUE TITLE
The port library is not automatically installed after building or installing

### ISSUE THREAD

**Issue by fldx** [microsoft/vcpkg#23309]
Please create a discussion in https://github.com/microsoft/vcpkg/discussions/new instead.
我试过几种方法都不行
CMakeLists.txt
```cmake
cmake_minimum_required(VERSION 3.21)
project(wxtest0)

set(CMAKE_CXX_STANDARD 14)
#if("${CMAKE_CXX_COMPILER_ID}" MATCHES "MSVC")
    add_compile_options("/utf-8")
#    add_compile_options("/subsystem:windows")
#endif()
set(wxBUILD_SHARED OFF)
set(VCPKG_LIBRARY_LINKAGE static)
#if(PORT MATCHES "qt5-")
#    set(VCPKG_LIBRARY_LINKAGE dynamic)
#endif()
find_package(wxWidgets REQUIRED)
#link_directories(vcpkg_installed/x86-windows/bin)
add_executable(wxtest0 WIN32 main.cpp)
target_include_directories(wxtest0 PRIVATE ${wxWidgets_INCLUDE_DIRS})
target_link_libraries(wxtest0 PRIVATE ${wxWidgets_LIBRARIES})
#install(TARGETS wxtest0 DESTINATION vcpkg_installed/x86-windows/bin)
```
vcpkg.json
```json
{
  "name": "wxtest0",
  "version": "0.0.1",
  "license": "MIT",
  "dependencies": [
    "wxwidgets"
  ]
}
```

![image](https://user-images.githubusercontent.com/11643460/155897544-72576c36-f49a-4902-b520-c8e2a6e442d0.png)
![image](https://user-images.githubusercontent.com/11643460/155897553-470f638b-fe41-42c9-9993-22f08efd2cf5.png)

**Comment by fldx** [comment]
如果把dll复制到可执行文件同一个目录下是可以运行的,有没有其他方法不复制也可以运行呢?

**Comment by JackBoosY** [comment]
正常来讲是可以的，你可以试试设置`-DX_VCPKG_APPLOCAL_DEPS_INSTALL=ON`.

**Comment by fldx** [comment]
> 

还是不行

**Comment by JackBoosY** [comment]
检查下你的`CMAKE_BINARY_DIR`里面有没有安装dll。

**Comment by fldx** [comment]
没有

**Comment by JackBoosY** [comment]
Install一下，再看看dll有没有安装在install目录里面？

**Comment by fldx** [comment]
![image](https://user-images.githubusercontent.com/11643460/155932687-b3ce477a-c9e7-4d0d-94f7-e9878d8ed282.png)

**Comment by JackBoosY** [comment]
不对呀，manifest模式下完全不需要手动运行`./vcpkg install`，你能发一下你的project的configure日志吗？

**Comment by fldx** [comment]
除了vcpkg_installed 我打包出来了
[cmake-build-debug.zip](https://github.com/microsoft/vcpkg/files/8151018/cmake-build-debug.zip)
[dotidea.zip](https://github.com/microsoft/vcpkg/files/8151029/dotidea.zip)

**Comment by fldx** [comment]
测试项目我放这里 https://github.com/fldx/wxtest0

**Comment by JackBoosY** [comment]
看起来没啥问题，你的powershell是用Windows Store安装的吗？

**Comment by fldx** [comment]
powershell是系统自带的吧,Windows Store只安装过Windows Terminal

**Comment by JackBoosY** [comment]
I can confirm this vcpkg bug.

请提供一下你的Visual Studio版本。谢谢。

**Comment by JackBoosY** [comment]
I can reproduce this issue using the following code:
```cmake

add_executable (CMakeProject2 WIN32 "CMakeProject2.cpp")
find_package(wxWidgets REQUIRED)
target_include_directories(CMakeProject2 PUBLIC ${wxWidgets_INCLUDE_DIRS})
target_link_libraries(CMakeProject2 PRIVATE ${wxWidgets_LIBRARIES})
install(TARGETS CMakeProject2 
  RUNTIME DESTINATION bin
  LIBRARY DESTINATION lib
  ARCHIVE DESTINATION lib
)
```

```cpp
#include "CMakeProject2.h"
#include <iostream>
#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#include <wx/wx.h>
#endif


class MyApp : public wxApp
{
public:
    virtual bool OnInit();
};
class MyFrame : public wxFrame
{
public:
    MyFrame();
private:
    void OnHello(wxCommandEvent& event);
    void OnExit(wxCommandEvent& event);
    void OnAbout(wxCommandEvent& event);
};
enum
{
    ID_Hello = 1
};
wxIMPLEMENT_APP(MyApp);
bool MyApp::OnInit()
{
    MyFrame *frame = new MyFrame();
    frame->Show(true);
    return true;
}
MyFrame::MyFrame()
    : wxFrame(NULL, wxID_ANY, "Hello World")
{
    wxMenu *menuFile = new wxMenu;
    menuFile->Append(ID_Hello, "&Hello...\tCtrl-H",
        "Help string shown in status bar for this menu item");
    menuFile->AppendSeparator();
    menuFile->Append(wxID_EXIT);
    wxMenu *menuHelp = new wxMenu;
    menuHelp->Append(wxID_ABOUT);
    wxMenuBar *menuBar = new wxMenuBar;
    menuBar->Append(menuFile, "&File");
    menuBar->Append(menuHelp, "&Help");
    SetMenuBar(menuBar);
    CreateStatusBar();
    SetStatusText("Welcome to wxWidgets!");
    Bind(wxEVT_MENU, &MyFrame::OnHello, this, ID_Hello);
    Bind(wxEVT_MENU, &MyFrame::OnAbout, this, wxID_ABOUT);
    Bind(wxEVT_MENU, &MyFrame::OnExit, this, wxID_EXIT);
}
void MyFrame::OnExit(wxCommandEvent& event)
{
    Close(true);
}
void MyFrame::OnAbout(wxCommandEvent& event)
{
    wxMessageBox("This is a wxWidgets Hello World example",
        "About Hello World", wxOK | wxICON_INFORMATION);
}
void MyFrame::OnHello(wxCommandEvent& event)
{
    wxLogMessage("Hello world from wxWidgets!");
}
```

The wxwidgets dlls are not installed during the build process and during installation.

**Comment by fldx** [comment]
Visual Studio 2019
![image](https://user-images.githubusercontent.com/11643460/155938562-437d274a-0a79-4c6c-b8e8-137c58736aa9.png)

**Comment by JackBoosY** [comment]
`applocal.ps1` may have some bugs and it can't print any logs.
Since we received many issues with that, @BillyONeal do we have any plans to make it executable?

**Comment by BillyONeal** [comment]
> I can reproduce this issue using the following code:
> The wxwidgets dlls are not installed during the build process and during installation.

My reading of

https://github.com/microsoft/vcpkg/blob/a0b2608a015fe05fe80255f8844489c106493291/scripts/buildsystems/vcpkg.cmake#L50

suggests that this is expected without `-DX_VCPKG_APPLOCAL_DEPS_INSTALL=ON` on the CMake configuration line.

**Comment by JackBoosY** [comment]
> My reading of
> 
> https://github.com/microsoft/vcpkg/blob/a0b2608a015fe05fe80255f8844489c106493291/scripts/buildsystems/vcpkg.cmake#L50
> 
> suggests that this is expected without `-DX_VCPKG_APPLOCAL_DEPS_INSTALL=ON` on the CMake configuration line.

Set `X_VCPKG_APPLOCAL_DEPS_INSTALL` to `ON` or `OFF` can't resolve this issue.

**Comment by sfhacker** [comment]
This OPEN issue is from 2022!

**Comment by Cheney-W** [comment]
The issue no longer reproduces, and the corresponding DLL can be copied to the project folder as expected.  
Environment: VS2022 + the latest vcpkg  

This issue seems to have been resolved.
