### ISSUE TITLE
Error: Building package keystone:x64-windows-static failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by uranus829** [microsoft/vcpkg#23314]
Please create a discussion in https://github.com/microsoft/vcpkg/discussions/new instead.
`
PS E:\tools\system\Visual studio\vcpkg-2022.02.23> .\vcpkg install keystone:x64-windows-static
Computing installation plan...
The following packages will be built and installed:
    keystone[core]:x64-windows-static -> 0.9.2#2
Detecting compiler hash for triplet x64-windows-static...
Restored 0 packages from C:\Users\admin\AppData\Local\vcpkg\archives in 221.9 us. Use --debug to see more details.
Starting package 1/1: keystone:x64-windows-static
Building package keystone[core]:x64-windows-static...
-- Using cached keystone-engine-keystone-dc7932ef2b2c4a793836caec6ecab485005139d6.tar.gz.
-- Cleaning sources at E:/tools/system/Visual studio/vcpkg-2022.02.23/buildtrees/keystone/src/85005139d6-6da20f5a0a.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/tools/system/Visual studio/vcpkg-2022.02.23/downloads/keystone-engine-keystone-dc7932ef2b2c4a793836caec6ecab485005139d6.tar.gz
-- Using source at E:/tools/system/Visual studio/vcpkg-2022.02.23/buildtrees/keystone/src/85005139d6-6da20f5a0a.clean
-- Using cached python-2.7.18.amd64.msi.
CMake Error at scripts/cmake/vcpkg_find_acquire_program.cmake:692 (message):
  Unable to find PYTHON2
Call Stack (most recent call first):
  ports/keystone/portfile.cmake:9 (vcpkg_find_acquire_program)
  scripts/ports.cmake:145 (include)

Error: Building package keystone:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+keystone
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[keystone]+Build+error
including:
  package: keystone[core]:x64-windows-static -> 0.9.2#2
    vcpkg-tool version: 2022-02-11-dac008bf9b55ef48e10bcc81e273b97a82bbf72d
    vcpkg-scripts version: unknown
`

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. There are error message in your log: **Unable to find PYTHON2**, please check the cotene in this folder _VCPKG_PATH/downloads/tools/python/python-2.7.18-x64_ is correct or not.
![image](https://user-images.githubusercontent.com/94091114/155947957-dee1fb57-aac8-4a09-a954-0da1205a5a96.png)
If this folder missing some files, please remove file **VCPKG_PATH/downloads/python-2.7.18.amd64.msi** and rebuild this port. If still install failed, please provide the new log.

**Comment by LilyWangLL** [comment]
Ping @uranus829 for response.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
