### ISSUE TITLE
[New Port Request] libmemcached

### ISSUE THREAD

**Issue by filak** [microsoft/vcpkg#23319]
Library name:   libmemcached

Library description:   libmemcached-awesome is an open source C/C++ client library and tools for the memcached server (http://memcached.org/). It has been designed to be light on memory usage, thread safe, and provide full access to server side methods.

Source repository URL:   https://github.com/awesomized/libmemcached

Project homepage (if different from the source repository):   https://awesomized.github.io/libmemcached/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now, consider making a pull request instead.
