### ISSUE TITLE
Error: Building package libffi:x64-linux failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by ikjoooon** [microsoft/vcpkg#23313]
I was trying to install opencv via vcpkg on Ubuntu 18.04 and got the following error:

Computing installation plan...
A suitable version of cmake was not found (required v3.22.2). Downloading portable cmake v3.22.2...
Downloading cmake...
  https://github.com/Kitware/CMake/releases/download/v3.22.2/cmake-3.22.2-linux-x86_64.tar.gz -> /mnt/d/conda/AutoAnnoUbuntu/vcpkg/downloads/cmake-3.22.2linux-x86_64.tar.gz
Extracting cmake...
The following packages will be built and installed:
  * atk[core]:x64-linux -> 2.36.0#2
  * brotli[core]:x64-linux -> 1.0.9#2
  * bzip2[core]:x64-linux -> 1.0.8#2
  * cairo[core,fontconfig,freetype,gobject,x11]:x64-linux -> 1.17.4#4
  * dirent[core]:x64-linux -> 1.23.2#1
  * expat[core]:x64-linux -> 2.4.1
  * fontconfig[core]:x64-linux -> 2.13.94#5
  * freetype[brotli,bzip2,core,png,zlib]:x64-linux -> 2.11.1
  * fribidi[core]:x64-linux -> 1.0.11#3
  * gdk-pixbuf[core]:x64-linux -> 2.42.2#2
  * getopt[core]:x64-linux -> 0#1
  * gettext[core]:x64-linux -> 0.21#9
  * glib[core]:x64-linux -> 2.70.1#2
  * graphene[core]:x64-linux -> 1.10.2#2
  * gtk[core]:x64-linux -> 4.6.0
  * harfbuzz[core]:x64-linux -> 3.2.0#1
  * json-c[core]:x64-linux -> 2019-09-10#2
  * libepoxy[core]:x64-linux -> 1.5.9#1
  * libffi[core]:x64-linux -> 3.4.2#4
  * libiconv[core]:x64-linux -> 1.16#11
  * libjpeg-turbo[core]:x64-linux -> 2.1.2
  * liblzma[core]:x64-linux -> 5.2.5#4
  * libpng[core]:x64-linux -> 1.6.37#16
  * libsass[core]:x64-linux -> 3.6.5#1
  * libuuid[core]:x64-linux -> 1.0.3#11
  * libwebp[core,nearlossless,simd]:x64-linux -> 1.2.1
  * lzo[core]:x64-linux -> 2.10#7
    opencv3[core,default-features,dnn,flann,gtk,jpeg,png,quirc,tiff,webp,world]:x64-linux -> 3.4.16#4
  * pango[core]:x64-linux -> 1.50.3
  * pcre[core]:x64-linux -> 8.45#2
  * pixman[core]:x64-linux -> 0.40.0#2
  * protobuf[core]:x64-linux -> 3.18.0#1
  * pthread[core]:x64-linux -> 3.0.0#1
  * pthreads[core]:x64-linux -> 3.0.0#10
  * quirc[core]:x64-linux -> 1.1#2
  * sassc[core]:x64-linux -> 3.6.2
  * tiff[core,jpeg,lzma,zip]:x64-linux -> 4.3.0#5
  * vcpkg-cmake[core]:x64-linux -> 2022-01-19
  * vcpkg-cmake-config[core]:x64-linux -> 2022-02-06
  * vcpkg-tool-meson[core]:x64-linux -> 0.60.2#2
  * zlib[core]:x64-linux -> 1.2.11#13
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-linux...
Restored 5 packages from /root/.cache/vcpkg/archives in 370.7 ms. Use --debug to see more details.
Starting package 1/41: libiconv:x64-linux
Installing package libiconv[core]:x64-linux...
Elapsed time for package libiconv:x64-linux: 85.14 ms
Starting package 2/41: gettext:x64-linux
Installing package gettext[core]:x64-linux...
Elapsed time for package gettext:x64-linux: 363.1 ms
Starting package 3/41: dirent:x64-linux
Installing package dirent[core]:x64-linux...
Elapsed time for package dirent:x64-linux: 87.06 ms
Starting package 4/41: vcpkg-cmake:x64-linux
Installing package vcpkg-cmake[core]:x64-linux...
Elapsed time for package vcpkg-cmake:x64-linux: 202 ms
Starting package 5/41: vcpkg-cmake-config:x64-linux
Installing package vcpkg-cmake-config[core]:x64-linux...
Elapsed time for package vcpkg-cmake-config:x64-linux: 126 ms
Starting package 6/41: libffi:x64-linux
Building package libffi[core]:x64-linux...
-- Downloading https://github.com/libffi/libffi/archive/v3.4.2.tar.gz -> libffi-libffi-v3.4.2.tar.gz...
-- Extracting source /mnt/d/conda/AutoAnnoUbuntu/vcpkg/downloads/libffi-libffi-v3.4.2.tar.gz
-- Using source at /mnt/d/conda/AutoAnnoUbuntu/vcpkg/buildtrees/libffi/src/v3.4.2-43b890eb15.clean
-- Found external ninja('1.10.2').
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Fixing pkgconfig file: /mnt/d/conda/AutoAnnoUbuntu/vcpkg/packages/libffi_x64-linux/lib/pkgconfig/libffi.pc
CMake Error at scripts/cmake/vcpkg_find_acquire_program.cmake:611 (message):
  Could not find pkg-config.  Please install it via your package manager:

      sudo apt-get install pkg-config
Call Stack (most recent call first):
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:198 (vcpkg_find_acquire_program)
  ports/libffi/portfile.cmake:57 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:145 (include)

Error: Building package libffi:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `./vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libffi
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[libffi]+Build+error
including:
  package: libffi[core]:x64-linux -> 3.4.2#4
    vcpkg-tool version: 2022-02-24-7efe7f2b04912a7d674f86a406f9f2711c0221c6
    vcpkg-scripts version: 1b1ae50e1 2022-02-25 (2 days ago)

**Comment by JackBoosY** [comment]
```
Could not find pkg-config. Please install it via your package manager:

sudo apt-get install pkg-config
```

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

**Comment by TomasMakus** [comment]
Is there a solution to this problem
