### ISSUE TITLE
Failed to process package 'ceres-solver'

### ISSUE THREAD

**Issue by FelicxFoster** [Microsoft/vcpkg#2331]
i got the error when i catkin_make_isolated --install --use-ninja with the tutorial about installing cartographer in ubuntu14.04(indigo)

felicx@felicx-Lenovo-XiaoXin-310-14ISK:~/carto_ws$ catkin_make_isolated --install --use-ninja
Base path: /home/felicx/carto_ws
Source space: /home/felicx/carto_ws/src
Build space: /home/felicx/carto_ws/build_isolated
Devel space: /home/felicx/carto_ws/devel_isolated
Install space: /home/felicx/carto_ws/install_isolated
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~  traversing 6 packages in topological order:
~~  - cartographer_ros_msgs
~~  - ceres-solver (plain cmake)
~~  - cartographer (plain cmake)
~~  - cartographer_ros
~~  - cartographer_rviz
~~  - cartographer_turtlebot
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

==> Processing catkin package: 'cartographer_ros_msgs'
build.ninja exists, skipping explicit cmake invocation...
==> ninja build.ninja in '/home/felicx/carto_ws/build_isolated/cartographer_ros_msgs'
ninja: no work to do.
==> ninja -j4 -l4 in '/home/felicx/carto_ws/build_isolated/cartographer_ros_msgs'
[9/9] cd /home/felicx/carto_ws/build_i...ons:cartographer_ros_msgs/SensorTopics
==> ninja install in '/home/felicx/carto_ws/build_isolated/cartographer_ros_msgs'
[10/10] Install the project...
-- Install configuration: ""
-- Up-to-date: /home/felicx/carto_ws/install_isolated/_setup_util.py
-- Up-to-date: /home/felicx/carto_ws/install_isolated/env.sh
-- Up-to-date: /home/felicx/carto_ws/install_isolated/setup.bash
-- Up-to-date: /home/felicx/carto_ws/install_isolated/setup.sh
-- Up-to-date: /home/felicx/carto_ws/install_isolated/setup.zsh
-- Up-to-date: /home/felicx/carto_ws/install_isolated/.rosinstall
-- Up-to-date: /home/felicx/carto_ws/install_isolated/share/cartographer_ros_msgs/msg/SubmapList.msg
-- Up-to-date: /home/felicx/carto_ws/install_isolated/share/cartographer_ros_msgs/msg/SubmapEntry.msg
-- Up-to-date: /home/felicx/carto_ws/install_isolated/share/cartographer_ros_msgs/msg/SubmapTexture.msg
-- Up-to-date: /home/felicx/carto_ws/install_isolated/share/cartographer_ros_msgs/msg/SensorTopics.msg
-- Up-to-date: /home/felicx/carto_ws/install_isolated/share/cartographer_ros_msgs/msg/TrajectoryOptions.msg
-- Up-to-date: /home/felicx/carto_ws/install_isolated/share/cartographer_ros_msgs/srv/SubmapQuery.srv
-- Up-to-date: /home/felicx/carto_ws/install_isolated/share/cartographer_ros_msgs/srv/FinishTrajectory.srv
-- Up-to-date: /home/felicx/carto_ws/install_isolated/share/cartographer_ros_msgs/srv/StartTrajectory.srv
-- Up-to-date: /home/felicx/carto_ws/install_isolated/share/cartographer_ros_msgs/srv/WriteState.srv
-- Up-to-date: /home/felicx/carto_ws/install_isolated/share/cartographer_ros_msgs/cmake/cartographer_ros_msgs-msg-paths.cmake
-- Installing: /home/felicx/carto_ws/install_isolated/include/cartographer_ros_msgs
-- Up-to-date: /home/felicx/carto_ws/install_isolated/include/cartographer_ros_msgs/StartTrajectoryResponse.h
-- Up-to-date: /home/felicx/carto_ws/install_isolated/include/cartographer_ros_msgs/FinishTrajectory.h
-- Up-to-date: /home/felicx/carto_ws/install_isolated/include/cartographer_ros_msgs/SensorTopics.h
-- Up-to-date: /home/felicx/carto_ws/install_isolated/include/cartographer_ros_msgs/SubmapEntry.h
-- Up-to-date: /home/felicx/carto_ws/install_isolated/include/cartographer_ros_msgs/SubmapTexture.h
-- Up-to-date: /home/felicx/carto_ws/install_isolated/include/cartographer_ros_msgs/WriteStateResponse.h
-- Up-to-date: /home/felicx/carto_ws/install_isolated/include/cartographer_ros_msgs/SubmapList.h
-- Up-to-date: /home/felicx/carto_ws/install_isolated/include/cartographer_ros_msgs/TrajectoryOptions.h
-- Up-to-date: /home/felicx/carto_ws/install_isolated/include/cartographer_ros_msgs/StartTrajectoryRequest.h
-- Up-to-date: /home/felicx/carto_ws/install_isolated/include/cartographer_ros_msgs/SubmapQuery.h
-- Up-to-date: /home/felicx/carto_ws/install_isolated/include/cartographer_ros_msgs/FinishTrajectoryResponse.h
-- Up-to-date: /home/felicx/carto_ws/install_isolated/include/cartographer_ros_msgs/SubmapQueryResponse.h
-- Up-to-date: /home/felicx/carto_ws/install_isolated/include/cartographer_ros_msgs/FinishTrajectoryRequest.h
-- Up-to-date: /home/felicx/carto_ws/install_isolated/include/cartographer_ros_msgs/WriteStateRequest.h
-- Up-to-date: /home/felicx/carto_ws/install_isolated/include/cartographer_ros_msgs/SubmapQueryRequest.h
-- Up-to-date: /home/felicx/carto_ws/install_isolated/include/cartographer_ros_msgs/WriteState.h
-- Up-to-date: /home/felicx/carto_ws/install_isolated/include/cartographer_ros_msgs/StartTrajectory.h
-- Installing: /home/felicx/carto_ws/install_isolated/share/common-lisp/ros/cartographer_ros_msgs
-- Installing: /home/felicx/carto_ws/install_isolated/share/common-lisp/ros/cartographer_ros_msgs/msg
-- Up-to-date: /home/felicx/carto_ws/install_isolated/share/common-lisp/ros/cartographer_ros_msgs/msg/_package_SensorTopics.lisp
-- Up-to-date: /home/felicx/carto_ws/install_isolated/share/common-lisp/ros/cartographer_ros_msgs/msg/TrajectoryOptions.lisp
-- Up-to-date: /home/felicx/carto_ws/install_isolated/share/common-lisp/ros/cartographer_ros_msgs/msg/_package.lisp
-- Up-to-date: /home/felicx/carto_ws/install_isolated/share/common-lisp/ros/cartographer_ros_msgs/msg/_package_SubmapList.lisp
-- Up-to-date: /home/felicx/carto_ws/install_isolated/share/common-lisp/ros/cartographer_ros_msgs/msg/SubmapEntry.lisp
-- Up-to-date: /home/felicx/carto_ws/install_isolated/share/common-lisp/ros/cartographer_ros_msgs/msg/SubmapTexture.lisp
-- Up-to-date: /home/felicx/carto_ws/install_isolated/share/common-lisp/ros/cartographer_ros_msgs/msg/SensorTopics.lisp
-- Up-to-date: /home/felicx/carto_ws/install_isolated/share/common-lisp/ros/cartographer_ros_msgs/msg/_package_SubmapTexture.lisp
-- Up-to-date: /home/felicx/carto_ws/install_isolated/share/common-lisp/ros/cartographer_ros_msgs/msg/SubmapList.lisp
-- Up-to-date: /home/felicx/carto_ws/install_isolated/share/common-lisp/ros/cartographer_ros_msgs/msg/_package_SubmapEntry.lisp
-- Up-to-date: /home/felicx/carto_ws/install_isolated/share/common-lisp/ros/cartographer_ros_msgs/msg/cartographer_ros_msgs-msg.asd
-- Up-to-date: /home/felicx/carto_ws/install_isolated/share/common-lisp/ros/cartographer_ros_msgs/msg/_package_TrajectoryOptions.lisp
-- Installing: /home/felicx/carto_ws/install_isolated/share/common-lisp/ros/cartographer_ros_msgs/srv
-- Up-to-date: /home/felicx/carto_ws/install_isolated/share/common-lisp/ros/cartographer_ros_msgs/srv/_package_FinishTrajectory.lisp
-- Up-to-date: /home/felicx/carto_ws/install_isolated/share/common-lisp/ros/cartographer_ros_msgs/srv/WriteState.lisp
-- Up-to-date: /home/felicx/carto_ws/install_isolated/share/common-lisp/ros/cartographer_ros_msgs/srv/_package.lisp
-- Up-to-date: /home/felicx/carto_ws/install_isolated/share/common-lisp/ros/cartographer_ros_msgs/srv/StartTrajectory.lisp
-- Up-to-date: /home/felicx/carto_ws/install_isolated/share/common-lisp/ros/cartographer_ros_msgs/srv/_package_WriteState.lisp
-- Up-to-date: /home/felicx/carto_ws/install_isolated/share/common-lisp/ros/cartographer_ros_msgs/srv/FinishTrajectory.lisp
-- Up-to-date: /home/felicx/carto_ws/install_isolated/share/common-lisp/ros/cartographer_ros_msgs/srv/_package_StartTrajectory.lisp
-- Up-to-date: /home/felicx/carto_ws/install_isolated/share/common-lisp/ros/cartographer_ros_msgs/srv/_package_SubmapQuery.lisp
-- Up-to-date: /home/felicx/carto_ws/install_isolated/share/common-lisp/ros/cartographer_ros_msgs/srv/cartographer_ros_msgs-srv.asd
-- Up-to-date: /home/felicx/carto_ws/install_isolated/share/common-lisp/ros/cartographer_ros_msgs/srv/SubmapQuery.lisp
Listing /home/felicx/carto_ws/devel_isolated/cartographer_ros_msgs/lib/python2.7/dist-packages/cartographer_ros_msgs ...
Listing /home/felicx/carto_ws/devel_isolated/cartographer_ros_msgs/lib/python2.7/dist-packages/cartographer_ros_msgs/msg ...
Listing /home/felicx/carto_ws/devel_isolated/cartographer_ros_msgs/lib/python2.7/dist-packages/cartographer_ros_msgs/srv ...
-- Installing: /home/felicx/carto_ws/install_isolated/lib/python2.7/dist-packages/cartographer_ros_msgs
-- Up-to-date: /home/felicx/carto_ws/install_isolated/lib/python2.7/dist-packages/cartographer_ros_msgs/__init__.py
-- Installing: /home/felicx/carto_ws/install_isolated/lib/python2.7/dist-packages/cartographer_ros_msgs/msg
-- Up-to-date: /home/felicx/carto_ws/install_isolated/lib/python2.7/dist-packages/cartographer_ros_msgs/msg/_SubmapEntry.pyc
-- Up-to-date: /home/felicx/carto_ws/install_isolated/lib/python2.7/dist-packages/cartographer_ros_msgs/msg/__init__.py
-- Up-to-date: /home/felicx/carto_ws/install_isolated/lib/python2.7/dist-packages/cartographer_ros_msgs/msg/_SubmapTexture.py
-- Up-to-date: /home/felicx/carto_ws/install_isolated/lib/python2.7/dist-packages/cartographer_ros_msgs/msg/_SubmapTexture.pyc
-- Up-to-date: /home/felicx/carto_ws/install_isolated/lib/python2.7/dist-packages/cartographer_ros_msgs/msg/_SubmapList.pyc
-- Up-to-date: /home/felicx/carto_ws/install_isolated/lib/python2.7/dist-packages/cartographer_ros_msgs/msg/_SensorTopics.py
-- Up-to-date: /home/felicx/carto_ws/install_isolated/lib/python2.7/dist-packages/cartographer_ros_msgs/msg/__init__.pyc
-- Up-to-date: /home/felicx/carto_ws/install_isolated/lib/python2.7/dist-packages/cartographer_ros_msgs/msg/_TrajectoryOptions.pyc
-- Up-to-date: /home/felicx/carto_ws/install_isolated/lib/python2.7/dist-packages/cartographer_ros_msgs/msg/_TrajectoryOptions.py
-- Up-to-date: /home/felicx/carto_ws/install_isolated/lib/python2.7/dist-packages/cartographer_ros_msgs/msg/_SubmapEntry.py
-- Up-to-date: /home/felicx/carto_ws/install_isolated/lib/python2.7/dist-packages/cartographer_ros_msgs/msg/_SubmapList.py
-- Up-to-date: /home/felicx/carto_ws/install_isolated/lib/python2.7/dist-packages/cartographer_ros_msgs/msg/_SensorTopics.pyc
-- Up-to-date: /home/felicx/carto_ws/install_isolated/lib/python2.7/dist-packages/cartographer_ros_msgs/__init__.pyc
-- Installing: /home/felicx/carto_ws/install_isolated/lib/python2.7/dist-packages/cartographer_ros_msgs/srv
-- Up-to-date: /home/felicx/carto_ws/install_isolated/lib/python2.7/dist-packages/cartographer_ros_msgs/srv/_WriteState.pyc
-- Up-to-date: /home/felicx/carto_ws/install_isolated/lib/python2.7/dist-packages/cartographer_ros_msgs/srv/__init__.py
-- Up-to-date: /home/felicx/carto_ws/install_isolated/lib/python2.7/dist-packages/cartographer_ros_msgs/srv/_SubmapQuery.py
-- Up-to-date: /home/felicx/carto_ws/install_isolated/lib/python2.7/dist-packages/cartographer_ros_msgs/srv/_FinishTrajectory.py
-- Up-to-date: /home/felicx/carto_ws/install_isolated/lib/python2.7/dist-packages/cartographer_ros_msgs/srv/_WriteState.py
-- Up-to-date: /home/felicx/carto_ws/install_isolated/lib/python2.7/dist-packages/cartographer_ros_msgs/srv/_StartTrajectory.py
-- Up-to-date: /home/felicx/carto_ws/install_isolated/lib/python2.7/dist-packages/cartographer_ros_msgs/srv/__init__.pyc
-- Up-to-date: /home/felicx/carto_ws/install_isolated/lib/python2.7/dist-packages/cartographer_ros_msgs/srv/_FinishTrajectory.pyc
-- Up-to-date: /home/felicx/carto_ws/install_isolated/lib/python2.7/dist-packages/cartographer_ros_msgs/srv/_StartTrajectory.pyc
-- Up-to-date: /home/felicx/carto_ws/install_isolated/lib/python2.7/dist-packages/cartographer_ros_msgs/srv/_SubmapQuery.pyc
-- Up-to-date: /home/felicx/carto_ws/install_isolated/lib/pkgconfig/cartographer_ros_msgs.pc
-- Up-to-date: /home/felicx/carto_ws/install_isolated/share/cartographer_ros_msgs/cmake/cartographer_ros_msgs-msg-extras.cmake
-- Up-to-date: /home/felicx/carto_ws/install_isolated/share/cartographer_ros_msgs/cmake/cartographer_ros_msgsConfig.cmake
-- Up-to-date: /home/felicx/carto_ws/install_isolated/share/cartographer_ros_msgs/cmake/cartographer_ros_msgsConfig-version.cmake
-- Up-to-date: /home/felicx/carto_ws/install_isolated/share/cartographer_ros_msgs/package.xml
<== Finished processing package [1 of 6]: 'cartographer_ros_msgs'

==> Processing plain cmake package: 'ceres-solver'
==> Building with env: '/home/felicx/carto_ws/install_isolated/env.sh'
==> cmake /home/felicx/carto_ws/src/ceres-solver -DCMAKE_INSTALL_PREFIX=/home/felicx/carto_ws/install_isolated -G Ninja in '/home/felicx/carto_ws/build_isolated/ceres-solver/install'
-- Detected Ceres being used as a git submodule, adding commit hook for Gerrit to: /home/felicx/carto_ws/src/ceres-solver/.git
CMake Error at cmake/AddGerritCommitHook.cmake:68 (file):
  file COPY cannot copy file
  "/home/felicx/carto_ws/build_isolated/ceres-solver/install/commit-msg" to
  "/home/felicx/carto_ws/src/ceres-solver/.git/hooks//commit-msg".
Call Stack (most recent call first):
  CMakeLists.txt:50 (add_gerrit_commit_hook)

-- Detected Ceres version: 1.12.0 from /home/felicx/carto_ws/src/ceres-solver/include/ceres/version.h
-- Found Eigen version 3.2.0: /usr/include/eigen3

   ===============================================================
   Disabling the use of Eigen as a sparse linear algebra library.
   This does not affect the covariance estimation algorithm 
   which can still use the EIGEN_SPARSE_QR algorithm.
   ===============================================================

-- A library with BLAS API found.
-- Found LAPACK library: /usr/lib/liblapack.so;/usr/lib/libf77blas.so;/usr/lib/libatlas.so
-- Found BLAS library: /usr/lib/libf77blas.so;/usr/lib/libatlas.so
-- A library with BLAS API found.
-- Found AMD library: /usr/lib/x86_64-linux-gnu/libamd.so
-- Found AMD header in: /usr/include/suitesparse
-- Found CAMD library: /usr/lib/x86_64-linux-gnu/libcamd.so
-- Found CAMD header in: /usr/include/suitesparse
-- Found COLAMD library: /usr/lib/x86_64-linux-gnu/libcolamd.so
-- Found COLAMD header in: /usr/include/suitesparse
-- Found CCOLAMD library: /usr/lib/x86_64-linux-gnu/libccolamd.so
-- Found CCOLAMD header in: /usr/include/suitesparse
-- Found CHOLMOD library: /usr/lib/x86_64-linux-gnu/libcholmod.so
-- Found CHOLMOD header in: /usr/include/suitesparse
-- Found SuiteSparseQR library: /usr/lib/x86_64-linux-gnu/libspqr.so
-- Found SuiteSparseQR header in: /usr/include/suitesparse
-- Found Intel Thread Building Blocks (TBB) library: /usr/lib/libtbb.so, assuming SuiteSparseQR was compiled with TBB.
-- Found Intel Thread Building Blocks (TBB) Malloc library: /usr/lib/libtbbmalloc.so
-- Found SuiteSparse_config library: /usr/lib/x86_64-linux-gnu/libsuitesparseconfig.a
-- Found SuiteSparse_config header in: /usr/include/suitesparse
-- Adding librt: /usr/lib/x86_64-linux-gnu/librt.so to SuiteSparse_config libraries (required on Linux & Unix [not OSX] if SuiteSparse is compiled with timing).
-- Did not find METIS library (optional SuiteSparse dependency)
-- Found SuiteSparse 4.2.1, building with SuiteSparse.
-- Building without CXSparse.
-- No preference for use of exported gflags CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported gflags CMake configuration if available.
-- Failed to find installed gflags CMake configuration, searching for gflags build directories exported with CMake.
-- Failed to find an installed/exported CMake configuration for gflags, will perform search for installed gflags components.
-- Found Google Flags header in: /usr/include, in namespace: google
-- No preference for use of exported glog CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported glog CMake configuration if available.
-- Failed to find installed glog CMake configuration, searching for glog build directories exported with CMake.
-- Failed to find an installed/exported CMake configuration for glog, will perform search for installed glog components.
-- Found Google Log (glog). Assuming glog was built with gflags support as gflags was found. This will make gflags a public dependency of Ceres.
-- Building with OpenMP.
-- Looking for C++ include unordered_map
-- Looking for C++ include unordered_map - not found
-- Looking for C++ include tr1/unordered_map
-- Looking for C++ include tr1/unordered_map - found
-- Found tr1/unordered_map/set in std::tr1 namespace.
-- Looking for C++ include memory
-- Looking for C++ include memory - found
-- Performing Test HAVE_SHARED_PTR_IN_STD_NAMESPACE
-- Performing Test HAVE_SHARED_PTR_IN_STD_NAMESPACE - Failed
-- Performing Test HAVE_SHARED_PTR_IN_TR1_NAMESPACE
-- Performing Test HAVE_SHARED_PTR_IN_TR1_NAMESPACE - Failed
-- Looking for C++ include tr1/memory
-- Looking for C++ include tr1/memory - found
-- Performing Test HAVE_SHARED_PTR_IN_TR1_NAMESPACE_FROM_TR1_MEMORY_HEADER
-- Performing Test HAVE_SHARED_PTR_IN_TR1_NAMESPACE_FROM_TR1_MEMORY_HEADER - Success
-- Found shared_ptr in std::tr1 namespace using <tr1/memory> header.
-- Building Ceres as a static library.
-- Enabling CERES_NO_CXSPARSE in Ceres config.h
-- Enabling CERES_USE_OPENMP in Ceres config.h
-- Enabling CERES_HAVE_PTHREAD in Ceres config.h
-- Enabling CERES_HAVE_RWLOCK in Ceres config.h
-- Enabling CERES_TR1_UNORDERED_MAP in Ceres config.h
-- Enabling CERES_TR1_MEMORY_HEADER in Ceres config.h
-- Enabling CERES_TR1_SHARED_PTR in Ceres config.h
-- Build the examples.
-- Configuring incomplete, errors occurred!
See also "/home/felicx/carto_ws/build_isolated/ceres-solver/install/CMakeFiles/CMakeOutput.log".
See also "/home/felicx/carto_ws/build_isolated/ceres-solver/install/CMakeFiles/CMakeError.log".
<== Failed to process package 'ceres-solver': 
  Command '['/home/felicx/carto_ws/install_isolated/env.sh', 'cmake', '/home/felicx/carto_ws/src/ceres-solver', '-DCMAKE_INSTALL_PREFIX=/home/felicx/carto_ws/install_isolated', '-G', 'Ninja']' returned non-zero exit status 1

Reproduce this error by running:
==> cd /home/felicx/carto_ws/build_isolated/ceres-solver && /home/felicx/carto_ws/install_isolated/env.sh cmake /home/felicx/carto_ws/src/ceres-solver -DCMAKE_INSTALL_PREFIX=/home/felicx/carto_ws/install_isolated -G Ninja

Command failed, exiting.

**Comment by KindDragon** [comment]
I think you post this issue to wrong repository
Check https://github.com/ceres-solver/ceres-solver/issues
