### ISSUE TITLE
[New Port Request] Backward-cpp

### ISSUE THREAD

**Issue by sonodima** [microsoft/vcpkg#23320]
Library name:
Backward-cpp

Library description:
Backward-cpp is a beautiful stack trace pretty printer.

Source repository URL:
https://github.com/bombela/backward-cpp

**Comment by FrankXie05** [comment]
Fix by PR #21955

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
