### ISSUE TITLE
[libjpeg-turbo] Build error

### ISSUE THREAD

**Issue by houmenghang** [microsoft/vcpkg#23337]
**Host Environment**
- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**
`./vcpkg install xxxx`

**Failure logs** 
-Cut and paste the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Could you please provide the error log file?

**Comment by houmenghang** [comment]
Thank you for your reply,this is my log.
[config-x64-windows-static-out.log](https://github.com/microsoft/vcpkg/files/8167077/config-x64-windows-static-out.log)

**Comment by LilyWangLL** [comment]
Thanks for your reply. I can't repro this issue locally. There are error message in your log. Did you use the latest version of VCPKG? And did you run command `.\bootstrap-vcpkg.bat` before installing port?
```
CMake Error at D:/work/code/Rust/rustDesk_releases/vcpkg/scripts/buildsystems/vcpkg.cmake:816 (message):
  Could not find .vcpkg-root
```

**Comment by dg0yt** [comment]
Or do you use an exFAT filesystem? https://github.com/microsoft/vcpkg/issues/19524

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
