### ISSUE TITLE
Build folly failed

### ISSUE THREAD

**Issue by lixinyancici** [Microsoft/vcpkg#2333]
Package: folly:x64-windows
Vcpkg version: 0.0.100-2017-12-07-48c4b79be510c5aff3f28079b7875a95497691e5

**Comment by KindDragon** [comment]
Can you provide build log?

**Comment by cppcraze** [comment]
I also tried to build folly yesterday night. Attach the build log.

[install-x64-windows-rel-out.log](https://github.com/Microsoft/vcpkg/files/1544481/install-x64-windows-rel-out.log)

**Comment by KindDragon** [comment]
Could you try Visual Studio to Update 5?

**Comment by lixinyancici** [comment]
This is my log file (the version of Visual Studio is 14.0.25431.01 Update 3) :
[install-x64-windows-rel-out.log](https://github.com/Microsoft/vcpkg/files/1544683/install-x64-windows-rel-out.log)

**Comment by KindDragon** [comment]
```
folly\IPAddressV6.cpp(441): error C2666: 'inet_ntop': 2 overloads have similar conversions
```
I think it depends on which Windows SDK version you using https://github.com/facebook/folly/issues/677#issuecomment-333019809

**Comment by KindDragon** [comment]
This issue fixed in Folly

**Comment by oatastemur** [comment]
I am getting the same build error related to inet_ntop on the latest master. I have only the Windows 8.1 SDK installed to save disk space. Is this insufficient for building folly?

**Comment by KindDragon** [comment]
It should be

**Comment by JackBoosY** [comment]
Hi @lixinyancici @cppcraze @oatastemur , thanks for post this issue, that's makes vcpkg better!
This issue should be fixed in nearly PR. Can you update and rebuild it?
Thx.
