### ISSUE TITLE
[lapacke] Add new port

### ISSUE THREAD

**Issue by liupeiqiHN** [microsoft/vcpkg#23333]
**Describe the bug**
some header file is missing in lapack-reference

**Environment**
- Windows11
- MSVC 2022

**To Reproduce**
1. ./vcpkg install lapack-reference[core]:x64-windows-static

**Expected behavior**
I want lapack header file just like:
[lapack.h](https://github.com/Reference-LAPACK/lapack/blob/master/LAPACKE/include/lapack.h)
[lapacke.h](https://github.com/Reference-LAPACK/lapack/blob/master/LAPACKE/include/lapacke.h)
[lapacke_config.h](https://github.com/Reference-LAPACK/lapack/blob/master/LAPACKE/include/lapacke_config.h)
...

**Comment by Neumann-A** [comment]
**LAPACKE** is not part of `lapack-reference`. `lapack-reference` only builds **LAPACK**. **LAPACKE** would require another port.

**Comment by liupeiqiHN** [comment]
Another port? I install lapack and lapack-reference, but I can't find lapack header file too.

**Comment by Neumann-A** [comment]
>  lapack header file

there are no lapack headers since lapack is a Fortran library. LAPACKE has headers since it is a C lib but that one does not have a port in vcpkg yet.

**Comment by liupeiqiHN** [comment]
I include lapack.h and link to lapack-reference[core]:x64-windows-static, I can call lapack function (dgels_) normally. But if I include lapacke.h and use LAPACKE_dgels function, I will get an error "unresolved external symbol LAPACKE_dgels". 
So lapack-reference only support xxxxx_() and don't support LAPACK_xxxxx() and LAPACKE_xxxxx()?

**Comment by Neumann-A** [comment]
> So lapack-reference only support xxxxx_() and don't support LAPACK_xxxxx() and LAPACKE_xxxxx()?

as I said. `lapack-reference` only contains the Fortran `lapack` library. The C wrapper is not part of it. If you want that a new port should be created for `lapacke`. The reason for that is that `lapacke` can use different lapack implementations as its backend and is thus not build together with `lapack`

**Comment by liupeiqiHN** [comment]
When I install openblas as backend, I can't find `lapacke` too.

**Comment by LilyWangLL** [comment]
>there are no lapack headers since lapack is a Fortran library. 

`lapacke` is a new port.

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by LiuPeiqiCN** [comment]
**B**LAS is very `basic`, `LAPACKE` is important, pls.
