### ISSUE TITLE
openssl x86-windows install failed

### ISSUE THREAD

**Issue by gogog22510** [Microsoft/vcpkg#2334]
When I tried to install openssl, it was showing build failed

E:\vcpkg-master>vcpkg install openssl
The following packages will be built and installed:
    openssl:x86-windows
Starting package 1/1: openssl:x86-windows
Building package openssl:x86-windows...
-- CURRENT_INSTALLED_DIR=E:/vcpkg-master/installed/x86-windows
-- DOWNLOADS=E:/vcpkg-master/downloads
-- CURRENT_PACKAGES_DIR=E:/vcpkg-master/packages/openssl_x86-windows
-- CURRENT_BUILDTREES_DIR=E:/vcpkg-master/buildtrees/openssl
-- CURRENT_PORT_DIR=E:/vcpkg-master/ports/openssl/.
-- Using cached E:/vcpkg-master/downloads/openssl-1.0.2n.tar.gz
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Applying patch E:/vcpkg-master/ports/openssl/PerlScriptSpaceInPathFixes.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch E:/vcpkg-master/ports/openssl/PerlScriptSpaceInPathFixes.patch done
-- Applying patch E:/vcpkg-master/ports/openssl/ConfigureIncludeQuotesFix.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch E:/vcpkg-master/ports/openssl/ConfigureIncludeQuotesFix.patch done
-- Applying patch E:/vcpkg-master/ports/openssl/STRINGIFYPatch.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch E:/vcpkg-master/ports/openssl/STRINGIFYPatch.patch done
-- Applying patch E:/vcpkg-master/ports/openssl/EmbedSymbolsInStaticLibsZ7.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch E:/vcpkg-master/ports/openssl/EmbedSymbolsInStaticLibsZ7.patch done
-- Configure x86-windows-rel
-- Configure x86-windows-rel done
-- Build x86-windows-rel
CMake Error at E:/vcpkg-master/scripts/cmake/vcpkg_execute_required_process.cmake:44 (message):
    Command failed: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.12.25827/bin/Hostx64/x64/nmake.exe;-f;ms\ntdll.mak;install
    Working Directory: E:/vcpkg-master/buildtrees/openssl/x86-windows-rel/openssl-1.0.2n
    See logs for more information:
      E:\vcpkg-master\buildtrees\openssl\build-x86-windows-rel-1-out.log
      E:\vcpkg-master\buildtrees\openssl\build-x86-windows-rel-1-err.log

Call Stack (most recent call first):
  E:/vcpkg-master/ports/openssl/portfile.cmake:86 (vcpkg_execute_required_process)
  E:/vcpkg-master/scripts/ports.cmake:72 (include)

Error: Building package openssl:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openssl:x86-windows
  Vcpkg version: 0.0.100-unknownhash

Additionally, attach any relevant sections from the log files above.
[build-x86-windows-rel-0-err.log](https://github.com/Microsoft/vcpkg/files/1543459/build-x86-windows-rel-0-err.log)
[build-x86-windows-rel-0-out.log](https://github.com/Microsoft/vcpkg/files/1543460/build-x86-windows-rel-0-out.log)

I already update to the latest version using git pull

**Comment by alexkaratarakis** [comment]
According to the log:
```
.\ssl\bad_dtls_test.c: error C2220: warning treated as error - no 'object' file generated
.\ssl\bad_dtls_test.c: warning C4819: The file contains a character that cannot be represented in the current code page (950). Save the file in Unicode format to prevent data loss
```

Please try:

1) Open `$vcpkg\buildtrees\openssl\src\openssl-1.0.2n\ssl\bad_dtls_test.c`
2) Line 22 is:
```
 * fixed up it's the wrong thing to test against — because if changes
```
That dash is apparently not ASCII. Delete it.
3) Try building again.

Let me know if it works!

**Comment by icedream2linxi** [comment]
Modify protfile.cmake and then compile on it.

> 修改protfile.cmake后再编译就可以了。

`
set(CONFIGURE_COMMAND ${PERL} Configure
    enable-static-engine
    enable-capieng
    no-ssl2
    -utf-8
)
`

**Comment by bitsrules** [comment]
Thank you for fixing this issue!

**Comment by gogog22510** [comment]
Thanks for the answer!

**Comment by alexkaratarakis** [comment]
I have added a patch to remove that character in ccedc8b4333037eb4cb4a2f2d15c3684e3729dd3. 
Also, this won't be an issue in upcoming versions of openssl since it appears that the entire file was removed.
