### ISSUE TITLE
[qt-advanced-docking-system] update to 3.8.1

### ISSUE THREAD

**Issue by stijnherfst** [microsoft/vcpkg#23341]
Can [this ](https://github.com/microsoft/vcpkg/pull/22350)revert be undone? I need to use version 3.8.1 for Qt6 support and people stuck on Qt 5.15 LTS will likely stick with an older version anyways as they want stability.

**Comment by Neumann-A** [comment]
Use an overlay. My ports can be found here:
https://github.com/Neumann-A/my-vcpkg-ports
and it contains the 3.8.1 version for Qt6 with the required patches

**Comment by FrankXie05** [comment]
@stijnherfst Sorry for that, you can use Neumann-A's library, we are still talking about qt6 support. If you have other questions please re-open this issue. :)
