### ISSUE TITLE
How do I install a library with multiple specific modules?

### ISSUE THREAD

**Issue by Philip035** [microsoft/vcpkg#23345]
For example, when I try to install PCL with vcpkg , the command "vcpkg search pcl" shows that there are
pcl                      1.12.0#2         Point Cloud Library (PCL) is open source library for 2D/3D image and point...
pcl[apps]                                 Build application examples/samples that show how PCL works
pcl[cuda]                                 CUDA support for PCL
pcl[examples]                             Build PCL examples
pcl[libusb]                               Build USB RGBD-Camera drivers
pcl[opengl]                               OpenGL support for PCL
pcl[openni2]                              OpenNI2 support for PCL
pcl[pcap]                                 PCAP support for PCL
pcl[qt]                                   Qt support for PCL
pcl[simulation]                           Build Point Cloud Library Simulation
pcl[tools]                                Build PCL utilities
pcl[visualization]                        Build visualization
pcl[vtk]

So, if I want to install modules [cuda] and [visualization] at the same time, how can I realize that?

**Comment by Philip035** [comment]
> These are "features", and you want to do `vcpkg install pcl[cuda,visualization]`.

 I am so grateful for your help and patience!

**Comment by FrankXie05** [comment]
@Philip035 Is your problem solved? :)

**Comment by Philip035** [comment]
> @Philip035 Is your problem solved? :)

Of course, I will close this issue  :)
