### ISSUE TITLE
[cgns] port do not generate the CMake config files

### ISSUE THREAD

**Issue by joao-aguirre** [microsoft/vcpkg#23351]
The CGNS port is not generating any CMake config files (something like `CGNSConfig.cmake` or `cgns-config.cmake`).

In order to use the built package, one has to manually configure the include and linking paths.

**Comment by Neumann-A** [comment]
Not a vcpkg issue. CGNS only exports targets on the current development branch of cgns. So unless they make a new release and the port in vcpkg needs updating there is nothing more to do here.

**Comment by joao-aguirre** [comment]
Ok, thank you for the answer!
Closing the issue.
