### ISSUE TITLE
[New Port Request] ThorVG

### ISSUE THREAD

**Issue by daljit97** [microsoft/vcpkg#23353]
Library name: ThorVG

Library description: ThorVG is a platform-independent portable library for drawing vector-based scenes and animation.

Source repository URL: https://github.com/Samsung/thorvg

Project homepage (if different from the source repository): https://github.com/Samsung/thorvg

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
