### ISSUE TITLE
How do I specify specific msvc compiler to be used for building

### ISSUE THREAD

**Issue by RamadanAhmed** [microsoft/vcpkg#23359]
I have Visual studio 2022 and 2019 and I want to continue to use 2019 for building packages but it always default to visual studio 2022 compiler

**Comment by FrankXie05** [comment]
@RamadanAhmed Thanks for posting this issue, you can add this parameter `-G"Visual Studio 16 2019"`

**Comment by RamadanAhmed** [comment]
I use CMake Presets with Ninja generator also using vcpkg mainfest 
How I pass this parameter ?

**Comment by FrankXie05** [comment]
@RamadanAhmed Sorry, I replied is the specified method of building the project, 
 you can use this `VCPKG_PLATFORM_TOOLSET` to set the specified version of `VS`. :)
 see: https://github.com/microsoft/vcpkg/blob/master/docs/users/triplets.md
