### ISSUE TITLE
[New Port Request] ODPI-C

### ISSUE THREAD

**Issue by cjbj** [microsoft/vcpkg#23360]
Library name: ODPI-C

Library description:  Oracle Database Programming Interface for C (ODPI-C) is an open source library of C code that simplifies access to Oracle Database for applications written in C or C++. It is a wrapper over [Oracle Call Interface (OCI)](http://www.oracle.com/technetwork/database/features/oci/index.html) that makes applications and language interfaces easier to develop.

Source repository URL: https://github.com/oracle/odpi

Project homepage (if different from the source repository): https://oracle.github.io/odpi/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

ODPI-C is maintained by Oracle.  Compilation doesn't require any Oracle software or headers to be available.  It dynamically loads Oracle Client libraries at runtime.  

@LilyWangLL I saw you were testing OCILIB in https://github.com/vrogier/ocilib/issues/297.  The ODPI-C library has some similarities to @[vrogier](https://github.com/vrogier)'s excellent OCILIB because it simplifies access to Oracle's OCI library, although the ODPI-C target user is more specialized. It would great to have ODPI-C in vcpkg for users who use it as a standalone library.

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
