### ISSUE TITLE
boost-python links against release python in debug builds

### ISSUE THREAD

**Issue by Osyotr** [microsoft/vcpkg#23374]
**Describe the bug**
Applications that use `boost-python` fail to link in debug build because `python*.lib` is not found. `python*_d.lib` should be used instead.
If I put `BOOST_DEBUG_PYTHON` into my custom triplet, `boost-python` build fails with `LINK : fatal error LNK1104: cannot open file 'python27_d.lib'`

**Environment**
- OS: Windows
- Compiler: MSVC v143

**To Reproduce**
1. `vcpkg install boost-python[python2,python3]:x64-windows`
2. Check runtime dependencies of `debug/bin/boost_python*.dll`.

**Expected behavior**
`boost-python` links against `python*_d.dll`, not `python*.dll`

**Comment by JackBoosY** [comment]
Related to my PR https://github.com/microsoft/vcpkg/pull/23318 ?

**Comment by Osyotr** [comment]
@JackBoosY no, this is unrelated.
Looking at logs, it seems that boost-python picks up system python instead of vcpkg's.
