### ISSUE TITLE
Make package-specific workarounds in cmake toolchain file conditional on that package being installed

### ISSUE THREAD

**Issue by rpavlik** [microsoft/vcpkg#2337]
There are a few parts of the CMake toolchain file that apply what I can only really describe as workarounds, presumably to avoid finding a system-wide install of a package, or to modify how a specific package is searched for (Boost, OpenSSL, ICU, TIFF). The first line that is one of these is this, though some are clustered there, while others are embedded in the `find_package()` override: https://github.com/Microsoft/vcpkg/blob/48c4b79be510c5aff3f28079b7875a95497691e5/scripts/buildsystems/vcpkg.cmake#L98 

However, they're presently applied unconditionally, even when, e.g. Boost has officially-provided binaries with installers that use a reliable default, and so a user might not think it necessary to build those packages with vcpkg.

It would be good if there was conditionals around all of those workarounds that would only apply them if the package in question is actually installed in the current triplet, to make it less invasive. Presumably a helper macro checking if a package was included in a triplet would be required for an elegant solution (that is, one without repetitive code).

See discussion started here: https://github.com/Microsoft/vcpkg/commit/3d8ba3e775c13816f4c298ba16b8094e2affc4dd#commitcomment-26148642

**Comment by NancyLi1013** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen.
