### ISSUE TITLE
[boost-regex] Build error

### ISSUE THREAD

**Issue by SheFire** [microsoft/vcpkg#23370]
**Host Environment**
win10 use vcpkg install boost-regex  version:1.78.0

**To Reproduce**
`./vcpkg install zlib boost-iostreams boost-program-options boost-system boost-serialization eigen3 cgal[core] opencv glew glfw3

**Failure logs** 
this is log file :
ERROR: rule "boostcpp.set-version" unknown in module "Jamfile<C:\openMVG_MVS\vcpkg\buildtrees\boost-regex\src\ost-1.78.0-c212e9f671.clean>".

cmd output:
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:158 (message):
    Command failed: C:/openMVG_MVS/vcpkg/downloads/tools/cmake-3.22.2-windows/cmake-3.22.2-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j9
    Working Directory: C:/openMVG_MVS/vcpkg/buildtrees/boost-regex/x64-windows-dbg
    See logs for more information:
      C:\openMVG_MVS\vcpkg\buildtrees\boost-regex\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:111 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
  installed/x64-windows/share/boost-build/boost-modular-build.cmake:124 (vcpkg_cmake_install)
  ports/boost-regex/portfile.cmake:15 (boost_modular_build)
  scripts/ports.cmake:145 (include)

Error: Building package boost-regex:x64-windows failed with: BUILD_FAILED

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Could you please provide the log file `C:\openMVG_MVS\vcpkg\buildtrees\boost-regex\install-x64-windows-dbg-out.log`? I can't get more information from this message:
`ERROR: rule "boostcpp.set-version" unknown in module "Jamfile<C:\openMVG_MVS\vcpkg\buildtrees\boost-regex\src\ost-1.78.0-c212e9f671.clean>".`

**Comment by SheFire** [comment]
[1/2] cmd.exe /C "cd /D C:\openMVG_MVS\vcpkg\buildtrees\boost-regex\src\ost-1.78.0-c212e9f671.clean\build && C:\openMVG_MVS\vcpkg\installed\x64-windows\tools\boost-build\b2.exe toolset=msvc --user-config=C:/openMVG_MVS/vcpkg/buildtrees/boost-regex/x64-windows-dbg/user-config.jam --stagedir=C:/openMVG_MVS/vcpkg/buildtrees/boost-regex/x64-windows-dbg/stage --build-dir=C:/openMVG_MVS/vcpkg/buildtrees/boost-regex/x64-windows-dbg runtime-link=shared link=shared address-model=64 architecture=x86 target-os=windows threadapi=win32 variant=debug --disable-icu --with-atomic --with-random --with-date_time --with-filesystem --with-system --with-thread --with-chrono -j8 -sBOOST_ROOT=C:/openMVG_MVS/vcpkg/installed/x64-windows/tools/boost-build -sBOOST_BUILD_PATH=C:/openMVG_MVS/vcpkg/installed/x64-windows/tools/boost-build --debug-configuration --debug-building --debug-generators --ignore-site-config --hash -q debug-symbols=on -d +2 threading=multi stage"
FAILED: CMakeFiles/boost C:/openMVG_MVS/vcpkg/buildtrees/boost-regex/x64-windows-dbg/CMakeFiles/boost 
cmd.exe /C "cd /D C:\openMVG_MVS\vcpkg\buildtrees\boost-regex\src\ost-1.78.0-c212e9f671.clean\build && C:\openMVG_MVS\vcpkg\installed\x64-windows\tools\boost-build\b2.exe toolset=msvc --user-config=C:/openMVG_MVS/vcpkg/buildtrees/boost-regex/x64-windows-dbg/user-config.jam --stagedir=C:/openMVG_MVS/vcpkg/buildtrees/boost-regex/x64-windows-dbg/stage --build-dir=C:/openMVG_MVS/vcpkg/buildtrees/boost-regex/x64-windows-dbg runtime-link=shared link=shared address-model=64 architecture=x86 target-os=windows threadapi=win32 variant=debug --disable-icu --with-atomic --with-random --with-date_time --with-filesystem --with-system --with-thread --with-chrono -j8 -sBOOST_ROOT=C:/openMVG_MVS/vcpkg/installed/x64-windows/tools/boost-build -sBOOST_BUILD_PATH=C:/openMVG_MVS/vcpkg/installed/x64-windows/tools/boost-build --debug-configuration --debug-building --debug-generators --ignore-site-config --hash -q debug-symbols=on -d +2 threading=multi stage"
notice: found boost-build.jam at C:/openMVG_MVS/vcpkg/installed/x64-windows/tools/boost-build/boost-build.jam
notice: loading B2 from C:/openMVG_MVS/vcpkg/installed/x64-windows/tools/boost-build/src/kernel/bootstrap.jam
notice: Site configuration files will be ignored due to the
notice: --ignore-site-config command-line option.
notice: Loading explicitly specified user configuration file:
    C:\openMVG_MVS\vcpkg\buildtrees\boost-regex\x64-windows-dbg\user-config.jam
notice: Searching 'C:\openMVG_MVS\vcpkg\buildtrees\boost-regex\x64-windows-dbg' for user-config configuration file 'user-config.jam'.
notice: Loading user-config configuration file 'user-config.jam' from 'C:/openMVG_MVS/vcpkg/buildtrees/boost-regex/x64-windows-dbg'.
C:\openMVG_MVS\vcpkg\buildtrees\boost-regex\x64-windows-dbg\user-config.jam:8: Unescaped special character in argument <linkflags>/machine:x64
notice: [msvc-cfg] msvc-14.2 detected, command: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\bin\Hostx64\arm64\cl.exe'
notice: will use 'C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe' for msvc, condition <toolset>msvc-142
notice: [msvc-cfg] condition: '<toolset>msvc-142/<architecture>x86/<address-model>32', setup: 'C:/openMVG_MVS/vcpkg/installed/x64-windows/share/boost-build/nothing.bat x86'
notice: [msvc-cfg] condition: '<toolset>msvc-142/<architecture>/<address-model>32', setup: 'C:/openMVG_MVS/vcpkg/installed/x64-windows/share/boost-build/nothing.bat x86'
notice: [msvc-cfg] condition: '<toolset>msvc-142/<architecture>x86/<address-model>64', setup: 'C:/openMVG_MVS/vcpkg/installed/x64-windows/share/boost-build/nothing.bat amd64'
notice: [msvc-cfg] condition: '<toolset>msvc-142/<architecture>/<address-model>64', setup: 'C:/openMVG_MVS/vcpkg/installed/x64-windows/share/boost-build/nothing.bat amd64'
notice: [msvc-cfg] condition: '<toolset>msvc-142/<architecture>x86/<address-model>', setup: 'C:/openMVG_MVS/vcpkg/installed/x64-windows/share/boost-build/nothing.bat amd64'
notice: [msvc-cfg] condition: '<toolset>msvc-142/<architecture>/<address-model>', setup: 'C:/openMVG_MVS/vcpkg/installed/x64-windows/share/boost-build/nothing.bat amd64'
notice: [msvc-cfg] condition: '<toolset>msvc-142/<architecture>ia64/<address-model>64', setup: 'C:/openMVG_MVS/vcpkg/installed/x64-windows/share/boost-build/nothing.bat x86_ia64'
notice: [msvc-cfg] condition: '<toolset>msvc-142/<architecture>ia64/<address-model>', setup: 'C:/openMVG_MVS/vcpkg/installed/x64-windows/share/boost-build/nothing.bat x86_ia64'
notice: [msvc-cfg] condition: '<toolset>msvc-142/<architecture>arm/<address-model>32', setup: 'C:/openMVG_MVS/vcpkg/installed/x64-windows/share/boost-build/nothing.bat x86_arm'
notice: [msvc-cfg] condition: '<toolset>msvc-142/<architecture>arm/<address-model>64', setup: 'C:/openMVG_MVS/vcpkg/installed/x64-windows/share/boost-build/nothing.bat x86_arm64'
C:/openMVG_MVS/vcpkg/installed/x64-windows/tools/boost-build\boostcpp.jam:2: Unescaped special character in argument url=(0050)https://www.boost.org/doc/libs/1_78_0/boostcpp.jam
C:/openMVG_MVS/vcpkg/installed/x64-windows/tools/boost-build\boostcpp.jam:3: Unescaped special character in argument xml:lang=en><head><meta
C:/openMVG_MVS/vcpkg/installed/x64-windows/tools/boost-build\boostcpp.jam:8: Unescaped special character in argument <!--[if
C:/openMVG_MVS/vcpkg/installed/x64-windows/tools/boost-build\boostcpp.jam:8: Unescaped special character in argument 7]>
C:/openMVG_MVS/vcpkg/installed/x64-windows/tools/boost-build\boostcpp.jam:8: syntax error at keyword {
..\Jamroot.jam:8: in modules.load
ERROR: rule "boostcpp.set-version" unknown in module "Jamfile<C:\openMVG_MVS\vcpkg\buildtrees\boost-regex\src\ost-1.78.0-c212e9f671.clean>".
C:/openMVG_MVS/vcpkg/installed/x64-windows/tools/boost-build/src/build\project.jam:372: in load-jamfile
C:/openMVG_MVS/vcpkg/installed/x64-windows/tools/boost-build/src/build\project.jam:64: in load
C:/openMVG_MVS/vcpkg/installed/x64-windows/tools/boost-build/src/build\project.jam:109: in load-parent
C:/openMVG_MVS/vcpkg/installed/x64-windows/tools/boost-build/src/build\project.jam:513: in initialize
C:/openMVG_MVS/vcpkg/installed/x64-windows/tools/boost-build/src/build\project.jam:348: in load-jamfile
C:/openMVG_MVS/vcpkg/installed/x64-windows/tools/boost-build/src/build\project.jam:64: in load
C:/openMVG_MVS/vcpkg/installed/x64-windows/tools/boost-build/src/build\project.jam:142: in project.find
C:/openMVG_MVS/vcpkg/installed/x64-windows/tools/boost-build/src\build-system.jam:618: in load
C:/openMVG_MVS/vcpkg/installed/x64-windows/tools/boost-build/src/kernel\modules.jam:294: in import
C:/openMVG_MVS/vcpkg/installed/x64-windows/tools/boost-build/src/kernel/bootstrap.jam:139: in boost-build
C:/openMVG_MVS/vcpkg/installed/x64-windows/tools/boost-build/boost-build.jam:8: in module scope
ninja: build stopped: subcommand failed.

**Comment by minorai** [comment]
Hello, I have a similar issue
`./vcpkg install boost-regex:x64-windows`

vcpkg output

```
Computing installation plan...
The following packages will be built and installed:
    boost-regex[core]:x64-windows -> 1.78.0
Detecting compiler hash for triplet x64-windows...
Restored 0 packages from C:\Users\gush\AppData\Local\vcpkg\archives in 265.5 us. Use --debug to see more details.
Starting package 1/1: boost-regex:x64-windows
Building package boost-regex[core]:x64-windows...
-- Using cached boostorg-regex-boost-1.78.0.tar.gz.
-- Cleaning sources at E:/gush/projects/vcpkg/buildtrees/boost-regex/src/ost-1.78.0-c212e9f671.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/gush/projects/vcpkg/downloads/boostorg-regex-boost-1.78.0.tar.gz
-- Using source at E:/gush/projects/vcpkg/buildtrees/boost-regex/src/ost-1.78.0-c212e9f671.clean
-- Including E:/gush/projects/vcpkg/ports/boost-regex/b2-options.cmake
-- Found external ninja('1.10.2').
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:128 (message):
    Command failed: ninja -v
    Working Directory: E:/gush/projects/vcpkg/buildtrees/boost-regex/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      E:\gush\projects\vcpkg\buildtrees\boost-regex\config-x64-windows-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:362 (vcpkg_execute_required_process)
  installed/x64-windows/share/boost-build/boost-modular-build.cmake:108 (vcpkg_cmake_configure)
  ports/boost-regex/portfile.cmake:15 (boost_modular_build)
  scripts/ports.cmake:145 (include)


Error: Building package boost-regex:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-regex
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[boost-regex]+Build+error
including:
  package: boost-regex[core]:x64-windows -> 1.78.0
    vcpkg-tool version: 2022-02-24-7efe7f2b04912a7d674f86a406f9f2711c0221c6
    vcpkg-scripts version: bd602277b 2022-03-04 (12 hours ago)

Additionally, attach any relevant sections from the log files above.
```

E:\gush\projects\vcpkg\buildtrees\boost-regex\config-x64-windows-out.log file
```
[1/2] "E:/gush/projects/vcpkg/downloads/tools/cmake-3.22.2-windows/cmake-3.22.2-windows-i386/bin/cmake.exe" -S "E:/gush/projects/vcpkg/installed/x64-windows/share/boost-build" -B .. "-DPORT=boost-regex" "-DFEATURES=core" "-DCURRENT_INSTALLED_DIR=E:/gush/projects/vcpkg/installed/x64-windows" "-DB2_EXE=E:/gush/projects/vcpkg/installed/x64-windows/tools/boost-build/b2.exe" "-DSOURCE_PATH=E:/gush/projects/vcpkg/buildtrees/boost-regex/src/ost-1.78.0-c212e9f671.clean" "-DBOOST_BUILD_PATH=E:/gush/projects/vcpkg/installed/x64-windows/tools/boost-build" "-DVCPKG_CRT_LINKAGE=dynamic" "-DBOOST_CMAKE_FRAGMENT=E:/gush/projects/vcpkg/ports/boost-regex/b2-options.cmake" "MAYBE_UNUSED_VARIABLES" "FEATURES" "-DCMAKE_MAKE_PROGRAM=C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=E:/gush/projects/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v142" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=E:/gush/projects/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_LINKER_FLAGS_RELEASE=" "-DVCPKG_LINKER_FLAGS_DEBUG=" "-DVCPKG_TARGET_ARCHITECTURE=x64" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=E:/gush/projects/vcpkg" "-D_VCPKG_INSTALLED_DIR=E:/gush/projects/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF" "-DCMAKE_DISABLE_SOURCE_CHANGES=ON" -G "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=E:/gush/projects/vcpkg/packages/boost-regex_x64-windows"
FAILED: ../CMakeCache.txt 
"E:/gush/projects/vcpkg/downloads/tools/cmake-3.22.2-windows/cmake-3.22.2-windows-i386/bin/cmake.exe" -S "E:/gush/projects/vcpkg/installed/x64-windows/share/boost-build" -B .. "-DPORT=boost-regex" "-DFEATURES=core" "-DCURRENT_INSTALLED_DIR=E:/gush/projects/vcpkg/installed/x64-windows" "-DB2_EXE=E:/gush/projects/vcpkg/installed/x64-windows/tools/boost-build/b2.exe" "-DSOURCE_PATH=E:/gush/projects/vcpkg/buildtrees/boost-regex/src/ost-1.78.0-c212e9f671.clean" "-DBOOST_BUILD_PATH=E:/gush/projects/vcpkg/installed/x64-windows/tools/boost-build" "-DVCPKG_CRT_LINKAGE=dynamic" "-DBOOST_CMAKE_FRAGMENT=E:/gush/projects/vcpkg/ports/boost-regex/b2-options.cmake" "MAYBE_UNUSED_VARIABLES" "FEATURES" "-DCMAKE_MAKE_PROGRAM=C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=E:/gush/projects/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v142" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=E:/gush/projects/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_LINKER_FLAGS_RELEASE=" "-DVCPKG_LINKER_FLAGS_DEBUG=" "-DVCPKG_TARGET_ARCHITECTURE=x64" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=E:/gush/projects/vcpkg" "-D_VCPKG_INSTALLED_DIR=E:/gush/projects/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF" "-DCMAKE_DISABLE_SOURCE_CHANGES=ON" -G "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=E:/gush/projects/vcpkg/packages/boost-regex_x64-windows"
CMake Error: The source directory "E:/gush/projects/vcpkg/buildtrees/boost-regex/x64-windows-rel/vcpkg-parallel-configure/FEATURES" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
[2/2] "E:/gush/projects/vcpkg/downloads/tools/cmake-3.22.2-windows/cmake-3.22.2-windows-i386/bin/cmake.exe" -S "E:/gush/projects/vcpkg/installed/x64-windows/share/boost-build" -B "../../x64-windows-dbg" "-DPORT=boost-regex" "-DFEATURES=core" "-DCURRENT_INSTALLED_DIR=E:/gush/projects/vcpkg/installed/x64-windows" "-DB2_EXE=E:/gush/projects/vcpkg/installed/x64-windows/tools/boost-build/b2.exe" "-DSOURCE_PATH=E:/gush/projects/vcpkg/buildtrees/boost-regex/src/ost-1.78.0-c212e9f671.clean" "-DBOOST_BUILD_PATH=E:/gush/projects/vcpkg/installed/x64-windows/tools/boost-build" "-DVCPKG_CRT_LINKAGE=dynamic" "-DBOOST_CMAKE_FRAGMENT=E:/gush/projects/vcpkg/ports/boost-regex/b2-options.cmake" "MAYBE_UNUSED_VARIABLES" "FEATURES" "-DCMAKE_MAKE_PROGRAM=C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=E:/gush/projects/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v142" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=E:/gush/projects/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_LINKER_FLAGS_RELEASE=" "-DVCPKG_LINKER_FLAGS_DEBUG=" "-DVCPKG_TARGET_ARCHITECTURE=x64" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=E:/gush/projects/vcpkg" "-D_VCPKG_INSTALLED_DIR=E:/gush/projects/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF" "-DCMAKE_DISABLE_SOURCE_CHANGES=ON" -G "Ninja" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_INSTALL_PREFIX=E:/gush/projects/vcpkg/packages/boost-regex_x64-windows/debug"
FAILED: ../../x64-windows-dbg/CMakeCache.txt 
"E:/gush/projects/vcpkg/downloads/tools/cmake-3.22.2-windows/cmake-3.22.2-windows-i386/bin/cmake.exe" -S "E:/gush/projects/vcpkg/installed/x64-windows/share/boost-build" -B "../../x64-windows-dbg" "-DPORT=boost-regex" "-DFEATURES=core" "-DCURRENT_INSTALLED_DIR=E:/gush/projects/vcpkg/installed/x64-windows" "-DB2_EXE=E:/gush/projects/vcpkg/installed/x64-windows/tools/boost-build/b2.exe" "-DSOURCE_PATH=E:/gush/projects/vcpkg/buildtrees/boost-regex/src/ost-1.78.0-c212e9f671.clean" "-DBOOST_BUILD_PATH=E:/gush/projects/vcpkg/installed/x64-windows/tools/boost-build" "-DVCPKG_CRT_LINKAGE=dynamic" "-DBOOST_CMAKE_FRAGMENT=E:/gush/projects/vcpkg/ports/boost-regex/b2-options.cmake" "MAYBE_UNUSED_VARIABLES" "FEATURES" "-DCMAKE_MAKE_PROGRAM=C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=E:/gush/projects/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v142" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=E:/gush/projects/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_LINKER_FLAGS_RELEASE=" "-DVCPKG_LINKER_FLAGS_DEBUG=" "-DVCPKG_TARGET_ARCHITECTURE=x64" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=E:/gush/projects/vcpkg" "-D_VCPKG_INSTALLED_DIR=E:/gush/projects/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF" "-DCMAKE_DISABLE_SOURCE_CHANGES=ON" -G "Ninja" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_INSTALL_PREFIX=E:/gush/projects/vcpkg/packages/boost-regex_x64-windows/debug"
CMake Error: The source directory "E:/gush/projects/vcpkg/buildtrees/boost-regex/x64-windows-rel/vcpkg-parallel-configure/FEATURES" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
ninja: build stopped: subcommand failed.
```

**Comment by LilyWangLL** [comment]
@SheFire It should be `vcpkg-cmake:x64-windows` package was outdated, please upgrade it and try again. Similar issue: https://github.com/microsoft/vcpkg/issues/24317

**Comment by LilyWangLL** [comment]
@minorai `Boost` has been updated to 1.8.0, does your issue still exist on latest version of `boost`?

**Comment by minorai** [comment]
> @minorai `Boost` has been updated to 1.8.0, does your issue still exist on latest version of `boost`?

The issue was resolved for me. Thanks!

**Comment by SheFire** [comment]
thank you help&nbsp;
After this issue. I tTry a few times .finally is ok .I don’t know why BUT is solve. Thanks again&nbsp;





发自我的iPhone


------------------ Original ------------------
From: Lily Wang ***@***.***&gt;
Date: Fri,Oct 21,2022 4:37 PM
To: microsoft/vcpkg ***@***.***&gt;
Cc: SheFire ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [microsoft/vcpkg] [boost-regex] Build error (Issue #23370)





 
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
