### ISSUE TITLE
${package}-config.cmake newline problem

### ISSUE THREAD

**Issue by injae** [microsoft/vcpkg#23382]
**Describe the bug**
Line break issue in code injected in ${package}-config.cmake of vcpkg

**Environment**
- OS: macOS 11.5.1 (x86_64-apple-darwin20.6.0)
- Compiler: clang version 13.0.1

**To Reproduce**
1. ./vcpkg install serdepp
2. See error
```cmake
find_package(serdepp CONFIG REQUIRED)
target_link_libraries(main PRIVATE serdepp::serdepp)
```

**Expected behavior**
```cmake
# serdepp-config.cmake
get_filename_component(VCPKG_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_DIR}/../../" ABSOLUTE)
get_filename_component(CPPM_CURRENT_MODULE_DIR ../ ABSOLUTE)
```

**Failure logs** 
```cmake
# serdepp-config.cmake
get_filename_component(VCPKG_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_DIR}/../../" ABSOLUTE)get_filename_component(CPPM_CURRENT_MODULE_DIR ../ ABSOLUTE)
```

**Additional context**
It looks like there should be an extra line break in the part where vcpkg insert `get_filename_component(VCPKG_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_DIR}/../../" ABSOLUTE)`.
It seems to be a similar problem to #23135

**Comment by dg0yt** [comment]
This was fixed by #22236. You need to install the updated `vcpkg-cmake-config` port for the host triplet.
(And you will need to rebuild all depending ports.)

**Comment by FrankXie05** [comment]
@injae Recently `vcpkg `updated `vcpkg_cmake_config_fixup(`) to solve the absolute path problem, can you test dg0t's suggestion? :)

**Comment by injae** [comment]
### Script
```console
./vcpkg remove vcpkg-cmake-config --recurse
./vcpkg install vcpkg-cmake-config
./vcpkg install serdepp
```

### Result
After running the above script, the problem was solved.
The reason I keep getting similar issues seems to be that `vcpkg-cmake-config`  is not upgrading to `./vcpkg upgrade`.

**Comment by FrankXie05** [comment]
@injae Sorry about that, hope you can keep the latest `vcpkg `version, any questions? :)

**Comment by injae** [comment]
@FrankXie05  Thanks for your help in resolving the problem.
