### ISSUE TITLE
[darknet] Build errorincluding:

### ISSUE THREAD

**Issue by sairam1139** [microsoft/vcpkg#23386]
PS C:\Users\Umadevi\desktop\tmp\vcpkg> .\vcpkg install darknet[opencv-base,cuda,cudnn]:x64-windows
Computing installation plan...
The following packages will be built and installed:
    darknet[core,cuda,cudnn,opencv-base]:x64-windows -> 2021-04-16#1
Detecting compiler hash for triplet x64-windows...
Restored 0 packages from C:\Users\Umadevi\AppData\Local\vcpkg\archives in 176.1 us. Use --debug to see more details.
Starting package 1/1: darknet:x64-windows
Building package darknet[core,cuda,cudnn,opencv-base]:x64-windows...
-- Using cached AlexeyAB-darknet-5853e51d604712918bd2fb23bab0ec82d19a88f9.tar.gz.
-- Cleaning sources at C:/Users/Umadevi/Desktop/tmp/vcpkg/buildtrees/darknet/src/82d19a88f9-186b8a9ef8.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/Umadevi/Desktop/tmp/vcpkg/downloads/AlexeyAB-darknet-5853e51d604712918bd2fb23bab0ec82d19a88f9.tar.gz
-- Using source at C:/Users/Umadevi/Desktop/tmp/vcpkg/buildtrees/darknet/src/82d19a88f9-186b8a9ef8.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:128 (message):
    Command failed: C:/Users/Umadevi/Desktop/tmp/vcpkg/downloads/tools/cmake-3.22.2-windows/cmake-3.22.2-windows-i386/bin/cmake.exe C:/Users/Umadevi/Desktop/tmp/vcpkg/buildtrees/darknet/src/82d19a88f9-186b8a9ef8.clean -DENABLE_CUDA=ON -DENABLE_CUDNN=ON -DINSTALL_BIN_DIR:STRING=bin -DINSTALL_LIB_DIR:STRING=lib -DENABLE_OPENCV:BOOL=TRUE "-DCMAKE_MAKE_PROGRAM=C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -DBUILD_SHARED_LIBS=ON -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/Users/Umadevi/Desktop/tmp/vcpkg/scripts/toolchains/windows.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=v143 -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=C:/Users/Umadevi/Desktop/tmp/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_LINKER_FLAGS_RELEASE= -DVCPKG_LINKER_FLAGS_DEBUG= -DVCPKG_TARGET_ARCHITECTURE=x64 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -D_VCPKG_ROOT_DIR=C:/Users/Umadevi/Desktop/tmp/vcpkg -DZ_VCPKG_ROOT_DIR=C:/Users/Umadevi/Desktop/tmp/vcpkg -D_VCPKG_INSTALLED_DIR=C:/Users/Umadevi/Desktop/tmp/vcpkg/installed -DVCPKG_MANIFEST_INSTALL=OFF -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=C:/Users/Umadevi/Desktop/tmp/vcpkg/packages/darknet_x64-windows/debug
    Working Directory: C:/Users/Umadevi/Desktop/tmp/vcpkg/buildtrees/darknet/x64-windows-dbg
    Error code: 1
    See logs for more information:
      C:\Users\Umadevi\Desktop\tmp\vcpkg\buildtrees\darknet\config-x64-windows-dbg-out.log
      C:\Users\Umadevi\Desktop\tmp\vcpkg\buildtrees\darknet\config-x64-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:358 (vcpkg_execute_required_process)
  ports/darknet/portfile.cmake:34 (vcpkg_configure_cmake)
  scripts/ports.cmake:145 (include)

Error: Building package darknet:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+darknet
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[darknet]+Build+error
including:
  package: darknet[core,cuda,cudnn,opencv-base]:x64-windows -> 2021-04-16#1
    vcpkg-tool version: 2022-02-24-7efe7f2b04912a7d674f86a406f9f2711c0221c6
    vcpkg-scripts version: bd602277b 2022-03-04 (11 hours ago)

**Comment by Adela0814** [comment]
@sairam1139  please provide the full failure logs. 
```
C:\Users\Umadevi\Desktop\tmp\vcpkg\buildtrees\darknet\config-x64-windows-dbg-out.log
C:\Users\Umadevi\Desktop\tmp\vcpkg\buildtrees\darknet\config-x64-windows-dbg-err.log
```

**Comment by Adela0814** [comment]
ping for response

**Comment by sairam1139** [comment]
Problem resolved thanks for giving the reply

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
