### ISSUE TITLE
`VCPKG_CMAKE_CONFIGURE_OPTIONS` in triplets not work in manifest mode?

### ISSUE THREAD

**Issue by charles-sun0v0** [microsoft/vcpkg#23384]
**Describe the bug**
I need set a CMake variable (-DTARGET=ARMV8)  by `VCPKG_CMAKE_CONFIGURE_OPTIONS` in triplet file.

```
... 
if(PORT MATCHES "openblas")
set(VCPKG_CMAKE_CONFIGURE_OPTIONS "-DTARGET=ARMV8")
endif()
....
```
It works when I execute vcpkg install `vcpkg install openblas:arm64-linux `, but failed in manifest mode

**Comment by charles-sun0v0** [comment]
well, in manifest, it based on baseline    `"builtin-baseline": "cbc22a396c88d098247fe7f79f0913a952e1f77d"`  while I use command line under latest commit.  I believe that if use the latest commit, it will work. I will try it later.

**Comment by JackBoosY** [comment]
1. You shouldn't use `-DTARGET=ARMV8` to select the triplet. Please use `VCPKG_TARGET_TRIPLET` instead of this. See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/users/manifests.md#vcpkg_target_triplet).
2. The judgment `if(PORT MATCHES "openblas")` shouldn't be used since we can **NOT** call binaries of different architectures from each other.

**Comment by charles-sun0v0** [comment]
@JackBoosY  It is a make variable of openblas itself rather than the triplet.  Cause I use it on a arm64 docker on qemu kvm which based on x86_64 host, it fail to get cpu target then I need to set this variable `TARGET=ARMV8`

**Comment by JackBoosY** [comment]
> @JackBoosY It is a make variable of openblas itself rather than the triplet. Cause I use it on a arm64 docker on qemu kvm which based on x86_64 host, it fail to get cpu target then I need to set this variable `TARGET=ARMV8`

The function `vcpkg_configure_make` will choose the correct `TARGET` based on the triple you choose, so you don't need to pass it in.

**Comment by charles-sun0v0** [comment]
> The function `vcpkg_configure_make` will choose the correct `TARGET` based on the triple you choose, so you don't need to pass it in.
I've used triplet `arm64-linux` but openblas complains that 
> CMake Error at CMakeLists.txt:139 (message):
  Detecting CPU failed.  Please set TARGET explicitly, e.g.  make
  TARGET=your_cpu_target.  Please read README for details.
so should I create a new triplets and set VCPKG_TARGET_ARCHITECTURE as `armv8` ?

**Comment by JackBoosY** [comment]
> so should I create a new triplet and set VCPKG_TARGET_ARCHITECTURE as ARMV8 ?

 Correct.

**Comment by charles-sun0v0** [comment]
Note that the `TARGET` here is defined in [openblas](https://github.com/xianyi/OpenBLAS/blob/develop/TargetList.txt) itself, I don't understand it will have something with vcpkg triplet

**Comment by JackBoosY** [comment]
triplet file -> toolchain file -> vcpkg_configure_cmake -> CMakeLists.txt

**Comment by JackBoosY** [comment]
For cmake, I think you should set `-DCORE=ARMV8` right?

**Comment by charles-sun0v0** [comment]
> For cmake, I think you should set `-DCORE=ARMV8` right?
Almost like this, I should set `-DTARGET=ARMV8`.

**Comment by JackBoosY** [comment]
> > For cmake, I think you should set `-DCORE=ARMV8` right?
> 
> Yes, almost like this, I should set `-DTARGET=ARMV8`.

https://github.com/xianyi/OpenBLAS/blob/f4d1f0333b98334745f7b61d8f6362c0d09f58f4/cmake/system.cmake#L33-L48
```cmake
if (DEFINED BINARY AND DEFINED TARGET AND BINARY EQUAL 32)
  message(STATUS "Compiling a ${BINARY}-bit binary.")
  set(NO_AVX 1)
  if (${TARGET} STREQUAL "HASWELL" OR ${TARGET} STREQUAL "SANDYBRIDGE" OR ${TARGET} STREQUAL "SKYLAKEX" OR ${TARGET} STREQUAL "COOPERLAKE" OR ${TARGET} STREQUAL "SAPPHIRERAPIDS")
    set(TARGET "NEHALEM")
  endif ()
  if (${TARGET} STREQUAL "BULLDOZER" OR ${TARGET} STREQUAL "PILEDRIVER" OR ${TARGET} STREQUAL "ZEN")
    set(TARGET "BARCELONA")
  endif ()
  if (${TARGET} STREQUAL "ARMV8" OR ${TARGET} STREQUAL "CORTEXA57" OR ${TARGET} STREQUAL "CORTEXA53" OR ${TARGET} STREQUAL "CORTEXA55")
    set(TARGET "ARMV7")
  endif ()
  if (${TARGET} STREQUAL "POWER8" OR ${TARGET} STREQUAL "POWER9" OR ${TARGET} STREQUAL "POWER10")
    set(TARGET "POWER6")
  endif ()
endif ()
```

**Comment by JackBoosY** [comment]
You can use overlay-ports to build (copy _ports/openblas_ and add `-DTARGET=ARMV8` to `vcpkg_cmake_configure` ), see https://github.com/microsoft/vcpkg/blob/master/docs/specifications/ports-overlay.md

**Comment by charles-sun0v0** [comment]
@JackBoosY Thanks a lot. I think your advice could help a lot.

 btw, `VCPKG_CMAKE_CONFIGURE_OPTIONS` in a triplet file like `arm64-linux.cmake` mentioned above also worked to build `openblas` successfully, is there any side-effect in this way?

**Comment by JackBoosY** [comment]
@charles-sun0v0 I checked our document, it shows that you also can use `VCPKG_CMAKE_CONFIGURE_OPTIONS`: add the following code to your custom triplet files:
```cmake
if(PORT MATCHES "openblas")
   set(VCPKG_CMAKE_CONFIGURE_OPTIONS "-DTARGET=ARMV8")
endif()
```

**Comment by dg0yt** [comment]
> btw, `VCPKG_CMAKE_CONFIGURE_OPTIONS` in a triplet file like `arm64-linux.cmake` mentioned above also worked to build `openblas` successfully, is there any side-effect in this way?

The triplet file content affects ABI hashing, so any change needs rebuilding the cached artifacts.

**Comment by charles-sun0v0** [comment]
Thank you!
