### ISSUE TITLE
Links to mardown on release page doesn't work

### ISSUE THREAD

**Issue by KindDragon** [microsoft/vcpkg#23387]
Each link to markdown on page https://github.com/microsoft/vcpkg/releases return error 404

**Comment by JackBoosY** [comment]
Yeah, the prefix is _https://github.com/microsoft/vcpkg/blob/2022.02.23/_.
@BillyONeal Do we have a way to fix the log generator?

**Comment by BillyONeal** [comment]
Yes, it's right here: https://github.com/microsoft/vcpkg/blob/5962cf5a3bfc2124e8de991a4e45a8edcb3b4c69/scripts/Get-Changelog.ps1#L427

**Comment by KindDragon** [comment]
@BillyONeal still links to markdown files for release 2022.03.10 doesn't work properly
