### ISSUE TITLE
[ffmpeg] Build error

### ISSUE THREAD

**Issue by rara-by** [microsoft/vcpkg#23389]
**Host Environment**
- OS: Windows 11
- 

**To Reproduce**
`./vcpkg install ffmpeg

**Failure logs** 
-Computing installation plan...
The following packages will be built and installed:
    ffmpeg[avcodec,avdevice,avfilter,avformat,core,swresample,swscale]:x64-windows -> 4.4.1#10
Detecting compiler hash for triplet x64-windows...
Restored 0 packages from C:\Users\user\AppData\Local\vcpkg\archives in 221.2 us. Use --debug to see more details.
Starting package 1/1: ffmpeg:x64-windows
Building package ffmpeg[avcodec,avdevice,avfilter,avformat,core,swresample,swscale]:x64-windows...
-- Using cached ffmpeg-ffmpeg-n4.4.1.tar.gz.
-- Cleaning sources at D:/Rara/Rarababa Works/MegaMind/Age and Gender Classifier/vcpkg-master/buildtrees/ffmpeg/src/n4.4.1-070f385ab7.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/Rara/Rarababa Works/MegaMind/Age and Gender Classifier/vcpkg-master/downloads/ffmpeg-ffmpeg-n4.4.1.tar.gz
-- Applying patch 0001-create-lib-libraries.patch
-- Applying patch 0003-fix-windowsinclude.patch
-- Applying patch 0004-fix-debug-build.patch
-- Applying patch 0006-fix-StaticFeatures.patch
-- Applying patch 0007-fix-lib-naming.patch
-- Applying patch 0009-Fix-fdk-detection.patch
-- Applying patch 0010-Fix-x264-detection.patch
-- Applying patch 0011-Fix-x265-detection.patch
-- Applying patch 0012-Fix-ssl-110-detection.patch
-- Applying patch 0013-define-WINVER.patch
-- Applying patch 0014-avfilter-dependency-fix.patch
-- Applying patch 0015-Fix-xml2-detection.patch
-- Applying patch 0016-configure-dnn-needs-avformat.patch
-- Applying patch 0017-Patch-for-ticket-9019-CUDA-Compile-Broken-Using-MSVC.patch
-- Applying patch 0018-libaom-Dont-use-aom_codec_av1_dx_algo.patch
-- Applying patch 0019-libx264-Do-not-explicitly-set-X264_API_IMPORTS.patch
-- Using source at D:/Rara/Rarababa Works/MegaMind/Age and Gender Classifier/vcpkg-master/buildtrees/ffmpeg/src/n4.4.1-070f385ab7.clean
CMake Error at ports/ffmpeg/portfile.cmake:30 (message):
  Error: ffmpeg will not build with spaces in the path.  Please use a
  directory with no spaces
Call Stack (most recent call first):
  scripts/ports.cmake:145 (include)

Error: Building package ffmpeg:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+ffmpeg
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[ffmpeg]+Build+error
including:
  package: ffmpeg[avcodec,avdevice,avfilter,avformat,core,swresample,swscale]:x64-windows -> 4.4.1#10
    vcpkg-tool version: 2022-02-24-7efe7f2b04912a7d674f86a406f9f2711c0221c6
    vcpkg-scripts version: unknown

Additionally, attach any relevant sections from the log files above.

-Checking patch configure...
warning: configure has type 100644, expected 100755
Hunk #1 succeeded at 6502 (offset -33 lines).
Checking patch libavcodec/libx264.c...
Hunk #1 succeeded at 32 (offset -2 lines).
Applied patch configure cleanly.
Applied patch libavcodec/libx264.c cleanly.

**Additional context**
I am using Visual Studio 2019, Cuda 10, intend to install darknet.

**Comment by StarGate-One** [comment]
>CMake Error at ports/ffmpeg/portfile.cmake:30 (message):
>Error: ffmpeg will not build with spaces in the path. Please use a directory with no spaces

I would create a directory with no spaces in it and also use a shorter directory
I use D:\vcpkg, other suggestions would be D:\src\vcpkg or E:\git\vcpkg - I think you get the picture :)

**Comment by rara-by** [comment]
@StarGate-One 

Hi thank you for the response! I've resolved that error following your instruction but now when I try to execute the build.sh script inside the darknet folder I get the following error. Please advice

CMake suite maintained and supported by Kitware (kitware.com/cmake).
Using Ninja from D:\Rara\Work\MegaMind\AnG_Classifier\darknet-master/ninja\ninja.exe
Ninja version 1.10.2
Found vcpkg in VCPKG_ROOT: E:\vcpkg-master
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=<remote>/<branch> master

Updating vcpkg sources failed! Exited with error code 1.
Press any key to continue...

**Comment by StarGate-One** [comment]
@rara-by 
I am not sure how you are using darknet, as I am not familiar with the product... As I do not know if you are installing darknet as a port of vcpkg i.e. `vcpkg install darknet` or if you are using one of the many repos of darknet and vcpkg is being used as a submodule to provide all the pre-requisites for darknet.
Vcpkg itself is using the repo https://github.com/AlexeyAB/darknet as its port source, and would be installed with `vcpkg install darknet:(triplet)` where (triplet) can be x64-windows, x64-windows-static or the default, no triplet specified on windows is x86-windows.
If you are building darknet from one of the many other repos available, then you would need to inquire on the repo itself on the trouble/issue you are having.
Also, if you downloaded the vcpkg as a zip or tar.gz file, I would suggest cloning the vcpkg repo using git as the messages posted above seem to be showing the vcpkg instance you have is not a proper git repo, as the default branch for vcpkg is master and the upstream repo is https://github.com/microsoft/vcpkg.git
Example of installing port darknet from vcpkg:
E:
cd E:\
rmdir /q /s .\vcpkg-master (note this will delete everything inside the E:\vcpkg-master directory structure)
git clone https://github.com/microsoft/vcpkg.git .\vcpkg-master
cd .\vcpkg-master
.\bootstrap-vcpkg.bat
.\vcpkg install darknet:x64-windows (for windows x64 dynamic libraries) -and/or-
.\vcpkg install darknet (for windows x86 dynamic libraries)
vcpkg will then download/install all the tools and port/feature pre-requisites for port darknet.

**Comment by PhoebeHui** [comment]
@StarGate-One, nice to see you again!

@rara-by, there was an exist issue https://github.com/microsoft/vcpkg/issues/23386 for darknet, please open a new issue if it's a different one.

**Comment by rara-by** [comment]
Thank you!

**Comment by StarGate-One** [comment]
@rara-by you are most welcome!
@PhoebeHui Hi again. I try to help when I can, but been busy doing other things not involving vcpkg, but I do look over issue, pull requests, etc from time to time to see how things are going, with vcpkg and the vcpkg-tool.
