### ISSUE TITLE
[libwebsockets] Build error x64-windows

### ISSUE THREAD

**Issue by dohnatello** [microsoft/vcpkg#23395]
**Host Environment**
- OS: Windows 10 Pro (19043.1526)
- Compiler: Microsoft (R) C/C++ Optimizing Compiler Version 19.31.31104 for x64

**To Reproduce**
`.\vcpkg.exe install libwebsockets:x64-windows` (also fails the x86-windows install)

**Failure logs** 
```
PS C:\Users\cmjen\source\repos\vcpkg> .\vcpkg.exe install libwebsockets:x64-windows
Computing installation plan...
The following packages will be built and installed:
    libwebsockets[core]:x64-windows -> 4.3.0#2
Detecting compiler hash for triplet x64-windows...
Restored 0 packages from C:\Users\cmjen\AppData\Local\vcpkg\archives in 129.5 us. Use --debug to see more details.
Starting package 1/1: libwebsockets:x64-windows
Building package libwebsockets[core]:x64-windows...
-- Using cached warmcat-libwebsockets-a5aae049b2a386712e1be3b417915c0d44c7e675.tar.gz.
-- Cleaning sources at C:/Users/cmjen/source/repos/vcpkg/buildtrees/libwebsockets/src/0d44c7e675-2bd6d36675.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/cmjen/source/repos/vcpkg/downloads/warmcat-libwebsockets-a5aae049b2a386712e1be3b417915c0d44c7e675.tar.gz
-- Applying patch fix-dependency-libuv.patch
-- Applying patch fix-build-error.patch
-- Applying patch export-include-path.patch
-- Applying patch fix-find-openssl.patch
-- Using source at C:/Users/cmjen/source/repos/vcpkg/buildtrees/libwebsockets/src/0d44c7e675-2bd6d36675.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:128 (message):
    Command failed: ninja -v
    Working Directory: C:/Users/cmjen/source/repos/vcpkg/buildtrees/libwebsockets/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\Users\cmjen\source\repos\vcpkg\buildtrees\libwebsockets\config-x64-windows-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:415 (vcpkg_execute_required_process)
  ports/libwebsockets/portfile.cmake:139 (vcpkg_cmake_configure)
  scripts/ports.cmake:145 (include)

Error: Building package libwebsockets:x64-windows failed with: BUILD_FAILED
```
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/8192305/config-x64-windows-out.log)

**Additional context**
I just installed vcpkg on this system and had successfully installed several packages when I came across this issue with libwebsockets (I was trying to install mosquitto of which libwebsockets is a dependency).

Looks similar to #17582 except that one seems to have devolved into a pthreads issue, which isn't the problem I'm having.

**Comment by JackBoosY** [comment]
```
CMake Error at cmake/FindOpenSSLbins.cmake:47 (string):
  string sub-command REGEX, mode MATCH needs at least 5 arguments total to
  command.
Call Stack (most recent call first):
  C:/Users/cmjen/source/repos/vcpkg/scripts/buildsystems/vcpkg.cmake:795 (_find_package)
  lib/tls/CMakeLists.txt:393 (find_package)
```

**Comment by JackBoosY** [comment]
Can you please remove openssl and re-install openssl then try again?

Thanks.

**Comment by dohnatello** [comment]
I did that in a sense.  I deleted the entire 'vcpkg' directory, re-cloned vcpkg, etc.  Same outcome.

**Comment by JackBoosY** [comment]
In _FindOpenSSLbins.cmake_:
```cmake
if(OPENSSL_FOUND)

	find_program(OPENSSL_EXECUTABLE openssl openssl.exe bin/openssl.exe
		HINTS ${_OPENSSL_ROOT_HINTS}
		PATH 
			/usr/bin/ 
			bin/
	  	DOC "Openssl executable")

	mark_as_advanced(OPENSSL_EXECUTABLE)
```

**Comment by dohnatello** [comment]
OK, progress -- but still something wrong on the script(s) end.

Under "\vcpkg\installed\x64-windows\bin", openssl.exe was not present.
openssl.exe did exist under "\vcpkg\packages\openssl_x64-windows\tools\openssl"

I manually copied openssl.exe from there into "\vcpkg\installed\x64-windows\bin", reran ".\vcpkg.exe install mosquitto:x64-windows" and it installed.

So thank you for your help but there does still seem to be an issue.

**Comment by dohnatello** [comment]
For the record, the openssl dll's and lib's were in their proper locations, seems only openssl.exe was missing.

**Comment by JackBoosY** [comment]
@dohnatello Can you double confirm that the executable was installed in the _bin_ folder instead of the _tools/openssl_ folder?
Did you installed powershell manually?

**Comment by dohnatello** [comment]
No, openssl.exe was only in the tools/openssl folder.  I manually copied it to the bin folder, that's what fixed the issue.

No, I have not manually installed powershell.  It was installed with the OS (and probably auto-updated since then).

**Comment by dg0yt** [comment]
> Under "\vcpkg\installed\x64-windows\bin", openssl.exe was not present.
> openssl.exe did exist under "\vcpkg\packages\openssl_x64-windows\tools\openssl"

The filesystem layout for tools depends on build system. This cannot be fixed unless vcpkg specifies a desired layout. Cf. #17607

**Comment by dg0yt** [comment]
... but in any case, you shall expect tools somewhere under `tools`, not `bin`...

**Comment by dohnatello** [comment]
Yes, I suppose that makes sense (output locations).  I'm a novice when it comes to both cmake & vcpkg.

I will look at #17607 and try to understand it.

I still think its odd that it would be expected that I would need to do anything beyond the standard setup and execution of vcpkg.  My build system is quite ordinary.

**Comment by dohnatello** [comment]
@JackBoosY But yes, to add to the answer to your earlier question, "\vcpkg\installed\x64-windows\tools\openssl" does contain openssl.exe and I did not copy it there.

I deleted the necessary packages (and deleted the vcpkg archives) on my system to do a full reinstall of openssl, libwebsockets, and mosquitto to recreate the failure.  Upon experiencing the failure again, I can confirm the following

"\vcpkg\installed\x64-windows\tools\openssl" contains:
- libcrypto-1_1-x64.dll
- libssl-1_1-x64.dll
- openssl.cnf
- openssl.exe

"\vcpkg\installed\x64-windows\bin" contains (omitting non-openssl files):
- c_rehash.pl
- libcrypto-1_1-x64.dll
- libcrypto-1_1-x64.pdb
- libssl-1_1-x64.dll
- libssl-1_1-x64.pdb
- openssl.pdb

However, the libwebsockets configuration fails to find openssl.exe without me having to take additional measures of some sort (I haven't had a chance to go through #17607 yet).

**Comment by JackBoosY** [comment]
This is a baseline regression.

**Comment by dg0yt** [comment]
> "\vcpkg\installed\x64-windows\tools\openssl" does contain openssl.exe and I did not copy it there.

This is right. 

> However, the libwebsockets configuration fails to find openssl.exe

This indicates a problem with how the toolchain sets the search path for `find_program`.

> ```cmake
> find_program(OPENSSL_EXECUTABLE openssl openssl.exe bin/openssl.exe
> ...
> ```

You can call `set(CMAKE_FIND_DEBUG_MODE 1)` before this line for extra debug output. (And reset after this statement.)

**Comment by JackBoosY** [comment]
Reproduced, maybe related to https://github.com/microsoft/vcpkg/pull/22701.

**Comment by dohnatello** [comment]
@dg0yt 

How would you recommend I add that line to the cmake file? (remember I'm a vcpkg noob)

FindOpenSSLbins.cmake exists in the "warmcat-libwebsockets-a5aae049b2a386712e1be3b417915c0d44c7e675.tar.gz" archive and in the "/vcpkg/buildtrees/libwebsockets/src/0d44c7e675-2bd6d36675.clean" directory.

If I edit the archive it breaks the hash and if I edit the file on disk, it is deleted and replaced when I run vcpkg to test the install.

**Comment by JackBoosY** [comment]
Oh no...
```
OPENSSL_EXECUTABLE: OPENSSL_EXECUTABLE-NOTFOUND
CMAKE_PROGRAM_PATH: F:/vcpkg/installed//tools
CMAKE_PREFIX_PATH: F:/vcpkg/installed/x64-windows;F:/vcpkg/installed/x64-windows/debug
CMAKE_APPBUNDLE_PATH: 
_OPENSSL_ROOT_HINTS: F:/vcpkg/installed/x64-windows;[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\OpenSSL (32-bit)_is1;Inno Setup: App Path];[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\OpenSSL (64-bit)_is1;Inno Setup: App Path];ENV;OPENSSL_ROOT_DIR
```

@dg0yt Is this also related to the vcpkg toolchain?
