### ISSUE TITLE
[tesseract] Build error

### ISSUE THREAD

**Issue by martingeorgiu** [microsoft/vcpkg#23397]
**Host Environment**
- OS: macOS arm64
- Compiler: Apple clang version 13.0.0 (clang-1300.0.29.30)

**To Reproduce**
`./vcpkg install tesseract`

**Failure logs** 
`Error: tesseract[core] is only supported on '!arm'`

**Additional context**
It returns that tesseract is not supported on arm, even though using [official tesseract compilation guide](https://tesseract-ocr.github.io/tessdoc/Compiling.html#macos) you can compile tesseract with no problems on macos-arm64 (apart from specifying arm64 target as written in the guide).

**Comment by FrankXie05** [comment]
@autoantwort What do you think?

**Comment by autoantwort** [comment]
You can try with `--allow-unsupported`, but for me it fails with 
```
CMake Error at cmake/OptimizeForArchitecture.cmake:78 (list):
  list index: 3 out of range (-1, 0)
Call Stack (most recent call first):
  CMakeLists.txt:129 (AutodetectHostArchitecture)
```
but it seems that this file was removed in version 5.0.1. So updating tesseract to the newest version should fix the error.

**Comment by spinicist** [comment]
Hello - to add that a colleague hit this problem on a Linux arm64 box. We removed the `"supports": "!arm64"` line from the port, and it compiled fine.

**Comment by FrankXie05** [comment]
@spinicist Currently, the port `tesseract ` is being updated, we will support `arm64 `in version 5.0.1. :)
Update Pull Ruquest: #23101

**Comment by spinicist** [comment]
@FrankXie05 great - any idea when that will be merged?
