### ISSUE TITLE
Show the source website URL in the search results

### ISSUE THREAD

**Issue by DrPizza** [microsoft/vcpkg#2339]
It'd be very useful to have a link to each project's homepage, or perhaps a changelog, in the `vcpkg search` results. When updating packages there's no real indication of what's changed, so having an easy way of going to the project page would be very useful. Some of the descriptions already include a URL (or part of one; often they get cut off) but many do not.

**Comment by PhoebeHui** [comment]
@DrPizza, thanks for your suggestion, currently, some of ports has added homepage in its CONTROL file, see related commits https://github.com/microsoft/vcpkg/pull/2933
