### ISSUE TITLE
socket-io-client update to 3.1.0

### ISSUE THREAD

**Issue by LudwigBloder** [microsoft/vcpkg#23396]
Library name: socket.io-cpp-client (https://github.com/socketio/socket.io-client-cpp)

New version number: 3.1.0

Other information that may be useful (release notes, etc...)
I'd very much appreciate a proper vcpkg port of the latest version of socket.io-client-cpp (3.1.0) with proper SSL support.

Thank you and best regards
Ludwig

**Comment by FrankXie05** [comment]
Fix by PR #20883

**Comment by LudwigBloder** [comment]
Thanks for pointing out that a modified port already exists. I did 'git pull' request and triggered an upgrade with 'vcpkg upgrade' and got the error message 'socket-io-client[core] is only supported on 'static'. It then removed the package and tried to install it again, however, the same error message is issued.

Any idea what might have gone wrong?

Thanks and best regards
Ludwig

**Comment by FrankXie05** [comment]
@LudwigBloder Currently `socket-io-client`  only supports `static `builds. 
You can run eg:` .\vcpkg.exe install socket-io-client:x64-windows-static` to build package
https://github.com/microsoft/vcpkg/blob/9d45ae9d87cdc7454d6a440a892bec9c17fb38a4/ports/socket-io-client/vcpkg.json#L6
Please see the reason: https://github.com/microsoft/vcpkg/pull/20883#r733282754

**Comment by LudwigBloder** [comment]
Thank you very much!
