### ISSUE TITLE
build failure for assimp at Irrlicht dependencies

### ISSUE THREAD

**Issue by glennDittmann** [microsoft/vcpkg#23401]
Hello, 
I stumbled upon a problem, when trying to install [assimp](https://github.com/assimp/assimp). I installed vcpgk as mentioned in [Get Started](https://vcpkg.io/en/getting-started.html).

It seems that the the problem is when vcpkg is trying to fetch some `Irrlicht` depencies, when vcpkg is looking for `Irrlicht 1.8.4`.
However following the [link from the log](https://sourceforge.net/projects/irrlicht/files/Irrlicht%20SDK/1.8/1.8.4/irrlicht-1.8.4.zip/download;https://sourceforge.net/projects/irrlicht/files/Irrlicht%20SDK/1.8/1.8.4/irrlicht-1.8.4.zip/download?use_mirror=cfhcable;https://sourceforge.net/projects/irrlicht/files/Irrlicht%20SDK/1.8/1.8.4/irrlicht-1.8.4.zip/download?use_mirror=pilotfiber;https://sourceforge.net/projects/irrlicht/files/Irrlicht%20SDK/1.8/1.8.4/irrlicht-1.8.4.zip/download?use_mirror=gigenet;https://sourceforge.net/projects/irrlicht/files/Irrlicht%20SDK/1.8/1.8.4/irrlicht-1.8.4.zip/download?use_mirror=versaweb;https://sourceforge.net/projects/irrlicht/files/Irrlicht%20SDK/1.8/1.8.4/irrlicht-1.8.4.zip/download?use_mirror=ayera;https://sourceforge.net/projects/irrlicht/files/Irrlicht%20SDK/1.8/1.8.4/irrlicht-1.8.4.zip/download?use_mirror=netactuate;https://sourceforge.net/projects/irrlicht/files/Irrlicht%20SDK/1.8/1.8.4/irrlicht-1.8.4.zip/download?use_mirror=phoenixnap;https://sourceforge.net/projects/irrlicht/files/Irrlicht%20SDK/1.8/1.8.4/irrlicht-1.8.4.zip/download?use_mirror=astuteinternet;https://sourceforge.net/projects/irrlicht/files/Irrlicht%20SDK/1.8/1.8.4/irrlicht-1.8.4.zip/download?use_mirror=freefr;https://sourceforge.net/projects/irrlicht/files/Irrlicht%20SDK/1.8/1.8.4/irrlicht-1.8.4.zip/download?use_mirror=netcologne;https://sourceforge.net/projects/irrlicht/files/Irrlicht%20SDK/1.8/1.8.4/irrlicht-1.8.4.zip/download?use_mirror=deac-riga;https://sourceforge.net/projects/irrlicht/files/Irrlicht%20SDK/1.8/1.8.4/irrlicht-1.8.4.zip/download?use_mirror=excellmedia;https://sourceforge.net/projects/irrlicht/files/Irrlicht%20SDK/1.8/1.8.4/irrlicht-1.8.4.zip/download?use_mirror=iweb;https://sourceforge.net/projects/irrlicht/files/Irrlicht%20SDK/1.8/1.8.4/irrlicht-1.8.4.zip/download?use_mirror=jaist;https://sourceforge.net/projects/irrlicht/files/Irrlicht%20SDK/1.8/1.8.4/irrlicht-1.8.4.zip/download?use_mirror=jztkft;https://sourceforge.net/projects/irrlicht/files/Irrlicht%20SDK/1.8/1.8.4/irrlicht-1.8.4.zip/download?use_mirror=managedway;https://sourceforge.net/projects/irrlicht/files/Irrlicht%20SDK/1.8/1.8.4/irrlicht-1.8.4.zip/download?use_mirror=nchc;https://sourceforge.net/projects/irrlicht/files/Irrlicht%20SDK/1.8/1.8.4/irrlicht-1.8.4.zip/download?use_mirror=netix;https://sourceforge.net/projects/irrlicht/files/Irrlicht%20SDK/1.8/1.8.4/irrlicht-1.8.4.zip/download?use_mirror=ufpr;https://sourceforge.net/projects/irrlicht/files/Irrlicht%20SDK/1.8/1.8.4/irrlicht-1.8.4.zip/download?use_mirror=tene), gives an `file not found`-error and is showing `Irrlicht 1.8.5` instead.

If I am assuming correctly, the fix should be easy. 
Thanks in advance !

**Host Environment**
- Windows 11
- Compiler: revision

**To Reproduce**
`.\vcpkg.exe install assimp`

**Failure logs** 
```
Computing installation plan...
The following packages will be built and installed:
    assimp[core]:x86-windows -> 5.0.1#5
  * irrlicht[core]:x86-windows -> 1.8.4#13
  * kubazip[core]:x86-windows -> 0.1.19#1
  * minizip[core]:x86-windows -> 1.2.11#10
  * poly2tri[core]:x86-windows -> 2020-07-21#2
  * polyclipping[core]:x86-windows -> 6.4.2#10
  * rapidjson[core]:x86-windows -> 2020-09-14#2
  * stb[core]:x86-windows -> 2020-09-14#1
  * utfcpp[core]:x86-windows -> 3.2.1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x86-windows...
Restored 0 packages from C:\Users\dittm\AppData\Local\vcpkg\archives in 213.8 us. Use --debug to see more details.
Starting package 1/9: irrlicht:x86-windows
Building package irrlicht[core]:x86-windows...
-- Downloading https://sourceforge.net/projects/irrlicht/files/Irrlicht%20SDK/1.8/1.8.4/irrlicht-1.8.4.zip/download;https://sourceforge.net/projects/irrlicht/files/Irrlicht%20SDK/1.8/1.8.4/irrlicht-1.8.4.zip/download?use_mirror=cfhcable;https://sourceforge.net/projects/irrlicht/files/Irrlicht%20SDK/1.8/1.8.4/irrlicht-1.8.4.zip/download?use_mirror=pilotfiber;https://sourceforge.net/projects/irrlicht/files/Irrlicht%20SDK/1.8/1.8.4/irrlicht-1.8.4.zip/download?use_mirror=gigenet;https://sourceforge.net/projects/irrlicht/files/Irrlicht%20SDK/1.8/1.8.4/irrlicht-1.8.4.zip/download?use_mirror=versaweb;https://sourceforge.net/projects/irrlicht/files/Irrlicht%20SDK/1.8/1.8.4/irrlicht-1.8.4.zip/download?use_mirror=ayera;https://sourceforge.net/projects/irrlicht/files/Irrlicht%20SDK/1.8/1.8.4/irrlicht-1.8.4.zip/download?use_mirror=netactuate;https://sourceforge.net/projects/irrlicht/files/Irrlicht%20SDK/1.8/1.8.4/irrlicht-1.8.4.zip/download?use_mirror=phoenixnap;https://sourceforge.net/projects/irrlicht/files/Irrlicht%20SDK/1.8/1.8.4/irrlicht-1.8.4.zip/download?use_mirror=astuteinternet;https://sourceforge.net/projects/irrlicht/files/Irrlicht%20SDK/1.8/1.8.4/irrlicht-1.8.4.zip/download?use_mirror=freefr;https://sourceforge.net/projects/irrlicht/files/Irrlicht%20SDK/1.8/1.8.4/irrlicht-1.8.4.zip/download?use_mirror=netcologne;https://sourceforge.net/projects/irrlicht/files/Irrlicht%20SDK/1.8/1.8.4/irrlicht-1.8.4.zip/download?use_mirror=deac-riga;https://sourceforge.net/projects/irrlicht/files/Irrlicht%20SDK/1.8/1.8.4/irrlicht-1.8.4.zip/download?use_mirror=excellmedia;https://sourceforge.net/projects/irrlicht/files/Irrlicht%20SDK/1.8/1.8.4/irrlicht-1.8.4.zip/download?use_mirror=iweb;https://sourceforge.net/projects/irrlicht/files/Irrlicht%20SDK/1.8/1.8.4/irrlicht-1.8.4.zip/download?use_mirror=jaist;https://sourceforge.net/projects/irrlicht/files/Irrlicht%20SDK/1.8/1.8.4/irrlicht-1.8.4.zip/download?use_mirror=jztkft;https://sourceforge.net/projects/irrlicht/files/Irrlicht%20SDK/1.8/1.8.4/irrlicht-1.8.4.zip/download?use_mirror=managedway;https://sourceforge.net/projects/irrlicht/files/Irrlicht%20SDK/1.8/1.8.4/irrlicht-1.8.4.zip/download?use_mirror=nchc;https://sourceforge.net/projects/irrlicht/files/Irrlicht%20SDK/1.8/1.8.4/irrlicht-1.8.4.zip/download?use_mirror=netix;https://sourceforge.net/projects/irrlicht/files/Irrlicht%20SDK/1.8/1.8.4/irrlicht-1.8.4.zip/download?use_mirror=ufpr;https://sourceforge.net/projects/irrlicht/files/Irrlicht%20SDK/1.8/1.8.4/irrlicht-1.8.4.zip/download?use_mirror=tenet -> irrlicht-1.8.4.zip...
```

**Comment by Adela0814** [comment]
@glennDittmann Could you please provide the full failure logs?

**Comment by glennDittmann** [comment]
Hey @Adela0814,
thanks for your answer. Sure I would do so, where do I find the failure logs?

**Comment by Adela0814** [comment]
Find your vcpkg installation path and go to`\vcpkg\buildtrees\assimp\`, please upload all install and config log. Thanks

**Comment by Adela0814** [comment]
`irrlicht` dependency will be removed, This PR will keep open until PR #21605  is closed.

**Comment by glennDittmann** [comment]
Thanks for your help! So you probably don't need the failure logs any more, correct? 😄

**Comment by Adela0814** [comment]
yes, we just need wait for the PR merge.

**Comment by glennDittmann** [comment]
Thanks a lot !
