### ISSUE TITLE
How to deal with libraries that install services in systemd? [New Port]

### ISSUE THREAD

**Issue by Bardo91** [microsoft/vcpkg#23404]
I am creating a port of a library that, when running its cmake-install, it creates a new linux service (systemd and systemctl... etc.).

That requires sudo access to copy files into "/lib/systemd/system" which is not possible (as far as I know) with `vcpkg install` command.

¿How should I proceed? The library can be compiled without that service, but it is useless without it (it uses it to connect to an specific hardware)

**Comment by JackBoosY** [comment]
After using the vcpkg installation port, vcpkg will install the generated files in the vcpkg directory instead of the system path. Since vcpkg provides toolchains, there is no problem using them.
If the port contains actions to install files to system paths, we should disable them.

**Comment by dg0yt** [comment]
Vcpkg is not a system package manager. `vcpkg install ...` build results must be relocatable (cached binary artifacts).  
If you need to modify the target system, e.g. install for users, this must be a separate activity.

**Comment by Bardo91** [comment]
Thanks @JackBoosY  and @dg0yt  that makes a lot of sense. I was expecting that answer, but I preferred to make sure about it (and I hope it helps the community if the question raises to someone again).  I have already created a patch file to remove that from the CMakeList instructions.
