### ISSUE TITLE
[New Port Request] libcitygml

### ISSUE THREAD

**Issue by maz-1** [microsoft/vcpkg#23407]
Library name: libcitygml

Library description: C++ Library for CityGML Parsing and Visualization

Source repository URL: https://github.com/jklimke/libcitygml

Project homepage (if different from the source repository): 

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

depends on xercesc
depends on gdal if coordinate transformations is required
depends on osg of OpenSceneGraph plugin is enabled
A quick but dirty windows port for reference: https://github.com/maz-1/vcpkg-ports/tree/master/libcitygml

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
