### ISSUE TITLE
[New Port Request] Win Flex-Bison

### ISSUE THREAD

**Issue by mfarnz** [microsoft/vcpkg#23419]
Library name:
Win flex-bison

Library description:
Win flex-bison is a windows port the Flex (the fast lexical analyser) and Bison (GNU parser generator). win_flex based on Flex version 2.6.3 source code and win_bison based on Bison version 2.7 and they depend on system libraries only.

Source repository URL:
https://github.com/lexxmark/winflexbison

Project homepage (if different from the source repository):
https://sourceforge.net/projects/winflexbison/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by SamuelMarks** [comment]
@mfarnz See #33084 for WiP
