### ISSUE TITLE
[cpr] After recent update, HTTPS requests don't work on Windows

### ISSUE THREAD

**Issue by tluchowski** [microsoft/vcpkg#23417]
**Describe the bug**
The bug was described on cpr forum, but they say it's vcpkg issue.

Please take a look at https://github.com/libcpr/cpr/issues/704

It contains all the details, along with steps to reproduce it.

**Environment**
- OS: Windows
- Compiler: Visual Studio 2019 16.11.10

**To Reproduce**
Please take a look at link above

**Expected behavior**
Request should succeed.

**Failure logs** 
Please take a look at link above

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. This issue appeared after curl upgrade from 7.80.0 to 7.81.0. And we should be remove `vcpkg_check_linkage(ONLY_STATIC_LIBRARY)` in _VCPKG_ROOT/ports/cpr/portfile.cmake_, because it will not create *.dll when use `vcpkg_check_linkage(ONLY_STATIC_LIBRARY)`.

**Comment by acidicoala** [comment]
Can anyone elaborate on what and where the real issue is that's causing the HTTPS requests to fail?

**Comment by acidicoala** [comment]
A temporary workaround is to [pin](https://devblogs.microsoft.com/cppblog/take-control-of-your-vcpkg-dependencies-with-versioning-support/) the curl version to 7.80.0 via [manifest](https://vcpkg.readthedocs.io/en/latest/specifications/manifests/) declaration. Credit to @LilyWangLL for the hint. Example `vcpkg.json`:
```json
{
  "name": "my-project",
  "version": "1.2.3",
  "license": "MIT",
  "dependencies": [
    "cpr"
  ],
  "builtin-baseline": "aebb363eaa0b658beb19cbefdd5aa2f9cbc14f1e",
  "overrides": [
    {
      "name": "curl",
      "version": "7.80.0"
    }
  ]
}

```

**Comment by HideakiAtsuyo** [comment]
Well, it's been a while this issue is opened, is there any way it get solved in ~7 days ?

**Comment by ZRR666** [comment]
When will it be settled

**Comment by ZRR666** [comment]
> 一个临时的解决方法是通过[清单](https://vcpkg.readthedocs.io/en/latest/specifications/manifests/)声明将 curl 版本固定到 7.80.0 [。](https://devblogs.microsoft.com/cppblog/take-control-of-your-vcpkg-dependencies-with-versioning-support/)归功于[](https://vcpkg.readthedocs.io/en/latest/specifications/manifests/)@LilyWangLL提示。示例`vcpkg.json`：
> 
> ```json
> {
>    “名称”：“我的项目”，
>    “版本”：“ 1.2.3 ”，
>    “许可证”：“ MIT ”，
>    “依赖项”：[
>      “ cpr ” 
>   ]，“内置基线”：“ aebb363eaa0b658beb19cbefdd5aa2f9cbc14f1e ”，
>    “覆盖“：[ 
>     { “名称”：“卷曲”，
>        “版本”：" 7.80.0 " ,
>        "$原因"
>   
>       ：“ https://github.com/microsoft/vcpkg/issues/23417 ” 
>     } 
>   ] 
> }
> ```

Error: In manifest mode, `vcpkg install` does not support individual package arguments. 
To install additional packages, edit vcpkg. json and then run `vcpkg install` without any package arguments. 
See https://github.com/Microsoft/vcpkg/tree/master/docs/users/manifests.md for more information.

**Comment by LilyWangLL** [comment]
You can use the solution from https://github.com/microsoft/vcpkg/issues/23417#issuecomment-1100634689, I think this isn't a vcpkg issue, we can wait the reply from https://github.com/curl/curl/issues/8741 and get a clearly reason of this issue.

**Comment by m-bruchovets** [comment]
If it helps:
curl from vcpkg is working fine when used directly (tested GET request to https) and only breaks when used with CPR.

**Comment by HideakiAtsuyo** [comment]
> If it helps: curl from vcpkg is working fine when used directly (tested GET request to https) and only breaks when used with CPR.

Actually we already know that but thanks anyway :)

**Comment by HideakiAtsuyo** [comment]
acidicoala suggested to pin the curl version but it would be bad I think, it's better to update as long as CURL is updated :)

**Comment by oofsamy** [comment]
Hey, the workaround was mentioned in the issue I had with cpr, but I still have the same problem even when version pinning with the manifest file, I modified it for x64 but I don't believe that could be the reason why though, could it?

```json
{
  "name": "my-project",
  "version": "1.2.3",
  "license": "MIT",
  "dependencies": [
	{
		"name": "cpr",
		"platform": "windows & x64"
	}
  ],
  "builtin-baseline": "aebb363eaa0b658beb19cbefdd5aa2f9cbc14f1e",
  "overrides": [
    {
      "name": "curl",
      "version": "7.80.0",
      "$reason": "https://github.com/microsoft/vcpkg/issues/23417"
    }
  ]
}
```
