### ISSUE TITLE
mongo-cxx-driver:x64-windows-static build failed

### ISSUE THREAD

**Issue by rhourfar** [microsoft/vcpkg#23420]
**Host Environment**
- OS: Windows 10
- Compiler: VS2022

**To Reproduce**
`./vcpkg.exe install mongo-cxx-driver:x64-windows-static`

**Failure logs** 
Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:111 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
  ports/mongo-cxx-driver/portfile.cmake:49 (vcpkg_cmake_install)
  scripts/ports.cmake:145 (include)

Error: Building package mongo-cxx-driver:x64-windows-static failed with: BUILD_FAILED

**Additional context**

**Comment by Cheney-W** [comment]
Could you please provide the log files in buildtrees/mongo-cxx-driver?

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Now `mongo-cxx-driver:x64-windows-static` could be installed succeed on the latest vcpkg, see the following logs. Please reopen this issue with more info if this is still a problem for you.

```
Elapsed time to handle mongo-cxx-driver:x64-windows-static: 1.1075325833333334 min
Total install time: 2.424575351666667 min
mongo-cxx-driver provides CMake targets:

    find_package(bsoncxx CONFIG REQUIRED)
    target_link_libraries(main PRIVATE $<IF:$<TARGET_EXISTS:mongo::bsoncxx_static>,mongo::bsoncxx_static,mongo::bsoncxx_shared>)

    find_package(mongocxx CONFIG REQUIRED)
    target_link_libraries(main PRIVATE $<IF:$<TARGET_EXISTS:mongo::mongocxx_static>,mongo::mongocxx_static,mongo::mongocxx_shared>)
```
