### ISSUE TITLE
[libjpeg-turbo] find_package fails when built statically

### ISSUE THREAD

**Issue by reynoldsbd** [microsoft/vcpkg#23422]
****

**Is your feature request related to a problem? Please describe.**

My team likes to statically link everything on Windows, so we build our vcpkg dependencies using the following custom triplet file (saved as _path/to/my/triplets/x64-windows.cmake_):

```cmake
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE static)
```

Then, we consume libjpeg-turbo in our CMake project as follows:

```cmake
find_package(libjpeg-turbo REQUIRED)

add_executable(tjexample tjexample.c)

target_link_libraries(tjexample PRIVATE libjpeg-turbo::turbojpeg-static)
```

However, the `find_package` call fails with the following error:

```
CMake Error at D:/Source/vcpkg/installed/x64-windows/share/libjpeg-turbo/libjpeg-turboTargets.cmake:80 (message):
  The imported target "libjpeg-turbo::turbojpeg-static" references the file

     "D:/Source/vcpkg/installed/x64-windows/debug/lib/turbojpeg-static.lib"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "D:/Source/vcpkg/installed/x64-windows/share/libjpeg-turbo/libjpeg-turboTargets.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  D:/Source/vcpkg/installed/x64-windows/share/libjpeg-turbo/libjpeg-turboConfig.cmake:27 (include)
  D:/Source/vcpkg/scripts/buildsystems/vcpkg.cmake:800 (_find_package)
  CMakeLists.txt:5 (find_package)
```

libjpeg-turbo does indeed install a file named _turbojpeg-static.lib_, yet for some reason the portfile is removing the _-static_ suffix after installation. As a result, there is a mismatch between the files on disk and the generated CMake targets.

https://github.com/microsoft/vcpkg/blob/5962cf5a3bfc2124e8de991a4e45a8edcb3b4c69/ports/libjpeg-turbo/portfile.cmake#L58-L70

**Proposed solution**

I propose removing the lines mentioned above. However, I don't fully understand why those lines were added in the first place.

Adding a few people who might be able to shed some light: @drdanz, @dg0yt 

**Describe alternatives you've considered**

It is possible to work around this issue by manually passing the appropriate values to `target_include_directories` and `target_link_libraries`.

**Comment by JackBoosY** [comment]
I think the official triplet `x64-windows-static` should match your requirement, so you don't need to add a custom triplet there.

I can be sure that jpeg's static library names `jpeg.lib` in Windows static build. Can you please confirm your vcpkg is latest?

Thanks.

**Comment by dg0yt** [comment]
> I propose removing the lines mentioned above. However, I don't fully understand why those lines were added in the first place.

IIRC they were added a) to match the pkg-config files, and/or b) to make `find_library(XXX turbojpeg)` work regardless of linkage.
