### ISSUE TITLE
Deploying dynamically loaded libraries

### ISSUE THREAD

**Issue by trollixx** [microsoft/vcpkg#2343]
I am using vcpkg (via `vcpkg export`) to provide build dependencies for a CI/CD system. It works nicely with one exception - OpenSSL libraries are not automatically deployed. My project is Qt based, and Qt loads OpenSSL in the runtime, so there's no direct link dependency.

Is there a way to tell CMake to deploy a library provided by vcpkg without checking linking status?

I tried simply using  `target_link_libraries()` for the main target, but that didn't work.

**Comment by ras0219-msft** [comment]
Thanks for posting this issue!

While we should definitely look at improving the general case, in the specific case of Qt I think it would be really easy to add a special rule to handle this scenario. According to my source code diving, it looks like the Network module is causing the load.

I've pushed a branch (`qt-deploy-openssl`) -- would you mind trying it out and let me know if it works for your scenario?

- `git fetch && git checkout qt-deploy-openssl`
- `vcpkg remove qt5-base --recurse && vcpkg install qt5-base`

Whenever you build an application that uses the `QtNetwork` module, you should now get the `openssl` DLLs deployed as well.

**Comment by trollixx** [comment]
Yeah, Qt Network loads OpenSSL.

But I don't think always deploying OpenSSL libraries is a good idea. There are uses cases when Qt Network would not need to establish a secure connection, hence no need in OpenSSL. Plus Qt does not bundle OpenSSL by default, and dynamically loads it due to legal reasons.

In [my particular case](https://github.com/zealdocs/ci-vcpkg), vcpkg does not include Qt, but only other dependencies. For Qt it relies on official Qt binaries, and prebuilt Qt WebKit (since I couldn't find a free Windows CI service capable of building Qt and Qt WebKit).

**Comment by davidebeatrici** [comment]
From https://github.com/qt/qtbase/blob/13e0a36626bd75e631dd9536e795a494432b1945/src/network/doc/src/ssl.qdoc:

> By default, an SSL-enabled Qt library dynamically loads any installed OpenSSL library at run-time. However, it is possible to link against the library at compile-time by configuring Qt with the **-openssl-linked** option.
