### ISSUE TITLE
Building package sentencepiece

### ISSUE THREAD

**Issue by abdulrhman-adel** [microsoft/vcpkg#23436]
PS C:\Users\abdul\vcpkg> ./vcpkg install sentencepiece
Computing installation plan...
The following packages will be built and installed:
    sentencepiece[core]:x86-windows -> 0.1.96
Detecting compiler hash for triplet x86-windows...
Restored 0 packages from C:\Users\abdul\AppData\Local\vcpkg\archives in 443.4 us. Use --debug to see more details.
Starting package 1/1: sentencepiece:x86-windows
Building package sentencepiece[core]:x86-windows...
-- Note: sentencepiece only supports static library linkage. Building static library.
CMake Error at scripts/cmake/vcpkg_check_linkage.cmake:70 (message):
  sentencepiece only supports static crt linkage
Call Stack (most recent call first):
  ports/sentencepiece/portfile.cmake:2 (vcpkg_check_linkage)
  scripts/ports.cmake:145 (include)

Error: Building package sentencepiece:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+sentencepiece
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[sentencepiece]+Build+error
including:
  package: sentencepiece[core]:x86-windows -> 0.1.96
    vcpkg-tool version: 2022-02-24-7efe7f2b04912a7d674f86a406f9f2711c0221c6
    vcpkg-scripts version: 5962cf5a3 2022-03-07 (25 hours ago)

Additionally, attach any relevant sections from the log files above.

**Comment by FrankXie05** [comment]
@abdulrhman-adel Thanks for posting this issue. `sentencepiece `only support static library linkage, so you can build `sentencepiece:x86-windows-static` or` sentencepiece:x64-windows-static `. :)
```
Building package sentencepiece[core]:x64-windows...
-- Note: sentencepiece only supports static library linkage. Building static library.
```
https://github.com/microsoft/vcpkg/blob/40a0fb232833dbc1b526394929f10b71627c2269/ports/sentencepiece/portfile.cmake#L1-L3
