### ISSUE TITLE
Build error after package installation failed

### ISSUE THREAD

**Issue by develooper1994** [microsoft/vcpkg#23437]
**Describe the bug**
When package installation failed, strange error sometimes appears in console. I can fix it manually, but it is some type of bug in my opinion.

**Environment**
- OS: Windows-11
- Compiler: visual c++ 2022

**To Reproduce**
1. ./vcpkg install [any package]
2. After installation failed
3. The error occurs: 
"
Error: while loading [any]:
The port directory (<vcpkg_dir>\ports\[any]) does not exist
Error: failed to load port from <vcpkg_dir>\ports\[any]
Note: Updating vcpkg by rerunning bootstrap-vcpkg may resolve this failure.
Repro code when
"

**Expected behavior**
It doesn't have to see like that.

**Failure logs** 
-(please attached failure logs)

Error: while loading [any]:
The port directory (<vcpkg_dir>\ports\[any]) does not exist
Error: failed to load port from <vcpkg_dir>\ports\[any]
Note: Updating vcpkg by rerunning bootstrap-vcpkg may resolve this failure.
Repro code when

**Additional context**
How i fix it manually:
1. cd <vcpkg_dir>\installed\vcpkg
2. open status. All installed package list is here. 
3. Find the failed package
4. Remove it
5. Save the file and close
6. restart console (really close the window)
7. back to work

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Did you use the latest version of vcpkg? Or before installing port, did you run command `git pull` and `.\bootstrap-vcpkg.bat`?

**Comment by LilyWangLL** [comment]
I can't reproduce it locally, if this error appear again, please provide the screenshot on powershell, and if the failed port has error log file, please also provide to us.

**Comment by develooper1994** [comment]
Ok, I will do that.

15 Mar 2022 Sal 09:18 tarihinde LilyWangLL ***@***.***> şunu
yazdı:

**Comment by JackBoosY** [comment]
@develooper1994 Any result?

**Comment by LilyWangLL** [comment]
Since this issue has no response more than two weeks, please reopen this issue with the new information.

**Comment by Amasterworld** [comment]
I run into the same  problem, please helpppppp

**Comment by JackBoosY** [comment]
Please follow the step:
1. use command `./vcpkg list <port_name>` to search the installed triplet.
2. use command `./vcpkg remove <port_with_triplet>` to remove that item.
3. try again.
