### ISSUE TITLE
[qt] fails to build

### ISSUE THREAD

**Issue by cdcseacave** [Microsoft/vcpkg#2344]
I am trying to install CGAL using `vcpkg --triplet x64-windows install cgal` on a clean windows 10 x64 with only Visual Studio 2017 (fresh installed). It has 17 dependencies, most of them install fine, but the 16th one is `qt5` which fails:

```
-- Downloading http://download.qt.io/official_releases/qt/5.8/5.8.0/single/qt-everywhere-opensource-src-5.8.0.7z...
-- Downloading http://download.qt.io/official_releases/qt/5.8/5.8.0/single/qt-everywhere-opensource-src-5.8.0.7z... OK
-- Testing integrity of downloaded file...
-- Testing integrity of downloaded file... OK
-- Extracting source C:/Users/Wii/Desktop/Pro/vcpkg/downloads/qt-5.8.0.7z
-- Extracting done
-- Applying patch C:/Users/Wii/Desktop/Pro/vcpkg/ports/qt5/fix-qalgorithms-vs2017.patch
-- Applying patch C:/Users/Wii/Desktop/Pro/vcpkg/ports/qt5/fix-qalgorithms-vs2017.patch done
-- Applying patch C:/Users/Wii/Desktop/Pro/vcpkg/ports/qt5/fix-commandline-overrides.patch
-- Applying patch C:/Users/Wii/Desktop/Pro/vcpkg/ports/qt5/fix-commandline-overrides.patch done
-- Configuring x64-windows-rel
-- Configuring x64-windows-rel done
-- Configuring x64-windows-dbg
-- Configuring x64-windows-dbg done
-- Downloading https://www.python.org/ftp/python/3.5.4/python-3.5.4-embed-win32.zip...
-- Downloading https://www.python.org/ftp/python/3.5.4/python-3.5.4-embed-win32.zip... OK
-- Testing integrity of downloaded file...
-- Testing integrity of downloaded file... OK
-- Package x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:44 (message):
    Command failed: C:/Users/Wii/Desktop/Pro/vcpkg/downloads/tools/jom/jom-1.1.2/jom.exe;/J;4
    Working Directory: C:/Users/Wii/Desktop/Pro/vcpkg/buildtrees/qt5/x64-windows-rel
    See logs for more information:
      C:\Users\Wii\Desktop\Pro\vcpkg\buildtrees\qt5\build-x64-windows-rel-out.log
      C:\Users\Wii\Desktop\Pro\vcpkg\buildtrees\qt5\build-x64-windows-rel-err.log

Call Stack (most recent call first):
  ports/qt5/install_qt.cmake:19 (vcpkg_execute_required_process)
  ports/qt5/portfile.cmake:67 (install_qt)
  scripts/ports.cmake:72 (include)


Error: Building package qt5:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: qt5:x64-windows
  Vcpkg version: 0.0.100-2017-12-09-4567fa570916b0398ac0a65645e2074a4c8f0fd9

Additionally, attach any relevant sections from the log files above.
```

Attached are the the log files: [qt5.zip](https://github.com/Microsoft/vcpkg/files/1545711/qt5.zip)

Please help!

Thank you!

PS: I do not need QT functionality, neither stand-alone nor in CGAL; is there a way to opt out this requirement when using `vcpkg` to install CGAL? (this is for sure possible when configuring CGAL)

**Comment by ras0219-msft** [comment]
Qt is likely failing due to long path lengths -- you should hopefully have gotten a warning about this towards the top of the output :) If you rename the vcpkg path to something much shorter, this should resolve the issue.

As for opting out of QT support in CGAL -- this is exactly what feature packages are intended to solve, but it looks like CGAL hasn't been enhanced with that quite yet. You can read about feature packages in https://github.com/Microsoft/vcpkg/pull/1205. They are implemented in the current master _except_ for default features.

**Comment by cdcseacave** [comment]
Thank you for your help. Indeed, I got the warning, and I tried also with `vcpkg` placed directly on `C:`, but the result is the same :( Please see the [log](https://github.com/Microsoft/vcpkg/files/1556129/build-x64-windows-rel-err.zip).

**Comment by justinjk007** [comment]
For this reason I can't install CGAL as well. For which Qt is a dependency, but it is not a requirement. We don't need Qt for CGAL unless you are building the demos.

**Comment by ras0219-msft** [comment]
It looks like Qt is eventually pulling in `atlbase.h`:
>C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um\sphelper.h(51): fatal error C1083: Cannot open include file: 'atlbase.h': No such file or directory

Installing MFC+ATL in the VS installer should fix this issue.

**Comment by justinjk007** [comment]
How am I supposed to go about doing this in AppVeyor?

**Comment by ras0219-msft** [comment]
I believe appveyor should have ATL installed. Could you post the build logs if you're having trouble in appveyor?

**Comment by justinjk007** [comment]
Yes
