### ISSUE TITLE
[New Port Request] mockcpp

### ISSUE THREAD

**Issue by endingly** [microsoft/vcpkg#23451]
Library name: mockcpp

Library description: mock++ is a jmock-like generic easy-of-use C++ Mock Framework, creating a mock object by mock++ is virtually as easy as using jMock.

Source repository URL: https://code.google.com/archive/p/mockcpp/

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
