### ISSUE TITLE
qtwebengine build failure

### ISSUE THREAD

**Issue by AndrewMoa2005** [microsoft/vcpkg#23457]
**Host Environment**
- OS: Windows 11 21H2
- Compiler: Visual Studio 2019 16.11.10

**To Reproduce**
`./vcpkg install qt:x64-windows`

**Failure logs** 
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:158 (message):
    Command failed: D:/dev/vcpkg/downloads/tools/cmake-3.22.2-windows/cmake-3.22.2-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j17
    Working Directory: D:/dev/vcpkg/buildtrees/qtwebengine/x64-windows-dbg
    See logs for more information:
      D:\dev\vcpkg\buildtrees\qtwebengine\install-x64-windows-dbg-out.log
      D:\dev\vcpkg\buildtrees\qtwebengine\install-x64-windows-dbg-err.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:111 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
  ports/qtwebengine/portfile.cmake:109 (vcpkg_cmake_install)
  scripts/ports.cmake:145 (include)

Error: Building package qtwebengine:x64-windows failed with: BUILD_FAILED
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/8216059/install-x64-windows-dbg-out.log)
[install-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/8216072/install-x64-windows-dbg-err.log)

**Comment by TaylorShi** [comment]
Maybe you can short the path, Change `D:\dev\vcpkg\` => `D:\v\` , Try Again.

**Comment by AndrewMoa2005** [comment]
> Maybe you can short the path, Change `D:\dev\vcpkg\` => `D:\v\` , Try Again.

I tried it with a short path, and it compiled successfully.

**Comment by Cheney-W** [comment]
Thanks for your reply!
