### ISSUE TITLE
Is there an easy way to move vcpkg to a new "identical" machine?

### ISSUE THREAD

**Issue by swilson314** [microsoft/vcpkg#23464]
I've got two "identical" (same OS, Visual Studio, etc.) machines. One has vcpkg with a number of installed packages ('older' versions), and I'd like an identical copy on the new machine that is integrated with Visual Studio. There seem to be a number of relatively complicated methods of accomplishing this: export/import, manifest versioning and binary caching. But what I'd really like to do is run a command on the new machine like "vcpkg installfrompath path" or copy the vcpkg folder to the new machine and run "vcpkg restore". I really feel like this must exist and I'm just not seeing it.

**Comment by autoantwort** [comment]
Simply copy the vcpkg folder and run `vcpkg integrate install`

**Comment by swilson314** [comment]
Fantastic, thanks!
