### ISSUE TITLE
Strange error text with custom project configuration

### ISSUE THREAD

**Issue by lazyhamster** [microsoft/vcpkg#2346]
I'm trying to build project with custom configuration name.
As suggested in FAQ I've added property to .vcxproj file (to the bottom)
> \<PropertyGroup Label="vcpkg">
>    \<VcpkgConfiguration>Release\</VcpkgConfiguration>
>  \</PropertyGroup>

But it didn't work and I've got quite strange error:

> Vcpkg is unable to link because we cannot decide between Release and Debug libraries. Please define the property VcpkgConfiguration to be 'Release' or 'Debug' (currently 'Release').

How can I fix this issue and make vcpkg accept Release configuration?
And error message should probably be improved. It is not very helpful in this scenario.

**Comment by ras0219-msft** [comment]
Thanks for posting this issue!

Unfortunately, due to the sequential nature of MSBuild you'll need to add those settings much higher in your vcxproj before our integration is loaded -- I recommend adding it to the "Globals" `PropertyGroup`.

**Comment by lazyhamster** [comment]
Yes, it works now after moving variable to "Globals" PropertyGroup. Thank you for the info.
This is not a bug then. But faq probably could use some update to make it more clear where to put the data in vcxproj file.
