### ISSUE TITLE
[boost-context] Build error

### ISSUE THREAD

**Issue by glingi** [microsoft/vcpkg#23473]
**Host Environment**
- OS: Microsoft Windows [Version 10.0.19044.1526]
- Compiler: revision

**To Reproduce**
`./vcpkg install boost-context:x64-windows`

**Failure logs** 

1. Log in command prompt

Computing installation plan...
The following packages will be built and installed:
    boost-context[core]:x64-windows -> 1.78.0
Detecting compiler hash for triplet x64-windows...
Restored 0 packages from C:\Users\CIWS4\AppData\Local\vcpkg\archives in 436.1 us. Use --debug to see more details.
Starting package 1/1: boost-context:x64-windows
Building package boost-context[core]:x64-windows...
-- Using cached boostorg-context-boost-1.78.0.tar.gz.
-- Cleaning sources at C:/vcpkg/buildtrees/boost-context/src/ost-1.78.0-71dc2519be.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg/downloads/boostorg-context-boost-1.78.0.tar.gz
-- Using source at C:/vcpkg/buildtrees/boost-context/src/ost-1.78.0-71dc2519be.clean
-- Including C:/vcpkg/buildtrees/boost-context/vcpkg-b2-options.cmake
-- Found external ninja('1.10.2').
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:158 (message):
    Command failed: C:/vcpkg/downloads/tools/cmake-3.22.2-windows/cmake-3.22.2-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j9
    Working Directory: C:/vcpkg/buildtrees/boost-context/x64-windows-dbg
    See logs for more information:
      C:\vcpkg\buildtrees\boost-context\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:111 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
  installed/x64-windows/share/boost-build/boost-modular-build.cmake:124 (vcpkg_cmake_install)
  ports/boost-context/portfile.cmake:24 (boost_modular_build)
  scripts/ports.cmake:145 (include)

Error: Building package boost-context:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-context
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[boost-context]+Build+error
including:
  package: boost-context[core]:x64-windows -> 1.78.0
    vcpkg-tool version: 2022-03-09-1affd32f93b299d5a907816c328ca3ededb73a7e
    vcpkg-scripts version: 5a8a1dfff 2022-03-09 (5 hours ago)

Additionally, attach any relevant sections from the log files above.

2. Log in "install-x64-windows-dbg-out.log"

Microsoft (R) Macro Assembler (x64) Version 14.29.30038.1
Copyright (C) Microsoft Corporation.  All rights reserved.

 Assembling: ..\src\asm\ontop_x86_64_ms_pe_masm.asm
..\src\asm\ontop_x86_64_ms_pe_masm.asm(1) : error A2039:line too long
..\src\asm\ontop_x86_64_ms_pe_masm.asm(1) : fatal error A1009:line too long
compile-c-c++ C:\vcpkg\buildtrees\boost-context\x64-windows-dbg\boost\build\390fd8092bb4d388fcb8550939707c7a\dummy.obj

    call "C:\vcpkg\buildtrees\boost-context\x64-windows-dbg\boost\standalone\msvc\19858a0c092d6daed3b7579665d68f18\msvc-setup.bat" amd64 >nul
 cl "..\src\dummy.cpp" -c -Fo"C:\vcpkg\buildtrees\boost-context\x64-windows-dbg\boost\build\390fd8092bb4d388fcb8550939707c7a\dummy.obj"     -TP /wd4675 /EHs /GR /Zc:throwingNew /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /Z7 /Od /Ob0 /W3 /MDd /Zc:forScope /Zc:wchar_t /Zc:inline /favor:blend -DBOOST_ALL_NO_LIB=1 -DBOOST_CONTEXT_DYN_LINK=1 -DBOOST_CONTEXT_EXPORT=EXPORT -DBOOST_CONTEXT_SOURCE -D_WIN32_WINNT=0x0601 "-I..\include" "-IC:\vcpkg\installed\x64-windows\include" 

dummy.cpp
compile-c-c++ C:\vcpkg\buildtrees\boost-context\x64-windows-dbg\boost\build\390fd8092bb4d388fcb8550939707c7a\windows\stack_traits.obj

    call "C:\vcpkg\buildtrees\boost-context\x64-windows-dbg\boost\standalone\msvc\19858a0c092d6daed3b7579665d68f18\msvc-setup.bat" amd64 >nul
 cl "..\src\windows\stack_traits.cpp" -c -Fo"C:\vcpkg\buildtrees\boost-context\x64-windows-dbg\boost\build\390fd8092bb4d388fcb8550939707c7a\windows\stack_traits.obj"     -TP /wd4675 /EHs /GR /Zc:throwingNew /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /Z7 /Od /Ob0 /W3 /MDd /Zc:forScope /Zc:wchar_t /Zc:inline /favor:blend -DBOOST_ALL_NO_LIB=1 -DBOOST_CONTEXT_DYN_LINK=1 -DBOOST_CONTEXT_EXPORT=EXPORT -DBOOST_CONTEXT_SOURCE -D_WIN32_WINNT=0x0601 "-I..\include" "-IC:\vcpkg\installed\x64-windows\include" 

stack_traits.cpp
...skipped <pC:\vcpkg\buildtrees\boost-context\x64-windows-dbg\boost\build\390fd8092bb4d388fcb8550939707c7a>boost_context-vc142-mt-gd-x64-1_78.dll for lack of <pC:\vcpkg\buildtrees\boost-context\x64-windows-dbg\boost\build\390fd8092bb4d388fcb8550939707c7a>asm\make_x86_64_ms_pe_masm.obj...
...skipped <pC:\vcpkg\buildtrees\boost-context\x64-windows-dbg\stage\lib>boost_context-vc142-mt-gd-x64-1_78.dll for lack of <pC:\vcpkg\buildtrees\boost-context\x64-windows-dbg\boost\build\390fd8092bb4d388fcb8550939707c7a>boost_context-vc142-mt-gd-x64-1_78.dll...
...failed updating 3 targets...
ninja: build stopped: subcommand failed.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by Adela0814** [comment]
Your source code seems to be missing some `obj` and `dll`:
```
...skipped pC:\vcpkg\buildtrees\boost-context\x64-windows-dbg\boost\build\390fd8092bb4d388fcb8550939707c7aboost_context-vc142-mt-gd-x64-1_78.dll for lack of pC:\vcpkg\buildtrees\boost-context\x64-windows-dbg\boost\build\390fd8092bb4d388fcb8550939707c7aasm\make_x86_64_ms_pe_masm.obj...
...skipped pC:\vcpkg\buildtrees\boost-context\x64-windows-dbg\stage\libboost_context-vc142-mt-gd-x64-1_78.dll for lack of pC:\vcpkg\buildtrees\boost-context\x64-windows-dbg\boost\build\390fd8092bb4d388fcb8550939707c7aboost_context-vc142-mt-gd-x64-1_78.dll...
...failed updating 3 targets...
ninja: build stopped: subcommand failed
```
Please empty the directory `C:\vcpkg\buildtrees\boost-context` and try again. If the issue is not solved, please upload the full failure log `install-x64-windows-dbg-out.log`.

**Comment by Adela0814** [comment]
ping for response

**Comment by Adela0814** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
