### ISSUE TITLE
[mbedtls] update to 2.28.0

### ISSUE THREAD

**Issue by hgbutte** [microsoft/vcpkg#23485]
Library name: mbedtls

New version number: 2.28.0

**Comment by Adela0814** [comment]
@hgbutte  I noticed that the latest version is [v3.1.0](https://github.com/ARMmbed/mbedtls/releases/tag/v3.1.0), so I will update mbedtls to v3.1.0.

**Comment by hgbutte** [comment]
There has been a [PR for version 3.1.0](https://github.com/microsoft/vcpkg/pull/20860). Please have a look at this.

Primarily i need to use libssl which depends on mbedtls.
I am not sure 3.1.0 is compatible with libssl 0.9.6.
