### ISSUE TITLE
Fails to install azure-iot-sdk-c

### ISSUE THREAD

**Issue by csampaio26** [microsoft/vcpkg#23489]
**Describe the bug**
Command: `vcpkg.exe install azure-iot-sdk-c:x64-windows` fails

**Environment**
- OS: Windows 11
- Compiler: Visual Studio 2022
- vcpkg version : 2022-03-09-1affd32f93b299d5a907816c328ca3ededb73a7e

**To Reproduce**
1. git clone https://github.com/Microsoft/vcpkg
2. cd vcpkg
3. bootstrap-vcpkg.bat
4. vcpkg.exe install azure-iot-sdk-c:x64-windows

**Expected behavior**

**Failure logs** 
Computing installation plan...
The following packages will be built and installed:
  * azure-c-shared-utility[core]:x64-windows -> 2022-01-21#2
    azure-iot-sdk-c[core]:x64-windows -> 2022-01-21#2
  * azure-macro-utils-c[core]:x64-windows -> 2022-01-21
  * azure-uamqp-c[core]:x64-windows -> 2022-01-21#1
  * azure-uhttp-c[core]:x64-windows -> 2022-01-21#1
  * azure-umqtt-c[core]:x64-windows -> 2022-01-21#1
  * parson[core]:x64-windows -> 2020-09-14#1
  * umock-c[core]:x64-windows -> 2022-01-21
  * vcpkg-cmake[core]:x64-windows -> 2022-01-19
  * vcpkg-cmake-config[core]:x64-windows -> 2022-02-06
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
A suitable version of powershell-core was not found (required v7.2.1). Downloading portable powershell-core v7.2.1...
Downloading powershell-core...
  https://github.com/PowerShell/PowerShell/releases/download/v7.2.1/PowerShell-7.2.1-win-x86.zip -> C:\Users\CarlaSampaio\Desktop\vcpkg\downloads\PowerShell-7.2.1-win-x86.zip
Extracting powershell-core...
Restored 0 packages from C:\Users\CarlaSampaio\AppData\Local\vcpkg\archives in 651.1 us. Use --debug to see more details.
Starting package 1/10: azure-macro-utils-c:x64-windows
Building package azure-macro-utils-c[core]:x64-windows...
-- Note: azure-macro-utils-c only supports static library linkage. Building static library.
-- Downloading https://github.com/Azure/azure-macro-utils-c/archive/5926caf4e42e98e730e6d03395788205649a3ada.tar.gz -> Azure-azure-macro-utils-c-5926caf4e42e98e730e6d03395788205649a3ada-1.tar.gz...
-- Extracting source C:/Users/CarlaSampaio/Desktop/vcpkg/downloads/Azure-azure-macro-utils-c-5926caf4e42e98e730e6d03395788205649a3ada-1.tar.gz
-- Using source at C:/Users/CarlaSampaio/Desktop/vcpkg/buildtrees/azure-macro-utils-c/src/05649a3ada-59e162c9fa.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:128 (message):
    Command failed: ninja -v
    Working Directory: C:/Users/CarlaSampaio/Desktop/vcpkg/buildtrees/azure-macro-utils-c/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\Users\CarlaSampaio\Desktop\vcpkg\buildtrees\azure-macro-utils-c\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:345 (vcpkg_execute_required_process)
  ports/azure-macro-utils-c/portfile.cmake:23 (vcpkg_configure_cmake)
  scripts/ports.cmake:145 (include)

**Additional context**

**Comment by FrankXie05** [comment]
Thanks for posting this issue,  It looks like a problem with the port `azure-macro-utils-c` and could you please try to run
` .\vcpkg.exe install azure-iot-sdk-c:x64-windows-static`.  and provide the log 

`C:\Users\CarlaSampaio\Desktop\vcpkg\buildtrees\azure-macro-utils-c\config-x64-windows-out.log`
```
Starting package 1/10: azure-macro-utils-c:x64-windows
Building package azure-macro-utils-c[core]:x64-windows...
-- Note: azure-macro-utils-c only supports static library linkage. Building static library.
```

**Comment by FrankXie05** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
