### ISSUE TITLE
[vcpkg-tool] Supports expressions do not remove host port dependencies from the graph in CI

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#23490]
In #23431 i noticed the following:
- `qtwebengine:x64-windows` is build in the `x86-windows` triplet
- `qtwebengine `has a host dependency on itself
- but supports of `qtwebengine` disallows `x86`

so the expected behavior would be to not build `qtwebengine:x64-windows` for the  `x86-windows` triplet
i noticed the same for  `x64-windows-static(-md)?` triplets. 
Considering CI takes roughly 2h to build `qtwebengine` this is quite a CI time waste.

**Comment by JackBoosY** [comment]
In qtwebengine's manifest file:
```json
  "supports": "!static & !((arm | x86) & windows)",
...
    {
      "$comment": "Requires GN host tool build by the port itself! (special version check)",
      "name": "qtwebengine",
      "host": true,
      "default-features": false
    },
```
So I assume this is a port issue?

**Comment by Neumann-A** [comment]
> So I assume this is a port issue?

Why do you assume that? The tool should deduce that a host dependency is not needed and thus not include it into the graph.

**Comment by JackBoosY** [comment]
> Why do you assume that? The tool should deduce that a host dependency is not needed and thus not include it into the graph.

Our CI systems are x64, so the host triple should be `x64-windows` by default.
According to dependencies, `qtwebengine:x86-windows` needs to build `qtwebengine:x64-windows` first. So the current behavor is make sence.
Am I missing something?

**Comment by Neumann-A** [comment]
> Am I missing something?

Yeah   "supports": "!static & !((arm | x86) & windows)",. x86 cannot be build, so no need to build it for x64. It is an unneeded host dependency since it cannot be build on x86

**Comment by JackBoosY** [comment]
> > Am I missing something?
> 
> Yeah ` "supports": "!static & !((arm | x86) & windows)"`,. x86 cannot be build, so no need to build it for x64 host. It is an unneeded host dependency since it cannot be build on x86

`!static & !((arm | x86) & windows)` == `(!static & (!arm & windows)) | (!static & (!x86 & windows))` == `(dynamic & !arm & windows) | (dynamic & x64 & windows)` right?

**Comment by Neumann-A** [comment]
Don't ask me supports logic always kills me ;)
For `x86-windows`:
`!static & !((arm | x86) & windows) = !static & !((arm | 1) & 1) = !static & !(1) = !static & 0 = 0` -> 0 means unsupported

>  right?

no because you are missing other platforms like x64-linux-dynamic. That is why supports generally blacklists instead of whitelists.

**Comment by JackBoosY** [comment]
> That is why supports generally blacklists instead of whitelists.


Yes that's me recommend. Let's discuss it with pure logic that doesn't distinguish between official and community triples.

If all the `x86-windows-dynamic` triplets are not supports, let's set `!arm | x86` as `A`, then the expected expressions should be:
`!(A & windows & dynamic)` == `!(A & windows & !static)` == `static & !(A & windows)`.
Then set back `A`  to `!arm | x86`, the final expression should be:
`static & ((!arm | x86) & windows)`
Is that correct?

**Comment by Neumann-A** [comment]
`dynamic` is supported. `static `is unsupported. But this is not about the `supports` expression. I mean, CI correctly identifies it to not build on `x86`. The problem is that it still builds for the host although that is completely unneeded.

**Comment by JackBoosY** [comment]
I still think that's just an expression issue.

I'm totally messed up.
cc @BillyONeal @ras0219-msft

**Comment by BillyONeal** [comment]
To rephrase the bug report: vcpkg thinks it wants to build qtwebengine:x86-windows, which wants qtwebengine:x64-windows. We evaluate 'supports' which removes qtwebengine:x86-windows, but we don't go and remove qtwebengine:x64-windows as well. (Or something else depends on `{qtwebengine:x64-windows, host=true}` we didn't notice?)
