### ISSUE TITLE
bootstrap-vcpkg.bat error

### ISSUE THREAD

**Issue by top1st** [Microsoft/vcpkg#2349]
WARNING: The binding of default value 'System.Net.NetworkCredential' to parameter 'ProxyCredential' failed: Cannot
process argument transformation on parameter 'ProxyCredential'. userName

![image](https://user-images.githubusercontent.com/23559697/33940595-84a5c204-e04a-11e7-8cbc-9b4bf5302aa3.png)

**Comment by alexkaratarakis** [comment]
What is your Windows version and powershell version?

**Comment by Moonwolf287** [comment]
I'm having the same issue.
PS Version:  5.1 Build 16299 Rev 64
Win 10 Pro 64bit Version 1709 Build 16299.64

**Comment by yuchenglong** [comment]
same issue +1

**Comment by JackBoosY** [comment]
Hi everyone , thanks for reporting this issue!
Please open a new issue if this is still a problem for you.
Thx.
