### ISSUE TITLE
WinHttpSendRequest() failed: 12007

### ISSUE THREAD

**Issue by ashari4** [microsoft/vcpkg#23512]
I see intermittent problems downloading 7zip.

```
PS E:\Code\vcpkg> .\vcpkg.exe install --recurse cppzmq
....
 A suitable version of 7zip was not found (required v19.0.0).  Downloading
  portable 7zip v19.0.0...

  Downloading 7zip...

    https://www.7-zip.org/a/7z1900-x64.msi -> C:\__w\_temp\vcpkg-src\downloads\7z1900-x64.msi

  Error: Failed to download from mirror set:

  https://www.7-zip.org/a/7z1900-x64.msi: WinHttpSendRequest() failed: 12007

  https://www.7-zip.org/a/7z1900-x64.msi: WinHttpSendRequest() failed: 12007

  https://www.7-zip.org/a/7z1900-x64.msi: WinHttpSendRequest() failed: 12007

  https://www.7-zip.org/a/7z1900-x64.msi: WinHttpSendRequest() failed: 12007

```

Perhaps, some improvement can be made to the download logic similar to this PR: https://github.com/microsoft/vcpkg-tool/pull/116.

12007 corresponds to `ERROR_WINHTTP_NAME_NOT_RESOLVED`: https://docs.microsoft.com/en-us/windows/win32/winhttp/error-messages

**Comment by Cheney-W** [comment]
What's the version of your vcpkg? Could you please clone the latest vcpkg and reinstall the port? Thank you!

**Comment by ashari4** [comment]
Thanks, we are using `b25cb779e5783531cc66562e224079b376055939`. We can update the version, but the question is around intermittent errors. Our CI pipelines use VCPKG to install `zmq` and occasionally hit the above `12007` error. Can the retry loop used by VCPKG be improved? I see that the VCPKG tool tries to download from `https://www.7-zip.org/a/7z1900-x64.msi` 4 times; perhaps, the VCPKG tool can try to download from different mirrors?

**Comment by Cheney-W** [comment]
This issue is more of a 7zip site issue, a random network issue.

**Comment by Cheney-W** [comment]
@BillyONeal What do you think about the two suggestions above?

**Comment by BillyONeal** [comment]
> Thanks. Feel free to close if you don't think the download logic can be improved. Some possible improvements
> 
> 1. use a different set of mirrors

If you have better ideas :)

> 2. wait before each retry attempt instead of immediately retrying.

We do do this: https://github.com/microsoft/vcpkg-tool/blob/91494e3e24f53270ba38749a325c36c6373699ed/src/vcpkg/base/downloads.cpp#L318

**Comment by Louis-Simon22** [comment]
For those like me who keep running into this problem: 

You can download the file manually using another reliable method (browser, curl, etc.) then put it under vcpkg/downloads/7z1900-x64.msi yourself.

**Comment by Cheney-W** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
