### ISSUE TITLE
[colmap] Build error

### ISSUE THREAD

**Issue by scotshinderman** [microsoft/vcpkg#23528]
**Host Environment**
Windows
D:\repos\vcpkg>git log
commit af2287382b1991dbdcb7e5112d236f3323b9dd7a (HEAD -> master, tag: 2022.03.10, origin/master, origin/HEAD)

**To Reproduce**
.\vcpkg install colmap[cuda]:x64-windows --clean-after-build

**Failure logs** 
[install-x64-windows-rel-out.zip](https://github.com/microsoft/vcpkg/files/8238942/install-x64-windows-rel-out.zip)

**Comment by scotshinderman** [comment]
D:\repos\vcpkg\installed\x64-windows\include\Eigen\src\Core\PlainObjectBase.h(591) : fatal error C1001: Internal compiler error.
(compiler file 'D:\a\_work\1\s\src\vctools\Compiler\Utc\src\p2\main.c', line 220)
 To work around this problem, try simplifying or changing the program near the locations listed above.
If possible please provide a repro here: https://developercommunity.visualstudio.com 
Please choose the Technical Support command on the Visual C++ 
 Help menu, or open the Technical Support help file for more information
  cl!RaiseException()+0x6c
  cl!RaiseException()+0x6c
  cl!InvokeCompilerPassW()+0x81bdf
  cl!InvokeCompilerPassW()+0x120297

**Comment by FrankXie05** [comment]
@scotshinderman Thanks for posting this issue, I have not reproduced this problem locally，according to you provide message, it may be a compiler bug.
see: https://github.com/microsoft/vcpkg/issues/19561#issuecomment-898879852

**Comment by donproc** [comment]
> D:\repos\vcpkg\installed\x64-windows\include\Eigen\src\Core\PlainObjectBase.h(591) : fatal error C1001: Internal compiler error. (compiler file 'D:\a_work\1\s\src\vctools\Compiler\Utc\src\p2\main.c', line 220) To work around this problem, try simplifying or changing the program near the locations listed above. If possible please provide a repro here: https://developercommunity.visualstudio.com Please choose the Technical Support command on the Visual C++ Help menu, or open the Technical Support help file for more information cl!RaiseException()+0x6c cl!RaiseException()+0x6c cl!InvokeCompilerPassW()+0x81bdf cl!InvokeCompilerPassW()+0x120297

Hi, @scotshinderman , I met the same problem, have you solved the issue? Thanks!

**Comment by scotshinderman** [comment]
@donproc`  just tried and no luck, now it's bumping into: https://github.com/microsoft/vcpkg/issues/24155#issue-1205324982
probably just revert to building from scratch and probably from WSL instead of dealing w/ windows mess

**Comment by sfhacker** [comment]
https://english-for-chinese.blogspot.com/2008/06/and-meet-problem.html

**Comment by Cheney-W** [comment]
This issue is a Visual Studio bug and we have reported to the compiler team.
We will update the status of this issue as soon as the compiler team has any updates on that bug.

**Comment by Cheney-W** [comment]
This issue is currently tracked by tickets on the Develop Community: https://developercommunity.visualstudio.com/t/Internal-compiler-error-when-install-col/10035653
