### ISSUE TITLE
vcpkg_find_acquire_program does not consider PATH

### ISSUE THREAD

**Issue by pravic** [microsoft/vcpkg#2353]
I was surprised that openssl started to download a new Strawberry Perl instead of the existing in the `PATH` one. The same for NASM.

I am not sure about how to check version of existing executables. May be just to hardcode a minimum version inside the `vcpkg_find_acquire_program`, like it's already done with the supported programs. Or may be it is not so important.

**Comment by jozefizso** [comment]
I have perl installed using chocolatey. It is Strawberry Perl installed at `C:\Strawberry\perl\bin` and it is set in the `%PATH%` variable.
Vcpkg does not use it and insists on downloading it again. This takes very long time and it is unnecessary.

```shell
c:\dev\github\vcpkg>where perl
C:\Strawberry\perl\bin\perl.exe

c:\dev\github\vcpkg>perl --version

This is perl 5, version 28, subversion 1 (v5.28.1) built for MSWin32-x64-multi-thread

Copyright 1987-2018, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.
```

```
vcpkg.exe install openssl:x86-windows-static
The following packages will be built and installed:
    openssl[core]:x86-windows-static
  * openssl-windows[core]:x86-windows-static
Additional packages (*) will be modified to complete this operation.
Starting package 1/2: openssl-windows:x86-windows-static
Building package openssl-windows[core]:x86-windows-static...
-- Downloading http://strawberryperl.com/download/5.24.1.1/strawberry-perl-5.24.1.1-32bit-portable.zip...
```

Vcpkg should use already installed tools on the system.

**Comment by levirs565** [comment]
I also experienced the same problem. I found that this problem occurred because writing mistake at `vcpkg_find_acquire_program.cmake` line 251.

```cmake
  if("${${VAR}}" MATCHES "-NOTFOUND")
```

After i change this line into

```cmake
  if("${VAR}" MATCHES "-NOTFOUND")
```

This problem is fixed.

**Comment by dg0yt** [comment]
Do you still see this issue?
IIUC, since https://github.com/microsoft/vcpkg/commit/0bbf4400e977b2db20f5acda1522ba5ecae1d789, there is an additional plain `find_program` which will look for programs in the `PATH`.
(However, I found that some scripts use the result from `vcpkg_find_acquire_program` to modify the `PATH` instead of using the precise tool path, leading to some strange side effects depending on program acquisition order.)

**Comment by pravic** [comment]
@dg0yt Can't check now since I don't have have Perl installed anymore. @jozefizso?
