### ISSUE TITLE
cmake can not find python3 (missing: Development Development.Module   Development.Embed) (found version "3.8.9")

### ISSUE THREAD

**Issue by MariaSabrinaMa** [microsoft/vcpkg#23537]
Please create a discussion in https://github.com/microsoft/vcpkg/discussions/new instead.
Hi, I want to install openeb which so I got the following code:
PS C:\Users\masiy\openeb\build> cmake .. -A x64 -DCMAKE_TOOLCHAIN_FILE=C:\Users\masiy\openeb\cmake\toolchains\vcpkg.cmake -DVCPKG_DIRECTORY=C:\src\vcpkg -DBUILD_TESTING=OFF

But I terminal reports an issue:
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19044.
-- Building METAVISION_SDK_MODULES_OPEN modules : base;core;driver;ui
-- Building METAVISION_SDK_MODULES_PROFESSIONAL modules : analytics;calibration;cv;ml;3dview;cv3d
CMake Error at C:/Program Files/CMake/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Python3 (missing: Development Development.Module
  Development.Embed) (found version "3.8.9")
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindPython/Support.cmake:2993 (find_package_handle_standard_args)
  cmake/Modules/FindPython3.cmake:391 (include)
  C:/Users/masiy/vcpkg/installed/x64-windows/share/python3/vcpkg-cmake-wrapper.cmake:67 (_find_package)
  C:/Users/masiy/vcpkg/scripts/buildsystems/vcpkg.cmake:754 (include)
  cmake/custom_functions/python3.cmake:63 (find_package)
  CMakeLists.txt:211 (include)

-- Configuring incomplete, errors occurred!
See also "C:/Users/masiy/openeb/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/masiy/openeb/build/CMakeFiles/CMakeError.log".

Could someone tells me how to solve this problem? Thanks very much.

**Comment by FrankXie05** [comment]
@MariaSabrinaMa Thanks for posting this issue, 
Do you have multiple versions of pythone3 and make sure that  you using the function target correctly in CMakeLists.txt.
```
find_package(Python3 COMPONENTS Development REQUIRED)                                                                   
target_link_libraries(main PRIVATE Python3::Python) 
```

**Comment by Osyotr** [comment]
`-DCMAKE_TOOLCHAIN_FILE=C:\Users\masiy\openeb\cmake\toolchains\vcpkg.cmake`
This looks wrong

**Comment by FrankXie05** [comment]
@MariaSabrinaMa Is still work for this issue?

**Comment by FrankXie05** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.

**Comment by MariaSabrinaMa** [comment]
Hi, the issue is still not solved...

**Comment by FrankXie05** [comment]
@MariaSabrinaMa Did you run the command `.\vcpkg.exe integrate install` ?

**Comment by MariaSabrinaMa** [comment]
Yes I did and it did not work. I am pretty sure I have multiple versions of python on my PC. I found the official document from prophesse (the software I want to install) stating that:
In that case, we can see that cmake found some version of the Python interpreter, but it then fails because it does not find other required components from this specific version. The solution is to specify to cmake which version of Python to use with the option -DPython3_EXECUTABLE=<path_to_python_to_use>.
So I added that but I got a new issue:
PS C:\Users\masiy\openeb\build> cmake .. -DBUILD_TESTING=OFF -DPython3_EXECUTABLE=/usr/bin/python3.8
CMake Error: The source directory "C:/Users/masiy/openeb/build/.8" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
PS C:\Users\masiy\openeb\build> cmake .. -DBUILD_TESTING=OFF -DPython3_EXECUTABLE=C:\Users\masiy\AppData\Local\Programs\Python\Python38
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19044.
-- Building METAVISION_SDK_MODULES_OPEN modules : base;core;driver;ui
-- Building METAVISION_SDK_MODULES_PROFESSIONAL modules : analytics;calibration;cv;ml;3dview;cv3d
CMake Error at C:/Program Files/CMake/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Python3 (missing: Interpreter Development Development.Module
  Development.Embed) (found version "3.8")

      Reason given by package:
          Interpreter: Cannot run the interpreter "C:/Users/masiy/AppData/Local/Programs/Python/Python38"

Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindPython/Support.cmake:2993 (find_package_handle_standard_args)
  cmake/Modules/FindPython3.cmake:391 (include)
  C:/Users/masiy/vcpkg/installed/x64-windows/share/python3/vcpkg-cmake-wrapper.cmake:67 (_find_package)
  C:/Users/masiy/vcpkg/scripts/buildsystems/vcpkg.cmake:754 (include)
  cmake/custom_functions/python3.cmake:63 (find_package)
  CMakeLists.txt:211 (include)

**Comment by FrankXie05** [comment]
Have you added python3 to your system environment variables?

**Comment by MariaSabrinaMa** [comment]
Yes it was added to my system environment variables

**Comment by FrankXie05** [comment]
@MariaSabrinaMa Since I have no way to reproduce your problem, I can provied the following solutions:
1. Keep only one version of pyhton in your local  
2. Can you manually run pyhton.exe("C:/Users/masiy/AppData/Local/Programs/Python/Python38/python.exe")
3. Add cmake -DPython_EXECUTABLE=<full_path_to/python_interpreter>...

Do not forget to cleanup your build directory before running this command. :)

**Comment by Osyotr** [comment]
You don't need to pass any additional arguments to cmake find python. If `Development` is in the list of components, then `Interpreter` will be the python3 executable provided by vcpkg.
But openeb does something very fishy here:
https://github.com/prophesee-ai/openeb/blob/92aa7c1fc0df52ab53a0b62517255737689f1134/cmake/custom_functions/python3.cmake#L43
So I would say that this is not a bug in vcpkg but in openeb.

**Comment by FrankXie05** [comment]
@Osyotr Thank you for your reply, I would like to say that currently we are not getting the correct reply and information from the user. 
@MariaSabrinaMa 
1. Your toolchanin is not provided by vcpkg   
   ` -DCMAKE_TOOLCHAIN_FILE=C:\Users\masiy\openeb\cmake\toolchains\vcpkg.cmake`
2. According to the log, there is no runnable python interpreter locally, and the user has not replied whether can run python3 normally  `Interpreter: Cannot run the interpreter "C:/Users/masiy/AppData/Local/Programs/Python/Python38"`
3. There may be file permission problems, you can try other disks. :)

**Comment by FrankXie05** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!

**Comment by lanzhan777** [comment]
Uninstalled version Python3.11 midway and installed version Python3.10. Using find_package(Python3 3.10 COMPONENTS Interpreter Development NumPy REQUIRED). A similar issue occurred. Then clean up the build directory and use find_package(), the issue disappeared.
