### ISSUE TITLE
atk does not build

### ISSUE THREAD

**Issue by barcharcraz** [Microsoft/vcpkg#2354]
[install-x64-windows-rel-out.log](https://github.com/Microsoft/vcpkg/files/1549795/install-x64-windows-rel-out.log)
[install-x64-windows-static-rel-out.log](https://github.com/Microsoft/vcpkg/files/1549796/install-x64-windows-static-rel-out.log)
[config-x64-windows-static-dbg-out.log](https://github.com/Microsoft/vcpkg/files/1549798/config-x64-windows-static-dbg-out.log)
[config-x64-windows-static-rel-out.log](https://github.com/Microsoft/vcpkg/files/1549799/config-x64-windows-static-rel-out.log)

**Comment by ras0219-msft** [comment]
I'm not able to reproduce this issue. Could you confirm you're using the latest vcpkg and all packages are up to date?

```
>vcpkg version
>vcpkg update
```

**Comment by DengHaijian** [comment]
Building package atkmm[core]:x86-windows...
-- Using cached D:/work/vcpkg/downloads/atkmm-2.24.2.tar.xz
-- Applying patch D:/work/vcpkg/ports/atkmm/fix_properties.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch D:/work/vcpkg/ports/atkmm/fix_charset.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Building D:/work/vcpkg/buildtrees/atkmm/src/atkmm-2.24.2/MSVC_Net2013/atkmm.sln for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: msbuild;D:/work/vcpkg/buildtrees/atkmm/src/atkmm-2.24.2/MSVC_Net2013/atkmm.sln;/p:Configuration=Release;/t:atkmm;/p:Platform=Win32;/p:PlatformToolset=v141;/p:VCPkgLocalAppDataDisabled=true;/p:UseIntelMKL=No;/p:WindowsTargetPlatformVersion=10.0.17134.0;/m;/p:ForceImportBeforeCppTargets=D:/work/vcpkg/scripts/buildsystems/msbuild/vcpkg.targets;/p:VcpkgTriplet=x86-windows
    Working Directory: D:/work/vcpkg/buildtrees/atkmm/x86-windows-rel
    See logs for more information:
      D:\work\vcpkg\buildtrees\atkmm\build-x86-windows-rel-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_msbuild.cmake:119 (vcpkg_execute_required_process)
  ports/atkmm/portfile.cmake:27 (vcpkg_build_msbuild)
  scripts/ports.cmake:71 (include)


Error: Building package atkmm:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: atkmm:x86-windows
  Vcpkg version: 0.0.113-nohash
[Uploading patch-x86-windows-0-err.log…]()
[Uploading patch-x86-windows-1-err.log…]()
[build-x86-windows-rel-out.log](https://github.com/Microsoft/vcpkg/files/2343893/build-x86-windows-rel-out.log)

**Comment by Cheney-W** [comment]
@barcharcraz & @DengHaijian  
I can install this port successfully with the latest VCPKG and VS2017 15.9.7.
