### ISSUE TITLE
[open62541] Add full namespace zero option

### ISSUE THREAD

**Issue by kuprinik** [microsoft/vcpkg#23546]
****

**Is your feature request related to a problem? Please describe.**
Some models require types from full namespace zero (ns0). It would be nice to choose what form of namespace to build with. 

**Proposed solution**
Add -DUA_NAMESPACE_ZERO:STRING=FULL to options.

**Describe alternatives you've considered**

**Additional context**
Wasn't able to fix by adding "-DUA_NAMESPACE_ZERO:STRING=FULL" to OPTIONS of vcpkg_cmake_configure because build failed due to "CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:128 (message): Command failed: ninja -v"

**Comment by FrankXie05** [comment]
@kuprinik Thanks for posting this issue, I see that the upstream supports the `Full `option, can you explain in detail why you have to manually set it? :)
```
set(UA_NAMESPACE_ZERO "REDUCED" CACHE STRING "Completeness of the generated namespace zero (minimal/reduced/full)")
SET_PROPERTY(CACHE UA_NAMESPACE_ZERO PROPERTY STRINGS "MINIMAL" "REDUCED" "FULL")
```
https://github.com/open62541/open62541/blob/2b226746898ef8751b00de11e7387a917644f889/CMakeLists.txt#L261

**Comment by kuprinik** [comment]
@FrankXie05  Thanks for the reply.
The issue with using default upstream options is that some types are then missing in `types_generated.h`. For example, the problem for me was that `UA_TYPES_IDTYPE` was missing. Please, try to manually set `UA_NAMESPACE_ZERO` to `FULL` and compare  `types_generated.h` files.

**Comment by FrankXie05** [comment]
@kuprinik 
It might be an upstream bug, can you provide steps to reproduce it?
Of course, I can provide you with a file for setting `UA_NAMESPACE_ZERO `to `FULL`, can you please try it? :)
[file.zip](https://github.com/microsoft/vcpkg/files/8250921/file.zip)

**Comment by kuprinik** [comment]
@FrankXie05  Actually, it works correctly. The namespace is set to `REDUCED` by default using this function:
`set(UA_NAMESPACE_ZERO "REDUCED" CACHE STRING "Completeness of the generated namespace zero `(minimal/reduced/full)")`
This function just sets available options for dropdown menu in cmake-gui:
`SET_PROPERTY(CACHE UA_NAMESPACE_ZERO PROPERTY STRINGS "MINIMAL" "REDUCED" "FULL")`

Regarding your file, it doesn't work, because it is necessary to update `ua-nodeset` submodule.  Unfortunately, `vcpkg_from_github` seems to ignore submodules. However, there is a workaround described here: [vcpkg's git strategy appears to neglect submodules](https://github.com/microsoft/vcpkg/issues/6886#issuecomment-502617274). The working version of the `profile.cmake` is here: [open62541.zip](https://github.com/microsoft/vcpkg/files/8268091/open62541.zip)

**Comment by FrankXie05** [comment]
@[JackBoosY](https://github.com/JackBoosY) What do you think?

**Comment by JackBoosY** [comment]
> Unfortunately, vcpkg_from_github seems to ignore submodules.

That's by design.

According to our policy, we shouldn't add a feature that has conflicts with other features, so unfortunately, we won't add this.
But you can download [this file](https://github.com/microsoft/vcpkg/files/8282367/open62541.zip)
, unzip it and copy to _VCPKG_ROOT/ports/open62541_ then try to install this port again.

Thanks.
