### ISSUE TITLE
[qt5-webengine] Build error

### ISSUE THREAD

**Issue by Cosma-M** [microsoft/vcpkg#23576]
**Host Environment**
- OS: Windows 11 21H2
- Compiler:  Visual Studio 2022 - Compiler 19.31.31104

**To Reproduce**
`./vcpkg install qt5-webengine`

**Failure logs** 
Building package qt5-webengine[core]:x64-windows...
CMake Warning at scripts/cmake/vcpkg_buildpath_length_warning.cmake:18 (message):
  qt5-webengine's buildsystem uses very long paths and may fail on your
  system.

  We recommend moving vcpkg to a short path such as 'C:\src\vcpkg' or using
  the subst command.
Call Stack (most recent call first):
  ports/qt5-webengine/portfile.cmake:4 (vcpkg_buildpath_length_warning)
  scripts/ports.cmake:145 (include)

CMake Error at ports/qt5-webengine/portfile.cmake:5 (message):
  terminating due to source length.
Call Stack (most recent call first):
  scripts/ports.cmake:145 (include)

package: qt5-webengine[core]:x64-windows -> 5.15.3#1
vcpkg-tool version: 2022-03-09-1affd32f93b299d5a907816c328ca3ededb73a7e
vcpkg-scripts version: 6b34240d0 2022-03-12 (3 days ago)

**Additional context**
- vcpkg path: c:\05\vcpkg
- registry key LongPathsEnabled set to 1

**Comment by Adela0814** [comment]
@Cosma-M  please move vcpkg to a short path such as `C:\src\vcpkg` and try again.

**Comment by Cosma-M** [comment]
OK, I changed the path from c:\05\vcpkg\ to c:\v\ and now works.
Thank you.
