### ISSUE TITLE
[mesa] Build error

### ISSUE THREAD

**Issue by Fedr** [microsoft/vcpkg#23573]
**Host Environment**
- OS: Windows 10
- Compiler: Visual Studio 2019

**To Reproduce**
`./vcpkg install mesa`

**Failure logs** 
```
-- Package x64-windows-meshrus-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:128 (message):
    Command failed: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" install -v
    Working Directory: C:/temp/vcpkg/buildtrees/mesa/x64-windows-meshrus-dbg
    Error code: 1
    See logs for more information:
      C:\temp\vcpkg\buildtrees\mesa\package-x64-windows-meshrus-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_meson.cmake:53 (vcpkg_execute_required_process)
  ports/mesa/portfile.cmake:187 (vcpkg_install_meson)
  scripts/ports.cmake:145 (include)


Error: Building package mesa:x64-windows-meshrus failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+mesa
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[mesa]+Build+error
including:
  package: mesa[core,default-features,gles1,gles2,llvm,opengl]:x64-windows-meshrus -> 21.2.5#2
    vcpkg-tool version: 2022-03-09-1affd32f93b299d5a907816c328ca3ededb73a7e
    vcpkg-scripts version: c6a4ed75f 2022-03-14 (18 hours ago)
```

The error in `C:\temp\vcpkg\buildtrees\mesa\package-x64-windows-meshrus-dbg-out.log`:
```
LINK : fatal error LNK1181: cannot open input file 'csr'
```

**Additional context**
[package-x64-windows-meshrus-dbg-out.log](https://github.com/microsoft/vcpkg/files/8256200/package-x64-windows-meshrus-dbg-out.log)
[x64-windows-meshrus.cmake.txt](https://github.com/microsoft/vcpkg/files/8256202/x64-windows-meshrus.cmake.txt)

**Comment by Fedr** [comment]
I get the same error with the standard triplet:
```
vcpkg install mesa:x86-windows
```
[package-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/8260820/package-x86-windows-dbg-out.log)

**Comment by Neumann-A** [comment]
The provided logs won't help. The problem is that your `meson` seems to be not the one from `vcpkg-tool-meson` which fixes the issue by patching `meson` itself. Maybe you have a cached version of `meson` in `downloads/tools` which somehow gets used (did you delete your host installation manually?). 
The linker detection is fixed by: https://github.com/microsoft/vcpkg/blob/master/ports/vcpkg-tool-meson/fix_linker_detection.patch

**Comment by Fedr** [comment]
Yes, it looks like caching error. After complete reinstall of vcpkg, this error has gone.
