### ISSUE TITLE
vcpkg dependency extraction stopped working

### ISSUE THREAD

**Issue by lazyhamster** [Microsoft/vcpkg#2358]
After one of the recent commits vcpkg fails to extract downloaded dependency, e.g. CMake.
Download works properly but zip file is not extracted. I have the following error in console

```
A suitable version of cmake was not found (required v3.10.0). Downloading portable cmake v3.10.0...
Fetching %s version %s (No sufficient installed version was found)
Could not run:
    'D:/Temp/vcpkg/scripts/fetchDependency.ps1'
Error message was:
    You cannot call a method on a null-valued expression.
At D:\Temp\vcpkg\scripts\VcpkgPowershellUtils.ps1:180 char:59
+             $shell.Namespace($destinationPartial).copyhere <<<< ($item) | Out-Null
    + CategoryInfo          : InvalidOperation: (copyhere:String) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Could not detect or download cmake
At D:\Temp\vcpkg\scripts\fetchDependency.ps1:109 char:14
+         throw <<<<  ("Could not detect or download " + $Dependency)
    + CategoryInfo          : OperationStopped: (Could not detect or download cmake:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not detect or download cmake

```

"Fetching %s version %s" message could use some improvement too.
To repeat the problem just delete extracted CMake directory.

**Comment by CaptainCrowbar** [comment]
I have the same problem. Manually installing cmake fixed this error but then it just gives me a very similar series of messages while trying to install git. I haven't tried to manually work around that because I expect I'd just get the same thing again on whatever comes after git. Something seems to have broken in vcpkg very recently.

**Comment by alexkaratarakis** [comment]
Thanks for reporting!

**Comment by alexkaratarakis** [comment]
@lazyhamster 
dd1c2d9d6256d345659372ae4731bc81a91ad63b fixes the "Fetching %s version %s" message.

**Comment by CaptainCrowbar** [comment]
Thanks for the quick fix. Can confirm it works for me now.

**Comment by lazyhamster** [comment]
Works for me now too. Thanks for the quick fix.
