### ISSUE TITLE
"PR suggestions" fails without reason for some PR

### ISSUE THREAD

**Issue by dg0yt** [microsoft/vcpkg#23585]
**Describe the bug**
For some PRs, the "PR suggestions" action fails without reason.
In the context of https://github.com/microsoft/vcpkg/pull/23532, this seems to be triggered by the manifest (correctly) using `version-string` instead of `version`.

**Environment**
https://github.com/microsoft/vcpkg/actions/workflows/untrustedPR.yml?query=is%3Afailure

**Failure logs** 
~~~
Succeeded in formatting the manifest files.
[detached HEAD 2da5e81] tmp
Error: Process completed with exit code 1.
~~~
https://github.com/microsoft/vcpkg/actions/runs/1990223146

**Comment by autoantwort** [comment]
Maybe because of https://github.com/microsoft/vcpkg/pull/23520

**Comment by JackBoosY** [comment]
cc @BillyONeal

**Comment by dg0yt** [comment]
With both https://github.com/microsoft/vcpkg/pull/23674 and https://github.com/microsoft/vcpkg/pull/24011, I hope that this can be closed now.

**Comment by JackBoosY** [comment]
I prefer to keep this issue for some days to make sure it was fixed.

**Comment by dg0yt** [comment]
Okay.

However, the merge immediately stopped new errors here:
https://github.com/microsoft/vcpkg/actions/workflows/untrustedPR.yml?query=is%3Afailure 
And there was one PR where only the version string message was passed:
https://github.com/microsoft/vcpkg/pull/24060#pullrequestreview-937163719 
So anything else should be a new issue.

**Comment by ras0219-msft** [comment]
Agreed, new issues are cheap and open issues are expensive when trying to separate noise.
