### ISSUE TITLE
[qt5-svg] Looking for qmake in the wrong directory with community triplet

### ISSUE THREAD

**Issue by RenaudB42** [microsoft/vcpkg#23590]
__Host Environment__

- OS: Windows 10
- Compiler: Build tools for VS2022 with toolset v142
- IDE : VSCode
- Buildsystem : Cmake with vcpkg integration

__Config files__

- settings.json : 
```
{
    "C_Cpp.default.configurationProvider": "ms-vscode.cmake-tools",
    "cmake.configureSettings": {
        "CMAKE_TOOLCHAIN_FILE": "D:/Developpements/vcpkg/scripts/buildsystems/vcpkg.cmake",
        "VCPKG_TARGET_TRIPLET": "x64-windows-142",
        "VCPKG_BUILD": "ON",
      }
}
```
- triplet file x64-windows-142.cmake
```
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_PLATFORM_TOOLSET v142)
``` 

__Log file__

- vcpkg-manifest-install.log

````
-- Using cached qtsvg-everywhere-src-5.15.2.tar.xz.
[cmake] -- Cleaning sources at D:/Developpements/vcpkg/buildtrees/qt5-svg/src/5.15.2-863459677c.clean. Use --editable to skip cleaning for the packages you specify.
[cmake] -- Extracting source D:/Developpements/vcpkg/downloads/qtsvg-everywhere-src-5.15.2.tar.xz
[cmake] -- Using source at D:/Developpements/vcpkg/buildtrees/qt5-svg/src/5.15.2-863459677c.clean
[cmake] D:/Developpements/C++/DEUFI/Deufi-031022/build/vcpkg_installed/x64-windows  // adding message("${CURRENT_HOST_INSTALLED_DIR}") in vcpkg\scripts\cmake\vcpkg_configure_qmake.cmake 
[cmake] CMake Error at scripts/cmake/vcpkg_configure_qmake.cmake:41 (message):
[cmake]   vcpkg_configure_qmake: unable to find qmake.
[cmake] Call Stack (most recent call first):
[cmake]   D:/Developpements/C++/DEUFI/Deufi-031022/build/vcpkg_installed/x64-windows-142/share/qt5/qt_build_submodule.cmake:10 (vcpkg_configure_qmake)
[cmake]   D:/Developpements/C++/DEUFI/Deufi-031022/build/vcpkg_installed/x64-windows-142/share/qt5/qt_submodule_installation.cmake:8 (qt_build_submodule)
[cmake]   buildtrees/versioning_/versions/qt5-svg/4cdec015d18a0bf66a77ea27006346f0fe382c64/portfile.cmake:2 (qt_submodule_installation)
[cmake]   scripts/ports.cmake:145 (include)
````

__Issue__

vcpkg is looking for qmake in the x64-windows subdirectory. This directory is quite empty since everything is built in x64-windows-v142 as i'm using a self-defined triplet file.

I think that all Qt subpackages calling vcpkg_configure_qmake.cmake could be affected the same way.

__Fix / Workaround__

Change vcpkg/scripts/cmake/vcpkg_configure_qmake.cmake line 37 : 
````
find_program(qmake_executable NAMES qmake PATHS "${CURRENT_HOST_INSTALLED_DIR}/tools/qt5/bin" NO_DEFAULT_PATH)
````
CURRENT_HOST_INSTALLED_DIR -> CURRENT_INSTALLED_DIR

**Comment by Neumann-A** [comment]
pass `--host-triplet=x64-windows-v142`. real issue seems to be that there is a host dependency missing in qt5-base.

**Comment by RenaudB42** [comment]
>  real issue seems to be that there is a host dependency missing in qt5-base.

I'm not quite sure about that. All my libraries (eg boost ) are built in my custom triplet directory. Qt5-base is in the right directory. There is nothing to look for in my host triplet directory.

**Comment by Adela0814** [comment]
@RenaudB42  Is your problem solved?

**Comment by LilyWangLL** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
