### ISSUE TITLE
[brotli] Build error with wasm32-emscripten triplet

### ISSUE THREAD

**Issue by PanForPancakes** [microsoft/vcpkg#23592]
**Host Environment**
- OS: Windows 11

**To Reproduce**
`./vcpkg install brotli:wasm32-emscripten`

**Failure logs** 
```
 Command failed: C:/Users/panforpancakes/vcpkg/downloads/tools/cmake-3.22.2-windows/cmake-3.22.2-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j21
    Working Directory: C:/Users/panforpancakes/vcpkg/buildtrees/brotli/wasm32-emscripten-dbg

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:106 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:44 (vcpkg_build_cmake)
  ports/brotli/portfile.cmake:20 (vcpkg_install_cmake)
  scripts/ports.cmake:145 (include)
```
..\vcpkg\buildtrees\brotli\install-wasm32-emscripten-dbg-err.log contains only one line:
```
ninja: error: unknown target 'install'
```

**Additional context**
Tried using both command line and powershell, neither of them works.
Issue with emscripten has been fixed in this PR https://github.com/google/brotli/pull/906
Same issues:
before fix: https://github.com/microsoft/vcpkg/issues/14574
after fix: https://github.com/microsoft/vcpkg/issues/16330

**Comment by LilyWangLL** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.

**Comment by ankurvdev** [comment]
This is still an issue
Fixed by 
-DBROTLI_EMSCRIPTEN=OFF

Looks like Brotli's cmakelist simply turns off all "install" cmake commands if it detects the emscripten platform

**Comment by LilyWangLL** [comment]
> This is still an issue Fixed by -DBROTLI_EMSCRIPTEN=OFF
> 
> Looks like Brotli's cmakelist simply turns off all "install" cmake commands if it detects the emscripten platform

Could you please submit a PR to fix this issue? I have no related machine to test it.
