### ISSUE TITLE
[libtorrent] Build error - x64-windows-static

### ISSUE THREAD

**Issue by ngjermundshaug** [microsoft/vcpkg#23595]
**Host Environment**
- OS: Win10
- Compiler: VS2022 (143)
- vcpkg-tool version: 2022-03-09-1affd32f93b299d5a907816c328ca3ededb73a7e
- vcpkg-scripts version: 5220969a9 2022-03-15 (12 hours ago)

**To Reproduce**
`./vcpkg.exe install libtorrent:x64-windows-static`

**Failure logs** 
C:\dev\vcpkg>vcpkg.exe install libtorrent:x64-windows-static
Computing installation plan...
The following packages will be built and installed:
    libtorrent[core,iconv]:x64-windows-static -> 2.0.5
Detecting compiler hash for triplet x64-windows-static...
Restored 0 packages from C:\Users\njal\AppData\Local\vcpkg\archives in 121.3 us. Use --debug to see more details.
Starting package 1/1: libtorrent:x64-windows-static
Building package libtorrent[core,iconv]:x64-windows-static...
-- Using cached arvidn-libtorrent-44e285c30f06772e48f515580f961998e1037b7e.tar.gz.
-- Cleaning sources at C:/dev/vcpkg/buildtrees/libtorrent/src/98e1037b7e-1ad34bc5b8.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/dev/vcpkg/downloads/arvidn-libtorrent-44e285c30f06772e48f515580f961998e1037b7e.tar.gz
-- Using source at C:/dev/vcpkg/buildtrees/libtorrent/src/98e1037b7e-1ad34bc5b8.clean
-- Using cached arvidn-try_signal-334fd139e2bb387017b42d36753a03935e3bca75.tar.gz.
-- Cleaning sources at C:/dev/vcpkg/buildtrees/libtorrent/src/935e3bca75-187e852738.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/dev/vcpkg/downloads/arvidn-try_signal-334fd139e2bb387017b42d36753a03935e3bca75.tar.gz
-- Using source at C:/dev/vcpkg/buildtrees/libtorrent/src/935e3bca75-187e852738.clean
-- Using cached paullouisageneau-boost-asio-gnutls-a57d4d36923c5fafa9698e14be16b8bc2913700a.tar.gz.
-- Cleaning sources at C:/dev/vcpkg/buildtrees/libtorrent/src/bc2913700a-b5eb8c940f.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/dev/vcpkg/downloads/paullouisageneau-boost-asio-gnutls-a57d4d36923c5fafa9698e14be16b8bc2913700a.tar.gz
-- Using source at C:/dev/vcpkg/buildtrees/libtorrent/src/bc2913700a-b5eb8c940f.clean
-- Using cached arvidn-libsimulator-64fb5b4fde1879abc09c018604d57e485a12e999.tar.gz.
-- Cleaning sources at C:/dev/vcpkg/buildtrees/libtorrent/src/485a12e999-ef147a2159.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/dev/vcpkg/downloads/arvidn-libsimulator-64fb5b4fde1879abc09c018604d57e485a12e999.tar.gz
-- Using source at C:/dev/vcpkg/buildtrees/libtorrent/src/485a12e999-ef147a2159.clean
CMake Error at ports/libtorrent/portfile.cmake:66 (vcpkg_cmake_configure):
  Unknown CMake command "vcpkg_cmake_configure".
Call Stack (most recent call first):
  scripts/ports.cmake:145 (include)

Error: Building package libtorrent:x64-windows-static failed with: BUILD_FAILED

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. There are error message: 
```
CMake Error at ports/libtorrent/portfile.cmake:66 (vcpkg_cmake_configure):
Unknown CMake command "vcpkg_cmake_configure".
```
Did you use the latest version of vcpkg? Please run command `git pull` and `.\bootstrap-vcpkg.bat` before installing port.

**Comment by LilyWangLL** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
