### ISSUE TITLE
[ncurses] Build error on x64-linux

### ISSUE THREAD

**Issue by hihig2001** [microsoft/vcpkg#23598]
**Host Environment**
- OS: WSL-Ubuntu20.04 / windows 10, 19044 (in case if need)
- Compiler: revision

**To Reproduce**
`./vcpkg install ncurses`

**Failure logs** 
### Log
Computing installation plan...
The following packages will be built and installed:
    ncurses[core]:x64-linux -> 6.3#1
Detecting compiler hash for triplet x64-linux...
Restored 0 packages from /home/hihig/.cache/vcpkg/archives in 33.6 us. Use --debug to see more details.
Starting package 1/1: ncurses:x64-linux
Building package ncurses[core]:x64-linux...
-- Using cached ncurses-6.3.tgz.
-- Cleaning sources at /mnt/c/programs/vcpkg/buildtrees/ncurses/src/ncurses-6-4e7ee3180a.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /mnt/c/programs/vcpkg/downloads/ncurses-6.3.tgz
-- Using source at /mnt/c/programs/vcpkg/buildtrees/ncurses/src/ncurses-6-4e7ee3180a.clean
-- Getting CMake variables for x64-linux-dbg
-- Getting CMake variables for x64-linux-rel
-- Configuring x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:128 (message):
    Command failed: /usr/bin/bash -c "V=1 ./../src/ncurses-6-4e7ee3180a.clean/configure  \"--disable-db-install\" \"--enable-pc-files\" \"--without-ada\" \"--without-manpages\" \"--without-progs\" \"--without-tack\" \"--without-tests\" \"--disable-silent-rules\" \"--verbose\" \"--disable-shared\" \"--enable-static\" \"--with-pkg-config-libdir=/mnt/c/programs/vcpkg/installed/x64-linux/debug/lib/pkgconfig\" \"--with-debug\" \"--without-normal\" \"--prefix=/mnt/c/programs/vcpkg/installed/x64-linux/debug\""
    Working Directory: /mnt/c/programs/vcpkg/buildtrees/ncurses/x64-linux-dbg
    Error code: 1
    See logs for more information:
      /mnt/c/programs/vcpkg/buildtrees/ncurses/config-x64-linux-dbg-out.log
      /mnt/c/programs/vcpkg/buildtrees/ncurses/config-x64-linux-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:815 (vcpkg_execute_required_process)
  ports/ncurses/portfile.cmake:52 (vcpkg_configure_make)
  scripts/ports.cmake:145 (include)

Error: Building package ncurses:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `./vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+ncurses
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[ncurses]+Build+error
including:
  package: ncurses[core]:x64-linux -> 6.3#1
    vcpkg-tool version: 2022-03-09-1affd32f93b299d5a907816c328ca3ededb73a7e
    vcpkg-scripts version: 5220969a9 2022-03-15 (17 hours ago)

### /mnt/c/programs/vcpkg/buildtrees/ncurses/config-x64-linux-dbg-out.log
checking for ggrep... no
checking for grep... grep
checking for egrep... grep -E
Configuring NCURSES 6.3 ABI 6 (Thu Mar 17 00:24:01 KST 2022)
checking for package version... 6.3
checking for package patch date... 20211021
        ABI VERSION 5:0:10
        VERSION_MAJOR 6
        VERSION_MINOR 3
        VERSION_PATCH 20211021
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
Configuring for linux-gnu
checking for fgrep... grep -F
checking for prefix... /mnt/c/programs/vcpkg/installed/x64-linux/debug
checking for gcc... gcc
checking for C compiler default output... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for executable suffix...
checking for object suffix... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking version of gcc... 9.4.0
checking if this is really Intel C compiler... no
checking if this is really Clang C compiler... no
checking for gcc option to accept ANSI C... none needed
checking $CFLAGS variable... ok
checking $CC variable... ok
checking how to run the C preprocessor... gcc -E
checking whether gcc needs -traditional... no
checking whether gcc understands -c and -o together... yes
checking for ldconfig... /usr/sbin/ldconfig
checking if you want to ensure bool is consistent with C++... yes
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking if g++ works... yes
checking for g++... /usr/bin/g++
checking version of /usr/bin/g++... 9.4.0
checking if you want to build C++ binding and demo... yes
checking if you want to build with Ada... no
checking if you want to install terminal database... no
checking if you want to install manpages... no
checking if you want to build programs such as tic... no
checking if you want to build test-programs... no
checking if you wish to install curses.h... yes
checking for mawk... mawk
checking for a BSD compatible install... /usr/bin/install -c
checking for lint... no
checking for cppcheck... no
checking for splint... no
checking whether ln -s works... yes
checking if ln -s -f options work... yes
checking for long file names... yes
checking if you want to use pkg-config... yes
checking for pkg-config... /bin/pkg-config --static
checking for /bin/pkg-config --static library directory... checking for first directory... none
checking if we should install .pc files for /bin/pkg-config --static... yes

###  /mnt/c/programs/vcpkg/buildtrees/ncurses/config-x64-linux-dbg-err.log
configure: error: expected a pathname, not ""

**Additional context**
at first, permission denied to rename so i do chown
at second, don't have pkg-config so i did "apt-get instal pkg-config"
now i'm stuck. please help

**Comment by hihig2001** [comment]
setting environment variable

`PKG_CONFIG_LIBDIR=/usr/lib/pkgconfig`

make it work
but manually installing pkg-config and setting environment variable is really cumbersome
is it meant to be? or is there are alternative way to show dependency using "vcpkg.json"?

**Comment by Cheney-W** [comment]
Dup to https://github.com/microsoft/vcpkg/issues/22654
