### ISSUE TITLE
Libiconv library installed in vcpkg missing files cause cmake can not import package on Windows x64

### ISSUE THREAD

**Issue by Liu-Zhiying** [microsoft/vcpkg#23606]
**Describe the bug**
Libiconv library installed in vcpkg missing files cause cmake can not import package on Windows x64.

**Environment**
- OS: Windows 11 x64
- Compiler: MSVC v143

**To Reproduce**
1. ./vcpkg install libiconv:x64-windows.
2. add this package in cmake using VS.
3. Compile.
Repro code when Compile

**Expected behavior**
cmake show error message that missing "iconvConfig.cmake" or "iconv-config.cmake".

**Failure logs** 
see pictures.
![QQ截图20220317122824](https://user-images.githubusercontent.com/51241479/158737352-2a5011f7-82c0-4420-adc0-bf9c8f2547a7.png)
![QQ截图20220317122837](https://user-images.githubusercontent.com/51241479/158737357-a7cbcce0-76e1-4714-b651-90667003fae9.png)

**Additional context**
I think this is a bug that caused by missing files.
I can not see the target folder has the required files.

**Comment by Liu-Zhiying** [comment]
Sorry i have a spell error in the title.
"camke" should be "cmake".

**Comment by dg0yt** [comment]
Note the correct spelling:
~~~
find_package(Iconv)
~~~
This is provide by a Find module from CMake, not by config files exported from libiconv.
https://cmake.org/cmake/help/v3.19/module/FindIconv.html

**Comment by Liu-Zhiying** [comment]
Thanks
I jiust copy the context which show in vcpkg. like this:
![QQ截图20220317134127](https://user-images.githubusercontent.com/51241479/158744507-dbdd4100-ea91-4271-b91a-3a758b3af010.png)
![QQ截图20220317133937](https://user-images.githubusercontent.com/51241479/158744328-ccd6eb6a-e58c-42e8-ba11-21b6e5219c9a.png)
It seems be wrong with "CONFIG REQUIRED".
when i delete it,it works.

**Comment by dg0yt** [comment]
This is a known issue: #20190.
