### ISSUE TITLE
[sdl2] Build error

### ISSUE THREAD

**Issue by 21020757** [microsoft/vcpkg#23604]
**Host Environment**
- OS: Windows 11
- Compiler: g ++ 10.2

**To Reproduce**

.\vcpkg\vcpkg install sdl2:x64-windows

**Failure logs** 
C:\Users\fpt>.\vcpkg\vcpkg install sdl2:x64-windows
Computing installation plan...
A suitable version of cmake was not found (required v3.22.2). Downloading portable cmake v3.22.2...
Downloading cmake...
  https://github.com/Kitware/CMake/releases/download/v3.22.2/cmake-3.22.2-windows-i386.zip -> C:\Users\fpt\vcpkg\downloads\cmake-3.22.2-windows-i386.zip
Extracting cmake...
The following packages will be built and installed:
    sdl2[core]:x64-windows -> 2.0.20
  * vcpkg-cmake[core]:x64-windows -> 2022-01-19
  * vcpkg-cmake-config[core]:x64-windows -> 2022-02-06
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
A suitable version of 7zip was not found (required v21.7.0). Downloading portable 7zip v21.7.0...
Downloading 7zip...
  https://www.7-zip.org/a/7z2107-extra.7z -> C:\Users\fpt\vcpkg\downloads\7z2107-extra.7z
Extracting 7zip...
Restored 2 packages from C:\Users\fpt\AppData\Local\vcpkg\archives in 5.495 s. Use --debug to see more details.
Starting package 1/3: vcpkg-cmake:x64-windows
Installing package vcpkg-cmake[core]:x64-windows...
Elapsed time for package vcpkg-cmake:x64-windows: 47.92 ms
Starting package 2/3: vcpkg-cmake-config:x64-windows
Installing package vcpkg-cmake-config[core]:x64-windows...
Elapsed time for package vcpkg-cmake-config:x64-windows: 36.6 ms
Starting package 3/3: sdl2:x64-windows
Building package sdl2[core]:x64-windows...
-- Downloading https://github.com/libsdl-org/SDL/archive/release-2.0.20.tar.gz -> libsdl-org-SDL-release-2.0.20.tar.gz...
-- Extracting source C:/Users/fpt/vcpkg/downloads/libsdl-org-SDL-release-2.0.20.tar.gz
-- Applying patch 0001-sdl2-Enable-creation-of-pkg-cfg-file-on-windows.patch
-- Applying patch 0002-sdl2-skip-ibus-on-linux.patch
-- Applying patch 0003-sdl2-disable-sdlmain-target-search-on-uwp.patch
-- Applying patch 0004-Define-crt-macros.patch
-- Applying patch 0005-Fix-uwp-joystick.patch
-- Applying patch 0006-Update-SDL_sysurl.cpp.patch
-- Using source at C:/Users/fpt/vcpkg/buildtrees/sdl2/src/ase-2.0.20-4d7f28b96f.clean
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:128 (message):
    Command failed: ninja -v
    Working Directory: C:/Users/fpt/vcpkg/buildtrees/sdl2/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\Users\fpt\vcpkg\buildtrees\sdl2\config-x64-windows-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:415 (vcpkg_execute_required_process)
  ports/sdl2/portfile.cmake:34 (vcpkg_cmake_configure)
  scripts/ports.cmake:145 (include)

Error: Building package sdl2:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+sdl2
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[sdl2]+Build+error
including:
  package: sdl2[core]:x64-windows -> 2.0.20
    vcpkg-tool version: 2022-03-09-1affd32f93b299d5a907816c328ca3ededb73a7e
    vcpkg-scripts version: 6b6f5a82d 2022-03-16 (2 hours ago)

Additionally, attach any relevant sections from the log files above.
**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by Adela0814** [comment]
@21020757  please upload the failure log` C:\Users\fpt\vcpkg\buildtrees\sdl2\config-x64-windows-out.log`, thanks.

**Comment by 21020757** [comment]
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/8282058/config-x64-windows-out.log)
here sir

**Comment by Adela0814** [comment]
See the required Visual Studio components in https://github.com/microsoft/vcpkg-tool/pull/314.

**Comment by 21020757** [comment]
I now got another problem, it seems like the linking isn't working

[testcode.txt](https://github.com/microsoft/vcpkg/files/8287853/testcode.txt)

[error.txt](https://github.com/microsoft/vcpkg/files/8287826/error.txt)

here is my cmake
[cmake.txt](https://github.com/microsoft/vcpkg/files/8287821/cmake.txt)

could you please help me
