### ISSUE TITLE
[cudnn] Build error

### ISSUE THREAD

**Issue by eix128** [microsoft/vcpkg#23609]
**Host Environment**
- OS: [Windows]
- Compiler: visual c 2022
- cudnn[core]:x64-windows-static -> 7.6.5#4

**To Reproduce**
`./vcpkg install cudnn`

Error: Building package cudnn:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.

**Comment by Adela0814** [comment]
@eix128  Please upload all failure logs.

**Comment by Adela0814** [comment]
ping for response

**Comment by eix128** [comment]
Okay ,  i tried on different pc and 
vcpkg install cudnn:x64-windows
This command worked thank you...
