### ISSUE TITLE
[New Port Request] opennurbs

### ISSUE THREAD

**Issue by xarthurx** [microsoft/vcpkg#23614]
Library name: opennurbs

Library description: 

The openNURBS Initiative provides CAD, CAM, CAE, and computer graphics software developers the tools to accurately transfer 3D geometry between applications.

The openNURBS Toolkit consists of C++ source code for a library that will read and write openNURBS 3D model files (.3dm). More than 400 software development teams and applications, including [Rhinoceros®](https://rhino3d.com/), exchange 3D models using the openNURBS file format. Additionally, the Toolkit provides NURBS evaluation tools and elementary geometric and 3D view manipulation tools as well as including source code for several example programs.

Source repository URL: https://github.com/mcneel/opennurbs

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
A fundamental lib for developing CAD and nurbs software related to Rhino environment.
There's no `CMakeList.txt`, I need help to add this to vcpkg...

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by xarthurx** [comment]
Hello, coming back again.

I need this library to be added.
Without including it in the `vcpkg`, it is hard to set up github actions to compile projects that depend on it on the cloud.

**Comment by xarthurx** [comment]
FYI, there is an unmerged PR in the repo: https://github.com/mcneel/opennurbs/pull/29
which added CMake options.

**Comment by JackBoosY** [comment]
Can you please make a PR to start this progress?

**Comment by xarthurx** [comment]
Yes, but before I do this, I found more info about the previous effort:

https://github.com/microsoft/vcpkg/pull/21521
https://discourse.mcneel.com/t/opennurbs-pre-builds-for-github-action/146973/4

Could you please give it a check and let me know if you're still fine to start this? Then I can make a PR.

**Comment by JackBoosY** [comment]
Ah, #21521 is adding this port, just need to wait for merge it.

**Comment by xarthurx** [comment]
> Ah, #21521 is adding this port, just need to wait for merge it.

Yeah, but it seems McNeel does not want to add it to vcpkg.

**Comment by JackBoosY** [comment]
@xarthurx Let's make discuss in that PR.
