### ISSUE TITLE
[boost-test] Build error Error: Building package boost-test:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by MurrayCapricorns** [microsoft/vcpkg#23618]
**Host Environment**
- OS: WIN11
- Compiler: VS2022

**To Reproduce**
`./vcpkg install boost:x86-windows`

**Failure logs** 
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:158 (message):
    Command failed: D:/mamy/vcpkg/downloads/tools/cmake-3.22.2-windows/cmake-3.22.2-windows-i386/bin/cmake.exe --build . --config Release --target install -- -v -j17
    Working Directory: D:/mamy/vcpkg/buildtrees/boost-test/x86-windows-rel
    See logs for more information:
      D:\mamy\vcpkg\buildtrees\boost-test\install-x86-windows-rel-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:111 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
  installed/x64-windows/share/boost-build/boost-modular-build.cmake:124 (vcpkg_cmake_install)
  ports/boost-test/portfile.cmake:19 (boost_modular_build)
  scripts/ports.cmake:145 (include)

Error: Building package boost-test:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-test
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[boost-test]+Build+error
including:
  package: boost-test[core]:x86-windows -> 1.78.0
    vcpkg-tool version: 2022-03-09-1affd32f93b299d5a907816c328ca3ededb73a7e
    vcpkg-scripts version: 6f827f25f 2022-03-17 (4 hours ago)
[install-x86-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/8298776/install-x86-windows-rel-out.log)

-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Could you please provide the error log file?
**D:\mamy\vcpkg\buildtrees\boost-test\install-x86-windows-rel-out.log**

**Comment by MurrayCapricorns** [comment]
> Thanks for posting this issue. Could you please provide the error log file? **D:\mamy\vcpkg\buildtrees\boost-test\install-x86-windows-rel-out.log**

Hi, actually he log is  provided  (https://github.com/microsoft/vcpkg/files/8298776/install-x86-windows-rel-out.log) .But,i want to say that i have already updated vcpkg and it was woked fine.. Thank you. i will close this issue..
