### ISSUE TITLE
Error in fetchDependency.ps1 while downloading CMake

### ISSUE THREAD

**Issue by PuzzleBlue** [Microsoft/vcpkg#2361]
After executing a `.\vcpkg install <package>` command, I get the error:

> Could not run:
>    'C:/temp/vcpkg/scripts/fetchDependency.ps1'
An error description follows that points to an illegal method call on a null pointer in file C:\temp\vcpkg\scripts\VcpkgPowershellUtils.ps1, line 180.

I had a look at the `vcpkgExtractFile` function in fetchDependency.ps1
My machine runs Windows 7 and Pscx is not installed. So I have no `Expand-Archive` command available and the function will use the "shell.application" object which does not seem to accept forward slashes in folder paths. 
In my configuration, the issue was fixed by replacing the forward slash with a backslash at line 155 of file fetchDependency.ps1 (in variable `$destinationPartial`)

**Comment by alexkaratarakis** [comment]
Thanks for reporting!
