### ISSUE TITLE
libpq:x64-windows Error: Building

### ISSUE THREAD

**Issue by wuvalue** [microsoft/vcpkg#23615]
-- Applying patch patches/windows/Solution_RELEASE.patch
-- Applying patch patches/windows/python3_build_RELEASE.patch
-- Patches applied!
-- Building libpq x64-windows-RELEASE...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:128 (message):
    Command failed: D:/vcpkg/vcpkg-master/downloads/tools/perl/5.32.1.1/perl/bin/perl.exe build.pl RELEASE libpq
    Working Directory: D:/vcpkg/vcpkg-master/buildtrees/libpq/x64-windows-rel/src/tools/msvc
    Error code: 1
    See logs for more information:
      D:\vcpkg\vcpkg-master\buildtrees\libpq\build-libpq-x64-windows-RELEASE-out.log
      D:\vcpkg\vcpkg-master\buildtrees\libpq\build-libpq-x64-windows-RELEASE-err.log

Call Stack (most recent call first):
  ports/libpq/portfile.cmake:223 (vcpkg_execute_required_process)
  scripts/ports.cmake:145 (include)

Error: Building package libpq:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libpq
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[libpq]+Build+error
including:
  package: libpq[core,openssl,zlib]:x64-windows -> 12.9#1
    vcpkg-tool version: 2022-03-09-1affd32f93b299d5a907816c328ca3ededb73a7e
    vcpkg-scripts version: unknown

**Comment by Cheney-W** [comment]
Could you please provide following logs to me? Thank you!
D:\vcpkg\vcpkg-master\buildtrees\libpq\build-libpq-x64-windows-RELEASE-out.log
D:\vcpkg\vcpkg-master\buildtrees\libpq\build-libpq-x64-windows-RELEASE-err.log

**Comment by wuvalue** [comment]
> 您能为我提供以下日志吗？谢谢！ D：\vcpkg\vcpkg-master\buildtrees\libpq\build-libpq-x64-windows-RELEASE-out.log D：\vcpkg\vcpkg-master\buildtrees\libpq\build-libpq-x64-windows-RELEASE-err.log

[build-libpq-x64-windows-RELEASE-err.log](https://github.com/microsoft/vcpkg/files/8300749/build-libpq-x64-windows-RELEASE-err.log)
[build-libpq-x64-windows-RELEASE-out.log](https://github.com/microsoft/vcpkg/files/8300750/build-libpq-x64-windows-RELEASE-out.log)
[error-logs-x64-windows.txt](https://github.com/microsoft/vcpkg/files/8300752/error-logs-x64-windows.txt)
[patch-x64-windows-0-err.log](https://github.com/microsoft/vcpkg/files/8300754/patch-x64-windows-0-err.log)
[patch-x64-windows-1-err.log](https://github.com/microsoft/vcpkg/files/8300755/patch-x64-windows-1-err.log)
[patch-x64-windows-2-err.log](https://github.com/microsoft/vcpkg/files/8300757/patch-x64-windows-2-err.log)
[patch-x64-windows-3-err.log](https://github.com/microsoft/vcpkg/files/8300758/patch-x64-windows-3-err.log)
[patch-x64-windows-4-err.log](https://github.com/microsoft/vcpkg/files/8300760/patch-x64-windows-4-err.log)
[patch-x64-windows-5-err.log](https://github.com/microsoft/vcpkg/files/8300762/patch-x64-windows-5-err.log)
[patch-x64-windows-6-err.log](https://github.com/microsoft/vcpkg/files/8300763/patch-x64-windows-6-err.log)
[patch-x64-windows-7-err.log](https://github.com/microsoft/vcpkg/files/8300764/patch-x64-windows-7-err.log)
[patch-x64-windows-8-err.log](https://github.com/microsoft/vcpkg/files/8300766/patch-x64-windows-8-err.log)
[stdout-x64-windows.log](https://github.com/microsoft/vcpkg/files/8300767/stdout-x64-windows.log)
[x64-windows.vcpkg_abi_info.txt](https://github.com/microsoft/vcpkg/files/8300769/x64-windows.vcpkg_abi_info.txt)

**Comment by Cheney-W** [comment]
Could you please reinstall this port again with following command:
`.\vcpkg install libpq[core,openssl,zlib]:x64-windows --binarysource=clear`

**Comment by howe1110** [comment]
I get the same error too.

**Comment by Cheney-W** [comment]
@howe1110 
The link of your log is https://github.com/microsoft/vcpkg/issues/url ???

**Comment by howe1110** [comment]
I had upload the error file [RELEASE-err.log]，I'm not sure it's the content of the file.
I fixed the error by installed the english language package to vs 2017.

**Comment by ylz-at** [comment]
> I had upload the error file [RELEASE-err.log]，I'm not sure it's the content of the file. I fixed the error by installed the english language package to vs 2017.

no way...

**Comment by Cheney-W** [comment]
Glad to know that your problem has been solved. 
The English language pack is fundamental for vcpkg to work correctly.

**Comment by ylz-at** [comment]
> Glad to know that your problem has been solved.
> The English language pack is fundamental for vcpkg to work correctly.

This should be documented somewhere.

**Comment by SchaichAlonso** [comment]
It actually is documented on the README.md in the top level directory, `Getting Started` -> `Quick Start: Windows` ( or click [here](https://github.com/Microsoft/vcpkg#quick-start-windows) ), where `Visual Studio 2015 Update 3 or greater with the English language pack` is listed as a requirement

**Comment by hugege1123** [comment]
你好，我用vcpkg执行命令： .\vcpkg install libpq[core,openssl,zlib]:x64-windows --binarysource=clear出现这样的错误如下：
error: building libpq:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libpq
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[libpq]+Build+error
Include '[libpq] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-10-17-3247920fbdd47d08f36cbd480addd9890d3c2435
    vcpkg-scripts version: 49931943a 2022-11-02 (17 hours ago)


Please use the prefilled template from D:\vcpkg\installed\vcpkg\issue_body.md when reporting your issue.
PS D:\vcpkg>

**Comment by hugege1123** [comment]
你好，已经解决，也是安装了英语语言包解决扽，谢谢各位！

**Comment by DNA-QS** [comment]
i'm facing the same issue ..how shouldcan I solve this problem

**Comment by hugege1123** [comment]
我是更新了vs 2015 的语言包，你可以上网查一下“如何更新活添加English语言包”。
