### ISSUE TITLE
How do I troubleshoot vcpkg ce?

### ISSUE THREAD

**Issue by tdjastrzebski** [microsoft/vcpkg#23629]
Trying to follow [Embedded Software Development in Visual Studio
](https://devblogs.microsoft.com/cppblog/visual-studio-embedded-development/) tutorial, at final step while executing `vcpkg activate` I get:
```
vcpkg-ce ('configure environment') is experimental and may change at any time.
Downloading vcpkg-ce bundle 2022-03-09
Failed to provision vcpkg-ce.
```
No details are provided. How do I go about troubleshooting/debugging it? It does not seem vcpkg has a "verbose" option.

**Comment by tdjastrzebski** [comment]
I have figured it out trying to install vcpkg-ce manually using npm. It turns out vcpkg-ce needs node.js ver 14, mine was 12.
I think better error reporting might be beneficial.

**Comment by BillyONeal** [comment]
vcpkg should have refused to use a node that was too old. Can you try again with --debug?

**Comment by BillyONeal** [comment]
> My point was that some more error info provided by default would be very helpful or, at least, info on how to find what the underlying error was.

The issue is that I don't know what the underlying error is to know where to add logging here. :/
