### ISSUE TITLE
vcpkg will rebuild dependencies that was already built with feature packages

### ISSUE THREAD

**Issue by jasjuang** [Microsoft/vcpkg#2362]
Suppose I installed VTK with feature package openvr, qt, and mpi

```
vcpkg install vtk[openvr,qt,mpi] --featurepackages --recurse
```

It installs successfully, the problem is when I try to build opencv with vtk, it wants to remove the VTK I already installed and rebuild it with the vanilla version

```
vcpkg install opencv[vtk] --featurepackages --recurse

The following packages will be built and installed:
    opencv[core,vtk]:x64-windows-dev
  * vtk[core]:x64-windows-dev
```

Can we fix it so when installing opencv it won't attempt to rebuild vtk?

EDIT: with further testing, the weird thing is this is only reproducible if I run it through a bat file with consecutive command say 

installlib.bat
``` 
vcpkg install vtk[openvr,qt,mpi] --featurepackages --recurse
vcpkg install opencv[vtk] --featurepackages --recurse
```

If I manually type it one by one in the command line, it actually works. Can we fix it so even if we are using a bat file it will still work?

**Comment by ras0219-msft** [comment]
Thanks for reporting!

I'm also having difficulty reproducing this. Can you confirm that:
1. You're using the latest vcpkg (throw `vcpkg version` in the bat file). We did fix bugs previously which would result in this error.
2. `vtk` did successfully install between the two commands (run `vcpkg list --featurepackages` in the bat file between the two commands). The behavior you're seeing would be entirely consistent with a failed `vtk` install.

Additionally, could you copy out the `installed\vcpkg\status` file and `installed\vcpkg\updates\` folder between the two install commands? I am suspecting that the `install opencv` command is not recognizing that `vtk` is installed, which would result in this behavior.

**Comment by jasjuang** [comment]
@ras0219-msft I figured out a way to reproduce this. It happens during the recent openssl update, so in order to recreate the situation, in my installlib.bat

```
vcpkg remove openssl --recurse
vcpkg install vtk[openvr,qt,mpi] --featurepackages --recurse
vcpkg install opencv[vtk] --featurepackages --recurse
```

I tested this two times. Although it takes a lot of time to build it will trigger the problem. The weird thing is the below actually works fine

```
vcpkg remove vtk --recurse
vcpkg install vtk[openvr,qt,mpi] --featurepackages --recurse
vcpkg install opencv[vtk] --featurepackages --recurse
```

and that's probably what you are testing with hence you can't reproduce the problem.

**Comment by JackBoosY** [comment]
Hi @jasjuang , thanks for reporting this issue!
Please open a new issue if this is still a problem for you.
Thx.
