### ISSUE TITLE
[boost-regex] Build error

### ISSUE THREAD

**Issue by bobluoluo** [microsoft/vcpkg#23632]
**Host Environment**
- OS: ubuntu 18.04
- Compiler: gcc 7.5

**To Reproduce**
`./vcpkg install boost-regex`

**Failure logs** 
Call Stack (most recent call first):
  installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:360 (vcpkg_execute_required_process)
  installed/x64-linux/share/boost-build/boost-modular-build.cmake:108 (vcpkg_cmake_configure)
  ports/boost-regex/portfile.cmake:15 (boost_modular_build)
  scripts/ports.cmake:145 (include)

Error: Building package boost-regex:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `./vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-regex
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[boost-regex]+Build+error
including:
  package: boost-regex[core]:x64-linux -> 1.78.0
    vcpkg-tool version: 2022-03-09-1affd32f93b299d5a907816c328ca3ededb73a7e
    vcpkg-scripts version: af2287382 2022-03-11 (7 days ago)

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Could you please provide the error log file? Did you use latest VCPKG?

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. I can't repro this issue locally, please reopen this issue if it still be a problem for you.
