### ISSUE TITLE
[date] Update port to fix use-of-uninitialized-value

### ISSUE THREAD

**Issue by acgetchell** [microsoft/vcpkg#23637]
**Describe the bug**
The current port for [date] when running on MSAN produces:

```
SUMMARY: MemorySanitizer: use-of-uninitialized-value (/home/travis/build/acgetchell/CDT-plusplus/build/src/cdt+0x642ce1) in date::get_tzdb_list()
```

This was fixed in:

https://github.com/HowardHinnant/date/pull/698/commits/a74eb1a540263eb883967e4f2dd8ed82f2e863d4

Please revise the port to include these changes.

**Environment**
- OS: Ubuntu 20.04
- Compiler: clang-13

**To Reproduce**
1. ./vcpkg install date
2. Run MSAN

**Expected behavior**
No uninitialized variable use.

**Failure logs** 

https://app.travis-ci.com/github/acgetchell/CDT-plusplus/jobs/563927674#L1376

**Additional context**

To run MSAN in Travis, I use:

https://github.com/acgetchell/CDT-plusplus/blob/develop/cmake/Sanitizers.cmake#L69

And then build, e.g.:

https://github.com/acgetchell/CDT-plusplus/blob/develop/.travis.yml#L83

It would probably be pretty easy to translate to GHA, I just haven't done so.

**Comment by JonLiu1993** [comment]
@acgetchell, thanks for posting this question, I found out that upstream hasn't released a stable version for a long time, I added a patch as you suggested to apply the changes from https://github.com/HowardHinnant/date/commit/a74eb1a540263eb883967e4f2dd8ed82f2e863d4 , if the upstream releases the stable version, I will update the version immediately, I have submitted a pr to fix this, Could you test this pr on your local machine? Thanks!

**Comment by acgetchell** [comment]
Done. I applied the changes locally and recompiled (arm64-osx) with no errors or warnings.

**Comment by JonLiu1993** [comment]
@acgetchell , I have commit a [issue ](https://github.com/HowardHinnant/date/issues/728)for date upstream, I'll update the port as soon as date releases a new version
