### ISSUE TITLE
[libiconv] build error

### ISSUE THREAD

**Issue by kirin111697** [microsoft/vcpkg#23633]
**Host Environment**
- OS: Windows 10
- package: libiconv[core]:x64-windows-release -> 1.16#12
    vcpkg-tool version: 2022-03-09-1affd32f93b299d5a907816c328ca3ededb73a7e
    vcpkg-scripts version: 6f827f25f 2022-03-17 (18 hours ago)

**To Reproduce**
building darknet with the following command:
 ./build.ps1 -UseVCPKG -InstallDARKNETthroughVCPKG -EnableOPENCV -EnableCUDA -EnableCUDNN -EnableOPENCV_CUDA -InstallDARKNETdependenciesThroughVCPKGManifest                                                                                     

**Failure logs** 
![libiconv error](https://user-images.githubusercontent.com/17411461/159067244-9059e905-41e5-4c7f-8341-ca43d0d85c05.png)

- the out.log file content:

> Makefile:74: update target 'all' due to: iconv_no_i18n.exe iconv.obj iconv.res
test `ls -ld . | sed -e 's/^d\(.........\).*/\1/'` = rwxrwxrwx || chmod 777 .
Makefile:113: update target 'install' due to: all force
if [ ! -d /C/Users/[my path]/Yolov3TinyTrain/darknet-master/vcpkg/packages/libiconv_x64-windows-release/C/Users/[my path]/Yolov3TinyTrain/darknet-master/vcpkg_installed/x64-windows-release/tools/libiconv/bin ] ; then /bin/sh .././../src/1.16-b0c41d3469.clean/build-aux/mkinstalldirs /C/Users/[my path]/Yolov3TinyTrain/darknet-master/vcpkg/packages/libiconv_x64-windows-release/C/Users/[my path]/Yolov3TinyTrain/darknet-master/vcpkg_installed/x64-windows-release/tools/libiconv/bin ; fi
mkdir -p -- /C/Users/[my path]/Yolov3TinyTrain/darknet-master/vcpkg/packages/libiconv_x64-windows-release/C/Users/[my path]/Yolov3TinyTrain/darknet-master/vcpkg_installed/x64-windows-release/tools/libiconv/bin
case "mingw32" in \
  hpux*) compile cl.exe -LC:/Users/[my path]/Yolov3TinyTrain/darknet-master/vcpkg_installed/x64-windows-release/lib -LC:/Users/[my path]/Yolov3TinyTrain/darknet-master/vcpkg_installed/x64-windows-release/lib/manual-link -nologo -W3 -utf-8 -MP -MD -O2 -Oi -Gy -Z7 `if test -n ':'; then : /C/Users/[my path]/Yolov3TinyTrain/darknet-master/vcpkg_installed/x64-windows-release/tools/libiconv/bin; fi` iconv.obj ../srclib/libicrt.a -L/C/Users/[my path]/Yolov3TinyTrain/darknet-master/vcpkg/packages/libiconv_x64-windows-release/C/Users/[my path]/Yolov3TinyTrain/darknet-master/vcpkg_installed/x64-windows-release/lib -liconv  iconv.res `if test -n '/C/Users/[my path]/Yolov3TinyTrain/darknet-master/vcpkg/packages/libiconv_x64-windows-release'; then echo " -Wl,+b -Wl,/C/Users/[my path]/Yolov3TinyTrain/darknet-master/vcpkg_installed/x64-windows-release/lib"; fi` -o iconv.exe;; \
  *) /bin/sh ../libtool --mode=link compile cl.exe -LC:/Users/[my path]/Yolov3TinyTrain/darknet-master/vcpkg_installed/x64-windows-release/lib -LC:/Users/[my path]/Yolov3TinyTrain/darknet-master/vcpkg_installed/x64-windows-release/lib/manual-link -nologo -W3 -utf-8 -MP -MD -O2 -Oi -Gy -Z7 `if test -n ':'; then : /C/Users/[my path]/Yolov3TinyTrain/darknet-master/vcpkg_installed/x64-windows-release/tools/libiconv/bin; fi` iconv.obj ../srclib/libicrt.a /C/Users/[my path]/Yolov3TinyTrain/darknet-master/vcpkg/packages/libiconv_x64-windows-release/C/Users/[my path]/Yolov3TinyTrain/darknet-master/vcpkg_installed/x64-windows-release/lib/libiconv.la  iconv.res -o iconv.exe;; \
esac
libtool: link: compile cl.exe -nologo -W3 -utf-8 -MP -MD -O2 -Oi -Gy -Z7 iconv.obj ../srclib/libicrt.a iconv.res -o .libs/iconv.exe  -LC:/Users/[my path]/Yolov3TinyTrain/darknet-master/vcpkg_installed/x64-windows-release/lib -LC:/Users/[my path]/Yolov3TinyTrain/darknet-master/vcpkg_installed/x64-windows-release/lib/manual-link /C/Users/[my path]/Yolov3TinyTrain/darknet-master/vcpkg/packages/libiconv_x64-windows-release/C/Users/[my path]/Yolov3TinyTrain/darknet-master/vcpkg_installed/x64-windows-release/lib/iconv.lib -L=C:/Users/[my path]/Yolov3TinyTrain/darknet-master/vcpkg_installed/x64-windows-release/lib -L=C:/Users/[my path]/Yolov3TinyTrain/darknet-master/vcpkg_installed/x64-windows-release/lib/manual-link  
cl : Command line warning D9002 : ignoring unknown option '//?/C:/Users/[my path]/Yolov3TinyTrain/darknet-master/vcpkg/packages/libiconv_x64-windows-release/C/Users/[my path]/Yolov3TinyTrain/darknet-master/vcpkg_installed/x64-windows-release/lib/iconv.lib'
cl : Command line warning D9002 : ignoring unknown option '//?/C:/Users/[my path]/Yolov3TinyTrain/darknet-master/vcpkg/packages/libiconv_x64-windows-release/C/Users/[my path]/Yolov3TinyTrain/darknet-master/vcpkg_installed/x64-windows-release/lib/iconv.lib'
cl : Command line warning D9002 : ignoring unknown option '//?/C:/Users/[my path]/Yolov3TinyTrain/darknet-master/vcpkg/packages/libiconv_x64-windows-release/C/Users/[my path]/Yolov3TinyTrain/darknet-master/vcpkg_installed/x64-windows-release/lib/iconv.lib'
cl : Command line warning D9024 : unrecognized source file type '../srclib/libicrt.a', object file assumed
cl : Command line warning D9024 : unrecognized source file type '../srclib/libicrt.a', object file assumed
cl : Command line warning D9024 : unrecognized source file type '../srclib/libicrt.a', object file assumed
   Creating library .libs\iconv.lib and object .libs\iconv.exp
LINK : warning LNK4217: symbol 'program_name' defined in 'libicrt.a(progname.obj)' is imported by 'iconv.obj' in function 'main'
iconv.obj : error LNK2019: unresolved external symbol libiconv_open referenced in function main
iconv.obj : error LNK2019: unresolved external symbol libiconv referenced in function convert
iconv.obj : error LNK2019: unresolved external symbol libiconv_close referenced in function main
iconv.obj : error LNK2019: unresolved external symbol libiconvctl referenced in function convert
iconv.obj : error LNK2019: unresolved external symbol libiconvlist referenced in function main
iconv.obj : error LNK2019: unresolved external symbol iconv_canonicalize referenced in function main
iconv.obj : error LNK2019: unresolved external symbol __imp__libiconv_version referenced in function print_version
.libs\iconv.exe : fatal error LNK1120: 7 unresolved externals

- the error.log content:

> libtool: warning: remember to run 'libtool --finish /C/Users/[my path]/Yolov3TinyTrain/darknet-master/vcpkg_installed/x64-windows-release/lib'
libtool: warning: remember to run 'libtool --finish /C/Users/[my path]/Yolov3TinyTrain/darknet-master/vcpkg_installed/x64-windows-release/lib'
libtool: warning: library '/C/Users/[my path]/Yolov3TinyTrain/darknet-master/vcpkg/packages/libiconv_x64-windows-release/C/Users/tsaiyenk/Documents/SnobBog/ML/TensorFlowTraining/Yolov3TinyTrain/darknet-master/vcpkg_installed/x64-windows-release/lib/libiconv.la' was moved.
libtool: warning: library '/C/Users/[my path]/Yolov3TinyTrain/darknet-master/vcpkg/packages/libiconv_x64-windows-release/C/Users/tsaiyenk/Documents/SnobBog/ML/TensorFlowTraining/Yolov3TinyTrain/darknet-master/vcpkg_installed/x64-windows-release/lib/libiconv.la' was moved.
cl : Command line warning D9002 : ignoring unknown option '//?/C:/Users/[my path]/Yolov3TinyTrain/darknet-master/vcpkg/packages/libiconv_x64-windows-release/C/Users/[my path]/Yolov3TinyTrain/darknet-master/vcpkg_installed/x64-windows-release/lib/iconv.lib'
cl : Command line warning D9024 : unrecognized source file type '../srclib/libicrt.a', object file assumed
make[1]: *** [Makefile:114: install] Error 2
make: *** [Makefile:54: install] Error 2

**Additional context**
I read through issue #15592 and my issue is the same as the second half of that thread. However, i didn't see a new issue open for that problem as suggested, so I open another issue for it. Any help will be appreciated.

**Comment by Cheney-W** [comment]
What's the file system of your C disk, ReFS or NTFS?

**Comment by Cheney-W** [comment]
Could you please provide me with your triplet file x64-windows-release and the build.ps1 file? Thank you!

**Comment by dg0yt** [comment]
Probably a path length issue, cf. https://github.com/microsoft/vcpkg/issues/25269#issuecomment-1158687687.

**Comment by Cheney-W** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
