### ISSUE TITLE
[librabbitmq] include path missing

### ISSUE THREAD

**Issue by anders-wind** [microsoft/vcpkg#23630]
****

**Is your feature request related to a problem? Please describe.**
When adding librabbitmq as a dependency the target does not set a `target_include_directories`. So while the header is located in the `build/vcpkg_installed/x64-linux/include/amqp.h` we still get a "cannot find the specified header" even after `find_package(rabbitmq-c CONFIG REQUIRED)` and adding `rabbitmq::rabbitmq-static` to `target_link_libraries`.

My temporary solution has been to add `"$<BUILD_INTERFACE:${PACKAGE_PREFIX_DIR}/include>"` to my own `target_include_directories` but it feels a bit hacky.

**Proposed solution**
Add a patch to the library which adds `target_include_directories` in a proper maner.

**Comment by FrankXie05** [comment]
@anders-wind Thanks for posting this issue, `vcpkg` is an open source community project,
we would like users to submit a pull request to solve the problem, if you have any problems during the solving process, you can ask me. Of course, if you don't have time I'll submit a pull request to fix this. What do you think? :)

**Comment by anders-wind** [comment]
Hi @FrankXie05, thanks for taking a look at my problem :) I'm going on vacation and have not had time to try your example.  Though I see that youre including `#include "rabbitmq-c.h"` and not `include <amqp.h>` It might be that the library never intended that file to be included, but we are relying on a third party project which does include it. 
I will try out your example when I get back :)

**Comment by FrankXie05** [comment]
@anders-wind I reproduced it，and I found that there is a way upstream to export the include definition file(https://github.com/alanxz/rabbitmq-c/blob/26ecf6d3012be81f5dfb8a2d822c722e916a86cb/librabbitmq/CMakeLists.txt#L72), but it doesn't link in the top-level CMakeLists.txt , it might be an upstream bug, you can submit an issue upstream to fix it. :)
