### ISSUE TITLE
[libpq] Build error

### ISSUE THREAD

**Issue by lufeng0709** [microsoft/vcpkg#23642]
**Host Environment**
- OS: Windows 10
- Compiler: 19044.1586

**To Reproduce**
.\vcpkg.exe install osgearth:x64-windows --recurse

**Failure logs** 

Error: Building package libpq:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libpq
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[libpq]+Build+error
including:
  package: libpq[core,openssl,zlib]:x64-windows -> 12.9#1
    vcpkg-tool version: 2022-03-09-1affd32f93b299d5a907816c328ca3ededb73a7e
    vcpkg-scripts version: 6f827f25f 2022-03-17 (27 hours ago)

Additionally, attach any relevant sections from the log files above.

**Additional context**
how to install osgearth by vcpkg

**Comment by BOBLAO2** [comment]
Could you solve this problem? I also meet this problem, but the package I installed is boost-disjoint-sets:x64-windows.

**Comment by lufeng0709** [comment]
your question is not same to me, my question need  install english langage packet
