### ISSUE TITLE
[poppler] build failure

### ISSUE THREAD

**Issue by beached** [microsoft/vcpkg#23646]
**Host Environment**
- OS: Ubuntu 21.04
- Compiler: gcc-10.3.0

**To Reproduce**
`./vcpkg install poppler --x-feature=cairo` I think, used manifest with cairo feature

**Failure logs** 
```
Imported target "unofficial::poppler::poppler-cpp" includes non-existent
  path

    "/tmp/project/cmake-build-debug-ubuntu21_04/vcpkg_installed/x64-linux/include/poppler/fofi"

  in its INTERFACE_INCLUDE_DIRECTORIES.
```

**Comment by dg0yt** [comment]
Thanks for reporting the issue. This seems to be one of the directories which is part of the "private API". 
I created a PR to fix and update poppler: #23651.
Until the exported config is fixed, install feature "private-api".

> `./vcpkg install poppler --x-feature=cairo`

The syntax is `./vcpkg install poppler[cairo,private-api]`.
