### ISSUE TITLE
[mpfr] Build error

### ISSUE THREAD

**Issue by bobluoluo** [microsoft/vcpkg#23641]
**Host Environment**
- OS: Ubuntu 18.04
- Compiler: gcc 7.5

**To Reproduce**
`./vcpkg install mpfr`

**Failure logs** 
Starting package 133/185: mpfr:x64-linux
Building package mpfr[core]:x64-linux...
-- Downloading http://www.mpfr.org/mpfr-4.1.0/mpfr-4.1.0.tar.xz -> mpfr-4.1.0.tar.xz...
-- Extracting source /root/dev/third-party/vcpkg/downloads/mpfr-4.1.0.tar.xz
-- Applying patch gmpd.patch
-- Applying patch dll.patch
-- Using source at /root/dev/third-party/vcpkg/buildtrees/mpfr/src/mpfr-4-8955d4bc66.clean
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Generating configure for x64-linux
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
    Command failed: /usr/bin/autoreconf -vfi
    Working Directory: /root/dev/third-party/vcpkg/buildtrees/mpfr/src/mpfr-4-8955d4bc66.clean/
    Error code: 1
    See logs for more information:
      /root/dev/third-party/vcpkg/buildtrees/mpfr/autoconf-x64-linux-out.log
      /root/dev/third-party/vcpkg/buildtrees/mpfr/autoconf-x64-linux-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:600 (vcpkg_execute_required_process)
  ports/mpfr/portfile.cmake:17 (vcpkg_configure_make)
  scripts/ports.cmake:142 (include)

Error: Building package mpfr:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: mpfr:x64-linux
  Vcpkg version: 2021-05-05-unknownhash

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by FrankXie05** [comment]
@bobluoluo Thanks for posting this issue, could you please provide the log: 
```
/root/dev/third-party/vcpkg/buildtrees/mpfr/autoconf-x64-linux-out.log
/root/dev/third-party/vcpkg/buildtrees/mpfr/autoconf-x64-linux-err.log
```
And you can run command and try again. :)
```
 sudo apt-get update -y
 sudo apt-get install -y autoconf-archive
```

**Comment by FrankXie05** [comment]
@bobluoluo Is still work for this issue?

**Comment by FrankXie05** [comment]
This issue hasn’t been updated for a long timer; if it is still an issue, please reopen this issue.
