### ISSUE TITLE
Packages not building using latest version of Visual Studio compiler

### ISSUE THREAD

**Issue by Steve-O-UK** [Microsoft/vcpkg#2365]
I upgraded to the latest version of VC studio community a few days ago and it appears this has broken something in vcpkg as nothing now builds.  As I deleted a number of packages to upgrade them I'm now stuck as I didn't think to back up my vcpkg binary folder.

Screenshot attached.  Please get in touch if more information would be useful.

![vcpkg_bug](https://user-images.githubusercontent.com/34509335/33937613-0d8b52d6-dffc-11e7-94e9-c53213b36a36.jpg)

**Comment by marcoesposito1988** [comment]
I have the same problem with a fresh install (VS2017 Community, vcpkg 621d9af)

**Comment by Steve-O-UK** [comment]
Update:  I reset my local branch to "Merge pull request #2356 from jasjuang/exiv2" 
SHA1 ID: bbb431c5a9f1548b6690067d05936053a86dc572 and rebuilt vcpkg and everything is working again.  Hope this helps.

**Comment by ras0219-msft** [comment]
Thanks for posting this issue! I've identified the offending commits and reverted them which should fix this crash.

**Comment by Steve-O-UK** [comment]
Confirmed.  I pulled / merged the latest changes and built a random package that wasn't building before and everything works correctly.  Thanks for the fast turn-around.
