### ISSUE TITLE
[opencv4] Build error

### ISSUE THREAD

**Issue by Sousuke13** [microsoft/vcpkg#23663]
**Host Environment**
- OS: Windows 11
- Microsoft Visual Studio Community 2022 (64 ビット) - Current Version 17.1.1

**To Reproduce**
`vcpkg.exe install opencv4[contrib]:x64-windows-static

**Failure logs** 
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:128 (message):
    Command failed: ninja -v
    Working Directory: D:/vcpkg/buildtrees/opencv4/x64-windows-static-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\vcpkg\buildtrees\opencv4\config-x64-windows-static-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:415 (vcpkg_execute_required_process)
  ports/opencv4/portfile.cmake:402 (vcpkg_cmake_configure)
  scripts/ports.cmake:145 (include)

Error: Building package opencv4:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+opencv4
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[opencv4]+Build+error
including:
  package: opencv4[contrib,core,default-features,dnn,jpeg,png,quirc,tiff,webp]:x64-windows-static -> 4.5.5
    vcpkg-tool version: 2022-03-09-1affd32f93b299d5a907816c328ca3ededb73a7e
    vcpkg-scripts version: a3df69692 2022-03-18 (35 hours ago)

-Please attach any additional failure logs mentioned in the console output.
[config-x64-windows-static-out.log](https://github.com/microsoft/vcpkg/files/8310915/config-x64-windows-static-out.log)

**Comment by dg0yt** [comment]
~~~
CMake Error at D:/vcpkg/installed/x64-windows-static/share/libarchive/vcpkg-cmake-wrapper.cmake:60 (set_property):
  Property INTERFACE_LINK_LIBRARIES may not contain link-type keyword
  "optimized".  The INTERFACE_LINK_LIBRARIES property may contain
  configuration-sensitive generator-expressions which may be used to specify
  per-configuration rules.
Call Stack (most recent call first):
  D:/vcpkg/scripts/buildsystems/vcpkg.cmake:759 (include)
  D:/vcpkg/installed/x64-windows-static/share/tesseract/TesseractConfig.cmake:26 (find_package)
  D:/vcpkg/scripts/buildsystems/vcpkg.cmake:805 (_find_package)
  D:/vcpkg/buildtrees/opencv4/src/4.5.5-c35cb8696d/modules/text/cmake/init.cmake:8 (find_package)
  cmake/OpenCVModule.cmake:298 (include)
  cmake/OpenCVModule.cmake:364 (_add_modules_1)
  cmake/OpenCVModule.cmake:385 (ocv_glob_modules)
  CMakeLists.txt:927 (ocv_register_modules)
~~~

There is a problem with the find module wrapper from port `libarchive`. I would say this is from its `lzo` dependency.
