### ISSUE TITLE
binutils-2.34-4-x86_64.pkg.tar.zst no longer in existing in repositories

### ISSUE THREAD

**Issue by lefteh** [microsoft/vcpkg#23677]
**Describe the bug**
vcpkg attempts to download binutils-2.34-4-x86_64.pkg.tar.zst, 2.3.4-4 is a old enough version that the hosting sites no longer support the file

**Environment**
- OS: Windows 10 (OS Build 19044.1586)
- Compiler: Vcpkg package management program version 2021-08-12-85ab112d5ee102bc6eac8cdbbfdd173a71374e04

**To Reproduce**
1. ./vcpkg install icu --triplet x64-windows
2. See error
>vcpkg install icu --triplet x64-windows
Computing installation plan...
The following packages will be built and installed:
    icu[core]:x64-windows -> 69.1#11
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\Luke\AppData\Local\vcpkg\archives\de\de54d4a4b01b207ba37da2bcad2e906989c769dcdeba2f9c67b9e7c6a19ef366.zip
Starting package 1/1: icu:x64-windows
Building package icu[core]:x64-windows...
-- Downloading https://github.com/unicode-org/icu/releases/download/release-69-1/icu4c-69_1-src.tgz -> icu4c-69_1-src.tgz...
-- Cleaning sources at C:/Users/Luke/source/repos/vcpkg/buildtrees/icu/src/c-69_1-src-78c1b28057.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/Luke/source/repos/vcpkg/downloads/icu4c-69_1-src.tgz
-- Applying patch C:/Users/Luke/source/repos/vcpkg/ports/icu/disable-escapestr-tool.patch
-- Applying patch C:/Users/Luke/source/repos/vcpkg/ports/icu/remove-MD-from-configure.patch
-- Applying patch C:/Users/Luke/source/repos/vcpkg/ports/icu/fix_parallel_build_on_windows.patch
-- Applying patch C:/Users/Luke/source/repos/vcpkg/ports/icu/fix-extra.patch
-- Using source at C:/Users/Luke/source/repos/vcpkg/buildtrees/icu/src/c-69_1-src-78c1b28057.clean
-- Found external ninja('1.10.2').
-- Getting CMake variables for x64-windows
-- Downloading https://repo.msys2.org/msys/x86_64/gzip-1.10-1-x86_64.pkg.tar.xz;https://www2.futureware.at/~nickoe/msys2-mirror/msys/x86_64/gzip-1.10-1-x86_64.pkg.tar.xz;https://mirror.yandex.ru/mirrors/msys2/msys/x86_64/gzip-1.10-1-x86_64.pkg.tar.xz;https://mirrors.tuna.tsinghua.edu.cn/msys2/msys/x86_64/gzip-1.10-1-x86_64.pkg.tar.xz;https://mirrors.ustc.edu.cn/msys2/msys/x86_64/gzip-1.10-1-x86_64.pkg.tar.xz;https://mirror.bit.edu.cn/msys2/msys/x86_64/gzip-1.10-1-x86_64.pkg.tar.xz;https://mirror.selfnet.de/msys2/msys/x86_64/gzip-1.10-1-x86_64.pkg.tar.xz;https://mirrors.sjtug.sjtu.edu.cn/msys2/msys/x86_64/gzip-1.10-1-x86_64.pkg.tar.xz -> msys-gzip-1.10-1-x86_64.pkg.tar.xz...
-- Downloading https://repo.msys2.org/msys/x86_64/bash-4.4.023-2-x86_64.pkg.tar.xz;https://www2.futureware.at/~nickoe/msys2-mirror/msys/x86_64/bash-4.4.023-2-x86_64.pkg.tar.xz;https://mirror.yandex.ru/mirrors/msys2/msys/x86_64/bash-4.4.023-2-x86_64.pkg.tar.xz;https://mirrors.tuna.tsinghua.edu.cn/msys2/msys/x86_64/bash-4.4.023-2-x86_64.pkg.tar.xz;https://mirrors.ustc.edu.cn/msys2/msys/x86_64/bash-4.4.023-2-x86_64.pkg.tar.xz;https://mirror.bit.edu.cn/msys2/msys/x86_64/bash-4.4.023-2-x86_64.pkg.tar.xz;https://mirror.selfnet.de/msys2/msys/x86_64/bash-4.4.023-2-x86_64.pkg.tar.xz;https://mirrors.sjtug.sjtu.edu.cn/msys2/msys/x86_64/bash-4.4.023-2-x86_64.pkg.tar.xz -> msys-bash-4.4.023-2-x86_64.pkg.tar.xz...
-- Downloading https://repo.msys2.org/msys/x86_64/autoconf-2.71-1-any.pkg.tar.zst;https://www2.futureware.at/~nickoe/msys2-mirror/msys/x86_64/autoconf-2.71-1-any.pkg.tar.zst;https://mirror.yandex.ru/mirrors/msys2/msys/x86_64/autoconf-2.71-1-any.pkg.tar.zst;https://mirrors.tuna.tsinghua.edu.cn/msys2/msys/x86_64/autoconf-2.71-1-any.pkg.tar.zst;https://mirrors.ustc.edu.cn/msys2/msys/x86_64/autoconf-2.71-1-any.pkg.tar.zst;https://mirror.bit.edu.cn/msys2/msys/x86_64/autoconf-2.71-1-any.pkg.tar.zst;https://mirror.selfnet.de/msys2/msys/x86_64/autoconf-2.71-1-any.pkg.tar.zst;https://mirrors.sjtug.sjtu.edu.cn/msys2/msys/x86_64/autoconf-2.71-1-any.pkg.tar.zst -> msys-autoconf-2.71-1-any.pkg.tar.zst...
-- Downloading https://repo.msys2.org/msys/x86_64/diffutils-3.7-1-x86_64.pkg.tar.xz;https://www2.futureware.at/~nickoe/msys2-mirror/msys/x86_64/diffutils-3.7-1-x86_64.pkg.tar.xz;https://mirror.yandex.ru/mirrors/msys2/msys/x86_64/diffutils-3.7-1-x86_64.pkg.tar.xz;https://mirrors.tuna.tsinghua.edu.cn/msys2/msys/x86_64/diffutils-3.7-1-x86_64.pkg.tar.xz;https://mirrors.ustc.edu.cn/msys2/msys/x86_64/diffutils-3.7-1-x86_64.pkg.tar.xz;https://mirror.bit.edu.cn/msys2/msys/x86_64/diffutils-3.7-1-x86_64.pkg.tar.xz;https://mirror.selfnet.de/msys2/msys/x86_64/diffutils-3.7-1-x86_64.pkg.tar.xz;https://mirrors.sjtug.sjtu.edu.cn/msys2/msys/x86_64/diffutils-3.7-1-x86_64.pkg.tar.xz -> msys-diffutils-3.7-1-x86_64.pkg.tar.xz...
-- Downloading https://repo.msys2.org/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst;https://www2.futureware.at/~nickoe/msys2-mirror/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst;https://mirror.yandex.ru/mirrors/msys2/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst;https://mirrors.tuna.tsinghua.edu.cn/msys2/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst;https://mirrors.ustc.edu.cn/msys2/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst;https://mirror.bit.edu.cn/msys2/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst;https://mirror.selfnet.de/msys2/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst;https://mirrors.sjtug.sjtu.edu.cn/msys2/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst -> msys-binutils-2.34-4-x86_64.pkg.tar.zst...
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' = off
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Downloading https://repo.msys2.org/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst
[DEBUG] Downloading https://www2.futureware.at/~nickoe/msys2-mirror/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst
[DEBUG] Downloading https://mirror.yandex.ru/mirrors/msys2/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst
[DEBUG] Downloading https://mirrors.tuna.tsinghua.edu.cn/msys2/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst
[DEBUG] Downloading https://mirrors.ustc.edu.cn/msys2/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst
[DEBUG] Downloading https://mirror.bit.edu.cn/msys2/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst
[DEBUG] Downloading https://mirror.selfnet.de/msys2/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst
[DEBUG] Downloading https://mirrors.sjtug.sjtu.edu.cn/msys2/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst
Error: Failed to download from mirror set:
https://repo.msys2.org/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst: failed: status code 404
https://www2.futureware.at/~nickoe/msys2-mirror/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst: failed: status code 404
https://mirror.yandex.ru/mirrors/msys2/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst: failed: status code 404
https://mirrors.tuna.tsinghua.edu.cn/msys2/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst: failed: status code 404
https://mirrors.ustc.edu.cn/msys2/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst: failed: status code 404
https://mirror.bit.edu.cn/msys2/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst: WinHttpSendRequest() failed: 12007
https://mirror.selfnet.de/msys2/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst: WinHttpSendRequest() failed: 12175
https://mirrors.sjtug.sjtu.edu.cn/msys2/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst: failed: status code 404

[DEBUG] C:\a\1\s\src\vcpkg\base\downloads.cpp(626)
[DEBUG] Exiting after 8341202 us (8336133 us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:83 (message):

      Failed to download file with error: 1
      If you use a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.

      3. You proxy's remote server is out of service.

      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)

      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:274 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_acquire_msys.cmake:84 (vcpkg_download_distfile)
  scripts/cmake/vcpkg_acquire_msys.cmake:123 (z_vcpkg_acquire_msys_download_package)
  scripts/cmake/vcpkg_acquire_msys.cmake:228 (z_vcpkg_acquire_msys_declare_package)
  scripts/cmake/vcpkg_configure_make.cmake:309 (vcpkg_acquire_msys)
  ports/icu/portfile.cmake:49 (vcpkg_configure_make)
  scripts/ports.cmake:140 (include)

Error: Building package icu:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: icu:x64-windows
  Vcpkg version: 2021-08-12-85ab112d5ee102bc6eac8cdbbfdd173a71374e04

Additionally, attach any relevant sections from the log files above.

**Expected behavior**
install

**Additional context**
current is [binutils-2.37-5-x86_64.pkg.tar.zst](https://repo.msys2.org/msys/x86_64/binutils-2.37-5-x86_64.pkg.tar.zst)                 19-Dec-2021 21:46

**Comment by JackBoosY** [comment]
I believe this was fixed in the master branch.
```
Vcpkg version: 2021-08-12-85ab112d5ee102bc6eac8cdbbfdd173a71374e04
```
Please update vcpkg and try again.

Thanks.

**Comment by Adela0814** [comment]
@lefteh ping for response

**Comment by Adela0814** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

**Comment by mostafanou7** [comment]
I got the same error.

**My log:**

> F:\rem\vcpkg>.\vcpkg.exe install cgal[qt]
Computing installation plan...
The following packages will be built and installed:
    cgal[core,qt]:x86-windows -> 5.3.1
  * double-conversion[core]:x86-windows -> 3.1.5#1
  * double-conversion[core]:x64-windows -> 3.1.5#1
  * egl-registry[core]:x86-windows -> 2021-11-23
  * egl-registry[core]:x64-windows -> 2021-11-23
  * freeglut[core]:x86-windows -> 3.2.1#7
  * freetype[brotli,bzip2,core,png,zlib]:x86-windows -> 2.11.1
  * freetype[brotli,bzip2,core,png,zlib]:x64-windows -> 2.11.1
  * harfbuzz[core]:x86-windows -> 3.2.0
  * harfbuzz[core]:x64-windows -> 3.2.0
  * icu[core]:x64-windows -> 69.1#18
  * icu[core]:x86-windows -> 69.1#18
  * jasper[core]:x86-windows -> 2.0.33#1
  * libjpeg-turbo[core]:x64-windows -> 2.1.2
  * libpng[core]:x64-windows -> 1.6.37#16
  * libwebp[core,nearlossless,simd,unicode]:x86-windows -> 1.2.1
  * mpfr[core]:x86-windows -> 4.1.0#2
  * opengl[core]:x86-windows -> 0.0#9
  * openssl[core]:x86-windows -> 1.1.1m#1
  * pcre2[core]:x86-windows -> 10.39#2
  * pcre2[core]:x64-windows -> 10.39#2
  * pkgconf[core]:x64-windows -> 1.8.0#1
  * qt5-3d[core]:x86-windows -> 5.15.2#3
  * qt5-activeqt[core]:x86-windows -> 5.15.2#1
  * qt5-base[core]:x64-windows -> 5.15.2#19
  * qt5-base[core]:x86-windows -> 5.15.2#19
  * qt5-declarative[core]:x86-windows -> 5.15.2#3
  * qt5-gamepad[core]:x86-windows -> 5.15.2#1
  * qt5-imageformats[core]:x86-windows -> 5.15.2#1
  * qt5-script[core]:x86-windows -> 5.15.2#1
  * qt5-svg[core]:x86-windows -> 5.15.2#2
  * qt5-tools[core]:x86-windows -> 5.15.2#1
  * qt5-xmlpatterns[core]:x86-windows -> 5.15.2#1
  * sqlite3[core]:x86-windows -> 3.37.1
  * sqlite3[core]:x64-windows -> 3.37.1
  * tiff[core,jpeg,lzma,zip]:x86-windows -> 4.3.0#5
  * vcpkg-pkgconfig-get-modules[core]:x64-windows -> 2022-01-10
  * vcpkg-tool-meson[core]:x64-windows -> 0.60.2#1
  * zstd[core]:x64-windows -> 1.5.2
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x86-windows...
Detecting compiler hash for triplet x64-windows...
Restored 0 packages from C:\Users\Mostafa\AppData\Local\vcpkg\archives in 1.259 ms. Use --debug to see more details.
Installing 1/39 mpfr:x86-windows...
Building mpfr[core]:x86-windows...
-- Using cached mpfr-4.1.0.tar.xz.
-- Cleaning sources at F:/source/repos/vcpkg/buildtrees/mpfr/src/mpfr-4-8955d4bc66.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source F:/source/repos/vcpkg/downloads/mpfr-4.1.0.tar.xz
-- Applying patch gmpd.patch
-- Applying patch dll.patch
-- Using source at F:/source/repos/vcpkg/buildtrees/mpfr/src/mpfr-4-8955d4bc66.clean
-- Found external ninja('1.10.2').
-- Getting CMake variables for x86-windows
-- Using cached msys-gzip-1.10-1-x86_64.pkg.tar.xz.
-- Using cached msys-texinfo-6.7-3-x86_64.pkg.tar.zst.
-- Using cached msys-bash-4.4.023-2-x86_64.pkg.tar.xz.
-- Using cached msys-autoconf-2.71-1-any.pkg.tar.zst.
-- Using cached msys-autoconf-archive-2019.01.06-1-any.pkg.tar.xz.
-- Using cached msys-diffutils-3.7-1-x86_64.pkg.tar.xz.
-- Downloading https://repo.msys2.org/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst;https://www2.futureware.at/~nickoe/msys2-mirror/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst;https://mirror.yandex.ru/mirrors/msys2/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst;https://mirrors.tuna.tsinghua.edu.cn/msys2/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst;https://mirrors.ustc.edu.cn/msys2/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst;https://mirror.bit.edu.cn/msys2/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst;https://mirror.selfnet.de/msys2/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst;https://mirrors.sjtug.sjtu.edu.cn/msys2/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst -> msys-binutils-2.34-4-x86_64.pkg.tar.zst...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' = off
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Downloading https://repo.msys2.org/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst
[DEBUG] Downloading https://www2.futureware.at/~nickoe/msys2-mirror/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst
[DEBUG] Downloading https://mirror.yandex.ru/mirrors/msys2/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst
[DEBUG] Downloading https://mirrors.tuna.tsinghua.edu.cn/msys2/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst
[DEBUG] Downloading https://mirrors.ustc.edu.cn/msys2/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst
[DEBUG] Downloading https://mirror.bit.edu.cn/msys2/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst
[DEBUG] Download failed -- retrying after 1000 ms.
[DEBUG] Download failed -- retrying after 2000 ms.
[DEBUG] Download failed -- retrying after 4000 ms.
[DEBUG] Downloading https://mirror.selfnet.de/msys2/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst
[DEBUG] Download failed -- retrying after 1000 ms.
[DEBUG] Download failed -- retrying after 2000 ms.
[DEBUG] Download failed -- retrying after 4000 ms.
[DEBUG] Downloading https://mirrors.sjtug.sjtu.edu.cn/msys2/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst
Error: Failed to download from mirror set:
https://repo.msys2.org/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst: failed: status code 404
https://www2.futureware.at/~nickoe/msys2-mirror/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst: failed: status code 404
https://mirror.yandex.ru/mirrors/msys2/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst: failed: status code 404
https://mirrors.tuna.tsinghua.edu.cn/msys2/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst: failed: status code 404
https://mirrors.ustc.edu.cn/msys2/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst: failed: status code 404
https://mirror.bit.edu.cn/msys2/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst: WinHttpSendRequest() failed: 12007
https://mirror.bit.edu.cn/msys2/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst: WinHttpSendRequest() failed: 12007
https://mirror.bit.edu.cn/msys2/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst: WinHttpSendRequest() failed: 12007
https://mirror.bit.edu.cn/msys2/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst: WinHttpSendRequest() failed: 12007
https://mirror.selfnet.de/msys2/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst: WinHttpSendRequest() failed: 12175
https://mirror.selfnet.de/msys2/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst: WinHttpSendRequest() failed: 12175
https://mirror.selfnet.de/msys2/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst: WinHttpSendRequest() failed: 12175
https://mirror.selfnet.de/msys2/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst: WinHttpSendRequest() failed: 12175
https://mirrors.sjtug.sjtu.edu.cn/msys2/msys/x86_64/binutils-2.34-4-x86_64.pkg.tar.zst: failed: status code 404

[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(751):
[DEBUG] Time in subprocesses: 0 us
[DEBUG] Time in parsing JSON: 5 us
[DEBUG] Time in JSON reader: 0 us
[DEBUG] Time in filesystem: 7784 us
[DEBUG] Time in loading ports: 0 us
[DEBUG] Exiting after 22.97 s (22936078 us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:84 (message):

      Failed to download file with error: 1
      If you use a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.

      3. You proxy's remote server is out of service.

      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)

      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:309 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_acquire_msys.cmake:84 (vcpkg_download_distfile)
  scripts/cmake/vcpkg_acquire_msys.cmake:123 (z_vcpkg_acquire_msys_download_package)
  scripts/cmake/vcpkg_acquire_msys.cmake:228 (z_vcpkg_acquire_msys_declare_package)
  scripts/cmake/vcpkg_configure_make.cmake:307 (vcpkg_acquire_msys)
  ports/mpfr/portfile.cmake:21 (vcpkg_configure_make)
  scripts/ports.cmake:145 (include)


error: building mpfr:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+mpfr
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[mpfr]+Build+error
Include '[mpfr] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-05-05-67e17c1782801cf481be9ac0b3765dff3e4bdeb8
    vcpkg-scripts version: d8d61c941 2022-02-02 (4 months ago)

**Comment by mostafanou7** [comment]
@Adela0814 Please consider reopening this.

**Comment by sfhacker** [comment]
I believe the latest binutils version is 2.38. Any particular reason you need to install 2.34?

**Comment by mostafanou7** [comment]
I'm just installing CGAL using this [manual ](https://doc.cgal.org/latest/Manual/windows.html).

> C:\dev\vcpkg> ./vcpkg.exe install cgal[qt]

**Comment by mostafanou7** [comment]
Turned out to be my fault. I found another old vcpkg repo installed on my machine. Removed it and all good.
Sorry for bothering you.
