### ISSUE TITLE
[arb] Arb package cannot be used to build programs

### ISSUE THREAD

**Issue by kaba2** [microsoft/vcpkg#23699]
**Describe the bug**
The `arb` package cannot be used to build programs because linking fails.

**Environment**
- OS: Windows 10
- Compiler: Visual Studio 17.0.1 2022

**To Reproduce**

`main.cpp`:

```cpp
#include <malloc.h>
#include <arb.h>

int main()
{
    flint_printf("Computed with arb-%s\n", arb_version);
}
```

`vcpkg.json`:

```json
{
  "name": "testarb",
  "version-string": "0.1.0",
  "dependencies": [
    "arb"
  ]
}
```

`CMakeLists.txt`:

```cmake
cmake_minimum_required(VERSION 3.15)

project(testarb CXX)

include_directories("./vcpkg/packages/arb_x64-windows/include")
include_directories("./vcpkg/packages/flint_x64-windows/include")
include_directories("./vcpkg/packages/gmp_x64-windows/include")
include_directories("./vcpkg/packages/mpfr_x64-windows/include")
include_directories("./vcpkg/packages/pthreads_x64-windows/include")

link_directories("./vcpkg/packages/arb_x64-windows/lib")
link_directories("./vcpkg/packages/flint_x64-windows/lib")
link_directories("./vcpkg/packages/gmp_x64-windows/lib")
link_directories("./vcpkg/packages/mpfr_x64-windows/lib")
link_directories("./vcpkg/packages/pthreads_x64-windows/lib")

add_executable(testarb main.cpp)
target_compile_features(testarb PRIVATE cxx_std_20)

target_link_libraries(testarb PRIVATE gmp flint mpfr arb)
```

Command line:

```
git clone https://github.com/Microsoft/vcpkg.git
.\vcpkg\bootstrap-vcpkg.bat
cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake
cmake --build build --config Release
```

Output:

```
main.obj : error LNK2019: unresolved external symbol __imp_arb_version referenced in function main [C:\work\testarb\bui
ld\testarb.vcxproj]
```

**Expected behavior**
Should link.

**Comment by dg0yt** [comment]
> ```cmake
> include_directories("./vcpkg/packages/pthreads_x64-windows/include")
> 
> link_directories("./vcpkg/packages/arb_x64-windows/lib")
> ```

This is not the right approach. The `packages` dir is an implementation detail, not to be accessed directly. 
The CMake toolchain from vcpkg will set a proper prefix path so that `find_path`, `find_library` etc. will find the paths and  files from `installed/<target triplet>`. This gives the input to `target_include_directories` and `target_link_libraries`.

**Comment by kaba2** [comment]
Agreed. With say, Boost, I can do `find_package(Boost REQUIRED)`. But with the above libraries that approach does not seem to be available. The above hack was the only way I knew after `find_package` was off the table. I'd appreciate if someone can show a better approach.

**Comment by dg0yt** [comment]
Well, if neither CMake nor upstream provide package helpers, then there is just plain `find_path` +  `find_library`. This is what the find modules do.

It there are .pc files in `lib/pkg-config`, you could also try to use CMake's PkgConfig module, but you will need the `pkgconf` or `pkg-config` program.

Example for another port:
https://github.com/microsoft/vcpkg/blob/master/ports/libdatrie/usage

**Comment by kaba2** [comment]
Thanks. Here is perhaps a better CMake file. 

```cmake
cmake_minimum_required(VERSION 3.15)

project(testarb CXX)

find_path(ARB_INCLUDE_DIR arb.h)
find_library(ARB_LIBRARY NAMES arb)

find_path(FLINT_INCLUDE_DIR flint/flint.h)
find_library(FLINT_LIBRARY NAMES flint)

find_path(GMP_INCLUDE_DIR gmp.h)
find_library(GMP_LIBRARY NAMES gmp)

find_path(MPFR_INCLUDE_DIR mpfr.h)
find_library(MPFR_LIBRARY NAMES mpfr)

find_path(PTHREADS_INCLUDE_DIR pthread.h)
find_library(PTHREADS_LIBRARY NAMES pthreadVC3)

add_executable(testarb main.cpp)
target_compile_features(testarb PRIVATE cxx_std_20)

target_include_directories(testarb PRIVATE 
    "${ARB_INCLUDE_DIR}" 
    "${FLINT_INCLUDE_DIR}"
    "${GMP_INCLUDE_DIR}"
    "${MPFR_INCLUDE_DIR}"
    "${PTHREADS_INCLUDE_DIR}"
)

target_link_libraries(testarb PRIVATE 
    "${ARB_LIBRARY}"
    "${FLINT_LIBRARY}"
    "${GMP_LIBRARY}"
    "${MPFR_LIBRARY}"
    "${PTHREADS_LIBRARY}"
)

message(STATUS "Include directories:")
message(STATUS "${ARB_INCLUDE_DIR}")
message(STATUS "${FLINT_INCLUDE_DIR}")
message(STATUS "${GMP_INCLUDE_DIR}")
message(STATUS "${MPFR_INCLUDE_DIR}")
message(STATUS "${PTHREADS_INCLUDE_DIR}")

message(STATUS "Libraries:")
message(STATUS "${ARB_LIBRARY}")
message(STATUS "${FLINT_LIBRARY}")
message(STATUS "${GMP_LIBRARY}")
message(STATUS "${MPFR_LIBRARY}")
message(STATUS "${PTHREADS_LIBRARY}")
```

The original issue still remains: `arb` won't link.

```
error LNK2019: unresolved external symbol __imp_arb_version referenced in function main [C:\code\testarb\bui
ld\testarb.vcxproj]
```

**Comment by kaba2** [comment]
@Adela0814 The added category is incorrect. This is supposed to be a bug report.

**Comment by dg0yt** [comment]
> The original issue still remains: `arb` won't link.
> 
> ```
> error LNK2019: unresolved external symbol __imp_arb_version referenced in function main [C:\code\testarb\bui
> ld\testarb.vcxproj]
> ```

Hm, port `arb` supports only static linkage, regardless of triplet. IIUC there shouldn't be an `__imp_` prefix on symbol names from the `arb` headers. There seem to be a `declspec` issue in the installed headers.

**Comment by kaba2** [comment]
As @dg0yt, I was wondering too where the `__imp_` prefixes are coming from. I found this discussion:

https://stackoverflow.com/questions/11236789/what-is-the-difference-between-imp-and-imp

Quoting the answer by Hans Passant:

> The imp_ prefix is auto-generated by the compiler, it exports a function pointer that allows optimizing binding to DLL exports. By language rules, the imp_ is prefixed by a leading underscore, required since it lives in the global namespace and is generated by the implementation and doesn't otherwise appear in the source code. So you get `_imp_`.

And further below:

> You then fixed it with extern "C", now you got the single added underscore for cdecl, turning `_imp_` into `__imp_`.

A working theory then: vcpkg may be confusing a dll-build with a static build.

**Comment by JackBoosY** [comment]
@kaba2 It's from `FINT_DLL`.
