### ISSUE TITLE
[CI] Green CI although host failure is observered. 

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#23692]
https://dev.azure.com/vcpkg/public/_build/results?buildId=69159&view=logs&jobId=84da4f4a-968a-5b5c-16e9-f444c845396d

arm64-windows shows green although the host dependency failed and the target port is not marked as a skipped or cascaded.

**Comment by dg0yt** [comment]
#21905 sub-item 3.

**Comment by JackBoosY** [comment]
Please track #21905 instead.
