### ISSUE TITLE
[openssl] respect build configuration when building for unix

### ISSUE THREAD

**Issue by fealebenpae** [microsoft/vcpkg#23700]
****

**Is your feature request related to a problem? Please describe.**
The port ignores custom flags specified in `CMAKE_C_FLAGS_DEBUG` and `CMAKE_C_FLAGS_RELEASE`.

**Proposed solution**
Teach `ports/openssl/unix/CMakeLists.txt` to pass the contents of `CMAKE_C_FLAGS_$CONFIG` to `Configure`:
```cmake
string(TOUPPER "${CMAKE_BUILD_TYPE}" BUILD_TYPE)
set(CFLAGS "${CFLAGS} ${CMAKE_C_FLAGS_${BUILD_TYPE}}")
```

**Describe alternatives you've considered**
Leave things as they are, and use Configure's defaults. However, I believe not passing configuration-dependent cflags is a bug of the port.

**Additional context**
I'll be happy to submit a pull request myself if the proposed change is acceptable.

**Comment by FrankXie05** [comment]
@fealebenpae Thanks for posting this issue, It is true that not passing the correct parameters can cause a port bug. We are very happy for users to submit a pull request to solve the problems. :)
