### ISSUE TITLE
[python] Building older python

### ISSUE THREAD

**Issue by ghlecl** [microsoft/vcpkg#23702]
Hello.

This is more of a question/request for help/new feature then I bug report.  Sorry if this is not the right forum for that.

I am stuck at work working on a software system for which we do not control the python version.  The system needs FDA approval and upgrades slowly.  It is currently on python 3.6.  The system runs on Windows >7 (but I develop on macOS).

The system allows users to provide python scripts to automate some tedious work.  I would like to build python modules using pybind11.  Initially, I installed an older python version on my system, created a virtual environment, installed pybind11 via pip and then used CMake trickery to try and make things work.  It did.

Then, I thought maybe vcpkg would work for me.  So I tried to install pybind11 via vcpkg.  It works great, is more reproducible and so I would really like to use it, except that the python port only supports more recent versions of python than 3.6 (I think it's 3.8 and above from my readings, but can't be 100% certain).

I have tried making an overlay port, which I could live with.  To that end, I have cloned the cpython git repo, and using the current vcpkg python3 port as a model, made patches and adjusted the git tag and the got the sha512 hash to check the download.  Unfortunately, it will not work.

Would it be possible to "backport" the python3 port to support versions as low as 3.6 ?  If not, does anyone have any suggestions for me to make the overlay work ?

In any case, thanks.

**Comment by ghlecl** [comment]
Just in case, here is my attempt.
[https://github.com/ghlecl/py3_vcpkg_overlay](https://github.com/ghlecl/py3_vcpkg_overlay)

**Comment by JackBoosY** [comment]
Sorry but vcpkg only guarantees the stability and robustness of the current version of the port, you can continue to use the overlay-port feature.

Thanks.

**Comment by JackBoosY** [comment]
> Do you know of any community supported overlays site?

No we don't support this yet.
