### ISSUE TITLE
Visual Studio 2022 Cannot Find Installed Library

### ISSUE THREAD

**Issue by rohanreact** [microsoft/vcpkg#23718]
I am using Windows 10 21H2. I installed the `magnum` package using `vcpkg install magnum`. I then ran `vcpkg integrate install`. Both commands completed successfully.

However, Visual Studio 2022 gave an error when trying to include the library. It gave an option to use vcpkg, but doing so just opened the vcpkg website.

![image](https://user-images.githubusercontent.com/82231446/159468846-4984a472-25d8-4b6d-adcd-f507f74195bd.png)

**Comment by Cheney-W** [comment]
Does this issue only occur under x86? 
If you install magnum:x64-windows, then set the project's config to x64, and then include the header file, does this issue still exist?

**Comment by Cheney-W** [comment]
I could reproduce this issue with VS2022, but only one time. This issue has the following characteristics:
1. It only occurs with x86. 
2. Despite the intellisense prompt that no header files were found, I was able to build project successfully.
3. After build the project and restart Visual Studio, this issue disappeared. Intellisense can correctly identify header files and can also assist with input.
4. After the issue disappears, no matter recloning vcpkg, upgrading or repairing VS, the issue cannot be reproduced again.

**Comment by rohanreact** [comment]
Installing magnum:x64-windows solved the problem. The project now builds successfully.

**Comment by Cheney-W** [comment]
Did you encounter this issue before because you included the header file of magnum:x86-windows in a project whose config is x64?
