### ISSUE TITLE
[python3] Build error

### ISSUE THREAD

**Issue by Aisiok** [microsoft/vcpkg#23713]
Starting package 144/166: python3:x64-windows
Building package python3[core]:x64-windows...
-- Downloading https://github.com/python/cpython/archive/v3.10.2.tar.gz -> python-cpython-v3.10.2.tar.gz...
-- Extracting source D:/vcpkg/downloads/python-cpython-v3.10.2.tar.gz
-- Applying patch 0002-use-vcpkg-zlib.patch
-- Applying patch 0003-devendor-external-dependencies.patch
-- Applying patch 0004-dont-copy-vcruntime.patch
-- Applying patch 0005-only-build-required-projects.patch
-- Applying patch 0009-python.pc.patch
-- Applying patch 0010-bz2d.patch
-- Using source at D:/vcpkg/buildtrees/python3/src/v3.10.2-a8de38632e.clean
-- Building PCbuild/pcbuild.proj for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:128 (message):
    Command failed: msbuild D:/vcpkg/buildtrees/python3/x64-windows-rel/v3.10.2-a8de38632e.clean/PCbuild/pcbuild.proj /p:Configuration=Release /p:IncludeExtensions=true /p:IncludeExternals=true /p:IncludeCTypes=true /p:IncludeSSL=true /p:IncludeTkinter=false /p:IncludeTests=false /p:ForceImportBeforeCppTargets=D:/vcpkg/buildtrees/python3/src/v3.10.2-a8de38632e.clean/PCbuild/python_vcpkg.props /p:IncludeUwp=false /p:_VcpkgPythonLinkage=DynamicLibrary /t:Rebuild /p:Platform=x64 /p:PlatformToolset=v143 /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /p:WindowsTargetPlatformVersion=10.0.19041.0 /p:VcpkgTriplet=x64-windows /p:VcpkgInstalledDir=D:/vcpkg/installed /p:VcpkgManifestInstall=false /p:UseMultiToolTask=true /p:MultiProcMaxCount=17 /p:EnforceProcessCountAcrossBuilds=true /m:17
    Working Directory: D:/vcpkg/buildtrees/python3/x64-windows-rel/v3.10.2-a8de38632e.clean
    Error code: 1
    See logs for more information:
      D:\vcpkg\buildtrees\python3\build-x64-windows-rel-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_msbuild.cmake:172 (vcpkg_execute_required_process)
  ports/python3/portfile.cmake:140 (vcpkg_install_msbuild)
  scripts/ports.cmake:145 (include)

Error: Building package python3:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+python3
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[python3]+Build+error
including:
  package: python3[core]:x64-windows -> 3.10.2#1
    vcpkg-tool version: 2022-03-09-1affd32f93b299d5a907816c328ca3ededb73a7e
    vcpkg-scripts version: 6b6a35335 2022-03-21 (7 hours ago)

Additionally, attach any relevant sections from the log files above.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Could you please provide the error log file: **D:\vcpkg\buildtrees\python3\build-x64-windows-rel-out.log**?

**Comment by filak** [comment]
I get the same error. I do not see anything suspicious in build-x64-windows-rel-out.log - just few warnings.

But in build-x64-windows-dbg-out.log I see:

```
       "C:\...\vcpkg\buildtrees\python3\x86-windows-dbg\v3.10.2-a8de38632e.clean\PCbuild\pcbuild.proj" (Rebuild target) (1) ->
       "C:\...\vcpkg\buildtrees\python3\x86-windows-dbg\v3.10.2-a8de38632e.clean\PCbuild\pythoncore.vcxproj" (Build target) (3:25) ->
       (Link target) -> 
         LINK : fatal error LNK1104: cannot open file 'LZMA_DEBUG-NOTFOUND.obj' [C:\...\vcpkg\buildtrees\python3\x86-windows-dbg\v3.10.2-a8de38632e.clean\PCbuild\pythoncore.vcxproj]

    3 Warning(s)
    1 Error(s)
```

**Comment by dg0yt** [comment]
@filak Your installed liblzma might be outdated. Please try to remove it first.

**Comment by filak** [comment]
OK, that helped! I have encountered the python3 error when installing Boost libraries - maybe that is how the outdated liblzma had been installed.

**Comment by LilyWangLL** [comment]
Ping @Aisiok for response.

**Comment by Aisiok** [comment]
> Ping @Aisiok for response.

Thanks. 
I solved the problem. 
I found that it was the problem with VS2022 setting sdkroots in the registry.
