### ISSUE TITLE
[chartdir] update download link

### ISSUE THREAD

**Issue by cd-pkwan** [microsoft/vcpkg#23721]
We are the developer of the ChartDirector software. Recently, we find out ChartDirector is available through vckpg as the package "chartdir". The package downloads the ChartDirector from our web site at https://www.advsofteng.com/chartdir_cpp_win.zip. This link is a generic link that always points to the latest update of ChartDirector. The file content can change over time and this will break the hash checksum in the chartdir port. 

To make the port more stable, we have created a new link https://www.advsofteng.com/vckpg/chartdir_cpp_win_7.0.0.zip that we promise will never change. This will keep the port stable. Would you mind to update the download link in the port to use this is new URL?

Also, can we manage the chartdir port ourselves in vcpkg (we are already managing nuget packages for our .NET release), or must be always go through you?  

Regards
Peter Kwan

**Comment by mathisloge** [comment]
@cd-pkwan the general workflow is to create a PR for the `chartdir` port and if everything is okay, it will get merged/reviewed from the vcpkg team. 
You can set you as a maintainer in the vcpkg.json of the port, https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/manifest-files.md#maintainers

**Comment by JonLiu1993** [comment]
@cd-pkwan ,Thanks for posting this issue, I can update new link to this port, but I find the new link can't open, we welcome you manage the chartdir port in vcpkg by commit pr for the chartdir

**Comment by cd-pkwan** [comment]
Sorry, there is a typo mistake in the link. The link should be "https://www.advsofteng.com/vcpkg/chartdir_cpp_win_7.0.0.zip". I have just edited the file myself and commit a pull request.
