### ISSUE TITLE
gtestd.lib refers to gtest.dll, not gtestd.dll

### ISSUE THREAD

**Issue by nishiken** [Microsoft/vcpkg#2373]
This is about gtest:x64-windows.

debug/lib/manual-link/gtestd.lib seems to refer gtest.dll, not gtestd.dll.
There is gtestd.dll at debug/bin/gtestd.dll.

\# dumpbin /ALL .\gtestd.lib | Select-String DLL

**Comment by whsimic** [comment]
I have the same doubt, the suffix 'd' should be in the name? or the correspond dll file is not right?

**Comment by nishiken** [comment]
it seems that debug/bin/gtestd.dll becomes debug/bin/gtest.dll.
I think it is not best for cmake (difficulty in ADD_TESTS(ENVIRONMENT)).
But the issue should be closed.

**Comment by yurybura** [comment]
Very simple solution for this issue - use CMAKE_DEBUG_POSTFIX=d:

`
vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA
    OPTIONS 
        -DBUILD_GMOCK=ON
        -DBUILD_GTEST=ON
        -DCMAKE_DEBUG_POSTFIX=d
        -Dgtest_force_shared_crt=${GTEST_FORCE_SHARED_CRT}
)
'
