### ISSUE TITLE
[fontconfig] Avoid installing Symlinks

### ISSUE THREAD

**Issue by SchaichAlonso** [microsoft/vcpkg#23735]
**Avoid installing Symlinks**

**Is your feature request related to a problem? Please describe.**
The fontconfig port installs a number of symlinks into `etc/fonts/` below the installation prefix. These files are, at least on linux, always processed, even if the configuration is overloaded by defining a custom configuration with the `FONTCONFIG_FILE` and/or `FONTCONFIG_PATH` variables.

Depending on security policies, windows based systems can disallow symlinks.
* Assuming the windows system can generate symlinks, using `vcpkg export --zip`  will create corrupted zip files, as the zip format cannot handle symlinks.
* Assuming the windows system cannot generate symlinks, an installation will be created that lacks  most content of the `etc` subpath. However, this installation, exports, and binarysource, cannot be distinguished by metadata from an installation/export/binarysource that does contain files in `etc`.

**Proposed solution**
Patch the port to Install regular files instead of symlinks. On linux and unix, where symlinks can be considered to be supported in any sane setup, avoiding the installation of symlinks fixes the zip-file export, while on windows the package becomes independend of symlink enabling/restricting security policies on top of getting the zip export fixed.

**Describe alternatives you've considered**
Not using caches/exports avoids the issue, but different security configurations still result in different installations, which is counter-intuitive

**Additional context**

**Comment by JackBoosY** [comment]
Thanks for reporting and fixing this!
