### ISSUE TITLE
How do I pass multiple VCPKG_CMAKE_CONFIGURE_OPTIONS?

### ISSUE THREAD

**Issue by Leonard-The-Wise** [microsoft/vcpkg#23741]
I need multiple config vars for my tripled. Tried:

`set(VCPKG_CMAKE_CONFIGURE_OPTIONS "-DwxUSE_SOCKETS=0 wxUSE_IPV6=0 wxUSE_ALL_THEMES=1 wxUSE_WINSOCK2=0")`

Also
```
set(VCPKG_CMAKE_CONFIGURE_OPTIONS "-DwxUSE_SOCKETS=0 \
wxUSE_IPV6=0 \
wxUSE_ALL_THEMES=1 \
wxUSE_WINSOCK2=0")
```
Also...

```
set(VCPKG_CMAKE_CONFIGURE_OPTIONS "-DwxUSE_SOCKETS=0")
set(VCPKG_CMAKE_CONFIGURE_OPTIONS "-DwxUSE_IPV6=0")
set(VCPKG_CMAKE_CONFIGURE_OPTIONS "-DwxUSE_ALL_THEMES=1")
set(VCPKG_CMAKE_CONFIGURE_OPTIONS "-DwxUSE_WINSOCK2=0")
```

Also

`set(VCPKG_CMAKE_CONFIGURE_OPTIONS "-DwxUSE_SOCKETS=0 -DwxUSE_IPV6=0 -DwxUSE_ALL_THEMES=1 -DwxUSE_WINSOCK2=0")`

Also
```
set(VCPKG_CMAKE_CONFIGURE_OPTIONS "-DwxUSE_SOCKETS=0 \
-DwxUSE_IPV6=0 \
-DwxUSE_ALL_THEMES=1 \
-DwxUSE_WINSOCK2=0")
```

To NO avail.

Thanks.

**Comment by dg0yt** [comment]
It is a CMake list, not a string. Either use
~~~cmake
set(VCPKG_CMAKE_CONFIGURE_OPTIONS "-DwxUSE_SOCKETS=0" "-DwxUSE_IPV6=0")
~~~
or
~~~cmake
set(VCPKG_CMAKE_CONFIGURE_OPTIONS "-DwxUSE_SOCKETS=0;-DwxUSE_IPV6=0")
~~~

https://cmake.org/cmake/help/latest/manual/cmake-language.7.html#lists

**Comment by Leonard-The-Wise** [comment]
Thanks, that solved (although separating arguments with `;` will get vcpkg complaining a lot to you that `this isn't a standard separator`, etc. Hence I am using space-separations now.
