### ISSUE TITLE
[New Port Request] astcenc

### ISSUE THREAD

**Issue by ylz-at** [microsoft/vcpkg#23744]
Library name: astc-encoder

Library description: This is the official repository for the Arm® Adaptive Scalable Texture Compression (ASTC) Encoder, astcenc, a command-line tool for compressing and decompressing images using the ASTC texture compression standard.

Source repository URL: https://github.com/ARM-software/astc-encoder

Project homepage (if different from the source repository): https://developer.arm.com/documentation/102162/0002/?lang=en

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
astcenc is a cli tool, but actcenc.h can be used as lib.

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
