### ISSUE TITLE
CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS fails when building for Arm64 Windows Desktop target

### ISSUE THREAD

**Issue by 4creators** [Microsoft/vcpkg#2375]
This issue tracks bug in CMake which prevents from using CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS feature when building for Arm64 Windows target. The relevant issue in CMake repo is https://gitlab.kitware.com/cmake/cmake/issues/17564

**Comment by 4creators** [comment]
PR by me with fix to CMake landed couple of days ago in CMake repo: https://gitlab.kitware.com/cmake/cmake/merge_requests/1603

According to repo labels it will ship with v3.11.

**Comment by ras0219-msft** [comment]
Should be resolved by 1410851. Thanks!
