### ISSUE TITLE
[tbb] build failure

### ISSUE THREAD

**Issue by xzhao99** [microsoft/vcpkg#23759]
**Host Environment**
- OS: [Windows.]
- Compiler: MSBuild v143

**To Reproduce**
`./vcpkg install tbb:x64-windows`

**Failure logs**
PS D:\workdir\vcpkg> .\vcpkg.exe install tbb:x64-windows
Computing installation plan...
The following packages will be built and installed:
    tbb[core]:x64-windows -> 2020_U3#8
Detecting compiler hash for triplet x64-windows...
Restored 0 packages from C:\Users\xzhao\AppData\Local\vcpkg\archives in 134.8 us. Use --debug to see more details.
Starting package 1/1: tbb:x64-windows
Building package tbb[core]:x64-windows...
-- Using cached oneapi-src-oneTBB-eca91f16d7490a8abfdee652dadf457ec820cc37.tar.gz.
-- Cleaning sources at D:/workdir/vcpkg/buildtrees/tbb/src/7ec820cc37-30e75ff0be.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/workdir/vcpkg/downloads/oneapi-src-oneTBB-eca91f16d7490a8abfdee652dadf457ec820cc37.tar.gz
-- Applying patch fix-static-build.patch
-- Applying patch terminate-when-buildtool-notfound.patch
-- Using source at D:/workdir/vcpkg/buildtrees/tbb/src/7ec820cc37-30e75ff0be.clean
-- Building build/vs2013/makefile.sln for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:128 (message):
    Command failed: msbuild D:/workdir/vcpkg/buildtrees/tbb/x64-windows-rel/7ec820cc37-30e75ff0be.clean/build/vs2013/makefile.sln /p:Configuration=Release /t:Rebuild /p:Platform=x64 /p:PlatformToolset=v143 /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /p:WindowsTargetPlatformVersion=10.0.19041.0 /p:VcpkgTriplet=x64-windows /p:VcpkgInstalledDir=D:/workdir/vcpkg/installed /p:VcpkgManifestInstall=false /p:UseMultiToolTask=true /p:MultiProcMaxCount=17 /p:EnforceProcessCountAcrossBuilds=true /m:17
    Working Directory: D:/workdir/vcpkg/buildtrees/tbb/x64-windows-rel/7ec820cc37-30e75ff0be.clean
    Error code: 1
    See logs for more information:
      D:\workdir\vcpkg\buildtrees\tbb\build-x64-windows-rel-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_msbuild.cmake:172 (vcpkg_execute_required_process)
  ports/tbb/portfile.cmake:70 (vcpkg_install_msbuild)
  scripts/ports.cmake:145 (include)

Error: Building package tbb:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+tbb
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[tbb]+Build+error
including:
  package: tbb[core]:x64-windows -> 2020_U3#8
    vcpkg-tool version: 2022-03-09-1affd32f93b299d5a907816c328ca3ededb73a7e
    vcpkg-scripts version: a76eb002a 2022-03-24 (6 hours ago)

Additionally, attach any relevant sections from the log files above.

**Additional context**
Found some similar problems that are still open. I am just curious if this TBB build problem has been solved. I have both MS Visual Studio and MSYS2 installed. Not sure if this is caused by some conflicts of two compilers or vcpkg is smart enough to figure out which toolchain to use.

**Comment by FrankXie05** [comment]
@xzhao99 Thanks for posting this issue. Sorry, I didn't reproduce your problem locally, you can pull a clean `vcpkg` to try again and could you please provied the error log? :)
`D:\workdir\vcpkg\buildtrees\tbb\build-x64-windows-rel-out.log`
```
PS E:\v\vcpkg> ./vcpkg install tbb:x64-windows                                                                                                                                                
Computing installation plan...                                                                                                                                                                
The following packages will be built and installed:                                                                                                                                               
tbb[core]:x64-windows -> 2020_U3#8                                                                                                                                                        
Detecting compiler hash for triplet x64-windows...                                                                                                                                            
Restored 0 packages from C:\Users\test\AppData\Local\vcpkg\archives in 345.8 us. Use --debug to see more details.                                                                       
Starting package 1/1: tbb:x64-windows                                                                                                                                                         
Building package tbb[core]:x64-windows...                                                                                                                                                     
-- Downloading https://github.com/oneapi-src/oneTBB/archive/eca91f16d7490a8abfdee652dadf457ec820cc37.tar.gz -> oneapi-src-oneTBB-eca91f16d7490a8abfdee652dadf457ec820cc37.tar.gz...           
-- Extracting source E:/v/vcpkg/downloads/oneapi-src-oneTBB-eca91f16d7490a8abfdee652dadf457ec820cc37.tar.gz                                                                                  
 -- Applying patch fix-static-build.patch                                                                                                                                                     
 -- Applying patch terminate-when-buildtool-notfound.patch                                                                                                                                    
 -- Using source at E:/v/vcpkg/buildtrees/tbb/src/7ec820cc37-30e75ff0be.clean                                                                                                                 
 -- Building build/vs2013/makefile.sln for Release                                                                                                                                            
 -- Building build/vs2013/makefile.sln for Debug                                                                                                                                              
 -- Installing: E:/v/vcpkg/packages/tbb_x64-windows/share/tbb/copyright                                                                                                                       
 -- Performing post-build validation                                                                                                                                                          
 -- Performing post-build validation done                                                                                                                                                     
 Stored binary cache: C:\Users\test\AppData\Local\vcpkg\archives\37\375f3bcd7d0324bd059cae5e5fce00485d09bf6785ea150d4455eb9f9966118a.zip                                                
 Installing package tbb[core]:x64-windows...                                                                                                                                                  
 Elapsed time for package tbb:x64-windows: 1.283 min 
 
 Total elapsed time: 1.58 min  
 
 The package tbb provides CMake targets:  
 
	 find_package(TBB CONFIG REQUIRED)                                                                                                                            
	 target_link_libraries(main PRIVATE TBB::tbb)                                                                                                                    
 
PS E:\v\vcpkg>  
```

**Comment by xzhao99** [comment]
@FrankXie05 @JonLiu1993 Thank you for reminding me to check the log files. I found that it was caused by the missing of "Windows 11 SDK" when installing Visual Studio Community and build tools. After modifying the installation, vcpkg now works! My first time to use vcpkg, very convenient!

**Comment by FrankXie05** [comment]
I will close this issue, if you still have questions please contact me and I will reopen it.
