### ISSUE TITLE
vcpkg build fleet should have CMake, Ninja, and Python installed so they need not be `vcpkg fetch`'d every time

### ISSUE THREAD

**Issue by BillyONeal** [microsoft/vcpkg#23756]

**Comment by Neumann-A** [comment]
Is that so bad? Rebuild llvm or unnecessary host deps are probably more of a CI timesink. Also how would those otherwise be updated by us?

**Comment by BillyONeal** [comment]
> Is that so bad? Rebuild llvm or unnecessary host deps are probably more of a CI timesink. Also how would those otherwise be updated by us?

It's less about time sink and more about wanting to try new things in the build lab being frustrating because we have to wash everything through `vcpkg fetch`.

**Comment by BillyONeal** [comment]
(To be clear, we would not gate edits to 'morally' vcpkgTools.xml or any replacement thereof on matching what we bundle into the images)

**Comment by klarkxy** [comment]
How can I install packages without Ninja?
I do not want use it.

**Comment by BillyONeal** [comment]
> How can I install packages without Ninja? I do not want use it.

You can't.
