### ISSUE TITLE
[atlmfc] Build error  Building package atlmfc:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by cindylly** [microsoft/vcpkg#23771]
**Host Environment**
- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**
`./vcpkg install xxxx`

**Failure logs**
-Cut and paste the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by FrankXie05** [comment]
@cindylly Thanks for posting this issue, could you please provide the error log?
 And please install ATL and MFC component via vs installer, and try again, you can reference https://github.com/microsoft/vcpkg/issues/4257

**Comment by FrankXie05** [comment]
Ping @cindylly does the issue still occur?

**Comment by FrankXie05** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!

**Comment by AnatolFil** [comment]
I have the same problem. ATL and MFC installed via VS.
Program log ->
 .....
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Restored 0 packages from C:\Users\chupakabra\AppData\Local\vcpkg\archives in 1.58 ms. Use --debug to see more details.
Starting package 1/33: atlmfc:x64-windows
Building package atlmfc[core]:x64-windows...
CMake Error at ports/atlmfc/portfile.cmake:7 (message):
  Unable to locate 'afxres.h'.  Ensure you have installed the ATL/MFC
  component of Visual Studio.
Call Stack (most recent call first):
  scripts/ports.cmake:145 (include)
