### ISSUE TITLE
[python3] Build error

### ISSUE THREAD

**Issue by whiteblXK** [microsoft/vcpkg#23777]
Starting package 1/30: python3:x64-windows
Building package python3[core]:x64-windows...
-- Using cached python-cpython-v3.10.2.tar.gz.
-- Cleaning sources at C:/vcpkg/buildtrees/python3/src/v3.10.2-a8de38632e.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg/downloads/python-cpython-v3.10.2.tar.gz
-- Applying patch 0002-use-vcpkg-zlib.patch
-- Applying patch 0003-devendor-external-dependencies.patch
-- Applying patch 0004-dont-copy-vcruntime.patch
-- Applying patch 0005-only-build-required-projects.patch
-- Applying patch 0009-python.pc.patch
-- Applying patch 0010-bz2d.patch
-- Using source at C:/vcpkg/buildtrees/python3/src/v3.10.2-a8de38632e.clean
-- Building PCbuild/pcbuild.proj for Release
-- Building PCbuild/pcbuild.proj for Debug
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:128 (message):
    Command failed: msbuild C:/vcpkg/buildtrees/python3/x64-windows-dbg/v3.10.2-a8de38632e.clean/PCbuild/pcbuild.proj /p:Configuration=Debug /p:IncludeExtensions=true /p:IncludeExternals=true /p:IncludeCTypes=true /p:IncludeSSL=true /p:IncludeTkinter=false /p:IncludeTests=false /p:ForceImportBeforeCppTargets=C:/vcpkg/buildtrees/python3/src/v3.10.2-a8de38632e.clean/PCbuild/python_vcpkg.props /p:IncludeUwp=false /p:_VcpkgPythonLinkage=DynamicLibrary /t:Rebuild /p:Platform=x64 /p:PlatformToolset=v143 /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /p:WindowsTargetPlatformVersion=10.0.19041.0 /p:VcpkgTriplet=x64-windows /p:VcpkgInstalledDir=C:/vcpkg/installed /p:VcpkgManifestInstall=false /p:UseMultiToolTask=true /p:MultiProcMaxCount=17 /p:EnforceProcessCountAcrossBuilds=true /m:17
    Working Directory: C:/vcpkg/buildtrees/python3/x64-windows-dbg/v3.10.2-a8de38632e.clean
    Error code: 1
    See logs for more information:
      C:\vcpkg\buildtrees\python3\build-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_msbuild.cmake:201 (vcpkg_execute_required_process)
  ports/python3/portfile.cmake:140 (vcpkg_install_msbuild)
  scripts/ports.cmake:145 (include)

Error: Building package python3:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+python3
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[python3]+Build+error
including:
  package: python3[core]:x64-windows -> 3.10.2#1
    vcpkg-tool version: 2022-03-09-1affd32f93b299d5a907816c328ca3ededb73a7e
    vcpkg-scripts version: a76eb002a 2022-03-24 (21 hours ago)

Additionally, attach any relevant sections from the log files above.

[build-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/8352894/build-x64-windows-dbg-out.log)
[build-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/8352895/build-x64-windows-rel-out.log)

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Did you install English language package on your Visual Studio Installer? And I found your build error is similar with issue #23713. Could you try the solution from https://github.com/microsoft/vcpkg/issues/23713#issuecomment-1077495305? You could try run `vcpkg update/upgrade` combo.

**Comment by whiteblXK** [comment]
I handled it, the problem was my antivirus. I had to exclude the vcpkg folder from scanning and now everything works. And yes, I have installed English language pack.

**Comment by LilyWangLL** [comment]
Thanks for your reply. Since this iusse has been resolved, I am closing this issue for now.
