### ISSUE TITLE
gtest.dll did not copy in dubug

### ISSUE THREAD

**Issue by LazyWolfLin** [Microsoft/vcpkg#2378]
I use gtest:x64-windows in windows10 with vs 2017 and it work well in release. But it did not copy gtest.dll in debug.

**Comment by whsimic** [comment]
me too, I use gtest:x86-windows in windows7 with VS2017, it work well in release, but it do not copy gtest.dll in debug. when I run my code in debug mode, it prompt "miss gtest.dll", release mode is OK

**Comment by ras0219-msft** [comment]
Thank you for posting this issue! It should be fixed in the latest master (gtest package version 1.8.0-5).
