### ISSUE TITLE
Regression in 2022.02.23 - CMake warnings on CMake 3.21 or greater: Policy CMP0126 is not set: set(CACHE) does not remove a normal variable of the same name

### ISSUE THREAD

**Issue by DSMitten** [microsoft/vcpkg#23784]
**Describe the bug**
In 2022.02.23, vcpkg.cmake added the following code:
```cmake
cmake_policy(PUSH)
cmake_policy(VERSION 3.7.2)
```

This leaves any policies introduced in later cmake versions unset. CMake 3.21 introduced policy CMP0126 which is not set, and generates build warnings anywhere vcpkg.cmake sets a cache variable:

```
WARNING: CMake Warning (dev) at external/vcpkg/scripts/buildsystems/vcpkg.cmake:63 (set):
  Policy CMP0126 is not set: set(CACHE) does not remove a normal variable of
  the same name.  Run "cmake --help-policy CMP0126" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

  For compatibility with older versions of CMake, normal variable
  "VCPKG_MANIFEST_DIR" will be removed from the current scope.
Call Stack (most recent call first):
  dev/make/projectInit/toolchain.cmake:38 (include)
  C:/Program Files/CMake/share/cmake-3.22/Modules/CMakeDetermineSystem.cmake:124 (include)
  CMakeLists.txt:18 (project)
This warning is for project developers.  Use -Wno-dev to suppress it.
```

**Expected behavior**
No build warnings due to unset CMake policy

This should be relatively easy to fix. After setting CMake policy to 3.7.2, you could add a conditional policy set for CMP0126, like this:
```cmake
cmake_policy(PUSH)
cmake_policy(VERSION 3.7.2)
if (CMAKE_VERSION VERSION_GREATER_EQUAL 3.21.0)
    cmake_policy(SET CMP0126 NEW) # Avoid warnings about resetting cache variables. Policy introduced in 3.21
endif()
```

**Failure logs**
[_generate_win-x64-debug.log](https://github.com/microsoft/vcpkg/files/8355279/_generate_win-x64-debug.log)

**Comment by dg0yt** [comment]
In general, setting a policy to `NEW` changes behaviour, and this is not always desired.

I tried to reproduce the warning with CMake 3.22.2 on Linux, but failed. And I didn't see them in CI logs. 
I found that for this policy, CMake normally doesn't warn:
> Unlike many policies, CMake version 3.22.3 does not warn when the policy is not set and simply uses OLD behavior. See documentation of the [CMAKE_POLICY_WARNING_CMP0126](https://cmake.org/cmake/help/v3.22/variable/CMAKE_POLICY_WARNING_CMPNNNN.html#variable:CMAKE_POLICY_WARNING_CMP%3CNNNN%3E) variable to control the warning.

So maybe you actually asked for these warnings?

**Comment by DSMitten** [comment]
I checked, and we've got --trace-redirect on to record cmake output to a file, so it warns on CMP0126. Please consider whether sticking with the old policy is the best thing to do here. The old behavior is less consistent than the new one - setting cache variables sometimes removes normal variables from the current scope, and other times doesn't.

**Comment by jobor** [comment]
Here's a minimal reproducer:
[cmp0126-vcpkg.zip](https://github.com/microsoft/vcpkg/files/10870287/cmp0126-vcpkg.zip)

Configure this project with 
```
cmake --toolchain D:\dev\vcpkg\scripts\buildsystems\vcpkg.cmake . --trace-expand --trace-redirect=cmake.trace
```
to see the CMP0126 warning.

**Comment by dg0yt** [comment]
This is my personal summary on this issue:
- It only happens when the user explicitly enables CMake tracing. 
- It is a CMake behaviour, not a vcpkg behaviour.
- It can be turned off by the user using `CMAKE_POLICY_WARNING_CMP<NNNN>`.
