### ISSUE TITLE
[vcpkg export] cmd.exe PATH issue

### ISSUE THREAD

**Issue by gvanem** [microsoft/vcpkg#23783]
Running commands like:
```
vcpkg.exe export picojson --zip --output-dir=pico-package
:: or
vcpkg.exe export picojson --nuget --output-dir=pico-package
```
works fine in my [4NT](https://jpsoft.com) shell. But not when using `cmd.exe` (!?). Errors are:
```
The following packages need to be built:
    zip:x86-windows
```

Or:
```
The following packages need to be built:
    nuget:x86-windows
```

Besides, with `--debug`, there is this message:
`[DEBUG] Failed to open: F:\gv\VC_project\VCPKG\vcpkg-bundle.json`

A file I do not have. With 4NT as my shell, there's the same message. But the `export` works. How come?

With `cmd` as the shell, only  a  `vcpkg.exe export picojson --raw` works.

I'd assume that `vcpkg.exe` would find my `f:\util\zip.exe` or `f:\util\nuget.exe` when both are on my `PATH`.
It does not. And I have a `set VCPKG_ROOT` in my User environment.

**Environment**
- OS: Windows-10
- Compiler: MSVC, 19.29.30139 for x86

**PS**. The [*picojson*](https://github.com/kazuho/picojson) package is really one single header. 
  So how can a `vcpkg.exe export picojson --raw --output-dir=pico-package` create a more lean package directory. 
  Now it fills the `picpo-package` directory with 24 files. Not very lean and compact.

**Comment by JackBoosY** [comment]
We recommend to use powershell instead of cmd in Windows, can you please retry again?

Thanks.

**Comment by gvanem** [comment]
Doing the same tests in *Powerhell* works. But I do not like it. I'll stick to 4NT.

**Comment by JackBoosY** [comment]
@gvanem We recommend use powershell in Windows is because some processes use powershell scripts to analyze some data. Invoking the powershell script may fail if other command line tools are used..

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
