### ISSUE TITLE
[ktx] update from beta to full release

### ISSUE THREAD

**Issue by kuzma-t** [microsoft/vcpkg#23825]
Library name: [ktx](https://github.com/KhronosGroup/KTX-Software)

New version number: [4.0.0](https://github.com/KhronosGroup/KTX-Software/releases/tag/v4.0.0)

Other information that may be useful (release notes, etc...): Version used in port file is beta5, current is a full release

**Comment by FrankXie05** [comment]
@kuzma-t The port `ktx `has been update to version 4.0.0, duplicate issue #17656, and fix pull request #18644
