### ISSUE TITLE
[icu] Build error

### ISSUE THREAD

**Issue by Machismo-xu** [microsoft/vcpkg#23829]
**Host Environment**
- OS: [Windows]
- Compiler:win10

**To Reproduce**
`./vcpkg install qt5:x64-windows`

**Failure logs**
```
-CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:128 (message):
    Command failed: "E:/Visual Studio/vcpkg/downloads/tools/msys2/7e05e7aa09f1709f/usr/bin/bash.exe" --noprofile --norc --debug -c "V=1 CPP='compile cl.exe -E' CC='compile cl.exe' CC_FOR_BUILD='compile cl.exe' CXX='compile cl.exe' RC='windres-rc rc.exe' WINDRES='windres-rc rc.exe' AR='ar-lib lib.exe' LD='link.exe -verbose' RANLIB=':' STRIP=':' NM='dumpbin.exe -symbols -headers' DLLTOOL='link.exe -verbose -dll' CCAS=':' AS=':' ./../src/c-69_1-src-b48be0c7ce.clean/source/configure --build=x86_64-pc-mingw32 \"--enable-icu-build-win\" \"--disable-samples\" \"--disable-tests\" \"--disable-layoutex\" \"ac_cv_prog_ac_ct_STRIP=:\" \"gl_cv_double_slash_root=yes\" \"ac_cv_func_memmove=yes\" \"--disable-silent-rules\" \"--verbose\" \"--enable-shared\" \"--disable-static\" \"--enable-debug\" \"--disable-release\" \"--prefix=/E/Visual Studio/vcpkg/installed/x64-windows/debug\" \"--bindir=\\${prefix}/../tools/icu/debug/bin\" \"--sbindir=\\${prefix}/../tools/icu/debug/sbin\" \"--libdir=\\${prefix}/lib\" \"--includedir=\\${prefix}/../include\" \"--datarootdir=\\${prefix}/share/icu\""
    Working Directory: E:/Visual Studio/vcpkg/buildtrees/icu/x64-windows-dbg
    Error code: 1
    See logs for more information:
      E:\Visual Studio\vcpkg\buildtrees\icu\config-x64-windows-dbg-out.log
      E:\Visual Studio\vcpkg\buildtrees\icu\config-x64-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:815 (vcpkg_execute_required_process)
  ports/icu/portfile.cmake:51 (vcpkg_configure_make)
  scripts/ports.cmake:145 (include)


Error: Building package icu:x64-windows failed with: BUILD_FAILED
```
**Additional context**
HELP ME!!!

**Comment by JackBoosY** [comment]
Please provide the following failure logs first:
E:\Visual Studio\vcpkg\buildtrees\icu\config-x64-windows-dbg-out.log
E:\Visual Studio\vcpkg\buildtrees\icu\config-x64-windows-dbg-err.log

**Comment by Machismo-xu** [comment]
This is the content in config-x64-windows-dbg-err.log:
-------------------------------------------------------------------------
configure: WARNING: unrecognized options: --disable-silent-rules
./../src/c-69_1-src-b48be0c7ce.clean/source/configure: line 4688: E:/Visual: No such file or directory
configure: WARNING: unrecognized options: --disable-silent-rules
./../src/c-69_1-src-b48be0c7ce.clean/source/configure: line 9916: E:/Visual: No such file or directory
configure: error: Python failed to run; see above error.
-------------------------------------------------------------------------
And this is the content in config-x64-windows-dbg-out.log:
-------------------------------------------------------------------------
checking for ICU version numbers... release 69.1, library 69.1, unicode version 13.0
checking build system type... x86_64-pc-mingw32
checking host system type... x86_64-pc-mingw32
checking whether to build debug libraries... yes
checking whether to build release libraries... no
checking whether the C compiler works... yes
checking for C compiler default output file name... conftest.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... no
checking for suffix of object files... obj
checking whether the compiler supports GNU C... no
checking whether compile cl.exe accepts -g... yes
checking for compile cl.exe option to enable C11 features... unsupported
checking for compile cl.exe option to enable C99 features... unsupported
checking for compile cl.exe option to enable C89 features... unsupported
checking whether the compiler supports GNU C++... no
checking whether compile cl.exe accepts -g... yes
checking for compile cl.exe option to enable C++11 features... none needed
checking pkg-config is at least version 0.20... no
checking for icu-le-hb... no
checking how to run the C preprocessor... compile cl.exe -E
checking for a BSD-compatible install... /usr/bin/install -c
checking for python3... E:/Visual Studio/vcpkg/downloads/tools/python/python-3.10.1-x64/python.exe
checking for gmake... no
checking for gnumake... no
checking for doxygen... no
checking checking for executable suffix... .exe
checking whether strict compiling is on... yes
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... no
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... no
checking size of void *... 8
checking whether runnable 64 bit binaries are built by default... yes
checking which Makefile fragment to use for x86_64-pc-mingw32... mh-msys-msvc
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking whether to enable auto cleanup of libraries... no
checking whether to enable draft APIs... yes
checking for ranlib... :
checking for a sed that does not truncate output... /usr/bin/sed
checking for ar... ar-lib lib.exe
checking whether to enable renaming of symbols... yes
checking whether to enable function and data tracing... no
checking for elf.h... no
checking whether to enable dynamic loading of plugins. Ignored if plugins disabled.... yes
checking for dlfcn.h... no
checking for library containing dlopen... no
checking for dlopen... no
checking for gettimeofday... no
checking if we have a C++ compiler... Good
checking for pthread_attr_init in -lpthread... no
checking for library containing pthread_mutex_destroy... no
checking for pthread_mutex_init in -lpthread... no
checking for pthread_mutex_lock... no
checking for mmap... no
checking for genccode assembly... 
checking for inttypes.h... (cached) yes
checking for dirent.h... no
checking whether byte ordering is bigendian... no
checking for nl_langinfo... no
checking for namespace support... yes
checking for properly overriding new and delete... yes
checking for placement new and delete... yes
checking for popen... no
checking for tzset... yes
checking for tzname... no
checking for _tzname... no
checking for timezone... no
checking for __timezone... no
checking for _timezone... yes
checking for strtod_l... no
checking for std::string_view... no
checking for int8_t... yes
checking for uint8_t... yes
checking for int16_t... yes
checking for uint16_t... yes
checking for int32_t... yes
checking for uint32_t... yes
checking for int64_t... yes
checking for uint64_t... yes
checking for wchar.h... yes
checking for library containing wcscpy... none required
checking size of wchar_t... 2
checking for UTF-16 string literal support... unknown
checking for a library suffix to use... none
CPPFLAGS=-DWIN32 -D_WINDOWS -D_DEBUG $(THREADSCPPFLAGS)  -DU_DEBUG=1 -DHAVE_DLOPEN=0 -DU_HAVE_MMAP=0 -DU_HAVE_DIRENT_H=0 -DU_HAVE_POPEN=0 -DU_HAVE_TZNAME=0 -DU_HAVE_STRTOD_L=0 
CFLAGS=-nologo -W3 -utf-8 -MP -MDd -Z7 -Ob0 -Od -Xcompiler -RTC1 -W4 -W4 $(THREADSCFLAGS) 
CXXFLAGS=-nologo -W3 -utf-8 -GR -EHsc -MP -MDd -Z7 -Ob0 -Od -Xcompiler -RTC1 $(THREADSCXXFLAGS) 
configure: creating ./config.status
config.status: creating icudefs.mk
config.status: creating Makefile
config.status: creating data/pkgdataMakefile
config.status: creating config/Makefile.inc
config.status: creating config/icu.pc
config.status: creating config/pkgdataMakefile
config.status: creating data/Makefile
config.status: creating stubdata/Makefile
config.status: creating common/Makefile
config.status: creating i18n/Makefile
config.status: creating layoutex/Makefile
config.status: creating io/Makefile
config.status: creating extra/Makefile
config.status: creating extra/uconv/Makefile
config.status: creating extra/uconv/pkgdataMakefile
config.status: creating extra/scrptrun/Makefile
config.status: creating tools/Makefile
config.status: creating tools/ctestfw/Makefile
config.status: creating tools/toolutil/Makefile
config.status: creating tools/makeconv/Makefile
config.status: creating tools/genrb/Makefile
config.status: creating tools/genccode/Makefile
config.status: creating tools/gencmn/Makefile
config.status: creating tools/gencnval/Makefile
config.status: creating tools/gendict/Makefile
config.status: creating tools/gentest/Makefile
config.status: creating tools/gennorm2/Makefile
config.status: creating tools/genbrk/Makefile
config.status: creating tools/gensprep/Makefile
config.status: creating tools/icuinfo/Makefile
config.status: creating tools/icupkg/Makefile
config.status: creating tools/icuswap/Makefile
config.status: creating tools/pkgdata/Makefile
config.status: creating tools/tzcode/Makefile
config.status: creating tools/gencfu/Makefile
config.status: creating tools/escapesrc/Makefile
config.status: creating test/Makefile
config.status: creating test/compat/Makefile
config.status: creating test/testdata/Makefile
config.status: creating test/testdata/pkgdataMakefile
config.status: creating test/hdrtst/Makefile
config.status: creating test/intltest/Makefile
config.status: creating test/cintltst/Makefile
config.status: creating test/iotest/Makefile
config.status: creating test/letest/Makefile
config.status: creating test/perf/Makefile
config.status: creating test/perf/collationperf/Makefile
config.status: creating test/perf/collperf/Makefile
config.status: creating test/perf/collperf2/Makefile
config.status: creating test/perf/dicttrieperf/Makefile
config.status: creating test/perf/ubrkperf/Makefile
config.status: creating test/perf/charperf/Makefile
config.status: creating test/perf/convperf/Makefile
config.status: creating test/perf/localecanperf/Makefile
config.status: creating test/perf/normperf/Makefile
config.status: creating test/perf/DateFmtPerf/Makefile
config.status: creating test/perf/howExpensiveIs/Makefile
config.status: creating test/perf/strsrchperf/Makefile
config.status: creating test/perf/unisetperf/Makefile
config.status: creating test/perf/usetperf/Makefile
config.status: creating test/perf/ustrperf/Makefile
config.status: creating test/perf/utfperf/Makefile
config.status: creating test/perf/utrie2perf/Makefile
config.status: creating test/perf/leperf/Makefile
config.status: creating test/fuzzer/Makefile
config.status: creating samples/Makefile
config.status: creating samples/date/Makefile
config.status: creating samples/cal/Makefile
config.status: creating samples/layout/Makefile
Not rebuilding data/rules.mk, assuming prebuilt data in data/in
Spawning Python to generate test/testdata/rules.mk...
----------------------------------------------------------------------------

**Comment by JackBoosY** [comment]
` E:/Visual: No such file or directory`

**Comment by dg0yt** [comment]
i.e. try a path without spaces...

**Comment by Machismo-xu** [comment]
Thank you all , and I addressed the problem by downloading and compiling manully -_-...

**Comment by ScarletEmanu** [comment]
I just had the same error. I'm using mingw64 with triplet x64-mingw-dynamic.

**Failure log from output "Cmake/build" in vscode:**
```
[cmake] CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
[cmake]     Command failed: C:/Users/archi/vcpkg/downloads/tools/msys2/a4d8db9df5991f31/usr/bin/bash.exe --noprofile --norc --debug -c "V=1 CPP='C:/ProgramData/mingw64/mingw64/bin/x86_64-w64-mingw32-gcc.exe -E' CC='C:/ProgramData/mingw64/mingw64/bin/x86_64-w64-mingw32-gcc.exe' CC_FOR_BUILD='C:/ProgramData/mingw64/mingw64/bin/x86_64-w64-mingw32-gcc.exe' CPP_FOR_BUILD='C:/ProgramData/mingw64/mingw64/bin/x86_64-w64-mingw32-gcc.exe -E' CXX_FOR_BUILD='C:/ProgramData/mingw64/mingw64/bin/x86_64-w64-mingw32-g++.exe' CXX='C:/ProgramData/mingw64/mingw64/bin/x86_64-w64-mingw32-g++.exe' RC='C:/ProgramData/mingw64/mingw64/bin/windres.exe' WINDRES='C:/ProgramData/mingw64/mingw64/bin/windres.exe' AR='C:/ProgramData/mingw64/mingw64/bin/ar.exe' LD='C:/ProgramData/mingw64/mingw64/bin/ld.exe -verbose' RANLIB='C:/ProgramData/mingw64/mingw64/bin/ranlib.exe' OBJDUMP='C:/ProgramData/mingw64/mingw64/bin/objdump.exe' STRIP='C:/ProgramData/mingw64/mingw64/bin/strip.exe' NM='C:/ProgramData/mingw64/mingw64/bin/nm.exe' DLLTOOL='C:/ProgramData/mingw64/mingw64/bin/dlltool.exe' CCAS=':' AS=':' ./../src/c-74_2-src-83138cd994.clean/source/configure --build=x86_64-pc-mingw32 \"--enable-icu-build-win\" \"--enable-tools\" \"--disable-samples\" \"--disable-tests\" \"--disable-layoutex\" \"gl_cv_double_slash_root=yes\" \"ac_cv_func_memmove=yes\" \"--disable-silent-rules\" \"--verbose\" \"--enable-shared\" \"--disable-static\" \"--enable-debug\" \"--disable-release\" \"--prefix=/C/Users/archi/progetti_C++/QtTunes_with_vcpkg/build/vcpkg_installed/x64-mingw-dynamic/debug\" \"--bindir=\\${prefix}/../tools/icu/debug/bin\" \"--sbindir=\\${prefix}/../tools/icu/debug/sbin\" \"--libdir=\\${prefix}/lib\" \"--includedir=\\${prefix}/../include\" \"--datarootdir=\\${prefix}/share/icu\""
[cmake]     Working Directory: C:/Users/archi/vcpkg/buildtrees/icu/x64-mingw-dynamic-dbg
[cmake]     Error code: 1
[cmake]     See logs for more information:
[cmake]       C:\Users\archi\vcpkg\buildtrees\icu\config-x64-mingw-dynamic-dbg-config.log
[cmake]       C:\Users\archi\vcpkg\buildtrees\icu\config-x64-mingw-dynamic-dbg-out.log
[cmake]       C:\Users\archi\vcpkg\buildtrees\icu\config-x64-mingw-dynamic-dbg-err.log
[cmake] 
[cmake] Call Stack (most recent call first):
[cmake]   scripts/cmake/vcpkg_configure_make.cmake:863 (vcpkg_execute_required_process)
[cmake]   C:/Users/archi/AppData/Local/vcpkg/registries/git-trees/a36199768fe1f9676b61d5d28ed9ac36c9f041c0/portfile.cmake:81 (vcpkg_configure_make)
[cmake]   scripts/ports.cmake:175 (include)
[cmake] 
[cmake] 
[cmake] error: building icu:x64-mingw-dynamic failed with: BUILD_FAILED
```


**config-x64-mingw-dynamic-dbg-err.log:**
```
configure: WARNING: unrecognized options: --disable-silent-rules
configure: WARNING: unrecognized options: --disable-silent-rules
./../src/c-74_2-src-83138cd994.clean/source/configure: line 10017: C:/Program: No such file or directory
configure: error: Python failed to run; see above error.
```

**config-x64-mingw-dynamic-dbg-out.log:**
```
checking for ICU version numbers... release 74.2, library 74.2, unicode version 15.1
checking build system type... x86_64-pc-mingw32
checking host system type... x86_64-pc-mingw32
checking whether to build debug libraries... yes
checking whether to build release libraries... no
checking whether the C compiler works... yes
checking for C compiler default output file name... a.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether C:/ProgramData/mingw64/mingw64/bin/x86_64-w64-mingw32-gcc.exe accepts -g... yes
checking for C:/ProgramData/mingw64/mingw64/bin/x86_64-w64-mingw32-gcc.exe option to enable C11 features... none needed
checking whether the compiler supports GNU C++... yes
checking whether C:/ProgramData/mingw64/mingw64/bin/x86_64-w64-mingw32-g++.exe accepts -g... yes
checking for C:/ProgramData/mingw64/mingw64/bin/x86_64-w64-mingw32-g++.exe option to enable C++11 features... none needed
checking pkg-config is at least version 0.20... yes
checking for icu-le-hb... no
checking how to run the C preprocessor... C:/ProgramData/mingw64/mingw64/bin/x86_64-w64-mingw32-gcc.exe -E
checking for a BSD-compatible install... /usr/bin/install -c
checking for python3... C:/Program Files/Python312/python.exe
checking for gmake... no
checking for gnumake... no
checking for doxygen... no
checking checking for executable suffix... .exe
checking whether strict compiling is on... yes
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking size of void *... 8
checking whether runnable 64 bit binaries are built by default... yes
checking which Makefile fragment to use for x86_64-pc-mingw32... mh-mingw64
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking whether to enable auto cleanup of libraries... no
checking whether to enable draft APIs... yes
checking for ranlib... C:/ProgramData/mingw64/mingw64/bin/ranlib.exe
checking for a sed that does not truncate output... /usr/bin/sed
checking for ar... C:/ProgramData/mingw64/mingw64/bin/ar.exe
checking whether to enable renaming of symbols... yes
checking whether to enable function and data tracing... no
checking for elf.h... no
checking whether to enable dynamic loading of plugins. Ignored if plugins disabled.... yes
checking for dlfcn.h... no
checking for library containing dlopen... no
checking for dlopen... no
checking for gettimeofday... yes
checking if we have a C++ compiler... Good
checking if we have a C++11 compiler... yes
configure: Adding CXXFLAGS option -std=c++11
checking for pthread_attr_init in -lpthread... yes
checking for mmap... no
checking for genccode assembly... 
checking for inttypes.h... (cached) yes
checking for dirent.h... yes
checking whether byte ordering is bigendian... no
checking for nl_langinfo... no
checking for namespace support... yes
checking for properly overriding new and delete... yes
checking for placement new and delete... yes
checking for popen... yes
checking for tzset... yes
checking for tzname... yes
checking for timezone... yes
checking for strtod_l... no
checking for std::string_view... no
checking for int8_t... yes
checking for uint8_t... yes
checking for int16_t... yes
checking for uint16_t... yes
checking for int32_t... yes
checking for uint32_t... yes
checking for int64_t... yes
checking for uint64_t... yes
checking for wchar.h... yes
checking for library containing wcscpy... none required
checking size of wchar_t... 2
checking for UTF-16 string literal support... available
checking for a library suffix to use... none
checking whether C++ compiler accepts -Wambiguous-reversed-operator... no
CPPFLAGS= $(THREADSCPPFLAGS)  -DU_DEBUG=1 -DHAVE_DLOPEN=0 -DU_HAVE_MMAP=0 -DU_HAVE_STRTOD_L=0 
CFLAGS=-g -std=c11 -Wall -pedantic -Wshadow -Wpointer-arith -Wmissing-prototypes -Wwrite-strings $(THREADSCFLAGS) 
CXXFLAGS=-g -W -Wall -pedantic -Wpointer-arith -Wwrite-strings -Wno-long-long -std=c++11 $(THREADSCXXFLAGS) 
configure: creating ./config.status
config.status: creating icudefs.mk
config.status: creating Makefile
config.status: creating data/pkgdataMakefile
config.status: creating config/Makefile.inc
config.status: creating config/icu.pc
config.status: creating config/pkgdataMakefile
config.status: creating data/Makefile
config.status: creating stubdata/Makefile
config.status: creating common/Makefile
config.status: creating i18n/Makefile
config.status: creating layoutex/Makefile
config.status: creating io/Makefile
config.status: creating extra/Makefile
config.status: creating extra/uconv/Makefile
config.status: creating extra/uconv/pkgdataMakefile
config.status: creating extra/scrptrun/Makefile
config.status: creating tools/Makefile
config.status: creating tools/ctestfw/Makefile
config.status: creating tools/toolutil/Makefile
config.status: creating tools/makeconv/Makefile
config.status: creating tools/genrb/Makefile
config.status: creating tools/genccode/Makefile
config.status: creating tools/gencmn/Makefile
config.status: creating tools/gencnval/Makefile
config.status: creating tools/gendict/Makefile
config.status: creating tools/gentest/Makefile
config.status: creating tools/gennorm2/Makefile
config.status: creating tools/genbrk/Makefile
config.status: creating tools/gensprep/Makefile
config.status: creating tools/icuinfo/Makefile
config.status: creating tools/icupkg/Makefile
config.status: creating tools/icuswap/Makefile
config.status: creating tools/pkgdata/Makefile
config.status: creating tools/icuexportdata/Makefile
config.status: creating tools/tzcode/Makefile
config.status: creating tools/gencfu/Makefile
config.status: creating tools/escapesrc/Makefile
config.status: creating test/Makefile
config.status: creating test/compat/Makefile
config.status: creating test/testdata/Makefile
config.status: creating test/testdata/pkgdataMakefile
config.status: creating test/hdrtst/Makefile
config.status: creating test/intltest/Makefile
config.status: creating test/cintltst/Makefile
config.status: creating test/iotest/Makefile
config.status: creating test/letest/Makefile
config.status: creating test/perf/Makefile
config.status: creating test/perf/collationperf/Makefile
config.status: creating test/perf/collperf/Makefile
config.status: creating test/perf/collperf2/Makefile
config.status: creating test/perf/dicttrieperf/Makefile
config.status: creating test/perf/ubrkperf/Makefile
config.status: creating test/perf/charperf/Makefile
config.status: creating test/perf/convperf/Makefile
config.status: creating test/perf/localecanperf/Makefile
config.status: creating test/perf/normperf/Makefile
config.status: creating test/perf/DateFmtPerf/Makefile
config.status: creating test/perf/howExpensiveIs/Makefile
config.status: creating test/perf/strsrchperf/Makefile
config.status: creating test/perf/unisetperf/Makefile
config.status: creating test/perf/usetperf/Makefile
config.status: creating test/perf/ustrperf/Makefile
config.status: creating test/perf/utfperf/Makefile
config.status: creating test/perf/utrie2perf/Makefile
config.status: creating test/perf/leperf/Makefile
config.status: creating test/fuzzer/Makefile
config.status: creating samples/Makefile
config.status: creating samples/date/Makefile
config.status: creating samples/cal/Makefile
config.status: creating samples/layout/Makefile
Not rebuilding data/rules.mk, assuming prebuilt data in data/in
Spawning Python to generate test/testdata/rules.mk...
```

Perhaps in config-x64-mingw-dynamic-dbg-err.log, "C:\Program" refers to path "C:\ProgramData\mingw64\mingw64\..." but i don't know.
