### ISSUE TITLE
Request: Add wimlib

### ISSUE THREAD

**Issue by TooYoungTooSimp** [microsoft/vcpkg#2383]
> [wimlib](https://wimlib.net/) is an open source, cross-platform library for creating, extracting, and modifying Windows Imaging (WIM) archives.

It would be great to have a port of it.
The dependencies of this library have already been included in vcpkg:
- pthread
- libxml2
- iconv
- liblzma
- zlib
> ![image](https://user-images.githubusercontent.com/6648049/34043368-b6ebe120-e1db-11e7-8684-ad6f7e063740.png)

So it would be not so difficult to port this library.

**Comment by JackBoosY** [comment]
We can’t reopen this issue until a PR is opened, unfortunately, consider making a pull request!
