### ISSUE TITLE
` .\vcpkg.exe remove opencv[contrib]` faild.

### ISSUE THREAD

**Issue by shelllet** [microsoft/vcpkg#23834]
**Describe the bug**
![image](https://user-images.githubusercontent.com/16729017/160546730-b4e5bca2-db5e-401c-bf85-728c26a92422.png)

**Environment**
- OS: Windows 11
- Compiler: revision

**To Reproduce**
1. ./vcpkg install opencv[contrib]:x64-windows
2. .\vcpkg.exe remove opencv[contrib]

**Expected behavior**

remove package successfully.

**Failure logs**
error: List of features is not allowed in this contect

**Comment by shelllet** [comment]
`vcpkg remove opencv:x64-windows-mixed` can be executed successfully.

may be features of package cannot directly removed.

**Comment by JackBoosY** [comment]
Since opencv is built in vcpkg by godsend, you can only remove this port completely instead of removing individual features.

**Comment by shelllet** [comment]
@JackBoosY what's godsend?

**Comment by JackBoosY** [comment]
@shelllet Sorry, should be
> Since opencv is built in vcpkg, you can only remove this port completely instead of removing individual features.

**Comment by JackBoosY** [comment]
If you want to remove this port, just use the port name would be okay.

**Comment by shelllet** [comment]
@JackBoosY thks!
