### ISSUE TITLE
[New Port Request] Caliper

### ISSUE THREAD

**Issue by hudengjunai** [microsoft/vcpkg#23832]
Library name:Caliper

Library description:Caliper is an instrumentation and performance profiling library

Source repository URL:https://github.com/LLNL/Caliper.git

Project homepage (if different from the source repository):https://software.llnl.gov/Caliper/index.html

instrumentation off-cpu  time counter and some profile tools  is very important for low latency service development. I think the Caliper is a very good tools.
Currently, I write a performance counter by my self.  Recently I found that the Caliper is more effeicient library than my tools.

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
