### ISSUE TITLE
[New Port Request] <xmlrpc-c>

### ISSUE THREAD

**Issue by MarioAuditore** [microsoft/vcpkg#23840]
Library name: xmlrpc-c

Library description: a c/c++ library for programming xml requests

Source repository URL: http://svn.code.sf.net/p/xmlrpc-c/code/

Project homepage (if different from the source repository): http://xmlrpc-c.sourceforge.net/downloading.php

Anything else that is useful to know when adding (such as optional features the library may have that should be included): library is rather old and yet is still updating, which results in two versions: stable and advanced

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
