### ISSUE TITLE
additional cmake variables

### ISSUE THREAD

**Issue by amigo421** [microsoft/vcpkg#2385]
this is not a bug report, just question

can't find an ability to add extra cmake variable ( -Dxxx=value ) during the build.
is it really possible or currently no? 

actually I'm looking how to enable Qt support in VTK library build. 
I'm looking at CONTROL file and portfile.cmake

I suppose I have to add qt5 to build-depends in CONTROL file but not sure - should I add something in portfile?
what does it mean in a comments there: 

> # Options: These should be set by feature-packages when they become available
> 
> if ("qt" IN_LIST FEATURES)
>     set(VTK_WITH_QT                      ON ) # IMPORTANT: if ON make sure `qt5` is listed as dependency in the CONTROL file
> 

thank you

**Comment by UnaNancyOwen** [comment]
```ps1
vcpkg install vtk[qt] --featurepackages
```

**Comment by JackBoosY** [comment]
Hi @amigo421, you can add a new feature to implement it.
Such as port **curl**:


1. In _ports/vtk/CONTROL_, add one feature like that：
```
...
Feature: qt5
Build-Depends: qt5
Description: qt5 support
```
2. In _ports/vtk/portfile.cmake_, add the following codes:
```
...
set(USE_QT5 OFF)
if("qt5" IN_LIST FEATURES)
    set(USE_QT5=ON)
endif()
...
vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA
    OPTIONS
    -DUSE_QT5=${USE_QT5}
...
```
3. Add support code to the source code and make a patch to apply it.
4. Use this feature with command 'vcpkg install vtk[qt5]'.

Related link [here](https://vcpkg.readthedocs.io/en/latest/specifications/feature-packages/)
