### ISSUE TITLE
Some questions on building CGAL library

### ISSUE THREAD

**Issue by xzhao99** [microsoft/vcpkg#23852]
Hi,

I have several questions on building CGAL library:
1. How can I pass the CMake variables to vcpkg? for example, after installation, there are some screen messages:
 CMake Warning at installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:487 (message):
```
  The following variables are not used in CMakeLists.txt:
      `CGAL_HEADER_ONLY`
      `WITH_CGAL_Qt5`
  Please recheck them and remove the unnecessary options from the
  `vcpkg_cmake_configure` call.

  If these options should still be passed for whatever reason, please use the
  `MAYBE_UNUSED_VARIABLES` argument.
Call Stack (most recent call first):
  ports/cgal/portfile.cmake:16 (vcpkg_cmake_configure)
  scripts/ports.cmake:145 (include)
```
However, if I want to build Boost in a "HEADER ONLY" mode for CGAL, how should I pass the configuration variables.

In addition, CGAL offers some optional 3rd-party libraries. If I want CGAL to use Eigen as my linear solver, any way to do it via vcpkg?

2.  Where can I find the detailed build logs and screen info that show the library dependencies and build history? Just want to make sure I can find them when sometimes I would like to look at these information. For example, forget the CMake `find_package()` format:
    ```
    find_package(CGAL CONFIG REQUIRED)
    target_link_libraries(main PRIVATE CGAL::CGAL)
   ```

**Comment by JackBoosY** [comment]
> How can I pass the CMake variables to vcpkg?

set the following code to the triplet file you selected in _VCPKG_ROOT/triplet_:
```cmake
list(APPEND VCPKG_CMAKE_CONFIGURE_OPTIONS YOUR_CUSTOM_CMAKE_OPTIONS)
```

> for example, after installation, there are some screen messages

Sounds like a port bug.

>However, if I want to build Boost in a "HEADER ONLY" mode for CGAL, how should I pass the configuration variables.

set the following code to the triplet file you selected in _VCPKG_ROOT/triplet_:
```cmake
if ("${PORT}" STREQUAL "cgal")
    list(APPEND VCPKG_CMAKE_CONFIGURE_OPTIONS YOUR_CUSTOM_CMAKE_OPTIONS)
endif()
```

>  If I want CGAL to use Eigen as my linear solver, any way to do it via vcpkg?

Request a port feature.

> Where can I find the detailed build logs and screen info that show the library dependencies and build history?

Just run the install command again, vcpkg will print the usage info and not to build it again.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
