### ISSUE TITLE
[cppmicroservices] build failure - Include paths are broken

### ISSUE THREAD

**Issue by spectre-ns** [microsoft/vcpkg#23858]
**Host Environment**
- OS: Windows 11
- Compiler: MSVC 2019

**To Reproduce**
`./vcpkg install cppmicroservices:x64-windows`

**Failure logs**
all includes are at #include <cppmicroservices3/cppmicroservices/Framework.h>
instead of #include <cppmicroservices/Framework.h> as expected by the rest of the library

**Comment by Adela0814** [comment]
@spectre-ns  I can not repro your issue, I can build successfully in my machine. Could you please provide the full failure logs.

**Comment by spectre-ns** [comment]
@Adela0814  You need to attempt to include and build a program with the library and you'll find that the include paths are all wrong and result in compiler errors in the consuming program.

**Comment by Adela0814** [comment]
So this is not a `cppmicroservices `build failure, but a usage issue. Please provide a simple project to reproduce this behavior, can you please also provide a sample code? thanks.

**Comment by Adela0814** [comment]
@spectre-ns  ping

**Comment by Adela0814** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
