### ISSUE TITLE
[opencv4] Build error with feature cuda

### ISSUE THREAD

**Issue by shuchincn** [microsoft/vcpkg#23850]
**Host Environment**
- OS: Windows 10 21H2
- Compiler: Visual Studio 2022 cl v19.31.31104

**To Reproduce**
` .\vcpkg.exe install opencv4[contrib,cuda]  --recurse`

**Failure logs**
Computing installation plan...
The following packages will be built and installed:
    opencv4[contrib,core,cuda,default-features,dnn,jpeg,png,quirc,tiff,webp]:x86-windows -> 4.5.5
Detecting compiler hash for triplet x86-windows...
-- Automatically setting HTTP(S)_PROXY environment variables to 127.0.0.1:8889
Restored 0 packages from C:\Users\shuchin\AppData\Local\vcpkg\archives in 232.3 us. Use --debug to see more details.
Starting package 1/1: opencv4:x86-windows
Building package opencv4[contrib,core,cuda,default-features,dnn,jpeg,png,quirc,tiff,webp]:x86-windows...
-- Using cached opencv-opencv-4.5.5.tar.gz.
-- Cleaning sources at C:/tools/vcpkg/buildtrees/opencv4/src/4.5.5-f2b5f31c0d.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/tools/vcpkg/downloads/opencv-opencv-4.5.5.tar.gz
-- Applying patch 0001-disable-downloading.patch
-- Applying patch 0002-install-options.patch
-- Applying patch 0003-force-package-requirements.patch
-- Applying patch 0004-fix-policy-CMP0057.patch
-- Applying patch 0005-fix-eigen.patch
-- Applying patch 0006-fix-uwp.patch
-- Applying patch 0008-devendor-quirc.patch
-- Applying patch 0009-fix-protobuf.patch
-- Applying patch 0010-fix-uwp-tiff-imgcodecs.patch
-- Applying patch 0011-remove-python2.patch
-- Applying patch 0012-fix-zlib.patch
-- Applying patch 0013-fix-opengl.patch
-- Applying patch 0014-fix-gstreamer.patch
-- Applying patch 0015-fix-freetype.patch
-- Using source at C:/tools/vcpkg/buildtrees/opencv4/src/4.5.5-f2b5f31c0d.clean
-- Using cached opencv-cache/tiny_dnn/adb1c512e09ca2c7a6faef36f9c53e59-v1.0.0a3.tar.gz.
-- Using cached opencv-cache/nvidia_optical_flow/a73cd48b18dcc0cc8933b30796074191-edb50da3cf849840d680249aa6dbef248ebce2ca.zip.
-- Using cached opencv-opencv_contrib-4.5.5.tar.gz.
-- Cleaning sources at C:/tools/vcpkg/buildtrees/opencv4/src/4.5.5-c35cb8696d.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/tools/vcpkg/downloads/opencv-opencv_contrib-4.5.5.tar.gz
-- Applying patch 0007-fix-hdf5.patch
-- Applying patch 0016-fix-freetype-contrib.patch
-- Using source at C:/tools/vcpkg/buildtrees/opencv4/src/4.5.5-c35cb8696d.clean
-- Using cached opencv-cache/wechat_qrcode/238e2b2d6f3c18d6c3a30de0c31e23cf-detect.caffemodel.
-- Using cached opencv-cache/wechat_qrcode/cbfcd60361a73beb8c583eea7e8e6664-sr.caffemodel.
-- Using cached opencv-cache/wechat_qrcode/6fb4976b32695f9f5c6305c19f12537d-detect.prototxt.
-- Using cached opencv-cache/wechat_qrcode/69db99927a70df953b471daaba03fbef-sr.prototxt.
-- Using cached opencv-cache/xfeatures2d/boostdesc/0ea90e7a8f3f7876d450e4149c97c74f-boostdesc_bgm.i.
-- Using cached opencv-cache/xfeatures2d/boostdesc/232c966b13651bd0e46a1497b0852191-boostdesc_bgm_bi.i.
-- Using cached opencv-cache/xfeatures2d/boostdesc/324426a24fa56ad9c5b8e3e0b3e5303e-boostdesc_bgm_hd.i.
-- Using cached opencv-cache/xfeatures2d/boostdesc/202e1b3e9fec871b04da31f7f016679f-boostdesc_binboost_064.i.
-- Using cached opencv-cache/xfeatures2d/boostdesc/98ea99d399965c03d555cef3ea502a0b-boostdesc_binboost_128.i.
-- Using cached opencv-cache/xfeatures2d/boostdesc/e6dcfa9f647779eb1ce446a8d759b6ea-boostdesc_binboost_256.i.
-- Using cached opencv-cache/xfeatures2d/boostdesc/0ae0675534aa318d9668f2a179c2a052-boostdesc_lbgm.i.
-- Using cached opencv-cache/xfeatures2d/vgg/e8d0dcd54d1bcfdc29203d011a797179-vgg_generated_48.i.
-- Using cached opencv-cache/xfeatures2d/vgg/7126a5d9a8884ebca5aea5d63d677225-vgg_generated_64.i.
-- Using cached opencv-cache/xfeatures2d/vgg/7cd47228edec52b6d82f46511af325c5-vgg_generated_80.i.
-- Using cached opencv-cache/xfeatures2d/vgg/151805e03568c9f490a5e3a872777b75-vgg_generated_120.i.
-- Using cached opencv-cache/data/7505c44ca4eb54b4ab1e4777cb96ac05-face_landmark_model.dat.
-- Found external ninja('1.10.2').
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:128 (message):
    Command failed: ninja -v
    Working Directory: C:/tools/vcpkg/buildtrees/opencv4/x86-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\tools\vcpkg\buildtrees\opencv4\config-x86-windows-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:415 (vcpkg_execute_required_process)
  ports/opencv4/portfile.cmake:402 (vcpkg_cmake_configure)
  scripts/ports.cmake:145 (include)

Error: Building package opencv4:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+opencv4
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[opencv4]+Build+error
including:
  package: opencv4[contrib,core,cuda,default-features,dnn,jpeg,png,quirc,tiff,webp]:x86-windows -> 4.5.5
    vcpkg-tool version: 2022-03-09-1affd32f93b299d5a907816c328ca3ededb73a7e
    vcpkg-scripts version: 773516ecf 2022-03-28 (14 hours ago)

Additionally, attach any relevant sections from the log files above.

**Additional context**
[config-x86-windows-out.log](https://github.com/microsoft/vcpkg/files/8372558/config-x86-windows-out.log)
sue.

**Comment by LilyWangLL** [comment]
I find a similar issue: https://github.com/opencv/opencv_contrib/issues/1478, there a solution on this issue: https://stackoverflow.com/questions/46584000/cmake-error-variables-are-set-to-notfound
I can't confirm this issue is a port bug or upstream issue. cc @cenit Could you help confirm this issue? Thanks in advance.

**Comment by cenit** [comment]
CUDA_nppi_LIBRARY has been deprecated from cuda and that was a problem back in the days. Your linked issue @LilyWangLL is not valid unfortunately. Here library is a different one and maybe it has been omitted from installation. 
For original poster issue, i'd say that the main issue is a broken cuda installation. First error is when detecting cuda version at the beginning of the cmake run, where it says that it has found version 11.6 but it's missing native archs...

**Comment by shuchincn** [comment]
> CUDA_nppi_LIBRARY has been deprecated from cuda and that was a problem back in the days. Your linked issue @LilyWangLL is not valid unfortunately. Here library is a different one and maybe it has been omitted from installation. For original poster issue, i'd say that the main issue is a broken cuda installation. First error is when detecting cuda version at the beginning of the cmake run, where it says that it has found version 11.6 but it's missing native archs...

Thanks for your suggestion, it really works.  I changed the architecture of OpenCV to x64-Windows, and finally the compilation was successful.  I searched for this issue [link](https://forums.developer.nvidia.com/t/x86-32-bit-support-for-cuda-to-build-32bit-opencv/107313) and it seems to require setting additional environment variables to make CUDA work for programs compiled for x86 architecture.

**Comment by cenit** [comment]
there are no more cublas, cufft, npp etc libraries in 32bit version, so there is no way to build 32bit cuda-enabled opencv, sorry

we should add a support clause to cuda port, stating that it does not  support x86 anymore (cross-compiler from 64bit to 32bit is there, but libraries no more). In this way vcpkg would have told you that the request was impossible to satisfy because a dependency was missing

**Comment by cenit** [comment]
only other option is to downgrade cuda a lot (< v7 maybe?) and use that
