### ISSUE TITLE
Pull request CI ignores baseline records

### ISSUE THREAD

**Issue by dg0yt** [microsoft/vcpkg#23862]
The PR CI now ignores the baseline records, i.e. it builds ports which are known to fail, resulting in unexpected passes for some ports and in unexpected failures (which should be cascade) in depending ports.
Evidence:
https://dev.azure.com/vcpkg/public/_build/results?buildId=69660
(qtinterfaceframework is "fail" since #23837)
https://dev.azure.com/vcpkg/public/_build/results?buildId=69648
(ompl:x64-osx is "fail", omplapp is cascade)

CC @BillyONeal.

**Comment by dg0yt** [comment]
If I observe and understand correctly this issue also drags [the 2 h llvm:x64-windows build caching issue](https://github.com/microsoft/vcpkg/issues/21905#issuecomment-1013422776) into more PRs than before.
CC @BillyONeal

**Comment by BillyONeal** [comment]
Your parent-hashes work is so effective we didn't notice 😅
