### ISSUE TITLE
[bzip2] Build error

### ISSUE THREAD

**Issue by wujilingfeng** [microsoft/vcpkg#23861]
**Host Environment**
- OS: windows10
- vcpkg : 2022-03-25
I don't quite understand what went wrong, so I can only post a picture.
When I run command like `vcpkg install boost-iostreams`

![屏幕截图 2022-03-30 110657](https://user-images.githubusercontent.com/35684738/160743504-950fdba0-f250-449e-a464-b1fc0bfc3ca9.png)

**Comment by JonLiu1993** [comment]
@wujilingfeng ,Thanks for posting this issue, This error is you are not run vcpkg script please run command " .\bootstrap-vcpkg.bat " and try again

**Comment by JonLiu1993** [comment]
@wujilingfeng ,Is this still a problem for you?

**Comment by JonLiu1993** [comment]
@wujilingfeng ,Thanks for posting this issue. Please reopen this issue if it still be a problem for you.
