### ISSUE TITLE
[New Port Request] <llgc>

### ISSUE THREAD

**Issue by VanityNie** [microsoft/vcpkg#23876]
Library name:
llgl:x64-windows
Library description:
Low Level Graphics Library (LLGL) is a thin abstraction layer for the modern graphics APIs OpenGL, Direct3D, Vulkan, and Metal
Source repository URL:
https://github.com/LukasBanana/LLGL
Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
In vcpkg the lib version is old , the version is publish in 2019, but the lib has update, I hope add the new version

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
