### ISSUE TITLE
Vcpkg fails when trying to extract downloaded tools from vcpkgTools.xml

### ISSUE THREAD

**Issue by cyrus-jackson** [microsoft/vcpkg#23875]
**Describe the bug**
vcpkg fails most of the time when required tools (with suitable versions) are not found. Tools like 7zip, powershell-core, cmake etc... (These tools are mentioned in scripts/vcpkgTools.xml). It happens so often in our azure build pipelines. 

Here is the error message 

```
6b6f5a82de4ece1d4e604dfc813632139bf5259e
Downloading https://github.com/microsoft/vcpkg-tool/releases/download/2022-03-09/vcpkg.exe -> C:\__w\1\s\deps\vcpkg\vcpkg.exe... done.
Validating signature... done.

Telemetry
---------
vcpkg collects usage data in order to help us improve your experience.
The data collected by Microsoft is anonymous.
You can opt-out of telemetry by re-running the bootstrap-vcpkg script with -disableMetrics,
passing --disable-metrics to vcpkg on the command line,
or by setting the VCPKG_DISABLE_METRICS environment variable.

Read more about vcpkg telemetry at docs/about/privacy.md
        1 file(s) copied.
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.
All installed packages are up-to-date with the local portfiles.
Computing installation plan...
The following packages will be built and installed:
    azure-storage-cpp[core]:x64-windows-static-bs -> 7.5.0#3
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows-static-bs...
A suitable version of powershell-core was not found (required v7.2.1). Downloading portable powershell-core v7.2.1...
Downloading powershell-core...
  https://github.com/PowerShell/PowerShell/releases/download/v7.2.1/PowerShell-7.2.1-win-x86.zip -> C:\__w\1\s\deps\vcpkg\downloads\PowerShell-7.2.1-win-x86.zip
Extracting powershell-core...
D:\a\_work\1\s\src\vcpkg\archives.cpp(237): rename_with_retry("C:\__w\1\s\deps\vcpkg\downloads\tools\powershell-core-7.2.1-windows.partial.11288", "C:\__w\1\s\deps\vcpkg\downloads\tools\powershell-core-7.2.1-windows"): Access is denied.
```

Here the bootstrap script failed as it could not rename powershell-core-7.2.1-windows.partial.11288 for some reason. Upon cross checking the file it is fully downloaded but it seems like its failing at extraction stage. However, it does pass for 2/10 times in our build pipelines. 

**Environment**
- OS: Windows

**To Reproduce**
1. call bootstrap-vcpkg.bat
2. The script tries to download the tools.
3. Once the download is complete it moves to extraction stage where the error happens. 

**Expected behavior**
The bootstrap-vcpkg.bat should download and extract the files from vcpkgTools.xml without throwing error. 

**Additional context**
As a workaround, I had to write a powershell script which downloads these required tools and rename them in this format `name-version-targetOs` and extract them in vcpkg/downloads/tools folder so that it skips this part and proceeds with the next step.

**Comment by JackBoosY** [comment]
Yeah, we know this issue but we can hardly reproduce this.
The workaround is to run the command again.

**Comment by dg0yt** [comment]
Maybe that's the usual anti-virus experience?

**Comment by trebconnell** [comment]
Our team is also hitting this in Azure Build Pipeline frequently.  It started happening when we updated vcpkg from commit hash
633f3e0c130a466beadb1f0cbd3ae3c55859565a - 13 Dec 2021
to
27fd32e91c172e8b8a2ee338efc088a0c0103348 - 31 Mar 2022

It was a pretty far jump, but perhaps that can help narrow things down a bit.  If there's any additional info I can collect let me know.  We'll probably implement the aforementioned workaround in the meantime.

**Comment by JackBoosY** [comment]
cc @BillyONeal

**Comment by BillyONeal** [comment]
I agree, this looks like A/V interaction and I'm not sure there's much vcpkg can do here. However, let's see if we can diagnose here.

>Here the bootstrap script failed as it could not rename powershell-core-7.2.1-windows.partial.11288 for some reason.

I'm not sure I agree with this diagnosis; all the text after "Read more about vcpkg telemetry at docs/about/privacy.md" is not coming from our bootstrap script, since that's the last thing that prints:

https://github.com/microsoft/vcpkg/blob/27fd32e91c172e8b8a2ee338efc088a0c0103348/scripts/bootstrap.ps1#L72-L82

There have to be some other commands run there, can you let us know what those are?


I note one other thing; I don't think this will fix anything but just in case:

> [27fd32e](https://github.com/microsoft/vcpkg/commit/27fd32e91c172e8b8a2ee338efc088a0c0103348) - 31 Mar 2022

[...]

> https://github.com/microsoft/vcpkg-tool/releases/download/2022-03-09/vcpkg.exe

That copy of vcpkg.exe looks too old; 31 Mar 2022 wants the tool release 2022-03-30: https://github.com/microsoft/vcpkg/blob/27fd32e91c172e8b8a2ee338efc088a0c0103348/scripts/bootstrap.ps1#L48

**Comment by trebconnell** [comment]
In my case this is happening as a result of this command:
```
  vcpkg install gtest --triplet=x64-windows --only-downloads --x-packages-root={pkg_root} --x-install-root={install_root} --x-buildtrees-root={bldtree_root}
```

Could we perhaps get a flag or environment variable to increase the number of retries for this rename?

**Comment by shaonms** [comment]
Having the same issue after updating vcpkg package to latest `af22873`.

```
A suitable version of powershell-core was not found (required v7.2.1). Downloading portable powershell-core v7.2.1...
Downloading powershell-core...
  https://github.com/PowerShell/PowerShell/releases/download/v7.2.1/PowerShell-7.2.1-win-x86.zip -> C:\__w\1\s\vcpkg\downloads\PowerShell-7.2.1-win-x86.zip
Extracting powershell-core...
D:\a\_work\1\s\src\vcpkg\archives.cpp(237): rename_with_retry("C:\__w\1\s\vcpkg\downloads\tools\powershell-core-7.2.1-windows.partial.12028", "C:\__w\1\s\vcpkg\downloads\tools\powershell-core-7.2.1-windows"): Access is denied.
"Install vcpkg packages end"
"Failed to restore correctly."
"Restore working directory"
##[error]Cmd.exe exited with code '1'.```

**Comment by trebconnell** [comment]
It does seem like this did start happening as the result of some commit, otherwise I'd assume it was just an A/V issue.  

I poked around the change log of relevant files, but I can't see what might've done it (though I'm not very familiar with the code).  I may try binary searching commits to see if I can find which commit it started on.

**Comment by trebconnell** [comment]
I binary searched commits and was able to determine that this started happening with tool version 2022-03-08.  It doesn't reproduce on 2022-03-03.  Looking at the commits between these 2, it seems very likely that the commit where this started was 7dfebffb2b25c0fda564dd60346d9c9674475f7f where extract_tar_cmake is used to extract zips instead of                 win32_extract_with_seven_zip/extract_tar.

Could just be a timing difference between the two, or if CMake is doing something crazy like creating a sub-process that's longer running than the parent process and holds onto the file handle.

**Comment by BillyONeal** [comment]
> Could just be a timing difference between the two, or if CMake is doing something crazy like creating a sub-process that's longer running than the parent process and holds onto the file handle.

Or it could be that AV tools just see different unzippers differently. It isn't because it's held onto by another process though; that would be `ERROR_SHARING_VIOLATION` rather than `ERROR_ACCESS_DENIED`.

**Comment by shaonms** [comment]
While this remains an issue, is there an alternative that you guys can suggest? I am on the same boat as @trebconnell, our Azure Pipeline builds are failing consistently.

**Comment by trebconnell** [comment]
There is the workaround Cyrus suggested in the OP of manually downloading and extracting powershell prior to invoking vcpkg install.  I'm planning to implement this today or tomorrow and can drop code here if you want.

**Comment by shaonms** [comment]
> Can also use vcpkg commit [5962cf5](https://github.com/microsoft/vcpkg/commit/5962cf5a3bfc2124e8de991a4e45a8edcb3b4c69) or earlier, which aren't affected.

Unfortunately, that's not working for me either, still getting same error. Also, what's up with vcpkg tags, why are they all same?

![image](https://user-images.githubusercontent.com/90572132/163024174-35aedcc7-58a0-4119-94c4-ba1e85fdd7c0.png)

**Comment by BillyONeal** [comment]
> Unfortunately, that's not working for me either, still getting same error. Also, what's up with vcpkg tags, why all the commit hashes are same?

Hmmmmmm when I went and created all the previous releases maybe I messed that up... O_O

**Comment by tomaspoupin** [comment]
Is there any update on this issue? I get the same error when trying to use manifest mode with cmake on Windows 10.

```
cmake.exe -B .\build\ -S . -DCMAKE_TOOLCHAIN_FILE="C:\GIT\cpluscore\vcpkg\scripts\buildsystems\vcpkg.cmake"
```
and get the following output.

```
-- Running vcpkg install
Detecting compiler hash for triplet x86-windows...
A suitable version of powershell-core was not found (required v7.2.1). Downloading portable powershell-core v7.2.1...
Extracting powershell-core...
D:\a\_work\1\s\src\vcpkg\archives.cpp(242): rename_with_retry("C:\GIT\cpluscore\vcpkg\downloads\tools\powershell-core-7.2.1-windows.partial.19844", "C:\GIT\cpluscore\vcpkg\downloads\tools\powershell-core-7.2.1-windows"): Access is denied.
```

**Comment by anluoma** [comment]
Same here with Windows 11

**Comment by fhwustc** [comment]
A way works for me is updating Windows Powershell manually.
Run Windows Powershell as administrator, then input `iex "& { $(irm https://aka.ms/install-powershell.ps1) } -UseMSI"`, install the latest Windows Powershell then rerun `vcpkg install xxx`

**Comment by trebconnell** [comment]
Here's the powershell code I use to extract manually before I run vcpkg install.  It seems to be working so far but if it starts hitting AV failures it would need retries added.
```Powershell
# Download and extract powershell manually because vcpkg hits random AV related rename failures when it tries.
$vcpkgRepoDir = "{your_repo_dir}"
$pwshVer = "7.2.3"
$zipName = "PowerShell-$pwshVer-win-x86.zip"
$downloadDir = "$vcpkgRepoDir\downloads"
$toolsDir = "$downloadDir\tools"

$pwshZipPath = "$downloadDir\$zipName"
$pwshFolderPath = "$toolsDir\powershell-core-$pwshVer-windows"
$needZip = -not (Test-Path $pwshZipPath)
if ($needZip)
{
  New-Item $downloadDir -ItemType Directory | Out-Null
  Write-Host "Downloading Powershell $pwshVer"
  Invoke-WebRequest -Uri "https://github.com/PowerShell/PowerShell/releases/download/v$pwshVer/$zipName" -OutFile $pwshZipPath
}
if ($needZip -or -not (Test-Path $pwshFolderPath))
{
  New-Item $toolsDir -ItemType Directory | Out-Null
  Expand-Archive $pwshZipPath "$pwshFolderPath-tmp" -Force
  Rename-Item "$pwshFolderPath-tmp" "$pwshFolderPath" -Force
}
```

**Comment by BillyONeal** [comment]
Thanks for the catch @JackBoosY :)
