### ISSUE TITLE
[<SDL2>] build failure

### ISSUE THREAD

**Issue by DeafMan1983** [microsoft/vcpkg#23873]
**Host Environment**
- OS: Windows
- Compiler: MSVC 2022 

**To Reproduce**
`./vcpkg install sdl2:x64-windows`
It works fine ok

But in Visual Studio 2022 COmmunity and I create emptry project then it can't build success

c++ -> include directory path to installed/x64-windows/include
linker addional directory path to installed/x64-windows/lib
linker inputs:
SDL2.lib
glew32.lib

**Failure logs**
![image](https://user-images.githubusercontent.com/57066679/160816483-fda7c4fd-81f8-4e17-8232-c6c3a54eeaa9.png)

**Additional context**
I have tried to reesolve release build version from libsdl.org but nothing successfully.

PS: Please stop annoying my success with SDL2 + GLEW - I will be mad because error ruined my exercise. And my Half-Life fans are waiting for me because I develop right with Renderer :(  

I found SDL2main.lib because it resolved my problem but vcpkg can't generate SDL2main.lib that is why from libsdl and I don't know before "SDL2main.lib" - I thought it is old and unusable and now Visual C++ 2019 builds successful with SDL2main.lib from libsdl website.

**Comment by DeafMan1983** [comment]
Hello @StarGate-One I have tried
but Visual STudio C++ builds with error.
![image](https://user-images.githubusercontent.com/57066679/160937506-3a631e2d-6719-463f-aced-940cf48a8c32.png)

![image](https://user-images.githubusercontent.com/57066679/160937645-25668550-2da4-430c-8c82-640badcd8578.png)

in last picture has nothing error lines - they have not issues but I have tried vcpkg build and copy to LearningSDL2withGLEW/libraries
for include:
![image](https://user-images.githubusercontent.com/57066679/160938003-974a081b-1e57-419a-ae0e-0d0bf32206a3.png)

for lib:
![image](https://user-images.githubusercontent.com/57066679/160938092-a3f7c18d-8f6e-42d4-9133-938c0b539f2f.png)

I use complete x64 Bit.

I never change to x86 Bit
![image](https://user-images.githubusercontent.com/57066679/160938254-073e1c8c-0c2c-44ae-8fed-b1c1b5fcab6f.png)
![image](https://user-images.githubusercontent.com/57066679/160938303-bf74b10a-1598-411e-8aba-d3dd45454dbd.png)

That is proof because Visual C++ builds failing why does it happen from vcpkg can't build complete like public methods are gone or library are unusable?

Thanks

**Comment by StarGate-One** [comment]
I use vcpkg  with the SDL2 ports for triplet x64-windows in my projects and they compile/link/execute as designed.

I see nothing in errors about x86 (32-bit).

The first post shows errors with SDL2 triplet x64-windows and the second post appears to be port GLEW triplet x64-windows-static???

**Comment by DeafMan1983** [comment]
First post uses x64-windows-static then second post I tell you why do I try to resolve problem with static then it throws errors and I try to generate in x64-windows-release and my end is same failed. I have followed like vcpkg install <package>:x64-windows-static and copy from vcpkg buildtrees, past to my working directory and create new empty project in Visual Studio 2019 Community and add new main.cpp then configure with include path like I told in 1 post and library path too then I code simple! Lazy Foo website. But I never changed wrong architecture or build - I use only release and x64 .

But I don't understand why does it happen with vcpkg. I have downloaded from github to C:\vcpkg then build and compilation are successful and don't have any errors. But my C:\ is already writable for current user ( that's me ) I checked command lines and it doesn't have any error lines and generates successfully. And that was this.

**Comment by StarGate-One** [comment]
I am unable to assist further as using SDL2 with GLEW is beyond my purview, maybe one of the other more knowledgeable users of vcpkg can assist as they have time, but a few things that could cause issues:
1. Did you `download` the zip file of vcpkg or did you `git clone` the package  - my experience is cloning is way better than trying to build anything from the downloaded source.
2. Did you do a `vcpkg integrate install`, best I can remember is `vcpkg` can only be integrated with one instance of visual studio, from reading here there seems to be VS2019 and VS2022 installed, so I am unsure which one it would integrate with?
3. If you did clone vcpkg have you done a `git pull` against the repo to update it with the latest information.
4. Triplet x64-windows-release is community driven, supported by the community, volunteers who answer help resolve issues with those triplets on their own time, not the vcpkg sponsors/authors (Microsoft).
5. Putting vcpkg on C:\ can cause all sorts of issues and C:\ is the system drive and windows, antivirus software, protect the drive differently not to mention hidden permissions not readily visible (my instance is on D:\)
6. Other things like too long a path, special characters and/or spaces in the path, not especially vcpkg, but many of the utilities used by vcpkg are UNIX derivatives meaning they are not very friendly where special characters, spaces or long path names are involved.

Maybe soon someone else with more expertise can assist, hopefully someone with SDL2 with GLEW experience.

**Comment by StarGate-One** [comment]
I was offering assistance to the best of my abilities, sorry if it does not meet the standards you are accustomed.

I do not follow links to youtube, pastebin, etc as it is considered a security risk and in general bad online practice.

Again wish you well and hopefully someone with more knowledge/abilities than I will assist you.

**Comment by DeafMan1983** [comment]
> I do not follow links to youtube, pastebin, etc as it is considered a security risk and in general bad online practice.
Wow you ignored my proof because i have tried to explain how do I show you to video about i have captured with OBS on my desktop - That is not risk. It is normal video platform. If you ignore me to watch my proof then I will block you whatever I will go other people on Microsoft VCPKG

I am very disappointed because you don't expect that I show proof.
`64-windows-release
Computing installation plan...
The following packages will be built and installed:
    sdl2[core]:x64-windows-release -> 2.0.20#1
  * vcpkg-cmake[core]:x64-windows -> 2022-02-14
  * vcpkg-cmake-config[core]:x64-windows -> 2022-02-06
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Detecting compiler hash for triplet x64-windows-release...
A suitable version of 7zip was not found (required v21.7.0). Downloading portable 7zip v21.7.0...
Downloading 7zip...
  https://www.7-zip.org/a/7z2107-extra.7z -> C:\vcpkg\downloads\7z2107-extra.7z
Extracting 7zip...
Restored 2 packages from C:\Users\Jens\AppData\Local\vcpkg\archives in 799.8 ms. Use --debug to see more details.
Starting package 1/3: vcpkg-cmake:x64-windows
Installing package vcpkg-cmake[core]:x64-windows...
Elapsed time for package vcpkg-cmake:x64-windows: 113.9 ms
Starting package 2/3: vcpkg-cmake-config:x64-windows
Installing package vcpkg-cmake-config[core]:x64-windows...
Elapsed time for package vcpkg-cmake-config:x64-windows: 26.4 ms
Starting package 3/3: sdl2:x64-windows-release
Building package sdl2[core]:x64-windows-release...
-- Using community triplet x64-windows-release. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: C:\vcpkg\triplets\community\x64-windows-release.cmake
-- Downloading https://github.com/libsdl-org/SDL/archive/release-2.0.20.tar.gz -> libsdl-org-SDL-release-2.0.20.tar.gz...
-- Extracting source C:/vcpkg/downloads/libsdl-org-SDL-release-2.0.20.tar.gz
-- Applying patch 0001-sdl2-Enable-creation-of-pkg-cfg-file-on-windows.patch
-- Applying patch 0002-sdl2-skip-ibus-on-linux.patch
-- Applying patch 0003-sdl2-disable-sdlmain-target-search-on-uwp.patch
-- Applying patch 0004-Define-crt-macros.patch
-- Applying patch 0005-Fix-uwp-joystick.patch
-- Applying patch 0006-Update-SDL_sysurl.cpp.patch
-- Applying patch 0007-timer-Fix-Emscripten-declaration-after-statement-err.patch
-- Using source at C:/vcpkg/buildtrees/sdl2/src/ase-2.0.20-870b37d4f3.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows-release
-- Building x64-windows-release-rel
-- Fixing pkgconfig file: C:/vcpkg/packages/sdl2_x64-windows-release/lib/pkgconfig/sdl2.pc
-- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst;https://www2.futureware.at/~nickoe/msys2-mirror/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst;https://mirror.yandex.ru/mirrors/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst;https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst;https://mirrors.ustc.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst;https://mirror.bit.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst;https://mirror.selfnet.de/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst;https://mirrors.sjtug.sjtu.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst -> msys-mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst...
-- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst;https://www2.futureware.at/~nickoe/msys2-mirror/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst;https://mirror.yandex.ru/mirrors/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst;https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst;https://mirrors.ustc.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst;https://mirror.bit.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst;https://mirror.selfnet.de/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst;https://mirrors.sjtug.sjtu.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst -> msys-mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst...
-- Using msys root at C:/vcpkg/downloads/tools/msys2/9a1ec3f33446b195
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\Jens\AppData\Local\vcpkg\archives\41\4163105e1b165d5c1cd6d9aa4bd9528e94dd41d4bd4ec40ded82f87638e8fd7d.zip
Installing package sdl2[core]:x64-windows-release...
Elapsed time for package sdl2:x64-windows-release: 1.956 min`

But vcpkg can't detect to Visual Studio 2019 Community.

**Comment by JackBoosY** [comment]
The symbols should have prefix `__imp_` in dynamic build. So I assume this is a macro bug in vcpkg side.

**Comment by DeafMan1983** [comment]
@JackBoosY Oh really bug? Thanks how do we fix it?

**Comment by JackBoosY** [comment]
Please keep this issue open until we really fixed this or confirmed that this is not a bug in vcpkg side.

**Comment by DeafMan1983** [comment]
@JackBoosY Okay

I have resolved issue because _imp_ from library was gone and Visual Studio doesn't jump failures. Now It looks okay 
I have proof
![image](https://user-images.githubusercontent.com/57066679/160965357-cce8cc44-1b10-4c78-a18a-5b0858ddf5be.png)
It means successful compilation since prompting with .\bootstrap-vcpkg.bat and .\vcpkg integrate install

And I install package sdl from vcpkg closing and I checked if Visual Studio doesn't jump failures cause it has __imp__ as macro bug in vcpkg side. It looks like __imp__ is gone. Now Visual Studio said my compilation is successfully.

**Comment by dg0yt** [comment]
> Sorry I expect static has bug.

No, static doesn't have `_imp`. 

> I found SDL2main.lib because it resolved my problem but vcpkg can't generate SDL2main.lib that is why from libsdl and I don't know before "SDL2main.lib" - I thought it is old and unusable and now Visual C++ 2019 builds successful with SDL2main.lib from libsdl website.

It looks like this cause the prefix confusion. You probably started to use sdlmain.lib from the static build (symbols without prefix) with the headers for the dynamic lib, where the runtime part (DLL, .dll) is complemented by a build time part (import lib, .lib), and this import lib has the symbols with prefix.

**Comment by DeafMan1983** [comment]
That is bug in static

Look [my video](https://www.youtube.com/watch?v=fTx-qMebOhY)

dynamic is ok and static is failed

**Comment by dg0yt** [comment]
> That is bug in static
> 
> Look [my video](https://www.youtube.com/watch?v=fTx-qMebOhY)
> 
> dynamic is ok and static is failed

The video didn't invalidate but confirm my comment: It shows that you copy sdl2mail.lib from the static build to your project. Again:
`sdl2main.lib`, the static library, doesn't have the prefix.
`sdl2main.lib`, the import library from the dynamic build, has the prefix.
The required prefix is generated in the headers, either based on a definition which indicates dynamic linkage, or hard-coded (in most vcpkg ports, for easy use with integration). If you only copy the lib and change nothing else, there must be a prefix mismatch.

**Comment by DeafMan1983** [comment]
Thank you for explanation! I will let in rest with my issue :)
