### ISSUE TITLE
[boost-atomic] build failure on alpine linux due to missing headers

### ISSUE THREAD

**Issue by mprather** [microsoft/vcpkg#23888]
**Host Environment**
- OS: Alpine Linux 3.15.3
- Compiler: g++ (Alpine 10.3.1_git20211027) 10.3.1 20211027

**To Reproduce**

1. Install minimum set of system packages needed to run vcpkg on an alpine system.
2. git clone vckpg
3. set env variable VCPKG_FORCE_SYSTEM_BINARIES to 1
4. run bootstrap-vcpkg.sh (it pulls down the pre-build muslc binary of vcpkg)
5. Attempt to install boost-atomic

  > ./vcpkg install boost-atomic

vcpkg reports:
```
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:158 (message):
    Command failed: /usr/bin/cmake --build . --config Debug --target install -- -v -j9
    Working Directory: /src/vcpkg/buildtrees/boost-atomic/x64-linux-dbg
    See logs for more information:
      /src/vcpkg/buildtrees/boost-atomic/install-x64-linux-dbg-out.log
```

**Failure logs**
Output log shows root cause...
```
    "/usr/bin/c++"   -fPIC -g -m64 -pthread -O0 -fno-inline -Wall -g  -DBOOST_ALL_NO_LIB=1 -DBOOST_ATOMIC_SOURCE -DBOOST_ATOMIC_STATIC_LINK=1 -DBOOST_ATOMIC_USE_SSE2 -DBOOST_ATOMIC_USE_SSE41  -I"../include" -I"/src/vcpkg/installed/x64-linux/include" -I"../src"  -c -o "/src/vcpkg/buildtrees/boost-atomic/x64-linux-dbg/boost/build/599c3892010ad001b78ddcb47e1afb19/lock_pool.o" "../src/lock_pool.cpp"

In file included from ../include/boost/atomic/detail/platform.hpp:151,
                 from ../include/boost/atomic/detail/capabilities.hpp:18,
                 from ../include/boost/atomic/capabilities.hpp:18,
                 from ../src/lock_pool.cpp:33:
../include/boost/atomic/detail/futex.hpp:52:10: fatal error: linux/futex.h: No such file or directory
   52 | #include <linux/futex.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
```

**Additional context**
This problem can be resolved by adding a system package.

> apk add linux-headers

**Expectation**
The port should tell the user what system packages are missing, if any, in order to build the port.  For example, if you attempt to install openssl and the perl package is not installed, the user is presented with a cmake message indicating the package could not be found.

**Comment by PhoebeHui** [comment]
@mprather, thanks for reporting this issue!

I'm not sure if it's neccessary to add a message to boost-atmoic, I don't have this problem on ubuntu, the linux-headers looks installed on my machine by default, our CI test machines are same, so can I say the problem on specific alpine linux?

cc @yurybura   cc @BillyONeal

**Comment by mprather** [comment]
@PhoebeHui yes, this is an alpine only config issue. I imagine that since alpine tends to be a minimalist config, it tends steer away from large dependency trees like what you find on other distros. for example, on debian, those headers are provided by linux-libc-dev, which is needed by libstdc++-10-dev, needed by g++-10). on arch, those headers are managed by linux-api-header and dependency tree is different (linux-api-header->glibc->gcc-libs->gcc).

**Comment by BillyONeal** [comment]
I think adding a message to boost-atomic is reasonable.

**Comment by PhoebeHui** [comment]
I have submitted a PR #23921 to add the message to boost-atomic.
