### ISSUE TITLE
[qt-base] build failure on x64-windows-static-md

### ISSUE THREAD

**Issue by ylz-at** [microsoft/vcpkg#23905]
**Host Environment**
- OS: Windows10 21H2
- Compiler: VS2022 17.1.2 MSVC 19.31.31105.0

**To Reproduce**
`./vcpkg install qtbase`

**Failure logs**
```
CMake Deprecation Warning at scripts/ports.cmake:75 (message):
  vcpkg_apply_patches has been deprecated in favor of the `PATCHES` argument
  to `vcpkg_from_*`.
Call Stack (most recent call first):
  scripts/cmake/vcpkg_apply_patches.cmake:18 (z_vcpkg_deprecation_message)
  ports/libpq/portfile.cmake:132 (vcpkg_apply_patches)
  scripts/ports.cmake:145 (include)


-- Applying patch patches/windows/Solution_RELEASE.patch
-- Applying patch patches/windows/python3_build_RELEASE.patch
-- Patches applied!
-- Building libpq x64-windows-RELEASE...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:128 (message):
    Command failed: C:/vcpkg/downloads/tools/perl/5.32.1.1/perl/bin/perl.exe build.pl RELEASE libpq
    Working Directory: C:/vcpkg/buildtrees/libpq/x64-windows-rel/src/tools/msvc
    Error code: 1
    See logs for more information:
      C:\vcpkg\buildtrees\libpq\build-libpq-x64-windows-RELEASE-out.log
      C:\vcpkg\buildtrees\libpq\build-libpq-x64-windows-RELEASE-err.log

Call Stack (most recent call first):
  ports/libpq/portfile.cmake:229 (vcpkg_execute_required_process)
  scripts/ports.cmake:145 (include)


Error: Building package libpq:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libpq
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[libpq]+Build+error
including:
  package: libpq[core,lz4,openssl,zlib]:x64-windows -> 14.1
    vcpkg-tool version: 2022-03-25-d9702d9d89b9468c32efc3f18fb84c3021d7dbae
    vcpkg-scripts version: 9d9a6f486 2022-03-30 (14 hours ago)
```

[build-libpq-x64-windows-RELEASE-out.log](https://github.com/microsoft/vcpkg/files/8394186/build-libpq-x64-windows-RELEASE-out.log)
[build-libpq-x64-windows-RELEASE-err.log](https://github.com/microsoft/vcpkg/files/8394188/build-libpq-x64-windows-RELEASE-err.log)

**Additional context**
ENV: `VCPKG_DEFAULT_TRIPLET` = `x64-windows-static-md`
Triplet: `x64-windows-static-md`

**Comment by SchaichAlonso** [comment]
Hi

unless your triplet is setup via environment variables, the statement you provided to reproduce the issue will not use the `x64-windows-static-md` target. The port causing the build to abort is `libpq` rather then `qtbase`, which is a dependency of qtbase. According to the error diagnostic, `libpq` seems to be targeting `x64-windows` rather then `x64-windows-static-md`.

This issue is likely related to #23615 , though for a confirmation , please check the log files indicated in the diagnostic

  C:\vcpkg\buildtrees\libpq\build-libpq-x64-windows-RELEASE-out.log
  C:\vcpkg\buildtrees\libpq\build-libpq-x64-windows-RELEASE-err.log

for similarities to those provided in #23615 's [second comment](https://github.com/microsoft/vcpkg/issues/23615#issuecomment-1071991075)

**Comment by ylz-at** [comment]
@SchaichAlonso 
Yes, I am using VCPKG_DEFAULT_TRIPLET = x64-windows-static-md.

The output of ...RELEASE-out.log and ...RELEASE-err.log is updated to the description of the issue. 

It seem that `libpq` doesn't support VS2022 now.

**Comment by JackBoosY** [comment]
`error MSB8013: 此项目不包含配置和平台组合 Release|x64。`
>   error MSB8013: this project configuration doesn't contains config Release|x64。

**Comment by Osyotr** [comment]
@JackBoosY `x64-windows` is not a community triplet.

**Comment by JackBoosY** [comment]
@Osyotr See https://github.com/microsoft/vcpkg/issues/23905#issuecomment-1085338261, the default path is _x64-windows-static-md_.

**Comment by dg0yt** [comment]
Yes, x64-windows-static-md is a community triplet which is tested in vcpkg CI...

**Comment by ylz-at** [comment]
Problem solved by installing the English pack.
