### ISSUE TITLE
[gdal] Cross-compiling for arm64-osx-dynamic on macos results in library with wrong architecture

### ISSUE THREAD

**Issue by jorisvandenbossche** [microsoft/vcpkg#23919]
**Host Environment**
- OS: macOS 11.6.5 (macos-11 on github actions)
- Using the vcpkg provided by github actions

**To Reproduce**

```
vcpkg install gdal[core]:arm64-osx-dynamic
```

The post-build validation of the gdal install shows the message:

```
The following files were built for an incorrect architecture:
    /usr/local/share/vcpkg/packages/gdal_arm64-osx-dynamic/debug/lib/libgdal.30.dylib
Expected arm64, but was: x86_64
```

So the library was not actually built for arm64 architecture.

Is this actually expected to work? (from searching for others issues, it seems that in general cross-compiling like this is supported?) Or is there some configuration / setup that I might be missing? Or could it be a bug in the port for this specific (untested) case?

**Failure logs**

The last part of the build log shows:

```
Starting package 26/26: gdal:arm64-osx-dynamic
Building package gdal[core]:arm64-osx-dynamic...
-- Using community triplet arm64-osx-dynamic. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: /usr/local/share/vcpkg/triplets/community/arm64-osx-dynamic.cmake
-- Downloading https://github.com/OSGeo/gdal/archive/v3.4.2.tar.gz -> OSGeo-gdal-v3.4.2.tar.gz...
-- Extracting source /usr/local/share/vcpkg/downloads/OSGeo-gdal-v3.4.2.tar.gz
-- Applying patch 0001-Fix-debug-crt-flags.patch
...
-- Using source at /usr/local/share/vcpkg/buildtrees/gdal/src/v3.4.2-58b4d4653a.clean
-- Getting CMake variables for arm64-osx-dynamic-dbg
-- Getting CMake variables for arm64-osx-dynamic-rel
-- Generating configure for arm64-osx-dynamic
-- Finished generating configure for arm64-osx-dynamic
-- Configuring arm64-osx-dynamic-dbg
-- Configuring arm64-osx-dynamic-rel
-- Building arm64-osx-dynamic-dbg
-- Installing arm64-osx-dynamic-dbg
-- Building arm64-osx-dynamic-rel
-- Installing arm64-osx-dynamic-rel
-- Fixing pkgconfig file: /usr/local/share/vcpkg/packages/gdal_arm64-osx-dynamic/lib/pkgconfig/gdal.pc
-- Fixing pkgconfig file: /usr/local/share/vcpkg/packages/gdal_arm64-osx-dynamic/debug/lib/pkgconfig/gdal.pc
-- Installing: /usr/local/share/vcpkg/packages/gdal_arm64-osx-dynamic/share/gdal/usage
-- Installing: /usr/local/share/vcpkg/packages/gdal_arm64-osx-dynamic/share/gdal/copyright
-- Performing post-build validation
The following files were built for an incorrect architecture:

    /usr/local/share/vcpkg/packages/gdal_arm64-osx-dynamic/debug/lib/libgdal.30.dylib
Expected arm64, but was: x86_64


    /usr/local/share/vcpkg/packages/gdal_arm64-osx-dynamic/debug/lib/libgdal.dylib
Expected arm64, but was: x86_64


    /usr/local/share/vcpkg/packages/gdal_arm64-osx-dynamic/lib/libgdal.30.dylib
Expected arm64, but was: x86_64


    /usr/local/share/vcpkg/packages/gdal_arm64-osx-dynamic/lib/libgdal.dylib
Expected arm64, but was: x86_64


Found 1 post-build check problem(s). To submit these ports to curated catalogs, please first correct the portfile:
    /usr/local/share/vcpkg/ports/gdal/portfile.cmake
-- Performing post-build validation done
Stored binary cache: /Users/runner/.cache/vcpkg/archives/35/35259b3067328ae8b8f98c8177b6444777d406ae0b17b0bee18d362432946b4b.zip
Installing package gdal[core]:arm64-osx-dynamic...
```

Full log of the vcpkg install step: [5_Install GDAL.txt](https://github.com/microsoft/vcpkg/files/8396798/5_Install.GDAL.txt) (github actions workflow log: https://github.com/geopandas/pyogrio/runs/5782969501?check_suite_focus=true, from https://github.com/geopandas/pyogrio/pull/64/)

**Comment by dg0yt** [comment]
> Is this actually expected to work?

`arm64-osx-dynamic` is at least untested. And from the point where port gdal was one year ago, I would say it is expected. Cross-building should work from linux to mingw. But between the two mac CPUs... 

The current port (3.4.x) uses autotools for mac.
There is WIP to immediately switch to CMake with GDAL 3.5: #22392
Try and report ... YMMV

**Comment by jorisvandenbossche** [comment]
Thanks for the quick reply! Will try to give the WIP CMake PR a go.

> But between the two mac CPUs...

Cross-compiling GDAL itself should work I think, since AFAIK that's what conda-forge does to produce osx arm64 binaries (but how to achieve this with vcpkg is something else .. and probably requires more configuration than a basic `vcpkg install`)

**Comment by Adela0814** [comment]
@jorisvandenbossche  This PR has been merged, could you please pull the latest `vcpkg` and try again.

**Comment by larsoner** [comment]
Locally on my Intel mac the following now succeeds:
```
$ mkdir temp
$ git clone https://github.com/Microsoft/vcpkg.git --depth=1
$ ./vcpkg/bootstrap-vcpkg.sh
$ ./vcpkg/vcpkg install hdf5:arm64-osx-dynamic
...
Elapsed time to handle gdal:arm64-osx-dynamic: 5.239 min

Total elapsed time: 12.02 min

The package GDAL provides CMake targets:

    find_package(GDAL CONFIG REQUIRED)
    target_link_libraries(main PRIVATE GDAL::GDAL)
```

**Comment by dg0yt** [comment]
Can this issue be closed now?

**Comment by jorisvandenbossche** [comment]
A bit late, but I can confirm that after updating GDAL to the latest port version so it is now using the new CMake build from GDAL, everything seems to work fine to cross-compile for arm64
