### ISSUE TITLE
[cudnn] Build error

### ISSUE THREAD

**Issue by NisreenAlaas** [microsoft/vcpkg#23925]
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Restored 0 packages from C:\Users\nasreen\AppData\Local\vcpkg\archives in 29.68 ms. Use --debug to see more details.
Starting package 1/32: cudnn:x64-windows
Building package cudnn[core]:x64-windows...
-- Found CUDA V11.6.124
-- CUDNN_INCLUDE_DIR: CUDNN_INCLUDE_DIR-NOTFOUND
-- CUDNN_LIBRARY: CUDNN_LIBRARY-NOTFOUND
CMake Error at ports/cudnn/portfile.cmake:69 (message):
  Please download CUDNN from official sources (such as
  https://developer.nvidia.com/rdp/cudnn-download ) and extract the zip into
  your CUDA_TOOLKIT_ROOT (C:/Program Files/NVIDIA GPU Computing
  Toolkit/CUDA/v11.6).  (For example: tar.exe -xvf
  cudnn-11.2-windows-x64-v8.1.1.33.zip --strip 1 --directory "C:/Program
  Files/NVIDIA GPU Computing Toolkit/CUDA/v11.6"
Call Stack (most recent call first):
  scripts/ports.cmake:145 (include)

error: building cudnn:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
 package: cudnn[core]:x64-windows -> 7.6.5#4
    vcpkg-tool version: 2022-03-30-692785ac944e81417840c6de244fb3e18a4b35eb
    vcpkg-scripts version: 27fd32e91 2022-03-31 (13 hours ago)

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Please download CUDNN as the log:
```
CMake Error at ports/cudnn/portfile.cmake:69 (message):
Please download CUDNN from official sources (such as
https://developer.nvidia.com/rdp/cudnn-download ) and extract the zip into
your CUDA_TOOLKIT_ROOT (C:/Program Files/NVIDIA GPU Computing
Toolkit/CUDA/v11.6). (For example: tar.exe -xvf
cudnn-11.2-windows-x64-v8.1.1.33.zip --strip 1 --directory "C:/Program
Files/NVIDIA GPU Computing Toolkit/CUDA/v11.6"
```

**Comment by JackBoosY** [comment]
According to the official document, please copy the CUDNN folder to _CUDA_PATH_ first.

**Comment by NisreenAlaas** [comment]
@JackBoosY Could you discuss it in more clear detail, I found that my laptop did not support GPU and I need to download vcpkg .. do I need to download vcpkg in the Visual studio code folder or in any folder .. please guide me I need to download darknet to test my model.

**Comment by JackBoosY** [comment]
@NisreenAlaas Look at this code:
https://github.com/microsoft/vcpkg/blob/e809a42f87565e803b2178a0c11263f462d1800a/ports/cudnn/portfile.cmake#L22

You should unzip the CUDNN package and put it into CUDA_HOME.

**Comment by LilyWangLL** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
