### ISSUE TITLE
[New Port Request] ClipboardXX

### ISSUE THREAD

**Issue by BullyWiiPlaza** [microsoft/vcpkg#23938]
Library name: ClipboardXX
Library description: Header only, lightweight and cross platform C++ library for copy and paste text from clipboard.
Source repository URL: https://github.com/Arian8j2/ClipboardXX

Kindly extract my `clipboardxx.zip` archive into the `ports` directory and test whether my port is fine:
[clipboardxx.zip](https://github.com/microsoft/vcpkg/files/8402106/clipboardxx.zip)

Then consider committing it to the master branch since my fork is conflicted. Thank you very much. 👍

**Comment by Pospelove** [comment]
huh, that's cute, I've created a PR with your files (fixed a bit)
you may want to delete your fork and re-create @BullyWiiPlaza

**Comment by BullyWiiPlaza** [comment]
> huh, that's cute, I've created a PR with your files (fixed a bit) you may want to delete your fork and re-create @BullyWiiPlaza
Thanks, I still need my fork for another pull request how it seems since it wasn't merged yet.
