### ISSUE TITLE
execute  .\vcpkg\bootstrap-vcpkg.bat problem

### ISSUE THREAD

**Issue by WinterOfMaple2016** [microsoft/vcpkg#23937]
Downloading https://github.com/microsoft/vcpkg-tool/releases/download/2022-03-25/vcpkg.exe -> C:\Users\v-huxiu\vcpkg\vcpkg.exe... done.
Validating signature... failed! 0x800B0111 Deleted!

**Comment by JackBoosY** [comment]
Please use proxy and try again. The downloaded data was broken.

**Comment by WinterOfMaple2016** [comment]
try again, Same as the last question

**Comment by WinterOfMaple2016** [comment]
> Please use proxy and try again. The downloaded data was broken.

try again, Same as the last question

**Comment by JackBoosY** [comment]
@WinterOfMaple2016 Please directly download [this link](https://github.com/microsoft/vcpkg-tool/releases/download/2022-03-25/vcpkg.exe) and move it to vcpkg root and try again.

Thanks.
