### ISSUE TITLE
[redis-plus-plus] update to <1.3.2>

### ISSUE THREAD

**Issue by AkshayPS12** [microsoft/vcpkg#23935]
Library name: redis-plus-plus

New version number: 1.3.2

**Comment by AkshayPS12** [comment]
Hey I want to assign this issue to myself. I have a PR ready to merge.

**Comment by JonLiu1993** [comment]
you just need to commit pr to fix this isse, we welcome your pr

**Comment by AkshayPS12** [comment]
@JonLiu1993 I need someone to approve and review my workflow request in the PR I have linked.
