### ISSUE TITLE
[qt] build failure

### ISSUE THREAD

**Issue by ilongshan** [microsoft/vcpkg#23936]
**Host Environment**
- OS: Mac M1
- Compiler: 
 ```
$ clang -v
Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: arm64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**To Reproduce**
`./vcpkg install`

```
{
  "name": "test",
  "version-string": "0.0.1",
  "dependencies": [
    "qt"
  ]
}
```

**Failure logs**
```
Error: yasm:arm64-osx@1.3.0#3 is only supported on 'windows & !uwp & !arm'
```

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Now `yasm` doesn't support MACOS, `qt` depends on `yasm`, so `qt` can't install on MACOS.

**Comment by Neumann-A** [comment]
> Thanks for posting this issue. Now yasm doesn't support MACOS, qt depends on yasm, so qt can't install on MACOS.

That is wrong. `yasm` should only be used on windows...... everywhere else gcc is fine to compile assembly. So somewhere there is a wrong dependency.

**Comment by Neumann-A** [comment]
Hmm
`./vcpkg.exe depend-info qt:arm64-osx`
does not return a dep on yasm so maybe update your vcpkg?

**Comment by ilongshan** [comment]
I am using the latest vcpkg. The output shows that qt has a dep on yasm:
<img width="924" alt="image" src="https://user-images.githubusercontent.com/7447401/161390684-c3cf5b61-cdbd-4b14-b645-690e1db0453d.png">

**Comment by Neumann-A** [comment]
#23949 should fix that. Since qtmultimedia is still cascade in ci you might encounter a different problem

**Comment by ilongshan** [comment]
Wait for it be merged. Thanks @Neumann-A
