### ISSUE TITLE
How do I set the compiler to use g++-11 in your Azure build ops?

### ISSUE THREAD

**Issue by RealTimeChris** [microsoft/vcpkg#23931]
I'm trying to get my port to build in your Azure build-ops area of the "new-port" process - but it keeps producing this... (For instance here... https://dev.azure.com/vcpkg/c1ee48cb-0df2-4ab3-8384-b1df5a79fe53/_apis/build/builds/69973/artifacts?artifactName=failure%20logs%20for%20x64-linux&api-version=7.0&%24format=zip)
```CMake Error at /mnt/vcpkg-ci/downloads/tools/cmake-3.22.2-linux/cmake-3.22.2-linux-x86_64/share/cmake-3.22/Modules/CMakeDetermineCXXCompiler.cmake:48 (message):
  Could not find compiler set in environment variable CXX:

  g++-11.

Call Stack (most recent call first):
  CMakeLists.txt:67 (project)


CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
```
Or it just states the the GNU compiler version 9.4.0 has been selected and proceeds to produce error messages regarding the missing coroutine and semaphore headers (For instance here... https://dev.azure.com/vcpkg/c1ee48cb-0df2-4ab3-8384-b1df5a79fe53/_apis/build/builds/69976/artifacts?artifactName=failure%20logs%20for%20x64-linux&api-version=7.0&%24format=zip) - how do I get it to use the newer version of the GNU C++ compiler?

**Comment by Cheney-W** [comment]
We are currently unable to set the g++ version of the Azure Pipeline to 11.
Add discordcoreapi:x64-linux=skip into the ci.baseline.txt to let your PR pass in CI.
Add a prompt to tell the user that g++ 11 is required when compiling this port on linux.
