### ISSUE TITLE
Trying glew32 debug / release for Windows = Access Violation Executing Location Error

### ISSUE THREAD

**Issue by DeafMan1983** [microsoft/vcpkg#23958]
**Describe the bug**
I expect why I have f**king Access Violation since I test with white Triangle without Shader in OpenGL
And I happens debug, release and x64/x86 = nothing works yet.

**Environment**
-Windows 10 Pro x64
- Compiler: MSVC 2019 Latest version

**To Reproduce**
1. ./vcpkg install sdl2 glew with x64 and x86 
2. See error Since vcpkg compiles successfully
Repro code: 
Like 
```
GLint vao = 0, vbo = 0;
....
glGenVertexArrays(1, &vao);
glGenBuffers(1, &vbo);
```

**Expected behavior**
I have tried but it throws "Access Violation Executing Location Exception"

**Failure logs**
-(please attached failure logs) SDL2 x86 debug yak... compilatioin under Visual Studio 2019 Community

**Additional context**
I have tried x64 debug and release -> not yet
x86 release -> not yet
x86 debug -> throw error cause yak... 

Access Violation Executing Location
![image](https://user-images.githubusercontent.com/57066679/161420240-18baf2b3-db81-482f-908d-1e1cfb82e74a.png)

Failure under x86 debug
![image](https://user-images.githubusercontent.com/57066679/161420291-1580d853-441d-450d-96fe-b07671e1deaa.png)

Thanks!

**Comment by JackBoosY** [comment]
I will dig the source code later.

**Comment by JackBoosY** [comment]
Temporary marked as port bug.

**Comment by koprok** [comment]
> @koprok @cenit Any ideas? I can repro this issue locally but don't know why it happened. Function `__glewGenVertexArrays` may not be initialized.

@JackBoosY , I have no idea, sorry.

**Comment by DeafMan1983** [comment]
Sorry I am busy yes.. I found 
![image](https://user-images.githubusercontent.com/57066679/165394098-8f7b4920-2237-44b4-b566-7c943dd7ea6f.png)

Yes it is correctly.
