### ISSUE TITLE
How to understand `VCPKG_DEFAULT_TRIPLET` and `VCPKG_DEFAULT_HOST_TRIPLET`?

### ISSUE THREAD

**Issue by playgithub** [microsoft/vcpkg#23968]
For cross compile, there are 3 concepts:
* build
* host
* target

`VCPKG_DEFAULT_HOST_TRIPLET` maps to `host`, right?
What does `VCPKG_DEFAULT_TRIPLET` map to?
For the 3 concepts in cross compile above, there should be 3 corresponding things in `vcpkg` but only 2 now (i.e. `VCPKG_DEFAULT_HOST_TRIPLET` and `VCPKG_DEFAULT_TRIPLET`), how can it be?

**Comment by Osyotr** [comment]
These three concepts are valid only when building a toolchain. For everything else there are only two concepts: host and target.
Host means the machine you are building on, and target means the machine you are building for.
`VCPKG_DEFAULT_TRIPLET` is for target triplet.

**Comment by dg0yt** [comment]
> These three concepts are valid only when building a toolchain.

In particular, this is a particular terminology from autotools, and often a source for confusion.
OTOH `host` is a term also used by CMake, and much closer to vcpkg.
