### ISSUE TITLE
Error: vcpkg has crashed; no additional details are available.

### ISSUE THREAD

**Issue by UnknownObject000** [microsoft/vcpkg#23967]
**Describe the bug**
I want to upgrade my packages using ```vcpkg upgrade --no-dry-run``` and I got ```vcpkg has crashed``` error.

**Environment**
- OS: Windows 11 build 22581.ni_release
- Compiler: Visual Studio 2022 (VC16)

**To Reproduce**
./vcpkg upgrade --no-dry-run

**Expected behavior**
Upgrade my packages instead of just crash

**Failure logs**
PS F:\vcpkg> vcpkg upgrade --no-dry-run
A suitable version of cmake was not found (required v3.22.2). Downloading portable cmake v3.22.2...
Extracting cmake...
A suitable version of 7zip was not found (required v21.7.0). Downloading portable 7zip v21.7.0...
Extracting 7zip...
Error: vcpkg has crashed; no additional details are available.
The source line is D:\a\_work\1\s\src\vcpkg\archives.cpp(100)

**Comment by DethRaid** [comment]
I just got the exact same issue, except I'm on Windows 10 OS build 19044.1586

I upgraded vcpkg to get the latest version of `DirectXTex`, but I guess vcpkg is broken rn

**Comment by DethRaid** [comment]
Looks like other people have run into this - see https://github.com/microsoft/vcpkg/issues/21117 . PhoebeHul repro'd the issue last year, but I don't see anything about fixing it. Looks like other people have been hitting the issue in the last two days

That issue suggests re-running `./bootstrap-vcpkg.bat` after `git pull`ing to update your local vcpkg. I ran the bootstrap script and can now build my project 

My feedback on this issue: VCPKG should say something far more helpful than "vcpkg has crashed; no additional details are available." Maybe it could say "old version of the vcpkg executable detected! Please run ./bootstrap-vcpkg.bat to upgrade"

**Comment by UnknownObject000** [comment]
> Looks like other people have run into this - see #21117 . PhoebeHui repro'd the issue last year, but I don't see anything about fixing it. Looks like other people have been hitting the issue in the last two days
> 
> That issue suggests re-running `./bootstrap-vcpkg.bat` after `git pull`ing to update your local vcpkg. I ran the bootstrap script and can now build my project
> 
> My feedback on this issue: VCPKG should say something far more helpful than "vcpkg has crashed; no additional details are available." Maybe it could say "old version of the vcpkg executable detected! Please run ./bootstrap-vcpkg.bat to upgrade"

Thank you for the advice, my vcpkg can successfully running now. I think you're right, if they give more information when such thing happens then I don't need to open this issue here.
