### ISSUE TITLE
[FontConfig] default config not found in application

### ISSUE THREAD

**Issue by Baklap4** [microsoft/vcpkg#23969]
I've managed to get a working build with vcpkg however now my application tells me:

```
Fontconfig error: Cannot load default config file: No such file: (null)
```
I can see the config files being therein : `build\x64-Debug\vcpkg_installed\x64-windows\etc`

![image](https://user-images.githubusercontent.com/3918517/161443102-709e61a0-1a08-4191-9e1e-dc742f537e07.png)

but for some reason the application (which resides in the folder: `build\x64-Debug` can't find it.
However if i override the environment variable to point to the location: `build\x64-Debug\vcpkg_installed\x64-windows\etc\fonts` it does work...

Is there a way to copy the `\etc\fonts` folder to be besides the executable on build?
The system im running is Windows 10, with VS2022 and the latest release of vcpkg.

**Comment by Adela0814** [comment]
@Baklap4  could you please provide the steps to reproduce the behavior.

**Comment by Adela0814** [comment]
@Baklap4  ping~

**Comment by Baklap4** [comment]
I currently don't have a small repro mvp. Will try to create one later tonight

**Comment by Adela0814** [comment]
@Baklap4  any update?

**Comment by Adela0814** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
