### ISSUE TITLE
[boost-container] Build error

### ISSUE THREAD

**Issue by jinj** [microsoft/vcpkg#23974]
**Host Environment**
- OS: Windows 2016
- Compiler: Visual Studio 2019 Community edtion

**To Reproduce**
vcpkg install boost-container:x64-windows-static

**Failure logs**
```
Computing installation plan...
The following packages will be built and installed:
    boost-container[core]:x64-windows-static -> 1.78.0
Detecting compiler hash for triplet x64-windows-static...
Restored 0 packages from C:\Users\Administrator\AppData\Local\vcpkg\archives in 192 us. Use --debug to see more details.
Starting package 1/1: boost-container:x64-windows-static
Building package boost-container[core]:x64-windows-static...
-- Using cached boostorg-container-boost-1.78.0.tar.gz.
-- Cleaning sources at C:/Users/Administrator/vcpkg/buildtrees/boost-container/src/ost-1.78.0-732edca2df.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/Administrator/vcpkg/downloads/boostorg-container-boost-1.78.0.tar.gz
-- Using source at C:/Users/Administrator/vcpkg/buildtrees/boost-container/src/ost-1.78.0-732edca2df.clean
-- Found external ninja('1.10.2').
-- Getting CMake variables for x64-windows-static
-- Configuring x64-windows-static
CMake Error at installed/x64-windows/share/boost-build/boost-modular-build.cmake:193 (message):
  No libraries were produced.  This indicates a failure while building the
  boost library.
Call Stack (most recent call first):
  ports/boost-container/portfile.cmake:15 (boost_modular_build)
  scripts/ports.cmake:145 (include)

error: building boost-container:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-container
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[boost-container]+Build+error
including:
  package: boost-container[core]:x64-windows-static -> 1.78.0
    vcpkg-tool version: 2022-03-30-692785ac944e81417840c6de244fb3e18a4b35eb
    vcpkg-scripts version: 01d6f6ff1 2022-04-01 (2 days ago)
```

**Comment by JackBoosY** [comment]
```
  No libraries were produced.  This indicates a failure while building the
  boost library.
```
Did you install boost before? If yes, please remove `boost-uninstall` and try again.

Thanks.

**Comment by jinj** [comment]
No, it is a newly installed windows. I am not aware if other programs installs it implicitly. but I have not installed it explicitly.

**Comment by JackBoosY** [comment]
@jinj can you please run the command `./vcpkg list boost` then provide the output?

**Comment by jinj** [comment]
```
```
C:\Users\Administrator\vcpkg>.\vcpkg list boost
boost-assert:x64-windows-static                    1.78.0           Boost assert module
boost-assert:x86-windows                           1.78.0           Boost assert module
boost-build:x64-windows                            1.78.0#1         Boost.Build
boost-config:x64-windows-static                    1.78.0           Boost config module
boost-config:x86-windows                           1.78.0           Boost config module
boost-container-hash:x64-windows-static            1.78.0           Boost container_hash module
boost-container-hash:x86-windows                   1.78.0           Boost container_hash module
boost-container:x86-windows                        1.78.0           Boost container module
boost-core:x64-windows-static                      1.78.0           Boost core module
boost-core:x86-windows                             1.78.0           Boost core module
boost-detail:x64-windows-static                    1.78.0           Boost detail module
boost-detail:x86-windows                           1.78.0           Boost detail module
boost-integer:x64-windows-static                   1.78.0           Boost integer module
boost-integer:x86-windows                          1.78.0           Boost integer module
boost-intrusive:x64-windows-static                 1.78.0           Boost intrusive module
boost-intrusive:x86-windows                        1.78.0           Boost intrusive module
boost-modular-build-helper:x64-windows             1.78.0#3         Internal vcpkg port used to build Boost libraries
boost-move:x64-windows-static                      1.78.0           Boost move module
boost-move:x86-windows                             1.78.0           Boost move module
boost-predef:x64-windows-static                    1.78.0           Boost predef module
boost-predef:x86-windows                           1.78.0           Boost predef module
boost-preprocessor:x64-windows-static              1.78.0           Boost preprocessor module
boost-preprocessor:x86-windows                     1.78.0           Boost preprocessor module
boost-static-assert:x64-windows-static             1.78.0           Boost static_assert module
boost-static-assert:x86-windows                    1.78.0           Boost static_assert module
boost-throw-exception:x64-windows-static           1.78.0           Boost throw_exception module
boost-throw-exception:x86-windows                  1.78.0           Boost throw_exception module
boost-type-traits:x64-windows-static               1.78.0           Boost type_traits module
boost-type-traits:x86-windows                      1.78.0           Boost type_traits module
boost-uninstall:x64-windows                        1.78.0           Internal vcpkg port used to uninstall Boost
boost-uninstall:x64-windows-static                 1.78.0           Internal vcpkg port used to uninstall Boost
boost-uninstall:x86-windows                        1.78.0           Internal vcpkg port used to uninstall Boost
boost-vcpkg-helpers:x64-windows-static             1.78.0#1         Internal vcpkg port used to modularize Boost
boost-vcpkg-helpers:x86-windows                    1.78.0#1         Internal vcpkg port used to modularize Boost
boost-winapi:x64-windows-static                    1.78.0           Boost winapi module
boost-winapi:x86-windows                           1.78.0           Boost winapi module


``````

**Comment by JackBoosY** [comment]
_C:/Users/Administrator/vcpkg_.
Maybe related to the permission.
Can you please pick another disk with a short path and try again?

**Comment by JackBoosY** [comment]
cc @yurybura any ideas?

**Comment by yurybura** [comment]
I think there isn't full log.
Please try to cleanup your local vcpkg folder and try install again.
Full log should look like:
```
D:\libs\vcpkg>vcpkg install boost-container:x64-windows-static
Computing installation plan...
A suitable version of cmake was not found (required v3.22.2). Downloading portable cmake v3.22.2...
Downloading cmake...
  https://github.com/Kitware/CMake/releases/download/v3.22.2/cmake-3.22.2-windows-i386.zip -> D:\libs\vcpkg\downloads\cmake-3.22.2-windows-i386.zip
Extracting cmake...
The following packages will be built and installed:
  * boost-assert[core]:x64-windows-static -> 1.78.0
  * boost-config[core]:x64-windows-static -> 1.78.0
    boost-container[core]:x64-windows-static -> 1.78.0
  * boost-container-hash[core]:x64-windows-static -> 1.78.0
  * boost-core[core]:x64-windows-static -> 1.78.0
  * boost-detail[core]:x64-windows-static -> 1.78.0
  * boost-integer[core]:x64-windows-static -> 1.78.0
  * boost-intrusive[core]:x64-windows-static -> 1.78.0
  * boost-move[core]:x64-windows-static -> 1.78.0
  * boost-predef[core]:x64-windows-static -> 1.78.0
  * boost-preprocessor[core]:x64-windows-static -> 1.78.0
  * boost-static-assert[core]:x64-windows-static -> 1.78.0
  * boost-throw-exception[core]:x64-windows-static -> 1.78.0
  * boost-type-traits[core]:x64-windows-static -> 1.78.0
  * boost-uninstall[core]:x64-windows-static -> 1.78.0
  * boost-vcpkg-helpers[core]:x64-windows-static -> 1.78.0#1
  * boost-winapi[core]:x64-windows-static -> 1.78.0
Additional packages (*) will be modified to complete this operation.
...
```

**Comment by JackBoosY** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.
