### ISSUE TITLE
[args] Build error

### ISSUE THREAD

**Issue by eao197** [microsoft/vcpkg#23976]
**Host Environment**
- OS: Windows 10 Home Single Language, 21H2, 64-bit
- Compiler: Visual Studio 2019 Developer Command Prompt v16.11.3

**To Reproduce**
`vcpkg install args:x64-windows-static`

**Failure logs**
```
  package: args[core]:x64-windows-static -> 6.3.0                                                                        
vcpkg-tool version: 2022-03-30-692785ac944e81417840c6de244fb3e18a4b35eb                                              
vcpkg-scripts version: 01d6f6ff1 2022-04-01 (2 days ago)                                                          
```
Logs attached.

[install-x64-windows-static-dbg-err.log](https://github.com/microsoft/vcpkg/files/8408273/install-x64-windows-static-dbg-err.log)
[install-x64-windows-static-dbg-out.log](https://github.com/microsoft/vcpkg/files/8408277/install-x64-windows-static-dbg-out.log)
[stdout-x64-windows-static.log](https://github.com/microsoft/vcpkg/files/8408287/stdout-x64-windows-static.log)
[config-x64-windows-static-out.log](https://github.com/microsoft/vcpkg/files/8408290/config-x64-windows-static-out.log)

**Comment by Adela0814** [comment]
`ninja: error: manifest 'build.ninja' still dirty after 100 tries`
This seems to ninja's bug, the related source issue: https://github.com/ninja-build/ninja/issues/1599. You can remove `PREFER_NINJA` temporarily and try to rebuild `args`.

**Comment by dg0yt** [comment]
> This seems to ninja's bug, the related source issue: [ninja-build/ninja#1599](https://github.com/ninja-build/ninja/issues/1599).

It doesn't look like ninja marked this as a "bug". At least in some case, it was a problem with the computer's clock.

Also, there is no `PREFER_NINJA`. You can try to add `WINDOWS_USE_MSBUILD` to the call to `vcpkg_cmake_configure`.

**Comment by eao197** [comment]
@dg0yt , thanks! It seems that the problem was related to computer's clock. It gone after turning on/off time-related buttons in System Settings.
