### ISSUE TITLE
How do I build Qt?

### ISSUE THREAD

**Issue by mrknight236604** [microsoft/vcpkg#23977]
I have a brand new Windows 11 laptop for development and am setting up VCPKG with the components I need.  I have been through this exercise previously on an old PC, though some time ago, as the Qt version was 5._something_.

I have successfully built the following...
.\vcpkg install boost:x64-windows
.\vcpkg install python3:x64-windows
.\vcpkg install cgal:x64-windows
...but when I try to install Qt, I get the following (see below).

I have done a GIT PULL and VCPKG UPDATE, both of which reply they are up to date; i.e. it's a brand new laptop with a clean install of VCPKG.

I have looked up a similar error (#23495), which tells me to ensure I have installed PYTHON3 and PYTHON3-VIRTUALENV.  The first I have done, but the second (apt-get install python3 python3-virtualenv) gives me another error, as it's a Windows PC and doesn't have the APT-GET function).  I'm not a Python user, so some explanation could be required here.  Online searches tell me it's a test environment, but I'm stumped as to why that's a problem when trying to build Qt.

Some help, if you please.  Here's the error from go to woe!

C:\dev\vcpkg>.\vcpkg install qt:x64-windows
Computing installation plan...
The following packages will be built and installed:
    qt[core,default-features]:x64-windows -> 6.2.4
  * qtinterfaceframework[core]:x64-windows -> 6.2.4
  * qtlocation[core]:x64-windows -> 6.2.4
  * qtlottie[core,qml]:x64-windows -> 6.2.4
  * qtmqtt[core]:x64-windows -> 6.2.4
  * qtnetworkauth[core]:x64-windows -> 6.2.4
  * qtopcua[core,default-features,gds,ns0idnames,open62541,qml]:x64-windows -> 6.2.4
  * qtpositioning[core,qml]:x64-windows -> 6.2.4
  * qtquick3d[core,default-features]:x64-windows -> 6.2.4
  * qtquicktimeline[core]:x64-windows -> 6.2.4
  * qtscxml[core,qml]:x64-windows -> 6.2.4
  * qtsensors[core,qml]:x64-windows -> 6.2.4
  * qtserialbus[core,default-features]:x64-windows -> 6.2.4
  * qtserialport[core]:x64-windows -> 6.2.4
  * qtsvg[core]:x64-windows -> 6.2.4
  * qttranslations[core,default-features]:x64-windows -> 6.2.4
  * qtvirtualkeyboard[core,default-features,hunspell]:x64-windows -> 6.2.4
  * qtwebchannel[core,qml]:x64-windows -> 6.2.4
  * qtwebengine[core,default-features,geolocation,spellchecker,webchannel]:x64-windows -> 6.2.4
  * qtwebsockets[core,qml]:x64-windows -> 6.2.4
  * qtwebview[core,qml,webengine]:x64-windows -> 6.2.4
  * vcpkg-tool-lessmsi[core]:x64-windows -> 1.10.0
  * vcpkg-tool-nodejs[core]:x64-windows -> 14.17.4
  * vcpkg-tool-python2[core]:x64-windows -> 2.7.18
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Restored 0 packages from C:\Users\XXXXX\AppData\Local\vcpkg\archives in 430.6 us. Use --debug to see more details.
Starting package 1/24: qtinterfaceframework:x64-windows
Building package qtinterfaceframework[core]:x64-windows...
-- Using cached C:/dev/vcpkg/downloads/qtinterfaceframework-71512be8758c75b4b6b0130d6b623f564c6bf227.tar.gz
-- Cleaning sources at C:/dev/vcpkg/buildtrees/qtinterfaceframework/src/564c6bf227-ee28b9e83e.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/dev/vcpkg/downloads/qtinterfaceframework-71512be8758c75b4b6b0130d6b623f564c6bf227.tar.gz
-- Applying patch fix-taglib-search.patch
-- Using source at C:/dev/vcpkg/buildtrees/qtinterfaceframework/src/564c6bf227-ee28b9e83e.clean
-- Using cached msys-mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst.
-- Using msys root at C:/dev/vcpkg/downloads/tools/msys2/9a1ec3f33446b195
Requirement already satisfied: virtualenv in c:\dev\vcpkg\downloads\tools\python\python-3.10.2-x64\lib\site-packages (20.14.0)
Requirement already satisfied: platformdirs<3,>=2 in c:\dev\vcpkg\downloads\tools\python\python-3.10.2-x64\lib\site-packages (from virtualenv) (2.5.1)
Requirement already satisfied: filelock<4,>=3.2 in c:\dev\vcpkg\downloads\tools\python\python-3.10.2-x64\lib\site-packages (from virtualenv) (3.6.0)
Requirement already satisfied: distlib<1,>=0.3.1 in c:\dev\vcpkg\downloads\tools\python\python-3.10.2-x64\lib\site-packages (from virtualenv) (0.3.4)
Requirement already satisfied: six<2,>=1.9.0 in c:\dev\vcpkg\downloads\tools\python\python-3.10.2-x64\lib\site-packages (from virtualenv) (1.16.0)
Requirement already satisfied: qface in c:\dev\vcpkg\downloads\tools\python\python-3.10.2-x64\lib\site-packages (2.0.6)
Requirement already satisfied: jinja2>=2.10.3 in c:\dev\vcpkg\downloads\tools\python\python-3.10.2-x64\lib\site-packages (from qface) (3.1.1)
Requirement already satisfied: coloredlogs>=10.0 in c:\dev\vcpkg\downloads\tools\python\python-3.10.2-x64\lib\site-packages (from qface) (15.0.1)
Requirement already satisfied: click>=6.7 in c:\dev\vcpkg\downloads\tools\python\python-3.10.2-x64\lib\site-packages (from qface) (8.1.2)
Requirement already satisfied: pyyaml>=5.1 in c:\dev\vcpkg\downloads\tools\python\python-3.10.2-x64\lib\site-packages (from qface) (6.0)
Requirement already satisfied: path.py>=11.0.1 in c:\dev\vcpkg\downloads\tools\python\python-3.10.2-x64\lib\site-packages (from qface) (12.5.0)
Requirement already satisfied: watchdog>=0.8.3 in c:\dev\vcpkg\downloads\tools\python\python-3.10.2-x64\lib\site-packages (from qface) (2.1.7)
Requirement already satisfied: antlr4-python3-runtime>=4.7.1 in c:\dev\vcpkg\downloads\tools\python\python-3.10.2-x64\lib\site-packages (from qface) (4.9.3)
Requirement already satisfied: six>=1.11.0 in c:\dev\vcpkg\downloads\tools\python\python-3.10.2-x64\lib\site-packages (from qface) (1.16.0)
Requirement already satisfied: colorama in c:\dev\vcpkg\downloads\tools\python\python-3.10.2-x64\lib\site-packages (from click>=6.7->qface) (0.4.4)
Requirement already satisfied: humanfriendly>=9.1 in c:\dev\vcpkg\downloads\tools\python\python-3.10.2-x64\lib\site-packages (from coloredlogs>=10.0->qface) (10.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\dev\vcpkg\downloads\tools\python\python-3.10.2-x64\lib\site-packages (from jinja2>=2.10.3->qface) (2.1.1)
Requirement already satisfied: path in c:\dev\vcpkg\downloads\tools\python\python-3.10.2-x64\lib\site-packages (from path.py>=11.0.1->qface) (16.4.0)
Requirement already satisfied: pyreadline3 in c:\dev\vcpkg\downloads\tools\python\python-3.10.2-x64\lib\site-packages (from humanfriendly>=9.1->coloredlogs>=10.0->qface) (3.4.1)
-- Found external ninja('1.10.2').
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:128 (message):
    Command failed: ninja -v
    Working Directory: C:/dev/vcpkg/buildtrees/qtinterfaceframework/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\dev\vcpkg\buildtrees\qtinterfaceframework\config-x64-windows-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:415 (vcpkg_execute_required_process)
  installed/x64-windows/share/qtbase/qt_install_submodule.cmake:102 (vcpkg_cmake_configure)
  ports/qtinterfaceframework/portfile.cmake:84 (qt_cmake_configure)
  scripts/ports.cmake:145 (include)

error: building qtinterfaceframework:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+qtinterfaceframework
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[qtinterfaceframework]+Build+error
including:
  package: qtinterfaceframework[core]:x64-windows -> 6.2.4
    vcpkg-tool version: 2022-03-30-692785ac944e81417840c6de244fb3e18a4b35eb
    vcpkg-scripts version: 01d6f6ff1 2022-04-01 (2 days ago)

Additionally, attach any relevant sections from the log files above.

**Comment by Neumann-A** [comment]
`qtinterfaceframework` is currently broken due to an upstream `jinja` issue. 
Advice: dont install all of Qt. Most people probably only need `qtbase[gui,widgets]` + `qttools` + `qtdeclarative` (if doing qml stuff) + some qt plugins (like `qtsvg`)

**Comment by FrankXie05** [comment]
@mrknight236604 does the issue still occur?

**Comment by mrknight236604** [comment]
I had installed qtbase only, as per the advice from @Neumann-A.  Retrying vcpkg install qt:x64-windows starts better than before bu still crashes at when trying to run ninja -v

CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:128 (message):
    Command failed: ninja -v
    Working Directory: C:/dev/vcpkg/buildtrees/qtinterfaceframework/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\dev\vcpkg\buildtrees\qtinterfaceframework\config-x64-windows-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:415 (vcpkg_execute_required_process)
  installed/x64-windows/share/qtbase/qt_install_submodule.cmake:102 (vcpkg_cmake_configure)
  ports/qtinterfaceframework/portfile.cmake:84 (qt_cmake_configure)
  scripts/ports.cmake:145 (include)


error: building qtinterfaceframework:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+qtinterfaceframework
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[qtinterfaceframework]+Build+error
including:
  package: qtinterfaceframework[core]:x64-windows -> 6.2.4
    vcpkg-tool version: 2022-03-30-692785ac944e81417840c6de244fb3e18a4b35eb
    vcpkg-scripts version: 01d6f6ff1 2022-04-01 (7 days ago)

Additionally, attach any relevant sections from the log files above.

**Comment by Neumann-A** [comment]
> Retrying vcpkg install qt:x64-windows

don't build all of qt.... you will not need it. Only install the modules you really want to have.

**Comment by mrknight236604** [comment]
qtbase it is then.

**Comment by FrankXie05** [comment]
@mrknight236604 The issue is now resolved, please use the latest vcpkg and try again. Run `git pull` .

**Comment by mrknight236604** [comment]
Thanks Frank, I have rebuilt Qt as directed.  FYI: it displays the following message not long after I started the build.  Not sure if it's something that needs fixing, but thought you'd need to know.

`CMake Warning at installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:487 (message):
  The following variables are not used in CMakeLists.txt:

      QT_USE_MINIMAL_QFACE_PACKAGES

  Please recheck them and remove the unnecessary options from the
  `vcpkg_cmake_configure` call.

  If these options should still be passed for whatever reason, please use the
  `MAYBE_UNUSED_VARIABLES` argument.
Call Stack (most recent call first):
  installed/x64-windows/share/qtbase/qt_install_submodule.cmake:102 (vcpkg_cmake_configure)
  ports/qtinterfaceframework/portfile.cmake:33 (qt_cmake_configure)
  scripts/ports.cmake:145 (include)
`

**Comment by FrankXie05** [comment]
@mrknight236604 Thanks for the reminder, it's just a warning, I'll check it on the next update, if it's not used I'll delete it. :)
