### ISSUE TITLE
[boost-build] Build error

### ISSUE THREAD

**Issue by pat18** [microsoft/vcpkg#23986]
**Host Environment**
- OS: [Windows]

**To Reproduce**
`./vcpkg install aricpp`

**Failure logs**
```
C:\src\vcpkg>.\vcpkg install aricpp
Computing installation plan...
The following packages will be built and installed:
    aricpp[core]:x86-windows -> 1.1.1#1
  * boost-algorithm[core]:x86-windows -> 1.78.0
  * boost-asio[core]:x86-windows -> 1.78.0
  * boost-beast[core]:x86-windows -> 1.78.0
  * boost-build[core]:x64-windows -> 1.78.0#1
  * boost-chrono[core]:x86-windows -> 1.78.0
  * boost-container[core]:x86-windows -> 1.78.0
  * boost-context[core]:x86-windows -> 1.78.0
  * boost-coroutine[core]:x86-windows -> 1.78.0
  * boost-date-time[core]:x86-windows -> 1.78.0
  * boost-endian[core]:x86-windows -> 1.78.0
  * boost-exception[core]:x86-windows -> 1.78.0
  * boost-intrusive[core]:x86-windows -> 1.78.0
  * boost-lexical-cast[core]:x86-windows -> 1.78.0
  * boost-logic[core]:x86-windows -> 1.78.0
  * boost-modular-build-helper[core]:x64-windows -> 1.78.0#3
  * boost-pool[core]:x86-windows -> 1.78.0
  * boost-range[core]:x86-windows -> 1.78.0
  * boost-ratio[core]:x86-windows -> 1.78.0
  * boost-rational[core]:x86-windows -> 1.78.0
  * boost-regex[core]:x86-windows -> 1.78.0
  * boost-system[core]:x86-windows -> 1.78.0
  * boost-tokenizer[core]:x86-windows -> 1.78.0
  * boost-unordered[core]:x86-windows -> 1.78.0
  * boost-variant2[core]:x86-windows -> 1.78.0
  * vcpkg-cmake[core]:x64-windows -> 2022-02-14
  * vcpkg-cmake-config[core]:x64-windows -> 2022-02-06
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Detecting compiler hash for triplet x86-windows...
Restored 0 packages from C:\Users\TopaSEAH\AppData\Local\vcpkg\archives in 725.6 us. Use --debug to see more details.
Starting package 1/27: boost-build:x64-windows
Building package boost-build[core]:x64-windows...
-- Using cached boostorg-build-boost-1.78.0.tar.gz.
-- Cleaning sources at C:/src/vcpkg/buildtrees/boost-build/src/ost-1.78.0-7f806436df.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/src/vcpkg/downloads/boostorg-build-boost-1.78.0.tar.gz
-- Applying patch 0001-don-t-skip-install-targets.patch
-- Applying patch 0002-fix-get-version.patch
-- Using source at C:/src/vcpkg/buildtrees/boost-build/src/ost-1.78.0-7f806436df.clean
-- Using cached boost_LICENSE_1_0.txt.
-- Using cached boost-1.78.0-boostcpp.jam.
-- Installing: C:/src/vcpkg/packages/boost-build_x64-windows/share/boost-build/copyright
-- Bootstrapping...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:128 (message):
    Command failed: C:/src/vcpkg/packages/boost-build_x64-windows/tools/boost-build/bootstrap.bat msvc
    Working Directory: C:/src/vcpkg/packages/boost-build_x64-windows/tools/boost-build
    Error code: 1
    See logs for more information:
      C:\src\vcpkg\buildtrees\boost-build\bootstrap-x64-windows-out.log
      C:\src\vcpkg\buildtrees\boost-build\bootstrap-x64-windows-err.log

Call Stack (most recent call first):
  ports/boost-build/portfile.cmake:64 (vcpkg_execute_required_process)
  scripts/ports.cmake:145 (include)


error: building boost-build:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-build
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[boost-build]+Build+error
including:
  package: boost-build[core]:x64-windows -> 1.78.0#1
    vcpkg-tool version: 2022-03-30-692785ac944e81417840c6de244fb3e18a4b35eb
    vcpkg-scripts version: 01d6f6ff1 2022-04-01 (3 days ago)
```
**Additional context**
first
I'm trying to run this example [https://github.com/daniele77/aricpp](url) in vscode. For this I try to install the libraries with vcpkg.
Now when I do  .\vcpkg install aricpp  I got this error. In vscode I changed the compiler to gcc and I got less problems with the libraries
But i couldn't install aricpp because of problem with boost-build. I need solve this error because I need work with this library

**Comment by autoantwort** [comment]
> See logs for more information:
C:\src\vcpkg\buildtrees\boost-build\bootstrap-x64-windows-out.log
C:\src\vcpkg\buildtrees\boost-build\bootstrap-x64-windows-err.log

**Comment by pat18** [comment]
Building the B2 engine..
Call_If_Exists "bin\VCVARS32.BAT"
###
### Using 'msvc' toolset.
###

C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine>"cl" /nologo /MP /MT /TP /Feb2 /wd4996 /O2 /GL /EHsc   -DNDEBUG  builtins.cpp class.cpp command.cpp compile.cpp constants.cpp cwd.cpp debug.cpp debugger.cpp execcmd.cpp execnt.cpp execunix.cpp filent.cpp filesys.cpp fileunix.cpp frames.cpp function.cpp glob.cpp hash.cpp hcache.cpp hdrmacro.cpp headers.cpp jam.cpp jamgram.cpp lists.cpp make.cpp make1.cpp md5.cpp mem.cpp modules.cpp native.cpp object.cpp option.cpp output.cpp parse.cpp pathnt.cpp pathsys.cpp pathunix.cpp regexp.cpp rules.cpp scan.cpp search.cpp jam_strings.cpp startup.cpp subst.cpp sysinfo.cpp timestamp.cpp variable.cpp w32_getreg.cpp modules/order.cpp modules/path.cpp modules/property-set.cpp modules/regex.cpp modules/sequence.cpp modules/set.cpp /link kernel32.lib advapi32.lib user32.lib 
builtins.cpp
class.cpp
command.cpp
compile.cpp
constants.cpp
cwd.cpp
debug.cpp
debugger.cpp
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: No se puede abrir el archivo incluir: 'ctype.h': No such file or directory (compilando archivo de origen command.cpp)
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: No se puede abrir el archivo incluir: 'ctype.h': No such file or directory (compilando archivo de origen builtins.cpp)
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: No se puede abrir el archivo incluir: 'ctype.h': No such file or directory (compilando archivo de origen compile.cpp)
execcmd.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include\yvals.h(12): fatal error C1083: No se puede abrir el archivo incluir: 'crtdbg.h': No such file or directory (compilando archivo de origen class.cpp)
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include\yvals.h(12): fatal error C1083: No se puede abrir el archivo incluir: 'crtdbg.h': No such file or directory (compilando archivo de origen cwd.cpp)
execnt.cpp
execunix.cpp
filent.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include\yvals.h(12): fatal error C1083: No se puede abrir el archivo incluir: 'crtdbg.h': No such file or directory (compilando archivo de origen constants.cpp)
filesys.cpp
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: No se puede abrir el archivo incluir: 'ctype.h': No such file or directory (compilando archivo de origen debug.cpp)
fileunix.cpp
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: No se puede abrir el archivo incluir: 'ctype.h': No such file or directory (compilando archivo de origen execcmd.cpp)
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include\yvals.h(12): fatal error C1083: No se puede abrir el archivo incluir: 'crtdbg.h': No such file or directory (compilando archivo de origen debugger.cpp)
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: No se puede abrir el archivo incluir: 'ctype.h': No such file or directory (compilando archivo de origen execunix.cpp)
frames.cpp
function.cpp
glob.cpp
hash.cpp
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: No se puede abrir el archivo incluir: 'ctype.h': No such file or directory (compilando archivo de origen filesys.cpp)
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: No se puede abrir el archivo incluir: 'ctype.h': No such file or directory (compilando archivo de origen fileunix.cpp)
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: No se puede abrir el archivo incluir: 'ctype.h': No such file or directory (compilando archivo de origen execnt.cpp)
hcache.cpp
hdrmacro.cpp
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: No se puede abrir el archivo incluir: 'ctype.h': No such file or directory (compilando archivo de origen filent.cpp)
headers.cpp
jam.cpp
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: No se puede abrir el archivo incluir: 'ctype.h': No such file or directory (compilando archivo de origen function.cpp)
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: No se puede abrir el archivo incluir: 'ctype.h': No such file or directory (compilando archivo de origen glob.cpp)
jamgram.cpp
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: No se puede abrir el archivo incluir: 'ctype.h': No such file or directory (compilando archivo de origen hash.cpp)
lists.cpp
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: No se puede abrir el archivo incluir: 'ctype.h': No such file or directory (compilando archivo de origen frames.cpp)
make.cpp
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: No se puede abrir el archivo incluir: 'ctype.h': No such file or directory (compilando archivo de origen hcache.cpp)
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: No se puede abrir el archivo incluir: 'ctype.h': No such file or directory (compilando archivo de origen hdrmacro.cpp)
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: No se puede abrir el archivo incluir: 'ctype.h': No such file or directory (compilando archivo de origen headers.cpp)
make1.cpp
md5.cpp
mem.cpp
modules.cpp
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: No se puede abrir el archivo incluir: 'ctype.h': No such file or directory (compilando archivo de origen jamgram.cpp)
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: No se puede abrir el archivo incluir: 'ctype.h': No such file or directory (compilando archivo de origen lists.cpp)
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: No se puede abrir el archivo incluir: 'ctype.h': No such file or directory (compilando archivo de origen jam.cpp)
native.cpp
object.cpp
option.cpp
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: No se puede abrir el archivo incluir: 'ctype.h': No such file or directory (compilando archivo de origen make.cpp)
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: No se puede abrir el archivo incluir: 'ctype.h': No such file or directory (compilando archivo de origen make1.cpp)
output.cpp
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\md5.h(53): fatal error C1083: No se puede abrir el archivo incluir: 'stddef.h': No such file or directory (compilando archivo de origen md5.cpp)
parse.cpp
pathnt.cpp
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: No se puede abrir el archivo incluir: 'ctype.h': No such file or directory (compilando archivo de origen modules.cpp)
pathsys.cpp
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: No se puede abrir el archivo incluir: 'ctype.h': No such file or directory (compilando archivo de origen option.cpp)
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: No se puede abrir el archivo incluir: 'ctype.h': No such file or directory (compilando archivo de origen object.cpp)
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: No se puede abrir el archivo incluir: 'ctype.h': No such file or directory (compilando archivo de origen mem.cpp)
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include\yvals.h(12): fatal error C1083: No se puede abrir el archivo incluir: 'crtdbg.h': No such file or directory (compilando archivo de origen native.cpp)
pathunix.cpp
regexp.cpp
rules.cpp
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: No se puede abrir el archivo incluir: 'ctype.h': No such file or directory (compilando archivo de origen output.cpp)
scan.cpp
search.cpp
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: No se puede abrir el archivo incluir: 'ctype.h': No such file or directory (compilando archivo de origen parse.cpp)
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: No se puede abrir el archivo incluir: 'ctype.h': No such file or directory (compilando archivo de origen pathnt.cpp)
jam_strings.cpp
startup.cpp
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: No se puede abrir el archivo incluir: 'ctype.h': No such file or directory (compilando archivo de origen pathsys.cpp)
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: No se puede abrir el archivo incluir: 'ctype.h': No such file or directory (compilando archivo de origen regexp.cpp)
subst.cpp
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: No se puede abrir el archivo incluir: 'ctype.h': No such file or directory (compilando archivo de origen pathunix.cpp)
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: No se puede abrir el archivo incluir: 'ctype.h': No such file or directory (compilando archivo de origen search.cpp)
sysinfo.cpp
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: No se puede abrir el archivo incluir: 'ctype.h': No such file or directory (compilando archivo de origen scan.cpp)
timestamp.cpp
variable.cpp
w32_getreg.cpp
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: No se puede abrir el archivo incluir: 'ctype.h': No such file or directory (compilando archivo de origen rules.cpp)
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include\yvals.h(12): fatal error C1083: No se puede abrir el archivo incluir: 'crtdbg.h': No such file or directory (compilando archivo de origen startup.cpp)
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: No se puede abrir el archivo incluir: 'ctype.h': No such file or directory (compilando archivo de origen jam_strings.cpp)
order.cpp
path.cpp
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: No se puede abrir el archivo incluir: 'ctype.h': No such file or directory (compilando archivo de origen subst.cpp)
property-set.cpp
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: No se puede abrir el archivo incluir: 'ctype.h': No such file or directory (compilando archivo de origen sysinfo.cpp)
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: No se puede abrir el archivo incluir: 'ctype.h': No such file or directory (compilando archivo de origen timestamp.cpp)
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: No se puede abrir el archivo incluir: 'ctype.h': No such file or directory (compilando archivo de origen variable.cpp)
regex.cpp
sequence.cpp
set.cpp
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: No se puede abrir el archivo incluir: 'ctype.h': No such file or directory (compilando archivo de origen w32_getreg.cpp)
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include\yvals.h(12): fatal error C1083: No se puede abrir el archivo incluir: 'crtdbg.h': No such file or directory (compilando archivo de origen modules/order.cpp)
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include\yvals.h(12): fatal error C1083: No se puede abrir el archivo incluir: 'crtdbg.h': No such file or directory (compilando archivo de origen modules/path.cpp)
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\modules\../mem.h(14): fatal error C1083: No se puede abrir el archivo incluir: 'stdlib.h': No such file or directory (compilando archivo de origen modules/regex.cpp)
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include\yvals.h(12): fatal error C1083: No se puede abrir el archivo incluir: 'crtdbg.h': No such file or directory (compilando archivo de origen modules/property-set.cpp)
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include\yvals.h(12): fatal error C1083: No se puede abrir el archivo incluir: 'crtdbg.h': No such file or directory (compilando archivo de origen modules/set.cpp)
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include\yvals.h(12): fatal error C1083: Cannot open file include: : 'crtdbg.h': No such file or directory (compilando archivo de origen modules/sequence.cpp)

C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine>dir *.exe 
 The volume of the unit is C is Windows-SSD
 The volume serial number is: 04AD-47C8

Directory of C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine


C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine>copy /b .\b2.exe .\bjam.exe 
The system cannot find the specified file.

Failed to build the B2 engine.

**Comment by autoantwort** [comment]
Google says https://stackoverflow.com/questions/42258311/cannot-open-include-file-ctype-h-no-such-file-or-directory

**Comment by pat18** [comment]
I have a question. In Visual Studio Code I can't open an User Install to do this :

> Google says https://stackoverflow.com/questions/42258311/cannot-open-include-file-ctype-h-no-such-file-or-directory

Is there another way to do this?

**Comment by autoantwort** [comment]
I don't know

**Comment by pat18** [comment]
Thanks now I know where to look

**Comment by pat18** [comment]
My solutions was first uninstall Visual Studio Code and after:

1. Install 'Visual Studio Community' version and after install 'Visual Studio code' version
2. Install 'vcpkg' in the path 'c:\dev and do .\\vcpkg.exe integrate install
3. Finally I install the library: .\vcpkg install aricpp:x64-windows

Now I can use the aricpp library.

This video can help you to configure Visual Studio and Visual Studio Code:  [https://www.youtube.com/watch?v=iZeK3Ie5Fz0](url)
