### ISSUE TITLE
vcpkg with Git(Hub) for Windows

### ISSUE THREAD

**Issue by patrikhuber** [Microsoft/vcpkg#2398]
I'm using the latest GitHub for Windows (https://desktop.github.com/) with I think Git for Windows (and posh-git). I would expect `vcpkg` to work in this scenario but I get:

```
~\Projects\vcpkg [master ≡]> .\vcpkg install zlib
The following packages will be built and installed:
    zlib[core]:x86-windows
Starting package 1/1: zlib:x86-windows
Building package zlib:x86-windows...
A suitable version of git was not found (required v2.15.0). Downloading portable git v2.15.0...
~\Projects\vcpkg [master ≡]> git --version
git version 2.11.0.windows.3
~\Projects\vcpkg [master ≡]> which git
/cmd/git
```

Do I really need to install another version of git on my system?
I think it would be nice if vcpkg worked with the GitHub version, as many people will use this version of git on Windows.

**Comment by jrose2002** [comment]
It will do that if your git for windows is not updated to the latest version.

**Comment by patrikhuber** [comment]
Ah, you're right, thanks. I got misled by GitHub for Windows: If I start their GUI and check the version, it says that it is up-to-date. However it seems that `git` now needs to be updated independently of that.
