### ISSUE TITLE
[New Port Request] Exiv2

### ISSUE THREAD

**Issue by jonverrier** [microsoft/vcpkg#23992]
Library name:Exiv2. Request is for a UWP port. 

Library description: Exiv2 is a Cross-platform C++ library to manage image metadata. 

Source repository URL: https://github.com/exiv2/exiv2

Project homepage (if different from the source repository): https://exiv2.org/ 

Anything else that is useful to know when adding (such as optional features the library may have that should be included): 
1. The other way round - command line utility is not needed from UWP apps. 
2. Requires zlib, expat, and gettext as dependencies for various features.  See https://github.com/exiv2/exiv2#Dependencies.

**Comment by JonLiu1993** [comment]
@jonverrier, thanks for posting this question, the exiv2 port has been added to vcpkg, you can git pull vcpkg and use this port
