### ISSUE TITLE
Unknown variable name VCPKG_CHAINLOAD_TOOLCHAIN_FILE=

### ISSUE THREAD

**Issue by kinsung** [Microsoft/vcpkg#2399]
visual stduio 2017 
D:\dev\vcpkg>vcpkg install zlib
The following packages will be built and installed:
    zlib:x86-windows
Starting package 1/1: zlib:x86-windows
Building package zlib:x86-windows...
Unknown variable name VCPKG_CHAINLOAD_TOOLCHAIN_FILE=

**Comment by ras0219-msft** [comment]
Hi @kinsung, could you make sure you've run:

```
>git pull
>bootstrap-vcpkg.bat
```


Then try again? If it still occurs, please post the output of `vcpkg version` as well as if you've made any modifications to `triplets\x86-windows.cmake`.

**Comment by lukas-w** [comment]
This problem was fixed for me after following your instructions, @ras0219-msft.

**Comment by wangli28** [comment]
Please open a new issue if this is still a problem for you.
