### ISSUE TITLE
gflags can not be used by a cmake project

### ISSUE THREAD

**Issue by barcharcraz** [Microsoft/vcpkg#240]
gflags does not properly fix up its cmakelists file, so it can't be used by a downstream cmake project. Additionally it deletes the debug cmake config file, so debug builds will not link to the debug version.

**Comment by KindDragon** [comment]
I though issue with debug build was already fixed

**Comment by ras0219-msft** [comment]
The debug build does work, the issue is that there isn't a `share/gflags/glfags-config-debug.cmake`, so `find_package(gflags)` won't work very well in debug mode.
