### ISSUE TITLE
Confused about install vcpkg in C:\src\vcpkg or C:\dev\vcpkg in document

### ISSUE THREAD

**Issue by ycdxsb** [microsoft/vcpkg#24007]
Hello,
    In the doc, it said that "We recommend somewhere like C:\src\vcpkg or C:\dev\vcpkg, since otherwise you may run into path issues for some port build systems."
   I want to know if the path C:\src is the real C:\src, or if it refers to the path where the project is located like C:\Project\Vscode\vcpkg_test?
Thanks

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. It just suggest a short path, you can according your project to choose vcpkg install path. By the way, some ports have `vcpkg_buildpath_length_warning`, if the install path too long, some ports will install failed.
