### ISSUE TITLE
LLVM 5.0 x64-windows build fails

### ISSUE THREAD

**Issue by Krokoklemmi** [Microsoft/vcpkg#2400]
Error: Building package llvm:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: llvm:x64-windows
  Vcpkg version: 0.0.100-2017-12-13-7a2120dba1fb606b06f555965908db438d10e019

Relevant information from the log file:
FAILED: lib/DebugInfo/PDB/CMakeFiles/LLVMDebugInfoPDB.dir/PDB.cpp.obj 
 [...]
ninja: build stopped: subcommand failed.
[install-x64-windows-rel-out.log](https://github.com/Microsoft/vcpkg/files/1569783/install-x64-windows-rel-out.log)

**Comment by Krokoklemmi** [comment]
And because I can't edit the issue for some reason, here's what comes before that message:

CMake Error at C:/vcpkg/scripts/cmake/vcpkg_execute_required_process.cmake:44 (message):
    Command failed: C:/vcpkg/downloads/cmake-3.10.0-win32-x86/bin/cmake.exe;--build;.;--config;Release;--target;install;--;-v
    Working Directory: C:/vcpkg/buildtrees/llvm/x64-windows-rel
    See logs for more information:
      C:\vcpkg\buildtrees\llvm\install-x64-windows-rel-out.log
      C:\vcpkg\buildtrees\llvm\install-x64-windows-rel-err.log

Call Stack (most recent call first):
  C:/vcpkg/scripts/cmake/vcpkg_build_cmake.cmake:63 (vcpkg_execute_required_process)
  C:/vcpkg/scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  C:/vcpkg/ports/llvm/portfile.cmake:40 (vcpkg_install_cmake)
  C:/vcpkg/scripts/ports.cmake:72 (include)

**Comment by fcharlie** [comment]
Please install ATL Component

```
Cannot open include file: 'atlbase.h': No such file or directory
```

**Comment by Krokoklemmi** [comment]
Weirdly enough, I already have had checked `Visual C++ ATL Support` in the VS installer. I'll try the `MFC and ATL Support` component as well.

**Comment by ras0219-msft** [comment]
I've added `atlmfc` to the dependencies list for `llvm`, which should now give a much better error message. Thank you for reporting this issue!

**Comment by amithks25** [comment]
I am having Visual Studio Desktop express edition ,so this problem keep on coming.
Interestingly atlbase.h file was not found in ubuntu,everything working correctly with ubuntu. 
How this could happen?Is there any way to build from source on windows?
