### ISSUE TITLE
[openssl] build failure due to missing repo files

### ISSUE THREAD

**Issue by mprather** [microsoft/vcpkg#24006]
**Host Environment**
- OS: Windows
- Compiler: VS2019, Version 16.11.9

**To Reproduce**
1. git pull
2. git checkout d78a0b47bdd4deb6bc5547e06e289672892ed226
3. bootstrap
4. git install openssl:x64-windows

Result:
Cannot complete and installation fails. The requested file does not exist on the msys2 sever.

https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.**5906**.c9a21571-1-any.pkg.tar.zst

**Failure logs**
```
> .\vcpkg.exe install openssl:x64-windows
Computing installation plan...
The following packages will be built and installed:
    openssl[core]:x64-windows -> 1.1.1l#3
Detecting compiler hash for triplet x64-windows...
Restored 0 packages from C:\Users\mp\AppData\Local\vcpkg\archives in 223.4 us. Use --debug to see more details.
Starting package 1/1: openssl:x64-windows
Building package openssl[core]:x64-windows...
-- Using cached openssl-1.1.1l.tar.gz.
-- Cleaning sources at C:/src/test_vcpkg/buildtrees/openssl/src/openssl-1-5a7d592597.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/src/test_vcpkg/downloads/openssl-1.1.1l.tar.gz
-- Using source at C:/src/test_vcpkg/buildtrees/openssl/src/openssl-1-5a7d592597.clean
-- Copying openssl release source files...
-- Copying openssl release source files... done
-- Configure x64-windows-rel
-- Configure x64-windows-rel done
-- Build x64-windows-rel
-- Build x64-windows-rel done
-- Copying openssl debug source files...
-- Copying openssl debug source files... done
-- Configure x64-windows-dbg
-- Configure x64-windows-dbg done
-- Build x64-windows-dbg
-- Build x64-windows-dbg done
-- Installing: C:/src/test_vcpkg/packages/openssl_x64-windows/share/openssl/copyright
-- Fixing pkgconfig file: C:/src/test_vcpkg/packages/openssl_x64-windows/lib/pkgconfig/libcrypto.pc
-- Fixing pkgconfig file: C:/src/test_vcpkg/packages/openssl_x64-windows/lib/pkgconfig/libssl.pc
-- Fixing pkgconfig file: C:/src/test_vcpkg/packages/openssl_x64-windows/lib/pkgconfig/openssl.pc
-- Using cached msys-mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst.
-- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst;https://www2.futureware.at/~nickoe/msys2-mirror/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst;https://mirror.yandex.ru/mirrors/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst;https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst;https://mirrors.ustc.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst;https://mirror.bit.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst;https://mirror.selfnet.de/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst;https://mirrors.sjtug.sjtu.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst -> msys-mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst...
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' = off
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst
[DEBUG] Downloading https://www2.futureware.at/~nickoe/msys2-mirror/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst
[DEBUG] Downloading https://mirror.yandex.ru/mirrors/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst
[DEBUG] Downloading https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst
[DEBUG] Downloading https://mirrors.ustc.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst
[DEBUG] Downloading https://mirror.bit.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst
[DEBUG] Downloading https://mirror.selfnet.de/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst
[DEBUG] Downloading https://mirrors.sjtug.sjtu.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst
Error: Failed to download from mirror set:
https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst: failed: status code 404
https://www2.futureware.at/~nickoe/msys2-mirror/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst: failed: status code 404
https://mirror.yandex.ru/mirrors/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst: failed: status code 404
https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst: failed: status code 404
https://mirrors.ustc.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst: failed: status code 404
https://mirror.bit.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst: WinHttpSendRequest() failed: 12007
https://mirror.selfnet.de/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst: WinHttpSendRequest() failed: 12175
https://mirrors.sjtug.sjtu.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst: failed: status code 404

[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(626)
[DEBUG] Exiting after 7.862 s us (7842892 us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:83 (message):

      Failed to download file with error: 1
      If you use a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.

      3. You proxy's remote server is out of service.

      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)

      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:291 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_acquire_msys.cmake:84 (vcpkg_download_distfile)
  scripts/cmake/vcpkg_acquire_msys.cmake:174 (z_vcpkg_acquire_msys_download_package)
  scripts/cmake/vcpkg_find_acquire_program.cmake:449 (vcpkg_acquire_msys)
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:198 (vcpkg_find_acquire_program)
  ports/openssl/install-pc-files.cmake:32 (vcpkg_fixup_pkgconfig)
  ports/openssl/portfile.cmake:21 (include)
  scripts/ports.cmake:142 (include)


Error: Building package openssl:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openssl:x64-windows
  Vcpkg version: 2021-09-10-2059ef11aa6067e6f59b0d939c5d17e3c5c47d3e

Additionally, attach any relevant sections from the log files above.
```

**Additional context**
This same vcpkg commit on linux does not have an issue. If the linux version works for this specific port version, then windows needs to work as well.

The vcpkg commit in question is from Oct 29, 2021, which is not terribly old. We can't roll vcpkg forward as our product has shipped with a dependency on that exact commit (and moving it forward results in other breaks on other platforms, this commit was a good compromise for all platforms that we use).

**Comment by FrankXie05** [comment]
@mprather Thanks for posting this issue, at present, `MSYS2 `is a rolling-based platform so not being able to dowload old packages is very expected.(Upstream issue: [10710](https://github.com/msys2/MINGW-packages/issues/10710))

 We can transfer to this issue(#23828 ) to discuss (of course, it also contains temporary solutions) :)

**Comment by mprather** [comment]
@FrankXie05 thanks for the info. This is disappointing. With our team holding a dependency on vcpkg, which then holds a dependency other libraries... this makes life so much harder all of a sudden if the underlying libraries will just up and disappear. 

I somewhat understand if this port was many years old.  It literally not even 6 months old but the port clearly was using some dependency that was deemed "not worth preserving" somewhere between the end of Oct and now.  

It's not as easy as just upgrading vcpkg, either. Vcpkg was broken for nearly 6 months on a customers platform due to other vcpkg-tool issues. We didn't even have a chance to pull latest. Further, it takes a lot of effort to get all of this documented and users onboard and in-sync with any tooling update.

**Comment by FrankXie05** [comment]
@mprather I don't think it's a conflict for you because `vcpkg `has updated `msys2 `to the latest version, the problem is just not being able to roll back to an older version. Just keep vcpkg in the latest version([2022.3.10](https://github.com/microsoft/vcpkg/releases/tag/2022.03.10)) :)

**Comment by dg0yt** [comment]
If you need to use a previous version of openssl, use manifest mode or an overlay port.

**Comment by mprather** [comment]
@FrankXie05 maybe I'm not understanding where the problem lies. are you saying the failure is really with vcpkg rather than openssl?

as I mentioned earlier, rolling vcpkg forward is not easy when you have the following concerns ...

* vcpkg not working on all platforms due to vcpkg-tool bugs. we were literally shut out of upgrading vcpkg for 6+ months due to misc vcpkg issues. 
* user education and general testing requirements of our api state that we ship our api and tools against a known vcpkg commit. in the nearly 2 years we've been using vcpkg, we've used exactly 2 specific vcpkg commits. in our summer release, we're picking up a new commit making that our 3rd commit. each upgrade requires a lot of work and we upgrade vcpkg because we're picking up new library versions (our main dependency has changed exactly 3 times since 2020).
* clients that require extensive review of all upgrades of tools/dependencies. this is required to verify we can cross over to an air-gapped system. we can't just upgrade on a whim.

Basically, it's like threading a needle. Now some library is telling us that we can't use something that they consider old is just nuts. Right now, I can't even build a new machine to get back to where we were in Oct. That does not seem right, does it?  This is quite honestly a very hard message to deliver to our customers and puts an immense burden on systems that require validation of all code versions. 

@dg0yt we will look into the alternates but in the past they did not fit the requirements (beta classification, makes storage explode, etc) and actually made development more difficult. classic mode has worked best for us across all platforms and in our azure pipelines. however, I don't understand how manifest mode will help the situation if we're fundamentally locked into a specific version of vcpkg. am I missing something or is this tied back to my first question?
