### ISSUE TITLE
[brotli] Build error

### ISSUE THREAD

**Issue by shinny-hongyan** [microsoft/vcpkg#24012]
**Host Environment**
- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**
`./vcpkg install xxxx`

**Failure logs**
-Cut and paste the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Could you please provide your environment information and the install error log file?

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Please reopen this issue with more info if this is still a problem for you.
