### ISSUE TITLE
[x265] Build error

### ISSUE THREAD

**Issue by choobek** [microsoft/vcpkg#24016]
**Host Environment**
- OS: Windows 11
- Compiler: ?

**To Reproduce**
`./vcpkg install openimageio:x64-windows`

**Failure logs**
Here is what I get when I try to install openimageio:
![image](https://user-images.githubusercontent.com/88386636/162152762-6ef2efea-c641-43d2-8c44-c0a08ff13b72.png)
And here is the log:
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/8440909/install-x64-windows-dbg-out.log)

**Additional context**
I'm simply trying to install openimageio library.

**Comment by Adela0814** [comment]
`x86_64: fatal: more than one input file specified`

**Comment by choobek** [comment]
Yep. I saw this error about "more than one input file" in the log but I didn't realise that it's about the path with space.

After changing the path - vcpkg successfully installed it! Thank you @dg0yt !
