### ISSUE TITLE
[openblas,metis] Link debug version first?

### ISSUE THREAD

**Issue by whuaegeanse** [microsoft/vcpkg#24036]
When building [suitesparse](https://github.com/sergiud/SuiteSparse.git), libs like openblas and metis has been installed via vcpkg and  imported to the project via CMake.  However libs like openblas and metis link Debug version first. Why?
Steps:
./vcpkg install openblas:x64-windows metis:x64-windows
![image](https://user-images.githubusercontent.com/8711991/162390861-83cb4b24-a7bf-4d0b-a212-cf01c7b6816c.png)
![image](https://user-images.githubusercontent.com/8711991/162390880-37b5cc14-92b4-4ceb-b6c5-6804a132fbba.png)
![image](https://user-images.githubusercontent.com/8711991/162391284-c030384a-d12f-4a87-ab3e-32bdffa78b85.png)

**Comment by JackBoosY** [comment]
Did you use vcpkg toolchain?

**Comment by Neumann-A** [comment]
Multi config generators don't work correctly with all ports in vcpkg.

**Comment by whuaegeanse** [comment]
> Did you use vcpkg toolchain?

Yes
![image](https://user-images.githubusercontent.com/8711991/162412495-1c39b0ab-583e-42a9-b3c6-4a4c1f2dcdaf.png)

**Comment by whuaegeanse** [comment]
> @whuaegeanse Can you please provide a sample cmake code to reproduce this?

Here:
https://github.com/sergiud/SuiteSparse

Steps:
(1) install openblas:x64-windows metis:x64-windows via vcpkg;
(2) Use vcpkg chain to build suitesparse via CMake.

**Comment by JackBoosY** [comment]
Marked as port bug temporary.
