### ISSUE TITLE
[New Port Request] litehtml

### ISSUE THREAD

**Issue by fawdlstty** [microsoft/vcpkg#24034]
Library name: litehtml

Library description: Fast and lightweight HTML/CSS rendering engine

Source repository URL: <https://github.com/litehtml/litehtml>

Project homepage (if different from the source repository): <http://www.litehtml.com/>

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by Neumann-A** [comment]
Please be aware that `qttools` needs a dependency on litehtml and remove the vendoring of the dependency.

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
