### ISSUE TITLE
[wxwidgets] Linux linkage binary and flags problem

### ISSUE THREAD

**Issue by talregev** [microsoft/vcpkg#24038]
Linux linkage binary and flags problem.

**Host Environment**
- OS: Linux/wsl
- Compiler: revision

**To Reproduce**
`./vcpkg install wxwidgets`

**Failure logs**
-Cut and paste the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

There is issues that need to be fix:
* tools/wxwidgets/wx-config is link to packages instead to lib
* tools/wxwidgets/wxrc is link to packages instead to tools
* lib/wx/config/gtk3-unicode-static-3.1  `--cppflags`/`--cflags`/`--cxxflags` options, the output of the include folders are linked to packages instead of include folder.
 
 ![image](https://user-images.githubusercontent.com/7043539/160748206-c208627c-3226-4c40-9ee8-3ce1c147618c.png) 
 ![image](https://user-images.githubusercontent.com/7043539/160748121-253704f9-a0a9-474f-b93a-df95b22061d5.png)

I already report it on the merge PR https://github.com/microsoft/vcpkg/pull/23765#issuecomment-1082591395.
I already ask help from @JackBoosY and @dg0yt and didn't get any respond.
So I am open an issue.

**Comment by JackBoosY** [comment]
Okay, I will handle this in the next week. Sorry for no reply.

**Comment by talregev** [comment]
> Okay, I will handle this in the next week. Sorry for no reply.
> 
> You can see how busy I am: ![image](https://user-images.githubusercontent.com/47264268/162402922-2c7c6693-31d2-423d-9ed5-43c49c136836.png)

Witch of them is wxwidgets issue?

**Comment by JackBoosY** [comment]
> > Okay, I will handle this in the next week. Sorry for no reply.
> > You can see how busy I am: ![image](https://user-images.githubusercontent.com/47264268/162402922-2c7c6693-31d2-423d-9ed5-43c49c136836.png)
> 
> which of them is wxwidgets issue?

three.

**Comment by talregev** [comment]
I see you have open discord. Can we also talk via discord?

**Comment by dg0yt** [comment]
I had some success with mingw (which is closer to Linux thant Windows in some regards) now and CMake's find module. 
This attempt was eye-opening. So I can make some improvements for single-config usage. But multi-config (Visual Studio?) might be a separate task.

**Comment by dg0yt** [comment]
@JackBoosY cf. #24047.
