### ISSUE TITLE
[gdk-pixbuf] Build error

### ISSUE THREAD

**Issue by yhl798999** [microsoft/vcpkg#24037]
**Host Environment**
- OS: [docker container for Ubuntu:20.04]
- Compiler: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

**To Reproduce**
`./vcpkg install opencv3`

**Failure logs**
```
Starting package 1/12: gdk-pixbuf:x64-linux
Building package gdk-pixbuf[core]:x64-linux...
-- Using cached gdk-pixbuf-2.42.2.tar.xz.
-- Cleaning sources at /vcpkg/buildtrees/gdk-pixbuf/src/k-pixbuf-2-de66e4ea53.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /vcpkg/downloads/gdk-pixbuf-2.42.2.tar.xz
-- Applying patch fix_build.patch
-- Applying patch fix_build_error_windows.patch
-- Using source at /vcpkg/buildtrees/gdk-pixbuf/src/k-pixbuf-2-de66e4ea53.clean
-- Getting CMake variables for x64-linux-dbg
-- Getting CMake variables for x64-linux-rel
-- Configuring x64-linux-dbg
-- Configuring x64-linux-dbg done
-- Configuring x64-linux-rel
-- Configuring x64-linux-rel done
-- Package x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:128 (message):
    Command failed: /vcpkg/downloads/tools/ninja/1.10.2-linux/ninja install -v
    Working Directory: /vcpkg/buildtrees/gdk-pixbuf/x64-linux-dbg
    Error code: 1
    See logs for more information:
      /vcpkg/buildtrees/gdk-pixbuf/package-x64-linux-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_meson.cmake:53 (vcpkg_execute_required_process)
  ports/gdk-pixbuf/portfile.cmake:40 (vcpkg_install_meson)
  scripts/ports.cmake:145 (include)
```
**Additional context**
1) I modified the vcpkg/triplets/x64-linux.cmake and set VCPKG_LIBRARY_LINKAGE to dynamic

2) the last 2 logs from /vcpkg/buildtrees/gdk-pixbuf/package-x64-linux-dbg-out.log:
```
[92/120] /usr/bin/cc -Itests/pixbuf-scale.p -Itests -I../src/k-pixbuf-2-de66e4ea53.clean/tests -I. -I../src/k-pixbuf-2-de66e4ea53.clean -Igdk-pixbuf -I../src/k-pixbuf-2-de66e4ea53.clean/gdk-pixbuf -I/vcpkg/installed/x64-linux/debug/lib/pkgconfig/../../../include/glib-2.0 -I/vcpkg/installed/x64-linux/debug/lib/pkgconfig/../../lib/glib-2.0/include -I/vcpkg/installed/x64-linux/debug/lib/pkgconfig/../../../include -I/vcpkg/installed/x64-linux/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c99 -g -D_POSIX_C_SOURCE=200809L -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=700 -DGDK_PIXBUF_RELOCATABLE -DHAVE_CONFIG_H=1 -fPIC -g -pthread -Wpointer-arith -Wformat=2 -Wstrict-prototypes -Wnested-externs -Wold-style-definition -Wdeclaration-after-statement -Wunused -Wcast-align -Wmissing-noreturn -Wmissing-format-attribute -Wlogical-op -fno-strict-aliasing -Wno-int-conversion -Wno-uninitialized -Wno-discarded-qualifiers -Werror=implicit -Werror=nonnull -Werror=init-self -Werror=main -Werror=missing-braces -Werror=sequence-point -Werror=return-type -Werror=trigraphs -Werror=array-bounds -Werror=write-strings -Werror=address -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -Werror=empty-body -fvisibility=hidden -MD -MQ tests/pixbuf-scale.p/pixbuf-scale.c.o -MF tests/pixbuf-scale.p/pixbuf-scale.c.o.d -o tests/pixbuf-scale.p/pixbuf-scale.c.o -c ../src/k-pixbuf-2-de66e4ea53.clean/tests/pixbuf-scale.c
ninja: build stopped: subcommand failed.
```

**Comment by dg0yt** [comment]
> the last 2 logs from /vcpkg/buildtrees/gdk-pixbuf/package-x64-linux-dbg-out.log:

The error is somewhere before these lines. ninja runs parallel jobs, and the output continues until all parallel jobs are finished.

**Comment by yhl798999** [comment]
> > the last 2 logs from /vcpkg/buildtrees/gdk-pixbuf/package-x64-linux-dbg-out.log:
> 
> The error is somewhere before these lines. ninja runs parallel jobs, and the output continues until all parallel jobs are finished.

I use "stderr" to search the log, the error is :
error while loading shared libraries: libpcre.so: cannot open shared object file: No such file or directory.
Then I use "find / -name libpcre.so" to search these missing libraries, the result is:
/vcpkg/installed/x64-linux/lib/libpcre.so
/vcpkg/installed/x64-linux/debug/lib/libpcre.so
/vcpkg/buildtrees/pcre/x64-linux-dbg/libpcre.so
/vcpkg/buildtrees/pcre/x64-linux-rel/libpcre.so
/vcpkg/packages/pcre_x64-linux/lib/libpcre.so
/vcpkg/packages/pcre_x64-linux/debug/lib/libpcre.so

**Comment by yhl798999** [comment]
> > > the last 2 logs from /vcpkg/buildtrees/gdk-pixbuf/package-x64-linux-dbg-out.log:
> > 
> > 
> > The error is somewhere before these lines. ninja runs parallel jobs, and the output continues until all parallel jobs are finished.
> 
> I use "stderr" to search the log, the error is : error while loading shared libraries: libpcre.so: cannot open shared object file: No such file or directory. Then I use "find / -name libpcre.so" to search these missing libraries, the result is: /vcpkg/installed/x64-linux/lib/libpcre.so /vcpkg/installed/x64-linux/debug/lib/libpcre.so /vcpkg/buildtrees/pcre/x64-linux-dbg/libpcre.so /vcpkg/buildtrees/pcre/x64-linux-rel/libpcre.so /vcpkg/packages/pcre_x64-linux/lib/libpcre.so /vcpkg/packages/pcre_x64-linux/debug/lib/libpcre.so

I use "apt-get install libpcre3-dev" to install the missing library, and this time the error is missing libffi.so, so I guess installing all missing libraries by myself is not a good way.

**Comment by dg0yt** [comment]
> error while loading shared libraries: libpcre.so: cannot open shared object file: No such file or directory.

IIUC some tool failed to run. It would be more helpful to know the tool.

> I use "apt-get install libpcre3-dev" to install the missing library

libpcre3-dev doesn't provide libpcre.so (itself). I guess the problem isn't Ubuntu packages, it is a vcpkg packages.

FTR if you enabled dynamic linkage on linux: it is untested, and the key gap is making shared objects available for tools. The supported x64-linux triplet has static linkage, so it wouldn't build libpcre.so.

**Comment by yhl798999** [comment]
>
Thanks! Eventually I gave up on using dynamic libraries. 
After installing libpcre3-dev & libffi-dev, the installation process continues.
