### ISSUE TITLE
[gdal] Could not find a configuration file for package "PROJ4" that is compatible   with requested version ""

### ISSUE THREAD

**Issue by whuaegeanse** [microsoft/vcpkg#24035]
**Describe the bug**
When importing GDAL installed via vcpkg in CMake, MSVC_TOOLSET_VERSION of PROJ4 is incompatible with the one used by the project.

**Environment**
- OS:Windows 10
- Compiler: Visual Studio 2017
- Three versions Visual Studio(2017，2019，2022) have been installed in my computer.

**To Reproduce**
1. ./vcpkg install gdal:x64-windows
2. Configure the project via CMake
![image](https://user-images.githubusercontent.com/8711991/162381318-ac5c27f1-7e18-4525-b74e-287f98502fa5.png)
![image](https://user-images.githubusercontent.com/8711991/162381372-643dfb2c-5675-4153-a1b7-20bbf238e4c8.png)
![image](https://user-images.githubusercontent.com/8711991/162381771-ebc4c150-ad45-4d22-9dad-7ff28e26eeb1.png)

**Expected behavior**
Libraries installed via vcpkg, should be binary compatible regardless of the version of Visual Studio (above 2015).

**Failure logs**
```
CMake Error at D:/ThirdLibs/vcpkg/vcpkg/scripts/buildsystems/vcpkg.cmake:816 (_find_package):
  Could not find a configuration file for package "PROJ4" that is compatible
  with requested version "".

  The following configuration files were considered but not accepted:

    D:/ThirdLibs/vcpkg/vcpkg/installed/x64-windows/share/proj4/proj4-config.cmake, version: 9.0.0 (MSVC_TOOLSET_VERSION = 143)

Call Stack (most recent call first):
  D:/ThirdLibs/vcpkg/vcpkg/installed/x64-windows/share/gdal/vcpkg-cmake-wrapper.cmake:37 (find_package)
  D:/ThirdLibs/vcpkg/vcpkg/installed/x64-windows/share/gdal/vcpkg-cmake-wrapper.cmake:138 (_gdal_add_dependency)
  D:/ThirdLibs/vcpkg/vcpkg/scripts/buildsystems/vcpkg.cmake:770 (include)
  CMakeLists.txt:113 (find_package)
```

**Comment by dg0yt** [comment]
IIUC this is unrelated to port `gdal`, except that occuring in dependency lookup for `find_package(GDAL)`:
The exported config of `proj` recorded a `MSVC_TOOLSET_VERSION` which is not compatible with the user project.
But `proj` is a regular CMake build, so vcpkg should have selected the toolset version based on target triplet.

Is it okay to choose a different toolset in the user project while using the vcpkg CMake toolchain? (I really don't know, no VS here.)

**Comment by whuaegeanse** [comment]
> IIUC this is unrelated to port `gdal`, except that occuring in dependency lookup for `find_package(GDAL)`: The exported config of `proj` recorded a `MSVC_TOOLSET_VERSION` which is not compatible with the user project. But `proj` is a regular CMake build, so vcpkg should have selected the toolset version based on target triplet.
> 
> Is it okay to choose a different toolset in the user project while using the vcpkg CMake toolchain? (I really don't know, no VS here.)

Configured the project with Visual Studio 2022 without encountering the above issues.

**Comment by whuaegeanse** [comment]
@dg0yt I figured out the reason of the bug this weekend.  Could you add a new port version before PROJ's team fix it?

**Comment by dg0yt** [comment]
@whuaegeanse I still didn't understand if this is a vcpkg error or a user error. I know little about `MSVC_TOOLSET_VERSION` but I guess it is recorded because it is relevant for compatibility.

**Comment by whuaegeanse** [comment]
@dg0yt My misunderstanding about binary compatibility. Thanks.
