### ISSUE TITLE
How does `vcpkg` know which libs to link in Visual Studio?

### ISSUE THREAD

**Issue by playgithub** [microsoft/vcpkg#24040]
When `vcpkg` is integrated with Visual Studio by `vcpkg integrate install`, how does it know which libs to link?

**Comment by heheda123123** [comment]
> It simply links everything

How can I know which libs to link if I use cmake?
I only have two lines below
```
The package poco is compatible with built-in CMake targets:

    find_package(Poco REQUIRED [COMPONENTS <libs>...])
    target_link_libraries(main PRIVATE Poco::<libs>)
```

**Comment by autoantwort** [comment]
You have to take a look at the poco documentation
