### ISSUE TITLE
How do I use shared libraries on Linux

### ISSUE THREAD

**Issue by diehard2** [microsoft/vcpkg#24048]
vcpkg is creating static libraries in manifest mode. Ideally I would like to use shared libraries. Is there a way to force that?

**Comment by mathisloge** [comment]
https://github.com/microsoft/vcpkg/discussions/19127

**Comment by JackBoosY** [comment]
You can add a new triplet file `x64-linux-dynamic.cmake` in _VCPKG_ROOT/triplets_ and write the following code:
```cmake
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)

set(VCPKG_CMAKE_SYSTEM_NAME Linux)
```
Then use `--triplet=x64-linux-dynamic` in the install command.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
