### ISSUE TITLE
[librabbitmq] Build error including

### ISSUE THREAD

**Issue by Flig** [microsoft/vcpkg#24052]
**Host Environment**
- OS: `Windows`
- Compiler: `MSVC 2019`

**To Reproduce**
`vcpkg.exe install librabbitmq`

**Failure logs**

  C:/Users/user/source/vcpkg/downloads/tools/msys2/9a1ec3f33446b195/mingw32/bin/pkg-config.exe
  --exists librabbitmq failed with error code: 1

      ENV{PKG_CONFIG_PATH}: "C:/Users/user/source/vcpkg/packages/librabbitmq_x64-windows/lib/pkgconfig;C:/Users/user/source/vcpkg/packages/librabbitmq_x64-windows/share/pkgconfig;C:/Users/user/source/vcpkg/installed/x64-windows/lib/pkgconfig;C:/Users/user/source/vcpkg/installed/x64-windows/share/pkgconfig"
      output: `Package openssl was not found` in the pkg-config search path.

  Perhaps you should add the directory containing `openssl.pc'

  to the PKG_CONFIG_PATH environment variable

  Package 'openssl', required by 'librabbitmq', not found
Call Stack (most recent call first):
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:201 (z_vcpkg_fixup_pkgconfig_check_files)
  ports/librabbitmq/portfile.cmake:26 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:145 (include)

error: building librabbitmq:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+librabbitmq
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[librabbitmq]+Build+error
including:
  package: librabbitmq[core]:x64-windows -> 0.11.0#1
    vcpkg-tool version: 2022-03-30-692785ac944e81417840c6de244fb3e18a4b35eb
    vcpkg-scripts version: bd1ef2df4 2022-04-08 (3 hours ago)

Additionally, attach any relevant sections from the log files above.

**Additional context**
It says OpenSSL cant be found, but openssl is installed:

```C:\Users\user\source\vcpkg>vcpkg.exe install openssl
Computing installation plan...
The following packages are already installed:
    openssl[core]:x64-windows -> 1.1.1k#5
Package openssl:x64-windows is already installed
Restored 0 packages from C:\Users\user\AppData\Local\vcpkg\archives in 262.9 us. Use --debug to see more details.

Total elapsed time: 91.9 ms

The package openssl is compatible with built-in CMake targets:

    find_package(OpenSSL REQUIRED)
    target_link_libraries(main PRIVATE OpenSSL::SSL OpenSSL::Crypto)```

**Comment by dg0yt** [comment]
> openssl[core]:x64-windows -> 1.1.1k#5

One year old security software, seriously?
The vcpkg port lacked `openssl.pc` at that time, but it is fixed now.
So two reason to upgrade.

**Comment by Flig** [comment]
Thanks, i miss that part!
