### ISSUE TITLE
[intel-mkl] Build error

### ISSUE THREAD

**Issue by JoJofun** [microsoft/vcpkg#24051]
**Host Environment**
- OS: Ubuntu 20.04 (WSL)
- Compiler: g++

**To Reproduce**
`./vcpkg install intel-mkl`

**Failure logs**
Building package intel-mkl[core]:x64-linux...
CMake Error at ports/intel-mkl/portfile.cmake:23 (message):
  Could not find MKL.  Before continuing, please download and install MKL
  (20200000 or higher) from:

      https://registrationcenter.intel.com/en/products/download/3178/

  Also ensure vcpkg has been rebuilt with the latest version (v0.0.104 or
  later)
Call Stack (most recent call first):
  scripts/ports.cmake:145 (include)

error: building intel-mkl:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `./vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+intel-mkl
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[intel-mkl]+Build+error
including:
  package: intel-mkl[core]:x64-linux -> 2020.0.0#2
    vcpkg-tool version: 2022-03-30-692785ac944e81417840c6de244fb3e18a4b35eb
    vcpkg-scripts version: unknown

**Additional context**
I've uninstalled and reinstalled vcpkg multiple times, but this seems to just be a package that doesnt want to play well
the 77 packages I required before this had no issue at all

**Comment by autoantwort** [comment]
I suggest reading the error message and do what the error message said

**Comment by JoJofun** [comment]
> I suggest reading the error message and do what the error message said

Why didn't I think of that?
Oh wait I did, and I did do it

**Comment by autoantwort** [comment]
So you have installed MKL inside your wsl. Is the env var `MKLROOT` set?

**Comment by JackBoosY** [comment]
Please test my PR https://github.com/microsoft/vcpkg/pull/15233.

**Comment by Adela0814** [comment]
@JoJofun could you please try the PR https://github.com/microsoft/vcpkg/pull/15233 and update the result. thanks.

**Comment by JoJofun** [comment]
Apologies for the delay, PR #15233 did not resolve the issue
but after a lot of research I am starting to think it might be an issue with WSL rather than vcpkg
apologies for the wild goose chase, but I am marking this as solved
thank you for helping!

**Comment by JiangTu2223** [comment]
> Apologies for the delay, PR #15233 did not resolve the issue but after a lot of research I am starting to think it might be an issue with WSL rather than vcpkg apologies for the wild goose chase, but I am marking this as solved thank you for helping!

I have met the same problem and had no idea to solve it. Could you share your solution for this? Thanks!
