### ISSUE TITLE
[New Port Request] VMime

### ISSUE THREAD

**Issue by Flig** [microsoft/vcpkg#24050]
Library name: `vmime`

Library description: ```powerful C++ class library for working with RFC-822 and MIME messages and Internet messaging services like IMAP, POP or SMTP.```

Source repository URL: [https://github.com/kisli/vmime](https://github.com/kisli/vmime)

Project homepage: [https://www.vmime.org/](https://www.vmime.org/)

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
