### ISSUE TITLE
[openssl] tool uses packages folder

### ISSUE THREAD

**Issue by aizuon** [microsoft/vcpkg#24068]
**Describe the bug**
When using the tool binary, openssl defaults to packages folder where it was built to read cnf file. 

**Environment**
- OS: Windows 11
- Compiler: msvc 14.2

**To Reproduce**
1. vcpkg.exe install openssl:x64-windows-static
2. cd installed\x64-windows-static\tools\openssl
3. openssl.exe req -x509 -newkey rsa:2048 -keyout key.pem -out cert.pem -sha256 -days 365

**Expected behavior**
openssl tool should generate a new key-cert pair

**Failure logs**
```
Can't open "<vcpkg_folder>\packages\openssl_x64-windows-static/openssl.cnf" for reading, No such file or directory
D8280000:error:80000003:system library:BIO_new_file:No such process:crypto\bio\bss_file.c:67:calling fopen(<vcpkg_folder>\packages\openssl_x64-windows-static/openssl.cnf, r)
D8280000:error:10000080:BIO routines:BIO_new_file:no such file:crypto\bio\bss_file.c:75:
```

**Additional context**
Tool should use the cnf file that exists in tool's directory

**Comment by JackBoosY** [comment]
```
   --openssldir shall be used exclusively to give the default
   location OPENSSLDIR where certificates, private keys, CRLs are
   managed.  This is also where the default openssl.cnf gets
   installed.
   --openssldir shall be used exclusively to give the default
   location OPENSSLDIR where certificates, private keys, CRLs are
   managed.  This is also where the default openssl.cnf gets
   installed.
```

**Comment by BillyONeal** [comment]
Given that the only ways that seem reasonable to 'fix' this would open up massive current directory attacks, and given that vcpkg is not intending for ports to be application delivery tools, I think we should 'wontfix' this for now. If OpenSSL provides a more reasonable way of solving this that doesn't require burning full paths to where build intermediates go that would make sense to deploy.

There are probably also additional command line or environment variable options you can set to tell `openssl.exe` where the `openssl.cnf` you want is.

**Comment by aizuon** [comment]
> Given that the only ways that seem reasonable to 'fix' this would open up massive current directory attacks, and given that vcpkg is not intending for ports to be application delivery tools, I think we should 'wontfix' this for now. If OpenSSL provides a more reasonable way of solving this that doesn't require burning full paths to where build intermediates go that would make sense to deploy.
> 
> There are probably also additional command line or environment variable options you can set to tell `openssl.exe` where the `openssl.cnf` you want is.

I can confirm that there are ways, at least one that I have discovered, stated in https://github.com/microsoft/vcpkg/pull/24076#issuecomment-1094659506 to point to cnf files. However, without this knowledge, building the openssl tool binary is simply useless because it cannot even generate basic RSA certificates and gives the error stated in this issue. So, any user who would like to do basically anything with the tool has to know that such an issue exists and cnf files must be manually introduced to the tool. This is not something like port xxx fails to build under xxx conditions, this is universal. 

Is it possible for a Microsoft representative to open an issue on the openssl repo and explain the situation in order to find ways of fixing this? As I have no knowledge of the potential security risk that would arise from exposing current directories, I don't think I would be able to explain the situation clearly. 

Also, I would like to state that I clearly remember the tool working like a year or so ago without this issue. I have used probably the exact same command to create self signing certificates and it worked, now that they are expired after a year and I had to generate new ones, the tool complains about the cnf file. 

Should this issue stay open nevertheless?

**Comment by BillyONeal** [comment]
>So, any user who would like to do basically anything with the tool has to know that such an issue exists and cnf files must be manually introduced to the tool.

That sounds like the workaround I'm suggesting yes.

Building the *tool* is not our primary aim here: vcpkg is not an application deployment system, and given that the world is not on fire for other ports' use of openssl it seems like the use as a library is fine. If building the library gives us the tool we can put somewhere, great, but....

>Is it possible for a Microsoft representative to open an issue on the openssl repo and explain the situation in order to find ways of fixing this? As I have no knowledge of the potential security risk that would arise from exposing current directories, I don't think I would be able to explain the situation clearly.

I don't see why the vcpkg team is any different than you here. (In fact, even less, considering we wouldn't be using the result so maybe they'd say 'bug fixed' but still leave you broken)

>Also, I would like to state that I clearly remember the tool working like a year or so ago without this issue. I have used probably the exact same command to create self signing certificates and it worked, now that they are expired after a year and I had to generate new ones, the tool complains about the cnf file.

It sounds like either (1) it happened to work before because your packages tree was leftover so the hard coded path still pointed to some particular place, or (2) maybe there have been changes in openssl. If I google around I see reports of the tool emitting warnings when the file isn't found, which maybe they decided to 'upgrade' into an error if there are security relevant settings in that file that you need to set.

>Should this issue stay open nevertheless?

I don't have strong opinions on whether it should stay open but I also don't think there is anything vcpkg can do to fix your problem.
