### ISSUE TITLE
python3 install requires compiler older than default

### ISSUE THREAD

**Issue by operativeF** [Microsoft/vcpkg#2407]
I'm using Windows 10 Insider build 17046 en-us. I run vcpkg install boost:x64-windows and when it gets to installing the python3 dependency, it fails, because I have the Windows 10 SDK (10.0.17046.0, v141) as the most recent, and default.

The results of trying to build python3 are here:
CMake Error at C:/vcpkg/scripts/cmake/vcpkg_execute_required_process.cmake:44 (message):
    Command failed: msbuild;C:/vcpkg/buildtrees/python3/src-x64-windows/cpython-3.6.1/PCBuild/pythoncore.vcxproj;/p:Configuration=Release;/t:Rebuild;/p:Platform=x64;/p:PlatformToolset=v141;/p:VCPkgLocalAppDataDisabled=true;/p:UseIntelMKL=No;/p:WindowsTargetPlatformVersion=10.0.17046.0;/m
    Working Directory: C:/vcpkg/buildtrees/python3/x64-windows-rel
    See logs for more information:
      C:\vcpkg\buildtrees\python3\build-x64-windows-rel-out.log
      C:\vcpkg\buildtrees\python3\build-x64-windows-rel-err.log

Call Stack (most recent call first):
  C:/vcpkg/scripts/cmake/vcpkg_build_msbuild.cmake:93 (vcpkg_execute_required_process)
  C:/vcpkg/ports/python3/portfile.cmake:58 (vcpkg_build_msbuild)
  C:/vcpkg/scripts/ports.cmake:72 (include)

Error: Building package python3:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: python3:x64-windows
  Vcpkg version: 0.0.100-2017-12-04-216f7137b9736d68e698f32154966ea68c7b98db

[build-x64-windows-rel-out.log](https://github.com/Microsoft/vcpkg/files/1574104/build-x64-windows-rel-out.log)

**Comment by LarryIII** [comment]
@operativeF Thanks for your feedback. I installed python3:x64-windows successfully. Please open a new issue if this is still a problem for you.
