### ISSUE TITLE
[wt] Build error

### ISSUE THREAD

**Issue by WesleyAertsPXL** [microsoft/vcpkg#24079]
**Host Environment**
- OS: Windows
- Compiler: Visual Studio 17 2022

**To Reproduce**
vcpkg install wt:x64-windows --triplet x86-windows

**Failure logs**
C:\Users\11900551\source\repos\webApptest> vcpkg install wt:x64-windows --triplet x86-windows
Computing installation plan...
warning: vcpkg appears to be in a Visual Studio prompt targeting x86 but is installing packages for x64-windows. Consider using --triplet x86-windows or --triplet x86-uwp.
The following packages will be built and installed:
    wt[core,openssl]:x64-windows -> 4.6.1
Detecting compiler hash for triplet x64-windows...
Restored 0 packages from C:\Users\11900551\AppData\Local\vcpkg\archives in 582.1 us. Use --debug to see more details.
Starting package 1/1: wt:x64-windows
Building package wt[core,openssl]:x64-windows...
-- Using cached emweb-wt-bc76cbea5bb845c4d0fb642968eb1b278ddbb047.tar.gz.
-- Cleaning sources at C:/Program Files/vcpkg/buildtrees/wt/src/278ddbb047-9793366655.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Program Files/vcpkg/downloads/emweb-wt-bc76cbea5bb845c4d0fb642968eb1b278ddbb047.tar.gz
-- Applying patch 0002-link-glew.patch
-- Applying patch 0005-XML_file_path.patch
-- Applying patch 0006-GraphicsMagick.patch
-- Using source at C:/Program Files/vcpkg/buildtrees/wt/src/278ddbb047-9793366655.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
CMake Warning at installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:487 (message):
  The following variables are not used in CMakeLists.txt:

      DISABLE_BOOST_AUTOLINK
      USE_SYSTEM_SQLITE3

  Please recheck them and remove the unnecessary options from the
  `vcpkg_cmake_configure` call.

  If these options should still be passed for whatever reason, please use the
  `MAYBE_UNUSED_VARIABLES` argument.
Call Stack (most recent call first):
  ports/wt/portfile.cmake:46 (vcpkg_cmake_configure)
  scripts/ports.cmake:145 (include)

-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:158 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j9
    Working Directory: C:/Program Files/vcpkg/buildtrees/wt/x64-windows-dbg
    See logs for more information:
      C:\Program Files\vcpkg\buildtrees\wt\install-x64-windows-dbg-err.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:111 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
  ports/wt/portfile.cmake:83 (vcpkg_cmake_install)
  scripts/ports.cmake:145 (include)

error: building wt:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+wt
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[wt]+Build+error
including:
  package: wt[core,openssl]:x64-windows -> 4.6.1
    vcpkg-tool version: 2022-03-30-692785ac944e81417840c6de244fb3e18a4b35eb
    vcpkg-scripts version: f6af75acc 2022-04-10 (13 hours ago)

From the log file install-x64-windows-dbg-err.log:
Error: could not load cache

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.
I've tried to install it for x64 and x86, but I get the same problem. My experience with vcpkg and c++ is extremely limited, so I could be missing something really basic. I've also tried doing the git pull and vcpkg update, but that didn't fix anything.

**Comment by Adela0814** [comment]
I cannot repro this issue, could you try using vcpkg in a path without space characters. if the issue still exist. please upload  `config-x64-windows-out.log` and `install-x64-windows-dbg-out.log.`

**Comment by Adela0814** [comment]
Sorry for the delay. Have you tried deleting the cache (empty `buildtree/wt`) and installing it in a new path without space characters?

**Comment by Adela0814** [comment]
@WesleyAertsPXL  ping~

**Comment by Adela0814** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.
