### ISSUE TITLE
[boost-exception] build failure

### ISSUE THREAD

**Issue by Masaiki** [microsoft/vcpkg#24075]
**Host Environment**
- OS: Windows 10 22H2
- Compiler: msys2 mingw-w64-x86_64-gcc-11.2.0-10

**To Reproduce**
`./vcpkg install boost-exception:x64-mingw-static`

**Failure logs**
https://pastebin.ubuntu.com/p/cbnQGPYQWN/

**Additional context**
reset to https://github.com/microsoft/vcpkg/commit/ec7b21c3f fix the problem which is the commit before my pulling

**Comment by Masaiki** [comment]
https://github.com/microsoft/vcpkg/commit/54951282f33d1ffed5fa9fa9a73a6c0466ac246d causes this.

**Comment by Masaiki** [comment]
> You may need to upgrade a number of boost modules (`vcpkg upgrade` or `vcpkg remove --recurse boost-uninstall`).

this also happens with a empty vcpkg.

**Comment by dg0yt** [comment]
Hm. I couldn't reproduce it in MSYS2, x64-mingw-static.

**Comment by dg0yt** [comment]
Your log indicates that you don't use mingw as host triplet: there are references to `x64-windows`. Is this intentional and desired? I used `x64-mingw-static` for target and host.

**Comment by dg0yt** [comment]
Can you please try this before building:
~~~
export VCPKG_DEFAULT_HOST_TRIPLET=x64-mingw-static
~~~
(I don't say you are doing it wrong. I just try to verify the context. I don't have MSVC locally.)

**Comment by Masaiki** [comment]
Another issue may be related with this, #24095

**Comment by dg0yt** [comment]
> commands and its output: https://pastebin.ubuntu.com/p/sQSMyRdBbH/

This wasn't  a clean install, such as after `vcpkg remove --recurse boost-uninstall`. These are the packages I would expect to see:
~~~
> .\vcpkg.exe install --dry-run boost-exception                                 

Computing installation plan...
The following packages will be built and installed:
  * boost-assert[core]:x64-mingw-static -> 1.78.0
  * boost-build[core]:x64-mingw-static -> 1.78.0#1
  * boost-config[core]:x64-mingw-static -> 1.78.0
  * boost-core[core]:x64-mingw-static -> 1.78.0
    boost-exception[core]:x64-mingw-static -> 1.78.0
  * boost-modular-build-helper[core]:x64-mingw-static -> 1.78.0#3
  * boost-move[core]:x64-mingw-static -> 1.78.0
  * boost-predef[core]:x64-mingw-static -> 1.78.0
  * boost-smart-ptr[core]:x64-mingw-static -> 1.78.0
  * boost-static-assert[core]:x64-mingw-static -> 1.78.0
  * boost-throw-exception[core]:x64-mingw-static -> 1.78.0
  * boost-tuple[core]:x64-mingw-static -> 1.78.0
  * boost-type-traits[core]:x64-mingw-static -> 1.78.0
  * boost-uninstall[core]:x64-mingw-static -> 1.78.0
  * boost-vcpkg-helpers[core]:x64-mingw-static -> 1.78.0#1
  * boost-winapi[core]:x64-mingw-static -> 1.78.0
Additional packages (*) will be modified to complete this operation.
~~~
(Note: it install boost-uninstall again.)

**Comment by Masaiki** [comment]
while i had tried a clean install after the comment, it still failed with same error.
here is an redo output and log
https://pastebin.ubuntu.com/p/bVJqCZ68kG/
https://pastebin.ubuntu.com/p/wWsfNGcqZp/

**Comment by dg0yt** [comment]
> [5495128](https://github.com/microsoft/vcpkg/commit/54951282f33d1ffed5fa9fa9a73a6c0466ac246d) causes this.

I think I found the error in this change, and I will prepare a PR.
(Comparing your log and my log showed two differences, a suspicious parameter and a surprising second difference. After cleaning my system, only the suspicious parameter was left... and building `boost-exception` started to fail.
And now I have to realize that [my past boost-exception trouble](https://github.com/microsoft/vcpkg/pull/23001#issuecomment-1085065407) after that commit was on x64-linux, not mingw.)

**Comment by dg0yt** [comment]
You can test #24101.

**Comment by Masaiki** [comment]
> You can test #24101.

it works, waiting for being merged.
Thanks
