### ISSUE TITLE
[libjpeg-turbo] Build er

### ISSUE THREAD

**Issue by yangmiaomiao11** [microsoft/vcpkg#24074]
**Host Environment**
- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**
`./vcpkg install xxxx`

**Failure logs**
-Cut and paste the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by JonLiu1993** [comment]
@yangmiaomiao11, Thanks for posting this question, could you provide enough information to describe your problem?
For example: operating system, compiler, steps to reproduce the behavior, failure logs...

**Comment by JonLiu1993** [comment]
Thanks for posting this issue. Please reopen this issue if it still be a problem for you
