### ISSUE TITLE
Add libc++-related triplet for linux

### ISSUE THREAD

**Issue by StarOrpheus** [microsoft/vcpkg#24086]
****

**Is your feature request related to a problem? Please describe.**
On Linux, it is impossible to work correctly on GCC and Clang toolchains simultaneously with vcpkg (`stdlibc++` vs `libc++`). It's easy to add the same custom triplet file each time, but setting up CI or teaching students how to use vcpkg may be harder than it seems.

**Proposed solution**
Create an analogue to `triplets/community/x64-mingw-*.cmake`. Like `x64-clang-static` and `x64-clang-dynamic`
```
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_CMAKE_SYSTEM_NAME Linux)
set(VCPKG_CXX_FLAGS "${VCPKG_CXX_FLAGS} -stdlib=libc++")
set(VCPKG_C_FLAGS "${VCPKG_C_FLAGS}")
```

**Describe alternatives you've considered**

It's possible to maintain a custom fork but looks like overkill for a single-file diff. 
Students struggle to install and set up toolchain, so downloading one file to a specific location and using it is kinda hard for them (tested).

**Comment by Osyotr** [comment]
This should be set in your custom toolchain file and then injected into triplet with `VCPKG_CHAINLOAD_TOOLCHAIN_FILE`.

**Comment by LilyWangLL** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.

**Comment by kreuzerkrieg** [comment]
@LilyWangLL can we reopen this issue? I would like to take it

**Comment by kreuzerkrieg** [comment]
> @LilyWangLL can we reopen this issue? I would like to take it

Is there any guidelines how the toolchainfile/triplet should be added?

**Comment by dg0yt** [comment]
Does it really need to be added to this repo? The default triplets don't enforce a particular stdlib.

**Comment by kreuzerkrieg** [comment]
> Does it really need to be added to this repo? The default triplets don't enforce a particular stdlib.

but it enforces the compiler. I want to add toolfile and triplet to build with clang and link with libstdc++. WDYT?

**Comment by JonLiu1993** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
