### ISSUE TITLE
[Tesseract] update to 5.1

### ISSUE THREAD

**Issue by quaesitor-scientiam** [microsoft/vcpkg#24085]
Library name:
**tesseract**

New version number:
**5.1**

Other information that may be useful (release notes, etc...)

**This is a new minor version of Tesseract 5.
- Handle image and line regions in output formats ALTO, hOCR and text.
- New parameter curl_timeout for curl_easy_setop.
- Build fixes and improvements.
- Catch nullptr in PageIterator::Orientation to improve robustness.
- Remove unused code.**

**Comment by JonLiu1993** [comment]
Duplicate of https://github.com/microsoft/vcpkg/issues/16019

**Comment by quaesitor-scientiam** [comment]
#16019 was for an alpha version of 5.0.0  how is that a duplicate?

**Comment by JonLiu1993** [comment]
@quaesitor-scientiam, when we update port we will update it to the latest version,I will update my pr.
