### ISSUE TITLE
[openblas] error: building openblas:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by zch-414** [microsoft/vcpkg#24097]
**Host Environment**
- OS: windows X64
- Compiler: powershell X86

**To Reproduce**
`./vcpkg install install opencv4 ceres ceres[suitesparse] lapack suitesparse --triplet x64-windows`

**Failure logs**
- package: openblas[core]:x64-windows -> 0.3.19
    vcpkg-tool version: 2022-03-30-692785ac944e81417840c6de244fb3e18a4b35eb
    vcpkg-scripts version: bd1ef2df4 2022-04-08 (4 days ago)

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by FrankXie05** [comment]
@zch-414 Thanks for posting this issue,
    Can you describe the port name that you want to install correctly?
    Please provide the error log.

**Comment by FrankXie05** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
