### ISSUE TITLE
[vcpkg] Compile flags are wrongly modified.

### ISSUE THREAD

**Issue by Nemirtingas** [microsoft/vcpkg#24095]
**Describe the bug**
Since some update (I don't know which one, I'm still looking for the commit), my compile flags are overwritten when they should not.

Maybe this lines are doing the change:
https://github.com/microsoft/vcpkg/blame/4415a0f31b5a012ca2efba13cc18e16adefd89c0/ports/vcpkg-cmake/cmake_get_vars/CMakeLists.txt#L146-L150

It appears that some ports use this code `set(CXXFLAGS "${VCPKG_COMBINED_CXX_FLAGS_${UPPER_BUILD_TYPE}}")` and inside VCPKG_COMBINED_* my flags are rewritten.

**Environment**
- OS: Ubuntu 20 for Windows
- Compiler: llvm 11 + clang 11 + clang-cl

**To Reproduce**
```
docker run --name windows_test -it nemirtingas/windowscross_vcpkg:msvc2019_win10.0.18362.0 bash
rm -rf /vcpkg
git clone https://github.com/microsoft/vcpkg
cd /vcpkg
./bootstrap-vcpkg.sh
cat >/vcpkg/triplets/community/x86-windows-nemirtingas.cmake <<EOF
set(VCPKG_TARGET_ARCHITECTURE x86)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_BUILD_TYPE release)

set(ENV{HOST_ARCH} \${VCPKG_TARGET_ARCHITECTURE})

set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE /clang_windows_sdk/clang-cl-msvc.cmake)

set(ENV{VCPKG_TOOLCHAIN} "/vcpkg/scripts/toolchains/windows.cmake")

set(VCPKG_POLICY_SKIP_ARCHITECTURE_CHECK enabled)
EOF
vcpkg install --triplet=x86-windows-nemirtingas boost-exception
```

**Expected behavior**
My flags are not modified.

**Failure logs**
```
"/usr/bin/clang-cl-11" --target=i386-pc-windows-msvc "../src/clone_current_exception_non_intrusive.cpp" -c -Fo"/vcpkg/buildtrees/boost-exception/x86-windows-nemirtingas-rel/boost/build/e89df7b4a4259fefb928dccf039f4bf8/clone_current_exception_non_intrusive.obj"     -TP /EHs /GR -Xclang -fexceptions -Xclang -fcxx-exceptions -Xclang -D_CRT_SECURE_NO_WARNINGS --target=i686-windows-msvc -fms-compatibility-version=19.11 -Wno-unused-command-line-argument -imsvc -clang_windows_sdk/msvc/include -imsvc -clang_windows_sdk/winsdk/Include/10.0.18362.0/ucrt -imsvc -clang_windows_sdk/winsdk/Include/10.0.18362.0/shared -imsvc -clang_windows_sdk/winsdk/Include/10.0.18362.0/um -imsvc -clang_windows_sdk/winsdk/Include/10.0.18362.0/winrt -Xclang -ivfsoverlay -Xclang -vcpkg/buildtrees/boost-exception/x86-windows-nemirtingas-rel/winsdk_vfs_overlay.yaml -MT -O2 -Oi -Gy -DNDEBUG -Z7 /O2 /Z7 /Ob2 /W3 /MT -DBOOST_ALL_NO_LIB=1 -DNDEBUG "-I../include" "-I/project/build/windows_vcpkg/x86-windows-nemirtingas/include" 

fatal error: virtual filesystem overlay file '-vcpkg/buildtrees/boost-exception/x86-windows-nemirtingas-rel/winsdk_vfs_overlay.yaml' not found
```

The compile options 
```
-imsvc -clang_windows_sdk/msvc/include
-imsvc -clang_windows_sdk/winsdk/Include/10.0.18362.0/ucrt
-imsvc -clang_windows_sdk/winsdk/Include/10.0.18362.0/shared
-imsvc -clang_windows_sdk/winsdk/Include/10.0.18362.0/um
-imsvc -clang_windows_sdk/winsdk/Include/10.0.18362.0/winrt
-Xclang -ivfsoverlay -Xclang -vcpkg/buildtrees/boost-exception/x86-windows-nemirtingas-rel/winsdk_vfs_overlay.yaml
```
Should stay as I originaly set them: (note the '/' instead of '-')
```
-imsvc /clang_windows_sdk/msvc/include
-imsvc /clang_windows_sdk/winsdk/Include/10.0.18362.0/ucrt
-imsvc /clang_windows_sdk/winsdk/Include/10.0.18362.0/shared
-imsvc /clang_windows_sdk/winsdk/Include/10.0.18362.0/um
-imsvc /clang_windows_sdk/winsdk/Include/10.0.18362.0/winrt
-Xclang -ivfsoverlay -Xclang /vcpkg/buildtrees/boost-exception/x86-windows-nemirtingas-rel/winsdk_vfs_overlay.yaml
```

**Additional context**

**Comment by Masaiki** [comment]
maybe this commit https://github.com/microsoft/vcpkg/commit/54951282f33d1ffed5fa9fa9a73a6c0466ac246d

**Comment by Nemirtingas** [comment]
Thanks, I'm trying to fix it on my fork. No success for now.

**Comment by Nemirtingas** [comment]
> > I removed the '/' into '-' replacement
> 
> Maybe a check is needed that the replacement is only done `if(MSCV AND WIN32)` or `CMAKE_HOST_SYSTEM_NAME` should be Linux.
> 
> `Could not find proper second linker member` Your triplet probably needs:
> 
> ```
> # set(VCPKG_POLICY_SKIP_ARCHITECTURE_CHECK enabled)
> set(VCPKG_POLICY_SKIP_DUMPBIN_CHECKS enabled) # try only this one first
> ```

I'll try ASAP and report back, thanks !

**Comment by dg0yt** [comment]
> Could not find proper second linker member

This typically happens when import `.lib` files are not generated by MSVC. I have seen this with mingw, with some ports, until restoring the standard `.dll.a`

**Comment by Neumann-A** [comment]
> 100% compatible with MSVC runtime

Its 98 % compatible. You sometimes cannot link files with `link.exe` .

**Comment by Nemirtingas** [comment]
> > 100% compatible with MSVC runtime
> 
> Its 98 % compatible. You sometimes cannot link files with `link.exe` .

Ok, if you say so :). I've updated my first post with a easy reproductible env. I'm searching now whats the best condition to not convert thoses '/' into '-'. As I'm building on Ubuntu but cross-compiling for Windows, CMAKE_HOST_SYSTEM_NAME should be Linux.

**Comment by Nemirtingas** [comment]
I just modified the condition: `if(MSVC)` into `if(MSVC AND "${CMAKE_HOST_SYSTEM_NAME}" STREQUAL "Windows")` and it works now.
Do you think its suffisent to fix this issue ? Should I make a PR ?

**Comment by Neumann-A** [comment]
>  Should I make a PR ?

Just make one.
