### ISSUE TITLE
boost-log fails to link if my project targets a different Windows version

### ISSUE THREAD

**Issue by elad8a** [microsoft/vcpkg#24099]
**Host Environment**
- OS: Windows
- Compiler: Visual Studio 2022

define a project wide preprocessor definition to target Windows 10:
_WIN32_WINNT=0x0A00;

If you try to link code that uses boost-log, it will fail. It is similar to the issue in the SO question:

(https://stackoverflow.com/questions/71120362/boost-log-linker-errors-lnk2001-lnk2019-unresolved-external-symbol-after-upgra)

**Comment by elad8a** [comment]
In general, it might be beneficial to able to specify specific flags / preprocessor macros to the library via the manifest file. currently I can only control the target platform / architecture / linkage via triplets. this case illustrates that this is not enough.

**Comment by JackBoosY** [comment]
Is this issue same with https://github.com/microsoft/vcpkg/discussions/22762?

**Comment by JackBoosY** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
