### ISSUE TITLE
FAQ unclear

### ISSUE THREAD

**Issue by steronydh** [Microsoft/vcpkg#2410]
Under the section ["How do I use different versions of a library on one machine?"](https://github.com/Microsoft/vcpkg/blob/master/docs/about/faq.md#how-do-i-use-different-versions-of-a-library-on-one-machine), the description

> The versions of each library are specified by the files in ports, so they are easily manipulated using standard git commands. This makes it very easy to roll back the entire set of libraries to a consistent set of older versions which all work with each other. 

is unclear. A worked example of how exactly to set up vcpkg to use a specific older version of a library would be very useful here.

**Comment by crackedmind** [comment]
You can read more information in [this blog post](https://blogs.msdn.microsoft.com/vcblog/2017/10/23/vcpkg-using-multiple-enlistments/)
