### ISSUE TITLE
[boost] Boost uses non-CONFIG mode and doesn't work in CONFIG mode?

### ISSUE THREAD

**Issue by patrikhuber** [microsoft/vcpkg#24107]
Hi,

I believe the Boost port in vcpkg doesn't work in CMake's `CONFIG` mode. After installing Boost, vcpkg outputs something like "Use find_package(Boost REQUIRED COMPONENTS ...)` and `target_link_libraries(<target> PRIVATE Boost::boost Boost::.....)` (sorry I haven't screenshot this and don't know where vcpkg outputs this to recreate it exactly.

When I then try to use Boost in `CONFIG` mode: `find_package(Boost REQUIRED CONFIG COMPONENTS system filesystem program_options)`, then it fails to find Boost.

As far as I am aware, more recent versions of Boost support the CONFIG mode, e.g. https://gitlab.kitware.com/cmake/cmake/-/issues/19658, https://gitlab.kitware.com/cmake/cmake/-/issues/19402.
I believe the CONFIG mode of `find_package` is the strongly preferred way of finding packages, so vcpkg should support it? Especially if a library already supports it?

**Comment by JackBoosY** [comment]
Yes.
Generally, boost use MODULE mode file `FindBoost.cmake` which provided by cmake.
But the boost now provides cmake submodule: https://github.com/boostorg/cmake.
