### ISSUE TITLE
[openssl] Build error on Windows 11

### ISSUE THREAD

**Issue by KaiTang2** [microsoft/vcpkg#24109]
**Host Environment**
- OS: [win11 x64]
 package: openssl[core]:x64-windows -> 3.0.2#2
    vcpkg-tool version: 2022-03-30-692785ac944e81417840c6de244fb3e18a4b35eb
    vcpkg-scripts version: 4415a0f31 2022-04-11 (24 hours ago)

**To Reproduce**
`./vcpkg install python3 python3:x64-windows`

**Failure logs**
Starting package 1/4: openssl:x64-windows
Building package openssl[core]:x64-windows...
-- Using cached openssl-3.0.2.tar.gz.
-- Cleaning sources at E:/GitHub/vcpkg/buildtrees/openssl/src/openssl-3-67d457a95e.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/GitHub/vcpkg/downloads/openssl-3.0.2.tar.gz
-- Using source at E:/GitHub/vcpkg/buildtrees/openssl/src/openssl-3-67d457a95e.clean
-- Copying openssl release source files...
-- Copying openssl release source files... done
-- Configure x64-windows-rel
-- Configure x64-windows-rel done
-- Build x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:128 (message):
    Command failed: E:/GitHub/vcpkg/downloads/tools/jom/jom-1.1.3/jom.exe -j 1 -f makefile install_sw install_ssldirs
    Working Directory: E:/GitHub/vcpkg/buildtrees/openssl/x64-windows-rel
    Error code: 2
    See logs for more information:
      E:\GitHub\vcpkg\buildtrees\openssl\build-x64-windows-rel-1-out.log
      E:\GitHub\vcpkg\buildtrees\openssl\build-x64-windows-rel-1-err.log

Call Stack (most recent call first):
  ports/openssl/windows/portfile.cmake:84 (vcpkg_execute_required_process)
  ports/openssl/portfile.cmake:31 (include)
  scripts/ports.cmake:145 (include)

**Additional context**
[build-x64-windows-rel-1-err.log](https://github.com/microsoft/vcpkg/files/8477340/build-x64-windows-rel-1-err.log)
[build-x64-windows-rel-1-out.log](https://github.com/microsoft/vcpkg/files/8477341/build-x64-windows-rel-1-out.log)

**Comment by JackBoosY** [comment]
```
cl : Command line error D8050 : cannot execute 'C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\bin\HostX64\x64\c1.dll': failed to get command line into debug records
```

**Comment by Adela0814** [comment]
This seems to be a problem with your VS settings，could you please repair your VS and try again.
![image](https://user-images.githubusercontent.com/95600143/163130644-eeb42fa0-32a6-4546-9694-7a10acc74e98.png)

**Comment by KaiTang2** [comment]
@Adela0814  thanks for your help,I tried it again as you said,but it still has this problem.

**Comment by Adela0814** [comment]
Can you try it with a new VS? sorry, I'm not sure which setting is wrong.

**Comment by KaiTang2** [comment]
@Adela0814  I use another compute with new os, install vs2019 ,then try it again, it still has this problem.

**Comment by justin-bj** [comment]
> Can you try it with a new VS? sorry, I'm not sure which setting is wrong.

I tried vs2022, but it still didn't work.

**Comment by JackBoosY** [comment]
Did you use cmd instead of powershell? We prefer to use powershell since there are some operations which need to be executed.

**Comment by justin-bj** [comment]
> Did you use cmd instead of powershell? We prefer to use powershell since there are some operations which need to be executed.

I tried it again with PowerShell with administrator privileges, and the error remained the same

**Comment by justin-bj** [comment]
Does vcpkg not support Windows 11?

**Comment by JackBoosY** [comment]
> Does vcpkg not support Windows 11?

Will try to reproduce this issue on Windows 11 later.

**Comment by justin-bj** [comment]
thanks. windows 11 home edition



---Original---
From: ***@***.***&gt;
Date: Mon, Apr 18, 2022 21:57 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [microsoft/vcpkg] [openssl] Build error on Windows 11 (Issue#24109)




  
Does vcpkg not support Windows 11?
  
Will try to reproduce this issue on Windows 11 later.

**Comment by justin-bj** [comment]
Guys, any progress? Has the problem been solved?

**Comment by JackBoosY** [comment]
Sorry for late, I will try to reproduce this in the next week.

**Comment by JackBoosY** [comment]
I can't reproduce this issue on Windows 11 locally.

**Comment by JackBoosY** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.
