### ISSUE TITLE
Is it possible to change the output DLL name of protobuf?

### ISSUE THREAD

**Issue by IIFE** [microsoft/vcpkg#24106]
Hi.

Is there a way to install protobuf with vcpkg such that the produced lib/dll names are customizeable?

For example protobuf currently builds the output as libprotobuf.lib/libprotobuf.dll, but is it possible for example to make it build as libprotobuf_v2.lib/libprotobuf_v2.dll (just for illustration purposes)?

Note I don't mean renaming the product binaries, but rather I want the produced binaries to be in a specific name, in a way that when an app links against protobuf it will look for a DLL that matches the new name (rather than libprotobuf.dll).

Thanks.

**Comment by LilyWangLL** [comment]
I think this question should go to the upstream of [protobuf](https://github.com/protocolbuffers/protobuf), they have more experience about use of `protobuf`.

**Comment by IIFE** [comment]
@LilyWangLL Thanks. I'm installing protobuf through vcpkg, so isn't this related to if vcpkg can allow installing a port with a chosen output name?

**Comment by Nemirtingas** [comment]
vcpkg only builds packages and doesn't modify how they are built. The output name is ambiguous. The library contains references to the library name. Only changing the .lib or .dll name might not be sufficient to "rename" it at link time.
vcpkg provides a convenient way to build libraries with their dependencies without you to download, setup and build them by hand.

**Comment by LilyWangLL** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
