### ISSUE TITLE
vcpkg search fail!

### ISSUE THREAD

**Issue by uuiid** [microsoft/vcpkg#24116]
```
PS E:\vcpkg> .\vcpkg.exe search sqlite
The result may be outdated. Run `git pull` to get the latest results.

If your port is not listed, please open an issue at and/or consider making a pull request:
    https://github.com/Microsoft/vcpkg/issues
PS E:\vcpkg> .\vcpkg install sqlite3
Error: invalid triplet: x86-windows
Available architecture triplets
VCPKG built-in triplets:

VCPKG community triplets:  
```
![image](https://user-images.githubusercontent.com/46096697/163152556-8160cfa5-21cc-4bf0-811a-545edc0e9317.png)

![image](https://user-images.githubusercontent.com/46096697/163152595-3f028d41-0d7d-44cc-927b-2a0c9fff6534.png)

![image](https://user-images.githubusercontent.com/46096697/163152778-81c80572-6782-4ac7-b520-97e160747fd1.png)

**Comment by autoantwort** [comment]
Your complete installation seems broken. Maybe try to delete vcpkg and clone it again.

**Comment by uuiid** [comment]
I reinstall it. There's still a problem
![vcpkg](https://user-images.githubusercontent.com/46096697/163295654-86c694f5-b507-416a-9645-bed92cd9137a.gif)

**Comment by uuiid** [comment]
`vcpkg.exe integrate install` fail
![image](https://user-images.githubusercontent.com/46096697/163295977-07cdf48a-55e4-4cda-bd52-04256dc42a21.png)
