### ISSUE TITLE
[boost-python] Build error

### ISSUE THREAD

**Issue by 70565912** [microsoft/vcpkg#24115]
**Host Environment**
- OS: Windows
- Compiler: msvc

**To Reproduce**
`./vcpkg install boost:x64-windows`

**Failure logs**

msvc.write-setup-script E:\SDK\vcpkg\buildtrees\boost-python\x64-windows-dbg\boost\standalone\msvc\943897acc6555446e7558f53bf1a3e85\msvc-setup.bat

    type "C:\Users\MSI\AppData\Local\Temp\jam4078841c.000" > "E:\SDK\vcpkg\buildtrees\boost-python\x64-windows-dbg\boost\standalone\msvc\943897acc6555446e7558f53bf1a3e85\msvc-setup.bat"

compile-c-c++ E:\SDK\vcpkg\buildtrees\boost-python\x64-windows-dbg\boost\build\64f7401830e536b590f94641995357c1\list.obj

    call "E:\SDK\vcpkg\buildtrees\boost-python\x64-windows-dbg\boost\standalone\msvc\943897acc6555446e7558f53bf1a3e85\msvc-setup.bat" amd64 >nul
 cl "..\src\list.cpp" -c -Fo"E:\SDK\vcpkg\buildtrees\boost-python\x64-windows-dbg\boost\build\64f7401830e536b590f94641995357c1\list.obj"     -TP /wd4675 /EHs /GR /Zc:throwingNew -nologo -DWIN32 -D_WINDOWS -W3 -utf-8 -GR -EHsc -MP -D_DEBUG -MDd -Z7 -Ob0 -Od -RTC1 /Z7 /Od /Ob0 /W3 /MDd /Zc:forScope /Zc:wchar_t /Zc:inline /favor:blend -DBOOST_ALL_NO_LIB=1 -DBOOST_PYTHON_SOURCE "-I..\include" "-IE:\SDK\vcpkg\installed\x64-windows\include" "-IE:\SDK\vcpkg\installed\x64-windows\include\python3.10;E:\SDK\vcpkg\installed\x64-windows\include\python3.9" 

list.cpp
E:\SDK\vcpkg\buildtrees\boost-python\src\ost-1.78.0-84b9faa522.clean\include\boost/python/detail/wrap_python.hpp(57): fatal error C1083: 无法打开包括文件: “pyconfig.h”: No such file or directory
compile-c-c++ E:\SDK\vcpkg\buildtrees\boost-python\x64-windows-dbg\boost\build\64f7401830e536b590f94641995357c1\long.obj

    call "E:\SDK\vcpkg\buildtrees\boost-python\x64-windows-dbg\boost\standalone\msvc\943897acc6555446e7558f53bf1a3e85\msvc-setup.bat" amd64 >nul
 cl "..\src\long.cpp" -c -Fo"E:\SDK\vcpkg\buildtrees\boost-python\x64-windows-dbg\boost\build\64f7401830e536b590f94641995357c1\long.obj"     -TP /wd4675 /EHs /GR /Zc:throwingNew -nologo -DWIN32 -D_WINDOWS -W3 -utf-8 -GR -EHsc -MP -D_DEBUG -MDd -Z7 -Ob0 -Od -RTC1 /Z7 /Od /Ob0 /W3 /MDd /Zc:forScope /Zc:wchar_t /Zc:inline /favor:blend -DBOOST_ALL_NO_LIB=1 -DBOOST_PYTHON_SOURCE "-I..\include" "-IE:\SDK\vcpkg\installed\x64-windows\include" "-IE:\SDK\vcpkg\installed\x64-windows\include\python3.10;E:\SDK\vcpkg\installed\x64-windows\include\python3.9" 

long.cpp
E:\SDK\vcpkg\buildtrees\boost-python\src\ost-1.78.0-84b9faa522.clean\include\boost/python/detail/wrap_python.hpp(57): fatal error C1083: 无法打开包括文件: “pyconfig.h”: No such file or directory
compile-c-c++ E:\SDK\vcpkg\buildtrees\boost-python\x64-windows-dbg\boost\build\64f7401830e536b590f94641995357c1\dict.obj

    call "E:\SDK\vcpkg\buildtrees\boost-python\x64-windows-dbg\boost\standalone\msvc\943897acc6555446e7558f53bf1a3e85\msvc-setup.bat" amd64 >nul
 cl "..\src\dict.cpp" -c -Fo"E:\SDK\vcpkg\buildtrees\boost-python\x64-windows-dbg\boost\build\64f7401830e536b590f94641995357c1\dict.obj"     -TP /wd4675 /EHs /GR /Zc:throwingNew -nologo -DWIN32 -D_WINDOWS -W3 -utf-8 -GR -EHsc -MP -D_DEBUG -MDd -Z7 -Ob0 -Od -RTC1 /Z7 /Od /Ob0 /W3 /MDd /Zc:forScope /Zc:wchar_t /Zc:inline /favor:blend -DBOOST_ALL_NO_LIB=1 -DBOOST_PYTHON_SOURCE "-I..\include" "-IE:\SDK\vcpkg\installed\x64-windows\include" "-IE:\SDK\vcpkg\installed\x64-windows\include\python3.10;E:\SDK\vcpkg\installed\x64-windows\include\python3.9" 

dict.cpp
E:\SDK\vcpkg\buildtrees\boost-python\src\ost-1.78.0-84b9faa522.clean\include\boost/python/detail/wrap_python.hpp(57): fatal error C1083: 无法打开包括文件: “pyconfig.h”: No such file or directory
compile-c-c++ E:\SDK\vcpkg\buildtrees\boost-python\x64-windows-dbg\boost\build\64f7401830e536b590f94641995357c1\tuple.obj

    call "E:\SDK\vcpkg\buildtrees\boost-python\x64-windows-dbg\boost\standalone\msvc\943897acc6555446e7558f53bf1a3e85\msvc-setup.bat" amd64 >nul
 cl "..\src\tuple.cpp" -c -Fo"E:\SDK\vcpkg\buildtrees\boost-python\x64-windows-dbg\boost\build\64f7401830e536b590f94641995357c1\tuple.obj"     -TP /wd4675 /EHs /GR /Zc:throwingNew -nologo -DWIN32 -D_WINDOWS -W3 -utf-8 -GR -EHsc -MP -D_DEBUG -MDd -Z7 -Ob0 -Od -RTC1 /Z7 /Od /Ob0 /W3 /MDd /Zc:forScope /Zc:wchar_t /Zc:inline /favor:blend -DBOOST_ALL_NO_LIB=1 -DBOOST_PYTHON_SOURCE "-I..\include" "-IE:\SDK\vcpkg\installed\x64-windows\include" "-IE:\SDK\vcpkg\installed\x64-windows\include\python3.10;E:\SDK\vcpkg\installed\x64-windows\include\python3.9" 

tuple.cpp
E:\SDK\vcpkg\buildtrees\boost-python\src\ost-1.78.0-84b9faa522.clean\include\boost/python/detail/wrap_python.hpp(57): fatal error C1083: 无法打开包括文件: “pyconfig.h”: No such file or directory
compile-c-c++ E:\SDK\vcpkg\buildtrees\boost-python\x64-windows-dbg\boost\build\64f7401830e536b590f94641995357c1\str.obj

    call "E:\SDK\vcpkg\buildtrees\boost-python\x64-windows-dbg\boost\standalone\msvc\943897acc6555446e7558f53bf1a3e85\msvc-setup.bat" amd64 >nul
 cl "..\src\str.cpp" -c -Fo"E:\SDK\vcpkg\buildtrees\boost-python\x64-windows-dbg\boost\build\64f7401830e536b590f94641995357c1\str.obj"     -TP /wd4675 /EHs /GR /Zc:throwingNew -nologo -DWIN32 -D_WINDOWS -W3 -utf-8 -GR -EHsc -MP -D_DEBUG -MDd -Z7 -Ob0 -Od -RTC1 /Z7 /Od /Ob0 /W3 /MDd /Zc:forScope /Zc:wchar_t /Zc:inline /favor:blend -DBOOST_ALL_NO_LIB=1 -DBOOST_PYTHON_SOURCE "-I..\include" "-IE:\SDK\vcpkg\installed\x64-windows\include" "-IE:\SDK\vcpkg\installed\x64-windows\include\python3.10;E:\SDK\vcpkg\installed\x64-windows\include\python3.9" 

str.cpp
E:\SDK\vcpkg\buildtrees\boost-python\src\ost-1.78.0-84b9faa522.clean\include\boost/python/detail/wrap_python.hpp(57): fatal error C1083: 无法打开包括文件: “pyconfig.h”: No such file or directory
compile-c-c++ E:\SDK\vcpkg\buildtrees\boost-python\x64-windows-dbg\boost\build\64f7401830e536b590f94641995357c1\slice.obj

    call "E:\SDK\vcpkg\buildtrees\boost-python\x64-windows-dbg\boost\standalone\msvc\943897acc6555446e7558f53bf1a3e85\msvc-setup.bat" amd64 >nul
 cl "..\src\slice.cpp" -c -Fo"E:\SDK\vcpkg\buildtrees\boost-python\x64-windows-dbg\boost\build\64f7401830e536b590f94641995357c1\slice.obj"     -TP /wd4675 /EHs /GR /Zc:throwingNew -nologo -DWIN32 -D_WINDOWS -W3 -utf-8 -GR -EHsc -MP -D_DEBUG -MDd -Z7 -Ob0 -Od -RTC1 /Z7 /Od /Ob0 /W3 /MDd /Zc:forScope /Zc:wchar_t /Zc:inline /favor:blend -DBOOST_ALL_NO_LIB=1 -DBOOST_PYTHON_SOURCE "-I..\include" "-IE:\SDK\vcpkg\installed\x64-windows\include" "-IE:\SDK\vcpkg\installed\x64-windows\include\python3.10;E:\SDK\vcpkg\installed\x64-windows\include\python3.9" 

slice.cpp
E:\SDK\vcpkg\buildtrees\boost-python\src\ost-1.78.0-84b9faa522.clean\include\boost/python/detail/wrap_python.hpp(57): fatal error C1083: 无法打开包括文件: “pyconfig.h”: No such file or directory
compile-c-c++ E:\SDK\vcpkg\buildtrees\boost-python\x64-windows-dbg\boost\build\64f7401830e536b590f94641995357c1\converter\from_python.obj

    call "E:\SDK\vcpkg\buildtrees\boost-python\x64-windows-dbg\boost\standalone\msvc\943897acc6555446e7558f53bf1a3e85\msvc-setup.bat" amd64 >nul
 cl "..\src\converter\from_python.cpp" -c -Fo"E:\SDK\vcpkg\buildtrees\boost-python\x64-windows-dbg\boost\build\64f7401830e536b590f94641995357c1\converter\from_python.obj"     -TP /wd4675 /EHs /GR /Zc:throwingNew -nologo -DWIN32 -D_WINDOWS -W3 -utf-8 -GR -EHsc -MP -D_DEBUG -MDd -Z7 -Ob0 -Od -RTC1 /Z7 /Od /Ob0 /W3 /MDd /Zc:forScope /Zc:wchar_t /Zc:inline /favor:blend -DBOOST_ALL_NO_LIB=1 -DBOOST_PYTHON_SOURCE "-I..\include" "-IE:\SDK\vcpkg\installed\x64-windows\include" "-IE:\SDK\vcpkg\installed\x64-windows\include\python3.10;E:\SDK\vcpkg\installed\x64-windows\include\python3.9" 

from_python.cpp
E:\SDK\vcpkg\buildtrees\boost-python\src\ost-1.78.0-84b9faa522.clean\include\boost/python/detail/wrap_python.hpp(57): fatal error C1083: 无法打开包括文件: “pyconfig.h”: No such file or directory
compile-c-c++ E:\SDK\vcpkg\buildtrees\boost-python\x64-windows-dbg\boost\build\64f7401830e536b590f94641995357c1\converter\registry.obj

    call "E:\SDK\vcpkg\buildtrees\boost-python\x64-windows-dbg\boost\standalone\msvc\943897acc6555446e7558f53bf1a3e85\msvc-setup.bat" amd64 >nul
 cl "..\src\converter\registry.cpp" -c -Fo"E:\SDK\vcpkg\buildtrees\boost-python\x64-windows-dbg\boost\build\64f7401830e536b590f94641995357c1\converter\registry.obj"     -TP /wd4675 /EHs /GR /Zc:throwingNew -nologo -DWIN32 -D_WINDOWS -W3 -utf-8 -GR -EHsc -MP -D_DEBUG -MDd -Z7 -Ob0 -Od -RTC1 /Z7 /Od /Ob0 /W3 /MDd /Zc:forScope /Zc:wchar_t /Zc:inline /favor:blend -DBOOST_ALL_NO_LIB=1 -DBOOST_PYTHON_SOURCE "-I..\include" "-IE:\SDK\vcpkg\installed\x64-windows\include" "-IE:\SDK\vcpkg\installed\x64-windows\include\python3.10;E:\SDK\vcpkg\installed\x64-windows\include\python3.9" 

registry.cpp
E:\SDK\vcpkg\buildtrees\boost-python\src\ost-1.78.0-84b9faa522.clean\include\boost/python/detail/wrap_python.hpp(57): fatal error C1083: 无法打开包括文件: “pyconfig.h”: No such file or directory
compile-c-c++ E:\SDK\vcpkg\buildtrees\boost-python\x64-windows-dbg\boost\build\64f7401830e536b590f94641995357c1\converter\type_id.obj

    call "E:\SDK\vcpkg\buildtrees\boost-python\x64-windows-dbg\boost\standalone\msvc\943897acc6555446e7558f53bf1a3e85\msvc-setup.bat" amd64 >nul
 cl "..\src\converter\type_id.cpp" -c -Fo"E:\SDK\vcpkg\buildtrees\boost-python\x64-windows-dbg\boost\build\64f7401830e536b590f94641995357c1\converter\type_id.obj"     -TP /wd4675 /EHs /GR /Zc:throwingNew -nologo -DWIN32 -D_WINDOWS -W3 -utf-8 -GR -EHsc -MP -D_DEBUG -MDd -Z7 -Ob0 -Od -RTC1 /Z7 /Od /Ob0 /W3 /MDd /Zc:forScope /Zc:wchar_t /Zc:inline /favor:blend -DBOOST_ALL_NO_LIB=1 -DBOOST_PYTHON_SOURCE "-I..\include" "-IE:\SDK\vcpkg\installed\x64-windows\include" "-IE:\SDK\vcpkg\installed\x64-windows\include\python3.10;E:\SDK\vcpkg\installed\x64-windows\include\python3.9" 

type_id.cpp
E:\SDK\vcpkg\buildtrees\boost-python\src\ost-1.78.0-84b9faa522.clean\include\boost/python/detail/wrap_python.hpp(57): fatal error C1083: 无法打开包括文件: “pyconfig.h”: No such file or directory
compile-c-c++ E:\SDK\vcpkg\buildtrees\boost-python\x64-windows-dbg\boost\build\64f7401830e536b590f94641995357c1\object\enum.obj

    call "E:\SDK\vcpkg\buildtrees\boost-python\x64-windows-dbg\boost\standalone\msvc\943897acc6555446e7558f53bf1a3e85\msvc-setup.bat" amd64 >nul
 cl "..\src\object\enum.cpp" -c -Fo"E:\SDK\vcpkg\buildtrees\boost-python\x64-windows-dbg\boost\build\64f7401830e536b590f94641995357c1\object\enum.obj"     -TP /wd4675 /EHs /GR /Zc:throwingNew -nologo -DWIN32 -D_WINDOWS -W3 -utf-8 -GR -EHsc -MP -D_DEBUG -MDd -Z7 -Ob0 -Od -RTC1 /Z7 /Od /Ob0 /W3 /MDd /Zc:forScope /Zc:wchar_t /Zc:inline /favor:blend -DBOOST_ALL_NO_LIB=1 -DBOOST_PYTHON_SOURCE "-I..\include" "-IE:\SDK\vcpkg\installed\x64-windows\include" "-IE:\SDK\vcpkg\installed\x64-windows\include\python3.10;E:\SDK\vcpkg\installed\x64-windows\include\python3.9" 

enum.cpp
E:\SDK\vcpkg\buildtrees\boost-python\src\ost-1.78.0-84b9faa522.clean\include\boost/python/detail/wrap_python.hpp(57): fatal error C1083: 无法打开包括文件: “pyconfig.h”: No such file or directory
compile-c-c++ E:\SDK\vcpkg\buildtrees\boost-python\x64-windows-dbg\boost\build\64f7401830e536b590f94641995357c1\object\class.obj

    call "E:\SDK\vcpkg\buildtrees\boost-python\x64-windows-dbg\boost\standalone\msvc\943897acc6555446e7558f53bf1a3e85\msvc-setup.bat" amd64 >nul
 cl "..\src\object\class.cpp" -c -Fo"E:\SDK\vcpkg\buildtrees\boost-python\x64-windows-dbg\boost\build\64f7401830e536b590f94641995357c1\object\class.obj"     -TP /wd4675 /EHs /GR /Zc:throwingNew -nologo -DWIN32 -D_WINDOWS -W3 -utf-8 -GR -EHsc -MP -D_DEBUG -MDd -Z7 -Ob0 -Od -RTC1 /Z7 /Od /Ob0 /W3 /MDd /Zc:forScope /Zc:wchar_t /Zc:inline /favor:blend -DBOOST_ALL_NO_LIB=1 -DBOOST_PYTHON_SOURCE "-I..\include" "-IE:\SDK\vcpkg\installed\x64-windows\include" "-IE:\SDK\vcpkg\installed\x64-windows\include\python3.10;E:\SDK\vcpkg\installed\x64-windows\include\python3.9" 

class.cpp
E:\SDK\vcpkg\buildtrees\boost-python\src\ost-1.78.0-84b9faa522.clean\include\boost/python/detail/wrap_python.hpp(57): fatal error C1083: 无法打开包括文件: “pyconfig.h”: No such file or directory
compile-c-c++ E:\SDK\vcpkg\buildtrees\boost-python\x64-windows-dbg\boost\build\64f7401830e536b590f94641995357c1\object\function.obj

    call "E:\SDK\vcpkg\buildtrees\boost-python\x64-windows-dbg\boost\standalone\msvc\943897acc6555446e7558f53bf1a3e85\msvc-setup.bat" amd64 >nul
 cl "..\src\object\function.cpp" -c -Fo"E:\SDK\vcpkg\buildtrees\boost-python\x64-windows-dbg\boost\build\64f7401830e536b590f94641995357c1\object\function.obj"     -TP /wd4675 /EHs /GR /Zc:throwingNew -nologo -DWIN32 -D_WINDOWS -W3 -utf-8 -GR -EHsc -MP -D_DEBUG -MDd -Z7 -Ob0 -Od -RTC1 /Z7 /Od /Ob0 /W3 /MDd /Zc:forScope /Zc:wchar_t /Zc:inline /favor:blend -DBOOST_ALL_NO_LIB=1 -DBOOST_PYTHON_SOURCE "-I..\include" "-IE:\SDK\vcpkg\installed\x64-windows\include" "-IE:\SDK\vcpkg\installed\x64-windows\include\python3.10;E:\SDK\vcpkg\installed\x64-windows\include\python3.9" 

function.cpp
E:\SDK\vcpkg\buildtrees\boost-python\src\ost-1.78.0-84b9faa522.clean\include\boost/python/detail/wrap_python.hpp(57): fatal error C1083: 无法打开包括文件: “pyconfig.h”: No such file or directory
compile-c-c++ E:\SDK\vcpkg\buildtrees\boost-python\x64-windows-dbg\boost\build\64f7401830e536b590f94641995357c1\object\inheritance.obj

    call "E:\SDK\vcpkg\buildtrees\boost-python\x64-windows-dbg\boost\standalone\msvc\943897acc6555446e7558f53bf1a3e85\msvc-setup.bat" amd64 >nul
 cl "..\src\object\inheritance.cpp" -c -Fo"E:\SDK\vcpkg\buildtrees\boost-python\x64-windows-dbg\boost\build\64f7401830e536b590f94641995357c1\object\inheritance.obj"     -TP /wd4675 /EHs /GR /Zc:throwingNew -nologo -DWIN32 -D_WINDOWS -W3 -utf-8 -GR -EHsc -MP -D_DEBUG -MDd -Z7 -Ob0 -Od -RTC1 /Z7 /Od /Ob0 /W3 /MDd /Zc:forScope /Zc:wchar_t /Zc:inline /favor:blend -DBOOST_ALL_NO_LIB=1 -DBOOST_PYTHON_SOURCE "-I..\include" "-IE:\SDK\vcpkg\installed\x64-windows\include" "-IE:\SDK\vcpkg\installed\x64-windows\include\python3.10;E:\SDK\vcpkg\installed\x64-windows\include\python3.9" 

inheritance.cpp
E:\SDK\vcpkg\buildtrees\boost-python\src\ost-1.78.0-84b9faa522.clean\include\boost/python/detail/wrap_python.hpp(57): fatal error C1083: 无法打开包括文件: “pyconfig.h”: No such file or directory
compile-c-c++ E:\SDK\vcpkg\buildtrees\boost-python\x64-windows-dbg\boost\build\64f7401830e536b590f94641995357c1\object\life_support.obj

    call "E:\SDK\vcpkg\buildtrees\boost-python\x64-windows-dbg\boost\standalone\msvc\943897acc6555446e7558f53bf1a3e85\msvc-setup.bat" amd64 >nul
 cl "..\src\object\life_support.cpp" -c -Fo"E:\SDK\vcpkg\buildtrees\boost-python\x64-windows-dbg\boost\build\64f7401830e536b590f94641995357c1\object\life_support.obj"     -TP /wd4675 /EHs /GR /Zc:throwingNew -nologo -DWIN32 -D_WINDOWS -W3 -utf-8 -GR -EHsc -MP -D_DEBUG -MDd -Z7 -Ob0 -Od -RTC1 /Z7 /Od /Ob0 /W3 /MDd /Zc:forScope /Zc:wchar_t /Zc:inline /favor:blend -DBOOST_ALL_NO_LIB=1 -DBOOST_PYTHON_SOURCE "-I..\include" "-IE:\SDK\vcpkg\installed\x64-windows\include" "-IE:\SDK\vcpkg\installed\x64-windows\include\python3.10;E:\SDK\vcpkg\installed\x64-windows\include\python3.9" 

life_support.cpp
E:\SDK\vcpkg\buildtrees\boost-python\src\ost-1.78.0-84b9faa522.clean\include\boost/python/detail/wrap_python.hpp(57): fatal error C1083: 无法打开包括文件: “pyconfig.h”: No such file or directory
compile-c-c++ E:\SDK\vcpkg\buildtrees\boost-python\x64-windows-dbg\boost\build\64f7401830e536b590f94641995357c1\object\pickle_support.obj

    call "E:\SDK\vcpkg\buildtrees\boost-python\x64-windows-dbg\boost\standalone\msvc\943897acc6555446e7558f53bf1a3e85\msvc-setup.bat" amd64 >nul
 cl "..\src\object\pickle_support.cpp" -c -Fo"E:\SDK\vcpkg\buildtrees\boost-python\x64-windows-dbg\boost\build\64f7401830e536b590f94641995357c1\object\pickle_support.obj"     -TP /wd4675 /EHs /GR /Zc:throwingNew -nologo -DWIN32 -D_WINDOWS -W3 -utf-8 -GR -EHsc -MP -D_DEBUG -MDd -Z7 -Ob0 -Od -RTC1 /Z7 /Od /Ob0 /W3 /MDd /Zc:forScope /Zc:wchar_t /Zc:inline /favor:blend -DBOOST_ALL_NO_LIB=1 -DBOOST_PYTHON_SOURCE "-I..\include" "-IE:\SDK\vcpkg\installed\x64-windows\include" "-IE:\SDK\vcpkg\installed\x64-windows\include\python3.10;E:\SDK\vcpkg\installed\x64-windows\include\python3.9" 

pickle_support.cpp
E:\SDK\vcpkg\buildtrees\boost-python\src\ost-1.78.0-84b9faa522.clean\include\boost/python/detail/wrap_python.hpp(57): fatal error C1083: 无法打开包括文件: “pyconfig.h”: No such file or directory
compile-c-c++ E:\SDK\vcpkg\buildtrees\boost-python\x64-windows-dbg\boost\build\64f7401830e536b590f94641995357c1\errors.obj

    call "E:\SDK\vcpkg\buildtrees\boost-python\x64-windows-dbg\boost\standalone\msvc\943897acc6555446e7558f53bf1a3e85\msvc-setup.bat" amd64 >nul
 cl "..\src\errors.cpp" -c -Fo"E:\SDK\vcpkg\buildtrees\boost-python\x64-windows-dbg\boost\build\64f7401830e536b590f94641995357c1\errors.obj"     -TP /wd4675 /EHs /GR /Zc:throwingNew -nologo -DWIN32 -D_WINDOWS -W3 -utf-8 -GR -EHsc -MP -D_DEBUG -MDd -Z7 -Ob0 -Od -RTC1 /Z7 /Od /Ob0 /W3 /MDd /Zc:forScope /Zc:wchar_t /Zc:inline /favor:blend -DBOOST_ALL_NO_LIB=1 -DBOOST_PYTHON_SOURCE "-I..\include" "-IE:\SDK\vcpkg\installed\x64-windows\include" "-IE:\SDK\vcpkg\installed\x64-windows\include\python3.10;E:\SDK\vcpkg\installed\x64-windows\include\python3.9" 

errors.cpp
E:\SDK\vcpkg\buildtrees\boost-python\src\ost-1.78.0-84b9faa522.clean\include\boost/python/detail/wrap_python.hpp(57): fatal error C1083: 无法打开包括文件: “pyconfig.h”: No such file or directory
compile-c-c++ E:\SDK\vcpkg\buildtrees\boost-python\x64-windows-dbg\boost\build\64f7401830e536b590f94641995357c1\converter\builtin_converters.obj

    call "E:\SDK\vcpkg\buildtrees\boost-python\x64-windows-dbg\boost\standalone\msvc\943897acc6555446e7558f53bf1a3e85\msvc-setup.bat" amd64 >nul
 cl "..\src\converter\builtin_converters.cpp" -c -Fo"E:\SDK\vcpkg\buildtrees\boost-python\x64-windows-dbg\boost\build\64f7401830e536b590f94641995357c1\converter\builtin_converters.obj"     -TP /wd4675 /EHs /GR /Zc:throwingNew -nologo -DWIN32 -D_WINDOWS -W3 -utf-8 -GR -EHsc -MP -D_DEBUG -MDd -Z7 -Ob0 -Od -RTC1 /Z7 /Od /Ob0 /W3 /MDd /Zc:forScope /Zc:wchar_t /Zc:inline /favor:blend -DBOOST_ALL_NO_LIB=1 -DBOOST_PYTHON_SOURCE "-I..\include" "-IE:\SDK\vcpkg\installed\x64-windows\include" "-IE:\SDK\vcpkg\installed\x64-windows\include\python3.10;E:\SDK\vcpkg\installed\x64-windows\include\python3.9" 

builtin_converters.cpp
E:\SDK\vcpkg\buildtrees\boost-python\src\ost-1.78.0-84b9faa522.clean\include\boost/python/detail/wrap_python.hpp(57): fatal error C1083: 无法打开包括文件: “pyconfig.h”: No such file or directory
compile-c-c++ E:\SDK\vcpkg\buildtrees\boost-python\x64-windows-dbg\boost\build\64f7401830e536b590f94641995357c1\object_protocol.obj

    call "E:\SDK\vcpkg\buildtrees\boost-python\x64-windows-dbg\boost\standalone\msvc\943897acc6555446e7558f53bf1a3e85\msvc-setup.bat" amd64 >nul
 cl "..\src\object_protocol.cpp" -c -Fo"E:\SDK\vcpkg\buildtrees\boost-python\x64-windows-dbg\boost\build\64f7401830e536b590f94641995357c1\object_protocol.obj"     -TP /wd4675 /EHs /GR /Zc:throwingNew -nologo -DWIN32 -D_WINDOWS -W3 -utf-8 -GR -EHsc -MP -D_DEBUG -MDd -Z7 -Ob0 -Od -RTC1 /Z7 /Od /Ob0 /W3 /MDd /Zc:forScope /Zc:wchar_t /Zc:inline /favor:blend -DBOOST_ALL_NO_LIB=1 -DBOOST_PYTHON_SOURCE "-I..\include" "-IE:\SDK\vcpkg\installed\x64-windows\include" "-IE:\SDK\vcpkg\installed\x64-windows\include\python3.10;E:\SDK\vcpkg\installed\x64-windows\include\python3.9" 

object_protocol.cpp
E:\SDK\vcpkg\buildtrees\boost-python\src\ost-1.78.0-84b9faa522.clean\include\boost/python/detail/wrap_python.hpp(57): fatal error C1083: 无法打开包括文件: “pyconfig.h”: No such file or directory
compile-c-c++ E:\SDK\vcpkg\buildtrees\boost-python\x64-windows-dbg\boost\build\64f7401830e536b590f94641995357c1\exec.obj

    call "E:\SDK\vcpkg\buildtrees\boost-python\x64-windows-dbg\boost\standalone\msvc\943897acc6555446e7558f53bf1a3e85\msvc-setup.bat" amd64 >nul
 cl "..\src\exec.cpp" -c -Fo"E:\SDK\vcpkg\buildtrees\boost-python\x64-windows-dbg\boost\build\64f7401830e536b590f94641995357c1\exec.obj"     -TP /wd4675 /EHs /GR /Zc:throwingNew -nologo -DWIN32 -D_WINDOWS -W3 -utf-8 -GR -EHsc -MP -D_DEBUG -MDd -Z7 -Ob0 -Od -RTC1 /Z7 /Od /Ob0 /W3 /MDd /Zc:forScope /Zc:wchar_t /Zc:inline /favor:blend -DBOOST_ALL_NO_LIB=1 -DBOOST_PYTHON_SOURCE "-I..\include" "-IE:\SDK\vcpkg\installed\x64-windows\include" "-IE:\SDK\vcpkg\installed\x64-windows\include\python3.10;E:\SDK\vcpkg\installed\x64-windows\include\python3.9" 

exec.cpp
E:\SDK\vcpkg\buildtrees\boost-python\src\ost-1.78.0-84b9faa522.clean\include\boost/python/detail/wrap_python.hpp(57): fatal error C1083: 无法打开包括文件: “pyconfig.h”: No such file or directory
...failed updating 19 targets...
ninja: build stopped: subcommand failed.

**Comment by Cheney-W** [comment]
Could you please provide me with all of the Iogs of the failed port? I can't reproduce this issue with latest vcpkg and VS2022 17.1.3.

**Comment by Cheney-W** [comment]
Please make sure you have installed the english language package of Visual Studio.

**Comment by Cheney-W** [comment]
Thanks for posting this issue. If this issue has new information, please reopen it.
