### ISSUE TITLE
Windows-style slashes in portfile fix suggestinons

### ISSUE THREAD

**Issue by Pospelove** [microsoft/vcpkg#24124]
**Describe the bug**
When port install fails, vcpkg suggests changes to the failed portfile.cmake which includes incorrect Windows-style slashes:
```
There should be no empty directories in C:\projects\vcpkg\packages\clipboardxx_x86-windows
The following empty directories were found:

    C:/projects/vcpkg/packages/clipboardxx_x86-windows/debug

If a directory should be populated but is not, this might indicate an error in the portfile.
If the directories are not needed and their creation cannot be disabled, use something like this in the portfile to remove them:

    file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}\debug")
```

It's a bug because if you copy-paste a provided piece of code (containing `\`), it results in a CMake error.

**Environment**
- OS: Any
- Compiler: Any

**To Reproduce**
1. Take a new port from my PR https://github.com/microsoft/vcpkg/pull/24023/files
2. Change `/debug` to `/debug/include` in portfile.cmake:17
3. vcpkg install clipboardxx
4. Congrats! You've got a wrong tip

**Expected behavior**
Expected `/` character instead:
```
    file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug")
```

**Failure logs**
```
CMake Error at ports/clipboardxx/portfile.cmake:17 (file):
  Syntax error in cmake code at

    C:/projects/vcpkg/ports/clipboardxx/portfile.cmake:17

  when parsing string

    ${CURRENT_PACKAGES_DIR}\debug

  Invalid character escape '\d'.
Call Stack (most recent call first):
  scripts/ports.cmake:145 (include)
```

**Comment by Pospelove** [comment]
Related line https://github.com/microsoft/vcpkg-tool/blob/main/src/vcpkg/postbuildlint.cpp#L744

**Comment by Pospelove** [comment]
Seems to be fixed in upstream.

**Comment by Cheney-W** [comment]
This issue has not been fixed. If you add the `--binarysource=clear` option in the `install` command, it will occurs again.
