### ISSUE TITLE
Add option to link only neccesary libs in `vcpkg`

### ISSUE THREAD

**Issue by playgithub** [microsoft/vcpkg#24123]
****

**Is your feature request related to a problem? Please describe.**
When `vcpkg` integrated to Visual Studio, a project will link to all the libs in `vcpkg`, not so efficient.

**Proposed solution**
In settings as in the screenshot below, add a new option to set direct dependencies for a project and `vcpkg` will do the work about the transitive dependencies automatically, so that only neccesary libs are linked.
![image](https://user-images.githubusercontent.com/3665590/163203281-8fb506d2-139a-4d8f-8d33-a611541e5679.png)

e.g.
* `AppA` dependes on `LibA`
* `LibA` dependdes on `LibB`
Only `LibA` needs to be specified explicitly, `vcpkg` for Visual Studio will do the work to set the link params for `LibB`.

**Comment by JackBoosY** [comment]
I talked with @BillyONeal about this. But since we need to adapt the manifest, this is difficult to implement.

**Comment by playgithub** [comment]
Also ok to keep it simple, thanks.
