### ISSUE TITLE
GLAD build failure

### ISSUE THREAD

**Issue by weather-tracker** [microsoft/vcpkg#24145]
**Host Environment**
- OS: [Windows/]
- Compiler: visual studio 2022 c++ built in.
.cpp  file
 visual studio.sln

**To Reproduce**
`./vcpkg install glad`

**cmd log**
The package glad provides CMake targets:

    find_package(glad CONFIG REQUIRED)
    target_link_libraries(main PRIVATE glad::glad)

**Additional context**
now in visual studio i get an error on the include glad/glad.h
cannot open source file "glad/glad.h"

i have installed a few packages and this is the only one that has gave me this error

**Comment by weather-tracker** [comment]
if I use the windows file explore I can can see glad.h under the packages folder

**Comment by Adela0814** [comment]
I cannot repro this issue. could you please `git pull` the latest `vcpkg` and try again? if the issue still exists, please provide your failure logs and `CmakeLists.txt`.

**Comment by weather-tracker** [comment]
i got the error to go away
