### ISSUE TITLE
[sqlite3] Build error

### ISSUE THREAD

**Issue by zyxcambridge** [microsoft/vcpkg#24143]
G] /mnt/vss/_work/1/s/src/vcpkg/base/downloads.cpp(741): 
[proxychains] DLL init: proxychains-ng 4.15
[DEBUG] Time in subprocesses: 150735 us
[DEBUG] Time in parsing JSON: 0 us
[DEBUG] Time in JSON reader: 0 us
[DEBUG] Time in filesystem: 50 us
[DEBUG] Time in loading ports: 0 us
[DEBUG] Exiting after 151.1 ms (150248 us)
[proxychains] DLL init: proxychains-ng 4.15

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:84 (message):
      
      Failed to download file with error: 1
      If you use a proxy, please check your proxy setting. Possible causes are:
      
      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
      
      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.
      
      3. Your proxy's remote server is out of service.
      
      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)
      
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:309 (z_vcpkg_download_distfile_show_proxy_and_fail)
  ports/sqlite3/portfile.cmake:6 (vcpkg_download_distfile)
  scripts/ports.cmake:145 (include)

error: building sqlite3:x64-linux failed with: BUILD_FAILED
[proxychains] DLL init: proxychains-ng 4.15
Please ensure you're using the latest portfiles with `git pull` and `./vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+sqlite3
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[sqlite3]+Build+error
including:
  package: sqlite3[core]:x64-linux -> 3.37.2#1
    vcpkg-tool version: 2022-03-30-692785ac944e81417840c6de244fb3e18a4b35eb
    vcpkg-scripts version: [proxychains] DLL init: proxychains-ng 4.15
99346bb69 2022-04-13 (18 hours ago)

Additionally, attach any relevant sections from the log files above.

**Comment by FrankXie05** [comment]
Duplicated to #22839
