### ISSUE TITLE
Error: Building package boost-build:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by Vehemos** [Microsoft/vcpkg#2415]
[bootstrap-x64-windows-err.log](https://github.com/Microsoft/vcpkg/files/1577063/bootstrap-x64-windows-err.log)
[bootstrap-x64-windows-out.log](https://github.com/Microsoft/vcpkg/files/1577064/bootstrap-x64-windows-out.log)
-- Testing integrity of cached file... OK
-- Bootstrapping...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:44 (message):
    Command failed: C:/vcpkg/packages/boost-build_x64-windows/tools/boost-build/bootstrap.bat;msvc
    Working Directory: C:/vcpkg/packages/boost-build_x64-windows/tools/boost-build
    See logs for more information:
      C:\vcpkg\buildtrees\boost-build\bootstrap-x64-windows-out.log
      C:\vcpkg\buildtrees\boost-build\bootstrap-x64-windows-err.log

Call Stack (most recent call first):
  ports/boost-build/portfile.cmake:47 (vcpkg_execute_required_process)
  scripts/ports.cmake:72 (include)

Error: Building package boost-build:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-build:x64-windows
  Vcpkg version: 0.0.100-2017-12-19-6cb6a61aaf5ef2c143f974e9f731778bcd3f5cbe

Additionally, attach any relevant sections from the log files above.

==========

I am running 64bit win10 Education version.

What to do? :(

Thank You!

**Comment by ras0219-msft** [comment]
Thanks for posting this issue!

Could you attach the contents of:
>C:/vcpkg/packages/boost-build_x64-windows/tools/boost-build/bootstrap.log

**Comment by Vehemos** [comment]
Hi, thanks for replying.

File is attached below: 

[bootstrap.log](https://github.com/Microsoft/vcpkg/files/1578634/bootstrap.log)

Thank You!

**Comment by ras0219-msft** [comment]
I... am not really sure what the issue is. Does your username have Unicode characters in it? I tried a user account with spaces, but boost-build still works for me.

If that isn't the issue then I think the best thing to do will be to try running `bootstrap.bat` yourself (it's located at `C:/vcpkg/packages/boost-build_x64-windows/tools/boost-build/bootstrap.bat`), outside vcpkg -- if that fails, then you can go to #boost on the cpplang slack to get help.

Really sorry I can't be of more help 😢!

**Comment by Vehemos** [comment]
All ASCII characters, english letters only 1 space. #boost on cpplang.slack sent me here xD I already tried all the methods they suggested

**Comment by JackBoosY** [comment]
Hi @Vehemos , thanks for reporting this issue!
I tested installing boost-build:x64-windows in a path with spaces, but found no problems.
Please open a new issue if this is still a problem for you.
Thx.
