### ISSUE TITLE
[openssl] Build error - x64-windows

### ISSUE THREAD

**Issue by justin-bj** [microsoft/vcpkg#24154]
**Host Environment**
- OS: microsoft windows 11 home edition
- Compiler: cmake version 3.23.0-rc4

**To Reproduce**
`.\vcpkg\vcpkg install openssl:x64-windows`

**Failure logs**
D:\17dev\cpp>.\vcpkg\vcpkg install openssl:x64-windows
Computing installation plan...
The following packages will be built and installed:
    openssl[core]:x64-windows -> 3.0.2#2
Detecting compiler hash for triplet x64-windows...
Restored 0 packages from C:\Users\郑勇\AppData\Local\vcpkg\archives in 152.6 us. Use --debug to see more details.
Starting package 1/1: openssl:x64-windows
Building package openssl[core]:x64-windows...
-- Using cached openssl-3.0.2.tar.gz.
-- Cleaning sources at D:/17dev/cpp/vcpkg/buildtrees/openssl/src/openssl-3-67d457a95e.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/17dev/cpp/vcpkg/downloads/openssl-3.0.2.tar.gz
-- Using source at D:/17dev/cpp/vcpkg/buildtrees/openssl/src/openssl-3-67d457a95e.clean
-- Copying openssl release source files...
-- Copying openssl release source files... done
-- Configure x64-windows-rel
-- Configure x64-windows-rel done
-- Build x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:128 (message):
    Command failed: D:/17dev/cpp/vcpkg/downloads/tools/jom/jom-1.1.3/jom.exe -j 1 -f makefile install_sw install_ssldirs
    Working Directory: D:/17dev/cpp/vcpkg/buildtrees/openssl/x64-windows-rel
    Error code: 2
    See logs for more information:
      D:\17dev\cpp\vcpkg\buildtrees\openssl\build-x64-windows-rel-1-out.log
      D:\17dev\cpp\vcpkg\buildtrees\openssl\build-x64-windows-rel-1-err.log

Call Stack (most recent call first):
  ports/openssl/windows/portfile.cmake:84 (vcpkg_execute_required_process)
  ports/openssl/portfile.cmake:31 (include)
  scripts/ports.cmake:145 (include)

error: building openssl:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+openssl
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[openssl]+Build+error
including:
  package: openssl[core]:x64-windows -> 3.0.2#2
    vcpkg-tool version: 2022-03-30-692785ac944e81417840c6de244fb3e18a4b35eb
    vcpkg-scripts version: 99346bb69 2022-04-13 (2 days ago)

Additionally, attach any relevant sections from the log files above.
-Cut and paste the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by justin-bj** [comment]
D:\17dev\cpp\vcpkg\buildtrees\openssl\build-x64-windows-rel-1-out.log:

	D:\17dev\cpp\vcpkg\downloads\tools\jom\jom-1.1.3\jom.exe /j1 depend
	D:\17dev\cpp\vcpkg\downloads\tools\jom\jom-1.1.3\jom.exe /j1 _build_libs
	"cl"  /Zi /Fdossl_static.pdb /Gs0 /GF /Gy /MD /W3 /wd4090 /nologo /O2 -utf-8 -FS -I"." -I"include" -I"apps\include" -D"L_ENDIAN" -D"OPENSSL_PIC" -D"OPENSSLDIR=\"D:\\17dev\\cpp\\vcpkg\\packages\\openssl_x64-windows\"" -D"ENGINESDIR=\"D:\\17dev\\cpp\\vcpkg\\packages\\openssl_x64-windows\\lib\\engines-3\"" -D"MODULESDIR=\"D:\\17dev\\cpp\\vcpkg\\packages\\openssl_x64-windows\\lib\\ossl-modules\"" -D"OPENSSL_BUILDING_OPENSSL" -D"OPENSSL_SYS_WIN32" -D"WIN32_LEAN_AND_MEAN" -D"UNICODE" -D"_UNICODE" -D"_CRT_SECURE_NO_DEPRECATE" -D"_WINSOCK_DEPRECATED_NO_WARNINGS" -D"NDEBUG"   -c /Foapps\lib\libapps-lib-app_libctx.obj "apps\lib\app_libctx.c"
app_libctx.c
cl: 命令行 error D8050 :无法执行“C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\c1.dll”: 未能将命令行放入调试记录中

**Comment by justin-bj** [comment]
D:\17dev\cpp\vcpkg\buildtrees\openssl\build-x64-windows-rel-1-err.log:


jom 1.1.3 - empower your cores

jom: D:\17dev\cpp\vcpkg\buildtrees\openssl\x64-windows-rel\Makefile [apps\lib\libapps-lib-app_libctx.obj] Error 2
jom: D:\17dev\cpp\vcpkg\buildtrees\openssl\x64-windows-rel\makefile [build_libs] Error 2

**Comment by FrankXie05** [comment]
Looks like it's the same issue as #24109

**Comment by justin-bj** [comment]
> Looks like it's the same issue as #24109

Yes, It looks similar, but that problem hasn't been solved

**Comment by FrankXie05** [comment]
Yes, we will fix this as soon as possible. :)

**Comment by justin-bj** [comment]
> Yes, we will fix this as soon as possible. :)

Thank you. When will it be solved? I'm using rust to write the consumption of Kafka messages

**Comment by FrankXie05** [comment]
@justin-bj Did you try this solution? https://github.com/microsoft/vcpkg/issues/24109#issuecomment-1097689010

**Comment by justin-bj** [comment]
> @justin-bj Did you try this solution? [#24109 (comment)](https://github.com/microsoft/vcpkg/issues/24109#issuecomment-1097689010)

That guy tried and didn't work, so I didn't try. I'll try it now

**Comment by justin-bj** [comment]
> @justin-bj Did you try this solution? [#24109 (comment)](https://github.com/microsoft/vcpkg/issues/24109#issuecomment-1097689010)

I tried. It didn't work. I installed vs2022 again, but it didn't work too.
