### ISSUE TITLE
[ceres] Build error

### ISSUE THREAD

**Issue by sungatetop** [microsoft/vcpkg#24155]
error: building ceres:x64-windows failed with: BUILD_FAILED
**Host Environment**
- OS: Windows 10 
- Compiler: revision

package: ceres[core,lapack,suitesparse]:x64-windows -> 2.1.0
    vcpkg-tool version: 2022-03-30-692785ac944e81417840c6de244fb3e18a4b35eb
    vcpkg-scripts version: 5d66a98f6 2022-04-14

**Comment by JonLiu1993** [comment]
@sungatetop ,Thanks for posting this issue, could you please provide the error?

**Comment by whuaegeanse** [comment]
@sungatetop 
Building ceres 2.1 is not supported via vcpkg right now.
Try to switch ceres 2.0 .

**Comment by JonLiu1993** [comment]
@sungatetop ,Is this still a problem for you?

**Comment by JonLiu1993** [comment]
Thanks for posting this issue. Please reopen this issue if it still be a problem for you
