### ISSUE TITLE
Build Failed Building Package bzip2

### ISSUE THREAD

**Issue by Kennedy747** [microsoft/vcpkg#24172]
**OS & System:**
Windows 10 Home with gpedit.msc GUI unlocked
AMD Ryzen 7 5800X, with GTX 3080

**To produce:**
I ran vcpkg.exe to install all libarries (ie: vcpkg.exe install --triplet x64-windows libusb eigen3 boost opencv glfw3 glew gtest dirent)

**What expected:**
I expected it not to fail

Note I also do not have a proxy installed.

**Outcome:**
-- Using source at C:/Users/User/Downloads/vcpkg-2020.11-1/buildtrees/bzip2/src/8689526147-1ef169fbaa.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst...
-- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst... Failed. Status: 22;"HTTP response code said error"
-- Downloading https://www2.futureware.at/~nickoe/msys2-mirror/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst...
-- Downloading https://www2.futureware.at/~nickoe/msys2-mirror/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst... Failed. Status: 22;"HTTP response code said error"
-- Downloading https://mirror.yandex.ru/mirrors/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst...
-- Downloading https://mirror.yandex.ru/mirrors/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst... Failed. Status: 22;"HTTP response code said error"
-- Downloading https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst...
-- Downloading https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst... Failed. Status: 22;"HTTP response code said error"
-- Downloading https://mirrors.ustc.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst...
-- Downloading https://mirrors.ustc.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst... Failed. Status: 22;"HTTP response code said error"
-- Downloading https://mirror.bit.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst...
-- Downloading https://mirror.bit.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst... Failed. Status: 6;"Couldn't resolve host name"
-- Downloading https://mirror.selfnet.de/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst...
-- Downloading https://mirror.selfnet.de/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst... Failed. Status: 35;"SSL connect error"
-- Downloading https://mirrors.sjtug.sjtu.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst...
-- Downloading https://mirrors.sjtug.sjtu.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst... Failed. Status: 22;"HTTP response code said error"
-- Downloading https://mirrors.zju.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst...
-- Downloading https://mirrors.zju.edu.cn/msys2/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst... Failed. Status: 22;"HTTP response code said error"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:182 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_acquire_msys.cmake:89 (vcpkg_download_distfile)
  scripts/cmake/vcpkg_acquire_msys.cmake:137 (msys_package_download)
  scripts/cmake/vcpkg_find_acquire_program.cmake:427 (vcpkg_acquire_msys)
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:271 (vcpkg_find_acquire_program)
  ports/bzip2/portfile.cmake:43 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:135 (include)

Error: Building package bzip2:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: bzip2:x64-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by dg0yt** [comment]
> Package: bzip2:x64-windows
> Vcpkg version: 2020.06.15-nohash

~~~
goto(2022);
~~~

**Comment by Kennedy747** [comment]
> > Package: bzip2:x64-windows
> > Vcpkg version: 2020.06.15-nohash
> 
> ```
> goto(2022);
> ```

I'm trying to install and compile the Prophesee OpenEb and it says in the installation guild to specifically use that version. https://docs.prophesee.ai/stable/installation/windows_open_from_source.html

**Comment by dg0yt** [comment]
This issue with [2020.11-1](https://github.com/microsoft/vcpkg/archive/refs/tags/2020.11-1.zip) cannot be fixed in 2022.

Apart from all the resolved issues since 2020 (including security fixes by upstreams), the key problem is that for ports based on autotools, vcpkg relies on MSYS2 tool binaries which are available at the time of the vcpkg commit but not forever. MSYS2 is a rolling release project, and outdated binary packages are removed after some months.

The only mitigation is using manifest mode, for combining the latest vcpkg scripts (MSYS2 downloads) with selected versions of desired ports.

**Comment by dg0yt** [comment]
> I'm trying to install and compile the Prophesee OpenEb and it says in the installation guild to specifically use that version. https://docs.prophesee.ai/stable/installation/windows_open_from_source.html

FTR this instructions also provide modification to the relevant script, but it might be oudated as well. I assume you already tried that.

**Comment by MichaelGoulding** [comment]
We just got hit by this.  When CI starts failing one week with no other changes, this is bad news.

**Comment by dg0yt** [comment]
@MichaelGoulding You are building Prophesee OpenEb and started from scratch? Or you didn't save external downloads?

**Comment by LilyWangLL** [comment]
@Kennedy747 Does this issue has new updates?

**Comment by LilyWangLL** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
