### ISSUE TITLE
[SDL2 under x64-windows] build failure

### ISSUE THREAD

**Issue by DeafMan1983** [microsoft/vcpkg#24171]
**Host Environment**
- OS: Windows 10 Pro x64
- Compiler: Visual Studio 2019 Build Tools & Visual Studio 2019 Community

**To Reproduce**
`./vcpkg install sdl2:x64-windows`

**Failure logs**
error: building sdl2:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+sdl2
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[sdl2]+Build+error
including:
  package: sdl2[core]:x64-windows -> 2.0.20#2
    vcpkg-tool version: 2022-03-30-692785ac944e81417840c6de244fb3e18a4b35eb
    vcpkg-scripts version: aebb363ea 2022-04-15 (3 hours ago)

Additionally, attach any relevant sections from the log files above.
**Additional context**
Try with `--recurse` it is same error.

// EDIT SORRY!

I clean up packages, installed, downloads and buildtrees and vcpkg compiles and builds successfully. I don't understand why does vcpkg make sensitively?

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Did you update VCPKG before installing ports? Use command `git pull` and `.\bootstrap-vcpkg.bat`. Maybe there are some updates about sdl2 and its dependencies.

**Comment by LilyWangLL** [comment]
Ping @DeafMan1983 for response.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Please reopen this issue if it still be a problem for you.

**Comment by DeafMan1983** [comment]
Sorry I am very busy. Yes it is ok with SDL2? I am working hard with GLFW3 and GLEW,  Thank you for everything!
