### ISSUE TITLE
Failed to find a custom pkg

### ISSUE THREAD

**Issue by playgithub** [microsoft/vcpkg#24197]
```cmake
find_package(boost REQUIRED COMPONENTS locale)
find_package(RapidJSON REQUIRED)
find_package(CURL REQUIRED)
find_package(openssl REQUIRED)
find_package(protobuf REQUIRED)
find_package(sqlite3 REQUIRED)
find_package(BasicToolBox REQUIRED)
```

Everything found except `BasicToolBox`,
however names for `BasicToolBox` is not consistent, cmake config path: `<vcpkg-root>\installed\<triplet>\share\basic-toolbox\BasicToolBoxConfig.cmake`

How to install it?

BTW, do I have to
* check folder `<vcpkg-root>\installed\<triplet>\share` to determine how to find a package?
* check the contents of the config files to know how to use it by `target_link_libraries` / `target_include_directories`?

**Comment by dg0yt** [comment]
Same as #24198.
