### ISSUE TITLE
Failed to find a custom package in cmake

### ISSUE THREAD

**Issue by playgithub** [microsoft/vcpkg#24198]
`CMAKE_TOOLCHAIN_FILE` & `DVCPKG_TARGET_TRIPLET` have been defined correctly.

```cmake
find_package(boost REQUIRED COMPONENTS locale)
find_package(RapidJSON REQUIRED)
find_package(CURL REQUIRED)
find_package(openssl REQUIRED)
find_package(protobuf REQUIRED)
find_package(sqlite3 REQUIRED)
find_package(BasicToolBox REQUIRED)
```

Everything found except `BasicToolBox`, which is a custom package.
However names for `BasicToolBox` is not consistent, cmake config path: `<vcpkg-root>\installed\<triplet>\share\basic-toolbox\BasicToolBoxConfig.cmake`

How to find it?

BTW, do I have to
* check folder `<vcpkg-root>\installed\<triplet>\share` to determine how to find a package?
* check the contents of the config files to know how to use it by `target_link_libraries` / `target_include_directories`?

**Comment by dg0yt** [comment]
> However names for `BasicToolBox` is not consistent, cmake config path: `<vcpkg-root>\installed\<triplet>\share\basic-toolbox\BasicToolBoxConfig.cmake`

So the config is installed to the wrong path. It needs to be `<vcpkg-root>\installed\<triplet>\share\BasicToolBox` or `...\basictoolbox`. (The dir name is case-insensitive. This package name isn't.) If your custom port uses `vcpkg_cmake_config_fixup`, you need to provide the `PACKAGE_NAME` argument.

> BTW, do I have to
> 
>  * check folder `<vcpkg-root>\installed\<triplet>\share` to determine how to find a package?
>  * check the contents of the config files to know how to use it by `target_link_libraries` / `target_include_directories`?

In the best case, you find it in upstream documentation. If you use a library, you will certainly need the documentation. 
You can also check the CMake documentation for find modules.

**Comment by playgithub** [comment]
With `vcpkg_cmake_config_fixup(PACKAGE_NAME "BasicToolBox" CONFIG_PATH "lib/cmake/BasicToolBox")`
`<vcpkg-root>\installed\<triplet>\share\BasicToolBox\BasicToolBoxConfig.cmake` there
But `<vcpkg-root>\installed\<triplet>\share\basic-toolbox\vcpkg_abi_info.txt` there
How to make `vcpkg_abi_info.txt` be in `<vcpkg-root>\installed\<triplet>\share\BasicToolBox`?

**Comment by dg0yt** [comment]
> How to make `vcpkg_abi_info.txt` be in `<vcpkg-root>\installed\<triplet>\share\BasicToolBox`?

You can't.
One directory name is based on the CMake package name.
One directory name is based on the vcpkg package name. In a proper port, it will be the place for `copyright` and  `usage`.

What could work: Rename your custom port to basictoolbox, and move the CMake config to this directory. As I said, case shouldn't matter for the directory name for CMake config.

**Comment by playgithub** [comment]
The answer is clear and useful, thanks very much.
