### ISSUE TITLE
[qtwebengine]+Build+error

### ISSUE THREAD

**Issue by GitJQ** [microsoft/vcpkg#24196]
**Host Environment**
- OS: Windows10
- Compiler: Visual Studio 2022

**To Reproduce**
`./vcpkg install qtwebengine:x64-windows --x-buildtrees-root=D:\b\`

**Failure logs**
Computing installation plan...
The following packages will be built and installed:
    qtwebengine[core,default-features]:x64-windows -> 6.2.4
Detecting compiler hash for triplet x64-windows...
Restored 0 packages from D:\vcpkg\archives in 2.146 ms. Use --debug to see more details.
Starting package 1/1: qtwebengine:x64-windows
-- Using cached D:/vcpkg/downloads/qtwebengine-b33b4266df8c333d3d273ae4665d6b322eee33c6.tar.gz
-- Cleaning sources at D:/b/qtwebengine/src/322eee33c6-0663a7f795.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/vcpkg/downloads/qtwebengine-b33b4266df8c333d3d273ae4665d6b322eee33c6.tar.gz
-- Using source at D:/b/qtwebengine/src/322eee33c6-0663a7f795.clean
-- Using cached D:/vcpkg/downloads/qtwebengine-cc7181c12d1d1605ecab6c448df4a684278d01d8.tar.gz
-- Cleaning sources at D:/b/qtwebengine/src/84278d01d8-ec27f397cb.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/vcpkg/downloads/qtwebengine-cc7181c12d1d1605ecab6c448df4a684278d01d8.tar.gz
-- Using source at D:/b/qtwebengine/src/84278d01d8-ec27f397cb.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:158 (message):
    Command failed: D:/vcpkg/downloads/tools/cmake-3.22.2-windows/cmake-3.22.2-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j13
    Working Directory: D:/b/qtwebengine/x64-windows-dbg
    See logs for more information:
      D:\b\qtwebengine\install-x64-windows-dbg-out.log
      D:\b\qtwebengine\install-x64-windows-dbg-err.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:111 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
  ports/qtwebengine/portfile.cmake:111 (vcpkg_cmake_install)
  scripts/ports.cmake:145 (include)

error: building qtwebengine:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+qtwebengine
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[qtwebengine]+Build+error
including:
  package: qtwebengine[c
[install-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/8500220/install-x64-windows-dbg-err.log)
ore,default-features]:x64-windows -> 6.2.4
    vcpkg-tool version: 2022-03-30-692785ac944e81417840c6de244fb3e18a4b35eb
    vcpkg-scripts version: aebb363ea 2022-04-15 (17 hours ago)

Additionally, attach any relevant sections from the log files above.

[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/8500222/install-x64-windows-dbg-out.log)
[install-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/8500223/install-x64-windows-dbg-err.log)

**Comment by Neumann-A** [comment]
Not a vcpkg issue:
`INTERNAL COMPILER ERROR in 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.31.31103\bin\HostX64\x64\cl.exe'`
