### ISSUE TITLE
README or bootstrap.ps1

### ISSUE THREAD

**Issue by leohawke** [Microsoft/vcpkg#242]
+ $gitHash = git rev-parse HEAD
+            ~~~
    + CategoryInfo          : ObjectNotFound: (git:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

README should tell user :"Must Have Git! In Path" (something,i think  git  not required)

And "VS140COMNTOOLS" is terrible ,How About Visual Studio Preview ?

**Comment by ras0219-msft** [comment]
Unfortunately, CMake doesn't yet ship with a way to use the Visual Studio "15" Preview compiler, so you will need to have Visual Studio 2015 installed on your machine for the libraries to build. The built libraries will be ABI compatible with VS "15", so you can still build your application with Preview (and the user-wide integration should work as well).

Thanks for catching the issue with git needing to be on the path. I'll update the README.

**Comment by ras0219-msft** [comment]
Fixed in 265ca59.
