### ISSUE TITLE
How to compile arm64-linux packages under Windows platform?

### ISSUE THREAD

**Issue by WangZP10969** [microsoft/vcpkg#24202]
https://github.com/microsoft/vcpkg/discussions/24173

I am trying to compile qt5 under Windows10 platform: arm64-linux
I have Visual Studio Community 2022 installed and I have C++ for desktop development and tools for Linux and embedded development with C++
I also have gcc-linaro-7.5.0-2019.12-i686-mingw32_aarch64-linux-gnu, installed, but don't know how to set it up

When I execute `PS C:\vcpkg> .\vcpkg install qt5:arm64-linux`, I get an error in the location of the detection compiler
Part of the config-arm64-linux-out.log is as follows
[config-arm64-linux-out.log](https://github.com/microsoft/vcpkg/files/8499169/config-arm64-linux-out.log)

```
-- The C compiler identification is unknown
CMake Error at CMakeLists.txt:11 (enable_language):
   No CMAKE_C_COMPILER could be found.

   Tell CMake where to find the compiler by setting either the environment
   variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
   the compiler, or to the compiler name if it is in the PATH.

```
I try to set the environment variable.
I set the path of aarch64-linux-gnu-gcc.exe to the environment variable CC, as well as CMAKE_C_COMPILER, and set the upper directory bin to Path, but there is no difference, vcpkg still does not find the compiler

How should I set up the compiler?
The exe path provided after the compiler is installed is as follows
![image](https://user-images.githubusercontent.com/47802547/163698977-cec86248-513b-4db1-a62d-1d9e7e171e64.png)
![image](https://user-images.githubusercontent.com/47802547/163698981-46bac917-0034-47b0-a0ea-5647339ddb0c.png)

Looking forward to your help

**Comment by bold84** [comment]
You might try creating a triplet file for your toolchain. 
Look in the triplets folder for inspiration. But I would not be surprised if this is not trivial to make it work.

You might be better off using a Raspberry Pi or an Amazon EC2 instance with Graviton CPU (aarch64).

I have built packages for Linux on aarch64 natively with vcpkg. You have to set the environment variable "VCPKG_USE_SYSTEM_BINARIES" or so and install all required tools with the package manager of the distribution you're using. They are not downloaded for obvious reasons.

**Comment by bold84** [comment]
Ah... Huawei Cloud also has servers with aarch64 CPUs (Kunpeng).

**Comment by WangZP10969** [comment]
> Ah... Huawei Cloud also has servers with aarch64 CPUs (Kunpeng).

@bold84 Thank you very much for your suggestion. In order to compile programs that can be executed on JETSON NANO, I am looking for a way to cross-compile on Windows. If this is really difficult, compiling directly on the device may also be a solution.

**Comment by bold84** [comment]
Other options would be docker buildx. That way you could build on x64 architecture for aarch64 (based on qemu).
Or you could use qemu directly and emulate an aarch64 system. Install linux and you're good to go. 

Depending on the machine you're using, it may be faster than building on the board.

**Comment by MVoz** [comment]
)) cross compile on Windows

https://github.com/microsoft/vcpkg/tree/master/triplets/community

https://github.com/microsoft/vcpkg/blob/master/triplets/community/arm64-mingw-dynamic.cmake
or
https://github.com/microsoft/vcpkg/blob/master/triplets/community/arm64-mingw-static.cmake

`vcpkg install qt5:arm64-mingw-dynamic`

**Comment by bold84** [comment]
won't the mingw compiler produce windows binaries? 

WSL is another good option though.

**Comment by WangZP10969** [comment]
> won't the mingw compiler produce windows binaries?
> 
> WSL is another good option though.

Yes, it does generate dynamic libraries for windows. 
<img width="250" alt="image" src="https://user-images.githubusercontent.com/47802547/163727047-4b04ed84-027e-4c45-8173-12b57e45ae85.png">
Am I using the wrong MinGW? Or should it really be done under Linux?

**Comment by bold84** [comment]
MinGW is GCC for Windows. It's just another compiler for windows. Looks like you have built yourself some nice "Windows on ARM" libraries. 

Okay, let me be frank. If you don't have experience cross-compiling, you are in for a lot of pain. Just build on the board natively. You save yourself a lot of headaches. If you need excitement and have lots of time, write your own triplet file and fix issues along the way in the ports that cause problems.

**Comment by WangZP10969** [comment]
@bold84 Thanks a lot, actually, even linux is a challenge for me :worried: , if it's really not possible to do it in a familiar environment, I'll try

**Comment by bold84** [comment]
It is possible... but the benefits of the familiar environment are really not worth the disadvantages of trying to make this work.

**Comment by WangZP10969** [comment]
https://github.com/microsoft/vcpkg/discussions/24173#discussioncomment-2583430

Thank you very much for your help and the tips in the discussion thread, I think there is some progress on this matter
I tried to add the definition of the compiler directly to the linux.cmake in ToolChain, and it successfully generated the library under linux
I'll keep trying to take control of the compilation process and hope it goes well

**Comment by bold84** [comment]
Wow... sounds better than I expected. Cool!
