### ISSUE TITLE
Vcpkg.json / packages.json

### ISSUE THREAD

**Issue by OlafvdSpek** [microsoft/vcpkg#2420]
I'd love to see something like composer's `composer.json` or npm's `packages.json`. A (JSON) file that lists all dependencies allowing a simple `vcpkg install` to install them.

**Comment by ras0219-msft** [comment]
Thanks for the suggestion!

For now, the best way to accomplish that would be a bat file with the contents:
```
vcpkg install boost:x64-windows folly:x64-windows <etc>
```

**Comment by OlafvdSpek** [comment]
A .bat is code, I'd prefer this data to be data. This would allow other tools to also read the data and it might be more flexible.
It could also be the start for much more meta-data about a project.

**Comment by wrathofodin** [comment]
That would be awesome and more close to how other package managers work. Cargo uses TOML and personally, I'd prefer it over JSON for listing dependencies or something like YAML.

**Comment by JackBoosY** [comment]
Close this issue via #11203 merged.
