### ISSUE TITLE
How to solve this dependency dilemma ? 

### ISSUE THREAD

**Issue by justinjk007** [Microsoft/vcpkg#2421]
I need to install CGAL. For which Boost is a dependency. I have boost already installed in a directory, which was installed manually, not by vcpkg. I was wondering how I can point vcpkg to that directory instead of installing boost again by vcpkg.

**Comment by jasjuang** [comment]
Why not install boost by vcpkg?

**Comment by justinjk007** [comment]
The problem is not really installing boost, for some reason CGAL lists Qt as a requirement as well, and Qt build is failing #2424 #2344, So I was wondering if I could point vcpkg to Qt and boost which I have already  installed so I can get CGAL working. I installed Boost and Qt way before I find out about vcpkg.

**Comment by xoviat** [comment]
The strategy that vcpkg is using to build libraries is a good one: namely that all of the libraries are built against each other. To resolve the appveyor situation, you may request that they install boost an qt with vcpkg rather than other methods.

**Comment by justinjk007** [comment]
yeah that's where the problem is, Qt takes more 60 minutes(60 minutes is all you get for building) to install via vcpkg which is they have it already installed by default.

**Comment by jasjuang** [comment]
You reference how [pcl](https://github.com/PointCloudLibrary/pcl) does it. All their dependencies are built in vcpkg and they cache it so they don't have to rebuild it everytime.

**Comment by justinjk007** [comment]
Yes, I am caching my build too just like they do
```
cache:
  - c:\tools\vcpkg\installed\
```
even if the files exist when you run `vcpkg install` it takes a bit of time to go over the packages again.

@jasjuang **pcl** does not have qt as a dependency which is where I am having problems.

I am trying this hack they are mentioning in issue #2424, I will close and comment if it works.
