### ISSUE TITLE
Allow offline bootstrapping

### ISSUE THREAD

**Issue by sweemer** [microsoft/vcpkg#24212]
****

**Is your feature request related to a problem? Please describe.**
Yes, I would like to bootstrap vcpkg on a server without Internet access but it fails with the following error:

```
$ ./bootstrap-vcpkg.sh
Downloading vcpkg-glibc...
curl: (6) Could not resolve host: github.com; Unknown error
```

There might be other errors as well after this one, but I wouldn't know because the bootstrapping fails at this point.

**Proposed solution**
I can think of a couple solutions:

1. Bundle vcpkg-glibc with vcpkg so that it does not need to be downloaded separately.
2. Add a way to point `bootstrap-vcpkg.sh` to a local version of vcpkg-glibc (or if this functionality already exists, then print out instructions for activating it when `bootstrap-vcpkg.sh` fails to download vcpkg-glibc).

**Describe alternatives you've considered**
I've considered maintaining an offline fork of vcpkg that includes all online dependencies, but this is suboptimal for many reasons, such as:

1. I have to modify `.gitignore` so that it does not ignore required dependencies.
2. The size of the forked repository becomes huge with all of the dependencies checked in.
3. Maintenance burden of resolving conflicts when pulling from upstream to the fork.

**Comment by JackBoosY** [comment]
I think you may need to store vcpkg binaries from [vcpkg-tool](https://github.com/microsoft/vcpkg-tool/releases), then download it internal and just rename it to `vcpkg`. Don't forgot to set permission.

The reason vcpkg is separated from vcpkg-tool is that we don't want a version correspondence.

**Comment by sweemer** [comment]
Thanks for the hint. I just tried building vcpkg-tool offline using cmake and it also failed due to online dependencies, specifically https://github.com/fmtlib/fmt/archive/refs/tags/8.1.1.tar.gz.

Should I submit another issue on the vcpkg-tool repository to add support for offline builds?

**Comment by JackBoosY** [comment]
If you are using an offline environment, pre-stored binaries are more appropriate I think.

**Comment by sweemer** [comment]
Ok, thank you. I will close this issue for now.
