### ISSUE TITLE
[boost-build] Build error

### ISSUE THREAD

**Issue by fabianvakhidi** [microsoft/vcpkg#24213]
How do I solve the following issue when installing packages on Windows 10 x64?

```
C:\src\vcpkg>vcpkg install pcl:x64-windows
Computing installation plan...
The following packages will be built and installed:
  * boost-algorithm[core]:x64-windows -> 1.78.0
  * boost-align[core]:x64-windows -> 1.78.0
  * boost-any[core]:x64-windows -> 1.78.0
  * boost-asio[core]:x64-windows -> 1.78.0
  * boost-atomic[core]:x64-windows -> 1.78.0
  * boost-bimap[core]:x64-windows -> 1.78.0
  * boost-build[core]:x64-windows -> 1.78.0#1
  * boost-chrono[core]:x64-windows -> 1.78.0
  * boost-circular-buffer[core]:x64-windows -> 1.78.0
  * boost-container[core]:x64-windows -> 1.78.0
  * boost-container-hash[core]:x64-windows -> 1.78.0
  * boost-context[core]:x64-windows -> 1.78.0
  * boost-conversion[core]:x64-windows -> 1.78.0
  * boost-coroutine[core]:x64-windows -> 1.78.0
  * boost-date-time[core]:x64-windows -> 1.78.0
  * boost-detail[core]:x64-windows -> 1.78.0
  * boost-dynamic-bitset[core]:x64-windows -> 1.78.0
  * boost-endian[core]:x64-windows -> 1.78.0
  * boost-exception[core]:x64-windows -> 1.78.0
  * boost-filesystem[core]:x64-windows -> 1.78.0
  * boost-foreach[core]:x64-windows -> 1.78.0
  * boost-format[core]:x64-windows -> 1.78.0
  * boost-function[core]:x64-windows -> 1.78.0
  * boost-function-types[core]:x64-windows -> 1.78.0
  * boost-functional[core]:x64-windows -> 1.78.0
  * boost-fusion[core]:x64-windows -> 1.78.0
  * boost-graph[core]:x64-windows -> 1.78.0
  * boost-integer[core]:x64-windows -> 1.78.0
  * boost-interprocess[core]:x64-windows -> 1.78.0
  * boost-intrusive[core]:x64-windows -> 1.78.0
  * boost-io[core]:x64-windows -> 1.78.0
  * boost-iostreams[bzip2,core,lzma,zlib,zstd]:x64-windows -> 1.78.0#2
  * boost-iterator[core]:x64-windows -> 1.78.0
  * boost-lambda[core]:x64-windows -> 1.78.0
  * boost-lexical-cast[core]:x64-windows -> 1.78.0
  * boost-math[core]:x64-windows -> 1.78.0
  * boost-modular-build-helper[core]:x64-windows -> 1.78.0#3
  * boost-move[core]:x64-windows -> 1.78.0
  * boost-mp11[core]:x64-windows -> 1.78.0
  * boost-mpl[core]:x64-windows -> 1.78.0
  * boost-multi-array[core]:x64-windows -> 1.78.0
  * boost-multi-index[core]:x64-windows -> 1.78.0
  * boost-numeric-conversion[core]:x64-windows -> 1.78.0
  * boost-optional[core]:x64-windows -> 1.78.0
  * boost-parameter[core]:x64-windows -> 1.78.0
  * boost-phoenix[core]:x64-windows -> 1.78.0
  * boost-pool[core]:x64-windows -> 1.78.0
  * boost-predef[core]:x64-windows -> 1.78.0
  * boost-property-map[core]:x64-windows -> 1.78.0
  * boost-property-tree[core]:x64-windows -> 1.78.0
  * boost-proto[core]:x64-windows -> 1.78.0
  * boost-ptr-container[core]:x64-windows -> 1.78.0
  * boost-random[core]:x64-windows -> 1.78.0
  * boost-range[core]:x64-windows -> 1.78.0
  * boost-ratio[core]:x64-windows -> 1.78.0
  * boost-rational[core]:x64-windows -> 1.78.0
  * boost-regex[core]:x64-windows -> 1.78.0
  * boost-serialization[core]:x64-windows -> 1.78.0
  * boost-signals2[core]:x64-windows -> 1.78.0
  * boost-smart-ptr[core]:x64-windows -> 1.78.0
  * boost-sort[core]:x64-windows -> 1.78.0
  * boost-spirit[core]:x64-windows -> 1.78.0
  * boost-system[core]:x64-windows -> 1.78.0
  * boost-thread[core]:x64-windows -> 1.78.0
  * boost-tokenizer[core]:x64-windows -> 1.78.0
  * boost-tti[core]:x64-windows -> 1.78.0
  * boost-tuple[core]:x64-windows -> 1.78.0
  * boost-type-index[core]:x64-windows -> 1.78.0
  * boost-typeof[core]:x64-windows -> 1.78.0
  * boost-unordered[core]:x64-windows -> 1.78.0
  * boost-utility[core]:x64-windows -> 1.78.0
  * boost-uuid[core]:x64-windows -> 1.78.0
  * boost-variant[core]:x64-windows -> 1.78.0
  * boost-variant2[core]:x64-windows -> 1.78.0
  * boost-winapi[core]:x64-windows -> 1.78.0
  * boost-xpressive[core]:x64-windows -> 1.78.0
  * bzip2[core]:x64-windows -> 1.0.8#2
  * eigen3[core]:x64-windows -> 3.4.0#2
  * flann[core]:x64-windows -> 2019-04-07#5
  * liblzma[core]:x64-windows -> 5.2.5#5
  * libpng[core]:x64-windows -> 1.6.37#16
  * lz4[core]:x64-windows -> 1.9.3#3
    pcl[core]:x64-windows -> 1.12.0#6
  * qhull[core]:x64-windows -> 8.0.2#3
  * zlib[core]:x64-windows -> 1.2.12
  * zstd[core]:x64-windows -> 1.5.2#1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Restored 23 packages from C:\Users\fabia\AppData\Local\vcpkg\archives in 1.837 s. Use --debug to see more details.
Starting package 1/86: boost-build:x64-windows
Building package boost-build[core]:x64-windows...
-- Using cached boostorg-build-boost-1.78.0.tar.gz.
-- Cleaning sources at C:/src/vcpkg/buildtrees/boost-build/src/ost-1.78.0-7f806436df.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/src/vcpkg/downloads/boostorg-build-boost-1.78.0.tar.gz
-- Applying patch 0001-don-t-skip-install-targets.patch
-- Applying patch 0002-fix-get-version.patch
-- Using source at C:/src/vcpkg/buildtrees/boost-build/src/ost-1.78.0-7f806436df.clean
-- Using cached boost_LICENSE_1_0.txt.
-- Using cached boost-1.78.0-boostcpp.jam.
-- Installing: C:/src/vcpkg/packages/boost-build_x64-windows/share/boost-build/copyright
-- Bootstrapping...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:128 (message):
    Command failed: C:/src/vcpkg/packages/boost-build_x64-windows/tools/boost-build/bootstrap.bat msvc
    Working Directory: C:/src/vcpkg/packages/boost-build_x64-windows/tools/boost-build
    Error code: 1
    See logs for more information:
      C:\src\vcpkg\buildtrees\boost-build\bootstrap-x64-windows-out.log
      C:\src\vcpkg\buildtrees\boost-build\bootstrap-x64-windows-err.log

Call Stack (most recent call first):
  ports/boost-build/portfile.cmake:64 (vcpkg_execute_required_process)
  scripts/ports.cmake:145 (include)


error: building boost-build:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-build
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[boost-build]+Build+error
including:
  package: boost-build[core]:x64-windows -> 1.78.0#1
    vcpkg-tool version: 2022-03-30-692785ac944e81417840c6de244fb3e18a4b35eb
    vcpkg-scripts version: aebb363ea 2022-04-15 (2 days ago)

Additionally, attach any relevant sections from the log files above.
```

**Comment by Osyotr** [comment]
>See logs for more information:
C:\src\vcpkg\buildtrees\boost-build\bootstrap-x64-windows-out.log
C:\src\vcpkg\buildtrees\boost-build\bootstrap-x64-windows-err.log

**Comment by fabianvakhidi** [comment]
The out.log shows:

Building the B2 engine..
Call_If_Exists "bin\VCVARS32.BAT"
###
### Using 'msvc' toolset.
###

C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine>"cl" /nologo /MP /MT /TP /Feb2 /wd4996 /O2 /GL /EHsc   -DNDEBUG  builtins.cpp class.cpp command.cpp compile.cpp constants.cpp cwd.cpp debug.cpp debugger.cpp execcmd.cpp execnt.cpp execunix.cpp filent.cpp filesys.cpp fileunix.cpp frames.cpp function.cpp glob.cpp hash.cpp hcache.cpp hdrmacro.cpp headers.cpp jam.cpp jamgram.cpp lists.cpp make.cpp make1.cpp md5.cpp mem.cpp modules.cpp native.cpp object.cpp option.cpp output.cpp parse.cpp pathnt.cpp pathsys.cpp pathunix.cpp regexp.cpp rules.cpp scan.cpp search.cpp jam_strings.cpp startup.cpp subst.cpp sysinfo.cpp timestamp.cpp variable.cpp w32_getreg.cpp modules/order.cpp modules/path.cpp modules/property-set.cpp modules/regex.cpp modules/sequence.cpp modules/set.cpp /link kernel32.lib advapi32.lib user32.lib 
builtins.cpp
class.cpp
command.cpp
compile.cpp
constants.cpp
cwd.cpp
debug.cpp
debugger.cpp
execcmd.cpp
execnt.cpp
execunix.cpp
filent.cpp
filesys.cpp
fileunix.cpp
frames.cpp
function.cpp
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file builtins.cpp)
glob.cpp
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\yvals.h(12): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory (compiling source file class.cpp)
hash.cpp
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file compile.cpp)
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file command.cpp)
hcache.cpp
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\yvals.h(12): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory (compiling source file constants.cpp)
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file debug.cpp)
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\yvals.h(12): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory (compiling source file cwd.cpp)
hdrmacro.cpp
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file execcmd.cpp)
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file fileunix.cpp)
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file filesys.cpp)
headers.cpp
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file frames.cpp)
jam.cpp
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file execunix.cpp)
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file execnt.cpp)
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file function.cpp)
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file filent.cpp)
jamgram.cpp
lists.cpp
make.cpp
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\yvals.h(12): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory (compiling source file debugger.cpp)
make1.cpp
md5.cpp
mem.cpp
modules.cpp
native.cpp
object.cpp
option.cpp
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file glob.cpp)
output.cpp
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file hash.cpp)
parse.cpp
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file hcache.cpp)
pathnt.cpp
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file headers.cpp)
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file hdrmacro.cpp)
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file jam.cpp)
pathsys.cpp
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\md5.h(53): fatal error C1083: Cannot open include file: 'stddef.h': No such file or directory (compiling source file md5.cpp)
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file jamgram.cpp)
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file make.cpp)
pathunix.cpp
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file modules.cpp)
regexp.cpp
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file lists.cpp)
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file mem.cpp)
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file make1.cpp)
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file option.cpp)
rules.cpp
scan.cpp
search.cpp
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\yvals.h(12): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory (compiling source file native.cpp)
jam_strings.cpp
startup.cpp
subst.cpp
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file object.cpp)
sysinfo.cpp
timestamp.cpp
variable.cpp
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file output.cpp)
w32_getreg.cpp
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file parse.cpp)
order.cpp
path.cpp
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file pathnt.cpp)
property-set.cpp
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file pathsys.cpp)
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file regexp.cpp)
regex.cpp
sequence.cpp
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file pathunix.cpp)
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file jam_strings.cpp)
set.cpp
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file rules.cpp)
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file search.cpp)
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file scan.cpp)
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file subst.cpp)
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\yvals.h(12): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory (compiling source file startup.cpp)
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file timestamp.cpp)
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file variable.cpp)
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file sysinfo.cpp)
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\jam.h(73): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file w32_getreg.cpp)
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\yvals.h(12): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory (compiling source file modules/path.cpp)
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\yvals.h(12): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory (compiling source file modules/order.cpp)
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\yvals.h(12): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory (compiling source file modules/property-set.cpp)
C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine\modules\../mem.h(14): fatal error C1083: Cannot open include file: 'stdlib.h': No such file or directory (compiling source file modules/regex.cpp)
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\yvals.h(12): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory (compiling source file modules/sequence.cpp)
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include\yvals.h(12): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory (compiling source file modules/set.cpp)

C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine>dir *.exe 
 Volume in drive C is Windows
 Volume Serial Number is D0CB-1FC3

 Directory of C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine


C:\src\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine>copy /b .\b2.exe .\bjam.exe 
Systemet finner ikke angitt fil.

Failed to build the B2 engine.

While err.log shows:
File Not Found

**Comment by Adela0814** [comment]
@fabianvakhidi  can you try the solutions in https://github.com/microsoft/vcpkg/issues/23986

**Comment by Adela0814** [comment]
@fabianvakhidi  ping~

**Comment by Adela0814** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
