### ISSUE TITLE
Error: Building package zlib:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by IronsDu** [Microsoft/vcpkg#2422]
## config-x86-windows-rel-err.log
CMake Error at D:/projects/vcpkg/downloads/cmake-3.10.0-win32-x86/share/cmake-3.10/Modules/CMakeTestCCompiler.cmake:52 (message):
  The C compiler

    "D:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_x86/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: D:/projects/vcpkg/buildtrees/zlib/x86-windows-rel/CMakeFiles/CMakeTmp
    
    Run Build Command:"D:/projects/vcpkg/downloads/tools/ninja/ninja-1.8.2/ninja.exe" "cmTC_a8708"
    [1/2] Building C object CMakeFiles\cmTC_a8708.dir\testCCompiler.c.obj
    [2/2] Linking C executable cmTC_a8708.exe
    FAILED: cmTC_a8708.exe 
    cmd.exe /C "cd . && D:\projects\vcpkg\downloads\cmake-3.10.0-win32-x86\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_a8708.dir --manifests  -- D:\PROGRA~1\MICROS~2.0\VC\bin\AMD64_~2\link.exe /nologo CMakeFiles\cmTC_a8708.dir\testCCompiler.c.obj  /out:cmTC_a8708.exe /implib:cmTC_a8708.lib /pdb:cmTC_a8708.pdb /version:0.0  /machine:X86  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    RC Pass 1: command "rc /foCMakeFiles\cmTC_a8708.dir/manifest.res CMakeFiles\cmTC_a8708.dir/manifest.rc" failed (exit code 0) with the following output:
    系统找不到指定的文件。
    ninja: build stopped: subcommand failed.
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:4 (project)

## config-x86-windows-rel-out.log

-- The C compiler identification is MSVC 19.0.23918.0
-- Check for working C compiler: D:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_x86/cl.exe
-- Check for working C compiler: D:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_x86/cl.exe -- broken
-- Configuring incomplete, errors occurred!
See also "D:/projects/vcpkg/buildtrees/zlib/x86-windows-rel/CMakeFiles/CMakeOutput.log".
See also "D:/projects/vcpkg/buildtrees/zlib/x86-windows-rel/CMakeFiles/CMakeError.log".

## patch-x86-windows-0-err.log
Checking patch CMakeLists.txt...
error: while searching for:

option(ASM686 "Enable building i686 assembly implementation")
option(AMD64 "Enable building amd64 assembly implementation")

set(INSTALL_BIN_DIR "${CMAKE_INSTALL_PREFIX}/bin" CACHE PATH "Installation directory for executables")
set(INSTALL_LIB_DIR "${CMAKE_INSTALL_PREFIX}/lib" CACHE PATH "Installation directory for libraries")

error: patch failed: CMakeLists.txt:7
error: CMakeLists.txt: patch does not apply

---
I use 64bit Win10 Professional Version, and vcpkg version is https://github.com/Microsoft/vcpkg/commit/5e5506e68a9657d18bc4fb4380b5b4dfc849c019.
**My computer not have english package**.(Have `Warning: The following VS instances are exluded because the English language pack is unavailable.` when install package)

I can't post file to https://github.com/Microsoft/vcpkg/files, Sorry.

BTW, I can't install other some packet (e.g protobuf, libuv, brynet, boost), only can install rapidjson and crow.

**Comment by IronsDu** [comment]
In fact, I want install english package , but failed (downloading failed).

**Comment by IULOVE** [comment]
我和你一样什么包都安装不了  win7 64  错误和你的一样！！

**Comment by sdcb** [comment]
可以通过安装英文版工具包来完成，该工具包下载应该不需要VPN，实在装不上也可以跑个
We can fix it by installing the English pack toolset:
![_20180102092014](https://user-images.githubusercontent.com/1317141/34472471-3729a816-ef9e-11e7-9eeb-90b7e8018cbd.png)

**Comment by IULOVE** [comment]
@sdcb 

我的是vs2015up3的``

**Comment by IronsDu** [comment]
It's OK.
