### ISSUE TITLE
[openssl-windows:x86-windows-static] build failure

### ISSUE THREAD

**Issue by lukakostic** [microsoft/vcpkg#24221]
**Host Environment**
- OS: Windows 10

**To Reproduce**
`vcpkg install openssl-windows:x86-windows-static`

openssl just updated to 3.0 from 1.1.1 , while there is now openssl-windows which claims its deprecated and stayed at 1.1.1
if i try to install openssl-windows , this seems to also pull in openssl:x86-windows-static 

```
The following packages will be built and installed:
  * openssl[core]:x86-windows-static -> 3.0.2#2
    openssl-windows[core]:x86-windows-static -> 1.1.1h#2
Additional packages (*) will be modified to complete this operation.
```
but when i try to compile my project, it still gives errors about things being deprecated in 3.0
why is that when i specifically installed openssl-windows which is 1.1.1 ?

sorry if wrong issue section, but installing a package which says deprecated and claims version 1.1.1 should do just that, no?

![image](https://user-images.githubusercontent.com/41348897/163822480-7cc6b5bf-b156-4023-8bd4-4a9f767a4a20.png)

**Comment by Thomas1664** [comment]
The port `openssl-windows` is empty and basically just a wrapper around `openssl`.

**Comment by lukakostic** [comment]
I still dont understand where to find baseline git IDs so i just copied a baseline from one of the versioning examples, and it seems to offer 1.1.1i version openssl so i just used that...

**Comment by Thomas1664** [comment]
I recommend using the latest 1.1.1 version which is 1.1.1n because of OpenSSL security fixes. It sits at commit ID `3b3bd424827a1f7f4813216f6b32b6c61e386b2e`.
The easiest way to get the commit ID is to look at the history of  `ports/<portname>/vcpkg.json` from the port you're interested in.

**Comment by LilyWangLL** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
