### ISSUE TITLE
Failed to get version of ... when installing jsoncpp:x64-windows

### ISSUE THREAD

**Issue by ceezous** [microsoft/vcpkg#24238]
**Description**
When I was installing jsoncpp:x64-windows, it shows:
```
$ vcpkg install jsoncpp
Computing installation plan...
The following packages will be built and installed:
    jsoncpp[core]:x86-windows -> 1.9.5
   * vcpkg-cmake[core]:x64-windows -> 2022-04-12
   * vcpkg-cmake-config[core]:x64-windows -> 2022-02-06
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
-- Automatically settiing HTTP(S)_PROXY environment variables to 127.0.0.1:7890
A suitable version of powershell-core was not found (required v7.2.1). Downloading portable powershell-core v7.2.1...
Extracting powershell-core...

Failed to get version of C:\vcpkg\vcpkg-master\downloads\tools\powershell-core-7.2.1-windows\pwsh.exe
```
And the installation stopped.

**Environment**
- OS: Windows10 19043.1645
- Compiler: None

**To Reproduce**
1. ./vcpkg install jsoncpp:x64-windows
2. See error

**Expected behavior**
Show the 'failed to ...' message and installation stops.

**Failure logs**
None

**Additional context**
Tried PS and git cmd.

**Comment by Cheney-W** [comment]
What's the result when you manually run following command?
`C:\vcpkg\vcpkg-master\downloads\tools\powershell-core-7.2.1-windows\pwsh.exe --version`
If it returns `PowerShell 7.2.1`, I think you could rerun the `bootstrap-vcpkg.bat` and then reinstall the port;
If it doesn't return `PowerShell 7.2.1`, please remove the download folder and reinstall the port.

**Comment by Cheney-W** [comment]
Please make sure you have installed the English language pack from Visual Studio Installer.

**Comment by ceezous** [comment]
> 

I did as suggestion, and it returned
```
$ ./downloads/tools/powershell-core-7.2.1-windows/pwsh.exe --version
Failed to load the dll from [C:\vcpkg\vcpkg-master\downloads\tools\powershell-core-7.2.1-windows\hostfxr.dll], HRESULT: 0x800700C1
The library hostfxr.dll was found, but loading it from C:\vcpkg\vcpkg-master\downloads\tools\powershell-core-7.2.1-windows\hostfxr.dll failed
  - Installing .NET prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=798306
```
Reinstallation was tried as well, and the result was the same.
I'm trying to solve it as the lint suggest.

**Comment by ceezous** [comment]
> 

English pack has been used since before this error.

**Comment by ceezous** [comment]
Bty, there is an encryption software installed on my PC, will it cause this bug?

**Comment by Cheney-W** [comment]
I'n not sure if this issue related with the encryption software, but I think you could do as below:
1. Manually download the powershell-core-7.2.1 from https://github.com/PowerShell/PowerShell/releases/download/v7.2.1/PowerShell-7.2.1-win-x64.msi
2. Install it into a new folder, e.g. `C:\MyTest`
3. Open a cmd and run `"C:\MyTest\7\pwsh.exe" --version`

If you still get the error, then this issue should have something to do with your local environment; 
if no, then please delete the content in `C:\vcpkg\vcpkg-master\downloads\tools\powershell-core-7.2.1-windows` and reinstall mm into that folder.

**Comment by Cheney-W** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
