### ISSUE TITLE
libpg  error 

### ISSUE THREAD

**Issue by wzxflying** [microsoft/vcpkg#24244]
Please create a discussion in https://github.com/microsoft/vcpkg/discussions/new instead.
-- Applying patch patches/windows/Solution_RELEASE.patch
-- Applying patch patches/windows/python3_build_RELEASE.patch
-- Patches applied!
-- Building libpq x64-windows-RELEASE...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:128 (message):
    Command failed: E:/000/0Cmake/QField/vcpkg/base/downloads/tools/perl/5.32.1.1/perl/bin/perl.exe build.pl RELEASE libpq
    Working Directory: E:/000/0Cmake/QField/vcpkg/base/buildtrees/libpq/x64-windows-rel/src/tools/msvc
    Error code: 1
    See logs for more information:
      E:\000\0Cmake\QField\vcpkg\base\buildtrees\libpq\build-libpq-x64-windows-RELEASE-out.log

Call Stack (most recent call first):
  ports/libpq/portfile.cmake:229 (vcpkg_execute_required_process)
  scripts/ports.cmake:145 (include)

Error: Building package libpq:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libpq
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[libpq]+Build+error
including:
  package: libpq[core,lz4,openssl,zlib]:x64-windows -> 14.1
    vcpkg-tool version: 2022-03-25-d9702d9d89b9468c32efc3f18fb84c3021d7dbae
    vcpkg-scripts version: 5d3e0e8a2 2022-03-30 (3 weeks ago)

Additionally, attach any relevant sections from the log files above.
-- Running vcpkg install - failed
CMake Error at vcpkg/base/scripts/buildsystems/vcpkg.cmake:850 (message):
  vcpkg install failed.  See logs for more information:
  E:\000\0Cmake\QField\build\vcpkg-manifest-install.log
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.23/Modules/CMakeDetermineSystem.cmake:124 (include)
  CMakeLists.txt:26 (project)

-- Configuring incomplete, errors occurred!

**Comment by wzxflying** [comment]
Generating pg_config_paths.h...
用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.11.2+f32259642
版权所有(C) Microsoft Corporation。保留所有权利。

生成启动时间为 2022/4/19 星期二 17:43:59。
     1>节点 1 上的项目“E:\000\0Cmake\QField\vcpkg\base\buildtrees\libpq\x64-windows-rel\libpq.vcxproj”(默认目标)。
     1>项目“E:\000\0Cmake\QField\vcpkg\base\buildtrees\libpq\x64-windows-rel\libpq.vcxproj”(1)正在节点 1 上生成“E:\000\0Cmake\QField\vcpkg\base\buildtrees\libpq\x64-windows-rel\libpgcommon.vcxproj”(2) (默认目标)。
     2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(436,5): error MSB8013: 此项目不包含配置和平台组合 Release|x64。 [E:\000\0Cmake\QField\vcpkg\base\buildtrees\libpq\x64-windows-rel\libpgcommon.vcxproj]
     2>已完成生成项目“E:\000\0Cmake\QField\vcpkg\base\buildtrees\libpq\x64-windows-rel\libpgcommon.vcxproj”(默认目标)的操作 - 失败。
     1>项目“E:\000\0Cmake\QField\vcpkg\base\buildtrees\libpq\x64-windows-rel\libpq.vcxproj”(1)正在节点 2 上生成“E:\000\0Cmake\QField\vcpkg\base\buildtrees\libpq\x64-windows-rel\libpgport.vcxproj”(3) (默认目标)。
     3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(436,5): error MSB8013: 此项目不包含配置和平台组合 Release|x64。 [E:\000\0Cmake\QField\vcpkg\base\buildtrees\libpq\x64-windows-rel\libpgport.vcxproj]
     3>已完成生成项目“E:\000\0Cmake\QField\vcpkg\base\buildtrees\libpq\x64-windows-rel\libpgport.vcxproj”(默认目标)的操作 - 失败。
     1>已完成生成项目“E:\000\0Cmake\QField\vcpkg\base\buildtrees\libpq\x64-windows-rel\libpq.vcxproj”(默认目标)的操作 - 失败。

生成失败。

       “E:\000\0Cmake\QField\vcpkg\base\buildtrees\libpq\x64-windows-rel\libpq.vcxproj”(默认目标) (1) ->
       “E:\000\0Cmake\QField\vcpkg\base\buildtrees\libpq\x64-windows-rel\libpgcommon.vcxproj”(默认目标) (2) ->
       (PrepareForBuild 目标) -> 
         C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(436,5): error MSB8013: 此项目不包含配置和平台组合 Release|x64。 [E:\000\0Cmake\QField\vcpkg\base\buildtrees\libpq\x64-windows-rel\libpgcommon.vcxproj]


       “E:\000\0Cmake\QField\vcpkg\base\buildtrees\libpq\x64-windows-rel\libpq.vcxproj”(默认目标) (1) ->
       “E:\000\0Cmake\QField\vcpkg\base\buildtrees\libpq\x64-windows-rel\libpgport.vcxproj”(默认目标) (3) ->
         C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(436,5): error MSB8013: 此项目不包含配置和平台组合 Release|x64。 [E:\000\0Cmake\QField\vcpkg\base\buildtrees\libpq\x64-windows-rel\libpgport.vcxproj]

    0 个警告
    2 个错误

已用时间 00:00:00.50

**Comment by Adela0814** [comment]
@wzxflying  Please add VS English Language pack and try again.

**Comment by wzxflying** [comment]
> @wzxflying Please add VS English Language pack and try again.

ok
