### ISSUE TITLE
opencv2[cuda]:x64-windows OpenCVConfig.cmake error

### ISSUE THREAD

**Issue by ericCHxia** [microsoft/vcpkg#24242]
**Describe the bug**
`<opencv2/opencv.hpp>`  can't be found by IDE. But everything is ok when I built it without cuda.
And I fix it when I delete the two lines in the `OpenCVConfig.cmake`.

```cmake
# if(NOT WIN32 OR ANDROID)
  if(ANDROID)
    set(OpenCV_INSTALL_PATH "${OpenCV_CONFIG_PATH}/../../..")
  else()
    set(OpenCV_INSTALL_PATH "${OpenCV_CONFIG_PATH}/../..")
  endif()
  # Get the absolute path with no ../.. relative marks, to eliminate implicit linker warnings
  if(${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION} VERSION_LESS 2.8)
    get_filename_component(OpenCV_INSTALL_PATH "${OpenCV_INSTALL_PATH}" ABSOLUTE)
  else()
    get_filename_component(OpenCV_INSTALL_PATH "${OpenCV_INSTALL_PATH}" REALPATH)
  endif()
# endif()
```

**Environment**
- OS: Windows
- Compiler: VS2019

**Comment by JackBoosY** [comment]
cc @cenit

**Comment by cenit** [comment]
I cannot reproduce the issue, for me both opencv2[default-features] and opencv2[cuda] work ok in a downstream project.
Also, I cannot see why CUDA could be an issue from the snippet above.
