### ISSUE TITLE
[wxwidgets] update to 3.1.6

### ISSUE THREAD

**Issue by weather-tracker** [microsoft/vcpkg#24255]
Library name: wxWidgets 

New version number: 3.1.6

https://github.com/wxWidgets/wxWidgets/releases
Other information that may be useful (release notes, etc...)

**Comment by PriitUring** [comment]
@weather-tracker

Isn't the latest version currently 3.1.6, not 3.16?
https://github.com/wxWidgets/wxWidgets/releases

So, if it's a typo, then please fix the incorrect title and opening post and edit them to look more common as other port update requests.

> ...wxwidgets>] update to <3.16>

Better title would be:
> [wxwidgets] update to 3.1.6

Better opening would be:
> Library name: wxWidgets
>
> New version number: 3.1.6
>
> https://github.com/wxWidgets/wxWidgets/releases

**Comment by FrankXie05** [comment]
Fixed by #24483
