### ISSUE TITLE
there is no package for armadillo library

### ISSUE THREAD

**Issue by how0723** [Microsoft/vcpkg#2425]
there is no package for armadillo library

conradsnicta/armadillo-code: source code repo for Armadillo C++ linear algebra (matrix) library - http://arma.sourceforge.net
https://github.com/conradsnicta/armadillo-code/

**Comment by jasjuang** [comment]
Please consider making a new port for this and submit a PR!

**Comment by arthur-tacca** [comment]
This is a dupe of #1491

**Comment by NancyLi1013** [comment]
The PR has been merged. So it should be closed.
