### ISSUE TITLE
vcpkg create doesn't work with the error message "vcpkg_download_distfile requires a SHA512 argument."

### ISSUE THREAD

**Issue by CdecPGL** [Microsoft/vcpkg#2426]
I tryied to create an original package by passing package name, url and archive name to  `vcpkg create`, but an error ocurred shown as bellow:
```:bat
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:49 (message):
  vcpkg_download_distfile requires a SHA512 argument.
Call Stack (most recent call first):
  scripts/ports.cmake:112 (vcpkg_download_distfile)
```

This is reproducable in the example of [https://vcpkg.readthedocs.io/en/latest/examples/packaging-zlib/](https://vcpkg.readthedocs.io/en/latest/examples/packaging-zlib/) in my environment (Windows10 Fall Creators Update, VisualStudio 2017.5.2). The example code is this:
```:bat
\vcpkg create zlib2 http://zlib.net/zlib128.zip zlib128.zip
```

I found that input sanitization are added to vcpkg_download_distfile.cmake in [this commit](https://github.com/Microsoft/vcpkg/commit/5e5506e68a9657d18bc4fb4380b5b4dfc849c019) and this causes the error in vcpkg create.

I think it is required to refer _VCPKG_INTERNAL_NO_HASH_CHECK in input sanitization, so I changed [L48 in vcpkg_download_distfile.cmake](https://github.com/Microsoft/vcpkg/blob/db40d19f3db8d72439f3d1958f3d6ffbd8003435/scripts/cmake/vcpkg_download_distfile.cmake#L48) in my repository([CdecPGL/vcpkg@d3614f1](https://github.com/CdecPGL/vcpkg/commit/d3614f12b823d38b93a41867915f2c803934adc0))
```:cmake
    if(NOT DEFINED vcpkg_download_distfile_SHA512)
```
to
```:cmake
    if(NOT _VCPKG_INTERNAL_NO_HASH_CHECK AND NOT DEFINED vcpkg_download_distfile_SHA512)
```
then `vcpkg create` works well.

**Comment by jasjuang** [comment]
Does #2469 solves this for you?

**Comment by CdecPGL** [comment]
Yes, the problem is solved.
Thank you!

**Comment by ivannp** [comment]
I see exactly the same error after cloning master.

**Comment by CdecPGL** [comment]
Sorry, I mistakenly checked if the problem is solved in my branch.
In master branch, the problem is not solved...

**Comment by ivannp** [comment]
Folks, can someone merge the fix into master? Looks like no new packages can be created using the latest master.

**Comment by ras0219-msft** [comment]
This should be completely resolved in in the current master:
```
D:\src\vcpkg> vcpkg create zlib2 http://zlib.net/zlib-1.2.11.tar.gz zlib-1.2.11.tar.gz
-- Downloading http://zlib.net/zlib-1.2.11.tar.gz...
-- Downloading http://zlib.net/zlib-1.2.11.tar.gz... OK
-- Generated portfile: D:\src\vcpkg\ports\zlib2\portfile.cmake
-- Generated CONTROL: D:\src\vcpkg\ports\zlib2\CONTROL
-- To launch an editor for these new files, run
--     .\vcpkg edit zlib2
```

The build then proceeds as documented in https://github.com/Microsoft/vcpkg/blob/53e61d4ab545fa0097cb58ce9818350595322aab/docs/examples/packaging-zlib.md

**Comment by Norocel** [comment]
Delete my account...

31 янв. 2018 г. 10:25 ПП пользователь "Robert Schumacher" <
notifications@github.com> написал:
