### ISSUE TITLE
[many ports] Remove local license file

### ISSUE THREAD

**Issue by Thomas1664** [microsoft/vcpkg#24283]
Many ports have a local `license`/ `LICENSE` file:
- [ ] zlib
- [ ] ~~monkeys-audio~~
- [ ] ~~pqp~~
- [ ] soil2
- [ ] bento4
- [ ] ~~sigslot~~
- [ ] bustache (via readme)
- [ ] ~~pdcurses~~
- [ ] ~~libstemmer~~
- [ ] angelscript `sdk/docs/manual/doc_license.html`
- [ ] ~~gettimeofday (in-port source files)~~
- [ ] ~~cspice~~
- [ ] ~~tinyxml~~
- [ ] ~~vulkan~~
- [ ] ~~irrlicht~~
- [ ] ~~ffnvcodec~~
- [ ] ~~hungarian~~
- [ ] ~~tensorflow-common~~

Not all of these are bugs, there might be good reasons why a local license file is needed. I will check this.

**Comment by autoantwort** [comment]
Maybe we should add a post build check for that?

**Comment by Thomas1664** [comment]
> Maybe we should add a post build check for that?

I like this idea.
The thing is there are ports that actually need a license file, e.g. vcpkg-cmake. We would need to implement a flag that disables the check. However, I'm afraid that this won't solve the problem. If someone thinks he/she needs a license file (even if they actually don't) they will use the flag to disable this check.
What we could implement is a check for license files that are called something different than `copyright`. But this would involve updating existing ports just to change the name of a file.

A better option would be to add documentation in the maintainer/ review guide that license files are only allowed if there is no license (even not in readme) in the downloaded file.
