### ISSUE TITLE
lapack-reference build error ninja error

### ISSUE THREAD

**Issue by wzxflying** [microsoft/vcpkg#24287]
```
Starting package 5/7: lapack-reference:x86-windows
Building package lapack-reference[blas-select,core,noblas]:x86-windows...
-- Using cached Reference-LAPACK-lapack-v3.10.0.tar.gz.
-- Cleaning sources at E:/vcpkg/buildtrees/lapack-reference/src/v3.10.0-a3af633c89.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/vcpkg/downloads/Reference-LAPACK-lapack-v3.10.0.tar.gz
-- Using source at E:/vcpkg/buildtrees/lapack-reference/src/v3.10.0-a3af633c89.clean
-- The Fortran compiler identification is unknown
-- No Fortran compiler found on the PATH. Using MinGW gfortran!
-- Using cached msys-mingw-w64-i686-gcc-fortran-11.2.0-8-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-gcc-libgfortran-11.2.0-8-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-gcc-libs-11.2.0-8-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-gmp-6.2.1-3-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-winpthreads-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-mpc-1.2.1-1-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-mpfr-4.1.0.p13-1-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-gcc-11.2.0-8-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-binutils-2.37-4-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-crt-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-headers-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-libiconv-1.16-2-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-windows-default-manifest-6.4-3-any.pkg.tar.xz.
-- Using cached msys-mingw-w64-i686-zlib-1.2.11-9-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-zstd-1.5.2-1-any.pkg.tar.zst.
-- Using cached msys-gzip-1.11-1-x86_64.pkg.tar.zst.
-- Using cached msys-bash-5.1.008-1-x86_64.pkg.tar.zst.
-- Using cached msys-diffutils-3.8-2-x86_64.pkg.tar.zst.
-- Using cached msys-coreutils-8.32-2-x86_64.pkg.tar.zst.
-- Using cached msys-grep-3.0-2-x86_64.pkg.tar.xz.
-- Using cached msys-sed-4.8-2-x86_64.pkg.tar.zst.
-- Using cached msys-libpcre-8.45-1-x86_64.pkg.tar.zst.
-- Using cached msys-gawk-5.1.0-2-x86_64.pkg.tar.zst.
-- Using cached msys-mpfr-4.1.0-1-x86_64.pkg.tar.zst.
-- Using cached msys-gmp-6.2.1-1-x86_64.pkg.tar.zst.
-- Using cached msys-libreadline-8.1.001-1-x86_64.pkg.tar.zst.
-- Using cached msys-ncurses-6.2-2-x86_64.pkg.tar.zst.
-- Using cached msys-pkg-config-0.29.2-4-x86_64.pkg.tar.zst.
-- Using cached msys-make-4.3-3-x86_64.pkg.tar.zst.
-- Using cached msys-libintl-0.21-1-x86_64.pkg.tar.zst.
-- Using cached msys-libiconv-1.16-2-x86_64.pkg.tar.zst.
-- Using cached msys-gcc-libs-11.2.0-3-x86_64.pkg.tar.zst.
-- Using cached msys-msys2-runtime-3.2.0-8-x86_64.pkg.tar.zst.
-- Using msys root at E:/vcpkg/downloads/tools/msys2/2b29df0583c528a8
-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:158 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j9
    Working Directory: E:/vcpkg/buildtrees/lapack-reference/x86-windows-dbg
    See logs for more information:
      E:\vcpkg\buildtrees\lapack-reference\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:111 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
  ports/lapack-reference/portfile.cmake:72 (vcpkg_cmake_install)
  scripts/ports.cmake:145 (include)


Error: Building package lapack-reference:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+lapack-reference
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[lapack-reference]+Build+error
including:
  package: lapack-reference[blas-select,core,noblas]:x86-windows -> 3.10.0
    vcpkg-tool version: 2022-02-24-7efe7f2b04912a7d674f86a406f9f2711c0221c6
    vcpkg-scripts version: c37cc7836 2022-04-19 (31 hours ago)

Additionally, attach any relevant sections from the log files above.
```

**Comment by wzxflying** [comment]
**[2472/3793] E:\vcpkg\downloads\tools\msys2\2b29df0583c528a8\mingw32\bin\gfortran.exe -IE:\vcpkg\buildtrees\lapack-reference\src\v3.10.0-a3af633c89.clean\SRC -mabi=ms -m32 -frecursive -g -JSRC -fpreprocessed -c SRC/CMakeFiles/lapack.dir/la_xisnan.F90-pp.f90 -o SRC/CMakeFiles/lapack.dir/la_xisnan.F90.obj
FAILED: SRC/CMakeFiles/lapack.dir/la_xisnan.F90.obj SRC/la_xisnan.mod 
E:\vcpkg\downloads\tools\msys2\2b29df0583c528a8\mingw32\bin\gfortran.exe -IE:\vcpkg\buildtrees\lapack-reference\src\v3.10.0-a3af633c89.clean\SRC -mabi=ms -m32 -frecursive -g -JSRC -fpreprocessed -c SRC/CMakeFiles/lapack.dir/la_xisnan.F90-pp.f90 -o SRC/CMakeFiles/lapack.dir/la_xisnan.F90.obj
f951.exe: Fatal Error: Reading module 'SRC/la_constants.mod' at line 3 column 10: Unexpected EOF
compilation terminated.**

[2473/3793] E:\vcpkg\downloads\tools\msys2\2b29df0583c528a8\mingw32\bin\gfortran.exe -IE:\vcpkg\buildtrees\lapack-reference\src\v3.10.0-a3af633c89.clean\SRC -mabi=ms -m32 -frecursive -g -JSRC -fpreprocessed -c SRC/CMakeFiles/lapack.dir/sgetrf.f-pp.f -o SRC/CMakeFiles/lapack.dir/sgetrf.f.obj
[2474/3793] E:\vcpkg\downloads\tools\msys2\2b29df0583c528a8\mingw32\bin\gfortran.exe -IE:\vcpkg\buildtrees\lapack-reference\src\v3.10.0-a3af633c89.clean\SRC -mabi=ms -m32 -frecursive -g -JSRC -fpreprocessed -c SRC/CMakeFiles/lapack.dir/sbdsdc.f-pp.f -o SRC/CMakeFiles/lapack.dir/sbdsdc.f.obj
[2475/3793] E:\vcpkg\downloads\tools\msys2\2b29df0583c528a8\mingw32\bin\gfortran.exe -IE:\vcpkg\buildtrees\lapack-reference\src\v3.10.0-a3af633c89.clean\SRC -mabi=ms -m32 -frecursive -g -JSRC -fpreprocessed -c SRC/CMakeFiles/lapack.dir/slabad.f-pp.f -o SRC/CMakeFiles/lapack.dir/slabad.f.obj
[2476/3793] E:\vcpkg\downloads\tools\msys2\2b29df0583c528a8\mingw32\bin\gfortran.exe -IE:\vcpkg\buildtrees\lapack-reference\src\v3.10.0-a3af633c89.clean\SRC -mabi=ms -m32 -frecursive -g -JSRC -fpreprocessed -c SRC/CMakeFiles/lapack.dir/sdisna.f-pp.f -o SRC/CMakeFiles/lapack.dir/sdisna.f.obj
[2477/3793] E:\vcpkg\downloads\tools\msys2\2b29df0583c528a8\mingw32\bin\gfortran.exe -IE:\vcpkg\buildtrees\lapack-reference\src\v3.10.0-a3af633c89.clean\SRC -mabi=ms -m32 -frecursive -g -JSRC -fpreprocessed -c SRC/CMakeFiles/lapack.dir/slae2.f-pp.f -o SRC/CMakeFiles/lapack.dir/slae2.f.obj
[2478/3793] E:\vcpkg\downloads\tools\msys2\2b29df0583c528a8\mingw32\bin\gfortran.exe -IE:\vcpkg\buildtrees\lapack-reference\src\v3.10.0-a3af633c89.clean\SRC -mabi=ms -m32 -frecursive -g -JSRC -fpreprocessed -c SRC/CMakeFiles/lapack.dir/slacpy.f-pp.f -o SRC/CMakeFiles/lapack.dir/slacpy.f.obj
[2479/3793] E:\vcpkg\downloads\tools\msys2\2b29df0583c528a8\mingw32\bin\gfortran.exe -IE:\vcpkg\buildtrees\lapack-reference\src\v3.10.0-a3af633c89.clean\SRC -mabi=ms -m32 -frecursive -g -JSRC -fpreprocessed -c SRC/CMakeFiles/lapack.dir/sbdsqr.f-pp.f -o SRC/CMakeFiles/lapack.dir/sbdsqr.f.obj
[2480/3793] E:\vcpkg\downloads\tools\msys2\2b29df0583c528a8\mingw32\bin\gfortran.exe -IE:\vcpkg\buildtrees\lapack-reference\src\v3.10.0-a3af633c89.clean\SRC -mabi=ms -m32 -frecursive -g -JSRC -fpreprocessed -c SRC/CMakeFiles/lapack.dir/sgesvdq.f-pp.f -o SRC/CMakeFiles/lapack.dir/sgesvdq.f.obj
ninja: build stopped: subcommand failed.

**Comment by JackBoosY** [comment]
Maybe a gfortran bug, @Neumann-A is it?

**Comment by wzxflying** [comment]
Previously, the old version of vcpkg compiled normally, but the new version did not

**Comment by JackBoosY** [comment]
@ras0219-msft Do you have any ideas on this?

**Comment by JonLiu1993** [comment]
@wzxflying, Do you still have this problem on the latest vcpkg version? I can successfully install lapack-reference locally:
````
PS F:\Feature-test\vcpkg> ./vcpkg install lapack-reference
Computing installation plan...
The following packages are already installed:
    lapack-reference[blas-select,core,noblas]:x86-windows -> 3.11.0
lapack-reference:x86-windows is already installed
Restored 0 package(s) from C:\Users\vzhli17\AppData\Local\vcpkg\archives in 179.3 us. Use --debug to see more details.
Total install time: 949.8 us
lapack-reference provides CMake targets:

    find_package(lapack CONFIG REQUIRED)
    target_link_libraries(main PRIVATE lapack)

lapack-reference is compatible with built-in CMake targets:

    find_package(LAPACK REQUIRED)
    target_link_libraries(main PRIVATE LAPACK::LAPACK)

PS F:\Feature-test\vcpkg>

````

**Comment by LilyWangLL** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.

**Comment by Erissonleo** [comment]
I want to intall g2o by vcpkg. When it run step "building lapack-reference", the same situation happened. I try to solve this problem, but failed.

**Comment by Erissonleo** [comment]
I want to install g2o by vcpkg. When it run "building lapack-reference", same situation happened. I cannot solve this problem. I found the same issue, so I closed my issue. [https://github.com/microsoft/vcpkg/issues/32142](url)
**Environmen**
Windows 10, 22h2,  VS2022

**Comment by ChinaShrimp** [comment]
the same issue when installing colmap

Environment:
Win10, VS2019
