### ISSUE TITLE
[yasm-tool] build failure

### ISSUE THREAD

**Issue by acgetchell** [microsoft/vcpkg#24319]
**Host Environment**
- OS: Windows ARM64
- Compiler: Visual Studio Community 2022 Release - amd64_arm64

**To Reproduce**
`./vcpkg install yasm-tool`

**Failure logs**
`Error: yasm:arm64-windows@1.3.0#3 is only supported on 'windows & !uwp & !arm'`

**Additional context**
Possibly related to https://github.com/microsoft/vcpkg/pull/16478

**Comment by JackBoosY** [comment]
You should pass extra option `--host-triplet=arm64-windows` to the install command.

**Comment by acgetchell** [comment]
Ah, okay, I'm using manifest mode so I set %VCPKG_DEFAULT_TRIPLET%.
