### ISSUE TITLE
[gmp] build failure

### ISSUE THREAD

**Issue by acgetchell** [microsoft/vcpkg#24323]
**Host Environment**
- OS: Windows ARM64
- Compiler: Visual Studio Community 2022 Release - amd64_arm64

**To Reproduce**
`./vcpkg install`

Using:

https://github.com/acgetchell/CDT-plusplus/blob/develop/vcpkg.json

**Failure logs**
`Error: gmp:arm64-windows@6.2.1#9 is only supported on '!(windows & (arm | arm64))'`

**Additional context**
Prerequisite for CGAL.

**Comment by Neumann-A** [comment]
> Error: gmp:arm64-windows@6.2.1#9 is only supported on '!(windows & (arm | arm64))'

That is due to yasm only supporting x86 targets as far as I know. If you want arm support `yasm` needs to be replaced with `clang-cl` using the appropriate arch/cpu flags.

**Comment by dg0yt** [comment]
To be closed. arm64-windows support was added with #26306 in August. (Assembly is still disabled, but there is #26764.)
