### ISSUE TITLE
[utfcpp] error building x64-mingw-static in manifest mode

### ISSUE THREAD

**Issue by pattakosn** [microsoft/vcpkg#24346]
**Host Environment**
- Win10
- gcc 11.2.0 / amd64 / msys2

**To Reproduce**
run this in a manifest enabled project (i can share if you want to try it):
`cmake -DVCPKG_TARGET_TRIPLET=x64-mingw-static -DVCPKG_HOST_TRIPLET=x64-mingw-static ..`

**Failure logs**
Starting package 2/20: utfcpp:x64-mingw-static
Building package utfcpp[core]:x64-mingw-static...
-- Using community triplet x64-mingw-static. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: D:\learnopengl-mine\vcpkg\triplets\community\x64-mingw-static.cmake
-- Downloading https://github.com/nemtrif/utfcpp/archive/v3.2.1.tar.gz -> nemtrif-utfcpp-v3.2.1.tar.gz...
-- Extracting source D:/learnopengl-mine/vcpkg/downloads/nemtrif-utfcpp-v3.2.1.tar.gz
-- Using source at D:/learnopengl-mine/vcpkg/buildtrees/utfcpp/src/v3.2.1-9f3df3227a.clean
-- Configuring x64-mingw-static
-- Building x64-mingw-static-dbg
-- Building x64-mingw-static-rel
CMake Error at scripts/cmake/vcpkg_fixup_cmake_targets.cmake:95 (message):
  'D:/learnopengl-mine/vcpkg/packages/utfcpp_x64-mingw-static/debug/cmake'
  does not exist.
Call Stack (most recent call first):
  ports/utfcpp/portfile.cmake:21 (vcpkg_fixup_cmake_targets)
  scripts/ports.cmake:145 (include)

error: building utfcpp:x64-mingw-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+utfcpp
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[utfcpp]+Build+error
including:
  package: utfcpp[core]:x64-mingw-static -> 3.2.1
    vcpkg-tool version: 2022-03-30-692785ac944e81417840c6de244fb3e18a4b35eb
    vcpkg-scripts version: ed6dc3a43 2022-04-21 (18 hours ago)

Additionally, attach any relevant sections from the log files above.
-- Running vcpkg install - failed
CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:850 (message):
  vcpkg install failed.  See logs for more information:
  D:\learnopengl-mine\cmake-build-release-mingw\vcpkg-manifest-install.log
Call Stack (most recent call first):
  D:/Program Files/Jetbrains/apps/CLion/ch-0/221.5080.224/bin/cmake/win/share/cmake-3.22/Modules/CMakeDetermineSystem.cmake:124 (include)
  CMakeLists.txt:18 (project)

CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. This issue has been fixed in PR #26954, so I am closing this issue for now.
