### ISSUE TITLE
$ENV doesn't work in Windows

### ISSUE THREAD

**Issue by david-aimsun** [microsoft/vcpkg#24343]
Environment variables in portfile.cmake are not read in Windows. In macOS they are.

**Environment**
- OS: Windows
- Compiler: Visual 2022
- Vcpkg package management program version 2022-03-30-692785ac944e81417840c6de244fb3e18a4b35eb

**To Reproduce**

add this line to the beginning of any portfile.cmake:

```
message( STATUS "MYVAR value is $ENV{MYVAR}" )
```

Define a value in the shell (powershell in my case) and install the port:

```
$env:MYVAR="SOME_VALUE"
vcpkg install modified-port
```

In macOS the line shows (as expected):

```
-- MYVAR value is SOME_VALUE
```

In Windows:

```
-- MYVAR value is
```

Using cmake directly shows the value correctly in Windows:

```
cmake -P portfile.cmake
```

**Comment by autoantwort** [comment]
It's not a bug, it's a feature: https://github.com/microsoft/vcpkg/blob/master/docs/users/triplets.md#vcpkg_env_passthrough 😄

**Comment by david-aimsun** [comment]
@autoantwort Thanks but I cannot make it work. I have tried:

```
$env:MYVAR="SOME_VALUE"
$env:VCPKG_ENV_PASSTHROUGH_UNTRACKED="MYVAR"
vcpkg install modified-port
```

with no success. Any help is welcomed :)

**Comment by Neumann-A** [comment]
> with no success. Any help is welcomed :)

you need to set the variable in the triplet. Otherwise it will not have any effect.

**Comment by david-aimsun** [comment]
@Neumann-A  Thanks, it works as expected :)

Note to self: My triplet was `x64-windows`, the triplet file was `$VCPKG_ROOT/triplets/x64-windows.cmake` and the line to add was: `set(VCPKG_ENV_PASSTHROUGH_UNTRACKED MYVAR)`
