### ISSUE TITLE
[rhash] update to 1.4.2

### ISSUE THREAD

**Issue by PriitUring** [microsoft/vcpkg#24340]
Library name: RHash

New version number: 1.4.2

https://github.com/rhash/RHash/releases/tag/v1.4.2

**Comment by Thomas1664** [comment]
@PriitUring May I ask why you're requesting that many (24) port updates during the last few days?

**Comment by PriitUring** [comment]
@Thomas1664

I'm sorry if I sent too many requests today, just didn't see if there's any specific request limit, waited when most get merged or other specific time to pass or timeframes to honour to request updates or if I should had made a single list or tried to create a pull requests instead.

Maybe good to add some reminders, links or extra info to read before being allowed to request or post something. Wiki page seems empty here aswell.

I'm not in a rush to get something specific updated here.

Just noticed that some haven't been updated in VCPKG for a long time and some might take months or longer to have updated if at all if new issues arise.

If these can't be updated or if I should have given chance to others to request updates instead or waited for certain time to pass or if I should had written if worth updating anything at all, then I'm ok if these currently get closed.

Sorry if my wording is not good enough or just too long reply, thank you for reading.

I was planning to take a break and will take a break, will try my best not to bother anyone anywhere for a while.

**Comment by Thomas1664** [comment]
First, note that my intention was not to make you stop opening issues/ request port updates.

>Just noticed that some haven't been updated in VCPKG for a long time and some might take months or longer to have updated if at all if new issues arise.

That sounds like you're not using/ want to use those ports . In this case, maintainers (note that I'm not a maintainer) would prefer if you opened a PR instead. Again, there is nothing wrong with opening one or more issues to request updates. In most cases, updating a port is very easy, so feel free to open up a PR. To get started, please have a look at the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md). Taking a look at some PRs that closed one of your update requests might me helpful as well.

**Comment by PriitUring** [comment]
@Thomas1664
Well I couldn't find anything positive or proper valuable discussion when I searched online for  "vcpkg signing agreement".

Only reply to another users several concerns about some unfavorable or not suitable wording for European residents, legal aspects, non Microsoft employees, not really open source agreement etc in 2019 issue post was that there's no plans to update the agreement. Issue nr. in GitHub: 6899

So bit skeptical to share personal details and agree to something when officially there's no proper easy to understand explanation how safe or worry free should an average person be when wishing to try helping out and signing the agreement.

So even if I provide my personal address, email and signature to tryout updating some packages versions in vcpkg. I'll still at least need to know:

1. So should I worry about anything before I sign the agreement and then try updating various package versions?

2. If packages versions have been regularly updated by specific contributors or maintainers then is it still ok and doesn't really matter who creates a newer version update pull request?

3. You wrote you're not maintainer, yet it seems as if you do update packages versions in vcpkg and you shared with me a link to maintainers guide, so shouldn't there be extra guides added for new contributors or non maintainers and is there any noticeable difference between certain contributors or knowing the word difference doesn't really matter?

4. If I start contributing, then I can assign my self to fix my own or other users issues and add labels to issues?

**Comment by Thomas1664** [comment]
> 1. So should I worry about anything before I sign the agreement and then try updating various package versions?

You have to provide your real name and your real email address. If you don't want to have your email included in commits, there is a GitHub setting to use an anonymous GitHub email instead. @BillyONeal can probably provide more information on this.

> If packages versions have been regularly updated by specific contributors or maintainers then is it still ok and doesn't really matter who creates a newer version update pull request?

Nobody takes some kind of "ownership" on a port. Feel free to update any port you like.

> You wrote you're not maintainer, yet it seems as if you do update packages versions in vcpkg and you shared with me a link to maintainers guide, so shouldn't there be extra guides added for new contributors or non maintainers and is there any noticeable difference between certain contributors or knowing the word difference doesn't really matter?

Yes, I'm just e very active community member. However, there are people like @FrankXie05 that are marked as contributors but are actually maintainers. Those people are usually assigned to issues/ PRs (this doesn't mean that you can't work on an issue).
Yes, better documentation for newcomers is definitely needed.

> If I start contributing, then I can assign my self to fix my own or other users issues and add labels to issues?

No, the people who are assigned to an issue are maintainers. If you want to work on an issue, just start, no need to ask for permission. If you open issues that you want to fix by yourself, it's probably better to mention this in the first few issues. The way I do it is I don't open an issue at all before I start updating a port; You don't have to open an issue at first to update a port.

**Comment by PriitUring** [comment]
@Thomas1664

Ok, so I shouldn't worry about any legal stuff, licence ownership and my residency when signing the agreement before trying to update ports?

What about licence files of ports, should certain ports with specific license or a missing licence be better left for maintainers to update or as long as some kind of source code is available for download it's fine for everyone else to update in vcpkg?

Latest port versions Git Tree and source SHA512 hash is somewhere hidden or somehow automatically given or updated if I can't find these written in source website?

**Comment by Thomas1664** [comment]
> Ok, so I shouldn't worry about any legal stuff, licence ownership and my residency when signing the agreement before trying to update ports?

Again, if you have any concerns, either DM Billy on Discord or write an email to vcpkg@microsoft.com. You can read the CLA here: https://cla.opensource.microsoft.com/microsoft/vcpkg. I'm not the right person to ask any legal questions.

> What about licence files of ports, should certain ports with specific license or a missing licence be better left for maintainers to update or as long as some kind of source code is available for download it's fine for everyone else to update in vcpkg?

You don't have to care about that too much. Because every port must install a `copyright` file, there is always some kind of license included.

> Latest port versions Git Tree and source SHA512 hash is somewhere hidden or somehow automatically given or updated if I can't find these written in source website?

If you're referring to `port-version` in manifest files, you increment it if you modified the port but didn't update the version. If you update a port, you remove `port-version`. This resets it to 0. `git-tree` in the version database is updated by running `vcpkg x-add-version <port name>`. If you already ran `vcpkg x-add-version <port name>` but modified the port again in the same PR, you append `--overwrite-version`. The easiest way to get `SHA512` is to set it to 0 and look at the error message when you try to install that port (`vcpkg install <port name>`. There you will find something like `expected hash`.

**Comment by PriitUring** [comment]
@Thomas1664
Ok, thank you taking time for answering.

Will think through what to ask if I do send an email to try to get clarification of certain things that haven't been publicly answered to other users long ago and maybe only then see later how easy it is to do the port version updating etc.

I did notice that some ports don't have licence type line at all or are later written "Null", when some do their pull requests. And some ports have date numbers instead of any specific release version number.

**Comment by Thomas1664** [comment]
> Will think through what to ask if I do send an email to try to get clarification of certain things that haven't been publicly answered to other users long ago and maybe only then see later how easy it is to do the port version updating etc.

Don't worry, most of your questions on how to do port updates will likely be answered after you created some PRs.

> I did notice that some ports don't have licence type line at all or are later written "Null", when some do their pull requests. And some ports have date numbers instead of any specific release version number.

We're adding license information when we update a port. Currently, we have to manually research the right license identifier. There are plans to automate this. Some ports have version-date because they don't provide any version tags or they didn't release a version for a long time, but the port was updated to a newer git commit. See [manifest guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/manifest-files.md). (We don't use `version-string` the way this page suggests. It's only used for versions that don't follow the `x.y.z` scheme like `deprecated` or `1.1.1.n`.)

**Comment by PriitUring** [comment]
@Thomas1664

Ok, thank you.

Will hide and mark my previous replies as resolved for now.

Will maybe later try out and see how things work exactly.

Will need to read and look around more why some ports are still updated with date number when release version numbers and source files for that release are also publicly available.

**Comment by FrankXie05** [comment]
@Thomas1664 @PriitUring 
Thank you very much **Thomas** for your reply. As the maintainer of vcpkg, we are very willing to see more and more users participating in the improvement. If you have any suggestions or questions, please feel free to submit an issue or pull request , We will guarantee to respond within 12 hours, of course, you can also consult contributors: such as **Thomas**, **dg0yt** , **Neumann-A** , **Osyotr**, etc. Thanks again for your many recent submissions and **Thomas** for the replies. :)
