### ISSUE TITLE
[New Port Request] asmtk

### ISSUE THREAD

**Issue by stevemk14ebr** [microsoft/vcpkg#24359]
Library name: asmtk
Library description: Assembler toolkit based on AsmJit

Source repository URL: https://github.com/asmjit/asmtk

Project homepage (if different from the source repository): N/A

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
This library depends on the already existing port asmjit. It's already up to date to use the latest version. I have struggled making this port myself, I do not understand vcpkg enough for this.

**Comment by acidicoala** [comment]
A vcpkg-friendly CMakeLists.txt for asmtk is being developed here: https://github.com/acidicoala/asmtk/blob/master/CMakeLists.txt

**Comment by stevemk14ebr** [comment]
Asmtk master (upstream) cmakelist is now vcpkg compatible! The fork by @acidicoala has been merged. This port should be able to move forward

**Comment by acidicoala** [comment]
asmtk still depends on the latest asmjit, which Microsoft isn't going to update unless Facebook decides to finally make use of it.

**Comment by stevemk14ebr** [comment]
Asked for an update again here https://github.com/pytorch/FBGEMM/issues/1070

**Comment by JackBoosY** [comment]
Can anyone make a PR to add this port? I can give some help.

**Comment by LilyWangLL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
