### ISSUE TITLE
[rtlsdr] build failure while using the port

### ISSUE THREAD

**Issue by ankurvdev** [microsoft/vcpkg#24351]
**Host Environment**
- OS: Windows
- Compiler: revision : VS2022 17.1

**To Reproduce**
`./vcpkg install rtlsdr:x64-windows-static-md`
And in a cmake project utilizing that port
use 
find_package(rtlsdr CONFIG REQURED)

**Failure logs**
  ```
  C:/Program Files/Microsoft Visual Studio/2022/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.22/Modules/FindPkgConfig.cmake:99 (find_package_handle_standard_args)
  E:/vcpkg.devel/installed/x64-windows-static-md/share/rtlsdr/rtlsdrConfig.cmake:1 (include)
  E:/vcpkg.devel/scripts/buildsystems/vcpkg.cmake:816 (_find_package)
  src/server/libadsb/CMakeLists.txt:31 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at E:/vcpkg.devel/installed/x64-windows-static-md/share/rtlsdr/rtlsdrTargets.cmake:86 (message):
  The imported target "rtlsdr::rtlsdr" references the file

     "E:/vcpkg.devel/installed/x64-windows-static-md/debug/bin/rtlsdr.dll"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "E:/vcpkg.devel/installed/x64-windows-static-md/share/rtlsdr/rtlsdrTargets.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  E:/vcpkg.devel/installed/x64-windows-static-md/share/rtlsdr/rtlsdrConfig.cmake:7 (include)
  E:/vcpkg.devel/scripts/buildsystems/vcpkg.cmake:816 (_find_package)
  ```
  
**Additional context**

The rtlsdr port cmake is hardcoded to generate a Target.cmake that contains both static and dynamic targets.
For some reason the x64-windows (dynamic) triplet is ok intializing the (potentially incorrect) rtlsdr_static target as well as the rtlsdr target (dynamic) but on x64-windows-static-md since there are no dynamic dlls the find_package call fails

**Comment by FrankXie05** [comment]
@ankurvdev Thanks for posting this issue, could you please provide your example project?

- CMakeLists.txt
- main.cpp

**Comment by ankurvdev** [comment]
Thr triplet you're using seems to be 
x64-windows

The problem is specific to 

x64-windows-static-md

**Comment by JonLiu1993** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
