### ISSUE TITLE
[winpcap] Build error

### ISSUE THREAD

**Issue by kaixin2007** [microsoft/vcpkg#24358]
**Host Environment**
- OS: Windows
- Compiler: Visual Studio 2019 Build Tools

**To Reproduce**
`./vcpkg install xxxx`
.\vcpkg.exe install winpcap:x64-windows

**Failure logs**
-Cut and paste the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.
Computing installation plan...
The following packages will be built and installed:
    winpcap[core]:x64-windows -> 4.1.3#8
Detecting compiler hash for triplet x64-windows...
Restored 0 packages from C:\Users\KaiXin\AppData\Local\vcpkg\archives in 299.7 us. Use --debug to see more details.
Starting package 1/1: winpcap:x64-windows
Building package winpcap[core]:x64-windows...
-- Using cached WpcapSrc_4_1_3.zip.
-- Extracting source G:/src/vcpkg/downloads/WpcapSrc_4_1_3.zip
-- Applying patch G:/src/vcpkg/buildtrees/winpcap/src/packetNtx.patch
-- Applying patch G:/src/vcpkg/buildtrees/winpcap/src/wpcap.patch
-- Applying patch G:/src/vcpkg/ports/winpcap/create_lib.patch
-- Applying patch G:/src/vcpkg/ports/winpcap/fix-create-lib-batch.patch
-- Using source at G:/src/vcpkg/buildtrees/winpcap/src/4_1_3-2020b05bdd.clean
-- Building G:/src/vcpkg/buildtrees/winpcap/src/4_1_3-2020b05bdd.clean/packetNtx/Dll/Project/Packet.sln for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:128 (message):
    Command failed: msbuild G:/src/vcpkg/buildtrees/winpcap/src/4_1_3-2020b05bdd.clean/packetNtx/Dll/Project/Packet.sln /p:Configuration=Release /t:Rebuild /p:Platform=x64 /p:PlatformToolset=v142 /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /p:WindowsTargetPlatformVersion=10.0.18362.0 /p:VcpkgManifestInstall=false /p:VcpkgManifestEnabled=false /m /p:VcpkgEnabled=false
    Working Directory: G:/src/vcpkg/buildtrees/winpcap/x64-windows-rel
    Error code: 1
    See logs for more information:
      G:\src\vcpkg\buildtrees\winpcap\build-x64-windows-rel-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_msbuild.cmake:129 (vcpkg_execute_required_process)
  ports/winpcap/portfile.cmake:62 (vcpkg_build_msbuild)
  scripts/ports.cmake:145 (include)

error: building winpcap:x64-windows failed with: BUILD_FAILED

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by dg0yt** [comment]
> See logs for more information:
> G:\src\vcpkg\buildtrees\winpcap\build-x64-windows-rel-out.log

**Comment by Cheney-W** [comment]
Could you please provide the log: G:\src\vcpkg\buildtrees\winpcap\build-x64-windows-rel-out.log to us?

**Comment by Cheney-W** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
