### ISSUE TITLE
How to install openssl 1.1.1n

### ISSUE THREAD

**Issue by muziling** [microsoft/vcpkg#24350]
I had try these steps:
1. search vcpkg install specify version parameter,  sadly no version parameter
2. create vcpkg.json,  use overrides  [ { "name": "openssl", "version-string": "1.1.1n" } ]   ,run  vcpkg install  and error occur:  Error: while checking out port openssl with git tree 7e4d802e3bde4154c227c0dd1da75c719be9f07a

**Comment by Adela0814** [comment]
The latest `openssl `version is `3.0.2`. Do you really need version 1.1.1n?
You can check your current version via `.\vcpkg search openssl`.

**Comment by muziling** [comment]
Yes , I need version 1.1.1n ，  compile an open source project , that need version 1, not 3,  3 is not supported.

**Comment by autoantwort** [comment]
Maybe run `git pull`. Which version of vcpkg are you using?

**Comment by muziling** [comment]
It's latest vcpkg 
```
git clone --depth 1 https://github.com/microsoft/vcpkg vcpkg
.\vcpkg\bootstrap-vcpkg.bat
echo '{ "name": "dbkg", "version-string": "1.0.0", "dependencies": [ "openssl", "fmt", "rapidjson", "keystone", "unicorn" ], "builtin-baseline": "2ac61f87f69f0484b8044f95ab274038fbaf7bdd", "overrides": [ { "name": "openssl", "version-string": "1.1.1n" } ] }' > vcpkg.json
.\vcpkg\vcpkg install
.\vcpkg\vcpkg integrate install
```

**Comment by autoantwort** [comment]
Hm that works on my machine

**Comment by Adela0814** [comment]
@muziling  you can use versioning to overwrite the `openssl `version to 1.1.1n, please refer to https://github.com/microsoft/vcpkg/issues/16967

**Comment by muziling** [comment]
> @muziling you can use versioning to overwrite the `openssl `version to `1.1.1n`, please refer to #16967

not support less than syntax  ,  "version<": "3.0.2" is illegal

**Comment by Adela0814** [comment]
please try to override the version:
```
  "overrides": [
    {
      "name": "openssl",
      "version": "1.1.1n"
    }
  ]
```

**Comment by muziling** [comment]
> please try to override the version:
> 
> ```
>   "overrides": [
>     {
>       "name": "openssl",
>       "version": "1.1.1n"
>     }
>   ]
> ```
version only support input number and dot.    'n' is illegal

**Comment by autoantwort** [comment]
> git clone --depth 1 https://github.com/microsoft/vcpkg vcpkg


Ah now I see the problem! `--depth 1`. Don't pass `--depth 1` and it will work.

**Comment by madaster97** [comment]
For posterity, I ran into this problem even with the most recent commit. I had to use `version-string` instead of `version` since openssl didn't use a semver string (1.1.1n). More details [here](https://github.com/microsoft/vcpkg/issues/22307#issuecomment-1042550870)
