### ISSUE TITLE
Tesseract error build demo on wiki

### ISSUE THREAD

**Issue by heightball** [Microsoft/vcpkg#2435]
trying to build the wiki demo that here https://github.com/tesseract-ocr/tesseract/wiki/APIExample

get that error with the lib:

1>------ Build started: Project: tesseract-sample, Configuration: Debug x64 ------
1>tesseract305d.lib(svutil.cpp.obj) : error LNK2019: unresolved external symbol closesocket referenced in function "public: void __cdecl SVNetwork::Close(void)" (?Close@SVNetwork@@QEAAXXZ)
1>tesseract305d.lib(svutil.cpp.obj) : error LNK2019: unresolved external symbol connect referenced in function "public: __cdecl SVNetwork::SVNetwork(char const *,int)" (??0SVNetwork@@QEAA@PEBDH@Z)
1>tesseract305d.lib(svutil.cpp.obj) : error LNK2019: unresolved external symbol htons referenced in function "int __cdecl GetAddrInfoNonLinux(char const *,int,struct addrinfo * *)" (?GetAddrInfoNonLinux@@YAHPEBDHPEAPEAUaddrinfo@@@Z)
1>tesseract305d.lib(svutil.cpp.obj) : error LNK2019: unresolved external symbol recv referenced in function "public: char * __cdecl SVNetwork::Receive(void)" (?Receive@SVNetwork@@QEAAPEADXZ)
1>tesseract305d.lib(svutil.cpp.obj) : error LNK2019: unresolved external symbol select referenced in function "public: char * __cdecl SVNetwork::Receive(void)" (?Receive@SVNetwork@@QEAAPEADXZ)
1>tesseract305d.lib(svutil.cpp.obj) : error LNK2019: unresolved external symbol send referenced in function "public: void __cdecl SVNetwork::Flush(void)" (?Flush@SVNetwork@@QEAAXXZ)
1>tesseract305d.lib(svutil.cpp.obj) : error LNK2019: unresolved external symbol socket referenced in function "public: __cdecl SVNetwork::SVNetwork(char const *,int)" (??0SVNetwork@@QEAA@PEBDH@Z)
1>tesseract305d.lib(svutil.cpp.obj) : error LNK2019: unresolved external symbol gethostbyname referenced in function "int __cdecl GetAddrInfoNonLinux(char const *,int,struct addrinfo * *)" (?GetAddrInfoNonLinux@@YAHPEBDHPEAPEAUaddrinfo@@@Z)
1>tesseract305d.lib(svutil.cpp.obj) : error LNK2019: unresolved external symbol WSAStartup referenced in function "int __cdecl GetAddrInfoNonLinux(char const *,int,struct addrinfo * *)" (?GetAddrInfoNonLinux@@YAHPEBDHPEAPEAUaddrinfo@@@Z)
1>C:\Users\frand\source\repos\tesseract-ocr-sample-master\x64\Debug\tesseract-sample.exe : fatal error LNK1120: 9 unresolved externals
1>Done building project "test_ocr.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by KindDragon** [comment]
You should link `Ws2_32.lib` library to your sample https://msdn.microsoft.com/ru-ru/library/windows/desktop/ms737582%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396
