### ISSUE TITLE
[New Port Request] openh264

### ISSUE THREAD

**Issue by freyu01** [microsoft/vcpkg#24354]
Library name: openh264

Library description:
OpenH264 is a codec library which supports H.264 encoding and decoding. It is suitable for use in real time applications such as WebRTC.

Source repository URL: https://github.com/cisco/openh264

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by Osyotr** [comment]
It's already in vcpkg https://github.com/microsoft/vcpkg/tree/master/ports/openh264

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. `openh264` is already in vcpkg, you can install it.
