### ISSUE TITLE
[boost-exception] Build error

### ISSUE THREAD

**Issue by sj-silva** [microsoft/vcpkg#24364]
**Host Environment**
- [Windows 10 Home]

**To Reproduce**
./vcpkg install mlpack

**Failure logs**
-- Extracting source C:/DEV/vcpkg/downloads/boostorg-exception-boost-1.79.0.tar.gz
-- Using source at C:/DEV/vcpkg/buildtrees/boost-exception/src/ost-1.79.0-1b4bdfb5ca.clean
CMake Error: File C:/DEV/vcpkg/installed/x86-windows/share/boost-build/user-config.jam does not exist.
CMake Error at installed/x64-windows/share/boost-build/boost-modular-build.cmake:356 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  ports/boost-exception/portfile.cmake:12 (boost_modular_build)
  scripts/ports.cmake:145 (include)

**error: building boost-exception:x86-windows failed with: BUILD_FAILED**

 package: boost-exception[core]:x86-windows -> 1.79.0
    vcpkg-tool version: 2022-03-30-692785ac944e81417840c6de244fb3e18a4b35eb
    vcpkg-scripts version: 2ac61f87f 2022-04-22 (32 hours ago)

**Comment by JackBoosY** [comment]
Your installed boost components are outdated.
Please use command `./vcpkg list boost` then pick the installed boost components which has triplet `x86-windows` then remove them and try again.

Thanks.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
