### ISSUE TITLE
Building package boost-regex:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by justinjk007** [Microsoft/vcpkg#2436]
I'm on windows 10, I was trying to install the whole boost package with `vcpkg install boost:x64-windows` and it was fine in the beginning then when building the regex library it failed.
 
![image](https://user-images.githubusercontent.com/12916795/34323599-d6b5296e-e81e-11e7-8791-dd94004e7e0a.png)

[build-x64-windows-rel-err.log](https://github.com/Microsoft/vcpkg/files/1584545/build-x64-windows-rel-err.log)
[build-x64-windows-rel-out.log](https://github.com/Microsoft/vcpkg/files/1584546/build-x64-windows-rel-out.log)

And here is the shell output
```shell
Starting package 1/107: boost-regex:x64-windows
Building package boost-regex:x64-windows...
-- CURRENT_INSTALLED_DIR=D:/Program Files/vcpkg/installed/x64-windows
-- DOWNLOADS=D:/Program Files/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=D:/Program Files/vcpkg/packages/boost-regex_x64-windows
-- CURRENT_BUILDTREES_DIR=D:/Program Files/vcpkg/buildtrees/boost-regex
-- CURRENT_PORT_DIR=D:/Program Files/vcpkg/ports/boost-regex/.
-- Using cached D:/Program Files/vcpkg/downloads/boostorg-regex-boost-1.66.0.tar.gz
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:44 (message):
    Command failed: D:/Program Files/vcpkg/installed/x64-windows/tools/boost-build/b2.exe;--stagedir=D:/Program Files/vcpkg/buildtrees/boost-regex/x64-windows-rel/stage;--build-dir=D:/Program Files/vcpkg/buildtrees/boost-regex/x64-windows-rel;--user-config=D:/Program Files/vcpkg/buildtrees/boost-regex/x64-windows-rel/user-config.jam;-j4;--debug-configuration;--debug-building;--debug-generators;--disable-icu;--ignore-site-config;--hash;-q;threadapi=win32;threading=multi;runtime-link=shared;link=shared;address-model=64;architecture=x86;toolset=msvc-14.0;variant=release;debug-symbols=on
    Working Directory: D:/Program Files/vcpkg/buildtrees/boost-regex/src/regex-boost-1.66.0
    See logs for more information:
      D:\Program Files\vcpkg\buildtrees\boost-regex\build-x64-windows-rel-out.log
      D:\Program Files\vcpkg\buildtrees\boost-regex\build-x64-windows-rel-err.log

Call Stack (most recent call first):
  installed/x64-windows/share/boost-vcpkg-helpers/boost-modular.cmake:174 (vcpkg_execute_required_process)
  ports/boost-regex/portfile.cmake:20 (boost_modular_build)
  scripts/ports.cmake:72 (include)


Error: Building package boost-regex:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-regex:x64-windows
  Vcpkg version: 0.0.100-2017-12-19-6cb6a61aaf5ef2c143f974e9f731778bcd3f5cbe

Additionally, attach any relevant sections from the log files above.
```

**Comment by bitsrules** [comment]
It seems to work with me. Did you update vcpkg via git pull ?

**Comment by justinjk007** [comment]
Yeah....I did that...

**Comment by bitsrules** [comment]
Another silly Q: vcpkg.exe remove --outdated
I am on Windows 10 and Visual Studio 2017

**Comment by justinjk007** [comment]
Oh I didn't do this...I will do this and get back in 6 hours...I gotta sleep

**Comment by bitsrules** [comment]
From your error it seems to have problems with spaces in the path, i.e. D:/Program Files
Try placing vcpkg in a directory name with no spaces.

**Comment by justinjk007** [comment]
Yessss...moving vcpkg to a new location, `D:/Dev/vcpkg` did the trick. Everything installs correctly now, thanks @bitsrules

**Comment by xiasun** [comment]
Hi @bitsrules I am having exactly the same issue. But I have no space in dir of vcpkg. I have just installed vcpkg from git so there shouldn't be updating problem. Thanks.

Building package boost-regex[core]:x64-windows...
-- CURRENT_INSTALLED_DIR=C:/Tools/vcpkg/installed/x64-windows
-- DOWNLOADS=C:/Tools/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/Tools/vcpkg/packages/boost-regex_x64-windows
-- CURRENT_BUILDTREES_DIR=C:/Tools/vcpkg/buildtrees/boost-regex
-- CURRENT_PORT_DIR=C:/Tools/vcpkg/ports/boost-regex/.
-- Using cached C:/Tools/vcpkg/downloads/boostorg-regex-boost-1.67.0.tar.gz
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: C:/Tools/vcpkg/installed/x64-windows/tools/boost-build/b2.exe;--stagedir=C:/Tools/vcpkg/buildtrees/boost-regex/x64-windows-rel/stage;--build-dir=C:/Tools/vcpkg/buildtrees/boost-regex/x64-windows-rel;--user-config=C:/Tools/vcpkg/buildtrees/boost-regex/x64-windows-rel/user-config.jam;-j4;--debug-configuration;--debug-building;--debug-generators;--disable-icu;--ignore-site-config;--hash;-q;-sZLIB_INCLUDE="C:/Tools/vcpkg/installed/x64-windows/include";-sBZIP2_INCLUDE="C:/Tools/vcpkg/installed/x64-windows/include";threading=multi;threadapi=win32;runtime-link=shared;link=shared;address-model=64;architecture=x86;toolset=msvc-14.0;-sZLIB_BINARY=zlib;-sZLIB_LIBPATH="C:/Tools/vcpkg/installed/x64-windows/lib";-sBZIP2_BINARY=bz2;-sBZIP2_LIBPATH="C:/Tools/vcpkg/installed/x64-windows/lib";variant=release;debug-symbols=on
    Working Directory: C:/Tools/vcpkg/buildtrees/boost-regex/src/ost-1.67.0-d36604157f/build
    See logs for more information:
      C:\Tools\vcpkg\buildtrees\boost-regex\build-x64-windows-rel-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/boost-build/boost-modular-build.cmake:231 (vcpkg_execute_required_process)
  ports/boost-regex/portfile.cmake:20 (boost_modular_build)
  scripts/ports.cmake:72 (include)


Error: Building package boost-regex:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-regex:x64-windows
  Vcpkg version: 0.0.110-2018-04-28-a9d989ec056246ea320a56ca7d02b161a6fee387

Additionally, attach any relevant sections from the log files above.
