### ISSUE TITLE
[New Port Request] datasketches-cpp

### ISSUE THREAD

**Issue by hudengjunai** [microsoft/vcpkg#24370]
Library name:datasketches-cpp

Library description: Data scketch is an important bigdata profiler sketch library.

Source repository URL:https://github.com/apache/datasketches-cpp

Project homepage (if different from the source repository): https://datasketches.apache.org/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
