### ISSUE TITLE
add triplet translation for the msbuild tool

### ISSUE THREAD

**Issue by scanban** [microsoft/vcpkg#2437]
Rationale: adding new build triplets breaks integration with Visual studio build in scripts\buildsystems\msbuild\vcpkg.targets during mapping from standard Visual Studio build target to package triplet. Adding additional level of translation, allows to have multiple triplets mapped to the same platform target. Example is adding x64-windows-static-dynamic-runtime triplet, used to build static libraries with dynamic runtime dependency.

changes:  https://github.com/scanban/vcpkg/commit/7b0ccd546ce92c7f15fc1a55906e32f8cc952a8c

**Comment by ras0219-msft** [comment]
This is interesting!

But first -- did you know you can set the MSBuild property `VcpkgTriplet` in your vcxproj (in the `"Globals"` section) and it will override the triplet selection process?

**Comment by scanban** [comment]
Yeah, I know. Problem is that this 'll require additional configuration from user. I was thought about minimal user intervention. Was tried to model the following workflow, that could be used in distributed development:
- build package in vcpkg once
- export as nuget package
- then all other developers could should simply import nuget package (and ofc update to the new version when available)
Goal is to minimize effort needed for other developers to create compatible development environment.

**Comment by ras0219-msft** [comment]
Thanks, this is helpful!

Have you considered editing the x86-windows (and friends) triplets directly?

**Comment by scanban** [comment]
You mean to add placeholders to the vcpkg.targets file and then edit it contents during package creation ? Yes, it's possible ofc. Honestly, decided to add additional level of indirection to minimize chance to break something.

**Comment by NancyLi1013** [comment]
This issue hasn’t been updated in a year; if it is still an issue, please reopen.
