### ISSUE TITLE
[pybind11] update to 2.9.1

### ISSUE THREAD

**Issue by demberto** [microsoft/vcpkg#24371]
Library name: pybind11

New version number: 2.9.1

[Changelog](https://pybind11.readthedocs.io/en/stable/changelog.html#version-2-9-1-feb-2-2022)

**Comment by JonLiu1993** [comment]
@demberto,Thanks for posting this issue, pybind11 has updated to 2.9.2 by pr #23893, please use command "git pull" updat your vcpkg and use it

**Comment by demberto** [comment]
@JonLiu1993 thanks for the fast reply and action 🚀
