### ISSUE TITLE
[geos] update to 3.10.2

### ISSUE THREAD

**Issue by AmoXT** [microsoft/vcpkg#24380]
Library name:geos

New version number:3.10.2

the current version has a problem with IsValid() test, this is a big problem, and the 3.10.2 has repaired it
https://libgeos.org/posts/2021-11-02-geos-3-10-2-released/

**Comment by PriitUring** [comment]
Please atleast edit the title to be easier to read and more common with rest of port update requests:
> [geos] update to 3.10.2
