### ISSUE TITLE
[mpg123] Build error

### ISSUE THREAD

**Issue by 995939901** [microsoft/vcpkg#24381]
**Host Environment**
- OS: arm64-linux
- Compiler:麒麟

**To Reproduce**
./vcpkg install osg[plugins,tools]:arm64-linux --allow-unsupported

**Failure logs**
FAILED: src/libmpg123/CMakeFiles/libmpg123.dir/data/usershare/vcpkg/buildtrees/mpg123/src/ffb82ffbeb-e55c71420d.clean/src/libmpg123/frame.c.o 
/usr/bin/cc -DOPT_GENERIC -DOPT_GENERIC_DITHER -DOPT_MULTI -DOPT_NEON64 -DREAL_IS_FIXED -I/data/usershare/vcpkg/buildtrees/mpg123/src/ffb82ffbeb-e55c71420d.clean/ports/cmake/src/../../../src -I/data/usershare/vcpkg/buildtrees/mpg123/arm64-linux-dbg/src -I/data/usershare/vcpkg/buildtrees/mpg123/src/ffb82ffbeb-e55c71420d.clean/ports/cmake/src/../../../src/compat -I/data/usershare/vcpkg/buildtrees/mpg123/src/ffb82ffbeb-e55c71420d.clean/ports/cmake/src/../../../src/libmpg123 -I/data/usershare/vcpkg/buildtrees/mpg123/arm64-linux-dbg/src/libmpg123 -I/data/usershare/vcpkg/buildtrees/mpg123/src/ffb82ffbeb-e55c71420d.clean/ports/cmake/src/libmpg123/../../../../src/libmpg123 -fPIC -g -MD -MT src/libmpg123/CMakeFiles/libmpg123.dir/data/usershare/vcpkg/buildtrees/mpg123/src/ffb82ffbeb-e55c71420d.clean/src/libmpg123/frame.c.o -MF src/libmpg123/CMakeFiles/libmpg123.dir/data/usershare/vcpkg/buildtrees/mpg123/src/ffb82ffbeb-e55c71420d.clean/src/libmpg123/frame.c.o.d -o src/libmpg123/CMakeFiles/libmpg123.dir/data/usershare/vcpkg/buildtrees/mpg123/src/ffb82ffbeb-e55c71420d.clean/src/libmpg123/frame.c.o -c /data/usershare/vcpkg/buildtrees/mpg123/src/ffb82ffbeb-e55c71420d.clean/src/libmpg123/frame.c
In file included from /data/usershare/vcpkg/buildtrees/mpg123/src/ffb82ffbeb-e55c71420d.clean/src/libmpg123/mpg123lib_intern.h:311,
                 from /data/usershare/vcpkg/buildtrees/mpg123/src/ffb82ffbeb-e55c71420d.clean/src/libmpg123/frame.c:10:
/data/usershare/vcpkg/buildtrees/mpg123/src/ffb82ffbeb-e55c71420d.clean/src/libmpg123/optimize.h:198:2: error: #error "Bad decoder choice together with fixed point math!"
  198 | #error "Bad decoder choice together with fixed point math!"
      |  ^~~~~
[4/57] /usr/bin/cc  -I/data/usershare/vcpkg/buildtrees/mpg123/src/ffb82ffbeb-e55c71420d.clean/ports/cmake/src/../../../src -

**Additional context**
995939901@qq.com

**Comment by abique** [comment]
I have the same error.
