### ISSUE TITLE
[lcm] Fix tooling support in Linux/macOS

### ISSUE THREAD

**Issue by venabled** [microsoft/vcpkg#24408]
****

**Is your feature request related to a problem? Please describe.**
Right now, the `lcm` portfile searches for `.exe` files to install as tools, which don't exist in non-Windows systems. Downstream users of the lib, when including the LCMTargets/config.cmake files will get an error that these targets are called out but don't exit

**Proposed solution**
Modify the port file to explicitly name the installed tools, copy these to the `tools/lcm` folder

**Describe alternatives you've considered**
Could alternatively dynamically search for the targets in the binary directory

**Additional context**
None

**Comment by Adela0814** [comment]
Fixed in https://github.com/microsoft/vcpkg/pull/26568
