### ISSUE TITLE
[activemq-cpp] Build error

### ISSUE THREAD

**Issue by minhaajk** [microsoft/vcpkg#24401]
**Host Environment**
- OS: Linux
- Compiler: revision

**To Reproduce**
./vcpkg install activemq-cpp

**Failure logs**
Starting package 3/3: activemq-cpp:x64-linux
Building package activemq-cpp[core]:x64-linux...
-- Downloading https://www.apache.org/dist/activemq/activemq-cpp/3.9.5/activemq-cpp-library-3.9.5-src.tar.bz2 -> activemq-cpp-library-3.9.5-src.tar.bz2...
-- Extracting source /home/minhaaj/app/vcpkg/downloads/activemq-cpp-library-3.9.5-src.tar.bz2
-- Using source at /home/minhaaj/app/vcpkg/buildtrees/activemq-cpp/src/-library-3-c86c7cf3b2.clean
-- Getting CMake variables for x64-linux-dbg
-- Getting CMake variables for x64-linux-rel
CMake Error at scripts/cmake/vcpkg_configure_make.cmake:619 (message):
  activemq-cpp requires autoconf from the system package manager (example:
  "sudo apt-get install autoconf")
Call Stack (most recent call first):
  ports/activemq-cpp/portfile.cmake:25 (vcpkg_configure_make)
  scripts/ports.cmake:145 (include)

error: building activemq-cpp:x64-linux failed with: BUILD_FAILED

**Comment by JackBoosY** [comment]
```
activemq-cpp requires autoconf from the system package manager (example:
"sudo apt-get install autoconf")
```

**Comment by minhaajk** [comment]
Hello, autoconf is installed in the system, still this error

**Comment by JackBoosY** [comment]
Please try `sudo apt-get autoconf automake libtool`.

**Comment by minhaajk** [comment]
@JackBoosY Thanks..the issue got resolved
