### ISSUE TITLE
dcmtk DCM_DICT_DEFAULT_PATH is not defined via osconfig.h

### ISSUE THREAD

**Issue by take5v** [microsoft/vcpkg#24403]
**Describe the bug**

When I compile a project with dcmtk 3.6.6#3 I get compilation error in dcdict.h: DCM_DICT_DEFAULT_PATH is not defined via osconfig.h. Apparently, this is because it was removed in a recent portfile: see https://github.com/microsoft/vcpkg/commit/c4f3862e4ce56ddd612a53845a467e945a2341a8.

**Environment**
- OS: MacOS
- Compiler: Clang 13.0.0 x86_64-apple-darwin21.4.0

**To Reproduce**
1. ./vcpkg install dcmtk
2. No defined marco DCM_DICT_DEFAULT_PATH in dcmtk/osconfig.h.
3. Create main file and add #include "dcmtk/dcmdata/dcdict.h"
4. Compilation error

**Expected behavior**
DCM_DICT_DEFAULT_PATH must be defined in dcmtk/osconfig.h.

**Comment by JackBoosY** [comment]
Also, `DCM_DICT_DEFAULT_PATH` was hardcoded in Windows.

**Comment by JackBoosY** [comment]
In _include/dcmtk/config/osconfig.h_:
```cpp
...
#define DCMTK_PREFIX "F:\\vcpkg\\packages\\dcmtk_x86-windows"
...
#define DCM_DICT_DEFAULT_PATH "F:\\vcpkg\\packages\\dcmtk_x86-windows\\share\\dcmtk\\dicom.dic;F:\\vcpkg\\packages\\dcmtk_x86-windows\\share\\dcmtk\\private.dic"
...
```
Thoese macros are hardcoded. I will fix this issue after https://github.com/microsoft/vcpkg/pull/24076 have some conclusion.

**Comment by JackBoosY** [comment]
After discussing with PR #24076, we believe this type of issue is best addressed upstream to avoid some security reasons.

Can you please open an issue in the upstream?

Thanks.

**Comment by take5v** [comment]
I built 3.6.6#3 dcmtk statically with vcpkg and don't have any issue anymore. Not sure what was changed in order to properly define DCM_DICT_DEFAULT_PATH.
