### ISSUE TITLE
[mimallac] pthread static linkage

### ISSUE THREAD

**Issue by niclar** [microsoft/vcpkg#24404]
mimalloc seems to default to a dynamic pthread linkage ( `find_library(MI_LIBPTHREAD pthread)` ) even though the library itself is built as static.

-Can we make static linkage to pthread an option for those of us that link all statically ?

Maybe something like pushing & popping the below;

if( MIMALLOC_USE_STATIC_LIBS )
    set(CMAKE_FIND_LIBRARY_SUFFIXES .a)
endif()

**Comment by LilyWangLL** [comment]
I install `mimallac` on Linux, it can search `libpthread.a`, this is **config-x64-linux-dbg-out.log**:
```
-- Library base name: mimalloc-debug
-- Version          : 2.0
-- Build type       : debug
-- C++ Compiler     : /usr/bin/c++
-- Compiler flags   : -Wall;-Wextra;-Wno-unknown-pragmas;-fvisibility=hidden;-ftls-model=initial-exec
-- Compiler defines : MI_DEBUG=3
-- Link libraries   : /usr/lib/x86_64-linux-gnu/libpthread.a;/usr/lib/x86_64-linux-gnu/librt.a
-- Build targets    : static
```

**Comment by niclar** [comment]
I got it to link and build but linking pthread (+ std libs & rt) statically turned out to be quite unreliable for us with occasional segfaults.

**Comment by LilyWangLL** [comment]
Sorry, I can't understand your means, could you provide an example or steps to reproduce this issue in detail?

**Comment by LilyWangLL** [comment]
Ping @niclar for response.
