### ISSUE TITLE
feedback on harfbuzz updates

### ISSUE THREAD

**Issue by ebraminio** [Microsoft/vcpkg#2441]
Hey guys, any particular issue on https://github.com/Microsoft/vcpkg/commit/0aa1bfe293454874eeae33ce80f2469ea28edb59 ? I can not access you CI log so felt asking so would be best.

Also I am changing upstream to use GNUInstallDirs https://github.com/harfbuzz/harfbuzz/pull/665 can you check if the change is OK to vcpkg? Thank you

**Comment by jasjuang** [comment]
@ebraminio I tried building harfbuzz  with the latest release 1.7.4 and it fails. I tried building it with the latest master and it still failed. Were you able to build it successfully in vcpkg?

**Comment by ebraminio** [comment]
What errors it gives? HarfBuzz has a Windows CI which uses vcpkg itself for pulling dependencies so it should be some issue from vcpkg side I guess.

**Comment by jasjuang** [comment]
The error should still be the same as #2276. I will double check again. However one thing I noticed in the harfbuzz Appveyor CI is that it only checks compilation on Visual Studio 2015 and not Visual Studio 2017. I am on Visual Studio 2017 and I am not sure if that's the reason compilation fails.

**Comment by jasjuang** [comment]
@ebraminio Just checked. It's the same error message as #2276.

**Comment by ebraminio** [comment]
Oh, on the newest change you are using the project source rather than a distribution and that needs "ragel" tool from vcpkg be installed (`vcpkg install ragel` I guess). So there it two solution for this, use distributions releases as the old versions, or add "ragel" to the dependencies of harfbuzz.

**Comment by jasjuang** [comment]
@ebraminio It is actually as simple as adding ragel as a dependency to solve this... I will submit a PR in a bit

**Comment by ebraminio** [comment]
> It is actually as simple as adding ragel as a dependency to solve this... I will submit a PR in a bit

I was also saying that :P That would be great, can you however test the build-ability of master also for me separately?

**Comment by jasjuang** [comment]
@ebraminio Current master compiles for me

**Comment by ebraminio** [comment]
Excellent :)
