### ISSUE TITLE
Issue about installing darknet in vcpkg

### ISSUE THREAD

**Issue by krkrman** [microsoft/vcpkg#24417]
**Host Environment**
- OS: Windows
- Compiler: revision

**To Reproduce**
`.\vcpkg install darknet[full]:x64-windows`

**Failure logs**
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:158 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j13
    Working Directory: C:/vcpckg/vcpkg/buildtrees/opencv4/x64-windows-dbg
    See logs for more information:
      C:\vcpckg\vcpkg\buildtrees\opencv4\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:111 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
  ports/opencv4/portfile.cmake:456 (vcpkg_cmake_install)
  scripts/ports.cmake:145 (include)
error: building opencv4:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.

**Additional context**
I tried git pull and .\cvpkg update and nothin happened

**Comment by Cheney-W** [comment]
Dup to https://github.com/microsoft/vcpkg/issues/16748
Maybe you could do as below:
1. Uninstall C:/Program Files/CMake/bin/cmake.exe
2. Run `git pull` in the vcpkg folder
3. .\bootstrap-vcpkg.bat
4. .\vcpkg install darknet[full]:x64-windows --binarysource=clear

**Comment by krkrman** [comment]
> 

Thanks, bro for your contribution
but after doing this still have the same problem
this is the whole error
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:158 (message):
    Command failed: C:/vcpckg/vcpkg/downloads/tools/cmake-3.22.2-windows/cmake-3.22.2-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j13
    Working Directory: C:/vcpckg/vcpkg/buildtrees/opencv4/x64-windows-dbg
    See logs for more information:
      C:\vcpckg\vcpkg\buildtrees\opencv4\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:111 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
  ports/opencv4/portfile.cmake:456 (vcpkg_cmake_install)
  scripts/ports.cmake:145 (include)


error: building opencv4:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+opencv4
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[opencv4]+Build+error
including:
  package: opencv4[contrib,core,cuda,default-features,dnn,ffmpeg,jpeg,png,quirc,tiff,webp]:x64-windows -> 4.5.5#3
    vcpkg-tool version: 2022-03-30-692785ac944e81417840c6de244fb3e18a4b35eb
    vcpkg-scripts version: 94c728df6 2022-04-25 (16 hours ago)
