### ISSUE TITLE
[colmap] Build error

### ISSUE THREAD

**Issue by Kimhoryong** [microsoft/vcpkg#24420]
**Host Environment**
- OS: Windows 10 Home
- Compiler:  Vcpkg package management program version 2022-03-30-692785ac944e81417840c6de244fb3e18a4b35eb

**To Reproduce**
'.\vcpkg.exe install colmap --triplet=x64-windows --head`

**Failure logs**
```
The following packages will be built and installed:
    colmap[core]:x64-windows -> 2022-03-14 (+HEAD)
Restored 0 packages from C:\Users\user\AppData\Local\vcpkg\archives in 118 us. Use --debug to see more details.
Starting package 1/1: colmap:x64-windows
Building package colmap[core]:x64-windows from HEAD...
-- Skipping hash check for C:/dev/vcpkg/downloads/colmap-colmap-dev.version.
-- Using cached colmap-colmap-dev.version.
-- Skipping hash check for C:/dev/vcpkg/downloads/colmap-colmap-c419bba98a8a987f61a363d6f542c3d050fb7743.tar.gz.
-- Using cached colmap-colmap-c419bba98a8a987f61a363d6f542c3d050fb7743.tar.gz.
-- Cleaning sources at C:/dev/vcpkg/buildtrees/colmap/src/head/d050fb7743-36abf1b6b1.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/dev/vcpkg/downloads/colmap-colmap-c419bba98a8a987f61a363d6f542c3d050fb7743.tar.gz
-- Applying patch fix-dependencies.patch
-- Using source at C:/dev/vcpkg/buildtrees/colmap/src/head/d050fb7743-36abf1b6b1.clean
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:158 (message):
    Command failed: C:/dev/vcpkg/downloads/tools/cmake-3.22.2-windows/cmake-3.22.2-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j17
    Working Directory: C:/dev/vcpkg/buildtrees/colmap/x64-windows-dbg
    See logs for more information:
      C:\dev\vcpkg\buildtrees\colmap\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:111 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
  ports/colmap/portfile.cmake:53 (vcpkg_cmake_install)
  scripts/ports.cmake:145 (include)
```
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/8560199/install-x64-windows-dbg-out.log)
[patch-x64-windows-0-err.log](https://github.com/microsoft/vcpkg/files/8560201/patch-x64-windows-0-err.log)

**Comment by Kimhoryong** [comment]
I tried to download pycolmap (https://github.com/colmap/pycolmap) but failed. I tried installing windows sdk or updating vcpkg but it didn't make the problem better.

**Comment by alexmargulis** [comment]
I also get FreeImage related errors when trying to build colmap on Windows 10
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/8598411/install-x64-windows-dbg-out.log)

**Comment by FischLu** [comment]
> 

I have the same error from FreeImage

**Comment by Adela0814** [comment]
This is a `glog `upstream bug.  please refer to: https://github.com/google/glog/issues/825

**Comment by zr19980402** [comment]
I have the same problem and  I CANNOT find any resolution. Have it been sovled?

**Comment by Adela0814** [comment]
> I have the same problem and I CANNOT find any resolution. Have it been sovled?

Not yet, I have found the reason and reported a bug to `glog`.

**Comment by Adela0814** [comment]
This is not an upstream bug, but a patch of vcpkg `glog `port.
@jiayuehua can you help to confirm why you add the patch `nogdi-nominmac.patch` #22135 
This macro(NOGDI) is not private to `glog `and affects sibling dependencies.

**Comment by zr19980402** [comment]
I have found another solution, dup to https://github.com/colmap/colmap/issues/1511
Maybe It will sovle your problem.

**Comment by Adela0814** [comment]
> I have found another solution, dup to [colmap/colmap#1511](https://github.com/colmap/colmap/issues/1511) Maybe It will sovle your problem.

yes, the same issue. PR #24538 fixed this.

**Comment by jiayuehua** [comment]
> @Adela0814 rsocket Use ERROR as enum Item , https://github.com/microsoft/vcpkg/pull/22135/commits/eb5f21325a7a14e0f9a9f8ba5764df4566ce1a98#diff-367f43f9cdddc022109aacebe93e0f2f51ba4776c2c1cb31971a7d276575e007 if not define NOGDI, rsocket can't compile successfully.
