### ISSUE TITLE
How to install static lib using manifests file

### ISSUE THREAD

**Issue by muziling** [microsoft/vcpkg#24423]
For example ,without manifests file, just run 
```
vcpkg install unicorn:x64-windows-static 
```

when using manifests file,  write  vcpkg.json:
```
{
    "name": "dbkg",
    "version-string": "1.0.0",
    "dependencies": [{
            "name": "unicorn",
            "platform": "static"
        }
    ],
    "builtin-baseline": "2ac61f87f69f0484b8044f95ab274038fbaf7bdd"
}
```
then run vcpkg install,   vcpkg do not perform install unicorn ,  seems be ignored

**Comment by autoantwort** [comment]
To install the static version, you have to run `vcpkg install --triplet=x64-windows-static `
