### ISSUE TITLE
[protobuf] build failure

### ISSUE THREAD

**Issue by alextsao1999** [microsoft/vcpkg#24429]
**Host Environment**
- OS: Windows
- Compiler: mingw

**To Reproduce**
`./vcpkg install protobuf:x86-mingw-static`

**Failure logs**
PS C:\Users\Alex\.vcpkg> vcpkg install protobuf:x86-mingw-static
Computing installation plan...
The following packages will be built and installed:
    protobuf[core]:x86-mingw-static -> 3.19.4
Detecting compiler hash for triplet x86-mingw-static...
-- Using HTTP(S)_PROXY in environment variables.
Restored 0 packages from C:\Users\Alex\AppData\Local\vcpkg\archives in 191.1 us. Use --debug to see more details.
Starting package 1/1: protobuf:x86-mingw-static
Building package protobuf[core]:x86-mingw-static...
-- Using community triplet x86-mingw-static. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: C:\Users\Alex\.vcpkg\triplets\community\x86-mingw-static.cmake
-- Using cached protocolbuffers-protobuf-v3.19.4.tar.gz.
-- Cleaning sources at C:/Users/Alex/.vcpkg/buildtrees/protobuf/src/v3.19.4-3d4c96d55c.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/Alex/.vcpkg/downloads/protocolbuffers-protobuf-v3.19.4.tar.gz
-- Applying patch fix-static-build.patch
-- Applying patch fix-default-proto-file-path.patch
-- Using source at C:/Users/Alex/.vcpkg/buildtrees/protobuf/src/v3.19.4-3d4c96d55c.clean
-- Found external ninja('1.10.2').
-- Configuring x86-mingw-static
-- Building x86-mingw-static-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:158 (message):
    Command failed: C:/Users/Alex/.vcpkg/downloads/tools/cmake-3.22.2-windows/cmake-3.22.2-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j17
    Working Directory: C:/Users/Alex/.vcpkg/buildtrees/protobuf/x86-mingw-static-dbg
    See logs for more information:
      C:\Users\Alex\.vcpkg\buildtrees\protobuf\install-x86-mingw-static-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:111 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
  ports/protobuf/portfile.cmake:45 (vcpkg_cmake_install)
  scripts/ports.cmake:145 (include)

error: building protobuf:x86-mingw-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+protobuf
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[protobuf]+Build+error
including:
  package: protobuf[core]:x86-mingw-static -> 3.19.4
    vcpkg-tool version: 2022-03-30-692785ac944e81417840c6de244fb3e18a4b35eb
    vcpkg-scripts version: 94c728df6 2022-04-25 (16 hours ago)

Additionally, attach any relevant sections from the log files above.

**Comment by LilyWangLL** [comment]
This issue hasn’t been updated in 3 months, if it is still an issue, please reopen this issue.
