### ISSUE TITLE
How to install a package globally (for all users)

### ISSUE THREAD

**Issue by AdelCraftZ** [microsoft/vcpkg#24446]
Is there a way to perform a system-wide package installation using vcpkg?

**Comment by JackBoosY** [comment]
Can you give an example of the scenario you need?

**Comment by Adela0814** [comment]
@AdelCraftZ ping for response.

**Comment by Adela0814** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
