### ISSUE TITLE
[libharu] Build error when using dynamic lib triplet on Linux

### ISSUE THREAD

**Issue by pionex** [microsoft/vcpkg#24441]
**Host Environment**
- OS: Ubuntu 22.04
- Compiler: revision

**To Reproduce**
Use dynamic lib triplet on Linux x64
`./vcpkg install libharu`

**Failure logs**
In file included from /home/perception/VagrantProjects/vcpkg/buildtrees/vtk/x64-linux-dbg/ThirdParty/libharu/vtk_libharu.h:24,
                 from /home/perception/VagrantProjects/vcpkg/buildtrees/vtk/src/edd2e5233f-2ed574e023.clean/IO/ExportPDF/vtkPDFContextDevice2D.cxx:47:
/home/perception/VagrantProjects/vcpkg/installed/x64-linux/include/hpdf.h:100:1: error: expected constructor, destructor, or type conversion before ‘(’ token
  100 | HPDF_EXPORT(const char *)
      | ^~~~~~~~~~~
/home/perception/VagrantProjects/vcpkg/installed/x64-linux/include/hpdf.h:104:1: error: expected constructor, destructor, or type conversion before ‘(’ token
  104 | HPDF_EXPORT(HPDF_Doc)
      | ^~~~~~~~~~~

...

**Additional context**
The portfile has the following code that modifies the hpdf.h and hpdf_types.h to include __stdcall in the HPDF_EXPORT and HPDF_STDCALL macros.  This does not work on Linux / GCC.  The portfile should check not only for dynamic build but also the OS before making that change.

**Comment by Cheney-W** [comment]
I can't reproduce this issue in my side with latest vcpkg version 2022-06-17-9268e366206712e38102b28dbd1617697a99ff2e
I used x64-linux-dynamic.cmake as below:
```
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)

set(VCPKG_CMAKE_SYSTEM_NAME Linux)
```

**Comment by dg0yt** [comment]
> **Failure logs**
> In file included from /home/perception/VagrantProjects/vcpkg/buildtrees/vtk/x64-linux-dbg/ThirdParty/libharu/vtk_libharu.h:24,

AFAIU you are building vtk here. `./vcpkg install libharu` won't reproduce the issue.
vcpkg tool prints the information for issues to the console. Why not shared it here? Maybe it is all outdated...

**Comment by LilyWangLL** [comment]
This issue hasn’t been updated in 3 months, if it is still an issue, please reopen this issue.
