### ISSUE TITLE
[boost-math] build failure: One or more PCH files were found, but they were invalid

### ISSUE THREAD

**Issue by guotaiyu** [microsoft/vcpkg#24457]
**Host Environment**
- OS: AlmaLinux v8.5
- Compiler: gcc 8.5.0

**To Reproduce**
`./vcpkg install boost` or `./vcpkg install boost-math`

**Failure logs**
Last page in `install-x64-linux-dbg-out.log`: 
![IMG_8924](https://user-images.githubusercontent.com/15621867/165667308-b9addb3c-6441-4f57-a3fc-2e5d5b03544c.jpg)

**Additional context**
Related/similar to [Issue 22553](https://github.com/microsoft/vcpkg/issues/22553), which is already closed.

**Comment by guotaiyu** [comment]
Tested on Centos 7 too and had the same issue

**Comment by Adela0814** [comment]
thanks for sharing the case and workaround which may help other user.
