### ISSUE TITLE
[python3] Build error

### ISSUE THREAD

**Issue by kael0930** [microsoft/vcpkg#24458]
**Host Environment**
- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**
`./vcpkg install xxxx`

**Failure logs**
-Cut and paste the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by FrankXie05** [comment]
@kael0930 Thanks for posting this issue, could you please provide the error log？

**Comment by FrankXie05** [comment]
@kael0930  does the issue still occur?

**Comment by FrankXie05** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
