### ISSUE TITLE
[boost-regex] Build error

### ISSUE THREAD

**Issue by lowerfain** [microsoft/vcpkg#24473]
**Host Environment**
- OS: [e.g. Windows/Linux etc...]win10
- Compiler: revision :  visual studio2022

**To Reproduce**
`vcpkg install boost-regex[core]:x64-windows`

**Failure logs**
```
Computing installation plan...
The following packages will be built and installed:
    boost-regex[core]:x64-windows -> 1.78.0
Detecting compiler hash for triplet x64-windows...
-- Automatically setting HTTP(S)_PROXY environment variables to 127.0.0.1:15732
Restored 0 packages from C:\Users\彗核\AppData\Local\vcpkg\archives in 148.4 us. Use --debug to see more details.
Starting package 1/1: boost-regex:x64-windows
Building package boost-regex[core]:x64-windows...
-- Using cached boostorg-regex-boost-1.78.0.tar.gz.
-- Cleaning sources at C:/dev/vcpkg/buildtrees/boost-regex/src/ost-1.78.0-c212e9f671.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/dev/vcpkg/downloads/boostorg-regex-boost-1.78.0.tar.gz
-- Using source at C:/dev/vcpkg/buildtrees/boost-regex/src/ost-1.78.0-c212e9f671.clean
-- Including C:/dev/vcpkg/ports/boost-regex/b2-options.cmake
-- Found external ninja('1.10.2').
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:158 (message):
    Command failed: D:/Software/CMake/bin/cmake.exe --build . --config Debug --target install -- -v -j17
    Working Directory: C:/dev/vcpkg/buildtrees/boost-regex/x64-windows-dbg
    See logs for more information:
      C:\dev\vcpkg\buildtrees\boost-regex\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:111 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
  installed/x64-windows/share/boost-build/boost-modular-build.cmake:124 (vcpkg_cmake_install)
  ports/boost-regex/portfile.cmake:15 (boost_modular_build)
  scripts/ports.cmake:145 (include)


Error: Building package boost-regex:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-regex
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[boost-regex]+Build+error
including:
  package: boost-regex[core]:x64-windows -> 1.78.0
    vcpkg-tool version: 2022-02-11-dac008bf9b55ef48e10bcc81e273b97a82bbf72d
    vcpkg-scripts version: unknown

Additionally, attach any relevant sections from the log files above.
```
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/8589180/install-x64-windows-dbg-out.log)

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by yurybura** [comment]
@lowerfain Actual Boost version is 1.79.0. Could you update and try again?

**Comment by lowerfain** [comment]
> @lowerfain Actual Boost version is 1.79.0. Could you update and try again?

After I updated vcpkg, I used the command 'vcpkg install boost:x64-windows'. The following error occurs:
Computing installation plan...
The following packages will be built and installed:
    boost[core]:x64-windows -> 1.79.0
  * boost-accumulators[core]:x64-windows -> 1.79.0
  * boost-algorithm[core]:x64-windows -> 1.79.0
  * boost-align[core]:x64-windows -> 1.79.0
  * boost-any[core]:x64-windows -> 1.79.0
  * boost-asio[core]:x64-windows -> 1.79.0
  * boost-assign[core]:x64-windows -> 1.79.0
  * boost-atomic[core]:x64-windows -> 1.79.0
  * boost-beast[core]:x64-windows -> 1.79.0
  * boost-bimap[core]:x64-windows -> 1.79.0
  * boost-callable-traits[core]:x64-windows -> 1.79.0
  * boost-chrono[core]:x64-windows -> 1.79.0
  * boost-compatibility[core]:x64-windows -> 1.79.0
  * boost-compute[core]:x64-windows -> 1.79.0
  * boost-container[core]:x64-windows -> 1.79.0
  * boost-context[core]:x64-windows -> 1.79.0
  * boost-contract[core]:x64-windows -> 1.79.0
  * boost-convert[core]:x64-windows -> 1.79.0
  * boost-coroutine[core]:x64-windows -> 1.79.0
  * boost-coroutine2[core]:x64-windows -> 1.79.0
  * boost-crc[core]:x64-windows -> 1.79.0
  * boost-date-time[core]:x64-windows -> 1.79.0
  * boost-describe[core]:x64-windows -> 1.79.0
  * boost-dll[core]:x64-windows -> 1.79.0
  * boost-dynamic-bitset[core]:x64-windows -> 1.79.0
  * boost-endian[core]:x64-windows -> 1.79.0
  * boost-exception[core]:x64-windows -> 1.79.0
  * boost-fiber[core]:x64-windows -> 1.79.0
  * boost-filesystem[core]:x64-windows -> 1.79.0
  * boost-flyweight[core]:x64-windows -> 1.79.0
  * boost-foreach[core]:x64-windows -> 1.79.0
  * boost-format[core]:x64-windows -> 1.79.0
  * boost-functional[core]:x64-windows -> 1.79.0
  * boost-geometry[core]:x64-windows -> 1.79.0
  * boost-gil[core]:x64-windows -> 1.79.0
  * boost-graph[core]:x64-windows -> 1.79.0
  * boost-hana[core]:x64-windows -> 1.79.0
  * boost-heap[core]:x64-windows -> 1.79.0
  * boost-histogram[core]:x64-windows -> 1.79.0
  * boost-hof[core]:x64-windows -> 1.79.0
  * boost-icl[core]:x64-windows -> 1.79.0
  * boost-interprocess[core]:x64-windows -> 1.79.0
  * boost-interval[core]:x64-windows -> 1.79.0
  * boost-intrusive[core]:x64-windows -> 1.79.0
  * boost-iostreams[bzip2,core,lzma,zlib,zstd]:x64-windows -> 1.79.0
  * boost-json[core]:x64-windows -> 1.79.0
  * boost-lambda[core]:x64-windows -> 1.79.0
  * boost-lambda2[core]:x64-windows -> 1.79.0
  * boost-leaf[core]:x64-windows -> 1.79.0
  * boost-lexical-cast[core]:x64-windows -> 1.79.0
  * boost-local-function[core]:x64-windows -> 1.79.0
  * boost-locale[core]:x64-windows -> 1.79.0
  * boost-lockfree[core]:x64-windows -> 1.79.0
  * boost-log[core]:x64-windows -> 1.79.0
  * boost-logic[core]:x64-windows -> 1.79.0
  * boost-math[core]:x64-windows -> 1.79.0
  * boost-metaparse[core]:x64-windows -> 1.79.0
  * boost-msm[core]:x64-windows -> 1.79.0
  * boost-multi-array[core]:x64-windows -> 1.79.0
  * boost-multi-index[core]:x64-windows -> 1.79.0
  * boost-multiprecision[core]:x64-windows -> 1.79.0
  * boost-nowide[core]:x64-windows -> 1.79.0
  * boost-odeint[core]:x64-windows -> 1.79.0
  * boost-outcome[core]:x64-windows -> 1.79.0
  * boost-parameter-python[core]:x64-windows -> 1.79.0
  * boost-pfr[core]:x64-windows -> 1.79.0
  * boost-phoenix[core]:x64-windows -> 1.79.0
  * boost-poly-collection[core]:x64-windows -> 1.79.0
  * boost-polygon[core]:x64-windows -> 1.79.0
  * boost-pool[core]:x64-windows -> 1.79.0
  * boost-process[core]:x64-windows -> 1.79.0
  * boost-program-options[core]:x64-windows -> 1.79.0
  * boost-property-map[core]:x64-windows -> 1.79.0
  * boost-property-tree[core]:x64-windows -> 1.79.0
  * boost-proto[core]:x64-windows -> 1.79.0
  * boost-ptr-container[core]:x64-windows -> 1.79.0
  * boost-python[core,python3]:x64-windows -> 1.79.0
  * boost-qvm[core]:x64-windows -> 1.79.0
  * boost-random[core]:x64-windows -> 1.79.0
  * boost-range[core]:x64-windows -> 1.79.0
  * boost-ratio[core]:x64-windows -> 1.79.0
  * boost-rational[core]:x64-windows -> 1.79.0
  * boost-regex[core]:x64-windows -> 1.79.0
  * boost-safe-numerics[core]:x64-windows -> 1.79.0
  * boost-scope-exit[core]:x64-windows -> 1.79.0
  * boost-serialization[core]:x64-windows -> 1.79.0
  * boost-signals2[core]:x64-windows -> 1.79.0
  * boost-sort[core]:x64-windows -> 1.79.0
  * boost-spirit[core]:x64-windows -> 1.79.0
  * boost-stacktrace[core]:x64-windows -> 1.79.0
  * boost-statechart[core]:x64-windows -> 1.79.0
  * boost-static-string[core]:x64-windows -> 1.79.0
  * boost-stl-interfaces[core]:x64-windows -> 1.79.0
  * boost-system[core]:x64-windows -> 1.79.0
  * boost-test[core]:x64-windows -> 1.79.0
  * boost-thread[core]:x64-windows -> 1.79.0
  * boost-timer[core]:x64-windows -> 1.79.0
  * boost-tokenizer[core]:x64-windows -> 1.79.0
  * boost-tti[core]:x64-windows -> 1.79.0
  * boost-type-erasure[core]:x64-windows -> 1.79.0
  * boost-ublas[core]:x64-windows -> 1.79.0
  * boost-units[core]:x64-windows -> 1.79.0
  * boost-unordered[core]:x64-windows -> 1.79.0
  * boost-uuid[core]:x64-windows -> 1.79.0
  * boost-variant[core]:x64-windows -> 1.79.0
  * boost-variant2[core]:x64-windows -> 1.79.0
  * boost-vmd[core]:x64-windows -> 1.79.0
  * boost-wave[core]:x64-windows -> 1.79.0
  * boost-xpressive[core]:x64-windows -> 1.79.0
  * boost-yap[core]:x64-windows -> 1.79.0
  * bzip2[core]:x64-windows -> 1.0.8#2
  * expat[core]:x64-windows -> 2.4.8#1
  * libffi[core]:x64-windows -> 3.4.2#4
  * liblzma[core]:x64-windows -> 5.2.5#5
  * openssl[core]:x64-windows -> 3.0.2#3
  * python3[core]:x64-windows -> 3.10.2#1
  * sqlite3[core]:x64-windows -> 3.37.2#1
  * vcpkg-cmake-config[core]:x64-windows -> 2022-02-06
  * zlib[core]:x64-windows -> 1.2.12
  * zstd[core]:x64-windows -> 1.5.2#1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
-- Automatically setting HTTP(S)_PROXY environment variables to 127.0.0.1:15732
Restored 0 packages from C:\Users\彗核\AppData\Local\vcpkg\archives in 3.37 ms. Use --debug to see more details.
Starting package 1/120: boost-regex:x64-windows
Building package boost-regex[core]:x64-windows...
-- Using cached boostorg-regex-boost-1.79.0.tar.gz.
-- Cleaning sources at D:/vcpkg/vcpkg/buildtrees/boost-regex/src/ost-1.79.0-42753a2328.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/vcpkg/vcpkg/downloads/boostorg-regex-boost-1.79.0.tar.gz
-- Using source at D:/vcpkg/vcpkg/buildtrees/boost-regex/src/ost-1.79.0-42753a2328.clean
-- Including D:/vcpkg/vcpkg/ports/boost-regex/b2-options.cmake
-- Found external ninja('1.10.2').
-- Getting CMake variables for x64-windows
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:158 (message):
    Command failed: D:/vcpkg/vcpkg/downloads/tools/cmake-3.22.2-windows/cmake-3.22.2-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j17
    Working Directory: D:/vcpkg/vcpkg/buildtrees/boost-regex/x64-windows-dbg
    See logs for more information:
      D:\vcpkg\vcpkg\buildtrees\boost-regex\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:111 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
  installed/x64-windows/share/boost-build/boost-modular-build.cmake:135 (vcpkg_cmake_install)
  ports/boost-regex/portfile.cmake:12 (boost_modular_build)
  scripts/ports.cmake:145 (include)


error: building boost-regex:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-regex
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[boost-regex]+Build+error
including:
  package: boost-regex[core]:x64-windows -> 1.79.0
    vcpkg-tool version: 2022-03-30-692785ac944e81417840c6de244fb3e18a4b35eb
    vcpkg-scripts version: 2ece8fedb 2022-04-29 (6 hours ago)

Additionally, attach any relevant sections from the log files above.

Logs:
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/8595508/install-x64-windows-dbg-out.log)

**Comment by JackBoosY** [comment]
Can you please remove `boost-uninstall` then try again?

Thanks.

**Comment by lowerfain** [comment]
> 可以请您删除`boost-uninstall`然后重试吗？
> 
> 谢谢。
Thanks for your suggestion, I use `vcpkg remove boost-uninstall:x64-windows --recurse` and then `vcpkg install boost:x64-windows`. But the error still occurs. Do you have any other solutions? The log file is as follows:
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/8644192/install-x64-windows-dbg-out.log)

**Comment by lowerfain** [comment]
> 可以请您删除`boost-uninstall`然后重试吗？
> 
> 谢谢。

Thanks for your suggestion, I use `vcpkg remove boost-uninstall:x64-windows --recurse` and then `vcpkg install boost:x64-windows`. But the error still occurs. Do you have any other solutions? The log file is as follows:
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/8644197/install-x64-windows-dbg-out.log)

**Comment by 2a3b4c** [comment]
I also met this problem at the error line: 158, and my OS: win8, compiler: VS code 2019.
Here is my error log
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/8748692/install-x64-windows-dbg-out.log)
.

**Comment by JackBoosY** [comment]
_C:\Users\彗核_
boost uses `%temp%` as a temporary folder to store temporary files such as scripts, but boost has bug with non-ascii characters.
This issue is caused by Windows usernames containing non-ASCII characters.

**Comment by JackBoosY** [comment]
Related issue: https://github.com/microsoft/vcpkg/issues/15201

**Comment by lowerfain** [comment]
> _C:\Users\彗核_ boost uses `%temp%` as a temporary folder to store temporary files such as scripts, but boost has bug with non-ascii characters. This issue is caused by Windows usernames containing non-ASCII characters.

I think it should be, I've had a similar situation before. Finally, thank you very much for your answer!
