### ISSUE TITLE
[FlatBuffers] Add BuildFlatBuffers.cmake to the distribution

### ISSUE THREAD

**Issue by r4nx** [microsoft/vcpkg#24484]
****

**Is your feature request related to a problem? Please describe.**
Unable to compile .fbs files from CMake when using FlatBuffers via vcpkg, as necessary convenience functions are in [BuildFlatBuffers.cmake](https://github.com/google/flatbuffers/blob/master/CMake/BuildFlatBuffers.cmake), which isn't included to the port distribution.

**Proposed solution**
Add BuildFlatBuffers.cmake to port distribution

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by Adela0814** [comment]
`BuildFlatBuffers.cmake` has been parsed when configuring. I'd like to confirm your request, could you please share your usage scenarios and reproduction steps?

**Comment by Adela0814** [comment]
@r4nx ping~

**Comment by Adela0814** [comment]
`BuildFlatBuffers.cmake` is a private file of `flatbutters`, it has not been installed, and [include(CMake/BuildFlatBuffers.cmake](https://github.com/google/flatbuffers/blob/9d45a640363a49e701e5bf7c04c740ef4edaa3c0/CMakeLists.txt#:~:text=include(CMake/BuildFlatBuffers.cmake)) has been called in `CMakeLists `in the source code, so I want to confirm if it is necessary for you to use this here,

**Comment by r4nx** [comment]
This is, as far as I know, the only method to compile the FlatBuffers schemas from CMake (i.e. without inventing your own function that will call `flatc`), thus I think we should have it in the distribution - it's directly impacting the library usage.

Also, a talk with  FlatBuffers maintainer:
![image](https://user-images.githubusercontent.com/30746510/169490015-40125241-862c-4354-a693-562908d828c2.png)

**Comment by dg0yt** [comment]
If upstream thinks that `BuildFlatBuffers.cmake` should be used in downstream projects (i.e. is public API), then it would be upstream's task to add a proper install command (and integrate with the exported CMake config, and add documentation).

**Comment by Adela0814** [comment]
@r4nx any process? Have you submitted an issue upstream?

**Comment by dbaileychess** [comment]
@dg0yt Maintainer of upstream project here, but I wasn't responsible for vcpkg integration. What needs to be done here?

**Comment by r4nx** [comment]
@Adela0814 ping

**Comment by Adela0814** [comment]
Sorry for the delay. @dbaileychess  You need to add the install command to the `CMakeLists.txt` to install `BuildFlatBuffers.cmake`.

**Comment by Adela0814** [comment]
Fixed by: https://github.com/microsoft/vcpkg/pull/27298
