### ISSUE TITLE
[New Port Request] YaaZ/VulkanMemoryAllocator-Hpp

### ISSUE THREAD

**Issue by rHermes** [microsoft/vcpkg#24482]
Library name: YaaZ/VulkanMemoryAllocator-Hpp

Library description:  C++ bindings for VulkanMemoryAllocator 

Source repository URL: https://github.com/YaaZ/VulkanMemoryAllocator-Hpp

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
