### ISSUE TITLE
[wxwidgets] vcpkg-cmake-wrapper.cmake causes failure to link debug libraries if project is reconfigured

### ISSUE THREAD

**Issue by marekr** [microsoft/vcpkg#24489]
So this is bug in `vcpkg-cmake-wrapper.cmake` that was introduced in vcpkg

in Findwxwidgets.cmake
```
        if(WX_${wxWidgets_CONFIGURATION}d_FOUND)
          option(wxWidgets_USE_REL_AND_DBG
            "Use release and debug configurations?" TRUE)
          set(WX_USE_REL_AND_DBG ${wxWidgets_USE_REL_AND_DBG})
        else()
          # If the option exists (already in cache), force it false.
          if(wxWidgets_USE_REL_AND_DBG)
            set(wxWidgets_USE_REL_AND_DBG FALSE CACHE BOOL
              "No ${wxWidgets_CONFIGURATION}d found." FORCE)
          endif()
          set(WX_USE_REL_AND_DBG FALSE)
        endif()
```

1st time cache
- vcpkg-cmake-wrapper.cmakeinvokves
-- Debug libs, wxWidgets_USE_REL_AND_DBG is not set, nothing happens
-- Release libs, wxWidgets_USE_REL_AND_DBG is set true by the first if statement.
-- Debug libs get selected for a debug build because wxWidgets_USE_REL_AND_DBG is true at the end of findwxwidgets.cmake

2nd time reconfigured
- wrapper invokes
-- Debug libs, wxWidgets_USE_REL_AND_DBG  is forced to false because it is currently true and the vcpkg cmake wrapper called findwxwidgets forcefully with the debug lib path only
-- Release libs, wxWidgets_USE_REL_AND_DBG  remains off because it is set in the cache and the option does not override it
-- debug libs are never selected

This bug isn't caught by CI due to the reconfiguration requirement.

**Comment by dg0yt** [comment]
Reproduced in CI with #24499.

**Comment by marekr** [comment]
This is now fixed by the merged PR
