### ISSUE TITLE
[vcpkg-tool-[coscli]] incorrect hash in vcpkgTools.xml

### ISSUE THREAD

**Issue by PavelCurtis** [microsoft/vcpkg#24492]
**Describe the bug**
The Windows version of the "coscli" tool is listed in "vcpkgTools.xml" with an incorrect hash code.  Any attempt to download this tool for Windows will therefore fail.

**Environment**
- OS: Windows

**To Reproduce**
I don't know when this tool will be reqiured.

**Comment by FrankXie05** [comment]
@PavelCurtis Thanks for posting this issue. Yes, now the hash is wrong. Maybe upstream made a change. I'll update it.
This problem was caused by not adding the `coscli` test. 
About what coscli is, you can refer to https://github.com/microsoft/vcpkg-tool/pull/476
