### ISSUE TITLE
[New Port Request] NTL

### ISSUE THREAD

**Issue by hros** [microsoft/vcpkg#24501]
Library name: NTL

Library description: A Library for doing Number Theory

Source repository URL: https://github.com/libntl/ntl

Project homepage (if different from the source repository): https://libntl.org/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
