### ISSUE TITLE
[mpfr] Build error

### ISSUE THREAD

**Issue by hros** [microsoft/vcpkg#24500]
**Host Environment**
- OS: Windows 11, WSL2, Ubuntu 22.04
- Compiler: g++ 11.2.0-19

**To Reproduce**
`./vcpkg install mpfr`

**Failure logs**
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:128 (message):
    Command failed: /usr/bin/autoreconf -vfi
    Working Directory: /home/user/.local/vcpkg/buildtrees/mpfr/src/mpfr-4-2533b4c96d.clean/
    Error code: 1
    See logs for more information:
      /home/user/.local/vcpkg/buildtrees/mpfr/autoconf-x64-linux-out.log
      /home/user/.local/vcpkg/buildtrees/mpfr/autoconf-x64-linux-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:633 (vcpkg_execute_required_process)
  ports/mpfr/portfile.cmake:21 (vcpkg_configure_make)
  scripts/ports.cmake:145 (include)

error: building mpfr:x64-linux failed with: BUILD_FAILED

package: mpfr[core]:x64-linux -> 4.1.0#4
    vcpkg-tool version: 2022-03-30-692785ac944e81417840c6de244fb3e18a4b35eb
    vcpkg-scripts version: c8a56fdc1 2022-04-29 (2 days ago)

**Additional context**
initially tried to install `flint` library (using `vcpkg install flint`) but got errors regarding mpfr.
then, tried to build `mpfr` directly, but got the same errors
naturally, I tried `git pull` / `vcpkg update` but everything is UpToDate

**Comment by JonLiu1993** [comment]
@hros ,Thanks for posting this issue, could you please provide the error log:
````
/home/user/.local/vcpkg/buildtrees/mpfr/autoconf-x64-linux-out.log
/home/user/.local/vcpkg/buildtrees/mpfr/autoconf-x64-linux-err.log
````

**Comment by hros** [comment]
@JonLiu1993, here are the logs

output of `autoconf-x64-linux-out.log`:
```
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
```

output of `autoconf-x64-linux-err.log`:
```
autoreconf: export WARNINGS=
autoreconf: Entering directory '.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
aclocal: warning: couldn't open directory 'm4': No such file or directory
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
autoreconf: configure.ac: not using Intltool
autoreconf: configure.ac: not using Gtkdoc
autoreconf: running: aclocal --force -I m4
autoreconf: running: /usr/bin/autoconf --force
configure.ac:550: warning: The macro `AC_HEADER_TIME' is obsolete.
configure.ac:550: You should run autoupdate.
./lib/autoconf/headers.m4:743: AC_HEADER_TIME is expanded from...
acinclude.m4:38: MPFR_CONFIGS is expanded from...
configure.ac:550: the top level
configure:15086: error: possibly undefined macro: AX_PTHREAD
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: error: /usr/bin/autoconf failed with exit status: 1
```

**Comment by JonLiu1993** [comment]
@hros I reproduced your issue locally, when I installed the autoconf-archive package according to the command prompt, the problem was solved, and mpfr could be installed successfully
````
CMake Warning at ports/mpfr/portfile.cmake:2 (message):
  mpfr currently requires the following packages:

      autoconf-archive

  These can be installed on Ubuntu systems via

      sudo apt-get update -y
      sudo apt-get install -y autoconf-archive

````

````
vzhli17@vzhli17001:~/vcpkg$ ./vcpkg install mpfr --editable
Computing installation plan...
The following packages are already installed:
    mpfr[core]:x64-linux -> 4.1.0#4
Package mpfr:x64-linux is already installed
Restored 0 packages from /home/vzhli17/.cache/vcpkg/archives in 3.8 us. Use --debug to see more details.

Total elapsed time: 24.59 ms

````

**Comment by hros** [comment]
thanks @JonLiu1993 
after installing `autoconf-archive` the packages in question (`flint` and its dependency `mpfr`) installed successfully

it would be helpful if `vcpkg` displayed (hopefully, higlighting) the `cmake` warning regarding the missing packages

**Comment by JonLiu1993** [comment]
> thanks @JonLiu1993 after installing `autoconf-archive` the packages in question (`flint` and its dependency `mpfr`) installed successfully
> 
> it would be helpful if `vcpkg` displayed (hopefully, higlighting) the `cmake` warning regarding the missing packages

@hros ,Currently we have a warning about installing under linux:
````
if (VCPKG_TARGET_IS_LINUX)
     message(WARNING "${PORT} currently requires the following packages:\n autoconf-archive\nThese can be installed on Ubuntu systems via\n sudo apt-get update -y\n sudo apt-get install -y autoconf-archive\ n")
endif()
````
In general, if you encounter errors involving the autoconf-archive package, you can try to install autoconf-archive to solve them
