### ISSUE TITLE
What's the diff for `VCPKG_DEFAULT_HOST_TRIPLET` and `VCPKG_DEFAULT_TRIPLET`?

### ISSUE THREAD

**Issue by playgithub** [microsoft/vcpkg#24504]
At https://vcpkg.io/en/docs/users/triplets.html, nothing about `VCPKG_DEFAULT_HOST_TRIPLET`.

**Comment by dg0yt** [comment]
(Please ask questions in "Discussions".)

These are environment variables, documented in [Environment and Configuraion](https://vcpkg.io/en/docs/users/config-environment.html#vcpkg_default_triplet), not CMake toolchain variables.

**Comment by playgithub** [comment]
OK, the entry in `Issues` is a little misleading
![image](https://user-images.githubusercontent.com/3665590/166207415-2a6be65c-d20c-4751-98af-91164c48dd0b.png)
