### ISSUE TITLE
[colmap] Build error

### ISSUE THREAD

**Issue by Hyunkil76** [microsoft/vcpkg#24520]
**Host Environment**
- OS: Windows_64x
- Compiler: MSVC19
**To Reproduce**
.\vcpkg install colmap[cuda,tests]:x64-windows

**Failure logs**
Computing installation plan...
The following packages will be built and installed:
    colmap[core,cuda,tests]:x64-windows -> 2022-03-14
Detecting compiler hash for triplet x64-windows...
Restored 0 packages from C:\Users\Hyunkil\AppData\Local\vcpkg\archives in 256.1 us. Use --debug to see more details.
Starting package 1/1: colmap:x64-windows
Building package colmap[core,cuda,tests]:x64-windows...
-- Using cached colmap-colmap-29a1e3642a3b00734a52b21e597ea4d576485fe6.tar.gz.
-- Cleaning sources at C:/src/vcpkg/buildtrees/colmap/src/d576485fe6-7dd36362d1.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/src/vcpkg/downloads/colmap-colmap-29a1e3642a3b00734a52b21e597ea4d576485fe6.tar.gz
-- Applying patch fix-dependencies.patch
-- Using source at C:/src/vcpkg/buildtrees/colmap/src/d576485fe6-7dd36362d1.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:158 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j17
    Working Directory: C:/src/vcpkg/buildtrees/colmap/x64-windows-dbg
    See logs for more information:
      C:\src\vcpkg\buildtrees\colmap\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:111 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
  ports/colmap/portfile.cmake:53 (vcpkg_cmake_install)
  scripts/ports.cmake:145 (include)

error: building colmap:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+colmap
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[colmap]+Build+error
including:
  package: colmap[core,cuda,tests]:x64-windows -> 2022-03-14
    vcpkg-tool version: 2022-03-30-692785ac944e81417840c6de244fb3e18a4b35eb
    vcpkg-scripts version: b98afc9f1 2022-05-02 (10 hours ago)

Additionally, attach any relevant sections from the log files above.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/8610857/install-x64-windows-dbg-out.log)

**Comment by ZZWang21** [comment]
same problem here. Any solutions?

**Comment by Cheney-W** [comment]
Dup to https://github.com/microsoft/vcpkg/issues/24420.
