### ISSUE TITLE
[usd] Build Failure on Windows

### ISSUE THREAD

**Issue by cgurps** [microsoft/vcpkg#24536]
**Host Environment**
- OS: Windows
- Compiler: VS 2019 / VS 2022
- vcpkg version 2022.04.12

Good afternoon,

I'm currently working on an USD 22.05 port. The port works fine on Linux and macOS (x86/arm64), but I'm having a weird `CMake` bug. More precisely, in debug, `CMake` is generating a `cmake_install.cmake` that contains a typo:
```cmake
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "C:/Users/***/git/vcpkg/packages/usd_x64-windows/debug"")
endif()
```
which is the extraneous `"` at the end of `set`. Did you ever encounter this error? Note that the release counterpart of that file is correctly generated:
```cmake
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "C:/Users/***/git/vcpkg/packages/usd_x64-windows")
endif()
```

**Comment by dg0yt** [comment]
> ```cmake
>  -DPYTHON_EXECUTABLE="${Python3_EXECUTABLE}"
> ```

This is not portable. You must quote the entire cmake expression:
~~~cmake
  "-DPYTHON_EXECUTABLE=${Python3_EXECUTABLE}"
~~~

And this is also which breaks your build, with `Python3_EXECUTABLE` being empty:

~~~
..L=ON" "-DPYTHON_EXECUTABLE=""" "-DPXR...
~~~

**Comment by cgurps** [comment]
That was indeed the problem! Thanks a lot.
