### ISSUE TITLE
Running bootstrap-vcpkg.bat results in 4536 errors

### ISSUE THREAD

**Issue by tontinton** [Microsoft/vcpkg#2453]
<h2>The final output is:</h2>

<pre class="source">
Time Elapsed 00:00:09.30
C:\vcpkg\scripts\bootstrap.ps1 : Building vcpkg.exe failed. Please ensure you have installed Visual Studio with the
Desktop C++ workload and the Windows SDK for Desktop C++.
At line:1 char:4
+ & {& 'C:\vcpkg\scripts\bootstrap.ps1'}
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,bootstrap.ps1
</pre>

Even though i have everything installed.

**Comment by UnaNancyOwen** [comment]
Did you install Visual C++?
In general, It needs to choose the "Desktop development with C++" workload and "Windows 10 SDK (10.0.XXXXX.0) for Desktop C++ [x86 and x64]" (or Windows SDK for your required targets)  in Visual Studio Installer. (It is not default selected.)

**Comment by ras0219-msft** [comment]
Thanks for reporting this issue!

Could you attach the results of running:
```
>powershell -exec bypass .\scripts\findAnyMSBuildWithCppPlatformToolset.ps1 -verbose
>powershell -exec bypass .\scripts\getWindowsSDK.ps1 -verbose
```

**Comment by bitsrules** [comment]
c:\vcpkg>powershell -exec bypass .\scripts\findAnyMSBuildWithCppPlatformToolset.ps1 -verbose
.\scripts\findAnyMSBuildWithCppPlatformToolset.ps1 : The term '.\scripts\findAnyMSBuildWithCppPlatformToolset.ps1' is
not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or
if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ .\scripts\findAnyMSBuildWithCppPlatformToolset.ps1 -verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\scripts\findA...formToolset.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by ras0219-msft** [comment]
@bitsrules Thanks for trying to run the scripts, however since this issue was originally posted they have been refactored out.

If you're having issues with boostrap, could you please open a new issue with any relevant error information (especially any compiler messages)?
