### ISSUE TITLE
How to ignore transient dependencies?

### ISSUE THREAD

**Issue by JulZimmermann** [microsoft/vcpkg#24558]
Hello,

I want to use vcpkg in my multi-platform project. I want to use it for all my libraries on a windows system, but for Linux, I'd like to use the system package manager for "big" libraries like Boost or OpenSSL, and use vcpkg only for smaller (header only, or statically linked) libraries.

I understand, that it is possible to achieve this with the `platform` field of the dependencies in the `vcpkg.json` manifest file. I can do something like this: 
```
"dependencies": [
  {
    "name": "openssl",
    "platform": "!linux"
  }
]
```

This works well. However, if I add the (small) dependency `cpp-jwt` To my project, `openssl` will get installed anyway, because it is now a transient dependency. Is there some way to prevent `openssl` from getting installed, in this scenario?

As a workaround, I also tried to use the CMake variable `VCPKG_PREFER_SYSTEM_LIBS`, so that the static library version of `openssl` will get installed via vcpkg, but I would still use the dynamic version from my system package manager. This also didn't work, but I haven't figured out why yet.
 
Thanks!

**Comment by autoantwort** [comment]
No this is not directly possible. You can write overlay ports that simply do nothing.

**Comment by Adela0814** [comment]
Has your problem been solved? @JulZimmermann

**Comment by Adela0814** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
