### ISSUE TITLE
[grpc] update to 1.46.0

### ISSUE THREAD

**Issue by FAKERINHEART** [microsoft/vcpkg#24557]
Library name:grpc

New version number:1.46.0

Other information that may be useful (release notes, etc...)
https://github.com/grpc/grpc/releases/tag/v1.46.0

**Comment by Tradias** [comment]
I have just worked on this, @FrankXie05 fyi

**Comment by FAKERINHEART** [comment]
@Tradias thank you for your work.

further more, I have tried on this with vcpkg. Howerver, I think the main problem is that the https://github.com/protocolbuffers/upb is not support cmake directly (the cmakelist.txt was deleted for repo in history commits), and you may go execute generating the cmakelist.txt in first.

**Comment by Tradias** [comment]
@FAKERINHEART yes thank you. I got it to work already :)
