### ISSUE TITLE
[v8] Build error

### ISSUE THREAD

**Issue by WangHHY19931001** [microsoft/vcpkg#24554]
windows10

vcpkg install v8
Computing installation plan...
The following packages will be built and installed:
    v8[core]:x86-windows -> 9.1.269.39#4
Detecting compiler hash for triplet x86-windows...
Restored 0 packages from C:\Users\CF\AppData\Local\vcpkg\archives in 210.1 us. Use --debug to see more details.
Starting package 1/1: v8:x86-windows
Building package v8[core]:x86-windows...
Consider adding vcpkg-tool-gn as a host dependency of this port or create an issue at https://github.com/microsoft/vcpkg/issues
-- Found external ninja('1.10.2').
-- Using cached msys-gzip-1.11-1-x86_64.pkg.tar.zst.
-- Using cached msys-bash-5.1.008-1-x86_64.pkg.tar.zst.
-- Using cached msys-diffutils-3.8-2-x86_64.pkg.tar.zst.
-- Using cached msys-coreutils-8.32-2-x86_64.pkg.tar.zst.
-- Using cached msys-grep-3.0-2-x86_64.pkg.tar.xz.
-- Using cached msys-sed-4.8-2-x86_64.pkg.tar.zst.
-- Using cached msys-libpcre-8.45-1-x86_64.pkg.tar.zst.
-- Using cached msys-gawk-5.1.0-2-x86_64.pkg.tar.zst.
-- Using cached msys-mpfr-4.1.0-1-x86_64.pkg.tar.zst.
-- Using cached msys-gmp-6.2.1-1-x86_64.pkg.tar.zst.
-- Using cached msys-libreadline-8.1.001-1-x86_64.pkg.tar.zst.
-- Using cached msys-ncurses-6.2-2-x86_64.pkg.tar.zst.
-- Using cached msys-pkg-config-0.29.2-4-x86_64.pkg.tar.zst.
-- Using cached msys-make-4.3-3-x86_64.pkg.tar.zst.
-- Using cached msys-libintl-0.21-1-x86_64.pkg.tar.zst.
-- Using cached msys-libiconv-1.16-2-x86_64.pkg.tar.zst.
-- Using cached msys-gcc-libs-11.2.0-3-x86_64.pkg.tar.zst.
-- Using cached msys-msys2-runtime-3.2.0-8-x86_64.pkg.tar.zst.
-- Using msys root at E:/vcpkg/downloads/tools/msys2/79d5b6b790550399
-- Using cached E:/vcpkg/downloads/v8-7d3d62c91f69a702e5aa54c6b4dbbaa883683717.tar.gz
-- Cleaning sources at E:/vcpkg/buildtrees/v8/src/a883683717-e774d37ef1.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/vcpkg/downloads/v8-7d3d62c91f69a702e5aa54c6b4dbbaa883683717.tar.gz
-- Applying patch E:/vcpkg/ports/v8/v8.patch
-- Using source at E:/vcpkg/buildtrees/v8/src/a883683717-e774d37ef1.clean
-- Fetching submodules
-- Generating v8 build files. Please wait...
-- Generating build (x86-windows-dbg)...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:128 (message):
    Command failed: E:/vcpkg/downloads/tools/gn/q5ExVHmXyD34Q_Tzb-aRxsPipO-e37-csVRhVM7IJh0C/gn.exe gen E:/vcpkg/buildtrees/v8/x86-windows-dbg "--args=is_component_build=true target_cpu=\"x86\" v8_monolithic=false v8_use_external_startup_data=true use_sysroot=false is_clang=false use_custom_libcxx=false v8_enable_verify_heap=false icu_use_data_file=false is_debug=true enable_iterator_debugging=true pkg_config_libdir=\"/e/vcpkg/installed/x86-windows/debug/lib/pkgconfig\""
    Working Directory: E:/vcpkg/buildtrees/v8/src/a883683717-e774d37ef1.clean
    Error code: 1
    See logs for more information:
      E:\vcpkg\buildtrees\v8\generate-x86-windows-dbg-out.log
      E:\vcpkg\buildtrees\v8\generate-x86-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_gn.cmake:39 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_configure_gn.cmake:66 (z_vcpkg_configure_gn_generate)
  ports/v8/portfile.cmake:150 (vcpkg_configure_gn)
  scripts/ports.cmake:145 (include)

including:
  package: v8[core]:x86-windows -> 9.1.269.39#4
    vcpkg-tool version: 2022-03-30-692785ac944e81417840c6de244fb3e18a4b35eb
    vcpkg-scripts version: b33f616f8 2022-05-04 (11 hours ago)

**Comment by Cheney-W** [comment]
Could you please provide us with following logs?
E:\vcpkg\buildtrees\v8\generate-x86-windows-dbg-out.log
E:\vcpkg\buildtrees\v8\generate-x86-windows-dbg-err.log

**Comment by WangHHY19931001** [comment]
generate-x86-windows-dbg-out.log

ERROR at //build/config/win/visual_studio_version.gni:27:7: Script returned non-zero exit code.
      exec_script("../../vs_toolchain.py", [ "get_toolchain_dir" ], "scope")
      ^----------
Current dir: E:/vcpkg/buildtrees/v8/x86-windows-dbg/
Command: E:/vcpkg/downloads/tools/python/python-3.10.2-x86/python.exe E:/vcpkg/buildtrees/v8/src/a883683717-e774d37ef1.clean/build/vs_toolchain.py get_toolchain_dir
Returned 1.
See //build/toolchain/win/BUILD.gn:8:1: whence it was imported.
import("//build/config/win/visual_studio_version.gni")
^----------------------------------------------------
See //BUILD.gn:1195:1: which caused the file to be included.
action("postmortem-metadata") {
^------------------------------

**Comment by WangHHY19931001** [comment]
generate-x86-windows-dbg-err.log

Traceback (most recent call last):
  File "E:\vcpkg\buildtrees\v8\src\a883683717-e774d37ef1.clean\build\vs_toolchain.py", line 573, in <module>
    sys.exit(main())
  File "E:\vcpkg\buildtrees\v8\src\a883683717-e774d37ef1.clean\build\vs_toolchain.py", line 569, in main
    return commands[sys.argv[1]](*sys.argv[2:])
  File "E:\vcpkg\buildtrees\v8\src\a883683717-e774d37ef1.clean\build\vs_toolchain.py", line 546, in GetToolchainDir
    runtime_dll_dirs = SetEnvironmentAndGetRuntimeDllDirs()
  File "E:\vcpkg\buildtrees\v8\src\a883683717-e774d37ef1.clean\build\vs_toolchain.py", line 106, in SetEnvironmentAndGetRuntimeDllDirs
    os.environ['GYP_MSVS_OVERRIDE_PATH'] = DetectVisualStudioPath()
  File "E:\vcpkg\buildtrees\v8\src\a883683717-e774d37ef1.clean\build\vs_toolchain.py", line 197, in DetectVisualStudioPath
    version_as_year = GetVisualStudioVersion()
  File "E:\vcpkg\buildtrees\v8\src\a883683717-e774d37ef1.clean\build\vs_toolchain.py", line 186, in GetVisualStudioVersion
    raise Exception('No supported Visual Studio can be found.'
Exception: No supported Visual Studio can be found. Supported versions are: 16.0 (2019), 15.0 (2017).

**Comment by WangHHY19931001** [comment]
E:\vcpkg\buildtrees\v8>python -V
Python 3.9.5

E:\vcpkg\buildtrees\v8>where python
C:\Users\CF\miniconda3\python.exe
C:\Users\CF\AppData\Local\Microsoft\WindowsApps\python.exe

**Comment by Cheney-W** [comment]
This issue is an known issue in v8. 
Currently v8 only support VS2017 and VS2019, if you just installed the VS2022, it will failed with above error.
Please make sure you installed VS2017 or VS2019 instead of installed V142 or V141 toolset in VS2022.
