### ISSUE TITLE
[OpenSSL] update to 1.1.1o

### ISSUE THREAD

**Issue by kalikin** [microsoft/vcpkg#24568]
Library name: OpenSSL

New version number: 1.1.1o

Other information that may be useful (release notes, etc...)
> 03-May-2022 OpenSSL 1.1.1o is now available, including bug and security fixes

https://www.openssl.org/
https://www.openssl.org/source/

**Comment by cron2** [comment]
bump?  trying to an OpenVPN release, being stuck with old OpenSSL vcpkg :-(

**Comment by JonLiu1993** [comment]
> 

@cron2 ,Sorry, I will submit a new version pr tomorrow

**Comment by cron2** [comment]
> 

cool, thanks

**Comment by JonLiu1993** [comment]
@kalikin @cron2 ,The current version of vcpkg is version 3.0.2, which corresponds to the 1.1.1 series1.1.1o. The openssl official website clearly states that OpenSSL 3.0 is the latest major version of OpenSSL, and all old versions (including 1.1.0, 1.0.2, 1.0.0 and 0.9.8) are now deprecated and should not be used. Users of these older versions are encouraged to upgrade to 3.0 as soon as possible. So the current version in the vcpkg library is already the latest version, and we can no longer roll back the new version to the old version. You can refer to the official website of openssl: https://www.openssl.org/source/

**Comment by dg0yt** [comment]
> version 3.0.2, which corresponds to the 1.1.1 series1.1.1o. 

It doesn't really "correspond". Read "the official website of openssl: https://www.openssl.org/source/":

> The previous LTS version (the 1.1.1 series) is also available and is supported until 11th September 2023.

So upstream considers the 1.1.1 series and the 3.0 series different enough to maintain both. However, the 1.1.1 series is no longer supported in vpckg. IIRC @ras0219-msft suggested to add a separate directory with an overlay port if really needed.

**Comment by zomborig** [comment]
I'd second to this, whit the addition, that it is currently 1.1.1q, not the "o" anymore. While I can manually work this around, it would be still nice to use OpenVPN-s internal build scripting for Windows with VCPKG.

**Comment by JonLiu1993** [comment]
@vicroms, Could you please take a look?

**Comment by vicroms** [comment]
We've discussed this internally in the past and the team is open to the idea of having a backports folder. But we haven't committed time to design how this backports would be tested in CI. I'll bring the topic for discussion on the next Thursday meeting.

**Comment by JonLiu1993** [comment]
This issue is similar to issue #20600, please track it in #20600.
