### ISSUE TITLE
[yasm] Build error, cannot open tools\re2c\re2c.exe for writing

### ISSUE THREAD

**Issue by EsbernTK** [microsoft/vcpkg#24562]
I was trying to compile pycolmap as instructed in the github repo under Windows https://github.com/colmap/pycolmap
In the middle of installing python 3.10 it hung for 30 minutes and i had to restart the compile.
After this i got the error that the compile had gotten access denied for opening install-x64-windows-dbg-out.log
I figured out that re2c.exe had a handle on that file and two other files, by using Process Explorer.
I removed those handles, and got this new error.
If i try to delete re2c.exe it gives me the error "The action can't be completed because the file is open in System"
I cannot shut down the re2c.exe process either, see additional context for full story.

**Host Environment**
- OS: Windows 10
package: yasm[core,tools]:x64-windows -> 1.3.0#3
    vcpkg-tool version: 2022-03-30-692785ac944e81417840c6de244fb3e18a4b35eb
    vcpkg-scripts version: 4b766c1cd 2022-05-04 (13 hours ago)

**To Reproduce**
`.\vcpkg.exe install colmap --triplet=x64-windows --head`
stop the execution as python 3.10 is being installed
run the above command again

**Failure logs**
```
Starting package 1/38: yasm:x64-windows
Building package yasm[core,tools]:x64-windows...
-- Using cached yasm-yasm-009450c7ad4d425fa5a10ac4bd6efbd25248d823.tar.gz.
-- Cleaning sources at C:/src/vcpkg/buildtrees/yasm/src/d25248d823-91ef8ed31f.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/src/vcpkg/downloads/yasm-yasm-009450c7a
-- Applying patch add-feature-tools.patch
-- Using source at C:/src/vcpkg/buildtrees/yasm/src/d25248d823-91ef8ed31f.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:158 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j9
    Working Directory: C:/src/vcpkg/buildtrees/yasm/x64-windows-dbg
    See logs for more information:
      C:\src\vcpkg\buildtrees\yasm\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:111 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
  ports/yasm/portfile.cmake:27 (vcpkg_cmake_install)
  scripts/ports.cmake:145 (include)
```
-Please attach any additional failure logs mentioned in the console output.
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/8632866/install-x64-windows-dbg-out.log)

**Additional context**
I was trying to compile pycolmap as instructed in the github repo under Windows https://github.com/colmap/pycolmap
I installed vcpkg as i did not have it on the computer, following the instructions in this repo.
As i was running the command to install colmap i noticed my antivirus (AVG) kept scanning the files that were being run, though they all passed. However as it was installing python 3.10 i noticed it had been hanging on the same line for 30 minutes, and i saw that my antivirus had given some error during the scanning, though the error was obscured as the GUI had not rendered properly.
I crtl+c in the console to stop the Colmap compile and to restart it.
As i restarted, vckpg gave an error that it got an access denied for opening install-x64-windows-dbg-out.log
I tried manually renaming the file to see if the compile would create a new version, however i got the error message that another process was using the file and therefore i could not rename.
I used Process Explorer to find the process that was responsible, and it was re2c.exe
This is where it gets interesting.
As an administrator i get access denied errors whenever i try to kill re2c.exe, wether it is done from Process Explorer or Resource Manager, nothing works. Running taskkill /F /im re2c.exe in an administrator command line just yields that no process is running, though i can see that is a lie in the Process Explorer.
When i try to delete re2c.exe i get the error "The action can't be completed because the file is open in System"
i have tried restarting and it always starts up with the system.
I managed to get past the first error and get to this compile error by closing the handles that re2c.exe had on the debug files, using the Process Explorer.

**Comment by EsbernTK** [comment]
Okay i have resolved the error and colmap is now compiling again.
I booted my pc into safe mode, and was luckily able to delete the re2c.exe, re2c.ilk and re2c.pdb files.
I restarted my pc into normal mode, and ran the command again, without copying the re2c files back into the directory
`.\vcpkg.exe install colmap --triplet=x64-windows --head`
It gave me this new error, and AVG freaked out again
<img width="425" alt="error_message" src="https://user-images.githubusercontent.com/10596719/167137280-722fc570-8611-4cc9-8a74-f30cb40a5675.png">
I crtl+c again and restarted the compile, but i started getting the access denied error for stdout-x64-windows.log
However, this time it was genmacro and genperf that had handles on the file
<img width="1838" alt="genperf_error" src="https://user-images.githubusercontent.com/10596719/167137733-4b46d489-3b83-40c5-9131-f36f84306fcd.png">

I again resolved this issue by booting into safe mode, deleting alle the .exe, .ilk and pdb files in both genperf and genmacro,
Booted into normal windows again, and then i wanted to get a good screenshot of the error message for documentation, so i copied back the genperf and genmacro files into their original folders, and ran the command again.
I got the same windows error message about the console being unable to reach the tools directory, however this time the console did not hang and it actually just continued compiling. I can also delete the genperf.exe, genmacro.exe and re2c.exe now, so they are no longer bound by the System process.

I do not want this issue closed, even though i found a solution, because this seems to be a general issue with how files are compiled by vcpkg. It is not great when a file gets bound to the system process and cannot be killed or deleted, and when it prevents the compile from going forward.

**Comment by Cheney-W** [comment]
Does this issue occur when the antivirus closed?

**Comment by EsbernTK** [comment]
The files do have handles on them even when antivirus is turned off. I also checked the "quarantined" files in my antivirus and there were none present.

**Comment by Cheney-W** [comment]
@BillyONeal 
I can't reproduce this issue in my side. Could you please help take a look this issue?

**Comment by BillyONeal** [comment]
"open in system" means "opened by a driver" which typically means antivirus. Just turning it off doesn't necessarily unload the drivers etc.

They tend to hate whenever we build something then immediately use it

**Comment by Cheney-W** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
