### ISSUE TITLE
There is a problem with darknet using cmake with CMAKE_TOOLCHAIN_FILE !

### ISSUE THREAD

**Issue by lunkyguy** [microsoft/vcpkg#24569]
while I am writing find_package(Darknet CONFIG REQUIRED) in my CMakeLists.txt,the compiler tells `find_package_handle_standard_args` (PThreads4W) does not match the name of the calling package (Darknet).

**Comment by dg0yt** [comment]
It as a problem with port pthreads, and should be resolved with #24308.

**Comment by dg0yt** [comment]
Note that you see a warning, i.e. a mild form of "problem".

**Comment by Adela0814** [comment]
@lunkyguy Have you tried this PR https://github.com/microsoft/vcpkg/pull/24308? Can this solve your problem？

**Comment by cenit** [comment]
@Adela0814 PR #24308 is made exactly for that. I hope it can be reviewed again soon, I just noticed that it was ok and it got stale only because of a wrong request (usage that was supposed wrong for *nix platform but was not)

**Comment by Adela0814** [comment]
The fix has been merged, closing this issue.
