### ISSUE TITLE
[tbb-2020_U3] build failure

### ISSUE THREAD

**Issue by cgurps** [microsoft/vcpkg#24575]
**Host Environment**
- OS: Windows 11
- Compiler: VS 2019

Good afternoon. I'm getting an error while building `TBB`:
```
 2>C:\dev\vs2019\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(523,5): error MSB6001: Invalid command line switch for "CL.exe". System.ArgumentException: Item has already been added. Key in dictionary: 'PATH'  Key being added: 'Path' [C:\Users\***\git\vcpkg\buildtrees\tbb\x64-windows-rel\7ec820cc37-30e75ff0be.clean\build\vs2013\tbb.vcxproj]
 ```
 Have you ever encountered that? It seems to be related to the project SLN configuration

**Comment by cgurps** [comment]
I've tried nuking my `vcpkg` cache and the `buildtress` folder but without success.

**Comment by JackBoosY** [comment]
Can you please provide the full log and repair your Visual Studio using Visual Studio Installer?

Thanks.

**Comment by cgurps** [comment]
Here's the full build log: [build-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/8639104/build-x64-windows-rel-out.log). I'm repairing my install right now.

**Comment by cgurps** [comment]
Repairing with Visual Studio Installer and rebuilding doesn't solve the issue.

**Comment by cgurps** [comment]
Looking at the environment variables, I only have one `PATH` which is under `System variables`

**Comment by cgurps** [comment]
So the repro is as followed:
- set `VCPKG_KEEP_ENV_VARS=PATH` in your env variables
- build the latest `tbb` version from `vcpkg`

**Comment by JackBoosY** [comment]
@cgurps I can't repro this locally, can you please provide your environment `PATH` value?

**Comment by JackBoosY** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.
