### ISSUE TITLE
[python3 x64-osx-dbg] Build error

### ISSUE THREAD

**Issue by BZandi** [microsoft/vcpkg#24576]
**Host Environment**
- OS: macOS 10.15.7
- Compiler: revision

**To Reproduce**
I use a Vcpkg.json file (manifest mode) with the following content
```json
{
    "name": "pypupilext",
    "port-version": 1,
    "version-string": "0.0.1.",
    "homepage": "https://github.com/openPupil/Open-PupilEXT",
    "description": "Python implementation of a open-source pupillometry system called PupilEXT.",
    "dependencies": [
        {
            "name": "pybind11",
            "version>=": "2.6.0#3"
        },
        {
            "name": "boost-math",
            "version>=": "1.75.0"
        },
        {
            "name": "boost-foreach",
            "version>=": "1.75.0"
        },
        {
            "name": "boost-range",
            "version>=": "1.75.0"
        },
        {
            "name": "boost-iterator",
            "version>=": "1.75.0"
        },
        {
            "name": "boost-config",
            "version>=": "1.75.0"
        },
        {
            "name": "boost-fusion",
            "version>=": "1.75.0"
        },
        {
            "name": "eigen3",
            "version>=": "3.3.9"
        },
        {
            "name": "tbb",
            "version>=": "2020_U3"
        },
        {
            "name": "ceres",
            "version>=": "2.0.0#3"
        },
        {
            "name": "opencv",
            "version>=": "4.5.1",
            "features": [
                "dnn",
                "jpeg",
                "png",
                "quirc",
                "tiff",
                "ffmpeg"
            ]
        }
    ],
    "builtin-baseline": "3426db05b996481ca31e95fff3734cf23e0f51bc"
}
```

The vcpkg folder is a submodule in my GitHub repo and is on the latest commit.

**Failure logs**
-- Downloading https://github.com/python/cpython/archive/v3.9.2.tar.gz -> python-cpython-v3.9.2.tar.gz...
-- Extracting source /Users/papillonmac/Desktop/PyPupilEXT/3rdparty/vcpkg/downloads/python-cpython-v3.9.2.tar.gz
-- Applying patch 0001-static-library.patch
-- Applying patch 0002-use-vcpkg-zlib.patch
-- Applying patch 0003-devendor-external-dependencies.patch
-- Applying patch 0004-dont-copy-vcruntime.patch
-- Applying patch 0005-only-build-required-projects.patch
-- Applying patch 0006-fix-duplicate-symbols.patch
-- Using source at /Users/papillonmac/Desktop/PyPupilEXT/3rdparty/vcpkg/buildtrees/python3/src/v3.9.2-51955b816d.clean
-- Getting CMake variables for x64-osx-dbg
-- Getting CMake variables for x64-osx-rel
-- Configuring x64-osx-dbg
-- Configuring x64-osx-rel
-- Building x64-osx-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:158 (message):
    Command failed: /usr/bin/make V=1 -j 13 -f Makefile all
    Working Directory: /Users/papillonmac/Desktop/PyPupilEXT/3rdparty/vcpkg/buildtrees/python3/x64-osx-dbg/
    See logs for more information:
      /Users/papillonmac/Desktop/PyPupilEXT/3rdparty/vcpkg/buildtrees/python3/build-x64-osx-dbg-out.log
      /Users/papillonmac/Desktop/PyPupilEXT/3rdparty/vcpkg/buildtrees/python3/build-x64-osx-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_make.cmake:202 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_make.cmake:26 (vcpkg_build_make)
  buildtrees/versioning_/versions/python3/9af42bd2d8ec6a2e8b563c9cb7544ffa7e2f938e/portfile.cmake:159 (vcpkg_install_make)
  scripts/ports.cmake:145 (include)

error: building python3:x64-osx failed with: BUILD_FAILED

**Additional context**
I found if I am on an older vcpkg commit (Link: [https://github.com/microsoft/vcpkg/tree/210240b399fbc2f1363f4103b6a93629c207d7e3](https://github.com/microsoft/vcpkg/tree/210240b399fbc2f1363f4103b6a93629c207d7e3); Hash: 210240b399fbc2f1363f4103b6a93629c207d7e3), then this error does not occur. Any suggestions how to solve this issue?

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Please provide the error log file:
```
/Users/papillonmac/Desktop/PyPupilEXT/3rdparty/vcpkg/buildtrees/python3/build-x64-osx-dbg-out.log
/Users/papillonmac/Desktop/PyPupilEXT/3rdparty/vcpkg/buildtrees/python3/build-x64-osx-dbg-err.log
```

**Comment by BZandi** [comment]
Thank you for your response.

You can reproduce the error on macOS 10.15 with the following commands:

```shell
# Create a python env to build the project
conda create -n pypupilenv python=3.7
conda activate pypupilenv
conda install numpy
python -m pip install --upgrade pip
python -m pip install opencv-python

# Start the build process
git clone --recursive https://github.com/openPupil/PyPupilEXT.git
cd PyPupilEXT/3rdparty/vcpkg
git checkout master
git pull
cd ...
python setup.py sdist bdist_wheel
```

Instead of calling ``python setup.py sdist bdist_wheel`` and create the python env you can also call the following

```shell
git clone --recursive https://github.com/openPupil/PyPupilEXT.git
cd PyPupilEXT/3rdparty/vcpkg
git checkout master
git pull
cd ...
cd build
cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DVCPKG_TARGET_TRIPLET=x64-osx -DCMAKE_TOOLCHAIN_FILE=3rdparty/vcpkg/scripts/buildsystems/vcpkg.cmake
cmake --build . --config Release
```

Attached you can find the log files.
[build-x64-osx-dbg-err.log](https://github.com/microsoft/vcpkg/files/8645440/build-x64-osx-dbg-err.log)
[build-x64-osx-dbg-out.log](https://github.com/microsoft/vcpkg/files/8645441/build-x64-osx-dbg-out.log)

**Comment by esdandreu** [comment]
I don't know if this might be relevant here. But I found an issue when building a python C++ extension worked on macOS when using `cmake` and `vcpkg` directly, but it failed when executing `cmake` (with `vcpkg` as a toolchain) through `pip`. This [run on github actions](https://github.com/esdandreu/python-extension-cpp/actions/runs/2304088913) shows it.
The error seems to be similar to the one presented in this issue:
```
Command failed: /usr/bin/make -j 5 -f Makefile altinstall DESTDIR=/Users/esdandreu/Desktop/python-extension-cpp/vcpkg/packages/python3_x64-osx
      Working Directory: /Users/esdandreu/Desktop/python-extension-cpp/vcpkg/buildtrees/python3/x64-osx-dbg/
[...]
Error: Building package python3:x64-osx failed with: BUILD_FAILED
```
The workaround I found is to execute `vcpkg install` *before* trying to build and install the python C++ extension with `pip install`. After applying the workaround, [github actions succeeds](https://github.com/esdandreu/python-extension-cpp/actions/runs/2310967365). If you think this is relevant I could provide more information and steps to reproduce.

**Comment by BZandi** [comment]
> I don't know if this might be relevant here. But I found an issue when building a python C++ extension worked on macOS when using `cmake` and `vcpkg` directly, but it failed when executing `cmake` (with `vcpkg` as a toolchain) through `pip`. This [run on github actions](https://github.com/esdandreu/python-extension-cpp/actions/runs/2304088913) shows it. The error seems to be similar to the one presented in this issue:
> 
> ```
> Command failed: /usr/bin/make -j 5 -f Makefile altinstall DESTDIR=/Users/esdandreu/Desktop/python-extension-cpp/vcpkg/packages/python3_x64-osx
>       Working Directory: /Users/esdandreu/Desktop/python-extension-cpp/vcpkg/buildtrees/python3/x64-osx-dbg/
> [...]
> Error: Building package python3:x64-osx failed with: BUILD_FAILED
> ```
> 
> The workaround I found is to execute `vcpkg install` _before_ trying to build and install the python C++ extension with `pip install`. After applying the workaround, [github actions succeeds](https://github.com/esdandreu/python-extension-cpp/actions/runs/2310967365). If you think this is relevant I could provide more information and steps to reproduce.

Thank you for posting your solution. I tried to include the following lines in my [GitHub Actions file](https://github.com/openPupil/PyPupilEXT/blob/0c5c7321326a2ece8d0e7695fa2fafaa3d70105c/.github/workflows/action.yml)

```yaml
${{ github.workspace }}/vcpkg/bootstrap-vcpkg.sh 
${{ github.workspace }}/vcpkg/vcpkg install
```

However, I receive the following error:

```shell
Read more about vcpkg telemetry at docs/about/privacy.md
[20](https://github.com/openPupil/PyPupilEXT/runs/6403081827?check_suite_focus=true#step:7:20)
Error: `vcpkg install` requires a list of packages to install in classic mode.
```

I wonder why this command works in [your yaml action file](https://github.com/esdandreu/python-extension-cpp/blob/main/.github/workflows/test.yml) but not in mine. Maybe I miss something.

**Comment by esdandreu** [comment]
It seems that it is not finding your `vcpkg.json` file and therefore thinks that is in classic mode. It may be caused by the fact that you `vcpkg` folder is not in the root of the repository, it is inside the `3rdparty` folder. But I'm not sure. Do you have access to a `macOS` machine or are you debugging on github actions?

**Comment by BZandi** [comment]
> It seems that it is not finding your `vcpkg.json` file and therefore thinks that is in classic mode. It may be caused by the fact that you `vcpkg` folder is not in the root of the repository, it is inside the `3rdparty` folder. But I'm not sure. Do you have access to a `macOS` machine or are you debugging on github actions?

Yes, I have a local macOS machine. In order to let vcpkg find the manifest file, I provided the path with ``vcpkg install --x-manifest-root=....``. Then, the pre-install of vcpkg worked.

However, unfortunately, this workaround did not solve the `` Building x64-osx-dbg`` error.

**Comment by dg0yt** [comment]
vcpkg is at python 3.10 now. Is this issue still relevant?
