### ISSUE TITLE
log4cplus package has wrong hash value

### ISSUE THREAD

**Issue by sbrosgol** [Microsoft/vcpkg#2457]
C:\dev\gitHub\vcpkg>vcpkg.exe install log4cplus log4cplus:x64-windows
The following packages will be built and installed:
  * catch[core]:x64-windows
    log4cplus[core]:x86-windows
    log4cplus[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/3: log4cplus:x86-windows
Building package log4cplus:x86-windows...
-- CURRENT_INSTALLED_DIR=C:/dev/gitHub/vcpkg/installed/x86-windows
-- DOWNLOADS=C:/dev/gitHub/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/dev/gitHub/vcpkg/packages/log4cplus_x86-windows
-- CURRENT_BUILDTREES_DIR=C:/dev/gitHub/vcpkg/buildtrees/log4cplus
-- CURRENT_PORT_DIR=C:/dev/gitHub/vcpkg/ports/log4cplus/.
-- Using cached C:/dev/gitHub/vcpkg/downloads/log4cplus-log4cplus-REL_2_0_0-RC2.tar.gz
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Using cached C:/dev/gitHub/vcpkg/downloads/log4cplus-threadpool-97b5877b9c49d02abf.tar.gz
-- Testing integrity of cached file...
CMake Error at C:/dev/gitHub/vcpkg/scripts/cmake/vcpkg_download_distfile.cmake:66 (message):

  File does not have expected hash:

          File path: [ C:/dev/gitHub/vcpkg/downloads/log4cplus-threadpool-97b5877b9c49d02abf.tar.gz ]
      Expected hash: [ 97b5877b9c49d02abfcba4ca1312b833b58e4f0e9884fdcf57c20b7ec58801ed24742c8316512b4de8ab29bae42cc1e34058c0d2443c3a5950a2fb3434f86662 ]
        Actual hash: [ 225adb11f447495a00e401d32f63d9a7eb3a8191d477a21bfa3c39f1ff5cbe8bfb7770a740e840c5748f816137cdef1a5915b17d16b3dd4c3399d1a67ab0f381 ]

  Please delete the file and retry if this file should be downloaded again.

Call Stack (most recent call first):
  C:/dev/gitHub/vcpkg/scripts/cmake/vcpkg_download_distfile.cmake:78 (test_hash)
  C:/dev/gitHub/vcpkg/ports/log4cplus/portfile.cmake:10 (vcpkg_download_distfile)
  C:/dev/gitHub/vcpkg/scripts/ports.cmake:72 (include)

Error: Building package log4cplus:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: log4cplus:x86-windows
  Vcpkg version: 0.0.100-2017-12-26-6e05f9cdf5cf4d53153214f4d4b29133b368bc4d

Additionally, attach any relevant sections from the log files above.

**Comment by ras0219-msft** [comment]
This should be fixed in master -- thanks for reporting this!
