### ISSUE TITLE
[abseil] support cxx20 

### ISSUE THREAD

**Issue by paulherman** [microsoft/vcpkg#24586]
****

**Is your feature request related to a problem? Please describe.**
Abseil provides polyfills when in C++20 mode for std::result_of. However, they're disabled without a new feature flag.

**Proposed solution**
Add a feature `cxx20`, similar to `cxx17` which sets `CMAKE_CXX_STANDARD` to `20`.

**Describe alternatives you've considered**
We could wire `CMAKE_CXX_STANDARD` from upstream, but not sure how feasible that is.

**Additional context**
The error when compiling in using `cxx17` when everything else is C++20: `absl/meta/type_traits.h(622,45): error C2039: 'result_of': is not a member of 'std'`.

**Comment by JackBoosY** [comment]
`abseil[cxx17]` was added before we released the policy, currently we do not accept adding c/cxx standard as a feature.
See https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#do-not-use-features-to-control-alternatives-in-published-interfaces

**Comment by LilyWangLL** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
