### ISSUE TITLE
[unicorn] update to 2.0.0rc7

### ISSUE THREAD

**Issue by wtdcode** [microsoft/vcpkg#24580]
Library name: unicorn

New version number: 2.0.0rc7

Other information that may be useful (release notes, etc...)

Hello, I just notice vcpkg is maintaining unicorn port and I'm the maintainer of the unicorn for now. Unicorn2 has a few RC versions already and is it possible to pack one?

Thanks for your efforts on porting unicorn ;).

**Comment by Adela0814** [comment]
Prefer to https://github.com/microsoft/vcpkg/issues/25707.
