### ISSUE TITLE
Building package libvorbis:x86-windows failed

### ISSUE THREAD

**Issue by LudovicLachance** [Microsoft/vcpkg#2458]
J:\vcpkg>.\vcpkg install libvorbis
The following packages will be built and installed:
    libvorbis[core]:x86-windows
Starting package 1/1: libvorbis:x86-windows
Building package libvorbis:x86-windows...
-- CURRENT_INSTALLED_DIR=J:/vcpkg/installed/x86-windows
-- DOWNLOADS=J:/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=J:/vcpkg/packages/libvorbis_x86-windows
-- CURRENT_BUILDTREES_DIR=J:/vcpkg/buildtrees/libvorbis
-- CURRENT_PORT_DIR=J:/vcpkg/ports/libvorbis/.
-- Using cached J:/vcpkg/downloads/vorbis-143caf4023a90c09a5eb685fdd46fb9b9c36b1ee.zip
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting source J:/vcpkg/downloads/vorbis-143caf4023a90c09a5eb685fdd46fb9b9c36b1ee.zip
CMake Error at J:/vcpkg/scripts/cmake/vcpkg_execute_required_process.cmake:44 (message):
    Command failed: J:/vcpkg/downloads/cmake-3.10.0-win32-x86/bin/cmake.exe;-E;tar;xjf;J:/vcpkg/downloads/vorbis-143caf4023a90c09a5eb685fdd46fb9b9c36b1ee.zip
    Working Directory: J:/vcpkg/buildtrees/libvorbis/src
    See logs for more information:
      J:\vcpkg\buildtrees\libvorbis\extract-out.log
      J:\vcpkg\buildtrees\libvorbis\extract-err.log

Call Stack (most recent call first):
  J:/vcpkg/scripts/cmake/vcpkg_extract_source_archive.cmake:49 (vcpkg_execute_required_process)
  J:/vcpkg/scripts/cmake/vcpkg_extract_source_archive.cmake:61 (vcpkg_extract_source_archive_ex)
  J:/vcpkg/ports/libvorbis/portfile.cmake:17 (vcpkg_extract_source_archive)
  J:/vcpkg/scripts/ports.cmake:72 (include)

Error: Building package libvorbis:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libvorbis:x86-windows
  Vcpkg version: 0.0.100-2017-12-26-6e05f9cdf5cf4d53153214f4d4b29133b368bc4d

Additionally, attach any relevant sections from the log files above.

**Comment by LudovicLachance** [comment]
out.log
CMake Error: Problem with archive_write_finish_entry(): Can't restore time
CMake Error: Problem extracting tar: J:/vcpkg/downloads/vorbis-143caf4023a90c09a5eb685fdd46fb9b9c36b1ee.zip

**Comment by LudovicLachance** [comment]
i can unzip the file alright by myself

**Comment by NancyLi1013** [comment]
@LudovicLachance , thank you for posting this issue.
this issue should be fixed now. Please open a new issue if this is still a problem for you.
