### ISSUE TITLE
[crashrpt] Build error

### ISSUE THREAD

**Issue by yansong1221** [microsoft/vcpkg#24594]
PS F:\code\vcpkg> .\vcpkg.exe install crashrpt:x64-windows
```
Computing installation plan...
The following packages will be built and installed:
    crashrpt[core]:x64-windows -> 1.4.3#2
Detecting compiler hash for triplet x64-windows...
-- Automatically setting HTTP(S)_PROXY environment variables to 127.0.0.1:8889
Restored 0 packages from C:\Users\pc\AppData\Local\vcpkg\archives in 161.5 us. Use --debug to see more details.
Starting package 1/1: crashrpt:x64-windows
Building package crashrpt[core]:x64-windows...
-- Using cached F:/code/vcpkg/downloads/crashrpt-4616504670be5a425a525376648d912a72ce18f2.tar.gz
-- Cleaning sources at F:/code/vcpkg/buildtrees/crashrpt/src/2a72ce18f2-57e43e2812.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source F:/code/vcpkg/downloads/crashrpt-4616504670be5a425a525376648d912a72ce18f2.tar.gz
-- Applying patch 001-add-install-target-and-find-deps.patch
-- Using source at F:/code/vcpkg/buildtrees/crashrpt/src/2a72ce18f2-57e43e2812.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:158 (message):
    Command failed: F:/code/vcpkg/downloads/tools/cmake-3.22.2-windows/cmake-3.22.2-windows-i386/bin/cmake.exe --build . --config Debug --target install -- /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /m
    Working Directory: F:/code/vcpkg/buildtrees/crashrpt/x64-windows-dbg
    See logs for more information:
      F:\code\vcpkg\buildtrees\crashrpt\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:113 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:44 (vcpkg_build_cmake)
  ports/crashrpt/portfile.cmake:46 (vcpkg_install_cmake)
  scripts/ports.cmake:145 (include)


error: building crashrpt:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+crashrpt
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[crashrpt]+Build+error
including:
  package: crashrpt[core]:x64-windows -> 1.4.3#2
    vcpkg-tool version: 2022-03-30-692785ac944e81417840c6de244fb3e18a4b35eb
    vcpkg-scripts version: a5d6d1451 2022-05-06 (2 hours ago)
```

**Comment by Cheney-W** [comment]
Could you please provide us with `F:\code\vcpkg\buildtrees\crashrpt\install-x64-windows-dbg-out.log`?

**Comment by yansong1221** [comment]
用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.11.2+f32259642
版权所有(C) Microsoft Corporation。保留所有权利。

生成启动时间为 2022/5/7 14:36:38。
     1>节点 1 上的项目“F:\code\vcpkg\buildtrees\crashrpt\x64-windows-dbg\install.vcxproj”(默认目标)。
     1>项目“F:\code\vcpkg\buildtrees\crashrpt\x64-windows-dbg\install.vcxproj”(1)正在节点 1 上生成“F:\code\vcpkg\buildtrees\crashrpt\x64-windows-dbg\ZERO_CHECK.vcxproj”(2) (默认目标)。
     2>PrepareForBuild:
         正在创建目录“x64\Debug\ZERO_CHECK\”。
         正在创建目录“x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\”。
       InitializeBuildStatus:
         正在创建“x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
       CustomBuild:
         Checking Build System
       FinalizeBuildStatus:
         正在删除文件“x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild”。
         正在对“x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\ZERO_CHECK.lastbuildstate”执行 Touch 任务。
     2>已完成生成项目“F:\code\vcpkg\buildtrees\crashrpt\x64-windows-dbg\ZERO_CHECK.vcxproj”(默认目标)的操作。
     1>项目“F:\code\vcpkg\buildtrees\crashrpt\x64-windows-dbg\install.vcxproj”(1)正在节点 2 上生成“F:\code\vcpkg\buildtrees\crashrpt\x64-windows-dbg\ALL_BUILD.vcxproj”(3) (默认目标)。
     3>项目“F:\code\vcpkg\buildtrees\crashrpt\x64-windows-dbg\ALL_BUILD.vcxproj”(3)正在节点 2 上生成“F:\code\vcpkg\buildtrees\crashrpt\x64-windows-dbg\reporting\crashrpt\CrashRpt.vcxproj”(4) (默认目标)。
     4>PrepareForBuild:
         正在创建目录“CrashRpt.dir\Debug\”。
         正在创建目录“F:\code\vcpkg\buildtrees\crashrpt\x64-windows-dbg\bin\x64\”。
         正在创建目录“CrashRpt.dir\Debug\CrashRpt.tlog\”。
       InitializeBuildStatus:
         正在创建“CrashRpt.dir\Debug\CrashRpt.tlog\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
       CustomBuild:
         Building Custom Rule F:/code/vcpkg/buildtrees/crashrpt/src/2a72ce18f2-57e43e2812.clean/reporting/crashrpt/CMakeLists.txt
       MakeDirsForCl:
         正在创建目录“F:\code\vcpkg\buildtrees\crashrpt\x64-windows-dbg\reporting\crashrpt\Debug”。
       ClCompile:
         C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\CL.exe /c /I"F:\code\vcpkg\buildtrees\crashrpt\src\2a72ce18f2-57e43e2812.clean\include" /I"F:\code\vcpkg\installed\x64-windows\include" /Z7 /nologo /W4 /WX- /diagnostics:column /MP /Od /Ob0 /Os /D _WINDLL /D _UNICODE /D UNICODE /D WIN32 /D _WINDOWS /D _DEBUG /D _UNICODE /D _CRT_SECURE_NO_DEPRECATE /D "CMAKE_INTDIR=\"Debug\"" /D CrashRpt_EXPORTS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Yc"stdafx.h" /Fp"F:/code/vcpkg/buildtrees/crashrpt/x64-windows-dbg/reporting/crashrpt/Debug/stdafx.pch" /Fo"CrashRpt.dir\Debug\\" /Fd"CrashRpt.dir\Debug\vc142.pdb" /external:W4 /Gd /TP /errorReport:queue  /utf-8 "F:\code\vcpkg\buildtrees\crashrpt\src\2a72ce18f2-57e43e2812.clean\reporting\crashrpt\StdAfx.cpp"
         StdAfx.cpp
     3>项目“F:\code\vcpkg\buildtrees\crashrpt\x64-windows-dbg\ALL_BUILD.vcxproj”(3)正在节点 3 上生成“F:\code\vcpkg\buildtrees\crashrpt\x64-windows-dbg\thirdparty\minizip\minizip.vcxproj”(6) (默认目标)。
     6>PrepareForBuild:
         正在创建目录“minizip.dir\Debug\”。
         正在创建目录“F:\code\vcpkg\buildtrees\crashrpt\x64-windows-dbg\thirdparty\lib\x64\”。
         正在创建目录“minizip.dir\Debug\minizip.tlog\”。
       InitializeBuildStatus:
         正在创建“minizip.dir\Debug\minizip.tlog\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
       CustomBuild:
         Building Custom Rule F:/code/vcpkg/buildtrees/crashrpt/src/2a72ce18f2-57e43e2812.clean/thirdparty/minizip/CMakeLists.txt
       ClCompile:
         C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\CL.exe /c /I"F:\code\vcpkg\installed\x64-windows\include" /Z7 /nologo /W4 /WX- /diagnostics:column /MP /Od /Ob0 /D _UNICODE /D UNICODE /D WIN32 /D _WINDOWS /D _DEBUG /D _UNICODE /D _CRT_SECURE_NO_DEPRECATE /D "CMAKE_INTDIR=\"Debug\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"minizip.dir\Debug\\" /Fd"F:\code\vcpkg\buildtrees\crashrpt\x64-windows-dbg\thirdparty\lib\x64\minizipd.pdb" /external:W4 /Gd /TC /wd4127 /wd4131 /wd4100 /wd4189 /wd4244 /errorReport:queue  /utf-8 "F:\code\vcpkg\buildtrees\crashrpt\src\2a72ce18f2-57e43e2812.clean\thirdparty\minizip\ioapi.c" "F:\code\vcpkg\buildtrees\crashrpt\src\2a72ce18f2-57e43e2812.clean\thirdparty\minizip\iowin32.c" "F:\code\vcpkg\buildtrees\crashrpt\src\2a72ce18f2-57e43e2812.clean\thirdparty\minizip\mztools.c" "F:\code\vcpkg\buildtrees\crashrpt\src\2a72ce18f2-57e43e2812.clean\thirdparty\minizip\unzip.c" "F:\code\vcpkg\buildtrees\crashrpt\src\2a72ce18f2-57e43e2812.clean\thirdparty\minizip\zip.c"
         ioapi.c
         iowin32.c
         mztools.c
         unzip.c
         zip.c
     6>F:\code\vcpkg\buildtrees\crashrpt\src\2a72ce18f2-57e43e2812.clean\thirdparty\minizip\mztools.c(139,26): warning C4456: declaration of 'header' hides previous local declaration [F:\code\vcpkg\buildtrees\crashrpt\x64-windows-dbg\thirdparty\minizip\minizip.vcxproj]
       F:\code\vcpkg\buildtrees\crashrpt\src\2a72ce18f2-57e43e2812.clean\thirdparty\minizip\mztools.c(44,10): message : see declaration of 'header' [F:\code\vcpkg\buildtrees\crashrpt\x64-windows-dbg\thirdparty\minizip\minizip.vcxproj]
     6>F:\code\vcpkg\buildtrees\crashrpt\src\2a72ce18f2-57e43e2812.clean\thirdparty\minizip\mztools.c(214,22): warning C4456: declaration of 'header' hides previous local declaration [F:\code\vcpkg\buildtrees\crashrpt\x64-windows-dbg\thirdparty\minizip\minizip.vcxproj]
       F:\code\vcpkg\buildtrees\crashrpt\src\2a72ce18f2-57e43e2812.clean\thirdparty\minizip\mztools.c(44,10): message : see declaration of 'header' [F:\code\vcpkg\buildtrees\crashrpt\x64-windows-dbg\thirdparty\minizip\minizip.vcxproj]
     6>F:\code\vcpkg\buildtrees\crashrpt\src\2a72ce18f2-57e43e2812.clean\thirdparty\minizip\unzip.c(1041,65): warning C4456: declaration of 'uL' hides previous local declaration [F:\code\vcpkg\buildtrees\crashrpt\x64-windows-dbg\thirdparty\minizip\minizip.vcxproj]
       F:\code\vcpkg\buildtrees\crashrpt\src\2a72ce18f2-57e43e2812.clean\thirdparty\minizip\unzip.c(896,11): message : see declaration of 'uL' [F:\code\vcpkg\buildtrees\crashrpt\x64-windows-dbg\thirdparty\minizip\minizip.vcxproj]
     6>F:\code\vcpkg\buildtrees\crashrpt\src\2a72ce18f2-57e43e2812.clean\thirdparty\minizip\zip.c(1248,45): warning C4057: '=': 'const unsigned long *' differs in indirection to slightly different base types from 'const z_crc_t *' [F:\code\vcpkg\buildtrees\crashrpt\x64-windows-dbg\thirdparty\minizip\minizip.vcxproj]
       Lib:
         C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\Lib.exe /OUT:"F:\code\vcpkg\buildtrees\crashrpt\x64-windows-dbg\thirdparty\lib\x64\minizipd.lib" /NOLOGO /MACHINE:X64  /machine:x64 /nologo minizip.dir\Debug\ioapi.obj
         minizip.dir\Debug\iowin32.obj
         minizip.dir\Debug\mztools.obj
         minizip.dir\Debug\unzip.obj
         minizip.dir\Debug\zip.obj
         minizip.vcxproj -> F:\code\vcpkg\buildtrees\crashrpt\x64-windows-dbg\thirdparty\lib\x64\minizipd.lib
       FinalizeBuildStatus:
         正在删除文件“minizip.dir\Debug\minizip.tlog\unsuccessfulbuild”。
         正在对“minizip.dir\Debug\minizip.tlog\minizip.lastbuildstate”执行 Touch 任务。
     6>已完成生成项目“F:\code\vcpkg\buildtrees\crashrpt\x64-windows-dbg\thirdparty\minizip\minizip.vcxproj”(默认目标)的操作。
     3>项目“F:\code\vcpkg\buildtrees\crashrpt\x64-windows-dbg\ALL_BUILD.vcxproj”(3)正在节点 1 上生成“F:\code\vcpkg\buildtrees\crashrpt\x64-windows-dbg\reporting\crashsender\CrashSender.vcxproj”(5) (默认目标)。
     5>PrepareForBuild:
         正在创建目录“CrashSender.dir\Debug\”。
         正在创建目录“CrashSender.dir\Debug\CrashSender.tlog\”。
       InitializeBuildStatus:
         正在创建“CrashSender.dir\Debug\CrashSender.tlog\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
       CustomBuild:
         Building Custom Rule F:/code/vcpkg/buildtrees/crashrpt/src/2a72ce18f2-57e43e2812.clean/reporting/crashsender/CMakeLists.txt
       MakeDirsForCl:
         正在创建目录“F:\code\vcpkg\buildtrees\crashrpt\x64-windows-dbg\reporting\crashsender\Debug”。
       ClCompile:
         C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\CL.exe /c /I"F:\code\vcpkg\buildtrees\crashrpt\src\2a72ce18f2-57e43e2812.clean\include" /I"F:\code\vcpkg\buildtrees\crashrpt\src\2a72ce18f2-57e43e2812.clean\reporting\CrashRpt" /I"F:\code\vcpkg\buildtrees\crashrpt\src\2a72ce18f2-57e43e2812.clean\thirdparty\minizip" /I"F:\code\vcpkg\installed\x64-windows\include" /Z7 /nologo /W4 /WX- /diagnostics:column /MP /Od /Ob0 /D _UNICODE /D UNICODE /D WIN32 /D _WINDOWS /D _DEBUG /D _UNICODE /D "CMAKE_INTDIR=\"Debug\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Yc"stdafx.h" /Fp"F:/code/vcpkg/buildtrees/crashrpt/x64-windows-dbg/reporting/crashsender/Debug/stdafx.pch" /Fo"CrashSender.dir\Debug\\" /Fd"CrashSender.dir\Debug\vc142.pdb" /external:W4 /Gd /TP /errorReport:queue  /utf-8 "F:\code\vcpkg\buildtrees\crashrpt\src\2a72ce18f2-57e43e2812.clean\reporting\crashsender\stdafx.cpp"
         stdafx.cpp
     4>F:\code\vcpkg\buildtrees\crashrpt\src\2a72ce18f2-57e43e2812.clean\reporting\crashrpt\StdAfx.cpp(5,1): error C2850: 'PCH header file': only allowed at file scope; may not be in a nested construct [F:\code\vcpkg\buildtrees\crashrpt\x64-windows-dbg\reporting\crashrpt\CrashRpt.vcxproj]
       F:\code\vcpkg\installed\x64-windows\include\dbghelp.h(48): message : this line contains a '{' which has not yet been matched [F:\code\vcpkg\buildtrees\crashrpt\x64-windows-dbg\reporting\crashrpt\CrashRpt.vcxproj]
     4>F:\code\vcpkg\installed\x64-windows\include\dbghelp.h(48): fatal error C1075: '{': no matching token found [F:\code\vcpkg\buildtrees\crashrpt\x64-windows-dbg\reporting\crashrpt\CrashRpt.vcxproj]
     4>已完成生成项目“F:\code\vcpkg\buildtrees\crashrpt\x64-windows-dbg\reporting\crashrpt\CrashRpt.vcxproj”(默认目标)的操作 - 失败。
     5>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\Wspiapi.h(53,10): error C2894: templates cannot be declared to have 'C' linkage [F:\code\vcpkg\buildtrees\crashrpt\x64-windows-dbg\reporting\crashsender\CrashSender.vcxproj]
     5>F:\code\vcpkg\buildtrees\crashrpt\src\2a72ce18f2-57e43e2812.clean\reporting\crashsender\stdafx.cpp(14,1): error C2850: 'PCH header file': only allowed at file scope; may not be in a nested construct [F:\code\vcpkg\buildtrees\crashrpt\x64-windows-dbg\reporting\crashsender\CrashSender.vcxproj]
       F:\code\vcpkg\installed\x64-windows\include\dbghelp.h(48): message : this line contains a '{' which has not yet been matched [F:\code\vcpkg\buildtrees\crashrpt\x64-windows-dbg\reporting\crashsender\CrashSender.vcxproj]
     5>F:\code\vcpkg\installed\x64-windows\include\dbghelp.h(48): fatal error C1075: '{': no matching token found [F:\code\vcpkg\buildtrees\crashrpt\x64-windows-dbg\reporting\crashsender\CrashSender.vcxproj]
     5>已完成生成项目“F:\code\vcpkg\buildtrees\crashrpt\x64-windows-dbg\reporting\crashsender\CrashSender.vcxproj”(默认目标)的操作 - 失败。
     3>已完成生成项目“F:\code\vcpkg\buildtrees\crashrpt\x64-windows-dbg\ALL_BUILD.vcxproj”(默认目标)的操作 - 失败。
     1>已完成生成项目“F:\code\vcpkg\buildtrees\crashrpt\x64-windows-dbg\install.vcxproj”(默认目标)的操作 - 失败。

生成失败。

       “F:\code\vcpkg\buildtrees\crashrpt\x64-windows-dbg\install.vcxproj”(默认目标) (1) ->
       “F:\code\vcpkg\buildtrees\crashrpt\x64-windows-dbg\ALL_BUILD.vcxproj”(默认目标) (3) ->
       “F:\code\vcpkg\buildtrees\crashrpt\x64-windows-dbg\thirdparty\minizip\minizip.vcxproj”(默认目标) (6) ->
       (ClCompile 目标) -> 
         F:\code\vcpkg\buildtrees\crashrpt\src\2a72ce18f2-57e43e2812.clean\thirdparty\minizip\mztools.c(139,26): warning C4456: declaration of 'header' hides previous local declaration [F:\code\vcpkg\buildtrees\crashrpt\x64-windows-dbg\thirdparty\minizip\minizip.vcxproj]
         F:\code\vcpkg\buildtrees\crashrpt\src\2a72ce18f2-57e43e2812.clean\thirdparty\minizip\mztools.c(214,22): warning C4456: declaration of 'header' hides previous local declaration [F:\code\vcpkg\buildtrees\crashrpt\x64-windows-dbg\thirdparty\minizip\minizip.vcxproj]
         F:\code\vcpkg\buildtrees\crashrpt\src\2a72ce18f2-57e43e2812.clean\thirdparty\minizip\unzip.c(1041,65): warning C4456: declaration of 'uL' hides previous local declaration [F:\code\vcpkg\buildtrees\crashrpt\x64-windows-dbg\thirdparty\minizip\minizip.vcxproj]
         F:\code\vcpkg\buildtrees\crashrpt\src\2a72ce18f2-57e43e2812.clean\thirdparty\minizip\zip.c(1248,45): warning C4057: '=': 'const unsigned long *' differs in indirection to slightly different base types from 'const z_crc_t *' [F:\code\vcpkg\buildtrees\crashrpt\x64-windows-dbg\thirdparty\minizip\minizip.vcxproj]


       “F:\code\vcpkg\buildtrees\crashrpt\x64-windows-dbg\install.vcxproj”(默认目标) (1) ->
       “F:\code\vcpkg\buildtrees\crashrpt\x64-windows-dbg\ALL_BUILD.vcxproj”(默认目标) (3) ->
       “F:\code\vcpkg\buildtrees\crashrpt\x64-windows-dbg\reporting\crashrpt\CrashRpt.vcxproj”(默认目标) (4) ->
       (ClCompile 目标) -> 
         F:\code\vcpkg\buildtrees\crashrpt\src\2a72ce18f2-57e43e2812.clean\reporting\crashrpt\StdAfx.cpp(5,1): error C2850: 'PCH header file': only allowed at file scope; may not be in a nested construct [F:\code\vcpkg\buildtrees\crashrpt\x64-windows-dbg\reporting\crashrpt\CrashRpt.vcxproj]
         F:\code\vcpkg\installed\x64-windows\include\dbghelp.h(48): fatal error C1075: '{': no matching token found [F:\code\vcpkg\buildtrees\crashrpt\x64-windows-dbg\reporting\crashrpt\CrashRpt.vcxproj]


       “F:\code\vcpkg\buildtrees\crashrpt\x64-windows-dbg\install.vcxproj”(默认目标) (1) ->
       “F:\code\vcpkg\buildtrees\crashrpt\x64-windows-dbg\ALL_BUILD.vcxproj”(默认目标) (3) ->
       “F:\code\vcpkg\buildtrees\crashrpt\x64-windows-dbg\reporting\crashsender\CrashSender.vcxproj”(默认目标) (5) ->
         C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\Wspiapi.h(53,10): error C2894: templates cannot be declared to have 'C' linkage [F:\code\vcpkg\buildtrees\crashrpt\x64-windows-dbg\reporting\crashsender\CrashSender.vcxproj]
         F:\code\vcpkg\buildtrees\crashrpt\src\2a72ce18f2-57e43e2812.clean\reporting\crashsender\stdafx.cpp(14,1): error C2850: 'PCH header file': only allowed at file scope; may not be in a nested construct [F:\code\vcpkg\buildtrees\crashrpt\x64-windows-dbg\reporting\crashsender\CrashSender.vcxproj]
         F:\code\vcpkg\installed\x64-windows\include\dbghelp.h(48): fatal error C1075: '{': no matching token found [F:\code\vcpkg\buildtrees\crashrpt\x64-windows-dbg\reporting\crashsender\CrashSender.vcxproj]

    4 个警告
    5 个错误

已用时间 00:00:02.94

**Comment by BenKey** [comment]
I believe I am experiencing the same issue. The config-x64-windows-out.log reveals the problem.

```
CMake Error at CMakeLists.txt:127 (message):
  WTL include dir not found
```

The WTL header files were previously installed in a wtl subdirectory of the **${vcpkg_root}\installed\x64-windows\include** directory. Now they are installed in the **${vcpkg_root}\installed\x64-windows\include** directory itself. The following test will fail as a result.

```
find_path(WTL_INCLUDE_DIR wtl/atlapp.h)
if(NOT WTL_INCLUDE_DIR)
  message(FATAL_ERROR "WTL include dir not found")
endif()
```

I hope this helps.

[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/8904514/config-x64-windows-out.log)

**Comment by Cheney-W** [comment]
@BenKey 
I think you got a different issue, your issue came from the PR https://github.com/microsoft/vcpkg/pull/25108, which is merged 6 days ago. For fixing this issue, we should do same change in the https://github.com/microsoft/vcpkg/blob/master/ports/crashrpt/001-add-install-target-and-find-deps.patch file.

**Comment by yansong1221** [comment]
remove   dependencies "dbghelp",Compiled successfully
