### ISSUE TITLE
[New Port Request] <phlib>

### ISSUE THREAD

**Issue by SpenserCai** [microsoft/vcpkg#24602]
Library name:
phlib
Library description:
This is a core library of ProcessHacker, it has a lot of and very useful windows api wrappers
Source repository URL:
https://github.com/processhacker/processhacker/tree/master/phlib
Project homepage (if different from the source repository):
https://processhacker.sourceforge.io/
Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
