### ISSUE TITLE
[New Port Request] libslirp, C++/C bindings

### ISSUE THREAD

**Issue by kcgen** [microsoft/vcpkg#24604]
**Library name:** libslirp

**Library description:**  A general purpose TCP-IP emulator used by virtual machine hypervisors to provide virtual networking services.

**Source repository URL:**
 - C/C++ library: https://gitlab.freedesktop.org/slirp/libslirp
 - Rust bindings: https://gitlab.freedesktop.org/slirp/libslirp-rs

**Project homepage**: https://gitlab.freedesktop.org/slirp

`libslirp` is used by Qemu, Bochs, VirtualBox, DOSBox-X, and DOSBox Staging (and surely others) to  emulate a full TCP/IP stack inside the software while at the host level acting as a TCP/IP client.

Currently `libslirp` is available on Windows via MinGW or MSYS2 package manager, such as pacman. For example: https://packages.msys2.org/package/mingw-w64-x86_64-libslirp

`libslirp` only depends on glib, which already is in vcpkg - so hopefully this is doable.

**More reading:**
 - https://en.wikipedia.org/wiki/Slirp
 - https://wiki.qemu.org/Documentation/Networking#User_Networking_.28SLIRP.29

**Comment by dhrdlicka** [comment]
vcpkg already has a libslirp port -- I submitted one a few months ago in #22394. Needs to be updated to 4.7.0 though.

**Comment by Kappa971** [comment]
> vcpkg already has a libslirp port -- I contributed one a few months ago in #22394. In fact I have just submitted #24689 which updates it to 4.7.0.

Does the new version work with MSVC?

**Comment by dhrdlicka** [comment]
No, the upstream still only supports MinGW.

FWIW the main issues are just the usage of GCC syntax for struct packing and some quirky POSIX includes. That could technically be patched in the port, though raising the issue at the upstream is a still good idea nevertheless.

**Comment by Kappa971** [comment]
> No, the upstream still only supports MinGW. The code uses the GCC syntax for struct packing and relies on its bitfields implementation. I guess Clang could work in theory, which would leave a bunch of quirky POSIX includes left to be fixed, but I don't think vcpkg supports it for compiling ports.

I will try to make a request on GitLab, thanks.

**Comment by Kappa971** [comment]
The developer is willing to add support to Visual Studio, this is what he wrote:
"_Hello, I don't have an MSVC toolchain, contribution welcome!_".
Anyone who wants to contribute, @kcgen, @dhrdlicka or others, can do it here: https://gitlab.freedesktop.org/slirp/libslirp/-/issues/60

**Comment by kcgen** [comment]
@Kappa971 , thanks for sharing this issue with upstream. 

@sthibaul , regarding not having an MSVC toolchain, the problem involves libslirp being written using GNU-specific extensions.  To make libslirp portable, these addon GNU-extensions need to be replace with standard C syntax language, be it C99 or C11 (or even C18). 

That can be pursued 100% with Meson and GCC, simply by telling Meson that the code case is C-standard-compliant:

```diff
diff --git a/meson.build b/meson.build
index 5fe33d3..7883e0f 100644
--- a/meson.build
+++ b/meson.build
@@ -1,7 +1,7 @@
 project('libslirp', 'c',
   version : '4.7.0',
   license : 'BSD-3-Clause',
-  default_options : ['warning_level=1', 'c_std=gnu99'],
+  default_options : ['warning_level=3', 'c_std=c99'],
   meson_version : '>= 0.50',
 )
```

Then:

``` shell
meson setup build
meson compile -C build
```

And watch the sparks fly :sweat_smile: !  

If you can get it compiling and working there, then it will build under OpenWatcom, MSVC, and others etc..

**Comment by sthibaul** [comment]
The only real problematic part I see is the use of the `typeof` extension (which to my opinion should have been in the standard for so long).
Do you have a use for the save-state part? We could simply disable that part under msvc. Otherwise, it won't be trivial to fix it not to use `typeof`.

**Comment by kcgen** [comment]
> Do you have a use for the save-state part? > We could simply disable that part under msvc. 

That would work for us, as DOSBox Staging project doesn't use save-states.  Sounds like good first round of changes.

**Comment by Kappa971** [comment]
Can you compile this build with MSVC?
[libslirp-msvc.zip](https://github.com/microsoft/vcpkg/files/8691461/libslirp-msvc.zip)

**Comment by Kappa971** [comment]
@kcgen @dhrdlicka, now you can compile libslirp with MSVC (branch here: https://gitlab.freedesktop.org/slirp/libslirp/-/merge_requests/124).

There are two problems left:
1. this part of `meson.build` code:
```
r = run_command('build-aux/git-version- gen',
                '@0@/.tarball-version'.format(meson.current_source_dir()),
                check : false)

full_version = r.stdout().strip()
if r.returncode() != 0 or full_version.startswith('UNKNOWN')
  full_version = meson.project_version()
elif not full_version.startswith(meson.project_version())
  error('meson.build project version @0@ does not match git-describe output @1@'
        .format(meson.project_version(), full_version))
endif
```
   causes this error:
![Immagine_2022-05-13_164639](https://user-images.githubusercontent.com/62349018/168448708-2f80675a-c07f-44aa-b978-744d99378622.png)
I'm not an expert, maybe you can help @sthibaul to solve this problem.
In order to compile the library, I had to leave only `full_version = meson.project_version()`.

2. At the end of compiling the program, this error comes up:
```
[35/35] Linking target pingtest.exe
FAILED: pingtest.exe pingtest.pdb
"link"  /MACHINE:x64 /OUT:pingtest.exe pingtest.exe.p/test_pingtest.c.obj "/nologo" "/release" "/nologo" "/DEBUG" "/PDB:pingtest.pdb" "slirp.lib" "ws2_32.lib" "iphlpapi.lib" "/SUBSYSTEM:CONSOLE" "kernel32.lib" "user32.lib" "gdi32.lib" "winspool.lib" "shell32.lib" "ole32.lib" "oleaut32.lib" "uuid.lib" "comdlg32.lib" "advapi32.lib"
LINK : fatal error LNK1181: non è possibile aprire il file di input 'slirp.lib'
ninja: build stopped: subcommand failed.
```
`pingtest.exe` fails to find `slirp.lib` (which is not created). According to @sthibaul, pingtest.exe is just a test and it is not important.
`slirp-0.dll` is created:
![slirp](https://user-images.githubusercontent.com/62349018/168448854-830ac8ef-6314-48fa-80e3-a4f67e85f480.png)

https://gitlab.freedesktop.org/slirp/libslirp/-/issues/60

**Comment by Kappa971** [comment]
Update: the `msvc` branch hasn't been merged with the main branch yet but everything seems to work. Thanks @sthibaul 
```
D:\Downloads\libslirp-msvc>meson setup build -Dpkg_config_path=C:\vcpkg\installed\x64-windows\lib\pkgconfig
The Meson build system
Version: 0.62.1
Source dir: D:\Downloads\libslirp-msvc
Build dir: D:\Downloads\libslirp-msvc\build
Build type: native build
Project name: libslirp
Project version: 4.7.0
C compiler for the host machine: cl (msvc 19.32.31328 "Microsoft (R) C/C++ Optimizing Compiler versione 19.32.31328 per x64")
C linker for the host machine: link link 14.32.31328.0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: C:\Program Files\Meson\pkg-config.EXE (0.29.2)
Run-time dependency glib-2.0 found: YES 2.70.5
Compiler for C supports arguments -Wmissing-prototypes: NO
Compiler for C supports arguments -Wstrict-prototypes: NO
Compiler for C supports arguments -Wredundant-decls: NO
Compiler for C supports arguments -Wundef: NO
Compiler for C supports arguments -Wwrite-strings: NO
Library ws2_32 found: YES
Library iphlpapi found: YES
cl.exe does not actually support gnu standards, and meson will instead demote to the nearest ISO C standard. This may cause compilation to fail.
Check usable header "valgrind/valgrind.h" : NO
Compiler for C supports link arguments -Wl,--version-script,D:\Downloads\libslirp-msvc/src/libslirp.map: NO
Configuring libslirp-version.h using configuration
Build targets in project: 2

libslirp 4.7.0

  User defined options
    pkg_config_path: C:\vcpkg\installed\x64-windows\lib\pkgconfig

Found ninja-1.10.2 at "C:\Program Files\Meson\ninja.EXE"

D:\Downloads\libslirp-msvc>meson compile -C build
ninja: Entering directory `D:/Downloads/libslirp-msvc/build'
[17/35] Compiling C object slirp-0.dll.p/src_misc.c.obj
../src/misc.c(150): warning C4068: l'istruzione pragma 'GCC' è sconosciuta
../src/misc.c(151): warning C4068: l'istruzione pragma 'GCC' è sconosciuta
../src/misc.c(201): warning C4068: l'istruzione pragma 'GCC' è sconosciuta
[33/35] Linking target slirp-0.dll
   Creazione della libreria slirp.lib e dell'oggetto slirp.exp
[35/35] Linking target pingtest.exe
```
![Immagine_2022-05-18_181915](https://user-images.githubusercontent.com/62349018/169661423-2d0e33b3-4dfe-4c6b-b4ed-c0dbd68bb553.png)

**Comment by dhrdlicka** [comment]
The port tracks libslirp releases, so I will update it whenever a new release is out.

**Comment by Kappa971** [comment]
> The port tracks libslirp releases, so I will update it whenever a new release is out.

Okay thanks @dhrdlicka. 
However this is a special case, the port doesn't currently exist for MSVC.

**Comment by JackBoosY** [comment]
So is this issue resolved?

**Comment by Cheney-W** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
