### ISSUE TITLE
[fluidsynth] link to libsndfile

### ISSUE THREAD

**Issue by hmoffatt** [microsoft/vcpkg#24619]
****
The fluidsynth port should link to libsndfile in order to access sf3 sound fonts and support rendering to file. libsndfile is already in the vcpkg repository.

**Comment by FrankXie05** [comment]
@hmoffatt Thanks for posting this issue, the port `fluidsynth` itself has already loaded `sf3`, why should it be linked to the port `libsndfile`? Can you elaborate? :)
https://github.com/FluidSynth/fluidsynth/blob/e63ea6698e15a6f3b6c9eeb5ceae76169bd5ba2d/src/config.cmake#L222

**Comment by hmoffatt** [comment]
@FrankXie05 it doesn't work. Fluidsynth can't load SF3 without libsndfile.

```
$ fluidsynth FluidR3Mono_GM.sf3
FluidSynth runtime version 2.2.6
Copyright (C) 2000-2022 Peter Hanappe and others.
Distributed under the LGPL license.
SoundFont(R) is a registered trademark of Creative Technology Ltd.

fluidsynth: warning: Sound font version is 3.102 but fluidsynth was compiled without support for (v3.x)
fluidsynth: error: Failed to load SoundFont "FluidR3Mono_GM.sf3"
Failed to load the SoundFont FluidR3Mono_GM.sf3
```

This is from the 2021.04.12 vcpkg release.

**Comment by hmoffatt** [comment]
It would be great if the fluidsynth port had a libsndfile feature. libsndfile only needs to be built with the external-libs feature and not the mpeg feature though else it brings in libmp3lame unnecessarily.

**Comment by FrankXie05** [comment]
@hmoffatt `Fluidsynth` added `libsndfile` in a recent update, we shouldn't add some unnecessary files repeatedly. 
https://github.com/FluidSynth/fluidsynth/blob/308cf737967f0ebd5fbdd4369ab31ffd29d75d4f/.azure/azure-pipelines-vcpkg.yml#L104
Related Pull Request: https://github.com/FluidSynth/fluidsynth/pull/892

**Comment by hmoffatt** [comment]
@FrankXie05 that PR is for Fluidsynth's release binaries (see also https://github.com/FluidSynth/fluidsynth/pull/282).

libsndfile has been supported as an optional extra since at least 2010 -- see the initial commit of their CMakeLists.txt here: https://github.com/FluidSynth/fluidsynth/commit/6624f6f2b78a5c16362d3ffa09743f1356e1cda0 

and the SF3 support was merged in 2017: https://github.com/FluidSynth/fluidsynth/pull/183

**Comment by FrankXie05** [comment]
@hmoffatt Thanks for the replies, we'd love to see user participation in improving port functionality, feel free to subbmit an issue or PR. I'm just not sure right now if this is a port bug, I'm verifying. :)

**Comment by hmoffatt** [comment]
Consider this a feature request rather than a bug! I'd be happy to submit a PR.

The change week just be to add the feature, an optional dependency on the libsndfile port, and change the cmake enable flags at build time.
