### ISSUE TITLE
[<libsass> from gtk and gtkmm ] build failure

### ISSUE THREAD

**Issue by DeafMan1983** [microsoft/vcpkg#24617]
**Host Environment**
- OS: Window
- Compiler: VCPKG latest

**To Reproduce**
`./vcpkg install libsass`

```
**Failure logs**
-- Using cached sass-libsass-3.6.5.tar.gz.
-- Extracting source C:/vcpkg/downloads/sass-libsass-3.6.5.tar.gz
-- Applying patch remove_compiler_flags.patch
-- Using source at C:/vcpkg/buildtrees/libsass/src/3.6.5-b48f56cd20.clean
-- Found external ninja('1.10.2').
-- Getting CMake variables for x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:128 (message):
    Command failed: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    Working Directory: C:/vcpkg/buildtrees/libsass/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\vcpkg\buildtrees\libsass\get-cmake-vars-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:383 (vcpkg_execute_required_process)
  scripts/cmake/z_vcpkg_get_cmake_vars.cmake:52 (vcpkg_configure_cmake)
  scripts/cmake/vcpkg_configure_make.cmake:240 (z_vcpkg_get_cmake_vars)
  ports/libsass/portfile.cmake:10 (vcpkg_configure_make)
  scripts/ports.cmake:145 (include)
```

**Additional context**
From patch....log
```
Checking patch GNUmakefile.am...
Checking patch src/GNUmakefile.am...
Applied patch GNUmakefile.am cleanly.
Applied patch src/GNUmakefile.am cleanly.
```
And other logs look empty...

I tried to install gtk and gtkmm because libsass
`vcpkg install libsass:x64-windows --recurse`

Then it throws same "Build failed" Thanks

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Could you please provide the error log: **C:\vcpkg\buildtrees\libsass\get-cmake-vars-x64-windows-out.log**? Is this file also empty?

**Comment by LilyWangLL** [comment]
Sorry I am late, could you install `libsass` again on the new vcpkg? I can't repro this issue locally, since the error log is empty, I have no idea about why this port install failed. And could you please provide your environment information, which version of Visual Studio you use?

**Comment by DeafMan1983** [comment]
Yes it happens before it has failed build and I have restarted Windows 10 and vcpkg has gone error. I am surprised. I don't understand why does vcpkg  build before failure and I have restarted then vcpkg build successful. That's why I can't reproduce. It is gone. Thanks for everything! Can we close issue, if you are trying to reproduce issue?

**Comment by LilyWangLL** [comment]
Yeah, thanks for your reply. I am closing this issue for now.
