### ISSUE TITLE
[taglib] build failure

### ISSUE THREAD

**Issue by complexlogic** [microsoft/vcpkg#24616]
**Host Environment**
- OS: Windows 10 Pro 21H2 x64
- Compiler: Visual Studio 2022, MSVC v143

**To Reproduce**
`./vcpkg install taglib --triplet=x64-windows`

**Failure logs**
```
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:158 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j5
    Working Directory: C:/Users/cstob/Documents/rsgain/vcpkg/buildtrees/taglib/x64-windows-dbg
    See logs for more information:
      C:\Users\cstob\Documents\rsgain\vcpkg\buildtrees\taglib\install-x64-windows-dbg-out.log
      C:\Users\cstob\Documents\rsgain\vcpkg\buildtrees\taglib\install-x64-windows-dbg-err.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:112 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
  ports/taglib/portfile.cmake:19 (vcpkg_cmake_install)
  scripts/ports.cmake:145 (include)


error: building taglib:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+taglib
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[taglib]+Build+error
including:
  package: taglib[core]:x64-windows -> 1.12.0#2
    vcpkg-tool version: 2022-03-30-692785ac944e81417840c6de244fb3e18a4b35eb
    vcpkg-scripts version: a5d6d1451 2022-05-06 (2 days ago)
```

**Additional context**
I built taglib a couple weeks ago with no issue. I'm trying to build again today on a different PC and I get the build failure as shown above. I did some investigation and there haven't been any recent commits on the `taglib` port, but there have been several for its dependency `vcpkg-cmake`. [This one](https://github.com/microsoft/vcpkg/commit/f7866c66d2a4717824cde89786692648c07be01f) in particular looks suspicious as it changed the `vcpkg_execute_build_process` function which is the most recent failure in the stack trace. Not sure how to confirm this is causing the issue.
@Neumann-A 
@BillyONeal 

**Workaround**
For a workaround, I started a new vcpkg root based on the most recent git tag, 2022.04.12.
```
git clone https://github.com/microsoft/vcpkg.git
cd vcpkg
git checkout tags/2022.04.12
```
Then bootstrap and run the `vcpkg install` command, and it successfully builds.

**Comment by Neumann-A** [comment]
Logs? Be aware that all those changes are tested by CI.
It also helps to compare CMake configure lines from the Logs before and after that change. 

For me it works as expected from a clean vcpkg. 
```
Starting package 3/3: taglib:x64-windows
Building package taglib[core]:x64-windows...
-- Using cached taglib-taglib-v1.12.tar.gz.
-- Extracting source G:/vcpkg_common/downloads/taglib-taglib-v1.12.tar.gz
-- Applying patch msvc-disable-deprecated-warnings.patch
-- Using source at E:/vcpkg_folders/master2/buildtrees/taglib/src/v1.12-8b13cd6052.clean
CMake Warning at installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:115 (message):
  PREFER_NINJA has been deprecated in vcpkg_cmake_configure.  Please remove
  it from the portfile!
Call Stack (most recent call first):
  ports/taglib/portfile.cmake:14 (vcpkg_cmake_configure)
  scripts/ports.cmake:145 (include)
-- Found external ninja('1.10.2').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Fixing pkgconfig file: E:/vcpkg_folders/master2/packages/taglib_x64-windows/lib/pkgconfig/taglib.pc
-- Fixing pkgconfig file: E:/vcpkg_folders/master2/packages/taglib_x64-windows/lib/pkgconfig/taglib_c.pc
-- Using cached msys-mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst.
-- Using msys root at G:/vcpkg_common/downloads/tools/msys2/9a1ec3f33446b195
-- Fixing pkgconfig file: E:/vcpkg_folders/master2/packages/taglib_x64-windows/debug/lib/pkgconfig/taglib.pc
-- Fixing pkgconfig file: E:/vcpkg_folders/master2/packages/taglib_x64-windows/debug/lib/pkgconfig/taglib_c.pc
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: G:\vcpkg_common\binary\e1\e119d2f7c113b5d245085e17db517d4b929660506bff78a93e097791016aac05.zip
Installing package taglib[core]:x64-windows...
Elapsed time for package taglib:x64-windows: 1.231 min
```

**Comment by FrankXie05** [comment]
Sorry, I didn't reproduce your problem locally, can you provide your error log? Could you please use the latest vcpkg and try again?
```
      C:\Users\cstob\Documents\rsgain\vcpkg\buildtrees\taglib\install-x64-windows-dbg-out.log
      C:\Users\cstob\Documents\rsgain\vcpkg\buildtrees\taglib\install-x64-windows-dbg-err.log
```
Try steps:
```
1. git clone https://github.com/microsoft/vcpkg
2. cd .\vcpkg\
3. .\bootstrap-vcpkg.bat
4. .\vcpkg.exe install taglib --triplet=x64-windows
```

**Comment by Neumann-A** [comment]
>       C:\Users\cstob\Documents\rsgain\vcpkg\buildtrees\taglib\install-x64-windows-dbg-out.log

also the `config-x64-windows-dbg-out.log` to compare how cmake was configured.

**Comment by complexlogic** [comment]
I looked at the logs, the relevant error message was:
```
ninja: error: manifest 'build.ninja' still dirty after 100 tries
```
After some research I came across [this comment](https://github.com/ninja-build/ninja/issues/1599#issuecomment-617411613). It's an issue related to the system clock being out of sync. Apparently, Ninja has a problem with this for some reason. 

I dual boot with Linux which uses UTC instead of local time for the system clock, and I also recently traveled to a different timezone but didn't update the settings. Not sure which of those was the culprit, but I went into the Windows settings updated the timezone and synced the time and now it builds fine. Not sure why it built successfully with the git tag 2022.04.12 with the clock out of sync. Perhaps some change to the Ninja config?

@Neumann-A I apologize for falsely assuming that the previously mentioned commit was causing this issue and tagging you here.

**Comment by dg0yt** [comment]
> It's an issue related to the system clock being out of sync.  Apparently, Ninja has a problem with this for some reason.

Ninja is designed for speed and simplicity. It is "relying on simple dependencies between file timestamps" i.e. it expects that generated files' timestamps are newer than their sources' timestamps.
