### ISSUE TITLE
[ignition-*] Upstreams are damaged

### ISSUE THREAD

**Issue by BillyONeal** [microsoft/vcpkg#24630]
/cc

* @traversaro
* @ahoarau
* @autoantwort

https://github.com/orgs/ignitionrobotics/repositories , the upstream for all these ports, reports that it has no repositories.

Individual repos are being redirected to @gazebosim .

We probably shouldn't just "fix the SHA and move on" ... what is the path forward for these libraries in our catalog?

Related: https://github.com/microsoft/vcpkg/pull/24618

**Comment by BillyONeal** [comment]
If we don't get someone familiar with these changes upstream I think we should =skip these in `ci.baseline.txt` until a maintainer familiar with the situation is available. I'll prepare that if we have no response by the end of this week.

**Comment by LilyWangLL** [comment]
I found the link of Ignition CMake on GitHub is https://github.com/ignitionrobotics/ign-cmake, should we change the upstream of Ignition CMake to this?

**Comment by traversaro** [comment]
Pinging other users that could be interested in this discussion: @j-rivero @Ace314159 .

**Comment by BillyONeal** [comment]
>I never announced this anywhere as I was not aware that vcpkg had any concept of "mantainer" or similar, differently from other package managers.

It's not a "formal maintainer" kind of thing. More "people we know will care if this is broken and say something about major upstream changes", sort of thing, since the vcpkg team doesn't actually know how to validate that these things build anything that makes sense.

**Comment by traversaro** [comment]
> >I never announced this anywhere as I was not aware that vcpkg had any concept of "mantainer" or similar, differently from other package managers.
> 
> It's not a "formal maintainer" kind of thing. More "people we know will care if this is broken and say something about major upstream changes", sort of thing, since the vcpkg team doesn't actually know how to validate that these things build anything that makes sense.

Yes, that is completely clear, I was just explaining that it was not clear to me how to specify that in the long term I am not be the best person to be the "people we know will care if this is broken and say something about major upstream changes" .

**Comment by j-rivero** [comment]
Hello, @BillyONeal @traversaro: thanks for the ping and the past and present efforts to keep the Ignition (now Gazebo after the last rename) libraries. It would be great if we can keep ignition packages working although the Open Robotics internal resources to help with this effort are limited.

I'm going to ask for help into our public forum so maybe someone from the community can volunteer to help maintaining the libraries here.

**Comment by j-rivero** [comment]
> I would be able to maintain the libraries here since I am actively using these packages for Gazebo.

Awesome Akash! feel free to ping me anytime if we can help you in with any information or change needed. Thanks!

**Comment by traversaro** [comment]
Thanks a lot @Ace314159 ! Feel free to ping me for any problem.

**Comment by BillyONeal** [comment]
OK, in light of the above I'm going to ensure https://github.com/microsoft/vcpkg/pull/24618 fixes all of them and run with that. Thanks folks!
