### ISSUE TITLE
[liburing] Build error

### ISSUE THREAD

**Issue by hros** [microsoft/vcpkg#24631]
**Host Environment**
- OS: Linux - Ubuntu 22.04
- Compiler: gcc version 11.2.0

**To Reproduce**
`./vcpkg install libunifex`

**Failure logs**
-Cut and paste the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.
```
  package: liburing[core]:x64-linux -> 2.0#3
    vcpkg-tool version: 2022-03-09-1affd32f93b299d5a907816c328ca3ededb73a7e
    vcpkg-scripts version: 19033ddfa 2022-05-09 (44 minutes ago)

```
error log:
```
ar: creating liburing.a
ucontext-cp.c:31:23: error: variably modified ‘stack_buf’ at file scope
   31 |         unsigned char stack_buf[SIGSTKSZ];
      |                       ^~~~~~~~~
```

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. This is a upstream bug https://github.com/axboe/liburing/issues/320 and has been fixed in new release of `liburing`, I will submit a PR to update the version of `liburing`.
