### ISSUE TITLE
Amend Documentation to suggest --toolchain over -DCMAKE_TOOLCHAIN_FILE

### ISSUE THREAD

**Issue by rioki** [microsoft/vcpkg#24641]
****

**Is your feature request related to a problem? Please describe.**

I have no idea what the underlying cause is but I spent the better part of the morning trying to get my CMake and vcpkg build work on windows. While following the vcpkg documentation and other sources from the internet use -DCMAKE_TOOLCHAIN_FILE I had no success. By chance I stumbled over the --toolchain option and tried that and it worked.

**Proposed solution**

Suggest --toolchain option for CMake invocation in the documentation.

**Describe alternatives you've considered**

n/t

**Additional context**

CMake appears to have some issues on Windows handling paths, see https://gitlab.kitware.com/cmake/cmake/-/issues/23109

**Comment by autoantwort** [comment]
Or we quote the parameter in all examples

**Comment by JackBoosY** [comment]
According to the `[official document](https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html#id12)`, `-DCMAKE_TOOLCHAIN_FILE` should be same with `--toolchain`.
I agree we should add double quotes to this full value.

**Comment by dg0yt** [comment]
> Suggest --toolchain option for CMake invocation in the documentation.

Note that this parameter requires CMake 3.21. But for user projects, vcpkg supports CMake down to  3.7.2.

> using -DCMAKE_TOOLCHAIN_FILE I had no success

A general source of problems is that this parameter must be used on the very first run of CMake for a clean build directory, before the first `project` command

**Comment by rioki** [comment]
To frame the problem: 

It's not just quoting. The path is simple: "D:/repos/vcpkg/scripts/buildsystems/vcpkg.cmake" and normal path shenanigans should not have been at play. I tried the old and expansive version "-DCMAKE_TOOLCHAIN_FILE:FILEPATH=" and that also worked. 

But the plain "-DCMAKE_TOOLCHAIN_FILE=" does not. This does not change with quotes or not or the direction of the slashes. IMHO this is bug in CMake, but it's frustrating when such a simple and obvious solution exists.

**Comment by JackBoosY** [comment]
@rioki Can you please also report this to the [upstream](https://gitlab.kitware.com/cmake/cmake/-/issues)?

**Comment by rioki** [comment]
I am still looking into the issue and tripple checking I am not the dummy. But once I isolated the issue I will do that.
