### ISSUE TITLE
[libevent] Build error

### ISSUE THREAD

**Issue by anuraghit** [microsoft/vcpkg#24658]
**Host Environment**
- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**
`./vcpkg install xxxx`

**Failure logs**
-Cut and paste the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by JonLiu1993** [comment]
@anuraghit ,Thanks for posting this issue, please follow the template above to fill in your reproduction environment, reproduction steps and error log

**Comment by anuraghit** [comment]
┌──(anu㉿ash)-[~/vcpkg]
└─$ ./vcpkg install libevent
Computing installation plan...
The following packages will be built and installed:
    libevent[core,thread]:x64-linux -> 2.1.12#6
Detecting compiler hash for triplet x64-linux...
Restored 0 packages from /home/anu/.cache/vcpkg/archives in 309.3 us. Use --debug to see more details.
Installing 1/1 libevent:x64-linux...
Building libevent[core,thread]:x64-linux...
-- Using cached libevent-libevent-release-2.1.12-stable.tar.gz.
-- Cleaning sources at /home/anu/vcpkg/buildtrees/libevent/src/.12-stable-cf80f24f51.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/anu/vcpkg/downloads/libevent-libevent-release-2.1.12-stable.tar.gz
-- Applying patch fix-file_path.patch
-- Applying patch fix-LibeventConfig_cmake_in_path.patch
-- Applying patch fix-usage.patch
-- Using source at /home/anu/vcpkg/buildtrees/libevent/src/.12-stable-cf80f24f51.clean
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
CMake Warning at installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:392 (message):
  The following variables are not used in CMakeLists.txt:

      EVENT__MSVC_STATIC_RUNTIME

  Please recheck them and remove the unnecessary options from the
  `vcpkg_cmake_configure` call.

  If these options should still be passed for whatever reason, please use the
  `MAYBE_UNUSED_VARIABLES` argument.
Call Stack (most recent call first):
  ports/libevent/portfile.cmake:30 (vcpkg_cmake_configure)
  scripts/ports.cmake:146 (include)


-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Fixing pkgconfig file: /home/anu/vcpkg/packages/libevent_x64-linux/lib/pkgconfig/libevent.pc
-- Fixing pkgconfig file: /home/anu/vcpkg/packages/libevent_x64-linux/lib/pkgconfig/libevent_core.pc
-- Fixing pkgconfig file: /home/anu/vcpkg/packages/libevent_x64-linux/lib/pkgconfig/libevent_extra.pc
-- Fixing pkgconfig file: /home/anu/vcpkg/packages/libevent_x64-linux/lib/pkgconfig/libevent_pthreads.pc
CMake Error at scripts/cmake/vcpkg_find_acquire_program.cmake:641 (message):
  Could not find pkg-config.  Please install it via your package manager:

      sudo apt-get install pkg-config
Call Stack (most recent call first):
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:198 (vcpkg_find_acquire_program)
  ports/libevent/portfile.cmake:65 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:146 (include)


error: building libevent:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libevent
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[libevent]+Build+error
Include '[libevent] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-05-05-67e17c1782801cf481be9ac0b3765dff3e4bdeb8
    vcpkg-scripts version: 0a1420dc4 2022-05-11 (21 hours ago)
![Screenshot from 2022-05-11 23-43-52](https://user-images.githubusercontent.com/57986981/167989432-a3a3e2a8-d5bf-456c-8262-7846d5c482f2.png)

**Comment by anuraghit** [comment]
also when I'm trying to run this libevent code(hello world).

error -
/usr/bin/ld: /tmp/ccK7l2DS.o: in function `main':
/home/anu/Documents/cpp/test.c:42: undefined reference to `event_base_new'
/usr/bin/ld: /home/anu/Documents/cpp/test.c:51: undefined reference to `evconnlistener_new_bind'
/usr/bin/ld: /home/anu/Documents/cpp/test.c:61: undefined reference to `event_new'
/usr/bin/ld: /home/anu/Documents/cpp/test.c:63: undefined reference to `event_add'
/usr/bin/ld: /home/anu/Documents/cpp/test.c:68: undefined reference to `event_base_dispatch'
/usr/bin/ld: /home/anu/Documents/cpp/test.c:70: undefined reference to `evconnlistener_free'
/usr/bin/ld: /home/anu/Documents/cpp/test.c:71: undefined reference to `event_free'
/usr/bin/ld: /home/anu/Documents/cpp/test.c:72: undefined reference to `event_base_free'
/usr/bin/ld: /tmp/ccK7l2DS.o: in function `listener_cb':
/home/anu/Documents/cpp/test.c:85: undefined reference to `bufferevent_socket_new'
/usr/bin/ld: /home/anu/Documents/cpp/test.c:88: undefined reference to `event_base_loopbreak'
/usr/bin/ld: /home/anu/Documents/cpp/test.c:91: undefined reference to `bufferevent_setcb'
/usr/bin/ld: /home/anu/Documents/cpp/test.c:92: undefined reference to `bufferevent_enable'
/usr/bin/ld: /home/anu/Documents/cpp/test.c:93: undefined reference to `bufferevent_disable'
/usr/bin/ld: /home/anu/Documents/cpp/test.c:95: undefined reference to `bufferevent_write'
/usr/bin/ld: /tmp/ccK7l2DS.o: in function `conn_writecb':
/home/anu/Documents/cpp/test.c:101: undefined reference to `bufferevent_get_output'
/usr/bin/ld: /home/anu/Documents/cpp/test.c:102: undefined reference to `evbuffer_get_length'
/usr/bin/ld: /home/anu/Documents/cpp/test.c:104: undefined reference to `bufferevent_free'
/usr/bin/ld: /tmp/ccK7l2DS.o: in function `conn_eventcb':
/home/anu/Documents/cpp/test.c:119: undefined reference to `bufferevent_free'
/usr/bin/ld: /tmp/ccK7l2DS.o: in function `signal_cb':
/home/anu/Documents/cpp/test.c:130: undefined reference to `event_base_loopexit'
collect2: error: ld returned 1 exit status

code-

#include <string.h>
#include <errno.h>
#include <stdio.h>
#include <signal.h>
#ifndef _WIN32
#include <netinet/in.h>
# ifdef _XOPEN_SOURCE_EXTENDED
#  include <arpa/inet.h>
# endif
#include <sys/socket.h>
#endif

#include <event2/bufferevent.h>
#include <event2/buffer.h>
#include <event2/listener.h>
#include <event2/util.h>
#include <event2/event.h>

static const char MESSAGE[] = "Hello, World!\n";

static const unsigned short PORT = 9995;

static void listener_cb(struct evconnlistener *, evutil_socket_t,
    struct sockaddr *, int socklen, void *);
static void conn_writecb(struct bufferevent *, void *);
static void conn_eventcb(struct bufferevent *, short, void *);
static void signal_cb(evutil_socket_t, short, void *);

int
main(int argc, char **argv)
{
	struct event_base *base;
	struct evconnlistener *listener;
	struct event *signal_event;

	struct sockaddr_in sin = {0};
#ifdef _WIN32
	WSADATA wsa_data;
	WSAStartup(0x0201, &wsa_data);
#endif

	base = event_base_new();
	if (!base) {
		fprintf(stderr, "Could not initialize libevent!\n");
		return 1;
	}

	sin.sin_family = AF_INET;
	sin.sin_port = htons(PORT);

	listener = evconnlistener_new_bind(base, listener_cb, (void *)base,
	    LEV_OPT_REUSEABLE|LEV_OPT_CLOSE_ON_FREE, -1,
	    (struct sockaddr*)&sin,
	    sizeof(sin));

	if (!listener) {
		fprintf(stderr, "Could not create a listener!\n");
		return 1;
	}

	signal_event = evsignal_new(base, SIGINT, signal_cb, (void *)base);

	if (!signal_event || event_add(signal_event, NULL)<0) {
		fprintf(stderr, "Could not create/add a signal event!\n");
		return 1;
	}

	event_base_dispatch(base);

	evconnlistener_free(listener);
	event_free(signal_event);
	event_base_free(base);

	printf("done\n");
	return 0;
}

static void
listener_cb(struct evconnlistener *listener, evutil_socket_t fd,
    struct sockaddr *sa, int socklen, void *user_data)
{
	struct event_base *base = user_data;
	struct bufferevent *bev;

	bev = bufferevent_socket_new(base, fd, BEV_OPT_CLOSE_ON_FREE);
	if (!bev) {
		fprintf(stderr, "Error constructing bufferevent!");
		event_base_loopbreak(base);
		return;
	}
	bufferevent_setcb(bev, NULL, conn_writecb, conn_eventcb, NULL);
	bufferevent_enable(bev, EV_WRITE);
	bufferevent_disable(bev, EV_READ);

	bufferevent_write(bev, MESSAGE, strlen(MESSAGE));
}

static void
conn_writecb(struct bufferevent *bev, void *user_data)
{
	struct evbuffer *output = bufferevent_get_output(bev);
	if (evbuffer_get_length(output) == 0) {
		printf("flushed answer\n");
		bufferevent_free(bev);
	}
}

static void
conn_eventcb(struct bufferevent *bev, short events, void *user_data)
{
	if (events & BEV_EVENT_EOF) {
		printf("Connection closed.\n");
	} else if (events & BEV_EVENT_ERROR) {
		printf("Got an error on the connection: %s\n",
		    strerror(errno));/*XXX win32*/
	}
	/* None of the other events can happen here, since we haven't enabled
	 * timeouts */
	bufferevent_free(bev);
}

static void
signal_cb(evutil_socket_t sig, short events, void *user_data)
{
	struct event_base *base = user_data;
	struct timeval delay = { 2, 0 };

	printf("Caught an interrupt signal; exiting cleanly in two seconds.\n");

	event_base_loopexit(base, &delay);
}

**Comment by anuraghit** [comment]
also when I'm trying to run the hello world program for libevent.

error;-
/usr/bin/ld: /tmp/ccG7H8xG.o: in function `main':
/home/anu/Documents/cpp/test.c:42: undefined reference to `event_base_new'
/usr/bin/ld: /home/anu/Documents/cpp/test.c:51: undefined reference to `evconnlistener_new_bind'
/usr/bin/ld: /home/anu/Documents/cpp/test.c:61: undefined reference to `event_new'
/usr/bin/ld: /home/anu/Documents/cpp/test.c:63: undefined reference to `event_add'
/usr/bin/ld: /home/anu/Documents/cpp/test.c:68: undefined reference to `event_base_dispatch'
/usr/bin/ld: /home/anu/Documents/cpp/test.c:70: undefined reference to `evconnlistener_free'
/usr/bin/ld: /home/anu/Documents/cpp/test.c:71: undefined reference to `event_free'
/usr/bin/ld: /home/anu/Documents/cpp/test.c:72: undefined reference to `event_base_free'
/usr/bin/ld: /tmp/ccG7H8xG.o: in function `listener_cb':
/home/anu/Documents/cpp/test.c:85: undefined reference to `bufferevent_socket_new'
/usr/bin/ld: /home/anu/Documents/cpp/test.c:88: undefined reference to `event_base_loopbreak'
/usr/bin/ld: /home/anu/Documents/cpp/test.c:91: undefined reference to `bufferevent_setcb'
/usr/bin/ld: /home/anu/Documents/cpp/test.c:92: undefined reference to `bufferevent_enable'
/usr/bin/ld: /home/anu/Documents/cpp/test.c:93: undefined reference to `bufferevent_disable'
/usr/bin/ld: /home/anu/Documents/cpp/test.c:95: undefined reference to `bufferevent_write'
/usr/bin/ld: /tmp/ccG7H8xG.o: in function `conn_writecb':
/home/anu/Documents/cpp/test.c:101: undefined reference to `bufferevent_get_output'
/usr/bin/ld: /home/anu/Documents/cpp/test.c:102: undefined reference to `evbuffer_get_length'
/usr/bin/ld: /home/anu/Documents/cpp/test.c:104: undefined reference to `bufferevent_free'
/usr/bin/ld: /tmp/ccG7H8xG.o: in function `conn_eventcb':
/home/anu/Documents/cpp/test.c:119: undefined reference to `bufferevent_free'
/usr/bin/ld: /tmp/ccG7H8xG.o: in function `signal_cb':
/home/anu/Documents/cpp/test.c:130: undefined reference to `event_base_loopexit'
collect2: error: ld returned 1 exit status

code-
'''#include <string.h>
#include <errno.h>
#include <stdio.h>
#include <signal.h>
#ifndef _WIN32
#include <netinet/in.h>
# ifdef _XOPEN_SOURCE_EXTENDED
#  include <arpa/inet.h>
# endif
#include <sys/socket.h>
#endif

#include <event2/bufferevent.h>
#include <event2/buffer.h>
#include <event2/listener.h>
#include <event2/util.h>
#include <event2/event.h>

static const char MESSAGE[] = "Hello, World!\n";

static const unsigned short PORT = 9995;

static void listener_cb(struct evconnlistener *, evutil_socket_t,
    struct sockaddr *, int socklen, void *);
static void conn_writecb(struct bufferevent *, void *);
static void conn_eventcb(struct bufferevent *, short, void *);
static void signal_cb(evutil_socket_t, short, void *);

int
main(int argc, char **argv)
{
	struct event_base *base;
	struct evconnlistener *listener;
	struct event *signal_event;

	struct sockaddr_in sin = {0};
#ifdef _WIN32
	WSADATA wsa_data;
	WSAStartup(0x0201, &wsa_data);
#endif

	base = event_base_new();
	if (!base) {
		fprintf(stderr, "Could not initialize libevent!\n");
		return 1;
	}

	sin.sin_family = AF_INET;
	sin.sin_port = htons(PORT);

	listener = evconnlistener_new_bind(base, listener_cb, (void *)base,
	    LEV_OPT_REUSEABLE|LEV_OPT_CLOSE_ON_FREE, -1,
	    (struct sockaddr*)&sin,
	    sizeof(sin));

	if (!listener) {
		fprintf(stderr, "Could not create a listener!\n");
		return 1;
	}

	signal_event = evsignal_new(base, SIGINT, signal_cb, (void *)base);

	if (!signal_event || event_add(signal_event, NULL)<0) {
		fprintf(stderr, "Could not create/add a signal event!\n");
		return 1;
	}

	event_base_dispatch(base);

	evconnlistener_free(listener);
	event_free(signal_event);
	event_base_free(base);

	printf("done\n");
	return 0;
}

static void
listener_cb(struct evconnlistener *listener, evutil_socket_t fd,
    struct sockaddr *sa, int socklen, void *user_data)
{
	struct event_base *base = user_data;
	struct bufferevent *bev;

	bev = bufferevent_socket_new(base, fd, BEV_OPT_CLOSE_ON_FREE);
	if (!bev) {
		fprintf(stderr, "Error constructing bufferevent!");
		event_base_loopbreak(base);
		return;
	}
	bufferevent_setcb(bev, NULL, conn_writecb, conn_eventcb, NULL);
	bufferevent_enable(bev, EV_WRITE);
	bufferevent_disable(bev, EV_READ);

	bufferevent_write(bev, MESSAGE, strlen(MESSAGE));
}

static void
conn_writecb(struct bufferevent *bev, void *user_data)
{
	struct evbuffer *output = bufferevent_get_output(bev);
	if (evbuffer_get_length(output) == 0) {
		printf("flushed answer\n");
		bufferevent_free(bev);
	}
}

static void
conn_eventcb(struct bufferevent *bev, short events, void *user_data)
{
	if (events & BEV_EVENT_EOF) {
		printf("Connection closed.\n");
	} else if (events & BEV_EVENT_ERROR) {
		printf("Got an error on the connection: %s\n",
		    strerror(errno));/*XXX win32*/
	}
	/* None of the other events can happen here, since we haven't enabled
	 * timeouts */
	bufferevent_free(bev);
}

static void
signal_cb(evutil_socket_t sig, short events, void *user_data)
{
	struct event_base *base = user_data;
	struct timeval delay = { 2, 0 };

	printf("Caught an interrupt signal; exiting cleanly in two seconds.\n");

	event_base_loopexit(base, &delay);
} '''

**Comment by anuraghit** [comment]
I'm getting this now.
how to config and compile it with my code.
also can you send me hello world program for libevent

──(anu㉿ash)-[~/vcpkg]
└─$ ./vcpkg install libevent       
Computing installation plan...
The following packages are already installed:
    libevent[core,thread]:x64-linux -> 2.1.12#6
libevent:x64-linux is already installed
Restored 0 packages from /home/anu/.cache/vcpkg/archives in 1.647 us. Use --debug to see more details.

Total elapsed time: 9.581 ms

libevent provides CMake targets:
    # this is heuristically generated, and may not be correct
    find_package(Libevent CONFIG REQUIRED)
    target_link_libraries(main PRIVATE libevent::core libevent::extra libevent::pthreads)

**Comment by JonLiu1993** [comment]
This is cmake project code, If you have any problem please let me know

CMakeLists:
````
cmake_minimum_required (VERSION 3.8)

project(test)
find_package(Libevent CONFIG REQUIRED)
# Add source to this project's executable.
add_executable (main "CMakeProject42.cpp" "CMakeProject42.h")

target_link_libraries(main PRIVATE libevent::core libevent::extra)
````
CMakeProject42.cpp
````
#include "CMakeProject42.h"

using namespace std;

int main()
{
	cout << "Hello CMake." << endl;
	return 0;
}
````
CMakeProject42.h
````
#pragma once

#include <iostream>
````

**Comment by anuraghit** [comment]
actually, I'm asking for libevent sample code. not cmake...

**Comment by JonLiu1993** [comment]
@anuraghit ,Have your problem solved?

**Comment by anuraghit** [comment]
Ye 👍 thank you
