### ISSUE TITLE
[boost-build] Use correct b2 version instead of boost version

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#24656]
running `./b2 --version `

returns:
```
$ ./b2.exe --version
B2 4.7-git
```

related:
https://repology.org/project/boost-build/related

**Comment by yurybura** [comment]
@Neumann-A I've just built b2 from the original repository:
```
git clone https://github.com/bfgroup/b2.git
cd b2
git checkout 4.9.2
bootstrap.bat
```
Running `.\b2 --version` returns:
```
D:\b2>.\b2 --version
B2 4.9-git
```

This is the standard output of the b2 utility. What do you want to fix in vcpkg?

**Comment by Neumann-A** [comment]
The version in the vcpkg.json

**Comment by Neumann-A** [comment]
@yurybura 
This is wrong:
https://github.com/microsoft/vcpkg/blob/55112eb54a1c4cfaec5dd2592a39cea72f78ed56/ports/boost-build/vcpkg.json#L3

**Comment by yurybura** [comment]
@Neumann-A 
In the `boost-build` port the Boost version tag is used: https://github.com/boostorg/build/releases/tag/boost-1.79.0
I think this is correct version for the `boost-build` port.

**Comment by yurybura** [comment]
> The release tag might be related to the boost version but the details tell another story:
> 
> ```
> [boost-1.80.0](https://github.com/boostorg/build/releases/tag/boost-1.80.0)
> Toggle commit message
> 
> B2 4.9.2
> ```

`boost-build` port is linked to https://github.com/boostorg/build repository.
Please have a look in source code:
https://github.com/microsoft/vcpkg/blob/55112eb54a1c4cfaec5dd2592a39cea72f78ed56/ports/boost-build/portfile.cmake#L9-L19
**In this repository version is 1.80.0**.
Downloading source code from one repository but use version from other is not good idea, isn't it?

**Comment by Neumann-A** [comment]
> In this repository version is 1.80.0

https://github.com/boostorg/build/commit/99742ad614537370686ab488560c1b23c6b4c95b

Why should I care about the tag of the repo?  Shouldn't I care about the version of the tool/project which the repo represents ?

**Comment by yurybura** [comment]
@Neumann-A You can create a separate port linked from https://github.com/bfgroup/b2. You can find an example in VCPKG: `asio` and `boost-asio`. Theoretically, Boost.Build can contain changes not included in the original repository.

**Comment by JackBoosY** [comment]
cc @Cheney-W
