### ISSUE TITLE
Vcpkg A package cannot be installed

### ISSUE THREAD

**Issue by IULOVE** [Microsoft/vcpkg#2465]
PS D:\program\c++\GitHub\vcpkg> .\vcpkg.exe install curl
The following packages will be built and installed:
    curl[core]:x86-windows
  * libssh2[core]:x86-windows
  * openssl[core]:x86-windows
  * zlib[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/4: zlib:x86-windows
Building package zlib:x86-windows...
-- CURRENT_INSTALLED_DIR=D:/program/c++/GitHub/vcpkg/installed/x86-windows
-- DOWNLOADS=D:/program/c++/GitHub/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=D:/program/c++/GitHub/vcpkg/packages/zlib_x86-windows
-- CURRENT_BUILDTREES_DIR=D:/program/c++/GitHub/vcpkg/buildtrees/zlib
-- CURRENT_PORT_DIR=D:/program/c++/GitHub/vcpkg/ports/zlib/.
-- Using cached D:/program/c++/GitHub/vcpkg/downloads/zlib1211.tar.gz
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Applying patch D:/program/c++/GitHub/vcpkg/ports/zlib/cmake_dont_build_more_than_needed.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch D:/program/c++/GitHub/vcpkg/ports/zlib/cmake_dont_build_more_than_needed.patch done
-- Configuring x86-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:44 (message):
    Command failed: D:/program/c++/GitHub/vcpkg/downloads/cmake-3.10.0-win32-x86/bin/cmake.exe;D:/program/c++/GitHub/vcpkg/buildtrees/zlib/src/zlib-1.
2.11;-DSKIP_INSTALL_FILES=ON;-DSKIP_BUILD_EXAMPLES=ON;-DBUILD_SHARED_LIBS=ON;-DCMAKE_CXX_FLAGS= /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP ;-DCMAKE_C
_FLAGS= /DWIN32 /D_WINDOWS /W3 /utf-8 /MP ;-DVCPKG_TARGET_TRIPLET=x86-windows;-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_PACKAGE_RE
GISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON;-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE;-DCMAKE_VERBOSE_MAKEFILE=ON;-DVCPKG_APPLOCA
L_DEPS=OFF;-DCMAKE_TOOLCHAIN_FILE=D:/program/c++/GitHub/vcpkg/scripts/buildsystems/vcpkg.cmake;-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON;-DCMAK
E_CXX_FLAGS_RELEASE=/MD /O2 /Oi /Gy /DNDEBUG /Z7 ;-DCMAKE_C_FLAGS_RELEASE=/MD /O2 /Oi /Gy /DNDEBUG /Z7 ;-DCMAKE_SHARED_LINKER_FLAGS_RELEASE=/DEBUG /IN
CREMENTAL:NO /OPT:REF /OPT:ICF ;-DCMAKE_EXE_LINKER_FLAGS_RELEASE=/DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF ;-G;Ninja;-DCMAKE_BUILD_TYPE=Release;-DCMAKE
_INSTALL_PREFIX=D:/program/c++/GitHub/vcpkg/packages/zlib_x86-windows
    Working Directory: D:/program/c++/GitHub/vcpkg/buildtrees/zlib/x86-windows-rel
    See logs for more information:
      D:\program\c++\GitHub\vcpkg\buildtrees\zlib\config-x86-windows-rel-out.log
      D:\program\c++\GitHub\vcpkg\buildtrees\zlib\config-x86-windows-rel-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:205 (vcpkg_execute_required_process)
  ports/zlib/portfile.cmake:23 (vcpkg_configure_cmake)
  scripts/ports.cmake:72 (include)

Error: Building package zlib:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zlib:x86-windows
  Vcpkg version: 0.0.100-2017-12-27-50baf7db17b8b23df300e48664863030e6d90936

Additionally, attach any relevant sections from the log files above.

[config-x86-windows-rel-err.log](https://github.com/Microsoft/vcpkg/files/1592618/config-x86-windows-rel-err.log)

![qq 20171229134817](https://user-images.githubusercontent.com/14193276/34430378-6eae03b0-ec9f-11e7-8ff6-186ce544c419.png)
This directory is empty.

No other packages can be installed
win7 64 vs2015 up3

**Comment by LarryIII** [comment]
@IULOVE Thanks for your feedback. I installed  curl successfully. Please open a new issue if this is still a problem for you.
