### ISSUE TITLE
Frequency of updates to vcpkg-cmake port

### ISSUE THREAD

**Issue by aizuon** [microsoft/vcpkg#24665]
****

**Is your feature request related to a problem? Please describe.**
Yes. It is so frustrating to see updates to vcpkg-cmake port as a lot of ports that take a really long time to build depend on it. 

**Proposed solution**
In my honest opinion, this port should have a rolling update schedule, maybe updated as the same time as vcpkg tool. 

**Describe alternatives you've considered**
Updating ports one by one with ./vcpkg update xxx which don't depend on vcpkg-cmake tool's update. Or, the core functionality of this port should be divided into subports which are updated less regularly. I can't think of any other solutions to this. 

**Additional context**
vcpkg-cmake is a dependency of ports like qt6, some boost ports, some ports that opencv4 have dependency on, physx and many more.

**Comment by Neumann-A** [comment]
> maybe updated as the same time as vcpkg-tool 

That doesn't affect world rebuilds. 

> Or, the core functionality of this port should be divided into subports which are updated less regularly

That was just done by moving `vcpkg-cmake-get-vars` out of it. 

Consider pinning your vcpkg version If you don't like the constant updates and improvements.

**Comment by JackBoosY** [comment]
We try our best to reduce the modification of ports like `vcpkg-cmake`, but every modification is necessary.
If the functions within it are split into a non-versioned state, dependencies are significantly reduced.
