### ISSUE TITLE
[angle] build failure on master

### ISSUE THREAD

**Issue by talregev** [microsoft/vcpkg#24664]
angle:arm64-windows failed with BUILD_FAILED
https://dev.azure.com/vcpkg/public/_build/results?buildId=71934&view=logs&j=84da4f4a-968a-5b5c-16e9-f444c845396d&t=80e5e0c8-bb3b-5216-9f3f-2618d4e9f3f4

**Comment by talregev** [comment]
Yes, I agree, if we can't reproduce it, we should close this issue, until the next problem. Thank you.

**Comment by talregev** [comment]
@Cheney-W We still have problem with angle on the master. it feel like random. always get an error in different triplets. Can you investigate it? 
https://dev.azure.com/vcpkg/public/_build/results?buildId=72059&view=results

**Comment by Cheney-W** [comment]
I've checked that the files being compiled, the compilation options, and the final result are exactly the same as the VS bug found internally before.

**Comment by talregev** [comment]
@Cheney-W Is it problem only in the CI?

**Comment by Cheney-W** [comment]
I suspect that the cache is not cleared to cause.

**Comment by talregev** [comment]
How we can clear the cache from the ci?
