### ISSUE TITLE
Folly usage error and its dependence on Double-Conversion

### ISSUE THREAD

**Issue by navidR** [Microsoft/vcpkg#2467]
There is something funny going on when using folly (which is installed by vcpkg) and it seems this port has not been tested **at all**. Folly tries to use its own Find[package_name].cmake 's which are available [here](https://github.com/facebook/folly/tree/master/CMake). But the problem is vcpkg installs double-conversion with the name of "double-conversion" and there for only "double-conversionConfig.cmake" is available. 

The error happens here (at ..\vcpkg\installed\x64-windows\share\folly\folly-config.cmake) : 

![folly-double-conversion](https://user-images.githubusercontent.com/3811601/34442693-0c255c72-ecd9-11e7-9eb9-3cb9ed00b595.PNG)
```
CMake Error at C:/Users/navid/AppData/Roaming/vcpkg/scripts/buildsystems/vcpkg.cmake:222 (_find_package):
No "FindDoubleConversion.cmake" found in CMAKE_MODULE_PATH.
Call Stack (most recent call first):
   C:/Users/navid/AppData/Roaming/vcpkg/installed/x64-windows/share/folly/folly-config.cmake(14): (find_package)
   C:/Users/navid/AppData/Roaming/vcpkg/scripts/buildsystems/vcpkg.cmake(222): (_find_package)
   CMakeLists.txt(15): (find_package)
```

First Solution: Since there is double-conversion in vcpkg already, I think patching follys' CMakeLists.txt to force it to use double-conversion would be a good solution.

Temporary fix : 
changed line 14 to : 
```
find_package(double-conversion CONFIG REQUIRED)
```

and 34 to : 
```
include(${CMAKE_CURRENT_LIST_DIR}/folly-targets.cmake)
```

**Comment by KindDragon** [comment]
I don't use `find-package(Folly)`, only some headers from Folly

**Comment by Cheney-W** [comment]
@navidR , I installed this port successfully with latest vcpkg:2018.11.23-nohash and VS2017 15.9.7, so closed this issue.
