### ISSUE TITLE
[qtbase] build failure

### ISSUE THREAD

**Issue by EVNII** [microsoft/vcpkg#24686]
**Host Environment**
- OS: x64-windows
- Compiler: msvc

**To Reproduce**
`./vcpkg install qtbase`

**Failure logs**
```plain text
Computing installation plan...
The following packages will be built and installed:
  * qtbase[brotli,concurrent,core,dbus,default-features,doubleconversion,freetype,gui,harfbuzz,icu,jpeg,network,openssl,pcre2,png,sql,sql-psql,sql-sqlite,testlib,widgets,zstd]:x64-windows -> 6.3.0#1
    qtbase[brotli,concurrent,core,dbus,default-features,doubleconversion,freetype,gui,harfbuzz,icu,jpeg,network,openssl,pcre2,png,sql,sql-psql,sql-sqlite,testlib,widgets,zstd]:x86-windows -> 6.3.0#1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Detecting compiler hash for triplet x86-windows...
Restored 0 packages from C:\Users\MSII\AppData\Local\vcpkg\archives in 257.3 us. Use --debug to see more details.
Installing 1/2 qtbase:x64-windows...
Building qtbase[brotli,concurrent,core,dbus,default-features,doubleconversion,freetype,gui,harfbuzz,icu,jpeg,network,openssl,pcre2,png,sql,sql-psql,sql-sqlite,testlib,widgets,zstd]:x64-windows...
-- Using cached C:/libsys/vcpkg/downloads/qtbase-0668a36d2804b300010d874f5ff4073c25c2784c.tar.gz
-- Extracting source C:/libsys/vcpkg/downloads/qtbase-0668a36d2804b300010d874f5ff4073c25c2784c.tar.gz
-- Applying patch allow_outside_prefix.patch
-- Applying patch clang-cl_source_location.patch
-- Applying patch config_install.patch
-- Applying patch fix_cmake_build.patch
-- Applying patch harfbuzz.patch
-- Applying patch fix_egl.patch
-- Applying patch env.patch
-- Applying patch dont_force_cmakecache_latest.patch
-- Using source at C:/libsys/vcpkg/buildtrees/qtbase/src/3c25c2784c-ddb6944668.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:158 (message):
    Command failed: C:/libsys/vcpkg/downloads/tools/cmake-3.22.2-windows/cmake-3.22.2-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j13
    Working Directory: C:/libsys/vcpkg/buildtrees/qtbase/x64-windows-dbg
    See logs for more information:
      C:\libsys\vcpkg\buildtrees\qtbase\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:112 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
  ports/qtbase/cmake/qt_install_submodule.cmake:305 (vcpkg_cmake_install)
  ports/qtbase/portfile.cmake:259 (qt_install_submodule)
  scripts/ports.cmake:146 (include)


error: building qtbase:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+qtbase
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[qtbase]+Build+error
Include '[qtbase] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-05-05-67e17c1782801cf481be9ac0b3765dff3e4bdeb8
    vcpkg-scripts version: bae8f8c7d 2022-05-11 (20 hours ago)


```
Log File: [install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/8682022/install-x64-windows-dbg-out.log)

**Comment by Neumann-A** [comment]
Error:
`LINK : fatal error LNK1168: cannot open Qt6\plugins\platforms\qdirect2dd.dll for writing`

Did you run out of HDD space?

**Comment by EVNII** [comment]
> 

I have 140 GB free memory left. I don't think I run out of. ( I will free more memory, and try again to see if this problem can be solved.)

**Comment by EVNII** [comment]
> Error: `LINK : fatal error LNK1168: cannot open Qt6\plugins\platforms\qdirect2dd.dll for writing`
> 
> Did you run out of HDD space?

I have 140 GB free memory left. I don't think I run out of. ( I will free more memory, and try again to see if this problem can be solved.)

**Comment by Cheney-W** [comment]
I could install qtbase successfully with vcpkg 2022-05-05-67e17c1782801cf481be9ac0b3765dff3e4bdeb8 and VS2019 16.11.4.

**Comment by Neumann-A** [comment]
The other possibility is antivirus acting up.

**Comment by EVNII** [comment]
![image](https://user-images.githubusercontent.com/19518187/168307760-602b6757-bdaa-45b0-83c9-158615fe597f.png)
is there any other possibility? I have turned off the protection in Windows Security.

**Comment by Neumann-A** [comment]
How many logical cores do you have? maybe it is too fast for the FS to catch up.

**Comment by EVNII** [comment]
12 Logical Cores. i7 8750H

**Comment by EVNII** [comment]
I update vcpkg, and try it again. And I get more detail error message in Chinese:
> mt.exe : general error c101008d: Failed to write the updated manifest to the resource of file "bin\Qt6Core.dll". 另一个程序正在使用此文件，进程无法访问。

in English by Google Translate:
> mt.exe : general error c101008d: Failed to write the updated manifest to the resource of file "bin\Qt6Core.dll".  This file is in use by another program and cannot be accessed by the process.

I don't know what process is using it, and I have turned off the antivirus(I probably still use the file, even I turn off). Or is there any way to check which process is using it? 

[install-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/8736032/install-x64-windows-rel-out.log)

**Comment by EVNII** [comment]
I finally figured it out, it is a rogue software called "alibabaprotect" and uses the .dll file.
