### ISSUE TITLE
[brotli] "brotli_x86-windows-static/debug/share/unofficial-brotli'   does not exist

### ISSUE THREAD

**Issue by ScottLangham** [microsoft/vcpkg#24682]
**Host Environment**
- OS: Windows
- Compiler: Visual Studio 16.11.13

**To Reproduce**
```
git clone https://github.com/Microsoft/vcpkg
    cd vcpkg
    .\bootstrap-vcpkg.bat
    .\vcpkg integrate install
    .\vcpkg install cpprestsdk:$(Platform)-windows-static
```
It also fails with the same error if I try to build with `.\vcpkg install cpprestsdk:x86-windows` which I believe is a supported triplet.

**Failure logs**
```
D:\dev\vcpkg master>    .\vcpkg install cpprestsdk:x86-windows-static
Computing installation plan...
The following packages will be built and installed:
  * brotli[core]:x86-windows-static -> 1.0.9#2
    cpprestsdk[brotli,compression,core,default-features]:x86-windows-static -> 2.10.18#1
  * vcpkg-cmake[core]:x64-windows -> 2022-05-10
  * vcpkg-cmake-config[core]:x64-windows -> 2022-02-06
  * zlib[core]:x86-windows-static -> 1.2.12#1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x86-windows-static...
Detecting compiler hash for triplet x64-windows...
Restored 0 packages from C:\Users\scott.langham\AppData\Local\vcpkg\archives in 617.3 us. Use --debug to see more details.
Installing 1/5 brotli:x86-windows-static...
Building brotli[core]:x86-windows-static...
-- Using community triplet x86-windows-static. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: D:\dev\vcpkg\triplets\community\x86-windows-static.cmake
-- Using cached google-brotli-e61745a6b7add50d380cfd7d3883dd6c62fc2c71.tar.gz.
-- Cleaning sources at D:/dev/vcpkg/buildtrees/brotli/src/6c62fc2c71-7c6c2710e9.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/dev/vcpkg/downloads/google-brotli-e61745a6b7add50d380cfd7d3883dd6c62fc2c71.tar.gz
-- Applying patch install.patch
-- Applying patch fix-arm-uwp.patch
-- Applying patch pkgconfig.patch
-- Applying patch fix-ios.patch
-- Using source at D:/dev/vcpkg/buildtrees/brotli/src/6c62fc2c71-7c6c2710e9.clean
-- Found external ninja('1.10.2').
-- Configuring x86-windows-static
-- Building x86-windows-static-dbg
-- Building x86-windows-static-rel
CMake Error at scripts/cmake/vcpkg_fixup_cmake_targets.cmake:140 (message):

  'D:/dev/vcpkg/packages/brotli_x86-windows-static/debug/share/unofficial-brotli'
  does not exist.
Call Stack (most recent call first):
  ports/brotli/portfile.cmake:25 (vcpkg_fixup_cmake_targets)
  scripts/ports.cmake:146 (include)


error: building brotli:x86-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+brotli
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[brotli]+Build+error
Include '[brotli] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-05-05-67e17c1782801cf481be9ac0b3765dff3e4bdeb8
    vcpkg-scripts version: bae8f8c7d 2022-05-11 (17 hours ago)
```

**Additional context**
It works on my colleagues machine. I haven't been able to work out what the difference is.
I've tried:
  * blowing the `vcpkg` repo folder and `%LOCALAPPDATA%\vcpkg\archives` away and starting fresh
  * creating the missing folder manually (it disappears when I run `install` again).
  * trying older commits of vcpkg

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. Could you please remove the following files and directory and rebuild `brotli` again?
```
D:\dev\vcpkg\downloads\google-brotli-e61745a6b7add50d380cfd7d3883dd6c62fc2c71.tar.gz
D:\dev\vcpkg\buildtrees\brotli\src
```
And please make sure the directory `D:/dev/vcpkg/packages/brotli_x86-windows-static/debug/share/unofficial-brotli` is not occupied by any process.

**Comment by ScottLangham** [comment]
I can try.
* The `tar.gz` file already does not exist
* I have deleted the `src` folder
* The `unofficial-brotli`  folder does not exist, so I presume it cannot be occupied by any process.

**Comment by ScottLangham** [comment]
I tried to ProcMon it. The only process that touches the folder `D:\dev\vcpkg\packages\brotli_x86-windows-static\debug\share\unofficial-brotli` is cmake. I presume that's immediately before the build fails because it doesn't exist. cmake runs with this command line:

`"D:\dev\vcpkg\downloads\tools\cmake-3.22.2-windows\cmake-3.22.2-windows-i386\bin\cmake.exe" -DALL_FEATURES= -DCURRENT_PORT_DIR=D:/dev/vcpkg/ports/brotli -D_HOST_TRIPLET=x64-windows -DFEATURES=core -DPORT=brotli -DVCPKG_USE_HEAD_VERSION=0 -D_VCPKG_DOWNLOAD_TOOL=BUILT_IN -D_VCPKG_EDITABLE=0 -D_VCPKG_NO_DOWNLOADS=0 -DZ_VCPKG_CHAINLOAD_TOOLCHAIN_FILE=D:/dev/vcpkg/scripts/toolchains/windows.cmake -DCMD=BUILD -DDOWNLOADS=D:/dev/vcpkg/downloads -DTARGET_TRIPLET=x86-windows-static -DTARGET_TRIPLET_FILE=D:/dev/vcpkg/triplets/community/x86-windows-static.cmake -DVCPKG_BASE_VERSION=2022-05-05 -DVCPKG_CONCURRENCY=13 -DVCPKG_PLATFORM_TOOLSET=v142 -DGIT=C:/Users/scott.langham/OneDrive/Scripts/git.bat -DVCPKG_ROOT_DIR=D:/dev/vcpkg -DPACKAGES_DIR=D:/dev/vcpkg/packages -DBUILDTREES_DIR=D:/dev/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=D:/dev/vcpkg/installed -DDOWNLOADS=D:/dev/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "D:\dev\vcpkg\scripts\ports.cmake"`

Also, I notice the script that raises the error: "D:\dev\vcpkg\scripts\cmake\vcpkg_fixup_cmake_targets.cmake" says at the top that it is deprecated.

**Comment by LilyWangLL** [comment]
[brotli.zip](https://github.com/microsoft/vcpkg/files/8685889/brotli.zip)
Could you use the portfile.cmake and vcpkg.json in this zip instead you locally files, and install `brotli` again? I changed the depracted function `vcpkg_fixup_cmake_targets`.

**Comment by ScottLangham** [comment]
Hi, thanks, I've tried those new files. The output was a little bit different, but still ended in the same error with the same folder missing.

```
D:\dev\vcpkg> .\vcpkg install brotli
Computing installation plan...
The following packages will be built and installed:
    brotli[core]:x86-windows -> 1.0.9#2
  * vcpkg-cmake[core]:x64-windows -> 2022-05-10
  * vcpkg-cmake-config[core]:x64-windows -> 2022-02-06
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Detecting compiler hash for triplet x86-windows...
Restored 0 packages from C:\Users\scott.langham\AppData\Local\vcpkg\archives in 1.304 ms. Use --debug to see more details.
Installing 1/3 vcpkg-cmake:x64-windows...
Building vcpkg-cmake[core]:x64-windows...
-- Installing: D:/dev/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake
-- Installing: D:/dev/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake
-- Installing: D:/dev/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake
-- Installing: D:/dev/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg-port-config.cmake
-- Installing: D:/dev/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/copyright
-- Performing post-build validation
-- Performing post-build validation done
A suitable version of 7zip was not found (required v21.7.0). Downloading portable 7zip v21.7.0...
Downloading 7zip...
  https://www.7-zip.org/a/7z2107-extra.7z -> D:\dev\vcpkg\downloads\7z2107-extra.7z
Extracting 7zip...
Stored binary cache: C:\Users\scott.langham\AppData\Local\vcpkg\archives\da\dae09e4b66969d74c0895988f4f32c31c47c815f062bb052557e08ced51dbf27.zip
Elapsed time to handle vcpkg-cmake:x64-windows: 1.409 s
Installing 2/3 vcpkg-cmake-config:x64-windows...
Building vcpkg-cmake-config[core]:x64-windows...
-- Installing: D:/dev/vcpkg/packages/vcpkg-cmake-config_x64-windows/share/vcpkg-cmake-config/vcpkg_cmake_config_fixup.cmake
-- Installing: D:/dev/vcpkg/packages/vcpkg-cmake-config_x64-windows/share/vcpkg-cmake-config/vcpkg-port-config.cmake
-- Installing: D:/dev/vcpkg/packages/vcpkg-cmake-config_x64-windows/share/vcpkg-cmake-config/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\scott.langham\AppData\Local\vcpkg\archives\56\56198a16b30a6d2f0f2f90c65ab146a75a0ce59a7606795ccf04b6b8f22dc7f7.zip
Elapsed time to handle vcpkg-cmake-config:x64-windows: 300.7 ms
Installing 3/3 brotli:x86-windows...
Building brotli[core]:x86-windows...
-- Using cached google-brotli-e61745a6b7add50d380cfd7d3883dd6c62fc2c71.tar.gz.
-- Cleaning sources at D:/dev/vcpkg/buildtrees/brotli/src/6c62fc2c71-7c6c2710e9.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/dev/vcpkg/downloads/google-brotli-e61745a6b7add50d380cfd7d3883dd6c62fc2c71.tar.gz
-- Applying patch install.patch
-- Applying patch fix-arm-uwp.patch
-- Applying patch pkgconfig.patch
-- Applying patch fix-ios.patch
-- Using source at D:/dev/vcpkg/buildtrees/brotli/src/6c62fc2c71-7c6c2710e9.clean
-- Found external ninja('1.10.2').
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
CMake Error at installed/x64-windows/share/vcpkg-cmake-config/vcpkg_cmake_config_fixup.cmake:135 (message):
  'D:/dev/vcpkg/packages/brotli_x86-windows/debug/share/unofficial-brotli'
  does not exist.
Call Stack (most recent call first):
  ports/brotli/portfile.cmake:25 (vcpkg_cmake_config_fixup)
  scripts/ports.cmake:146 (include)


error: building brotli:x86-windows failed with: BUILD_FAILED
```

**Comment by ScottLangham** [comment]
I've been trying to compare my system with my colleagues (that works). We both deleted the `vcpkg` repo and got rid of the `%LOCALAPPDATA%\vcpkg`, cloned again and tried to run `.\vcpkg install brotli`.

I've attached our build out.log files. At the end where it says `-- Installing:`, the broken one installs `brotli.exe` from `debug\bin\brotli.exe`. On the working system its different and is from `debug\tools\brotli\brotli.exe`

And where the working system says `-- Installing: D:/Source/Temp/brot2/vcpkg/packages/brotli_x86-windows/debug/share/unofficial-brotli/unofficial-brotli-config.cmake`  the broken one says `-- Installing: D:/dev/vcpkg/packages/brotli_x86-windows/debug/lib/brotlienc-static.lib`.  The broken log.out doesn't mention `unofficial-brotli` at all.

[working install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/8686441/working.install-x86-windows-dbg-out.log)
[broken install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/8686442/broken.install-x86-windows-dbg-out.log)

**Comment by dg0yt** [comment]
It looks like the broken build lacks `ports\brotli\install.patch`.

**Comment by dg0yt** [comment]
> It looks like the broken build lacks `ports\brotli\install.patch`.

... and this would be very strange, because the source dirname (6c62fc2c71-7c6c2710e9.clean) identifies the same configuration.

**Comment by LilyWangLL** [comment]
@ScottLangham Could you also please provide the release log file **install-x86-windows-rel-out.log** on broken machine? I found the broken debug log doesn't have these message in the end of log. 
```
-- Installing: D:/Source/Temp/brot2/vcpkg/packages/brotli_x86-windows/debug/share/unofficial-brotli/unofficial-brotli-config.cmake
-- Installing: D:/Source/Temp/brot2/vcpkg/packages/brotli_x86-windows/debug/share/unofficial-brotli/unofficial-brotli-config-debug.cmake
```
This show the broken vcpkg doesn't do the following codes in _${SOURCE_PATH}/CMakeLists.txt_.
```
install(EXPORT brotli FILE unofficial-brotli-config.cmake NAMESPACE unofficial::brotli:: DESTINATION share/unofficial-brotli)
```

**Comment by LilyWangLL** [comment]
And did you install other ports have the same error, does this error only exist when instlling `brotli`?

**Comment by ScottLangham** [comment]
`cpprest` is the first vcpkg I have ever tried, and it fails with this `brotli` error.

I have randomly picked some other packages to install and they appear to build successfully.

**Comment by LilyWangLL** [comment]
Yeah, the patches apply failed on your vcpkg, did you install git on your machine? Could you use command on vcpkg window?

**Comment by LilyWangLL** [comment]
Yeah, these patches applied failed on your vcpkg, did you install git on your machine?

**Comment by ScottLangham** [comment]
I've extracted the environment variables from the running cmake. The PATH variable has a different value to what's in my system environment variables. I'm new to cmake. I don't know where its getting its PATH env variable from.

**Comment by dg0yt** [comment]
In any case, this should trigger a vcpkg error immediately in the patching step, not in the build step. This is a vcpkg bug.

**Comment by JackBoosY** [comment]
Can you please add an extra option `--debug` to the install command then provide the output?

**Comment by ScottLangham** [comment]
[brotli stdout.txt](https://github.com/microsoft/vcpkg/files/8729275/brotli.stdout.txt)
[config-x86-windows-out.log](https://github.com/microsoft/vcpkg/files/8729286/config-x86-windows-out.log)
[install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/8729289/install-x86-windows-dbg-out.log)
[install-x86-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/8729290/install-x86-windows-rel-out.log)
[patch-x86-windows-0-err.log](https://github.com/microsoft/vcpkg/files/8729292/patch-x86-windows-0-err.log)
[stdout-x86-windows.log](https://github.com/microsoft/vcpkg/files/8729294/stdout-x86-windows.log)
[x86-windows.vcpkg_abi_info.txt](https://github.com/microsoft/vcpkg/files/8729297/x86-windows.vcpkg_abi_info.txt)
From `D:\dev\vcpkg\buildtrees\brotli\x86-windows-dbg\CMakeFiles`
[CMakeError.log](https://github.com/microsoft/vcpkg/files/8729358/CMakeError.log)
[CMakeOutput.log](https://github.com/microsoft/vcpkg/files/8729360/CMakeOutput.log)
[TargetDirectories.txt](https://github.com/microsoft/vcpkg/files/8729361/TargetDirectories.txt)

**Comment by JackBoosY** [comment]
The reason is 
```cmake
include(CheckCSourceCompiles)
check_c_source_compiles(
  "#if defined(__EMSCRIPTEN__)
   int main() {return 0;}
   #endif"
  BROTLI_EMSCRIPTEN
)
if (BROTLI_EMSCRIPTEN)
  message("-- Compiler is EMSCRIPTEN")
else()
  message("-- Compiler is not EMSCRIPTEN")
endif()
```
BROTLI_EMSCRIPTEN is false.

**Comment by dg0yt** [comment]
> The reason is
> ...
> BROTLI_EMSCRIPTEN is false.

That's not the reason. `BROTLI_EMSCRIPTEN` must be false for x86-windows.

Remember, we are looking for the reason for:

> ~~~
> 'git.exe' is not recognized as an internal or external command,
> operable program or batch file.
> ~~~

And this is from the debug trace:
~~~
[DEBUG] Found path: C:\Users\scott.langham\OneDrive\Scripts\git.bat
[DEBUG] Found path: C:\Program Files\Git\cmd\git.exe
[DEBUG] CreateProcessW("C:\Users\scott.langham\OneDrive\Scripts\git.bat" --version)
[DEBUG] ReadFile() finished with GetLastError(): 109
...
[DEBUG] CreateProcessW("D:\dev\vcpkg\downloads\tools\cmake-3.22.2-windows\cmake-3.22.2-windows-i386\bin\cmake.exe" -DCURRENT_PORT_DIR=D:/dev/vcpkg/scripts/detect_compiler -DCURRENT_BUILDTREES_DIR=D:/dev/vcpkg/buildtrees/detect_compiler -DCURRENT_PACKAGES_DIR=D:/dev/vcpkg/packages/detect_compiler_x86-windows -D_HOST_TRIPLET=x86-windows -DCMD=BUILD -DDOWNLOADS=D:/dev/vcpkg/downloads -DTARGET_TRIPLET=x86-windows -DTARGET_TRIPLET_FILE=D:/dev/vcpkg/triplets/x86-windows.cmake -DVCPKG_BASE_VERSION=2022-05-05 -DVCPKG_CONCURRENCY=13 -DVCPKG_PLATFORM_TOOLSET=v142 -DGIT=C:/Users/scott.langham/OneDrive/Scripts/git.bat -DVCPKG_ROOT_DIR=D:/dev/vcpkg -DPACKAGES_DIR=D:/dev/vcpkg/packages -DBUILDTREES_DIR=D:/dev/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=D:/dev/vcpkg/installed -DDOWNLOADS=D:/dev/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "D:\dev\vcpkg\scripts\ports.cmake")
...
[DEBUG] CreateProcessW("C:\Users\scott.langham\OneDrive\Scripts\git.bat" "--git-dir=D:\dev\vcpkg\.git" "--work-tree=D:\dev\vcpkg\.git" -c core.autocrlf=false show "--pretty=format:%h %cd (%cr)" -s --date=short HEAD)
[DEBUG] ReadFile() finished with GetLastError(): 109
~~~

So vcpkg doesn't pick the `git.exe` but the `git.bat`.
And for Windows, `vcpkg.exe` cleans the environment before building the port. I guess that `C:\Program Files\Git\cmd` is no longer in `PATH` (and not in `CMAKE_PROGRAM_PATH`) when CMake looks for `git.exe`.

**Comment by JackBoosY** [comment]
Did you use `VCPKG_FORCE_SYSTEM_BINARIES` ?

**Comment by ScottLangham** [comment]
@JackBoosY I haven't done anything with `VCPKG_FORCE_SYSTEM_BINARIES`

**Comment by ScottLangham** [comment]
@dg0yt I renamed `git.bat` and the build has worked.

Yes, when I looked at cmake.exe's environment block using Process Explorer, it did not have `C:\Program Files\Git\cmd` in the `PATH` environment variable.

I found the `git.bat` online somewhere, it forwards to git.exe and then updates my cmd prompt to include the name of the current branch. With `git.bat` present, other ports built without issue. I use Windows Terminal all the time now instead of cmd prompt and no longer need `git.bat`, so removing/renaming that is a sufficient solution for me.

It would be nice if the brotli build was resistant to `git.bat` existing.

Thanks for your help.

**Comment by ScottLangham** [comment]
@dg0yt I renamed `git.bat` and the build has worked.

Yes, when I looked at cmake.exe's environment block using Process Explorer, it did not have `C:\Program Files\Git\cmd` in the `PATH` environment variable.

I found the `git.bat` online somewhere, it forwards to git.exe and then updates my cmd prompt to include the name of the current branch. With `git.bat` present, other ports built without issue. I use Windows Terminal all the time now instead of cmd prompt and no longer need `git.bat`, so removing/renaming that is a sufficient solution for me.

It would be nice if the brotli build was resistant to `git.bat` existing.

Thanks for your help.

**Comment by JackBoosY** [comment]
Trying to understand why `git.bat` was choosen.

**Comment by JackBoosY** [comment]
It's because:
https://github.com/microsoft/vcpkg-tool/blob/fb99b59387aa41e50abe0ecaafaa8ec050b59661/src/vcpkg/base/files.cpp#L3286-L3288
```cpp
...
        virtual std::vector<Path> find_from_PATH(StringView name) const override
        {
#if defined(_WIN32)
            static constexpr StringLiteral EXTS[] = {".cmd", ".exe", ".bat"};
#else  // ^^^ _WIN32 // !_WIN32 vvv
...
```
If `git.bat` exists in a path in the environment variable `PATH`, it will be added to the pre-selection list, and the git command will be executed to confirm whether it can be called normally.

But it is inconsistent in the subsequent cmake process:
https://github.com/microsoft/vcpkg/blob/7e3dcf74e37034eea358934a90a11d618520e139/scripts/cmake/z_vcpkg_apply_patches.cmake#L38-L43
cmake will look for git according to the suffix corresponding to the system. If not found, the patch application will fail.

@BillyONeal I think we need to pass GIT_EXECUTABLE to cmake to avoid inconsistent behavior of c++ part with cmake part?

**Comment by JackBoosY** [comment]
> it did not have C:\Program Files\Git\cmd in the PATH environment variable.

```
[DEBUG] Found path: C:\Users\scott.langham\OneDrive\Scripts\git.bat
[DEBUG] Found path: C:\Program Files\Git\cmd\git.exe
```
No idea why git.exe was found even if this path isn't included in PATH.

**Comment by dg0yt** [comment]
I think the bug is really inside `git.bat`: 
I guess that it prints the error message but doesn't return an error result when it can't run `git.exe`.

1. `vcpkg.exe` finds and runs `git.bat` when it looks for git alternatives.
   - `git.bat` finds `git.exe` via `PATH` and runs it.
   - `vcpkg.exe` is happy.
2. `vcpkg.exe` cleans the environment (incl. `PATH`) and runs CMake, passing the path to `git.bat` via the `GIT` CMake input variable.
3. With `GIT` set, the CMake scripts use `git.bat` instead acquiring any other version.
   However, when it is actually used in `vcpkg_apply_patches`, it no longer finds `git.exe` via the `PATH`.
   But it just doesn't signal this error.
   So the build continues with unpatched sources.

Note that most ports don't need to `git` to fetch sources, so the error is really hidden.
One would need to clean `PATH` also when testing the found git program in the first step.

**Comment by ScottLangham** [comment]
Yes, here is the contents of `git.bat`

```bat
@echo off
git.exe %*
set GITBRANCH=
for /f %%I in ('git.exe rev-parse --abbrev-ref HEAD 2^> NUL') do set GITBRANCH=%%I

if "%GITBRANCH%" == "" (
  prompt $P$G 
) else (
    prompt $P $E[32;7;32;47m%GITBRANCH%$E[0m$G
)
```

**Comment by dg0yt** [comment]
That's it. The git error code is blured by extra commands. Ever line after `git.exe` would need to be inside `if not errorlevel 1 ( ... )`.

**Comment by BillyONeal** [comment]
> `vcpkg.exe` finds and runs `git.bat` when it looks for git alternatives.

This seems like the actual bug

**Comment by JackBoosY** [comment]
I don't think we should find `git.bat`, the only git instance we need is the executable.
