### ISSUE TITLE
[curl] update to 7.83.1

### ISSUE THREAD

**Issue by voltagex** [microsoft/vcpkg#24690]
Library name: curl

New version number: 7.83.1

https://curl.se/changes.html

https://daniel.haxx.se/blog/2022/05/11/curl-7-83-1-it-burns/

Contains security updates

**Comment by JonLiu1993** [comment]
@voltagex , Thanks for posting this issue, curl have updated to the latest version 7.83.1 by the pr #24690. please use command "git pull" get the latest version
