### ISSUE TITLE
-mfloat-abi=hard or -mfloat-abi=softfp on triple arm-linux ?

### ISSUE THREAD

**Issue by aphage** [microsoft/vcpkg#24693]
[-mfloat-abi=hard or -mfloat-abi=softfp on triple arm-linux ?](https://github.com/microsoft/vcpkg/discussions/24692)

**Comment by JackBoosY** [comment]
cc @xieyubo Is it valuable?

**Comment by xieyubo** [comment]
I think it depends on the compiler flag used by different packages. If packet doesn't specify, it depends on the compiler and whether you use cross compiling. If you don't use cross compiling, compiler will detect your host (target) by default. If you use cross compiling, it depends on your cross compiling tool. E.g. if your cross compiler is `gcc-arm-linux-gnueabihf` I think it uses `-mfloat-abi=hard`. If your cross compiler is `gcc-arm-linux-gnueabi`, I think it uses `-mfloat-abi=soft`.

**Comment by aphage** [comment]
> I think it depends on the compiler flag used by different packages. If packet doesn't specify, it depends on the compiler and whether you use cross compiling. If you don't use cross compiling, compiler will detect your host (target) by default. If you use cross compiling, it depends on your cross compiling tool. E.g. if your cross compiler is `gcc-arm-linux-gnueabihf` I think it uses `-mfloat-abi=hard`. If your cross compiler is `gcc-arm-linux-gnueabi`, I think it uses `-mfloat-abi=soft`.

`./vcpkg install glog --triplet=arm-linux`

What compiler is the default?

**Comment by LilyWangLL** [comment]
This issue hasn’t been updated in 3 months, if it is still an issue, please reopen this issue.
