### ISSUE TITLE
[github actions] PR bot suggests deprecated license identifiers

### ISSUE THREAD

**Issue by Thomas1664** [microsoft/vcpkg#24709]
**Describe the bug**
If a port doesn't provide a license field while its original license is `LGPL-2.1-only`, the bot suggests the deprecated identifier `LGPL-2.1`. I'm pretty sure this bug exists for the other `(L)GPL-*` identifiers as well.

e.g.: https://github.com/microsoft/vcpkg/pull/24706#pullrequestreview-972989616

**Comment by dg0yt** [comment]
FTR  the non-deprecated alternative is the strict `LGPL-2.1-only`, not the relaxed `LGPL-2.1-or-later`.

**Comment by Adela0814** [comment]
@BillyONeal Can you please take a look at this issue.

**Comment by BillyONeal** [comment]
It isn't suggesting that you use that deprecated license, it is saying "this is the license I found". I'll see if I can clarify the message.
