### ISSUE TITLE
[<osgEarth] update to <3.3>

### ISSUE THREAD

**Issue by chuyanjuncn** [microsoft/vcpkg#24717]
Library name:  osgEarth

New version number:  3.3

Other information that may be useful (release notes, etc...)

https://github.com/gwaldron/osgearth

https://github.com/gwaldron/osgearth/archive/refs/tags/osgearth-3.3.tar.gz

**Comment by dg0yt** [comment]
I started working on that yesterday, but it is not trivial. Key problems:
- Not aware of static library linking order for OpenSceneGraph libs. 
- Transitive dependencies not properly carried by OpenSceneGraph. 
- Dependency on outdated LERC - patch done, but not tested.

Basically, I just went one step back and look at OpenSceneGraph now.
