### ISSUE TITLE
CGAL can;t be used after exporting

### ISSUE THREAD

**Issue by justinjk007** [Microsoft/vcpkg#2471]
After installing **CGAL** I exported it, so that I can use it in appveyor. I downloaded my zip file, extracted and try to build after setting the `DCMAKE_TOOLCHAIN..`  file as the `vcpkg.cmake` file. But when trying to build, even though all libraries are found, **CGAL** vomits this error.
![image](https://user-images.githubusercontent.com/12916795/34448832-8f9038a8-ecbf-11e7-8a1b-e698cc2d3654.png)

**Line 47** in the `CMakeLists.txt` file is `include( ${CGAL_USE_FILE} )` but **CGAL_USE_FILE** is pointing to the file in my home computer(`D:/Dev/vcpkg/packages/cgal_x64-windows/lib/CGAL/UseCGAL.cmake`), which **appveyor** can't obviously find.

This is what the CGAL section looks like.
```cmake
# CGAL config
find_package(CGAL REQUIRED)
include( ${CGAL_USE_FILE} )
include( CGAL_CreateSingleSourceCGALProgram )
include_directories ("${CGAL_ROOT}/include/CGAL")
include_directories (BEFORE "../../include")

```

I can successfully build my project in my home computer by the way.

**Comment by justinjk007** [comment]
I tried to build my project using the exported zip file from my laptop as well, I get the same error.

**Comment by jasjuang** [comment]
CGAL's CMake is very non standard. I will try to figure out whether this should be fixed from the upstream or vcpkg patch. It looks to me that some of the cmake config files that is in the `install` folder is referencing something in the `packages` folder.

Can you let me know which file exactly has the `CGAL_USE_FILE` that points to the wrong location? `CMakeLists.txt` looks like something from the `buildtree` folder and not something from the `install` folder.

**Comment by justinjk007** [comment]
I didn't understand your question, do you want to know which file is CGAL_USE_FILE pointing to ?

**Comment by jasjuang** [comment]
Which file has this line `include( ${CGAL_USE_FILE} )`?

**Comment by justinjk007** [comment]
My `CMakeLists.txt` file.

**Comment by jasjuang** [comment]
That way of using it is outdated, try

```
cmake_minimum_required(VERSION 3.9)

project(Example)

set(PROJECT_SRCS ${PROJECT_SOURCE_DIR}/main.cpp)

find_package( CGAL REQUIRED )

add_executable(${PROJECT_NAME} ${PROJECT_SRCS})

target_link_libraries(${PROJECT_NAME} CGAL::CGAL)
```

**Comment by justinjk007** [comment]
YUSSS !, it works now. Thank you for giving the correct config.

**Comment by justinjk007** [comment]
@jasjuang ....yeahhhhhh....but this config won't work for linux

**Comment by jasjuang** [comment]
works on my linux and my main devs happens on linux

**Comment by justinjk007** [comment]
Look at this log https://travis-ci.org/justinjk007/Pentagonal-tiling

**Comment by jasjuang** [comment]
Where is your cgal from? Must be an old version. Try building current master with my PR https://github.com/CGAL/cgal/pull/2700

**Comment by justinjk007** [comment]
I installed this `libcgal-dev` package, not sure about its version. I update and come back.

**Comment by jasjuang** [comment]
That's way too old. If you don't want to build from master at least build with the latest release like vcpkg.

**Comment by justinjk007** [comment]
Yeah...I realised it is version `4.2` I will update that and the problem should go away, thanks for pointing me in the right direction.

**Comment by justinjk007** [comment]
Yep installing latest version from source and rebuilding gives me no more errors phewww!

**Comment by justinjk007** [comment]
Well...seems like in windows the include directories won't be added without my old config for cmake.

**Comment by jasjuang** [comment]
For some reason the `INTERFACE_INCLUDE_DIRECTORIES` does not show up in `CGALExports.cmake` in the windows build, but it shows up in the linux build. Can't figure out why at the moment. 

I always uses CGAL with other libraries, and since the INTERFACE_INCLUDE_DIRECTORIES is the same `C:\vcpkg\installed\x64-windows\include` for all of them it kind of hides the problem.

**Comment by jasjuang** [comment]
Ah, `vcpkg install cgal --head` solves it. Apparently they fixed it some point recently. I can go and try to request for a minor release.

**Comment by lrineau** [comment]
It seems a bug has been fixed in the CGAL port by @albertziegenhagel, two days ago: eb34e61d6d1a01851db311776f8f6218449ca53c. That may explain why `vcpkg install cgal --head` solves the issue. And the version of CGAL that is packages is still the same: CGAL version 4.11.

**Comment by justinjk007** [comment]
Thank you very much.

**Comment by lrineau** [comment]
Not really. The `include_directories("${CGAL_ROOT}/include/CGAL")` will trigger a bug and the error message `#error You have added .../path/to/CGAL-x.y/include/CGAL to the INCLUDE path.`, and put "../../include" is useless, unless you need it for your application.

```cmake
find_package(CGAL REQUIRED)
include( ${CGAL_USE_FILE} )
include( CGAL_CreateSingleSourceCGALProgram )
```

and even the line
```cmake
include( CGAL_CreateSingleSourceCGALProgram )
```

is only useful if you want to use the macro `create_single_source_cgal_program`.

**Comment by justinjk007** [comment]
@jasjuang @lrineau 
OK I deleted whole of my **vcpkg** directory. Installed vcpkg again. Exported **CGAL**. Now when i'm trying to use the exported zip file in appveyor, the **.sln** file is generated correctly, but when it starts to build it exits with errors like these 
![image](https://user-images.githubusercontent.com/12916795/34889349-aab095ba-f79b-11e7-975f-8578e770e423.png)

The file it says it cannot open is the file in my system,, so it won't find it obviously.

**Comment by jasjuang** [comment]
The point of exporting the installed libs/dlls/headers is to avoid rebuilding it again. Why are you trying to build CGAL again in appveyor?

**Comment by justinjk007** [comment]
I am not building CGAL I only unzip the **.7z**, link the tool-chain file and build my project not CGAL.

**Comment by justinjk007** [comment]
So, does anybody know what's going on ?

**Comment by albertziegenhagel** [comment]
I think the problem is that CGAL just does not create a portable package (which means their CMake config file has absolute paths written to it). Unfortunately that is pretty common and in general not a very easy task to solve.

Maybe vcpkg could extend the `vcpkg_fixup_cmake_targets` function that it looks for `<vcpkg_root>/installed/<triplet_name>/` in the files and replaces that with a relative path or something similar. However it would be difficult to guarantee that this will really fix all cases.

@ras0219-msft: any ideas on this? I think this issue is actually quite important if `vcpkg export` should work with CMake packages that have third-party dependencies.

**Comment by justinjk007** [comment]
I should also point out as you can see the file it is trying to access is `mpfr.lib` so it really CGAL's problem or MPFR's problem.

**Comment by albertziegenhagel** [comment]
Just as a workaround for now (and maybe as a test) you could manually edit the file `<vcpkg_root>/installed/<triplet_name>/share/cgal/CGALConfig.cmake` and replace the absolute paths in the very end of that file. So e.g. instead of `<vcpkg_root>/installed/<triplet_name>/lib/mpfr.lib` you would write `${CGAL_CONFIG_DIR}/../../lib/mpfr.lib`.

Of course you would have to redo the fixes every time CGAL gets updated by vcpkg.

**Comment by justinjk007** [comment]
But I can do this on the exported package and then it would never be updated again right ?

**Comment by albertziegenhagel** [comment]
If you are not planing to update your exported packages, that should be true, yes.

**Comment by ras0219-msft** [comment]
@albertziegenhagel Yes, I think this is the right approach to deal with this problem (doing find/replace to make absolute paths relative).

**Comment by justinjk007** [comment]
This is what I changed
```diff
@@ -166,15 +166,16 @@
 if (NOT CGAL_IGNORE_PRECONFIGURED_GMP)
   set( GMP_FOUND           "TRUE")
   set( GMP_USE_FILE        "" )
-  set( GMP_INCLUDE_DIR     "${CGAL_CONFIG_DIR}/../../include" )
-  set( GMP_LIBRARIES       "${CGAL_CONFIG_DIR}/../../lib/mpir.lib" )
+  set( GMP_INCLUDE_DIR     "D:/Dev/vcpkg/installed/x64-windows/include" )
+  set( GMP_LIBRARIES       "D:/Dev/vcpkg/installed/x64-windows/lib/mpir.lib" )
   set( GMP_DEFINITIONS     "" )
 endif()
 
 if (NOT CGAL_IGNORE_PRECONFIGURED_MPFR)
   set( MPFR_FOUND           "TRUE")
   set( MPFR_USE_FILE        "" )
-  set( MPFR_INCLUDE_DIR     "${CGAL_CONFIG_DIR}/../../include" )
-  set( MPFR_LIBRARIES       "${CGAL_CONFIG_DIR}/../../lib/mpfr.lib" )
+  set( MPFR_INCLUDE_DIR     "D:/Dev/vcpkg/installed/x64-windows/include" )
+  set( MPFR_LIBRARIES       "D:/Dev/vcpkg/installed/x64-windows/lib/mpfr.lib" )
   set( MPFR_DEFINITIONS     "" )
 endif()
+

Diff finished.  Sat Jan 20 18:18:41 2018
```

And it works now.. thanks everyone. But ofc this should be taken care as a whole.

**Comment by lrineau** [comment]
At the CGAL side, it cannot be changed, because GMP and MPFR may be installed separately from CGAL, and the CGAL CMake code cannot but use absolute paths to MPFR/GMP headers and libraries.

In the context of a package manager (like vcpkg, chocolatey, conan, ...) a relative path makes sense, because the package management system assures a coherence of installation paths, but in general that cannot be assumed.

**Comment by jclay** [comment]
I have been following this thread and just wanted to confirm a few details regarding the usage of the CGAL package before I open a pull request:

Post-install of CGAL gives this output:
```
The package cgal:x64-windows provides CMake targets:

    find_package(cgal REQUIRED)
    # Note: 7 targets were omitted
    target_link_libraries(main PRIVATE CGAL::CGAL CGAL::CGAL CGAL::CGAL_Core CGAL::CGAL_Core)
```

Based on my reading of the `vcpkg` source, it looks like if there is no `usage` file given, then it uses some heuristic to try and infer the targets that are available.

It seems based on the thread above, and my personal usage that the following usage is correct:

```
find_package(cgal REQUIRED)
target_link_libraries(main PRIVATE CGAL::CGAL)
```

Are there are other targets that are available? `CGAL::CGAL_CORE` does not seem to exist, so I just wanted to confirm before I open a PR to add proper usage instructions.

**Comment by justinjk007** [comment]
I think all you need is CGAL::CGAL

**Comment by lrineau** [comment]
Depending on the configuration and available dependencies, CGAL also provides `CGAL::CGAL_Qt5` (used only to compile the demos), and `CGAL::CGAL_ImageIO` used only by a few classes in the Mesh_3 package of CGAL.

`CGAL::CGAL_Core` provides an exact and expansive number type with exact square roots. It is only required by a few packages of CGAL (2D arrangements with circle arcs, 2D exact straight skeleton, 2D exact Minkovski sums, maybe others) . If you do not link it and have no link errors, then your code does not use it.

**Comment by studiofuga** [comment]
Hi, this issue is still present, is there any long term fix that can be added, other than manually run a fixup script after unpacking the exported package?
Thanks

**Comment by lrineau** [comment]
[**@studiofuga**](https://github.com/studiofuga) commented on [Dec 14, 2018, 10:01 AM GMT+1](https://github.com/Microsoft/vcpkg/issues/2471#issuecomment-447260580 "2018-12-14T09:01:46Z - Replied by Github Reply Comments"):
> Hi, this issue is still present, is there any long term fix that can be added, other than manually run a fixup script after unpacking the exported package?  
> 
> Thanks

I think the recent PR https://github.com/CGAL/cgal/pull/3922 might have fixed the issue.
