### ISSUE TITLE
error: building jasper:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by nlm1997** [microsoft/vcpkg#24723]
**Host Environment**
- OS: Windows
- Compiler: g++

**To Reproduce**
`git clone https://github.com/Microsoft/vcpkg.git
cd vcpkg
.\bootstrap-vcpkg.sh
.\vcpkg integrate install
vcpkg install ogre`

**Additional context**
`error: building jasper:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+jasper
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[jasper]+Build+error
Include '[jasper] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-05-05-67e17c1782801cf481be9ac0b3765dff3e4bdeb8
    vcpkg-scripts version: 0cf5b4305 2022-05-13 (2 days ago)`

**Comment by JonLiu1993** [comment]
@Luseno64 ,Thanks for posting this issue, could you please provide your error log?

**Comment by JackBoosY** [comment]
We can't reproduce this issue locally.
Pleaes provide the output in your console and the failure logs mentioned in the ouput.

Thanks.

**Comment by JonLiu1993** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
