### ISSUE TITLE
Ports in manifest mode fail to build using MSVC after updating to the 2022.05.10 release

### ISSUE THREAD

**Issue by markgomez** [microsoft/vcpkg#24721]
**Describe the bug**

I've been using the `2022.04.12` release as a submodule in manifest mode and it was working fine until I updated to the latest release (`2022.05.10` at the time of this writing). Many of the ports I've tried so far (not just the one listed in my example below) result in a `BUILD_FAILED` error when using MSVC.

<br>

**Environment**
- MSVC v142, 19.29.30145.0 (VS 2019) x64/x86 build tools
- Ninja 1.10.2
- CMake 3.20.21032501-MSVC_2
- Windows 10 SDK 10.0.18362.0
- Windows 10 Pro, build 19044.1706
- Developer Command Prompt 16.11.14 (`vcvarsall.bat` initialized for `x64`; also fails in PowerShell 7.2.3)

<br>

**To Reproduce**

Given a freshly initialized empty Git repository with the following `vcpkg.json`:

```js
{
  "name": "foo",
  "version": "0.1.0",
  "dependencies": ["libxml2"]
}
```

Add `vcpkg` as a submodule:

```cmd
> git submodule add https://github.com/microsoft/vcpkg
```

Switch to the [2022.05.10 release](https://github.com/microsoft/vcpkg/releases/tag/2022.05.10) (`14e7bb4`):

```cmd
> git -C vcpkg checkout 14e7bb4ae24616ec54ff6b2f6ef4e8659434ea44
```

Bootstrap it:

```cmd
> ./vcpkg/bootstrap-vcpkg.bat
```

Install manifest dependencies:

```cmd
> ./vcpkg/vcpkg install
```

The following error appears (see attached log below):

> error: building zlib:x64-windows failed with: BUILD_FAILED

Now, switch to the previous [2022.04.12 release](https://github.com/microsoft/vcpkg/releases/tag/2022.04.12) (`e809a42`):

```cmd
> git -C vcpkg checkout e809a42f87565e803b2178a0c11263f462d1800a
```

Bootstrap it:

```cmd
> ./vcpkg/bootstrap-vcpkg.bat
```

Try installing manifest dependencies again:

```cmd
> ./vcpkg/vcpkg install
```

It should now succeed.

<br>

**Expected behavior**

Ports build successfully; `find_package` and `target_link_libraries` strings are sent to `stdout`.

<br>

**Failure logs**

[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/8695582/config-x64-windows-out.log)

<br>

**Additional context**

I've tried the above steps on the following setups without any issues:

- Apple Clang 13.0.0, macOS Big Sur (M1, arm64)
- Clang 10.0.0, Ubuntu 20.04.3 via WSL 2 (GNU/Linux 4.19.104-microsoft-standard x86_64)
- GCC 10.3.0, Ubuntu 20.04.3 (same WSL 2 instance)

It's only my MSVC setup that fails to build. From the logs, it looks like CMake fails at "detecting C compiler ABI info". The one thing in the log that stood out to me was the following:

> Run Build Command(s):E:/VS/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe cmTC_8c87c && ninja: error: 'C:/Users/Mark/dev-local/www/foo/vcpkg/buildtrees/zlib/x64-windows-dbg/CMakeFiles/CMakeTmp/`testCCompiler.c`', needed by 'CMakeFiles/cmTC_8c87c.dir/testCCompiler.c.obj', `missing and no known rule to make it`

It sounds like a required file (`testCCompiler.c`) for some reason isn't being generated?

**Comment by JackBoosY** [comment]
I can't repro this issue locally. It works fine in my machine.
`testCCompiler.c` should be generated by cmake function `CMakeTestCCompiler`.
This issue should related to your Visual Studio or disk.

**Comment by JackBoosY** [comment]
>  it looks like vcpkg incorrectly downloaded CMake x86 onto my x64 machine for some reason (is this a bug with architecture detection?)

No, that's by design.
To ensure compatibility, vcpkg will only download x86 binaries on x86/x64 systems.

**Comment by JackBoosY** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.
