### ISSUE TITLE
Visual Studio doesn't detect Vcpkg

### ISSUE THREAD

**Issue by JacqueSatan** [microsoft/vcpkg#24730]
**Describe the bug**
I used Visual Studio Community from early versions of 2019 until now, both Preview and Normal, and it never detected Vcpkg as it should do it. I always added the vcpkg include and library directories by hand in each of my projects.

I just saw that other users have a vcpkg category in their projects properties, which I didn't even know was a thing. I completely reinstalled Visual Studio and Vcpkg a bunch of times during the lifespan of my computer.

**Environment**
- OS: Windows (error occurring from Windows 10 to Windows 11 22616.100)
- Compiler: Visual Studio 2019 and 2022

**To Reproduce**
1. ./vcpkg integrate install
2. ./vcpkg install cpr:x64-windows (other triplets don't work either)

**Expected behavior**
I expect Visual Studio to detect the libraries I installed with Vcpkg automatically, instead of having to add the include path and the libraries path + every single .lib file in the properties of my projects.

**Additional context**
Doesn't detect vcpkg: 
![image](https://user-images.githubusercontent.com/38167139/168595867-c1623bfb-4744-4543-b153-6e82854c4880.png)
Vcpkg category doesn't exist:
![image](https://user-images.githubusercontent.com/38167139/168595967-bb48b30e-37bd-4505-9646-8c107a6241da.png)

Thank you for reading, if you can help me that'd save me a lot of time.

**Comment by Cheney-W** [comment]
Could you please check to see if your ${VSINSTALLDIR}\MSBuild\Microsoft\VC\v170\Microsoft.Cpp.Common.props file contains the following:
```
  <PropertyGroup >
    <VCLibPackagePath Condition="'$(VCLibPackagePath)' == ''">$(LOCALAPPDATA)\vcpkg\vcpkg.user</VCLibPackagePath>
  </PropertyGroup>
  <Import Condition="'$(VCLibPackagePath)' != '' and Exists('$(VCLibPackagePath).props')" Project="$(VCLibPackagePath).props" />
```
If not, I think you could open Powershell as administrator and run `.\vcpkg integrate install` again.

**Comment by JacqueSatan** [comment]
The file contains this property.

**Comment by Cheney-W** [comment]
@BillyONeal Could you please help take a look this issue? Thank you!

**Comment by Cheney-W** [comment]
1. What is the specific version of VS and vcpkg that you are currently reproducing the problem with?
2. After run vcpkg integrate install and added `#include<cpr/cpr.h>` into the VS project, will this project fail when build with debug x64?

**Comment by JacqueSatan** [comment]
Currently using Visual Studio Community 2022 Version 17.2.0 with Vcpkg 2022-03-30-692785ac944e81417840c6de244fb3e18a4b35eb. But this problem occurred with every version I tried since at least three years.

After running `vcpkg install cpr:x64-windows` and `vcpkg integrate install`, the build fails, saying `cannot open source file "cr/cpr.h"`. Same kind of error with every other library I installed.

**Comment by BillyONeal** [comment]
![image](https://user-images.githubusercontent.com/1544943/169897179-5a5d5f93-b6dc-4b57-8412-413ec1542e78.png)

I'm unable to repro the problem. Every time we have gotten such reports it has been the triplet getting selected in Visual Studio land not matching the one used to build the dependencies in question. (e.g. building **x86**-windows, the default, but VS building **x64**-windows)

**Comment by JacqueSatan** [comment]
None of the two triplets work. Is there a way to get logs about Visual Studio looking for Vcpkg?

**Comment by Cheney-W** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
