### ISSUE TITLE
[ImGui] missing version 1.80

### ISSUE THREAD

**Issue by knoxfighter** [microsoft/vcpkg#24732]
Library name: imgui

Missing version number: 1.80

Other information that may be useful (release notes, etc...):
ImGui is already listed and up to date. BUT, version 1.80 is not tracked and we have to use that specific version.
Please add that version to the list of available versions.

**Comment by JonLiu1993** [comment]
@knoxfighter, Thanks for posting this issue, vcpkg can't add the missing version temporarily, but we provide the overlay feature for users to add a specific version locally. For the specific usage method, please refer to [this](https://github.com/microsoft/vcpkg/blob/master/docs/specifications/ports-overlay.md). If you have any problems during use, you can ping me

**Comment by JonLiu1993** [comment]
Temporarily close this issue and reopen it if you have any questions
