### ISSUE TITLE
Unable to switch between dynamic and static links

### ISSUE THREAD

**Issue by x64bugreport** [Microsoft/vcpkg#2473]
I built by VCPKG boost dynamic library and static library, but in vs2017 can not be switched by the / MT option to statically compile mode, change to / MT, still using dynamic link, how to switch between static library and dynamic library options the way? ? ?

**Comment by x64bugreport** [comment]
vcpkg first installed the boost dynamic library, then install the boost static library, but in the vs compiler option to / MT, still can not be statically linked, # include priority to find still dynamic library directory, how to switch to static Link, or vcpkg can be adaptive search directory under the compiler options? ?

**Comment by cenit** [comment]
If you want to use non-default triplets in solutions (if you use CMake it's a different topic), you need to manually edit the vcxproj.
Here it is a very short guide, let me know if you have any other question
https://gist.github.com/cenit/469d0c2ccbf428614fc35de443470929
