### ISSUE TITLE
DLL can not be copied when project path exists in Chinese.

### ISSUE THREAD

**Issue by x64bugreport** [Microsoft/vcpkg#2474]
When the project path exists in Chinese, such as boost dynamic link, you can not copy the DLL file. vs error output, unrecognized Chinese directory.

**Comment by Cheney-W** [comment]
@x64bugreport, Could you provide a detailed repro steps and the version of vcpkg to us?

**Comment by wangli28** [comment]
Thanks for posting this issue. Please open a new issue if this is still a problem for you.
