### ISSUE TITLE
[New Port Request] Cling C++ interpreter.

### ISSUE THREAD

**Issue by Remotion** [microsoft/vcpkg#24753]
Library name: 
Cling 

Library description:
Cling C++ interpreter.

Source repository URL:
https://github.com/root-project/cling

Project homepage (if different from the source repository):
https://root.cern/cling/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by Neumann-A** [comment]
Since `cling` is a tool and not a library it is, in general, out of the scope of vcpkg. I might provide an overlay someday but it probably won't go into the main repo.

**Comment by LilyWangLL** [comment]
Thanks Neumann's help. Since tool `cling` can't be added to vcpkg for now, so I am closing this issue for now. If there are new updates about this tool, please reopen this issue.

**Comment by jeaye** [comment]
Hi! Jumping in here to say that Cling is a tool, yes, but **it is also embeddable as a library**. Any program looking to JIT compile C or C++ can embed Cling to accomplish it.

Can we please have this ticket reopened?

**Comment by LilyWangLL** [comment]
> Hi! Jumping in here to say that Cling is a tool, yes, but **it is also embeddable as a library**. Any program looking to JIT compile C or C++ can embed Cling to accomplish it. For example, the [jank compiler](https://github.com/jank-lang/jank).
> 
> Can we please have this ticket reopened?

If someone can submit a PR to add this library, this issue can be reopened.
