### ISSUE TITLE
[New Port Request] CVC5 SMT Solver.

### ISSUE THREAD

**Issue by Remotion** [microsoft/vcpkg#24752]
Library name: 
cvc5

Library description: 
cvc5 is an open-source automatic theorem prover for Satisfiability Modulo Theories (SMT) problems. 

Source repository URL:  
https://github.com/cvc5/cvc5

Project homepage (if different from the source repository): 
https://cvc5.github.io/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
