### ISSUE TITLE
[curl] build failure "an FYI"

### ISSUE THREAD

**Issue by StarGate-One** [microsoft/vcpkg#24765]
**Just an FYI Heads up**

**Host Environment**
- OS: Windows 11 Version [10.0.22000.675]
- Compiler: Visual Studio Community 2022 Version: [17.2.1]  VS Tools Version: [14.31.31103] 
                   Microsoft (R) C/C++ Optimizing Compiler Version [19.31.31107] for x64 

**To Reproduce**
`./vcpkg install curl[core,non-http,schannel,ssl,sspi,winssl]:x64-windows`

**Failure logs**
-Cut and paste the appropriate build messages from the console output.
`->vcpkg install curl[core,non-http,schannel,ssl,sspi,winssl]:x64-windows`
`Computing installation plan...`
`The following packages will be built and installed:`
`    curl[core,non-http,schannel,ssl,sspi,winssl]:x64-windows -> 7.83.1#1`
`Installing 1/1 curl:x64-windows...`
`Building curl[core,non-http,schannel,ssl,sspi,winssl]:x64-windows...`
`-- Using cached curl-curl-curl-7_83_1.tar.gz.`
`-- Cleaning sources at D:/vcpkg/buildtrees/curl/src/url-7_83_1-a62e868212.clean. Use --editable to skip cleaning for the packages you specify.`
`-- Extracting source D:/vcpkg-downloads/curl-curl-curl-7_83_1.tar.gz`
`-- Applying patch 0002_fix_uwp.patch`
`-- Applying patch 0005_remove_imp_suffix.patch`
`-- Applying patch 0012-fix-dependency-idn2.patch`
`-- Applying patch 0020-fix-pc-file.patch`
`-- Applying patch 0021-normaliz.patch`
`-- Applying patch 0022-deduplicate-libs.patch`
`-- Applying patch mbedtls-ws2_32.patch`
`-- Applying patch export-components.patch`
`-- Applying patch wolfssl-ntlm.patch`
`-- Using source at D:/vcpkg/buildtrees/curl/src/url-7_83_1-a62e868212.clean`
`-- Configuring x64-windows`
`-- Building x64-windows-dbg`
`CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:158 (message):`
`    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j8`
`    Working Directory: D:/vcpkg/buildtrees/curl/x64-windows-dbg`
`    See logs for more information:`
`      D:\vcpkg\buildtrees\curl\install-x64-windows-dbg-out.log`
` `
`Call Stack (most recent call first):`
`  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:112 (vcpkg_execute_build_process)`
`  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)`
`  ports/curl/portfile.cmake:98 (vcpkg_cmake_install)`
`  scripts/ports.cmake:146 (include)`
` `
`error: building curl:x64-windows failed with: BUILD_FAILED`
`Please ensure you're using the latest port files with `git pull` and `vcpkg update`.`
`Then check for known issues at:`
`    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+curl`
`You can submit a new issue at:`
`    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[curl]+Build+error`
`Include '[curl] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.`
`    vcpkg-tool version: 2022-05-16-ef052b7b58d92aed795b851b356c06f9b5cf1deb`
`    vcpkg-scripts version: 22b403386 2022-05-17 (4 hours ago)`

-Please attach any additional failure logs mentioned in the console output.
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/8712268/install-x64-windows-dbg-out.log)

-Error in install-x64-windows-dbg-out.log as follows:
`D:\vcpkg\buildtrees\curl\src\url-7_83_1-a62e868212.clean\lib\curl_ntlm_core.h(42): fatal error C1083: Cannot open include file: 'openssl/ssl.h': No such file or directory`

**Additional context**
-The new patch [wolfssl-ntlm.patch lines 1 thru 18](https://github.com/microsoft/vcpkg/blob/61058871a9d0a671539b35f73c7fde8ac88d9014/ports/curl/wolfssl-ntlm.patch#L1-L18) and [wolfssl-ntlm.patch lines 30 thru 37](https://github.com/microsoft/vcpkg/blob/61058871a9d0a671539b35f73c7fde8ac88d9014/ports/curl/wolfssl-ntlm.patch#L30-L37) added in [Pull Request [new port] Add wolfSSL projects #24348](https://github.com/microsoft/vcpkg/pull/24348) creates **fall thru situation** where feature `openssl must be installed` if feature `wolfssl is not installed`  to successfully generate, compile, link and install `port curl`.

-If `feature openssl or wolfssl` is selected then `port curl` builds, compiles, links and installs with no issues, otherwise it fails as the source files for neither port openssl or wolfssl are installed.

/cc: @elms @BillyONeal @Cheney-W

**Comment by elms** [comment]
I think this https://github.com/microsoft/vcpkg/compare/master...elms:fix/curl_ntlm?expand=1 will fix it. But really should apply the full patch from https://github.com/curl/curl/pull/8864

**Comment by BillyONeal** [comment]
https://github.com/microsoft/vcpkg/pull/24766

**Comment by LilyWangLL** [comment]
Fixed by #24766

**Comment by StarGate-One** [comment]
Thank you everyone. Have a great weekend.
