### ISSUE TITLE
[New Port Request] <Servo>

### ISSUE THREAD

**Issue by Aayush0612** [microsoft/vcpkg#24779]
Library name : Servo

Library description : A official Arduino Library for controlling Servo motors via their chipsets.

Source repository URL : https://github.com/arduino-libraries/Servo

Project Docs : https://www.arduino.cc/reference/en/libraries/servo/

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
