### ISSUE TITLE
[gmp] build failure

### ISSUE THREAD

**Issue by terrylyons** [microsoft/vcpkg#24788]
**Host Environment**
- OS: [Linux]
- Compiler: g++ (Ubuntu 9.3.0-10ubuntu2) 9.3.0
~/vcpkg$ cmake --version
cmake version 3.23.1

**To Reproduce**
Clean virtual ubuntu machine 
with git, cmake, autoconf and all the tools needed for cross compilation in C++ with visual studio
Clean clone of vcpgk ; git pull and vcpkg update both say up to date.
then:
`./vcpkg install gmp`

**Failure logs**
terry@terry-vm3:~/vcpkg$ ./vcpkg install gmp
Computing installation plan...
The following packages will be built and installed:
    gmp[core]:x64-linux -> 6.2.1#9
Detecting compiler hash for triplet x64-linux...
Restored 0 packages from /home/terry/.cache/vcpkg/archives in 3.9 us. Use --debug to see more details.
Installing 1/1 gmp:x64-linux...
Building gmp[core]:x64-linux...
-- Using cached gmp-6.2.1.tar.xz.
-- Cleaning sources at /home/terry/vcpkg/buildtrees/gmp/src/gmp-6.2.1-f412680bba.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/terry/vcpkg/downloads/gmp-6.2.1.tar.xz
-- Applying patch tools.patch
-- Using source at /home/terry/vcpkg/buildtrees/gmp/src/gmp-6.2.1-f412680bba.clean
-- Getting CMake variables for x64-linux-dbg
-- Getting CMake variables for x64-linux-rel
-- Generating configure for x64-linux
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:128 (message):
    Command failed: /usr/bin/autoreconf -vfi
    Working Directory: /home/terry/vcpkg/buildtrees/gmp/src/gmp-6.2.1-f412680bba.clean/
    Error code: 1
    See logs for more information:
      /home/terry/vcpkg/buildtrees/gmp/autoconf-x64-linux-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:629 (vcpkg_execute_required_process)
  ports/gmp/portfile.cmake:46 (vcpkg_configure_make)
  scripts/ports.cmake:146 (include)

error: building gmp:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+gmp
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[gmp]+Build+error
Include '[gmp] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-05-05-67e17c1782801cf481be9ac0b3765dff3e4bdeb8
    vcpkg-scripts version: 261ca0dd4 2022-05-18 (12 hours ago)
**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by Adela0814** [comment]
@terrylyons  please install `autoreconf `first,
```
These can be installed on Ubuntu systems via
      sudo apt-get update -y
      sudo apt-get install -y autoconf-archive
```

if the issue still exists, please provide the failure log:
`/home/terry/vcpkg/buildtrees/gmp/autoconf-x64-linux-err.log`

**Comment by Adela0814** [comment]
@terrylyons Has your problem been solved?

**Comment by Adela0814** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
