### ISSUE TITLE
Error: Building package zlib:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by wuwo1952368901** [Microsoft/vcpkg#2478]
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zlib:x64-windows
  Vcpkg version: 0.0.100-unknownhash

**Comment by jasjuang** [comment]
Please post the error log so we can trouble shoot

**Comment by wuwo1952368901** [comment]
[config-x64-windows-dbg-err.log](https://github.com/Microsoft/vcpkg/files/1595777/config-x64-windows-dbg-err.log)
[config-x64-windows-rel-err.log](https://github.com/Microsoft/vcpkg/files/1595778/config-x64-windows-rel-err.log)
[patch-x64-windows-0-err.log](https://github.com/Microsoft/vcpkg/files/1595779/patch-x64-windows-0-err.log)

**Comment by jasjuang** [comment]
According to your log

```
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_CXX_FLAGS
    CMAKE_CXX_FLAGS_RELEASE
```

Did you have Visual Studio installed?

**Comment by wuwo1952368901** [comment]
Yes,I installed Visual Studio 2013, Visual Studio 2015 and Visual Studio 2017

**Comment by wuwo1952368901** [comment]
Yes, It's OK，I don't install some components。

**Comment by ChisonShang** [comment]
> Yes, It's OK，I don't install some components。

Could you tell me what components do you installed?

**Comment by LarryIII** [comment]
Please open a new issue if this is still a problem for you.
