### ISSUE TITLE
[glfw3] Build error

### ISSUE THREAD

**Issue by SkitzFist** [microsoft/vcpkg#24787]
**Host Environment**
- OS: Windows 10

**To Reproduce**
`./vcpkg install raylib:wasm32-emscripten

**Failure logs**
PS C:\Projects\Emscripten Test> .\vcpkg\vcpkg.exe install raylib:wasm32-emscripten
Computing installation plan...
The following packages will be built and installed:
  * glfw3[core]:wasm32-emscripten -> 3.3.7
    raylib[core,use-audio]:wasm32-emscripten -> 4.0.0#3
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet wasm32-emscripten...
Restored 0 packages from C:\Users\JoPer\AppData\Local\vcpkg\archives in 163.4 us. Use --debug to see more details.
Installing 1/2 glfw3:wasm32-emscripten...
Building glfw3[core]:wasm32-emscripten...
-- Using community triplet wasm32-emscripten. This triplet configuration is not guaranteed to succeed.-- [COMMUNITY] Loading triplet configuration from: C:\Projects\Emscripten Test\vcpkg\triplets\community\wasm32-emscripten.cmake
-- Using cached glfw-glfw-45ce5ddd197d5c58f50fdd3296a5131c894e5527.tar.gz.
-- Cleaning sources at C:/Projects/Emscripten Test/vcpkg/buildtrees/glfw3/src/1c894e5527-3070f6d62b.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Projects/Emscripten Test/vcpkg/downloads/glfw-glfw-45ce5ddd197d5c58f50fdd3296a5131c894e5527.tar.gz
-- Using source at C:/Projects/Emscripten Test/vcpkg/buildtrees/glfw3/src/1c894e5527-3070f6d62b.clean
-- Found external ninja('1.10.2').
-- Configuring wasm32-emscripten
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:128 (message):
    Command failed: C:/mingw64/bin/ninja.exe -v
    Working Directory: C:/Projects/Emscripten Test/vcpkg/buildtrees/glfw3/wasm32-emscripten-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\Projects\Emscripten Test\vcpkg\buildtrees\glfw3\config-wasm32-emscripten-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:331 (vcpkg_execute_required_process)
  ports/glfw3/portfile.cmake:20 (vcpkg_cmake_configure)
  scripts/ports.cmake:146 (include)

error: building glfw3:wasm32-emscripten failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+glfw3
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[glfw3]+Build+error
Include '[glfw3] Build error' in your bug report title, the following version information in your bug 
description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-05-05-67e17c1782801cf481be9ac0b3765dff3e4bdeb8
    vcpkg-scripts version: 261ca0dd4 2022-05-18 (11 hours ago)

**-------\vcpkg\buildtrees\glfw3\config-wasm32-emscripten-out.log-----------------**
[1/2] cmd /c "cd ../../wasm32-emscripten-dbg && "C:/cmake/bin/cmake.exe" "C:/Projects/Emscripten Test/vcpkg/buildtrees/glfw3/src/1c894e5527-3070f6d62b.clean" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_INSTALL_PREFIX=C:/Projects/Emscripten Test/vcpkg/packages/glfw3_wasm32-emscripten/debug" "-DGLFW_BUILD_EXAMPLES=OFF" "-DGLFW_BUILD_TESTS=OFF" "-DGLFW_BUILD_DOCS=OFF" "-DCMAKE_MAKE_PROGRAM=C:/mingw64/bin/ninja.exe" "-DCMAKE_SYSTEM_NAME=Emscripten" "-DBUILD_SHARED_LIBS=OFF" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/Projects/Emscripten Test/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake" "-DVCPKG_TARGET_TRIPLET=wasm32-emscripten" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=external" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/Projects/Emscripten Test/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_LINKER_FLAGS_RELEASE=" "-DVCPKG_LINKER_FLAGS_DEBUG=" "-DVCPKG_TARGET_ARCHITECTURE=wasm32" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=C:/Projects/Emscripten Test/vcpkg" "-D_VCPKG_INSTALLED_DIR=C:/Projects/Emscripten Test/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF""
FAILED: ../../wasm32-emscripten-dbg/CMakeCache.txt 
cmd /c "cd ../../wasm32-emscripten-dbg && "C:/cmake/bin/cmake.exe" "C:/Projects/Emscripten Test/vcpkg/buildtrees/glfw3/src/1c894e5527-3070f6d62b.clean" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_INSTALL_PREFIX=C:/Projects/Emscripten Test/vcpkg/packages/glfw3_wasm32-emscripten/debug" "-DGLFW_BUILD_EXAMPLES=OFF" "-DGLFW_BUILD_TESTS=OFF" "-DGLFW_BUILD_DOCS=OFF" "-DCMAKE_MAKE_PROGRAM=C:/mingw64/bin/ninja.exe" "-DCMAKE_SYSTEM_NAME=Emscripten" "-DBUILD_SHARED_LIBS=OFF" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/Projects/Emscripten Test/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake" "-DVCPKG_TARGET_TRIPLET=wasm32-emscripten" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=external" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/Projects/Emscripten Test/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_LINKER_FLAGS_RELEASE=" "-DVCPKG_LINKER_FLAGS_DEBUG=" "-DVCPKG_TARGET_ARCHITECTURE=wasm32" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=C:/Projects/Emscripten Test/vcpkg" "-D_VCPKG_INSTALLED_DIR=C:/Projects/Emscripten Test/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF""
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Using X11 for window creation
CMake Error at C:/cmake/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find X11 (missing: X11_X11_LIB)
Call Stack (most recent call first):
  C:/cmake/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  C:/cmake/share/cmake-3.23/Modules/FindX11.cmake:457 (find_package_handle_standard_args)
  C:/Projects/Emscripten Test/vcpkg/scripts/buildsystems/vcpkg.cmake:824 (_find_package)
  CMakeLists.txt:208 (find_package)

-- Configuring incomplete, errors occurred!
See also "C:/Projects/Emscripten Test/vcpkg/buildtrees/glfw3/wasm32-emscripten-dbg/CMakeFiles/CMakeOutput.log".
[2/2] cmd /c "cd .. && "C:/cmake/bin/cmake.exe" "C:/Projects/Emscripten Test/vcpkg/buildtrees/glfw3/src/1c894e5527-3070f6d62b.clean" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=C:/Projects/Emscripten Test/vcpkg/packages/glfw3_wasm32-emscripten" "-DGLFW_BUILD_EXAMPLES=OFF" "-DGLFW_BUILD_TESTS=OFF" "-DGLFW_BUILD_DOCS=OFF" "-DCMAKE_MAKE_PROGRAM=C:/mingw64/bin/ninja.exe" "-DCMAKE_SYSTEM_NAME=Emscripten" "-DBUILD_SHARED_LIBS=OFF" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/Projects/Emscripten Test/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake" "-DVCPKG_TARGET_TRIPLET=wasm32-emscripten" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=external" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/Projects/Emscripten Test/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_LINKER_FLAGS_RELEASE=" "-DVCPKG_LINKER_FLAGS_DEBUG=" "-DVCPKG_TARGET_ARCHITECTURE=wasm32" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=C:/Projects/Emscripten Test/vcpkg" "-D_VCPKG_INSTALLED_DIR=C:/Projects/Emscripten Test/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF""
FAILED: ../CMakeCache.txt 
cmd /c "cd .. && "C:/cmake/bin/cmake.exe" "C:/Projects/Emscripten Test/vcpkg/buildtrees/glfw3/src/1c894e5527-3070f6d62b.clean" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=C:/Projects/Emscripten Test/vcpkg/packages/glfw3_wasm32-emscripten" "-DGLFW_BUILD_EXAMPLES=OFF" "-DGLFW_BUILD_TESTS=OFF" "-DGLFW_BUILD_DOCS=OFF" "-DCMAKE_MAKE_PROGRAM=C:/mingw64/bin/ninja.exe" "-DCMAKE_SYSTEM_NAME=Emscripten" "-DBUILD_SHARED_LIBS=OFF" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/Projects/Emscripten Test/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake" "-DVCPKG_TARGET_TRIPLET=wasm32-emscripten" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=external" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/Projects/Emscripten Test/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_LINKER_FLAGS_RELEASE=" "-DVCPKG_LINKER_FLAGS_DEBUG=" "-DVCPKG_TARGET_ARCHITECTURE=wasm32" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=C:/Projects/Emscripten Test/vcpkg" "-D_VCPKG_INSTALLED_DIR=C:/Projects/Emscripten Test/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF""
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Using X11 for window creation
CMake Error at C:/cmake/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find X11 (missing: X11_X11_LIB)
Call Stack (most recent call first):
  C:/cmake/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  C:/cmake/share/cmake-3.23/Modules/FindX11.cmake:457 (find_package_handle_standard_args)
  C:/Projects/Emscripten Test/vcpkg/scripts/buildsystems/vcpkg.cmake:824 (_find_package)
  CMakeLists.txt:208 (find_package)

-- Configuring incomplete, errors occurred!
See also "C:/Projects/Emscripten Test/vcpkg/buildtrees/glfw3/wasm32-emscripten-rel/CMakeFiles/CMakeOutput.log".
ninja: build stopped: subcommand failed.

**-----CMakeOutput.log----**
The target system is: Emscripten - 1 - x86
The host system is: Windows - 10.0.19044 - AMD64
Performing C SOURCE FILE Test CMAKE_HAVE_LIBC_PTHREAD succeeded with the following output:
Change Dir: C:/Projects/Emscripten Test/vcpkg/buildtrees/glfw3/wasm32-emscripten-rel/CMakeFiles/CMakeTmp

Run Build Command(s):C:/mingw64/bin/ninja.exe cmTC_9fb08 && [1/2] Building C object CMakeFiles/cmTC_9fb08.dir/src.c.o

[2/2] Linking C executable cmTC_9fb08.js

Source file was:
#include <pthread.h>

static void* test_func(void* data)
{
  return data;
}

int main(void)
{
  pthread_t thread;
  pthread_create(&thread, NULL, test_func, NULL);
  pthread_detach(thread);
  pthread_cancel(thread);
  pthread_join(thread, NULL);
  pthread_atfork(NULL, NULL, NULL);
  pthread_exit(NULL);

  return 0;
}

**Additional context**
I have very limited knowledge about bouth emsdk and vcpk as this is the first project I've tried to setup with this configuration. 
I pretty much just followd the steps from this site: https://thatonegamedev.com/cpp/programming-a-c-game-for-the-web-emscripten/
Thank you.

**Comment by MoAlyousef** [comment]
Emscripten comes with its own patched version of glfw which you can enable using "-s USE_GLFW=3" in your shell args (which can be passed to CMAKE_C_FLAGS and CMAKE_CXX_FLAGS. So compiling glfw using vcpkg is not needed.

**Comment by LilyWangLL** [comment]
This issue hasn’t been updated in 3 months, if it is still an issue, please reopen this issue.

**Comment by object71** [comment]
This was closed prematurely. There is an actual issue here with the portfile since [this commit](https://github.com/microsoft/vcpkg/commit/75d2a36b8e4bbee183d3db72f60de705c54f39c3) which introduced the dependency for glfw3 to raylib for all platforms except windows. The case should be for all platforms except windows and emscripten since emscripten provides its own implementation.
