### ISSUE TITLE
[libgcrypt] wrong supports statement 

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#24786]
`libgcrypt` claims to be unsupported on windows.

according to the `configure.ac` however there is stuff like this:

```
LT_INIT([win32-dll disable-static])
have_w32_system=no
have_w32ce_system=no
```

indicating that windows is a supported target!

**Comment by FrankXie05** [comment]
Reopen by PR https://github.com/microsoft/vcpkg/pull/36022

**Comment by dg0yt** [comment]
> Reopen by PR #36022

Invalid. https://github.com/microsoft/vcpkg/pull/36022#issuecomment-1876468846.
