### ISSUE TITLE
can't build any packages on linux ecryptfs file system

### ISSUE THREAD

**Issue by hmoffatt** [microsoft/vcpkg#24794]
**Describe the bug**
All packages fail to build when running on an ecryptfs (encrypted file system) overlay on linux whenever vcpkg needs to copy a file.

For example a simple install of libsass fails with:

```
/mnt/vss/_work/1/s/src/vcpkg/build.cpp(1456): copy_file("/home/hamish/dev/vcpkg/buildtrees/libsass/x64-linux.vcpkg_abi_info.txt", "/home/hamish/dev/vcpkg/packages/libsass_x64-linux/share/libsass/vcpkg_abi_info.txt"): Invalid argument
```

If I run from tmpfs then it works except copying to the cache (on ecryptfs) fails:
```
Failed to store binary cache /home/hamish/.cache/vcpkg/archives/9d/9d3a160067d30b121be7c5419170f7ba04de2d8102b46fd527ab5ff12f530e85.zip: Invalid argument
```

`strace` shows that `sendfile` calls are failing with invalid argument. The sendfile manual page says that code may need to fallback to read/write for copying if sendfile fails, which doesn't seem to happen in https://github.com/microsoft/vcpkg-tool/blob/main/src/vcpkg/base/files.cpp#L2890

**Environment**
- OS: Linux (Debian, glibc)
- Compiler: revision

Cannot reproduce on WSL2 because there is no ecryptfs in the kernel.

**To Reproduce**
1. Mount encrypted file system
```mkdir orig mnt && sudo mount -t ecryptfs mnt orig```

2. Checkout vcpkg and bootstrap
3. Build any package

**Expected behavior**
Package should install.

**Failure logs**
Install fails with:
```
/mnt/vss/_work/1/s/src/vcpkg/build.cpp(1456): copy_file("/home/hamish/src/ecrtest/mnt/vcpkg/buildtrees/vcpkg-cmake/x64-linux.vcpkg_abi_info.txt", "/home/hamish/src/ecrtest/mnt/vcpkg/packages/vcpkg-cmake_x64-linux/share/vcpkg-cmake/vcpkg_abi_info.txt"): Invalid argument
```

strace shows

```
openat(AT_FDCWD, "/home/hamish/src/ecrtest/mnt/vcpkg/buildtrees/vcpkg-cmake/x64-linux.vcpkg_abi_info.txt", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=1445, ...}) = 0
openat(AT_FDCWD, "/home/hamish/src/ecrtest/mnt/vcpkg/packages/vcpkg-cmake_x64-linux/share/vcpkg-cmake/vcpkg_abi_info.txt", O_WRONLY|O_CREAT|O_EXCL, 0100666) = 4
fstat(4, {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
sendfile(4, 3, [0], 1445)               = -1 EINVAL (Invalid argument)
```

**Comment by hmoffatt** [comment]
Same cause as #24585 most likely.

**Comment by JackBoosY** [comment]
It should be the same issue with #24585.

**Comment by JackBoosY** [comment]
Ops, sorry, please track #24585.
