### ISSUE TITLE
[vcpkg upgrade] lapack-reference build error

### ISSUE THREAD

**Issue by eunhwanshin** [microsoft/vcpkg#24793]
package: lapack-reference[blas-select,core,noblas]:x64-windows -> 3.10.0
    vcpkg-tool version: 2022-03-30-692785ac944e81417840c6de244fb3e18a4b35eb
    vcpkg-scripts version: 8f1d60f20 2022-05-18 (70 minutes ago)

**Comment by Adela0814** [comment]
@eunhwanshin  Please provide the reproduce steps and all failure logs.

**Comment by eunhwanshin** [comment]
[stdout-x64-windows.log](https://github.com/microsoft/vcpkg/files/8731968/stdout-x64-windows.log)

It happed while doing the following steps:
1. Checkout https://github.com/RainerKuemmerle/g2o.git
2. Run install-deps-windows.bat which exists under "script" folder

**Comment by Neumann-A** [comment]
remove `clapack` from the script and retry from a clean directory.

**Comment by JackBoosY** [comment]
```
CMake Error at ports/lapack-reference/portfile.cmake:8 (message):
  Can't build lapack-reference if clapack is installed.  Please remove
  clapack:x64-windows, and try to install lapack-reference:x64-windows again.
```

**Comment by Adela0814** [comment]
@eunhwanshin Have you tried the solutions above?

**Comment by eunhwanshin** [comment]
Still does not work. Below are the error messages:

The following packages are not installed:
    clapack:x64-windows
    suitesparse:x64-windows

internal error: D:\a\_work\1\s\src\vcpkg\commands.upgrade.cpp(191): vcpkg has crashed; no additional details are available.
Please open an issue at https://github.com/microsoft/vcpkg/issues/new?template=other-type-of-bug-report.md&labels=category:vcpkg-bug with detailed steps to reproduce the problem.
Computing installation plan...
The following packages are already installed:
    ceres[core]:x64-windows -> 2.1.0#1
    eigen3[core]:x64-windows -> 3.4.0#2
    openblas[core]:x64-windows -> 0.3.20
The following packages will be built and installed:
    clapack[core]:x64-windows -> 3.2.1#20
  * lapack[core]:x64-windows -> 2022-02-22
  * lapack-reference[blas-select,core,noblas]:x64-windows -> 3.10.0
    suitesparse[core]:x64-windows -> 5.8.0#1
Additional packages (*) will be modified to complete this operation.
Package ceres:x64-windows is already installed
Package eigen3:x64-windows is already installed
Package openblas:x64-windows is already installed
Detecting compiler hash for triplet x64-windows...
Restored 1 packages from C:\Users\EunHwanShin\AppData\Local\vcpkg\archives in 512.6 ms. Use --debug to see more details.
Starting package 1/4: clapack:x64-windows
Installing package clapack[core]:x64-windows...
Elapsed time for package clapack:x64-windows: 917.9 ms
Starting package 2/4: lapack-reference:x64-windows
Building package lapack-reference[blas-select,core,noblas]:x64-windows...
CMake Error at ports/lapack-reference/portfile.cmake:8 (message):
  Can't build lapack-reference if clapack is installed.  Please remove
  clapack:x64-windows, and try to install lapack-reference:x64-windows again.
Call Stack (most recent call first):
  scripts/ports.cmake:146 (include)


error: building lapack-reference:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+lapack-reference
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[lapack-reference]+Build+error
including:
  package: lapack-reference[blas-select,core,noblas]:x64-windows -> 3.10.0
    vcpkg-tool version: 2022-03-30-692785ac944e81417840c6de244fb3e18a4b35eb
    vcpkg-scripts version: 8f1d60f20 2022-05-18 (9 days ago)

Additionally, attach any relevant sections from the log files above.

**Comment by autoantwort** [comment]
@JackBoosY This is not a vcpkg bug

**Comment by JonLiu1993** [comment]
The latest vcpkg cannot reproduce this issue. If the problem still exists, please reopen it.
