### ISSUE TITLE
[icu] build failure

### ISSUE THREAD

**Issue by nadiaholmquist** [microsoft/vcpkg#24806]
**Host Environment**
- OS: macOS 12.4
- Compiler: Apple clang version 13.1.6 (clang-1316.0.21.2.5)

**To Reproduce**
`./vcpkg install icu`

**Failure logs**
```
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:128 (message):
    Command failed: /usr/local/bin/bash -c "V=1 ./../src/c-71_1-src-08c83f7de1.clean/source/configure  \"--disable-samples\" \"--disable-tests\" \"--disable-layoutex\" \"--disable-silent-rules\" \"--verbose\" \"--disable-shared\" \"--enable-static\" \"--enable-debug\" \"--disable-release\" \"--prefix=/opt/vcpkg/installed/x64-osx/debug\" \"--bindir=\\${prefix}/../tools/icu/debug/bin\" \"--sbindir=\\${prefix}/../tools/icu/debug/sbin\" \"--libdir=\\${prefix}/lib\" \"--includedir=\\${prefix}/../include\" \"--datarootdir=\\${prefix}/share/icu\""
```
[config-x64-osx-dbg-err.log](https://github.com/microsoft/vcpkg/files/8732161/config-x64-osx-dbg-err.log)
[config-x64-osx-dbg-out.log](https://github.com/microsoft/vcpkg/files/8732163/config-x64-osx-dbg-out.log)

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by dg0yt** [comment]
> configure: error: 'autoconf-archive' is missing

brew install autoconf-archive

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
