### ISSUE TITLE
Building boost:x64-Windows failed

### ISSUE THREAD

**Issue by haquocviet** [Microsoft/vcpkg#2481]
Hi,
I got no problem when built previous versions of boost (<= 1.65) via vcpkg.
Since vcpkg does the breaking change for boost by tearing it into small modules, this is the first time I try to build boost 1.66 and get failure. 
I have MSVC 2017 15.5 is installed.

Here are the errors, please check:

E:\vcpkg>vcpkg install cpprestsdk:x64-Windows
The following packages will be built and installed:
  * boost-algorithm[core]:x64-windows
  * boost-array[core]:x64-windows
  * boost-asio[core]:x64-windows
  * boost-assert[core]:x64-windows
  * boost-atomic[core]:x64-windows
  * boost-bind[core]:x64-windows
  * boost-chrono[core]:x64-windows
  * boost-concept-check[core]:x64-windows
  * boost-container[core]:x64-windows
  * boost-context[core]:x64-windows
  * boost-core[core]:x64-windows
  * boost-coroutine[core]:x64-windows
  * boost-date-time[core]:x64-windows
  * boost-exception[core]:x64-windows
  * boost-function[core]:x64-windows
  * boost-function-types[core]:x64-windows
  * boost-functional[core]:x64-windows
  * boost-fusion[core]:x64-windows
  * boost-integer[core]:x64-windows
  * boost-intrusive[core]:x64-windows
  * boost-io[core]:x64-windows
  * boost-iterator[core]:x64-windows
  * boost-lambda[core]:x64-windows
  * boost-lexical-cast[core]:x64-windows
  * boost-math[core]:x64-windows
  * boost-move[core]:x64-windows
  * boost-mpl[core]:x64-windows
  * boost-numeric-conversion[core]:x64-windows
  * boost-optional[core]:x64-windows
  * boost-pool[core]:x64-windows
  * boost-range[core]:x64-windows
  * boost-ratio[core]:x64-windows
  * boost-rational[core]:x64-windows
  * boost-regex[core]:x64-windows
  * boost-smart-ptr[core]:x64-windows
  * boost-system[core]:x64-windows
  * boost-thread[core]:x64-windows
  * boost-tokenizer[core]:x64-windows
  * boost-tuple[core]:x64-windows
  * boost-type-index[core]:x64-windows
  * boost-type-traits[core]:x64-windows
  * boost-typeof[core]:x64-windows
  * boost-unordered[core]:x64-windows
  * boost-utility[core]:x64-windows
  * boost-winapi[core]:x64-windows
    cpprestsdk[core]:x64-windows
  * websocketpp[core]:x64-windows
  
  // ...
  // _Many boost modules are built successfully here._
  // ...
  
  Installing package boost-smart-ptr:x64-windows... done
Elapsed time for package boost-smart-ptr:x64-windows: 2.246 s
Starting package 17/47: boost-regex:x64-windows
Building package boost-regex:x64-windows...
-- CURRENT_INSTALLED_DIR=E:/vcpkg/installed/x64-windows
-- DOWNLOADS=E:/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=E:/vcpkg/packages/boost-regex_x64-windows
-- CURRENT_BUILDTREES_DIR=E:/vcpkg/buildtrees/boost-regex
-- CURRENT_PORT_DIR=E:/vcpkg/ports/boost-regex/.
-- Using cached E:/vcpkg/downloads/boostorg-regex-boost-1.66.0.tar.gz
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:44 (message):
    Command failed: E:/vcpkg/installed/x64-windows/tools/boost-build/b2.exe;--stagedir=E:/vcpkg/buildtrees/boost-regex/x64-windows-rel/stage;--build-dir=E:/vcpkg/buildtrees/boost-regex/x64-windows-rel;--user-config=E:/vcpkg/buildtrees/boost-regex/x64-windows-rel/user-config.jam;-j8;--debug-configuration;--debug-building;--debug-generators;--disable-icu;--ignore-site-config;--hash;-q;threadapi=win32;threading=multi;runtime-link=shared;link=shared;address-model=64;architecture=x86;toolset=msvc-14.1;variant=release;debug-symbols=on
    Working Directory: E:/vcpkg/buildtrees/boost-regex/src/regex-boost-1.66.0
    See logs for more information:
      E:\vcpkg\buildtrees\boost-regex\build-x64-windows-rel-out.log
      E:\vcpkg\buildtrees\boost-regex\build-x64-windows-rel-err.log

Call Stack (most recent call first):
  installed/x64-windows/share/boost-vcpkg-helpers/boost-modular.cmake:174 (vcpkg_execute_required_process)
  ports/boost-regex/portfile.cmake:20 (boost_modular_build)
  scripts/ports.cmake:72 (include)

Error: Building package boost-regex:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-regex:x64-windows
  Vcpkg version: 0.0.100-2017-12-31-79fbc50de998f25d8ecebb0946521869e50f7fff

Additionally, attach any relevant sections from the log files above.
  
  
**build-x64-windows-rel-err.log is empty.
build-x64-windows-rel-out.log content:**

//	_some other text here_

notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>arm/<address-model>32', setup: 'call "E:/vcpkg/installed/x64-windows/share/boost-vcpkg-helpers/nothing.bat" x86_arm >nul
'
notice: [cmdline-cfg] toolset msvc-14.1 not previously configured; attempting to auto-configure now
error: msvc initialization: parameter 'version' inconsistent
error: no value was specified in earlier initialization
error: an explicit value is specified now

**Note that I tried to modify checking of _MSC_VER value in** 
E:\vcpkg\buildtrees\boost-config\src\config-boost-1.66.0\include\boost\config\compiler\visualc.hpp
**to be consistent with version VS2017 15.5 but it did not help.**

**Comment by JackBoosY** [comment]
Hi @haquocviet , this bug seems to have been fixed, plz update vcpkg and rebuild it.
Thx.

**Comment by haquocviet** [comment]
The issues was solved last year. Now I no longer build boost via the vcpkg anymore. Building directly via boost's tool is much faster, simpler, more flexible and more important, I do not need to wait for vcpkg to update the new boost version.
Thanks anyway.
