### ISSUE TITLE
[botan] fix port

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#24814]
https://github.com/microsoft/vcpkg/pull/24811#issuecomment-1132203348

indicates:
- the port needs proper compiler setup (so that custom toolchains work)
- the port needs proper dependency setup (so that sqlite does not get picked up by accident)

**Comment by Adela0814** [comment]
May be fixed by PR: https://github.com/microsoft/vcpkg/pull/27750.
