### ISSUE TITLE
Libmariadb x64 windows

### ISSUE THREAD

**Issue by Alexv45** [microsoft/vcpkg#24825]
error: building libmariadb:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libmariadb
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[libmariadb]+Build+error
Include '[libmariadb] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-05-05-67e17c1782801cf481be9ac0b3765dff3e4bdeb8
    vcpkg-scripts version: 7e3dcf74e 2022-05-19 (5 hours ago)

Windows 11

Reproduce:
Install visual studio 2019,
git clone https://github.com/Microsoft/vcpkg
cd vcpkg
.\bootstrap-vcpkg.bat
cd C:\vcpkg
.\vcpkg --triplet x64-windows install boost-asio boost-filesystem boost-iostreams boost-lockfree boost-system boost-variant cryptopp curl jsoncpp libmariadb luajit mpir pugixml spdlog libmysql
.\vcpkg integrate install

**Comment by JackBoosY** [comment]
Please provide the **full** output and the logs mentioned in the output.

Thanks.

**Comment by Alexv45** [comment]
[vcpkg-manifest-install.log](https://github.com/microsoft/vcpkg/files/8737807/vcpkg-manifest-install.log)

I see check this file for the error, here is the file

**Comment by JackBoosY** [comment]
```
Installing 1/5 libmariadb:x64-windows...
Elapsed time to handle libmariadb:x64-windows: 213 ms
```
It seems that libmariadb was already successfully installed. And I couldn't find any errors in the log.
Can you please provide your configure failure log?

**Comment by Alexv45** [comment]
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/8738017/config-x64-windows-out.log)

There is the libmariadb log

Error on visual:
![image](https://user-images.githubusercontent.com/89811188/169493613-f86bf783-9540-4d9a-bdb0-06de8b036fc4.png)

**Comment by JackBoosY** [comment]
```
CMake Error at E:/vcpkg/downloads/tools/cmake-3.20.2-windows/cmake-3.20.2-windows-i386/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
Call Stack (most recent call first):
  E:/vcpkg/downloads/tools/cmake-3.20.2-windows/cmake-3.20.2-windows-i386/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  E:/vcpkg/downloads/tools/cmake-3.20.2-windows/cmake-3.20.2-windows-i386/share/cmake-3.20/Modules/FindZLIB.cmake:120 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  E:/vcpkg/scripts/buildsystems/vcpkg.cmake:772 (_find_package)
  CMakeLists.txt:197 (FIND_PACKAGE)
```
Did you install zlib manually into a path included in your environment PATH ?

**Comment by Alexv45** [comment]
Nop i didnt do anything,
Just last week i use git command to update Vcpkg.. and now i cannot compile.

I Just start from fresh, re installing VCPKG is giving an error right now:

![image](https://user-images.githubusercontent.com/89811188/169506471-e2c5757b-1ea2-4122-8e9f-6ba298b7a49b.png)

**Comment by dg0yt** [comment]
I don't think you gave us the logs from the original issue.
What didn't change is that you can't install libmariadb and libmysql at the same time:
https://github.com/microsoft/vcpkg/blob/7e3dcf74e37034eea358934a90a11d618520e139/ports/libmariadb/portfile.cmake#L1-L3

So this original step "to reproduce" is an expected fail:
~~~
.\vcpkg --triplet x64-windows install boost-asio boost-filesystem boost-iostreams boost-lockfree boost-system boost-variant cryptopp curl jsoncpp libmariadb luajit mpir pugixml spdlog libmysql
~~~

**Comment by Alexv45** [comment]
Thanks @dg0yt  i have removed libmysql , now
I opened visual studio, Installed components  required, SDK 10.0.19...
![image](https://user-images.githubusercontent.com/89811188/169621648-fc923471-3fe4-4444-b309-1d8abecec0ee.png)
Already installed,

Then: .\vcpkg install --triplet x64-windows boost-asio boost-filesystem boost-iostreams boost-lockfree boost-system boost-variant cryptopp libmariadb luajit mpir pugixml

![image](https://user-images.githubusercontent.com/89811188/169621697-aca5755d-cdb1-4d2f-a5e7-9dcf0c35764b.png)

Then it says it doesn't found the SDK version and giving error on install mpir:

[build-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/8744873/build-x64-windows-rel-out.log)

**Comment by Alexv45** [comment]
Downloaded from
[2019.12](https://github.com/microsoft/vcpkg/releases/tag/2019.12)
vcpkg (2019.12.31)
To the latest package today.

MPIR is giving an error on build on all version like here
https://github.com/microsoft/vcpkg/issues/24825#issuecomment-1133443864

I got Visual Studio 2019 Complete, 93 GB installed, im sure is not an additional extension/tool from visual, all SDK installed, what happens ?

The compilation i done it like 200 times for a Forum game, since now i cannot compile anyone of them, huuuhu.
There is the Tutorial of the compilation, and yes, all c++ redistributables & git installed.
https://tibiaking.com/forums/topic/101588-windowsvc2019-compilando-sources-otservbr-12x/
