### ISSUE TITLE
[protobuf] update to 3.20.1

### ISSUE THREAD

**Issue by 0x44449** [microsoft/vcpkg#24822]
Library name: protobuf

New version number: 3.20.1

Other information that may be useful (release notes, etc...)
has many changes in 3.20.0
[https://github.com/protocolbuffers/protobuf/releases/tag/v3.20.0](https://github.com/protocolbuffers/protobuf/releases/tag/v3.20.0)

**Comment by JonLiu1993** [comment]
Fixed by #24400
