### ISSUE TITLE
[libsodium] Missing header file

### ISSUE THREAD

**Issue by leecbaker** [Microsoft/vcpkg#2482]
Libsodium doesn't install the top level header file- this is critical for usage of this library.

I think the fix is pretty simple- one additional header file needs to be installed. It's at "${SOURCE_PATH}/src/libsodium/include/sodium.h".

**Comment by myd7349** [comment]
Fixed by https://github.com/Microsoft/vcpkg/pull/2986

**Comment by JackBoosY** [comment]
Hi @leecbaker , thanks for reporting this issue!
Please open a new issue if this is still a problem for you.
Thx.
