### ISSUE TITLE
can not install curl[http2] library on macos 12

### ISSUE THREAD

**Issue by xengine-qyt** [microsoft/vcpkg#24839]
macos@192 vcpkg % ./vcpkg search curl
azure-core-cpp[curl]                      Libcurl HTTP transport implementation
cfitsio[curl]                             UseCurl
cocoyaxi[libcurl]                         libcurl with OpenSSL support
cpr                      1.8.3            C++ Requests is a simple wrapper around libcurl inspired by the excellent ...
cpr[ssl]                                  Enable SSL support
curl                     7.83.1#2         A library for transferring data with URLs
curl[brotli]                              brotli support (brotli)
curl[c-ares]                              c-ares support
curl[http2]                               HTTP2 support
curl[idn]                                 Default IDN support
curl[idn2]                                idn2 support (libidn2)
curl[mbedtls]                             SSL support (mbedTLS)
curl[non-http]                            Enables protocols beyond HTTP/HTTPS/HTTP2
curl[openssl]                             SSL support (OpenSSL)
curl[schannel]                            SSL support (Secure Channel)
curl[sectransp]                           SSL support (sectransp)
curl[ssh]                                 SSH support via libssh2
curl[ssl]                                 Default SSL backend
curl[sspi]                                SSPI support
curl[tool]                                Builds curl executable
curl[winidn]                              WinIDN support
curl[winldap]                             LDAP support (WinLDAP). This feature does not include LDAPS support.
curl[winssl]                              Legacy name for schannel
curl[wolfssl]                             SSL support (wolfSSL)
curlpp                   2018-06-15#7     C++ wrapper around libcURL
czmq[curl]                                Build with libcurl
libcurl-simple-https     2022-02-14       Very simple HTTPS interface built atop libcurl
oatpp-curl               1.3.0            Oat++ Modern web framework curl module to use libcurl as a RequestExecutor...
poppler[curl]                             curl for poppler
restclient-cpp           2022-02-09       Simple REST client for C++. It wraps libcurl for HTTP requests.
The result may be outdated. Run `git pull` to get the latest results.

If your port is not listed, please open an issue at and/or consider making a pull request:
    https://github.com/Microsoft/vcpkg/issues
macos@192 vcpkg % ./vcpkg install curl[http2] 
zsh: no matches found: curl[http2]

**Comment by xengine-qyt** [comment]
it is last version of vcpkg

**Comment by autoantwort** [comment]
This is a zsh 'issue'. Run `./vcpkg install 'curl[http2]'`

**Comment by Cheney-W** [comment]
@xengine-qyt Is the problem solved?

**Comment by Neithari** [comment]
> @xengine-qyt Is the problem solved?

The problem is still present. Stumbled on the same issue with imgui. #24965
Is this fixable on your side or simply a syntax quirk from zsh?

**Comment by autoantwort** [comment]
> Is this fixable on your side or simply a syntax quirk from zsh?

It is a syntax quirk from zsh
