### ISSUE TITLE
[Documentation] Get Started describes bootstrap script as building vcpkg, and is light on details

### ISSUE THREAD

**Issue by nat42** [microsoft/vcpkg#24831]
The Get Started page https://vcpkg.io/en/getting-started.html says to "Step 2: Run the bootstrap script to _build_ vcpkg" and for Windows it says to run bootstrap-vcpkg.bat to do this but per the output to the commandline and per https://github.com/microsoft/vcpkg/pull/15474 vcpkg is not built from source and instead a binary executable is downloaded.

I feel the documentation should be updated.

While I think reading the PR/issue the change was for has given me some appreciation for why a binary is downloaded, I do feel it might be worth stating as a user getting started with vcpkg, I must say it feels rather odd and a little wrong to clone a github repo and run a batch file in that repo only for that file to download a prebuilt executable, that is the major part of that tooling, and then to find that the source isn't even in the cloned repo but rather another project repo.

**Comment by AugP** [comment]
We are doing a pass through our documentation over the next few months. I added this as something we should fix. Thanks for reporting this!
