### ISSUE TITLE
[cppgraphqlgen] Build error

### ISSUE THREAD

**Issue by panthers-00** [microsoft/vcpkg#24833]
**Host Environment**
- OS: Linux (in WSL)
- Compiler: gcc --version
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**To Reproduce**
`./vcpkg install cppgraphqlgen`

**Failure logs**
-Cut and paste the appropriate build messages from the console output.
Computing installation plan...
The following packages will be built and installed:
    cppgraphqlgen[core]:x64-linux -> 4.4.1
Detecting compiler hash for triplet x64-linux...
Restored 0 packages from /home/user/.cache/vcpkg/archives in 5.2 us. Use --debug to see more details.
Installing 1/1 cppgraphqlgen:x64-linux...
Building cppgraphqlgen[core]:x64-linux...
-- Using cached microsoft-cppgraphqlgen-v4.4.1.tar.gz.
-- Cleaning sources at /home/user/vcpkg/buildtrees/cppgraphqlgen/src/v4.4.1-f9e72237e0.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/user/vcpkg/downloads/microsoft-cppgraphqlgen-v4.4.1.tar.gz
-- Using source at /home/user/vcpkg/buildtrees/cppgraphqlgen/src/v4.4.1-f9e72237e0.clean
-- Configuring x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:128 (message):
    Command failed: /home/user/vcpkg/downloads/tools/cmake-3.22.2-linux/cmake-3.22.2-linux-x86_64/bin/cmake /home/user/vcpkg/buildtrees/cppgraphqlgen/src/v4.4.1-f9e72237e0.clean -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/home/user/vcpkg/packages/cppgraphqlgen_x64-linux/debug -DGRAPHQL_BUILD_TESTS=OFF -DGRAPHQL_UPDATE_VERSION=OFF -DGRAPHQL_UPDATE_SAMPLES=OFF -DGRAPHQL_INSTALL_CONFIGURATIONS=Release -DCMAKE_MAKE_PROGRAM=/home/user/vcpkg/downloads/tools/ninja/1.10.2-linux/ninja -DCMAKE_SYSTEM_NAME=Linux -DBUILD_SHARED_LIBS=OFF -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/home/user/vcpkg/scripts/toolchains/linux.cmake -DVCPKG_TARGET_TRIPLET=x64-linux -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=external -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=/home/user/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_LINKER_FLAGS_RELEASE= -DVCPKG_LINKER_FLAGS_DEBUG= -DVCPKG_TARGET_ARCHITECTURE=x64 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -D_VCPKG_ROOT_DIR=/home/user/vcpkg -D_VCPKG_INSTALLED_DIR=/home/user/vcpkg/installed -DVCPKG_MANIFEST_INSTALL=OFF -DGRAPHQL_INSTALL_CMAKE_DIR=/home/user/vcpkg/packages/cppgraphqlgen_x64-linux/debug/share -DGRAPHQL_INSTALL_TOOLS_DIR=/home/user/vcpkg/packages/cppgraphqlgen_x64-linux/debug/tools
    Working Directory: /home/user/vcpkg/buildtrees/cppgraphqlgen/x64-linux-dbg
    Error code: 1
    See logs for more information:
      /vcpkg/buildtrees/cppgraphqlgen/config-x64-linux-dbg-out.log
      /home/user/vcpkg/buildtrees/cppgraphqlgen/config-x64-linux-dbg-err.log

Call Stack (most recent call first):
  installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:343 (vcpkg_execute_required_process)
  ports/cppgraphqlgen/portfile.cmake:9 (vcpkg_cmake_configure)
  scripts/ports.cmake:146 (include)

error: building cppgraphqlgen:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+cppgraphqlgen
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[cppgraphqlgen]+Build+error
Include '[cppgraphqlgen] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-05-05-67e17c1782801cf481be9ac0b3765dff3e4bdeb8
    vcpkg-scripts version: 7e3dcf74e 2022-05-19 (17 hours ago)

-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

[config-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/8743743/config-x64-linux-dbg-out.log)
[config-x64-linux-dbg-err.log](https://github.com/microsoft/vcpkg/files/8743744/config-x64-linux-dbg-err.log)
[CMakeError.log](https://github.com/microsoft/vcpkg/files/8743762/CMakeError.log)
[CmakeOutput.log](https://github.com/microsoft/vcpkg/files/8743764/CmakeOutput.log)

**Comment by LilyWangLL** [comment]
This is a known issue. The reason is as below in ci.baseline.txt. `cppgraphqlgen` needs gcc 10.3.0 to support C++20 coroutine. If you want use `cppgraphqlgen` on Linux, you could upgrade your gcc version.

> /# The x64-linux pipeline uses gcc 9.3.0, which lacks C++20 coroutine support.
> /# This is known to work on x64-linux as of gcc 10.3.0.
> cppgraphqlgen:x64-linux=fail

**Comment by panthers-00** [comment]
That resolved the issue. Thank you!
