### ISSUE TITLE
[angle] Build error

### ISSUE THREAD

**Issue by GJD-first** [microsoft/vcpkg#24834]
**Host Environment**
- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**
`./vcpkg install xxxx`

**Failure logs**
-Cut and paste the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by JonLiu1993** [comment]
@GJD-first , Thanks for posting this issue, please follow the template above to fill in your reproduction environment, reproduction steps and error log

**Comment by dg0yt** [comment]
Probably another duplicate of #24704 (internal compiler error).

**Comment by JonLiu1993** [comment]
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!
