### ISSUE TITLE
Cannot Using Installed Library with CMake (Toolchain File)

### ISSUE THREAD

**Issue by chuongvhn** [Microsoft/vcpkg#2484]
I am following this [tut](https://github.com/Microsoft/vcpkg/blob/master/docs/examples/using-sqlite.md).
Step 2: we have 2 options, the first one **S/MSBuild Project (User-wide integration)** is working as expectation but the second one **CMAKE (Toolchain FIle)**  
* Scenario:
 1. There are main.cpp and CMakeLists.text in build folder as described in the tut
 2. Invoke CMake generator with: PS> cmake .. -DCMAKE_TOOLCHAIN_FILE=<path to vcpkg\scripts\buildsystems\vcpkg.cmake>
* Expected: Generation is successful with configuration in CMakeLists. Sqlite3 can be found without any file path direction.
* Actual:  generation is fail due to Sqlite 3 is not found.
>"PS C:\Users\vohoa\test_vcpkg\build> cmake .. -DCMAKE_TOOLCHAIN_FILE=C:\Users\vohoa\vcpkg\scripts\buildsystems\
vcpkg.cmake
CMake Error at CMakeLists.txt:5 (find_package):
  By not providing "FindSqlite3.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Sqlite3", but
  CMake did not find one.
  Could not find a package configuration file provided by "Sqlite3" with any
  of the following names:
    Sqlite3Config.cmake
    sqlite3-config.cmake
  Add the installation prefix of "Sqlite3" to CMAKE_PREFIX_PATH or set
  "Sqlite3_DIR" to a directory containing one of the above files.  If
  "Sqlite3" provides a separate development package or SDK, be sure it has
  been installed.
-- Configuring incomplete, errors occurred!
See also "C:/Users/vohoa/test_vcpkg/build/CMakeFiles/CMakeOutput.log"."

Sqlite is installed via vcpkg:  
>"PS C:\Users\vohoa\vcpkg> .\vcpkg.exe list"
>"sqlite3:x86-windows                                3.21.0           SQLite is a software library that implemen"

**Comment by hmenke** [comment]
Might be related to #2476

**Comment by ras0219-msft** [comment]
Sorry for missing this issue, and thanks for posting!

Could you confirm that `C:\Users\vohoa\vcpkg\installed\x86-windows\share\sqlite3\sqlite3Config.cmake` exists? Additionally, could you add a statement to your cmake project right after the `project()` directive:
```cmake
message("VCPKG_TARGET_TRIPLET=${VCPKG_TARGET_TRIPLET}")
```

**Comment by chuongvhn** [comment]
Hi,
I've setup my PC with brand new Wins 10. I'm trying to reproduce the issue but by now the issue no longer occurs. I can build as following the tutorial.
Anyway here are some information you query:
1.  Yes the location is exist
2.  VCPKG_TARGET_TRIPLET=x86-windows
Thanks for your support.
