### ISSUE TITLE
[fontconfig] Build error

### ISSUE THREAD

**Issue by axojhf** [microsoft/vcpkg#24841]
**Host Environment**
- OS: Windows 10
- Compiler: gcc version 11.2.0 (x86_64-posix-seh-rev3, Built by MinGW-W64 project)
-  vcpkg-tool version: 2022-05-05-67e17c1782801cf481be9ac0b3765dff3e4bdeb8
-  vcpkg-scripts version: 314018fef 2022-05-20

**To Reproduce**
`vcpkg install fontconfig:x64-mingw-static`

**Failure logs**
```
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:128 (message):
    Command failed: D:/vcpkg/downloads/tools/python/python-3.10.2-x64/python.exe D:/vcpkg/installed/x64-windows/tools/meson/meson.py -Ddoc=disabled -Dcache-build=disabled -Dtests=disabled --buildtype plain --backend ninja --wrap-mode nodownload --native D:/vcpkg/buildtrees/fontconfig/meson-native-x64-mingw-static.log --default-library static --libdir lib --native D:/vcpkg/buildtrees/fontconfig/meson-native-x64-mingw-static-debug.log -Ddebug=true --prefix D:/vcpkg/packages/fontconfig_x64-mingw-static/debug --includedir ../include -Dcmake_prefix_path=['D:/vcpkg/installed/x64-mingw-static/debug','D:/vcpkg/installed/x64-mingw-static','D:/vcpkg/installed/x64-mingw-static/share'] D:/vcpkg/buildtrees/fontconfig/src/2.14.0-523cc719dc.clean
    Working Directory: D:/vcpkg/buildtrees/fontconfig/x64-mingw-static-dbg
    Error code: 1
    See logs for more information:
      D:\vcpkg\buildtrees\fontconfig\config-x64-mingw-static-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_meson.cmake:470 (vcpkg_execute_required_process)
  ports/fontconfig/portfile.cmake:19 (vcpkg_configure_meson)
  scripts/ports.cmake:146 (include)
```

config-x64-mingw-static-dbg-out.log
```
WARNING: Recommend using either -Dbuildtype or -Doptimization + -Ddebug. Using both is redundant since they override each other. See: https://mesonbuild.com/Builtin-options.html#build-type-options
The Meson build system
Version: 0.60.2
Source dir: D:\vcpkg\buildtrees\fontconfig\src\2.14.0-523cc719dc.clean
Build dir: D:\vcpkg\buildtrees\fontconfig\x64-mingw-static-dbg
Build type: native build
Project name: fontconfig
Project version: 2.14.0
C compiler for the host machine: D:/Qt/Tools/mingw1120_64/bin/x86_64-w64-mingw32-gcc.exe (gcc 11.2.0 "x86_64-w64-mingw32-gcc.exe (x86_64-posix-seh-rev3, Built by MinGW-W64 project) 11.2.0")
C linker for the host machine: D:/Qt/Tools/mingw1120_64/bin/x86_64-w64-mingw32-gcc.exe ld.bfd 2.37
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: D:/vcpkg/downloads/tools/msys2/9a1ec3f33446b195/mingw32/bin/pkg-config.exe (0.29.2)
Run-time dependency freetype2 found: YES 24.1.18
Run-time dependency expat found: YES 2.4.8
Program python found: YES (D:/vcpkg/downloads/tools/python/python-3.10.2-x64/python.exe)
WARNING: Broken python installation detected. Python files installed by Meson might not be found by python interpreter.
 This warning can be avoided by setting "python.platlibdir" option.
WARNING: Broken python installation detected. Python files installed by Meson might not be found by python interpreter.
 This warning can be avoided by setting "python.purelibdir" option.
Has header "dirent.h" : YES 
Has header "fcntl.h" : YES 
Has header "stdlib.h" : YES 
Has header "string.h" : YES 
Has header "unistd.h" : YES 
Has header "sys/statvfs.h" : NO 
Has header "sys/vfs.h" : NO 
Has header "sys/statfs.h" : NO 
Has header "sys/param.h" : YES 
Has header "sys/mount.h" : NO 
Checking for function "link" : NO 
Checking for function "mkstemp" : YES 
Checking for function "mkostemp" : NO 
Checking for function "_mktemp_s" : YES 
Checking for function "mkdtemp" : NO 
Checking for function "getopt" : YES 
Checking for function "getopt_long" : YES 
Checking for function "getprogname" : NO 
Checking for function "getexecname" : NO 
Checking for function "rand" : YES 
Checking for function "random" : NO 
Checking for function "lrand48" : NO 
Checking for function "random_r" : NO 
Checking for function "rand_r" : NO 
Checking for function "readlink" : NO 
Checking for function "fstatvfs" : NO 
Checking for function "fstatfs" : NO 
Checking for function "lstat" : NO 
Checking for function "mmap" : NO 
Checking for function "vprintf" : YES 
Checking for function "FT_Get_BDF_Property" with dependency freetype2: YES 
Checking for function "FT_Get_PS_Font_Info" with dependency freetype2: YES 
Checking for function "FT_Has_PS_Glyph_Names" with dependency freetype2: YES 
Checking for function "FT_Get_X11_Font_Format" with dependency freetype2: YES 
Checking for function "FT_Done_MM_Var" with dependency freetype2: YES 
Header <fcntl.h> has symbol "posix_fadvise" : NO 
Checking whether type "struct statvfs" has member "f_basetype" : NO 
Checking whether type "struct statvfs" has member "f_fstypename" : NO 
Checking whether type "struct statfs" has member "f_flags" : NO 
Checking whether type "struct statfs" has member "f_fstypename" : NO 
Checking whether type "struct dirent" has member "d_type" : NO 
Checking for size of "void *" : 8
Checking for alignment of "void *" : 8
Checking for alignment of "double" : 8
Checking if "stdatomic.h atomics" : links: YES 
Checking if "Intel atomics" : links: YES 
Checking if "Solaris atomic ops" : links: NO 

..\src\2.14.0-523cc719dc.clean\meson.build:208:2: ERROR: C shared or static library 'getopt' not found

A full log can be found at D:\vcpkg\buildtrees\fontconfig\x64-mingw-static-dbg\meson-logs\meson-log.txt
```

**Additional context**
I try to install getopt:x64-mingw-static, but I find that no `.a` library file was generated.
In contrast, installing `getopt-win32:x64-windows-static` can provide `getopt.lib`.
I'm sorry I don't know if fontconfig can be compiled as a static library under mingw on Windows.

**Comment by SchaichAlonso** [comment]
Installing the getopt library is a nop on mingw over [this line](https://github.com/microsoft/vcpkg/blob/master/ports/getopt/vcpkg.json#L10).

**Comment by SchaichAlonso** [comment]
I don't have a mingw environment here, so I can't reproduce it over here. Can you try whether the pull request-ed patch fixes the build for you?

**Comment by axojhf** [comment]
> I don't have a mingw environment here, so I can't reproduce it over here. Can you try whether the pull request-ed patch fixes the build for you?

I'm sorry I couldn't compile it successfully

vcpkg-tool version: 2022-05-05-67e17c1782801cf481be9ac0b3765dff3e4bdeb8
vcpkg-scripts version: 193797555 2022-05-23 (10 hours ago)
`config-x64-mingw-static-dbg-out.log` also showed
`..\src\2.14.0-523cc719dc.clean\meson.build:208:2: ERROR: C shared or static library 'getopt' not found`

**Comment by dg0yt** [comment]
> * Compiler: gcc version 11.2.0 (x86_64-posix-seh-rev3, Built by MinGW-W64 project)
> ...
> **To Reproduce** Steps to reproduce the behavior: `vcpkg install fontconfig:x64-mingw-static`

This was mingw...

> Then I copied `getopt.h` to the `install` folder of `vcpkg\installed\x64-windows-static` and copied `libgetopt.a`(`libwingetopt.a` renamed) to the `lib` folder (and `debug/lib` folder).

... and x64-windows-static isn't. So this doesn't seem to fit.

For "windows" triplets, vcpkg does provides a port `getopt-win32`, and it is a proper dependency of `fontconfig`.
For "mingw" triplets, the required functions seem to come with mingw and don't need another library, as on other platforms.

**Comment by axojhf** [comment]
> > * Compiler: gcc version 11.2.0 (x86_64-posix-seh-rev3, Built by MinGW-W64 project)
> >   ...
> >   **To Reproduce** Steps to reproduce the behavior: `vcpkg install fontconfig:x64-mingw-static`
> 
> This was mingw...
> 
> > Then I copied `getopt.h` to the `install` folder of `vcpkg\installed\x64-windows-static` and copied `libgetopt.a`(`libwingetopt.a` renamed) to the `lib` folder (and `debug/lib` folder).
> 
> ... and x64-windows-static isn't. So this doesn't seem to fit.
> 
> For "windows" triplets, vcpkg does provides a port `getopt-win32`, and it is a proper dependency of `fontconfig`. For "mingw" triplets, the required functions seem to come with mingw and don't need another library, as on other platforms.

Well, I found `getopt.h` in the include directory of mingw, but why did the installation fail when I ran `vcpkg install fontconfig:x64-mingw-static`?
Can anyone reproduce this installation in a Windows mingw environment?

**Comment by dg0yt** [comment]
> Can anyone reproduce this installation in a Windows mingw environment?

I did.

> Well, I found `getopt.h` in the include directory of mingw, but why did the installation fail when I ran `vcpkg install fontconfig:x64-mingw-static`?

Because mingw provides the environment packages expect from a POSIX system: 
The getopt implementation is in a standard library, not in a separate library. But the patch in vcpkg makes the separate library required for all windows builds including mingw. 
That's why my workaround is to make `required: false` for that library.

**Comment by axojhf** [comment]
> > Can anyone reproduce this installation in a Windows mingw environment?
> 
> I did.
> 
> > Well, I found `getopt.h` in the include directory of mingw, but why did the installation fail when I ran `vcpkg install fontconfig:x64-mingw-static`?
> 
> Because mingw provides the environment packages expect from a POSIX system: The getopt implementation is in a standard library, not in a separate library. But the patch in vcpkg makes the separate library required for all windows builds including mingw. That's why my workaround is to make `required: false` for that library.

Thanks, sorry I am new to c/c++ programming and don't know much about the standard library under POSIX system, so I solved the problem in a very abnormal way.
