### ISSUE TITLE
[libpq] build failure

### ISSUE THREAD

**Issue by 0x8A63F77D** [microsoft/vcpkg#24856]
**Host Environment**
- OS: CentOS 7.6  (WSL2)
- Compiler: gcc (GCC) 11.2.1 20210728 (Red Hat 11.2.1-1)

**To Reproduce**
```bash
./vcpkg install libpq:x64-linux-dynamic --overlay-triplets /opt/vcpkg-overlay/triplets/
```
The file x64-linux-dynamic.cmake:
```cmake
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)

set(VCPKG_CMAKE_SYSTEM_NAME Linux)
```
**Failure logs**
Start from line 5707
```log
configure:15282: result: 0
configure:15302: checking size of bool
configure:15307: /opt/rh/devtoolset-11/root/bin/gcc -o conftest -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -fPIC -g  -D_GNU_SOURCE -I/opt/vcpkg/installed/x64-linux-dynamic/debug/lib/pkgconfig/../../../include  -L/opt/vcpkg/installed/x64-linux-dynamic/debug/lib   conftest.c -llz4d -lssl -lcrypto -lz -lpthread -lrt -ldl -lm  >&5
configure:15307: $? = 0
configure:15307: ./conftest
./conftest: error while loading shared libraries: liblz4d.so: cannot open shared object file: No such file or directory
configure:15307: $? = 127
configure: program exited with status 127
configure: failed program was:
| /* confdefs.h */
```

**Additional context**
The file liblz4d.so does not exist. And I searched on the Internet and no many results (Maybe that causes this issue? A typo or something else?) . But if I use `ln -s liblz4.so liblz4d.so` to create a link, it works.
Static version is fine.

**Comment by Osyotr** [comment]
This is the reason why there is no official `x64-linux-dynamic` triplet. You may want to apply patch from https://github.com/microsoft/vcpkg/pull/23035 to be able to work with dynamic libraries on Linux.

**Comment by 0x8A63F77D** [comment]
> This is the reason why there is no official `x64-linux-dynamic` triplet. You may want to apply patch from #23035 to be able to work with dynamic libraries on Linux.

Thank you for your reply. It's working now.
