### ISSUE TITLE
how to update an exist library to the new version, error: File does not have expected hash...

### ISSUE THREAD

**Issue by duuyia** [Microsoft/vcpkg#2485]
I want to update the tacopie library to the new version: 3.2.0, the current version is 2.4.1
how shuold i do? Is there any document about this?

I meet an error after I changed the version of tacopie to 3.2.0 in the port/tacopie/CONTROL & port/tacopie/portfile.cmake file, the error like this:
D:\Program Files\Libraries>vcpkg build tacopie
-- CURRENT_INSTALLED_DIR=D:/Program Files/Libraries/installed/x86-windows
-- DOWNLOADS=D:/Program Files/Libraries/downloads
-- CURRENT_PACKAGES_DIR=D:/Program Files/Libraries/packages/tacopie_x86-windows
-- CURRENT_BUILDTREES_DIR=D:/Program Files/Libraries/buildtrees/tacopie
-- CURRENT_PORT_DIR=D:/Program Files/Libraries/ports/tacopie/.
-- cpp-redis only supports static library linkage.
-- Using cached D:/Program Files/Libraries/downloads/Cylix-tacopie-3.2.0.tar.gz
-- Testing integrity of cached file...
CMake Error at D:/Program Files/Libraries/scripts/cmake/vcpkg_download_distfile.cmake:66 (message):

  File does not have expected hash:

          File path: [D:/Program Files/Libraries/downloads/Cylix-tacopie-3.2.0.tar.gz]
Expected hash: [a1579080412114d3899492cd9559bb0eadd6048c1f84ac66ec8ca47bd6fbb35306f0d203d789bd1b7ed0a0a5ab27434dfe6583a1c67873c85bca4b6e2a186d77]
Actual hash: [ 079b294b537aaffe3bcf43a485c3be5b15f633c3f7c70140032d60cb010d35b76e76ef4ddd7596f6bfaf3f7edca7cb086c67552efffbf65846e725d7be54ce72]

Please delete the file and retry if this file should be downloaded again.

Call Stack (most recent call first):
  D:/Program Files/Libraries/scripts/cmake/vcpkg_download_distfile.cmake:78 (test_hash)
  D:/Program Files/Libraries/scripts/cmake/vcpkg_from_github.cmake:106 (vcpkg_download_distfile)
  D:/Program Files/Libraries/ports/tacopie/portfile.cmake:7 (vcpkg_from_github)
  D:/Program Files/Libraries/scripts/ports.cmake:72 (include)

Elapsed time for package tacopie:x86-windows: 12.31 s
Error: Building package tacopie:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: tacopie:x86-windows
Vcpkg version: 0.0.100-2018-01-01-ead35fd00a0b82fcd7e2484a5265d3f7c47130dc

**Comment by crackedmind** [comment]
Just put actual hash in portfile :)

But if think we missed some new PRs: #2492 #2491

**Comment by duuyia** [comment]
thanks a lot..
