### ISSUE TITLE
How to add support for Clang/LLVM?

### ISSUE THREAD

**Issue by fsb4000** [Microsoft/vcpkg#2486]
I installed http://releases.llvm.org/5.0.1/LLVM-5.0.1-win64.exe and vcpkg
I tried example with sqlite3
```c
#include <sqlite3.h>
#include <stdio.h>

int main()
{
	printf("%s\n", sqlite3_libversion());
	return 0;
}
```
If I use Visual Studio 2017 (v141) everything is working.
![MSVC](https://i.imgur.com/9KGFcnC.png)

If I use Clang LLVM 5.0.1, I get " 'sqlite3.h' file not found"
![Clang](https://i.imgur.com/gD17Xkx.png)

What should I do for user-wide integration for both Clang and MSVC 2017?
Thank you!

**Comment by glachancecmaisonneuve** [comment]
![image](https://user-images.githubusercontent.com/8885056/35463779-62286824-02c0-11e8-8754-c586a113bdf3.png)

**Comment by fsb4000** [comment]
It works.
Thank you very much.
