### ISSUE TITLE
I can't install opencv

### ISSUE THREAD

**Issue by RadonCoding** [microsoft/vcpkg#24864]
**Describe the bug**
When i run the command "./vcpkg install opencv:x64-windows" i get a error

**Environment**
- OS: Windows

**To Reproduce**
1. Use latest version of vcpkg
2. ./vcpkg install opencv:x64-windows
3. See error
Repro code when

**Expected behavior**
I expected it to be installed without errors

**Failure logs**
[-(please attached failure logs)](https://pastebin.com/9yUMFgEZ)

**Comment by JonLiu1993** [comment]
@RadonCoding ,Thanks for posting this issue, I cannot repro this issue, could you please git pull the latest vcpkg and try again?
````
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\AppData\Local\vcpkg\archives\40\403e7905ada50a1230056390c527ea1d28861a7cfc87035ec00bb60473b2e160.zip
Installing package opencv4[core,default-features,dnn,jpeg,png,quirc,tiff,webp]:x64-windows...
Elapsed time for package opencv4:x64-windows: 8.377 min
Starting package 4/4: opencv:x64-windows
Building package opencv[core,default-features]:x64-windows...
-- Performing post-build validation
-- Performing post-build validation done
Installing package opencv[core,default-features]:x64-windows...
Elapsed time for package opencv:x64-windows: 141.7 ms

Total elapsed time: 8.636 min
````

**Comment by JackBoosY** [comment]
Please download [this file](https://github.com/microsoft/vcpkg/files/8760120/nasm-2.15.05-win32.zip) and put it into _VCPKG_ROOT/downloads_ then try again.

Thanks.

**Comment by RadonCoding** [comment]
worked
