### ISSUE TITLE
[openssl] build failure

### ISSUE THREAD

**Issue by shinny-jipeng** [microsoft/vcpkg#24876]
**Host Environment**
- OS: [Microsoft Windows Server 2019]

**Failure logs**
Building package openssl[core]:x64-windows...
  -- Downloading https://www.openssl.org/source/openssl-1.1.1m.tar.gz;https://www.openssl.org/source/old/1.1.1/openssl-1.1.1m.tar.gz -> openssl-1.1.1m.tar.gz...
  -- Downloading https://strawberryperl.com/download/5.32.1.1/strawberry-perl-5.32.1.1-32bit.zip -> strawberry-perl-5.32.1.1-32bit.zip...
  -- Extracting source D:/a/qpro/qpro/vcpkg/downloads/openssl-1.1.1m.tar.gz
  -- Using source at D:/a/qpro/qpro/vcpkg/buildtrees/openssl/src/openssl-1-8c9323690c.clean
  -- Downloading https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win32/nasm-2.15.05-win32.zip;https://fossies.org/windows/misc/nasm-2.15.05-win32.zip -> nasm-2.15.05-win32.zip...
  [DEBUG] Feature flag 'binarycaching' unset
  [DEBUG] Feature flag 'manifests' = off
  [DEBUG] Feature flag 'compilertracking' unset
  [DEBUG] Feature flag 'registries' unset
  [DEBUG] Feature flag 'versions' unset
  [DEBUG] Downloading https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win32/nasm-2.15.05-win32.zip
  [DEBUG] Download failed -- retrying after 1000 ms.
  [DEBUG] Download failed -- retrying after 2000 ms.
  [DEBUG] Download failed -- retrying after 4000 ms.
  [DEBUG] Downloading https://fossies.org/windows/misc/nasm-2.15.05-win32.zip
  Error: Failed to download from mirror set:
  https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win32/nasm-2.15.05-win32.zip: WinHttpSendRequest() failed: 12029
  https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win32/nasm-2.15.05-win32.zip: WinHttpSendRequest() failed: 12029
  https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win32/nasm-2.15.05-win32.zip: WinHttpSendRequest() failed: 12029
  https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win32/nasm-2.15.05-win32.zip: WinHttpSendRequest() failed: 12029
  https://fossies.org/windows/misc/nasm-2.15.05-win32.zip: failed: status code 410
  
  [DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(709): 
  [DEBUG] Time in subprocesses: 0 us
  [DEBUG] Time in parsing JSON: 15 us
  [DEBUG] Time in JSON reader: 0 us
  [DEBUG] Time in filesystem: 1039 us
  [DEBUG] Time in loading ports: 0 us
  [DEBUG] Exiting after 16.39 s (16380873 us)
  
  CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:84 (message):
        
        Failed to download file with error: 1

**Comment by Oen44** [comment]
Confirmed, same happens to me, my workflows are now failing, ugh.

**Comment by niclar** [comment]
nasm download mirrors are down...

**Comment by Cheney-W** [comment]
Dup to https://github.com/microsoft/vcpkg/issues/24871
