### ISSUE TITLE
nasm-2.15.05-win32.zip download failed

### ISSUE THREAD

**Issue by hiromaru17** [microsoft/vcpkg#24871]
**Describe the bug**
I tried the following command.

vcpkg install colmap[cuda,tests]:x64-windows

But, I encountered the error below.

**Environment**
OS: win10 64
Compiler: vs2017

**To Reproduce**

vcpkg install colmap[cuda,tests]:x64-windows
[vcpkg_install_colmap[cuda_tests]_x64-windows.log](https://github.com/microsoft/vcpkg/files/8751156/vcpkg_install_colmap.cuda_tests._x64-windows.log)

**Comment by PoweredByAndrox** [comment]
The same on VS2022. I checked and (https://fossies.org/windows/misc/nasm-2.15.05-win32.zip) has only win64 zip. Others sites don't work :(

**Comment by Cheney-W** [comment]
Modify line 184 and 185 of `vcpkg\scripts\cmake\vcpkg_find_acquire_program.cmake` as below:
```
            #"https://www.nasm.us/pub/nasm/releasebuilds/${program_version}/win32/nasm-${program_version}-win32.zip"
            #"https://fossies.org/windows/misc/nasm-${program_version}-win32.zip"
            "https://github.com/microsoft/vcpkg/files/7075269/nasm-2.15.05-win32.zip"
```

**Comment by Cheney-W** [comment]
Close this issue because the nasm server worked again.

**Comment by hiromaru17** [comment]
Solved this issue although another problem occurred. Thanks!

**Comment by Cheney-W** [comment]
What's the another problem?

**Comment by hiromaru17** [comment]
My goal is to build colmap on Windows 10 x64 environment. So I followed the following instruction available at https://colmap.github.io/install.html.

   git clone https://github.com/microsoft/vcpkg
   cd vcpkg
   .\bootstrap-vcpkg.bat
   .\vcpkg install colmap[cuda,tests]:x64-windows

The first three commands went well.
When I carried out the last one, 164 programs had to be installed as can be seen in the attached log file.
 When it came to 125 th  program, it did not complete building even after 1.5 hour passed. So I stopped the building of the 125th program. After that, building kept going and finally I got the following error message.

error: building colmap:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+colmap
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[colmap]+Build+error
Include '[colmap] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-05-05-67e17c1782801cf481be9ac0b3765dff3e4bdeb8
    vcpkg-scripts version: c40e73f7e 2022-05-24 (6 hours ago)

I would be most grateful if you could provide me with some guidance.

[Microsoft_Windows_[Version_10_0_19043_1706].txt](https://github.com/microsoft/vcpkg/files/8775045/Microsoft_Windows_.Version_10_0_19043_1706.txt)

**Comment by Cheney-W** [comment]
Please submit a new issue to us and attach the failure log: `C:\vcpkg\buildtrees\colmap\install-x64-windows-dbg-out.log`, thank you!

**Comment by hiromaru17** [comment]
All right. Thanks!

**Comment by stevecotton** [comment]
nasm appears to be down again. Also the script falls back to fossies.org, which is reporting HTTP status code 410 (GONE); the status code implies the file will never be found again on that server, so the fallback should probably be removed.

Log from https://github.com/wesnoth/wesnoth/runs/6650584378?check_suite_focus=true - although that build uses an 8-week old version of vcpkg, the same URLs are in the current version.
```
Error: Failed to download from mirror set:
https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win32/nasm-2.15.05-win32.zip: WinHttpSendRequest() failed: 12002
https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win32/nasm-2.15.05-win32.zip: WinHttpSendRequest() failed: 12002
https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win32/nasm-2.15.05-win32.zip: WinHttpSendRequest() failed: 12002
https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win32/nasm-2.15.05-win32.zip: WinHttpSendRequest() failed: 12002
https://fossies.org/windows/misc/nasm-2.15.05-win32.zip: failed: status code 410
```

**Comment by Cheney-W** [comment]
Looks like nasm server worked again.
