### ISSUE TITLE
nasm download mirrors are down

### ISSUE THREAD

**Issue by niclar** [microsoft/vcpkg#24879]
I.e building openssl3
`
-- Downloading https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win32/nasm-2.15.05-win32.zip;https://fossies.org/windows/misc/nasm-2.15.05-win32.zip -> nasm-2.15.05-win32.zip...
...
https://fossies.org/windows/misc/nasm-2.15.05-win32.zip: failed: status code 410
`

**Comment by Neumann-A** [comment]
Seems to be back up.
