### ISSUE TITLE
[ffmpeg] Build error

### ISSUE THREAD

**Issue by kita32** [microsoft/vcpkg#24873]
**Host Environment**
- OS: Windows
- Compiler: revision

**To Reproduce**
`./vcpkg install ffmpeg`

**Failure logs**

-- Downloading https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win32/nasm-2.15.05-win32.zip;https://fossies.org/windows/misc/nasm-2.15.05-win32.zip -> nasm-2.15.05-win32.zip...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' = off
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Downloading https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win32/nasm-2.15.05-win32.zip
[DEBUG] Downloading https://fossies.org/windows/misc/nasm-2.15.05-win32.zip
Error: Failed to download from mirror set:
https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win32/nasm-2.15.05-win32.zip: failed: status code 503
https://fossies.org/windows/misc/nasm-2.15.05-win32.zip: failed: status code 410

[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(751):
[DEBUG] Time in subprocesses: 0 us
[DEBUG] Time in parsing JSON: 2 us
[DEBUG] Time in JSON reader: 0 us
[DEBUG] Time in filesystem: 2442 us
[DEBUG] Time in loading ports: 0 us
[DEBUG] Exiting after 4.428 s (4394523 us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:84 (message):

      Failed to download file with error: 1
      If you use a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.

      3. Your proxy's remote server is out of service.

      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)

      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:309 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_find_acquire_program.cmake:650 (vcpkg_download_distfile)
  ports/ffmpeg/portfile.cmake:40 (vcpkg_find_acquire_program)
  scripts/ports.cmake:146 (include)

error: building ffmpeg:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+ffmpeg
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[ffmpeg]+Build+error
Include '[ffmpeg] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-05-05-67e17c1782801cf481be9ac0b3765dff3e4bdeb8
    vcpkg-scripts version: 314018fef 2022-05-20 (2 days ago)

**Additional context**

https://fossies.org/windows/misc/nasm-2.15.05-win32.zip
"File gone - probably newer version of requested archive available"

**Comment by kamomek2** [comment]
I have the same error.

In my case, I was able to avoid the error by making the following changes
However, I changed the file contents directly from win32 to win64.
I have not been able to test on my end to see how it works after the build is complete, but I hope this will help you to avoid this error problem.

**Changed files and modified lines:**
vcpkg/scripts/cmake/vcpkg_find_acquire_program.cmake
----
elseif(program STREQUAL "NASM")
        set(program_name nasm)
        set(program_version 2.15.05)
        set(paths_to_search "${DOWNLOADS}/tools/nasm/nasm-${program_version}")
        set(brew_package_name "nasm")
        set(apt_package_name "nasm")
        set(download_urls
            "https://www.nasm.us/pub/nasm/releasebuilds/${program_version}/win32/nasm-${program_version}-win32.zip"
            "https://fossies.org/windows/misc/nasm-${program_version}-**win64**.zip"
        )
        set(download_filename "nasm-${program_version}-win64.zip")
        set(download_sha512 **0d0469f3d475f3d192b9b5b7ee74662cbcb9e02efa0d51839c12cbf6f5de5cd58b32e1d12c9ee4381a63e99a4956e03df7decaf1369e598e0edff19a12629073**)

**Comment by kamomek2** [comment]
I have the same error.

In my case, I was able to avoid the error by making the following changes
However, I changed the file contents directly from win32 to win64.
I have not been able to test on my end to see how it works after the build is complete, but I hope this will help you to avoid this error problem.

Changed files and modified lines:
vcpkg/scripts/cmake/vcpkg_find_acquire_program.cmake

```
elseif(program STREQUAL "NASM")
set(program_name nasm)
set(program_version 2.15.05)
set(paths_to_search "{program_version}")
set(brew_package_name "nasm")
set(apt_package_name "nasm")
set(download_urls
"https://www.nasm.us/pub/nasm/releasebuilds/${program_version}/win32/nasm-${program_version}-win32.zip"
"https://fossies.org/windows/misc/nasm-${program_version}-win64.zip"
)
set(download_filename "nasm-${program_version}-win64.zip")
set(download_sha512 0d0469f3d475f3d192b9b5b7ee74662cbcb9e02efa0d51839c12cbf6f5de5cd58b32e1d12c9ee4381a63e99a4956e03df7decaf1369e598e0edff19a12629073)
```

**Comment by Adela0814** [comment]
@kita32 I cannot repro this issue, could you please `git pull` the latest `vcpkg` and try again?

**Comment by Cheney-W** [comment]
Dup to https://github.com/microsoft/vcpkg/issues/24871
