### ISSUE TITLE
[New Port Request] SeetaFace2

### ISSUE THREAD

**Issue by SpenserCai** [microsoft/vcpkg#24887]
Library name: SeetaFace2

Library description: 
An open source face recognition library

Source repository URL: https://github.com/seetafaceengine/SeetaFace2

Project homepage (if different from the source repository): https://github.com/seetafaceengine/SeetaFace2

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
