### ISSUE TITLE
[clamav] update to 0.105.0

### ISSUE THREAD

**Issue by SpenserCai** [microsoft/vcpkg#24894]
Library name: clamav

New version number: 0.105.0

Other information that may be useful (release notes, etc...)
https://www.clamav.net/downloads

**Comment by SpenserCai** [comment]
when will merge to master

**Comment by FrankXie05** [comment]
@SpenserCai Since the port `clamav` requires `rust`, and considering that more and more ports are starting to require rust, we are now adding rust to the script to get it.(Maybe a little longer, sorry) :)
