### ISSUE TITLE
[gettext] Bison as a required global package

### ISSUE THREAD

**Issue by PaulCombal** [microsoft/vcpkg#24895]
**Host Environment**
- OS: Ubuntu 20.04
- Compiler: g++ 9.4.0

**To Reproduce**

vcpkg.json

```json
{
    "name": "samrewritten",
    "version-string": "2022.05.25",
    "dependencies": [
      "cxxopts",
      "gtkmm"
    ]
  }
```

`./vcpkg/vcpkg install`

**Failure logs**
```
[previous cut for brevity]

Additional packages (*) will be modified to complete this operation.
Restored 0 packages from /home/paul/.cache/vcpkg/archives in 52.32 us. Use --debug to see more details.
Installing 1/31 gettext:x64-linux...
Building gettext[core]:x64-linux...
-- Using cached gettext-0.21.tar.gz.
-- Cleaning sources at /home/paul/git/perso/SamRewritten/vcpkg/buildtrees/gettext/src/0.21-66fbad380c.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/paul/git/perso/SamRewritten/vcpkg/downloads/gettext-0.21.tar.gz
-- Applying patch 0002-Fix-uwp-build.patch
-- Applying patch 0003-Fix-win-unicode-paths.patch
-- Applying patch 0004-Fix-uwp-tools-build.patch
-- Applying patch rel_path.patch
-- Applying patch android.patch
-- Applying patch gettext-tools_woe32dll_gettextsrc-exports.c.patch
-- Using source at /home/paul/git/perso/SamRewritten/vcpkg/buildtrees/gettext/src/0.21-66fbad380c.clean
CMake Error at scripts/cmake/vcpkg_find_acquire_program.cmake:641 (message):
  Could not find bison.  Please install it via your package manager:

      sudo apt-get install bison
Call Stack (most recent call first):
  ports/gettext/portfile.cmake:35 (vcpkg_find_acquire_program)
  scripts/ports.cmake:146 (include)
```

**Additional context**

Gettext is a very basic library that I'm sure be included everywhere. I want to use vcpkg to avoid having to install the development packages on the target machines. Does that really mean everyone requiring gettext needs to globally install bison as well? Bison does not come preinstalled with most of the common distributions. This is such a PITA to ask users to install global packages as well as use a package manager, it completely defeats its purpose. If this stays like this it's better to just ask to install the development packages.

Is this intentional? Is there a known workaround?

Thank you

**Comment by Thomas1664** [comment]
Reading the logs I can see that you have to install bison first:

>
```
Could not find bison.  Please install it via your package manager:

      sudo apt-get install bison
```

**Comment by Thomas1664** [comment]
The other solution would be to add bison to the catalogue

**Comment by PaulCombal** [comment]
I'm a beginner, so I will probably not grasp the whole idea. By catalogue, do you mean the list of packages in the public vcpkg repo? As far as I understand, bison here is a CLI tool required for the compilation of gettext. Since this is not a library, would it make sense to add it to the catalogue? Even then, is it possible to invoke this "local" version in the makefile of gettext?

Many questions but hopefully one conving answer :)

**Comment by Thomas1664** [comment]
> By catalogue, do you mean the list of packages in the public vcpkg repo?

Yes

> As far as I understand, bison here is a CLI tool required for the compilation of gettext. Since this is not a library, would it make sense to add it to the catalogue?

Yes, there are multiple packages that are just tools.

> Even then, is it possible to invoke this "local" version in the makefile of gettext?

Yes, this can be done by adding the location of `bison` to `PATH` (at least on Windows, I don't know what the Linux equivalent is).

**Comment by PaulCombal** [comment]
Thank you very much for your fast and clear answers. I will open a new issue to add bison to the catalogue and keep this thread updated as much as I can 👍

**Comment by JackBoosY** [comment]
So I will only leave issue #24905.
