### ISSUE TITLE
[colmap] build failure

### ISSUE THREAD

**Issue by wbw24** [microsoft/vcpkg#24910]
**Host Environment**
- OS: Windows 10

**To Reproduce**
`.\vcpkg install colmap[cuda,tests]:x64-windows`

**Failure logs**
```
Computing installation plan...
The following packages will be built and installed:
    colmap[core,cuda,tests]:x64-windows -> 2022-03-14
Detecting compiler hash for triplet x64-windows...
Restored 0 packages from C:\Users\wbw14\AppData\Local\vcpkg\archives in 346.2 us. Use --debug to see more details.
Installing 1/1 colmap:x64-windows...
Building colmap[core,cuda,tests]:x64-windows...
-- Using cached colmap-colmap-29a1e3642a3b00734a52b21e597ea4d576485fe6.tar.gz.
-- Cleaning sources at D:/develop/LLFF/vcpkg/buildtrees/colmap/src/d576485fe6-7dd36362d1.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/develop/LLFF/vcpkg/downloads/colmap-colmap-29a1e3642a3b00734a52b21e597ea4d576485fe6.tar.gz
-- Applying patch fix-dependencies.patch
-- Using source at D:/develop/LLFF/vcpkg/buildtrees/colmap/src/d576485fe6-7dd36362d1.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:158 (message):
    Command failed: D:/develop/LLFF/vcpkg/downloads/tools/cmake-3.22.2-windows/cmake-3.22.2-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j17
    Working Directory: D:/develop/LLFF/vcpkg/buildtrees/colmap/x64-windows-dbg
    See logs for more information:
      D:\develop\LLFF\vcpkg\buildtrees\colmap\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:112 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
  ports/colmap/portfile.cmake:53 (vcpkg_cmake_install)
  scripts/ports.cmake:146 (include)


error: building colmap:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+colmap
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[colmap]+Build+error
Include '[colmap] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-05-05-67e17c1782801cf481be9ac0b3765dff3e4bdeb8
    vcpkg-scripts version: 93b38546e 2022-05-24 (4 hours ago)
```
**Additional context**
I did use the latest port files with `git pull` and `vcpkg update`.
I have uninstalled my original cmake according to the [iss
ue23160].(https://github.com/microsoft/vcpkg/issues/23160)
I also turned off the firewall and antivirus software.
Where is my problem?
[config-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/8767858/config-x64-windows-dbg-err.log)
[config-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/8767861/config-x64-windows-dbg-out.log)

**Comment by JackBoosY** [comment]
Please provide failure log _D:\develop\LLFF\vcpkg\buildtrees\colmap\install-x64-windows-dbg-out.log_.

Thanks.

**Comment by wbw24** [comment]
> Please provide failure log _D:\develop\LLFF\vcpkg\buildtrees\colmap\install-x64-windows-dbg-out.log_.
> 
> Thanks.

This is.
[Uploading install-x64-windows-dbg-out.log…]()

**Comment by wbw24** [comment]
> @wbw24 It seems you didn't upload the log successfully?

So, is there something I missing or what should I do?

**Comment by JackBoosY** [comment]
Just drag your log file _D:\develop\LLFF\vcpkg\buildtrees\colmap\install-x64-windows-dbg-out.log_ into the comment box.
The link in https://github.com/microsoft/vcpkg/issues/24910#issuecomment-1136902348 is link to this issue, not download url.

**Comment by wbw24** [comment]
> Just drag your log file _D:\develop\LLFF\vcpkg\buildtrees\colmap\install-x64-windows-dbg-out.log_ into the comment box. The link in [#24910 (comment)](https://github.com/microsoft/vcpkg/issues/24910#issuecomment-1136902348) is link to this issue, not download url.
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/8769088/install-x64-windows-dbg-out.log)

**Comment by JackBoosY** [comment]
```
D:\develop\LLFF\vcpkg\installed\x64-windows\include\FreeImage.h(921): error: identifier "RGBQUAD" is undefined
```
Did you installed glog using vcpkg?

**Comment by wbw24** [comment]
> 

I did not install glog using vcpkg.
I follow the steps on the official website to install colmap

```
git clone https://github.com/microsoft/vcpkg
cd vcpkg
.\bootstrap-vcpkg.bat
.\vcpkg install colmap[cuda,tests]:x64-windows
```

**Comment by JackBoosY** [comment]
I think this issue is duplicated of https://github.com/microsoft/vcpkg/issues/24420. Please track that issue instead.

Thanks.

**Comment by wbw24** [comment]
> [JackBoosY](/JackBoosY)

https://github.com/colmap/colmap/issues/1511#issuecomment-1136962617

I can not understand what this issue meanning.
Whould u plz help me.
Thanks.
