### ISSUE TITLE
[colmap] Build error

### ISSUE THREAD

**Issue by hiromaru17** [microsoft/vcpkg#24927]
**Describe the bug**
-My goal is to build colmap on Windows 10 x64 environment. So I did the following command available at https://colmap.github.io/install.html.

git clone https://github.com/microsoft/vcpkg
cd vcpkg
.\bootstrap-vcpkg.bat
.\vcpkg install colmap[cuda,tests]:x64-windows
vcpkg install colmap[cuda,tests]:x64-windows

The first three commands went well.
But, I encountered the error below when I did the last one.

error: building colmap:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+colmap
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[colmap]+Build+error
Include '[colmap] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-05-05-67e17c1782801cf481be9ac0b3765dff3e4bdeb8
    vcpkg-scripts version: 20907dc8b 2022-05-25 (8 hours ago)

**Environment**
OS: win10 64
Compiler: vs2017

**Failure logs**
C:\vcpkg>vcpkg install colmap[cuda,tests]:x64-windows
Computing installation plan...
A suitable version of cmake was not found (required v3.22.2). Downloading portable cmake v3.22.2...
Downloading cmake...
  https://github.com/Kitware/CMake/releases/download/v3.22.2/cmake-3.22.2-windows-i386.zip -> C:\vcpkg\downloads\cmake-3.22.2-windows-i386.zip
Extracting cmake...
The following packages will be built and installed:
  * assimp[core]:x64-windows -> 5.0.1#5
  
     ( omit the middle)

  * zstd[core]:x64-windows -> 1.5.2#1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
A suitable version of powershell-core was not found (required v7.2.3). Downloading portable powershell-core v7.2.3...
Downloading powershell-core...
  https://github.com/PowerShell/PowerShell/releases/download/v7.2.3/PowerShell-7.2.3-win-x86.zip -> C:\vcpkg\downloads\PowerShell-7.2.3-win-x86.zip
Extracting powershell-core...
A suitable version of 7zip was not found (required v21.7.0). Downloading portable 7zip v21.7.0...
Downloading 7zip...
  https://www.7-zip.org/a/7z2107-extra.7z -> C:\vcpkg\downloads\7z2107-extra.7z
Extracting 7zip...
Restored 163 packages from C:\Users\kanri\AppData\Local\vcpkg\archives in 2.344 min. Use --debug to see more details.
Installing 1/164 bzip2:x64-windows...
Elapsed time to handle bzip2:x64-windows: 371.4 ms

 (omit the middle)

Installing 164/164 colmap:x64-windows...
Building colmap[core,cuda,tests]:x64-windows...
-- Downloading https://github.com/colmap/colmap/archive/29a1e3642a3b00734a52b21e597ea4d576485fe6.tar.gz -> colmap-colmap-29a1e3642a3b00734a52b21e597ea4d576485fe6.tar.gz...
-- Extracting source C:/vcpkg/downloads/colmap-colmap-29a1e3642a3b00734a52b21e597ea4d576485fe6.tar.gz
-- Applying patch fix-dependencies.patch
-- Using source at C:/vcpkg/buildtrees/colmap/src/d576485fe6-7dd36362d1.clean
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:158 (message):
    Command failed: C:/vcpkg/downloads/tools/cmake-3.22.2-windows/cmake-3.22.2-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j9
    Working Directory: C:/vcpkg/buildtrees/colmap/x64-windows-dbg
    See logs for more information:
      C:\vcpkg\buildtrees\colmap\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:112 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
  ports/colmap/portfile.cmake:53 (vcpkg_cmake_install)
  scripts/ports.cmake:146 (include)

I would be most grateful if you could provide me with some guidance.

[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/8776383/install-x64-windows-dbg-out.log)

**Comment by Adela0814** [comment]
@hiromaru17  Please install English language pack in VS and try again.

**Comment by hiromaru17** [comment]
I install the English version of VS 2017.
But I got the same error message.
Outputs of  Windows Power shell is the same as I wrote above. 

I attach the log file for this trial.

[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/8783353/install-x64-windows-dbg-out.log)

**Comment by hiromaru17** [comment]
Following https://github.com/colmap/colmap/issues/1511, I commented out 3 lines of glog/logging.h .  Then, I could complete the following command.

 .\vcpkg install colmap[cuda,tests]:x64-windows

Thanks!

**Comment by Adela0814** [comment]
Dup to #24420
