### ISSUE TITLE
[gamenetworkingsockets] build failure

### ISSUE THREAD

**Issue by s2s-k** [microsoft/vcpkg#24924]
**Host Environment**
- OS: Windows
- Compiler: Visual C++ 2022

**To Reproduce**
`./vcpkg install gamenetworkingsockets:x64-windows-static`

**Failure logs**
Error: gamenetworkingsockets[core] is only supported on '!(static & windows) & !uwp & !(arm64 & windows)'

**Additional context**
This package cannot be built statically, although it should. I created a [issue](https://github.com/ValveSoftware/GameNetworkingSockets/issues/225) in the GameNetworkingSockets repository, but it seems from the dynamics of the responses that it will not be resolved soon. I don't really understand why this [PR](https://github.com/microsoft/vcpkg/pull/21759/files#diff-df79355ed795c21b49d5d8596e433a23b90e4b326d746a7beaaccf19eb9ebe58R8) was not included in version 1.4.0... Is there any way to fix this?

**Comment by Pospelove** [comment]
This patch should help https://github.com/eddiejames/vcpkg/commit/420290091e82288e461473e3447e6e4901f0c8df

**Comment by Pospelove** [comment]
@Cheney-W Could you please apply the patch (only the linking part)
It would be awesome to have this landed

**Comment by Cheney-W** [comment]
OK, I will have a try.

**Comment by kkEngine** [comment]
Please make this feature available, I need to fallback to submodules since I need static build

**Comment by Cheney-W** [comment]
Keep-Alive
