### ISSUE TITLE
How do I make my own triplet?

### ISSUE THREAD

**Issue by grepwood** [microsoft/vcpkg#24932]
I want to create a triplet with support for Windows XP preserved. I happen to build an arcade computer running Windows XP x64 (to get all that juicy memory and 64bit arithmetic) and I will be compiling a lot of things on my own to serve my own needs. In the future the system will change to ReactOS once it becomes usable for my purposes. These bizarre decisions depend on the fact that these are the only systems with DirectSound3D support and I happen to own a very well preserved Audigy 2 ZS card.

**Comment by Neumann-A** [comment]
examples see https://github.com/Neumann-A/my-vcpkg-triplets. use `--overlay-triplets` to point it to the directory containing the new triplets

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. This issue has been fixed, so I am closing this issue for now.
