### ISSUE TITLE
[winpcap] Build error

### ISSUE THREAD

**Issue by ronen-gr** [microsoft/vcpkg#24937]
**Host Environment**
- OS: Windows 10
- Compiler: MSVC (Visual Studio 2019)

**To Reproduce**
`./vcpkg install winpcap`

**Failure logs**
-Cut and paste the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.
```
Detecting compiler hash for triplet x64-windows...
4>The following packages will be built and installed:
4>    winpcap[core]:x64-windows -> 4.1.3#8 -- C:\vcpkg-git\vcpkg\buildtrees\versioning_\versions\winpcap\85d70a721afa26cf8ff26aec62fd04a16f8e6f7b
4>Restored 0 packages from C:\Users\ronen\AppData\Local\vcpkg\archives in 278.3 us. Use --debug to see more details.
4>Installing 1/1 winpcap:x64-windows...
4>Building winpcap[core]:x64-windows...
4>-- Installing port from location: C:\vcpkg-git\vcpkg\buildtrees\versioning_\versions\winpcap\85d70a721afa26cf8ff26aec62fd04a16f8e6f7b
4>-- Using cached WpcapSrc_4_1_3.zip.
4>-- Extracting source C:/vcpkg-git/vcpkg/downloads/WpcapSrc_4_1_3.zip
4>-- Applying patch C:/vcpkg-git/vcpkg/buildtrees/winpcap/src/packetNtx.patch
4>-- Applying patch C:/vcpkg-git/vcpkg/buildtrees/winpcap/src/wpcap.patch
4>-- Applying patch C:/vcpkg-git/vcpkg/buildtrees/versioning_/versions/winpcap/85d70a721afa26cf8ff26aec62fd04a16f8e6f7b/create_lib.patch
4>-- Applying patch C:/vcpkg-git/vcpkg/buildtrees/versioning_/versions/winpcap/85d70a721afa26cf8ff26aec62fd04a16f8e6f7b/fix-create-lib-batch.patch
4>-- Using source at C:/vcpkg-git/vcpkg/buildtrees/winpcap/src/4_1_3-2020b05bdd.clean
4>CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:128 (message):
4>    Command failed: devenv.exe Packet.sln /Upgrade
4>    Working Directory: C:/vcpkg-git/vcpkg/buildtrees/winpcap/src/4_1_3-2020b05bdd.clean/packetNtx/Dll/Project
4>EXEC : error code: The system cannot find the file specified
4>    See logs for more information:
4>
4>Call Stack (most recent call first):
4>  buildtrees/versioning_/versions/winpcap/85d70a721afa26cf8ff26aec62fd04a16f8e6f7b/portfile.cmake:50 (vcpkg_execute_required_process)
4>  scripts/ports.cmake:146 (include)
4>
4>
4>EXEC : error : building winpcap:x64-windows failed with: BUILD_FAILED
```

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.
I tried to add the path for the devenv.exe file at the system environment variables.
I confirmed that the .sln file is present at the Working Directory, and also tried to run the command 'devenv.exe Packet.sln /Upgrade' myself from CMD successfully.
Also tried to update vcpkg.
All things runs as admin.
Still, for some reason the .cmake scripts attempting to run the command fails...

**Comment by Adela0814** [comment]
Can you please repair your Visual Studio using Visual Studio Installer then retry?
Since pcap's `sln` file needs and can only be upgraded with `devenv`, a complete Visual Studio is required to build it.

**Comment by ronen-gr** [comment]
> Can you please repair your Visual Studio using Visual Studio Installer then retry? Since pcap's `sln` file needs and can only be upgraded with `devenv`, a complete Visual Studio is required to build it.

I tried that but it did not help. Also, I have a complete VS installation already.
I got this sorted out, I can only speculate the reason for the fix:
Before I installed VS19, VS Code was installed first, and along with it something called 'Built Tools for Visual Studio 2022'.
At this point VS19 and the additional build tools are installed.
Only after removing the 'Build Tools' the pcap package installed successfully.
So my guess is that there was some conflict of sort with the build tools.
Thank you.

**Comment by stvchester** [comment]
Are there any available work arounds for this?  We are utilizing the Build Tools for our build system to allow for easy replication of build agents depending on load, however this limitation is currently preventing us from being able to use this package.
