### ISSUE TITLE
[wtl] Error when including atlribbon.h

### ISSUE THREAD

**Issue by vividos** [microsoft/vcpkg#24933]
****

I'm trying to use the wtl package, but as soon as I `#include <wtl/atlribbon.h>`, the build fails:

    ...\vcpkg_installed\x86-windows\x86-windows\include\wtl\atlribbon.h(30,10): fatal error C1083: Cannot open include file: 'atlmisc.h': No such file or directory

The error comes from the atlribbon.h file in the WTL package, and from the fact that vcpkg sets the include path to the folder containing the "wtl" folder, not the folder itself. Therefore, I also had to change my includes from `#include <atlribbon.h>` to `#include <wtl/atlribbon.h>` in the first place. WTL just assumes that its include folder is directly in the path.

Easy steps to reproduce:
- Install the WTL package into VS 2019 (I didn't try VS 2022)
- create a new WTL project, any type
- add a vcpkg.json that references the "wtl" package
- switch on "Use Vcpkg Manifest"
- compile

**Proposed solution**

The solution would be to change the include path for the WTL package to directly include the "wtl" folder in the package, not the parent folder of that. After all, the WTL project wizard creates projects with this in mind and surely there are WTL projects out there who use that convention for decade(s). I'm not sure if this breaks some vcpkg rules. At the moment, the package is useless.

**Describe alternatives you've considered**

I can manually add an "Additional Include Directory" in the Visual Studio C/C++ properties, as a workaround:

    $(VcpkgManifestRoot)\vcpkg_installed\$(VcpkgTriplet)\$(VcpkgTriplet)\include\wtl

Note that this is also needed to be added to the Resource Compiler settings, as the .rc files may also include <atlres.h>, which is also a part of WTL.

**Comment by vividos** [comment]
Here you can see my try to replace the WTL NuGet package with the vcpkg reference:
https://github.com/vividos/UnderworldAdventures/commit/7efa220044e6ca87325c3b9d2da40b6dae574656

**Comment by JackBoosY** [comment]
Confirmed with the following code:
```cpp
#include <atlbase.h>
#include <wtl/atlapp.h>
#include <wtl/atlribbon.h>
```

**Comment by JackBoosY** [comment]
cc @chrullrich.

**Comment by chrullrich** [comment]
Hello @vividos, here is the patch. I tried getting it in via PR, but it seems people here care more about me dotting their "i"s and crossing their "t"s than about fixing bugs.

```
--- a/Include/atlribbon.h	2022-06-06 03:12:54.312690900 +0200
+++ b/Include/atlribbon.h	2022-06-06 03:13:24.337068900 +0200
@@ -27,10 +27,10 @@
 	#error atlribbon.h requires atlapp.h to be included first
 #endif

-#include <atlmisc.h>    // for RecentDocumentList classes
-#include <atlframe.h>   // for Frame and UpdateUI classes
-#include <atlctrls.h>   // required for atlctrlw.h
-#include <atlctrlw.h>   // for CCommandBarCtrl
+#include "atlmisc.h"    // for RecentDocumentList classes
+#include "atlframe.h"   // for Frame and UpdateUI classes
+#include "atlctrls.h"   // required for atlctrlw.h
+#include "atlctrlw.h"   // for CCommandBarCtrl

 #ifndef __ATLSTR_H__
   #pragma warning(push)
``´

**Comment by chrullrich** [comment]
The difference between angle brackets and double quotes in #include is that the angle brackets use the system header include path, while double quotes use an include path that also contains the current file's directory. In short, angle brackets are simply wrong in this situation.

I'm going to submit the same patch upstream ASAP, but until then this is the correct fix.

**Comment by vividos** [comment]
Again thanks for your efforts and your explanation!

**Comment by dg0yt** [comment]
> people here care more about me dotting their "i"s and crossing their "t"s than about fixing bugs.

@chrullrich I don't think that's a fair statement. And you didn't even ask for help within the few hours your PR was open.

**Comment by chrullrich** [comment]
Right. I was going to angrily reply that that was because I did not need help, but on further consideration, and after looking at #25108, I now see that I misread the documentation on the version formats. I was under the impression that "version" required a four-part version number (by mistaking the word "for" for "four"). I would not have added the final ".0" and the whole back-and-forth with removing the port version etc. would not have happened.

So, I'm sorry about that. It was my mistake.
