### ISSUE TITLE
[gmp] Build error

### ISSUE THREAD

**Issue by npagane** [microsoft/vcpkg#24947]
Versions
---------
OS: Windows 10
vcpkg-tool version: 2022-05-05-67e17c1782801cf481be9ac0b3765dff3e4bdeb8
vcpkg-scripts version: 9ab334404 2022-05-26 

Cmd that led to build error
------------------------------
vcpkg.exe install cgal:x64-windows

Error message
----------------
-- Configuring x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:128 (message):
    Command failed: C:/dev/vcpkg/downloads/tools/msys2/7e05e7aa09f1709f/usr/bin/bash.exe --noprofile --norc --debug -c "V=1 CPP='compile cl.exe -E' CC='compile cl.exe' CC_FOR_BUILD='compile cl.exe' CXX='compile cl.exe' RC='windres-rc rc.exe' WINDRES='windres-rc rc.exe' AR='ar-lib lib.exe' LD='link.exe -verbose' RANLIB=':' STRIP=':' NM='dumpbin.exe -symbols -headers' DLLTOOL='link.exe -verbose -dll' CCAS='C:/dev/vcpkg/installed/x64-windows/tools/yasm/yasm.exe' AS=':' ./../src/gmp-6.2.1-e782e0632d.clean/configure --build=x86_64-pc-mingw32 \"ac_cv_func_memset=yes\" \"gmp_cv_asm_w32=.word\" \"--enable-cxx\" \"ac_cv_prog_ac_ct_STRIP=:\" \"gl_cv_double_slash_root=yes\" \"ac_cv_func_memmove=yes\" \"--disable-silent-rules\" \"--verbose\" \"--enable-shared\" \"--disable-static\" \"--prefix=/C/dev/vcpkg/installed/x64-windows/debug\" \"--bindir=\\${prefix}/../tools/gmp/debug/bin\" \"--sbindir=\\${prefix}/../tools/gmp/debug/sbin\" \"--libdir=\\${prefix}/lib\" \"--includedir=\\${prefix}/../include\" \"--datarootdir=\\${prefix}/share/gmp\""
    Working Directory: C:/dev/vcpkg/buildtrees/gmp/x64-windows-dbg
    Error code: 1
    See logs for more information:
      C:\dev\vcpkg\buildtrees\gmp\config-x64-windows-dbg-out.log
      C:\dev\vcpkg\buildtrees\gmp\config-x64-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:799 (vcpkg_execute_required_process)
  ports/gmp/portfile.cmake:46 (vcpkg_configure_make)
  scripts/ports.cmake:146 (include)

error: building gmp:x64-windows failed with: BUILD_FAILED

**Comment by Cheney-W** [comment]
Could you please provide following logs to us? Thank you!
```
C:\dev\vcpkg\buildtrees\gmp\config-x64-windows-dbg-out.log
C:\dev\vcpkg\buildtrees\gmp\config-x64-windows-dbg-err.log
```

**Comment by npagane** [comment]
C:\dev\vcpkg>type buildtrees\gmp\config-x64-windows-dbg-out.log
-----------------------------------------------------------------------------
checking build system type... x86_64-pc-mingw32
checking host system type... x86_64-pc-mingw32
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking ABI=64
checking compiler compile cl.exe -nologo -W3 -utf-8 -MP -MDd -Z7 -Ob0 -Od -Xcompiler -RTC1 -DWIN32 -D_WINDOWS -D_DEBUG... no
checking ABI=x32
checking compiler compile cl.exe -nologo -W3 -utf-8 -MP -MDd -Z7 -Ob0 -Od -Xcompiler -RTC1 -DWIN32 -D_WINDOWS -D_DEBUG... no
checking ABI=32
checking compiler compile cl.exe -nologo -W3 -utf-8 -MP -MDd -Z7 -Ob0 -Od -Xcompiler -RTC1 -DWIN32 -D_WINDOWS -D_DEBUG... no

C:\dev\vcpkg>type buildtrees\gmp\config-x64-windows-dbg-err.log
-----------------------------------------------------------------------------------
configure: error: could not find a working compiler, see config.log for details

**Comment by npagane** [comment]
nevermind. it seems that HP Wolf Security kept flagging and removing a file during gmp compilation; hence why it couldn't build. after excluding the path to vcpkg from HP Wolf Security, the build is successful. thanks though!

**Comment by Cheney-W** [comment]
Thanks for your reply! I'm glad to know that this issue has been solved.
