### ISSUE TITLE
[feature] Provide the counterpart of "cmake-conan".

### ISSUE THREAD

**Issue by hwhsu1231** [microsoft/vcpkg#24956]
### Feature Request

Conan provides a CMake Wrapper, [cmake-conan](https://github.com/conan-io/cmake-conan).

The key point is that we can use commands provided by "cmake-conan" in replacement of `conan` commands.

For example, it wraps the [`conan install`](https://docs.conan.io/en/latest/reference/commands/consumer/install.html) command into [`conan_cmake_install()`](https://github.com/conan-io/cmake-conan#conan_cmake_install). Which means, we can install the libraries without typing the `conan install` command ourselves on the terminal. Instead, we just need to execute `cmake` command to configure the `CMakeLists.txt`. When `conan_cmake_install()` command is executed, Conan will start to install the libraries we need.

For me, the manifest `vcpkg.json` is similar to the recipe `conanfile.txt/conanfile.py`.

Is it possible to implement the counterpart of it?

**Comment by Neumann-A** [comment]
that would be intrusive. The whole point of vcpkg is to be not intrusive and not leak into the build description.

**Comment by hwhsu1231** [comment]
What does **"intrusive"** mean?

**Comment by Neumann-A** [comment]
> What does "intrusive" mean?

You 
a) make vcpkg a hard dependency
b) add a function call which only works if vcpkg defined the function. (which basically is a) ). So configure without vcpkg will fail.

One point of vcpkg is to decoupled the dependency provider (vcpkg/cmake) from the dependency lookup (cmake).

**Comment by JackBoosY** [comment]
For me, I know we don't have this plan at the moment.

**Comment by MichaelGoulding** [comment]
@hwhsu1231 , I don't understand, if you are using manifest mode, the packages should be installed during cmake configure.  Are you setting any flags with VCPKG_FEATURE_FLAGS?

**Comment by hwhsu1231** [comment]
@MichaelGoulding Can you show me a example about this, please?

**Comment by Osyotr** [comment]
No need to add any feature flags. Just pass `CMAKE_TOOLCHAIN_FILE` to cmake and vcpkg will automatically install dependencies from manifest file (`vcpkg.json`).

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
