### ISSUE TITLE
[vcpkg integrate] Visual Studio doesn't detect Vcpkg With VS2015 update 3

### ISSUE THREAD

**Issue by zh1an** [microsoft/vcpkg#24952]
Please create a discussion in https://github.com/microsoft/vcpkg/discussions/new instead.
VCPKG integrate install log:
```
PS E:\vcpkg> .\vcpkg.exe integrate install --debug
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] BuiltinRegistry initialized with: ""
[DEBUG] Using vcpkg-root: E:\vcpkg
[DEBUG] Using installed-root: E:\vcpkg\installed
[DEBUG] BuiltinRegistry initialized with: ""
[DEBUG] Using buildtrees-root: E:\vcpkg\buildtrees
[DEBUG] Using downloads-root: E:\vcpkg\downloads
[DEBUG] Using packages-root: E:\vcpkg\packages
[DEBUG] Using scripts-root: E:\vcpkg\scripts
[DEBUG] Using ports-root: E:\vcpkg\ports
[DEBUG] Using versions-root: E:\vcpkg\versions
Applied user-wide integration for this vcpkg root.

All MSBuild C++ projects can now #include any installed libraries.
Linking will be handled automatically.
Installing new libraries will make them instantly available.

CMake projects should use: "-DCMAKE_TOOLCHAIN_FILE=E:/vcpkg/scripts/buildsystems/vcpkg.cmake"
[DEBUG] D:\a\_work\1\s\src\vcpkg\commands.integrate.cpp(307)
[DEBUG] Exiting after 22.79 ms us (4042 us)
PS E:\vcpkg>
```

That log executed successed, but there is no vcpkg setting with visual studio 2015.

![image](https://user-images.githubusercontent.com/30436038/170612049-0dacd88a-9175-4c88-86cf-d4886c513f10.png)

**Comment by zh1an** [comment]
> Please create a discussion in https://github.com/microsoft/vcpkg/discussions/new instead. VCPKG integrate install log:
> 
> ```
> PS E:\vcpkg> .\vcpkg.exe integrate install --debug
> [DEBUG] Feature flag 'binarycaching' unset
> [DEBUG] Feature flag 'manifests' unset
> [DEBUG] Feature flag 'compilertracking' unset
> [DEBUG] Feature flag 'registries' unset
> [DEBUG] Feature flag 'versions' unset
> [DEBUG] BuiltinRegistry initialized with: ""
> [DEBUG] Using vcpkg-root: E:\vcpkg
> [DEBUG] Using installed-root: E:\vcpkg\installed
> [DEBUG] BuiltinRegistry initialized with: ""
> [DEBUG] Using buildtrees-root: E:\vcpkg\buildtrees
> [DEBUG] Using downloads-root: E:\vcpkg\downloads
> [DEBUG] Using packages-root: E:\vcpkg\packages
> [DEBUG] Using scripts-root: E:\vcpkg\scripts
> [DEBUG] Using ports-root: E:\vcpkg\ports
> [DEBUG] Using versions-root: E:\vcpkg\versions
> Applied user-wide integration for this vcpkg root.
> 
> All MSBuild C++ projects can now #include any installed libraries.
> Linking will be handled automatically.
> Installing new libraries will make them instantly available.
> 
> CMake projects should use: "-DCMAKE_TOOLCHAIN_FILE=E:/vcpkg/scripts/buildsystems/vcpkg.cmake"
> [DEBUG] D:\a\_work\1\s\src\vcpkg\commands.integrate.cpp(307)
> [DEBUG] Exiting after 22.79 ms us (4042 us)
> PS E:\vcpkg>
> ```
> 
> That log executed successed, but there is no vcpkg setting with visual studio 2015.
> 
> ![image](https://user-images.githubusercontent.com/30436038/170612049-0dacd88a-9175-4c88-86cf-d4886c513f10.png)

installed package command:

```
./vcpkg install g3log --no-binarycaching
```

This command is related with this error?

**Comment by zh1an** [comment]
![image](https://user-images.githubusercontent.com/30436038/170612623-74e05733-6986-4cac-b870-5ecf56f5b928.png)

**Comment by zh1an** [comment]
![image](https://user-images.githubusercontent.com/30436038/170612976-fca7ef87-79ea-44f8-a9f6-61fb260ab6f2.png)

**Comment by JackBoosY** [comment]
cc @ras0219-msft @BillyONeal

**Comment by BillyONeal** [comment]
I don't believe the hooks needed to show UI in VS exist for us in 2015.

**Comment by JackBoosY** [comment]
I confirmed that msbuild integration is not suitable for VS2015.

**Comment by zh1an** [comment]
> I confirmed that msbuild integration is not suitable for VS2015.

@JackBoosY ths, will that be fixed? If no, how to use it in VS2015?

**Comment by JackBoosY** [comment]
cc @ras0219-msft

**Comment by zh1an** [comment]
> 

OK。THS。
