### ISSUE TITLE
[vcpkg-tool] build, compile, link failed (latest git pull from 05/26/2022 @ 00:00 UTC) (not the official release version)

### ISSUE THREAD

**Issue by StarGate-One** [microsoft/vcpkg#24950]
**Describe the bug**
[vcpkg-tool] build, compile, link failed (latest git pull from 05/26/2022 @ 00:00 UTC)  **(not the current official release version but latest git commit)**

**Environment**
- OS: [Windows 11 latest release build Windows Version [10.0.22000.708] ]
- Compiler: Visual Studio Community 2022 Version: [17.2.2]  VS Tools Version: [14.31.31103] 
                  Microsoft (R) C/C++ Optimizing Compiler Version [19.31.31107] for x64 

**To Reproduce**
1. `cmake -B %_vcpkg_tool_build% -S %_vcpkg_tool_source% -G "Visual Studio 17 2022" -A x64 -T v143 -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -DVCPKG_DEVELOPMENT_WARNINGS=ON -DVCPKG_WARNINGS_AS_ERRORS=ON -DVCPKG_BUILD_FUZZING=OFF -DVCPKG_BUILD_TLS12_DOWNLOADER=OFF -DVCPKG_EMBED_GIT_SHA=ON -DVCPKG_OFFICIAL_BUILD=OFF -DFETCHCONTENT_FULLY_DISCONNECTED=OFF -DVCPKG_ADD_SOURCELINK=OFF -DVCPKG_BASE_VERSION=%_vcpkg-tool_latest_tag-refname-date% -DVCPKG_VERSION=%_vcpkg-tool_latest_tag-refname-date%`
2. `cmake --build %_vcpkg_tool_build% --target vcpkg --clean-first --verbose --config release --parallel 8`

Repro code when
After commit [Resolve several ExpectedT<T> problems (https://github.com/microsoft/vcpkg-tool/pull/511 (#511))](https://github.com/microsoft/vcpkg-tool/commit/dcc70412f5ca28001de9c4b76231f7fae15aba7b) vcpkg-tool build, compile and link fails (see attached failure logs).

**Expected behavior**
vcpkg-tool should build, compile and link.
I am not sure if I should leave `VCPKG_WARNINGS_AS_ERRORS=ON` or should I turn them off or is there a different way I should be compiling.

**Failure logs**
-(please attached failure logs)
[vcpkg-tool-compile.log](https://github.com/microsoft/vcpkg/files/8783021/vcpkg-tool-compile.log)
Last part of attached log is as follows:
`         vcpkgcmdarguments.cpp`
`         vcpkglib.cpp`
`         Running Code Analysis for C/C++...`
`         Generating Code...`
`     3>D:\vcpkg-tool\include\vcpkg\base\strings.h(22): error C2220: the following warning is treated as an error [D:\vcpkg-tool\build\vcpkglib.vcxproj]`
`     3>D:\vcpkg-tool\include\vcpkg\base\strings.h(22): warning C4172: returning address of local variable or temporary [D:\vcpkg-tool\build\vcpkglib.vcxproj]`
`         Compiling...`
`         vcpkgpaths.cpp`
`         versiondeserializers.cpp`
`         versions.cpp`
`         visualstudio.cpp`
`         Running Code Analysis for C/C++...`
`         Generating Code...`
`     3>Done Building Project "D:\vcpkg-tool\build\vcpkglib.vcxproj" (default targets) -- FAILED.`
`     1>Done Building Project "D:\vcpkg-tool\build\vcpkg.vcxproj" (default targets) -- FAILED.`
` `
`Build FAILED.`
` `
`       "D:\vcpkg-tool\build\vcpkg.vcxproj" (default target) (1) ->`
`       "D:\vcpkg-tool\build\vcpkglib.vcxproj" (default target) (3) ->`
`       (ClCompile target) -> `
`         D:\vcpkg-tool\include\vcpkg\base\strings.h(22): warning C4172: returning address of local variable or temporary [D:\vcpkg-tool\build\vcpkglib.vcxproj]`
`  `
`       "D:\vcpkg-tool\build\vcpkg.vcxproj" (default target) (1) ->`
`       "D:\vcpkg-tool\build\vcpkglib.vcxproj" (default target) (3) ->`
`       (ClCompile target) -> `
`         D:\vcpkg-tool\include\vcpkg\base\strings.h(22): error C2220: the following warning is treated as an error [D:\vcpkg-tool\build\vcpkglib.vcxproj]`
` `
`    1 Warning(s)`
`    1 Error(s)`
` `
`Time Elapsed 00:01:27.58`
` `
**Additional context**
**After backout of above mentioned commit, vcpkg-tool compiles, links successfully.**

**Comment by StarGate-One** [comment]
Note: vcpkg-tool will build, compile and link by setting `VCPKG_WARNINGS_AS_ERRORS=OFF` but again, I am not sure if this  should be the correct direction to take, so I can work around until guidance provided by vcpkg team. Thank you and everyone have a wonderful *Memorial Day Weekend**
/cc @BillyONeal @ras0219-msft

**Comment by BillyONeal** [comment]
T was std::regex's csubmatch :(

**Comment by StarGate-One** [comment]
Thanks a lot @BillyONeal - I appreciate the fast response and hard work done on this project.
It just keeps getting better with age.
You have a super wonderful holiday weekend.
