### ISSUE TITLE
imgui[docking-experimental] no matches found - WSL Ubuntu - zsh

### ISSUE THREAD

**Issue by Neithari** [microsoft/vcpkg#24965]
**Describe the bug**
When I try to install the experimental docking branch of imgui in my Ubuntu, it can not find the package using zsh.

**Environment**
- OS: Ubuntu 22.04 on WSL2
- Compiler: gcc 11.2

**To Reproduce**
1. use zsh instead of bash
2. `./vcpkg install imgui[docking-experimental]`
Error: `zsh: no matches found: imgui[docking-experimental]`

**Expected behavior**
Installing of the experimental docking feature like under windows and bash

**Failure logs**
- currently no logs

**Additional context**
It is listed under search imgui. It does work under my windows install and with bash. Tested with 2 PCs both 22.04  with zsh not working. Tested on 1 PC with 20.04 Ubuntu on WSL 2 with bash, it is working like intended there.
All on the newest commit "8cfe2589b7060a9c1e131f31822aca3fa35ff3cf"
It seems to be a problem only with zsh.
I will set up a VM to check if it's WSL related or not.

Edit:
The problem is zsh, not WSL or Ubuntu 22.04.
It's working as expected on the same WSL 2 Ubuntu using bash instead of zsh.
Edit2:
I've setup a fresh Ubuntu 22.04 with the server iso and the minimum needed packages to make vcpkg work.
`./vcpkg install imgui[docking-experimental]` does work normal under bash.

Under a base zsh install via apt:
```
./vcpkg install imgui[docking-experimental]
zsh: no matches found: imgui[docking-experimental]
```

So it is indeed a bug with zsh.

**Comment by Neithari** [comment]
Related issue: #24839

**Comment by autoantwort** [comment]
> Is this fixable or a syntax quirk of zsh?

a syntax quirk of zsh
