### ISSUE TITLE
my vs code is not detecting the compiler How do I fix that or how can i download anew compiler

### ISSUE THREAD

**Issue by javeriaakram** [microsoft/vcpkg#24962]
Please create a discussion in https://github.com/microsoft/vcpkg/discussions/new instead.

**Comment by Neumann-A** [comment]
> my vs code is not detecting the compiler

Wrong github. If vcpkg is not detecting your compiler you probably use a windows triplet and don't have visual studio installed.
If you have it installed and are trying to use ninja, run vcvars and run code from there. alternatively don't use the ninja generator.

**Comment by Adela0814** [comment]
@javeriaakram Is your problem solved?

**Comment by Adela0814** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
