### ISSUE TITLE
[New Port Request] liba52

### ISSUE THREAD

**Issue by oddlf** [microsoft/vcpkg#24973]
Library name: liba52

Library description: a free ATSC A/52 stream decoder (Dolby Digital/AC3)

Source repository URL: https://liba52.sourceforge.io/files/a52dec-0.7.4.tar.gz

Project homepage (if different from the source repository): https://liba52.sourceforge.io/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

sister project of libmpeg2: https://github.com/microsoft/vcpkg/tree/master/ports/libmpeg2
example implementation: https://github.com/oddlf/libzplay/tree/main/vcpkg-ports/liba52

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by djegg** [comment]
I would like liba52 to be added right now :-)
