### ISSUE TITLE
Unable to build sdl2 

### ISSUE THREAD

**Issue by Pumkko** [Microsoft/vcpkg#2497]
- I am using Windows 10 professional version 10.0.16299.125
- I just cloned the vcpkg repo
- I just installed vcpkg using the steps described in the readme.md
- I run \vcpkg.exe install sdl2
- It fails due to incorrect hash
Details
Building package sdl2:x86-windows...
-- CURRENT_INSTALLED_DIR=C:/VcPkg/vcpkg/installed/x86-windows
-- DOWNLOADS=C:/VcPkg/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/VcPkg/vcpkg/packages/sdl2_x86-windows
-- CURRENT_BUILDTREES_DIR=C:/VcPkg/vcpkg/buildtrees/sdl2
-- CURRENT_PORT_DIR=C:/VcPkg/vcpkg/ports/sdl2/.
-- Using cached C:/VcPkg/vcpkg/downloads/SDL2-2.0.7.tar.gz
-- Testing integrity of cached file...
CMake Error at C:/VcPkg/vcpkg/scripts/cmake/vcpkg_download_distfile.cmake:66 (message):

  File does not have expected hash:

          File path: [ C:/VcPkg/vcpkg/downloads/SDL2-2.0.7.tar.gz ]
      Expected hash: [ eed5477843086a0e66552eb197a5c4929134522bc366d873732361ea0df5fb841ef7e2b1913e21d1bae69e6fd3152ee630492e615c58cbe903e7d6e47b587410 ]
        Actual hash: [ 7caaf29b29df29284604d4fb52ce9a3f8591cb067afffbe0ab747ed8f7cf0ce0c28c173d8ab97ffce9e2274dcfeb0249fd49d0ba192c8d53e4ede7f8c3f0652b ]

  Please delete the file and retry if this file should be downloaded again.

Call Stack (most recent call first):
  C:/VcPkg/vcpkg/scripts/cmake/vcpkg_download_distfile.cmake:78 (test_hash)
  C:/VcPkg/vcpkg/ports/sdl2/portfile.cmake:7 (vcpkg_download_distfile)
  C:/VcPkg/vcpkg/scripts/ports.cmake:72 (include)

Error: Building package sdl2:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: sdl2:x86-windows
  Vcpkg version: 0.0.100-2018-01-03-c4bc3a25e51563b8949380bf8fca99052caf07f0

**Comment by crackedmind** [comment]
Seems like cached file is broken. Remove C:/VcPkg/vcpkg/downloads/SDL2-2.0.7.tar.gz and reinstall.

```
> vcpkg hash downloads\SDL2-2.0.7.tar.gz
eed5477843086a0e66552eb197a5c4929134522bc366d873732361ea0df5fb841ef7e2b1913e21d1bae69e6fd3152ee630492e615c58cbe903e7d6e47b587410
```

**Comment by Pumkko** [comment]
There is something weird, no matter how many times i try to download the archive, i still get a corrupted file, my SDL2 archive is only 1Ko big

**Comment by Pumkko** [comment]
I was able to install it successfully by downloading the archive directly from SDL2's official website
