### ISSUE TITLE
[New Port Request] faac

### ISSUE THREAD

**Issue by oddlf** [microsoft/vcpkg#24972]
Library name: faac

Library description: Freeware Advanced Audio (AAC) Encoder

Source repository URL: https://github.com/knik0/faac

Project homepage (if different from the source repository): https://sourceforge.net/projects/faac/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

sister project of faad2: https://github.com/microsoft/vcpkg/pull/9003
example implementation: https://github.com/oddlf/libzplay/tree/main/vcpkg-ports/faac

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
