### ISSUE TITLE
[soundtouch] add integer feature (float is the default)

### ISSUE THREAD

**Issue by oddlf** [microsoft/vcpkg#24976]
****

**Is your feature request related to a problem? Please describe.**
This library has 2 modes of operation: float (32 bit) and integer (16 bit)
the default one is float

From the [CMakeLists.txt](https://codeberg.org/soundtouch/soundtouch/src/branch/master/CMakeLists.txt#L55)
```CMake
option(INTEGER_SAMPLES "Use integers instead of floats for samples" OFF)
if(INTEGER_SAMPLES)
  target_compile_definitions(SoundTouch PRIVATE SOUNDTOUCH_INTEGER_SAMPLES)
else()
  target_compile_definitions(SoundTouch PRIVATE SOUNDTOUCH_FLOAT_SAMPLES)
endif()
```

**Proposed solution**
Add a new feature `integer` where the data is 16 bit integers instead of floats.

**Describe alternatives you've considered**
I have a fork of the current port with this new feature: https://github.com/oddlf/libzplay/tree/main/vcpkg-ports/soundtouch

**Additional context**
example implementation: https://github.com/oddlf/libzplay/tree/main/vcpkg-ports/soundtouch

**Comment by JackBoosY** [comment]
Does feature `integer` conflict with feature `float`?

**Comment by oddlf** [comment]
From what I understand, the format of the audio data buffers depends on this option. I have the project above that uses the library and when `integer` isn't used, I get static from the speakers, because I'm sending floats to the soundcard that's expecting integers.

Note: the above project applies a patch that's just for that project. it's not needed for the feature.

**Comment by JackBoosY** [comment]
Since option INTEGER_SAMPLES does not conflict with other options, we can accept this feature.

I saw you have added this feature in your custom branch, can you please make a PR to add it?

Thanks.

**Comment by dg0yt** [comment]
> Since option INTEGER_SAMPLES does not conflict with other options, we can accept this feature.

This is not right. The option makes incompatible changes. Key location:
https://codeberg.org/soundtouch/soundtouch/src/branch/master/include/STTypes.h

**Comment by JackBoosY** [comment]
Well, this information proves that we cannot accept it.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

**Comment by JackBoosY** [comment]
I think you can use overlay-ports to apply your custom changes.
See https://github.com/microsoft/vcpkg/blob/master/docs/specifications/ports-overlay.md.
