### ISSUE TITLE
[New Port Request] JoltPhysics

### ISSUE THREAD

**Issue by bmarques1995** [microsoft/vcpkg#24981]
Library name: JoltPhysics

Library description: A multi-core friendly rigid body physics and collision detection library suitable for games and VR applications, used by Horizon Forbidden West.

Source repository URL: https://github.com/jrouwe/JoltPhysics.git

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by JackBoosY** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
