### ISSUE TITLE
[ogre] update to 13.3.4

### ISSUE THREAD

**Issue by Tarek-Hasan** [microsoft/vcpkg#24984]
Library name: ogre

New version number: 13.3.4

Other information that may be useful (release notes, etc...)
This port was last updated in 2020. Don't be confused with the new versioning number, ogre developers just dropped 1 from 1.13 so it's just v13 now.
https://github.com/OGRECave/ogre

**Comment by xavier2k6** [comment]
latest is now 13.4.2
