### ISSUE TITLE
[pkgconf] Build error

### ISSUE THREAD

**Issue by yangtx2009** [microsoft/vcpkg#24989]
**Host Environment**
- OS: Ubuntu 22.04 - Raspberry Pi 400
- Compiler: revision

**To Reproduce**
`./vcpkg install aubio`

**Failure logs**

Computing installation plan...
The following packages will be built and installed:
    aubio[core,tools]:arm64-linux -> 0.4.9#9
  * ffmpeg[avcodec,avdevice,avfilter,avformat,core,swresample,swscale]:arm64-linux -> 4.4.1#13
  * libflac[core]:arm64-linux -> 1.3.4
  * liblzma[core]:arm64-linux -> 5.2.5#6
  * libogg[core]:arm64-linux -> 1.3.5
  * libsndfile[core,external-libs,mpeg]:arm64-linux -> 1.1.0
  * libvorbis[core]:arm64-linux -> 1.3.7#2
  * mp3lame[core]:arm64-linux -> 3.100#7
  * mpg123[core]:arm64-linux -> 1.29.3
  * opus[core]:arm64-linux -> 1.3.1#6
  * pkgconf[core]:arm64-linux -> 1.8.0#3
  * vcpkg-cmake-config[core]:arm64-linux -> 2022-02-06
  * vcpkg-pkgconfig-get-modules[core]:arm64-linux -> 2022-02-10
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet arm64-linux...
Restored 0 packages from /home/pi/.cache/vcpkg/archives in 397.6 us. Use --debug to see more details.
Installing 1/13 pkgconf:arm64-linux...
Building pkgconf[core]:arm64-linux...
-- Using community triplet arm64-linux. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: /home/pi/vcpkg/triplets/community/arm64-linux.cmake
-- Using cached pkgconf-pkgconf-cef30268e1a3f79efd607c26abcf556aa314c9c4.tar.gz.
-- Cleaning sources at /home/pi/vcpkg/buildtrees/pkgconf/src/6aa314c9c4-8bd74a463d.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/pi/vcpkg/downloads/pkgconf-pkgconf-cef30268e1a3f79efd607c26abcf556aa314c9c4.tar.gz
-- Using source at /home/pi/vcpkg/buildtrees/pkgconf/src/6aa314c9c4-8bd74a463d.clean
-- Getting CMake variables for arm64-linux-dbg
-- Getting CMake variables for arm64-linux-rel
-- Configuring arm64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:128 (message):
    Command failed: /usr/bin/python3 /home/pi/vcpkg/installed/arm64-linux/tools/meson/meson.py -Dtests=false --buildtype plain --backend ninja --wrap-mode nodownload --native /home/pi/vcpkg/buildtrees/pkgconf/meson-native-arm64-linux.log --default-library static --libdir lib --native /home/pi/vcpkg/buildtrees/pkgconf/meson-native-arm64-linux-debug.log -Ddebug=true --prefix /home/pi/vcpkg/packages/pkgconf_arm64-linux/debug --includedir ../include -Dcmake_prefix_path=['/home/pi/vcpkg/installed/arm64-linux/debug','/home/pi/vcpkg/installed/arm64-linux'] /home/pi/vcpkg/buildtrees/pkgconf/src/6aa314c9c4-8bd74a463d.clean
    Working Directory: /home/pi/vcpkg/buildtrees/pkgconf/arm64-linux-dbg
    Error code: 2
    See logs for more information:
      /home/pi/vcpkg/buildtrees/pkgconf/config-arm64-linux-dbg-out.log
      /home/pi/vcpkg/buildtrees/pkgconf/config-arm64-linux-dbg-err.log

**Additional context**
I want to compile vcpkg packages in Raspberry Pi. I find that the package pkgconf cannot be compiled because it always need to run meson.py. The Python error is caused by the parameter `-Dcmake_prefix_path=['/home/pi/vcpkg/installed/arm64-linux/debug','/home/pi/vcpkg/installed/arm64-linux']`, because meson cannot resolve the list. I have tried Python 3.8 and 3.10. This problem always remains.

If I replace it with -Dcmake_prefix_path='/home/pi/vcpkg/installed/arm64-linux/debug and run it manually, the command can then proceed. However, I do not know where I should modify in order to workaround it during installation.

Thank you in advance!

**Comment by LilyWangLL** [comment]
This issue hasn’t been updated in 3 months, if it is still an issue, please reopen this issue.
