### ISSUE TITLE
[openssl] build failure

### ISSUE THREAD

**Issue by blatwo** [microsoft/vcpkg#24988]
**Host Environment**
- OS: Centos7.9
- Compiler: gcc10.3.0

**To Reproduce**
`./vcpkg install libpq`

**Failure logs**
error: building openssl:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+openssl
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[openssl]+Build+error
Include '[openssl] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-05-05-67e17c1782801cf481be9ac0b3765dff3e4bdeb8
    vcpkg-scripts version: unknown

-Please attach any additional failure logs mentioned in the console output.
[root@S01 vcpkg]# more /root/vcpkg/buildtrees/openssl/install-x64-linux-dbg-out.log
[1/3] cd /root/vcpkg/buildtrees/openssl/x64-linux-dbg/3.0.3-ba651081cb.clean && export PATH=/usr/bin:/opt/HighGo4.5.7-see/bin:/usr/lib64/qt-3.3/bin:/usr/loca
l/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:/usr/bin:/root/vcpkg/downloads/tools/ninja/1.10.2-linux && export CC=/usr/bin/cc && export AR=/usr/bin/ar 
&& export LD=/usr/bin/ld && export RANLIB=/usr/bin/ranlib && export MAKE=/usr/bin/make && export MAKEDEPPROG=/usr/bin/cc && export WINDRES= && /usr/bin/perl 
Configure no-shared no-module enable-static-engine no-zlib no-ssl2 no-idea no-cast no-seed no-md2 no-tests linux-x86_64 --prefix=/root/vcpkg/packages/openssl
_x64-linux/debug --openssldir=/etc/ssl "-fPIC -g" && /root/vcpkg/downloads/tools/cmake-3.22.2-linux/cmake-3.22.2-linux-x86_64/bin/cmake -DDIR=/root/vcpkg/bui
ldtrees/openssl/x64-linux-dbg/3.0.3-ba651081cb.clean -P /root/vcpkg/ports/openssl/unix/remove-deps.cmake
FAILED: 3.0.3-ba651081cb.clean/Makefile /root/vcpkg/buildtrees/openssl/x64-linux-dbg/3.0.3-ba651081cb.clean/Makefile 
cd /root/vcpkg/buildtrees/openssl/x64-linux-dbg/3.0.3-ba651081cb.clean && export PATH=/usr/bin:/opt/HighGo4.5.7-see/bin:/usr/lib64/qt-3.3/bin:/usr/local/sbin
:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:/usr/bin:/root/vcpkg/downloads/tools/ninja/1.10.2-linux && export CC=/usr/bin/cc && export AR=/usr/bin/ar && exp
ort LD=/usr/bin/ld && export RANLIB=/usr/bin/ranlib && export MAKE=/usr/bin/make && export MAKEDEPPROG=/usr/bin/cc && export WINDRES= && /usr/bin/perl Config
ure no-shared no-module enable-static-engine no-zlib no-ssl2 no-idea no-cast no-seed no-md2 no-tests linux-x86_64 --prefix=/root/vcpkg/packages/openssl_x64-l
inux/debug --openssldir=/etc/ssl "-fPIC -g" && /root/vcpkg/downloads/tools/cmake-3.22.2-linux/cmake-3.22.2-linux-x86_64/bin/cmake -DDIR=/root/vcpkg/buildtree
s/openssl/x64-linux-dbg/3.0.3-ba651081cb.clean -P /root/vcpkg/ports/openssl/unix/remove-deps.cmake
Can't locate IPC/Cmd.pm in @INC (@INC contains: /root/vcpkg/buildtrees/openssl/x64-linux-dbg/3.0.3-ba651081cb.clean/util/perl /usr/local/lib64/perl5 /usr/loc
al/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 . /root/vcpkg/buildtrees/openssl/x64-linux-dbg/3.0
.3-ba651081cb.clean/external/perl/Text-Template-1.56/lib) at /root/vcpkg/buildtrees/openssl/x64-linux-dbg/3.0.3-ba651081cb.clean/util/perl/OpenSSL/config.pm 
line 18.
BEGIN failed--compilation aborted at /root/vcpkg/buildtrees/openssl/x64-linux-dbg/3.0.3-ba651081cb.clean/util/perl/OpenSSL/config.pm line 18.
Compilation failed in require at Configure line 23.
BEGIN failed--compilation aborted at Configure line 23.
ninja: build stopped: subcommand failed.

**Additional context**
This can do as follow to resolve this problem:
yum install -y perl-CPAN
perl -MCPAN -e shell
cpan[1]> install IPC/Cmd.pm

**Comment by 0x8A63F77D** [comment]
Try `yum install perl-IPC-Cmd`.

**Comment by dg0yt** [comment]
> Include '[openssl] Build error' in your bug report title

Please change the title of the issue. It is not a `libpq` issue.

**Comment by blatwo** [comment]
> Try `yum install perl-IPC-Cmd`.

thank you!
