### ISSUE TITLE
[ogre-next] update to 2.3.0

### ISSUE THREAD

**Issue by Tarek-Hasan** [microsoft/vcpkg#24985]
Library name: ogre-next

New version number: 2.3.0

Other information that may be useful (release notes, etc...)
It has been 3 year since this port was last updated.
https://github.com/OGRECave/ogre-next/releases

**Comment by FrankXie05** [comment]
The port `[ogre-next]` has been updated to 2.3.0 #22058, please use the latest vcpkg and run the command `git pull`
