### ISSUE TITLE
VCPKG_APPLOCAL_DEPS copies incorrect DLL, breaking library package builds

### ISSUE THREAD

**Issue by rleigh-lumiradx** [microsoft/vcpkg#24983]
**Describe the bug**

This bug is a DLL mismatch as a result of the DLL copying performed by `VCPKG_APPLOCAL_DEPS`.  It copies the `tiffd.dll` or `tiff.dll` into the build tree.  However, when building the `tiff` library itself, it copies over the vcpkg copy of the library, rather than using the in-tree copy which was built during the package build.  This breaks unit test running, since it's using the older vcpkg copy rather than the actual copy already present in the build tree.

**Environment**
- OS: Windows 11
- Compiler: MSVC / VS2022

**To Reproduce**

1. `./vcpkg install tiff:x64-windows` [version 4.3.x at present using commit c8a56fdc]
2. `git clone https://gitlab.com/libtiff/libtiff.git`
3. `cd libtiff`
4. `git checkout v4.4.0`
5. `cmake -DCMAKE_TOOLCHAIN_FILE=\path\to\vcpkg\scripts\buildsystems\vcpkg.cmake -G Ninja -S \path\to\libtiff -B \path\to\libtiff\build`
-- Building tiff version 4.4.0
...
6. `cd build`
6. `ninja`
6. `ctest -V`

You can see the mismatches through the checksums below.  Note that the copied checksums match the vcpkg debug DLL.  And this is **not** the in-tree DLL which is what we actually need to use to meaningfully run tests or tools using the DLL.

```
rleigh@sorilea MINGW64 ~/code/libtiff ((19db1d31...))
$ find . -name 'tiff*.dll' | xargs sha256sum
6db42b57c66c512af6d5e02f5c7149e5e69a4348024defadf432682067be1a4e *./cmake-build-default-visual-studio-2022/contrib/addtiffo/tiffd.dll
6db42b57c66c512af6d5e02f5c7149e5e69a4348024defadf432682067be1a4e *./cmake-build-default-visual-studio-2022/contrib/dbs/tiffd.dll
e78365364232974d75456dce7b768913715b7606c4911fa4a35d64e0c76845b6 *./cmake-build-default-visual-studio-2022/libtiff/tiffd.dll
d3c2e1bf39e7760eb5d79234298a1b5cca681bee465987970b60e66c6bd86b4f *./cmake-build-default-visual-studio-2022/libtiff/tiffxxd.dll
6db42b57c66c512af6d5e02f5c7149e5e69a4348024defadf432682067be1a4e *./cmake-build-default-visual-studio-2022/test/tiffd.dll
6db42b57c66c512af6d5e02f5c7149e5e69a4348024defadf432682067be1a4e *./cmake-build-default-visual-studio-2022/tools/tiffd.dll

rleigh@sorilea MINGW64 ~/code/libtiff ((19db1d31...))
$ find ../vcpkg -name 'tiff*.dll' | xargs sha256sum
133be7e62aee2131450f08dbaf4962bd65906e74e7f993cf638b0699913a169f *../vcpkg/installed/x64-windows/bin/tiff.dll
6db42b57c66c512af6d5e02f5c7149e5e69a4348024defadf432682067be1a4e *../vcpkg/installed/x64-windows/debug/bin/tiffd.dll
```

**Expected behavior**
Build completes and tests all pass.

If I do not use the `vcpkg` toolchain file, this works as expected.

**Failure logs**
[tiff-test-fail-vcpkg-dll-used.txt](https://github.com/microsoft/vcpkg/files/8792861/tiff-test-fail-vcpkg-dll-used.txt)

**Additional context**

This failure is purely down to the behaviour of `VCPKG_APPLOCAL_DEPS` making an unwarranted assumption.  It won't be seen internally since vcpkg will uninstall tiff before building a new copy.  But for external users, it's going to be triggered for any package building a library which is also present in the vcpkg install directory.  In this case this was libtiff, but it applies to all situations where library copying would copy the wrong library.

I would suggest that this monkeypatching be dropped.  It's counterintuitive and dangerous.

I would suggest that a better solution would be to update the runtime PATH to include both the vcpkg DLL directories and the build tree directories (with the latter having precedence) so that the DLLs will be automatically found without the need to copy them.  Extending CMake to support this, rather than patching around it, would be much more flexible.  CTest could be extended to permit prepending paths to PATH.  Similarly for, `add_custom_command` and `add_custom_target`, maybe with some global PATH prefixes which cmake could use to default the extra paths.

I'm not sure of the best solution here.  The current approach does solve a real problem.  But it's being solved at the wrong level, and is too fragile to be fully practical.

**Comment by JackBoosY** [comment]
We assume that the user projects that use the vcpkg integration use the ports in vcpkg. If the ports in vcpkg and the same customized port are used at the same time, the following problems will occur:
1. The installed library will conflict.
2. The dependent library cannot determine which version to use.
3. The symbols will conflict.

Your use case clearly violates this. You can use the vcpkg feature overlay port to solve this problem.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

**Comment by rleigh-lumiradx** [comment]
@JackBoosY The part that the answer doesn't address is upstream development.  You're quite correct that it works when you're building everything within the context of a vcpkg build.  But it doesn't address downstream use of vcpkg at all, where a leaf package is built using vcpkg dependencies during *routine development* of the package as opposed to *deployment of a released version*.

**Comment by rleigh-lumiradx** [comment]
As an example, I use vcpkg to provision dependencies for CI builds of libtiff on AppVeyor for Windows.  This is not running the unit tests against the built version of libtiff.  It's copying in an old version.  That's completely breaking the workflow for both clould-based CI, and also local development when building with MSVC.

**Comment by JackBoosY** [comment]
@rleigh-lumiradx For this scenes, you may need to use [manifest mode](https://github.com/microsoft/vcpkg/blob/master/docs/users/manifests.md) to isolate the test phase from the build phase.
You may also need to use the [registry feature](https://github.com/microsoft/vcpkg/blob/master/docs/users/registries.md) if you need to use the port in vcpkg that depends on custom libtiff instead of port libtiff in vcpkg.

**Comment by dg0yt** [comment]
> But for external users, it's going to be triggered for any package building a library which is also present in the vcpkg install directory.

In general, you cannot safely build and use "a library which is also present in the vcpkg install directory". This would open the door for unpredictable behaviour at run time when symbols and behaviours in other depending libs from vcpkg are resolved differently than at build time. If you don't want the library from vcpkg, you have to provide an empty overlay port instead.
