### ISSUE TITLE
Request add CImg

### ISSUE THREAD

**Issue by vindar** [Microsoft/vcpkg#2499]
It would be nice to have a package for the image processing toolkit CImg (http://cimg.eu). 

It is distributed under CeCILL licences which are GPL compatible. 

Making a package is straightforward since the whole library is a single header file without additional dependencies. Yet, having a package for this library would still simplify the process of updating the library when a new version is released. 

I can create the package if needed.

**Comment by ras0219-msft** [comment]
We'd be happy to accept a PR for CImg!
