### ISSUE TITLE
[openssl] Build error

### ISSUE THREAD

**Issue by gheorghitamutu** [microsoft/vcpkg#25003]
**Host Environment**
- OS: Windows x64
- Compiler: Visual Studio 17 2022

**To Reproduce**
The following packages will be built and installed:
    openssl[core]:x64-windows -> 1.1.1n -- C:\vcpkg\buildtrees\versioning_\versions\openssl\7e4d802e3bde4[15](https://github.com/gdt050579/GView/runs/6653617961?check_suite_focus=true#step:6:16)4c227c0dd1da75c719be9f07a
  * vcpkg-cmake[core]:x64-windows -> 2021-02-28#3 -- C:\vcpkg\buildtrees\versioning_\versions\vcpkg-cmake\0e8bb94599a00fd9c61fd0ae524c22a067c21420
  * vcpkg-cmake-config[core]:x64-windows -> 2021-05-22 -- C:\vcpkg\buildtrees\versioning_\versions\vcpkg-cmake-config\2d4f997a32b8e8bfe98d12beb2bfe6be713c7086

**Failure logs**
(https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win32/nasm-2.15.05-win32.zip: WinHttpSendRequest() failed: 12002
https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win32/nasm-2.15.05-win32.zip: WinHttpSendRequest() failed: 12002
https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win32/nasm-2.15.05-win32.zip: WinHttpSendRequest() failed: 12002
https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win32/nasm-2.15.05-win32.zip: WinHttpSendRequest() failed: 12002
https://fossies.org/windows/misc/nasm-2.15.05-win32.zip: failed: status code 410)

**Additional context**
    vcpkg-tool version: 2022-05-05-67e17c1782801cf481be9ac0b3765dff3e4bdeb8
    vcpkg-scripts version: 314018fef 2022-05-20 (10 days ago)

**Comment by gheorghitamutu** [comment]
[vcpkg.json.txt](https://github.com/microsoft/vcpkg/files/8797945/vcpkg.json.txt)

**Comment by stevecotton** [comment]
Dup of #24871.

**Comment by Adela0814** [comment]
Please download [this file](https://github.com/microsoft/vcpkg/files/8760120/nasm-2.15.05-win32.zip) and put it into VCPKG_ROOT/downloads then try again.
