### ISSUE TITLE
[wxwidgets] Build error

### ISSUE THREAD

**Issue by stfzy** [microsoft/vcpkg#25006]
**Host Environment**
- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**
`./vcpkg install xxxx`

**Failure logs**
-Cut and paste the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by LilyWangLL** [comment]
Please provide the error log file or text.

**Comment by stfzy** [comment]
-- Using community triplet x86-windows-static. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: D:\code\vcpkg\triplets\community\x86-windows-static.cmake
-- Using cached wxWidgets-wxWidgets-35a6d7b15fedfdb5198bb6c28b31cda33b2c2a76.tar.gz.
-- Cleaning sources at D:/code/vcpkg/buildtrees/wxwidgets/src/a33b2c2a76-d7830df458.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/code/vcpkg/downloads/wxWidgets-wxWidgets-35a6d7b15fedfdb5198bb6c28b31cda33b2c2a76.tar.gz
-- Applying patch install-layout.patch
-- Applying patch relocatable-wx-config.patch
-- Applying patch nanosvg-ext-depend.patch
-- Applying patch fix-libs-export.patch
-- Applying patch fix-pcre2.patch
-- Using source at D:/code/vcpkg/buildtrees/wxwidgets/src/a33b2c2a76-d7830df458.clean
-- Using cached msys-mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst.
-- Using msys root at D:/code/vcpkg/downloads/tools/msys2/9a1ec3f33446b195
-- Found external ninja('1.10.2').
-- Configuring x86-windows-static
-- Building x86-windows-static-dbg
CMake Warning at scripts/cmake/vcpkg_execute_build_process.cmake:89 (message):
  Please ensure your system has sufficient memory.
Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:111 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
  ports/wxwidgets/portfile.cmake:103 (vcpkg_cmake_install)
  scripts/ports.cmake:146 (include)


-- Restarting build without parallelism
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:158 (message):
    Command failed: D:/code/vcpkg/downloads/tools/cmake-3.22.2-windows/cmake-3.22.2-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j13
    Working Directory: D:/code/vcpkg/buildtrees/wxwidgets/x86-windows-static-dbg
    See logs for more information:
      D:\code\vcpkg\buildtrees\wxwidgets\install-x86-windows-static-dbg-out.log
      D:\code\vcpkg\buildtrees\wxwidgets\install-x86-windows-static-dbg-out-1.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:111 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
  ports/wxwidgets/portfile.cmake:103 (vcpkg_cmake_install)
  scripts/ports.cmake:146 (include)


error: building wxwidgets:x86-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+wxwidgets
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[wxwidgets]+Build+error
Include '[wxwidgets] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-05-05-67e17c1782801cf481be9ac0b3765dff3e4bdeb8
    vcpkg-scripts version: d953973cf 2022-05-27 (3 days ago)

**Comment by stfzy** [comment]
“D:\code\vcpkg\buildtrees\wxwidgets\install-x86-windows-static-dbg-out-1.log”

[1/370] cmd.exe /C "cd . && D:\code\vcpkg\downloads\tools\cmake-3.22.2-windows\cmake-3.22.2-windows-i386\bin\cmake.exe -E vs_link_exe --intdir=utils\CMakeFiles\wxrc.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\mt.exe --manifests  -- C:\PROGRA~1\MICROS~3\2022\ENTERP~1\VC\Tools\MSVC\1432~1.313\bin\Hostx64\x86\link.exe  utils\CMakeFiles\wxrc.dir\__\__\__\utils\wxrc\wxrc.cpp.obj  /out:lib\wxrc.exe /implib:lib\wxrc.lib /pdb:lib\wxrc.pdb /version:0.0 /machine:X86 /nologo    /debug /INCREMENTAL /subsystem:console  lib\wxbase31ud_xml.lib  lib\wxbase31ud.lib  D:\code\vcpkg\installed\x86-windows-static\debug\lib\zlibd.lib  pcre2-16d.lib  kernel32.lib  user32.lib  gdi32.lib  comdlg32.lib  winspool.lib  winmm.lib  shell32.lib  shlwapi.lib  comctl32.lib  ole32.lib  oleaut32.lib  uuid.lib  rpcrt4.lib  advapi32.lib  version.lib  ws2_32.lib  wininet.lib  oleacc.lib  uxtheme.lib  D:\code\vcpkg\installed\x86-windows-static\debug\lib\libexpatdMD.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
FAILED: lib/wxrc.exe 
cmd.exe /C "cd . && D:\code\vcpkg\downloads\tools\cmake-3.22.2-windows\cmake-3.22.2-windows-i386\bin\cmake.exe -E vs_link_exe --intdir=utils\CMakeFiles\wxrc.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\mt.exe --manifests  -- C:\PROGRA~1\MICROS~3\2022\ENTERP~1\VC\Tools\MSVC\1432~1.313\bin\Hostx64\x86\link.exe  utils\CMakeFiles\wxrc.dir\__\__\__\utils\wxrc\wxrc.cpp.obj  /out:lib\wxrc.exe /implib:lib\wxrc.lib /pdb:lib\wxrc.pdb /version:0.0 /machine:X86 /nologo    /debug /INCREMENTAL /subsystem:console  lib\wxbase31ud_xml.lib  lib\wxbase31ud.lib  D:\code\vcpkg\installed\x86-windows-static\debug\lib\zlibd.lib  pcre2-16d.lib  kernel32.lib  user32.lib  gdi32.lib  comdlg32.lib  winspool.lib  winmm.lib  shell32.lib  shlwapi.lib  comctl32.lib  ole32.lib  oleaut32.lib  uuid.lib  rpcrt4.lib  advapi32.lib  version.lib  ws2_32.lib  wininet.lib  oleacc.lib  uxtheme.lib  D:\code\vcpkg\installed\x86-windows-static\debug\lib\libexpatdMD.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
LINK Pass 1: command "C:\PROGRA~1\MICROS~3\2022\ENTERP~1\VC\Tools\MSVC\1432~1.313\bin\Hostx64\x86\link.exe utils\CMakeFiles\wxrc.dir\__\__\__\utils\wxrc\wxrc.cpp.obj /out:lib\wxrc.exe /implib:lib\wxrc.lib /pdb:lib\wxrc.pdb /version:0.0 /machine:X86 /nologo /debug /INCREMENTAL /subsystem:console lib\wxbase31ud_xml.lib lib\wxbase31ud.lib D:\code\vcpkg\installed\x86-windows-static\debug\lib\zlibd.lib pcre2-16d.lib kernel32.lib user32.lib gdi32.lib comdlg32.lib winspool.lib winmm.lib shell32.lib shlwapi.lib comctl32.lib ole32.lib oleaut32.lib uuid.lib rpcrt4.lib advapi32.lib version.lib ws2_32.lib wininet.lib oleacc.lib uxtheme.lib D:\code\vcpkg\installed\x86-windows-static\debug\lib\libexpatdMD.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:utils\CMakeFiles\wxrc.dir/intermediate.manifest utils\CMakeFiles\wxrc.dir/manifest.res" failed (exit code 1104) with the following output:
LINK : fatal error LNK1104: 无法打开文件“pcre2-16d.lib”
ninja: build stopped: subcommand failed.

**Comment by LilyWangLL** [comment]
Did you install `wxwidgets:x64-windows-static` also failed?

**Comment by stfzy** [comment]
wxwidgets:x64-windows-static is OK

**Comment by LilyWangLL** [comment]
Please also provide the log file: config-x86-windows-static-out.log.

**Comment by stfzy** [comment]
[install-x86-windows-static-dbg-out.log](https://github.com/microsoft/vcpkg/files/8802201/install-x86-windows-static-dbg-out.log)

**Comment by LilyWangLL** [comment]
@stfzy Please provide config log: `config-x86-windows-static-out.log`, because this log have the following message:
```
-- Found PCRE2: E:/Lily/0509/installed/x86-windows-static/lib/pcre2-16.lib (found version "10.40") 
```

**Comment by stfzy** [comment]
[config-x86-windows-static-out.log](https://github.com/microsoft/vcpkg/files/8810620/config-x86-windows-static-out.log)

**Comment by LilyWangLL** [comment]
Did you install `pcre2` before? The version of `pcre2` in your config log is 10.39, this is outed, the latest version of `pcre2` is 10.40. Could you please remove your old `pcre2` and rebuild it and `wxwidgets`? If `wxwidgets` still install failed, please provide the config and install log. Thanks~

The log information:
```
-- Check size of wchar_t - done
-- Found PCRE2: pcre2-16 (found version "10.39") 
-- Found ZLIB: optimized;D:/code/vcpkg/installed/x86-windows-static/lib/zlib.lib;debug;D:/code/vcpkg/installed/x86-windows-static/debug/lib/zlibd.lib (found version "1.2.12") 
```

**Comment by stfzy** [comment]
It's solved, thanks

**Comment by LilyWangLL** [comment]
Since this issue has been resolved, so I am closing this issue for now.
