### ISSUE TITLE
[qt5-imageformats] Build error

### ISSUE THREAD

**Issue by lijingjian001** [microsoft/vcpkg#25007]
**Host Environment**
- OS: Windows11
- Compiler: revision

**To Reproduce**
`./vcpkg install qt5`

**Failure logs**
Computing installation plan...
The following packages will be built and installed:
    qt5[activeqt,core,declarative,essentials,imageformats,multimedia,networkauth,quickcontrols2,svg,tools]:x86-windows -> 5.15.4
  * qt5-activeqt[core]:x86-windows -> 5.15.4
  * qt5-declarative[core]:x86-windows -> 5.15.4
  * qt5-imageformats[core]:x86-windows -> 5.15.4
  * qt5-multimedia[core]:x86-windows -> 5.15.4
  * qt5-networkauth[core]:x86-windows -> 5.15.4
  * qt5-quickcontrols2[core]:x86-windows -> 5.15.4
  * qt5-svg[core]:x86-windows -> 5.15.4
  * qt5-tools[core]:x86-windows -> 5.15.4
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x86-windows...
Restored 0 packages from C:\Users\LiJingJian\AppData\Local\vcpkg\archives in 299.6 us. Use --debug to see more details.
Installing 1/9 qt5-imageformats:x86-windows...
Building qt5-imageformats[core]:x86-windows...
CMake Warning at scripts/cmake/vcpkg_buildpath_length_warning.cmake:18 (message):
  qt5-imageformats's buildsystem uses very long paths and may fail on your
  system.

  We recommend moving vcpkg to a short path such as 'C:\src\vcpkg' or using
  the subst command.
Call Stack (most recent call first):
  installed/x86-windows/share/qt5/qt_download_submodule.cmake:13 (vcpkg_buildpath_length_warning)
  installed/x86-windows/share/qt5/qt_submodule_installation.cmake:5 (qt_download_submodule)
  ports/qt5-imageformats/portfile.cmake:54 (qt_submodule_installation)
  scripts/ports.cmake:146 (include)

-- Using cached qtimageformats-everywhere-opensource-src-5.15.4.tar.xz.
-- Cleaning sources at E:/kaiyuan_project/kaiyuan_complex_c_c++/vcpkg/buildtrees/qt5-imageformats/src/5.15.4-bcd2eef2c0.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/kaiyuan_project/kaiyuan_complex_c_c++/vcpkg/downloads/qtimageformats-everywhere-opensource-src-5.15.4.tar.xz
-- Using source at E:/kaiyuan_project/kaiyuan_complex_c_c++/vcpkg/buildtrees/qt5-imageformats/src/5.15.4-bcd2eef2c0.clean
-- Using cached msys-mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst.
-- Using msys root at E:/kaiyuan_project/kaiyuan_complex_c_c++/vcpkg/downloads/tools/msys2/9a1ec3f33446b195
-- Configuring x86-windows-rel
-- Configuring x86-windows-rel done
-- Configuring x86-windows-dbg
-- Configuring x86-windows-dbg done
-- Package build-x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:158 (message):
    Command failed: E:/kaiyuan_project/kaiyuan_complex_c_c++/vcpkg/downloads/tools/jom/jom-1.1.3/jom.exe -j 9
    Working Directory: E:/kaiyuan_project/kaiyuan_complex_c_c++/vcpkg/buildtrees/qt5-imageformats/x86-windows-dbg
    See logs for more information:
      E:\kaiyuan_project\kaiyuan_complex_c_c++\vcpkg\buildtrees\qt5-imageformats\package-build-x86-windows-dbg-out.log
      E:\kaiyuan_project\kaiyuan_complex_c_c++\vcpkg\buildtrees\qt5-imageformats\package-build-x86-windows-dbg-err.log

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.
[package-build-x86-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/8799160/package-build-x86-windows-dbg-err.log)
[package-build-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/8799161/package-build-x86-windows-dbg-out.log)

**Comment by Osyotr** [comment]
Where is qt5-base??

**Comment by dg0yt** [comment]
> Where is qt5-base??

I guess this refers to the "installation plan". From a clean build, we would expect to see the installation of port `qt5-base`.

**Comment by Osyotr** [comment]
Don't install `qt5`, install individual ports instead (`qt5-base`, `qt5-declarative`, etc)

**Comment by lijingjian001** [comment]
> Don't install `qt5`, install individual ports instead (`qt5-base`, `qt5-declarative`, etc)
Thank you. It's normal now
