### ISSUE TITLE
[libjpeg-turbo] Build error

### ISSUE THREAD

**Issue by nullrick** [microsoft/vcpkg#25000]
**Host Environment**
- OS: windows 10  in virtualbox
- Compiler: vcpkg 2022-05-05-67e17c1782801cf481be9ac0b3765dff3e4bdeb8

**To Reproduce**
`./vcpkg install opencv`

**Failure logs**
Computing installation plan...
The following packages will be built and installed:
  * libjpeg-turbo[core]:x86-windows -> 2.1.3#3
  * liblzma[core]:x86-windows -> 5.2.5#6
  * libpng[core]:x86-windows -> 1.6.37#17
  * libwebp[core,libwebpmux,nearlossless,simd,unicode]:x86-windows -> 1.2.2
    opencv[core,default-features]:x86-windows -> 4.5.5
  * opencv4[core,default-features,dnn,jpeg,png,quirc,tiff,webp]:x86-windows -> 4.5.5#4
  * protobuf[core]:x64-windows -> 3.19.4
  * protobuf[core]:x86-windows -> 3.19.4
  * quirc[core]:x86-windows -> 1.1#2
  * tiff[core,jpeg,lzma,zip]:x86-windows -> 4.3.0#8
  * vcpkg-get-python-packages[core]:x64-windows -> 2022-04-11
  * zlib[core]:x86-windows -> 1.2.12#1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x86-windows...
Detecting compiler hash for triplet x64-windows...
Restored 0 packages from C:\Users\Administrator\AppData\Local\vcpkg\archives in 255.5 us. Use --debug to see more details.
Installing 1/12 libjpeg-turbo:x86-windows...
Building libjpeg-turbo[core]:x86-windows...
-- Using cached libjpeg-turbo-libjpeg-turbo-c5f269eb9665435271c05fbcaf8721fa58e9eafa.tar.gz.
-- Cleaning sources at C:/vcpkg/buildtrees/libjpeg-turbo/src/fa58e9eafa-51b986428d.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg/downloads/libjpeg-turbo-libjpeg-turbo-c5f269eb9665435271c05fbcaf8721fa58e9eafa.tar.gz
-- Applying patch add-options-for-exes-docs-headers.patch
-- Applying patch workaround_cmake_system_processor.patch
-- Using source at C:/vcpkg/buildtrees/libjpeg-turbo/src/fa58e9eafa-51b986428d.clean
-- Downloading https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win32/nasm-2.15.05-win32.zip;https://fossies.org/windows/misc/nasm-2.15.05-win32.zip -> nasm-2.15.05-win32.zip...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' = off
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Downloading https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win32/nasm-2.15.05-win32.zip
[DEBUG] Download failed -- retrying after 1000 ms.
[DEBUG] Download failed -- retrying after 2000 ms.
[DEBUG] Download failed -- retrying after 4000 ms.
[DEBUG] Downloading https://fossies.org/windows/misc/nasm-2.15.05-win32.zip
Error: Failed to download from mirror set:
https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win32/nasm-2.15.05-win32.zip: WinHttpSendRequest() failed: 12002
https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win32/nasm-2.15.05-win32.zip: WinHttpSendRequest() failed: 12002
https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win32/nasm-2.15.05-win32.zip: WinHttpSendRequest() failed: 12002
https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win32/nasm-2.15.05-win32.zip: WinHttpSendRequest() failed: 12002
https://fossies.org/windows/misc/nasm-2.15.05-win32.zip: failed: status code 410

[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(751):
[DEBUG] Time in subprocesses: 0 us
[DEBUG] Time in parsing JSON: 2 us
[DEBUG] Time in JSON reader: 0 us
[DEBUG] Time in filesystem: 8392 us
[DEBUG] Time in loading ports: 0 us
[DEBUG] Exiting after 8.229 min (493708201 us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:84 (message):

      Failed to download file with error: 1
      If you use a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.

      3. Your proxy's remote server is out of service.

      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)

      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:309 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_find_acquire_program.cmake:650 (vcpkg_download_distfile)
  ports/libjpeg-turbo/portfile.cmake:21 (vcpkg_find_acquire_program)
  scripts/ports.cmake:146 (include)

error: building libjpeg-turbo:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libjpeg-turbo
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[libjpeg-turbo]+Build+error
Include '[libjpeg-turbo] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-05-05-67e17c1782801cf481be9ac0b3765dff3e4bdeb8
    vcpkg-scripts version: d953973cf 2022-05-27 (2 days ago)

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by nullrick** [comment]
I don't use any proxy.

**Comment by LilyWangLL** [comment]
Close this issue because the nasm server worked again.
