### ISSUE TITLE
[crashpad] Build error with clang-cl on Windows

### ISSUE THREAD

**Issue by old-pigeon** [microsoft/vcpkg#25011]
**Host Environment**
- OS: Windows 11 Pro
- Compiler: Clang 13.0.1 (installed with Visual Studio)
- Visual Studio 2022 version 17.2

**To Reproduce**

Use `clang-cl` with CMake, like so (from `CMakePresets.json`):
```
"cacheVariables": {
  "CMAKE_C_COMPILER": "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/Llvm/x64/bin/clang-cl.exe",
  "CMAKE_CXX_COMPILER": "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/Llvm/x64/bin/clang-cl.exe"
},
```
Then add `crashpad` into the `dependencies`-array in `vcpkg.json`.

**Failure logs**
- [build-x64-windows-static-dbg-out.log](https://github.com/microsoft/vcpkg/files/8801092/build-x64-windows-static-dbg-out.log)
- [crashpad-build.log](https://github.com/microsoft/vcpkg/files/8801099/crashpad-build.log)

**Additional context**
- I need crashpad for x64 statically build
- I fully updated vcpkg

**Comment by JackBoosY** [comment]
I don't think it should work.
We're set to use MSVC in Windows, so the cmake settings in the Windows toolchain are for MSVC, not clang.
See https://github.com/microsoft/vcpkg/blob/master/scripts/toolchains/windows.cmake

**Comment by old-pigeon** [comment]
Thanks for the quick reply.

Do you recommend me trying to tweak it for clang or would you say this endeavor is basically hopeless as vcpkg is built for MSVC and me doing that would basically be a hack?

**Comment by JackBoosY** [comment]
I'd prefer to add a new toolchain `clang-cl.cmake` to https://github.com/microsoft/vcpkg/tree/master/scripts/toolchains
And add new community triplet such as `x86-windows-clang` to use it.

**Comment by old-pigeon** [comment]
That sounds like a good idea.

Do you think that I, as a vcpkg end user, can help producing this toolchain? Do you accept MRs from the public for stuff like this? Or does this need more planning for the small details?

Also, I still think this might be a bug in the crashpad package. Because if I understood it right, vcpkg tries to isolate itself from the actual outer CMake project. And that works well for all other packages we use: all of them use MSVC even though we are using clang-cl for our project. But crashpad doesn't. For some reason it tries to use clang-cl, which to me, looks like inconsistent behavior.

**Comment by Neumann-A** [comment]
https://github.com/Neumann-A/my-vcpkg-triplets/blob/master/x64-windows-llvm.cmake

**Comment by JackBoosY** [comment]
@old-pigeon We can accept that. In fact, some other toolchains / community triplets are come from contributors.

```
C:/vcpkg/downloads/tools/python/python-3.10.2-x64/python.exe C:/v/crashpad/src/86e8d5a126-0d522bae5c.clean/third_party/mini_chromium/mini_chromium/build/win_helper.py link-wrapper environment.amd64 lib.exe /nologo /out:obj/third_party/getopt/getopt.lib  /LTCG:OFF obj/third_party/getopt/getopt.getopt.obj
The system cannot find the path specified.
```
The reason is cmake couldn't find `lib.exe`.

**Comment by Neumann-A** [comment]
The problem here is that `crashpad` is using `vcpkg-gn`. `GN` is not yet correctly setup to work with custom toolchains. So somebody needs to figure out how `gn` works and how it can be fed a custom toolchain with compiler settings, flags and all that stuff.

**Comment by old-pigeon** [comment]
Is there a way to let crashpad build with MSVC until this is fixed even though I keep my CMakePresets with clang? I. e. something like this (pseudo-code):

```cmake
set(CMAKE_C_COMPILER cl.exe)
set(CMAKE_CXX_COMPILER cl.exe)

vcpkg_install_now()

# set CMAKE_C_COMPILER and CMAKE_CXX_COMPILER back to clang/whatever was in CMakePresets
```

**Comment by LilyWangLL** [comment]
Now crashpad works fine on windows with using vcpkg-gn, if someone has new idea about use clang to build crashpad on windows, please reopen this issue.
