### ISSUE TITLE
[angle] Build error

### ISSUE THREAD

**Issue by lijingjian001** [microsoft/vcpkg#25013]
**Host Environment**
- OS: Windows
- Compiler: revision
- vcpkg-tool version: 2022-05-05-67e17c1782801cf481be9ac0b3765dff3e4bdeb8
- vcpkg-scripts version: d953973cf 2022-05-27

**To Reproduce**
`./vcpkg install angle`

**Failure logs**
-Computing installation plan...
The following packages will be built and installed:
    angle[core]:x86-windows -> chromium_4472#3
Detecting compiler hash for triplet x86-windows...
Restored 0 packages from C:\Users\xxxxxx\AppData\Local\vcpkg\archives in 642.1 us. Use --debug to see more details.
Installing 1/1 angle:x86-windows...
Building angle[core]:x86-windows...
-- Using cached google-angle-d15be77864e18f407c317be6f6bc06ee2b7d070a.tar.gz.
-- Cleaning sources at E:/kaiyuan_project/kaiyuan_complex_c_c++/vcpkg/buildtrees/angle/src/ee2b7d070a-83a419ab43.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/kaiyuan_project/kaiyuan_complex_c_c++/vcpkg/downloads/google-angle-d15be77864e18f407c317be6f6bc06ee2b7d070a.tar.gz
-- Applying patch 001-fix-uwp.patch
-- Applying patch 002-fix-builder-error.patch
-- Applying patch 003-fix-mingw.patch
-- Using source at E:/kaiyuan_project/kaiyuan_complex_c_c++/vcpkg/buildtrees/angle/src/ee2b7d070a-83a419ab43.clean
-- Using cached E:/kaiyuan_project/kaiyuan_complex_c_c++/vcpkg/downloads/angle-09490503d0f201b81e03f5ca0ab8ba8ee76d4a8e.tar.gz
-- Extracting source E:/kaiyuan_project/kaiyuan_complex_c_c++/vcpkg/downloads/angle-09490503d0f201b81e03f5ca0ab8ba8ee76d4a8e.tar.gz
-- Applying patch third-party-zlib-far-undef.patch
-- Using source at E:/kaiyuan_project/kaiyuan_complex_c_c++/vcpkg/buildtrees/angle/src/8ee76d4a8e-895bfc7289.clean
-- Found external ninja('1.10.2').
-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:158 (message):
    Command failed: "D:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j9
    Working Directory: E:/kaiyuan_project/kaiyuan_complex_c_c++/vcpkg/buildtrees/angle/x86-windows-dbg
    See logs for more information:
      E:\kaiyuan_project\kaiyuan_complex_c_c++\vcpkg\buildtrees\angle\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:113 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:44 (vcpkg_build_cmake)
  ports/angle/portfile.cmake:64 (vcpkg_install_cmake)
  scripts/ports.cmake:146 (include)

error: building angle:x86-windows failed with: BUILD_FAILED

**Additional context**
[install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/8801906/install-x86-windows-dbg-out.log)

**Comment by Cheney-W** [comment]
What's the version of your Visual Studio?

**Comment by lijingjian001** [comment]
> What's the version of your Visual Studio?

Microsoft Visual Studio Community 2022 (64 位)

**Comment by Cheney-W** [comment]
Thanks for your reply! I want to know the specific version number, you could get it from:
![image](https://user-images.githubusercontent.com/38240633/171151614-65c851df-64b2-469a-a50d-ff707953ce53.png)

**Comment by lijingjian001** [comment]
ok! 
![image](https://user-images.githubusercontent.com/12969526/171156523-6ec07388-0b75-43e0-a0cb-a9d68791c369.png)

**Comment by Cheney-W** [comment]
This issue is a bug of Visual Studio, I have file a feedback ticket on the Develop Community: https://developercommunity.visualstudio.com/t/Internal-compiler-error-when-install-ang/10059040
You could track the status of this issue by that ticket.
