### ISSUE TITLE
[gtk] Build Error

### ISSUE THREAD

**Issue by RReventlov** [microsoft/vcpkg#25015]
**Host Environment**
- OS: Windows 11
- Compiler: Visual C++

**To Reproduce**
`./vcpkg install gtk`

**Failure logs**
error: building gtk:x64-windows failed with: BUILD_FAILED

[package-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/8803694/package-x64-windows-dbg-err.log)
[package-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/8803696/package-x64-windows-dbg-out.log)

**Additional context**
vcpkg-tool version: 2022-05-05-67e17c1782801cf481be9ac0b3765dff3e4bdeb8
vcpkg-scripts version: d953973cf 2022-05-27 (3 days ago)

I am not comfortable with C++ Build systems (I know Gtk and wanted to play with C++) so I have not tried anything besides from restarting my PC.

**Comment by JackBoosY** [comment]
Maybe related to directory name _.vcpkg_.

**Comment by GitHubYjan** [comment]
I have tried renaming `.vcpkg` -> `vcpkg` and `C++` -> `Cpp` but the error message is still the same. The error logs are also the same.

**Comment by JackBoosY** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.
