### ISSUE TITLE
[qt5-webengine] Build error

### ISSUE THREAD

**Issue by hyzboy** [microsoft/vcpkg#25023]
**Host Environment**
- OS: [e.g. Windows]
- Compiler: vc2022

**To Reproduce**
`./vcpkg install qt5-webengine:x64-windows`

vcpkg-tool version: 2022-05-05-67e17c1782801cf481be9ac0b3765dff3e4bdeb8
vcpkg-scripts version: f78f4440d 2022-05-31 (9 hours ago
[package-build-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/8812367/package-build-x64-windows-dbg-out.log)
[package-build-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/8812369/package-build-x64-windows-dbg-err.log)
)

**Comment by Cheney-W** [comment]
Dup to https://github.com/microsoft/vcpkg/issues/25013
