### ISSUE TITLE
[fontconfig] Build error

### ISSUE THREAD

**Issue by chuckypt** [microsoft/vcpkg#25035]
**Host Environment**
- OS: centos stream 8
- Compiler: gcc version 8.5.0 20210514 (Red Hat 8.5.0-13) (GCC)

**To Reproduce**
`./vcpkg install fontconfig:x64-linux`

**Failure logs**
```
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:128 (message):
    Command failed: /usr/bin/python3 /home/vcpkg/installed/x64-linux/tools/meson/meson.py -Ddoc=disabled -Dcache-build=disabled -Dtests=disabled --buildtype plain --backend ninja --wrap-mode nodownload --native /home/vcpkg/buildtrees/fontconfig/meson-native-x64-linux.log --default-library static --libdir lib --native /home/vcpkg/buildtrees/fontconfig/meson-native-x64-linux-debug.log -Ddebug=true --prefix /home/vcpkg/packages/fontconfig_x64-linux/debug --includedir ../include -Dcmake_prefix_path=['/home/vcpkg/installed/x64-linux/debug','/home/vcpkg/installed/x64-linux'] /home/vcpkg/buildtrees/fontconfig/src/2.14.0-523cc719dc.clean
    Working Directory: /home/vcpkg/buildtrees/fontconfig/x64-linux-dbg
    Error code: 1
    See logs for more information:
      /home/vcpkg/buildtrees/fontconfig/config-x64-linux-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_meson.cmake:470 (vcpkg_execute_required_process)
  ports/fontconfig/portfile.cmake:17 (vcpkg_configure_meson)
  scripts/ports.cmake:146 (include)


error: building fontconfig:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+fontconfig
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[fontconfig]+Build+error
Include '[fontconfig] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-05-05-67e17c1782801cf481be9ac0b3765dff3e4bdeb8
    vcpkg-scripts version: a2d8a7cbb 2022-06-01 (2 hours ago)


root@localhost vcpkg]# cat /home/vcpkg/buildtrees/fontconfig/config-x64-linux-dbg-err.log
Traceback (most recent call last):
  File "/home/vcpkg/installed/x64-linux/tools/meson/meson.py", line 26, in <module>
    from mesonbuild import mesonmain
  File "/home/vcpkg/installed/x64-linux/tools/meson/mesonbuild/mesonmain.py", line 28, in <module>
    from . import mesonlib
  File "/home/vcpkg/installed/x64-linux/tools/meson/mesonbuild/mesonlib/__init__.py", line 21, in <module>
    from .universal import *
  File "/home/vcpkg/installed/x64-linux/tools/meson/mesonbuild/mesonlib/universal.py", line 17
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
```

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by Adela0814** [comment]
@chuckypt Can you please add `vcpkg_find_acquire_program(PYTHON3)` to `vcpkg\ports\fontconfig.portfile.cmake` and try again.

**Comment by chuckypt** [comment]
> @chuckypt Can you please add `vcpkg_find_acquire_program(PYTHON3)` to `vcpkg\ports\fontconfig.portfile.cmake` and try again.

i find profile.cmake   in  vcpkg\ports\fontconfig 
 and  at first line  like this:
----------------------------------
 [root@localhost fontconfig]# cat portfile.cmake | more
vcpkg_find_acquire_program(PYTHON3)

set(FONTCONFIG_VERSION 2.14.0)
vcpkg_from_gitlab(
    GITLAB_URL https://gitlab.freedesktop.org
    OUT_SOURCE_PATH SOURCE_PATH
    REPO fontconfig/fontconfig
    REF ${FONTCONFIG_VERSION}
    SHA512 0f36fa503c0277750ff253534f9305c9b4c86fd0d88a470e3b666080951714c51f13a69eecab382d0a7883a07494fc71730213e6086194a92aa5dfc075789e85
    HEAD_REF master
    PATCHES
        no-etc-symlinks.patch
        libgetopt.patch
)
-------------------------

i try again  ./vcpkg install fontconfig:x64-linux
 
[root@localhost vcpkg]# ./vcpkg install fontconfig
Computing installation plan...
The following packages will be built and installed:
    fontconfig[core]:x64-linux -> 2.14.0#2
Detecting compiler hash for triplet x64-linux...
Restored 0 packages from /root/.cache/vcpkg/archives in 4.692 us. Use --debug to see more details.
Installing 1/1 fontconfig:x64-linux...
Building fontconfig[core]:x64-linux...
-- Using cached fontconfig-fontconfig-2.14.0.tar.gz.
-- Cleaning sources at /home/vcpkg/buildtrees/fontconfig/src/2.14.0-523cc719dc.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/vcpkg/downloads/fontconfig-fontconfig-2.14.0.tar.gz
-- Applying patch no-etc-symlinks.patch
-- Applying patch libgetopt.patch
-- Using source at /home/vcpkg/buildtrees/fontconfig/src/2.14.0-523cc719dc.clean
-- Getting CMake variables for x64-linux-dbg
-- Getting CMake variables for x64-linux-rel
-- Configuring x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:128 (message):
    Command failed: /usr/bin/python3 /home/vcpkg/installed/x64-linux/tools/meson/meson.py -Ddoc=disabled -Dcache-build=disabled -Dtests=disabled --buildtype plain --backend ninja --wrap-mode nodownload --native /home/vcpkg/buildtrees/fontconfig/meson-native-x64-linux.log --default-library static --libdir lib --native /home/vcpkg/buildtrees/fontconfig/meson-native-x64-linux-debug.log -Ddebug=true --prefix /home/vcpkg/packages/fontconfig_x64-linux/debug --includedir ../include -Dcmake_prefix_path=['/home/vcpkg/installed/x64-linux/debug','/home/vcpkg/installed/x64-linux'] /home/vcpkg/buildtrees/fontconfig/src/2.14.0-523cc719dc.clean
    Working Directory: /home/vcpkg/buildtrees/fontconfig/x64-linux-dbg
    Error code: 1
    See logs for more information:
      /home/vcpkg/buildtrees/fontconfig/config-x64-linux-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_meson.cmake:470 (vcpkg_execute_required_process)
  ports/fontconfig/portfile.cmake:18 (vcpkg_configure_meson)
  scripts/ports.cmake:146 (include)


error: building fontconfig:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+fontconfig
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[fontconfig]+Build+error
Include '[fontconfig] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-05-05-67e17c1782801cf481be9ac0b3765dff3e4bdeb8
    vcpkg-scripts version: a2d8a7cbb 2022-06-01 (7 hours ago)
-----------------------


can  you help me ~~

**Comment by Adela0814** [comment]
Sorry, I missed this. can you please provide the failure logs?
`/home/vcpkg/buildtrees/fontconfig/config-x64-linux-dbg-out.log`

**Comment by chuckypt** [comment]
> Sorry, I missed this. can you please provide the failure logs? `/home/vcpkg/buildtrees/fontconfig/config-x64-linux-dbg-out.log`

[root@localhost vcpkg]# cat /home/vcpkg/buildtrees/fontconfig/config-x64-linux-dbg-err.log 
Traceback (most recent call last):
  File "/home/vcpkg/installed/x64-linux/tools/meson/meson.py", line 26, in <module>
    from mesonbuild import mesonmain
  File "/home/vcpkg/installed/x64-linux/tools/meson/mesonbuild/mesonmain.py", line 28, in <module>
    from . import mesonlib
  File "/home/vcpkg/installed/x64-linux/tools/meson/mesonbuild/mesonlib/__init__.py", line 21, in <module>
    from .universal import *
  File "/home/vcpkg/installed/x64-linux/tools/meson/mesonbuild/mesonlib/universal.py", line 17
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
[root@localhost vcpkg]#

**Comment by chuckypt** [comment]
> 

[root@localhost vcpkg]# cat /home/vcpkg/buildtrees/fontconfig/config-x64-linux-dbg-out.log 
[root@localhost vcpkg]# 

~~ it empty

**Comment by Adela0814** [comment]
Actually I want to confirm your python version.

**Comment by chuckypt** [comment]
> Actually I want to confirm your python version.

[root@localhost fontconfig]# python3 -V
Python 3.6.8

**Comment by Adela0814** [comment]
Please try Python>=3.7

**Comment by chuckypt** [comment]
> Please try Python>=3.7

it work~  thannk you~~~
