### ISSUE TITLE
[magic-enum] Needs to be patched from upstream source

### ISSUE THREAD

**Issue by johnco3** [microsoft/vcpkg#25045]
Library name: magic-enum

New version number: not sure

[Other information that may be useful (release notes, etc...)
(1) The following patch from the magic-enum repo needs to be included:
Not including the following magic-enum commit causes a build error
Fix compilation error, when including magic_enum after windows.h 

(2) Also, in magic_enum.hpp line 763 causes a global variable collision with std::chrono, the auto created variable `last` collides with last defined in the chrono package.  This has not been fixed upstream yet: both issues are probably due to my header include order (which should not matter).  The fix for this was to rename the variable in line 763 from `last` to `lastxx`.  i.e.: `for (auto first = values.begin() + Page, lastxx = values.begin() + Page + values_to; first != lastxx; )`

**Comment by JonLiu1993** [comment]
@johnco3, Thanks for posting this issue, Can you provide me with your error log and steps to reproduce?

**Comment by JonLiu1993** [comment]
I think this issue needs upstrem to confirm, @[Neargye](https://github.com/Neargye), could you please take a look?

**Comment by johnco3** [comment]
@Neargye - This needs the patch indicated below along with the [Fix compilation error, when including magic_enum after windows.h](https://github.com/Neargye/magic_enum/commit/6956c560330e21c7673ba8d5e43d53b71a7fce48) patch you already submitted upstream in order to have a clean compile.  Not sure how the work flow is in github - it might be easiest to fix the upstream magic_enum and pull the changes in here.

```
--- ./orig/magic_enum.hpp	2022-06-13 13:53:58.403851100 -0400
+++ ./include/magic_enum.hpp	2022-06-13 11:41:08.241855500 -0400
@@ -760,7 +760,7 @@
 
   std::array<switch_t, 256> result{};
   auto fill = result.begin();
-  for (auto first = values.begin() + Page, last = values.begin() + Page + values_to; first != last; ) {
+  for (auto first = values.begin() + Page, lastxx = values.begin() + Page + values_to; first != lastxx; ) {
     *fill++ = hash_v<Hash>(*first++);
   }
```

**Comment by JonLiu1993** [comment]
@johnco3, Could you please commit a pr fix this issue?

**Comment by Neargye** [comment]
Unfortunately, this patch does not fix the problem, but only masks it.
The real reason is that for some reason the local variable conflicts with std::chrono::last.

**Comment by JonLiu1993** [comment]
@Neargye ,Do you have any repair plans?

**Comment by BullyWiiPlaza** [comment]
It seems like the vcpkg port has been not updated yet: https://github.com/microsoft/vcpkg/tree/bae8f8c7d837c631ca72daec4b14e243824135a5/ports/magic-enum
The compilation error fixed by commit https://github.com/Neargye/magic_enum/commit/6956c560330e21c7673ba8d5e43d53b71a7fce48 is not available yet in vcpkg. Pasting the `magic_enum.hpp` header source code from GitHub over the one installed by vcpkg works.

**Comment by Neargye** [comment]
https://github.com/microsoft/vcpkg/pull/26166
