### ISSUE TITLE
[glib] build failure on x64-linux

### ISSUE THREAD

**Issue by btwostealth** [microsoft/vcpkg#25043]
**Host Environment**
- OS: [e.g. Linux 22.04]
- Compiler: gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0

**To Reproduce**
`sudo vcpkg install opencv:x64-linux`

**Failure logs**
```diff
error: building glib:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+glib
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[glib]+Build+error
Include '[glib] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-05-05-67e17c1782801cf481be9ac0b3765dff3e4bdeb8
    vcpkg-scripts version: unknown
```

**Additional context**
I have the similar error. Tried to install vcpkg on Ubuntu 22.04 from this [tutorial](https://lindevs.com/install-vcpkg-on-ubuntu/), and install opencv with `sudo vcpkg install opencv:x64-linux`. However, it is returning, 

Just to test, I tried to install another library `glm`, and it worked fine `sudo vcpkg install glm:x64-Linux`.

**Comment by LilyWangLL** [comment]
Please provide the error log file.

**Comment by btwostealth** [comment]
Hi @LilyWangLL , It is working now. I actually forgot how I solved the problem. Closing the issue. thanks.
