### ISSUE TITLE
[icu] Build error

### ISSUE THREAD

**Issue by 18922271727** [microsoft/vcpkg#25054]
**Host Environment**
- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**
`./vcpkg install xxxx`

**Failure logs**
-Cut and paste the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by autoantwort** [comment]
Please fill out the issue template

**Comment by Cheney-W** [comment]
Please provide the specific environment for you to reproduce the problem, such as compiler version, vcpkg version, specific vcpkg command, and the error log.

**Comment by Cheney-W** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
