### ISSUE TITLE
[Install] bootstrap-vcpkg.bat cannot install in a path with single quote

### ISSUE THREAD

**Issue by Dynesshely** [microsoft/vcpkg#25058]
**Describe the bug**
When installing vcpkg accroding to [official tutorial](https://github.com/microsoft/vcpkg#quick-start-windows) , I tried execute `.\vcpkg\bootstrap-vcpkg.bat` after clone this repo, and it gave me 
![image](https://user-images.githubusercontent.com/50760269/171910361-84864b71-8e8d-4ab8-8edd-0cc4558ea070.png)
```
PS E:\Development\Projects\Catrol's-Forks> .\vcpkg\bootstrap-vcpkg.bat
字符串缺少终止符: '。
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : TerminatorExpectedAtEndOfString
```

**Environment**
- OS: Windows 11 21H2 22000.708 (Windows Experience Pack 1000.22000.708.0)

**To Reproduce**
1. cd D:\xxx'xxx\
2. git clone git@github.com:microsoft/vcpkg.git
3. ./vcpkg/bootstrap-vcpkg.bat

**Expected behavior**
Install successfully.

**Failure logs**
- I think this is no need.

**Comment by Neumann-A** [comment]
You will probably run into more issues with that than just bootstrap. vcpkg_configure_make and vcpkg_configure_meson probably don't correctly handle that.

**Comment by Dynesshely** [comment]
I mean, maybe we need give a more clear descr for example
"The install path can't contains single quote"

**Comment by Adela0814** [comment]
@BillyONeal Could you please take a look.

**Comment by BillyONeal** [comment]
@Adela0814 Seems like a legitimate bug but I don't expect it will be fixed anytime soon

**Comment by BillyONeal** [comment]
> @Adela0814 Seems like a legitimate bug but I don't expect it will be fixed anytime soon

2024 Bill understands that this is now much easier to fix. Lots of ports will still hate the single quote but we can at least fix bootstrap.
