### ISSUE TITLE
[New Port Request] Marian

### ISSUE THREAD

**Issue by Shatur** [microsoft/vcpkg#25050]
Library name: Marian

Library description: an efficient, free Neural Machine Translation framework written in pure C++ with minimal dependencies. It is mainly being developed by the [Microsoft Translator](http://translator.microsoft.com/) team. Many academic (most notably the University of Edinburgh and in the past the Adam Mickiewicz University in Poznań) and commercial [contributors](https://github.com/marian-nmt/marian-dev/graphs/contributors) help with its development. Also used by [Mozilla Project Bergamot](https://blog.mozilla.org/en/mozilla/local-translation-add-on-project-bergamot/).

Source repository URL: https://github.com/marian-nmt/marian

Project homepage https://marian-nmt.github.io/

**Comment by LilyWangLL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
