### ISSUE TITLE
building libiconv:arm64-android failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by MCSQNXA** [microsoft/vcpkg#25052]
Hello, I'm compiling the x86 windows architecture dependency library normally, but I can't compile the arm64 Android architecture dependency library, and there are no logs

C:\Users\Administrator>vcpkg install libiconv:arm64-android
Computing installation plan...
The following packages will be built and installed:
    libiconv[core]:arm64-android -> 1.16#13
Detecting compiler hash for triplet arm64-android...
Restored 0 packages from C:\Users\Administrator\AppData\Local\vcpkg\archives in 2.499 ms. Use --debug to see more details.
Installing 1/1 libiconv:arm64-android...
Building libiconv[core]:arm64-android...
-- Using community triplet arm64-android. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: C:\Microsoft\Vcpkg\triplets\community\arm64-android.cmake
-- Using cached libiconv-1.16.tar.gz.
-- Cleaning sources at C:/Microsoft/Vcpkg/buildtrees/libiconv/src/1.16-b0c41d3469.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Microsoft/Vcpkg/downloads/libiconv-1.16.tar.gz
-- Applying patch 0002-Config-for-MSVC.patch
-- Applying patch 0003-Add-export.patch
-- Applying patch 0004-ModuleFileName.patch
-- Using source at C:/Microsoft/Vcpkg/buildtrees/libiconv/src/1.16-b0c41d3469.clean
-- Getting CMake variables for arm64-android
-- Using cached msys-mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst.
-- Using msys root at C:/Microsoft/Vcpkg/downloads/tools/msys2/9a1ec3f33446b195
-- Configuring arm64-android-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:128 (message):
    Command failed: --noprofile --norc --debug -c "V=1 ./../src/1.16-b0c41d3469.clean/configure  \"--enable-extra-encodings\" \"--without-libiconv-prefix\" \"--without-libintl-prefix\" \"--disable-silent-rules\" \"--verbose\" \"--disable-shared\" \"--enable-static\" \"--prefix=/C/Microsoft/Vcpkg/installed/arm64-android/debug\" \"--bindir=\\${prefix}/../tools/libiconv/debug/bin\" \"--sbindir=\\${prefix}/../tools/libiconv/debug/sbin\" \"--libdir=\\${prefix}/lib\" \"--includedir=\\${prefix}/../include\" \"--datarootdir=\\${prefix}/share/libiconv\""
    Working Directory: C:/Microsoft/Vcpkg/buildtrees/libiconv/arm64-android-dbg
    Error code: 系统找不到指定的文件。
    See logs for more information:

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:799 (vcpkg_execute_required_process)
  ports/libiconv/portfile.cmake:29 (vcpkg_configure_make)
  scripts/ports.cmake:146 (include)

error: building libiconv:arm64-android failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libiconv
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[libiconv]+Build+error
Include '[libiconv] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-05-05-67e17c1782801cf481be9ac0b3765dff3e4bdeb8
    vcpkg-scripts version: unknown

**Comment by LilyWangLL** [comment]
This issue hasn’t been updated in 3 months, if it is still an issue, please reopen this issue.
