### ISSUE TITLE
[glib:arm64-linux] build failure

### ISSUE THREAD

**Issue by kexuedaishu** [microsoft/vcpkg#25064]
**Host Environment**
- OS: Linux version 4.19.90-24.4.v2101.ky10.aarch64

**To Reproduce**
`./vcpkg install glib:arm64-linux`

**Failure logs**
In the error log: "vcpkg/buildtrees/glib/config-arm64-linux-dbg-err.log" it shows:
OSError: [Errno 8] Exec format error: '/shared/vcpkg/downloads/tools/ninja/1.10.2-linux/ninja'

==============
I think the issue should be with the version of ninja, maybe not even an accepted version in aarch64.

**Comment by LilyWangLL** [comment]
This issue hasn’t been updated in 3 months, if it is still an issue, please reopen this issue.
